LLVM: lib/TargetParser/AArch64TargetParser.cpp File Reference
AArch64TargetParser.cpp File Reference
#include "llvm/TargetParser/AArch64TargetParser.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/ARMTargetParserCommon.h"
#include "llvm/TargetParser/Triple.h"
#include <cctype>
#include <vector>
#include "llvm/TargetParser/AArch64TargetParserDef.inc"
Macros
#define DEBUG_TYPE "target-parser"
#define EMIT_FMV_INFO
Functions
static unsigned checkArchVersion (llvm::StringRef Arch)
std::optional< AArch64::FMVInfo > lookupFMVByID (AArch64::ArchExtKind ExtID)
const llvm::AArch64::ExtensionInfo & lookupExtensionByID (llvm::AArch64::ArchExtKind ExtID)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "target-parser"
Definition at line 23 of file AArch64TargetParser.cpp.
EMIT_FMV_INFO
#define EMIT_FMV_INFO
Definition at line 27 of file AArch64TargetParser.cpp.
Function Documentation
checkArchVersion()
unsigned checkArchVersion (llvm::StringRef Arch) static
Definition at line 30 of file AArch64TargetParser.cpp.
References llvm::StringRef::size().
Referenced by llvm::AArch64::parseArch().
lookupExtensionByID()
const llvm::AArch64::ExtensionInfo & lookupExtensionByID (llvm::AArch64::ArchExtKind ExtID)
Definition at line 245 of file AArch64TargetParser.cpp.
References E(), and llvm_unreachable.
Referenced by llvm::AArch64::ExtensionSet::disable(), and llvm::AArch64::ExtensionSet::enable().
lookupFMVByID()
std::optional< AArch64::FMVInfo > lookupFMVByID (AArch64::ArchExtKind ExtID)
Definition at line 51 of file AArch64TargetParser.cpp.
References llvm::AArch64::getFMVInfo(), and Info.
Referenced by llvm::AArch64::getFMVPriority().