LLVM: lib/Target/AArch64/AArch64TargetObjectFile.cpp File Reference
AArch64TargetObjectFile.cpp File Reference
#include "AArch64TargetObjectFile.h"
#include "AArch64TargetMachine.h"
#include "MCTargetDesc/AArch64MCAsmInfo.h"
#include "MCTargetDesc/AArch64TargetStreamer.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCValue.h"
Functions
template<typename MachineModuleInfoTarget>
static MCSymbol * getAuthPtrSlotSymbolHelper (MCContext &Ctx, const TargetMachine &TM, MachineModuleInfo *MMI, MachineModuleInfoTarget &TargetMMI, const MCSymbol *RawSym, AArch64PACKey::ID Key, uint16_t Discriminator)
static bool isExecuteOnlyFunction (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM)
Function Documentation
getAuthPtrSlotSymbolHelper()
template<typename MachineModuleInfoTarget> MCSymbol * getAuthPtrSlotSymbolHelper (MCContext & Ctx, const TargetMachine & TM, MachineModuleInfo * MMI, MachineModuleInfoTarget & TargetMMI, const MCSymbol * RawSym, AArch64PACKey::ID Key, uint16_t Discriminator) static
Definition at line 124 of file AArch64TargetObjectFile.cpp.
References llvm::AArch64PACKeyIDToString(), llvm::AArch64AuthMCExpr::create(), llvm::MCSymbolRefExpr::create(), DL, llvm::Module::getDataLayout(), llvm::MachineModuleInfo::getModule(), llvm::MCSymbol::getName(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::AArch64_ELFTargetObjectFile::getAuthPtrSlotSymbol(), and llvm::AArch64_MachoTargetObjectFile::getAuthPtrSlotSymbol().
isExecuteOnlyFunction()
bool isExecuteOnlyFunction (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM) static
Definition at line 164 of file AArch64TargetObjectFile.cpp.
References llvm::dyn_cast(), and F.
Referenced by llvm::AArch64_ELFTargetObjectFile::getExplicitSectionGlobal(), llvm::ARMElfTargetObjectFile::getExplicitSectionGlobal(), llvm::AArch64_ELFTargetObjectFile::SelectSectionForGlobal(), and llvm::ARMElfTargetObjectFile::SelectSectionForGlobal().