LLVM: lib/Target/AMDGPU/AMDGPUCallLowering.cpp File Reference
AMDGPUCallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "AMDGPUCallLowering.h"
#include "AMDGPU.h"
#include "AMDGPULegalizerInfo.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
Macros
#define DEBUG_TYPE "amdgpu-call-lowering"
Functions
static ISD::NodeType extOpcodeToISDExtOpcode (unsigned MIOpc)
static void allocateHSAUserSGPRs (CCState &CCInfo, MachineIRBuilder &B, MachineFunction &MF, const SIRegisterInfo &TRI, SIMachineFunctionInfo &Info)
static std::pair< CCAssignFn *, CCAssignFn * > getAssignFnsForCC (CallingConv::ID CC, const SITargetLowering &TLI)
Returns a pair containing the fixed CCAssignFn and the vararg CCAssignFn for CC.
static unsigned getCallOpcode (const MachineFunction &CallerF, bool IsIndirect, bool IsTailCall, bool IsWave32, CallingConv::ID CC, bool IsDynamicVGPRChainCall=false)
static bool addCallTargetOperands (MachineInstrBuilder &CallInst, MachineIRBuilder &MIRBuilder, AMDGPUCallLowering::CallLoweringInfo &Info, bool IsDynamicVGPRChainCall=false)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file AMDGPUCallLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-call-lowering"
Definition at line 26 of file AMDGPUCallLowering.cpp.
Function Documentation
addCallTargetOperands()
bool addCallTargetOperands (MachineInstrBuilder & CallInst, MachineIRBuilder & MIRBuilder, AMDGPUCallLowering::CallLoweringInfo & Info, bool IsDynamicVGPRChainCall = false) static
Definition at line 984 of file AMDGPUCallLowering.cpp.
References llvm::MachineIRBuilder::buildGlobalValue(), llvm::GlobalValue::getAddressSpace(), Info, llvm::LLT::pointer(), and Ptr.
Referenced by llvm::AMDGPUCallLowering::lowerCall(), and llvm::AMDGPUCallLowering::lowerTailCall().
allocateHSAUserSGPRs()
void allocateHSAUserSGPRs (CCState & CCInfo, MachineIRBuilder & B, MachineFunction & MF, const SIRegisterInfo & TRI, SIMachineFunctionInfo & Info) static
Definition at line 448 of file AMDGPUCallLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AllocateReg(), B(), llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::MachineFunction::getRegInfo(), llvm::GCNUserSGPRUsageInfo::hasDispatchID(), llvm::GCNUserSGPRUsageInfo::hasDispatchPtr(), llvm::GCNUserSGPRUsageInfo::hasFlatScratchInit(), llvm::GCNUserSGPRUsageInfo::hasKernargSegmentPtr(), llvm::GCNUserSGPRUsageInfo::hasPrivateSegmentBuffer(), llvm::GCNUserSGPRUsageInfo::hasPrivateSegmentSize(), llvm::GCNUserSGPRUsageInfo::hasQueuePtr(), Info, MRI, llvm::LLT::pointer(), and TRI.
Referenced by llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel().
extOpcodeToISDExtOpcode()
ISD::NodeType extOpcodeToISDExtOpcode (unsigned MIOpc) static
Definition at line 262 of file AMDGPUCallLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm_unreachable, llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
getAssignFnsForCC()
std::pair< CCAssignFn *, CCAssignFn * > getAssignFnsForCC (CallingConv::ID CC, const SITargetLowering & TLI) static
Returns a pair containing the fixed CCAssignFn and the vararg CCAssignFn for CC.
Definition at line 957 of file AMDGPUCallLowering.cpp.
References llvm::AMDGPUTargetLowering::CCAssignFnForCall().
getCallOpcode()
unsigned getCallOpcode (const MachineFunction & CallerF, bool IsIndirect, bool IsTailCall, bool IsWave32, CallingConv::ID CC, bool IsDynamicVGPRChainCall = false) static
Definition at line 961 of file AMDGPUCallLowering.cpp.
References llvm::CallingConv::AMDGPU_Gfx, assert(), and llvm::AMDGPU::isChainCC().