LLVM: lib/Target/AMDGPU/AMDGPUExportKernelRuntimeHandles.cpp File Reference
AMDGPUExportKernelRuntimeHandles.cpp File Reference
#include "AMDGPUExportKernelRuntimeHandles.h"
#include "AMDGPU.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "amdgpu-export-kernel-runtime-handles"
Functions
INITIALIZE_PASS (AMDGPUExportKernelRuntimeHandlesLegacy, DEBUG_TYPE, "Externalize enqueued block runtime handles", false, false) ModulePass *llvm
static bool exportKernelRuntimeHandles (Module &M)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-export-kernel-runtime-handles"
Definition at line 29 of file AMDGPUExportKernelRuntimeHandles.cpp.
Function Documentation
exportKernelRuntimeHandles()
bool exportKernelRuntimeHandles (Module & M) static
Definition at line 60 of file AMDGPUExportKernelRuntimeHandles.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, llvm::cast(), Changed, llvm::dyn_cast(), llvm::GlobalValue::ExternalLinkage, F, llvm::MDNode::getOperand(), and llvm::GlobalValue::ProtectedVisibility.
Referenced by llvm::AMDGPUExportKernelRuntimeHandlesPass::run().
INITIALIZE_PASS()
INITIALIZE_PASS (AMDGPUExportKernelRuntimeHandlesLegacy , DEBUG_TYPE , "Externalize enqueued block runtime handles" , false , false)
Definition at line 53 of file AMDGPUExportKernelRuntimeHandles.cpp.
References llvm::createAMDGPUExportKernelRuntimeHandlesLegacyPass(), and DEBUG_TYPE.