LLVM: lib/Target/AMDGPU/AMDGPUGlobalISelUtils.cpp File Reference
AMDGPUGlobalISelUtils.cpp File Reference
#include "AMDGPUGlobalISelUtils.h"
#include "AMDGPURegisterBankInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/CodeGen/GlobalISel/GISelValueTracking.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGenTypes/LowLevelType.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
Functions
static LLT getReadAnyLaneSplitTy (LLT Ty)
static Register buildReadAnyLane (MachineIRBuilder &B, Register VgprSrc, const RegisterBankInfo &RBI)
static void unmergeReadAnyLane (MachineIRBuilder &B, SmallVectorImpl< Register > &SgprDstParts, LLT UnmergeTy, Register VgprSrc, const RegisterBankInfo &RBI)
Function Documentation
buildReadAnyLane()
Register buildReadAnyLane (MachineIRBuilder & B, Register VgprSrc, const RegisterBankInfo & RBI) static
Definition at line 134 of file AMDGPUGlobalISelUtils.cpp.
References B(), getReadAnyLaneSplitTy(), getReg(), llvm::RegisterBankInfo::getRegBank(), and unmergeReadAnyLane().
getReadAnyLaneSplitTy()
LLT getReadAnyLaneSplitTy (LLT Ty) static
Definition at line 107 of file AMDGPUGlobalISelUtils.cpp.
References llvm::LLT::fixed_vector(), llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), and llvm::LLT::scalar().
Referenced by buildReadAnyLane(), and llvm::AMDGPU::buildReadAnyLane().
unmergeReadAnyLane()
void unmergeReadAnyLane (MachineIRBuilder & B, SmallVectorImpl< Register > & SgprDstParts, LLT UnmergeTy, Register VgprSrc, const RegisterBankInfo & RBI) static
Definition at line 123 of file AMDGPUGlobalISelUtils.cpp.
References B(), llvm::AMDGPU::buildReadAnyLane(), llvm::RegisterBankInfo::getRegBank(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by buildReadAnyLane(), and llvm::AMDGPU::buildReadAnyLane().