LLVM: lib/Target/AMDGPU/AMDGPUAlwaysInlinePass.cpp File Reference
AMDGPUAlwaysInlinePass.cpp File Reference
This pass marks all internal functions as always_inline and creates duplicates of all other functions and marks the duplicates as always_inline.
#include "AMDGPU.h"
#include "AMDGPUTargetMachine.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/CodeGen/CommandFlags.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
Functions
static INITIALIZE_PASS(AMDGPUAlwaysInline, "amdgpu-always-inline", "AMDGPU Inline All Functions", false, false) char AMDGPUAlwaysInline void recursivelyVisitUsers (GlobalValue &GV, SmallPtrSetImpl< Function * > &FuncsToAlwaysInline)
static bool alwaysInlineImpl (Module &M, bool GlobalOpt)
Detailed Description
This pass marks all internal functions as always_inline and creates duplicates of all other functions and marks the duplicates as always_inline.
Definition in file AMDGPUAlwaysInlinePass.cpp.
Function Documentation
alwaysInlineImpl()
bool alwaysInlineImpl (Module & M, bool GlobalOpt) static
Definition at line 89 of file AMDGPUAlwaysInlinePass.cpp.
References A(), Changed, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dyn_cast(), llvm::SmallPtrSetImplBase::empty(), llvm::AMDGPUTargetMachine::EnableFunctionCalls, llvm::AMDGPUTargetMachine::EnableLowerModuleLDS, F, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::GlobalValue::InternalLinkage, llvm::AMDGPUAS::LOCAL_ADDRESS, recursivelyVisitUsers(), and llvm::AMDGPUAS::REGION_ADDRESS.
Referenced by llvm::AMDGPUAlwaysInlinePass::run().
recursivelyVisitUsers()
INITIALIZE_PASS(AMDGPUAlwaysInline, "amdgpu-always-inline", "AMDGPU Inline All Functions", false, false) char AMDGPUAlwaysInline void recursivelyVisitUsers (GlobalValue & GV, SmallPtrSetImpl< Function * > & FuncsToAlwaysInline) static
Definition at line 56 of file AMDGPUAlwaysInlinePass.cpp.
References llvm::append_range(), llvm::dyn_cast(), F, I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::AMDGPU::isEntryFunctionCC(), and recursivelyVisitUsers().
Referenced by alwaysInlineImpl(), and recursivelyVisitUsers().