LLVM: lib/Target/AMDGPU/AMDGPULowerKernelArguments.cpp File Reference
AMDGPULowerKernelArguments.cpp File Reference
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "amdgpu-lower-kernel-arguments"
Functions
static BasicBlock::iterator getInsertPt (BasicBlock &BB)
static bool lowerKernelArguments (Function &F, const TargetMachine &TM)
INITIALIZE_PASS_BEGIN (AMDGPULowerKernelArguments, DEBUG_TYPE, "AMDGPU Lower Kernel Arguments", false, false) INITIALIZE_PASS_END(AMDGPULowerKernelArguments
Variables
DEBUG_TYPE
AMDGPU Lower Kernel Arguments
AMDGPU Lower Kernel false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-lower-kernel-arguments"
Definition at line 24 of file AMDGPULowerKernelArguments.cpp.
Function Documentation
getInsertPt()
BasicBlock::iterator getInsertPt (BasicBlock & BB) static
Definition at line 47 of file AMDGPULowerKernelArguments.cpp.
References llvm::dyn_cast(), E(), llvm::BasicBlock::end(), llvm::BasicBlock::getFirstInsertionPt(), and llvm::AllocaInst::isStaticAlloca().
Referenced by lowerKernelArguments().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPULowerKernelArguments , DEBUG_TYPE , "AMDGPU Lower Kernel Arguments" , false , false)
References DEBUG_TYPE.
lowerKernelArguments()
bool lowerKernelArguments (Function & F, const TargetMachine & TM) static
Definition at line 61 of file AMDGPULowerKernelArguments.cpp.
References llvm::CallBase::addRetAttr(), llvm::alignDown(), llvm::alignTo(), llvm::CallingConv::AMDGPU_KERNEL, llvm::commonAlignment(), llvm::MDBuilder::createConstant(), llvm::MDBuilder::createRange(), DL, llvm::dyn_cast(), F, llvm::FixedVectorType::get(), llvm::MDNode::get(), getInsertPt(), llvm::Type::getInt32Ty(), llvm::Type::getIntNTy(), llvm::Value::getType(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithDereferenceableBytes(), llvm::isa(), llvm::Type::isAggregateType(), llvm::AMDGPUAS::LOCAL_ADDRESS, Range, llvm::AMDGPUAS::REGION_ADDRESS, llvm::Value::replaceAllUsesWith(), and Size.
Referenced by llvm::AMDGPULowerKernelArgumentsPass::run().
Variable Documentation
Arguments
AMDGPU Lower Kernel Arguments
Definition at line 253 of file AMDGPULowerKernelArguments.cpp.
Referenced by llvm::VPWidenIntrinsicRecipe::computeCost(), llvm::MDBuilder::createCallbackEncoding(), llvm::coro::createMustTailCall(), llvm::PMTopLevelManager::dumpArguments(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::lookupBuiltin(), llvm::coro::normalizeCoroutine(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), and llvm::logicalview::LVTypeVisitor::visitKnownRecord().
DEBUG_TYPE
DEBUG_TYPE
Definition at line 253 of file AMDGPULowerKernelArguments.cpp.
false
AMDGPU Lower Kernel false
Definition at line 254 of file AMDGPULowerKernelArguments.cpp.