LLVM: lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp File Reference
AMDGPUHSAMetadataStreamer.cpp File Reference
AMDGPU HSA Metadata Streamer.
#include "AMDGPUHSAMetadataStreamer.h"
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "MCTargetDesc/AMDGPUTargetStreamer.h"
#include "SIMachineFunctionInfo.h"
#include "SIProgramInfo.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::AMDGPU
namespace llvm::AMDGPU::HSAMD
Functions
static std::pair< Type *, Align > getArgumentTypeAlign (const Argument &Arg, const DataLayout &DL)
static std::string getEnqueuedBlockSymbolName (const AMDGPUTargetMachine &TM, const Function &EnqueuedBlock)
Find the mangled symbol name for the runtime handle for EnqueuedBlock.
Variables
static cl::opt< bool > llvm::DumpHSAMetadata ("amdgpu-dump-hsa-metadata", cl::desc("Dump AMDGPU HSA Metadata"))
static cl::opt< bool > llvm::VerifyHSAMetadata ("amdgpu-verify-hsa-metadata", cl::desc("Verify AMDGPU HSA Metadata"))
Detailed Description
AMDGPU HSA Metadata Streamer.
Definition in file AMDGPUHSAMetadataStreamer.cpp.
Function Documentation
getArgumentTypeAlign()
std::pair< Type *, Align > getArgumentTypeAlign (const Argument & Arg, const DataLayout & DL) static
Definition at line 28 of file AMDGPUHSAMetadataStreamer.cpp.
References DL, llvm::Argument::getParamAlign(), llvm::Argument::getParamByRefType(), llvm::Value::getType(), and llvm::Argument::hasByRefAttr().
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelArg().
getEnqueuedBlockSymbolName()
std::string getEnqueuedBlockSymbolName (const AMDGPUTargetMachine & TM, const Function & EnqueuedBlock) static
Find the mangled symbol name for the runtime handle for EnqueuedBlock.
Definition at line 44 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::GlobalObject::getMetadata(), and llvm::MDNode::getOperand().
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelAttrs().