LLVM: lib/Target/BPF/BPFAsmPrinter.cpp File Reference
BPFAsmPrinter.cpp File Reference
#include "BPF.h"
#include "BPFInstrInfo.h"
#include "BPFMCInstLower.h"
#include "BTFDebug.h"
#include "MCTargetDesc/BPFInstPrinter.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
INITIALIZE_PASS (BPFAsmPrinter, "bpf-asm-printer", "BPF Assembly Printer", false, false) extern "C" LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFAsmPrinter()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 34 of file BPFAsmPrinter.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (BPFAsmPrinter , "bpf-asm-printer" , "BPF Assembly Printer" , false , false)
Definition at line 155 of file BPFAsmPrinter.cpp.
References llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, X, and Y.