LLVM: lib/Target/BPF/BPFPreserveStaticOffset.cpp File Reference
BPFPreserveStaticOffset.cpp File Reference
#include "BPF.h"
#include "BPFCORE.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsBPF.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "bpf-preserve-static-offset"
Functions
static bool isIntrinsicCall (Value *I, Intrinsic::ID Id)
static bool isPreserveStaticOffsetCall (Value *I)
static CallInst * isGEPAndLoad (Value *I)
static CallInst * isGEPAndStore (Value *I)
template<class T = Instruction>
static DebugLoc mergeDebugLocs (SmallVector< T * > &Insns)
static CallInst * makeIntrinsicCall (Module *M, Intrinsic::BPFIntrinsics Intrinsic, ArrayRef< Type * > Types, ArrayRef< Value * > Args)
static void setParamElementType (CallInst *Call, unsigned ArgNo, Type *Type)
static void setParamReadNone (CallInst *Call, unsigned ArgNo)
static void setParamReadOnly (CallInst *Call, unsigned ArgNo)
static void setParamWriteOnly (CallInst *Call, unsigned ArgNo)
template<class T = std::disjunction<LoadInst, StoreInst>>
static void fillCommonArgs (LLVMContext &C, SmallVector< Value * > &Args, GEPChainInfo &GEP, T *Insn)
static Instruction * makeGEPAndLoad (Module *M, GEPChainInfo &GEP, LoadInst *Load)
static Instruction * makeGEPAndStore (Module *M, GEPChainInfo &GEP, StoreInst *Store)
static unsigned getOperandAsUnsigned (CallInst *Call, unsigned ArgNo)
static GetElementPtrInst * reconstructGEP (CallInst *Call, int Delta)
template<class T = std::disjunction<LoadInst, StoreInst>>
static void reconstructCommon (CallInst *Call, GetElementPtrInst *GEP, T *Insn, int Delta)
static bool isZero (Value *V)
static bool foldGEPChainAsStructAccess (SmallVector< GetElementPtrInst * > &GEPs, GEPChainInfo &Info)
static bool foldGEPChainAsU8Access (SmallVector< GetElementPtrInst * > &GEPs, GEPChainInfo &Info)
static void reportNonStaticGEPChain (Instruction *Insn)
static bool allZeroIndices (SmallVector< GetElementPtrInst * > &GEPs)
static bool tryToReplaceWithGEPBuiltin (Instruction *LoadOrStoreTemplate, SmallVector< GetElementPtrInst * > &GEPs, Instruction *InsnToReplace)
static bool isPointerOperand (Value *I, User *U)
static bool isInlineableCall (User *U)
static void rewriteAccessChain (Instruction *Insn, SmallVector< GetElementPtrInst * > &GEPs, SmallVector< Instruction * > &Visited, bool AllowPatial, bool &StillUsed)
static void rewriteUses (Instruction *Insn, SmallVector< GetElementPtrInst * > &GEPs, SmallVector< Instruction * > &Visited, bool AllowPatial, bool &StillUsed)
static void removeMarkerCall (Instruction *Marker)
static bool rewriteAccessChain (Instruction *Marker, bool AllowPatial, SmallPtrSetImpl< Instruction * > &RemovedMarkers)
static std::vector< Instruction * > collectPreserveStaticOffsetCalls (Function &F)
bool isPreserveArrayIndex (Value *V)
bool isPreserveStructIndex (Value *V)
bool isPreserveUnionIndex (Value *V)
static void removePAICalls (Instruction *Marker)
static bool rewriteFunction (Function &F, bool AllowPartial)
Variables
static const unsigned GepAndLoadFirstIdxArg = 6
static const unsigned GepAndStoreFirstIdxArg = 7
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bpf-preserve-static-offset"
Definition at line 121 of file BPFPreserveStaticOffset.cpp.
Function Documentation
allZeroIndices()
bool allZeroIndices (SmallVector< GetElementPtrInst * > & GEPs) static
Definition at line 403 of file BPFPreserveStaticOffset.cpp.
References llvm::all_of(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), and GEP.
Referenced by rewriteAccessChain().
collectPreserveStaticOffsetCalls()
std::vector< Instruction * > collectPreserveStaticOffsetCalls (Function & F) static
Definition at line 589 of file BPFPreserveStaticOffset.cpp.
References F, Insn, instructions, and isPreserveStaticOffsetCall().
Referenced by rewriteFunction().
fillCommonArgs()
template<class T = std::disjunction<LoadInst, StoreInst>> void fillCommonArgs (LLVMContext & C, SmallVector< Value * > & Args, GEPChainInfo & GEP, T * Insn) static
Definition at line 207 of file BPFPreserveStaticOffset.cpp.
References llvm::CallingConv::C, GEP, llvm::Type::getInt1Ty(), llvm::Type::getInt8Ty(), Insn, llvm::Log2_64(), and T.
Referenced by makeGEPAndLoad(), and makeGEPAndStore().
foldGEPChainAsStructAccess()
bool foldGEPChainAsStructAccess (SmallVector< GetElementPtrInst * > & GEPs, GEPChainInfo & Info) static
Definition at line 329 of file BPFPreserveStaticOffset.cpp.
References llvm::all_of(), llvm::drop_begin(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::First, GEP, Info, and isZero().
Referenced by tryToReplaceWithGEPBuiltin().
foldGEPChainAsU8Access()
bool foldGEPChainAsU8Access (SmallVector< GetElementPtrInst * > & GEPs, GEPChainInfo & Info) static
Definition at line 368 of file BPFPreserveStaticOffset.cpp.
References llvm::CallingConv::C, DL, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::First, GEP, llvm::Type::getInt8Ty(), Info, and llvm::Offset.
Referenced by tryToReplaceWithGEPBuiltin().
getOperandAsUnsigned()
unsigned getOperandAsUnsigned (CallInst * Call, unsigned ArgNo) static
Definition at line 265 of file BPFPreserveStaticOffset.cpp.
References Call, llvm::dyn_cast(), Int, and llvm::report_fatal_error().
Referenced by reconstructCommon(), and reconstructGEP().
isGEPAndLoad()
CallInst * isGEPAndLoad (Value * I) static
Definition at line 139 of file BPFPreserveStaticOffset.cpp.
References llvm::cast(), I, and isIntrinsicCall().
Referenced by isPointerOperand(), and rewriteAccessChain().
isGEPAndStore()
CallInst * isGEPAndStore (Value * I) static
Definition at line 145 of file BPFPreserveStaticOffset.cpp.
References llvm::cast(), I, and isIntrinsicCall().
Referenced by isPointerOperand(), and rewriteAccessChain().
isInlineableCall()
bool isInlineableCall (User * U) static
Definition at line 445 of file BPFPreserveStaticOffset.cpp.
References Call, and llvm::dyn_cast().
Referenced by rewriteAccessChain(), and rewriteUses().
isIntrinsicCall()
bool isIntrinsicCall (Value * I, Intrinsic::ID Id) static
Definition at line 128 of file BPFPreserveStaticOffset.cpp.
References Call, llvm::dyn_cast(), and I.
Referenced by isGEPAndLoad(), isGEPAndStore(), and isPreserveStaticOffsetCall().
isPointerOperand()
bool isPointerOperand (Value * I, User * U) static
Definition at line 431 of file BPFPreserveStaticOffset.cpp.
References Call, llvm::dyn_cast(), GEP, I, isGEPAndLoad(), and isGEPAndStore().
Referenced by isInterestingPointerComparison(), isInterestingPointerSubtraction(), and rewriteUses().
isPreserveArrayIndex()
bool isPreserveArrayIndex (Value * V)
Definition at line 597 of file BPFPreserveStaticOffset.cpp.
References isIntrinsicCall().
Referenced by removePAICalls().
isPreserveStaticOffsetCall()
bool isPreserveStaticOffsetCall (Value * I) static
Definition at line 135 of file BPFPreserveStaticOffset.cpp.
References I, and isIntrinsicCall().
Referenced by collectPreserveStaticOffsetCalls(), removePAICalls(), rewriteAccessChain(), rewriteAccessChain(), and rewriteUses().
isPreserveStructIndex()
bool isPreserveStructIndex (Value * V)
Definition at line 601 of file BPFPreserveStaticOffset.cpp.
References isIntrinsicCall().
Referenced by removePAICalls().
isPreserveUnionIndex()
bool isPreserveUnionIndex (Value * V)
Definition at line 605 of file BPFPreserveStaticOffset.cpp.
References isIntrinsicCall().
Referenced by removePAICalls().
isZero()
bool isZero (Value * V) static
Definition at line 321 of file BPFPreserveStaticOffset.cpp.
References llvm::dyn_cast().
makeGEPAndLoad()
Instruction * makeGEPAndLoad (Module * M, GEPChainInfo & GEP, LoadInst * Load) static
Definition at line 222 of file BPFPreserveStaticOffset.cpp.
References Call, fillCommonArgs(), GEP, GepAndLoadFirstIdxArg, I, makeIntrinsicCall(), mergeDebugLocs(), setParamElementType(), and setParamReadOnly().
Referenced by tryToReplaceWithGEPBuiltin().
makeGEPAndStore()
Instruction * makeGEPAndStore (Module * M, GEPChainInfo & GEP, StoreInst * Store) static
Definition at line 242 of file BPFPreserveStaticOffset.cpp.
References Call, fillCommonArgs(), GEP, GepAndStoreFirstIdxArg, I, makeIntrinsicCall(), mergeDebugLocs(), setParamElementType(), setParamReadNone(), and setParamWriteOnly().
Referenced by tryToReplaceWithGEPBuiltin().
makeIntrinsicCall()
CallInst * makeIntrinsicCall (Module * M, Intrinsic::BPFIntrinsics Intrinsic, ArrayRef< Type * > Types, ArrayRef< Value * > Args) static
Definition at line 159 of file BPFPreserveStaticOffset.cpp.
References llvm::CallInst::Create(), and llvm::Intrinsic::getOrInsertDeclaration().
Referenced by makeGEPAndLoad(), and makeGEPAndStore().
mergeDebugLocs()
template<class T = Instruction> DebugLoc mergeDebugLocs (SmallVector< T * > & Insns) static
Definition at line 152 of file BPFPreserveStaticOffset.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::DebugLoc::getMergedLocation(), I, and T.
Referenced by makeGEPAndLoad(), and makeGEPAndStore().
reconstructCommon()
template<class T = std::disjunction<LoadInst, StoreInst>> void reconstructCommon (CallInst * Call, GetElementPtrInst * GEP, T * Insn, int Delta) static
Definition at line 288 of file BPFPreserveStaticOffset.cpp.
References Call, GEP, getOperandAsUnsigned(), Insn, and T.
Referenced by llvm::BPFPreserveStaticOffsetPass::reconstructLoad(), and llvm::BPFPreserveStaticOffsetPass::reconstructStore().
reconstructGEP()
GetElementPtrInst * reconstructGEP (CallInst * Call, int Delta) static
Definition at line 275 of file BPFPreserveStaticOffset.cpp.
References llvm::SmallVectorImpl< T >::append(), Call, llvm::GetElementPtrInst::Create(), GEP, and getOperandAsUnsigned().
Referenced by llvm::BPFPreserveStaticOffsetPass::reconstructLoad(), and llvm::BPFPreserveStaticOffsetPass::reconstructStore().
removeMarkerCall()
void removeMarkerCall (Instruction * Marker) static
Definition at line 564 of file BPFPreserveStaticOffset.cpp.
References llvm::Instruction::eraseFromParent(), llvm::User::getOperand(), and llvm::Value::replaceAllUsesWith().
Referenced by rewriteAccessChain(), and rewriteFunction().
removePAICalls()
void removePAICalls (Instruction * Marker) static
Definition at line 609 of file BPFPreserveStaticOffset.cpp.
References Call, llvm::cast(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), GEP, isPreserveArrayIndex(), isPreserveStaticOffsetCall(), isPreserveStructIndex(), isPreserveUnionIndex(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::BPFCoreSharedInfo::removeArrayAccessCall(), llvm::BPFCoreSharedInfo::removeStructAccessCall(), llvm::BPFCoreSharedInfo::removeUnionAccessCall(), and llvm::Value::users().
Referenced by rewriteFunction().
reportNonStaticGEPChain()
void reportNonStaticGEPChain (Instruction * Insn) static
Definition at line 392 of file BPFPreserveStaticOffset.cpp.
References llvm::concat(), llvm::DS_Warning, and Insn.
Referenced by rewriteAccessChain().
rewriteAccessChain() [1/2]
void rewriteAccessChain (Instruction * Insn, SmallVector< GetElementPtrInst * > & GEPs, SmallVector< Instruction * > & Visited, bool AllowPatial, bool & StillUsed) static
Definition at line 497 of file BPFPreserveStaticOffset.cpp.
References allZeroIndices(), llvm::cast(), llvm::concat(), llvm::dyn_cast(), GEP, Insn, llvm::isa(), isGEPAndLoad(), isGEPAndStore(), isInlineableCall(), isPreserveStaticOffsetCall(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::BPFPreserveStaticOffsetPass::reconstructLoad(), llvm::BPFPreserveStaticOffsetPass::reconstructStore(), llvm::report_fatal_error(), reportNonStaticGEPChain(), rewriteUses(), and tryToReplaceWithGEPBuiltin().
Referenced by rewriteFunction(), and rewriteUses().
rewriteAccessChain() [2/2]
bool rewriteAccessChain (Instruction * Marker, bool AllowPatial, SmallPtrSetImpl< Instruction * > & RemovedMarkers) static
Definition at line 569 of file BPFPreserveStaticOffset.cpp.
References llvm::SmallPtrSetImpl< PtrType >::insert(), isPreserveStaticOffsetCall(), llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), removeMarkerCall(), llvm::SmallVectorTemplateCommon< T, typename >::rend(), and rewriteUses().
rewriteFunction()
bool rewriteFunction (Function & F, bool AllowPartial) static
Definition at line 644 of file BPFPreserveStaticOffset.cpp.
References Call, collectPreserveStaticOffsetCalls(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::dbgs(), F, LLVM_DEBUG, removeMarkerCall(), removePAICalls(), and rewriteAccessChain().
Referenced by llvm::BPFPreserveStaticOffsetPass::run().
rewriteUses()
void rewriteUses (Instruction * Insn, SmallVector< GetElementPtrInst * > & GEPs, SmallVector< Instruction * > & Visited, bool AllowPatial, bool & StillUsed) static
Definition at line 456 of file BPFPreserveStaticOffset.cpp.
References llvm::dbgs(), llvm::dyn_cast(), Insn, isInlineableCall(), isPointerOperand(), isPreserveStaticOffsetCall(), LLVM_DEBUG, and rewriteAccessChain().
Referenced by rewriteAccessChain(), and rewriteAccessChain().
setParamElementType()
void setParamElementType (CallInst * Call, unsigned ArgNo, Type * Type) static
Definition at line 168 of file BPFPreserveStaticOffset.cpp.
References llvm::CallingConv::C, Call, and llvm::Attribute::get().
Referenced by makeGEPAndLoad(), and makeGEPAndStore().
setParamReadNone()
void setParamReadNone (CallInst * Call, unsigned ArgNo) static
Definition at line 173 of file BPFPreserveStaticOffset.cpp.
References llvm::CallingConv::C, Call, and llvm::Attribute::get().
Referenced by makeGEPAndStore().
setParamReadOnly()
void setParamReadOnly (CallInst * Call, unsigned ArgNo) static
Definition at line 178 of file BPFPreserveStaticOffset.cpp.
References llvm::CallingConv::C, Call, and llvm::Attribute::get().
Referenced by makeGEPAndLoad().
setParamWriteOnly()
void setParamWriteOnly (CallInst * Call, unsigned ArgNo) static
Definition at line 183 of file BPFPreserveStaticOffset.cpp.
References llvm::CallingConv::C, Call, and llvm::Attribute::get().
Referenced by makeGEPAndStore().
tryToReplaceWithGEPBuiltin()
bool tryToReplaceWithGEPBuiltin (Instruction * LoadOrStoreTemplate, SmallVector< GetElementPtrInst * > & GEPs, Instruction * InsnToReplace) static
Definition at line 409 of file BPFPreserveStaticOffset.cpp.
References llvm::dyn_cast(), foldGEPChainAsStructAccess(), foldGEPChainAsU8Access(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getModule(), llvm::Instruction::insertBefore(), makeGEPAndLoad(), makeGEPAndStore(), and llvm::Value::replaceAllUsesWith().
Referenced by rewriteAccessChain().
Variable Documentation
GepAndLoadFirstIdxArg
const unsigned GepAndLoadFirstIdxArg = 6 static
Definition at line 125 of file BPFPreserveStaticOffset.cpp.
Referenced by makeGEPAndLoad().
GepAndStoreFirstIdxArg
const unsigned GepAndStoreFirstIdxArg = 7 static
Definition at line 126 of file BPFPreserveStaticOffset.cpp.
Referenced by makeGEPAndStore().