LLVM: llvm::ReleaseModePriorityAdvisorProvider Class Reference
llvm::ReleaseModePriorityAdvisorProvider Class Reference final
Public Member Functions
ReleaseModePriorityAdvisorProvider ()
std::unique_ptr< RegAllocPriorityAdvisor > getAdvisor (const MachineFunction &MF, const RAGreedy &RA, SlotIndexes &SI) override
Public Member Functions inherited from llvm::RegAllocPriorityAdvisorProvider
RegAllocPriorityAdvisorProvider (AdvisorMode Mode)
virtual ~RegAllocPriorityAdvisorProvider ()=default
virtual void logRewardIfNeeded (const MachineFunction &MF, function_ref< float()> GetReward)
AdvisorMode getAdvisorMode () const
Additional Inherited Members
Public Types inherited from llvm::RegAllocPriorityAdvisorProvider
enum class AdvisorMode : int { Default , Release , Development , Dummy }
Detailed Description
Definition at line 124 of file MLRegAllocPriorityAdvisor.cpp.
Constructor & Destructor Documentation
ReleaseModePriorityAdvisorProvider()
llvm::ReleaseModePriorityAdvisorProvider::ReleaseModePriorityAdvisorProvider () inline
Definition at line 127 of file MLRegAllocPriorityAdvisor.cpp.
References llvm::RegAllocPriorityAdvisorProvider::RegAllocPriorityAdvisorProvider(), and llvm::RegAllocPriorityAdvisorProvider::Release.
Member Function Documentation
getAdvisor()
std::unique_ptr< RegAllocPriorityAdvisor > llvm::ReleaseModePriorityAdvisorProvider::getAdvisor (const MachineFunction & MF, const RAGreedy & RA, SlotIndexes & SI) inline override virtual
Implements llvm::RegAllocPriorityAdvisorProvider.
Definition at line 130 of file MLRegAllocPriorityAdvisor.cpp.
References llvm::DecisionName, llvm::DecisionSpec, llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::InputFeatures, InteractiveChannelBaseName, and RA.
The documentation for this class was generated from the following file:
lib/CodeGen/MLRegAllocPriorityAdvisor.cpp