LLVM: llvm::PostGenericScheduler Class Reference
llvm::PostGenericScheduler Class Reference
PostGenericScheduler - Interface to the scheduling algorithm used by ScheduleDAGMI.
#include "llvm/CodeGen/MachineScheduler.h"
Public Member Functions
PostGenericScheduler (const MachineSchedContext *C)
~PostGenericScheduler () override=default
void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override
Optionally override the per-region scheduling policy.
bool shouldTrackPressure () const override
PostRA scheduling does not track pressure.
void initialize (ScheduleDAGMI *Dag) override
Initialize the strategy after building the DAG for a new region.
void registerRoots () override
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
SUnit * pickNode (bool &IsTopNode) override
Pick the next node to schedule.
SUnit * pickNodeBidirectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
void scheduleTree (unsigned SubtreeID) override
Scheduler callback to notify that a new subtree is scheduled.
void schedNode (SUnit *SU, bool IsTopNode) override
Called after ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void dumpPolicy () const
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
Protected Member Functions
virtual bool tryCandidate (SchedCandidate &Cand, SchedCandidate &TryCand)
Apply a set of heuristics to a new candidate for PostRA scheduling.
void pickNodeFromQueue (SchedBoundary &Zone, SchedCandidate &Cand)
Protected Member Functions inherited from llvm::GenericSchedulerBase
GenericSchedulerBase (const MachineSchedContext *C)
LLVM_ABI void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
MachineSchedPolicy getPolicy () const override
void traceCandidate (const SchedCandidate &Cand)
Protected Attributes
ScheduleDAGMI * DAG = nullptr
SchedBoundary Top
SchedBoundary Bot
SchedCandidate TopCand
Candidate last picked from Top boundary.
SchedCandidate BotCand
Candidate last picked from Bot boundary.
ClusterInfo * TopCluster
ClusterInfo * BotCluster
Protected Attributes inherited from llvm::GenericSchedulerBase
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
unsigned TopIdx = 0
unsigned BotIdx = 0
unsigned NumRegionInstrs = 0
MachineSchedPolicy RegionPolicy
SchedRemainder Rem
Additional Inherited Members
Public Types inherited from llvm::GenericSchedulerBase
enum CandReason : uint8_t {
NoCand , Only1 , PhysReg , RegExcess ,
RegCritical , Stall , Cluster , Weak ,
RegMax , ResourceReduce , ResourceDemand , BotHeightReduce ,
BotPathReduce , TopDepthReduce , TopPathReduce , NodeOrder ,
FirstValid
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions inherited from llvm::GenericSchedulerBase
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Detailed Description
PostGenericScheduler - Interface to the scheduling algorithm used by ScheduleDAGMI.
Callbacks from ScheduleDAGMI: initPolicy -> initialize(DAG) -> registerRoots -> pickNode ...
Definition at line 1322 of file MachineScheduler.h.
Constructor & Destructor Documentation
PostGenericScheduler()
llvm::PostGenericScheduler::PostGenericScheduler (const MachineSchedContext * C) inline
Definition at line 1337 of file MachineScheduler.h.
References Bot, llvm::CallingConv::C, llvm::GenericSchedulerBase::GenericSchedulerBase(), and Top.
Referenced by llvm::AArch64PostRASchedStrategy::AArch64PostRASchedStrategy(), and llvm::PPCPostRASchedStrategy::PPCPostRASchedStrategy().
~PostGenericScheduler()
llvm::PostGenericScheduler::~PostGenericScheduler () override default
References initPolicy(), and llvm::GenericSchedulerBase::NumRegionInstrs.
Member Function Documentation
initialize()
void PostGenericScheduler::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::PPCPostRASchedStrategy.
Definition at line 4308 of file MachineScheduler.cpp.
References Bot, BotCluster, DAG, llvm::GenericSchedulerBase::Rem, llvm::GenericSchedulerBase::SchedModel, Top, TopCluster, and llvm::GenericSchedulerBase::TRI.
Referenced by llvm::PPCPostRASchedStrategy::initialize().
initPolicy()
void PostGenericScheduler::initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override virtual
Optionally override the per-region scheduling policy.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 4330 of file MachineScheduler.cpp.
References llvm::MISched::Bidirectional, llvm::GenericSchedulerBase::BotIdx, llvm::MISched::BottomUp, llvm::MachineFunction::getSubtarget(), llvm::GenericSchedulerBase::NumRegionInstrs, llvm::TargetSubtargetInfo::overridePostRASchedPolicy(), llvm::PostRADirection, llvm::GenericSchedulerBase::RegionPolicy, and llvm::MISched::TopDown.
Referenced by ~PostGenericScheduler().
pickNode()
SUnit * PostGenericScheduler::pickNode (bool & IsTopNode) override virtual
Pick the next node to schedule.
Implements llvm::MachineSchedStrategy.
Reimplemented in llvm::PPCPostRASchedStrategy.
Definition at line 4522 of file MachineScheduler.cpp.
References assert(), Bot, BotCand, llvm::GenericSchedulerBase::BotIdx, DAG, llvm::dbgs(), llvm::SUnit::getInstr(), llvm::SUnit::isBottomReady(), llvm::SUnit::isScheduled, llvm::SUnit::isTopReady(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::NumRegionInstrs, llvm::GenericSchedulerBase::Only1, pickNodeBidirectional(), pickNodeFromQueue(), llvm::GenericSchedulerBase::RegionPolicy, llvm::GenericSchedulerBase::setPolicy(), Top, TopCand, llvm::GenericSchedulerBase::TopIdx, and tracePick().
Referenced by llvm::PPCPostRASchedStrategy::pickNode().
pickNodeBidirectional()
SUnit * PostGenericScheduler::pickNodeBidirectional (bool & IsTopNode)
Pick the best candidate node from either the top or bottom queue.
Definition at line 4441 of file MachineScheduler.cpp.
References assert(), llvm::GenericSchedulerBase::SchedCandidate::AtTop, Bot, BotCand, llvm::dbgs(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::GenericSchedulerBase::Only1, pickNodeFromQueue(), llvm::GenericSchedulerBase::SchedCandidate::reset(), llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::GenericSchedulerBase::setPolicy(), llvm::GenericSchedulerBase::SchedCandidate::SU, Top, TopCand, llvm::GenericSchedulerBase::traceCandidate(), tracePick(), tryCandidate(), and llvm::VerifyScheduling.
Referenced by pickNode().
pickNodeFromQueue()
void PostGenericScheduler::pickNodeFromQueue (SchedBoundary & Zone, SchedCandidate & Cand) protected
Definition at line 4425 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::SchedBoundary::Available, DAG, llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::SchedBoundary::isTop(), LLVM_DEBUG, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::GenericSchedulerBase::traceCandidate(), and tryCandidate().
Referenced by pickNode(), and pickNodeBidirectional().
registerRoots()
void PostGenericScheduler::registerRoots () override virtual
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 4359 of file MachineScheduler.cpp.
References Bot, DAG, llvm::dbgs(), llvm::DumpCriticalPathLength, llvm::errs(), llvm::SUnit::getDepth(), LLVM_DEBUG, and llvm::GenericSchedulerBase::Rem.
releaseBottomNode()
void llvm::PostGenericScheduler::releaseBottomNode (SUnit * SU) inline override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 1371 of file MachineScheduler.h.
References Bot, BotCand, llvm::SUnit::BotReadyCycle, and llvm::SUnit::isScheduled.
releaseTopNode()
void llvm::PostGenericScheduler::releaseTopNode (SUnit * SU) inline override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 1364 of file MachineScheduler.h.
References llvm::SUnit::isScheduled, Top, TopCand, and llvm::SUnit::TopReadyCycle.
schedNode()
void PostGenericScheduler::schedNode (SUnit * SU, bool IsTopNode) override virtual
Called after ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
Implements llvm::MachineSchedStrategy.
Definition at line 4591 of file MachineScheduler.cpp.
References Bot, BotCluster, llvm::SUnit::BotReadyCycle, DAG, llvm::SUnit::ParentClusterIdx, Top, TopCluster, and llvm::SUnit::TopReadyCycle.
scheduleTree()
void llvm::PostGenericScheduler::scheduleTree (unsigned SubtreeID) inline override virtual
Scheduler callback to notify that a new subtree is scheduled.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1358 of file MachineScheduler.h.
References llvm_unreachable.
shouldTrackPressure()
bool llvm::PostGenericScheduler::shouldTrackPressure () const inline override virtual
PostRA scheduling does not track pressure.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 1348 of file MachineScheduler.h.
tryCandidate()
bool PostGenericScheduler::tryCandidate (SchedCandidate & Cand, SchedCandidate & TryCand) protected virtual
Apply a set of heuristics to a new candidate for PostRA scheduling.
Parameters
Cand provides the policy and current best candidate.
TryCand refers to the next SUnit candidate, otherwise uninitialized.
Returns
true if TryCand is better than Cand (Reason is NOT NoCand)
Reimplemented in llvm::AArch64PostRASchedStrategy, and llvm::PPCPostRASchedStrategy.
Definition at line 4378 of file MachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, Bot, BotCluster, llvm::GenericSchedulerBase::Cluster, llvm::SmallSet< T, N, C >::contains(), llvm::GenericSchedulerBase::SchedResourceDelta::CritResources, llvm::GenericSchedulerBase::SchedResourceDelta::DemandedResources, llvm::GenericSchedulerBase::FirstValid, llvm::GenericSchedulerBase::SchedCandidate::isValid(), llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::NodeOrder, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::CandPolicy::ReduceLatency, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::ResourceDemand, llvm::GenericSchedulerBase::ResourceReduce, llvm::GenericSchedulerBase::Stall, llvm::GenericSchedulerBase::SchedCandidate::SU, Top, TopCluster, llvm::tryGreater(), llvm::tryLatency(), and llvm::tryLess().
Referenced by pickNodeBidirectional(), pickNodeFromQueue(), and llvm::AArch64PostRASchedStrategy::tryCandidate().
Member Data Documentation
Bot
SchedBoundary llvm::PostGenericScheduler::Bot protected
Definition at line 1326 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeBidirectional(), PostGenericScheduler(), registerRoots(), releaseBottomNode(), schedNode(), and tryCandidate().
BotCand
SchedCandidate llvm::PostGenericScheduler::BotCand protected
Candidate last picked from Bot boundary.
Definition at line 1331 of file MachineScheduler.h.
Referenced by pickNode(), pickNodeBidirectional(), and releaseBottomNode().
BotCluster
ClusterInfo* llvm::PostGenericScheduler::BotCluster protected
Definition at line 1334 of file MachineScheduler.h.
Referenced by initialize(), schedNode(), tryCandidate(), and llvm::PPCPostRASchedStrategy::tryCandidate().
DAG
ScheduleDAGMI* llvm::PostGenericScheduler::DAG = nullptr protected
Definition at line 1324 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeFromQueue(), registerRoots(), and schedNode().
Top
SchedBoundary llvm::PostGenericScheduler::Top protected
Definition at line 1325 of file MachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeBidirectional(), PostGenericScheduler(), releaseTopNode(), schedNode(), tryCandidate(), and llvm::PPCPostRASchedStrategy::tryCandidate().
TopCand
SchedCandidate llvm::PostGenericScheduler::TopCand protected
Candidate last picked from Top boundary.
Definition at line 1329 of file MachineScheduler.h.
Referenced by pickNode(), pickNodeBidirectional(), and releaseTopNode().
TopCluster
ClusterInfo* llvm::PostGenericScheduler::TopCluster protected
Definition at line 1333 of file MachineScheduler.h.
Referenced by initialize(), schedNode(), tryCandidate(), and llvm::PPCPostRASchedStrategy::tryCandidate().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp