LLVM: llvm::DiagnosticInfoISelFallback Class Reference
llvm::DiagnosticInfoISelFallback Class Reference
Diagnostic information for ISel fallback path.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoISelFallback (const Function &Fn, DiagnosticSeverity Severity=DS_Warning)
const Function & getFunction () const
void print (DiagnosticPrinter &DP) const override
Print using the given DP a user-friendly message.
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for ISel fallback path.
Definition at line 1021 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoISelFallback()
llvm::DiagnosticInfoISelFallback::DiagnosticInfoISelFallback (const Function & Fn, DiagnosticSeverity Severity = DS_Warning) inline
Definition at line 1026 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_ISelFallback, and llvm::DS_Warning.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoISelFallback::classof (const DiagnosticInfo * DI) inline static
Definition at line 1034 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_ISelFallback, and llvm::DiagnosticInfo::getKind().
getFunction()
const Function & llvm::DiagnosticInfoISelFallback::getFunction () const inline
Definition at line 1030 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoISelFallback::print (DiagnosticPrinter & DP) const override virtual
Print using the given DP a user-friendly message.
This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implements llvm::DiagnosticInfo.
Definition at line 417 of file DiagnosticInfo.cpp.
References getFunction().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp