LLVM: llvm::PseudoSourceValue Class Reference
llvm::PseudoSourceValue Class Reference
Special value supplied for machine level alias analysis.
#include "llvm/CodeGen/PseudoSourceValue.h"
Public Types
enum PSVKind : unsigned {
Stack , GOT , JumpTable , ConstantPool ,
FixedStack , GlobalValueCallEntry , ExternalSymbolCallEntry , TargetCustom
}
Public Member Functions
PseudoSourceValue (unsigned Kind, const TargetMachine &TM)
virtual ~PseudoSourceValue ()
unsigned kind () const
bool isStack () const
bool isGOT () const
bool isConstantPool () const
bool isJumpTable () const
unsigned getAddressSpace () const
unsigned getTargetCustom () const
virtual bool isConstant (const MachineFrameInfo *) const
Test whether the memory pointed to by this PseudoSourceValue has a constant value.
virtual bool isAliased (const MachineFrameInfo *) const
Test whether the memory pointed to by this PseudoSourceValue may also be pointed to by an LLVM IR Value.
virtual bool mayAlias (const MachineFrameInfo *) const
Return true if the memory pointed to by this PseudoSourceValue can ever alias an LLVM IR Value.
Friends
class MachineMemOperand
class MIRFormatter
LLVM_ABI friend raw_ostream & llvm::operator<< (raw_ostream &OS, const PseudoSourceValue *PSV)
Detailed Description
Special value supplied for machine level alias analysis.
It indicates that a memory access references the functions stack frame (e.g., a spill slot), below the stack frame (e.g., argument space), or constant pool.
Definition at line 33 of file PseudoSourceValue.h.
Member Enumeration Documentation
PSVKind
enum llvm::PseudoSourceValue::PSVKind : unsigned
Enumerator
Stack
GOT
JumpTable
ConstantPool
FixedStack
GlobalValueCallEntry
ExternalSymbolCallEntry
TargetCustom
Definition at line 35 of file PseudoSourceValue.h.
Constructor & Destructor Documentation
PseudoSourceValue()
PseudoSourceValue::PseudoSourceValue (unsigned Kind, const TargetMachine & TM) explicit
Definition at line 27 of file PseudoSourceValue.cpp.
Referenced by llvm::AMDGPUPseudoSourceValue::AMDGPUPseudoSourceValue(), llvm::CallEntryPseudoSourceValue::CallEntryPseudoSourceValue(), llvm::FixedStackPseudoSourceValue::classof(), llvm::FixedStackPseudoSourceValue::FixedStackPseudoSourceValue(), llvm::operator<<, and MIRFormatter.
~PseudoSourceValue()
PseudoSourceValue::~PseudoSourceValue () virtual default
Member Function Documentation
getAddressSpace()
unsigned llvm::PseudoSourceValue::getAddressSpace () const inline
Definition at line 71 of file PseudoSourceValue.h.
getTargetCustom()
unsigned llvm::PseudoSourceValue::getTargetCustom () const inline
Definition at line 73 of file PseudoSourceValue.h.
References TargetCustom.
isAliased()
bool PseudoSourceValue::isAliased (const MachineFrameInfo *) const virtual
Test whether the memory pointed to by this PseudoSourceValue may also be pointed to by an LLVM IR Value.
Reimplemented in llvm::AMDGPUGWSResourcePseudoSourceValue, llvm::AMDGPUPseudoSourceValue, llvm::CallEntryPseudoSourceValue, and llvm::FixedStackPseudoSourceValue.
Definition at line 49 of file PseudoSourceValue.cpp.
References isConstantPool(), isGOT(), isJumpTable(), isStack(), and llvm_unreachable.
isConstant()
bool PseudoSourceValue::isConstant (const MachineFrameInfo *) const virtual
Test whether the memory pointed to by this PseudoSourceValue has a constant value.
Reimplemented in llvm::AMDGPUPseudoSourceValue, llvm::CallEntryPseudoSourceValue, and llvm::FixedStackPseudoSourceValue.
Definition at line 41 of file PseudoSourceValue.cpp.
References isConstantPool(), isGOT(), isJumpTable(), isStack(), and llvm_unreachable.
isConstantPool()
bool llvm::PseudoSourceValue::isConstantPool () const inline
Definition at line 68 of file PseudoSourceValue.h.
References ConstantPool.
Referenced by isAliased(), isConstant(), and mayAlias().
isGOT()
bool llvm::PseudoSourceValue::isGOT () const inline
Definition at line 67 of file PseudoSourceValue.h.
References GOT.
Referenced by isAliased(), isConstant(), and mayAlias().
isJumpTable()
bool llvm::PseudoSourceValue::isJumpTable () const inline
Definition at line 69 of file PseudoSourceValue.h.
References JumpTable.
Referenced by isAliased(), isConstant(), and mayAlias().
isStack()
bool llvm::PseudoSourceValue::isStack () const inline
Definition at line 66 of file PseudoSourceValue.h.
References Stack.
Referenced by isAliased(), and isConstant().
kind()
unsigned llvm::PseudoSourceValue::kind () const inline
Definition at line 64 of file PseudoSourceValue.h.
Referenced by ValidateMVEStore().
mayAlias()
bool PseudoSourceValue::mayAlias (const MachineFrameInfo *) const virtual
Return true if the memory pointed to by this PseudoSourceValue can ever alias an LLVM IR Value.
Reimplemented in llvm::AMDGPUGWSResourcePseudoSourceValue, llvm::AMDGPUPseudoSourceValue, llvm::CallEntryPseudoSourceValue, and llvm::FixedStackPseudoSourceValue.
Definition at line 55 of file PseudoSourceValue.cpp.
References isConstantPool(), isGOT(), and isJumpTable().
Referenced by llvm::TargetInstrInfo::describeLoadedValue(), and MemOperandsHaveAlias().
Friends And Related Symbol Documentation
llvm::operator<<
LLVM_ABI friend raw_ostream & llvm::operator<< (raw_ostream & OS, const PseudoSourceValue * PSV) friend
References LLVM_ABI, and PseudoSourceValue().
MachineMemOperand
friend class MachineMemOperand friend
Definition at line 52 of file PseudoSourceValue.h.
References MachineMemOperand.
Referenced by MachineMemOperand.
MIRFormatter
friend class MIRFormatter friend
Definition at line 53 of file PseudoSourceValue.h.
References MIRFormatter, and PseudoSourceValue().
Referenced by MIRFormatter.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/PseudoSourceValue.h
lib/CodeGen/PseudoSourceValue.cpp