LLVM: llvm::orc::OrcMips64 Class Reference
llvm::orc::OrcMips64 Class Reference
#include "llvm/ExecutionEngine/Orc/OrcABISupport.h"
Static Public Member Functions
static LLVM_ABI void writeResolverCode (char *ResolverWorkingMem, ExecutorAddr ResolverTargetAddress, ExecutorAddr ReentryFnAddr, ExecutorAddr ReentryCtxAddr)
Write the resolver code into the given memory.
static LLVM_ABI void writeTrampolines (char *TrampolineBlockWorkingMem, ExecutorAddr TrampolineBlockTargetAddress, ExecutorAddr ResolverFnAddr, unsigned NumTrampolines)
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
static LLVM_ABI void writeIndirectStubsBlock (char *StubsBlockWorkingMem, ExecutorAddr StubsBlockTargetAddress, ExecutorAddr PointersBlockTargetAddress, unsigned NumStubs)
Write NumStubs indirect stubs to working memory at StubsBlockWorkingMem.
Static Public Attributes
static constexpr unsigned PointerSize = 8
static constexpr unsigned TrampolineSize = 40
static constexpr unsigned StubSize = 32
static constexpr unsigned StubToPointerMaxDisplacement = 1 << 31
static constexpr unsigned ResolverCodeSize = 0x120
Detailed Description
Definition at line 299 of file OrcABISupport.h.
Member Function Documentation
writeIndirectStubsBlock()
void llvm::orc::OrcMips64::writeIndirectStubsBlock (char * StubsBlockWorkingMem, ExecutorAddr StubsBlockTargetAddress, ExecutorAddr PointersBlockTargetAddress, unsigned NumStubs) static
Write NumStubs indirect stubs to working memory at StubsBlockWorkingMem.
Stubs will be written as if linked at StubsBlockTargetAddress, with the Nth stub using the Nth pointer in memory starting at PointersBlockTargetAddress.
Definition at line 862 of file OrcABISupport.cpp.
References assert(), llvm::orc::ExecutorAddr::getValue(), I, and stubAndPointerRangesOk().
writeResolverCode()
void llvm::orc::OrcMips64::writeResolverCode (char * ResolverWorkingMem, ExecutorAddr ResolverTargetAddress, ExecutorAddr ReentryFnAddr, ExecutorAddr ReentryCtxAddr) static
Write the resolver code into the given memory.
The user is responsible for allocating the memory and setting permissions.
ReentryFnAddr should be the address of a function whose signature matches void* (*)(void *TrampolineAddr, void *ReentryCtxAddr). The ReentryCtxAddr argument of writeResolverCode will be passed as the second argument to the function at ReentryFnAddr.
Definition at line 689 of file OrcABISupport.cpp.
References llvm::orc::ExecutorAddr::getValue().
writeTrampolines()
void llvm::orc::OrcMips64::writeTrampolines (char * TrampolineBlockWorkingMem, ExecutorAddr TrampolineBlockTargetAddress, ExecutorAddr ResolverFnAddr, unsigned NumTrampolines) static
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
Definition at line 835 of file OrcABISupport.cpp.
References llvm::orc::ExecutorAddr::getValue(), and I.
Member Data Documentation
PointerSize
unsigned llvm::orc::OrcMips64::PointerSize = 8 static constexpr
Definition at line 301 of file OrcABISupport.h.
ResolverCodeSize
unsigned llvm::orc::OrcMips64::ResolverCodeSize = 0x120 static constexpr
Definition at line 305 of file OrcABISupport.h.
StubSize
unsigned llvm::orc::OrcMips64::StubSize = 32 static constexpr
Definition at line 303 of file OrcABISupport.h.
StubToPointerMaxDisplacement
unsigned llvm::orc::OrcMips64::StubToPointerMaxDisplacement = 1 << 31 static constexpr
Definition at line 304 of file OrcABISupport.h.
TrampolineSize
unsigned llvm::orc::OrcMips64::TrampolineSize = 40 static constexpr
Definition at line 302 of file OrcABISupport.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/OrcABISupport.h
lib/ExecutionEngine/Orc/OrcABISupport.cpp