LLVM: llvm::object::OffloadBundleFatBin Class Reference
llvm::object::OffloadBundleFatBin Class Reference
Fat binary embedded in object files in clang-offload-bundler format.
#include "llvm/Object/OffloadBundle.h"
Public Member Functions
SmallVector< OffloadBundleEntry > getEntries ()
uint64_t getSize () const
StringRef getFileName () const
uint64_t getNumEntries () const
LLVM_ABI Error extractBundle (const ObjectFile &Source)
LLVM_ABI Error dumpEntryToCodeObject ()
LLVM_ABI Error readEntries (StringRef Section, uint64_t SectionOffset)
void dumpEntries ()
void printEntriesAsURI ()
OffloadBundleFatBin (MemoryBufferRef Source, StringRef File)
Static Public Member Functions
static LLVM_ABI Expected< std::unique_ptr< OffloadBundleFatBin > > create (MemoryBufferRef, uint64_t SectionOffset, StringRef FileName)
Detailed Description
Fat binary embedded in object files in clang-offload-bundler format.
Definition at line 79 of file OffloadBundle.h.
Constructor & Destructor Documentation
OffloadBundleFatBin()
llvm::object::OffloadBundleFatBin::OffloadBundleFatBin (MemoryBufferRef Source, StringRef File) inline
Definition at line 109 of file OffloadBundle.h.
Referenced by create().
Member Function Documentation
create()
Expected< std::unique_ptr< OffloadBundleFatBin > > OffloadBundleFatBin::create (MemoryBufferRef Buf, uint64_t SectionOffset, StringRef FileName) static
Definition at line 114 of file OffloadBundle.cpp.
References llvm::errorCodeToError(), llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferSize(), llvm::identify_magic(), llvm::file_magic::offload_bundle, OffloadBundleFatBin(), llvm::object::parse_failed, and readEntries().
Referenced by extractOffloadBundle().
dumpEntries()
void llvm::object::OffloadBundleFatBin::dumpEntries () inline
Definition at line 99 of file OffloadBundle.h.
References llvm::outs().
dumpEntryToCodeObject()
LLVM_ABI Error llvm::object::OffloadBundleFatBin::dumpEntryToCodeObject ()
References LLVM_ABI.
extractBundle()
Error OffloadBundleFatBin::extractBundle (const ObjectFile & Source)
Definition at line 133 of file OffloadBundle.cpp.
References llvm::object::extractCodeObject(), getFileName(), llvm::itostr(), llvm::StringRef::str(), and llvm::Error::success().
getEntries()
SmallVector< OffloadBundleEntry > llvm::object::OffloadBundleFatBin::getEntries () inline
Definition at line 87 of file OffloadBundle.h.
getFileName()
StringRef llvm::object::OffloadBundleFatBin::getFileName () const inline
Definition at line 89 of file OffloadBundle.h.
Referenced by extractBundle().
getNumEntries()
uint64_t llvm::object::OffloadBundleFatBin::getNumEntries () const inline
Definition at line 90 of file OffloadBundle.h.
getSize()
uint64_t llvm::object::OffloadBundleFatBin::getSize () const inline
Definition at line 88 of file OffloadBundle.h.
printEntriesAsURI()
void llvm::object::OffloadBundleFatBin::printEntriesAsURI () inline
Definition at line 104 of file OffloadBundle.h.
References llvm::outs().
readEntries()
Error OffloadBundleFatBin::readEntries (StringRef Section, uint64_t SectionOffset)
Definition at line 68 of file OffloadBundle.cpp.
References llvm::errorCodeToError(), I, llvm::little, llvm::object::parse_failed, llvm::BinaryStreamReader::readFixedString(), llvm::BinaryStreamReader::readInteger(), and llvm::Error::success().
Referenced by create().
The documentation for this class was generated from the following files:
include/llvm/Object/OffloadBundle.h
lib/Object/OffloadBundle.cpp