LLVM: llvm::LoongArchAsmBackend Class Reference
llvm::LoongArchAsmBackend Class Reference
#include "Target/LoongArch/MCTargetDesc/LoongArchAsmBackend.h"
Public Member Functions
LoongArchAsmBackend (const MCSubtargetInfo &STI, uint8_t OSABI, bool Is64Bit, const MCTargetOptions &Options)
bool addReloc (const MCFragment &, const MCFixup &, const MCValue &, uint64_t &FixedValue, bool IsResolved)
void applyFixup (const MCFragment &, const MCFixup &, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved) override
Determine if a relocation is required.
bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size) override
Hook to check if extra nop bytes must be inserted for alignment directive.
bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, MCAlignFragment &AF) override
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
bool shouldForceRelocation (const MCFixup &Fixup, const MCValue &Target)
std::optional< MCFixupKind > getFixupKind (StringRef Name) const override
Map a relocation name used in .reloc to a fixup kind.
MCFixupKindInfo getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, bool &WasRelaxed) const override
bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, bool &WasRelaxed) const override
std::pair< bool, bool > relaxLEB128 (MCLEBFragment &LF, int64_t &Value) const override
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
const MCTargetOptions & getTargetOptions () const
DenseMap< MCSection *, const MCSymbolRefExpr * > & getSecToAlignSym ()
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
void setAssembler (MCAssembler *A)
MCContext & getContext () const
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool finishLayout (const MCAssembler &Asm) const
virtual uint64_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
virtual std::optional< bool > evaluateFixup (const MCFragment &, MCFixup &, MCValue &, uint64_t &)
void maybeAddReloc (const MCFragment &, const MCFixup &, const MCValue &, uint64_t &Value, bool IsResolved)
virtual bool mayNeedRelaxation (unsigned Opcode, ArrayRef< MCOperand > Operands, const MCSubtargetInfo &STI) const
Check whether the given instruction (encoded as Opcode+Operands) may need relaxation.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &, const MCValue &, uint64_t, bool Resolved) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
virtual bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value) const
Simple predicate for targets where !Resolved implies requiring relaxation.
virtual void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const
Relax the instruction in the given fragment to the next wider instruction.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MCAsmBackend
static const MCSubtargetInfo * getSubtargetInfo (const MCFragment &F)
Public Attributes inherited from llvm::MCAsmBackend
const llvm::endianness Endian
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (llvm::endianness Endian)
Protected Attributes inherited from llvm::MCAsmBackend
MCAssembler * Asm = nullptr
Detailed Description
Definition at line 26 of file LoongArchAsmBackend.h.
Constructor & Destructor Documentation
LoongArchAsmBackend()
LoongArchAsmBackend::LoongArchAsmBackend (const MCSubtargetInfo & STI, uint8_t OSABI, bool Is64Bit, const MCTargetOptions & Options)
Definition at line 31 of file LoongArchAsmBackend.cpp.
References llvm::little, llvm::MCAsmBackend::MCAsmBackend(), and Options.
Member Function Documentation
addReloc()
bool LoongArchAsmBackend::addReloc (const MCFragment & F, const MCFixup & Fixup, const MCValue & Target, uint64_t & FixedValue, bool IsResolved)
Definition at line 449 of file LoongArchAsmBackend.cpp.
References A(), llvm::MCAsmBackend::Asm, assert(), B(), llvm::MCFixup::create(), F, Fallback, Fixup, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_Data_leb128, llvm::MCValue::get(), getRelocPairForSize(), llvm::MCSymbol::getSection(), llvm::MCSymbol::isInSection(), llvm_unreachable, and llvm::MCAsmBackend::maybeAddReloc().
Referenced by applyFixup().
applyFixup()
void LoongArchAsmBackend::applyFixup (const MCFragment & , const MCFixup & , const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved) override virtual
Determine if a relocation is required.
In addition, Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate. Errors (such as an out of range fixup value) should be reported via Ctx.
Implements llvm::MCAsmBackend.
Definition at line 143 of file LoongArchAsmBackend.cpp.
References addReloc(), adjustFixupValue(), llvm::alignTo(), assert(), llvm::Data, F, Fixup, fixupLeb128(), llvm::FK_Data_leb128, llvm::MCAsmBackend::getContext(), getFixupKindInfo(), I, llvm::mc::isRelocation(), llvm::Offset, and shouldForceRelocation().
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > LoongArchAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 531 of file LoongArchAsmBackend.cpp.
References llvm::createLoongArchELFObjectWriter().
getFixupKind()
std::optional< MCFixupKind > LoongArchAsmBackend::getFixupKind (StringRef Name) const override virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 38 of file LoongArchAsmBackend.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and llvm::FirstLiteralRelocationKind.
getFixupKindInfo()
MCFixupKindInfo LoongArchAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 54 of file LoongArchAsmBackend.cpp.
References assert(), llvm::FirstTargetFixupKind, llvm::MCAsmBackend::getFixupKindInfo(), llvm::mc::isRelocation(), and llvm::LoongArch::NumTargetFixupKinds.
Referenced by applyFixup().
getSecToAlignSym()
DenseMap< MCSection *, const MCSymbolRefExpr * > & llvm::LoongArchAsmBackend::getSecToAlignSym () inline
Definition at line 75 of file LoongArchAsmBackend.h.
Referenced by shouldInsertFixupForCodeAlign().
getTargetOptions()
const MCTargetOptions & llvm::LoongArchAsmBackend::getTargetOptions () const inline
Definition at line 74 of file LoongArchAsmBackend.h.
relaxDwarfCFA()
bool LoongArchAsmBackend::relaxDwarfCFA (MCDwarfCallFrameFragment & DF, bool & WasRelaxed) const override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 358 of file LoongArchAsmBackend.cpp.
References llvm::MCAsmBackend::Asm, assert(), llvm::cast(), llvm::MCFixup::create(), llvm::Data, DF, llvm::MCExpr::evaluateKnownAbsolute(), llvm::MCAsmBackend::getContext(), llvm::MCBinaryExpr::getLHS(), getRelocPairForSize(), llvm::MCBinaryExpr::getRHS(), llvm::isUInt(), llvm::isUIntN(), llvm::little, llvm_unreachable, llvm::Offset, and llvm::support::endian::write().
relaxDwarfLineAddr()
bool LoongArchAsmBackend::relaxDwarfLineAddr (MCDwarfLineAddrFragment & DF, bool & WasRelaxed) const override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 291 of file LoongArchAsmBackend.cpp.
References llvm::MCAsmBackend::Asm, assert(), llvm::CallingConv::C, llvm::cast(), llvm::MCFixup::create(), llvm::Data, DF, llvm::encodeSLEB128(), llvm::encodeULEB128(), llvm::MCExpr::evaluateKnownAbsolute(), llvm::MCAsmBackend::getContext(), llvm::MCBinaryExpr::getLHS(), getRelocPairForSize(), llvm::MCBinaryExpr::getRHS(), INT64_MAX, llvm::little, llvm::Offset, llvm::raw_ostream::tell(), llvm::support::endian::write(), and llvm::raw_ostream::write_zeros().
relaxLEB128()
std::pair< bool, bool > LoongArchAsmBackend::relaxLEB128 (MCLEBFragment & LF, int64_t & Value) const override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 282 of file LoongArchAsmBackend.cpp.
References llvm::MCEncodedFragment::addFixup(), llvm::MCAsmBackend::Asm, llvm::MCFixup::create(), llvm::MCExpr::evaluateKnownAbsolute(), llvm::FK_Data_leb128, llvm::MCLEBFragment::getValue(), and llvm::MCLEBFragment::isSigned().
shouldForceRelocation()
bool LoongArchAsmBackend::shouldForceRelocation (const MCFixup & Fixup, const MCValue & Target)
Definition at line 248 of file LoongArchAsmBackend.cpp.
References Fixup, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, and llvm::FK_Data_leb128.
Referenced by applyFixup().
shouldInsertExtraNopBytesForCodeAlign()
bool LoongArchAsmBackend::shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment & AF, unsigned & Size) override virtual
Hook to check if extra nop bytes must be inserted for alignment directive.
For some targets this may be necessary in order to support linker relaxation. The number of bytes to insert are returned in Size.
Reimplemented from llvm::MCAsmBackend.
Definition at line 184 of file LoongArchAsmBackend.cpp.
References llvm::MCAlignFragment::getAlignment(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCAlignFragment::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), Size, and llvm::Align::value().
Referenced by shouldInsertFixupForCodeAlign().
shouldInsertFixupForCodeAlign()
bool LoongArchAsmBackend::shouldInsertFixupForCodeAlign (MCAssembler & Asm, MCAlignFragment & AF) override virtual
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
Reimplemented from llvm::MCAsmBackend.
Definition at line 207 of file LoongArchAsmBackend.cpp.
References llvm::MCAsmBackend::Asm, llvm::MCConstantExpr::create(), llvm::MCFixup::create(), llvm::MCSymbolRefExpr::create(), Fixup, llvm::MCValue::get(), llvm::MCAlignFragment::getAlignment(), llvm::MCSection::getBeginSymbol(), llvm::MCAsmBackend::getContext(), llvm::MCSymbol::getFragment(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCFragment::getParent(), getSecToAlignSym(), llvm::MCAlignFragment::getSubtargetInfo(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSubtargetInfo::hasFeature(), llvm::Log2(), llvm::MCSymbol::setFragment(), and shouldInsertExtraNopBytesForCodeAlign().
writeNopData()
bool LoongArchAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 415 of file LoongArchAsmBackend.cpp.
References llvm::Count, llvm::raw_ostream::write(), and llvm::raw_ostream::write_zeros().
The documentation for this class was generated from the following files:
lib/Target/LoongArch/MCTargetDesc/LoongArchAsmBackend.h
lib/Target/LoongArch/MCTargetDesc/LoongArchAsmBackend.cpp