LLVM: llvm::orc::Speculator Class Reference
llvm::orc::Speculator Class Reference
#include "llvm/ExecutionEngine/Orc/Speculation.h"
Public Types
using TargetFAddr = ExecutorAddr
using FunctionCandidatesMap = DenseMap<SymbolStringPtr, SymbolNameSet>
using StubAddrLikelies = DenseMap<TargetFAddr, SymbolNameSet>
Public Member Functions
Speculator (ImplSymbolMap &Impl, ExecutionSession &ref)
Speculator (const Speculator &)=delete
Speculator (Speculator &&)=delete
Speculator & operator= (const Speculator &)=delete
Speculator & operator= (Speculator &&)=delete
LLVM_ABI Error addSpeculationRuntime (JITDylib &JD, MangleAndInterner &Mangle)
Define symbols for this Speculator object (__orc_speculator) and the speculation runtime entry point symbol (__orc_speculate_for) in the given JITDylib.
void speculateFor (TargetFAddr StubAddr)
void registerSymbols (FunctionCandidatesMap Candidates, JITDylib *JD)
ExecutionSession & getES ()
Detailed Description
Definition at line 61 of file Speculation.h.
Member Typedef Documentation
FunctionCandidatesMap
using llvm::orc::Speculator::FunctionCandidatesMap = DenseMap<SymbolStringPtr, SymbolNameSet>
Definition at line 64 of file Speculation.h.
StubAddrLikelies
using llvm::orc::Speculator::StubAddrLikelies = DenseMap<TargetFAddr, SymbolNameSet>
Definition at line 65 of file Speculation.h.
TargetFAddr
using llvm::orc::Speculator::TargetFAddr = ExecutorAddr
Definition at line 63 of file Speculation.h.
Constructor & Destructor Documentation
Speculator() [1/3]
llvm::orc::Speculator::Speculator (ImplSymbolMap & Impl, ExecutionSession & ref) inline
Definition at line 123 of file Speculation.h.
Referenced by operator=(), operator=(), Speculator(), and Speculator().
Speculator() [2/3]
llvm::orc::Speculator::Speculator (const Speculator &) delete
References Speculator().
Speculator() [3/3]
llvm::orc::Speculator::Speculator (Speculator &&) delete
References Speculator().
Member Function Documentation
addSpeculationRuntime()
Error llvm::orc::Speculator::addSpeculationRuntime (JITDylib & JD, MangleAndInterner & Mangle)
Define symbols for this Speculator object (__orc_speculator) and the speculation runtime entry point symbol (__orc_speculate_for) in the given JITDylib.
Definition at line 44 of file Speculation.cpp.
References llvm::orc::absoluteSymbols(), llvm::orc::JITDylib::define(), llvm::JITSymbolFlags::Exported, and llvm::orc::ExecutorAddr::fromPtr().
getES()
ExecutionSession & llvm::orc::Speculator::getES () inline
Definition at line 162 of file Speculation.h.
Referenced by registerSymbols().
operator=() [1/2]
Speculator & llvm::orc::Speculator::operator= (const Speculator &) delete
References Speculator().
operator=() [2/2]
Speculator & llvm::orc::Speculator::operator= (Speculator &&) delete
References LLVM_ABI, and Speculator().
registerSymbols()
void llvm::orc::Speculator::registerSymbols (FunctionCandidatesMap Candidates, JITDylib * JD) inline
Definition at line 140 of file Speculation.h.
References getES(), llvm::orc::makeJITDylibSearchOrder(), llvm::orc::MatchAllSymbols, llvm::orc::NoDependenciesToRegister, llvm::orc::Ready, llvm::orc::ExecutionSession::reportError(), llvm::orc::Static, and llvm::orc::WeaklyReferencedSymbol.
speculateFor()
void llvm::orc::Speculator::speculateFor (TargetFAddr StubAddr) inline
Definition at line 137 of file Speculation.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Speculation.h
lib/ExecutionEngine/Orc/Speculation.cpp