LLVM: llvm::object::Archive::Symbol Class Reference
llvm::object::Archive::Symbol Class Reference
#include "llvm/Object/Archive.h"
Public Member Functions
Symbol (const Archive *p, uint32_t symi, uint32_t stri)
bool operator== (const Symbol &other) const
LLVM_ABI StringRef getName () const
LLVM_ABI Expected< Child > getMember () const
LLVM_ABI Symbol getNext () const
LLVM_ABI bool isECSymbol () const
Detailed Description
Definition at line 292 of file Archive.h.
Constructor & Destructor Documentation
Symbol()
llvm::object::Archive::Symbol::Symbol (const Archive * p, uint32_t symi, uint32_t stri) inline
Definition at line 298 of file Archive.h.
References llvm::object::Archive::Archive().
Referenced by getNext(), and operator==().
Member Function Documentation
getMember()
Expected< Archive::Child > Archive::Symbol::getMember () const
Definition at line 1020 of file Archive.cpp.
References llvm::CallingConv::C, llvm::errorCodeToError(), isECSymbol(), llvm::object::Archive::K_AIXBIG, llvm::object::Archive::K_BSD, llvm::object::Archive::K_DARWIN64, llvm::object::Archive::K_GNU, llvm::object::Archive::K_GNU64, llvm::Offset, llvm::object::parse_failed, llvm::support::endian::read16le(), llvm::support::endian::read32be(), llvm::support::endian::read32le(), llvm::support::endian::read64be(), llvm::support::endian::read64le(), and llvm::Error::success().
Referenced by llvm::object::Archive::findSym().
getName()
StringRef Archive::Symbol::getName () const
Definition at line 1014 of file Archive.cpp.
References llvm::StringRef::begin(), and isECSymbol().
Referenced by llvm::object::Archive::findSym().
getNext()
Archive::Symbol Archive::Symbol::getNext () const
Definition at line 1090 of file Archive.cpp.
References isECSymbol(), llvm::object::Archive::K_BSD, llvm::support::endian::read32le(), and Symbol().
isECSymbol()
bool Archive::Symbol::isECSymbol () const
Definition at line 1006 of file Archive.cpp.
Referenced by getMember(), getName(), and getNext().
operator==()
bool llvm::object::Archive::Symbol::operator== (const Symbol & other) const inline
Definition at line 301 of file Archive.h.
References Symbol().
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp