LLVM: llvm::RopePieceBTree Class Reference
llvm::RopePieceBTree Class Reference
#include "llvm/ADT/RewriteRope.h"
Public Types
using iterator = RopePieceBTreeIterator
Public Member Functions
LLVM_ABI RopePieceBTree ()
LLVM_ABI RopePieceBTree (const RopePieceBTree &RHS)
RopePieceBTree & operator= (const RopePieceBTree &)=delete
LLVM_ABI ~RopePieceBTree ()
iterator begin () const
iterator end () const
LLVM_ABI unsigned size () const
unsigned empty () const
LLVM_ABI void clear ()
LLVM_ABI void insert (unsigned Offset, const RopePiece &R)
LLVM_ABI void erase (unsigned Offset, unsigned NumBytes)
Detailed Description
Definition at line 142 of file RewriteRope.h.
Member Typedef Documentation
iterator
using llvm::RopePieceBTree::iterator = RopePieceBTreeIterator
Definition at line 151 of file RewriteRope.h.
Constructor & Destructor Documentation
RopePieceBTree() [1/2]
RopePieceBTree::RopePieceBTree ()
Definition at line 718 of file RewriteRope.cpp.
Referenced by operator=(), and RopePieceBTree().
RopePieceBTree() [2/2]
RopePieceBTree::RopePieceBTree (const RopePieceBTree & RHS)
Definition at line 720 of file RewriteRope.cpp.
References assert(), and RopePieceBTree().
~RopePieceBTree()
RopePieceBTree::~RopePieceBTree ()
Definition at line 725 of file RewriteRope.cpp.
References getRoot().
Member Function Documentation
begin()
iterator llvm::RopePieceBTree::begin () const inline
Definition at line 153 of file RewriteRope.h.
clear()
void RopePieceBTree::clear ()
Definition at line 729 of file RewriteRope.cpp.
References llvm::dyn_cast(), and getRoot().
empty()
unsigned llvm::RopePieceBTree::empty () const inline
Definition at line 156 of file RewriteRope.h.
References size().
end()
iterator llvm::RopePieceBTree::end () const inline
Definition at line 154 of file RewriteRope.h.
erase()
void RopePieceBTree::erase (unsigned Offset, unsigned NumBytes)
Definition at line 748 of file RewriteRope.cpp.
References getRoot(), llvm::Offset, and llvm::split().
insert()
void RopePieceBTree::insert (unsigned Offset, const RopePiece & R)
Definition at line 738 of file RewriteRope.cpp.
References getRoot(), insert(), llvm::Offset, and llvm::split().
Referenced by insert().
operator=()
RopePieceBTree & llvm::RopePieceBTree::operator= (const RopePieceBTree &) delete
References LLVM_ABI, and RopePieceBTree().
size()
unsigned RopePieceBTree::size () const
Definition at line 727 of file RewriteRope.cpp.
References getRoot().
Referenced by empty().
The documentation for this class was generated from the following files:
include/llvm/ADT/RewriteRope.h
lib/Support/RewriteRope.cpp