LLVM: llvm::InstructionSelect Class Reference
llvm::InstructionSelect Class Reference
This pass is responsible for selecting generic machine instructions to target-specific instructions.
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
Classes
class MIIteratorMaintainer
This class observes instruction insertions/removals.
Public Member Functions
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
MachineFunctionProperties getRequiredProperties () const override
MachineFunctionProperties getSetProperties () const override
InstructionSelect (CodeGenOptLevel OL=CodeGenOptLevel::Default, char &PassID=ID)
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
bool selectMachineFunction (MachineFunction &MF)
void setInstructionSelector (InstructionSelector *NewISel)
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Protected Member Functions
bool selectInstr (MachineInstr &MI)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes
InstructionSelector * ISel = nullptr
GISelValueTracking * VT = nullptr
BlockFrequencyInfo * BFI = nullptr
ProfileSummaryInfo * PSI = nullptr
CodeGenOptLevel OptLevel = CodeGenOptLevel::None
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
This pass is responsible for selecting generic machine instructions to target-specific instructions.
It relies on the InstructionSelector provided by the target. Selection is done by examining blocks in post-order, and instructions in reverse order.
Postcondition
for all inst in MF: not isPreISelGenericOpcode(inst.opcode)
Definition at line 36 of file InstructionSelect.h.
Constructor & Destructor Documentation
InstructionSelect()
Select target instructions out of generic false InstructionSelect::InstructionSelect (CodeGenOptLevel OL = CodeGenOptLevel::Default, char & PassID = ID)
Definition at line 66 of file InstructionSelect.cpp.
References InstructionSelect(), llvm::MachineFunctionPass::MachineFunctionPass(), and OptLevel.
Referenced by InstructionSelect().
Member Function Documentation
getAnalysisUsage()
void InstructionSelect::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 121 of file InstructionSelect.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::LazyBlockFrequencyInfoPass::getLazyBFIAnalysisUsage(), llvm::getSelectionDAGFallbackAnalysisUsage(), llvm::None, and OptLevel.
getPassName()
StringRef llvm::InstructionSelect::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 39 of file InstructionSelect.h.
getRequiredProperties()
MachineFunctionProperties llvm::InstructionSelect::getRequiredProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 43 of file InstructionSelect.h.
getSetProperties()
MachineFunctionProperties llvm::InstructionSelect::getSetProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 50 of file InstructionSelect.h.
runOnMachineFunction()
bool InstructionSelect::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 134 of file InstructionSelect.cpp.
References BFI, llvm::Pass::getAnalysis(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstructionSelector(), llvm::TargetMachine::getOptLevel(), llvm::MachineFunction::getProperties(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::Function::hasOptNone(), ISel, llvm::make_scope_exit(), llvm::None, OptLevel, PSI, selectMachineFunction(), and VT.
selectInstr()
bool InstructionSelect::selectInstr (MachineInstr & MI) protected
Definition at line 350 of file InstructionSelect.cpp.
References assert(), llvm::canReplaceReg(), llvm::dbgs(), ISel, llvm::isPreISelGenericOptimizationHint(), llvm::isTriviallyDead(), LLVM_DEBUG, MI, MRI, and llvm::salvageDebugInfo().
Referenced by selectMachineFunction().
selectMachineFunction()
bool InstructionSelect::selectMachineFunction (MachineFunction & MF)
Definition at line 158 of file InstructionSelect.cpp.
References llvm::GISelObserverWrapper::addObserver(), assert(), BFI, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains(), CoveragePrefix, llvm::CodeGenCoverage::covered(), llvm::dbgs(), llvm::DisableGISelLegalityCheck, llvm::CodeGenCoverage::emit(), llvm::TargetLoweringBase::finalizeLowering(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getName(), llvm::MachineFunction::getProperties(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::Function::getSubprogram(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::MachineFrameInfo::hasCalls(), llvm::MachineFunction::hasInlineAsm(), I, llvm::Register::index2VirtReg(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), ISel, llvm::details::FixedOrScalableQuantity< TypeSize, uint64_t >::isKnownGT(), llvm::Register::isVirtual(), LLVM_DEBUG, llvm::machineFunctionIsIllegal(), MBB, MI, llvm::InstructionSelect::MIIteratorMaintainer::MII, MORE, MRI, llvm::post_order(), PSI, llvm::InstructionSelect::MIIteratorMaintainer::reportFullyCreatedInstrs(), llvm::reportGISelFailure(), selectInstr(), llvm::MachineFrameInfo::setHasCalls(), llvm::MachineFunction::setHasInlineAsm(), llvm::DebugCounter::shouldExecute(), llvm::MachineFunction::size(), TRI, and VT.
Referenced by runOnMachineFunction().
setInstructionSelector()
void llvm::InstructionSelect::setInstructionSelector (InstructionSelector * NewISel) inline
Definition at line 59 of file InstructionSelect.h.
References ISel.
Member Data Documentation
BFI
BlockFrequencyInfo* llvm::InstructionSelect::BFI = nullptr protected
Definition at line 66 of file InstructionSelect.h.
Referenced by runOnMachineFunction(), and selectMachineFunction().
ID
char InstructionSelect::ID = 0 static
Definition at line 38 of file InstructionSelect.h.
ISel
InstructionSelector* llvm::InstructionSelect::ISel = nullptr protected
Definition at line 64 of file InstructionSelect.h.
Referenced by runOnMachineFunction(), selectInstr(), selectMachineFunction(), and setInstructionSelector().
OptLevel
CodeGenOptLevel llvm::InstructionSelect::OptLevel = CodeGenOptLevel::None protected
Definition at line 69 of file InstructionSelect.h.
Referenced by getAnalysisUsage(), InstructionSelect(), and runOnMachineFunction().
PSI
ProfileSummaryInfo* llvm::InstructionSelect::PSI = nullptr protected
Definition at line 67 of file InstructionSelect.h.
Referenced by runOnMachineFunction(), and selectMachineFunction().
VT
GISelValueTracking* llvm::InstructionSelect::VT = nullptr protected
Definition at line 65 of file InstructionSelect.h.
Referenced by runOnMachineFunction(), and selectMachineFunction().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/InstructionSelect.h
lib/CodeGen/GlobalISel/InstructionSelect.cpp