LLVM: llvm::jitlink::BasicLayout Class Reference
llvm::jitlink::BasicLayout Class Reference
BasicLayout simplifies the implementation of JITLinkMemoryManagers.
#include "llvm/ExecutionEngine/JITLink/JITLinkMemoryManager.h"
Classes
struct ContiguousPageBasedLayoutSizes
A convenience class that further groups segments based on memory deallocation policy.
class Segment
The Alignment, ContentSize and ZeroFillSize of each segment will be pre-filled from the Graph.
Public Member Functions
LLVM_ABI BasicLayout (LinkGraph &G)
LinkGraph & getGraph ()
Return a reference to the graph this allocation was created from.
LLVM_ABI Expected< ContiguousPageBasedLayoutSizes > getContiguousPageBasedLayoutSizes (uint64_t PageSize)
Returns the total number of required to allocate all segments (with each segment padded out to page size) for all standard segments, and all finalize segments.
iterator_range< SegmentMap::iterator > segments ()
Returns an iterator over the segments of the layout.
LLVM_ABI Error apply ()
Apply the layout to the graph.
LLVM_ABI orc::shared::AllocActions & graphAllocActions ()
Returns a reference to the AllocActions in the graph.
Detailed Description
BasicLayout simplifies the implementation of JITLinkMemoryManagers.
BasicLayout groups Sections into Segments based on their memory protection and deallocation policies. JITLinkMemoryManagers can construct a BasicLayout from a Graph, and then assign working memory and addresses to each of the Segments. These addreses will be mapped back onto the Graph blocks in the apply method.
Definition at line 214 of file JITLinkMemoryManager.h.
Constructor & Destructor Documentation
BasicLayout()
llvm::jitlink::BasicLayout::BasicLayout (LinkGraph & G)
Definition at line 24 of file JITLinkMemoryManager.cpp.
References B(), for(), if(), and LLVM_LIKELY.
Member Function Documentation
apply()
Error llvm::jitlink::BasicLayout::apply ()
Apply the layout to the graph.
Definition at line 102 of file JITLinkMemoryManager.cpp.
References llvm::jitlink::alignToBlock(), apply(), assert(), B(), and llvm::Error::success().
Referenced by llvm::jitlink::InProcessMemoryManager::allocate(), llvm::orc::MapperJITLinkMemoryManager::allocate(), and apply().
getContiguousPageBasedLayoutSizes()
Expected< BasicLayout::ContiguousPageBasedLayoutSizes > llvm::jitlink::BasicLayout::getContiguousPageBasedLayoutSizes (uint64_t PageSize)
Returns the total number of required to allocate all segments (with each segment padded out to page size) for all standard segments, and all finalize segments.
This is a convenience function for the common case where the segments will be allocated contiguously.
This function will return an error if any segment has an alignment that is higher than a page.
Definition at line 81 of file JITLinkMemoryManager.cpp.
References llvm::alignTo(), llvm::jitlink::BasicLayout::ContiguousPageBasedLayoutSizes::FinalizeSegs, getContiguousPageBasedLayoutSizes(), llvm::inconvertibleErrorCode(), llvm::make_error(), PageSize, segments(), llvm::orc::Standard, and llvm::jitlink::BasicLayout::ContiguousPageBasedLayoutSizes::StandardSegs.
Referenced by llvm::jitlink::InProcessMemoryManager::allocate(), llvm::orc::EPCGenericJITLinkMemoryManager::allocate(), llvm::orc::MapperJITLinkMemoryManager::allocate(), and getContiguousPageBasedLayoutSizes().
getGraph()
LinkGraph & llvm::jitlink::BasicLayout::getGraph () inline
Return a reference to the graph this allocation was created from.
Definition at line 257 of file JITLinkMemoryManager.h.
graphAllocActions()
orc::shared::AllocActions & llvm::jitlink::BasicLayout::graphAllocActions ()
Returns a reference to the AllocActions in the graph.
This convenience function saves callers from having to #include LinkGraph.h if all they need are allocation actions.
Definition at line 142 of file JITLinkMemoryManager.cpp.
References graphAllocActions().
Referenced by graphAllocActions().
segments()
iterator_range< SegmentMap::iterator > llvm::jitlink::BasicLayout::segments () inline
Returns an iterator over the segments of the layout.
Definition at line 272 of file JITLinkMemoryManager.h.
Referenced by llvm::jitlink::InProcessMemoryManager::allocate(), llvm::orc::MapperJITLinkMemoryManager::allocate(), and getContiguousPageBasedLayoutSizes().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLinkMemoryManager.h
lib/ExecutionEngine/JITLink/JITLinkMemoryManager.cpp