LLVM: llvm::VPBlockBase Class Reference
llvm::VPBlockBase Class Reference abstract
VPBlockBase is the building block of the Hierarchical Control-Flow Graph.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using VPBlockTy = enum { VPRegionBlockSC, VPBasicBlockSC, VPIRBasicBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
using VPBlocksTy = SmallVectorImpl<VPBlockBase *>
Public Member Functions
virtual ~VPBlockBase ()=default
const std::string & getName () const
void setName (const Twine &newName)
unsigned getVPBlockID () const
VPRegionBlock * getParent ()
const VPRegionBlock * getParent () const
VPlan * getPlan ()
const VPlan * getPlan () const
void setPlan (VPlan *ParentPlan)
Sets the pointer of the plan containing the block.
void setParent (VPRegionBlock *P)
const VPBasicBlock * getEntryBasicBlock () const
VPBasicBlock * getEntryBasicBlock ()
const VPBasicBlock * getExitingBasicBlock () const
VPBasicBlock * getExitingBasicBlock ()
const VPBlocksTy & getSuccessors () const
VPBlocksTy & getSuccessors ()
iterator_range< VPBlockBase ** > successors ()
iterator_range< VPBlockBase ** > predecessors ()
const VPBlocksTy & getPredecessors () const
VPBlocksTy & getPredecessors ()
VPBlockBase * getSingleSuccessor () const
VPBlockBase * getSinglePredecessor () const
size_t getNumSuccessors () const
size_t getNumPredecessors () const
VPBlockBase * getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
VPBlockBase * getEnclosingBlockWithPredecessors ()
const VPBlocksTy & getHierarchicalSuccessors ()
VPBlockBase * getSingleHierarchicalSuccessor ()
const VPBlocksTy & getHierarchicalPredecessors ()
VPBlockBase * getSingleHierarchicalPredecessor ()
void setOneSuccessor (VPBlockBase *Successor)
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
void setTwoSuccessors (VPBlockBase *IfTrue, VPBlockBase *IfFalse)
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
void setPredecessors (ArrayRef< VPBlockBase * > NewPreds)
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
void setSuccessors (ArrayRef< VPBlockBase * > NewSuccs)
Set each VPBasicBlock in NewSuccss as successor of this VPBlockBase.
void clearPredecessors ()
Remove all the predecessor of this block.
void clearSuccessors ()
Remove all the successors of this block.
void swapPredecessors ()
Swap predecessors of the block.
void swapSuccessors ()
Swap successors of the block. The block must have exactly 2 successors.
unsigned getIndexForPredecessor (const VPBlockBase *Pred) const
Returns the index for Pred in the blocks predecessors list.
unsigned getIndexForSuccessor (const VPBlockBase *Succ) const
Returns the index for Succ in the blocks successor list.
virtual void execute (VPTransformState *State)=0
The method which generates the output IR that correspond to this VPBlockBase, thereby "executing" the VPlan.
virtual InstructionCost cost (ElementCount VF, VPCostContext &Ctx)=0
Return the cost of the block.
bool isLegalToHoistInto ()
Return true if it is legal to hoist instructions into this block.
void printAsOperand (raw_ostream &OS, bool PrintType=false) const
virtual void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const =0
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
void printSuccessors (raw_ostream &O, const Twine &Indent) const
Print the successors of this block to O, prefixing all lines with Indent.
LLVM_DUMP_METHOD void dump () const
Dump this VPBlockBase to dbgs().
virtual VPBlockBase * clone ()=0
Clone the current block and it's recipes without updating the operands of the cloned recipes, including all blocks in the single-entry single-exit region for VPRegionBlocks.
Protected Member Functions
VPBlockBase (const unsigned char SC, const std::string &N)
Friends
class VPBlockUtils
Detailed Description
VPBlockBase is the building block of the Hierarchical Control-Flow Graph.
A VPBlockBase can be either a VPBasicBlock or a VPRegionBlock.
Definition at line 81 of file VPlan.h.
Member Typedef Documentation
VPBlocksTy
using llvm::VPBlockBase::VPBlocksTy = SmallVectorImpl<VPBlockBase *>
Definition at line 160 of file VPlan.h.
VPBlockTy
using llvm::VPBlockBase::VPBlockTy = enum { VPRegionBlockSC, VPBasicBlockSC, VPIRBasicBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
Values of this enumeration are kept in the SubclassID field of the VPBlockBase objects. They are used for concrete type identification.
Definition at line 158 of file VPlan.h.
Constructor & Destructor Documentation
VPBlockBase()
llvm::VPBlockBase::VPBlockBase (const unsigned char SC, const std::string & N) inline protected
Definition at line 150 of file VPlan.h.
References N.
Referenced by llvm::VPBasicBlock::classof(), llvm::VPRegionBlock::classof(), clone(), llvm::VPRegionBlock::clone(), llvm::VPBasicBlock::connectToPredecessors(), llvm::VPRegionBlock::cost(), llvm::VPRegionBlock::dissolveToCFGLoop(), llvm::VPBasicBlock::execute(), llvm::VPRegionBlock::execute(), llvm::VPBasicBlock::getCFGPredecessor(), getEnclosingBlockWithPredecessors(), getEnclosingBlockWithSuccessors(), llvm::VPRegionBlock::getEntry(), llvm::VPRegionBlock::getEntry(), getEntryBasicBlock(), getEntryBasicBlock(), llvm::VPRegionBlock::getExiting(), llvm::VPRegionBlock::getExiting(), getExitingBasicBlock(), getExitingBasicBlock(), getIndexForPredecessor(), getIndexForSuccessor(), getSingleHierarchicalPredecessor(), getSingleHierarchicalSuccessor(), getSinglePredecessor(), getSingleSuccessor(), llvm::VPRegionBlock::setEntry(), llvm::VPRegionBlock::setExiting(), setOneSuccessor(), setTwoSuccessors(), llvm::VPBasicBlock::VPBasicBlock(), VPBlockUtils, llvm::VPBasicBlock::VPlan, and llvm::VPRegionBlock::VPlan.
~VPBlockBase()
virtual llvm::VPBlockBase::~VPBlockBase () virtual default
Member Function Documentation
clearPredecessors()
void llvm::VPBlockBase::clearPredecessors () inline
Remove all the predecessor of this block.
Definition at line 304 of file VPlan.h.
Referenced by llvm::VPBlockUtils::insertBlockBefore(), and llvm::VPBlockUtils::reassociateBlocks().
clearSuccessors()
void llvm::VPBlockBase::clearSuccessors () inline
Remove all the successors of this block.
Definition at line 307 of file VPlan.h.
Referenced by llvm::VPBlockUtils::insertBlockAfter(), and llvm::VPBlockUtils::reassociateBlocks().
clone()
virtual VPBlockBase * llvm::VPBlockBase::clone () pure virtual
Clone the current block and it's recipes without updating the operands of the cloned recipes, including all blocks in the single-entry single-exit region for VPRegionBlocks.
Implemented in llvm::VPBasicBlock, llvm::VPIRBasicBlock, and llvm::VPRegionBlock.
References VPBlockBase().
cost()
virtual InstructionCost llvm::VPBlockBase::cost (ElementCount VF, VPCostContext & Ctx) pure virtual
Return the cost of the block.
Implemented in llvm::VPBasicBlock, and llvm::VPRegionBlock.
dump()
LLVM_DUMP_METHOD void llvm::VPBlockBase::dump () const inline
Dump this VPBlockBase to dbgs().
Definition at line 374 of file VPlan.h.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
execute()
virtual void llvm::VPBlockBase::execute (VPTransformState * State) pure virtual
The method which generates the output IR that correspond to this VPBlockBase, thereby "executing" the VPlan.
Implemented in llvm::VPBasicBlock, llvm::VPIRBasicBlock, and llvm::VPRegionBlock.
getEnclosingBlockWithPredecessors()
VPBlockBase * VPBlockBase::getEnclosingBlockWithPredecessors ()
Returns
the closest enclosing block starting from "this", which has predecessors.
the root enclosing block if all enclosing blocks have no predecessors.
Definition at line 202 of file VPlan.cpp.
References assert(), and VPBlockBase().
Referenced by getHierarchicalPredecessors(), and getSingleHierarchicalPredecessor().
getEnclosingBlockWithSuccessors()
VPBlockBase * VPBlockBase::getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
Returns
the closest enclosing block starting from "this", which has successors.
the root enclosing block if all enclosing blocks have no successors.
Definition at line 194 of file VPlan.cpp.
References assert(), and VPBlockBase().
Referenced by getHierarchicalSuccessors(), and getSingleHierarchicalSuccessor().
getEntryBasicBlock() [1/2]
VPBasicBlock * VPBlockBase::getEntryBasicBlock ()
Definition at line 167 of file VPlan.cpp.
References llvm::Block, llvm::cast(), llvm::dyn_cast(), llvm::RegionBase< Tr >::getEntry(), and VPBlockBase().
getEntryBasicBlock() [2/2]
const VPBasicBlock * VPBlockBase::getEntryBasicBlock () const
Returns
the VPBasicBlock that is the entry of this VPBlockBase, recursively, if the latter is a VPRegionBlock. Otherwise, if this VPBlockBase is a VPBasicBlock, it is returned.
the VPBasicBlock that is the entry of Block, possibly indirectly.
Definition at line 160 of file VPlan.cpp.
References llvm::Block, llvm::cast(), llvm::dyn_cast(), llvm::RegionBase< Tr >::getEntry(), and VPBlockBase().
Referenced by addExitUsersForFirstOrderRecurrences(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::calculateRegisterUsageForPlan(), llvm::VPlanTransforms::clearReductionWrapFlags(), collectAllHeaderMasks(), llvm::VPlanTransforms::createLoopRegions(), createScalarIVSteps(), llvm::VPlan::getCanonicalIV(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::introduceMasksAndLinearize(), legalizeAndOptimizeInductions(), llvm::VPlanTransforms::narrowInterleaveGroups(), optimizeVectorInductionWidthForTCAndVFUF(), preparePlanForEpilogueVectorLoop(), preparePlanForMainVectorLoop(), removeRedundantCanonicalIVs(), removeRedundantExpandSCEVRecipes(), removeRedundantInductionCasts(), sinkScalarOperands(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::tryAddExplicitVectorLength(), and llvm::VPlanTransforms::unrollByUF().
getExitingBasicBlock() [1/2]
VPBasicBlock * VPBlockBase::getExitingBasicBlock ()
Definition at line 187 of file VPlan.cpp.
References llvm::Block, llvm::cast(), llvm::dyn_cast(), and VPBlockBase().
getExitingBasicBlock() [2/2]
const VPBasicBlock * VPBlockBase::getExitingBasicBlock () const
Returns
the VPBasicBlock that is the exiting this VPBlockBase, recursively, if the latter is a VPRegionBlock. Otherwise, if this VPBlockBase is a VPBasicBlock, it is returned.
the VPBasicBlock that is the exit of Block, possibly indirectly.
Definition at line 180 of file VPlan.cpp.
References llvm::Block, llvm::cast(), llvm::dyn_cast(), and VPBlockBase().
Referenced by addVPLaneMaskPhiAndUpdateExitBranch(), expandVPWidenIntOrFpInduction(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPBasicBlock::isExiting(), simplifyBranchConditionForVFAndUF(), and sinkScalarOperands().
getHierarchicalPredecessors()
const VPBlocksTy & llvm::VPBlockBase::getHierarchicalPredecessors () inline
Returns
the predecessors either attached directly to this VPBlockBase or, if this VPBlockBase is the entry block of a VPRegionBlock and has no predecessors of its own, search recursively for the first enclosing VPRegionBlock that has predecessors and return them. If no such VPRegionBlock exists, return the (empty) predecessors of the topmost VPBlockBase reached.
Definition at line 255 of file VPlan.h.
References getEnclosingBlockWithPredecessors().
getHierarchicalSuccessors()
const VPBlocksTy & llvm::VPBlockBase::getHierarchicalSuccessors () inline
Returns
the successors either attached directly to this VPBlockBase or, if this VPBlockBase is the exit block of a VPRegionBlock and has no successors of its own, search recursively for the first enclosing VPRegionBlock that has successors and return them. If no such VPRegionBlock exists, return the (empty) successors of the topmost VPBlockBase reached.
Definition at line 239 of file VPlan.h.
References getEnclosingBlockWithSuccessors().
Referenced by llvm::VPBasicBlock::connectToPredecessors(), and llvm::VPIRBasicBlock::execute().
getIndexForPredecessor()
unsigned llvm::VPBlockBase::getIndexForPredecessor (const VPBlockBase * Pred) const inline
Returns the index for Pred in the blocks predecessors list.
Definition at line 325 of file VPlan.h.
References assert(), llvm::count(), llvm::find(), and VPBlockBase().
Referenced by llvm::VPBlockUtils::insertOnEdge().
getIndexForSuccessor()
unsigned llvm::VPBlockBase::getIndexForSuccessor (const VPBlockBase * Succ) const inline
Returns the index for Succ in the blocks successor list.
Definition at line 332 of file VPlan.h.
References assert(), llvm::count(), llvm::find(), and VPBlockBase().
Referenced by llvm::VPBlockUtils::insertOnEdge().
getName()
const std::string & llvm::VPBlockBase::getName () const inline
Definition at line 164 of file VPlan.h.
Referenced by llvm::VPBasicBlock::clone(), llvm::VPRegionBlock::clone(), llvm::VPBasicBlock::executeRecipes(), llvm::VPBasicBlock::print(), llvm::VPRegionBlock::print(), llvm::VPBasicBlock::splitAt(), and llvm::VPIRBasicBlock::VPlan.
getNumPredecessors()
size_t llvm::VPBlockBase::getNumPredecessors () const inline
Definition at line 220 of file VPlan.h.
Referenced by llvm::VPlanTransforms::attachCheckBlock(), llvm::LoopVectorizationPlanner::executePlan(), llvm::VPBasicBlock::getCFGPredecessor(), llvm::VPlanTransforms::handleUncountableEarlyExit(), llvm::VPlan::hasScalarTail(), llvm::InnerLoopVectorizer::introduceCheckBlockInVPlan(), and removeBranchOnConst().
getNumSuccessors()
size_t llvm::VPBlockBase::getNumSuccessors () const inline
Definition at line 219 of file VPlan.h.
Referenced by llvm::VPBlockUtils::connectBlocks(), llvm::VPlan::duplicate(), llvm::VPIRBasicBlock::execute(), hasConditionalTerminator(), llvm::InnerLoopVectorizer::introduceCheckBlockInVPlan(), llvm::VPBlockUtils::isLatch(), and llvm::VPlanTransforms::prepareForVectorization().
getParent() [1/2]
VPRegionBlock * llvm::VPBlockBase::getParent () inline
Definition at line 173 of file VPlan.h.
Referenced by addReplicateRegions(), cloneFrom(), llvm::VPBlockUtils::connectBlocks(), llvm::VPRegionBlock::dissolveToCFGLoop(), llvm::VPBasicBlock::execute(), llvm::VPBasicBlock::getCFGPredecessor(), llvm::VPBasicBlock::getEnclosingLoopRegion(), llvm::VPBasicBlock::getEnclosingLoopRegion(), hasConditionalTerminator(), hoistPreviousBeforeFORUsers(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertBlockBefore(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPBasicBlock::isExiting(), llvm::vputils::isSingleScalar(), scalarizeInstruction(), setOneSuccessor(), and llvm::VPRecipeBuilder::tryToCreateWidenRecipe().
getParent() [2/2]
const VPRegionBlock * llvm::VPBlockBase::getParent () const inline
Definition at line 174 of file VPlan.h.
getPlan() [1/2]
VPlan * VPBlockBase::getPlan ()
Returns
A pointer to the plan containing the current block.
Definition at line 155 of file VPlan.cpp.
References getPlanEntry().
Referenced by llvm::VPBasicBlock::clone(), llvm::VPIRBasicBlock::clone(), llvm::VPRegionBlock::clone(), llvm::VPBasicBlock::connectToPredecessors(), llvm::VPRegionBlock::dissolveToCFGLoop(), expandVPWidenIntOrFpInduction(), llvm::VPSlotTracker::getOrCreateName(), llvm::operator<<(), print(), replaceVPBBWithIRVPBB(), scalarizeInstruction(), and llvm::VPBasicBlock::splitAt().
getPlan() [2/2]
const VPlan * VPBlockBase::getPlan () const
Definition at line 157 of file VPlan.cpp.
References getPlanEntry().
getPredecessors() [1/2]
VPBlocksTy & llvm::VPBlockBase::getPredecessors () inline
Definition at line 205 of file VPlan.h.
getPredecessors() [2/2]
const VPBlocksTy & llvm::VPBlockBase::getPredecessors () const inline
Definition at line 204 of file VPlan.h.
Referenced by canonicalHeaderAndLatch(), cloneFrom(), llvm::VPBlockUtils::connectBlocks(), llvm::VPBasicBlock::connectToPredecessors(), createLoopRegion(), llvm::VPIRPhi::execute(), llvm::VPBasicBlock::getCFGPredecessor(), llvm::VPlanTransforms::handleUncountableEarlyExit(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertBlockBefore(), llvm::VPBlockUtils::isHeader(), llvm::VPlanTransforms::prepareForVectorization(), llvm::VPIRPhi::print(), llvm::VPBlockUtils::reassociateBlocks(), removeBranchOnConst(), and llvm::VPRegionBlock::setEntry().
getSingleHierarchicalPredecessor()
VPBlockBase * llvm::VPBlockBase::getSingleHierarchicalPredecessor () inline
Returns
the hierarchical predecessor of this VPBlockBase if it has a single hierarchical predecessor. Otherwise return a null pointer.
Definition at line 261 of file VPlan.h.
References getEnclosingBlockWithPredecessors(), and VPBlockBase().
Referenced by createScalarIVSteps(), and llvm::VPBasicBlock::execute().
getSingleHierarchicalSuccessor()
VPBlockBase * llvm::VPBlockBase::getSingleHierarchicalSuccessor () inline
Returns
the hierarchical successor of this VPBlockBase if it has a single hierarchical successor. Otherwise return a null pointer.
Definition at line 245 of file VPlan.h.
References getEnclosingBlockWithSuccessors(), and VPBlockBase().
getSinglePredecessor()
VPBlockBase * llvm::VPBlockBase::getSinglePredecessor () const inline
Returns
the predecessor of this VPBlockBase if it has a single predecessor. Otherwise return a null pointer.
Definition at line 215 of file VPlan.h.
References VPBlockBase().
Referenced by addScalarResumePhis(), llvm::VPlanTransforms::attachCheckBlock(), llvm::VPRegionBlock::dissolveToCFGLoop(), llvm::VPRegionBlock::getPreheaderVPBB(), llvm::VPlan::getVectorPreheader(), llvm::VPlanTransforms::handleUncountableEarlyExit(), llvm::VPlan::hasScalarTail(), and simplifyBranchConditionForVFAndUF().
getSingleSuccessor()
VPBlockBase * llvm::VPBlockBase::getSingleSuccessor () const inline
Returns
the successor of this VPBlockBase if it has a single successor. Otherwise return a null pointer.
Definition at line 209 of file VPlan.h.
References VPBlockBase().
Referenced by addExitUsersForFirstOrderRecurrences(), addScalarResumePhis(), llvm::VPBasicBlock::connectToPredecessors(), createLoopRegion(), llvm::VPRegionBlock::dissolveToCFGLoop(), llvm::VPIRBasicBlock::execute(), llvm::VPlan::getCanonicalIV(), llvm::VPlan::getMiddleBlock(), mergeReplicateRegionsIntoSuccessors(), llvm::VPlanTransforms::prepareForVectorization(), simplifyBranchConditionForVFAndUF(), and sinkScalarOperands().
getSuccessors() [1/2]
VPBlocksTy & llvm::VPBlockBase::getSuccessors () inline
Definition at line 199 of file VPlan.h.
getSuccessors() [2/2]
const VPBlocksTy & llvm::VPBlockBase::getSuccessors () const inline
Definition at line 198 of file VPlan.h.
Referenced by llvm::VPBlockUtils::connectBlocks(), llvm::VPRegionBlock::cost(), createCondBranch(), llvm::VPlanTransforms::handleUncountableEarlyExit(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertBlockBefore(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::InnerLoopVectorizer::introduceCheckBlockInVPlan(), llvm::VPlanTransforms::introduceMasksAndLinearize(), llvm::VPBlockUtils::isLatch(), llvm::VPlanTransforms::prepareForVectorization(), printSuccessors(), llvm::VPBlockUtils::reassociateBlocks(), llvm::VPRegionBlock::setExiting(), and sinkScalarOperands().
getVPBlockID()
unsigned llvm::VPBlockBase::getVPBlockID () const inline
Returns
an ID for the concrete type of this object. This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves.
Definition at line 171 of file VPlan.h.
isLegalToHoistInto()
bool llvm::VPBlockBase::isLegalToHoistInto () inline
Return true if it is legal to hoist instructions into this block.
Definition at line 346 of file VPlan.h.
predecessors()
iterator_range< VPBlockBase ** > llvm::VPBlockBase::predecessors () inline
Definition at line 202 of file VPlan.h.
Referenced by llvm::VPBlockUtils::insertBlockBefore().
print() [1/2]
void VPBlockBase::print (raw_ostream & O) const
Print plain-text dump of this VPlan to O.
Definition at line 698 of file VPlan.cpp.
References getPlan(), and print().
print() [2/2]
virtual void llvm::VPBlockBase::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const pure virtual
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
SlotTracker is used to print unnamed VPValue's using consequtive numbers.
Note that the numbering is applied to the whole VPlan, so printing individual blocks is consistent with the whole VPlan printing.
Implemented in llvm::VPBasicBlock, and llvm::VPRegionBlock.
References printSuccessors().
Referenced by print().
printAsOperand()
void llvm::VPBlockBase::printAsOperand (raw_ostream & OS, bool PrintType = false) const inline
Definition at line 353 of file VPlan.h.
References getName().
Referenced by llvm::VPPhiAccessors::printPhiOperands().
printSuccessors()
void VPBlockBase::printSuccessors (raw_ostream & O, const Twine & Indent) const
Print the successors of this block to O, prefixing all lines with Indent.
Definition at line 703 of file VPlan.cpp.
References getSuccessors().
Referenced by llvm::VPBasicBlock::print(), print(), and llvm::VPRegionBlock::print().
setName()
void llvm::VPBlockBase::setName (const Twine & newName) inline
Definition at line 166 of file VPlan.h.
References llvm::Twine::str().
Referenced by llvm::LoopVectorizationPlanner::buildVPlans(), llvm::VPlanTransforms::createLoopRegions(), preparePlanForEpilogueVectorLoop(), and llvm::LoopVectorizePass::processLoop().
setOneSuccessor()
void llvm::VPBlockBase::setOneSuccessor (VPBlockBase * Successor) inline
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
This VPBlockBase is not added as predecessor of Successor. This VPBlockBase must have no successors.
Definition at line 268 of file VPlan.h.
References assert(), getParent(), llvm::Successor, and VPBlockBase().
setParent()
void llvm::VPBlockBase::setParent (VPRegionBlock * P) inline
Definition at line 184 of file VPlan.h.
References P.
Referenced by createLoopRegion(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertBlockBefore(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPRegionBlock::setEntry(), and llvm::VPRegionBlock::setExiting().
setPlan()
void VPBlockBase::setPlan (VPlan * ParentPlan)
Sets the pointer of the plan containing the block.
The block must be the entry block into the VPlan.
Definition at line 174 of file VPlan.cpp.
References assert(), and llvm::VPlan::getEntry().
Referenced by llvm::VPlan::setEntry().
setPredecessors()
void llvm::VPBlockBase::setPredecessors (ArrayRef< VPBlockBase * > NewPreds) inline
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
This VPBlockBase must have no predecessors. This VPBlockBase is not added as successor of any VPBasicBlock in NewPreds.
Definition at line 288 of file VPlan.h.
References assert().
Referenced by cloneFrom(), and llvm::VPBlockUtils::insertTwoBlocksAfter().
setSuccessors()
void llvm::VPBlockBase::setSuccessors (ArrayRef< VPBlockBase * > NewSuccs) inline
Set each VPBasicBlock in NewSuccss as successor of this VPBlockBase.
This VPBlockBase must have no successors. This VPBlockBase is not added as predecessor of any VPBasicBlock in NewSuccs.
Definition at line 297 of file VPlan.h.
References assert().
Referenced by cloneFrom().
setTwoSuccessors()
void llvm::VPBlockBase::setTwoSuccessors (VPBlockBase * IfTrue, VPBlockBase * IfFalse) inline
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
This VPBlockBase is not added as predecessor of IfTrue or IfFalse. This VPBlockBase must have no successors.
Definition at line 279 of file VPlan.h.
References assert(), and VPBlockBase().
Referenced by llvm::VPBlockUtils::insertTwoBlocksAfter().
successors()
iterator_range< VPBlockBase ** > llvm::VPBlockBase::successors () inline
Definition at line 201 of file VPlan.h.
Referenced by cloneFrom(), and llvm::VPBlockUtils::insertBlockAfter().
swapPredecessors()
void llvm::VPBlockBase::swapPredecessors () inline
Swap predecessors of the block.
The block must have exactly 2 predecessors.
Definition at line 311 of file VPlan.h.
References assert(), and std::swap().
Referenced by canonicalHeaderAndLatch().
swapSuccessors()
void llvm::VPBlockBase::swapSuccessors () inline
Swap successors of the block. The block must have exactly 2 successors.
Definition at line 319 of file VPlan.h.
References assert(), and std::swap().
Referenced by llvm::VPlanTransforms::attachCheckBlock(), llvm::VPlanTransforms::handleUncountableEarlyExit(), llvm::InnerLoopVectorizer::introduceCheckBlockInVPlan(), and llvm::VPlanTransforms::prepareForVectorization().
Friends And Related Symbol Documentation
VPBlockUtils
friend class VPBlockUtils friend
Definition at line 82 of file VPlan.h.
References llvm::Successor, VPBlockBase(), and VPBlockUtils.
Referenced by VPBlockUtils.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp