LLVM: llvm::dxil::RootSignatureBindingInfo Class Reference
llvm::dxil::RootSignatureBindingInfo Class Reference
#include "Target/DirectX/DXILRootSignature.h"
Public Types
using iterator
Public Member Functions
RootSignatureBindingInfo ()=default
RootSignatureBindingInfo (SmallDenseMap< const Function *, mcdxbc::RootSignatureDesc > Map)
iterator find (const Function *F)
iterator end ()
std::optional< mcdxbc::RootSignatureDesc > getDescForFunction (const Function *F)
Detailed Description
Definition at line 40 of file DXILRootSignature.h.
Member Typedef Documentation
iterator
using llvm::dxil::RootSignatureBindingInfo::iterator
Initial value:
      SmallDenseMap<const Function *, mcdxbc::RootSignatureDesc>::iterator
Definition at line 45 of file DXILRootSignature.h.
Constructor & Destructor Documentation
RootSignatureBindingInfo() [1/2]
llvm::dxil::RootSignatureBindingInfo::RootSignatureBindingInfo () default
RootSignatureBindingInfo() [2/2]
llvm::dxil::RootSignatureBindingInfo::RootSignatureBindingInfo (SmallDenseMap< const Function *, mcdxbc::RootSignatureDesc > Map) inline
Definition at line 49 of file DXILRootSignature.h.
Member Function Documentation
end()
iterator llvm::dxil::RootSignatureBindingInfo::end () inline
Definition at line 55 of file DXILRootSignature.h.
Referenced by getDescForFunction(), and llvm::dxil::RootSignatureAnalysisPrinter::run().
find()
iterator llvm::dxil::RootSignatureBindingInfo::find (const Function * F) inline
Definition at line 53 of file DXILRootSignature.h.
References F.
Referenced by getDescForFunction(), and llvm::dxil::RootSignatureAnalysisPrinter::run().
getDescForFunction()
std::optional< mcdxbc::RootSignatureDesc > llvm::dxil::RootSignatureBindingInfo::getDescForFunction (const Function * F) inline
Definition at line 58 of file DXILRootSignature.h.
References end(), F, and find().
The documentation for this class was generated from the following file:
lib/Target/DirectX/DXILRootSignature.h