LLVM: llvm::DIFixedPointType Class Reference
llvm::DIFixedPointType Class Reference
Fixed-point type.
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
enum FixedPointKind : unsigned { FixedPointBinary , FixedPointDecimal , FixedPointRational , LastFixedPointKind = FixedPointRational }
Public Types inherited from llvm::DIBasicType
enum class Signedness { Signed , Unsigned }
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
DEFINE_MDNODE_GET (DIFixedPointType,(unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, DIFlags Flags, unsigned Kind, int Factor, APInt Numerator, APInt Denominator),(Tag, Name, SizeInBits, AlignInBits, Encoding, Flags, Kind, Factor, Numerator, Denominator)) DEFINE_MDNODE_GET(DIFixedPointType
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Denominator DEFINE_MDNODE_GET (DIFixedPointType,(unsigned Tag, MDString *Name, Metadata *SizeInBits, uint32_t AlignInBits, unsigned Encoding, DIFlags Flags, unsigned Kind, int Factor, APInt Numerator, APInt Denominator),(Tag, Name, SizeInBits, AlignInBits, Encoding, Flags, Kind, Factor, Numerator, Denominator)) TempDIFixedPointType clone() const
bool isBinary () const
bool isDecimal () const
bool isRational () const
LLVM_ABI bool isSigned () const
FixedPointKind getKind () const
int getFactorRaw () const
int getFactor () const
const APInt & getNumeratorRaw () const
const APInt & getNumerator () const
const APInt & getDenominatorRaw () const
const APInt & getDenominator () const
Public Member Functions inherited from llvm::DIBasicType
DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, StringRef Name),(Tag, Name, 0, 0, 0, 0, FlagZero)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, MDString *Name, uint64_t SizeInBits),(Tag, Name, SizeInBits, 0, 0, 0, FlagZero)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, DIFlags Flags),(Tag, Name, SizeInBits, AlignInBits, Encoding, 0, Flags)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, DIFlags Flags),(Tag, Name, SizeInBits, AlignInBits, Encoding, NumExtraInhabitants, Flags)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags Flags TempDIBasicType clone () const
unsigned getEncoding () const
LLVM_ABI std::optional< Signedness > getSignedness () const
Return the signedness of this type, or std::nullopt if this type is neither signed nor unsigned.
Public Member Functions inherited from llvm::DIType
TempDIType clone () const
unsigned getLine () const
LLVM_ABI uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
uint32_t getNumExtraInhabitants () const
DIFlags getFlags () const
DIScope * getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
Metadata * getRawSizeInBits () const
uint64_t getSizeInBits () const
Metadata * getRawOffsetInBits () const
uint64_t getOffsetInBits () const
TempDIType cloneWithFlags (DIFlags NewFlags) const
Returns a new temporary DIType with updated Flags.
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isBitField () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isTypePassByValue () const
bool isTypePassByReference () const
bool isBigEndian () const
bool isLittleEndian () const
bool getExportSymbols () const
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
LLVM_ABI StringRef getName () const
LLVM_ABI DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
LLVM_ABI dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
LLVM_ABI TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
LLVM_ABI void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
LLVM_ABI void resolveCycles ()
Resolve cycles.
LLVM_ABI void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
LLVM_ABI bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
LLVM_ABI void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
LLVM_ABI void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
LLVM_ABI void dumpTree () const
User-friendly dump in tree shape.
LLVM_ABI void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static LLVM_ABI std::optional< FixedPointKind > getFixedPointKind (StringRef Str)
static LLVM_ABI const char * fixedPointKindString (FixedPointKind)
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIBasicType
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIType
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static LLVM_ABI DIFlags getFlag (StringRef Flag)
static LLVM_ABI StringRef getFlagString (DIFlags Flag)
static LLVM_ABI DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static LLVM_ABI void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static LLVM_ABI MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static LLVM_ABI MDNode * intersect (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericNoaliasAddrspace (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
static LLVM_ABI MDNode * getMergedMemProfMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCallsiteMetadata (MDNode *A, MDNode *B)
Public Attributes
unsigned Tag
unsigned StringRef Name
unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t uint32_t AlignInBits
unsigned StringRef uint64_t uint32_t unsigned Encoding
unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned Kind
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int Factor
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt Numerator
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Denominator
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Tag
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Name
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt SizeInBits
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt AlignInBits
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Encoding
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Flags
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Kind
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Factor
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Numerator
Public Attributes inherited from llvm::DIBasicType
unsigned Tag
unsigned StringRef Name
unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t Tag
unsigned StringRef uint64_t Name
unsigned StringRef uint64_t FlagZero unsigned Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t NumExtraInhabitants
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags NumExtraInhabitants
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString * Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata * SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t NumExtraInhabitants
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags Flags
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString Metadata uint32_t unsigned uint32_t DIFlags NumExtraInhabitants
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIBasicType
DIBasicType (LLVMContext &C, StorageType Storage, unsigned Tag, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, DIFlags Flags, ArrayRef< Metadata * > Ops)
DIBasicType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, DIFlags Flags, ArrayRef< Metadata * > Ops)
~DIBasicType ()=default
TempDIBasicType cloneImpl () const
Protected Member Functions inherited from llvm::DIType
DIType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags, ArrayRef< Metadata * > Ops)
~DIType ()=default
void init (unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags)
void mutate (unsigned Tag, unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags)
Change fields in place.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~DINode ()=default
template<class Ty>
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
LLVM_ABI MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~MDNode ()=default
LLVM_ABI void * operator new (size_t Size, size_t NumOps, StorageType Storage)
LLVM_ABI void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
LLVM_ABI void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
LLVM_ABI void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
LLVM_ABI void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DIBasicType
static DIBasicType * getImpl (LLVMContext &Context, unsigned Tag, StringRef Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, DIFlags Flags, StorageType Storage, bool ShouldCreate=true)
static DIBasicType * getImpl (LLVMContext &Context, unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, DIFlags Flags, StorageType Storage, bool ShouldCreate=true)
static LLVM_ABI DIBasicType * getImpl (LLVMContext &Context, unsigned Tag, MDString *Name, Metadata *SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, DIFlags Flags, StorageType Storage, bool ShouldCreate=true)
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T, class StoreT>
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T>
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Static Protected Attributes inherited from llvm::DIType
static constexpr unsigned N_OPERANDS = 5
Detailed Description
Fixed-point type.
Definition at line 949 of file DebugInfoMetadata.h.
Member Enumeration Documentation
FixedPointKind
enum llvm::DIFixedPointType::FixedPointKind : unsigned
Enumerator
FixedPointBinary
Scale factor 2^Factor.
FixedPointDecimal
Scale factor 10^Factor.
FixedPointRational
Arbitrary rational scale factor.
LastFixedPointKind
Definition at line 1032 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
bool llvm::DIFixedPointType::classof (const Metadata * MD) inline static
Definition at line 1096 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
DEFINE_MDNODE_GET() [1/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt Denominator llvm::DIFixedPointType::DEFINE_MDNODE_GET (DIFixedPointType , (unsigned Tag, MDString *Name, Metadata *SizeInBits, uint32_t AlignInBits, unsigned Encoding, DIFlags Flags, unsigned Kind, int Factor, APInt Numerator, APInt Denominator) , (Tag, Name, SizeInBits, AlignInBits, Encoding, Flags, Kind, Factor, Numerator, Denominator)) const inline
Definition at line 1060 of file DebugInfoMetadata.h.
References AlignInBits, llvm::DIBasicType::clone(), llvm::DIBasicType::cloneImpl(), DEFINE_MDNODE_GET(), Encoding, Flags, Name, SizeInBits, and Tag.
DEFINE_MDNODE_GET() [2/2]
llvm::DIFixedPointType::DEFINE_MDNODE_GET (DIFixedPointType , (unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, DIFlags Flags, unsigned Kind, int Factor, APInt Numerator, APInt Denominator) , (Tag, Name, SizeInBits, AlignInBits, Encoding, Flags, Kind, Factor, Numerator, Denominator))
References AlignInBits, Encoding, Flags, Name, SizeInBits, and Tag.
Referenced by DEFINE_MDNODE_GET().
fixedPointKindString()
const char * DIFixedPointType::fixedPointKindString (FixedPointKind V) static
Definition at line 941 of file DebugInfoMetadata.cpp.
References FixedPointBinary, FixedPointDecimal, and FixedPointRational.
getDenominator()
const APInt & llvm::DIFixedPointType::getDenominator () const inline
Definition at line 1091 of file DebugInfoMetadata.h.
References assert(), and FixedPointRational.
getDenominatorRaw()
const APInt & llvm::DIFixedPointType::getDenominatorRaw () const inline
Definition at line 1090 of file DebugInfoMetadata.h.
getFactor()
int llvm::DIFixedPointType::getFactor () const inline
Definition at line 1079 of file DebugInfoMetadata.h.
References assert(), FixedPointBinary, and FixedPointDecimal.
getFactorRaw()
int llvm::DIFixedPointType::getFactorRaw () const inline
Definition at line 1078 of file DebugInfoMetadata.h.
getFixedPointKind()
std::optional< DIFixedPointType::FixedPointKind > DIFixedPointType::getFixedPointKind (StringRef Str) static
Definition at line 933 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), FixedPointBinary, FixedPointDecimal, and FixedPointRational.
Referenced by llvm::LLParser::parseMDField().
getKind()
FixedPointKind llvm::DIFixedPointType::getKind () const inline
Definition at line 1076 of file DebugInfoMetadata.h.
getNumerator()
const APInt & llvm::DIFixedPointType::getNumerator () const inline
Definition at line 1085 of file DebugInfoMetadata.h.
References assert(), and FixedPointRational.
getNumeratorRaw()
const APInt & llvm::DIFixedPointType::getNumeratorRaw () const inline
Definition at line 1084 of file DebugInfoMetadata.h.
isBinary()
bool llvm::DIFixedPointType::isBinary () const inline
Definition at line 1070 of file DebugInfoMetadata.h.
References FixedPointBinary.
isDecimal()
bool llvm::DIFixedPointType::isDecimal () const inline
Definition at line 1071 of file DebugInfoMetadata.h.
References FixedPointDecimal.
isRational()
bool llvm::DIFixedPointType::isRational () const inline
Definition at line 1072 of file DebugInfoMetadata.h.
References FixedPointRational.
isSigned()
bool DIFixedPointType::isSigned () const
Definition at line 928 of file DebugInfoMetadata.cpp.
References llvm::DIBasicType::getEncoding().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 950 of file DebugInfoMetadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
MDNode
friend class MDNode friend
Definition at line 951 of file DebugInfoMetadata.h.
References AbstractManglingParser< Derived, Alloc >::Ops, AlignInBits, llvm::CallingConv::C, llvm::DIBasicType::DIBasicType(), Encoding, FixedPointBinary, FixedPointDecimal, Flags, MDNode, llvm::Metadata::Storage, and Tag.
Referenced by MDNode.
Member Data Documentation
AlignInBits [1/2]
unsigned StringRef uint64_t uint32_t llvm::DIFixedPointType::AlignInBits
Definition at line 1055 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), and MDNode.
AlignInBits [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::AlignInBits
Definition at line 1058 of file DebugInfoMetadata.h.
Denominator
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Denominator
Definition at line 1057 of file DebugInfoMetadata.h.
Encoding [1/2]
unsigned StringRef uint64_t uint32_t unsigned llvm::DIFixedPointType::Encoding
Definition at line 1055 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), and MDNode.
Encoding [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Encoding
Definition at line 1058 of file DebugInfoMetadata.h.
Factor [1/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int llvm::DIFixedPointType::Factor
Definition at line 1056 of file DebugInfoMetadata.h.
Factor [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Factor
Definition at line 1059 of file DebugInfoMetadata.h.
Flags [1/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags llvm::DIFixedPointType::Flags
Definition at line 1055 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), and MDNode.
Flags [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Flags
Definition at line 1058 of file DebugInfoMetadata.h.
Kind [1/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned llvm::DIFixedPointType::Kind
Definition at line 1056 of file DebugInfoMetadata.h.
Kind [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Kind
Definition at line 1058 of file DebugInfoMetadata.h.
Name [1/2]
unsigned StringRef llvm::DIFixedPointType::Name
Definition at line 1054 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), and DEFINE_MDNODE_GET().
Name [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Name
Definition at line 1058 of file DebugInfoMetadata.h.
Numerator [1/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt llvm::DIFixedPointType::Numerator
Definition at line 1056 of file DebugInfoMetadata.h.
Numerator [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Numerator
Definition at line 1059 of file DebugInfoMetadata.h.
SizeInBits [1/2]
unsigned StringRef uint64_t llvm::DIFixedPointType::SizeInBits
Definition at line 1054 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), and DEFINE_MDNODE_GET().
SizeInBits [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::SizeInBits
Definition at line 1058 of file DebugInfoMetadata.h.
Tag [1/2]
unsigned llvm::DIFixedPointType::Tag
Definition at line 1054 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), and MDNode.
Tag [2/2]
unsigned StringRef uint64_t uint32_t unsigned DIFlags unsigned int APInt APInt llvm::DIFixedPointType::Tag
Definition at line 1058 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp