LLVM: llvm::SplittingIterator Class Reference
llvm::SplittingIterator Class Reference
A forward iterator over partitions of string over a separator.
#include "llvm/ADT/StringExtras.h"
Public Member Functions
SplittingIterator (StringRef Str, StringRef Separator)
SplittingIterator (StringRef Str, char Separator)
SplittingIterator (const SplittingIterator &R)
SplittingIterator & operator= (const SplittingIterator &R)
bool operator== (const SplittingIterator &R) const
const StringRef & operator* () const
StringRef & operator* ()
SplittingIterator & operator++ ()
Public Member Functions inherited from llvm::iterator_facade_base< SplittingIterator, std::forward_iterator_tag, StringRef >
SplittingIterator operator+ (std::ptrdiff_t n) const
SplittingIterator operator- (std::ptrdiff_t n) const
SplittingIterator & operator++ ()
SplittingIterator & operator-- ()
bool operator!= (const SplittingIterator &RHS) const
bool operator> (const SplittingIterator &RHS) const
bool operator<= (const SplittingIterator &RHS) const
bool operator>= (const SplittingIterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< SplittingIterator, std::forward_iterator_tag, StringRef >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Protected Types inherited from llvm::iterator_facade_base< SplittingIterator, std::forward_iterator_tag, StringRef >
enum
Detailed Description
A forward iterator over partitions of string over a separator.
Definition at line 545 of file StringExtras.h.
Constructor & Destructor Documentation
SplittingIterator() [1/3]
llvm::SplittingIterator::SplittingIterator (StringRef Str, StringRef Separator) inline
Definition at line 554 of file StringExtras.h.
Referenced by operator++(), operator=(), operator==(), and SplittingIterator().
SplittingIterator() [2/3]
llvm::SplittingIterator::SplittingIterator (StringRef Str, char Separator) inline
Definition at line 559 of file StringExtras.h.
SplittingIterator() [3/3]
llvm::SplittingIterator::SplittingIterator (const SplittingIterator & R) inline
Definition at line 565 of file StringExtras.h.
References SplittingIterator().
Member Function Documentation
operator*() [1/2]
StringRef & llvm::SplittingIterator::operator* () inline
Definition at line 592 of file StringExtras.h.
operator*() [2/2]
const StringRef & llvm::SplittingIterator::operator* () const inline
Definition at line 590 of file StringExtras.h.
operator++()
SplittingIterator & llvm::SplittingIterator::operator++ () inline
Definition at line 594 of file StringExtras.h.
References SplittingIterator().
operator=()
SplittingIterator & llvm::SplittingIterator::operator= (const SplittingIterator & R) inline
Definition at line 572 of file StringExtras.h.
References SplittingIterator().
operator==()
bool llvm::SplittingIterator::operator== (const SplittingIterator & R) const inline
Definition at line 585 of file StringExtras.h.
References assert(), and SplittingIterator().
The documentation for this class was generated from the following file:
include/llvm/ADT/StringExtras.h