LLVM: llvm::sandboxir::PHIAddIncoming Class Reference
llvm::sandboxir::PHIAddIncoming Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
PHIAddIncoming (PHINode *PHI)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 170 of file Tracker.h.
Constructor & Destructor Documentation
PHIAddIncoming()
PHIAddIncoming::PHIAddIncoming (PHINode * PHI)
Definition at line 127 of file Tracker.cpp.
Member Function Documentation
accept()
void llvm::sandboxir::PHIAddIncoming::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 177 of file Tracker.h.
dump() [1/2]
void PHIAddIncoming::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 133 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::PHIAddIncoming::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 179 of file Tracker.h.
revert()
void PHIAddIncoming::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 130 of file Tracker.cpp.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp