LLVM: llvm::MCDwarfLineStr Class Reference
llvm::MCDwarfLineStr Class Reference
Manage the .debug_line_str section contents, if we use it.
#include "llvm/MC/MCDwarf.h"
Public Member Functions
LLVM_ABI MCDwarfLineStr (MCContext &Ctx)
Construct an instance that can emit .debug_line_str (for use in a normal v5 line table).
StringSaver & getSaver ()
LLVM_ABI void emitRef (MCStreamer *MCOS, StringRef Path)
Emit a reference to the string.
LLVM_ABI void emitSection (MCStreamer *MCOS)
Emit the .debug_line_str section if appropriate.
LLVM_ABI SmallString< 0 > getFinalizedData ()
Returns finalized section.
LLVM_ABI size_t addString (StringRef Path)
Adds path Path to the line string.
Detailed Description
Manage the .debug_line_str section contents, if we use it.
Definition at line 52 of file MCDwarf.h.
Constructor & Destructor Documentation
MCDwarfLineStr()
MCDwarfLineStr::MCDwarfLineStr (MCContext & Ctx) explicit
Construct an instance that can emit .debug_line_str (for use in a normal v5 line table).
Definition at line 76 of file MCDwarf.cpp.
References assert(), and llvm::MCSection::getBeginSymbol().
Member Function Documentation
addString()
size_t MCDwarfLineStr::addString (StringRef Path)
Adds path Path to the line string.
Returns offset in the .debug_line_str section.
Definition at line 393 of file MCDwarf.cpp.
Referenced by emitRef().
emitRef()
void MCDwarfLineStr::emitRef (MCStreamer * MCOS, StringRef Path)
Emit a reference to the string.
Definition at line 397 of file MCDwarf.cpp.
References addString(), llvm::MCStreamer::emitCOFFSecRel32(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfFormat(), llvm::dwarf::getDwarfOffsetByteSize(), makeStartPlusIntExpr(), and llvm::Offset.
emitSection()
void MCDwarfLineStr::emitSection (MCStreamer * MCOS)
Emit the .debug_line_str section if appropriate.
Definition at line 375 of file MCDwarf.cpp.
References llvm::Data, llvm::MCStreamer::emitBinaryData(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfLineStrSection(), getFinalizedData(), llvm::MCContext::getObjectFileInfo(), and llvm::MCStreamer::switchSection().
getFinalizedData()
SmallString< 0 > MCDwarfLineStr::getFinalizedData ()
Returns finalized section.
Definition at line 383 of file MCDwarf.cpp.
References llvm::Data.
Referenced by emitSection().
getSaver()
StringSaver & llvm::MCDwarfLineStr::getSaver () inline
Definition at line 64 of file MCDwarf.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp