LLVM: llvm::SampleProfileLoaderPass Class Reference
llvm::SampleProfileLoaderPass Class Reference
The sample profiler data loader pass.
#include "llvm/Transforms/IPO/SampleProfile.h"
Public Member Functions
LLVM_ABI SampleProfileLoaderPass (std::string File="", std::string RemappingFile="", ThinOrFullLTOPhase LTOPhase=ThinOrFullLTOPhase::None, IntrusiveRefCntPtr< vfs::FileSystem > FS=nullptr, bool DisableSampleProfileInlining=false, bool UseFlattenedProfile=false)
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< SampleProfileLoaderPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SampleProfileLoaderPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The sample profiler data loader pass.
Definition at line 40 of file SampleProfile.h.
Constructor & Destructor Documentation
SampleProfileLoaderPass()
SampleProfileLoaderPass::SampleProfileLoaderPass (std::string File = "", std::string RemappingFile = "", ThinOrFullLTOPhase LTOPhase = ThinOrFullLTOPhase::None, IntrusiveRefCntPtr< vfs::FileSystem > FS = nullptr, bool DisableSampleProfileInlining = false, bool UseFlattenedProfile = false)
Definition at line 2328 of file SampleProfile.cpp.
References llvm::move().
Member Function Documentation
run()
PreservedAnalyses SampleProfileLoaderPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 2337 of file SampleProfile.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::vfs::getRealFileSystem(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::none(), SampleProfileFile, and SampleProfileRemappingFile.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleProfile.h
lib/Transforms/IPO/SampleProfile.cpp