LLVM: llvm::SampleContextTracker Class Reference
llvm::SampleContextTracker Class Reference
#include "llvm/Transforms/IPO/SampleContextTracker.h"
Classes
class Iterator
Public Types
using ContextSamplesTy = std::vector<FunctionSamples *>
Public Member Functions
SampleContextTracker ()=default
LLVM_ABI SampleContextTracker (SampleProfileMap &Profiles, const DenseMap< uint64_t, StringRef > *GUIDToFuncNameMap)
LLVM_ABI void populateFuncToCtxtMap ()
LLVM_ABI FunctionSamples * getCalleeContextSamplesFor (const CallBase &Inst, StringRef CalleeName)
LLVM_ABI std::vector< const FunctionSamples * > getIndirectCalleeContextSamplesFor (const DILocation *DIL)
LLVM_ABI FunctionSamples * getContextSamplesFor (const DILocation *DIL)
LLVM_ABI FunctionSamples * getContextSamplesFor (const SampleContext &Context)
LLVM_ABI ContextSamplesTy & getAllContextSamplesFor (const Function &Func)
LLVM_ABI ContextSamplesTy & getAllContextSamplesFor (StringRef Name)
LLVM_ABI ContextTrieNode * getOrCreateContextPath (const SampleContext &Context, bool AllowCreate)
LLVM_ABI FunctionSamples * getBaseSamplesFor (const Function &Func, bool MergeContext=true)
LLVM_ABI FunctionSamples * getBaseSamplesFor (FunctionId Name, bool MergeContext=true)
LLVM_ABI ContextTrieNode * getContextFor (const SampleContext &Context)
LLVM_ABI StringRef getFuncNameFor (ContextTrieNode *Node) const
LLVM_ABI void markContextSamplesInlined (const FunctionSamples *InlinedSamples)
LLVM_ABI ContextTrieNode & getRootContext ()
LLVM_ABI void promoteMergeContextSamplesTree (const Instruction &Inst, FunctionId CalleeName)
LLVM_ABI void createContextLessProfileMap (SampleProfileMap &ContextLessProfiles)
ContextTrieNode * getContextNodeForProfile (const FunctionSamples *FSamples) const
HashKeyMap< std::unordered_map, FunctionId, ContextSamplesTy > & getFuncToCtxtProfiles ()
Iterator begin ()
Iterator end ()
std::string getContextString (const FunctionSamples &FSamples) const
std::string getContextString (ContextTrieNode *Node) const
LLVM_ABI void dump ()
Detailed Description
Definition at line 92 of file SampleContextTracker.h.
Member Typedef Documentation
ContextSamplesTy
using llvm::SampleContextTracker::ContextSamplesTy = std::vector<FunctionSamples *>
Definition at line 94 of file SampleContextTracker.h.
Constructor & Destructor Documentation
SampleContextTracker() [1/2]
llvm::SampleContextTracker::SampleContextTracker () default
References LLVM_ABI.
SampleContextTracker() [2/2]
llvm::SampleContextTracker::SampleContextTracker (SampleProfileMap & Profiles, const DenseMap< uint64_t, StringRef > * GUIDToFuncNameMap)
Definition at line 198 of file SampleContextTracker.cpp.
References assert(), llvm::dbgs(), llvm::ContextTrieNode::getFunctionSamples(), getOrCreateContextPath(), LLVM_DEBUG, populateFuncToCtxtMap(), and llvm::ContextTrieNode::setFunctionSamples().
Member Function Documentation
begin()
Iterator llvm::SampleContextTracker::begin () inline
Definition at line 185 of file SampleContextTracker.h.
createContextLessProfileMap()
void llvm::SampleContextTracker::createContextLessProfileMap (SampleProfileMap & ContextLessProfiles)
Definition at line 622 of file SampleContextTracker.cpp.
References llvm::sampleprof::SampleProfileMap::create(), and llvm::sampleprof::FunctionSamples::merge().
dump()
void llvm::SampleContextTracker::dump ()
Definition at line 451 of file SampleContextTracker.cpp.
end()
Iterator llvm::SampleContextTracker::end () inline
Definition at line 186 of file SampleContextTracker.h.
getAllContextSamplesFor() [1/2]
SampleContextTracker::ContextSamplesTy & llvm::SampleContextTracker::getAllContextSamplesFor (const Function & Func)
Definition at line 304 of file SampleContextTracker.cpp.
References llvm::sampleprof::FunctionSamples::getCanonicalFnName(), and llvm::sampleprof::getRepInFormat().
getAllContextSamplesFor() [2/2]
SampleContextTracker::ContextSamplesTy & llvm::SampleContextTracker::getAllContextSamplesFor (StringRef Name)
Definition at line 310 of file SampleContextTracker.cpp.
References llvm::sampleprof::getRepInFormat().
getBaseSamplesFor() [1/2]
FunctionSamples * llvm::SampleContextTracker::getBaseSamplesFor (const Function & Func, bool MergeContext = true)
Definition at line 314 of file SampleContextTracker.cpp.
References getBaseSamplesFor(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), and llvm::sampleprof::getRepInFormat().
Referenced by getBaseSamplesFor().
getBaseSamplesFor() [2/2]
FunctionSamples * llvm::SampleContextTracker::getBaseSamplesFor (FunctionId Name, bool MergeContext = true)
Definition at line 320 of file SampleContextTracker.cpp.
References assert(), llvm::dbgs(), getContextNodeForProfile(), llvm::sampleprof::InlinedContext, LLVM_DEBUG, llvm::sampleprof::MergedContext, and promoteMergeContextSamplesTree().
getCalleeContextSamplesFor()
FunctionSamples * llvm::SampleContextTracker::getCalleeContextSamplesFor (const CallBase & Inst, StringRef CalleeName)
Definition at line 227 of file SampleContextTracker.cpp.
References llvm::dbgs(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), getContextString(), llvm::Instruction::getDebugLoc(), llvm::ContextTrieNode::getFunctionSamples(), llvm::sampleprof::getRepInFormat(), and LLVM_DEBUG.
getContextFor()
ContextTrieNode * llvm::SampleContextTracker::getContextFor (const SampleContext & Context)
Definition at line 461 of file SampleContextTracker.cpp.
References getOrCreateContextPath().
Referenced by getContextSamplesFor(), getContextSamplesFor(), getIndirectCalleeContextSamplesFor(), and promoteMergeContextSamplesTree().
getContextNodeForProfile()
ContextTrieNode * llvm::SampleContextTracker::getContextNodeForProfile (const FunctionSamples * FSamples) const inline
Definition at line 143 of file SampleContextTracker.h.
References I.
Referenced by getBaseSamplesFor(), and getContextString().
getContextSamplesFor() [1/2]
FunctionSamples * llvm::SampleContextTracker::getContextSamplesFor (const DILocation * DIL)
Definition at line 274 of file SampleContextTracker.cpp.
References assert(), llvm::sampleprof::FunctionSamples::getContext(), getContextFor(), llvm::ContextTrieNode::getFunctionSamples(), llvm::ContextTrieNode::getParentContext(), llvm::sampleprof::InlinedContext, and llvm::sampleprof::SampleContext::setState().
getContextSamplesFor() [2/2]
FunctionSamples * llvm::SampleContextTracker::getContextSamplesFor (const SampleContext & Context)
Definition at line 295 of file SampleContextTracker.cpp.
References getContextFor().
getContextString() [1/2]
std::string llvm::SampleContextTracker::getContextString (const FunctionSamples & FSamples) const
Definition at line 426 of file SampleContextTracker.cpp.
References getContextNodeForProfile(), and getContextString().
Referenced by getCalleeContextSamplesFor(), getContextString(), and markContextSamplesInlined().
getContextString() [2/2]
std::string llvm::SampleContextTracker::getContextString (ContextTrieNode * Node) const
Definition at line 431 of file SampleContextTracker.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ContextTrieNode::getCallSiteLoc(), and llvm::sampleprof::SampleContext::getContextString().
getFuncNameFor()
StringRef llvm::SampleContextTracker::getFuncNameFor (ContextTrieNode * Node) const
Definition at line 453 of file SampleContextTracker.cpp.
References assert(), and llvm::sampleprof::FunctionSamples::UseMD5.
getFuncToCtxtProfiles()
HashKeyMap< std::unordered_map, FunctionId, ContextSamplesTy > & llvm::SampleContextTracker::getFuncToCtxtProfiles () inline
Definition at line 150 of file SampleContextTracker.h.
getIndirectCalleeContextSamplesFor()
std::vector< const FunctionSamples * > llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor (const DILocation * DIL)
Definition at line 254 of file SampleContextTracker.cpp.
References llvm::ContextTrieNode::getAllChildContext(), llvm::sampleprof::FunctionSamples::getCallSiteIdentifier(), llvm::ContextTrieNode::getCallSiteLoc(), getContextFor(), and llvm::ContextTrieNode::getFunctionSamples().
getOrCreateContextPath()
ContextTrieNode * llvm::SampleContextTracker::getOrCreateContextPath (const SampleContext & Context, bool AllowCreate)
Definition at line 519 of file SampleContextTracker.cpp.
References assert(), llvm::ContextTrieNode::getChildContext(), and llvm::ContextTrieNode::getOrCreateChildContext().
Referenced by getContextFor(), and SampleContextTracker().
getRootContext()
ContextTrieNode & llvm::SampleContextTracker::getRootContext ()
Definition at line 367 of file SampleContextTracker.cpp.
Referenced by llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph().
markContextSamplesInlined()
void llvm::SampleContextTracker::markContextSamplesInlined (const FunctionSamples * InlinedSamples)
Definition at line 359 of file SampleContextTracker.cpp.
References assert(), llvm::dbgs(), llvm::sampleprof::FunctionSamples::getContext(), getContextString(), llvm::sampleprof::InlinedContext, LLVM_DEBUG, and llvm::sampleprof::SampleContext::setState().
populateFuncToCtxtMap()
void llvm::SampleContextTracker::populateFuncToCtxtMap ()
Definition at line 215 of file SampleContextTracker.cpp.
References llvm::sampleprof::FunctionSamples::getContext(), llvm::sampleprof::RawContext, and llvm::sampleprof::SampleContext::setState().
Referenced by SampleContextTracker().
promoteMergeContextSamplesTree()
void llvm::SampleContextTracker::promoteMergeContextSamplesTree (const Instruction & Inst, FunctionId CalleeName)
Definition at line 369 of file SampleContextTracker.cpp.
References llvm::dbgs(), llvm::sampleprof::FunctionId::empty(), llvm::ContextTrieNode::getAllChildContext(), llvm::sampleprof::FunctionSamples::getCallSiteIdentifier(), llvm::ContextTrieNode::getCallSiteLoc(), llvm::ContextTrieNode::getChildContext(), llvm::sampleprof::FunctionSamples::getContext(), getContextFor(), llvm::Instruction::getDebugLoc(), llvm::ContextTrieNode::getFunctionSamples(), llvm::sampleprof::SampleContext::hasState(), llvm::sampleprof::InlinedContext, LLVM_DEBUG, and promoteMergeContextSamplesTree().
Referenced by getBaseSamplesFor(), and promoteMergeContextSamplesTree().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleContextTracker.h
lib/Transforms/IPO/SampleContextTracker.cpp