LLVM: llvm::sandboxir::RegionPass Class Reference
llvm::sandboxir::RegionPass Class Reference abstract
A pass that runs on a sandbox::Region.
#include "llvm/SandboxIR/Pass.h"
Public Member Functions
RegionPass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual bool runOnRegion (Region &R, const Analyses &A)=0
\Returns true if it modifies R.
Public Member Functions inherited from llvm::sandboxir::Pass
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()
StringRef getName () const
\Returns the name of the pass.
virtual void print (raw_ostream &OS) const
virtual LLVM_DUMP_METHOD void dump () const
virtual void printPipeline (raw_ostream &OS) const
Similar to print() but adds a newline. Used for testing.
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::Pass
const std::string Name
The pass name.
Detailed Description
A pass that runs on a sandbox::Region.
Definition at line 84 of file Pass.h.
Constructor & Destructor Documentation
RegionPass()
llvm::sandboxir::RegionPass::RegionPass (StringRef Name) inline
Name can't contain any spaces or start with '-'.
Definition at line 87 of file Pass.h.
References llvm::sandboxir::Pass::Name, and llvm::sandboxir::Pass::Pass().
Referenced by llvm::sandboxir::BottomUpVec::BottomUpVec(), llvm::sandboxir::NullPass::NullPass(), llvm::sandboxir::PackReuse::PackReuse(), llvm::sandboxir::PrintInstructionCount::PrintInstructionCount(), llvm::sandboxir::PrintRegion::PrintRegion(), llvm::sandboxir::TransactionAcceptOrRevert::TransactionAcceptOrRevert(), llvm::sandboxir::TransactionAlwaysAccept::TransactionAlwaysAccept(), llvm::sandboxir::TransactionAlwaysRevert::TransactionAlwaysRevert(), and llvm::sandboxir::TransactionSave::TransactionSave().
Member Function Documentation
runOnRegion()
virtual bool llvm::sandboxir::RegionPass::runOnRegion (Region & R, const Analyses & A) pure virtual
\Returns true if it modifies R.
Implemented in llvm::sandboxir::BottomUpVec, llvm::sandboxir::NullPass, llvm::sandboxir::PackReuse, llvm::sandboxir::PrintInstructionCount, llvm::sandboxir::PrintRegion, llvm::sandboxir::RegionPassManager, llvm::sandboxir::TransactionAcceptOrRevert, llvm::sandboxir::TransactionAlwaysAccept, llvm::sandboxir::TransactionAlwaysRevert, and llvm::sandboxir::TransactionSave.
References A().
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Pass.h