LLVM: llvm::RISCVConstantPoolValue Class Reference
llvm::RISCVConstantPoolValue Class Reference
A RISCV-specific constant pool value.
#include "Target/RISCV/RISCVConstantPoolValue.h"
Public Member Functions
~RISCVConstantPoolValue ()=default
bool isGlobalValue () const
bool isExtSymbol () const
const GlobalValue * getGlobalValue () const
StringRef getSymbol () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const RISCVConstantPoolValue *A) const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static RISCVConstantPoolValue * Create (const GlobalValue *GV)
static RISCVConstantPoolValue * Create (LLVMContext &C, StringRef S)
Detailed Description
A RISCV-specific constant pool value.
Definition at line 28 of file RISCVConstantPoolValue.h.
Constructor & Destructor Documentation
~RISCVConstantPoolValue()
llvm::RISCVConstantPoolValue::~RISCVConstantPoolValue () default
References llvm::CallingConv::C.
Member Function Documentation
addSelectionDAGCSEId()
void RISCVConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 54 of file RISCVConstantPoolValue.cpp.
References assert(), isExtSymbol(), and isGlobalValue().
Create() [1/2]
RISCVConstantPoolValue * RISCVConstantPoolValue::Create (const GlobalValue * GV) static
Definition at line 29 of file RISCVConstantPoolValue.cpp.
Referenced by getLargeExternalSymbol(), and getLargeGlobalAddress().
Create() [2/2]
RISCVConstantPoolValue * RISCVConstantPoolValue::Create (LLVMContext & C, StringRef S) static
Definition at line 33 of file RISCVConstantPoolValue.cpp.
References llvm::CallingConv::C.
equals()
bool RISCVConstantPoolValue::equals (const RISCVConstantPoolValue * A) const
Definition at line 72 of file RISCVConstantPoolValue.cpp.
References A(), isExtSymbol(), and isGlobalValue().
Referenced by getExistingMachineCPValue().
getExistingMachineCPValue()
int RISCVConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 38 of file RISCVConstantPoolValue.cpp.
References equals(), and llvm::getAlign().
getGlobalValue()
const GlobalValue * llvm::RISCVConstantPoolValue::getGlobalValue () const inline
Definition at line 48 of file RISCVConstantPoolValue.h.
getSymbol()
StringRef llvm::RISCVConstantPoolValue::getSymbol () const inline
Definition at line 49 of file RISCVConstantPoolValue.h.
isExtSymbol()
bool llvm::RISCVConstantPoolValue::isExtSymbol () const inline
Definition at line 46 of file RISCVConstantPoolValue.h.
Referenced by addSelectionDAGCSEId(), equals(), and print().
isGlobalValue()
bool llvm::RISCVConstantPoolValue::isGlobalValue () const inline
Definition at line 45 of file RISCVConstantPoolValue.h.
Referenced by addSelectionDAGCSEId(), equals(), and print().
print()
void RISCVConstantPoolValue::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 63 of file RISCVConstantPoolValue.cpp.
References assert(), isExtSymbol(), and isGlobalValue().
The documentation for this class was generated from the following files:
lib/Target/RISCV/RISCVConstantPoolValue.h
lib/Target/RISCV/RISCVConstantPoolValue.cpp