LLVM: llvm::TargetLibraryInfo Class Reference
llvm::TargetLibraryInfo Class Reference
Provides information about what library functions are available for the current target.
#include "llvm/Analysis/TargetLibraryInfo.h"
Public Member Functions
TargetLibraryInfo ()=delete
TargetLibraryInfo (const TargetLibraryInfoImpl &Impl, std::optional< const Function * > F=std::nullopt)
TargetLibraryInfo (const TargetLibraryInfo &TLI)=default
TargetLibraryInfo (TargetLibraryInfo &&TLI)=default
TargetLibraryInfo & operator= (const TargetLibraryInfo &TLI)=default
TargetLibraryInfo & operator= (TargetLibraryInfo &&TLI)=default
bool areInlineCompatible (const TargetLibraryInfo &CalleeTLI, bool AllowCallerSuperset) const
Determine whether a callee with the given TLI can be inlined into caller with this TLI, based on 'nobuiltin' attributes.
bool isValidProtoForLibFunc (const FunctionType &FTy, LibFunc F, const Module &M) const
Return true if the function type FTy is valid for the library function F, regardless of whether the function is available.
bool getLibFunc (StringRef funcName, LibFunc &F) const
Searches for a particular function name.
bool getLibFunc (const Function &FDecl, LibFunc &F) const
bool getLibFunc (const CallBase &CB, LibFunc &F) const
If a callbase does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
bool getLibFunc (unsigned int Opcode, Type *Ty, LibFunc &F) const
Searches for a function name using an Instruction Opcode.
void disableAllFunctions () LLVM_ATTRIBUTE_UNUSED
Disables all builtins.
void setUnavailable (LibFunc F) LLVM_ATTRIBUTE_UNUSED
Forces a function to be marked as unavailable.
TargetLibraryInfoImpl::AvailabilityState getState (LibFunc F) const
bool has (LibFunc F) const
Tests whether a library function is available.
bool isFunctionVectorizable (StringRef F, const ElementCount &VF) const
bool isFunctionVectorizable (StringRef F) const
StringRef getVectorizedFunction (StringRef F, const ElementCount &VF, bool Masked=false) const
const VecDesc * getVectorMappingInfo (StringRef F, const ElementCount &VF, bool Masked) const
bool hasOptimizedCodeGen (LibFunc F) const
Tests if the function is both available and a candidate for optimized code generation.
StringRef getName (LibFunc F) const
Attribute::AttrKind getExtAttrForI32Param (bool Signed=true) const
Attribute::AttrKind getExtAttrForI32Return (bool Signed=true) const
AttributeList getAttrList (LLVMContext *C, ArrayRef< unsigned > ArgNos, bool Signed, bool Ret=false, AttributeList AL=AttributeList()) const
unsigned getWCharSize (const Module &M) const
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
unsigned getSizeTSize (const Module &M) const
Returns the size of the size_t type in bits.
IntegerType * getSizeTType (const Module &M) const
Returns an IntegerType corresponding to size_t.
ConstantInt * getAsSizeT (uint64_t V, const Module &M) const
Returns a constant materialized as a size_t type.
unsigned getIntSize () const
Get size of a C-level int or unsigned int, in bits.
bool invalidate (Module &, const PreservedAnalyses &, ModuleAnalysisManager::Invalidator &)
Handle invalidation from the pass manager.
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
void getWidestVF (StringRef ScalarF, ElementCount &FixedVF, ElementCount &ScalableVF) const
Returns the largest vectorization factor used in the list of vector functions.
bool isKnownVectorFunctionInLibrary (StringRef F) const
Check if the function "F" is listed in a library known to LLVM.
Static Public Member Functions
static void initExtensionsForTriple (bool &ShouldExtI32Param, bool &ShouldExtI32Return, bool &ShouldSignExtI32Param, bool &ShouldSignExtI32Return, const Triple &T)
static Attribute::AttrKind getExtAttrForI32Param (const Triple &T, bool Signed=true)
static Attribute::AttrKind getExtAttrForI32Return (const Triple &T, bool Signed=true)
Friends
class TargetLibraryAnalysis
class TargetLibraryInfoWrapperPass
Detailed Description
Provides information about what library functions are available for the current target.
This both allows optimizations to handle them specially and frontends to disable such optimizations through -fno-builtin etc.
Definition at line 285 of file TargetLibraryInfo.h.
Constructor & Destructor Documentation
TargetLibraryInfo() [1/4]
llvm::TargetLibraryInfo::TargetLibraryInfo () delete
Referenced by areInlineCompatible(), operator=(), operator=(), TargetLibraryInfo(), and TargetLibraryInfo().
TargetLibraryInfo() [2/4]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfoImpl & Impl, std::optional< const Function * > F = std::nullopt) inline explicit
Definition at line 299 of file TargetLibraryInfo.h.
References disableAllFunctions(), F, getLibFunc(), and setUnavailable().
TargetLibraryInfo() [3/4]
llvm::TargetLibraryInfo::TargetLibraryInfo (const TargetLibraryInfo & TLI) default
References TargetLibraryInfo().
TargetLibraryInfo() [4/4]
llvm::TargetLibraryInfo::TargetLibraryInfo (TargetLibraryInfo && TLI) default
References TargetLibraryInfo().
Member Function Documentation
areInlineCompatible()
bool llvm::TargetLibraryInfo::areInlineCompatible (const TargetLibraryInfo & CalleeTLI, bool AllowCallerSuperset) const inline
Determine whether a callee with the given TLI can be inlined into caller with this TLI, based on 'nobuiltin' attributes.
When requested, allow inlining into a caller with a superset of the callee's nobuiltin attributes, which is conservatively correct.
Definition at line 332 of file TargetLibraryInfo.h.
References TargetLibraryInfo().
disableAllFunctions()
void llvm::TargetLibraryInfo::disableAllFunctions () inline
Disables all builtins.
This can be used for options like -fno-builtin.
Definition at line 376 of file TargetLibraryInfo.h.
References LLVM_ATTRIBUTE_UNUSED.
Referenced by TargetLibraryInfo().
getAsSizeT()
ConstantInt * llvm::TargetLibraryInfo::getAsSizeT (uint64_t V, const Module & M) const inline
Returns a constant materialized as a size_t type.
Definition at line 583 of file TargetLibraryInfo.h.
References getSizeTType().
getAttrList()
AttributeList llvm::TargetLibraryInfo::getAttrList (LLVMContext * C, ArrayRef< unsigned > ArgNos, bool Signed, bool Ret = false, AttributeList AL = AttributeList()) const inline
Definition at line 557 of file TargetLibraryInfo.h.
References llvm::CallingConv::C, and Signed.
getExtAttrForI32Param() [1/2]
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Param (bool Signed = true) const inline
Definition at line 519 of file TargetLibraryInfo.h.
References Signed.
getExtAttrForI32Param() [2/2]
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Param (const Triple & T, bool Signed = true) inline static
Definition at line 509 of file TargetLibraryInfo.h.
References initExtensionsForTriple(), Signed, and T.
getExtAttrForI32Return() [1/2]
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Return (bool Signed = true) const inline
Definition at line 549 of file TargetLibraryInfo.h.
References Signed.
getExtAttrForI32Return() [2/2]
Attribute::AttrKind llvm::TargetLibraryInfo::getExtAttrForI32Return (const Triple & T, bool Signed = true) inline static
Definition at line 539 of file TargetLibraryInfo.h.
References initExtensionsForTriple(), Signed, and T.
getIntSize()
unsigned llvm::TargetLibraryInfo::getIntSize () const inline
Get size of a C-level int or unsigned int, in bits.
Definition at line 588 of file TargetLibraryInfo.h.
Referenced by getIntTy().
getLibFunc() [1/4]
bool llvm::TargetLibraryInfo::getLibFunc (const CallBase & CB, LibFunc & F) const inline
If a callbase does not have the 'nobuiltin' attribute, return if the called function is a known library function and set F to that function.
Definition at line 362 of file TargetLibraryInfo.h.
References F, llvm::CallBase::getCalledFunction(), getLibFunc(), and llvm::CallBase::isNoBuiltin().
getLibFunc() [2/4]
bool llvm::TargetLibraryInfo::getLibFunc (const Function & FDecl, LibFunc & F) const inline
Definition at line 356 of file TargetLibraryInfo.h.
References F.
getLibFunc() [3/4]
bool llvm::TargetLibraryInfo::getLibFunc (StringRef funcName, LibFunc & F) const inline
Searches for a particular function name.
If it is one of the known library functions, return true and set F to the corresponding value.
Definition at line 352 of file TargetLibraryInfo.h.
References F.
Referenced by llvm::callsGCLeafFunction(), llvm::ConstantFoldCall(), llvm::emitBinaryFloatFnCall(), llvm::emitUnaryFloatFnCall(), foldLibCalls(), getAllocationDataForFunction(), llvm::getAllocationFamily(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::MemoryLocation::getForArgument(), llvm::getFreedOperand(), llvm::getIntrinsicForCallSite(), getIntrinsicFromLibfunc(), getLibFunc(), llvm::inferNonMandatoryLibFuncAttrs(), insertSinCosCall(), isAllocationWithHotColdVariant(), isAllocSiteRemovable(), isIntrinsicOrLFToBeTailCalled(), isKnownLibFunction(), isKnownLibFunction(), llvm::isLibFuncEmittable(), llvm::isMathLibCallNoop(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), optimizeCall(), runPartiallyInlineLibCalls(), shouldCheckArgs(), and TargetLibraryInfo().
getLibFunc() [4/4]
bool llvm::TargetLibraryInfo::getLibFunc (unsigned int Opcode, Type * Ty, LibFunc & F) const inline
Searches for a function name using an Instruction Opcode.
Currently, only the frem instruction is supported.
Definition at line 369 of file TargetLibraryInfo.h.
References F.
getName()
StringRef llvm::TargetLibraryInfo::getName (LibFunc F) const inline
Definition at line 457 of file TargetLibraryInfo.h.
References assert(), F, and getState().
Referenced by llvm::emitCalloc(), llvm::emitFPutC(), llvm::emitFPutS(), llvm::emitFWrite(), llvm::emitHotColdNew(), llvm::emitHotColdNewAligned(), llvm::emitHotColdNewAlignedNoThrow(), llvm::emitHotColdNewNoThrow(), llvm::emitHotColdSizeReturningNew(), llvm::emitHotColdSizeReturningNewAligned(), emitLibCall(), llvm::emitMalloc(), llvm::emitPutChar(), llvm::emitPutS(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::getFloatFn(), getIntrinsicFromLibfunc(), llvm::getOrInsertLibFunc(), and llvm::isLibFuncEmittable().
getSizeTSize()
unsigned llvm::TargetLibraryInfo::getSizeTSize (const Module & M) const inline
Returns the size of the size_t type in bits.
Definition at line 575 of file TargetLibraryInfo.h.
Referenced by getSizeTTy(), and getSizeTType().
getSizeTType()
IntegerType * llvm::TargetLibraryInfo::getSizeTType (const Module & M) const inline
Returns an IntegerType corresponding to size_t.
Definition at line 578 of file TargetLibraryInfo.h.
References llvm::IntegerType::get(), and getSizeTSize().
Referenced by getAsSizeT().
getState()
TargetLibraryInfoImpl::AvailabilityState llvm::TargetLibraryInfo::getState (LibFunc F) const inline
Definition at line 386 of file TargetLibraryInfo.h.
References assert(), and F.
Referenced by getName(), has(), and hasOptimizedCodeGen().
getVectorizedFunction()
StringRef llvm::TargetLibraryInfo::getVectorizedFunction (StringRef F, const ElementCount & VF, bool Masked = false) const inline
Definition at line 403 of file TargetLibraryInfo.h.
References F, and llvm::Masked.
getVectorMappingInfo()
const VecDesc * llvm::TargetLibraryInfo::getVectorMappingInfo (StringRef F, const ElementCount & VF, bool Masked) const inline
Definition at line 407 of file TargetLibraryInfo.h.
References F, and llvm::Masked.
Referenced by addMappingsFromTLI(), and replaceWithCallToVeclib().
getWCharSize()
unsigned llvm::TargetLibraryInfo::getWCharSize (const Module & M) const inline
Returns the size of the wchar_t type in bytes or 0 if the size is unknown.
This queries the 'wchar_size' metadata.
Definition at line 570 of file TargetLibraryInfo.h.
getWidestVF()
void llvm::TargetLibraryInfo::getWidestVF (StringRef ScalarF, ElementCount & FixedVF, ElementCount & ScalableVF) const inline
Returns the largest vectorization factor used in the list of vector functions.
Definition at line 606 of file TargetLibraryInfo.h.
Referenced by addMappingsFromTLI(), and llvm::isTLIScalarize().
has()
bool llvm::TargetLibraryInfo::has (LibFunc F) const inline
Tests whether a library function is available.
Definition at line 394 of file TargetLibraryInfo.h.
References F, and getState().
Referenced by llvm::callsGCLeafFunction(), getAllocationDataForFunction(), llvm::getAllocationFamily(), llvm::MemoryLocation::getForArgument(), llvm::getFreedOperand(), llvm::getOrInsertLibFunc(), llvm::inferNonMandatoryLibFuncAttrs(), isAllocSiteRemovable(), llvm::isLibFuncEmittable(), and runPartiallyInlineLibCalls().
hasOptimizedCodeGen()
bool llvm::TargetLibraryInfo::hasOptimizedCodeGen (LibFunc F) const inline
Tests if the function is both available and a candidate for optimized code generation.
Definition at line 414 of file TargetLibraryInfo.h.
References F, and getState().
Referenced by llvm::maybeMarkSanitizerLibraryCallNoBuiltin().
initExtensionsForTriple()
void llvm::TargetLibraryInfo::initExtensionsForTriple (bool & ShouldExtI32Param, bool & ShouldExtI32Return, bool & ShouldSignExtI32Param, bool & ShouldSignExtI32Return, const Triple & T) inline static
Definition at line 467 of file TargetLibraryInfo.h.
References llvm::Triple::sparcv9, llvm::Triple::systemz, and T.
Referenced by getExtAttrForI32Param(), getExtAttrForI32Return(), and initializeBase().
invalidate() [1/2]
bool llvm::TargetLibraryInfo::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Definition at line 600 of file TargetLibraryInfo.h.
invalidate() [2/2]
bool llvm::TargetLibraryInfo::invalidate (Module & , const PreservedAnalyses & , ModuleAnalysisManager::Invalidator &) inline
Handle invalidation from the pass manager.
If we try to invalidate this info, just return false. It cannot become invalid even if the module or function changes.
Definition at line 596 of file TargetLibraryInfo.h.
isFunctionVectorizable() [1/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F) const inline
Definition at line 400 of file TargetLibraryInfo.h.
References F.
isFunctionVectorizable() [2/2]
bool llvm::TargetLibraryInfo::isFunctionVectorizable (StringRef F, const ElementCount & VF) const inline
Definition at line 397 of file TargetLibraryInfo.h.
References F.
Referenced by addMappingsFromTLI(), llvm::TargetTransformInfo::getArithmeticInstrCost(), isKnownVectorFunctionInLibrary(), and llvm::isTLIScalarize().
isKnownVectorFunctionInLibrary()
bool llvm::TargetLibraryInfo::isKnownVectorFunctionInLibrary (StringRef F) const inline
Check if the function "F" is listed in a library known to LLVM.
Definition at line 612 of file TargetLibraryInfo.h.
References F, and isFunctionVectorizable().
Referenced by isKnownLibFunction(), and isKnownLibFunction().
isValidProtoForLibFunc()
bool llvm::TargetLibraryInfo::isValidProtoForLibFunc (const FunctionType & FTy, LibFunc F, const Module & M) const inline
Return true if the function type FTy is valid for the library function F, regardless of whether the function is available.
Definition at line 343 of file TargetLibraryInfo.h.
References F.
Referenced by llvm::isLibFuncEmittable().
operator=() [1/2]
TargetLibraryInfo & llvm::TargetLibraryInfo::operator= (const TargetLibraryInfo & TLI) default
References TargetLibraryInfo().
operator=() [2/2]
TargetLibraryInfo & llvm::TargetLibraryInfo::operator= (TargetLibraryInfo && TLI) default
References TargetLibraryInfo().
setUnavailable()
void llvm::TargetLibraryInfo::setUnavailable (LibFunc F) inline
Forces a function to be marked as unavailable.
Definition at line 381 of file TargetLibraryInfo.h.
References assert(), F, and LLVM_ATTRIBUTE_UNUSED.
Referenced by TargetLibraryInfo().
Friends And Related Symbol Documentation
TargetLibraryAnalysis
friend class TargetLibraryAnalysis friend
Definition at line 286 of file TargetLibraryInfo.h.
References TargetLibraryAnalysis.
Referenced by TargetLibraryAnalysis.
TargetLibraryInfoWrapperPass
friend class TargetLibraryInfoWrapperPass friend
Definition at line 287 of file TargetLibraryInfo.h.
References TargetLibraryInfoWrapperPass.
Referenced by TargetLibraryInfoWrapperPass.
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetLibraryInfo.h