LLVM: llvm::pdb::GSIHashIterator Class Reference
llvm::pdb::GSIHashIterator Class Reference
Iterator over hash records producing symbol record offsets.
#include "llvm/DebugInfo/PDB/Native/GlobalsStream.h"
Public Member Functions
template<typename T>
GSIHashIterator (T &&v)
uint32_t operator* () const
Public Member Functions inherited from llvm::iterator_adaptor_base< GSIHashIterator, FixedStreamArrayIterator< PSHashRecord >, std::random_access_iterator_tag, const uint32_t >
GSIHashIterator & operator+= (difference_type n)
GSIHashIterator & operator-= (difference_type n)
difference_type operator- (const GSIHashIterator &RHS) const
GSIHashIterator & operator++ ()
GSIHashIterator & operator-- ()
std::conditional_t< std::is_same< const uint32_t, typename std::iterator_traits< FixedStreamArrayIterator< PSHashRecord > >::value_type >::value, typename std::iterator_traits< FixedStreamArrayIterator< PSHashRecord > >::reference, const uint32_t & > operator* () const
Additional Inherited Members
Public Types inherited from llvm::iterator_adaptor_base< GSIHashIterator, FixedStreamArrayIterator< PSHashRecord >, std::random_access_iterator_tag, const uint32_t >
using difference_type
Protected Member Functions inherited from llvm::iterator_adaptor_base< GSIHashIterator, FixedStreamArrayIterator< PSHashRecord >, std::random_access_iterator_tag, const uint32_t >
iterator_adaptor_base ()=default
const FixedStreamArrayIterator< PSHashRecord > & wrapped () const
Protected Attributes inherited from llvm::iterator_adaptor_base< GSIHashIterator, FixedStreamArrayIterator< PSHashRecord >, std::random_access_iterator_tag, const uint32_t >
FixedStreamArrayIterator< PSHashRecord > I
Detailed Description
Iterator over hash records producing symbol record offsets.
Abstracts away the fact that symbol record offsets on disk are off-by-one.
Definition at line 30 of file GlobalsStream.h.
Constructor & Destructor Documentation
GSIHashIterator()
template<typename T> llvm::pdb::GSIHashIterator::GSIHashIterator (T && v) inline
Definition at line 36 of file GlobalsStream.h.
References GSIHashIterator(), llvm::iterator_adaptor_base< GSIHashIterator, FixedStreamArrayIterator< PSHashRecord >, std::random_access_iterator_tag, const uint32_t >::iterator_adaptor_base(), and T.
Referenced by GSIHashIterator().
Member Function Documentation
operator*()
uint32_t llvm::pdb::GSIHashIterator::operator* () const inline
Definition at line 39 of file GlobalsStream.h.
References llvm::iterator_adaptor_base< GSIHashIterator, FixedStreamArrayIterator< PSHashRecord >, std::random_access_iterator_tag, const uint32_t >::I.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/PDB/Native/GlobalsStream.h