LLVM: llvm::SrcOp Class Reference
llvm::SrcOp Class Reference
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
Public Types
enum class SrcType { Ty_Reg , Ty_MIB , Ty_Predicate , Ty_Imm }
Public Member Functions
SrcOp (Register R)
SrcOp (const MachineOperand &Op)
SrcOp (const MachineInstrBuilder &MIB)
SrcOp (const CmpInst::Predicate P)
SrcOp (unsigned)=delete
Use of registers held in unsigned integer variables (or more rarely signed integers) is no longer permitted to avoid ambiguity with upcoming support for immediates.
SrcOp (int)=delete
SrcOp (uint64_t V)
SrcOp (int64_t V)
void addSrcToMIB (MachineInstrBuilder &MIB) const
LLT getLLTTy (const MachineRegisterInfo &MRI) const
Register getReg () const
CmpInst::Predicate getPredicate () const
int64_t getImm () const
SrcType getSrcOpKind () const
Detailed Description
Definition at line 143 of file MachineIRBuilder.h.
Member Enumeration Documentation
SrcType
enum class llvm::SrcOp::SrcType strong
Enumerator
Ty_Reg
Ty_MIB
Ty_Predicate
Ty_Imm
Definition at line 152 of file MachineIRBuilder.h.
Constructor & Destructor Documentation
SrcOp() [1/8]
llvm::SrcOp::SrcOp (Register R) inline
Definition at line 153 of file MachineIRBuilder.h.
References Reg, and Ty_Reg.
SrcOp() [2/8]
llvm::SrcOp::SrcOp (const MachineOperand & Op) inline
Definition at line 154 of file MachineIRBuilder.h.
References getReg(), Reg, and Ty_Reg.
SrcOp() [3/8]
llvm::SrcOp::SrcOp (const MachineInstrBuilder & MIB) inline
Definition at line 155 of file MachineIRBuilder.h.
References SrcMIB, and Ty_MIB.
SrcOp() [4/8]
llvm::SrcOp::SrcOp (const CmpInst::Predicate P) inline
Definition at line 156 of file MachineIRBuilder.h.
References P, Pred, and Ty_Predicate.
SrcOp() [5/8]
llvm::SrcOp::SrcOp (unsigned) delete
Use of registers held in unsigned integer variables (or more rarely signed integers) is no longer permitted to avoid ambiguity with upcoming support for immediates.
SrcOp() [6/8]
llvm::SrcOp::SrcOp (int) delete
SrcOp() [7/8]
llvm::SrcOp::SrcOp (uint64_t V) inline
Definition at line 162 of file MachineIRBuilder.h.
References Imm, and Ty_Imm.
SrcOp() [8/8]
llvm::SrcOp::SrcOp (int64_t V) inline
Definition at line 163 of file MachineIRBuilder.h.
References Imm, and Ty_Imm.
Member Function Documentation
addSrcToMIB()
void llvm::SrcOp::addSrcToMIB (MachineInstrBuilder & MIB) const inline
Definition at line 165 of file MachineIRBuilder.h.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addPredicate(), llvm::MachineInstrBuilder::addUse(), Imm, Pred, Reg, SrcMIB, Ty_Imm, Ty_MIB, Ty_Predicate, and Ty_Reg.
Referenced by llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::MachineIRBuilder::buildBrCond(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildPrefetch(), and llvm::MachineIRBuilder::buildStore().
getImm()
int64_t llvm::SrcOp::getImm () const inline
Definition at line 217 of file MachineIRBuilder.h.
References Imm, llvm_unreachable, and Ty_Imm.
Referenced by llvm::CSEMIRBuilder::buildInstr(), llvm::SIInstrInfo::expandMovDPP64(), llvm::SIInstrInfo::expandPostRAPseudo(), and llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic().
getLLTTy()
LLT llvm::SrcOp::getLLTTy (const MachineRegisterInfo & MRI) const inline
Definition at line 182 of file MachineIRBuilder.h.
References llvm_unreachable, MRI, Reg, SrcMIB, Ty_Imm, Ty_MIB, Ty_Predicate, and Ty_Reg.
Referenced by llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::MachineIRBuilder::buildBrCond(), llvm::MachineIRBuilder::buildDeleteTrailingVectorElements(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildShuffleVector(), llvm::MachineIRBuilder::buildStore(), llvm::MachineIRBuilder::buildStore(), and llvm::LegalizerHelper::createStackStoreLoad().
getPredicate()
CmpInst::Predicate llvm::SrcOp::getPredicate () const inline
Definition at line 208 of file MachineIRBuilder.h.
References llvm_unreachable, Pred, and Ty_Predicate.
getReg()
Register llvm::SrcOp::getReg () const inline
Definition at line 195 of file MachineIRBuilder.h.
References llvm_unreachable, Reg, SrcMIB, Ty_Imm, Ty_MIB, Ty_Predicate, and Ty_Reg.
Referenced by llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), buildSplatSplitS64WithVL(), convertImageAddrToPacked(), llvm::SPIRVInstrInfo::copyPhysReg(), llvm::SIInstrInfo::expandMovDPP64(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AMDGPURegisterBankInfo::getDefaultMappingSOP(), llvm::SIInstrInfo::getInstructionUniformity(), isCopyOf(), isCopyOfBundle(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), lookUpCopyChain(), packImage16bitOpsToDwords(), SrcOp(), and llvm::SIInstrInfo::verifyInstruction().
getSrcOpKind()
SrcType llvm::SrcOp::getSrcOpKind () const inline
Definition at line 226 of file MachineIRBuilder.h.
Member Data Documentation
Imm
int64_t llvm::SrcOp::Imm
Definition at line 148 of file MachineIRBuilder.h.
Referenced by addSrcToMIB(), getImm(), SrcOp(), and SrcOp().
Pred
CmpInst::Predicate llvm::SrcOp::Pred
Definition at line 147 of file MachineIRBuilder.h.
Referenced by addSrcToMIB(), getPredicate(), and SrcOp().
Reg
Register llvm::SrcOp::Reg
Definition at line 146 of file MachineIRBuilder.h.
Referenced by addSrcToMIB(), getLLTTy(), getReg(), SrcOp(), and SrcOp().
SrcMIB
MachineInstrBuilder llvm::SrcOp::SrcMIB
Definition at line 145 of file MachineIRBuilder.h.
Referenced by addSrcToMIB(), getLLTTy(), getReg(), and SrcOp().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h