LLVM: llvm::orc::LLJITBuilderState Class Reference
llvm::orc::LLJITBuilderState Class Reference
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Types
using ObjectLinkingLayerCreator
using CompileFunctionCreator
using ProcessSymbolsJITDylibSetupFunction
using PlatformSetupFunction = unique_function<Expected<JITDylibSP>(LLJIT &J)>
using NotifyCreatedFunction = std::function<Error(LLJIT &)>
Public Member Functions
LLVM_ABI Error prepareForConstruction ()
Called prior to JIT class construcion to fix up defaults.
Public Attributes
std::unique_ptr< ExecutorProcessControl > EPC
std::unique_ptr< ExecutionSession > ES
std::optional< JITTargetMachineBuilder > JTMB
std::optional< DataLayout > DL
bool LinkProcessSymbolsByDefault = true
ProcessSymbolsJITDylibSetupFunction SetupProcessSymbolsJITDylib
ObjectLinkingLayerCreator CreateObjectLinkingLayer
CompileFunctionCreator CreateCompileFunction
unique_function< Error(LLJIT &)> PrePlatformSetup
PlatformSetupFunction SetUpPlatform
NotifyCreatedFunction NotifyCreated
unsigned NumCompileThreads = 0
std::optional< bool > SupportConcurrentCompilation
Detailed Description
Definition at line 300 of file LLJIT.h.
Member Typedef Documentation
CompileFunctionCreator
using llvm::orc::LLJITBuilderState::CompileFunctionCreator
Initial value:
      std::function<Expected<std::unique_ptr<IRCompileLayer::IRCompiler>>(
          JITTargetMachineBuilder JTMB)>
Definition at line 305 of file LLJIT.h.
NotifyCreatedFunction
using llvm::orc::LLJITBuilderState::NotifyCreatedFunction = std::function<Error(LLJIT &)>
Definition at line 314 of file LLJIT.h.
ObjectLinkingLayerCreator
using llvm::orc::LLJITBuilderState::ObjectLinkingLayerCreator
Initial value:
      std::function<Expected<std::unique_ptr<ObjectLayer>>(ExecutionSession &)>
Definition at line 302 of file LLJIT.h.
PlatformSetupFunction
using llvm::orc::LLJITBuilderState::PlatformSetupFunction = unique_function<Expected<JITDylibSP>(LLJIT &J)>
Definition at line 312 of file LLJIT.h.
ProcessSymbolsJITDylibSetupFunction
using llvm::orc::LLJITBuilderState::ProcessSymbolsJITDylibSetupFunction
Initial value:
      unique_function<Expected<JITDylibSP>(LLJIT &J)>
Definition at line 309 of file LLJIT.h.
Member Function Documentation
prepareForConstruction()
Error llvm::orc::LLJITBuilderState::prepareForConstruction ()
Called prior to JIT class construcion to fix up defaults.
Definition at line 682 of file LLJIT.cpp.
References llvm::Triple::aarch64, llvm::orc::JITDylib::addGenerator(), llvm::Triple::arm, llvm::Triple::armeb, llvm::orc::SelfExecutorProcessControl::Create(), llvm::orc::ExecutionSession::createBareJITDylib(), CreateCompileFunction, CreateObjectLinkingLayer, D(), llvm::dbgs(), llvm::orc::JITTargetMachineBuilder::detectHost(), DL, EPC, ES, G, llvm::orc::JITDylib::getExecutionSession(), llvm::orc::EPCDynamicLibrarySearchGenerator::GetForTargetProcess(), llvm::inconvertibleErrorCode(), JTMB, LinkProcessSymbolsByDefault, LLVM_DEBUG, llvm::Triple::loongarch64, llvm::make_error(), NumCompileThreads, llvm::Reloc::PIC_, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::riscv64, SetUpPlatform, SetupProcessSymbolsJITDylib, llvm::CodeModel::Small, llvm::Error::success(), SupportConcurrentCompilation, llvm::Triple::thumb, llvm::Triple::thumbeb, and llvm::Triple::x86_64.
Referenced by llvm::orc::LLLazyJITBuilderState::prepareForConstruction().
Member Data Documentation
CreateCompileFunction
CompileFunctionCreator llvm::orc::LLJITBuilderState::CreateCompileFunction
Definition at line 323 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::createCompileFunction(), and prepareForConstruction().
CreateObjectLinkingLayer
ObjectLinkingLayerCreator llvm::orc::LLJITBuilderState::CreateObjectLinkingLayer
Definition at line 322 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::createObjectLinkingLayer(), and prepareForConstruction().
DL
std::optional<DataLayout> llvm::orc::LLJITBuilderState::DL
Definition at line 319 of file LLJIT.h.
Referenced by prepareForConstruction().
EPC
std::unique_ptr<ExecutorProcessControl> llvm::orc::LLJITBuilderState::EPC
Definition at line 316 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::LLJIT(), and prepareForConstruction().
ES
std::unique_ptr<ExecutionSession> llvm::orc::LLJITBuilderState::ES
Definition at line 317 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::LLJIT(), and prepareForConstruction().
JTMB
std::optional<JITTargetMachineBuilder> llvm::orc::LLJITBuilderState::JTMB
Definition at line 318 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::createObjectLinkingLayer(), llvm::orc::LLJIT::LLJIT(), prepareForConstruction(), and llvm::orc::LLLazyJITBuilderState::prepareForConstruction().
LinkProcessSymbolsByDefault
bool llvm::orc::LLJITBuilderState::LinkProcessSymbolsByDefault = true
Definition at line 320 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::LLJIT(), and prepareForConstruction().
NotifyCreated
NotifyCreatedFunction llvm::orc::LLJITBuilderState::NotifyCreated
Definition at line 326 of file LLJIT.h.
NumCompileThreads
unsigned llvm::orc::LLJITBuilderState::NumCompileThreads = 0
Definition at line 327 of file LLJIT.h.
Referenced by prepareForConstruction().
PrePlatformSetup
unique_function<Error(LLJIT &)> llvm::orc::LLJITBuilderState::PrePlatformSetup
Definition at line 324 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::LLJIT().
SetUpPlatform
PlatformSetupFunction llvm::orc::LLJITBuilderState::SetUpPlatform
Definition at line 325 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::LLJIT(), and prepareForConstruction().
SetupProcessSymbolsJITDylib
ProcessSymbolsJITDylibSetupFunction llvm::orc::LLJITBuilderState::SetupProcessSymbolsJITDylib
Definition at line 321 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::LLJIT(), and prepareForConstruction().
SupportConcurrentCompilation
std::optional<bool> llvm::orc::LLJITBuilderState::SupportConcurrentCompilation
Definition at line 328 of file LLJIT.h.
Referenced by llvm::orc::LLJIT::createCompileFunction(), llvm::orc::LLJIT::LLJIT(), and prepareForConstruction().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LLJIT.h
lib/ExecutionEngine/Orc/LLJIT.cpp