LLVM: llvm::TargetTransformInfoImplBase Class Reference
llvm::TargetTransformInfoImplBase Class Reference
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
#include "llvm/Analysis/TargetTransformInfoImpl.h"
Public Member Functions
virtual ~TargetTransformInfoImplBase ()
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)=default
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
virtual const DataLayout & getDataLayout () const
virtual InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const
virtual InstructionCost getPointersChainCost (ArrayRef< const Value * > Ptrs, const Value *Base, const TTI::PointersChainInfo &Info, Type *AccessTy, TTI::TargetCostKind CostKind) const
virtual unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
virtual InstructionCost getInstructionCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const
virtual unsigned getInliningThresholdMultiplier () const
virtual unsigned getInliningCostBenefitAnalysisSavingsMultiplier () const
virtual unsigned getInliningCostBenefitAnalysisProfitableMultiplier () const
virtual int getInliningLastCallToStaticBonus () const
virtual unsigned adjustInliningThreshold (const CallBase *CB) const
virtual unsigned getCallerAllocaCost (const CallBase *CB, const AllocaInst *AI) const
virtual int getInlinerVectorBonusPercent () const
virtual InstructionCost getMemcpyCost (const Instruction *I) const
virtual uint64_t getMaxMemIntrinsicInlineSizeThreshold () const
virtual BranchProbability getPredictableBranchThreshold () const
virtual InstructionCost getBranchMispredictPenalty () const
virtual bool hasBranchDivergence (const Function *F=nullptr) const
virtual bool isSourceOfDivergence (const Value *V) const
virtual bool isAlwaysUniform (const Value *V) const
virtual bool isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const
virtual bool addrspacesMayAlias (unsigned AS0, unsigned AS1) const
virtual unsigned getFlatAddressSpace () const
virtual bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
virtual bool isNoopAddrSpaceCast (unsigned, unsigned) const
virtual bool canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const
virtual unsigned getAssumedAddrSpace (const Value *V) const
virtual bool isSingleThreaded () const
virtual std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
virtual Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
virtual bool isLoweredToCall (const Function *F) const
virtual bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const
virtual unsigned getEpilogueVectorizationMinVF () const
virtual bool preferPredicateOverEpilogue (TailFoldingInfo *TFI) const
virtual TailFoldingStyle getPreferredTailFoldingStyle (bool IVUpdateMayOverflow=true) const
virtual std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const
virtual std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const
virtual std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
virtual void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &, OptimizationRemarkEmitter *) const
virtual void getPeelingPreferences (Loop *, ScalarEvolution &, TTI::PeelingPreferences &) const
virtual bool isLegalAddImmediate (int64_t Imm) const
virtual bool isLegalAddScalableImmediate (int64_t Imm) const
virtual bool isLegalICmpImmediate (int64_t Imm) const
virtual bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr, int64_t ScalableOffset=0) const
virtual bool isLSRCostLess (const TTI::LSRCost &C1, const TTI::LSRCost &C2) const
virtual bool isNumRegsMajorCostOfLSR () const
virtual bool shouldDropLSRSolutionIfLessProfitable () const
virtual bool isProfitableLSRChainElement (Instruction *I) const
virtual bool canMacroFuseCmp () const
virtual bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
virtual TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
virtual bool isLegalMaskedStore (Type *DataType, Align Alignment, unsigned AddressSpace) const
virtual bool isLegalMaskedLoad (Type *DataType, Align Alignment, unsigned AddressSpace) const
virtual bool isLegalNTStore (Type *DataType, Align Alignment) const
virtual bool isLegalNTLoad (Type *DataType, Align Alignment) const
virtual bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const
virtual bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
virtual bool isLegalMaskedGather (Type *DataType, Align Alignment) const
virtual bool forceScalarizeMaskedGather (VectorType *DataType, Align Alignment) const
virtual bool forceScalarizeMaskedScatter (VectorType *DataType, Align Alignment) const
virtual bool isLegalMaskedCompressStore (Type *DataType, Align Alignment) const
virtual bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const
virtual bool isLegalMaskedExpandLoad (Type *DataType, Align Alignment) const
virtual bool isLegalStridedLoadStore (Type *DataType, Align Alignment) const
virtual bool isLegalInterleavedAccessType (VectorType *VTy, unsigned Factor, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalMaskedVectorHistogram (Type *AddrType, Type *DataType) const
virtual bool enableOrderedReductions () const
virtual bool hasDivRemOp (Type *DataType, bool IsSigned) const
virtual bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
virtual bool prefersVectorizedAddressing () const
virtual InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
virtual bool LSRWithInstrQueries () const
virtual bool isTruncateFree (Type *Ty1, Type *Ty2) const
virtual bool isProfitableToHoist (Instruction *I) const
virtual bool useAA () const
virtual bool isTypeLegal (Type *Ty) const
virtual unsigned getRegUsageForType (Type *Ty) const
virtual bool shouldBuildLookupTables () const
virtual bool shouldBuildLookupTablesForConstant (Constant *C) const
virtual bool shouldBuildRelLookupTables () const
virtual bool useColdCCForColdCall (Function &F) const
virtual bool isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const
virtual bool isTargetIntrinsicWithScalarOpAtArg (Intrinsic::ID ID, unsigned ScalarOpdIdx) const
virtual bool isTargetIntrinsicWithOverloadTypeAtArg (Intrinsic::ID ID, int OpdIdx) const
virtual bool isTargetIntrinsicWithStructReturnOverloadAtField (Intrinsic::ID ID, int RetIdx) const
virtual InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc=true, ArrayRef< Value * > VL={}) const
virtual InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
virtual bool supportsEfficientVectorElementLoadStore () const
virtual bool supportsTailCalls () const
virtual bool supportsTailCallFor (const CallBase *CB) const
virtual bool enableAggressiveInterleaving (bool LoopHasReductions) const
virtual TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
virtual bool enableSelectOptimize () const
virtual bool shouldTreatInstructionLikeSelect (const Instruction *I) const
virtual bool enableInterleavedAccessVectorization () const
virtual bool enableMaskedInterleavedAccessVectorization () const
virtual bool isFPVectorizationPotentiallyUnsafe () const
virtual bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const
virtual TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
virtual bool haveFastSqrt (Type *Ty) const
virtual bool isExpensiveToSpeculativelyExecute (const Instruction *I) const
virtual bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const
virtual InstructionCost getFPOpCost (Type *Ty) const
virtual InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
virtual InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
virtual InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const
virtual InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
virtual bool preferToKeepConstantsAttached (const Instruction &Inst, const Function &Fn) const
virtual unsigned getNumberOfRegisters (unsigned ClassID) const
virtual bool hasConditionalLoadStoreForType (Type *Ty, bool IsStore) const
virtual unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
virtual const char * getRegisterClassName (unsigned ClassID) const
virtual TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
virtual unsigned getMinVectorRegisterBitWidth () const
virtual std::optional< unsigned > getMaxVScale () const
virtual std::optional< unsigned > getVScaleForTuning () const
virtual bool isVScaleKnownToBeAPowerOfTwo () const
virtual bool shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const
virtual ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
virtual unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
virtual unsigned getStoreMinimumVF (unsigned VF, Type *, Type *) const
virtual bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
virtual unsigned getCacheLineSize () const
virtual std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
virtual std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
virtual std::optional< unsigned > getMinPageSize () const
virtual unsigned getPrefetchDistance () const
virtual unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
virtual unsigned getMaxPrefetchIterationsAhead () const
virtual bool enableWritePrefetching () const
virtual bool shouldPrefetchAddressSpace (unsigned AS) const
virtual InstructionCost getPartialReductionCost (unsigned Opcode, Type *InputTypeA, Type *InputTypeB, Type *AccumType, ElementCount VF, TTI::PartialReductionExtendKind OpAExtend, TTI::PartialReductionExtendKind OpBExtend, std::optional< unsigned > BinOp, TTI::TargetCostKind CostKind) const
virtual unsigned getMaxInterleaveFactor (ElementCount VF) const
virtual InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info, TTI::OperandValueInfo Opd2Info, ArrayRef< const Value * > Args, const Instruction *CxtI=nullptr) const
virtual InstructionCost getAltInstrCost (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask, TTI::TargetCostKind CostKind) const
virtual InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *DstTy, VectorType *SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const
virtual InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I) const
virtual InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index, TTI::TargetCostKind CostKind) const
virtual InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
virtual InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info, TTI::OperandValueInfo Op2Info, const Instruction *I) const
virtual InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, const Value *Op0, const Value *Op1) const
virtual InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const
virtual InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const
virtual InstructionCost getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind) const
virtual InstructionCost getInsertExtractValueCost (unsigned Opcode, TTI::TargetCostKind CostKind) const
virtual InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo, const Instruction *I) const
virtual InstructionCost getVPMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I) const
virtual InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const
virtual InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
virtual InstructionCost getExpandCompressMemoryOpCost (unsigned Opcode, Type *DataTy, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
virtual InstructionCost getStridedMemoryOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
virtual InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const
virtual InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
virtual InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
virtual unsigned getNumberOfParts (Type *Tp) const
virtual InstructionCost getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *) const
virtual InstructionCost getArithmeticReductionCost (unsigned, VectorType *, std::optional< FastMathFlags > FMF, TTI::TargetCostKind) const
virtual InstructionCost getMinMaxReductionCost (Intrinsic::ID IID, VectorType *, FastMathFlags, TTI::TargetCostKind) const
virtual InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const
virtual InstructionCost getMulAccReductionCost (bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind) const
virtual InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
virtual bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
virtual unsigned getAtomicMemIntrinsicMaxElementSize () const
virtual Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType, bool CanCreate=true) const
virtual Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicElementSize) const
virtual void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicCpySize) const
virtual bool areInlineCompatible (const Function *Caller, const Function *Callee) const
virtual unsigned getInlineCallPenalty (const Function *F, const CallBase &Call, unsigned DefaultCallPenalty) const
virtual bool areTypesABICompatible (const Function *Caller, const Function *Callee, const ArrayRef< Type * > &Types) const
virtual bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty) const
virtual bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty) const
virtual unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
virtual bool isLegalToVectorizeLoad (LoadInst *LI) const
virtual bool isLegalToVectorizeStore (StoreInst *SI) const
virtual bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
virtual bool isElementTypeLegalForScalableVector (Type *Ty) const
virtual unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual bool preferFixedOverScalableIfEqualCost () const
virtual bool preferInLoopReduction (RecurKind Kind, Type *Ty) const
virtual bool preferAlternateOpcodeVectorization () const
virtual bool preferPredicatedReductionSelect () const
virtual bool preferEpilogueVectorization () const
virtual bool shouldExpandReduction (const IntrinsicInst *II) const
virtual TTI::ReductionShuffle getPreferredExpandedReductionShuffle (const IntrinsicInst *II) const
virtual unsigned getGISelRematGlobalCost () const
virtual unsigned getMinTripCountTailFoldingThreshold () const
virtual bool supportsScalableVectors () const
virtual bool enableScalableVectorization () const
virtual bool hasActiveVectorLength () const
virtual bool isProfitableToSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
virtual bool hasArmWideBranch (bool) const
virtual uint64_t getFeatureMask (const Function &F) const
virtual bool isMultiversionedFunction (const Function &F) const
virtual unsigned getMaxNumArgs () const
virtual unsigned getNumBytesToPadGlobalArray (unsigned Size, Type *ArrayType) const
virtual void collectKernelLaunchBounds (const Function &F, SmallVectorImpl< std::pair< StringRef, int64_t > > &LB) const
Protected Types
typedef TargetTransformInfo TTI
Protected Member Functions
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes
const DataLayout & DL
Detailed Description
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
Definition at line 34 of file TargetTransformInfoImpl.h.
Member Typedef Documentation
TTI
typedef TargetTransformInfo llvm::TargetTransformInfoImplBase::TTI protected
Definition at line 37 of file TargetTransformInfoImpl.h.
Constructor & Destructor Documentation
TargetTransformInfoImplBase() [1/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const DataLayout & DL) inline explicit protected
Definition at line 41 of file TargetTransformInfoImpl.h.
References DL.
Referenced by TargetTransformInfoImplBase(), and TargetTransformInfoImplBase().
~TargetTransformInfoImplBase()
TargetTransformInfoImplBase::~TargetTransformInfoImplBase () virtual default
TargetTransformInfoImplBase() [2/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const TargetTransformInfoImplBase & Arg) default
References TargetTransformInfoImplBase().
TargetTransformInfoImplBase() [3/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (TargetTransformInfoImplBase && Arg) inline
Definition at line 48 of file TargetTransformInfoImpl.h.
References DL, and TargetTransformInfoImplBase().
Member Function Documentation
addrspacesMayAlias()
virtual bool llvm::TargetTransformInfoImplBase::addrspacesMayAlias (unsigned AS0, unsigned AS1) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::GCNTTIImpl.
Definition at line 142 of file TargetTransformInfoImpl.h.
adjustInliningThreshold()
virtual unsigned llvm::TargetTransformInfoImplBase::adjustInliningThreshold (const CallBase * CB) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 102 of file TargetTransformInfoImpl.h.
allowsMisalignedMemoryAccesses()
virtual bool llvm::TargetTransformInfoImplBase::allowsMisalignedMemoryAccesses (LLVMContext & Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned * Fast) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 508 of file TargetTransformInfoImpl.h.
References llvm::BitWidth, and llvm::CallingConv::Fast.
areInlineCompatible()
virtual bool llvm::TargetTransformInfoImplBase::areInlineCompatible (const Function * Caller, const Function * Callee) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 1012 of file TargetTransformInfoImpl.h.
areTypesABICompatible()
virtual bool llvm::TargetTransformInfoImplBase::areTypesABICompatible (const Function * Caller, const Function * Callee, const ArrayRef< Type * > & Types) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 1025 of file TargetTransformInfoImpl.h.
Referenced by llvm::AArch64TTIImpl::areTypesABICompatible(), llvm::PPCTTIImpl::areTypesABICompatible(), and llvm::X86TTIImpl::areTypesABICompatible().
canHaveNonUndefGlobalInitializerInAddressSpace()
virtual bool llvm::TargetTransformInfoImplBase::canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const inline virtual
Reimplemented in llvm::GCNTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 155 of file TargetTransformInfoImpl.h.
canMacroFuseCmp()
virtual bool llvm::TargetTransformInfoImplBase::canMacroFuseCmp () const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 298 of file TargetTransformInfoImpl.h.
canSaveCmp()
virtual bool llvm::TargetTransformInfoImplBase::canSaveCmp (Loop * L, BranchInst ** BI, ScalarEvolution * SE, LoopInfo * LI, DominatorTree * DT, AssumptionCache * AC, TargetLibraryInfo * LibInfo) const inline virtual
Reimplemented in llvm::PPCTTIImpl.
Definition at line 300 of file TargetTransformInfoImpl.h.
collectFlatAddressOperands()
virtual bool llvm::TargetTransformInfoImplBase::collectFlatAddressOperands (SmallVectorImpl< int > & OpIndexes, Intrinsic::ID IID) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::SPIRVTTIImpl.
Definition at line 148 of file TargetTransformInfoImpl.h.
collectKernelLaunchBounds()
virtual void llvm::TargetTransformInfoImplBase::collectKernelLaunchBounds (const Function & F, SmallVectorImpl< std::pair< StringRef, int64_t > > & LB) const inline virtual
Reimplemented in llvm::GCNTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 1142 of file TargetTransformInfoImpl.h.
References F.
enableAggressiveInterleaving()
virtual bool llvm::TargetTransformInfoImplBase::enableAggressiveInterleaving (bool LoopHasReductions) const inline virtual
Reimplemented in llvm::HexagonTTIImpl, and llvm::PPCTTIImpl.
Definition at line 476 of file TargetTransformInfoImpl.h.
enableInterleavedAccessVectorization()
virtual bool llvm::TargetTransformInfoImplBase::enableInterleavedAccessVectorization () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 500 of file TargetTransformInfoImpl.h.
enableMaskedInterleavedAccessVectorization()
virtual bool llvm::TargetTransformInfoImplBase::enableMaskedInterleavedAccessVectorization () const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 502 of file TargetTransformInfoImpl.h.
enableMemCmpExpansion()
virtual TTI::MemCmpExpansionOptions llvm::TargetTransformInfoImplBase::enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BPFTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 481 of file TargetTransformInfoImpl.h.
enableOrderedReductions()
virtual bool llvm::TargetTransformInfoImplBase::enableOrderedReductions () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 388 of file TargetTransformInfoImpl.h.
enableScalableVectorization()
virtual bool llvm::TargetTransformInfoImplBase::enableScalableVectorization () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 1109 of file TargetTransformInfoImpl.h.
enableSelectOptimize()
virtual bool llvm::TargetTransformInfoImplBase::enableSelectOptimize () const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 485 of file TargetTransformInfoImpl.h.
enableWritePrefetching()
virtual bool llvm::TargetTransformInfoImplBase::enableWritePrefetching () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::LoongArchTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 652 of file TargetTransformInfoImpl.h.
forceScalarizeMaskedGather()
virtual bool llvm::TargetTransformInfoImplBase::forceScalarizeMaskedGather (VectorType * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::ARMTTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 348 of file TargetTransformInfoImpl.h.
forceScalarizeMaskedScatter()
virtual bool llvm::TargetTransformInfoImplBase::forceScalarizeMaskedScatter (VectorType * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::ARMTTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 353 of file TargetTransformInfoImpl.h.
getAddressComputationCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getAddressComputationCost (Type * Tp, ScalarEvolution * , const SCEV *) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::HexagonTTIImpl, and llvm::X86TTIImpl.
Definition at line 936 of file TargetTransformInfoImpl.h.
getAltInstrCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getAltInstrCost (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 705 of file TargetTransformInfoImpl.h.
References CostKind, and llvm::InstructionCost::getInvalid().
getArithmeticInstrCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info, TTI::OperandValueInfo Opd2Info, ArrayRef< const Value * > Args, const Instruction * CxtI = nullptr) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BPFTTIImpl, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LanaiTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 665 of file TargetTransformInfoImpl.h.
References llvm::any_of(), CostKind, llvm::dyn_cast(), II, llvm::TargetTransformInfo::TCC_Expensive, llvm::TargetTransformInfo::TCC_Free, and llvm::TargetTransformInfo::TCK_Latency.
Referenced by llvm::TargetTransformInfoImplCRTPBase< T >::getPointersChainCost().
getArithmeticReductionCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getArithmeticReductionCost (unsigned , VectorType * , std::optional< FastMathFlags > FMF, TTI::TargetCostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 942 of file TargetTransformInfoImpl.h.
getAssumedAddrSpace()
virtual unsigned llvm::TargetTransformInfoImplBase::getAssumedAddrSpace (const Value * V) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::NVPTXTTIImpl.
Definition at line 159 of file TargetTransformInfoImpl.h.
getAtomicMemIntrinsicMaxElementSize()
virtual unsigned llvm::TargetTransformInfoImplBase::getAtomicMemIntrinsicMaxElementSize () const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 977 of file TargetTransformInfoImpl.h.
getBranchMispredictPenalty()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getBranchMispredictPenalty () const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 128 of file TargetTransformInfoImpl.h.
getCacheAssociativity()
virtual std::optional< unsigned > llvm::TargetTransformInfoImplBase::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::X86TTIImpl.
Definition at line 631 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getCacheAssociativity().
getCacheLineSize()
virtual unsigned llvm::TargetTransformInfoImplBase::getCacheLineSize () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 618 of file TargetTransformInfoImpl.h.
getCacheSize()
virtual std::optional< unsigned > llvm::TargetTransformInfoImplBase::getCacheSize (TargetTransformInfo::CacheLevel Level) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::X86TTIImpl.
Definition at line 620 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
getCallerAllocaCost()
virtual unsigned llvm::TargetTransformInfoImplBase::getCallerAllocaCost (const CallBase * CB, const AllocaInst * AI) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::GCNTTIImpl.
Definition at line 105 of file TargetTransformInfoImpl.h.
getCallInstrCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::HexagonTTIImpl.
Definition at line 927 of file TargetTransformInfoImpl.h.
References CostKind, and F.
getCastInstrCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 720 of file TargetTransformInfoImpl.h.
References CostKind, DL, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), I, and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getCastInstrCost().
getCFInstrCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 764 of file TargetTransformInfoImpl.h.
References CostKind, I, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getCFInstrCost().
getCmpSelInstrCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info, TTI::OperandValueInfo Op2Info, const Instruction * I) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::BPFTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 774 of file TargetTransformInfoImpl.h.
References CostKind, and I.
getConstantStrideStep()
const SCEVConstant * llvm::TargetTransformInfoImplBase::getConstantStrideStep (ScalarEvolution * SE, const SCEV * Ptr) const inline protected
Definition at line 1207 of file TargetTransformInfoImpl.h.
References llvm::cast(), llvm::dyn_cast(), llvm::SCEVAddRecExpr::getStepRecurrence(), isStridedAccess(), and Ptr.
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and isConstantStridedAccessLessThan().
getCostOfKeepingLiveOverCall()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 968 of file TargetTransformInfoImpl.h.
getDataLayout()
virtual const DataLayout & llvm::TargetTransformInfoImplBase::getDataLayout () const inline virtual
Definition at line 50 of file TargetTransformInfoImpl.h.
References DL.
Referenced by llvm::AArch64TTIImpl::AArch64TTIImpl(), adjustInliningThresholdUsingCallee(), llvm::AMDGPUTTIImpl::AMDGPUTTIImpl(), llvm::ARCTTIImpl::ARCTTIImpl(), llvm::ARMTTIImpl::ARMTTIImpl(), llvm::BasicTTIImpl::BasicTTIImpl(), llvm::BPFTTIImpl::BPFTTIImpl(), llvm::DirectXTTIImpl::DirectXTTIImpl(), llvm::GCNTTIImpl::GCNTTIImpl(), llvm::RISCVTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getEstimatedNumberOfCaseClusters(), llvm::HexagonTTIImpl::getInstructionCost(), llvm::RISCVTTIImpl::getIntImmCost(), llvm::RISCVTTIImpl::getIntImmCostInst(), llvm::RISCVTTIImpl::getMemoryOpCost(), llvm::HexagonTTIImpl::HexagonTTIImpl(), llvm::LanaiTTIImpl::LanaiTTIImpl(), llvm::LoongArchTTIImpl::LoongArchTTIImpl(), llvm::MipsTTIImpl::MipsTTIImpl(), llvm::NVPTXTTIImpl::NVPTXTTIImpl(), llvm::PPCTTIImpl::PPCTTIImpl(), llvm::R600TTIImpl::R600TTIImpl(), llvm::RISCVTTIImpl::RISCVTTIImpl(), llvm::SPIRVTTIImpl::SPIRVTTIImpl(), llvm::SystemZTTIImpl::SystemZTTIImpl(), llvm::VETTIImpl::VETTIImpl(), llvm::WebAssemblyTTIImpl::WebAssemblyTTIImpl(), llvm::X86TTIImpl::X86TTIImpl(), and llvm::XCoreTTIImpl::XCoreTTIImpl().
getEpilogueVectorizationMinVF()
virtual unsigned llvm::TargetTransformInfoImplBase::getEpilogueVectorizationMinVF () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 228 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getEpilogueVectorizationMinVF().
getEstimatedNumberOfCaseClusters()
virtual unsigned llvm::TargetTransformInfoImplBase::getEstimatedNumberOfCaseClusters (const SwitchInst & SI, unsigned & JTSize, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 75 of file TargetTransformInfoImpl.h.
getExpandCompressMemoryOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getExpandCompressMemoryOpCost (unsigned Opcode, Type * DataTy, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 854 of file TargetTransformInfoImpl.h.
References CostKind, and I.
getExtendedReductionCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type * ResTy, VectorType * Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 955 of file TargetTransformInfoImpl.h.
References CostKind.
getExtractWithExtendCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getExtractWithExtendCost (unsigned Opcode, Type * Dst, VectorType * VecTy, unsigned Index, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 759 of file TargetTransformInfoImpl.h.
References CostKind.
getFeatureMask()
virtual uint64_t llvm::TargetTransformInfoImplBase::getFeatureMask (const Function & F) const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 1129 of file TargetTransformInfoImpl.h.
References F.
getFlatAddressSpace()
virtual unsigned llvm::TargetTransformInfoImplBase::getFlatAddressSpace () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::SPIRVTTIImpl.
Definition at line 146 of file TargetTransformInfoImpl.h.
getFPOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getFPOpCost (Type * Ty) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 529 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
getGatherScatterOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::HexagonTTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 847 of file TargetTransformInfoImpl.h.
References CostKind, I, and Ptr.
getGEPCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getGEPCost (Type * PointeeType, const Value * Ptr, ArrayRef< const Value * > Operands, Type * AccessType, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::TargetTransformInfoImplCRTPBase< T >.
Definition at line 54 of file TargetTransformInfoImpl.h.
References CostKind, llvm::isa(), Operands, Ptr, llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
getGISelRematGlobalCost()
virtual unsigned llvm::TargetTransformInfoImplBase::getGISelRematGlobalCost () const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 1103 of file TargetTransformInfoImpl.h.
getInlineCallPenalty()
virtual unsigned llvm::TargetTransformInfoImplBase::getInlineCallPenalty (const Function * F, const CallBase & Call, unsigned DefaultCallPenalty) const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 1020 of file TargetTransformInfoImpl.h.
References Call, and F.
getInlinerVectorBonusPercent()
virtual int llvm::TargetTransformInfoImplBase::getInlinerVectorBonusPercent () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::GCNTTIImpl.
Definition at line 110 of file TargetTransformInfoImpl.h.
getInliningCostBenefitAnalysisProfitableMultiplier()
virtual unsigned llvm::TargetTransformInfoImplBase::getInliningCostBenefitAnalysisProfitableMultiplier () const inline virtual
Definition at line 94 of file TargetTransformInfoImpl.h.
getInliningCostBenefitAnalysisSavingsMultiplier()
virtual unsigned llvm::TargetTransformInfoImplBase::getInliningCostBenefitAnalysisSavingsMultiplier () const inline virtual
Definition at line 91 of file TargetTransformInfoImpl.h.
getInliningLastCallToStaticBonus()
virtual int llvm::TargetTransformInfoImplBase::getInliningLastCallToStaticBonus () const inline virtual
Reimplemented in llvm::GCNTTIImpl.
Definition at line 97 of file TargetTransformInfoImpl.h.
Referenced by llvm::GCNTTIImpl::getInliningLastCallToStaticBonus().
getInliningThresholdMultiplier()
virtual unsigned llvm::TargetTransformInfoImplBase::getInliningThresholdMultiplier () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 90 of file TargetTransformInfoImpl.h.
getInsertExtractValueCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getInsertExtractValueCost (unsigned Opcode, TTI::TargetCostKind CostKind) const inline virtual
Definition at line 813 of file TargetTransformInfoImpl.h.
References CostKind, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, and llvm::TargetTransformInfo::TCK_RecipThroughput.
getInstructionCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getInstructionCost (const User * U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::HexagonTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, and llvm::TargetTransformInfoImplCRTPBase< T >.
Definition at line 85 of file TargetTransformInfoImpl.h.
References CostKind, llvm_unreachable, and Operands.
Referenced by llvm::HexagonTTIImpl::getInstructionCost(), llvm::NVPTXTTIImpl::getInstructionCost(), and llvm::PPCTTIImpl::getInstructionCost().
getInterleavedMemoryOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 868 of file TargetTransformInfoImpl.h.
References CostKind.
getIntImmCodeSizeCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty) const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 533 of file TargetTransformInfoImpl.h.
getIntImmCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCost (const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BPFTTIImpl, llvm::LanaiTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 539 of file TargetTransformInfoImpl.h.
References CostKind, and llvm::TargetTransformInfo::TCC_Basic.
Referenced by llvm::PPCTTIImpl::getIntImmCost().
getIntImmCostInst()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind, Instruction * Inst = nullptr) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::LanaiTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 544 of file TargetTransformInfoImpl.h.
References CostKind, and llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostInst().
getIntImmCostIntrin()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::LanaiTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 552 of file TargetTransformInfoImpl.h.
References CostKind, and llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostIntrin().
getIntrinsicInstrCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 876 of file TargetTransformInfoImpl.h.
References CostKind, llvm::IntrinsicCostAttributes::getID(), and llvm::InstructionCost::getInvalid().
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost().
getLoadStoreVecRegBitWidth()
virtual unsigned llvm::TargetTransformInfoImplBase::getLoadStoreVecRegBitWidth (unsigned AddrSpace) const inline virtual
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, llvm::R600TTIImpl, and llvm::X86TTIImpl.
Definition at line 1042 of file TargetTransformInfoImpl.h.
getLoadVectorFactor()
virtual unsigned llvm::TargetTransformInfoImplBase::getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline virtual
Reimplemented in llvm::GCNTTIImpl.
Definition at line 1071 of file TargetTransformInfoImpl.h.
getMaskedMemoryOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::HexagonTTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 840 of file TargetTransformInfoImpl.h.
References CostKind.
getMaximumVF()
virtual unsigned llvm::TargetTransformInfoImplBase::getMaximumVF (unsigned ElemWidth, unsigned Opcode) const inline virtual
Reimplemented in llvm::GCNTTIImpl, and llvm::RISCVTTIImpl.
Definition at line 605 of file TargetTransformInfoImpl.h.
getMaxInterleaveFactor()
virtual unsigned llvm::TargetTransformInfoImplBase::getMaxInterleaveFactor (ElementCount VF) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 663 of file TargetTransformInfoImpl.h.
getMaxMemIntrinsicInlineSizeThreshold()
virtual uint64_t llvm::TargetTransformInfoImplBase::getMaxMemIntrinsicInlineSizeThreshold () const inline virtual
Reimplemented in llvm::AMDGPUTTIImpl, llvm::ARMTTIImpl, llvm::GCNTTIImpl, and llvm::X86TTIImpl.
Definition at line 116 of file TargetTransformInfoImpl.h.
getMaxNumArgs()
virtual unsigned llvm::TargetTransformInfoImplBase::getMaxNumArgs () const inline virtual
Reimplemented in llvm::BPFTTIImpl.
Definition at line 1135 of file TargetTransformInfoImpl.h.
getMaxPrefetchIterationsAhead()
virtual unsigned llvm::TargetTransformInfoImplBase::getMaxPrefetchIterationsAhead () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 651 of file TargetTransformInfoImpl.h.
getMaxVScale()
virtual std::optional< unsigned > llvm::TargetTransformInfoImplBase::getMaxVScale () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 590 of file TargetTransformInfoImpl.h.
getMemcpyCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getMemcpyCost (const Instruction * I) const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 112 of file TargetTransformInfoImpl.h.
References I, and llvm::TargetTransformInfo::TCC_Expensive.
getMemcpyLoopLoweringType()
virtual Type * llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType (LLVMContext & Context, Value * Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicElementSize) const inline virtual
Reimplemented in llvm::GCNTTIImpl.
Definition at line 993 of file TargetTransformInfoImpl.h.
References llvm::Type::getInt8Ty(), llvm::Type::getIntNTy(), and llvm::Length.
getMemcpyLoopResidualLoweringType()
virtual void llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > & OpsOut, LLVMContext & Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicCpySize) const inline virtual
Reimplemented in llvm::GCNTTIImpl.
Definition at line 1001 of file TargetTransformInfoImpl.h.
References llvm::Type::getIntNTy(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType().
getMemoryOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo, const Instruction * I) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 825 of file TargetTransformInfoImpl.h.
References CostKind, and I.
getMinimumVF()
virtual ElementCount llvm::TargetTransformInfoImplBase::getMinimumVF (unsigned ElemWidth, bool IsScalable) const inline virtual
Reimplemented in llvm::HexagonTTIImpl.
Definition at line 601 of file TargetTransformInfoImpl.h.
References llvm::ElementCount::get().
getMinMaxReductionCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getMinMaxReductionCost (Intrinsic::ID IID, VectorType * , FastMathFlags , TTI::TargetCostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 948 of file TargetTransformInfoImpl.h.
getMinPageSize()
virtual std::optional< unsigned > llvm::TargetTransformInfoImplBase::getMinPageSize () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 642 of file TargetTransformInfoImpl.h.
getMinPrefetchStride()
virtual unsigned llvm::TargetTransformInfoImplBase::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::SystemZTTIImpl.
Definition at line 645 of file TargetTransformInfoImpl.h.
getMinTripCountTailFoldingThreshold()
virtual unsigned llvm::TargetTransformInfoImplBase::getMinTripCountTailFoldingThreshold () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 1105 of file TargetTransformInfoImpl.h.
getMinVectorRegisterBitWidth()
virtual unsigned llvm::TargetTransformInfoImplBase::getMinVectorRegisterBitWidth () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::DirectXTTIImpl, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::NVPTXTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, and llvm::VETTIImpl.
Definition at line 588 of file TargetTransformInfoImpl.h.
getMulAccReductionCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getMulAccReductionCost (bool IsUnsigned, Type * ResTy, VectorType * Ty, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 962 of file TargetTransformInfoImpl.h.
References CostKind.
getNumberOfParts()
virtual unsigned llvm::TargetTransformInfoImplBase::getNumberOfParts (Type * Tp) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::GCNTTIImpl.
Definition at line 934 of file TargetTransformInfoImpl.h.
getNumberOfRegisters()
virtual unsigned llvm::TargetTransformInfoImplBase::getNumberOfRegisters (unsigned ClassID) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::VETTIImpl, llvm::WebAssemblyTTIImpl, llvm::X86TTIImpl, and llvm::XCoreTTIImpl.
Definition at line 562 of file TargetTransformInfoImpl.h.
Referenced by llvm::WebAssemblyTTIImpl::getNumberOfRegisters().
getNumBytesToPadGlobalArray()
virtual unsigned llvm::TargetTransformInfoImplBase::getNumBytesToPadGlobalArray (unsigned Size, Type * ArrayType) const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 1137 of file TargetTransformInfoImpl.h.
References Size.
getOperandsScalarizationOverhead()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 462 of file TargetTransformInfoImpl.h.
References CostKind.
getOrCreateResultFromMemIntrinsic()
virtual Value * llvm::TargetTransformInfoImplBase::getOrCreateResultFromMemIntrinsic (IntrinsicInst * Inst, Type * ExpectedType, bool CanCreate = true) const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 987 of file TargetTransformInfoImpl.h.
getPartialReductionCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getPartialReductionCost (unsigned Opcode, Type * InputTypeA, Type * InputTypeB, Type * AccumType, ElementCount VF, TTI::PartialReductionExtendKind OpAExtend, TTI::PartialReductionExtendKind OpBExtend, std::optional< unsigned > BinOp, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::RISCVTTIImpl, and llvm::WebAssemblyTTIImpl.
Definition at line 655 of file TargetTransformInfoImpl.h.
References CostKind, and llvm::InstructionCost::getInvalid().
getPeelingPreferences()
virtual void llvm::TargetTransformInfoImplBase::getPeelingPreferences (Loop * , ScalarEvolution & , TTI::PeelingPreferences &) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::AMDGPUTTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 263 of file TargetTransformInfoImpl.h.
getPointersChainCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getPointersChainCost (ArrayRef< const Value * > Ptrs, const Value * Base, const TTI::PointersChainInfo & Info, Type * AccessTy, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::RISCVTTIImpl, llvm::TargetTransformInfoImplCRTPBase< T >, and llvm::X86TTIImpl.
Definition at line 68 of file TargetTransformInfoImpl.h.
References llvm::sampleprof::Base, CostKind, Info, and llvm_unreachable.
Referenced by llvm::X86TTIImpl::getPointersChainCost().
getPopcntSupport()
virtual TTI::PopcntSupportKind llvm::TargetTransformInfoImplBase::getPopcntSupport (unsigned IntTyWidthInBit) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LanaiTTIImpl, llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SPIRVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 517 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::PSK_Software.
getPredicatedAddrSpace()
virtual std::pair< const Value *, unsigned > llvm::TargetTransformInfoImplBase::getPredicatedAddrSpace (const Value * V) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 164 of file TargetTransformInfoImpl.h.
getPredictableBranchThreshold()
virtual BranchProbability llvm::TargetTransformInfoImplBase::getPredictableBranchThreshold () const inline virtual
Definition at line 124 of file TargetTransformInfoImpl.h.
getPreferredAddressingMode()
virtual TTI::AddressingModeKind llvm::TargetTransformInfoImplBase::getPreferredAddressingMode (const Loop * L, ScalarEvolution * SE) const inline virtual
Reimplemented in llvm::ARMTTIImpl, llvm::HexagonTTIImpl, and llvm::RISCVTTIImpl.
Definition at line 307 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::AMK_None.
Referenced by llvm::RISCVTTIImpl::getPreferredAddressingMode().
getPreferredExpandedReductionShuffle()
virtual TTI::ReductionShuffle llvm::TargetTransformInfoImplBase::getPreferredExpandedReductionShuffle (const IntrinsicInst * II) const inline virtual
Reimplemented in llvm::WebAssemblyTTIImpl.
Definition at line 1099 of file TargetTransformInfoImpl.h.
References II, and llvm::TargetTransformInfo::SplitHalf.
getPreferredTailFoldingStyle()
virtual TailFoldingStyle llvm::TargetTransformInfoImplBase::getPreferredTailFoldingStyle (bool IVUpdateMayOverflow = true) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 235 of file TargetTransformInfoImpl.h.
References llvm::DataWithoutLaneMask.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getPreferredTailFoldingStyle().
getPrefetchDistance()
virtual unsigned llvm::TargetTransformInfoImplBase::getPrefetchDistance () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 644 of file TargetTransformInfoImpl.h.
getRegisterBitWidth()
virtual TypeSize llvm::TargetTransformInfoImplBase::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::VETTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 584 of file TargetTransformInfoImpl.h.
References llvm::TypeSize::getFixed().
Referenced by llvm::LoongArchTTIImpl::getRegisterBitWidth().
getRegisterClassForType()
virtual unsigned llvm::TargetTransformInfoImplBase::getRegisterClassForType (bool Vector, Type * Ty = nullptr) const inline virtual
Reimplemented in llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, and llvm::RISCVTTIImpl.
Definition at line 567 of file TargetTransformInfoImpl.h.
References llvm::Vector.
getRegisterClassName()
virtual const char * llvm::TargetTransformInfoImplBase::getRegisterClassName (unsigned ClassID) const inline virtual
Reimplemented in llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, and llvm::RISCVTTIImpl.
Definition at line 572 of file TargetTransformInfoImpl.h.
getRegUsageForType()
virtual unsigned llvm::TargetTransformInfoImplBase::getRegUsageForType (Type * Ty) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 422 of file TargetTransformInfoImpl.h.
getReplicationShuffleCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getReplicationShuffleCost (Type * EltTy, int ReplicationFactor, int VF, const APInt & DemandedDstElts, TTI::TargetCostKind CostKind) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::X86TTIImpl.
Definition at line 806 of file TargetTransformInfoImpl.h.
References CostKind.
getScalarizationOverhead()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getScalarizationOverhead (VectorType * Ty, const APInt & DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc = true, ArrayRef< Value * > VL = {}) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::NVPTXTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 454 of file TargetTransformInfoImpl.h.
References CostKind.
getScalingFactorCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::X86TTIImpl.
Definition at line 400 of file TargetTransformInfoImpl.h.
References llvm::StackOffset::getFixed(), llvm::InstructionCost::getInvalid(), llvm::StackOffset::getScalable(), and isLegalAddressingMode().
getShuffleCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getShuffleCost (TTI::ShuffleKind Kind, VectorType * DstTy, VectorType * SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType * SubTp, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 713 of file TargetTransformInfoImpl.h.
References CostKind.
getStoreMinimumVF()
virtual unsigned llvm::TargetTransformInfoImplBase::getStoreMinimumVF (unsigned VF, Type * , Type *) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::X86TTIImpl.
Definition at line 608 of file TargetTransformInfoImpl.h.
getStoreVectorFactor()
virtual unsigned llvm::TargetTransformInfoImplBase::getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline virtual
Reimplemented in llvm::GCNTTIImpl.
Definition at line 1077 of file TargetTransformInfoImpl.h.
getStridedMemoryOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getStridedMemoryOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 861 of file TargetTransformInfoImpl.h.
References CostKind, llvm::InstructionCost::getInvalid(), I, and Ptr.
getTgtMemIntrinsic()
virtual bool llvm::TargetTransformInfoImplBase::getTgtMemIntrinsic (IntrinsicInst * Inst, MemIntrinsicInfo & Info) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::GCNTTIImpl, and llvm::PPCTTIImpl.
Definition at line 972 of file TargetTransformInfoImpl.h.
References Info.
getUnrollingPreferences()
virtual void llvm::TargetTransformInfoImplBase::getUnrollingPreferences (Loop * , ScalarEvolution & , TTI::UnrollingPreferences & , OptimizationRemarkEmitter *) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::AMDGPUTTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::WebAssemblyTTIImpl.
Definition at line 259 of file TargetTransformInfoImpl.h.
getVectorInstrCost() [1/3]
virtual InstructionCost llvm::TargetTransformInfoImplBase::getVectorInstrCost (const Instruction & I, Type * Val, TTI::TargetCostKind CostKind, unsigned Index) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 799 of file TargetTransformInfoImpl.h.
References CostKind, and I.
getVectorInstrCost() [2/3]
virtual InstructionCost llvm::TargetTransformInfoImplBase::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, const Value * Op0, const Value * Op1) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 781 of file TargetTransformInfoImpl.h.
References CostKind.
getVectorInstrCost() [3/3]
virtual InstructionCost llvm::TargetTransformInfoImplBase::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, Value * Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const inline virtual
Parameters
ScalarUserAndIdx encodes the information about extracts from a vector with 'Scalar' being the value being extracted,'User' being the user of the extract(nullptr if user is not known before vectorization) and 'Idx' being the extract lane.
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 792 of file TargetTransformInfoImpl.h.
References CostKind.
getVPLegalizationStrategy()
virtual TargetTransformInfo::VPLegalization llvm::TargetTransformInfoImplBase::getVPLegalizationStrategy (const VPIntrinsic & PI) const inline virtual
Reimplemented in llvm::RISCVTTIImpl, and llvm::VETTIImpl.
Definition at line 1121 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::VPLegalization::Convert, and llvm::TargetTransformInfo::VPLegalization::Discard.
getVPMemoryOpCost()
virtual InstructionCost llvm::TargetTransformInfoImplBase::getVPMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction * I) const inline virtual
Definition at line 831 of file TargetTransformInfoImpl.h.
References CostKind, and I.
getVScaleForTuning()
virtual std::optional< unsigned > llvm::TargetTransformInfoImplBase::getVScaleForTuning () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 591 of file TargetTransformInfoImpl.h.
hasActiveVectorLength()
virtual bool llvm::TargetTransformInfoImplBase::hasActiveVectorLength () const inline virtual
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 1111 of file TargetTransformInfoImpl.h.
hasArmWideBranch()
virtual bool llvm::TargetTransformInfoImplBase::hasArmWideBranch (bool) const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 1127 of file TargetTransformInfoImpl.h.
hasBranchDivergence()
virtual bool llvm::TargetTransformInfoImplBase::hasBranchDivergence (const Function * F = nullptr) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 130 of file TargetTransformInfoImpl.h.
References F.
hasConditionalLoadStoreForType()
virtual bool llvm::TargetTransformInfoImplBase::hasConditionalLoadStoreForType (Type * Ty, bool IsStore) const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 563 of file TargetTransformInfoImpl.h.
hasDivRemOp()
virtual bool llvm::TargetTransformInfoImplBase::hasDivRemOp (Type * DataType, bool IsSigned) const inline virtual
Reimplemented in llvm::MipsTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 390 of file TargetTransformInfoImpl.h.
hasVolatileVariant()
virtual bool llvm::TargetTransformInfoImplBase::hasVolatileVariant (Instruction * I, unsigned AddrSpace) const inline virtual
Reimplemented in llvm::NVPTXTTIImpl.
Definition at line 394 of file TargetTransformInfoImpl.h.
References I.
haveFastSqrt()
virtual bool llvm::TargetTransformInfoImplBase::haveFastSqrt (Type * Ty) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 521 of file TargetTransformInfoImpl.h.
instCombineIntrinsic()
virtual std::optional< Instruction * > llvm::TargetTransformInfoImplBase::instCombineIntrinsic (InstCombiner & IC, IntrinsicInst & II) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 240 of file TargetTransformInfoImpl.h.
References II.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::instCombineIntrinsic().
isAlwaysUniform()
virtual bool llvm::TargetTransformInfoImplBase::isAlwaysUniform (const Value * V) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::GCNTTIImpl.
Definition at line 136 of file TargetTransformInfoImpl.h.
isConstantStridedAccessLessThan()
bool llvm::TargetTransformInfoImplBase::isConstantStridedAccessLessThan (ScalarEvolution * SE, const SCEV * Ptr, int64_t MergeDistance) const inline protected
Definition at line 1215 of file TargetTransformInfoImpl.h.
References llvm::SCEVConstant::getAPInt(), llvm::APInt::getBitWidth(), getConstantStrideStep(), llvm::APInt::getSExtValue(), and Ptr.
Referenced by llvm::AArch64TTIImpl::getAddressComputationCost(), and llvm::ARMTTIImpl::getAddressComputationCost().
isElementTypeLegalForScalableVector()
virtual bool llvm::TargetTransformInfoImplBase::isElementTypeLegalForScalableVector (Type * Ty) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 1067 of file TargetTransformInfoImpl.h.
isExpensiveToSpeculativelyExecute()
virtual bool llvm::TargetTransformInfoImplBase::isExpensiveToSpeculativelyExecute (const Instruction * I) const inline virtual
Reimplemented in llvm::TargetTransformInfoImplCRTPBase< T >, and llvm::X86TTIImpl.
Definition at line 523 of file TargetTransformInfoImpl.h.
References I.
Referenced by llvm::X86TTIImpl::isExpensiveToSpeculativelyExecute().
isFCmpOrdCheaperThanFCmpZero()
virtual bool llvm::TargetTransformInfoImplBase::isFCmpOrdCheaperThanFCmpZero (Type * Ty) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::X86TTIImpl.
Definition at line 527 of file TargetTransformInfoImpl.h.
isFPVectorizationPotentiallyUnsafe()
virtual bool llvm::TargetTransformInfoImplBase::isFPVectorizationPotentiallyUnsafe () const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 506 of file TargetTransformInfoImpl.h.
isHardwareLoopProfitable()
virtual bool llvm::TargetTransformInfoImplBase::isHardwareLoopProfitable (Loop * L, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * LibInfo, HardwareLoopInfo & HWLoopInfo) const inline virtual
Reimplemented in llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::PPCTTIImpl.
Definition at line 221 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::isHardwareLoopProfitable().
isIndexedLoadLegal()
virtual bool llvm::TargetTransformInfoImplBase::isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type * Ty) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 1034 of file TargetTransformInfoImpl.h.
References Mode.
isIndexedStoreLegal()
virtual bool llvm::TargetTransformInfoImplBase::isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type * Ty) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 1038 of file TargetTransformInfoImpl.h.
References Mode.
isLegalAddImmediate()
virtual bool llvm::TargetTransformInfoImplBase::isLegalAddImmediate (int64_t Imm) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 266 of file TargetTransformInfoImpl.h.
isLegalAddressingMode()
virtual bool llvm::TargetTransformInfoImplBase::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction * I = nullptr, int64_t ScalableOffset = 0) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 272 of file TargetTransformInfoImpl.h.
References I.
Referenced by llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), and getScalingFactorCost().
isLegalAddScalableImmediate()
virtual bool llvm::TargetTransformInfoImplBase::isLegalAddScalableImmediate (int64_t Imm) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 268 of file TargetTransformInfoImpl.h.
isLegalAltInstr()
virtual bool llvm::TargetTransformInfoImplBase::isLegalAltInstr (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask) const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 363 of file TargetTransformInfoImpl.h.
isLegalBroadcastLoad()
virtual bool llvm::TargetTransformInfoImplBase::isLegalBroadcastLoad (Type * ElementTy, ElementCount NumElements) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::X86TTIImpl.
Definition at line 335 of file TargetTransformInfoImpl.h.
isLegalICmpImmediate()
virtual bool llvm::TargetTransformInfoImplBase::isLegalICmpImmediate (int64_t Imm) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 270 of file TargetTransformInfoImpl.h.
isLegalInterleavedAccessType()
virtual bool llvm::TargetTransformInfoImplBase::isLegalInterleavedAccessType (VectorType * VTy, unsigned Factor, Align Alignment, unsigned AddrSpace) const inline virtual
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 377 of file TargetTransformInfoImpl.h.
isLegalMaskedCompressStore()
virtual bool llvm::TargetTransformInfoImplBase::isLegalMaskedCompressStore (Type * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 358 of file TargetTransformInfoImpl.h.
isLegalMaskedExpandLoad()
virtual bool llvm::TargetTransformInfoImplBase::isLegalMaskedExpandLoad (Type * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 369 of file TargetTransformInfoImpl.h.
isLegalMaskedGather()
virtual bool llvm::TargetTransformInfoImplBase::isLegalMaskedGather (Type * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::RISCVTTIImpl, llvm::VETTIImpl, and llvm::X86TTIImpl.
Definition at line 344 of file TargetTransformInfoImpl.h.
isLegalMaskedLoad()
virtual bool llvm::TargetTransformInfoImplBase::isLegalMaskedLoad (Type * DataType, Align Alignment, unsigned AddressSpace) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::HexagonTTIImpl, llvm::RISCVTTIImpl, llvm::VETTIImpl, and llvm::X86TTIImpl.
Definition at line 316 of file TargetTransformInfoImpl.h.
isLegalMaskedScatter()
virtual bool llvm::TargetTransformInfoImplBase::isLegalMaskedScatter (Type * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::RISCVTTIImpl, llvm::VETTIImpl, and llvm::X86TTIImpl.
Definition at line 340 of file TargetTransformInfoImpl.h.
isLegalMaskedStore()
virtual bool llvm::TargetTransformInfoImplBase::isLegalMaskedStore (Type * DataType, Align Alignment, unsigned AddressSpace) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::HexagonTTIImpl, llvm::RISCVTTIImpl, llvm::VETTIImpl, and llvm::X86TTIImpl.
Definition at line 311 of file TargetTransformInfoImpl.h.
isLegalMaskedVectorHistogram()
virtual bool llvm::TargetTransformInfoImplBase::isLegalMaskedVectorHistogram (Type * AddrType, Type * DataType) const inline virtual
Definition at line 383 of file TargetTransformInfoImpl.h.
isLegalNTLoad()
virtual bool llvm::TargetTransformInfoImplBase::isLegalNTLoad (Type * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::X86TTIImpl.
Definition at line 328 of file TargetTransformInfoImpl.h.
References llvm::DataSize, DL, and llvm::isPowerOf2_32().
Referenced by llvm::AArch64TTIImpl::isLegalNTLoad().
isLegalNTStore()
virtual bool llvm::TargetTransformInfoImplBase::isLegalNTStore (Type * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::X86TTIImpl.
Definition at line 321 of file TargetTransformInfoImpl.h.
References llvm::DataSize, DL, and llvm::isPowerOf2_32().
Referenced by llvm::AArch64TTIImpl::isLegalNTStoreLoad().
isLegalStridedLoadStore()
virtual bool llvm::TargetTransformInfoImplBase::isLegalStridedLoadStore (Type * DataType, Align Alignment) const inline virtual
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 373 of file TargetTransformInfoImpl.h.
isLegalToVectorizeLoad()
virtual bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoad (LoadInst * LI) const inline virtual
Definition at line 1046 of file TargetTransformInfoImpl.h.
isLegalToVectorizeLoadChain()
virtual bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const inline virtual
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::R600TTIImpl.
Definition at line 1050 of file TargetTransformInfoImpl.h.
isLegalToVectorizeReduction()
virtual bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeReduction (const RecurrenceDescriptor & RdxDesc, ElementCount VF) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 1062 of file TargetTransformInfoImpl.h.
isLegalToVectorizeStore()
virtual bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStore (StoreInst * SI) const inline virtual
Definition at line 1048 of file TargetTransformInfoImpl.h.
isLegalToVectorizeStoreChain()
virtual bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const inline virtual
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::R600TTIImpl.
Definition at line 1056 of file TargetTransformInfoImpl.h.
isLoweredToCall()
virtual bool llvm::TargetTransformInfoImplBase::isLoweredToCall (const Function * F) const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 174 of file TargetTransformInfoImpl.h.
References assert(), and F.
Referenced by llvm::AArch64TTIImpl::getUnrollingPreferences(), llvm::BasicTTIImplBase< BasicTTIImpl >::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::SystemZTTIImpl::getUnrollingPreferences(), llvm::WebAssemblyTTIImpl::getUnrollingPreferences(), and llvm::ARMTTIImpl::isLoweredToCall().
isLSRCostLess()
virtual bool llvm::TargetTransformInfoImplBase::isLSRCostLess (const TTI::LSRCost & C1, const TTI::LSRCost & C2) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::MipsTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 282 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
Referenced by llvm::AArch64TTIImpl::isLSRCostLess(), llvm::BasicTTIImplBase< BasicTTIImpl >::isLSRCostLess(), and llvm::PPCTTIImpl::isLSRCostLess().
isMultiversionedFunction()
virtual bool llvm::TargetTransformInfoImplBase::isMultiversionedFunction (const Function & F) const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 1131 of file TargetTransformInfoImpl.h.
References F.
isNoopAddrSpaceCast()
virtual bool llvm::TargetTransformInfoImplBase::isNoopAddrSpaceCast (unsigned , unsigned) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 153 of file TargetTransformInfoImpl.h.
isNumRegsMajorCostOfLSR()
virtual bool llvm::TargetTransformInfoImplBase::isNumRegsMajorCostOfLSR () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::PPCTTIImpl.
Definition at line 290 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::isNumRegsMajorCostOfLSR().
isProfitableLSRChainElement()
virtual bool llvm::TargetTransformInfoImplBase::isProfitableLSRChainElement (Instruction * I) const inline virtual
Reimplemented in llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 294 of file TargetTransformInfoImpl.h.
References I.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::isProfitableLSRChainElement().
isProfitableToHoist()
virtual bool llvm::TargetTransformInfoImplBase::isProfitableToHoist (Instruction * I) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 416 of file TargetTransformInfoImpl.h.
References I.
isProfitableToSinkOperands()
virtual bool llvm::TargetTransformInfoImplBase::isProfitableToSinkOperands (Instruction * I, SmallVectorImpl< Use * > & Ops) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::GCNTTIImpl, llvm::RISCVTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1113 of file TargetTransformInfoImpl.h.
References AbstractManglingParser< Derived, Alloc >::Ops, and I.
isSingleThreaded()
virtual bool llvm::TargetTransformInfoImplBase::isSingleThreaded () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 161 of file TargetTransformInfoImpl.h.
isSourceOfDivergence()
virtual bool llvm::TargetTransformInfoImplBase::isSourceOfDivergence (const Value * V) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 134 of file TargetTransformInfoImpl.h.
isStridedAccess()
bool llvm::TargetTransformInfoImplBase::isStridedAccess (const SCEV * Ptr) const inline protected
Definition at line 1203 of file TargetTransformInfoImpl.h.
References llvm::isa(), and Ptr.
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and getConstantStrideStep().
isTargetIntrinsicTriviallyScalarizable()
virtual bool llvm::TargetTransformInfoImplBase::isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::DirectXTTIImpl.
Definition at line 434 of file TargetTransformInfoImpl.h.
isTargetIntrinsicWithOverloadTypeAtArg()
virtual bool llvm::TargetTransformInfoImplBase::isTargetIntrinsicWithOverloadTypeAtArg (Intrinsic::ID ID, int OpdIdx) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::DirectXTTIImpl.
Definition at line 443 of file TargetTransformInfoImpl.h.
isTargetIntrinsicWithScalarOpAtArg()
virtual bool llvm::TargetTransformInfoImplBase::isTargetIntrinsicWithScalarOpAtArg (Intrinsic::ID ID, unsigned ScalarOpdIdx) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::DirectXTTIImpl.
Definition at line 438 of file TargetTransformInfoImpl.h.
isTargetIntrinsicWithStructReturnOverloadAtField()
virtual bool llvm::TargetTransformInfoImplBase::isTargetIntrinsicWithStructReturnOverloadAtField (Intrinsic::ID ID, int RetIdx) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 449 of file TargetTransformInfoImpl.h.
isTruncateFree()
virtual bool llvm::TargetTransformInfoImplBase::isTruncateFree (Type * Ty1, Type * Ty2) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 414 of file TargetTransformInfoImpl.h.
isTypeLegal()
virtual bool llvm::TargetTransformInfoImplBase::isTypeLegal (Type * Ty) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 420 of file TargetTransformInfoImpl.h.
isValidAddrSpaceCast()
virtual bool llvm::TargetTransformInfoImplBase::isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::GCNTTIImpl.
Definition at line 138 of file TargetTransformInfoImpl.h.
isVectorShiftByScalarCheap()
virtual bool llvm::TargetTransformInfoImplBase::isVectorShiftByScalarCheap (Type * Ty) const inline virtual
Reimplemented in llvm::X86TTIImpl.
Definition at line 1118 of file TargetTransformInfoImpl.h.
isVScaleKnownToBeAPowerOfTwo()
virtual bool llvm::TargetTransformInfoImplBase::isVScaleKnownToBeAPowerOfTwo () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::RISCVTTIImpl.
Definition at line 594 of file TargetTransformInfoImpl.h.
LSRWithInstrQueries()
virtual bool llvm::TargetTransformInfoImplBase::LSRWithInstrQueries () const inline virtual
Reimplemented in llvm::SystemZTTIImpl.
Definition at line 412 of file TargetTransformInfoImpl.h.
minRequiredElementSize()
unsigned llvm::TargetTransformInfoImplBase::minRequiredElementSize (const Value * Val, bool & isSigned) const inline protected
Definition at line 1149 of file TargetTransformInfoImpl.h.
References llvm::cast(), llvm::dyn_cast(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::isa(), and isSigned().
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost().
preferAlternateOpcodeVectorization()
virtual bool llvm::TargetTransformInfoImplBase::preferAlternateOpcodeVectorization () const inline virtual
Reimplemented in llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 1088 of file TargetTransformInfoImpl.h.
preferEpilogueVectorization()
virtual bool llvm::TargetTransformInfoImplBase::preferEpilogueVectorization () const inline virtual
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 1092 of file TargetTransformInfoImpl.h.
preferFixedOverScalableIfEqualCost()
virtual bool llvm::TargetTransformInfoImplBase::preferFixedOverScalableIfEqualCost () const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 1083 of file TargetTransformInfoImpl.h.
preferInLoopReduction()
virtual bool llvm::TargetTransformInfoImplBase::preferInLoopReduction (RecurKind Kind, Type * Ty) const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 1085 of file TargetTransformInfoImpl.h.
preferPredicatedReductionSelect()
virtual bool llvm::TargetTransformInfoImplBase::preferPredicatedReductionSelect () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::ARMTTIImpl.
Definition at line 1090 of file TargetTransformInfoImpl.h.
preferPredicateOverEpilogue()
virtual bool llvm::TargetTransformInfoImplBase::preferPredicateOverEpilogue (TailFoldingInfo * TFI) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 230 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::preferPredicateOverEpilogue().
prefersVectorizedAddressing()
virtual bool llvm::TargetTransformInfoImplBase::prefersVectorizedAddressing () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::HexagonTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 398 of file TargetTransformInfoImpl.h.
preferToKeepConstantsAttached()
virtual bool llvm::TargetTransformInfoImplBase::preferToKeepConstantsAttached (const Instruction & Inst, const Function & Fn) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 557 of file TargetTransformInfoImpl.h.
rewriteIntrinsicWithAddressSpace()
virtual Value * llvm::TargetTransformInfoImplBase::rewriteIntrinsicWithAddressSpace (IntrinsicInst * II, Value * OldV, Value * NewV) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::SPIRVTTIImpl.
Definition at line 168 of file TargetTransformInfoImpl.h.
References II.
shouldBuildLookupTables()
virtual bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTables () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::HexagonTTIImpl, and llvm::LanaiTTIImpl.
Definition at line 424 of file TargetTransformInfoImpl.h.
shouldBuildLookupTablesForConstant()
virtual bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTablesForConstant (Constant * C) const inline virtual
Reimplemented in llvm::ARMTTIImpl.
Definition at line 426 of file TargetTransformInfoImpl.h.
References llvm::CallingConv::C.
shouldBuildRelLookupTables()
virtual bool llvm::TargetTransformInfoImplBase::shouldBuildRelLookupTables () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::PPCTTIImpl, and llvm::VETTIImpl.
Definition at line 430 of file TargetTransformInfoImpl.h.
shouldConsiderAddressTypePromotion()
virtual bool llvm::TargetTransformInfoImplBase::shouldConsiderAddressTypePromotion (const Instruction & I, bool & AllowPromotionWithoutCommonHeader) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 612 of file TargetTransformInfoImpl.h.
References I.
shouldDropLSRSolutionIfLessProfitable()
virtual bool llvm::TargetTransformInfoImplBase::shouldDropLSRSolutionIfLessProfitable () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 292 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::shouldDropLSRSolutionIfLessProfitable().
shouldExpandReduction()
virtual bool llvm::TargetTransformInfoImplBase::shouldExpandReduction (const IntrinsicInst * II) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::VETTIImpl.
Definition at line 1094 of file TargetTransformInfoImpl.h.
References II.
shouldMaximizeVectorBandwidth()
virtual bool llvm::TargetTransformInfoImplBase::shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::HexagonTTIImpl.
Definition at line 597 of file TargetTransformInfoImpl.h.
shouldPrefetchAddressSpace()
virtual bool llvm::TargetTransformInfoImplBase::shouldPrefetchAddressSpace (unsigned AS) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::GCNTTIImpl.
Definition at line 653 of file TargetTransformInfoImpl.h.
shouldTreatInstructionLikeSelect()
virtual bool llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect (const Instruction * I) const inline virtual
Reimplemented in llvm::AArch64TTIImpl.
Definition at line 487 of file TargetTransformInfoImpl.h.
References I, llvm::isa(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::AArch64TTIImpl::shouldTreatInstructionLikeSelect().
simplifyDemandedUseBitsIntrinsic()
virtual std::optional< Value * > llvm::TargetTransformInfoImplBase::simplifyDemandedUseBitsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedMask, KnownBits & Known, bool & KnownBitsComputed) const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, and llvm::X86TTIImpl.
Definition at line 245 of file TargetTransformInfoImpl.h.
References II.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::simplifyDemandedUseBitsIntrinsic().
simplifyDemandedVectorEltsIntrinsic()
virtual std::optional< Value * > llvm::TargetTransformInfoImplBase::simplifyDemandedVectorEltsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, APInt & UndefElts, APInt & UndefElts2, APInt & UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const inline virtual
Reimplemented in llvm::AArch64TTIImpl, llvm::ARMTTIImpl, llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, llvm::BasicTTIImplBase< XCoreTTIImpl >, llvm::GCNTTIImpl, and llvm::X86TTIImpl.
Definition at line 251 of file TargetTransformInfoImpl.h.
References II.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::simplifyDemandedVectorEltsIntrinsic().
supportsEfficientVectorElementLoadStore()
virtual bool llvm::TargetTransformInfoImplBase::supportsEfficientVectorElementLoadStore () const inline virtual
Reimplemented in llvm::HexagonTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 468 of file TargetTransformInfoImpl.h.
supportsScalableVectors()
virtual bool llvm::TargetTransformInfoImplBase::supportsScalableVectors () const inline virtual
Reimplemented in llvm::AArch64TTIImpl, and llvm::RISCVTTIImpl.
Definition at line 1107 of file TargetTransformInfoImpl.h.
supportsTailCallFor()
virtual bool llvm::TargetTransformInfoImplBase::supportsTailCallFor (const CallBase * CB) const inline virtual
Reimplemented in llvm::PPCTTIImpl, and llvm::TargetTransformInfoImplCRTPBase< T >.
Definition at line 472 of file TargetTransformInfoImpl.h.
References llvm_unreachable.
supportsTailCalls()
virtual bool llvm::TargetTransformInfoImplBase::supportsTailCalls () const inline virtual
Reimplemented in llvm::WebAssemblyTTIImpl.
Definition at line 470 of file TargetTransformInfoImpl.h.
Referenced by llvm::TargetTransformInfoImplCRTPBase< T >::supportsTailCallFor().
useAA()
virtual bool llvm::TargetTransformInfoImplBase::useAA () const inline virtual
Reimplemented in llvm::BasicTTIImplBase< T >, llvm::BasicTTIImplBase< AArch64TTIImpl >, llvm::BasicTTIImplBase< AMDGPUTTIImpl >, llvm::BasicTTIImplBase< ARCTTIImpl >, llvm::BasicTTIImplBase< ARMTTIImpl >, llvm::BasicTTIImplBase< BasicTTIImpl >, llvm::BasicTTIImplBase< BPFTTIImpl >, llvm::BasicTTIImplBase< DirectXTTIImpl >, llvm::BasicTTIImplBase< GCNTTIImpl >, llvm::BasicTTIImplBase< HexagonTTIImpl >, llvm::BasicTTIImplBase< LanaiTTIImpl >, llvm::BasicTTIImplBase< LoongArchTTIImpl >, llvm::BasicTTIImplBase< MipsTTIImpl >, llvm::BasicTTIImplBase< NVPTXTTIImpl >, llvm::BasicTTIImplBase< PPCTTIImpl >, llvm::BasicTTIImplBase< R600TTIImpl >, llvm::BasicTTIImplBase< RISCVTTIImpl >, llvm::BasicTTIImplBase< SPIRVTTIImpl >, llvm::BasicTTIImplBase< SystemZTTIImpl >, llvm::BasicTTIImplBase< VETTIImpl >, llvm::BasicTTIImplBase< WebAssemblyTTIImpl >, llvm::BasicTTIImplBase< X86TTIImpl >, and llvm::BasicTTIImplBase< XCoreTTIImpl >.
Definition at line 418 of file TargetTransformInfoImpl.h.
useColdCCForColdCall()
virtual bool llvm::TargetTransformInfoImplBase::useColdCCForColdCall (Function & F) const inline virtual
Reimplemented in llvm::PPCTTIImpl.
Definition at line 432 of file TargetTransformInfoImpl.h.
References F.
Member Data Documentation
DL
const DataLayout& llvm::TargetTransformInfoImplBase::DL protected
Definition at line 39 of file TargetTransformInfoImpl.h.
Referenced by getCastInstrCost(), getDataLayout(), llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), isLegalNTLoad(), isLegalNTStore(), TargetTransformInfoImplBase(), TargetTransformInfoImplBase(), llvm::TargetTransformInfoImplCRTPBase< T >::TargetTransformInfoImplCRTPBase(), and llvm::BasicTTIImplBase< BasicTTIImpl >::~BasicTTIImplBase().
The documentation for this class was generated from the following files:
include/llvm/Analysis/TargetTransformInfoImpl.h
lib/Analysis/TargetTransformInfo.cpp