LLVM: llvm::MachineInstrBuilder Class Reference
llvm::MachineInstrBuilder Class Reference
#include "llvm/CodeGen/MachineInstrBuilder.h"
Public Member Functions
MachineInstrBuilder ()=default
MachineInstrBuilder (MachineFunction &F, MachineInstr *I)
Create a MachineInstrBuilder for manipulating an existing instruction.
MachineInstrBuilder (MachineFunction &F, MachineBasicBlock::iterator I)
operator MachineInstr * () const
Allow automatic conversion to the machine instruction we are working on.
MachineInstr * operator-> () const
operator MachineBasicBlock::iterator () const
MachineInstr * getInstr () const
If conversion operators fail, use this method to get the MachineInstr explicitly.
Register getReg (unsigned Idx) const
Get the register for the operand index.
const MachineInstrBuilder & addReg (Register RegNo, unsigned flags=0, unsigned SubReg=0) const
Add a new virtual register operand.
const MachineInstrBuilder & addDef (Register RegNo, unsigned Flags=0, unsigned SubReg=0) const
Add a virtual register definition operand.
const MachineInstrBuilder & addUse (Register RegNo, unsigned Flags=0, unsigned SubReg=0) const
Add a virtual register use operand.
const MachineInstrBuilder & addImm (int64_t Val) const
Add a new immediate operand.
const MachineInstrBuilder & addCImm (const ConstantInt *Val) const
const MachineInstrBuilder & addFPImm (const ConstantFP *Val) const
const MachineInstrBuilder & addMBB (MachineBasicBlock *MBB, unsigned TargetFlags=0) const
const MachineInstrBuilder & addFrameIndex (int Idx) const
const MachineInstrBuilder & addConstantPoolIndex (unsigned Idx, int Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addTargetIndex (unsigned Idx, int64_t Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addJumpTableIndex (unsigned Idx, unsigned TargetFlags=0) const
const MachineInstrBuilder & addGlobalAddress (const GlobalValue *GV, int64_t Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addExternalSymbol (const char *FnName, unsigned TargetFlags=0) const
const MachineInstrBuilder & addBlockAddress (const BlockAddress *BA, int64_t Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addRegMask (const uint32_t *Mask) const
const MachineInstrBuilder & addMemOperand (MachineMemOperand *MMO) const
const MachineInstrBuilder & setMemRefs (ArrayRef< MachineMemOperand * > MMOs) const
const MachineInstrBuilder & cloneMemRefs (const MachineInstr &OtherMI) const
const MachineInstrBuilder & cloneMergedMemRefs (ArrayRef< const MachineInstr * > OtherMIs) const
const MachineInstrBuilder & add (const MachineOperand &MO) const
const MachineInstrBuilder & add (ArrayRef< MachineOperand > MOs) const
const MachineInstrBuilder & addMetadata (const MDNode *MD) const
const MachineInstrBuilder & addCFIIndex (unsigned CFIIndex) const
const MachineInstrBuilder & addIntrinsicID (Intrinsic::ID ID) const
const MachineInstrBuilder & addPredicate (CmpInst::Predicate Pred) const
const MachineInstrBuilder & addShuffleMask (ArrayRef< int > Val) const
const MachineInstrBuilder & addSym (MCSymbol *Sym, unsigned char TargetFlags=0) const
const MachineInstrBuilder & setMIFlags (unsigned Flags) const
const MachineInstrBuilder & setMIFlag (MachineInstr::MIFlag Flag) const
const MachineInstrBuilder & setOperandDead (unsigned OpIdx) const
const MachineInstrBuilder & addDisp (const MachineOperand &Disp, int64_t off, unsigned char TargetFlags=0) const
const MachineInstrBuilder & setPCSections (MDNode *MD) const
const MachineInstrBuilder & setMMRAMetadata (MDNode *MMRA) const
const MachineInstrBuilder & copyImplicitOps (const MachineInstr &OtherMI) const
Copy all the implicit operands from OtherMI onto this one.
bool constrainAllUses (const TargetInstrInfo &TII, const TargetRegisterInfo &TRI, const RegisterBankInfo &RBI) const
Detailed Description
Definition at line 72 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
MachineInstrBuilder() [1/3]
llvm::MachineInstrBuilder::MachineInstrBuilder () default
Referenced by add(), add(), addBlockAddress(), addCFIIndex(), addCImm(), addDef(), addDisp(), addExternalSymbol(), addFPImm(), addFrameIndex(), addGlobalAddress(), addImm(), addIntrinsicID(), addJumpTableIndex(), addMBB(), addMemOperand(), addMetadata(), addPredicate(), addReg(), addRegMask(), addShuffleMask(), addSym(), addTargetIndex(), addUse(), cloneMemRefs(), setMIFlag(), setMIFlags(), setMMRAMetadata(), setOperandDead(), and setPCSections().
MachineInstrBuilder() [2/3]
llvm::MachineInstrBuilder::MachineInstrBuilder (MachineFunction & F, MachineInstr * I) inline
Create a MachineInstrBuilder for manipulating an existing instruction.
F must be the machine function that was used to allocate I.
Definition at line 81 of file MachineInstrBuilder.h.
References F, and I.
MachineInstrBuilder() [3/3]
llvm::MachineInstrBuilder::MachineInstrBuilder (MachineFunction & F, MachineBasicBlock::iterator I) inline
Definition at line 82 of file MachineInstrBuilder.h.
References F, and I.
Member Function Documentation
add() [1/2]
const MachineInstrBuilder & llvm::MachineInstrBuilder::add (ArrayRef< MachineOperand > MOs) const inline
Definition at line 232 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and MachineInstrBuilder().
add() [2/2]
const MachineInstrBuilder & llvm::MachineInstrBuilder::add (const MachineOperand & MO) const inline
Definition at line 227 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and MachineInstrBuilder().
Referenced by llvm::InstrEmitter::AddDbgValueLocationOps(), llvm::addOffset(), addOperands(), AdjustBaseAndOffset(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::buildDbgValueForSpill(), llvm::buildDbgValueForSpill(), llvm::BuildMI(), buildMUBUFOffsetLoadStore(), llvm::ARMBaseInstrInfo::buildOutlinedFrame(), llvm::SIInstrInfo::buildShrunkInst(), CMSEPopCalleeSaves(), CMSEPushCalleeSaves(), CombineCVTAToLocal(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), copyOpWithoutRegFlags(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::Thumb2InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyToCPSR(), createCallWithOps(), createPostIncLoadStore(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitARMRegPlusImmediate(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitFill(), emitIndirectDst(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), llvm::emitT2RegPlusImmediate(), emitThumb2LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::AArch64TargetLowering::EmitTileLoad(), emitVFROUND_NOEXCEPT_MASK(), llvm::AArch64TargetLowering::EmitZAInstr(), llvm::AArch64TargetLowering::EmitZero(), llvm::AArch64TargetLowering::EmitZTInstr(), llvm::GIMatchTableExecutor::executeMatchTable(), expandFillPPRFromZPRSlotPseudo(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::M68kInstrInfo::ExpandPUSH_POP(), expandSpillPPRToZPRSlotPseudo(), llvm::HexagonInstrInfo::expandVGatherPseudo(), llvm::RISCVInstrInfo::finalizeInsInstrs(), llvm::ARMBaseInstrInfo::foldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), foldVGPRCopyIntoRegSequence(), forceReg(), fuseInst(), fuseTwoAddrInst(), genIndexedMultiply(), llvm::MipsInstrInfo::genInstrWithNewOpc(), genNeg(), genTPEntry(), genTPLoopBody(), getIndirectSGPRIdx(), handleNDDOrNFInstructions(), indirectCopyToAGPR(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::ARCInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), insertSEH(), llvm::SIInstrInfo::insertVectorSelect(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::AArch64CallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::RISCVCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), LowerCallResults(), LowerMemcpy(), LowerMemset(), llvm::ARMCallLowering::lowerReturn(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::moveToVALUImpl(), MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), llvm::LegalizerHelper::narrowScalar(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::RISCVInstrInfo::optimizeCondBranch(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::RISCVInstrInfo::optimizeSelect(), llvm::Thumb2InstrInfo::optimizeSelect(), popRegsFromStack(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), pushRegsToStack(), llvm::TargetInstrInfo::reassociateOps(), llvm::X86InstrInfo::reMaterialize(), llvm::RevertDoLoopStart(), llvm::RevertLoopDec(), llvm::RevertLoopEnd(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), selectMergeValues(), SelectMSA3OpIntrinsic(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), selectUnmergeValues(), llvm::FastISel::selectXRayCustomEvent(), llvm::FastISel::selectXRayTypedEvent(), llvm::ARMBaseInstrInfo::setExecutionDomain(), setM0ToIndexFromSGPR(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::tryFoldSPUpdateIntoPushPop(), and llvm::X86InstrInfo::unfoldMemoryOperand().
addBlockAddress()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addBlockAddress (const BlockAddress * BA, int64_t Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 193 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateBA(), MachineInstrBuilder(), and llvm::Offset.
Referenced by addDisp(), and llvm::MachineIRBuilder::buildBlockAddress().
addCFIIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addCFIIndex (unsigned CFIIndex) const inline
Definition at line 249 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateCFIIndex(), and MachineInstrBuilder().
Referenced by buildCFAOffs(), llvm::MSP430FrameLowering::BuildCFI(), llvm::X86FrameLowering::BuildCFI(), buildDefCFAReg(), EmitCfiOffset(), EmitDefCfaOffset(), EmitDefCfaRegister(), emitFrameOffsetAdj(), llvm::ARCFrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::XtensaFrameLowering::emitPrologue(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::CFIInstBuilder::insertCFIInst(), and insertRememberRestorePair().
addCImm()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addCImm (const ConstantInt * Val) const inline
Definition at line 139 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateCImm(), and MachineInstrBuilder().
Referenced by llvm::MachineIRBuilder::buildConstant(), and llvm::FastISel::lowerDbgValue().
addConstantPoolIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addConstantPoolIndex (unsigned Idx, int Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 161 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateCPI(), and llvm::Offset.
Referenced by llvm::addConstantPoolReference(), addDisp(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::XCoreInstrInfo::loadImmediate(), llvm::XtensaInstrInfo::loadImmediate(), and llvm::ARMBaseInstrInfo::reMaterialize().
addDef()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addDef (Register RegNo, unsigned Flags = 0, unsigned SubReg = 0) const inline
Add a virtual register definition operand.
Definition at line 119 of file MachineInstrBuilder.h.
References addReg(), llvm::RegState::Define, MachineInstrBuilder(), and SubReg.
Referenced by llvm::DstOp::addDefToMIB(), llvm::build2DBlockIOINTELInst(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicFlagInst(), llvm::buildAtomicFloatingRMWInst(), llvm::buildAtomicLoadInst(), llvm::buildAtomicRMWInst(), llvm::buildBindlessImageINTELInst(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildConstant(), llvm::SPIRVGlobalRegistry::buildConstantFP(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::buildEnqueueKernel(), llvm::buildExtendedBitOpsInst(), llvm::MachineIRBuilder::buildFConstant(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::buildNDRange(), buildOpBitcast(), llvm::buildTernaryBitwiseFunctionINTELInst(), convertPtrToInt(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::SPIRVGlobalRegistry::createConstFP(), llvm::SPIRVGlobalRegistry::createConstInt(), llvm::createContinuedInstructions(), doInsertBitcast(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), emitLoad(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::PPCFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), emitStore(), llvm::AArch64TargetLowering::EmitZero(), llvm::VEInstrInfo::expandGetStackTopPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), expandPseudoLogM(), llvm::generateAsyncCopy(), llvm::generateCastToPtrInst(), llvm::generateConvertInst(), llvm::generateCoopMatrInst(), llvm::generateDotOrFMulInst(), llvm::generateEnqueueInst(), llvm::generateExtInst(), llvm::generateGroupInst(), llvm::generateGroupUniformInst(), llvm::generateICarryBorrowInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::generateIntelSubgroupsInst(), llvm::generateKernelClockInst(), llvm::generateReadImageInst(), llvm::generateRelationalInst(), llvm::generateSampleImageInst(), llvm::generateSpecConstantInst(), llvm::generateVectorLoadStoreInst(), genTPLoopBody(), llvm::SPIRVGlobalRegistry::getOrAddMemAliasingINTELInst(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), getOrCreateFrameHelper(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampler(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::SPIRVGlobalRegistry::getOrCreateUnknownType(), llvm::insertAssignInstr(), insertInlineAsmProcess(), llvm::SPIRVTargetLowering::insertLogicalCopyOnResult(), llvm::SIInstrInfo::legalizeOperands(), llvm::AMDGPUCallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::PPCRegisterInfo::lowerDMRSpilling(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::PPCRegisterInfo::lowerWACCSpilling(), llvm::RegBankSelect::repairReg(), and llvm::RISCVFrameLowering::restoreCalleeSavedRegisters().
addDisp()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addDisp (const MachineOperand & Disp, int64_t off, unsigned char TargetFlags = 0) const inline
Definition at line 291 of file MachineInstrBuilder.h.
References addBlockAddress(), addConstantPoolIndex(), addGlobalAddress(), addImm(), addJumpTableIndex(), assert(), llvm::MachineOperand::getBlockAddress(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, MachineInstrBuilder(), llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, and llvm::MachineOperand::MO_JumpTableIndex.
Referenced by addOperands().
addExternalSymbol()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addExternalSymbol (const char * FnName, unsigned TargetFlags = 0) const inline
Definition at line 187 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateES(), and MachineInstrBuilder().
Referenced by addAsmInstr(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARCFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitGetSMESaveSize(), emitGPDisp(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::VETargetLowering::prepareSymbol(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::FastISel::selectCall(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), and llvm::WebAssemblyFrameLowering::writeSPToGlobal().
addFPImm()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addFPImm (const ConstantFP * Val) const inline
Definition at line 144 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateFPImm(), and MachineInstrBuilder().
Referenced by llvm::MachineIRBuilder::buildFConstant(), llvm::FastISel::fastEmitInst_f(), llvm::FastISel::lowerDbgValue(), and LowerFPToInt().
addFrameIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addFrameIndex (int Idx) const inline
Definition at line 155 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateFI(), and MachineInstrBuilder().
Referenced by llvm::InstrEmitter::AddDbgValueLocationOps(), addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::addFullAddress(), llvm::buildDbgValueForSpill(), llvm::buildDbgValueForSpill(), emitAlignedDPRCS2Restores(), emitBuildPairF64Pseudo(), llvm::AArch64TargetLowering::EmitInitTPIDR2Object(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), emitSplitF64Pseudo(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::BPFInstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::LanaiInstrInfo::loadRegFromStackSlot(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::RISCVRegisterInfo::materializeFrameBaseRegister(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::restoreCalleeSavedRegisters(), llvm::SIFrameLowering::spillCalleeSavedRegisters(), storeRegPairToStackSlot(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::BPFInstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::LanaiInstrInfo::storeRegToStackSlot(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
addGlobalAddress()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addGlobalAddress (const GlobalValue * GV, int64_t Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 180 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateGA(), MachineInstrBuilder(), and llvm::Offset.
Referenced by addDisp(), llvm::addFullAddress(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), llvm::SystemZELFFrameLowering::emitPrologue(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::MipsFunctionInfo::initGlobalBaseReg(), INITIALIZE_PASS(), INITIALIZE_PASS(), and llvm::ARMBaseInstrInfo::insertOutlinedCall().
addImm()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addImm (int64_t Val) const inline
Add a new immediate operand.
Definition at line 134 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateImm(), and MachineInstrBuilder().
Referenced by addAsmInstr(), llvm::addConstantPoolReference(), llvm::addDirectMem(), addDisp(), addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::addFullAddress(), llvm::SITargetLowering::AddMemOpInit(), addMemoryOperands(), addMemoryOperands(), llvm::addNumImm(), llvm::addOffset(), llvm::addOffset(), llvm::M68k::addOffset(), addOperandsForVFMK(), llvm::addPredicatedMveVpredNOp(), llvm::M68k::addRegIndirectWithDisp(), llvm::addRegReg(), llvm::SrcOp::addSrcToMIB(), llvm::addStringImm(), llvm::addUnpredicatedMveVpredNOp(), addZeroImm(), llvm::M68kInstrInfo::AddZExt(), AdjustBaseAndOffset(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::RISCVRegisterInfo::adjustReg(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::XtensaInstrInfo::adjustStackPtr(), llvm::RISCVFrameLowering::allocateStack(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::Mips16InstrInfo::BuildAddiuSpImm(), llvm::X86InstrInfo::buildClearRegister(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::buildDbgValueForSpill(), llvm::buildDbgValueForSpill(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::buildEnqueueKernel(), llvm::MachineIRBuilder::buildFence(), buildGitPtr(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::SPIRVGlobalRegistry::buildMemAliasingOpDecorate(), llvm::BuildMI(), llvm::BuildMI(), buildMUBUFOffsetLoadStore(), llvm::buildOpDecorate(), llvm::buildOpDecorate(), llvm::buildOpMemberDecorate(), llvm::buildOpMemberDecorate(), llvm::buildOpSpirvDecorations(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), buildRegSequence(), buildScratchExecCopy(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SITargetLowering::bundleInstWithWaitcnt(), llvm::PPCInstrInfo::commuteInstructionImpl(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::CSKYInstrInfo::copyPhysReg(), llvm::LanaiInstrInfo::copyPhysReg(), llvm::LoongArchInstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::VEInstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), copyPhysSubRegs(), llvm::ARMBaseInstrInfo::copyToCPSR(), createPostIncLoadStore(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::AArch64TargetLowering::EmitAllocateSMESaveBuffer(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBuildPairF64Pseudo(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::RISCVTargetLowering::emitDynamicProbedAlloc(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::SystemZTargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SystemZTargetLowering::emitEHSjLjSetJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::LanaiFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitFrameOffsetAdj(), emitFROUND(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), emitIncrement(), emitIndirectDst(), emitIndirectSrc(), llvm::AArch64TargetLowering::EmitInitTPIDR2Object(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64TargetLowering::EmitKCFICheck(), llvm::RISCVTargetLowering::EmitKCFICheck(), llvm::X86TargetLowering::EmitKCFICheck(), llvm::AArch64InstrInfo::emitLdStWithAddr(), llvm::RISCVInstrInfo::emitLdStWithAddr(), emitLoad(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitLoadM0FromVGPRLoop(), emitLoadScalarOpsFromVGPRLoop(), emitLpad(), emitPACSymOffsetIntoX16(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AVRFrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::XtensaFrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), llvm::VEFrameLowering::emitPrologueInsns(), emitPseudoCTPOP(), emitPseudoVMSKCOND(), emitPseudoXVINSGR2VR(), emitReadCounterWidePseudo(), emitRegUpdate(), emitSCSEpilogue(), emitSCSPrologue(), emitSelectPseudo(), emitSelectPseudo(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSiFiveCLICPreemptibleRestores(), emitSiFiveCLICPreemptibleSaves(), emitSiFiveCLICStackSwap(), llvm::VETargetLowering::emitSjLjDispatchBlock(), emitSplitF64Pseudo(), llvm::M68kFrameLowering::emitSPUpdate(), llvm::X86FrameLowering::emitSPUpdate(), llvm::X86FrameLowering::emitStackProbe(), emitStackProbeInline(), emitStore(), llvm::emitT2RegPlusImmediate(), emitThumb1LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), emitVecCondBranchPseudo(), emitXBegin(), llvm::SIInstrInfo::enforceOperandRCAlignment(), ensureEntrySetPrio(), llvm::VEInstrInfo::expandExtendStackPseudo(), expandFillPPRFromZPRSlotPseudo(), llvm::VEInstrInfo::expandGetStackTopPseudo(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::SIInstrInfo::expandMovDPP64(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::M68kInstrInfo::ExpandMOVI(), ExpandMOVImmSExti8(), expandNOVLXStore(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), expandSHXDROT(), expandSpillPPRToZPRSlotPseudo(), llvm::HexagonInstrInfo::expandVGatherPseudo(), extractRsrcPtr(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rri(), llvm::finishBuildOpDecorate(), llvm::ARMBaseInstrInfo::foldImmediate(), llvm::SystemZInstrInfo::foldImmediate(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), llvm::generateCastToPtrInst(), llvm::generateCoopMatrInst(), llvm::generateDotOrFMulInst(), generateEndPgm(), llvm::generateExtInst(), llvm::generateGroupInst(), llvm::generateImageSizeQueryInst(), llvm::generateReadImageInst(), llvm::generateSampleImageInst(), generateStackAdjustment(), llvm::generateVectorLoadStoreInst(), genFusedMultiply(), genIndexedMultiply(), llvm::MipsInstrInfo::genInstrWithNewOpc(), genTPEntry(), genTPLoopBody(), getIndirectSGPRIdx(), getOrCreateFrameHelper(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUnknownType(), llvm::SITargetLowering::getPrefLoopAlignment(), handleNDDOrNFInstructions(), IfNeededExtSP(), IfNeededLDAWSP(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::MSP430InstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranchAtInst(), llvm::XtensaInstrInfo::insertConstBranchAtInst(), insertDivByZeroTrap(), insertDivByZeroTrap(), llvm::SIInstrInfo::insertEQ(), InsertFPImmInst(), llvm::AArch64InstrInfo::insertIndirectBranch(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), insertInlineAsmProcess(), InsertLDR_STR(), llvm::insertMultibyteShift(), llvm::SIInstrInfo::insertNE(), llvm::AArch64InstrInfo::insertNoop(), llvm::SIInstrInfo::insertNoops(), insertNoopsInBundle(), llvm::MipsInstrInfo::insertNop(), insertNopBeforeInstruction(), llvm::SIInstrInfo::insertReturn(), llvm::SIInstrInfo::insertScratchExecCopy(), InsertSEH(), insertSEH(), llvm::AArch64InstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), llvm::SIInstrInfo::insertSimulatedTrap(), InsertSPConstInst(), InsertSPImmInst(), llvm::SIInstrInfo::insertVectorSelect(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVALUt16(), llvm::AMDGPULegalizerInfo::legalizeTrapEndpgm(), llvm::ARCInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::XCoreInstrInfo::loadImmediate(), llvm::XtensaInstrInfo::loadImmediate(), loadMBUFScalarOperandsFromVGPR(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::BPFInstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::LanaiInstrInfo::loadRegFromStackSlot(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::X86InstrInfo::loadStoreTileReg(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::RISCVCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), LowerCallResults(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::FastISel::lowerDbgValue(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::SPIRVCallLowering::lowerFormalArguments(), LowerFPToInt(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::X86CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerTailCall(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), lowerWaveReduce(), llvm::Mips16InstrInfo::makeFrame(), makeM0Inst(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::RISCVRegisterInfo::materializeFrameBaseRegister(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::SIInstrInfo::moveToVALUImpl(), llvm::CSKYInstrInfo::movImm(), llvm::LoongArchInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), llvm::RISCVInstrInfo::mulImm(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::RISCVInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::SGPRSpillBuilder::prepare(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::VETargetLowering::prepareMBB(), llvm::VETargetLowering::prepareSymbol(), llvm::AArch64InstrInfo::probedStackAlloc(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCInstrInfo::promoteInstr32To64ForElimEXTSW(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::ARMBaseInstrInfo::reMaterialize(), llvm::X86InstrInfo::reMaterialize(), llvm::X86InstrInfo::replaceBranchWithTailCall(), replaceFI(), replaceFrameIndex(), llvm::PPCInstrInfo::replaceInstrWithLI(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::M68kFrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::SIFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), llvm::SIRegisterInfo::restoreSGPR(), RestoreSpillList(), llvm::restoreStatusRegister(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::RevertLoopDec(), llvm::RevertLoopEnd(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::FastISel::selectCall(), selectCopy(), llvm::FastISel::selectStackmap(), llvm::ARMBaseInstrInfo::setExecutionDomain(), setM0ToIndexFromSGPR(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::M68kFrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), llvm::SIFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillEmergencySGPR(), llvm::SIRegisterInfo::spillSGPR(), storeRegPairToStackSlot(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::BPFInstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::LanaiInstrInfo::storeRegToStackSlot(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
addIntrinsicID()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addIntrinsicID (Intrinsic::ID ID) const inline
Definition at line 254 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateIntrinsicID(), and MachineInstrBuilder().
addJumpTableIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addJumpTableIndex (unsigned Idx, unsigned TargetFlags = 0) const inline
Definition at line 174 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateJTI(), and MachineInstrBuilder().
Referenced by addDisp(), llvm::MachineIRBuilder::buildBrJT(), and llvm::VETargetLowering::emitSjLjDispatchBlock().
addMBB()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addMBB (MachineBasicBlock * MBB, unsigned TargetFlags = 0) const inline
Definition at line 149 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateMBB(), MachineInstrBuilder(), and MBB.
Referenced by addIncomingValuesToPHIs(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::AVRInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::AnalyzeBranchImpl(), llvm::MachineIRBuilder::buildBr(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::RISCVTargetLowering::emitDynamicProbedAlloc(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SystemZTargetLowering::emitEHSjLjSetJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitFROUND(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::XtensaTargetLowering::EmitInstrWithCustomInserter(), emitLoadM0FromVGPRLoop(), emitLoadScalarOpsFromVGPRLoop(), EmitLoweredCascadedSelect(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), emitReadCounterWidePseudo(), emitSelectPseudo(), emitSelectPseudo(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::VETargetLowering::emitSjLjDispatchBlock(), emitStackProbeInline(), emitVecCondBranchPseudo(), emitXBegin(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::SparcTargetLowering::expandSelectCC(), genTPEntry(), genTPLoopBody(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), INITIALIZE_PASS(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), llvm::AArch64InstrInfo::insertBranch(), llvm::ARCInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::AVRInstrInfo::insertBranch(), llvm::BPFInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::M68kInstrInfo::insertBranch(), llvm::MipsInstrInfo::insertBranch(), llvm::MSP430InstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::SPIRVInstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::XCoreInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranchAtInst(), insertDivByZeroTrap(), llvm::AArch64InstrInfo::insertIndirectBranch(), llvm::AVRInstrInfo::insertIndirectBranch(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), insertPHI(), llvm::SIInstrInfo::insertSimulatedTrap(), llvm::AMDGPULegalizerInfo::legalizeTrapEndpgm(), LowerFPToInt(), LowerMemcpy(), LowerMemset(), lowerWaveReduce(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::RISCVInstrInfo::optimizeCondBranch(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::VETargetLowering::prepareMBB(), llvm::AArch64InstrInfo::probedStackAlloc(), llvm::RevertWhileLoopStartLR(), splitEdge(), and splitMBB().
addMemOperand()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addMemOperand (MachineMemOperand * MMO) const inline
Definition at line 205 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addMemOperand(), and MachineInstrBuilder().
Referenced by addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::M68k::addMemOperand(), emitBuildPairF64Pseudo(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), emitSplitF64Pseudo(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::SystemZELFFrameLowering::inlineStackProbe(), InsertFPConstInst(), InsertFPImmInst(), InsertSPConstInst(), InsertSPImmInst(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), replaceFrameIndex(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::SIFrameLowering::restoreCalleeSavedRegisters(), RestoreSpillList(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::SIFrameLowering::spillCalleeSavedRegisters(), storeRegPairToStackSlot(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), and llvm::AArch64GISelUtils::tryEmitBZero().
addMetadata()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addMetadata (const MDNode * MD) const inline
Definition at line 238 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), assert(), llvm::MachineOperand::CreateMetadata(), and MachineInstrBuilder().
Referenced by llvm::buildDbgValueForSpill(), llvm::buildDbgValueForSpill(), llvm::BuildMI(), llvm::BuildMI(), llvm::InstrEmitter::EmitDbgLabel(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::InstrEmitter::EmitDbgValueList(), llvm::FastISel::handleDbgInfo(), llvm::FastISel::lowerDbgValue(), and llvm::FastISel::selectCall().
addPredicate()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addPredicate (CmpInst::Predicate Pred) const inline
Definition at line 259 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreatePredicate(), and MachineInstrBuilder().
Referenced by llvm::SrcOp::addSrcToMIB().
addReg()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addReg (Register RegNo, unsigned flags = 0, unsigned SubReg = 0) const inline
Add a new virtual register operand.
Definition at line 100 of file MachineInstrBuilder.h.
References assert(), llvm::MachineOperand::CreateReg(), llvm::RegState::Dead, llvm::RegState::Debug, llvm::RegState::Define, llvm::RegState::EarlyClobber, llvm::RegState::Implicit, llvm::RegState::InternalRead, llvm::RegState::Kill, MachineInstrBuilder(), llvm::RegState::Renamable, SubReg, and llvm::RegState::Undef.
Referenced by llvm::addConstantPoolReference(), llvm::InstrEmitter::AddDbgValueLocationOps(), addDef(), llvm::addDirectMem(), llvm::ARMBaseInstrInfo::AddDReg(), addExclusiveRegPair(), llvm::addFrameReference(), llvm::addFullAddress(), addIncomingValuesToPHIs(), llvm::MachineBasicBlock::addLiveIn(), llvm::SITargetLowering::AddMemOpInit(), llvm::addOffset(), llvm::addOffset(), addOperandsForVFMK(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::addPredicatedMveVpredNOp(), llvm::addPredicatedMveVpredROp(), llvm::M68k::addRegIndirectWithDisp(), llvm::addRegOffset(), llvm::addRegReg(), addSavedGPR(), addSaveRestoreRegs(), llvm::M68kInstrInfo::AddSExt(), AddSubReg(), llvm::addUnpredicatedMveVpredNOp(), llvm::addUnpredicatedMveVpredROp(), addUse(), llvm::M68kInstrInfo::AddZExt(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::RISCVRegisterInfo::adjustReg(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::XtensaInstrInfo::adjustStackPtr(), llvm::RISCVFrameLowering::allocateStack(), attachMEMCPYScratchRegs(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::X86InstrInfo::buildClearRegister(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildExtractSubReg(), buildGitPtr(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), buildRegSequence(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::X86InstrInfo::classifyLEAReg(), CMSEPopCalleeSaves(), CMSEPushCalleeSaves(), CombineCVTAToLocal(), combineFPFusedMultiply(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::constrainOperandRegClass(), llvm::FastISel::constrainOperandRegClass(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::AArch64InstrInfo::copyGPRRegTuple(), copyOpWithoutRegFlags(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARCInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::AVRInstrInfo::copyPhysReg(), llvm::BPFInstrInfo::copyPhysReg(), llvm::CSKYInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::LanaiInstrInfo::copyPhysReg(), llvm::LoongArchInstrInfo::copyPhysReg(), llvm::M68kInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MSP430InstrInfo::copyPhysReg(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::R600InstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::Thumb2InstrInfo::copyPhysReg(), llvm::VEInstrInfo::copyPhysReg(), llvm::WebAssemblyInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::XtensaInstrInfo::copyPhysReg(), copyPhysSubRegs(), llvm::ARMBaseInstrInfo::copyToCPSR(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::SIInstrInfo::createPHIDestinationCopy(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::SIInstrInfo::createPHISourceCopy(), createPostIncLoadStore(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::XtensaRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::AArch64TargetLowering::EmitAllocateSMESaveBuffer(), llvm::AArch64TargetLowering::EmitAllocateZABuffer(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBuildPairF64Pseudo(), emitBuildPairF64Pseudo(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::RISCVTargetLowering::emitDynamicProbedAlloc(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::SystemZTargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SystemZTargetLowering::emitEHSjLjSetJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::LanaiFrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::XtensaFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64TargetLowering::EmitFill(), emitFrameOffsetAdj(), emitFROUND(), llvm::AArch64TargetLowering::EmitGetSMESaveSize(), emitGPDisp(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), emitIncrement(), emitIndirectDst(), emitIndirectSrc(), llvm::AArch64TargetLowering::EmitInitTPIDR2Object(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::XtensaTargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64TargetLowering::EmitKCFICheck(), llvm::RISCVTargetLowering::EmitKCFICheck(), llvm::X86TargetLowering::EmitKCFICheck(), llvm::AArch64InstrInfo::emitLdStWithAddr(), llvm::RISCVInstrInfo::emitLdStWithAddr(), llvm::MachineRegisterInfo::EmitLiveInCopies(), emitLoad(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitLoadM0FromVGPRLoop(), emitLoadScalarOpsFromVGPRLoop(), EmitLoweredCascadedSelect(), emitPACSymOffsetIntoX16(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AVRFrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::XtensaFrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), llvm::VEFrameLowering::emitPrologueInsns(), emitPseudoCTPOP(), emitPseudoVMSKCOND(), emitPseudoXVINSGR2VR(), emitQuietFCMP(), emitReadCounterWidePseudo(), emitRegUpdate(), emitSCSEpilogue(), emitSCSPrologue(), emitSelectPseudo(), emitSelectPseudo(), emitSelectPseudo(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSiFiveCLICPreemptibleRestores(), emitSiFiveCLICPreemptibleSaves(), emitSiFiveCLICStackSwap(), llvm::VETargetLowering::emitSjLjDispatchBlock(), emitSplitPairF64Pseudo(), llvm::M68kFrameLowering::emitSPUpdate(), llvm::X86FrameLowering::emitSPUpdate(), emitStackProbeInline(), emitStore(), llvm::emitT2RegPlusImmediate(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::AArch64TargetLowering::EmitTileLoad(), emitVecCondBranchPseudo(), emitVFROUND_NOEXCEPT_MASK(), emitXBegin(), llvm::AArch64TargetLowering::EmitZAInstr(), llvm::AArch64TargetLowering::EmitZTInstr(), llvm::SIInstrInfo::enforceOperandRCAlignment(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), Expand2AddrKreg(), Expand2AddrUndef(), Expand2AddrUndef(), llvm::VEInstrInfo::expandExtendStackPseudo(), expandFillPPRFromZPRSlotPseudo(), llvm::VEInstrInfo::expandGetStackTopPseudo(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), expandMOV32r1(), llvm::SIInstrInfo::expandMovDPP64(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::M68kInstrInfo::ExpandMOVI(), llvm::M68kInstrInfo::ExpandMOVSZX_RR(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::M68kInstrInfo::ExpandPUSH_POP(), llvm::SparcTargetLowering::expandSelectCC(), expandSGPRCopy(), expandSHXDROT(), expandSpillPPRToZPRSlotPseudo(), llvm::HexagonInstrInfo::expandVGatherPseudo(), expandXorFP(), extractRsrcPtr(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::FastISel::fastEmitInst_f(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrr(), llvm::finalizeBundle(), llvm::ARMBaseInstrInfo::foldImmediate(), llvm::SystemZInstrInfo::foldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldVGPRCopyIntoRegSequence(), forceReg(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), genAlternativeDpCodeSequence(), generateEndPgm(), generateStackAdjustment(), genFNegatedMAD(), genFusedMultiply(), genIndexedMultiply(), genMaddR(), genShXAddAddShift(), genSubAdd2SubSub(), genTPEntry(), genTPLoopBody(), llvm::SIInstrInfo::getAddNoCarry(), llvm::SIInstrInfo::getAddNoCarry(), llvm::getFunctionLiveInPhysReg(), llvm::CSKYInstrInfo::getGlobalBaseReg(), getLegalRegBank(), getOrCreateFrameHelper(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), handleNDDOrNFInstructions(), indirectCopyToAGPR(), llvm::MipsFunctionInfo::initGlobalBaseReg(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), llvm::HexagonInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::XCoreInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranchAtInst(), llvm::XtensaInstrInfo::insertConstBranchAtInst(), llvm::AArch64TargetLowering::insertCopiesSplitCSR(), llvm::SITargetLowering::insertCopiesSplitCSR(), insertCopy(), insertDivByZeroTrap(), insertDivByZeroTrap(), llvm::SIInstrInfo::insertEQ(), InsertFPConstInst(), InsertFPImmInst(), llvm::AArch64InstrInfo::insertIndirectBranch(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::XtensaInstrInfo::insertIndirectBranch(), InsertLDR_STR(), llvm::insertMultibyteShift(), llvm::SIInstrInfo::insertNE(), llvm::MipsInstrInfo::insertNop(), insertPHI(), llvm::SIInstrInfo::insertScratchExecCopy(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), InsertSPConstInst(), InsertSPImmInst(), llvm::SIInstrInfo::insertVectorSelect(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsVALUt16(), llvm::Mips16InstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::XtensaInstrInfo::loadImmediate(), loadM0FromVGPR(), loadMBUFScalarOperandsFromVGPR(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::X86InstrInfo::loadStoreTileReg(), llvm::PPCRegisterInfo::lowerACCRestore(), llvm::PPCRegisterInfo::lowerACCSpilling(), LowerCallResults(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDMRRestore(), llvm::PPCRegisterInfo::lowerDMRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), LowerFPToInt(), LowerMemcpy(), LowerMemset(), llvm::PPCRegisterInfo::lowerPrepareProbedAlloca(), llvm::PPCRegisterInfo::lowerQuadwordSpilling(), llvm::X86CallLowering::lowerReturn(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::PPCRegisterInfo::lowerWACCRestore(), llvm::PPCRegisterInfo::lowerWACCSpilling(), lowerWaveReduce(), llvm::Mips16InstrInfo::makeFrame(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::PPCInstrInfo::materializeImmPostRA(), maybeRewriteToFallthrough(), moveAndTeeForMultiUse(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::SIInstrInfo::moveToVALUImpl(), llvm::CSKYInstrInfo::movImm(), llvm::LoongArchInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), llvm::RISCVInstrInfo::mulImm(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::RISCVInstrInfo::optimizeCondBranch(), popRegsFromStack(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::SGPRSpillBuilder::prepare(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::VETargetLowering::prepareMBB(), llvm::VETargetLowering::prepareSymbol(), llvm::AArch64InstrInfo::probedStackAlloc(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCInstrInfo::promoteInstr32To64ForElimEXTSW(), llvm::SwiftErrorValueTracking::propagateVRegs(), pushRegsToStack(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::SGPRSpillBuilder::readWriteTmpVGPR(), llvm::TargetInstrInfo::reassociateOps(), llvm::TargetInstrInfo::reduceAccumulatorTree(), llvm::X86InstrInfo::replaceBranchWithTailCall(), replaceFI(), replaceFrameIndex(), llvm::PPCInstrInfo::replaceInstrWithLI(), reportIllegalCopy(), llvm::SIRegisterInfo::resolveFrameIndex(), llvm::SGPRSpillBuilder::restore(), llvm::TargetFrameLowering::restoreCalleeSavedRegister(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::SIFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::SIInstrInfo::restoreExec(), llvm::Mips16InstrInfo::restoreFrame(), llvm::SIRegisterInfo::restoreSGPR(), llvm::restoreStatusRegister(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::RevertLoopDec(), llvm::RevertLoopEnd(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::MachineSSAUpdater::RewriteUse(), llvm::FastISel::selectFreeze(), setCallTargetReg(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::VETargetLowering::setupEntryBlockForSjLj(), llvm::TargetFrameLowering::spillCalleeSavedRegister(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::SIFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillEmergencySGPR(), llvm::SIRegisterInfo::spillSGPR(), spillVGPRtoAGPR(), splitMBB(), storeRegPairToStackSlot(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::BPFInstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::LanaiInstrInfo::storeRegToStackSlot(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::M68kInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::XtensaInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::unfoldMemoryOperand(), unstackifyVRegsUsedInSplitBB(), UpdatePredRedefs(), and llvm::WebAssemblyFrameLowering::writeSPToGlobal().
addRegMask()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addRegMask (const uint32_t * Mask) const inline
Definition at line 200 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateRegMask(), and MachineInstrBuilder().
Referenced by llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SystemZTargetLowering::emitEHSjLjSetJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitGetSMESaveSize(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::M68kCallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::SystemZInstrInfo::PredicateInstruction(), and llvm::AArch64FrameLowering::spillCalleeSavedRegisters().
addShuffleMask()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addShuffleMask (ArrayRef< int > Val) const inline
Definition at line 264 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateShuffleMask(), and MachineInstrBuilder().
addSym()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addSym (MCSymbol * Sym, unsigned char TargetFlags = 0) const inline
Definition at line 269 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateMCSymbol(), and MachineInstrBuilder().
Referenced by emitPACSymOffsetIntoX16(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::AArch64InstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), and LowerCallResults().
addTargetIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addTargetIndex (unsigned Idx, int64_t Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 167 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateTargetIndex(), MachineInstrBuilder(), and llvm::Offset.
addUse()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addUse (Register RegNo, unsigned Flags = 0, unsigned SubReg = 0) const inline
Add a virtual register use operand.
It is an error for Flags to contain RegState::Define when calling this function.
Definition at line 126 of file MachineInstrBuilder.h.
References addReg(), assert(), llvm::RegState::Define, MachineInstrBuilder(), and SubReg.
Referenced by llvm::SIRegisterInfo::addImplicitUsesForBlockCSRLoad(), addMemoryOperands(), llvm::SrcOp::addSrcToMIB(), llvm::build2DBlockIOINTELInst(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicFlagInst(), llvm::buildAtomicFloatingRMWInst(), llvm::buildAtomicInitInst(), llvm::buildAtomicLoadInst(), llvm::buildAtomicRMWInst(), llvm::buildAtomicStoreInst(), llvm::buildBarrierInst(), llvm::buildBindlessImageINTELInst(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), llvm::SPIRVGlobalRegistry::buildConstantFP(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::buildEnqueueKernel(), llvm::buildExtendedBitOpsInst(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::SPIRVGlobalRegistry::buildMemAliasingOpDecorate(), llvm::buildNDRange(), buildOpBitcast(), llvm::buildOpDecorate(), llvm::buildOpDecorate(), llvm::buildOpMemberDecorate(), llvm::buildOpMemberDecorate(), llvm::buildOpName(), llvm::buildOpName(), llvm::buildOpSpirvDecorations(), llvm::buildTernaryBitwiseFunctionINTELInst(), convertPtrToInt(), llvm::SPIRVGlobalRegistry::createConstFP(), llvm::SPIRVGlobalRegistry::createConstInt(), llvm::createContinuedInstructions(), doInsertBitcast(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::HexagonInstrInfo::expandPostRAPseudo(), expandPseudoLogM(), llvm::RISCVInstrInfo::finalizeInsInstrs(), llvm::generateAsyncCopy(), llvm::generateCastToPtrInst(), llvm::generateConvertInst(), llvm::generateCoopMatrInst(), llvm::generateDotOrFMulInst(), llvm::generateEnqueueInst(), llvm::generateExtInst(), llvm::generateGroupInst(), llvm::generateGroupUniformInst(), llvm::generateICarryBorrowInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::generateIntelSubgroupsInst(), llvm::generateKernelClockInst(), llvm::generateLoadStoreInst(), llvm::generateReadImageInst(), llvm::generateRelationalInst(), llvm::generateSampleImageInst(), llvm::generateSpecConstantInst(), llvm::generateVectorLoadStoreInst(), llvm::generateWriteImageInst(), genTPEntry(), genTPLoopBody(), llvm::genWorkgroupQuery(), llvm::SPIRVGlobalRegistry::getOrAddMemAliasingINTELInst(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), getOrCreateFrameHelper(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::SPIRVGlobalRegistry::getOrCreateUnknownType(), llvm::insertAssignInstr(), insertInlineAsmProcess(), llvm::SPIRVTargetLowering::insertLogicalCopyOnResult(), llvm::SIInstrInfo::insertSimulatedTrap(), llvm::MipsCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::SPIRVCallLowering::lowerReturn(), llvm::LegalizerHelper::narrowScalar(), llvm::RegBankSelect::repairReg(), selectCopy(), and llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
cloneMemRefs()
const MachineInstrBuilder & llvm::MachineInstrBuilder::cloneMemRefs (const MachineInstr & OtherMI) const inline
Definition at line 216 of file MachineInstrBuilder.h.
References llvm::MachineInstr::cloneMemRefs(), and MachineInstrBuilder().
Referenced by AdjustBaseAndOffset(), buildMUBUFOffsetLoadStore(), createPostIncLoadStore(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::MipsInstrInfo::genInstrWithNewOpc(), InsertLDR_STR(), llvm::SIInstrInfo::legalizeOperands(), and llvm::ARMBaseInstrInfo::reMaterialize().
cloneMergedMemRefs()
const MachineInstrBuilder & llvm::MachineInstrBuilder::cloneMergedMemRefs (ArrayRef< const MachineInstr * > OtherMIs) const inline
Definition at line 222 of file MachineInstrBuilder.h.
References llvm::MachineInstr::cloneMergedMemRefs().
constrainAllUses()
bool llvm::MachineInstrBuilder::constrainAllUses (const TargetInstrInfo & TII, const TargetRegisterInfo & TRI, const RegisterBankInfo & RBI) const inline
Definition at line 339 of file MachineInstrBuilder.h.
References llvm::constrainSelectedInstRegOperands(), TII, and TRI.
Referenced by doInsertBitcast(), llvm::SPIRVTargetLowering::insertLogicalCopyOnResult(), llvm::MipsCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerReturn(), and SelectMSA3OpIntrinsic().
copyImplicitOps()
const MachineInstrBuilder & llvm::MachineInstrBuilder::copyImplicitOps (const MachineInstr & OtherMI) const inline
Copy all the implicit operands from OtherMI onto this one.
Definition at line 334 of file MachineInstrBuilder.h.
References llvm::MachineInstr::copyImplicitOps().
Referenced by llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::LanaiInstrInfo::optimizeSelect(), popRegsFromStack(), llvm::TargetInstrInfo::reassociateOps(), and llvm::X86InstrInfo::replaceBranchWithTailCall().
getInstr()
MachineInstr * llvm::MachineInstrBuilder::getInstr () const inline
If conversion operators fail, use this method to get the MachineInstr explicitly.
Definition at line 92 of file MachineInstrBuilder.h.
Referenced by llvm::addNumImm(), buildMUBUFOffsetLoadStore(), llvm::SparcInstrInfo::copyPhysReg(), llvm::VEInstrInfo::copyPhysReg(), copyPhysSubRegs(), createCallWithOps(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::AArch64TargetLowering::EmitKCFICheck(), llvm::RISCVTargetLowering::EmitKCFICheck(), llvm::X86TargetLowering::EmitKCFICheck(), expandFillPPRFromZPRSlotPseudo(), expandLoadStackGuard(), expandMOV32r1(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::M68kInstrInfo::ExpandMOVI(), ExpandMOVImmSExti8(), llvm::M68kInstrInfo::ExpandMOVSZX_RM(), llvm::M68kInstrInfo::ExpandMOVSZX_RR(), llvm::M68kInstrInfo::ExpandMOVX_RR(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::M68kInstrInfo::ExpandPUSH_POP(), expandSpillPPRToZPRSlotPseudo(), llvm::SPIRVGlobalRegistry::getOrAddMemAliasingINTELInst(), llvm::ARCInstrInfo::loadImmediate(), llvm::XCoreInstrInfo::loadImmediate(), LowerCallResults(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::ARMBlockPlacement::moveBasicBlock(), and llvm::TargetInstrInfo::reassociateOps().
getReg()
Register llvm::MachineInstrBuilder::getReg (unsigned Idx) const inline
Get the register for the operand index.
The operand at the index should be a register (asserted by MachineOperand).
Definition at line 97 of file MachineInstrBuilder.h.
Referenced by buildAnyextOrCopy(), llvm::CSEMIRBuilder::buildInstr(), buildLogBase2(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), createAtomicLibcall(), llvm::SIRegisterInfo::eliminateFrameIndex(), Expand2AddrUndef(), expandLoadStackGuard(), expandMOV32r1(), ExpandMOVImmSExti8(), expandNOVLXLoad(), expandNOVLXStore(), llvm::X86InstrInfo::expandPostRAPseudo(), expandSHXDROT(), llvm::extractParts(), llvm::extractVectorParts(), getMemsetValue(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::CallLowering::handleAssignments(), llvm::CallLowering::insertSRetOutgoingArgument(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeLaneOp(), llvm::AMDGPULegalizerInfo::legalizePointerAsRsrcIntrin(), llvm::AArch64CallLowering::lowerCall(), llvm::CallLowering::lowerCall(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerReturn(), llvm::LegalizerHelper::lowerVECTOR_COMPRESS(), llvm::AMDGPUCallLowering::passSpecialInputs(), selectMergeValues(), and selectUnmergeValues().
operator MachineBasicBlock::iterator()
llvm::MachineInstrBuilder::operator MachineBasicBlock::iterator () const inline
Definition at line 88 of file MachineInstrBuilder.h.
operator MachineInstr *()
llvm::MachineInstrBuilder::operator MachineInstr * () const inline
Allow automatic conversion to the machine instruction we are working on.
Definition at line 86 of file MachineInstrBuilder.h.
operator->()
MachineInstr * llvm::MachineInstrBuilder::operator-> () const inline
Definition at line 87 of file MachineInstrBuilder.h.
setMemRefs()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setMemRefs (ArrayRef< MachineMemOperand * > MMOs) const inline
Definition at line 211 of file MachineInstrBuilder.h.
References llvm::MachineInstr::setMemRefs().
Referenced by convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::AArch64InstrInfo::emitLdStWithAddr(), llvm::RISCVInstrInfo::emitLdStWithAddr(), expandFillPPRFromZPRSlotPseudo(), expandSpillPPRToZPRSlotPseudo(), INITIALIZE_PASS(), and llvm::X86InstrInfo::unfoldMemoryOperand().
setMIFlag()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setMIFlag (MachineInstr::MIFlag Flag) const inline
Definition at line 280 of file MachineInstrBuilder.h.
References MachineInstrBuilder(), and llvm::MachineInstr::setFlag().
Referenced by llvm::RISCVRegisterInfo::adjustReg(), llvm::MSP430FrameLowering::BuildCFI(), llvm::X86FrameLowering::BuildCFI(), BuildPACM(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), emitFrameOffsetAdj(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), emitLoad(), llvm::AArch64FrameLowering::emitPacRetPlusLeafHardening(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AVRFrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XtensaFrameLowering::emitPrologue(), emitSCSEpilogue(), emitSCSPrologue(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), emitSiFiveCLICPreemptibleRestores(), emitSiFiveCLICPreemptibleSaves(), emitSiFiveCLICStackSwap(), llvm::X86FrameLowering::emitSPUpdate(), emitStore(), llvm::finalizeBundle(), getOrCreateFrameHelper(), llvm::CFIInstBuilder::insertCFIInst(), InsertSEH(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadRegFromStackSlot(), llvm::AMDGPUCallLowering::lowerCall(), llvm::LoongArchInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), llvm::RISCVInstrInfo::mulImm(), popRegsFromStack(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::M68kFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), signOutlinedFunction(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::M68kFrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::RISCVInstrInfo::storeRegToStackSlot(), and llvm::X86InstrInfo::storeRegToStackSlot().
setMIFlags()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setMIFlags (unsigned Flags) const inline
Definition at line 275 of file MachineInstrBuilder.h.
References MachineInstrBuilder(), and llvm::MachineInstr::setFlags().
Referenced by llvm::RISCVFrameLowering::allocateStack(), llvm::SIInstrInfo::buildShrunkInst(), combineFPFusedMultiply(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::emitARMRegPlusImmediate(), llvm::AArch64FrameLowering::emitEpilogue(), emitFrameOffsetAdj(), llvm::AArch64InstrInfo::emitLdStWithAddr(), llvm::RISCVInstrInfo::emitLdStWithAddr(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), emitStackProbeInline(), llvm::emitT2RegPlusImmediate(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), genSubAdd2SubSub(), llvm::insertAssignInstr(), insertSEH(), llvm::SIInstrInfo::moveToVALUImpl(), llvm::CSKYInstrInfo::movImm(), llvm::AArch64InstrInfo::probedStackAlloc(), pushRegsToStack(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
setMMRAMetadata()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setMMRAMetadata (MDNode * MMRA) const inline
Definition at line 326 of file MachineInstrBuilder.h.
References MachineInstrBuilder(), and llvm::MachineInstr::setMMRAMetadata().
Referenced by llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), and llvm::BuildMI().
setOperandDead()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setOperandDead (unsigned OpIdx) const inline
Definition at line 285 of file MachineInstrBuilder.h.
References llvm::MachineInstr::getOperand(), MachineInstrBuilder(), OpIdx, and llvm::MachineOperand::setIsDead().
Referenced by llvm::SIRegisterInfo::eliminateFrameIndex(), and llvm::SIRegisterInfo::materializeFrameBaseRegister().
setPCSections()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setPCSections (MDNode * MD) const inline
Definition at line 320 of file MachineInstrBuilder.h.
References MachineInstrBuilder(), and llvm::MachineInstr::setPCSections().
Referenced by llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), and llvm::TargetInstrInfo::reassociateOps().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineInstrBuilder.h