LLVM: llvm::MSP430InstrInfo Class Reference
llvm::MSP430InstrInfo Class Reference
#include "Target/MSP430/MSP430InstrInfo.h"
Public Member Functions
MSP430InstrInfo (MSP430Subtarget &STI)
const MSP430RegisterInfo & getRegisterInfo () const
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, Register DestReg, Register SrcReg, bool KillSrc, bool RenamableDest=false, bool RenamableSrc=false) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg, MachineInstr::MIFlag Flags=MachineInstr::NoFlags) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIdx, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg, MachineInstr::MIFlag Flags=MachineInstr::NoFlags) const override
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
int64_t getFramePoppedByCallee (const MachineInstr &I) const
Detailed Description
Definition at line 26 of file MSP430InstrInfo.h.
Constructor & Destructor Documentation
MSP430InstrInfo()
MSP430InstrInfo::MSP430InstrInfo (MSP430Subtarget & STI) explicit
Definition at line 27 of file MSP430InstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool MSP430InstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 159 of file MSP430InstrInfo.cpp.
References assert(), Cond, MSP430CC::COND_INVALID, llvm::MachineOperand::CreateImm(), llvm::getImm(), I, MBB, and TBB.
copyPhysReg()
void MSP430InstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, Register DestReg, Register SrcReg, bool KillSrc, bool RenamableDest = false, bool RenamableSrc = false) const override
Definition at line 84 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), DL, llvm::get(), llvm::getKillRegState(), I, llvm_unreachable, MBB, and Opc.
getFramePoppedByCallee()
int64_t llvm::MSP430InstrInfo::getFramePoppedByCallee (const MachineInstr & I) const inline
Definition at line 71 of file MSP430InstrInfo.h.
References assert(), and I.
getInstSizeInBytes()
unsigned MSP430InstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
GetInstSize - Return the number of bytes of code the specified instruction may be.
This returns the maximum number of bytes.
Definition at line 283 of file MSP430InstrInfo.cpp.
References llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), MI, and TII.
getRegisterInfo()
const MSP430RegisterInfo & llvm::MSP430InstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 36 of file MSP430InstrInfo.h.
Referenced by llvm::MSP430Subtarget::getRegisterInfo().
insertBranch()
unsigned MSP430InstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 248 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), Cond, llvm::Count, DL, llvm::get(), llvm::getImm(), MBB, and TBB.
loadRegFromStackSlot()
void MSP430InstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIdx, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg, MachineInstr::MIFlag Flags = MachineInstr::NoFlags) const override
Definition at line 58 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::get(), llvm::getDefRegState(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm_unreachable, MBB, MI, llvm::MachineMemOperand::MOLoad, and TRI.
removeBranch()
unsigned MSP430InstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 101 of file MSP430InstrInfo.cpp.
References assert(), llvm::Count, I, and MBB.
reverseBranchCondition()
bool MSP430InstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 127 of file MSP430InstrInfo.cpp.
References assert(), Cond, MSP430CC::COND_E, MSP430CC::COND_GE, MSP430CC::COND_HS, MSP430CC::COND_L, MSP430CC::COND_LO, MSP430CC::COND_NE, and llvm_unreachable.
storeRegToStackSlot()
void MSP430InstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg, MachineInstr::MIFlag Flags = MachineInstr::NoFlags) const override
Definition at line 31 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm_unreachable, MBB, MI, llvm::MachineMemOperand::MOStore, and TRI.
The documentation for this class was generated from the following files:
lib/Target/MSP430/MSP430InstrInfo.h
lib/Target/MSP430/MSP430InstrInfo.cpp