LLVM: llvm::AArch64TargetStreamer Class Reference
llvm::AArch64TargetStreamer Class Reference
#include "Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h"
Public Member Functions
AArch64TargetStreamer (MCStreamer &S)
~AArch64TargetStreamer () override
void finish () override
void emitConstantPools () override
const MCExpr * addConstantPoolEntry (const MCExpr *, unsigned Size, SMLoc Loc)
Callback used to implement the ldr= pseudo.
void emitCurrentConstantPool ()
Callback used to implement the .ltorg directive.
void emitNoteSection (unsigned Flags, uint64_t PAuthABIPlatform=-1, uint64_t PAuthABIVersion=-1)
Callback used to implement the .note.gnu.property section.
void emitAuthValue (const MCExpr *Expr, uint16_t Discriminator, AArch64PACKey::ID Key, bool HasAddressDiversity)
Callback used to emit AUTH expressions (e.g.
virtual void emitInst (uint32_t Inst)
Callback used to implement the .inst directive.
virtual void emitDirectiveVariantPCS (MCSymbol *Symbol)
Callback used to implement the .variant_pcs directive.
virtual void emitDirectiveArch (StringRef Name)
virtual void emitDirectiveArchExtension (StringRef Name)
virtual void emitARM64WinCFIAllocStack (unsigned Size)
virtual void emitARM64WinCFISaveR19R20X (int Offset)
virtual void emitARM64WinCFISaveFPLR (int Offset)
virtual void emitARM64WinCFISaveFPLRX (int Offset)
virtual void emitARM64WinCFISaveReg (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveRegX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveRegP (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveRegPX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveLRPair (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFReg (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFRegX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFRegP (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFRegPX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISetFP ()
virtual void emitARM64WinCFIAddFP (unsigned Size)
virtual void emitARM64WinCFINop ()
virtual void emitARM64WinCFISaveNext ()
virtual void emitARM64WinCFIPrologEnd ()
virtual void emitARM64WinCFIEpilogStart ()
virtual void emitARM64WinCFIEpilogEnd ()
virtual void emitARM64WinCFITrapFrame ()
virtual void emitARM64WinCFIMachineFrame ()
virtual void emitARM64WinCFIContext ()
virtual void emitARM64WinCFIECContext ()
virtual void emitARM64WinCFIClearUnwoundToCall ()
virtual void emitARM64WinCFIPACSignLR ()
virtual void emitARM64WinCFISaveAnyRegI (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegIP (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegD (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegDP (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegQ (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegQP (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegIX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegIPX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegDX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegDPX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegQX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveAnyRegQPX (unsigned Reg, int Offset)
virtual void emitARM64WinCFIAllocZ (int Offset)
virtual void emitARM64WinCFISaveZReg (unsigned Reg, int Offset)
virtual void emitARM64WinCFISavePReg (unsigned Reg, int Offset)
virtual void emitAttributesSubsection (StringRef VendorName, AArch64BuildAttributes::SubsectionOptional IsOptional, AArch64BuildAttributes::SubsectionType ParameterType)
Build attributes implementation.
virtual void emitAttribute (StringRef VendorName, unsigned Tag, unsigned Value, std::string String)
void activateAttributesSubsection (StringRef VendorName)
std::unique_ptr< MCELFStreamer::AttributeSubSection > getActiveAttributesSubsection ()
std::unique_ptr< MCELFStreamer::AttributeSubSection > getAttributesSubsectionByName (StringRef Name)
void insertAttributeInPlace (const MCELFStreamer::AttributeItem &Attr, MCELFStreamer::AttributeSubSection &AttSubSection)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
Public Attributes
SmallVector< MCELFStreamer::AttributeSubSection, 64 > AttributeSubSections
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 26 of file AArch64TargetStreamer.h.
Constructor & Destructor Documentation
AArch64TargetStreamer()
AArch64TargetStreamer::AArch64TargetStreamer (MCStreamer & S)
Definition at line 34 of file AArch64TargetStreamer.cpp.
References llvm::MCTargetStreamer::MCTargetStreamer().
Referenced by llvm::AArch64TargetELFStreamer::AArch64TargetELFStreamer(), and llvm::AArch64TargetWinCOFFStreamer::AArch64TargetWinCOFFStreamer().
~AArch64TargetStreamer()
AArch64TargetStreamer::~AArch64TargetStreamer () override default
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and Size.
Member Function Documentation
activateAttributesSubsection()
void AArch64TargetStreamer::activateAttributesSubsection (StringRef VendorName)
Definition at line 241 of file AArch64TargetStreamer.cpp.
References AttributeSubSections.
Referenced by emitAttributesSubsection().
addConstantPoolEntry()
const MCExpr * AArch64TargetStreamer::addConstantPoolEntry (const MCExpr * Expr, unsigned Size, SMLoc Loc)
Callback used to implement the ldr= pseudo.
Add a new entry to the constant pool for the current section and return an MCExpr that can be used to refer to the constant pool location.
Definition at line 51 of file AArch64TargetStreamer.cpp.
References Size, and llvm::MCTargetStreamer::Streamer.
emitARM64WinCFIAddFP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIAddFP (unsigned Size) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 75 of file AArch64TargetStreamer.h.
References Size.
emitARM64WinCFIAllocStack()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIAllocStack (unsigned Size) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 61 of file AArch64TargetStreamer.h.
References Size.
emitARM64WinCFIAllocZ()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIAllocZ (int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 99 of file AArch64TargetStreamer.h.
References llvm::Offset.
emitARM64WinCFIClearUnwoundToCall()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIClearUnwoundToCall () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 85 of file AArch64TargetStreamer.h.
emitARM64WinCFIContext()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIContext () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 83 of file AArch64TargetStreamer.h.
emitARM64WinCFIECContext()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIECContext () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 84 of file AArch64TargetStreamer.h.
emitARM64WinCFIEpilogEnd()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIEpilogEnd () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 80 of file AArch64TargetStreamer.h.
emitARM64WinCFIEpilogStart()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIEpilogStart () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 79 of file AArch64TargetStreamer.h.
emitARM64WinCFIMachineFrame()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIMachineFrame () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 82 of file AArch64TargetStreamer.h.
emitARM64WinCFINop()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFINop () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 76 of file AArch64TargetStreamer.h.
emitARM64WinCFIPACSignLR()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIPACSignLR () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 86 of file AArch64TargetStreamer.h.
emitARM64WinCFIPrologEnd()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIPrologEnd () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 78 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveAnyRegD()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegD (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 89 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegDP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegDP (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 90 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegDPX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegDPX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 96 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegDX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegDX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 95 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegI()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegI (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 87 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegIP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegIP (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 88 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegIPX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegIPX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 94 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegIX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegIX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 93 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegQ()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegQ (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 91 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegQP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegQP (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 92 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegQPX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegQPX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 98 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveAnyRegQX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveAnyRegQX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 97 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveFPLR()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFPLR (int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 63 of file AArch64TargetStreamer.h.
References llvm::Offset.
emitARM64WinCFISaveFPLRX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFPLRX (int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 64 of file AArch64TargetStreamer.h.
References llvm::Offset.
emitARM64WinCFISaveFReg()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFReg (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 70 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveFRegP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFRegP (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 72 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveFRegPX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFRegPX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 73 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveFRegX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFRegX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 71 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveLRPair()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveLRPair (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 69 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveNext()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveNext () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 77 of file AArch64TargetStreamer.h.
emitARM64WinCFISavePReg()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISavePReg (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 101 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveR19R20X()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveR19R20X (int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 62 of file AArch64TargetStreamer.h.
References llvm::Offset.
emitARM64WinCFISaveReg()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveReg (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 65 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveRegP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveRegP (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 67 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveRegPX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveRegPX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 68 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveRegX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveRegX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 66 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISaveZReg()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveZReg (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 100 of file AArch64TargetStreamer.h.
References llvm::Offset, and Reg.
emitARM64WinCFISetFP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISetFP () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 74 of file AArch64TargetStreamer.h.
emitARM64WinCFITrapFrame()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFITrapFrame () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 81 of file AArch64TargetStreamer.h.
emitAttribute()
void AArch64TargetStreamer::emitAttribute (StringRef VendorName, unsigned Tag, unsigned Value, std::string String) virtual
Definition at line 196 of file AArch64TargetStreamer.cpp.
References assert(), AttributeSubSections, llvm::MCELFStreamer::AttributeItem::IntValue, llvm::MCELFStreamer::AttributeItem::NumericAttribute, llvm::String, llvm::MCELFStreamer::AttributeItem::StringValue, llvm::Tag, llvm::MCELFStreamer::AttributeItem::Tag, llvm::MCELFStreamer::AttributeItem::TextAttribute, and llvm::MCELFStreamer::AttributeItem::Type.
emitAttributesSubsection()
void AArch64TargetStreamer::emitAttributesSubsection (StringRef VendorName, AArch64BuildAttributes::SubsectionOptional IsOptional, AArch64BuildAttributes::SubsectionType ParameterType) virtual
Build attributes implementation.
Definition at line 156 of file AArch64TargetStreamer.cpp.
References activateAttributesSubsection(), AttributeSubSections, llvm::MCELFStreamer::AttributeSubSection::IsOptional, llvm::MCELFStreamer::AttributeSubSection::ParameterType, and llvm::MCELFStreamer::AttributeSubSection::VendorName.
emitAuthValue()
void AArch64TargetStreamer::emitAuthValue (const MCExpr * Expr, uint16_t Discriminator, AArch64PACKey::ID Key, bool HasAddressDiversity)
Callback used to emit AUTH expressions (e.g.
signed personality function pointer).
Definition at line 39 of file AArch64TargetStreamer.cpp.
References llvm::AArch64AuthMCExpr::create(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::MCTargetStreamer::Streamer.
emitConstantPools()
void AArch64TargetStreamer::emitConstantPools () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 61 of file AArch64TargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
emitCurrentConstantPool()
void AArch64TargetStreamer::emitCurrentConstantPool ()
Callback used to implement the .ltorg directive.
Emit contents of constant pool for the current section.
Definition at line 57 of file AArch64TargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
emitDirectiveArch()
virtual void llvm::AArch64TargetStreamer::emitDirectiveArch (StringRef Name) inline virtual
Definition at line 58 of file AArch64TargetStreamer.h.
emitDirectiveArchExtension()
virtual void llvm::AArch64TargetStreamer::emitDirectiveArchExtension (StringRef Name) inline virtual
Definition at line 59 of file AArch64TargetStreamer.h.
emitDirectiveVariantPCS()
virtual void llvm::AArch64TargetStreamer::emitDirectiveVariantPCS (MCSymbol * Symbol) inline virtual
Callback used to implement the .variant_pcs directive.
Definition at line 56 of file AArch64TargetStreamer.h.
emitInst()
void AArch64TargetStreamer::emitInst (uint32_t Inst) virtual
Callback used to implement the .inst directive.
Definition at line 127 of file AArch64TargetStreamer.cpp.
References llvm::CallingConv::C, llvm::MCStreamer::emitBytes(), and llvm::MCTargetStreamer::getStreamer().
emitNoteSection()
void AArch64TargetStreamer::emitNoteSection (unsigned Flags, uint64_t PAuthABIPlatform = -1, uint64_t PAuthABIVersion = -1)
Callback used to implement the .note.gnu.property section.
Definition at line 72 of file AArch64TargetStreamer.cpp.
References assert(), llvm::MCStreamer::emitBytes(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::MCStreamer::endSection(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCTargetStreamer::getStreamer(), llvm::ELF::GNU_PROPERTY_AARCH64_FEATURE_1_AND, llvm::ELF::GNU_PROPERTY_AARCH64_FEATURE_PAUTH, llvm::MCSection::isRegistered(), llvm::ELF::NT_GNU_PROPERTY_TYPE_0, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOTE, and llvm::MCStreamer::switchSection().
Referenced by finish().
finish()
void AArch64TargetStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 67 of file AArch64TargetStreamer.cpp.
References emitNoteSection(), llvm::ELF::GNU_PROPERTY_AARCH64_FEATURE_1_BTI, and MarkBTIProperty.
getActiveAttributesSubsection()
std::unique_ptr< MCELFStreamer::AttributeSubSection > AArch64TargetStreamer::getActiveAttributesSubsection ()
Definition at line 177 of file AArch64TargetStreamer.cpp.
References AttributeSubSections.
getAttributesSubsectionByName()
std::unique_ptr< MCELFStreamer::AttributeSubSection > AArch64TargetStreamer::getAttributesSubsectionByName (StringRef Name)
Definition at line 187 of file AArch64TargetStreamer.cpp.
References AttributeSubSections.
insertAttributeInPlace()
void llvm::AArch64TargetStreamer::insertAttributeInPlace (const MCELFStreamer::AttributeItem & Attr, MCELFStreamer::AttributeSubSection & AttSubSection)
Member Data Documentation
AttributeSubSections
SmallVector<MCELFStreamer::AttributeSubSection, 64> llvm::AArch64TargetStreamer::AttributeSubSections
Definition at line 119 of file AArch64TargetStreamer.h.
Referenced by activateAttributesSubsection(), emitAttribute(), emitAttributesSubsection(), getActiveAttributesSubsection(), and getAttributesSubsectionByName().
The documentation for this class was generated from the following files:
lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h
lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.cpp