LLVM: llvm::sandboxir::EraseFromParent Class Reference
llvm::sandboxir::EraseFromParent Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
EraseFromParent (std::unique_ptr< sandboxir::Value > &&IPtr)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Friends
raw_ostream & operator<< (raw_ostream &OS, const EraseFromParent &C)
Detailed Description
Definition at line 215 of file Tracker.h.
Constructor & Destructor Documentation
EraseFromParent()
EraseFromParent::EraseFromParent (std::unique_ptr< sandboxir::Value > && IPtr)
Definition at line 143 of file Tracker.cpp.
References assert(), llvm::cast(), llvm::enumerate(), llvm::sandboxir::Use::get(), I, llvm::is_sorted(), llvm::move(), Operands, and llvm::reverse().
Referenced by operator<<.
Member Function Documentation
accept()
void EraseFromParent::accept () final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 167 of file Tracker.cpp.
dump() [1/2]
void EraseFromParent::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 195 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::EraseFromParent::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 238 of file Tracker.h.
revert()
void EraseFromParent::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 172 of file Tracker.cpp.
References llvm::cast(), llvm::drop_begin(), llvm::dyn_cast(), llvm::enumerate(), Operands, and llvm::sandboxir::IRChangeBase::Tracker.
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const EraseFromParent & C) friend
Definition at line 240 of file Tracker.h.
References llvm::CallingConv::C, const, and EraseFromParent().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp