LLVM: llvm::coverage::RawCoverageMappingDummyChecker Class Reference
llvm::coverage::RawCoverageMappingDummyChecker Class Reference
Checks if the given coverage mapping data is exported for an unused function.
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
Public Member Functions
RawCoverageMappingDummyChecker (StringRef MappingData)
LLVM_ABI Expected< bool > isDummy ()
Additional Inherited Members
Protected Member Functions inherited from llvm::coverage::RawCoverageReader
RawCoverageReader (StringRef Data)
LLVM_ABI Error readULEB128 (uint64_t &Result)
LLVM_ABI Error readIntMax (uint64_t &Result, uint64_t MaxPlus1)
LLVM_ABI Error readSize (uint64_t &Result)
LLVM_ABI Error readString (StringRef &Result)
Protected Attributes inherited from llvm::coverage::RawCoverageReader
StringRef Data
Detailed Description
Checks if the given coverage mapping data is exported for an unused function.
Definition at line 124 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
RawCoverageMappingDummyChecker()
llvm::coverage::RawCoverageMappingDummyChecker::RawCoverageMappingDummyChecker (StringRef MappingData) inline
Definition at line 126 of file CoverageMappingReader.h.
References llvm::coverage::RawCoverageReader::RawCoverageReader().
Member Function Documentation
isDummy()
Expected< bool > RawCoverageMappingDummyChecker::isDummy ()
Definition at line 465 of file CoverageMappingReader.cpp.
References llvm::coverage::Counter::EncodingTagMask, llvm::coverage::RawCoverageReader::readIntMax(), llvm::coverage::RawCoverageReader::readSize(), llvm::Tag, and llvm::coverage::Counter::Zero.
Referenced by isCoverageMappingDummy().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingReader.h
lib/ProfileData/Coverage/CoverageMappingReader.cpp