LLVM: llvm::AArch64SelectionDAGInfo Class Reference
llvm::AArch64SelectionDAGInfo Class Reference
#include "Target/AArch64/AArch64SelectionDAGInfo.h"
Public Member Functions
AArch64SelectionDAGInfo ()
void verifyTargetNode (const SelectionDAG &DAG, const SDNode *N) const override
Checks that the given target-specific node is valid. Aborts if it is not.
SDValue EmitMOPS (unsigned Opcode, SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dst, SDValue SrcOrValue, SDValue Size, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override
Emit target-specific code that performs a memcpy.
SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const override
Emit target-specific code that performs a memset.
SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override
Emit target-specific code that performs a memmove.
SDValue EmitTargetCodeForSetTag (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo DstPtrInfo, bool ZeroData) const override
SDValue EmitStreamingCompatibleMemLibCall (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, RTLIB::Libcall LC) const
Public Member Functions inherited from llvm::SelectionDAGGenTargetInfo
~SelectionDAGGenTargetInfo () override
const char * getTargetNodeName (unsigned Opcode) const override
Returns the name of the given target-specific opcode, suitable for debug printing.
bool isTargetMemoryOpcode (unsigned Opcode) const override
Returns true if a node with the given target-specific opcode has a memory operand.
bool isTargetStrictFPOpcode (unsigned Opcode) const override
Returns true if a node with the given target-specific opcode has strict floating-point semantics.
void verifyTargetNode (const SelectionDAG &DAG, const SDNode *N) const override
Checks that the given target-specific node is valid. Aborts if it is not.
Public Member Functions inherited from llvm::SelectionDAGTargetInfo
SelectionDAGTargetInfo ()=default
SelectionDAGTargetInfo (const SelectionDAGTargetInfo &)=delete
SelectionDAGTargetInfo & operator= (const SelectionDAGTargetInfo &)=delete
virtual ~SelectionDAGTargetInfo ()
virtual bool mayRaiseFPException (unsigned Opcode) const
Returns true if a node with the given target-specific opcode may raise a floating-point exception.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a memcmp/bcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
virtual bool disableGenericCombines (CodeGenOptLevel OptLevel) const
Additional Inherited Members
Protected Member Functions inherited from llvm::SelectionDAGGenTargetInfo
SelectionDAGGenTargetInfo (const SDNodeInfo &GenNodeInfo)
Protected Attributes inherited from llvm::SelectionDAGGenTargetInfo
const SDNodeInfo & GenNodeInfo
Detailed Description
Definition at line 25 of file AArch64SelectionDAGInfo.h.
Constructor & Destructor Documentation
AArch64SelectionDAGInfo()
AArch64SelectionDAGInfo::AArch64SelectionDAGInfo ()
Definition at line 30 of file AArch64SelectionDAGInfo.cpp.
References llvm::SelectionDAGGenTargetInfo::SelectionDAGGenTargetInfo().
Member Function Documentation
EmitMOPS()
SDValue AArch64SelectionDAGInfo::EmitMOPS (unsigned Opcode, SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Dst, SDValue SrcOrValue, SDValue Size, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Definition at line 114 of file AArch64SelectionDAGInfo.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::ANY_EXTEND, llvm::CallingConv::C, DL, llvm::dyn_cast(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOStore, llvm::MachineMemOperand::MOVolatile, SDValue(), llvm::SelectionDAG::setNodeMemRefs(), and Size.
Referenced by EmitTargetCodeForMemcpy(), EmitTargetCodeForMemmove(), and EmitTargetCodeForMemset().
EmitStreamingCompatibleMemLibCall()
SDValue AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, RTLIB::Libcall LC) const
Definition at line 160 of file AArch64SelectionDAGInfo.cpp.
References DL, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getExternalSymbol(), llvm::Type::getInt32Ty(), llvm::DataLayout::getIntPtrType(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getSubtarget(), llvm::AArch64Subtarget::getTargetLowering(), llvm::PointerType::getUnqual(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::TargetLoweringBase::ArgListEntry::Node, SDValue(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), Size, and llvm::TargetLoweringBase::ArgListEntry::Ty.
Referenced by EmitTargetCodeForMemcpy(), EmitTargetCodeForMemmove(), and EmitTargetCodeForMemset().
EmitTargetCodeForMemcpy()
SDValue AArch64SelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override virtual
Emit target-specific code that performs a memcpy.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 217 of file AArch64SelectionDAGInfo.cpp.
References DL, EmitMOPS(), EmitStreamingCompatibleMemLibCall(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getSubtarget(), LowerToSMERoutines, SDValue(), and Size.
EmitTargetCodeForMemmove()
SDValue AArch64SelectionDAGInfo::EmitTargetCodeForMemmove (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override virtual
Emit target-specific code that performs a memmove.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 256 of file AArch64SelectionDAGInfo.cpp.
References EmitMOPS(), EmitStreamingCompatibleMemLibCall(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getSubtarget(), LowerToSMERoutines, SDValue(), and Size.
EmitTargetCodeForMemset()
SDValue AArch64SelectionDAGInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const override virtual
Emit target-specific code that performs a memset.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used. Note that if AlwaysInline is true the function has to return a valid SDValue.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 236 of file AArch64SelectionDAGInfo.cpp.
References EmitMOPS(), EmitStreamingCompatibleMemLibCall(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getSubtarget(), LowerToSMERoutines, SDValue(), and Size.
EmitTargetCodeForSetTag()
SDValue AArch64SelectionDAGInfo::EmitTargetCodeForSetTag (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo DstPtrInfo, bool ZeroData) const override virtual
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 329 of file AArch64SelectionDAGInfo.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::cast(), EmitUnrolledSetTag(), llvm::ISD::FrameIndex, llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), kSetTagLoopThreshold, llvm::MachineMemOperand::MOStore, SDValue(), llvm::SelectionDAG::setNodeMemRefs(), and Size.
verifyTargetNode()
void AArch64SelectionDAGInfo::verifyTargetNode (const SelectionDAG & DAG, const SDNode * N) const override virtual
Checks that the given target-specific node is valid. Aborts if it is not.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 33 of file AArch64SelectionDAGInfo.cpp.
References assert(), llvm::EVT::getSizeInBits(), llvm::EVT::getVectorElementCount(), llvm::isa(), llvm::EVT::isInteger(), llvm::EVT::isVector(), N, and llvm::SelectionDAGGenTargetInfo::verifyTargetNode().
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64SelectionDAGInfo.h
lib/Target/AArch64/AArch64SelectionDAGInfo.cpp