LLVM: llvm::orc::ForceLoadMachOArchiveMembers Class Reference
llvm::orc::ForceLoadMachOArchiveMembers Class Reference
For use with StaticLibraryDefinitionGenerators.
#include "llvm/ExecutionEngine/Orc/MachO.h"
Public Member Functions
ForceLoadMachOArchiveMembers (ObjectLayer &L, JITDylib &JD, bool ObjCOnly)
LLVM_ABI Expected< bool > operator() (object::Archive &A, MemoryBufferRef MemberBuf, size_t Index)
Detailed Description
For use with StaticLibraryDefinitionGenerators.
Definition at line 82 of file MachO.h.
Constructor & Destructor Documentation
ForceLoadMachOArchiveMembers()
llvm::orc::ForceLoadMachOArchiveMembers::ForceLoadMachOArchiveMembers (ObjectLayer & L, JITDylib & JD, bool ObjCOnly) inline
Definition at line 84 of file MachO.h.
Member Function Documentation
operator()()
Expected< bool > llvm::orc::ForceLoadMachOArchiveMembers::operator() (object::Archive & A, MemoryBufferRef MemberBuf, size_t Index)
Definition at line 233 of file MachO.cpp.
References A(), llvm::consumeError(), llvm::orc::StaticLibraryDefinitionGenerator::createMemberBuffer(), llvm::object::ObjectFile::createObjectFile(), and llvm::dyn_cast().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/MachO.h
lib/ExecutionEngine/Orc/MachO.cpp