LLVM: llvm::CSKYAsmBackend Class Reference
llvm::CSKYAsmBackend Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYAsmBackend.h"
Public Member Functions
CSKYAsmBackend (const MCSubtargetInfo &STI, const MCTargetOptions &OP)
std::optional< bool > evaluateFixup (const MCFragment &, MCFixup &, MCValue &, uint64_t &) override
void applyFixup (const MCFragment &, const MCFixup &, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved) override
Determine if a relocation is required.
MCFixupKindInfo getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value) const override
Simple predicate for targets where !Resolved implies requiring relaxation.
bool mayNeedRelaxation (unsigned Opcode, ArrayRef< MCOperand > Operands, const MCSubtargetInfo &STI) const override
Check whether the given instruction (encoded as Opcode+Operands) may need relaxation.
void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const override
Relax the instruction in the given fragment to the next wider instruction.
bool fixupNeedsRelaxationAdvanced (const MCFixup &, const MCValue &, uint64_t, bool) const override
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
bool shouldForceRelocation (const MCFixup &Fixup, const MCValue &Target)
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
void setAssembler (MCAssembler *A)
MCContext & getContext () const
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool finishLayout (const MCAssembler &Asm) const
virtual uint64_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
virtual std::optional< MCFixupKind > getFixupKind (StringRef Name) const
Map a relocation name used in .reloc to a fixup kind.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
void maybeAddReloc (const MCFragment &, const MCFixup &, const MCValue &, uint64_t &Value, bool IsResolved)
virtual bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, bool &WasRelaxed) const
virtual std::pair< bool, bool > relaxLEB128 (MCLEBFragment &LF, int64_t &Value) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::MCAsmBackend
static const MCSubtargetInfo * getSubtargetInfo (const MCFragment &F)
Public Attributes inherited from llvm::MCAsmBackend
const llvm::endianness Endian
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (llvm::endianness Endian)
Protected Attributes inherited from llvm::MCAsmBackend
MCAssembler * Asm = nullptr
Detailed Description
Definition at line 19 of file CSKYAsmBackend.h.
Constructor & Destructor Documentation
CSKYAsmBackend()
llvm::CSKYAsmBackend::CSKYAsmBackend (const MCSubtargetInfo & STI, const MCTargetOptions & OP) inline
Definition at line 22 of file CSKYAsmBackend.h.
References llvm::little, llvm::MCAsmBackend::MCAsmBackend(), and OP.
Member Function Documentation
applyFixup()
void CSKYAsmBackend::applyFixup (const MCFragment & , const MCFixup & , const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved) override virtual
Determine if a relocation is required.
In addition, Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate. Errors (such as an out of range fixup value) should be reported via Ctx.
Implements llvm::MCAsmBackend.
Definition at line 198 of file CSKYAsmBackend.cpp.
References adjustFixupValue(), llvm::alignTo(), assert(), llvm::Data, llvm::MCAsmBackend::Endian, F, llvm::FirstTargetFixupKind, Fixup, llvm::MCAsmBackend::getContext(), getFixupKindInfo(), I, llvm::mc::isRelocation(), llvm::little, llvm::MCAsmBackend::maybeAddReloc(), llvm::Offset, and shouldForceRelocation().
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > CSKYAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 23 of file CSKYAsmBackend.cpp.
References llvm::createCSKYELFObjectWriter().
evaluateFixup()
std::optional< bool > CSKYAsmBackend::evaluateFixup (const MCFragment & F, MCFixup & Fixup, MCValue & , uint64_t & Value) override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 183 of file CSKYAsmBackend.cpp.
References llvm::MCAsmBackend::Asm, F, Fixup, llvm::CSKY::fixup_csky_pcrel_uimm16_scale4, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, and llvm::CSKY::fixup_csky_pcrel_uimm8_scale4.
fixupNeedsRelaxation()
bool CSKYAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value) const override virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Reimplemented from llvm::MCAsmBackend.
Definition at line 279 of file CSKYAsmBackend.cpp.
References Fixup.
fixupNeedsRelaxationAdvanced()
bool CSKYAsmBackend::fixupNeedsRelaxationAdvanced (const MCFixup & Fixup, const MCValue & , uint64_t Value, bool Resolved) const override virtual
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Reimplemented from llvm::MCAsmBackend.
Definition at line 160 of file CSKYAsmBackend.cpp.
References Fixup, llvm::CSKY::fixup_csky_pcrel_imm10_scale2, llvm::CSKY::fixup_csky_pcrel_imm16_scale2, llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, llvm::isShiftedInt(), and llvm::Offset.
getFixupKindInfo()
MCFixupKindInfo CSKYAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 27 of file CSKYAsmBackend.cpp.
References assert(), llvm::FirstTargetFixupKind, llvm::CSKY::fixup_csky_addr32, llvm::CSKY::fixup_csky_addr_hi16, llvm::CSKY::fixup_csky_addr_lo16, llvm::CSKY::fixup_csky_doffset_imm18, llvm::CSKY::fixup_csky_doffset_imm18_scale2, llvm::CSKY::fixup_csky_doffset_imm18_scale4, llvm::CSKY::fixup_csky_got32, llvm::CSKY::fixup_csky_got_imm18_scale4, llvm::CSKY::fixup_csky_gotoff, llvm::CSKY::fixup_csky_gotpc, llvm::CSKY::fixup_csky_pcrel_imm10_scale2, llvm::CSKY::fixup_csky_pcrel_imm16_scale2, llvm::CSKY::fixup_csky_pcrel_imm18_scale2, llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::CSKY::fixup_csky_pcrel_uimm16_scale4, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, llvm::CSKY::fixup_csky_pcrel_uimm8_scale4, llvm::CSKY::fixup_csky_plt32, llvm::CSKY::fixup_csky_plt_imm18_scale4, llvm::MCAsmBackend::getFixupKindInfo(), llvm::mc::isRelocation(), llvm::CSKY::NumTargetFixupKinds, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by applyFixup().
mayNeedRelaxation()
bool CSKYAsmBackend::mayNeedRelaxation (unsigned Opcode, ArrayRef< MCOperand > Operands, const MCSubtargetInfo & STI) const override virtual
Check whether the given instruction (encoded as Opcode+Operands) may need relaxation.
Reimplemented from llvm::MCAsmBackend.
Definition at line 242 of file CSKYAsmBackend.cpp.
References llvm::MCSubtargetInfo::hasFeature().
relaxInstruction()
void CSKYAsmBackend::relaxInstruction (MCInst & Inst, const MCSubtargetInfo & STI) const override virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
[out] Inst The instruction to relax, which is also the relaxed instruction.
STI the subtarget information for the associated instruction.
Reimplemented from llvm::MCAsmBackend.
Definition at line 284 of file CSKYAsmBackend.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::dump(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCSubtargetInfo::hasFeature(), LLVM_DEBUG, llvm_unreachable, and llvm::MCInst::setOpcode().
shouldForceRelocation()
bool CSKYAsmBackend::shouldForceRelocation (const MCFixup & Fixup, const MCValue & Target)
Definition at line 263 of file CSKYAsmBackend.cpp.
References Fixup, llvm::CSKY::fixup_csky_doffset_imm18, llvm::CSKY::fixup_csky_doffset_imm18_scale2, and llvm::CSKY::fixup_csky_doffset_imm18_scale4.
Referenced by applyFixup().
writeNopData()
bool CSKYAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 339 of file CSKYAsmBackend.cpp.
References llvm::Count, and llvm::raw_ostream::write_zeros().
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYAsmBackend.h
lib/Target/CSKY/MCTargetDesc/CSKYAsmBackend.cpp