LLVM: llvm::Expected< T > Class Template Reference
llvm::Expected< T > Class Template Reference
Tagged union holding either a T or a Error.
#include "llvm/Support/Error.h"
Public Types
using storage_type = std::conditional_t<isRef, wrap, T>
using value_type = T
Public Member Functions
Expected (Error &&Err)
Create an Expected<T> error value from the given Error.
Expected (ErrorSuccess)=delete
Forbid to convert from Error::success() implicitly, this avoids having Expected<T> foo() { return Error::success(); } which compiles otherwise but triggers the assertion above.
template<typename OtherT>
Expected (OtherT &&Val, std::enable_if_t< std::is_convertible_v< OtherT, T > > *=nullptr)
Create an Expected<T> success value from the given OtherT value, which must be convertible to T.
Expected (Expected &&Other)
Move construct an Expected<T> value.
template<class OtherT>
Expected (Expected< OtherT > &&Other, std::enable_if_t< std::is_convertible_v< OtherT, T > > *=nullptr)
Move construct an Expected<T> value from an Expected<OtherT>, where OtherT must be convertible to T.
template<class OtherT>
Expected (Expected< OtherT > &&Other, std::enable_if_t<!std::is_convertible_v< OtherT, T > > *=nullptr)
Move construct an Expected<T> value from an Expected<OtherT>, where OtherT isn't convertible to T.
Expected & operator= (Expected &&Other)
Move-assign from another Expected<T>.
~Expected ()
Destroy an Expected<T>.
operator bool ()
Return false if there is an error.
reference get ()
Returns a reference to the stored T value.
const_reference get () const
Returns a const reference to the stored T value.
template<class OtherT>
Error moveInto (OtherT &Value, std::enable_if_t< std::is_assignable_v< OtherT &, T && > > *=nullptr) &&
Returns takeError() after moving the held T (if any) into V.
template<typename ErrT>
bool errorIsA () const
Check that this Expected<T> is an error of type ErrT.
Error takeError ()
Take ownership of the stored error.
pointer operator-> ()
Returns a pointer to the stored T value.
const_pointer operator-> () const
Returns a const pointer to the stored T value.
reference operator* ()
Returns a reference to the stored T value.
const_reference operator* () const
Returns a const reference to the stored T value.
Friends
template<class T1>
class ExpectedAsOutParameter
template<class OtherT>
class Expected
Detailed Description
template<class T>
class llvm::Expected< T >
Tagged union holding either a T or a Error.
This class parallels ErrorOr, but replaces error_code with Error. Since Error cannot be copied, this class replaces getError() with takeError(). It also adds an bool errorIsA<ErrT>() method for testing the error class type.
Example usage of 'Expected<T>' as a function return type:
Expected<int> myDivide(int A, int B) {
  if (B == 0) {
    // return an Error
    return createStringError(inconvertibleErrorCode(),
                             "B must not be zero!");
  }
  // return an integer
  return A / B;
}
Checking the results of to a function returning 'Expected<T>':
if (auto E = Result.takeError()) {
  // We must consume the error. Typically one of:
  // - return the error to our caller
  // - toString(), when logging
  // - consumeError(), to silently swallow the error
  // - handleErrors(), to distinguish error types
  errs() << "Problem with division " << toString(std::move(E)) << "\n";
  return;
}
// use the result
outs() << "The answer is " << *Result << "\n";
For unit-testing a function returning an 'Expected<T>', see the 'EXPECT_THAT_EXPECTED' macros in llvm/Testing/Support/Error.h
Definition at line 485 of file Error.h.
Member Typedef Documentation
storage_type
template<class T> using llvm::Expected< T >::storage_type = std::conditional_t<isRef, wrap, T>
Definition at line 496 of file Error.h.
value_type
template<class T> using llvm::Expected< T >::value_type = T
Definition at line 497 of file Error.h.
Constructor & Destructor Documentation
Expected() [1/6]
template<class T> llvm::Expected< T >::Expected (Error && Err) inline
Create an Expected<T> error value from the given Error.
Definition at line 507 of file Error.h.
Expected() [2/6]
template<class T> llvm::Expected< T >::Expected (ErrorSuccess) delete
Forbid to convert from Error::success() implicitly, this avoids having Expected<T> foo() { return Error::success(); } which compiles otherwise but triggers the assertion above.
Expected() [3/6]
template<class T> template<typename OtherT> llvm::Expected< T >::Expected (OtherT && Val, std::enable_if_t< std::is_convertible_v< OtherT, T > > * = nullptr) inline
Create an Expected<T> success value from the given OtherT value, which must be convertible to T.
Definition at line 526 of file Error.h.
Expected() [4/6]
template<class T> llvm::Expected< T >::Expected (Expected< T > && Other) inline
Move construct an Expected<T> value.
Definition at line 539 of file Error.h.
Expected() [5/6]
template<class T> template<class OtherT> llvm::Expected< T >::Expected (Expected< OtherT > && Other, std::enable_if_t< std::is_convertible_v< OtherT, T > > * = nullptr) inline
Move construct an Expected<T> value from an Expected<OtherT>, where OtherT must be convertible to T.
Definition at line 544 of file Error.h.
Expected() [6/6]
template<class T> template<class OtherT> llvm::Expected< T >::Expected (Expected< OtherT > && Other, std::enable_if_t<!std::is_convertible_v< OtherT, T > > * = nullptr) inline explicit
Move construct an Expected<T> value from an Expected<OtherT>, where OtherT isn't convertible to T.
Definition at line 552 of file Error.h.
~Expected()
template<class T> llvm::Expected< T >::~Expected () inline
Destroy an Expected<T>.
Definition at line 565 of file Error.h.
Member Function Documentation
errorIsA()
template<class T> template<typename ErrT> bool llvm::Expected< T >::errorIsA () const inline
Check that this Expected<T> is an error of type ErrT.
Definition at line 604 of file Error.h.
get() [1/2]
template<class T> reference llvm::Expected< T >::get () inline
Returns a reference to the stored T value.
Definition at line 582 of file Error.h.
Referenced by llvm::BitstreamCursor::advance(), llvm::BitstreamCursor::advanceSkippingSubblocks(), llvm::BitcodeAnalyzer::analyze(), llvm::object::Archive::Archive(), llvm::object::ArchiveMemberHeader::ArchiveMemberHeader(), llvm::object::Archive::Child::Child(), llvm::gsym::ObjectFileTransformer::convert(), llvm::coverage::BinaryCoverageReader::create(), llvm::DXContainerYAML::RootSignatureYamlDesc::create(), llvm::object::Slice::create(), llvm::object::Slice::create(), llvm::object::createBinary(), llvm::pdb::NativeSession::createFromExe(), llvm::objcopy::createNewArchiveMembers(), llvm::object::ObjectFile::createObjectFile(), llvm::object::SymbolicFile::createSymbolicFile(), decode(), doList(), llvm::BitstreamCursor::EnterSubBlock(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), llvm::object::extractOffloadBinaries(), llvm::object::IRObjectFile::findBitcodeInMemBuffer(), llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA(), llvm::MCJIT::findSymbol(), llvm::dwarf_linker::finiteLoop(), llvm::MCJIT::generateCodeForModule(), llvm::object::Archive::Child::getAsBinary(), llvm::getBitcodeFileContents(), llvm::object::Archive::Child::getBuffer(), llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), getDbiStreamPtr(), getDbiStreamPtr(), llvm::object::ELFFile< ELFT >::getDynSymtabSize(), getEnableSplitLTOUnitAndUnifiedFlag(), llvm::object::XCOFFObjectFile::getImportFileTable(), llvm::getLazyIRModule(), llvm::object::Archive::Child::getMemoryBufferRef(), llvm::object::Archive::Child::getName(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::Archive::Child::getNext(), llvm::object::ArchiveMemberHeader::getNextChildLoc(), llvm::object::BigArchiveMemberHeader::getNextChildLoc(), llvm::NewArchiveMember::getOldMember(), llvm::object::BigArchiveMemberHeader::getRawName(), llvm::object::WasmObjectFile::getSymbolAddress(), llvm::object::XCOFFObjectFile::getSymbolAlignment(), llvm::object::XCOFFObjectFile::getSymbolFlags(), llvm::object::XCOFFObjectFile::getSymbolSection(), llvm::object::XCOFFObjectFile::getSymbolSectionName(), llvm::object::XCOFFObjectFile::getSymbolSize(), llvm::object::XCOFFObjectFile::getSymbolType(), llvm::BitcodeReaderValueList::getValueFwdRef(), llvm::jitlink::getXCOFFSymbolContainingSymbolRef(), hasObjCCategoryInModule(), llvm::object::COFFObjectFile::isDebugSection(), llvm::object::ELFObjectFile< ELFT >::isDebugSection(), llvm::object::MachOObjectFile::isDebugSection(), llvm::object::XCOFFSymbolRef::isFunction(), llvm::object::ArchiveMemberHeader::isThin(), jumpToValueSymbolTable(), LLVMCreateBinary(), LLVMCreateObjectFile(), LLVMGetBitcodeModuleInContext(), LLVMMachOUniversalBinaryCopyObjectForArch(), LLVMParseBitcodeInContext(), llvm::pdb::loadDataForEXE(), loadModuleFromInput(), llvm::orc::ExecutionSession::lookupFlags(), llvm::BTFParser::ParseContext::makeExtractor(), llvm::cgdata::mergeCodeGenData(), parseInlineInfo(), llvm::parseIR(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataKinds(), llvm::BitstreamCursor::ReadAbbrevRecord(), readBlobInRecord(), llvm::BitstreamCursor::ReadBlockInfoBlock(), readCoverageMappingData(), llvm::ifs::readELFFile(), llvm::msgpack::Document::readFromBlob(), readIdentificationBlock(), readModuleTriple(), llvm::BitstreamCursor::readRecord(), readTriple(), llvm::InstrProfLookupTrait::readValueProfilingData(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), searchForExe(), llvm::pdb::NativeSession::searchForPdb(), llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), llvm::SPIRVTranslate(), splitCodeGen(), and upgrade().
get() [2/2]
template<class T> const_reference llvm::Expected< T >::get () const inline
Returns a const reference to the stored T value.
Definition at line 588 of file Error.h.
moveInto()
template<class T> template<class OtherT> Error llvm::Expected< T >::moveInto (OtherT & Value, std::enable_if_t< std::is_assignable_v< OtherT &, T && > > * = nullptr) && inline
Returns takeError() after moving the held T (if any) into V.
Definition at line 595 of file Error.h.
operator bool()
template<class T> llvm::Expected< T >::operator bool () inline explicit
Return false if there is an error.
Definition at line 574 of file Error.h.
operator*() [1/2]
template<class T> reference llvm::Expected< T >::operator* () inline
Returns a reference to the stored T value.
Definition at line 632 of file Error.h.
operator*() [2/2]
template<class T> const_reference llvm::Expected< T >::operator* () const inline
Returns a const reference to the stored T value.
Definition at line 638 of file Error.h.
operator->() [1/2]
template<class T> pointer llvm::Expected< T >::operator-> () inline
Returns a pointer to the stored T value.
Definition at line 620 of file Error.h.
operator->() [2/2]
template<class T> const_pointer llvm::Expected< T >::operator-> () const inline
Returns a const pointer to the stored T value.
Definition at line 626 of file Error.h.
operator=()
template<class T> Expected & llvm::Expected< T >::operator= (Expected< T > && Other) inline
Move-assign from another Expected<T>.
Definition at line 559 of file Error.h.
Referenced by llvm::MSVCPExpected< T >::operator=().
takeError()
template<class T> Error llvm::Expected< T >::takeError () inline
Take ownership of the stored error.
After calling this the Expected<T> is in an indeterminate state that can only be safely destructed. No further calls (beside the destructor) should be made on the Expected<T> value.
Definition at line 612 of file Error.h.
Referenced by accumulateLocs(), llvm::CodeGenTargetMachineImpl::addAsmPrinter(), llvm::objcopy::coff::addGnuDebugLink(), llvm::objcopy::NameMatcher::addMatcher(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::BitstreamCursor::advance(), advanceToMetaBlock(), llvm::BitcodeAnalyzer::analyze(), llvm::object::ELFFile< ELFT >::android_relas(), appendFile(), llvm::object::Archive::Archive(), llvm::object::ArchiveMemberHeader::ArchiveMemberHeader(), llvm::lto::backend(), llvm::object::BindRebaseSegInfo::BindRebaseSegInfo(), llvm::objcopy::elf::ELFBuilder< ELFT >::build(), llvm::ifs::buildStub(), llvm::object::Archive::Child::Child(), codegen(), llvm::pdb::PDBFileBuilder::commit(), computeMemberData(), llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::object::computeSymbolSizes(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::object::SectionRef::containsSymbol(), llvm::gsym::ObjectFileTransformer::convert(), llvm::coverage::BinaryCoverageReader::create(), llvm::DXContainerYAML::RootSignatureYamlDesc::create(), llvm::InstrProfSymtab::create(), llvm::lto::InputFile::create(), llvm::MinidumpYAML::Stream::create(), llvm::objcopy::NameOrPattern::create(), llvm::object::IRObjectFile::create(), llvm::object::MinidumpFile::create(), llvm::object::Slice::create(), llvm::object::Slice::create(), llvm::symbolize::SymbolizableObjectFile::create(), llvm::object::createBinary(), llvm::OpenMPIRBuilder::createCancel(), llvm::OpenMPIRBuilder::createCancellationPoint(), llvm::pdb::NativeSession::createFromExe(), llvm::LTOModule::createInputFile(), llvm::mca::InstrBuilder::createInstruction(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::jitlink::createLinkGraphFromELFObject(), createMemberHeaderParseError(), llvm::objcopy::createNewArchiveMembers(), llvm::object::ObjectFile::createObjectFile(), createOnDiskBuffer(), createOutlinedFunction(), llvm::OpenMPIRBuilder::createParallel(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::ListeningSocket::createUnix(), llvm::remarks::createYAMLParserFromMeta(), llvm::object::ELFFile< ELFT >::crels(), decode(), llvm::gsym::CallSiteInfoCollection::decode(), llvm::gsym::MergedFunctionsInfo::decode(), decodeBBAddrMapImpl(), deepWriteArchive(), llvm::FileCheckPatternContext::defineCmdlineVariables(), llvm::NewArchiveMember::detectKindFromObject(), doImportingForModuleForTest(), doList(), llvm::DWARFDebugNames::Entry::dumpParentIdx(), dumpSectionToFile(), dumpSectionToFile(), llvm::objcopy::wasm::dumpSectionToFile(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::DWARFYAML::emitDebugNames(), llvm::RuntimeDyldImpl::emitSection(), llvm::gsym::MergedFunctionsInfo::encode(), llvm::BitstreamCursor::EnterSubBlock(), llvm::BinaryOperation::eval(), llvm::objcopy::executeObjcopyOnArchive(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), llvm::objcopy::elf::executeObjcopyOnRawBinary(), llvm::expectedToErrorOrAndEmitErrors(), llvm::DWARFAbbreviationDeclarationSet::extract(), llvm::object::extractCodeObject(), llvm::object::extractOffloadBinaries(), llvm::object::extractOffloadBundleByURI(), llvm::object::extractOffloadBundleFatBinary(), extractSections(), llvm::DebuginfodFetcher::fetch(), llvm::ifs::filterIFSSyms(), llvm::objcopy::elf::ASCIIHexWriter::finalize(), llvm::orc::DebugObject::finalizeAsync(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::pdb::GSIStreamBuilder::finalizeMsfLayout(), llvm::DebuginfodCollection::findBinaryPath(), llvm::object::IRObjectFile::findBitcodeInMemBuffer(), llvm::object::IRObjectFile::findBitcodeInObject(), llvm::DebuginfodCollection::findDebugBinaryPath(), llvm::pdb::TpiStream::findFullDeclForForwardRef(), llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA(), llvm::pdb::NativeFunctionSymbol::findInlineFramesByVA(), llvm::pdb::SymbolCache::findLineNumbersByVA(), llvm::MCJIT::findSymbol(), llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::lto::findThinLTOModule(), llvm::dwarf_linker::finiteLoop(), llvm::ARMJITSymbolFlags::fromObjectSymbol(), llvm::JITSymbolFlags::fromObjectSymbol(), llvm::DWARFDebugAranges::generate(), llvm::MCJIT::generateCodeForModule(), llvm::DWARFUnit::getAbbreviations(), llvm::object::AbstractArchiveMemberHeader::getAccessMode(), llvm::offloading::amdgpu::getAMDGPUMetaDataFromImage(), llvm::object::Archive::Child::getAsBinary(), llvm::DWARFFormValue::getAsCString(), llvm::object::COFFObjectFile::getAuxSymbol(), llvm::getBitcodeFileContents(), getBitcodeFileMachine(), llvm::getBitcodeLTOInfo(), llvm::getBitcodeProducerString(), llvm::getBitcodeTargetTriple(), llvm::object::Archive::Child::getBuffer(), llvm::getCachedOrDownloadArtifact(), llvm::getCachedOrDownloadArtifact(), llvm::orc::getCOFFObjectFileSymbolInfo(), llvm::object::ObjectFile::getCommonSymbolSize(), llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), llvm::object::ResourceSectionRef::getContents(), llvm::object::SectionRef::getContents(), getCUIdentifiers(), getDbiStreamPtr(), getDbiStreamPtr(), llvm::dwarf_linker::parallel::CompileUnit::getDirAndFilenameFromLineTable(), llvm::object::ELFFile< ELFT >::getDynSymtabSize(), llvm::object::getELFAddend(), llvm::orc::getELFObjectFileSymbolInfo(), getEnableSplitLTOUnitAndUnifiedFlag(), llvm::object::ELFFile< ELFT >::getEntry(), llvm::object::XCOFFObjectFile::getExceptionEntries(), llvm::object::getExtendedSymbolTableIndex(), llvm::MemoryBuffer::getFileAsStream(), getFileAux(), llvm::object::Archive::Child::getFullName(), llvm::gsym::GsymReader::getFunctionInfoDataForAddress(), llvm::orc::getGenericObjectFileSymbolInfo(), llvm::BinaryOperation::getImplicitFormat(), llvm::object::XCOFFObjectFile::getImportFileTable(), llvm::object::AbstractArchiveMemberHeader::getLastModified(), llvm::getLazyBitcodeModule(), llvm::getLazyIRModule(), llvm::DWARFContext::getLineTableForUnit(), llvm::object::ELFFile< ELFT >::getLinkAsStrtab(), getLoadCommandInfo(), llvm::orc::getMachOObjectFileSymbolInfo(), llvm::object::MinidumpFile::getMemory64List(), llvm::object::Archive::Child::getMemoryBufferRef(), llvm::pdb::getModuleDebugStream(), llvm::pdb::getModuleDebugStream(), llvm::getModuleSummaryIndex(), llvm::object::Archive::Child::getName(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::Archive::Child::getNext(), llvm::object::ArchiveMemberHeader::getNextChildLoc(), llvm::object::BigArchiveMemberHeader::getNextChildLoc(), llvm::getOffset(), llvm::NewArchiveMember::getOldMember(), getOpenFileImpl(), getPdbPathFromExe(), llvm::object::ELFObjectFileBase::getPltEntries(), llvm::LTOModule::getProducerString(), llvm::object::BigArchiveMemberHeader::getRawName(), getReadWriteFile(), llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), llvm::remarks::getRemarksSectionContents(), llvm::StringSubstitution::getResultForDiagnostics(), llvm::NumericSubstitution::getResultRegex(), llvm::StringSubstitution::getResultRegex(), llvm::object::ELFFile< ELFT >::getSectionAndRelocations(), llvm::object::ELFFile< ELFT >::getSectionIndex(), llvm::objcopy::elf::SectionTableRef::getSectionOfType(), getSingleModule(), llvm::object::BigArchiveMemberHeader::getSize(), llvm::object::ELFFile< ELFT >::getStringTableForSymtab(), llvm::object::ELFObjectFile< ELFT >::getSymbolAddress(), llvm::object::WasmObjectFile::getSymbolAddress(), llvm::object::ELFObjectFile< ELFT >::getSymbolAlignment(), llvm::object::XCOFFObjectFile::getSymbolAlignment(), llvm::object::ELFObjectFile< ELFT >::getSymbolBinding(), llvm::objcopy::elf::SymbolTableSection::getSymbolByIndex(), llvm::object::ELFObjectFile< ELFT >::getSymbolELFType(), llvm::object::ELFObjectFile< ELFT >::getSymbolFlags(), llvm::object::XCOFFObjectFile::getSymbolFlags(), getSymbolInfo(), llvm::object::ELFObjectFile< ELFT >::getSymbolName(), llvm::object::ELFObjectFile< ELFT >::getSymbolOther(), llvm::object::COFFObjectFile::getSymbolSection(), llvm::object::ELFObjectFile< ELFT >::getSymbolSection(), llvm::object::ELFObjectFile< ELFT >::getSymbolSection(), llvm::object::XCOFFObjectFile::getSymbolSection(), llvm::object::XCOFFObjectFile::getSymbolSectionName(), llvm::object::XCOFFObjectFile::getSymbolSize(), llvm::object::ELFObjectFile< ELFT >::getSymbolType(), llvm::object::MachOObjectFile::getSymbolType(), llvm::object::XCOFFObjectFile::getSymbolType(), llvm::object::ELFObjectFile< ELFT >::getSymbolValueImpl(), getUUID(), llvm::BitcodeReaderValueList::getValueFwdRef(), llvm::object::ELFFile< ELFT >::getVersionDefinitions(), llvm::object::ELFFile< ELFT >::getVersionDependencies(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), llvm::orc::getXCOFFObjectFileSymbolInfo(), llvm::jitlink::COFFLinkGraphBuilder::graphifySections(), llvm::jitlink::COFFLinkGraphBuilder::graphifySymbols(), handleCompressedSection(), llvm::handleSection(), hasObjCCategoryInModule(), llvm::pdb::PDBFile::hasPDBInjectedSourceStream(), llvm::pdb::PDBFile::hasPDBStringTable(), llvm::FunctionImporter::importFunctions(), llvm::objcopy::elf::RelocSectionWithSymtabBase< SymTabType >::initialize(), llvm::objcopy::elf::Section::initialize(), llvm::objcopy::elf::SectionIndexSection::initialize(), llvm::objcopy::elf::SymbolTableSection::initialize(), initRelocations(), isArchiveSymbol(), llvm::isBitcodeContainingObjCCategory(), llvm::LTOModule::isBitcodeFile(), llvm::LTOModule::isBitcodeFile(), llvm::LTOModule::isBitcodeForTarget(), isCodeViewDebugSubsection(), llvm::object::COFFObjectFile::isDebugSection(), llvm::object::ELFObjectFile< ELFT >::isDebugSection(), llvm::object::MachOObjectFile::isDebugSection(), llvm::object::XCOFFSymbolRef::isFunction(), llvm::object::ObjectFile::isSectionBitcode(), llvm::object::ArchiveMemberHeader::isThin(), llvm::isThumbFunc(), jumpToValueSymbolTable(), llvm::libDriverMain(), llvm::remarks::RemarkLinker::link(), llvm::remarks::RemarkLinker::link(), llvm::jitlink::JITLinkerBase::linkPhase2(), llvm::jitlink::JITLinkerBase::linkPhase3(), llvm::jitlink::JITLinkerBase::linkPhase4(), LLVMCreateBinary(), LLVMCreateObjectFile(), LLVMGetBitcodeModuleInContext(), LLVMMachOUniversalBinaryCopyObjectForArch(), LLVMMoveToContainingSection(), LLVMParseBitcodeInContext(), LLVMRemarkParserGetNext(), llvm::object::ResourceSectionRef::load(), llvm::pdb::loadDataForEXE(), llvm::xray::loadInstrumentationMap(), llvm::orc::loadLinkableFile(), llvm::orc::loadMachORelocatableObject(), loadModuleFromInput(), loadObj(), llvm::RuntimeDyldImpl::loadObjectImpl(), llvm::xray::loadProfile(), llvm::xray::loadTraceFile(), llvm::object::ELFFile< ELFT >::loadVersionMap(), llvm::localCache(), llvm::orc::LLJIT::lookupLinkerMangled(), lookupSections(), llvm::BTFParser::ParseContext::makeExtractor(), llvm::logicalview::LVBinaryReader::mapVirtualAddress(), llvm::logicalview::LVBinaryReader::mapVirtualAddress(), llvm::cgdata::mergeCodeGenData(), llvm::CodeGenDataReader::mergeFromObjectFile(), llvm::MSVCPExpected< T >::MSVCPExpected(), llvm::remarks::YAMLRemarkParser::next(), llvm::orc::DebugObjectManagerPlugin::notifyEmitted(), llvm::pdb::InputFile::open(), llvm::BTFParser::parse(), llvm::remarks::YAMLRemarkParser::parseArg(), llvm::parseBitcodeFile(), parseBitcodeFileImpl(), llvm::remarks::BitstreamParserHelper::parseBlockInfoBlock(), llvm::remarks::YAMLRemarkParser::parseDebugLoc(), llvm::parseIR(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataKinds(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parsePattern(), parseRecord(), parseRecord(), llvm::remarks::YAMLRemarkParser::parseRemark(), llvm::dwarf::parseRows(), parseV5DirFileTables(), populateReductionFunction(), llvm::ifs::populateSymbols(), llvm::Pattern::printSubstitutions(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::BitstreamCursor::ReadAbbrevRecord(), readBBAddrMapImpl(), readBlobInRecord(), llvm::BitstreamCursor::ReadBlockInfoBlock(), readCoverageMappingData(), llvm::readDescriptorRanges(), readDynsymVersionsImpl(), llvm::ifs::readELFFile(), llvm::msgpack::Document::readFromBlob(), readIdentificationBlock(), llvm::object::readIRSymtab(), llvm::readModuleSummaryIndex(), readModuleTriple(), llvm::sys::fs::readNativeFileToEOF(), llvm::BitstreamCursor::readRecord(), readTriple(), llvm::InstrProfLookupTrait::readValueProfilingData(), llvm::objcopy::coff::Object::removeSymbols(), llvm::pdb::PDBFile::safelyCreateNamedStream(), llvm::cgdata::saveModuleForTwoRounds(), searchForExe(), llvm::pdb::NativeSession::searchForPdb(), llvm::remarks::RemarkLinker::serialize(), setSectionFlagsAndType(), llvm::dwarf_linker::parallel::SectionDescriptor::setSizesForSectionCreatedByAsmPrinter(), llvm::setupLLVMOptimizationRemarks(), llvm::setupLLVMOptimizationRemarks(), llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), llvm::SPIRVTranslate(), llvm::streamFile(), llvm::lto::thinBackend(), updateSection(), upgrade(), llvm::write(), llvm::writeArchive(), llvm::writeArchiveToStream(), writeDIE(), writeDWARFLists(), llvm::ifs::writeELFBinaryToFile(), llvm::object::writeImportLibrary(), llvm::writeToOutput(), writeUniversalArchsToStream(), llvm::object::writeUniversalBinary(), and llvm::yaml::yaml2ObjectFile().
Friends And Related Symbol Documentation
Expected
template<class T> template<class OtherT> friend class Expected friend
Definition at line 487 of file Error.h.
Referenced by llvm::MSVCPExpected< T >::MSVCPExpected(), llvm::MSVCPExpected< T >::MSVCPExpected(), llvm::MSVCPExpected< T >::MSVCPExpected(), llvm::MSVCPExpected< T >::MSVCPExpected(), llvm::MSVCPExpected< T >::MSVCPExpected(), and llvm::MSVCPExpected< T >::MSVCPExpected().
ExpectedAsOutParameter
template<class T> template<class T1> friend class ExpectedAsOutParameter friend
Definition at line 486 of file Error.h.
Member Data Documentation
ErrorStorage
template<class T> error_type llvm::Expected< T >::ErrorStorage
Definition at line 736 of file Error.h.
TStorage
template<class T> storage_type llvm::Expected< T >::TStorage
Definition at line 735 of file Error.h.
The documentation for this class was generated from the following files:
include/llvm/ADT/APFloat.h
include/llvm/Support/Error.h