LLVM: llvm::Error Class Reference
llvm::Error Class Reference
Lightweight error class with error context and mandatory checking.
#include "llvm/Support/Error.h"
Public Member Functions
Error (const Error &Other)=delete
Error (Error &&Other)
Move-construct an error value.
Error (std::unique_ptr< ErrorInfoBase > Payload)
Create an error value.
Error & operator= (const Error &Other)=delete
Error & operator= (Error &&Other)
Move-assign an error value.
~Error ()
Destroy a Error.
operator bool ()
Bool conversion.
template<typename ErrT>
bool isA () const
Check whether one error is a subclass of another.
const void * dynamicClassID () const
Returns the dynamic class id of this error, or null if this is a success value.
Static Public Member Functions
static ErrorSuccess success ()
Create a success value.
Protected Member Functions
Error ()
Create a success value. Prefer using 'Error::success()' for readability.
Friends
class ErrorList
template<typename T>
class Expected
template<typename... HandlerTs>
Error handleErrors (Error E, HandlerTs &&... Handlers)
Pass the ErrorInfo(s) contained in E to their respective handlers.
template<typename HandlerT>
void visitErrors (const Error &E, HandlerT H)
Visit all the ErrorInfo(s) contained in E by passing them to the respective handler, without consuming the error.
LLVMErrorRef wrap (Error Err)
Conversion from Error to LLVMErrorRef for C error bindings.
raw_ostream & operator<< (raw_ostream &OS, const Error &E)
Detailed Description
Lightweight error class with error context and mandatory checking.
Instances of this class wrap a ErrorInfoBase pointer. Failure states are represented by setting the pointer to a ErrorInfoBase subclass instance containing information describing the failure. Success is represented by a null pointer value.
Instances of Error also contains a 'Checked' flag, which must be set before the destructor is called, otherwise the destructor will trigger a runtime error. This enforces at runtime the requirement that all Error instances be checked or returned to the caller.
There are two ways to set the checked flag, depending on what state the Error instance is in. For Error instances indicating success, it is sufficient to invoke the boolean conversion operator. E.g.:
Error foo(<...>);
if (auto E = foo(<...>))
  return E; // <- Return E if it is in the error state.
// We have verified that E was in the success state. It can now be safely
// destroyed.
A success value can not be dropped. For example, just calling 'foo(<...>)' without testing the return value will raise a runtime error, even if foo returns success.
For Error instances representing failure, you must use either the handleErrors or handleAllErrors function with a typed handler. E.g.:
class MyErrorInfo : public ErrorInfo<MyErrorInfo> {
  // Custom error info.
};
Error foo(<...>) { return make_error<MyErrorInfo>(...); }
auto E = foo(<...>); // <- foo returns failure with MyErrorInfo.
auto NewE =
  handleErrors(std::move(E),
    [](const MyErrorInfo &M) {
      // Deal with the error.
    },
    [](std::unique_ptr<OtherError> M) -> Error {
      if (canHandle(*M)) {
        // handle error.
        return Error::success();
      }
      // Couldn't handle this error instance. Pass it up the stack.
      return Error(std::move(M));
  });
// Note - The error passed to handleErrors will be marked as checked. If
// there is no matched handler, a new error with the same payload is
// created and returned.
// The handlers take the error checked by handleErrors as an argument,
// which can be used to retrieve more information. If a new error is
// created by a handler, it will be passed back to the caller of
// handleErrors and needs to be checked or return up to the stack.
// Otherwise, the passed-in error is considered consumed.
The handleAllErrors function is identical to handleErrors, except that it has a void return type, and requires all errors to be handled and no new errors be returned. It prevents errors (assuming they can all be handled) from having to be bubbled all the way to the top-level.
All Error instances must be checked before destruction, even if they're moved-assigned or constructed from Success values that have already been checked. This enforces checking through all levels of the call stack.
Definition at line 159 of file Error.h.
Constructor & Destructor Documentation
Error() [1/4]
llvm::Error::Error () inline protected
Create a success value. Prefer using 'Error::success()' for readability.
Definition at line 181 of file Error.h.
Referenced by Error(), Error(), ErrorList, Expected, handleErrors, llvm::MSVCPError::MSVCPError(), llvm::MSVCPError::MSVCPError(), operator<<, operator=(), operator=(), visitErrors, and wrap.
Error() [2/4]
llvm::Error::Error (const Error & Other) delete
References Error(), and llvm::Other.
Error() [3/4]
llvm::Error::Error (Error && Other) inline
Move-construct an error value.
The newly constructed error is considered unchecked, even if the source error had been checked. The original error becomes a checked Success value, regardless of its original state.
Definition at line 196 of file Error.h.
References Error(), and llvm::Other.
Error() [4/4]
llvm::Error::Error (std::unique_ptr< ErrorInfoBase > Payload) inline
Create an error value.
Prefer using the 'make_error' function, but this constructor can be useful when "re-throwing" errors from handlers.
Definition at line 203 of file Error.h.
~Error()
llvm::Error::~Error () inline
Destroy a Error.
Fails with a call to abort() if the error is unchecked.
Definition at line 232 of file Error.h.
References getPtr().
Member Function Documentation
dynamicClassID()
const void * llvm::Error::dynamicClassID () const inline
Returns the dynamic class id of this error, or null if this is a success value.
Definition at line 252 of file Error.h.
References getPtr().
isA()
template<typename ErrT> bool llvm::Error::isA () const inline
Check whether one error is a subclass of another.
Definition at line 246 of file Error.h.
References getPtr().
operator bool()
llvm::Error::operator bool () inline explicit
Bool conversion.
Returns true if this Error is in a failure state, and false if it is in an accept state. If the error is in a Success state it will be considered checked.
Definition at line 240 of file Error.h.
References getPtr().
operator=() [1/2]
Error & llvm::Error::operator= (const Error & Other) delete
References Error(), and llvm::Other.
Referenced by llvm::MSVCPError::operator=().
operator=() [2/2]
Error & llvm::Error::operator= (Error && Other) inline
Move-assign an error value.
The current error must represent success, you you cannot overwrite an unhandled error. The current error is then considered unchecked. The source error becomes a checked success value, regardless of its original state.
Definition at line 215 of file Error.h.
References Error(), and llvm::Other.
success()
ErrorSuccess llvm::Error::success () inline static
Create a success value.
Definition at line 336 of file Error.h.
Referenced by llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc::abandon(), llvm::OverlapStats::accumulateCounts(), llvm::lto::LTO::add(), addAllTypesFromDWP(), addAllTypesFromTypesSection(), llvm::jitlink::BlockAddressMap::addBlock(), llvm::xray::Profile::addBlock(), llvm::jitlink::BlockAddressMap::addBlocks(), llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addCoreISelPasses(), llvm::pdb::DbiStreamBuilder::addDbgStream(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addDIETypeName(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::objcopy::coff::addGnuDebugLink(), llvm::AMDGPUCodeGenPassBuilder::addInstSelector(), llvm::R600CodeGenPassBuilder::addInstSelector(), llvm::memprof::DataAccessProfData::addKnownSymbolWithoutSamples(), llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addMachinePasses(), llvm::objcopy::NameMatcher::addMatcher(), llvm::pdb::DbiStreamBuilder::addModuleSourceFile(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::objcopy::elf::Object::addNewSymbolTable(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addParamNames(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addParentName(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addReferencedODRDies(), llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addRegAssignmentFast(), llvm::AMDGPUCodeGenPassBuilder::addRegAssignmentOptimized(), llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addRegAssignmentOptimized(), llvm::lto::Config::addSaveTemps(), addSection(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addSignature(), llvm::InstrProfSymtab::addSymbolName(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addTemplateParamNames(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addTypeName(), llvm::InstrProfSymtab::addVTableName(), advanceToMetaBlock(), llvm::BitcodeAnalyzer::analyze(), appendFile(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::FilePermissionsApplier::apply(), llvm::jitlink::BasicLayout::apply(), llvm::orc::LLJIT::applyDataLayout(), llvm::jitlink::aarch32::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::loongarch::applyFixup(), llvm::jitlink::ppc64::applyFixup(), llvm::jitlink::x86::applyFixup(), llvm::jitlink::x86_64::applyFixup(), llvm::jitlink::XCOFFJITLinker_ppc64::applyFixup(), llvm::jitlink::aarch32::applyFixupArm(), llvm::jitlink::aarch32::applyFixupData(), llvm::jitlink::aarch32::applyFixupThumb(), llvm::DWARFUnitHeader::applyIndexEntry(), llvm::jitlink::applyPACSigningToModInitPointers(), llvm::object::Archive::Archive(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::assignName(), llvm::dwarf_linker::parallel::CompileUnit::assignTypeNames(), llvm::BitcodeReaderValueList::assignValue(), llvm::lto::backend(), llvm::codeview::CodeViewRecordIO::beginRecord(), llvm::object::BigArchive::BigArchive(), llvm::jitlink::buildTables_ELF_aarch32(), llvm::jitlink::buildTables_MachO_arm64(), llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::callAsync(), llvm::DWARFContext::checkAddressSizeSupported(), checkChars(), llvm::FileCheckString::CheckDag(), checkDyldCommand(), checkDyldInfoCommand(), checkDylibCommand(), checkDylibIdCommand(), checkDysymtabCommand(), checkEncryptCommand(), llvm::gsym::Header::checkForError(), checkHashHdrVersion(), checkLinkeditDataCommand(), checkLinkerOptCommand(), llvm::orc::checkMachORelocatableObject(), checkNoteCommand(), llvm::object::Binary::checkOffset(), llvm::BinaryStream::checkOffsetForRead(), llvm::BinaryStreamRefBase< RefType, StreamType >::checkOffsetForRead(), llvm::WritableBinaryStream::checkOffsetForWrite(), llvm::jitlink::aarch32::checkOpcode(), llvm::jitlink::aarch32::checkOpcode(), checkOperandCount(), checkOverlappingElement(), checkRecord(), checkRpathCommand(), llvm::objcopy::elf::ASCIIHexWriter::checkSection(), checkSubCommand(), llvm::object::MachOObjectFile::checkSymbolTable(), checkSymtabCommand(), checkThreadCommand(), checkTwoLevelHintsCommand(), checkVersCommand(), llvm::orc::JITDylib::clear(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::cloneAndEmitDebugFrame(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitDebugLocations(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitDebugMacro(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitLineTable(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitRanges(), llvm::collectGlobalObjectNameStrings(), llvm::AppendingBinaryByteStream::commit(), llvm::CachedFileStream::commit(), llvm::codeview::DebugChecksumsSubsection::commit(), llvm::codeview::DebugCrossModuleExportsSubsection::commit(), llvm::codeview::DebugCrossModuleImportsSubsection::commit(), llvm::codeview::DebugFrameDataSubsection::commit(), llvm::codeview::DebugInlineeLinesSubsection::commit(), llvm::codeview::DebugLinesSubsection::commit(), llvm::codeview::DebugStringTableSubsection::commit(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::codeview::DebugSymbolsSubsection::commit(), llvm::MutableBinaryByteStream::commit(), llvm::pdb::const_iterator< SrcHeaderBlockEntry >::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::pdb::GSIHashStreamBuilder::commit(), llvm::pdb::GSIStreamBuilder::commit(), llvm::pdb::InfoStreamBuilder::commit(), llvm::pdb::ModuleDebugStreamRef::commit(), llvm::pdb::NamedStreamMap::commit(), llvm::pdb::PDBStringTableBuilder::commit(), llvm::pdb::SymbolStream::commit(), llvm::pdb::TpiStream::commit(), llvm::pdb::TpiStreamBuilder::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commitSymbolStream(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::codeview::consume(), llvm::codeview::consume(), llvm::xray::LogBuilderConsumer::consume(), llvm::xray::PipelineConsumer::consume(), llvm::codeview::consume_numeric(), llvm::offloading::intel::containerizeOpenMPSPIRVImage(), llvm::gsym::DwarfTransformer::convert(), llvm::gsym::ObjectFileTransformer::convert(), llvm::orc::COFFPlatform::Create(), llvm::orc::ELFNixPlatform::Create(), llvm::orc::LazyReexportsManager::Create(), llvm::orc::LocalJITCompileCallbackManager< ORCABI >::Create(), llvm::orc::LocalTrampolinePool< ORCABI >::Create(), llvm::orc::MachOPlatform::Create(), llvm::orc::StaticLibraryDefinitionGenerator::Create(), llvm::coverage::BinaryCoverageReader::create(), llvm::InstrProfSymtab::create(), llvm::InstrProfSymtab::create(), llvm::InstrProfSymtab::create(), llvm::InstrProfSymtab::create(), llvm::InstrProfSymtab::create(), llvm::MinidumpYAML::Stream::create(), llvm::object::Archive::create(), llvm::object::MachOObjectFile::create(), llvm::object::MachOUniversalBinary::create(), llvm::object::Slice::create(), llvm::object::TapiUniversal::create(), llvm::object::TBVectorExt::create(), llvm::object::XCOFFTracebackTable::create(), llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::create(), llvm::OpenMPIRBuilder::createCancel(), llvm::OpenMPIRBuilder::createCancellationPoint(), llvm::createCtxProfFromYAML(), llvm::jitlink::aarch64::createEmptyPointerSigningFunction(), llvm::pdb::DIASession::createFromExe(), llvm::pdb::NativeSession::createFromExe(), llvm::pdb::DIASession::createFromPdb(), llvm::pdb::NativeSession::createFromPdb(), llvm::pdb::NativeSession::createFromPdbPath(), llvm::object::ObjectFile::createGOFFObjectFile(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::objcopy::createNewArchiveMembers(), llvm::OpenMPIRBuilder::createParallel(), llvm::logicalview::LVCodeViewReader::createScopes(), llvm::logicalview::LVDWARFReader::createScopes(), llvm::logicalview::LVReader::createScopes(), llvm::logicalview::LVSplitContext::createSplitFolder(), llvm::orc::LocalIndirectStubsManager< TargetT >::createStub(), llvm::orc::LocalIndirectStubsManager< TargetT >::createStubs(), llvm::object::ObjectFile::createWasmObjectFile(), llvm::jitlink::InProcessMemoryManager::deallocate(), llvm::orc::MapperJITLinkMemoryManager::deallocate(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::deallocate(), llvm::decodeBase64(), decodeBBAddrMapImpl(), deepWriteArchive(), llvm::orc::JITDylib::define(), llvm::orc::JITDylib::define(), llvm::FileCheckPatternContext::defineCmdlineVariables(), llvm::orc::InProcessMemoryMapper::deinitialize(), llvm::orc::ORCPlatformSupport::deinitialize(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::deinitialize(), llvm::orc::deregisterFrameWrapper(), llvm::codeview::serialize_conditional_impl< T, U >::deserialize(), llvm::codeview::serialize_vector_tail_impl< T >::deserialize(), llvm::IndexedMemProfReader::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT >::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize(), llvm::codeview::SymbolDeserializer::deserializeAs(), llvm::codeview::TypeDeserializer::deserializeAs(), llvm::orc::SelfExecutorProcessControl::disconnect(), llvm::telemetry::Manager::dispatch(), doList(), llvm::logicalview::LVReader::doLoad(), llvm::logicalview::LVObject::doPrint(), llvm::logicalview::LVReader::doPrint(), llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::DWARFContext::dump(), llvm::objcopy::coff::dumpSection(), dumpSectionToFile(), dumpSectionToFile(), llvm::objcopy::wasm::dumpSectionToFile(), llvm::InstrProfCorrelatorImpl< IntPtrT >::dumpYaml(), llvm::dwarf_linker::parallel::DebugLineSectionEmitter::emit(), llvm::dwarf_linker::parallel::DwarfUnit::emitAbbreviations(), llvm::RuntimeDyldImpl::emitCommonSymbols(), llvm::DWARFYAML::emitDebugAbbrev(), llvm::DWARFYAML::emitDebugAddr(), llvm::DWARFYAML::emitDebugAranges(), llvm::dwarf_linker::parallel::DwarfUnit::emitDebugInfo(), llvm::DWARFYAML::emitDebugInfo(), llvm::DWARFYAML::emitDebugLine(), llvm::DWARFYAML::emitDebugNames(), llvm::DWARFYAML::emitDebugRanges(), emitDebugSectionImpl(), llvm::DWARFYAML::emitDebugSections(), llvm::DWARFYAML::emitDebugStr(), llvm::dwarf_linker::parallel::DwarfUnit::emitDebugStringOffsetSection(), llvm::DWARFYAML::emitDebugStrOffsets(), llvm::lto::ThinBackendProc::emitFiles(), llvm::EmitImportsFiles(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::emitInvariantSections(), emitPubSection(), emitTargetCall(), llvm::orc::enableDebuggerSupport(), llvm::gsym::CallSiteInfo::encode(), llvm::gsym::CallSiteInfoCollection::encode(), llvm::gsym::Header::encode(), llvm::gsym::InlineInfo::encode(), llvm::gsym::LineTable::encode(), llvm::gsym::MergedFunctionsInfo::encode(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::BitstreamCursor::EnterSubBlock(), llvm::CodeGenDataReader::error(), llvm::InstrProfReader::error(), llvm::remarks::YAMLRemarkParser::error(), llvm::BinaryOperation::eval(), llvm::logicalview::LVCompare::execute(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::AppleAcceleratorTable::extract(), llvm::DWARFAbbreviationDeclaration::extract(), llvm::DWARFAbbreviationDeclarationSet::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFDebugNames::extract(), llvm::DWARFDebugNames::NameIndex::extract(), llvm::DWARFDebugRangeList::extract(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::DWARFListTableHeader::extract(), llvm::DWARFListType< ListEntryType >::extract(), llvm::DWARFUnitHeader::extract(), llvm::RangeListEntry::extract(), llvm::object::OffloadBundleFatBin::extractBundle(), llvm::object::extractCodeObject(), llvm::object::extractOffloadBinaries(), extractOffloadBundle(), llvm::object::extractOffloadBundleByURI(), llvm::object::extractOffloadBundleFatBinary(), llvm::DWARFDebugAddrTable::extractV5(), llvm::DWARFFormValue::extractValue(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::ifs::filterIFSSyms(), llvm::gsym::GsymCreator::finalize(), llvm::objcopy::elf::ASCIIHexWriter::finalize(), llvm::objcopy::elf::BinaryWriter::finalize(), llvm::objcopy::elf::ELFWriter< ELFT >::finalize(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::finalize(), llvm::RuntimeDyldImpl::finalizeAsync(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldImpl::finalizeLoad(), llvm::RuntimeDyldMachOCRTPBase< Impl >::finalizeLoad(), llvm::orc::EPCGenericRTDyldMemoryManager::finalizeMemory(), llvm::pdb::DbiModuleDescriptorBuilder::finalizeMsfLayout(), llvm::pdb::DbiStreamBuilder::finalizeMsfLayout(), llvm::pdb::GSIStreamBuilder::finalizeMsfLayout(), llvm::pdb::InfoStreamBuilder::finalizeMsfLayout(), llvm::pdb::TpiStreamBuilder::finalizeMsfLayout(), llvm::lto::finalizeOptimizationRemarks(), llvm::RuntimeDyldMachOAArch64::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::RuntimeDyldMachOI386::finalizeSection(), llvm::RuntimeDyldMachOX86_64::finalizeSection(), llvm::DWARFUnit::findLoclistFromOffset(), llvm::dwarf_linker::parallel::TypeUnit::finishCloningAndEmit(), finishVisitation(), llvm::logicalview::LVLogicalVisitor::finishVisitation(), llvm::dwarf_linker::finiteLoop(), llvm::xray::BlockIndexer::flush(), llvm::xray::TraceExpander::flush(), llvm::codeview::forEachCodeViewRecord(), llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >::forEachRelaRelocation(), llvm::jitlink::COFFLinkGraphBuilder::forEachRelocation(), llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >::forEachRelRelocation(), llvm::orc::SymbolLookupSet::forEachWithRemoval(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), llvm::orc::shared::detail::fromSPSSerializable(), llvm::HTTPServer::get(), llvm::offloading::amdgpu::getAMDGPUMetaDataFromImage(), llvm::object::COFFObjectFile::getAuxSymbol(), llvm::orc::ExecutorProcessControl::getBootstrapMapValue(), llvm::orc::ExecutorProcessControl::getBootstrapSymbols(), llvm::object::ELFObjectFile< ELF32LE >::getBuildAttributes(), llvm::object::Record::getContinuousData(), llvm::object::ELFFile< ELFT >::getCrelHeader(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::object::DelayImportDirectoryEntryRef::getDelayImportTable(), llvm::object::ExportDirectoryEntryRef::getDllName(), llvm::InstrProfReader::getError(), llvm::object::ExportDirectoryEntryRef::getExportRVA(), getExtensionVersion(), llvm::object::ExportDirectoryEntryRef::getForwardTo(), llvm::coverage::accessors::getFuncNameViaRef(), getGlobalSymtabLocAndSize(), llvm::object::COFFObjectFile::getHintName(), llvm::object::ImportedSymbolRef::getHintNameRVA(), llvm::BinaryOperation::getImplicitFormat(), llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), llvm::object::ImportDirectoryEntryRef::getImportAddressTableRVA(), llvm::object::ImportDirectoryEntryRef::getImportLookupTableRVA(), llvm::IndexedInstrProfReader::getInstrProfRecord(), llvm::object::Archive::Symbol::getMember(), llvm::object::DelayImportDirectoryEntryRef::getName(), llvm::object::ImportDirectoryEntryRef::getName(), llvm::object::Archive::Child::getNext(), getObject(), llvm::getOffset(), llvm::object::ExportDirectoryEntryRef::getOrdinal(), llvm::object::ImportedSymbolRef::getOrdinal(), llvm::object::ExportDirectoryEntryRef::getOrdinalBase(), llvm::InstrProfReaderIndex< HashTableImpl >::getRecords(), llvm::InstrProfReaderIndex< HashTableImpl >::getRecords(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), llvm::object::BaseRelocRef::getRVA(), llvm::object::COFFObjectFile::getRvaAndSizeAsBytes(), llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::ELFFile< ELFT >::getSectionAndRelocations(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::ExportDirectoryEntryRef::getSymbolName(), llvm::object::ImportedSymbolRef::getSymbolName(), llvm::object::BaseRelocRef::getType(), llvm::jitlink::COFFLinkGraphBuilder::graphifySections(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::graphifySections(), llvm::jitlink::COFFLinkGraphBuilder::graphifySymbols(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::graphifySymbols(), handleArgs(), handleArgs(), llvm::objcopy::coff::handleArgs(), llvm::objcopy::wasm::handleArgs(), llvm::objcopy::xcoff::handleArgs(), handleCompressedSection(), handleErrors, handleMaybeNoDataFoundError(), llvm::orc::LazyReexportsManager::handleRemoveResources(), llvm::orc::ReOptimizeLayer::handleRemoveResources(), llvm::handleSection(), hasInvalidBitcodeHeader(), llvm::orc::ReOptimizeLayer::identity(), ignoreStrippedErrors(), llvm::object::Archive::ChildFallibleIterator::inc(), llvm::object::MinidumpFile::Memory64Iterator::inc(), llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), llvm::object::Binary::initContent(), llvm::object::ELFObjectFile< ELFT >::initContent(), llvm::codeview::DebugChecksumsSubsectionRef::initialize(), llvm::codeview::DebugFrameDataSubsectionRef::initialize(), llvm::codeview::DebugInlineeLinesSubsectionRef::initialize(), llvm::codeview::DebugLinesSubsectionRef::initialize(), llvm::codeview::DebugStringTableSubsectionRef::initialize(), llvm::codeview::DebugSubsectionRecord::initialize(), llvm::objcopy::elf::RelocSectionWithSymtabBase< SymTabType >::initialize(), llvm::objcopy::elf::Section::initialize(), llvm::objcopy::elf::SectionBase::initialize(), llvm::objcopy::elf::SectionIndexSection::initialize(), llvm::objcopy::elf::SymbolTableSection::initialize(), llvm::object::DirectX::Signature::initialize(), llvm::orc::ORCPlatformSupport::initialize(), llvm::pdb::DbiModuleDescriptor::initialize(), llvm::pdb::DbiModuleList::initialize(), llvm::pdb::PDBFileBuilder::initialize(), llvm::orc::COFFVCRuntimeBootstrapper::initializeStaticVCRuntime(), initRelocations(), llvm::objcopy::elf::BasicELFBuilder::initSections(), llvm::logicalview::LVLogicalVisitor::inlineSiteAnnotation(), llvm::SpecialCaseList::Matcher::insert(), llvm::ELFCompactAttrParser::integerAttribute(), llvm::interpretDecimal(), llvm::object::ExportDirectoryEntryRef::isForwarder(), llvm::object::isNotObjectErrorInvalidFileType(), llvm::object::ImportedSymbolRef::isOrdinal(), isValidMachOCannonicalName(), llvm::pdb::iterateModuleSubsections(), llvm::pdb::iterateSymbolGroups(), llvm::SimpleBitstreamCursor::JumpToBit(), llvm::sys::fs::TempFile::keep(), llvm::dwarf_linker::classic::DWARFLinker::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::link(), llvm::remarks::RemarkLinker::link(), llvm::remarks::RemarkLinker::link(), llvm::orc::LLJIT::linkStaticLibraryInto(), llvm::orc::LLJIT::linkStaticLibraryInto(), llvm_orc_registerJITLoaderGDBAllocAction(), llvm_orc_registerJITLoaderGDBWrapper(), llvm::object::ResourceSectionRef::load(), llvm::pdb::const_iterator< SrcHeaderBlockEntry >::load(), load(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::loadClangModule(), LoadDIA(), llvm::logicalview::LVBinaryReader::loadGenericTargetInfo(), loadObj(), loadSectionContribs(), loadYAML(), llvm::localCache(), llvm::gsym::InlineInfo::lookup(), llvm::orc::ExecutionSession::lookup(), llvm::orc::ExecutionSession::lookup(), llvm::orc::lookupAndRecordAddrs(), llvm::orc::lookupAndRecordAddrs(), llvm::orc::ExecutionSession::lookupFlags(), llvm::orc::ExecutionSession::lookupFlags(), llvm::orc::Platform::lookupInitSymbols(), llvm::orc::Platform::lookupInitSymbolsAsync(), llvm::jitlink::aarch64::lowerPointer64AuthEdgesToSigningFunction(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::makeValue(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), llvm::codeview::CodeViewRecordIO::mapEncodedInteger(), llvm::codeview::CodeViewRecordIO::mapEncodedInteger(), llvm::codeview::CodeViewRecordIO::mapEncodedInteger(), llvm::codeview::CodeViewRecordIO::mapEnum(), llvm::codeview::CodeViewRecordIO::mapGuid(), llvm::codeview::CodeViewRecordIO::mapInteger(), llvm::codeview::CodeViewRecordIO::mapInteger(), mapLocalVariableAddrRange(), mapNameAndUniqueName(), llvm::codeview::CodeViewRecordIO::mapObject(), llvm::codeview::CodeViewRecordIO::mapStringZ(), llvm::codeview::CodeViewRecordIO::mapStringZVectorZ(), llvm::codeview::CodeViewRecordIO::mapVectorN(), llvm::codeview::CodeViewRecordIO::mapVectorTail(), llvm::jitlink::markAllSymbolsLive(), llvm::objcopy::coff::Object::markSymbols(), llvm::Pattern::match(), llvm::CodeGenDataReader::mergeFromObjectFile(), llvm::InstrProfWriter::mergeProfileKind(), llvm::jitlink::JITLinkContext::modifyPassConfig(), llvm::orc::DebugObjectManagerPlugin::modifyPassConfig(), llvm::orc::EHFrameRegistrationPlugin::modifyPassConfig(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::modifyPassConfig(), llvm::orc::PerfSupportPlugin::modifyPassConfig(), llvm::orc::VTuneSupportPlugin::modifyPassConfig(), llvm::object::ResourceEntryRef::moveNext(), llvm::orc::COFFPlatform::notifyAdding(), llvm::orc::ELFNixPlatform::notifyAdding(), llvm::orc::MachOPlatform::notifyAdding(), llvm::orc::DebugObjectManagerPlugin::notifyEmitted(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyEmitted(), llvm::orc::LinkGraphLinkingLayer::Plugin::notifyEmitted(), llvm::orc::UnwindInfoRegistrationPlugin::notifyEmitted(), llvm::orc::VTuneSupportPlugin::notifyEmitted(), llvm::orc::DebugInfoPreservationPlugin::notifyFailed(), llvm::orc::DebugObjectManagerPlugin::notifyFailed(), llvm::orc::EHFrameRegistrationPlugin::notifyFailed(), llvm::orc::GDBJITDebugInfoRegistrationPlugin::notifyFailed(), llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::notifyFailed(), llvm::orc::LazyObjectLinkingLayer::RenamerPlugin::notifyFailed(), llvm::orc::LazyReexportsManager::Plugin::notifyFailed(), llvm::orc::PerfSupportPlugin::notifyFailed(), llvm::orc::UnwindInfoRegistrationPlugin::notifyFailed(), llvm::orc::VTuneSupportPlugin::notifyFailed(), llvm::orc::DebugInfoPreservationPlugin::notifyRemovingResources(), llvm::orc::DebugObjectManagerPlugin::notifyRemovingResources(), llvm::orc::EHFrameRegistrationPlugin::notifyRemovingResources(), llvm::orc::GDBJITDebugInfoRegistrationPlugin::notifyRemovingResources(), llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::notifyRemovingResources(), llvm::orc::LazyObjectLinkingLayer::RenamerPlugin::notifyRemovingResources(), llvm::orc::LazyReexportsManager::Plugin::notifyRemovingResources(), llvm::orc::PerfSupportPlugin::notifyRemovingResources(), llvm::orc::UnwindInfoRegistrationPlugin::notifyRemovingResources(), llvm::orc::VTuneSupportPlugin::notifyRemovingResources(), llvm::orc::LazyCallThroughManager::notifyResolved(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved(), llvm::orc::SimpleLazyReexportsSpeculator::onLazyReexportsRemoved(), llvm::codeview::LineColumnExtractor::operator()(), llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >::operator()(), llvm::jitlink::DWARFRecordSectionSplitter::operator()(), llvm::jitlink::EHFrameEdgeFixer::operator()(), llvm::jitlink::EHFrameNullTerminator::operator()(), llvm::jitlink::SEHFrameKeepAlivePass::operator()(), llvm::orc::LoadAndLinkDynLibrary::operator()(), llvm::VarStreamArrayExtractor< T >::operator()(), llvm::VarStreamArrayExtractor< codeview::CVRecord< Kind > >::operator()(), llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord >::operator()(), llvm::VarStreamArrayExtractor< pdb::DbiModuleDescriptor >::operator()(), llvm::jitlink::x86::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), llvm::ifs::overrideIFSTarget(), llvm::BinaryStreamWriter::padToAlignment(), llvm::parallelForEachError(), llvm::BTFParser::parse(), llvm::DWARFDebugAbbrev::parse(), llvm::DWARFDebugFrame::parse(), llvm::DWARFDebugLine::LineTable::parse(), llvm::DWARFDebugLine::Prologue::parse(), llvm::ELFAttributeParser::parse(), llvm::object::DirectX::PSVRuntimeInfo::parse(), llvm::object::DirectX::RootSignature::parse(), llvm::object::WindowsResourceParser::parse(), parse(), llvm::PassBuilder::parseAAPipeline(), parseAddrSpace(), parseAlignment(), llvm::ELFCompactAttrParser::parseAttributeList(), parseBlock(), llvm::remarks::BitstreamParserHelper::parseBlockInfoBlock(), parseBuildVersionCommand(), llvm::pdb::PDBFile::parseFileHeaders(), llvm::parseInfoSectionUnitHeader(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataKinds(), llvm::PassBuilder::parsePassPipeline(), llvm::PassBuilder::parsePassPipeline(), llvm::PassBuilder::parsePassPipeline(), llvm::PassBuilder::parsePassPipeline(), llvm::PassBuilder::parsePassPipeline(), parseRecord(), parseRecord(), llvm::MCSectionMachO::ParseSectionSpecifier(), parseSegmentLoadCommand(), parseSize(), llvm::pdb::PDBFile::parseStreamData(), llvm::ELFCompactAttrParser::parseStringAttribute(), llvm::ELFCompactAttrParser::parseSubsection(), parseV2DirFileTables(), parseV5DirFileTables(), parseV5EntryFormat(), llvm::ifs::populateDynamic(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), populateReductionFunction(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::populateRemappings(), llvm::InstrProfReaderRemapper::populateRemappings(), llvm::ifs::populateSymbols(), llvm::telemetry::Manager::preDispatch(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::prepare(), llvm::orc::LLJITBuilderState::prepareForConstruction(), llvm::orc::LLLazyJITBuilderState::prepareForConstruction(), llvm::jitlink::CompactUnwindManager< CURecTraits >::prepareForPrune(), llvm::orc::preserveDebugSections(), llvm::IndexedInstrProfReader::printBinaryIds(), llvm::RawInstrProfReader< IntPtrT >::printBinaryIds(), llvm::logicalview::LVReader::printScopes(), llvm::object::COFFImportFile::printSymbolName(), llvm::object::IRObjectFile::printSymbolName(), llvm::object::ObjectFile::printSymbolName(), llvm::object::TapiFile::printSymbolName(), llvm::logicalview::LVReaderHandler::process(), llvm::jitlink::CompactUnwindManager< CURecTraits >::processAndReserveUnwindInfo(), processLoadCommands(), processRemarkVersion(), processStrTab(), llvm::coverage::RawCoverageMappingReader::read(), llvm::pdb::GSIHashTable::read(), llvm::SymbolRemappingReader::read(), llvm::TextCodeGenDataReader::read(), llvm::BitstreamCursor::ReadAbbrevRecord(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readArray(), llvm::RawInstrProfReader< IntPtrT >::readBinaryIds(), readBinaryIdsInternal(), llvm::AppendingBinaryByteStream::readBytes(), llvm::BinaryByteStream::readBytes(), llvm::BinaryItemStream< T, Traits >::readBytes(), llvm::BinaryStreamReader::readBytes(), llvm::msf::MappedBlockStream::readBytes(), readCoverageMappingData(), llvm::BinaryStreamReader::readCString(), llvm::readDescriptorRanges(), llvm::object::OffloadBundleFatBin::readEntries(), llvm::BinaryStreamReader::readEnum(), llvm::BinaryStreamReader::readFixedString(), readGSIHashBuckets(), readGSIHashHeader(), readGSIHashRecords(), readInitExpr(), llvm::BinaryStreamReader::readInteger(), readInteger(), llvm::coverage::RawCoverageReader::readIntMax(), llvm::AppendingBinaryByteStream::readLongestContiguousChunk(), llvm::BinaryByteStream::readLongestContiguousChunk(), llvm::BinaryItemStream< T, Traits >::readLongestContiguousChunk(), llvm::BinaryStreamReader::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::msf::MappedBlockStream::readLongestContiguousChunk(), readMachOHeader(), llvm::sys::fs::readNativeFileToEOF(), llvm::coverage::BinaryCoverageReader::readNextRecord(), llvm::memprof::MemProfReader::readNextRecord(), llvm::BinaryStreamReader::readObject(), readSection(), ReadSignature(), llvm::coverage::RawCoverageReader::readSize(), llvm::BinaryStreamReader::readSLEB128(), llvm::pdb::readSparseBitVector(), llvm::BinaryStreamReader::readStreamRef(), llvm::coverage::RawCoverageReader::readString(), llvm::object::readStringOrId(), readStruct(), readSymbols(), llvm::BinaryStreamReader::readULEB128(), llvm::coverage::RawCoverageReader::readULEB128(), llvm::BinaryStreamReader::readWideString(), llvm::orc::ELFDebugObject::recordSection(), llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::recordTrampolineAddrs(), llvm::orc::IndirectStubsManager::redirect(), llvm::orc::registerFrameWrapper(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), llvm::jitlink::relax(), llvm::orc::InProcessMemoryMapper::release(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::release(), llvm::orc::SharedMemoryMapper::release(), llvm::pdb::DbiStream::reload(), llvm::pdb::GlobalsStream::reload(), llvm::pdb::InfoStream::reload(), llvm::pdb::InjectedSourceStream::reload(), llvm::pdb::ModuleDebugStreamRef::reload(), llvm::pdb::PDBStringTable::reload(), llvm::pdb::PublicsStream::reload(), llvm::pdb::SymbolStream::reload(), llvm::pdb::TpiStream::reload(), llvm::jitlink::ppc64::relocateHalf16(), llvm::orc::JITDylib::remove(), llvm::orc::ExecutionSession::removeJITDylibs(), llvm::objcopy::macho::Object::removeLoadCommands(), removeNotes(), llvm::objcopy::elf::DynamicRelocationSection::removeSectionReferences(), llvm::objcopy::elf::GroupSection::removeSectionReferences(), llvm::objcopy::elf::Section::removeSectionReferences(), llvm::objcopy::elf::SectionBase::removeSectionReferences(), llvm::objcopy::elf::Object::removeSections(), llvm::objcopy::macho::Object::removeSections(), llvm::objcopy::coff::Object::removeSymbols(), llvm::objcopy::elf::GroupSection::removeSymbols(), llvm::objcopy::elf::Object::removeSymbols(), llvm::objcopy::elf::RelocationSection::removeSymbols(), llvm::objcopy::elf::SectionBase::removeSymbols(), llvm::objcopy::elf::SymbolTableSection::removeSymbols(), removeUnneededSections(), llvm::orc::ReOptimizeLayer::reoptimizeIfCallFrequent(), replaceAndRemoveSections(), llvm::objcopy::elf::Object::replaceSections(), llvm::ErrorReported::reportedOrSuccess(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), llvm::orc::CtorDtorRunner::run(), llvm::orc::LookupTask::run(), llvm::orc::shared::runDeallocActions(), llvm::orc::shared::WrapperFunctionCall::runWithSPSRet(), sectionOverflowErrorOrWarning(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), llvm::memprof::DataAccessProfData::serialize(), llvm::remarks::RemarkLinker::serialize(), llvm::MachO::serializeInterfaceFileToJSON(), llvm::msf::MSFBuilder::setBlockMapAddr(), llvm::memprof::DataAccessProfData::setDataAccessProfile(), llvm::memprof::DataAccessProfData::setDataAccessProfile(), llvm::msf::MSFBuilder::setDirectoryBlocksHint(), llvm::remarks::RemarkStreamer::setFilter(), setSectionFlagsAndType(), llvm::msf::MSFBuilder::setStreamSize(), llvm::dwarf_linker::classic::DWARFLinker::setTargetDWARFVersion(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setTargetDWARFVersion(), llvm::orc::COFFPlatform::setupJITDylib(), llvm::setupLLVMOptimizationRemarks(), llvm::orc::setUpOrcPlatformManually(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::shutdown(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::shutdown(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::shutdown(), llvm::BinaryStreamReader::skip(), llvm::BitstreamCursor::SkipBlock(), llvm::codeview::CodeViewRecordIO::skipPadding(), llvm::jitlink::splitCompactUnwindBlocks(), llvm::orc::FDSimpleRemoteEPCTransport::start(), llvm::ELFCompactAttrParser::stringAttribute(), llvm::Expected< std::unique_ptr< InFlightAlloc > >::takeError(), llvm::JITSymbol::takeError(), llvm::orc::COFFPlatform::teardownJITDylib(), llvm::orc::ELFNixPlatform::teardownJITDylib(), llvm::orc::MachOPlatform::teardownJITDylib(), llvm::timeTraceProfilerWrite(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::EPCDynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::ReexportsGenerator::tryToGenerate(), llvm::orc::StaticLibraryDefinitionGenerator::tryToGenerate(), llvm::DebuginfodCollection::update(), updateAndRemoveSymbols(), llvm::orc::LocalIndirectStubsManager< TargetT >::updatePointer(), updateSection(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::validateAndUpdateOptions(), llvm::StackMapParser< Endianness >::validateHeader(), llvm::ifs::validateIFSTarget(), llvm::orc::ELFDebugObjectSection< ELFT >::validateInBounds(), validateMagicNumber(), llvm::InstrProfWriter::validateRecord(), llvm::msf::validateSuperBlock(), llvm::GISelCSEInfo::verify(), llvm::gsym::DwarfTransformer::verify(), llvm::InlineAsm::verify(), llvm::xray::BlockVerifier::verify(), verifyNoteSection(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::IHexSectionWriter::visit(), llvm::objcopy::elf::IHexSectionWriterBase::visit(), llvm::objcopy::elf::IHexSectionWriterBase::visit(), llvm::objcopy::elf::IHexSectionWriterBase::visit(), llvm::objcopy::elf::IHexSectionWriterBase::visit(), llvm::objcopy::elf::SectionWriter::visit(), llvm::objcopy::elf::SectionWriter::visit(), llvm::objcopy::elf::SectionWriter::visit(), llvm::objcopy::elf::SRECSectionWriter::visit(), llvm::objcopy::elf::SRECSectionWriterBase::visit(), llvm::objcopy::elf::SRECSectionWriterBase::visit(), llvm::objcopy::elf::SRECSectionWriterBase::visit(), llvm::objcopy::elf::SRECSectionWriterBase::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::RecordPrinter::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::TraceExpander::visit(), llvm::codeview::detail::visitDebugSubsections(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), llvm::logicalview::LVTypeVisitor::visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), llvm::DWARFDebugLoc::visitLocationList(), llvm::DWARFDebugLoclists::visitLocationList(), llvm::codeview::TypeDumpVisitor::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeVisitorCallbackPipeline::visitMemberBegin(), llvm::codeview::TypeVisitorCallbacks::visitMemberBegin(), llvm::logicalview::LVTypeVisitor::visitMemberBegin(), llvm::codeview::FieldListDeserializer::visitMemberEnd(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::TypeVisitorCallbackPipeline::visitMemberEnd(), llvm::codeview::TypeVisitorCallbacks::visitMemberEnd(), llvm::logicalview::LVTypeVisitor::visitMemberEnd(), llvm::logicalview::LVLogicalVisitor::visitMemberRecord(), visitMemberRecord(), llvm::codeview::SymbolRecordMapping::visitSymbolBegin(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolBegin(), llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolBegin(), llvm::codeview::SymbolVisitorCallbacks::visitSymbolBegin(), llvm::codeview::SymbolVisitorCallbacks::visitSymbolBegin(), llvm::logicalview::LVSymbolVisitor::visitSymbolBegin(), llvm::codeview::SymbolRecordMapping::visitSymbolEnd(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolEnd(), llvm::codeview::SymbolVisitorCallbacks::visitSymbolEnd(), llvm::logicalview::LVSymbolVisitor::visitSymbolEnd(), llvm::codeview::CVSymbolVisitor::visitSymbolStream(), llvm::codeview::CVSymbolVisitor::visitSymbolStream(), llvm::codeview::CVSymbolVisitor::visitSymbolStreamFiltered(), llvm::codeview::TypeDumpVisitor::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeVisitorCallbackPipeline::visitTypeBegin(), llvm::codeview::TypeVisitorCallbackPipeline::visitTypeBegin(), llvm::codeview::TypeVisitorCallbacks::visitTypeBegin(), llvm::codeview::TypeVisitorCallbacks::visitTypeBegin(), llvm::logicalview::LVTypeVisitor::visitTypeBegin(), llvm::codeview::TypeDumpVisitor::visitTypeEnd(), llvm::codeview::TypeRecordMapping::visitTypeEnd(), llvm::codeview::TypeVisitorCallbackPipeline::visitTypeEnd(), llvm::codeview::TypeVisitorCallbacks::visitTypeEnd(), llvm::codeview::DebugSubsectionVisitor::visitUnknown(), llvm::codeview::TypeDumpVisitor::visitUnknownMember(), llvm::codeview::TypeVisitorCallbackPipeline::visitUnknownMember(), llvm::codeview::TypeVisitorCallbacks::visitUnknownMember(), llvm::logicalview::LVLogicalVisitor::visitUnknownMember(), llvm::logicalview::LVTypeVisitor::visitUnknownMember(), llvm::codeview::SymbolVisitorCallbackPipeline::visitUnknownSymbol(), llvm::codeview::SymbolVisitorCallbacks::visitUnknownSymbol(), llvm::logicalview::LVSymbolVisitor::visitUnknownSymbol(), llvm::codeview::TypeDumpVisitor::visitUnknownType(), llvm::codeview::TypeVisitorCallbackPipeline::visitUnknownType(), llvm::codeview::TypeVisitorCallbacks::visitUnknownType(), llvm::logicalview::LVLogicalVisitor::visitUnknownType(), llvm::logicalview::LVTypeVisitor::visitUnknownType(), llvm::lto::ThinBackendProc::wait(), llvm::orc::walkLibunwindEHFrameSection(), llvm::orc::ResourceTracker::withResourceKeyDo(), llvm::offloading::wrapCudaBinary(), llvm::offloading::wrapHIPBinary(), llvm::offloading::wrapOpenMPBinaries(), llvm::objcopy::elf::BinaryWriter::write(), llvm::objcopy::elf::ELFWriter< ELFT >::write(), llvm::objcopy::elf::IHexWriter::write(), llvm::objcopy::elf::SRECWriter::write(), llvm::objcopy::macho::MachOWriter::write(), llvm::objcopy::wasm::Writer::write(), llvm::objcopy::xcoff::XCOFFWriter::write(), llvm::write(), llvm::writeArchiveToStream(), llvm::BinaryStreamWriter::writeArray(), llvm::orc::InProcessMemoryAccess::writeBuffersAsync(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::BinaryStreamWriter::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), llvm::BinaryStreamWriter::writeCString(), writeDWARFLists(), llvm::ifs::writeELFBinaryToFile(), llvm::ifs::writeIFSToOutputStream(), llvm::object::writeImportLibrary(), writeListEntry(), writeListEntryAddress(), llvm::writeMemProfRadixTreeBased(), llvm::writeMemProfV2(), llvm::jitlink::aarch64::writeMovRegImm64Seq(), llvm::jitlink::aarch64::writeMovRegRegSeq(), llvm::orc::InProcessMemoryAccess::writePointersAsync(), writePublics(), llvm::pdb::writeSparseBitVector(), llvm::BinaryStreamWriter::writeStreamRef(), llvm::CodeGenDataWriter::writeText(), llvm::InstrProfWriter::writeText(), llvm::MachO::TextAPIWriter::writeToStream(), llvm::orc::InProcessMemoryAccess::writeUInt16sAsync(), llvm::orc::InProcessMemoryAccess::writeUInt32sAsync(), llvm::orc::InProcessMemoryAccess::writeUInt64sAsync(), llvm::orc::InProcessMemoryAccess::writeUInt8sAsync(), writeUniversalArchsToStream(), llvm::jitlink::CompactUnwindManager< CURecTraits >::writeUnwindInfo(), writeVariableSizedInteger(), llvm::object::writeWindowsResourceCOFF(), llvm::orc::EPCGenericRTDyldMemoryManager::~EPCGenericRTDyldMemoryManager(), and llvm::ErrorAsOutParameter::~ErrorAsOutParameter().
Friends And Related Symbol Documentation
ErrorList
friend class ErrorList friend
Definition at line 163 of file Error.h.
References E(), Error(), ErrorList, H, handleErrors, and visitErrors.
Referenced by ErrorList, handleErrors, and visitErrors.
Expected
template<typename T> friend class Expected friend
Definition at line 174 of file Error.h.
References Error(), and Expected.
Referenced by Expected.
handleErrors
template<typename... HandlerTs> Error handleErrors (Error E, HandlerTs &&... Handlers) friend
Pass the ErrorInfo(s) contained in E to their respective handlers.
Any unhandled errors (or Errors returned by handlers) are re-concatenated and returned. Because this function returns an error, its result must also be checked or returned. If you intend to handle all errors use handleAllErrors (which returns void, and will abort() on unhandled errors) instead.
Definition at line 967 of file Error.h.
References E(), Error(), ErrorList, llvm::handleErrorImpl(), llvm::List, P, and success().
Referenced by ErrorList.
operator<<
raw_ostream & operator<< (raw_ostream & OS, const Error & E) friend
Definition at line 320 of file Error.h.
References E(), Error(), and P.
visitErrors
template<typename HandlerT> void visitErrors (const Error & E, HandlerT H) friend
Visit all the ErrorInfo(s) contained in E by passing them to the respective handler, without consuming the error.
Definition at line 1002 of file Error.h.
References E(), Error(), ErrorList, H, llvm::List, and P.
Referenced by ErrorList.
wrap
LLVMErrorRef wrap (Error Err) friend
Conversion from Error to LLVMErrorRef for C error bindings.
Definition at line 1490 of file Error.h.
References Error(), and llvm::release.
The documentation for this class was generated from the following file:
include/llvm/Support/Error.h