LLVM: llvm::jitlink::aarch64::GOTTableManager Class Reference
llvm::jitlink::aarch64::GOTTableManager Class Reference
Global Offset Table Builder.
#include "llvm/ExecutionEngine/JITLink/aarch64.h"
Public Member Functions
GOTTableManager (LinkGraph &G)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< GOTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Detailed Description
Global Offset Table Builder.
Definition at line 786 of file aarch64.h.
Constructor & Destructor Documentation
GOTTableManager()
llvm::jitlink::aarch64::GOTTableManager::GOTTableManager (LinkGraph & G) inline
Definition at line 790 of file aarch64.h.
References G, and getSectionName().
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::aarch64::GOTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 845 of file aarch64.h.
References llvm::jitlink::aarch64::createAnonymousPointer(), and G.
getSectionName()
StringRef llvm::jitlink::aarch64::GOTTableManager::getSectionName () inline static
Definition at line 788 of file aarch64.h.
Referenced by GOTTableManager().
visitEdge()
bool llvm::jitlink::aarch64::GOTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 795 of file aarch64.h.
References assert(), B(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::jitlink::aarch64::Delta32, E(), llvm::formatv(), G, llvm::jitlink::TableManager< GOTTableManager >::getEntryForTarget(), llvm::jitlink::aarch64::GotPageOffset15, llvm::jitlink::aarch64::Page21, llvm::jitlink::aarch64::PageOffset12, llvm::jitlink::aarch64::RequestGOTAndTransformToDelta32, llvm::jitlink::aarch64::RequestGOTAndTransformToPage21, llvm::jitlink::aarch64::RequestGOTAndTransformToPageOffset12, llvm::jitlink::aarch64::RequestGOTAndTransformToPageOffset15, llvm::jitlink::aarch64::RequestTLVPAndTransformToPage21, and llvm::jitlink::aarch64::RequestTLVPAndTransformToPageOffset12.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/aarch64.h
lib/ExecutionEngine/JITLink/aarch64.cpp