LLVM: llvm::EquivalenceClasses< ElemTy >::member_iterator Class Reference
llvm::EquivalenceClasses< ElemTy >::member_iterator Class Reference
#include "llvm/ADT/EquivalenceClasses.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = const ElemTy
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
member_iterator ()=default
member_iterator (const ECValue *N)
reference operator* () const
pointer operator-> () const
member_iterator & operator++ ()
member_iterator operator++ (int)
bool operator== (const member_iterator &RHS) const
bool operator!= (const member_iterator &RHS) const
Friends
class EquivalenceClasses
Detailed Description
template<class ElemTy>
class llvm::EquivalenceClasses< ElemTy >::member_iterator
Definition at line 333 of file EquivalenceClasses.h.
Member Typedef Documentation
difference_type
template<class ElemTy> using llvm::EquivalenceClasses< ElemTy >::member_iterator::difference_type = std::ptrdiff_t
Definition at line 342 of file EquivalenceClasses.h.
iterator_category
template<class ElemTy> using llvm::EquivalenceClasses< ElemTy >::member_iterator::iterator_category = std::forward_iterator_tag
Definition at line 339 of file EquivalenceClasses.h.
pointer
template<class ElemTy> using llvm::EquivalenceClasses< ElemTy >::member_iterator::pointer = value_type *
Definition at line 343 of file EquivalenceClasses.h.
reference
template<class ElemTy> using llvm::EquivalenceClasses< ElemTy >::member_iterator::reference = value_type &
Definition at line 344 of file EquivalenceClasses.h.
size_type
template<class ElemTy> using llvm::EquivalenceClasses< ElemTy >::member_iterator::size_type = std::size_t
Definition at line 341 of file EquivalenceClasses.h.
value_type
template<class ElemTy> using llvm::EquivalenceClasses< ElemTy >::member_iterator::value_type = const ElemTy
Definition at line 340 of file EquivalenceClasses.h.
Constructor & Destructor Documentation
member_iterator() [1/2]
template<class ElemTy> llvm::EquivalenceClasses< ElemTy >::member_iterator::member_iterator () explicit default
Referenced by operator!=(), operator++(), operator++(), and operator==().
member_iterator() [2/2]
template<class ElemTy> llvm::EquivalenceClasses< ElemTy >::member_iterator::member_iterator (const ECValue * N) inline explicit
Definition at line 347 of file EquivalenceClasses.h.
References N.
Member Function Documentation
operator!=()
template<class ElemTy> bool llvm::EquivalenceClasses< ElemTy >::member_iterator::operator!= (const member_iterator & RHS) const inline
Definition at line 370 of file EquivalenceClasses.h.
References member_iterator(), and RHS.
operator*()
template<class ElemTy> reference llvm::EquivalenceClasses< ElemTy >::member_iterator::operator* () const inline
Definition at line 349 of file EquivalenceClasses.h.
References assert().
Referenced by operator->().
operator++() [1/2]
template<class ElemTy> member_iterator & llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++ () inline
Definition at line 355 of file EquivalenceClasses.h.
References assert(), and member_iterator().
operator++() [2/2]
template<class ElemTy> member_iterator llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++ (int) inline
Definition at line 361 of file EquivalenceClasses.h.
References member_iterator().
operator->()
template<class ElemTy> pointer llvm::EquivalenceClasses< ElemTy >::member_iterator::operator-> () const inline
Definition at line 353 of file EquivalenceClasses.h.
References operator*().
operator==()
template<class ElemTy> bool llvm::EquivalenceClasses< ElemTy >::member_iterator::operator== (const member_iterator & RHS) const inline
Definition at line 367 of file EquivalenceClasses.h.
References member_iterator(), and RHS.
Friends And Related Symbol Documentation
EquivalenceClasses
template<class ElemTy> friend class EquivalenceClasses friend
Definition at line 334 of file EquivalenceClasses.h.
References EquivalenceClasses.
Referenced by EquivalenceClasses.
The documentation for this class was generated from the following file:
include/llvm/ADT/EquivalenceClasses.h