LLVM: llvm::mustache::Template Class Reference
llvm::mustache::Template Class Reference
#include "llvm/Support/Mustache.h"
Public Member Functions
LLVM_ABI Template (StringRef TemplateStr)
Template (const Template &)=delete
Template & operator= (const Template &)=delete
LLVM_ABI Template (Template &&Other) noexcept
LLVM_ABI ~Template ()
LLVM_ABI Template & operator= (Template &&Other) noexcept
LLVM_ABI void render (const llvm::json::Value &Data, llvm::raw_ostream &OS)
LLVM_ABI void registerPartial (std::string Name, std::string Partial)
LLVM_ABI void registerLambda (std::string Name, Lambda Lambda)
LLVM_ABI void registerLambda (std::string Name, SectionLambda Lambda)
LLVM_ABI void overrideEscapeCharacters (DenseMap< char, std::string > Escapes)
Detailed Description
Definition at line 91 of file Mustache.h.
Constructor & Destructor Documentation
Template() [1/3]
llvm::mustache::Template::Template (StringRef TemplateStr)
Definition at line 738 of file Mustache.cpp.
References overrideEscapeCharacters(), and P.
Referenced by operator=(), operator=(), Template(), Template(), and ~Template().
Template() [2/3]
llvm::mustache::Template::Template (const Template &) delete
References Template().
Template() [3/3]
llvm::mustache::Template::Template (Template && Other) noexcept
Definition at line 750 of file Mustache.cpp.
References llvm::Other, and Template().
~Template()
llvm::mustache::Template::~Template () default
References llvm::Data, LLVM_ABI, llvm::Other, and Template().
Member Function Documentation
operator=() [1/2]
Template & llvm::mustache::Template::operator= (const Template &) delete
References LLVM_ABI, llvm::Other, and Template().
operator=() [2/2]
Template & llvm::mustache::Template::operator= (Template && Other) noexcept
Definition at line 757 of file Mustache.cpp.
References llvm::Other, and Template().
overrideEscapeCharacters()
void llvm::mustache::Template::overrideEscapeCharacters (DenseMap< char, std::string > Escapes)
Definition at line 736 of file Mustache.cpp.
Referenced by Template().
registerLambda() [1/2]
void llvm::mustache::Template::registerLambda (std::string Name, Lambda Lambda)
Definition at line 730 of file Mustache.cpp.
registerLambda() [2/2]
void llvm::mustache::Template::registerLambda (std::string Name, SectionLambda Lambda)
Definition at line 732 of file Mustache.cpp.
registerPartial()
void llvm::mustache::Template::registerPartial (std::string Name, std::string Partial)
Definition at line 724 of file Mustache.cpp.
References P.
render()
void llvm::mustache::Template::render (const llvm::json::Value & Data, llvm::raw_ostream & OS)
Definition at line 720 of file Mustache.cpp.
References llvm::Data.
The documentation for this class was generated from the following files:
include/llvm/Support/Mustache.h
lib/Support/Mustache.cpp