LLVM: llvm::LoongArchTargetELFStreamer Class Reference
llvm::LoongArchTargetELFStreamer Class Reference
#include "Target/LoongArch/MCTargetDesc/LoongArchELFStreamer.h"
Public Member Functions
MCELFStreamer & getStreamer ()
LoongArchTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
void emitDirectiveOptionPush () override
void emitDirectiveOptionPop () override
void emitDirectiveOptionRelax () override
void emitDirectiveOptionNoRelax () override
void finish () override
Public Member Functions inherited from llvm::LoongArchTargetStreamer
LoongArchTargetStreamer (MCStreamer &S)
void setTargetABI (LoongArchABI::ABI ABI)
LoongArchABI::ABI getTargetABI () const
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 17 of file LoongArchELFStreamer.h.
Constructor & Destructor Documentation
LoongArchTargetELFStreamer()
LoongArchTargetELFStreamer::LoongArchTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 24 of file LoongArchELFStreamer.cpp.
References llvm::LoongArchABI::computeTargetABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCSubtargetInfo::getFeatureBits(), getStreamer(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::LoongArchTargetStreamer::LoongArchTargetStreamer(), and llvm::LoongArchTargetStreamer::setTargetABI().
Member Function Documentation
emitDirectiveOptionNoRelax()
void LoongArchTargetELFStreamer::emitDirectiveOptionNoRelax () override virtual
Reimplemented from llvm::LoongArchTargetStreamer.
Definition at line 41 of file LoongArchELFStreamer.cpp.
emitDirectiveOptionPop()
void LoongArchTargetELFStreamer::emitDirectiveOptionPop () override virtual
Reimplemented from llvm::LoongArchTargetStreamer.
Definition at line 39 of file LoongArchELFStreamer.cpp.
emitDirectiveOptionPush()
void LoongArchTargetELFStreamer::emitDirectiveOptionPush () override virtual
Reimplemented from llvm::LoongArchTargetStreamer.
Definition at line 38 of file LoongArchELFStreamer.cpp.
emitDirectiveOptionRelax()
void LoongArchTargetELFStreamer::emitDirectiveOptionRelax () override virtual
Reimplemented from llvm::LoongArchTargetStreamer.
Definition at line 40 of file LoongArchELFStreamer.cpp.
finish()
void LoongArchTargetELFStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 43 of file LoongArchELFStreamer.cpp.
References llvm::LoongArchABI::ABI_ILP32D, llvm::LoongArchABI::ABI_ILP32F, llvm::LoongArchABI::ABI_ILP32S, llvm::LoongArchABI::ABI_LP64D, llvm::LoongArchABI::ABI_LP64F, llvm::LoongArchABI::ABI_LP64S, llvm::LoongArchABI::ABI_Unknown, llvm::ELF::EF_LOONGARCH_ABI_DOUBLE_FLOAT, llvm::ELF::EF_LOONGARCH_ABI_SINGLE_FLOAT, llvm::ELF::EF_LOONGARCH_ABI_SOFT_FLOAT, llvm::ELF::EF_LOONGARCH_OBJABI_V1, llvm::MCTargetStreamer::finish(), getStreamer(), llvm::LoongArchTargetStreamer::getTargetABI(), llvm::MCELFStreamer::getWriter(), and llvm_unreachable.
getStreamer()
MCELFStreamer & LoongArchTargetELFStreamer::getStreamer ()
Definition at line 34 of file LoongArchELFStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by finish(), and LoongArchTargetELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/LoongArch/MCTargetDesc/LoongArchELFStreamer.h
lib/Target/LoongArch/MCTargetDesc/LoongArchELFStreamer.cpp