LLVM: llvm::VirtRegRewriterPass Class Reference
llvm::VirtRegRewriterPass Class Reference
#include "llvm/CodeGen/VirtRegMap.h"
Public Member Functions
VirtRegRewriterPass (bool ClearVirtRegs=true)
LLVM_ABI PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
LLVM_ABI void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)>) const
MachineFunctionProperties getSetProperties () const
Public Member Functions inherited from llvm::PassInfoMixin< VirtRegRewriterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< VirtRegRewriterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 241 of file VirtRegMap.h.
Constructor & Destructor Documentation
VirtRegRewriterPass()
llvm::VirtRegRewriterPass::VirtRegRewriterPass (bool ClearVirtRegs = true) inline
Definition at line 245 of file VirtRegMap.h.
Member Function Documentation
getSetProperties()
MachineFunctionProperties llvm::VirtRegRewriterPass::getSetProperties () const inline
Definition at line 255 of file VirtRegMap.h.
References llvm::MachineFunctionProperties::NoVRegs, and llvm::MachineFunctionProperties::set().
isRequired()
bool llvm::VirtRegRewriterPass::isRequired () inline static
Definition at line 250 of file VirtRegMap.h.
printPipeline()
void VirtRegRewriterPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)>) const
Definition at line 775 of file VirtRegMap.cpp.
run()
PreservedAnalyses VirtRegRewriterPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 302 of file VirtRegMap.cpp.
References _, llvm::PreservedAnalyses::all(), llvm::getMachineFunctionPassPreservedAnalyses(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/VirtRegMap.h
lib/CodeGen/VirtRegMap.cpp