LLVM: llvm::TargetFolder Class Reference
llvm::TargetFolder Class Reference final
TargetFolder - Create constants with target dependent folding.
#include "llvm/Analysis/TargetFolder.h"
Public Member Functions
TargetFolder (const DataLayout &DL)
Value * FoldBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS) const override
Value * FoldExactBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool IsExact) const override
Value * FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool HasNUW, bool HasNSW) const override
Value * FoldBinOpFMF (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, FastMathFlags FMF) const override
Value * FoldCmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const override
Value * FoldUnOpFMF (Instruction::UnaryOps Opc, Value *V, FastMathFlags FMF) const override
Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, GEPNoWrapFlags NW) const override
Value * FoldSelect (Value *C, Value *True, Value *False) const override
Value * FoldExtractValue (Value *Agg, ArrayRef< unsigned > IdxList) const override
Value * FoldInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > IdxList) const override
Value * FoldExtractElement (Value *Vec, Value *Idx) const override
Value * FoldInsertElement (Value *Vec, Value *NewElt, Value *Idx) const override
Value * FoldShuffleVector (Value *V1, Value *V2, ArrayRef< int > Mask) const override
Value * FoldCast (Instruction::CastOps Op, Value *V, Type *DestTy) const override
Value * FoldBinaryIntrinsic (Intrinsic::ID ID, Value *LHS, Value *RHS, Type *Ty, Instruction *FMFSource) const override
Constant * CreatePointerCast (Constant *C, Type *DestTy) const override
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
TargetFolder - Create constants with target dependent folding.
Definition at line 35 of file TargetFolder.h.
Constructor & Destructor Documentation
TargetFolder()
llvm::TargetFolder::TargetFolder (const DataLayout & DL) inline explicit
Definition at line 46 of file TargetFolder.h.
Member Function Documentation
CreatePointerBitCastOrAddrSpaceCast()
Constant * llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 211 of file TargetFolder.h.
References llvm::CallingConv::C, and llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Constant * llvm::TargetFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 205 of file TargetFolder.h.
References llvm::CallingConv::C, and llvm::ConstantExpr::getPointerCast().
FoldBinaryIntrinsic()
Value * llvm::TargetFolder::FoldBinaryIntrinsic (Intrinsic::ID ID, Value * LHS, Value * RHS, Type * Ty, Instruction * FMFSource) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 192 of file TargetFolder.h.
References llvm::ConstantFoldBinaryIntrinsic(), llvm::dyn_cast(), LHS, and RHS.
FoldBinOp()
Value * llvm::TargetFolder::FoldBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 55 of file TargetFolder.h.
References llvm::ConstantFoldBinaryOpOperands(), llvm::dyn_cast(), llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), LHS, Opc, and RHS.
Referenced by FoldBinOpFMF().
FoldBinOpFMF()
Value * llvm::TargetFolder::FoldBinOpFMF (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 98 of file TargetFolder.h.
References FoldBinOp(), LHS, Opc, and RHS.
FoldCast()
Value * llvm::TargetFolder::FoldCast (Instruction::CastOps Op, Value * V, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 185 of file TargetFolder.h.
References llvm::CallingConv::C, llvm::ConstantFoldCastOperand(), and llvm::dyn_cast().
FoldCmp()
Value * llvm::TargetFolder::FoldCmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 103 of file TargetFolder.h.
References llvm::ConstantFoldCompareInstOperands(), llvm::dyn_cast(), LHS, P, and RHS.
FoldExactBinOp()
Value * llvm::TargetFolder::FoldExactBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool IsExact) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 67 of file TargetFolder.h.
References llvm::ConstantFoldBinaryOpOperands(), llvm::dyn_cast(), llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), llvm::PossiblyExactOperator::IsExact, LHS, Opc, and RHS.
FoldExtractElement()
Value * llvm::TargetFolder::FoldExtractElement (Value * Vec, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 158 of file TargetFolder.h.
References llvm::dyn_cast(), and llvm::ConstantExpr::getExtractElement().
FoldExtractValue()
Value * llvm::TargetFolder::FoldExtractValue (Value * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 142 of file TargetFolder.h.
References llvm::ConstantFoldExtractValueInstruction(), and llvm::dyn_cast().
FoldGEP()
Value * llvm::TargetFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, GEPNoWrapFlags NW) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 118 of file TargetFolder.h.
References llvm::any_of(), llvm::dyn_cast(), llvm::ConstantExpr::getGetElementPtr(), llvm::isa(), llvm::ConstantExpr::isSupportedGetElementPtr(), and Ptr.
FoldInsertElement()
Value * llvm::TargetFolder::FoldInsertElement (Value * Vec, Value * NewElt, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 166 of file TargetFolder.h.
References llvm::dyn_cast(), and llvm::ConstantExpr::getInsertElement().
FoldInsertValue()
Value * llvm::TargetFolder::FoldInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 149 of file TargetFolder.h.
References llvm::ConstantFoldInsertValueInstruction(), and llvm::dyn_cast().
FoldNoWrapBinOp()
Value * llvm::TargetFolder::FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool HasNUW, bool HasNSW) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 80 of file TargetFolder.h.
References llvm::ConstantFoldBinaryOpOperands(), llvm::dyn_cast(), llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, Opc, and RHS.
FoldSelect()
Value * llvm::TargetFolder::FoldSelect (Value * C, Value * True, Value * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 132 of file TargetFolder.h.
References llvm::CallingConv::C, llvm::ConstantFoldSelectInstruction(), and llvm::dyn_cast().
FoldShuffleVector()
Value * llvm::TargetFolder::FoldShuffleVector (Value * V1, Value * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 176 of file TargetFolder.h.
References llvm::dyn_cast(), and llvm::ConstantExpr::getShuffleVector().
FoldUnOpFMF()
Value * llvm::TargetFolder::FoldUnOpFMF (Instruction::UnaryOps Opc, Value * V, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 111 of file TargetFolder.h.
References llvm::CallingConv::C, llvm::ConstantFoldUnaryOpOperand(), llvm::dyn_cast(), and Opc.
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetFolder.h