LLVM: llvm::sandboxir::GlobalObject Class Reference
llvm::sandboxir::GlobalObject Class Reference
#include "llvm/SandboxIR/Constant.h"
Public Types
using VCallVisibility = llvm::GlobalObject::VCallVisibility
Public Types inherited from llvm::sandboxir::GlobalValue
using LinkageTypes = llvm::GlobalValue::LinkageTypes
using UnnamedAddr = llvm::GlobalValue::UnnamedAddr
using VisibilityTypes = llvm::GlobalValue::VisibilityTypes
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Public Member Functions
unsigned getUseOperandNo (const Use &Use) const final
\Returns the operand index of Use.
bool hasSection () const
Check if this global has a custom object file section.
StringRef getSection () const
Get the custom section of this global if it has one.
LLVM_ABI void setSection (StringRef S)
Change the section for this global.
bool hasComdat () const
VCallVisibility getVCallVisibility () const
bool canIncreaseAlignment () const
Returns true if the alignment of the value can be unilaterally increased.
Public Member Functions inherited from llvm::sandboxir::GlobalValue
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
LLVM_ABI void setUnnamedAddr (UnnamedAddr V)
bool hasComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
LLVM_ABI void setVisibility (VisibilityTypes V)
Public Member Functions inherited from llvm::sandboxir::Constant
sandboxir::Context & getParent () const
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::GlobalValue
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
Static Public Member Functions inherited from llvm::sandboxir::Constant
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Protected Member Functions
GlobalObject (ClassID ID, llvm::GlobalObject *C, Context &Ctx)
Use getOperandUseInternal (unsigned OpIdx, bool Verify) const final
\Returns the Use for the OpIdx'th operand.
Protected Member Functions inherited from llvm::sandboxir::GlobalValue
GlobalValue (ClassID ID, llvm::GlobalValue *C, Context &Ctx)
Protected Member Functions inherited from llvm::sandboxir::Constant
Constant (llvm::Constant *C, sandboxir::Context &SBCtx)
Constant (ClassID ID, llvm::Constant *C, sandboxir::Context &SBCtx)
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Friends
class Context
Additional Inherited Members
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 956 of file Constant.h.
Member Typedef Documentation
VCallVisibility
using llvm::sandboxir::GlobalObject::VCallVisibility = llvm::GlobalObject::VCallVisibility
Definition at line 1010 of file Constant.h.
Constructor & Destructor Documentation
GlobalObject()
llvm::sandboxir::GlobalObject::GlobalObject (ClassID ID, llvm::GlobalObject * C, Context & Ctx) inline protected
Definition at line 958 of file Constant.h.
References llvm::CallingConv::C, Context, llvm::sandboxir::Value::Ctx, and llvm::sandboxir::GlobalValue::GlobalValue().
Member Function Documentation
canIncreaseAlignment()
bool llvm::sandboxir::GlobalObject::canIncreaseAlignment () const inline
Returns true if the alignment of the value can be unilaterally increased.
Note that for functions this is the alignment of the code, not the alignment of a function pointer.
Definition at line 1021 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
classof()
bool llvm::sandboxir::GlobalObject::classof (const sandboxir::Value * From) inline static
For isa/dyn_cast.
Definition at line 970 of file Constant.h.
References llvm::sandboxir::Value::getSubclassID().
getOperandUseInternal()
Use llvm::sandboxir::GlobalObject::getOperandUseInternal (unsigned OpIdx, bool Verify) const inline final protected virtual
\Returns the Use for the OpIdx'th operand.
This is virtual to allow instructions to deviate from the LLVM IR operands, which is a requirement for sandboxir Instructions that consist of more than one LLVM Instruction.
Reimplemented from llvm::sandboxir::Constant.
Definition at line 961 of file Constant.h.
References llvm::sandboxir::User::getOperandUseDefault(), OpIdx, and Verify.
getSection()
StringRef llvm::sandboxir::GlobalObject::getSection () const inline
Get the custom section of this global if it has one.
If this global does not have a custom section, this will be empty and the default object file section (.text, .data, etc) will be used.
Definition at line 993 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getUseOperandNo()
unsigned llvm::sandboxir::GlobalObject::getUseOperandNo (const Use & Use) const inline final virtual
\Returns the operand index of Use.
Reimplemented from llvm::sandboxir::Constant.
Definition at line 966 of file Constant.h.
References llvm::sandboxir::User::getUseOperandNoDefault().
getVCallVisibility()
VCallVisibility llvm::sandboxir::GlobalObject::getVCallVisibility () const inline
Definition at line 1012 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasComdat()
bool llvm::sandboxir::GlobalObject::hasComdat () const inline
Definition at line 1003 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasSection()
bool llvm::sandboxir::GlobalObject::hasSection () const inline
Check if this global has a custom object file section.
This is more efficient than calling getSection() and checking for an empty string.
Definition at line 985 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
setSection()
void llvm::sandboxir::GlobalObject::setSection (StringRef S)
Change the section for this global.
Setting the section to the empty string tells LLVM to choose an appropriate default object file section.
Definition at line 292 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 960 of file Constant.h.
References Context.
Referenced by Context, and GlobalObject().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Constant.h
lib/SandboxIR/Constant.cpp