LLVM: llvm::codeview::DebugSubsection Class Reference
llvm::codeview::DebugSubsection Class Reference abstract
#include "llvm/DebugInfo/CodeView/DebugSubsection.h"
Public Member Functions
DebugSubsection (DebugSubsectionKind Kind)
virtual ~DebugSubsection ()
DebugSubsectionKind kind () const
virtual Error commit (BinaryStreamWriter &Writer) const =0
virtual uint32_t calculateSerializedSize () const =0
Static Public Member Functions
static bool classof (const DebugSubsection *S)
Protected Attributes
DebugSubsectionKind Kind
Detailed Description
Definition at line 35 of file DebugSubsection.h.
Constructor & Destructor Documentation
DebugSubsection()
llvm::codeview::DebugSubsection::DebugSubsection (DebugSubsectionKind Kind) inline explicit
Definition at line 37 of file DebugSubsection.h.
References Kind.
Referenced by llvm::codeview::DebugChecksumsSubsection::classof(), llvm::codeview::DebugCrossModuleExportsSubsection::classof(), llvm::codeview::DebugCrossModuleImportsSubsection::classof(), llvm::codeview::DebugFrameDataSubsection::classof(), llvm::codeview::DebugInlineeLinesSubsection::classof(), llvm::codeview::DebugLinesSubsection::classof(), llvm::codeview::DebugStringTableSubsection::classof(), classof(), llvm::codeview::DebugSymbolRVASubsection::classof(), llvm::codeview::DebugSymbolsSubsection::classof(), llvm::codeview::DebugChecksumsSubsection::DebugChecksumsSubsection(), llvm::codeview::DebugCrossModuleExportsSubsection::DebugCrossModuleExportsSubsection(), llvm::codeview::DebugCrossModuleImportsSubsection::DebugCrossModuleImportsSubsection(), llvm::codeview::DebugFrameDataSubsection::DebugFrameDataSubsection(), llvm::codeview::DebugInlineeLinesSubsection::DebugInlineeLinesSubsection(), llvm::codeview::DebugLinesSubsection::DebugLinesSubsection(), llvm::codeview::DebugStringTableSubsection::DebugStringTableSubsection(), llvm::codeview::DebugSymbolRVASubsection::DebugSymbolRVASubsection(), and llvm::codeview::DebugSymbolsSubsection::DebugSymbolsSubsection().
~DebugSubsection()
DebugSubsection::~DebugSubsection () virtual default
Member Function Documentation
calculateSerializedSize()
virtual uint32_t llvm::codeview::DebugSubsection::calculateSerializedSize () const pure virtual
Implemented in llvm::codeview::DebugChecksumsSubsection, llvm::codeview::DebugCrossModuleExportsSubsection, llvm::codeview::DebugCrossModuleImportsSubsection, llvm::codeview::DebugFrameDataSubsection, llvm::codeview::DebugInlineeLinesSubsection, llvm::codeview::DebugLinesSubsection, llvm::codeview::DebugStringTableSubsection, llvm::codeview::DebugSymbolRVASubsection, and llvm::codeview::DebugSymbolsSubsection.
classof()
bool llvm::codeview::DebugSubsection::classof (const DebugSubsection * S) inline static
Definition at line 40 of file DebugSubsection.h.
References DebugSubsection().
commit()
virtual Error llvm::codeview::DebugSubsection::commit (BinaryStreamWriter & Writer) const pure virtual
Implemented in llvm::codeview::DebugChecksumsSubsection, llvm::codeview::DebugCrossModuleExportsSubsection, llvm::codeview::DebugCrossModuleImportsSubsection, llvm::codeview::DebugFrameDataSubsection, llvm::codeview::DebugInlineeLinesSubsection, llvm::codeview::DebugLinesSubsection, llvm::codeview::DebugStringTableSubsection, llvm::codeview::DebugSymbolRVASubsection, and llvm::codeview::DebugSymbolsSubsection.
kind()
DebugSubsectionKind llvm::codeview::DebugSubsection::kind () const inline
Definition at line 42 of file DebugSubsection.h.
References Kind.
Referenced by llvm::codeview::DebugChecksumsSubsection::classof(), llvm::codeview::DebugCrossModuleExportsSubsection::classof(), llvm::codeview::DebugCrossModuleImportsSubsection::classof(), llvm::codeview::DebugFrameDataSubsection::classof(), llvm::codeview::DebugFrameDataSubsectionRef::classof(), llvm::codeview::DebugInlineeLinesSubsection::classof(), llvm::codeview::DebugLinesSubsection::classof(), llvm::codeview::DebugStringTableSubsection::classof(), llvm::codeview::DebugSymbolRVASubsection::classof(), and llvm::codeview::DebugSymbolsSubsection::classof().
Member Data Documentation
Kind
DebugSubsectionKind llvm::codeview::DebugSubsection::Kind protected
Definition at line 48 of file DebugSubsection.h.
Referenced by llvm::codeview::DebugChecksumsSubsection::addChecksum(), DebugSubsection(), and kind().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSubsection.h
lib/DebugInfo/CodeView/DebugSubsection.cpp