LLVM: llvm::IVUsersPrinterPass Class Reference
llvm::IVUsersPrinterPass Class Reference
Printer pass for the IVUsers for a loop.
#include "llvm/Transforms/Scalar/IVUsersPrinter.h"
Public Member Functions
IVUsersPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< IVUsersPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< IVUsersPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the IVUsers for a loop.
Definition at line 21 of file IVUsersPrinter.h.
Constructor & Destructor Documentation
IVUsersPrinterPass()
llvm::IVUsersPrinterPass::IVUsersPrinterPass (raw_ostream & OS) inline explicit
Definition at line 25 of file IVUsersPrinter.h.
Member Function Documentation
isRequired()
bool llvm::IVUsersPrinterPass::isRequired () inline static
Definition at line 28 of file IVUsersPrinter.h.
run()
PreservedAnalyses IVUsersPrinterPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 15 of file IVUsersPrinter.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::print().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/IVUsersPrinter.h
lib/Transforms/Scalar/IVUsersPrinter.cpp