LLVM: llvm::OpenMPIRBuilder::AtomicInfo Class Reference
llvm::OpenMPIRBuilder::AtomicInfo Class Reference
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
Public Member Functions
AtomicInfo (IRBuilder<> *Builder, llvm::Type *Ty, uint64_t AtomicSizeInBits, uint64_t ValueSizeInBits, llvm::Align AtomicAlign, llvm::Align ValueAlign, bool UseLibcall, IRBuilderBase::InsertPoint AllocaIP, llvm::Value *AtomicVar)
llvm::Value * getAtomicPointer () const override
void decorateWithTBAA (llvm::Instruction *I) override
llvm::AllocaInst * CreateAlloca (llvm::Type *Ty, const llvm::Twine &Name) const override
Public Member Functions inherited from llvm::AtomicInfo
AtomicInfo (IRBuilderBase *Builder, Type *Ty, uint64_t AtomicSizeInBits, uint64_t ValueSizeInBits, Align AtomicAlign, Align ValueAlign, bool UseLibcall, IRBuilderBase::InsertPoint AllocaIP)
virtual ~AtomicInfo ()=default
Align getAtomicAlignment () const
uint64_t getAtomicSizeInBits () const
uint64_t getValueSizeInBits () const
bool shouldUseLibcall () const
Type * getAtomicTy () const
bool hasPadding () const
LLVMContext & getLLVMContext () const
LLVM_ABI bool shouldCastToInt (Type *ValTy, bool CmpXchg)
LLVM_ABI Value * EmitAtomicLoadOp (AtomicOrdering AO, bool IsVolatile, bool CmpXchg=false)
LLVM_ABI CallInst * EmitAtomicLibcall (StringRef fnName, Type *ResultType, ArrayRef< Value * > Args)
Value * getAtomicSizeValue () const
LLVM_ABI std::pair< Value *, Value * > EmitAtomicCompareExchangeLibcall (Value *ExpectedVal, Value *DesiredVal, AtomicOrdering Success, AtomicOrdering Failure)
Value * castToAtomicIntPointer (Value *addr) const
Value * getAtomicAddressAsAtomicIntPointer () const
LLVM_ABI std::pair< Value *, Value * > EmitAtomicCompareExchangeOp (Value *ExpectedVal, Value *DesiredVal, AtomicOrdering Success, AtomicOrdering Failure, bool IsVolatile=false, bool IsWeak=false)
LLVM_ABI std::pair< Value *, Value * > EmitAtomicCompareExchange (Value *ExpectedVal, Value *DesiredVal, AtomicOrdering Success, AtomicOrdering Failure, bool IsVolatile, bool IsWeak)
LLVM_ABI std::pair< LoadInst *, AllocaInst * > EmitAtomicLoadLibcall (AtomicOrdering AO)
LLVM_ABI void EmitAtomicStoreLibcall (AtomicOrdering AO, Value *Source)
Additional Inherited Members
Protected Attributes inherited from llvm::AtomicInfo
IRBuilderBase * Builder
Type * Ty
uint64_t AtomicSizeInBits
uint64_t ValueSizeInBits
Align AtomicAlign
Align ValueAlign
bool UseLibcall
IRBuilderBase::InsertPoint AllocaIP
Detailed Description
Definition at line 493 of file OMPIRBuilder.h.
Constructor & Destructor Documentation
AtomicInfo()
llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo (IRBuilder<> * Builder, llvm::Type * Ty, uint64_t AtomicSizeInBits, uint64_t ValueSizeInBits, llvm::Align AtomicAlign, llvm::Align ValueAlign, bool UseLibcall, IRBuilderBase::InsertPoint AllocaIP, llvm::Value * AtomicVar) inline
Definition at line 497 of file OMPIRBuilder.h.
References llvm::AtomicInfo::AllocaIP, llvm::AtomicInfo::AtomicAlign, AtomicInfo(), llvm::AtomicInfo::AtomicSizeInBits, llvm::AtomicInfo::Builder, llvm::AtomicInfo::Ty, llvm::AtomicInfo::UseLibcall, llvm::AtomicInfo::ValueAlign, and llvm::AtomicInfo::ValueSizeInBits.
Referenced by AtomicInfo().
Member Function Documentation
CreateAlloca()
llvm::AllocaInst * llvm::OpenMPIRBuilder::AtomicInfo::CreateAlloca (llvm::Type * Ty, const llvm::Twine & Name) const inline override virtual
Implements llvm::AtomicInfo.
Definition at line 507 of file OMPIRBuilder.h.
References llvm::AtomicInfo::Builder, llvm::Value::setName(), and llvm::AtomicInfo::Ty.
decorateWithTBAA()
void llvm::OpenMPIRBuilder::AtomicInfo::decorateWithTBAA (llvm::Instruction * I) inline override virtual
Implements llvm::AtomicInfo.
Definition at line 506 of file OMPIRBuilder.h.
References I.
getAtomicPointer()
llvm::Value * llvm::OpenMPIRBuilder::AtomicInfo::getAtomicPointer () const inline override virtual
Implements llvm::AtomicInfo.
Definition at line 505 of file OMPIRBuilder.h.
The documentation for this class was generated from the following file:
include/llvm/Frontend/OpenMP/OMPIRBuilder.h