LLVM: llvm::SMEAttrs Class Reference
llvm::SMEAttrs Class Reference
SMEAttrs is a utility class to parse the SME ACLE attributes on functions.
#include "Target/AArch64/Utils/AArch64SMEAttributes.h"
Public Types
enum class StateValue {
None = 0 , In = 1 , Out = 2 , InOut = 3 ,
Preserved = 4 , New = 5
}
enum Mask {
Normal = 0 , SM_Enabled = 1 << 0 , SM_Compatible = 1 << 1 , SM_Body = 1 << 2 ,
SME_ABI_Routine = 1 << 3 , ZA_State_Agnostic = 1 << 4 , ZT0_Undef = 1 << 5 , ZA_Shift = 6 ,
ZA_Mask = 0b111 << ZA_Shift , ZT0_Shift = 9 , ZT0_Mask = 0b111 << ZT0_Shift , CallSiteFlags_Mask = ZT0_Undef
}
enum class InferAttrsFromName { No , Yes }
Public Member Functions
SMEAttrs ()=default
SMEAttrs (unsigned Mask)
SMEAttrs (const Function &F, InferAttrsFromName Infer=InferAttrsFromName::No)
SMEAttrs (const AttributeList &L)
SMEAttrs (StringRef FuncName)
void set (unsigned M, bool Enable=true)
bool hasStreamingBody () const
bool hasStreamingInterface () const
bool hasStreamingInterfaceOrBody () const
bool hasStreamingCompatibleInterface () const
bool hasNonStreamingInterface () const
bool hasNonStreamingInterfaceAndBody () const
bool isNewZA () const
bool isInZA () const
bool isOutZA () const
bool isInOutZA () const
bool isPreservesZA () const
bool sharesZA () const
bool hasAgnosticZAInterface () const
bool hasSharedZAInterface () const
bool hasPrivateZAInterface () const
bool hasZAState () const
bool isSMEABIRoutine () const
bool isNewZT0 () const
bool isInZT0 () const
bool isOutZT0 () const
bool isInOutZT0 () const
bool isPreservesZT0 () const
bool hasUndefZT0 () const
bool sharesZT0 () const
bool hasZT0State () const
SMEAttrs operator| (SMEAttrs Other) const
SMEAttrs withoutPerCallsiteFlags () const
bool operator== (SMEAttrs const &Other) const
Static Public Member Functions
static StateValue decodeZAState (unsigned Bitmask)
static unsigned encodeZAState (StateValue S)
static StateValue decodeZT0State (unsigned Bitmask)
static unsigned encodeZT0State (StateValue S)
Detailed Description
SMEAttrs is a utility class to parse the SME ACLE attributes on functions.
It helps determine a function's requirements for PSTATE.ZA and PSTATE.SM.
Definition at line 22 of file AArch64SMEAttributes.h.
Member Enumeration Documentation
InferAttrsFromName
enum class llvm::SMEAttrs::InferAttrsFromName strong
Enumerator
No
Yes
Definition at line 51 of file AArch64SMEAttributes.h.
Mask
enum llvm::SMEAttrs::Mask
Enumerator
Normal
SM_Enabled
SM_Compatible
SM_Body
SME_ABI_Routine
ZA_State_Agnostic
ZT0_Undef
ZA_Shift
ZA_Mask
ZT0_Shift
ZT0_Mask
CallSiteFlags_Mask
Definition at line 36 of file AArch64SMEAttributes.h.
StateValue
enum class llvm::SMEAttrs::StateValue strong
Enumerator
None
In
Out
InOut
Preserved
New
Definition at line 26 of file AArch64SMEAttributes.h.
Constructor & Destructor Documentation
SMEAttrs() [1/5]
llvm::SMEAttrs::SMEAttrs () default
Referenced by operator==(), operator|(), SMEAttrs(), and withoutPerCallsiteFlags().
SMEAttrs() [2/5]
llvm::SMEAttrs::SMEAttrs (unsigned Mask) inline
Definition at line 54 of file AArch64SMEAttributes.h.
References set().
SMEAttrs() [3/5]
llvm::SMEAttrs::SMEAttrs (const Function & F, InferAttrsFromName Infer = InferAttrsFromName::No) inline
Definition at line 55 of file AArch64SMEAttributes.h.
References F, No, SMEAttrs(), and Yes.
SMEAttrs() [4/5]
SMEAttrs::SMEAttrs (const AttributeList & L)
Definition at line 46 of file AArch64SMEAttributes.cpp.
References encodeZAState(), encodeZT0State(), In, InOut, New, Out, Preserved, SM_Body, SM_Compatible, SM_Enabled, ZA_State_Agnostic, and ZT0_Undef.
SMEAttrs() [5/5]
llvm::SMEAttrs::SMEAttrs (StringRef FuncName) inline
Definition at line 61 of file AArch64SMEAttributes.h.
Member Function Documentation
decodeZAState()
StateValue llvm::SMEAttrs::decodeZAState (unsigned Bitmask) inline static
Definition at line 82 of file AArch64SMEAttributes.h.
References ZA_Mask, and ZA_Shift.
Referenced by isInOutZA(), isInZA(), isNewZA(), isOutZA(), isPreservesZA(), and sharesZA().
decodeZT0State()
StateValue llvm::SMEAttrs::decodeZT0State (unsigned Bitmask) inline static
Definition at line 110 of file AArch64SMEAttributes.h.
References ZT0_Mask, and ZT0_Shift.
Referenced by isInOutZT0(), isInZT0(), isNewZT0(), isOutZT0(), isPreservesZT0(), and sharesZT0().
encodeZAState()
unsigned llvm::SMEAttrs::encodeZAState (StateValue S) inline static
Definition at line 85 of file AArch64SMEAttributes.h.
References ZA_Shift.
Referenced by SMEAttrs().
encodeZT0State()
unsigned llvm::SMEAttrs::encodeZT0State (StateValue S) inline static
Definition at line 113 of file AArch64SMEAttributes.h.
References ZT0_Shift.
Referenced by SMEAttrs().
hasAgnosticZAInterface()
bool llvm::SMEAttrs::hasAgnosticZAInterface () const inline
Definition at line 101 of file AArch64SMEAttributes.h.
References ZA_State_Agnostic.
Referenced by llvm::AArch64::createFastISel(), hasPrivateZAInterface(), llvm::SMECallAttrs::requiresPreservingAllZAState(), llvm::SMECallAttrs::requiresPreservingZT0(), and set().
hasNonStreamingInterface()
bool llvm::SMEAttrs::hasNonStreamingInterface () const inline
Definition at line 74 of file AArch64SMEAttributes.h.
References hasStreamingCompatibleInterface(), and hasStreamingInterface().
Referenced by getSMToggleCondition(), and hasNonStreamingInterfaceAndBody().
hasNonStreamingInterfaceAndBody()
bool llvm::SMEAttrs::hasNonStreamingInterfaceAndBody () const inline
Definition at line 77 of file AArch64SMEAttributes.h.
References hasNonStreamingInterface(), and hasStreamingBody().
hasPrivateZAInterface()
bool llvm::SMEAttrs::hasPrivateZAInterface () const inline
Definition at line 103 of file AArch64SMEAttributes.h.
References hasAgnosticZAInterface(), and hasSharedZAInterface().
Referenced by llvm::SMECallAttrs::requiresDisablingZABeforeCall(), and llvm::SMECallAttrs::requiresLazySave().
hasSharedZAInterface()
bool llvm::SMEAttrs::hasSharedZAInterface () const inline
Definition at line 102 of file AArch64SMEAttributes.h.
References sharesZA(), and sharesZT0().
Referenced by hasPrivateZAInterface(), and set().
hasStreamingBody()
bool llvm::SMEAttrs::hasStreamingBody () const inline
Definition at line 66 of file AArch64SMEAttributes.h.
References SM_Body.
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), enableMultiVectorSpillFill(), getSMToggleCondition(), hasNonStreamingInterfaceAndBody(), and hasStreamingInterfaceOrBody().
hasStreamingCompatibleInterface()
bool llvm::SMEAttrs::hasStreamingCompatibleInterface () const inline
Definition at line 71 of file AArch64SMEAttributes.h.
References SM_Compatible.
Referenced by llvm::AArch64::createFastISel(), getSMToggleCondition(), hasNonStreamingInterface(), instCombineInStreamingMode(), and set().
hasStreamingInterface()
bool llvm::SMEAttrs::hasStreamingInterface () const inline
Definition at line 67 of file AArch64SMEAttributes.h.
References SM_Enabled.
Referenced by enableMultiVectorSpillFill(), getSMToggleCondition(), hasNonStreamingInterface(), hasStreamingInterfaceOrBody(), and set().
hasStreamingInterfaceOrBody()
bool llvm::SMEAttrs::hasStreamingInterfaceOrBody () const inline
Definition at line 68 of file AArch64SMEAttributes.h.
References hasStreamingBody(), and hasStreamingInterface().
Referenced by llvm::AArch64::createFastISel(), and instCombineInStreamingMode().
hasUndefZT0()
bool llvm::SMEAttrs::hasUndefZT0 () const inline
Definition at line 126 of file AArch64SMEAttributes.h.
References ZT0_Undef.
Referenced by llvm::SMECallAttrs::requiresPreservingZT0().
hasZAState()
bool llvm::SMEAttrs::hasZAState () const inline
Definition at line 106 of file AArch64SMEAttributes.h.
References isNewZA(), and sharesZA().
Referenced by llvm::AArch64::createFastISel(), llvm::SMECallAttrs::requiresDisablingZABeforeCall(), and llvm::SMECallAttrs::requiresLazySave().
hasZT0State()
bool llvm::SMEAttrs::hasZT0State () const inline
Definition at line 132 of file AArch64SMEAttributes.h.
References isNewZT0(), and sharesZT0().
Referenced by llvm::AArch64::createFastISel(), llvm::SMECallAttrs::requiresDisablingZABeforeCall(), and llvm::SMECallAttrs::requiresPreservingZT0().
isInOutZA()
bool llvm::SMEAttrs::isInOutZA () const inline
Definition at line 92 of file AArch64SMEAttributes.h.
References decodeZAState(), and InOut.
Referenced by set().
isInOutZT0()
bool llvm::SMEAttrs::isInOutZT0 () const inline
Definition at line 120 of file AArch64SMEAttributes.h.
References decodeZT0State(), and InOut.
Referenced by set().
isInZA()
bool llvm::SMEAttrs::isInZA () const inline
Definition at line 90 of file AArch64SMEAttributes.h.
References decodeZAState(), and In.
Referenced by set().
isInZT0()
bool llvm::SMEAttrs::isInZT0 () const inline
Definition at line 118 of file AArch64SMEAttributes.h.
References decodeZT0State(), and In.
Referenced by set().
isNewZA()
bool llvm::SMEAttrs::isNewZA () const inline
Definition at line 89 of file AArch64SMEAttributes.h.
References decodeZAState(), and New.
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), hasZAState(), and set().
isNewZT0()
bool llvm::SMEAttrs::isNewZT0 () const inline
Definition at line 117 of file AArch64SMEAttributes.h.
References decodeZT0State(), and New.
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), hasZT0State(), and set().
isOutZA()
bool llvm::SMEAttrs::isOutZA () const inline
Definition at line 91 of file AArch64SMEAttributes.h.
References decodeZAState(), and Out.
Referenced by set().
isOutZT0()
bool llvm::SMEAttrs::isOutZT0 () const inline
Definition at line 119 of file AArch64SMEAttributes.h.
References decodeZT0State(), and Out.
Referenced by set().
isPreservesZA()
bool llvm::SMEAttrs::isPreservesZA () const inline
Definition at line 93 of file AArch64SMEAttributes.h.
References decodeZAState(), and Preserved.
Referenced by set().
isPreservesZT0()
bool llvm::SMEAttrs::isPreservesZT0 () const inline
Definition at line 123 of file AArch64SMEAttributes.h.
References decodeZT0State(), and Preserved.
Referenced by set().
isSMEABIRoutine()
bool llvm::SMEAttrs::isSMEABIRoutine () const inline
Definition at line 107 of file AArch64SMEAttributes.h.
References SME_ABI_Routine.
Referenced by llvm::SMECallAttrs::requiresDisablingZABeforeCall(), llvm::SMECallAttrs::requiresLazySave(), and llvm::SMECallAttrs::requiresPreservingAllZAState().
operator==()
bool llvm::SMEAttrs::operator== (SMEAttrs const & Other) const inline
Definition at line 144 of file AArch64SMEAttributes.h.
References llvm::Other, and SMEAttrs().
operator|()
SMEAttrs llvm::SMEAttrs::operator| (SMEAttrs Other) const inline
Definition at line 134 of file AArch64SMEAttributes.h.
References llvm::Other, set(), and SMEAttrs().
set()
void SMEAttrs::set (unsigned M, bool Enable = true)
Definition at line 15 of file AArch64SMEAttributes.cpp.
References assert(), llvm::Enable, hasAgnosticZAInterface(), hasSharedZAInterface(), hasStreamingCompatibleInterface(), hasStreamingInterface(), isInOutZA(), isInOutZT0(), isInZA(), isInZT0(), isNewZA(), isNewZT0(), isOutZA(), isOutZT0(), isPreservesZA(), isPreservesZT0(), and SME_ABI_Routine.
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), operator|(), and SMEAttrs().
sharesZA()
bool llvm::SMEAttrs::sharesZA () const inline
Definition at line 96 of file AArch64SMEAttributes.h.
References decodeZAState(), In, InOut, Out, and Preserved.
Referenced by hasSharedZAInterface(), and hasZAState().
sharesZT0()
bool llvm::SMEAttrs::sharesZT0 () const inline
Definition at line 127 of file AArch64SMEAttributes.h.
References decodeZT0State(), In, InOut, Out, and Preserved.
Referenced by hasSharedZAInterface(), hasZT0State(), and llvm::SMECallAttrs::requiresPreservingZT0().
withoutPerCallsiteFlags()
SMEAttrs llvm::SMEAttrs::withoutPerCallsiteFlags () const inline
Definition at line 140 of file AArch64SMEAttributes.h.
References CallSiteFlags_Mask, and SMEAttrs().
The documentation for this class was generated from the following files:
lib/Target/AArch64/Utils/AArch64SMEAttributes.h
lib/Target/AArch64/Utils/AArch64SMEAttributes.cpp