LLVM: SearchOptions Class Reference
SearchOptions Class Reference
This is used to control valid status that current MI supports.
Public Member Functions
SearchOptions (Register Reg, const MachineRegisterInfo &MRI)
bool checkOptions (SrcStatus Stat) const
Detailed Description
This is used to control valid status that current MI supports.
For example, non floating point intrinsic such as @llvm.amdgcn.sdot2 does not support NEG bit on VOP3P. The class can be further extended to recognize support on SEL, NEG, ABS bit for different MI on different arch
Definition at line 4661 of file AMDGPUInstructionSelector.cpp.
Constructor & Destructor Documentation
SearchOptions()
SearchOptions::SearchOptions (Register Reg, const MachineRegisterInfo & MRI) inline
Definition at line 4668 of file AMDGPUInstructionSelector.cpp.
References llvm::cast(), MI, MRI, and Opc.
Member Function Documentation
checkOptions()
bool SearchOptions::checkOptions (SrcStatus Stat) const inline
Definition at line 4682 of file AMDGPUInstructionSelector.cpp.
References HALF_END, HALF_START, NEG_END, and NEG_START.
Referenced by getLastSameOrNeg(), and getSrcStats().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp