LLVM: llvm::object::DirectX::RootSignature Class Reference
llvm::object::DirectX::RootSignature Class Reference
#include "llvm/Object/DXContainer.h"
Public Member Functions
RootSignature (StringRef PD)
LLVM_ABI Error parse ()
uint32_t getVersion () const
uint32_t getNumParameters () const
uint32_t getRootParametersOffset () const
uint32_t getNumStaticSamplers () const
uint32_t getStaticSamplersOffset () const
uint32_t getNumRootParameters () const
llvm::iterator_range< param_header_iterator > param_headers () const
llvm::iterator_range< samplers_iterator > samplers () const
uint32_t getFlags () const
llvm::Expected< RootParameterView > getParameter (const dxbc::RTS0::v1::RootParameterHeader &Header) const
Detailed Description
Definition at line 220 of file DXContainer.h.
Constructor & Destructor Documentation
RootSignature()
llvm::object::DirectX::RootSignature::RootSignature (StringRef PD) inline
Definition at line 237 of file DXContainer.h.
Member Function Documentation
getFlags()
uint32_t llvm::object::DirectX::RootSignature::getFlags () const inline
Definition at line 252 of file DXContainer.h.
getNumParameters()
uint32_t llvm::object::DirectX::RootSignature::getNumParameters () const inline
Definition at line 241 of file DXContainer.h.
getNumRootParameters()
uint32_t llvm::object::DirectX::RootSignature::getNumRootParameters () const inline
Definition at line 245 of file DXContainer.h.
getNumStaticSamplers()
uint32_t llvm::object::DirectX::RootSignature::getNumStaticSamplers () const inline
Definition at line 243 of file DXContainer.h.
Referenced by getParameter().
getParameter()
llvm::Expected< RootParameterView > llvm::object::DirectX::RootSignature::getParameter (const dxbc::RTS0::v1::RootParameterHeader & Header) const inline
Definition at line 255 of file DXContainer.h.
References llvm::DataSize, getNumStaticSamplers(), getStaticSamplersOffset(), llvm::dxbc::isValidParameterType(), llvm::object::DirectX::parseFailed(), llvm::support::endian::read(), and llvm::StringRef::substr().
getRootParametersOffset()
uint32_t llvm::object::DirectX::RootSignature::getRootParametersOffset () const inline
Definition at line 242 of file DXContainer.h.
getStaticSamplersOffset()
uint32_t llvm::object::DirectX::RootSignature::getStaticSamplersOffset () const inline
Definition at line 244 of file DXContainer.h.
Referenced by getParameter().
getVersion()
uint32_t llvm::object::DirectX::RootSignature::getVersion () const inline
Definition at line 240 of file DXContainer.h.
param_headers()
llvm::iterator_range< param_header_iterator > llvm::object::DirectX::RootSignature::param_headers () const inline
Definition at line 246 of file DXContainer.h.
References llvm::make_range().
parse()
Error DirectX::RootSignature::parse ()
Definition at line 244 of file DXContainer.cpp.
References llvm::object::DirectX::parseFailed(), llvm::support::endian::read(), and llvm::Error::success().
samplers()
llvm::iterator_range< samplers_iterator > llvm::object::DirectX::RootSignature::samplers () const inline
Definition at line 249 of file DXContainer.h.
References llvm::make_range().
The documentation for this class was generated from the following files:
include/llvm/Object/DXContainer.h
lib/Object/DXContainer.cpp