LLVM: llvm::SparcTargetELFStreamer Class Reference
llvm::SparcTargetELFStreamer Class Reference
#include "Target/Sparc/MCTargetDesc/SparcTargetStreamer.h"
Public Member Functions
SparcTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
MCELFStreamer & getStreamer ()
void emitSparcRegisterIgnore (unsigned reg) override
Emit ".register <reg>, #ignore".
void emitSparcRegisterScratch (unsigned reg) override
Emit ".register <reg>, #scratch".
Public Member Functions inherited from llvm::SparcTargetStreamer
SparcTargetStreamer (MCStreamer &S)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 41 of file SparcTargetStreamer.h.
Constructor & Destructor Documentation
SparcTargetELFStreamer()
SparcTargetELFStreamer::SparcTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 62 of file SparcTargetStreamer.cpp.
References llvm::getEFlagsForFeatureSet(), getStreamer(), llvm::MCELFStreamer::getWriter(), and llvm::SparcTargetStreamer::SparcTargetStreamer().
Member Function Documentation
emitSparcRegisterIgnore()
void llvm::SparcTargetELFStreamer::emitSparcRegisterIgnore (unsigned reg) inline override virtual
Emit ".register <reg>, #ignore".
Reimplemented from llvm::SparcTargetStreamer.
Definition at line 45 of file SparcTargetStreamer.h.
emitSparcRegisterScratch()
void llvm::SparcTargetELFStreamer::emitSparcRegisterScratch (unsigned reg) inline override virtual
Emit ".register <reg>, #scratch".
Reimplemented from llvm::SparcTargetStreamer.
Definition at line 46 of file SparcTargetStreamer.h.
getStreamer()
MCELFStreamer & SparcTargetELFStreamer::getStreamer ()
Definition at line 73 of file SparcTargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by SparcTargetELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/Sparc/MCTargetDesc/SparcTargetStreamer.h
lib/Target/Sparc/MCTargetDesc/SparcTargetStreamer.cpp