LLVM: llvm::RewriteBuffer Class Reference
llvm::RewriteBuffer Class Reference
RewriteBuffer - As code is rewritten, SourceBuffer's from the original input with modifications get a new RewriteBuffer associated with them.
#include "llvm/ADT/RewriteBuffer.h"
Public Types
using iterator = RewriteRope::const_iterator
Public Member Functions
iterator begin () const
iterator end () const
unsigned size () const
void Initialize (const char *BufStart, const char *BufEnd)
Initialize - Start this rewrite buffer out with a copy of the unmodified input buffer.
void Initialize (StringRef Input)
LLVM_ABI raw_ostream & write (raw_ostream &Stream) const
Write to Stream the result of applying all changes to the original buffer.
LLVM_ABI void RemoveText (unsigned OrigOffset, unsigned Size, bool removeLineIfEmpty=false)
RemoveText - Remove the specified text.
LLVM_ABI void InsertText (unsigned OrigOffset, StringRef Str, bool InsertAfter=true)
InsertText - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
void InsertTextBefore (unsigned OrigOffset, StringRef Str)
InsertTextBefore - Insert some text before the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
void InsertTextAfter (unsigned OrigOffset, StringRef Str)
InsertTextAfter - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
LLVM_ABI void ReplaceText (unsigned OrigOffset, unsigned OrigLength, StringRef NewStr)
ReplaceText - This method replaces a range of characters in the input buffer with a new string.
Friends
class clang::Rewriter
Detailed Description
RewriteBuffer - As code is rewritten, SourceBuffer's from the original input with modifications get a new RewriteBuffer associated with them.
The RewriteBuffer captures the modified text itself as well as information used to map between SourceLocation's in the original input and offsets in the RewriteBuffer. For example, if text is inserted into the buffer, any locations after the insertion point have to be mapped.
Definition at line 31 of file RewriteBuffer.h.
Member Typedef Documentation
iterator
using llvm::RewriteBuffer::iterator = RewriteRope::const_iterator
Definition at line 41 of file RewriteBuffer.h.
Member Function Documentation
begin()
iterator llvm::RewriteBuffer::begin () const inline
Definition at line 43 of file RewriteBuffer.h.
Referenced by RemoveText(), and write().
end()
iterator llvm::RewriteBuffer::end () const inline
Definition at line 44 of file RewriteBuffer.h.
Referenced by RemoveText(), and write().
Initialize() [1/2]
void llvm::RewriteBuffer::Initialize (const char * BufStart, const char * BufEnd) inline
Initialize - Start this rewrite buffer out with a copy of the unmodified input buffer.
Definition at line 49 of file RewriteBuffer.h.
Initialize() [2/2]
void llvm::RewriteBuffer::Initialize (StringRef Input) inline
Definition at line 52 of file RewriteBuffer.h.
References Initialize().
Referenced by Initialize().
InsertText()
void RewriteBuffer::InsertText (unsigned OrigOffset, StringRef Str, bool InsertAfter = true)
InsertText - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
The text is inserted after the specified location.
Definition at line 84 of file RewriteBuffer.cpp.
Referenced by InsertTextAfter(), and InsertTextBefore().
InsertTextAfter()
void llvm::RewriteBuffer::InsertTextAfter (unsigned OrigOffset, StringRef Str) inline
InsertTextAfter - Insert some text at the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
The text is inserted after the specified location.
Definition at line 84 of file RewriteBuffer.h.
References InsertText().
InsertTextBefore()
void llvm::RewriteBuffer::InsertTextBefore (unsigned OrigOffset, StringRef Str) inline
InsertTextBefore - Insert some text before the specified point, where the offset in the buffer is specified relative to the original SourceBuffer.
The text is inserted before the specified location. This is method is the same as InsertText with "InsertAfter == false".
Definition at line 77 of file RewriteBuffer.h.
References InsertText().
RemoveText()
void RewriteBuffer::RemoveText (unsigned OrigOffset, unsigned Size, bool removeLineIfEmpty = false)
RemoveText - Remove the specified text.
Definition at line 29 of file RewriteBuffer.cpp.
References assert(), begin(), end(), isWhitespaceExceptNL(), and Size.
ReplaceText()
void RewriteBuffer::ReplaceText (unsigned OrigOffset, unsigned OrigLength, StringRef NewStr)
ReplaceText - This method replaces a range of characters in the input buffer with a new string.
This is effectively a combined "remove/insert" operation.
This is effectively a combined "remove+insert" operation.
Definition at line 100 of file RewriteBuffer.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), and llvm::StringRef::size().
size()
unsigned llvm::RewriteBuffer::size () const inline
Definition at line 45 of file RewriteBuffer.h.
write()
raw_ostream & RewriteBuffer::write (raw_ostream & Stream) const
Write to Stream the result of applying all changes to the original buffer.
Note that it isn't safe to use this function to overwrite memory mapped files in-place (PR17960). Consider using a higher-level utility such as Rewriter::overwriteChangedFiles() instead.
The original buffer is not actually changed.
Definition at line 14 of file RewriteBuffer.cpp.
References begin(), end(), and I.
Friends And Related Symbol Documentation
clang::Rewriter
friend class clang::Rewriter friend
Definition at line 32 of file RewriteBuffer.h.
References clang::Rewriter.
Referenced by clang::Rewriter.
The documentation for this class was generated from the following files:
include/llvm/ADT/RewriteBuffer.h
lib/Support/RewriteBuffer.cpp