LLVM: llvm::codeview::FrameCookieSym Class Reference
llvm::codeview::FrameCookieSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
FrameCookieSym (SymbolRecordKind Kind)
FrameCookieSym (uint32_t RecordOffset)
uint32_t getRelocationOffset () const
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
uint32_t CodeOffset = 0
uint16_t Register = 0
FrameCookieKind CookieKind
uint8_t Flags = 0
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 875 of file SymbolRecord.h.
Constructor & Destructor Documentation
FrameCookieSym() [1/2]
llvm::codeview::FrameCookieSym::FrameCookieSym (SymbolRecordKind Kind) inline explicit
Definition at line 879 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by FrameCookieSym().
FrameCookieSym() [2/2]
llvm::codeview::FrameCookieSym::FrameCookieSym (uint32_t RecordOffset) inline explicit
Definition at line 880 of file SymbolRecord.h.
References FrameCookieSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Function Documentation
getRelocationOffset()
uint32_t llvm::codeview::FrameCookieSym::getRelocationOffset () const inline
Definition at line 883 of file SymbolRecord.h.
References RecordOffset.
Member Data Documentation
CodeOffset
uint32_t llvm::codeview::FrameCookieSym::CodeOffset = 0
Definition at line 887 of file SymbolRecord.h.
CookieKind
FrameCookieKind llvm::codeview::FrameCookieSym::CookieKind
Definition at line 889 of file SymbolRecord.h.
Flags
uint8_t llvm::codeview::FrameCookieSym::Flags = 0
Definition at line 890 of file SymbolRecord.h.
RecordOffset
uint32_t llvm::codeview::FrameCookieSym::RecordOffset = 0
Definition at line 892 of file SymbolRecord.h.
Referenced by FrameCookieSym(), and getRelocationOffset().
Register
uint16_t llvm::codeview::FrameCookieSym::Register = 0
Definition at line 888 of file SymbolRecord.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h