LLVM: llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator Class Reference
llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator Class Reference
#include "llvm/ADT/DenseSet.h"
Public Types
using difference_type = typename MapTy::const_iterator::difference_type
using value_type = ValueT
using pointer = const value_type *
using reference = const value_type &
using iterator_category = std::forward_iterator_tag
Public Member Functions
ConstIterator ()=default
ConstIterator (const Iterator &B)
ConstIterator (const typename MapTy::const_iterator &i)
const ValueT & operator* () const
const ValueT * operator-> () const
ConstIterator & operator++ ()
ConstIterator operator++ (int)
Friends
class DenseSetImpl
class Iterator
bool operator== (const ConstIterator &X, const ConstIterator &Y)
bool operator!= (const ConstIterator &X, const ConstIterator &Y)
Detailed Description
template<typename ValueT, typename MapTy, typename ValueInfoT>
class llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator
Definition at line 148 of file DenseSet.h.
Member Typedef Documentation
difference_type
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::difference_type = typename MapTy::const_iterator::difference_type
Definition at line 154 of file DenseSet.h.
iterator_category
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::iterator_category = std::forward_iterator_tag
Definition at line 158 of file DenseSet.h.
pointer
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::pointer = const value_type *
Definition at line 156 of file DenseSet.h.
reference
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::reference = const value_type &
Definition at line 157 of file DenseSet.h.
value_type
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::value_type = ValueT
Definition at line 155 of file DenseSet.h.
Constructor & Destructor Documentation
ConstIterator() [1/3]
template<typename ValueT, typename MapTy, typename ValueInfoT> llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::ConstIterator () default
Referenced by operator!=, operator++(), operator++(), and operator==.
ConstIterator() [2/3]
template<typename ValueT, typename MapTy, typename ValueInfoT> llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::ConstIterator (const Iterator & B) inline
Definition at line 161 of file DenseSet.h.
References B(), and Iterator.
ConstIterator() [3/3]
template<typename ValueT, typename MapTy, typename ValueInfoT> llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::ConstIterator (const typename MapTy::const_iterator & i) inline
Definition at line 162 of file DenseSet.h.
Member Function Documentation
operator*()
template<typename ValueT, typename MapTy, typename ValueInfoT> const ValueT & llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::operator* () const inline
Definition at line 164 of file DenseSet.h.
operator++() [1/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> ConstIterator & llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::operator++ () inline
Definition at line 167 of file DenseSet.h.
References ConstIterator().
operator++() [2/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> ConstIterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::operator++ (int) inline
Definition at line 171 of file DenseSet.h.
References ConstIterator(), and T.
operator->()
template<typename ValueT, typename MapTy, typename ValueInfoT> const ValueT * llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::ConstIterator::operator-> () const inline
Definition at line 165 of file DenseSet.h.
Friends And Related Symbol Documentation
DenseSetImpl
template<typename ValueT, typename MapTy, typename ValueInfoT> friend class DenseSetImpl friend
Definition at line 150 of file DenseSet.h.
References DenseSetImpl.
Referenced by DenseSetImpl.
Iterator
template<typename ValueT, typename MapTy, typename ValueInfoT> friend class Iterator friend
Definition at line 151 of file DenseSet.h.
References Iterator.
Referenced by ConstIterator(), and Iterator.
operator!=
template<typename ValueT, typename MapTy, typename ValueInfoT> bool operator!= (const ConstIterator & X, const ConstIterator & Y) friend
Definition at line 179 of file DenseSet.h.
References ConstIterator(), X, and Y.
operator==
template<typename ValueT, typename MapTy, typename ValueInfoT> bool operator== (const ConstIterator & X, const ConstIterator & Y) friend
Definition at line 176 of file DenseSet.h.
References ConstIterator(), X, and Y.
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseSet.h