LLVM: llvm::InstSimplifyFolder Class Reference
llvm::InstSimplifyFolder Class Reference final
InstSimplifyFolder - Use InstructionSimplify to fold operations to existing values.
#include "llvm/Analysis/InstSimplifyFolder.h"
Public Member Functions
InstSimplifyFolder (const DataLayout &DL)
Value * FoldBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS) const override
Value * FoldExactBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool IsExact) const override
Value * FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool HasNUW, bool HasNSW) const override
Value * FoldBinOpFMF (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, FastMathFlags FMF) const override
Value * FoldUnOpFMF (Instruction::UnaryOps Opc, Value *V, FastMathFlags FMF) const override
Value * FoldCmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const override
Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, GEPNoWrapFlags NW) const override
Value * FoldSelect (Value *C, Value *True, Value *False) const override
Value * FoldExtractValue (Value *Agg, ArrayRef< unsigned > IdxList) const override
Value * FoldInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > IdxList) const override
Value * FoldExtractElement (Value *Vec, Value *Idx) const override
Value * FoldInsertElement (Value *Vec, Value *NewElt, Value *Idx) const override
Value * FoldShuffleVector (Value *V1, Value *V2, ArrayRef< int > Mask) const override
Value * FoldCast (Instruction::CastOps Op, Value *V, Type *DestTy) const override
Value * FoldBinaryIntrinsic (Intrinsic::ID ID, Value *LHS, Value *RHS, Type *Ty, Instruction *FMFSource) const override
Value * CreatePointerCast (Constant *C, Type *DestTy) const override
Value * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
InstSimplifyFolder - Use InstructionSimplify to fold operations to existing values.
Also applies target-specific constant folding when not using InstructionSimplify.
Definition at line 36 of file InstSimplifyFolder.h.
Constructor & Destructor Documentation
InstSimplifyFolder()
llvm::InstSimplifyFolder::InstSimplifyFolder (const DataLayout & DL) inline explicit
Definition at line 43 of file InstSimplifyFolder.h.
References DL.
Member Function Documentation
CreatePointerBitCastOrAddrSpaceCast()
Value * llvm::InstSimplifyFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 138 of file InstSimplifyFolder.h.
References llvm::CallingConv::C.
CreatePointerCast()
Value * llvm::InstSimplifyFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 132 of file InstSimplifyFolder.h.
References llvm::CallingConv::C.
FoldBinaryIntrinsic()
Value * llvm::InstSimplifyFolder::FoldBinaryIntrinsic (Intrinsic::ID ID, Value * LHS, Value * RHS, Type * Ty, Instruction * FMFSource) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 122 of file InstSimplifyFolder.h.
References llvm::dyn_cast_if_present(), LHS, RHS, and llvm::simplifyBinaryIntrinsic().
FoldBinOp()
Value * llvm::InstSimplifyFolder::FoldBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 52 of file InstSimplifyFolder.h.
References LHS, Opc, RHS, and simplifyBinOp().
Referenced by tryToFoldLiveIns().
FoldBinOpFMF()
Value * llvm::InstSimplifyFolder::FoldBinOpFMF (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 67 of file InstSimplifyFolder.h.
References LHS, Opc, RHS, and simplifyBinOp().
FoldCast()
Value * llvm::InstSimplifyFolder::FoldCast (Instruction::CastOps Op, Value * V, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 117 of file InstSimplifyFolder.h.
References simplifyCastInst().
Referenced by tryToFoldLiveIns().
FoldCmp()
Value * llvm::InstSimplifyFolder::FoldCmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 77 of file InstSimplifyFolder.h.
References LHS, P, RHS, and simplifyCmpInst().
Referenced by tryToFoldLiveIns().
FoldExactBinOp()
Value * llvm::InstSimplifyFolder::FoldExactBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool IsExact) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 57 of file InstSimplifyFolder.h.
References LHS, Opc, RHS, and simplifyBinOp().
FoldExtractElement()
Value * llvm::InstSimplifyFolder::FoldExtractElement (Value * Vec, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 100 of file InstSimplifyFolder.h.
References simplifyExtractElementInst().
Referenced by tryToFoldLiveIns().
FoldExtractValue()
Value * llvm::InstSimplifyFolder::FoldExtractValue (Value * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 90 of file InstSimplifyFolder.h.
References simplifyExtractValueInst().
FoldGEP()
Value * llvm::InstSimplifyFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, GEPNoWrapFlags NW) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 81 of file InstSimplifyFolder.h.
References Ptr, and simplifyGEPInst().
Referenced by tryToFoldLiveIns().
FoldInsertElement()
Value * llvm::InstSimplifyFolder::FoldInsertElement (Value * Vec, Value * NewElt, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 104 of file InstSimplifyFolder.h.
References llvm::simplifyInsertElementInst().
Referenced by tryToFoldLiveIns().
FoldInsertValue()
Value * llvm::InstSimplifyFolder::FoldInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 95 of file InstSimplifyFolder.h.
References simplifyInsertValueInst().
FoldNoWrapBinOp()
Value * llvm::InstSimplifyFolder::FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool HasNUW, bool HasNSW) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 62 of file InstSimplifyFolder.h.
References LHS, Opc, RHS, and simplifyBinOp().
FoldSelect()
Value * llvm::InstSimplifyFolder::FoldSelect (Value * C, Value * True, Value * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 86 of file InstSimplifyFolder.h.
References llvm::CallingConv::C, and simplifySelectInst().
Referenced by tryToFoldLiveIns().
FoldShuffleVector()
Value * llvm::InstSimplifyFolder::FoldShuffleVector (Value * V1, Value * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 109 of file InstSimplifyFolder.h.
References llvm::cast(), llvm::VectorType::get(), llvm::isa(), and simplifyShuffleVectorInst().
FoldUnOpFMF()
Value * llvm::InstSimplifyFolder::FoldUnOpFMF (Instruction::UnaryOps Opc, Value * V, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 72 of file InstSimplifyFolder.h.
References Opc, and simplifyUnOp().
The documentation for this class was generated from the following file:
include/llvm/Analysis/InstSimplifyFolder.h