LLVM: llvm::DebugVariable Class Reference
llvm::DebugVariable Class Reference
Identifies a unique instance of a variable.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
LLVM_ABI DebugVariable (const DbgVariableIntrinsic *DII)
LLVM_ABI DebugVariable (const DbgVariableRecord *DVR)
DebugVariable (const DILocalVariable *Var, std::optional< FragmentInfo > FragmentInfo, const DILocation *InlinedAt)
DebugVariable (const DILocalVariable *Var, const DIExpression *DIExpr, const DILocation *InlinedAt)
const DILocalVariable * getVariable () const
std::optional< FragmentInfo > getFragment () const
const DILocation * getInlinedAt () const
FragmentInfo getFragmentOrDefault () const
bool operator== (const DebugVariable &Other) const
bool operator< (const DebugVariable &Other) const
Static Public Member Functions
static bool isDefaultFragment (const FragmentInfo F)
Detailed Description
Identifies a unique instance of a variable.
Storage for identifying a potentially inlined instance of a variable, or a fragment thereof. This guarantees that exactly one variable instance may be identified by this class, even when that variable is a fragment of an aggregate variable and/or there is another inlined instance of the same source code variable nearby. This class does not necessarily uniquely identify that variable: it is possible that a DebugVariable with different parameters may point to the same variable instance, but not that one DebugVariable points to multiple variable instances.
Definition at line 4604 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DebugVariable() [1/4]
DebugVariable::DebugVariable (const DbgVariableIntrinsic * DII)
Definition at line 52 of file DebugInfoMetadata.cpp.
References getDebugLoc(), getInlinedAt(), and getVariable().
Referenced by llvm::DebugVariableAggregate::DebugVariableAggregate(), llvm::DebugVariableAggregate::DebugVariableAggregate(), operator<(), and operator==().
DebugVariable() [2/4]
DebugVariable::DebugVariable (const DbgVariableRecord * DVR)
Definition at line 57 of file DebugInfoMetadata.cpp.
References getDebugLoc(), getInlinedAt(), and getVariable().
DebugVariable() [3/4]
llvm::DebugVariable::DebugVariable (const DILocalVariable * Var, std::optional< FragmentInfo > FragmentInfo, const DILocation * InlinedAt) inline
Definition at line 4619 of file DebugInfoMetadata.h.
DebugVariable() [4/4]
llvm::DebugVariable::DebugVariable (const DILocalVariable * Var, const DIExpression * DIExpr, const DILocation * InlinedAt) inline
Definition at line 4624 of file DebugInfoMetadata.h.
Member Function Documentation
getFragment()
std::optional< FragmentInfo > llvm::DebugVariable::getFragment () const inline
Definition at line 4631 of file DebugInfoMetadata.h.
Referenced by LiveDebugValues::MLocTracker::emitLoc().
getFragmentOrDefault()
FragmentInfo llvm::DebugVariable::getFragmentOrDefault () const inline
Definition at line 4634 of file DebugInfoMetadata.h.
Referenced by LiveDebugValues::VLocTracker::considerOverlaps().
getInlinedAt()
const DILocation * llvm::DebugVariable::getInlinedAt () const inline
Definition at line 4632 of file DebugInfoMetadata.h.
Referenced by buildOverlapMapAndRecordDeclares(), LiveDebugValues::VLocTracker::considerOverlaps(), DebugVariable(), DebugVariable(), llvm::DebugVariableAggregate::DebugVariableAggregate(), llvm::DebugVariableAggregate::DebugVariableAggregate(), TransferTracker::emitMOLoc(), getAggregate(), and TransferTracker::isEntryValueVariable().
getVariable()
const DILocalVariable * llvm::DebugVariable::getVariable () const inline
Definition at line 4630 of file DebugInfoMetadata.h.
Referenced by buildOverlapMapAndRecordDeclares(), LiveDebugValues::VLocTracker::considerOverlaps(), DebugVariable(), DebugVariable(), llvm::DebugVariableAggregate::DebugVariableAggregate(), llvm::DebugVariableAggregate::DebugVariableAggregate(), LiveDebugValues::MLocTracker::emitLoc(), TransferTracker::emitMOLoc(), getAggregate(), llvm::FunctionVarLocs::getDILocalVariable(), TransferTracker::isEntryValueVariable(), removeRedundantDbgLocsUsingForwardScan(), and removeUndefDbgLocsFromEntryBlock().
isDefaultFragment()
bool llvm::DebugVariable::isDefaultFragment (const FragmentInfo F) inline static
Definition at line 4638 of file DebugInfoMetadata.h.
References F.
Referenced by LiveDebugValues::VLocTracker::considerOverlaps().
operator<()
bool llvm::DebugVariable::operator< (const DebugVariable & Other) const inline
Definition at line 4647 of file DebugInfoMetadata.h.
References DebugVariable(), and llvm::Other.
operator==()
bool llvm::DebugVariable::operator== (const DebugVariable & Other) const inline
Definition at line 4642 of file DebugInfoMetadata.h.
References DebugVariable(), and llvm::Other.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp