LLVM: llvm::ManagedStaticBase Class Reference
llvm::ManagedStaticBase Class Reference
ManagedStaticBase - Common base class for ManagedStatic instances.
#include "llvm/Support/ManagedStatic.h"
Public Member Functions
constexpr ManagedStaticBase ()=default
bool isConstructed () const
isConstructed - Return true if this object has not been created yet.
LLVM_ABI void destroy () const
Protected Member Functions
LLVM_ABI void RegisterManagedStatic (void *(*creator)(), void(*deleter)(void *)) const
Protected Attributes
std::atomic< void * > Ptr {}
void(* DeleterFn)(void *) = nullptr
const ManagedStaticBase * Next = nullptr
Detailed Description
ManagedStaticBase - Common base class for ManagedStatic instances.
Definition at line 50 of file ManagedStatic.h.
Constructor & Destructor Documentation
ManagedStaticBase()
llvm::ManagedStaticBase::ManagedStaticBase () constexpr default
Member Function Documentation
destroy()
void ManagedStaticBase::destroy () const
Definition at line 55 of file ManagedStatic.cpp.
References assert(), DeleterFn, Next, Ptr, and StaticList.
isConstructed()
bool llvm::ManagedStaticBase::isConstructed () const inline
isConstructed - Return true if this object has not been created yet.
Definition at line 73 of file ManagedStatic.h.
References Ptr.
RegisterManagedStatic()
void ManagedStaticBase::RegisterManagedStatic (void *(* creator)(), void(* deleter)(void *)) const protected
Definition at line 27 of file ManagedStatic.cpp.
References assert(), DeleterFn, getManagedStaticMutex(), llvm::llvm_is_multithreaded(), Next, Ptr, and StaticList.
Referenced by llvm::ManagedStatic< C, Creator, Deleter >::operator*(), and llvm::ManagedStatic< C, Creator, Deleter >::operator*().
Member Data Documentation
DeleterFn
void(* llvm::ManagedStaticBase::DeleterFn) (void *) = nullptr mutable protected
Definition at line 54 of file ManagedStatic.h.
Referenced by destroy(), and RegisterManagedStatic().
Next
const ManagedStaticBase* llvm::ManagedStaticBase::Next = nullptr mutable protected
Definition at line 55 of file ManagedStatic.h.
Referenced by destroy(), and RegisterManagedStatic().
Ptr
std::atomic<void *> llvm::ManagedStaticBase::Ptr {} mutable protected
Definition at line 53 of file ManagedStatic.h.
Referenced by llvm::ManagedStatic< C, Creator, Deleter >::claim(), destroy(), isConstructed(), llvm::ManagedStatic< C, Creator, Deleter >::operator*(), llvm::ManagedStatic< C, Creator, Deleter >::operator*(), and RegisterManagedStatic().
The documentation for this class was generated from the following files:
include/llvm/Support/ManagedStatic.h
lib/Support/ManagedStatic.cpp