LLVM: llvm::MCSymbol Class Reference
llvm::MCSymbol Class Reference
MCSymbol - Instances of this class represent a symbol name in the MC file, and MCSymbols are created and uniqued by the MCContext class.
#include "llvm/MC/MCSymbol.h"
Public Member Functions
StringRef getName () const
getName - Get the symbol name.
bool isRegistered () const
void setIsRegistered (bool Value) const
void setUsedInReloc () const
bool isUsedInReloc () const
uint32_t getIndex () const
Get the (implementation defined) index.
void setIndex (uint32_t Value) const
Set the (implementation defined) index.
bool isUnset () const
uint64_t getOffset () const
void setOffset (uint64_t Value)
uint64_t getCommonSize () const
Return the size of a 'common' symbol.
void setCommon (uint64_t Size, Align Alignment, bool Target=false)
Mark this symbol as being 'common'.
MaybeAlign getCommonAlignment () const
Return the alignment of a 'common' symbol.
bool declareCommon (uint64_t Size, Align Alignment, bool Target=false)
Declare this symbol as being 'common'.
bool isCommon () const
Is this a 'common' symbol.
bool isTargetCommon () const
Is this a target-specific common-like symbol.
MCFragment * getFragment () const
bool isExternal () const
void setExternal (bool Value) const
bool isWeakExternal () const
LLVM_ABI void print (raw_ostream &OS, const MCAsmInfo *MAI) const
print - Print the value to the stream OS.
LLVM_ABI void dump () const
dump - Print the value to stderr.
Accessors
bool isTemporary () const
isTemporary - Check if this is an assembler temporary symbol.
bool isRedefinable () const
Check if this symbol is redefinable.
void setRedefinable (bool Value)
Mark this symbol as redefinable.
void redefineIfPossible ()
Prepare this symbol to be redefined.
bool isResolving () const
void setIsResolving (bool V)
Associated Sections
bool isDefined () const
isDefined - Check if this symbol is defined (i.e., it has an address).
bool isInSection () const
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
bool isUndefined () const
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
bool isAbsolute () const
isAbsolute - Check if this is an absolute symbol.
MCSection & getSection () const
Get the section associated with a defined, non-absolute symbol.
void setFragment (MCFragment *F) const
Mark the symbol as defined in the fragment F.
void setUndefined ()
Mark the symbol as undefined.
bool isELF () const
bool isCOFF () const
bool isGOFF () const
bool isMachO () const
bool isWasm () const
bool isXCOFF () const
Variable Symbols
bool isVariable () const
isVariable - Check if this is a variable symbol.
const MCExpr * getVariableValue () const
Get the expression of the variable symbol.
LLVM_ABI void setVariableValue (const MCExpr *Value)
Protected Types
enum SymbolKind {
SymbolKindUnset , SymbolKindCOFF , SymbolKindELF , SymbolKindGOFF ,
SymbolKindMachO , SymbolKindWasm , SymbolKindXCOFF
}
The kind of the symbol.
enum Contents : uint8_t {
SymContentsUnset , SymContentsOffset , SymContentsVariable , SymContentsCommon ,
SymContentsTargetCommon
}
A symbol can contain an Offset, or Value, or be Common, but never more than one of these.
enum : unsigned { NumCommonAlignmentBits = 5 }
The alignment of the symbol if it is 'common'.
enum : unsigned { NumFlagsBits = 16 }
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
using NameEntryStorageTy
The name for a symbol.
Protected Member Functions
MCSymbol (SymbolKind Kind, const MCSymbolTableEntry *Name, bool isTemporary)
MCSymbol (const MCSymbol &)=default
MCSymbol & operator= (const MCSymbol &)=delete
LLVM_ABI void * operator new (size_t s, const MCSymbolTableEntry *Name, MCContext &Ctx)
uint32_t getFlags () const
Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value) const
Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask) const
Modify the flags via a mask.
Protected Attributes
MCFragment * Fragment = nullptr
If a symbol has a Fragment, the section is implied, so we only need one pointer.
unsigned HasName: 1
True if this symbol is named.
unsigned IsTemporary: 1
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
unsigned IsRedefinable: 1
True if this symbol can be redefined.
unsigned IsRegistered: 1
unsigned IsExternal: 1
True if this symbol is visible outside this translation unit.
unsigned IsPrivateExtern: 1
Mach-O specific: This symbol is private extern.
unsigned IsWeakExternal: 1
This symbol is weak external.
unsigned Kind: 3
LLVM RTTI discriminator.
unsigned IsUsedInReloc: 1
True if we have created a relocation that uses this symbol.
unsigned IsResolving: 1
Used to detect cyclic dependency like a = a + 1 and a = b; b = a.
unsigned SymbolContents: 3
This is actually a Contents enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
unsigned CommonAlignLog2: NumCommonAlignmentBits
uint32_t Flags: NumFlagsBits
uint32_t Index = 0
Index field, for use by the object file implementation.
union {
uint64_t Offset
The offset to apply to the fragment address to form this symbol's value.
uint64_t CommonSize
The size of the symbol, if it is 'common'.
const MCExpr * Value
If non-null, the value for a variable symbol.
};
Static Protected Attributes
static LLVM_ABI MCFragment * AbsolutePseudoFragment = &SentinelFragment
Friends
class MCExpr
class MCContext
Detailed Description
MCSymbol - Instances of this class represent a symbol name in the MC file, and MCSymbols are created and uniqued by the MCContext class.
MCSymbols should only be constructed with valid names for the object file.
If the symbol is defined/emitted into the current translation unit, the Section member is set to indicate what section it lives in. Otherwise, if it is a reference to an external entity, it has a null section.
Definition at line 42 of file MCSymbol.h.
Member Typedef Documentation
NameEntryStorageTy
using llvm::MCSymbol::NameEntryStorageTy protected
Initial value:
 union {
    const MCSymbolTableEntry *NameEntry;
    uint64_t AlignmentPadding;
  }
The name for a symbol.
MCSymbol contains a uint64_t so is probably aligned to 8. On a 32-bit system, the name is a pointer so isn't going to satisfy the 8 byte alignment of uint64_t. Account for that here.
Definition at line 160 of file MCSymbol.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned protected
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
Enumerator
NumFlagsBits
Definition at line 135 of file MCSymbol.h.
anonymous enum
anonymous enum : unsigned protected
The alignment of the symbol if it is 'common'.
Internally, this is stored as log2(align) + 1. We reserve 5 bits to encode this value which allows the following values 0b00000 -> unset 0b00001 -> 1ULL << 0 = 1 0b00010 -> 1ULL << 1 = 2 0b00011 -> 1ULL << 2 = 4 ... 0b11111 -> 1ULL << 30 = 1 GiB
Enumerator
NumCommonAlignmentBits
Definition at line 130 of file MCSymbol.h.
Contents
enum llvm::MCSymbol::Contents : uint8_t protected
A symbol can contain an Offset, or Value, or be Common, but never more than one of these.
Enumerator
SymContentsUnset
SymContentsOffset
SymContentsVariable
SymContentsCommon
SymContentsTargetCommon
Definition at line 58 of file MCSymbol.h.
SymbolKind
enum llvm::MCSymbol::SymbolKind protected
The kind of the symbol.
If it is any value other than unset then this class is actually one of the appropriate subclasses of MCSymbol.
Enumerator
SymbolKindUnset
SymbolKindCOFF
SymbolKindELF
SymbolKindGOFF
SymbolKindMachO
SymbolKindWasm
SymbolKindXCOFF
Definition at line 46 of file MCSymbol.h.
Constructor & Destructor Documentation
MCSymbol() [1/2]
llvm::MCSymbol::MCSymbol (SymbolKind Kind, const MCSymbolTableEntry * Name, bool isTemporary) inline protected
Definition at line 165 of file MCSymbol.h.
References CommonAlignLog2, Flags, HasName, IsExternal, IsPrivateExtern, IsRedefinable, IsRegistered, IsResolving, IsTemporary, isTemporary(), IsUsedInReloc, IsWeakExternal, Kind, Offset, SymbolContents, and SymContentsUnset.
Referenced by llvm::MCSymbolCOFF::classof(), llvm::MCSymbolELF::classof(), llvm::MCSymbolGOFF::classof(), llvm::MCSymbolMachO::classof(), llvm::MCSymbolWasm::classof(), llvm::MCSymbolXCOFF::classof(), MCSymbol(), llvm::MCSymbolCOFF::MCSymbolCOFF(), llvm::MCSymbolELF::MCSymbolELF(), llvm::MCSymbolGOFF::MCSymbolGOFF(), llvm::MCSymbolMachO::MCSymbolMachO(), llvm::MCSymbolWasm::MCSymbolWasm(), llvm::MCSymbolXCOFF::MCSymbolXCOFF(), operator new(), and operator=().
MCSymbol() [2/2]
llvm::MCSymbol::MCSymbol (const MCSymbol &) protected default
References MCSymbol().
Member Function Documentation
declareCommon()
bool llvm::MCSymbol::declareCommon (uint64_t Size, Align Alignment, bool Target = false) inline
Declare this symbol as being 'common'.
Parameters
Size - The size of the symbol.
Alignment - The alignment of the symbol.
Target - Is the symbol a target-specific common-like symbol.
Returns
True if symbol was already declared as a different type
Definition at line 375 of file MCSymbol.h.
References assert(), CommonSize, getCommonAlignment(), getOffset(), isCommon(), isTargetCommon(), setCommon(), and Size.
Referenced by llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS().
dump()
LLVM_DUMP_METHOD void MCSymbol::dump () const
dump - Print the value to stderr.
Definition at line 84 of file MCSymbol.cpp.
References llvm::dbgs(), and LLVM_DUMP_METHOD.
getCommonAlignment()
MaybeAlign llvm::MCSymbol::getCommonAlignment () const inline
Return the alignment of a 'common' symbol.
Definition at line 364 of file MCSymbol.h.
References assert(), CommonAlignLog2, llvm::decodeMaybeAlign(), and isCommon().
Referenced by declareCommon(), and llvm::MCSymbolMachO::getEncodedFlags().
getCommonSize()
uint64_t llvm::MCSymbol::getCommonSize () const inline
Return the size of a 'common' symbol.
Definition at line 342 of file MCSymbol.h.
References assert(), CommonSize, and isCommon().
getFlags()
uint32_t llvm::MCSymbol::getFlags () const inline protected
Get the (implementation defined) symbol flags.
Definition at line 421 of file MCSymbol.h.
References Flags.
Referenced by llvm::MCSymbolCOFF::getClass(), llvm::MCSymbolMachO::getEncodedFlags(), llvm::MCSymbolCOFF::getWeakExternalCharacteristics(), llvm::MCSymbolGOFF::hasLDAttributes(), llvm::MCSymbolMachO::isAltEntry(), llvm::MCSymbolELF::isBindingSet(), llvm::MCSymbolMachO::isCold(), llvm::MCSymbolXCOFF::isEHInfo(), llvm::MCSymbolWasm::isExported(), llvm::MCSymbolELF::isMemtag(), llvm::MCSymbolMachO::isNoDeadStrip(), llvm::MCSymbolWasm::isNoStrip(), llvm::MCSymbolCOFF::isSafeSEH(), llvm::MCSymbolELF::isSignature(), llvm::MCSymbolMachO::isSymbolResolver(), llvm::MCSymbolWasm::isTLS(), llvm::MCSymbolMachO::isWeakDefinition(), llvm::MCSymbolELF::isWeakref(), llvm::MCSymbolMachO::isWeakReference(), llvm::MCSymbolELF::setBinding(), llvm::MCSymbolELF::setIsSignature(), llvm::MCSymbolELF::setIsWeakref(), llvm::MCSymbolELF::setMemtag(), llvm::MCSymbolELF::setOther(), llvm::MCSymbolELF::setType(), and llvm::MCSymbolELF::setVisibility().
getFragment()
MCFragment * llvm::MCSymbol::getFragment () const inline
Definition at line 397 of file MCSymbol.h.
References llvm::MCExpr::findAssociatedFragment(), Fragment, getVariableValue(), isVariable(), and isWeakExternal().
Referenced by attemptToFoldSymbolOffsetDifference(), llvm::MCExpr::findAssociatedFragment(), llvm::MachObjectWriter::getAtom(), getLabelOffset(), getOffsetAndDataFragment(), getPCRelHiFixup(), getSection(), llvm::MachObjectWriter::getSymbolAddress(), isAbsolute(), isInSection(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), isUndefined(), and llvm::LoongArchAsmBackend::shouldInsertFixupForCodeAlign().
getIndex()
uint32_t llvm::MCSymbol::getIndex () const inline
Get the (implementation defined) index.
Definition at line 316 of file MCSymbol.h.
References Index.
Referenced by llvm::DwarfDebug::insertSectionLabel(), writeFragment(), and llvm::WinCOFFWriter::writeObject().
getName()
StringRef llvm::MCSymbol::getName () const inline
getName - Get the symbol name.
Definition at line 207 of file MCSymbol.h.
References HasName.
Referenced by llvm::MCResourceInfo::createTotalNumSGPRs(), llvm::MCResourceInfo::createTotalNumVGPRs(), llvm::SystemZTargetHLASMStreamer::createWordDiffExpr(), llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::emitCOFFReplaceableFunctionData(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::EHStreamer::emitExceptionTable(), llvm::WebAssemblyTargetAsmStreamer::emitExportName(), llvm::WebAssemblyTargetAsmStreamer::emitFunctionType(), llvm::WebAssemblyTargetAsmStreamer::emitGlobalType(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::AsmPrinter::emitGlobalVariable(), llvm::WebAssemblyTargetAsmStreamer::emitImportModule(), llvm::WebAssemblyTargetAsmStreamer::emitImportName(), llvm::XtensaTargetAsmStreamer::emitLiteral(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::WebAssemblyTargetAsmStreamer::emitTableType(), llvm::WebAssemblyTargetAsmStreamer::emitTagType(), llvm::NVPTXTargetStreamer::emitValue(), llvm::MCStreamer::emitWinCFIBeginEpilogue(), llvm::MCStreamer::emitWinCFIEndEpilogue(), llvm::MCStreamer::emitWinCFIUnwindV2Start(), llvm::MCStreamer::emitWinCFIUnwindVersion(), llvm::MCExpr::evaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::ELFObjectWriter::executePostLayoutBinding(), llvm::RecordStreamer::flushSymverDirectives(), llvm::MCResourceInfo::gatherResourceInfo(), llvm::MCContext::getAssociativeCOFFSection(), getAuthPtrSlotSymbolHelper(), llvm::MCAssembler::getBaseSymbol(), llvm::MCContext::getCOFFSection(), llvm::MCContext::getELFSection(), llvm::MCSymbolMachO::getEncodedFlags(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::MCSymbolWasm::getImportName(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), getLabelOffset(), llvm::NVPTXTargetLowering::getParamName(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), getStaticStructorSection(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), llvm::MCSymbolXCOFF::getUnqualifiedName(), llvm::MCContext::getWasmSection(), hasGOTReference(), llvm::MCAsmBackend::isDarwinCanonicalPersonality(), print(), llvm::X86Operand::print(), llvm::WebAssemblyInstPrinter::printCatchList(), llvm::MipsAsmPrinter::printOperand(), llvm::SystemZInstPrinterCommon::printPCRelTLSOperand(), llvm::NVPTXInstPrinter::printProtoIdent(), llvm::PPCInstPrinter::printTLSCall(), llvm::MCContext::registerInlineAsmLabel(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), smallData(), llvm::stableHashValue(), startsWithGlobalOffsetTable(), and llvm::WinCOFFWriter::writeObject().
getOffset()
uint64_t llvm::MCSymbol::getOffset () const inline
Definition at line 327 of file MCSymbol.h.
References assert(), Offset, SymbolContents, SymContentsOffset, and SymContentsUnset.
Referenced by attemptToFoldSymbolOffsetDifference(), declareCommon(), getLabelOffset(), getOffsetAndDataFragment(), getPCRelHiFixup(), and setCommon().
getSection()
MCSection & llvm::MCSymbol::getSection () const inline
Get the section associated with a defined, non-absolute symbol.
Definition at line 270 of file MCSymbol.h.
References assert(), getFragment(), llvm::MCFragment::getParent(), and isInSection().
Referenced by llvm::MCLineSection::addEndEntry(), llvm::LoongArchAsmBackend::addReloc(), llvm::BTFDebug::beginFunctionImpl(), emitRangeList(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::RISCVAsmBackend::evaluateFixup(), llvm::ELFObjectWriter::executePostLayoutBinding(), llvm::MCContext::getCOFFSection(), llvm::DwarfDebug::insertSectionLabel(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::WinCOFFObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::ELFObjectWriter::useSectionSymbol(), and llvm::WinCOFFWriter::writeObject().
getVariableValue()
const MCExpr * llvm::MCSymbol::getVariableValue () const inline
Get the expression of the variable symbol.
Definition at line 306 of file MCSymbol.h.
References assert(), isVariable(), MCExpr, and Value.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::MachObjectWriter::findAliasedSymbol(), llvm::MCResourceInfo::gatherResourceInfo(), getFragment(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), llvm::AMDGPUMCExpr::isSymbolUsedInExpression(), knownBitsMapHelper(), and AMDGPUMCInstLower::lowerOperand().
isAbsolute()
bool llvm::MCSymbol::isAbsolute () const inline
isAbsolute - Check if this is an absolute symbol.
Definition at line 265 of file MCSymbol.h.
References AbsolutePseudoFragment, and getFragment().
isCOFF()
bool llvm::MCSymbol::isCOFF () const inline
Definition at line 286 of file MCSymbol.h.
References Kind, and SymbolKindCOFF.
Referenced by llvm::MCSymbolCOFF::classof().
isCommon()
bool llvm::MCSymbol::isCommon () const inline
Is this a 'common' symbol.
Definition at line 387 of file MCSymbol.h.
References SymbolContents, SymContentsCommon, and SymContentsTargetCommon.
Referenced by declareCommon(), llvm::MCAssembler::getBaseSymbol(), getCommonAlignment(), getCommonSize(), and llvm::MCSymbolMachO::getEncodedFlags().
isDefined()
bool llvm::MCSymbol::isDefined () const inline
isDefined - Check if this symbol is defined (i.e., it has an address).
Defined symbols are either absolute or in some section.
Definition at line 252 of file MCSymbol.h.
References isUndefined().
Referenced by llvm::DwarfCompileUnit::attachLowHighPC(), llvm::EHStreamer::computePadMap(), llvm::AsmPrinter::emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::AsmPrinter::emitGlobalVariable(), llvm::MCSymbolELF::getBinding(), llvm::MCContext::getCOFFSection(), getOffsetAndDataFragment(), isInSymtab(), and llvm::AddrLabelMap::UpdateForDeletedBlock().
isELF()
bool llvm::MCSymbol::isELF () const inline
Definition at line 284 of file MCSymbol.h.
References Kind, and SymbolKindELF.
Referenced by llvm::MCSymbolELF::classof(), and needsInterworking().
isExternal()
bool llvm::MCSymbol::isExternal () const inline
Definition at line 407 of file MCSymbol.h.
References IsExternal.
Referenced by llvm::ARMAsmBackend::shouldForceRelocation().
isGOFF()
bool llvm::MCSymbol::isGOFF () const inline
Definition at line 288 of file MCSymbol.h.
References Kind, and SymbolKindGOFF.
Referenced by llvm::MCSymbolGOFF::classof().
isInSection()
bool llvm::MCSymbol::isInSection () const inline
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
Definition at line 256 of file MCSymbol.h.
References AbsolutePseudoFragment, F, and getFragment().
Referenced by llvm::LoongArchAsmBackend::addReloc(), llvm::BTFDebug::beginFunctionImpl(), llvm::MCStreamer::endSection(), llvm::ELFObjectWriter::executePostLayoutBinding(), llvm::MachObjectWriter::getAtom(), llvm::MCContext::getCOFFSection(), getSection(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MCStreamer::switchSection(), llvm::MCStreamer::switchSectionNoPrint(), llvm::ELFObjectWriter::useSectionSymbol(), and llvm::WinCOFFWriter::writeObject().
isMachO()
bool llvm::MCSymbol::isMachO () const inline
Definition at line 290 of file MCSymbol.h.
References Kind, and SymbolKindMachO.
Referenced by llvm::MCSymbolMachO::classof(), and llvm::MCAsmBackend::isDarwinCanonicalPersonality().
isRedefinable()
bool llvm::MCSymbol::isRedefinable () const inline
Check if this symbol is redefinable.
Definition at line 227 of file MCSymbol.h.
References IsRedefinable.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
isRegistered()
bool llvm::MCSymbol::isRegistered () const inline
Definition at line 214 of file MCSymbol.h.
References IsRegistered.
Referenced by llvm::WinCOFFWriter::writeObject().
isResolving()
bool llvm::MCSymbol::isResolving () const inline
Definition at line 242 of file MCSymbol.h.
References IsResolving.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), and llvm::MCExpr::findAssociatedFragment().
isTargetCommon()
bool llvm::MCSymbol::isTargetCommon () const inline
Is this a target-specific common-like symbol.
Definition at line 393 of file MCSymbol.h.
References SymbolContents, and SymContentsTargetCommon.
Referenced by declareCommon().
isTemporary()
bool llvm::MCSymbol::isTemporary () const inline
isTemporary - Check if this is an assembler temporary symbol.
Definition at line 224 of file MCSymbol.h.
References IsTemporary.
Referenced by llvm::MCWinCOFFStreamer::emitCGProfileEntry(), isInSymtab(), llvm::MCSymbolMachO::isSymbolLinkerVisible(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), MCSymbol(), llvm::MCSymbolCOFF::MCSymbolCOFF(), llvm::MCSymbolELF::MCSymbolELF(), llvm::MCSymbolMachO::MCSymbolMachO(), llvm::MCSymbolWasm::MCSymbolWasm(), llvm::MCSymbolXCOFF::MCSymbolXCOFF(), and llvm::WinCOFFWriter::writeObject().
isUndefined()
bool llvm::MCSymbol::isUndefined () const inline
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
Definition at line 262 of file MCSymbol.h.
References getFragment().
Referenced by attemptToFoldSymbolOffsetDifference(), llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), llvm::AsmPrinter::emitConstantPool(), llvm::RISCVAsmBackend::evaluateFixup(), isDefined(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), and smallData().
isUnset()
bool llvm::MCSymbol::isUnset () const inline
Definition at line 325 of file MCSymbol.h.
References SymbolContents, and SymContentsUnset.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
isUsedInReloc()
bool llvm::MCSymbol::isUsedInReloc () const inline
Definition at line 218 of file MCSymbol.h.
References IsUsedInReloc.
Referenced by llvm::MCSymbolELF::getBinding(), isInSymtab(), and llvm::MCSymbolMachO::isSymbolLinkerVisible().
isVariable()
bool llvm::MCSymbol::isVariable () const inline
isVariable - Check if this is a variable symbol.
Definition at line 301 of file MCSymbol.h.
References SymbolContents, and SymContentsVariable.
Referenced by attemptToFoldSymbolOffsetDifference(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::AsmPrinter::emitGlobalVariable(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::MachObjectWriter::findAliasedSymbol(), llvm::MCResourceInfo::gatherResourceInfo(), getFragment(), getOffsetAndDataFragment(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), getVariableValue(), llvm::AMDGPUMCExpr::isSymbolUsedInExpression(), knownBitsMapHelper(), and setFragment().
isWasm()
bool llvm::MCSymbol::isWasm () const inline
Definition at line 292 of file MCSymbol.h.
References Kind, and SymbolKindWasm.
Referenced by llvm::MCSymbolWasm::classof().
isWeakExternal()
bool llvm::MCSymbol::isWeakExternal () const inline
Definition at line 411 of file MCSymbol.h.
References IsWeakExternal.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), and getFragment().
isXCOFF()
bool llvm::MCSymbol::isXCOFF () const inline
Definition at line 294 of file MCSymbol.h.
References Kind, and SymbolKindXCOFF.
Referenced by llvm::MCSymbolXCOFF::classof().
modifyFlags()
void llvm::MCSymbol::modifyFlags (uint32_t Value, uint32_t Mask) const inline protected
Modify the flags via a mask.
Definition at line 430 of file MCSymbol.h.
References assert(), Flags, NumFlagsBits, and Value.
Referenced by llvm::MCSymbolMachO::clearReferenceType(), llvm::MCSymbolMachO::setAltEntry(), llvm::MCSymbolCOFF::setClass(), llvm::MCSymbolMachO::setCold(), llvm::MCSymbolXCOFF::setEHInfo(), llvm::MCSymbolWasm::setExported(), llvm::MCSymbolCOFF::setIsSafeSEH(), llvm::MCSymbolGOFF::setLDAttributes(), llvm::MCSymbolMachO::setNoDeadStrip(), llvm::MCSymbolWasm::setNoStrip(), llvm::MCSymbolMachO::setReferenceTypeUndefinedLazy(), llvm::MCSymbolMachO::setSymbolResolver(), llvm::MCSymbolMachO::setThumbFunc(), llvm::MCSymbolWasm::setTLS(), llvm::MCSymbolMachO::setWeakDefinition(), llvm::MCSymbolCOFF::setWeakExternalCharacteristics(), and llvm::MCSymbolMachO::setWeakReference().
operator new()
void * MCSymbol::operator new (size_t s, const MCSymbolTableEntry * Name, MCContext & Ctx) protected
Definition at line 29 of file MCSymbol.cpp.
References MCContext, MCSymbol(), and Size.
operator=()
MCSymbol & llvm::MCSymbol::operator= (const MCSymbol &) protected delete
References LLVM_ABI, llvm_unreachable, MCContext, and MCSymbol().
print()
void MCSymbol::print (raw_ostream & OS, const MCAsmInfo * MAI) const
print - Print the value to the stream OS.
Definition at line 56 of file MCSymbol.cpp.
References llvm::CallingConv::C, getName(), llvm::MCAsmInfo::isValidUnquotedName(), llvm::report_fatal_error(), and llvm::MCAsmInfo::supportsNameQuoting().
Referenced by EmitInlineAsmStr(), llvm::operator<<(), llvm::M68kAsmPrinter::PrintAsmMemoryOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), printExpr(), printExpr(), llvm::ARMAsmPrinter::printOperand(), llvm::HexagonAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), and llvm::AsmPrinter::PrintSymbolOperand().
redefineIfPossible()
void llvm::MCSymbol::redefineIfPossible () inline
Prepare this symbol to be redefined.
Definition at line 231 of file MCSymbol.h.
References IsRedefinable, setUndefined(), SymbolContents, SymContentsUnset, SymContentsVariable, and Value.
Referenced by llvm::AMDGPUAsmPrinter::emitGlobalVariable(), and llvm::AsmPrinter::emitGlobalVariable().
setCommon()
void llvm::MCSymbol::setCommon (uint64_t Size, Align Alignment, bool Target = false) inline
Mark this symbol as being 'common'.
Parameters
Size - The size of the symbol.
Alignment - The alignment of the symbol.
Target - Is the symbol a target-specific common-like symbol.
Definition at line 352 of file MCSymbol.h.
References assert(), CommonAlignLog2, CommonSize, llvm::encode(), getOffset(), NumCommonAlignmentBits, Size, SymbolContents, SymContentsCommon, and SymContentsTargetCommon.
Referenced by declareCommon().
setExternal()
void llvm::MCSymbol::setExternal (bool Value) const inline
Definition at line 408 of file MCSymbol.h.
References IsExternal, and Value.
Referenced by llvm::MCContext::cloneSymbol(), and llvm::MCWinCOFFStreamer::finalizeCGProfileEntry().
setFlags()
void llvm::MCSymbol::setFlags (uint32_t Value) const inline protected
Set the (implementation defined) symbol flags.
Definition at line 424 of file MCSymbol.h.
References assert(), Flags, NumFlagsBits, and Value.
Referenced by llvm::MCSymbolELF::setBinding(), llvm::MCSymbolMachO::setDesc(), llvm::MCSymbolELF::setIsSignature(), llvm::MCSymbolELF::setIsWeakref(), llvm::MCSymbolELF::setMemtag(), llvm::MCSymbolELF::setOther(), llvm::MCSymbolELF::setType(), and llvm::MCSymbolELF::setVisibility().
setFragment()
void llvm::MCSymbol::setFragment (MCFragment * F) const inline
Mark the symbol as defined in the fragment F.
Definition at line 276 of file MCSymbol.h.
References assert(), F, Fragment, and isVariable().
Referenced by llvm::MCContext::getCOFFSection(), llvm::MCContext::getWasmSection(), llvm::MCContext::getXCOFFSection(), and llvm::LoongArchAsmBackend::shouldInsertFixupForCodeAlign().
setIndex()
void llvm::MCSymbol::setIndex (uint32_t Value) const inline
Set the (implementation defined) index.
Definition at line 321 of file MCSymbol.h.
References Index, and Value.
Referenced by llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS().
setIsRegistered()
void llvm::MCSymbol::setIsRegistered (bool Value) const inline
Definition at line 215 of file MCSymbol.h.
References IsRegistered, and Value.
Referenced by llvm::MCContext::cloneSymbol().
setIsResolving()
void llvm::MCSymbol::setIsResolving (bool V) inline
Definition at line 243 of file MCSymbol.h.
References IsResolving.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), and llvm::MCExpr::findAssociatedFragment().
setOffset()
void llvm::MCSymbol::setOffset (uint64_t Value) inline
Definition at line 333 of file MCSymbol.h.
References assert(), Offset, SymbolContents, SymContentsOffset, SymContentsUnset, and Value.
setRedefinable()
void llvm::MCSymbol::setRedefinable (bool Value) inline
Mark this symbol as redefinable.
Definition at line 229 of file MCSymbol.h.
References IsRedefinable, and Value.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
setUndefined()
void llvm::MCSymbol::setUndefined () inline
Mark the symbol as undefined.
Definition at line 282 of file MCSymbol.h.
References Fragment.
Referenced by llvm::WebAssembly::getOrCreateFunctionTableSymbol(), redefineIfPossible(), and setVariableValue().
setUsedInReloc()
void llvm::MCSymbol::setUsedInReloc () const inline
Definition at line 217 of file MCSymbol.h.
References IsUsedInReloc.
Referenced by llvm::ELFObjectWriter::executePostLayoutBinding().
setVariableValue()
void MCSymbol::setVariableValue (const MCExpr * Value)
Definition at line 46 of file MCSymbol.cpp.
References assert(), MCExpr, setUndefined(), SymbolContents, SymContentsUnset, SymContentsVariable, and Value.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::MCResourceInfo::gatherResourceInfo(), llvm::SIInstrInfo::insertIndirectBranch(), and llvm::RISCVAsmBackend::maybeAddVendorReloc().
Friends And Related Symbol Documentation
MCContext
friend class MCContext friend
Definition at line 154 of file MCSymbol.h.
References MCContext.
Referenced by MCContext, operator new(), and operator=().
MCExpr
friend class MCExpr friend
Definition at line 153 of file MCSymbol.h.
References MCExpr.
Referenced by llvm::MCSymbolELF::getSize(), llvm::MCSymbolWasm::getSize(), getVariableValue(), MCExpr, llvm::MCSymbolELF::setSize(), llvm::MCSymbolWasm::setSize(), and setVariableValue().
Member Data Documentation
[union]
union { ... } llvm::MCSymbol
AbsolutePseudoFragment
MCFragment * MCSymbol::AbsolutePseudoFragment = &SentinelFragment static protected
Definition at line 67 of file MCSymbol.h.
Referenced by llvm::MCExpr::findAssociatedFragment(), isAbsolute(), and isInSection().
CommonAlignLog2
unsigned llvm::MCSymbol::CommonAlignLog2 protected
Definition at line 131 of file MCSymbol.h.
Referenced by getCommonAlignment(), MCSymbol(), and setCommon().
CommonSize
uint64_t llvm::MCSymbol::CommonSize
The size of the symbol, if it is 'common'.
Definition at line 146 of file MCSymbol.h.
Referenced by declareCommon(), getCommonSize(), and setCommon().
Flags
uint32_t llvm::MCSymbol::Flags mutable protected
Definition at line 136 of file MCSymbol.h.
Referenced by llvm::MCSymbolELF::getBinding(), llvm::MCSymbolMachO::getEncodedFlags(), getFlags(), llvm::MCSymbolELF::getOther(), llvm::MCSymbolELF::getType(), llvm::MCSymbolELF::getVisibility(), MCSymbol(), modifyFlags(), and setFlags().
Fragment
MCFragment* llvm::MCSymbol::Fragment = nullptr mutable protected
If a symbol has a Fragment, the section is implied, so we only need one pointer.
The special AbsolutePseudoFragment value is for absolute symbols. If this is a variable symbol, this caches the variable value's fragment. FIXME: We might be able to simplify this by having the asm streamer create dummy fragments. If this is a section, then it gives the symbol is defined in. This is null for undefined symbols.
If this is a fragment, then it gives the fragment this symbol's value is relative to, if any.
Definition at line 80 of file MCSymbol.h.
Referenced by llvm::MCExpr::findAssociatedFragment(), getFragment(), setFragment(), and setUndefined().
HasName
unsigned llvm::MCSymbol::HasName protected
True if this symbol is named.
A named symbol will have a pointer to the name allocated in the bytes immediately prior to the MCSymbol.
Definition at line 84 of file MCSymbol.h.
Referenced by getName(), and MCSymbol().
Index
uint32_t llvm::MCSymbol::Index = 0 mutable protected
Index field, for use by the object file implementation.
Definition at line 139 of file MCSymbol.h.
Referenced by getIndex(), and setIndex().
IsExternal
unsigned llvm::MCSymbol::IsExternal mutable protected
True if this symbol is visible outside this translation unit.
Note: ELF uses binding instead of this bit.
Definition at line 98 of file MCSymbol.h.
Referenced by isExternal(), MCSymbol(), and setExternal().
IsPrivateExtern
unsigned llvm::MCSymbol::IsPrivateExtern mutable protected
Mach-O specific: This symbol is private extern.
Definition at line 101 of file MCSymbol.h.
Referenced by llvm::MCSymbolMachO::isPrivateExtern(), MCSymbol(), and llvm::MCSymbolMachO::setPrivateExtern().
IsRedefinable
unsigned llvm::MCSymbol::IsRedefinable protected
True if this symbol can be redefined.
Definition at line 92 of file MCSymbol.h.
Referenced by isRedefinable(), MCSymbol(), redefineIfPossible(), and setRedefinable().
IsRegistered
unsigned llvm::MCSymbol::IsRegistered mutable protected
Definition at line 94 of file MCSymbol.h.
Referenced by isRegistered(), MCSymbol(), and setIsRegistered().
IsResolving
unsigned llvm::MCSymbol::IsResolving protected
Used to detect cyclic dependency like a = a + 1 and a = b; b = a.
Definition at line 114 of file MCSymbol.h.
Referenced by isResolving(), MCSymbol(), and setIsResolving().
IsTemporary
unsigned llvm::MCSymbol::IsTemporary protected
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
Usually "Lfoo" or ".foo".
Definition at line 89 of file MCSymbol.h.
Referenced by llvm::MCContext::cloneSymbol(), isTemporary(), MCSymbol(), and llvm::MCSymbolGOFF::MCSymbolGOFF().
IsUsedInReloc
unsigned llvm::MCSymbol::IsUsedInReloc mutable protected
True if we have created a relocation that uses this symbol.
Definition at line 111 of file MCSymbol.h.
Referenced by isUsedInReloc(), MCSymbol(), and setUsedInReloc().
IsWeakExternal
unsigned llvm::MCSymbol::IsWeakExternal mutable protected
This symbol is weak external.
Definition at line 104 of file MCSymbol.h.
Referenced by isWeakExternal(), MCSymbol(), and llvm::MCSymbolCOFF::setIsWeakExternal().
Kind
unsigned llvm::MCSymbol::Kind protected
LLVM RTTI discriminator.
This is actually a SymbolKind enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
Definition at line 108 of file MCSymbol.h.
Referenced by isCOFF(), isELF(), isGOFF(), isMachO(), isWasm(), isXCOFF(), and MCSymbol().
Offset
uint64_t llvm::MCSymbol::Offset
The offset to apply to the fragment address to form this symbol's value.
Definition at line 143 of file MCSymbol.h.
Referenced by getOffset(), MCSymbol(), and setOffset().
SymbolContents
unsigned llvm::MCSymbol::SymbolContents protected
This is actually a Contents enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
Definition at line 118 of file MCSymbol.h.
Referenced by getOffset(), isCommon(), isTargetCommon(), isUnset(), isVariable(), MCSymbol(), redefineIfPossible(), setCommon(), setOffset(), and setVariableValue().
Value
const MCExpr* llvm::MCSymbol::Value
If non-null, the value for a variable symbol.
Definition at line 149 of file MCSymbol.h.
Referenced by getVariableValue(), modifyFlags(), redefineIfPossible(), llvm::MCSymbolMachO::setDesc(), setExternal(), setFlags(), setIndex(), setIsRegistered(), setOffset(), llvm::MCSymbolMachO::setPrivateExtern(), setRedefinable(), llvm::MCSymbolMachO::setReferenceTypeUndefinedLazy(), and setVariableValue().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSymbol.h
lib/MC/MCSymbol.cpp