LLVM: llvm::ARM::WinEH::RuntimeFunctionARM64 Class Reference
llvm::ARM::WinEH::RuntimeFunctionARM64 Class Reference
RuntimeFunctionARM64 - An entry in the table of procedure data (.pdata)
#include "llvm/Support/ARMWinEH.h"
Public Member Functions
RuntimeFunctionARM64 (const support::ulittle32_t *Data)
RuntimeFunctionARM64 (const support::ulittle32_t BeginAddress, const support::ulittle32_t UnwindData)
RuntimeFunctionFlag Flag () const
uint32_t ExceptionInformationRVA () const
uint32_t PackedUnwindData () const
uint32_t FunctionLength () const
uint8_t RegF () const
uint8_t RegI () const
bool H () const
uint8_t CR () const
uint16_t FrameSize () const
Public Attributes
const support::ulittle32_t BeginAddress
const support::ulittle32_t UnwindData
Detailed Description
RuntimeFunctionARM64 - An entry in the table of procedure data (.pdata)
3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 +------------------------------------------------------------—+ | Function Start RVA | +--------------—+—+-+----—+--—+------------------—+—+ | Frame Size |CR |H| RegI |RegF | Function Length |Flg| +--------------—+—+-+----—+--—+------------------—+—+
See https://docs.microsoft.com/en-us/cpp/build/arm64-exception-handling for the full reference for this struct.
Definition at line 225 of file ARMWinEH.h.
Constructor & Destructor Documentation
RuntimeFunctionARM64() [1/2]
llvm::ARM::WinEH::RuntimeFunctionARM64::RuntimeFunctionARM64 (const support::ulittle32_t * Data) inline
Definition at line 230 of file ARMWinEH.h.
References BeginAddress, llvm::Data, and UnwindData.
RuntimeFunctionARM64() [2/2]
llvm::ARM::WinEH::RuntimeFunctionARM64::RuntimeFunctionARM64 (const support::ulittle32_t BeginAddress, const support::ulittle32_t UnwindData) inline
Definition at line 233 of file ARMWinEH.h.
References BeginAddress, and UnwindData.
Member Function Documentation
CR()
uint8_t llvm::ARM::WinEH::RuntimeFunctionARM64::CR () const inline
Definition at line 277 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Packed, llvm::ARM::WinEH::RFF_PackedFragment, and UnwindData.
ExceptionInformationRVA()
uint32_t llvm::ARM::WinEH::RuntimeFunctionARM64::ExceptionInformationRVA () const inline
Definition at line 241 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Unpacked, and UnwindData.
Flag()
RuntimeFunctionFlag llvm::ARM::WinEH::RuntimeFunctionARM64::Flag () const inline
Definition at line 237 of file ARMWinEH.h.
References UnwindData.
Referenced by CR(), ExceptionInformationRVA(), FrameSize(), FunctionLength(), H(), PackedUnwindData(), RegF(), and RegI().
FrameSize()
uint16_t llvm::ARM::WinEH::RuntimeFunctionARM64::FrameSize () const inline
Definition at line 283 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Packed, llvm::ARM::WinEH::RFF_PackedFragment, and UnwindData.
FunctionLength()
uint32_t llvm::ARM::WinEH::RuntimeFunctionARM64::FunctionLength () const inline
Definition at line 253 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Packed, llvm::ARM::WinEH::RFF_PackedFragment, and UnwindData.
H()
bool llvm::ARM::WinEH::RuntimeFunctionARM64::H () const inline
Definition at line 271 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Packed, llvm::ARM::WinEH::RFF_PackedFragment, and UnwindData.
PackedUnwindData()
uint32_t llvm::ARM::WinEH::RuntimeFunctionARM64::PackedUnwindData () const inline
Definition at line 247 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Packed, llvm::ARM::WinEH::RFF_PackedFragment, and UnwindData.
RegF()
uint8_t llvm::ARM::WinEH::RuntimeFunctionARM64::RegF () const inline
Definition at line 259 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Packed, llvm::ARM::WinEH::RFF_PackedFragment, and UnwindData.
RegI()
uint8_t llvm::ARM::WinEH::RuntimeFunctionARM64::RegI () const inline
Definition at line 265 of file ARMWinEH.h.
References assert(), Flag(), llvm::ARM::WinEH::RFF_Packed, llvm::ARM::WinEH::RFF_PackedFragment, and UnwindData.
Member Data Documentation
BeginAddress
const support::ulittle32_t llvm::ARM::WinEH::RuntimeFunctionARM64::BeginAddress
Definition at line 227 of file ARMWinEH.h.
Referenced by RuntimeFunctionARM64(), and RuntimeFunctionARM64().
UnwindData
const support::ulittle32_t llvm::ARM::WinEH::RuntimeFunctionARM64::UnwindData
Definition at line 228 of file ARMWinEH.h.
Referenced by CR(), ExceptionInformationRVA(), Flag(), FrameSize(), FunctionLength(), H(), PackedUnwindData(), RegF(), RegI(), RuntimeFunctionARM64(), and RuntimeFunctionARM64().
The documentation for this class was generated from the following file:
include/llvm/Support/ARMWinEH.h