LLVM: llvm::sandboxir::DGNode Class Reference
llvm::sandboxir::DGNode Class Reference
A DependencyGraph Node that points to an Instruction and contains memory dependency edges.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h"
Public Types
using iterator = PredIterator
Public Member Functions
DGNode (Instruction *I)
DGNode (const DGNode &Other)=delete
virtual ~DGNode ()
unsigned getNumUnscheduledSuccs () const
\Returns the number of unscheduled successors.
void decrUnscheduledSuccs ()
void incrUnscheduledSuccs ()
void resetScheduleState ()
bool ready () const
\Returns true if all dependent successors have been scheduled.
bool scheduled () const
\Returns true if this node has been scheduled.
void setScheduled (bool NewVal)
SchedBundle * getSchedBundle () const
\Returns the scheduling bundle that this node belongs to, or nullptr.
bool comesBefore (const DGNode *Other)
\Returns true if this is before Other in program order.
virtual iterator preds_begin (DependencyGraph &DAG)
virtual iterator preds_end (DependencyGraph &DAG)
iterator preds_begin (DependencyGraph &DAG) const
iterator preds_end (DependencyGraph &DAG) const
iterator_range< iterator > preds (DependencyGraph &DAG) const
\Returns a range of DAG predecessors nodes.
Instruction * getInstruction () const
virtual void print (raw_ostream &OS, bool PrintDeps=true) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool isStackSaveOrRestoreIntrinsic (Instruction *I)
static bool isMemIntrinsic (IntrinsicInst *I)
\Returns true if intrinsic I touches memory.
static bool isMemDepCandidate (Instruction *I)
We consider I as a Memory Dependency Candidate instruction if it reads/write memory or if it has side-effects.
static bool isFenceLike (Instruction *I)
\Returns true if I is fence like. It excludes non-mem intrinsics.
static bool isMemDepNodeCandidate (Instruction *I)
\Returns true if I is a memory dependency candidate instruction.
Protected Member Functions
void setSchedBundle (SchedBundle &SB)
void clearSchedBundle ()
DGNode (Instruction *I, DGNodeID ID)
Protected Attributes
Instruction * I
DGNodeID SubclassID
For isa/dyn_cast etc.
unsigned UnscheduledSuccs = 0
The number of unscheduled successors.
bool Scheduled = false
This is true if this node has been scheduled.
SchedBundle * SB = nullptr
The scheduler bundle that this node belongs to.
Friends
class SchedBundle
class MemDGNode
class DependencyGraph
raw_ostream & operator<< (raw_ostream &OS, DGNode &N)
Detailed Description
A DependencyGraph Node that points to an Instruction and contains memory dependency edges.
Definition at line 95 of file DependencyGraph.h.
Member Typedef Documentation
iterator
using llvm::sandboxir::DGNode::iterator = PredIterator
Definition at line 143 of file DependencyGraph.h.
Constructor & Destructor Documentation
DGNode() [1/3]
llvm::sandboxir::DGNode::DGNode (Instruction * I, DGNodeID ID) inline protected
Definition at line 112 of file DependencyGraph.h.
References I, and SubclassID.
Referenced by llvm::sandboxir::MemDGNode::classof(), comesBefore(), DGNode(), DGNode(), llvm::sandboxir::MemDGNode::hasMemPred(), llvm::sandboxir::MemDGNode::MemDGNode(), operator<<, preds_begin(), and preds_end().
DGNode() [2/3]
llvm::sandboxir::DGNode::DGNode (Instruction * I) inline
Definition at line 117 of file DependencyGraph.h.
References assert(), DGNode(), I, isMemDepNodeCandidate(), and SubclassID.
DGNode() [3/3]
llvm::sandboxir::DGNode::DGNode (const DGNode & Other) delete
References DGNode(), and llvm::Other.
~DGNode()
llvm::sandboxir::DGNode::~DGNode () virtual
Definition at line 80 of file DependencyGraph.cpp.
References SB.
Member Function Documentation
clearSchedBundle()
void llvm::sandboxir::DGNode::clearSchedBundle () inline protected
Definition at line 109 of file DependencyGraph.h.
comesBefore()
bool llvm::sandboxir::DGNode::comesBefore (const DGNode * Other) inline
\Returns true if this is before Other in program order.
Definition at line 142 of file DependencyGraph.h.
References DGNode(), I, and llvm::Other.
decrUnscheduledSuccs()
void llvm::sandboxir::DGNode::decrUnscheduledSuccs () inline
Definition at line 125 of file DependencyGraph.h.
References assert(), and UnscheduledSuccs.
Referenced by llvm::sandboxir::MemDGNode::removeMemPred().
dump()
void llvm::sandboxir::DGNode::dump () const
Definition at line 90 of file DependencyGraph.cpp.
References llvm::dbgs(), and print().
getInstruction()
Instruction * llvm::sandboxir::DGNode::getInstruction () const inline
Definition at line 206 of file DependencyGraph.h.
References I.
Referenced by llvm::sandboxir::SchedBundle::getBot(), llvm::sandboxir::SchedBundle::getTop(), llvm::sandboxir::PriorityCmp::operator()(), and llvm::sandboxir::DependencyGraph::print().
getNumUnscheduledSuccs()
unsigned llvm::sandboxir::DGNode::getNumUnscheduledSuccs () const inline
\Returns the number of unscheduled successors.
Definition at line 123 of file DependencyGraph.h.
References UnscheduledSuccs.
getSchedBundle()
SchedBundle * llvm::sandboxir::DGNode::getSchedBundle () const inline
\Returns the scheduling bundle that this node belongs to, or nullptr.
Definition at line 140 of file DependencyGraph.h.
References SB, and SchedBundle.
incrUnscheduledSuccs()
void llvm::sandboxir::DGNode::incrUnscheduledSuccs () inline
Definition at line 129 of file DependencyGraph.h.
References UnscheduledSuccs.
isFenceLike()
bool llvm::sandboxir::DGNode::isFenceLike (Instruction * I) inline static
\Returns true if I is fence like. It excludes non-mem intrinsics.
Definition at line 191 of file DependencyGraph.h.
References llvm::dyn_cast(), I, II, and isMemIntrinsic().
Referenced by isMemDepNodeCandidate(), and llvm::sandboxir::isOrdered().
isMemDepCandidate()
bool llvm::sandboxir::DGNode::isMemDepCandidate (Instruction * I) inline static
We consider I as a Memory Dependency Candidate instruction if it reads/write memory or if it has side-effects.
This is used by the dependency graph.
Definition at line 184 of file DependencyGraph.h.
References llvm::dyn_cast(), I, II, and isMemIntrinsic().
Referenced by isMemDepNodeCandidate(), and llvm::sandboxir::isOrdered().
isMemDepNodeCandidate()
bool llvm::sandboxir::DGNode::isMemDepNodeCandidate (Instruction * I) inline static
\Returns true if I is a memory dependency candidate instruction.
Definition at line 198 of file DependencyGraph.h.
References llvm::dyn_cast(), I, isFenceLike(), isMemDepCandidate(), isStackSaveOrRestoreIntrinsic(), and llvm::sandboxir::AllocaInst::isUsedWithInAlloca().
Referenced by DGNode(), llvm::sandboxir::MemDGNodeIntervalBuilder::getBotMemDGNode(), llvm::sandboxir::DependencyGraph::getOrCreateNode(), llvm::sandboxir::MemDGNodeIntervalBuilder::getTopMemDGNode(), and llvm::sandboxir::MemDGNode::MemDGNode().
isMemIntrinsic()
bool llvm::sandboxir::DGNode::isMemIntrinsic (IntrinsicInst * I) inline static
\Returns true if intrinsic I touches memory.
This is used by the dependency graph.
Definition at line 176 of file DependencyGraph.h.
References I.
Referenced by isFenceLike(), and isMemDepCandidate().
isStackSaveOrRestoreIntrinsic()
bool llvm::sandboxir::DGNode::isStackSaveOrRestoreIntrinsic (Instruction * I) inline static
Definition at line 166 of file DependencyGraph.h.
References llvm::dyn_cast(), I, and II.
Referenced by isMemDepNodeCandidate().
preds()
iterator_range< iterator > llvm::sandboxir::DGNode::preds (DependencyGraph & DAG) const inline
\Returns a range of DAG predecessors nodes.
If this is a MemDGNode then this will also include the memory dependency predecessors. Please note that this can include the same node more than once, if for example it's both a use-def predecessor and a mem dep predecessor.
Definition at line 162 of file DependencyGraph.h.
References DependencyGraph, llvm::make_range(), preds_begin(), and preds_end().
preds_begin() [1/2]
virtual iterator llvm::sandboxir::DGNode::preds_begin (DependencyGraph & DAG) inline virtual
Reimplemented in llvm::sandboxir::MemDGNode.
Definition at line 144 of file DependencyGraph.h.
References DependencyGraph, and I.
Referenced by preds(), and preds_begin().
preds_begin() [2/2]
iterator llvm::sandboxir::DGNode::preds_begin (DependencyGraph & DAG) const inline
Definition at line 152 of file DependencyGraph.h.
References DependencyGraph, DGNode(), and preds_begin().
preds_end() [1/2]
virtual iterator llvm::sandboxir::DGNode::preds_end (DependencyGraph & DAG) inline virtual
Reimplemented in llvm::sandboxir::MemDGNode.
Definition at line 149 of file DependencyGraph.h.
References DependencyGraph, and I.
Referenced by preds(), and preds_end().
preds_end() [2/2]
iterator llvm::sandboxir::DGNode::preds_end (DependencyGraph & DAG) const inline
Definition at line 155 of file DependencyGraph.h.
References DependencyGraph, DGNode(), and preds_end().
print()
void llvm::sandboxir::DGNode::print (raw_ostream & OS, bool PrintDeps = true) const virtual
Reimplemented in llvm::sandboxir::MemDGNode.
Definition at line 87 of file DependencyGraph.cpp.
References I, Scheduled, and UnscheduledSuccs.
Referenced by dump(), and llvm::sandboxir::MemDGNode::print().
ready()
bool llvm::sandboxir::DGNode::ready () const inline
\Returns true if all dependent successors have been scheduled.
Definition at line 135 of file DependencyGraph.h.
References UnscheduledSuccs.
resetScheduleState()
void llvm::sandboxir::DGNode::resetScheduleState () inline
Definition at line 130 of file DependencyGraph.h.
References Scheduled, and UnscheduledSuccs.
scheduled()
bool llvm::sandboxir::DGNode::scheduled () const inline
\Returns true if this node has been scheduled.
Definition at line 137 of file DependencyGraph.h.
References Scheduled.
setSchedBundle()
void llvm::sandboxir::DGNode::setSchedBundle (SchedBundle & SB) protected
Definition at line 74 of file DependencyGraph.cpp.
References SB, and SchedBundle.
setScheduled()
void llvm::sandboxir::DGNode::setScheduled (bool NewVal) inline
Definition at line 138 of file DependencyGraph.h.
References Scheduled.
Friends And Related Symbol Documentation
DependencyGraph
friend class DependencyGraph friend
Definition at line 114 of file DependencyGraph.h.
References DependencyGraph.
Referenced by DependencyGraph, preds(), preds_begin(), preds_begin(), preds_end(), and preds_end().
MemDGNode
friend class MemDGNode friend
Definition at line 113 of file DependencyGraph.h.
References MemDGNode.
Referenced by MemDGNode.
operator<<
raw_ostream & operator<< (raw_ostream & OS, DGNode & N) friend
Definition at line 210 of file DependencyGraph.h.
References DGNode(), and N.
SchedBundle
friend class SchedBundle friend
Definition at line 110 of file DependencyGraph.h.
References SchedBundle.
Referenced by getSchedBundle(), SchedBundle, and setSchedBundle().
Member Data Documentation
I
Instruction* llvm::sandboxir::DGNode::I protected
Definition at line 97 of file DependencyGraph.h.
Referenced by comesBefore(), DGNode(), DGNode(), getInstruction(), isFenceLike(), isMemDepCandidate(), isMemDepNodeCandidate(), isMemIntrinsic(), isStackSaveOrRestoreIntrinsic(), llvm::sandboxir::MemDGNode::MemDGNode(), preds_begin(), llvm::sandboxir::MemDGNode::preds_begin(), preds_end(), llvm::sandboxir::MemDGNode::preds_end(), and print().
SB
SchedBundle* llvm::sandboxir::DGNode::SB = nullptr protected
The scheduler bundle that this node belongs to.
Definition at line 106 of file DependencyGraph.h.
Referenced by getSchedBundle(), setSchedBundle(), and ~DGNode().
Scheduled
bool llvm::sandboxir::DGNode::Scheduled = false protected
This is true if this node has been scheduled.
Definition at line 104 of file DependencyGraph.h.
Referenced by llvm::sandboxir::MemDGNode::addMemPred(), print(), llvm::sandboxir::MemDGNode::removeMemPred(), resetScheduleState(), scheduled(), and setScheduled().
SubclassID
DGNodeID llvm::sandboxir::DGNode::SubclassID protected
For isa/dyn_cast etc.
Definition at line 100 of file DependencyGraph.h.
Referenced by DGNode(), and DGNode().
UnscheduledSuccs
unsigned llvm::sandboxir::DGNode::UnscheduledSuccs = 0 protected
The number of unscheduled successors.
Definition at line 102 of file DependencyGraph.h.
Referenced by llvm::sandboxir::MemDGNode::addMemPred(), decrUnscheduledSuccs(), getNumUnscheduledSuccs(), incrUnscheduledSuccs(), print(), ready(), and resetScheduleState().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h
lib/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.cpp