LLVM: llvm::PartialOrderingVisitor Class Reference
llvm::PartialOrderingVisitor Class Reference
#include "Target/SPIRV/SPIRVUtils.h"
Public Member Functions
size_t GetNodeRank (BasicBlock *BB) const
PartialOrderingVisitor (Function &F)
bool compare (const BasicBlock *LHS, const BasicBlock *RHS) const
void partialOrderVisit (BasicBlock &Start, std::function< bool(BasicBlock *)> Op)
Detailed Description
Definition at line 69 of file SPIRVUtils.h.
Constructor & Destructor Documentation
PartialOrderingVisitor()
llvm::PartialOrderingVisitor::PartialOrderingVisitor (Function & F)
Definition at line 667 of file SPIRVUtils.cpp.
References F, Info, LHS, and RHS.
Member Function Documentation
compare()
bool llvm::PartialOrderingVisitor::compare (const BasicBlock * LHS, const BasicBlock * RHS) const
Definition at line 682 of file SPIRVUtils.cpp.
References LHS, and RHS.
GetNodeRank()
size_t llvm::PartialOrderingVisitor::GetNodeRank (BasicBlock * BB) const
Definition at line 600 of file SPIRVUtils.cpp.
References assert(), P, and llvm::predecessors().
partialOrderVisit()
void llvm::PartialOrderingVisitor::partialOrderVisit (BasicBlock & Start, std::function< bool(BasicBlock *)> Op)
Definition at line 691 of file SPIRVUtils.cpp.
References assert().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVUtils.h
lib/Target/SPIRV/SPIRVUtils.cpp