LLVM: llvm::InLineChangePrinter Class Reference
llvm::InLineChangePrinter Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
InLineChangePrinter (bool VerboseMode, bool ColourMode)
~InLineChangePrinter () override
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Public Member Functions inherited from llvm::ChangeReporter< IRDataT< EmptyData > >
virtual ~ChangeReporter ()
void saveIRBeforePass (Any IR, StringRef PassID, StringRef PassName)
void handleIRAfterPass (Any IR, StringRef PassID, StringRef PassName)
void handleInvalidatedPass (StringRef PassID)
Protected Member Functions
void generateIRRepresentation (Any IR, StringRef PassID, IRDataT< EmptyData > &Output) override
void handleAfter (StringRef PassID, std::string &Name, const IRDataT< EmptyData > &Before, const IRDataT< EmptyData > &After, Any) override
void handleFunctionCompare (StringRef Name, StringRef Prefix, StringRef PassID, StringRef Divider, bool InModule, unsigned Minor, const FuncDataT< EmptyData > &Before, const FuncDataT< EmptyData > &After)
Protected Member Functions inherited from llvm::TextChangeReporter< IRDataT< EmptyData > >
TextChangeReporter (bool Verbose)
void handleInitialIR (Any IR) override
void omitAfter (StringRef PassID, std::string &Name) override
void handleInvalidated (StringRef PassID) override
void handleFiltered (StringRef PassID, std::string &Name) override
void handleIgnored (StringRef PassID, std::string &Name) override
Protected Member Functions inherited from llvm::ChangeReporter< IRDataT< EmptyData > >
ChangeReporter (bool RunInVerboseMode)
void registerRequiredCallbacks (PassInstrumentationCallbacks &PIC)
Protected Attributes
bool UseColour
Protected Attributes inherited from llvm::TextChangeReporter< IRDataT< EmptyData > >
raw_ostream & Out
Protected Attributes inherited from llvm::ChangeReporter< IRDataT< EmptyData > >
std::vector< IRDataT< EmptyData > > BeforeStack
bool InitialIR
const bool VerboseMode
Detailed Description
Definition at line 448 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
InLineChangePrinter()
llvm::InLineChangePrinter::InLineChangePrinter (bool VerboseMode, bool ColourMode) inline
Definition at line 451 of file StandardInstrumentations.h.
References llvm::TextChangeReporter< IRDataT< EmptyData > >::TextChangeReporter(), UseColour, and llvm::ChangeReporter< IRDataT< EmptyData > >::VerboseMode.
~InLineChangePrinter()
InLineChangePrinter::~InLineChangePrinter () override default
References generateIRRepresentation(), handleAfter(), handleFunctionCompare(), IR, and PIC.
Member Function Documentation
generateIRRepresentation()
void InLineChangePrinter::generateIRRepresentation (Any IR, StringRef PassID, IRDataT< EmptyData > & Output) override protected virtual
Implements llvm::ChangeReporter< IRDataT< EmptyData > >.
Definition at line 1512 of file StandardInstrumentations.cpp.
References llvm::IRComparer< T >::analyzeIR(), D(), and IR.
Referenced by ~InLineChangePrinter().
handleAfter()
void InLineChangePrinter::handleAfter (StringRef PassID, std::string & Name, const IRDataT< EmptyData > & Before, const IRDataT< EmptyData > & After, Any IR) override protected virtual
Implements llvm::ChangeReporter< IRDataT< EmptyData > >.
Definition at line 1518 of file StandardInstrumentations.cpp.
References llvm::IRComparer< T >::compare(), llvm::formatv(), handleFunctionCompare(), IR, and llvm::TextChangeReporter< IRDataT< EmptyData > >::Out.
Referenced by ~InLineChangePrinter().
handleFunctionCompare()
void InLineChangePrinter::handleFunctionCompare (StringRef Name, StringRef Prefix, StringRef PassID, StringRef Divider, bool InModule, unsigned Minor, const FuncDataT< EmptyData > & Before, const FuncDataT< EmptyData > & After) protected
Definition at line 1536 of file StandardInstrumentations.cpp.
References A(), B(), llvm::doSystemDiff(), llvm::TextChangeReporter< IRDataT< EmptyData > >::Out, llvm::OrderedChangedData< BlockDataT< T > >::report(), and UseColour.
Referenced by handleAfter(), and ~InLineChangePrinter().
registerCallbacks()
void InLineChangePrinter::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 1557 of file StandardInstrumentations.cpp.
References llvm::ColourDiffQuiet, llvm::ColourDiffVerbose, llvm::DiffQuiet, llvm::DiffVerbose, PIC, llvm::PrintChanged, llvm::ChangeReporter< IRDataT< EmptyData > >::registerRequiredCallbacks(), and llvm::TextChangeReporter< IRDataT< EmptyData > >::TextChangeReporter().
Member Data Documentation
UseColour
bool llvm::InLineChangePrinter::UseColour protected
Definition at line 472 of file StandardInstrumentations.h.
Referenced by handleFunctionCompare(), and InLineChangePrinter().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp