LLVM: llvm::MCEncodedFragment Class Reference
llvm::MCEncodedFragment Class Reference
Interface implemented by fragments that contain encoded instructions and/or data.
#include "llvm/MC/MCSection.h"
Public Member Functions
bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
void setAlignToBundleEnd (bool V)
uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment.
void setBundlePadding (uint8_t N)
Set the padding size for this fragment.
const MCSubtargetInfo * getSubtargetInfo () const
Retrieve the MCSubTargetInfo in effect when the instruction was encoded.
void setHasInstructions (const MCSubtargetInfo &STI)
Record that the fragment contains instructions with the MCSubtargetInfo in effect when the instruction was encoded.
bool getAllowAutoPadding () const
void setAllowAutoPadding (bool V)
void clearContents ()
SmallVectorImpl< char > & getContentsForAppending ()
void doneAppending ()
void appendContents (ArrayRef< char > Contents)
void appendContents (size_t Num, char Elt)
LLVM_ABI void setContents (ArrayRef< char > Contents)
MutableArrayRef< char > getContents ()
ArrayRef< char > getContents () const
void clearFixups ()
LLVM_ABI void addFixup (MCFixup Fixup)
LLVM_ABI void appendFixups (ArrayRef< MCFixup > Fixups)
LLVM_ABI void setFixups (ArrayRef< MCFixup > Fixups)
MutableArrayRef< MCFixup > getFixups ()
ArrayRef< MCFixup > getFixups () const
size_t getSize () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
MCFragment * getNext () const
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
LLVM_ABI const MCSymbol * getAtom () const
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it?
bool isLinkerRelaxable () const
void setLinkerRelaxable ()
LLVM_ABI void dump () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Protected Member Functions
MCEncodedFragment (MCFragment::FragmentType FType, bool HasInstructions)
Protected Member Functions inherited from llvm::MCFragment
LLVM_ABI MCFragment (FragmentType Kind, bool HasInstructions)
Protected Attributes
const MCSubtargetInfo * STI = nullptr
The MCSubtargetInfo in effect when the instruction was encoded.
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions: 1
Used by subclasses for better packing.
bool AlignToBundleEnd: 1
bool LinkerRelaxable: 1
MCDataFragment.
bool AllowAutoPadding: 1
MCRelaxableFragment: x86-specific.
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Data , FT_Relaxable , FT_Align , FT_Fill ,
FT_LEB , FT_Nops , FT_Org , FT_Dwarf ,
FT_DwarfFrame , FT_BoundaryAlign , FT_SymbolId , FT_CVInlineLines ,
FT_CVDefRange , FT_PseudoProbe
}
Detailed Description
Interface implemented by fragments that contain encoded instructions and/or data.
Definition at line 299 of file MCSection.h.
Constructor & Destructor Documentation
MCEncodedFragment()
llvm::MCEncodedFragment::MCEncodedFragment (MCFragment::FragmentType FType, bool HasInstructions) inline protected
Definition at line 307 of file MCSection.h.
References llvm::MCFragment::HasInstructions, and llvm::MCFragment::MCFragment().
Referenced by llvm::MCCVDefRangeFragment::MCCVDefRangeFragment(), llvm::MCCVInlineLineTableFragment::MCCVInlineLineTableFragment(), llvm::MCDataFragment::MCDataFragment(), llvm::MCDwarfCallFrameFragment::MCDwarfCallFrameFragment(), llvm::MCDwarfLineAddrFragment::MCDwarfLineAddrFragment(), llvm::MCLEBFragment::MCLEBFragment(), llvm::MCPseudoProbeAddrFragment::MCPseudoProbeAddrFragment(), and llvm::MCRelaxableFragment::MCRelaxableFragment().
Member Function Documentation
addFixup()
void MCEncodedFragment::addFixup (MCFixup Fixup)
Definition at line 95 of file MCSection.cpp.
References appendFixups(), and Fixup.
Referenced by llvm::LoongArchAsmBackend::relaxLEB128(), and llvm::RISCVAsmBackend::relaxLEB128().
alignToBundleEnd()
bool llvm::MCEncodedFragment::alignToBundleEnd () const inline
Should this fragment be placed at the end of an aligned bundle?
Definition at line 333 of file MCSection.h.
References llvm::MCFragment::AlignToBundleEnd.
Referenced by llvm::MCAssembler::writeFragmentPadding().
appendContents() [1/2]
void llvm::MCEncodedFragment::appendContents (ArrayRef< char > Contents) inline
Definition at line 379 of file MCSection.h.
References llvm::SmallVectorImpl< T >::append(), llvm::ArrayRef< T >::begin(), doneAppending(), llvm::ArrayRef< T >::end(), and getContentsForAppending().
appendContents() [2/2]
void llvm::MCEncodedFragment::appendContents (size_t Num, char Elt) inline
Definition at line 383 of file MCSection.h.
References llvm::SmallVectorImpl< T >::append(), doneAppending(), and getContentsForAppending().
appendFixups()
void MCEncodedFragment::appendFixups (ArrayRef< MCFixup > Fixups)
Definition at line 97 of file MCSection.cpp.
References llvm::MCFragment::getParent(), I, LLVM_UNLIKELY, and Size.
Referenced by addFixup().
classof()
bool llvm::MCEncodedFragment::classof (const MCFragment * F) inline static
Definition at line 315 of file MCSection.h.
References F, llvm::MCFragment::FT_CVDefRange, llvm::MCFragment::FT_CVInlineLines, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Dwarf, llvm::MCFragment::FT_DwarfFrame, llvm::MCFragment::FT_LEB, llvm::MCFragment::FT_PseudoProbe, llvm::MCFragment::FT_Relaxable, and llvm::MCFragment::MCFragment().
clearContents()
void llvm::MCEncodedFragment::clearContents () inline
Definition at line 363 of file MCSection.h.
clearFixups()
void llvm::MCEncodedFragment::clearFixups () inline
Definition at line 399 of file MCSection.h.
doneAppending()
void llvm::MCEncodedFragment::doneAppending () inline
Definition at line 378 of file MCSection.h.
References llvm::MCFragment::getParent(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by appendContents(), and appendContents().
getAllowAutoPadding()
bool llvm::MCEncodedFragment::getAllowAutoPadding () const inline
Definition at line 358 of file MCSection.h.
References llvm::MCFragment::AllowAutoPadding.
getBundlePadding()
uint8_t llvm::MCEncodedFragment::getBundlePadding () const inline
Get the padding size that must be inserted before this fragment.
Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
Definition at line 341 of file MCSection.h.
Referenced by llvm::MCAssembler::writeFragmentPadding().
getContents() [1/2]
MutableArrayRef< char > llvm::MCEncodedFragment::getContents () inline
Definition at line 388 of file MCSection.h.
References llvm::MCFragment::getParent(), llvm::MutableArrayRef(), and llvm::MutableArrayRef< T >::slice().
getContents() [2/2]
ArrayRef< char > llvm::MCEncodedFragment::getContents () const inline
Definition at line 392 of file MCSection.h.
References llvm::ArrayRef(), llvm::MCFragment::getParent(), and llvm::ArrayRef< T >::slice().
getContentsForAppending()
SmallVectorImpl< char > & llvm::MCEncodedFragment::getContentsForAppending () inline
Definition at line 366 of file MCSection.h.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MCFragment::getParent(), I, LLVM_UNLIKELY, llvm::SmallVectorImpl< T >::reserve(), Size, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by appendContents(), and appendContents().
getFixups() [1/2]
MutableArrayRef< MCFixup > llvm::MCEncodedFragment::getFixups () inline
Definition at line 403 of file MCSection.h.
References llvm::MCFragment::getParent(), and llvm::MutableArrayRef().
getFixups() [2/2]
ArrayRef< MCFixup > llvm::MCEncodedFragment::getFixups () const inline
Definition at line 407 of file MCSection.h.
References llvm::ArrayRef(), and llvm::MCFragment::getParent().
getSize()
size_t llvm::MCEncodedFragment::getSize () const inline
Definition at line 412 of file MCSection.h.
getSubtargetInfo()
const MCSubtargetInfo * llvm::MCEncodedFragment::getSubtargetInfo () const inline
Retrieve the MCSubTargetInfo in effect when the instruction was encoded.
Guaranteed to be non-null if hasInstructions() == true
Definition at line 349 of file MCSection.h.
References STI.
Referenced by llvm::MCAssembler::writeFragmentPadding().
setAlignToBundleEnd()
void llvm::MCEncodedFragment::setAlignToBundleEnd (bool V) inline
Definition at line 334 of file MCSection.h.
References llvm::MCFragment::AlignToBundleEnd.
setAllowAutoPadding()
void llvm::MCEncodedFragment::setAllowAutoPadding (bool V) inline
Definition at line 359 of file MCSection.h.
References llvm::MCFragment::AllowAutoPadding.
setBundlePadding()
void llvm::MCEncodedFragment::setBundlePadding (uint8_t N) inline
Set the padding size for this fragment.
By default it's a no-op, and only some fragments have a meaningful implementation.
Definition at line 345 of file MCSection.h.
References N.
Referenced by llvm::MCAssembler::layoutBundle().
setContents()
void MCEncodedFragment::setContents (ArrayRef< char > Contents)
Definition at line 85 of file MCSection.cpp.
References llvm::ArrayRef< T >::begin(), llvm::copy(), llvm::MCFragment::getParent(), and llvm::ArrayRef< T >::size().
Referenced by llvm::CodeViewContext::encodeDefRange(), and llvm::CodeViewContext::encodeInlineLineTable().
setFixups()
void MCEncodedFragment::setFixups (ArrayRef< MCFixup > Fixups)
Definition at line 111 of file MCSection.cpp.
References llvm::copy(), and llvm::MCFragment::getParent().
Referenced by llvm::CodeViewContext::encodeDefRange().
setHasInstructions()
void llvm::MCEncodedFragment::setHasInstructions (const MCSubtargetInfo & STI) inline
Record that the fragment contains instructions with the MCSubtargetInfo in effect when the instruction was encoded.
Definition at line 353 of file MCSection.h.
References llvm::MCFragment::HasInstructions, and STI.
Member Data Documentation
STI
const MCSubtargetInfo* llvm::MCEncodedFragment::STI = nullptr protected
The MCSubtargetInfo in effect when the instruction was encoded.
It must be non-null for instructions.
Definition at line 312 of file MCSection.h.
Referenced by getSubtargetInfo(), llvm::MCRelaxableFragment::MCRelaxableFragment(), and setHasInstructions().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSection.h
lib/MC/MCSection.cpp