LLVM: llvm::orc::SpeculateQuery Class Reference
llvm::orc::SpeculateQuery Class Reference
#include "llvm/ExecutionEngine/Orc/SpeculateAnalyses.h"
Public Types
using ResultTy = std::optional<DenseMap<StringRef, DenseSet<StringRef>>>
Protected Member Functions
void findCalles (const BasicBlock *, DenseSet< StringRef > &)
bool isStraightLine (const Function &F)
Detailed Description
Definition at line 25 of file SpeculateAnalyses.h.
Member Typedef Documentation
ResultTy
using llvm::orc::SpeculateQuery::ResultTy = std::optional<DenseMap<StringRef, DenseSet<StringRef>>>
Definition at line 31 of file SpeculateAnalyses.h.
Member Function Documentation
findCalles()
void llvm::orc::SpeculateQuery::findCalles (const BasicBlock * BB, DenseSet< StringRef > & CallesNames) protected
Definition at line 49 of file SpeculateAnalyses.cpp.
References assert(), Call, llvm::DirectCall, llvm::dyn_cast(), getCalledFunction(), llvm::BasicBlock::getTerminator(), I, II, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and llvm::BasicBlock::instructionsWithoutDebug().
Referenced by llvm::orc::BlockFreqQuery::operator()(), and llvm::orc::SequenceBBQuery::operator()().
isStraightLine()
bool llvm::orc::SpeculateQuery::isStraightLine (const Function & F) protected
Definition at line 66 of file SpeculateAnalyses.cpp.
References llvm::all_of(), F, and llvm::BasicBlock::getSingleSuccessor().
Referenced by llvm::orc::SequenceBBQuery::operator()().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/SpeculateAnalyses.h
lib/ExecutionEngine/Orc/SpeculateAnalyses.cpp