LLVM: llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor Class Reference
llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor Class Reference
#include "llvm/ADT/TrieRawHashMap.h"
Public Member Functions
value_type & operator() (T &&RHS)
value_type & operator() (const T &RHS)
template<class... ArgsT>
value_type & emplace (ArgsT &&...Args)
LazyValueConstructor (LazyValueConstructor &&RHS)
~LazyValueConstructor ()
Friends
class ThreadSafeTrieRawHashMap
Detailed Description
template<class T, size_t NumHashBytes>
class llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor
Definition at line 277 of file TrieRawHashMap.h.
Constructor & Destructor Documentation
LazyValueConstructor()
template<class T, size_t NumHashBytes> llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::LazyValueConstructor (LazyValueConstructor && RHS) inline
Definition at line 294 of file TrieRawHashMap.h.
References LazyValueConstructor(), and RHS.
Referenced by LazyValueConstructor().
~LazyValueConstructor()
template<class T, size_t NumHashBytes> llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::~LazyValueConstructor () inline
Definition at line 298 of file TrieRawHashMap.h.
References assert().
Member Function Documentation
emplace()
template<class T, size_t NumHashBytes> template<class... ArgsT> value_type & llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::emplace (ArgsT &&... Args) inline
Definition at line 287 of file TrieRawHashMap.h.
References assert().
operator()() [1/2]
template<class T, size_t NumHashBytes> value_type & llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::operator() (const T & RHS) inline
Definition at line 283 of file TrieRawHashMap.h.
References assert(), RHS, and T.
operator()() [2/2]
template<class T, size_t NumHashBytes> value_type & llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::operator() (T && RHS) inline
Definition at line 279 of file TrieRawHashMap.h.
References assert(), RHS, and T.
Friends And Related Symbol Documentation
ThreadSafeTrieRawHashMap
template<class T, size_t NumHashBytes> friend class ThreadSafeTrieRawHashMap friend
Definition at line 306 of file TrieRawHashMap.h.
References ThreadSafeTrieRawHashMap.
Referenced by ThreadSafeTrieRawHashMap.
The documentation for this class was generated from the following file:
include/llvm/ADT/TrieRawHashMap.h