LLVM: llvm::ShapeT Class Reference
llvm::ShapeT Class Reference
#include "llvm/CodeGen/TileShapeInfo.h"
Public Member Functions
ShapeT (MachineOperand *Row, MachineOperand *Col, const MachineRegisterInfo *MRI=nullptr)
ShapeT (ArrayRef< MachineOperand * > ShapesOperands, const MachineRegisterInfo *MRI=nullptr)
ShapeT ()
bool operator== (const ShapeT &Shape) const
bool operator!= (const ShapeT &Shape) const
MachineOperand * getRow (unsigned I=0) const
MachineOperand * getCol (unsigned I=0) const
int64_t getRowImm (unsigned I=0) const
int64_t getColImm (unsigned I=0) const
unsigned getShapeNum ()
bool isValid ()
void deduceImm (const MachineRegisterInfo *MRI)
Detailed Description
Definition at line 29 of file TileShapeInfo.h.
Constructor & Destructor Documentation
ShapeT() [1/3]
llvm::ShapeT::ShapeT (MachineOperand * Row, MachineOperand * Col, const MachineRegisterInfo * MRI = nullptr) inline
Definition at line 31 of file TileShapeInfo.h.
References deduceImm(), and MRI.
Referenced by operator!=(), and operator==().
ShapeT() [2/3]
llvm::ShapeT::ShapeT (ArrayRef< MachineOperand * > ShapesOperands, const MachineRegisterInfo * MRI = nullptr) inline
Definition at line 45 of file TileShapeInfo.h.
References llvm::append_range(), assert(), deduceImm(), MRI, and llvm::ArrayRef< T >::size().
ShapeT() [3/3]
llvm::ShapeT::ShapeT () inline
Definition at line 56 of file TileShapeInfo.h.
Member Function Documentation
deduceImm()
void llvm::ShapeT::deduceImm (const MachineRegisterInfo * MRI) inline
Definition at line 114 of file TileShapeInfo.h.
References assert(), GetImm(), MI, MRI, and Reg.
Referenced by ShapeT(), and ShapeT().
getCol()
MachineOperand * llvm::ShapeT::getCol (unsigned I = 0) const inline
Definition at line 84 of file TileShapeInfo.h.
References assert(), and I.
Referenced by canHintShape(), and collectVirtRegShapes().
getColImm()
int64_t llvm::ShapeT::getColImm (unsigned I = 0) const inline
Definition at line 98 of file TileShapeInfo.h.
References assert(), and I.
Referenced by operator==().
getRow()
MachineOperand * llvm::ShapeT::getRow (unsigned I = 0) const inline
Definition at line 77 of file TileShapeInfo.h.
References assert(), and I.
Referenced by canHintShape(), and collectVirtRegShapes().
getRowImm()
int64_t llvm::ShapeT::getRowImm (unsigned I = 0) const inline
Definition at line 91 of file TileShapeInfo.h.
References assert(), and I.
Referenced by operator==().
getShapeNum()
unsigned llvm::ShapeT::getShapeNum () inline
Definition at line 105 of file TileShapeInfo.h.
References isValid().
Referenced by canHintShape(), and collectVirtRegShapes().
isValid()
bool llvm::ShapeT::isValid () inline
Definition at line 112 of file TileShapeInfo.h.
Referenced by getShapeNum().
operator!=()
bool llvm::ShapeT::operator!= (const ShapeT & Shape) const inline
Definition at line 75 of file TileShapeInfo.h.
References ShapeT().
operator==()
bool llvm::ShapeT::operator== (const ShapeT & Shape) const inline
Definition at line 61 of file TileShapeInfo.h.
References llvm::CallingConv::C, getColImm(), getRowImm(), and ShapeT().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/TileShapeInfo.h