LLVM: llvm::NoInferenceModelRunner Class Reference
llvm::NoInferenceModelRunner Class Reference
A pseudo model runner.
#include "llvm/Analysis/NoInferenceModelRunner.h"
Public Member Functions
LLVM_ABI NoInferenceModelRunner (LLVMContext &Ctx, const std::vector< TensorSpec > &Inputs)
Public Member Functions inherited from llvm::MLModelRunner
MLModelRunner (const MLModelRunner &)=delete
MLModelRunner & operator= (const MLModelRunner &)=delete
virtual ~MLModelRunner ()=default
template<typename T>
T evaluate ()
template<typename T, typename I>
T * getTensor (I FeatureID)
template<typename T, typename I>
const T * getTensor (I FeatureID) const
void * getTensorUntyped (size_t Index)
const void * getTensorUntyped (size_t Index) const
Kind getKind () const
virtual void switchContext (StringRef Name)
Static Public Member Functions
static bool classof (const MLModelRunner *R)
Additional Inherited Members
Public Types inherited from llvm::MLModelRunner
enum class Kind : int {
Unknown , Release , Development , NoOp ,
Interactive
}
Protected Member Functions inherited from llvm::MLModelRunner
MLModelRunner (LLVMContext &Ctx, Kind Type, size_t NumInputs)
void setUpBufferForTensor (size_t Index, const TensorSpec &Spec, void *Buffer)
Protected Attributes inherited from llvm::MLModelRunner
LLVMContext & Ctx
const Kind Type
Detailed Description
A pseudo model runner.
We use it to store feature values when collecting logs for the default policy, in 'development' mode, but never ask it to 'run'.
Definition at line 21 of file NoInferenceModelRunner.h.
Constructor & Destructor Documentation
NoInferenceModelRunner()
NoInferenceModelRunner::NoInferenceModelRunner (LLVMContext & Ctx, const std::vector< TensorSpec > & Inputs)
Definition at line 17 of file NoInferenceModelRunner.cpp.
References llvm::MLModelRunner::Ctx, llvm::MLModelRunner::MLModelRunner(), llvm::MLModelRunner::NoOp, llvm::MLModelRunner::setUpBufferForTensor(), and llvm::size().
Member Function Documentation
classof()
bool llvm::NoInferenceModelRunner::classof (const MLModelRunner * R) inline static
Definition at line 26 of file NoInferenceModelRunner.h.
References llvm::MLModelRunner::MLModelRunner(), and llvm::MLModelRunner::NoOp.
The documentation for this class was generated from the following files:
include/llvm/Analysis/NoInferenceModelRunner.h
lib/Analysis/NoInferenceModelRunner.cpp