LLVM: llvm::VPVectorEndPointerRecipe Class Reference
llvm::VPVectorEndPointerRecipe Class Reference
A recipe to compute a pointer to the last element of each part of a widened memory access for widened memory accesses of IndexedTy.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPVectorEndPointerRecipe (VPValue *Ptr, VPValue *VF, Type *IndexedTy, int64_t Stride, GEPNoWrapFlags GEPFlags, DebugLoc DL)
VPValue * getVFValue ()
const VPValue * getVFValue () const
void execute (VPTransformState &State) override
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the VPUser only uses the first lane of operand Op.
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Return the cost of this VPVectorPointerRecipe.
bool onlyFirstPartUsed (const VPValue *Op) const override
Returns true if the recipe only uses the first part of operand Op.
VPVectorEndPointerRecipe * clone () override
Clone the current recipe.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
Public Member Functions inherited from llvm::VPRecipeWithIRFlags
VPRecipeWithIRFlags (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
VPRecipeWithIRFlags (const unsigned char SC, ArrayRef< VPValue * > Operands, Instruction &I)
VPRecipeWithIRFlags (const unsigned char SC, ArrayRef< VPValue * > Operands, const VPIRFlags &Flags, DebugLoc DL={})
Public Member Functions inherited from llvm::VPSingleDefRecipe
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, Value *UV, DebugLoc DL={})
Instruction * getUnderlyingInstr ()
Returns the underlying instruction.
const Instruction * getUnderlyingInstr () const
LLVM_DUMP_METHOD void dump () const
Print this VPSingleDefRecipe to dbgs() (for debugging).
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
bool isScalarCast () const
Return true if the recipe is a scalar cast.
void setDebugLoc (DebugLoc NewDL)
Set the recipe's debug location to NewDL.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser () const
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isLiveIn () const
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Value * getLiveInIRValue () const
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
bool isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop.
void setUnderlyingValue (Value *Val)
Public Member Functions inherited from llvm::VPIRFlags
VPIRFlags ()
VPIRFlags (Instruction &I)
VPIRFlags (CmpInst::Predicate Pred)
VPIRFlags (WrapFlagsTy WrapFlags)
VPIRFlags (FastMathFlags FMFs)
VPIRFlags (DisjointFlagsTy DisjointFlags)
VPIRFlags (NonNegFlagsTy NonNegFlags)
VPIRFlags (GEPNoWrapFlags GEPFlags)
void transferFlags (VPIRFlags &Other)
void dropPoisonGeneratingFlags ()
Drop all poison-generating flags.
void applyFlags (Instruction &I) const
Apply the IR flags to I.
CmpInst::Predicate getPredicate () const
void setPredicate (CmpInst::Predicate Pred)
GEPNoWrapFlags getGEPNoWrapFlags () const
bool hasFastMathFlags () const
Returns true if the recipe has fast-math flags.
LLVM_ABI_FOR_TEST FastMathFlags getFastMathFlags () const
bool hasNonNegFlag () const
Returns true if the recipe has non-negative flag.
bool isNonNeg () const
bool hasNoUnsignedWrap () const
bool hasNoSignedWrap () const
bool isDisjoint () const
bool flagsValidForOpcode (unsigned Opcode) const
Returns true if the set flags are valid for Opcode.
void printFlags (raw_ostream &O) const
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC , VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Static Public Member Functions inherited from llvm::VPRecipeWithIRFlags
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
static bool classof (const VPValue *V)
Static Public Member Functions inherited from llvm::VPSingleDefRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
Protected Member Functions inherited from llvm::VPUnrollPartAccessor< 2 >
VPValue * getUnrollPartOperand (VPUser &U) const
Return the VPValue operand containing the unroll part or null if there is no such operand.
unsigned getUnrollPart (VPUser &U) const
Return the unroll part.
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
A recipe to compute a pointer to the last element of each part of a widened memory access for widened memory accesses of IndexedTy.
Used for VPWidenMemoryRecipes or VPInterleaveRecipes that are reversed.
Definition at line 1743 of file VPlan.h.
Constructor & Destructor Documentation
VPVectorEndPointerRecipe()
llvm::VPVectorEndPointerRecipe::VPVectorEndPointerRecipe (VPValue * Ptr, VPValue * VF, Type * IndexedTy, int64_t Stride, GEPNoWrapFlags GEPFlags, DebugLoc DL) inline
Definition at line 1752 of file VPlan.h.
References llvm::VPIRFlags::GEPFlags, Ptr, and llvm::VPRecipeWithIRFlags::VPRecipeWithIRFlags().
Referenced by clone().
Member Function Documentation
clone()
VPVectorEndPointerRecipe * llvm::VPVectorEndPointerRecipe::clone () inline override virtual
Clone the current recipe.
Implements llvm::VPSingleDefRecipe.
Definition at line 1788 of file VPlan.h.
References llvm::VPRecipeBase::getDebugLoc(), llvm::VPIRFlags::getGEPNoWrapFlags(), llvm::VPUser::getOperand(), getVFValue(), and VPVectorEndPointerRecipe().
computeCost()
InstructionCost llvm::VPVectorEndPointerRecipe::computeCost (ElementCount VF, VPCostContext & Ctx) const inline override virtual
Return the cost of this VPVectorPointerRecipe.
Reimplemented from llvm::VPRecipeBase.
Definition at line 1774 of file VPlan.h.
execute()
void VPVectorEndPointerRecipe::execute (VPTransformState & State) override virtual
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
Implements llvm::VPRecipeWithIRFlags.
Definition at line 2351 of file VPlanRecipes.cpp.
References getGEPIndexTy(), llvm::VPIRFlags::getGEPNoWrapFlags(), llvm::VPUser::getOperand(), llvm::Value::getType(), llvm::VPUnrollPartAccessor< 2 >::getUnrollPart(), getVFValue(), and Ptr.
getVFValue() [1/2]
VPValue * llvm::VPVectorEndPointerRecipe::getVFValue () inline
Definition at line 1762 of file VPlan.h.
References llvm::VPUser::getOperand(), and getVFValue().
Referenced by clone(), execute(), and getVFValue().
getVFValue() [2/2]
const VPValue * llvm::VPVectorEndPointerRecipe::getVFValue () const inline
Definition at line 1763 of file VPlan.h.
References llvm::VPUser::getOperand().
onlyFirstLaneUsed()
bool llvm::VPVectorEndPointerRecipe::onlyFirstLaneUsed (const VPValue * Op) const inline override virtual
Returns true if the VPUser only uses the first lane of operand Op.
Conservatively returns false.
Reimplemented from llvm::VPUser.
Definition at line 1767 of file VPlan.h.
References assert(), llvm::is_contained(), and llvm::VPUser::operands().
onlyFirstPartUsed()
bool llvm::VPVectorEndPointerRecipe::onlyFirstPartUsed (const VPValue * Op) const inline override virtual
Returns true if the recipe only uses the first part of operand Op.
Reimplemented from llvm::VPUser.
Definition at line 1781 of file VPlan.h.
References assert(), llvm::VPUser::getNumOperands(), llvm::is_contained(), and llvm::VPUser::operands().
print()
void VPVectorEndPointerRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 2379 of file VPlanRecipes.cpp.
References llvm::VPValue::printAsOperand(), llvm::VPIRFlags::printFlags(), and llvm::VPUser::printOperands().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp