LLVM: ModuleImportsManager Class Reference
ModuleImportsManager Class Reference
Determine the list of imports and exports for each module.
Public Member Functions
virtual ~ModuleImportsManager ()=default
virtual void computeImportForModule (const GVSummaryMapTy &DefinedGVSummaries, StringRef ModName, FunctionImporter::ImportMapTy &ImportList)
Given the list of globals defined in a module, compute the list of imports as well as the list of "exports", i.e.
Static Public Member Functions
static std::unique_ptr< ModuleImportsManager > create (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex &Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists=nullptr)
Protected Member Functions
ModuleImportsManager (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex &Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists=nullptr)
virtual bool canImport (ValueInfo VI)
Protected Attributes
function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing
const ModuleSummaryIndex & Index
DenseMap< StringRef, FunctionImporter::ExportSetTy > *const ExportLists
Detailed Description
Determine the list of imports and exports for each module.
Definition at line 501 of file FunctionImport.cpp.
Constructor & Destructor Documentation
ModuleImportsManager()
ModuleImportsManager::ModuleImportsManager (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex & Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > * ExportLists = nullptr) inline protected
Definition at line 515 of file FunctionImport.cpp.
References ExportLists, Index, and IsPrevailing.
Referenced by create(), and WorkloadImportsManager::WorkloadImportsManager().
~ModuleImportsManager()
virtual ModuleImportsManager::~ModuleImportsManager () virtual default
References computeImportForModule(), create(), ExportLists, Index, and IsPrevailing.
Member Function Documentation
canImport()
virtual bool ModuleImportsManager::canImport (ValueInfo VI) inline protected virtual
Definition at line 521 of file FunctionImport.cpp.
computeImportForModule()
void ModuleImportsManager::computeImportForModule (const GVSummaryMapTy & DefinedGVSummaries, StringRef ModName, FunctionImporter::ImportMapTy & ImportList) virtual
Given the list of globals defined in a module, compute the list of imports as well as the list of "exports", i.e.
the list of symbols referenced from another module (that may require promotion).
Definition at line 1061 of file FunctionImport.cpp.
References assert(), llvm::dbgs(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), ExportLists, getFailureName(), llvm::getHotnessName(), I, ImportInstrLimit, Index, IsPrevailing, LLVM_DEBUG, llvm::SmallVectorImpl< T >::pop_back_val(), and PrintImportFailures.
Referenced by ~ModuleImportsManager().
create()
std::unique_ptr< ModuleImportsManager > ModuleImportsManager::create (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex & Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > * ExportLists = nullptr) static
Definition at line 830 of file FunctionImport.cpp.
References llvm::dbgs(), ExportLists, Index, IsPrevailing, LLVM_DEBUG, ModuleImportsManager(), UseCtxProfile, and WorkloadDefinitions.
Referenced by llvm::ComputeCrossModuleImport(), ComputeCrossModuleImportForModuleForTest(), and ~ModuleImportsManager().
Member Data Documentation
ExportLists
DenseMap<StringRef, FunctionImporter::ExportSetTy>* const ModuleImportsManager::ExportLists protected
Definition at line 513 of file FunctionImport.cpp.
Referenced by computeImportForModule(), create(), ModuleImportsManager(), WorkloadImportsManager::WorkloadImportsManager(), and ~ModuleImportsManager().
Index
const ModuleSummaryIndex& ModuleImportsManager::Index protected
Definition at line 512 of file FunctionImport.cpp.
Referenced by computeImportForModule(), create(), ModuleImportsManager(), WorkloadImportsManager::WorkloadImportsManager(), and ~ModuleImportsManager().
IsPrevailing
function_ref<bool(GlobalValue::GUID, const GlobalValueSummary *)> ModuleImportsManager::IsPrevailing protected
Definition at line 511 of file FunctionImport.cpp.
Referenced by computeImportForModule(), create(), ModuleImportsManager(), WorkloadImportsManager::WorkloadImportsManager(), and ~ModuleImportsManager().
The documentation for this class was generated from the following file:
lib/Transforms/IPO/FunctionImport.cpp