LLVM: llvm::PPCTargetMachine Class Reference
llvm::PPCTargetMachine Class Reference final
Common code between 32-bit and 64-bit PowerPC targets.
#include "Target/PowerPC/PPCTargetMachine.h"
Public Types
enum PPCABI { PPC_ABI_UNKNOWN , PPC_ABI_ELFv1 , PPC_ABI_ELFv2 }
enum Endian { NOT_DETECTED , LITTLE , BIG }
Public Member Functions
PPCTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOptLevel OL, bool JIT)
~PPCTargetMachine () override
const PPCSubtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
const PPCSubtarget * getSubtargetImpl () const =delete
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetTransformInfo getTargetTransformInfo (const Function &F) const override
Get a TargetTransformInfo implementation for the target.
TargetLoweringObjectFile * getObjFileLowering () const override
MachineFunctionInfo * createMachineFunctionInfo (BumpPtrAllocator &Allocator, const Function &F, const TargetSubtargetInfo *STI) const override
Create the target's instance of MachineFunctionInfo.
ScheduleDAGInstrs * createMachineScheduler (MachineSchedContext *C) const override
Create an instance of ScheduleDAGInstrs to be run within the standard MachineScheduler pass for this function and target at the current optimization level.
ScheduleDAGInstrs * createPostMachineScheduler (MachineSchedContext *C) const override
Similar to createMachineScheduler but used when postRA machine scheduling is enabled.
bool isELFv2ABI () const
bool hasGlibcHWCAPAccess () const
void setGlibcHWCAPAccess (bool Val=true) const
bool isPPC64 () const
bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast between SrcAS and DestAS is a noop.
bool isLittleEndian () const
int unqualifiedInlineAsmVariant () const override
The default variant to use in unqualified asm instructions.
Public Member Functions inherited from llvm::CodeGenTargetMachineImpl
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context) override
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
Expected< std::unique_ptr< MCStreamer > > createMCStreamer (raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Ctx) override
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
void setTargetFeatureString (StringRef FS)
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC>
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
ExceptionHandling getExceptionModel () const
Return the ExceptionHandling to use, considering TargetOptions and the Triple's default.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
uint64_t getMaxCodeSize () const
Returns the maximum code size possible under the code model.
void setCodeModel (CodeModel::Model CM)
Set the code model.
void setLargeDataThreshold (uint64_t LDT)
bool isLargeGlobalValue (const GlobalValue *GV) const
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
bool useTLSDESC () const
Returns true if this target uses TLS Descriptors.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOptLevel getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOptLevel Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
void setSupportsDebugEntryValues (bool Enable)
void setCFIFixup (bool Enable)
bool getAIXExtendedAltivecABI () const
bool getUniqueSectionNames () const
bool getUniqueBasicBlockSectionNames () const
Return true if unique basic block section names must be generated.
bool getSeparateNamedSections () const
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
bool getEnableStaticDataPartitioning () const
bool getIgnoreXCOFFVisibility () const
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
bool getXCOFFTracebackTable () const
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
llvm::BasicBlockSection getBBSectionsType () const
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
const MemoryBuffer * getBBSectionsFuncListBuf () const
Get the list of functions and basic block ids that need unique sections.
void setPGOOption (std::optional< PGOOptions > PGOOpt)
const std::optional< PGOOptions > & getPGOOption () const
virtual unsigned getAssumedAddrSpace (const Value *V) const
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
virtual std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
TargetIRAnalysis getTargetIRAnalysis () const
Get a TargetIRAnalysis appropriate for the target.
virtual void registerPassBuilderCallbacks (PassBuilder &)
Allow the target to modify the pass pipeline.
virtual void registerEarlyDefaultAliasAnalyses (AAManager &)
Allow the target to register early alias analyses (AA before BasicAA) with the AAManager for use with the new pass manager.
virtual void registerDefaultAliasAnalyses (AAManager &)
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
virtual unsigned getSjLjDataSize () const
virtual unsigned getAddressSpaceForPseudoSourceKind (unsigned Kind) const
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
virtual bool splitModule (Module &M, unsigned NumParts, function_ref< void(std::unique_ptr< Module > MPart)> ModuleCallback)
Entry point for module splitting.
virtual Error buildCodeGenPipeline (ModulePassManager &, raw_pwrite_stream &, raw_pwrite_stream *, CodeGenFileType, const CGPassBuilderOption &, PassInstrumentationCallbacks *)
virtual bool isMachineVerifierClean () const
Returns true if the target is expected to pass all machine verifier checks.
virtual bool usesPhysRegsForValues () const
True if the target uses physical regs (as nearly all targets do).
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
virtual void registerMachineRegisterInfoCallback (MachineFunction &MF) const
virtual size_t clearLinkerOptimizationHints (const SmallPtrSetImpl< MachineInstr * > &MIs) const
Remove all Linker Optimization Hints (LOH) associated with instructions in MIs and.
Additional Inherited Members
Static Public Member Functions inherited from llvm::TargetMachine
static std::pair< int, int > parseBinutilsVersion (StringRef Version)
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Static Public Attributes inherited from llvm::TargetMachine
static constexpr unsigned DefaultSjLjDataSize = 32
The integer bit size to use for SjLj based exception handling.
Protected Member Functions inherited from llvm::CodeGenTargetMachineImpl
CodeGenTargetMachineImpl (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOptLevel OL)
void initAsmInfo ()
virtual void reset ()
Reset internal state.
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
uint64_t LargeDataThreshold = 0
CodeGenOptLevel OptLevel = CodeGenOptLevel::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
std::optional< PGOOptions > PGOOption
Detailed Description
Common code between 32-bit and 64-bit PowerPC targets.
Definition at line 26 of file PPCTargetMachine.h.
Member Enumeration Documentation
Endian
enum llvm::PPCTargetMachine::Endian
Enumerator
NOT_DETECTED
LITTLE
BIG
Definition at line 29 of file PPCTargetMachine.h.
PPCABI
enum llvm::PPCTargetMachine::PPCABI
Enumerator
PPC_ABI_UNKNOWN
PPC_ABI_ELFv1
PPC_ABI_ELFv2
Definition at line 28 of file PPCTargetMachine.h.
Constructor & Destructor Documentation
PPCTargetMachine()
PPCTargetMachine::PPCTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOptLevel OL, bool JIT)
Definition at line 345 of file PPCTargetMachine.cpp.
References BIG, llvm::CodeGenTargetMachineImpl::CodeGenTargetMachineImpl(), computeFSAdditions(), computeTargetABI(), createTLOF(), getDataLayoutString(), getEffectivePPCCodeModel(), llvm::getEffectiveRelocModel(), llvm::TargetMachine::getTargetTriple(), llvm::CodeGenTargetMachineImpl::initAsmInfo(), isLittleEndianTriple(), LITTLE, llvm::TargetMachine::Options, llvm::TargetMachine::RM, and T.
~PPCTargetMachine()
PPCTargetMachine::~PPCTargetMachine () override default
References F.
Member Function Documentation
createMachineFunctionInfo()
MachineFunctionInfo * PPCTargetMachine::createMachineFunctionInfo (BumpPtrAllocator & Allocator, const Function & F, const TargetSubtargetInfo * STI) const override virtual
Create the target's instance of MachineFunctionInfo.
Reimplemented from llvm::TargetMachine.
Definition at line 617 of file PPCTargetMachine.cpp.
References llvm::MachineFunctionInfo::create(), F, and llvm::TargetMachine::STI.
createMachineScheduler()
ScheduleDAGInstrs * PPCTargetMachine::createMachineScheduler (MachineSchedContext * C) const override virtual
Create an instance of ScheduleDAGInstrs to be run within the standard MachineScheduler pass for this function and target at the current optimization level.
This can also be used to plug a new MachineSchedStrategy into an instance of the standard ScheduleDAGMI: return new ScheduleDAGMI(C, std::make_unique<MyStrategy>(C), /*RemoveKillFlags=*‍/false)
Return NULL to select the default (generic) machine scheduler.
Reimplemented from llvm::TargetMachine.
Definition at line 407 of file PPCTargetMachine.cpp.
References llvm::CallingConv::C, and createPPCMachineScheduler().
createPassConfig()
TargetPassConfig * PPCTargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::CodeGenTargetMachineImpl.
Definition at line 455 of file PPCTargetMachine.cpp.
createPostMachineScheduler()
ScheduleDAGInstrs * PPCTargetMachine::createPostMachineScheduler (MachineSchedContext * C) const override virtual
Similar to createMachineScheduler but used when postRA machine scheduling is enabled.
Reimplemented from llvm::TargetMachine.
Definition at line 412 of file PPCTargetMachine.cpp.
References llvm::CallingConv::C, and createPPCPostMachineScheduler().
getObjFileLowering()
TargetLoweringObjectFile * llvm::PPCTargetMachine::getObjFileLowering () const inline override virtual
Reimplemented from llvm::TargetMachine.
Definition at line 59 of file PPCTargetMachine.h.
getSubtargetImpl() [1/2]
const PPCSubtarget * llvm::PPCTargetMachine::getSubtargetImpl () const delete
References F.
getSubtargetImpl() [2/2]
const PPCSubtarget * PPCTargetMachine::getSubtargetImpl (const Function &) const override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 364 of file PPCTargetMachine.cpp.
References computeFSAdditions(), F, llvm::TargetMachine::getOptLevel(), llvm::TargetMachine::getTargetTriple(), llvm::Attribute::getValueAsString(), I, llvm::Attribute::isValid(), llvm::TargetMachine::resetTargetOptions(), llvm::StringRef::str(), llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, and llvm::TargetMachine::TargetTriple.
getTargetTransformInfo()
TargetTransformInfo PPCTargetMachine::getTargetTransformInfo (const Function & F) const override virtual
Get a TargetTransformInfo implementation for the target.
The TTI returned uses the common code generator to answer queries about the IR.
Reimplemented from llvm::CodeGenTargetMachineImpl.
Definition at line 607 of file PPCTargetMachine.cpp.
References F.
hasGlibcHWCAPAccess()
bool llvm::PPCTargetMachine::hasGlibcHWCAPAccess () const inline
Definition at line 72 of file PPCTargetMachine.h.
isELFv2ABI()
bool llvm::PPCTargetMachine::isELFv2ABI () const inline
Definition at line 71 of file PPCTargetMachine.h.
References PPC_ABI_ELFv2.
isLittleEndian()
bool PPCTargetMachine::isLittleEndian () const
Definition at line 611 of file PPCTargetMachine.cpp.
References assert(), LITTLE, and NOT_DETECTED.
isNoopAddrSpaceCast()
bool llvm::PPCTargetMachine::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const inline override virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented from llvm::TargetMachine.
Definition at line 79 of file PPCTargetMachine.h.
isPPC64()
bool llvm::PPCTargetMachine::isPPC64 () const inline
Definition at line 74 of file PPCTargetMachine.h.
References llvm::TargetMachine::getTargetTriple(), llvm::Triple::ppc64, and llvm::Triple::ppc64le.
setGlibcHWCAPAccess()
void llvm::PPCTargetMachine::setGlibcHWCAPAccess (bool Val = true) const inline
Definition at line 73 of file PPCTargetMachine.h.
unqualifiedInlineAsmVariant()
int llvm::PPCTargetMachine::unqualifiedInlineAsmVariant () const inline override virtual
The default variant to use in unqualified asm instructions.
If this returns 0, asm "$(foo$|bar$)" will evaluate to asm "foo".
Reimplemented from llvm::TargetMachine.
Definition at line 86 of file PPCTargetMachine.h.
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCTargetMachine.h
lib/Target/PowerPC/PPCTargetMachine.cpp