LLVM: llvm::SCEV Class Reference
llvm::SCEV Class Reference
This class represents an analyzed expression in the program.
#include "llvm/Analysis/ScalarEvolution.h"
Public Types
enum NoWrapFlags {
FlagAnyWrap = 0 , FlagNW = (1 << 0) , FlagNUW = (1 << 1) , FlagNSW = (1 << 2) ,
NoWrapMask = (1 << 3) - 1
}
NoWrapFlags are bitfield indices into SubclassData.
Public Member Functions
SCEV (const FoldingSetNodeIDRef ID, SCEVTypes SCEVTy, unsigned short ExpressionSize)
SCEV (const SCEV &)=delete
SCEV & operator= (const SCEV &)=delete
SCEVTypes getSCEVType () const
LLVM_ABI Type * getType () const
Return the LLVM type of this SCEV expression.
LLVM_ABI ArrayRef< const SCEV * > operands () const
Return operands of this SCEV expression.
LLVM_ABI bool isZero () const
Return true if the expression is a constant zero.
LLVM_ABI bool isOne () const
Return true if the expression is a constant one.
LLVM_ABI bool isAllOnesValue () const
Return true if the expression is a constant all-ones value.
LLVM_ABI bool isNonConstantNegative () const
Return true if the specified scev is negated, but not a constant.
unsigned short getExpressionSize () const
LLVM_ABI void print (raw_ostream &OS) const
Print out the internal representation of this scalar to the specified stream.
LLVM_ABI void dump () const
This method is used for debugging.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Protected Attributes
const unsigned short ExpressionSize
unsigned short SubclassData = 0
This field is initialized to zero and may be used in subclasses to store miscellaneous information.
Friends
struct FoldingSetTrait< SCEV >
Detailed Description
This class represents an analyzed expression in the program.
These are opaque objects that the client is not allowed to do much with directly.
Definition at line 72 of file ScalarEvolution.h.
Member Enumeration Documentation
NoWrapFlags
enum llvm::SCEV::NoWrapFlags
NoWrapFlags are bitfield indices into SubclassData.
Add and Mul expressions may have no-unsigned-wrap <NUW> or no-signed-wrap <NSW> properties, which are derived from the IR operator. NSW is a misnomer that we use to mean no signed overflow or underflow.
AddRec expressions may have a no-self-wraparound <NW> property if, in the integer domain, abs(step) * max-iteration(loop) <= unsigned-max(bitwidth). This means that the recurrence will never reach its start value if the step is non-zero. Computing the same value on each iteration is not considered wrapping, and recurrences with step = 0 are trivially <NW>. <NW> is independent of the sign of step and the value the add recurrence starts with.
Note that NUW and NSW are also valid properties of a recurrence, and either implies NW. For convenience, NW will be set for a recurrence whenever either NUW or NSW are set.
We require that the flag on a SCEV apply to the entire scope in which that SCEV is defined. A SCEV's scope is set of locations dominated by a defining location, which is in turn described by the following rules:
A SCEVUnknown is at the point of definition of the Value.
A SCEVConstant is defined at all points.
A SCEVAddRec is defined starting with the header of the associated loop.
All other SCEVs are defined at the earlest point all operands are defined.
The above rules describe a maximally hoisted form (without regards to potential control dependence). A SCEV is defined anywhere a corresponding instruction could be defined in said maximally hoisted form. Note that SCEVUDivExpr (currently the only expression type which can trap) can be defined per these rules in regions where it would trap at runtime. A SCEV being defined does not require the existence of any instruction within the defined scope.
Enumerator
FlagAnyWrap
FlagNW
FlagNUW
FlagNSW
NoWrapMask
Definition at line 127 of file ScalarEvolution.h.
Constructor & Destructor Documentation
SCEV() [1/2]
llvm::SCEV::SCEV (const FoldingSetNodeIDRef ID, SCEVTypes SCEVTy, unsigned short ExpressionSize) inline explicit
Definition at line 135 of file ScalarEvolution.h.
References ExpressionSize.
Referenced by llvm::SCEVCastExpr::classof(), llvm::SCEVConstant::classof(), llvm::SCEVCouldNotCompute::classof(), llvm::SCEVNAryExpr::classof(), llvm::SCEVUDivExpr::classof(), llvm::SCEVUnknown::classof(), llvm::SCEVVScale::classof(), llvm::SCEVUDivExpr::getLHS(), llvm::SCEVCastExpr::getOperand(), llvm::SCEVCastExpr::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVUDivExpr::getOperand(), llvm::SCEVUDivExpr::getRHS(), operator=(), print(), llvm::SCEVConstant::ScalarEvolution, llvm::SCEVUDivExpr::ScalarEvolution, llvm::SCEVUnknown::ScalarEvolution, llvm::SCEVVScale::ScalarEvolution, SCEV(), llvm::SCEVCastExpr::SCEVCastExpr(), llvm::SCEVCouldNotCompute::SCEVCouldNotCompute(), and llvm::SCEVNAryExpr::SCEVNAryExpr().
SCEV() [2/2]
llvm::SCEV::SCEV (const SCEV &) delete
References SCEV().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void SCEV::dump () const
This method is used for debugging.
Definition at line 267 of file ScalarEvolution.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
getExpressionSize()
unsigned short llvm::SCEV::getExpressionSize () const inline
Definition at line 170 of file ScalarEvolution.h.
References ExpressionSize.
Referenced by hasHugeExpression().
getSCEVType()
SCEVTypes llvm::SCEV::getSCEVType () const inline
Definition at line 141 of file ScalarEvolution.h.
Referenced by llvm::SCEVAddExpr::classof(), llvm::SCEVAddRecExpr::classof(), llvm::SCEVCastExpr::classof(), llvm::SCEVCommutativeExpr::classof(), llvm::SCEVConstant::classof(), llvm::SCEVCouldNotCompute::classof(), llvm::SCEVIntegralCastExpr::classof(), llvm::SCEVMinMaxExpr::classof(), llvm::SCEVMulExpr::classof(), llvm::SCEVNAryExpr::classof(), llvm::SCEVPtrToIntExpr::classof(), llvm::SCEVSequentialMinMaxExpr::classof(), llvm::SCEVSequentialUMinExpr::classof(), llvm::SCEVSignExtendExpr::classof(), llvm::SCEVSMaxExpr::classof(), llvm::SCEVSMinExpr::classof(), llvm::SCEVTruncateExpr::classof(), llvm::SCEVUDivExpr::classof(), llvm::SCEVUMaxExpr::classof(), llvm::SCEVUMinExpr::classof(), llvm::SCEVUnknown::classof(), llvm::SCEVVScale::classof(), llvm::SCEVZeroExtendExpr::classof(), llvm::SCEVSequentialMinMaxExpr::getEquivalentNonSequentialSCEVType(), getExprBase(), getType(), GroupByComplexity(), isHighCostExpansion(), operands(), print(), SCEVMinMaxExprContains(), llvm::SCEVVisitor< SCEVSequentialMinMaxDeduplicatingVisitor, RetVal >::visit(), and llvm::SCEVTraversal< SV >::visitAll().
getType()
Type * SCEV::getType () const
Return the LLVM type of this SCEV expression.
Definition at line 384 of file ScalarEvolution.cpp.
References llvm::cast(), getSCEVType(), llvm_unreachable, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scPtrToInt, llvm::scSequentialUMinExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, llvm::scVScale, and llvm::scZeroExtend.
Referenced by llvm::SCEVAAResult::alias(), BinomialCoefficient(), calculateRtStride(), llvm::cannotBeMaxInLoop(), llvm::cannotBeMinInLoop(), CollectSubexprs(), llvm::ScalarEvolution::computeConstantDifference(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::IndexedReference::computeRefCost(), computeTripCount(), countToEliminateCompares(), createNodeForSelectViaUMinSeq(), createReplacement(), llvm::DependenceInfo::depends(), DoInitialMatch(), evaluatePtrAddRecAtMaxBTCWillNotWrap(), expandBounds(), llvm::SCEVExpander::expandCodeFor(), ExtractImmediate(), FindLoopCounter(), llvm::SCEVExpander::generateOverflowCheck(), genLoopLimit(), llvm::ScalarEvolution::getAnyExtendExpr(), llvm::ScalarEvolution::getGEPExpr(), llvm::ScalarEvolution::getLoopInvariantExitCondDuringFirstIterationsImpl(), llvm::ScalarEvolution::getLosslessPtrToIntExpr(), llvm::ScalarEvolution::getMinTrailingZeros(), getNewAlignment(), getSignedOverflowLimitForStep(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::getStartAndEndForAccess(), llvm::ScalarEvolution::getTripCountFromExitCount(), llvm::ScalarEvolution::getTripCountFromExitCount(), llvm::SCEVAddRecExpr::getType(), llvm::SCEVMinMaxExpr::getType(), llvm::SCEVMulExpr::getType(), llvm::SCEVSequentialMinMaxExpr::getType(), llvm::SCEVUDivExpr::getType(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), getUnsignedOverflowLimitForStep(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::hasIterationCountInvariantInParent(), llvm::SCEVWrapPredicate::implies(), isConditionTrueViaVFAndUF(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::ScalarEvolution::isKnownMultipleOf(), llvm::isKnownNegativeInLoop(), llvm::isKnownNonNegativeInLoop(), llvm::isKnownNonPositiveInLoop(), llvm::isKnownPositiveInLoop(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isSafeDecreasingBound(), isSafeDependenceDistance(), isSafeIncreasingBound(), IsSimplerBaseSCEVForTarget(), llvm::SCEVPatternMatch::bind_cst_ty::match(), llvm::SCEVPatternMatch::cst_pred_ty< Predicate >::match(), mayUsePostIncMode(), optimizeLoopExitWithUnknownExitCount(), llvm::LoopStructure::parseLoopStructure(), llvm::peelLoop(), llvm::VPlanTransforms::prepareForVectorization(), PrintSCEVWithTypeHint(), llvm::replaceSymbolicStrideSCEV(), shouldPeelLastIteration(), simplifyBranchConditionForVFAndUF(), llvm::splitLoopBound(), llvm::UnrollRuntimeLoopRemainder(), verifyTripCount(), llvm::SCEVDivision::visitAddExpr(), llvm::SCEVDivision::visitAddRecExpr(), and llvm::SCEVDivision::visitMulExpr().
isAllOnesValue()
bool SCEV::isAllOnesValue () const
Return true if the expression is a constant all-ones value.
Definition at line 450 of file ScalarEvolution.cpp.
References llvm::SCEVPatternMatch::m_scev_AllOnes(), and llvm::PatternMatch::match().
Referenced by MatchNotExpr().
isNonConstantNegative()
bool SCEV::isNonConstantNegative () const
Return true if the specified scev is negated, but not a constant.
Definition at line 452 of file ScalarEvolution.cpp.
References llvm::dyn_cast(), and llvm::Mul.
Referenced by calculateRtStride().
isOne()
bool SCEV::isOne () const
Return true if the expression is a constant one.
Definition at line 448 of file ScalarEvolution.cpp.
References llvm::SCEVPatternMatch::m_scev_One(), and llvm::PatternMatch::match().
Referenced by llvm::SCEVExpander::generateOverflowCheck(), genLoopLimit(), getStartForNegStride(), and normalizePredicate().
isZero()
bool SCEV::isZero () const
Return true if the expression is a constant zero.
Definition at line 446 of file ScalarEvolution.cpp.
References llvm::SCEVPatternMatch::m_scev_Zero(), and llvm::PatternMatch::match().
Referenced by breakBackedgeIfNotTaken(), calculateRtStride(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::DependenceInfo::depends(), llvm::SCEVDivision::divide(), dumpExampleDependence(), llvm::findArrayDimensions(), FindLoopCounter(), isAlwaysFoldable(), simplifyBranchConditionForVFAndUF(), SolveQuadraticAddRecRange(), and llvm::ScalarEvolution::verify().
operands()
ArrayRef< const SCEV * > SCEV::operands () const
Return operands of this SCEV expression.
Definition at line 418 of file ScalarEvolution.cpp.
References llvm::cast(), getSCEVType(), llvm_unreachable, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scPtrToInt, llvm::scSequentialUMinExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, llvm::scVScale, and llvm::scZeroExtend.
Referenced by llvm::ScalarEvolution::computeConstantDifference(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getNotSCEV(), getSetupCost(), llvm::ScalarEvolution::verify(), and llvm::SCEVTraversal< SV >::visitAll().
operator=()
SCEV & llvm::SCEV::operator= (const SCEV &) delete
References SCEV().
print()
void SCEV::print (raw_ostream & OS) const
Print out the internal representation of this scalar to the specified stream.
This should really only be used for debugging purposes.
Definition at line 273 of file ScalarEvolution.cpp.
References llvm::cast(), FlagNSW, FlagNUW, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::SCEVUDivExpr::getLHS(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVCastExpr::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVUDivExpr::getRHS(), getSCEVType(), llvm::SCEVCastExpr::getType(), llvm::SCEVNAryExpr::hasNoSelfWrap(), llvm::SCEVNAryExpr::hasNoSignedWrap(), llvm::SCEVNAryExpr::hasNoUnsignedWrap(), llvm::interleaved(), llvm_unreachable, llvm::make_pointee_range(), llvm::SCEVNAryExpr::operands(), llvm::Value::printAsOperand(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, SCEV(), llvm::scMulExpr, llvm::scPtrToInt, llvm::scSequentialUMinExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, llvm::scVScale, and llvm::scZeroExtend.
Referenced by dump(), llvm::operator<<(), and llvm::ScalarEvolution::print().
Friends And Related Symbol Documentation
FoldingSetTrait< SCEV >
friend struct FoldingSetTrait< SCEV > friend
Definition at line 2390 of file ScalarEvolution.h.
References llvm::FunctionPass::FunctionPass(), LLVM_ABI, and llvm::ScalarEvolutionWrapperPass::ScalarEvolutionWrapperPass().
Member Data Documentation
ExpressionSize
const unsigned short llvm::SCEV::ExpressionSize protected
Definition at line 84 of file ScalarEvolution.h.
Referenced by getExpressionSize(), and SCEV().
SubclassData
unsigned short llvm::SCEV::SubclassData = 0 protected
This field is initialized to zero and may be used in subclasses to store miscellaneous information.
Definition at line 88 of file ScalarEvolution.h.
Referenced by llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVAddRecExpr::setNoWrapFlags(), and llvm::SCEVCommutativeExpr::setNoWrapFlags().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ScalarEvolution.h
lib/Analysis/ScalarEvolution.cpp