LLVM: llvm::sandboxir::OperandUseIterator Class Reference
llvm::sandboxir::OperandUseIterator Class Reference
Iterator for the Use edges of a User's operands.
#include "llvm/SandboxIR/User.h"
Public Types
using difference_type = std::ptrdiff_t
using value_type = sandboxir::Use
using pointer = value_type *
using reference = value_type &
using iterator_category = std::input_iterator_tag
Public Member Functions
OperandUseIterator ()=default
LLVM_ABI value_type operator* () const
LLVM_ABI OperandUseIterator & operator++ ()
OperandUseIterator operator++ (int)
bool operator== (const OperandUseIterator &Other) const
bool operator!= (const OperandUseIterator &Other) const
LLVM_ABI OperandUseIterator operator+ (unsigned Num) const
LLVM_ABI OperandUseIterator operator- (unsigned Num) const
LLVM_ABI int operator- (const OperandUseIterator &Other) const
Friends
class User
Detailed Description
Iterator for the Use edges of a User's operands.
\Returns the operand Use when dereferenced.
Definition at line 24 of file User.h.
Member Typedef Documentation
difference_type
using llvm::sandboxir::OperandUseIterator::difference_type = std::ptrdiff_t
Definition at line 33 of file User.h.
iterator_category
using llvm::sandboxir::OperandUseIterator::iterator_category = std::input_iterator_tag
Definition at line 37 of file User.h.
pointer
using llvm::sandboxir::OperandUseIterator::pointer = value_type *
Definition at line 35 of file User.h.
reference
using llvm::sandboxir::OperandUseIterator::reference = value_type &
Definition at line 36 of file User.h.
value_type
using llvm::sandboxir::OperandUseIterator::value_type = sandboxir::Use
Definition at line 34 of file User.h.
Constructor & Destructor Documentation
OperandUseIterator()
llvm::sandboxir::OperandUseIterator::OperandUseIterator () default
References LLVM_ABI.
Referenced by operator+(), and operator-().
Member Function Documentation
operator!=()
bool llvm::sandboxir::OperandUseIterator::operator!= (const OperandUseIterator & Other) const inline
Definition at line 50 of file User.h.
References llvm::Other.
operator*()
Use llvm::sandboxir::OperandUseIterator::operator* () const
Definition at line 14 of file User.cpp.
operator+()
OperandUseIterator llvm::sandboxir::OperandUseIterator::operator+ (unsigned Num) const
Definition at line 39 of file User.cpp.
References llvm::sandboxir::User::getOperandUseInternal(), llvm::sandboxir::Use::getUser(), and OperandUseIterator().
operator++() [1/2]
OperandUseIterator & llvm::sandboxir::OperandUseIterator::operator++ ()
Definition at line 16 of file User.cpp.
References assert(), and User.
Referenced by operator++().
operator++() [2/2]
OperandUseIterator llvm::sandboxir::OperandUseIterator::operator++ (int) inline
Definition at line 42 of file User.h.
References operator++().
operator-() [1/2]
int llvm::sandboxir::OperandUseIterator::operator- (const OperandUseIterator & Other) const
Definition at line 52 of file User.cpp.
References llvm::Other.
operator-() [2/2]
OperandUseIterator llvm::sandboxir::OperandUseIterator::operator- (unsigned Num) const
Definition at line 45 of file User.cpp.
References assert(), llvm::sandboxir::User::getOperandUseInternal(), llvm::sandboxir::Use::getUser(), and OperandUseIterator().
operator==()
bool llvm::sandboxir::OperandUseIterator::operator== (const OperandUseIterator & Other) const inline
Definition at line 47 of file User.h.
References llvm::Other.
Friends And Related Symbol Documentation
User
friend class User friend
Definition at line 28 of file User.h.
References User.
Referenced by operator++(), and User.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/User.h
lib/SandboxIR/User.cpp