LLVM: llvm::MachineSchedRegistry Class Reference
llvm::MachineSchedRegistry Class Reference
MachineSchedRegistry provides a selection of available machine instruction schedulers.
#include "llvm/CodeGen/MachineScheduler.h"
Public Types
using ScheduleDAGCtor = ScheduleDAGInstrs *(*)(MachineSchedContext *)
using FunctionPassCtor = ScheduleDAGCtor
Public Member Functions
MachineSchedRegistry (const char *N, const char *D, ScheduleDAGCtor C)
~MachineSchedRegistry ()
MachineSchedRegistry * getNext () const
Public Member Functions inherited from llvm::MachinePassRegistryNode< ScheduleDAGInstrs *(*)(MachineSchedContext *)>
MachinePassRegistryNode (const char *N, const char *D, ScheduleDAGInstrs *C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
StringRef getName () const
StringRef getDescription () const
ScheduleDAGInstrs * getCtor () const
void setNext (MachinePassRegistryNode *N)
Static Public Member Functions
static MachineSchedRegistry * getList ()
static void setListener (MachinePassRegistryListener< FunctionPassCtor > *L)
Static Public Attributes
static LLVM_ABI MachinePassRegistry< ScheduleDAGCtor > Registry
Detailed Description
MachineSchedRegistry provides a selection of available machine instruction schedulers.
Definition at line 161 of file MachineScheduler.h.
Member Typedef Documentation
FunctionPassCtor
using llvm::MachineSchedRegistry::FunctionPassCtor = ScheduleDAGCtor
Definition at line 168 of file MachineScheduler.h.
ScheduleDAGCtor
using llvm::MachineSchedRegistry::ScheduleDAGCtor = ScheduleDAGInstrs *(*)(MachineSchedContext *)
Definition at line 165 of file MachineScheduler.h.
Constructor & Destructor Documentation
MachineSchedRegistry()
llvm::MachineSchedRegistry::MachineSchedRegistry (const char * N, const char * D, ScheduleDAGCtor C) inline
Definition at line 172 of file MachineScheduler.h.
References llvm::CallingConv::C, D(), llvm::MachinePassRegistryNode< ScheduleDAGInstrs *(*)(MachineSchedContext *)>::MachinePassRegistryNode(), N, and Registry.
Referenced by getList(), and getNext().
~MachineSchedRegistry()
llvm::MachineSchedRegistry::~MachineSchedRegistry () inline
Definition at line 177 of file MachineScheduler.h.
References Registry.
Member Function Documentation
getList()
MachineSchedRegistry * llvm::MachineSchedRegistry::getList () inline static
Definition at line 185 of file MachineScheduler.h.
References MachineSchedRegistry(), and Registry.
getNext()
MachineSchedRegistry * llvm::MachineSchedRegistry::getNext () const inline
Definition at line 181 of file MachineScheduler.h.
References llvm::MachinePassRegistryNode< PassCtorTy >::getNext(), and MachineSchedRegistry().
setListener()
void llvm::MachineSchedRegistry::setListener (MachinePassRegistryListener< FunctionPassCtor > * L) inline static
Definition at line 189 of file MachineScheduler.h.
References Registry.
Member Data Documentation
Registry
MachinePassRegistry< MachineSchedRegistry::ScheduleDAGCtor > MachineSchedRegistry::Registry static
Definition at line 170 of file MachineScheduler.h.
Referenced by getList(), MachineSchedRegistry(), setListener(), and ~MachineSchedRegistry().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp