LLVM: llvm::CombinerHelper Class Reference
llvm::CombinerHelper Class Reference
#include "llvm/CodeGen/GlobalISel/CombinerHelper.h"
Public Member Functions
CombinerHelper (GISelChangeObserver &Observer, MachineIRBuilder &B, bool IsPreLegalize, GISelValueTracking *VT=nullptr, MachineDominatorTree *MDT=nullptr, const LegalizerInfo *LI=nullptr)
GISelValueTracking * getValueTracking () const
MachineIRBuilder & getBuilder () const
const TargetLowering & getTargetLowering () const
const MachineFunction & getMachineFunction () const
const DataLayout & getDataLayout () const
LLVMContext & getContext () const
bool isPreLegalize () const
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrBeforeLegalizer (const LegalityQuery &Query) const
bool isLegalOrHasWidenScalar (const LegalityQuery &Query) const
bool isConstantLegalOrBeforeLegalizer (const LLT Ty) const
void replaceRegWith (MachineRegisterInfo &MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
void replaceRegOpWith (MachineRegisterInfo &MRI, MachineOperand &FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
void replaceOpcodeWith (MachineInstr &FromMI, unsigned ToOpcode) const
Replace the opcode in instruction with a new opcode and inform the observer of the changes.
const RegisterBank * getRegBank (Register Reg) const
Get the register bank of Reg.
void setRegBank (Register Reg, const RegisterBank *RegBank) const
Set the register bank of Reg.
bool tryCombineCopy (MachineInstr &MI) const
If MI is COPY, try to combine it.
bool matchCombineCopy (MachineInstr &MI) const
void applyCombineCopy (MachineInstr &MI) const
bool isPredecessor (const MachineInstr &DefMI, const MachineInstr &UseMI) const
Returns true if DefMI precedes UseMI or they are the same instruction.
bool dominates (const MachineInstr &DefMI, const MachineInstr &UseMI) const
Returns true if DefMI dominates UseMI.
bool tryCombineExtendingLoads (MachineInstr &MI) const
If MI is extend that consumes the result of a load, try to combine it.
bool matchCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo) const
void applyCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo) const
bool matchCombineLoadWithAndMask (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match (and (load x), mask) -> zextload x.
bool matchCombineExtractedVectorLoad (MachineInstr &MI, BuildFnTy &MatchInfo) const
Combine a G_EXTRACT_VECTOR_ELT of a load into a narrowed load.
bool matchCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo) const
void applyCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo) const
bool matchSextTruncSextLoad (MachineInstr &MI) const
void applySextTruncSextLoad (MachineInstr &MI) const
bool matchSextInRegOfLoad (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo) const
Match sext_inreg(load p), imm -> sextload p.
void applySextInRegOfLoad (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo) const
bool matchCombineDivRem (MachineInstr &MI, MachineInstr *&OtherMI) const
Try to combine G_[SU]DIV and G_[SU]REM into a single G_[SU]DIVREM when their source operands are identical.
void applyCombineDivRem (MachineInstr &MI, MachineInstr *&OtherMI) const
bool matchOptBrCondByInvertingCond (MachineInstr &MI, MachineInstr *&BrCond) const
If a brcond's true block is not the fallthrough, make it so by inverting the condition and swapping operands.
void applyOptBrCondByInvertingCond (MachineInstr &MI, MachineInstr *&BrCond) const
bool matchCombineConcatVectors (MachineInstr &MI, SmallVector< Register > &Ops) const
If MI is G_CONCAT_VECTORS, try to combine it.
void applyCombineConcatVectors (MachineInstr &MI, SmallVector< Register > &Ops) const
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
bool matchCombineShuffleConcat (MachineInstr &MI, SmallVector< Register > &Ops) const
void applyCombineShuffleConcat (MachineInstr &MI, SmallVector< Register > &Ops) const
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
bool matchCombineShuffleToBuildVector (MachineInstr &MI) const
Replace MI with a build_vector.
void applyCombineShuffleToBuildVector (MachineInstr &MI) const
bool tryCombineShuffleVector (MachineInstr &MI) const
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
bool matchCombineShuffleVector (MachineInstr &MI, SmallVectorImpl< Register > &Ops) const
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
void applyCombineShuffleVector (MachineInstr &MI, const ArrayRef< Register > Ops) const
Replace MI with a concat_vectors with Ops.
bool matchShuffleToExtract (MachineInstr &MI) const
void applyShuffleToExtract (MachineInstr &MI) const
bool tryCombineMemCpyFamily (MachineInstr &MI, unsigned MaxLen=0) const
Optimize memcpy intrinsics et al, e.g.
bool matchPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo) const
void applyPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo) const
bool matchShiftImmedChain (MachineInstr &MI, RegisterImmPair &MatchInfo) const
Fold (shift (shift base, x), y) -> (shift base (x+y))
void applyShiftImmedChain (MachineInstr &MI, RegisterImmPair &MatchInfo) const
bool matchShiftOfShiftedLogic (MachineInstr &MI, ShiftOfShiftedLogic &MatchInfo) const
If we have a shift-by-constant of a bitwise logic op that itself has a shift-by-constant operand with identical opcode, we may be able to convert that into 2 independent shifts followed by the logic op.
void applyShiftOfShiftedLogic (MachineInstr &MI, ShiftOfShiftedLogic &MatchInfo) const
bool matchCommuteShift (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchCombineMulToShl (MachineInstr &MI, unsigned &ShiftVal) const
Transform a multiply by a power-of-2 value to a left shift.
void applyCombineMulToShl (MachineInstr &MI, unsigned &ShiftVal) const
bool matchCombineSubToAdd (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchCombineShlOfExtend (MachineInstr &MI, RegisterImmPair &MatchData) const
void applyCombineShlOfExtend (MachineInstr &MI, const RegisterImmPair &MatchData) const
bool matchCombineMergeUnmerge (MachineInstr &MI, Register &MatchInfo) const
Fold away a merge of an unmerge of the corresponding values.
bool matchCombineShiftToUnmerge (MachineInstr &MI, unsigned TargetShiftSize, unsigned &ShiftVal) const
Reduce a shift by a constant to an unmerge and a shift on a half sized type.
void applyCombineShiftToUnmerge (MachineInstr &MI, const unsigned &ShiftVal) const
bool tryCombineShiftToUnmerge (MachineInstr &MI, unsigned TargetShiftAmount) const
bool matchCombineUnmergeMergeToPlainValues (MachineInstr &MI, SmallVectorImpl< Register > &Operands) const
Transform <ty,...> G_UNMERGE(G_MERGE ty X, Y, Z) -> ty X, Y, Z.
void applyCombineUnmergeMergeToPlainValues (MachineInstr &MI, SmallVectorImpl< Register > &Operands) const
bool matchCombineUnmergeConstant (MachineInstr &MI, SmallVectorImpl< APInt > &Csts) const
Transform G_UNMERGE Constant -> Constant1, Constant2, ...
void applyCombineUnmergeConstant (MachineInstr &MI, SmallVectorImpl< APInt > &Csts) const
bool matchCombineUnmergeUndef (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo) const
Transform G_UNMERGE G_IMPLICIT_DEF -> G_IMPLICIT_DEF, G_IMPLICIT_DEF, ...
bool matchCombineUnmergeWithDeadLanesToTrunc (MachineInstr &MI) const
Transform X, Y<dead> = G_UNMERGE Z -> X = G_TRUNC Z.
void applyCombineUnmergeWithDeadLanesToTrunc (MachineInstr &MI) const
bool matchCombineUnmergeZExtToZExt (MachineInstr &MI) const
Transform X, Y = G_UNMERGE(G_ZEXT(Z)) -> X = G_ZEXT(Z); Y = G_CONSTANT 0.
void applyCombineUnmergeZExtToZExt (MachineInstr &MI) const
void applyCombineConstantFoldFpUnary (MachineInstr &MI, const ConstantFP *Cst) const
Transform fp_instr(cst) to constant result of the fp operation.
bool matchCombineI2PToP2I (MachineInstr &MI, Register &Reg) const
Transform IntToPtr(PtrToInt(x)) to x if cast is in the same address space.
void applyCombineI2PToP2I (MachineInstr &MI, Register &Reg) const
void applyCombineP2IToI2P (MachineInstr &MI, Register &Reg) const
Transform PtrToInt(IntToPtr(x)) to x.
bool matchCombineAddP2IToPtrAdd (MachineInstr &MI, std::pair< Register, bool > &PtrRegAndCommute) const
Transform G_ADD (G_PTRTOINT x), y -> G_PTRTOINT (G_PTR_ADD x, y) Transform G_ADD y, (G_PTRTOINT x) -> G_PTRTOINT (G_PTR_ADD x, y)
void applyCombineAddP2IToPtrAdd (MachineInstr &MI, std::pair< Register, bool > &PtrRegAndCommute) const
bool matchCombineConstPtrAddToI2P (MachineInstr &MI, APInt &NewCst) const
void applyCombineConstPtrAddToI2P (MachineInstr &MI, APInt &NewCst) const
bool matchCombineAnyExtTrunc (MachineInstr &MI, Register &Reg) const
Transform anyext(trunc(x)) to x.
bool matchCombineZextTrunc (MachineInstr &MI, Register &Reg) const
Transform zext(trunc(x)) to x.
bool matchCombineTruncOfShift (MachineInstr &MI, std::pair< MachineInstr *, LLT > &MatchInfo) const
Transform trunc (shl x, K) to shl (trunc x), K if K < VT.getScalarSizeInBits().
void applyCombineTruncOfShift (MachineInstr &MI, std::pair< MachineInstr *, LLT > &MatchInfo) const
bool matchAnyExplicitUseIsUndef (MachineInstr &MI) const
Return true if any explicit use operand on MI is defined by a G_IMPLICIT_DEF.
bool matchAllExplicitUsesAreUndef (MachineInstr &MI) const
Return true if all register explicit use operands on MI are defined by a G_IMPLICIT_DEF.
bool matchUndefShuffleVectorMask (MachineInstr &MI) const
Return true if a G_SHUFFLE_VECTOR instruction MI has an undef mask.
bool matchUndefStore (MachineInstr &MI) const
Return true if a G_STORE instruction MI is storing an undef value.
bool matchUndefSelectCmp (MachineInstr &MI) const
Return true if a G_SELECT instruction MI has an undef comparison.
bool matchInsertExtractVecEltOutOfBounds (MachineInstr &MI) const
Return true if a G_{EXTRACT,INSERT}_VECTOR_ELT has an out of range index.
bool matchConstantSelectCmp (MachineInstr &MI, unsigned &OpIdx) const
Return true if a G_SELECT instruction MI has a constant comparison.
void replaceInstWithFConstant (MachineInstr &MI, double C) const
Replace an instruction with a G_FCONSTANT with value C.
void replaceInstWithFConstant (MachineInstr &MI, ConstantFP *CFP) const
Replace an instruction with an G_FCONSTANT with value CFP.
void replaceInstWithConstant (MachineInstr &MI, int64_t C) const
Replace an instruction with a G_CONSTANT with value C.
void replaceInstWithConstant (MachineInstr &MI, APInt C) const
Replace an instruction with a G_CONSTANT with value C.
void replaceInstWithUndef (MachineInstr &MI) const
Replace an instruction with a G_IMPLICIT_DEF.
void replaceSingleDefInstWithOperand (MachineInstr &MI, unsigned OpIdx) const
Delete MI and replace all of its uses with its OpIdx-th operand.
void replaceSingleDefInstWithReg (MachineInstr &MI, Register Replacement) const
Delete MI and replace all of its uses with Replacement.
void applyFunnelShiftConstantModulo (MachineInstr &MI) const
Replaces the shift amount in MI with ShiftAmt % BW.
bool matchEqualDefs (const MachineOperand &MOP1, const MachineOperand &MOP2) const
Return true if MOP1 and MOP2 are register operands are defined by equivalent instructions.
bool matchConstantOp (const MachineOperand &MOP, int64_t C) const
Return true if MOP is defined by a G_CONSTANT or splat with a value equal to C.
bool matchConstantFPOp (const MachineOperand &MOP, double C) const
Return true if MOP is defined by a G_FCONSTANT or splat with a value exactly equal to C.
bool matchConstantLargerBitWidth (MachineInstr &MI, unsigned ConstIdx) const
Checks if constant at ConstIdx is larger than MI 's bitwidth.
bool matchSelectSameVal (MachineInstr &MI) const
Optimize (cond ? x : x) -> x.
bool matchBinOpSameVal (MachineInstr &MI) const
Optimize (x op x) -> x.
bool matchOperandIsZero (MachineInstr &MI, unsigned OpIdx) const
Check if operand OpIdx is zero.
bool matchOperandIsUndef (MachineInstr &MI, unsigned OpIdx) const
Check if operand OpIdx is undef.
bool matchOperandIsKnownToBeAPowerOfTwo (MachineInstr &MI, unsigned OpIdx) const
Check if operand OpIdx is known to be a power of 2.
void eraseInst (MachineInstr &MI) const
Erase MI.
bool matchSimplifyAddToSub (MachineInstr &MI, std::tuple< Register, Register > &MatchInfo) const
Return true if MI is a G_ADD which can be simplified to a G_SUB.
void applySimplifyAddToSub (MachineInstr &MI, std::tuple< Register, Register > &MatchInfo) const
bool matchHoistLogicOpWithSameOpcodeHands (MachineInstr &MI, InstructionStepsMatchInfo &MatchInfo) const
Match (logic_op (op x...), (op y...)) -> (op (logic_op x, y))
void applyBuildInstructionSteps (MachineInstr &MI, InstructionStepsMatchInfo &MatchInfo) const
Replace MI with a series of instructions described in MatchInfo.
bool matchAshrShlToSextInreg (MachineInstr &MI, std::tuple< Register, int64_t > &MatchInfo) const
Match ashr (shl x, C), C -> sext_inreg (C)
void applyAshShlToSextInreg (MachineInstr &MI, std::tuple< Register, int64_t > &MatchInfo) const
bool matchOverlappingAnd (MachineInstr &MI, BuildFnTy &MatchInfo) const
Fold and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0.
bool matchRedundantAnd (MachineInstr &MI, Register &Replacement) const
bool matchRedundantOr (MachineInstr &MI, Register &Replacement) const
bool matchRedundantSExtInReg (MachineInstr &MI) const
bool matchNotCmp (MachineInstr &MI, SmallVectorImpl< Register > &RegsToNegate) const
Combine inverting a result of a compare into the opposite cond code.
void applyNotCmp (MachineInstr &MI, SmallVectorImpl< Register > &RegsToNegate) const
bool matchXorOfAndWithSameReg (MachineInstr &MI, std::pair< Register, Register > &MatchInfo) const
Fold (xor (and x, y), y) -> (and (not x), y) {.
void applyXorOfAndWithSameReg (MachineInstr &MI, std::pair< Register, Register > &MatchInfo) const
bool matchPtrAddZero (MachineInstr &MI) const
}
void applyPtrAddZero (MachineInstr &MI) const
void applySimplifyURemByPow2 (MachineInstr &MI) const
Combine G_UREM x, (known power of 2) to an add and bitmasking.
bool matchFoldBinOpIntoSelect (MachineInstr &MI, unsigned &SelectOpNo) const
Push a binary operator through a select on constants.
void applyFoldBinOpIntoSelect (MachineInstr &MI, const unsigned &SelectOpNo) const
SelectOperand is the operand in binary operator MI that is the select to fold.
bool matchCombineInsertVecElts (MachineInstr &MI, SmallVectorImpl< Register > &MatchInfo) const
void applyCombineInsertVecElts (MachineInstr &MI, SmallVectorImpl< Register > &MatchInfo) const
bool matchLoadOrCombine (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match expression trees of the form.
bool matchExtendThroughPhis (MachineInstr &MI, MachineInstr *&ExtMI) const
void applyExtendThroughPhis (MachineInstr &MI, MachineInstr *&ExtMI) const
bool matchExtractVecEltBuildVec (MachineInstr &MI, Register &Reg) const
void applyExtractVecEltBuildVec (MachineInstr &MI, Register &Reg) const
bool matchExtractAllEltsFromBuildVector (MachineInstr &MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > &MatchInfo) const
void applyExtractAllEltsFromBuildVector (MachineInstr &MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > &MatchInfo) const
void applyBuildFn (MachineInstr &MI, BuildFnTy &MatchInfo) const
Use a function which takes in a MachineIRBuilder to perform a combine.
void applyBuildFnNoErase (MachineInstr &MI, BuildFnTy &MatchInfo) const
Use a function which takes in a MachineIRBuilder to perform a combine.
bool matchOrShiftToFunnelShift (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchFunnelShiftToRotate (MachineInstr &MI) const
Match an FSHL or FSHR that can be combined to a ROTR or ROTL rotate.
void applyFunnelShiftToRotate (MachineInstr &MI) const
bool matchRotateOutOfRange (MachineInstr &MI) const
void applyRotateOutOfRange (MachineInstr &MI) const
bool matchUseVectorTruncate (MachineInstr &MI, Register &MatchInfo) const
void applyUseVectorTruncate (MachineInstr &MI, Register &MatchInfo) const
bool matchICmpToTrueFalseKnownBits (MachineInstr &MI, int64_t &MatchInfo) const
bool matchICmpToLHSKnownBits (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchAndOrDisjointMask (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchBitfieldExtractFromSExtInReg (MachineInstr &MI, BuildFnTy &MatchInfo) const
Form a G_SBFX from a G_SEXT_INREG fed by a right shift.
bool matchBitfieldExtractFromAnd (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match: and (lshr x, cst), mask -> ubfx x, cst, width.
bool matchBitfieldExtractFromShr (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match: shr (shl x, n), k -> sbfx/ubfx x, pos, width.
bool matchBitfieldExtractFromShrAnd (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match: shr (and x, n), k -> ubfx x, pos, width.
bool matchReassocConstantInnerRHS (GPtrAdd &MI, MachineInstr *RHS, BuildFnTy &MatchInfo) const
bool matchReassocFoldConstantsInSubTree (GPtrAdd &MI, MachineInstr *LHS, MachineInstr *RHS, BuildFnTy &MatchInfo) const
bool matchReassocConstantInnerLHS (GPtrAdd &MI, MachineInstr *LHS, MachineInstr *RHS, BuildFnTy &MatchInfo) const
bool matchReassocPtrAdd (MachineInstr &MI, BuildFnTy &MatchInfo) const
Reassociate pointer calculations with G_ADD involved, to allow better addressing mode usage.
bool tryReassocBinOp (unsigned Opc, Register DstReg, Register Op0, Register Op1, BuildFnTy &MatchInfo) const
Try to reassociate to reassociate operands of a commutative binop.
bool matchReassocCommBinOp (MachineInstr &MI, BuildFnTy &MatchInfo) const
Reassociate commutative binary operations like G_ADD.
bool matchConstantFoldCastOp (MachineInstr &MI, APInt &MatchInfo) const
Do constant folding when opportunities are exposed after MIR building.
bool matchConstantFoldBinOp (MachineInstr &MI, APInt &MatchInfo) const
Do constant folding when opportunities are exposed after MIR building.
bool matchConstantFoldFPBinOp (MachineInstr &MI, ConstantFP *&MatchInfo) const
Do constant FP folding when opportunities are exposed after MIR building.
bool matchConstantFoldFMA (MachineInstr &MI, ConstantFP *&MatchInfo) const
Constant fold G_FMA/G_FMAD.
bool matchNarrowBinopFeedingAnd (MachineInstr &MI, BuildFnTy &MatchInfo) const
MachineInstr * buildUDivorURemUsingMul (MachineInstr &MI) const
Given an G_UDIV MI or G_UREM MI expressing a divide by constant, return an expression that implements it by multiplying by a magic number.
bool matchUDivorURemByConst (MachineInstr &MI) const
Combine G_UDIV or G_UREM by constant into a multiply by magic constant.
void applyUDivorURemByConst (MachineInstr &MI) const
MachineInstr * buildSDivUsingMul (MachineInstr &MI) const
Given an G_SDIV MI expressing a signed divide by constant, return an expression that implements it by multiplying by a magic number.
bool matchSDivByConst (MachineInstr &MI) const
Combine G_SDIV by constant into a multiply by magic constant.
void applySDivByConst (MachineInstr &MI) const
bool matchDivByPow2 (MachineInstr &MI, bool IsSigned) const
Given an G_SDIV MI expressing a signed divided by a pow2 constant, return expressions that implements it by shifting.
void applySDivByPow2 (MachineInstr &MI) const
void applyUDivByPow2 (MachineInstr &MI) const
Given an G_UDIV MI expressing an unsigned divided by a pow2 constant, return expressions that implements it by shifting.
bool matchUMulHToLShr (MachineInstr &MI) const
void applyUMulHToLShr (MachineInstr &MI) const
bool tryCombine (MachineInstr &MI) const
Try to transform MI by using all of the above combine functions.
bool tryEmitMemcpyInline (MachineInstr &MI) const
Emit loads and stores that perform the given memcpy.
bool matchMulOBy2 (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match: (G_UMULO x, 2) -> (G_UADDO x, x) (G_SMULO x, 2) -> (G_SADDO x, x)
bool matchMulOBy0 (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match: (G_*MULO x, 0) -> 0 + no carry out.
bool matchAddEToAddO (MachineInstr &MI, BuildFnTy &MatchInfo) const
Match: (G_*ADDE x, y, 0) -> (G_*ADDO x, y) (G_*SUBE x, y, 0) -> (G_*SUBO x, y)
bool matchRedundantNegOperands (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fadd x, fneg(y)) -> (fsub x, y) (fadd fneg(x), y) -> (fsub y, x) (fsub x, fneg(y)) -> (fadd x, y) (fmul fneg(x), fneg(y)) -> (fmul x, y) (fdiv fneg(x), fneg(y)) -> (fdiv x, y) (fmad fneg(x), fneg(y), z) -> (fmad x, y, z) (fma fneg(x), fneg(y), z) -> (fma x, y, z)
bool matchFsubToFneg (MachineInstr &MI, Register &MatchInfo) const
void applyFsubToFneg (MachineInstr &MI, Register &MatchInfo) const
bool canCombineFMadOrFMA (MachineInstr &MI, bool &AllowFusionGlobally, bool &HasFMAD, bool &Aggressive, bool CanReassociate=false) const
bool matchCombineFAddFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fadd (fmul x, y), z) -> (fma x, y, z) (fadd (fmul x, y), z) -> (fmad x, y, z)
bool matchCombineFAddFpExtFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fadd (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), z) (fadd (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), z)
bool matchCombineFAddFMAFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fadd (fma x, y, (fmul u, v)), z) -> (fma x, y, (fma u, v, z)) (fadd (fmad x, y, (fmul u, v)), z) -> (fmad x, y, (fmad u, v, z))
bool matchCombineFAddFpExtFMulToFMadOrFMAAggressive (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchCombineFSubFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fsub (fmul x, y), z) -> (fma x, y, -z) (fsub (fmul x, y), z) -> (fmad x, y, -z)
bool matchCombineFSubFNegFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fsub (fneg (fmul, x, y)), z) -> (fma (fneg x), y, (fneg z)) (fsub (fneg (fmul, x, y)), z) -> (fmad (fneg x), y, (fneg z))
bool matchCombineFSubFpExtFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fsub (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), (fneg z)) (fsub (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), (fneg z))
bool matchCombineFSubFpExtFNegFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fma (fpext x), (fpext y), z)) (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fmad (fpext x), (fpext y), z))
bool matchCombineFMinMaxNaN (MachineInstr &MI, unsigned &Info) const
bool matchAddSubSameReg (MachineInstr &MI, Register &Src) const
Transform G_ADD(x, G_SUB(y, x)) to y.
bool matchBuildVectorIdentityFold (MachineInstr &MI, Register &MatchInfo) const
bool matchTruncBuildVectorFold (MachineInstr &MI, Register &MatchInfo) const
bool matchTruncLshrBuildVectorFold (MachineInstr &MI, Register &MatchInfo) const
bool matchSubAddSameReg (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform: (x + y) - y -> x (x + y) - x -> y x - (y + x) -> 0 - y x - (x + z) -> 0 - z.
bool matchSimplifySelectToMinMax (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchRedundantBinOpInEquality (MachineInstr &MI, BuildFnTy &MatchInfo) const
Transform: (X + Y) == X -> Y == 0 (X - Y) == X -> Y == 0 (X ^ Y) == X -> Y == 0 (X + Y) != X -> Y != 0 (X - Y) != X -> Y != 0 (X ^ Y) != X -> Y != 0.
bool matchShiftsTooBig (MachineInstr &MI, std::optional< int64_t > &MatchInfo) const
Match shifts greater or equal to the range (the bitwidth of the result datatype, or the effective bitwidth of the source value).
bool matchCommuteConstantToRHS (MachineInstr &MI) const
Match constant LHS ops that should be commuted.
bool matchSextOfTrunc (const MachineOperand &MO, BuildFnTy &MatchInfo) const
Combine sext of trunc.
bool matchZextOfTrunc (const MachineOperand &MO, BuildFnTy &MatchInfo) const
Combine zext of trunc.
bool matchNonNegZext (const MachineOperand &MO, BuildFnTy &MatchInfo) const
Combine zext nneg to sext.
bool matchCommuteFPConstantToRHS (MachineInstr &MI) const
Match constant LHS FP ops that should be commuted.
void applyCommuteBinOpOperands (MachineInstr &MI) const
bool matchSelectIMinMax (const MachineOperand &MO, BuildFnTy &MatchInfo) const
Combine select to integer min/max.
bool matchSimplifyNegMinMax (MachineInstr &MI, BuildFnTy &MatchInfo) const
Tranform (neg (min/max x, (neg x))) into (max/min x, (neg x)).
bool matchSelect (MachineInstr &MI, BuildFnTy &MatchInfo) const
Combine selects.
bool matchAnd (MachineInstr &MI, BuildFnTy &MatchInfo) const
Combine ands.
bool matchOr (MachineInstr &MI, BuildFnTy &MatchInfo) const
Combine ors.
bool matchNarrowBinop (const MachineInstr &TruncMI, const MachineInstr &BinopMI, BuildFnTy &MatchInfo) const
trunc (binop X, C) --> binop (trunc X, trunc C).
bool matchCastOfInteger (const MachineInstr &CastMI, APInt &MatchInfo) const
bool matchAddOverflow (MachineInstr &MI, BuildFnTy &MatchInfo) const
Combine addos.
bool matchExtractVectorElement (MachineInstr &MI, BuildFnTy &MatchInfo) const
Combine extract vector element.
bool matchExtractVectorElementWithBuildVector (const MachineInstr &MI, const MachineInstr &MI2, BuildFnTy &MatchInfo) const
Combine extract vector element with a build vector on the vector register.
bool matchExtractVectorElementWithBuildVectorTrunc (const MachineOperand &MO, BuildFnTy &MatchInfo) const
Combine extract vector element with a build vector trunc on the vector register.
bool matchExtractVectorElementWithShuffleVector (const MachineInstr &MI, const MachineInstr &MI2, BuildFnTy &MatchInfo) const
Combine extract vector element with a shuffle vector on the vector register.
bool matchExtractVectorElementWithDifferentIndices (const MachineOperand &MO, BuildFnTy &MatchInfo) const
Combine extract vector element with a insert vector element on the vector register and different indices.
bool matchShuffleUndefRHS (MachineInstr &MI, BuildFnTy &MatchInfo) const
Remove references to rhs if it is undef.
bool matchShuffleDisjointMask (MachineInstr &MI, BuildFnTy &MatchInfo) const
Turn shuffle a, b, mask -> shuffle undef, b, mask iff mask does not reference a.
void applyBuildFnMO (const MachineOperand &MO, BuildFnTy &MatchInfo) const
Use a function which takes in a MachineIRBuilder to perform a combine.
bool matchFPowIExpansion (MachineInstr &MI, int64_t Exponent) const
Match FPOWI if it's safe to extend it into a series of multiplications.
void applyExpandFPowI (MachineInstr &MI, int64_t Exponent) const
Expands FPOWI into a series of multiplications and a division if the exponent is negative.
bool matchInsertVectorElementOOB (MachineInstr &MI, BuildFnTy &MatchInfo) const
Combine insert vector element OOB.
bool matchFreezeOfSingleMaybePoisonOperand (MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchAddOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo) const
bool matchMulOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo) const
bool matchSubOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo) const
bool matchShlOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo) const
bool matchTruncateOfExt (const MachineInstr &Root, const MachineInstr &ExtMI, BuildFnTy &MatchInfo) const
Transform trunc ([asz]ext x) to x or ([asz]ext x) or (trunc x).
bool matchCastOfSelect (const MachineInstr &Cast, const MachineInstr &SelectMI, BuildFnTy &MatchInfo) const
bool matchFoldAPlusC1MinusC2 (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchFoldC2MinusAPlusC1 (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchFoldAMinusC1MinusC2 (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchFoldC1Minus2MinusC2 (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchFoldAMinusC1PlusC2 (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchExtOfExt (const MachineInstr &FirstMI, const MachineInstr &SecondMI, BuildFnTy &MatchInfo) const
bool matchCastOfBuildVector (const MachineInstr &CastMI, const MachineInstr &BVMI, BuildFnTy &MatchInfo) const
bool matchCanonicalizeICmp (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchCanonicalizeFCmp (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchUnmergeValuesAnyExtBuildVector (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchMergeXAndUndef (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchMergeXAndZero (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchSuboCarryOut (const MachineInstr &MI, BuildFnTy &MatchInfo) const
bool matchRedundantSextInReg (MachineInstr &Root, MachineInstr &Other, BuildFnTy &MatchInfo) const
Protected Attributes
MachineIRBuilder & Builder
MachineRegisterInfo & MRI
GISelChangeObserver & Observer
GISelValueTracking * VT
MachineDominatorTree * MDT
bool IsPreLegalize
const LegalizerInfo * LI
const RegisterBankInfo * RBI
const TargetRegisterInfo * TRI
Detailed Description
Definition at line 104 of file CombinerHelper.h.
Constructor & Destructor Documentation
CombinerHelper()
CombinerHelper::CombinerHelper (GISelChangeObserver & Observer, MachineIRBuilder & B, bool IsPreLegalize, GISelValueTracking * VT = nullptr, MachineDominatorTree * MDT = nullptr, const LegalizerInfo * LI = nullptr)
Definition at line 57 of file CombinerHelper.cpp.
References B(), Builder, IsPreLegalize, LI, MDT, MRI, Observer, RBI, TRI, and VT.
Member Function Documentation
applyAshShlToSextInreg()
void CombinerHelper::applyAshShlToSextInreg (MachineInstr & MI, std::tuple< Register, int64_t > & MatchInfo) const
Definition at line 3279 of file CombinerHelper.cpp.
References assert(), Builder, MI, MRI, and Size.
applyBuildFn()
void CombinerHelper::applyBuildFn (MachineInstr & MI, BuildFnTy & MatchInfo) const
Use a function which takes in a MachineIRBuilder to perform a combine.
By default, it erases the instruction MI from the function.
Definition at line 4379 of file CombinerHelper.cpp.
References applyBuildFnNoErase(), and MI.
applyBuildFnMO()
void CombinerHelper::applyBuildFnMO (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Use a function which takes in a MachineIRBuilder to perform a combine.
By default, it erases the instruction def'd on MO from the function.
Definition at line 7744 of file CombinerHelper.cpp.
References Builder, llvm::MachineInstr::eraseFromParent(), llvm::getDefIgnoringCopies(), llvm::MachineOperand::getReg(), and MRI.
applyBuildFnNoErase()
void CombinerHelper::applyBuildFnNoErase (MachineInstr & MI, BuildFnTy & MatchInfo) const
Use a function which takes in a MachineIRBuilder to perform a combine.
This variant does not erase MI after calling the build function.
Definition at line 4386 of file CombinerHelper.cpp.
References Builder, and MI.
Referenced by applyBuildFn().
applyBuildInstructionSteps()
void CombinerHelper::applyBuildInstructionSteps (MachineInstr & MI, InstructionStepsMatchInfo & MatchInfo) const
Replace MI with a series of instructions described in MatchInfo.
Definition at line 3247 of file CombinerHelper.cpp.
References assert(), Builder, llvm::InstructionStepsMatchInfo::InstrsToBuild, and MI.
applyCombineAddP2IToPtrAdd()
void CombinerHelper::applyCombineAddP2IToPtrAdd (MachineInstr & MI, std::pair< Register, bool > & PtrRegAndCommute) const
Definition at line 2561 of file CombinerHelper.cpp.
References Builder, MI, MRI, and std::swap().
applyCombineConcatVectors()
void CombinerHelper::applyCombineConcatVectors (MachineInstr & MI, SmallVector< Register > & Ops) const
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
Definition at line 372 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, Builder, MI, MRI, and replaceRegWith().
applyCombineConstantFoldFpUnary()
void CombinerHelper::applyCombineConstantFoldFpUnary (MachineInstr & MI, const ConstantFP * Cst) const
Transform fp_instr(cst) to constant result of the fp operation.
Definition at line 1761 of file CombinerHelper.cpp.
References Builder, constantFoldFpUnary(), llvm::ConstantFP::getValue(), MI, and MRI.
applyCombineConstPtrAddToI2P()
void CombinerHelper::applyCombineConstPtrAddToI2P (MachineInstr & MI, APInt & NewCst) const
Definition at line 2600 of file CombinerHelper.cpp.
References Builder, llvm::cast(), and MI.
applyCombineCopy()
void CombinerHelper::applyCombineCopy (MachineInstr & MI) const
Definition at line 237 of file CombinerHelper.cpp.
References MI, MRI, and replaceRegWith().
Referenced by tryCombineCopy().
applyCombineDivRem()
void CombinerHelper::applyCombineDivRem (MachineInstr & MI, MachineInstr *& OtherMI) const
Definition at line 1608 of file CombinerHelper.cpp.
References assert(), Builder, dominates(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and MI.
applyCombineExtendingLoads()
void CombinerHelper::applyCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo) const
rewrites to:
rewrites to:
Definition at line 846 of file CombinerHelper.cpp.
References Builder, llvm::MachineInstr::eraseFromParent(), llvm::PreferredTuple::ExtendOpcode, getExtLoadOpcForExtend(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::make_pointer_range(), llvm::PreferredTuple::MI, MI, MRI, Observer, replaceRegOpWith(), replaceRegWith(), llvm::MachineOperand::setReg(), llvm::PreferredTuple::Ty, UseMI, and Uses.
Referenced by tryCombineExtendingLoads().
applyCombineI2PToP2I()
void CombinerHelper::applyCombineI2PToP2I (MachineInstr & MI, Register & Reg) const
Definition at line 2520 of file CombinerHelper.cpp.
References assert(), Builder, and MI.
applyCombineIndexedLoadStore()
void CombinerHelper::applyCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo) const
Definition at line 1510 of file CombinerHelper.cpp.
References llvm::IndexedLoadStoreMatchInfo::Addr, llvm::IndexedLoadStoreMatchInfo::Base, Builder, llvm::dbgs(), llvm::MachineInstr::eraseFromParent(), getIndexedOpc(), llvm::IndexedLoadStoreMatchInfo::IsPre, LLVM_DEBUG, MI, MRI, llvm::IndexedLoadStoreMatchInfo::Offset, and llvm::IndexedLoadStoreMatchInfo::RematOffset.
applyCombineInsertVecElts()
void CombinerHelper::applyCombineInsertVecElts (MachineInstr & MI, SmallVectorImpl< Register > & MatchInfo) const
Definition at line 3113 of file CombinerHelper.cpp.
References Builder, llvm::LLT::getScalarType(), MI, and MRI.
applyCombineMulToShl()
void CombinerHelper::applyCombineMulToShl (MachineInstr & MI, unsigned & ShiftVal) const
Definition at line 2089 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), llvm::MCInstrInfo::get(), llvm::LLT::getScalarSizeInBits(), llvm::MachineIRBuilder::getTII(), MI, MRI, llvm::MachineInstr::NoSWrap, and Observer.
applyCombineP2IToI2P()
void CombinerHelper::applyCombineP2IToI2P (MachineInstr & MI, Register & Reg) const
Transform PtrToInt(IntToPtr(x)) to x.
Definition at line 2528 of file CombinerHelper.cpp.
References assert(), Builder, and MI.
applyCombineShiftToUnmerge()
void CombinerHelper::applyCombineShiftToUnmerge (MachineInstr & MI, const unsigned & ShiftVal) const
Definition at line 2427 of file CombinerHelper.cpp.
References assert(), Builder, llvm::Hi, llvm::Lo, MI, MRI, llvm::LLT::scalar(), and Size.
Referenced by tryCombineShiftToUnmerge().
applyCombineShlOfExtend()
void CombinerHelper::applyCombineShlOfExtend (MachineInstr & MI, const RegisterImmPair & MatchData) const
Definition at line 2171 of file CombinerHelper.cpp.
References Builder, llvm::RegisterImmPair::Imm, MI, MRI, and llvm::RegisterImmPair::Reg.
applyCombineShuffleConcat()
void CombinerHelper::applyCombineShuffleConcat (MachineInstr & MI, SmallVector< Register > & Ops) const
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
Definition at line 496 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), Builder, MI, and MRI.
applyCombineShuffleToBuildVector()
void CombinerHelper::applyCombineShuffleToBuildVector (MachineInstr & MI) const
Definition at line 407 of file CombinerHelper.cpp.
References assert(), Builder, llvm::cast(), MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
applyCombineShuffleVector()
void CombinerHelper::applyCombineShuffleVector (MachineInstr & MI, const ArrayRef< Register > Ops) const
Replace MI with a concat_vectors with Ops.
Definition at line 607 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, Builder, MI, MRI, and replaceRegWith().
Referenced by tryCombineShuffleVector().
applyCombineTruncOfShift()
void CombinerHelper::applyCombineTruncOfShift (MachineInstr & MI, std::pair< MachineInstr *, LLT > & MatchInfo) const
Definition at line 2717 of file CombinerHelper.cpp.
References Builder, eraseInst(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), MI, MRI, and replaceRegWith().
applyCombineUnmergeConstant()
void CombinerHelper::applyCombineUnmergeConstant (MachineInstr & MI, SmallVectorImpl< APInt > & Csts) const
Definition at line 2291 of file CombinerHelper.cpp.
References assert(), Builder, MI, and llvm::SmallVectorTemplateCommon< T, typename >::size().
applyCombineUnmergeMergeToPlainValues()
void CombinerHelper::applyCombineUnmergeMergeToPlainValues (MachineInstr & MI, SmallVectorImpl< Register > & Operands) const
Definition at line 2235 of file CombinerHelper.cpp.
References assert(), Builder, MI, MRI, Operands, and replaceRegWith().
applyCombineUnmergeWithDeadLanesToTrunc()
void CombinerHelper::applyCombineUnmergeWithDeadLanesToTrunc (MachineInstr & MI) const
Definition at line 2336 of file CombinerHelper.cpp.
References Builder, and MI.
applyCombineUnmergeZExtToZExt()
void CombinerHelper::applyCombineUnmergeZExtToZExt (MachineInstr & MI) const
Definition at line 2370 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), MI, MRI, and replaceRegWith().
applyCommuteBinOpOperands()
void CombinerHelper::applyCommuteBinOpOperands (MachineInstr & MI) const
Definition at line 6851 of file CombinerHelper.cpp.
References MI, and Observer.
applyExpandFPowI()
void CombinerHelper::applyExpandFPowI (MachineInstr & MI, int64_t Exponent) const
Expands FPOWI into a series of multiplications and a division if the exponent is negative.
Definition at line 7757 of file CombinerHelper.cpp.
References llvm::sampleprof::Base, Builder, llvm::Exponent, MI, and MRI.
applyExtendThroughPhis()
void CombinerHelper::applyExtendThroughPhis (MachineInstr & MI, MachineInstr *& ExtMI) const
Definition at line 4227 of file CombinerHelper.cpp.
References Builder, llvm::cast(), llvm::drop_begin(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, llvm::SetVector< T, Vector, Set, N >::insert(), MBB, MI, MRI, and PHI.
applyExtractAllEltsFromBuildVector()
void CombinerHelper::applyExtractAllEltsFromBuildVector (MachineInstr & MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > & MatchInfo) const
Definition at line 4367 of file CombinerHelper.cpp.
References assert(), MI, MRI, and replaceRegWith().
applyExtractVecEltBuildVec()
void CombinerHelper::applyExtractVecEltBuildVec (MachineInstr & MI, Register & Reg) const
Definition at line 4308 of file CombinerHelper.cpp.
References assert(), Builder, llvm::LLT::getSizeInBits(), MI, MRI, and replaceSingleDefInstWithReg().
applyFoldBinOpIntoSelect()
void CombinerHelper::applyFoldBinOpIntoSelect (MachineInstr & MI, const unsigned & SelectOpNo) const
SelectOperand is the operand in binary operator MI that is the select to fold.
Definition at line 3790 of file CombinerHelper.cpp.
References Builder, getReg(), MI, MRI, and Select.
applyFsubToFneg()
void CombinerHelper::applyFsubToFneg (MachineInstr & MI, Register & MatchInfo) const
Definition at line 5905 of file CombinerHelper.cpp.
References Builder, eraseInst(), MI, and MRI.
applyFunnelShiftConstantModulo()
void CombinerHelper::applyFunnelShiftConstantModulo (MachineInstr & MI) const
Replaces the shift amount in MI with ShiftAmt % BW.
Parameters
MI
Definition at line 2955 of file CombinerHelper.cpp.
References assert(), Builder, llvm::getIConstantVRegValWithLookThrough(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::APInt::getZExtValue(), MI, MRI, and llvm::APInt::urem().
applyFunnelShiftToRotate()
void CombinerHelper::applyFunnelShiftToRotate (MachineInstr & MI) const
Definition at line 4458 of file CombinerHelper.cpp.
References assert(), Builder, MI, Observer, and Opc.
applyNotCmp()
void CombinerHelper::applyNotCmp (MachineInstr & MI, SmallVectorImpl< Register > & RegsToNegate) const
Definition at line 3621 of file CombinerHelper.cpp.
References Builder, llvm::CmpInst::getInversePredicate(), llvm::MachineOperand::getPredicate(), llvm_unreachable, MI, MRI, Observer, replaceRegWith(), and llvm::MachineOperand::setPredicate().
applyOptBrCondByInvertingCond()
void CombinerHelper::applyOptBrCondByInvertingCond (MachineInstr & MI, MachineInstr *& BrCond) const
Definition at line 1674 of file CombinerHelper.cpp.
References Builder, llvm::getICmpTrueVal(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), MI, MRI, Observer, llvm::MachineOperand::setMBB(), llvm::MachineOperand::setReg(), and llvm::Xor.
applyPtrAddImmedChain()
void CombinerHelper::applyPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo) const
Definition at line 1831 of file CombinerHelper.cpp.
References assert(), llvm::PtrAddChain::Bank, llvm::PtrAddChain::Base, llvm::MachineIRBuilder::buildConstant(), llvm::PtrAddChain::Imm, MI, MRI, Observer, and setRegBank().
applyPtrAddZero()
void CombinerHelper::applyPtrAddZero (MachineInstr & MI) const
Definition at line 3716 of file CombinerHelper.cpp.
References Builder, llvm::cast(), and MI.
applyRotateOutOfRange()
void CombinerHelper::applyRotateOutOfRange (MachineInstr & MI) const
Definition at line 4485 of file CombinerHelper.cpp.
References assert(), Builder, MI, MRI, and Observer.
applySDivByConst()
void CombinerHelper::applySDivByConst (MachineInstr & MI) const
Definition at line 5568 of file CombinerHelper.cpp.
References buildSDivUsingMul(), MI, and replaceSingleDefInstWithReg().
applySDivByPow2()
void CombinerHelper::applySDivByPow2 (MachineInstr & MI) const
Definition at line 5725 of file CombinerHelper.cpp.
References llvm::Add, assert(), llvm::BitWidth, Builder, llvm::cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SLT, llvm::LLT::isVector(), MI, MRI, llvm::LLT::scalar(), and llvm::LLT::vector().
applySextInRegOfLoad()
void CombinerHelper::applySextInRegOfLoad (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo) const
Definition at line 1146 of file CombinerHelper.cpp.
References assert(), Builder, llvm::cast(), llvm::MachineInstr::eraseFromParent(), llvm::GMemOperation::getMMO(), llvm::GLoadStore::getPointerReg(), MI, and MRI.
applySextTruncSextLoad()
void CombinerHelper::applySextTruncSextLoad (MachineInstr & MI) const
Definition at line 1088 of file CombinerHelper.cpp.
References assert(), Builder, and MI.
applyShiftImmedChain()
void CombinerHelper::applyShiftImmedChain (MachineInstr & MI, RegisterImmPair & MatchInfo) const
Definition at line 1889 of file CombinerHelper.cpp.
References assert(), Builder, llvm::RegisterImmPair::Imm, MI, MRI, Observer, and llvm::RegisterImmPair::Reg.
applyShiftOfShiftedLogic()
void CombinerHelper::applyShiftOfShiftedLogic (MachineInstr & MI, ShiftOfShiftedLogic & MatchInfo) const
Definition at line 2002 of file CombinerHelper.cpp.
References assert(), Builder, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getReg(), llvm::MachineOperand::getReg(), llvm::ShiftOfShiftedLogic::Logic, llvm::ShiftOfShiftedLogic::LogicNonShiftReg, MI, MRI, llvm::ShiftOfShiftedLogic::Shift2, and llvm::ShiftOfShiftedLogic::ValSum.
applyShuffleToExtract()
void CombinerHelper::applyShuffleToExtract (MachineInstr & MI) const
Definition at line 630 of file CombinerHelper.cpp.
References Builder, I, MI, and MRI.
applySimplifyAddToSub()
void CombinerHelper::applySimplifyAddToSub (MachineInstr & MI, std::tuple< Register, Register > & MatchInfo) const
Definition at line 3131 of file CombinerHelper.cpp.
References Builder, and MI.
applySimplifyURemByPow2()
void CombinerHelper::applySimplifyURemByPow2 (MachineInstr & MI) const
Combine G_UREM x, (known power of 2) to an add and bitmasking.
The second source operand is known to be a power of 2.
Definition at line 3723 of file CombinerHelper.cpp.
References llvm::Add, Builder, MI, and MRI.
applyUDivByPow2()
void CombinerHelper::applyUDivByPow2 (MachineInstr & MI) const
Given an G_UDIV MI expressing an unsigned divided by a pow2 constant, return expressions that implements it by shifting.
Definition at line 5784 of file CombinerHelper.cpp.
References assert(), Builder, llvm::cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), MI, and MRI.
applyUDivorURemByConst()
void CombinerHelper::applyUDivorURemByConst (MachineInstr & MI) const
Definition at line 5520 of file CombinerHelper.cpp.
References buildUDivorURemUsingMul(), MI, and replaceSingleDefInstWithReg().
applyUMulHToLShr()
void CombinerHelper::applyUMulHToLShr (MachineInstr & MI) const
Definition at line 5818 of file CombinerHelper.cpp.
References Builder, buildLogBase2(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarSizeInBits(), getTargetLowering(), MI, and MRI.
applyUseVectorTruncate()
void CombinerHelper::applyUseVectorTruncate (MachineInstr & MI, Register & MatchInfo) const
Definition at line 3517 of file CombinerHelper.cpp.
References Builder, llvm::BuildMI(), llvm::cast(), llvm::LLT::changeElementType(), llvm::LLT::getNumElements(), llvm::LLT::getScalarType(), I, MI, MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
applyXorOfAndWithSameReg()
void CombinerHelper::applyXorOfAndWithSameReg (MachineInstr & MI, std::pair< Register, Register > & MatchInfo) const
Definition at line 3684 of file CombinerHelper.cpp.
References Builder, MI, MRI, Observer, X, and Y.
buildSDivUsingMul()
MachineInstr * CombinerHelper::buildSDivUsingMul (MachineInstr & MI) const
Given an G_SDIV MI expressing a signed divide by constant, return an expression that implements it by multiplying by a magic number.
Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
Definition at line 5573 of file CombinerHelper.cpp.
References llvm::APInt::ashrInPlace(), assert(), Builder, llvm::CallingConv::C, llvm::cast(), llvm::APInt::countr_zero(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SignedDivisionByConstantInfo::get(), llvm::getDefIgnoringCopies(), llvm::getIConstantSplatVal(), llvm::getOpcodeDef(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getScalarType(), llvm::APInt::getSExtValue(), getTargetLowering(), llvm::APInt::isAllOnes(), llvm::MachineInstr::IsExact, llvm::APInt::isNegative(), llvm::APInt::isOne(), llvm::APInt::isStrictlyPositive(), llvm::SignedDivisionByConstantInfo::Magic, llvm::matchUnaryPredicate(), MI, MRI, llvm::APInt::multiplicativeInverse(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SignedDivisionByConstantInfo::ShiftAmount, and T.
Referenced by applySDivByConst().
buildUDivorURemUsingMul()
MachineInstr * CombinerHelper::buildUDivorURemUsingMul (MachineInstr & MI) const
Given an G_UDIV MI or G_UREM MI expressing a divide by constant, return an expression that implements it by multiplying by a magic number.
Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
Definition at line 5303 of file CombinerHelper.cpp.
References assert(), Builder, llvm::CallingConv::C, llvm::cast(), llvm::APInt::countl_zero(), llvm::APInt::countr_zero(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::UnsignedDivisionByConstantInfo::get(), llvm::APInt::getBitWidth(), llvm::getDefIgnoringCopies(), llvm::getIConstantSplatVal(), llvm::APInt::getOneBitSet(), llvm::getOpcodeDef(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getScalarType(), getTargetLowering(), llvm::APInt::getZero(), llvm::CmpInst::ICMP_EQ, llvm::UnsignedDivisionByConstantInfo::IsAdd, llvm::MachineInstr::IsExact, llvm::APInt::isOne(), llvm_unreachable, llvm::APInt::lshrInPlace(), llvm::UnsignedDivisionByConstantInfo::Magic, llvm::matchUnaryPredicate(), MI, MRI, llvm::APInt::multiplicativeInverse(), llvm::UnsignedDivisionByConstantInfo::PostShift, llvm::UnsignedDivisionByConstantInfo::PreShift, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LLT::scalar(), and VT.
Referenced by applyUDivorURemByConst().
canCombineFMadOrFMA()
bool CombinerHelper::canCombineFMadOrFMA (MachineInstr & MI, bool & AllowFusionGlobally, bool & HasFMAD, bool & Aggressive, bool CanReassociate = false) const
Definition at line 5929 of file CombinerHelper.cpp.
References llvm::Aggressive, llvm::FPOpFusion::Fast, llvm::MachineInstr::FmContract, llvm::MachineInstr::FmReassoc, isLegalOrBeforeLegalizer(), isPreLegalize(), MI, MRI, and Options.
Referenced by matchCombineFAddFMAFMulToFMadOrFMA(), matchCombineFAddFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), matchCombineFSubFMulToFMadOrFMA(), matchCombineFSubFNegFMulToFMadOrFMA(), matchCombineFSubFpExtFMulToFMadOrFMA(), and matchCombineFSubFpExtFNegFMulToFMadOrFMA().
dominates()
bool CombinerHelper::dominates (const MachineInstr & DefMI, const MachineInstr & UseMI) const
Returns true if DefMI dominates UseMI.
By definition an instruction dominates itself.
If we haven't been provided with a MachineDominatorTree during construction, this function returns a conservative result that tracks just a single basic block.
Definition at line 1049 of file CombinerHelper.cpp.
References assert(), DefMI, isPredecessor(), MDT, and UseMI.
Referenced by applyCombineDivRem().
eraseInst()
void CombinerHelper::eraseInst (MachineInstr & MI) const
Erase MI.
Definition at line 2802 of file CombinerHelper.cpp.
References MI.
Referenced by applyCombineTruncOfShift(), and applyFsubToFneg().
getBuilder()
MachineIRBuilder & llvm::CombinerHelper::getBuilder () const inline
Definition at line 124 of file CombinerHelper.h.
References Builder.
getContext()
LLVMContext & CombinerHelper::getContext () const
Definition at line 81 of file CombinerHelper.cpp.
References Builder.
getDataLayout()
const DataLayout & CombinerHelper::getDataLayout () const
Definition at line 77 of file CombinerHelper.cpp.
References llvm::MachineFunction::getDataLayout(), and getMachineFunction().
getMachineFunction()
const MachineFunction & CombinerHelper::getMachineFunction () const
Definition at line 73 of file CombinerHelper.cpp.
References Builder.
Referenced by getDataLayout().
getRegBank()
const RegisterBank * CombinerHelper::getRegBank (Register Reg) const
Get the register bank of Reg.
If Reg has not been assigned a register, a register class, or a register bank, then this returns nullptr.
Precondition
Reg.isValid()
Definition at line 213 of file CombinerHelper.cpp.
References MRI, RBI, and TRI.
Referenced by matchPtrAddImmedChain().
getTargetLowering()
const TargetLowering & CombinerHelper::getTargetLowering () const
Definition at line 69 of file CombinerHelper.cpp.
References Builder.
Referenced by applyOptBrCondByInvertingCond(), applySDivByPow2(), applyUDivByPow2(), applyUMulHToLShr(), buildSDivUsingMul(), buildUDivorURemUsingMul(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchBitfieldExtractFromShr(), matchBitfieldExtractFromShrAnd(), matchCombineExtractedVectorLoad(), matchCombineShlOfExtend(), matchCombineTruncOfShift(), matchCommuteShift(), matchExtractVecEltBuildVec(), matchExtractVectorElementWithBuildVector(), matchExtractVectorElementWithBuildVectorTrunc(), matchFPowIExpansion(), matchHoistLogicOpWithSameOpcodeHands(), matchICmpToLHSKnownBits(), matchICmpToTrueFalseKnownBits(), matchLoadOrCombine(), matchNarrowBinopFeedingAnd(), matchNonNegZext(), matchSDivByConst(), matchSuboCarryOut(), matchUDivorURemByConst(), matchUMulHToLShr(), and tryReassocBinOp().
getValueTracking()
GISelValueTracking * llvm::CombinerHelper::getValueTracking () const inline
Definition at line 122 of file CombinerHelper.h.
References VT.
isConstantLegalOrBeforeLegalizer()
bool CombinerHelper::isConstantLegalOrBeforeLegalizer (const LLT Ty) const
Returns
true if the combine is running prior to legalization, or if Ty is a legal integer constant type on the target.
Definition at line 170 of file CombinerHelper.cpp.
References llvm::LLT::getElementType(), isLegal(), isLegalOrBeforeLegalizer(), and isPreLegalize().
Referenced by matchAddOverflow(), matchCastOfInteger(), matchCombineSubToAdd(), matchExtractVectorElementWithShuffleVector(), matchMulOBy0(), and matchSuboCarryOut().
isLegal()
bool CombinerHelper::isLegal (const LegalityQuery & Query) const
Returns
true if Query is legal on the target.
Definition at line 155 of file CombinerHelper.cpp.
References assert(), llvm::LegalizeActions::Legal, and LI.
Referenced by isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), isLegalOrHasWidenScalar(), matchSDivByConst(), matchSimplifyNegMinMax(), and matchUseVectorTruncate().
isLegalOrBeforeLegalizer()
bool CombinerHelper::isLegalOrBeforeLegalizer (const LegalityQuery & Query) const
Returns
true if the combine is running prior to legalization, or if Query is legal on the target.
Definition at line 160 of file CombinerHelper.cpp.
References isLegal(), and isPreLegalize().
Referenced by canCombineFMadOrFMA(), isConstantLegalOrBeforeLegalizer(), matchAddOverflow(), matchAshrShlToSextInreg(), matchCastOfBuildVector(), matchCastOfSelect(), matchCombineConcatVectors(), matchCombineDivRem(), matchCombineExtractedVectorLoad(), matchCombineLoadWithAndMask(), matchCombineShlOfExtend(), matchCombineShuffleConcat(), matchCombineSubToAdd(), matchCombineTruncOfShift(), matchExtOfExt(), matchExtractVectorElement(), matchExtractVectorElementWithBuildVectorTrunc(), matchExtractVectorElementWithShuffleVector(), matchFunnelShiftToRotate(), matchHoistLogicOpWithSameOpcodeHands(), matchICmpToLHSKnownBits(), matchInsertVectorElementOOB(), matchLoadOrCombine(), matchMergeXAndUndef(), matchMergeXAndZero(), matchNarrowBinop(), matchNarrowBinopFeedingAnd(), matchNonNegZext(), matchOrShiftToFunnelShift(), matchRedundantNegOperands(), matchSDivByConst(), matchSelectIMinMax(), matchSextInRegOfLoad(), matchSextOfTrunc(), matchShlOfVScale(), matchShuffleDisjointMask(), matchSuboCarryOut(), matchSubOfVScale(), matchTruncateOfExt(), matchUDivorURemByConst(), matchUMulHToLShr(), matchUnmergeValuesAnyExtBuildVector(), and matchZextOfTrunc().
isLegalOrHasWidenScalar()
bool CombinerHelper::isLegalOrHasWidenScalar (const LegalityQuery & Query) const
Returns
true if Query is legal on the target, or if Query will perform WidenScalar action on the target.
Definition at line 165 of file CombinerHelper.cpp.
References isLegal(), LI, and llvm::LegalizeActions::WidenScalar.
Referenced by matchSDivByConst().
isPredecessor()
bool CombinerHelper::isPredecessor (const MachineInstr & DefMI, const MachineInstr & UseMI) const
Returns true if DefMI precedes UseMI or they are the same instruction.
Both must be in the same basic block.
Definition at line 1033 of file CombinerHelper.cpp.
References assert(), DefMI, llvm::find_if(), llvm_unreachable, MBB, MI, and UseMI.
Referenced by dominates().
isPreLegalize()
bool CombinerHelper::isPreLegalize () const
Returns
true if the combiner is running pre-legalization.
Definition at line 153 of file CombinerHelper.cpp.
References IsPreLegalize.
Referenced by canCombineFMadOrFMA(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), matchCombineExtendingLoads(), and matchCommuteShift().
matchAddEToAddO()
bool CombinerHelper::matchAddEToAddO (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match: (G_*ADDE x, y, 0) -> (G_*ADDO x, y) (G_*SUBE x, y, 0) -> (G_*SUBO x, y)
Definition at line 5225 of file CombinerHelper.cpp.
References assert(), B(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Observer.
matchAddOfVScale()
bool CombinerHelper::matchAddOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Definition at line 365 of file CombinerHelperVectorOps.cpp.
References llvm::Add, B(), llvm::cast(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GVScale::getSrc(), and MRI.
matchAddOverflow()
bool CombinerHelper::matchAddOverflow (MachineInstr & MI, BuildFnTy & MatchInfo) const
Combine addos.
Definition at line 7576 of file CombinerHelper.cpp.
References llvm::Add, llvm::ConstantRange::AlwaysOverflowsHigh, llvm::ConstantRange::AlwaysOverflowsLow, B(), llvm::cast(), llvm::ConstantRange::fromKnownBits(), llvm::MachineInstr::getFlag(), llvm::GBinOp::getLHSReg(), llvm::getOpcodeDef(), llvm::GBinOp::getRHSReg(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), llvm::ConstantRange::MayOverflow, MI, MRI, llvm::ConstantRange::NeverOverflows, llvm::MachineInstr::NoSWrap, llvm::MachineInstr::NoUWrap, llvm::ConstantRange::signedAddMayOverflow(), llvm::ConstantRange::unsignedAddMayOverflow(), and VT.
matchAddSubSameReg()
bool CombinerHelper::matchAddSubSameReg (MachineInstr & MI, Register & Src) const
Transform G_ADD(x, G_SUB(y, x)) to y.
Transform G_ADD(G_SUB(y, x), x) to y.
Definition at line 6505 of file CombinerHelper.cpp.
References assert(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchAllExplicitUsesAreUndef()
bool CombinerHelper::matchAllExplicitUsesAreUndef (MachineInstr & MI) const
Return true if all register explicit use operands on MI are defined by a G_IMPLICIT_DEF.
Definition at line 2749 of file CombinerHelper.cpp.
References llvm::all_of(), and MI.
matchAnd()
bool CombinerHelper::matchAnd (MachineInstr & MI, BuildFnTy & MatchInfo) const
Combine ands.
Definition at line 7552 of file CombinerHelper.cpp.
References llvm::cast(), and MI.
matchAndOrDisjointMask()
bool CombinerHelper::matchAndOrDisjointMask (MachineInstr & MI, BuildFnTy & MatchInfo) const
Returns
true if (and (or x, c1), c2) can be replaced with (and x, c2)
Definition at line 4587 of file CombinerHelper.cpp.
References assert(), B(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Observer.
matchAnyExplicitUseIsUndef()
bool CombinerHelper::matchAnyExplicitUseIsUndef (MachineInstr & MI) const
Return true if any explicit use operand on MI is defined by a G_IMPLICIT_DEF.
Definition at line 2742 of file CombinerHelper.cpp.
References llvm::any_of(), and MI.
matchAshrShlToSextInreg()
bool CombinerHelper::matchAshrShlToSextInreg (MachineInstr & MI, std::tuple< Register, int64_t > & MatchInfo) const
Match ashr (shl x, C), C -> sext_inreg (C)
Definition at line 3261 of file CombinerHelper.cpp.
References assert(), isLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_GAShr(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchBinOpSameVal()
bool CombinerHelper::matchBinOpSameVal (MachineInstr & MI) const
Optimize (x op x) -> x.
Definition at line 2987 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), matchEqualDefs(), MI, and MRI.
matchBitfieldExtractFromAnd()
bool CombinerHelper::matchBitfieldExtractFromAnd (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match: and (lshr x, cst), mask -> ubfx x, cst, width.
Form a G_UBFX from "(a srl b) & mask", where b and mask are constants.
Definition at line 4653 of file CombinerHelper.cpp.
References llvm::cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), LI, MI, and MRI.
matchBitfieldExtractFromSExtInReg()
bool CombinerHelper::matchBitfieldExtractFromSExtInReg (MachineInstr & MI, BuildFnTy & MatchInfo) const
Form a G_SBFX from a G_SEXT_INREG fed by a right shift.
Definition at line 4623 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), LI, MI, and MRI.
matchBitfieldExtractFromShr()
bool CombinerHelper::matchBitfieldExtractFromShr (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match: shr (shl x, n), k -> sbfx/ubfx x, pos, width.
Definition at line 4690 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), LI, MI, and MRI.
matchBitfieldExtractFromShrAnd()
bool CombinerHelper::matchBitfieldExtractFromShrAnd (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match: shr (and x, n), k -> ubfx x, pos, width.
Definition at line 4740 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), LI, MI, and MRI.
matchBuildVectorIdentityFold()
bool CombinerHelper::matchBuildVectorIdentityFold (MachineInstr & MI, Register & MatchInfo) const
Definition at line 6521 of file CombinerHelper.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), llvm::Hi, llvm::Lo, llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GBitcast(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_GBuildVectorTrunc(), llvm::MIPatternMatch::m_GCst(), llvm::MIPatternMatch::m_GImplicitDef(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCanonicalizeFCmp()
bool CombinerHelper::matchCanonicalizeFCmp (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 116 of file CombinerHelperCompares.cpp.
References assert(), B(), llvm::cast(), llvm::GFConstant::getConstant(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::isFPPredicate(), MI, MRI, and std::swap().
matchCanonicalizeICmp()
bool CombinerHelper::matchCanonicalizeICmp (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 91 of file CombinerHelperCompares.cpp.
References assert(), B(), llvm::cast(), llvm::GIConstant::getConstant(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::isIntPredicate(), MI, MRI, and std::swap().
matchCastOfBuildVector()
bool CombinerHelper::matchCastOfBuildVector (const MachineInstr & CastMI, const MachineInstr & BVMI, BuildFnTy & MatchInfo) const
Definition at line 296 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), llvm::GMergeLikeInstr::getNumSources(), llvm::MachineInstr::getOpcode(), llvm::GenericMachineInstr::getReg(), llvm::LLT::getScalarType(), I, isLegalOrBeforeLegalizer(), MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
matchCastOfInteger()
bool CombinerHelper::matchCastOfInteger (const MachineInstr & CastMI, APInt & MatchInfo) const
Definition at line 361 of file CombinerHelperCasts.cpp.
References llvm::cast(), llvm::getIConstantFromReg(), llvm::MachineInstr::getOpcode(), llvm::GenericMachineInstr::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::GCastOp::getSrcReg(), isConstantLegalOrBeforeLegalizer(), and MRI.
matchCastOfSelect()
bool CombinerHelper::matchCastOfSelect (const MachineInstr & Cast, const MachineInstr & SelectMI, BuildFnTy & MatchInfo) const
Definition at line 200 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), Cond, llvm::MachineInstr::getOpcode(), llvm::GenericMachineInstr::getReg(), isLegalOrBeforeLegalizer(), MRI, and Select.
matchCombineAddP2IToPtrAdd()
bool CombinerHelper::matchCombineAddP2IToPtrAdd (MachineInstr & MI, std::pair< Register, bool > & PtrRegAndCommute) const
Transform G_ADD (G_PTRTOINT x), y -> G_PTRTOINT (G_PTR_ADD x, y) Transform G_ADD y, (G_PTRTOINT x) -> G_PTRTOINT (G_PTR_ADD x, y)
Definition at line 2536 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getScalarSizeInBits(), llvm::MIPatternMatch::m_GPtrToInt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineAnyExtTrunc()
bool CombinerHelper::matchCombineAnyExtTrunc (MachineInstr & MI, Register & Reg) const
Transform anyext(trunc(x)) to x.
Definition at line 2609 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), llvm::getSrcRegIgnoringCopies(), llvm::Register::isValid(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineConcatVectors()
bool CombinerHelper::matchCombineConcatVectors (MachineInstr & MI, SmallVector< Register > & Ops) const
If MI is G_CONCAT_VECTORS, try to combine it.
Returns true if MI changed. Right now, we support:
concat_vector(undef, undef) => undef
concat_vector(build_vector(A, B), build_vector(C, D)) =>
build_vector(A, B, C, D)
Check if the G_CONCAT_VECTORS MI is undef or if it can be flattened into a build_vector. In the first case Ops will be empty In the second case Ops will contain the operands needed to produce the flattened build_vector.
Precondition
MI.getOpcode() == G_CONCAT_VECTORS.
Definition at line 314 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), Builder, isLegalOrBeforeLegalizer(), MI, and MRI.
matchCombineConstPtrAddToI2P()
bool CombinerHelper::matchCombineConstPtrAddToI2P (MachineInstr & MI, APInt & NewCst) const
Definition at line 2579 of file CombinerHelper.cpp.
References Builder, llvm::cast(), llvm::getIConstantVRegVal(), llvm::MIPatternMatch::m_GIntToPtr(), llvm::MIPatternMatch::m_ICst(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::APInt::sextOrTrunc(), and llvm::APInt::zextOrTrunc().
matchCombineCopy()
bool CombinerHelper::matchCombineCopy (MachineInstr & MI) const
Definition at line 230 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), MI, and MRI.
Referenced by tryCombineCopy().
matchCombineDivRem()
bool CombinerHelper::matchCombineDivRem (MachineInstr & MI, MachineInstr *& OtherMI) const
Try to combine G_[SU]DIV and G_[SU]REM into a single G_[SU]DIVREM when their source operands are identical.
Definition at line 1545 of file CombinerHelper.cpp.
References isLegalOrBeforeLegalizer(), llvm_unreachable, matchEqualDefs(), MI, MRI, and UseMI.
matchCombineExtendingLoads()
bool CombinerHelper::matchCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo) const
Definition at line 770 of file CombinerHelper.cpp.
References llvm::dyn_cast(), llvm::GAnyLoad::getDstReg(), getExtLoadOpcForExtend(), llvm::GMemOperation::getMMO(), llvm::GLoadStore::getPointerReg(), llvm::LLT::getSizeInBits(), llvm::has_single_bit(), llvm::isa(), isPreLegalize(), llvm::LLT::isScalar(), llvm::LegalizeActions::Legal, LI, MI, MRI, and UseMI.
Referenced by tryCombineExtendingLoads().
matchCombineExtractedVectorLoad()
bool CombinerHelper::matchCombineExtractedVectorLoad (MachineInstr & MI, BuildFnTy & MatchInfo) const
Combine a G_EXTRACT_VECTOR_ELT of a load into a narrowed load.
Definition at line 1388 of file CombinerHelper.cpp.
References assert(), B(), llvm::CallingConv::C, llvm::commonAlignment(), DL, llvm::MachineInstr::eraseFromParent(), llvm::CallingConv::Fast, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getAlign(), llvm::Function::getContext(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::getIConstantVRegVal(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFunction::getMachineMemOperand(), llvm::getOpcodeDef(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineMemOperand::getPointerInfo(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), getTargetLowering(), llvm::LegalizerHelper::getVectorElementPointer(), llvm::MachinePointerInfo::getWithOffset(), II, llvm::LLT::isByteSized(), isLegalOrBeforeLegalizer(), MI, MRI, llvm::Offset, and llvm::Vector.
matchCombineFAddFMAFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fadd (fma x, y, (fmul u, v)), z) -> (fma x, y, (fma u, v, z)) (fadd (fmad x, y, (fmul u, v)), z) -> (fmad x, y, (fmad u, v, z))
Definition at line 6071 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), hasMoreUses(), isContractableFMul(), MI, MRI, std::swap(), X, and Y.
matchCombineFAddFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFAddFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fadd (fmul x, y), z) -> (fma x, y, z) (fadd (fmul x, y), z) -> (fmad x, y, z)
Definition at line 5962 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), hasMoreUses(), isContractableFMul(), MI, MRI, and std::swap().
matchCombineFAddFpExtFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fadd (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), z) (fadd (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), z)
Definition at line 6011 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), hasMoreUses(), isContractableFMul(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), MRI, and std::swap().
matchCombineFAddFpExtFMulToFMadOrFMAAggressive()
bool CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive (MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 6137 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getReg(), llvm::MachineOperand::getReg(), hasMoreUses(), isContractableFMul(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), MRI, std::swap(), X, and Y.
matchCombineFMinMaxNaN()
bool CombinerHelper::matchCombineFMinMaxNaN (MachineInstr & MI, unsigned & Info) const
Definition at line 6477 of file CombinerHelper.cpp.
References llvm::getConstantFPVRegVal(), llvm::ConstantFP::getValueAPF(), llvm::APFloat::isNaN(), MI, and MRI.
matchCombineFSubFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fsub (fmul x, y), z) -> (fma x, y, -z) (fsub (fmul x, y), z) -> (fmad x, y, -z)
Definition at line 6264 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), hasMoreUses(), isContractableFMul(), MI, and MRI.
matchCombineFSubFNegFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fsub (fneg (fmul, x, y)), z) -> (fma (fneg x), y, (fneg z)) (fsub (fneg (fmul, x, y)), z) -> (fmad (fneg x), y, (fneg z))
Definition at line 6317 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), isContractableFMul(), llvm::MIPatternMatch::m_GFNeg(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineFSubFpExtFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fsub (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), (fneg z)) (fsub (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), (fneg z))
Definition at line 6365 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), isContractableFMul(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineFSubFpExtFNegFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fma (fpext x), (fpext y), z)) (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fmad (fpext x), (fpext y), z))
Definition at line 6417 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B(), canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), isContractableFMul(), llvm::MIPatternMatch::m_GFNeg(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), MRI, X, and Y.
matchCombineI2PToP2I()
bool CombinerHelper::matchCombineI2PToP2I (MachineInstr & MI, Register & Reg) const
Transform IntToPtr(PtrToInt(x)) to x if cast is in the same address space.
Definition at line 2510 of file CombinerHelper.cpp.
References assert(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GPtrToInt(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineIndexedLoadStore()
bool CombinerHelper::matchCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo) const
Definition at line 1493 of file CombinerHelper.cpp.
References llvm::IndexedLoadStoreMatchInfo::Addr, llvm::IndexedLoadStoreMatchInfo::Base, llvm::cast(), llvm::GMemOperation::isAtomic(), llvm::IndexedLoadStoreMatchInfo::IsPre, MI, llvm::IndexedLoadStoreMatchInfo::Offset, and llvm::IndexedLoadStoreMatchInfo::RematOffset.
matchCombineInsertVecElts()
bool CombinerHelper::matchCombineInsertVecElts (MachineInstr & MI, SmallVectorImpl< Register > & MatchInfo) const
Definition at line 3066 of file CombinerHelper.cpp.
References llvm::all_of(), assert(), llvm::LLT::getNumElements(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, llvm::LLT::isScalableVector(), isValid(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GInsertVecElt(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and llvm::SmallVectorImpl< T >::resize().
matchCombineLoadWithAndMask()
bool CombinerHelper::matchCombineLoadWithAndMask (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match (and (load x), mask) -> zextload x.
Definition at line 951 of file CombinerHelper.cpp.
References assert(), B(), llvm::APInt::countr_one(), llvm::dyn_cast(), llvm::MachineInstr::eraseFromParent(), llvm::GAnyLoad::getDstReg(), llvm::getIConstantVRegValWithLookThrough(), llvm::GMemOperation::getMemSizeInBits(), llvm::GMemOperation::getMMO(), llvm::MachineMemOperand::getPointerInfo(), llvm::GLoadStore::getPointerReg(), llvm::LLT::getSizeInBits(), llvm::LocationSize::getValue(), isLegalOrBeforeLegalizer(), llvm::APInt::isMask(), llvm::isPowerOf2_32(), llvm::GMemOperation::isSimple(), llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, RegSize, and llvm::LLT::scalar().
matchCombineMergeUnmerge()
bool CombinerHelper::matchCombineMergeUnmerge (MachineInstr & MI, Register & MatchInfo) const
Fold away a merge of an unmerge of the corresponding values.
Definition at line 2184 of file CombinerHelper.cpp.
References llvm::cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::getOpcodeDef(), I, Merge, MI, MRI, and llvm::SmallVectorTemplateCommon< T, typename >::size().
matchCombineMulToShl()
bool CombinerHelper::matchCombineMulToShl (MachineInstr & MI, unsigned & ShiftVal) const
Transform a multiply by a power-of-2 value to a left shift.
Definition at line 2077 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), MI, and MRI.
matchCombineShiftToUnmerge()
bool CombinerHelper::matchCombineShiftToUnmerge (MachineInstr & MI, unsigned TargetShiftSize, unsigned & ShiftVal) const
Reduce a shift by a constant to an unmerge and a shift on a half sized type.
This will not produce a shift smaller than TargetShiftSize.
Definition at line 2402 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), MI, MRI, and Size.
Referenced by tryCombineShiftToUnmerge().
matchCombineShlOfExtend()
bool CombinerHelper::matchCombineShlOfExtend (MachineInstr & MI, RegisterImmPair & MatchData) const
Definition at line 2131 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::RegisterImmPair::Imm, llvm::isConstantOrConstantSplatVector(), isLegalOrBeforeLegalizer(), LI, llvm::MIPatternMatch::m_GAnyExt(), llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::RegisterImmPair::Reg, and VT.
matchCombineShuffleConcat()
bool CombinerHelper::matchCombineShuffleConcat (MachineInstr & MI, SmallVector< Register > & Ops) const
Definition at line 436 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::dyn_cast(), llvm::LLT::getNumElements(), isLegalOrBeforeLegalizer(), MI, and MRI.
matchCombineShuffleToBuildVector()
bool CombinerHelper::matchCombineShuffleToBuildVector (MachineInstr & MI) const
Replace MI with a build_vector.
Definition at line 394 of file CombinerHelper.cpp.
References assert(), llvm::cast(), llvm::LLT::isVector(), MI, and MRI.
matchCombineShuffleVector()
bool CombinerHelper::matchCombineShuffleVector (MachineInstr & MI, SmallVectorImpl< Register > & Ops) const
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
Ops will contain the operands needed to produce the flattened concat_vectors.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 531 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), Builder, MI, and MRI.
Referenced by tryCombineShuffleVector().
matchCombineSubToAdd()
bool CombinerHelper::matchCombineSubToAdd (MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 2103 of file CombinerHelper.cpp.
References B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GenericMachineInstr::getReg(), llvm::GBinOp::getRHSReg(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), MI, MRI, llvm::MachineInstr::NoSWrap, llvm::MachineInstr::NoUWrap, and Observer.
matchCombineTruncOfShift()
bool CombinerHelper::matchCombineTruncOfShift (MachineInstr & MI, std::pair< MachineInstr *, LLT > & MatchInfo) const
Transform trunc (shl x, K) to shl (trunc x), K if K < VT.getScalarSizeInBits().
Transforms trunc ([al]shr x, K) to (trunc ([al]shr (MidVT (trunc x)), K)) if K <= (MidVT.getScalarSizeInBits() - VT.getScalarSizeInBits()) MidVT is obtained by finding a legal type between the trunc's src and dst types.
Definition at line 2656 of file CombinerHelper.cpp.
References assert(), llvm::getDefIgnoringCopies(), llvm::KnownBits::getMaxValue(), getMidVTForTruncRightShiftCombine(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), getTargetLowering(), isLegalOrBeforeLegalizer(), MI, MRI, llvm::APInt::uge(), llvm::APInt::ugt(), and VT.
matchCombineUnmergeConstant()
bool CombinerHelper::matchCombineUnmergeConstant (MachineInstr & MI, SmallVectorImpl< APInt > & Csts) const
Transform G_UNMERGE Constant -> Constant1, Constant2, ...
Definition at line 2266 of file CombinerHelper.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachineOperand::getCImm(), llvm::MachineOperand::getFPImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::LLT::getSizeInBits(), llvm::ConstantInt::getValue(), llvm::ConstantFP::getValueAPF(), llvm::APInt::lshr(), MI, MRI, and llvm::APInt::trunc().
matchCombineUnmergeMergeToPlainValues()
bool CombinerHelper::matchCombineUnmergeMergeToPlainValues (MachineInstr & MI, SmallVectorImpl< Register > & Operands) const
Transform <ty,...> G_UNMERGE(G_MERGE ty X, Y, Z) -> ty X, Y, Z.
Definition at line 2211 of file CombinerHelper.cpp.
References assert(), llvm::cast(), llvm::getOpcodeDef(), llvm::LLT::getSizeInBits(), MI, MRI, Operands, and peekThroughBitcast().
matchCombineUnmergeUndef()
bool CombinerHelper::matchCombineUnmergeUndef (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo) const
Transform G_UNMERGE G_IMPLICIT_DEF -> G_IMPLICIT_DEF, G_IMPLICIT_DEF, ...
Definition at line 2306 of file CombinerHelper.cpp.
References B(), llvm::isa(), MI, and MRI.
matchCombineUnmergeWithDeadLanesToTrunc()
bool CombinerHelper::matchCombineUnmergeWithDeadLanesToTrunc (MachineInstr & MI) const
Transform X, Y<dead> = G_UNMERGE Z -> X = G_TRUNC Z.
Definition at line 2321 of file CombinerHelper.cpp.
References assert(), MI, and MRI.
matchCombineUnmergeZExtToZExt()
bool CombinerHelper::matchCombineUnmergeZExtToZExt (MachineInstr & MI) const
Transform X, Y = G_UNMERGE(G_ZEXT(Z)) -> X = G_ZEXT(Z); Y = G_CONSTANT 0.
Definition at line 2344 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getSizeInBits(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineZextTrunc()
bool CombinerHelper::matchCombineZextTrunc (MachineInstr & MI, Register & Reg) const
Transform zext(trunc(x)) to x.
Definition at line 2623 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), llvm::LLT::getScalarSizeInBits(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), MRI, and VT.
matchCommuteConstantToRHS()
bool CombinerHelper::matchCommuteConstantToRHS (MachineInstr & MI) const
Match constant LHS ops that should be commuted.
Definition at line 6812 of file CombinerHelper.cpp.
References llvm::getIConstantVRegVal(), MI, and MRI.
matchCommuteFPConstantToRHS()
bool CombinerHelper::matchCommuteFPConstantToRHS (MachineInstr & MI) const
Match constant LHS FP ops that should be commuted.
Definition at line 6842 of file CombinerHelper.cpp.
References llvm::MIPatternMatch::m_GFCstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCommuteShift()
bool CombinerHelper::matchCommuteShift (MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 2041 of file CombinerHelper.cpp.
References assert(), B(), llvm::cast(), getTargetLowering(), isPreLegalize(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, S1, and X.
matchConstantFoldBinOp()
bool CombinerHelper::matchConstantFoldBinOp (MachineInstr & MI, APInt & MatchInfo) const
Do constant folding when opportunities are exposed after MIR building.
Definition at line 5048 of file CombinerHelper.cpp.
References llvm::ConstantFoldBinOp(), MI, and MRI.
matchConstantFoldCastOp()
bool CombinerHelper::matchConstantFoldCastOp (MachineInstr & MI, APInt & MatchInfo) const
Do constant folding when opportunities are exposed after MIR building.
Definition at line 5035 of file CombinerHelper.cpp.
References llvm::ConstantFoldCastOp(), MI, and MRI.
matchConstantFoldFMA()
bool CombinerHelper::matchConstantFoldFMA (MachineInstr & MI, ConstantFP *& MatchInfo) const
Constant fold G_FMA/G_FMAD.
Definition at line 5071 of file CombinerHelper.cpp.
References _, assert(), llvm::APFloat::fusedMultiplyAdd(), llvm::getConstantFPVRegVal(), llvm::ConstantFP::getValueAPF(), MI, MRI, and llvm::APFloatBase::rmNearestTiesToEven.
matchConstantFoldFPBinOp()
bool CombinerHelper::matchConstantFoldFPBinOp (MachineInstr & MI, ConstantFP *& MatchInfo) const
Do constant FP folding when opportunities are exposed after MIR building.
Definition at line 5059 of file CombinerHelper.cpp.
References llvm::ConstantFoldFPBinOp(), MI, and MRI.
matchConstantFPOp()
bool CombinerHelper::matchConstantFPOp (const MachineOperand & MOP, double C) const
Return true if MOP is defined by a G_FCONSTANT or splat with a value exactly equal to C.
Definition at line 2911 of file CombinerHelper.cpp.
References llvm::CallingConv::C, llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::MIPatternMatch::m_GFCstOrSplat(), llvm::MIPatternMatch::mi_match(), and MRI.
matchConstantLargerBitWidth()
bool CombinerHelper::matchConstantLargerBitWidth (MachineInstr & MI, unsigned ConstIdx) const
Checks if constant at ConstIdx is larger than MI 's bitwidth.
Parameters
ConstIdx Index of the constant
Definition at line 2941 of file CombinerHelper.cpp.
References llvm::getIConstantVRegValWithLookThrough(), llvm::LLT::getSizeInBits(), MI, and MRI.
matchConstantOp()
bool CombinerHelper::matchConstantOp (const MachineOperand & MOP, int64_t C) const
Return true if MOP is defined by a G_CONSTANT or splat with a value equal to C.
Definition at line 2901 of file CombinerHelper.cpp.
References llvm::CallingConv::C, llvm::MachineOperand::getReg(), llvm::isConstantOrConstantSplatVector(), llvm::MachineOperand::isReg(), MI, and MRI.
Referenced by matchOperandIsZero().
matchConstantSelectCmp()
bool CombinerHelper::matchConstantSelectCmp (MachineInstr & MI, unsigned & OpIdx) const
Return true if a G_SELECT instruction MI has a constant comparison.
If true, OpIdx will store the operand index of the known selected value.
Definition at line 2791 of file CombinerHelper.cpp.
References llvm::cast(), llvm::GSelect::getCondReg(), llvm::isConstantOrConstantSplatVector(), MI, MRI, and OpIdx.
matchDivByPow2()
bool CombinerHelper::matchDivByPow2 (MachineInstr & MI, bool IsSigned) const
Given an G_SDIV MI expressing a signed divided by a pow2 constant, return expressions that implements it by shifting.
Definition at line 5711 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::matchUnaryPredicate(), MI, and MRI.
matchEqualDefs()
bool CombinerHelper::matchEqualDefs (const MachineOperand & MOP1, const MachineOperand & MOP2) const
Return true if MOP1 and MOP2 are register operands are defined by equivalent instructions.
Definition at line 2804 of file CombinerHelper.cpp.
References llvm::any_of(), Builder, llvm::dyn_cast(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::getDefSrcRegIgnoringCopies(), llvm::GMemOperation::getMemSizeInBits(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isDereferenceableInvariantLoad(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoadOrStore(), and MRI.
Referenced by matchBinOpSameVal(), matchCombineDivRem(), matchHoistLogicOpWithSameOpcodeHands(), and matchSelectSameVal().
matchExtendThroughPhis()
bool CombinerHelper::matchExtendThroughPhis (MachineInstr & MI, MachineInstr *& ExtMI) const
Definition at line 4173 of file CombinerHelper.cpp.
References Builder, llvm::cast(), DefMI, llvm::getDefIgnoringCopies(), llvm::MachineInstr::getOpcode(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), MI, MRI, PHI, and llvm::SmallPtrSetImplBase::size().
matchExtOfExt()
bool CombinerHelper::matchExtOfExt (const MachineInstr & FirstMI, const MachineInstr & SecondMI, BuildFnTy & MatchInfo) const
Definition at line 232 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), llvm::First, llvm::MachineInstr::getFlag(), llvm::MachineInstr::getOpcode(), llvm::GenericMachineInstr::getReg(), llvm::GCastOp::getSrcReg(), isLegalOrBeforeLegalizer(), MRI, llvm::MachineInstr::NoFlags, and llvm::MachineInstr::NonNeg.
matchExtractAllEltsFromBuildVector()
bool CombinerHelper::matchExtractAllEltsFromBuildVector (MachineInstr & MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > & MatchInfo) const
Definition at line 4325 of file CombinerHelper.cpp.
References llvm::SmallBitVector::all(), assert(), llvm::getIConstantVRegVal(), llvm::LLT::getNumElements(), II, MI, MRI, and llvm::SmallBitVector::set().
matchExtractVecEltBuildVec()
bool CombinerHelper::matchExtractVecEltBuildVec (MachineInstr & MI, Register & Reg) const
Definition at line 4272 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), llvm::getMVTForLLT(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), MI, and MRI.
matchExtractVectorElement()
bool CombinerHelper::matchExtractVectorElement (MachineInstr & MI, BuildFnTy & MatchInfo) const
Combine extract vector element.
Definition at line 33 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::LLT::getNumElements(), llvm::GenericMachineInstr::getReg(), llvm::GExtractVectorElement::getVectorReg(), llvm::LLT::isFixedVector(), isLegalOrBeforeLegalizer(), MI, MRI, and llvm::Vector.
matchExtractVectorElementWithBuildVector()
bool CombinerHelper::matchExtractVectorElementWithBuildVector (const MachineInstr & MI, const MachineInstr & MI2, BuildFnTy & MatchInfo) const
Combine extract vector element with a build vector on the vector register.
Definition at line 148 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GExtractVectorElement::getIndexReg(), llvm::getMVTForLLT(), llvm::GenericMachineInstr::getReg(), llvm::GMergeLikeInstr::getSourceReg(), getTargetLowering(), llvm::GExtractVectorElement::getVectorReg(), MI, MRI, and llvm::Vector.
matchExtractVectorElementWithBuildVectorTrunc()
bool CombinerHelper::matchExtractVectorElementWithBuildVectorTrunc (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Combine extract vector element with a build vector trunc on the vector register.
Definition at line 188 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::getMVTForLLT(), llvm::getOpcodeDef(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GMergeLikeInstr::getSourceReg(), getTargetLowering(), llvm::GExtractVectorElement::getVectorReg(), isLegalOrBeforeLegalizer(), MRI, and llvm::Vector.
matchExtractVectorElementWithDifferentIndices()
bool CombinerHelper::matchExtractVectorElementWithDifferentIndices (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Combine extract vector element with a insert vector element on the vector register and different indices.
Definition at line 91 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::getOpcodeDef(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GExtractVectorElement::getVectorReg(), MRI, and llvm::Vector.
matchExtractVectorElementWithShuffleVector()
bool CombinerHelper::matchExtractVectorElementWithShuffleVector (const MachineInstr & MI, const MachineInstr & MI2, BuildFnTy & MatchInfo) const
Combine extract vector element with a shuffle vector on the vector register.
Definition at line 255 of file CombinerHelperVectorOps.cpp.
References assert(), B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GExtractVectorElement::getIndexReg(), llvm::GShuffleVector::getMask(), llvm::LLT::getNumElements(), llvm::GenericMachineInstr::getReg(), llvm::GShuffleVector::getSrc1Reg(), llvm::GShuffleVector::getSrc2Reg(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), llvm::LLT::isVector(), MI, MRI, and llvm::Offset.
matchFoldAMinusC1MinusC2()
bool CombinerHelper::matchFoldAMinusC1MinusC2 (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 7847 of file CombinerHelper.cpp.
References B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GBinOp::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::GBinOp::getRHSReg(), MI, and MRI.
matchFoldAMinusC1PlusC2()
bool CombinerHelper::matchFoldAMinusC1PlusC2 (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 7893 of file CombinerHelper.cpp.
References llvm::Add, B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GBinOp::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::GBinOp::getRHSReg(), MI, and MRI.
matchFoldAPlusC1MinusC2()
bool CombinerHelper::matchFoldAPlusC1MinusC2 (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 7801 of file CombinerHelper.cpp.
References llvm::Add, B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GBinOp::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::GBinOp::getRHSReg(), MI, and MRI.
matchFoldBinOpIntoSelect()
bool CombinerHelper::matchFoldBinOpIntoSelect (MachineInstr & MI, unsigned & SelectOpNo) const
Push a binary operator through a select on constants.
binop (select cond, K0, K1), K2 -> select cond, (binop K0, K2), (binop K1, K2)
Definition at line 3736 of file CombinerHelper.cpp.
References llvm::isAllOnesOrAllOnesSplat(), llvm::isConstantOrConstantVector(), llvm::isNullOrNullSplat(), MI, MRI, and Select.
matchFoldC1Minus2MinusC2()
bool CombinerHelper::matchFoldC1Minus2MinusC2 (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 7870 of file CombinerHelper.cpp.
References B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GBinOp::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::GBinOp::getRHSReg(), MI, and MRI.
matchFoldC2MinusAPlusC1()
bool CombinerHelper::matchFoldC2MinusAPlusC1 (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 7824 of file CombinerHelper.cpp.
References llvm::Add, B(), llvm::cast(), llvm::getIConstantFromReg(), llvm::GBinOp::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::GBinOp::getRHSReg(), MI, and MRI.
matchFPowIExpansion()
bool CombinerHelper::matchFPowIExpansion (MachineInstr & MI, int64_t Exponent) const
Match FPOWI if it's safe to extend it into a series of multiplications.
Definition at line 7751 of file CombinerHelper.cpp.
References llvm::Exponent, getTargetLowering(), llvm::TargetLoweringBase::isBeneficialToExpandPowI(), and MI.
matchFreezeOfSingleMaybePoisonOperand()
bool CombinerHelper::matchFreezeOfSingleMaybePoisonOperand (MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 244 of file CombinerHelper.cpp.
References B(), llvm::canCreateUndefOrPoison(), llvm::cast(), llvm::MachineInstr::findRegisterUseOperand(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::isa(), llvm::isGuaranteedNotToBeUndefOrPoison(), llvm::MachineInstr::isPHI(), MI, MRI, Observer, replaceRegOpWith(), replaceRegWith(), TRI, and llvm::MachineInstr::uses().
matchFsubToFneg()
bool CombinerHelper::matchFsubToFneg (MachineInstr & MI, Register & MatchInfo) const
Definition at line 5880 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::FmNsz, llvm::getFConstantSplat(), llvm::getFConstantVRegValWithLookThrough(), MI, and MRI.
matchFunnelShiftToRotate()
bool CombinerHelper::matchFunnelShiftToRotate (MachineInstr & MI) const
Match an FSHL or FSHR that can be combined to a ROTR or ROTL rotate.
Definition at line 4446 of file CombinerHelper.cpp.
References assert(), isLegalOrBeforeLegalizer(), MI, MRI, Opc, X, and Y.
matchHoistLogicOpWithSameOpcodeHands()
bool CombinerHelper::matchHoistLogicOpWithSameOpcodeHands (MachineInstr & MI, InstructionStepsMatchInfo & MatchInfo) const
Match (logic_op (op x...), (op y...)) -> (op (logic_op x, y))
Definition at line 3139 of file CombinerHelper.cpp.
References assert(), llvm::Function::getContext(), llvm::getDefIgnoringCopies(), llvm::MachineFunction::getFunction(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), isLegalOrBeforeLegalizer(), llvm::MachineOperand::isReg(), llvm::TargetLoweringBase::isTruncateFree(), llvm::LLT::isValid(), llvm::Register::isValid(), llvm::TargetLoweringBase::isZExtFree(), matchEqualDefs(), MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), X, and Y.
matchICmpToLHSKnownBits()
bool CombinerHelper::matchICmpToLHSKnownBits (MachineInstr & MI, BuildFnTy & MatchInfo) const
Returns
true if a G_ICMP MI can be replaced with its LHS based off of KnownBits information.
Definition at line 4543 of file CombinerHelper.cpp.
References assert(), B(), llvm::getICmpTrueVal(), llvm::LLT::getSizeInBits(), getTargetLowering(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::isEquality(), isLegalOrBeforeLegalizer(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_SpecificICst(), MI, llvm::MIPatternMatch::mi_match(), MRI, and VT.
matchICmpToTrueFalseKnownBits()
bool CombinerHelper::matchICmpToTrueFalseKnownBits (MachineInstr & MI, int64_t & MatchInfo) const
Returns
true if a G_ICMP instruction MI can be replaced with a true or false constant based off of KnownBits information.
Definition at line 4499 of file CombinerHelper.cpp.
References assert(), llvm::ICmpInst::compare(), llvm::getICmpTrueVal(), getTargetLowering(), llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, MI, MRI, and VT.
matchInsertExtractVecEltOutOfBounds()
bool CombinerHelper::matchInsertExtractVecEltOutOfBounds (MachineInstr & MI) const
Return true if a G_{EXTRACT,INSERT}_VECTOR_ELT has an out of range index.
Definition at line 2774 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegVal(), llvm::LLT::getNumElements(), llvm::LLT::isScalableVector(), MI, and MRI.
matchInsertVectorElementOOB()
bool CombinerHelper::matchInsertVectorElementOOB (MachineInstr & MI, BuildFnTy & MatchInfo) const
Combine insert vector element OOB.
Definition at line 342 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::getIConstantVRegValWithLookThrough(), llvm::LLT::getNumElements(), llvm::LLT::isFixedVector(), isLegalOrBeforeLegalizer(), MI, and MRI.
matchLoadOrCombine()
bool CombinerHelper::matchLoadOrCombine (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match expression trees of the form.
sN *a = ...
sM val = a[0] | (a[1] << N) | (a[2] << 2N) | (a[3] << 3N) ...
And check if the tree can be replaced with a M-bit load + possibly a bswap.
Definition at line 4059 of file CombinerHelper.cpp.
References assert(), bigEndianByteAt(), llvm::CallingConv::C, DL, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::CallingConv::Fast, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Function::getContext(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::GMemOperation::getMMO(), llvm::MachineMemOperand::getPointerInfo(), llvm::GLoadStore::getPointerReg(), getTargetLowering(), isBigEndian(), llvm::DataLayout::isBigEndian(), isLegalOrBeforeLegalizer(), littleEndianByteAt(), llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, and Ptr.
matchMergeXAndUndef()
bool CombinerHelper::matchMergeXAndUndef (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 30 of file CombinerHelperArtifacts.cpp.
References assert(), B(), llvm::cast(), isLegalOrBeforeLegalizer(), Merge, MI, and MRI.
matchMergeXAndZero()
bool CombinerHelper::matchMergeXAndZero (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 59 of file CombinerHelperArtifacts.cpp.
References B(), llvm::cast(), isLegalOrBeforeLegalizer(), Merge, MI, and MRI.
matchMulOBy0()
bool CombinerHelper::matchMulOBy0 (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match: (G_*MULO x, 0) -> 0 + no carry out.
Definition at line 5206 of file CombinerHelper.cpp.
References assert(), B(), isConstantLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchMulOBy2()
bool CombinerHelper::matchMulOBy2 (MachineInstr & MI, BuildFnTy & MatchInfo) const
Match: (G_UMULO x, 2) -> (G_UADDO x, x) (G_SMULO x, 2) -> (G_SADDO x, x)
Definition at line 5187 of file CombinerHelper.cpp.
References assert(), B(), Builder, llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), MRI, Observer, and Opc.
matchMulOfVScale()
bool CombinerHelper::matchMulOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Definition at line 384 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::getIConstantVRegVal(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GVScale::getSrc(), MRI, and llvm::Mul.
matchNarrowBinop()
bool CombinerHelper::matchNarrowBinop (const MachineInstr & TruncMI, const MachineInstr & BinopMI, BuildFnTy & MatchInfo) const
trunc (binop X, C) --> binop (trunc X, trunc C).
Definition at line 336 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), llvm::GBinOp::getLHSReg(), llvm::MachineInstr::getOpcode(), llvm::GenericMachineInstr::getReg(), llvm::GBinOp::getRHSReg(), isLegalOrBeforeLegalizer(), and MRI.
matchNarrowBinopFeedingAnd()
bool CombinerHelper::matchNarrowBinopFeedingAnd (MachineInstr & MI, BuildFnTy & MatchInfo) const
Returns
true if it is possible to narrow the width of a scalar binop feeding a G_AND instruction MI.
Definition at line 5096 of file CombinerHelper.cpp.
References assert(), B(), Builder, llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), getTargetLowering(), isLegalOrBeforeLegalizer(), llvm::LLT::isScalar(), MI, MRI, Observer, and llvm::LLT::scalar().
matchNonNegZext()
bool CombinerHelper::matchNonNegZext (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Combine zext nneg to sext.
Definition at line 116 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), llvm::getMVTForLLT(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GCastOp::getSrcReg(), getTargetLowering(), isLegalOrBeforeLegalizer(), and MRI.
matchNotCmp()
bool CombinerHelper::matchNotCmp (MachineInstr & MI, SmallVectorImpl< Register > & RegsToNegate) const
Combine inverting a result of a compare into the opposite cond code.
Definition at line 3544 of file CombinerHelper.cpp.
References assert(), Builder, llvm::getIConstantSplatSExtVal(), I, isConstValidTrue(), llvm::MIPatternMatch::m_GXor(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
matchOperandIsKnownToBeAPowerOfTwo()
bool CombinerHelper::matchOperandIsKnownToBeAPowerOfTwo (MachineInstr & MI, unsigned OpIdx) const
Check if operand OpIdx is known to be a power of 2.
Definition at line 3007 of file CombinerHelper.cpp.
References llvm::MachineOperand::getReg(), llvm::isKnownToBeAPowerOfTwo(), MI, MRI, OpIdx, and VT.
matchOperandIsUndef()
bool CombinerHelper::matchOperandIsUndef (MachineInstr & MI, unsigned OpIdx) const
Check if operand OpIdx is undef.
Definition at line 3000 of file CombinerHelper.cpp.
References llvm::getOpcodeDef(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), MI, MRI, and OpIdx.
matchOperandIsZero()
bool CombinerHelper::matchOperandIsZero (MachineInstr & MI, unsigned OpIdx) const
Check if operand OpIdx is zero.
Definition at line 2993 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), matchConstantOp(), MI, MRI, and OpIdx.
matchOptBrCondByInvertingCond()
bool CombinerHelper::matchOptBrCondByInvertingCond (MachineInstr & MI, MachineInstr *& BrCond) const
If a brcond's true block is not the fallthrough, make it so by inverting the condition and swapping operands.
Definition at line 1640 of file CombinerHelper.cpp.
References assert(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), MBB, and MI.
matchOr()
bool CombinerHelper::matchOr (MachineInstr & MI, BuildFnTy & MatchInfo) const
Combine ors.
Definition at line 7564 of file CombinerHelper.cpp.
References llvm::cast(), and MI.
matchOrShiftToFunnelShift()
bool CombinerHelper::matchOrShiftToFunnelShift (MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 4392 of file CombinerHelper.cpp.
References assert(), B(), llvm::BitWidth, isLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchOverlappingAnd()
bool CombinerHelper::matchOverlappingAnd (MachineInstr & MI, BuildFnTy & MatchInfo) const
Fold and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0.
and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0
Definition at line 3291 of file CombinerHelper.cpp.
References assert(), B(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and replaceRegWith().
matchPtrAddImmedChain()
bool CombinerHelper::matchPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo) const
Definition at line 1769 of file CombinerHelper.cpp.
References llvm::PtrAddChain::Bank, llvm::PtrAddChain::Base, llvm::sampleprof::Base, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::dyn_cast(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), getRegBank(), llvm::APInt::getSExtValue(), llvm::getTypeForLLT(), llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::PtrAddChain::Imm, MI, MRI, and UseMI.
matchPtrAddZero()
bool CombinerHelper::matchPtrAddZero (MachineInstr & MI) const
}
Combine G_PTR_ADD with nullptr to G_INTTOPTR
Definition at line 3697 of file CombinerHelper.cpp.
References assert(), Builder, llvm::cast(), DL, llvm::getIConstantVRegVal(), llvm::isBuildVectorAllZeros(), MI, and MRI.
matchReassocCommBinOp()
bool CombinerHelper::matchReassocCommBinOp (MachineInstr & MI, BuildFnTy & MatchInfo) const
Reassociate commutative binary operations like G_ADD.
Definition at line 5019 of file CombinerHelper.cpp.
References MI, Opc, and tryReassocBinOp().
matchReassocConstantInnerLHS()
bool CombinerHelper::matchReassocConstantInnerLHS (GPtrAdd & MI, MachineInstr * LHS, MachineInstr * RHS, BuildFnTy & MatchInfo) const
Definition at line 4887 of file CombinerHelper.cpp.
References B(), llvm::cast(), llvm::MIPatternMatch::m_GCst(), llvm::MIPatternMatch::m_GPtrAdd(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Observer.
Referenced by matchReassocPtrAdd().
matchReassocConstantInnerRHS()
bool CombinerHelper::matchReassocConstantInnerRHS (GPtrAdd & MI, MachineInstr * RHS, BuildFnTy & MatchInfo) const
Definition at line 4863 of file CombinerHelper.cpp.
References B(), Builder, llvm::getIConstantVRegVal(), MI, MRI, and Observer.
Referenced by matchReassocPtrAdd().
matchReassocFoldConstantsInSubTree()
bool CombinerHelper::matchReassocFoldConstantsInSubTree (GPtrAdd & MI, MachineInstr * LHS, MachineInstr * RHS, BuildFnTy & MatchInfo) const
Definition at line 4918 of file CombinerHelper.cpp.
References B(), llvm::dyn_cast(), llvm::getIConstantVRegVal(), MI, MRI, and Observer.
Referenced by matchReassocPtrAdd().
matchReassocPtrAdd()
bool CombinerHelper::matchReassocPtrAdd (MachineInstr & MI, BuildFnTy & MatchInfo) const
Reassociate pointer calculations with G_ADD involved, to allow better addressing mode usage.
Definition at line 4946 of file CombinerHelper.cpp.
References llvm::cast(), matchReassocConstantInnerLHS(), matchReassocConstantInnerRHS(), matchReassocFoldConstantsInSubTree(), MI, and MRI.
matchRedundantAnd()
bool CombinerHelper::matchRedundantAnd (MachineInstr & MI, Register & Replacement) const
Returns
true if MI is a G_AND instruction whose operands are x and y where x & y == x or x & y == y. (E.g., one of operands is all-ones value.)
Parameters
[in] MI - The G_AND instruction.
[out] Replacement - A register the G_AND should be replaced with on success.
Definition at line 3318 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), llvm::KnownBits::isUnknown(), MI, MRI, llvm::KnownBits::One, VT, and llvm::KnownBits::Zero.
matchRedundantBinOpInEquality()
bool CombinerHelper::matchRedundantBinOpInEquality (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform: (X + Y) == X -> Y == 0 (X - Y) == X -> Y == 0 (X ^ Y) == X -> Y == 0 (X + Y) != X -> Y != 0 (X - Y) != X -> Y != 0 (X ^ Y) != X -> Y != 0.
Definition at line 6724 of file CombinerHelper.cpp.
References assert(), B(), llvm::CmpInst::isEquality(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_c_GICmp(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_GXor(), llvm::MIPatternMatch::m_Pred(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, Register, X, and Y.
matchRedundantNegOperands()
bool CombinerHelper::matchRedundantNegOperands (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform (fadd x, fneg(y)) -> (fsub x, y) (fadd fneg(x), y) -> (fsub y, x) (fsub x, fneg(y)) -> (fadd x, y) (fmul fneg(x), fneg(y)) -> (fmul x, y) (fdiv fneg(x), fneg(y)) -> (fdiv x, y) (fmad fneg(x), fneg(y), z) -> (fmad x, y, z) (fma fneg(x), fneg(y), z) -> (fma x, y, z)
fold (fsub x, fneg(y)) -> (fadd x, y)
Definition at line 5834 of file CombinerHelper.cpp.
References assert(), B(), isLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_GFAdd(), llvm::MIPatternMatch::m_GFNeg(), llvm::MIPatternMatch::m_GFSub(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, Observer, Opc, X, and Y.
matchRedundantOr()
bool CombinerHelper::matchRedundantOr (MachineInstr & MI, Register & Replacement) const
Returns
true if MI is a G_OR instruction whose operands are x and y where x | y == x or x | y == y. (E.g., one of operands is all-zeros value.)
Parameters
[in] MI - The G_OR instruction.
[out] Replacement - A register the G_OR should be replaced with on success.
Definition at line 3374 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), MI, MRI, llvm::KnownBits::One, VT, and llvm::KnownBits::Zero.
matchRedundantSExtInReg()
bool CombinerHelper::matchRedundantSExtInReg (MachineInstr & MI) const
Returns
true if MI is a G_SEXT_INREG that can be erased.
Definition at line 3416 of file CombinerHelper.cpp.
References MI, MRI, and VT.
matchRedundantSextInReg()
bool CombinerHelper::matchRedundantSextInReg (MachineInstr & Root, MachineInstr & Other, BuildFnTy & MatchInfo) const
Definition at line 382 of file CombinerHelperCasts.cpp.
References assert(), B(), llvm::canReplaceReg(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), MRI, Observer, and llvm::Other.
matchRotateOutOfRange()
bool CombinerHelper::matchRotateOutOfRange (MachineInstr & MI) const
Definition at line 4470 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::matchUnaryPredicate(), MI, and MRI.
matchSDivByConst()
bool CombinerHelper::matchSDivByConst (MachineInstr & MI) const
Combine G_SDIV by constant into a multiply by magic constant.
Definition at line 5525 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::LLT::changeElementSize(), llvm::getApproximateEVTForLLT(), llvm::LLT::getScalarSizeInBits(), getTargetLowering(), llvm::isConstantOrConstantVector(), llvm::MachineInstr::IsExact, isLegal(), isLegalOrBeforeLegalizer(), isLegalOrHasWidenScalar(), LI, llvm::matchUnaryPredicate(), MI, and MRI.
matchSelect()
bool CombinerHelper::matchSelect (MachineInstr & MI, BuildFnTy & MatchInfo) const
Combine selects.
Definition at line 7302 of file CombinerHelper.cpp.
References llvm::cast(), MI, and Select.
matchSelectIMinMax()
bool CombinerHelper::matchSelectIMinMax (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Combine select to integer min/max.
Definition at line 7202 of file CombinerHelper.cpp.
References B(), llvm::cast(), llvm::MachineOperand::getReg(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::CmpInst::isEquality(), isLegalOrBeforeLegalizer(), llvm::LLT::isPointer(), MRI, Select, and std::swap().
matchSelectSameVal()
bool CombinerHelper::matchSelectSameVal (MachineInstr & MI) const
Optimize (cond ? x : x) -> x.
Definition at line 2979 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), matchEqualDefs(), MI, and MRI.
matchSextInRegOfLoad()
bool CombinerHelper::matchSextInRegOfLoad (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo) const
Match sext_inreg(load p), imm -> sextload p.
Definition at line 1094 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), llvm::LLT::getSizeInBits(), isLegalOrBeforeLegalizer(), llvm::isPowerOf2_32(), llvm::LLT::isVector(), llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, and llvm::LLT::scalar().
matchSextOfTrunc()
bool CombinerHelper::matchSextOfTrunc (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Combine sext of trunc.
Definition at line 28 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), llvm::getDefIgnoringCopies(), llvm::MachineInstr::getFlag(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::GCastOp::getSrcReg(), isLegalOrBeforeLegalizer(), MRI, and llvm::MachineInstr::NoSWrap.
matchSextTruncSextLoad()
bool CombinerHelper::matchSextTruncSextLoad (MachineInstr & MI) const
Definition at line 1061 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchShiftImmedChain()
bool CombinerHelper::matchShiftImmedChain (MachineInstr & MI, RegisterImmPair & MatchInfo) const
Fold (shift (shift base, x), y) -> (shift base (x+y))
Definition at line 1844 of file CombinerHelper.cpp.
References assert(), llvm::sampleprof::Base, llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::RegisterImmPair::Imm, MI, MRI, and llvm::RegisterImmPair::Reg.
matchShiftOfShiftedLogic()
bool CombinerHelper::matchShiftOfShiftedLogic (MachineInstr & MI, ShiftOfShiftedLogic & MatchInfo) const
If we have a shift-by-constant of a bitwise logic op that itself has a shift-by-constant operand with identical opcode, we may be able to convert that into 2 independent shifts followed by the logic op.
Definition at line 1921 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ShiftOfShiftedLogic::Logic, llvm::ShiftOfShiftedLogic::LogicNonShiftReg, MI, MRI, llvm::ShiftOfShiftedLogic::Shift2, and llvm::ShiftOfShiftedLogic::ValSum.
matchShiftsTooBig()
bool CombinerHelper::matchShiftsTooBig (MachineInstr & MI, std::optional< int64_t > & MatchInfo) const
Match shifts greater or equal to the range (the bitwidth of the result datatype, or the effective bitwidth of the source value).
Definition at line 6792 of file CombinerHelper.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), getMinUselessShift(), llvm::LLT::getScalarSizeInBits(), llvm::matchUnaryPredicate(), MI, MRI, and VT.
matchShlOfVScale()
bool CombinerHelper::matchShlOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Definition at line 425 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::getIConstantVRegVal(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GShl::getShiftReg(), llvm::GVScale::getSrc(), llvm::GShl::getSrcReg(), isLegalOrBeforeLegalizer(), MRI, and llvm::APInt::shl().
matchShuffleDisjointMask()
bool CombinerHelper::matchShuffleDisjointMask (MachineInstr & MI, BuildFnTy & MatchInfo) const
Turn shuffle a, b, mask -> shuffle undef, b, mask iff mask does not reference a.
Definition at line 8042 of file CombinerHelper.cpp.
References B(), llvm::cast(), commuteMask(), llvm::getOpcodeDef(), isLegalOrBeforeLegalizer(), MI, and MRI.
matchShuffleToExtract()
bool CombinerHelper::matchShuffleToExtract (MachineInstr & MI) const
Definition at line 622 of file CombinerHelper.cpp.
References assert(), and MI.
matchShuffleUndefRHS()
bool CombinerHelper::matchShuffleUndefRHS (MachineInstr & MI, BuildFnTy & MatchInfo) const
Remove references to rhs if it is undef.
Definition at line 7998 of file CombinerHelper.cpp.
References B(), llvm::cast(), Changed, MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ArrayRef< T >::size().
matchSimplifyAddToSub()
bool CombinerHelper::matchSimplifyAddToSub (MachineInstr & MI, std::tuple< Register, Register > & MatchInfo) const
Return true if MI is a G_ADD which can be simplified to a G_SUB.
Definition at line 3046 of file CombinerHelper.cpp.
References llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchSimplifyNegMinMax()
bool CombinerHelper::matchSimplifyNegMinMax (MachineInstr & MI, BuildFnTy & MatchInfo) const
Tranform (neg (min/max x, (neg x))) into (max/min x, (neg x)).
Definition at line 7275 of file CombinerHelper.cpp.
References assert(), B(), llvm::getInverseGMinMaxOpcode(), llvm::MachineInstr::getOpcode(), isLegal(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_DeferredReg(), llvm::MIPatternMatch::m_GSMax(), llvm::MIPatternMatch::m_GSMin(), llvm::MIPatternMatch::m_GUMax(), llvm::MIPatternMatch::m_GUMin(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_OneUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and X.
matchSimplifySelectToMinMax()
bool CombinerHelper::matchSimplifySelectToMinMax (MachineInstr & MI, BuildFnTy & MatchInfo) const
Returns
true if it is possible to simplify a select instruction MI to a min/max instruction of some sort.
Definition at line 6709 of file CombinerHelper.cpp.
References assert(), Cond, llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchSubAddSameReg()
bool CombinerHelper::matchSubAddSameReg (MachineInstr & MI, BuildFnTy & MatchInfo) const
Transform: (x + y) - y -> x (x + y) - x -> y x - (y + x) -> 0 - y x - (x + z) -> 0 - z.
Definition at line 5259 of file CombinerHelper.cpp.
References assert(), B(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), MRI, X, and Y.
matchSuboCarryOut()
bool CombinerHelper::matchSuboCarryOut (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 8094 of file CombinerHelper.cpp.
References llvm::ConstantRange::AlwaysOverflowsHigh, llvm::ConstantRange::AlwaysOverflowsLow, B(), llvm::cast(), llvm::ConstantRange::fromKnownBits(), llvm::GBinOpCarryOut::getCarryOutReg(), llvm::getICmpTrueVal(), llvm::GBinOpCarryOut::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::GBinOpCarryOut::getRHSReg(), getTargetLowering(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), llvm::GSubCarryOut::isSigned(), llvm::LLT::isVector(), llvm::ConstantRange::MayOverflow, MI, MRI, llvm::ConstantRange::NeverOverflows, llvm::MachineInstr::NoSWrap, llvm::MachineInstr::NoUWrap, llvm::ConstantRange::signedSubMayOverflow(), llvm::ConstantRange::unsignedSubMayOverflow(), and VT.
matchSubOfVScale()
bool CombinerHelper::matchSubOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Definition at line 405 of file CombinerHelperVectorOps.cpp.
References B(), llvm::cast(), llvm::MachineInstr::getFlags(), llvm::GBinOp::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GBinOp::getRHSReg(), llvm::GVScale::getSrc(), isLegalOrBeforeLegalizer(), and MRI.
matchTruncateOfExt()
bool CombinerHelper::matchTruncateOfExt (const MachineInstr & Root, const MachineInstr & ExtMI, BuildFnTy & MatchInfo) const
Transform trunc ([asz]ext x) to x or ([asz]ext x) or (trunc x).
Definition at line 137 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), llvm::GenericMachineInstr::getReg(), llvm::LLT::getScalarSizeInBits(), isLegalOrBeforeLegalizer(), and MRI.
matchTruncBuildVectorFold()
bool CombinerHelper::matchTruncBuildVectorFold (MachineInstr & MI, Register & MatchInfo) const
Definition at line 6567 of file CombinerHelper.cpp.
References llvm::MIPatternMatch::m_GBitcast(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchTruncLshrBuildVectorFold()
bool CombinerHelper::matchTruncLshrBuildVectorFold (MachineInstr & MI, Register & MatchInfo) const
Definition at line 6578 of file CombinerHelper.cpp.
References llvm::LLT::getSizeInBits(), llvm::MIPatternMatch::m_GBitcast(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_GCst(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchUDivorURemByConst()
bool CombinerHelper::matchUDivorURemByConst (MachineInstr & MI) const
Combine G_UDIV or G_UREM by constant into a multiply by magic constant.
Definition at line 5471 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::LLT::changeElementSize(), llvm::getApproximateEVTForLLT(), getTargetLowering(), llvm::isConstantOrConstantVector(), llvm::MachineInstr::IsExact, isLegalOrBeforeLegalizer(), llvm::LLT::isVector(), LI, llvm::matchUnaryPredicate(), MI, MRI, and llvm::LLT::scalar().
matchUMulHToLShr()
bool CombinerHelper::matchUMulHToLShr (MachineInstr & MI) const
Definition at line 5798 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), isLegalOrBeforeLegalizer(), llvm::matchUnaryPredicate(), MI, and MRI.
matchUndefSelectCmp()
bool CombinerHelper::matchUndefSelectCmp (MachineInstr & MI) const
Return true if a G_SELECT instruction MI has an undef comparison.
Definition at line 2768 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), MI, and MRI.
matchUndefShuffleVectorMask()
bool CombinerHelper::matchUndefShuffleVectorMask (MachineInstr & MI) const
Return true if a G_SHUFFLE_VECTOR instruction MI has an undef mask.
Definition at line 2756 of file CombinerHelper.cpp.
References llvm::all_of(), assert(), and MI.
matchUndefStore()
bool CombinerHelper::matchUndefStore (MachineInstr & MI) const
Return true if a G_STORE instruction MI is storing an undef value.
Definition at line 2762 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), MI, and MRI.
matchUnmergeValuesAnyExtBuildVector()
bool CombinerHelper::matchUnmergeValuesAnyExtBuildVector (const MachineInstr & MI, BuildFnTy & MatchInfo) const
Definition at line 7916 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, B(), llvm::cast(), llvm::dyn_cast(), llvm::LLT::getElementType(), llvm::GUnmerge::getNumDefs(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOperand(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GUnmerge::getSourceReg(), I, llvm::LLT::isFixedVector(), isLegalOrBeforeLegalizer(), MI, and MRI.
matchUseVectorTruncate()
bool CombinerHelper::matchUseVectorTruncate (MachineInstr & MI, Register & MatchInfo) const
Definition at line 3447 of file CombinerHelper.cpp.
References llvm::BuildMI(), llvm::cast(), llvm::LLT::changeElementType(), llvm::LLT::getElementCount(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarType(), I, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownMultipleOf(), isLegal(), IsPreLegalize, MI, and MRI.
matchXorOfAndWithSameReg()
bool CombinerHelper::matchXorOfAndWithSameReg (MachineInstr & MI, std::pair< Register, Register > & MatchInfo) const
Fold (xor (and x, y), y) -> (and (not x), y) {.
Definition at line 3653 of file CombinerHelper.cpp.
References assert(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, std::swap(), X, and Y.
matchZextOfTrunc()
bool CombinerHelper::matchZextOfTrunc (const MachineOperand & MO, BuildFnTy & MatchInfo) const
Combine zext of trunc.
Definition at line 81 of file CombinerHelperCasts.cpp.
References B(), llvm::cast(), llvm::getDefIgnoringCopies(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::GCastOp::getSrcReg(), isLegalOrBeforeLegalizer(), MRI, llvm::MachineInstr::NonNeg, and llvm::MachineInstr::NoUWrap.
replaceInstWithConstant() [1/2]
void CombinerHelper::replaceInstWithConstant (MachineInstr & MI, APInt C) const
Replace an instruction with a G_CONSTANT with value C.
Definition at line 3027 of file CombinerHelper.cpp.
References assert(), Builder, llvm::CallingConv::C, and MI.
replaceInstWithConstant() [2/2]
void CombinerHelper::replaceInstWithConstant (MachineInstr & MI, int64_t C) const
Replace an instruction with a G_CONSTANT with value C.
Definition at line 3020 of file CombinerHelper.cpp.
References assert(), Builder, llvm::CallingConv::C, and MI.
replaceInstWithFConstant() [1/2]
void CombinerHelper::replaceInstWithFConstant (MachineInstr & MI, ConstantFP * CFP) const
Replace an instruction with an G_FCONSTANT with value CFP.
Definition at line 3033 of file CombinerHelper.cpp.
References assert(), Builder, llvm::ConstantFP::getValueAPF(), and MI.
replaceInstWithFConstant() [2/2]
void CombinerHelper::replaceInstWithFConstant (MachineInstr & MI, double C) const
Replace an instruction with a G_FCONSTANT with value C.
Definition at line 3013 of file CombinerHelper.cpp.
References assert(), Builder, llvm::CallingConv::C, and MI.
replaceInstWithUndef()
void CombinerHelper::replaceInstWithUndef (MachineInstr & MI) const
Replace an instruction with a G_IMPLICIT_DEF.
Definition at line 3040 of file CombinerHelper.cpp.
References assert(), Builder, and MI.
replaceOpcodeWith()
void CombinerHelper::replaceOpcodeWith (MachineInstr & FromMI, unsigned ToOpcode) const
Replace the opcode in instruction with a new opcode and inform the observer of the changes.
Definition at line 204 of file CombinerHelper.cpp.
References Builder, Observer, and llvm::MachineInstr::setDesc().
Referenced by llvm::AMDGPUCombinerHelper::applyFoldableFneg().
replaceRegOpWith()
void CombinerHelper::replaceRegOpWith (MachineRegisterInfo & MRI, MachineOperand & FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
Definition at line 193 of file CombinerHelper.cpp.
References assert(), llvm::MachineOperand::getParent(), MRI, Observer, and llvm::MachineOperand::setReg().
Referenced by applyCombineExtendingLoads(), llvm::AMDGPUCombinerHelper::applyFoldableFneg(), and matchFreezeOfSingleMaybePoisonOperand().
replaceRegWith()
void CombinerHelper::replaceRegWith (MachineRegisterInfo & MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
Definition at line 181 of file CombinerHelper.cpp.
References Builder, MRI, and Observer.
Referenced by applyCombineConcatVectors(), applyCombineCopy(), applyCombineExtendingLoads(), applyCombineShuffleVector(), applyCombineTruncOfShift(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeZExtToZExt(), applyExtractAllEltsFromBuildVector(), llvm::AMDGPUCombinerHelper::applyFoldableFneg(), applyNotCmp(), matchFreezeOfSingleMaybePoisonOperand(), matchOverlappingAnd(), replaceSingleDefInstWithOperand(), and replaceSingleDefInstWithReg().
replaceSingleDefInstWithOperand()
void CombinerHelper::replaceSingleDefInstWithOperand (MachineInstr & MI, unsigned OpIdx) const
Delete MI and replace all of its uses with its OpIdx-th operand.
Definition at line 2922 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), MI, MRI, OpIdx, and replaceRegWith().
replaceSingleDefInstWithReg()
void CombinerHelper::replaceSingleDefInstWithReg (MachineInstr & MI, Register Replacement) const
Delete MI and replace all of its uses with Replacement.
Definition at line 2932 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), MI, MRI, and replaceRegWith().
Referenced by applyExtractVecEltBuildVec(), applySDivByConst(), and applyUDivorURemByConst().
setRegBank()
void CombinerHelper::setRegBank (Register Reg, const RegisterBank * RegBank) const
Set the register bank of Reg.
Does nothing if the RegBank is null. This is the counterpart to getRegBank.
Definition at line 217 of file CombinerHelper.cpp.
References MRI.
Referenced by applyPtrAddImmedChain().
tryCombine()
bool llvm::CombinerHelper::tryCombine (MachineInstr & MI) const
Try to transform MI by using all of the above combine functions.
Returns true if changed.
References llvm::Aggressive, llvm::sampleprof::Base, llvm::Exponent, Info, MI, llvm::Offset, and llvm::Other.
tryCombineCopy()
bool CombinerHelper::tryCombineCopy (MachineInstr & MI) const
If MI is COPY, try to combine it.
Returns true if MI changed.
Definition at line 223 of file CombinerHelper.cpp.
References applyCombineCopy(), matchCombineCopy(), and MI.
tryCombineExtendingLoads()
bool CombinerHelper::tryCombineExtendingLoads (MachineInstr & MI) const
If MI is extend that consumes the result of a load, try to combine it.
Returns true if MI changed.
Definition at line 743 of file CombinerHelper.cpp.
References applyCombineExtendingLoads(), matchCombineExtendingLoads(), and MI.
tryCombineMemCpyFamily()
bool CombinerHelper::tryCombineMemCpyFamily (MachineInstr & MI, unsigned MaxLen = 0) const
Optimize memcpy intrinsics et al, e.g.
constant len calls. /p MaxLen if non-zero specifies the max length of a mem libcall to inline.
For example (pre-indexed):
$addr = G_PTR_ADD $base, $offset
[...]
$val = G_LOAD $addr
[...]
$whatever = COPY $addr
-->
$val, $addr = G_INDEXED_LOAD $base, $offset, 1 (IsPre)
[...]
$whatever = COPY $addr
or (post-indexed):
G_STORE $val, $base
[...]
$addr = G_PTR_ADD $base, $offset
[...]
$whatever = COPY $addr
-->
$addr = G_INDEXED_STORE $val, $base, $offset
[...]
$whatever = COPY $addr
Definition at line 1707 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::getMF(), llvm::LegalizerHelper::Legalized, llvm::LegalizerHelper::lowerMemCpyFamily(), and MI.
tryCombineShiftToUnmerge()
bool CombinerHelper::tryCombineShiftToUnmerge (MachineInstr & MI, unsigned TargetShiftAmount) const
Definition at line 2499 of file CombinerHelper.cpp.
References applyCombineShiftToUnmerge(), matchCombineShiftToUnmerge(), and MI.
tryCombineShuffleVector()
bool CombinerHelper::tryCombineShuffleVector (MachineInstr & MI) const
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
Returns true if MI changed.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 522 of file CombinerHelper.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, applyCombineShuffleVector(), matchCombineShuffleVector(), and MI.
tryEmitMemcpyInline()
bool CombinerHelper::tryEmitMemcpyInline (MachineInstr & MI) const
Emit loads and stores that perform the given memcpy.
Assumes MI is a G_MEMCPY_INLINE TODO: implement dynamically sized inline memcpy, and rename: s/bool tryEmit/void emit/
Definition at line 1699 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::getMF(), llvm::LegalizerHelper::Legalized, and MI.
tryReassocBinOp()
bool CombinerHelper::tryReassocBinOp (unsigned Opc, Register DstReg, Register Op0, Register Op1, BuildFnTy & MatchInfo) const
Try to reassociate to reassociate operands of a commutative binop.
Definition at line 4978 of file CombinerHelper.cpp.
References B(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), llvm::isConstantOrConstantSplatVector(), MRI, and Opc.
Referenced by matchReassocCommBinOp().
Member Data Documentation
Builder
MachineIRBuilder& llvm::CombinerHelper::Builder protected
Definition at line 106 of file CombinerHelper.h.
Referenced by applyAshShlToSextInreg(), applyBuildFnMO(), applyBuildFnNoErase(), applyBuildInstructionSteps(), applyCombineAddP2IToPtrAdd(), applyCombineConcatVectors(), applyCombineConstantFoldFpUnary(), applyCombineConstPtrAddToI2P(), applyCombineDivRem(), applyCombineExtendingLoads(), applyCombineI2PToP2I(), applyCombineIndexedLoadStore(), applyCombineInsertVecElts(), applyCombineP2IToI2P(), applyCombineShiftToUnmerge(), applyCombineShlOfExtend(), applyCombineShuffleConcat(), applyCombineShuffleToBuildVector(), applyCombineShuffleVector(), applyCombineTruncOfShift(), applyCombineUnmergeConstant(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeWithDeadLanesToTrunc(), applyCombineUnmergeZExtToZExt(), applyExpandFPowI(), llvm::AMDGPUCombinerHelper::applyExpandPromotedF16FMed3(), applyExtendThroughPhis(), applyExtractVecEltBuildVec(), llvm::AMDGPUCombinerHelper::applyFoldableFneg(), applyFoldBinOpIntoSelect(), applyFsubToFneg(), applyFunnelShiftConstantModulo(), applyFunnelShiftToRotate(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddZero(), applyRotateOutOfRange(), applySDivByPow2(), applySextInRegOfLoad(), applySextTruncSextLoad(), applyShiftImmedChain(), applyShiftOfShiftedLogic(), applyShuffleToExtract(), applySimplifyAddToSub(), applySimplifyURemByPow2(), applyUDivByPow2(), applyUMulHToLShr(), applyUseVectorTruncate(), applyXorOfAndWithSameReg(), buildSDivUsingMul(), buildUDivorURemUsingMul(), CombinerHelper(), getBuilder(), getContext(), getMachineFunction(), getTargetLowering(), matchCombineConcatVectors(), matchCombineConstPtrAddToI2P(), llvm::AMDGPUCombinerHelper::matchCombineFmulWithSelectToFldexp(), matchCombineShuffleVector(), matchEqualDefs(), matchExtendThroughPhis(), matchMulOBy2(), matchNarrowBinopFeedingAnd(), matchNotCmp(), matchPtrAddZero(), matchReassocConstantInnerRHS(), replaceInstWithConstant(), replaceInstWithConstant(), replaceInstWithFConstant(), replaceInstWithFConstant(), replaceInstWithUndef(), replaceOpcodeWith(), and replaceRegWith().
IsPreLegalize
bool llvm::CombinerHelper::IsPreLegalize protected
Definition at line 111 of file CombinerHelper.h.
Referenced by llvm::AMDGPUCombinerHelper::AMDGPUCombinerHelper(), CombinerHelper(), isPreLegalize(), and matchUseVectorTruncate().
LI
const LegalizerInfo* llvm::CombinerHelper::LI protected
Definition at line 112 of file CombinerHelper.h.
Referenced by llvm::AMDGPUCombinerHelper::AMDGPUCombinerHelper(), CombinerHelper(), isLegal(), isLegalOrHasWidenScalar(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchBitfieldExtractFromShr(), matchBitfieldExtractFromShrAnd(), matchCombineExtendingLoads(), matchCombineShlOfExtend(), matchSDivByConst(), and matchUDivorURemByConst().
MDT
MachineDominatorTree* llvm::CombinerHelper::MDT protected
Definition at line 110 of file CombinerHelper.h.
Referenced by llvm::AMDGPUCombinerHelper::AMDGPUCombinerHelper(), CombinerHelper(), and dominates().
MRI
MachineRegisterInfo& llvm::CombinerHelper::MRI protected
Definition at line 107 of file CombinerHelper.h.
Referenced by applyAshShlToSextInreg(), applyBuildFnMO(), applyCombineAddP2IToPtrAdd(), applyCombineConcatVectors(), applyCombineConstantFoldFpUnary(), applyCombineCopy(), applyCombineExtendingLoads(), applyCombineIndexedLoadStore(), applyCombineInsertVecElts(), applyCombineMulToShl(), applyCombineShiftToUnmerge(), applyCombineShlOfExtend(), applyCombineShuffleConcat(), applyCombineShuffleToBuildVector(), applyCombineShuffleVector(), applyCombineTruncOfShift(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeZExtToZExt(), applyExpandFPowI(), llvm::AMDGPUCombinerHelper::applyExpandPromotedF16FMed3(), applyExtendThroughPhis(), applyExtractAllEltsFromBuildVector(), applyExtractVecEltBuildVec(), llvm::AMDGPUCombinerHelper::applyFoldableFneg(), applyFoldBinOpIntoSelect(), applyFsubToFneg(), applyFunnelShiftConstantModulo(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddImmedChain(), applyRotateOutOfRange(), applySDivByPow2(), applySextInRegOfLoad(), applyShiftImmedChain(), applyShiftOfShiftedLogic(), applyShuffleToExtract(), applySimplifyURemByPow2(), applyUDivByPow2(), applyUMulHToLShr(), applyUseVectorTruncate(), applyXorOfAndWithSameReg(), buildSDivUsingMul(), buildUDivorURemUsingMul(), canCombineFMadOrFMA(), CombinerHelper(), getRegBank(), matchAddEToAddO(), matchAddOfVScale(), matchAddOverflow(), matchAddSubSameReg(), matchAndOrDisjointMask(), matchAshrShlToSextInreg(), matchBinOpSameVal(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchBitfieldExtractFromShr(), matchBitfieldExtractFromShrAnd(), matchBuildVectorIdentityFold(), matchCanonicalizeFCmp(), matchCanonicalizeICmp(), matchCastOfBuildVector(), matchCastOfInteger(), matchCastOfSelect(), matchCombineAddP2IToPtrAdd(), matchCombineAnyExtTrunc(), matchCombineConcatVectors(), matchCombineConstPtrAddToI2P(), matchCombineCopy(), matchCombineDivRem(), matchCombineExtendingLoads(), matchCombineExtractedVectorLoad(), matchCombineFAddFMAFMulToFMadOrFMA(), matchCombineFAddFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), matchCombineFMinMaxNaN(), llvm::AMDGPUCombinerHelper::matchCombineFmulWithSelectToFldexp(), matchCombineFSubFMulToFMadOrFMA(), matchCombineFSubFNegFMulToFMadOrFMA(), matchCombineFSubFpExtFMulToFMadOrFMA(), matchCombineFSubFpExtFNegFMulToFMadOrFMA(), matchCombineI2PToP2I(), matchCombineInsertVecElts(), matchCombineLoadWithAndMask(), matchCombineMergeUnmerge(), matchCombineMulToShl(), matchCombineShiftToUnmerge(), matchCombineShlOfExtend(), matchCombineShuffleConcat(), matchCombineShuffleToBuildVector(), matchCombineShuffleVector(), matchCombineSubToAdd(), matchCombineTruncOfShift(), matchCombineUnmergeConstant(), matchCombineUnmergeMergeToPlainValues(), matchCombineUnmergeUndef(), matchCombineUnmergeWithDeadLanesToTrunc(), matchCombineUnmergeZExtToZExt(), matchCombineZextTrunc(), matchCommuteConstantToRHS(), matchCommuteFPConstantToRHS(), matchCommuteShift(), matchConstantFoldBinOp(), matchConstantFoldCastOp(), matchConstantFoldFMA(), matchConstantFoldFPBinOp(), matchConstantFPOp(), matchConstantLargerBitWidth(), matchConstantOp(), matchConstantSelectCmp(), matchDivByPow2(), matchEqualDefs(), llvm::AMDGPUCombinerHelper::matchExpandPromotedF16FMed3(), matchExtendThroughPhis(), matchExtOfExt(), matchExtractAllEltsFromBuildVector(), matchExtractVecEltBuildVec(), matchExtractVectorElement(), matchExtractVectorElementWithBuildVector(), matchExtractVectorElementWithBuildVectorTrunc(), matchExtractVectorElementWithDifferentIndices(), matchExtractVectorElementWithShuffleVector(), llvm::AMDGPUCombinerHelper::matchFoldableFneg(), matchFoldAMinusC1MinusC2(), matchFoldAMinusC1PlusC2(), matchFoldAPlusC1MinusC2(), matchFoldBinOpIntoSelect(), matchFoldC1Minus2MinusC2(), matchFoldC2MinusAPlusC1(), matchFreezeOfSingleMaybePoisonOperand(), matchFsubToFneg(), matchFunnelShiftToRotate(), matchHoistLogicOpWithSameOpcodeHands(), matchICmpToLHSKnownBits(), matchICmpToTrueFalseKnownBits(), matchInsertExtractVecEltOutOfBounds(), matchInsertVectorElementOOB(), matchLoadOrCombine(), matchMergeXAndUndef(), matchMergeXAndZero(), matchMulOBy0(), matchMulOBy2(), matchMulOfVScale(), matchNarrowBinop(), matchNarrowBinopFeedingAnd(), matchNonNegZext(), matchNotCmp(), matchOperandIsKnownToBeAPowerOfTwo(), matchOperandIsUndef(), matchOperandIsZero(), matchOrShiftToFunnelShift(), matchOverlappingAnd(), matchPtrAddImmedChain(), matchPtrAddZero(), matchReassocConstantInnerLHS(), matchReassocConstantInnerRHS(), matchReassocFoldConstantsInSubTree(), matchReassocPtrAdd(), matchRedundantAnd(), matchRedundantBinOpInEquality(), matchRedundantNegOperands(), matchRedundantOr(), matchRedundantSExtInReg(), matchRedundantSextInReg(), matchRotateOutOfRange(), matchSDivByConst(), matchSelectIMinMax(), matchSelectSameVal(), matchSextInRegOfLoad(), matchSextOfTrunc(), matchSextTruncSextLoad(), matchShiftImmedChain(), matchShiftOfShiftedLogic(), matchShiftsTooBig(), matchShlOfVScale(), matchShuffleDisjointMask(), matchShuffleUndefRHS(), matchSimplifyAddToSub(), matchSimplifyNegMinMax(), matchSimplifySelectToMinMax(), matchSubAddSameReg(), matchSuboCarryOut(), matchSubOfVScale(), matchTruncateOfExt(), matchTruncBuildVectorFold(), matchTruncLshrBuildVectorFold(), matchUDivorURemByConst(), matchUMulHToLShr(), matchUndefSelectCmp(), matchUndefStore(), matchUnmergeValuesAnyExtBuildVector(), matchUseVectorTruncate(), matchXorOfAndWithSameReg(), matchZextOfTrunc(), replaceRegOpWith(), replaceRegWith(), replaceSingleDefInstWithOperand(), replaceSingleDefInstWithReg(), setRegBank(), and tryReassocBinOp().
Observer
GISelChangeObserver& llvm::CombinerHelper::Observer protected
Definition at line 108 of file CombinerHelper.h.
Referenced by llvm::AMDGPUCombinerHelper::AMDGPUCombinerHelper(), applyCombineExtendingLoads(), applyCombineMulToShl(), applyCommuteBinOpOperands(), applyFunnelShiftToRotate(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddImmedChain(), applyRotateOutOfRange(), applyShiftImmedChain(), applyXorOfAndWithSameReg(), CombinerHelper(), matchAddEToAddO(), matchAndOrDisjointMask(), matchCombineSubToAdd(), matchFreezeOfSingleMaybePoisonOperand(), matchMulOBy2(), matchNarrowBinopFeedingAnd(), matchReassocConstantInnerLHS(), matchReassocConstantInnerRHS(), matchReassocFoldConstantsInSubTree(), matchRedundantNegOperands(), matchRedundantSextInReg(), replaceOpcodeWith(), replaceRegOpWith(), and replaceRegWith().
RBI
const RegisterBankInfo* llvm::CombinerHelper::RBI protected
Definition at line 113 of file CombinerHelper.h.
Referenced by CombinerHelper(), and getRegBank().
TRI
const TargetRegisterInfo* llvm::CombinerHelper::TRI protected
Definition at line 114 of file CombinerHelper.h.
Referenced by CombinerHelper(), getRegBank(), and matchFreezeOfSingleMaybePoisonOperand().
VT
GISelValueTracking* llvm::CombinerHelper::VT protected
Definition at line 109 of file CombinerHelper.h.
Referenced by llvm::AMDGPUCombinerHelper::AMDGPUCombinerHelper(), buildUDivorURemUsingMul(), CombinerHelper(), getValueTracking(), matchAddOverflow(), matchCombineShlOfExtend(), matchCombineTruncOfShift(), matchCombineZextTrunc(), matchICmpToLHSKnownBits(), matchICmpToTrueFalseKnownBits(), matchOperandIsKnownToBeAPowerOfTwo(), matchRedundantAnd(), matchRedundantOr(), matchRedundantSExtInReg(), matchShiftsTooBig(), and matchSuboCarryOut().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CombinerHelper.h
lib/CodeGen/GlobalISel/CombinerHelper.cpp
lib/CodeGen/GlobalISel/CombinerHelperArtifacts.cpp
lib/CodeGen/GlobalISel/CombinerHelperCasts.cpp
lib/CodeGen/GlobalISel/CombinerHelperCompares.cpp
lib/CodeGen/GlobalISel/CombinerHelperVectorOps.cpp