LLVM: llvm::SDNodeInfo Class Reference
llvm::SDNodeInfo Class Reference final
#include "llvm/CodeGen/SDNodeInfo.h"
Public Member Functions
constexpr SDNodeInfo (unsigned NumOpcodes, const SDNodeDesc *Descs, StringTable Names, const SDTypeConstraint *Constraints)
bool hasDesc (unsigned Opcode) const
Returns true if there is a generated description for a node with the given target-specific opcode.
const SDNodeDesc & getDesc (unsigned Opcode) const
Returns the description of a node with the given opcode.
ArrayRef< SDTypeConstraint > getConstraints (unsigned Opcode) const
Returns operand constraints for a node with the given opcode.
StringRef getName (unsigned Opcode) const
Returns the name of the given target-specific opcode, suitable for debug printing.
void verifyNode (const SelectionDAG &DAG, const SDNode *N) const
Detailed Description
Definition at line 75 of file SDNodeInfo.h.
Constructor & Destructor Documentation
SDNodeInfo()
llvm::SDNodeInfo::SDNodeInfo (unsigned NumOpcodes, const SDNodeDesc * Descs, StringTable Names, const SDTypeConstraint * Constraints) inline constexpr
Definition at line 82 of file SDNodeInfo.h.
Member Function Documentation
getConstraints()
ArrayRef< SDTypeConstraint > llvm::SDNodeInfo::getConstraints (unsigned Opcode) const inline
Returns operand constraints for a node with the given opcode.
Definition at line 101 of file SDNodeInfo.h.
References llvm::ArrayRef(), and getDesc().
getDesc()
const SDNodeDesc & llvm::SDNodeInfo::getDesc (unsigned Opcode) const inline
Returns the description of a node with the given opcode.
Definition at line 95 of file SDNodeInfo.h.
References assert(), llvm::ISD::BUILTIN_OP_END, and hasDesc().
Referenced by getConstraints(), getName(), and verifyNode().
getName()
StringRef llvm::SDNodeInfo::getName (unsigned Opcode) const inline
Returns the name of the given target-specific opcode, suitable for debug printing.
Definition at line 108 of file SDNodeInfo.h.
References getDesc(), and llvm::SDNodeDesc::NameOffset.
hasDesc()
bool llvm::SDNodeInfo::hasDesc (unsigned Opcode) const inline
Returns true if there is a generated description for a node with the given target-specific opcode.
Definition at line 89 of file SDNodeInfo.h.
References assert(), and llvm::ISD::BUILTIN_OP_END.
Referenced by getDesc().
verifyNode()
void SDNodeInfo::verifyNode (const SelectionDAG & DAG, const SDNode * N) const
Definition at line 43 of file SDNodeInfo.cpp.
References checkOperandType(), checkResultType(), getDesc(), N, OpIdx, llvm::ISD::Register, llvm::ISD::RegisterMask, reportNodeError(), llvm::SDNPHasChain, llvm::SDNPInGlue, llvm::SDNPOptInGlue, llvm::SDNPOutGlue, and llvm::SDNPVariadic.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SDNodeInfo.h
lib/CodeGen/SelectionDAG/SDNodeInfo.cpp