LLVM: llvm::PredicateAssume Class Reference
llvm::PredicateAssume Class Reference
#include "llvm/Transforms/Utils/PredicateInfo.h"
Public Member Functions
PredicateAssume (Value *Op, IntrinsicInst *AssumeInst, Value *Condition)
PredicateAssume ()=delete
Public Member Functions inherited from llvm::PredicateBase
PredicateBase (const PredicateBase &)=delete
PredicateBase & operator= (const PredicateBase &)=delete
PredicateBase ()=delete
LLVM_ABI std::optional< PredicateConstraint > getConstraint () const
Fetch condition in the form of PredicateConstraint, if possible.
Static Public Member Functions
static bool classof (const PredicateBase *PB)
Static Public Member Functions inherited from llvm::PredicateBase
static bool classof (const PredicateBase *PB)
Public Attributes
IntrinsicInst * AssumeInst
Public Attributes inherited from llvm::PredicateBase
PredicateType Type
Value * OriginalOp
Value * RenamedOp
Value * Condition
Additional Inherited Members
Protected Member Functions inherited from llvm::PredicateBase
PredicateBase (PredicateType PT, Value *Op, Value *Condition)
Detailed Description
Definition at line 114 of file PredicateInfo.h.
Constructor & Destructor Documentation
PredicateAssume() [1/2]
llvm::PredicateAssume::PredicateAssume (Value * Op, IntrinsicInst * AssumeInst, Value * Condition) inline
Definition at line 117 of file PredicateInfo.h.
References AssumeInst, llvm::PredicateBase::Condition, llvm::PredicateBase::PredicateBase(), and llvm::PT_Assume.
PredicateAssume() [2/2]
llvm::PredicateAssume::PredicateAssume () delete
Member Function Documentation
classof()
bool llvm::PredicateAssume::classof (const PredicateBase * PB) inline static
Definition at line 120 of file PredicateInfo.h.
References PB(), llvm::PredicateBase::PredicateBase(), and llvm::PT_Assume.
Member Data Documentation
AssumeInst
IntrinsicInst* llvm::PredicateAssume::AssumeInst
Definition at line 116 of file PredicateInfo.h.
Referenced by PredicateAssume().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Utils/PredicateInfo.h