LLVM: llvm::DIEAbbrev Class Reference
llvm::DIEAbbrev Class Reference
Dwarf abbreviation, describes the organization of a debug information object.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEAbbrev (dwarf::Tag T, bool C)
void AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form)
Adds another set of attribute information to the abbreviation.
void AddImplicitConstAttribute (dwarf::Attribute Attribute, int64_t Value)
Adds attribute with DW_FORM_implicit_const value.
void AddAttribute (const DIEAbbrevData &AbbrevData)
Adds another set of attribute information to the abbreviation.
LLVM_ABI void Profile (FoldingSetNodeID &ID) const
Used to gather unique data for the abbreviation folding set.
LLVM_ABI void Emit (const AsmPrinter *AP) const
Print the abbreviation using the specified asm printer.
LLVM_ABI void print (raw_ostream &O) const
LLVM_ABI void dump () const
dwarf::Tag getTag () const
Accessors.
unsigned getNumber () const
bool hasChildren () const
const SmallVectorImpl< DIEAbbrevData > & getData () const
void setChildrenFlag (bool hasChild)
void setNumber (unsigned N)
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Detailed Description
Dwarf abbreviation, describes the organization of a debug information object.
Definition at line 80 of file DIE.h.
Constructor & Destructor Documentation
DIEAbbrev()
llvm::DIEAbbrev::DIEAbbrev (dwarf::Tag T, bool C) inline
Definition at line 97 of file DIE.h.
References llvm::CallingConv::C, and T.
Member Function Documentation
AddAttribute() [1/2]
void llvm::DIEAbbrev::AddAttribute (const DIEAbbrevData & AbbrevData) inline
Adds another set of attribute information to the abbreviation.
Definition at line 120 of file DIE.h.
AddAttribute() [2/2]
void llvm::DIEAbbrev::AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form) inline
Adds another set of attribute information to the abbreviation.
Definition at line 110 of file DIE.h.
Referenced by llvm::DIE::generateAbbrev().
AddImplicitConstAttribute()
void llvm::DIEAbbrev::AddImplicitConstAttribute (dwarf::Attribute Attribute, int64_t Value) inline
Adds attribute with DW_FORM_implicit_const value.
Definition at line 115 of file DIE.h.
Referenced by llvm::DIE::generateAbbrev().
dump()
LLVM_DUMP_METHOD void DIEAbbrev::dump () const
Definition at line 122 of file DIE.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
Emit()
void DIEAbbrev::Emit (const AsmPrinter * AP) const
Print the abbreviation using the specified asm printer.
Emit - Print the abbreviation using the specified asm printer.
Definition at line 62 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), data, llvm::dbgs(), llvm::AsmPrinter::emitSLEB128(), llvm::AsmPrinter::emitULEB128(), llvm::format(), llvm::dwarf::FormEncodingString(), llvm::AsmPrinter::getDwarfVersion(), llvm::dwarf::isValidFormForVersion(), LLVM_DEBUG, llvm_unreachable, and llvm::dwarf::TagString().
Referenced by llvm::AsmPrinter::emitDwarfAbbrev().
getData()
const SmallVectorImpl< DIEAbbrevData > & llvm::DIEAbbrev::getData () const inline
Definition at line 104 of file DIE.h.
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::assignAbbrev(), and llvm::dwarf_linker::parallel::DwarfUnit::emitDwarfAbbrevEntry().
getNumber()
unsigned llvm::DIEAbbrev::getNumber () const inline
Definition at line 102 of file DIE.h.
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::assignAbbrev(), llvm::AsmPrinter::emitDwarfAbbrev(), llvm::dwarf_linker::parallel::DwarfUnit::emitDwarfAbbrevEntry(), and llvm::dwarf_linker::parallel::DIEGenerator::finalizeAbbreviations().
getTag()
dwarf::Tag llvm::DIEAbbrev::getTag () const inline
Accessors.
Definition at line 101 of file DIE.h.
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::assignAbbrev(), and llvm::dwarf_linker::parallel::DwarfUnit::emitDwarfAbbrevEntry().
hasChildren()
bool llvm::DIEAbbrev::hasChildren () const inline
Definition at line 103 of file DIE.h.
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::assignAbbrev(), llvm::DIE::computeOffsetsAndAbbrevs(), and llvm::dwarf_linker::parallel::DwarfUnit::emitDwarfAbbrevEntry().
print()
LLVM_DUMP_METHOD void DIEAbbrev::print (raw_ostream & O) const
Definition at line 101 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), D(), llvm::format(), llvm::dwarf::FormEncodingString(), and llvm::dwarf::TagString().
Referenced by dump().
Profile()
void DIEAbbrev::Profile (FoldingSetNodeID & ID) const
Used to gather unique data for the abbreviation folding set.
Profile - Used to gather unique data for the abbreviation folding set.
Definition at line 51 of file DIE.cpp.
References D().
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::assignAbbrev(), and llvm::DIEAbbrevSet::uniqueAbbreviation().
setChildrenFlag()
void llvm::DIEAbbrev::setChildrenFlag (bool hasChild) inline
Definition at line 105 of file DIE.h.
Referenced by llvm::dwarf_linker::parallel::DIEGenerator::finalizeAbbreviations().
setNumber()
void llvm::DIEAbbrev::setNumber (unsigned N) inline
Definition at line 106 of file DIE.h.
References N.
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::assignAbbrev().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp