LLVM: llvm::GCMetadataPrinter Class Reference
llvm::GCMetadataPrinter Class Reference
GCMetadataPrinter - Emits GC metadata as assembly code.
#include "llvm/CodeGen/GCMetadataPrinter.h"
Public Member Functions
GCMetadataPrinter (const GCMetadataPrinter &)=delete
GCMetadataPrinter & operator= (const GCMetadataPrinter &)=delete
virtual ~GCMetadataPrinter ()
GCStrategy & getStrategy ()
virtual void beginAssembly (Module &M, GCModuleInfo &Info, AsmPrinter &AP)
Called before the assembly for the module is generated by the AsmPrinter (but after target specific hooks.)
virtual void finishAssembly (Module &M, GCModuleInfo &Info, AsmPrinter &AP)
Called after the assembly for the module is generated by the AsmPrinter (but before target specific hooks)
virtual bool emitStackMaps (StackMaps &SM, AsmPrinter &AP)
Called when the stack maps are generated.
Protected Member Functions
GCMetadataPrinter ()
Friends
class AsmPrinter
Detailed Description
GCMetadataPrinter - Emits GC metadata as assembly code.
Instances are created, managed, and owned by the AsmPrinter.
Definition at line 41 of file GCMetadataPrinter.h.
Constructor & Destructor Documentation
GCMetadataPrinter() [1/2]
GCMetadataPrinter::GCMetadataPrinter () protected default
Referenced by GCMetadataPrinter(), and operator=().
GCMetadataPrinter() [2/2]
llvm::GCMetadataPrinter::GCMetadataPrinter (const GCMetadataPrinter &) delete
References GCMetadataPrinter().
~GCMetadataPrinter()
GCMetadataPrinter::~GCMetadataPrinter () virtual default
Member Function Documentation
beginAssembly()
virtual void llvm::GCMetadataPrinter::beginAssembly (Module & M, GCModuleInfo & Info, AsmPrinter & AP) inline virtual
Called before the assembly for the module is generated by the AsmPrinter (but after target specific hooks.)
Definition at line 60 of file GCMetadataPrinter.h.
References AsmPrinter, and Info.
emitStackMaps()
virtual bool llvm::GCMetadataPrinter::emitStackMaps (StackMaps & SM, AsmPrinter & AP) inline virtual
Called when the stack maps are generated.
Return true if stack maps with a custom format are generated. Otherwise returns false and the default format will be used.
Definition at line 69 of file GCMetadataPrinter.h.
References AsmPrinter.
finishAssembly()
virtual void llvm::GCMetadataPrinter::finishAssembly (Module & M, GCModuleInfo & Info, AsmPrinter & AP) inline virtual
Called after the assembly for the module is generated by the AsmPrinter (but before target specific hooks)
Definition at line 64 of file GCMetadataPrinter.h.
References AsmPrinter, and Info.
getStrategy()
GCStrategy & llvm::GCMetadataPrinter::getStrategy () inline
Definition at line 56 of file GCMetadataPrinter.h.
operator=()
GCMetadataPrinter & llvm::GCMetadataPrinter::operator= (const GCMetadataPrinter &) delete
References GCMetadataPrinter().
Friends And Related Symbol Documentation
AsmPrinter
friend class AsmPrinter friend
Definition at line 43 of file GCMetadataPrinter.h.
References AsmPrinter.
Referenced by AsmPrinter, beginAssembly(), emitStackMaps(), and finishAssembly().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GCMetadataPrinter.h
lib/CodeGen/GCMetadataPrinter.cpp