LLVM: llvm::ms_demangle::ArenaAllocator Class Reference
llvm::ms_demangle::ArenaAllocator Class Reference
#include "llvm/Demangle/MicrosoftDemangle.h"
Public Member Functions
ArenaAllocator ()
~ArenaAllocator ()
ArenaAllocator (const ArenaAllocator &)=delete
ArenaAllocator & operator= (const ArenaAllocator &)=delete
char * allocUnalignedBuffer (size_t Size)
template<typename T, typename... Args>
T * allocArray (size_t Count)
template<typename T, typename... Args>
T * alloc (Args &&... ConstructorArgs)
Detailed Description
Definition at line 28 of file MicrosoftDemangle.h.
Constructor & Destructor Documentation
ArenaAllocator() [1/2]
llvm::ms_demangle::ArenaAllocator::ArenaAllocator () inline
Definition at line 46 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit.
Referenced by ArenaAllocator(), and operator=().
~ArenaAllocator()
llvm::ms_demangle::ArenaAllocator::~ArenaAllocator () inline
Definition at line 48 of file MicrosoftDemangle.h.
References assert(), and llvm::Next.
ArenaAllocator() [2/2]
llvm::ms_demangle::ArenaAllocator::ArenaAllocator (const ArenaAllocator &) delete
References ArenaAllocator().
Member Function Documentation
alloc()
template<typename T, typename... Args> T * llvm::ms_demangle::ArenaAllocator::alloc (Args &&... ConstructorArgs) inline
Definition at line 95 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit, assert(), P, Size, and T.
Referenced by nodeListToNodeArray(), synthesizeNamedIdentifier(), synthesizeQualifiedName(), and synthesizeVariable().
allocArray()
template<typename T, typename... Args> T * llvm::ms_demangle::ArenaAllocator::allocArray (size_t Count) inline
Definition at line 76 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit, assert(), llvm::Count, P, Size, and T.
Referenced by nodeListToNodeArray(), and synthesizeQualifiedName().
allocUnalignedBuffer()
char * llvm::ms_demangle::ArenaAllocator::allocUnalignedBuffer (size_t Size) inline
Definition at line 62 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit, assert(), P, and Size.
operator=()
ArenaAllocator & llvm::ms_demangle::ArenaAllocator::operator= (const ArenaAllocator &) delete
References ArenaAllocator().
The documentation for this class was generated from the following file:
include/llvm/Demangle/MicrosoftDemangle.h