LLVM: llvm::codeview::detail::GuidAdapter Class Reference
llvm::codeview::detail::GuidAdapter Class Reference final
#include "llvm/DebugInfo/CodeView/Formatters.h"
Public Member Functions
GuidAdapter (ArrayRef< uint8_t > Guid)
GuidAdapter (StringRef Guid)
void format (raw_ostream &Stream, StringRef Style) override
Additional Inherited Members
Protected Member Functions inherited from llvm::FormatAdapter< ArrayRef< uint8_t > >
FormatAdapter (ArrayRef< uint8_t > &&Item)
Protected Member Functions inherited from llvm::support::detail::format_adapter
virtual ~format_adapter ()=default
Protected Attributes inherited from llvm::FormatAdapter< ArrayRef< uint8_t > >
ArrayRef< uint8_t > Item
Detailed Description
Definition at line 30 of file Formatters.h.
Constructor & Destructor Documentation
GuidAdapter() [1/2]
GuidAdapter::GuidAdapter (ArrayRef< uint8_t > Guid) explicit
Definition at line 25 of file Formatters.cpp.
References llvm::FormatAdapter< ArrayRef< uint8_t > >::FormatAdapter(), and llvm::move().
GuidAdapter() [2/2]
GuidAdapter::GuidAdapter (StringRef Guid) explicit
Definition at line 22 of file Formatters.cpp.
References llvm::FormatAdapter< ArrayRef< uint8_t > >::FormatAdapter().
Member Function Documentation
format()
void GuidAdapter::format (raw_ostream & Stream, StringRef Style) override virtual
Implements llvm::support::detail::format_adapter.
Definition at line 39 of file Formatters.cpp.
References assert(), llvm::format_hex_no_prefix(), G, and llvm::FormatAdapter< ArrayRef< uint8_t > >::Item.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/Formatters.h
lib/DebugInfo/CodeView/Formatters.cpp