LLVM: llvm::DstOp Class Reference
llvm::DstOp Class Reference
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
Public Types
enum class DstType { Ty_LLT , Ty_Reg , Ty_RC , Ty_VRegAttrs }
Public Member Functions
DstOp (unsigned R)
DstOp (Register R)
DstOp (const MachineOperand &Op)
DstOp (const LLT T)
DstOp (const TargetRegisterClass *TRC)
DstOp (MachineRegisterInfo::VRegAttrs Attrs)
DstOp (RegClassOrRegBank RCOrRB, LLT Ty)
void addDefToMIB (MachineRegisterInfo &MRI, MachineInstrBuilder &MIB) const
LLT getLLTTy (const MachineRegisterInfo &MRI) const
Register getReg () const
const TargetRegisterClass * getRegClass () const
MachineRegisterInfo::VRegAttrs getVRegAttrs () const
DstType getDstOpKind () const
Detailed Description
Definition at line 71 of file MachineIRBuilder.h.
Member Enumeration Documentation
DstType
enum class llvm::DstOp::DstType strong
Enumerator
Ty_LLT
Ty_Reg
Ty_RC
Ty_VRegAttrs
Definition at line 80 of file MachineIRBuilder.h.
Constructor & Destructor Documentation
DstOp() [1/7]
llvm::DstOp::DstOp (unsigned R) inline
Definition at line 81 of file MachineIRBuilder.h.
References Reg, and Ty_Reg.
DstOp() [2/7]
llvm::DstOp::DstOp (Register R) inline
Definition at line 82 of file MachineIRBuilder.h.
References Reg, and Ty_Reg.
DstOp() [3/7]
llvm::DstOp::DstOp (const MachineOperand & Op) inline
Definition at line 83 of file MachineIRBuilder.h.
References getReg(), Reg, and Ty_Reg.
DstOp() [4/7]
llvm::DstOp::DstOp (const LLT T) inline
Definition at line 84 of file MachineIRBuilder.h.
References LLTTy, T, and Ty_LLT.
DstOp() [5/7]
llvm::DstOp::DstOp (const TargetRegisterClass * TRC) inline
Definition at line 85 of file MachineIRBuilder.h.
References RC, and Ty_RC.
DstOp() [6/7]
llvm::DstOp::DstOp (MachineRegisterInfo::VRegAttrs Attrs) inline
Definition at line 86 of file MachineIRBuilder.h.
References Attrs, and Ty_VRegAttrs.
DstOp() [7/7]
llvm::DstOp::DstOp (RegClassOrRegBank RCOrRB, LLT Ty) inline
Definition at line 88 of file MachineIRBuilder.h.
References Attrs.
Member Function Documentation
addDefToMIB()
void llvm::DstOp::addDefToMIB (MachineRegisterInfo & MRI, MachineInstrBuilder & MIB) const inline
Definition at line 91 of file MachineIRBuilder.h.
References llvm::MachineInstrBuilder::addDef(), Attrs, LLTTy, MRI, RC, Reg, Ty_LLT, Ty_RC, Ty_Reg, and Ty_VRegAttrs.
Referenced by llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildConstantPool(), llvm::MachineIRBuilder::buildConstantPtrAuth(), llvm::MachineIRBuilder::buildDynStackAlloc(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFrameIndex(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildStepVector(), llvm::MachineIRBuilder::buildVScale(), and llvm::AArch64CallLowering::lowerCall().
getDstOpKind()
DstType llvm::DstOp::getDstOpKind () const inline
Definition at line 137 of file MachineIRBuilder.h.
getLLTTy()
LLT llvm::DstOp::getLLTTy (const MachineRegisterInfo & MRI) const inline
Definition at line 108 of file MachineIRBuilder.h.
References Attrs, LLTTy, llvm_unreachable, MRI, Reg, Ty_LLT, Ty_RC, Ty_Reg, and Ty_VRegAttrs.
Referenced by llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::MachineIRBuilder::buildBuildVectorConstant(), llvm::MachineIRBuilder::buildBuildVectorTrunc(), llvm::CSEMIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildConstantPool(), llvm::MachineIRBuilder::buildDeleteTrailingVectorElements(), llvm::MachineIRBuilder::buildDynStackAlloc(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::CSEMIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFrameIndex(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildMaskLowPtrBits(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildShuffleSplat(), llvm::MachineIRBuilder::buildShuffleVector(), llvm::MachineIRBuilder::buildSplatBuildVector(), llvm::MachineIRBuilder::buildSplatVector(), llvm::MachineIRBuilder::buildStepVector(), llvm::MachineIRBuilder::buildVScale(), llvm::MachineIRBuilder::buildZExtInReg(), and llvm::LegalizerHelper::createStackStoreLoad().
getReg()
Register llvm::DstOp::getReg () const inline
Definition at line 122 of file MachineIRBuilder.h.
References assert(), Reg, and Ty_Reg.
Referenced by addConstantComments(), llvm::MachineIRBuilder::buildDeleteTrailingVectorElements(), llvm::SPIRVInstrInfo::copyPhysReg(), cvtVOP3DstOpSelOnly(), DstOp(), llvm::SIRegisterInfo::eliminateFrameIndex(), isCopyOf(), isCopyOfBundle(), and printDstRegisterName().
getRegClass()
const TargetRegisterClass * llvm::DstOp::getRegClass () const inline
Definition at line 127 of file MachineIRBuilder.h.
References assert(), RC, and Ty_RC.
getVRegAttrs()
MachineRegisterInfo::VRegAttrs llvm::DstOp::getVRegAttrs () const inline
Definition at line 132 of file MachineIRBuilder.h.
References assert(), Attrs, and Ty_VRegAttrs.
Member Data Documentation
Attrs
MachineRegisterInfo::VRegAttrs llvm::DstOp::Attrs
Definition at line 76 of file MachineIRBuilder.h.
Referenced by addDefToMIB(), DstOp(), DstOp(), getLLTTy(), and getVRegAttrs().
LLTTy
LLT llvm::DstOp::LLTTy
Definition at line 73 of file MachineIRBuilder.h.
Referenced by addDefToMIB(), DstOp(), and getLLTTy().
RC
const TargetRegisterClass* llvm::DstOp::RC
Definition at line 75 of file MachineIRBuilder.h.
Referenced by addDefToMIB(), DstOp(), and getRegClass().
Reg
Register llvm::DstOp::Reg
Definition at line 74 of file MachineIRBuilder.h.
Referenced by addDefToMIB(), DstOp(), DstOp(), DstOp(), getLLTTy(), and getReg().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h