LLVM: llvm::mca::HWInstructionEvent Class Reference
llvm::mca::HWInstructionEvent Class Reference
#include "llvm/MCA/HWEventListener.h"
Public Types
enum GenericEventType {
Invalid = 0 , Retired , Pending , Ready ,
Issued , Executed , Dispatched , LastGenericEventType
}
Public Member Functions
HWInstructionEvent (unsigned type, const InstRef &Inst)
Public Attributes
const unsigned Type
const InstRef & IR
Detailed Description
Definition at line 28 of file HWEventListener.h.
Member Enumeration Documentation
GenericEventType
enum llvm::mca::HWInstructionEvent::GenericEventType
Enumerator
Invalid
Retired
Pending
Ready
Issued
Executed
Dispatched
LastGenericEventType
Definition at line 38 of file HWEventListener.h.
Constructor & Destructor Documentation
HWInstructionEvent()
llvm::mca::HWInstructionEvent::HWInstructionEvent (unsigned type, const InstRef & Inst) inline
Definition at line 53 of file HWEventListener.h.
References IR, and Type.
Referenced by llvm::mca::HWInstructionDispatchedEvent::HWInstructionDispatchedEvent(), llvm::mca::HWInstructionIssuedEvent::HWInstructionIssuedEvent(), and llvm::mca::HWInstructionRetiredEvent::HWInstructionRetiredEvent().
Member Data Documentation
IR
const InstRef& llvm::mca::HWInstructionEvent::IR
Definition at line 60 of file HWEventListener.h.
Referenced by llvm::mca::HWInstructionDispatchedEvent::HWInstructionDispatchedEvent(), HWInstructionEvent(), llvm::mca::HWInstructionIssuedEvent::HWInstructionIssuedEvent(), and llvm::mca::HWInstructionRetiredEvent::HWInstructionRetiredEvent().
Type
const unsigned llvm::mca::HWInstructionEvent::Type
Definition at line 57 of file HWEventListener.h.
Referenced by HWInstructionEvent().
The documentation for this class was generated from the following file:
include/llvm/MCA/HWEventListener.h