LLVM: llvm::MCLOHDirective Class Reference
llvm::MCLOHDirective Class Reference
Store Linker Optimization Hint information (LOH).
#include "llvm/MC/MCLinkerOptimizationHint.h"
Public Types
using LOHArgs = SmallVectorImpl<MCSymbol *>
Public Member Functions
MCLOHDirective (MCLOHType Kind, const LOHArgs &Args)
MCLOHType getKind () const
const LOHArgs & getArgs () const
LLVM_ABI void emit (const MCAssembler &Asm, MachObjectWriter &ObjWriter) const
Emit this directive as: <kind, numArgs, addr1, ..., addrN>
LLVM_ABI uint64_t getEmitSize (const MCAssembler &Asm, const MachObjectWriter &ObjWriter) const
Get the size in bytes of this directive if emitted in ObjWriter with the given Layout.
Detailed Description
Store Linker Optimization Hint information (LOH).
Definition at line 103 of file MCLinkerOptimizationHint.h.
Member Typedef Documentation
LOHArgs
using llvm::MCLOHDirective::LOHArgs = SmallVectorImpl<MCSymbol *>
Definition at line 116 of file MCLinkerOptimizationHint.h.
Constructor & Destructor Documentation
MCLOHDirective()
llvm::MCLOHDirective::MCLOHDirective (MCLOHType Kind, const LOHArgs & Args) inline
Definition at line 118 of file MCLinkerOptimizationHint.h.
References assert(), and llvm::isValidMCLOHType().
Member Function Documentation
emit()
void MCLOHDirective::emit (const MCAssembler & Asm, MachObjectWriter & ObjWriter) const
Emit this directive as: <kind, numArgs, addr1, ..., addrN>
Definition at line 36 of file MCLinkerOptimizationHint.cpp.
References llvm::support::endian::Writer::OS, and llvm::MachObjectWriter::W.
getArgs()
const LOHArgs & llvm::MCLOHDirective::getArgs () const inline
Definition at line 125 of file MCLinkerOptimizationHint.h.
getEmitSize()
uint64_t MCLOHDirective::getEmitSize (const MCAssembler & Asm, const MachObjectWriter & ObjWriter) const
Get the size in bytes of this directive if emitted in ObjWriter with the given Layout.
Definition at line 42 of file MCLinkerOptimizationHint.cpp.
References llvm::Count, and llvm::size().
getKind()
MCLOHType llvm::MCLOHDirective::getKind () const inline
Definition at line 123 of file MCLinkerOptimizationHint.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCLinkerOptimizationHint.h
lib/MC/MCLinkerOptimizationHint.cpp