LLVM: llvm::slpvectorizer::BoUpSLP::VLOperands Class Reference
llvm::slpvectorizer::BoUpSLP::VLOperands Class Reference
A helper data structure to hold the operands of a vector of instructions.
Public Member Functions
VLOperands (ArrayRef< Value * > RootVL, ArrayRef< ValueList > Operands, const InstructionsState &S, const BoUpSLP &R)
Initialize with all the operands of the instruction vector RootVL.
ValueList getVL (unsigned OpIdx) const
\Returns a value vector with the operands across all lanes for the opearnd at OpIdx.
void reorder ()
LLVM_DUMP_METHOD raw_ostream & print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Debug print.
Static Public Member Functions
static LLVM_DUMP_METHOD StringRef getModeStr (ReorderingMode RMode)
static LLVM_DUMP_METHOD raw_ostream & printMode (ReorderingMode RMode, raw_ostream &OS)
static LLVM_DUMP_METHOD void dumpMode (ReorderingMode RMode)
Debug print.
Friends
raw_ostream & operator<< (raw_ostream &OS, ReorderingMode RMode)
Detailed Description
A helper data structure to hold the operands of a vector of instructions.
This supports a fixed vector length for all operand vectors.
Definition at line 2436 of file SLPVectorizer.cpp.
Constructor & Destructor Documentation
VLOperands()
llvm::slpvectorizer::BoUpSLP::VLOperands::VLOperands (ArrayRef< Value * > RootVL, ArrayRef< ValueList > Operands, const InstructionsState & S, const BoUpSLP & R) inline
Initialize with all the operands of the instruction vector RootVL.
Definition at line 3034 of file SLPVectorizer.cpp.
References llvm::slpvectorizer::BoUpSLP::BoUpSLP(), getParent(), and Operands.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void llvm::slpvectorizer::BoUpSLP::VLOperands::dump () const inline
Debug print.
Definition at line 3246 of file SLPVectorizer.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
dumpMode()
LLVM_DUMP_METHOD void llvm::slpvectorizer::BoUpSLP::VLOperands::dumpMode (ReorderingMode RMode) inline static
Debug print.
Definition at line 3219 of file SLPVectorizer.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and printMode().
getModeStr()
LLVM_DUMP_METHOD StringRef llvm::slpvectorizer::BoUpSLP::VLOperands::getModeStr (ReorderingMode RMode) inline static
Definition at line 3197 of file SLPVectorizer.cpp.
References LLVM_DUMP_METHOD, and llvm_unreachable.
Referenced by printMode().
getVL()
ValueList llvm::slpvectorizer::BoUpSLP::VLOperands::getVL (unsigned OpIdx) const inline
\Returns a value vector with the operands across all lanes for the opearnd at OpIdx.
Definition at line 3044 of file SLPVectorizer.cpp.
References assert(), OpIdx, and llvm::size().
print()
LLVM_DUMP_METHOD raw_ostream & llvm::slpvectorizer::BoUpSLP::VLOperands::print (raw_ostream & OS) const inline
Definition at line 3227 of file SLPVectorizer.cpp.
References llvm::raw_ostream::indent(), and LLVM_DUMP_METHOD.
Referenced by dump().
printMode()
LLVM_DUMP_METHOD raw_ostream & llvm::slpvectorizer::BoUpSLP::VLOperands::printMode (ReorderingMode RMode, raw_ostream & OS) inline static
Definition at line 3213 of file SLPVectorizer.cpp.
References getModeStr(), and LLVM_DUMP_METHOD.
Referenced by dumpMode(), and operator<<.
reorder()
void llvm::slpvectorizer::BoUpSLP::VLOperands::reorder () inline
Definition at line 3056 of file SLPVectorizer.cpp.
References llvm::any_of(), llvm::ArrayRef(), assert(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::Data, llvm::dyn_cast(), llvm::ArrayRef< T >::front(), llvm::SmallVectorTemplateCommon< T, typename >::front(), getSameOpcode(), llvm::hasFullVectorsOrPowerOf2(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm_unreachable, OpIdx, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallBitVector::set(), llvm::size(), and llvm::SmallPtrSetImplBase::size().
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, ReorderingMode RMode) friend
Definition at line 3223 of file SLPVectorizer.cpp.
References printMode().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/SLPVectorizer.cpp