LLVM: llvm::object::ELFSectionRef Class Reference
llvm::object::ELFSectionRef Class Reference
#include "llvm/Object/ELFObjectFile.h"
Public Member Functions
ELFSectionRef (const SectionRef &B)
const ELFObjectFileBase * getObject () const
uint32_t getType () const
uint64_t getFlags () const
uint64_t getOffset () const
Public Member Functions inherited from llvm::object::SectionRef
SectionRef ()=default
SectionRef (DataRefImpl SectionP, const ObjectFile *Owner)
SectionRef.
bool operator== (const SectionRef &Other) const
bool operator!= (const SectionRef &Other) const
bool operator< (const SectionRef &Other) const
void moveNext ()
Expected< StringRef > getName () const
uint64_t getAddress () const
uint64_t getIndex () const
uint64_t getSize () const
Expected< StringRef > getContents () const
Align getAlignment () const
Get the alignment of this section.
bool isCompressed () const
bool isText () const
Whether this section contains instructions.
bool isData () const
Whether this section contains data, not instructions.
bool isBSS () const
Whether this section contains BSS uninitialized data.
bool isVirtual () const
bool isBitcode () const
bool isStripped () const
bool isBerkeleyText () const
Whether this section will be placed in the text segment, according to the Berkeley size format.
bool isBerkeleyData () const
Whether this section will be placed in the data segment, according to the Berkeley size format.
bool isDebugSection () const
Whether this section is a debug section.
LLVM_ABI bool containsSymbol (SymbolRef S) const
relocation_iterator relocation_begin () const
relocation_iterator relocation_end () const
iterator_range< relocation_iterator > relocations () const
Expected< section_iterator > getRelocatedSection () const
Returns the related section if this section contains relocations.
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObject () const
Detailed Description
Definition at line 133 of file ELFObjectFile.h.
Constructor & Destructor Documentation
ELFSectionRef()
llvm::object::ELFSectionRef::ELFSectionRef (const SectionRef & B) inline
Definition at line 135 of file ELFObjectFile.h.
References assert(), B(), llvm::object::SectionRef::getObject(), llvm::isa(), and llvm::object::SectionRef::SectionRef().
Member Function Documentation
getFlags()
uint64_t llvm::object::ELFSectionRef::getFlags () const inline
Definition at line 147 of file ELFObjectFile.h.
References getObject(), llvm::object::SectionRef::getRawDataRefImpl(), and llvm::object::ELFObjectFileBase::getSectionFlags().
Referenced by llvm::isReadOnlyData(), llvm::isRequiredForExecution(), and llvm::isTLS().
getObject()
const ELFObjectFileBase * llvm::object::ELFSectionRef::getObject () const inline
Definition at line 139 of file ELFObjectFile.h.
References llvm::cast(), and llvm::object::SectionRef::getObject().
Referenced by getFlags(), getOffset(), and getType().
getOffset()
uint64_t llvm::object::ELFSectionRef::getOffset () const inline
Definition at line 151 of file ELFObjectFile.h.
References getObject(), llvm::object::SectionRef::getRawDataRefImpl(), and llvm::object::ELFObjectFileBase::getSectionOffset().
Referenced by llvm::object::extractOffloadBundleFatBinary().
getType()
uint32_t llvm::object::ELFSectionRef::getType () const inline
Definition at line 143 of file ELFObjectFile.h.
References getObject(), llvm::object::SectionRef::getRawDataRefImpl(), and llvm::object::ELFObjectFileBase::getSectionType().
Referenced by llvm::isZeroInit().
The documentation for this class was generated from the following file:
include/llvm/Object/ELFObjectFile.h