LLVM: llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction > Class Template Reference
llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction > Class Template Reference
Pass implementation for the createDefineExternalSectionStartAndEndSymbols function.
#include "ExecutionEngine/JITLink/DefineExternalSectionStartAndEndSymbols.h"
Public Member Functions
DefineExternalSectionStartAndEndSymbols (SymbolIdentifierFunction F)
Error operator() (LinkGraph &G)
Detailed Description
template<typename SymbolIdentifierFunction>
class llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >
Pass implementation for the createDefineExternalSectionStartAndEndSymbols function.
Definition at line 37 of file DefineExternalSectionStartAndEndSymbols.h.
Constructor & Destructor Documentation
DefineExternalSectionStartAndEndSymbols()
template<typename SymbolIdentifierFunction> llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >::DefineExternalSectionStartAndEndSymbols (SymbolIdentifierFunction F) inline
Definition at line 39 of file DefineExternalSectionStartAndEndSymbols.h.
References llvm::move().
Member Function Documentation
operator()()
template<typename SymbolIdentifierFunction> Error llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >::operator() (LinkGraph & G) inline
Definition at line 42 of file DefineExternalSectionStartAndEndSymbols.h.
References D(), F, G, llvm::jitlink::Local, llvm::jitlink::Strong, and llvm::Error::success().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/DefineExternalSectionStartAndEndSymbols.h