LLVM: llvm::memprof::YAMLMemProfReader Class Reference
llvm::memprof::YAMLMemProfReader Class Reference final
#include "llvm/ProfileData/MemProfReader.h"
Public Member Functions
YAMLMemProfReader ()=default
LLVM_ABI void parse (StringRef YAMLData)
std::unique_ptr< memprof::DataAccessProfData > takeDataAccessProfData ()
Public Member Functions inherited from llvm::memprof::MemProfReader
InstrProfKind getProfileKind () const
Iterator end ()
Iterator begin ()
IndexedMemProfData takeMemProfData ()
virtual Error readNextRecord (GuidMemProfRecordPair &GuidRecord, std::function< const Frame(const FrameId)> Callback=nullptr)
MemProfReader ()=default
virtual ~MemProfReader ()=default
MemProfReader (IndexedMemProfData &&MemProfData)
Static Public Member Functions
static LLVM_ABI bool hasFormat (const MemoryBuffer &DataBuffer)
static LLVM_ABI bool hasFormat (const StringRef Path)
static LLVM_ABI Expected< std::unique_ptr< YAMLMemProfReader > > create (const Twine &Path)
static LLVM_ABI Expected< std::unique_ptr< YAMLMemProfReader > > create (std::unique_ptr< MemoryBuffer > Buffer)
Additional Inherited Members
Public Types inherited from llvm::memprof::MemProfReader
using GuidMemProfRecordPair = std::pair<GlobalValue::GUID, MemProfRecord>
using Iterator = InstrProfIterator<GuidMemProfRecordPair, MemProfReader>
Protected Member Functions inherited from llvm::memprof::MemProfReader
const Frame & idToFrame (const FrameId Id) const
Protected Attributes inherited from llvm::memprof::MemProfReader
IndexedMemProfData MemProfData
llvm::MapVector< GlobalValue::GUID, IndexedMemProfRecord >::iterator Iter
Detailed Description
Definition at line 214 of file MemProfReader.h.
Constructor & Destructor Documentation
YAMLMemProfReader()
llvm::memprof::YAMLMemProfReader::YAMLMemProfReader () default
References LLVM_ABI.
Member Function Documentation
create() [1/2]
Expected< std::unique_ptr< YAMLMemProfReader > > llvm::memprof::YAMLMemProfReader::create (const Twine & Path) static
Definition at line 769 of file MemProfReader.cpp.
References create(), llvm::errorCodeToError(), and llvm::MemoryBuffer::getFileOrSTDIN().
Referenced by create().
create() [2/2]
Expected< std::unique_ptr< YAMLMemProfReader > > llvm::memprof::YAMLMemProfReader::create (std::unique_ptr< MemoryBuffer > Buffer) static
Definition at line 779 of file MemProfReader.cpp.
hasFormat() [1/2]
bool llvm::memprof::YAMLMemProfReader::hasFormat (const MemoryBuffer & DataBuffer) static
Definition at line 794 of file MemProfReader.cpp.
References llvm::MemoryBuffer::getBuffer(), and llvm::StringRef::starts_with().
Referenced by hasFormat().
hasFormat() [2/2]
bool llvm::memprof::YAMLMemProfReader::hasFormat (const StringRef Path) static
Definition at line 785 of file MemProfReader.cpp.
References llvm::MemoryBuffer::getFileOrSTDIN(), and hasFormat().
parse()
void llvm::memprof::YAMLMemProfReader::parse (StringRef YAMLData)
Definition at line 798 of file MemProfReader.cpp.
References llvm::memprof::IndexedMemProfRecord::AllocSites, llvm::memprof::IndexedMemProfRecord::CallSites, llvm::memprof::AllocationInfo::CallStack, E(), llvm::yaml::Input::error(), F, llvm::memprof::AllMemProfData::HeapProfileRecords, llvm::memprof::AllocationInfo::Info, llvm::memprof::YamlDataAccessProfData::isEmpty(), llvm::memprof::YamlDataAccessProfData::KnownColdStrHashes, llvm::memprof::YamlDataAccessProfData::KnownColdSymbols, llvm::memprof::MemProfReader::MemProfData, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::memprof::YamlDataAccessProfData::Records, llvm::reportFatalInternalError(), llvm::SmallVectorImpl< T >::reserve(), and llvm::memprof::AllMemProfData::YamlifiedDataAccessProfiles.
takeDataAccessProfData()
std::unique_ptr< memprof::DataAccessProfData > llvm::memprof::YAMLMemProfReader::takeDataAccessProfData () inline
Definition at line 234 of file MemProfReader.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/MemProfReader.h
lib/ProfileData/MemProfReader.cpp