LLVM: llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin Class Reference
llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin Class Reference
Public Member Functions
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::PassConfiguration &Config) override
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (JITDylib &JD, ResourceKey K) override
void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey) override
void registerGraph (LinkGraph &G, std::shared_ptr< std::vector< ExecutorSymbolDef > > Addrs)
Error recordTrampolineAddrs (LinkGraph &G)
Detailed Description
Definition at line 29 of file JITLinkReentryTrampolines.cpp.
Member Function Documentation
modifyPassConfig()
void llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & G, jitlink::PassConfiguration & Config) inline override
Definition at line 32 of file JITLinkReentryTrampolines.cpp.
References G, llvm::jitlink::PassConfiguration::PreFixupPasses, and recordTrampolineAddrs().
notifyFailed()
Error llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::notifyFailed (MaterializationResponsibility & MR) inline override
Definition at line 39 of file JITLinkReentryTrampolines.cpp.
References llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::notifyRemovingResources (JITDylib & JD, ResourceKey K) inline override
Definition at line 43 of file JITLinkReentryTrampolines.cpp.
References llvm::Error::success().
notifyTransferringResources()
void llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::notifyTransferringResources (JITDylib & JD, ResourceKey DstKey, ResourceKey SrcKey) inline override
Definition at line 47 of file JITLinkReentryTrampolines.cpp.
recordTrampolineAddrs()
Error llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::recordTrampolineAddrs (LinkGraph & G) inline
Definition at line 57 of file JITLinkReentryTrampolines.cpp.
References assert(), G, I, and llvm::Error::success().
Referenced by modifyPassConfig().
registerGraph()
void llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::registerGraph (LinkGraph & G, std::shared_ptr< std::vector< ExecutorSymbolDef > > Addrs) inline
Definition at line 50 of file JITLinkReentryTrampolines.cpp.
References assert(), and G.
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/JITLinkReentryTrampolines.cpp