LLVM: llvm::CmpInst Class Reference
llvm::CmpInst Class Reference
This class is the base class for the comparison instructions.
#include "llvm/IR/InstrTypes.h"
Public Types
enum Predicate : unsigned {
FCMP_FALSE = 0 , FCMP_OEQ = 1 , FCMP_OGT = 2 , FCMP_OGE = 3 ,
FCMP_OLT = 4 , FCMP_OLE = 5 , FCMP_ONE = 6 , FCMP_ORD = 7 ,
FCMP_UNO = 8 , FCMP_UEQ = 9 , FCMP_UGT = 10 , FCMP_UGE = 11 ,
FCMP_ULT = 12 , FCMP_ULE = 13 , FCMP_UNE = 14 , FCMP_TRUE = 15 ,
FIRST_FCMP_PREDICATE = FCMP_FALSE , LAST_FCMP_PREDICATE = FCMP_TRUE , BAD_FCMP_PREDICATE = FCMP_TRUE + 1 , ICMP_EQ = 32 ,
ICMP_NE = 33 , ICMP_UGT = 34 , ICMP_UGE = 35 , ICMP_ULT = 36 ,
ICMP_ULE = 37 , ICMP_SGT = 38 , ICMP_SGE = 39 , ICMP_SLT = 40 ,
ICMP_SLE = 41 , FIRST_ICMP_PREDICATE = ICMP_EQ , LAST_ICMP_PREDICATE = ICMP_SLE , BAD_ICMP_PREDICATE = ICMP_SLE + 1
}
This enumeration lists the possible predicates for CmpInst subclasses.
using PredicateField
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1 << 0 , CompareUsingScalarTypes = 1 << 1 , CompareUsingIntersectedAttrs = 1 << 2 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
using InstListType
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Public Member Functions
void * operator new (size_t S)
void operator delete (void *Ptr)
OtherOps getOpcode () const
Get the opcode casted to the right type.
Predicate getPredicate () const
Return the predicate for this instruction.
void setPredicate (Predicate P)
Set the predicate for this instruction to the specified value.
bool isFPPredicate () const
bool isIntPredicate () const
Predicate getInversePredicate () const
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
Predicate getOrderedPredicate () const
Predicate getUnorderedPredicate () const
Predicate getSwappedPredicate () const
For example, EQ->EQ, SLE->SGE, ULT->UGT, OEQ->OEQ, ULE->UGE, OLT->OGT, etc.
bool isStrictPredicate () const
bool isNonStrictPredicate () const
Predicate getStrictPredicate () const
For example, SGE -> SGT, SLE -> SLT, ULE -> ULT, UGE -> UGT.
Predicate getNonStrictPredicate () const
For example, SGT -> SGE, SLT -> SLE, ULT -> ULE, UGT -> UGE.
Predicate getFlippedStrictnessPredicate () const
For predicate of kind "is X or equal to 0" returns the predicate "is X".
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide more efficient getOperand methods.
LLVM_ABI void swapOperands ()
This is just a convenience that dispatches to the subclasses.
LLVM_ABI bool isCommutative () const
This is just a convenience that dispatches to the subclasses.
bool isEquality () const
Determine if this is an equals/not equals predicate.
LLVM_ABI bool isEquivalence (bool Invert=false) const
Determine if one operand of this compare can always be replaced by the other operand, ignoring provenance considerations.
bool isRelational () const
Return true if the predicate is relational (not EQ or NE).
bool isSigned () const
bool isUnsigned () const
bool isTrueWhenEqual () const
This is just a convenience.
bool isFalseWhenEqual () const
This is just a convenience.
Public Member Functions inherited from llvm::Instruction
LLVM_ABI iterator_range< simple_ilist< DbgRecord >::iterator > cloneDebugInfoFrom (const Instruction *From, std::optional< simple_ilist< DbgRecord >::iterator > FromHere=std::nullopt, bool InsertAtHead=false)
Clone any debug-info attached to From onto this instruction.
iterator_range< simple_ilist< DbgRecord >::iterator > getDbgRecordRange () const
Return a range over the DbgRecords attached to this instruction.
LLVM_ABI std::optional< simple_ilist< DbgRecord >::iterator > getDbgReinsertionPosition ()
Return an iterator to the position of the "Next" DbgRecord after this instruction, or std::nullopt.
LLVM_ABI bool hasDbgRecords () const
Returns true if any DbgRecords are attached to this instruction.
LLVM_ABI void adoptDbgRecords (BasicBlock *BB, InstListType::iterator It, bool InsertAtHead)
Transfer any DbgRecords on the position It onto this instruction, by simply adopting the sequence of DbgRecords (which is efficient) if possible, by merging two sequences otherwise.
LLVM_ABI void dropDbgRecords ()
Erase any DbgRecords attached to this instruction.
LLVM_ABI void dropOneDbgRecord (DbgRecord *I)
Erase a single DbgRecord I that is attached to this instruction.
LLVM_ABI void handleMarkerRemoval ()
Handle the debug-info implications of this instruction being removed.
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
LLVM_ABI const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
LLVM_ABI const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
LLVM_ABI const DataLayout & getDataLayout () const
Get the data layout of the module this instruction belongs to.
LLVM_ABI void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
LLVM_ABI InstListType::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void insertBefore(Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
LLVM_ABI void insertBefore (InstListType::iterator InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified position.
LLVM_ABI void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
LLVM_ABI void insertAfter (InstListType::iterator InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified position.
LLVM_ABI InstListType::iterator insertInto (BasicBlock *ParentBB, InstListType::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
LLVM_ABI void insertBefore (BasicBlock &BB, InstListType::iterator InsertPos)
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void moveBefore(Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
LLVM_ABI void moveBefore (InstListType::iterator InsertPos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
LLVM_ABI void moveBeforePreserving (InstListType::iterator MovePos)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI void moveBeforePreserving (BasicBlock &BB, InstListType::iterator I)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void moveBeforePreserving(Instruction *MovePos)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI void moveBefore (BasicBlock &BB, InstListType::iterator I)
Unlink this instruction and insert into BB before I.
LLVM_ABI void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
LLVM_ABI void moveAfter (InstListType::iterator MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
LLVM_ABI void moveAfterPreserving (Instruction *MovePos)
See moveBeforePreserving .
LLVM_ABI bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
LLVM_ABI std::optional< InstListType::iterator > getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isFPDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isSpecialTerminator () const
LLVM_ABI bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
LLVM_ABI bool hasNonDebugLocLoopMetadata () const
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
LLVM_ABI void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
LLVM_ABI void setMetadata (StringRef Kind, MDNode *Node)
LLVM_ABI void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
LLVM_ABI void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata that matches the predicate.
LLVM_ABI void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
LLVM_ABI void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
LLVM_ABI void addAnnotationMetadata (SmallVector< StringRef > Annotations)
Adds an !annotation metadata node with an array of Annotations as a tuple to this instruction.
LLVM_ABI AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
LLVM_ABI void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
LLVM_ABI void setNoSanitizeMetadata ()
Sets the nosanitize metadata on this instruction.
LLVM_ABI bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
LLVM_ABI const DebugLoc & getStableDebugLoc () const
Fetch the debug location for this node, unless this is a debug intrinsic, in which case fetch the debug location of the next non-debug node.
LLVM_ABI void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setNonNeg (bool b=true)
Set or clear the nneg flag on this instruction, which must be a zext instruction.
LLVM_ABI bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
LLVM_ABI bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
LLVM_ABI bool hasNonNeg () const LLVM_READONLY
Determine whether the the nneg flag is set.
LLVM_ABI bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
LLVM_ABI void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
LLVM_ABI bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
LLVM_ABI void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
LLVM_ABI bool hasPoisonGeneratingReturnAttributes () const LLVM_READONLY
Return true if this instruction has poison-generating attribute.
LLVM_ABI void dropPoisonGeneratingReturnAttributes ()
Drops return attributes that may generate poison.
bool hasPoisonGeneratingAnnotations () const
Return true if this instruction has poison-generating flags, return attributes or metadata.
void dropPoisonGeneratingAnnotations ()
Drops flags, return attributes and metadata that may generate poison.
LLVM_ABI void dropUBImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
LLVM_ABI void dropUBImplyingAttrsAndMetadata ()
Drop any attributes or metadata that can cause immediate undefined behavior.
LLVM_ABI bool hasUBImplyingAttrs () const LLVM_READONLY
Return true if this instruction has UB-implying attributes that can cause immediate undefined behavior.
LLVM_ABI bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
LLVM_ABI void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
LLVM_ABI bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
LLVM_ABI bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
LLVM_ABI bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
LLVM_ABI bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
LLVM_ABI bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
LLVM_ABI bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
LLVM_ABI bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
LLVM_ABI bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
LLVM_ABI FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
LLVM_ABI void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
LLVM_ABI void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
LLVM_ABI void applyMergedLocation (DebugLoc LocA, DebugLoc LocB)
Merge 2 debug locations and apply it to the Instruction.
LLVM_ABI void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
LLVM_ABI void dropLocation ()
Drop the instruction's debug location.
LLVM_ABI void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
LLVM_ABI bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
LLVM_ABI bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
LLVM_ABI bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
LLVM_ABI bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
LLVM_ABI bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
LLVM_ABI bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
LLVM_ABI bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
LLVM_ABI bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
LLVM_ABI Type * getAccessType () const LLVM_READONLY
Return the type this instruction accesses in memory, if any.
LLVM_ABI bool mayThrow (bool IncludePhaseOneUnwind=false) const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
LLVM_ABI bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
LLVM_ABI bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
LLVM_ABI bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
LLVM_ABI bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
LLVM_ABI bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
LLVM_ABI bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
LLVM_ABI const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
LLVM_ABI const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
LLVM_ABI Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
LLVM_ABI bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
LLVM_ABI bool isIdenticalToWhenDefined (const Instruction *I, bool IntersectAttrs=false) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
LLVM_ABI bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
LLVM_ABI bool hasSameSpecialState (const Instruction *I2, bool IgnoreAlignment=false, bool IntersectAttrs=false) const LLVM_READONLY
This function determines if the speficied instruction has the same "special" characteristics as the current one.
LLVM_ABI bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
LLVM_ABI unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
LLVM_ABI BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
LLVM_ABI void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
LLVM_ABI void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
LLVM_ABI void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs={})
Drop all unknown metadata except for debug locations.
Public Member Functions inherited from llvm::User
User (const User &)=delete
LLVM_ABI void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, HungOffOperandsAllocMarker)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, IntrusiveOperandsAllocMarker)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, IntrusiveOperandsAndDescriptorAllocMarker)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
LLVM_ABI ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
LLVM_ABI MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
LLVM_ABI bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
LLVM_ABI bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
LLVM_ABI void deleteValue ()
Delete a pointer to a generic Value.
LLVM_ABI void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVM_ABI LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
LLVM_ABI ValueName * getValueName () const
LLVM_ABI void setValueName (ValueName *VN)
LLVM_ABI StringRef getName () const
Return a constant reference to the value's name.
LLVM_ABI void setName (const Twine &Name)
Change the name of the value.
LLVM_ABI void takeName (Value *V)
Transfer the name from V to this value.
LLVM_ABI std::string getNameOrAsOperand () const
LLVM_ABI void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
LLVM_ABI void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
LLVM_ABI void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
LLVM_ABI void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
LLVM_ABI void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool hasUseList () const
Check if this Value has a use-list.
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
LLVM_ABI bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
LLVM_ABI bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI bool hasOneUser () const
Return true if there is exactly one user of this value.
LLVM_ABI Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
LLVM_ABI User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
LLVM_ABI bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
LLVM_ABI bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
LLVM_ABI void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
LLVM_ABI bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
LLVM_ABI unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
LLVM_ABI bool isSwiftError () const
Return true if this value is a swifterror value.
LLVM_ABI const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
LLVM_ABI const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
LLVM_ABI const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
LLVM_ABI const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
LLVM_ABI const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
LLVM_ABI const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
LLVM_ABI const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
LLVM_ABI std::optional< int64_t > getPointerOffsetFrom (const Value *Other, const DataLayout &DL) const
If this ptr is provably equal to Other plus a constant offset, return that offset in bytes.
LLVM_ABI bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
LLVM_ABI uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
LLVM_ABI Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
LLVM_ABI const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
LLVM_ABI void reverseUseList ()
Reverse the use-list.
LLVM_ABI void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
LLVM_ABI void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock, ilist_iterator_bits< true >, ilist_parent< BasicBlock > >
Instruction * getPrevNode ()
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >, ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty *Parent)
Static Public Member Functions
static auto FCmpPredicates ()
Returns the sequence of all FCmp predicates.
static auto ICmpPredicates ()
Returns the sequence of all ICmp predicates.
static LLVM_ABI CmpInst * Create (OtherOps Op, Predicate Pred, Value *S1, Value *S2, const Twine &Name="", InsertPosition InsertBefore=nullptr)
Construct a compare instruction, given the opcode, the predicate and the two operands.
static LLVM_ABI CmpInst * CreateWithCopiedFlags (OtherOps Op, Predicate Pred, Value *S1, Value *S2, const Instruction *FlagsSource, const Twine &Name="", InsertPosition InsertBefore=nullptr)
Construct a compare instruction, given the opcode, the predicate, the two operands and the instruction to copy the flags from.
static bool isFPPredicate (Predicate P)
static bool isIntPredicate (Predicate P)
static LLVM_ABI StringRef getPredicateName (Predicate P)
static Predicate getOrderedPredicate (Predicate Pred)
Returns the ordered variant of a floating point compare.
static Predicate getUnorderedPredicate (Predicate Pred)
Returns the unordered variant of a floating point compare.
static LLVM_ABI Predicate getInversePredicate (Predicate pred)
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
static LLVM_ABI Predicate getSwappedPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI bool isStrictPredicate (Predicate predicate)
This is a static version that you can use without an instruction available.
static LLVM_ABI bool isNonStrictPredicate (Predicate predicate)
This is a static version that you can use without an instruction available.
static LLVM_ABI Predicate getStrictPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI Predicate getNonStrictPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI Predicate getFlippedStrictnessPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI bool isEquality (Predicate pred)
Determine if this is an equals/not equals predicate.
static bool isRelational (Predicate P)
Return true if the predicate is relational (not EQ or NE).
static LLVM_ABI bool isUnsigned (Predicate predicate)
static LLVM_ABI bool isSigned (Predicate predicate)
static LLVM_ABI bool isOrdered (Predicate predicate)
Determine if the predicate is an ordered operation.
static LLVM_ABI bool isUnordered (Predicate predicate)
Determine if the predicate is an unordered operation.
static LLVM_ABI bool isTrueWhenEqual (Predicate predicate)
Determine if the predicate is true when comparing a value with itself.
static LLVM_ABI bool isFalseWhenEqual (Predicate predicate)
Determine if the predicate is false when comparing a value with itself.
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
static Type * makeCmpResultType (Type *opnd_type)
Create a result type for fcmp/icmp.
Static Public Member Functions inherited from llvm::Instruction
static LLVM_ABI const char * getOpcodeName (unsigned Opcode)
static bool isTerminator (unsigned Opcode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isFPDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned Opcode)
Determine if the Opcode is one of the CastInst instructions.
static bool isFuncletPad (unsigned Opcode)
Determine if the Opcode is one of the FuncletPadInst instructions.
static bool isSpecialTerminator (unsigned Opcode)
Returns true if the Opcode is a "special" terminator that does more than branch to a successor (e.g.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static LLVM_ABI void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
LLVM_ABI CmpInst (Type *ty, Instruction::OtherOps op, Predicate pred, Value *LHS, Value *RHS, const Twine &Name="", InsertPosition InsertBefore=nullptr, Instruction *FlagsSource=nullptr)
Protected Member Functions inherited from llvm::Instruction
LLVM_ABI ~Instruction ()
template<typename BitfieldElement>
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement>
void setSubclassData (typename BitfieldElement::Type Value)
LLVM_ABI Instruction (Type *Ty, unsigned iType, AllocInfo AllocInfo, InsertPosition InsertBefore=nullptr)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)=delete
LLVM_ABI void * operator new (size_t Size, HungOffOperandsAllocMarker)
Allocate a User with an operand pointer co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAndDescriptorAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, AllocInfo AllocInfo)
LLVM_ABI void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
LLVM_ABI void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
LLVM_ABI Value (Type *Ty, unsigned scid)
LLVM_ABI ~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
LLVM_ABI void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
LLVM_ABI bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
LLVM_ABI void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata attachments matching the given predicate.
LLVM_ABI void clearMetadata ()
Erase all metadata attached to this Value.
LLVM_ABI MDNode * getMetadataImpl (unsigned KindID) const
Get metadata for the given kind, if any.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
LLVM_ABI MDNode * getMetadata (StringRef Kind) const
LLVM_ABI void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
LLVM_ABI void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
LLVM_ABI void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
LLVM_ABI void setMetadata (StringRef Kind, MDNode *Node)
LLVM_ABI void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
LLVM_ABI void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock, ilist_iterator_bits< true >, ilist_parent< BasicBlock > >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
ilist_node_impl ()=default
Additional Inherited Members
Public Attributes inherited from llvm::Instruction
DbgMarker * DebugMarker = nullptr
Optional marker recording the position for debugging information that takes effect immediately before this instruction.
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This class is the base class for the comparison instructions.
Abstract base class of comparison instructions.
Definition at line 666 of file InstrTypes.h.
Member Typedef Documentation
PredicateField
using llvm::CmpInst::PredicateField
Initial value:
      Bitfield::Element<Predicate, 0, 6, LAST_ICMP_PREDICATE>
Definition at line 713 of file InstrTypes.h.
Member Enumeration Documentation
Predicate
enum llvm::CmpInst::Predicate : unsigned
This enumeration lists the possible predicates for CmpInst subclasses.
Values in the range 0-31 are reserved for FCmpInst, while values in the range 32-64 are reserved for ICmpInst. This is necessary to ensure the predicate values are not overlapping between the classes.
Some passes (e.g. InstCombine) depend on the bit-wise characteristics of FCMP_* values. Changing the bit patterns requires a potential change to those passes.
Enumerator
FCMP_FALSE
0 0 0 0 Always false (always folded)
FCMP_OEQ
0 0 0 1 True if ordered and equal
FCMP_OGT
0 0 1 0 True if ordered and greater than
FCMP_OGE
0 0 1 1 True if ordered and greater than or equal
FCMP_OLT
0 1 0 0 True if ordered and less than
FCMP_OLE
0 1 0 1 True if ordered and less than or equal
FCMP_ONE
0 1 1 0 True if ordered and operands are unequal
FCMP_ORD
0 1 1 1 True if ordered (no nans)
FCMP_UNO
1 0 0 0 True if unordered: isnan(X) | isnan(Y)
FCMP_UEQ
1 0 0 1 True if unordered or equal
FCMP_UGT
1 0 1 0 True if unordered or greater than
FCMP_UGE
1 0 1 1 True if unordered, greater than, or equal
FCMP_ULT
1 1 0 0 True if unordered or less than
FCMP_ULE
1 1 0 1 True if unordered, less than, or equal
FCMP_UNE
1 1 1 0 True if unordered or not equal
FCMP_TRUE
1 1 1 1 Always true (always folded)
FIRST_FCMP_PREDICATE
LAST_FCMP_PREDICATE
BAD_FCMP_PREDICATE
ICMP_EQ
equal
ICMP_NE
not equal
ICMP_UGT
unsigned greater than
ICMP_UGE
unsigned greater or equal
ICMP_ULT
unsigned less than
ICMP_ULE
unsigned less or equal
ICMP_SGT
signed greater than
ICMP_SGE
signed greater or equal
ICMP_SLT
signed less than
ICMP_SLE
signed less or equal
FIRST_ICMP_PREDICATE
LAST_ICMP_PREDICATE
BAD_ICMP_PREDICATE
Definition at line 678 of file InstrTypes.h.
Constructor & Destructor Documentation
CmpInst()
CmpInst::CmpInst (Type * ty, Instruction::OtherOps op, Predicate pred, Value * LHS, Value * RHS, const Twine & Name = "", InsertPosition InsertBefore = nullptr, Instruction * FlagsSource = nullptr) protected
Definition at line 3485 of file Instructions.cpp.
References llvm::Instruction::copyIRFlags(), llvm::Instruction::Instruction(), op, llvm::Value::setName(), and setPredicate().
Referenced by Create(), CreateWithCopiedFlags(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), llvm::ICmpInst::ICmpInst(), and llvm::ICmpInst::ICmpInst().
Member Function Documentation
classof() [1/2]
bool llvm::CmpInst::classof (const Instruction * I) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 975 of file InstrTypes.h.
References I, and llvm::Instruction::Instruction().
Referenced by classof().
classof() [2/2]
bool llvm::CmpInst::classof (const Value * V) inline static
Definition at line 979 of file InstrTypes.h.
References llvm::cast(), classof(), and llvm::isa().
Create()
CmpInst * CmpInst::Create (OtherOps Op, Predicate Pred, Value * S1, Value * S2, const Twine & Name = "", InsertPosition InsertBefore = nullptr) static
Construct a compare instruction, given the opcode, the predicate and the two operands.
Optionally (if InstBefore is specified) insert the instruction into a BasicBlock right before the specified instruction. The specified Instruction is allowed to be a dereferenced end iterator. Create a CmpInst
Definition at line 3497 of file Instructions.cpp.
References CmpInst(), llvm::InsertPosition::isValid(), and S1.
Referenced by calcPredicateUsingInteger(), llvm::fuzzerop::cmpOpDescriptor(), CreateWithCopiedFlags(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), foldICmpInvariantGroup(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), foldICmpWithHighBitMask(), llvm::InstCombinerImpl::foldICmpWithMinMax(), foldICmpXNegX(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), llvm::InstCombinerImpl::foldPHIArgBinOpIntoPHI(), llvm::InstCombinerImpl::foldPHIArgOpIntoPHI(), foldReductionIdiom(), llvm::InstCombinerImpl::foldSignBitTest(), injectPendingInvariantConditions(), sinkCmpExpression(), and llvm::InstCombinerImpl::visitICmpInst().
CreateWithCopiedFlags()
CmpInst * CmpInst::CreateWithCopiedFlags (OtherOps Op, Predicate Pred, Value * S1, Value * S2, const Instruction * FlagsSource, const Twine & Name = "", InsertPosition InsertBefore = nullptr) static
Construct a compare instruction, given the opcode, the predicate, the two operands and the instruction to copy the flags from.
Optionally (if InstBefore is specified) insert the instruction into a BasicBlock right before the specified instruction. The specified Instruction is allowed to be a dereferenced end iterator. Create a CmpInst
Definition at line 3516 of file Instructions.cpp.
References CmpInst(), llvm::Instruction::copyIRFlags(), Create(), llvm::Instruction::Instruction(), and S1.
Referenced by llvm::InstCombinerImpl::visitExtractElementInst().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::CmpInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide more efficient getOperand methods.
References LLVM_ABI.
FCmpPredicates()
auto llvm::CmpInst::FCmpPredicates () inline static
Returns the sequence of all FCmp predicates.
Definition at line 717 of file InstrTypes.h.
References llvm::enum_seq_inclusive(), FIRST_FCMP_PREDICATE, llvm::force_iteration_on_noniterable_enum, and LAST_FCMP_PREDICATE.
Referenced by llvm::FCmpInst::predicates().
getFlippedStrictnessPredicate() [1/2]
Predicate llvm::CmpInst::getFlippedStrictnessPredicate () const inline
For predicate of kind "is X or equal to 0" returns the predicate "is X".
For predicate of kind "is X" returns the predicate "is X or equal to 0". does not support other kind of predicates.
Returns
the predicate that does not contains is equal to zero if it had and vice versa. Return the flipped strictness of predicate
Definition at line 895 of file InstrTypes.h.
References getFlippedStrictnessPredicate(), and getPredicate().
Referenced by llvm::Loop::LoopBounds::getCanonicalPredicate(), getFlippedStrictnessPredicate(), and llvm::getFlippedStrictnessPredicateAndConstant().
getFlippedStrictnessPredicate() [2/2]
CmpInst::Predicate CmpInst::getFlippedStrictnessPredicate (Predicate pred) static
This is a static version that you can use without an instruction available.
Return the flipped strictness of predicate
Definition at line 3781 of file Instructions.cpp.
References assert(), getNonStrictPredicate(), getStrictPredicate(), isNonStrictPredicate(), isRelational(), isStrictPredicate(), and llvm_unreachable.
Referenced by foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), and llvm::InstCombinerImpl::foldICmpOrConstant().
getInversePredicate() [1/2]
Predicate llvm::CmpInst::getInversePredicate () const inline
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
Returns
the inverse predicate for the instruction's current predicate. Return the inverse of the instruction's predicate.
Definition at line 791 of file InstrTypes.h.
References getInversePredicate(), and getPredicate().
Referenced by llvm::CombinerHelper::applyNotCmp(), canonicalizeForInvariantConditionInjection(), llvm::InstCombinerImpl::canonicalizeICmpPredicate(), canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), llvm::AArch64GISelUtils::changeVectorFCMPPredToAArch64CC(), checkCondition(), checkOrAndOpImpliedByOther(), computeKnownBitsFromOperator(), countToEliminateCompares(), createInvariantCond(), llvm::InnerLoopVectorizer::createIterationCountCheck(), llvm::decomposeBitTestICmp(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), llvm::SCEVExpander::expandComparePredicate(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpShlConstConst(), llvm::InstCombinerImpl::foldICmpShrConstConst(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldICmpWithMinMax(), foldLogOpOfMaskedICmps(), generateKeySubkey(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::ValueLatticeElement::getCompare(), llvm::PredicateBase::getConstraint(), llvm::ConstantRange::getEquivalentPredWithFlippedSignedness(), getHashValueImpl(), llvm::ICmpInst::getInverseCmpPredicate(), getInversePredicate(), getPredicateResult(), getRangeViaSLT(), hoistMinMax(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::InvertBranch(), isEqualImpl(), isEquivalence(), isImpliedCondCommonOperandWithCR(), isImpliedToBeAPowerOfTwoFromCond(), llvm::isKnownInversion(), isKnownNonNullFromDominatingCondition(), isKnownNonZeroFromOperator(), legalizeFCmpPredicate(), llvm::ConstantRange::makeSatisfyingICmpRegion(), matchFastFloatClamp(), negateICmpIfUsedByBranchOrSelectOnly(), shouldPeelLastIteration(), simplifyCmpSelOfMaxMin(), simplifyICmpInst(), simplifyICmpWithMinMax(), llvm::InstCombinerImpl::simplifyRangeCheck(), simplifyRecipe(), simplifySelectWithFCmp(), simplifySwitchOnSelectUsingRanges(), and llvm::InstCombinerImpl::visitBranchInst().
getInversePredicate() [2/2]
CmpInst::Predicate CmpInst::getInversePredicate (Predicate pred) static
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
Returns
the inverse predicate for predicate provided in pred. Return the inverse of a given predicate
Definition at line 3577 of file Instructions.cpp.
References FCMP_FALSE, FCMP_OEQ, FCMP_OGE, FCMP_OGT, FCMP_OLE, FCMP_OLT, FCMP_ONE, FCMP_ORD, FCMP_TRUE, FCMP_UEQ, FCMP_UGE, FCMP_UGT, FCMP_ULE, FCMP_ULT, FCMP_UNE, FCMP_UNO, ICMP_EQ, ICMP_NE, ICMP_SGE, ICMP_SGT, ICMP_SLE, ICMP_SLT, ICMP_UGE, ICMP_UGT, ICMP_ULE, ICMP_ULT, and llvm_unreachable.
getNonStrictPredicate() [1/2]
Predicate llvm::CmpInst::getNonStrictPredicate () const inline
For example, SGT -> SGE, SLT -> SLE, ULT -> ULE, UGT -> UGE.
Returns the non-strict version of strict comparisons.
Definition at line 873 of file InstrTypes.h.
References getNonStrictPredicate(), and getPredicate().
Referenced by checkAndReplaceMinMax(), llvm::InstCombinerImpl::foldICmpWithMinMax(), getFlippedStrictnessPredicate(), llvm::ICmpInst::getNonStrictCmpPredicate(), getNonStrictPredicate(), insertCandidatesWithPendingInjections(), processMinMaxIntrinsic(), llvm::simplifyBinaryIntrinsic(), and llvm::InstCombinerImpl::visitCallInst().
getNonStrictPredicate() [2/2]
CmpInst::Predicate CmpInst::getNonStrictPredicate (Predicate pred) static
This is a static version that you can use without an instruction available.
Returns
the non-strict version of comparison provided in pred. If pred is not a strict comparison predicate, returns pred. Returns the non-strict version of strict comparisons.
Definition at line 3758 of file Instructions.cpp.
References FCMP_OGE, FCMP_OGT, FCMP_OLE, FCMP_OLT, FCMP_UGE, FCMP_UGT, FCMP_ULE, FCMP_ULT, ICMP_SGE, ICMP_SGT, ICMP_SLE, ICMP_SLT, ICMP_UGE, ICMP_UGT, ICMP_ULE, and ICMP_ULT.
getOpcode()
OtherOps llvm::CmpInst::getOpcode () const inline
Get the opcode casted to the right type.
Definition at line 762 of file InstrTypes.h.
References llvm::Instruction::getOpcode().
Referenced by llvm::InstCombinerImpl::foldPHIArgOpIntoPHI(), and llvm::InstCombinerImpl::visitExtractElementInst().
getOrderedPredicate() [1/2]
Predicate llvm::CmpInst::getOrderedPredicate () const inline
Definition at line 802 of file InstrTypes.h.
References getOrderedPredicate(), and getPredicate().
Referenced by getOrderedPredicate().
getOrderedPredicate() [2/2]
Predicate llvm::CmpInst::getOrderedPredicate (Predicate Pred) inline static
Returns the ordered variant of a floating point compare.
For example, UEQ -> OEQ, ULT -> OLT, OEQ -> OEQ
Definition at line 798 of file InstrTypes.h.
References FCMP_ORD.
Referenced by matchIsFiniteTest().
getPredicate()
Predicate llvm::CmpInst::getPredicate () const inline
Return the predicate for this instruction.
Definition at line 767 of file InstrTypes.h.
References llvm::Instruction::getSubclassData().
Referenced by CanGenerateTest(), canonicalizeSaturatedSubtract(), checkOrAndOpImpliedByOther(), llvm::FCmpInst::cloneImpl(), llvm::ICmpInst::cloneImpl(), computeUnlikelySuccessors(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldFCmpToFPClassTest(), llvm::InstCombinerImpl::foldICmpWithCastOp(), llvm::InstCombinerImpl::foldICmpWithTrunc(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldIsPowerOf2(), llvm::InstCombinerImpl::foldPHIArgOpIntoPHI(), foldSelectICmpLshrAshr(), foldSignedTruncationCheck(), getBranchCondString(), getBranchWeights(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::ICmpInst::getCmpPredicate(), llvm::ICmpInst::getFlippedSignednessPredicate(), getFlippedStrictnessPredicate(), getInversePredicate(), getNonStrictPredicate(), getOrderedPredicate(), getSalvageOpsForIcmpOp(), llvm::ICmpInst::getSignedPredicate(), getStrictPredicate(), getSwappedPredicate(), getUnorderedPredicate(), llvm::ICmpInst::getUnsignedPredicate(), handleBrSelExpect(), isCmpSameOrSwapped(), llvm::FCmpInst::isCommutative(), llvm::ICmpInst::isCommutative(), isEqualImpl(), isEquality(), llvm::FCmpInst::isEquality(), llvm::ICmpInst::isEquality(), isEquivalence(), isFalseWhenEqual(), isFPPredicate(), isIntPredicate(), isNonStrictPredicate(), isSigned(), isStrictPredicate(), isTrueWhenEqual(), isUnsigned(), llvm::matchDecomposedSelectPattern(), negateICmpIfUsedByBranchOrSelectOnly(), llvm::FastISel::optimizeCmpPredicate(), OptimizeGlobalAddressOfAllocation(), llvm::LoopStructure::parseLoopStructure(), llvm::IRSimilarity::IRInstructionData::predicateForConsistency(), llvm::InstCombinerImpl::replacedSelectWithOperand(), reuseTableCompare(), simplifyAndOrOfICmpsWithConstants(), llvm::InstCombinerImpl::simplifyRangeCheck(), sinkMinMaxInBB(), and llvm::JumpThreadingPass::tryToUnfoldSelect().
getPredicateName()
StringRef CmpInst::getPredicateName (Predicate P) static
Definition at line 3610 of file Instructions.cpp.
References FCMP_FALSE, FCMP_OEQ, FCMP_OGE, FCMP_OGT, FCMP_OLE, FCMP_OLT, FCMP_ONE, FCMP_ORD, FCMP_TRUE, FCMP_UEQ, FCMP_UGE, FCMP_UGT, FCMP_ULE, FCMP_ULT, FCMP_UNE, FCMP_UNO, ICMP_EQ, ICMP_NE, ICMP_SGE, ICMP_SGT, ICMP_SLE, ICMP_SLT, ICMP_UGE, ICMP_UGT, ICMP_ULE, and ICMP_ULT.
Referenced by llvm::operator<<(), and llvm::VPIRFlags::printFlags().
getStrictPredicate() [1/2]
Predicate llvm::CmpInst::getStrictPredicate () const inline
For example, SGE -> SGT, SLE -> SLT, ULE -> ULT, UGE -> UGT.
Returns the strict version of non-strict comparisons.
Definition at line 860 of file InstrTypes.h.
References getPredicate(), and getStrictPredicate().
Referenced by llvm::decomposeBitTestICmp(), llvm::InstCombinerImpl::foldICmpWithMinMax(), foldICmpXorXX(), getFlippedStrictnessPredicate(), getStrictPredicate(), and simplifyCmpSelOfMaxMin().
getStrictPredicate() [2/2]
CmpInst::Predicate CmpInst::getStrictPredicate (Predicate pred) static
This is a static version that you can use without an instruction available.
Returns
the strict version of comparison provided in pred. If pred is not a strict comparison predicate, returns pred. Returns the strict version of non-strict comparisons.
Definition at line 3735 of file Instructions.cpp.
References FCMP_OGE, FCMP_OGT, FCMP_OLE, FCMP_OLT, FCMP_UGE, FCMP_UGT, FCMP_ULE, FCMP_ULT, ICMP_SGE, ICMP_SGT, ICMP_SLE, ICMP_SLT, ICMP_UGE, ICMP_UGT, ICMP_ULE, and ICMP_ULT.
getSwappedPredicate() [1/2]
Predicate llvm::CmpInst::getSwappedPredicate () const inline
For example, EQ->EQ, SLE->SGE, ULT->UGT, OEQ->OEQ, ULE->UGE, OLT->OGT, etc.
Returns
the predicate that would be the result of exchanging the two operands of the CmpInst instruction without changing the result produced. Return the predicate as if the operands were swapped
Definition at line 829 of file InstrTypes.h.
References getPredicate(), and getSwappedPredicate().
Referenced by llvm::analyzeICmp(), canonicalizeForInvariantConditionInjection(), canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), compareCmp(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), countToEliminateCompares(), evaluateICmpRelation(), extractEquivalentCondition(), foldAbsDiff(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), foldICmpOrXX(), foldICmpWithDominatingICmp(), foldICmpXNegX(), foldICmpXorXX(), foldSelectICmpMinMax(), generateKeySubkey(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::ScalarEvolution::getMonotonicPredicateType(), getOperandsForBranch(), llvm::LazyValueInfo::getPredicateAt(), getSameOpcode(), llvm::CmpPredicate::getSwapped(), llvm::ICmpInst::getSwappedCmpPredicate(), getSwappedPredicate(), hoistAddSub(), hoistMinMax(), hoistSub(), llvm::GCNTTIImpl::instCombineIntrinsic(), isAlternateInstruction(), isCmpSameOrSwapped(), isSameCompare(), legalizeFCmpPredicate(), llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::match(), llvm::CombinerHelper::matchCanonicalizeFCmp(), llvm::CombinerHelper::matchCanonicalizeICmp(), matchClamp(), matchMinMaxOfMinMax(), llvm::CombinerHelper::matchSelectIMinMax(), matchSelectPattern(), matchSelectWithOptionalNotCond(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), llvm::LoopStructure::parseLoopStructure(), llvm::IRSimilarity::IRInstructionData::predicateForConsistency(), simplifyCmpSelOfMaxMin(), simplifyFCmpInst(), simplifyICmpInst(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), llvm::InstCombinerImpl::simplifyRangeCheck(), simplifyUnsignedRangeCheck(), sinkMinMaxInBB(), llvm::FCmpInst::swapOperands(), llvm::ICmpInst::swapOperands(), threadCmpOverPHI(), threadCmpOverSelect(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitFCmpInst().
getSwappedPredicate() [2/2]
CmpInst::Predicate CmpInst::getSwappedPredicate (Predicate pred) static
This is a static version that you can use without an instruction available.
Return the predicate as if the operands were swapped.
Definition at line 3673 of file Instructions.cpp.
References FCMP_FALSE, FCMP_OEQ, FCMP_OGE, FCMP_OGT, FCMP_OLE, FCMP_OLT, FCMP_ONE, FCMP_ORD, FCMP_TRUE, FCMP_UEQ, FCMP_UGE, FCMP_UGT, FCMP_ULE, FCMP_ULT, FCMP_UNE, FCMP_UNO, ICMP_EQ, ICMP_NE, ICMP_SGE, ICMP_SGT, ICMP_SLE, ICMP_SLT, ICMP_UGE, ICMP_UGT, ICMP_ULE, ICMP_ULT, and llvm_unreachable.
getUnorderedPredicate() [1/2]
Predicate llvm::CmpInst::getUnorderedPredicate () const inline
Definition at line 813 of file InstrTypes.h.
References getPredicate(), and getUnorderedPredicate().
Referenced by getUnorderedPredicate().
getUnorderedPredicate() [2/2]
Predicate llvm::CmpInst::getUnorderedPredicate (Predicate Pred) inline static
Returns the unordered variant of a floating point compare.
For example, OEQ -> UEQ, OLT -> ULT, OEQ -> UEQ
Definition at line 809 of file InstrTypes.h.
References FCMP_UNO.
ICmpPredicates()
auto llvm::CmpInst::ICmpPredicates () inline static
Returns the sequence of all ICmp predicates.
Definition at line 724 of file InstrTypes.h.
References llvm::enum_seq_inclusive(), FIRST_ICMP_PREDICATE, llvm::force_iteration_on_noniterable_enum, and LAST_ICMP_PREDICATE.
Referenced by llvm::ICmpInst::predicates().
isCommutative()
bool CmpInst::isCommutative () const
This is just a convenience that dispatches to the subclasses.
Determine if this CmpInst is commutative.
Definition at line 3533 of file Instructions.cpp.
References llvm::cast(), and llvm::dyn_cast().
isEquality() [1/2]
bool llvm::CmpInst::isEquality () const inline
Determine if this is an equals/not equals predicate.
Definition at line 917 of file InstrTypes.h.
References getPredicate(), and isEquality().
Referenced by isEquality(), isRelational(), isRelational(), and llvm::CombinerHelper::matchRedundantBinOpInEquality().
isEquality() [2/2]
bool CmpInst::isEquality (Predicate pred) static
Determine if this is an equals/not equals predicate.
This is a static version that you can use without an instruction available.
Definition at line 3539 of file Instructions.cpp.
References llvm::FCmpInst::isEquality(), llvm::ICmpInst::isEquality(), isFPPredicate(), isIntPredicate(), llvm_unreachable, and P.
Referenced by llvm::ICmpInst::getFlippedSignednessPredicate(), llvm::AArch64GISelUtils::isCMN(), llvm::matchDecomposedSelectPattern(), llvm::CombinerHelper::matchICmpToLHSKnownBits(), llvm::CombinerHelper::matchSelectIMinMax(), and llvm::InstCombinerImpl::visitPHINode().
isEquivalence()
bool CmpInst::isEquivalence (bool Invert = false) const
Determine if one operand of this compare can always be replaced by the other operand, ignoring provenance considerations.
If Invert, check for equivalence with the inverse predicate.
Definition at line 3562 of file Instructions.cpp.
References FCMP_OEQ, FCMP_UEQ, getInversePredicate(), getPredicate(), llvm::Instruction::hasNoNaNs(), hasNonZeroFPOperands(), and ICMP_EQ.
isFalseWhenEqual() [1/2]
bool llvm::CmpInst::isFalseWhenEqual () const inline
This is just a convenience.
Determine if this is false when both operands are the same.
Definition at line 950 of file InstrTypes.h.
References getPredicate(), and isFalseWhenEqual().
Referenced by computePointerICmp(), isFalseWhenEqual(), simplifyFCmpInst(), and llvm::ScalarEvolution::SimplifyICmpOperands().
isFalseWhenEqual() [2/2]
bool CmpInst::isFalseWhenEqual (Predicate predicate) static
Determine if the predicate is false when comparing a value with itself.
Definition at line 3944 of file Instructions.cpp.
References FCMP_FALSE, FCMP_OGT, FCMP_OLT, FCMP_ONE, ICMP_NE, ICMP_SGT, ICMP_SLT, ICMP_UGT, and ICMP_ULT.
isFPPredicate() [1/2]
bool llvm::CmpInst::isFPPredicate () const inline
Definition at line 784 of file InstrTypes.h.
References getPredicate(), and isFPPredicate().
Referenced by llvm::MachineIRBuilder::buildInstr(), llvm::IRBuilderBase::CreateCmp(), llvm::GCNTTIImpl::instCombineIntrinsic(), and isFPPredicate().
isFPPredicate() [2/2]
bool llvm::CmpInst::isFPPredicate (Predicate P) inline static
Definition at line 772 of file InstrTypes.h.
References FIRST_FCMP_PREDICATE, LAST_FCMP_PREDICATE, and P.
Referenced by llvm::ConstantFoldCompareInstOperands(), foldSelectBinOpIdentity(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), llvm::CmpPredicate::getMatching(), isEquality(), lowerFCMPIntrinsic(), llvm::CombinerHelper::matchCanonicalizeFCmp(), matchSelectPattern(), and simplifyFCmpInst().
isIntPredicate() [1/2]
bool llvm::CmpInst::isIntPredicate () const inline
Definition at line 785 of file InstrTypes.h.
References getPredicate(), and isIntPredicate().
Referenced by llvm::MachineIRBuilder::buildInstr(), isIntPredicate(), and llvm::MachineOperand::print().
isIntPredicate() [2/2]
bool llvm::CmpInst::isIntPredicate (Predicate P) inline static
Definition at line 778 of file InstrTypes.h.
References FIRST_ICMP_PREDICATE, LAST_ICMP_PREDICATE, and P.
Referenced by canonicalizeCmpWithConstant(), llvm::CmpPredicate::CmpPredicate(), llvm::ICmpInst::compare(), llvm::ConstantFoldCompareInstruction(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), llvm::ConstantRange::getEquivalentPredWithFlippedSignedness(), llvm::getFlippedStrictnessPredicateAndConstant(), isEquality(), llvm::ARMLegalizerInfo::legalizeCustom(), lowerICMPIntrinsic(), llvm::CombinerHelper::matchCanonicalizeICmp(), matchMinMaxOfMinMax(), matchSelectPattern(), simplifyCmpInst(), and simplifyICmpInst().
isNonStrictPredicate() [1/2]
bool llvm::CmpInst::isNonStrictPredicate () const inline
Returns
true if the comparison predicate is non-strict, false otherwise. Determine if this instruction is using an non-strict comparison predicate.
Definition at line 854 of file InstrTypes.h.
References getPredicate(), and isNonStrictPredicate().
Referenced by getFlippedStrictnessPredicate(), and isNonStrictPredicate().
isNonStrictPredicate() [2/2]
bool CmpInst::isNonStrictPredicate (Predicate predicate) static
This is a static version that you can use without an instruction available.
Returns
true if the comparison predicate is non-strict, false otherwise.
Definition at line 3703 of file Instructions.cpp.
References FCMP_OGE, FCMP_OLE, FCMP_UGE, FCMP_ULE, ICMP_SGE, ICMP_SLE, ICMP_UGE, and ICMP_ULE.
isOrdered()
bool CmpInst::isOrdered (Predicate predicate) static
Determine if the predicate is an ordered operation.
Definition at line 3918 of file Instructions.cpp.
References FCMP_OEQ, FCMP_OGE, FCMP_OGT, FCMP_OLE, FCMP_OLT, FCMP_ONE, and FCMP_ORD.
Referenced by llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::ConstantFPRange::makeAllowedFCmpRegion(), llvm::ConstantFPRange::makeSatisfyingFCmpRegion(), matchSelectPattern(), and simplifyAndOrOfFCmps().
isRelational() [1/2]
bool llvm::CmpInst::isRelational () const inline
Return true if the predicate is relational (not EQ or NE).
Definition at line 928 of file InstrTypes.h.
References isEquality().
isRelational() [2/2]
bool llvm::CmpInst::isRelational (Predicate P) inline static
Return true if the predicate is relational (not EQ or NE).
Definition at line 925 of file InstrTypes.h.
References isEquality(), and P.
Referenced by llvm::ConstantRange::getEquivalentPredWithFlippedSignedness(), and getFlippedStrictnessPredicate().
isSigned() [1/2]
bool llvm::CmpInst::isSigned () const inline
Returns
true if the comparison is signed, false otherwise. Determine if this instruction is using a signed comparison.
Definition at line 932 of file InstrTypes.h.
References getPredicate(), and isSigned().
Referenced by AllUsesOfValueWillTrapIfNull(), llvm::calculateUpperBound(), computePointerICmp(), llvm::ConstantFoldCompareInstOperands(), llvm::decomposeBitTestICmp(), llvm::InstCombinerImpl::foldGEPICmp(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), generateReproducer(), llvm::ICmpInst::getFlippedSignednessPredicate(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::ScalarEvolution::getLoopInvariantExitCondDuringFirstIterationsImpl(), getSalvageOpsForIcmpOp(), hoistAdd(), hoistMinMax(), hoistSub(), llvm::GCNTTIImpl::instCombineIntrinsic(), isImpliedCondICmps(), isImpliedTrueByMatchingCmp(), IsKnownPredicateViaAddRecStart(), isSafeDecreasingBound(), isSafeIncreasingBound(), isSigned(), llvm::MinMaxIntrinsic::isSigned(), isSignTest(), lookThroughCastConst(), lowerICMPIntrinsic(), llvm::LoopStructure::parseLoopStructure(), llvm::predicatesFoldable(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), sinkMinMaxInBB(), llvm::splitLoopBound(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitOr(), and llvm::LegalizerHelper::widenScalar().
isSigned() [2/2]
bool CmpInst::isSigned (Predicate predicate) static
Returns
true if the predicate is signed, false otherwise. Determine if the predicate is an signed operation.
Definition at line 3800 of file Instructions.cpp.
References ICMP_SGE, ICMP_SGT, ICMP_SLE, and ICMP_SLT.
isStrictPredicate() [1/2]
bool llvm::CmpInst::isStrictPredicate () const inline
Returns
true if the comparison predicate is strict, false otherwise. Determine if this instruction is using an strict comparison predicate.
Definition at line 845 of file InstrTypes.h.
References getPredicate(), and isStrictPredicate().
Referenced by getFlippedStrictnessPredicate(), and isStrictPredicate().
isStrictPredicate() [2/2]
bool CmpInst::isStrictPredicate (Predicate predicate) static
This is a static version that you can use without an instruction available.
Returns
true if the comparison predicate is strict, false otherwise.
Definition at line 3719 of file Instructions.cpp.
References FCMP_OGT, FCMP_OLT, FCMP_UGT, FCMP_ULT, ICMP_SGT, ICMP_SLT, ICMP_UGT, and ICMP_ULT.
Referenced by llvm::InstCombinerImpl::foldICmpShlConstant(), and insertCandidatesWithPendingInjections().
isTrueWhenEqual() [1/2]
bool llvm::CmpInst::isTrueWhenEqual () const inline
This is just a convenience.
Determine if this is true when both operands are the same.
Definition at line 944 of file InstrTypes.h.
References getPredicate(), and isTrueWhenEqual().
Referenced by computePointerICmp(), llvm::ConstantFoldCompareInstruction(), llvm::InstCombinerImpl::foldGEPICmp(), isTruePredicate(), isTrueWhenEqual(), simplifyFCmpInst(), simplifyICmpInst(), and llvm::ScalarEvolution::SimplifyICmpOperands().
isTrueWhenEqual() [2/2]
bool CmpInst::isTrueWhenEqual (Predicate predicate) static
Determine if the predicate is true when comparing a value with itself.
Definition at line 3936 of file Instructions.cpp.
References FCMP_TRUE, FCMP_UEQ, FCMP_UGE, FCMP_ULE, ICMP_EQ, ICMP_SGE, ICMP_SLE, ICMP_UGE, and ICMP_ULE.
isUnordered()
bool CmpInst::isUnordered (Predicate predicate) static
Determine if the predicate is an unordered operation.
Definition at line 3927 of file Instructions.cpp.
References FCMP_UEQ, FCMP_UGE, FCMP_UGT, FCMP_ULE, FCMP_ULT, FCMP_UNE, and FCMP_UNO.
Referenced by llvm::ConstantFoldCompareInstruction(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::ConstantFPRange::makeAllowedFCmpRegion(), llvm::ConstantFPRange::makeSatisfyingFCmpRegion(), matchUnorderedInfCompare(), setNaNField(), simplifyAndOrOfFCmps(), and simplifyFCmpInst().
isUnsigned() [1/2]
bool llvm::CmpInst::isUnsigned () const inline
Returns
true if the comparison is unsigned, false otherwise. Determine if this instruction is using an unsigned comparison.
Definition at line 938 of file InstrTypes.h.
References getPredicate(), and isUnsigned().
Referenced by canonicalizeSaturatedSubtract(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpMulConstant(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpWithMinMax(), foldICmpXNegX(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::ICmpInst::getFlippedSignednessPredicate(), injectPendingInvariantConditions(), isUnsigned(), lookThroughCastConst(), simplifyICmpWithBinOp(), simplifyUnsignedRangeCheck(), and llvm::InstCombinerImpl::visitICmpInst().
isUnsigned() [2/2]
bool CmpInst::isUnsigned (Predicate predicate) static
Returns
true if the predicate is unsigned, false otherwise. Determine if the predicate is an unsigned operation.
Definition at line 3792 of file Instructions.cpp.
References ICMP_UGE, ICMP_UGT, ICMP_ULE, and ICMP_ULT.
makeCmpResultType()
Type * llvm::CmpInst::makeCmpResultType (Type * opnd_type) inline static
Create a result type for fcmp/icmp.
Definition at line 984 of file InstrTypes.h.
References llvm::dyn_cast(), llvm::VectorType::get(), llvm::Type::getContext(), and llvm::Type::getInt1Ty().
Referenced by checkAndReplaceCondition(), llvm::VPWidenRecipe::computeCost(), costAndCollectOperands(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::ARMTTIImpl::getCmpSelInstrCost(), getCompareTy(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::getPredForFCmpCode(), llvm::getPredForICmpCode(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateAt(), getPredicateResult(), llvm::BasicTTIImplBase< BasicTTIImpl >::getTreeReductionCost(), llvm::ICmpInst::ICmpInst(), llvm::ICmpInst::ICmpInst(), validateAndCostRequiredSelects(), and llvm::InstCombinerImpl::visitMul().
operator delete()
void llvm::CmpInst::operator delete (void * Ptr) inline
Definition at line 739 of file InstrTypes.h.
References Ptr.
operator new()
void * llvm::CmpInst::operator new (size_t S) inline
Definition at line 738 of file InstrTypes.h.
setPredicate()
void llvm::CmpInst::setPredicate (Predicate P) inline
Set the predicate for this instruction to the specified value.
Definition at line 770 of file InstrTypes.h.
References P, and llvm::Instruction::setSubclassData().
Referenced by CmpInst(), hoistAdd(), hoistSub(), llvm::InvertBranch(), llvm::InstModificationIRStrategy::mutate(), negateICmpIfUsedByBranchOrSelectOnly(), llvm::FCmpInst::swapOperands(), and llvm::ICmpInst::swapOperands().
swapOperands()
void CmpInst::swapOperands ()
This is just a convenience that dispatches to the subclasses.
Swap the operands and adjust predicate accordingly to retain the same comparison.
Definition at line 3526 of file Instructions.cpp.
References llvm::cast(), llvm::dyn_cast(), and swapOperands().
Referenced by swapOperands().
The documentation for this class was generated from the following files:
include/llvm/IR/InstrTypes.h
lib/IR/Instructions.cpp