LLVM: llvm::telemetry::Manager Class Reference
llvm::telemetry::Manager Class Reference
This class is the main interaction point between any LLVM tool and this framework.
#include "llvm/Telemetry/Telemetry.h"
Public Member Functions
Manager ()=default
virtual ~Manager ()=default
Manager (Manager const &)=delete
Manager & operator= (Manager const &)=delete
virtual Error dispatch (TelemetryInfo *Entry)
void addDestination (std::unique_ptr< Destination > Destination)
Protected Member Functions
virtual Error preDispatch (TelemetryInfo *Entry)
Detailed Description
This class is the main interaction point between any LLVM tool and this framework.
It is responsible for collecting telemetry data from the tool being monitored and transmitting the data elsewhere.
Definition at line 145 of file Telemetry.h.
Constructor & Destructor Documentation
Manager() [1/2]
llvm::telemetry::Manager::Manager () default
Referenced by Manager(), and operator=().
~Manager()
virtual llvm::telemetry::Manager::~Manager () virtual default
Manager() [2/2]
llvm::telemetry::Manager::Manager (Manager const &) delete
References Manager().
Member Function Documentation
addDestination()
void llvm::telemetry::Manager::addDestination (std::unique_ptr< Destination > Destination)
Definition at line 36 of file Telemetry.cpp.
Referenced by operator=().
dispatch()
Error llvm::telemetry::Manager::dispatch (TelemetryInfo * Entry) virtual
Definition at line 23 of file Telemetry.cpp.
References assert(), llvm::telemetry::Config::BuildTimeEnableTelemetry, llvm::joinErrors(), preDispatch(), and llvm::Error::success().
Referenced by operator=().
operator=()
Manager & llvm::telemetry::Manager::operator= (Manager const &) delete
References addDestination(), dispatch(), Manager(), and preDispatch().
preDispatch()
Error llvm::telemetry::Manager::preDispatch (TelemetryInfo * Entry) protected virtual
Definition at line 40 of file Telemetry.cpp.
References llvm::Error::success().
Referenced by dispatch(), and operator=().
The documentation for this class was generated from the following files:
include/llvm/Telemetry/Telemetry.h
lib/Telemetry/Telemetry.cpp