LLVM: llvm::DXILResourceBindingInfo Class Reference
llvm::DXILResourceBindingInfo Class Reference
#include "llvm/Analysis/DXILResource.h"
Classes
struct BindingRange
struct BindingSpaces
struct RegisterSpace
Public Member Functions
DXILResourceBindingInfo ()
bool hasImplicitBinding () const
void setHasImplicitBinding (bool Value)
bool hasOverlappingBinding () const
BindingSpaces & getBindingSpaces (dxil::ResourceClass RC)
LLVM_ABI std::optional< uint32_t > findAvailableBinding (dxil::ResourceClass RC, uint32_t Space, int32_t Size)
Friends
class DXILResourceBindingAnalysis
class DXILResourceBindingWrapperPass
Detailed Description
Definition at line 650 of file DXILResource.h.
Constructor & Destructor Documentation
DXILResourceBindingInfo()
llvm::DXILResourceBindingInfo::DXILResourceBindingInfo () inline
Definition at line 685 of file DXILResource.h.
Member Function Documentation
findAvailableBinding()
std::optional< uint32_t > DXILResourceBindingInfo::findAvailableBinding (dxil::ResourceClass RC, uint32_t Space, int32_t Size)
Definition at line 1113 of file DXILResource.cpp.
References llvm::DXILResourceBindingInfo::RegisterSpace::findAvailableBinding(), getBindingSpaces(), llvm::DXILResourceBindingInfo::BindingSpaces::getOrInsertSpace(), and Size.
getBindingSpaces()
BindingSpaces & llvm::DXILResourceBindingInfo::getBindingSpaces (dxil::ResourceClass RC) inline
Definition at line 696 of file DXILResource.h.
References llvm::dxil::CBuffer, llvm_unreachable, llvm::dxil::Sampler, llvm::dxil::SRV, and llvm::dxil::UAV.
Referenced by findAvailableBinding().
hasImplicitBinding()
bool llvm::DXILResourceBindingInfo::hasImplicitBinding () const inline
Definition at line 692 of file DXILResource.h.
Referenced by llvm::DXILResourceImplicitBinding::run().
hasOverlappingBinding()
bool llvm::DXILResourceBindingInfo::hasOverlappingBinding () const inline
Definition at line 694 of file DXILResource.h.
setHasImplicitBinding()
void llvm::DXILResourceBindingInfo::setHasImplicitBinding (bool Value) inline
Definition at line 693 of file DXILResource.h.
Friends And Related Symbol Documentation
DXILResourceBindingAnalysis
friend class DXILResourceBindingAnalysis friend
Definition at line 715 of file DXILResource.h.
References DXILResourceBindingAnalysis.
Referenced by DXILResourceBindingAnalysis.
DXILResourceBindingWrapperPass
friend class DXILResourceBindingWrapperPass friend
Definition at line 716 of file DXILResource.h.
References DXILResourceBindingWrapperPass.
Referenced by DXILResourceBindingWrapperPass.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILResource.h
lib/Analysis/DXILResource.cpp