LLVM: llvm::RawLocationWrapper Class Reference
llvm::RawLocationWrapper Class Reference
Lightweight class that wraps the location operand metadata of a debug intrinsic.
#include "llvm/IR/IntrinsicInst.h"
Public Member Functions
RawLocationWrapper ()=default
RawLocationWrapper (Metadata *RawLocation)
Metadata * getRawLocation () const
LLVM_ABI iterator_range< location_op_iterator > location_ops () const
Get the locations corresponding to the variable referenced by the debug info intrinsic.
LLVM_ABI Value * getVariableLocationOp (unsigned OpIdx) const
unsigned getNumVariableLocationOps () const
bool hasArgList () const
bool isKillLocation (const DIExpression *Expression) const
Friends
bool operator== (const RawLocationWrapper &A, const RawLocationWrapper &B)
bool operator!= (const RawLocationWrapper &A, const RawLocationWrapper &B)
bool operator> (const RawLocationWrapper &A, const RawLocationWrapper &B)
bool operator>= (const RawLocationWrapper &A, const RawLocationWrapper &B)
bool operator< (const RawLocationWrapper &A, const RawLocationWrapper &B)
bool operator<= (const RawLocationWrapper &A, const RawLocationWrapper &B)
Detailed Description
Lightweight class that wraps the location operand metadata of a debug intrinsic.
The raw location may be a ValueAsMetadata, an empty MDTuple, or a DIArgList.
Definition at line 243 of file IntrinsicInst.h.
Constructor & Destructor Documentation
RawLocationWrapper() [1/2]
llvm::RawLocationWrapper::RawLocationWrapper () default
Referenced by operator!=, operator<, operator<=, operator==, operator>, and operator>=.
RawLocationWrapper() [2/2]
llvm::RawLocationWrapper::RawLocationWrapper (Metadata * RawLocation) inline explicit
Definition at line 248 of file IntrinsicInst.h.
References assert(), llvm::cast(), and llvm::isa().
Member Function Documentation
getNumVariableLocationOps()
unsigned llvm::RawLocationWrapper::getNumVariableLocationOps () const inline
Definition at line 262 of file IntrinsicInst.h.
References llvm::cast(), getRawLocation(), and hasArgList().
Referenced by llvm::DbgVariableIntrinsic::getNumVariableLocationOps(), and isKillLocation().
getRawLocation()
Metadata * llvm::RawLocationWrapper::getRawLocation () const inline
Definition at line 256 of file IntrinsicInst.h.
Referenced by getNumVariableLocationOps(), getVariableLocationOp(), hasArgList(), isKillLocation(), and location_ops().
getVariableLocationOp()
Value * RawLocationWrapper::getVariableLocationOp (unsigned OpIdx) const
Definition at line 99 of file IntrinsicInst.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), getRawLocation(), llvm::isa(), and OpIdx.
Referenced by llvm::DbgVariableIntrinsic::getVariableLocationOp().
hasArgList()
bool llvm::RawLocationWrapper::hasArgList () const inline
Definition at line 267 of file IntrinsicInst.h.
References getRawLocation(), and llvm::isa().
Referenced by getNumVariableLocationOps(), llvm::DbgVariableIntrinsic::hasArgList(), and isKillLocation().
isKillLocation()
bool llvm::RawLocationWrapper::isKillLocation (const DIExpression * Expression) const inline
Definition at line 268 of file IntrinsicInst.h.
References llvm::any_of(), getNumVariableLocationOps(), getRawLocation(), hasArgList(), llvm::isa(), and location_ops().
Referenced by llvm::DbgVariableIntrinsic::isKillLocation().
location_ops()
iterator_range< location_op_iterator > RawLocationWrapper::location_ops () const
Get the locations corresponding to the variable referenced by the debug info intrinsic.
DbgVariableIntrinsic - This is the common base class for debug info intrinsics for variables.
Depending on the intrinsic, this could be the variable's value or its address.
Definition at line 74 of file IntrinsicInst.cpp.
References assert(), llvm::dyn_cast(), and getRawLocation().
Referenced by isKillLocation(), and llvm::DbgVariableIntrinsic::location_ops().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const RawLocationWrapper & A, const RawLocationWrapper & B) friend
Definition at line 285 of file IntrinsicInst.h.
References A(), B(), and RawLocationWrapper().
operator<
bool operator< (const RawLocationWrapper & A, const RawLocationWrapper & B) friend
Definition at line 297 of file IntrinsicInst.h.
References A(), B(), and RawLocationWrapper().
operator<=
bool operator<= (const RawLocationWrapper & A, const RawLocationWrapper & B) friend
Definition at line 301 of file IntrinsicInst.h.
References A(), B(), and RawLocationWrapper().
operator==
bool operator== (const RawLocationWrapper & A, const RawLocationWrapper & B) friend
Definition at line 281 of file IntrinsicInst.h.
References A(), B(), and RawLocationWrapper().
operator>
bool operator> (const RawLocationWrapper & A, const RawLocationWrapper & B) friend
Definition at line 289 of file IntrinsicInst.h.
References A(), B(), and RawLocationWrapper().
operator>=
bool operator>= (const RawLocationWrapper & A, const RawLocationWrapper & B) friend
Definition at line 293 of file IntrinsicInst.h.
References A(), B(), and RawLocationWrapper().
The documentation for this class was generated from the following files:
include/llvm/IR/IntrinsicInst.h
lib/IR/IntrinsicInst.cpp