LLVM: llvm::MDBuilder Class Reference
llvm::MDBuilder Class Reference
#include "llvm/IR/MDBuilder.h"
Classes
struct TBAAStructField
Public Types
using PCSection = std::pair<StringRef, SmallVector<Constant *>>
A pair of PC section name with auxilliary constant data.
Public Member Functions
MDBuilder (LLVMContext &context)
LLVM_ABI MDString * createString (StringRef Str)
Return the given string as metadata.
LLVM_ABI ConstantAsMetadata * createConstant (Constant *C)
Return the given constant as metadata.
LLVM_ABI MDNode * createFPMath (float Accuracy)
Return metadata with the given settings.
LLVM_ABI MDNode * createBranchWeights (uint32_t TrueWeight, uint32_t FalseWeight, bool IsExpected=false)
Return metadata containing two branch weights.
LLVM_ABI MDNode * createLikelyBranchWeights ()
Return metadata containing two branch weights, with significant bias towards true destination.
LLVM_ABI MDNode * createUnlikelyBranchWeights ()
Return metadata containing two branch weights, with significant bias towards false destination.
LLVM_ABI MDNode * createBranchWeights (ArrayRef< uint32_t > Weights, bool IsExpected=false)
Return metadata containing a number of branch weights.
LLVM_ABI MDNode * createUnpredictable ()
Return metadata specifying that a branch or switch is unpredictable.
LLVM_ABI MDNode * createFunctionEntryCount (uint64_t Count, bool Synthetic, const DenseSet< GlobalValue::GUID > *Imports)
Return metadata containing the entry Count for a function, a boolean \Synthetic indicating whether the counts were synthetized, and the GUIDs stored in Imports that need to be imported for sample PGO, to enable the same inlines as the profiled optimized binary.
LLVM_ABI MDNode * createGlobalObjectSectionPrefix (StringRef Prefix)
Return metadata containing the section prefix for a global object.
LLVM_ABI MDNode * createPseudoProbeDesc (uint64_t GUID, uint64_t Hash, StringRef FName)
Return metadata containing the pseudo probe descriptor for a function.
LLVM_ABI MDNode * createLLVMStats (ArrayRef< std::pair< StringRef, uint64_t > > LLVMStatsVec)
Return metadata containing llvm statistics.
LLVM_ABI MDNode * createRange (const APInt &Lo, const APInt &Hi)
Return metadata describing the range [Lo, Hi).
LLVM_ABI MDNode * createRange (Constant *Lo, Constant *Hi)
Return metadata describing the range [Lo, Hi).
LLVM_ABI MDNode * createCallees (ArrayRef< Function * > Callees)
Return metadata indicating the possible callees of indirect calls.
LLVM_ABI MDNode * createCallbackEncoding (unsigned CalleeArgNo, ArrayRef< int > Arguments, bool VarArgsArePassed)
Return metadata describing a callback (see llvm::AbstractCallSite).
LLVM_ABI MDNode * mergeCallbackEncodings (MDNode *ExistingCallbacks, MDNode *NewCB)
Merge the new callback encoding NewCB into ExistingCallbacks.
LLVM_ABI MDNode * createRTTIPointerPrologue (Constant *PrologueSig, Constant *RTTI)
Return metadata feeding to the CodeGen about how to generate a function prologue for the "function" santizier.
LLVM_ABI MDNode * createPCSections (ArrayRef< PCSection > Sections)
Return metadata for PC sections.
MDNode * createAnonymousTBAARoot ()
Return metadata appropriate for a TBAA root node.
MDNode * createAnonymousAliasScopeDomain (StringRef Name=StringRef())
Return metadata appropriate for an alias scope domain node.
MDNode * createAnonymousAliasScope (MDNode *Domain, StringRef Name=StringRef())
Return metadata appropriate for an alias scope root node.
LLVM_ABI MDNode * createTBAARoot (StringRef Name)
Return metadata appropriate for a TBAA root node with the given name.
LLVM_ABI MDNode * createAliasScopeDomain (StringRef Name)
Return metadata appropriate for an alias scope domain node with the given name.
LLVM_ABI MDNode * createAliasScope (StringRef Name, MDNode *Domain)
Return metadata appropriate for an alias scope node with the given name.
LLVM_ABI MDNode * createTBAANode (StringRef Name, MDNode *Parent, bool isConstant=false)
Return metadata for a non-root TBAA node with the given name, parent in the TBAA tree, and value for 'pointsToConstantMemory'.
LLVM_ABI MDNode * createTBAAStructNode (ArrayRef< TBAAStructField > Fields)
Return metadata for a tbaa.struct node with the given struct field descriptions.
LLVM_ABI MDNode * createTBAAStructTypeNode (StringRef Name, ArrayRef< std::pair< MDNode *, uint64_t > > Fields)
Return metadata for a TBAA struct node in the type DAG with the given name, a list of pairs (offset, field type in the type DAG).
LLVM_ABI MDNode * createTBAAScalarTypeNode (StringRef Name, MDNode *Parent, uint64_t Offset=0)
Return metadata for a TBAA scalar type node with the given name, an offset and a parent in the TBAA type DAG.
LLVM_ABI MDNode * createTBAAStructTagNode (MDNode *BaseType, MDNode *AccessType, uint64_t Offset, bool IsConstant=false)
Return metadata for a TBAA tag node with the given base type, access type and offset relative to the base type.
LLVM_ABI MDNode * createTBAATypeNode (MDNode *Parent, uint64_t Size, Metadata *Id, ArrayRef< TBAAStructField > Fields=ArrayRef< TBAAStructField >())
Return metadata for a TBAA type node in the TBAA type DAG with the given parent type, size in bytes, type identifier and a list of fields.
LLVM_ABI MDNode * createTBAAAccessTag (MDNode *BaseType, MDNode *AccessType, uint64_t Offset, uint64_t Size, bool IsImmutable=false)
Return metadata for a TBAA access tag with the given base type, final access type, offset of the access relative to the base type, size of the access and flag indicating whether the accessed object can be considered immutable for the purposes of the TBAA analysis.
LLVM_ABI MDNode * createMutableTBAAAccessTag (MDNode *Tag)
Return mutable version of the given mutable or immutable TBAA access tag.
LLVM_ABI MDNode * createIrrLoopHeaderWeight (uint64_t Weight)
Return metadata containing an irreducible loop header weight.
Protected Member Functions
LLVM_ABI MDNode * createAnonymousAARoot (StringRef Name=StringRef(), MDNode *Extra=nullptr)
Return metadata appropriate for a AA root node (scope or TBAA).
Detailed Description
Definition at line 37 of file MDBuilder.h.
Member Typedef Documentation
PCSection
using llvm::MDBuilder::PCSection = std::pair<StringRef, SmallVector<Constant *>>
A pair of PC section name with auxilliary constant data.
Definition at line 147 of file MDBuilder.h.
Constructor & Destructor Documentation
MDBuilder()
llvm::MDBuilder::MDBuilder (LLVMContext & context) inline
Definition at line 41 of file MDBuilder.h.
Member Function Documentation
createAliasScope()
MDNode * MDBuilder::createAliasScope (StringRef Name, MDNode * Domain)
Return metadata appropriate for an alias scope node with the given name.
This may be identified (uniqued) with other scopes with the same name and domain.
Definition at line 233 of file MDBuilder.cpp.
References createString(), and llvm::MDNode::get().
createAliasScopeDomain()
MDNode * MDBuilder::createAliasScopeDomain (StringRef Name)
Return metadata appropriate for an alias scope domain node with the given name.
This may be identified (uniqued) with other roots with the same name.
Definition at line 229 of file MDBuilder.cpp.
References createString(), and llvm::MDNode::get().
createAnonymousAARoot()
MDNode * MDBuilder::createAnonymousAARoot (StringRef Name = StringRef(), MDNode * Extra = nullptr) protected
Return metadata appropriate for a AA root node (scope or TBAA).
Each returned node is distinct from all other metadata and will never be identified (uniqued) with anything else.
Definition at line 195 of file MDBuilder.cpp.
References createString(), llvm::MDNode::getDistinct(), and llvm::MDNode::replaceOperandWith().
Referenced by createAnonymousAliasScope(), createAnonymousAliasScopeDomain(), and createAnonymousTBAARoot().
createAnonymousAliasScope()
MDNode * llvm::MDBuilder::createAnonymousAliasScope (MDNode * Domain, StringRef Name = StringRef()) inline
Return metadata appropriate for an alias scope root node.
Each returned node is distinct from all other metadata and will never be identified (uniqued) with anything else.
Definition at line 181 of file MDBuilder.h.
References createAnonymousAARoot().
Referenced by AddAliasScopeMetadata(), llvm::cloneNoAliasScopes(), llvm::createMemCpyLoopKnownSize(), and llvm::LoopVersioning::prepareNoAliasMetadata().
createAnonymousAliasScopeDomain()
MDNode * llvm::MDBuilder::createAnonymousAliasScopeDomain (StringRef Name = StringRef()) inline
Return metadata appropriate for an alias scope domain node.
Each returned node is distinct from all other metadata and will never be identified (uniqued) with anything else.
Definition at line 174 of file MDBuilder.h.
References createAnonymousAARoot().
Referenced by AddAliasScopeMetadata(), llvm::createMemCpyLoopKnownSize(), and llvm::LoopVersioning::prepareNoAliasMetadata().
createAnonymousTBAARoot()
MDNode * llvm::MDBuilder::createAnonymousTBAARoot () inline
Return metadata appropriate for a TBAA root node.
Each returned node is distinct from all other metadata and will never be identified (uniqued) with anything else.
Definition at line 167 of file MDBuilder.h.
References createAnonymousAARoot().
createBranchWeights() [1/2]
MDNode * MDBuilder::createBranchWeights (ArrayRef< uint32_t > Weights, bool IsExpected = false)
Return metadata containing a number of branch weights.
Parameters
Weights the weights of all the branches
Do these weights come from __builtin_expect*
Definition at line 53 of file MDBuilder.cpp.
References assert(), llvm::MDProfLabels::BranchWeights, createConstant(), createString(), llvm::MDProfLabels::ExpectedBranchWeights, llvm::MDNode::get(), llvm::Type::getInt32Ty(), llvm::Int32Ty, llvm::Offset, and llvm::ArrayRef< T >::size().
createBranchWeights() [2/2]
MDNode * MDBuilder::createBranchWeights (uint32_t TrueWeight, uint32_t FalseWeight, bool IsExpected = false)
Return metadata containing two branch weights.
Parameters
TrueWeight the weight of the true branch
FalseWeight the weight of the false branch
Do these weights come from __builtin_expect*
Definition at line 38 of file MDBuilder.cpp.
References createBranchWeights().
Referenced by llvm::VPlanTransforms::addBranchWeightToMiddleTerminator(), llvm::VPlanTransforms::attachCheckBlock(), llvm::SwitchInstProfUpdateWrapper::buildProfBranchWeightsMD(), CloneLoopBlocks(), ConnectEpilog(), ConnectProlog(), llvm::ConstantFoldTerminator(), createBranchWeights(), createBranchWeights(), llvm::createCallMatchingInvoke(), createLikelyBranchWeights(), createUnlikelyBranchWeights(), handleBrSelExpect(), handlePhiDef(), InsertStackProtectors(), llvm::makeGuardControlFlowExplicit(), llvm::setBranchWeights(), setBranchWeights(), setBranchWeights(), llvm::setLoopEstimatedTripCount(), simplifySwitchOfCmpIntrinsic(), and llvm::UnrollRuntimeLoopRemainder().
createCallbackEncoding()
MDNode * MDBuilder::createCallbackEncoding (unsigned CalleeArgNo, ArrayRef< int > Arguments, bool VarArgsArePassed)
Return metadata describing a callback (see llvm::AbstractCallSite).
Definition at line 119 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, Arguments, createConstant(), llvm::MDNode::get(), llvm::Type::getInt1Ty(), llvm::Type::getInt64Ty(), Int1, and Int64.
Referenced by hostParallelCallback().
createCallees()
MDNode * MDBuilder::createCallees (ArrayRef< Function * > Callees)
Return metadata indicating the possible callees of indirect calls.
Definition at line 112 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, createConstant(), F, and llvm::MDNode::get().
Referenced by runCVP().
createConstant()
ConstantAsMetadata * MDBuilder::createConstant (Constant * C)
Return the given constant as metadata.
Definition at line 25 of file MDBuilder.cpp.
References llvm::CallingConv::C, and llvm::ConstantAsMetadata::get().
Referenced by addModuleFlags(), llvm::annotateValueSite(), createBranchWeights(), createCallbackEncoding(), createCallees(), createFPMath(), createFunctionEntryCount(), createIrrLoopHeaderWeight(), createLLVMStats(), createPCSections(), createPseudoProbeDesc(), createRange(), createRTTIPointerPrologue(), createTBAAAccessTag(), createTBAANode(), createTBAAScalarTypeNode(), createTBAAStructNode(), createTBAAStructTagNode(), createTBAAStructTypeNode(), createTBAATypeNode(), lowerKernelArguments(), llvm::scaleProfData(), llvm::setKCFIType(), and translateBranchMetadata().
createFPMath()
MDNode * MDBuilder::createFPMath (float Accuracy)
Return metadata with the given settings.
The special value 0.0 for the Accuracy parameter indicates the default (maximal precision) setting.
Definition at line 29 of file MDBuilder.cpp.
References assert(), createConstant(), llvm::MDNode::get(), and llvm::Type::getFloatTy().
createFunctionEntryCount()
MDNode * MDBuilder::createFunctionEntryCount (uint64_t Count, bool Synthetic, const DenseSet< GlobalValue::GUID > * Imports)
Return metadata containing the entry Count for a function, a boolean \Synthetic indicating whether the counts were synthetized, and the GUIDs stored in Imports that need to be imported for sample PGO, to enable the same inlines as the profiled optimized binary.
Definition at line 72 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::Count, createConstant(), createString(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), llvm::MDProfLabels::FunctionEntryCount, llvm::MDNode::get(), llvm::Type::getInt64Ty(), llvm::sort(), and llvm::MDProfLabels::SyntheticFunctionEntryCount.
createGlobalObjectSectionPrefix()
MDNode * MDBuilder::createGlobalObjectSectionPrefix (StringRef Prefix)
Return metadata containing the section prefix for a global object.
Definition at line 91 of file MDBuilder.cpp.
References createString(), and llvm::MDNode::get().
Referenced by llvm::GlobalObject::setSectionPrefix().
createIrrLoopHeaderWeight()
MDNode * MDBuilder::createIrrLoopHeaderWeight (uint64_t Weight)
Return metadata containing an irreducible loop header weight.
Definition at line 343 of file MDBuilder.cpp.
References createConstant(), createString(), llvm::MDNode::get(), and llvm::Type::getInt64Ty().
Referenced by llvm::setIrrLoopHeaderMetadata().
createLikelyBranchWeights()
MDNode * MDBuilder::createLikelyBranchWeights ()
Return metadata containing two branch weights, with significant bias towards true destination.
Definition at line 43 of file MDBuilder.cpp.
References createBranchWeights().
createLLVMStats()
MDNode * MDBuilder::createLLVMStats (ArrayRef< std::pair< StringRef, uint64_t > > LLVMStatsVec)
Return metadata containing llvm statistics.
Definition at line 362 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, createConstant(), createString(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), and I.
createMutableTBAAAccessTag()
MDNode * MDBuilder::createMutableTBAAAccessTag (MDNode * Tag)
Return mutable version of the given mutable or immutable TBAA access tag.
Definition at line 316 of file MDBuilder.cpp.
References llvm::cast(), createTBAAAccessTag(), createTBAAStructTagNode(), llvm::mdconst::extract(), llvm::MDNode::getOperand(), llvm::isa(), llvm::Offset, Size, and llvm::Tag.
createPCSections()
MDNode * MDBuilder::createPCSections (ArrayRef< PCSection > Sections)
Return metadata for PC sections.
Definition at line 174 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::CallingConv::C, createConstant(), createString(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::MDNode::get(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
createPseudoProbeDesc()
MDNode * MDBuilder::createPseudoProbeDesc (uint64_t GUID, uint64_t Hash, StringRef FName)
Return metadata containing the pseudo probe descriptor for a function.
Definition at line 351 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, createConstant(), createString(), llvm::MDNode::get(), and llvm::Type::getInt64Ty().
Referenced by llvm::SampleProfileProber::instrumentOneFunc().
createRange() [1/2]
MDNode * MDBuilder::createRange (const APInt & Lo, const APInt & Hi)
Return metadata describing the range [Lo, Hi).
Definition at line 96 of file MDBuilder.cpp.
References assert(), createRange(), llvm::IntegerType::get(), llvm::Hi, and llvm::Lo.
Referenced by annotateGridSizeLoadWithRangeMD(), llvm::copyNonnullMetadata(), createRange(), llvm::SITargetLowering::emitExpandAtomicAddrSpacePredicate(), lowerKernelArguments(), llvm::AMDGPUSubtarget::makeLIDRangeMetadata(), and upgradeAMDGCNIntrinsicCall().
createRange() [2/2]
MDNode * MDBuilder::createRange (Constant * Lo, Constant * Hi)
Return metadata describing the range [Lo, Hi).
Definition at line 103 of file MDBuilder.cpp.
References createConstant(), llvm::MDNode::get(), llvm::Hi, and llvm::Lo.
createRTTIPointerPrologue()
MDNode * MDBuilder::createRTTIPointerPrologue (Constant * PrologueSig, Constant * RTTI)
Return metadata feeding to the CodeGen about how to generate a function prologue for the "function" santizier.
Definition at line 166 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, createConstant(), and llvm::MDNode::get().
createString()
MDString * MDBuilder::createString (StringRef Str)
Return the given string as metadata.
Definition at line 21 of file MDBuilder.cpp.
References llvm::MDString::get().
Referenced by llvm::Instruction::addAnnotationMetadata(), llvm::Instruction::addAnnotationMetadata(), annotateFunctionWithHashMismatch(), llvm::annotateValueSite(), createAliasScope(), createAliasScopeDomain(), createAnonymousAARoot(), createBranchWeights(), createFunctionEntryCount(), createGlobalObjectSectionPrefix(), createIrrLoopHeaderWeight(), createLLVMStats(), createPCSections(), createPseudoProbeDesc(), createTBAANode(), createTBAARoot(), createTBAAScalarTypeNode(), createTBAAStructTypeNode(), llvm::setExplicitlyUnknownBranchWeights(), and translateBranchMetadata().
createTBAAAccessTag()
MDNode * MDBuilder::createTBAAAccessTag (MDNode * BaseType, MDNode * AccessType, uint64_t Offset, uint64_t Size, bool IsImmutable = false)
Return metadata for a TBAA access tag with the given base type, final access type, offset of the access relative to the base type, size of the access and flag indicating whether the accessed object can be considered immutable for the purposes of the TBAA analysis.
Definition at line 302 of file MDBuilder.cpp.
References createConstant(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), Int64, llvm::Offset, and Size.
Referenced by createMutableTBAAAccessTag().
createTBAANode()
MDNode * MDBuilder::createTBAANode (StringRef Name, MDNode * Parent, bool isConstant = false)
Return metadata for a non-root TBAA node with the given name, parent in the TBAA tree, and value for 'pointsToConstantMemory'.
Definition at line 219 of file MDBuilder.cpp.
References createConstant(), createString(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), and isConstant().
createTBAARoot()
MDNode * MDBuilder::createTBAARoot (StringRef Name)
Return metadata appropriate for a TBAA root node with the given name.
This may be identified (uniqued) with other roots with the same name.
Definition at line 213 of file MDBuilder.cpp.
References createString(), and llvm::MDNode::get().
createTBAAScalarTypeNode()
MDNode * MDBuilder::createTBAAScalarTypeNode (StringRef Name, MDNode * Parent, uint64_t Offset = 0)
Return metadata for a TBAA scalar type node with the given name, an offset and a parent in the TBAA type DAG.
Definition at line 266 of file MDBuilder.cpp.
References createConstant(), createString(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), and llvm::Offset.
createTBAAStructNode()
MDNode * MDBuilder::createTBAAStructNode (ArrayRef< TBAAStructField > Fields)
Return metadata for a tbaa.struct node with the given struct field descriptions.
Definition at line 239 of file MDBuilder.cpp.
References createConstant(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), Int64, llvm::Offset, Size, and llvm::ArrayRef< T >::size().
createTBAAStructTagNode()
MDNode * MDBuilder::createTBAAStructTagNode (MDNode * BaseType, MDNode * AccessType, uint64_t Offset, bool IsConstant = false)
Return metadata for a TBAA tag node with the given base type, access type and offset relative to the base type.
Definition at line 275 of file MDBuilder.cpp.
References createConstant(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), Int64, and llvm::Offset.
Referenced by createMutableTBAAAccessTag().
createTBAAStructTypeNode()
MDNode * MDBuilder::createTBAAStructTypeNode (StringRef Name, ArrayRef< std::pair< MDNode *, uint64_t > > Fields)
Return metadata for a TBAA struct node in the type DAG with the given name, a list of pairs (offset, field type in the type DAG).
Definition at line 252 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, createConstant(), createString(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), and Int64.
createTBAATypeNode()
MDNode * MDBuilder::createTBAATypeNode (MDNode * Parent, uint64_t Size, Metadata * Id, ArrayRef< TBAAStructField > Fields = ArrayRef<TBAAStructField>())
Return metadata for a TBAA type node in the TBAA type DAG with the given parent type, size in bytes, type identifier and a list of fields.
Definition at line 286 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, createConstant(), llvm::MDNode::get(), llvm::Type::getInt64Ty(), I, Int64, llvm::Offset, Size, and llvm::ArrayRef< T >::size().
createUnlikelyBranchWeights()
MDNode * MDBuilder::createUnlikelyBranchWeights ()
Return metadata containing two branch weights, with significant bias towards false destination.
Definition at line 48 of file MDBuilder.cpp.
References createBranchWeights().
Referenced by llvm::AMDGPU::genAMDGPUReportBlock(), and llvm::KCFIPass::run().
createUnpredictable()
MDNode * MDBuilder::createUnpredictable ()
Return metadata specifying that a branch or switch is unpredictable.
Definition at line 70 of file MDBuilder.cpp.
References llvm::MDNode::get().
mergeCallbackEncodings()
MDNode * MDBuilder::mergeCallbackEncodings (MDNode * ExistingCallbacks, MDNode * NewCB)
Merge the new callback encoding NewCB into ExistingCallbacks.
Definition at line 136 of file MDBuilder.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::cast(), llvm::MDNode::get(), llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
The documentation for this class was generated from the following files:
include/llvm/IR/MDBuilder.h
lib/IR/MDBuilder.cpp