LLVM: RAGreedyPass Class Reference
RAGreedyPass Class Reference
#include "llvm/CodeGen/RegAllocGreedyPass.h"
Classes
struct Options
Public Member Functions
RAGreedyPass (Options Opts=Options())
PreservedAnalyses run (MachineFunction &F, MachineFunctionAnalysisManager &AM)
MachineFunctionProperties getRequiredProperties () const
MachineFunctionProperties getClearedProperties () const
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName) const
Public Member Functions inherited from llvm::PassInfoMixin< RAGreedyPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< RAGreedyPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 18 of file RegAllocGreedyPass.h.
Constructor & Destructor Documentation
RAGreedyPass()
RAGreedyPass::RAGreedyPass (Options Opts = Options()) inline
Definition at line 27 of file RegAllocGreedyPass.h.
References llvm::move().
Member Function Documentation
getClearedProperties()
MachineFunctionProperties RAGreedyPass::getClearedProperties () const inline
Definition at line 34 of file RegAllocGreedyPass.h.
getRequiredProperties()
MachineFunctionProperties RAGreedyPass::getRequiredProperties () const inline
Definition at line 30 of file RegAllocGreedyPass.h.
isRequired()
bool RAGreedyPass::isRequired () inline static
Definition at line 41 of file RegAllocGreedyPass.h.
printPipeline()
void RAGreedyPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName) const
Definition at line 218 of file RegAllocGreedy.cpp.
References llvm::StringRef::empty().
run()
PreservedAnalyses RAGreedyPass::run (MachineFunction & F, MachineFunctionAnalysisManager & AM)
Definition at line 244 of file RegAllocGreedy.cpp.
References _, llvm::PreservedAnalyses::all(), Changed, and llvm::getMachineFunctionPassPreservedAnalyses().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegAllocGreedyPass.h
lib/CodeGen/RegAllocGreedy.cpp