LLVM: llvm::codeview::UsingNamespaceSym Class Reference
llvm::codeview::UsingNamespaceSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
UsingNamespaceSym (SymbolRecordKind Kind)
UsingNamespaceSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 1011 of file SymbolRecord.h.
Constructor & Destructor Documentation
UsingNamespaceSym() [1/2]
llvm::codeview::UsingNamespaceSym::UsingNamespaceSym (SymbolRecordKind Kind) inline explicit
Definition at line 1013 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by UsingNamespaceSym().
UsingNamespaceSym() [2/2]
llvm::codeview::UsingNamespaceSym::UsingNamespaceSym (uint32_t RecordOffset) inline explicit
Definition at line 1014 of file SymbolRecord.h.
References RecordOffset, llvm::codeview::SymbolRecord::SymbolRecord(), and UsingNamespaceSym().
Member Data Documentation
Name
StringRef llvm::codeview::UsingNamespaceSym::Name
Definition at line 1018 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
RecordOffset
uint32_t llvm::codeview::UsingNamespaceSym::RecordOffset = 0
Definition at line 1020 of file SymbolRecord.h.
Referenced by UsingNamespaceSym().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h