LLVM: llvm::StringMapImpl Class Reference
llvm::StringMapImpl Class Reference
StringMapImpl - This is the base class of StringMap that is shared among all of its instantiations.
#include "llvm/ADT/StringMap.h"
Inherited by llvm::StringMap< std::nullopt_t, AllocatorTy >, llvm::StringMap< std::unique_ptr< InlineGraphNode > >, llvm::StringMap< const TargetRegisterClass * >, llvm::StringMap< const RegisterBank * >, llvm::StringMap< DwarfStringPoolEntry, BumpPtrAllocator >, llvm::StringMap< size_t, BumpPtrAllocator >, llvm::StringMap< uint64_t >, llvm::StringMap< Symbol * >, llvm::StringMap< std::pair< ExecutorAddr, JITSymbolFlags > >, llvm::StringMap< RefCountType >, llvm::StringMap< State >, llvm::StringMap< OffloadEntryInfoDeviceGlobalVar >, llvm::StringMap< Comdat >, llvm::StringMap< NamedMDNode * >, llvm::StringMap< ModuleHash >, llvm::StringMap< Value * >, llvm::StringMap< MCSymbolTableValue, BumpPtrAllocator & >, llvm::StringMap< const PassInfo * >, llvm::StringMap< StringMap< Matcher > >, llvm::StringMap< std::pair< HNode *, SMRange > >, llvm::StringMap< RecordLoc >, llvm::StringMap< ProbeFactorMap >, llvm::StringMap< SymbolTableEntry >, llvm::const_iterator< State >, llvm::StringMap< T >, llvm::StringMap< std::nullopt_t, MallocAllocator >, llvm::StringMap< llvm::DenseSet< llvm::ValueInfo > >, llvm::StringMap< std::unique_ptr< llvm::AArch64Subtarget > >, llvm::StringMap< std::unique_ptr< llvm::ARMSubtarget > >, llvm::StringMap< llvm::SmallVector< size_t, 1 > >, llvm::StringMap< std::vector< std::string > >, llvm::StringMap< llvm::SmallString< 128 > >, llvm::StringMap< llvm::FunctionPathAndClusterInfo >, llvm::StringMap< llvm::StringRef >, llvm::StringMap< std::unique_ptr< llvm::CSKYSubtarget > >, llvm::StringMap< unsigned >, llvm::StringMap< uint32_t >, llvm::StringMap< std::string >, llvm::StringMap< const llvm::DIE * >, llvm::StringMap< llvm::DwarfStringPoolEntry, llvm::BumpPtrAllocatorImpl & >, llvm::StringMap< bool >, llvm::StringMap< llvm::NumericVariable * >, llvm::StringMap< llvm::GCStrategy * >, llvm::StringMap< std::unique_ptr< llvm::GCNSubtarget > >, llvm::StringMap< std::unique_ptr< llvm::HexagonSubtarget > >, llvm::StringMap< llvm::SmallDenseMap< uint64_t, InstrProfRecord > >, llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >, llvm::StringMap< llvm::MDString, llvm::BumpPtrAllocatorImpl >, llvm::StringMap< std::unique_ptr< llvm::ConstantDataSequential > >, llvm::StringMap< llvm::StructType * >, llvm::StringMap< uint8_t >, llvm::StringMap< GlobalValue::LinkageTypes >, llvm::StringMap< NameAndAttributes >, llvm::StringMap< size_t >, llvm::StringMap< std::unique_ptr< llvm::LoongArchSubtarget > >, llvm::StringMap< std::unique_ptr< llvm::M68kSubtarget > >, llvm::StringMap< llvm::MCSymbol *, llvm::BumpPtrAllocatorImpl & >, llvm::StringMap< llvm::MCSectionMachO * >, llvm::StringMap< llvm::MCSectionELF * >, llvm::StringMap< llvm::MCSectionDXContainer * >, llvm::StringMap< llvm::MCAsmMacro >, llvm::StringMap< std::unique_ptr< llvm::MipsSubtarget > >, llvm::StringMap< std::unique_ptr< llvm::PPCSubtarget > >, llvm::StringMap< NumericVariableMatch >, llvm::StringMap< llvm::VRegInfo * >, llvm::StringMap< llvm::Register >, llvm::StringMap< const uint32_t * >, llvm::StringMap< int >, llvm::StringMap< MachineMemOperand::Flags >, llvm::StringMap< std::unique_ptr< const llvm::ExternalSymbolPseudoSourceValue > >, llvm::StringMap< std::unique_ptr< llvm::R600Subtarget > >, llvm::StringMap< llvm::MCSymbol * >, llvm::StringMap< std::unique_ptr< llvm::RISCVSubtarget > >, llvm::StringMap< llvm::SmallVector< RelocationEntry, 64 > >, llvm::StringMap< LocToLocMap >, llvm::StringMap< std::unordered_map< llvm::sampleprof::LineLocation, MatchState, llvm::sampleprof::LineLocationHash > >, llvm::StringMap< llvm::SDNode * >, llvm::StringMap< std::unique_ptr< llvm::SetTheory::Operator > >, llvm::StringMap< std::unique_ptr< llvm::SetTheory::Expander > >, llvm::StringMap< llvm::Type * >, llvm::StringMap< std::unique_ptr< llvm::SparcSubtarget > >, llvm::StringMap< std::unique_ptr< llvm::SystemZSubtarget > >, llvm::StringMap< llvm::SmallVector< std::unique_ptr< Timer >, 4 > >, llvm::StringMap< CountAndDurationType >, llvm::StringMap< std::unique_ptr< llvm::WebAssemblySubtarget > >, llvm::StringMap< std::unique_ptr< llvm::X86Subtarget > >, llvm::StringMap< std::unique_ptr< llvm::XtensaSubtarget > >, llvm::StringMap< llvm::cl::Option * >, llvm::StringMap< std::vector< llvm::support::detail::packed_endian_specific_integral< uint32_t, llvm::endianness::little, unaligned > > >, llvm::StringMap< const llvm::StringInit *, llvm::BumpPtrAllocatorImpl & >, llvm::StringMap< llvm::StringMapEntry< std::nullopt_t > * >, llvm::StringMap< SectionParserFunction >, llvm::StringMap< AstPtr >, llvm::StringMap< Lambda >, llvm::StringMap< SectionLambda >, llvm::StringMap< llvm::objcopy::SectionRename >, llvm::StringMap< llvm::objcopy::SectionFlagsUpdate >, llvm::StringMap< std::unique_ptr< llvm::orc::DebugObjectSection > >, llvm::StringMap< std::vector< char > >, llvm::StringMap< llvm::orc::ExecutorAddr >, llvm::StringMap< std::pair< StubKey, llvm::JITSymbolFlags > >, llvm::StringMap< llvm::codeview::FileChecksumEntry >, llvm::StringMap< unsigned, llvm::BumpPtrAllocatorImpl >, and llvm::StringMap< ValueTy, AllocatorTy >.
Public Member Functions
unsigned getNumBuckets () const
unsigned getNumItems () const
bool empty () const
unsigned size () const
void swap (StringMapImpl &Other)
Static Public Member Functions
static StringMapEntryBase * getTombstoneVal ()
static LLVM_ABI uint32_t hash (StringRef Key)
Returns the hash value that will be used for the given string.
Static Public Attributes
static constexpr uintptr_t TombstoneIntVal
Protected Member Functions
StringMapImpl (unsigned itemSize)
StringMapImpl (StringMapImpl &&RHS)
LLVM_ABI StringMapImpl (unsigned InitSize, unsigned ItemSize)
~StringMapImpl ()
LLVM_ABI unsigned RehashTable (unsigned BucketNo=0)
RehashTable - Grow the table, redistributing values into the buckets with the appropriate mod-of-hashtable-size.
unsigned LookupBucketFor (StringRef Key)
LookupBucketFor - Look up the bucket that the specified string should end up in.
LLVM_ABI unsigned LookupBucketFor (StringRef Key, uint32_t FullHashValue)
Overload that explicitly takes precomputed hash(Key).
int FindKey (StringRef Key) const
FindKey - Look up the bucket that contains the specified key.
LLVM_ABI int FindKey (StringRef Key, uint32_t FullHashValue) const
Overload that explicitly takes precomputed hash(Key).
LLVM_ABI void RemoveKey (StringMapEntryBase *V)
RemoveKey - Remove the specified StringMapEntry from the table, but do not delete it.
LLVM_ABI StringMapEntryBase * RemoveKey (StringRef Key)
RemoveKey - Remove the StringMapEntry for the specified key from the table, returning it.
LLVM_ABI void init (unsigned Size)
Allocate the table with the specified number of buckets and otherwise setup the map as empty.
Protected Attributes
StringMapEntryBase ** TheTable = nullptr
unsigned NumBuckets = 0
unsigned NumItems = 0
unsigned NumTombstones = 0
unsigned ItemSize
Detailed Description
StringMapImpl - This is the base class of StringMap that is shared among all of its instantiations.
Definition at line 33 of file StringMap.h.
Constructor & Destructor Documentation
StringMapImpl() [1/3]
llvm::StringMapImpl::StringMapImpl (unsigned itemSize) inline explicit protected
Definition at line 45 of file StringMap.h.
References ItemSize.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), StringMapImpl(), and swap().
StringMapImpl() [2/3]
llvm::StringMapImpl::StringMapImpl (StringMapImpl && RHS) inline protected
Definition at line 46 of file StringMap.h.
References ItemSize, NumBuckets, NumItems, NumTombstones, RHS, StringMapImpl(), and TheTable.
StringMapImpl() [3/3]
StringMapImpl::StringMapImpl (unsigned InitSize, unsigned ItemSize) protected
Definition at line 48 of file StringMap.cpp.
References getMinBucketToReserveForEntries(), init(), ItemSize, NumBuckets, NumItems, NumTombstones, and TheTable.
~StringMapImpl()
llvm::StringMapImpl::~StringMapImpl () inline protected
Definition at line 57 of file StringMap.h.
References TheTable.
Member Function Documentation
empty()
bool llvm::StringMapImpl::empty () const inline
Definition at line 104 of file StringMap.h.
References NumItems.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::clear(), handleArgs(), llvm::RISCVISAInfo::printEnabledExtensions(), llvm::ARM::PrintSupportedExtensions(), llvm::RISCVISAInfo::printSupportedExtensions(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::~StringMap().
FindKey() [1/2]
int llvm::StringMapImpl::FindKey (StringRef Key) const inline protected
FindKey - Look up the bucket that contains the specified key.
If it exists in the map, return the bucket number of the key. Otherwise return -1. This does not modify the map.
Definition at line 75 of file StringMap.h.
References FindKey(), hash(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::StringSet< AllocatorTy >::contains(), llvm::StringMap< std::nullopt_t, AllocatorTy >::find(), llvm::StringMap< std::nullopt_t, AllocatorTy >::find(), FindKey(), and RemoveKey().
FindKey() [2/2]
int StringMapImpl::FindKey (StringRef Key, uint32_t FullHashValue) const protected
Overload that explicitly takes precomputed hash(Key).
FindKey - Look up the bucket that contains the specified key.
If it exists in the map, return the bucket number of the key. Otherwise return -1. This does not modify the map.
Definition at line 147 of file StringMap.cpp.
References assert(), getHashTable(), llvm::StringMapEntryBase::getKeyLength(), getTombstoneVal(), hash(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, ItemSize, LLVM_LIKELY, NumBuckets, llvm::shouldReverseIterate(), and TheTable.
getNumBuckets()
unsigned llvm::StringMapImpl::getNumBuckets () const inline
Definition at line 101 of file StringMap.h.
References NumBuckets.
getNumItems()
unsigned llvm::StringMapImpl::getNumItems () const inline
Definition at line 102 of file StringMap.h.
References NumItems.
getTombstoneVal()
StringMapEntryBase * llvm::StringMapImpl::getTombstoneVal () inline static
Definition at line 97 of file StringMap.h.
References TombstoneIntVal.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::clear(), FindKey(), llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), LookupBucketFor(), RehashTable(), RemoveKey(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace_with_hash(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::~StringMap().
hash()
uint32_t StringMapImpl::hash (StringRef Key) static
Returns the hash value that will be used for the given string.
This allows precomputing the value and passing it explicitly to some of the functions. The implementation of this function is not guaranteed to be stable and may change.
Definition at line 46 of file StringMap.cpp.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::xxh3_64bits().
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::find(), llvm::StringMap< std::nullopt_t, AllocatorTy >::find(), FindKey(), FindKey(), llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), LookupBucketFor(), LookupBucketFor(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace().
init()
void StringMapImpl::init (unsigned Size) protected
Allocate the table with the specified number of buckets and otherwise setup the map as empty.
Definition at line 67 of file StringMap.cpp.
References assert(), createTable(), NumBuckets, NumItems, NumTombstones, and TheTable.
Referenced by LookupBucketFor(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), and StringMapImpl().
LookupBucketFor() [1/2]
unsigned llvm::StringMapImpl::LookupBucketFor (StringRef Key) inline protected
LookupBucketFor - Look up the bucket that the specified string should end up in.
If it already exists as a key in the map, the Item pointer for the specified bucket will be non-null. Otherwise, it will be null. In either case, the FullHashValue field of the bucket will be set to the hash value of the string.
Definition at line 65 of file StringMap.h.
References hash(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and LookupBucketFor().
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), LookupBucketFor(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace_with_hash().
LookupBucketFor() [2/2]
unsigned StringMapImpl::LookupBucketFor (StringRef Name, uint32_t FullHashValue) protected
Overload that explicitly takes precomputed hash(Key).
LookupBucketFor - Look up the bucket that the specified string should end up in.
If it already exists as a key in the map, the Item pointer for the specified bucket will be non-null. Otherwise, it will be null. In either case, the FullHashValue field of the bucket will be set to the hash value of the string.
Definition at line 86 of file StringMap.cpp.
References assert(), getHashTable(), llvm::StringMapEntryBase::getKeyLength(), getTombstoneVal(), hash(), init(), ItemSize, LLVM_LIKELY, NumBuckets, llvm::shouldReverseIterate(), and TheTable.
RehashTable()
unsigned StringMapImpl::RehashTable (unsigned BucketNo = 0) protected
RehashTable - Grow the table, redistributing values into the buckets with the appropriate mod-of-hashtable-size.
Definition at line 218 of file StringMap.cpp.
References createTable(), getHashTable(), getTombstoneVal(), I, LLVM_UNLIKELY, NumBuckets, NumItems, NumTombstones, and TheTable.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace_with_hash().
RemoveKey() [1/2]
void StringMapImpl::RemoveKey (StringMapEntryBase * V) protected
RemoveKey - Remove the specified StringMapEntry from the table, but do not delete it.
This aborts if the value isn't in the table.
Definition at line 193 of file StringMap.cpp.
References assert(), ItemSize, and RemoveKey().
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::remove(), and RemoveKey().
RemoveKey() [2/2]
StringMapEntryBase * StringMapImpl::RemoveKey (StringRef Key) protected
RemoveKey - Remove the StringMapEntry for the specified key from the table, returning it.
If the key is not in the table, this returns null.
Definition at line 202 of file StringMap.cpp.
References assert(), FindKey(), getTombstoneVal(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, NumBuckets, NumItems, NumTombstones, and TheTable.
size()
unsigned llvm::StringMapImpl::size () const inline
Definition at line 105 of file StringMap.h.
References NumItems.
Referenced by llvm::orc::LocalIndirectStubsManager< TargetT >::createStubs(), llvm::StringMap< std::nullopt_t, AllocatorTy >::operator==(), ProcessThinLTOModule(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), and llvm::TimeTraceProfiler::write().
swap()
void llvm::StringMapImpl::swap (StringMapImpl & Other) inline
Definition at line 114 of file StringMap.h.
References NumBuckets, NumItems, NumTombstones, llvm::Other, StringMapImpl(), std::swap(), and TheTable.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::operator=().
Member Data Documentation
ItemSize
unsigned llvm::StringMapImpl::ItemSize protected
Definition at line 42 of file StringMap.h.
Referenced by FindKey(), LookupBucketFor(), RemoveKey(), StringMapImpl(), StringMapImpl(), and StringMapImpl().
NumBuckets
unsigned llvm::StringMapImpl::NumBuckets = 0 protected
Definition at line 39 of file StringMap.h.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::begin(), llvm::StringMap< std::nullopt_t, AllocatorTy >::begin(), llvm::StringMap< std::nullopt_t, AllocatorTy >::clear(), llvm::StringMap< std::nullopt_t, AllocatorTy >::end(), llvm::StringMap< std::nullopt_t, AllocatorTy >::end(), FindKey(), getNumBuckets(), init(), llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), LookupBucketFor(), RehashTable(), RemoveKey(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), StringMapImpl(), StringMapImpl(), swap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace_with_hash(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::~StringMap().
NumItems
unsigned llvm::StringMapImpl::NumItems = 0 protected
Definition at line 40 of file StringMap.h.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::clear(), empty(), getNumItems(), init(), llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), RehashTable(), RemoveKey(), size(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), StringMapImpl(), StringMapImpl(), swap(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace_with_hash().
NumTombstones
unsigned llvm::StringMapImpl::NumTombstones = 0 protected
Definition at line 41 of file StringMap.h.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::clear(), init(), llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), RehashTable(), RemoveKey(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), StringMapImpl(), StringMapImpl(), swap(), and llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace_with_hash().
TheTable
StringMapEntryBase** llvm::StringMapImpl::TheTable = nullptr protected
Definition at line 38 of file StringMap.h.
Referenced by llvm::StringMap< std::nullopt_t, AllocatorTy >::begin(), llvm::StringMap< std::nullopt_t, AllocatorTy >::begin(), llvm::StringMap< std::nullopt_t, AllocatorTy >::clear(), llvm::StringMap< std::nullopt_t, AllocatorTy >::end(), llvm::StringMap< std::nullopt_t, AllocatorTy >::end(), llvm::StringMap< std::nullopt_t, AllocatorTy >::find(), llvm::StringMap< std::nullopt_t, AllocatorTy >::find(), FindKey(), init(), llvm::StringMap< std::nullopt_t, AllocatorTy >::insert(), LookupBucketFor(), RehashTable(), RemoveKey(), llvm::StringMap< std::nullopt_t, AllocatorTy >::StringMap(), StringMapImpl(), StringMapImpl(), swap(), llvm::StringMap< std::nullopt_t, AllocatorTy >::try_emplace_with_hash(), llvm::StringMap< std::nullopt_t, AllocatorTy >::~StringMap(), and ~StringMapImpl().
TombstoneIntVal
uintptr_t llvm::StringMapImpl::TombstoneIntVal static constexpr
Initial value:
=
      static_cast<uintptr_t>(-1)
      << PointerLikeTypeTraits<StringMapEntryBase *>::NumLowBitsAvailable
Definition at line 93 of file StringMap.h.
Referenced by getTombstoneVal().
The documentation for this class was generated from the following files:
include/llvm/ADT/StringMap.h
lib/Support/StringMap.cpp