LLVM: llvm::xray::CustomEventRecordV5 Class Reference
llvm::xray::CustomEventRecordV5 Class Reference
#include "llvm/XRay/FDRRecords.h"
Public Member Functions
CustomEventRecordV5 ()
CustomEventRecordV5 (int32_t S, int32_t D, std::string P)
int32_t size () const
int32_t delta () const
StringRef data () const
Error apply (RecordVisitor &V) override
Public Member Functions inherited from llvm::xray::MetadataRecord
MetadataRecord (RecordKind T, MetadataType M)
MetadataType metadataType () const
virtual ~MetadataRecord ()=default
Public Member Functions inherited from llvm::xray::Record
Record (const Record &)=delete
Record (Record &&)=delete
Record & operator= (const Record &)=delete
Record & operator= (Record &&)=delete
Record (RecordKind T)
RecordKind getRecordType () const
virtual ~Record ()=default
Static Public Member Functions
static bool classof (const Record *R)
Static Public Member Functions inherited from llvm::xray::MetadataRecord
static bool classof (const Record *R)
Static Public Member Functions inherited from llvm::xray::Record
static LLVM_ABI StringRef kindToString (RecordKind K)
Friends
class RecordInitializer
Additional Inherited Members
Public Types inherited from llvm::xray::MetadataRecord
enum class MetadataType : unsigned {
Unknown , BufferExtents , WallClockTime , NewCPUId ,
TSCWrap , CustomEvent , CallArg , PIDEntry ,
NewBuffer , EndOfBuffer , TypedEvent
}
Public Types inherited from llvm::xray::Record
enum class RecordKind {
RK_Metadata , RK_Metadata_BufferExtents , RK_Metadata_WallClockTime , RK_Metadata_NewCPUId ,
RK_Metadata_TSCWrap , RK_Metadata_CustomEvent , RK_Metadata_CustomEventV5 , RK_Metadata_CallArg ,
RK_Metadata_PIDEntry , RK_Metadata_NewBuffer , RK_Metadata_EndOfBuffer , RK_Metadata_TypedEvent ,
RK_Metadata_LastMetadata , RK_Function
}
Static Protected Attributes inherited from llvm::xray::MetadataRecord
static constexpr int kMetadataBodySize = 15
Detailed Description
Definition at line 236 of file FDRRecords.h.
Constructor & Destructor Documentation
CustomEventRecordV5() [1/2]
llvm::xray::CustomEventRecordV5::CustomEventRecordV5 () inline
Definition at line 243 of file FDRRecords.h.
References llvm::xray::MetadataRecord::CustomEvent, llvm::xray::MetadataRecord::MetadataRecord(), and llvm::xray::Record::RK_Metadata_CustomEventV5.
CustomEventRecordV5() [2/2]
llvm::xray::CustomEventRecordV5::CustomEventRecordV5 (int32_t S, int32_t D, std::string P) inline explicit
Definition at line 247 of file FDRRecords.h.
References llvm::xray::MetadataRecord::CustomEvent, D(), llvm::xray::MetadataRecord::MetadataRecord(), llvm::move(), P, and llvm::xray::Record::RK_Metadata_CustomEventV5.
Member Function Documentation
apply()
Error llvm::xray::CustomEventRecordV5::apply (RecordVisitor & V) override virtual
Implements llvm::xray::Record.
Definition at line 28 of file FDRRecords.cpp.
classof()
bool llvm::xray::CustomEventRecordV5::classof (const Record * R) inline static
Definition at line 258 of file FDRRecords.h.
References llvm::xray::Record::RK_Metadata_CustomEventV5.
data()
StringRef llvm::xray::CustomEventRecordV5::data () const inline
Definition at line 254 of file FDRRecords.h.
delta()
int32_t llvm::xray::CustomEventRecordV5::delta () const inline
Definition at line 253 of file FDRRecords.h.
size()
int32_t llvm::xray::CustomEventRecordV5::size () const inline
Definition at line 252 of file FDRRecords.h.
Friends And Related Symbol Documentation
RecordInitializer
friend class RecordInitializer friend
Definition at line 240 of file FDRRecords.h.
References RecordInitializer.
Referenced by RecordInitializer.
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecords.h
lib/XRay/FDRRecords.cpp