LLVM: llvm::GVNExpression::int_op_inserter Class Reference
llvm::GVNExpression::int_op_inserter Class Reference
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Types
using iterator_category = std::output_iterator_tag
using value_type = void
using difference_type = void
using pointer = void
using reference = void
Public Member Functions
int_op_inserter (AggregateValueExpression &E)
int_op_inserter (AggregateValueExpression *E)
int_op_inserter & operator= (unsigned int val)
int_op_inserter & operator* ()
int_op_inserter & operator++ ()
int_op_inserter & operator++ (int)
Detailed Description
Definition at line 486 of file GVNExpression.h.
Member Typedef Documentation
difference_type
using llvm::GVNExpression::int_op_inserter::difference_type = void
Definition at line 495 of file GVNExpression.h.
iterator_category
using llvm::GVNExpression::int_op_inserter::iterator_category = std::output_iterator_tag
Definition at line 493 of file GVNExpression.h.
pointer
using llvm::GVNExpression::int_op_inserter::pointer = void
Definition at line 496 of file GVNExpression.h.
reference
using llvm::GVNExpression::int_op_inserter::reference = void
Definition at line 497 of file GVNExpression.h.
value_type
using llvm::GVNExpression::int_op_inserter::value_type = void
Definition at line 494 of file GVNExpression.h.
Constructor & Destructor Documentation
int_op_inserter() [1/2]
llvm::GVNExpression::int_op_inserter::int_op_inserter (AggregateValueExpression & E) inline explicit
Definition at line 499 of file GVNExpression.h.
References E().
Referenced by operator*(), operator++(), operator++(), and operator=().
int_op_inserter() [2/2]
llvm::GVNExpression::int_op_inserter::int_op_inserter (AggregateValueExpression * E) inline explicit
Definition at line 500 of file GVNExpression.h.
References E().
Member Function Documentation
operator*()
int_op_inserter & llvm::GVNExpression::int_op_inserter::operator* () inline
Definition at line 506 of file GVNExpression.h.
References int_op_inserter().
operator++() [1/2]
int_op_inserter & llvm::GVNExpression::int_op_inserter::operator++ () inline
Definition at line 507 of file GVNExpression.h.
References int_op_inserter().
operator++() [2/2]
int_op_inserter & llvm::GVNExpression::int_op_inserter::operator++ (int) inline
Definition at line 508 of file GVNExpression.h.
References int_op_inserter().
operator=()
int_op_inserter & llvm::GVNExpression::int_op_inserter::operator= (unsigned int val) inline
Definition at line 502 of file GVNExpression.h.
References int_op_inserter().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Scalar/GVNExpression.h