LLVM: llvm::MCBoundaryAlignFragment Class Reference
llvm::MCBoundaryAlignFragment Class Reference
Represents required padding such that a particular other set of fragments does not cross a particular power-of-two boundary.
#include "llvm/MC/MCSection.h"
Public Member Functions
MCBoundaryAlignFragment (Align AlignBoundary, const MCSubtargetInfo &STI)
uint64_t getSize () const
void setSize (uint64_t Value)
Align getAlignment () const
void setAlignment (Align Value)
const MCFragment * getLastFragment () const
void setLastFragment (const MCFragment *F)
const MCSubtargetInfo * getSubtargetInfo () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
MCFragment * getNext () const
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
LLVM_ABI const MCSymbol * getAtom () const
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it?
bool isLinkerRelaxable () const
void setLinkerRelaxable ()
LLVM_ABI void dump () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Data , FT_Relaxable , FT_Align , FT_Fill ,
FT_LEB , FT_Nops , FT_Org , FT_Dwarf ,
FT_DwarfFrame , FT_BoundaryAlign , FT_SymbolId , FT_CVInlineLines ,
FT_CVDefRange , FT_PseudoProbe
}
Protected Member Functions inherited from llvm::MCFragment
LLVM_ABI MCFragment (FragmentType Kind, bool HasInstructions)
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions: 1
Used by subclasses for better packing.
bool AlignToBundleEnd: 1
bool LinkerRelaxable: 1
MCDataFragment.
bool AllowAutoPadding: 1
MCRelaxableFragment: x86-specific.
Detailed Description
Represents required padding such that a particular other set of fragments does not cross a particular power-of-two boundary.
The other fragments must follow this one within the same section.
Definition at line 739 of file MCSection.h.
Constructor & Destructor Documentation
MCBoundaryAlignFragment()
llvm::MCBoundaryAlignFragment::MCBoundaryAlignFragment (Align AlignBoundary, const MCSubtargetInfo & STI) inline
Definition at line 752 of file MCSection.h.
References llvm::MCFragment::FT_BoundaryAlign, and llvm::MCFragment::MCFragment().
Member Function Documentation
classof()
bool llvm::MCBoundaryAlignFragment::classof (const MCFragment * F) inline static
Definition at line 770 of file MCSection.h.
References F, llvm::MCFragment::FT_BoundaryAlign, and llvm::MCFragment::MCFragment().
getAlignment()
Align llvm::MCBoundaryAlignFragment::getAlignment () const inline
Definition at line 759 of file MCSection.h.
getLastFragment()
const MCFragment * llvm::MCBoundaryAlignFragment::getLastFragment () const inline
Definition at line 762 of file MCSection.h.
References llvm::MCFragment::MCFragment().
getSize()
uint64_t llvm::MCBoundaryAlignFragment::getSize () const inline
Definition at line 756 of file MCSection.h.
getSubtargetInfo()
const MCSubtargetInfo * llvm::MCBoundaryAlignFragment::getSubtargetInfo () const inline
Definition at line 768 of file MCSection.h.
Referenced by writeFragment().
setAlignment()
void llvm::MCBoundaryAlignFragment::setAlignment (Align Value) inline
Definition at line 760 of file MCSection.h.
setLastFragment()
void llvm::MCBoundaryAlignFragment::setLastFragment (const MCFragment * F) inline
Definition at line 763 of file MCSection.h.
References assert(), F, llvm::MCFragment::getParent(), and llvm::MCFragment::MCFragment().
setSize()
void llvm::MCBoundaryAlignFragment::setSize (uint64_t Value) inline
Definition at line 757 of file MCSection.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCSection.h