LLVM: llvm::impl_detail::MachineSchedulerBase Class Reference
llvm::impl_detail::MachineSchedulerBase Class Reference
Base class for the machine scheduler classes.
Protected Member Functions
void scheduleRegions (ScheduleDAGInstrs &Scheduler, bool FixKillFlags)
Main driver for both MachineScheduler and PostMachineScheduler.
Additional Inherited Members
Public Member Functions inherited from llvm::MachineSchedContext
MachineSchedContext ()
MachineSchedContext & operator= (const MachineSchedContext &other)=delete
MachineSchedContext (const MachineSchedContext &other)=delete
virtual ~MachineSchedContext ()
Public Attributes inherited from llvm::MachineSchedContext
MachineFunction * MF = nullptr
const MachineLoopInfo * MLI = nullptr
const MachineDominatorTree * MDT = nullptr
const TargetMachine * TM = nullptr
AAResults * AA = nullptr
LiveIntervals * LIS = nullptr
RegisterClassInfo * RegClassInfo
Detailed Description
Base class for the machine scheduler classes.
Definition at line 321 of file MachineScheduler.cpp.
Member Function Documentation
scheduleRegions()
void MachineSchedulerBase::scheduleRegions (ScheduleDAGInstrs & Scheduler, bool FixKillFlags) protected
Main driver for both MachineScheduler and PostMachineScheduler.
Definition at line 837 of file MachineScheduler.cpp.
References llvm::dbgs(), llvm::DumpCriticalPathLength, llvm::errs(), getSchedRegions(), I, if(), LLVM_DEBUG, MBB, llvm::MachineSchedContext::MF, llvm::printMBBReference(), SchedOnlyBlock, SchedOnlyFunc, Scheduler, and scheduleRegions().
Referenced by llvm::impl_detail::MachineSchedulerImpl::run(), llvm::impl_detail::PostMachineSchedulerImpl::run(), and scheduleRegions().
The documentation for this class was generated from the following file:
lib/CodeGen/MachineScheduler.cpp