LLVM: llvm::jitlink::Symbol Class Reference
llvm::jitlink::Symbol Class Reference
Symbol representation.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Member Functions
Symbol ()=default
Create a null Symbol.
Symbol (const Symbol &)=delete
Symbol & operator= (const Symbol &)=delete
Symbol (Symbol &&)=delete
Symbol & operator= (Symbol &&)=delete
bool hasName () const
Returns true if this symbol has a name.
const orc::SymbolStringPtr & getName () const
Returns the name of this symbol (empty if the symbol is anonymous).
void setName (const orc::SymbolStringPtr Name)
Rename this symbol.
bool isDefined () const
Returns true if this Symbol has content (potentially) defined within this object file (i.e.
bool isLive () const
Returns true if this symbol is live (i.e.
void setLive (bool IsLive)
Set this symbol's live bit.
bool isCallable () const
Returns true is this symbol is callable.
void setCallable (bool IsCallable)
Set this symbol's callable bit.
bool isExternal () const
Returns true if the underlying addressable is an unresolved external.
bool isAbsolute () const
Returns true if the underlying addressable is an absolute symbol.
Addressable & getAddressable ()
Return the addressable that this symbol points to.
const Addressable & getAddressable () const
Return the addressable that this symbol points to.
Block & getBlock ()
Return the Block for this Symbol (Symbol must be defined).
const Block & getBlock () const
Return the Block for this Symbol (Symbol must be defined).
Section & getSection () const
Return the Section for this Symbol (Symbol must be defined).
orc::ExecutorAddrDiff getOffset () const
Returns the offset for this symbol within the underlying addressable.
void setOffset (orc::ExecutorAddrDiff NewOffset)
orc::ExecutorAddr getAddress () const
Returns the address of this symbol.
orc::ExecutorAddrDiff getSize () const
Returns the size of this symbol.
void setSize (orc::ExecutorAddrDiff Size)
Set the size of this symbol.
orc::ExecutorAddrRange getRange () const
Returns the address range of this symbol.
bool isSymbolZeroFill () const
Returns true if this symbol is backed by a zero-fill block.
ArrayRef< char > getSymbolContent () const
Returns the content in the underlying block covered by this symbol.
Linkage getLinkage () const
Get the linkage for this Symbol.
void setLinkage (Linkage L)
Set the linkage for this Symbol.
Scope getScope () const
Get the visibility for this Symbol.
void setScope (Scope S)
Set the visibility for this Symbol.
TargetFlagsType getTargetFlags () const
Get the target flags of this Symbol.
void setTargetFlags (TargetFlagsType Flags)
Set the target flags for this Symbol.
bool isWeaklyReferenced () const
Returns true if this is a weakly referenced external symbol.
void setWeaklyReferenced (bool WeakRef)
Set the WeaklyReferenced value for this symbol.
Friends
class LinkGraph
Detailed Description
Symbol representation.
Symbols represent locations within Addressable objects. They can be either Named or Anonymous. Anonymous symbols have neither linkage nor visibility, and must point at ContentBlocks. Named symbols may be in one of four states:
Null: Default initialized. Assignable, but otherwise unusable.
Defined: Has both linkage and visibility and points to a ContentBlock
Common: Has both linkage and visibility, points to a null Addressable.
External: Has neither linkage nor visibility, points to an external Addressable.
Definition at line 433 of file JITLink.h.
Constructor & Destructor Documentation
Symbol() [1/3]
llvm::jitlink::Symbol::Symbol () default
Create a null Symbol.
This allows Symbols to be default initialized for use in containers (e.g. as map values). Null symbols are only useful for assigning to.
Symbol() [2/3]
llvm::jitlink::Symbol::Symbol (const Symbol &) delete
Symbol() [3/3]
llvm::jitlink::Symbol::Symbol (Symbol &&) delete
Member Function Documentation
getAddress()
orc::ExecutorAddr llvm::jitlink::Symbol::getAddress () const inline
Returns the address of this symbol.
Definition at line 603 of file JITLink.h.
Referenced by llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::jitlink::SymbolAddressMap::addSymbol(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::ppc64::applyFixup(), llvm::jitlink::x86::applyFixup(), llvm::jitlink::x86_64::applyFixup(), llvm::jitlink::aarch32::applyFixupArm(), llvm::jitlink::aarch32::applyFixupData(), llvm::jitlink::aarch32::applyFixupThumb(), getRange(), and llvm::jitlink::operator<<().
getAddressable() [1/2]
Addressable & llvm::jitlink::Symbol::getAddressable () inline
Return the addressable that this symbol points to.
Definition at line 566 of file JITLink.h.
References assert().
Referenced by llvm::jitlink::LinkGraph::makeAbsolute(), and llvm::jitlink::LinkGraph::makeExternal().
getAddressable() [2/2]
const Addressable & llvm::jitlink::Symbol::getAddressable () const inline
Return the addressable that this symbol points to.
Definition at line 572 of file JITLink.h.
References assert().
getBlock() [1/2]
Block & llvm::jitlink::Symbol::getBlock () inline
Return the Block for this Symbol (Symbol must be defined).
Definition at line 578 of file JITLink.h.
References assert().
Referenced by llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), getSection(), getSymbolContent(), llvm::jitlink::initRelaxAux(), isSymbolZeroFill(), setOffset(), and llvm::jitlink::LinkGraph::transferBlock().
getBlock() [2/2]
const Block & llvm::jitlink::Symbol::getBlock () const inline
Return the Block for this Symbol (Symbol must be defined).
Definition at line 585 of file JITLink.h.
References assert().
getLinkage()
Linkage llvm::jitlink::Symbol::getLinkage () const inline
Get the linkage for this Symbol.
Definition at line 634 of file JITLink.h.
Referenced by llvm::orc::LinkGraphLayer::getJITSymbolFlagsForSymbol(), llvm::jitlink::makeTargetOutOfRangeError(), and llvm::jitlink::operator<<().
getName()
const orc::SymbolStringPtr & llvm::jitlink::Symbol::getName () const inline
Returns the name of this symbol (empty if the symbol is anonymous).
Definition at line 519 of file JITLink.h.
References assert(), getScope(), hasName(), and llvm::jitlink::Local.
Referenced by llvm::jitlink::LinkGraph::addAbsoluteSymbol(), llvm::jitlink::LinkGraph::addDefinedSymbol(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::jitlink::identifyELFSectionStartAndEndSymbols(), llvm::jitlink::identifyMachOSectionStartAndEndSymbols(), llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeDefined(), llvm::jitlink::LinkGraph::makeExternal(), llvm::jitlink::makeTargetOutOfRangeError(), llvm::jitlink::operator<<(), llvm::jitlink::CompactUnwindManager< CURecTraits >::prepareForPrune(), and llvm::jitlink::LinkGraph::removeExternalSymbol().
getOffset()
orc::ExecutorAddrDiff llvm::jitlink::Symbol::getOffset () const inline
Returns the offset for this symbol within the underlying addressable.
Definition at line 595 of file JITLink.h.
Referenced by llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::jitlink::initRelaxAux(), llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeExternal(), llvm::jitlink::operator<<(), llvm::jitlink::relaxBlock(), and llvm::jitlink::COFFLinkGraphBuilder::setGraphSymbol().
getRange()
orc::ExecutorAddrRange llvm::jitlink::Symbol::getRange () const inline
Returns the address range of this symbol.
Definition at line 619 of file JITLink.h.
References getAddress(), and getSize().
getScope()
Scope llvm::jitlink::Symbol::getScope () const inline
Get the visibility for this Symbol.
Definition at line 644 of file JITLink.h.
Referenced by llvm::orc::LinkGraphLayer::getJITSymbolFlagsForSymbol(), getName(), llvm::jitlink::makeTargetOutOfRangeError(), and llvm::jitlink::operator<<().
getSection()
Section & llvm::jitlink::Symbol::getSection () const inline
Return the Section for this Symbol (Symbol must be defined).
Definition at line 592 of file JITLink.h.
References getBlock(), and llvm::jitlink::Block::getSection().
Referenced by llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeExternal(), llvm::jitlink::LinkGraph::removeDefinedSymbol(), llvm::jitlink::LinkGraph::transferDefinedSymbol(), llvm::jitlink::aarch32::StubsManager_prev7::visitEdge(), and llvm::jitlink::aarch32::StubsManager_v7::visitEdge().
getSize()
orc::ExecutorAddrDiff llvm::jitlink::Symbol::getSize () const inline
Returns the size of this symbol.
Definition at line 606 of file JITLink.h.
Referenced by llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), getRange(), llvm::jitlink::initRelaxAux(), llvm::jitlink::operator<<(), setOffset(), and llvm::jitlink::LinkGraph::transferDefinedSymbol().
getSymbolContent()
ArrayRef< char > llvm::jitlink::Symbol::getSymbolContent () const inline
Returns the content in the underlying block covered by this symbol.
This method may only be called on defined non-zero-fill symbols.
Definition at line 629 of file JITLink.h.
References getBlock(), llvm::jitlink::Block::getContent(), and llvm::ArrayRef< T >::slice().
getTargetFlags()
TargetFlagsType llvm::jitlink::Symbol::getTargetFlags () const inline
Get the target flags of this Symbol.
Definition at line 656 of file JITLink.h.
Referenced by llvm::jitlink::aarch32::hasTargetFlags(), and llvm::jitlink::aarch32::StubsManager_v7::visitEdge().
hasName()
bool llvm::jitlink::Symbol::hasName () const inline
Returns true if this symbol has a name.
Definition at line 516 of file JITLink.h.
Referenced by getName(), llvm::jitlink::operator<<(), and setScope().
isAbsolute()
bool llvm::jitlink::Symbol::isAbsolute () const inline
Returns true if the underlying addressable is an absolute symbol.
Definition at line 560 of file JITLink.h.
References assert().
Referenced by llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeDefined(), llvm::jitlink::LinkGraph::makeExternal(), llvm::jitlink::LinkGraph::removeAbsoluteSymbol(), and llvm::jitlink::LinkGraph::removeExternalSymbol().
isCallable()
bool llvm::jitlink::Symbol::isCallable () const inline
Returns true is this symbol is callable.
Definition at line 548 of file JITLink.h.
Referenced by llvm::orc::LinkGraphLayer::getJITSymbolFlagsForSymbol().
isDefined()
bool llvm::jitlink::Symbol::isDefined () const inline
Returns true if this Symbol has content (potentially) defined within this object file (i.e.
is anything but an external or absolute symbol).
Definition at line 532 of file JITLink.h.
References assert().
Referenced by llvm::jitlink::initRelaxAux(), llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeDefined(), llvm::jitlink::LinkGraph::makeExternal(), llvm::jitlink::operator<<(), llvm::jitlink::CompactUnwindManager< CURecTraits >::prepareForPrune(), llvm::jitlink::LinkGraph::removeAbsoluteSymbol(), llvm::jitlink::LinkGraph::removeDefinedSymbol(), and llvm::jitlink::LinkGraph::removeExternalSymbol().
isExternal()
bool llvm::jitlink::Symbol::isExternal () const inline
Returns true if the underlying addressable is an unresolved external.
Definition at line 554 of file JITLink.h.
References assert().
Referenced by isWeaklyReferenced(), llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeExternal(), and setWeaklyReferenced().
isLive()
bool llvm::jitlink::Symbol::isLive () const inline
Returns true if this symbol is live (i.e.
should be treated as a root for dead stripping).
Definition at line 539 of file JITLink.h.
References assert().
Referenced by llvm::jitlink::operator<<().
isSymbolZeroFill()
bool llvm::jitlink::Symbol::isSymbolZeroFill () const inline
Returns true if this symbol is backed by a zero-fill block.
This method may only be called on defined symbols.
Definition at line 625 of file JITLink.h.
References getBlock(), and llvm::jitlink::Block::isZeroFill().
isWeaklyReferenced()
bool llvm::jitlink::Symbol::isWeaklyReferenced () const inline
Returns true if this is a weakly referenced external symbol.
This method may only be called on external symbols.
Definition at line 666 of file JITLink.h.
References assert(), and isExternal().
operator=() [1/2]
Symbol & llvm::jitlink::Symbol::operator= (const Symbol &) delete
operator=() [2/2]
Symbol & llvm::jitlink::Symbol::operator= (Symbol &&) delete
setCallable()
void llvm::jitlink::Symbol::setCallable (bool IsCallable) inline
Set this symbol's callable bit.
Definition at line 551 of file JITLink.h.
setLinkage()
void llvm::jitlink::Symbol::setLinkage (Linkage L) inline
Set the linkage for this Symbol.
Definition at line 637 of file JITLink.h.
References assert(), and llvm::jitlink::Strong.
Referenced by llvm::jitlink::LinkGraph::makeDefined().
setLive()
void llvm::jitlink::Symbol::setLive (bool IsLive) inline
Set this symbol's live bit.
Definition at line 545 of file JITLink.h.
Referenced by llvm::jitlink::COFFLinkGraphBuilder::addImageBaseSymbol(), and llvm::jitlink::LinkGraph::makeDefined().
setName()
void llvm::jitlink::Symbol::setName (const orc::SymbolStringPtr Name) inline
Rename this symbol.
The client is responsible for updating scope and linkage if this name-change requires it.
Definition at line 528 of file JITLink.h.
setOffset()
void llvm::jitlink::Symbol::setOffset (orc::ExecutorAddrDiff NewOffset) inline
Definition at line 597 of file JITLink.h.
References assert(), getBlock(), and getSize().
Referenced by llvm::jitlink::LinkGraph::makeDefined(), and llvm::jitlink::LinkGraph::transferDefinedSymbol().
setScope()
void llvm::jitlink::Symbol::setScope (Scope S) inline
Set the visibility for this Symbol.
Definition at line 647 of file JITLink.h.
References assert(), hasName(), and llvm::jitlink::Local.
Referenced by llvm::jitlink::LinkGraph::makeAbsolute(), and llvm::jitlink::LinkGraph::makeDefined().
setSize()
void llvm::jitlink::Symbol::setSize (orc::ExecutorAddrDiff Size) inline
Set the size of this symbol.
Definition at line 609 of file JITLink.h.
References assert(), and llvm::jitlink::Block::getSize().
Referenced by llvm::jitlink::LinkGraph::makeDefined(), and llvm::jitlink::LinkGraph::transferDefinedSymbol().
setTargetFlags()
void llvm::jitlink::Symbol::setTargetFlags (TargetFlagsType Flags) inline
Set the target flags for this Symbol.
Definition at line 659 of file JITLink.h.
References assert().
Referenced by llvm::jitlink::aarch32::StubsManager_v7::visitEdge().
setWeaklyReferenced()
void llvm::jitlink::Symbol::setWeaklyReferenced (bool WeakRef) inline
Set the WeaklyReferenced value for this symbol.
This method may only be called on external symbols.
Definition at line 673 of file JITLink.h.
References assert(), and isExternal().
Friends And Related Symbol Documentation
LinkGraph
friend class LinkGraph friend
Definition at line 434 of file JITLink.h.
References LinkGraph, and llvm::move().
Referenced by LinkGraph.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h