LLVM: llvm::coro::BaseABI Class Reference
llvm::coro::BaseABI Class Reference abstract
#include "llvm/Transforms/Coroutines/ABI.h"
Public Member Functions
BaseABI (Function &F, coro::Shape &S, std::function< bool(Instruction &)> IsMaterializable)
virtual ~BaseABI ()=default
virtual void init ()=0
virtual void buildCoroutineFrame (bool OptimizeFrame)
virtual void splitCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones, TargetTransformInfo &TTI)=0
Public Attributes
Function & F
coro::Shape & Shape
std::function< bool(Instruction &I)> IsMaterializable
Detailed Description
Definition at line 41 of file ABI.h.
Constructor & Destructor Documentation
BaseABI()
llvm::coro::BaseABI::BaseABI (Function & F, coro::Shape & S, std::function< bool(Instruction &)> IsMaterializable) inline
Definition at line 43 of file ABI.h.
References F, IsMaterializable, llvm::move(), and Shape.
Referenced by llvm::coro::AnyRetconABI::AnyRetconABI(), llvm::coro::AsyncABI::AsyncABI(), and llvm::coro::SwitchABI::SwitchABI().
~BaseABI()
virtual llvm::coro::BaseABI::~BaseABI () virtual default
Member Function Documentation
buildCoroutineFrame()
void coro::BaseABI::buildCoroutineFrame (bool OptimizeFrame) virtual
Definition at line 2052 of file CoroFrame.cpp.
References llvm::coro::Async, buildFrameDebugInfo(), buildFrameType(), llvm::coro::collectSpillsAndAllocasFromInsts(), llvm::coro::collectSpillsFromArgs(), llvm::coro::collectSpillsFromDbgInfo(), llvm::coro::doRematerializations(), dumpAllocas(), dumpSpills(), F, I, insertSpills(), IsMaterializable, LLVM_DEBUG, lowerLocalAllocas(), llvm::coro::Retcon, llvm::coro::RetconOnce, Shape, sinkLifetimeStartMarkers(), and llvm::coro::sinkSpillUsesAfterCoroBegin().
Referenced by init().
init()
virtual void llvm::coro::BaseABI::init () pure virtual
Implemented in llvm::coro::AnyRetconABI, llvm::coro::AsyncABI, and llvm::coro::SwitchABI.
References buildCoroutineFrame().
splitCoroutine()
virtual void llvm::coro::BaseABI::splitCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones, TargetTransformInfo & TTI) pure virtual
Implemented in llvm::coro::AnyRetconABI, llvm::coro::AsyncABI, and llvm::coro::SwitchABI.
References F, and Shape.
Member Data Documentation
F
Function& llvm::coro::BaseABI::F
Definition at line 59 of file ABI.h.
Referenced by llvm::coro::AnyRetconABI::AnyRetconABI(), llvm::coro::AsyncABI::AsyncABI(), BaseABI(), buildCoroutineFrame(), llvm::coro::AnyRetconABI::splitCoroutine(), llvm::coro::AsyncABI::splitCoroutine(), splitCoroutine(), llvm::coro::SwitchABI::splitCoroutine(), and llvm::coro::SwitchABI::SwitchABI().
IsMaterializable
std::function<bool(Instruction &I)> llvm::coro::BaseABI::IsMaterializable
Definition at line 64 of file ABI.h.
Referenced by llvm::coro::AnyRetconABI::AnyRetconABI(), llvm::coro::AsyncABI::AsyncABI(), BaseABI(), buildCoroutineFrame(), and llvm::coro::SwitchABI::SwitchABI().
Shape
coro::Shape& llvm::coro::BaseABI::Shape
Definition at line 60 of file ABI.h.
Referenced by BaseABI(), buildCoroutineFrame(), llvm::coro::AnyRetconABI::init(), llvm::coro::AsyncABI::init(), llvm::coro::SwitchABI::init(), llvm::coro::AnyRetconABI::splitCoroutine(), llvm::coro::AsyncABI::splitCoroutine(), splitCoroutine(), and llvm::coro::SwitchABI::splitCoroutine().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Coroutines/ABI.h
lib/Transforms/Coroutines/CoroFrame.cpp