LLVM: llvm::MachineCopyPropagationPass Class Reference
llvm::MachineCopyPropagationPass Class Reference
#include "llvm/CodeGen/MachineCopyPropagation.h"
Public Member Functions
MachineCopyPropagationPass (bool UseCopyInstr=false)
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
MachineFunctionProperties getRequiredProperties () const
Public Member Functions inherited from llvm::PassInfoMixin< MachineCopyPropagationPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MachineCopyPropagationPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file MachineCopyPropagation.h.
Constructor & Destructor Documentation
MachineCopyPropagationPass()
llvm::MachineCopyPropagationPass::MachineCopyPropagationPass (bool UseCopyInstr = false) inline
Definition at line 21 of file MachineCopyPropagation.h.
Member Function Documentation
getRequiredProperties()
MachineFunctionProperties llvm::MachineCopyPropagationPass::getRequiredProperties () const inline
Definition at line 27 of file MachineCopyPropagation.h.
run()
PreservedAnalyses MachineCopyPropagationPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 1589 of file MachineCopyPropagation.cpp.
References _, llvm::PreservedAnalyses::all(), llvm::getMachineFunctionPassPreservedAnalyses(), and run().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineCopyPropagation.h
lib/CodeGen/MachineCopyPropagation.cpp