LLVM: llvm::dwarf::UnwindTable Class Reference
llvm::dwarf::UnwindTable Class Reference
A class that contains all UnwindRow objects for an FDE or a single unwind row for a CIE.
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFUnwindTable.h"
Public Types
using RowContainer = std::vector<UnwindRow>
using iterator = RowContainer::iterator
using const_iterator = RowContainer::const_iterator
Public Member Functions
UnwindTable (RowContainer &&Rows)
size_t size () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const UnwindRow & operator[] (size_t Index) const
Detailed Description
A class that contains all UnwindRow objects for an FDE or a single unwind row for a CIE.
To unwind an address the rows, which are sorted by start address, can be searched to find the UnwindRow with the lowest starting address that is greater than or equal to the address that is being looked up.
Definition at line 274 of file DWARFUnwindTable.h.
Member Typedef Documentation
const_iterator
using llvm::dwarf::UnwindTable::const_iterator = RowContainer::const_iterator
Definition at line 278 of file DWARFUnwindTable.h.
iterator
using llvm::dwarf::UnwindTable::iterator = RowContainer::iterator
Definition at line 277 of file DWARFUnwindTable.h.
RowContainer
using llvm::dwarf::UnwindTable::RowContainer = std::vector<UnwindRow>
Definition at line 276 of file DWARFUnwindTable.h.
Constructor & Destructor Documentation
UnwindTable()
llvm::dwarf::UnwindTable::UnwindTable (RowContainer && Rows) inline
Definition at line 280 of file DWARFUnwindTable.h.
References llvm::move().
Member Function Documentation
begin() [1/2]
iterator llvm::dwarf::UnwindTable::begin () inline
Definition at line 283 of file DWARFUnwindTable.h.
begin() [2/2]
const_iterator llvm::dwarf::UnwindTable::begin () const inline
Definition at line 284 of file DWARFUnwindTable.h.
end() [1/2]
iterator llvm::dwarf::UnwindTable::end () inline
Definition at line 285 of file DWARFUnwindTable.h.
end() [2/2]
const_iterator llvm::dwarf::UnwindTable::end () const inline
Definition at line 286 of file DWARFUnwindTable.h.
operator[]()
const UnwindRow & llvm::dwarf::UnwindTable::operator[] (size_t Index) const inline
Definition at line 287 of file DWARFUnwindTable.h.
References assert(), and size().
size()
size_t llvm::dwarf::UnwindTable::size () const inline
Definition at line 282 of file DWARFUnwindTable.h.
Referenced by operator[]().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/LowLevel/DWARFUnwindTable.h