LLVM: llvm::sampleprof::SampleProfileWriterExtBinaryBase Class Reference
llvm::sampleprof::SampleProfileWriterExtBinaryBase Class Reference abstract
#include "llvm/ProfileData/SampleProfWriter.h"
Public Member Functions
std::error_code write (const SampleProfileMap &ProfileMap) override
Write all the sample profiles in the given map of samples.
void setToCompressAllSections () override
void setToCompressSection (SecType Type)
std::error_code writeSample (const FunctionSamples &S) override
Write samples of a top-level function to a binary file.
void setUseMD5 () override
void setPartialProfile () override
void setProfileSymbolList (ProfileSymbolList *PSL) override
void setUseCtxSplitLayout () override
void resetSecLayout (SectionLayout SL)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
SampleProfileWriterBinary (std::unique_ptr< raw_ostream > &OS)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
virtual ~SampleProfileWriter ()=default
template<typename FunctionPruningStrategy = DefaultFunctionPruningStrategy>
std::error_code writeWithSizeLimit (SampleProfileMap &ProfileMap, size_t OutputSizeLimit)
Write sample profiles up to given size limit, using the pruning strategy to drop some functions if necessary.
raw_ostream & getOutputStream ()
Protected Member Functions
uint64_t markSectionStart (SecType Type, uint32_t LayoutIdx)
Return the current position and prepare to use it as the start position of a section given the section type Type and its position LayoutIdx in SectionHdrLayout.
std::error_code addNewSection (SecType Sec, uint32_t LayoutIdx, uint64_t SectionStart)
Add a new section into section header table given the section type Type, its position LayoutIdx in SectionHdrLayout and the location SectionStart where the section should be written to.
template<class SecFlagType>
void addSectionFlag (SecType Type, SecFlagType Flag)
template<class SecFlagType>
void addSectionFlag (uint32_t SectionIdx, SecFlagType Flag)
void addContext (const SampleContext &Context) override
virtual std::error_code writeCustomSection (SecType Type)=0
virtual void verifySecLayout (SectionLayout SL)=0
virtual std::error_code writeSections (const SampleProfileMap &ProfileMap)=0
virtual std::error_code writeOneSection (SecType Type, uint32_t LayoutIdx, const SampleProfileMap &ProfileMap)
std::error_code writeNameTable () override
std::error_code writeContextIdx (const SampleContext &Context) override
std::error_code writeCSNameIdx (const SampleContext &Context)
std::error_code writeCSNameTableSection ()
std::error_code writeFuncMetadata (const SampleProfileMap &Profiles)
std::error_code writeFuncMetadata (const FunctionSamples &Profile)
std::error_code writeNameTableSection (const SampleProfileMap &ProfileMap)
std::error_code writeFuncOffsetTable ()
std::error_code writeProfileSymbolListSection ()
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriterBinary
virtual MapVector< FunctionId, uint32_t > & getNameTable ()
virtual std::error_code writeMagicIdent (SampleProfileFormat Format)
std::error_code writeSummary ()
std::error_code writeNameIdx (FunctionId FName)
std::error_code writeBody (const FunctionSamples &S)
void stablizeNameTable (MapVector< FunctionId, uint32_t > &NameTable, std::set< FunctionId > &V)
void addName (FunctionId FName)
void addNames (const FunctionSamples &S)
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeFuncProfiles (const SampleProfileMap &ProfileMap)
std::error_code writeWithSizeLimitInternal (SampleProfileMap &ProfileMap, size_t OutputSizeLimit, FunctionPruningStrategy *Strategy)
void computeSummary (const SampleProfileMap &ProfileMap)
Compute summary for this profile.
Protected Attributes
SectionLayout SecLayout = DefaultLayout
SmallVector< SecHdrTableEntry, 8 > SectionHdrLayout
uint64_t SecLBRProfileStart = 0
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriterBinary
MapVector< FunctionId, uint32_t > NameTable
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
size_t LineCount
For writeWithSizeLimit in text mode, each newline takes 1 additional byte on Windows when actually written to the file, but not written to a memory buffer.
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
SampleProfileFormat Format = SPF_None
Profile format.
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Detailed Description
Definition at line 268 of file SampleProfWriter.h.
Member Function Documentation
addContext()
void SampleProfileWriterExtBinaryBase::addContext (const SampleContext & Context) override protected virtual
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 668 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleProfileWriterBinary::addName().
Referenced by writeNameTableSection().
addNewSection()
std::error_code SampleProfileWriterExtBinaryBase::addNewSection (SecType Sec, uint32_t LayoutIdx, uint64_t SectionStart) protected
Add a new section into section header table given the section type Type, its position LayoutIdx in SectionHdrLayout and the location SectionStart where the section should be written to.
Definition at line 199 of file SampleProfWriter.cpp.
References assert(), llvm::sampleprof::hasSecFlag(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SecFlagCompress, SectionHdrLayout, and llvm::success.
Referenced by writeOneSection().
addSectionFlag() [1/2]
template<class SecFlagType> void llvm::sampleprof::SampleProfileWriterExtBinaryBase::addSectionFlag (SecType Type, SecFlagType Flag) inline protected
Definition at line 320 of file SampleProfWriter.h.
References llvm::sampleprof::addSecFlag(), and SectionHdrLayout.
Referenced by setPartialProfile(), setToCompressSection(), setUseMD5(), writeFuncOffsetTable(), writeNameTableSection(), and writeOneSection().
addSectionFlag() [2/2]
template<class SecFlagType> void llvm::sampleprof::SampleProfileWriterExtBinaryBase::addSectionFlag (uint32_t SectionIdx, SecFlagType Flag) inline protected
Definition at line 327 of file SampleProfWriter.h.
References llvm::sampleprof::addSecFlag(), and SectionHdrLayout.
markSectionStart()
uint64_t SampleProfileWriterExtBinaryBase::markSectionStart (SecType Type, uint32_t LayoutIdx) protected
Return the current position and prepare to use it as the start position of a section given the section type Type and its position LayoutIdx in SectionHdrLayout.
Definition at line 165 of file SampleProfWriter.cpp.
References assert(), llvm::sampleprof::hasSecFlag(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SecFlagCompress, and SectionHdrLayout.
Referenced by writeOneSection().
resetSecLayout()
void llvm::sampleprof::SampleProfileWriterExtBinaryBase::resetSecLayout (SectionLayout SL) inline
Definition at line 302 of file SampleProfWriter.h.
References assert(), llvm::sampleprof::ExtBinaryHdrLayoutTable, SecLayout, SectionHdrLayout, and verifySecLayout().
Referenced by setUseCtxSplitLayout().
setPartialProfile()
void llvm::sampleprof::SampleProfileWriterExtBinaryBase::setPartialProfile () inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 290 of file SampleProfWriter.h.
References addSectionFlag(), llvm::sampleprof::SecFlagPartial, and llvm::sampleprof::SecProfSummary.
setProfileSymbolList()
void llvm::sampleprof::SampleProfileWriterExtBinaryBase::setProfileSymbolList (ProfileSymbolList * PSL) inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 294 of file SampleProfWriter.h.
setToCompressAllSections()
void SampleProfileWriterExtBinaryBase::setToCompressAllSections () override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 734 of file SampleProfWriter.cpp.
References llvm::sampleprof::addSecFlag(), llvm::sampleprof::SecFlagCompress, and SectionHdrLayout.
setToCompressSection()
void SampleProfileWriterExtBinaryBase::setToCompressSection (SecType Type)
Definition at line 739 of file SampleProfWriter.cpp.
References addSectionFlag(), and llvm::sampleprof::SecFlagCompress.
Referenced by writeOneSection().
setUseCtxSplitLayout()
void llvm::sampleprof::SampleProfileWriterExtBinaryBase::setUseCtxSplitLayout () inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 298 of file SampleProfWriter.h.
References llvm::sampleprof::CtxSplitLayout, and resetSecLayout().
setUseMD5()
void llvm::sampleprof::SampleProfileWriterExtBinaryBase::setUseMD5 () inline override virtual
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 279 of file SampleProfWriter.h.
References addSectionFlag(), llvm::sampleprof::SecFlagFixedLengthMD5, llvm::sampleprof::SecFlagMD5Name, and llvm::sampleprof::SecNameTable.
verifySecLayout()
virtual void llvm::sampleprof::SampleProfileWriterExtBinaryBase::verifySecLayout (SectionLayout SL) protected pure virtual
Referenced by resetSecLayout().
write()
std::error_code SampleProfileWriterExtBinaryBase::write (const SampleProfileMap & ProfileMap) override virtual
Write all the sample profiles in the given map of samples.
Returns
status code of the file update operation.
Reimplemented from llvm::sampleprof::SampleProfileWriter.
Definition at line 215 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleProfileWriterBinary::NameTable, llvm::success, and writeSections().
writeContextIdx()
std::error_code SampleProfileWriterExtBinaryBase::writeContextIdx (const SampleContext & Context) override protected virtual
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 236 of file SampleProfWriter.cpp.
References writeCSNameIdx(), and llvm::sampleprof::SampleProfileWriterBinary::writeNameIdx().
Referenced by writeFuncMetadata(), writeFuncOffsetTable(), and writeSections().
writeCSNameIdx()
std::error_code SampleProfileWriterExtBinaryBase::writeCSNameIdx (const SampleContext & Context) protected
Definition at line 245 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::success, and llvm::truncated_name_table.
Referenced by writeContextIdx(), and writeSections().
writeCSNameTableSection()
std::error_code SampleProfileWriterExtBinaryBase::writeCSNameTableSection () protected
Definition at line 385 of file SampleProfWriter.cpp.
References assert(), llvm::encodeULEB128(), I, llvm::little, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::success, and llvm::sampleprof::SampleProfileWriterBinary::writeNameIdx().
Referenced by writeOneSection(), and writeSections().
writeCustomSection()
virtual std::error_code llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCustomSection (SecType Type) protected pure virtual
Referenced by writeOneSection().
writeFuncMetadata() [1/2]
std::error_code SampleProfileWriterExtBinaryBase::writeFuncMetadata (const FunctionSamples & Profile) protected
Definition at line 298 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::SampleContext::getAllAttributes(), llvm::sampleprof::FunctionSamples::getCallsiteSamples(), llvm::sampleprof::FunctionSamples::getContext(), llvm::sampleprof::FunctionSamples::getFunctionHash(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::FunctionSamples::ProfileIsPreInlined, llvm::sampleprof::FunctionSamples::ProfileIsProbeBased, llvm::success, writeContextIdx(), and writeFuncMetadata().
writeFuncMetadata() [2/2]
std::error_code SampleProfileWriterExtBinaryBase::writeFuncMetadata (const SampleProfileMap & Profiles) protected
Definition at line 330 of file SampleProfWriter.cpp.
References llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::FunctionSamples::ProfileIsPreInlined, llvm::sampleprof::FunctionSamples::ProfileIsProbeBased, llvm::success, and writeFuncMetadata().
Referenced by writeFuncMetadata(), writeFuncMetadata(), writeOneSection(), and writeSections().
writeFuncOffsetTable()
std::error_code SampleProfileWriterExtBinaryBase::writeFuncOffsetTable () protected
Definition at line 262 of file SampleProfWriter.cpp.
References addSectionFlag(), llvm::encodeULEB128(), llvm::Offset, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::SecFlagOrdered, llvm::sampleprof::SecFuncOffsetTable, llvm::success, and writeContextIdx().
Referenced by writeOneSection(), and writeSections().
writeNameTable()
std::error_code SampleProfileWriterExtBinaryBase::writeNameTable () override protected virtual
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 342 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::little, N, llvm::sampleprof::SampleProfileWriterBinary::NameTable, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SampleProfileWriterBinary::stablizeNameTable(), llvm::success, llvm::support::endian::Writer::write(), and llvm::sampleprof::SampleProfileWriterBinary::writeNameTable().
Referenced by writeNameTableSection(), and writeSections().
writeNameTableSection()
std::error_code SampleProfileWriterExtBinaryBase::writeNameTableSection (const SampleProfileMap & ProfileMap) protected
Definition at line 360 of file SampleProfWriter.cpp.
References addContext(), llvm::sampleprof::SampleProfileWriterBinary::addNames(), addSectionFlag(), I, llvm::sampleprof::SampleProfileWriterBinary::NameTable, llvm::sampleprof::SecFlagUniqSuffix, llvm::sampleprof::SecNameTable, llvm::success, llvm::sampleprof::FunctionSamples::UniqSuffix, and writeNameTable().
Referenced by writeOneSection(), and writeSections().
writeOneSection()
std::error_code SampleProfileWriterExtBinaryBase::writeOneSection (SecType Type, uint32_t LayoutIdx, const SampleProfileMap & ProfileMap) protected virtual
Definition at line 422 of file SampleProfWriter.cpp.
References addNewSection(), addSectionFlag(), llvm::sampleprof::SampleProfileWriter::computeSummary(), markSectionStart(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::FunctionSamples::ProfileIsFS, llvm::sampleprof::FunctionSamples::ProfileIsPreInlined, llvm::sampleprof::FunctionSamples::ProfileIsProbeBased, llvm::sampleprof::SecCSNameTable, llvm::sampleprof::SecFlagFSDiscriminator, llvm::sampleprof::SecFlagFullContext, llvm::sampleprof::SecFlagHasAttribute, llvm::sampleprof::SecFlagIsPreInlined, llvm::sampleprof::SecFlagIsProbeBased, llvm::sampleprof::SecFuncMetadata, llvm::sampleprof::SecFuncOffsetTable, llvm::sampleprof::SecLBRProfile, SecLBRProfileStart, llvm::sampleprof::SecNameTable, llvm::sampleprof::SecProfileSymbolList, llvm::sampleprof::SecProfSummary, setToCompressSection(), llvm::success, writeCSNameTableSection(), writeCustomSection(), writeFuncMetadata(), writeFuncOffsetTable(), llvm::sampleprof::SampleProfileWriter::writeFuncProfiles(), writeNameTableSection(), writeProfileSymbolListSection(), and llvm::sampleprof::SampleProfileWriterBinary::writeSummary().
Referenced by writeSections().
writeProfileSymbolListSection()
std::error_code SampleProfileWriterExtBinaryBase::writeProfileSymbolListSection () protected
Definition at line 414 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleProfileWriter::OutputStream, and llvm::success.
Referenced by writeOneSection(), and writeSections().
writeSample()
std::error_code SampleProfileWriterExtBinaryBase::writeSample (const FunctionSamples & S) override virtual
Write samples of a top-level function to a binary file.
Returns
true if the samples were written successfully, false otherwise.
Reimplemented from llvm::sampleprof::SampleProfileWriterBinary.
Definition at line 254 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::FunctionSamples::getContext(), llvm::sampleprof::FunctionSamples::getHeadSamples(), llvm::Offset, llvm::sampleprof::SampleProfileWriter::OutputStream, SecLBRProfileStart, and llvm::sampleprof::SampleProfileWriterBinary::writeBody().
writeSections()
virtual std::error_code llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeSections (const SampleProfileMap & ProfileMap) protected pure virtual
References Profile, writeContextIdx(), writeCSNameIdx(), writeCSNameTableSection(), writeFuncMetadata(), writeFuncOffsetTable(), writeNameTable(), writeNameTableSection(), writeOneSection(), and writeProfileSymbolListSection().
Referenced by write().
Member Data Documentation
SecLayout
SectionLayout llvm::sampleprof::SampleProfileWriterExtBinaryBase::SecLayout = DefaultLayout protected
Definition at line 360 of file SampleProfWriter.h.
Referenced by resetSecLayout().
SecLBRProfileStart
uint64_t llvm::sampleprof::SampleProfileWriterExtBinaryBase::SecLBRProfileStart = 0 protected
Definition at line 371 of file SampleProfWriter.h.
Referenced by writeOneSection(), and writeSample().
SectionHdrLayout
SmallVector<SecHdrTableEntry, 8> llvm::sampleprof::SampleProfileWriterExtBinaryBase::SectionHdrLayout protected
Initial value:
=
      ExtBinaryHdrLayoutTable[DefaultLayout]
Definition at line 365 of file SampleProfWriter.h.
Referenced by addNewSection(), addSectionFlag(), addSectionFlag(), markSectionStart(), resetSecLayout(), and setToCompressAllSections().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp