LLVM: llvm::jitlink::EHFrameEdgeFixer Class Reference
llvm::jitlink::EHFrameEdgeFixer Class Reference
A LinkGraph pass that adds missing FDE-to-CIE, FDE-to-PC and FDE-to-LSDA edges.
#include "ExecutionEngine/JITLink/EHFrameSupportImpl.h"
Public Member Functions
EHFrameEdgeFixer (StringRef EHFrameSectionName, unsigned PointerSize, Edge::Kind Pointer32, Edge::Kind Pointer64, Edge::Kind Delta32, Edge::Kind Delta64, Edge::Kind NegDelta32)
Create an eh-frame edge fixer.
Error operator() (LinkGraph &G)
Detailed Description
A LinkGraph pass that adds missing FDE-to-CIE, FDE-to-PC and FDE-to-LSDA edges.
Definition at line 26 of file EHFrameSupportImpl.h.
Constructor & Destructor Documentation
EHFrameEdgeFixer()
llvm::jitlink::EHFrameEdgeFixer::EHFrameEdgeFixer (StringRef EHFrameSectionName, unsigned PointerSize, Edge::Kind Pointer32, Edge::Kind Pointer64, Edge::Kind Delta32, Edge::Kind Delta64, Edge::Kind NegDelta32)
Create an eh-frame edge fixer.
Adds edges for implicit relocations on platforms where these are used (e.g. MachO/x86-64).
If a given edge-kind is not supported on the target architecture then Edge::Invalid should be used.
Definition at line 21 of file EHFrameSupport.cpp.
Member Function Documentation
operator()()
Error llvm::jitlink::EHFrameEdgeFixer::operator() (LinkGraph & G)
Definition at line 29 of file EHFrameSupport.cpp.
References llvm::append_range(), B(), llvm::dbgs(), G, llvm::jitlink::BlockAddressMap::includeNonNull(), LHS, LLVM_DEBUG, llvm::make_error(), RHS, llvm::sort(), and llvm::Error::success().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/EHFrameSupportImpl.h
lib/ExecutionEngine/JITLink/EHFrameSupport.cpp