LLVM: llvm::ARMAsmPrinter Class Reference
llvm::ARMAsmPrinter Class Reference
#include "Target/ARM/ARMAsmPrinter.h"
Public Member Functions
ARMAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
const ARMBaseTargetMachine & getTM () const
void printOperand (const MachineInstr *MI, int OpNum, raw_ostream &O)
void PrintSymbolOperand (const MachineOperand &MO, raw_ostream &O) override
Print the MachineOperand as a symbol.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNum, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNum, const char *ExtraCode, raw_ostream &O) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const override
Let the target do anything it needs to do after emitting inlineasm.
void emitJumpTableAddrs (const MachineInstr *MI)
void emitJumpTableInsts (const MachineInstr *MI)
void emitJumpTableTBInst (const MachineInstr *MI, unsigned OffsetWidth)
void emitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - This uses the emitInstruction() method to print assembly for each instruction.
std::tuple< const MCSymbol *, uint64_t, const MCSymbol *, codeview::JumpTableEntrySize > getCodeViewJumpTableInfo (int JTI, const MachineInstr *BranchInstr, const MCSymbol *BranchLabel) const override
Gets information required to create a CodeView debug symbol for a jump table.
void emitConstantPool () override
Print to the current output stream assembly representations of the constants in the constant pool MCP.
void emitFunctionBodyEnd () override
Targets can override this to emit stuff after the last basic block in the function.
void emitFunctionEntryLabel () override
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
void emitStartOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the start of their file.
void emitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
void emitXXStructor (const DataLayout &DL, const Constant *CV) override
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
void emitGlobalVariable (const GlobalVariable *GV) override
Emit the specified global variable to the .s file.
MCSymbol * GetCPISymbol (unsigned CPID) const override
Return the symbol for the specified constant pool entry.
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp)
void LowerPATCHABLE_FUNCTION_ENTER (const MachineInstr &MI)
void LowerPATCHABLE_FUNCTION_EXIT (const MachineInstr &MI)
void LowerPATCHABLE_TAIL_CALL (const MachineInstr &MI)
unsigned getISAEncoding () override
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
void emitMachineConstantPoolValue (MachineConstantPoolValue *MCPV) override
EmitMachineConstantPoolValue - Print a machine constantpool value to the .s file.
Public Member Functions inherited from llvm::AsmPrinter
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isDwarf64 () const
unsigned int getDwarfOffsetByteSize () const
Returns 4 for DWARF32 and 8 for DWARF64.
unsigned int getUnitLengthFieldByteSize () const
Returns 4 for DWARF32 and 12 for DWARF64.
dwarf::FormParams getDwarfFormParams () const
Returns information about the byte size of DW_FORM values.
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getMBBExceptionSym (const MachineBasicBlock &MBB)
MCSymbol * getAddrLabelSymbol (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
MCSymbol * createCallsiteSymbol (const MachineBasicBlock &MBB)
Creates a new symbol to be used for the beginning of a callsite at the specified basic block.
void takeDeletedSymbolsForFunction (const Function *F, std::vector< MCSymbol * > &Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
MCSymbol * getSymbolPreferLocal (const GlobalValue &GV) const
Similar to getSymbol() but preferred for references.
bool doesDwarfUseRelocationsAcrossSections () const
void setDwarfUsesRelocationsAcrossSections (bool Enable)
StringRef getConstantSectionSuffix (const Constant *C) const
Returns a section suffix (hot or unlikely) for the constant if profiles are available.
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
bool doFinalization (Module &M) override
Shut down the asmprinter.
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void emitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitStackUsage (const MachineFunction &MF)
void emitBBAddrMapSection (const MachineFunction &MF)
void emitKCFITrapEntry (const MachineFunction &MF, const MCSymbol *Symbol)
virtual void emitKCFITypeId (const MachineFunction &MF)
void emitPseudoProbe (const MachineInstr &MI)
void emitRemarksSection (remarks::RemarkStreamer &RS)
void emitPCSectionsLabel (const MachineFunction &MF, const MDNode &MD)
Emits a label as reference for PC sections.
void emitPCSections (const MachineFunction &MF)
Emits the PC sections collected from instructions.
CFISection getFunctionCFISectionType (const Function &F) const
Get the CFISection type for a function.
CFISection getFunctionCFISectionType (const MachineFunction &MF) const
Get the CFISection type for a function.
CFISection getModuleCFISectionType () const
Get the CFISection type for the module.
bool hasDebugInfo () const
Returns true if valid debug info is present.
bool needsSEHMoves ()
bool usesCFIWithoutEH () const
Since emitting CFI unwind information is entangled with supporting the exceptions, this returns true for platforms which use CFI unwind information for other purposes (debugging, sanitizers, ...) when MCAsmInfo::ExceptionsType == ExceptionHandling::None.
virtual void emitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
bool emitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void preprocessXXStructorList (const DataLayout &DL, const Constant *List, SmallVector< Structor, 8 > &Structors)
This method gathers an array of Structors and then sorts them out by Priority.
virtual void emitXXStructorList (const DataLayout &DL, const Constant *List, bool IsCtor)
This method emits llvm.global_ctors or llvm.global_dtors list.
void emitAlignment (Align Alignment, const GlobalObject *GV=nullptr, unsigned MaxBytesToEmit=0) const
Emit an alignment directive to the specified power of two boundary.
virtual const MCExpr * lowerConstant (const Constant *CV, const Constant *BaseCV=nullptr, uint64_t Offset=0)
Lower the specified LLVM Constant to an MCExpr.
void emitGlobalConstant (const DataLayout &DL, const Constant *CV, AliasMapTy *AliasList=nullptr)
EmitGlobalConstant - Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps ()
Emit the stack maps.
void addAsmPrinterHandler (std::unique_ptr< AsmPrinterHandler > Handler)
virtual void emitFunctionBodyStart ()
Targets can override this to emit stuff before the first basic block in the function.
virtual void emitBasicBlockStart (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the start of a basic block.
virtual void emitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual void emitFunctionDescriptor ()
virtual const MCExpr * lowerConstantPtrAuth (const ConstantPtrAuth &CPA)
virtual const MCExpr * lowerBlockAddressConstant (const BlockAddress &BA)
Lower the specified BlockAddress to an MCExpr.
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
virtual const MCSubtargetInfo * getIFuncMCSubtargetInfo () const
getSubtargetInfo() cannot be used where this is needed because we don't have a MachineFunction when we're lowering a GlobalIFunc, and getSubtargetInfo requires one.
virtual void emitMachOIFuncStubBody (Module &M, const GlobalIFunc &GI, MCSymbol *LazyPointer)
virtual void emitMachOIFuncStubHelperBody (Module &M, const GlobalIFunc &GI, MCSymbol *LazyPointer)
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (const Twine &Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void emitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void emitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void emitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void emitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void emitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
virtual void emitTTypeReference (const GlobalValue *GV, unsigned Encoding)
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4- or 8-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-or 8-byte offset of a string from the start of its section.
void emitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset" or ".quad Label + Offset" depending on the DWARF format.
void emitDwarfLengthOrOffset (uint64_t Value) const
Emit 32- or 64-bit value depending on the DWARF format.
void emitDwarfUnitLength (uint64_t Length, const Twine &Comment) const
Emit a unit length field.
MCSymbol * emitDwarfUnitLength (const Twine &Prefix, const Twine &Comment) const
Emit a unit length field.
void emitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual void emitDebugValue (const MCExpr *Value, unsigned Size) const
Emit the directive and value for debug thread local expression.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T>
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
void emitCOFFReplaceableFunctionData (Module &M)
Emits symbols and data to allow functions marked with the loader-replaceable attribute to be replaceable.
void emitCOFFFeatureSymbol (Module &M)
Emits the @feat.00 symbol indicating the features enabled in this module.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, StringRef Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void emitInlineAsmStart () const
Let the target do anything it needs to do before emitting inlineasm.
void emitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
virtual void emitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum class CFISection : unsigned { None = 0 , EH = 1 , Debug = 2 }
enum class SledKind : uint8_t {
FUNCTION_ENTER = 0 , FUNCTION_EXIT = 1 , TAIL_CALL = 2 , LOG_ARGS_ENTER = 3 ,
CUSTOM_EVENT = 4 , TYPED_EVENT = 5
}
using GOTEquivUsePair = std::pair<const GlobalVariable *, unsigned>
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
using AliasMapTy = DenseMap<uint64_t, SmallVector<const GlobalAlias *, 1>>
Print a general LLVM constant to the .s file.
Static Public Member Functions inherited from llvm::AsmPrinter
static Align getGVAlignment (const GlobalObject *GV, const DataLayout &DL, Align InAlign=Align(1))
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI = nullptr
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineDominatorTree.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE = nullptr
Optimization remark emitter.
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
DenseMap< const MachineBasicBlock *, SmallVector< MCSymbol *, 1 > > CurrentFnCallsiteSymbols
Vector of symbols marking the position of callsites in the current function, keyed by their containing basic block.
const StaticDataProfileInfo * SDPI = nullptr
Provides the profile information for constants.
const ProfileSummaryInfo * PSI = nullptr
The profile summary information.
MapVector< MBBSectionID, MBBSectionRange > MBBSectionRanges
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer, char &ID=AsmPrinter::ID)
virtual void emitJumpTableEntry (const MachineJumpTableInfo &MJTI, const MachineBasicBlock *MBB, unsigned uid) const
EmitJumpTableEntry - Emit a jump table entry for the specified MBB to the current stream.
virtual void emitGlobalAlias (const Module &M, const GlobalAlias &GA)
virtual bool shouldEmitWeakSwiftAsyncExtendedFramePointerFlags () const
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::AsmPrinter
MCSymbol * CurrentFnBegin = nullptr
MCSymbol * CurrentFnBeginLocal = nullptr
For dso_local functions, the current $local alias for the function.
SmallVector< std::unique_ptr< AsmPrinterHandler >, 1 > EHHandlers
A handle to the EH info emitter (if present).
SmallVector< std::unique_ptr< AsmPrinterHandler >, 2 > Handlers
size_t NumUserHandlers = 0
StackMaps SM
Detailed Description
Definition at line 31 of file ARMAsmPrinter.h.
Constructor & Destructor Documentation
ARMAsmPrinter()
ARMAsmPrinter::ARMAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) explicit
Definition at line 52 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::AsmPrinter(), ID, llvm::move(), and llvm::AsmPrinter::TM.
Member Function Documentation
emitConstantPool()
void llvm::ARMAsmPrinter::emitConstantPool () inline override virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 102 of file ARMAsmPrinter.h.
emitEndOfAsmFile()
void ARMAsmPrinter::emitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 548 of file ARMAsmPrinter.cpp.
References llvm::ARMBuildAttrs::ABI_optimization_goals, llvm::AsmPrinter::emitAlignment(), llvm::ARMTargetStreamer::emitAttribute(), emitNonLazySymbolPointer(), llvm::ARMTargetStreamer::finishAttributeSection(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MCObjectFileInfo::getNonLazySymbolPointerSection(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineModuleInfoMachO::GetThreadLocalGVStubList(), llvm::MCObjectFileInfo::getThreadLocalPointerSection(), llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
emitFunctionBodyEnd()
void ARMAsmPrinter::emitFunctionBodyEnd () override virtual
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 61 of file ARMAsmPrinter.cpp.
References llvm::MCDR_DataRegionEnd, and llvm::AsmPrinter::OutStreamer.
emitFunctionEntryLabel()
void ARMAsmPrinter::emitFunctionEntryLabel () override virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 70 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::emitFunctionEntryLabel(), llvm::AsmPrinter::emitLinkage(), llvm::MCSA_ELF_TypeFunction, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
emitGlobalVariable()
void ARMAsmPrinter::emitGlobalVariable (const GlobalVariable * GV) override virtual
Emit the specified global variable to the .s file.
EmitGlobalVariable - Emit the specified global variable to the .s file.
Reimplemented from llvm::AsmPrinter.
Definition at line 105 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::emitGlobalVariable().
emitInlineAsmEnd()
void ARMAsmPrinter::emitInlineAsmEnd (const MCSubtargetInfo & StartInfo, const MCSubtargetInfo * EndInfo) const override virtual
Let the target do anything it needs to do after emitting inlineasm.
This callback can be used restore the original mode in case the inlineasm contains directives to switch modes. StartInfo - the original subtarget info before inline asm EndInfo - the final subtarget info after parsing the inline asm, or NULL if the value is unknown.
Reimplemented from llvm::AsmPrinter.
Definition at line 492 of file ARMAsmPrinter.cpp.
References llvm::ARMTargetStreamer::emitCode16(), isThumb(), and llvm::AsmPrinter::OutStreamer.
emitInstruction()
void ARMAsmPrinter::emitInstruction (const MachineInstr *) override virtual
Targets should implement this to emit instructions.
CONSTPOOL_ENTRY - This instruction represents a floating constant pool in the function. The first operand is the ID# for this instruction, the second is the index into the MachineConstantPool that this is, the third is the size in bytes of this constant pool entry. The required alignment is specified on the basic block holding this MI.
Reimplemented from llvm::AsmPrinter.
Definition at line 1456 of file ARMAsmPrinter.cpp.
References llvm::MCInstBuilder::addExpr(), llvm::MCInstBuilder::addImm(), llvm::MCInst::addOperand(), llvm::MCInstBuilder::addReg(), llvm::ARMCC::AL, assert(), llvm::sampleprof::Base, llvm::MachineConstantPoolEntry::ConstVal, llvm::convertAddSubFlagsOpcode(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::ARM::createLower16(), llvm::MCOperand::createReg(), llvm::MCBinaryExpr::createSub(), llvm::ARM::createUpper16(), DL, llvm::ARMTargetStreamer::emitARMWinCFIAllocStack(), llvm::ARMTargetStreamer::emitARMWinCFIEpilogEnd(), llvm::ARMTargetStreamer::emitARMWinCFIEpilogStart(), llvm::ARMTargetStreamer::emitARMWinCFINop(), llvm::ARMTargetStreamer::emitARMWinCFIPrologEnd(), llvm::ARMTargetStreamer::emitARMWinCFISaveFRegs(), llvm::ARMTargetStreamer::emitARMWinCFISaveLR(), llvm::ARMTargetStreamer::emitARMWinCFISaveRegMask(), llvm::ARMTargetStreamer::emitARMWinCFISaveSP(), llvm::AsmPrinter::emitGlobalConstant(), llvm::ARMTargetStreamer::emitInst(), emitJumpTableAddrs(), emitJumpTableInsts(), emitJumpTableTBInst(), emitMachineConstantPoolValue(), llvm::AsmPrinter::EmitToStreamer(), llvm::MachineInstr::FrameSetup, getBFLabel(), GetCPISymbol(), llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::ARMSubtarget::getFramePointerReg(), llvm::AsmPrinter::getFunctionNumber(), getPICLabel(), llvm::AsmPrinter::getSubtargetInfo(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::ARMSubtarget::isTargetDarwin(), llvm::ARMSubtarget::isTargetWindows(), llvm_unreachable, llvm::LowerARMMachineInstrToMCInst(), LowerPATCHABLE_FUNCTION_ENTER(), LowerPATCHABLE_FUNCTION_EXIT(), LowerPATCHABLE_TAIL_CALL(), llvm::MachineConstantPoolEntry::MachineCPVal, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, llvm::AsmPrinter::MF, MI, Opc, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::MCInst::setOpcode(), and llvm::MachineConstantPoolEntry::Val.
emitJumpTableAddrs()
void ARMAsmPrinter::emitJumpTableAddrs (const MachineInstr * MI)
Definition at line 1001 of file ARMAsmPrinter.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::emitAlignment(), llvm::MachineOperand::getIndex(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::AsmPrinter::isPositionIndependent(), MBB, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT32, llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by emitInstruction().
emitJumpTableInsts()
void ARMAsmPrinter::emitJumpTableInsts (const MachineInstr * MI)
Definition at line 1047 of file ARMAsmPrinter.cpp.
References llvm::ARMCC::AL, llvm::MCSymbolRefExpr::create(), llvm::AsmPrinter::emitAlignment(), llvm::AsmPrinter::EmitToStreamer(), llvm::MachineOperand::getIndex(), llvm::MachineJumpTableInfo::getJumpTables(), MBB, llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by emitInstruction().
emitJumpTableTBInst()
void ARMAsmPrinter::emitJumpTableTBInst (const MachineInstr * MI, unsigned OffsetWidth)
Definition at line 1075 of file ARMAsmPrinter.cpp.
References assert(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createDiv(), llvm::MCBinaryExpr::createSub(), llvm::AsmPrinter::emitAlignment(), GetCPISymbol(), llvm::MachineOperand::getIndex(), llvm::MachineJumpTableInfo::getJumpTables(), MBB, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT16, llvm::MCDR_DataRegionJT8, llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by emitInstruction().
emitMachineConstantPoolValue()
void ARMAsmPrinter::emitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) override virtual
EmitMachineConstantPoolValue - Print a machine constantpool value to the .s file.
Reimplemented from llvm::AsmPrinter.
Definition at line 923 of file ARMAsmPrinter.cpp.
References assert(), llvm::cast(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), DL, llvm::AsmPrinter::emitGlobalConstant(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::ARMConstantPoolValue::getLabelId(), llvm::AsmPrinter::getMBBExceptionSym(), llvm::ARMConstantPoolValue::getModifier(), getModifierSpecifier(), llvm::ARMConstantPoolValue::getPCAdjustment(), getPICLabel(), llvm::AsmPrinter::getSymbol(), llvm::MachineConstantPoolValue::getType(), llvm::ARMConstantPoolValue::isBlockAddress(), llvm::ARMConstantPoolValue::isExtSymbol(), llvm::ARMConstantPoolValue::isGlobalValue(), llvm::ARMConstantPoolValue::isLSDA(), llvm::ARMConstantPoolValue::isMachineBasicBlock(), llvm::ARMConstantPoolValue::isPromotedGlobal(), MBB, llvm::AsmPrinter::MF, llvm::ARMII::MO_NONLAZY, llvm::ARMConstantPoolValue::mustAddCurrentAddress(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitInstruction().
emitStartOfAsmFile()
void ARMAsmPrinter::emitStartOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 507 of file ARMAsmPrinter.cpp.
References llvm::ARMTargetStreamer::emitSyntaxUnified(), llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
emitXXStructor()
void ARMAsmPrinter::emitXXStructor (const DataLayout & DL, const Constant * CV) override virtual
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented from llvm::AsmPrinter.
Definition at line 91 of file ARMAsmPrinter.cpp.
References assert(), llvm::MCSymbolRefExpr::create(), DL, llvm::dyn_cast(), llvm::AsmPrinter::getDataLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ARMII::MO_NO_FLAG, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::ARM::S_None, llvm::ARM::S_TARGET1, Size, and llvm::Constant::stripPointerCasts().
getCodeViewJumpTableInfo()
std::tuple< const MCSymbol *, uint64_t, const MCSymbol *, codeview::JumpTableEntrySize > ARMAsmPrinter::getCodeViewJumpTableInfo (int JTI, const MachineInstr * BranchInstr, const MCSymbol * BranchLabel) const override virtual
Gets information required to create a CodeView debug symbol for a jump table.
Return value is <Base Address, Base Offset, Branch Address, Entry Size>
Reimplemented from llvm::AsmPrinter.
Definition at line 1130 of file ARMAsmPrinter.cpp.
References GetCPISymbol(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm_unreachable, llvm::codeview::Pointer, llvm::codeview::UInt16ShiftLeft, llvm::codeview::UInt32, and llvm::codeview::UInt8ShiftLeft.
GetCPISymbol()
MCSymbol * ARMAsmPrinter::GetCPISymbol (unsigned CPID) const override virtual
Return the symbol for the specified constant pool entry.
GetCPISymbol - Return the symbol for the specified constant pool entry.
Reimplemented from llvm::AsmPrinter.
Definition at line 269 of file ARMAsmPrinter.cpp.
References DL, llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getFunctionNumber(), and llvm::AsmPrinter::OutContext.
Referenced by emitInstruction(), emitJumpTableTBInst(), getCodeViewJumpTableInfo(), lowerOperand(), and printOperand().
getISAEncoding()
unsigned llvm::ARMAsmPrinter::getISAEncoding () inline override virtual
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented from llvm::AsmPrinter.
Definition at line 138 of file ARMAsmPrinter.h.
References llvm::Triple::ARMSubArch_v6m, llvm::Triple::ARMSubArch_v7m, llvm::ARM::DW_ISA_ARM_arm, llvm::ARM::DW_ISA_ARM_thumb, isThumb(), and llvm::AsmPrinter::TM.
getPassName()
StringRef llvm::ARMAsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 75 of file ARMAsmPrinter.h.
getTM()
const ARMBaseTargetMachine & ARMAsmPrinter::getTM () const
Definition at line 57 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::TM.
lowerOperand()
bool ARMAsmPrinter::lowerOperand (const MachineOperand & MO, MCOperand & MCOp)
Definition at line 85 of file ARMMCInstLower.cpp.
References assert(), llvm::bit_cast(), llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createDFPImm(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::ConstantFP::getValueAPF(), llvm::APFloatBase::IEEEdouble(), llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, llvm::AsmPrinter::OutContext, and llvm::APFloatBase::rmTowardZero.
Referenced by llvm::LowerARMMachineInstrToMCInst().
LowerPATCHABLE_FUNCTION_ENTER()
void ARMAsmPrinter::LowerPATCHABLE_FUNCTION_ENTER (const MachineInstr & MI)
Definition at line 232 of file ARMMCInstLower.cpp.
References llvm::AsmPrinter::FUNCTION_ENTER, and MI.
Referenced by emitInstruction().
LowerPATCHABLE_FUNCTION_EXIT()
void ARMAsmPrinter::LowerPATCHABLE_FUNCTION_EXIT (const MachineInstr & MI)
Definition at line 237 of file ARMMCInstLower.cpp.
References llvm::AsmPrinter::FUNCTION_EXIT, and MI.
Referenced by emitInstruction().
LowerPATCHABLE_TAIL_CALL()
void ARMAsmPrinter::LowerPATCHABLE_TAIL_CALL (const MachineInstr & MI)
Definition at line 242 of file ARMMCInstLower.cpp.
References MI, and llvm::AsmPrinter::TAIL_CALL.
Referenced by emitInstruction().
PrintAsmMemoryOperand()
bool ARMAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 464 of file ARMAsmPrinter.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::ARMInstPrinter::getRegisterName(), llvm::MachineOperand::isReg(), and MI.
PrintAsmOperand()
bool ARMAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & O) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate for machine specific ExtraCodes or when the arch-independent handling would be too complex otherwise.
Reimplemented from llvm::AsmPrinter.
Definition at line 289 of file ARMAsmPrinter.cpp.
References contains(), F, llvm::getImm(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::ARMInstPrinter::getRegisterName(), llvm::MachineOperand::isImm(), llvm::ARMBaseTargetMachine::isLittleEndian(), llvm::MachineOperand::isReg(), llvm::AsmPrinter::MF, MI, llvm::InlineAsm::MIOp_FirstOperand, llvm::AsmPrinter::PrintAsmOperand(), printOperand(), SubReg, llvm::AsmPrinter::TM, and TRI.
printOperand()
void ARMAsmPrinter::printOperand (const MachineInstr * MI, int OpNum, raw_ostream & O)
Definition at line 218 of file ARMAsmPrinter.cpp.
References assert(), contains(), GetCPISymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getReg(), llvm::ARMInstPrinter::getRegisterName(), llvm::MachineOperand::getSubReg(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::AsmPrinter::MAI, llvm::AsmPrinter::MF, MI, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::ARMII::MO_HI16, llvm::ARMII::MO_HI_0_7, llvm::ARMII::MO_HI_8_15, llvm::MachineOperand::MO_Immediate, llvm::ARMII::MO_LO16, llvm::ARMII::MO_LO_0_7, llvm::ARMII::MO_LO_8_15, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MCSymbol::print(), PrintSymbolOperand(), and TRI.
Referenced by PrintAsmOperand().
PrintSymbolOperand()
void ARMAsmPrinter::PrintSymbolOperand (const MachineOperand & MO, raw_ostream & OS) override virtual
Print the MachineOperand as a symbol.
Targets with complex handling of symbol references should override the base implementation.
Reimplemented from llvm::AsmPrinter.
Definition at line 197 of file ARMAsmPrinter.cpp.
References assert(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::isGlobal(), llvm::AsmPrinter::MAI, llvm::ARMII::MO_HI16, llvm::ARMII::MO_HI_0_7, llvm::ARMII::MO_HI_8_15, llvm::ARMII::MO_LO16, llvm::ARMII::MO_LO_0_7, llvm::ARMII::MO_LO_8_15, and llvm::AsmPrinter::printOffset().
Referenced by printOperand().
runOnMachineFunction()
bool ARMAsmPrinter::runOnMachineFunction (MachineFunction & F) override virtual
runOnMachineFunction - This uses the emitInstruction() method to print assembly for each instruction.
Implements llvm::MachineFunctionPass.
Definition at line 115 of file ARMAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::Aggressive, llvm::ARMCC::AL, llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::emitAlignment(), llvm::ARMTargetStreamer::emitCode16(), llvm::AsmPrinter::emitFunctionBody(), llvm::AsmPrinter::EmitToStreamer(), llvm::AsmPrinter::emitXRayTable(), F, llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, Local, llvm::AsmPrinter::MF, llvm::None, llvm::AsmPrinter::OutStreamer, llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, llvm::AsmPrinter::SetupMachineFunction(), and llvm::AsmPrinter::TM.
Member Data Documentation
ID
char ARMAsmPrinter::ID = 0 static
Definition at line 33 of file ARMAsmPrinter.h.
Referenced by ARMAsmPrinter().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMAsmPrinter.h
lib/Target/ARM/ARMAsmPrinter.cpp
lib/Target/ARM/ARMMCInstLower.cpp