LLVM: llvm::AVRTargetStreamer Class Reference
llvm::AVRTargetStreamer Class Reference
A generic AVR target output stream.
#include "Target/AVR/MCTargetDesc/AVRTargetStreamer.h"
Public Member Functions
AVRTargetStreamer (MCStreamer &S)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
A generic AVR target output stream.
Definition at line 18 of file AVRTargetStreamer.h.
Constructor & Destructor Documentation
AVRTargetStreamer()
llvm::AVRTargetStreamer::AVRTargetStreamer (MCStreamer & S) explicit
Definition at line 19 of file AVRTargetStreamer.cpp.
References llvm::MCTargetStreamer::MCTargetStreamer().
Referenced by llvm::AVRELFStreamer::AVRELFStreamer(), and llvm::AVRTargetAsmStreamer::AVRTargetAsmStreamer().
The documentation for this class was generated from the following files:
lib/Target/AVR/MCTargetDesc/AVRTargetStreamer.h
lib/Target/AVR/MCTargetDesc/AVRTargetStreamer.cpp