LLVM: llvm::orc::LinkGraphLayer Class Reference
llvm::orc::LinkGraphLayer Class Reference abstract
#include "llvm/ExecutionEngine/Orc/LinkGraphLayer.h"
Public Member Functions
LinkGraphLayer (ExecutionSession &ES)
virtual ~LinkGraphLayer ()
ExecutionSession & getExecutionSession ()
virtual Error add (ResourceTrackerSP RT, std::unique_ptr< jitlink::LinkGraph > G, MaterializationUnit::Interface I)
Adds a LinkGraph to the JITDylib for the given ResourceTracker.
Error add (ResourceTrackerSP RT, std::unique_ptr< jitlink::LinkGraph > G)
Adds a LinkGraph to the JITDylib for the given ResourceTracker.
Error add (JITDylib &JD, std::unique_ptr< jitlink::LinkGraph > G, MaterializationUnit::Interface I)
Adds a LinkGraph to the given JITDylib.
Error add (JITDylib &JD, std::unique_ptr< jitlink::LinkGraph > G)
Adds a LinkGraph to the given JITDylib.
virtual void emit (std::unique_ptr< MaterializationResponsibility > R, std::unique_ptr< jitlink::LinkGraph > G)=0
Emit should materialize the given IR.
MaterializationUnit::Interface getInterface (jitlink::LinkGraph &G)
Get the interface for the given LinkGraph.
Static Public Member Functions
static JITSymbolFlags getJITSymbolFlagsForSymbol (jitlink::Symbol &Sym)
Get the JITSymbolFlags for the given symbol.
Detailed Description
Definition at line 27 of file LinkGraphLayer.h.
Constructor & Destructor Documentation
LinkGraphLayer()
llvm::orc::LinkGraphLayer::LinkGraphLayer (ExecutionSession & ES) inline
Definition at line 29 of file LinkGraphLayer.h.
Referenced by llvm::orc::LinkGraphLinkingLayer::LinkGraphLinkingLayer(), and llvm::orc::LinkGraphLinkingLayer::LinkGraphLinkingLayer().
~LinkGraphLayer()
llvm::orc::LinkGraphLayer::~LinkGraphLayer () virtual default
Member Function Documentation
add() [1/4]
Error llvm::orc::LinkGraphLayer::add (JITDylib & JD, std::unique_ptr< jitlink::LinkGraph > G) inline
Adds a LinkGraph to the given JITDylib.
The interface for the object will be built using getLinkGraphInterface.
Definition at line 54 of file LinkGraphLayer.h.
References add(), G, and llvm::orc::JITDylib::getDefaultResourceTracker().
add() [2/4]
Error llvm::orc::LinkGraphLayer::add (JITDylib & JD, std::unique_ptr< jitlink::LinkGraph > G, MaterializationUnit::Interface I) inline
Adds a LinkGraph to the given JITDylib.
Definition at line 47 of file LinkGraphLayer.h.
References add(), G, llvm::orc::JITDylib::getDefaultResourceTracker(), and I.
add() [3/4]
Error llvm::orc::LinkGraphLayer::add (ResourceTrackerSP RT, std::unique_ptr< jitlink::LinkGraph > G) inline
Adds a LinkGraph to the JITDylib for the given ResourceTracker.
The interface for the graph will be built using getLinkGraphInterface.
Definition at line 41 of file LinkGraphLayer.h.
References add(), G, and getInterface().
add() [4/4]
Error llvm::orc::LinkGraphLayer::add (ResourceTrackerSP RT, std::unique_ptr< jitlink::LinkGraph > G, MaterializationUnit::Interface I) inline virtual
Adds a LinkGraph to the JITDylib for the given ResourceTracker.
Definition at line 99 of file LinkGraphLayer.h.
References G, and I.
Referenced by add(), add(), and add().
emit()
virtual void llvm::orc::LinkGraphLayer::emit (std::unique_ptr< MaterializationResponsibility > R, std::unique_ptr< jitlink::LinkGraph > G) pure virtual
Emit should materialize the given IR.
Implemented in llvm::orc::LinkGraphLinkingLayer, and llvm::orc::ObjectLinkingLayer.
References G, getInterface(), and getJITSymbolFlagsForSymbol().
getExecutionSession()
ExecutionSession & llvm::orc::LinkGraphLayer::getExecutionSession () inline
Definition at line 33 of file LinkGraphLayer.h.
Referenced by llvm::orc::ObjectLinkingLayer::emit(), and llvm::orc::LinkGraphLinkingLayer::~LinkGraphLinkingLayer().
getInterface()
MaterializationUnit::Interface llvm::orc::LinkGraphLayer::getInterface (jitlink::LinkGraph & G)
Get the interface for the given LinkGraph.
Definition at line 45 of file LinkGraphLayer.cpp.
References assert(), G, getJITSymbolFlagsForSymbol(), llvm::orc::MaterializationUnit::Interface::InitSymbol, llvm::jitlink::Local, and llvm::orc::MaterializationUnit::Interface::SymbolFlags.
Referenced by add(), and emit().
getJITSymbolFlagsForSymbol()
JITSymbolFlags llvm::orc::LinkGraphLayer::getJITSymbolFlagsForSymbol (jitlink::Symbol & Sym) static
Get the JITSymbolFlags for the given symbol.
Definition at line 75 of file LinkGraphLayer.cpp.
References llvm::JITSymbolFlags::Callable, llvm::jitlink::Default, llvm::JITSymbolFlags::Exported, llvm::jitlink::Symbol::getLinkage(), llvm::jitlink::Symbol::getScope(), llvm::jitlink::Symbol::isCallable(), llvm::JITSymbolFlags::MaterializationSideEffectsOnly, llvm::jitlink::SideEffectsOnly, llvm::jitlink::Weak, and llvm::JITSymbolFlags::Weak.
Referenced by emit(), getInterface(), and llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LinkGraphLayer.h
lib/ExecutionEngine/Orc/LinkGraphLayer.cpp