LLVM: Predicate Class Reference
Predicate Class Reference
Public Member Functions
Predicate (std::function< bool(const MachineInstr &)> Pred)
bool operator() (const MachineInstr &MI) const
Predicate operator! () const
Predicate operator&& (const Predicate &RHS) const
Predicate operator|| (const Predicate &RHS) const
Detailed Description
Definition at line 376 of file AMDGPURegBankLegalizeRules.cpp.
Constructor & Destructor Documentation
Predicate()
Predicate::Predicate (std::function< bool(const MachineInstr &)> Pred) inline
Definition at line 401 of file AMDGPURegBankLegalizeRules.cpp.
Member Function Documentation
operator!()
Predicate Predicate::operator! () const inline
Definition at line 422 of file AMDGPURegBankLegalizeRules.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
operator&&()
Predicate Predicate::operator&& (const Predicate & RHS) const inline
Definition at line 431 of file AMDGPURegBankLegalizeRules.cpp.
References llvm::SmallVectorImpl< T >::append(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
operator()()
bool Predicate::operator() (const MachineInstr & MI) const inline
Definition at line 405 of file AMDGPURegBankLegalizeRules.cpp.
References MI.
operator||()
Predicate Predicate::operator|| (const Predicate & RHS) const inline
Definition at line 447 of file AMDGPURegBankLegalizeRules.cpp.
References llvm::SmallVectorImpl< T >::append(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPURegBankLegalizeRules.cpp