LLVM: llvm::DbgLabelRecord Class Reference
llvm::DbgLabelRecord Class Reference
Records a position in IR for a source label (DILabel).
#include "llvm/IR/DebugProgramInstruction.h"
Public Member Functions
LLVM_ABI DbgLabelRecord (DILabel *Label, DebugLoc DL)
LLVM_ABI DbgLabelRecord * clone () const
LLVM_ABI void print (raw_ostream &O, bool IsForDebug=false) const
LLVM_ABI void print (raw_ostream &ROS, ModuleSlotTracker &MST, bool IsForDebug) const
LLVM_ABI DbgLabelInst * createDebugIntrinsic (Module *M, Instruction *InsertBefore) const
void setLabel (DILabel *NewLabel)
DILabel * getLabel () const
MDNode * getRawLabel () const
Public Member Functions inherited from llvm::DbgRecord
DbgRecord (Kind RecordKind, DebugLoc DL)
LLVM_ABI bool isEquivalentTo (const DbgRecord &R) const
Same as isIdenticalToWhenDefined but checks DebugLoc too.
Kind getRecordKind () const
void setMarker (DbgMarker *M)
DbgMarker * getMarker ()
const DbgMarker * getMarker () const
LLVM_ABI BasicBlock * getBlock ()
LLVM_ABI const BasicBlock * getBlock () const
LLVM_ABI Function * getFunction ()
LLVM_ABI const Function * getFunction () const
LLVM_ABI Module * getModule ()
LLVM_ABI const Module * getModule () const
LLVM_ABI LLVMContext & getContext ()
LLVM_ABI const LLVMContext & getContext () const
LLVM_ABI const Instruction * getInstruction () const
LLVM_ABI const BasicBlock * getParent () const
LLVM_ABI BasicBlock * getParent ()
LLVM_ABI void removeFromParent ()
LLVM_ABI void eraseFromParent ()
DbgRecord * getNextNode ()
DbgRecord * getPrevNode ()
LLVM_ABI void insertBefore (DbgRecord *InsertBefore)
LLVM_ABI void insertAfter (DbgRecord *InsertAfter)
LLVM_ABI void moveBefore (DbgRecord *MoveBefore)
LLVM_ABI void moveAfter (DbgRecord *MoveAfter)
LLVM_ABI void insertBefore (self_iterator InsertBefore)
LLVM_ABI void insertAfter (self_iterator InsertAfter)
LLVM_ABI void moveBefore (self_iterator MoveBefore)
LLVM_ABI void moveAfter (self_iterator MoveAfter)
DebugLoc getDebugLoc () const
void setDebugLoc (DebugLoc Loc)
LLVM_ABI void dump () const
LLVM_ABI void deleteRecord ()
Methods that dispatch to subclass implementations.
LLVM_ABI DbgRecord * clone () const
LLVM_ABI void print (raw_ostream &O, bool IsForDebug=false) const
LLVM_ABI void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug) const
LLVM_ABI bool isIdenticalToWhenDefined (const DbgRecord &R) const
LLVM_ABI DbgInfoIntrinsic * createDebugIntrinsic (Module *M, Instruction *InsertBefore) const
Convert this DbgRecord back into an appropriate llvm.dbg.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >, ilist_detail::compute_node_options< DbgRecord, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< DbgRecord, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< DbgRecord, Options... >::type::parent_ty *Parent)
Static Public Member Functions
static LLVM_ABI DbgLabelRecord * createUnresolvedDbgLabelRecord (MDNode *Label, MDNode *DL)
For use during parsing; creates a DbgLabelRecord from as-of-yet unresolved MDNodes.
static bool classof (const DbgRecord *E)
Support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::DbgRecord
enum Kind : uint8_t { ValueKind , LabelKind }
Subclass discriminator.
using self_iterator = simple_ilist<DbgRecord>::iterator
using const_self_iterator = simple_ilist<DbgRecord>::const_iterator
Public Attributes inherited from llvm::DbgRecord
DbgMarker * Marker = nullptr
Marker that this DbgRecord is linked into.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::DbgRecord
~DbgRecord ()=default
Similarly to Value, we avoid paying the cost of a vtable by protecting the dtor and having deleteRecord dispatch cleanup.
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >
ilist_node_impl ()=default
Protected Attributes inherited from llvm::DbgRecord
DebugLoc DbgLoc
Kind RecordKind
Subclass discriminator.
Detailed Description
Records a position in IR for a source label (DILabel).
Corresponds to the llvm.dbg.label intrinsic.
Definition at line 237 of file DebugProgramInstruction.h.
Constructor & Destructor Documentation
DbgLabelRecord()
llvm::DbgLabelRecord::DbgLabelRecord (DILabel * Label, DebugLoc DL)
Definition at line 152 of file DebugProgramInstruction.cpp.
References assert(), llvm::DbgRecord::DbgRecord(), DL, and llvm::DbgRecord::LabelKind.
Member Function Documentation
classof()
bool llvm::DbgLabelRecord::classof (const DbgRecord * E) inline static
Support type inquiry through isa, cast, and dyn_cast.
Definition at line 267 of file DebugProgramInstruction.h.
References llvm::DbgRecord::DbgRecord(), E(), and llvm::DbgRecord::LabelKind.
clone()
DbgLabelRecord * llvm::DbgLabelRecord::clone () const
Definition at line 399 of file DebugProgramInstruction.cpp.
References llvm::DbgRecord::getDebugLoc(), and getLabel().
createDebugIntrinsic()
DbgLabelInst * llvm::DbgLabelRecord::createDebugIntrinsic (Module * M, Instruction * InsertBefore) const
Definition at line 461 of file DebugProgramInstruction.cpp.
References llvm::cast(), llvm::CallInst::Create(), llvm::MetadataAsValue::get(), llvm::DbgRecord::getContext(), llvm::DbgRecord::getDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), getLabel(), and llvm::Intrinsic::getOrInsertDeclaration().
createUnresolvedDbgLabelRecord()
DbgLabelRecord * llvm::DbgLabelRecord::createUnresolvedDbgLabelRecord (MDNode * Label, MDNode * DL) static
For use during parsing; creates a DbgLabelRecord from as-of-yet unresolved MDNodes.
Trying to access the resulting DbgLabelRecord's fields before they are resolved, or if they resolve to the wrong type, will result in a crash.
Definition at line 157 of file DebugProgramInstruction.cpp.
References DL.
Referenced by upgradeDbgIntrinsicToDbgRecord().
getLabel()
DILabel * llvm::DbgLabelRecord::getLabel () const inline
Definition at line 263 of file DebugProgramInstruction.h.
References llvm::MDNode::get().
Referenced by clone(), and createDebugIntrinsic().
getRawLabel()
MDNode * llvm::DbgLabelRecord::getRawLabel () const inline
Definition at line 264 of file DebugProgramInstruction.h.
print() [1/2]
void DbgLabelRecord::print (raw_ostream & O, bool IsForDebug = false) const
Definition at line 5179 of file AsmWriter.cpp.
References getModuleFromDPI(), and print().
print() [2/2]
void DbgLabelRecord::print (raw_ostream & ROS, ModuleSlotTracker & MST, bool IsForDebug) const
Definition at line 5202 of file AsmWriter.cpp.
References F, llvm::ModuleSlotTracker::getMachine(), getModuleFromDPI(), llvm::ModuleSlotTracker::incorporateFunction(), and llvm::DbgRecord::Marker.
setLabel()
void llvm::DbgLabelRecord::setLabel (DILabel * NewLabel) inline
Definition at line 262 of file DebugProgramInstruction.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugProgramInstruction.h
lib/IR/AsmWriter.cpp
lib/IR/DebugProgramInstruction.cpp