LLVM: llvm::RegAllocPriorityAdvisorProvider Class Reference
llvm::RegAllocPriorityAdvisorProvider Class Reference abstract
Common provider for getting the priority advisor and logging rewards.
#include "llvm/CodeGen/RegAllocPriorityAdvisor.h"
Public Types
enum class AdvisorMode : int { Default , Release , Development , Dummy }
Public Member Functions
RegAllocPriorityAdvisorProvider (AdvisorMode Mode)
virtual ~RegAllocPriorityAdvisorProvider ()=default
virtual void logRewardIfNeeded (const MachineFunction &MF, function_ref< float()> GetReward)
virtual std::unique_ptr< RegAllocPriorityAdvisor > getAdvisor (const MachineFunction &MF, const RAGreedy &RA, SlotIndexes &SI)=0
AdvisorMode getAdvisorMode () const
Detailed Description
Common provider for getting the priority advisor and logging rewards.
Legacy analysis forwards all calls to this provider. New analysis serves the provider as the analysis result. Expensive setup is done in the constructor, so that the advisor can be created quickly for every machine function. TODO: Remove once legacy PM support is dropped.
Definition at line 79 of file RegAllocPriorityAdvisor.h.
Member Enumeration Documentation
AdvisorMode
enum class llvm::RegAllocPriorityAdvisorProvider::AdvisorMode : int strong
Enumerator
Default
Release
Development
Dummy
Definition at line 81 of file RegAllocPriorityAdvisor.h.
Constructor & Destructor Documentation
RegAllocPriorityAdvisorProvider()
llvm::RegAllocPriorityAdvisorProvider::RegAllocPriorityAdvisorProvider (AdvisorMode Mode) inline
Definition at line 83 of file RegAllocPriorityAdvisor.h.
Referenced by INITIALIZE_PASS(), and llvm::ReleaseModePriorityAdvisorProvider::ReleaseModePriorityAdvisorProvider().
~RegAllocPriorityAdvisorProvider()
virtual llvm::RegAllocPriorityAdvisorProvider::~RegAllocPriorityAdvisorProvider () virtual default
Member Function Documentation
getAdvisor()
virtual std::unique_ptr< RegAllocPriorityAdvisor > llvm::RegAllocPriorityAdvisorProvider::getAdvisor (const MachineFunction & MF, const RAGreedy & RA, SlotIndexes & SI) pure virtual
Implemented in llvm::ReleaseModePriorityAdvisorProvider.
References RA.
Referenced by INITIALIZE_PASS().
getAdvisorMode()
AdvisorMode llvm::RegAllocPriorityAdvisorProvider::getAdvisorMode () const inline
Definition at line 94 of file RegAllocPriorityAdvisor.h.
logRewardIfNeeded()
virtual void llvm::RegAllocPriorityAdvisorProvider::logRewardIfNeeded (const MachineFunction & MF, function_ref< float()> GetReward) inline virtual
Definition at line 87 of file RegAllocPriorityAdvisor.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/RegAllocPriorityAdvisor.h