LLVM: llvm::InnerLoopAndEpilogueVectorizer Class Reference
llvm::InnerLoopAndEpilogueVectorizer Class Reference abstract
An extension of the inner loop vectorizer that creates a skeleton for a vectorized loop that has its epilogue (residual) also vectorized.
Public Member Functions
InnerLoopAndEpilogueVectorizer (Loop *OrigLoop, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, EpilogueLoopVectorizationInfo &EPI, LoopVectorizationCostModel *CM, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI, GeneratedRTChecks &Checks, VPlan &Plan)
BasicBlock * createVectorizedLoopSkeleton () final
Create a new empty loop that will contain vectorized instructions later on, while the old loop will be used as the scalar remainder.
virtual BasicBlock * createEpilogueVectorizedLoopSkeleton ()=0
The interface for creating a vectorized skeleton using one of two different strategies, each corresponding to one execution of the vplan as described above.
Public Member Functions inherited from llvm::InnerLoopVectorizer
InnerLoopVectorizer (Loop *OrigLoop, PredicatedScalarEvolution &PSE, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, AssumptionCache *AC, OptimizationRemarkEmitter *ORE, ElementCount VecWidth, ElementCount MinProfitableTripCount, unsigned UnrollFactor, LoopVectorizationCostModel *CM, BlockFrequencyInfo *BFI, ProfileSummaryInfo *PSI, GeneratedRTChecks &RTChecks, VPlan &Plan)
virtual ~InnerLoopVectorizer ()=default
void fixVectorizedLoop (VPTransformState &State)
Fix the vectorized code, taking care of header phi's, and more.
void fixNonInductionPHIs (VPTransformState &State)
Fix the non-induction PHIs in Plan.
Value * getTripCount () const
Returns the original loop trip count.
void setTripCount (Value *TC)
Used to set the trip count after ILV's construction and after the preheader block has been executed.
BasicBlock * getAdditionalBypassBlock () const
Return the additional bypass block which targets the scalar loop by skipping the epilogue loop after completing the main loop.
Public Attributes
EpilogueLoopVectorizationInfo & EPI
Holds and updates state information required to vectorize the main loop and its epilogue in two separate passes.
Additional Inherited Members
Protected Member Functions inherited from llvm::InnerLoopVectorizer
Value * getOrCreateVectorTripCount (BasicBlock *InsertBlock)
Returns (and creates if needed) the trip count of the widened loop.
Value * createIterationCountCheck (ElementCount VF, unsigned UF) const
void emitIterationCountCheck (BasicBlock *Bypass)
Emit a bypass check to see if the vector trip count is zero, including if it overflows.
void createVectorLoopSkeleton (StringRef Prefix)
Emit basic blocks (prefixed with Prefix) for the iteration check, vector loop preheader, middle block and scalar preheader.
virtual void printDebugTracesAtStart ()
Allow subclasses to override and print debug traces before/after vplan execution, when trace information is requested.
virtual void printDebugTracesAtEnd ()
void introduceCheckBlockInVPlan (BasicBlock *CheckIRBB)
Introduces a new VPIRBasicBlock for CheckIRBB to Plan between the vector preheader and its predecessor, also connecting the new block to the scalar preheader.
Protected Attributes inherited from llvm::InnerLoopVectorizer
Loop * OrigLoop
The original loop.
PredicatedScalarEvolution & PSE
A wrapper around ScalarEvolution used to add runtime SCEV checks.
LoopInfo * LI
Loop Info.
DominatorTree * DT
Dominator Tree.
const TargetLibraryInfo * TLI
Target Library Info.
const TargetTransformInfo * TTI
Target Transform Info.
AssumptionCache * AC
Assumption Cache.
OptimizationRemarkEmitter * ORE
Interface to emit optimization remarks.
ElementCount VF
The vectorization SIMD factor to use.
ElementCount MinProfitableTripCount
unsigned UF
The vectorization unroll factor to use.
IRBuilder Builder
The builder that we use.
BasicBlock * LoopVectorPreHeader = nullptr
The vector-loop preheader.
BasicBlock * LoopScalarPreHeader = nullptr
The scalar-loop preheader.
BasicBlock * LoopMiddleBlock = nullptr
Middle Block between the vector and the scalar.
Value * TripCount = nullptr
Trip count of the original loop.
Value * VectorTripCount = nullptr
Trip count of the widened loop (TripCount - TripCount % (VF*UF))
LoopVectorizationCostModel * Cost
The profitablity analysis.
BlockFrequencyInfo * BFI
BFI and PSI are used to check for profile guided size optimizations.
ProfileSummaryInfo * PSI
GeneratedRTChecks & RTChecks
Structure to hold information about generated runtime checks, responsible for cleaning the checks, if vectorization turns out unprofitable.
BasicBlock * AdditionalBypassBlock = nullptr
The additional bypass block which conditionally skips over the epilogue loop after executing the main loop.
VPlan & Plan
VPBlockBase * VectorPHVPB
The vector preheader block of Plan, used as target for check blocks introduced during skeleton creation.
Detailed Description
An extension of the inner loop vectorizer that creates a skeleton for a vectorized loop that has its epilogue (residual) also vectorized.
The idea is to run the vplan on a given loop twice, firstly to setup the skeleton and vectorize the main loop, and secondly to complete the skeleton from the first step and vectorize the epilogue. This is achieved by deriving two concrete strategy classes from this base class and invoking them in succession from the loop vectorizer planner.
Definition at line 666 of file LoopVectorize.cpp.
Constructor & Destructor Documentation
InnerLoopAndEpilogueVectorizer()
llvm::InnerLoopAndEpilogueVectorizer::InnerLoopAndEpilogueVectorizer (Loop * OrigLoop, PredicatedScalarEvolution & PSE, LoopInfo * LI, DominatorTree * DT, const TargetLibraryInfo * TLI, const TargetTransformInfo * TTI, AssumptionCache * AC, OptimizationRemarkEmitter * ORE, EpilogueLoopVectorizationInfo & EPI, LoopVectorizationCostModel * CM, BlockFrequencyInfo * BFI, ProfileSummaryInfo * PSI, GeneratedRTChecks & Checks, VPlan & Plan) inline
Definition at line 668 of file LoopVectorize.cpp.
References llvm::InnerLoopVectorizer::AC, llvm::InnerLoopVectorizer::BFI, llvm::InnerLoopVectorizer::DT, EPI, llvm::InnerLoopVectorizer::InnerLoopVectorizer(), llvm::InnerLoopVectorizer::LI, llvm::InnerLoopVectorizer::ORE, llvm::InnerLoopVectorizer::OrigLoop, llvm::InnerLoopVectorizer::Plan, llvm::InnerLoopVectorizer::PSE, llvm::InnerLoopVectorizer::PSI, llvm::InnerLoopVectorizer::TLI, and llvm::InnerLoopVectorizer::TTI.
Referenced by llvm::EpilogueVectorizerEpilogueLoop::EpilogueVectorizerEpilogueLoop(), and llvm::EpilogueVectorizerMainLoop::EpilogueVectorizerMainLoop().
Member Function Documentation
createEpilogueVectorizedLoopSkeleton()
virtual BasicBlock * llvm::InnerLoopAndEpilogueVectorizer::createEpilogueVectorizedLoopSkeleton () pure virtual
The interface for creating a vectorized skeleton using one of two different strategies, each corresponding to one execution of the vplan as described above.
Implemented in llvm::EpilogueVectorizerEpilogueLoop, and llvm::EpilogueVectorizerMainLoop.
Referenced by createVectorizedLoopSkeleton().
createVectorizedLoopSkeleton()
BasicBlock * llvm::InnerLoopAndEpilogueVectorizer::createVectorizedLoopSkeleton () inline final virtual
Create a new empty loop that will contain vectorized instructions later on, while the old loop will be used as the scalar remainder.
Control flow is generated around the vectorized (and scalar epilogue) loops consisting of various checks and bypasses. Return the pre-header block of the new loop. In the case of epilogue vectorization, this function is overriden to handle the more complex control flow around the loops.
Reimplemented from llvm::InnerLoopVectorizer.
Definition at line 682 of file LoopVectorize.cpp.
References createEpilogueVectorizedLoopSkeleton().
Member Data Documentation
EPI
EpilogueLoopVectorizationInfo& llvm::InnerLoopAndEpilogueVectorizer::EPI
Holds and updates state information required to vectorize the main loop and its epilogue in two separate passes.
This setup helps us avoid regenerating and recomputing runtime safety checks. It also helps us to shorten the iteration-count-check path length for the cases where the iteration count of the loop is so small that the main vector loop is completely skipped.
Definition at line 697 of file LoopVectorize.cpp.
Referenced by llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerMainLoop::createEpilogueVectorizedLoopSkeleton(), llvm::EpilogueVectorizerMainLoop::emitIterationCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), llvm::EpilogueVectorizerEpilogueLoop::EpilogueVectorizerEpilogueLoop(), llvm::EpilogueVectorizerMainLoop::EpilogueVectorizerMainLoop(), InnerLoopAndEpilogueVectorizer(), llvm::EpilogueVectorizerEpilogueLoop::printDebugTracesAtStart(), and llvm::EpilogueVectorizerMainLoop::printDebugTracesAtStart().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorize.cpp