LLVM: llvm::StructuralHashPrinterPass Class Reference
llvm::StructuralHashPrinterPass Class Reference
Printer pass for StructuralHashes.
#include "llvm/Analysis/StructuralHash.h"
Public Member Functions
StructuralHashPrinterPass (raw_ostream &OS, StructuralHashOptions Options)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Public Member Functions inherited from llvm::PassInfoMixin< StructuralHashPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< StructuralHashPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for StructuralHashes.
Definition at line 23 of file StructuralHash.h.
Constructor & Destructor Documentation
StructuralHashPrinterPass()
llvm::StructuralHashPrinterPass::StructuralHashPrinterPass (raw_ostream & OS, StructuralHashOptions Options) inline explicit
Definition at line 29 of file StructuralHash.h.
Member Function Documentation
isRequired()
bool llvm::StructuralHashPrinterPass::isRequired () inline static
Definition at line 35 of file StructuralHash.h.
run()
PreservedAnalyses StructuralHashPrinterPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 21 of file StructuralHash.cpp.
References llvm::PreservedAnalyses::all(), llvm::CallTargetIgnored, llvm::Detailed, F, llvm::format(), I, llvm::isa(), MAM, llvm::None, llvm::StructuralHash(), and llvm::StructuralHashWithDifferences().
The documentation for this class was generated from the following files:
include/llvm/Analysis/StructuralHash.h
lib/Analysis/StructuralHash.cpp