LLVM: llvm::orc::ELFDebugObject Class Reference
llvm::orc::ELFDebugObject Class Reference
The current implementation of ELFDebugObject replicates the approach used in RuntimeDyld: It patches executable and data section headers in the given object buffer with load-addresses of their corresponding sections in target memory.
Public Member Functions
void reportSectionTargetMemoryRange (StringRef Name, SectionRange TargetMem) override
StringRef getBuffer () const
Public Member Functions inherited from llvm::orc::DebugObject
DebugObject (JITLinkMemoryManager &MemMgr, const JITLinkDylib *JD, ExecutionSession &ES)
bool hasFlags (DebugObjectFlags F) const
void setFlags (DebugObjectFlags F)
void clearFlags (DebugObjectFlags F)
void finalizeAsync (FinalizeContinuation OnFinalize)
virtual ~DebugObject ()
Static Public Member Functions
static Expected< std::unique_ptr< DebugObject > > Create (MemoryBufferRef Buffer, JITLinkContext &Ctx, ExecutionSession &ES)
Protected Member Functions
Expected< SimpleSegmentAlloc > finalizeWorkingMemory () override
template<typename ELFT>
Error recordSection (StringRef Name, std::unique_ptr< ELFDebugObjectSection< ELFT > > Section)
DebugObjectSection * getSection (StringRef Name)
Additional Inherited Members
Public Types inherited from llvm::orc::DebugObject
using FinalizeContinuation = std::function<void(Expected<ExecutorAddrRange>)>
Protected Types inherited from llvm::orc::DebugObject
using InFlightAlloc = JITLinkMemoryManager::InFlightAlloc
using FinalizedAlloc = JITLinkMemoryManager::FinalizedAlloc
Protected Attributes inherited from llvm::orc::DebugObject
JITLinkMemoryManager & MemMgr
const JITLinkDylib * JD = nullptr
ExecutionSession & ES
Detailed Description
The current implementation of ELFDebugObject replicates the approach used in RuntimeDyld: It patches executable and data section headers in the given object buffer with load-addresses of their corresponding sections in target memory.
Definition at line 186 of file DebugObjectManagerPlugin.cpp.
Member Function Documentation
Create()
Expected< std::unique_ptr< DebugObject > > llvm::orc::ELFDebugObject::Create (MemoryBufferRef Buffer, JITLinkContext & Ctx, ExecutionSession & ES) static
Definition at line 295 of file DebugObjectManagerPlugin.cpp.
References llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::ELFDATA2MSB, llvm::orc::DebugObject::ES, and llvm::object::getElfArchType().
Referenced by llvm::orc::createDebugObjectFromBuffer().
finalizeWorkingMemory()
Expected< SimpleSegmentAlloc > llvm::orc::ELFDebugObject::finalizeWorkingMemory () override protected virtual
Implements llvm::orc::DebugObject.
Definition at line 321 of file DebugObjectManagerPlugin.cpp.
References llvm::jitlink::SimpleSegmentAlloc::Create(), llvm::dbgs(), llvm::orc::DebugObject::ES, llvm::sys::Process::getPageSizeEstimate(), llvm::orc::DebugObject::JD, LLVM_DEBUG, llvm::orc::DebugObject::MemMgr, PageSize, and Size.
getBuffer()
StringRef llvm::orc::ELFDebugObject::getBuffer () const inline
Definition at line 194 of file DebugObjectManagerPlugin.cpp.
getSection()
DebugObjectSection * llvm::orc::ELFDebugObject::getSection (StringRef Name) protected
Definition at line 367 of file DebugObjectManagerPlugin.cpp.
References getSection().
Referenced by getSection().
recordSection()
template<typename ELFT> Error llvm::orc::ELFDebugObject::recordSection (StringRef Name, std::unique_ptr< ELFDebugObjectSection< ELFT > > Section) protected
Definition at line 355 of file DebugObjectManagerPlugin.cpp.
References llvm::dbgs(), LLVM_DEBUG, recordSection(), and llvm::Error::success().
Referenced by recordSection().
reportSectionTargetMemoryRange()
void llvm::orc::ELFDebugObject::reportSectionTargetMemoryRange (StringRef Name, SectionRange TargetMem) override virtual
Reimplemented from llvm::orc::DebugObject.
Definition at line 348 of file DebugObjectManagerPlugin.cpp.
References llvm::object::getSection(), and reportSectionTargetMemoryRange().
Referenced by reportSectionTargetMemoryRange().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/DebugObjectManagerPlugin.cpp