LLVM: llvm::objcopy::elf::IHexWriter Class Reference
llvm::objcopy::elf::IHexWriter Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
Error write () override
IHexWriter (Object &Obj, raw_ostream &Out, StringRef OutputFile)
Public Member Functions inherited from llvm::objcopy::elf::ASCIIHexWriter
ASCIIHexWriter (Object &Obj, raw_ostream &OS, StringRef OutputFile)
Error finalize () override
Public Member Functions inherited from llvm::objcopy::elf::Writer
virtual ~Writer ()
Writer (Object &O, raw_ostream &Out)
Additional Inherited Members
Protected Member Functions inherited from llvm::objcopy::elf::ASCIIHexWriter
Error checkSection (const SectionBase &S) const
Protected Attributes inherited from llvm::objcopy::elf::ASCIIHexWriter
StringRef OutputFileName
size_t TotalSize = 0
std::vector< const SectionBase * > Sections
Protected Attributes inherited from llvm::objcopy::elf::Writer
Object & Obj
std::unique_ptr< WritableMemoryBuffer > Buf
raw_ostream & Out
Detailed Description
Definition at line 394 of file ELFObject.h.
Constructor & Destructor Documentation
IHexWriter()
llvm::objcopy::elf::IHexWriter::IHexWriter (Object & Obj, raw_ostream & Out, StringRef OutputFile) inline
Definition at line 397 of file ELFObject.h.
References llvm::objcopy::elf::ASCIIHexWriter::ASCIIHexWriter(), llvm::objcopy::elf::Writer::Obj, and llvm::objcopy::elf::Writer::Out.
Member Function Documentation
write()
Error IHexWriter::write () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2853 of file ELFObject.cpp.
References assert(), llvm::objcopy::elf::Writer::Buf, llvm::Offset, llvm::objcopy::elf::Writer::Out, llvm::objcopy::elf::ASCIIHexWriter::Sections, llvm::Error::success(), llvm::objcopy::elf::ASCIIHexWriter::TotalSize, and llvm::objcopy::elf::Writer::Writer().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp