LLVM: llvm::LazyCallGraphDOTPrinterPass Class Reference
llvm::LazyCallGraphDOTPrinterPass Class Reference
A pass which prints the call graph as a DOT file to a raw_ostream.
#include "llvm/Analysis/LazyCallGraph.h"
Public Member Functions
LLVM_ABI LazyCallGraphDOTPrinterPass (raw_ostream &OS)
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< LazyCallGraphDOTPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< LazyCallGraphDOTPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A pass which prints the call graph as a DOT file to a raw_ostream.
This is primarily useful for visualization purposes.
Definition at line 1304 of file LazyCallGraph.h.
Constructor & Destructor Documentation
LazyCallGraphDOTPrinterPass()
LazyCallGraphDOTPrinterPass::LazyCallGraphDOTPrinterPass (raw_ostream & OS) explicit
Definition at line 2042 of file LazyCallGraph.cpp.
Member Function Documentation
isRequired()
bool llvm::LazyCallGraphDOTPrinterPass::isRequired () inline static
Definition at line 1313 of file LazyCallGraph.h.
run()
PreservedAnalyses LazyCallGraphDOTPrinterPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 2060 of file LazyCallGraph.cpp.
References llvm::PreservedAnalyses::all(), llvm::DOT::EscapeString(), F, G, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and printNodeDOT().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyCallGraph.h
lib/Analysis/LazyCallGraph.cpp