LLVM: llvm::MachineModuleInfoMachO Class Reference
llvm::MachineModuleInfoMachO Class Reference
MachineModuleInfoMachO - This is a MachineModuleInfoImpl implementation for MachO targets.
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
Public Member Functions
MachineModuleInfoMachO (const MachineModuleInfo &)
StubValueTy & getGVStubEntry (MCSymbol *Sym)
StubValueTy & getThreadLocalGVStubEntry (MCSymbol *Sym)
const MCExpr *& getAuthPtrStubEntry (MCSymbol *Sym)
SymbolListTy GetGVStubList ()
Accessor methods to return the set of stubs in sorted order.
SymbolListTy GetThreadLocalGVStubList ()
ExprStubListTy getAuthGVStubList ()
Public Member Functions inherited from llvm::MachineModuleInfoImpl
virtual ~MachineModuleInfoImpl ()
Additional Inherited Members
Public Types inherited from llvm::MachineModuleInfoImpl
using StubValueTy = PointerIntPair<MCSymbol *, 1, bool>
using SymbolListTy = std::vector<std::pair<MCSymbol *, StubValueTy>>
using ExprStubListTy = std::vector<std::pair<MCSymbol *, const MCExpr *>>
A variant of SymbolListTy where the stub is a generalized MCExpr.
Static Protected Member Functions inherited from llvm::MachineModuleInfoImpl
static SymbolListTy getSortedStubs (DenseMap< MCSymbol *, StubValueTy > &)
Return the entries from a DenseMap in a deterministic sorted orer.
static ExprStubListTy getSortedExprStubs (DenseMap< MCSymbol *, const MCExpr * > &)
Return the entries from a DenseMap in a deterministic sorted orer.
Detailed Description
MachineModuleInfoMachO - This is a MachineModuleInfoImpl implementation for MachO targets.
Definition at line 28 of file MachineModuleInfoImpls.h.
Constructor & Destructor Documentation
MachineModuleInfoMachO()
llvm::MachineModuleInfoMachO::MachineModuleInfoMachO (const MachineModuleInfo &) inline
Definition at line 47 of file MachineModuleInfoImpls.h.
Member Function Documentation
getAuthGVStubList()
ExprStubListTy llvm::MachineModuleInfoMachO::getAuthGVStubList () inline
Definition at line 70 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedExprStubs().
getAuthPtrStubEntry()
const MCExpr *& llvm::MachineModuleInfoMachO::getAuthPtrStubEntry (MCSymbol * Sym) inline
Definition at line 59 of file MachineModuleInfoImpls.h.
References assert().
getGVStubEntry()
StubValueTy & llvm::MachineModuleInfoMachO::getGVStubEntry (MCSymbol * Sym) inline
Definition at line 49 of file MachineModuleInfoImpls.h.
References assert().
Referenced by llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
GetGVStubList()
SymbolListTy llvm::MachineModuleInfoMachO::GetGVStubList () inline
Accessor methods to return the set of stubs in sorted order.
Definition at line 65 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedStubs().
Referenced by llvm::ARMAsmPrinter::emitEndOfAsmFile(), and emitNonLazyStubs().
getThreadLocalGVStubEntry()
StubValueTy & llvm::MachineModuleInfoMachO::getThreadLocalGVStubEntry (MCSymbol * Sym) inline
Definition at line 54 of file MachineModuleInfoImpls.h.
References assert().
GetThreadLocalGVStubList()
SymbolListTy llvm::MachineModuleInfoMachO::GetThreadLocalGVStubList () inline
Definition at line 66 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedStubs().
Referenced by llvm::ARMAsmPrinter::emitEndOfAsmFile().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfoImpls.h
lib/CodeGen/MachineModuleInfoImpls.cpp