LLVM: llvm::MipsAsmBackend Class Reference
llvm::MipsAsmBackend Class Reference
#include "Target/Mips/MCTargetDesc/MipsAsmBackend.h"
Public Member Functions
MipsAsmBackend (const Target &T, const MCRegisterInfo &MRI, const Triple &TT, StringRef CPU, bool N32)
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
void applyFixup (const MCFragment &, const MCFixup &, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved) override
ApplyFixup - Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
std::optional< MCFixupKind > getFixupKind (StringRef Name) const override
Map a relocation name used in .reloc to a fixup kind.
MCFixupKindInfo getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
WriteNopData - Write an (optimal) nop sequence of Count bytes to the given output.
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
void setAssembler (MCAssembler *A)
MCContext & getContext () const
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool finishLayout (const MCAssembler &Asm) const
virtual uint64_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual std::optional< bool > evaluateFixup (const MCFragment &, MCFixup &, MCValue &, uint64_t &)
void maybeAddReloc (const MCFragment &, const MCFixup &, const MCValue &, uint64_t &Value, bool IsResolved)
virtual bool mayNeedRelaxation (unsigned Opcode, ArrayRef< MCOperand > Operands, const MCSubtargetInfo &STI) const
Check whether the given instruction (encoded as Opcode+Operands) may need relaxation.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &, const MCValue &, uint64_t, bool Resolved) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
virtual bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value) const
Simple predicate for targets where !Resolved implies requiring relaxation.
virtual void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const
Relax the instruction in the given fragment to the next wider instruction.
virtual bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, bool &WasRelaxed) const
virtual std::pair< bool, bool > relaxLEB128 (MCLEBFragment &LF, int64_t &Value) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::MCAsmBackend
static const MCSubtargetInfo * getSubtargetInfo (const MCFragment &F)
Public Attributes inherited from llvm::MCAsmBackend
const llvm::endianness Endian
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (llvm::endianness Endian)
Protected Attributes inherited from llvm::MCAsmBackend
MCAssembler * Asm = nullptr
Detailed Description
Definition at line 28 of file MipsAsmBackend.h.
Constructor & Destructor Documentation
MipsAsmBackend()
llvm::MipsAsmBackend::MipsAsmBackend (const Target & T, const MCRegisterInfo & MRI, const Triple & TT, StringRef CPU, bool N32) inline
Definition at line 33 of file MipsAsmBackend.h.
References llvm::big, llvm::little, llvm::MCAsmBackend::MCAsmBackend(), MRI, and T.
Member Function Documentation
applyFixup()
void MipsAsmBackend::applyFixup (const MCFragment & F, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved) override virtual
ApplyFixup - Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Implements llvm::MCAsmBackend.
Definition at line 285 of file MipsAsmBackend.cpp.
References adjustFixupValue(), calculateMMLEIndex(), llvm::Data, llvm::MCAsmBackend::Endian, F, Fixup, llvm::Mips::fixup_MICROMIPS_PC10_S1, llvm::Mips::fixup_Mips_16, llvm::Mips::fixup_Mips_64, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::MCAsmBackend::getContext(), getFixupKindInfo(), llvm::little, llvm::MCAsmBackend::maybeAddReloc(), needsMMLEByteOrder(), llvm::Offset, shouldForceRelocation(), and llvm::MCFixupKindInfo::TargetSize.
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > MipsAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 220 of file MipsAsmBackend.cpp.
References llvm::createMipsELFObjectWriter().
getFixupKind()
std::optional< MCFixupKind > MipsAsmBackend::getFixupKind (StringRef Name) const override virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 347 of file MipsAsmBackend.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::FirstLiteralRelocationKind, llvm::Mips::fixup_MICROMIPS_CALL16, llvm::Mips::fixup_MICROMIPS_GOT16, llvm::Mips::fixup_MICROMIPS_GOT_DISP, llvm::Mips::fixup_MICROMIPS_GOT_OFST, llvm::Mips::fixup_MICROMIPS_GOT_PAGE, llvm::Mips::fixup_MICROMIPS_GOTTPREL, llvm::Mips::fixup_MICROMIPS_JALR, llvm::Mips::fixup_MICROMIPS_TLS_DTPREL_HI16, llvm::Mips::fixup_MICROMIPS_TLS_DTPREL_LO16, llvm::Mips::fixup_MICROMIPS_TLS_GD, llvm::Mips::fixup_MICROMIPS_TLS_LDM, llvm::Mips::fixup_MICROMIPS_TLS_TPREL_HI16, llvm::Mips::fixup_MICROMIPS_TLS_TPREL_LO16, llvm::Mips::fixup_Mips_CALL16, llvm::Mips::fixup_Mips_CALL_HI16, llvm::Mips::fixup_Mips_CALL_LO16, llvm::Mips::fixup_Mips_DTPREL_HI, llvm::Mips::fixup_Mips_DTPREL_LO, llvm::Mips::fixup_Mips_GOT, llvm::Mips::fixup_Mips_GOT_DISP, llvm::Mips::fixup_Mips_GOT_HI16, llvm::Mips::fixup_Mips_GOT_LO16, llvm::Mips::fixup_Mips_GOT_OFST, llvm::Mips::fixup_Mips_GOT_PAGE, llvm::Mips::fixup_Mips_GOTTPREL, llvm::Mips::fixup_Mips_JALR, llvm::Mips::fixup_Mips_TLSGD, llvm::Mips::fixup_Mips_TLSLDM, llvm::Mips::fixup_Mips_TPREL_HI, llvm::Mips::fixup_Mips_TPREL_LO, llvm::FK_Data_4, llvm::FK_NONE, and llvm::MCAsmBackend::getFixupKind().
getFixupKindInfo()
MCFixupKindInfo MipsAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 395 of file MipsAsmBackend.cpp.
References assert(), llvm::MCAsmBackend::Endian, llvm::FirstTargetFixupKind, llvm::MCAsmBackend::getFixupKindInfo(), llvm::mc::isRelocation(), llvm::little, and llvm::Mips::NumTargetFixupKinds.
Referenced by applyFixup().
writeNopData()
bool MipsAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
WriteNopData - Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 586 of file MipsAsmBackend.cpp.
References llvm::Count, and llvm::raw_ostream::write_zeros().
The documentation for this class was generated from the following files:
lib/Target/Mips/MCTargetDesc/MipsAsmBackend.h
lib/Target/Mips/MCTargetDesc/MipsAsmBackend.cpp