LLVM: llvm::AttributeImpl Class Reference
llvm::AttributeImpl Class Reference
This class represents a single, uniqued attribute.
#include "IR/AttributeImpl.h"
Public Member Functions
AttributeImpl (const AttributeImpl &)=delete
AttributeImpl & operator= (const AttributeImpl &)=delete
bool isEnumAttribute () const
bool isIntAttribute () const
bool isStringAttribute () const
bool isTypeAttribute () const
bool isConstantRangeAttribute () const
bool isConstantRangeListAttribute () const
bool hasAttribute (Attribute::AttrKind A) const
bool hasAttribute (StringRef Kind) const
Attribute::AttrKind getKindAsEnum () const
uint64_t getValueAsInt () const
bool getValueAsBool () const
StringRef getKindAsString () const
StringRef getValueAsString () const
Type * getValueAsType () const
const ConstantRange & getValueAsConstantRange () const
ArrayRef< ConstantRange > getValueAsConstantRangeList () const
int cmp (const AttributeImpl &AI, bool KindOnly) const
Used to sort attributes.
bool operator< (const AttributeImpl &AI) const
Used when sorting the attributes.
void Profile (FoldingSetNodeID &ID) const
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind)
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, uint64_t Val)
static void Profile (FoldingSetNodeID &ID, StringRef Kind, StringRef Values)
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, Type *Ty)
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, const ConstantRange &CR)
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, ArrayRef< ConstantRange > Val)
Protected Types
enum AttrEntryKind {
EnumAttrEntry , IntAttrEntry , StringAttrEntry , TypeAttrEntry ,
ConstantRangeAttrEntry , ConstantRangeListAttrEntry
}
Protected Member Functions
AttributeImpl (AttrEntryKind KindID)
Detailed Description
This class represents a single, uniqued attribute.
That attribute could be a single enum, a tuple, or a string.
Definition at line 42 of file AttributeImpl.h.
Member Enumeration Documentation
AttrEntryKind
enum llvm::AttributeImpl::AttrEntryKind protected
Enumerator
EnumAttrEntry
IntAttrEntry
StringAttrEntry
TypeAttrEntry
ConstantRangeAttrEntry
ConstantRangeListAttrEntry
Definition at line 46 of file AttributeImpl.h.
Constructor & Destructor Documentation
AttributeImpl() [1/2]
llvm::AttributeImpl::AttributeImpl (AttrEntryKind KindID) inline protected
Definition at line 55 of file AttributeImpl.h.
Referenced by AttributeImpl(), cmp(), llvm::EnumAttributeImpl::EnumAttributeImpl(), llvm::EnumAttributeImpl::EnumAttributeImpl(), operator<(), operator=(), and llvm::StringAttributeImpl::StringAttributeImpl().
AttributeImpl() [2/2]
llvm::AttributeImpl::AttributeImpl (const AttributeImpl &) delete
References AttributeImpl().
Member Function Documentation
cmp()
int AttributeImpl::cmp (const AttributeImpl & AI, bool KindOnly) const
Used to sort attributes.
KindOnly controls if the sort includes the attributes' values or just the kind.
Definition at line 878 of file Attributes.cpp.
References assert(), AttributeImpl(), llvm::StringRef::compare(), getKindAsEnum(), getKindAsString(), getValueAsInt(), getValueAsString(), isConstantRangeAttribute(), isConstantRangeListAttribute(), isEnumAttribute(), isIntAttribute(), isStringAttribute(), and isTypeAttribute().
Referenced by operator<().
getKindAsEnum()
Attribute::AttrKind AttributeImpl::getKindAsEnum () const
Definition at line 835 of file Attributes.cpp.
References assert(), isConstantRangeAttribute(), isConstantRangeListAttribute(), isEnumAttribute(), isIntAttribute(), and isTypeAttribute().
Referenced by cmp(), hasAttribute(), and Profile().
getKindAsString()
StringRef AttributeImpl::getKindAsString () const
Definition at line 851 of file Attributes.cpp.
References assert(), and isStringAttribute().
Referenced by cmp(), hasAttribute(), and Profile().
getValueAsBool()
bool AttributeImpl::getValueAsBool () const
Definition at line 846 of file Attributes.cpp.
References assert(), and getValueAsString().
getValueAsConstantRange()
const ConstantRange & AttributeImpl::getValueAsConstantRange () const
Definition at line 866 of file Attributes.cpp.
References assert(), and isConstantRangeAttribute().
Referenced by Profile().
getValueAsConstantRangeList()
ArrayRef< ConstantRange > AttributeImpl::getValueAsConstantRangeList () const
Definition at line 872 of file Attributes.cpp.
References assert(), and isConstantRangeListAttribute().
Referenced by Profile().
getValueAsInt()
uint64_t AttributeImpl::getValueAsInt () const
Definition at line 841 of file Attributes.cpp.
References assert(), and isIntAttribute().
Referenced by cmp(), and Profile().
getValueAsString()
StringRef AttributeImpl::getValueAsString () const
Definition at line 856 of file Attributes.cpp.
References assert(), and isStringAttribute().
Referenced by cmp(), getValueAsBool(), and Profile().
getValueAsType()
Type * AttributeImpl::getValueAsType () const
Definition at line 861 of file Attributes.cpp.
References assert(), and isTypeAttribute().
Referenced by Profile().
hasAttribute() [1/2]
bool AttributeImpl::hasAttribute (Attribute::AttrKind A) const
Definition at line 825 of file Attributes.cpp.
References A(), getKindAsEnum(), and isStringAttribute().
hasAttribute() [2/2]
bool AttributeImpl::hasAttribute (StringRef Kind) const
Definition at line 830 of file Attributes.cpp.
References getKindAsString(), and isStringAttribute().
isConstantRangeAttribute()
bool llvm::AttributeImpl::isConstantRangeAttribute () const inline
Definition at line 66 of file AttributeImpl.h.
References ConstantRangeAttrEntry.
Referenced by cmp(), getKindAsEnum(), getValueAsConstantRange(), and Profile().
isConstantRangeListAttribute()
bool llvm::AttributeImpl::isConstantRangeListAttribute () const inline
Definition at line 69 of file AttributeImpl.h.
References ConstantRangeListAttrEntry.
Referenced by cmp(), getKindAsEnum(), and getValueAsConstantRangeList().
isEnumAttribute()
bool llvm::AttributeImpl::isEnumAttribute () const inline
Definition at line 62 of file AttributeImpl.h.
References EnumAttrEntry.
Referenced by cmp(), getKindAsEnum(), and Profile().
isIntAttribute()
bool llvm::AttributeImpl::isIntAttribute () const inline
Definition at line 63 of file AttributeImpl.h.
References IntAttrEntry.
Referenced by cmp(), getKindAsEnum(), getValueAsInt(), and Profile().
isStringAttribute()
bool llvm::AttributeImpl::isStringAttribute () const inline
Definition at line 64 of file AttributeImpl.h.
References StringAttrEntry.
Referenced by cmp(), getKindAsString(), getValueAsString(), hasAttribute(), hasAttribute(), and Profile().
isTypeAttribute()
bool llvm::AttributeImpl::isTypeAttribute () const inline
Definition at line 65 of file AttributeImpl.h.
References TypeAttrEntry.
Referenced by cmp(), getKindAsEnum(), getValueAsType(), and Profile().
operator<()
bool AttributeImpl::operator< (const AttributeImpl & AI) const
Used when sorting the attributes.
Definition at line 913 of file Attributes.cpp.
References AttributeImpl(), and cmp().
operator=()
AttributeImpl & llvm::AttributeImpl::operator= (const AttributeImpl &) delete
References AttributeImpl().
Profile() [1/7]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID) const inline
Definition at line 95 of file AttributeImpl.h.
References getKindAsEnum(), getKindAsString(), getValueAsConstantRange(), getValueAsConstantRangeList(), getValueAsInt(), getValueAsString(), getValueAsType(), isConstantRangeAttribute(), isEnumAttribute(), isIntAttribute(), isStringAttribute(), isTypeAttribute(), and Profile.
Profile() [2/7]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind) inline static
Definition at line 110 of file AttributeImpl.h.
References assert(), and llvm::Attribute::isEnumAttrKind().
Profile() [3/7]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind, ArrayRef< ConstantRange > Val) inline static
Definition at line 140 of file AttributeImpl.h.
References llvm::ArrayRef< T >::size().
Profile() [4/7]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind, const ConstantRange & CR) inline static
Definition at line 133 of file AttributeImpl.h.
References llvm::ConstantRange::getLower(), llvm::ConstantRange::getUpper(), and llvm::APInt::Profile().
Profile() [5/7]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind, Type * Ty) inline static
Definition at line 127 of file AttributeImpl.h.
Profile() [6/7]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind, uint64_t Val) inline static
Definition at line 115 of file AttributeImpl.h.
References assert(), and llvm::Attribute::isIntAttrKind().
Profile() [7/7]
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, StringRef Kind, StringRef Values) inline static
Definition at line 122 of file AttributeImpl.h.
References llvm::StringRef::empty().
The documentation for this class was generated from the following files:
lib/IR/AttributeImpl.h
lib/IR/Attributes.cpp