LLVM: llvm::VPExpressionRecipe Class Reference
llvm::VPExpressionRecipe Class Reference
A recipe to combine multiple recipes into a single 'expression' recipe, which should be considered a single entity for cost-modeling and transforms.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPExpressionRecipe (VPWidenCastRecipe *Ext, VPReductionRecipe *Red)
VPExpressionRecipe (VPWidenRecipe *Mul, VPReductionRecipe *Red)
VPExpressionRecipe (VPWidenCastRecipe *Ext0, VPWidenCastRecipe *Ext1, VPWidenRecipe *Mul, VPReductionRecipe *Red)
~VPExpressionRecipe () override
VPExpressionRecipe * clone () override
Clone the current recipe.
VPValue * getOperandOfResultType () const
Return the VPValue to use to infer the result type of the recipe.
void decompose ()
Insert the recipes of the expression back into the VPlan, directly before the current recipe.
void execute (VPTransformState &State) override
Method for generating code, must not be called as this recipe is abstract.
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Compute the cost of this recipe either using a recipe's specialized implementation or using the legacy cost model and the underlying instructions.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
bool mayReadOrWriteMemory () const
Returns true if this expression contains recipes that may read from or write to memory.
bool mayHaveSideEffects () const
Returns true if this expression contains recipes that may have side effects.
Public Member Functions inherited from llvm::VPSingleDefRecipe
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, Value *UV, DebugLoc DL={})
Instruction * getUnderlyingInstr ()
Returns the underlying instruction.
const Instruction * getUnderlyingInstr () const
LLVM_DUMP_METHOD void dump () const
Print this VPSingleDefRecipe to dbgs() (for debugging).
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
bool isScalarCast () const
Return true if the recipe is a scalar cast.
void setDebugLoc (DebugLoc NewDL)
Set the recipe's debug location to NewDL.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstLaneUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first lane of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser () const
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isLiveIn () const
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Value * getLiveInIRValue () const
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
bool isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop.
void setUnderlyingValue (Value *Val)
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC , VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Static Public Member Functions inherited from llvm::VPSingleDefRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
A recipe to combine multiple recipes into a single 'expression' recipe, which should be considered a single entity for cost-modeling and transforms.
The recipe needs to be 'decomposed', i.e. replaced by its individual expression recipes, before execute. The individual expression recipes are completely disconnected from the def-use graph of other recipes not part of the expression. Def-use edges between pairs of expression recipes remain intact, whereas every edge between an expression recipe and a recipe outside the expression is elevated to connect the non-expression recipe with the VPExpressionRecipe itself.
Definition at line 2777 of file VPlan.h.
Constructor & Destructor Documentation
VPExpressionRecipe() [1/3]
llvm::VPExpressionRecipe::VPExpressionRecipe (VPWidenCastRecipe * Ext, VPReductionRecipe * Red) inline
Definition at line 2813 of file VPlan.h.
VPExpressionRecipe() [2/3]
llvm::VPExpressionRecipe::VPExpressionRecipe (VPWidenRecipe * Mul, VPReductionRecipe * Red) inline
Definition at line 2815 of file VPlan.h.
References llvm::Mul.
VPExpressionRecipe() [3/3]
llvm::VPExpressionRecipe::VPExpressionRecipe (VPWidenCastRecipe * Ext0, VPWidenCastRecipe * Ext1, VPWidenRecipe * Mul, VPReductionRecipe * Red) inline
Definition at line 2817 of file VPlan.h.
References llvm::Mul.
~VPExpressionRecipe()
llvm::VPExpressionRecipe::~VPExpressionRecipe () inline override
Definition at line 2822 of file VPlan.h.
References llvm::reverse(), and T.
Member Function Documentation
clone()
VPExpressionRecipe * llvm::VPExpressionRecipe::clone () inline override virtual
Clone the current recipe.
Implements llvm::VPSingleDefRecipe.
Definition at line 2831 of file VPlan.h.
References assert(), clone(), llvm::enumerate(), llvm::VPUser::operands(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::VPValue::VPExpressionRecipe, and llvm::zip().
Referenced by clone().
computeCost()
InstructionCost VPExpressionRecipe::computeCost (ElementCount VF, VPCostContext & Ctx) const override virtual
Compute the cost of this recipe either using a recipe's specialized implementation or using the legacy cost model and the underlying instructions.
Reimplemented from llvm::VPRecipeBase.
Definition at line 2665 of file VPlanRecipes.cpp.
References assert(), llvm::cast(), llvm::RecurrenceDescriptor::getOpcode(), llvm::VPUser::getOperand(), llvm::Type::isIntegerTy(), llvm_unreachable, and llvm::toVectorTy().
decompose()
void VPExpressionRecipe::decompose ()
Insert the recipes of the expression back into the VPlan, directly before the current recipe.
Leaves the expression recipe empty, which must be removed before codegen.
Definition at line 2654 of file VPlanRecipes.cpp.
References llvm::enumerate(), llvm::VPUser::operands(), and llvm::VPValue::replaceAllUsesWith().
execute()
void llvm::VPExpressionRecipe::execute (VPTransformState & State) inline override virtual
Method for generating code, must not be called as this recipe is abstract.
Implements llvm::VPRecipeBase.
Definition at line 2862 of file VPlan.h.
References llvm_unreachable.
getOperandOfResultType()
VPValue * llvm::VPExpressionRecipe::getOperandOfResultType () const inline
Return the VPValue to use to infer the result type of the recipe.
Definition at line 2849 of file VPlan.h.
References llvm::cast(), llvm::VPUser::getNumOperands(), llvm::VPUser::getOperand(), and OpIdx.
mayHaveSideEffects()
bool VPExpressionRecipe::mayHaveSideEffects () const
Returns true if this expression contains recipes that may have side effects.
Definition at line 2700 of file VPlanRecipes.cpp.
References assert(), llvm::none_of(), and llvm::VPSingleDefRecipe::VPSingleDefRecipe().
mayReadOrWriteMemory()
bool VPExpressionRecipe::mayReadOrWriteMemory () const
Returns true if this expression contains recipes that may read from or write to memory.
Definition at line 2694 of file VPlanRecipes.cpp.
References llvm::any_of(), and llvm::VPSingleDefRecipe::VPSingleDefRecipe().
print()
void VPExpressionRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 2710 of file VPlanRecipes.cpp.
References llvm::cast(), llvm::VPUser::getNumOperands(), llvm::RecurrenceDescriptor::getOpcode(), llvm::RecurrenceDescriptor::getOpcode(), llvm::Instruction::getOpcodeName(), llvm::VPUser::getOperand(), llvm::Mul, and llvm::VPValue::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp