LLVM: llvm::CodeViewContext Class Reference
llvm::CodeViewContext Class Reference
Holds state from .cv_file and .cv_loc directives for later emission.
#include "llvm/MC/MCCodeView.h"
Public Member Functions
CodeViewContext (MCContext *MCCtx)
CodeViewContext & operator= (const CodeViewContext &other)=delete
CodeViewContext (const CodeViewContext &other)=delete
void finish ()
bool isValidFileNumber (unsigned FileNumber) const
This is a valid number for use with .cv_loc if we've already seen a .cv_file for it.
bool addFile (MCStreamer &OS, unsigned FileNumber, StringRef Filename, ArrayRef< uint8_t > ChecksumBytes, uint8_t ChecksumKind)
bool recordFunctionId (unsigned FuncId)
Records the function id of a normal function.
bool recordInlinedCallSiteId (unsigned FuncId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol)
Records the function id of an inlined call site.
MCCVFunctionInfo * getCVFunctionInfo (unsigned FuncId)
Retreive the function info if this is a valid function id, or nullptr.
void recordCVLoc (MCContext &Ctx, const MCSymbol *Label, unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt)
Saves the information from the currently parsed .cv_loc directive and sets CVLocSeen.
void addLineEntry (const MCCVLoc &LineEntry)
Add a line entry.
std::vector< MCCVLoc > getFunctionLineEntries (unsigned FuncId)
std::pair< size_t, size_t > getLineExtent (unsigned FuncId)
std::pair< size_t, size_t > getLineExtentIncludingInlinees (unsigned FuncId)
ArrayRef< MCCVLoc > getLinesForExtent (size_t L, size_t R)
void emitLineTableForFunction (MCObjectStreamer &OS, unsigned FuncId, const MCSymbol *FuncBegin, const MCSymbol *FuncEnd)
Emits a line table substream.
void emitInlineLineTableForFunction (MCObjectStreamer &OS, unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym)
void encodeInlineLineTable (const MCAssembler &Asm, MCCVInlineLineTableFragment &F)
Encodes the binary annotations once we have a layout.
MCFragment * emitDefRange (MCObjectStreamer &OS, ArrayRef< std::pair< const MCSymbol *, const MCSymbol * > > Ranges, StringRef FixedSizePortion)
void encodeDefRange (const MCAssembler &Asm, MCCVDefRangeFragment &F)
void emitStringTable (MCObjectStreamer &OS)
Emits the string table substream.
void emitFileChecksums (MCObjectStreamer &OS)
Emits the file checksum substream.
void emitFileChecksumOffset (MCObjectStreamer &OS, unsigned FileNo)
Emits the offset into the checksum table of the given file number.
std::pair< StringRef, unsigned > addToStringTable (StringRef S)
Add something to the string table.
Detailed Description
Holds state from .cv_file and .cv_loc directives for later emission.
Definition at line 145 of file MCCodeView.h.
Constructor & Destructor Documentation
CodeViewContext() [1/2]
llvm::CodeViewContext::CodeViewContext (MCContext * MCCtx) inline
Definition at line 147 of file MCCodeView.h.
Referenced by CodeViewContext(), and operator=().
CodeViewContext() [2/2]
llvm::CodeViewContext::CodeViewContext (const CodeViewContext & other) delete
References CodeViewContext(), and F.
Member Function Documentation
addFile()
bool CodeViewContext::addFile (MCStreamer & OS, unsigned FileNumber, StringRef Filename, ArrayRef< uint8_t > ChecksumBytes, uint8_t ChecksumKind)
Definition at line 42 of file MCCodeView.cpp.
References addToStringTable(), assert(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::getContext(), and llvm::Offset.
Referenced by llvm::MCStreamer::emitCVFileDirective().
addLineEntry()
void CodeViewContext::addLineEntry (const MCCVLoc & LineEntry)
Add a line entry.
Definition at line 251 of file MCCodeView.cpp.
References llvm::MCCVLoc::getFunctionId(), I, and llvm::Offset.
Referenced by recordCVLoc().
addToStringTable()
std::pair< StringRef, unsigned > CodeViewContext::addToStringTable (StringRef S)
Add something to the string table.
Returns the final string as well as offset into the string table.
Definition at line 134 of file MCCodeView.cpp.
Referenced by addFile().
emitDefRange()
MCFragment * CodeViewContext::emitDefRange (MCObjectStreamer & OS, ArrayRef< std::pair< const MCSymbol *, const MCSymbol * > > Ranges, StringRef FixedSizePortion)
Definition at line 441 of file MCCodeView.cpp.
References F, llvm::MCObjectStreamer::insert(), and Saved.
Referenced by llvm::MCObjectStreamer::emitCVDefRangeDirective().
emitFileChecksumOffset()
void CodeViewContext::emitFileChecksumOffset (MCObjectStreamer & OS, unsigned FileNo)
Emits the offset into the checksum table of the given file number.
Definition at line 233 of file MCCodeView.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCStreamer::emitSymbolValue(), llvm::MCObjectStreamer::emitValueImpl(), and llvm::MCStreamer::getContext().
Referenced by llvm::MCObjectStreamer::emitCVFileChecksumOffsetDirective().
emitFileChecksums()
void CodeViewContext::emitFileChecksums (MCObjectStreamer & OS)
Emits the file checksum substream.
Definition at line 178 of file MCCodeView.cpp.
References llvm::alignTo(), llvm::MCConstantExpr::create(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::MCObjectStreamer::emitAssignment(), llvm::MCObjectStreamer::emitBytes(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCObjectStreamer::emitLabel(), llvm::MCObjectStreamer::emitValueToAlignment(), llvm::codeview::FileChecksums, llvm::MCStreamer::getContext(), and llvm::toStringRef().
Referenced by llvm::MCObjectStreamer::emitCVFileChecksumsDirective().
emitInlineLineTableForFunction()
void CodeViewContext::emitInlineLineTableForFunction (MCObjectStreamer & OS, unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol * FnStartSym, const MCSymbol * FnEndSym)
Definition at line 428 of file MCCodeView.cpp.
References F, and llvm::MCObjectStreamer::insert().
Referenced by llvm::MCObjectStreamer::emitCVInlineLinetableDirective().
emitLineTableForFunction()
void CodeViewContext::emitLineTableForFunction (MCObjectStreamer & OS, unsigned FuncId, const MCSymbol * FuncBegin, const MCSymbol * FuncEnd)
Emits a line table substream.
Definition at line 335 of file MCCodeView.cpp.
References llvm::MCStreamer::AddComment(), llvm::any_of(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitCOFFSecRel32(), llvm::MCStreamer::emitCOFFSectionIndex(), llvm::MCObjectStreamer::emitCVFileChecksumOffsetDirective(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCObjectStreamer::emitLabel(), llvm::MCCVLoc::getColumn(), llvm::MCStreamer::getContext(), getFunctionLineEntries(), I, llvm::codeview::LF_HaveColumns, llvm::codeview::Lines, and llvm::codeview::LineInfo::StatementFlag.
Referenced by llvm::MCObjectStreamer::emitCVLinetableDirective().
emitStringTable()
void CodeViewContext::emitStringTable (MCObjectStreamer & OS)
Emits the string table substream.
Definition at line 156 of file MCCodeView.cpp.
References llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitInt32(), llvm::MCObjectStreamer::emitLabel(), llvm::MCObjectStreamer::emitValueToAlignment(), llvm::MCStreamer::getContext(), llvm::MCObjectStreamer::insert(), and llvm::codeview::StringTable.
Referenced by llvm::MCObjectStreamer::emitCVStringTableDirective().
encodeDefRange()
void CodeViewContext::encodeDefRange (const MCAssembler & Asm, MCCVDefRangeFragment & F)
Definition at line 609 of file MCCodeView.cpp.
References assert(), computeLabelDiff(), llvm::MCConstantExpr::create(), llvm::MCFixup::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::FK_SecRel_2, llvm::FK_SecRel_4, llvm::MCCVDefRangeFragment::getFixedSizePortion(), llvm::MCCVDefRangeFragment::getRanges(), I, llvm::little, llvm::codeview::MaxDefRange, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Range, llvm::MCEncodedFragment::setContents(), llvm::MCEncodedFragment::setFixups(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::size(), and llvm::support::endian::Writer::write().
encodeInlineLineTable()
void CodeViewContext::encodeInlineLineTable (const MCAssembler & Asm, MCCVInlineLineTableFragment & F)
Encodes the binary annotations once we have a layout.
Definition at line 472 of file MCCodeView.cpp.
References assert(), llvm::codeview::ChangeCodeLength, llvm::codeview::ChangeCodeOffset, llvm::codeview::ChangeCodeOffsetAndLineOffset, llvm::codeview::ChangeFile, llvm::codeview::ChangeLineOffset, compressAnnotation(), computeLabelDiff(), llvm::ArrayRef< T >::empty(), encodeSignedNumber(), llvm::errs(), llvm::MCCVFunctionInfo::LineInfo::File, llvm::ArrayRef< T >::front(), getCVFunctionInfo(), llvm::MCCVInlineLineTableFragment::getFnEndSym(), llvm::MCCVInlineLineTableFragment::getFnStartSym(), getLineExtentIncludingInlinees(), getLinesForExtent(), llvm::MCSymbol::getSection(), llvm::MCConstantExpr::getValue(), I, llvm::MCCVFunctionInfo::InlinedAtMap, llvm::Length, llvm::MCCVFunctionInfo::LineInfo::Line, llvm_unreachable, llvm::codeview::MaxRecordLength, llvm::MCEncodedFragment::setContents(), llvm::MCCVLoc::setFileNum(), llvm::MCCVLoc::setLabel(), llvm::MCCVLoc::setLine(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
finish()
void CodeViewContext::finish ()
Definition at line 28 of file MCCodeView.cpp.
Referenced by llvm::MCWinCOFFStreamer::finishImpl().
getCVFunctionInfo()
MCCVFunctionInfo * CodeViewContext::getCVFunctionInfo (unsigned FuncId)
Retreive the function info if this is a valid function id, or nullptr.
Definition at line 74 of file MCCodeView.cpp.
Referenced by llvm::MCStreamer::checkCVLocSection(), encodeInlineLineTable(), getFunctionLineEntries(), getLineExtentIncludingInlinees(), and recordInlinedCallSiteId().
getFunctionLineEntries()
std::vector< MCCVLoc > CodeViewContext::getFunctionLineEntries (unsigned FuncId)
Definition at line 261 of file MCCodeView.cpp.
References getCVFunctionInfo(), getLineExtentIncludingInlinees(), I, and llvm::MCCVFunctionInfo::InlinedAtMap.
Referenced by emitLineTableForFunction().
getLineExtent()
std::pair< size_t, size_t > CodeViewContext::getLineExtent (unsigned FuncId)
Definition at line 299 of file MCCodeView.cpp.
References I.
Referenced by getLineExtentIncludingInlinees().
getLineExtentIncludingInlinees()
std::pair< size_t, size_t > CodeViewContext::getLineExtentIncludingInlinees (unsigned FuncId)
Definition at line 308 of file MCCodeView.cpp.
References getCVFunctionInfo(), getLineExtent(), and llvm::MCCVFunctionInfo::InlinedAtMap.
Referenced by encodeInlineLineTable(), and getFunctionLineEntries().
getLinesForExtent()
ArrayRef< MCCVLoc > CodeViewContext::getLinesForExtent (size_t L, size_t R)
Definition at line 327 of file MCCodeView.cpp.
References llvm::ArrayRef().
Referenced by encodeInlineLineTable().
isValidFileNumber()
bool CodeViewContext::isValidFileNumber (unsigned FileNumber) const
This is a valid number for use with .cv_loc if we've already seen a .cv_file for it.
Definition at line 35 of file MCCodeView.cpp.
operator=()
CodeViewContext & llvm::CodeViewContext::operator= (const CodeViewContext & other) delete
References CodeViewContext().
recordCVLoc()
void CodeViewContext::recordCVLoc (MCContext & Ctx, const MCSymbol * Label, unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt)
Saves the information from the currently parsed .cv_loc directive and sets CVLocSeen.
When the next instruction is assembled an entry in the line number table with this information and the address of the instruction will be created.
Definition at line 126 of file MCCodeView.cpp.
References addLineEntry().
Referenced by llvm::MCObjectStreamer::emitCVLocDirective().
recordFunctionId()
bool CodeViewContext::recordFunctionId (unsigned FuncId)
Records the function id of a normal function.
Returns false if the function id has already been used, and true otherwise.
Definition at line 82 of file MCCodeView.cpp.
References llvm::MCCVFunctionInfo::FunctionSentinel.
Referenced by llvm::MCStreamer::emitCVFuncIdDirective().
recordInlinedCallSiteId()
bool CodeViewContext::recordInlinedCallSiteId (unsigned FuncId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol)
Records the function id of an inlined call site.
Records the "inlined at" location info of the call site, including what function or inlined call site it was inlined into. Returns false if the function id has already been used, and true otherwise.
Definition at line 95 of file MCCodeView.cpp.
References llvm::MCCVFunctionInfo::LineInfo::Col, llvm::MCCVFunctionInfo::LineInfo::File, getCVFunctionInfo(), llvm::MCCVFunctionInfo::LineInfo::Line, and llvm::MCCVFunctionInfo::ParentFuncIdPlusOne.
Referenced by llvm::MCStreamer::emitCVInlineSiteIdDirective().
The documentation for this class was generated from the following files:
include/llvm/MC/MCCodeView.h
lib/MC/MCCodeView.cpp