LLVM: llvm::CrashRecoveryContextDestructorCleanup< T > Class Template Reference
llvm::CrashRecoveryContextDestructorCleanup< T > Class Template Reference
Cleanup handler that reclaims resource by calling destructor on it.
#include "llvm/Support/CrashRecoveryContext.h"
Public Member Functions
CrashRecoveryContextDestructorCleanup (CrashRecoveryContext *context, T *resource)
void recoverResources () override
Public Member Functions inherited from llvm::CrashRecoveryContextCleanup
virtual ~CrashRecoveryContextCleanup ()
CrashRecoveryContext * getContext () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >
static CrashRecoveryContextDestructorCleanup< T > * create (T *x)
Creates cleanup handler.
Public Attributes inherited from llvm::CrashRecoveryContextCleanup
bool cleanupFired = false
Protected Member Functions inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >
CrashRecoveryContextCleanupBase (CrashRecoveryContext *context, T *resource)
Protected Member Functions inherited from llvm::CrashRecoveryContextCleanup
CrashRecoveryContextCleanup (CrashRecoveryContext *context)
Protected Attributes inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >
T * resource
Protected Attributes inherited from llvm::CrashRecoveryContextCleanup
CrashRecoveryContext * context = nullptr
Detailed Description
template<typename T>
class llvm::CrashRecoveryContextDestructorCleanup< T >
Cleanup handler that reclaims resource by calling destructor on it.
Definition at line 187 of file CrashRecoveryContext.h.
Constructor & Destructor Documentation
CrashRecoveryContextDestructorCleanup()
template<typename T> llvm::CrashRecoveryContextDestructorCleanup< T >::CrashRecoveryContextDestructorCleanup (CrashRecoveryContext * context, T * resource) inline
Definition at line 190 of file CrashRecoveryContext.h.
References llvm::CrashRecoveryContextCleanup::context, llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >::CrashRecoveryContextCleanupBase(), CrashRecoveryContextDestructorCleanup(), llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >::resource, and T.
Referenced by CrashRecoveryContextDestructorCleanup().
Member Function Documentation
recoverResources()
template<typename T> void llvm::CrashRecoveryContextDestructorCleanup< T >::recoverResources () inline override virtual
Implements llvm::CrashRecoveryContextCleanup.
Definition at line 195 of file CrashRecoveryContext.h.
References llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >::resource.
The documentation for this class was generated from the following file:
include/llvm/Support/CrashRecoveryContext.h