LLVM: llvm::DIFile Class Reference
llvm::DIFile Class Reference
File.
#include "llvm/IR/DebugInfoMetadata.h"
Classes
struct ChecksumInfo
A single checksum, represented by a Kind and a Value (a string).
Public Types
enum ChecksumKind { CSK_MD5 = 1 , CSK_SHA1 = 2 , CSK_SHA256 = 3 , CSK_Last = CSK_SHA256 }
Which algorithm (e.g.
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
DEFINE_MDNODE_GET (DIFile,(StringRef Filename, StringRef Directory, std::optional< ChecksumInfo< StringRef > > CS=std::nullopt, std::optional< StringRef > Source=std::nullopt),(Filename, Directory, CS, Source)) DEFINE_MDNODE_GET(DIFile
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
LLVM_ABI StringRef getName () const
LLVM_ABI DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
LLVM_ABI dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
LLVM_ABI TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
LLVM_ABI void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
LLVM_ABI void resolveCycles ()
Resolve cycles.
LLVM_ABI void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
LLVM_ABI bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
LLVM_ABI void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
LLVM_ABI void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
LLVM_ABI void dumpTree () const
User-friendly dump in tree shape.
LLVM_ABI void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static LLVM_ABI std::optional< ChecksumKind > getChecksumKind (StringRef CSKindStr)
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static LLVM_ABI DIFlags getFlag (StringRef Flag)
static LLVM_ABI StringRef getFlagString (DIFlags Flag)
static LLVM_ABI DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static LLVM_ABI void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static LLVM_ABI MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static LLVM_ABI MDNode * intersect (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericNoaliasAddrspace (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
static LLVM_ABI MDNode * getMergedMemProfMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCallsiteMetadata (MDNode *A, MDNode *B)
Public Attributes
MDString * Filename
MDString MDString * Directory
MDString MDString std::optional< ChecksumInfo< MDString * > > CS = std::nullopt
MDString MDString std::optional< ChecksumInfo< MDString * > > MDString * Source
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~DINode ()=default
template<class Ty>
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
LLVM_ABI MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~MDNode ()=default
LLVM_ABI void * operator new (size_t Size, size_t NumOps, StorageType Storage)
LLVM_ABI void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
LLVM_ABI void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
LLVM_ABI void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
LLVM_ABI void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T, class StoreT>
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T>
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
File.
TODO: Merge with directory/file node (including users). TODO: Canonicalize paths on creation.
Definition at line 579 of file DebugInfoMetadata.h.
Member Enumeration Documentation
ChecksumKind
enum llvm::DIFile::ChecksumKind
Which algorithm (e.g.
MD5) a checksum was generated with.
The encoding is explicit because it is used directly in Bitcode. The value 0 is reserved to indicate the absence of a checksum in Bitcode.
Enumerator
CSK_MD5
CSK_SHA1
CSK_SHA256
CSK_Last
Definition at line 588 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
bool llvm::DIFile::classof (const Metadata * MD) inline static
Definition at line 687 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
DEFINE_MDNODE_GET()
llvm::DIFile::DEFINE_MDNODE_GET (DIFile , (StringRef Filename, StringRef Directory, std::optional< ChecksumInfo< StringRef > > CS=std::nullopt, std::optional< StringRef > Source=std::nullopt) , (Filename, Directory, CS, Source))
References CS, Directory, and Filename.
getChecksumKind()
std::optional< DIFile::ChecksumKind > DIFile::getChecksumKind (StringRef CSKindStr) static
Definition at line 1175 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Case(), CSK_MD5, CSK_SHA1, CSK_SHA256, and llvm::StringSwitch< T, R >::Default().
Referenced by llvm::LLParser::parseMDField().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 580 of file DebugInfoMetadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
MDNode
friend class MDNode friend
Definition at line 581 of file DebugInfoMetadata.h.
References MDNode.
Referenced by MDNode.
Member Data Documentation
CS
MDString MDString std::optional<ChecksumInfo<MDString *> > llvm::DIFile::CS = std::nullopt
Definition at line 657 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET().
Directory
MDString MDString* llvm::DIFile::Directory
Definition at line 656 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET().
Filename
MDString* llvm::DIFile::Filename
Definition at line 656 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET().
Source
MDString MDString std::optional<ChecksumInfo<MDString *> > MDString* llvm::DIFile::Source
Initial value:
= nullptr),
                    (Filename, Directory, CS, Source))
  TempDIFile clone() const { return cloneImpl(); }
  StringRef getFilename() const { return getStringOperand(0); }
  StringRef getDirectory() const { return getStringOperand(1); }
  std::optional<ChecksumInfo<StringRef>> getChecksum() const {
    std::optional<ChecksumInfo<StringRef>> StringRefChecksum;
    if (Checksum)
      StringRefChecksum.emplace(Checksum->Kind, Checksum->Value->getString());
    return StringRefChecksum;
  }
  std::optional<StringRef> getSource() const {
    return Source ? std::optional<StringRef>(Source->getString())
                  : std::nullopt;
  }
  MDString *getRawFilename() const { return getOperandAs<MDString>(0); }
  MDString *getRawDirectory() const { return getOperandAs<MDString>(1); }
  std::optional<ChecksumInfo<MDString *>> getRawChecksum() const {
    return Checksum;
  }
  MDString *getRawSource() const { return Source; }
  LLVM_ABI static StringRef getChecksumKindAsString(ChecksumKind CSKind)
Definition at line 658 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp