LLVM: llvm::objcopy::elf::ELFWriter< ELFT > Class Template Reference
llvm::objcopy::elf::ELFWriter< ELFT > Class Template Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~ELFWriter ()
Error finalize () override
Error write () override
ELFWriter (Object &Obj, raw_ostream &Out, bool WSH, bool OnlyKeepDebug)
Public Member Functions inherited from llvm::objcopy::elf::Writer
virtual ~Writer ()
Writer (Object &O, raw_ostream &Out)
Public Attributes
bool WriteSectionHeaders
bool OnlyKeepDebug
Additional Inherited Members
Protected Attributes inherited from llvm::objcopy::elf::Writer
Object & Obj
std::unique_ptr< WritableMemoryBuffer > Buf
raw_ostream & Out
Detailed Description
template<class ELFT>
class llvm::objcopy::elf::ELFWriter< ELFT >
Definition at line 324 of file ELFObject.h.
Constructor & Destructor Documentation
~ELFWriter()
template<class ELFT> virtual llvm::objcopy::elf::ELFWriter< ELFT >::~ELFWriter () inline virtual
Definition at line 349 of file ELFObject.h.
ELFWriter()
template<class ELFT> ELFWriter::ELFWriter (Object & Obj, raw_ostream & Out, bool WSH, bool OnlyKeepDebug)
Definition at line 2152 of file ELFObject.cpp.
References llvm::objcopy::elf::Writer::Buf, llvm::objcopy::elf::Writer::Obj, OnlyKeepDebug, llvm::objcopy::elf::Writer::Writer(), and WriteSectionHeaders.
Member Function Documentation
finalize()
template<class ELFT> Error ELFWriter::finalize () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2576 of file ELFObject.cpp.
References llvm::any_of(), llvm::objcopy::elf::Writer::Buf, llvm::createStringError(), llvm::drop_begin(), llvm::dyn_cast(), llvm::WritableMemoryBuffer::getNewMemBuffer(), llvm::objcopy::elf::SectionBase::HasSymbol, llvm::invalid_argument, llvm::not_enough_memory, llvm::objcopy::elf::Writer::Obj, llvm::Offset, removeUnneededSections(), llvm::ELF::SHN_LORESERVE, llvm::Error::success(), llvm::Twine::utohexstr(), and WriteSectionHeaders.
write()
template<class ELFT> Error ELFWriter::write () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2540 of file ELFObject.cpp.
References llvm::objcopy::elf::Writer::Buf, llvm::objcopy::elf::Writer::Out, llvm::Error::success(), and WriteSectionHeaders.
Member Data Documentation
OnlyKeepDebug
template<class ELFT> bool llvm::objcopy::elf::ELFWriter< ELFT >::OnlyKeepDebug
Definition at line 354 of file ELFObject.h.
Referenced by ELFWriter().
WriteSectionHeaders
template<class ELFT> bool llvm::objcopy::elf::ELFWriter< ELFT >::WriteSectionHeaders
Definition at line 350 of file ELFObject.h.
Referenced by ELFWriter(), finalize(), and write().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/MC/ELFObjectWriter.cpp
lib/ObjCopy/ELF/ELFObject.cpp