LLVM: llvm::sandboxir::CollectDescr Class Reference
llvm::sandboxir::CollectDescr Class Reference
Describes how to collect the values needed by each lane.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h"
Classes
class ExtractElementDescr
Describes how to get a value element.
Public Types
using DescrVecT = SmallVector<ExtractElementDescr, 4>
Public Member Functions
CollectDescr (SmallVectorImpl< ExtractElementDescr > &&Descrs)
std::optional< std::pair< Action *, ShuffleMask > > getSingleInput () const
If all elements come from a single vector input, then return that vector and also the shuffle mask required to get them in order.
bool hasVectorInputs () const
const SmallVector< ExtractElementDescr, 4 > & getDescrs () const
Public Attributes
DescrVecT Descrs
Detailed Description
Describes how to collect the values needed by each lane.
Definition at line 252 of file Legality.h.
Member Typedef Documentation
DescrVecT
using llvm::sandboxir::CollectDescr::DescrVecT = SmallVector<ExtractElementDescr, 4>
Definition at line 271 of file Legality.h.
Constructor & Destructor Documentation
CollectDescr()
llvm::sandboxir::CollectDescr::CollectDescr (SmallVectorImpl< ExtractElementDescr > && Descrs) inline
Definition at line 275 of file Legality.h.
References Descrs, and llvm::move().
Member Function Documentation
getDescrs()
const SmallVector< ExtractElementDescr, 4 > & llvm::sandboxir::CollectDescr::getDescrs () const inline
Definition at line 298 of file Legality.h.
References Descrs.
getSingleInput()
std::optional< std::pair< Action *, ShuffleMask > > llvm::sandboxir::CollectDescr::getSingleInput () const inline
If all elements come from a single vector input, then return that vector and also the shuffle mask required to get them in order.
Definition at line 279 of file Legality.h.
References Descrs, llvm::drop_begin(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
hasVectorInputs()
bool llvm::sandboxir::CollectDescr::hasVectorInputs () const inline
Definition at line 295 of file Legality.h.
References llvm::any_of(), D(), and Descrs.
Member Data Documentation
Descrs
DescrVecT llvm::sandboxir::CollectDescr::Descrs
Definition at line 272 of file Legality.h.
Referenced by CollectDescr(), getDescrs(), getSingleInput(), and hasVectorInputs().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h