LLVM: llvm::orc::InProcessMemoryAccess Class Reference
llvm::orc::InProcessMemoryAccess Class Reference
#include "llvm/ExecutionEngine/Orc/InProcessMemoryAccess.h"
Public Member Functions
InProcessMemoryAccess (bool IsArch64Bit)
void writeUInt8sAsync (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt16sAsync (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt32sAsync (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt64sAsync (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete) override
void writePointersAsync (ArrayRef< tpctypes::PointerWrite > Ws, WriteResultFn OnWriteComplete) override
void writeBuffersAsync (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete) override
void readUInt8sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint8_t > OnComplete) override
void readUInt16sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint16_t > OnComplete) override
void readUInt32sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint32_t > OnComplete) override
void readUInt64sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint64_t > OnComplete) override
void readPointersAsync (ArrayRef< ExecutorAddr > Rs, OnReadPointersCompleteFn OnComplete) override
void readBuffersAsync (ArrayRef< ExecutorAddrRange > Rs, OnReadBuffersCompleteFn OnComplete) override
void readStringsAsync (ArrayRef< ExecutorAddr > Rs, OnReadStringsCompleteFn OnComplete) override
Public Member Functions inherited from llvm::orc::MemoryAccess
virtual ~MemoryAccess ()
Error writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws)
Error writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws)
Error writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws)
Error writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws)
Error writePointers (ArrayRef< tpctypes::PointerWrite > Ws)
Error writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws)
Expected< ReadUIntsResult< uint8_t > > readUInt8s (ArrayRef< ExecutorAddr > Rs)
Expected< ReadUIntsResult< uint16_t > > readUInt16s (ArrayRef< ExecutorAddr > Rs)
Expected< ReadUIntsResult< uint32_t > > readUInt32s (ArrayRef< ExecutorAddr > Rs)
Expected< ReadUIntsResult< uint64_t > > readUInt64s (ArrayRef< ExecutorAddr > Rs)
Expected< ReadPointersResult > readPointers (ArrayRef< ExecutorAddr > Rs)
Expected< ReadBuffersResult > readBuffers (ArrayRef< ExecutorAddrRange > Rs)
Expected< ReadStringsResult > readStrings (ArrayRef< ExecutorAddr > Rs)
Additional Inherited Members
Public Types inherited from llvm::orc::MemoryAccess
using WriteResultFn = unique_function<void(Error)>
Callback function for asynchronous writes.
template<typename T>
using ReadUIntsResult = std::vector<T>
template<typename T>
using OnReadUIntsCompleteFn
using ReadPointersResult = std::vector<ExecutorAddr>
using OnReadPointersCompleteFn
using ReadBuffersResult = std::vector<std::vector<uint8_t>>
using OnReadBuffersCompleteFn
using ReadStringsResult = std::vector<std::string>
using OnReadStringsCompleteFn
Detailed Description
Definition at line 20 of file InProcessMemoryAccess.h.
Constructor & Destructor Documentation
InProcessMemoryAccess()
llvm::orc::InProcessMemoryAccess::InProcessMemoryAccess (bool IsArch64Bit) inline
Definition at line 22 of file InProcessMemoryAccess.h.
Member Function Documentation
readBuffersAsync()
void llvm::orc::InProcessMemoryAccess::readBuffersAsync (ArrayRef< ExecutorAddrRange > Rs, OnReadBuffersCompleteFn OnComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 110 of file InProcessMemoryAccess.cpp.
References llvm::orc::Result, and llvm::ArrayRef< T >::size().
readPointersAsync()
void llvm::orc::InProcessMemoryAccess::readPointersAsync (ArrayRef< ExecutorAddr > Rs, OnReadPointersCompleteFn OnComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 101 of file InProcessMemoryAccess.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::orc::Result, and llvm::ArrayRef< T >::size().
readStringsAsync()
void llvm::orc::InProcessMemoryAccess::readStringsAsync (ArrayRef< ExecutorAddr > Rs, OnReadStringsCompleteFn OnComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 122 of file InProcessMemoryAccess.cpp.
References P, llvm::orc::Result, and llvm::ArrayRef< T >::size().
readUInt16sAsync()
void llvm::orc::InProcessMemoryAccess::readUInt16sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint16_t > OnComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 74 of file InProcessMemoryAccess.cpp.
References llvm::orc::Result, and llvm::ArrayRef< T >::size().
readUInt32sAsync()
void llvm::orc::InProcessMemoryAccess::readUInt32sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint32_t > OnComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 83 of file InProcessMemoryAccess.cpp.
References llvm::orc::Result, and llvm::ArrayRef< T >::size().
readUInt64sAsync()
void llvm::orc::InProcessMemoryAccess::readUInt64sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint64_t > OnComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 92 of file InProcessMemoryAccess.cpp.
References llvm::orc::Result, and llvm::ArrayRef< T >::size().
readUInt8sAsync()
void llvm::orc::InProcessMemoryAccess::readUInt8sAsync (ArrayRef< ExecutorAddr > Rs, OnReadUIntsCompleteFn< uint8_t > OnComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 65 of file InProcessMemoryAccess.cpp.
References llvm::orc::Result, and llvm::ArrayRef< T >::size().
writeBuffersAsync()
void llvm::orc::InProcessMemoryAccess::writeBuffersAsync (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 58 of file InProcessMemoryAccess.cpp.
References llvm::Error::success().
writePointersAsync()
void llvm::orc::InProcessMemoryAccess::writePointersAsync (ArrayRef< tpctypes::PointerWrite > Ws, WriteResultFn OnWriteComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 45 of file InProcessMemoryAccess.cpp.
References llvm::Error::success().
writeUInt16sAsync()
void llvm::orc::InProcessMemoryAccess::writeUInt16sAsync (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 24 of file InProcessMemoryAccess.cpp.
References llvm::Error::success().
writeUInt32sAsync()
void llvm::orc::InProcessMemoryAccess::writeUInt32sAsync (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 31 of file InProcessMemoryAccess.cpp.
References llvm::Error::success().
writeUInt64sAsync()
void llvm::orc::InProcessMemoryAccess::writeUInt64sAsync (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 38 of file InProcessMemoryAccess.cpp.
References llvm::Error::success().
writeUInt8sAsync()
void llvm::orc::InProcessMemoryAccess::writeUInt8sAsync (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete) override virtual
Implements llvm::orc::MemoryAccess.
Definition at line 17 of file InProcessMemoryAccess.cpp.
References llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/InProcessMemoryAccess.h
lib/ExecutionEngine/Orc/InProcessMemoryAccess.cpp