LLVM: llvm::sandboxir::Instruction Class Reference
llvm::sandboxir::Instruction Class Reference abstract
A sandboxir::User with operands, opcode and linked with previous/next instructions in an instruction list.
#include "llvm/SandboxIR/Instruction.h"
Public Types
enum class Opcode
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Public Member Functions
virtual unsigned getNumOfIRInstrs () const =0
This is used by BasicBlock::iterator.
LLVM_ABI BBIterator getIterator () const
\Returns a BasicBlock::iterator for this Instruction.
LLVM_ABI Instruction * getNextNode () const
\Returns the next sandboxir::Instruction in the block, or nullptr if at the end of the block.
LLVM_ABI Instruction * getPrevNode () const
\Returns the previous sandboxir::Instruction in the block, or nullptr if at the beginning of the block.
Opcode getOpcode () const
\Returns this Instruction's opcode.
const char * getOpcodeName () const
const DataLayout & getDataLayout () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isSpecialTerminator () const
bool isOnlyUserOfAnyOperand () const
bool isLogicalShift () const
bool hasMetadata () const
Return true if the instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
LLVM_ABI void removeFromParent ()
Detach this from its parent BasicBlock without deleting it.
LLVM_ABI void eraseFromParent ()
Detach this Value from its parent and delete it.
LLVM_ABI void insertBefore (Instruction *BeforeI)
Insert this detached instruction before BeforeI.
LLVM_ABI void insertAfter (Instruction *AfterI)
Insert this detached instruction after AfterI.
LLVM_ABI void insertInto (BasicBlock *BB, const BBIterator &WhereIt)
Insert this detached instruction into BB at WhereIt.
LLVM_ABI void moveBefore (BasicBlock &BB, const BBIterator &WhereIt)
Move this instruction to WhereIt.
void moveBefore (Instruction *Before)
Move this instruction before Before.
void moveAfter (Instruction *After)
Move this instruction after After.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
LLVM_ABI BasicBlock * getParent () const
\Returns the BasicBlock containing this Instruction, or null if it is detached.
bool hasNoUnsignedWrap () const
Determine whether the no signed wrap flag is set.
LLVM_ABI void setHasNoUnsignedWrap (bool B=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
bool hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
LLVM_ABI void setHasNoSignedWrap (bool B=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
bool isFast () const
Determine whether all fast-math-flags are set.
LLVM_ABI void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
bool hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
LLVM_ABI void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
bool isExact () const
Determine whether the exact flag is set.
LLVM_ABI void setIsExact (bool B=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
LLVM_ABI void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
LLVM_ABI void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
LLVM_ABI void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
LLVM_ABI void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
bool hasAllowContract () const
Determine whether the allow-contract flag is set.
LLVM_ABI void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
bool hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
LLVM_ABI void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
LLVM_ABI void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool isAtomic () const
bool hasAtomicLoad () const
bool hasAtomicStore () const
bool isVolatile () const
LLVM_ABI Type * getAccessType () const
bool mayThrow (bool IncludePhaseOneUnwind=false) const
bool isFenceLike () const
bool mayHaveSideEffects () const
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static LLVM_ABI const char * getOpcodeName (Opcode Opc)
static LLVM_ABI bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Protected Member Functions
Instruction (ClassID ID, Opcode Opc, llvm::Instruction *I, sandboxir::Context &SBCtx)
LLVM_ABI llvm::Instruction * getTopmostLLVMInstruction () const
A SandboxIR Instruction may map to multiple LLVM IR Instruction.
virtual SmallVector< llvm::Instruction *, 1 > getLLVMInstrs () const =0
\Returns the LLVM IR Instructions that this SandboxIR maps to in program order.
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
virtual Use getOperandUseInternal (unsigned OpIdx, bool Verify) const =0
\Returns the Use for the OpIdx'th operand.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
virtual unsigned getUseOperandNo (const Use &Use) const =0
\Returns the operand index of Use.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Static Protected Member Functions
static IRBuilder & setInsertPos (InsertPosition Pos)
Helper function for create().
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes
Opcode Opc
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Friends
class VAArgInst
class FreezeInst
class FenceInst
class SelectInst
class ExtractElementInst
class InsertElementInst
class ShuffleVectorInst
class ExtractValueInst
class InsertValueInst
class BranchInst
class LoadInst
class StoreInst
class ReturnInst
class CallInst
class InvokeInst
class CallBrInst
class LandingPadInst
class CatchPadInst
class CleanupPadInst
class CatchReturnInst
class CleanupReturnInst
class GetElementPtrInst
class ResumeInst
class CatchSwitchInst
class SwitchInst
class UnaryOperator
class BinaryOperator
class AtomicRMWInst
class AtomicCmpXchgInst
class AllocaInst
class CastInst
class PHINode
class UnreachableInst
class CmpInst
class EraseFromParent
Detailed Description
A sandboxir::User with operands, opcode and linked with previous/next instructions in an instruction list.
Definition at line 43 of file Instruction.h.
Member Enumeration Documentation
Opcode
enum class llvm::sandboxir::Instruction::Opcode strong
Definition at line 45 of file Instruction.h.
Constructor & Destructor Documentation
Instruction()
llvm::sandboxir::Instruction::Instruction (ClassID ID, Opcode Opc, llvm::Instruction * I, sandboxir::Context & SBCtx) inline protected
Definition at line 53 of file Instruction.h.
References I, Opc, and llvm::sandboxir::User::User().
Referenced by comesBefore(), getNextNode(), getNumOfIRInstrs(), getPrevNode(), getTopmostLLVMInstruction(), insertAfter(), insertBefore(), insertInto(), moveAfter(), and moveBefore().
Member Function Documentation
classof()
bool llvm::sandboxir::Instruction::classof (const sandboxir::Value * From) static
For isa/dyn_cast.
Definition at line 170 of file Instruction.cpp.
References llvm::sandboxir::Value::getSubclassID().
comesBefore()
bool llvm::sandboxir::Instruction::comesBefore (const Instruction * Other) const inline
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
Definition at line 215 of file Instruction.h.
References llvm::cast(), Instruction(), llvm::Other, and llvm::sandboxir::Value::Val.
Referenced by llvm::sandboxir::SchedBundle::getBot(), llvm::sandboxir::VecUtils::getLowest(), llvm::sandboxir::VecUtils::getLowest(), and llvm::sandboxir::DependencyGraph::print().
copyFastMathFlags()
void llvm::sandboxir::Instruction::copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
See LangRef.html for the meaning of these flags.
Definition at line 264 of file Instruction.cpp.
References llvm::sandboxir::Value::Ctx.
Referenced by setFastMathFlags().
dumpOS()
void llvm::sandboxir::Instruction::dumpOS (raw_ostream & OS) const override virtual
Implements llvm::sandboxir::Value.
Reimplemented in llvm::sandboxir::SingleLLVMInstructionImpl< LLVMT >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::AtomicCmpXchgInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::AtomicRMWInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::BinaryOperator >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::BranchInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CallBase >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CatchReturnInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CatchSwitchInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CleanupReturnInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CmpInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ExtractElementInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::FenceInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::FuncletPadInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::GetElementPtrInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::InsertElementInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::InsertValueInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::Instruction >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::LandingPadInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::PHINode >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ResumeInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ReturnInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::SelectInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ShuffleVectorInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::StoreInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::SwitchInst >, and llvm::sandboxir::SingleLLVMInstructionImpl< llvm::UnaryInstruction >.
Definition at line 283 of file Instruction.cpp.
eraseFromParent()
void llvm::sandboxir::Instruction::eraseFromParent ()
Detach this Value from its parent and delete it.
Definition at line 74 of file Instruction.cpp.
References assert(), llvm::sandboxir::empty(), and llvm::sandboxir::Value::users().
getAccessType()
Type * llvm::sandboxir::Instruction::getAccessType () const
Definition at line 271 of file Instruction.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, getAccessType(), and llvm::sandboxir::Value::Val.
Referenced by getAccessType().
getDataLayout()
const DataLayout & llvm::sandboxir::Instruction::getDataLayout () const inline
Definition at line 134 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getFastMathFlags()
FastMathFlags llvm::sandboxir::Instruction::getFastMathFlags () const inline
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
See LangRef.html for the meaning of these flags.
Definition at line 305 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setFastMathFlags().
getIterator()
BBIterator llvm::sandboxir::Instruction::getIterator () const
\Returns a BasicBlock::iterator for this Instruction.
Definition at line 38 of file Instruction.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, I, and llvm::sandboxir::Value::Val.
Referenced by getNextNode(), getPrevNode(), insertAfter(), moveAfter(), moveBefore(), and moveBefore().
getLLVMInstrs()
virtual SmallVector< llvm::Instruction *, 1 > llvm::sandboxir::Instruction::getLLVMInstrs () const protected pure virtual
\Returns the LLVM IR Instructions that this SandboxIR maps to in program order.
Referenced by insertBefore(), and insertInto().
getNextNode()
Instruction * llvm::sandboxir::Instruction::getNextNode () const
\Returns the next sandboxir::Instruction in the block, or nullptr if at the end of the block.
Definition at line 43 of file Instruction.cpp.
References assert(), llvm::sandboxir::end(), getIterator(), getParent(), and Instruction().
getNumOfIRInstrs()
virtual unsigned llvm::sandboxir::Instruction::getNumOfIRInstrs () const pure virtual
This is used by BasicBlock::iterator.
Implemented in llvm::sandboxir::SingleLLVMInstructionImpl< LLVMT >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::AtomicCmpXchgInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::AtomicRMWInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::BinaryOperator >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::BranchInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CallBase >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CatchReturnInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CatchSwitchInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CleanupReturnInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CmpInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ExtractElementInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::FenceInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::FuncletPadInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::GetElementPtrInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::InsertElementInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::InsertValueInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::Instruction >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::LandingPadInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::PHINode >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ResumeInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ReturnInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::SelectInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::ShuffleVectorInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::StoreInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::SwitchInst >, llvm::sandboxir::SingleLLVMInstructionImpl< llvm::UnaryInstruction >, and llvm::sandboxir::UnreachableInst.
References Instruction(), and LLVM_ABI.
getOpcode()
Opcode llvm::sandboxir::Instruction::getOpcode () const inline
\Returns this Instruction's opcode.
Note that SandboxIR has its own opcode state to allow for new SandboxIR-specific instructions.
Definition at line 130 of file Instruction.h.
References Opc.
Referenced by llvm::sandboxir::BinaryOperator::BinaryOperator().
getOpcodeName() [1/2]
const char * llvm::sandboxir::Instruction::getOpcodeName () const inline
Definition at line 132 of file Instruction.h.
References getOpcodeName(), and Opc.
Referenced by getOpcodeName().
getOpcodeName() [2/2]
const char * llvm::sandboxir::Instruction::getOpcodeName (Opcode Opc) static
Definition at line 14 of file Instruction.cpp.
References llvm_unreachable, and Opc.
getParent()
BasicBlock * llvm::sandboxir::Instruction::getParent () const
\Returns the BasicBlock containing this Instruction, or null if it is detached.
Definition at line 161 of file Instruction.cpp.
References llvm::sandboxir::BasicBlock(), llvm::cast(), llvm::sandboxir::Value::Ctx, llvm::BasicBlock::getParent(), and llvm::sandboxir::Value::Val.
Referenced by getNextNode(), getPrevNode(), getTopmostLLVMInstruction(), insertAfter(), llvm::sandboxir::VecUtils::matchPack(), moveAfter(), and moveBefore().
getPrevNode()
Instruction * llvm::sandboxir::Instruction::getPrevNode () const
\Returns the previous sandboxir::Instruction in the block, or nullptr if at the beginning of the block.
Definition at line 58 of file Instruction.cpp.
References assert(), llvm::sandboxir::begin(), getIterator(), getParent(), and Instruction().
Referenced by getTopmostLLVMInstruction().
getTopmostLLVMInstruction()
llvm::Instruction * llvm::sandboxir::Instruction::getTopmostLLVMInstruction () const protected
A SandboxIR Instruction may map to multiple LLVM IR Instruction.
This returns its topmost LLVM IR instruction.
Definition at line 26 of file Instruction.cpp.
References llvm::cast(), getParent(), getPrevNode(), Instruction(), and llvm::sandboxir::Value::Val.
Referenced by insertBefore(), and insertInto().
hasAllowContract()
bool llvm::sandboxir::Instruction::hasAllowContract () const inline
Determine whether the allow-contract flag is set.
Definition at line 287 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setHasAllowContract().
hasAllowReassoc()
bool llvm::sandboxir::Instruction::hasAllowReassoc () const inline
Determine whether the allow-reassociation flag is set.
Definition at line 246 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasAllowReciprocal()
bool llvm::sandboxir::Instruction::hasAllowReciprocal () const inline
Determine whether the allow-reciprocal flag is set.
Definition at line 279 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setHasAllowReciprocal().
hasApproxFunc()
bool llvm::sandboxir::Instruction::hasApproxFunc () const inline
Determine whether the approximate-math-functions flag is set.
Definition at line 295 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setHasApproxFunc().
hasAtomicLoad()
bool llvm::sandboxir::Instruction::hasAtomicLoad () const inline
Definition at line 346 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasAtomicStore()
bool llvm::sandboxir::Instruction::hasAtomicStore () const inline
Definition at line 350 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasMetadata() [1/2]
bool llvm::sandboxir::Instruction::hasMetadata () const inline
Return true if the instruction has any metadata attached to it.
Definition at line 171 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasMetadata() [2/2]
bool llvm::sandboxir::Instruction::hasMetadata (unsigned KindID) const inline
Return true if this instruction has the given type of metadata attached.
Definition at line 182 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasMetadataOtherThanDebugLoc()
bool llvm::sandboxir::Instruction::hasMetadataOtherThanDebugLoc () const inline
Return true if this instruction has metadata attached to it other than a debug location.
Definition at line 177 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasNoInfs()
bool llvm::sandboxir::Instruction::hasNoInfs () const inline
Determine whether the no-infs flag is set.
Definition at line 265 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasNoNaNs()
bool llvm::sandboxir::Instruction::hasNoNaNs () const inline
Determine whether the no-NaNs flag is set.
Definition at line 259 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasNoSignedWrap()
bool llvm::sandboxir::Instruction::hasNoSignedWrap () const inline
Determine whether the no signed wrap flag is set.
Definition at line 233 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setHasNoSignedWrap().
hasNoSignedZeros()
bool llvm::sandboxir::Instruction::hasNoSignedZeros () const inline
Determine whether the no-signed-zeros flag is set.
Definition at line 271 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setHasNoSignedZeros().
hasNoUnsignedWrap()
bool llvm::sandboxir::Instruction::hasNoUnsignedWrap () const inline
Determine whether the no signed wrap flag is set.
Definition at line 226 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
insertAfter()
void llvm::sandboxir::Instruction::insertAfter (Instruction * AfterI)
Insert this detached instruction after AfterI.
Definition at line 135 of file Instruction.cpp.
References getIterator(), getParent(), insertInto(), and Instruction().
insertBefore()
void llvm::sandboxir::Instruction::insertBefore (Instruction * BeforeI)
Insert this detached instruction before BeforeI.
Definition at line 125 of file Instruction.cpp.
References llvm::sandboxir::Value::Ctx, llvm::ilist_node_impl< OptionsT >::getIterator(), getLLVMInstrs(), getTopmostLLVMInstruction(), I, and Instruction().
insertInto()
void llvm::sandboxir::Instruction::insertInto (BasicBlock * BB, const BBIterator & WhereIt)
Insert this detached instruction into BB at WhereIt.
Definition at line 139 of file Instruction.cpp.
References llvm::sandboxir::BasicBlock(), llvm::cast(), llvm::sandboxir::Value::Ctx, llvm::BasicBlock::end(), llvm::ilist_node_impl< OptionsT >::getIterator(), getLLVMInstrs(), getTopmostLLVMInstruction(), I, and Instruction().
Referenced by insertAfter().
isAssociative()
bool llvm::sandboxir::Instruction::isAssociative () const inline
Definition at line 317 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isAtomic()
bool llvm::sandboxir::Instruction::isAtomic () const inline
Definition at line 344 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isBinaryOp()
bool llvm::sandboxir::Instruction::isBinaryOp () const inline
Definition at line 147 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isCast()
bool llvm::sandboxir::Instruction::isCast () const inline
Definition at line 152 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isCommutative()
bool llvm::sandboxir::Instruction::isCommutative () const inline
Definition at line 321 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by llvm::sandboxir::CmpInst::WRAP_MEMBER(), llvm::sandboxir::FCmpInst::WRAP_MEMBER(), and llvm::sandboxir::ICmpInst::WRAP_MEMBER().
isExact()
bool llvm::sandboxir::Instruction::isExact () const inline
Determine whether the exact flag is set.
Definition at line 254 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isFast()
bool llvm::sandboxir::Instruction::isFast () const inline
Determine whether all fast-math-flags are set.
Definition at line 240 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isFenceLike()
bool llvm::sandboxir::Instruction::isFenceLike () const inline
Definition at line 362 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isFuncletPad()
bool llvm::sandboxir::Instruction::isFuncletPad () const inline
Definition at line 153 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isIdempotent()
bool llvm::sandboxir::Instruction::isIdempotent () const inline
Definition at line 325 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isIntDivRem()
bool llvm::sandboxir::Instruction::isIntDivRem () const inline
Definition at line 148 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isLogicalShift()
bool llvm::sandboxir::Instruction::isLogicalShift () const inline
Definition at line 162 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isNilpotent()
bool llvm::sandboxir::Instruction::isNilpotent () const inline
Definition at line 329 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isOnlyUserOfAnyOperand()
bool llvm::sandboxir::Instruction::isOnlyUserOfAnyOperand () const inline
Definition at line 159 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isShift()
bool llvm::sandboxir::Instruction::isShift () const inline
Definition at line 151 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isSpecialTerminator()
bool llvm::sandboxir::Instruction::isSpecialTerminator () const inline
Definition at line 156 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isTerminator()
bool llvm::sandboxir::Instruction::isTerminator () const inline
Definition at line 143 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isUnaryOp()
bool llvm::sandboxir::Instruction::isUnaryOp () const inline
Definition at line 146 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isVolatile()
bool llvm::sandboxir::Instruction::isVolatile () const inline
Definition at line 354 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
mayHaveSideEffects()
bool llvm::sandboxir::Instruction::mayHaveSideEffects () const inline
Definition at line 366 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
mayReadFromMemory()
bool llvm::sandboxir::Instruction::mayReadFromMemory () const inline
Definition at line 337 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
mayReadOrWriteMemory()
bool llvm::sandboxir::Instruction::mayReadOrWriteMemory () const inline
Definition at line 340 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
mayThrow()
bool llvm::sandboxir::Instruction::mayThrow (bool IncludePhaseOneUnwind = false) const inline
Definition at line 358 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
mayWriteToMemory()
bool llvm::sandboxir::Instruction::mayWriteToMemory () const inline
Definition at line 333 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
moveAfter()
void llvm::sandboxir::Instruction::moveAfter (Instruction * After) inline
Move this instruction after After.
Definition at line 208 of file Instruction.h.
References getIterator(), getParent(), Instruction(), and moveBefore().
moveBefore() [1/2]
void llvm::sandboxir::Instruction::moveBefore (BasicBlock & BB, const BBIterator & WhereIt)
Move this instruction to WhereIt.
Definition at line 100 of file Instruction.cpp.
References llvm::sandboxir::BasicBlock(), llvm::sandboxir::Value::Ctx, and getIterator().
Referenced by moveAfter(), and moveBefore().
moveBefore() [2/2]
void llvm::sandboxir::Instruction::moveBefore (Instruction * Before) inline
Move this instruction before Before.
Definition at line 204 of file Instruction.h.
References getIterator(), getParent(), Instruction(), and moveBefore().
removeFromParent()
void llvm::sandboxir::Instruction::removeFromParent ()
Detach this from its parent BasicBlock without deleting it.
Definition at line 66 of file Instruction.cpp.
References llvm::sandboxir::Value::Ctx.
setFast()
void llvm::sandboxir::Instruction::setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 196 of file Instruction.cpp.
References B(), llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
setFastMathFlags()
void llvm::sandboxir::Instruction::setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
See LangRef.html for the meaning of these flags.
Definition at line 257 of file Instruction.cpp.
References llvm::cast(), copyFastMathFlags(), llvm::sandboxir::Value::Ctx, getFastMathFlags(), and llvm::sandboxir::Value::Val.
setHasAllowContract()
void llvm::sandboxir::Instruction::setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 249 of file Instruction.cpp.
References B(), llvm::sandboxir::Value::Ctx, and hasAllowContract().
setHasAllowReassoc()
void llvm::sandboxir::Instruction::setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 210 of file Instruction.cpp.
setHasAllowReciprocal()
void llvm::sandboxir::Instruction::setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 241 of file Instruction.cpp.
References B(), llvm::cast(), llvm::sandboxir::Value::Ctx, hasAllowReciprocal(), setHasAllowReciprocal(), and llvm::sandboxir::Value::Val.
Referenced by setHasAllowReciprocal().
setHasApproxFunc()
void llvm::sandboxir::Instruction::setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 275 of file Instruction.cpp.
References B(), llvm::sandboxir::Value::Ctx, hasApproxFunc(), and setHasApproxFunc().
Referenced by setHasApproxFunc().
setHasNoInfs()
void llvm::sandboxir::Instruction::setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 225 of file Instruction.cpp.
References B(), llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
setHasNoNaNs()
void llvm::sandboxir::Instruction::setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 217 of file Instruction.cpp.
References B(), llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
setHasNoSignedWrap()
void llvm::sandboxir::Instruction::setHasNoSignedWrap (bool B = true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 189 of file Instruction.cpp.
References B(), llvm::cast(), llvm::sandboxir::Value::Ctx, hasNoSignedWrap(), setHasNoSignedWrap(), and llvm::sandboxir::Value::Val.
Referenced by setHasNoSignedWrap().
setHasNoSignedZeros()
void llvm::sandboxir::Instruction::setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 233 of file Instruction.cpp.
References B(), llvm::cast(), llvm::sandboxir::Value::Ctx, hasNoSignedZeros(), setHasNoSignedZeros(), and llvm::sandboxir::Value::Val.
Referenced by setHasNoSignedZeros().
setHasNoUnsignedWrap()
void llvm::sandboxir::Instruction::setHasNoUnsignedWrap (bool B = true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 181 of file Instruction.cpp.
References B(), and llvm::sandboxir::Value::Ctx.
setInsertPos()
IRBuilder & llvm::sandboxir::Instruction::setInsertPos (InsertPosition Pos) inline static protected
Helper function for create().
It sets the builder's insert position according to Pos.
Definition at line 104 of file Instruction.h.
References llvm::cast(), llvm::sandboxir::Value::Ctx, llvm::sandboxir::InsertPosition::getBasicBlock(), and llvm::sandboxir::InsertPosition::getIterator().
Referenced by llvm::Instruction::clone(), llvm::sandboxir::AtomicCmpXchgInst::create(), llvm::sandboxir::BinaryOperator::create(), llvm::sandboxir::BranchInst::create(), llvm::sandboxir::BranchInst::create(), llvm::sandboxir::CastInst::create(), llvm::sandboxir::CatchPadInst::create(), llvm::sandboxir::CatchReturnInst::create(), llvm::sandboxir::CleanupPadInst::create(), llvm::sandboxir::CleanupReturnInst::create(), llvm::sandboxir::CmpInst::create(), llvm::sandboxir::ExtractElementInst::create(), llvm::sandboxir::ExtractValueInst::create(), llvm::sandboxir::FenceInst::create(), llvm::sandboxir::FreezeInst::create(), llvm::sandboxir::GetElementPtrInst::create(), llvm::sandboxir::InsertElementInst::create(), llvm::sandboxir::InsertValueInst::create(), llvm::sandboxir::InvokeInst::create(), llvm::sandboxir::LandingPadInst::create(), llvm::sandboxir::LoadInst::create(), llvm::sandboxir::PHINode::create(), llvm::sandboxir::ReturnInst::create(), llvm::sandboxir::SelectInst::create(), llvm::sandboxir::ShuffleVectorInst::create(), llvm::sandboxir::ShuffleVectorInst::create(), llvm::sandboxir::StoreInst::create(), llvm::sandboxir::UnaryOperator::create(), llvm::sandboxir::UnreachableInst::create(), llvm::sandboxir::VAArgInst::create(), llvm::Instruction::dropPoisonGeneratingReturnAttributes(), llvm::Instruction::getSuccessor(), llvm::CallBase::Instruction(), llvm::Instruction::isAtomic(), and llvm::Instruction::setFast().
setIsExact()
void llvm::sandboxir::Instruction::setIsExact (bool B = true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 203 of file Instruction.cpp.
References B(), llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
Friends And Related Symbol Documentation
AllocaInst
friend class AllocaInst friend
Definition at line 91 of file Instruction.h.
References AllocaInst.
Referenced by AllocaInst.
AtomicCmpXchgInst
friend class AtomicCmpXchgInst friend
Definition at line 90 of file Instruction.h.
References AtomicCmpXchgInst.
Referenced by AtomicCmpXchgInst.
AtomicRMWInst
friend class AtomicRMWInst friend
Definition at line 89 of file Instruction.h.
References AtomicRMWInst.
Referenced by AtomicRMWInst.
BinaryOperator
friend class BinaryOperator friend
Definition at line 88 of file Instruction.h.
References BinaryOperator.
Referenced by BinaryOperator.
BranchInst
friend class BranchInst friend
Definition at line 71 of file Instruction.h.
References BranchInst.
Referenced by BranchInst.
CallBrInst
friend class CallBrInst friend
Definition at line 77 of file Instruction.h.
References CallBrInst.
Referenced by CallBrInst.
CallInst
friend class CallInst friend
Definition at line 75 of file Instruction.h.
References CallInst.
Referenced by CallInst.
CastInst
friend class CastInst friend
Definition at line 92 of file Instruction.h.
References CastInst.
Referenced by CastInst.
CatchPadInst
friend class CatchPadInst friend
Definition at line 79 of file Instruction.h.
References CatchPadInst.
Referenced by CatchPadInst.
CatchReturnInst
friend class CatchReturnInst friend
Definition at line 81 of file Instruction.h.
References CatchReturnInst.
Referenced by CatchReturnInst.
CatchSwitchInst
friend class CatchSwitchInst friend
Definition at line 85 of file Instruction.h.
References CatchSwitchInst.
Referenced by CatchSwitchInst.
CleanupPadInst
friend class CleanupPadInst friend
Definition at line 80 of file Instruction.h.
References CleanupPadInst.
Referenced by CleanupPadInst.
CleanupReturnInst
friend class CleanupReturnInst friend
Definition at line 82 of file Instruction.h.
References CleanupReturnInst.
Referenced by CleanupReturnInst.
CmpInst
friend class CmpInst friend
Definition at line 95 of file Instruction.h.
References CmpInst.
Referenced by CmpInst.
EraseFromParent
friend class EraseFromParent friend
Definition at line 100 of file Instruction.h.
References EraseFromParent.
Referenced by EraseFromParent.
ExtractElementInst
friend class ExtractElementInst friend
Definition at line 66 of file Instruction.h.
References ExtractElementInst.
Referenced by ExtractElementInst.
ExtractValueInst
friend class ExtractValueInst friend
Definition at line 69 of file Instruction.h.
References ExtractValueInst.
Referenced by ExtractValueInst.
FenceInst
friend class FenceInst friend
Definition at line 64 of file Instruction.h.
References FenceInst.
Referenced by FenceInst.
FreezeInst
friend class FreezeInst friend
Definition at line 63 of file Instruction.h.
References FreezeInst.
Referenced by FreezeInst.
GetElementPtrInst
friend class GetElementPtrInst friend
Definition at line 83 of file Instruction.h.
References GetElementPtrInst.
Referenced by GetElementPtrInst.
InsertElementInst
friend class InsertElementInst friend
Definition at line 67 of file Instruction.h.
References InsertElementInst.
Referenced by InsertElementInst.
InsertValueInst
friend class InsertValueInst friend
Definition at line 70 of file Instruction.h.
References InsertValueInst.
Referenced by InsertValueInst.
InvokeInst
friend class InvokeInst friend
Definition at line 76 of file Instruction.h.
References InvokeInst.
Referenced by InvokeInst.
LandingPadInst
friend class LandingPadInst friend
Definition at line 78 of file Instruction.h.
References LandingPadInst.
Referenced by LandingPadInst.
LoadInst
friend class LoadInst friend
Definition at line 72 of file Instruction.h.
References LoadInst.
Referenced by LoadInst.
PHINode
friend class PHINode friend
Definition at line 93 of file Instruction.h.
References PHINode.
Referenced by PHINode.
ResumeInst
friend class ResumeInst friend
Definition at line 84 of file Instruction.h.
References ResumeInst.
Referenced by ResumeInst.
ReturnInst
friend class ReturnInst friend
Definition at line 74 of file Instruction.h.
References ReturnInst.
Referenced by ReturnInst.
SelectInst
friend class SelectInst friend
Definition at line 65 of file Instruction.h.
References SelectInst.
Referenced by SelectInst.
ShuffleVectorInst
friend class ShuffleVectorInst friend
Definition at line 68 of file Instruction.h.
References ShuffleVectorInst.
Referenced by ShuffleVectorInst.
StoreInst
friend class StoreInst friend
Definition at line 73 of file Instruction.h.
References StoreInst.
Referenced by StoreInst.
SwitchInst
friend class SwitchInst friend
Definition at line 86 of file Instruction.h.
References SwitchInst.
Referenced by SwitchInst.
UnaryOperator
friend class UnaryOperator friend
Definition at line 87 of file Instruction.h.
References UnaryOperator.
Referenced by UnaryOperator.
UnreachableInst
friend class UnreachableInst friend
Definition at line 94 of file Instruction.h.
References UnreachableInst.
Referenced by UnreachableInst.
VAArgInst
friend class VAArgInst friend
Definition at line 62 of file Instruction.h.
References VAArgInst.
Referenced by VAArgInst.
Member Data Documentation
Opc
Opcode llvm::sandboxir::Instruction::Opc protected
Definition at line 57 of file Instruction.h.
Referenced by llvm::sandboxir::CallBase::classof(), llvm::sandboxir::CmpInst::CmpInst(), getOpcode(), getOpcodeName(), getOpcodeName(), Instruction(), and llvm::sandboxir::UnaryInstruction::UnaryInstruction().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Instruction.h
lib/SandboxIR/Instruction.cpp