LLVM: llvm::logicalview::LVLogicalVisitor Class Reference
llvm::logicalview::LVLogicalVisitor Class Reference final
#include "llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h"
Public Member Functions
LVLogicalVisitor (LVCodeViewReader *Reader, ScopedPrinter &W, llvm::pdb::InputFile &Input)
void setInput (std::shared_ptr< llvm::pdb::InputFile > TypeServer)
void setInput (std::shared_ptr< LazyRandomTypeCollection > PrecompHeader)
void addInlineeInfo (TypeIndex TI, uint32_t LineNumber, StringRef Filename)
void printTypeIndex (StringRef FieldName, TypeIndex TI, uint32_t StreamIdx)
void printMemberAttributes (MemberAttributes Attrs)
void printMemberAttributes (MemberAccess Access, MethodKind Kind, MethodOptions Options)
LVElement * createElement (TypeLeafKind Kind)
LVElement * createElement (SymbolKind Kind)
LVElement * createElement (TypeIndex TI, TypeLeafKind Kind)
Error inlineSiteAnnotation (LVScope *AbstractFunction, LVScope *InlinedFunction, InlineSiteSym &InlineSite)
void pushScope (LVScope *Scope)
void popScope ()
void closeScope ()
void setRoot (LVScope *Root)
void addElement (LVScope *Scope, bool IsCompileUnit)
void addElement (LVSymbol *Symbol)
void addElement (LVType *Type)
std::string getCompileUnitName ()
void setCompileUnitName (std::string Name)
LVElement * getElement (uint32_t StreamIdx, TypeIndex TI, LVScope *Parent=nullptr)
LVShared * getShared ()
LVScope * getReaderScope () const
void printTypeBegin (CVType &Record, TypeIndex TI, LVElement *Element, uint32_t StreamIdx)
void printTypeEnd (CVType &Record)
void printMemberBegin (CVMemberRecord &Record, TypeIndex TI, LVElement *Element, uint32_t StreamIdx)
void printMemberEnd (CVMemberRecord &Record)
void startProcessArgumentList ()
void stopProcessArgumentList ()
void processFiles ()
void processLines ()
void processNamespaces ()
void printRecords (raw_ostream &OS) const
Error visitUnknownType (CVType &Record, TypeIndex TI)
Error visitKnownRecord (CVType &Record, ArgListRecord &Args, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, ArrayRecord &AT, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, BitFieldRecord &BF, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, BuildInfoRecord &BI, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, ClassRecord &Class, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, EnumRecord &Enum, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, FieldListRecord &FieldList, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, FuncIdRecord &Func, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, LabelRecord &LR, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, ModifierRecord &Mod, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, MemberFuncIdRecord &Id, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, MemberFunctionRecord &MF, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, MethodOverloadListRecord &Overloads, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, PointerRecord &Ptr, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, ProcedureRecord &Proc, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, UnionRecord &Union, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, TypeServer2Record &TS, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, VFTableRecord &VFT, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, VFTableShapeRecord &Shape, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, StringListRecord &Strings, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, StringIdRecord &String, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, UdtSourceLineRecord &SourceLine, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, UdtModSourceLineRecord &ModSourceLine, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, PrecompRecord &Precomp, TypeIndex TI, LVElement *Element)
Error visitKnownRecord (CVType &Record, EndPrecompRecord &EndPrecomp, TypeIndex TI, LVElement *Element)
Error visitUnknownMember (CVMemberRecord &Record, TypeIndex TI)
Error visitKnownMember (CVMemberRecord &Record, BaseClassRecord &Base, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, DataMemberRecord &Field, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, EnumeratorRecord &Enum, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, ListContinuationRecord &Cont, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, NestedTypeRecord &Nested, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, OneMethodRecord &Method, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, OverloadedMethodRecord &Method, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, StaticDataMemberRecord &Field, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, VFPtrRecord &VFTable, TypeIndex TI, LVElement *Element)
Error visitKnownMember (CVMemberRecord &Record, VirtualBaseClassRecord &Base, TypeIndex TI, LVElement *Element)
template<typename T>
Error visitKnownMember (CVMemberRecord &Record, TypeVisitorCallbacks &Callbacks, TypeIndex TI, LVElement *Element)
template<typename T>
Error visitKnownRecord (CVType &Record, TypeIndex TI, LVElement *Element)
Error visitMemberRecord (CVMemberRecord &Record, TypeVisitorCallbacks &Callbacks, TypeIndex TI, LVElement *Element)
Error finishVisitation (CVType &Record, TypeIndex TI, LVElement *Element)
Public Attributes
LVElement * CurrentElement = nullptr
LVScope * CurrentScope = nullptr
LVSymbol * CurrentSymbol = nullptr
LVType * CurrentType = nullptr
Detailed Description
Definition at line 232 of file LVCodeViewVisitor.h.
Constructor & Destructor Documentation
LVLogicalVisitor()
LVLogicalVisitor::LVLogicalVisitor (LVCodeViewReader * Reader, ScopedPrinter & W, llvm::pdb::InputFile & Input)
Definition at line 1729 of file LVCodeViewVisitor.cpp.
Member Function Documentation
addElement() [1/3]
void LVLogicalVisitor::addElement (LVScope * Scope, bool IsCompileUnit)
Definition at line 2954 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::IsCompileUnit, popScope(), and pushScope().
Referenced by visitKnownMember(), visitKnownMember(), visitKnownMember(), and visitKnownMember().
addElement() [2/3]
void LVLogicalVisitor::addElement (LVSymbol * Symbol)
Definition at line 2969 of file LVCodeViewVisitor.cpp.
addElement() [3/3]
void LVLogicalVisitor::addElement (LVType * Type)
Definition at line 2973 of file LVCodeViewVisitor.cpp.
addInlineeInfo()
void llvm::logicalview::LVLogicalVisitor::addInlineeInfo (TypeIndex TI, uint32_t LineNumber, StringRef Filename) inline
Definition at line 302 of file LVCodeViewVisitor.h.
References llvm::logicalview::Filename.
closeScope()
void llvm::logicalview::LVLogicalVisitor::closeScope () inline
Definition at line 331 of file LVCodeViewVisitor.h.
References popScope().
createElement() [1/3]
LVElement * LVLogicalVisitor::createElement (SymbolKind Kind)
Definition at line 3062 of file LVCodeViewVisitor.cpp.
References CurrentScope, CurrentSymbol, CurrentType, and llvm::logicalview::Kind.
createElement() [2/3]
LVElement * LVLogicalVisitor::createElement (TypeIndex TI, TypeLeafKind Kind)
Definition at line 3129 of file LVCodeViewVisitor.cpp.
References createElement(), llvm::codeview::TypeIndex::FirstNonSimpleIndex, llvm::pdb::formatTypeLeafKind(), llvm::codeview::TypeIndex::getIndex(), llvm::logicalview::Kind, printTypeIndex(), llvm::logicalview::LVObject::setOffset(), and llvm::pdb::StreamTPI.
createElement() [3/3]
LVElement * LVLogicalVisitor::createElement (TypeLeafKind Kind)
Definition at line 2977 of file LVCodeViewVisitor.cpp.
References CurrentScope, CurrentSymbol, CurrentType, llvm::codeview::TypeIndex::FirstNonSimpleIndex, llvm::logicalview::Kind, and llvm::logicalview::options().
Referenced by createElement(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), and visitKnownMember().
finishVisitation()
Error LVLogicalVisitor::finishVisitation (CVType & Record, TypeIndex TI, LVElement * Element)
Definition at line 2908 of file LVCodeViewVisitor.cpp.
References llvm::Error::success(), and visitUnknownType().
Referenced by getElement(), visitKnownMember(), visitKnownMember(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), and visitKnownRecord().
getCompileUnitName()
std::string llvm::logicalview::LVLogicalVisitor::getCompileUnitName () inline
Definition at line 343 of file LVCodeViewVisitor.h.
getElement()
LVElement * LVLogicalVisitor::getElement (uint32_t StreamIdx, TypeIndex TI, LVScope * Parent = nullptr)
Definition at line 3315 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::consumeError(), finishVisitation(), llvm::codeview::TypeIndex::getIndex(), llvm::codeview::TypeIndex::isNoneType(), llvm::codeview::TypeIndex::isSimple(), LLVM_DEBUG, printTypeIndex(), llvm::codeview::TypeIndex::simpleTypeName(), llvm::pdb::StreamTPI, and llvm::logicalview::Types.
Referenced by visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), and visitKnownRecord().
getReaderScope()
LVScope * llvm::logicalview::LVLogicalVisitor::getReaderScope () const inline
Definition at line 352 of file LVCodeViewVisitor.h.
getShared()
LVShared * llvm::logicalview::LVLogicalVisitor::getShared () inline
Definition at line 350 of file LVCodeViewVisitor.h.
inlineSiteAnnotation()
Error LVLogicalVisitor::inlineSiteAnnotation (LVScope * AbstractFunction, LVScope * InlinedFunction, InlineSiteSym & InlineSite)
Definition at line 3422 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addObject(), llvm::codeview::ChangeCodeLength, llvm::codeview::ChangeCodeLengthAndCodeOffset, llvm::codeview::ChangeCodeOffset, llvm::codeview::ChangeCodeOffsetAndLineOffset, llvm::codeview::ChangeFile, llvm::codeview::ChangeLineOffset, llvm::codeview::CodeOffset, llvm::dbgs(), llvm::logicalview::Filename, llvm::fmt_align(), llvm::formatv(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVObject::getParentScope(), llvm::logicalview::LVScope::getRanges(), llvm::logicalview::hexValue(), llvm::codeview::InlineeLines, llvm::Left, LLVM_DEBUG, llvm::logicalview::Locations, llvm::logicalview::Offset, llvm::logicalview::options(), llvm::logicalview::LVObject::setLineNumber(), llvm::Error::success(), llvm::toHex(), and llvm::utohexstr().
popScope()
void llvm::logicalview::LVLogicalVisitor::popScope () inline
Definition at line 326 of file LVCodeViewVisitor.h.
Referenced by addElement(), and closeScope().
printMemberAttributes() [1/2]
void llvm::logicalview::LVLogicalVisitor::printMemberAttributes (MemberAccess Access, MethodKind Kind, MethodOptions Options)
References Access, llvm::logicalview::Kind, and Options.
printMemberAttributes() [2/2]
void llvm::logicalview::LVLogicalVisitor::printMemberAttributes (MemberAttributes Attrs)
printMemberBegin()
void LVLogicalVisitor::printMemberBegin (CVMemberRecord & Record, TypeIndex TI, LVElement * Element, uint32_t StreamIdx)
Definition at line 1761 of file LVCodeViewVisitor.cpp.
References llvm::pdb::formatTypeLeafKind(), llvm::codeview::TypeIndex::getIndex(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVObject::getOffset(), llvm::logicalview::LeafTypeNames, and printTypeIndex().
Referenced by visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), and visitKnownMember().
printMemberEnd()
void LVLogicalVisitor::printMemberEnd (CVMemberRecord & Record)
Definition at line 1775 of file LVCodeViewVisitor.cpp.
Referenced by visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), and visitKnownMember().
printRecords()
void LVLogicalVisitor::printRecords (raw_ostream & OS) const
Definition at line 3392 of file LVCodeViewVisitor.cpp.
References llvm::Count, llvm::format(), llvm::pdb::formatTypeLeafKind(), llvm::logicalview::LVCodeViewReader::getSymbolKindName(), llvm::logicalview::Kind, llvm::logicalview::Name, and llvm::logicalview::options().
printTypeBegin()
void LVLogicalVisitor::printTypeBegin (CVType & Record, TypeIndex TI, LVElement * Element, uint32_t StreamIdx)
Definition at line 1743 of file LVCodeViewVisitor.cpp.
References llvm::pdb::formatTypeLeafKind(), llvm::codeview::TypeIndex::getIndex(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVObject::getOffset(), llvm::logicalview::LeafTypeNames, and printTypeIndex().
Referenced by visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), and visitKnownRecord().
printTypeEnd()
void LVLogicalVisitor::printTypeEnd (CVType & Record)
Definition at line 1756 of file LVCodeViewVisitor.cpp.
Referenced by visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), and visitKnownRecord().
printTypeIndex()
void LVLogicalVisitor::printTypeIndex (StringRef FieldName, TypeIndex TI, uint32_t StreamIdx)
Definition at line 1737 of file LVCodeViewVisitor.cpp.
References llvm::codeview::printTypeIndex(), and llvm::pdb::StreamTPI.
Referenced by createElement(), getElement(), printMemberBegin(), printTypeBegin(), processLines(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownMember(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), visitKnownRecord(), and visitUnknownType().
processFiles()
void LVLogicalVisitor::processFiles ()
Definition at line 3390 of file LVCodeViewVisitor.cpp.
processLines()
void LVLogicalVisitor::processLines ()
Definition at line 3356 of file LVCodeViewVisitor.cpp.
References llvm::consumeError(), llvm::codeview::TypeDeserializer::deserializeAs(), LLVM_DEBUG, printTypeIndex(), llvm::logicalview::LVElement::setFilenameIndex(), llvm::logicalview::LVObject::setLineNumber(), llvm::pdb::StreamIPI, and llvm::pdb::StreamTPI.
processNamespaces()
void LVLogicalVisitor::processNamespaces ()
Definition at line 3385 of file LVCodeViewVisitor.cpp.
pushScope()
void llvm::logicalview::LVLogicalVisitor::pushScope (LVScope * Scope) inline
Definition at line 321 of file LVCodeViewVisitor.h.
Referenced by addElement().
setCompileUnitName()
void llvm::logicalview::LVLogicalVisitor::setCompileUnitName (std::string Name) inline
Definition at line 344 of file LVCodeViewVisitor.h.
References llvm::logicalview::Name.
setInput() [1/2]
void llvm::logicalview::LVLogicalVisitor::setInput (std::shared_ptr< LazyRandomTypeCollection > PrecompHeader) inline
Definition at line 298 of file LVCodeViewVisitor.h.
setInput() [2/2]
void llvm::logicalview::LVLogicalVisitor::setInput (std::shared_ptr< llvm::pdb::InputFile > TypeServer) inline
Definition at line 295 of file LVCodeViewVisitor.h.
setRoot()
void llvm::logicalview::LVLogicalVisitor::setRoot (LVScope * Root) inline
Definition at line 337 of file LVCodeViewVisitor.h.
startProcessArgumentList()
void llvm::logicalview::LVLogicalVisitor::startProcessArgumentList () inline
Definition at line 361 of file LVCodeViewVisitor.h.
stopProcessArgumentList()
void llvm::logicalview::LVLogicalVisitor::stopProcessArgumentList () inline
Definition at line 362 of file LVCodeViewVisitor.h.
visitKnownMember() [1/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, BaseClassRecord & Base, TypeIndex TI, LVElement * Element)
Definition at line 2633 of file LVCodeViewVisitor.cpp.
References addElement(), llvm::logicalview::Base, llvm::pdb::BaseClass, createElement(), CurrentSymbol, getElement(), LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
Referenced by visitKnownMember(), and visitKnownRecord().
visitKnownMember() [2/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, DataMemberRecord & Field, TypeIndex TI, LVElement * Element)
Definition at line 2656 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownMember() [3/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, EnumeratorRecord & Enum, TypeIndex TI, LVElement * Element)
Definition at line 2674 of file LVCodeViewVisitor.cpp.
References addElement(), createElement(), CurrentType, llvm::pdb::Enum, LLVM_DEBUG, printMemberBegin(), printMemberEnd(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownMember() [4/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, ListContinuationRecord & Cont, TypeIndex TI, LVElement * Element)
Definition at line 2697 of file LVCodeViewVisitor.cpp.
References llvm::codeview::ListContinuationRecord::getContinuationIndex(), LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownMember() [5/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, NestedTypeRecord & Nested, TypeIndex TI, LVElement * Element)
Definition at line 2709 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), createElement(), getElement(), llvm::logicalview::getInnerComponent(), llvm::logicalview::LVElement::getName(), llvm::logicalview::getRecordName(), LLVM_DEBUG, llvm::codeview::Nested, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::StringRef::size(), llvm::pdb::StreamTPI, llvm::Error::success(), llvm::pdb::Typedef, and llvm::logicalview::LVElement::updateLevel().
visitKnownMember() [6/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, OneMethodRecord & Method, TypeIndex TI, LVElement * Element)
Definition at line 2754 of file LVCodeViewVisitor.cpp.
References addElement(), llvm::codeview::OneMethodRecord::Attrs, llvm::codeview::CompilerGenerated, createElement(), finishVisitation(), llvm::codeview::OneMethodRecord::getAccess(), llvm::codeview::MemberAttributes::getFlags(), llvm::codeview::OneMethodRecord::getMethodKind(), llvm::codeview::OneMethodRecord::getName(), llvm::codeview::OneMethodRecord::getType(), llvm::codeview::OneMethodRecord::getVFTableOffset(), llvm::codeview::OneMethodRecord::isIntroducingVirtual(), llvm::logicalview::Kind, LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::logicalview::LVElement::setName(), llvm::codeview::Static, llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownMember() [7/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, OverloadedMethodRecord & Method, TypeIndex TI, LVElement * Element)
Definition at line 2800 of file LVCodeViewVisitor.cpp.
References finishVisitation(), llvm::codeview::OverloadedMethodRecord::getMethodList(), llvm::codeview::OverloadedMethodRecord::getName(), llvm::codeview::OverloadedMethodRecord::getNumOverloads(), LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownMember() [8/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, StaticDataMemberRecord & Field, TypeIndex TI, LVElement * Element)
Definition at line 2823 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownMember() [9/11]
template<typename T> Error llvm::logicalview::LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, TypeVisitorCallbacks & Callbacks, TypeIndex TI, LVElement * Element) inline
Definition at line 445 of file LVCodeViewVisitor.h.
References llvm::Error::success(), T, and visitKnownMember().
visitKnownMember() [10/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, VFPtrRecord & VFTable, TypeIndex TI, LVElement * Element)
Definition at line 2840 of file LVCodeViewVisitor.cpp.
References llvm::codeview::VFPtrRecord::getType(), LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownMember() [11/11]
Error LVLogicalVisitor::visitKnownMember (CVMemberRecord & Record, VirtualBaseClassRecord & Base, TypeIndex TI, LVElement * Element)
Definition at line 2852 of file LVCodeViewVisitor.cpp.
References addElement(), llvm::logicalview::Base, llvm::pdb::BaseClass, createElement(), CurrentSymbol, getElement(), LLVM_DEBUG, printMemberBegin(), printMemberEnd(), printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::codeview::Virtual.
visitKnownRecord() [1/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, ArgListRecord & Args, TypeIndex TI, LVElement * Element)
Definition at line 1789 of file LVCodeViewVisitor.cpp.
References Arguments, llvm::codeview::Function, I, LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::logicalview::Size, llvm::ArrayRef< T >::size(), llvm::pdb::StreamTPI, and llvm::Error::success().
Referenced by visitKnownRecord().
visitKnownRecord() [2/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, ArrayRecord & AT, TypeIndex TI, LVElement * Element)
Definition at line 1812 of file LVCodeViewVisitor.cpp.
References llvm::consumeError(), llvm::Count, llvm::codeview::TypeDeserializer::deserializeAs(), finishVisitation(), llvm::logicalview::LVElement::getCount(), getElement(), llvm::codeview::ArrayRecord::getElementType(), llvm::codeview::TypeIndex::getIndex(), llvm::codeview::ArrayRecord::getIndexType(), llvm::codeview::getModifiedType(), llvm::codeview::ArrayRecord::getName(), llvm::codeview::TypeIndex::getSimpleKind(), llvm::codeview::ArrayRecord::getSize(), llvm::codeview::getSizeInBytesForTypeIndex(), llvm::codeview::getSizeInBytesForTypeRecord(), llvm::logicalview::getTrueType(), llvm::codeview::isAggregate(), llvm::codeview::TypeIndex::isSimple(), llvm::codeview::CVRecord< Kind >::kind(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::logicalview::LVElement::setCount(), llvm::Record::setName(), llvm::logicalview::Size, llvm::pdb::StreamTPI, llvm::logicalview::Subrange, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownRecord() [3/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, BitFieldRecord & BF, TypeIndex TI, LVElement * Element)
Definition at line 1930 of file LVCodeViewVisitor.cpp.
References llvm::codeview::BitFieldRecord::getBitOffset(), llvm::codeview::BitFieldRecord::getBitSize(), getElement(), llvm::codeview::BitFieldRecord::getType(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::logicalview::LVElement::setBitSize(), llvm::logicalview::LVElement::setType(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [4/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, BuildInfoRecord & BI, TypeIndex TI, LVElement * Element)
Definition at line 1946 of file LVCodeViewVisitor.cpp.
References Arguments, llvm::codeview::BuildInfoRecord::getArgs(), llvm::getTypeName(), LLVM_DEBUG, llvm::logicalview::Name, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::logicalview::LVElement::setName(), llvm::codeview::BuildInfoRecord::SourceFile, llvm::pdb::StreamIPI, and llvm::Error::success().
visitKnownRecord() [5/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, ClassRecord & Class, TypeIndex TI, LVElement * Element)
Definition at line 1970 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::pdb::Class, llvm::codeview::TypeDeserializer::deserializeAs(), llvm::logicalview::DWARF_CHAR_BIT, finishVisitation(), llvm::codeview::TagRecord::getFieldList(), llvm::codeview::TypeIndex::isNoneType(), llvm::codeview::CVRecord< Kind >::kind(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownRecord() [6/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, EndPrecompRecord & EndPrecomp, TypeIndex TI, LVElement * Element)
Definition at line 2615 of file LVCodeViewVisitor.cpp.
References llvm::codeview::EndPrecompRecord::getSignature(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [7/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, EnumRecord & Enum, TypeIndex TI, LVElement * Element)
Definition at line 2041 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::pdb::Enum, finishVisitation(), getElement(), llvm::codeview::TypeIndex::isNoneType(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownRecord() [8/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, FieldListRecord & FieldList, TypeIndex TI, LVElement * Element)
Definition at line 2098 of file LVCodeViewVisitor.cpp.
References llvm::codeview::FieldList, LLVM_DEBUG, printTypeBegin(), printTypeEnd(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [9/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, FuncIdRecord & Func, TypeIndex TI, LVElement * Element)
Definition at line 2113 of file LVCodeViewVisitor.cpp.
References finishVisitation(), llvm::codeview::TypeIndex::isNoneType(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamIPI, llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownRecord() [10/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, LabelRecord & LR, TypeIndex TI, LVElement * Element)
Definition at line 2158 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, printTypeBegin(), printTypeEnd(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [11/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, MemberFuncIdRecord & Id, TypeIndex TI, LVElement * Element)
Definition at line 2168 of file LVCodeViewVisitor.cpp.
References llvm::pdb::Class, finishVisitation(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamIPI, llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [12/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, MemberFunctionRecord & MF, TypeIndex TI, LVElement * Element)
Definition at line 2199 of file LVCodeViewVisitor.cpp.
References llvm::pdb::Class, finishVisitation(), llvm::codeview::MemberFunctionRecord::getArgumentList(), llvm::codeview::MemberFunctionRecord::getClassType(), getElement(), llvm::codeview::TypeIndex::getIndex(), llvm::codeview::MemberFunctionRecord::getParameterCount(), llvm::codeview::MemberFunctionRecord::getReturnType(), llvm::codeview::MemberFunctionRecord::getThisPointerAdjustment(), llvm::codeview::MemberFunctionRecord::getThisType(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::logicalview::LVElement::setType(), llvm::pdb::StreamTPI, llvm::Error::success(), llvm::codeview::This, and llvm::logicalview::Types.
visitKnownRecord() [13/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, MethodOverloadListRecord & Overloads, TypeIndex TI, LVElement * Element)
Definition at line 2246 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::codeview::MethodOverloadListRecord::Methods, llvm::codeview::OneMethodRecord::Name, printTypeBegin(), printTypeEnd(), llvm::pdb::StreamTPI, llvm::Error::success(), and visitKnownMember().
visitKnownRecord() [14/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, ModifierRecord & Mod, TypeIndex TI, LVElement * Element)
Definition at line 2266 of file LVCodeViewVisitor.cpp.
References llvm::codeview::Const, llvm::dwarf::DW_TAG_unaligned, getElement(), llvm::logicalview::LVObject::getParentScope(), LLVM_DEBUG, llvm::Mod, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::logicalview::LVElement::setName(), llvm::logicalview::LVObject::setTag(), llvm::logicalview::LVElement::setType(), llvm::pdb::StreamTPI, llvm::Error::success(), llvm::codeview::Unaligned, and llvm::codeview::Volatile.
visitKnownRecord() [15/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, PointerRecord & Ptr, TypeIndex TI, LVElement * Element)
Definition at line 2327 of file LVCodeViewVisitor.cpp.
References getElement(), llvm::logicalview::LVObject::getParentScope(), LLVM_DEBUG, llvm::codeview::LValueReference, MI, llvm::codeview::Pointer, printTypeBegin(), printTypeEnd(), printTypeIndex(), Ptr, llvm::codeview::Restrict, llvm::codeview::RValueReference, llvm::logicalview::LVElement::setName(), llvm::logicalview::LVObject::setTag(), llvm::logicalview::LVElement::setType(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [16/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, PrecompRecord & Precomp, TypeIndex TI, LVElement * Element)
Definition at line 2601 of file LVCodeViewVisitor.cpp.
References llvm::codeview::PrecompRecord::getPrecompFilePath(), llvm::codeview::PrecompRecord::getSignature(), llvm::codeview::PrecompRecord::getStartTypeIndex(), llvm::codeview::PrecompRecord::getTypesCount(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [17/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, ProcedureRecord & Proc, TypeIndex TI, LVElement * Element)
Definition at line 2410 of file LVCodeViewVisitor.cpp.
References finishVisitation(), llvm::codeview::ProcedureRecord::getArgumentList(), getElement(), llvm::codeview::ProcedureRecord::getParameterCount(), llvm::codeview::ProcedureRecord::getReturnType(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownRecord() [18/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, StringIdRecord & String, TypeIndex TI, LVElement * Element)
Definition at line 2548 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVObject::getParentScope(), LLVM_DEBUG, printTypeIndex(), llvm::pdb::StreamIPI, llvm::String, and llvm::Error::success().
visitKnownRecord() [19/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, StringListRecord & Strings, TypeIndex TI, LVElement * Element)
Definition at line 2530 of file LVCodeViewVisitor.cpp.
References Arguments, llvm::codeview::StringListRecord::getIndices(), I, LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::logicalview::Size, llvm::ArrayRef< T >::size(), llvm::pdb::StreamIPI, and llvm::Error::success().
visitKnownRecord() [20/26]
template<typename T> Error llvm::logicalview::LVLogicalVisitor::visitKnownRecord (CVType & Record, TypeIndex TI, LVElement * Element) inline
Definition at line 458 of file LVCodeViewVisitor.h.
References llvm::codeview::TypeDeserializer::deserializeAs(), llvm::Error::success(), T, and visitKnownRecord().
visitKnownRecord() [21/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, TypeServer2Record & TS, TypeIndex TI, LVElement * Element)
Definition at line 2489 of file LVCodeViewVisitor.cpp.
References llvm::formatv(), llvm::codeview::TypeServer2Record::getAge(), llvm::codeview::TypeServer2Record::getGuid(), llvm::codeview::TypeServer2Record::getName(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [22/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, UdtModSourceLineRecord & ModSourceLine, TypeIndex TI, LVElement * Element)
Definition at line 2584 of file LVCodeViewVisitor.cpp.
References llvm::codeview::UdtModSourceLineRecord::getLineNumber(), llvm::codeview::UdtModSourceLineRecord::getModule(), llvm::codeview::UdtModSourceLineRecord::getSourceFile(), llvm::codeview::UdtModSourceLineRecord::getUDT(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamIPI, and llvm::Error::success().
visitKnownRecord() [23/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, UdtSourceLineRecord & SourceLine, TypeIndex TI, LVElement * Element)
Definition at line 2570 of file LVCodeViewVisitor.cpp.
References llvm::codeview::UdtSourceLineRecord::getLineNumber(), llvm::codeview::UdtSourceLineRecord::getSourceFile(), llvm::codeview::UdtSourceLineRecord::getUDT(), LLVM_DEBUG, printTypeIndex(), llvm::pdb::StreamIPI, and llvm::Error::success().
visitKnownRecord() [24/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, UnionRecord & Union, TypeIndex TI, LVElement * Element)
Definition at line 2441 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::logicalview::DWARF_CHAR_BIT, finishVisitation(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), llvm::logicalview::Types, and llvm::pdb::Union.
visitKnownRecord() [25/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, VFTableRecord & VFT, TypeIndex TI, LVElement * Element)
Definition at line 2502 of file LVCodeViewVisitor.cpp.
References llvm::codeview::VFTableRecord::getCompleteClass(), llvm::codeview::VFTableRecord::getMethodNames(), llvm::codeview::VFTableRecord::getName(), llvm::codeview::VFTableRecord::getOverriddenVTable(), llvm::codeview::VFTableRecord::getVFPtrOffset(), LLVM_DEBUG, N, printTypeBegin(), printTypeEnd(), printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [26/26]
Error LVLogicalVisitor::visitKnownRecord (CVType & Record, VFTableShapeRecord & Shape, TypeIndex TI, LVElement * Element)
Definition at line 2518 of file LVCodeViewVisitor.cpp.
References llvm::codeview::VFTableShapeRecord::getEntryCount(), LLVM_DEBUG, printTypeBegin(), printTypeEnd(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitMemberRecord()
Error LVLogicalVisitor::visitMemberRecord (CVMemberRecord & Record, TypeVisitorCallbacks & Callbacks, TypeIndex TI, LVElement * Element)
Definition at line 2877 of file LVCodeViewVisitor.cpp.
References llvm::Error::success(), llvm::codeview::TypeVisitorCallbacks::visitMemberBegin(), llvm::codeview::TypeVisitorCallbacks::visitMemberEnd(), and llvm::codeview::TypeVisitorCallbacks::visitUnknownMember().
visitUnknownMember()
Error LVLogicalVisitor::visitUnknownMember (CVMemberRecord & Record, TypeIndex TI)
Definition at line 2626 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, and llvm::Error::success().
visitUnknownType()
Error LVLogicalVisitor::visitUnknownType (CVType & Record, TypeIndex TI)
Definition at line 1780 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
Referenced by finishVisitation().
Member Data Documentation
CurrentElement
LVElement* llvm::logicalview::LVLogicalVisitor::CurrentElement = nullptr
Definition at line 289 of file LVCodeViewVisitor.h.
CurrentScope
LVScope* llvm::logicalview::LVLogicalVisitor::CurrentScope = nullptr
Definition at line 290 of file LVCodeViewVisitor.h.
Referenced by createElement(), and createElement().
CurrentSymbol
LVSymbol* llvm::logicalview::LVLogicalVisitor::CurrentSymbol = nullptr
Definition at line 291 of file LVCodeViewVisitor.h.
Referenced by createElement(), createElement(), visitKnownMember(), and visitKnownMember().
CurrentType
LVType* llvm::logicalview::LVLogicalVisitor::CurrentType = nullptr
Definition at line 292 of file LVCodeViewVisitor.h.
Referenced by createElement(), createElement(), and visitKnownMember().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h
lib/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.cpp