LLVM: llvm::object::RelocationRef Class Reference
llvm::object::RelocationRef Class Reference
This is a value type class that represents a single relocation in the list of relocations in the object file.
#include "llvm/Object/ObjectFile.h"
Public Member Functions
RelocationRef ()=default
RelocationRef (DataRefImpl RelocationP, const ObjectFile *Owner)
RelocationRef.
bool operator== (const RelocationRef &Other) const
void moveNext ()
uint64_t getOffset () const
symbol_iterator getSymbol () const
uint64_t getType () const
void getTypeName (SmallVectorImpl< char > &Result) const
Get a string that represents the type of this relocation.
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObject () const
Detailed Description
This is a value type class that represents a single relocation in the list of relocations in the object file.
Definition at line 53 of file ObjectFile.h.
Constructor & Destructor Documentation
RelocationRef() [1/2]
llvm::object::RelocationRef::RelocationRef () default
References llvm::Other, and RelocationRef().
Referenced by llvm::object::ELFRelocationRef::ELFRelocationRef(), operator==(), and RelocationRef().
RelocationRef() [2/2]
llvm::object::RelocationRef::RelocationRef (DataRefImpl RelocationP, const ObjectFile * Owner) inline
RelocationRef.
Definition at line 608 of file ObjectFile.h.
Member Function Documentation
getObject()
const ObjectFile * llvm::object::RelocationRef::getObject () const inline
Definition at line 641 of file ObjectFile.h.
Referenced by llvm::object::ELFRelocationRef::ELFRelocationRef(), llvm::object::ELFRelocationRef::getObject(), and llvm::RuntimeDyldMachO::makeValueAddendPCRel().
getOffset()
uint64_t llvm::object::RelocationRef::getOffset () const inline
Definition at line 621 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), llvm::RuntimeDyldMachO::makeValueAddendPCRel(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
getRawDataRefImpl()
DataRefImpl llvm::object::RelocationRef::getRawDataRefImpl () const inline
Definition at line 637 of file ObjectFile.h.
Referenced by llvm::object::ELFRelocationRef::getAddend(), llvm::RuntimeDyldMachO::getRelocationEntry(), llvm::jitlink::MachOLinkGraphBuilder::getRelocationInfo(), llvm::object::MachOObjectFile::getRelocationRelocatedSection(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachO::processScatteredVANILLA(), and llvm::object::ELFObjectFile< ELFT >::section_rel_end().
getSymbol()
symbol_iterator llvm::object::RelocationRef::getSymbol () const inline
Definition at line 625 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldMachOARM::processRelocationRef().
getType()
uint64_t llvm::object::RelocationRef::getType () const inline
Definition at line 629 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), and llvm::RuntimeDyldELF::processRelocationRef().
getTypeName()
void llvm::object::RelocationRef::getTypeName (SmallVectorImpl< char > & Result) const inline
Get a string that represents the type of this relocation.
This is for display purposes only.
Definition at line 633 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), and llvm::RuntimeDyldCOFFThumb::processRelocationRef().
moveNext()
void llvm::object::RelocationRef::moveNext () inline
Definition at line 617 of file ObjectFile.h.
operator==()
bool llvm::object::RelocationRef::operator== (const RelocationRef & Other) const inline
Definition at line 613 of file ObjectFile.h.
References llvm::Other, and RelocationRef().
The documentation for this class was generated from the following file:
include/llvm/Object/ObjectFile.h