LLVM: llvm::mca::MCAOperand Class Reference
llvm::mca::MCAOperand Class Reference
A representation of an mca::Instruction operand for use in mca::CustomBehaviour.
#include "llvm/MCA/Instruction.h"
Public Member Functions
MCAOperand ()
bool isValid () const
bool isReg () const
bool isImm () const
bool isSFPImm () const
bool isDFPImm () const
unsigned getReg () const
Returns the register number.
int64_t getImm () const
uint32_t getSFPImm () const
uint64_t getDFPImm () const
void setIndex (const unsigned Idx)
unsigned getIndex () const
Static Public Member Functions
static MCAOperand createReg (unsigned Reg)
static MCAOperand createImm (int64_t Val)
static MCAOperand createSFPImm (uint32_t Val)
static MCAOperand createDFPImm (uint64_t Val)
static MCAOperand createInvalid ()
Detailed Description
A representation of an mca::Instruction operand for use in mca::CustomBehaviour.
Definition at line 39 of file Instruction.h.
Constructor & Destructor Documentation
MCAOperand()
llvm::mca::MCAOperand::MCAOperand () inline
Definition at line 66 of file Instruction.h.
References FPImmVal.
Referenced by createDFPImm(), createImm(), createInvalid(), createReg(), and createSFPImm().
Member Function Documentation
createDFPImm()
MCAOperand llvm::mca::MCAOperand::createDFPImm (uint64_t Val) inline static
Definition at line 120 of file Instruction.h.
References MCAOperand().
createImm()
MCAOperand llvm::mca::MCAOperand::createImm (int64_t Val) inline static
Definition at line 106 of file Instruction.h.
References MCAOperand().
createInvalid()
MCAOperand llvm::mca::MCAOperand::createInvalid () inline static
Definition at line 127 of file Instruction.h.
References MCAOperand().
createReg()
MCAOperand llvm::mca::MCAOperand::createReg (unsigned Reg) inline static
Definition at line 99 of file Instruction.h.
References MCAOperand(), and Reg.
createSFPImm()
MCAOperand llvm::mca::MCAOperand::createSFPImm (uint32_t Val) inline static
Definition at line 113 of file Instruction.h.
References MCAOperand().
getDFPImm()
uint64_t llvm::mca::MCAOperand::getDFPImm () const inline
Definition at line 90 of file Instruction.h.
References assert(), FPImmVal, and isDFPImm().
getImm()
int64_t llvm::mca::MCAOperand::getImm () const inline
Definition at line 80 of file Instruction.h.
References assert(), ImmVal, and isImm().
getIndex()
unsigned llvm::mca::MCAOperand::getIndex () const inline
Definition at line 97 of file Instruction.h.
getReg()
unsigned llvm::mca::MCAOperand::getReg () const inline
Returns the register number.
Definition at line 75 of file Instruction.h.
References assert(), isReg(), and RegVal.
getSFPImm()
uint32_t llvm::mca::MCAOperand::getSFPImm () const inline
Definition at line 85 of file Instruction.h.
References assert(), isSFPImm(), and SFPImmVal.
isDFPImm()
bool llvm::mca::MCAOperand::isDFPImm () const inline
Definition at line 72 of file Instruction.h.
Referenced by getDFPImm().
isImm()
bool llvm::mca::MCAOperand::isImm () const inline
Definition at line 70 of file Instruction.h.
Referenced by getImm().
isReg()
bool llvm::mca::MCAOperand::isReg () const inline
Definition at line 69 of file Instruction.h.
Referenced by getReg().
isSFPImm()
bool llvm::mca::MCAOperand::isSFPImm () const inline
Definition at line 71 of file Instruction.h.
Referenced by getSFPImm().
isValid()
bool llvm::mca::MCAOperand::isValid () const inline
Definition at line 68 of file Instruction.h.
setIndex()
void llvm::mca::MCAOperand::setIndex (const unsigned Idx) inline
Definition at line 95 of file Instruction.h.
Member Data Documentation
FPImmVal
uint64_t llvm::mca::MCAOperand::FPImmVal
Definition at line 56 of file Instruction.h.
Referenced by getDFPImm(), and MCAOperand().
ImmVal
int64_t llvm::mca::MCAOperand::ImmVal
Definition at line 54 of file Instruction.h.
Referenced by getImm().
RegVal
unsigned llvm::mca::MCAOperand::RegVal
Definition at line 53 of file Instruction.h.
Referenced by getReg().
SFPImmVal
uint32_t llvm::mca::MCAOperand::SFPImmVal
Definition at line 55 of file Instruction.h.
Referenced by getSFPImm().
The documentation for this class was generated from the following file:
include/llvm/MCA/Instruction.h