LLVM: llvm::ELFCompactAttrParser Class Reference
llvm::ELFCompactAttrParser Class Reference abstract
#include "llvm/Support/ELFAttrParserCompact.h"
Public Member Functions
virtual ~ELFCompactAttrParser ()
Error integerAttribute (unsigned tag)
Error stringAttribute (unsigned tag)
ELFCompactAttrParser (ScopedPrinter *sw, TagNameMap tagNameMap, StringRef vendor)
ELFCompactAttrParser (TagNameMap tagNameMap, StringRef vendor)
Error parse (ArrayRef< uint8_t > section, llvm::endianness endian) override
std::optional< unsigned > getAttributeValue (unsigned tag) const override
std::optional< unsigned > getAttributeValue (StringRef buildAttributeSubsectionName, unsigned tag) const override
std::optional< StringRef > getAttributeString (unsigned tag) const override
std::optional< StringRef > getAttributeString (StringRef buildAttributeSubsectionName, unsigned tag) const override
Public Member Functions inherited from llvm::ELFAttributeParser
virtual ~ELFAttributeParser ()
Protected Member Functions
void printAttribute (unsigned tag, unsigned value, StringRef valueDesc)
Error parseStringAttribute (const char *name, unsigned tag, ArrayRef< const char * > strings)
Error parseAttributeList (uint32_t length)
void parseIndexList (SmallVectorImpl< uint8_t > &indexList)
Error parseSubsection (uint32_t length)
void setAttributeString (unsigned tag, StringRef value)
Protected Attributes
ScopedPrinter * sw
TagNameMap tagToStringMap
DataExtractor de {ArrayRef<uint8_t>{}, true, 0}
DataExtractor::Cursor cursor {0}
Detailed Description
Definition at line 26 of file ELFAttrParserCompact.h.
Constructor & Destructor Documentation
~ELFCompactAttrParser()
virtual llvm::ELFCompactAttrParser::~ELFCompactAttrParser () inline virtual
Definition at line 52 of file ELFAttrParserCompact.h.
References cursor.
ELFCompactAttrParser() [1/2]
llvm::ELFCompactAttrParser::ELFCompactAttrParser (ScopedPrinter * sw, TagNameMap tagNameMap, StringRef vendor) inline
Definition at line 56 of file ELFAttrParserCompact.h.
References sw, and tagToStringMap.
Referenced by llvm::ARMAttributeParser::ARMAttributeParser(), llvm::ARMAttributeParser::ARMAttributeParser(), llvm::CSKYAttributeParser::CSKYAttributeParser(), llvm::CSKYAttributeParser::CSKYAttributeParser(), llvm::HexagonAttributeParser::HexagonAttributeParser(), llvm::HexagonAttributeParser::HexagonAttributeParser(), llvm::MSP430AttributeParser::MSP430AttributeParser(), llvm::MSP430AttributeParser::MSP430AttributeParser(), llvm::RISCVAttributeParser::RISCVAttributeParser(), and llvm::RISCVAttributeParser::RISCVAttributeParser().
ELFCompactAttrParser() [2/2]
llvm::ELFCompactAttrParser::ELFCompactAttrParser (TagNameMap tagNameMap, StringRef vendor) inline
Definition at line 59 of file ELFAttrParserCompact.h.
References sw, and tagToStringMap.
Member Function Documentation
getAttributeString() [1/2]
std::optional< StringRef > llvm::ELFCompactAttrParser::getAttributeString (StringRef buildAttributeSubsectionName, unsigned tag) const inline override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 84 of file ELFAttrParserCompact.h.
References assert(), and getAttributeString().
getAttributeString() [2/2]
std::optional< StringRef > llvm::ELFCompactAttrParser::getAttributeString (unsigned tag) const inline override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 77 of file ELFAttrParserCompact.h.
References I.
Referenced by getAttributeString().
getAttributeValue() [1/2]
std::optional< unsigned > llvm::ELFCompactAttrParser::getAttributeValue (StringRef buildAttributeSubsectionName, unsigned tag) const inline override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 71 of file ELFAttrParserCompact.h.
References assert(), and getAttributeValue().
getAttributeValue() [2/2]
std::optional< unsigned > llvm::ELFCompactAttrParser::getAttributeValue (unsigned tag) const inline override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 64 of file ELFAttrParserCompact.h.
References I.
Referenced by getAttributeValue().
integerAttribute()
Error ELFCompactAttrParser::integerAttribute (unsigned tag)
Definition at line 39 of file ELFAttrParserCompact.cpp.
References llvm::ELFAttrs::attrTypeAsString(), cursor, de, llvm::StringRef::empty(), llvm::Error::success(), sw, and tagToStringMap.
Referenced by parseAttributeList().
parse()
Error ELFCompactAttrParser::parse (ArrayRef< uint8_t > section, llvm::endianness endian) override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 194 of file ELFAttrParserCompact.cpp.
References llvm::consumeError(), llvm::createStringError(), cursor, de, llvm::ELFAttrs::Format_Version, llvm::invalid_argument, llvm::little, parseSubsection(), llvm::ArrayRef< T >::size(), sw, and llvm::utohexstr().
parseAttributeList()
Error ELFCompactAttrParser::parseAttributeList (uint32_t length) protected
Definition at line 97 of file ELFAttrParserCompact.cpp.
References llvm::createStringError(), cursor, de, integerAttribute(), llvm::invalid_argument, stringAttribute(), llvm::Error::success(), and llvm::Twine::utohexstr().
Referenced by parseSubsection().
parseIndexList()
void ELFCompactAttrParser::parseIndexList (SmallVectorImpl< uint8_t > & indexList) protected
Definition at line 88 of file ELFAttrParserCompact.cpp.
References cursor, de, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by parseSubsection().
parseStringAttribute()
Error ELFCompactAttrParser::parseStringAttribute (const char * name, unsigned tag, ArrayRef< const char * > strings) protected
Definition at line 26 of file ELFAttrParserCompact.cpp.
References llvm::createStringError(), cursor, de, llvm::invalid_argument, name, printAttribute(), llvm::ArrayRef< T >::size(), and llvm::Error::success().
parseSubsection()
Error ELFCompactAttrParser::parseSubsection (uint32_t length) protected
Tag_File | Tag_Section | Tag_Symbol uleb128:byte-size
Definition at line 125 of file ELFAttrParserCompact.cpp.
References llvm::ArrayRef(), llvm::createStringError(), cursor, de, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::ELFAttrs::File, llvm::invalid_argument, llvm::StringRef::lower(), parseAttributeList(), parseIndexList(), llvm::ELFAttrs::Section, llvm::size(), llvm::Error::success(), sw, llvm::ELFAttrs::Symbol, tagNames, and llvm::Twine::utohexstr().
Referenced by parse().
printAttribute()
void ELFCompactAttrParser::printAttribute (unsigned tag, unsigned value, StringRef valueDesc) protected
Definition at line 71 of file ELFAttrParserCompact.cpp.
References llvm::ELFAttrs::attrTypeAsString(), llvm::StringRef::empty(), sw, and tagToStringMap.
Referenced by parseStringAttribute().
setAttributeString()
void llvm::ELFCompactAttrParser::setAttributeString (unsigned tag, StringRef value) inline protected
Definition at line 47 of file ELFAttrParserCompact.h.
Referenced by stringAttribute().
stringAttribute()
Error ELFCompactAttrParser::stringAttribute (unsigned tag)
Definition at line 55 of file ELFAttrParserCompact.cpp.
References llvm::ELFAttrs::attrTypeAsString(), cursor, de, llvm::StringRef::empty(), setAttributeString(), llvm::Error::success(), sw, and tagToStringMap.
Referenced by parseAttributeList().
Member Data Documentation
cursor
DataExtractor::Cursor llvm::ELFCompactAttrParser::cursor {0} protected
Definition at line 37 of file ELFAttrParserCompact.h.
Referenced by integerAttribute(), parse(), parseAttributeList(), parseIndexList(), parseStringAttribute(), parseSubsection(), stringAttribute(), and ~ELFCompactAttrParser().
de
DataExtractor llvm::ELFCompactAttrParser::de {ArrayRef<uint8_t>{}, true, 0} protected
Definition at line 36 of file ELFAttrParserCompact.h.
Referenced by integerAttribute(), parse(), parseAttributeList(), parseIndexList(), parseStringAttribute(), parseSubsection(), and stringAttribute().
sw
ScopedPrinter* llvm::ELFCompactAttrParser::sw protected
Definition at line 34 of file ELFAttrParserCompact.h.
Referenced by llvm::ARMAttributeParser::ARMAttributeParser(), llvm::CSKYAttributeParser::CSKYAttributeParser(), ELFCompactAttrParser(), ELFCompactAttrParser(), integerAttribute(), parse(), parseSubsection(), printAttribute(), llvm::RISCVAttributeParser::RISCVAttributeParser(), and stringAttribute().
tagToStringMap
TagNameMap llvm::ELFCompactAttrParser::tagToStringMap protected
Definition at line 35 of file ELFAttrParserCompact.h.
Referenced by ELFCompactAttrParser(), ELFCompactAttrParser(), integerAttribute(), printAttribute(), and stringAttribute().
The documentation for this class was generated from the following files:
include/llvm/Support/ELFAttrParserCompact.h
lib/Support/ELFAttrParserCompact.cpp