LLVM: llvm::ShrinkWrapPass Class Reference
llvm::ShrinkWrapPass Class Reference
#include "llvm/CodeGen/ShrinkWrap.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
MachineFunctionProperties getRequiredProperties () const
Public Member Functions inherited from llvm::PassInfoMixin< ShrinkWrapPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ShrinkWrapPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file ShrinkWrap.h.
Member Function Documentation
getRequiredProperties()
MachineFunctionProperties llvm::ShrinkWrapPass::getRequiredProperties () const inline
Definition at line 21 of file ShrinkWrap.h.
run()
PreservedAnalyses ShrinkWrapPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 994 of file ShrinkWrap.cpp.
References _, llvm::PreservedAnalyses::all(), llvm::MachineFunction::empty(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::MachineOptimizationRemarkEmitterAnalysis::run().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ShrinkWrap.h
lib/CodeGen/ShrinkWrap.cpp