LLVM: llvm::MCAlignFragment Class Reference
llvm::MCAlignFragment Class Reference
#include "llvm/MC/MCSection.h"
Public Member Functions
MCAlignFragment (Align Alignment, int64_t Fill, uint8_t FillLen, unsigned MaxBytesToEmit)
Align getAlignment () const
int64_t getFill () const
uint8_t getFillLen () const
unsigned getMaxBytesToEmit () const
bool hasEmitNops () const
void setEmitNops (bool Value, const MCSubtargetInfo *STI)
const MCSubtargetInfo * getSubtargetInfo () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
MCFragment * getNext () const
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
LLVM_ABI const MCSymbol * getAtom () const
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it?
bool isLinkerRelaxable () const
void setLinkerRelaxable ()
LLVM_ABI void dump () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Data , FT_Relaxable , FT_Align , FT_Fill ,
FT_LEB , FT_Nops , FT_Org , FT_Dwarf ,
FT_DwarfFrame , FT_BoundaryAlign , FT_SymbolId , FT_CVInlineLines ,
FT_CVDefRange , FT_PseudoProbe
}
Protected Member Functions inherited from llvm::MCFragment
LLVM_ABI MCFragment (FragmentType Kind, bool HasInstructions)
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions: 1
Used by subclasses for better packing.
bool AlignToBundleEnd: 1
bool LinkerRelaxable: 1
MCDataFragment.
bool AllowAutoPadding: 1
MCRelaxableFragment: x86-specific.
Detailed Description
Definition at line 471 of file MCSection.h.
Constructor & Destructor Documentation
MCAlignFragment()
llvm::MCAlignFragment::MCAlignFragment (Align Alignment, int64_t Fill, uint8_t FillLen, unsigned MaxBytesToEmit) inline
Definition at line 494 of file MCSection.h.
References llvm::MCFragment::FT_Align, and llvm::MCFragment::MCFragment().
Member Function Documentation
classof()
bool llvm::MCAlignFragment::classof (const MCFragment * F) inline static
Definition at line 512 of file MCSection.h.
References F, llvm::MCFragment::FT_Align, and llvm::MCFragment::MCFragment().
getAlignment()
Align llvm::MCAlignFragment::getAlignment () const inline
Definition at line 499 of file MCSection.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), llvm::LoongArchAsmBackend::shouldInsertExtraNopBytesForCodeAlign(), llvm::RISCVAsmBackend::shouldInsertExtraNopBytesForCodeAlign(), and llvm::LoongArchAsmBackend::shouldInsertFixupForCodeAlign().
getFill()
int64_t llvm::MCAlignFragment::getFill () const inline
Definition at line 500 of file MCSection.h.
Referenced by writeFragment().
getFillLen()
uint8_t llvm::MCAlignFragment::getFillLen () const inline
Definition at line 501 of file MCSection.h.
Referenced by writeFragment().
getMaxBytesToEmit()
unsigned llvm::MCAlignFragment::getMaxBytesToEmit () const inline
Definition at line 502 of file MCSection.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), llvm::LoongArchAsmBackend::shouldInsertExtraNopBytesForCodeAlign(), and llvm::LoongArchAsmBackend::shouldInsertFixupForCodeAlign().
getSubtargetInfo()
const MCSubtargetInfo * llvm::MCAlignFragment::getSubtargetInfo () const inline
Definition at line 510 of file MCSection.h.
Referenced by llvm::LoongArchAsmBackend::shouldInsertExtraNopBytesForCodeAlign(), llvm::RISCVAsmBackend::shouldInsertExtraNopBytesForCodeAlign(), llvm::LoongArchAsmBackend::shouldInsertFixupForCodeAlign(), llvm::RISCVAsmBackend::shouldInsertFixupForCodeAlign(), and writeFragment().
hasEmitNops()
bool llvm::MCAlignFragment::hasEmitNops () const inline
Definition at line 504 of file MCSection.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), and writeFragment().
setEmitNops()
void llvm::MCAlignFragment::setEmitNops (bool Value, const MCSubtargetInfo * STI) inline
Definition at line 505 of file MCSection.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCSection.h