LLVM: llvm::SmallSet< T, N, C > Class Template Reference
llvm::SmallSet< T, N, C > Class Template Reference
SmallSet - This maintains a set of unique values, optimizing for the case when the set is small (less than N).
#include "llvm/ADT/SmallSet.h"
Public Types
using key_type = T
using size_type = size_t
using value_type = T
using const_iterator = SmallSetIterator<T, N, C>
Public Member Functions
SmallSet ()=default
SmallSet (const SmallSet &)=default
SmallSet (SmallSet &&)=default
template<typename IterT>
SmallSet (IterT Begin, IterT End)
template<typename Range>
SmallSet (llvm::from_range_t, Range &&R)
SmallSet (std::initializer_list< T > L)
SmallSet & operator= (const SmallSet &)=default
SmallSet & operator= (SmallSet &&)=default
bool empty () const
size_type size () const
size_type count (const T &V) const
count - Return 1 if the element is in the set, 0 otherwise.
std::pair< const_iterator, bool > insert (const T &V)
insert - Insert an element into the set if it isn't already there.
std::pair< const_iterator, bool > insert (T &&V)
template<typename IterT>
void insert (IterT I, IterT E)
template<typename Range>
void insert_range (Range &&R)
bool erase (const T &V)
void clear ()
const_iterator begin () const
const_iterator end () const
bool contains (const T &V) const
Check if the SmallSet contains the given element.
Detailed Description
template<typename T, unsigned N, typename C = std::less<T>>
class llvm::SmallSet< T, N, C >
SmallSet - This maintains a set of unique values, optimizing for the case when the set is small (less than N).
In this case, the set can be maintained with no mallocs. If the set gets large, we expand to using an std::set to maintain reasonable lookup times.
Definition at line 134 of file SmallSet.h.
Member Typedef Documentation
const_iterator
template<typename T, unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::const_iterator = SmallSetIterator<T, N, C>
Definition at line 150 of file SmallSet.h.
key_type
template<typename T, unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::key_type = T
Definition at line 147 of file SmallSet.h.
size_type
template<typename T, unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::size_type = size_t
Definition at line 148 of file SmallSet.h.
value_type
template<typename T, unsigned N, typename C = std::less<T>> using llvm::SmallSet< T, N, C >::value_type = T
Definition at line 149 of file SmallSet.h.
Constructor & Destructor Documentation
SmallSet() [1/6]
template<typename T, unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet () default
SmallSet() [2/6]
template<typename T, unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet (const SmallSet< T, N, C > &) default
SmallSet() [3/6]
template<typename T, unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet (SmallSet< T, N, C > &&) default
SmallSet() [4/6]
template<typename T, unsigned N, typename C = std::less<T>> template<typename IterT> llvm::SmallSet< T, N, C >::SmallSet (IterT Begin, IterT End) inline
Definition at line 156 of file SmallSet.h.
SmallSet() [5/6]
template<typename T, unsigned N, typename C = std::less<T>> template<typename Range> llvm::SmallSet< T, N, C >::SmallSet (llvm::from_range_t , Range && R) inline
Definition at line 161 of file SmallSet.h.
SmallSet() [6/6]
template<typename T, unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet (std::initializer_list< T > L) inline
Definition at line 164 of file SmallSet.h.
Member Function Documentation
begin()
template<typename T, unsigned N, typename C = std::less<T>> const_iterator llvm::SmallSet< T, N, C >::begin () const inline
Definition at line 214 of file SmallSet.h.
clear()
template<typename T, unsigned N, typename C = std::less<T>> void llvm::SmallSet< T, N, C >::clear () inline
Definition at line 209 of file SmallSet.h.
Referenced by llvm::HexagonSubtarget::adjustSchedDependency(), findConsecutiveLoad(), isProfitable(), and ReduceLoopStrength().
contains()
template<typename T, unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::contains (const T & V) const inline
Check if the SmallSet contains the given element.
Definition at line 227 of file SmallSet.h.
Referenced by clobberRegEntries(), llvm::SmallSet< Register, 16 >::count(), llvm::finalizeBundle(), gatherPossiblyVectorizableLoads(), llvm::TargetInstrInfo::getAccumulatorReassociationPatterns(), llvm::SMSchedule::normalizeNonPipelinedInstructions(), llvm::GCNMaxILPSchedStrategy::tryCandidate(), llvm::GCNMaxMemoryClauseSchedStrategy::tryCandidate(), llvm::GenericScheduler::tryCandidate(), llvm::PostGenericScheduler::tryCandidate(), llvm::PPCPostRASchedStrategy::tryCandidate(), and llvm::PPCPreRASchedStrategy::tryCandidate().
count()
template<typename T, unsigned N, typename C = std::less<T>> size_type llvm::SmallSet< T, N, C >::count (const T & V) const inline
count - Return 1 if the element is in the set, 0 otherwise.
Definition at line 176 of file SmallSet.h.
Referenced by addHints(), llvm::SMSchedule::computeUnpipelineableNodes(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::Instruction::dropUnknownNonDebugMetadata(), emitSelectPseudo(), emitSelectPseudo(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), findConsecutiveLoad(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getScoreAtLevelRec(), getUniqueCaseValue(), hoistAndMergeSGPRInits(), llvm::WindowScheduler::initialize(), IsSafeAndProfitableToMove(), lowerStatepointMetaArgs(), MaySpeculate(), ProcessSourceNode(), programUndefinedIfUndefOrPoison(), llvm::MachineBasicBlock::SplitCriticalEdge(), and verifyCTRBranch().
empty()
template<typename T, unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::empty () const inline nodiscard
Definition at line 169 of file SmallSet.h.
Referenced by llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), IsValueFullyAvailableInBlock(), and llvm::ShuffleBlockStrategy::mutate().
end()
template<typename T, unsigned N, typename C = std::less<T>> const_iterator llvm::SmallSet< T, N, C >::end () const inline
Definition at line 220 of file SmallSet.h.
erase()
template<typename T, unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::erase (const T & V) inline
Definition at line 198 of file SmallSet.h.
Referenced by llvm::finalizeBundle(), and IsValueFullyAvailableInBlock().
insert() [1/3]
template<typename T, unsigned N, typename C = std::less<T>> std::pair< const_iterator, bool > llvm::SmallSet< T, N, C >::insert (const T & V) inline
insert - Insert an element into the set if it isn't already there.
Returns a pair. The first value of it is an iterator to the inserted element or the existing element in the set. The second value is true if the element is inserted (it was not in the set before).
Definition at line 182 of file SmallSet.h.
Referenced by llvm::AAPointerInfo::OffsetInfo::addToAll(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), AntiDepEdges(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyUpdatesPermissive(), AssignProtectedObjSet(), llvm::changeToUnreachable(), CheckForLiveRegDef(), CheckForLiveRegDef(), CheckForLiveRegDefMasked(), clobberRegEntries(), llvm::JumpThreadingPass::cloneInstructions(), llvm::VPRecipeBuilder::collectScaledReductions(), llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), combineShuffleOfScalars(), llvm::SMSchedule::computeUnpipelineableNodes(), llvm::ConstantFoldTerminator(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::ARMBaseInstrInfo::copyPhysReg(), despeculateCountZeros(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), emitSelectPseudo(), emitSelectPseudo(), llvm::finalizeBundle(), findConsecutiveLoad(), llvm::DWARFDie::findRecursively(), llvm::R600InstrInfo::fitsConstReadLimitations(), foldURemOfLoopIncrement(), gatherPossiblyVectorizableLoads(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getScoreAtLevelRec(), getUniqueCaseValue(), handleNormalInst(), hasAllNBitUsers(), hasAllNBitUsers(), hoistAndMergeSGPRInits(), llvm::WindowScheduler::initialize(), llvm::SmallSet< Register, 16 >::insert(), llvm::SmallSet< Register, 16 >::insert_range(), llvm::MemorySSAUpdater::insertDef(), llvm::AMDGPU::isClobberedInFunction(), isLoadCombineCandidate(), isProfitable(), IsSafeAndProfitableToMove(), isSignExtendedW(), isSignExtendedW(), isStridedLoad(), IsValueFullyAvailableInBlock(), liesBetween(), LowerAVXCONCAT_VECTORS(), llvm::SelectionDAGBuilder::LowerStatepoint(), lowerStatepointMetaArgs(), llvm::mustExecuteUBIfPoisonOnPathTo(), llvm::ShuffleBlockStrategy::mutate(), llvm::PointerMayBeCaptured(), ProcessSourceNode(), programUndefinedIfUndefOrPoison(), llvm::SwiftErrorValueTracking::propagateVRegs(), replaceAllUsesWith(), simplifySwitchOfCmpIntrinsic(), llvm::SmallSet< Register, 16 >::SmallSet(), llvm::SmallSet< Register, 16 >::SmallSet(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::InstCombinerImpl::tryToSinkInstructionDbgValues(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), unique_unsorted(), llvm::DWARFCFIAnalysis::update(), llvm::UpgradeNVVMAnnotations(), and verifyCTRBranch().
insert() [2/3]
template<typename T, unsigned N, typename C = std::less<T>> template<typename IterT> void llvm::SmallSet< T, N, C >::insert (IterT I, IterT E) inline
Definition at line 189 of file SmallSet.h.
insert() [3/3]
template<typename T, unsigned N, typename C = std::less<T>> std::pair< const_iterator, bool > llvm::SmallSet< T, N, C >::insert (T && V) inline
Definition at line 184 of file SmallSet.h.
insert_range()
template<typename T, unsigned N, typename C = std::less<T>> template<typename Range> void llvm::SmallSet< T, N, C >::insert_range (Range && R) inline
Definition at line 194 of file SmallSet.h.
Referenced by interpretValues().
operator=() [1/2]
template<typename T, unsigned N, typename C = std::less<T>> SmallSet & llvm::SmallSet< T, N, C >::operator= (const SmallSet< T, N, C > &) default
operator=() [2/2]
template<typename T, unsigned N, typename C = std::less<T>> SmallSet & llvm::SmallSet< T, N, C >::operator= (SmallSet< T, N, C > &&) default
size()
template<typename T, unsigned N, typename C = std::less<T>> size_type llvm::SmallSet< T, N, C >::size () const inline
Definition at line 171 of file SmallSet.h.
Referenced by llvm::changeToUnreachable(), llvm::ConstantFoldTerminator(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::MemorySSAUpdater::insertDef(), isProfitable(), IsSafeAndProfitableToMove(), isStridedLoad(), and llvm::PointerMayBeCaptured().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallSet.h