LLVM: llvm::AMDGPU::VOPD::ComponentInfo Class Reference
llvm::AMDGPU::VOPD::ComponentInfo Class Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Member Functions
ComponentInfo (const MCInstrDesc &OpDesc, ComponentKind Kind=ComponentKind::SINGLE, bool VOP3Layout=false)
ComponentInfo (const MCInstrDesc &OpDesc, const ComponentProps &OpXProps, bool VOP3Layout=false)
unsigned getIndexInParsedOperands (unsigned CompOprIdx) const
Public Member Functions inherited from llvm::AMDGPU::VOPD::ComponentProps
ComponentProps ()=default
ComponentProps (const MCInstrDesc &OpDesc, bool VOP3Layout=false)
unsigned getCompSrcOperandsNum () const
unsigned getCompParsedSrcOperandsNum () const
bool hasMandatoryLiteral () const
unsigned getMandatoryLiteralCompOperandIndex () const
bool hasRegSrcOperand (unsigned CompSrcIdx) const
bool hasSrc2Acc () const
unsigned getCompVOPD3ModsNum () const
unsigned getOpcode () const
unsigned isVOP3 () const
int getBitOp3OperandIdx () const
Public Member Functions inherited from llvm::AMDGPU::VOPD::ComponentLayout
ComponentLayout (ComponentKind Kind, unsigned VOPD3ModsNum, int BitOp3Idx)
ComponentLayout (const ComponentProps &OpXProps, unsigned VOPD3ModsNum, int BitOp3Idx)
unsigned getIndexOfDstInMCOperands () const
unsigned getIndexOfSrcInMCOperands (unsigned CompSrcIdx, bool VOPD3) const
unsigned getIndexOfDstInParsedOperands () const
unsigned getIndexOfSrcInParsedOperands (unsigned CompSrcIdx) const
Detailed Description
Definition at line 867 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
ComponentInfo() [1/2]
llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo (const MCInstrDesc & OpDesc, ComponentKind Kind = ComponentKind::SINGLE, bool VOP3Layout = false) inline
Definition at line 870 of file AMDGPUBaseInfo.h.
References llvm::AMDGPU::VOPD::ComponentLayout::ComponentLayout(), llvm::AMDGPU::VOPD::ComponentProps::ComponentProps(), llvm::AMDGPU::VOPD::ComponentProps::getBitOp3OperandIdx(), llvm::AMDGPU::VOPD::ComponentProps::getCompVOPD3ModsNum(), and llvm::AMDGPU::VOPD::SINGLE.
ComponentInfo() [2/2]
llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo (const MCInstrDesc & OpDesc, const ComponentProps & OpXProps, bool VOP3Layout = false) inline
Definition at line 877 of file AMDGPUBaseInfo.h.
References llvm::AMDGPU::VOPD::ComponentLayout::ComponentLayout(), llvm::AMDGPU::VOPD::ComponentProps::ComponentProps(), llvm::AMDGPU::VOPD::ComponentProps::getBitOp3OperandIdx(), and llvm::AMDGPU::VOPD::ComponentProps::getCompVOPD3ModsNum().
Member Function Documentation
getIndexInParsedOperands()
unsigned llvm::AMDGPU::VOPD::ComponentInfo::getIndexInParsedOperands (unsigned CompOprIdx) const
Definition at line 848 of file AMDGPUBaseInfo.cpp.
References assert(), llvm::AMDGPU::VOPD::DST, llvm::AMDGPU::VOPD::DST_NUM, llvm::AMDGPU::VOPD::ComponentProps::getCompParsedSrcOperandsNum(), llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfDstInParsedOperands(), llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfSrcInParsedOperands(), and llvm::AMDGPU::VOPD::MAX_OPR_NUM.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp