LLVM: llvm::LoopAnalysis Class Reference
llvm::LoopAnalysis Class Reference
Analysis pass that exposes the LoopInfo for a function.
#include "llvm/Analysis/LoopInfo.h"
Public Types
typedef LoopInfo Result
Public Member Functions
LLVM_ABI LoopInfo run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< LoopAnalysis >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< LoopAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopAnalysis >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Analysis pass that exposes the LoopInfo for a function.
Definition at line 569 of file LoopInfo.h.
Member Typedef Documentation
Result
typedef LoopInfo llvm::LoopAnalysis::Result
Definition at line 574 of file LoopInfo.h.
Member Function Documentation
run()
LoopInfo LoopAnalysis::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 969 of file LoopInfo.cpp.
References llvm::LoopInfoBase< BlockT, LoopT >::analyze(), F, and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
Referenced by llvm::OpenMPIRBuilder::applySimd(), and computeHeuristicUnrollFactor().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopInfo.h
lib/Analysis/LoopInfo.cpp