LLVM: llvm::formatv_object< Tuple > Class Template Reference
llvm::formatv_object< Tuple > Class Template Reference
#include "llvm/Support/FormatVariadic.h"
Public Member Functions
formatv_object (StringRef Fmt, Tuple &&Params, bool Validate)
formatv_object (formatv_object const &rhs)=delete
formatv_object (formatv_object &&rhs)
Public Member Functions inherited from llvm::formatv_object_base
void format (raw_ostream &S) const
std::string str () const
template<unsigned N>
SmallString< N > sstr () const
template<unsigned N>
operator SmallString< N > () const
operator std::string () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::formatv_object_base
static LLVM_ABI SmallVector< ReplacementItem, 2 > parseFormatString (StringRef Fmt, size_t NumArgs, bool Validate)
Protected Member Functions inherited from llvm::formatv_object_base
formatv_object_base (StringRef Fmt, ArrayRef< support::detail::format_adapter * > Adapters, bool Validate)
formatv_object_base (formatv_object_base const &rhs)=delete
formatv_object_base (formatv_object_base &&rhs)=default
Protected Attributes inherited from llvm::formatv_object_base
StringRef Fmt
ArrayRef< support::detail::format_adapter * > Adapters
bool Validate
Detailed Description
template<typename Tuple>
class llvm::formatv_object< Tuple >
Definition at line 124 of file FormatVariadic.h.
Constructor & Destructor Documentation
formatv_object() [1/3]
template<typename Tuple> llvm::formatv_object< Tuple >::formatv_object (StringRef Fmt, Tuple && Params, bool Validate) inline
Definition at line 148 of file FormatVariadic.h.
References llvm::formatv_object_base::Fmt, llvm::formatv_object_base::formatv_object_base(), llvm::move(), and llvm::formatv_object_base::Validate.
Referenced by formatv_object(), and formatv_object().
formatv_object() [2/3]
template<typename Tuple> llvm::formatv_object< Tuple >::formatv_object (formatv_object< Tuple > const & rhs) delete
References formatv_object().
formatv_object() [3/3]
template<typename Tuple> llvm::formatv_object< Tuple >::formatv_object (formatv_object< Tuple > && rhs) inline
Definition at line 156 of file FormatVariadic.h.
References llvm::formatv_object_base::Adapters, formatv_object(), llvm::formatv_object_base::formatv_object_base(), and llvm::move().
The documentation for this class was generated from the following file:
include/llvm/Support/FormatVariadic.h