LLVM: llvm::WebAssemblyRegisterInfo Class Reference
llvm::WebAssemblyRegisterInfo Class Reference final
#include "Target/WebAssembly/WebAssemblyRegisterInfo.h"
Public Member Functions
WebAssemblyRegisterInfo (const Triple &TT)
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
const uint32_t * getNoPreservedMask () const override
Detailed Description
Definition at line 28 of file WebAssemblyRegisterInfo.h.
Constructor & Destructor Documentation
WebAssemblyRegisterInfo()
WebAssemblyRegisterInfo::WebAssemblyRegisterInfo (const Triple & TT) explicit
Definition at line 33 of file WebAssemblyRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
bool WebAssemblyRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 51 of file WebAssemblyRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::WebAssemblyFrameLowering::getOpcAdd(), llvm::WebAssemblyFrameLowering::getOpcConst(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getUniqueVRegDef(), II, llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::Register::isVirtual(), MBB, MI, MRI, llvm::Offset, llvm::MachineOperand::setImm(), and TII.
getCalleeSavedRegs()
const MCPhysReg * WebAssemblyRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 37 of file WebAssemblyRegisterInfo.cpp.
getFrameRegister()
Register WebAssemblyRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 138 of file WebAssemblyRegisterInfo.cpp.
References llvm::WebAssemblyFunctionInfo::getFrameBaseVreg(), llvm::MachineFunction::getInfo(), and llvm::TargetFrameLowering::hasFP().
Referenced by eliminateFrameIndex().
getNoPreservedMask()
const uint32_t * llvm::WebAssemblyRegisterInfo::getNoPreservedMask () const inline override
Definition at line 48 of file WebAssemblyRegisterInfo.h.
getPointerRegClass()
const TargetRegisterClass * WebAssemblyRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 152 of file WebAssemblyRegisterInfo.cpp.
References assert(), llvm::MachineFunction::getSubtarget(), and llvm::WebAssemblySubtarget::hasAddr64().
getReservedRegs()
BitVector WebAssemblyRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 43 of file WebAssemblyRegisterInfo.cpp.
References llvm::Reserved.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyRegisterInfo.h
lib/Target/WebAssembly/WebAssemblyRegisterInfo.cpp