LLVM: llvm::IntrusiveBackList< T >::const_iterator Class Reference
llvm::IntrusiveBackList< T >::const_iterator Class Reference
#include "llvm/CodeGen/DIE.h"
Public Member Functions
const_iterator ()=default
const_iterator (typename IntrusiveBackList< T >::iterator X)
const_iterator (const T *N)
const_iterator & operator++ ()
operator bool () const
const T & operator* () const
bool operator== (const const_iterator &X) const
Public Member Functions inherited from llvm::iterator_facade_base< const_iterator, std::forward_iterator_tag, const T >
const_iterator operator+ (std::ptrdiff_t n) const
const_iterator operator- (std::ptrdiff_t n) const
const_iterator & operator++ ()
const_iterator & operator-- ()
bool operator!= (const const_iterator &RHS) const
bool operator> (const const_iterator &RHS) const
bool operator<= (const const_iterator &RHS) const
bool operator>= (const const_iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< const_iterator, std::forward_iterator_tag, const T >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Protected Types inherited from llvm::iterator_facade_base< const_iterator, std::forward_iterator_tag, const T >
enum
Detailed Description
template<class T>
class llvm::IntrusiveBackList< T >::const_iterator
Definition at line 648 of file DIE.h.
Constructor & Destructor Documentation
const_iterator() [1/3]
template<class T> llvm::IntrusiveBackList< T >::const_iterator::const_iterator () default
Referenced by operator++(), and operator==().
const_iterator() [2/3]
template<class T> llvm::IntrusiveBackList< T >::const_iterator::const_iterator (typename IntrusiveBackList< T >::iterator X) inline
Definition at line 656 of file DIE.h.
References X.
const_iterator() [3/3]
template<class T> llvm::IntrusiveBackList< T >::const_iterator::const_iterator (const T * N) inline explicit
Definition at line 657 of file DIE.h.
References T.
Member Function Documentation
operator bool()
template<class T> llvm::IntrusiveBackList< T >::const_iterator::operator bool () const inline explicit
Definition at line 664 of file DIE.h.
operator*()
template<class T> const T & llvm::IntrusiveBackList< T >::const_iterator::operator* () const inline
Definition at line 665 of file DIE.h.
References T.
operator++()
template<class T> const_iterator & llvm::IntrusiveBackList< T >::const_iterator::operator++ () inline
Definition at line 659 of file DIE.h.
References const_iterator().
operator==()
template<class T> bool llvm::IntrusiveBackList< T >::const_iterator::operator== (const const_iterator & X) const inline
Definition at line 667 of file DIE.h.
References const_iterator(), and X.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/DIE.h