LLVM: llvm::MCInstPrinter::WithMarkup Class Reference
llvm::MCInstPrinter::WithMarkup Class Reference
#include "llvm/MC/MCInstPrinter.h"
Public Member Functions
LLVM_CTOR_NODISCARD LLVM_ABI WithMarkup (MCInstPrinter &IP, raw_ostream &OS, Markup M, bool EnableMarkup, bool EnableColor)
LLVM_ABI ~WithMarkup ()
template<typename T>
WithMarkup & operator<< (T &O)
template<typename T>
WithMarkup & operator<< (const T &O)
Detailed Description
Definition at line 102 of file MCInstPrinter.h.
Constructor & Destructor Documentation
WithMarkup()
MCInstPrinter::WithMarkup::WithMarkup (MCInstPrinter & IP, raw_ostream & OS, Markup M, bool EnableMarkup, bool EnableColor)
Definition at line 231 of file MCInstPrinter.cpp.
References llvm::raw_ostream::CYAN, llvm::raw_ostream::GREEN, llvm::MCInstPrinter::Immediate, llvm::MCInstPrinter::MCInstPrinter(), llvm::MCInstPrinter::Memory, llvm::raw_ostream::RED, llvm::MCInstPrinter::Register, llvm::raw_ostream::RESET, llvm::MCInstPrinter::Target, and llvm::raw_ostream::YELLOW.
Referenced by operator<<(), and operator<<().
~WithMarkup()
MCInstPrinter::WithMarkup::~WithMarkup ()
Definition at line 273 of file MCInstPrinter.cpp.
Member Function Documentation
operator<<() [1/2]
template<typename T> WithMarkup & llvm::MCInstPrinter::WithMarkup::operator<< (const T & O) inline
Definition at line 114 of file MCInstPrinter.h.
References T, and WithMarkup().
operator<<() [2/2]
template<typename T> WithMarkup & llvm::MCInstPrinter::WithMarkup::operator<< (T & O) inline
Definition at line 109 of file MCInstPrinter.h.
References T, and WithMarkup().
The documentation for this class was generated from the following files:
include/llvm/MC/MCInstPrinter.h
lib/MC/MCInstPrinter.cpp