LLVM: llvm::Directive Class Reference
llvm::Directive Class Reference
#include "llvm/TableGen/DirectiveEmitter.h"
Public Member Functions
Directive (const Record *Def)
std::vector< const Record * > getAllowedClauses () const
std::vector< const Record * > getAllowedOnceClauses () const
std::vector< const Record * > getAllowedExclusiveClauses () const
std::vector< const Record * > getRequiredClauses () const
std::vector< const Record * > getLeafConstructs () const
const Record * getAssociation () const
const Record * getCategory () const
std::vector< const Record * > getSourceLanguages () const
std::string getClangAccSpelling () const
Public Member Functions inherited from llvm::BaseRecord
BaseRecord (const Record *Def)
std::vector< Spelling::Value > getSpellings () const
StringRef getSpellingForIdentifier () const
std::string getFormattedName () const
bool isDefault () const
StringRef getRecordName () const
const Record * getRecord () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::BaseRecord
static std::string getSnakeName (StringRef Name)
static std::string getUpperCamelName (StringRef Name, StringRef Sep)
Protected Attributes inherited from llvm::BaseRecord
const Record * Def
Detailed Description
Definition at line 232 of file DirectiveEmitter.h.
Constructor & Destructor Documentation
Directive()
llvm::Directive::Directive (const Record * Def) inline
Definition at line 234 of file DirectiveEmitter.h.
References llvm::BaseRecord::BaseRecord(), and llvm::BaseRecord::Def.
Member Function Documentation
getAllowedClauses()
std::vector< const Record * > llvm::Directive::getAllowedClauses () const inline
Definition at line 236 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getAllowedExclusiveClauses()
std::vector< const Record * > llvm::Directive::getAllowedExclusiveClauses () const inline
Definition at line 244 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getAllowedOnceClauses()
std::vector< const Record * > llvm::Directive::getAllowedOnceClauses () const inline
Definition at line 240 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getAssociation()
const Record * llvm::Directive::getAssociation () const inline
Definition at line 256 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getCategory()
const Record * llvm::Directive::getCategory () const inline
Definition at line 260 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getClangAccSpelling()
std::string llvm::Directive::getClangAccSpelling () const inline
Definition at line 267 of file DirectiveEmitter.h.
References llvm::BaseRecord::getSpellingForIdentifier(), and llvm::BaseRecord::getUpperCamelName().
getLeafConstructs()
std::vector< const Record * > llvm::Directive::getLeafConstructs () const inline
Definition at line 252 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getRequiredClauses()
std::vector< const Record * > llvm::Directive::getRequiredClauses () const inline
Definition at line 248 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getSourceLanguages()
std::vector< const Record * > llvm::Directive::getSourceLanguages () const inline
Definition at line 262 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
The documentation for this class was generated from the following file:
include/llvm/TableGen/DirectiveEmitter.h