LLVM: llvm::sandboxir::RegionsFromMetadata Class Reference
llvm::sandboxir::RegionsFromMetadata Class Reference final
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Passes/RegionsFromMetadata.h"
Public Member Functions
RegionsFromMetadata (StringRef Pipeline)
bool runOnFunction (Function &F, const Analyses &A) final
\Returns true if it modifies F.
void printPipeline (raw_ostream &OS) const final
Similar to print() but adds a newline. Used for testing.
Public Member Functions inherited from llvm::sandboxir::FunctionPass
FunctionPass (StringRef Name)
Name can't contain any spaces or start with '-'.
Public Member Functions inherited from llvm::sandboxir::Pass
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()
StringRef getName () const
\Returns the name of the pass.
virtual void print (raw_ostream &OS) const
virtual LLVM_DUMP_METHOD void dump () const
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::Pass
const std::string Name
The pass name.
Detailed Description
Definition at line 23 of file RegionsFromMetadata.h.
Constructor & Destructor Documentation
RegionsFromMetadata()
llvm::sandboxir::RegionsFromMetadata::RegionsFromMetadata (StringRef Pipeline)
Definition at line 16 of file RegionsFromMetadata.cpp.
References llvm::sandboxir::FunctionPass::FunctionPass().
Member Function Documentation
printPipeline()
void llvm::sandboxir::RegionsFromMetadata::printPipeline (raw_ostream & OS) const inline final virtual
Similar to print() but adds a newline. Used for testing.
Reimplemented from llvm::sandboxir::Pass.
Definition at line 30 of file RegionsFromMetadata.h.
References llvm::sandboxir::Pass::getName().
runOnFunction()
bool llvm::sandboxir::RegionsFromMetadata::runOnFunction (Function & F, const Analyses & A) final virtual
\Returns true if it modifies F.
Implements llvm::sandboxir::FunctionPass.
Definition at line 20 of file RegionsFromMetadata.cpp.
References A(), llvm::sandboxir::Region::createRegionsFromMD(), and F.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Passes/RegionsFromMetadata.h
lib/Transforms/Vectorize/SandboxVectorizer/Passes/RegionsFromMetadata.cpp