LLVM: llvm::location_op_iterator Class Reference
llvm::location_op_iterator Class Reference
#include "llvm/IR/IntrinsicInst.h"
Public Member Functions
location_op_iterator (ValueAsMetadata *SingleIter)
location_op_iterator (ValueAsMetadata **MultiIter)
location_op_iterator (const location_op_iterator &R)
location_op_iterator & operator= (const location_op_iterator &R)
bool operator== (const location_op_iterator &RHS) const
const Value * operator* () const
Value * operator* ()
location_op_iterator & operator++ ()
location_op_iterator & operator-- ()
Public Member Functions inherited from llvm::iterator_facade_base< location_op_iterator, std::bidirectional_iterator_tag, Value * >
location_op_iterator operator+ (std::ptrdiff_t n) const
location_op_iterator operator- (std::ptrdiff_t n) const
location_op_iterator & operator++ ()
location_op_iterator & operator-- ()
bool operator!= (const location_op_iterator &RHS) const
bool operator> (const location_op_iterator &RHS) const
bool operator<= (const location_op_iterator &RHS) const
bool operator>= (const location_op_iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< location_op_iterator, std::bidirectional_iterator_tag, Value * >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Protected Types inherited from llvm::iterator_facade_base< location_op_iterator, std::bidirectional_iterator_tag, Value * >
enum
Detailed Description
Definition at line 197 of file IntrinsicInst.h.
Constructor & Destructor Documentation
location_op_iterator() [1/3]
llvm::location_op_iterator::location_op_iterator (ValueAsMetadata * SingleIter) inline
Definition at line 203 of file IntrinsicInst.h.
Referenced by location_op_iterator(), operator++(), operator--(), operator=(), and operator==().
location_op_iterator() [2/3]
llvm::location_op_iterator::location_op_iterator (ValueAsMetadata ** MultiIter) inline
Definition at line 204 of file IntrinsicInst.h.
location_op_iterator() [3/3]
llvm::location_op_iterator::location_op_iterator (const location_op_iterator & R) inline
Definition at line 206 of file IntrinsicInst.h.
References location_op_iterator().
Member Function Documentation
operator*() [1/2]
Value * llvm::location_op_iterator::operator* () inline
Definition at line 218 of file IntrinsicInst.h.
References llvm::cast(), llvm::ValueAsMetadata::getValue(), and llvm::isa().
operator*() [2/2]
const Value * llvm::location_op_iterator::operator* () const inline
Definition at line 212 of file IntrinsicInst.h.
References llvm::cast(), llvm::ValueAsMetadata::getValue(), and llvm::isa().
operator++()
location_op_iterator & llvm::location_op_iterator::operator++ () inline
Definition at line 224 of file IntrinsicInst.h.
References llvm::cast(), llvm::isa(), and location_op_iterator().
operator--()
location_op_iterator & llvm::location_op_iterator::operator-- () inline
Definition at line 231 of file IntrinsicInst.h.
References llvm::cast(), llvm::isa(), and location_op_iterator().
operator=()
location_op_iterator & llvm::location_op_iterator::operator= (const location_op_iterator & R) inline
Definition at line 207 of file IntrinsicInst.h.
References location_op_iterator().
operator==()
bool llvm::location_op_iterator::operator== (const location_op_iterator & RHS) const inline
Definition at line 211 of file IntrinsicInst.h.
References location_op_iterator(), and RHS.
The documentation for this class was generated from the following file:
include/llvm/IR/IntrinsicInst.h