LLVM: llvm::PPCPostRASchedStrategy Class Reference
llvm::PPCPostRASchedStrategy Class Reference
A MachineSchedStrategy implementation for PowerPC post RA scheduling.
#include "Target/PowerPC/PPCMachineScheduler.h"
Public Member Functions
PPCPostRASchedStrategy (const MachineSchedContext *C)
Public Member Functions inherited from llvm::PostGenericScheduler
PostGenericScheduler (const MachineSchedContext *C)
~PostGenericScheduler () override=default
void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override
Optionally override the per-region scheduling policy.
bool shouldTrackPressure () const override
PostRA scheduling does not track pressure.
void registerRoots () override
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
SUnit * pickNodeBidirectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
void scheduleTree (unsigned SubtreeID) override
Scheduler callback to notify that a new subtree is scheduled.
void schedNode (SUnit *SU, bool IsTopNode) override
Called after ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void dumpPolicy () const
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
Protected Member Functions
void initialize (ScheduleDAGMI *Dag) override
Initialize the strategy after building the DAG for a new region.
SUnit * pickNode (bool &IsTopNode) override
Pick the next node to schedule.
void enterMBB (MachineBasicBlock *MBB) override
Tell the strategy that MBB is about to be processed.
void leaveMBB () override
Tell the strategy that current MBB is done.
bool tryCandidate (SchedCandidate &Cand, SchedCandidate &TryCand) override
Apply a set of heuristics to a new candidate for PostRA scheduling.
bool biasAddiCandidate (SchedCandidate &Cand, SchedCandidate &TryCand) const
Protected Member Functions inherited from llvm::PostGenericScheduler
void pickNodeFromQueue (SchedBoundary &Zone, SchedCandidate &Cand)
Protected Member Functions inherited from llvm::GenericSchedulerBase
GenericSchedulerBase (const MachineSchedContext *C)
LLVM_ABI void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
MachineSchedPolicy getPolicy () const override
void traceCandidate (const SchedCandidate &Cand)
Additional Inherited Members
Public Types inherited from llvm::GenericSchedulerBase
enum CandReason : uint8_t {
NoCand , Only1 , PhysReg , RegExcess ,
RegCritical , Stall , Cluster , Weak ,
RegMax , ResourceReduce , ResourceDemand , BotHeightReduce ,
BotPathReduce , TopDepthReduce , TopPathReduce , NodeOrder ,
FirstValid
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions inherited from llvm::GenericSchedulerBase
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Protected Attributes inherited from llvm::PostGenericScheduler
ScheduleDAGMI * DAG = nullptr
SchedBoundary Top
SchedBoundary Bot
SchedCandidate TopCand
Candidate last picked from Top boundary.
SchedCandidate BotCand
Candidate last picked from Bot boundary.
ClusterInfo * TopCluster
ClusterInfo * BotCluster
Protected Attributes inherited from llvm::GenericSchedulerBase
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
unsigned TopIdx = 0
unsigned BotIdx = 0
unsigned NumRegionInstrs = 0
MachineSchedPolicy RegionPolicy
SchedRemainder Rem
Detailed Description
A MachineSchedStrategy implementation for PowerPC post RA scheduling.
Definition at line 36 of file PPCMachineScheduler.h.
Constructor & Destructor Documentation
PPCPostRASchedStrategy()
llvm::PPCPostRASchedStrategy::PPCPostRASchedStrategy (const MachineSchedContext * C) inline
Definition at line 38 of file PPCMachineScheduler.h.
References llvm::CallingConv::C, and llvm::PostGenericScheduler::PostGenericScheduler().
Member Function Documentation
biasAddiCandidate()
bool PPCPostRASchedStrategy::biasAddiCandidate (SchedCandidate & Cand, SchedCandidate & TryCand) const protected
Definition at line 164 of file PPCMachineScheduler.cpp.
References EnableAddiHeuristic, isADDIInstr(), llvm::GenericSchedulerBase::SchedCandidate::Reason, and llvm::GenericSchedulerBase::Stall.
Referenced by tryCandidate().
enterMBB()
void PPCPostRASchedStrategy::enterMBB (MachineBasicBlock * MBB) override protected virtual
Tell the strategy that MBB is about to be processed.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 234 of file PPCMachineScheduler.cpp.
References llvm::MachineSchedStrategy::enterMBB(), and MBB.
initialize()
void PPCPostRASchedStrategy::initialize (ScheduleDAGMI * DAG) override protected virtual
Initialize the strategy after building the DAG for a new region.
Reimplemented from llvm::PostGenericScheduler.
Definition at line 244 of file PPCMachineScheduler.cpp.
References llvm::PostGenericScheduler::initialize().
leaveMBB()
void PPCPostRASchedStrategy::leaveMBB () override protected virtual
Tell the strategy that current MBB is done.
Reimplemented from llvm::MachineSchedStrategy.
Definition at line 239 of file PPCMachineScheduler.cpp.
References llvm::MachineSchedStrategy::leaveMBB().
pickNode()
SUnit * PPCPostRASchedStrategy::pickNode (bool & IsTopNode) override protected virtual
Pick the next node to schedule.
Reimplemented from llvm::PostGenericScheduler.
Definition at line 249 of file PPCMachineScheduler.cpp.
References llvm::PostGenericScheduler::pickNode().
tryCandidate()
bool PPCPostRASchedStrategy::tryCandidate (SchedCandidate & Cand, SchedCandidate & TryCand) override protected virtual
Apply a set of heuristics to a new candidate for PostRA scheduling.
Parameters
Cand provides the policy and current best candidate.
TryCand refers to the next SUnit candidate, otherwise uninitialized.
Returns
true if TryCand is better than Cand (Reason is NOT NoCand)
Reimplemented from llvm::PostGenericScheduler.
Definition at line 176 of file PPCMachineScheduler.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, biasAddiCandidate(), llvm::PostGenericScheduler::BotCluster, llvm::GenericSchedulerBase::Cluster, llvm::SmallSet< T, N, C >::contains(), llvm::GenericSchedulerBase::SchedResourceDelta::CritResources, llvm::GenericSchedulerBase::SchedResourceDelta::DemandedResources, llvm::GenericSchedulerBase::SchedCandidate::isValid(), llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::NodeOrder, llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::CandPolicy::ReduceLatency, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::ResourceDemand, llvm::GenericSchedulerBase::ResourceReduce, llvm::GenericSchedulerBase::Stall, llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::PostGenericScheduler::Top, llvm::PostGenericScheduler::TopCluster, llvm::tryGreater(), llvm::tryLatency(), and llvm::tryLess().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCMachineScheduler.h
lib/Target/PowerPC/PPCMachineScheduler.cpp