LLVM: llvm::UnOpInit Class Reference
llvm::UnOpInit Class Reference final
!op (X) - Transform an init.
#include "llvm/TableGen/Record.h"
Public Types
enum UnaryOp : uint8_t {
TOLOWER , TOUPPER , CAST , NOT ,
HEAD , TAIL , SIZE , EMPTY ,
GETDAGOP , LOG2 , REPR , LISTFLATTEN ,
INITIALIZED
}
Public Member Functions
UnOpInit (const UnOpInit &)=delete
UnOpInit & operator= (const UnOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
UnaryOp getOpcode () const
const Init * getOperand () const
const Init * Fold (const Record *CurRec, bool IsFinal=false) const
const Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a literal form.
Public Member Functions inherited from llvm::OpInit
OpInit (const OpInit &)=delete
OpInit & operator= (OpInit &)=delete
const Init * getBit (unsigned Bit) const final
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
const RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
const Init * getCastTo (const RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
const Init * convertInitializerTo (const RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
const Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
const RecTy * getFieldType (const StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations?
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static const UnOpInit * get (UnaryOp opc, const Init *lhs, const RecTy *Type)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_InstancesOpInit , IK_AnonymousNameInit ,
IK_StringInit , IK_VarInit , IK_VarBitInit , IK_VarDefInit ,
IK_LastTypedInit , IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, const RecTy *Type, uint8_t Opc)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, const RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!op (X) - Transform an init.
Definition at line 832 of file Record.h.
Member Enumeration Documentation
UnaryOp
enum llvm::UnOpInit::UnaryOp : uint8_t
Enumerator
TOLOWER
TOUPPER
CAST
NOT
HEAD
TAIL
SIZE
EMPTY
GETDAGOP
LOG2
REPR
LISTFLATTEN
INITIALIZED
Definition at line 834 of file Record.h.
Constructor & Destructor Documentation
UnOpInit()
llvm::UnOpInit::UnOpInit (const UnOpInit &) delete
Member Function Documentation
classof()
bool llvm::UnOpInit::classof (const Init * I) inline static
Definition at line 860 of file Record.h.
References I, and llvm::Init::IK_UnOpInit.
Fold()
const Init * UnOpInit::Fold (const Record * CurRec, bool IsFinal = false) const
Definition at line 838 of file Record.cpp.
References llvm::append_range(), assert(), CAST, llvm::cast(), llvm::Init::convertInitializerTo(), D(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), EMPTY, llvm::IntInit::get(), llvm::IntRecTy::get(), llvm::ListInit::get(), llvm::StringInit::get(), llvm::RecTy::getAsString(), getAsString(), GETDAGOP, llvm::RecordKeeper::getDef(), llvm::Record::getLoc(), llvm::Record::getNameInit(), getOpcode(), llvm::TypedInit::getRecordKeeper(), llvm::TypedInit::getType(), HEAD, INITIALIZED, INT64_MAX, llvm::isa(), llvm::List, LISTFLATTEN, LOG2, llvm::Log2_64(), NOT, llvm::PrintFatalError(), REPR, SIZE, T, TAIL, TOLOWER, TOUPPER, and llvm::RecTy::typeIsA().
Referenced by llvm::TypedInit::getCastTo().
get()
const UnOpInit * UnOpInit::get (UnaryOp opc, const Init * lhs, const RecTy * Type) static
Definition at line 820 of file Record.cpp.
References llvm::detail::RecordKeeperImpl::Allocator, I, llvm::Init::Opc, ProfileUnOpInit(), and llvm::detail::RecordKeeperImpl::TheUnOpInitPool.
Referenced by llvm::TypedInit::getCastTo(), and resolveReferences().
getAsString()
std::string UnOpInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 1043 of file Record.cpp.
References CAST, EMPTY, llvm::RecTy::getAsString(), GETDAGOP, getOpcode(), llvm::TypedInit::getType(), HEAD, INITIALIZED, LISTFLATTEN, LOG2, NOT, REPR, SIZE, TAIL, TOLOWER, and TOUPPER.
Referenced by Fold().
getOpcode()
UnaryOp llvm::UnOpInit::getOpcode () const inline
Definition at line 868 of file Record.h.
References llvm::Init::Opc.
Referenced by Fold(), getAsString(), Profile(), and resolveReferences().
getOperand()
const Init * llvm::UnOpInit::getOperand () const inline
Definition at line 869 of file Record.h.
Referenced by Profile().
operator=()
UnOpInit & llvm::UnOpInit::operator= (const UnOpInit &) delete
Profile()
void UnOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 834 of file Record.cpp.
References getOpcode(), getOperand(), llvm::TypedInit::getType(), and ProfileUnOpInit().
resolveReferences()
const Init * UnOpInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1034 of file Record.cpp.
References CAST, get(), getOpcode(), llvm::TypedInit::getType(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp