LLVM: llvm::XtensaMachineFunctionInfo Class Reference
llvm::XtensaMachineFunctionInfo Class Reference
#include "Target/Xtensa/XtensaMachineFunctionInfo.h"
Public Member Functions
XtensaMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
int getBranchRelaxationScratchFrameIndex () const
void setBranchRelaxationScratchFrameIndex (int Index)
unsigned getVarArgsFirstGPR () const
void setVarArgsFirstGPR (unsigned GPR)
int getVarArgsOnStackFrameIndex () const
void setVarArgsOnStackFrameIndex (int FI)
int getVarArgsInRegsFrameIndex () const
void setVarArgsInRegsFrameIndex (int FI)
bool isSaveFrameRegister () const
void setSaveFrameRegister ()
unsigned createCPLabelId ()
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy, typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
Definition at line 24 of file XtensaMachineFunctionInfo.h.
Constructor & Destructor Documentation
XtensaMachineFunctionInfo()
llvm::XtensaMachineFunctionInfo::XtensaMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline explicit
Definition at line 34 of file XtensaMachineFunctionInfo.h.
References F.
Member Function Documentation
createCPLabelId()
unsigned llvm::XtensaMachineFunctionInfo::createCPLabelId () inline
Definition at line 59 of file XtensaMachineFunctionInfo.h.
Referenced by llvm::XtensaTargetLowering::LowerCall().
getBranchRelaxationScratchFrameIndex()
int llvm::XtensaMachineFunctionInfo::getBranchRelaxationScratchFrameIndex () const inline
Definition at line 39 of file XtensaMachineFunctionInfo.h.
getVarArgsFirstGPR()
unsigned llvm::XtensaMachineFunctionInfo::getVarArgsFirstGPR () const inline
Definition at line 46 of file XtensaMachineFunctionInfo.h.
getVarArgsInRegsFrameIndex()
int llvm::XtensaMachineFunctionInfo::getVarArgsInRegsFrameIndex () const inline
Definition at line 53 of file XtensaMachineFunctionInfo.h.
getVarArgsOnStackFrameIndex()
int llvm::XtensaMachineFunctionInfo::getVarArgsOnStackFrameIndex () const inline
Definition at line 49 of file XtensaMachineFunctionInfo.h.
isSaveFrameRegister()
bool llvm::XtensaMachineFunctionInfo::isSaveFrameRegister () const inline
Definition at line 56 of file XtensaMachineFunctionInfo.h.
Referenced by llvm::XtensaFrameLowering::emitPrologue().
setBranchRelaxationScratchFrameIndex()
void llvm::XtensaMachineFunctionInfo::setBranchRelaxationScratchFrameIndex (int Index) inline
Definition at line 42 of file XtensaMachineFunctionInfo.h.
setSaveFrameRegister()
void llvm::XtensaMachineFunctionInfo::setSaveFrameRegister () inline
Definition at line 57 of file XtensaMachineFunctionInfo.h.
Referenced by llvm::XtensaTargetLowering::LowerFormalArguments().
setVarArgsFirstGPR()
void llvm::XtensaMachineFunctionInfo::setVarArgsFirstGPR (unsigned GPR) inline
Definition at line 47 of file XtensaMachineFunctionInfo.h.
Referenced by llvm::XtensaTargetLowering::LowerFormalArguments().
setVarArgsInRegsFrameIndex()
void llvm::XtensaMachineFunctionInfo::setVarArgsInRegsFrameIndex (int FI) inline
Definition at line 54 of file XtensaMachineFunctionInfo.h.
Referenced by llvm::XtensaTargetLowering::LowerFormalArguments().
setVarArgsOnStackFrameIndex()
void llvm::XtensaMachineFunctionInfo::setVarArgsOnStackFrameIndex (int FI) inline
Definition at line 50 of file XtensaMachineFunctionInfo.h.
Referenced by llvm::XtensaTargetLowering::LowerFormalArguments().
The documentation for this class was generated from the following file:
lib/Target/Xtensa/XtensaMachineFunctionInfo.h