LLVM: llvm::DbgValueLoc Class Reference
llvm::DbgValueLoc Class Reference
The location of a single variable, composed of an expression and 0 or more DbgValueLocEntries.
#include "CodeGen/AsmPrinter/DebugLocEntry.h"
Public Member Functions
DbgValueLoc (const DIExpression *Expr, ArrayRef< DbgValueLocEntry > Locs)
DbgValueLoc (const DIExpression *Expr, ArrayRef< DbgValueLocEntry > Locs, bool IsVariadic)
DbgValueLoc (const DIExpression *Expr, DbgValueLocEntry Loc)
bool isFragment () const
bool isEntryVal () const
bool isVariadic () const
bool isEquivalent (const DbgValueLoc &Other) const
const DIExpression * getExpression () const
ArrayRef< DbgValueLocEntry > getLocEntries () const
LLVM_DUMP_METHOD void dump () const
Friends
bool operator== (const DbgValueLoc &A, const DbgValueLoc &B)
Compare two DbgValueLocs for equality.
bool operator< (const DbgValueLoc &A, const DbgValueLoc &B)
Compare two fragments based on their offset.
Detailed Description
The location of a single variable, composed of an expression and 0 or more DbgValueLocEntries.
Definition at line 111 of file DebugLocEntry.h.
Constructor & Destructor Documentation
DbgValueLoc() [1/3]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, ArrayRef< DbgValueLocEntry > Locs) inline
Definition at line 120 of file DebugLocEntry.h.
Referenced by isEquivalent(), operator<, and operator==.
DbgValueLoc() [2/3]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, ArrayRef< DbgValueLocEntry > Locs, bool IsVariadic) inline
Definition at line 123 of file DebugLocEntry.h.
References llvm::any_of(), assert(), and llvm::DIExpression::isValid().
DbgValueLoc() [3/3]
llvm::DbgValueLoc::DbgValueLoc (const DIExpression * Expr, DbgValueLocEntry Loc) inline
Definition at line 135 of file DebugLocEntry.h.
References assert(), and llvm::DIExpression::isValid().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void llvm::DbgValueLoc::dump () const inline
Definition at line 172 of file DebugLocEntry.h.
References LLVM_DUMP_METHOD.
getExpression()
const DIExpression * llvm::DbgValueLoc::getExpression () const inline
Definition at line 167 of file DebugLocEntry.h.
Referenced by isEntryVal(), and isFragment().
getLocEntries()
ArrayRef< DbgValueLocEntry > llvm::DbgValueLoc::getLocEntries () const inline
Definition at line 168 of file DebugLocEntry.h.
isEntryVal()
bool llvm::DbgValueLoc::isEntryVal () const inline
Definition at line 142 of file DebugLocEntry.h.
References getExpression(), and llvm::DIExpression::isEntryValue().
isEquivalent()
bool llvm::DbgValueLoc::isEquivalent (const DbgValueLoc & Other) const inline
Definition at line 144 of file DebugLocEntry.h.
References DbgValueLoc(), llvm::DbgValueLocEntry::getLoc(), llvm::MachineLocation::getReg(), llvm::DIExpression::isEqualExpression(), llvm::DbgValueLocEntry::isLocation(), and llvm::Other.
isFragment()
bool llvm::DbgValueLoc::isFragment () const inline
Definition at line 141 of file DebugLocEntry.h.
References getExpression(), and llvm::DIExpression::isFragment().
isVariadic()
bool llvm::DbgValueLoc::isVariadic () const inline
Definition at line 143 of file DebugLocEntry.h.
Friends And Related Symbol Documentation
operator<
bool operator< (const DbgValueLoc & A, const DbgValueLoc & B) friend
Compare two fragments based on their offset.
Definition at line 280 of file DebugLocEntry.h.
References A(), B(), and DbgValueLoc().
operator==
bool operator== (const DbgValueLoc & A, const DbgValueLoc & B) friend
Compare two DbgValueLocs for equality.
Definition at line 274 of file DebugLocEntry.h.
References A(), B(), and DbgValueLoc().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/DebugLocEntry.h