LLVM: llvm::PGOCtxProfileReader Class Reference
llvm::PGOCtxProfileReader Class Reference final
#include "llvm/ProfileData/PGOCtxProfReader.h"
Public Member Functions
PGOCtxProfileReader (StringRef Buffer)
LLVM_ABI Expected< PGOCtxProfile > loadProfiles ()
Detailed Description
Definition at line 199 of file PGOCtxProfReader.h.
Constructor & Destructor Documentation
PGOCtxProfileReader()
llvm::PGOCtxProfileReader::PGOCtxProfileReader (StringRef Buffer) inline
Definition at line 219 of file PGOCtxProfReader.h.
References llvm::size(), and substr().
Member Function Documentation
loadProfiles()
Expected< PGOCtxProfile > PGOCtxProfileReader::loadProfiles ()
Definition at line 242 of file PGOCtxProfReader.cpp.
References llvm::ContextsSectionBlockID, llvm::FlatProfilesSectionBlockID, I, RET_ON_ERR, and llvm::Test.
Referenced by llvm::CtxProfAnalysis::run().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/PGOCtxProfReader.h
lib/ProfileData/PGOCtxProfReader.cpp