LLVM: llvm::StringSwitch< T, R > Class Template Reference
llvm::StringSwitch< T, R > Class Template Reference
A switch()-like statement whose cases are string literals.
#include "llvm/ADT/StringSwitch.h"
Public Member Functions
StringSwitch (StringRef S)
StringSwitch (const StringSwitch &)=delete
void operator= (const StringSwitch &)=delete
void operator= (StringSwitch &&other)=delete
StringSwitch (StringSwitch &&other)
~StringSwitch ()=default
StringSwitch & Case (StringLiteral S, T Value)
StringSwitch & EndsWith (StringLiteral S, T Value)
StringSwitch & StartsWith (StringLiteral S, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, StringLiteral S9, T Value)
StringSwitch & CaseLower (StringLiteral S, T Value)
StringSwitch & EndsWithLower (StringLiteral S, T Value)
StringSwitch & StartsWithLower (StringLiteral S, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value)
R Default (T Value)
operator R ()
Detailed Description
template<typename T, typename R = T>
class llvm::StringSwitch< T, R >
A switch()-like statement whose cases are string literals.
The StringSwitch class is a simple form of a switch() statement that determines whether the given string matches one of the given string literals. The template type parameter T is the type of the value that will be returned from the string-switch expression. For example, the following code switches on the name of a color in argv[i]:
Color color = StringSwitch<Color>(argv[i])
  .Case("red", Red)
  .Case("orange", Orange)
  .Case("yellow", Yellow)
  .Case("green", Green)
  .Case("blue", Blue)
  .Case("indigo", Indigo)
  .Cases("violet", "purple", Violet)
  .Default(UnknownColor);
Definition at line 43 of file StringSwitch.h.
Constructor & Destructor Documentation
StringSwitch() [1/3]
template<typename T, typename R = T> llvm::StringSwitch< T, R >::StringSwitch (StringRef S) inline explicit
Definition at line 52 of file StringSwitch.h.
Referenced by Case(), CaseLower(), Cases(), Cases(), Cases(), Cases(), Cases(), Cases(), Cases(), Cases(), Cases(), CasesLower(), CasesLower(), CasesLower(), CasesLower(), EndsWith(), EndsWithLower(), operator=(), operator=(), StartsWith(), StartsWithLower(), StringSwitch(), and StringSwitch().
StringSwitch() [2/3]
template<typename T, typename R = T> llvm::StringSwitch< T, R >::StringSwitch (const StringSwitch< T, R > &) delete
References StringSwitch().
StringSwitch() [3/3]
template<typename T, typename R = T> llvm::StringSwitch< T, R >::StringSwitch (StringSwitch< T, R > && other) inline
Definition at line 62 of file StringSwitch.h.
References llvm::move(), and StringSwitch().
~StringSwitch()
template<typename T, typename R = T> llvm::StringSwitch< T, R >::~StringSwitch () default
Member Function Documentation
Case()
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Case (StringLiteral S, T Value) inline
Definition at line 68 of file StringSwitch.h.
References StringSwitch(), and T.
Referenced by llvm::AArch64StringToVectorLayout(), llvm::ARMCondCodeFromString(), llvm::ARMVectorCondCodeFromString(), llvm::classifyEHPersonality(), llvm::ELF::convertArchNameToEMachine(), llvm::convertStrToExceptionBehavior(), llvm::convertStrToRoundingMode(), llvm::TargetOptions::FramePointerIsReserved(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getAccessQualifier(), llvm::ARM::getArchSynonym(), llvm::Triple::getArchTypeForLLVMName(), llvm::DIFile::getChecksumKind(), llvm::Hexagon::getCpu(), llvm::XCOFF::getCpuID(), llvm::DWARFYAML::getDWARFEmitterByName(), llvm::Hexagon_MC::GetELFFlags(), llvm::DICompileUnit::getEmissionKind(), llvm::AArch64BuildAttributes::getFeatureAndBitsTagsID(), llvm::DIFixedPointType::getFixedPointKind(), llvm::ARMAsmBackendELF::getFixupKind(), llvm::AVRAsmBackend::getFixupKind(), llvm::LoongArchAsmBackend::getFixupKind(), llvm::MipsAsmBackend::getFixupKind(), llvm::RISCVAsmBackend::getFixupKind(), getFPPredicateFromMD(), llvm::ARM::getFPUSynonym(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForPowerPC(), llvm::sys::detail::getHostCPUNameForRISCV(), getHWDivSynonym(), getIdentifierKind(), llvm::object::getImageKind(), llvm::M68kTargetLowering::getInlineAsmMemConstraint(), llvm::RISCVMachineFunctionInfo::getInterruptStackKind(), getIntPredicateFromMD(), llvm::mca::RISCVLMULInstrument::getLMUL(), llvm::getMachineType(), llvm::dwarf::getMacinfo(), getMClassFlagsMask(), getMetadataKeywordKind(), llvm::DICompileUnit::getNameTableKind(), llvm::object::getOffloadKind(), llvm::dwarf::getOperationEncoding(), llvm::AArch64BuildAttributes::getOptionalID(), llvm::AArch64BuildAttributes::getPauthABITagsID(), llvm::MachO::getPlatformFromName(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::AVRTargetLowering::getRegisterByName(), llvm::HexagonTargetLowering::getRegisterByName(), llvm::LanaiTargetLowering::getRegisterByName(), llvm::MipsTargetLowering::getRegisterByName(), llvm::SITargetLowering::getRegisterByName(), llvm::SparcTargetLowering::getRegisterByName(), llvm::SystemZTargetLowering::getRegisterByName(), llvm::VETargetLowering::getRegisterByName(), llvm::X86TargetLowering::getRegisterByName(), llvm::mca::RISCVSEWInstrument::getSEW(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), getSpecialRegForName(), llvm::LoongArchABI::getTargetABI(), llvm::RISCVABI::getTargetABI(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getValueKind(), llvm::AArch64BuildAttributes::getVendorID(), llvm::VFABI::getVFParamKindFromString(), llvm::yaml::ScalarTraits< IFSBitWidthType >::input(), llvm::yaml::ScalarTraits< IFSEndiannessType >::input(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), isSMEABIRoutineCall(), isSpecialLLVMGlobalArrayToSkip(), llvm::object::Lexer::lex(), llvm::object::COFFObjectFile::mapDebugSectionName(), llvm::object::MachOObjectFile::mapDebugSectionName(), llvm::object::XCOFFObjectFile::mapDebugSectionName(), matchMatrixRegName(), matchMatrixTileListRegName(), MatchNeonVectorRegName(), matchSVEDataVectorRegName(), matchSVEPredicateAsCounterRegName(), matchSVEPredicateVectorRegName(), MCAttrForString(), llvm::PPC::normalizeCPUName(), llvm::HexagonMCInstrInfo::packetSize(), parseAMDGPUAtomicOptimizerStrategy(), parseArch(), llvm::WebAssembly::parseBlockType(), parseConstraintCode(), parseConstraintCode(), llvm::dwarf_linker::parseDebugTableName(), llvm::parseDenormalFPAttributeComponent(), parseDescriptorRange(), llvm::MachO::TextAPIWriter::parseFileType(), llvm::remarks::parseFormat(), llvm::WebAssembly::parseMVT(), parseNamePrefix(), parseOptLevel(), parsePredicateConstraint(), parseReducedGprConstraint(), parseRootSignatureElement(), llvm::LoongArch::parseSpecifier(), llvm::Sparc::parseSpecifier(), llvm::RISCV::parseSpecifierName(), llvm::RISCV::parseTuneCPU(), llvm::remarks::YAMLRemarkParser::parseType(), llvm::WebAssembly::parseType(), parseVectorKind(), parseVendor(), llvm::SymbolRemappingReader::read(), shouldUpgradeNVPTXBF16Intrinsic(), shouldUpgradeNVPTXSharedClusterIntrinsic(), shouldUpgradeNVPTXTMAG2SIntrinsics(), llvm::LPAC::stringToLanaiAluCode(), llvm::RISCVFPRndMode::stringToRoundingMode(), llvm::RISCVVXRndMode::stringToRoundingMode(), llvm::stringToVEFCondCode(), llvm::stringToVEICondCode(), llvm::stringToVERD(), upgradeAArch64IntrinsicCall(), upgradeArmOrAarch64IntrinsicFunction(), upgradeIntrinsicFunction1(), and upgradeX86IntrinsicFunction().
CaseLower()
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::CaseLower (StringLiteral S, T Value) inline
Definition at line 139 of file StringSwitch.h.
References StringSwitch(), and T.
Cases() [1/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, StringLiteral S9, T Value) inline
Definition at line 131 of file StringSwitch.h.
References S1, S8, StringSwitch(), and T.
Cases() [2/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, T Value) inline
Definition at line 124 of file StringSwitch.h.
References S1, S8, StringSwitch(), and T.
Cases() [3/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, T Value) inline
Definition at line 118 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Cases() [4/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, T Value) inline
Definition at line 112 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Cases() [5/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, T Value) inline
Definition at line 106 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Cases() [6/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value) inline
Definition at line 101 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Cases() [7/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value) inline
Definition at line 96 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Cases() [8/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value) inline
Definition at line 91 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Cases() [9/9]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, T Value) inline
Definition at line 87 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Referenced by llvm::TargetOptions::FramePointerIsReserved(), llvm::ARM::getArchSynonym(), llvm::XCOFF::getCpuID(), llvm::ARM::getFPUSynonym(), llvm::getMachineType(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::AArch64BuildAttributes::getTypeID(), llvm::mca::RISCVLMULInstrument::isDataValid(), llvm::mca::RISCVSEWInstrument::isDataValid(), isSpecialLLVMGlobalArrayForStaticInit(), isValidInsnFormat(), MCAttrForString(), llvm::PPC::normalizeCPUName(), parseAMDGPUAtomicOptimizerStrategy(), parseArch(), llvm::parseDenormalFPAttributeComponent(), llvm::remarks::parseFormat(), llvm::WebAssembly::parseType(), llvm::Triple::Triple(), upgradeArmOrAarch64IntrinsicFunction(), and upgradeIntrinsicFunction1().
CasesLower() [1/4]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value) inline
Definition at line 172 of file StringSwitch.h.
References S1, StringSwitch(), and T.
CasesLower() [2/4]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value) inline
Definition at line 167 of file StringSwitch.h.
References S1, StringSwitch(), and T.
CasesLower() [3/4]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value) inline
Definition at line 162 of file StringSwitch.h.
References S1, StringSwitch(), and T.
CasesLower() [4/4]
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, T Value) inline
Definition at line 158 of file StringSwitch.h.
References S1, StringSwitch(), and T.
Default()
template<typename T, typename R = T> R llvm::StringSwitch< T, R >::Default (T Value) inline nodiscard
Definition at line 177 of file StringSwitch.h.
References T.
Referenced by llvm::AArch64StringToVectorLayout(), llvm::ARMCondCodeFromString(), llvm::ARMVectorCondCodeFromString(), llvm::classifyEHPersonality(), llvm::ELF::convertArchNameToEMachine(), llvm::ELF::convertNameToOSABI(), llvm::convertStrToExceptionBehavior(), llvm::convertStrToRoundingMode(), llvm::MachO::Target::create(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getAccessQualifier(), llvm::MachO::getArchitectureFromName(), llvm::ARM::getArchSynonym(), llvm::Triple::getArchTypeForLLVMName(), llvm::dwarf::getAttributeEncoding(), llvm::Attribute::getAttrKindFromName(), llvm::dwarf::getCallingConvention(), llvm::DIFile::getChecksumKind(), llvm::Hexagon::getCpu(), llvm::XCOFF::getCpuID(), llvm::ARM::getDefaultExtensions(), llvm::CSKY::getDefaultExtensions(), llvm::ARM::getDefaultFPU(), llvm::DWARFYAML::getDWARFEmitterByName(), llvm::DICompileUnit::getEmissionKind(), llvm::dwarf::getEnumKind(), llvm::AArch64BuildAttributes::getFeatureAndBitsTagsID(), llvm::DIFixedPointType::getFixedPointKind(), llvm::ARMAsmBackendELF::getFixupKind(), llvm::AVRAsmBackend::getFixupKind(), llvm::LoongArchAsmBackend::getFixupKind(), llvm::MipsAsmBackend::getFixupKind(), llvm::RISCVAsmBackend::getFixupKind(), llvm::DINode::getFlag(), llvm::DISubprogram::getFlag(), getFPPredicateFromMD(), llvm::ARM::getFPUSynonym(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForPowerPC(), llvm::sys::detail::getHostCPUNameForRISCV(), getHWDivSynonym(), getIdentifierKind(), llvm::object::getImageKind(), llvm::M68kTargetLowering::getInlineAsmMemConstraint(), llvm::RISCVMachineFunctionInfo::getInterruptStackKind(), getIntPredicateFromMD(), llvm::dwarf::getLanguage(), getLlvmUserOperationEncoding(), llvm::getMachineType(), llvm::dwarf::getMacinfo(), llvm::dwarf::getMacro(), getMClassFlagsMask(), getMetadataKeywordKind(), llvm::DICompileUnit::getNameTableKind(), llvm::object::getOffloadKind(), llvm::omp::getOpenMPContextTraitPropertyForSelector(), llvm::omp::getOpenMPContextTraitSelectorKind(), llvm::omp::getOpenMPContextTraitSetKind(), llvm::dwarf::getOperationEncoding(), llvm::AArch64BuildAttributes::getOptionalID(), llvm::AArch64BuildAttributes::getPauthABITagsID(), llvm::MachO::getPlatformFromName(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::AVRTargetLowering::getRegisterByName(), llvm::HexagonTargetLowering::getRegisterByName(), llvm::LanaiTargetLowering::getRegisterByName(), llvm::MipsTargetLowering::getRegisterByName(), llvm::SITargetLowering::getRegisterByName(), llvm::SparcTargetLowering::getRegisterByName(), llvm::SystemZTargetLowering::getRegisterByName(), llvm::VETargetLowering::getRegisterByName(), llvm::X86TargetLowering::getRegisterByName(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), getSpecialRegForName(), llvm::dwarf::getTag(), llvm::LoongArchABI::getTargetABI(), llvm::RISCVABI::getTargetABI(), llvm::AArch64BuildAttributes::getTypeID(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getValueKind(), llvm::AArch64BuildAttributes::getVendorID(), llvm::VFABI::getVFParamKindFromString(), llvm::dwarf::getVirtuality(), llvm::yaml::ScalarTraits< IFSBitWidthType >::input(), llvm::yaml::ScalarTraits< IFSEndiannessType >::input(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), llvm::mca::RISCVLMULInstrument::isDataValid(), llvm::mca::RISCVSEWInstrument::isDataValid(), llvm::Attribute::isExistingAttribute(), isSMEABIRoutineCall(), isSpecialLLVMGlobalArrayForStaticInit(), isSpecialLLVMGlobalArrayToSkip(), isValidInsnFormat(), llvm::object::Lexer::lex(), llvm::remarks::magicToFormat(), llvm::object::COFFObjectFile::mapDebugSectionName(), llvm::object::MachOObjectFile::mapDebugSectionName(), llvm::object::XCOFFObjectFile::mapDebugSectionName(), llvm::object::MachOObjectFile::mapReflectionSectionNameToEnumValue(), matchMatrixRegName(), matchMatrixTileListRegName(), MatchNeonVectorRegName(), matchSVEDataVectorRegName(), matchSVEPredicateAsCounterRegName(), matchSVEPredicateVectorRegName(), MaybePredicatedInst(), MCAttrForString(), llvm::MCLOHNameToId(), llvm::PPC::normalizeCPUName(), llvm::HexagonMCInstrInfo::packetSize(), parseAMDGPUAtomicOptimizerStrategy(), parseArch(), llvm::ARM::parseArchISA(), llvm::WebAssembly::parseBlockType(), parseConstraintCode(), parseConstraintCode(), llvm::dwarf_linker::parseDebugTableName(), llvm::parseDenormalFPAttributeComponent(), parseDescriptorRange(), parseEnvironment(), llvm::MachO::TextAPIWriter::parseFileType(), llvm::remarks::parseFormat(), parseFormat(), llvm::WebAssembly::parseMVT(), parseNamePrefix(), parseOptLevel(), parseOS(), llvm::dxbc::parsePartType(), parsePredicateConstraint(), parseReducedGprConstraint(), parseRootSignatureElement(), llvm::LoongArch::parseSpecifier(), llvm::Sparc::parseSpecifier(), llvm::RISCV::parseSpecifierName(), parseSubArch(), parseThunkName(), llvm::RISCV::parseTuneCPU(), llvm::remarks::YAMLRemarkParser::parseType(), llvm::WebAssembly::parseType(), parseVendor(), llvm::SymbolRemappingReader::read(), shouldUpgradeNVPTXBF16Intrinsic(), shouldUpgradeNVPTXSharedClusterIntrinsic(), shouldUpgradeNVPTXTMAG2SIntrinsics(), SizeForSuffix(), llvm::LPAC::stringToLanaiAluCode(), llvm::RISCVFPRndMode::stringToRoundingMode(), llvm::RISCVVXRndMode::stringToRoundingMode(), llvm::stringToVEFCondCode(), llvm::stringToVEICondCode(), llvm::stringToVERD(), llvm::LPCC::suffixToLanaiCondCode(), llvm::Triple::Triple(), upgradeAArch64IntrinsicCall(), upgradeArmOrAarch64IntrinsicFunction(), llvm::UpgradeIntrinsicCall(), upgradeIntrinsicFunction1(), and upgradeX86IntrinsicFunction().
EndsWith()
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::EndsWith (StringLiteral S, T Value) inline
Definition at line 73 of file StringSwitch.h.
References StringSwitch(), and T.
Referenced by llvm::generateKernelClockInst(), parseFormat(), parseSubArch(), SizeForSuffix(), and llvm::LPCC::suffixToLanaiCondCode().
EndsWithLower()
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::EndsWithLower (StringLiteral S, T Value) inline
Definition at line 144 of file StringSwitch.h.
References StringSwitch(), and T.
operator R()
template<typename T, typename R = T> llvm::StringSwitch< T, R >::operator R () inline nodiscard
Definition at line 183 of file StringSwitch.h.
References assert().
operator=() [1/2]
template<typename T, typename R = T> void llvm::StringSwitch< T, R >::operator= (const StringSwitch< T, R > &) delete
References StringSwitch().
operator=() [2/2]
template<typename T, typename R = T> void llvm::StringSwitch< T, R >::operator= (StringSwitch< T, R > && other) delete
References StringSwitch().
StartsWith()
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::StartsWith (StringLiteral S, T Value) inline
Definition at line 80 of file StringSwitch.h.
References StringSwitch(), and T.
Referenced by llvm::ELF::convertNameToOSABI(), llvm::Triple::getArchTypeForLLVMName(), llvm::remarks::magicToFormat(), MaybePredicatedInst(), parseArch(), llvm::ARM::parseArchISA(), parseEnvironment(), parseOS(), parseThunkName(), llvm::Triple::Triple(), upgradeAMDGCNIntrinsicCall(), upgradeArmOrAarch64IntrinsicFunction(), llvm::UpgradeIntrinsicCall(), and upgradeIntrinsicFunction1().
StartsWithLower()
template<typename T, typename R = T> StringSwitch & llvm::StringSwitch< T, R >::StartsWithLower (StringLiteral S, T Value) inline
Definition at line 151 of file StringSwitch.h.
References StringSwitch(), and T.
The documentation for this class was generated from the following file:
include/llvm/ADT/StringSwitch.h