LLVM: llvm::orc::AllocGroup Class Reference
llvm::orc::AllocGroup Class Reference
A pair of memory protections and allocation policies.
#include "llvm/ExecutionEngine/Orc/Shared/MemoryFlags.h"
Public Member Functions
AllocGroup ()=default
Create a default AllocGroup.
AllocGroup (MemProt MP)
Create an AllocGroup from a MemProt only – uses MemLifetime::Standard.
AllocGroup (MemProt MP, MemLifetime MLP)
Create an AllocGroup from a MemProt and a MemLifetime.
MemProt getMemProt () const
Returns the MemProt for this group.
MemLifetime getMemLifetime () const
Returns the MemLifetime for this group.
Static Public Attributes
static constexpr unsigned NumGroups = MaxIdentifiers
Friends
struct llvm::DenseMapInfo< AllocGroup >
bool operator== (const AllocGroup &LHS, const AllocGroup &RHS)
bool operator!= (const AllocGroup &LHS, const AllocGroup &RHS)
bool operator< (const AllocGroup &LHS, const AllocGroup &RHS)
Detailed Description
A pair of memory protections and allocation policies.
Optimized for use as a small map key.
Definition at line 110 of file MemoryFlags.h.
Constructor & Destructor Documentation
AllocGroup() [1/3]
llvm::orc::AllocGroup::AllocGroup () default
Create a default AllocGroup.
No memory protections, standard lifetime policy.
Referenced by llvm::DenseMapInfo< AllocGroup >, operator!=, operator<, and operator==.
AllocGroup() [2/3]
llvm::orc::AllocGroup::AllocGroup (MemProt MP) inline
Create an AllocGroup from a MemProt only – uses MemLifetime::Standard.
Definition at line 128 of file MemoryFlags.h.
AllocGroup() [3/3]
llvm::orc::AllocGroup::AllocGroup (MemProt MP, MemLifetime MLP) inline
Create an AllocGroup from a MemProt and a MemLifetime.
Definition at line 131 of file MemoryFlags.h.
Member Function Documentation
getMemLifetime()
MemLifetime llvm::orc::AllocGroup::getMemLifetime () const inline
Returns the MemLifetime for this group.
Definition at line 141 of file MemoryFlags.h.
Referenced by llvm::DenseMapInfo< AllocGroup >, and llvm::orc::tpctypes::RemoteAllocGroup::RemoteAllocGroup().
getMemProt()
MemProt llvm::orc::AllocGroup::getMemProt () const inline
Returns the MemProt for this group.
Definition at line 136 of file MemoryFlags.h.
Referenced by llvm::DenseMapInfo< AllocGroup >.
Friends And Related Symbol Documentation
llvm::DenseMapInfo< AllocGroup >
friend struct llvm::DenseMapInfo< AllocGroup > friend
Definition at line 205 of file MemoryFlags.h.
References AllocGroup(), getMemLifetime(), and getMemProt().
operator!=
bool operator!= (const AllocGroup & LHS, const AllocGroup & RHS) friend
Definition at line 149 of file MemoryFlags.h.
References AllocGroup(), LHS, and RHS.
operator<
bool operator< (const AllocGroup & LHS, const AllocGroup & RHS) friend
Definition at line 153 of file MemoryFlags.h.
References AllocGroup(), LHS, and RHS.
operator==
bool operator== (const AllocGroup & LHS, const AllocGroup & RHS) friend
Definition at line 145 of file MemoryFlags.h.
References AllocGroup(), LHS, and RHS.
Member Data Documentation
NumGroups
unsigned llvm::orc::AllocGroup::NumGroups = MaxIdentifiers static constexpr
Definition at line 120 of file MemoryFlags.h.
Referenced by llvm::jitlink::SimpleSegmentAlloc::Create().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/MemoryFlags.h