LLVM: llvm::objcopy::elf::BasicELFBuilder Class Reference
llvm::objcopy::elf::BasicELFBuilder Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
BasicELFBuilder ()
Protected Member Functions
void initFileHeader ()
void initHeaderSegment ()
StringTableSection * addStrTab ()
SymbolTableSection * addSymTab (StringTableSection *StrTab)
Error initSections ()
Protected Attributes
std::unique_ptr< Object > Obj
Detailed Description
Definition at line 1051 of file ELFObject.h.
Constructor & Destructor Documentation
BasicELFBuilder()
llvm::objcopy::elf::BasicELFBuilder::BasicELFBuilder () inline
Definition at line 1062 of file ELFObject.h.
References Obj.
Member Function Documentation
addStrTab()
StringTableSection * BasicELFBuilder::addStrTab () protected
Definition at line 1281 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Name, and Obj.
Referenced by llvm::objcopy::elf::BinaryELFBuilder::build(), and llvm::objcopy::elf::IHexELFBuilder::build().
addSymTab()
SymbolTableSection * BasicELFBuilder::addSymTab (StringTableSection * StrTab) protected
Definition at line 1289 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Index, llvm::objcopy::elf::SectionBase::Name, and Obj.
Referenced by llvm::objcopy::elf::BinaryELFBuilder::build(), and llvm::objcopy::elf::IHexELFBuilder::build().
initFileHeader()
void BasicELFBuilder::initFileHeader () protected
Definition at line 1269 of file ELFObject.cpp.
References llvm::ELF::ELFOSABI_NONE, llvm::ELF::EM_NONE, llvm::ELF::ET_REL, and Obj.
Referenced by llvm::objcopy::elf::BinaryELFBuilder::build(), and llvm::objcopy::elf::IHexELFBuilder::build().
initHeaderSegment()
void BasicELFBuilder::initHeaderSegment () protected
Definition at line 1279 of file ELFObject.cpp.
References Obj.
Referenced by llvm::objcopy::elf::BinaryELFBuilder::build(), and llvm::objcopy::elf::IHexELFBuilder::build().
initSections()
Error BasicELFBuilder::initSections () protected
Definition at line 1302 of file ELFObject.cpp.
References llvm::objcopy::elf::Section::initialize(), Obj, and llvm::Error::success().
Referenced by llvm::objcopy::elf::BinaryELFBuilder::build(), and llvm::objcopy::elf::IHexELFBuilder::build().
Member Data Documentation
Obj
std::unique_ptr<Object> llvm::objcopy::elf::BasicELFBuilder::Obj protected
Definition at line 1053 of file ELFObject.h.
Referenced by addStrTab(), addSymTab(), BasicELFBuilder(), llvm::objcopy::elf::BinaryELFBuilder::build(), llvm::objcopy::elf::IHexELFBuilder::build(), initFileHeader(), initHeaderSegment(), and initSections().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp