LLVM: llvm::HexagonCVIResource Class Reference
llvm::HexagonCVIResource Class Reference
#include "Target/Hexagon/MCTargetDesc/HexagonShuffler.h"
Public Types
using UnitsAndLanes = std::pair<unsigned, unsigned>
Public Member Functions
HexagonCVIResource (MCInstrInfo const &MCII, MCSubtargetInfo const &STI, unsigned s, MCInst const *id)
bool isValid () const
unsigned getLanes () const
bool mayLoad () const
bool mayStore () const
Public Member Functions inherited from llvm::HexagonResource
HexagonResource (unsigned s)
void setUnits (unsigned s)
void setAllUnits ()
unsigned setWeight (unsigned s)
unsigned getUnits () const
unsigned getWeight () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::HexagonResource
static bool lessUnits (const HexagonResource &A, const HexagonResource &B)
static bool lessWeight (const HexagonResource &A, const HexagonResource &B)
Detailed Description
Definition at line 70 of file HexagonShuffler.h.
Member Typedef Documentation
UnitsAndLanes
using llvm::HexagonCVIResource::UnitsAndLanes = std::pair<unsigned, unsigned>
Definition at line 72 of file HexagonShuffler.h.
Constructor & Destructor Documentation
HexagonCVIResource()
HexagonCVIResource::HexagonCVIResource (MCInstrInfo const & MCII, MCSubtargetInfo const & STI, unsigned s, MCInst const * id)
Definition at line 108 of file HexagonShuffler.cpp.
References llvm::HexagonMCInstrInfo::getCVIResources(), llvm::HexagonMCInstrInfo::getDesc(), llvm::HexagonConvertUnits(), llvm::HexagonResource::HexagonResource(), mayLoad(), mayStore(), and llvm::HexagonResource::setUnits().
Member Function Documentation
getLanes()
unsigned llvm::HexagonCVIResource::getLanes () const inline
Definition at line 92 of file HexagonShuffler.h.
isValid()
bool llvm::HexagonCVIResource::isValid () const inline
Definition at line 91 of file HexagonShuffler.h.
mayLoad()
bool llvm::HexagonCVIResource::mayLoad () const inline
Definition at line 93 of file HexagonShuffler.h.
Referenced by HexagonCVIResource().
mayStore()
bool llvm::HexagonCVIResource::mayStore () const inline
Definition at line 94 of file HexagonShuffler.h.
Referenced by HexagonCVIResource().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonShuffler.h
lib/Target/Hexagon/MCTargetDesc/HexagonShuffler.cpp