LLVM: llvm::orc::UnwindInfoManager Class Reference
llvm::orc::UnwindInfoManager Class Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/UnwindInfoManager.h"
Classes
struct UnwindSections
Public Member Functions
UnwindInfoManager (UnwindInfoManager &&)=delete
UnwindInfoManager & operator= (UnwindInfoManager &&)=delete
LLVM_ABI ~UnwindInfoManager ()
Static Public Member Functions
static LLVM_ABI bool TryEnable ()
If the libunwind find-dynamic-unwind-info callback registration APIs are available then this method will instantiate a global UnwindInfoManager instance suitable for the process and return true.
static LLVM_ABI void addBootstrapSymbols (StringMap< ExecutorAddr > &M)
static LLVM_ABI Error registerSections (ArrayRef< orc::ExecutorAddrRange > CodeRanges, orc::ExecutorAddr DSOBase, orc::ExecutorAddrRange DWARFEHFrame, orc::ExecutorAddrRange CompactUnwind)
static LLVM_ABI Error deregisterSections (ArrayRef< orc::ExecutorAddrRange > CodeRanges)
Detailed Description
Definition at line 25 of file UnwindInfoManager.h.
Constructor & Destructor Documentation
UnwindInfoManager()
llvm::orc::UnwindInfoManager::UnwindInfoManager (UnwindInfoManager &&) delete
References UnwindInfoManager().
Referenced by operator=(), TryEnable(), and UnwindInfoManager().
~UnwindInfoManager()
llvm::orc::UnwindInfoManager::~UnwindInfoManager ()
Definition at line 62 of file UnwindInfoManager.cpp.
References llvm::dbgs(), LLVM_DEBUG, llvm::orc::RemoveFindDynamicUnwindSections, and llvm::orc::RemoveFnName.
Member Function Documentation
addBootstrapSymbols()
void llvm::orc::UnwindInfoManager::addBootstrapSymbols (StringMap< ExecutorAddr > & M) static
Definition at line 108 of file UnwindInfoManager.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm_orc_rt_alt_UnwindInfoManager_deregister(), llvm_orc_rt_alt_UnwindInfoManager_register(), llvm::orc::rt_alt::UnwindInfoManagerDeregisterActionName, and llvm::orc::rt_alt::UnwindInfoManagerRegisterActionName.
Referenced by llvm::orc::SelfExecutorProcessControl::SelfExecutorProcessControl().
deregisterSections()
Error llvm::orc::UnwindInfoManager::deregisterSections (ArrayRef< orc::ExecutorAddrRange > CodeRanges) static
Definition at line 122 of file UnwindInfoManager.cpp.
References llvm::orc::Instance.
Referenced by llvm_orc_rt_alt_UnwindInfoManager_deregister().
operator=()
UnwindInfoManager & llvm::orc::UnwindInfoManager::operator= (UnwindInfoManager &&) delete
References Info, LLVM_ABI, and UnwindInfoManager().
registerSections()
Error llvm::orc::UnwindInfoManager::registerSections (ArrayRef< orc::ExecutorAddrRange > CodeRanges, orc::ExecutorAddr DSOBase, orc::ExecutorAddrRange DWARFEHFrame, orc::ExecutorAddrRange CompactUnwind) static
Definition at line 115 of file UnwindInfoManager.cpp.
References llvm::orc::Instance.
Referenced by llvm_orc_rt_alt_UnwindInfoManager_register().
TryEnable()
bool llvm::orc::UnwindInfoManager::TryEnable () static
If the libunwind find-dynamic-unwind-info callback registration APIs are available then this method will instantiate a global UnwindInfoManager instance suitable for the process and return true.
Otherwise it will return false.
Definition at line 73 of file UnwindInfoManager.cpp.
References llvm::orc::AddFnName, llvm::dbgs(), llvm::orc::Instance, LLVM_DEBUG, llvm::orc::RemoveFindDynamicUnwindSections, llvm::orc::RemoveFnName, and UnwindInfoManager().
Referenced by llvm::orc::SelfExecutorProcessControl::SelfExecutorProcessControl().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/UnwindInfoManager.h
lib/ExecutionEngine/Orc/TargetProcess/UnwindInfoManager.cpp