LLVM: llvm::DiagnosticInfoUnsupported Class Reference
llvm::DiagnosticInfoUnsupported Class Reference
Diagnostic information for unsupported feature in backend.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoUnsupported (const Function &Fn, const Twine &Msg LLVM_LIFETIME_BOUND, const DiagnosticLocation &Loc=DiagnosticLocation(), DiagnosticSeverity Severity=DS_Error)
Fn is the function where the diagnostic is being emitted.
const Twine & getMessage () const
void print (DiagnosticPrinter &DP) const override
Print using the given DP a user-friendly message.
Public Member Functions inherited from llvm::DiagnosticInfoWithLocationBase
DiagnosticInfoWithLocationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const Function &Fn, const DiagnosticLocation &Loc)
Fn is the function where the diagnostic is being emitted.
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
std::string getLocationStr () const
Return a string with the location information for this diagnostic in the format "file:line:col".
void getLocation (StringRef &RelativePath, unsigned &Line, unsigned &Column) const
Return location information for this diagnostic in three parts: the relative source file path, line number and column.
std::string getAbsolutePath () const
Return the absolute path tot the file.
const Function & getFunction () const
DiagnosticLocation getLocation () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for unsupported feature in backend.
Definition at line 1075 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoUnsupported()
llvm::DiagnosticInfoUnsupported::DiagnosticInfoUnsupported (const Function & Fn, const Twine &Msg LLVM_LIFETIME_BOUND, const DiagnosticLocation & Loc = DiagnosticLocation(), DiagnosticSeverity Severity = DS_Error) inline
Fn is the function where the diagnostic is being emitted.
Loc is the location information to use in the diagnostic. If line table information is available, the diagnostic will include the source code location. Msg is the message to show. Note that this class does not copy this message, so this reference must be valid for the whole life time of the diagnostic.
Definition at line 1087 of file DiagnosticInfo.h.
References llvm::DiagnosticInfoWithLocationBase::DiagnosticInfoWithLocationBase(), llvm::DK_Unsupported, llvm::DS_Error, and LLVM_LIFETIME_BOUND.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoUnsupported::classof (const DiagnosticInfo * DI) inline static
Definition at line 1094 of file DiagnosticInfo.h.
References llvm::DK_Unsupported, and llvm::DiagnosticInfo::getKind().
getMessage()
const Twine & llvm::DiagnosticInfoUnsupported::getMessage () const inline
Definition at line 1098 of file DiagnosticInfo.h.
print()
void DiagnosticInfoUnsupported::print (DiagnosticPrinter & DP) const override virtual
Print using the given DP a user-friendly message.
This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implements llvm::DiagnosticInfo.
Definition at line 403 of file DiagnosticInfo.cpp.
References llvm::raw_ostream::flush(), llvm::DiagnosticInfoWithLocationBase::getFunction(), llvm::Function::getFunctionType(), llvm::DiagnosticInfoWithLocationBase::getLocationStr(), and llvm::Value::getName().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp