LLVM: llvm::object::MinidumpFile::Memory64Iterator Class Reference
llvm::object::MinidumpFile::Memory64Iterator Class Reference
Class the provides an iterator over the memory64 memory ranges.
#include "llvm/Object/Minidump.h"
Public Member Functions
bool operator== (const Memory64Iterator &R) const
bool operator!= (const Memory64Iterator &R) const
const std::pair< minidump::MemoryDescriptor_64, ArrayRef< uint8_t > > & operator* ()
const std::pair< minidump::MemoryDescriptor_64, ArrayRef< uint8_t > > * operator-> ()
Error inc ()
Static Public Member Functions
static Memory64Iterator begin (ArrayRef< uint8_t > Storage, ArrayRef< minidump::MemoryDescriptor_64 > Descriptors)
static Memory64Iterator end ()
Detailed Description
Class the provides an iterator over the memory64 memory ranges.
Only the the first descriptor is validated as readable beforehand.
Definition at line 160 of file Minidump.h.
Member Function Documentation
begin()
Memory64Iterator llvm::object::MinidumpFile::Memory64Iterator::begin (ArrayRef< uint8_t > Storage, ArrayRef< minidump::MemoryDescriptor_64 > Descriptors) inline static
Definition at line 163 of file Minidump.h.
Referenced by llvm::object::MinidumpFile::getMemory64List().
end()
Memory64Iterator llvm::object::MinidumpFile::Memory64Iterator::end () inline static
Definition at line 168 of file Minidump.h.
Referenced by llvm::object::MinidumpFile::getMemory64List().
inc()
Error llvm::object::MinidumpFile::Memory64Iterator::inc () inline
Definition at line 186 of file Minidump.h.
References llvm::minidump::MemoryDescriptor_64::DataSize, llvm::make_error(), llvm::Error::success(), llvm::ArrayRef< T >::take_front(), and llvm::object::unexpected_eof.
operator!=()
bool llvm::object::MinidumpFile::Memory64Iterator::operator!= (const Memory64Iterator & R) const inline
Definition at line 174 of file Minidump.h.
operator*()
const std::pair< minidump::MemoryDescriptor_64, ArrayRef< uint8_t > > & llvm::object::MinidumpFile::Memory64Iterator::operator* () inline
Definition at line 177 of file Minidump.h.
operator->()
const std::pair< minidump::MemoryDescriptor_64, ArrayRef< uint8_t > > * llvm::object::MinidumpFile::Memory64Iterator::operator-> () inline
Definition at line 182 of file Minidump.h.
operator==()
bool llvm::object::MinidumpFile::Memory64Iterator::operator== (const Memory64Iterator & R) const inline
Definition at line 170 of file Minidump.h.
The documentation for this class was generated from the following file:
include/llvm/Object/Minidump.h