LLVM: llvm::FMFSource Class Reference
llvm::FMFSource Class Reference
This provides a helper for copying FMF from an instruction or setting specified flags.
#include "llvm/IR/IRBuilder.h"
Public Member Functions
FMFSource ()=default
FMFSource (Instruction *Source)
FMFSource (FastMathFlags FMF)
FastMathFlags get (FastMathFlags Default) const
Static Public Member Functions
static FMFSource intersect (Value *A, Value *B)
Intersect the FMF from two instructions.
Detailed Description
This provides a helper for copying FMF from an instruction or setting specified flags.
Definition at line 93 of file IRBuilder.h.
Constructor & Destructor Documentation
FMFSource() [1/3]
llvm::FMFSource::FMFSource () default
Referenced by intersect().
FMFSource() [2/3]
llvm::FMFSource::FMFSource (Instruction * Source) inline
Definition at line 98 of file IRBuilder.h.
FMFSource() [3/3]
llvm::FMFSource::FMFSource (FastMathFlags FMF) inline
Definition at line 102 of file IRBuilder.h.
Member Function Documentation
get()
FastMathFlags llvm::FMFSource::get (FastMathFlags Default) const inline
Definition at line 103 of file IRBuilder.h.
References llvm::Default.
Referenced by llvm::IRBuilderBase::CreateBinOpFMF(), llvm::IRBuilderBase::CreateConstrainedFPBinOp(), llvm::IRBuilderBase::CreateConstrainedFPCast(), llvm::IRBuilderBase::CreateConstrainedFPIntrinsic(), llvm::IRBuilderBase::CreateConstrainedFPUnroundedBinOp(), llvm::IRBuilderBase::CreateFAddFMF(), llvm::IRBuilderBase::CreateFDivFMF(), llvm::IRBuilderBase::CreateFMulFMF(), llvm::IRBuilderBase::CreateFNegFMF(), llvm::IRBuilderBase::CreateFRemFMF(), llvm::IRBuilderBase::CreateFSubFMF(), and llvm::IRBuilderBase::CreateSelectFMF().
intersect()
FMFSource llvm::FMFSource::intersect (Value * A, Value * B) inline static
Intersect the FMF from two instructions.
Definition at line 107 of file IRBuilder.h.
References A(), B(), llvm::cast(), and FMFSource().
Referenced by matchIsFiniteTest(), reassociateFCmps(), and llvm::InstCombinerImpl::visitCallInst().
The documentation for this class was generated from the following file:
include/llvm/IR/IRBuilder.h