LLVM: llvm::VPWidenIntOrFpInductionRecipe Class Reference
llvm::VPWidenIntOrFpInductionRecipe Class Reference
A recipe for handling phi nodes of integer and floating-point inductions, producing their vector values.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenIntOrFpInductionRecipe (PHINode *IV, VPValue *Start, VPValue *Step, VPValue *VF, const InductionDescriptor &IndDesc, DebugLoc DL)
VPWidenIntOrFpInductionRecipe (PHINode *IV, VPValue *Start, VPValue *Step, VPValue *VF, const InductionDescriptor &IndDesc, TruncInst *Trunc, DebugLoc DL)
~VPWidenIntOrFpInductionRecipe () override=default
VPWidenIntOrFpInductionRecipe * clone () override
Clone the current recipe.
void execute (VPTransformState &State) override
Generate the phi nodes.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
VPValue * getVFValue ()
const VPValue * getVFValue () const
VPValue * getSplatVFValue ()
unsigned getNumIncoming () const override
Returns the number of incoming values, also number of incoming blocks.
TruncInst * getTruncInst ()
Returns the first defined value as TruncInst, if it is one or nullptr otherwise.
const TruncInst * getTruncInst () const
bool isCanonical () const
Returns true if the induction is canonical, i.e.
Type * getScalarType () const
Returns the scalar type of the induction.
VPValue * getLastUnrolledPartOperand ()
Returns the VPValue representing the value of this induction at the last unrolled part, if it exists.
Public Member Functions inherited from llvm::VPWidenInductionRecipe
VPWidenInductionRecipe (unsigned char Kind, PHINode *IV, VPValue *Start, VPValue *Step, const InductionDescriptor &IndDesc, DebugLoc DL)
VPValue * getStepValue ()
Returns the step value of the induction.
const VPValue * getStepValue () const
void setStepValue (VPValue *V)
Update the step value of the recipe.
PHINode * getPHINode () const
const InductionDescriptor & getInductionDescriptor () const
Returns the induction descriptor for the recipe.
VPValue * getBackedgeValue () override
Returns the incoming value from the loop backedge.
VPRecipeBase & getBackedgeRecipe () override
Returns the backedge value as a recipe.
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the recipe only uses the first lane of operand Op.
Public Member Functions inherited from llvm::VPHeaderPHIRecipe
~VPHeaderPHIRecipe () override=default
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Return the cost of this header phi recipe.
VPValue * getStartValue ()
Returns the start value of the phi, if one is set.
VPValue * getStartValue () const
void setStartValue (VPValue *V)
Update the start value of the recipe.
Public Member Functions inherited from llvm::VPSingleDefRecipe
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, Value *UV, DebugLoc DL={})
Instruction * getUnderlyingInstr ()
Returns the underlying instruction.
const Instruction * getUnderlyingInstr () const
LLVM_DUMP_METHOD void dump () const
Print this VPSingleDefRecipe to dbgs() (for debugging).
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
bool isScalarCast () const
Return true if the recipe is a scalar cast.
void setDebugLoc (DebugLoc NewDL)
Set the recipe's debug location to NewDL.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser () const
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isLiveIn () const
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Value * getLiveInIRValue () const
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
bool isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop.
void setUnderlyingValue (Value *Val)
Public Member Functions inherited from llvm::VPPhiAccessors
virtual ~VPPhiAccessors ()=default
VPValue * getIncomingValue (unsigned Idx) const
Returns the incoming VPValue with index Idx.
const VPBasicBlock * getIncomingBlock (unsigned Idx) const
Returns the incoming block with index Idx.
void removeIncomingValueFor (VPBlockBase *IncomingBlock) const
Removes the incoming value for IncomingBlock, which must be a predecessor.
void printPhiOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the recipe.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC , VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Static Public Member Functions inherited from llvm::VPWidenInductionRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPValue *V)
static bool classof (const VPHeaderPHIRecipe *R)
Static Public Member Functions inherited from llvm::VPHeaderPHIRecipe
static bool classof (const VPRecipeBase *B)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPValue *V)
Static Public Member Functions inherited from llvm::VPSingleDefRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::VPHeaderPHIRecipe
VPHeaderPHIRecipe (unsigned char VPDefID, Instruction *UnderlyingInstr, VPValue *Start, DebugLoc DL=DebugLoc::getUnknown())
const VPRecipeBase * getAsRecipe () const override
Return a VPRecipeBase* to the current object.
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
A recipe for handling phi nodes of integer and floating-point inductions, producing their vector values.
This is an abstract recipe and must be converted to concrete recipes before executing.
Definition at line 2008 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenIntOrFpInductionRecipe() [1/2]
llvm::VPWidenIntOrFpInductionRecipe::VPWidenIntOrFpInductionRecipe (PHINode * IV, VPValue * Start, VPValue * Step, VPValue * VF, const InductionDescriptor & IndDesc, DebugLoc DL) inline
Definition at line 2015 of file VPlan.h.
References addOperand(), DL, IV, and llvm::VPWidenInductionRecipe::VPWidenInductionRecipe().
Referenced by clone().
VPWidenIntOrFpInductionRecipe() [2/2]
llvm::VPWidenIntOrFpInductionRecipe::VPWidenIntOrFpInductionRecipe (PHINode * IV, VPValue * Start, VPValue * Step, VPValue * VF, const InductionDescriptor & IndDesc, TruncInst * Trunc, DebugLoc DL) inline
Definition at line 2024 of file VPlan.h.
References addOperand(), assert(), DL, llvm::getMetadataToPropagate(), IV, and llvm::VPWidenInductionRecipe::VPWidenInductionRecipe().
~VPWidenIntOrFpInductionRecipe()
llvm::VPWidenIntOrFpInductionRecipe::~VPWidenIntOrFpInductionRecipe () override default
Member Function Documentation
clone()
VPWidenIntOrFpInductionRecipe * llvm::VPWidenIntOrFpInductionRecipe::clone () inline override virtual
Clone the current recipe.
Implements llvm::VPSingleDefRecipe.
Definition at line 2040 of file VPlan.h.
References llvm::VPRecipeBase::getDebugLoc(), llvm::VPWidenInductionRecipe::getInductionDescriptor(), llvm::VPWidenInductionRecipe::getPHINode(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPWidenInductionRecipe::getStepValue(), getVFValue(), and VPWidenIntOrFpInductionRecipe().
execute()
void llvm::VPWidenIntOrFpInductionRecipe::execute (VPTransformState & State) inline override virtual
Generate the phi nodes.
Implements llvm::VPWidenInductionRecipe.
Definition at line 2048 of file VPlan.h.
References execute(), and llvm_unreachable.
Referenced by execute().
getLastUnrolledPartOperand()
VPValue * llvm::VPWidenIntOrFpInductionRecipe::getLastUnrolledPartOperand () inline
Returns the VPValue representing the value of this induction at the last unrolled part, if it exists.
Returns itself if unrolling did not take place.
Definition at line 2092 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
Referenced by expandVPWidenIntOrFpInduction().
getNumIncoming()
unsigned llvm::VPWidenIntOrFpInductionRecipe::getNumIncoming () const inline override virtual
Returns the number of incoming values, also number of incoming blocks.
Note that at the moment, VPWidenIntOrFpInductionRecipes only have a single incoming value, its start value.
Reimplemented from llvm::VPWidenInductionRecipe.
Definition at line 2071 of file VPlan.h.
getScalarType()
Type * llvm::VPWidenIntOrFpInductionRecipe::getScalarType () const inline
Returns the scalar type of the induction.
Definition at line 2084 of file VPlan.h.
References llvm::VPValue::getLiveInIRValue(), llvm::VPHeaderPHIRecipe::getStartValue(), and llvm::Value::getType().
Referenced by isCanonical().
getSplatVFValue()
VPValue * llvm::VPWidenIntOrFpInductionRecipe::getSplatVFValue () inline
Definition at line 2062 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
Referenced by expandVPWidenIntOrFpInduction().
getTruncInst() [1/2]
TruncInst * llvm::VPWidenIntOrFpInductionRecipe::getTruncInst () inline
Returns the first defined value as TruncInst, if it is one or nullptr otherwise.
Definition at line 2075 of file VPlan.h.
Referenced by print().
getTruncInst() [2/2]
const TruncInst * llvm::VPWidenIntOrFpInductionRecipe::getTruncInst () const inline
Definition at line 2076 of file VPlan.h.
getVFValue() [1/2]
VPValue * llvm::VPWidenIntOrFpInductionRecipe::getVFValue () inline
Definition at line 2059 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by clone(), and expandVPWidenIntOrFpInduction().
getVFValue() [2/2]
const VPValue * llvm::VPWidenIntOrFpInductionRecipe::getVFValue () const inline
Definition at line 2060 of file VPlan.h.
References llvm::VPUser::getOperand().
isCanonical()
bool VPWidenIntOrFpInductionRecipe::isCanonical () const
Returns true if the induction is canonical, i.e.
starting at 0 and incremented by UF * VF (= the original IV is incremented by 1) and has the same type as the canonical induction.
Definition at line 2134 of file VPlanRecipes.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::VPValue::getDefiningRecipe(), llvm::VPValue::getLiveInIRValue(), getParent(), getScalarType(), llvm::VPHeaderPHIRecipe::getStartValue(), and llvm::VPWidenInductionRecipe::getStepValue().
print()
void VPWidenIntOrFpInductionRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPHeaderPHIRecipe.
Definition at line 2122 of file VPlanRecipes.cpp.
References getTruncInst(), llvm::VPValue::printAsOperand(), and llvm::VPUser::printOperands().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp