LLVM: llvm::DiagnosticInfoStackSize Class Reference
llvm::DiagnosticInfoStackSize Class Reference
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoStackSize (const Function &Fn, uint64_t StackSize, uint64_t StackLimit, DiagnosticSeverity Severity=DS_Warning)
uint64_t getStackSize () const
uint64_t getStackLimit () const
Public Member Functions inherited from llvm::DiagnosticInfoResourceLimit
DiagnosticInfoResourceLimit (const Function &Fn, const char *ResourceName, uint64_t ResourceSize, uint64_t ResourceLimit, DiagnosticSeverity Severity=DS_Warning, DiagnosticKind Kind=DK_ResourceLimit)
The function that is concerned by this stack size diagnostic.
const Function & getFunction () const
const char * getResourceName () const
uint64_t getResourceSize () const
uint64_t getResourceLimit () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfoWithLocationBase
DiagnosticInfoWithLocationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const Function &Fn, const DiagnosticLocation &Loc)
Fn is the function where the diagnostic is being emitted.
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
std::string getLocationStr () const
Return a string with the location information for this diagnostic in the format "file:line:col".
void getLocation (StringRef &RelativePath, unsigned &Line, unsigned &Column) const
Return location information for this diagnostic in three parts: the relative source file path, line number and column.
std::string getAbsolutePath () const
Return the absolute path tot the file.
const Function & getFunction () const
DiagnosticLocation getLocation () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Static Public Member Functions inherited from llvm::DiagnosticInfoResourceLimit
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Definition at line 477 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoStackSize()
llvm::DiagnosticInfoStackSize::DiagnosticInfoStackSize (const Function & Fn, uint64_t StackSize, uint64_t StackLimit, DiagnosticSeverity Severity = DS_Warning) inline
Definition at line 481 of file DiagnosticInfo.h.
References llvm::DiagnosticInfoResourceLimit::DiagnosticInfoResourceLimit(), llvm::DK_StackSize, and llvm::DS_Warning.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoStackSize::classof (const DiagnosticInfo * DI) inline static
Definition at line 490 of file DiagnosticInfo.h.
References llvm::DK_StackSize, and llvm::DiagnosticInfo::getKind().
getStackLimit()
uint64_t llvm::DiagnosticInfoStackSize::getStackLimit () const inline
Definition at line 488 of file DiagnosticInfo.h.
References llvm::DiagnosticInfoResourceLimit::getResourceLimit().
getStackSize()
uint64_t llvm::DiagnosticInfoStackSize::getStackSize () const inline
Definition at line 487 of file DiagnosticInfo.h.
References llvm::DiagnosticInfoResourceLimit::getResourceSize().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp