LLVM: llvm::support::detail::HelperFunctions Class Reference
llvm::support::detail::HelperFunctions Class Reference
#include "llvm/Support/FormatProviders.h"
Static Protected Member Functions
static std::optional< size_t > parseNumericPrecision (StringRef Str)
static std::optional< HexPrintStyle > consumeHexStyle (StringRef &Str)
static size_t consumeNumHexDigits (StringRef &Str, HexPrintStyle Style, size_t Default)
Detailed Description
Definition at line 62 of file FormatProviders.h.
Member Function Documentation
consumeHexStyle()
std::optional< HexPrintStyle > llvm::support::detail::HelperFunctions::consumeHexStyle (StringRef & Str) inline static protected
Definition at line 79 of file FormatProviders.h.
References llvm::Lower, llvm::PrefixLower, llvm::PrefixUpper, and llvm::Upper.
Referenced by llvm::format_provider< T, std::enable_if_t< support::detail::use_integral_formatter< T >::value > >::format(), and llvm::format_provider< T, std::enable_if_t< support::detail::use_pointer_formatter< T >::value > >::format().
consumeNumHexDigits()
size_t llvm::support::detail::HelperFunctions::consumeNumHexDigits (StringRef & Str, HexPrintStyle Style, size_t Default) inline static protected
Definition at line 94 of file FormatProviders.h.
References llvm::Default, and llvm::isPrefixedHexStyle().
Referenced by llvm::format_provider< T, std::enable_if_t< support::detail::use_integral_formatter< T >::value > >::format(), and llvm::format_provider< T, std::enable_if_t< support::detail::use_pointer_formatter< T >::value > >::format().
parseNumericPrecision()
std::optional< size_t > llvm::support::detail::HelperFunctions::parseNumericPrecision (StringRef Str) inline static protected
Definition at line 64 of file FormatProviders.h.
References assert().
Referenced by llvm::format_provider< T, std::enable_if_t< support::detail::use_double_formatter< T >::value > >::format().
The documentation for this class was generated from the following file:
include/llvm/Support/FormatProviders.h