LLVM: llvm::TargetIRAnalysis Class Reference
llvm::TargetIRAnalysis Class Reference
Analysis pass providing the TargetTransformInfo.
#include "llvm/Analysis/TargetTransformInfo.h"
Public Types
typedef TargetTransformInfo Result
Public Member Functions
LLVM_ABI TargetIRAnalysis ()
Default construct a target IR analysis.
LLVM_ABI TargetIRAnalysis (std::function< Result(const Function &)> TTICallback)
Construct an IR analysis pass around a target-provide callback.
TargetIRAnalysis (const TargetIRAnalysis &Arg)
TargetIRAnalysis (TargetIRAnalysis &&Arg)
TargetIRAnalysis & operator= (const TargetIRAnalysis &RHS)
TargetIRAnalysis & operator= (TargetIRAnalysis &&RHS)
LLVM_ABI Result run (const Function &F, FunctionAnalysisManager &)
Public Member Functions inherited from llvm::PassInfoMixin< TargetIRAnalysis >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< TargetIRAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< TargetIRAnalysis >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Analysis pass providing the TargetTransformInfo.
The core idea of the TargetIRAnalysis is to expose an interface through which LLVM targets can analyze and provide information about the middle end's target-independent IR. This supports use cases such as target-aware cost modeling of IR constructs.
This is a function analysis because much of the cost modeling for targets is done in a subtarget specific way and LLVM supports compiling different functions targeting different subtargets in order to support runtime dispatch according to the observed subtarget.
Definition at line 1968 of file TargetTransformInfo.h.
Member Typedef Documentation
Result
typedef TargetTransformInfo llvm::TargetIRAnalysis::Result
Definition at line 1970 of file TargetTransformInfo.h.
Constructor & Destructor Documentation
TargetIRAnalysis() [1/4]
TargetIRAnalysis::TargetIRAnalysis ()
Default construct a target IR analysis.
This will use the module's datalayout to construct a baseline conservative TTI result.
Definition at line 1491 of file TargetTransformInfo.cpp.
Referenced by operator=(), operator=(), TargetIRAnalysis(), and TargetIRAnalysis().
TargetIRAnalysis() [2/4]
TargetIRAnalysis::TargetIRAnalysis (std::function< Result(const Function &)> TTICallback)
Construct an IR analysis pass around a target-provide callback.
The callback will be called with a particular function for which the TTI is needed and must return a TTI object for that function.
Definition at line 1493 of file TargetTransformInfo.cpp.
References llvm::move().
TargetIRAnalysis() [3/4]
llvm::TargetIRAnalysis::TargetIRAnalysis (const TargetIRAnalysis & Arg) inline
Definition at line 1986 of file TargetTransformInfo.h.
References TargetIRAnalysis().
TargetIRAnalysis() [4/4]
llvm::TargetIRAnalysis::TargetIRAnalysis (TargetIRAnalysis && Arg) inline
Definition at line 1988 of file TargetTransformInfo.h.
References llvm::move(), and TargetIRAnalysis().
Member Function Documentation
operator=() [1/2]
TargetIRAnalysis & llvm::TargetIRAnalysis::operator= (const TargetIRAnalysis & RHS) inline
Definition at line 1990 of file TargetTransformInfo.h.
References RHS, and TargetIRAnalysis().
operator=() [2/2]
TargetIRAnalysis & llvm::TargetIRAnalysis::operator= (TargetIRAnalysis && RHS) inline
Definition at line 1994 of file TargetTransformInfo.h.
References RHS, and TargetIRAnalysis().
run()
TargetIRAnalysis::Result TargetIRAnalysis::run (const Function & F, FunctionAnalysisManager &)
Definition at line 1497 of file TargetTransformInfo.cpp.
References assert(), and F.
Referenced by computeHeuristicUnrollFactor(), and llvm::AMDGPUUnifyDivergentExitNodesPass::run().
The documentation for this class was generated from the following files:
include/llvm/Analysis/TargetTransformInfo.h
lib/Analysis/TargetTransformInfo.cpp