LLVM: llvm::ModuleInlinerPass Class Reference
llvm::ModuleInlinerPass Class Reference
The module inliner pass for the new pass manager.
#include "llvm/Transforms/IPO/ModuleInliner.h"
Public Member Functions
ModuleInlinerPass (InlineParams Params=getInlineParams(), InliningAdvisorMode Mode=InliningAdvisorMode::Default, ThinOrFullLTOPhase LTOPhase=ThinOrFullLTOPhase::None)
ModuleInlinerPass (ModuleInlinerPass &&Arg)=default
LLVM_ABI PreservedAnalyses run (Module &, ModuleAnalysisManager &)
Public Member Functions inherited from llvm::PassInfoMixin< ModuleInlinerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ModuleInlinerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The module inliner pass for the new pass manager.
This pass wires together the inlining utilities and the inline cost analysis into a module pass. Different from SCC inliner, it considers every call in every function in the whole module and tries to inline if profitable. With this module level inliner, it is possible to evaluate more heuristics in the module level such like PriorityInlineOrder. It can be tuned with a number of parameters to control what cost model is used and what tradeoffs are made when making the decision.
Definition at line 28 of file ModuleInliner.h.
Constructor & Destructor Documentation
ModuleInlinerPass() [1/2]
llvm::ModuleInlinerPass::ModuleInlinerPass (InlineParams Params = getInlineParams(), InliningAdvisorMode Mode = InliningAdvisorMode::Default, ThinOrFullLTOPhase LTOPhase = ThinOrFullLTOPhase::None) inline
Definition at line 30 of file ModuleInliner.h.
References llvm::Default, and llvm::None.
Referenced by ModuleInlinerPass().
ModuleInlinerPass() [2/2]
llvm::ModuleInlinerPass::ModuleInlinerPass (ModuleInlinerPass && Arg) default
References FAM, LLVM_ABI, MAM, and ModuleInlinerPass().
Member Function Documentation
run()
PreservedAnalyses ModuleInlinerPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 111 of file ModuleInliner.cpp.
References llvm::PreservedAnalyses::all(), assert(), Call, Changed, llvm::CtxProfAnalysis::collectIndirectCallPromotionList(), CtxProfPromoteAlwaysInline, llvm::dbgs(), DEBUG_TYPE, llvm::dyn_cast(), F, FAM, llvm::InlineAdvisor::getAdvice(), llvm::CallBase::getCalledFunction(), llvm::CallBase::getCaller(), llvm::getInlineOrder(), I, llvm::InlineFunctionInfo::InlinedCallSites, llvm::InlineFunction(), inlineHistoryIncludes(), instructions, IR, llvm::is_contained(), llvm::isa(), llvm::GlobalValue::isDeclaration(), isKnownLibFunction(), LLVM_DEBUG, llvm::make_scope_exit(), MAM, llvm::PreservedAnalyses::none(), llvm::InlineAdvisor::onPassEntry(), llvm::InlineAdvisor::onPassExit(), P, llvm::promoteCallWithIfThenElse(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), llvm::setInlineRemark(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::tryPromoteCall().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/ModuleInliner.h
lib/Transforms/IPO/ModuleInliner.cpp