LLVM: llvm::support::detail::ErrorAdapter Class Reference
llvm::support::detail::ErrorAdapter Class Reference
#include "llvm/Support/FormatAdapters.h"
Public Member Functions
ErrorAdapter (Error &&Item)
ErrorAdapter (ErrorAdapter &&)=default
~ErrorAdapter ()
void format (llvm::raw_ostream &Stream, StringRef Style) override
Additional Inherited Members
Protected Member Functions inherited from llvm::FormatAdapter< Error >
FormatAdapter (Error &&Item)
Protected Member Functions inherited from llvm::support::detail::format_adapter
virtual ~format_adapter ()=default
Protected Attributes inherited from llvm::FormatAdapter< Error >
Error Item
Detailed Description
Definition at line 76 of file FormatAdapters.h.
Constructor & Destructor Documentation
ErrorAdapter() [1/2]
llvm::support::detail::ErrorAdapter::ErrorAdapter (Error && Item) inline
Definition at line 78 of file FormatAdapters.h.
References llvm::FormatAdapter< Error >::FormatAdapter(), llvm::FormatAdapter< Error >::Item, and llvm::move().
Referenced by ErrorAdapter().
ErrorAdapter() [2/2]
llvm::support::detail::ErrorAdapter::ErrorAdapter (ErrorAdapter &&) default
References ErrorAdapter().
~ErrorAdapter()
llvm::support::detail::ErrorAdapter::~ErrorAdapter () inline
Definition at line 80 of file FormatAdapters.h.
References llvm::consumeError(), and llvm::FormatAdapter< Error >::Item.
Member Function Documentation
format()
void llvm::support::detail::ErrorAdapter::format (llvm::raw_ostream & Stream, StringRef Style) inline override virtual
Implements llvm::support::detail::format_adapter.
Definition at line 81 of file FormatAdapters.h.
References llvm::FormatAdapter< Error >::Item.
The documentation for this class was generated from the following file:
include/llvm/Support/FormatAdapters.h