LLVM: llvm::Constant Class Reference
llvm::Constant Class Reference
This is an important base class in LLVM.
#include "llvm/IR/Constant.h"
Public Member Functions
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
LLVM_ABI bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
LLVM_ABI bool isOneValue () const
Returns true if the value is one.
LLVM_ABI bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
LLVM_ABI bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
LLVM_ABI bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
LLVM_ABI bool isZeroValue () const
Return true if the value is negative zero or null value.
LLVM_ABI bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
LLVM_ABI bool isMinSignedValue () const
Return true if the value is the smallest signed value.
LLVM_ABI bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a fixed width vector constant with all finite and non-zero elements.
LLVM_ABI bool isNormalFP () const
Return true if this is a normal (as opposed to denormal, infinity, nan, or zero) floating-point scalar constant or a vector constant with all normal elements.
LLVM_ABI bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
LLVM_ABI bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
LLVM_ABI bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
LLVM_ABI bool containsUndefOrPoisonElement () const
Return true if this is a vector constant that includes any undef or poison elements.
LLVM_ABI bool containsPoisonElement () const
Return true if this is a vector constant that includes any poison elements.
LLVM_ABI bool containsUndefElement () const
Return true if this is a vector constant that includes any strictly undef (not poison) elements.
LLVM_ABI bool containsConstantExpression () const
Return true if this is a fixed width vector constant that includes any constant expressions.
LLVM_ABI bool isThreadDependent () const
Return true if the value can vary between threads.
LLVM_ABI bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
LLVM_ABI bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
LLVM_ABI bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry (either static or dynamic).
LLVM_ABI bool needsDynamicRelocation () const
LLVM_ABI Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
LLVM_ABI Constant * getAggregateElement (Constant *Elt) const
LLVM_ABI Constant * getSplatValue (bool AllowPoison=false) const
If all elements of the vector constant have the same value, return that value.
LLVM_ABI const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
LLVM_ABI ConstantRange toConstantRange () const
Convert constant to an approximate constant range.
LLVM_ABI void destroyConstant ()
Called if some element of this constant is no longer valid.
LLVM_ABI void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
LLVM_ABI void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
LLVM_ABI bool hasOneLiveUse () const
Return true if the constant has exactly one live use.
LLVM_ABI bool hasZeroLiveUses () const
Return true if the constant has no live uses.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
LLVM_ABI bool isManifestConstant () const
Return true if a constant is ConstantData or a ConstantAggregate or ConstantExpr that contain only ConstantData.
Public Member Functions inherited from llvm::User
User (const User &)=delete
LLVM_ABI void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, HungOffOperandsAllocMarker)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, IntrusiveOperandsAllocMarker)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, IntrusiveOperandsAndDescriptorAllocMarker)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
LLVM_ABI ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
LLVM_ABI MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
LLVM_ABI bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
LLVM_ABI bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
LLVM_ABI void deleteValue ()
Delete a pointer to a generic Value.
LLVM_ABI void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVM_ABI LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
LLVM_ABI ValueName * getValueName () const
LLVM_ABI void setValueName (ValueName *VN)
LLVM_ABI StringRef getName () const
Return a constant reference to the value's name.
LLVM_ABI void setName (const Twine &Name)
Change the name of the value.
LLVM_ABI void takeName (Value *V)
Transfer the name from V to this value.
LLVM_ABI std::string getNameOrAsOperand () const
LLVM_ABI void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
LLVM_ABI void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
LLVM_ABI void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
LLVM_ABI void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
LLVM_ABI void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool hasUseList () const
Check if this Value has a use-list.
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
LLVM_ABI bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
LLVM_ABI bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI bool hasOneUser () const
Return true if there is exactly one user of this value.
LLVM_ABI Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
LLVM_ABI User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
LLVM_ABI bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
LLVM_ABI bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
LLVM_ABI void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
LLVM_ABI bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
LLVM_ABI unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
LLVM_ABI bool isSwiftError () const
Return true if this value is a swifterror value.
LLVM_ABI const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
LLVM_ABI const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
LLVM_ABI const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
LLVM_ABI const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
LLVM_ABI const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
LLVM_ABI const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
LLVM_ABI const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
LLVM_ABI std::optional< int64_t > getPointerOffsetFrom (const Value *Other, const DataLayout &DL) const
If this ptr is provably equal to Other plus a constant offset, return that offset in bytes.
LLVM_ABI bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
LLVM_ABI uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
LLVM_ABI Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
LLVM_ABI const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
LLVM_ABI void reverseUseList ()
Reverse the use-list.
LLVM_ABI void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
LLVM_ABI void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Value *V)
static LLVM_ABI Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static LLVM_ABI Constant * getAllOnesValue (Type *Ty)
static LLVM_ABI Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static LLVM_ABI Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
static LLVM_ABI Constant * mergeUndefsWith (Constant *C, Constant *Other)
Merges undefs of a Constant with another Constant, along with the undefs already present.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static LLVM_ABI void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
Constant (Type *ty, ValueTy vty, AllocInfo AllocInfo)
~Constant ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)=delete
LLVM_ABI void * operator new (size_t Size, HungOffOperandsAllocMarker)
Allocate a User with an operand pointer co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAndDescriptorAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, AllocInfo AllocInfo)
LLVM_ABI void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
LLVM_ABI void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
LLVM_ABI Value (Type *Ty, unsigned scid)
LLVM_ABI ~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
LLVM_ABI void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
LLVM_ABI bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
LLVM_ABI void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata attachments matching the given predicate.
LLVM_ABI void clearMetadata ()
Erase all metadata attached to this Value.
LLVM_ABI MDNode * getMetadataImpl (unsigned KindID) const
Get metadata for the given kind, if any.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
LLVM_ABI MDNode * getMetadata (StringRef Kind) const
LLVM_ABI void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
LLVM_ABI void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
LLVM_ABI void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
LLVM_ABI void setMetadata (StringRef Kind, MDNode *Node)
LLVM_ABI void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
LLVM_ABI void addMetadata (StringRef Kind, MDNode &MD)
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This is an important base class in LLVM.
It provides the common facilities of all constant values in an LLVM program. A constant is a value that is immutable at runtime. Functions are constants because their address is immutable. Same with global variables.
All constants share the capabilities provided in this class. All constants can have a null value. They can have an operand list. Constants can be simple (integer and floating point values), complex (arrays and structures), or expression based (computations yielding a constant value composed of only certain operators and other constant values).
Note that Constants are immutable (once created they never change) and are fully shared by structural equivalence. This means that two structurally equivalent constants will always have the same address. Constants are created on demand as needed and never deleted: thus clients don't have to worry about the lifetime of the objects. LLVM Constant Representation
Definition at line 43 of file Constant.h.
Constructor & Destructor Documentation
Constant() [1/2]
llvm::Constant::Constant (Type * ty, ValueTy vty, AllocInfo AllocInfo) inline protected
Definition at line 45 of file Constant.h.
References llvm::User::User().
Referenced by Constant(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantAggregate::DECLARE_TRANSPARENT_OPERAND_ACCESSORS(), getAggregateElement(), getAggregateElement(), getAllOnesValue(), getIntegerValue(), getNullValue(), getSplatValue(), getUniqueInteger(), isConstantUsed(), isElementWiseEqual(), isNotMinSignedValue(), isNotOneValue(), mergeUndefsWith(), operator=(), removeDeadConstantUsers(), replaceUndefsWith(), stripPointerCasts(), stripPointerCasts(), and toConstantRange().
~Constant()
llvm::Constant::~Constant () protected default
Constant() [2/2]
llvm::Constant::Constant (const Constant &) delete
References Constant(), LLVM_ABI, and Y.
Member Function Documentation
classof()
bool llvm::Constant::classof (const Value * V) inline static
Definition at line 173 of file Constant.h.
containsConstantExpression()
bool Constant::containsConstantExpression () const
Return true if this is a fixed width vector constant that includes any constant expressions.
Definition at line 360 of file Constants.cpp.
References llvm::dyn_cast(), getAggregateElement(), llvm::Value::getType(), and llvm::isa().
containsPoisonElement()
bool Constant::containsPoisonElement () const
Return true if this is a vector constant that includes any poison elements.
Definition at line 349 of file Constants.cpp.
References llvm::CallingConv::C, containsUndefinedElement(), and llvm::isa().
containsUndefElement()
bool Constant::containsUndefElement () const
Return true if this is a vector constant that includes any strictly undef (not poison) elements.
Definition at line 354 of file Constants.cpp.
References llvm::CallingConv::C, containsUndefinedElement(), and llvm::isa().
containsUndefOrPoisonElement()
bool Constant::containsUndefOrPoisonElement () const
Return true if this is a vector constant that includes any undef or poison elements.
Since it is impossible to inspect a scalable vector element- wise at compile time, this function returns true only if the entire vector is undef or poison.
Definition at line 344 of file Constants.cpp.
References llvm::CallingConv::C, containsUndefinedElement(), and llvm::isa().
destroyConstant()
void Constant::destroyConstant ()
Called if some element of this constant is no longer valid.
At this point only other constants may be on the use_list for this constant. Any constants on our Use list must also be destroy'd. The implementation must be sure to remove the constant from the list of available cached constants. Implementations should implement destroyConstantImpl to remove constants from any pools/maps they are contained it.
First call destroyConstantImpl on the subclass. This gives the subclass a chance to remove the constant from any maps/pools it's contained in.
Definition at line 489 of file Constants.cpp.
References assert(), llvm::cast(), llvm::dbgs(), llvm::deleteConstant(), llvm::Value::getValueID(), llvm::isa(), llvm_unreachable, llvm::Value::use_empty(), and llvm::Value::user_back().
Referenced by handleOperandChange(), llvm::MergeBasicBlockIntoOnlyPred(), and processBlockAddr().
getAggregateElement() [1/2]
Constant * Constant::getAggregateElement (Constant * Elt) const
Definition at line 478 of file Constants.cpp.
References assert(), Constant(), llvm::dyn_cast(), getAggregateElement(), llvm::Value::getType(), and llvm::isa().
getAggregateElement() [2/2]
Constant * Constant::getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
This can return null if the element index is a ConstantExpr, if 'this' is a constant expr or if the constant does not fit into an uint64_t.
Definition at line 435 of file Constants.cpp.
References assert(), Constant(), llvm::dyn_cast(), llvm::Value::getContext(), llvm::Value::getType(), and llvm::isa().
Referenced by areInverseVectorBitmasks(), CheckAndCreateOffsetAdd(), checkOffsetSize(), llvm::InstCombinerImpl::commonIDivRemTransforms(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownFPClass(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldInsertValueInstruction(), containsConstantExpression(), emitGlobalConstantVector(), llvm::FlushFPConstant(), foldConstantInsEltIntoShuffle(), getAggregateElement(), getSplatableConstant(), getTargetConstantBitsFromNode(), getUniqueInteger(), hasExactInverseFP(), isFiniteNonZeroFP(), isKnownIntegral(), isNaN(), isNormalFP(), isNotMinSignedValue(), isNotOneValue(), matchStridedConstant(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifySelectInst(), simplifyX86pshufb(), simplifyX86vpermilvar(), simplifyX86vpermv(), simplifyX86vpermv3(), and WriteConstantInternal().
getAllOnesValue()
Constant * Constant::getAllOnesValue (Type * Ty) static
Returns
the value for an integer or vector of integer constant of the given type that has all its bits set to true. Get the all ones value
Definition at line 420 of file Constants.cpp.
References llvm::cast(), Constant(), llvm::dyn_cast(), llvm::APInt::getAllOnes(), llvm::APFloat::getAllOnesValue(), getAllOnesValue(), and llvm::ConstantVector::getSplat().
Referenced by canonicalizeLowbitMask(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromUniformValue(), llvm::IRBuilderBase::CreateIsNotNeg(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::BinaryOperator::CreateNot(), llvm::IRBuilderBase::CreateNot(), DoInitialMatch(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), FoldBitCast(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEqIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), foldICmpOrXX(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), llvm::InstCombinerImpl::foldICmpXorConstant(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::InstCombinerImpl::foldPowiReassoc(), llvm::IRBuilderBase::getAllOnesMask(), getAllOnesValue(), getAlternateBinop(), llvm::ConstantExpr::getBinOpAbsorber(), llvm::ConstantExpr::getBinOpIdentity(), llvm::ConstantExpr::getIntrinsicIdentity(), getMaskedTypeForICmpPair(), llvm::ConstantExpr::getNot(), getSign32(), handleOtherCmpSelSimplifications(), instCombinePTrue(), LLVMConstAllOnes(), llvm::RISCVTargetLowering::lowerDeinterleaveIntrinsicToLoad(), llvm::RISCVTargetLowering::lowerInterleaveIntrinsicToStore(), LowerNegateToMultiply(), llvm::lowerObjectSizeCall(), matchUAddWithOverflowConstantEdgeCases(), OptimizeAndOrXor(), replaceWithTLIFunction(), simplifyAddInst(), simplifyAShrInst(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpInst(), simplifyIntrinsic(), simplifyLogicOfAddSub(), simplifyOrInst(), simplifyOrLogic(), simplifySDivInst(), simplifyTernarylogic(), simplifyXorInst(), tryToFoldLiveIns(), llvm::UnrollRuntimeLoopRemainder(), upgradeMaskedCompare(), upgradeX86IntrinsicCall(), upgradeX86vpcom(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), and llvm::InstCombinerImpl::visitXor().
getIntegerValue()
Constant * Constant::getIntegerValue (Type * Ty, const APInt & V) static
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
Definition at line 403 of file Constants.cpp.
References llvm::CallingConv::C, Constant(), llvm::dyn_cast(), llvm::ConstantExpr::getIntToPtr(), llvm::Type::getScalarType(), and llvm::ConstantVector::getSplat().
Referenced by constantFoldUser(), createIRLevelProfileFlagVar(), createMemprofHistogramFlagVar(), llvm::createProfileSamplingVar(), llvm::AtomicInfo::EmitAtomicCompareExchangeLibcall(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), foldCtpopPow2Test(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldSwitchToSelect(), llvm::dxil::ResourceInfo::getAsMetadata(), getConstantVector(), getConstantVector(), llvm::ConstantExpr::getIntrinsicIdentity(), llvm::MinMaxIntrinsic::getSaturationPoint(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyX86pack(), and llvm::InstCombinerImpl::visitCallInst().
getNullValue()
Constant * Constant::getNullValue (Type * Ty) static
Constructor to create a '0' constant of arbitrary type.
Definition at line 373 of file Constants.cpp.
References llvm::Type::ArrayTyID, llvm::Type::BFloatTyID, llvm::cast(), Constant(), llvm::Type::DoubleTyID, llvm::Type::FixedVectorTyID, llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::ConstantAggregateZero::get(), llvm::ConstantPointerNull::get(), llvm::ConstantTargetNone::get(), llvm::ConstantTokenNone::get(), llvm::APFloat::getZero(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, llvm_unreachable, llvm::Type::PointerTyID, llvm::Type::PPC_FP128TyID, llvm::Type::ScalableVectorTyID, llvm::Type::StructTyID, llvm::Type::TargetExtTyID, llvm::Type::TokenTyID, and llvm::Type::X86_FP80TyID.
Referenced by addAssumeNonNull(), appendToGlobalArray(), applyX86MaskOn1BitsVec(), BreakUpSubtract(), calculateVectorIndex(), canonicalizeAbs(), collectElements(), combineTargetShuffle(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromUniformValue(), convertImplicitDefToConstZero(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::SanitizerStatReport::create(), llvm::AArch64TargetLowering::createComplexDeinterleavingIR(), llvm::FixedPointBuilder< IRBuilderTy >::CreateFloatingToFixed(), llvm::IRBuilderBase::CreateIsNeg(), llvm::IRBuilderBase::CreateIsNotNull(), llvm::IRBuilderBase::CreateIsNull(), llvm::IRBuilderBase::CreateLogicalAnd(), createMaskInstrs(), llvm::IRBuilderBase::CreateNeg(), llvm::FixedPointBuilder< IRBuilderTy >::CreateSub(), despeculateCountZeros(), eliminateSwiftErrorArgument(), llvm::emitGEPOffset(), expandSignIntrinsic(), expandUDivOrURem(), llvm::SanitizerStatReport::finish(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), foldCtpop(), foldCtpopPow2Test(), foldCttzCtlz(), foldDependentIVs(), foldFPtoI(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEqIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstantNotInt(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpOrXX(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShlConstConst(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpShrConstConst(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpWithHighBitMask(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), llvm::InstCombinerImpl::foldICmpXorConstant(), foldICmpXorXX(), foldLogOpOfMaskedICmps(), foldMemChr(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::InstCombinerImpl::foldPtrToIntOfGEP(), foldSetClearBits(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::InstCombinerImpl::foldSignBitTest(), foldSwitchToSelect(), foldURemOfLoopIncrement(), llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), llvm::ConstantExpr::getAlignOf(), llvm::SCCPInstVisitor::getArgAttributeVL(), getBaseType(), llvm::ConstantExpr::getBinOpAbsorber(), llvm::ConstantExpr::getBinOpIdentity(), llvm::ExecutionEngine::getConstantValue(), llvm::ConstantExpr::getExactLogBase2(), getFPClassConstant(), llvm::getInitialValueOfAllocation(), llvm::ConstantExpr::getIntrinsicIdentity(), getNegativeIsTrueBoolVec(), llvm::offloading::getOffloadingEntryInitializer(), llvm::InstCombiner::getSafeVectorConstantForBinop(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::ConstantAggregateZero::getSequentialElement(), getSign32(), llvm::ConstantExpr::getSizeOf(), getSplatValue(), getStrlenWithNull(), llvm::ConstantAggregateZero::getStructElement(), GetTLSADDR(), llvm::AA::getWithType(), hostParallelCallback(), llvm::GCNTTIImpl::instCombineIntrinsic(), instCombineSVECmpNE(), llvm::isBytewiseValue(), LLVMBuildCatchSwitch(), LLVMBuildCleanupPad(), LLVMConstNull(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), llvm::lowerObjectSizeCall(), LowerToTLSExecModel(), memChrToCharCompare(), OptimizeAndOrXor(), OptimizeEmptyGlobalAtExitDtors(), optimizeIntegerToVectorInsertions(), optimizeMemCmpConstantSize(), optimizeMemCmpVarSize(), optimizeVectorResizeWithIntegerBitCasts(), processUse(), llvm::orc::ReOptimizeLayer::reoptimizeIfCallFrequent(), rewriteGEPAsOffset(), runImpl(), runPass(), simplifyAddInst(), simplifyAllocaArraySize(), simplifyAndCommutative(), simplifyAndInst(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), llvm::InstCombinerImpl::SimplifyAnyMemTransfer(), llvm::simplifyBinaryIntrinsic(), simplifyByDomEq(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::X86TTIImpl::simplifyDemandedUseBitsIntrinsic(), simplifyDivRem(), simplifyFSubInst(), simplifyICmpInst(), simplifyICmpWithBinOp(), simplifyIntrinsic(), simplifyIRemMulShl(), simplifyLogicOfAddSub(), simplifyMulInst(), simplifyNeonTbl1(), simplifyRem(), simplifyRightShift(), simplifyShift(), simplifyShlInst(), simplifySRemInst(), simplifySubInst(), simplifySVEIntrinsic(), simplifyTernarylogic(), simplifyWithOpsReplaced(), simplifyX86MaskedLoad(), simplifyX86movmsk(), simplifyX86pshufb(), simplifyX86varShift(), simplifyXorInst(), targetParallelCallback(), tryToFoldLiveIns(), upgradeMaskedCompare(), upgradeNVVMIntrinsicCall(), llvm::UpgradeTBAANode(), upgradeX86ALIGNIntrinsics(), upgradeX86IntrinsicCall(), upgradeX86PSLLDQIntrinsics(), upgradeX86PSRLDQIntrinsics(), upgradeX86vpcom(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitGEPOfGEP(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitZExt(), workshareLoopTargetCallback(), and llvm::Evaluator::~Evaluator().
getSplatValue()
Constant * Constant::getSplatValue (bool AllowPoison = false) const
If all elements of the vector constant have the same value, return that value.
Otherwise, return nullptr. Ignore poison elements by setting AllowPoison to true.
Definition at line 1712 of file Constants.cpp.
References llvm::all_of(), assert(), llvm::cast(), Constant(), llvm::dyn_cast(), llvm::PoisonValue::get(), llvm::Value::getContext(), getNullValue(), llvm::Value::getType(), I, and llvm::isa().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::FlushFPConstant(), getUniqueInteger(), hasExactInverseFP(), isAllOnesValue(), isFiniteNonZeroFP(), isMinSignedValue(), isNaN(), isNegativeZeroValue(), isNormalFP(), isNotMinSignedValue(), isNotOneValue(), isOneValue(), isZeroValue(), toConstantRange(), and WriteConstantInternal().
getUniqueInteger()
const APInt & Constant::getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
Definition at line 1777 of file Constants.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), Constant(), llvm::dyn_cast(), getAggregateElement(), getSplatValue(), and llvm::isa().
Referenced by foldShiftIntoShiftInAnotherHandOfAndInICmp().
handleOperandChange()
void Constant::handleOperandChange (Value * From, Value * To)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
Update this constant array to change uses of 'From' to be uses of 'To'.
Basically this method goes through the trouble of building a new constant that is equivalent to the current one, with all uses of From replaced with uses of To. After this construction is completed, all of the users of 'this' are replaced to use the new constant, and then 'this' is deleted. In general, you should not call this method, instead, use Value::replaceAllUsesWith, which automatically dispatches to this method as needed.
This must update the uniquing data structures etc.
Note that we intentionally replace all uses of From with To here. Consider a large array that uses 'From' 1000 times. By handling this case all here, ConstantArray::handleOperandChange is only invoked once, and that single invocation handles all 1000 uses. Handling them one at a time would work, but would be really slow because it would have to unique each updated array instance.
Definition at line 3242 of file Constants.cpp.
References assert(), destroyConstant(), llvm::Value::getValueID(), llvm_unreachable, and llvm::Value::replaceAllUsesWith().
hasExactInverseFP()
bool Constant::hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
Definition at line 256 of file Constants.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), getAggregateElement(), getSplatValue(), llvm::Value::getType(), and I.
hasOneLiveUse()
bool Constant::hasOneLiveUse () const
Return true if the constant has exactly one live use.
This returns the same result as calling Value::hasOneUse after Constant::removeDeadConstantUsers, but doesn't remove dead constants.
Definition at line 766 of file Constants.cpp.
hasZeroLiveUses()
bool Constant::hasZeroLiveUses () const
Return true if the constant has no live uses.
This returns the same result as calling Value::use_empty after Constant::removeDeadConstantUsers, but doesn't remove dead constants.
Definition at line 768 of file Constants.cpp.
isAllOnesValue()
bool Constant::isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
Definition at line 107 of file Constants.cpp.
References llvm::dyn_cast(), getSplatValue(), and llvm::Value::getType().
Referenced by llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), and simplifyICmpInst().
isConstantUsed()
bool Constant::isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
Definition at line 639 of file Constants.cpp.
References Constant(), llvm::dyn_cast(), llvm::isa(), isConstantUsed(), llvm::User::User(), and llvm::Value::users().
Referenced by findPartitions(), and isConstantUsed().
isDLLImportDependent()
bool Constant::isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
Definition at line 632 of file Constants.cpp.
References ConstHasGlobalValuePredicate().
isElementWiseEqual()
bool Constant::isElementWiseEqual (Value * Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
This is identical to just comparing the pointers, with the exception that for vectors, if only one of the constants has an undef element in some lane, the constants still match.
Definition at line 298 of file Constants.cpp.
References llvm::cast(), Constant(), llvm::ConstantFoldCompareInstruction(), llvm::dyn_cast(), llvm::ConstantExpr::getBitCast(), llvm::VectorType::getInteger(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::isa(), llvm::PatternMatch::m_One(), llvm::PatternMatch::match(), and Y.
Referenced by llvm::InstCombinerImpl::visitSExt(), and llvm::InstCombinerImpl::visitSub().
isFiniteNonZeroFP()
bool Constant::isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a fixed width vector constant with all finite and non-zero elements.
Definition at line 214 of file Constants.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), getAggregateElement(), getSplatValue(), llvm::Value::getType(), and I.
isManifestConstant()
bool Constant::isManifestConstant () const
Return true if a constant is ConstantData or a ConstantAggregate or ConstantExpr that contain only ConstantData.
Definition at line 843 of file Constants.cpp.
References llvm::cast(), llvm::isa(), isManifestConstant(), llvm::User::Op(), and llvm::User::operand_values().
Referenced by isManifestConstant().
isMinSignedValue()
bool Constant::isMinSignedValue () const
Return true if the value is the smallest signed value.
Definition at line 169 of file Constants.cpp.
References llvm::dyn_cast(), getSplatValue(), and llvm::Value::getType().
isNaN()
bool Constant::isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
Definition at line 277 of file Constants.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), getAggregateElement(), getSplatValue(), llvm::Value::getType(), and I.
Referenced by propagateNaN().
isNegativeZeroValue()
bool Constant::isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
Definition at line 56 of file Constants.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), getSplatValue(), llvm::Value::getType(), and isNullValue().
isNormalFP()
bool Constant::isNormalFP () const
Return true if this is a normal (as opposed to denormal, infinity, nan, or zero) floating-point scalar constant or a vector constant with all normal elements.
See APFloat::isNormal.
Definition at line 235 of file Constants.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), getAggregateElement(), getSplatValue(), llvm::Value::getType(), and I.
Referenced by foldFDivConstantDividend(), and llvm::InstCombinerImpl::foldFMulReassoc().
isNotMinSignedValue()
bool Constant::isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
Definition at line 186 of file Constants.cpp.
References Constant(), llvm::dyn_cast(), getAggregateElement(), getSplatValue(), llvm::Value::getType(), I, and isNotMinSignedValue().
Referenced by isNotMinSignedValue(), and llvm::InstCombinerImpl::visitMul().
isNotOneValue()
bool Constant::isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
Definition at line 141 of file Constants.cpp.
References Constant(), llvm::dyn_cast(), getAggregateElement(), getSplatValue(), llvm::Value::getType(), I, and isNotOneValue().
Referenced by isNotOneValue().
isNullValue()
bool Constant::isNullValue () const
Return true if this is the value that would be returned by getNullValue.
Definition at line 90 of file Constants.cpp.
References llvm::dyn_cast(), and llvm::isa().
Referenced by addConditions(), addTryBlockMapEntry(), calculateSEHStateNumbers(), llvm::InstCombinerImpl::commonIDivRemTransforms(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::InstCombinerImpl::foldICmpInstWithConstantNotInt(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldSwitchToSelect(), llvm::getConstantDataArrayInfo(), getPredicateResult(), llvm::inferAttribute(), llvm::GCNTTIImpl::instCombineIntrinsic(), isCatchAll(), llvm::ConstantPtrAuth::isKnownCompatibleWith(), isKnownNonZero(), isNegativeZeroValue(), isZeroValue(), llvm::AsmPrinter::lowerConstant(), optimizeOnceStoredGlobal(), runImpl(), shouldUseSwitchConditionAsTableIndex(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyICmpInst(), and TryToShrinkGlobalToBoolean().
isOneValue()
bool Constant::isOneValue () const
Returns true if the value is one.
Definition at line 124 of file Constants.cpp.
References llvm::dyn_cast(), getSplatValue(), and llvm::Value::getType().
Referenced by findBestNonTrivialUnswitchCandidate(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), and unswitchNontrivialInvariants().
isThreadDependent()
bool Constant::isThreadDependent () const
Return true if the value can vary between threads.
Definition at line 625 of file Constants.cpp.
References ConstHasGlobalValuePredicate().
isZeroValue()
bool Constant::isZeroValue () const
Return true if the value is negative zero or null value.
Definition at line 76 of file Constants.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), getSplatValue(), llvm::Value::getType(), and isNullValue().
Referenced by computeKnownBitsFromOperator(), expandVecReduceAdd(), shouldConvertImpl(), and llvm::InstCombinerImpl::visitXor().
mergeUndefsWith()
Constant * Constant::mergeUndefsWith (Constant * C, Constant * Other) static
Merges undefs of a Constant with another Constant, along with the undefs already present.
Other doesn't have to be the same type as C, but both must either be scalars or vectors with the same element count. If no changes are made, the constant C is returned.
Definition at line 808 of file Constants.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), Constant(), llvm::dyn_cast(), llvm::ConstantVector::get(), llvm::UndefValue::get(), I, llvm::isa(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::match(), and llvm::Other.
Referenced by llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), foldSelectZeroOrMul(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitXor().
needsDynamicRelocation()
bool Constant::needsDynamicRelocation () const
Definition at line 651 of file Constants.cpp.
needsRelocation()
bool Constant::needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry (either static or dynamic).
This must be conservative, so if it might codegen to a relocatable entry, it should say so.
FIXME: This really should not be in IR.
Definition at line 655 of file Constants.cpp.
operator=()
void llvm::Constant::operator= (const Constant &) delete
References Constant().
removeDeadConstantUsers()
void Constant::removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
This method is useful for clients that want to check to see if a global is unused, but don't want to deal with potentially dead constants hanging off of the globals.
Definition at line 739 of file Constants.cpp.
References Constant(), constantIsDead(), llvm::dyn_cast(), I, llvm::User::User(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), deleteIfDead(), hasAddressTakenAndUsed(), mustPreserveGV(), llvm::CallGraphUpdater::replaceFunctionWith(), llvm::GlobalDCEPass::run(), SRAGlobal(), and llvm::GlobalValue::~GlobalValue().
replaceUndefsWith()
Constant * Constant::replaceUndefsWith (Constant * C, Constant * Replacement) static
Try to replace undefined constant C or undefined elements in C with Replacement.
If no changes are made, the constant C is returned.
Definition at line 784 of file Constants.cpp.
References assert(), llvm::CallingConv::C, Constant(), llvm::dyn_cast(), llvm::ConstantVector::get(), llvm::Value::getType(), llvm::PatternMatch::m_Undef(), and llvm::PatternMatch::match().
Referenced by dropRedundantMaskingOfLeftShiftInput(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::InstCombinerImpl::visitFreeze(), visitMaskedMerge(), and llvm::InstCombinerImpl::visitXor().
stripPointerCasts() [1/2]
Constant * llvm::Constant::stripPointerCasts () inline
Definition at line 223 of file Constant.h.
References Constant().
stripPointerCasts() [2/2]
const Constant * llvm::Constant::stripPointerCasts () const inline
Definition at line 219 of file Constant.h.
References llvm::cast(), Constant(), and llvm::Value::stripPointerCasts().
Referenced by addTryBlockMapEntry(), llvm::AsmPrinter::emitGlobalAlias(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::ExtractTypeInfo(), hasUsesToReplace(), llvm::InlineFunction(), OptimizeGlobalAliases(), runImpl(), and llvm::InstCombinerImpl::visitLandingPadInst().
toConstantRange()
ConstantRange Constant::toConstantRange () const
Convert constant to an approximate constant range.
For vectors, the range is the union over the element ranges. Poison elements are ignored.
Definition at line 1791 of file Constants.cpp.
References llvm::BitWidth, Constant(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::Type::getScalarSizeInBits(), getSplatValue(), llvm::Value::getType(), I, llvm::isa(), and llvm::ConstantRange::unionWith().
Referenced by llvm::ValueLatticeElement::asConstantRange(), and llvm::ValueLatticeElement::mergeIn().
The documentation for this class was generated from the following files:
include/llvm/IR/Constant.h
lib/IR/Constants.cpp