LLVM: llvm::codeview::TypeRecord Class Reference
llvm::codeview::TypeRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
TypeRecordKind getKind () const
Public Attributes
TypeRecordKind Kind
Protected Member Functions
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 118 of file TypeRecord.h.
Constructor & Destructor Documentation
TypeRecord() [1/2]
llvm::codeview::TypeRecord::TypeRecord () protected default
Referenced by llvm::codeview::ArgListRecord::ArgListRecord(), llvm::codeview::ArgListRecord::ArgListRecord(), llvm::codeview::ArrayRecord::ArrayRecord(), llvm::codeview::ArrayRecord::ArrayRecord(), llvm::codeview::BaseClassRecord::BaseClassRecord(), llvm::codeview::BaseClassRecord::BaseClassRecord(), llvm::codeview::BaseClassRecord::BaseClassRecord(), llvm::codeview::BitFieldRecord::BitFieldRecord(), llvm::codeview::BitFieldRecord::BitFieldRecord(), llvm::codeview::BuildInfoRecord::BuildInfoRecord(), llvm::codeview::BuildInfoRecord::BuildInfoRecord(), llvm::codeview::DataMemberRecord::DataMemberRecord(), llvm::codeview::DataMemberRecord::DataMemberRecord(), llvm::codeview::DataMemberRecord::DataMemberRecord(), llvm::codeview::EndPrecompRecord::EndPrecompRecord(), llvm::codeview::EnumeratorRecord::EnumeratorRecord(), llvm::codeview::EnumeratorRecord::EnumeratorRecord(), llvm::codeview::EnumeratorRecord::EnumeratorRecord(), llvm::codeview::FieldListRecord::FieldListRecord(), llvm::codeview::FieldListRecord::FieldListRecord(), llvm::codeview::FuncIdRecord::FuncIdRecord(), llvm::codeview::FuncIdRecord::FuncIdRecord(), llvm::codeview::LabelRecord::LabelRecord(), llvm::codeview::LabelRecord::LabelRecord(), llvm::codeview::ListContinuationRecord::ListContinuationRecord(), llvm::codeview::ListContinuationRecord::ListContinuationRecord(), llvm::codeview::MemberFuncIdRecord::MemberFuncIdRecord(), llvm::codeview::MemberFuncIdRecord::MemberFuncIdRecord(), llvm::codeview::MemberFunctionRecord::MemberFunctionRecord(), llvm::codeview::MemberFunctionRecord::MemberFunctionRecord(), llvm::codeview::MethodOverloadListRecord::MethodOverloadListRecord(), llvm::codeview::MethodOverloadListRecord::MethodOverloadListRecord(), llvm::codeview::ModifierRecord::ModifierRecord(), llvm::codeview::ModifierRecord::ModifierRecord(), llvm::codeview::NestedTypeRecord::NestedTypeRecord(), llvm::codeview::NestedTypeRecord::NestedTypeRecord(), llvm::codeview::OneMethodRecord::OneMethodRecord(), llvm::codeview::OneMethodRecord::OneMethodRecord(), llvm::codeview::OneMethodRecord::OneMethodRecord(), llvm::codeview::OverloadedMethodRecord::OverloadedMethodRecord(), llvm::codeview::OverloadedMethodRecord::OverloadedMethodRecord(), llvm::codeview::PointerRecord::PointerRecord(), llvm::codeview::PointerRecord::PointerRecord(), llvm::codeview::PointerRecord::PointerRecord(), llvm::codeview::PointerRecord::PointerRecord(), llvm::codeview::PrecompRecord::PrecompRecord(), llvm::codeview::ProcedureRecord::ProcedureRecord(), llvm::codeview::ProcedureRecord::ProcedureRecord(), llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord(), llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord(), llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord(), llvm::codeview::StringIdRecord::StringIdRecord(), llvm::codeview::StringIdRecord::StringIdRecord(), llvm::codeview::StringListRecord::StringListRecord(), llvm::codeview::StringListRecord::StringListRecord(), llvm::codeview::TagRecord::TagRecord(), llvm::codeview::TagRecord::TagRecord(), llvm::codeview::TypeServer2Record::TypeServer2Record(), llvm::codeview::TypeServer2Record::TypeServer2Record(), llvm::codeview::UdtModSourceLineRecord::UdtModSourceLineRecord(), llvm::codeview::UdtModSourceLineRecord::UdtModSourceLineRecord(), llvm::codeview::UdtSourceLineRecord::UdtSourceLineRecord(), llvm::codeview::UdtSourceLineRecord::UdtSourceLineRecord(), llvm::codeview::VFPtrRecord::VFPtrRecord(), llvm::codeview::VFPtrRecord::VFPtrRecord(), llvm::codeview::VFTableRecord::VFTableRecord(), llvm::codeview::VFTableRecord::VFTableRecord(), llvm::codeview::VFTableShapeRecord::VFTableShapeRecord(), llvm::codeview::VFTableShapeRecord::VFTableShapeRecord(), llvm::codeview::VFTableShapeRecord::VFTableShapeRecord(), llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord(), llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord(), and llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord().
TypeRecord() [2/2]
llvm::codeview::TypeRecord::TypeRecord (TypeRecordKind Kind) inline explicit protected
Definition at line 121 of file TypeRecord.h.
References Kind.
Member Function Documentation
getKind()
TypeRecordKind llvm::codeview::TypeRecord::getKind () const inline
Definition at line 124 of file TypeRecord.h.
References Kind.
Member Data Documentation
Kind
TypeRecordKind llvm::codeview::TypeRecord::Kind
Definition at line 126 of file TypeRecord.h.
Referenced by llvm::codeview::ArgListRecord::ArgListRecord(), llvm::codeview::ArgListRecord::ArgListRecord(), llvm::codeview::ArrayRecord::ArrayRecord(), llvm::codeview::BaseClassRecord::BaseClassRecord(), llvm::codeview::BitFieldRecord::BitFieldRecord(), llvm::codeview::BuildInfoRecord::BuildInfoRecord(), llvm::codeview::ClassRecord::ClassRecord(), llvm::codeview::ClassRecord::ClassRecord(), llvm::codeview::DataMemberRecord::DataMemberRecord(), llvm::codeview::EndPrecompRecord::EndPrecompRecord(), llvm::codeview::EnumeratorRecord::EnumeratorRecord(), llvm::codeview::EnumRecord::EnumRecord(), llvm::codeview::FieldListRecord::FieldListRecord(), llvm::codeview::FuncIdRecord::FuncIdRecord(), getKind(), llvm::codeview::LabelRecord::LabelRecord(), llvm::codeview::ListContinuationRecord::ListContinuationRecord(), llvm::codeview::MemberFuncIdRecord::MemberFuncIdRecord(), llvm::codeview::MemberFunctionRecord::MemberFunctionRecord(), llvm::codeview::MethodOverloadListRecord::MethodOverloadListRecord(), llvm::codeview::ModifierRecord::ModifierRecord(), llvm::codeview::NestedTypeRecord::NestedTypeRecord(), llvm::codeview::OneMethodRecord::OneMethodRecord(), llvm::codeview::OverloadedMethodRecord::OverloadedMethodRecord(), llvm::codeview::PointerRecord::PointerRecord(), llvm::codeview::PrecompRecord::PrecompRecord(), llvm::codeview::ProcedureRecord::ProcedureRecord(), llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord(), llvm::codeview::StringIdRecord::StringIdRecord(), llvm::codeview::StringListRecord::StringListRecord(), llvm::codeview::StringListRecord::StringListRecord(), llvm::codeview::TagRecord::TagRecord(), llvm::codeview::TagRecord::TagRecord(), TypeRecord(), llvm::codeview::TypeServer2Record::TypeServer2Record(), llvm::codeview::UdtModSourceLineRecord::UdtModSourceLineRecord(), llvm::codeview::UdtSourceLineRecord::UdtSourceLineRecord(), llvm::codeview::UnionRecord::UnionRecord(), llvm::codeview::VFPtrRecord::VFPtrRecord(), llvm::codeview::VFTableRecord::VFTableRecord(), llvm::codeview::VFTableShapeRecord::VFTableShapeRecord(), llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord(), llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord(), and llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h