LLVM: llvm::IRComparer< T > Class Template Reference
llvm::IRComparer< T > Class Template Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
IRComparer (const IRDataT< T > &Before, const IRDataT< T > &After)
void compare (bool CompareModule, std::function< void(bool InModule, unsigned Minor, const FuncDataT< T > &Before, const FuncDataT< T > &After)> CompareFunc)
Static Public Member Functions
static void analyzeIR (Any IR, IRDataT< T > &Data)
Static Protected Member Functions
template<typename FunctionT>
static bool generateFunctionData (IRDataT< T > &Data, const FunctionT &F)
Protected Attributes
const IRDataT< T > & Before
const IRDataT< T > & After
Detailed Description
template<typename T>
class llvm::IRComparer< T >
Definition at line 416 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
IRComparer()
template<typename T> llvm::IRComparer< T >::IRComparer (const IRDataT< T > & Before, const IRDataT< T > & After) inline
Definition at line 418 of file StandardInstrumentations.h.
References After, and Before.
Member Function Documentation
analyzeIR()
template<typename T> void IRComparer::analyzeIR (Any IR, IRDataT< T > & Data) static
Definition at line 691 of file StandardInstrumentations.cpp.
References llvm::Data, F, generateFunctionData(), IR, llvm_unreachable, and unwrapIR().
Referenced by llvm::DotCfgChangeReporter::generateIRRepresentation(), llvm::InLineChangePrinter::generateIRRepresentation(), and llvm::DotCfgChangeReporter::handleInitialIR().
compare()
template<typename T> void IRComparer::compare (bool CompareModule, std::function< void(bool InModule, unsigned Minor, const FuncDataT< T > &Before, const FuncDataT< T > &After)> CompareFunc)
Definition at line 664 of file StandardInstrumentations.cpp.
References A(), After, assert(), B(), Before, and llvm::OrderedChangedData< FuncDataT< T > >::report().
Referenced by llvm::DotCfgChangeReporter::handleAfter(), llvm::InLineChangePrinter::handleAfter(), and llvm::DotCfgChangeReporter::handleInitialIR().
generateFunctionData()
template<typename T> template<typename FunctionT> bool IRComparer::generateFunctionData (IRDataT< T > & Data, const FunctionT & F) static protected
Definition at line 728 of file StandardInstrumentations.cpp.
References B(), llvm::Data, F, llvm::formatv(), llvm::OrderedChangedData< T >::getData(), llvm::OrderedChangedData< T >::getOrder(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and shouldGenerateData().
Referenced by analyzeIR().
Member Data Documentation
After
template<typename T> const IRDataT<T>& llvm::IRComparer< T >::After protected
Definition at line 439 of file StandardInstrumentations.h.
Referenced by compare(), and IRComparer().
Before
template<typename T> const IRDataT<T>& llvm::IRComparer< T >::Before protected
Definition at line 438 of file StandardInstrumentations.h.
Referenced by compare(), and IRComparer().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp