LLVM: llvm::RISCVInstPrinter Class Reference
llvm::RISCVInstPrinter Class Reference
#include "Target/RISCV/MCTargetDesc/RISCVInstPrinter.h"
Public Member Functions
RISCVInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
bool applyTargetSpecificCLOption (StringRef Opt) override
Customize the printer according to a command line option.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &O, MCRegister Reg) override
Print the assembler register name.
void printOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printBranchOperand (const MCInst *MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printCSRSystemRegister (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFenceArg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFRMArg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFRMArgLegacy (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFPImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printZeroOffsetMemOp (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printVTypeI (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printXSfmmVType (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printVMaskReg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printRegList (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printStackAdj (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O, bool Negate=false)
void printNegStackAdj (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printRegReg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
std::pair< const char *, uint64_t > getMnemonic (const MCInst &MI) const override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
void printCustomAliasOperand (const MCInst *MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
bool getUseColor () const
void setUseColor (bool Value)
WithMarkup markup (raw_ostream &OS, Markup M)
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
static const char * getRegisterName (MCRegister Reg, unsigned AltIdx)
Additional Inherited Members
Public Types inherited from llvm::MCInstPrinter
enum class Markup { Immediate , Register , Target , Memory }
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool UseColor = false
True if we are printing colored assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
SmallVector< raw_ostream::Colors, 4 > ColorStack {raw_ostream::Colors::RESET}
Detailed Description
Definition at line 21 of file RISCVInstPrinter.h.
Constructor & Destructor Documentation
RISCVInstPrinter()
llvm::RISCVInstPrinter::RISCVInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 23 of file RISCVInstPrinter.h.
References llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MCInstPrinter(), llvm::MCInstPrinter::MII, and llvm::MCInstPrinter::MRI.
Member Function Documentation
applyTargetSpecificCLOption()
bool RISCVInstPrinter::applyTargetSpecificCLOption (StringRef Opt) override virtual
Customize the printer according to a command line option.
Returns
true if the option is recognized and applied.
Reimplemented from llvm::MCInstPrinter.
Definition at line 51 of file RISCVInstPrinter.cpp.
References ArchRegNames, EmitX8AsFP, and llvm::MCInstPrinter::PrintAliases.
getMnemonic()
std::pair< const char *, uint64_t > llvm::RISCVInstPrinter::getMnemonic (const MCInst & MI) const override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
References MI.
getRegisterName() [1/2]
const char * RISCVInstPrinter::getRegisterName (MCRegister Reg) static
Definition at line 334 of file RISCVInstPrinter.cpp.
References ArchRegNames, EmitX8AsFP, and getRegisterName().
Referenced by getRegisterName(), and printRegName().
getRegisterName() [2/2]
const char * llvm::RISCVInstPrinter::getRegisterName (MCRegister Reg, unsigned AltIdx) static
References Reg.
printAliasInstr()
bool llvm::RISCVInstPrinter::printAliasInstr (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
References llvm::Address, and MI.
Referenced by printInst().
printBranchOperand()
void RISCVInstPrinter::printBranchOperand (const MCInst * MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 107 of file RISCVInstPrinter.cpp.
References llvm::Address, llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCSubtargetInfo::hasFeature(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::markup(), MI, llvm::MCInstPrinter::PrintBranchImmAsAddress, printOperand(), and llvm::MCInstPrinter::Target.
printCSRSystemRegister()
void RISCVInstPrinter::printCSRSystemRegister (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 125 of file RISCVInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInstPrinter::markup(), MI, Range, and llvm::MCInstPrinter::Register.
printCustomAliasOperand()
void llvm::RISCVInstPrinter::printCustomAliasOperand (const MCInst * MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O)
References llvm::Address, MI, OpIdx, and Reg.
printFenceArg()
void RISCVInstPrinter::printFenceArg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 141 of file RISCVInstPrinter.cpp.
References assert(), llvm::RISCVFenceField::I, MI, llvm::RISCVFenceField::O, llvm::RISCVFenceField::R, and llvm::RISCVFenceField::W.
printFPImmOperand()
void RISCVInstPrinter::printFPImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 181 of file RISCVInstPrinter.cpp.
References llvm::format(), llvm::RISCVLoadFPImm::getFPImm(), llvm::MCInstPrinter::Immediate, llvm::MCInstPrinter::markup(), and MI.
printFRMArg()
void RISCVInstPrinter::printFRMArg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 159 of file RISCVInstPrinter.cpp.
References llvm::RISCVFPRndMode::DYN, llvm::getImm(), MI, NoAliases, llvm::MCInstPrinter::PrintAliases, and llvm::RISCVFPRndMode::roundingModeToString().
printFRMArgLegacy()
void RISCVInstPrinter::printFRMArgLegacy (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 168 of file RISCVInstPrinter.cpp.
References llvm::getImm(), MI, llvm::RISCVFPRndMode::RNE, and llvm::RISCVFPRndMode::roundingModeToString().
printInst()
void RISCVInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 69 of file RISCVInstPrinter.cpp.
References llvm::Address, MI, NoAliases, llvm::MCInstPrinter::PrintAliases, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), and llvm::RISCVRVC::uncompress().
printInstruction()
void llvm::RISCVInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
References llvm::Address, and MI.
Referenced by printInst().
printNegStackAdj()
void llvm::RISCVInstPrinter::printNegStackAdj (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O) inline
Definition at line 60 of file RISCVInstPrinter.h.
References MI, and printStackAdj().
printOperand()
void RISCVInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 88 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::Immediate, llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::markup(), MI, and printRegName().
Referenced by printBranchOperand().
printRegList()
void RISCVInstPrinter::printRegList (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 246 of file RISCVInstPrinter.cpp.
References ArchRegNames, assert(), MI, llvm::Offset, printRegName(), llvm::RISCVZC::RA, llvm::RISCVZC::RA_S0, llvm::RISCVZC::RA_S0_S1, llvm::RISCVZC::RA_S0_S11, llvm::RISCVZC::RA_S0_S2, and llvm::RISCVZC::RA_S0_S3.
printRegName()
void RISCVInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 84 of file RISCVInstPrinter.cpp.
References getRegisterName(), llvm::MCInstPrinter::markup(), and llvm::MCInstPrinter::Register.
Referenced by printOperand(), printRegList(), printRegReg(), printVMaskReg(), and printZeroOffsetMemOp().
printRegReg()
void RISCVInstPrinter::printRegReg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 288 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), MI, and printRegName().
printStackAdj()
void RISCVInstPrinter::printStackAdj (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O, bool Negate = false)
Definition at line 302 of file RISCVInstPrinter.cpp.
References assert(), llvm::sampleprof::Base, llvm::RISCVZC::getStackAdjBase(), llvm::MCSubtargetInfo::hasFeature(), llvm::MCInstPrinter::Immediate, llvm::MCInstPrinter::markup(), and MI.
Referenced by printNegStackAdj().
printVMaskReg()
void RISCVInstPrinter::printVMaskReg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 321 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), MI, and printRegName().
printVTypeI()
void RISCVInstPrinter::printVTypeI (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 215 of file RISCVInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::RISCVVType::getSEW(), llvm::RISCVVType::getVLMUL(), llvm::RISCVVType::LMUL_RESERVED, MI, and llvm::RISCVVType::printVType().
printXSfmmVType()
void RISCVInstPrinter::printXSfmmVType (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 229 of file RISCVInstPrinter.cpp.
References assert(), llvm::RISCVVType::getSEW(), llvm::RISCVVType::getXSfmmWiden(), llvm::RISCVVType::isAltFmt(), llvm::RISCVVType::isValidXSfmmVType(), MI, and Widen().
printZeroOffsetMemOp()
void RISCVInstPrinter::printZeroOffsetMemOp (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 204 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), MI, and printRegName().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.h
lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.cpp