LLVM: llvm::ELFObjectWriter Class Reference
llvm::ELFObjectWriter Class Reference final
#include "llvm/MC/MCELFObjectWriter.h"
Classes
struct Symver
Public Member Functions
ELFObjectWriter (std::unique_ptr< MCELFObjectTargetWriter > MOTW, raw_pwrite_stream &OS, bool IsLittleEndian)
ELFObjectWriter (std::unique_ptr< MCELFObjectTargetWriter > MOTW, raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS, bool IsLittleEndian)
void reset () override
lifetime management
void setAssembler (MCAssembler *Asm) override
void executePostLayoutBinding () override
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
void recordRelocation (const MCFragment &F, const MCFixup &Fixup, MCValue Target, uint64_t &FixedValue) override
Record a relocation entry.
bool isSymbolRefDifferenceFullyResolvedImpl (const MCSymbol &SymA, const MCFragment &FB, bool InSet, bool IsPCRel) const override
uint64_t writeObject () override
Write the object file and returns the number of bytes written.
bool hasRelocationAddend () const
bool usesRela (const MCTargetOptions *TO, const MCSectionELF &Sec) const
bool useSectionSymbol (const MCValue &Val, const MCSymbolELF *Sym, uint64_t C, unsigned Type) const
bool checkRelocation (SMLoc Loc, const MCSectionELF *From, const MCSectionELF *To)
unsigned getELFHeaderEFlags () const
void setELFHeaderEFlags (unsigned Flags)
void markGnuAbi ()
bool seenGnuAbi () const
void setOverrideABIVersion (uint8_t V)
Public Member Functions inherited from llvm::MCObjectWriter
MCObjectWriter (const MCObjectWriter &)=delete
MCObjectWriter & operator= (const MCObjectWriter &)=delete
virtual ~MCObjectWriter ()
MCContext & getContext () const
bool isSymbolRefDifferenceFullyResolved (const MCSymbol &A, const MCSymbol &B, bool InSet) const
Check whether the difference (A - B) between two symbol references is fully resolved.
MutableArrayRef< std::pair< std::string, size_t > > getFileNames ()
void addFileName (StringRef FileName)
void setCompilerVersion (StringRef CompilerVers)
void emitAddrsigSection ()
Tell the object writer to emit an address-significance table during writeObject().
bool getEmitAddrsigSection ()
void addAddrsigSymbol (const MCSymbol *Sym)
Record the given symbol in the address-significance table to be written diring writeObject().
std::vector< const MCSymbol * > & getAddrsigSyms ()
SmallVector< CGProfileEntry, 0 > & getCGProfile ()
bool getSubsectionsViaSymbols () const
void setSubsectionsViaSymbols (bool Value)
Public Attributes
std::unique_ptr< MCELFObjectTargetWriter > TargetObjectWriter
raw_pwrite_stream & OS
raw_pwrite_stream * DwoOS = nullptr
DenseMap< const MCSectionELF *, std::vector< ELFRelocationEntry > > Relocations
DenseMap< const MCSymbolELF *, const MCSymbolELF * > Renames
SmallVector< const MCSymbolELF *, 0 > Weakrefs
bool IsLittleEndian = false
bool SeenGnuAbi = false
std::optional< uint8_t > OverrideABIVersion
SmallVector< Symver, 0 > Symvers
Additional Inherited Members
Protected Member Functions inherited from llvm::MCObjectWriter
MCObjectWriter ()=default
Protected Attributes inherited from llvm::MCObjectWriter
MCAssembler * Asm = nullptr
SmallVector< std::pair< std::string, size_t >, 0 > FileNames
List of declared file names.
std::string CompilerVersion
std::vector< const MCSymbol * > AddrsigSyms
bool EmitAddrsigSection = false
bool SubsectionsViaSymbols = false
SmallVector< CGProfileEntry, 0 > CGProfile
Detailed Description
Definition at line 142 of file MCELFObjectWriter.h.
Constructor & Destructor Documentation
ELFObjectWriter() [1/2]
ELFObjectWriter::ELFObjectWriter (std::unique_ptr< MCELFObjectTargetWriter > MOTW, raw_pwrite_stream & OS, bool IsLittleEndian)
Definition at line 1154 of file ELFObjectWriter.cpp.
References IsLittleEndian, llvm::move(), OS, and TargetObjectWriter.
ELFObjectWriter() [2/2]
ELFObjectWriter::ELFObjectWriter (std::unique_ptr< MCELFObjectTargetWriter > MOTW, raw_pwrite_stream & OS, raw_pwrite_stream & DwoOS, bool IsLittleEndian)
Definition at line 1158 of file ELFObjectWriter.cpp.
References DwoOS, IsLittleEndian, llvm::move(), OS, and TargetObjectWriter.
Member Function Documentation
checkRelocation()
bool ELFObjectWriter::checkRelocation (SMLoc Loc, const MCSectionELF * From, const MCSectionELF * To)
Definition at line 1311 of file ELFObjectWriter.cpp.
References llvm::MCObjectWriter::getContext(), isDwoSection(), and llvm::MCContext::reportError().
Referenced by recordRelocation().
executePostLayoutBinding()
void ELFObjectWriter::executePostLayoutBinding () override virtual
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
This routine is called by the assembler after layout and relaxation is complete.
Reimplemented from llvm::MCObjectWriter.
Definition at line 1185 of file ELFObjectWriter.cpp.
References llvm::MCObjectWriter::AddrsigSyms, llvm::MCObjectWriter::Asm, assert(), llvm::cast(), llvm::MCSymbolRefExpr::create(), llvm::dyn_cast(), llvm::StringRef::find(), llvm::MCSection::getBeginSymbol(), llvm::MCSymbol::getName(), llvm::MCSymbol::getSection(), llvm::MCSymbol::isInSection(), llvm::StringRef::npos, Renames, llvm::MCSymbol::setUsedInReloc(), llvm::StringRef::starts_with(), llvm::ELF::STB_WEAK, llvm::StringRef::substr(), Symvers, llvm::CallingConv::Tail, and Weakrefs.
getELFHeaderEFlags()
unsigned llvm::ELFObjectWriter::getELFHeaderEFlags () const inline
Definition at line 192 of file MCELFObjectWriter.h.
hasRelocationAddend()
bool ELFObjectWriter::hasRelocationAddend () const
Definition at line 1181 of file ELFObjectWriter.cpp.
References TargetObjectWriter.
Referenced by useSectionSymbol(), and usesRela().
isSymbolRefDifferenceFullyResolvedImpl()
bool ELFObjectWriter::isSymbolRefDifferenceFullyResolvedImpl (const MCSymbol & SymA, const MCFragment & FB, bool InSet, bool IsPCRel) const override virtual
Reimplemented from llvm::MCObjectWriter.
Definition at line 1395 of file ELFObjectWriter.cpp.
References assert(), llvm::cast(), llvm::MCFragment::getParent(), llvm::ELF::STB_LOCAL, and llvm::ELF::STT_GNU_IFUNC.
markGnuAbi()
void llvm::ELFObjectWriter::markGnuAbi () inline
Definition at line 196 of file MCELFObjectWriter.h.
References SeenGnuAbi.
Referenced by llvm::MCELFStreamer::changeSection(), and llvm::MCELFStreamer::emitSymbolAttribute().
recordRelocation()
void ELFObjectWriter::recordRelocation (const MCFragment & F, const MCFixup & Fixup, MCValue Target, uint64_t & FixedValue) override virtual
Record a relocation entry.
This routine is called by the assembler after layout and relaxation, and post layout binding. The implementation is responsible for storing information about the relocation so that it can be emitted during writeObject().
Reimplemented from llvm::MCObjectWriter.
Definition at line 1325 of file ELFObjectWriter.cpp.
References llvm::MCObjectWriter::Asm, assert(), llvm::cast(), llvm::cast_or_null(), checkRelocation(), DwoOS, F, llvm::FirstLiteralRelocationKind, Fixup, llvm::MCSection::getBeginSymbol(), llvm::MCObjectWriter::getContext(), llvm::mc::isRelocRelocation(), Relocations, Renames, llvm::ELF::STB_LOCAL, TargetObjectWriter, useSectionSymbol(), and usesRela().
reset()
void ELFObjectWriter::reset () override virtual
lifetime management
Reimplemented from llvm::MCObjectWriter.
Definition at line 1164 of file ELFObjectWriter.cpp.
References OverrideABIVersion, Relocations, Renames, llvm::MCObjectWriter::reset(), SeenGnuAbi, Symvers, and Weakrefs.
seenGnuAbi()
bool llvm::ELFObjectWriter::seenGnuAbi () const inline
Definition at line 197 of file MCELFObjectWriter.h.
References SeenGnuAbi.
setAssembler()
void ELFObjectWriter::setAssembler (MCAssembler * Asm) override virtual
Reimplemented from llvm::MCObjectWriter.
Definition at line 1176 of file ELFObjectWriter.cpp.
References llvm::MCObjectWriter::Asm, llvm::MCObjectWriter::setAssembler(), and TargetObjectWriter.
setELFHeaderEFlags()
void llvm::ELFObjectWriter::setELFHeaderEFlags (unsigned Flags) inline
Definition at line 193 of file MCELFObjectWriter.h.
setOverrideABIVersion()
void llvm::ELFObjectWriter::setOverrideABIVersion (uint8_t V) inline
Definition at line 200 of file MCELFObjectWriter.h.
References OverrideABIVersion.
useSectionSymbol()
bool ELFObjectWriter::useSectionSymbol (const MCValue & Val, const MCSymbolELF * Sym, uint64_t C, unsigned Type) const
Definition at line 1259 of file ELFObjectWriter.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::ELF::EM_386, llvm::ELF::EM_MIPS, llvm::MCSectionELF::getFlags(), llvm::MCSymbol::getSection(), llvm::MCSymbolELF::getType(), hasRelocationAddend(), llvm::MCSymbol::isInSection(), llvm::ELF::SHF_MERGE, llvm::ELF::SHF_TLS, llvm::ELF::STT_GNU_IFUNC, and TargetObjectWriter.
Referenced by recordRelocation().
usesRela()
bool ELFObjectWriter::usesRela (const MCTargetOptions * TO, const MCSectionELF & Sec) const
Definition at line 1388 of file ELFObjectWriter.cpp.
References llvm::MCTargetOptions::Crel, llvm::MCSectionELF::getType(), hasRelocationAddend(), and llvm::ELF::SHT_LLVM_CALL_GRAPH_PROFILE.
Referenced by recordRelocation().
writeObject()
uint64_t ELFObjectWriter::writeObject () override virtual
Write the object file and returns the number of bytes written.
This routine is called by the assembler after layout and relaxation is complete, fixups have been evaluated and applied, and relocations generated.
Implements llvm::MCObjectWriter.
Definition at line 1407 of file ELFObjectWriter.cpp.
References llvm::MCObjectWriter::Asm, DwoOS, IsLittleEndian, OS, and Size.
Member Data Documentation
DwoOS
raw_pwrite_stream* llvm::ELFObjectWriter::DwoOS = nullptr
Definition at line 148 of file MCELFObjectWriter.h.
Referenced by ELFObjectWriter(), recordRelocation(), and writeObject().
IsLittleEndian
bool llvm::ELFObjectWriter::IsLittleEndian = false
Definition at line 154 of file MCELFObjectWriter.h.
Referenced by ELFObjectWriter(), ELFObjectWriter(), and writeObject().
OS
raw_pwrite_stream& llvm::ELFObjectWriter::OS
Definition at line 147 of file MCELFObjectWriter.h.
Referenced by ELFObjectWriter(), ELFObjectWriter(), and writeObject().
OverrideABIVersion
std::optional<uint8_t> llvm::ELFObjectWriter::OverrideABIVersion
Definition at line 156 of file MCELFObjectWriter.h.
Referenced by reset(), and setOverrideABIVersion().
Relocations
DenseMap<const MCSectionELF *, std::vector<ELFRelocationEntry> > llvm::ELFObjectWriter::Relocations
Definition at line 150 of file MCELFObjectWriter.h.
Referenced by recordRelocation(), and reset().
Renames
DenseMap<const MCSymbolELF *, const MCSymbolELF *> llvm::ELFObjectWriter::Renames
Definition at line 151 of file MCELFObjectWriter.h.
Referenced by executePostLayoutBinding(), recordRelocation(), and reset().
SeenGnuAbi
bool llvm::ELFObjectWriter::SeenGnuAbi = false
Definition at line 155 of file MCELFObjectWriter.h.
Referenced by markGnuAbi(), reset(), and seenGnuAbi().
Symvers
SmallVector<Symver, 0> llvm::ELFObjectWriter::Symvers
Definition at line 165 of file MCELFObjectWriter.h.
Referenced by llvm::MCELFStreamer::emitELFSymverDirective(), executePostLayoutBinding(), and reset().
TargetObjectWriter
std::unique_ptr<MCELFObjectTargetWriter> llvm::ELFObjectWriter::TargetObjectWriter
Definition at line 146 of file MCELFObjectWriter.h.
Referenced by ELFObjectWriter(), ELFObjectWriter(), hasRelocationAddend(), recordRelocation(), setAssembler(), and useSectionSymbol().
Weakrefs
SmallVector<const MCSymbolELF *, 0> llvm::ELFObjectWriter::Weakrefs
Definition at line 153 of file MCELFObjectWriter.h.
Referenced by llvm::MCELFStreamer::emitWeakReference(), executePostLayoutBinding(), and reset().
The documentation for this class was generated from the following files:
include/llvm/MC/MCELFObjectWriter.h
lib/MC/ELFObjectWriter.cpp