LLVM: llvm::SystemZTTIImpl Class Reference
llvm::SystemZTTIImpl Class Reference final
#include "Target/SystemZ/SystemZTargetTransformInfo.h"
Public Member Functions
SystemZTTIImpl (const SystemZTargetMachine *TM, const Function &F)
Scalar TTI Implementations
unsigned adjustInliningThreshold (const CallBase *CB) const override
InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const override
InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const override
InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const override
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth) const override
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP, OptimizationRemarkEmitter *ORE) const override
void getPeelingPreferences (Loop *L, ScalarEvolution &SE, TTI::PeelingPreferences &PP) const override
bool isLSRCostLess (const TargetTransformInfo::LSRCost &C1, const TargetTransformInfo::LSRCost &C2) const override
Vector TTI Implementations
unsigned getNumberOfRegisters (unsigned ClassID) const override
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const override
unsigned getCacheLineSize () const override
unsigned getPrefetchDistance () const override
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const override
bool enableWritePrefetching () const override
bool hasDivRemOp (Type *DataType, bool IsSigned) const override
bool prefersVectorizedAddressing () const override
bool LSRWithInstrQueries () const override
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc=true, ArrayRef< Value * > VL={}) const override
Estimate the overhead of scalarizing an instruction.
bool supportsEfficientVectorElementLoadStore () const override
bool enableInterleavedAccessVectorization () const override
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info={TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const override
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *DstTy, VectorType *SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const override
unsigned getVectorTruncCost (Type *SrcTy, Type *DstTy) const
unsigned getVectorBitmaskConversionCost (Type *SrcTy, Type *DstTy) const
unsigned getBoolVecToIntConversionCost (unsigned Opcode, Type *Dst, const Instruction *I) const
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr) const override
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, const Value *Op0, const Value *Op1) const override
bool isFoldableLoad (const LoadInst *Ld, const Instruction *&FoldedValue) const
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr) const override
InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false) const override
InstructionCost getArithmeticReductionCost (unsigned Opcode, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override
InstructionCost getMinMaxReductionCost (Intrinsic::ID IID, VectorType *Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const override
Try to calculate op costs for min/max reduction operations.
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const override
Get intrinsic cost based on arguments.
bool shouldExpandReduction (const IntrinsicInst *II) const override
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const override
InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const override
Public Member Functions inherited from llvm::BasicTTIImplBase< SystemZTTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const override
bool areInlineCompatible (const Function *Caller, const Function *Callee) const override
bool hasBranchDivergence (const Function *F=nullptr) const override
bool isSourceOfDivergence (const Value *V) const override
bool isAlwaysUniform (const Value *V) const override
bool isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const override
bool addrspacesMayAlias (unsigned AS0, unsigned AS1) const override
unsigned getFlatAddressSpace () const override
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const override
bool isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const override
unsigned getAssumedAddrSpace (const Value *V) const override
bool isSingleThreaded () const override
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const override
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const override
bool isLegalAddImmediate (int64_t imm) const override
bool isLegalAddScalableImmediate (int64_t Imm) const override
bool isLegalICmpImmediate (int64_t imm) const override
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr, int64_t ScalableOffset=0) const override
int64_t getPreferredLargeGEPBaseOffset (int64_t MinOffset, int64_t MaxOffset)
unsigned getStoreMinimumVF (unsigned VF, Type *ScalarMemTy, Type *ScalarValTy) const override
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty) const override
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty) const override
bool isNumRegsMajorCostOfLSR () const override
bool shouldDropLSRSolutionIfLessProfitable () const override
bool isProfitableLSRChainElement (Instruction *I) const override
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const override
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
bool isProfitableToHoist (Instruction *I) const override
bool useAA () const override
bool isTypeLegal (Type *Ty) const override
unsigned getRegUsageForType (Type *Ty) const override
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const override
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const override
bool shouldBuildLookupTables () const override
bool shouldBuildRelLookupTables () const override
bool haveFastSqrt (Type *Ty) const override
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const override
InstructionCost getFPOpCost (Type *Ty) const override
bool preferToKeepConstantsAttached (const Instruction &Inst, const Function &Fn) const override
unsigned getInliningThresholdMultiplier () const override
unsigned getCallerAllocaCost (const CallBase *CB, const AllocaInst *AI) const override
int getInlinerVectorBonusPercent () const override
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const override
unsigned getEpilogueVectorizationMinVF () const override
bool preferPredicateOverEpilogue (TailFoldingInfo *TFI) const override
TailFoldingStyle getPreferredTailFoldingStyle (bool IVUpdateMayOverflow=true) const override
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const override
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const override
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const override
virtual std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const override
virtual std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const override
virtual unsigned getMaxPrefetchIterationsAhead () const override
virtual bool shouldPrefetchAddressSpace (unsigned AS) const override
std::optional< unsigned > getMaxVScale () const override
std::optional< unsigned > getVScaleForTuning () const override
bool isVScaleKnownToBeAPowerOfTwo () const override
bool isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const override
bool isTargetIntrinsicWithScalarOpAtArg (Intrinsic::ID ID, unsigned ScalarOpdIdx) const override
bool isTargetIntrinsicWithOverloadTypeAtArg (Intrinsic::ID ID, int OpdIdx) const override
bool isTargetIntrinsicWithStructReturnOverloadAtField (Intrinsic::ID ID, int RetIdx) const override
InstructionCost getScalarizationOverhead (VectorType *InTy, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const override
Estimate the overhead of scalarizing an instructions unique non-constant operands.
InstructionCost getScalarizationOverhead (VectorType *RetTy, ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
Estimate the overhead of scalarizing the inputs and outputs of an instruction, with return type RetTy and arguments Args of type Tys.
std::pair< InstructionCost, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
unsigned getMaxInterleaveFactor (ElementCount VF) const override
TTI::ShuffleKind improveShuffleKindFromMask (TTI::ShuffleKind Kind, ArrayRef< int > Mask, VectorType *SrcTy, int &Index, VectorType *&SubTy) const
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index, TTI::TargetCostKind CostKind) const override
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind) const override
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *DataTy, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const override
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getExpandCompressMemoryOpCost (unsigned Opcode, Type *DataTy, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getStridedMemoryOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I) const override
InstructionCost getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
Get intrinsic cost based on argument types.
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const override
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp) const override
InstructionCost getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *) const override
InstructionCost getTreeReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind) const
Try to calculate arithmetic and shuffle op costs for reduction intrinsics.
InstructionCost getOrderedReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind) const
Try to calculate the cost of performing strict (in-order) reductions, which involves doing a sequence of floating point additions in lane order, starting with an initial value.
InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override
InstructionCost getMulAccReductionCost (bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind) const override
InstructionCost getVectorSplitCost () const
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const override
InstructionCost getPointersChainCost (ArrayRef< const Value * > Ptrs, const Value *Base, const TTI::PointersChainInfo &Info, Type *AccessTy, TTI::TargetCostKind CostKind) const override
InstructionCost getInstructionCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const override
bool isExpensiveToSpeculativelyExecute (const Instruction *I) const override
bool supportsTailCallFor (const CallBase *CB) const override
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
virtual ~TargetTransformInfoImplBase ()
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)=default
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
virtual const DataLayout & getDataLayout () const
virtual unsigned getInliningCostBenefitAnalysisSavingsMultiplier () const
virtual unsigned getInliningCostBenefitAnalysisProfitableMultiplier () const
virtual int getInliningLastCallToStaticBonus () const
virtual InstructionCost getMemcpyCost (const Instruction *I) const
virtual uint64_t getMaxMemIntrinsicInlineSizeThreshold () const
virtual BranchProbability getPredictableBranchThreshold () const
virtual InstructionCost getBranchMispredictPenalty () const
virtual bool canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const
virtual bool isLoweredToCall (const Function *F) const
virtual bool canMacroFuseCmp () const
virtual bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
virtual TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
virtual bool isLegalMaskedStore (Type *DataType, Align Alignment, unsigned AddressSpace) const
virtual bool isLegalMaskedLoad (Type *DataType, Align Alignment, unsigned AddressSpace) const
virtual bool isLegalNTStore (Type *DataType, Align Alignment) const
virtual bool isLegalNTLoad (Type *DataType, Align Alignment) const
virtual bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const
virtual bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
virtual bool isLegalMaskedGather (Type *DataType, Align Alignment) const
virtual bool forceScalarizeMaskedGather (VectorType *DataType, Align Alignment) const
virtual bool forceScalarizeMaskedScatter (VectorType *DataType, Align Alignment) const
virtual bool isLegalMaskedCompressStore (Type *DataType, Align Alignment) const
virtual bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const
virtual bool isLegalMaskedExpandLoad (Type *DataType, Align Alignment) const
virtual bool isLegalStridedLoadStore (Type *DataType, Align Alignment) const
virtual bool isLegalInterleavedAccessType (VectorType *VTy, unsigned Factor, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalMaskedVectorHistogram (Type *AddrType, Type *DataType) const
virtual bool enableOrderedReductions () const
virtual bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
virtual bool shouldBuildLookupTablesForConstant (Constant *C) const
virtual bool useColdCCForColdCall (Function &F) const
virtual bool supportsTailCalls () const
virtual bool enableAggressiveInterleaving (bool LoopHasReductions) const
virtual TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
virtual bool enableSelectOptimize () const
virtual bool shouldTreatInstructionLikeSelect (const Instruction *I) const
virtual bool enableMaskedInterleavedAccessVectorization () const
virtual bool isFPVectorizationPotentiallyUnsafe () const
virtual InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
virtual bool hasConditionalLoadStoreForType (Type *Ty, bool IsStore) const
virtual unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
virtual const char * getRegisterClassName (unsigned ClassID) const
virtual unsigned getMinVectorRegisterBitWidth () const
virtual bool shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const
virtual ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
virtual unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
virtual bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
virtual std::optional< unsigned > getMinPageSize () const
virtual InstructionCost getPartialReductionCost (unsigned Opcode, Type *InputTypeA, Type *InputTypeB, Type *AccumType, ElementCount VF, TTI::PartialReductionExtendKind OpAExtend, TTI::PartialReductionExtendKind OpBExtend, std::optional< unsigned > BinOp, TTI::TargetCostKind CostKind) const
virtual InstructionCost getAltInstrCost (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask, TTI::TargetCostKind CostKind) const
virtual InstructionCost getInsertExtractValueCost (unsigned Opcode, TTI::TargetCostKind CostKind) const
virtual InstructionCost getVPMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I) const
virtual InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
virtual bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
virtual unsigned getAtomicMemIntrinsicMaxElementSize () const
virtual Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType, bool CanCreate=true) const
virtual Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicElementSize) const
virtual void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicCpySize) const
virtual unsigned getInlineCallPenalty (const Function *F, const CallBase &Call, unsigned DefaultCallPenalty) const
virtual bool areTypesABICompatible (const Function *Caller, const Function *Callee, const ArrayRef< Type * > &Types) const
virtual unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
virtual bool isLegalToVectorizeLoad (LoadInst *LI) const
virtual bool isLegalToVectorizeStore (StoreInst *SI) const
virtual bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
virtual bool isElementTypeLegalForScalableVector (Type *Ty) const
virtual unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual bool preferFixedOverScalableIfEqualCost () const
virtual bool preferInLoopReduction (RecurKind Kind, Type *Ty) const
virtual bool preferAlternateOpcodeVectorization () const
virtual bool preferPredicatedReductionSelect () const
virtual bool preferEpilogueVectorization () const
virtual TTI::ReductionShuffle getPreferredExpandedReductionShuffle (const IntrinsicInst *II) const
virtual unsigned getGISelRematGlobalCost () const
virtual unsigned getMinTripCountTailFoldingThreshold () const
virtual bool supportsScalableVectors () const
virtual bool enableScalableVectorization () const
virtual bool hasActiveVectorLength () const
virtual bool isProfitableToSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
virtual bool hasArmWideBranch (bool) const
virtual uint64_t getFeatureMask (const Function &F) const
virtual bool isMultiversionedFunction (const Function &F) const
virtual unsigned getMaxNumArgs () const
virtual unsigned getNumBytesToPadGlobalArray (unsigned Size, Type *ArrayType) const
virtual void collectKernelLaunchBounds (const Function &F, SmallVectorImpl< std::pair< StringRef, int64_t > > &LB) const
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< SystemZTTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
virtual ~BasicTTIImplBase ()=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes inherited from llvm::BasicTTIImplBase< SystemZTTIImpl >
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 18 of file SystemZTargetTransformInfo.h.
Constructor & Destructor Documentation
SystemZTTIImpl()
llvm::SystemZTTIImpl::SystemZTTIImpl (const SystemZTargetMachine * TM, const Function & F) inline explicit
Definition at line 36 of file SystemZTargetTransformInfo.h.
References F, and llvm::TargetTransformInfoImplBase::getDataLayout().
Member Function Documentation
adjustInliningThreshold()
unsigned SystemZTTIImpl::adjustInliningThreshold (const CallBase * CB) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 78 of file SystemZTargetTransformInfo.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), countNumMemAccesses(), llvm::dbgs(), llvm::dyn_cast(), GEP, llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), I, InstrCount, instructions, llvm::isa(), isUsedAsMemCpySource(), LLVM_DEBUG, OpIdx, and Ptr.
enableInterleavedAccessVectorization()
bool llvm::SystemZTTIImpl::enableInterleavedAccessVectorization () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 93 of file SystemZTargetTransformInfo.h.
enableWritePrefetching()
bool llvm::SystemZTTIImpl::enableWritePrefetching () const inline override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 83 of file SystemZTargetTransformInfo.h.
getArithmeticInstrCost()
InstructionCost SystemZTTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info = {TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info = {TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 542 of file SystemZTargetTransformInfo.cpp.
References A(), llvm::CallingConv::C, llvm::cast(), CostKind, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getArithmeticInstrCost(), getArithmeticInstrCost(), getNumVectorRegs(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getScalarizationOverhead(), llvm::ConstantInt::getValue(), I, llvm::APInt::isNegatedPowerOf2(), llvm::APInt::isPowerOf2(), and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by getArithmeticInstrCost().
getArithmeticReductionCost()
InstructionCost SystemZTTIImpl::getArithmeticReductionCost (unsigned Opcode, VectorType * Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1461 of file SystemZTargetTransformInfo.cpp.
References CostKind, customCostReductions(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getArithmeticReductionCost(), getFastReductionCost(), getIntAddReductionCost(), getNumVectorRegs(), llvm::TargetTransformInfo::requiresOrderedReduction(), and llvm::SystemZ::VectorBits.
getBoolVecToIntConversionCost()
unsigned SystemZTTIImpl::getBoolVecToIntConversionCost (unsigned Opcode, Type * Dst, const Instruction * I) const
Definition at line 875 of file SystemZTargetTransformInfo.cpp.
References llvm::cast(), getCmpOpsType(), getNumVectorRegs(), getVectorBitmaskConversionCost(), and I.
Referenced by getCastInstrCost().
getCacheLineSize()
unsigned llvm::SystemZTTIImpl::getCacheLineSize () const inline override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 77 of file SystemZTargetTransformInfo.h.
getCastInstrCost()
InstructionCost SystemZTTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 891 of file SystemZTargetTransformInfo.cpp.
References llvm::cast(), CostKind, llvm::dyn_cast(), getBoolVecToIntConversionCost(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getCastInstrCost(), getCastInstrCost(), getCmpOpsType(), getElSizeLog2Diff(), getNumVectorRegs(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getScalarizationOverhead(), getVectorTruncCost(), I, llvm::isa(), llvm::Type::isFloatingPointTy(), llvm::TargetTransformInfo::TCK_CodeSize, and llvm::TargetTransformInfo::TCK_SizeAndLatency.
Referenced by getCastInstrCost().
getCmpSelInstrCost()
InstructionCost SystemZTTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info = {TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info = {TTI::OK_AnyValue, TTI::OP_None}, const Instruction * I = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1089 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), CostKind, llvm::dyn_cast(), llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UNO, getCmpOpsType(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getCmpSelInstrCost(), getNumVectorRegs(), getOperandsExtensionCost(), getVectorBitmaskConversionCost(), I, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, and llvm::TargetTransformInfo::TCK_RecipThroughput.
getInterleavedMemoryOpCost()
InstructionCost SystemZTTIImpl::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond = false, bool UseMaskForGaps = false) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1380 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::cast(), CostKind, llvm::BitVector::count(), llvm::divideCeil(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getInterleavedMemoryOpCost(), getNumVectorRegs(), getScalarSizeInBits(), llvm::isa(), and llvm::BitVector::set().
getIntImmCost()
InstructionCost SystemZTTIImpl::getIntImmCost (const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 152 of file SystemZTargetTransformInfo.cpp.
References assert(), CostKind, llvm::isInt(), llvm::isUInt(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCostInst(), and getIntImmCostIntrin().
getIntImmCostInst()
InstructionCost SystemZTTIImpl::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind, Instruction * Inst = nullptr) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 186 of file SystemZTargetTransformInfo.cpp.
References assert(), CostKind, getIntImmCost(), llvm::isInt(), llvm::isUInt(), llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, and TII.
getIntImmCostIntrin()
InstructionCost SystemZTTIImpl::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 307 of file SystemZTargetTransformInfo.cpp.
References assert(), CostKind, getIntImmCost(), llvm::isInt(), llvm::isUInt(), and llvm::TargetTransformInfo::TCC_Free.
getIntrinsicInstrCost()
InstructionCost SystemZTTIImpl::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) const override virtual
Get intrinsic cost based on arguments.
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1518 of file SystemZTargetTransformInfo.cpp.
References CostKind, llvm::IntrinsicCostAttributes::getArgTypes(), llvm::IntrinsicCostAttributes::getID(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getIntrinsicInstrCost(), llvm::IntrinsicCostAttributes::getReturnType(), and getVectorIntrinsicInstrCost().
getMemoryOpCost()
InstructionCost SystemZTTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo = {TTI::OK_AnyValue, TTI::OP_None}, const Instruction * I = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1303 of file SystemZTargetTransformInfo.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, assert(), llvm::cast(), CostKind, llvm::BasicTTIImplBase< SystemZTTIImpl >::DL, llvm::dyn_cast(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getMemoryOpCost(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getNumberOfParts(), llvm::User::getNumOperands(), getNumVectorRegs(), llvm::User::getOperand(), llvm::Value::hasOneUse(), I, llvm::isa(), isBswapIntrinsicCall(), isFoldableLoad(), llvm::TargetTransformInfo::TCK_RecipThroughput, and llvm::Value::user_begin().
Referenced by getUnrollingPreferences().
getMinMaxReductionCost()
InstructionCost SystemZTTIImpl::getMinMaxReductionCost (Intrinsic::ID IID, VectorType * Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const override virtual
Try to calculate op costs for min/max reduction operations.
Parameters
CondTy Conditional type for the Select instruction.
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1488 of file SystemZTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< SystemZTTIImpl >::getMinMaxReductionCost(), getNumVectorRegs(), and llvm::SystemZ::VectorBits.
getMinPrefetchStride()
unsigned SystemZTTIImpl::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 464 of file SystemZTargetTransformInfo.cpp.
getNumberOfRegisters()
unsigned SystemZTTIImpl::getNumberOfRegisters (unsigned ClassID) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 439 of file SystemZTargetTransformInfo.cpp.
References llvm::Vector.
getPeelingPreferences()
void SystemZTTIImpl::getPeelingPreferences (Loop * L, ScalarEvolution & SE, TTI::PeelingPreferences & PP) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 421 of file SystemZTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< SystemZTTIImpl >::getPeelingPreferences().
getPopcntSupport()
TargetTransformInfo::PopcntSupportKind SystemZTTIImpl::getPopcntSupport (unsigned TyWidth) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 358 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
getPrefetchDistance()
unsigned llvm::SystemZTTIImpl::getPrefetchDistance () const inline override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 78 of file SystemZTargetTransformInfo.h.
getRegisterBitWidth()
TypeSize SystemZTTIImpl::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 451 of file SystemZTargetTransformInfo.cpp.
References llvm::TypeSize::getFixed(), llvm::TypeSize::getScalable(), llvm_unreachable, llvm::TargetTransformInfo::RGK_FixedWidthVector, llvm::TargetTransformInfo::RGK_ScalableVector, and llvm::TargetTransformInfo::RGK_Scalar.
getScalarizationOverhead()
InstructionCost SystemZTTIImpl::getScalarizationOverhead (VectorType * InTy, const APInt & DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc = true, ArrayRef< Value * > VL = {}) const override virtual
Estimate the overhead of scalarizing an instruction.
Insert and Extract are set if the demanded result elements need to be inserted and/or extracted from vectors.
FIXME: a bitfield is not a reasonable abstraction for talking about which elements are needed from a scalable vector
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 494 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::cast(), CostKind, llvm::ArrayRef< T >::empty(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getScalarizationOverhead(), InstructionCost, isFreeEltLoad(), and llvm::ArrayRef< T >::size().
getShuffleCost()
InstructionCost SystemZTTIImpl::getShuffleCost (TTI::ShuffleKind Kind, VectorType * DstTy, VectorType * SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType * SubTp, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 728 of file SystemZTargetTransformInfo.cpp.
References CostKind, getNumVectorRegs(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getShuffleCost(), llvm::BasicTTIImplBase< SystemZTTIImpl >::improveShuffleKindFromMask(), llvm::TargetTransformInfo::SK_Broadcast, and llvm::TargetTransformInfo::SK_ExtractSubvector.
getUnrollingPreferences()
void SystemZTTIImpl::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP, OptimizationRemarkEmitter * ORE) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 365 of file SystemZTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::UnrollingPreferences::AllowExpensiveTripCount, llvm::cast(), llvm::TargetTransformInfo::UnrollingPreferences::DefaultUnrollRuntimeCount, F, llvm::TargetTransformInfo::UnrollingPreferences::Force, llvm::TargetTransformInfo::UnrollingPreferences::FullUnrollMaxCount, getCalledFunction(), getMemoryOpCost(), llvm::InstructionCost::getValue(), I, llvm::isa(), llvm::TargetTransformInfoImplBase::isLoweredToCall(), llvm::TargetTransformInfo::UnrollingPreferences::MaxCount, llvm::TargetTransformInfo::UnrollingPreferences::Partial, llvm::TargetTransformInfo::UnrollingPreferences::PartialThreshold, llvm::TargetTransformInfo::UnrollingPreferences::Runtime, and llvm::TargetTransformInfo::TCK_RecipThroughput.
getVectorBitmaskConversionCost()
unsigned SystemZTTIImpl::getVectorBitmaskConversionCost (Type * SrcTy, Type * DstTy) const
Definition at line 823 of file SystemZTargetTransformInfo.cpp.
References assert(), getElSizeLog2Diff(), getNumVectorRegs(), llvm::Type::getScalarSizeInBits(), getVectorTruncCost(), and llvm::Type::isVectorTy().
Referenced by getBoolVecToIntConversionCost(), and getCmpSelInstrCost().
getVectorInstrCost() [1/3]
InstructionCost llvm::BasicTTIImplBase< SystemZTTIImpl >::getVectorInstrCost (const Instruction & I, Type * Val, TTI::TargetCostKind CostKind, unsigned Index) const inline override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1435 of file BasicTTIImpl.h.
getVectorInstrCost() [2/3]
InstructionCost SystemZTTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, const Value * Op0, const Value * Op1) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1184 of file SystemZTargetTransformInfo.cpp.
References CostKind, getScalarSizeInBits(), llvm::BasicTTIImplBase< SystemZTTIImpl >::getVectorInstrCost(), isFreeEltLoad(), and llvm::Type::isIntOrIntVectorTy().
getVectorInstrCost() [3/3]
InstructionCost llvm::BasicTTIImplBase< SystemZTTIImpl >::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, Value * Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const inline override virtual
Parameters
ScalarUserAndIdx encodes the information about extracts from a vector with 'Scalar' being the value being extracted,'User' being the user of the extract(nullptr if user is not known before vectorization) and 'Idx' being the extract lane.
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 1426 of file BasicTTIImpl.h.
getVectorTruncCost()
unsigned SystemZTTIImpl::getVectorTruncCost (Type * SrcTy, Type * DstTy) const
Definition at line 782 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::cast(), getElSizeLog2Diff(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), getNumElements(), getNumVectorRegs(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Type::isVectorTy(), and P.
Referenced by getCastInstrCost(), and getVectorBitmaskConversionCost().
hasDivRemOp()
bool SystemZTTIImpl::hasDivRemOp (Type * DataType, bool IsSigned) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 481 of file SystemZTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< SystemZTTIImpl >::DL, and llvm::EVT::isScalarInteger().
isFoldableLoad()
bool SystemZTTIImpl::isFoldableLoad (const LoadInst * Ld, const Instruction *& FoldedValue) const
Definition at line 1215 of file SystemZTargetTransformInfo.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), getScalarSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::isa(), and llvm::Value::user_begin().
Referenced by getMemoryOpCost().
isLSRCostLess()
bool SystemZTTIImpl::isLSRCostLess (const TargetTransformInfo::LSRCost & C1, const TargetTransformInfo::LSRCost & C2) const override virtual
Reimplemented from llvm::BasicTTIImplBase< SystemZTTIImpl >.
Definition at line 426 of file SystemZTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::TargetTransformInfo::LSRCost::Insns, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
LSRWithInstrQueries()
bool llvm::SystemZTTIImpl::LSRWithInstrQueries () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 87 of file SystemZTargetTransformInfo.h.
prefersVectorizedAddressing()
bool llvm::SystemZTTIImpl::prefersVectorizedAddressing () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 86 of file SystemZTargetTransformInfo.h.
shouldExpandReduction()
bool SystemZTTIImpl::shouldExpandReduction (const IntrinsicInst * II) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 1527 of file SystemZTargetTransformInfo.cpp.
References llvm::cast(), II, and llvm::SystemZ::VectorBits.
supportsEfficientVectorElementLoadStore()
bool llvm::SystemZTTIImpl::supportsEfficientVectorElementLoadStore () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 92 of file SystemZTargetTransformInfo.h.
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZTargetTransformInfo.h
lib/Target/SystemZ/SystemZTargetTransformInfo.cpp