LLVM: llvm::xray::MetadataRecord Class Reference
llvm::xray::MetadataRecord Class Reference
#include "llvm/XRay/FDRRecords.h"
Public Types
enum class MetadataType : unsigned {
Unknown , BufferExtents , WallClockTime , NewCPUId ,
TSCWrap , CustomEvent , CallArg , PIDEntry ,
NewBuffer , EndOfBuffer , TypedEvent
}
Public Types inherited from llvm::xray::Record
enum class RecordKind {
RK_Metadata , RK_Metadata_BufferExtents , RK_Metadata_WallClockTime , RK_Metadata_NewCPUId ,
RK_Metadata_TSCWrap , RK_Metadata_CustomEvent , RK_Metadata_CustomEventV5 , RK_Metadata_CallArg ,
RK_Metadata_PIDEntry , RK_Metadata_NewBuffer , RK_Metadata_EndOfBuffer , RK_Metadata_TypedEvent ,
RK_Metadata_LastMetadata , RK_Function
}
Public Member Functions
MetadataRecord (RecordKind T, MetadataType M)
MetadataType metadataType () const
virtual ~MetadataRecord ()=default
Public Member Functions inherited from llvm::xray::Record
Record (const Record &)=delete
Record (Record &&)=delete
Record & operator= (const Record &)=delete
Record & operator= (Record &&)=delete
Record (RecordKind T)
RecordKind getRecordType () const
virtual Error apply (RecordVisitor &V)=0
virtual ~Record ()=default
Static Public Member Functions
static bool classof (const Record *R)
Static Public Member Functions inherited from llvm::xray::Record
static LLVM_ABI StringRef kindToString (RecordKind K)
Static Protected Attributes
static constexpr int kMetadataBodySize = 15
Friends
class RecordInitializer
Detailed Description
Definition at line 72 of file FDRRecords.h.
Member Enumeration Documentation
MetadataType
enum class llvm::xray::MetadataRecord::MetadataType : unsigned strong
Enumerator
Unknown
BufferExtents
WallClockTime
NewCPUId
TSCWrap
CustomEvent
CallArg
PIDEntry
NewBuffer
EndOfBuffer
TypedEvent
Definition at line 74 of file FDRRecords.h.
Constructor & Destructor Documentation
MetadataRecord()
llvm::xray::MetadataRecord::MetadataRecord (RecordKind T, MetadataType M) inline explicit
Definition at line 96 of file FDRRecords.h.
References llvm::xray::Record::Record().
Referenced by llvm::xray::BufferExtents::BufferExtents(), llvm::xray::BufferExtents::BufferExtents(), llvm::xray::CallArgRecord::CallArgRecord(), llvm::xray::CallArgRecord::CallArgRecord(), llvm::xray::CustomEventRecord::CustomEventRecord(), llvm::xray::CustomEventRecord::CustomEventRecord(), llvm::xray::CustomEventRecordV5::CustomEventRecordV5(), llvm::xray::CustomEventRecordV5::CustomEventRecordV5(), llvm::xray::EndBufferRecord::EndBufferRecord(), llvm::xray::NewBufferRecord::NewBufferRecord(), llvm::xray::NewBufferRecord::NewBufferRecord(), llvm::xray::NewCPUIDRecord::NewCPUIDRecord(), llvm::xray::NewCPUIDRecord::NewCPUIDRecord(), llvm::xray::PIDRecord::PIDRecord(), llvm::xray::PIDRecord::PIDRecord(), llvm::xray::TSCWrapRecord::TSCWrapRecord(), llvm::xray::TSCWrapRecord::TSCWrapRecord(), llvm::xray::TypedEventRecord::TypedEventRecord(), llvm::xray::TypedEventRecord::TypedEventRecord(), llvm::xray::WallclockRecord::WallclockRecord(), and llvm::xray::WallclockRecord::WallclockRecord().
~MetadataRecord()
virtual llvm::xray::MetadataRecord::~MetadataRecord () virtual default
Member Function Documentation
classof()
bool llvm::xray::MetadataRecord::classof (const Record * R) inline static
Definition at line 98 of file FDRRecords.h.
References llvm::xray::Record::Record(), llvm::xray::Record::RK_Metadata, and llvm::xray::Record::RK_Metadata_LastMetadata.
metadataType()
MetadataType llvm::xray::MetadataRecord::metadataType () const inline
Definition at line 103 of file FDRRecords.h.
Friends And Related Symbol Documentation
RecordInitializer
friend class RecordInitializer friend
Definition at line 90 of file FDRRecords.h.
References RecordInitializer.
Referenced by RecordInitializer.
Member Data Documentation
kMetadataBodySize
int llvm::xray::MetadataRecord::kMetadataBodySize = 15 static constexpr protected
Definition at line 89 of file FDRRecords.h.
Referenced by llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), and llvm::xray::RecordInitializer::visit().
The documentation for this class was generated from the following file:
include/llvm/XRay/FDRRecords.h