LLVM: llvm::MemProfContextDisambiguation Class Reference
llvm::MemProfContextDisambiguation Class Reference
#include "llvm/Transforms/IPO/MemProfContextDisambiguation.h"
Public Member Functions
MemProfContextDisambiguation (const ModuleSummaryIndex *Summary=nullptr, bool isSamplePGO=false)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
void run (ModuleSummaryIndex &Index, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> isPrevailing)
Public Member Functions inherited from llvm::PassInfoMixin< MemProfContextDisambiguation >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MemProfContextDisambiguation >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 30 of file MemProfContextDisambiguation.h.
Constructor & Destructor Documentation
MemProfContextDisambiguation()
MemProfContextDisambiguation::MemProfContextDisambiguation (const ModuleSummaryIndex * Summary = nullptr, bool isSamplePGO = false)
Definition at line 5707 of file MemProfContextDisambiguation.cpp.
References All, Alloc, AllocIdForDot, assert(), Context, ContextIdForDot, DotGraphScope, llvm::errorOrToExpected(), llvm::errs(), llvm::MemoryBuffer::getFile(), llvm::getModuleSummaryIndex(), if(), llvm::logAllUnhandledErrors(), MemProfImportSummary, and llvm::report_fatal_error().
Member Function Documentation
run() [1/2]
PreservedAnalyses MemProfContextDisambiguation::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 5753 of file MemProfContextDisambiguation.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
run() [2/2]
void MemProfContextDisambiguation::run (ModuleSummaryIndex & Index, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> isPrevailing)
Definition at line 5764 of file MemProfContextDisambiguation.cpp.
References assert(), and llvm::SupportsHotColdNew.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/MemProfContextDisambiguation.h
lib/Transforms/IPO/MemProfContextDisambiguation.cpp