LLVM: llvm::DbgVariableRecord::location_op_iterator Class Reference
llvm::DbgVariableRecord::location_op_iterator Class Reference
Iterator for ValueAsMetadata that internally uses direct pointer iteration over either a ValueAsMetadata* or a ValueAsMetadata**, dereferencing to the ValueAsMetadata .
#include "llvm/IR/DebugProgramInstruction.h"
Public Member Functions
location_op_iterator (ValueAsMetadata *SingleIter)
location_op_iterator (ValueAsMetadata **MultiIter)
location_op_iterator (const location_op_iterator &R)
location_op_iterator & operator= (const location_op_iterator &R)
bool operator== (const location_op_iterator &RHS) const
const Value * operator* () const
Value * operator* ()
location_op_iterator & operator++ ()
location_op_iterator & operator-- ()
Public Member Functions inherited from llvm::iterator_facade_base< location_op_iterator, std::bidirectional_iterator_tag, Value * >
location_op_iterator operator+ (std::ptrdiff_t n) const
location_op_iterator operator- (std::ptrdiff_t n) const
location_op_iterator & operator++ ()
location_op_iterator & operator-- ()
bool operator!= (const location_op_iterator &RHS) const
bool operator> (const location_op_iterator &RHS) const
bool operator<= (const location_op_iterator &RHS) const
bool operator>= (const location_op_iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< location_op_iterator, std::bidirectional_iterator_tag, Value * >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Protected Types inherited from llvm::iterator_facade_base< location_op_iterator, std::bidirectional_iterator_tag, Value * >
enum
Detailed Description
Iterator for ValueAsMetadata that internally uses direct pointer iteration over either a ValueAsMetadata* or a ValueAsMetadata**, dereferencing to the ValueAsMetadata .
Definition at line 370 of file DebugProgramInstruction.h.
Constructor & Destructor Documentation
location_op_iterator() [1/3]
llvm::DbgVariableRecord::location_op_iterator::location_op_iterator (ValueAsMetadata * SingleIter) inline
Definition at line 376 of file DebugProgramInstruction.h.
Referenced by location_op_iterator(), operator++(), operator--(), operator=(), and operator==().
location_op_iterator() [2/3]
llvm::DbgVariableRecord::location_op_iterator::location_op_iterator (ValueAsMetadata ** MultiIter) inline
Definition at line 377 of file DebugProgramInstruction.h.
location_op_iterator() [3/3]
llvm::DbgVariableRecord::location_op_iterator::location_op_iterator (const location_op_iterator & R) inline
Definition at line 379 of file DebugProgramInstruction.h.
References location_op_iterator().
Member Function Documentation
operator*() [1/2]
Value * llvm::DbgVariableRecord::location_op_iterator::operator* () inline
Definition at line 393 of file DebugProgramInstruction.h.
References llvm::cast(), llvm::ValueAsMetadata::getValue(), llvm::isa(), and llvm::DbgVariableRecord::Value.
operator*() [2/2]
const Value * llvm::DbgVariableRecord::location_op_iterator::operator* () const inline
Definition at line 387 of file DebugProgramInstruction.h.
References llvm::cast(), llvm::ValueAsMetadata::getValue(), llvm::isa(), and llvm::DbgVariableRecord::Value.
operator++()
location_op_iterator & llvm::DbgVariableRecord::location_op_iterator::operator++ () inline
Definition at line 399 of file DebugProgramInstruction.h.
References llvm::cast(), llvm::dyn_cast(), and location_op_iterator().
operator--()
location_op_iterator & llvm::DbgVariableRecord::location_op_iterator::operator-- () inline
Definition at line 406 of file DebugProgramInstruction.h.
References llvm::cast(), llvm::dyn_cast(), and location_op_iterator().
operator=()
location_op_iterator & llvm::DbgVariableRecord::location_op_iterator::operator= (const location_op_iterator & R) inline
Definition at line 380 of file DebugProgramInstruction.h.
References location_op_iterator().
operator==()
bool llvm::DbgVariableRecord::location_op_iterator::operator== (const location_op_iterator & RHS) const inline
Definition at line 384 of file DebugProgramInstruction.h.
References location_op_iterator(), and RHS.
The documentation for this class was generated from the following file:
include/llvm/IR/DebugProgramInstruction.h