LLVM: llvm::PredicateInfoBuilder Class Reference
llvm::PredicateInfoBuilder Class Reference
Public Member Functions
PredicateInfoBuilder (PredicateInfo &PI, Function &F, DominatorTree &DT, AssumptionCache &AC, BumpPtrAllocator &Allocator)
void buildPredicateInfo ()
Detailed Description
Definition at line 196 of file PredicateInfo.cpp.
Constructor & Destructor Documentation
PredicateInfoBuilder()
llvm::PredicateInfoBuilder::PredicateInfoBuilder (PredicateInfo & PI, Function & F, DominatorTree & DT, AssumptionCache & AC, BumpPtrAllocator & Allocator) inline
Definition at line 246 of file PredicateInfo.cpp.
Member Function Documentation
buildPredicateInfo()
void llvm::PredicateInfoBuilder::buildPredicateInfo ()
Definition at line 457 of file PredicateInfo.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::BranchInst::getSuccessor(), II, and llvm::BranchInst::isConditional().
The documentation for this class was generated from the following file:
lib/Transforms/Utils/PredicateInfo.cpp