LLVM: llvm::MachineBlockPlacementStatsPass Class Reference
llvm::MachineBlockPlacementStatsPass Class Reference
#include "llvm/CodeGen/MachineBlockPlacement.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< MachineBlockPlacementStatsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< MachineBlockPlacementStatsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 33 of file MachineBlockPlacement.h.
Member Function Documentation
isRequired()
bool llvm::MachineBlockPlacementStatsPass::isRequired () inline static
Definition at line 39 of file MachineBlockPlacement.h.
run()
block placement Basic Block Placement false PreservedAnalyses MachineBlockPlacementStatsPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 3905 of file MachineBlockPlacement.cpp.
References llvm::PreservedAnalyses::all(), llvm::MachineBlockFrequencyAnalysis::run(), and run().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineBlockPlacement.h
lib/CodeGen/MachineBlockPlacement.cpp