LLVM: llvm::ModulePass Class Reference
llvm::ModulePass Class Reference abstract
ModulePass class - This class is used to implement unstructured interprocedural optimizations and analyses.
#include "llvm/Pass.h"
Public Member Functions
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
virtual bool runOnModule (Module &M)=0
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Protected Member Functions
bool skipModule (const Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
ModulePass class - This class is used to implement unstructured interprocedural optimizations and analyses.
ModulePasses may do anything they want to the program.
Definition at line 251 of file Pass.h.
Constructor & Destructor Documentation
ModulePass()
llvm::ModulePass::ModulePass (char & pid) inline explicit
Definition at line 253 of file Pass.h.
References llvm::Pass::Pass(), and llvm::PT_Module.
Referenced by llvm::CallGraphWrapperPass::CallGraphWrapperPass(), llvm::DOTGraphTraitsModulePrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsModulePrinterWrapperPass(), llvm::DOTGraphTraitsModuleViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsModuleViewerWrapperPass(), DXILDataScalarizationLegacy::DXILDataScalarizationLegacy(), llvm::DXILFinalizeLinkageLegacy::DXILFinalizeLinkageLegacy(), DXILIntrinsicExpansionLegacy::DXILIntrinsicExpansionLegacy(), llvm::DXILMetadataAnalysisWrapperPass::DXILMetadataAnalysisWrapperPass(), llvm::DXILResourceBindingWrapperPass::DXILResourceBindingWrapperPass(), llvm::DXILResourceWrapperPass::DXILResourceWrapperPass(), llvm::FPPassManager::FPPassManager(), llvm::GlobalsAAWrapperPass::GlobalsAAWrapperPass(), llvm::ImmutablePass::ImmutablePass(), llvm::ModuleSummaryIndexWrapperPass::ModuleSummaryIndexWrapperPass(), llvm::dxil::RootSignatureAnalysisWrapper::RootSignatureAnalysisWrapper(), llvm::dxil::ShaderFlagsAnalysisWrapper::ShaderFlagsAnalysisWrapper(), llvm::SPIRVModuleAnalysis::SPIRVModuleAnalysis(), llvm::StackSafetyGlobalInfoWrapperPass::StackSafetyGlobalInfoWrapperPass(), and StaticDataAnnotator::StaticDataAnnotator().
~ModulePass()
ModulePass::~ModulePass () override default
References createPrinterPass(), and llvm::Pass::Pass().
Member Function Documentation
assignPassManager()
void ModulePass::assignPassManager (PMStack & PMS, PassManagerType T) override virtual
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
Reimplemented from llvm::Pass.
Definition at line 1693 of file LegacyPassManager.cpp.
References llvm::PMDataManager::add(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_ModulePassManager, llvm::PMStack::pop(), T, and llvm::PMStack::top().
Referenced by runOnModule().
createPrinterPass()
Pass * ModulePass::createPrinterPass (raw_ostream & OS, const std::string & Banner) const override virtual
createPrinterPass - Get a module printer pass.
Implements llvm::Pass.
Definition at line 50 of file Pass.cpp.
Referenced by ~ModulePass().
getPotentialPassManagerType()
PassManagerType ModulePass::getPotentialPassManagerType () const override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 55 of file Pass.cpp.
Referenced by runOnModule().
runOnModule()
virtual bool llvm::ModulePass::runOnModule (Module & M) pure virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implemented in DXILDataScalarizationLegacy, DXILIntrinsicExpansionLegacy, llvm::CallGraphWrapperPass, llvm::DOTGraphTraitsModulePrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsModuleViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::dxil::RootSignatureAnalysisWrapper, llvm::dxil::ShaderFlagsAnalysisWrapper, llvm::DXILFinalizeLinkageLegacy, llvm::DXILMetadataAnalysisWrapperPass, llvm::DXILResourceBindingWrapperPass, llvm::DXILResourceWrapperPass, llvm::FPPassManager, llvm::GlobalsAAWrapperPass, llvm::ImmutablePass, llvm::IRSimilarityIdentifierWrapperPass, llvm::ModuleSummaryIndexWrapperPass, llvm::SPIRVModuleAnalysis, llvm::StackSafetyGlobalInfoWrapperPass, and StaticDataAnnotator.
References assignPassManager(), getPotentialPassManagerType(), skipModule(), and T.
skipModule()
bool ModulePass::skipModule (const Module & M) const protected
Optional passes call this function to check whether the pass should be skipped.
This is the case when optimization bisect is over the limit.
Definition at line 63 of file Pass.cpp.
Referenced by runOnModule().
The documentation for this class was generated from the following files:
include/llvm/Pass.h
lib/IR/LegacyPassManager.cpp
lib/SandboxIR/Pass.cpp