LLVM: llvm::sandboxir::Pass Class Reference
llvm::sandboxir::Pass Class Reference
The base class of a Sandbox IR Pass.
#include "llvm/SandboxIR/Pass.h"
Public Member Functions
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()
StringRef getName () const
\Returns the name of the pass.
virtual void print (raw_ostream &OS) const
virtual LLVM_DUMP_METHOD void dump () const
virtual void printPipeline (raw_ostream &OS) const
Similar to print() but adds a newline. Used for testing.
Protected Attributes
const std::string Name
The pass name.
Friends
raw_ostream & operator<< (raw_ostream &OS, const Pass &Pass)
Detailed Description
The base class of a Sandbox IR Pass.
Definition at line 46 of file Pass.h.
Constructor & Destructor Documentation
Pass()
llvm::sandboxir::Pass::Pass (StringRef Name) inline
Name can't contain any spaces or start with '-'.
Definition at line 54 of file Pass.h.
References assert(), and Name.
Referenced by llvm::sandboxir::FunctionPass::FunctionPass(), operator<<, and llvm::sandboxir::RegionPass::RegionPass().
~Pass()
virtual llvm::sandboxir::Pass::~Pass () inline virtual
Definition at line 59 of file Pass.h.
Member Function Documentation
dump()
virtual LLVM_DUMP_METHOD void llvm::sandboxir::Pass::dump () const virtual
Reimplemented in llvm::sandboxir::PassManager< FunctionPass, FunctionPass >, and llvm::sandboxir::PassManager< RegionPass, RegionPass >.
References LLVM_DUMP_METHOD.
getName()
StringRef llvm::sandboxir::Pass::getName () const inline
\Returns the name of the pass.
Definition at line 61 of file Pass.h.
References Name.
Referenced by llvm::sandboxir::RegionsFromBBs::printPipeline(), llvm::sandboxir::RegionsFromMetadata::printPipeline(), and llvm::sandboxir::SeedCollection::printPipeline().
print()
virtual void llvm::sandboxir::Pass::print (raw_ostream & OS) const inline virtual
Reimplemented in llvm::sandboxir::PassManager< FunctionPass, FunctionPass >, and llvm::sandboxir::PassManager< RegionPass, RegionPass >.
Definition at line 67 of file Pass.h.
References Name.
Referenced by llvm::sandboxir::PassManager< ParentPass, ContainedPass >::print().
printPipeline()
virtual void llvm::sandboxir::Pass::printPipeline (raw_ostream & OS) const inline virtual
Similar to print() but adds a newline. Used for testing.
Reimplemented in llvm::sandboxir::PassManager< FunctionPass, FunctionPass >, llvm::sandboxir::PassManager< RegionPass, RegionPass >, llvm::sandboxir::RegionsFromBBs, llvm::sandboxir::RegionsFromMetadata, and llvm::sandboxir::SeedCollection.
Definition at line 71 of file Pass.h.
References Name.
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const Pass & Pass) friend
Definition at line 63 of file Pass.h.
References Pass().
Member Data Documentation
Name
const std::string llvm::sandboxir::Pass::Name protected
The pass name.
This is also used as a command-line flag and should not contain whitespaces.
Definition at line 50 of file Pass.h.
Referenced by llvm::sandboxir::FunctionPass::FunctionPass(), llvm::sandboxir::FunctionPassManager::FunctionPassManager(), llvm::sandboxir::FunctionPassManager::FunctionPassManager(), getName(), Pass(), print(), printPipeline(), llvm::sandboxir::RegionPass::RegionPass(), llvm::sandboxir::RegionPassManager::RegionPassManager(), and llvm::sandboxir::RegionPassManager::RegionPassManager().
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Pass.h