LLVM: llvm::codeview::HotPatchFuncSym Class Reference
llvm::codeview::HotPatchFuncSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
HotPatchFuncSym (SymbolRecordKind Kind)
HotPatchFuncSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
TypeIndex Function
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 180 of file SymbolRecord.h.
Constructor & Destructor Documentation
HotPatchFuncSym() [1/2]
llvm::codeview::HotPatchFuncSym::HotPatchFuncSym (SymbolRecordKind Kind) inline explicit
Definition at line 182 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by HotPatchFuncSym().
HotPatchFuncSym() [2/2]
llvm::codeview::HotPatchFuncSym::HotPatchFuncSym (uint32_t RecordOffset) inline
Definition at line 183 of file SymbolRecord.h.
References HotPatchFuncSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Data Documentation
Function
TypeIndex llvm::codeview::HotPatchFuncSym::Function
Definition at line 189 of file SymbolRecord.h.
Name
StringRef llvm::codeview::HotPatchFuncSym::Name
Definition at line 190 of file SymbolRecord.h.
RecordOffset
uint32_t llvm::codeview::HotPatchFuncSym::RecordOffset = 0
Definition at line 192 of file SymbolRecord.h.
Referenced by HotPatchFuncSym().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h