LLVM: llvm::CollectorMetadataAnalysis Class Reference
llvm::CollectorMetadataAnalysis Class Reference
An analysis pass which caches information about the entire Module.
#include "llvm/CodeGen/GCMetadata.h"
Public Types
using Result = GCStrategyMap
Public Member Functions
Result run (Module &M, ModuleAnalysisManager &MAM)
Public Member Functions inherited from llvm::PassInfoMixin< CollectorMetadataAnalysis >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Friends
struct AnalysisInfoMixin< CollectorMetadataAnalysis >
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< CollectorMetadataAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< CollectorMetadataAnalysis >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
An analysis pass which caches information about the entire Module.
Records a cache of the 'active' gc strategy objects for the current Module.
Definition at line 201 of file GCMetadata.h.
Member Typedef Documentation
Result
using llvm::CollectorMetadataAnalysis::Result = GCStrategyMap
Definition at line 207 of file GCMetadata.h.
Member Function Documentation
run()
CollectorMetadataAnalysis::Result CollectorMetadataAnalysis::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 38 of file GCMetadata.cpp.
References F, llvm::getGCStrategy(), MAM, and llvm::GCStrategyMap::try_emplace().
Friends And Related Symbol Documentation
AnalysisInfoMixin< CollectorMetadataAnalysis >
friend struct AnalysisInfoMixin< CollectorMetadataAnalysis > friend
Definition at line 196 of file GCMetadata.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::contains().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GCMetadata.h
lib/CodeGen/GCMetadata.cpp