LLVM: llvm::GEPNoWrapFlags Class Reference
llvm::GEPNoWrapFlags Class Reference
Represents flags for the getelementptr instruction/expression.
#include "llvm/IR/GEPNoWrapFlags.h"
Public Member Functions
GEPNoWrapFlags ()
GEPNoWrapFlags (bool IsInBounds)
unsigned getRaw () const
bool isInBounds () const
bool hasNoUnsignedSignedWrap () const
bool hasNoUnsignedWrap () const
GEPNoWrapFlags withoutInBounds () const
GEPNoWrapFlags withoutNoUnsignedSignedWrap () const
GEPNoWrapFlags withoutNoUnsignedWrap () const
GEPNoWrapFlags intersectForOffsetAdd (GEPNoWrapFlags Other) const
Given (gep (gep p, x), y), determine the nowrap flags for (gep p, x+y).
bool operator== (GEPNoWrapFlags Other) const
bool operator!= (GEPNoWrapFlags Other) const
GEPNoWrapFlags operator& (GEPNoWrapFlags Other) const
GEPNoWrapFlags operator| (GEPNoWrapFlags Other) const
GEPNoWrapFlags & operator&= (GEPNoWrapFlags Other)
GEPNoWrapFlags & operator|= (GEPNoWrapFlags Other)
Static Public Member Functions
static GEPNoWrapFlags none ()
static GEPNoWrapFlags all ()
static GEPNoWrapFlags inBounds ()
static GEPNoWrapFlags noUnsignedSignedWrap ()
static GEPNoWrapFlags noUnsignedWrap ()
static GEPNoWrapFlags fromRaw (unsigned Flags)
Detailed Description
Represents flags for the getelementptr instruction/expression.
The following flags are supported:
inbounds (implies nusw)
nusw (no unsigned signed wrap)
nuw (no unsigned wrap) See LangRef for a description of their semantics.
Definition at line 26 of file GEPNoWrapFlags.h.
Constructor & Destructor Documentation
GEPNoWrapFlags() [1/2]
llvm::GEPNoWrapFlags::GEPNoWrapFlags () inline
Definition at line 40 of file GEPNoWrapFlags.h.
Referenced by all(), fromRaw(), inBounds(), none(), noUnsignedSignedWrap(), noUnsignedWrap(), operator&(), operator|(), withoutInBounds(), withoutNoUnsignedSignedWrap(), and withoutNoUnsignedWrap().
GEPNoWrapFlags() [2/2]
llvm::GEPNoWrapFlags::GEPNoWrapFlags (bool IsInBounds) inline
Definition at line 43 of file GEPNoWrapFlags.h.
Member Function Documentation
all()
GEPNoWrapFlags llvm::GEPNoWrapFlags::all () inline static
Definition at line 47 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
fromRaw()
GEPNoWrapFlags llvm::GEPNoWrapFlags::fromRaw (unsigned Flags) inline static
Definition at line 58 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by llvm::GEPOperator::getNoWrapFlags().
getRaw()
unsigned llvm::GEPNoWrapFlags::getRaw () const inline
Definition at line 61 of file GEPNoWrapFlags.h.
Referenced by llvm::ConstantExpr::getGetElementPtr(), and llvm::GetElementPtrInst::setNoWrapFlags().
hasNoUnsignedSignedWrap()
bool llvm::GEPNoWrapFlags::hasNoUnsignedSignedWrap () const inline
Definition at line 64 of file GEPNoWrapFlags.h.
Referenced by llvm::InstCombinerImpl::foldGEPICmp(), llvm::ScalarEvolution::getGEPExpr(), llvm::GEPOperator::hasNoUnsignedSignedWrap(), intersectForOffsetAdd(), mapToLLVMGEPNoWrapFlags(), and rewriteGEPAsOffset().
hasNoUnsignedWrap()
bool llvm::GEPNoWrapFlags::hasNoUnsignedWrap () const inline
Definition at line 65 of file GEPNoWrapFlags.h.
Referenced by llvm::InstCombinerImpl::foldGEPICmp(), llvm::ScalarEvolution::getGEPExpr(), llvm::GEPOperator::hasNoUnsignedWrap(), mapToLLVMGEPNoWrapFlags(), and rewriteGEPAsOffset().
inBounds()
GEPNoWrapFlags llvm::GEPNoWrapFlags::inBounds () inline static
Definition at line 50 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by llvm::IRBuilderBase::CreateConstInBoundsGEP1_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_64(), llvm::GetElementPtrInst::CreateInBounds(), llvm::IRBuilderBase::CreateInBoundsGEP(), llvm::IRBuilderBase::CreateInBoundsPtrAdd(), llvm::VPBuilder::createInBoundsPtrAdd(), llvm::VPlanTransforms::createInterleaveGroups(), llvm::IRBuilderBase::CreateStructGEP(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::ConstantExpr::getInBoundsGetElementPtr(), mapFromLLVMGEPNoWrapFlags(), llvm::GetElementPtrInst::setIsInBounds(), and toGEPNoWrapFlags().
intersectForOffsetAdd()
GEPNoWrapFlags llvm::GEPNoWrapFlags::intersectForOffsetAdd (GEPNoWrapFlags Other) const inline
Given (gep (gep p, x), y), determine the nowrap flags for (gep p, x+y).
Definition at line 78 of file GEPNoWrapFlags.h.
References hasNoUnsignedSignedWrap(), isInBounds(), llvm::Other, and withoutNoUnsignedSignedWrap().
Referenced by canRewriteGEPAsOffset(), and getMergedGEPNoWrapFlags().
isInBounds()
bool llvm::GEPNoWrapFlags::isInBounds () const inline
Definition at line 63 of file GEPNoWrapFlags.h.
Referenced by intersectForOffsetAdd(), llvm::GEPOperator::isInBounds(), and mapToLLVMGEPNoWrapFlags().
none()
GEPNoWrapFlags llvm::GEPNoWrapFlags::none () inline static
Definition at line 46 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by llvm::IRBuilderBase::CreateConstGEP1_32(), llvm::IRBuilderBase::CreateConstGEP1_64(), llvm::IRBuilderBase::CreateConstGEP2_32(), llvm::IRBuilderBase::CreateConstGEP2_64(), llvm::IRBuilderBase::CreateGEP(), llvm::VPlanTransforms::createInterleaveGroups(), llvm::IRBuilderBase::CreatePtrAdd(), llvm::VPBuilder::createPtrAdd(), decomposeGEP(), llvm::VPIRFlags::dropPoisonGeneratingFlags(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::ScalarEvolution::getGEPExpr(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getGetElementPtr(), llvm::Operator::hasPoisonGeneratingFlags(), llvm::PoisonFlags::PoisonFlags(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
noUnsignedSignedWrap()
GEPNoWrapFlags llvm::GEPNoWrapFlags::noUnsignedSignedWrap () inline static
Definition at line 53 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by mapFromLLVMGEPNoWrapFlags(), and toGEPNoWrapFlags().
noUnsignedWrap()
GEPNoWrapFlags llvm::GEPNoWrapFlags::noUnsignedWrap () inline static
Definition at line 56 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by llvm::IRBuilderBase::CreateStructGEP(), mapFromLLVMGEPNoWrapFlags(), llvm::refineInstruction(), toGEPNoWrapFlags(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
operator!=()
bool llvm::GEPNoWrapFlags::operator!= (GEPNoWrapFlags Other) const inline
Definition at line 88 of file GEPNoWrapFlags.h.
References llvm::Other.
operator&()
GEPNoWrapFlags llvm::GEPNoWrapFlags::operator& (GEPNoWrapFlags Other) const inline
Definition at line 90 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags(), and llvm::Other.
operator&=()
GEPNoWrapFlags & llvm::GEPNoWrapFlags::operator&= (GEPNoWrapFlags Other) inline
Definition at line 96 of file GEPNoWrapFlags.h.
References llvm::Other.
operator==()
bool llvm::GEPNoWrapFlags::operator== (GEPNoWrapFlags Other) const inline
Definition at line 87 of file GEPNoWrapFlags.h.
References llvm::Other.
operator|()
GEPNoWrapFlags llvm::GEPNoWrapFlags::operator| (GEPNoWrapFlags Other) const inline
Definition at line 93 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags(), and llvm::Other.
operator|=()
GEPNoWrapFlags & llvm::GEPNoWrapFlags::operator|= (GEPNoWrapFlags Other) inline
Definition at line 100 of file GEPNoWrapFlags.h.
References llvm::Other.
withoutInBounds()
GEPNoWrapFlags llvm::GEPNoWrapFlags::withoutInBounds () const inline
Definition at line 67 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by llvm::GetElementPtrInst::setIsInBounds().
withoutNoUnsignedSignedWrap()
GEPNoWrapFlags llvm::GEPNoWrapFlags::withoutNoUnsignedSignedWrap () const inline
Definition at line 70 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by intersectForOffsetAdd(), and llvm::InstCombinerImpl::visitGEPOfGEP().
withoutNoUnsignedWrap()
GEPNoWrapFlags llvm::GEPNoWrapFlags::withoutNoUnsignedWrap () const inline
Definition at line 73 of file GEPNoWrapFlags.h.
References GEPNoWrapFlags().
Referenced by llvm::InstCombinerImpl::visitGEPOfGEP().
The documentation for this class was generated from the following file:
include/llvm/IR/GEPNoWrapFlags.h