LLVM: llvm::MachineModuleInfoImpl Class Reference
llvm::MachineModuleInfoImpl Class Reference
This class can be derived from and used by targets to hold private target-specific information for each Module.
#include "llvm/CodeGen/MachineModuleInfo.h"
Public Types
using StubValueTy = PointerIntPair<MCSymbol *, 1, bool>
using SymbolListTy = std::vector<std::pair<MCSymbol *, StubValueTy>>
using ExprStubListTy = std::vector<std::pair<MCSymbol *, const MCExpr *>>
A variant of SymbolListTy where the stub is a generalized MCExpr.
Public Member Functions
virtual ~MachineModuleInfoImpl ()
Static Protected Member Functions
static SymbolListTy getSortedStubs (DenseMap< MCSymbol *, StubValueTy > &)
Return the entries from a DenseMap in a deterministic sorted orer.
static ExprStubListTy getSortedExprStubs (DenseMap< MCSymbol *, const MCExpr * > &)
Return the entries from a DenseMap in a deterministic sorted orer.
Detailed Description
This class can be derived from and used by targets to hold private target-specific information for each Module.
Objects of type are accessed/created with MachineModuleInfo::getObjFileInfo and destroyed when the MachineModuleInfo is destroyed.
Definition at line 57 of file MachineModuleInfo.h.
Member Typedef Documentation
ExprStubListTy
using llvm::MachineModuleInfoImpl::ExprStubListTy = std::vector<std::pair<MCSymbol *, const MCExpr *>>
A variant of SymbolListTy where the stub is a generalized MCExpr.
Definition at line 63 of file MachineModuleInfo.h.
StubValueTy
using llvm::MachineModuleInfoImpl::StubValueTy = PointerIntPair<MCSymbol *, 1, bool>
Definition at line 59 of file MachineModuleInfo.h.
SymbolListTy
using llvm::MachineModuleInfoImpl::SymbolListTy = std::vector<std::pair<MCSymbol *, StubValueTy>>
Definition at line 60 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
~MachineModuleInfoImpl()
MachineModuleInfoImpl::~MachineModuleInfoImpl () virtual default
References getSortedExprStubs(), and getSortedStubs().
Member Function Documentation
getSortedExprStubs()
MachineModuleInfoImpl::ExprStubListTy MachineModuleInfoImpl::getSortedExprStubs (DenseMap< MCSymbol *, const MCExpr * > & ExprStubs) static protected
Return the entries from a DenseMap in a deterministic sorted orer.
Clears the map.
Definition at line 54 of file MachineModuleInfoImpls.cpp.
References llvm::array_pod_sort(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::List, and SortAuthStubPair().
Referenced by llvm::MachineModuleInfoELF::getAuthGVStubList(), llvm::MachineModuleInfoMachO::getAuthGVStubList(), and ~MachineModuleInfoImpl().
getSortedStubs()
MachineModuleInfoImpl::SymbolListTy MachineModuleInfoImpl::getSortedStubs (DenseMap< MCSymbol *, StubValueTy > & Map) static protected
Return the entries from a DenseMap in a deterministic sorted orer.
Clears the map.
Definition at line 38 of file MachineModuleInfoImpls.cpp.
References llvm::array_pod_sort(), llvm::List, and SortSymbolPair().
Referenced by llvm::MachineModuleInfoCOFF::GetGVStubList(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MachineModuleInfoMachO::GetThreadLocalGVStubList(), and ~MachineModuleInfoImpl().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfo.h
lib/CodeGen/MachineModuleInfo.cpp
lib/CodeGen/MachineModuleInfoImpls.cpp