LLVM: llvm::X86MCExpr Class Reference
llvm::X86MCExpr Class Reference
#include "Target/X86/MCTargetDesc/X86MCExpr.h"
Public Member Functions
MCRegister getReg () const
getSubExpr - Get the child of this expression.
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm) const override
bool inlineAssignedExpr () const override
bool isEqualTo (const MCExpr *X) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
LLVM_ABI void dump () const
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res) const
Try to evaluate the expression to an absolute value.
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
LLVM_ABI bool evaluateKnownAbsolute (int64_t &Res, const MCAssembler &Asm) const
Aggressive variant of evaluateAsRelocatable when relocations are unavailable (e.g.
LLVM_ABI bool evaluateAsRelocatable (MCValue &Res, const MCAssembler *Asm) const
Try to evaluate the expression to a relocatable value, i.e.
LLVM_ABI bool evaluateAsValue (MCValue &Res, const MCAssembler &Asm) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
LLVM_ABI MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static const X86MCExpr * create (MCRegister Reg, MCContext &Ctx)
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCExpr
static LLVM_ABI bool evaluateSymbolicAdd (const MCAssembler *, bool, const MCValue &, const MCValue &, MCValue &)
Additional Inherited Members
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary , Constant , SymbolRef , Unary ,
Specifier , Target
}
Protected Types inherited from llvm::MCExpr
using Spec = uint16_t
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
LLVM_ABI bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Definition at line 26 of file X86MCExpr.h.
Member Function Documentation
classof()
bool llvm::X86MCExpr::classof (const MCExpr * E) inline static
Definition at line 61 of file X86MCExpr.h.
References E(), and llvm::MCExpr::Target.
create()
const X86MCExpr * llvm::X86MCExpr::create (MCRegister Reg, MCContext & Ctx) inline static
Definition at line 34 of file X86MCExpr.h.
evaluateAsRelocatableImpl()
bool llvm::X86MCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAssembler * Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 47 of file X86MCExpr.h.
findAssociatedFragment()
MCFragment * llvm::X86MCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 59 of file X86MCExpr.h.
getReg()
MCRegister llvm::X86MCExpr::getReg () const inline
getSubExpr - Get the child of this expression.
Definition at line 39 of file X86MCExpr.h.
Referenced by isEqualTo().
inlineAssignedExpr()
bool llvm::X86MCExpr::inlineAssignedExpr () const inline override virtual
Reimplemented from llvm::MCTargetExpr.
Definition at line 52 of file X86MCExpr.h.
isEqualTo()
bool llvm::X86MCExpr::isEqualTo (const MCExpr * X) const inline override virtual
Reimplemented from llvm::MCTargetExpr.
Definition at line 53 of file X86MCExpr.h.
References llvm::dyn_cast(), E(), getReg(), and X.
printImpl()
void llvm::X86MCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 41 of file X86MCExpr.h.
References llvm::MCAsmInfo::getAssemblerDialect(), and llvm::X86ATTInstPrinter::getRegisterName().
visitUsedExpr()
void llvm::X86MCExpr::visitUsedExpr (MCStreamer & Streamer) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 58 of file X86MCExpr.h.
The documentation for this class was generated from the following file:
lib/Target/X86/MCTargetDesc/X86MCExpr.h