LLVM: llvm::object::MinidumpFile::MemoryInfoIterator Class Reference
llvm::object::MinidumpFile::MemoryInfoIterator Class Reference
#include "llvm/Object/Minidump.h"
Public Member Functions
MemoryInfoIterator (ArrayRef< uint8_t > Storage, size_t Stride)
bool operator== (const MemoryInfoIterator &R) const
const minidump::MemoryInfo & operator* () const
MemoryInfoIterator & operator++ ()
Public Member Functions inherited from llvm::iterator_facade_base< MemoryInfoIterator, std::forward_iterator_tag, minidump::MemoryInfo >
MemoryInfoIterator operator+ (std::ptrdiff_t n) const
MemoryInfoIterator operator- (std::ptrdiff_t n) const
MemoryInfoIterator & operator++ ()
MemoryInfoIterator & operator-- ()
bool operator!= (const MemoryInfoIterator &RHS) const
bool operator> (const MemoryInfoIterator &RHS) const
bool operator<= (const MemoryInfoIterator &RHS) const
bool operator>= (const MemoryInfoIterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< MemoryInfoIterator, std::forward_iterator_tag, minidump::MemoryInfo >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Protected Types inherited from llvm::iterator_facade_base< MemoryInfoIterator, std::forward_iterator_tag, minidump::MemoryInfo >
enum
Detailed Description
Definition at line 129 of file Minidump.h.
Constructor & Destructor Documentation
MemoryInfoIterator()
llvm::object::MinidumpFile::MemoryInfoIterator::MemoryInfoIterator (ArrayRef< uint8_t > Storage, size_t Stride) inline
Definition at line 134 of file Minidump.h.
References assert().
Referenced by operator++(), and operator==().
Member Function Documentation
operator*()
const minidump::MemoryInfo & llvm::object::MinidumpFile::MemoryInfoIterator::operator* () const inline
Definition at line 143 of file Minidump.h.
References assert().
operator++()
MemoryInfoIterator & llvm::object::MinidumpFile::MemoryInfoIterator::operator++ () inline
Definition at line 148 of file Minidump.h.
References MemoryInfoIterator().
operator==()
bool llvm::object::MinidumpFile::MemoryInfoIterator::operator== (const MemoryInfoIterator & R) const inline
Definition at line 139 of file Minidump.h.
References MemoryInfoIterator().
The documentation for this class was generated from the following file:
include/llvm/Object/Minidump.h