LLVM: llvm::PreRARematStage Class Reference
llvm::PreRARematStage Class Reference
Attempts to reduce function spilling or, if there is no spilling, to increase function occupancy by one with respect to ArchVGPR usage by sinking trivially rematerializable instructions to their use.
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
bool initGCNSchedStage () override
bool initGCNRegion () override
bool shouldRevertScheduling (unsigned WavesAfter) override
PreRARematStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Public Member Functions inherited from llvm::GCNSchedStage
void setupNewBlock ()
void finalizeGCNRegion ()
void checkScheduling ()
ScheduleMetrics getScheduleMetrics (const std::vector< SUnit > &InputSchedule)
ScheduleMetrics getScheduleMetrics (const GCNScheduleDAGMILive &DAG)
unsigned computeSUnitReadyCycle (const SUnit &SU, unsigned CurrCycle, DenseMap< unsigned, unsigned > &ReadyCycles, const TargetSchedModel &SM)
bool isRegionWithExcessRP () const
unsigned getRegionIdx ()
bool mayCauseSpilling (unsigned WavesAfter)
void revertScheduling ()
void advanceRegion ()
virtual ~GCNSchedStage ()=default
Additional Inherited Members
Protected Member Functions inherited from llvm::GCNSchedStage
GCNSchedStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Protected Attributes inherited from llvm::GCNSchedStage
GCNScheduleDAGMILive & DAG
GCNSchedStrategy & S
MachineFunction & MF
SIMachineFunctionInfo & MFI
const GCNSubtarget & ST
const GCNSchedStageID StageID
MachineBasicBlock * CurrentMBB = nullptr
unsigned RegionIdx = 0
std::vector< MachineInstr * > Unsched
GCNRegPressure PressureBefore
GCNRegPressure PressureAfter
std::vector< std::unique_ptr< ScheduleDAGMutation > > SavedMutations
Detailed Description
Attempts to reduce function spilling or, if there is no spilling, to increase function occupancy by one with respect to ArchVGPR usage by sinking trivially rematerializable instructions to their use.
When the stage estimates reducing spilling or increasing occupancy is possible, as few instructions as possible are rematerialized to reduce potential negative effects on function latency.
Definition at line 443 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
PreRARematStage()
llvm::PreRARematStage::PreRARematStage (GCNSchedStageID StageID, GCNScheduleDAGMILive & DAG) inline
Definition at line 519 of file GCNSchedStrategy.h.
References llvm::GCNSchedStage::DAG, llvm::GCNSchedStage::GCNSchedStage(), llvm::size(), and llvm::GCNSchedStage::StageID.
Member Function Documentation
initGCNRegion()
bool PreRARematStage::initGCNRegion () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 1238 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::initGCNRegion(), and llvm::GCNSchedStage::RegionIdx.
initGCNSchedStage()
bool PreRARematStage::initGCNSchedStage () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 1091 of file GCNSchedStrategy.cpp.
References assert(), llvm::GCNSchedStage::DAG, llvm::dbgs(), GCNTrackers, llvm::RegionBase< Tr >::getParent(), I, llvm::GCNSchedStage::initGCNSchedStage(), llvm::GCNSchedStage::MF, llvm::GCNSchedStage::MFI, MI, REMAT_DEBUG, and llvm::GCNSchedStage::S.
shouldRevertScheduling()
bool PreRARematStage::shouldRevertScheduling (unsigned WavesAfter) override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 1551 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::mayCauseSpilling(), and llvm::GCNSchedStage::shouldRevertScheduling().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp