LLVM: llvm::X86TargetStreamer Class Reference
llvm::X86TargetStreamer Class Reference
X86 target streamer implementing x86-only assembly directives.
#include "Target/X86/MCTargetDesc/X86TargetStreamer.h"
Public Member Functions
X86TargetStreamer (MCStreamer &S)
virtual void emitCode16 ()
virtual void emitCode32 ()
virtual void emitCode64 ()
virtual bool emitFPOProc (const MCSymbol *ProcSym, unsigned ParamsSize, SMLoc L={})
virtual bool emitFPOEndPrologue (SMLoc L={})
virtual bool emitFPOEndProc (SMLoc L={})
virtual bool emitFPOData (const MCSymbol *ProcSym, SMLoc L={})
virtual bool emitFPOPushReg (MCRegister Reg, SMLoc L={})
virtual bool emitFPOStackAlloc (unsigned StackAlloc, SMLoc L={})
virtual bool emitFPOStackAlign (unsigned Align, SMLoc L={})
virtual bool emitFPOSetFrame (MCRegister Reg, SMLoc L={})
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
X86 target streamer implementing x86-only assembly directives.
Definition at line 17 of file X86TargetStreamer.h.
Constructor & Destructor Documentation
X86TargetStreamer()
llvm::X86TargetStreamer::X86TargetStreamer (MCStreamer & S) inline
Definition at line 19 of file X86TargetStreamer.h.
References llvm::MCTargetStreamer::MCTargetStreamer().
Member Function Documentation
emitCode16()
virtual void llvm::X86TargetStreamer::emitCode16 () inline virtual
Definition at line 21 of file X86TargetStreamer.h.
Referenced by llvm::X86AsmPrinter::emitStartOfAsmFile().
emitCode32()
virtual void llvm::X86TargetStreamer::emitCode32 () inline virtual
Definition at line 22 of file X86TargetStreamer.h.
emitCode64()
virtual void llvm::X86TargetStreamer::emitCode64 () inline virtual
Definition at line 23 of file X86TargetStreamer.h.
emitFPOData()
virtual bool llvm::X86TargetStreamer::emitFPOData (const MCSymbol * ProcSym, SMLoc L = {}) inline virtual
Definition at line 31 of file X86TargetStreamer.h.
emitFPOEndProc()
virtual bool llvm::X86TargetStreamer::emitFPOEndProc (SMLoc L = {}) inline virtual
Definition at line 30 of file X86TargetStreamer.h.
Referenced by llvm::X86AsmPrinter::emitFunctionBodyEnd().
emitFPOEndPrologue()
virtual bool llvm::X86TargetStreamer::emitFPOEndPrologue (SMLoc L = {}) inline virtual
Definition at line 29 of file X86TargetStreamer.h.
emitFPOProc()
virtual bool llvm::X86TargetStreamer::emitFPOProc (const MCSymbol * ProcSym, unsigned ParamsSize, SMLoc L = {}) inline virtual
Definition at line 25 of file X86TargetStreamer.h.
Referenced by llvm::X86AsmPrinter::emitFunctionBodyStart().
emitFPOPushReg()
virtual bool llvm::X86TargetStreamer::emitFPOPushReg (MCRegister Reg, SMLoc L = {}) inline virtual
Definition at line 34 of file X86TargetStreamer.h.
References Reg.
emitFPOSetFrame()
virtual bool llvm::X86TargetStreamer::emitFPOSetFrame (MCRegister Reg, SMLoc L = {}) inline virtual
Definition at line 39 of file X86TargetStreamer.h.
References Reg.
emitFPOStackAlign()
virtual bool llvm::X86TargetStreamer::emitFPOStackAlign (unsigned Align, SMLoc L = {}) inline virtual
Definition at line 38 of file X86TargetStreamer.h.
emitFPOStackAlloc()
virtual bool llvm::X86TargetStreamer::emitFPOStackAlloc (unsigned StackAlloc, SMLoc L = {}) inline virtual
Definition at line 35 of file X86TargetStreamer.h.
The documentation for this class was generated from the following file:
lib/Target/X86/MCTargetDesc/X86TargetStreamer.h