LLVM: llvm::MCSectionGOFF Class Reference
llvm::MCSectionGOFF Class Reference final
#include "llvm/MC/MCSectionGOFF.h"
Public Member Functions
void printSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, uint32_t Subsection) const override
bool useCodeAlign () const override
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
MCSectionGOFF * getParent () const
bool isBSS () const
GOFF::ESDSymbolType getSymbolType () const
bool isSD () const
bool isED () const
bool isPR () const
GOFF::SDAttr getSDAttributes () const
GOFF::EDAttr getEDAttributes () const
GOFF::PRAttr getPRAttributes () const
GOFF::ESDTextStyle getTextStyle () const
bool requiresNonZeroLength () const
void setName (StringRef SectionName)
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
StringRef getName () const
bool isText () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
Align getAlign () const
void setAlignment (Align Value)
void ensureMinAlignment (Align MinAlignment)
Makes sure that Alignment is at least MinAlignment.
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
bool isLinkerRelaxable () const
void setLinkerRelaxable ()
MCFragment & getDummyFragment ()
FragList * curFragList () const
iterator begin () const
iterator end () const
void dump (DenseMap< const MCFragment *, SmallVector< const MCSymbol *, 0 > > *FragToSyms=nullptr) const
bool isVirtualSection () const
Check whether this section is "virtual", that is has no actual object file contents.
virtual StringRef getVirtualSectionKind () const
Static Public Member Functions
static bool classof (const MCSection *S)
Friends
class MCContext
class MCSymbolGOFF
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant {
SV_COFF = 0 , SV_ELF , SV_GOFF , SV_MachO ,
SV_Wasm , SV_XCOFF , SV_SPIRV , SV_DXContainer
}
enum BundleLockStateType { NotBundleLocked , BundleLocked , BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
Public Attributes inherited from llvm::MCSection
friend MCAssembler
friend MCObjectStreamer
Static Public Attributes inherited from llvm::MCSection
static constexpr unsigned NonUniqueID = ~0U
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, StringRef Name, bool IsText, bool IsVirtual, MCSymbol *Begin)
~MCSection ()
Protected Attributes inherited from llvm::MCSection
StringRef Name
SectionVariant Variant
Detailed Description
Definition at line 29 of file MCSectionGOFF.h.
Member Function Documentation
classof()
bool llvm::MCSectionGOFF::classof (const MCSection * S) inline static
Definition at line 127 of file MCSectionGOFF.h.
References llvm::MCSection::getVariant(), llvm::MCSection::MCSection(), and llvm::MCSection::SV_GOFF.
getEDAttributes()
GOFF::EDAttr llvm::MCSectionGOFF::getEDAttributes () const inline
Definition at line 103 of file MCSectionGOFF.h.
References assert(), EDAttributes, and isED().
Referenced by printSwitchToSection().
getParent()
MCSectionGOFF * llvm::MCSectionGOFF::getParent () const inline
Definition at line 86 of file MCSectionGOFF.h.
Referenced by llvm::TargetLoweringObjectFileGOFF::getSectionForLSDA(), and printSwitchToSection().
getPRAttributes()
GOFF::PRAttr llvm::MCSectionGOFF::getPRAttributes () const inline
Definition at line 107 of file MCSectionGOFF.h.
References assert(), isPR(), and PRAttributes.
getSDAttributes()
GOFF::SDAttr llvm::MCSectionGOFF::getSDAttributes () const inline
Definition at line 99 of file MCSectionGOFF.h.
References assert(), isSD(), and SDAttributes.
getSymbolType()
GOFF::ESDSymbolType llvm::MCSectionGOFF::getSymbolType () const inline
Definition at line 92 of file MCSectionGOFF.h.
getTextStyle()
GOFF::ESDTextStyle llvm::MCSectionGOFF::getTextStyle () const inline
Definition at line 113 of file MCSectionGOFF.h.
References assert(), EDAttributes, llvm::GOFF::ESD_TS_ByteOriented, getParent(), isED(), isPR(), and llvm::MCSection::isVirtualSection().
isBSS()
bool llvm::MCSectionGOFF::isBSS () const inline
Definition at line 89 of file MCSectionGOFF.h.
Referenced by MCSymbolGOFF.
isED()
bool llvm::MCSectionGOFF::isED () const inline
Definition at line 95 of file MCSectionGOFF.h.
References llvm::GOFF::ESD_ST_ElementDefinition.
Referenced by getEDAttributes(), and getTextStyle().
isPR()
bool llvm::MCSectionGOFF::isPR () const inline
Definition at line 96 of file MCSectionGOFF.h.
References llvm::GOFF::ESD_ST_PartReference.
Referenced by getPRAttributes(), and getTextStyle().
isSD()
bool llvm::MCSectionGOFF::isSD () const inline
Definition at line 94 of file MCSectionGOFF.h.
References llvm::GOFF::ESD_ST_SectionDefinition.
Referenced by getSDAttributes().
printSwitchToSection()
void MCSectionGOFF::printSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, uint32_t Subsection) const override virtual
Implements llvm::MCSection.
Definition at line 103 of file MCSectionGOFF.cpp.
References llvm::GOFF::EDAttr::Alignment, EDAttributes, emitCATTR(), emitXATTR(), llvm::GOFF::ESD_EXE_Unspecified, llvm::GOFF::ESD_ST_ElementDefinition, llvm::GOFF::ESD_ST_PartReference, llvm::GOFF::ESD_ST_SectionDefinition, llvm::GOFF::EDAttr::FillByteValue, getEDAttributes(), llvm::MCSection::getName(), getParent(), llvm::GOFF::EDAttr::IsReadOnly, llvm_unreachable, llvm::GOFF::EDAttr::LoadBehavior, llvm::MCSection::Name, PRAttributes, printSwitchToSection(), llvm::GOFF::EDAttr::Rmode, and T.
Referenced by printSwitchToSection().
requiresNonZeroLength()
bool llvm::MCSectionGOFF::requiresNonZeroLength () const inline
Definition at line 123 of file MCSectionGOFF.h.
setName()
void llvm::MCSectionGOFF::setName (StringRef SectionName) inline
Definition at line 125 of file MCSectionGOFF.h.
References llvm::MCSection::Name.
Referenced by llvm::TargetLoweringObjectFileGOFF::getModuleMetadata().
useCodeAlign()
bool llvm::MCSectionGOFF::useCodeAlign () const inline override virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implements llvm::MCSection.
Definition at line 83 of file MCSectionGOFF.h.
Friends And Related Symbol Documentation
MCContext
friend class MCContext friend
Definition at line 54 of file MCSectionGOFF.h.
References MCContext.
Referenced by MCContext.
MCSymbolGOFF
friend class MCSymbolGOFF friend
Definition at line 55 of file MCSectionGOFF.h.
References isBSS(), llvm::MCSection::isText(), llvm::MCSection::MCSection(), MCSymbolGOFF, llvm::MCSection::Name, SDAttributes, and llvm::MCSection::SV_GOFF.
Referenced by MCSymbolGOFF.
Member Data Documentation
EDAttributes
GOFF::EDAttr llvm::MCSectionGOFF::EDAttributes
Definition at line 36 of file MCSectionGOFF.h.
Referenced by getEDAttributes(), getTextStyle(), and printSwitchToSection().
PRAttributes
GOFF::PRAttr llvm::MCSectionGOFF::PRAttributes
Definition at line 37 of file MCSectionGOFF.h.
Referenced by getPRAttributes(), and printSwitchToSection().
SDAttributes
GOFF::SDAttr llvm::MCSectionGOFF::SDAttributes
Definition at line 35 of file MCSectionGOFF.h.
Referenced by getSDAttributes(), and MCSymbolGOFF.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSectionGOFF.h
lib/MC/MCSectionGOFF.cpp