LLVM: llvm::SparcTargetStreamer Class Reference
llvm::SparcTargetStreamer Class Reference
#include "Target/Sparc/MCTargetDesc/SparcTargetStreamer.h"
Public Member Functions
SparcTargetStreamer (MCStreamer &S)
virtual void emitSparcRegisterIgnore (unsigned reg)
Emit ".register <reg>, #ignore".
virtual void emitSparcRegisterScratch (unsigned reg)
Emit ".register <reg>, #scratch".
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 19 of file SparcTargetStreamer.h.
Constructor & Destructor Documentation
SparcTargetStreamer()
SparcTargetStreamer::SparcTargetStreamer (MCStreamer & S)
Definition at line 42 of file SparcTargetStreamer.cpp.
References llvm::MCTargetStreamer::MCTargetStreamer().
Referenced by llvm::SparcTargetAsmStreamer::SparcTargetAsmStreamer(), and llvm::SparcTargetELFStreamer::SparcTargetELFStreamer().
Member Function Documentation
emitSparcRegisterIgnore()
virtual void llvm::SparcTargetStreamer::emitSparcRegisterIgnore (unsigned reg) inline virtual
Emit ".register <reg>, #ignore".
Reimplemented in llvm::SparcTargetAsmStreamer, and llvm::SparcTargetELFStreamer.
Definition at line 25 of file SparcTargetStreamer.h.
emitSparcRegisterScratch()
virtual void llvm::SparcTargetStreamer::emitSparcRegisterScratch (unsigned reg) inline virtual
Emit ".register <reg>, #scratch".
Reimplemented in llvm::SparcTargetAsmStreamer, and llvm::SparcTargetELFStreamer.
Definition at line 27 of file SparcTargetStreamer.h.
The documentation for this class was generated from the following files:
lib/Target/Sparc/MCTargetDesc/SparcTargetStreamer.h
lib/Target/Sparc/MCTargetDesc/SparcTargetStreamer.cpp