LLVM: llvm::AMDGPU::VOPD::ComponentLayout Class Reference
llvm::AMDGPU::VOPD::ComponentLayout Class Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Member Functions
ComponentLayout (ComponentKind Kind, unsigned VOPD3ModsNum, int BitOp3Idx)
ComponentLayout (const ComponentProps &OpXProps, unsigned VOPD3ModsNum, int BitOp3Idx)
unsigned getIndexOfDstInMCOperands () const
unsigned getIndexOfSrcInMCOperands (unsigned CompSrcIdx, bool VOPD3) const
unsigned getIndexOfDstInParsedOperands () const
unsigned getIndexOfSrcInParsedOperands (unsigned CompSrcIdx) const
Detailed Description
Definition at line 775 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
ComponentLayout() [1/2]
llvm::AMDGPU::VOPD::ComponentLayout::ComponentLayout (ComponentKind Kind, unsigned VOPD3ModsNum, int BitOp3Idx) inline
Definition at line 812 of file AMDGPUBaseInfo.h.
References assert(), llvm::AMDGPU::VOPD::COMPONENT_X, and llvm::AMDGPU::VOPD::SINGLE.
Referenced by llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo(), and llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo().
ComponentLayout() [2/2]
llvm::AMDGPU::VOPD::ComponentLayout::ComponentLayout (const ComponentProps & OpXProps, unsigned VOPD3ModsNum, int BitOp3Idx) inline
Definition at line 818 of file AMDGPUBaseInfo.h.
References llvm::AMDGPU::VOPD::COMPONENT_Y.
Member Function Documentation
getIndexOfDstInMCOperands()
unsigned llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfDstInMCOperands () const inline
Definition at line 825 of file AMDGPUBaseInfo.h.
getIndexOfDstInParsedOperands()
unsigned llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfDstInParsedOperands () const inline
Definition at line 844 of file AMDGPUBaseInfo.h.
Referenced by llvm::AMDGPU::VOPD::ComponentInfo::getIndexInParsedOperands().
getIndexOfSrcInMCOperands()
unsigned llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfSrcInMCOperands (unsigned CompSrcIdx, bool VOPD3) const inline
Definition at line 828 of file AMDGPUBaseInfo.h.
References assert(), llvm::AMDGPU::VOPD::MAX_SRC_NUM, and llvm::AMDGPU::VOPD::SINGLE.
getIndexOfSrcInParsedOperands()
unsigned llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfSrcInParsedOperands (unsigned CompSrcIdx) const inline
Definition at line 849 of file AMDGPUBaseInfo.h.
References assert(), and llvm::AMDGPU::VOPD::MAX_SRC_NUM.
Referenced by llvm::AMDGPU::VOPD::ComponentInfo::getIndexInParsedOperands().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h