LLVM: llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn > Class Template Reference
llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn > Class Template Reference final
Similar to GenericSetter but the setters/getters have an index as their first argument.
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
GenericSetterWithIdx (InstrT *I, unsigned Idx)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
template<auto GetterFn, auto SetterFn>
class llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn >
Similar to GenericSetter but the setters/getters have an index as their first argument.
This is commont in cases like: getOperand(unsigned Idx)
Definition at line 305 of file Tracker.h.
Constructor & Destructor Documentation
GenericSetterWithIdx()
template<auto GetterFn, auto SetterFn> llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn >::GenericSetterWithIdx (InstrT * I, unsigned Idx) inline
Definition at line 319 of file Tracker.h.
Member Function Documentation
accept()
template<auto GetterFn, auto SetterFn> void llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn >::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 322 of file Tracker.h.
dump() [1/2]
template<auto GetterFn, auto SetterFn> LLVM_DUMP_METHOD void llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn >::dump () const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 325 of file Tracker.h.
References const, llvm::dbgs(), dump(), and LLVM_DUMP_METHOD.
Referenced by dump().
dump() [2/2]
template<auto GetterFn, auto SetterFn> void llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn >::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 324 of file Tracker.h.
revert()
template<auto GetterFn, auto SetterFn> void llvm::sandboxir::GenericSetterWithIdx< GetterFn, SetterFn >::revert (Tracker & Tracker) inline final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 321 of file Tracker.h.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Tracker.h