LLVM: llvm::codeview::LabelSym Class Reference
llvm::codeview::LabelSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
LabelSym (SymbolRecordKind Kind)
LabelSym (uint32_t RecordOffset)
uint32_t getRelocationOffset () const
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
uint32_t CodeOffset = 0
uint16_t Segment = 0
ProcSymFlags Flags = ProcSymFlags::None
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 656 of file SymbolRecord.h.
Constructor & Destructor Documentation
LabelSym() [1/2]
llvm::codeview::LabelSym::LabelSym (SymbolRecordKind Kind) inline explicit
Definition at line 660 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by LabelSym().
LabelSym() [2/2]
llvm::codeview::LabelSym::LabelSym (uint32_t RecordOffset) inline explicit
Definition at line 661 of file SymbolRecord.h.
References LabelSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Function Documentation
getRelocationOffset()
uint32_t llvm::codeview::LabelSym::getRelocationOffset () const inline
Definition at line 664 of file SymbolRecord.h.
References RecordOffset.
Member Data Documentation
CodeOffset
uint32_t llvm::codeview::LabelSym::CodeOffset = 0
Definition at line 668 of file SymbolRecord.h.
Flags
ProcSymFlags llvm::codeview::LabelSym::Flags = ProcSymFlags::None
Definition at line 670 of file SymbolRecord.h.
Name
StringRef llvm::codeview::LabelSym::Name
Definition at line 671 of file SymbolRecord.h.
RecordOffset
uint32_t llvm::codeview::LabelSym::RecordOffset = 0
Definition at line 673 of file SymbolRecord.h.
Referenced by getRelocationOffset(), and LabelSym().
Segment
uint16_t llvm::codeview::LabelSym::Segment = 0
Definition at line 669 of file SymbolRecord.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h