LLVM: llvm::SampleProfileSummaryBuilder Class Reference
llvm::SampleProfileSummaryBuilder Class Reference final
#include "llvm/ProfileData/ProfileCommon.h"
Public Member Functions
SampleProfileSummaryBuilder (std::vector< uint32_t > Cutoffs)
LLVM_ABI void addRecord (const sampleprof::FunctionSamples &FS, bool isCallsiteSample=false)
LLVM_ABI std::unique_ptr< ProfileSummary > computeSummaryForProfiles (const sampleprof::SampleProfileMap &Profiles)
LLVM_ABI std::unique_ptr< ProfileSummary > getSummary ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::ProfileSummaryBuilder
static LLVM_ABI const ProfileSummaryEntry & getEntryForPercentile (const SummaryEntryVector &DS, uint64_t Percentile)
Find the summary entry for a desired percentile of counts.
static LLVM_ABI uint64_t getHotCountThreshold (const SummaryEntryVector &DS)
static LLVM_ABI uint64_t getColdCountThreshold (const SummaryEntryVector &DS)
Static Public Attributes inherited from llvm::ProfileSummaryBuilder
static LLVM_ABI const ArrayRef< uint32_t > DefaultCutoffs
A vector of useful cutoff values for detailed summary.
Protected Member Functions inherited from llvm::ProfileSummaryBuilder
ProfileSummaryBuilder (std::vector< uint32_t > Cutoffs)
~ProfileSummaryBuilder ()=default
void addCount (uint64_t Count)
This is called when a count is seen in the profile.
LLVM_ABI void computeDetailedSummary ()
Protected Attributes inherited from llvm::ProfileSummaryBuilder
SummaryEntryVector DetailedSummary
uint64_t TotalCount = 0
uint64_t MaxCount = 0
uint64_t MaxFunctionCount = 0
uint32_t NumCounts = 0
uint32_t NumFunctions = 0
Detailed Description
Definition at line 94 of file ProfileCommon.h.
Constructor & Destructor Documentation
SampleProfileSummaryBuilder()
llvm::SampleProfileSummaryBuilder::SampleProfileSummaryBuilder (std::vector< uint32_t > Cutoffs) inline
Definition at line 96 of file ProfileCommon.h.
References llvm::move(), and llvm::ProfileSummaryBuilder::ProfileSummaryBuilder().
Member Function Documentation
addRecord()
void SampleProfileSummaryBuilder::addRecord (const sampleprof::FunctionSamples & FS, bool isCallsiteSample = false)
Definition at line 118 of file ProfileSummaryBuilder.cpp.
References llvm::ProfileSummaryBuilder::addCount(), addRecord(), llvm::sampleprof::ContextDuplicatedIntoBase, llvm::Count, I, llvm::ProfileSummaryBuilder::MaxFunctionCount, and llvm::ProfileSummaryBuilder::NumFunctions.
Referenced by addRecord(), and computeSummaryForProfiles().
computeSummaryForProfiles()
std::unique_ptr< ProfileSummary > SampleProfileSummaryBuilder::computeSummaryForProfiles (const sampleprof::SampleProfileMap & Profiles)
Definition at line 202 of file ProfileSummaryBuilder.cpp.
References addRecord(), assert(), llvm::sampleprof::ProfileConverter::flattenProfile(), getSummary(), I, llvm::ProfileSummaryBuilder::NumFunctions, Profile, llvm::sampleprof::FunctionSamples::ProfileIsCS, and llvm::UseContextLessSummary.
getSummary()
std::unique_ptr< ProfileSummary > SampleProfileSummaryBuilder::getSummary ()
Definition at line 194 of file ProfileSummaryBuilder.cpp.
References llvm::ProfileSummaryBuilder::computeDetailedSummary(), llvm::ProfileSummaryBuilder::DetailedSummary, llvm::ProfileSummaryBuilder::MaxCount, llvm::ProfileSummaryBuilder::MaxFunctionCount, llvm::ProfileSummaryBuilder::NumCounts, llvm::ProfileSummaryBuilder::NumFunctions, llvm::ProfileSummary::PSK_Sample, and llvm::ProfileSummaryBuilder::TotalCount.
Referenced by computeSummaryForProfiles().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/ProfileCommon.h
lib/ProfileData/ProfileSummaryBuilder.cpp