LLVM: llvm::codeview::DebugSubsectionRef Class Reference
llvm::codeview::DebugSubsectionRef Class Reference
#include "llvm/DebugInfo/CodeView/DebugSubsection.h"
Public Member Functions
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Protected Attributes
DebugSubsectionKind Kind
Detailed Description
Definition at line 22 of file DebugSubsection.h.
Constructor & Destructor Documentation
DebugSubsectionRef()
llvm::codeview::DebugSubsectionRef::DebugSubsectionRef (DebugSubsectionKind Kind) inline explicit
Definition at line 24 of file DebugSubsection.h.
References Kind.
Referenced by llvm::codeview::DebugChecksumsSubsectionRef::classof(), llvm::codeview::DebugCrossModuleExportsSubsectionRef::classof(), llvm::codeview::DebugCrossModuleImportsSubsectionRef::classof(), llvm::codeview::DebugInlineeLinesSubsectionRef::classof(), llvm::codeview::DebugLinesSubsectionRef::classof(), llvm::codeview::DebugStringTableSubsectionRef::classof(), classof(), llvm::codeview::DebugSymbolRVASubsectionRef::classof(), llvm::codeview::DebugSymbolsSubsectionRef::classof(), llvm::codeview::DebugChecksumsSubsectionRef::DebugChecksumsSubsectionRef(), llvm::codeview::DebugCrossModuleExportsSubsectionRef::DebugCrossModuleExportsSubsectionRef(), llvm::codeview::DebugCrossModuleImportsSubsectionRef::DebugCrossModuleImportsSubsectionRef(), llvm::codeview::DebugFrameDataSubsectionRef::DebugFrameDataSubsectionRef(), llvm::codeview::DebugInlineeLinesSubsectionRef::DebugInlineeLinesSubsectionRef(), llvm::codeview::DebugLinesSubsectionRef::DebugLinesSubsectionRef(), llvm::codeview::DebugStringTableSubsectionRef::DebugStringTableSubsectionRef(), llvm::codeview::DebugSymbolRVASubsectionRef::DebugSymbolRVASubsectionRef(), llvm::codeview::DebugSymbolsSubsectionRef::DebugSymbolsSubsectionRef(), and llvm::codeview::DebugUnknownSubsectionRef::DebugUnknownSubsectionRef().
~DebugSubsectionRef()
DebugSubsectionRef::~DebugSubsectionRef () virtual default
Member Function Documentation
classof()
bool llvm::codeview::DebugSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 27 of file DebugSubsection.h.
References DebugSubsectionRef().
kind()
DebugSubsectionKind llvm::codeview::DebugSubsectionRef::kind () const inline
Definition at line 29 of file DebugSubsection.h.
References Kind.
Referenced by llvm::codeview::DebugChecksumsSubsectionRef::classof(), llvm::codeview::DebugCrossModuleExportsSubsectionRef::classof(), llvm::codeview::DebugCrossModuleImportsSubsectionRef::classof(), llvm::codeview::DebugInlineeLinesSubsectionRef::classof(), llvm::codeview::DebugLinesSubsectionRef::classof(), llvm::codeview::DebugStringTableSubsectionRef::classof(), llvm::codeview::DebugSymbolRVASubsectionRef::classof(), and llvm::codeview::DebugSymbolsSubsectionRef::classof().
Member Data Documentation
Kind
DebugSubsectionKind llvm::codeview::DebugSubsectionRef::Kind protected
Definition at line 32 of file DebugSubsection.h.
Referenced by DebugSubsectionRef(), llvm::codeview::DebugUnknownSubsectionRef::DebugUnknownSubsectionRef(), and kind().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugSubsection.h
lib/DebugInfo/CodeView/DebugSubsection.cpp