LLVM: llvm::objcopy::elf::ASCIIHexWriter Class Reference
llvm::objcopy::elf::ASCIIHexWriter Class Reference abstract
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
ASCIIHexWriter (Object &Obj, raw_ostream &OS, StringRef OutputFile)
Error finalize () override
Public Member Functions inherited from llvm::objcopy::elf::Writer
virtual ~Writer ()
virtual Error write ()=0
Writer (Object &O, raw_ostream &Out)
Protected Member Functions
Error checkSection (const SectionBase &S) const
virtual Expected< size_t > getTotalSize (WritableMemoryBuffer &EmptyBuffer) const =0
Protected Attributes
StringRef OutputFileName
size_t TotalSize = 0
std::vector< const SectionBase * > Sections
Protected Attributes inherited from llvm::objcopy::elf::Writer
Object & Obj
std::unique_ptr< WritableMemoryBuffer > Buf
raw_ostream & Out
Detailed Description
Definition at line 378 of file ELFObject.h.
Constructor & Destructor Documentation
ASCIIHexWriter()
llvm::objcopy::elf::ASCIIHexWriter::ASCIIHexWriter (Object & Obj, raw_ostream & OS, StringRef OutputFile) inline
Definition at line 380 of file ELFObject.h.
References llvm::objcopy::elf::Writer::Obj, OutputFileName, and llvm::objcopy::elf::Writer::Writer().
Referenced by llvm::objcopy::elf::IHexWriter::IHexWriter(), and llvm::objcopy::elf::SRECWriter::SRECWriter().
Member Function Documentation
checkSection()
Error ASCIIHexWriter::checkSection (const SectionBase & S) const protected
Definition at line 2764 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Addr, addressOverflows32bit(), llvm::createStringError(), llvm::invalid_argument, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::SectionBase::Size, and llvm::Error::success().
Referenced by finalize().
finalize()
Error ASCIIHexWriter::finalize () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2774 of file ELFObject.cpp.
References A(), addressOverflows32bit(), B(), llvm::objcopy::elf::Writer::Buf, checkSection(), llvm::createStringError(), llvm::WritableMemoryBuffer::getNewMemBuffer(), getTotalSize(), llvm::invalid_argument, llvm::not_enough_memory, llvm::objcopy::elf::Writer::Obj, sectionPhysicalAddr(), Sections, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOBITS, llvm::sort(), llvm::Error::success(), llvm::Expected< T >::takeError(), TotalSize, and llvm::Twine::utohexstr().
getTotalSize()
virtual Expected< size_t > llvm::objcopy::elf::ASCIIHexWriter::getTotalSize (WritableMemoryBuffer & EmptyBuffer) const protected pure virtual
Referenced by finalize().
Member Data Documentation
OutputFileName
StringRef llvm::objcopy::elf::ASCIIHexWriter::OutputFileName protected
Definition at line 385 of file ELFObject.h.
Referenced by ASCIIHexWriter().
Sections
std::vector<const SectionBase *> llvm::objcopy::elf::ASCIIHexWriter::Sections protected
Definition at line 387 of file ELFObject.h.
Referenced by finalize(), llvm::objcopy::elf::IHexWriter::write(), and llvm::objcopy::elf::SRECWriter::write().
TotalSize
size_t llvm::objcopy::elf::ASCIIHexWriter::TotalSize = 0 protected
Definition at line 386 of file ELFObject.h.
Referenced by finalize(), llvm::objcopy::elf::IHexWriter::write(), and llvm::objcopy::elf::SRECWriter::write().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp