LLVM: llvm::sandboxir::InsertIntoBB Class Reference
llvm::sandboxir::InsertIntoBB Class Reference final
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
InsertIntoBB (Instruction *InsertedI)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 400 of file Tracker.h.
Constructor & Destructor Documentation
InsertIntoBB()
InsertIntoBB::InsertIntoBB (Instruction * InsertedI)
Definition at line 297 of file Tracker.cpp.
Member Function Documentation
accept()
void llvm::sandboxir::InsertIntoBB::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 406 of file Tracker.h.
dump() [1/2]
void InsertIntoBB::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 300 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::InsertIntoBB::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 408 of file Tracker.h.
revert()
void InsertIntoBB::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 295 of file Tracker.cpp.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp