LLVM: llvm::object::XCOFFSymbolRef Class Reference
llvm::object::XCOFFSymbolRef Class Reference
#include "llvm/Object/XCOFFObjectFile.h"
Public Types
enum { NAME_IN_STR_TBL_MAGIC = 0x0 }
Public Types inherited from llvm::object::SymbolRef
enum Type {
ST_Unknown , ST_Other , ST_Data , ST_Debug ,
ST_File , ST_Function
}
Public Types inherited from llvm::object::BasicSymbolRef
enum Flags : unsigned {
SF_None = 0 , SF_Undefined = 1U << 0 , SF_Global = 1U << 1 , SF_Weak = 1U << 2 ,
SF_Absolute = 1U << 3 , SF_Common = 1U << 4 , SF_Indirect = 1U << 5 , SF_Exported = 1U << 6 ,
SF_FormatSpecific = 1U << 7 , SF_Thumb = 1U << 8 , SF_Hidden = 1U << 9 , SF_Const = 1U << 10 ,
SF_Executable = 1U << 11
}
Public Member Functions
XCOFFSymbolRef (DataRefImpl SymEntDataRef, const XCOFFObjectFile *OwningObjectPtr)
const XCOFFSymbolEntry32 * getSymbol32 () const
const XCOFFSymbolEntry64 * getSymbol64 () const
uint64_t getValue () const
uint32_t getValue32 () const
uint64_t getValue64 () const
uint64_t getSize () const
int16_t getSectionNumber () const
uint16_t getSymbolType () const
uint8_t getLanguageIdForCFile () const
uint8_t getCPUTypeIddForCFile () const
XCOFF::StorageClass getStorageClass () const
uint8_t getNumberOfAuxEntries () const
uintptr_t getEntryAddress () const
LLVM_ABI Expected< StringRef > getName () const
LLVM_ABI Expected< bool > isFunction () const
LLVM_ABI bool isCsectSymbol () const
LLVM_ABI Expected< XCOFFCsectAuxRef > getXCOFFCsectAuxRef () const
Public Member Functions inherited from llvm::object::SymbolRef
SymbolRef ()=default
SymbolRef (DataRefImpl SymbolP, const ObjectFile *Owner)
SymbolRef (const BasicSymbolRef &B)
Expected< StringRef > getName () const
Expected< uint64_t > getAddress () const
Returns the symbol virtual address (i.e.
Expected< uint64_t > getValue () const
Return the value of the symbol depending on the object this can be an offset or a virtual address.
uint32_t getAlignment () const
Get the alignment of this symbol as the actual value (not log 2).
uint64_t getCommonSize () const
Expected< SymbolRef::Type > getType () const
Expected< section_iterator > getSection () const
Get section this symbol is defined in reference to.
const ObjectFile * getObject () const
Public Member Functions inherited from llvm::object::BasicSymbolRef
BasicSymbolRef ()=default
BasicSymbolRef (DataRefImpl SymbolP, const SymbolicFile *Owner)
bool operator== (const BasicSymbolRef &Other) const
bool operator< (const BasicSymbolRef &Other) const
void moveNext ()
Error printName (raw_ostream &OS) const
Expected< uint32_t > getFlags () const
Get symbol flags (bitwise OR of SymbolRef::Flags)
DataRefImpl getRawDataRefImpl () const
const SymbolicFile * getObject () const
Detailed Description
Definition at line 792 of file XCOFFObjectFile.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NAME_IN_STR_TBL_MAGIC
Definition at line 794 of file XCOFFObjectFile.h.
Constructor & Destructor Documentation
XCOFFSymbolRef()
llvm::object::XCOFFSymbolRef::XCOFFSymbolRef (DataRefImpl SymEntDataRef, const XCOFFObjectFile * OwningObjectPtr) inline
Definition at line 796 of file XCOFFObjectFile.h.
References assert(), llvm::object::DataRefImpl::p, and llvm::object::SymbolRef::SymbolRef().
Member Function Documentation
getCPUTypeIddForCFile()
uint8_t llvm::object::XCOFFSymbolRef::getCPUTypeIddForCFile () const inline
Definition at line 845 of file XCOFFObjectFile.h.
References assert(), llvm::XCOFF::C_FILE, getStorageClass(), and GETVALUE.
getEntryAddress()
uintptr_t llvm::object::XCOFFSymbolRef::getEntryAddress () const inline
Definition at line 857 of file XCOFFObjectFile.h.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
Referenced by getXCOFFCsectAuxRef().
getLanguageIdForCFile()
uint8_t llvm::object::XCOFFSymbolRef::getLanguageIdForCFile () const inline
Definition at line 839 of file XCOFFObjectFile.h.
References assert(), llvm::XCOFF::C_FILE, getStorageClass(), and GETVALUE.
getName()
Expected< StringRef > llvm::object::XCOFFSymbolRef::getName () const
Definition at line 1360 of file XCOFFObjectFile.cpp.
References llvm::object::generateXCOFFFixedNameStringRef(), llvm::object::SymbolRef::getObject(), getStorageClass(), getSymbol32(), getSymbol64(), is64Bit(), NAME_IN_STR_TBL_MAGIC, and llvm::Offset.
Referenced by llvm::object::XCOFFObjectFile::getSymbolName(), llvm::object::XCOFFObjectFile::getSymbolType(), getXCOFFCsectAuxRef(), and llvm::jitlink::printSymbolEntry().
getNumberOfAuxEntries()
uint8_t llvm::object::XCOFFSymbolRef::getNumberOfAuxEntries () const inline
Definition at line 853 of file XCOFFObjectFile.h.
References GETVALUE.
Referenced by getXCOFFCsectAuxRef().
getSectionNumber()
int16_t llvm::object::XCOFFSymbolRef::getSectionNumber () const inline
Definition at line 835 of file XCOFFObjectFile.h.
References GETVALUE.
Referenced by llvm::object::XCOFFObjectFile::getSymbolFlags(), llvm::object::XCOFFObjectFile::getSymbolSection(), llvm::object::XCOFFObjectFile::getSymbolSectionID(), llvm::object::XCOFFObjectFile::getSymbolSectionName(), llvm::object::XCOFFObjectFile::getSymbolType(), and llvm::jitlink::printSymbolEntry().
getSize()
uint64_t llvm::object::XCOFFSymbolRef::getSize () const inline
Definition at line 826 of file XCOFFObjectFile.h.
References llvm::object::SymbolRef::getObject(), and llvm::object::BasicSymbolRef::getRawDataRefImpl().
Referenced by isFunction(), and llvm::jitlink::printSymbolEntry().
getStorageClass()
XCOFF::StorageClass llvm::object::XCOFFSymbolRef::getStorageClass () const inline
Definition at line 851 of file XCOFFObjectFile.h.
References GETVALUE.
Referenced by getCPUTypeIddForCFile(), getLanguageIdForCFile(), getName(), llvm::object::XCOFFObjectFile::getSymbolFlags(), llvm::object::XCOFFObjectFile::getSymbolType(), isCsectSymbol(), and llvm::jitlink::printSymbolEntry().
getSymbol32()
const XCOFFSymbolEntry32 * llvm::object::XCOFFSymbolRef::getSymbol32 () const inline
Definition at line 804 of file XCOFFObjectFile.h.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
Referenced by getName().
getSymbol64()
const XCOFFSymbolEntry64 * llvm::object::XCOFFSymbolRef::getSymbol64 () const inline
Definition at line 808 of file XCOFFObjectFile.h.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
Referenced by getName().
getSymbolType()
uint16_t llvm::object::XCOFFSymbolRef::getSymbolType () const inline
Definition at line 837 of file XCOFFObjectFile.h.
References GETVALUE.
Referenced by llvm::object::XCOFFObjectFile::getSymbolFlags(), and isFunction().
getValue()
uint64_t llvm::object::XCOFFSymbolRef::getValue () const inline
Definition at line 812 of file XCOFFObjectFile.h.
References llvm::object::SymbolRef::getObject(), getValue32(), getValue64(), and llvm::object::SymbolicFile::is64Bit().
Referenced by llvm::object::XCOFFObjectFile::getSymbolAddress(), and llvm::object::XCOFFObjectFile::getSymbolValueImpl().
getValue32()
uint32_t llvm::object::XCOFFSymbolRef::getValue32 () const inline
Definition at line 816 of file XCOFFObjectFile.h.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
Referenced by getValue().
getValue64()
uint64_t llvm::object::XCOFFSymbolRef::getValue64 () const inline
Definition at line 821 of file XCOFFObjectFile.h.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
Referenced by getValue().
getXCOFFCsectAuxRef()
Expected< XCOFFCsectAuxRef > llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef () const
Definition at line 1317 of file XCOFFObjectFile.cpp.
References assert(), llvm::XCOFF::AUX_CSECT, llvm::object::createError(), llvm::object::XCOFFObjectFile::getAdvancedSymbolEntryAddress(), getEntryAddress(), getName(), getNumberOfAuxEntries(), llvm::object::SymbolRef::getObject(), is64Bit(), isCsectSymbol(), llvm::Expected< T >::takeError(), and llvm::object::viewAs().
Referenced by llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), llvm::object::XCOFFObjectFile::getSymbolAlignment(), llvm::object::XCOFFObjectFile::getSymbolFlags(), llvm::object::XCOFFObjectFile::getSymbolSize(), llvm::jitlink::getXCOFFSymbolContainingSymbolRef(), isFunction(), and llvm::jitlink::printSymbolEntry().
isCsectSymbol()
bool llvm::object::XCOFFSymbolRef::isCsectSymbol () const
Definition at line 1311 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::C_EXT, llvm::XCOFF::C_HIDEXT, llvm::XCOFF::C_WEAKEXT, and getStorageClass().
Referenced by llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), llvm::object::XCOFFObjectFile::getSymbolAlignment(), llvm::object::XCOFFObjectFile::getSymbolFlags(), llvm::object::XCOFFObjectFile::getSymbolSize(), getXCOFFCsectAuxRef(), llvm::jitlink::getXCOFFSymbolContainingSymbolRef(), isFunction(), and llvm::jitlink::printSymbolEntry().
isFunction()
Expected< bool > llvm::object::XCOFFSymbolRef::isFunction () const
Definition at line 1245 of file XCOFFObjectFile.cpp.
References llvm::cantFail(), llvm::object::createError(), llvm::object::FunctionSym, llvm::Expected< T >::get(), llvm::object::SymbolRef::getAddress(), llvm::object::XCOFFCsectAuxRef::getEntryAddress(), llvm::object::SymbolRef::getObject(), getSize(), llvm::object::XCOFFCsectAuxRef::getStorageMappingClass(), llvm::object::XCOFFCsectAuxRef::getSymbolType(), getSymbolType(), getXCOFFCsectAuxRef(), isCsectSymbol(), llvm::Expected< T >::takeError(), llvm::Twine::utohexstr(), llvm::XCOFF::XMC_GL, llvm::XCOFF::XMC_PR, llvm::XCOFF::XTY_CM, llvm::XCOFF::XTY_ER, llvm::XCOFF::XTY_LD, and llvm::XCOFF::XTY_SD.
Referenced by llvm::object::XCOFFObjectFile::getSymbolType().
The documentation for this class was generated from the following files:
include/llvm/Object/XCOFFObjectFile.h
lib/Object/XCOFFObjectFile.cpp