LLVM: llvm::PrintLoopPass Class Reference
llvm::PrintLoopPass Class Reference
Pass for printing a loop's contents as textual IR.
#include "llvm/Transforms/Scalar/LoopPassManager.h"
Public Member Functions
LLVM_ABI PrintLoopPass ()
LLVM_ABI PrintLoopPass (raw_ostream &OS, const std::string &Banner="")
LLVM_ABI PreservedAnalyses run (Loop &L, LoopAnalysisManager &, LoopStandardAnalysisResults &, LPMUpdater &)
Public Member Functions inherited from llvm::PassInfoMixin< PrintLoopPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< PrintLoopPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass for printing a loop's contents as textual IR.
Definition at line 499 of file LoopPassManager.h.
Constructor & Destructor Documentation
PrintLoopPass() [1/2]
PrintLoopPass::PrintLoopPass ()
Definition at line 361 of file LoopPassManager.cpp.
References llvm::dbgs().
PrintLoopPass() [2/2]
PrintLoopPass::PrintLoopPass (raw_ostream & OS, const std::string & Banner = "")
Definition at line 362 of file LoopPassManager.cpp.
Member Function Documentation
run()
PreservedAnalyses PrintLoopPass::run (Loop & L, LoopAnalysisManager & , LoopStandardAnalysisResults & , LPMUpdater &)
Definition at line 365 of file LoopPassManager.cpp.
References llvm::PreservedAnalyses::all(), and llvm::printLoop().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopPassManager.h
lib/Transforms/Scalar/LoopPassManager.cpp