LLVM: llvm::jitlink::ELFJITLinker_aarch32 Class Reference
llvm::jitlink::ELFJITLinker_aarch32 Class Reference
Public Member Functions
ELFJITLinker_aarch32 (std::unique_ptr< JITLinkContext > Ctx, std::unique_ptr< LinkGraph > G, PassConfiguration PassCfg, aarch32::ArmConfig ArmCfg)
Public Member Functions inherited from llvm::jitlink::JITLinker< ELFJITLinker_aarch32 >
JITLinkerBase (std::unique_ptr< JITLinkContext > Ctx, std::unique_ptr< LinkGraph > G, PassConfiguration Passes)
Public Member Functions inherited from llvm::jitlink::JITLinkerBase
JITLinkerBase (std::unique_ptr< JITLinkContext > Ctx, std::unique_ptr< LinkGraph > G, PassConfiguration Passes)
virtual ~JITLinkerBase ()
Friends
class JITLinker< ELFJITLinker_aarch32 >
Additional Inherited Members
Static Public Member Functions inherited from llvm::jitlink::JITLinker< ELFJITLinker_aarch32 >
static void link (ArgTs &&... Args)
Link constructs a LinkerImpl instance and calls linkPhase1.
Protected Types inherited from llvm::jitlink::JITLinkerBase
using InFlightAlloc = JITLinkMemoryManager::InFlightAlloc
using AllocResult = Expected<std::unique_ptr<InFlightAlloc>>
using FinalizeResult = Expected<JITLinkMemoryManager::FinalizedAlloc>
Protected Member Functions inherited from llvm::jitlink::JITLinkerBase
LinkGraph & getGraph ()
bool shouldAddDefaultTargetPasses (const Triple &TT)
PassConfiguration & getPassConfig ()
void linkPhase1 (std::unique_ptr< JITLinkerBase > Self)
void linkPhase2 (std::unique_ptr< JITLinkerBase > Self, AllocResult AR)
void linkPhase3 (std::unique_ptr< JITLinkerBase > Self, Expected< AsyncLookupResult > LookupResult)
void linkPhase4 (std::unique_ptr< JITLinkerBase > Self, FinalizeResult FR)
Detailed Description
Definition at line 123 of file ELF_aarch32.cpp.
Constructor & Destructor Documentation
ELFJITLinker_aarch32()
llvm::jitlink::ELFJITLinker_aarch32::ELFJITLinker_aarch32 (std::unique_ptr< JITLinkContext > Ctx, std::unique_ptr< LinkGraph > G, PassConfiguration PassCfg, aarch32::ArmConfig ArmCfg) inline
Definition at line 127 of file ELF_aarch32.cpp.
References llvm::move().
Friends And Related Symbol Documentation
JITLinker< ELFJITLinker_aarch32 >
friend class JITLinker< ELFJITLinker_aarch32 > friend
Definition at line 298 of file ELF_aarch32.cpp.
References llvm::jitlink::buildTables_ELF_aarch32(), llvm::ARM::getArchAttr(), llvm::jitlink::aarch32::getArmConfigForCPUArch(), llvm::jitlink::JITLinker< ELFJITLinker_aarch32 >::link(), llvm_unreachable, llvm::jitlink::markAllSymbolsLive(), llvm::ARM::parseArch(), llvm::jitlink::PassConfiguration::PostPrunePasses, llvm::jitlink::aarch32::pre_v7, llvm::jitlink::PassConfiguration::PrePrunePasses, llvm::jitlink::aarch32::Undefined, and llvm::jitlink::aarch32::v7.
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/ELF_aarch32.cpp