LLVM: llvm::LiveDebugVariables Class Reference
llvm::LiveDebugVariables Class Reference
#include "llvm/CodeGen/LiveDebugVariables.h"
Classes
class LDVImpl
Public Member Functions
LiveDebugVariables ()
Implementation of the LiveDebugVariables pass.
~LiveDebugVariables ()
LiveDebugVariables (LiveDebugVariables &&)
void analyze (MachineFunction &MF, LiveIntervals *LIS)
void splitRegister (Register OldReg, ArrayRef< Register > NewRegs, LiveIntervals &LIS)
splitRegister - Move any user variables in OldReg to the live ranges in NewRegs where they are live.
void emitDebugValues (VirtRegMap *VRM)
emitDebugValues - Emit new DBG_VALUE instructions reflecting the changes that happened during register allocation.
void dump () const
dump - Print data structures to dbgs().
void print (raw_ostream &OS) const
void releaseMemory ()
bool invalidate (MachineFunction &MF, const PreservedAnalyses &PA, MachineFunctionAnalysisManager::Invalidator &Inv)
Detailed Description
Definition at line 35 of file LiveDebugVariables.h.
Constructor & Destructor Documentation
LiveDebugVariables() [1/2]
llvm::LiveDebugVariables::LiveDebugVariables () default
Implementation of the LiveDebugVariables pass.
Referenced by LiveDebugVariables().
~LiveDebugVariables()
llvm::LiveDebugVariables::~LiveDebugVariables () default
LiveDebugVariables() [2/2]
llvm::LiveDebugVariables::LiveDebugVariables (LiveDebugVariables &&) default
References LiveDebugVariables().
Member Function Documentation
analyze()
void LiveDebugVariables::analyze (MachineFunction & MF, LiveIntervals * LIS)
Definition at line 1357 of file LiveDebugVariables.cpp.
References EnableLDV, llvm::MachineFunction::getFunction(), llvm::Function::getSubprogram(), removeDebugInstrs(), and llvm::MachineFunction::useDebugInstrRef().
dump()
LLVM_DUMP_METHOD void LiveDebugVariables::dump () const
dump - Print data structures to dbgs().
Definition at line 2011 of file LiveDebugVariables.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
emitDebugValues()
void LiveDebugVariables::emitDebugValues (VirtRegMap * VRM)
emitDebugValues - Emit new DBG_VALUE instructions reflecting the changes that happened during register allocation.
Parameters
VRM Rename virtual registers according to map.
Definition at line 2005 of file LiveDebugVariables.cpp.
invalidate()
bool LiveDebugVariables::invalidate (MachineFunction & MF, const PreservedAnalyses & PA, MachineFunctionAnalysisManager::Invalidator & Inv)
Definition at line 1347 of file LiveDebugVariables.cpp.
References llvm::PreservedAnalyses::getChecker().
print()
void LiveDebugVariables::print (raw_ostream & OS) const
Definition at line 2014 of file LiveDebugVariables.cpp.
Referenced by dump(), and llvm::LiveDebugVariables::LDVImpl::runOnMachineFunction().
releaseMemory()
void LiveDebugVariables::releaseMemory ()
Definition at line 1342 of file LiveDebugVariables.cpp.
splitRegister()
void LiveDebugVariables::splitRegister (Register OldReg, ArrayRef< Register > NewRegs, LiveIntervals & LIS)
splitRegister - Move any user variables in OldReg to the live ranges in NewRegs where they are live.
Mark the values as unavailable where no new register is live.
Definition at line 1552 of file LiveDebugVariables.cpp.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveDebugVariables.h
lib/CodeGen/LiveDebugVariables.cpp