LLVM: llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator Class Reference
llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator Class Reference
#include "llvm/ADT/DenseSet.h"
Public Types
using difference_type = typename MapTy::iterator::difference_type
using value_type = ValueT
using pointer = value_type *
using reference = value_type &
using iterator_category = std::forward_iterator_tag
Public Member Functions
Iterator ()=default
Iterator (const typename MapTy::iterator &i)
ValueT & operator* ()
const ValueT & operator* () const
ValueT * operator-> ()
const ValueT * operator-> () const
Iterator & operator++ ()
Iterator operator++ (int)
Friends
class DenseSetImpl
class ConstIterator
bool operator== (const Iterator &X, const Iterator &Y)
bool operator!= (const Iterator &X, const Iterator &Y)
Detailed Description
template<typename ValueT, typename MapTy, typename ValueInfoT>
class llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator
Definition at line 111 of file DenseSet.h.
Member Typedef Documentation
difference_type
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::difference_type = typename MapTy::iterator::difference_type
Definition at line 117 of file DenseSet.h.
iterator_category
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::iterator_category = std::forward_iterator_tag
Definition at line 121 of file DenseSet.h.
pointer
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::pointer = value_type *
Definition at line 119 of file DenseSet.h.
reference
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::reference = value_type &
Definition at line 120 of file DenseSet.h.
value_type
template<typename ValueT, typename MapTy, typename ValueInfoT> using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::value_type = ValueT
Definition at line 118 of file DenseSet.h.
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::Iterator () default
Referenced by operator!=, operator++(), operator++(), and operator==.
Iterator() [2/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::Iterator (const typename MapTy::iterator & i) inline
Definition at line 124 of file DenseSet.h.
Member Function Documentation
operator*() [1/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> ValueT & llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::operator* () inline
Definition at line 126 of file DenseSet.h.
operator*() [2/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> const ValueT & llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::operator* () const inline
Definition at line 127 of file DenseSet.h.
operator++() [1/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> Iterator & llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::operator++ () inline
Definition at line 131 of file DenseSet.h.
References Iterator().
operator++() [2/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> Iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::operator++ (int) inline
Definition at line 135 of file DenseSet.h.
References Iterator(), and T.
operator->() [1/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> ValueT * llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::operator-> () inline
Definition at line 128 of file DenseSet.h.
operator->() [2/2]
template<typename ValueT, typename MapTy, typename ValueInfoT> const ValueT * llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::Iterator::operator-> () const inline
Definition at line 129 of file DenseSet.h.
Friends And Related Symbol Documentation
ConstIterator
template<typename ValueT, typename MapTy, typename ValueInfoT> friend class ConstIterator friend
Definition at line 114 of file DenseSet.h.
References ConstIterator.
Referenced by ConstIterator.
DenseSetImpl
template<typename ValueT, typename MapTy, typename ValueInfoT> friend class DenseSetImpl friend
Definition at line 113 of file DenseSet.h.
References DenseSetImpl.
Referenced by DenseSetImpl.
operator!=
template<typename ValueT, typename MapTy, typename ValueInfoT> bool operator!= (const Iterator & X, const Iterator & Y) friend
Definition at line 143 of file DenseSet.h.
References Iterator(), X, and Y.
operator==
template<typename ValueT, typename MapTy, typename ValueInfoT> bool operator== (const Iterator & X, const Iterator & Y) friend
Definition at line 140 of file DenseSet.h.
References Iterator(), X, and Y.
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseSet.h