LLVM: llvm::objcopy::elf::ELFSectionWriter< ELFT > Class Template Reference
llvm::objcopy::elf::ELFSectionWriter< ELFT > Class Template Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~ELFSectionWriter ()
Error visit (const SymbolTableSection &Sec) override
Error visit (const RelocationSection &Sec) override
Error visit (const GnuDebugLinkSection &Sec) override
Error visit (const GroupSection &Sec) override
Error visit (const SectionIndexSection &Sec) override
Error visit (const CompressedSection &Sec) override
Error visit (const DecompressedSection &Sec) override
ELFSectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionWriter
virtual ~SectionWriter ()=default
Error visit (const Section &Sec) override
Error visit (const OwnedDataSection &Sec) override
Error visit (const StringTableSection &Sec) override
Error visit (const DynamicRelocationSection &Sec) override
SectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionVisitor
virtual ~SectionVisitor ()=default
Additional Inherited Members
Protected Attributes inherited from llvm::objcopy::elf::SectionWriter
WritableMemoryBuffer & Out
Detailed Description
template<class ELFT>
class llvm::objcopy::elf::ELFSectionWriter< ELFT >
Definition at line 129 of file ELFObject.h.
Constructor & Destructor Documentation
~ELFSectionWriter()
template<class ELFT> virtual llvm::objcopy::elf::ELFSectionWriter< ELFT >::~ELFSectionWriter () inline virtual
Definition at line 137 of file ELFObject.h.
ELFSectionWriter()
template<class ELFT> llvm::objcopy::elf::ELFSectionWriter< ELFT >::ELFSectionWriter (WritableMemoryBuffer & Buf) inline explicit
Definition at line 146 of file ELFObject.h.
References llvm::objcopy::elf::SectionWriter::SectionWriter().
Member Function Documentation
visit() [1/7]
template<class ELFT> Error ELFSectionWriter::visit (const CompressedSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Definition at line 534 of file ELFObject.cpp.
References llvm::ArrayRef< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ELF::ELFCOMPRESS_ZLIB, llvm::ELF::ELFCOMPRESS_ZSTD, llvm::ArrayRef< T >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::None, llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::SectionBase::OriginalData, llvm::objcopy::elf::SectionWriter::Out, llvm::Error::success(), llvm::Zlib, and llvm::Zstd.
visit() [2/7]
template<class ELFT> Error ELFSectionWriter::visit (const DecompressedSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Definition at line 461 of file ELFObject.cpp.
References llvm::objcopy::elf::DecompressedSection::ChType, llvm::copy(), llvm::createStringError(), llvm::compression::decompress(), llvm::ELF::ELFCOMPRESS_ZLIB, llvm::ELF::ELFCOMPRESS_ZSTD, llvm::compression::formatFor(), llvm::compression::getReasonIfUnsupported(), llvm::invalid_argument, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::SectionBase::OriginalData, llvm::objcopy::elf::SectionWriter::Out, llvm::objcopy::elf::SectionBase::Size, llvm::ArrayRef< T >::slice(), llvm::Error::success(), llvm::toString(), llvm::Zlib, and llvm::Zstd.
visit() [3/7]
template<class ELFT> Error ELFSectionWriter::visit (const GnuDebugLinkSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Definition at line 1179 of file ELFObject.cpp.
References llvm::copy(), llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::SectionWriter::Out, llvm::objcopy::elf::SectionBase::Size, and llvm::Error::success().
visit() [4/7]
template<class ELFT> Error ELFSectionWriter::visit (const GroupSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Definition at line 1198 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Index, llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::SectionWriter::Out, llvm::Error::success(), and llvm::support::endian::write32().
visit() [5/7]
template<class ELFT> Error ELFSectionWriter::visit (const RelocationSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Definition at line 984 of file ELFObject.cpp.
References llvm::ELF::encodeCrel(), llvm::objcopy::elf::RelocationSection::getObject(), llvm::objcopy::elf::Object::IsMips64EL, llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::SectionWriter::Out, llvm::ELF::SHT_CREL, llvm::ELF::SHT_REL, llvm::Error::success(), llvm::objcopy::elf::SectionBase::Type, and writeRel().
visit() [6/7]
template<class ELFT> Error ELFSectionWriter::visit (const SectionIndexSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Definition at line 615 of file ELFObject.cpp.
References llvm::copy(), llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::SectionWriter::Out, and llvm::Error::success().
visit() [7/7]
template<class ELFT> Error ELFSectionWriter::visit (const SymbolTableSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Definition at line 862 of file ELFObject.cpp.
References llvm::objcopy::elf::Symbol::Binding, llvm::objcopy::elf::Symbol::getShndx(), llvm::objcopy::elf::Symbol::NameIndex, llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::SectionWriter::Out, llvm::objcopy::elf::Symbol::Size, llvm::Error::success(), llvm::objcopy::elf::SymbolTableSection::Symbols, llvm::objcopy::elf::Symbol::Type, llvm::objcopy::elf::Symbol::Value, and llvm::objcopy::elf::Symbol::Visibility.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp