LLVM: llvm::DXILResourceMap Class Reference
llvm::DXILResourceMap Class Reference
#include "llvm/Analysis/DXILResource.h"
Classes
struct call_iterator
Public Types
using iterator = SmallVector<dxil::ResourceInfo>::iterator
using const_iterator = SmallVector<dxil::ResourceInfo>::const_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool empty () const
iterator find (const CallInst *Key)
const_iterator find (const CallInst *Key) const
iterator srv_begin ()
const_iterator srv_begin () const
iterator srv_end ()
const_iterator srv_end () const
iterator_range< iterator > srvs ()
iterator_range< const_iterator > srvs () const
iterator uav_begin ()
const_iterator uav_begin () const
iterator uav_end ()
const_iterator uav_end () const
iterator_range< iterator > uavs ()
iterator_range< const_iterator > uavs () const
iterator cbuffer_begin ()
const_iterator cbuffer_begin () const
iterator cbuffer_end ()
const_iterator cbuffer_end () const
iterator_range< iterator > cbuffers ()
iterator_range< const_iterator > cbuffers () const
iterator sampler_begin ()
const_iterator sampler_begin () const
iterator sampler_end ()
const_iterator sampler_end () const
iterator_range< iterator > samplers ()
iterator_range< const_iterator > samplers () const
call_iterator call_begin ()
call_iterator call_end ()
iterator_range< call_iterator > calls ()
bool hasInvalidCounterDirection () const
LLVM_ABI void print (raw_ostream &OS, DXILResourceTypeMap &DRTM, const DataLayout &DL) const
Friends
class DXILResourceAnalysis
class DXILResourceWrapperPass
Detailed Description
Definition at line 465 of file DXILResource.h.
Member Typedef Documentation
const_iterator
using llvm::DXILResourceMap::const_iterator = SmallVector<dxil::ResourceInfo>::const_iterator
Definition at line 491 of file DXILResource.h.
iterator
using llvm::DXILResourceMap::iterator = SmallVector<dxil::ResourceInfo>::iterator
Definition at line 490 of file DXILResource.h.
Member Function Documentation
begin() [1/2]
iterator llvm::DXILResourceMap::begin () inline
Definition at line 493 of file DXILResource.h.
Referenced by cbuffer_begin(), cbuffer_begin(), cbuffer_end(), cbuffer_end(), sampler_begin(), sampler_begin(), srv_begin(), srv_begin(), srv_end(), srv_end(), uav_begin(), uav_begin(), uav_end(), and uav_end().
begin() [2/2]
const_iterator llvm::DXILResourceMap::begin () const inline
Definition at line 494 of file DXILResource.h.
call_begin()
call_iterator llvm::DXILResourceMap::call_begin () inline
Definition at line 559 of file DXILResource.h.
Referenced by calls().
call_end()
call_iterator llvm::DXILResourceMap::call_end () inline
Definition at line 560 of file DXILResource.h.
Referenced by calls().
calls()
iterator_range< call_iterator > llvm::DXILResourceMap::calls () inline
Definition at line 561 of file DXILResource.h.
References call_begin(), call_end(), and llvm::make_range().
cbuffer_begin() [1/2]
iterator llvm::DXILResourceMap::cbuffer_begin () inline
Definition at line 528 of file DXILResource.h.
References begin().
Referenced by cbuffers(), and cbuffers().
cbuffer_begin() [2/2]
const_iterator llvm::DXILResourceMap::cbuffer_begin () const inline
Definition at line 529 of file DXILResource.h.
References begin().
cbuffer_end() [1/2]
iterator llvm::DXILResourceMap::cbuffer_end () inline
Definition at line 530 of file DXILResource.h.
References begin().
Referenced by cbuffers(), and cbuffers().
cbuffer_end() [2/2]
const_iterator llvm::DXILResourceMap::cbuffer_end () const inline
Definition at line 531 of file DXILResource.h.
References begin().
cbuffers() [1/2]
iterator_range< iterator > llvm::DXILResourceMap::cbuffers () inline
Definition at line 532 of file DXILResource.h.
References cbuffer_begin(), cbuffer_end(), and llvm::make_range().
Referenced by emitResourceMetadata().
cbuffers() [2/2]
iterator_range< const_iterator > llvm::DXILResourceMap::cbuffers () const inline
Definition at line 535 of file DXILResource.h.
References cbuffer_begin(), cbuffer_end(), and llvm::make_range().
empty()
bool llvm::DXILResourceMap::empty () const inline
Definition at line 498 of file DXILResource.h.
Referenced by emitResourceMetadata().
end() [1/2]
iterator llvm::DXILResourceMap::end () inline
Definition at line 495 of file DXILResource.h.
Referenced by sampler_end(), and sampler_end().
end() [2/2]
const_iterator llvm::DXILResourceMap::end () const inline
Definition at line 496 of file DXILResource.h.
find() [1/2]
iterator llvm::DXILResourceMap::find (const CallInst * Key) inline
Definition at line 500 of file DXILResource.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
find() [2/2]
const_iterator llvm::DXILResourceMap::find (const CallInst * Key) const inline
Definition at line 505 of file DXILResource.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
hasInvalidCounterDirection()
bool llvm::DXILResourceMap::hasInvalidCounterDirection () const inline
Definition at line 565 of file DXILResource.h.
print()
void DXILResourceMap::print (raw_ostream & OS, DXILResourceTypeMap & DRTM, const DataLayout & DL) const
Definition at line 941 of file DXILResource.cpp.
References DL, llvm::dxil::ResourceInfo::getHandleTy(), I, llvm::dxil::ResourceInfo::print(), and llvm::Value::print().
Referenced by llvm::DXILResourcePrinterPass::run().
sampler_begin() [1/2]
iterator llvm::DXILResourceMap::sampler_begin () inline
Definition at line 539 of file DXILResource.h.
References begin().
Referenced by samplers(), and samplers().
sampler_begin() [2/2]
const_iterator llvm::DXILResourceMap::sampler_begin () const inline
Definition at line 540 of file DXILResource.h.
References begin().
sampler_end() [1/2]
iterator llvm::DXILResourceMap::sampler_end () inline
Definition at line 541 of file DXILResource.h.
References end().
Referenced by samplers(), and samplers().
sampler_end() [2/2]
const_iterator llvm::DXILResourceMap::sampler_end () const inline
Definition at line 542 of file DXILResource.h.
References end().
samplers() [1/2]
iterator_range< iterator > llvm::DXILResourceMap::samplers () inline
Definition at line 543 of file DXILResource.h.
References llvm::make_range(), sampler_begin(), and sampler_end().
Referenced by emitResourceMetadata().
samplers() [2/2]
iterator_range< const_iterator > llvm::DXILResourceMap::samplers () const inline
Definition at line 546 of file DXILResource.h.
References llvm::make_range(), sampler_begin(), and sampler_end().
srv_begin() [1/2]
iterator llvm::DXILResourceMap::srv_begin () inline
Definition at line 510 of file DXILResource.h.
References begin().
Referenced by srvs(), and srvs().
srv_begin() [2/2]
const_iterator llvm::DXILResourceMap::srv_begin () const inline
Definition at line 511 of file DXILResource.h.
References begin().
srv_end() [1/2]
iterator llvm::DXILResourceMap::srv_end () inline
Definition at line 512 of file DXILResource.h.
References begin().
Referenced by srvs(), and srvs().
srv_end() [2/2]
const_iterator llvm::DXILResourceMap::srv_end () const inline
Definition at line 513 of file DXILResource.h.
References begin().
srvs() [1/2]
iterator_range< iterator > llvm::DXILResourceMap::srvs () inline
Definition at line 514 of file DXILResource.h.
References llvm::make_range(), srv_begin(), and srv_end().
Referenced by emitResourceMetadata().
srvs() [2/2]
iterator_range< const_iterator > llvm::DXILResourceMap::srvs () const inline
Definition at line 515 of file DXILResource.h.
References llvm::make_range(), srv_begin(), and srv_end().
uav_begin() [1/2]
iterator llvm::DXILResourceMap::uav_begin () inline
Definition at line 519 of file DXILResource.h.
References begin().
Referenced by uavs(), and uavs().
uav_begin() [2/2]
const_iterator llvm::DXILResourceMap::uav_begin () const inline
Definition at line 520 of file DXILResource.h.
References begin().
uav_end() [1/2]
iterator llvm::DXILResourceMap::uav_end () inline
Definition at line 521 of file DXILResource.h.
References begin().
Referenced by uavs(), and uavs().
uav_end() [2/2]
const_iterator llvm::DXILResourceMap::uav_end () const inline
Definition at line 522 of file DXILResource.h.
References begin().
uavs() [1/2]
iterator_range< iterator > llvm::DXILResourceMap::uavs () inline
Definition at line 523 of file DXILResource.h.
References llvm::make_range(), uav_begin(), and uav_end().
Referenced by emitResourceMetadata(), and hasUAVsAtEveryStage().
uavs() [2/2]
iterator_range< const_iterator > llvm::DXILResourceMap::uavs () const inline
Definition at line 524 of file DXILResource.h.
References llvm::make_range(), uav_begin(), and uav_end().
Friends And Related Symbol Documentation
DXILResourceAnalysis
friend class DXILResourceAnalysis friend
Definition at line 570 of file DXILResource.h.
References DXILResourceAnalysis.
Referenced by DXILResourceAnalysis.
DXILResourceWrapperPass
friend class DXILResourceWrapperPass friend
Definition at line 571 of file DXILResource.h.
References DXILResourceWrapperPass.
Referenced by DXILResourceWrapperPass.
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILResource.h
lib/Analysis/DXILResource.cpp