LLVM: llvm::PredIteratorCache Class Reference
llvm::PredIteratorCache Class Reference
PredIteratorCache - This class is an extremely trivial cache for predecessor iterator queries.
#include "llvm/IR/PredIteratorCache.h"
Public Member Functions
size_t size (BasicBlock *BB)
ArrayRef< BasicBlock * > get (BasicBlock *BB)
void clear ()
clear - Remove all information.
Detailed Description
PredIteratorCache - This class is an extremely trivial cache for predecessor iterator queries.
This is useful for code that repeatedly wants the predecessor list for the same blocks.
Definition at line 27 of file PredIteratorCache.h.
Member Function Documentation
clear()
void llvm::PredIteratorCache::clear () inline
clear - Remove all information.
Definition at line 49 of file PredIteratorCache.h.
get()
ArrayRef< BasicBlock * > llvm::PredIteratorCache::get (BasicBlock * BB) inline
Definition at line 36 of file PredIteratorCache.h.
References llvm::ArrayRef(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::Data, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::predecessors(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by ComputeLiveInBlocks(), formLCSSAForInstructionsImpl(), and size().
size()
size_t llvm::PredIteratorCache::size (BasicBlock * BB) inline
Definition at line 35 of file PredIteratorCache.h.
References get().
Referenced by formLCSSAForInstructionsImpl().
The documentation for this class was generated from the following file:
include/llvm/IR/PredIteratorCache.h