LLVM: llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy > Class Template Reference
llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy > Class Template Reference
#include "llvm/ProfileData/MemProfRadixTree.h"
Public Member Functions
CallStackRadixTreeBuilder ()=default
void build (llvm::MapVector< CallStackId, llvm::SmallVector< FrameIdTy > > &&MemProfCallStackData, const llvm::DenseMap< FrameIdTy, LinearFrameId > *MemProfFrameIndexes, llvm::DenseMap< FrameIdTy, FrameStat > &FrameHistogram)
ArrayRef< LinearFrameId > getRadixArray () const
llvm::DenseMap< CallStackId, LinearCallStackId > takeCallStackPos ()
Detailed Description
template<typename FrameIdTy>
class llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >
Definition at line 305 of file MemProfRadixTree.h.
Constructor & Destructor Documentation
CallStackRadixTreeBuilder()
template<typename FrameIdTy> llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::CallStackRadixTreeBuilder () default
Member Function Documentation
build()
template<typename FrameIdTy> void llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::build (llvm::MapVector< CallStackId, llvm::SmallVector< FrameIdTy > > && MemProfCallStackData, const llvm::DenseMap< FrameIdTy, LinearFrameId > * MemProfFrameIndexes, llvm::DenseMap< FrameIdTy, FrameStat > & FrameHistogram)
Definition at line 93 of file MemProfRadixTree.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), I, llvm::reverse(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::sort(), and std::swap().
Referenced by writeMemoryProfileRadixTree(), and llvm::writeMemProfCallStackArray().
getRadixArray()
template<typename FrameIdTy> ArrayRef< LinearFrameId > llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::getRadixArray () const inline
Definition at line 351 of file MemProfRadixTree.h.
takeCallStackPos()
template<typename FrameIdTy> llvm::DenseMap< CallStackId, LinearCallStackId > llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::takeCallStackPos () inline
Definition at line 353 of file MemProfRadixTree.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/MemProfRadixTree.h
lib/ProfileData/MemProfRadixTree.cpp