LLVM: llvm::orc::ORCPlatformSupport Class Reference
llvm::orc::ORCPlatformSupport Class Reference
A Platform-support class that implements initialize / deinitialize by forwarding to ORC runtime dlopen / dlclose operations.
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
ORCPlatformSupport (orc::LLJIT &J)
Error initialize (orc::JITDylib &JD) override
Error deinitialize (orc::JITDylib &JD) override
Public Member Functions inherited from llvm::orc::LLJIT::PlatformSupport
virtual ~PlatformSupport ()
Additional Inherited Members
Static Protected Member Functions inherited from llvm::orc::LLJIT::PlatformSupport
static void setInitTransform (LLJIT &J, IRTransformLayer::TransformFunction T)
Detailed Description
A Platform-support class that implements initialize / deinitialize by forwarding to ORC runtime dlopen / dlclose operations.
Definition at line 615 of file LLJIT.h.
Constructor & Destructor Documentation
ORCPlatformSupport()
llvm::orc::ORCPlatformSupport::ORCPlatformSupport (orc::LLJIT & J) inline
Definition at line 617 of file LLJIT.h.
Member Function Documentation
deinitialize()
Error llvm::orc::ORCPlatformSupport::deinitialize (orc::JITDylib & JD) override virtual
Implements llvm::orc::LLJIT::PlatformSupport.
Definition at line 650 of file LLJIT.cpp.
References llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::Error::success().
initialize()
Error llvm::orc::ORCPlatformSupport::initialize (orc::JITDylib & JD) override virtual
Implements llvm::orc::LLJIT::PlatformSupport.
Definition at line 603 of file LLJIT.cpp.
References llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LLJIT.h
lib/ExecutionEngine/Orc/LLJIT.cpp