LLVM: llvm::RegAllocPriorityAdvisorAnalysisLegacy Class Reference
llvm::RegAllocPriorityAdvisorAnalysisLegacy Class Reference
#include "llvm/CodeGen/RegAllocPriorityAdvisor.h"
Public Types
using AdvisorMode = RegAllocPriorityAdvisorProvider::AdvisorMode
Public Member Functions
RegAllocPriorityAdvisorAnalysisLegacy (AdvisorMode Mode)
RegAllocPriorityAdvisorProvider & getProvider ()
Get an advisor for the given context (i.e. machine function, etc)
AdvisorMode getAdvisorMode () const
virtual void logRewardIfNeeded (const MachineFunction &MF, llvm::function_ref< float()> GetReward)
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Protected Member Functions
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (const Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes
std::unique_ptr< RegAllocPriorityAdvisorProvider > Provider
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 127 of file RegAllocPriorityAdvisor.h.
Member Typedef Documentation
AdvisorMode
using llvm::RegAllocPriorityAdvisorAnalysisLegacy::AdvisorMode = RegAllocPriorityAdvisorProvider::AdvisorMode
Definition at line 129 of file RegAllocPriorityAdvisor.h.
Constructor & Destructor Documentation
RegAllocPriorityAdvisorAnalysisLegacy()
llvm::RegAllocPriorityAdvisorAnalysisLegacy::RegAllocPriorityAdvisorAnalysisLegacy (AdvisorMode Mode) inline
Definition at line 130 of file RegAllocPriorityAdvisor.h.
References ID, and llvm::ImmutablePass::ImmutablePass().
Referenced by llvm::ReleaseModePriorityAdvisorAnalysisLegacy::classof(), INITIALIZE_PASS(), and llvm::ReleaseModePriorityAdvisorAnalysisLegacy::ReleaseModePriorityAdvisorAnalysisLegacy().
Member Function Documentation
getAdvisorMode()
AdvisorMode llvm::RegAllocPriorityAdvisorAnalysisLegacy::getAdvisorMode () const inline
Definition at line 136 of file RegAllocPriorityAdvisor.h.
getAnalysisUsage()
void llvm::RegAllocPriorityAdvisorAnalysisLegacy::getAnalysisUsage (AnalysisUsage &) const inline override protected virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 143 of file RegAllocPriorityAdvisor.h.
References llvm::AnalysisUsage::setPreservesAll().
Referenced by INITIALIZE_PASS().
getProvider()
RegAllocPriorityAdvisorProvider & llvm::RegAllocPriorityAdvisorAnalysisLegacy::getProvider () inline
Get an advisor for the given context (i.e. machine function, etc)
Definition at line 135 of file RegAllocPriorityAdvisor.h.
References Provider.
logRewardIfNeeded()
virtual void llvm::RegAllocPriorityAdvisorAnalysisLegacy::logRewardIfNeeded (const MachineFunction & MF, llvm::function_ref< float()> GetReward) inline virtual
Definition at line 137 of file RegAllocPriorityAdvisor.h.
Member Data Documentation
ID
char RegAllocPriorityAdvisorAnalysisLegacy::ID = 0 static
Definition at line 132 of file RegAllocPriorityAdvisor.h.
Referenced by RegAllocPriorityAdvisorAnalysisLegacy().
Provider
std::unique_ptr<RegAllocPriorityAdvisorProvider> llvm::RegAllocPriorityAdvisorAnalysisLegacy::Provider protected
Definition at line 147 of file RegAllocPriorityAdvisor.h.
Referenced by getProvider().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegAllocPriorityAdvisor.h
lib/CodeGen/RegAllocPriorityAdvisor.cpp