LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4 Class Reference
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerMsgPackV4 ()=default
~MetadataStreamerMsgPackV4 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()=default
Protected Member Functions
void dump (StringRef HSAMetadataString) const
void verify (StringRef HSAMetadataString) const
std::optional< StringRef > getAccessQualifier (StringRef AccQual) const
std::optional< StringRef > getAddressSpaceQualifier (unsigned AddressSpace) const
StringRef getValueKind (Type *Ty, StringRef TypeQual, StringRef BaseTypeName) const
std::string getTypeName (Type *Ty, bool Signed) const
msgpack::ArrayDocNode getWorkGroupDimensions (MDNode *Node) const
msgpack::MapDocNode getHSAKernelProps (const MachineFunction &MF, const SIProgramInfo &ProgramInfo, unsigned CodeObjectVersion) const
void emitVersion () override
void emitTargetID (const IsaInfo::AMDGPUTargetID &TargetID)
void emitPrintf (const Module &Mod)
void emitKernelLanguage (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelAttrs (const AMDGPUTargetMachine &TM, const Function &Func, msgpack::MapDocNode Kern) override
void emitKernelArgs (const MachineFunction &MF, msgpack::MapDocNode Kern)
void emitKernelArg (const Argument &Arg, unsigned &Offset, msgpack::ArrayDocNode Args)
void emitKernelArg (const DataLayout &DL, Type *Ty, Align Alignment, StringRef ValueKind, unsigned &Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign=std::nullopt, StringRef Name="", StringRef TypeName="", StringRef BaseTypeName="", StringRef ActAccQual="", StringRef AccQual="", StringRef TypeQual="")
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
msgpack::DocNode & getRootMetadata (StringRef Key)
msgpack::DocNode & getHSAMetadataRoot ()
Protected Attributes
std::unique_ptr< DelayedMCExprs > DelayedExprs
std::unique_ptr< msgpack::Document > HSAMetadataDoc
Detailed Description
Definition at line 68 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerMsgPackV4()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::MetadataStreamerMsgPackV4 () default
~MetadataStreamerMsgPackV4()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::~MetadataStreamerMsgPackV4 () default
References begin(), emitKernel(), emitTo(), end(), and llvm::Mod.
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::begin (const Module & Mod, const IsaInfo::AMDGPUTargetID & TargetID) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 561 of file AMDGPUHSAMetadataStreamer.cpp.
References DelayedExprs, emitPrintf(), emitTargetID(), emitVersion(), getRootMetadata(), HSAMetadataDoc, and llvm::Mod.
Referenced by ~MetadataStreamerMsgPackV4().
dump()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::dump (StringRef HSAMetadataString) const protected
Definition at line 79 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs().
Referenced by end().
emitHiddenKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitHiddenKernelArgs (const MachineFunction & MF, unsigned & Offset, msgpack::ArrayDocNode Args) override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5.
Definition at line 415 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::alignTo(), DL, emitKernelArg(), llvm::PointerType::get(), llvm::MachineFunction::getFunction(), llvm::Type::getInt64Ty(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUAS::GLOBAL_ADDRESS, and llvm::Offset.
Referenced by emitKernelArgs().
emitKernel()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 582 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, emitKernelArgs(), emitKernelAttrs(), emitKernelLanguage(), llvm::AMDGPU::getAMDHSACodeObjectVersion(), llvm::msgpack::DocNode::getArray(), llvm::MachineFunction::getFunction(), getHSAKernelProps(), getRootMetadata(), llvm::MachineFunction::getTarget(), and llvm::CallingConv::SPIR_KERNEL.
Referenced by ~MetadataStreamerMsgPackV4().
emitKernelArg() [1/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelArg (const Argument & Arg, unsigned & Offset, msgpack::ArrayDocNode Args) protected
Definition at line 301 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::cast(), DL, llvm::dyn_cast(), emitKernelArg(), llvm::Argument::getArgNo(), getArgumentTypeAlign(), llvm::Value::getName(), llvm::Argument::getParamAlign(), llvm::Argument::getParamByRefType(), llvm::Argument::getParent(), llvm::Value::getType(), getValueKind(), llvm::Argument::hasAttribute(), llvm::Argument::hasByRefAttr(), llvm::Value::hasName(), llvm::Argument::hasNoAliasAttr(), llvm::Type::isPointerTy(), llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::Offset, llvm::Argument::onlyReadsMemory(), and llvm::MaybeAlign::valueOrOne().
Referenced by emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), emitKernelArg(), and emitKernelArgs().
emitKernelArg() [2/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelArg (const DataLayout & DL, Type * Ty, Align Alignment, StringRef ValueKind, unsigned & Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign = std::nullopt, StringRef Name = "", StringRef TypeName = "", StringRef BaseTypeName = "", StringRef ActAccQual = "", StringRef AccQual = "", StringRef TypeQual = "") protected
Definition at line 366 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::alignTo(), DL, llvm::dyn_cast(), getAccessQualifier(), getAddressSpaceQualifier(), llvm::Offset, Size, and llvm::StringRef::split().
emitKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelArgs (const MachineFunction & MF, msgpack::MapDocNode Kern) protected
Definition at line 284 of file AMDGPUHSAMetadataStreamer.cpp.
References emitHiddenKernelArgs(), emitKernelArg(), llvm::MachineFunction::getFunction(), HSAMetadataDoc, and llvm::Offset.
Referenced by emitKernel().
emitKernelAttrs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelAttrs (const AMDGPUTargetMachine & TM, const Function & Func, msgpack::MapDocNode Kern) override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5.
Definition at line 256 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::cast(), llvm::mdconst::extract(), llvm::msgpack::DocNode::getDocument(), getEnqueuedBlockSymbolName(), llvm::msgpack::Document::getNode(), llvm::getTypeName(), and getWorkGroupDimensions().
Referenced by emitKernel(), and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitKernelAttrs().
emitKernelLanguage()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelLanguage (const Function & Func, msgpack::MapDocNode Kern) protected
Definition at line 237 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::mdconst::extract(), llvm::msgpack::Document::getArrayNode(), llvm::msgpack::DocNode::getDocument(), and llvm::msgpack::Document::getNode().
Referenced by emitKernel().
emitPrintf()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitPrintf (const Module & Mod) protected
Definition at line 224 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::cast(), getRootMetadata(), HSAMetadataDoc, and llvm::Mod.
Referenced by begin().
emitTargetID()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitTargetID (const IsaInfo::AMDGPUTargetID & TargetID) protected
Definition at line 218 of file AMDGPUHSAMetadataStreamer.cpp.
References getRootMetadata(), HSAMetadataDoc, and llvm::AMDGPU::IsaInfo::AMDGPUTargetID::toString().
Referenced by begin().
emitTo()
bool llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitTo (AMDGPUTargetStreamer & TargetStreamer) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 556 of file AMDGPUHSAMetadataStreamer.cpp.
References DelayedExprs, llvm::AMDGPUTargetStreamer::EmitHSAMetadata(), and HSAMetadataDoc.
Referenced by ~MetadataStreamerMsgPackV4().
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitVersion () override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5, and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV6.
Definition at line 211 of file AMDGPUHSAMetadataStreamer.cpp.
References getRootMetadata(), HSAMetadataDoc, llvm::Version, llvm::AMDGPU::HSAMD::VersionMajorV4, and llvm::AMDGPU::HSAMD::VersionMinorV4.
Referenced by begin().
end()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::end () override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 570 of file AMDGPUHSAMetadataStreamer.cpp.
References DelayedExprs, dump(), llvm::DumpHSAMetadata, HSAMetadataDoc, llvm::raw_string_ostream::str(), verify, and llvm::VerifyHSAMetadata.
Referenced by ~MetadataStreamerMsgPackV4().
getAccessQualifier()
std::optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getAccessQualifier (StringRef AccQual) const protected
Definition at line 105 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
Referenced by emitKernelArg().
getAddressSpaceQualifier()
std::optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getAddressSpaceQualifier (unsigned AddressSpace) const protected
Definition at line 113 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPUAS::FLAT_ADDRESS, llvm::AMDGPUAS::GLOBAL_ADDRESS, llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::AMDGPUAS::PRIVATE_ADDRESS, and llvm::AMDGPUAS::REGION_ADDRESS.
Referenced by emitKernelArg().
getHSAKernelProps()
msgpack::MapDocNode llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getHSAKernelProps (const MachineFunction & MF, const SIProgramInfo & ProgramInfo, unsigned CodeObjectVersion) const protected
Definition at line 489 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::AMDHSA_COV5, llvm::msgpack::Boolean, DelayedExprs, llvm::SIProgramInfo::DynamicCallStack, F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AMDGPUSubtarget::getKernArgSegmentSize(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::GCNSubtarget::hasMAIInsts(), HSAMetadataDoc, llvm::SIProgramInfo::LDSSize, llvm::SIProgramInfo::NumAccVGPR, llvm::SIProgramInfo::NumSGPR, llvm::SIProgramInfo::NumVGPR, llvm::SIProgramInfo::ScratchSize, llvm::GCNSubtarget::supportsWGP(), llvm::msgpack::UInt, and llvm::SIProgramInfo::WgpMode.
Referenced by emitKernel().
getHSAMetadataRoot()
msgpack::DocNode & llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getHSAMetadataRoot () inline protected
Definition at line 128 of file AMDGPUHSAMetadataStreamer.h.
References HSAMetadataDoc.
getRootMetadata()
msgpack::DocNode & llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getRootMetadata (StringRef Key) inline protected
Definition at line 124 of file AMDGPUHSAMetadataStreamer.h.
References HSAMetadataDoc.
Referenced by begin(), emitKernel(), emitPrintf(), emitTargetID(), emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitVersion(), and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV6::emitVersion().
getTypeName()
std::string llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getTypeName (Type * Ty, bool Signed) const protected
Definition at line 161 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::BitWidth, llvm::cast(), llvm::Type::DoubleTyID, llvm::Type::FixedVectorTyID, llvm::Type::FloatTyID, llvm::getTypeName(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, and Signed.
getValueKind()
StringRef llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getValueKind (Type * Ty, StringRef TypeQual, StringRef BaseTypeName) const protected
Definition at line 134 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringRef::contains(), llvm::StringSwitch< T, R >::Default(), llvm::isa(), and llvm::AMDGPUAS::LOCAL_ADDRESS.
Referenced by emitKernelArg().
getWorkGroupDimensions()
msgpack::ArrayDocNode llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getWorkGroupDimensions (MDNode * Node) const protected
Definition at line 200 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::mdconst::extract(), and HSAMetadataDoc.
Referenced by emitKernelAttrs().
verify()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::verify (StringRef HSAMetadataString) const protected
Definition at line 83 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs(), llvm::msgpack::Document::fromYAML(), llvm::raw_string_ostream::str(), and llvm::msgpack::Document::toYAML().
Member Data Documentation
DelayedExprs
std::unique_ptr<DelayedMCExprs> llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::DelayedExprs protected
Initial value:
=
      std::make_unique<DelayedMCExprs>()
Definition at line 71 of file AMDGPUHSAMetadataStreamer.h.
Referenced by begin(), emitTo(), end(), and getHSAKernelProps().
HSAMetadataDoc
std::unique_ptr<msgpack::Document> llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::HSAMetadataDoc protected
Initial value:
=
      std::make_unique<msgpack::Document>()
Definition at line 74 of file AMDGPUHSAMetadataStreamer.h.
Referenced by begin(), emitKernelArgs(), emitPrintf(), emitTargetID(), emitTo(), emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV6::emitVersion(), end(), getHSAKernelProps(), getHSAMetadataRoot(), getRootMetadata(), and getWorkGroupDimensions().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp