LLVM: llvm::FunctionImporter Class Reference
llvm::FunctionImporter Class Reference
The function importer is automatically importing function from other modules based on the provided summary informations.
#include "llvm/Transforms/IPO/FunctionImport.h"
Classes
struct ImportFailureInfo
Information optionally tracked for candidates the importer decided not to import.
class ImportIDTable
class ImportListsTy
class ImportMapTy
The map maintains the list of imports.
class SortedImportList
Public Types
enum class ImportFailureReason {
None , GlobalVar , NotLive , TooLarge ,
InterposableLinkage , LocalLinkageNotInModule , NotEligible , NoInline
}
The different reasons selectCallee will chose not to import a candidate.
using ImportThresholdsTy
Map of callee GUID considered for import into a given module to a pair consisting of the largest threshold applied when deciding whether to import it and, if we decided to import, a pointer to the summary instance imported.
using ExportSetTy = DenseSet<ValueInfo>
The set contains an entry for every global value that the module exports.
using ModuleLoaderTy
A function of this type is used to load modules referenced by the index.
Public Member Functions
FunctionImporter (const ModuleSummaryIndex &Index, ModuleLoaderTy ModuleLoader, bool ClearDSOLocalOnDeclarations)
Create a Function Importer.
LLVM_ABI Expected< bool > importFunctions (Module &M, const ImportMapTy &ImportList)
Import functions in Module M based on the supplied import list.
Detailed Description
The function importer is automatically importing function from other modules based on the provided summary informations.
Definition at line 31 of file FunctionImport.h.
Member Typedef Documentation
ExportSetTy
using llvm::FunctionImporter::ExportSetTy = DenseSet<ValueInfo>
The set contains an entry for every global value that the module exports.
Depending on the user context, this container is allowed to contain definitions, declarations or a mix of both.
Definition at line 305 of file FunctionImport.h.
ImportThresholdsTy
using llvm::FunctionImporter::ImportThresholdsTy
Initial value:
      DenseMap<GlobalValue::GUID,
               std::tuple<unsigned, const GlobalValueSummary *,
                          std::unique_ptr<ImportFailureInfo>>>
Map of callee GUID considered for import into a given module to a pair consisting of the largest threshold applied when deciding whether to import it and, if we decided to import, a pointer to the summary instance imported.
If we decided not to import, the summary will be nullptr.
Definition at line 84 of file FunctionImport.h.
ModuleLoaderTy
using llvm::FunctionImporter::ModuleLoaderTy
Initial value:
      std::function<Expected<std::unique_ptr<Module>>(StringRef Identifier)>
A function of this type is used to load modules referenced by the index.
Definition at line 308 of file FunctionImport.h.
Member Enumeration Documentation
ImportFailureReason
enum class llvm::FunctionImporter::ImportFailureReason strong
The different reasons selectCallee will chose not to import a candidate.
Enumerator
None
GlobalVar
NotLive
TooLarge
InterposableLinkage
LocalLinkageNotInModule
NotEligible
NoInline
Definition at line 35 of file FunctionImport.h.
Constructor & Destructor Documentation
FunctionImporter()
llvm::FunctionImporter::FunctionImporter (const ModuleSummaryIndex & Index, ModuleLoaderTy ModuleLoader, bool ClearDSOLocalOnDeclarations) inline
Create a Function Importer.
Definition at line 312 of file FunctionImport.h.
References llvm::move().
Member Function Documentation
importFunctions()
Expected< bool > FunctionImporter::importFunctions (Module & M, const ImportMapTy & ImportList)
Import functions in Module M based on the supplied import list.
Definition at line 1869 of file FunctionImport.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains(), llvm::createStringError(), llvm::dbgs(), llvm::GlobalValueSummary::Definition, EnableImportMetadata, llvm::EnableMemProfContextDisambiguation, F, llvm::MDNode::get(), llvm::GlobalValue::getAliaseeObject(), llvm::SetVector< T, Vector, Set, N >::getArrayRef(), llvm::Module::getContext(), llvm::GlobalValue::getGUID(), llvm::FunctionImporter::ImportMapTy::getImportType(), llvm::Module::getModuleIdentifier(), llvm::Value::getName(), llvm::Module::getSourceFileName(), llvm::FunctionImporter::ImportMapTy::getSourceModules(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert_range(), internalizeGVsAfterImport(), llvm::invalid_argument, llvm::isa(), LLVM_DEBUG, llvm::GlobalValue::materialize(), llvm::IRMover::move(), MoveSymbolGUID, PrintImports, llvm::renameModuleForThinLTO(), replaceAliasWithAliasee(), llvm::SetVector< T, Vector, Set, N >::size(), llvm::Expected< T >::takeError(), llvm::toString(), and llvm::UpgradeDebugInfo().
Referenced by crossImportIntoModule(), doImportingForModuleForTest(), and llvm::lto::thinBackend().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/FunctionImport.h
lib/Transforms/IPO/FunctionImport.cpp