LLVM: llvm::MCAssembler Class Reference
llvm::MCAssembler Class Reference
#include "llvm/MC/MCAssembler.h"
Public Types
using SectionListType = SmallVector<MCSection *, 0>
using const_iterator = pointee_iterator<SectionListType::const_iterator>
Public Member Functions
LLVM_ABI MCAssembler (MCContext &Context, std::unique_ptr< MCAsmBackend > Backend, std::unique_ptr< MCCodeEmitter > Emitter, std::unique_ptr< MCObjectWriter > Writer)
Construct a new assembler instance.
MCAssembler (const MCAssembler &)=delete
MCAssembler & operator= (const MCAssembler &)=delete
LLVM_ABI uint64_t computeFragmentSize (const MCFragment &F) const
Compute the effective fragment size.
LLVM_ABI void layoutBundle (MCFragment *Prev, MCFragment *F) const
uint64_t getFragmentOffset (const MCFragment &F) const
LLVM_ABI uint64_t getSectionAddressSize (const MCSection &Sec) const
LLVM_ABI uint64_t getSectionFileSize (const MCSection &Sec) const
LLVM_ABI bool getSymbolOffset (const MCSymbol &S, uint64_t &Val) const
LLVM_ABI uint64_t getSymbolOffset (const MCSymbol &S) const
LLVM_ABI const MCSymbol * getBaseSymbol (const MCSymbol &Symbol) const
LLVM_ABI void writeSectionData (raw_ostream &OS, const MCSection *Section) const
Emit the section contents to OS.
LLVM_ABI bool isThumbFunc (const MCSymbol *Func) const
Check whether a given symbol has been flagged with .thumb_func.
void setIsThumbFunc (const MCSymbol *Func)
Flag a function symbol as the target of a .thumb_func directive.
LLVM_ABI void reset ()
Reuse an assembler instance.
MCContext & getContext () const
MCAsmBackend * getBackendPtr () const
MCCodeEmitter * getEmitterPtr () const
MCAsmBackend & getBackend () const
MCCodeEmitter & getEmitter () const
MCObjectWriter & getWriter () const
MCDwarfLineTableParams getDWARFLinetableParams () const
LLVM_ABI void Finish ()
Finish - Do final processing and write the object to the output stream.
LLVM_ABI void layout ()
bool hasLayout () const
bool hasFinalLayout () const
bool getRelaxAll () const
void setRelaxAll (bool Value)
bool isBundlingEnabled () const
unsigned getBundleAlignSize () const
void setBundleAlignSize (unsigned Size)
const_iterator begin () const
const_iterator end () const
SmallVectorImpl< const MCSymbol * > & getSymbols ()
iterator_range< pointee_iterator< typename SmallVector< const MCSymbol *, 0 >::const_iterator > > symbols () const
LLVM_ABI bool registerSection (MCSection &Section)
LLVM_ABI bool registerSymbol (const MCSymbol &Symbol)
LLVM_ABI void writeFragmentPadding (raw_ostream &OS, const MCEncodedFragment &F, uint64_t FSize) const
Write the necessary bundle padding to OS.
LLVM_ABI void reportError (SMLoc L, const Twine &Msg) const
LLVM_ABI void recordError (SMLoc L, const Twine &Msg) const
LLVM_ABI void flushPendingErrors () const
LLVM_ABI void dump () const
Friends
class MCObjectWriter
Detailed Description
Definition at line 54 of file MCAssembler.h.
Member Typedef Documentation
const_iterator
using llvm::MCAssembler::const_iterator = pointee_iterator<SectionListType::const_iterator>
Definition at line 58 of file MCAssembler.h.
SectionListType
using llvm::MCAssembler::SectionListType = SmallVector<MCSection *, 0>
Definition at line 57 of file MCAssembler.h.
Constructor & Destructor Documentation
MCAssembler() [1/2]
MCAssembler::MCAssembler (MCContext & Context, std::unique_ptr< MCAsmBackend > Backend, std::unique_ptr< MCCodeEmitter > Emitter, std::unique_ptr< MCObjectWriter > Writer)
Construct a new assembler instance.
Definition at line 78 of file MCAssembler.cpp.
References if(), and llvm::move().
Referenced by MCAssembler(), and operator=().
MCAssembler() [2/2]
llvm::MCAssembler::MCAssembler (const MCAssembler &) delete
References MCAssembler().
Member Function Documentation
begin()
const_iterator llvm::MCAssembler::begin () const inline
Definition at line 216 of file MCAssembler.h.
computeFragmentSize()
uint64_t MCAssembler::computeFragmentSize (const MCFragment & F) const
Compute the effective fragment size.
Definition at line 195 of file MCAssembler.cpp.
References assert(), llvm::cast(), llvm::MCExpr::evaluateAsValue(), F, llvm::MCFragment::FT_Align, llvm::MCFragment::FT_BoundaryAlign, llvm::MCFragment::FT_CVDefRange, llvm::MCFragment::FT_CVInlineLines, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Dwarf, llvm::MCFragment::FT_DwarfFrame, llvm::MCFragment::FT_Fill, llvm::MCFragment::FT_LEB, llvm::MCFragment::FT_Nops, llvm::MCFragment::FT_Org, llvm::MCFragment::FT_PseudoProbe, llvm::MCFragment::FT_Relaxable, llvm::MCFragment::FT_SymbolId, llvm::MCAlignFragment::getAlignment(), getBackend(), getBackendPtr(), getFragmentOffset(), llvm::MCOrgFragment::getLoc(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCOrgFragment::getOffset(), llvm::MCFragment::getParent(), getSymbolOffset(), llvm::MCAlignFragment::hasEmitNops(), llvm_unreachable, llvm::Offset, llvm::offsetToAlignment(), recordError(), Size, llvm::MCSection::useCodeAlign(), and llvm::Align::value().
Referenced by getSectionAddressSize(), and layoutBundle().
dump()
LLVM_DUMP_METHOD void MCAssembler::dump () const
Definition at line 1166 of file MCAssembler.cpp.
References llvm::MCSection::dump(), llvm::errs(), F, LLVM_DUMP_METHOD, symbols(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by layout().
end()
const_iterator llvm::MCAssembler::end () const inline
Definition at line 217 of file MCAssembler.h.
Finish()
void MCAssembler::Finish ()
Finish - Do final processing and write the object to the output stream.
Writer is used for custom object writer (as the MCJIT does), if not specified it is automatically created from backend.
Definition at line 840 of file MCAssembler.cpp.
References assert(), getWriter(), layout(), and llvm::MCObjectWriter::writeObject().
Referenced by llvm::MCObjectStreamer::finishImpl().
flushPendingErrors()
void MCAssembler::flushPendingErrors () const
Definition at line 1159 of file MCAssembler.cpp.
References reportError().
Referenced by layout(), and writeSectionData().
getBackend()
MCAsmBackend & llvm::MCAssembler::getBackend () const inline
Definition at line 185 of file MCAssembler.h.
Referenced by computeFragmentSize(), llvm::MCXCOFFStreamer::emitXCOFFRefDirective(), layout(), llvm::LoongArchTargetELFStreamer::LoongArchTargetELFStreamer(), llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer(), and writeFragmentPadding().
getBackendPtr()
MCAsmBackend * llvm::MCAssembler::getBackendPtr () const inline
Definition at line 181 of file MCAssembler.h.
Referenced by computeFragmentSize(), layout(), reset(), writeFragmentPadding(), and writeSectionData().
getBaseSymbol()
const MCSymbol * MCAssembler::getBaseSymbol (const MCSymbol & Symbol) const
Definition at line 426 of file MCAssembler.cpp.
References A(), assert(), llvm::MCExpr::evaluateAsValue(), llvm::MCExpr::getLoc(), llvm::MCSymbol::getName(), llvm::MCSymbol::isCommon(), and reportError().
getBundleAlignSize()
unsigned llvm::MCAssembler::getBundleAlignSize () const inline
Definition at line 208 of file MCAssembler.h.
Referenced by layoutBundle(), setSectionAlignmentForBundling(), and writeFragmentPadding().
getContext()
MCContext & llvm::MCAssembler::getContext () const inline
Definition at line 179 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::emitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitFrame(), llvm::MCELFStreamer::emitIdent(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsTargetELFStreamer::finish(), GetOptionalAbsDifference(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), layout(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), reportError(), and writeSectionData().
getDWARFLinetableParams()
MCDwarfLineTableParams llvm::MCAssembler::getDWARFLinetableParams () const inline
Definition at line 191 of file MCAssembler.h.
getEmitter()
MCCodeEmitter & llvm::MCAssembler::getEmitter () const inline
Definition at line 187 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::emitInstToFragment().
getEmitterPtr()
MCCodeEmitter * llvm::MCAssembler::getEmitterPtr () const inline
Definition at line 183 of file MCAssembler.h.
Referenced by llvm::PPCELFStreamer::emitInstruction(), llvm::PPCXCOFFStreamer::emitInstruction(), reset(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
getFragmentOffset()
uint64_t llvm::MCAssembler::getFragmentOffset (const MCFragment & F) const inline
Definition at line 149 of file MCAssembler.h.
References F.
Referenced by computeFragmentSize(), and getSectionAddressSize().
getRelaxAll()
bool llvm::MCAssembler::getRelaxAll () const inline
Definition at line 203 of file MCAssembler.h.
getSectionAddressSize()
uint64_t MCAssembler::getSectionAddressSize (const MCSection & Sec) const
Definition at line 460 of file MCAssembler.cpp.
References assert(), computeFragmentSize(), llvm::MCSection::curFragList(), F, getFragmentOffset(), and llvm::MCSection::FragList::Tail.
Referenced by getSectionFileSize(), and writeSectionData().
getSectionFileSize()
uint64_t MCAssembler::getSectionFileSize (const MCSection & Sec) const
Definition at line 467 of file MCAssembler.cpp.
References getSectionAddressSize(), and llvm::MCSection::isVirtualSection().
Referenced by writeSectionData().
getSymbolOffset() [1/2]
uint64_t MCAssembler::getSymbolOffset (const MCSymbol & S) const
Definition at line 420 of file MCAssembler.cpp.
References getSymbolOffsetImpl().
getSymbolOffset() [2/2]
bool MCAssembler::getSymbolOffset (const MCSymbol & S, uint64_t & Val) const
Definition at line 416 of file MCAssembler.cpp.
References getSymbolOffsetImpl().
Referenced by computeFragmentSize().
getSymbols()
SmallVectorImpl< const MCSymbol * > & llvm::MCAssembler::getSymbols () inline
Definition at line 219 of file MCAssembler.h.
getWriter()
MCObjectWriter & llvm::MCAssembler::getWriter () const inline
Definition at line 189 of file MCAssembler.h.
References MCObjectWriter.
Referenced by llvm::MCObjectStreamer::emitAddrsig(), llvm::MCObjectStreamer::emitAddrsigSym(), llvm::MCObjectStreamer::emitFileDirective(), Finish(), llvm::MCELFStreamer::getWriter(), llvm::MCGOFFStreamer::getWriter(), llvm::MCWinCOFFStreamer::getWriter(), llvm::MCXCOFFStreamer::getWriter(), and layout().
hasFinalLayout()
bool llvm::MCAssembler::hasFinalLayout () const inline
Definition at line 202 of file MCAssembler.h.
hasLayout()
bool llvm::MCAssembler::hasLayout () const inline
Definition at line 201 of file MCAssembler.h.
isBundlingEnabled()
bool llvm::MCAssembler::isBundlingEnabled () const inline
Definition at line 206 of file MCAssembler.h.
Referenced by canReuseDataFragment(), setSectionAlignmentForBundling(), and writeFragmentPadding().
isThumbFunc()
bool MCAssembler::isThumbFunc (const MCSymbol * Func) const
Check whether a given symbol has been flagged with .thumb_func.
Definition at line 117 of file MCAssembler.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), llvm::MCValue::getAddSym(), and isThumbFunc().
Referenced by isThumbFunc().
layout()
void MCAssembler::layout ()
Definition at line 758 of file MCAssembler.cpp.
References _, assert(), DEBUG_WITH_TYPE, dump(), llvm::dyn_cast(), llvm::errs(), llvm::MCObjectWriter::executePostLayoutBinding(), F, Fixup, flushPendingErrors(), getBackend(), getBackendPtr(), getContext(), llvm::MCFragment::getNext(), getWriter(), llvm::List, llvm::MCSection::setOrdinal(), llvm::MCAsmBackend::shouldInsertFixupForCodeAlign(), and llvm::CallingConv::Tail.
Referenced by Finish().
layoutBundle()
void MCAssembler::layoutBundle (MCFragment * Prev, MCFragment * F) const
Definition at line 325 of file MCAssembler.cpp.
References assert(), llvm::cast(), computeBundlePadding(), computeFragmentSize(), DF, llvm::dyn_cast_or_null(), F, getBundleAlignSize(), llvm::isa(), llvm::report_fatal_error(), and llvm::MCEncodedFragment::setBundlePadding().
operator=()
MCAssembler & llvm::MCAssembler::operator= (const MCAssembler &) delete
References F, LLVM_ABI, and MCAssembler().
recordError()
void MCAssembler::recordError (SMLoc L, const Twine & Msg) const
Definition at line 1155 of file MCAssembler.cpp.
References llvm::Twine::str().
Referenced by computeFragmentSize().
registerSection()
bool MCAssembler::registerSection (MCSection & Section)
Definition at line 108 of file MCAssembler.cpp.
References assert().
registerSymbol()
bool MCAssembler::registerSymbol (const MCSymbol & Symbol)
Definition at line 474 of file MCAssembler.cpp.
References Changed.
Referenced by llvm::MCWinCOFFStreamer::changeSection(), llvm::MipsELFStreamer::createPendingLabelRelocs(), llvm::MCObjectStreamer::emitAssignment(), llvm::MCWinCOFFStreamer::emitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::emitCOFFSymbolIndex(), llvm::MCWinCOFFStreamer::emitCOFFSymbolStorageClass(), llvm::MCWinCOFFStreamer::emitCOFFSymbolType(), llvm::MCELFStreamer::emitCommonSymbol(), llvm::MCWinCOFFStreamer::emitCommonSymbol(), llvm::MCXCOFFStreamer::emitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::RISCVTargetELFStreamer::emitDirectiveVariantCC(), llvm::MCObjectStreamer::emitLabel(), llvm::MipsTargetELFStreamer::emitLabel(), llvm::MCObjectStreamer::emitLabelAtPos(), llvm::MCELFStreamer::emitLocalCommonSymbol(), llvm::MCELFStreamer::emitSymbolAttribute(), llvm::MCWasmStreamer::emitSymbolAttribute(), llvm::MCWinCOFFStreamer::emitSymbolAttribute(), llvm::MCXCOFFStreamer::emitSymbolAttribute(), llvm::MCWinCOFFStreamer::emitWeakReference(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), and llvm::HexagonMCELFStreamer::HexagonMCEmitLocalCommonSymbol().
reportError()
void MCAssembler::reportError (SMLoc L, const Twine & Msg) const
Definition at line 1151 of file MCAssembler.cpp.
References getContext(), and llvm::MCContext::reportError().
Referenced by flushPendingErrors(), getBaseSymbol(), and writeSectionData().
reset()
void MCAssembler::reset ()
Reuse an assembler instance.
Definition at line 90 of file MCAssembler.cpp.
References getBackendPtr(), getEmitterPtr(), llvm::MCAsmBackend::reset(), and llvm::MCCodeEmitter::reset().
setBundleAlignSize()
void llvm::MCAssembler::setBundleAlignSize (unsigned Size) inline
Definition at line 210 of file MCAssembler.h.
References assert(), and Size.
setIsThumbFunc()
void llvm::MCAssembler::setIsThumbFunc (const MCSymbol * Func) inline
Flag a function symbol as the target of a .thumb_func directive.
Definition at line 173 of file MCAssembler.h.
setRelaxAll()
void llvm::MCAssembler::setRelaxAll (bool Value) inline
Definition at line 204 of file MCAssembler.h.
symbols()
iterator_range< pointee_iterator< typename SmallVector< const MCSymbol *, 0 >::const_iterator > > llvm::MCAssembler::symbols () const inline
Definition at line 222 of file MCAssembler.h.
References llvm::make_pointee_range().
Referenced by dump().
writeFragmentPadding()
void MCAssembler::writeFragmentPadding (raw_ostream & OS, const MCEncodedFragment & F, uint64_t FSize) const
Write the necessary bundle padding to OS.
Expects a fragment F containing instructions and its size FSize.
Definition at line 483 of file MCAssembler.cpp.
References llvm::MCEncodedFragment::alignToBundleEnd(), assert(), getBackend(), getBackendPtr(), getBundleAlignSize(), llvm::MCEncodedFragment::getBundlePadding(), llvm::MCEncodedFragment::getSubtargetInfo(), llvm::MCFragment::hasInstructions(), isBundlingEnabled(), and llvm::report_fatal_error().
writeSectionData()
void MCAssembler::writeSectionData (raw_ostream & OS, const MCSection * Section) const
Emit the section contents to OS.
Definition at line 699 of file MCAssembler.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), DF, F, flushPendingErrors(), llvm::MCFragment::FT_Align, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Fill, llvm::MCFragment::FT_Org, getBackendPtr(), getContext(), getSectionAddressSize(), getSectionFileSize(), llvm::MCSection::isVirtualSection(), llvm_unreachable, reportError(), llvm::raw_ostream::tell(), and writeFragment().
Friends And Related Symbol Documentation
MCObjectWriter
friend class MCObjectWriter friend
Definition at line 56 of file MCAssembler.h.
References MCObjectWriter.
Referenced by getWriter(), and MCObjectWriter.
The documentation for this class was generated from the following files:
include/llvm/MC/MCAssembler.h
lib/MC/MCAssembler.cpp