LLVM: llvm::LowerAllowCheckPass Class Reference
llvm::LowerAllowCheckPass Class Reference
#include "llvm/Transforms/Instrumentation/LowerAllowCheckPass.h"
Classes
struct Options
Public Member Functions
LowerAllowCheckPass (LowerAllowCheckPass::Options Opts)
LLVM_ABI PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
LLVM_ABI void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< LowerAllowCheckPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static LLVM_ABI bool IsRequested ()
Static Public Member Functions inherited from llvm::PassInfoMixin< LowerAllowCheckPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 26 of file LowerAllowCheckPass.h.
Constructor & Destructor Documentation
LowerAllowCheckPass()
llvm::LowerAllowCheckPass::LowerAllowCheckPass (LowerAllowCheckPass::Options Opts) inline explicit
Definition at line 33 of file LowerAllowCheckPass.h.
References llvm::move().
Member Function Documentation
IsRequested()
bool LowerAllowCheckPass::IsRequested () static
Definition at line 169 of file LowerAllowCheckPass.cpp.
References HotPercentileCutoff, and RandomRate.
printPipeline()
void LowerAllowCheckPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 174 of file LowerAllowCheckPass.cpp.
References printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses LowerAllowCheckPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 151 of file LowerAllowCheckPass.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::none(), llvm::PreservedAnalyses::preserveSet(), and removeUbsanTraps().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/LowerAllowCheckPass.h
lib/Transforms/Instrumentation/LowerAllowCheckPass.cpp