LLVM: llvm::object::MinidumpFile::ExceptionStreamsIterator Class Reference
llvm::object::MinidumpFile::ExceptionStreamsIterator Class Reference
#include "llvm/Object/Minidump.h"
Public Member Functions
ExceptionStreamsIterator (ArrayRef< minidump::Directory > Streams, const MinidumpFile *File)
bool operator== (const ExceptionStreamsIterator &R) const
bool operator!= (const ExceptionStreamsIterator &R) const
Expected< const minidump::ExceptionStream & > operator* ()
ExceptionStreamsIterator & operator++ ()
Detailed Description
Definition at line 234 of file Minidump.h.
Constructor & Destructor Documentation
ExceptionStreamsIterator()
llvm::object::MinidumpFile::ExceptionStreamsIterator::ExceptionStreamsIterator (ArrayRef< minidump::Directory > Streams, const MinidumpFile * File) inline
Definition at line 236 of file Minidump.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
bool llvm::object::MinidumpFile::ExceptionStreamsIterator::operator!= (const ExceptionStreamsIterator & R) const inline
Definition at line 244 of file Minidump.h.
References ExceptionStreamsIterator().
operator*()
Expected< const minidump::ExceptionStream & > llvm::object::MinidumpFile::ExceptionStreamsIterator::operator* () inline
Definition at line 248 of file Minidump.h.
operator++()
ExceptionStreamsIterator & llvm::object::MinidumpFile::ExceptionStreamsIterator::operator++ () inline
Definition at line 252 of file Minidump.h.
References ExceptionStreamsIterator().
operator==()
bool llvm::object::MinidumpFile::ExceptionStreamsIterator::operator== (const ExceptionStreamsIterator & R) const inline
Definition at line 240 of file Minidump.h.
References ExceptionStreamsIterator().
The documentation for this class was generated from the following file:
include/llvm/Object/Minidump.h