LLVM: llvm::sandboxir::Function Class Reference
llvm::sandboxir::Function Class Reference
#include "llvm/SandboxIR/Function.h"
Public Types
using iterator = mapped_iterator<llvm::Function::iterator, LLVMBBToBB>
Public Types inherited from llvm::sandboxir::GlobalWithNodeAPI< Function, llvm::Function, GlobalObject, llvm::GlobalObject >
using iterator
using reverse_iterator
Public Types inherited from llvm::sandboxir::GlobalObject
using VCallVisibility = llvm::GlobalObject::VCallVisibility
Public Types inherited from llvm::sandboxir::GlobalValue
using LinkageTypes = llvm::GlobalValue::LinkageTypes
using UnnamedAddr = llvm::GlobalValue::UnnamedAddr
using VisibilityTypes = llvm::GlobalValue::VisibilityTypes
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Public Member Functions
Module * getParent ()
Argument * getArg (unsigned Idx) const
size_t arg_size () const
bool arg_empty () const
iterator begin () const
iterator end () const
LLVM_ABI FunctionType * getFunctionType () const
MaybeAlign getAlign () const
Returns the alignment of the given function.
LLVM_ABI void setAlignment (MaybeAlign Align)
Sets the alignment attribute of the Function.
void verify () const final
Should crash if there is something wrong with the instruction.
void dumpNameAndArgs (raw_ostream &OS) const
void dumpOS (raw_ostream &OS) const final
Public Member Functions inherited from llvm::sandboxir::GlobalWithNodeAPI< Function, llvm::Function, GlobalObject, llvm::GlobalObject >
GlobalWithNodeAPI (Value::ClassID ID, llvm::GlobalObject *C, Context &Ctx)
Module * getParent () const
iterator getIterator () const
reverse_iterator getReverseIterator () const
Public Member Functions inherited from llvm::sandboxir::GlobalObject
unsigned getUseOperandNo (const Use &Use) const final
\Returns the operand index of Use.
bool hasSection () const
Check if this global has a custom object file section.
StringRef getSection () const
Get the custom section of this global if it has one.
LLVM_ABI void setSection (StringRef S)
Change the section for this global.
bool hasComdat () const
VCallVisibility getVCallVisibility () const
bool canIncreaseAlignment () const
Returns true if the alignment of the value can be unilaterally increased.
Public Member Functions inherited from llvm::sandboxir::GlobalValue
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
LLVM_ABI void setUnnamedAddr (UnnamedAddr V)
bool hasComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
LLVM_ABI void setVisibility (VisibilityTypes V)
Public Member Functions inherited from llvm::sandboxir::Constant
sandboxir::Context & getParent () const
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::GlobalObject
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::GlobalValue
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
Static Public Member Functions inherited from llvm::sandboxir::Constant
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Friends
class Context
Additional Inherited Members
Protected Member Functions inherited from llvm::sandboxir::GlobalObject
GlobalObject (ClassID ID, llvm::GlobalObject *C, Context &Ctx)
Use getOperandUseInternal (unsigned OpIdx, bool Verify) const final
\Returns the Use for the OpIdx'th operand.
Protected Member Functions inherited from llvm::sandboxir::GlobalValue
GlobalValue (ClassID ID, llvm::GlobalValue *C, Context &Ctx)
Protected Member Functions inherited from llvm::sandboxir::Constant
Constant (llvm::Constant *C, sandboxir::Context &SBCtx)
Constant (ClassID ID, llvm::Constant *C, sandboxir::Context &SBCtx)
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 18 of file Function.h.
Member Typedef Documentation
iterator
using llvm::sandboxir::Function::iterator = mapped_iterator<llvm::Function::iterator, LLVMBBToBB>
Definition at line 51 of file Function.h.
Member Function Documentation
arg_empty()
bool llvm::sandboxir::Function::arg_empty () const inline
Definition at line 49 of file Function.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
arg_size()
size_t llvm::sandboxir::Function::arg_size () const inline
Definition at line 48 of file Function.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
begin()
iterator llvm::sandboxir::Function::begin () const inline
Definition at line 52 of file Function.h.
References begin(), llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
Referenced by begin().
classof()
bool llvm::sandboxir::Function::classof (const sandboxir::Value * From) inline static
For isa/dyn_cast.
Definition at line 35 of file Function.h.
References llvm::sandboxir::Value::getSubclassID().
dumpNameAndArgs()
void llvm::sandboxir::Function::dumpNameAndArgs (raw_ostream & OS) const
Definition at line 28 of file Function.cpp.
References llvm::cast(), F, llvm::interleave(), and llvm::sandboxir::Value::Val.
Referenced by dumpOS().
dumpOS()
void llvm::sandboxir::Function::dumpOS (raw_ostream & OS) const final virtual
Reimplemented from llvm::sandboxir::Constant.
Definition at line 44 of file Function.cpp.
References llvm::cast(), llvm::cast_or_null(), llvm::sandboxir::Value::Ctx, dumpNameAndArgs(), llvm::interleave(), and llvm::sandboxir::Value::Val.
end()
iterator llvm::sandboxir::Function::end () const inline
Definition at line 56 of file Function.h.
References llvm::cast(), llvm::sandboxir::Value::Ctx, end(), and llvm::sandboxir::Value::Val.
Referenced by end().
getAlign()
MaybeAlign llvm::sandboxir::Function::getAlign () const inline
Returns the alignment of the given function.
Definition at line 63 of file Function.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getArg()
Argument * llvm::sandboxir::Function::getArg (unsigned Idx) const inline
Definition at line 43 of file Function.h.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
getFunctionType()
FunctionType * llvm::sandboxir::Function::getFunctionType () const
Definition at line 15 of file Function.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
getParent()
Module * llvm::sandboxir::Function::getParent () inline
Definition at line 39 of file Function.h.
References llvm::cast(), llvm::sandboxir::Value::Ctx, getParent(), and llvm::sandboxir::Value::Val.
Referenced by getParent().
setAlignment()
void llvm::sandboxir::Function::setAlignment (MaybeAlign Align)
Sets the alignment attribute of the Function.
This method will be deprecated as the alignment property should always be defined.
Definition at line 20 of file Function.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
verify()
void llvm::sandboxir::Function::verify () const inline final virtual
Should crash if there is something wrong with the instruction.
Reimplemented from llvm::sandboxir::Constant.
Definition at line 73 of file Function.h.
References assert(), const, llvm::isa(), and llvm::sandboxir::Value::Val.
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 31 of file Function.h.
References Context.
Referenced by Context.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Function.h
lib/SandboxIR/Function.cpp