LLVM: llvm::CfiFunctionIndex Class Reference
llvm::CfiFunctionIndex Class Reference
#include "llvm/IR/ModuleSummaryIndex.h"
Classes
class GUIDIterator
Public Member Functions
CfiFunctionIndex ()=default
template<typename It>
CfiFunctionIndex (It B, It E)
std::vector< StringRef > symbols () const
GUIDIterator guid_begin () const
GUIDIterator guid_end () const
iterator_range< GUIDIterator > guids () const
iterator_range< NestedIterator > forGuid (GlobalValue::GUID GUID) const
template<typename... Args>
void emplace (Args &&...A)
size_t count (StringRef S) const
bool empty () const
Detailed Description
Definition at line 1275 of file ModuleSummaryIndex.h.
Constructor & Destructor Documentation
CfiFunctionIndex() [1/2]
llvm::CfiFunctionIndex::CfiFunctionIndex () default
CfiFunctionIndex() [2/2]
template<typename It> llvm::CfiFunctionIndex::CfiFunctionIndex (It B, It E) inline
Definition at line 1297 of file ModuleSummaryIndex.h.
References B(), E(), and emplace().
Member Function Documentation
count()
size_t llvm::CfiFunctionIndex::count (StringRef S) const inline
Definition at line 1331 of file ModuleSummaryIndex.h.
References llvm::GlobalValue::dropLLVMManglingEscape(), llvm::GlobalValue::getGUIDAssumingExternalLinkage(), and I.
emplace()
template<typename... Args> void llvm::CfiFunctionIndex::emplace (Args &&... A) inline
Definition at line 1324 of file ModuleSummaryIndex.h.
References A(), llvm::GlobalValue::dropLLVMManglingEscape(), and llvm::GlobalValue::getGUIDAssumingExternalLinkage().
Referenced by CfiFunctionIndex().
empty()
bool llvm::CfiFunctionIndex::empty () const inline
Definition at line 1340 of file ModuleSummaryIndex.h.
forGuid()
iterator_range< NestedIterator > llvm::CfiFunctionIndex::forGuid (GlobalValue::GUID GUID) const inline
Definition at line 1317 of file ModuleSummaryIndex.h.
References I, and llvm::make_range().
guid_begin()
GUIDIterator llvm::CfiFunctionIndex::guid_begin () const inline
Definition at line 1311 of file ModuleSummaryIndex.h.
Referenced by guids().
guid_end()
GUIDIterator llvm::CfiFunctionIndex::guid_end () const inline
Definition at line 1312 of file ModuleSummaryIndex.h.
Referenced by guids().
guids()
iterator_range< GUIDIterator > llvm::CfiFunctionIndex::guids () const inline
Definition at line 1313 of file ModuleSummaryIndex.h.
References guid_begin(), guid_end(), and llvm::make_range().
symbols()
std::vector< StringRef > llvm::CfiFunctionIndex::symbols () const inline
Definition at line 1302 of file ModuleSummaryIndex.h.
References llvm::append_range().
Referenced by llvm::yaml::MappingTraits< ModuleSummaryIndex >::mapping().
The documentation for this class was generated from the following file:
include/llvm/IR/ModuleSummaryIndex.h