LLVM: llvm::RopePieceBTreeIterator Class Reference
llvm::RopePieceBTreeIterator Class Reference
RopePieceBTreeIterator - This class provides read-only forward iteration over bytes that are in a RopePieceBTree.
#include "llvm/ADT/RewriteRope.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = const char
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
RopePieceBTreeIterator ()=default
LLVM_ABI RopePieceBTreeIterator (const void *N)
char operator* () const
bool operator== (const RopePieceBTreeIterator &RHS) const
bool operator!= (const RopePieceBTreeIterator &RHS) const
RopePieceBTreeIterator & operator++ ()
RopePieceBTreeIterator operator++ (int)
llvm::StringRef piece () const
LLVM_ABI void MoveToNextPiece ()
Detailed Description
RopePieceBTreeIterator - This class provides read-only forward iteration over bytes that are in a RopePieceBTree.
This first iterates over bytes in a RopePiece, then iterates over RopePiece's in a RopePieceBTreeLeaf, then iterates over RopePieceBTreeLeaf's in a RopePieceBTree.
Definition at line 87 of file RewriteRope.h.
Member Typedef Documentation
difference_type
using llvm::RopePieceBTreeIterator::difference_type = std::ptrdiff_t
Definition at line 101 of file RewriteRope.h.
iterator_category
using llvm::RopePieceBTreeIterator::iterator_category = std::forward_iterator_tag
Definition at line 99 of file RewriteRope.h.
pointer
using llvm::RopePieceBTreeIterator::pointer = value_type *
Definition at line 102 of file RewriteRope.h.
reference
using llvm::RopePieceBTreeIterator::reference = value_type &
Definition at line 103 of file RewriteRope.h.
value_type
using llvm::RopePieceBTreeIterator::value_type = const char
Definition at line 100 of file RewriteRope.h.
Constructor & Destructor Documentation
RopePieceBTreeIterator() [1/2]
llvm::RopePieceBTreeIterator::RopePieceBTreeIterator () default
References LLVM_ABI, and N.
Referenced by operator!=(), operator++(), operator++(), and operator==().
RopePieceBTreeIterator() [2/2]
RopePieceBTreeIterator::RopePieceBTreeIterator (const void * N)
Definition at line 668 of file RewriteRope.cpp.
References llvm::cast(), llvm::dyn_cast(), getCN(), and N.
Member Function Documentation
MoveToNextPiece()
void RopePieceBTreeIterator::MoveToNextPiece ()
Definition at line 690 of file RewriteRope.cpp.
References getCN().
Referenced by operator++().
operator!=()
bool llvm::RopePieceBTreeIterator::operator!= (const RopePieceBTreeIterator & RHS) const inline
Definition at line 113 of file RewriteRope.h.
References operator==(), RHS, and RopePieceBTreeIterator().
operator*()
char llvm::RopePieceBTreeIterator::operator* () const inline
Definition at line 108 of file RewriteRope.h.
operator++() [1/2]
RopePieceBTreeIterator & llvm::RopePieceBTreeIterator::operator++ () inline
Definition at line 117 of file RewriteRope.h.
References MoveToNextPiece(), and RopePieceBTreeIterator().
operator++() [2/2]
RopePieceBTreeIterator llvm::RopePieceBTreeIterator::operator++ (int) inline
Definition at line 125 of file RewriteRope.h.
References RopePieceBTreeIterator().
operator==()
bool llvm::RopePieceBTreeIterator::operator== (const RopePieceBTreeIterator & RHS) const inline
Definition at line 110 of file RewriteRope.h.
References RHS, and RopePieceBTreeIterator().
Referenced by operator!=().
piece()
llvm::StringRef llvm::RopePieceBTreeIterator::piece () const inline
Definition at line 131 of file RewriteRope.h.
The documentation for this class was generated from the following files:
include/llvm/ADT/RewriteRope.h
lib/Support/RewriteRope.cpp