LLVM: llvm::TrackUnresolvedResolver Class Reference
llvm::TrackUnresolvedResolver Class Reference final
(Optionally) delegate resolving to a sub-resolver, and keep track whether there were unresolved references.
#include "llvm/TableGen/Record.h"
Public Member Functions
TrackUnresolvedResolver (Resolver *R=nullptr)
bool foundUnresolved () const
const Init * resolve (const Init *VarName) override
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Public Member Functions inherited from llvm::Resolver
Resolver (const Record *CurRec)
virtual ~Resolver ()=default
const Record * getCurrentRecord () const
virtual bool keepUnsetBits () const
bool isFinal () const
void setFinal (bool Final)
Detailed Description
(Optionally) delegate resolving to a sub-resolver, and keep track whether there were unresolved references.
Definition at line 2285 of file Record.h.
Constructor & Destructor Documentation
TrackUnresolvedResolver()
llvm::TrackUnresolvedResolver::TrackUnresolvedResolver (Resolver * R = nullptr) inline explicit
Definition at line 2290 of file Record.h.
References llvm::Resolver::getCurrentRecord(), and llvm::Resolver::Resolver().
Referenced by resolve().
Member Function Documentation
foundUnresolved()
bool llvm::TrackUnresolvedResolver::foundUnresolved () const inline
Definition at line 2293 of file Record.h.
Referenced by llvm::VarDefInit::resolveReferences().
resolve()
const Init * TrackUnresolvedResolver::resolve (const Init * VarName) override virtual
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Implements llvm::Resolver.
Definition at line 3375 of file Record.cpp.
References I, and TrackUnresolvedResolver().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp