LLVM: llvm::AVRInstrInfo Class Reference
llvm::AVRInstrInfo Class Reference
Utilities related to the AVR instruction set.
#include "Target/AVR/AVRInstrInfo.h"
Public Member Functions
AVRInstrInfo (AVRSubtarget &STI)
const AVRRegisterInfo & getRegisterInfo () const
const MCInstrDesc & getBrCond (AVRCC::CondCodes CC) const
AVRCC::CondCodes getCondFromBranchOpc (unsigned Opc) const
AVRCC::CondCodes getOppositeCondition (AVRCC::CondCodes CC) const
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, Register DestReg, Register SrcReg, bool KillSrc, bool RenamableDest=false, bool RenamableSrc=false) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg, MachineInstr::MIFlag Flags=MachineInstr::NoFlags) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg, MachineInstr::MIFlag Flags=MachineInstr::NoFlags) const override
Register isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
Register isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
MachineBasicBlock * getBranchDestBlock (const MachineInstr &MI) const override
bool isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
void insertIndirectBranch (MachineBasicBlock &MBB, MachineBasicBlock &NewDestBB, MachineBasicBlock &RestoreBB, const DebugLoc &DL, int64_t BrOffset, RegScavenger *RS) const override
Protected Attributes
const AVRSubtarget & STI
Detailed Description
Utilities related to the AVR instruction set.
Definition at line 66 of file AVRInstrInfo.h.
Constructor & Destructor Documentation
AVRInstrInfo()
llvm::AVRInstrInfo::AVRInstrInfo (AVRSubtarget & STI) explicit
Definition at line 32 of file AVRInstrInfo.cpp.
References STI.
Member Function Documentation
analyzeBranch()
bool llvm::AVRInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Definition at line 261 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), Cond, llvm::AVRCC::COND_INVALID, llvm::MachineOperand::CreateImm(), llvm::get(), getBrCond(), getCondFromBranchOpc(), llvm::getImm(), llvm::MCInstrDesc::getOpcode(), getOppositeCondition(), I, MBB, and TBB.
copyPhysReg()
void llvm::AVRInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, Register DestReg, Register SrcReg, bool KillSrc, bool RenamableDest = false, bool RenamableSrc = false) const override
Definition at line 36 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), DL, llvm::get(), llvm::getKillRegState(), llvm_unreachable, MBB, MI, Opc, STI, TRI, and llvm::RegState::Undef.
getBranchDestBlock()
MachineBasicBlock * llvm::AVRInstrInfo::getBranchDestBlock (const MachineInstr & MI) const override
Definition at line 503 of file AVRInstrInfo.cpp.
References llvm_unreachable, and MI.
getBrCond()
const MCInstrDesc & llvm::AVRInstrInfo::getBrCond (AVRCC::CondCodes CC) const
Definition at line 192 of file AVRInstrInfo.cpp.
References llvm::AVRCC::COND_EQ, llvm::AVRCC::COND_GE, llvm::AVRCC::COND_LO, llvm::AVRCC::COND_LT, llvm::AVRCC::COND_MI, llvm::AVRCC::COND_NE, llvm::AVRCC::COND_PL, llvm::AVRCC::COND_SH, llvm::get(), and llvm_unreachable.
Referenced by analyzeBranch(), and insertBranch().
getCondFromBranchOpc()
AVRCC::CondCodes llvm::AVRInstrInfo::getCondFromBranchOpc (unsigned Opc) const
Definition at line 215 of file AVRInstrInfo.cpp.
References llvm::AVRCC::COND_EQ, llvm::AVRCC::COND_GE, llvm::AVRCC::COND_INVALID, llvm::AVRCC::COND_LO, llvm::AVRCC::COND_LT, llvm::AVRCC::COND_MI, llvm::AVRCC::COND_NE, llvm::AVRCC::COND_PL, llvm::AVRCC::COND_SH, and Opc.
Referenced by analyzeBranch(), and removeBranch().
getInstSizeInBytes()
unsigned llvm::AVRInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
Definition at line 476 of file AVRInstrInfo.cpp.
References llvm::get(), llvm::MachineFunction::getTarget(), MI, STI, and TII.
Referenced by insertBranch(), and removeBranch().
getOppositeCondition()
AVRCC::CondCodes llvm::AVRInstrInfo::getOppositeCondition (AVRCC::CondCodes CC) const
Definition at line 238 of file AVRInstrInfo.cpp.
References llvm::AVRCC::COND_EQ, llvm::AVRCC::COND_GE, llvm::AVRCC::COND_LO, llvm::AVRCC::COND_LT, llvm::AVRCC::COND_MI, llvm::AVRCC::COND_NE, llvm::AVRCC::COND_PL, llvm::AVRCC::COND_SH, and llvm_unreachable.
Referenced by analyzeBranch(), and reverseBranchCondition().
getRegisterInfo()
const AVRRegisterInfo & llvm::AVRInstrInfo::getRegisterInfo () const inline
Definition at line 70 of file AVRInstrInfo.h.
insertBranch()
unsigned llvm::AVRInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 394 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), Cond, llvm::Count, DL, llvm::get(), getBrCond(), llvm::getImm(), getInstSizeInBytes(), MBB, MI, and TBB.
insertIndirectBranch()
void llvm::AVRInstrInfo::insertIndirectBranch (MachineBasicBlock & MBB, MachineBasicBlock & NewDestBB, MachineBasicBlock & RestoreBB, const DebugLoc & DL, int64_t BrOffset, RegScavenger * RS) const override
Definition at line 557 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), DL, llvm::get(), MBB, and STI.
isBranchOffsetInRange()
bool llvm::AVRInstrInfo::isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
Definition at line 531 of file AVRInstrInfo.cpp.
References llvm::isIntN(), llvm_unreachable, and STI.
isLoadFromStackSlot()
Register llvm::AVRInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 89 of file AVRInstrInfo.cpp.
References MI.
isStoreToStackSlot()
Register llvm::AVRInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 108 of file AVRInstrInfo.cpp.
References MI.
loadRegFromStackSlot()
void llvm::AVRInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg, MachineInstr::MIFlag Flags = MachineInstr::NoFlags) const override
Definition at line 160 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), llvm::dwarf_linker::DebugLoc, llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm_unreachable, MBB, MI, llvm::MachineMemOperand::MOLoad, and TRI.
removeBranch()
unsigned llvm::AVRInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 435 of file AVRInstrInfo.cpp.
References llvm::AVRCC::COND_INVALID, llvm::Count, getCondFromBranchOpc(), getInstSizeInBytes(), I, and MBB.
reverseBranchCondition()
bool llvm::AVRInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 466 of file AVRInstrInfo.cpp.
References assert(), Cond, and getOppositeCondition().
storeRegToStackSlot()
void llvm::AVRInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg, MachineInstr::MIFlag Flags = MachineInstr::NoFlags) const override
Definition at line 127 of file AVRInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::dwarf_linker::DebugLoc, llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm_unreachable, MBB, MI, llvm::MachineMemOperand::MOStore, llvm::AVRMachineFunctionInfo::setHasSpills(), and TRI.
Member Data Documentation
STI
const AVRSubtarget& llvm::AVRInstrInfo::STI protected
Definition at line 123 of file AVRInstrInfo.h.
Referenced by AVRInstrInfo(), copyPhysReg(), getInstSizeInBytes(), insertIndirectBranch(), and isBranchOffsetInRange().
The documentation for this class was generated from the following files:
lib/Target/AVR/AVRInstrInfo.h
lib/Target/AVR/AVRInstrInfo.cpp