LLVM: llvm::XtensaSubtarget Class Reference
llvm::XtensaSubtarget Class Reference
#include "Target/Xtensa/XtensaSubtarget.h"
Public Member Functions
XtensaSubtarget (const Triple &TT, StringRef CPU, StringRef FS, const TargetMachine &TM)
const Triple & getTargetTriple () const
const TargetFrameLowering * getFrameLowering () const override
const XtensaInstrInfo * getInstrInfo () const override
const XtensaRegisterInfo * getRegisterInfo () const override
const XtensaTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool hasDensity () const
bool hasMAC16 () const
bool hasWindowed () const
bool hasBoolean () const
bool hasLoop () const
bool hasSEXT () const
bool hasCLAMPS () const
bool hasNSA () const
bool hasMINMAX () const
bool hasMul16 () const
bool hasMul32 () const
bool hasMul32High () const
bool hasDiv32 () const
bool hasSingleFloat () const
bool hasRegionProtection () const
bool hasRelocatableVector () const
bool hasMiscSR () const
bool hasExtendedL32R () const
bool hasDataCache () const
bool hasHighPriInterrupts () const
bool hasHighPriInterruptsLevel3 () const
bool hasHighPriInterruptsLevel4 () const
bool hasHighPriInterruptsLevel5 () const
bool hasHighPriInterruptsLevel6 () const
bool hasHighPriInterruptsLevel7 () const
bool hasInterrupt () const
bool hasException () const
bool hasTHREADPTR () const
bool isWindowedABI () const
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Detailed Description
Definition at line 31 of file XtensaSubtarget.h.
Constructor & Destructor Documentation
XtensaSubtarget()
XtensaSubtarget::XtensaSubtarget (const Triple & TT, StringRef CPU, StringRef FS, const TargetMachine & TM)
Definition at line 38 of file XtensaSubtarget.cpp.
Member Function Documentation
getFrameLowering()
const TargetFrameLowering * llvm::XtensaSubtarget::getFrameLowering () const inline override
Definition at line 52 of file XtensaSubtarget.h.
getInstrInfo()
const XtensaInstrInfo * llvm::XtensaSubtarget::getInstrInfo () const inline override
Definition at line 55 of file XtensaSubtarget.h.
getRegisterInfo()
const XtensaRegisterInfo * llvm::XtensaSubtarget::getRegisterInfo () const inline override
Definition at line 56 of file XtensaSubtarget.h.
Referenced by llvm::XtensaTargetLowering::XtensaTargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::XtensaSubtarget::getSelectionDAGInfo () const inline override
Definition at line 63 of file XtensaSubtarget.h.
getTargetLowering()
const XtensaTargetLowering * llvm::XtensaSubtarget::getTargetLowering () const inline override
Definition at line 60 of file XtensaSubtarget.h.
getTargetTriple()
const Triple & llvm::XtensaSubtarget::getTargetTriple () const inline
Definition at line 50 of file XtensaSubtarget.h.
hasBoolean()
bool llvm::XtensaSubtarget::hasBoolean () const inline
Definition at line 70 of file XtensaSubtarget.h.
hasCLAMPS()
bool llvm::XtensaSubtarget::hasCLAMPS () const inline
Definition at line 73 of file XtensaSubtarget.h.
hasDataCache()
bool llvm::XtensaSubtarget::hasDataCache () const inline
Definition at line 85 of file XtensaSubtarget.h.
hasDensity()
bool llvm::XtensaSubtarget::hasDensity () const inline
Definition at line 67 of file XtensaSubtarget.h.
hasDiv32()
bool llvm::XtensaSubtarget::hasDiv32 () const inline
Definition at line 79 of file XtensaSubtarget.h.
hasException()
bool llvm::XtensaSubtarget::hasException () const inline
Definition at line 93 of file XtensaSubtarget.h.
hasExtendedL32R()
bool llvm::XtensaSubtarget::hasExtendedL32R () const inline
Definition at line 84 of file XtensaSubtarget.h.
hasHighPriInterrupts()
bool llvm::XtensaSubtarget::hasHighPriInterrupts () const inline
Definition at line 86 of file XtensaSubtarget.h.
hasHighPriInterruptsLevel3()
bool llvm::XtensaSubtarget::hasHighPriInterruptsLevel3 () const inline
Definition at line 87 of file XtensaSubtarget.h.
hasHighPriInterruptsLevel4()
bool llvm::XtensaSubtarget::hasHighPriInterruptsLevel4 () const inline
Definition at line 88 of file XtensaSubtarget.h.
hasHighPriInterruptsLevel5()
bool llvm::XtensaSubtarget::hasHighPriInterruptsLevel5 () const inline
Definition at line 89 of file XtensaSubtarget.h.
hasHighPriInterruptsLevel6()
bool llvm::XtensaSubtarget::hasHighPriInterruptsLevel6 () const inline
Definition at line 90 of file XtensaSubtarget.h.
hasHighPriInterruptsLevel7()
bool llvm::XtensaSubtarget::hasHighPriInterruptsLevel7 () const inline
Definition at line 91 of file XtensaSubtarget.h.
hasInterrupt()
bool llvm::XtensaSubtarget::hasInterrupt () const inline
Definition at line 92 of file XtensaSubtarget.h.
hasLoop()
bool llvm::XtensaSubtarget::hasLoop () const inline
Definition at line 71 of file XtensaSubtarget.h.
hasMAC16()
bool llvm::XtensaSubtarget::hasMAC16 () const inline
Definition at line 68 of file XtensaSubtarget.h.
hasMINMAX()
bool llvm::XtensaSubtarget::hasMINMAX () const inline
Definition at line 75 of file XtensaSubtarget.h.
hasMiscSR()
bool llvm::XtensaSubtarget::hasMiscSR () const inline
Definition at line 83 of file XtensaSubtarget.h.
hasMul16()
bool llvm::XtensaSubtarget::hasMul16 () const inline
Definition at line 76 of file XtensaSubtarget.h.
hasMul32()
bool llvm::XtensaSubtarget::hasMul32 () const inline
Definition at line 77 of file XtensaSubtarget.h.
hasMul32High()
bool llvm::XtensaSubtarget::hasMul32High () const inline
Definition at line 78 of file XtensaSubtarget.h.
hasNSA()
bool llvm::XtensaSubtarget::hasNSA () const inline
Definition at line 74 of file XtensaSubtarget.h.
hasRegionProtection()
bool llvm::XtensaSubtarget::hasRegionProtection () const inline
Definition at line 81 of file XtensaSubtarget.h.
hasRelocatableVector()
bool llvm::XtensaSubtarget::hasRelocatableVector () const inline
Definition at line 82 of file XtensaSubtarget.h.
hasSEXT()
bool llvm::XtensaSubtarget::hasSEXT () const inline
Definition at line 72 of file XtensaSubtarget.h.
hasSingleFloat()
bool llvm::XtensaSubtarget::hasSingleFloat () const inline
Definition at line 80 of file XtensaSubtarget.h.
hasTHREADPTR()
bool llvm::XtensaSubtarget::hasTHREADPTR () const inline
Definition at line 94 of file XtensaSubtarget.h.
hasWindowed()
bool llvm::XtensaSubtarget::hasWindowed () const inline
Definition at line 69 of file XtensaSubtarget.h.
Referenced by isWindowedABI().
isWindowedABI()
bool llvm::XtensaSubtarget::isWindowedABI () const inline
Definition at line 95 of file XtensaSubtarget.h.
References hasWindowed().
ParseSubtargetFeatures()
void llvm::XtensaSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaSubtarget.h
lib/Target/Xtensa/XtensaSubtarget.cpp