LLVM: llvm::LiveDebugVariables::LDVImpl Class Reference
llvm::LiveDebugVariables::LDVImpl Class Reference
Public Member Functions
LDVImpl (LiveIntervals *LIS)
bool runOnMachineFunction (MachineFunction &mf, bool InstrRef)
void clear ()
Release all memory.
void mapVirtReg (Register VirtReg, UserValue *EC)
Map virtual register to an equivalence class.
void splitPHIRegister (Register OldReg, ArrayRef< Register > NewRegs)
Replace any PHI referring to OldReg with its corresponding NewReg, if present.
void splitRegister (Register OldReg, ArrayRef< Register > NewRegs)
Replace all references to OldReg with NewRegs.
void emitDebugValues (VirtRegMap *VRM)
Recreate DBG_VALUE instruction from data structures.
void print (raw_ostream &)
Detailed Description
Definition at line 545 of file LiveDebugVariables.cpp.
Constructor & Destructor Documentation
LDVImpl()
llvm::LiveDebugVariables::LDVImpl::LDVImpl (LiveIntervals * LIS) inline
Definition at line 649 of file LiveDebugVariables.cpp.
Member Function Documentation
clear()
void llvm::LiveDebugVariables::LDVImpl::clear () inline
Release all memory.
Definition at line 654 of file LiveDebugVariables.cpp.
References assert().
Referenced by runOnMachineFunction().
emitDebugValues()
void LiveDebugVariables::LDVImpl::emitDebugValues (VirtRegMap * VRM)
Recreate DBG_VALUE instruction from data structures.
Definition at line 1857 of file LiveDebugVariables.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::dbgs(), findInsertLocation(), llvm::VirtRegMap::getPhys(), llvm::VirtRegMap::getStackSlot(), llvm::VirtRegMap::hasPhys(), llvm::VirtRegMap::isAssignedReg(), LLVM_DEBUG, MBB, MI, MRI, llvm::VirtRegMap::NO_STACK_SLOT, llvm::printReg(), llvm::skipDebugInstructionsForward(), SubReg, llvm::Success, and TII.
mapVirtReg()
void LiveDebugVariables::LDVImpl::mapVirtReg (Register VirtReg, UserValue * EC)
Map virtual register to an equivalence class.
Definition at line 797 of file LiveDebugVariables.cpp.
References assert(), and llvm::Register::isVirtual().
Referenced by splitRegister().
print()
void LiveDebugVariables::LDVImpl::print (raw_ostream & OS)
Definition at line 767 of file LiveDebugVariables.cpp.
Referenced by llvm::LiveDebugVariablesPrinterPass::run().
runOnMachineFunction()
bool LiveDebugVariables::LDVImpl::runOnMachineFunction (MachineFunction & mf, bool InstrRef)
Definition at line 1274 of file LiveDebugVariables.cpp.
References Changed, clear(), llvm::dbgs(), llvm::SlotIndexes::getMBBStartIdx(), llvm::MachineFunction::getName(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, MBB, llvm::LiveDebugVariables::print(), and SubReg.
splitPHIRegister()
void LiveDebugVariables::LDVImpl::splitPHIRegister (Register OldReg, ArrayRef< Register > NewRegs)
Replace any PHI referring to OldReg with its corresponding NewReg, if present.
Definition at line 1493 of file LiveDebugVariables.cpp.
References assert(), llvm::LiveRange::end(), and llvm::LiveRange::find().
Referenced by splitRegister().
splitRegister()
void LiveDebugVariables::LDVImpl::splitRegister (Register OldReg, ArrayRef< Register > NewRegs)
Replace all references to OldReg with NewRegs.
Definition at line 1532 of file LiveDebugVariables.cpp.
References mapVirtReg(), and splitPHIRegister().
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugVariables.cpp