LLVM: llvm::ProfOStream Class Reference
llvm::ProfOStream Class Reference
#include "llvm/ProfileData/InstrProf.h"
Public Member Functions
LLVM_ABI ProfOStream (raw_fd_ostream &FD)
LLVM_ABI ProfOStream (raw_string_ostream &STR)
LLVM_ABI uint64_t tell () const
LLVM_ABI void write (uint64_t V)
LLVM_ABI void write32 (uint32_t V)
LLVM_ABI void writeByte (uint8_t V)
LLVM_ABI void patch (ArrayRef< PatchItem > P)
Public Attributes
bool IsFDOStream
raw_ostream & OS
support::endian::Writer LE
Detailed Description
Definition at line 70 of file InstrProf.h.
Constructor & Destructor Documentation
ProfOStream() [1/2]
llvm::ProfOStream::ProfOStream (raw_fd_ostream & FD)
Definition at line 263 of file InstrProf.cpp.
References IsFDOStream, LE, llvm::little, and OS.
ProfOStream() [2/2]
llvm::ProfOStream::ProfOStream (raw_string_ostream & STR)
Definition at line 266 of file InstrProf.cpp.
References IsFDOStream, LE, llvm::little, and OS.
Member Function Documentation
patch()
void llvm::ProfOStream::patch (ArrayRef< PatchItem > P)
Definition at line 274 of file InstrProf.cpp.
References llvm::support::endian::byte_swap(), llvm::Data, I, IsFDOStream, OS, P, llvm::raw_fd_ostream::seek(), llvm::raw_string_ostream::str(), llvm::raw_ostream::tell(), and write().
Referenced by llvm::writeMemProfRadixTreeBased(), and llvm::writeMemProfV2().
tell()
uint64_t llvm::ProfOStream::tell () const nodiscard
Definition at line 269 of file InstrProf.cpp.
References OS.
Referenced by llvm::memprof::MemProfSummary::write(), llvm::writeMemProfRadixTreeBased(), and llvm::writeMemProfV2().
write()
void llvm::ProfOStream::write (uint64_t V)
Definition at line 270 of file InstrProf.cpp.
References LE.
Referenced by patch(), llvm::memprof::DataAccessProfData::serialize(), llvm::memprof::MemProfSummary::write(), llvm::writeMemProfRadixTreeBased(), llvm::writeMemProfSchema(), and llvm::writeMemProfV2().
write32()
void llvm::ProfOStream::write32 (uint32_t V)
Definition at line 271 of file InstrProf.cpp.
References LE.
Referenced by llvm::memprof::DataAccessProfData::serialize(), llvm::memprof::MemProfSummary::write(), and llvm::writeMemProfCallStackArray().
writeByte()
void llvm::ProfOStream::writeByte (uint8_t V)
Definition at line 272 of file InstrProf.cpp.
References LE.
Referenced by llvm::memprof::DataAccessProfData::serialize().
Member Data Documentation
IsFDOStream
bool llvm::ProfOStream::IsFDOStream
Definition at line 87 of file InstrProf.h.
Referenced by patch(), ProfOStream(), and ProfOStream().
LE
support::endian::Writer llvm::ProfOStream::LE
Definition at line 89 of file InstrProf.h.
Referenced by ProfOStream(), ProfOStream(), write(), write32(), and writeByte().
OS
raw_ostream& llvm::ProfOStream::OS
Definition at line 88 of file InstrProf.h.
Referenced by patch(), ProfOStream(), ProfOStream(), tell(), llvm::writeMemProfCallStacks(), llvm::writeMemProfFrameArray(), llvm::writeMemProfFrames(), and llvm::writeMemProfRecords().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProf.h
lib/ProfileData/InstrProf.cpp