LLVM: llvm::MCDwarfLineEntry Class Reference
llvm::MCDwarfLineEntry Class Reference
Instances of this class represent the line information for the dwarf line table entries.
#include "llvm/MC/MCDwarf.h"
Public Member Functions
MCDwarfLineEntry (MCSymbol *label, const MCDwarfLoc loc, MCSymbol *lineStreamLabel=nullptr, SMLoc streamLabelDefLoc={})
MCSymbol * getLabel () const
void setEndLabel (MCSymbol *EndLabel)
Public Member Functions inherited from llvm::MCDwarfLoc
unsigned getFileNum () const
Get the FileNum of this MCDwarfLoc.
unsigned getLine () const
Get the Line of this MCDwarfLoc.
unsigned getColumn () const
Get the Column of this MCDwarfLoc.
unsigned getFlags () const
Get the Flags of this MCDwarfLoc.
unsigned getIsa () const
Get the Isa of this MCDwarfLoc.
unsigned getDiscriminator () const
Get the Discriminator of this MCDwarfLoc.
void setFileNum (unsigned fileNum)
Set the FileNum of this MCDwarfLoc.
void setLine (unsigned line)
Set the Line of this MCDwarfLoc.
void setColumn (unsigned column)
Set the Column of this MCDwarfLoc.
void setFlags (unsigned flags)
Set the Flags of this MCDwarfLoc.
void setIsa (unsigned isa)
Set the Isa of this MCDwarfLoc.
void setDiscriminator (unsigned discriminator)
Set the Discriminator of this MCDwarfLoc.
Static Public Member Functions
static LLVM_ABI void make (MCStreamer *MCOS, MCSection *Section)
Public Attributes
MCSymbol * LineStreamLabel
SMLoc StreamLabelDefLoc
bool IsEndEntry = false
Detailed Description
Instances of this class represent the line information for the dwarf line table entries.
Which is created after a machine instruction is assembled and uses an address from a temporary label created at the current address in the current section and the info from the last .loc directive seen as stored in the context.
Definition at line 189 of file MCDwarf.h.
Constructor & Destructor Documentation
MCDwarfLineEntry()
llvm::MCDwarfLineEntry::MCDwarfLineEntry (MCSymbol * label, const MCDwarfLoc loc, MCSymbol * lineStreamLabel = nullptr, SMLoc streamLabelDefLoc = {}) inline
Definition at line 198 of file MCDwarf.h.
Referenced by make().
Member Function Documentation
getLabel()
MCSymbol * llvm::MCDwarfLineEntry::getLabel () const inline
Definition at line 204 of file MCDwarf.h.
make()
void MCDwarfLineEntry::make (MCStreamer * MCOS, MCSection * Section) static
Definition at line 91 of file MCDwarf.cpp.
References llvm::MCLineSection::addLineEntry(), llvm::MCContext::clearDwarfLocSeen(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::getContext(), llvm::MCContext::getCurrentDwarfLoc(), llvm::MCContext::getDwarfCompileUnitID(), llvm::MCContext::getDwarfLocSeen(), llvm::MCContext::getMCDwarfLineTable(), llvm::MCDwarfLineTable::getMCLineSections(), and MCDwarfLineEntry().
Referenced by llvm::DwarfDebug::beginCodeAlignment(), llvm::MCObjectStreamer::emitBytes(), llvm::MCObjectStreamer::emitDwarfLocDirective(), and llvm::MCObjectStreamer::emitValueImpl().
setEndLabel()
void llvm::MCDwarfLineEntry::setEndLabel (MCSymbol * EndLabel) inline
Definition at line 219 of file MCDwarf.h.
References assert(), IsEndEntry, and LineStreamLabel.
Referenced by llvm::MCLineSection::addEndEntry().
Member Data Documentation
IsEndEntry
bool llvm::MCDwarfLineEntry::IsEndEntry = false
Definition at line 216 of file MCDwarf.h.
Referenced by setEndLabel().
LineStreamLabel
MCSymbol* llvm::MCDwarfLineEntry::LineStreamLabel
Definition at line 209 of file MCDwarf.h.
Referenced by llvm::MCLineSection::addEndEntry(), and setEndLabel().
StreamLabelDefLoc
SMLoc llvm::MCDwarfLineEntry::StreamLabelDefLoc
Definition at line 213 of file MCDwarf.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp