LLVM: llvm::AAEvaluator Class Reference
llvm::AAEvaluator Class Reference
#include "llvm/Analysis/AliasAnalysisEvaluator.h"
Public Member Functions
AAEvaluator ()=default
AAEvaluator (AAEvaluator &&Arg)
LLVM_ABI ~AAEvaluator ()
LLVM_ABI PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Run the pass over the function.
Public Member Functions inherited from llvm::PassInfoMixin< AAEvaluator >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AAEvaluator >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 34 of file AliasAnalysisEvaluator.h.
Constructor & Destructor Documentation
AAEvaluator() [1/2]
llvm::AAEvaluator::AAEvaluator () default
Referenced by AAEvaluator().
AAEvaluator() [2/2]
llvm::AAEvaluator::AAEvaluator (AAEvaluator && Arg) inline
Definition at line 42 of file AliasAnalysisEvaluator.h.
References AAEvaluator().
~AAEvaluator()
AAEvaluator::~AAEvaluator ()
Definition at line 273 of file AliasAnalysisEvaluator.cpp.
References llvm::errs(), and PrintPercent().
Member Function Documentation
run()
PreservedAnalyses AAEvaluator::run (Function & F, FunctionAnalysisManager & AM)
Run the pass over the function.
Definition at line 96 of file AliasAnalysisEvaluator.cpp.
References llvm::PreservedAnalyses::all(), F, and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
The documentation for this class was generated from the following files:
include/llvm/Analysis/AliasAnalysisEvaluator.h
lib/Analysis/AliasAnalysisEvaluator.cpp