LLVM: llvm::sandboxir::SeedCollector Class Reference
llvm::sandboxir::SeedCollector Class Reference
#include "llvm/Transforms/Vectorize/SandboxVectorizer/SeedCollector.h"
Public Member Functions
LLVM_ABI SeedCollector (BasicBlock *BB, ScalarEvolution &SE, bool CollectStores, bool CollectLoads)
LLVM_ABI ~SeedCollector ()
iterator_range< SeedContainer::iterator > getStoreSeeds ()
iterator_range< SeedContainer::iterator > getLoadSeeds ()
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
Definition at line 298 of file SeedCollector.h.
Constructor & Destructor Documentation
SeedCollector()
llvm::sandboxir::SeedCollector::SeedCollector (BasicBlock * BB, ScalarEvolution & SE, bool CollectStores, bool CollectLoads)
Definition at line 160 of file SeedCollector.cpp.
References llvm::sandboxir::BasicBlock(), llvm::dyn_cast(), llvm::sandboxir::getContext(), I, llvm::sandboxir::isValidMemSeed(), and llvm::sandboxir::SeedGroupsLimit.
~SeedCollector()
llvm::sandboxir::SeedCollector::~SeedCollector ()
Definition at line 188 of file SeedCollector.cpp.
Member Function Documentation
dump()
void llvm::sandboxir::SeedCollector::dump () const
Definition at line 200 of file SeedCollector.cpp.
References llvm::dbgs(), and print().
getLoadSeeds()
iterator_range< SeedContainer::iterator > llvm::sandboxir::SeedCollector::getLoadSeeds () inline
Definition at line 317 of file SeedCollector.h.
getStoreSeeds()
iterator_range< SeedContainer::iterator > llvm::sandboxir::SeedCollector::getStoreSeeds () inline
Definition at line 314 of file SeedCollector.h.
print()
void llvm::sandboxir::SeedCollector::print (raw_ostream & OS) const
Definition at line 193 of file SeedCollector.cpp.
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/SeedCollector.h
lib/Transforms/Vectorize/SandboxVectorizer/SeedCollector.cpp