LLVM: llvm::SPIRVSubtarget Class Reference
llvm::SPIRVSubtarget Class Reference
#include "Target/SPIRV/SPIRVSubtarget.h"
Public Types
enum SPIRVEnvType { Kernel , Shader , Unknown }
Public Member Functions
SPIRVSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const SPIRVTargetMachine &TM)
SPIRVSubtarget & initSubtargetDependencies (StringRef CPU, StringRef FS)
void initAvailableExtensions (const std::set< SPIRV::Extension::Extension > &AllowedExtIds)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
unsigned getPointerSize () const
unsigned getBound () const
bool canDirectlyComparePointers () const
void setEnv (SPIRVEnvType E)
SPIRVEnvType getEnv () const
bool isKernel () const
bool isShader () const
bool isLogicalSPIRV () const
bool isPhysicalSPIRV () const
const std::string & getTargetTripleAsStr () const
VersionTuple getSPIRVVersion () const
bool isAtLeastSPIRVVer (VersionTuple VerToCompareTo) const
bool isAtLeastOpenCLVer (VersionTuple VerToCompareTo) const
bool hasOpenCLFullProfile () const
bool hasOpenCLImageSupport () const
const SmallSet< SPIRV::Extension::Extension, 4 > & getAllAvailableExtensions () const
bool canUseExtension (SPIRV::Extension::Extension E) const
bool canUseExtInstSet (SPIRV::InstructionSet::InstructionSet E) const
SPIRV::InstructionSet::InstructionSet getPreferredInstructionSet () const
SPIRVGlobalRegistry * getSPIRVGlobalRegistry () const
const CallLowering * getCallLowering () const override
const RegisterBankInfo * getRegBankInfo () const override
const LegalizerInfo * getLegalizerInfo () const override
InstructionSelector * getInstructionSelector () const override
const InlineAsmLowering * getInlineAsmLowering () const override
const SPIRVInstrInfo * getInstrInfo () const override
const SPIRVFrameLowering * getFrameLowering () const override
const SPIRVTargetLowering * getTargetLowering () const override
const SPIRVRegisterInfo * getRegisterInfo () const override
Static Public Member Functions
static bool classof (const TargetSubtargetInfo *ST)
static void addExtensionsToClOpt (const std::set< SPIRV::Extension::Extension > &AllowList)
Static Public Attributes
static constexpr unsigned MaxLegalAddressSpace = 6
Detailed Description
Definition at line 38 of file SPIRVSubtarget.h.
Member Enumeration Documentation
SPIRVEnvType
enum llvm::SPIRVSubtarget::SPIRVEnvType
Enumerator
Kernel
Shader
Unknown
Definition at line 41 of file SPIRVSubtarget.h.
Constructor & Destructor Documentation
SPIRVSubtarget()
SPIRVSubtarget::SPIRVSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const SPIRVTargetMachine & TM)
Definition at line 52 of file SPIRVSubtarget.cpp.
References llvm::createSPIRVInstructionSelector(), Extensions, if(), initAvailableExtensions(), initSubtargetDependencies(), Kernel, llvm::Triple::OpenCL, Shader, Unknown, and llvm::Triple::Vulkan.
Referenced by initSubtargetDependencies().
Member Function Documentation
addExtensionsToClOpt()
void SPIRVSubtarget::addExtensionsToClOpt (const std::set< SPIRV::Extension::Extension > & AllowList) static
Definition at line 42 of file SPIRVSubtarget.cpp.
References Extensions.
canDirectlyComparePointers()
bool SPIRVSubtarget::canDirectlyComparePointers () const
Definition at line 140 of file SPIRVSubtarget.cpp.
References isAtLeastVer(), and SPVTranslatorCompat.
canUseExtension()
bool SPIRVSubtarget::canUseExtension (SPIRV::Extension::Extension E) const
Definition at line 111 of file SPIRVSubtarget.cpp.
Referenced by llvm::addressSpaceToStorageClass().
canUseExtInstSet()
bool SPIRVSubtarget::canUseExtInstSet (SPIRV::InstructionSet::InstructionSet E) const
Definition at line 115 of file SPIRVSubtarget.cpp.
classof()
bool llvm::SPIRVSubtarget::classof (const TargetSubtargetInfo * ST) inline static
Definition at line 147 of file SPIRVSubtarget.h.
getAllAvailableExtensions()
const SmallSet< SPIRV::Extension::Extension, 4 > & llvm::SPIRVSubtarget::getAllAvailableExtensions () const inline
Definition at line 112 of file SPIRVSubtarget.h.
getBound()
unsigned llvm::SPIRVSubtarget::getBound () const inline
Definition at line 84 of file SPIRVSubtarget.h.
getCallLowering()
const CallLowering * llvm::SPIRVSubtarget::getCallLowering () const inline override
Definition at line 121 of file SPIRVSubtarget.h.
getEnv()
SPIRVEnvType llvm::SPIRVSubtarget::getEnv () const inline
Definition at line 94 of file SPIRVSubtarget.h.
Referenced by getExecutionModel(), isKernel(), and isShader().
getFrameLowering()
const SPIRVFrameLowering * llvm::SPIRVSubtarget::getFrameLowering () const inline override
Definition at line 137 of file SPIRVSubtarget.h.
getInlineAsmLowering()
const InlineAsmLowering * llvm::SPIRVSubtarget::getInlineAsmLowering () const inline override
Definition at line 133 of file SPIRVSubtarget.h.
getInstrInfo()
const SPIRVInstrInfo * llvm::SPIRVSubtarget::getInstrInfo () const inline override
Definition at line 136 of file SPIRVSubtarget.h.
Referenced by addConstantsToTrack(), and doInsertBitcast().
getInstructionSelector()
InstructionSelector * llvm::SPIRVSubtarget::getInstructionSelector () const inline override
Definition at line 130 of file SPIRVSubtarget.h.
getLegalizerInfo()
const LegalizerInfo * llvm::SPIRVSubtarget::getLegalizerInfo () const inline override
Definition at line 127 of file SPIRVSubtarget.h.
getPointerSize()
unsigned llvm::SPIRVSubtarget::getPointerSize () const inline
Definition at line 83 of file SPIRVSubtarget.h.
getPreferredInstructionSet()
SPIRV::InstructionSet::InstructionSet SPIRVSubtarget::getPreferredInstructionSet () const
Definition at line 121 of file SPIRVSubtarget.cpp.
References isShader().
getRegBankInfo()
const RegisterBankInfo * llvm::SPIRVSubtarget::getRegBankInfo () const inline override
Definition at line 124 of file SPIRVSubtarget.h.
Referenced by doInsertBitcast().
getRegisterInfo()
const SPIRVRegisterInfo * llvm::SPIRVSubtarget::getRegisterInfo () const inline override
Definition at line 143 of file SPIRVSubtarget.h.
Referenced by doInsertBitcast().
getSPIRVGlobalRegistry()
SPIRVGlobalRegistry * llvm::SPIRVSubtarget::getSPIRVGlobalRegistry () const inline
Definition at line 119 of file SPIRVSubtarget.h.
Referenced by llvm::SPIRVLegalizerInfo::SPIRVLegalizerInfo().
getSPIRVVersion()
VersionTuple llvm::SPIRVSubtarget::getSPIRVVersion () const inline
Definition at line 105 of file SPIRVSubtarget.h.
getTargetLowering()
const SPIRVTargetLowering * llvm::SPIRVSubtarget::getTargetLowering () const inline override
Definition at line 140 of file SPIRVSubtarget.h.
getTargetTripleAsStr()
const std::string & llvm::SPIRVSubtarget::getTargetTripleAsStr () const inline
Definition at line 104 of file SPIRVSubtarget.h.
hasOpenCLFullProfile()
bool llvm::SPIRVSubtarget::hasOpenCLFullProfile () const inline
Definition at line 109 of file SPIRVSubtarget.h.
hasOpenCLImageSupport()
bool llvm::SPIRVSubtarget::hasOpenCLImageSupport () const inline
Definition at line 110 of file SPIRVSubtarget.h.
initAvailableExtensions()
void SPIRVSubtarget::initAvailableExtensions (const std::set< SPIRV::Extension::Extension > & AllowedExtIds)
Definition at line 166 of file SPIRVSubtarget.cpp.
Referenced by SPIRVSubtarget(), and llvm::SPIRVTranslate().
initSubtargetDependencies()
SPIRVSubtarget & SPIRVSubtarget::initSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 105 of file SPIRVSubtarget.cpp.
References ParseSubtargetFeatures(), and SPIRVSubtarget().
Referenced by SPIRVSubtarget().
isAtLeastOpenCLVer()
bool SPIRVSubtarget::isAtLeastOpenCLVer (VersionTuple VerToCompareTo) const
Definition at line 132 of file SPIRVSubtarget.cpp.
References isAtLeastVer(), and isShader().
isAtLeastSPIRVVer()
bool SPIRVSubtarget::isAtLeastSPIRVVer (VersionTuple VerToCompareTo) const
Definition at line 128 of file SPIRVSubtarget.cpp.
References isAtLeastVer().
isKernel()
bool llvm::SPIRVSubtarget::isKernel () const inline
Definition at line 95 of file SPIRVSubtarget.h.
References getEnv(), and Kernel.
Referenced by getExecutionModel().
isLogicalSPIRV()
bool llvm::SPIRVSubtarget::isLogicalSPIRV () const inline
Definition at line 97 of file SPIRVSubtarget.h.
References llvm::Triple::spirv.
isPhysicalSPIRV()
bool llvm::SPIRVSubtarget::isPhysicalSPIRV () const inline
Definition at line 100 of file SPIRVSubtarget.h.
References llvm::Triple::spirv32, and llvm::Triple::spirv64.
isShader()
bool llvm::SPIRVSubtarget::isShader () const inline
Definition at line 96 of file SPIRVSubtarget.h.
References getEnv(), and Shader.
Referenced by getExecutionModel(), getPreferredInstructionSet(), and isAtLeastOpenCLVer().
ParseSubtargetFeatures()
void llvm::SPIRVSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Referenced by initSubtargetDependencies().
setEnv()
void llvm::SPIRVSubtarget::setEnv (SPIRVEnvType E) inline
Definition at line 86 of file SPIRVSubtarget.h.
References E(), llvm::report_fatal_error(), and Unknown.
Referenced by getExecutionModel().
Member Data Documentation
MaxLegalAddressSpace
unsigned llvm::SPIRVSubtarget::MaxLegalAddressSpace = 6 static constexpr
Definition at line 151 of file SPIRVSubtarget.h.
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVSubtarget.h
lib/Target/SPIRV/SPIRVSubtarget.cpp