LLVM: llvm::ir2vec::Embedder Class Reference
llvm::ir2vec::Embedder Class Reference abstract
Embedder provides the interface to generate embeddings (vector representations) for instructions, basic blocks, and functions.
#include "llvm/Analysis/IR2Vec.h"
Public Member Functions
virtual ~Embedder ()=default
LLVM_ABI const InstEmbeddingsMap & getInstVecMap () const
Returns a map containing instructions and the corresponding embeddings for the function F if it has been computed.
LLVM_ABI const BBEmbeddingsMap & getBBVecMap () const
Returns a map containing basic block and the corresponding embeddings for the function F if it has been computed.
LLVM_ABI const Embedding & getBBVector (const BasicBlock &BB) const
Returns the embedding for a given basic block in the function F if it has been computed.
LLVM_ABI const Embedding & getFunctionVector () const
Computes and returns the embedding for the current function.
Static Public Member Functions
static LLVM_ABI std::unique_ptr< Embedder > create (IR2VecKind Mode, const Function &F, const Vocabulary &Vocab)
Factory method to create an Embedder object.
Protected Member Functions
LLVM_ABI Embedder (const Function &F, const Vocabulary &Vocab)
virtual void computeEmbeddings () const =0
Helper function to compute embeddings.
virtual void computeEmbeddings (const BasicBlock &BB) const =0
Helper function to compute the embedding for a given basic block.
Protected Attributes
const Function & F
const Vocabulary & Vocab
const unsigned Dimension
Dimension of the vector representation; captured from the input vocabulary.
const float OpcWeight
Weights for different entities (like opcode, arguments, types) in the IR instructions to generate the vector representation.
const float TypeWeight
const float ArgWeight
Embedding FuncVector
BBEmbeddingsMap BBVecMap
InstEmbeddingsMap InstVecMap
Detailed Description
Embedder provides the interface to generate embeddings (vector representations) for instructions, basic blocks, and functions.
The vector representations are generated using IR2Vec algorithms.
The Embedder class is an abstract class and it is intended to be subclassed for different IR2Vec algorithms like Symbolic and Flow-aware.
Definition at line 230 of file IR2Vec.h.
Constructor & Destructor Documentation
Embedder()
Embedder::Embedder (const Function & F, const Vocabulary & Vocab) protected
Definition at line 142 of file IR2Vec.cpp.
References ArgWeight, Dimension, F, OpcWeight, TypeWeight, and Vocab.
Referenced by llvm::ir2vec::SymbolicEmbedder::SymbolicEmbedder().
~Embedder()
virtual llvm::ir2vec::Embedder::~Embedder () virtual default
References F, LLVM_ABI, Mode, and Vocab.
Member Function Documentation
computeEmbeddings() [1/2]
virtual void llvm::ir2vec::Embedder::computeEmbeddings () const protected pure virtual
Helper function to compute embeddings.
It generates embeddings for all the instructions and basic blocks in the function F. Logic of computing the embeddings is specific to the kind of embeddings being computed.
Referenced by getBBVecMap(), getBBVector(), getFunctionVector(), and getInstVecMap().
computeEmbeddings() [2/2]
virtual void llvm::ir2vec::Embedder::computeEmbeddings (const BasicBlock & BB) const protected pure virtual
Helper function to compute the embedding for a given basic block.
Specific to the kind of embeddings being computed.
create()
std::unique_ptr< Embedder > Embedder::create (IR2VecKind Mode, const Function & F, const Vocabulary & Vocab) static
Factory method to create an Embedder object.
Definition at line 147 of file IR2Vec.cpp.
References F, llvm::Symbolic, and Vocab.
Referenced by llvm::IR2VecPrinterPass::run().
getBBVecMap()
const BBEmbeddingsMap & Embedder::getBBVecMap () const
Returns a map containing basic block and the corresponding embeddings for the function F if it has been computed.
If not, it computes the embeddings for the function and returns the map.
Definition at line 162 of file IR2Vec.cpp.
References BBVecMap, and computeEmbeddings().
getBBVector()
const Embedding & Embedder::getBBVector (const BasicBlock & BB) const
Returns the embedding for a given basic block in the function F if it has been computed.
If not, it computes the embedding for the basic block and returns it.
Definition at line 168 of file IR2Vec.cpp.
References BBVecMap, and computeEmbeddings().
getFunctionVector()
const Embedding & Embedder::getFunctionVector () const
Computes and returns the embedding for the current function.
Definition at line 176 of file IR2Vec.cpp.
References computeEmbeddings(), and FuncVector.
getInstVecMap()
const InstEmbeddingsMap & Embedder::getInstVecMap () const
Returns a map containing instructions and the corresponding embeddings for the function F if it has been computed.
If not, it computes the embeddings for the function and returns the map.
Definition at line 156 of file IR2Vec.cpp.
References computeEmbeddings(), and InstVecMap.
Member Data Documentation
ArgWeight
const float llvm::ir2vec::Embedder::ArgWeight protected
Definition at line 240 of file IR2Vec.h.
Referenced by Embedder().
BBVecMap
BBEmbeddingsMap llvm::ir2vec::Embedder::BBVecMap mutable protected
Definition at line 245 of file IR2Vec.h.
Referenced by getBBVecMap(), and getBBVector().
Dimension
const unsigned llvm::ir2vec::Embedder::Dimension protected
Dimension of the vector representation; captured from the input vocabulary.
Definition at line 236 of file IR2Vec.h.
Referenced by Embedder(), and llvm::ir2vec::SymbolicEmbedder::SymbolicEmbedder().
F
const Function& llvm::ir2vec::Embedder::F protected
Definition at line 232 of file IR2Vec.h.
Referenced by create(), Embedder(), llvm::ir2vec::SymbolicEmbedder::SymbolicEmbedder(), and ~Embedder().
FuncVector
Embedding llvm::ir2vec::Embedder::FuncVector mutable protected
Definition at line 244 of file IR2Vec.h.
Referenced by getFunctionVector(), and llvm::ir2vec::SymbolicEmbedder::SymbolicEmbedder().
InstVecMap
InstEmbeddingsMap llvm::ir2vec::Embedder::InstVecMap mutable protected
Definition at line 246 of file IR2Vec.h.
Referenced by getInstVecMap().
OpcWeight
const float llvm::ir2vec::Embedder::OpcWeight protected
Weights for different entities (like opcode, arguments, types) in the IR instructions to generate the vector representation.
Definition at line 240 of file IR2Vec.h.
Referenced by Embedder().
TypeWeight
const float llvm::ir2vec::Embedder::TypeWeight protected
Definition at line 240 of file IR2Vec.h.
Referenced by Embedder().
Vocab
const Vocabulary& llvm::ir2vec::Embedder::Vocab protected
Definition at line 233 of file IR2Vec.h.
Referenced by create(), Embedder(), llvm::ir2vec::SymbolicEmbedder::SymbolicEmbedder(), and ~Embedder().
The documentation for this class was generated from the following files:
include/llvm/Analysis/IR2Vec.h
lib/Analysis/IR2Vec.cpp