LLVM: llvm::MCDecodedPseudoProbe Class Reference
llvm::MCDecodedPseudoProbe Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCDecodedPseudoProbe (uint64_t Ad, uint32_t I, PseudoProbeType K, uint8_t At, uint32_t D, MCDecodedPseudoProbeInlineTree *Tree)
LLVM_ABI uint64_t getGuid () const
uint64_t getAddress () const
void setAddress (uint64_t Addr)
MCDecodedPseudoProbeInlineTree * getInlineTreeNode () const
LLVM_ABI void getInlineContext (SmallVectorImpl< MCPseudoProbeFrameLocation > &ContextStack, const GUIDProbeFunctionMap &GUID2FuncMAP) const
LLVM_ABI std::string getInlineContextStr (const GUIDProbeFunctionMap &GUID2FuncMAP) const
LLVM_ABI void print (raw_ostream &OS, const GUIDProbeFunctionMap &GUID2FuncMAP, bool ShowName) const
Public Member Functions inherited from llvm::MCPseudoProbeBase
MCPseudoProbeBase (uint64_t I, uint64_t At, uint8_t T, uint32_t D)
bool isEntry () const
uint32_t getIndex () const
uint32_t getDiscriminator () const
uint8_t getAttributes () const
uint8_t getType () const
bool isBlock () const
bool isIndirectCall () const
bool isDirectCall () const
bool isCall () const
void setAttributes (uint8_t Attr)
Additional Inherited Members
Protected Attributes inherited from llvm::MCPseudoProbeBase
uint32_t Index
uint32_t Discriminator
uint8_t Attributes
uint8_t Type
Static Protected Attributes inherited from llvm::MCPseudoProbeBase
static const uint32_t PseudoProbeFirstId = 1
Detailed Description
Definition at line 189 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCDecodedPseudoProbe()
llvm::MCDecodedPseudoProbe::MCDecodedPseudoProbe (uint64_t Ad, uint32_t I, PseudoProbeType K, uint8_t At, uint32_t D, MCDecodedPseudoProbeInlineTree * Tree) inline
Definition at line 194 of file MCPseudoProbe.h.
References D(), I, and llvm::MCPseudoProbeBase::MCPseudoProbeBase().
Member Function Documentation
getAddress()
uint64_t llvm::MCDecodedPseudoProbe::getAddress () const inline
Definition at line 200 of file MCPseudoProbe.h.
getGuid()
uint64_t MCDecodedPseudoProbe::getGuid () const
Definition at line 50 of file MCPseudoProbe.cpp.
Referenced by llvm::MCPseudoProbeDecoder::getInlineContextForProbe(), and print().
getInlineContext()
void MCDecodedPseudoProbe::getInlineContext (SmallVectorImpl< MCPseudoProbeFrameLocation > & ContextStack, const GUIDProbeFunctionMap & GUID2FuncMAP) const
Definition at line 283 of file MCPseudoProbe.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MCDecodedPseudoProbeInlineTree::getInlineSite(), getProbeFNameForGUID(), llvm::MCPseudoProbeInlineTreeBase< ProbesType, DerivedProbeInlineTreeType, InlinedProbeTreeMap >::Guid, llvm::MCDecodedPseudoProbeInlineTree::hasInlineSite(), llvm::MCPseudoProbeInlineTreeBase< ProbesType, DerivedProbeInlineTreeType, InlinedProbeTreeMap >::Parent, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::MCPseudoProbeDecoder::getInlineContextForProbe(), and getInlineContextStr().
getInlineContextStr()
std::string MCDecodedPseudoProbe::getInlineContextStr (const GUIDProbeFunctionMap & GUID2FuncMAP) const
Definition at line 300 of file MCPseudoProbe.cpp.
References getInlineContext().
Referenced by print().
getInlineTreeNode()
MCDecodedPseudoProbeInlineTree * llvm::MCDecodedPseudoProbe::getInlineTreeNode () const inline
Definition at line 204 of file MCPseudoProbe.h.
Referenced by llvm::MCPseudoProbeDecoder::addInjectedProbe(), and llvm::MCPseudoProbeDecoder::getInlinerDescForProbe().
print()
void MCDecodedPseudoProbe::print (raw_ostream & OS, const GUIDProbeFunctionMap & GUID2FuncMAP, bool ShowName) const
Definition at line 316 of file MCPseudoProbe.cpp.
References llvm::MCPseudoProbeBase::Discriminator, getGuid(), getInlineContextStr(), getProbeFNameForGUID(), llvm::MCPseudoProbeBase::Index, PseudoProbeTypeStr, llvm::StringRef::str(), and llvm::MCPseudoProbeBase::Type.
setAddress()
void llvm::MCDecodedPseudoProbe::setAddress (uint64_t Addr) inline
Definition at line 202 of file MCPseudoProbe.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp