LLVM: llvm::MCTargetStreamer Class Reference
llvm::MCTargetStreamer Class Reference
Target specific streamer interface.
#include "llvm/MC/MCStreamer.h"
Public Member Functions
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Protected Attributes
MCStreamer & Streamer
Detailed Description
Target specific streamer interface.
This is used so that targets can implement support for target specific assembly directives.
If target foo wants to use this, it should implement 3 classes:
FooTargetStreamer : public MCTargetStreamer
FooTargetAsmStreamer : public FooTargetStreamer
FooTargetELFStreamer : public FooTargetStreamer
FooTargetStreamer should have a pure virtual method for each directive. For example, for a ".bar symbol_name" directive, it should have virtual emitBar(const MCSymbol &Symbol) = 0;
The FooTargetAsmStreamer and FooTargetELFStreamer classes implement the method. The assembly streamer just prints ".bar symbol_name". The object streamer does whatever is needed to implement .bar in the object file.
In the assembly printer and parser the target streamer can be used by calling getTargetStreamer and casting it to FooTargetStreamer:
MCTargetStreamer &TS = OutStreamer.getTargetStreamer(); FooTargetStreamer &ATS = static_cast<FooTargetStreamer &>(TS);
The base classes FooTargetAsmStreamer and FooTargetELFStreamer should never be treated differently. Callers should always talk to a FooTargetStreamer.
Definition at line 93 of file MCStreamer.h.
Constructor & Destructor Documentation
MCTargetStreamer()
MCTargetStreamer::MCTargetStreamer (MCStreamer & S)
Definition at line 46 of file MCStreamer.cpp.
References llvm::MCStreamer::setTargetStreamer(), and Streamer.
Referenced by llvm::AArch64TargetStreamer::AArch64TargetStreamer(), llvm::AMDGPUTargetStreamer::AMDGPUTargetStreamer(), llvm::ARCTargetStreamer::ARCTargetStreamer(), llvm::ARMTargetStreamer::ARMTargetStreamer(), llvm::AVRTargetStreamer::AVRTargetStreamer(), llvm::CSKYTargetStreamer::CSKYTargetStreamer(), llvm::HexagonTargetStreamer::HexagonTargetStreamer(), llvm::LoongArchTargetStreamer::LoongArchTargetStreamer(), llvm::MipsTargetStreamer::MipsTargetStreamer(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), llvm::NVPTXTargetStreamer::NVPTXTargetStreamer(), llvm::PPCTargetStreamer::PPCTargetStreamer(), llvm::RISCVTargetStreamer::RISCVTargetStreamer(), llvm::SparcTargetStreamer::SparcTargetStreamer(), llvm::SPIRVTargetStreamer::SPIRVTargetStreamer(), llvm::SystemZTargetStreamer::SystemZTargetStreamer(), llvm::VETargetStreamer::VETargetStreamer(), llvm::WebAssemblyTargetStreamer::WebAssemblyTargetStreamer(), llvm::X86TargetStreamer::X86TargetStreamer(), llvm::XCoreTargetStreamer::XCoreTargetStreamer(), and llvm::XtensaTargetStreamer::XtensaTargetStreamer().
~MCTargetStreamer()
MCTargetStreamer::~MCTargetStreamer () virtual default
Member Function Documentation
changeSection()
void MCTargetStreamer::changeSection (const MCSection * CurSection, MCSection * Section, uint32_t SubSection, raw_ostream & OS) virtual
Update streamer for a new active section.
This is called by popSection and switchSection, if the current section changes.
Reimplemented in llvm::NVPTXTargetStreamer, and llvm::SPIRVTargetStreamer.
Definition at line 59 of file MCStreamer.cpp.
References Streamer.
emitAssignment()
void MCTargetStreamer::emitAssignment (MCSymbol * Symbol, const MCExpr * Value) virtual
Reimplemented in llvm::MipsTargetELFStreamer.
Definition at line 91 of file MCStreamer.cpp.
Referenced by llvm::MCStreamer::emitAssignment().
emitConstantPools()
void MCTargetStreamer::emitConstantPools () virtual
Reimplemented in llvm::AArch64TargetStreamer, llvm::ARMTargetStreamer, and llvm::SystemZTargetStreamer.
Definition at line 57 of file MCStreamer.cpp.
emitDwarfFileDirective()
void MCTargetStreamer::emitDwarfFileDirective (StringRef Directive) virtual
Reimplemented in llvm::NVPTXTargetStreamer.
Definition at line 67 of file MCStreamer.cpp.
References Streamer.
emitLabel()
void MCTargetStreamer::emitLabel (MCSymbol * Symbol) virtual
Reimplemented in llvm::MipsTargetELFStreamer.
Definition at line 53 of file MCStreamer.cpp.
Referenced by llvm::MCStreamer::emitLabel().
emitRawBytes()
void MCTargetStreamer::emitRawBytes (StringRef Data) virtual
Emit the bytes in Data into the output.
This is used to emit bytes in Data as sequence of .byte directives.
Reimplemented in llvm::NVPTXTargetStreamer.
Definition at line 79 of file MCStreamer.cpp.
References llvm::CallingConv::C, llvm::Data, llvm::MCAsmInfo::getData8bitsDirective(), llvm::raw_svector_ostream::str(), and Streamer.
Referenced by llvm::NVPTXTargetStreamer::emitRawBytes().
emitValue()
void MCTargetStreamer::emitValue (const MCExpr * Value) virtual
Reimplemented in llvm::NVPTXTargetStreamer.
Definition at line 71 of file MCStreamer.cpp.
References llvm::raw_svector_ostream::str(), and Streamer.
Referenced by llvm::NVPTXTargetStreamer::emitValue().
finish()
void MCTargetStreamer::finish () virtual
Reimplemented in llvm::AArch64TargetStreamer, llvm::AMDGPUTargetAsmStreamer, llvm::AMDGPUTargetELFStreamer, llvm::CSKYTargetStreamer, llvm::HexagonTargetStreamer, llvm::LoongArchTargetELFStreamer, llvm::MipsTargetELFStreamer, llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetStreamer.
Definition at line 55 of file MCStreamer.cpp.
Referenced by llvm::LoongArchTargetELFStreamer::finish(), and llvm::MCStreamer::finish().
getContext()
MCContext & llvm::MCTargetStreamer::getContext () inline
Definition at line 1125 of file MCStreamer.h.
References Streamer.
Referenced by llvm::NVPTXTargetStreamer::changeSection(), llvm::WebAssemblyTargetAsmStreamer::emitIndIdx(), and llvm::ARMTargetStreamer::emitInst().
getStreamer()
MCStreamer & llvm::MCTargetStreamer::getStreamer () inline
Definition at line 101 of file MCStreamer.h.
References Streamer.
Referenced by llvm::CSKYTargetStreamer::addConstantPoolEntry(), llvm::NVPTXTargetStreamer::changeSection(), llvm::NVPTXTargetStreamer::closeLastSection(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFIEpilogEnd(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFIEpilogStart(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFIPrologEnd(), llvm::MipsTargetAsmStreamer::emitDTPRel32Value(), llvm::MipsTargetAsmStreamer::emitDTPRel64Value(), llvm::SystemZTargetHLASMStreamer::emitExtern(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::MipsTargetAsmStreamer::emitGPRel32Value(), llvm::MipsTargetAsmStreamer::emitGPRel64Value(), llvm::MipsTargetStreamer::emitII(), llvm::AArch64TargetStreamer::emitInst(), llvm::ARMTargetStreamer::emitInst(), llvm::RISCVTargetStreamer::emitNoteGnuPropertySection(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRRX(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), llvm::MipsTargetAsmStreamer::emitTPRel32Value(), llvm::MipsTargetAsmStreamer::emitTPRel64Value(), llvm::SystemZTargetHLASMStreamer::getHLASMStreamer(), and llvm::NVPTXTargetStreamer::outputDwarfFileDirectives().
prettyPrintAsm()
void MCTargetStreamer::prettyPrintAsm (MCInstPrinter & InstPrinter, uint64_t Address, const MCInst & Inst, const MCSubtargetInfo & STI, raw_ostream & OS) virtual
Definition at line 1156 of file MCStreamer.cpp.
References llvm::Address, and llvm::MCInstPrinter::printInst().
Member Data Documentation
Streamer
MCStreamer& llvm::MCTargetStreamer::Streamer protected
Definition at line 95 of file MCStreamer.h.
Referenced by llvm::AArch64TargetStreamer::addConstantPoolEntry(), llvm::ARMTargetStreamer::addConstantPoolEntry(), changeSection(), llvm::AArch64TargetStreamer::emitAuthValue(), llvm::AArch64TargetStreamer::emitConstantPools(), llvm::ARMTargetStreamer::emitConstantPools(), llvm::SystemZTargetStreamer::emitConstantPools(), llvm::AArch64TargetStreamer::emitCurrentConstantPool(), llvm::ARMTargetStreamer::emitCurrentConstantPool(), llvm::CSKYTargetStreamer::emitCurrentConstantPool(), llvm::MipsTargetELFStreamer::emitDirectiveInsn(), emitDwarfFileDirective(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), emitRawBytes(), llvm::NVPTXTargetStreamer::emitRawBytes(), emitValue(), llvm::NVPTXTargetStreamer::emitValue(), llvm::WebAssemblyTargetStreamer::emitValueType(), llvm::CSKYTargetStreamer::finish(), llvm::MipsTargetELFStreamer::finish(), llvm::AMDGPUTargetStreamer::getContext(), getContext(), llvm::AVRELFStreamer::getStreamer(), llvm::CSKYTargetELFStreamer::getStreamer(), llvm::LoongArchTargetELFStreamer::getStreamer(), getStreamer(), llvm::MipsTargetELFStreamer::getStreamer(), llvm::MSP430TargetELFStreamer::getStreamer(), llvm::RISCVTargetELFStreamer::getStreamer(), llvm::SparcTargetELFStreamer::getStreamer(), llvm::VETargetELFStreamer::getStreamer(), llvm::XtensaTargetELFStreamer::getStreamer(), MCTargetStreamer(), and llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer().
The documentation for this class was generated from the following files:
include/llvm/MC/MCStreamer.h
lib/MC/MCStreamer.cpp