LLVM: llvm::InlineSizeEstimatorAnalysis Class Reference
llvm::InlineSizeEstimatorAnalysis Class Reference
#include "llvm/Analysis/InlineSizeEstimatorAnalysis.h"
Public Types
using Result = std::optional<size_t>
Public Member Functions
InlineSizeEstimatorAnalysis ()
InlineSizeEstimatorAnalysis (InlineSizeEstimatorAnalysis &&)
~InlineSizeEstimatorAnalysis ()
Result run (const Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< InlineSizeEstimatorAnalysis >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isEvaluatorRequested ()
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< InlineSizeEstimatorAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< InlineSizeEstimatorAnalysis >
static StringRef name ()
Gets the name of the pass we are mixed into.
Static Public Attributes
static AnalysisKey Key
Detailed Description
Definition at line 19 of file InlineSizeEstimatorAnalysis.h.
Member Typedef Documentation
Result
using llvm::InlineSizeEstimatorAnalysis::Result = std::optional<size_t>
Definition at line 27 of file InlineSizeEstimatorAnalysis.h.
Constructor & Destructor Documentation
InlineSizeEstimatorAnalysis() [1/2]
InlineSizeEstimatorAnalysis::InlineSizeEstimatorAnalysis () default
References InlineSizeEstimatorAnalysis().
Referenced by InlineSizeEstimatorAnalysis(), and InlineSizeEstimatorAnalysis().
InlineSizeEstimatorAnalysis() [2/2]
InlineSizeEstimatorAnalysis::InlineSizeEstimatorAnalysis (InlineSizeEstimatorAnalysis &&)
Definition at line 264 of file InlineSizeEstimatorAnalysis.cpp.
References InlineSizeEstimatorAnalysis().
~InlineSizeEstimatorAnalysis()
InlineSizeEstimatorAnalysis::~InlineSizeEstimatorAnalysis () default
Member Function Documentation
isEvaluatorRequested()
bool InlineSizeEstimatorAnalysis::isEvaluatorRequested () static
Definition at line 272 of file InlineSizeEstimatorAnalysis.cpp.
run()
InlineSizeEstimatorAnalysis::Result InlineSizeEstimatorAnalysis::run (const Function & F, FunctionAnalysisManager & FAM)
Definition at line 268 of file InlineSizeEstimatorAnalysis.cpp.
References F, and FAM.
Member Data Documentation
Key
AnalysisKey InlineSizeEstimatorAnalysis::Key static
Definition at line 26 of file InlineSizeEstimatorAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/InlineSizeEstimatorAnalysis.h
lib/Analysis/InlineSizeEstimatorAnalysis.cpp