LLVM: llvm::ICmpInst Class Reference
llvm::ICmpInst Class Reference
This instruction compares its operands according to the predicate given to the constructor.
#include "llvm/IR/Instructions.h"
Public Member Functions
ICmpInst (InsertPosition InsertBefore, Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with insertion semantics.
ICmpInst (Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with no-insertion semantics.
CmpPredicate getCmpPredicate () const
CmpPredicate getInverseCmpPredicate () const
CmpPredicate getSwappedCmpPredicate () const
Predicate getNonStrictCmpPredicate () const
For example, SGT -> SGE, SLT -> SLE, ULT -> ULE, UGT -> UGE.
Predicate getSignedPredicate () const
For example, EQ->EQ, SLE->SLE, UGT->SGT, etc.
Predicate getUnsignedPredicate () const
For example, EQ->EQ, SLE->ULE, UGT->UGT, etc.
Predicate getFlippedSignednessPredicate () const
For example, SLT->ULT, ULT->SLT, SLE->ULE, ULE->SLE, EQ->EQ.
void setSameSign (bool B=true)
bool hasSameSign () const
An icmp instruction, which can be marked as "samesign", indicating that the two operands have the same sign.
bool isEquality () const
Return true if this predicate is either EQ or NE.
bool isCommutative () const
bool isRelational () const
Return true if the predicate is relational (not EQ or NE).
void swapOperands ()
Exchange the two operands to this instruction in such a way that it does not modify the semantics of the instruction.
Public Member Functions inherited from llvm::CmpInst
void * operator new (size_t S)
void operator delete (void *Ptr)
OtherOps getOpcode () const
Get the opcode casted to the right type.
Predicate getPredicate () const
Return the predicate for this instruction.
void setPredicate (Predicate P)
Set the predicate for this instruction to the specified value.
bool isFPPredicate () const
bool isIntPredicate () const
Predicate getInversePredicate () const
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
Predicate getOrderedPredicate () const
Predicate getUnorderedPredicate () const
Predicate getSwappedPredicate () const
For example, EQ->EQ, SLE->SGE, ULT->UGT, OEQ->OEQ, ULE->UGE, OLT->OGT, etc.
bool isStrictPredicate () const
bool isNonStrictPredicate () const
Predicate getStrictPredicate () const
For example, SGE -> SGT, SLE -> SLT, ULE -> ULT, UGE -> UGT.
Predicate getNonStrictPredicate () const
For example, SGT -> SGE, SLT -> SLE, ULT -> ULE, UGT -> UGE.
Predicate getFlippedStrictnessPredicate () const
For predicate of kind "is X or equal to 0" returns the predicate "is X".
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide more efficient getOperand methods.
LLVM_ABI void swapOperands ()
This is just a convenience that dispatches to the subclasses.
LLVM_ABI bool isCommutative () const
This is just a convenience that dispatches to the subclasses.
bool isEquality () const
Determine if this is an equals/not equals predicate.
LLVM_ABI bool isEquivalence (bool Invert=false) const
Determine if one operand of this compare can always be replaced by the other operand, ignoring provenance considerations.
bool isRelational () const
Return true if the predicate is relational (not EQ or NE).
bool isSigned () const
bool isUnsigned () const
bool isTrueWhenEqual () const
This is just a convenience.
bool isFalseWhenEqual () const
This is just a convenience.
Public Member Functions inherited from llvm::Instruction
LLVM_ABI iterator_range< simple_ilist< DbgRecord >::iterator > cloneDebugInfoFrom (const Instruction *From, std::optional< simple_ilist< DbgRecord >::iterator > FromHere=std::nullopt, bool InsertAtHead=false)
Clone any debug-info attached to From onto this instruction.
iterator_range< simple_ilist< DbgRecord >::iterator > getDbgRecordRange () const
Return a range over the DbgRecords attached to this instruction.
LLVM_ABI std::optional< simple_ilist< DbgRecord >::iterator > getDbgReinsertionPosition ()
Return an iterator to the position of the "Next" DbgRecord after this instruction, or std::nullopt.
LLVM_ABI bool hasDbgRecords () const
Returns true if any DbgRecords are attached to this instruction.
LLVM_ABI void adoptDbgRecords (BasicBlock *BB, InstListType::iterator It, bool InsertAtHead)
Transfer any DbgRecords on the position It onto this instruction, by simply adopting the sequence of DbgRecords (which is efficient) if possible, by merging two sequences otherwise.
LLVM_ABI void dropDbgRecords ()
Erase any DbgRecords attached to this instruction.
LLVM_ABI void dropOneDbgRecord (DbgRecord *I)
Erase a single DbgRecord I that is attached to this instruction.
LLVM_ABI void handleMarkerRemoval ()
Handle the debug-info implications of this instruction being removed.
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
LLVM_ABI const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
LLVM_ABI const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
LLVM_ABI const DataLayout & getDataLayout () const
Get the data layout of the module this instruction belongs to.
LLVM_ABI void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
LLVM_ABI InstListType::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void insertBefore(Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
LLVM_ABI void insertBefore (InstListType::iterator InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified position.
LLVM_ABI void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
LLVM_ABI void insertAfter (InstListType::iterator InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified position.
LLVM_ABI InstListType::iterator insertInto (BasicBlock *ParentBB, InstListType::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
LLVM_ABI void insertBefore (BasicBlock &BB, InstListType::iterator InsertPos)
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void moveBefore(Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
LLVM_ABI void moveBefore (InstListType::iterator InsertPos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
LLVM_ABI void moveBeforePreserving (InstListType::iterator MovePos)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI void moveBeforePreserving (BasicBlock &BB, InstListType::iterator I)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void moveBeforePreserving(Instruction *MovePos)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI void moveBefore (BasicBlock &BB, InstListType::iterator I)
Unlink this instruction and insert into BB before I.
LLVM_ABI void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
LLVM_ABI void moveAfter (InstListType::iterator MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
LLVM_ABI void moveAfterPreserving (Instruction *MovePos)
See moveBeforePreserving .
LLVM_ABI bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
LLVM_ABI std::optional< InstListType::iterator > getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isFPDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isSpecialTerminator () const
LLVM_ABI bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
LLVM_ABI bool hasNonDebugLocLoopMetadata () const
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
LLVM_ABI void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
LLVM_ABI void setMetadata (StringRef Kind, MDNode *Node)
LLVM_ABI void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
LLVM_ABI void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata that matches the predicate.
LLVM_ABI void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
LLVM_ABI void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
LLVM_ABI void addAnnotationMetadata (SmallVector< StringRef > Annotations)
Adds an !annotation metadata node with an array of Annotations as a tuple to this instruction.
LLVM_ABI AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
LLVM_ABI void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
LLVM_ABI void setNoSanitizeMetadata ()
Sets the nosanitize metadata on this instruction.
LLVM_ABI bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
LLVM_ABI const DebugLoc & getStableDebugLoc () const
Fetch the debug location for this node, unless this is a debug intrinsic, in which case fetch the debug location of the next non-debug node.
LLVM_ABI void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setNonNeg (bool b=true)
Set or clear the nneg flag on this instruction, which must be a zext instruction.
LLVM_ABI bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
LLVM_ABI bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
LLVM_ABI bool hasNonNeg () const LLVM_READONLY
Determine whether the the nneg flag is set.
LLVM_ABI bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
LLVM_ABI void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
LLVM_ABI bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
LLVM_ABI void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
LLVM_ABI bool hasPoisonGeneratingReturnAttributes () const LLVM_READONLY
Return true if this instruction has poison-generating attribute.
LLVM_ABI void dropPoisonGeneratingReturnAttributes ()
Drops return attributes that may generate poison.
bool hasPoisonGeneratingAnnotations () const
Return true if this instruction has poison-generating flags, return attributes or metadata.
void dropPoisonGeneratingAnnotations ()
Drops flags, return attributes and metadata that may generate poison.
LLVM_ABI void dropUBImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
LLVM_ABI void dropUBImplyingAttrsAndMetadata ()
Drop any attributes or metadata that can cause immediate undefined behavior.
LLVM_ABI bool hasUBImplyingAttrs () const LLVM_READONLY
Return true if this instruction has UB-implying attributes that can cause immediate undefined behavior.
LLVM_ABI bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
LLVM_ABI void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
LLVM_ABI bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
LLVM_ABI bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
LLVM_ABI bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
LLVM_ABI bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
LLVM_ABI bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
LLVM_ABI bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
LLVM_ABI bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
LLVM_ABI bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
LLVM_ABI FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
LLVM_ABI void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
LLVM_ABI void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
LLVM_ABI void applyMergedLocation (DebugLoc LocA, DebugLoc LocB)
Merge 2 debug locations and apply it to the Instruction.
LLVM_ABI void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
LLVM_ABI void dropLocation ()
Drop the instruction's debug location.
LLVM_ABI void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
LLVM_ABI bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
LLVM_ABI bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
LLVM_ABI bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
LLVM_ABI bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
LLVM_ABI bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
LLVM_ABI bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
LLVM_ABI bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
LLVM_ABI bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
LLVM_ABI Type * getAccessType () const LLVM_READONLY
Return the type this instruction accesses in memory, if any.
LLVM_ABI bool mayThrow (bool IncludePhaseOneUnwind=false) const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
LLVM_ABI bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
LLVM_ABI bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
LLVM_ABI bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
LLVM_ABI bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
LLVM_ABI bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
LLVM_ABI bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
LLVM_ABI const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
LLVM_ABI const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
LLVM_ABI Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
LLVM_ABI bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
LLVM_ABI bool isIdenticalToWhenDefined (const Instruction *I, bool IntersectAttrs=false) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
LLVM_ABI bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
LLVM_ABI bool hasSameSpecialState (const Instruction *I2, bool IgnoreAlignment=false, bool IntersectAttrs=false) const LLVM_READONLY
This function determines if the speficied instruction has the same "special" characteristics as the current one.
LLVM_ABI bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
LLVM_ABI unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
LLVM_ABI BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
LLVM_ABI void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
LLVM_ABI void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
LLVM_ABI void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs={})
Drop all unknown metadata except for debug locations.
Public Member Functions inherited from llvm::User
User (const User &)=delete
LLVM_ABI void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, HungOffOperandsAllocMarker)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, IntrusiveOperandsAllocMarker)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, IntrusiveOperandsAndDescriptorAllocMarker)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
LLVM_ABI ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
LLVM_ABI MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
LLVM_ABI bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
LLVM_ABI bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
LLVM_ABI void deleteValue ()
Delete a pointer to a generic Value.
LLVM_ABI void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVM_ABI LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
LLVM_ABI ValueName * getValueName () const
LLVM_ABI void setValueName (ValueName *VN)
LLVM_ABI StringRef getName () const
Return a constant reference to the value's name.
LLVM_ABI void setName (const Twine &Name)
Change the name of the value.
LLVM_ABI void takeName (Value *V)
Transfer the name from V to this value.
LLVM_ABI std::string getNameOrAsOperand () const
LLVM_ABI void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
LLVM_ABI void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
LLVM_ABI void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
LLVM_ABI void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
LLVM_ABI void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool hasUseList () const
Check if this Value has a use-list.
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
LLVM_ABI bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
LLVM_ABI bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI bool hasOneUser () const
Return true if there is exactly one user of this value.
LLVM_ABI Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
LLVM_ABI User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
LLVM_ABI bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
LLVM_ABI bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
LLVM_ABI void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
LLVM_ABI bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
LLVM_ABI unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
LLVM_ABI bool isSwiftError () const
Return true if this value is a swifterror value.
LLVM_ABI const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
LLVM_ABI const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
LLVM_ABI const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
LLVM_ABI const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
LLVM_ABI const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
LLVM_ABI const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
LLVM_ABI const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
LLVM_ABI std::optional< int64_t > getPointerOffsetFrom (const Value *Other, const DataLayout &DL) const
If this ptr is provably equal to Other plus a constant offset, return that offset in bytes.
LLVM_ABI bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
LLVM_ABI uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
LLVM_ABI Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
LLVM_ABI const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
LLVM_ABI void reverseUseList ()
Reverse the use-list.
LLVM_ABI void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
LLVM_ABI void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock, ilist_iterator_bits< true >, ilist_parent< BasicBlock > >
Instruction * getPrevNode ()
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >, ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty *Parent)
Static Public Member Functions
static CmpPredicate getInverseCmpPredicate (CmpPredicate Pred)
static CmpPredicate getSwappedCmpPredicate (CmpPredicate Pred)
static CmpPredicate getNonStrictCmpPredicate (CmpPredicate Pred)
static LLVM_ABI Predicate getSignedPredicate (Predicate Pred)
Return the signed version of the predicate: static variant.
static LLVM_ABI Predicate getUnsignedPredicate (Predicate Pred)
Return the unsigned version of the predicate: static variant.
static LLVM_ABI Predicate getFlippedSignednessPredicate (Predicate Pred)
For example, SLT->ULT, ULT->SLT, SLE->ULE, ULE->SLE, EQ->EQ.
static LLVM_ABI std::optional< bool > isImpliedByMatchingCmp (CmpPredicate Pred1, CmpPredicate Pred2)
Determine if Pred1 implies Pred2 is true, false, or if nothing can be inferred about the implication, when two compares have matching operands.
static bool isEquality (Predicate P)
Return true if this predicate is either EQ or NE.
static bool isCommutative (Predicate P)
static bool isRelational (Predicate P)
Return true if the predicate is relational (not EQ or NE).
static bool isGT (Predicate P)
Return true if the predicate is SGT or UGT.
static bool isLT (Predicate P)
Return true if the predicate is SLT or ULT.
static bool isGE (Predicate P)
Return true if the predicate is SGE or UGE.
static bool isLE (Predicate P)
Return true if the predicate is SLE or ULE.
static auto predicates ()
Returns the sequence of all ICmp predicates.
static LLVM_ABI bool compare (const APInt &LHS, const APInt &RHS, ICmpInst::Predicate Pred)
Return result of LHS Pred RHS comparison.
static LLVM_ABI std::optional< bool > compare (const KnownBits &LHS, const KnownBits &RHS, ICmpInst::Predicate Pred)
Return result of LHS Pred RHS, if it can be determined from the KnownBits.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::CmpInst
static auto FCmpPredicates ()
Returns the sequence of all FCmp predicates.
static auto ICmpPredicates ()
Returns the sequence of all ICmp predicates.
static LLVM_ABI CmpInst * Create (OtherOps Op, Predicate Pred, Value *S1, Value *S2, const Twine &Name="", InsertPosition InsertBefore=nullptr)
Construct a compare instruction, given the opcode, the predicate and the two operands.
static LLVM_ABI CmpInst * CreateWithCopiedFlags (OtherOps Op, Predicate Pred, Value *S1, Value *S2, const Instruction *FlagsSource, const Twine &Name="", InsertPosition InsertBefore=nullptr)
Construct a compare instruction, given the opcode, the predicate, the two operands and the instruction to copy the flags from.
static bool isFPPredicate (Predicate P)
static bool isIntPredicate (Predicate P)
static LLVM_ABI StringRef getPredicateName (Predicate P)
static Predicate getOrderedPredicate (Predicate Pred)
Returns the ordered variant of a floating point compare.
static Predicate getUnorderedPredicate (Predicate Pred)
Returns the unordered variant of a floating point compare.
static LLVM_ABI Predicate getInversePredicate (Predicate pred)
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
static LLVM_ABI Predicate getSwappedPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI bool isStrictPredicate (Predicate predicate)
This is a static version that you can use without an instruction available.
static LLVM_ABI bool isNonStrictPredicate (Predicate predicate)
This is a static version that you can use without an instruction available.
static LLVM_ABI Predicate getStrictPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI Predicate getNonStrictPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI Predicate getFlippedStrictnessPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static LLVM_ABI bool isEquality (Predicate pred)
Determine if this is an equals/not equals predicate.
static bool isRelational (Predicate P)
Return true if the predicate is relational (not EQ or NE).
static LLVM_ABI bool isUnsigned (Predicate predicate)
static LLVM_ABI bool isSigned (Predicate predicate)
static LLVM_ABI bool isOrdered (Predicate predicate)
Determine if the predicate is an ordered operation.
static LLVM_ABI bool isUnordered (Predicate predicate)
Determine if the predicate is an unordered operation.
static LLVM_ABI bool isTrueWhenEqual (Predicate predicate)
Determine if the predicate is true when comparing a value with itself.
static LLVM_ABI bool isFalseWhenEqual (Predicate predicate)
Determine if the predicate is false when comparing a value with itself.
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
static Type * makeCmpResultType (Type *opnd_type)
Create a result type for fcmp/icmp.
Static Public Member Functions inherited from llvm::Instruction
static LLVM_ABI const char * getOpcodeName (unsigned Opcode)
static bool isTerminator (unsigned Opcode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isFPDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned Opcode)
Determine if the Opcode is one of the CastInst instructions.
static bool isFuncletPad (unsigned Opcode)
Determine if the Opcode is one of the FuncletPadInst instructions.
static bool isSpecialTerminator (unsigned Opcode)
Returns true if the Opcode is a "special" terminator that does more than branch to a successor (e.g.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static LLVM_ABI void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
LLVM_ABI ICmpInst * cloneImpl () const
Clone an identical ICmpInst.
Protected Member Functions inherited from llvm::CmpInst
LLVM_ABI CmpInst (Type *ty, Instruction::OtherOps op, Predicate pred, Value *LHS, Value *RHS, const Twine &Name="", InsertPosition InsertBefore=nullptr, Instruction *FlagsSource=nullptr)
Protected Member Functions inherited from llvm::Instruction
LLVM_ABI ~Instruction ()
template<typename BitfieldElement>
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement>
void setSubclassData (typename BitfieldElement::Type Value)
LLVM_ABI Instruction (Type *Ty, unsigned iType, AllocInfo AllocInfo, InsertPosition InsertBefore=nullptr)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)=delete
LLVM_ABI void * operator new (size_t Size, HungOffOperandsAllocMarker)
Allocate a User with an operand pointer co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAndDescriptorAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, AllocInfo AllocInfo)
LLVM_ABI void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
LLVM_ABI void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
LLVM_ABI Value (Type *Ty, unsigned scid)
LLVM_ABI ~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
LLVM_ABI void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
LLVM_ABI bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
LLVM_ABI void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata attachments matching the given predicate.
LLVM_ABI void clearMetadata ()
Erase all metadata attached to this Value.
LLVM_ABI MDNode * getMetadataImpl (unsigned KindID) const
Get metadata for the given kind, if any.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
LLVM_ABI MDNode * getMetadata (StringRef Kind) const
LLVM_ABI void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
LLVM_ABI void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
LLVM_ABI void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
LLVM_ABI void setMetadata (StringRef Kind, MDNode *Node)
LLVM_ABI void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
LLVM_ABI void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock, ilist_iterator_bits< true >, ilist_parent< BasicBlock > >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
ilist_node_impl ()=default
Friends
class Instruction
Iterator for Instructions in a `BasicBlock.
Additional Inherited Members
Public Types inherited from llvm::CmpInst
enum Predicate : unsigned {
FCMP_FALSE = 0 , FCMP_OEQ = 1 , FCMP_OGT = 2 , FCMP_OGE = 3 ,
FCMP_OLT = 4 , FCMP_OLE = 5 , FCMP_ONE = 6 , FCMP_ORD = 7 ,
FCMP_UNO = 8 , FCMP_UEQ = 9 , FCMP_UGT = 10 , FCMP_UGE = 11 ,
FCMP_ULT = 12 , FCMP_ULE = 13 , FCMP_UNE = 14 , FCMP_TRUE = 15 ,
FIRST_FCMP_PREDICATE = FCMP_FALSE , LAST_FCMP_PREDICATE = FCMP_TRUE , BAD_FCMP_PREDICATE = FCMP_TRUE + 1 , ICMP_EQ = 32 ,
ICMP_NE = 33 , ICMP_UGT = 34 , ICMP_UGE = 35 , ICMP_ULT = 36 ,
ICMP_ULE = 37 , ICMP_SGT = 38 , ICMP_SGE = 39 , ICMP_SLT = 40 ,
ICMP_SLE = 41 , FIRST_ICMP_PREDICATE = ICMP_EQ , LAST_ICMP_PREDICATE = ICMP_SLE , BAD_ICMP_PREDICATE = ICMP_SLE + 1
}
This enumeration lists the possible predicates for CmpInst subclasses.
using PredicateField
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1 << 0 , CompareUsingScalarTypes = 1 << 1 , CompareUsingIntersectedAttrs = 1 << 2 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
using InstListType
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Public Attributes inherited from llvm::Instruction
DbgMarker * DebugMarker = nullptr
Optional marker recording the position for debugging information that takes effect immediately before this instruction.
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This instruction compares its operands according to the predicate given to the constructor.
It only operates on integers or pointers. The operands must be identical types. Represent an integer comparison operator.
Definition at line 1177 of file Instructions.h.
Constructor & Destructor Documentation
ICmpInst() [1/2]
llvm::ICmpInst::ICmpInst (InsertPosition InsertBefore, Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") inline
Constructor with insertion semantics.
Parameters
InsertBefore Where to insert
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1200 of file Instructions.h.
References llvm::CmpInst::CmpInst(), llvm::Value::getType(), Instruction, LHS, llvm::CmpInst::makeCmpResultType(), and RHS.
Referenced by cloneImpl(), and Instruction.
ICmpInst() [2/2]
llvm::ICmpInst::ICmpInst (Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") inline
Constructor with no-insertion semantics.
Parameters
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1214 of file Instructions.h.
References llvm::CmpInst::CmpInst(), llvm::Value::getType(), Instruction, LHS, llvm::CmpInst::makeCmpResultType(), and RHS.
Member Function Documentation
classof() [1/2]
bool llvm::ICmpInst::classof (const Instruction * I) inline static
Definition at line 1394 of file Instructions.h.
References I, and Instruction.
Referenced by classof().
classof() [2/2]
bool llvm::ICmpInst::classof (const Value * V) inline static
Definition at line 1397 of file Instructions.h.
References llvm::cast(), classof(), and llvm::isa().
cloneImpl()
ICmpInst * ICmpInst::cloneImpl () const protected
Clone an identical ICmpInst.
Definition at line 4339 of file Instructions.cpp.
References llvm::CmpInst::getPredicate(), and ICmpInst().
Referenced by Instruction.
compare() [1/2]
bool ICmpInst::compare (const APInt & LHS, const APInt & RHS, ICmpInst::Predicate Pred) static
Return result of LHS Pred RHS comparison.
Definition at line 3808 of file Instructions.cpp.
References assert(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::CmpInst::isIntPredicate(), and llvm_unreachable.
Referenced by llvm::sandboxir::ICmpInst::compare(), computePointerICmp(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), llvm::InstCombinerImpl::foldICmpSelectConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpUSubSatOrUAddSatWithConstant(), llvm::SelectionDAG::FoldSetCC(), llvm::PatternMatch::icmp_pred_with_threshold::isValue(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), llvm::simplifyBinaryIntrinsic(), and llvm::ScalarEvolution::SimplifyICmpOperands().
compare() [2/2]
std::optional< bool > ICmpInst::compare (const KnownBits & LHS, const KnownBits & RHS, ICmpInst::Predicate Pred) static
Return result of LHS Pred RHS, if it can be determined from the KnownBits.
Otherwise return nullopt.
Definition at line 3878 of file Instructions.cpp.
References llvm::KnownBits::eq(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, llvm::KnownBits::ne(), llvm::KnownBits::sge(), llvm::KnownBits::sgt(), llvm::KnownBits::sle(), llvm::KnownBits::slt(), llvm::KnownBits::uge(), llvm::KnownBits::ugt(), llvm::KnownBits::ule(), and llvm::KnownBits::ult().
getCmpPredicate()
CmpPredicate llvm::ICmpInst::getCmpPredicate () const inline
Returns
the predicate along with samesign information.
Definition at line 1227 of file Instructions.h.
References llvm::CmpInst::getPredicate(), and hasSameSign().
Referenced by createReplacement(), getInverseCmpPredicate(), getNonStrictCmpPredicate(), getSwappedCmpPredicate(), and simplifyInstructionWithPHI().
getFlippedSignednessPredicate() [1/2]
Predicate llvm::ICmpInst::getFlippedSignednessPredicate () const inline
For example, SLT->ULT, ULT->SLT, SLE->ULE, ULE->SLE, EQ->EQ.
Returns
the unsigned version of the signed predicate pred or the signed version of the signed predicate pred.
Definition at line 1296 of file Instructions.h.
References getFlippedSignednessPredicate(), and llvm::CmpInst::getPredicate().
Referenced by llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::ConstantRange::getEquivalentPredWithFlippedSignedness(), llvm::ScalarEvolution::getLoopInvariantPredicate(), isImpliedCondCommonOperandWithCR(), and isImpliedTrueByMatchingCmp().
getFlippedSignednessPredicate() [2/2]
CmpInst::Predicate ICmpInst::getFlippedSignednessPredicate (Predicate Pred) static
For example, SLT->ULT, ULT->SLT, SLE->ULE, ULE->SLE, EQ->EQ.
Returns
the unsigned version of the signed predicate pred or the signed version of the signed predicate pred. Static variant.
Definition at line 3907 of file Instructions.cpp.
References getSignedPredicate(), getUnsignedPredicate(), llvm::CmpInst::isEquality(), llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), and llvm_unreachable.
Referenced by getFlippedSignednessPredicate(), and llvm::CmpPredicate::getMatching().
getInverseCmpPredicate() [1/2]
CmpPredicate llvm::ICmpInst::getInverseCmpPredicate () const inline
Returns
the inverse predicate along with samesign information.
Definition at line 1238 of file Instructions.h.
References getCmpPredicate(), and getInverseCmpPredicate().
Referenced by createReplacement(), llvm::ScalarEvolution::getLoopInvariantPredicate(), and isImpliedCondICmps().
getInverseCmpPredicate() [2/2]
CmpPredicate llvm::ICmpInst::getInverseCmpPredicate (CmpPredicate Pred) inline static
Returns
the inverse predicate along with samesign information: static variant.
Definition at line 1233 of file Instructions.h.
References llvm::CmpInst::getInversePredicate().
Referenced by llvm::ScalarEvolution::evaluatePredicate(), llvm::ScalarEvolution::evaluatePredicateAt(), getInverseCmpPredicate(), and isImpliedFalseByMatchingCmp().
getNonStrictCmpPredicate() [1/2]
Predicate llvm::ICmpInst::getNonStrictCmpPredicate () const inline
For example, SGT -> SGE, SLT -> SLE, ULT -> ULE, UGT -> UGE.
Returns
the non-strict predicate along with samesign information.
Definition at line 1261 of file Instructions.h.
References getCmpPredicate(), and getNonStrictCmpPredicate().
Referenced by llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond().
getNonStrictCmpPredicate() [2/2]
CmpPredicate llvm::ICmpInst::getNonStrictCmpPredicate (CmpPredicate Pred) inline static
Returns
the non-strict predicate along with samesign information: static variant.
Definition at line 1255 of file Instructions.h.
References llvm::CmpInst::getNonStrictPredicate().
Referenced by getNonStrictCmpPredicate().
getSignedPredicate() [1/2]
Predicate llvm::ICmpInst::getSignedPredicate () const inline
For example, EQ->EQ, SLE->SLE, UGT->SGT, etc.
Returns
the predicate that would be the result if the operand were regarded as signed. Return the signed version of the predicate.
Definition at line 1269 of file Instructions.h.
References llvm::CmpInst::getPredicate(), and getSignedPredicate().
Referenced by computePointerICmp(), llvm::ConstantFoldCompareInstOperands(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), foldICmpOfCmpIntrinsicWithConstant(), foldICmpXNegX(), getFlippedSignednessPredicate(), llvm::CmpPredicate::getPreferredSignedPredicate(), getSignedPredicate(), llvm::InstCombinerImpl::insertRangeTest(), simplifySwitchOfCmpIntrinsic(), and transformToIndexedCompare().
getSignedPredicate() [2/2]
ICmpInst::Predicate ICmpInst::getSignedPredicate (Predicate Pred) static
Return the signed version of the predicate: static variant.
Definition at line 3647 of file Instructions.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
getSwappedCmpPredicate() [1/2]
CmpPredicate llvm::ICmpInst::getSwappedCmpPredicate () const inline
Returns
the swapped predicate along with samesign information.
Definition at line 1249 of file Instructions.h.
References getCmpPredicate(), and getSwappedCmpPredicate().
Referenced by llvm::ScalarEvolution::getLoopInvariantExitCondDuringFirstIterationsImpl(), llvm::ScalarEvolution::getLoopInvariantPredicate(), isImpliedCondICmps(), and llvm::ScalarEvolution::SimplifyICmpOperands().
getSwappedCmpPredicate() [2/2]
CmpPredicate llvm::ICmpInst::getSwappedCmpPredicate (CmpPredicate Pred) inline static
Returns
the swapped predicate along with samesign information: static variant.
Definition at line 1244 of file Instructions.h.
References llvm::CmpInst::getSwappedPredicate().
Referenced by llvm::InstCombinerImpl::foldSelectOpOp(), and getSwappedCmpPredicate().
getUnsignedPredicate() [1/2]
Predicate llvm::ICmpInst::getUnsignedPredicate () const inline
For example, EQ->EQ, SLE->ULE, UGT->UGT, etc.
Returns
the predicate that would be the result if the operand were regarded as unsigned. Return the unsigned version of the predicate.
Definition at line 1280 of file Instructions.h.
References llvm::CmpInst::getPredicate(), and getUnsignedPredicate().
Referenced by foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), getFlippedSignednessPredicate(), llvm::getFlippedStrictnessPredicateAndConstant(), getUnsignedPredicate(), llvm::LegalizerHelper::narrowScalar(), and simplifyICmpInst().
getUnsignedPredicate() [2/2]
ICmpInst::Predicate ICmpInst::getUnsignedPredicate (Predicate Pred) static
Return the unsigned version of the predicate: static variant.
Definition at line 3660 of file Instructions.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
hasSameSign()
bool llvm::ICmpInst::hasSameSign () const inline
An icmp instruction, which can be marked as "samesign", indicating that the two operands have the same sign.
This means that we can convert "slt" to "ult" and vice versa, which enables more optimizations.
Definition at line 1312 of file Instructions.h.
References llvm::Value::SubclassOptionalData.
Referenced by getCmpPredicate().
isCommutative() [1/2]
bool llvm::ICmpInst::isCommutative () const inline
Returns
true if the predicate of this ICmpInst is commutative Determine if this relation is commutative.
Definition at line 1332 of file Instructions.h.
References llvm::CmpInst::getPredicate(), and isCommutative().
Referenced by isCommutative().
isCommutative() [2/2]
bool llvm::ICmpInst::isCommutative (Predicate P) inline static
Returns
true if the predicate is commutative Determine if this relation is commutative.
Definition at line 1328 of file Instructions.h.
References isEquality(), and P.
isEquality() [1/2]
bool llvm::ICmpInst::isEquality () const inline
Return true if this predicate is either EQ or NE.
This also tests for commutativity.
Definition at line 1322 of file Instructions.h.
References llvm::CmpInst::getPredicate(), and isEquality().
Referenced by computePointerICmp(), llvm::ConstantFoldCompareInstOperands(), detectShiftUntilBitTestIdiom(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::CmpInst::isEquality(), llvm::predicatesFoldable(), and simplifyICmpWithBinOp().
isEquality() [2/2]
bool llvm::ICmpInst::isEquality (Predicate P) inline static
Return true if this predicate is either EQ or NE.
This also tests for commutativity.
Definition at line 1316 of file Instructions.h.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, and P.
Referenced by canonicalizeCmpWithConstant(), computePointerICmp(), llvm::ConstantFoldCompareInstruction(), countToEliminateCompares(), llvm::decomposeBitTestICmp(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldGEPICmp(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), foldICmpOrChain(), foldICmpOrXX(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmpsAsymmetric(), foldNegativePower2AndShiftedMask(), foldReductionIdiom(), foldSelectBinOpIdentity(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSelectZeroOrMul(), foldUnsignedUnderflowCheck(), llvm::ValueLatticeElement::getCompare(), getMaskedTypeForICmpPair(), isAllocSiteRemovable(), isCommutative(), isEquality(), isRelational(), isRelational(), matchBitmaskMul(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), llvm::LegalizerHelper::narrowScalar(), normalizePredicate(), llvm::LoopStructure::parseLoopStructure(), llvm::predicatesFoldable(), simplifyAndOrWithICmpEq(), simplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithConstant(), simplifyUnsignedRangeCheck(), llvm::InstCombinerImpl::visitICmpInst(), and llvm::InstCombinerImpl::visitOr().
isGE()
bool llvm::ICmpInst::isGE (Predicate P) inline static
Return true if the predicate is SGE or UGE.
Definition at line 1360 of file Instructions.h.
References llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_UGE, and P.
Referenced by llvm::decomposeBitTestICmp(), llvm::InstCombinerImpl::foldICmpBinOp(), hoistMinMax(), and sinkMinMaxInBB().
isGT()
bool llvm::ICmpInst::isGT (Predicate P) inline static
Return true if the predicate is SGT or UGT.
Definition at line 1348 of file Instructions.h.
References llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_UGT, and P.
Referenced by llvm::decomposeBitTestICmp(), llvm::InstCombinerImpl::foldICmpBinOp(), hoistMinMax(), sinkMinMaxInBB(), and llvm::InstCombinerImpl::visitAdd().
isImpliedByMatchingCmp()
std::optional< bool > ICmpInst::isImpliedByMatchingCmp (CmpPredicate Pred1, CmpPredicate Pred2) static
Determine if Pred1 implies Pred2 is true, false, or if nothing can be inferred about the implication, when two compares have matching operands.
Definition at line 3988 of file Instructions.cpp.
References isImpliedFalseByMatchingCmp(), and isImpliedTrueByMatchingCmp().
Referenced by llvm::sandboxir::ICmpInst::isImpliedByMatchingCmp(), and isImpliedCondICmps().
isLE()
bool llvm::ICmpInst::isLE (Predicate P) inline static
Return true if the predicate is SLE or ULE.
Definition at line 1366 of file Instructions.h.
References llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_ULE, and P.
Referenced by llvm::decomposeBitTestICmp(), llvm::InstCombinerImpl::foldICmpBinOp(), hoistMinMax(), and sinkMinMaxInBB().
isLT()
bool llvm::ICmpInst::isLT (Predicate P) inline static
Return true if the predicate is SLT or ULT.
Definition at line 1354 of file Instructions.h.
References llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULT, and P.
Referenced by llvm::InstCombinerImpl::foldICmpBinOp(), hoistMinMax(), sinkMinMaxInBB(), and llvm::InstCombinerImpl::visitAdd().
isRelational() [1/2]
bool llvm::ICmpInst::isRelational () const inline
Return true if the predicate is relational (not EQ or NE).
Definition at line 1336 of file Instructions.h.
References isEquality().
Referenced by llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::ScalarEvolution::getLoopInvariantExitCondDuringFirstIterationsImpl(), hoistMinMax(), insertCandidatesWithPendingInjections(), IsKnownPredicateViaAddRecStart(), isSignTest(), simplifyICmpWithBinOp(), and sinkMinMaxInBB().
isRelational() [2/2]
bool llvm::ICmpInst::isRelational (Predicate P) inline static
Return true if the predicate is relational (not EQ or NE).
Definition at line 1342 of file Instructions.h.
References isEquality(), and P.
predicates()
auto llvm::ICmpInst::predicates () inline static
Returns the sequence of all ICmp predicates.
Definition at line 1372 of file Instructions.h.
References llvm::CmpInst::ICmpPredicates().
Referenced by llvm::sandboxir::ICmpInst::predicates().
setSameSign()
void llvm::ICmpInst::setSameSign (bool B = true) inline
Definition at line 1305 of file Instructions.h.
References B(), and llvm::Value::SubclassOptionalData.
swapOperands()
void llvm::ICmpInst::swapOperands () inline
Exchange the two operands to this instruction in such a way that it does not modify the semantics of the instruction.
The predicate value may be changed to retain the same result if the predicate is order dependent (e.g. ult). Swap operands and adjust predicate.
Definition at line 1379 of file Instructions.h.
References llvm::CmpInst::getSwappedPredicate(), and llvm::CmpInst::setPredicate().
Friends And Related Symbol Documentation
Instruction
friend class Instruction friend
Iterator for Instructions in a `BasicBlock.
/ \Returns an sandboxir::Instruction & when derereferenced. class BBIterator { public: using difference_type = std::ptrdiff_t; using value_type = Instruction; using pointer = value_type *; using reference = value_type &; using iterator_category = std::bidirectional_iterator_tag;
private: llvm::BasicBlock *BB; llvm::BasicBlock::iterator It; Context *Ctx; LLVM_ABI pointer getInstr(llvm::BasicBlock::iterator It) const;
public: BBIterator() : BB(nullptr), Ctx(nullptr) {} BBIterator(llvm::BasicBlock <em>BB, llvm::BasicBlock::iterator It, Context *Ctx) : BB(BB), It(It), Ctx(Ctx) {} reference operator() const { return *getInstr(It); } LLVM_ABI BBIterator &operator++(); BBIterator operator++(int) { auto Copy = *this; ++*this; return Copy; } LLVM_ABI BBIterator &operator--(); BBIterator operator--(int) { auto Copy = *this; –*this; return Copy; } bool operator==(const BBIterator &Other) const { assert(Ctx == Other.Ctx && "BBIterators in different context!"); return It == Other.It; } bool operator!=(const BBIterator &Other) const { return !(*this == Other); } / \Returns the SBInstruction that corresponds to this iterator, or null if / the instruction is not found in the IR-to-SandboxIR tables. pointer get() const { return getInstr(It); } / \Returns the parent BB. LLVM_ABI BasicBlock *getNodeParent() const; };
/ Contains a list of sandboxir::Instruction's. class BasicBlock : public Value { / Builds a graph that contains all values in BB in their original form / i.e., no vectorization is taking place here. LLVM_ABI void buildBasicBlockFromLLVMIR(llvm::BasicBlock *LLVMBB); friend class Context; // For buildBasicBlockFromIR
Definition at line 1193 of file Instructions.h.
References cloneImpl(), ICmpInst(), Instruction, and LLVM_ABI.
Referenced by classof(), ICmpInst(), ICmpInst(), and Instruction.
The documentation for this class was generated from the following files:
include/llvm/IR/Instructions.h
lib/IR/Instructions.cpp