LLVM: llvm::SMECallAttrs Class Reference
llvm::SMECallAttrs Class Reference
SMECallAttrs is a utility class to hold the SMEAttrs for a callsite.
#include "Target/AArch64/Utils/AArch64SMEAttributes.h"
Public Member Functions
SMECallAttrs (SMEAttrs Caller, SMEAttrs Callee, SMEAttrs Callsite=SMEAttrs::Normal)
SMECallAttrs (const CallBase &CB)
SMEAttrs & caller ()
SMEAttrs & callee ()
SMEAttrs & callsite ()
SMEAttrs const & caller () const
SMEAttrs const & callee () const
SMEAttrs const & callsite () const
bool requiresSMChange () const
bool requiresLazySave () const
bool requiresPreservingZT0 () const
bool requiresDisablingZABeforeCall () const
bool requiresEnablingZAAfterCall () const
bool requiresPreservingAllZAState () const
Detailed Description
SMECallAttrs is a utility class to hold the SMEAttrs for a callsite.
It has interfaces to query whether a streaming mode change or lazy-save mechanism is required when going from one function to another (e.g. through a call).
Definition at line 155 of file AArch64SMEAttributes.h.
Constructor & Destructor Documentation
SMECallAttrs() [1/2]
llvm::SMECallAttrs::SMECallAttrs (SMEAttrs Caller, SMEAttrs Callee, SMEAttrs Callsite = SMEAttrs::Normal) inline
Definition at line 162 of file AArch64SMEAttributes.h.
References llvm::SMEAttrs::Normal.
Referenced by callee().
SMECallAttrs() [2/2]
SMECallAttrs::SMECallAttrs (const CallBase & CB)
Definition at line 113 of file AArch64SMEAttributes.cpp.
References assert(), llvm::CallBase::getCalledFunction(), getFunction(), llvm::isIndirectCall(), llvm::Normal, and llvm::SMEAttrs::Yes.
Member Function Documentation
callee() [1/2]
SMEAttrs & llvm::SMECallAttrs::callee () inline
Definition at line 169 of file AArch64SMEAttributes.h.
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), callee(), llvm::AArch64TTIImpl::getInlineCallPenalty(), getSMToggleCondition(), requiresDisablingZABeforeCall(), requiresLazySave(), requiresPreservingAllZAState(), requiresPreservingZT0(), and requiresSMChange().
callee() [2/2]
SMEAttrs const & llvm::SMECallAttrs::callee () const inline
Definition at line 172 of file AArch64SMEAttributes.h.
References callee(), and SMECallAttrs().
caller() [1/2]
SMEAttrs & llvm::SMECallAttrs::caller () inline
Definition at line 168 of file AArch64SMEAttributes.h.
Referenced by llvm::AArch64TTIImpl::getInlineCallPenalty(), getSMToggleCondition(), requiresDisablingZABeforeCall(), requiresLazySave(), requiresPreservingAllZAState(), requiresPreservingZT0(), and requiresSMChange().
caller() [2/2]
SMEAttrs const & llvm::SMECallAttrs::caller () const inline
Definition at line 171 of file AArch64SMEAttributes.h.
callsite() [1/2]
SMEAttrs & llvm::SMECallAttrs::callsite () inline
Definition at line 170 of file AArch64SMEAttributes.h.
Referenced by requiresPreservingZT0().
callsite() [2/2]
SMEAttrs const & llvm::SMECallAttrs::callsite () const inline
Definition at line 175 of file AArch64SMEAttributes.h.
requiresDisablingZABeforeCall()
bool llvm::SMECallAttrs::requiresDisablingZABeforeCall () const inline
Definition at line 191 of file AArch64SMEAttributes.h.
References callee(), caller(), llvm::SMEAttrs::hasPrivateZAInterface(), llvm::SMEAttrs::hasZAState(), llvm::SMEAttrs::hasZT0State(), and llvm::SMEAttrs::isSMEABIRoutine().
Referenced by requiresEnablingZAAfterCall().
requiresEnablingZAAfterCall()
bool llvm::SMECallAttrs::requiresEnablingZAAfterCall () const inline
Definition at line 196 of file AArch64SMEAttributes.h.
References requiresDisablingZABeforeCall(), and requiresLazySave().
requiresLazySave()
bool llvm::SMECallAttrs::requiresLazySave () const inline
Definition at line 181 of file AArch64SMEAttributes.h.
References callee(), caller(), llvm::SMEAttrs::hasPrivateZAInterface(), llvm::SMEAttrs::hasZAState(), and llvm::SMEAttrs::isSMEABIRoutine().
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), llvm::AArch64TargetLowering::fallBackToDAGISel(), and requiresEnablingZAAfterCall().
requiresPreservingAllZAState()
bool llvm::SMECallAttrs::requiresPreservingAllZAState () const inline
Definition at line 200 of file AArch64SMEAttributes.h.
References callee(), caller(), llvm::SMEAttrs::hasAgnosticZAInterface(), and llvm::SMEAttrs::isSMEABIRoutine().
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), and llvm::AArch64TargetLowering::fallBackToDAGISel().
requiresPreservingZT0()
bool llvm::SMECallAttrs::requiresPreservingZT0 () const inline
Definition at line 186 of file AArch64SMEAttributes.h.
References callee(), caller(), callsite(), llvm::SMEAttrs::hasAgnosticZAInterface(), llvm::SMEAttrs::hasUndefZT0(), llvm::SMEAttrs::hasZT0State(), and llvm::SMEAttrs::sharesZT0().
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), and llvm::AArch64TargetLowering::fallBackToDAGISel().
requiresSMChange()
bool SMECallAttrs::requiresSMChange () const
Returns
true if a call from Caller -> Callee requires a change in streaming mode.
Definition at line 96 of file AArch64SMEAttributes.cpp.
References callee(), and caller().
Referenced by llvm::AArch64TTIImpl::areInlineCompatible(), llvm::AArch64TargetLowering::fallBackToDAGISel(), and llvm::AArch64TTIImpl::getInlineCallPenalty().
The documentation for this class was generated from the following files:
lib/Target/AArch64/Utils/AArch64SMEAttributes.h
lib/Target/AArch64/Utils/AArch64SMEAttributes.cpp