LLVM: llvm::AArch64AuthMCExpr Class Reference
llvm::AArch64AuthMCExpr Class Reference final
#include "Target/AArch64/MCTargetDesc/AArch64MCAsmInfo.h"
Public Member Functions
AArch64PACKey::ID getKey () const
uint16_t getDiscriminator () const
bool hasAddressDiversity () const
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
Public Member Functions inherited from llvm::MCSpecifierExpr
Spec getSpecifier () const
const MCExpr * getSubExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
LLVM_ABI void dump () const
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res) const
Try to evaluate the expression to an absolute value.
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
LLVM_ABI bool evaluateKnownAbsolute (int64_t &Res, const MCAssembler &Asm) const
Aggressive variant of evaluateAsRelocatable when relocations are unavailable (e.g.
LLVM_ABI bool evaluateAsRelocatable (MCValue &Res, const MCAssembler *Asm) const
Try to evaluate the expression to a relocatable value, i.e.
LLVM_ABI bool evaluateAsValue (MCValue &Res, const MCAssembler &Asm) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
LLVM_ABI MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static const AArch64AuthMCExpr * create (const MCExpr *Expr, uint16_t Discriminator, AArch64PACKey::ID Key, bool HasAddressDiversity, MCContext &Ctx, SMLoc Loc=SMLoc())
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCSpecifierExpr
static const MCSpecifierExpr * create (const MCExpr *Expr, Spec S, MCContext &Ctx, SMLoc Loc=SMLoc())
static const MCSpecifierExpr * create (const MCSymbol *Sym, Spec S, MCContext &Ctx, SMLoc Loc=SMLoc())
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCExpr
static LLVM_ABI bool evaluateSymbolicAdd (const MCAssembler *, bool, const MCValue &, const MCValue &, MCValue &)
Additional Inherited Members
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary , Constant , SymbolRef , Unary ,
Specifier , Target
}
Protected Types inherited from llvm::MCExpr
using Spec = uint16_t
Protected Member Functions inherited from llvm::MCSpecifierExpr
MCSpecifierExpr (const MCExpr *Expr, Spec S, SMLoc Loc=SMLoc())
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
LLVM_ABI bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, bool InSet) const
unsigned getSubclassData () const
Protected Attributes inherited from llvm::MCSpecifierExpr
const MCExpr * Expr
Detailed Description
Definition at line 197 of file AArch64MCAsmInfo.h.
Member Function Documentation
classof()
bool llvm::AArch64AuthMCExpr::classof (const MCExpr * E) inline static
Definition at line 222 of file AArch64MCAsmInfo.h.
References llvm::dyn_cast(), E(), llvm::AArch64::S_AUTH, and llvm::AArch64::S_AUTHADDR.
create()
const AArch64AuthMCExpr * AArch64AuthMCExpr::create (const MCExpr * Expr, uint16_t Discriminator, AArch64PACKey::ID Key, bool HasAddressDiversity, MCContext & Ctx, SMLoc Loc = SMLoc()) static
Definition at line 17 of file AArch64MCExpr.cpp.
References llvm::MCSpecifierExpr::Expr.
Referenced by llvm::AArch64TargetStreamer::emitAuthValue(), and getAuthPtrSlotSymbolHelper().
getDiscriminator()
uint16_t llvm::AArch64AuthMCExpr::getDiscriminator () const inline
Definition at line 215 of file AArch64MCAsmInfo.h.
getKey()
AArch64PACKey::ID llvm::AArch64AuthMCExpr::getKey () const inline
Definition at line 214 of file AArch64MCAsmInfo.h.
hasAddressDiversity()
bool llvm::AArch64AuthMCExpr::hasAddressDiversity () const inline
Definition at line 216 of file AArch64MCAsmInfo.h.
References llvm::MCSpecifierExpr::getSpecifier(), and llvm::AArch64::S_AUTHADDR.
Referenced by print().
print()
void AArch64AuthMCExpr::print (raw_ostream & OS, const MCAsmInfo * MAI) const
Definition at line 168 of file AArch64MCAsmInfo.cpp.
References llvm::AArch64PACKeyIDToString(), llvm::MCSpecifierExpr::getSubExpr(), hasAddressDiversity(), llvm::isa(), and llvm::MCAsmInfo::printExpr().
The documentation for this class was generated from the following files:
lib/Target/AArch64/MCTargetDesc/AArch64MCAsmInfo.h
lib/Target/AArch64/MCTargetDesc/AArch64MCAsmInfo.cpp
lib/Target/AArch64/MCTargetDesc/AArch64MCExpr.cpp