LLVM: llvm::CGDataOStream Class Reference
llvm::CGDataOStream Class Reference
A wrapper class to abstract writer stream with support of bytes back patching.
#include "llvm/CGData/CodeGenDataWriter.h"
Public Member Functions
CGDataOStream (raw_fd_ostream &FD)
CGDataOStream (raw_string_ostream &STR)
CGDataOStream (raw_svector_ostream &SVEC)
uint64_t tell ()
void write (uint64_t V)
void write32 (uint32_t V)
void write8 (uint8_t V)
LLVM_ABI void patch (ArrayRef< CGDataPatchItem > P)
Public Attributes
OStreamKind Kind
raw_ostream & OS
support::endian::Writer LE
Detailed Description
A wrapper class to abstract writer stream with support of bytes back patching.
Definition at line 28 of file CodeGenDataWriter.h.
Constructor & Destructor Documentation
CGDataOStream() [1/3]
llvm::CGDataOStream::CGDataOStream (raw_fd_ostream & FD) inline
Definition at line 36 of file CodeGenDataWriter.h.
References Kind, LE, llvm::little, and OS.
CGDataOStream() [2/3]
llvm::CGDataOStream::CGDataOStream (raw_string_ostream & STR) inline
Definition at line 38 of file CodeGenDataWriter.h.
References Kind, LE, llvm::little, and OS.
CGDataOStream() [3/3]
llvm::CGDataOStream::CGDataOStream (raw_svector_ostream & SVEC) inline
Definition at line 40 of file CodeGenDataWriter.h.
References Kind, LE, llvm::little, and OS.
Member Function Documentation
patch()
void CGDataOStream::patch (ArrayRef< CGDataPatchItem > P)
Definition at line 19 of file CodeGenDataWriter.cpp.
References llvm::support::endian::byte_swap(), llvm::Data, I, Kind, OS, P, llvm::raw_pwrite_stream::pwrite(), llvm::raw_fd_ostream::seek(), llvm::raw_string_ostream::str(), llvm::raw_ostream::tell(), and write().
Referenced by llvm::GlobalMergeFunc::emitFunctionMap().
tell()
uint64_t llvm::CGDataOStream::tell () inline
Definition at line 44 of file CodeGenDataWriter.h.
References OS.
write()
void llvm::CGDataOStream::write (uint64_t V) inline
Definition at line 45 of file CodeGenDataWriter.h.
References LE.
Referenced by patch().
write32()
void llvm::CGDataOStream::write32 (uint32_t V) inline
Definition at line 46 of file CodeGenDataWriter.h.
References LE.
write8()
void llvm::CGDataOStream::write8 (uint8_t V) inline
Definition at line 47 of file CodeGenDataWriter.h.
References LE.
Member Data Documentation
Kind
OStreamKind llvm::CGDataOStream::Kind
Definition at line 54 of file CodeGenDataWriter.h.
Referenced by CGDataOStream(), CGDataOStream(), CGDataOStream(), and patch().
LE
support::endian::Writer llvm::CGDataOStream::LE
Definition at line 56 of file CodeGenDataWriter.h.
Referenced by CGDataOStream(), CGDataOStream(), CGDataOStream(), write(), write32(), and write8().
OS
raw_ostream& llvm::CGDataOStream::OS
Definition at line 55 of file CodeGenDataWriter.h.
Referenced by CGDataOStream(), CGDataOStream(), CGDataOStream(), patch(), and tell().
The documentation for this class was generated from the following files:
include/llvm/CGData/CodeGenDataWriter.h
lib/CGData/CodeGenDataWriter.cpp