LLVM: llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass Class Reference
llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass Class Reference
#include "llvm/Passes/CodeGenPassBuilder.h"
Public Member Functions
AddMachinePass (ModulePassManager &MPM, const DerivedT &PB)
~AddMachinePass ()
template<typename PassT>
void operator() (PassT &&Pass, bool Force=false, StringRef Name=PassT::name())
void requireCGSCCOrder ()
Setting this will add passes to the CGSCC pass manager.
void stopAddingInCGSCCOrder ()
Stop adding passes to the CGSCC pass manager.
Detailed Description
template<typename DerivedT, typename TargetMachineT>
class llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass
Definition at line 273 of file CodeGenPassBuilder.h.
Constructor & Destructor Documentation
AddMachinePass()
template<typename DerivedT, typename TargetMachineT> llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::AddMachinePass (ModulePassManager & MPM, const DerivedT & PB) inline
Definition at line 275 of file CodeGenPassBuilder.h.
~AddMachinePass()
template<typename DerivedT, typename TargetMachineT> llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::~AddMachinePass () inline
Definition at line 277 of file CodeGenPassBuilder.h.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::createCGSCCToFunctionPassAdaptor(), llvm::createFunctionToMachineFunctionPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), and llvm::createModuleToPostOrderCGSCCPassAdaptor().
Member Function Documentation
operator()()
template<typename DerivedT, typename TargetMachineT> template<typename PassT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::operator() (PassT && Pass, bool Force = false, StringRef Name = PassT::name()) inline
Definition at line 292 of file CodeGenPassBuilder.h.
References llvm::CallingConv::C.
requireCGSCCOrder()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::requireCGSCCOrder () inline
Setting this will add passes to the CGSCC pass manager.
Definition at line 315 of file CodeGenPassBuilder.h.
stopAddingInCGSCCOrder()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::stopAddingInCGSCCOrder () inline
Stop adding passes to the CGSCC pass manager.
Existing passes won't be removed.
Definition at line 324 of file CodeGenPassBuilder.h.
The documentation for this class was generated from the following file:
include/llvm/Passes/CodeGenPassBuilder.h