LLVM: llvm::MCInstBuilder Class Reference
llvm::MCInstBuilder Class Reference
#include "llvm/MC/MCInstBuilder.h"
Public Member Functions
MCInstBuilder (unsigned Opcode)
Create a new MCInstBuilder for an MCInst with a specific opcode.
MCInstBuilder & setLoc (SMLoc SM)
Set the location.
MCInstBuilder & addReg (MCRegister Reg)
Add a new register operand.
MCInstBuilder & addImm (int64_t Val)
Add a new integer immediate operand.
MCInstBuilder & addSFPImm (uint32_t Val)
Add a new single floating point immediate operand.
MCInstBuilder & addDFPImm (uint64_t Val)
Add a new floating point immediate operand.
MCInstBuilder & addExpr (const MCExpr *Val)
Add a new MCExpr operand.
MCInstBuilder & addInst (const MCInst *Val)
Add a new MCInst operand.
MCInstBuilder & addOperand (const MCOperand &Op)
Add an operand.
operator MCInst & ()
Detailed Description
Definition at line 21 of file MCInstBuilder.h.
Constructor & Destructor Documentation
MCInstBuilder()
llvm::MCInstBuilder::MCInstBuilder (unsigned Opcode) inline
Create a new MCInstBuilder for an MCInst with a specific opcode.
Definition at line 26 of file MCInstBuilder.h.
Referenced by addDFPImm(), addExpr(), addImm(), addInst(), addOperand(), addReg(), addSFPImm(), and setLoc().
Member Function Documentation
addDFPImm()
MCInstBuilder & llvm::MCInstBuilder::addDFPImm (uint64_t Val) inline
Add a new floating point immediate operand.
Definition at line 55 of file MCInstBuilder.h.
References addOperand(), llvm::MCOperand::createDFPImm(), and MCInstBuilder().
addExpr()
MCInstBuilder & llvm::MCInstBuilder::addExpr (const MCExpr * Val) inline
Add a new MCExpr operand.
Definition at line 61 of file MCInstBuilder.h.
References addOperand(), llvm::MCOperand::createExpr(), and MCInstBuilder().
Referenced by llvm::ARMAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), and llvm::X86AsmPrinter::emitInstruction().
addImm()
MCInstBuilder & llvm::MCInstBuilder::addImm (int64_t Val) inline
Add a new integer immediate operand.
Definition at line 43 of file MCInstBuilder.h.
References addOperand(), llvm::MCOperand::createImm(), and MCInstBuilder().
Referenced by llvm::ARMAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::RISCVMatInt::generateMCInstSeq(), llvm::AArch64InstrInfo::getNop(), llvm::HexagonInstrInfo::getNop(), llvm::LoongArchInstrInfo::getNop(), llvm::MipsInstrInfo::getNop(), llvm::RISCVInstrInfo::getNop(), llvm::Thumb1InstrInfo::getNop(), llvm::Thumb2InstrInfo::getNop(), lowerRIEfLow(), lowerRIHigh(), lowerRILow(), lowerSubvectorLoad(), lowerSubvectorStore(), lowerVecEltExtraction(), lowerVecEltInsertion(), and llvm::ARMAsmPrinter::runOnMachineFunction().
addInst()
MCInstBuilder & llvm::MCInstBuilder::addInst (const MCInst * Val) inline
Add a new MCInst operand.
Definition at line 67 of file MCInstBuilder.h.
References addOperand(), llvm::MCOperand::createInst(), and MCInstBuilder().
Referenced by llvm::HexagonInstrInfo::getNop().
addOperand()
MCInstBuilder & llvm::MCInstBuilder::addOperand (const MCOperand & Op) inline
Add an operand.
Definition at line 73 of file MCInstBuilder.h.
References addOperand(), and MCInstBuilder().
Referenced by addDFPImm(), addExpr(), addImm(), addInst(), addOperand(), addReg(), and addSFPImm().
addReg()
MCInstBuilder & llvm::MCInstBuilder::addReg (MCRegister Reg) inline
Add a new register operand.
Definition at line 37 of file MCInstBuilder.h.
References addOperand(), llvm::MCOperand::createReg(), MCInstBuilder(), and Reg.
Referenced by llvm::ARMAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::RISCVMatInt::generateMCInstSeq(), llvm::LoongArchInstrInfo::getNop(), llvm::MipsInstrInfo::getNop(), llvm::RISCVInstrInfo::getNop(), llvm::Thumb1InstrInfo::getNop(), llvm::Thumb2InstrInfo::getNop(), lowerRIEfLow(), lowerRIHigh(), lowerRILow(), lowerSubvectorLoad(), lowerSubvectorStore(), lowerVecEltExtraction(), lowerVecEltInsertion(), and llvm::ARMAsmPrinter::runOnMachineFunction().
addSFPImm()
MCInstBuilder & llvm::MCInstBuilder::addSFPImm (uint32_t Val) inline
Add a new single floating point immediate operand.
Definition at line 49 of file MCInstBuilder.h.
References addOperand(), llvm::MCOperand::createSFPImm(), and MCInstBuilder().
operator MCInst &()
llvm::MCInstBuilder::operator MCInst & () inline
Definition at line 78 of file MCInstBuilder.h.
setLoc()
MCInstBuilder & llvm::MCInstBuilder::setLoc (SMLoc SM) inline
Set the location.
Definition at line 31 of file MCInstBuilder.h.
References MCInstBuilder(), and setLoc().
Referenced by setLoc().
The documentation for this class was generated from the following file:
include/llvm/MC/MCInstBuilder.h