LLVM: llvm::LegalizationArtifactCombiner Class Reference
llvm::LegalizationArtifactCombiner Class Reference
#include "llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h"
Classes
class ArtifactValueFinder
This class provides utilities for finding source registers of specific bit ranges in an artifact.
Public Member Functions
LegalizationArtifactCombiner (MachineIRBuilder &B, MachineRegisterInfo &MRI, const LegalizerInfo &LI, GISelValueTracking *VT=nullptr)
bool tryCombineAnyExt (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs, GISelObserverWrapper &Observer)
bool tryCombineZExt (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs, GISelObserverWrapper &Observer)
bool tryCombineSExt (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs, GISelObserverWrapper &Observer)
bool tryCombineTrunc (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs, GISelObserverWrapper &Observer)
bool tryFoldImplicitDef (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs, GISelObserverWrapper &Observer)
Try to fold G_[ASZ]EXT (G_IMPLICIT_DEF).
bool tryFoldUnmergeCast (MachineInstr &MI, MachineInstr &CastMI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryCombineUnmergeValues (GUnmerge &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs, GISelChangeObserver &Observer)
bool tryCombineExtract (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs)
bool tryCombineInstruction (MachineInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, GISelObserverWrapper &WrapperObserver)
Try to combine away MI.
Static Public Member Functions
static bool canFoldMergeOpcode (unsigned MergeOp, unsigned ConvertOp, LLT OpTy, LLT DestTy)
static void replaceRegOrBuildCopy (Register DstReg, Register SrcReg, MachineRegisterInfo &MRI, MachineIRBuilder &Builder, SmallVectorImpl< Register > &UpdatedDefs, GISelChangeObserver &Observer)
Try to replace DstReg with SrcReg or build a COPY instruction depending on the register constraints.
static unsigned getDefIndex (const MachineInstr &MI, Register SearchDef)
Return the operand index in MI that defines Def.
Detailed Description
Definition at line 35 of file LegalizationArtifactCombiner.h.
Constructor & Destructor Documentation
LegalizationArtifactCombiner()
llvm::LegalizationArtifactCombiner::LegalizationArtifactCombiner (MachineIRBuilder & B, MachineRegisterInfo & MRI, const LegalizerInfo & LI, GISelValueTracking * VT = nullptr) inline
Definition at line 54 of file LegalizationArtifactCombiner.h.
References B().
Member Function Documentation
canFoldMergeOpcode()
bool llvm::LegalizationArtifactCombiner::canFoldMergeOpcode (unsigned MergeOp, unsigned ConvertOp, LLT OpTy, LLT DestTy) inline static
Definition at line 516 of file LegalizationArtifactCombiner.h.
References llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), and llvm::LLT::isVector().
getDefIndex()
unsigned llvm::LegalizationArtifactCombiner::getDefIndex (const MachineInstr & MI, Register SearchDef) inline static
Return the operand index in MI that defines Def.
Definition at line 595 of file LegalizationArtifactCombiner.h.
References MI.
Referenced by tryCombineUnmergeValues().
replaceRegOrBuildCopy()
void llvm::LegalizationArtifactCombiner::replaceRegOrBuildCopy (Register DstReg, Register SrcReg, MachineRegisterInfo & MRI, MachineIRBuilder & Builder, SmallVectorImpl< Register > & UpdatedDefs, GISelChangeObserver & Observer) inline static
Try to replace DstReg with SrcReg or build a COPY instruction depending on the register constraints.
Definition at line 570 of file LegalizationArtifactCombiner.h.
References llvm::canReplaceReg(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and UseMI.
Referenced by tryCombineAnyExt(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::tryCombineMergeLike(), tryCombineSExt(), tryCombineTrunc(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::tryCombineUnmergeDefs(), tryCombineUnmergeValues(), tryCombineZExt(), and tryFoldImplicitDef().
tryCombineAnyExt()
bool llvm::LegalizationArtifactCombiner::tryCombineAnyExt (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs, GISelObserverWrapper & Observer) inline
Definition at line 59 of file LegalizationArtifactCombiner.h.
References assert(), llvm::dbgs(), llvm::DebugLoc::getMergedLocation(), llvm::MachineInstr::getOpcode(), llvm::LLT::getSizeInBits(), LLVM_DEBUG, llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GAnyExt(), llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), replaceRegOrBuildCopy(), and tryFoldImplicitDef().
Referenced by tryCombineInstruction().
tryCombineExtract()
bool llvm::LegalizationArtifactCombiner::tryCombineExtract (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 1272 of file LegalizationArtifactCombiner.h.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::isa(), MI, llvm::Offset, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by tryCombineInstruction().
tryCombineInstruction()
bool llvm::LegalizationArtifactCombiner::tryCombineInstruction (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, GISelObserverWrapper & WrapperObserver) inline
Try to combine away MI.
Returns true if it combined away the MI. Adds instructions that are dead as a result of the combine into DeadInsts, which can include MI.
Definition at line 1325 of file LegalizationArtifactCombiner.h.
References assert(), llvm::cast(), Changed, llvm::GISelObserverWrapper::changedInstr(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::Register::isVirtual(), MI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), tryCombineAnyExt(), tryCombineExtract(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::tryCombineMergeLike(), tryCombineSExt(), tryCombineTrunc(), tryCombineUnmergeValues(), and tryCombineZExt().
Referenced by llvm::Legalizer::legalizeMachineFunction().
tryCombineSExt()
bool llvm::LegalizationArtifactCombiner::tryCombineSExt (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs, GISelObserverWrapper & Observer) inline
Definition at line 193 of file LegalizationArtifactCombiner.h.
References assert(), llvm::dbgs(), llvm::MachineInstr::getOpcode(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), LLVM_DEBUG, llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), replaceRegOrBuildCopy(), and tryFoldImplicitDef().
Referenced by tryCombineInstruction().
tryCombineTrunc()
bool llvm::LegalizationArtifactCombiner::tryCombineTrunc (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs, GISelObserverWrapper & Observer) inline
Definition at line 258 of file LegalizationArtifactCombiner.h.
References assert(), llvm::dbgs(), llvm::dyn_cast(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::findValueFromDef(), llvm::LLT::getSizeInBits(), llvm::LLT::isScalar(), LLVM_DEBUG, llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and replaceRegOrBuildCopy().
Referenced by tryCombineInstruction().
tryCombineUnmergeValues()
bool llvm::LegalizationArtifactCombiner::tryCombineUnmergeValues (GUnmerge & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs, GISelChangeObserver & Observer) inline
Definition at line 1064 of file LegalizationArtifactCombiner.h.
References llvm::LegalizeActionStep::Action, llvm::dyn_cast(), llvm::LegalizeActions::FewerElements, llvm::getDefIgnoringCopies(), getDefIndex(), I, llvm::LLT::isVector(), llvm::LegalizeActions::Legal, llvm::LegalizeActions::Lower, MI, llvm::LegalizeActions::NarrowScalar, replaceRegOrBuildCopy(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::tryCombineUnmergeDefs(), llvm::LegalizeActionStep::TypeIdx, and llvm::LegalizeActions::Unsupported.
Referenced by combineAwayG_UNMERGE_VALUES(), and tryCombineInstruction().
tryCombineZExt()
bool llvm::LegalizationArtifactCombiner::tryCombineZExt (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs, GISelObserverWrapper & Observer) inline
Definition at line 118 of file LegalizationArtifactCombiner.h.
References assert(), llvm::GISelObserverWrapper::changedInstr(), llvm::GISelObserverWrapper::changingInstr(), llvm::dbgs(), llvm::APInt::getAllOnes(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), LLVM_DEBUG, llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), replaceRegOrBuildCopy(), tryFoldImplicitDef(), and llvm::APInt::zext().
Referenced by tryCombineInstruction().
tryFoldImplicitDef()
bool llvm::LegalizationArtifactCombiner::tryFoldImplicitDef (MachineInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs, GISelObserverWrapper & Observer) inline
Try to fold G_[ASZ]EXT (G_IMPLICIT_DEF).
Definition at line 377 of file LegalizationArtifactCombiner.h.
References assert(), llvm::dbgs(), DefMI, llvm::getOpcodeDef(), LLVM_DEBUG, MI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and replaceRegOrBuildCopy().
Referenced by tryCombineAnyExt(), tryCombineSExt(), and tryCombineZExt().
tryFoldUnmergeCast()
bool llvm::LegalizationArtifactCombiner::tryFoldUnmergeCast (MachineInstr & MI, MachineInstr & CastMI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs) inline
Definition at line 418 of file LegalizationArtifactCombiner.h.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::LLT::changeElementCount(), llvm::ElementCount::getFixed(), llvm::LLT::getNumElements(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarType(), llvm::LLT::getSizeInBits(), I, llvm::LLT::isScalar(), llvm::LLT::isVector(), MI, llvm::LegalizeActions::MoreElements, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h