LLVM: llvm::Resolver Class Reference
llvm::Resolver Class Reference abstract
Interface for looking up the initializer for a variable name, used by Init::resolveReferences.
#include "llvm/TableGen/Record.h"
Public Member Functions
Resolver (const Record *CurRec)
virtual ~Resolver ()=default
const Record * getCurrentRecord () const
virtual const Init * resolve (const Init *VarName)=0
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
virtual bool keepUnsetBits () const
bool isFinal () const
void setFinal (bool Final)
Detailed Description
Interface for looking up the initializer for a variable name, used by Init::resolveReferences.
Definition at line 2194 of file Record.h.
Constructor & Destructor Documentation
Resolver()
llvm::Resolver::Resolver (const Record * CurRec) inline explicit
Definition at line 2199 of file Record.h.
Referenced by llvm::HasReferenceResolver::HasReferenceResolver(), llvm::MapResolver::MapResolver(), llvm::RecordResolver::RecordResolver(), llvm::ShadowResolver::ShadowResolver(), and llvm::TrackUnresolvedResolver::TrackUnresolvedResolver().
~Resolver()
virtual llvm::Resolver::~Resolver () virtual default
Member Function Documentation
getCurrentRecord()
const Record * llvm::Resolver::getCurrentRecord () const inline
Definition at line 2202 of file Record.h.
Referenced by llvm::RecordResolver::resolve(), llvm::ShadowResolver::ShadowResolver(), and llvm::TrackUnresolvedResolver::TrackUnresolvedResolver().
isFinal()
bool llvm::Resolver::isFinal () const inline
Definition at line 2216 of file Record.h.
keepUnsetBits()
virtual bool llvm::Resolver::keepUnsetBits () const inline virtual
Reimplemented in llvm::RecordResolver.
Definition at line 2211 of file Record.h.
resolve()
virtual const Init * llvm::Resolver::resolve (const Init * VarName) pure virtual
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Implemented in llvm::HasReferenceResolver, llvm::MapResolver, llvm::RecordResolver, llvm::ShadowResolver, and llvm::TrackUnresolvedResolver.
setFinal()
void llvm::Resolver::setFinal (bool Final) inline
Definition at line 2218 of file Record.h.
Referenced by llvm::ShadowResolver::ShadowResolver().
The documentation for this class was generated from the following file:
include/llvm/TableGen/Record.h