LLVM: llvm::sandboxir::FunctionPass Class Reference
llvm::sandboxir::FunctionPass Class Reference abstract
A pass that runs on a sandbox::Function.
#include "llvm/SandboxIR/Pass.h"
Public Member Functions
FunctionPass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual bool runOnFunction (Function &F, const Analyses &A)=0
\Returns true if it modifies F.
Public Member Functions inherited from llvm::sandboxir::Pass
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()
StringRef getName () const
\Returns the name of the pass.
virtual void print (raw_ostream &OS) const
virtual LLVM_DUMP_METHOD void dump () const
virtual void printPipeline (raw_ostream &OS) const
Similar to print() but adds a newline. Used for testing.
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::Pass
const std::string Name
The pass name.
Detailed Description
A pass that runs on a sandbox::Function.
Definition at line 75 of file Pass.h.
Constructor & Destructor Documentation
FunctionPass()
llvm::sandboxir::FunctionPass::FunctionPass (StringRef Name) inline
Name can't contain any spaces or start with '-'.
Definition at line 78 of file Pass.h.
References llvm::sandboxir::Pass::Name, and llvm::sandboxir::Pass::Pass().
Referenced by llvm::sandboxir::RegionsFromBBs::RegionsFromBBs(), llvm::sandboxir::RegionsFromMetadata::RegionsFromMetadata(), and llvm::sandboxir::SeedCollection::SeedCollection().
Member Function Documentation
runOnFunction()
virtual bool llvm::sandboxir::FunctionPass::runOnFunction (Function & F, const Analyses & A) pure virtual
\Returns true if it modifies F.
Implemented in llvm::sandboxir::FunctionPassManager, llvm::sandboxir::RegionsFromBBs, llvm::sandboxir::RegionsFromMetadata, and llvm::sandboxir::SeedCollection.
References A(), and F.
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Pass.h