LLVM: llvm::PreservedAnalyses Class Reference
llvm::PreservedAnalyses Class Reference
A set of analyses that are preserved following a run of a transformation pass.
#include "llvm/IR/Analysis.h"
Classes
class PreservedAnalysisChecker
A checker object that makes it easy to query for whether an analysis or some set covering it is preserved.
Public Member Functions
template<typename AnalysisT>
PreservedAnalyses & preserve ()
Mark an analysis as preserved.
PreservedAnalyses & preserve (AnalysisKey *ID)
Given an analysis's ID, mark the analysis as preserved, adding it to the set.
template<typename AnalysisSetT>
PreservedAnalyses & preserveSet ()
Mark an analysis set as preserved.
PreservedAnalyses & preserveSet (AnalysisSetKey *ID)
Mark an analysis set as preserved using its ID.
template<typename AnalysisT>
PreservedAnalyses & abandon ()
Mark an analysis as abandoned.
PreservedAnalyses & abandon (AnalysisKey *ID)
Mark an analysis as abandoned using its ID.
void intersect (const PreservedAnalyses &Arg)
Intersect this set with another in place.
void intersect (PreservedAnalyses &&Arg)
Intersect this set with a temporary other set in place.
template<typename AnalysisT>
PreservedAnalysisChecker getChecker () const
Build a checker for this PreservedAnalyses and the specified analysis type.
PreservedAnalysisChecker getChecker (AnalysisKey *ID) const
Build a checker for this PreservedAnalyses and the specified analysis ID.
bool areAllPreserved () const
Test whether all analyses are preserved (and none are abandoned).
template<typename AnalysisSetT>
bool allAnalysesInSetPreserved () const
Directly test whether a set of analyses is preserved.
bool allAnalysesInSetPreserved (AnalysisSetKey *SetID) const
Directly test whether a set of analyses is preserved.
Static Public Member Functions
static PreservedAnalyses none ()
Convenience factory function for the empty preserved set.
static PreservedAnalyses all ()
Construct a special preserved set that preserves all passes.
template<typename AnalysisSetT>
static PreservedAnalyses allInSet ()
Construct a preserved analyses object with a single preserved set.
Detailed Description
A set of analyses that are preserved following a run of a transformation pass.
Transformation passes build and return these objects to communicate which analyses are still valid after the transformation. For most passes this is fairly simple: if they don't change anything all analyses are preserved, otherwise only a short list of analyses that have been explicitly updated are preserved.
This class also lets transformation passes mark abstract sets of analyses as preserved. A transformation that (say) does not alter the CFG can indicate such by marking a particular AnalysisSetKey as preserved, and then analyses can query whether that AnalysisSetKey is preserved.
Finally, this class can represent an "abandoned" analysis, which is not preserved even if it would be covered by some abstract set of analyses.
Given a PreservedAnalyses object, an analysis will typically want to figure out whether it is preserved. In the example below, MyAnalysisType is preserved if it's not abandoned, and (a) it's explicitly marked as preserved, (b), the set AllAnalysesOn<MyIRUnit> is preserved, or (c) both AnalysisSetA and AnalysisSetB are preserved.
auto PAC = PA.getChecker<MyAnalysisType>();
if (PAC.preserved() || PAC.preservedSet<AllAnalysesOn<MyIRUnit>>() ||
    (PAC.preservedSet<AnalysisSetA>() &&
     PAC.preservedSet<AnalysisSetB>())) {
  // The analysis has been successfully preserved ...
}
Definition at line 112 of file Analysis.h.
Member Function Documentation
abandon() [1/2]
template<typename AnalysisT> PreservedAnalyses & llvm::PreservedAnalyses::abandon () inline
Mark an analysis as abandoned.
An abandoned analysis is not preserved, even if it is nominally covered by some other set or was previously explicitly marked as preserved.
Note that you can only abandon a specific analysis, not a set of analyses.
Definition at line 171 of file Analysis.h.
References abandon().
Referenced by abandon(), llvm::MLInlineAdvisor::onSuccessfulInlining(), llvm::AddressSanitizerPass::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::DataFlowSanitizerPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::InvalidateAnalysisPass< AnalysisT >::run(), llvm::IRCEPass::run(), llvm::LowerEmuTLSPass::run(), llvm::MemorySanitizerPass::run(), llvm::PGOCtxProfFlatteningPass::run(), and llvm::SanitizerCoveragePass::run().
abandon() [2/2]
PreservedAnalyses & llvm::PreservedAnalyses::abandon (AnalysisKey * ID) inline
Mark an analysis as abandoned using its ID.
An abandoned analysis is not preserved, even if it is nominally covered by some other set or was previously explicitly marked as preserved.
Note that you can only abandon a specific analysis, not a set of analyses.
Definition at line 183 of file Analysis.h.
all()
PreservedAnalyses llvm::PreservedAnalyses::all () inline static
Construct a special preserved set that preserves all passes.
Definition at line 118 of file Analysis.h.
References llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::MLInlineAdvisor::onSuccessfulInlining(), llvm::AAEvaluator::run(), llvm::ADCEPass::run(), llvm::AddDiscriminatorsPass::run(), llvm::AddressSanitizerPass::run(), llvm::AggressiveInstCombinePass::run(), llvm::AliasSetsPrinterPass::run(), llvm::AlignmentFromAssumptionsPass::run(), llvm::AlwaysInlinerPass::run(), llvm::AMDGPUAlwaysInlinePass::run(), llvm::AMDGPUAnnotateUniformValuesPass::run(), llvm::AMDGPUAtomicOptimizerPass::run(), llvm::AMDGPUAttributorPass::run(), llvm::AMDGPUCodeGenPreparePass::run(), llvm::AMDGPUCtorDtorLoweringPass::run(), llvm::AMDGPUExportKernelRuntimeHandlesPass::run(), llvm::AMDGPUImageIntrinsicOptimizerPass::run(), llvm::AMDGPUInsertDelayAluPass::run(), llvm::AMDGPULateCodeGenPreparePass::run(), llvm::AMDGPULowerBufferFatPointersPass::run(), llvm::AMDGPULowerKernelArgumentsPass::run(), llvm::AMDGPULowerKernelAttributesPass::run(), llvm::AMDGPULowerModuleLDSPass::run(), llvm::AMDGPUMarkLastScratchLoadPass::run(), llvm::AMDGPUPerfHintAnalysisPass::run(), llvm::AMDGPUPreloadKernArgPrologPass::run(), llvm::AMDGPUPreloadKernelArgumentsPass::run(), llvm::AMDGPUPrintfRuntimeBindingPass::run(), llvm::AMDGPUPromoteAllocaPass::run(), llvm::AMDGPUPromoteAllocaToVectorPass::run(), llvm::AMDGPUPromoteKernelArgumentsPass::run(), llvm::AMDGPURemoveIncompatibleFunctionsPass::run(), llvm::AMDGPUReserveWWMRegsPass::run(), llvm::AMDGPURewriteAGPRCopyMFMAPass::run(), llvm::AMDGPURewriteUndefForPHIPass::run(), llvm::AMDGPUSetWavePriorityPass::run(), llvm::AMDGPUSimplifyLibCallsPass::run(), llvm::AMDGPUSwLowerLDSPass::run(), llvm::AMDGPUUnifyDivergentExitNodesPass::run(), llvm::AMDGPUUnifyMetadataPass::run(), llvm::AMDGPUUseNativeCallsPass::run(), llvm::Annotation2MetadataPass::run(), llvm::AnnotationRemarksPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AssignmentTrackingPass::run(), llvm::AssignmentTrackingPass::run(), llvm::AssumeBuilderPass::run(), llvm::AssumeSimplifyPass::run(), llvm::AssumptionPrinterPass::run(), llvm::AtomicExpandPass::run(), llvm::AttributorCGSCCPass::run(), llvm::AttributorLightCGSCCPass::run(), llvm::AttributorLightPass::run(), llvm::AttributorPass::run(), llvm::BDCEPass::run(), llvm::BitcodeWriterPass::run(), llvm::BlockExtractorPass::run(), llvm::BlockFrequencyPrinterPass::run(), llvm::BoundsCheckingPass::run(), llvm::BPFAbstractMemberAccessPass::run(), llvm::BPFAdjustOptPass::run(), llvm::BPFASpaceCastSimplifyPass::run(), llvm::BPFIRPeepholePass::run(), llvm::BPFPreserveDITypePass::run(), llvm::BPFPreserveStaticOffsetPass::run(), llvm::BranchProbabilityPrinterPass::run(), llvm::BranchRelaxationPass::run(), llvm::BreakCriticalEdgesPass::run(), llvm::CallBrPreparePass::run(), llvm::CalledValuePropagationPass::run(), llvm::CallGraphDOTPrinterPass::run(), llvm::CallGraphPrinterPass::run(), llvm::CallGraphSCCsPrinterPass::run(), llvm::CallGraphViewerPass::run(), llvm::CallSiteSplittingPass::run(), llvm::CanonicalizeAliasesPass::run(), llvm::CanonicalizeFreezeInLoopsPass::run(), llvm::CFGOnlyPrinterPass::run(), llvm::CFGOnlyViewerPass::run(), llvm::CFGPrinterPass::run(), llvm::CFGSCCPrinterPass::run(), llvm::CFGuardPass::run(), llvm::CFGViewerPass::run(), llvm::CGProfilePass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CodeGenPreparePass::run(), llvm::ComplexDeinterleavingPass::run(), llvm::ConstantHoistingPass::run(), llvm::ConstantMergePass::run(), llvm::ConstraintEliminationPass::run(), llvm::ControlHeightReductionPass::run(), llvm::CoroAnnotationElidePass::run(), llvm::CoroCleanupPass::run(), llvm::CoroConditionalWrapper::run(), llvm::CoroEarlyPass::run(), llvm::CoroElidePass::run(), llvm::CoroSplitPass::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::CostModelPrinterPass::run(), llvm::CountVisitsPass::run(), llvm::CrossDSOCFIPass::run(), llvm::CtxProfAnalysisPrinterPass::run(), llvm::CycleInfoPrinterPass::run(), llvm::CycleInfoVerifierPass::run(), llvm::DataFlowSanitizerPass::run(), llvm::DCEPass::run(), llvm::DDGAnalysisPrinterPass::run(), llvm::DDGDotPrinterPass::run(), llvm::DeadArgumentEliminationPass::run(), llvm::DeadMachineInstructionElimPass::run(), llvm::DebugAssignmentTrackingPrinterPass::run(), llvm::DelinearizationPrinterPass::run(), llvm::DemandedBitsPrinterPass::run(), llvm::DependenceAnalysisPrinterPass::run(), llvm::DetectDeadLanesPass::run(), llvm::DevirtSCCRepeatedPass::run(), llvm::DFAJumpThreadingPass::run(), llvm::DivRemPairsPass::run(), llvm::DominanceFrontierPrinterPass::run(), llvm::DominatorTreePrinterPass::run(), llvm::DominatorTreeVerifierPass::run(), llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::run(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::run(), llvm::DSEPass::run(), llvm::DwarfEHPreparePass::run(), llvm::dxil::RootSignatureAnalysisPrinter::run(), llvm::dxil::ShaderFlagsAnalysisPrinter::run(), llvm::DXILCBufferAccess::run(), llvm::DXILDataScalarization::run(), llvm::DXILFinalizeLinkage::run(), llvm::DXILFlattenArrays::run(), llvm::DXILForwardHandleAccesses::run(), llvm::DXILIntrinsicExpansion::run(), llvm::DXILLegalizePass::run(), llvm::DXILMetadataAnalysisPrinterPass::run(), llvm::DXILOpLowering::run(), llvm::DXILPostOptimizationValidation::run(), llvm::DXILPrettyPrinterPass::run(), llvm::DXILResourceAccess::run(), llvm::DXILResourceImplicitBinding::run(), llvm::DXILResourcePrinterPass::run(), llvm::DXILTranslateMetadata::run(), llvm::DXILUpgradePass::run(), llvm::EarlyCSEPass::run(), llvm::EarlyIfConverterPass::run(), llvm::EliminateAvailableExternallyPass::run(), llvm::EntryExitInstrumenterPass::run(), llvm::EVLIndVarSimplifyPass::run(), llvm::ExpandFpPass::run(), llvm::ExpandLargeDivRemPass::run(), llvm::ExpandPostRAPseudosPass::run(), llvm::ExpandReductionsPass::run(), llvm::ExpandVariadicsPass::run(), llvm::ExtraFunctionPassManager< MarkerTy >::run(), llvm::ExtraLoopPassManager< MarkerTy >::run(), llvm::FatLtoCleanup::run(), llvm::FEntryInserterPass::run(), llvm::FinalizeISelPass::run(), llvm::FixIrreduciblePass::run(), llvm::FixupStatepointCallerSavedPass::run(), llvm::FlattenCFGPass::run(), llvm::Float2IntPass::run(), llvm::ForceFunctionAttrsPass::run(), llvm::FunctionImportPass::run(), llvm::FunctionPropertiesPrinterPass::run(), llvm::FunctionToLoopPassAdaptor::run(), llvm::FunctionToMachineFunctionPassAdaptor::run(), llvm::GCLoweringPass::run(), llvm::GCNCreateVOPDPass::run(), llvm::GCNDPPCombinePass::run(), llvm::GCNNSAReassignPass::run(), llvm::GCNPreRALongBranchRegPass::run(), llvm::GCNPreRAOptimizationsPass::run(), llvm::GCNRewritePartialRegUsesPass::run(), llvm::GCOVProfilerPass::run(), llvm::GenericToNVVMPass::run(), llvm::GISelValueTrackingPrinterPass::run(), llvm::GlobalDCEPass::run(), llvm::GlobalMergeFuncPass::run(), llvm::GlobalMergePass::run(), llvm::GlobalOptPass::run(), llvm::GlobalSplitPass::run(), llvm::GuardWideningPass::run(), llvm::GuardWideningPass::run(), llvm::GVNHoistPass::run(), llvm::GVNPass::run(), llvm::GVNSinkPass::run(), llvm::HardwareLoopsPass::run(), llvm::HashRecognizePrinterPass::run(), llvm::HelloWorldPass::run(), llvm::HexagonLoopIdiomRecognitionPass::run(), llvm::HexagonVectorLoopCarriedReusePass::run(), llvm::HotColdSplittingPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::IndirectBrExpandPass::run(), llvm::IndVarSimplifyPass::run(), llvm::InferAddressSpacesPass::run(), llvm::InferAlignmentPass::run(), llvm::InferFunctionAttrsPass::run(), llvm::InitUndefPass::run(), llvm::InjectTLIMappings::run(), llvm::InlineAdvisorAnalysisPrinterPass::run(), llvm::InlineAdvisorAnalysisPrinterPass::run(), llvm::InlineCostAnnotationPrinterPass::run(), llvm::InlinerPass::run(), llvm::InlineSizeEstimatorAnalysisPrinterPass::run(), llvm::InstCombinePass::run(), llvm::InstCountPass::run(), llvm::InstrProfilingLoweringPass::run(), llvm::InstructionNamerPass::run(), llvm::InstSimplifyPass::run(), llvm::InterleavedAccessPass::run(), llvm::InterleavedLoadCombinePass::run(), llvm::InternalizePass::run(), llvm::InvalidateAnalysisPass< AnalysisT >::run(), llvm::IPSCCPPass::run(), llvm::IR2VecPrinterPass::run(), llvm::IR2VecVocabPrinterPass::run(), llvm::IRCEPass::run(), llvm::IROutlinerPass::run(), llvm::IRSimilarityAnalysisPrinterPass::run(), llvm::IVUsersPrinterPass::run(), llvm::JMCInstrumenterPass::run(), llvm::JumpTableToSwitchPass::run(), llvm::JumpThreadingPass::run(), llvm::KCFIPass::run(), llvm::KernelInfoPrinter::run(), llvm::LazyCallGraphDOTPrinterPass::run(), llvm::LazyCallGraphPrinterPass::run(), llvm::LazyValueInfoPrinterPass::run(), llvm::LCSSAPass::run(), llvm::LibCallsShrinkWrapPass::run(), llvm::LICMPass::run(), llvm::LintPass::run(), llvm::LiveDebugValuesPass::run(), llvm::LiveDebugVariablesPrinterPass::run(), llvm::LiveIntervalsPrinterPass::run(), llvm::LiveStacksPrinterPass::run(), llvm::LiveVariablesPrinterPass::run(), llvm::LNICMPass::run(), llvm::LoadStoreVectorizerPass::run(), llvm::LocalStackSlotAllocationPass::run(), llvm::LoopAccessInfoPrinterPass::run(), llvm::LoopBoundSplitPass::run(), llvm::LoopCachePrinterPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::LoopDeletionPass::run(), llvm::LoopDistributePass::run(), llvm::LoopExtractorPass::run(), llvm::LoopFlattenPass::run(), llvm::LoopFullUnrollPass::run(), llvm::LoopFusePass::run(), llvm::LoopIdiomRecognizePass::run(), llvm::LoopIdiomVectorizePass::run(), llvm::LoopInstSimplifyPass::run(), llvm::LoopInterchangePass::run(), llvm::LoopLoadEliminationPass::run(), llvm::LoopNestPrinterPass::run(), llvm::LoopPredicationPass::run(), llvm::LoopPrinterPass::run(), llvm::LoopRotatePass::run(), llvm::LoopSimplifyCFGPass::run(), llvm::LoopSimplifyPass::run(), llvm::LoopSinkPass::run(), llvm::LoopStrengthReducePass::run(), llvm::LoopTermFoldPass::run(), llvm::LoopUnrollAndJamPass::run(), llvm::LoopUnrollPass::run(), llvm::LoopVectorizePass::run(), llvm::LoopVerifierPass::run(), llvm::LoopVersioningLICMPass::run(), llvm::LoopVersioningPass::run(), llvm::LowerAllowCheckPass::run(), llvm::LowerAtomicPass::run(), llvm::LowerConstantIntrinsicsPass::run(), llvm::LowerEmuTLSPass::run(), llvm::LowerExpectIntrinsicPass::run(), llvm::LowerGlobalDtorsPass::run(), llvm::LowerGuardIntrinsicPass::run(), llvm::LowerIFuncPass::run(), llvm::LowerInvokePass::run(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::LowerSwitchPass::run(), llvm::LowerTypeTestsPass::run(), llvm::LowerWidenableConditionPass::run(), llvm::MachineBlockFrequencyPrinterPass::run(), llvm::MachineBlockPlacementPass::run(), llvm::MachineBlockPlacementStatsPass::run(), llvm::MachineBranchProbabilityPrinterPass::run(), llvm::MachineCopyPropagationPass::run(), llvm::MachineCSEPass::run(), llvm::MachineCycleInfoPrinterPass::run(), llvm::MachineDominatorTreePrinterPass::run(), llvm::MachineLateInstrsCleanupPass::run(), llvm::MachineLICMBasePass< DerivedT, PreRegAlloc >::run(), llvm::MachineLoopPrinterPass::run(), llvm::MachinePostDominatorTreePrinterPass::run(), llvm::MachineSanitizerBinaryMetadataPass::run(), llvm::MachineSchedulerPass::run(), llvm::MachineSinkingPass::run(), llvm::MachineTraceMetricsVerifierPass::run(), llvm::MachineUniformityPrinterPass::run(), llvm::MachineVerifierPass::run(), llvm::MakeGuardsExplicitPass::run(), llvm::MemCpyOptPass::run(), llvm::MemDerefPrinterPass::run(), llvm::MemorySanitizerPass::run(), llvm::MemorySSAPrinterPass::run(), llvm::MemorySSAVerifierPass::run(), llvm::MemorySSAWalkerPrinterPass::run(), llvm::MemProfContextDisambiguation::run(), llvm::MemProfilerPass::run(), llvm::MemProfUsePass::run(), llvm::MergedLoadStoreMotionPass::run(), llvm::MergeFunctionsPass::run(), llvm::MergeICmpsPass::run(), llvm::MetaRenamerPass::run(), llvm::ModuleDebugInfoPrinterPass::run(), llvm::ModuleInlinerPass::run(), llvm::ModuleMemProfilerPass::run(), llvm::ModuleThreadSanitizerPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::MoveAutoInitPass::run(), llvm::MustBeExecutedContextPrinterPass::run(), llvm::MustExecutePrinterPass::run(), llvm::NameAnonGlobalPass::run(), llvm::NaryReassociatePass::run(), llvm::NewGVNPass::run(), llvm::NoinlineNonPrevailing::run(), llvm::NoOpCGSCCPass::run(), llvm::NoOpFunctionPass::run(), llvm::NoOpLoopNestPass::run(), llvm::NoOpLoopPass::run(), llvm::NoOpMachineFunctionPass::run(), llvm::NoOpModulePass::run(), llvm::NVPTXCopyByValArgsPass::run(), llvm::NVPTXCtorDtorLoweringPass::run(), llvm::NVPTXLowerArgsPass::run(), llvm::NVPTXTagInvariantLoadsPass::run(), llvm::NVVMIntrRangePass::run(), llvm::NVVMReflectPass::run(), llvm::ObjCARCAPElimPass::run(), llvm::ObjCARCContractPass::run(), llvm::ObjCARCExpandPass::run(), llvm::ObjCARCOptPass::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::OpenMPOptPass::run(), llvm::PAEvalPass::run(), llvm::PartialInlinerPass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run(), llvm::PatchableFunctionPass::run(), llvm::PeepholeOptimizerPass::run(), llvm::PGOCtxProfLoweringPass::run(), llvm::PGOForceFunctionAttrsPass::run(), llvm::PGOIndirectCallPromotion::run(), llvm::PGOInstrumentationGen::run(), llvm::PGOInstrumentationUse::run(), llvm::PGOMemOPSizeOpt::run(), llvm::PHIEliminationPass::run(), llvm::PhiValuesPrinterPass::run(), llvm::PhysicalRegisterUsageInfoPrinterPass::run(), llvm::PlaceSafepointsPass::run(), llvm::PostDominatorTreePrinterPass::run(), llvm::PostMachineSchedulerPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::PostRAMachineSinkingPass::run(), llvm::PostRASchedulerPass::run(), llvm::PredicateInfoPrinterPass::run(), llvm::PredicateInfoVerifierPass::run(), llvm::PreISelIntrinsicLoweringPass::run(), llvm::PrintFunctionPass::run(), llvm::PrintLoopPass::run(), llvm::PrintMIRPass::run(), llvm::PrintMIRPreparePass::run(), llvm::PrintModulePass::run(), llvm::ProfileSummaryPrinterPass::run(), llvm::PrologEpilogInserterPass::run(), llvm::PromotePass::run(), llvm::ReassociatePass::run(), llvm::RecomputeGlobalsAAPass::run(), llvm::RedundantDbgInstEliminationPass::run(), llvm::RegAllocFastPass::run(), llvm::RegionInfoPrinterPass::run(), llvm::RegionInfoVerifierPass::run(), llvm::RegisterCoalescerPass::run(), llvm::RegToMemPass::run(), llvm::RegUsageInfoCollectorPass::run(), llvm::RegUsageInfoPropagationPass::run(), llvm::RelLookupTableConverterPass::run(), llvm::RemoveLoadsIntoFakeUsesPass::run(), llvm::RemoveRedundantDebugValuesPass::run(), llvm::RenameIndependentSubregsPass::run(), llvm::ReplaceWithVeclib::run(), llvm::RequireAnalysisPass< AnalysisT, IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::RequireAnalysisPass< AnalysisT, LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run(), llvm::ReversePostOrderFunctionAttrsPass::run(), llvm::RewriteStatepointsForGC::run(), llvm::RewriteSymbolPass::run(), llvm::SafepointIRVerifierPass::run(), llvm::SafeStackPass::run(), llvm::SampleProfileLoaderPass::run(), llvm::SandboxVectorizerPass::run(), llvm::SanitizerBinaryMetadataPass::run(), llvm::SanitizerCoveragePass::run(), llvm::ScalarEvolutionPrinterPass::run(), llvm::ScalarEvolutionVerifierPass::run(), llvm::ScalarizeMaskedMemIntrinPass::run(), llvm::ScalarizerPass::run(), llvm::SCCPPass::run(), llvm::SelectionDAGISelPass::run(), llvm::SeparateConstOffsetFromGEPPass::run(), llvm::ShadowStackGCLoweringPass::run(), llvm::ShrinkWrapPass::run(), llvm::SIAnnotateControlFlowPass::run(), llvm::SIFixSGPRCopiesPass::run(), llvm::SIFixVGPRCopiesPass::run(), llvm::SIFoldOperandsPass::run(), llvm::SIFormMemoryClausesPass::run(), llvm::SIInsertHardClausesPass::run(), llvm::SIInsertWaitcntsPass::run(), llvm::SILateBranchLoweringPass::run(), llvm::SILoadStoreOptimizerPass::run(), llvm::SILowerControlFlowPass::run(), llvm::SILowerI1CopiesPass::run(), llvm::SILowerSGPRSpillsPass::run(), llvm::SILowerWWMCopiesPass::run(), llvm::SIMemoryLegalizerPass::run(), llvm::SIModeRegisterPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::SimplifyCFGPass::run(), llvm::SimplifyTypeTestsPass::run(), llvm::SinkingPass::run(), llvm::SIOptimizeExecMaskingPass::run(), llvm::SIOptimizeExecMaskingPreRAPass::run(), llvm::SIOptimizeVGPRLiveRangePass::run(), llvm::SIPeepholeSDWAPass::run(), llvm::SIPostRABundlerPass::run(), llvm::SIPreAllocateWWMRegsPass::run(), llvm::SIPreEmitPeepholePass::run(), llvm::SIShrinkInstructionsPass::run(), llvm::SIWholeQuadModePass::run(), llvm::SjLjEHPreparePass::run(), llvm::SlotIndexesPrinterPass::run(), llvm::SLPVectorizerPass::run(), llvm::SpeculativeExecutionPass::run(), llvm::SPIRVStructurizerWrapper::run(), llvm::SROAPass::run(), llvm::StackColoringPass::run(), llvm::StackFrameLayoutAnalysisPass::run(), llvm::StackLifetimePrinterPass::run(), llvm::StackProtectorPass::run(), llvm::StackSafetyGlobalPrinterPass::run(), llvm::StackSafetyPrinterPass::run(), llvm::StackSlotColoringPass::run(), llvm::StraightLineStrengthReducePass::run(), llvm::StripDeadCGProfilePass::run(), llvm::StripDeadPrototypesPass::run(), llvm::StripGCRelocates::run(), llvm::StructuralHashPrinterPass::run(), llvm::StructurizeCFGPass::run(), llvm::TailCallElimPass::run(), llvm::TailDuplicatePassBase< DerivedT, PreRegAlloc >::run(), llvm::ThinLTOBitcodeWriterPass::run(), llvm::ThreadSanitizerPass::run(), llvm::TwoAddressInstructionPass::run(), llvm::TypePromotionPass::run(), llvm::UniformityInfoPrinterPass::run(), llvm::UnifyFunctionExitNodesPass::run(), llvm::UnifyLoopExitsPass::run(), llvm::UnreachableBlockElimPass::run(), llvm::UnreachableMachineBlockElimPass::run(), llvm::VectorCombinePass::run(), llvm::VerifierPass::run(), llvm::VerifierPass::run(), llvm::VirtRegMapPrinterPass::run(), llvm::VirtRegRewriterPass::run(), llvm::WarnMissedTransformationsPass::run(), llvm::WholeProgramDevirtPass::run(), llvm::WinEHPreparePass::run(), llvm::XRayInstrumentationPass::run(), NewPMCheckDebugifyPass::run(), RAGreedyPass::run(), and updateNewSCCFunctionAnalyses().
allAnalysesInSetPreserved() [1/2]
template<typename AnalysisSetT> bool llvm::PreservedAnalyses::allAnalysesInSetPreserved () const inline
Directly test whether a set of analyses is preserved.
This is only true when no analyses have been explicitly abandoned.
Definition at line 300 of file Analysis.h.
References allAnalysesInSetPreserved().
Referenced by allAnalysesInSetPreserved(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::CGSCCAnalysisManagerModuleProxy::Result::invalidate(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), and llvm::MemorySSAAnalysis::Result::invalidate().
allAnalysesInSetPreserved() [2/2]
bool llvm::PreservedAnalyses::allAnalysesInSetPreserved (AnalysisSetKey * SetID) const inline
Directly test whether a set of analyses is preserved.
This is only true when no analyses have been explicitly abandoned.
Definition at line 307 of file Analysis.h.
allInSet()
template<typename AnalysisSetT> PreservedAnalyses llvm::PreservedAnalyses::allInSet () inline static
Construct a preserved analyses object with a single preserved set.
Definition at line 125 of file Analysis.h.
References preserveSet().
Referenced by incorporateNewSCCRange(), llvm::EVLIndVarSimplifyPass::run(), and updateCGAndAnalysisManagerForPass().
areAllPreserved()
bool llvm::PreservedAnalyses::areAllPreserved () const inline
Test whether all analyses are preserved (and none are abandoned).
This is used primarily to optimize for the common case of a transformation which makes no changes to the IR.
Definition at line 292 of file Analysis.h.
Referenced by intersect(), intersect(), llvm::CGSCCAnalysisManagerModuleProxy::Result::invalidate(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), preserve(), and preserveSet().
getChecker() [1/2]
template<typename AnalysisT> PreservedAnalysisChecker llvm::PreservedAnalyses::getChecker () const inline
Build a checker for this PreservedAnalyses and the specified analysis type.
You can use the returned object to query whether an analysis was preserved. See the example in the comment on PreservedAnalysis.
Definition at line 275 of file Analysis.h.
Referenced by llvm::AAResults::invalidate(), llvm::BlockFrequencyInfo::invalidate(), llvm::BranchProbabilityInfo::invalidate(), llvm::CallGraph::invalidate(), llvm::CGSCCAnalysisManagerModuleProxy::Result::invalidate(), llvm::DependenceInfo::invalidate(), llvm::DominanceFrontier::invalidate(), llvm::DominatorTree::invalidate(), llvm::DXILResourceTypeMap::invalidate(), llvm::EdgeBundles::invalidate(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), llvm::GCFunctionInfo::invalidate(), llvm::GlobalsAAResult::invalidate(), llvm::InlineAdvisorAnalysis::Result::invalidate(), llvm::ir2vec::Vocabulary::invalidate(), llvm::LazyCallGraph::invalidate(), llvm::LazyValueInfo::invalidate(), llvm::LiveDebugVariables::invalidate(), llvm::LiveIntervals::invalidate(), llvm::LoopAccessInfoManager::invalidate(), llvm::LoopInfo::invalidate(), llvm::MachineBlockFrequencyInfo::invalidate(), llvm::MachineBranchProbabilityInfo::invalidate(), llvm::MachineDominatorTree::invalidate(), llvm::MachineFunctionAnalysis::Result::invalidate(), llvm::MachineLoopInfo::invalidate(), llvm::MachinePostDominatorTree::invalidate(), llvm::MachineTraceMetrics::invalidate(), llvm::MemoryDependenceResults::invalidate(), llvm::MemorySSAAnalysis::Result::invalidate(), llvm::PGOContextualProfile::invalidate(), llvm::PhiValues::invalidate(), llvm::PhysicalRegisterUsageInfo::invalidate(), llvm::PreservedCFGCheckerInstrumentation::CFG::invalidate(), llvm::RegAllocPriorityAdvisorAnalysis::Result::invalidate(), llvm::RegionInfo::invalidate(), llvm::ScalarEvolution::invalidate(), llvm::ShouldRunExtraPasses< MarkerTy >::Result::invalidate(), llvm::ShouldRunExtraPasses< MarkerTy >::Result::invalidate(), llvm::SpillPlacement::invalidate(), llvm::CGSCCToFunctionPassAdaptor::run(), and llvm::FunctionToLoopPassAdaptor::run().
getChecker() [2/2]
PreservedAnalysisChecker llvm::PreservedAnalyses::getChecker (AnalysisKey * ID) const inline
Build a checker for this PreservedAnalyses and the specified analysis ID.
You can use the returned object to query whether an analysis was preserved. See the example in the comment on PreservedAnalysis.
Definition at line 284 of file Analysis.h.
intersect() [1/2]
void llvm::PreservedAnalyses::intersect (const PreservedAnalyses & Arg) inline
Intersect this set with another in place.
This is a mutating operation on this preserved set, removing all preserved passes which are not also preserved in the argument.
Definition at line 193 of file Analysis.h.
References areAllPreserved(), and llvm::SmallPtrSetImpl< PtrType >::contains().
Referenced by llvm::CGSCCToFunctionPassAdaptor::run(), llvm::DevirtSCCRepeatedPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), and llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run().
intersect() [2/2]
void llvm::PreservedAnalyses::intersect (PreservedAnalyses && Arg) inline
Intersect this set with a temporary other set in place.
This is a mutating operation on this preserved set, removing all preserved passes which are not also preserved in the argument.
Definition at line 214 of file Analysis.h.
References areAllPreserved().
none()
PreservedAnalyses llvm::PreservedAnalyses::none () inline static
Convenience factory function for the empty preserved set.
Definition at line 115 of file Analysis.h.
Referenced by INITIALIZE_PASS(), llvm::AddDiscriminatorsPass::run(), llvm::AddressSanitizerPass::run(), llvm::AMDGPUAlwaysInlinePass::run(), llvm::AMDGPUAnnotateUniformValuesPass::run(), llvm::AMDGPUAttributorPass::run(), llvm::AMDGPUCodeGenPreparePass::run(), llvm::AMDGPUCtorDtorLoweringPass::run(), llvm::AMDGPUImageIntrinsicOptimizerPass::run(), llvm::AMDGPULateCodeGenPreparePass::run(), llvm::AMDGPULowerBufferFatPointersPass::run(), llvm::AMDGPULowerModuleLDSPass::run(), llvm::AMDGPUPreloadKernelArgumentsPass::run(), llvm::AMDGPUPrintfRuntimeBindingPass::run(), llvm::AMDGPURemoveIncompatibleFunctionsPass::run(), llvm::AMDGPUSimplifyLibCallsPass::run(), llvm::AMDGPUSplitModulePass::run(), llvm::AMDGPUUnifyDivergentExitNodesPass::run(), llvm::AMDGPUUnifyMetadataPass::run(), llvm::AMDGPUUseNativeCallsPass::run(), llvm::Annotation2MetadataPass::run(), llvm::AssignGUIDPass::run(), llvm::AtomicExpandPass::run(), llvm::AttributorPass::run(), llvm::BlockExtractorPass::run(), llvm::BoundsCheckingPass::run(), llvm::BPFAbstractMemberAccessPass::run(), llvm::BPFAdjustOptPass::run(), llvm::BPFASpaceCastSimplifyPass::run(), llvm::BPFIRPeepholePass::run(), llvm::BPFPreserveDITypePass::run(), llvm::BPFPreserveStaticOffsetPass::run(), llvm::CanonicalizeAliasesPass::run(), llvm::CFGuardPass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::ConstantMergePass::run(), llvm::ControlHeightReductionPass::run(), llvm::CoroAnnotationElidePass::run(), llvm::CoroCleanupPass::run(), llvm::CoroElidePass::run(), llvm::CoroSplitPass::run(), llvm::CrossDSOCFIPass::run(), llvm::DataFlowSanitizerPass::run(), llvm::DeadArgumentEliminationPass::run(), llvm::DeclareRuntimeLibcallsPass::run(), llvm::DXILFinalizeLinkage::run(), llvm::DXILIntrinsicExpansion::run(), llvm::EliminateAvailableExternallyPass::run(), llvm::EmbedBitcodePass::run(), llvm::ExpandFpPass::run(), llvm::ExpandLargeDivRemPass::run(), llvm::ExpandVariadicsPass::run(), llvm::ExtractGVPass::run(), llvm::FatLtoCleanup::run(), llvm::FlattenCFGPass::run(), llvm::ForceFunctionAttrsPass::run(), llvm::FunctionImportPass::run(), llvm::GCOVProfilerPass::run(), llvm::GenericToNVVMPass::run(), llvm::GlobalDCEPass::run(), llvm::GlobalMergeFuncPass::run(), llvm::GlobalOptPass::run(), llvm::GlobalSplitPass::run(), llvm::GVNSinkPass::run(), llvm::HipStdParAcceleratorCodeSelectionPass::run(), llvm::HipStdParAllocationInterpositionPass::run(), llvm::HotColdSplittingPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::InferFunctionAttrsPass::run(), llvm::InlinerPass::run(), llvm::InstrProfilingLoweringPass::run(), llvm::InterleavedLoadCombinePass::run(), llvm::InternalizePass::run(), llvm::InvalidateAllAnalysesPass::run(), llvm::IROutlinerPass::run(), llvm::JMCInstrumenterPass::run(), llvm::KCFIPass::run(), llvm::LoopIdiomVectorizePass::run(), llvm::LoopVersioningPass::run(), llvm::LowerAllowCheckPass::run(), llvm::LowerAtomicPass::run(), llvm::LowerExpectIntrinsicPass::run(), llvm::LowerGuardIntrinsicPass::run(), llvm::LowerIFuncPass::run(), llvm::LowerInvokePass::run(), llvm::LowerSwitchPass::run(), llvm::LowerTypeTestsPass::run(), llvm::LowerWidenableConditionPass::run(), llvm::MakeGuardsExplicitPass::run(), llvm::MemorySanitizerPass::run(), llvm::MemProfContextDisambiguation::run(), llvm::MemProfilerPass::run(), llvm::MemProfUsePass::run(), llvm::MergeFunctionsPass::run(), llvm::ModuleInlinerPass::run(), llvm::ModuleMemProfilerPass::run(), llvm::ModuleThreadSanitizerPass::run(), llvm::NameAnonGlobalPass::run(), llvm::NoinlineNonPrevailing::run(), llvm::NumericalStabilitySanitizerPass::run(), llvm::NVPTXCopyByValArgsPass::run(), llvm::NVPTXCtorDtorLoweringPass::run(), llvm::NVPTXLowerArgsPass::run(), llvm::NVPTXTagInvariantLoadsPass::run(), llvm::NVVMIntrRangePass::run(), llvm::NVVMReflectPass::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::OpenMPOptPass::run(), llvm::PartialInlinerPass::run(), llvm::PGOCtxProfFlatteningPass::run(), llvm::PGOCtxProfLoweringPass::run(), llvm::PGOForceFunctionAttrsPass::run(), llvm::PGOIndirectCallPromotion::run(), llvm::PGOInstrumentationGen::run(), llvm::PGOInstrumentationUse::run(), llvm::PlaceSafepointsPass::run(), llvm::PreISelIntrinsicLoweringPass::run(), llvm::PseudoProbeUpdatePass::run(), llvm::RealtimeSanitizerPass::run(), llvm::RewriteSymbolPass::run(), llvm::SampleProfileLoaderPass::run(), llvm::SampleProfileProbePass::run(), llvm::SanitizerBinaryMetadataPass::run(), llvm::SanitizerCoveragePass::run(), llvm::SIAnnotateControlFlowPass::run(), llvm::SimplifyTypeTestsPass::run(), llvm::SjLjEHPreparePass::run(), llvm::StripDeadCGProfilePass::run(), llvm::StripDeadPrototypesPass::run(), llvm::ThinLTOBitcodeWriterPass::run(), llvm::ThreadSanitizerPass::run(), llvm::TypeSanitizerPass::run(), llvm::WasmEHPreparePass::run(), llvm::WholeProgramDevirtPass::run(), llvm::WinEHPreparePass::run(), and llvm::AnalysisManager< LazyCallGraph::SCC, LazyCallGraph & >::verifyNotInvalidated().
preserve() [1/2]
template<typename AnalysisT> PreservedAnalyses & llvm::PreservedAnalyses::preserve () inline
Mark an analysis as preserved.
Definition at line 132 of file Analysis.h.
References preserve().
Referenced by llvm::getLoopPassPreservedAnalyses(), preserve(), llvm::ADCEPass::run(), llvm::AggressiveInstCombinePass::run(), llvm::AlignmentFromAssumptionsPass::run(), llvm::AMDGPUAtomicOptimizerPass::run(), llvm::AMDGPUPerfHintAnalysisPass::run(), llvm::AMDGPUPromoteKernelArgumentsPass::run(), llvm::AMDGPUSwLowerLDSPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AttributorCGSCCPass::run(), llvm::AttributorLightCGSCCPass::run(), llvm::AttributorLightPass::run(), llvm::BreakCriticalEdgesPass::run(), llvm::CallBrPreparePass::run(), llvm::CallSiteSplittingPass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CodeGenPreparePass::run(), llvm::ComplexDeinterleavingPass::run(), llvm::ConstraintEliminationPass::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::DFAJumpThreadingPass::run(), llvm::DSEPass::run(), llvm::DwarfEHPreparePass::run(), llvm::DXILOpLowering::run(), llvm::DXILResourceAccess::run(), llvm::DXILResourceImplicitBinding::run(), llvm::DXILUpgradePass::run(), llvm::EarlyCSEPass::run(), llvm::FixIrreduciblePass::run(), llvm::GCLoweringPass::run(), llvm::GlobalOptPass::run(), llvm::GuardWideningPass::run(), llvm::GVNHoistPass::run(), llvm::GVNPass::run(), llvm::HardwareLoopsPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::IndirectBrExpandPass::run(), llvm::InferAddressSpacesPass::run(), llvm::InlinerPass::run(), llvm::InstCombinePass::run(), llvm::IPSCCPPass::run(), llvm::JumpTableToSwitchPass::run(), llvm::LCSSAPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::LoopDistributePass::run(), llvm::LoopExtractorPass::run(), llvm::LoopFusePass::run(), llvm::LoopLoadEliminationPass::run(), llvm::LoopSimplifyPass::run(), llvm::LoopSinkPass::run(), llvm::LoopVectorizePass::run(), llvm::LowerConstantIntrinsicsPass::run(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::MemCpyOptPass::run(), llvm::MergeICmpsPass::run(), llvm::MoveAutoInitPass::run(), llvm::NaryReassociatePass::run(), llvm::NewGVNPass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::PGOInstrumentationGenCreateVar::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::PostRASchedulerPass::run(), llvm::RegToMemPass::run(), llvm::ReplaceWithVeclib::run(), llvm::ReversePostOrderFunctionAttrsPass::run(), llvm::RewriteStatepointsForGC::run(), llvm::SafeStackPass::run(), llvm::ScalarizeMaskedMemIntrinPass::run(), llvm::ScalarizerPass::run(), llvm::ShadowStackGCLoweringPass::run(), llvm::SIAnnotateControlFlowPass::run(), llvm::SILateBranchLoweringPass::run(), llvm::SimplifyCFGPass::run(), llvm::SimplifyTypeTestsPass::run(), llvm::SIWholeQuadModePass::run(), llvm::SROAPass::run(), llvm::StackProtectorPass::run(), llvm::StraightLineStrengthReducePass::run(), llvm::StructurizeCFGPass::run(), llvm::TailCallElimPass::run(), llvm::TypePromotionPass::run(), llvm::UnifyLoopExitsPass::run(), llvm::UnreachableBlockElimPass::run(), and llvm::UnreachableMachineBlockElimPass::run().
preserve() [2/2]
PreservedAnalyses & llvm::PreservedAnalyses::preserve (AnalysisKey * ID) inline
Given an analysis's ID, mark the analysis as preserved, adding it to the set.
Definition at line 139 of file Analysis.h.
References areAllPreserved().
preserveSet() [1/2]
template<typename AnalysisSetT> PreservedAnalyses & llvm::PreservedAnalyses::preserveSet () inline
Mark an analysis set as preserved.
Definition at line 151 of file Analysis.h.
References preserveSet().
Referenced by allInSet(), preserveSet(), llvm::DebugifyEachInstrumentation::registerCallbacks(), rtsanPreservedCFGAnalyses(), llvm::ADCEPass::run(), llvm::AggressiveInstCombinePass::run(), llvm::AlignmentFromAssumptionsPass::run(), llvm::AlwaysInlinerPass::run(), llvm::AMDGPUAnnotateUniformValuesPass::run(), llvm::AMDGPUCodeGenPreparePass::run(), llvm::AMDGPUExportKernelRuntimeHandlesPass::run(), llvm::AMDGPULateCodeGenPreparePass::run(), llvm::AMDGPULowerKernelArgumentsPass::run(), llvm::AMDGPUPromoteAllocaPass::run(), llvm::AMDGPUPromoteAllocaToVectorPass::run(), llvm::AMDGPUPromoteKernelArgumentsPass::run(), llvm::AMDGPURewriteUndefForPHIPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AssignmentTrackingPass::run(), llvm::AssignmentTrackingPass::run(), llvm::AssumeBuilderPass::run(), llvm::AssumeSimplifyPass::run(), llvm::AttributorLightCGSCCPass::run(), llvm::AttributorLightPass::run(), llvm::BDCEPass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::ConstantHoistingPass::run(), llvm::ConstraintEliminationPass::run(), llvm::CoroCleanupPass::run(), llvm::CoroEarlyPass::run(), llvm::DCEPass::run(), llvm::DeadMachineInstructionElimPass::run(), llvm::DivRemPairsPass::run(), llvm::DSEPass::run(), llvm::DXILUpgradePass::run(), llvm::EarlyCSEPass::run(), llvm::EntryExitInstrumenterPass::run(), llvm::ExpandPostRAPseudosPass::run(), llvm::ExpandReductionsPass::run(), llvm::Float2IntPass::run(), llvm::GCNCreateVOPDPass::run(), llvm::GlobalMergePass::run(), llvm::GlobalOptPass::run(), llvm::GuardWideningPass::run(), llvm::HexagonVectorLoopCarriedReusePass::run(), llvm::InferAddressSpacesPass::run(), llvm::InlinerPass::run(), llvm::InstCombinePass::run(), llvm::InstSimplifyPass::run(), llvm::InterleavedAccessPass::run(), llvm::IRNormalizerPass::run(), llvm::LCSSAPass::run(), llvm::LoadStoreVectorizerPass::run(), llvm::LoopSinkPass::run(), llvm::LoopVectorizePass::run(), llvm::LowerAllowCheckPass::run(), llvm::LowerGlobalDtorsPass::run(), llvm::MachineSchedulerPass::run(), llvm::MemCpyOptPass::run(), llvm::MergedLoadStoreMotionPass::run(), llvm::MoveAutoInitPass::run(), llvm::NaryReassociatePass::run(), llvm::ObjCARCAPElimPass::run(), llvm::ObjCARCContractPass::run(), llvm::ObjCARCExpandPass::run(), llvm::ObjCARCOptPass::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::PGOInstrumentationGenCreateVar::run(), llvm::PostMachineSchedulerPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::PostRAMachineSinkingPass::run(), llvm::PostRASchedulerPass::run(), llvm::PrologEpilogInserterPass::run(), llvm::PromotePass::run(), llvm::ReassociatePass::run(), llvm::RedundantDbgInstEliminationPass::run(), llvm::RelLookupTableConverterPass::run(), llvm::ReplaceWithVeclib::run(), llvm::SandboxVectorizerPass::run(), llvm::SeparateConstOffsetFromGEPPass::run(), llvm::SIInsertWaitcntsPass::run(), llvm::SILoadStoreOptimizerPass::run(), llvm::SILowerI1CopiesPass::run(), llvm::SIMemoryLegalizerPass::run(), llvm::SinkingPass::run(), llvm::SIPeepholeSDWAPass::run(), llvm::SLPVectorizerPass::run(), llvm::SpeculativeExecutionPass::run(), llvm::SPIRVStructurizerWrapper::run(), llvm::SROAPass::run(), llvm::StraightLineStrengthReducePass::run(), llvm::StripDeadDebugInfoPass::run(), llvm::StripDebugDeclarePass::run(), llvm::StripGCRelocates::run(), llvm::StripNonDebugSymbolsPass::run(), llvm::StripNonLineTableDebugInfoPass::run(), llvm::StripSymbolsPass::run(), llvm::TypePromotionPass::run(), llvm::VectorCombinePass::run(), NewPMDebugifyPass::run(), and runAttributorLightOnFunctions().
preserveSet() [2/2]
PreservedAnalyses & llvm::PreservedAnalyses::preserveSet (AnalysisSetKey * ID) inline
Mark an analysis set as preserved using its ID.
Definition at line 157 of file Analysis.h.
References areAllPreserved().
The documentation for this class was generated from the following files:
include/llvm/IR/Analysis.h
lib/SandboxIR/PassManager.cpp