LLVM: llvm::telemetry::Serializer Class Reference
llvm::telemetry::Serializer Class Reference abstract
#include "llvm/Telemetry/Telemetry.h"
Public Member Functions
virtual ~Serializer ()=default
virtual Error init ()=0
virtual void write (StringRef KeyName, bool Value)=0
virtual void write (StringRef KeyName, StringRef Value)=0
virtual void write (StringRef KeyName, int Value)=0
virtual void write (StringRef KeyName, long Value)=0
virtual void write (StringRef KeyName, long long Value)=0
virtual void write (StringRef KeyName, unsigned int Value)=0
virtual void write (StringRef KeyName, unsigned long Value)=0
virtual void write (StringRef KeyName, unsigned long long Value)=0
virtual void beginObject (StringRef KeyName)=0
virtual void endObject ()=0
virtual Error finalize ()=0
template<typename T, typename = typename T::mapped_type>
void write (StringRef KeyName, const T &Map)
Detailed Description
Definition at line 32 of file Telemetry.h.
Constructor & Destructor Documentation
~Serializer()
virtual llvm::telemetry::Serializer::~Serializer () virtual default
Member Function Documentation
beginObject()
virtual void llvm::telemetry::Serializer::beginObject (StringRef KeyName) pure virtual
Referenced by write().
endObject()
virtual void llvm::telemetry::Serializer::endObject () pure virtual
Referenced by write().
finalize()
virtual Error llvm::telemetry::Serializer::finalize () pure virtual
init()
virtual Error llvm::telemetry::Serializer::init () pure virtual
write() [1/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, bool Value) pure virtual
Referenced by llvm::telemetry::TelemetryInfo::serialize(), and write().
write() [2/9]
template<typename T, typename = typename T::mapped_type> void llvm::telemetry::Serializer::write (StringRef KeyName, const T & Map) inline
Definition at line 50 of file Telemetry.h.
References beginObject(), endObject(), T, and write().
write() [3/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, int Value) pure virtual
write() [4/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, long long Value) pure virtual
write() [5/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, long Value) pure virtual
write() [6/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, StringRef Value) pure virtual
write() [7/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, unsigned int Value) pure virtual
write() [8/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, unsigned long long Value) pure virtual
write() [9/9]
virtual void llvm::telemetry::Serializer::write (StringRef KeyName, unsigned long Value) pure virtual
The documentation for this class was generated from the following file:
include/llvm/Telemetry/Telemetry.h