LLVM: llvm::ARMFunctionInfo Class Reference
llvm::ARMFunctionInfo Class Reference
ARMFunctionInfo - This class is derived from MachineFunctionInfo and contains private ARM-specific information for each MachineFunction.
#include "Target/ARM/ARMMachineFunctionInfo.h"
Public Member Functions
ARMFunctionInfo ()=default
ARMFunctionInfo (const Function &F, const ARMSubtarget *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
bool isThumbFunction () const
bool isThumb1OnlyFunction () const
bool isThumb2Function () const
bool isCmseNSEntryFunction () const
bool isCmseNSCallFunction () const
unsigned getArgRegsSaveSize () const
void setArgRegsSaveSize (unsigned s)
unsigned getReturnRegsCount () const
void setReturnRegsCount (unsigned s)
bool hasStackFrame () const
void setHasStackFrame (bool s)
bool shouldRestoreSPFromFP () const
void setShouldRestoreSPFromFP (bool s)
bool isLRSpilled () const
void setLRIsSpilled (bool s)
unsigned getFramePtrSpillOffset () const
void setFramePtrSpillOffset (unsigned o)
unsigned getNumAlignedDPRCS2Regs () const
void setNumAlignedDPRCS2Regs (unsigned n)
unsigned getGPRCalleeSavedArea1Offset () const
unsigned getGPRCalleeSavedArea2Offset () const
unsigned getDPRCalleeSavedArea1Offset () const
void setGPRCalleeSavedArea1Offset (unsigned o)
void setGPRCalleeSavedArea2Offset (unsigned o)
void setDPRCalleeSavedArea1Offset (unsigned o)
unsigned getFPCXTSaveAreaSize () const
unsigned getFrameRecordSavedAreaSize () const
unsigned getGPRCalleeSavedArea1Size () const
unsigned getGPRCalleeSavedArea2Size () const
unsigned getFPStatusSavesSize () const
unsigned getDPRCalleeSavedGapSize () const
unsigned getDPRCalleeSavedArea1Size () const
unsigned getGPRCalleeSavedArea3Size () const
void setFPCXTSaveAreaSize (unsigned s)
void setFrameRecordSavedAreaSize (unsigned s)
void setGPRCalleeSavedArea1Size (unsigned s)
void setGPRCalleeSavedArea2Size (unsigned s)
void setFPStatusSavesSize (unsigned s)
void setDPRCalleeSavedGapSize (unsigned s)
void setDPRCalleeSavedArea1Size (unsigned s)
void setGPRCalleeSavedArea3Size (unsigned s)
unsigned getArgumentStackSize () const
void setArgumentStackSize (unsigned size)
unsigned getArgumentStackToRestore () const
void setArgumentStackToRestore (unsigned v)
void initPICLabelUId (unsigned UId)
unsigned getNumPICLabels () const
unsigned createPICLabelUId ()
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
bool hasITBlocks () const
void setHasITBlocks (bool h)
bool isSplitCSR () const
void setIsSplitCSR (bool s)
void recordCPEClone (unsigned CPIdx, unsigned CPCloneIdx)
unsigned getOriginalCPIdx (unsigned CloneIdx) const
DenseMap< constMachineBasicBlock *, unsigned >::iterator getCoalescedWeight (MachineBasicBlock *MBB)
void markGlobalAsPromotedToConstantPool (const GlobalVariable *GV)
Indicate to the backend that GV has had its storage changed to inside a constant pool.
SmallPtrSet< const GlobalVariable *, 2 > & getGlobalsPromotedToConstantPool ()
int getPromotedConstpoolIncrease () const
void setPromotedConstpoolIncrease (int Sz)
void setPreservesR0 ()
bool getPreservesR0 () const
bool shouldSignReturnAddress () const
bool shouldSignReturnAddress (bool SpillsLR) const
bool branchTargetEnforcement () const
void initializeBaseYamlFields (const yaml::ARMFunctionInfo &YamlMFI)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Public Attributes
DenseMap< unsigned, unsigned > EHPrologueRemappedRegs
DenseMap< unsigned, unsigned > EHPrologueOffsetInRegs
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy, typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
ARMFunctionInfo - This class is derived from MachineFunctionInfo and contains private ARM-specific information for each MachineFunction.
Definition at line 34 of file ARMMachineFunctionInfo.h.
Constructor & Destructor Documentation
ARMFunctionInfo() [1/2]
llvm::ARMFunctionInfo::ARMFunctionInfo () default
References Allocator, and F.
Referenced by clone().
ARMFunctionInfo() [2/2]
ARMFunctionInfo::ARMFunctionInfo (const Function & F, const ARMSubtarget * STI) explicit
Definition at line 54 of file ARMMachineFunctionInfo.cpp.
References F, GetBranchTargetEnforcement(), GetSignReturnAddress(), and llvm::ARMSubtarget::isMClass().
Member Function Documentation
branchTargetEnforcement()
bool llvm::ARMFunctionInfo::branchTargetEnforcement () const inline
Definition at line 302 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMBaseInstrInfo::getOutliningCandidateInfo().
clone()
MachineFunctionInfo * ARMFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 65 of file ARMMachineFunctionInfo.cpp.
References ARMFunctionInfo(), and llvm::MachineFunction::cloneInfo().
createPICLabelUId()
unsigned llvm::ARMFunctionInfo::createPICLabelUId () inline
Definition at line 237 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), and duplicateCPV().
getArgRegsSaveSize()
unsigned llvm::ARMFunctionInfo::getArgRegsSaveSize () const inline
Definition at line 176 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), getMaxFPOffset(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), and llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
getArgumentStackSize()
unsigned llvm::ARMFunctionInfo::getArgumentStackSize () const inline
Definition at line 223 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks().
getArgumentStackToRestore()
unsigned llvm::ARMFunctionInfo::getArgumentStackToRestore () const inline
Definition at line 226 of file ARMMachineFunctionInfo.h.
Referenced by getArgumentStackToRestore().
getCoalescedWeight()
DenseMap< constMachineBasicBlock *, unsigned >::iterator llvm::ARMFunctionInfo::getCoalescedWeight (MachineBasicBlock * MBB) inline
Definition at line 264 of file ARMMachineFunctionInfo.h.
References MBB.
Referenced by llvm::ARMBaseRegisterInfo::shouldCoalesce().
getDPRCalleeSavedArea1Offset()
unsigned llvm::ARMFunctionInfo::getDPRCalleeSavedArea1Offset () const inline
Definition at line 199 of file ARMMachineFunctionInfo.h.
getDPRCalleeSavedArea1Size()
unsigned llvm::ARMFunctionInfo::getDPRCalleeSavedArea1Size () const inline
Definition at line 211 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue(), and llvm::Thumb1FrameLowering::emitEpilogue().
getDPRCalleeSavedGapSize()
unsigned llvm::ARMFunctionInfo::getDPRCalleeSavedGapSize () const inline
Definition at line 210 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue().
getFPCXTSaveAreaSize()
unsigned llvm::ARMFunctionInfo::getFPCXTSaveAreaSize () const inline
Definition at line 205 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue().
getFPStatusSavesSize()
unsigned llvm::ARMFunctionInfo::getFPStatusSavesSize () const inline
Definition at line 209 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue().
getFramePtrSpillOffset()
unsigned llvm::ARMFunctionInfo::getFramePtrSpillOffset () const inline
Definition at line 191 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), and llvm::ARMFrameLowering::ResolveFrameIndexReference().
getFrameRecordSavedAreaSize()
unsigned llvm::ARMFunctionInfo::getFrameRecordSavedAreaSize () const inline
Definition at line 206 of file ARMMachineFunctionInfo.h.
Referenced by llvm::Thumb1FrameLowering::emitEpilogue().
getGlobalsPromotedToConstantPool()
SmallPtrSet< const GlobalVariable *, 2 > & llvm::ARMFunctionInfo::getGlobalsPromotedToConstantPool () inline
Definition at line 274 of file ARMMachineFunctionInfo.h.
Referenced by promoteToConstantPool().
getGPRCalleeSavedArea1Offset()
unsigned llvm::ARMFunctionInfo::getGPRCalleeSavedArea1Offset () const inline
Definition at line 197 of file ARMMachineFunctionInfo.h.
getGPRCalleeSavedArea1Size()
unsigned llvm::ARMFunctionInfo::getGPRCalleeSavedArea1Size () const inline
Definition at line 207 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue(), and llvm::Thumb1FrameLowering::emitEpilogue().
getGPRCalleeSavedArea2Offset()
unsigned llvm::ARMFunctionInfo::getGPRCalleeSavedArea2Offset () const inline
Definition at line 198 of file ARMMachineFunctionInfo.h.
getGPRCalleeSavedArea2Size()
unsigned llvm::ARMFunctionInfo::getGPRCalleeSavedArea2Size () const inline
Definition at line 208 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue(), and llvm::Thumb1FrameLowering::emitEpilogue().
getGPRCalleeSavedArea3Size()
unsigned llvm::ARMFunctionInfo::getGPRCalleeSavedArea3Size () const inline
Definition at line 212 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue().
getNumAlignedDPRCS2Regs()
unsigned llvm::ARMFunctionInfo::getNumAlignedDPRCS2Regs () const inline
Definition at line 194 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), and llvm::ARMFrameLowering::spillCalleeSavedRegisters().
getNumPICLabels()
unsigned llvm::ARMFunctionInfo::getNumPICLabels () const inline
Definition at line 233 of file ARMMachineFunctionInfo.h.
getOriginalCPIdx()
unsigned llvm::ARMFunctionInfo::getOriginalCPIdx (unsigned CloneIdx) const inline
Definition at line 255 of file ARMMachineFunctionInfo.h.
References I.
getPreservesR0()
bool llvm::ARMFunctionInfo::getPreservesR0 () const inline
Definition at line 288 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::getCalleeSaves().
getPromotedConstpoolIncrease()
int llvm::ARMFunctionInfo::getPromotedConstpoolIncrease () const inline
Definition at line 277 of file ARMMachineFunctionInfo.h.
Referenced by promoteToConstantPool().
getReturnRegsCount()
unsigned llvm::ARMFunctionInfo::getReturnRegsCount () const inline
Definition at line 179 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::determineCalleeSaves().
getVarArgsFrameIndex()
int llvm::ARMFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 241 of file ARMMachineFunctionInfo.h.
Referenced by LowerVASTART().
hasITBlocks()
bool llvm::ARMFunctionInfo::hasITBlocks () const inline
Definition at line 244 of file ARMMachineFunctionInfo.h.
Referenced by llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo().
hasStackFrame()
bool llvm::ARMFunctionInfo::hasStackFrame () const inline
Definition at line 182 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), estimateRSStackSizeLimit(), and llvm::ARMFrameLowering::ResolveFrameIndexReference().
initializeBaseYamlFields()
void ARMFunctionInfo::initializeBaseYamlFields (const yaml::ARMFunctionInfo & YamlMFI)
Definition at line 23 of file ARMMachineFunctionInfo.cpp.
References llvm::yaml::ARMFunctionInfo::LRSpilled.
initPICLabelUId()
void llvm::ARMFunctionInfo::initPICLabelUId (unsigned UId) inline
Definition at line 229 of file ARMMachineFunctionInfo.h.
isCmseNSCallFunction()
bool llvm::ARMFunctionInfo::isCmseNSCallFunction () const inline
Definition at line 174 of file ARMMachineFunctionInfo.h.
isCmseNSEntryFunction()
bool llvm::ARMFunctionInfo::isCmseNSEntryFunction () const inline
Definition at line 173 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::assignCalleeSavedSpillSlots(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::enableShrinkWrapping(), getMaxFPOffset(), and popRegsFromStack().
isLRSpilled()
bool llvm::ARMFunctionInfo::isLRSpilled () const inline
Definition at line 188 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMBaseInstrInfo::insertOutlinedCall().
isSplitCSR()
bool llvm::ARMFunctionInfo::isSplitCSR () const inline
Definition at line 247 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMBaseRegisterInfo::getCalleeSavedRegsViaCopy().
isThumb1OnlyFunction()
bool llvm::ARMFunctionInfo::isThumb1OnlyFunction () const inline
Definition at line 170 of file ARMMachineFunctionInfo.h.
Referenced by canSpillOnFrameIndexAccess(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::ARMFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), getMaxFPOffset(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::ARMBaseInstrInfo::isFunctionSafeToOutlineFrom(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), and llvm::ARMBaseRegisterInfo::resolveFrameIndex().
isThumb2Function()
bool llvm::ARMFunctionInfo::isThumb2Function () const inline
Definition at line 171 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::isPredicable(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), and llvm::ARMFrameLowering::ResolveFrameIndexReference().
isThumbFunction()
bool llvm::ARMFunctionInfo::isThumbFunction () const inline
Definition at line 169 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMBasicBlockUtils::ARMBasicBlockUtils(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::ARMFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), and llvm::ARMFrameLowering::spillCalleeSavedRegisters().
markGlobalAsPromotedToConstantPool()
void llvm::ARMFunctionInfo::markGlobalAsPromotedToConstantPool (const GlobalVariable * GV) inline
Indicate to the backend that GV has had its storage changed to inside a constant pool.
This means it no longer needs to be emitted as a global variable.
Definition at line 271 of file ARMMachineFunctionInfo.h.
Referenced by promoteToConstantPool().
recordCPEClone()
void llvm::ARMFunctionInfo::recordCPEClone (unsigned CPIdx, unsigned CPCloneIdx) inline
Definition at line 250 of file ARMMachineFunctionInfo.h.
References llvm_unreachable.
setArgRegsSaveSize()
void llvm::ARMFunctionInfo::setArgRegsSaveSize (unsigned s) inline
Definition at line 177 of file ARMMachineFunctionInfo.h.
setArgumentStackSize()
void llvm::ARMFunctionInfo::setArgumentStackSize (unsigned size) inline
Definition at line 224 of file ARMMachineFunctionInfo.h.
References llvm::size().
setArgumentStackToRestore()
void llvm::ARMFunctionInfo::setArgumentStackToRestore (unsigned v) inline
Definition at line 227 of file ARMMachineFunctionInfo.h.
setDPRCalleeSavedArea1Offset()
void llvm::ARMFunctionInfo::setDPRCalleeSavedArea1Offset (unsigned o) inline
Definition at line 203 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setDPRCalleeSavedArea1Size()
void llvm::ARMFunctionInfo::setDPRCalleeSavedArea1Size (unsigned s) inline
Definition at line 220 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setDPRCalleeSavedGapSize()
void llvm::ARMFunctionInfo::setDPRCalleeSavedGapSize (unsigned s) inline
Definition at line 219 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue().
setFPCXTSaveAreaSize()
void llvm::ARMFunctionInfo::setFPCXTSaveAreaSize (unsigned s) inline
Definition at line 214 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue().
setFPStatusSavesSize()
void llvm::ARMFunctionInfo::setFPStatusSavesSize (unsigned s) inline
Definition at line 218 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue().
setFramePtrSpillOffset()
void llvm::ARMFunctionInfo::setFramePtrSpillOffset (unsigned o) inline
Definition at line 192 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setFrameRecordSavedAreaSize()
void llvm::ARMFunctionInfo::setFrameRecordSavedAreaSize (unsigned s) inline
Definition at line 215 of file ARMMachineFunctionInfo.h.
Referenced by llvm::Thumb1FrameLowering::emitPrologue().
setGPRCalleeSavedArea1Offset()
void llvm::ARMFunctionInfo::setGPRCalleeSavedArea1Offset (unsigned o) inline
Definition at line 201 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setGPRCalleeSavedArea1Size()
void llvm::ARMFunctionInfo::setGPRCalleeSavedArea1Size (unsigned s) inline
Definition at line 216 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setGPRCalleeSavedArea2Offset()
void llvm::ARMFunctionInfo::setGPRCalleeSavedArea2Offset (unsigned o) inline
Definition at line 202 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setGPRCalleeSavedArea2Size()
void llvm::ARMFunctionInfo::setGPRCalleeSavedArea2Size (unsigned s) inline
Definition at line 217 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setGPRCalleeSavedArea3Size()
void llvm::ARMFunctionInfo::setGPRCalleeSavedArea3Size (unsigned s) inline
Definition at line 221 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue().
setHasITBlocks()
void llvm::ARMFunctionInfo::setHasITBlocks (bool h) inline
Definition at line 245 of file ARMMachineFunctionInfo.h.
setHasStackFrame()
void llvm::ARMFunctionInfo::setHasStackFrame (bool s) inline
Definition at line 183 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::determineCalleeSaves().
setIsSplitCSR()
void llvm::ARMFunctionInfo::setIsSplitCSR (bool s) inline
Definition at line 248 of file ARMMachineFunctionInfo.h.
setLRIsSpilled()
void llvm::ARMFunctionInfo::setLRIsSpilled (bool s) inline
Definition at line 189 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::determineCalleeSaves().
setNumAlignedDPRCS2Regs()
void llvm::ARMFunctionInfo::setNumAlignedDPRCS2Regs (unsigned n) inline
Definition at line 195 of file ARMMachineFunctionInfo.h.
setPreservesR0()
void llvm::ARMFunctionInfo::setPreservesR0 () inline
Definition at line 287 of file ARMMachineFunctionInfo.h.
setPromotedConstpoolIncrease()
void llvm::ARMFunctionInfo::setPromotedConstpoolIncrease (int Sz) inline
Definition at line 280 of file ARMMachineFunctionInfo.h.
Referenced by promoteToConstantPool().
setReturnRegsCount()
void llvm::ARMFunctionInfo::setReturnRegsCount (unsigned s) inline
Definition at line 180 of file ARMMachineFunctionInfo.h.
setShouldRestoreSPFromFP()
void llvm::ARMFunctionInfo::setShouldRestoreSPFromFP (bool s) inline
Definition at line 186 of file ARMMachineFunctionInfo.h.
Referenced by emitAlignedDPRCS2Spills(), llvm::ARMFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
setVarArgsFrameIndex()
void llvm::ARMFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 242 of file ARMMachineFunctionInfo.h.
shouldRestoreSPFromFP()
bool llvm::ARMFunctionInfo::shouldRestoreSPFromFP () const inline
Definition at line 185 of file ARMMachineFunctionInfo.h.
Referenced by llvm::ARMFrameLowering::emitEpilogue(), and llvm::Thumb1FrameLowering::emitEpilogue().
shouldSignReturnAddress() [1/2]
bool llvm::ARMFunctionInfo::shouldSignReturnAddress () const inline
Definition at line 290 of file ARMMachineFunctionInfo.h.
References shouldSignReturnAddress().
Referenced by llvm::ARMFrameLowering::assignCalleeSavedSpillSlots(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARMFrameLowering::enableShrinkWrapping(), llvm::ARMBaseInstrInfo::getOutliningCandidateInfo(), llvm::ARMSubtarget::getPushPopSplitVariation(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), shouldSignReturnAddress(), and llvm::ARMFrameLowering::spillCalleeSavedRegisters().
shouldSignReturnAddress() [2/2]
bool llvm::ARMFunctionInfo::shouldSignReturnAddress (bool SpillsLR) const inline
Definition at line 294 of file ARMMachineFunctionInfo.h.
Member Data Documentation
EHPrologueOffsetInRegs
DenseMap<unsigned, unsigned> llvm::ARMFunctionInfo::EHPrologueOffsetInRegs
Definition at line 285 of file ARMMachineFunctionInfo.h.
EHPrologueRemappedRegs
DenseMap<unsigned, unsigned> llvm::ARMFunctionInfo::EHPrologueRemappedRegs
Definition at line 284 of file ARMMachineFunctionInfo.h.
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMMachineFunctionInfo.h
lib/Target/ARM/ARMMachineFunctionInfo.cpp