LLVM: llvm::DiagnosticInfoInstrumentation Class Reference
llvm::DiagnosticInfoInstrumentation Class Reference
Diagnostic information for IR instrumentation reporting.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoInstrumentation (const Twine &DiagMsg, DiagnosticSeverity Severity=DS_Warning)
void print (DiagnosticPrinter &DP) const override
Print using the given DP a user-friendly message.
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for IR instrumentation reporting.
Definition at line 1005 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoInstrumentation()
llvm::DiagnosticInfoInstrumentation::DiagnosticInfoInstrumentation (const Twine & DiagMsg, DiagnosticSeverity Severity = DS_Warning) inline
Definition at line 1009 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_Instrumentation, and llvm::DS_Warning.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoInstrumentation::classof (const DiagnosticInfo * DI) inline static
Definition at line 1015 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_Instrumentation, and llvm::DiagnosticInfo::getKind().
print()
void DiagnosticInfoInstrumentation::print (DiagnosticPrinter & DP) const override virtual
Print using the given DP a user-friendly message.
This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implements llvm::DiagnosticInfo.
Definition at line 413 of file DiagnosticInfo.cpp.
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp