LLVM: llvm::objcopy::xcoff::XCOFFReader Class Reference
llvm::objcopy::xcoff::XCOFFReader Class Reference
#include "ObjCopy/XCOFF/XCOFFReader.h"
Public Member Functions
XCOFFReader (const XCOFFObjectFile &O)
Expected< std::unique_ptr< Object > > create () const
Detailed Description
Definition at line 20 of file XCOFFReader.h.
Constructor & Destructor Documentation
XCOFFReader()
llvm::objcopy::xcoff::XCOFFReader::XCOFFReader (const XCOFFObjectFile & O) inline explicit
Definition at line 22 of file XCOFFReader.h.
Member Function Documentation
create()
Expected< std::unique_ptr< Object > > llvm::objcopy::xcoff::XCOFFReader::create () const
Definition at line 74 of file XCOFFReader.cpp.
References llvm::createStringError(), and E().
Referenced by llvm::objcopy::xcoff::executeObjcopyOnBinary().
The documentation for this class was generated from the following files:
lib/ObjCopy/XCOFF/XCOFFReader.h
lib/ObjCopy/XCOFF/XCOFFReader.cpp