LLVM: llvm::sandboxir::Utils Class Reference
llvm::sandboxir::Utils Class Reference
#include "llvm/SandboxIR/Utils.h"
Static Public Member Functions
static Type * getExpectedType (const Value *V)
\Returns the expected type of Value V.
static Value * getExpectedValue (const Instruction *I)
\Returns the expected Value for this instruction.
template<typename LoadOrStoreT>
static Value * getMemInstructionBase (const LoadOrStoreT *LSI)
\Returns the base Value for load or store instruction LSI.
static unsigned getNumBits (Type *Ty, const DataLayout &DL)
\Returns the number of bits of Ty.
static unsigned getNumBits (Value *V, const DataLayout &DL)
\Returns the number of bits required to represent the operands or return value of V in DL.
static unsigned getNumBits (Instruction *I)
\Returns the number of bits required to represent the operands or return value of I.
static std::optional< llvm::MemoryLocation > memoryLocationGetOrNone (const Instruction *I)
Equivalent to MemoryLocation::getOrNone(I).
template<typename LoadOrStoreT>
static std::optional< int > getPointerDiffInBytes (LoadOrStoreT *I0, LoadOrStoreT *I1, ScalarEvolution &SE)
\Returns the gap between the memory locations accessed by I0 and I1 in bytes.
template<typename LoadOrStoreT>
static bool atLowerAddress (LoadOrStoreT *I0, LoadOrStoreT *I1, ScalarEvolution &SE)
\Returns true if I0 accesses a memory location lower than I1.
static ModRefInfo aliasAnalysisGetModRefInfo (BatchAAResults &BatchAA, const Instruction *I, const std::optional< MemoryLocation > &OptLoc)
Equivalent to BatchAA::getModRefInfo().
static bool verifyFunction (const Function *F, raw_ostream &OS)
Equivalent to llvm::verifyFunction().
Detailed Description
Definition at line 27 of file Utils.h.
Member Function Documentation
aliasAnalysisGetModRefInfo()
ModRefInfo llvm::sandboxir::Utils::aliasAnalysisGetModRefInfo (BatchAAResults & BatchAA, const Instruction * I, const std::optional< MemoryLocation > & OptLoc) inline static
Equivalent to BatchAA::getModRefInfo().
Definition at line 123 of file Utils.h.
References llvm::cast(), llvm::BatchAAResults::getModRefInfo(), and I.
atLowerAddress()
template<typename LoadOrStoreT> bool llvm::sandboxir::Utils::atLowerAddress (LoadOrStoreT * I0, LoadOrStoreT * I1, ScalarEvolution & SE) inline static
\Returns true if I0 accesses a memory location lower than I1.
Returns false if the difference cannot be determined, if the memory locations are equal, or if I1 accesses a memory location greater than I0.
Definition at line 113 of file Utils.h.
References getPointerDiffInBytes().
Referenced by llvm::sandboxir::MemSeedBundle< sandboxir::StoreInst >::insert(), and llvm::sandboxir::MemSeedBundle< sandboxir::StoreInst >::MemSeedBundle().
getExpectedType()
Type * llvm::sandboxir::Utils::getExpectedType (const Value * V) inline static
\Returns the expected type of Value V.
For most Values this is equivalent to getType, but for stores returns the stored type, rather than void, and for ReturnInsts returns the returned type.
Definition at line 32 of file Utils.h.
References llvm::dyn_cast(), getExpectedValue(), llvm::sandboxir::Value::getType(), and I.
Referenced by llvm::sandboxir::VecUtils::getCommonScalarType(), getNumBits(), getNumBits(), llvm::sandboxir::VecUtils::getNumLanes(), llvm::sandboxir::isValidMemSeed(), llvm::sandboxir::SeedCollection::runOnFunction(), and llvm::sandboxir::VecUtils::tryGetCommonScalarType().
getExpectedValue()
Value * llvm::sandboxir::Utils::getExpectedValue (const Instruction * I) inline static
\Returns the expected Value for this instruction.
For most instructions, this is the instruction itself, but for stores returns the stored operand, and for ReturnInstructions returns the returned value.
Definition at line 47 of file Utils.h.
References llvm::dyn_cast(), and I.
Referenced by getExpectedType().
getMemInstructionBase()
template<typename LoadOrStoreT> Value * llvm::sandboxir::Utils::getMemInstructionBase (const LoadOrStoreT * LSI) inline static
\Returns the base Value for load or store instruction LSI.
Definition at line 57 of file Utils.h.
References llvm::sandboxir::Value::Ctx, llvm::sandboxir::Context::getOrCreateValue(), and llvm::getUnderlyingObject().
getNumBits() [1/3]
unsigned llvm::sandboxir::Utils::getNumBits (Instruction * I) inline static
\Returns the number of bits required to represent the operands or return value of I.
Definition at line 79 of file Utils.h.
References getExpectedType(), and I.
getNumBits() [2/3]
unsigned llvm::sandboxir::Utils::getNumBits (Type * Ty, const DataLayout & DL) inline static
\Returns the number of bits of Ty.
Definition at line 66 of file Utils.h.
References DL.
Referenced by llvm::sandboxir::VecUtils::areConsecutive(), getNumBits(), llvm::sandboxir::SeedBundle::getSlice(), llvm::sandboxir::SeedBundle::insertAt(), llvm::sandboxir::SeedCollection::runOnFunction(), llvm::sandboxir::SeedBundle::SeedBundle(), and llvm::sandboxir::SeedBundle::setUsed().
getNumBits() [3/3]
unsigned llvm::sandboxir::Utils::getNumBits (Value * V, const DataLayout & DL) inline static
\Returns the number of bits required to represent the operands or return value of V in DL.
Definition at line 72 of file Utils.h.
References DL, getExpectedType(), and getNumBits().
getPointerDiffInBytes()
template<typename LoadOrStoreT> std::optional< int > llvm::sandboxir::Utils::getPointerDiffInBytes (LoadOrStoreT * I0, LoadOrStoreT * I1, ScalarEvolution & SE) inline static
\Returns the gap between the memory locations accessed by I0 and I1 in bytes.
Definition at line 92 of file Utils.h.
References llvm::ScalarEvolution::getContext(), llvm::Type::getInt8Ty(), llvm::getPointersDiff(), and llvm::getUnderlyingObject().
Referenced by llvm::sandboxir::VecUtils::areConsecutive(), and atLowerAddress().
memoryLocationGetOrNone()
std::optional< llvm::MemoryLocation > llvm::sandboxir::Utils::memoryLocationGetOrNone (const Instruction * I) inline static
Equivalent to MemoryLocation::getOrNone(I).
Definition at line 85 of file Utils.h.
References llvm::cast(), llvm::MemoryLocation::getOrNone(), and I.
verifyFunction()
bool llvm::sandboxir::Utils::verifyFunction (const Function * F, raw_ostream & OS) inline static
Equivalent to llvm::verifyFunction().
\Returns true if the IR is broken.
Definition at line 130 of file Utils.h.
References llvm::cast(), F, and llvm::verifyFunction().
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Utils.h