LLVM: llvm::coro::AnyRetconABI Class Reference
llvm::coro::AnyRetconABI Class Reference
#include "llvm/Transforms/Coroutines/ABI.h"
Public Member Functions
AnyRetconABI (Function &F, coro::Shape &S, std::function< bool(Instruction &)> IsMaterializable)
void init () override
void splitCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones, TargetTransformInfo &TTI) override
Public Member Functions inherited from llvm::coro::BaseABI
BaseABI (Function &F, coro::Shape &S, std::function< bool(Instruction &)> IsMaterializable)
virtual ~BaseABI ()=default
virtual void buildCoroutineFrame (bool OptimizeFrame)
Additional Inherited Members
Public Attributes inherited from llvm::coro::BaseABI
Function & F
coro::Shape & Shape
std::function< bool(Instruction &I)> IsMaterializable
Detailed Description
Definition at line 93 of file ABI.h.
Constructor & Destructor Documentation
AnyRetconABI()
llvm::coro::AnyRetconABI::AnyRetconABI (Function & F, coro::Shape & S, std::function< bool(Instruction &)> IsMaterializable) inline
Definition at line 95 of file ABI.h.
References llvm::coro::BaseABI::BaseABI(), llvm::coro::BaseABI::F, llvm::coro::BaseABI::IsMaterializable, and llvm::move().
Member Function Documentation
init()
void coro::AnyRetconABI::init () override virtual
Implements llvm::coro::BaseABI.
Definition at line 388 of file Coroutines.cpp.
References assert(), llvm::dyn_cast(), I, llvm::CastInst::isBitCastable(), llvm::Type::isVoidTy(), llvm::report_fatal_error(), llvm::coro::Retcon, llvm::coro::RetconOnce, llvm::coro::BaseABI::Shape, and llvm::ArrayRef< T >::size().
splitCoroutine()
void coro::AnyRetconABI::splitCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones, TargetTransformInfo & TTI) override virtual
Implements llvm::coro::BaseABI.
Definition at line 1809 of file CoroSplit.cpp.
References llvm::PHINode::addIncoming(), assert(), llvm::cast(), llvm::coro::Continuation, llvm::BasicBlock::Create(), llvm::coro::BaseCloner::createClone(), createCloneDeclaration(), DL, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::enumerate(), llvm::coro::BaseABI::F, llvm::PoisonValue::get(), llvm::TrackingVH< ValueTy >::getValPtr(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::coro::Retcon, llvm::coro::RetconOnce, llvm::coro::BaseABI::Shape, Size, llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::zip_equal().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Coroutines/ABI.h
lib/Transforms/Coroutines/CoroSplit.cpp
lib/Transforms/Coroutines/Coroutines.cpp