LLVM: llvm::UniformityInfoPrinterPass Class Reference
llvm::UniformityInfoPrinterPass Class Reference
Printer pass for the UniformityInfo.
#include "llvm/Analysis/UniformityAnalysis.h"
Public Member Functions
UniformityInfoPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< UniformityInfoPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< UniformityInfoPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the UniformityInfo.
Definition at line 44 of file UniformityAnalysis.h.
Constructor & Destructor Documentation
UniformityInfoPrinterPass()
UniformityInfoPrinterPass::UniformityInfoPrinterPass (raw_ostream & OS) explicit
Definition at line 129 of file UniformityAnalysis.cpp.
Member Function Documentation
isRequired()
bool llvm::UniformityInfoPrinterPass::isRequired () inline static
Definition at line 53 of file UniformityAnalysis.h.
run()
PreservedAnalyses UniformityInfoPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 132 of file UniformityAnalysis.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/UniformityAnalysis.h
lib/Analysis/UniformityAnalysis.cpp