LLVM: lib/CodeGen/CodeGenTargetMachineImpl.cpp File Reference
CodeGenTargetMachineImpl.cpp File Reference
#include "llvm/CodeGen/CodeGenTargetMachineImpl.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Target/RegisterTargetPassConfigCallback.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
Functions
static TargetPassConfig * addPassesToGenerateCode (CodeGenTargetMachineImpl &TM, PassManagerBase &PM, bool DisableVerify, MachineModuleInfoWrapperPass &MMIWP)
addPassesToX helper drives creation and initialization of TargetPassConfig.
Variables
static cl::opt< bool > EnableTrapUnreachable ("trap-unreachable", cl::Hidden, cl::desc("Enable generating trap for unreachable"))
static cl::opt< bool > EnableNoTrapAfterNoreturn ("no-trap-after-noreturn", cl::Hidden, cl::desc("Do not emit a trap instruction for 'unreachable' IR instructions " "after noreturn calls, even if --trap-unreachable is set."))
Function Documentation
addPassesToGenerateCode()
TargetPassConfig * addPassesToGenerateCode (CodeGenTargetMachineImpl & TM, PassManagerBase & PM, bool DisableVerify, MachineModuleInfoWrapperPass & MMIWP) static
addPassesToX helper drives creation and initialization of TargetPassConfig.
Definition at line 116 of file CodeGenTargetMachineImpl.cpp.
References llvm::legacy::PassManagerBase::add(), llvm::TargetPassConfig::addISelPasses(), llvm::TargetPassConfig::addMachinePasses(), llvm::invokeGlobalTargetPassConfigCallbacks(), llvm::TargetPassConfig::setDisableVerify(), and llvm::TargetPassConfig::setInitialized().
Referenced by llvm::CodeGenTargetMachineImpl::addPassesToEmitFile(), and llvm::CodeGenTargetMachineImpl::addPassesToEmitMC().
Variable Documentation
EnableNoTrapAfterNoreturn
cl::opt< bool > EnableNoTrapAfterNoreturn("no-trap-after-noreturn", cl::Hidden, cl::desc("Do not emit a trap instruction for 'unreachable' IR instructions " "after noreturn calls, even if --trap-unreachable is set.")) ("no-trap-after-noreturn" , cl::Hidden , cl::desc("Do not emit a trap instruction for 'unreachable' IR instructions " "after noreturn calls, even if --trap-unreachable is set.")) static
Referenced by llvm::CodeGenTargetMachineImpl::CodeGenTargetMachineImpl().
EnableTrapUnreachable
cl::opt< bool > EnableTrapUnreachable("trap-unreachable", cl::Hidden, cl::desc("Enable generating trap for unreachable")) ("trap-unreachable" , cl::Hidden , cl::desc("Enable generating trap for unreachable")) static
Referenced by llvm::CodeGenTargetMachineImpl::CodeGenTargetMachineImpl().