LLVM: lib/Transforms/Utils/Debugify.cpp File Reference
Debugify.cpp File Reference
#include "llvm/Transforms/Utils/Debugify.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassInstrumentation.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/JSON.h"
#include <optional>
Macros
#define DEBUG_TYPE "debugify"
Functions
static bool applyDebugify (Function &F, enum DebugifyMode Mode, DebugInfoPerPass *DebugInfoBeforePass, StringRef NameOfWrappedPass="")
static bool applyDebugify (Module &M, enum DebugifyMode Mode, DebugInfoPerPass *DebugInfoBeforePass, StringRef NameOfWrappedPass="")
bool hasLoc (const Instruction &I)
static bool checkFunctions (const DebugFnMap &DIFunctionsBefore, const DebugFnMap &DIFunctionsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array &Bugs)
static bool checkInstructions (const DebugInstMap &DILocsBefore, const DebugInstMap &DILocsAfter, const WeakInstValueMap &InstToDelete, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array &Bugs)
static bool checkVars (const DebugVarMap &DIVarsBefore, const DebugVarMap &DIVarsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array &Bugs)
static void writeJSON (StringRef OrigDIVerifyBugsReportFilePath, StringRef FileNameFromCU, StringRef NameOfWrappedPass, llvm::json::Array &Bugs)
ModulePass * createDebugifyModulePass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass *DebugInfoBeforePass)
FunctionPass * createDebugifyFunctionPass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass *DebugInfoBeforePass)
ModulePass * createCheckDebugifyModulePass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap *StatsMap, enum DebugifyMode Mode, DebugInfoPerPass *DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
FunctionPass * createCheckDebugifyFunctionPass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap *StatsMap, enum DebugifyMode Mode, DebugInfoPerPass *DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
static bool isIgnoredPass (StringRef PassID)
Variables
static RegisterPass< DebugifyModulePass > DM ("debugify", "Attach debug info to everything")
static RegisterPass< CheckDebugifyModulePass > CDM ("check-debugify", "Check debug info from -debugify")
static RegisterPass< DebugifyFunctionPass > DF ("debugify-function", "Attach debug info to a function")
static RegisterPass< CheckDebugifyFunctionPass > CDF ("check-debugify-function", "Check debug info from -debugify-function")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "debugify"
Definition at line 39 of file Debugify.cpp.
Function Documentation
applyDebugify() [1/2]
bool applyDebugify (Function & F, enum DebugifyMode Mode, DebugInfoPerPass * DebugInfoBeforePass, StringRef NameOfWrappedPass = "") static
Definition at line 281 of file Debugify.cpp.
References llvm::applyDebugifyMetadata(), assert(), llvm::collectDebugInfoMetadata(), F, llvm::make_range(), Mode, and SyntheticDebugInfo.
Referenced by llvm::DebugifyEachInstrumentation::registerCallbacks().
applyDebugify() [2/2]
bool applyDebugify (Module & M, enum DebugifyMode Mode, DebugInfoPerPass * DebugInfoBeforePass, StringRef NameOfWrappedPass = "") static
Definition at line 295 of file Debugify.cpp.
References llvm::applyDebugifyMetadata(), assert(), llvm::collectDebugInfoMetadata(), Mode, and SyntheticDebugInfo.
checkFunctions()
bool checkFunctions (const DebugFnMap & DIFunctionsBefore, const DebugFnMap & DIFunctionsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array & Bugs) static
Definition at line 444 of file Debugify.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), F, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), and llvm::json::Array::push_back().
Referenced by llvm::checkDebugInfoMetadata().
checkInstructions()
bool checkInstructions (const DebugInstMap & DILocsBefore, const DebugInstMap & DILocsAfter, const WeakInstValueMap & InstToDelete, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array & Bugs) static
Definition at line 486 of file Debugify.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), llvm::Instruction::getOpcodeName(), and llvm::json::Array::push_back().
Referenced by llvm::checkDebugInfoMetadata().
checkVars()
bool checkVars (const DebugVarMap & DIVarsBefore, const DebugVarMap & DIVarsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array & Bugs) static
Definition at line 552 of file Debugify.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), and llvm::json::Array::push_back().
Referenced by llvm::checkDebugInfoMetadata().
createCheckDebugifyFunctionPass()
FunctionPass * createCheckDebugifyFunctionPass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap * StatsMap, enum DebugifyMode Mode, DebugInfoPerPass * DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
Definition at line 1089 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createCheckDebugifyModulePass()
ModulePass * createCheckDebugifyModulePass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap * StatsMap, enum DebugifyMode Mode, DebugInfoPerPass * DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
Definition at line 1077 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyFunctionPass()
FunctionPass * createDebugifyFunctionPass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass * DebugInfoBeforePass)
Definition at line 1054 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyModulePass()
ModulePass * createDebugifyModulePass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass * DebugInfoBeforePass)
Definition at line 1044 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
hasLoc()
bool hasLoc (const Instruction & I)
Definition at line 357 of file Debugify.cpp.
References I.
Referenced by llvm::checkDebugInfoMetadata(), and llvm::collectDebugInfoMetadata().
isIgnoredPass()
bool isIgnoredPass (StringRef PassID) static
Definition at line 1115 of file Debugify.cpp.
References llvm::isSpecialPass().
Referenced by llvm::DebugifyEachInstrumentation::registerCallbacks().
writeJSON()
void writeJSON (StringRef OrigDIVerifyBugsReportFilePath, StringRef FileNameFromCU, StringRef NameOfWrappedPass, llvm::json::Array & Bugs) static
Definition at line 585 of file Debugify.cpp.
References llvm::raw_fd_ostream::close(), llvm::errs(), llvm::raw_fd_ostream::lock(), llvm::sys::fs::OF_Append, llvm::sys::fs::OF_TextWithCRLF, and PassName.
Referenced by llvm::checkDebugInfoMetadata().
Variable Documentation
CDF
RegisterPass< CheckDebugifyFunctionPass > CDF("check-debugify-function", "Check debug info from -debugify-function") ("check-debugify-function" , "Check debug info from -debugify-function") static
CDM
RegisterPass< CheckDebugifyModulePass > CDM("check-debugify", "Check debug info from -debugify") ("check-debugify" , "Check debug info from -debugify") static
DF
RegisterPass< DebugifyFunctionPass > DF("debugify-function", "Attach debug info to a function") ("debugify-function" , "Attach debug info to a function") static
Referenced by attemptToFoldSymbolOffsetDifference(), llvm::RegionBase< RegionTraits< MachineFunction > >::clearNodeCache(), llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::DILocation::cloneWithBaseDiscriminator(), llvm::DILocation::decodeDiscriminator(), llvm::DWARFContext::dump(), llvm::MCObjectStreamer::emitBytes(), llvm::MCWinCOFFStreamer::emitCOFFImgRel32(), llvm::MCWinCOFFStreamer::emitCOFFSecNumber(), llvm::MCWinCOFFStreamer::emitCOFFSecOffset(), llvm::MCWinCOFFStreamer::emitCOFFSecRel32(), llvm::MCWinCOFFStreamer::emitCOFFSectionIndex(), llvm::MipsTargetELFStreamer::emitDTPRel32Value(), llvm::MipsTargetELFStreamer::emitDTPRel64Value(), llvm::MipsTargetELFStreamer::emitGPRel32Value(), llvm::MipsTargetELFStreamer::emitGPRel64Value(), llvm::MCObjectStreamer::emitRelocDirective(), llvm::MipsTargetELFStreamer::emitTPRel32Value(), llvm::MipsTargetELFStreamer::emitTPRel64Value(), EmitUnwindInfo(), llvm::MCObjectStreamer::emitValueImpl(), llvm::MCXCOFFStreamer::emitXCOFFRefDirective(), llvm::DILocation::encodeDiscriminator(), getOffsetAndDataFragment(), getPCRelHiFixup(), getSizeForInstFragment(), llvm::MCAsmBackend::getSubtargetInfo(), llvm::MCInstrInfo::InitMCInstrInfo(), isRightAfterData(), llvm::MCAssembler::layoutBundle(), llvm::LoongArchAsmBackend::relaxDwarfCFA(), llvm::MCAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::LoongArchAsmBackend::relaxDwarfLineAddr(), llvm::MCAsmBackend::relaxDwarfLineAddr(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::DominanceFrontierAnalysis::run(), llvm::RegionInfoAnalysis::run(), llvm::RegionInfoPass::runOnFunction(), llvm::MachineRegionInfoPass::runOnMachineFunction(), llvm::MCAssembler::writeSectionData(), and llvm::RISCVAsmBackend::~RISCVAsmBackend().
DM
RegisterPass< DebugifyModulePass > DM("debugify", "Attach debug info to everything") ("debugify" , "Attach debug info to everything") static
Referenced by llvm::PMDataManager::add(), llvm::rdf::DataFlowGraph::build(), llvm::pdb::UDTLayoutBase::initializeChildren(), llvm::PPC::isXXPERMDIShuffleMask(), and llvm::PMTopLevelManager::schedulePass().