LLVM: lib/IR/DebugInfoMetadata.cpp File Reference
DebugInfoMetadata.cpp File Reference
#include "llvm/IR/DebugInfoMetadata.h"
#include "LLVMContextImpl.h"
#include "MetadataImpl.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/DebugProgramInstruction.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include <numeric>
#include <optional>
#include "llvm/IR/DebugInfoFlags.def"
Classes
struct EqualScopesMatcher
struct ScopeLocationsMatcher
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define HANDLE_DI_FLAG(ID, NAME)
#define HANDLE_DI_FLAG(ID, NAME)
#define HANDLE_DI_FLAG(ID, NAME)
#define UNWRAP_ARGS_IMPL(...)
#define UNWRAP_ARGS(ARGS)
#define DEFINE_GETIMPL_LOOKUP(CLASS, ARGS)
#define DEFINE_GETIMPL_STORE(CLASS, ARGS, OPS)
#define DEFINE_GETIMPL_STORE_NO_OPS(CLASS, ARGS)
#define DEFINE_GETIMPL_STORE_NO_CONSTRUCTOR_ARGS(CLASS, OPS)
#define DEFINE_GETIMPL_STORE_N(CLASS, ARGS, OPS, NUM_OPS)
#define HANDLE_DISP_FLAG(ID, NAME)
#define HANDLE_DISP_FLAG(ID, NAME)
#define HANDLE_DISP_FLAG(ID, NAME)
Typedefs
using LineColumn = std::pair<unsigned , unsigned >
Functions
cl::opt< bool > llvm::EnableFSDiscriminator ("enable-fs-discriminator", cl::Hidden, cl::desc("Enable adding flow sensitive discriminators"))
LLVM_ABI cl::opt< bool > llvm::PickMergedSourceLocations ("pick-merged-source-locations", cl::init(false), cl::Hidden, cl::desc("Preserve line and column number when merging locations."))
static void adjustColumn (unsigned &Column)
static DILexicalBlockBase * cloneAndReplaceParentScope (DILexicalBlockBase *LBB, DIScope *NewParent)
static LineColumn getLocalScopeLocationOr (DIScope *S, LineColumn Default)
Returns the location of DILocalScope, if present, or a default value.
template<typename MatcherT>
static std::pair< DIScope *, LineColumn > getNearestMatchingScope (const DILocation *L1, const DILocation *L2)
static bool isCanonical (const MDString *S)
Variables
static const char * ChecksumKindName [DIFile::CSK_Last]
Macro Definition Documentation
DEFINE_GETIMPL_LOOKUP
#define DEFINE_GETIMPL_LOOKUP (CLASS, ARGS)
Value:
  do {                                                                         \
    if (Storage == Uniqued) {                                                  \
      if (auto *N = getUniqued(Context.pImpl->CLASS##s,                        \
                               CLASS##Info::KeyTy(UNWRAP_ARGS(ARGS))))         \
        return N;                                                              \
      if (!ShouldCreate)                                                       \
        return nullptr;                                                        \
    } else {                                                                   \
      assert(ShouldCreate &&                                                   \
             "Expected non-uniqued nodes to always be created");               \
    }                                                                          \
  } while (false)
Definition at line 602 of file DebugInfoMetadata.cpp.
Referenced by llvm::DIBasicType::getImpl().
DEFINE_GETIMPL_STORE
#define DEFINE_GETIMPL_STORE (CLASS, ARGS, OPS)
Value:
  return storeImpl(new (std::size(OPS), Storage)                               \
                       CLASS(Context, Storage, UNWRAP_ARGS(ARGS), OPS),        \
                   Storage, Context.pImpl->CLASS##s)
Definition at line 615 of file DebugInfoMetadata.cpp.
Referenced by llvm::DIBasicType::getImpl().
DEFINE_GETIMPL_STORE_N
#define DEFINE_GETIMPL_STORE_N (CLASS, ARGS, OPS, NUM_OPS)
Value:
  return storeImpl(new (NUM_OPS, Storage)                                      \
                       CLASS(Context, Storage, UNWRAP_ARGS(ARGS), OPS),        \
                   Storage, Context.pImpl->CLASS##s)
Definition at line 626 of file DebugInfoMetadata.cpp.
DEFINE_GETIMPL_STORE_NO_CONSTRUCTOR_ARGS
#define DEFINE_GETIMPL_STORE_NO_CONSTRUCTOR_ARGS (CLASS, OPS)
Value:
  return storeImpl(new (std::size(OPS), Storage) CLASS(Context, Storage, OPS), \
                   Storage, Context.pImpl->CLASS##s)
Definition at line 623 of file DebugInfoMetadata.cpp.
DEFINE_GETIMPL_STORE_NO_OPS
#define DEFINE_GETIMPL_STORE_NO_OPS (CLASS, ARGS)
Value:
  return storeImpl(new (0u, Storage)                                           \
                       CLASS(Context, Storage, UNWRAP_ARGS(ARGS)),             \
                   Storage, Context.pImpl->CLASS##s)
Definition at line 619 of file DebugInfoMetadata.cpp.
HANDLE_DI_FLAG [1/3]
#define HANDLE_DI_FLAG (ID, NAME)
Value:
.Case("DIFlag" #NAME, Flag##NAME)
HANDLE_DI_FLAG [2/3]
#define HANDLE_DI_FLAG (ID, NAME)
Value:
  case Flag##NAME:                                                             \
    return "DIFlag" #NAME;
HANDLE_DI_FLAG [3/3]
#define HANDLE_DI_FLAG (ID, NAME)
Value:
  if (DIFlags Bit = Flags & Flag##NAME) {                                      \
    SplitFlags.push_back(Bit);                                                 \
    Flags &= ~Bit;                                                             \
  }
HANDLE_DISP_FLAG [1/3]
#define HANDLE_DISP_FLAG (ID, NAME)
Value:
.Case("DISPFlag" #NAME, SPFlag##NAME)
HANDLE_DISP_FLAG [2/3]
#define HANDLE_DISP_FLAG (ID, NAME)
Value:
  case SPFlag##NAME:                                                           \
    return "DISPFlag" #NAME;
HANDLE_DISP_FLAG [3/3]
#define HANDLE_DISP_FLAG (ID, NAME)
Value:
  if (DISPFlags Bit = Flags & SPFlag##NAME) {                                  \
    SplitFlags.push_back(Bit);                                                 \
    Flags &= ~Bit;                                                             \
  }
UNWRAP_ARGS
#define UNWRAP_ARGS (ARGS)
Value:
UNWRAP_ARGS_IMPL ARGS
Definition at line 601 of file DebugInfoMetadata.cpp.
UNWRAP_ARGS_IMPL
#define UNWRAP_ARGS_IMPL (...)
Value:
__VA_ARGS__
Definition at line 600 of file DebugInfoMetadata.cpp.
Typedef Documentation
LineColumn
using LineColumn = std::pair<unsigned , unsigned >
Definition at line 150 of file DebugInfoMetadata.cpp.
Function Documentation
adjustColumn()
void adjustColumn (unsigned & Column) static
Definition at line 92 of file DebugInfoMetadata.cpp.
cloneAndReplaceParentScope()
DILexicalBlockBase * cloneAndReplaceParentScope (DILexicalBlockBase * LBB, DIScope * NewParent) static
Definition at line 142 of file DebugInfoMetadata.cpp.
References llvm::cast(), llvm::MDNode::clone(), and llvm::MDNode::replaceWithUniqued().
Referenced by llvm::DILocalScope::cloneScopeForSubprogram(), and llvm::DILocation::getMergedLocation().
getLocalScopeLocationOr()
LineColumn getLocalScopeLocationOr (DIScope * S, LineColumn Default) static
Returns the location of DILocalScope, if present, or a default value.
Definition at line 153 of file DebugInfoMetadata.cpp.
References assert(), Default, llvm::dyn_cast(), llvm::isa(), and llvm_unreachable.
Referenced by getNearestMatchingScope().
getNearestMatchingScope()
template<typename MatcherT> std::pair< DIScope *, LineColumn > getNearestMatchingScope (const DILocation * L1, const DILocation * L2) static
Definition at line 169 of file DebugInfoMetadata.cpp.
References getLocalScopeLocationOr(), llvm::DIScope::getScope(), llvm::isa(), and S1.
Referenced by llvm::DILocation::getMergedLocation().
isCanonical()
bool isCanonical (const MDString * S) static
Definition at line 566 of file DebugInfoMetadata.cpp.
References llvm::StringRef::empty(), and llvm::MDString::getString().
Referenced by llvm::DIBasicType::getImpl().
Variable Documentation
ChecksumKindName
const char* ChecksumKindName[DIFile::CSK_Last] static
Initial value:
= {
    "CSK_MD5",
    "CSK_SHA1",
    "CSK_SHA256",
}
Definition at line 1160 of file DebugInfoMetadata.cpp.