LLVM: include/llvm/Transforms/Utils/Debugify.h File Reference
Debugify.h File Reference
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Bitcode/BitcodeWriterPass.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassInstrumentation.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
#include "llvm/Support/Compiler.h"
Classes
struct DebugInfoPerPass
Used to track the Debug Info Metadata information.
class NewPMDebugifyPass
struct DebugifyStatistics
Track how much debugify information (in the synthetic mode only) has been lost.
class NewPMCheckDebugifyPass
class llvm::DebugifyEachInstrumentation
class llvm::DebugifyCustomPassManager
DebugifyCustomPassManager wraps each pass with the debugify passes if needed.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Typedefs
using DebugFnMap
using DebugInstMap = llvm::MapVector<const llvm::Instruction *, bool>
using DebugVarMap = llvm::MapVector<const llvm::DILocalVariable *, unsigned>
using WeakInstValueMap
using DebugifyStatsMap = llvm::MapVector<llvm::StringRef, DebugifyStatistics>
Map pass names to a per-pass DebugifyStatistics instance.
Enumerations
enum class DebugifyMode { NoDebugify , SyntheticDebugInfo , OriginalDebugInfo }
Used to check whether we track synthetic or original debug info.
Functions
LLVM_ABI bool llvm::applyDebugifyMetadata (Module &M, iterator_range< Module::iterator > Functions, StringRef Banner, std::function< bool(DIBuilder &, Function &)> ApplyToMF)
Add synthesized debug information to a module.
LLVM_ABI bool llvm::stripDebugifyMetadata (Module &M)
Strip out all of the metadata and debug info inserted by debugify.
LLVM_ABI bool llvm::collectDebugInfoMetadata (Module &M, iterator_range< Module::iterator > Functions, DebugInfoPerPass &DebugInfoBeforePass, StringRef Banner, StringRef NameOfWrappedPass)
Collect original debug information before a pass.
LLVM_ABI bool llvm::checkDebugInfoMetadata (Module &M, iterator_range< Module::iterator > Functions, DebugInfoPerPass &DebugInfoBeforePass, StringRef Banner, StringRef NameOfWrappedPass, StringRef OrigDIVerifyBugsReportFilePath)
Check original debug information after a pass.
LLVM_ABI llvm::ModulePass * createDebugifyModulePass (enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass="", DebugInfoPerPass *DebugInfoBeforePass=nullptr)
LLVM_ABI llvm::FunctionPass * createDebugifyFunctionPass (enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass="", DebugInfoPerPass *DebugInfoBeforePass=nullptr)
LLVM_ABI llvm::ModulePass * createCheckDebugifyModulePass (bool Strip=false, llvm::StringRef NameOfWrappedPass="", DebugifyStatsMap *StatsMap=nullptr, enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass *DebugInfoBeforePass=nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath="")
LLVM_ABI llvm::FunctionPass * createCheckDebugifyFunctionPass (bool Strip=false, llvm::StringRef NameOfWrappedPass="", DebugifyStatsMap *StatsMap=nullptr, enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass *DebugInfoBeforePass=nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath="")
LLVM_ABI void llvm::exportDebugifyStats (StringRef Path, const DebugifyStatsMap &Map)
Typedef Documentation
DebugFnMap
using DebugFnMap
Initial value:
    llvm::MapVector<const llvm::Function *, const llvm::DISubprogram *>
Definition at line 29 of file Debugify.h.
DebugifyStatsMap
using DebugifyStatsMap = llvm::MapVector<llvm::StringRef, DebugifyStatistics>
Map pass names to a per-pass DebugifyStatistics instance.
Definition at line 152 of file Debugify.h.
DebugInstMap
using DebugInstMap = llvm::MapVector<const llvm::Instruction *, bool>
Definition at line 31 of file Debugify.h.
DebugVarMap
using DebugVarMap = llvm::MapVector<const llvm::DILocalVariable *, unsigned>
Definition at line 32 of file Debugify.h.
WeakInstValueMap
using WeakInstValueMap
Initial value:
    llvm::MapVector<const llvm::Instruction *, llvm::WeakVH>
Definition at line 33 of file Debugify.h.
Enumeration Type Documentation
DebugifyMode
enum class DebugifyMode strong
Used to check whether we track synthetic or original debug info.
Enumerator
NoDebugify
SyntheticDebugInfo
OriginalDebugInfo
Definition at line 98 of file Debugify.h.
Function Documentation
createCheckDebugifyFunctionPass()
LLVM_ABI llvm::FunctionPass * createCheckDebugifyFunctionPass (bool Strip = false, llvm::StringRef NameOfWrappedPass = "", DebugifyStatsMap * StatsMap = nullptr, enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass * DebugInfoBeforePass = nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath = "")
Definition at line 1089 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createCheckDebugifyModulePass()
LLVM_ABI llvm::ModulePass * createCheckDebugifyModulePass (bool Strip = false, llvm::StringRef NameOfWrappedPass = "", DebugifyStatsMap * StatsMap = nullptr, enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass * DebugInfoBeforePass = nullptr, llvm::StringRef OrigDIVerifyBugsReportFilePath = "")
Definition at line 1077 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyFunctionPass()
LLVM_ABI llvm::FunctionPass * createDebugifyFunctionPass (enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass = "", DebugInfoPerPass * DebugInfoBeforePass = nullptr)
Definition at line 1054 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyModulePass()
LLVM_ABI llvm::ModulePass * createDebugifyModulePass (enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass = "", DebugInfoPerPass * DebugInfoBeforePass = nullptr)
Definition at line 1044 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().