LLVM: lib/Target/DirectX/DirectXTargetMachine.cpp File Reference
DirectXTargetMachine.cpp File Reference
This file contains DirectX target initializer.
#include "DirectXTargetMachine.h"
#include "DXILCBufferAccess.h"
#include "DXILDataScalarization.h"
#include "DXILFlattenArrays.h"
#include "DXILForwardHandleAccesses.h"
#include "DXILIntrinsicExpansion.h"
#include "DXILLegalizePass.h"
#include "DXILOpLowering.h"
#include "DXILPostOptimizationValidation.h"
#include "DXILPrettyPrinter.h"
#include "DXILResourceAccess.h"
#include "DXILResourceImplicitBinding.h"
#include "DXILRootSignature.h"
#include "DXILShaderFlags.h"
#include "DXILTranslateMetadata.h"
#include "DXILWriter/DXILWriterPass.h"
#include "DirectX.h"
#include "DirectXSubtarget.h"
#include "DirectXTargetTransformInfo.h"
#include "TargetInfo/DirectXTargetInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCSectionDXContainer.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Transforms/Scalar/Scalarizer.h"
#include <optional>
#include "llvm/Passes/TargetPassRegistry.inc"
Classes
class DXILTargetObjectFile
class DirectXPassConfig
Macros
#define GET_PASS_REGISTRY "DirectXPassRegistry.def"
#define ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
#define ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
#define MODULE_ANALYSIS(NAME, CREATE_PASS)
#define MODULE_PASS(NAME, CREATE_PASS)
#define MODULE_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define FUNCTION_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_ALIAS_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_PASS(NAME, CREATE_PASS)
#define FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define LOOP_ANALYSIS(NAME, CREATE_PASS)
#define LOOP_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_ANALYSIS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define ADD_PASS(NAME, CREATE_PASS)
#define ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
#define MODULE_PASS(NAME, CREATE_PASS)
#define MODULE_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define FUNCTION_PASS(NAME, CREATE_PASS)
#define FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define LOOP_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define MODULE_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_ALIAS_ANALYSIS(NAME, CREATE_PASS)
#define LOOP_ANALYSIS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_ANALYSIS(NAME, CREATE_PASS)
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeDirectXTarget ()
Detailed Description
This file contains DirectX target initializer.
Definition in file DirectXTargetMachine.cpp.
Macro Definition Documentation
ADD_CLASS_PASS_TO_PASS_NAME
#define ADD_CLASS_PASS_TO_PASS_NAME (NAME, CREATE_PASS)
Value:
  PIC->addClassToPassName(decltype(CREATE_PASS)::name(), NAME);
ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS
#define ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS (NAME, CLASS)
Value:
  PIC->addClassToPassName(CLASS, NAME);
ADD_PASS
#define ADD_PASS (NAME, CREATE_PASS)
Value:
  if (Name == NAME) {                                                          \
    PM.addPass(CREATE_PASS);                                                   \
    return true;                                                               \
  }
ADD_PASS_WITH_PARAMS
#define ADD_PASS_WITH_PARAMS (NAME, CREATE_PASS, PARSER)
Value:
  if (PassBuilder::checkParametrizedPassName(Name, NAME)) {                    \
    auto Params = PassBuilder::parsePassParameters(PARSER, Name, NAME);        \
    if (!Params) {                                                             \
      errs() << NAME ": " << toString(Params.takeError()) << '\n';             \
      return false;                                                            \
    }                                                                          \
    PM.addPass(CREATE_PASS(Params.get()));                                     \
    return true;                                                               \
  }
FUNCTION_ALIAS_ANALYSIS [1/2]
#define FUNCTION_ALIAS_ANALYSIS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
FUNCTION_ALIAS_ANALYSIS [2/2]
#define FUNCTION_ALIAS_ANALYSIS (NAME, CREATE_PASS)
Value:
  if (Name == NAME) {                                                          \
    AM.registerFunctionAnalysis<                                               \
        std::remove_reference_t<decltype(CREATE_PASS)>>();                     \
    return true;                                                               \
  }
FUNCTION_ANALYSIS [1/2]
#define FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
FUNCTION_ANALYSIS [2/2]
#define FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
  AM.registerPass([&] { return CREATE_PASS; });
FUNCTION_PASS [1/2]
#define FUNCTION_PASS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
FUNCTION_PASS [2/2]
#define FUNCTION_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
FUNCTION_PASS_WITH_PARAMS [1/2]
#define FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
FUNCTION_PASS_WITH_PARAMS [2/2]
#define FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
  ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
GET_PASS_REGISTRY
#define GET_PASS_REGISTRY "DirectXPassRegistry.def"
LOOP_ANALYSIS [1/2]
#define LOOP_ANALYSIS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
LOOP_ANALYSIS [2/2]
#define LOOP_ANALYSIS (NAME, CREATE_PASS)
Value:
  AM.registerPass([&] { return CREATE_PASS; });
LOOP_PASS [1/2]
#define LOOP_PASS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
LOOP_PASS [2/2]
#define LOOP_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
MACHINE_FUNCTION_ANALYSIS [1/2]
#define MACHINE_FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MACHINE_FUNCTION_ANALYSIS [2/2]
#define MACHINE_FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
  AM.registerPass([&] { return CREATE_PASS; });
MACHINE_FUNCTION_PASS [1/2]
#define MACHINE_FUNCTION_PASS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MACHINE_FUNCTION_PASS [2/2]
#define MACHINE_FUNCTION_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
MACHINE_FUNCTION_PASS_WITH_PARAMS [1/2]
#define MACHINE_FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
MACHINE_FUNCTION_PASS_WITH_PARAMS [2/2]
#define MACHINE_FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
  ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
MODULE_ANALYSIS [1/2]
#define MODULE_ANALYSIS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MODULE_ANALYSIS [2/2]
#define MODULE_ANALYSIS (NAME, CREATE_PASS)
Value:
  AM.registerPass([&] { return CREATE_PASS; });
MODULE_PASS [1/2]
#define MODULE_PASS (NAME, CREATE_PASS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MODULE_PASS [2/2]
#define MODULE_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
MODULE_PASS_WITH_PARAMS [1/2]
#define MODULE_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
  ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
MODULE_PASS_WITH_PARAMS [2/2]
#define MODULE_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
  ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
Function Documentation
LLVMInitializeDirectXTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeDirectXTarget ()
Definition at line 53 of file DirectXTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheDirectXTarget(), llvm::initializeDXContainerGlobalsPass(), llvm::initializeDXILCBufferAccessLegacyPass(), llvm::initializeDXILDataScalarizationLegacyPass(), llvm::initializeDXILFinalizeLinkageLegacyPass(), llvm::initializeDXILFlattenArraysLegacyPass(), llvm::initializeDXILForwardHandleAccessesLegacyPass(), llvm::initializeDXILIntrinsicExpansionLegacyPass(), llvm::initializeDXILLegalizeLegacyPass(), llvm::initializeDXILOpLoweringLegacyPass(), llvm::initializeDXILPostOptimizationValidationLegacyPass(), llvm::initializeDXILPrepareModulePass(), llvm::initializeDXILPrettyPrinterLegacyPass(), llvm::initializeDXILResourceAccessLegacyPass(), llvm::initializeDXILResourceImplicitBindingLegacyPass(), llvm::initializeDXILTranslateMetadataLegacyPass(), llvm::initializeEmbedDXILPassPass(), llvm::initializeRootSignatureAnalysisWrapperPass(), llvm::initializeScalarizerLegacyPassPass(), llvm::initializeShaderFlagsAnalysisWrapperPass(), llvm::initializeWriteDXILPassPass(), LLVM_EXTERNAL_VISIBILITY, and X.