LLVM: lib/IR/Dominators.cpp File Reference
Dominators.cpp File Reference
#include "llvm/IR/Dominators.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/PassRegistry.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/GenericDomTreeConstruction.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree &DT)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::CalculateWithUpdates< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree &DT, BBUpdates U)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree &DT)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree &DT, DomTreeBuilder::BBDomTreeGraphDiff &, DomTreeBuilder::BBDomTreeGraphDiff *)
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree &DT, DomTreeBuilder::BBPostDomTreeGraphDiff &, DomTreeBuilder::BBPostDomTreeGraphDiff *)
template LLVM_EXPORT_TEMPLATE bool llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBDomTree > (const DomTreeBuilder::BBDomTree &DT, DomTreeBuilder::BBDomTree::VerificationLevel VL)
template LLVM_EXPORT_TEMPLATE bool llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBPostDomTree > (const DomTreeBuilder::BBPostDomTree &DT, DomTreeBuilder::BBPostDomTree::VerificationLevel VL)
INITIALIZE_PASS (DominatorTreeWrapperPass, "domtree", "Dominator Tree Construction", true, true) bool DominatorTreeWrapperPass
Variables
static cl::opt< bool, true > VerifyDomInfoX ("verify-dom-info", cl::location(VerifyDomInfo), cl::Hidden, cl::desc("Verify dominator info (time consuming)"))
static constexpr bool ExpensiveChecksEnabled = false
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (DominatorTreeWrapperPass , "domtree" , "Dominator Tree Construction" , true , true)
Definition at line 426 of file Dominators.cpp.
References F, and runOnFunction().
llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree & DT, DomTreeBuilder::BBDomTreeGraphDiff & , DomTreeBuilder::BBDomTreeGraphDiff *)
References llvm::DomTreeBuilder::ApplyUpdates(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree & DT, DomTreeBuilder::BBPostDomTreeGraphDiff & , DomTreeBuilder::BBPostDomTreeGraphDiff *)
References llvm::DomTreeBuilder::ApplyUpdates(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree & DT)
References llvm::DomTreeBuilder::Calculate(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree & DT)
References llvm::DomTreeBuilder::Calculate(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::CalculateWithUpdates< DomTreeBuilder::BBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::CalculateWithUpdates< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree & DT, BBUpdates U)
References llvm::DomTreeBuilder::CalculateWithUpdates(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree & DT, BasicBlock * From, BasicBlock * To)
References llvm::DomTreeBuilder::DeleteEdge(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree & DT, BasicBlock * From, BasicBlock * To)
References llvm::DomTreeBuilder::DeleteEdge(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBDomTree > (DomTreeBuilder::BBDomTree & DT, BasicBlock * From, BasicBlock * To)
References llvm::DomTreeBuilder::InsertEdge(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBPostDomTree > (DomTreeBuilder::BBPostDomTree & DT, BasicBlock * From, BasicBlock * To)
References llvm::DomTreeBuilder::InsertEdge(), and LLVM_EXPORT_TEMPLATE.
llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBDomTree >()
template LLVM_EXPORT_TEMPLATE bool llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBDomTree > (const DomTreeBuilder::BBDomTree & DT, DomTreeBuilder::BBDomTree::VerificationLevel VL)
References LLVM_EXPORT_TEMPLATE, and llvm::DomTreeBuilder::Verify().
llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBPostDomTree >()
template LLVM_EXPORT_TEMPLATE bool llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBPostDomTree > (const DomTreeBuilder::BBPostDomTree & DT, DomTreeBuilder::BBPostDomTree::VerificationLevel VL)
References LLVM_EXPORT_TEMPLATE, and llvm::DomTreeBuilder::Verify().
Variable Documentation
ExpensiveChecksEnabled
bool ExpensiveChecksEnabled = false static constexpr
Definition at line 49 of file Dominators.cpp.
VerifyDomInfoX
cl::opt< bool, true > VerifyDomInfoX("verify-dom-info", cl::location(VerifyDomInfo), cl::Hidden, cl::desc("Verify dominator info (time consuming)")) ("verify-dom-info" , cl::location(VerifyDomInfo) , cl::Hidden , cl::desc("Verify dominator info (time consuming)")) static