LLVM: lib/DebugInfo/DWARF/DWARFCFIPrinter.cpp File Reference
DWARFCFIPrinter.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFCFIPrinter.h"
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDataExtractor.h"
#include "llvm/DebugInfo/DWARF/DWARFExpressionPrinter.h"
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFCFIProgram.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <optional>
Functions
static void printRegister (raw_ostream &OS, const DIDumpOptions &DumpOpts, unsigned RegNum)
static void printOperand (raw_ostream &OS, const DIDumpOptions &DumpOpts, const CFIProgram &P, const CFIProgram::Instruction &Instr, unsigned OperandIdx, uint64_t Operand, std::optional< uint64_t > &Address)
Print Opcode's operand number OperandIdx which has value Operand.
Function Documentation
printOperand()
void printOperand (raw_ostream & OS, const DIDumpOptions & DumpOpts, const CFIProgram & P, const CFIProgram::Instruction & Instr, unsigned OperandIdx, uint64_t Operand, std::optional< uint64_t > & Address) static
Print Opcode's operand number OperandIdx which has value Operand.
Definition at line 41 of file DWARFCFIPrinter.cpp.
References assert(), llvm::format(), llvm::dwarf::CFIProgram::MaxOperands, llvm::dwarf::CFIProgram::OT_Address, llvm::dwarf::CFIProgram::OT_AddressSpace, llvm::dwarf::CFIProgram::OT_Expression, llvm::dwarf::CFIProgram::OT_FactoredCodeOffset, llvm::dwarf::CFIProgram::OT_None, llvm::dwarf::CFIProgram::OT_Offset, llvm::dwarf::CFIProgram::OT_Register, llvm::dwarf::CFIProgram::OT_SignedFactDataOffset, llvm::dwarf::CFIProgram::OT_Unset, llvm::dwarf::CFIProgram::OT_UnsignedFactDataOffset, P, llvm::printDwarfExpression(), and printRegister().
Referenced by llvm::dwarf::printCFIProgram().
printRegister()
void printRegister (raw_ostream & OS, const DIDumpOptions & DumpOpts, unsigned RegNum) static
Definition at line 28 of file DWARFCFIPrinter.cpp.
References llvm::DIDumpOptions::GetNameForDWARFReg, llvm::DIDumpOptions::IsEH, and RegName.
Referenced by printOperand().