LLVM: lib/DebugInfo/DWARF/DWARFUnwindTablePrinter.cpp File Reference
DWARFUnwindTablePrinter.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFUnwindTablePrinter.h"
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFExpressionPrinter.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <optional>
Functions
static void printRegister (raw_ostream &OS, DIDumpOptions DumpOpts, unsigned RegNum)
static void printUnwindLocation (const UnwindLocation &UL, raw_ostream &OS, DIDumpOptions DumpOpts)
Print an unwind location expression as text and use the register information if some is provided.
static void printRegisterLocations (const RegisterLocations &RL, raw_ostream &OS, DIDumpOptions DumpOpts)
Print all registers + locations that are currently defined in a register locations.
static void printUnwindRow (const UnwindRow &Row, raw_ostream &OS, DIDumpOptions DumpOpts, unsigned IndentLevel)
Print an UnwindRow to the stream.
Function Documentation
printRegister()
void printRegister (raw_ostream & OS, DIDumpOptions DumpOpts, unsigned RegNum) static
Definition at line 23 of file DWARFUnwindTablePrinter.cpp.
References llvm::DIDumpOptions::GetNameForDWARFReg, llvm::DIDumpOptions::IsEH, and RegName.
Referenced by printRegisterLocations(), and printUnwindLocation().
printRegisterLocations()
void printRegisterLocations (const RegisterLocations & RL, raw_ostream & OS, DIDumpOptions DumpOpts) static
Print all registers + locations that are currently defined in a register locations.
Parameters
RL the register locations to print.
OS the stream to use for output.
MRI register information that helps emit register names insteead of raw register numbers.
IsEH true if the DWARF Call Frame Information is from .eh_frame instead of from .debug_frame. This is needed for register number conversion because some register numbers differ between the two sections for certain architectures like x86.
Definition at line 117 of file DWARFUnwindTablePrinter.cpp.
References llvm::First, llvm::dwarf::RegisterLocations::getRegisterLocation(), llvm::dwarf::RegisterLocations::getRegisters(), printRegister(), printUnwindLocation(), and Reg.
Referenced by llvm::dwarf::operator<<(), and printUnwindRow().
printUnwindLocation()
void printUnwindLocation (const UnwindLocation & UL, raw_ostream & OS, DIDumpOptions DumpOpts) static
Print an unwind location expression as text and use the register information if some is provided.
Parameters
R the unwind location to print.
OS the stream to use for output.
MRI register information that helps emit register names insteead of raw register numbers.
IsEH true if the DWARF Call Frame Information is from .eh_frame instead of from .debug_frame. This is needed for register number conversion because some register numbers differ between the two sections for certain architectures like x86.
Definition at line 49 of file DWARFUnwindTablePrinter.cpp.
References llvm::dwarf::UnwindLocation::CFAPlusOffset, llvm::dwarf::UnwindLocation::Constant, llvm::dwarf::UnwindLocation::DWARFExpr, llvm::dwarf::UnwindLocation::getAddressSpace(), llvm::dwarf::UnwindLocation::getDereference(), llvm::dwarf::UnwindLocation::getDWARFExpressionBytes(), llvm::dwarf::UnwindLocation::getLocation(), llvm::dwarf::UnwindLocation::getOffset(), llvm::dwarf::UnwindLocation::getRegister(), llvm::dwarf::UnwindLocation::hasAddressSpace(), llvm::printDwarfExpression(), printRegister(), llvm::dwarf::UnwindLocation::RegPlusOffset, llvm::dwarf::UnwindLocation::Same, llvm::dwarf::UnwindLocation::Undefined, and llvm::dwarf::UnwindLocation::Unspecified.
Referenced by llvm::dwarf::operator<<(), printRegisterLocations(), and printUnwindRow().
printUnwindRow()
void printUnwindRow (const UnwindRow & Row, raw_ostream & OS, DIDumpOptions DumpOpts, unsigned IndentLevel) static
Print an UnwindRow to the stream.
Parameters
Row the UnwindRow to print.
OS the stream to use for output.
MRI register information that helps emit register names insteead of raw register numbers.
IsEH true if the DWARF Call Frame Information is from .eh_frame instead of from .debug_frame. This is needed for register number conversion because some register numbers differ between the two sections for certain architectures like x86.
IndentLevel specify the indent level as an integer. The UnwindRow will be output to the stream preceded by 2 * IndentLevel number of spaces.
Definition at line 155 of file DWARFUnwindTablePrinter.cpp.
References llvm::format(), llvm::raw_ostream::indent(), printRegisterLocations(), and printUnwindLocation().
Referenced by llvm::dwarf::operator<<(), and llvm::dwarf::printUnwindTable().