LLVM: lib/DebugInfo/DWARF/DWARFDebugFrame.cpp File Reference
DWARFDebugFrame.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugFrame.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFCFIPrinter.h"
#include "llvm/DebugInfo/DWARF/DWARFDataExtractor.h"
#include "llvm/DebugInfo/DWARF/DWARFExpressionPrinter.h"
#include "llvm/DebugInfo/DWARF/DWARFUnwindTablePrinter.h"
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFCFIProgram.h"
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFExpression.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <optional>
Functions
constexpr uint64_t getCIEId (bool IsDWARF64, bool IsEH)
static void LLVM_ATTRIBUTE_UNUSED dumpDataAux (DataExtractor Data, uint64_t Offset, int Length)
Function Documentation
dumpDataAux()
void LLVM_ATTRIBUTE_UNUSED dumpDataAux (DataExtractor Data, uint64_t Offset, int Length) static
Definition at line 184 of file DWARFDebugFrame.cpp.
References llvm::Data, llvm::errs(), llvm::Length, LLVM_ATTRIBUTE_UNUSED, llvm::Offset, and llvm::raw_ostream::write_hex().
getCIEId()
uint64_t getCIEId (bool IsDWARF64, bool IsEH) constexpr
Definition at line 93 of file DWARFDebugFrame.cpp.
References llvm::dwarf::DW64_CIE_ID, and llvm::dwarf::DW_CIE_ID.
Referenced by llvm::dwarf::CIE::dump(), and llvm::DWARFDebugFrame::parse().