LLVM: lib/Target/DirectX/DXILForwardHandleAccesses.cpp File Reference
DXILForwardHandleAccesses.cpp File Reference
#include "DXILForwardHandleAccesses.h"
#include "DXILShaderFlags.h"
#include "DirectX.h"
#include "llvm/Analysis/DXILResource.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "dxil-forward-handle-accesses"
Functions
static void diagnoseAmbiguousHandle (IntrinsicInst *NewII, IntrinsicInst *PrevII)
static void diagnoseHandleNotFound (LoadInst *LI)
static void diagnoseUndominatedLoad (LoadInst *LI, IntrinsicInst *Handle)
static void processHandle (IntrinsicInst *II, DenseMap< GlobalVariable *, IntrinsicInst * > &HandleMap)
static bool forwardHandleAccesses (Function &F, DominatorTree &DT)
INITIALIZE_PASS_BEGIN (DXILForwardHandleAccessesLegacy, DEBUG_TYPE, "DXIL Forward Handle Accesses", false, false) INITIALIZE_PASS_END(DXILForwardHandleAccessesLegacy
Variables
DEBUG_TYPE
DXIL Forward Handle Accesses
DXIL Forward Handle false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-forward-handle-accesses"
Definition at line 24 of file DXILForwardHandleAccesses.cpp.
Function Documentation
diagnoseAmbiguousHandle()
void diagnoseAmbiguousHandle (IntrinsicInst * NewII, IntrinsicInst * PrevII) static
Definition at line 28 of file DXILForwardHandleAccesses.cpp.
References F, llvm::Instruction::getFunction(), and llvm::Value::getName().
Referenced by processHandle().
diagnoseHandleNotFound()
void diagnoseHandleNotFound (LoadInst * LI) static
Definition at line 37 of file DXILForwardHandleAccesses.cpp.
References F, llvm::Instruction::getFunction(), llvm::Value::getName(), and llvm::LoadInst::getPointerOperand().
Referenced by forwardHandleAccesses().
diagnoseUndominatedLoad()
void diagnoseUndominatedLoad (LoadInst * LI, IntrinsicInst * Handle) static
Definition at line 45 of file DXILForwardHandleAccesses.cpp.
References F, llvm::Instruction::getFunction(), and llvm::Value::getName().
Referenced by forwardHandleAccesses().
forwardHandleAccesses()
bool forwardHandleAccesses (Function & F, DominatorTree & DT) static
Definition at line 68 of file DXILForwardHandleAccesses.cpp.
References Changed, llvm::dbgs(), diagnoseHandleNotFound(), diagnoseUndominatedLoad(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::FindAvailableLoadedValue(), II, llvm::isa(), LLVM_DEBUG, processHandle(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::DXILForwardHandleAccesses::run().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILForwardHandleAccessesLegacy , DEBUG_TYPE , "DXIL Forward Handle Accesses" , false , false)
References DEBUG_TYPE, and INITIALIZE_PASS_DEPENDENCY.
processHandle()
void processHandle (IntrinsicInst * II, DenseMap< GlobalVariable *, IntrinsicInst * > & HandleMap) static
Definition at line 55 of file DXILForwardHandleAccesses.cpp.
References llvm::dbgs(), diagnoseAmbiguousHandle(), llvm::dyn_cast(), II, LLVM_DEBUG, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by forwardHandleAccesses().
Variable Documentation
Accesses
DXIL Forward Handle Accesses
Definition at line 162 of file DXILForwardHandleAccesses.cpp.
Referenced by foreachMemoryAccess(), llvm::MachineInstr::getFoldedRestoreSize(), llvm::MachineInstr::getFoldedSpillSize(), getSpillSlotSize(), llvm::HexagonInstrInfo::hasLoadFromStackSlot(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), llvm::HexagonInstrInfo::hasStoreToStackSlot(), llvm::TargetInstrInfo::hasStoreToStackSlot(), llvm::MemorySSA::insertIntoListsBefore(), llvm::MemorySSA::insertIntoListsForBlock(), llvm::ARMBaseInstrInfo::isLoadFromStackSlotPostFE(), llvm::LanaiInstrInfo::isLoadFromStackSlotPostFE(), llvm::SystemZInstrInfo::isLoadFromStackSlotPostFE(), llvm::X86InstrInfo::isLoadFromStackSlotPostFE(), llvm::ARMBaseInstrInfo::isStoreToStackSlotPostFE(), llvm::SystemZInstrInfo::isStoreToStackSlotPostFE(), llvm::X86InstrInfo::isStoreToStackSlotPostFE(), noConflictingReadWrites(), pointerInvalidatedByBlock(), llvm::MemorySSA::removeFromLists(), llvm::SinkAndHoistLICMFlags::SinkAndHoistLICMFlags(), and llvm::MemorySSA::verifyDominationNumbers().
DEBUG_TYPE
DEBUG_TYPE
Definition at line 161 of file DXILForwardHandleAccesses.cpp.
false
DXIL Forward Handle false
Definition at line 162 of file DXILForwardHandleAccesses.cpp.