LLVM: lib/Transforms/Utils/DXILUpgrade.cpp File Reference
DXILUpgrade.cpp File Reference
#include "llvm/Transforms/Utils/DXILUpgrade.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "dxil-upgrade"
Functions
static bool handleValVerMetadata (Module &M)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-upgrade"
Definition at line 17 of file DXILUpgrade.cpp.
Function Documentation
handleValVerMetadata()
bool handleValVerMetadata (Module & M) static
Definition at line 19 of file DXILUpgrade.cpp.
References llvm::dbgs(), llvm::NamedMDNode::dropAllReferences(), llvm::NamedMDNode::eraseFromParent(), llvm::mdconst::extract(), llvm::NamedMDNode::getOperand(), LLVM_DEBUG, N, X, and Y.
Referenced by llvm::DXILUpgradePass::run().