LLVM: lib/Analysis/DXILResource.cpp File Reference
DXILResource.cpp File Reference
#include "llvm/Analysis/DXILResource.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/FormatVariadic.h"
#include <cstdint>
#include <optional>
Macros
#define DEBUG_TYPE "dxil-resource"
Functions
static StringRef getResourceClassName (ResourceClass RC)
static StringRef getResourceKindName (ResourceKind RK)
static StringRef getElementTypeName (ElementType ET)
static StringRef getElementTypeNameForTemplate (ElementType ET)
static StringRef getSamplerTypeName (SamplerType ST)
static StringRef getSamplerFeedbackTypeName (SamplerFeedbackType SFT)
static dxil::ElementType toDXILElementType (Type *Ty, bool IsSigned)
static void formatTypeName (SmallString< 64 > &Dest, StringRef Name, bool IsWriteable, bool IsROV, Type *ContainedType=nullptr, bool IsSigned=true)
static StructType * getOrCreateElementStruct (Type *ElemType, StringRef Name)
static bool isROV (dxil::ResourceKind Kind, TargetExtType *Ty)
static std::pair< Type *, bool > getTypedElementType (dxil::ResourceKind Kind, TargetExtType *Ty)
static bool isUpdateCounterIntrinsic (Function &F)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-resource"
Definition at line 27 of file DXILResource.cpp.
Function Documentation
formatTypeName()
void formatTypeName (SmallString< 64 > & Dest, StringRef Name, bool IsWriteable, bool IsROV, Type * ContainedType = nullptr, bool IsSigned = true) static
Definition at line 259 of file DXILResource.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), getElementTypeNameForTemplate(), llvm::dxil::Invalid, llvm::isa(), and toDXILElementType().
Referenced by llvm::dxil::ResourceTypeInfo::createElementStruct().
getElementTypeName()
StringRef getElementTypeName (ElementType ET) static
Definition at line 91 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getElementTypeNameForTemplate()
StringRef getElementTypeNameForTemplate (ElementType ET) static
Definition at line 135 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by formatTypeName().
getOrCreateElementStruct()
StructType * getOrCreateElementStruct (Type * ElemType, StringRef Name) static
Definition at line 290 of file DXILResource.cpp.
References llvm::StructType::create(), llvm::Type::getContext(), and llvm::StructType::getTypeByName().
Referenced by llvm::dxil::ResourceTypeInfo::createElementStruct().
getResourceClassName()
StringRef getResourceClassName (ResourceClass RC) static
Definition at line 32 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getResourceKindName()
StringRef getResourceKindName (ResourceKind RK) static
Definition at line 46 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::createElementStruct(), and llvm::dxil::ResourceTypeInfo::print().
getSamplerFeedbackTypeName()
StringRef getSamplerFeedbackTypeName (SamplerFeedbackType SFT) static
Definition at line 185 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getSamplerTypeName()
StringRef getSamplerTypeName (SamplerType ST) static
Definition at line 173 of file DXILResource.cpp.
References llvm_unreachable.
Referenced by llvm::dxil::ResourceTypeInfo::print().
getTypedElementType()
std::pair< Type *, bool > getTypedElementType (dxil::ResourceKind Kind, TargetExtType * Ty) static
Definition at line 496 of file DXILResource.cpp.
References llvm::cast(), llvm::dxil::CBuffer, llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by llvm::dxil::ResourceTypeInfo::getTyped().
isROV()
bool isROV (dxil::ResourceKind Kind, TargetExtType * Ty) static
Definition at line 429 of file DXILResource.cpp.
References llvm::cast(), llvm::dxil::CBuffer, llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by llvm::dxil::ResourceTypeInfo::getUAV().
isUpdateCounterIntrinsic()
bool isUpdateCounterIntrinsic (Function & F) static
Definition at line 786 of file DXILResource.cpp.
References F.
toDXILElementType()
dxil::ElementType toDXILElementType (Type * Ty, bool IsSigned) static
Definition at line 195 of file DXILResource.cpp.
Referenced by formatTypeName(), and llvm::dxil::ResourceTypeInfo::getTyped().