LLVM: lib/Analysis/DXILMetadataAnalysis.cpp File Reference
DXILMetadataAnalysis.cpp File Reference
#include "llvm/Analysis/DXILMetadataAnalysis.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "dxil-metadata-analysis"
Functions
static ModuleMetadataInfo collectMetadataInfo (Module &M)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-metadata-analysis"
Definition at line 20 of file DXILMetadataAnalysis.cpp.
Function Documentation
collectMetadataInfo()
ModuleMetadataInfo collectMetadataInfo (Module & M) static
Definition at line 25 of file DXILMetadataAnalysis.cpp.
References assert(), llvm::cast(), llvm::dxil::ModuleMetadataInfo::DXILVersion, llvm::StringRef::empty(), llvm::dxil::ModuleMetadataInfo::EntryPropertyVec, llvm::mdconst::extract(), F, llvm::NamedMDNode::getOperand(), llvm::Attribute::getValueAsString(), llvm::Attribute::isValid(), llvm::dxil::EntryProperties::NumThreadsX, llvm::dxil::EntryProperties::NumThreadsY, llvm::dxil::EntryProperties::NumThreadsZ, llvm::dxil::ModuleMetadataInfo::ShaderModelVersion, llvm::dxil::ModuleMetadataInfo::ShaderProfile, llvm::dxil::EntryProperties::ShaderStage, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::split(), Success, T, llvm::to_integer(), and llvm::dxil::ModuleMetadataInfo::ValidatorVersion.
Referenced by llvm::DXILMetadataAnalysis::run(), and llvm::DXILMetadataAnalysisWrapperPass::runOnModule().