LLVM: lib/Target/DirectX/DXILRootSignature.cpp File Reference
DXILRootSignature.cpp File Reference
#include "DXILRootSignature.h"
#include "DirectX.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/DXILMetadataAnalysis.h"
#include "llvm/BinaryFormat/DXContainer.h"
#include "llvm/Frontend/HLSL/RootSignatureValidations.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdint>
#include <optional>
#include <utility>
Functions
static bool reportError (LLVMContext *Ctx, Twine Message, DiagnosticSeverity Severity=DS_Error)
static bool reportValueError (LLVMContext *Ctx, Twine ParamName, uint32_t Value)
static std::optional< uint32_t > extractMdIntValue (MDNode *Node, unsigned int OpId)
static std::optional< float > extractMdFloatValue (MDNode *Node, unsigned int OpId)
static std::optional< StringRef > extractMdStringValue (MDNode *Node, unsigned int OpId)
static bool parseRootFlags (LLVMContext *Ctx, mcdxbc::RootSignatureDesc &RSD, MDNode *RootFlagNode)
static bool parseRootConstants (LLVMContext *Ctx, mcdxbc::RootSignatureDesc &RSD, MDNode *RootConstantNode)
static bool parseRootDescriptors (LLVMContext *Ctx, mcdxbc::RootSignatureDesc &RSD, MDNode *RootDescriptorNode, RootSignatureElementKind ElementKind)
static bool parseDescriptorRange (LLVMContext *Ctx, mcdxbc::DescriptorTable &Table, MDNode *RangeDescriptorNode)
static bool parseDescriptorTable (LLVMContext *Ctx, mcdxbc::RootSignatureDesc &RSD, MDNode *DescriptorTableNode)
static bool parseStaticSampler (LLVMContext *Ctx, mcdxbc::RootSignatureDesc &RSD, MDNode *StaticSamplerNode)
static bool parseRootSignatureElement (LLVMContext *Ctx, mcdxbc::RootSignatureDesc &RSD, MDNode *Element)
static bool parse (LLVMContext *Ctx, mcdxbc::RootSignatureDesc &RSD, MDNode *Node)
static bool validate (LLVMContext *Ctx, const mcdxbc::RootSignatureDesc &RSD)
static SmallDenseMap< const Function *, mcdxbc::RootSignatureDesc > analyzeModule (Module &M)
INITIALIZE_PASS_BEGIN (RootSignatureAnalysisWrapper, "dxil-root-signature-analysis", "DXIL Root Signature Analysis", true, true) INITIALIZE_PASS_END(RootSignatureAnalysisWrapper
Variables
dxil root signature analysis
dxil root signature DXIL Root Signature Analysis
dxil root signature DXIL Root Signature true
Function Documentation
analyzeModule()
SmallDenseMap< const Function *, mcdxbc::RootSignatureDesc > analyzeModule (Module & M) static
Root Signature are specified as following in the metadata:
!dx.rootsignatures = !{!2} ; list of function/root signature pairs !2 = !{ ptr @main, !3 } ; function, root signature !3 = !{ !4, !5, !6, !7 } ; list of root signature elements
So for each MDNode inside dx.rootsignatures NamedMDNode (the Root parameter of this function), the parsing process needs to loop through each of its operands and process the function, signature pair.
Definition at line 509 of file DXILRootSignature.cpp.
References llvm::dyn_cast(), extractMdIntValue(), F, llvm::MDOperand::get(), llvm::ValueAsMetadata::getValue(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::NamedMDNode::operands(), parse(), reportError(), llvm::mcdxbc::RootSignatureDesc::RootParameterOffset, llvm::mcdxbc::RootSignatureDesc::StaticSamplersOffset, validate(), and llvm::mcdxbc::RootSignatureDesc::Version.
Referenced by llvm::dxil::RootSignatureAnalysis::run(), and llvm::dxil::RootSignatureAnalysisWrapper::runOnModule().
extractMdFloatValue()
std::optional< float > extractMdFloatValue (MDNode * Node, unsigned int OpId) static
Definition at line 59 of file DXILRootSignature.cpp.
References llvm::mdconst::dyn_extract().
Referenced by parseStaticSampler().
extractMdIntValue()
std::optional< uint32_t > extractMdIntValue (MDNode * Node, unsigned int OpId) static
Definition at line 51 of file DXILRootSignature.cpp.
References llvm::mdconst::dyn_extract().
Referenced by analyzeModule(), parseDescriptorRange(), parseDescriptorTable(), parseRootConstants(), parseRootDescriptors(), parseRootFlags(), and parseStaticSampler().
extractMdStringValue()
std::optional< StringRef > extractMdStringValue (MDNode * Node, unsigned int OpId) static
Definition at line 66 of file DXILRootSignature.cpp.
References llvm::dyn_cast(), and llvm::MDString::getString().
Referenced by parseDescriptorRange(), and parseRootSignatureElement().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (RootSignatureAnalysisWrapper , "dxil-root-signature-analysis" , "DXIL Root Signature Analysis" , true , true)
References INITIALIZE_PASS_END.
parse()
bool parse (LLVMContext * Ctx, mcdxbc::RootSignatureDesc & RSD, MDNode * Node) static
Definition at line 386 of file DXILRootSignature.cpp.
References llvm::dyn_cast(), parseRootSignatureElement(), and reportError().
Referenced by analyzeModule().
parseDescriptorRange()
bool parseDescriptorRange (LLVMContext * Ctx, mcdxbc::DescriptorTable & Table, MDNode * RangeDescriptorNode) static
Definition at line 185 of file DXILRootSignature.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), extractMdIntValue(), extractMdStringValue(), llvm::MDNode::getNumOperands(), Range, llvm::mcdxbc::DescriptorTable::Ranges, reportError(), and llvm::to_underlying().
Referenced by parseDescriptorTable().
parseDescriptorTable()
bool parseDescriptorTable (LLVMContext * Ctx, mcdxbc::RootSignatureDesc & RSD, MDNode * DescriptorTableNode) static
Definition at line 242 of file DXILRootSignature.cpp.
References llvm::mcdxbc::RootParametersContainer::addParameter(), llvm::dyn_cast(), extractMdIntValue(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), I, llvm::mcdxbc::RootSignatureDesc::ParametersContainer, parseDescriptorRange(), reportError(), llvm::dxbc::RTS0::v1::RootParameterHeader::ShaderVisibility, and llvm::to_underlying().
Referenced by parseRootSignatureElement().
parseRootConstants()
bool parseRootConstants (LLVMContext * Ctx, mcdxbc::RootSignatureDesc & RSD, MDNode * RootConstantNode) static
Definition at line 88 of file DXILRootSignature.cpp.
References llvm::mcdxbc::RootParametersContainer::addParameter(), extractMdIntValue(), llvm::MDNode::getNumOperands(), llvm::mcdxbc::RootSignatureDesc::ParametersContainer, llvm::dxbc::RTS0::v1::RootParameterHeader::ParameterType, reportError(), llvm::dxbc::RTS0::v1::RootConstants::ShaderRegister, and llvm::to_underlying().
Referenced by parseRootSignatureElement().
parseRootDescriptors()
bool parseRootDescriptors (LLVMContext * Ctx, mcdxbc::RootSignatureDesc & RSD, MDNode * RootDescriptorNode, RootSignatureElementKind ElementKind) static
Definition at line 126 of file DXILRootSignature.cpp.
References llvm::mcdxbc::RootParametersContainer::addParameter(), assert(), llvm::dxil::CBV, extractMdIntValue(), llvm::dxbc::RTS0::v2::RootDescriptor::Flags, llvm::MDNode::getNumOperands(), llvm_unreachable, llvm::mcdxbc::RootSignatureDesc::ParametersContainer, llvm::dxbc::RTS0::v1::RootDescriptor::RegisterSpace, reportError(), llvm::dxbc::RTS0::v1::RootDescriptor::ShaderRegister, llvm::dxbc::RTS0::v1::RootParameterHeader::ShaderVisibility, llvm::dxil::SRV, llvm::to_underlying(), llvm::dxil::UAV, and llvm::mcdxbc::RootSignatureDesc::Version.
Referenced by parseRootSignatureElement().
parseRootFlags()
bool parseRootFlags (LLVMContext * Ctx, mcdxbc::RootSignatureDesc & RSD, MDNode * RootFlagNode) static
Definition at line 74 of file DXILRootSignature.cpp.
References extractMdIntValue(), llvm::mcdxbc::RootSignatureDesc::Flags, llvm::MDNode::getNumOperands(), and reportError().
Referenced by parseRootSignatureElement().
parseRootSignatureElement()
bool parseRootSignatureElement (LLVMContext * Ctx, mcdxbc::RootSignatureDesc & RSD, MDNode * Element) static
Definition at line 347 of file DXILRootSignature.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::dxil::CBV, llvm::StringSwitch< T, R >::Default(), llvm::dxil::DescriptorTable, llvm::dxil::Error, extractMdStringValue(), llvm_unreachable, parseDescriptorTable(), parseRootConstants(), parseRootDescriptors(), parseRootFlags(), parseStaticSampler(), reportError(), llvm::dxil::RootConstants, llvm::dxil::RootFlags, llvm::dxil::SRV, llvm::dxil::StaticSamplers, and llvm::dxil::UAV.
Referenced by parse().
parseStaticSampler()
bool parseStaticSampler (LLVMContext * Ctx, mcdxbc::RootSignatureDesc & RSD, MDNode * StaticSamplerNode) static
Definition at line 272 of file DXILRootSignature.cpp.
References extractMdFloatValue(), extractMdIntValue(), llvm::MDNode::getNumOperands(), reportError(), llvm::dxil::Sampler, and llvm::mcdxbc::RootSignatureDesc::StaticSamplers.
Referenced by parseRootSignatureElement().
reportError()
bool reportError (LLVMContext * Ctx, Twine Message, DiagnosticSeverity Severity = DS_Error) static
Definition at line 38 of file DXILRootSignature.cpp.
References llvm::DS_Error.
Referenced by analyzeModule(), parse(), parseDescriptorRange(), parseDescriptorTable(), parseRootConstants(), parseRootDescriptors(), parseRootFlags(), parseRootSignatureElement(), and parseStaticSampler().
reportValueError()
bool reportValueError (LLVMContext * Ctx, Twine ParamName, uint32_t Value) static
Definition at line 44 of file DXILRootSignature.cpp.
References llvm::DS_Error.
Referenced by validate().
validate()
bool validate (LLVMContext * Ctx, const mcdxbc::RootSignatureDesc & RSD) static
Definition at line 402 of file DXILRootSignature.cpp.
References assert(), llvm::dxbc::RTS0::v2::RootDescriptor::Flags, llvm::mcdxbc::RootSignatureDesc::Flags, llvm::mcdxbc::RootParametersContainer::getDescriptorTable(), llvm::mcdxbc::RootParametersContainer::getRootDescriptor(), Info, llvm::dxbc::isValidParameterType(), llvm::dxbc::isValidShaderVisibility(), llvm::mcdxbc::RootSignatureDesc::ParametersContainer, Range, llvm::dxbc::RTS0::v1::RootDescriptor::RegisterSpace, reportValueError(), llvm::dxil::Sampler, llvm::dxbc::RTS0::v1::RootDescriptor::ShaderRegister, llvm::mcdxbc::RootSignatureDesc::StaticSamplers, llvm::to_underlying(), llvm::hlsl::rootsig::verifyAddress(), llvm::hlsl::rootsig::verifyBorderColor(), llvm::hlsl::rootsig::verifyComparisonFunc(), llvm::hlsl::rootsig::verifyDescriptorRangeFlag(), llvm::hlsl::rootsig::verifyLOD(), llvm::hlsl::rootsig::verifyMaxAnisotropy(), llvm::hlsl::rootsig::verifyMipLODBias(), llvm::hlsl::rootsig::verifyNumDescriptors(), llvm::hlsl::rootsig::verifyRangeType(), llvm::hlsl::rootsig::verifyRegisterSpace(), llvm::hlsl::rootsig::verifyRegisterValue(), llvm::hlsl::rootsig::verifyRootDescriptorFlag(), llvm::hlsl::rootsig::verifyRootFlag(), llvm::hlsl::rootsig::verifySamplerFilter(), llvm::hlsl::rootsig::verifyVersion(), and llvm::mcdxbc::RootSignatureDesc::Version.
Referenced by analyzeModule(), and LLVM_YAML_IS_SEQUENCE_VECTOR().
Variable Documentation
Analysis
dxil root signature DXIL Root Signature Analysis
Definition at line 697 of file DXILRootSignature.cpp.
analysis
dxil root signature analysis
Definition at line 696 of file DXILRootSignature.cpp.
true
dxil root signature DXIL Root Signature true
Definition at line 697 of file DXILRootSignature.cpp.