LLVM: lib/Target/DirectX/DXILLegalizePass.cpp File Reference
DXILLegalizePass.cpp File Reference
#include "DXILLegalizePass.h"
#include "DirectX.h"
#include "llvm/ADT/APInt.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <functional>
Macros
#define DEBUG_TYPE "dxil-legalize"
Functions
static void legalizeFreeze (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * >)
static void fixI8UseChain (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * > &ReplacedValues)
static void upcastI8AllocasAndUses (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * > &ReplacedValues)
static void downcastI64toI32InsertExtractElements (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * > &)
static void emitMemcpyExpansion (IRBuilder<> &Builder, Value *Dst, Value *Src, ConstantInt *Length)
static void emitMemsetExpansion (IRBuilder<> &Builder, Value *Dst, Value *Val, ConstantInt *SizeCI, DenseMap< Value *, Value * > &ReplacedValues)
static void legalizeMemCpy (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * > &ReplacedValues)
static void removeMemSet (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * > &ReplacedValues)
static void updateFnegToFsub (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * > &)
static void legalizeGetHighLowi64Bytes (Instruction &I, SmallVectorImpl< Instruction * > &ToRemove, DenseMap< Value *, Value * > &ReplacedValues)
INITIALIZE_PASS_BEGIN (DXILLegalizeLegacy, DEBUG_TYPE, "DXIL Legalizer", false, false) INITIALIZE_PASS_END(DXILLegalizeLegacy
Variables
DEBUG_TYPE
DXIL Legalizer
DXIL false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-legalize"
Definition at line 23 of file DXILLegalizePass.cpp.
Function Documentation
downcastI64toI32InsertExtractElements()
void downcastI64toI32InsertExtractElements (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * > &) static
Definition at line 304 of file DXILLegalizePass.cpp.
References llvm::dyn_cast(), llvm::Type::getInt32Ty(), I, llvm::Value::replaceAllUsesWith(), and ToRemove.
emitMemcpyExpansion()
void emitMemcpyExpansion (IRBuilder<> & Builder, Value * Dst, Value * Src, ConstantInt * Length) static
Definition at line 342 of file DXILLegalizePass.cpp.
References assert(), DL, llvm::dyn_cast(), llvm::Type::getInt32Ty(), I, llvm::isa(), llvm::Length, and llvm::Offset.
Referenced by legalizeMemCpy().
emitMemsetExpansion()
void emitMemsetExpansion (IRBuilder<> & Builder, Value * Dst, Value * Val, ConstantInt * SizeCI, DenseMap< Value *, Value * > & ReplacedValues) static
Definition at line 403 of file DXILLegalizePass.cpp.
References assert(), DL, llvm::dyn_cast(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getAllocationSize(), llvm::Type::getInt32Ty(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), I, llvm::Offset, Ptr, and Size.
Referenced by removeMemSet().
fixI8UseChain()
void fixI8UseChain (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * > & ReplacedValues) static
Definition at line 38 of file DXILLegalizePass.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::dyn_cast(), GEP, llvm::ArrayType::get(), llvm::IntegerType::get(), llvm::Type::getArrayElementType(), I, llvm::isa(), llvm::Offset, OpIdx, llvm::Value::replaceAllUsesWith(), and ToRemove.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILLegalizeLegacy , DEBUG_TYPE , "DXIL Legalizer" , false , false)
References DEBUG_TYPE.
legalizeFreeze()
void legalizeFreeze (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * >) static
Definition at line 27 of file DXILLegalizePass.cpp.
References llvm::dyn_cast(), I, and ToRemove.
legalizeGetHighLowi64Bytes()
void legalizeGetHighLowi64Bytes (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * > & ReplacedValues) static
Definition at line 517 of file DXILLegalizePass.cpp.
References assert(), llvm::dyn_cast(), llvm::FixedVectorType::get(), llvm::Type::getInt32Ty(), I, and ToRemove.
legalizeMemCpy()
void legalizeMemCpy (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * > & ReplacedValues) static
Definition at line 456 of file DXILLegalizePass.cpp.
References assert(), llvm::dyn_cast(), emitMemcpyExpansion(), llvm::CallBase::getArgOperand(), llvm::CallBase::getIntrinsicID(), I, llvm::Length, and ToRemove.
removeMemSet()
void removeMemSet (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * > & ReplacedValues) static
Definition at line 481 of file DXILLegalizePass.cpp.
References assert(), llvm::dyn_cast(), emitMemsetExpansion(), llvm::CallBase::getArgOperand(), llvm::CallBase::getIntrinsicID(), I, Size, and ToRemove.
upcastI8AllocasAndUses()
void upcastI8AllocasAndUses (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * > & ReplacedValues) static
Definition at line 254 of file DXILLegalizePass.cpp.
References llvm::dyn_cast(), GEP, llvm::Type::getInt32Ty(), llvm::Type::getPrimitiveSizeInBits(), I, ToRemove, and llvm::Value::users().
updateFnegToFsub()
void updateFnegToFsub (Instruction & I, SmallVectorImpl< Instruction * > & ToRemove, DenseMap< Value *, Value * > &) static
Definition at line 502 of file DXILLegalizePass.cpp.
References I, and ToRemove.
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 647 of file DXILLegalizePass.cpp.
false
DXIL false
Definition at line 647 of file DXILLegalizePass.cpp.
Legalizer
DXIL Legalizer
Definition at line 647 of file DXILLegalizePass.cpp.
Referenced by llvm::SelectionDAG::Legalize(), and llvm::SelectionDAG::LegalizeOp().