LLVM: lib/Support/ErrorHandling.cpp File Reference
ErrorHandling.cpp File Reference
#include "llvm/Support/ErrorHandling.h"
#include "llvm-c/ErrorHandling.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/config.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Errno.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/WindowsError.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdlib>
#include <mutex>
#include <new>
#include <unistd.h>
Functions
static bool write_retry (int fd, const char *buf, size_t count)
static void out_of_memory_new_handler ()
static void bindingsErrorHandler (void *user_data, const char *reason, bool gen_crash_diag)
void LLVMInstallFatalErrorHandler (LLVMFatalErrorHandler Handler)
Install a fatal error handler.
void LLVMResetFatalErrorHandler ()
Reset the fatal error handler.
Variables
static fatal_error_handler_t ErrorHandler = nullptr
static void * ErrorHandlerUserData = nullptr
static fatal_error_handler_t BadAllocErrorHandler = nullptr
static void * BadAllocErrorHandlerUserData = nullptr
Function Documentation
bindingsErrorHandler()
void bindingsErrorHandler (void * user_data, const char * reason, bool gen_crash_diag) static
Definition at line 252 of file ErrorHandling.cpp.
References LLVM_EXTENSION.
Referenced by LLVMInstallFatalErrorHandler().
out_of_memory_new_handler()
void out_of_memory_new_handler () static
Definition at line 219 of file ErrorHandling.cpp.
References llvm::report_bad_alloc_error().
Referenced by llvm::install_out_of_memory_new_handler().
write_retry()
bool write_retry (int fd, const char * buf, size_t count) static
Definition at line 66 of file ErrorHandling.cpp.
References llvm::count(), llvm::sys::RetryAfterSignal(), and llvm::write().
Referenced by llvm::report_bad_alloc_error(), and llvm::report_fatal_error().
Variable Documentation
BadAllocErrorHandler
fatal_error_handler_t BadAllocErrorHandler = nullptr static
Definition at line 47 of file ErrorHandling.cpp.
Referenced by llvm::install_bad_alloc_error_handler(), llvm::remove_bad_alloc_error_handler(), and llvm::report_bad_alloc_error().
BadAllocErrorHandlerUserData
void* BadAllocErrorHandlerUserData = nullptr static
Definition at line 48 of file ErrorHandling.cpp.
Referenced by llvm::install_bad_alloc_error_handler(), llvm::remove_bad_alloc_error_handler(), and llvm::report_bad_alloc_error().
ErrorHandler
fatal_error_handler_t ErrorHandler = nullptr static
Definition at line 44 of file ErrorHandling.cpp.
Referenced by llvm::BTFContext::create(), llvm::dwarf_linker::parallel::DWARFLinker::createLinker(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::DWARFLinkerImpl(), llvm::install_fatal_error_handler(), llvm::remove_fatal_error_handler(), llvm::report_fatal_error(), and llvm::dwarf_linker::parallel::DWARFLinker::~DWARFLinker().
ErrorHandlerUserData
void* ErrorHandlerUserData = nullptr static
Definition at line 45 of file ErrorHandling.cpp.
Referenced by llvm::install_fatal_error_handler(), llvm::remove_fatal_error_handler(), and llvm::report_fatal_error().