LLVM: lib/Support/FormatVariadic.cpp File Reference
FormatVariadic.cpp File Reference
#include "llvm/Support/FormatVariadic.h"
#include <cassert>
#include <optional>
Macros
#define ENABLE_VALIDATION 1
Functions
static std::optional< AlignStyle > translateLocChar (char C)
static bool consumeFieldLayout (StringRef &Spec, AlignStyle &Where, unsigned &Align, char &Pad)
static std::optional< ReplacementItem > parseReplacementItem (StringRef Spec)
static std::pair< std::optional< ReplacementItem >, StringRef > splitLiteralAndReplacement (StringRef Fmt)
Macro Definition Documentation
ENABLE_VALIDATION
#define ENABLE_VALIDATION 1
Definition at line 136 of file FormatVariadic.cpp.
Function Documentation
consumeFieldLayout()
bool consumeFieldLayout (StringRef & Spec, AlignStyle & Where, unsigned & Align, char & Pad) static
Definition at line 28 of file FormatVariadic.cpp.
References llvm::Failed(), llvm::Right, and translateLocChar().
Referenced by parseReplacementItem().
parseReplacementItem()
std::optional< ReplacementItem > parseReplacementItem (StringRef Spec) static
Definition at line 57 of file FormatVariadic.cpp.
References assert(), llvm::StringRef::consume_front(), consumeFieldLayout(), llvm::StringRef::consumeInteger(), llvm::StringRef::empty(), llvm::StringRef::ltrim(), Options, llvm::Right, and llvm::StringRef::trim().
Referenced by splitLiteralAndReplacement().
splitLiteralAndReplacement()
std::pair< std::optional< ReplacementItem >, StringRef > splitLiteralAndReplacement (StringRef Fmt) static
Definition at line 93 of file FormatVariadic.cpp.
References assert(), llvm::CallingConv::C, llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::find_first_of(), llvm::StringRef::front(), llvm::StringRef::npos, parseReplacementItem(), llvm::Right, llvm::StringRef::size(), llvm::StringRef::slice(), llvm::StringRef::substr(), llvm::StringRef::take_front(), and llvm::StringRef::take_while().
Referenced by llvm::formatv_object_base::parseFormatString().
translateLocChar()
std::optional< AlignStyle > translateLocChar (char C) static
Definition at line 14 of file FormatVariadic.cpp.
References llvm::CallingConv::C, llvm::Center, llvm::Left, and llvm::Right.
Referenced by consumeFieldLayout().