LLVM: lib/CodeGen/GlobalMergeFunctions.cpp File Reference
GlobalMergeFunctions.cpp File Reference
#include "llvm/CodeGen/GlobalMergeFunctions.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ModuleSummaryAnalysis.h"
#include "llvm/CGData/CodeGenData.h"
#include "llvm/CGData/CodeGenDataWriter.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/StructuralHash.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
Classes
struct FuncMergeInfo
Tuple to hold function info to process merging.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "global-merge-func"
Functions
STATISTIC (NumMergedFunctions, "Number of functions that are actually merged using function hash")
STATISTIC (NumAnalyzedModues, "Number of modules that are analyzed")
STATISTIC (NumAnalyzedFunctions, "Number of functions that are analyzed")
STATISTIC (NumEligibleFunctions, "Number of functions that are eligible")
static bool isCalleeOperand (const CallBase *CI, unsigned OpIdx)
Returns true if the \OpIdx operand of CI is the callee operand.
static bool canParameterizeCallOperand (const CallBase *CI, unsigned OpIdx)
bool isEligibleFunction (Function *F)
Returns true if function F is eligible for merging.
static bool isEligibleInstructionForConstantSharing (const Instruction *I)
static bool ignoreOp (const Instruction *I, unsigned OpIdx)
static Function * createMergedFunction (FuncMergeInfo &FI, ArrayRef< Type * > ConstParamTypes, const ParamLocsVecTy &ParamLocsVec)
static void createThunk (FuncMergeInfo &FI, ArrayRef< Constant * > Params, Function *ToFunc)
static bool checkConstHashCompatible (const DenseMap< IndexPair, stable_hash > &OldInstOpndIndexToConstHash, const DenseMap< IndexPair, stable_hash > &CurrInstOpndIndexToConstHash)
static bool checkConstLocationCompatible (const StableFunctionMap::StableFunctionEntry &SF, const IndexInstrMap &IndexInstruction, const ParamLocsVecTy &ParamLocsVec)
static ParamLocsVecTy computeParamInfo (const SmallVector< std::unique_ptr< StableFunctionMap::StableFunctionEntry > > &SFS)
INITIALIZE_PASS_BEGIN (GlobalMergeFuncPassWrapper, "global-merge-func", "Global merge function pass", false, false) INITIALIZE_PASS_END(GlobalMergeFuncPassWrapper
LLVM_ABI ModulePass * llvm::createGlobalMergeFuncPass ()
This pass performs merging similar functions globally.
Variables
static cl::opt< bool > DisableCGDataForMerging ("disable-cgdata-for-merging", cl::Hidden, cl::desc("Disable codegen data for function merging. Local " "merging is still enabled within a module."), cl::init(false))
global merge func
global merge Global merge function pass
global merge Global merge function false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "global-merge-func"
Definition at line 25 of file GlobalMergeFunctions.cpp.
Function Documentation
canParameterizeCallOperand()
bool canParameterizeCallOperand (const CallBase * CI, unsigned OpIdx) static
Definition at line 47 of file GlobalMergeFunctions.cpp.
References llvm::dyn_cast_or_null(), llvm::CallBase::getCalledOperand(), llvm::CallBase::getOperandBundle(), isCalleeOperand(), llvm::CallBase::isInlineAsm(), llvm::CallBase::isOperandBundleOfType(), llvm::LLVMContext::OB_clang_arc_attachedcall, llvm::LLVMContext::OB_ptrauth, OpIdx, and llvm::Value::stripPointerCasts().
Referenced by ignoreOp().
checkConstHashCompatible()
bool checkConstHashCompatible (const DenseMap< IndexPair, stable_hash > & OldInstOpndIndexToConstHash, const DenseMap< IndexPair, stable_hash > & CurrInstOpndIndexToConstHash) static
Definition at line 302 of file GlobalMergeFunctions.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
Referenced by llvm::GlobalMergeFunc::merge().
checkConstLocationCompatible()
bool checkConstLocationCompatible (const StableFunctionMap::StableFunctionEntry & SF, const IndexInstrMap & IndexInstruction, const ParamLocsVecTy & ParamLocsVec) static
Definition at line 325 of file GlobalMergeFunctions.cpp.
References assert(), llvm::cast(), llvm::StableFunctionMap::StableFunctionEntry::IndexOperandHashMap, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), and llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size().
Referenced by llvm::GlobalMergeFunc::merge().
computeParamInfo()
ParamLocsVecTy computeParamInfo (const SmallVector< std::unique_ptr< StableFunctionMap::StableFunctionEntry > > & SFS) static
Definition at line 349 of file GlobalMergeFunctions.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sort().
Referenced by llvm::GlobalMergeFunc::merge().
createMergedFunction()
Function * createMergedFunction (FuncMergeInfo & FI, ArrayRef< Type * > ConstParamTypes, const ParamLocsVecTy & ParamLocsVec) static
Definition at line 182 of file GlobalMergeFunctions.cpp.
References llvm::Function::addFnAttr(), llvm::SmallVectorImpl< T >::append(), llvm::Function::arg_begin(), assert(), llvm::ArrayRef< T >::begin(), llvm::Function::begin(), llvm::Function::copyAttributesFrom(), llvm::Function::Create(), llvm::GlobalValue::DefaultStorageClass, llvm::ArrayRef< T >::end(), FuncMergeInfo::F, llvm::FunctionType::get(), llvm::Function::getArg(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Value::getType(), FuncMergeInfo::IndexInstruction, llvm::GlobalValue::InternalLinkage, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), llvm::GlobalMergeFunc::MergingInstanceSuffix, llvm::Value::replaceAllUsesWith(), llvm::GlobalValue::setDLLStorageClass(), llvm::GlobalValue::setLinkage(), llvm::Function::setSubprogram(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Function::splice(), and llvm::StringRef::str().
Referenced by llvm::GlobalMergeFunc::merge().
createThunk()
void createThunk (FuncMergeInfo & FI, ArrayRef< Constant * > Params, Function * ToFunc) static
Definition at line 247 of file GlobalMergeFunctions.cpp.
References assert(), llvm::BasicBlock::Create(), FuncMergeInfo::F, llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::Function::getFunctionType(), llvm::FunctionType::getNumParams(), llvm::CallBase::setAttributes(), llvm::CallBase::setCallingConv(), llvm::CallInst::setTailCallKind(), llvm::ArrayRef< T >::size(), llvm::CallingConv::SwiftTail, llvm::CallInst::TCK_MustTail, and llvm::CallInst::TCK_Tail.
Referenced by llvm::GlobalMergeFunc::merge().
ignoreOp()
bool ignoreOp (const Instruction * I, unsigned OpIdx) static
Definition at line 129 of file GlobalMergeFunctions.cpp.
References canParameterizeCallOperand(), llvm::dyn_cast(), I, llvm::isa(), isEligibleInstructionForConstantSharing(), and OpIdx.
Referenced by llvm::GlobalMergeFunc::analyze(), and llvm::GlobalMergeFunc::merge().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (GlobalMergeFuncPassWrapper , "global-merge-func" , "Global merge function pass" , false , false)
isCalleeOperand()
bool isCalleeOperand (const CallBase * CI, unsigned OpIdx) static
Returns true if the \OpIdx operand of CI is the callee operand.
Definition at line 43 of file GlobalMergeFunctions.cpp.
References llvm::CallBase::getCalledOperandUse(), llvm::User::getOperandUse(), and OpIdx.
Referenced by canParameterizeCallOperand().
isEligibleFunction()
bool isEligibleFunction (Function * F)
Returns true if function F is eligible for merging.
Definition at line 81 of file GlobalMergeFunctions.cpp.
References llvm::dyn_cast(), F, I, and llvm::CallingConv::SwiftTail.
Referenced by llvm::GlobalMergeFunc::analyze(), and llvm::GlobalMergeFunc::merge().
isEligibleInstructionForConstantSharing()
bool isEligibleInstructionForConstantSharing (const Instruction * I) static
Definition at line 113 of file GlobalMergeFunctions.cpp.
References I.
Referenced by ignoreOp().
STATISTIC() [1/4]
STATISTIC (NumAnalyzedFunctions , "Number of functions that are analyzed")
STATISTIC() [2/4]
STATISTIC (NumAnalyzedModues , "Number of modules that are analyzed")
STATISTIC() [3/4]
STATISTIC (NumEligibleFunctions , "Number of functions that are eligible")
STATISTIC() [4/4]
STATISTIC (NumMergedFunctions , "Number of functions that are actually merged using function hash")
Variable Documentation
DisableCGDataForMerging
cl::opt< bool > DisableCGDataForMerging("disable-cgdata-for-merging", cl::Hidden, cl::desc("Disable codegen data for function merging. Local " "merging is still enabled within a module."), cl::init(false)) ("disable-cgdata-for-merging" , cl::Hidden , cl::desc("Disable codegen data for function merging. Local " "merging is still enabled within a module.") , cl::init(false)) static
Referenced by llvm::GlobalMergeFunc::initializeMergerMode().
false
global merge Global merge function false
Definition at line 591 of file GlobalMergeFunctions.cpp.
func
global merge func
Definition at line 590 of file GlobalMergeFunctions.cpp.
Referenced by llvm::cl::AddExtraVersionPrinter(), llvm::WebAssembly::getLibcallSignature(), tomp::makeList(), llvm::yaml::MappingTraits< FunctionYAML >::mapping(), and llvm::cl::SetVersionPrinter().
pass
global merge Global merge function pass
Definition at line 591 of file GlobalMergeFunctions.cpp.
Referenced by LLVMTargetMachineEmit(), and llvm::verifySafepointIR().