LLVM: LLJIT Utilities
LLJIT Utilities
LLVM-C: C interface to LLVM » Execution Engine » LLJIT
Functions
LLVM_C_ABI LLVMErrorRef LLVMOrcLLJITEnableDebugSupport (LLVMOrcLLJITRef J)
Install the plugin that submits debug objects to the executor.
Detailed Description
Function Documentation
LLVMOrcLLJITEnableDebugSupport()
LLVM_C_ABI LLVMErrorRef LLVMOrcLLJITEnableDebugSupport (LLVMOrcLLJITRef J)
Install the plugin that submits debug objects to the executor.
Executors must expose the llvm_orc_registerJITLoaderGDBWrapper symbol.
Definition at line 20 of file LLJITUtilsCBindings.cpp.
References llvm::orc::enableDebuggerSupport(), LLVMOrcLLJITEnableDebugSupport(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMOrcLLJITEnableDebugSupport().