LLVM: Instruction Builders
Instruction Builders
LLVM-C: C interface to LLVM
An instruction builder represents a point within a basic block and is the exclusive means of building instructions using the C interface.
Functions
LLVM_C_ABI LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
LLVM_C_ABI LLVMBuilderRef LLVMCreateBuilder (void)
LLVM_C_ABI void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
Set the builder position before Instr but after any attached debug records, or if Instr is null set the position to the end of Block.
LLVM_C_ABI void LLVMPositionBuilderBeforeDbgRecords (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Inst)
Set the builder position before Instr and any attached debug records, or if Instr is null set the position to the end of Block.
LLVM_C_ABI void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
Set the builder position before Instr but after any attached debug records.
LLVM_C_ABI void LLVMPositionBuilderBeforeInstrAndDbgRecords (LLVMBuilderRef Builder, LLVMValueRef Instr)
Set the builder position before Instr and any attached debug records.
LLVM_C_ABI void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
LLVM_C_ABI LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
LLVM_C_ABI void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
LLVM_C_ABI void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
LLVM_C_ABI void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char *Name)
LLVM_C_ABI void LLVMDisposeBuilder (LLVMBuilderRef Builder)
LLVM_C_ABI LLVMMetadataRef LLVMGetCurrentDebugLocation2 (LLVMBuilderRef Builder)
Get location information used by debugging information.
LLVM_C_ABI void LLVMSetCurrentDebugLocation2 (LLVMBuilderRef Builder, LLVMMetadataRef Loc)
Set location information used by debugging information.
LLVM_C_ABI void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
Attempts to set the debug location for the given instruction using the current debug location for the given builder.
LLVM_C_ABI void LLVMAddMetadataToInst (LLVMBuilderRef Builder, LLVMValueRef Inst)
Adds the metadata registered with the given builder to the given instruction.
LLVM_C_ABI LLVMMetadataRef LLVMBuilderGetDefaultFPMathTag (LLVMBuilderRef Builder)
Get the dafult floating-point math metadata for a given builder.
LLVM_C_ABI void LLVMBuilderSetDefaultFPMathTag (LLVMBuilderRef Builder, LLVMMetadataRef FPMathTag)
Set the default floating-point math metadata for the given builder.
LLVM_C_ABI LLVMContextRef LLVMGetBuilderContext (LLVMBuilderRef Builder)
Obtain the context to which this builder is associated.
LLVM_C_ABI void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
Deprecated: Passing the NULL location will crash.
LLVM_C_ABI LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
Deprecated: Returning the NULL location will crash.
LLVM_C_ABI LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef)
LLVM_C_ABI LLVMValueRef LLVMBuildRet (LLVMBuilderRef, LLVMValueRef V)
LLVM_C_ABI LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef, LLVMValueRef *RetVals, unsigned N)
LLVM_C_ABI LLVMValueRef LLVMBuildBr (LLVMBuilderRef, LLVMBasicBlockRef Dest)
LLVM_C_ABI LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
LLVM_C_ABI LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
LLVM_C_ABI LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
LLVM_C_ABI LLVMValueRef LLVMBuildCallBr (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMBasicBlockRef DefaultDest, LLVMBasicBlockRef *IndirectDests, unsigned NumIndirectDests, LLVMValueRef *Args, unsigned NumArgs, LLVMOperandBundleRef *Bundles, unsigned NumBundles, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildInvoke2 (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildInvokeWithOperandBundles (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, LLVMOperandBundleRef *Bundles, unsigned NumBundles, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef)
LLVM_C_ABI LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
LLVM_C_ABI LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildCleanupRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
LLVM_C_ABI LLVMValueRef LLVMBuildCatchRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
LLVM_C_ABI LLVMValueRef LLVMBuildCatchPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildCleanupPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildCatchSwitch (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMBasicBlockRef UnwindBB, unsigned NumHandlers, const char *Name)
LLVM_C_ABI void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
LLVM_C_ABI void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
LLVM_C_ABI unsigned LLVMGetNumClauses (LLVMValueRef LandingPad)
LLVM_C_ABI LLVMValueRef LLVMGetClause (LLVMValueRef LandingPad, unsigned Idx)
LLVM_C_ABI void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
LLVM_C_ABI LLVMBool LLVMIsCleanup (LLVMValueRef LandingPad)
LLVM_C_ABI void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
LLVM_C_ABI void LLVMAddHandler (LLVMValueRef CatchSwitch, LLVMBasicBlockRef Dest)
LLVM_C_ABI unsigned LLVMGetNumHandlers (LLVMValueRef CatchSwitch)
LLVM_C_ABI void LLVMGetHandlers (LLVMValueRef CatchSwitch, LLVMBasicBlockRef *Handlers)
Obtain the basic blocks acting as handlers for a catchswitch instruction.
LLVM_C_ABI LLVMValueRef LLVMGetArgOperand (LLVMValueRef Funclet, unsigned i)
LLVM_C_ABI void LLVMSetArgOperand (LLVMValueRef Funclet, unsigned i, LLVMValueRef value)
LLVM_C_ABI LLVMValueRef LLVMGetParentCatchSwitch (LLVMValueRef CatchPad)
Get the parent catchswitch instruction of a catchpad instruction.
LLVM_C_ABI void LLVMSetParentCatchSwitch (LLVMValueRef CatchPad, LLVMValueRef CatchSwitch)
Set the parent catchswitch instruction of a catchpad instruction.
LLVM_C_ABI LLVMValueRef LLVMBuildAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildExactUDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildURem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildSRem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFRem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildShl (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildLShr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildAShr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildAnd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildOr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildXor (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNeg (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMValueRef LLVMBuildNUWNeg(LLVMBuilderRef B, LLVMValueRef V, const char *Name), "Use LLVMBuildNeg + LLVMSetNUW instead.")
LLVM_C_ABI LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildNot (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVM_C_ABI LLVMBool LLVMGetNUW (LLVMValueRef ArithInst)
LLVM_C_ABI void LLVMSetNUW (LLVMValueRef ArithInst, LLVMBool HasNUW)
LLVM_C_ABI LLVMBool LLVMGetNSW (LLVMValueRef ArithInst)
LLVM_C_ABI void LLVMSetNSW (LLVMValueRef ArithInst, LLVMBool HasNSW)
LLVM_C_ABI LLVMBool LLVMGetExact (LLVMValueRef DivOrShrInst)
LLVM_C_ABI void LLVMSetExact (LLVMValueRef DivOrShrInst, LLVMBool IsExact)
LLVM_C_ABI LLVMBool LLVMGetNNeg (LLVMValueRef NonNegInst)
Gets if the instruction has the non-negative flag set.
LLVM_C_ABI void LLVMSetNNeg (LLVMValueRef NonNegInst, LLVMBool IsNonNeg)
Sets the non-negative flag for the instruction.
LLVM_C_ABI LLVMFastMathFlags LLVMGetFastMathFlags (LLVMValueRef FPMathInst)
Get the flags for which fast-math-style optimizations are allowed for this value.
LLVM_C_ABI void LLVMSetFastMathFlags (LLVMValueRef FPMathInst, LLVMFastMathFlags FMF)
Sets the flags for which fast-math-style optimizations are allowed for this value.
LLVM_C_ABI LLVMBool LLVMCanValueUseFastMathFlags (LLVMValueRef Inst)
Check if a given value can potentially have fast math flags.
LLVM_C_ABI LLVMBool LLVMGetIsDisjoint (LLVMValueRef Inst)
Gets whether the instruction has the disjoint flag set.
LLVM_C_ABI void LLVMSetIsDisjoint (LLVMValueRef Inst, LLVMBool IsDisjoint)
Sets the disjoint flag for the instruction.
LLVM_C_ABI LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildMemSet (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Val, LLVMValueRef Len, unsigned Align)
Creates and inserts a memset to the specified pointer and the specified value.
LLVM_C_ABI LLVMValueRef LLVMBuildMemCpy (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memcpy between the specified pointers.
LLVM_C_ABI LLVMValueRef LLVMBuildMemMove (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memmove between the specified pointers.
LLVM_C_ABI LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFree (LLVMBuilderRef, LLVMValueRef PointerVal)
LLVM_C_ABI LLVMValueRef LLVMBuildLoad2 (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef PointerVal, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildStore (LLVMBuilderRef, LLVMValueRef Val, LLVMValueRef Ptr)
LLVM_C_ABI LLVMValueRef LLVMBuildGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildInBoundsGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildGEPWithNoWrapFlags (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name, LLVMGEPNoWrapFlags NoWrapFlags)
Creates a GetElementPtr instruction.
LLVM_C_ABI LLVMValueRef LLVMBuildStructGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, unsigned Idx, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char *Str, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char *Str, const char *Name)
Deprecated: Use LLVMBuildGlobalString instead, which has identical behavior.
LLVM_C_ABI LLVMBool LLVMGetVolatile (LLVMValueRef MemoryAccessInst)
LLVM_C_ABI void LLVMSetVolatile (LLVMValueRef MemoryAccessInst, LLVMBool IsVolatile)
LLVM_C_ABI LLVMBool LLVMGetWeak (LLVMValueRef CmpXchgInst)
LLVM_C_ABI void LLVMSetWeak (LLVMValueRef CmpXchgInst, LLVMBool IsWeak)
LLVM_C_ABI LLVMAtomicOrdering LLVMGetOrdering (LLVMValueRef MemoryAccessInst)
LLVM_C_ABI void LLVMSetOrdering (LLVMValueRef MemoryAccessInst, LLVMAtomicOrdering Ordering)
LLVM_C_ABI LLVMAtomicRMWBinOp LLVMGetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst)
LLVM_C_ABI void LLVMSetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst, LLVMAtomicRMWBinOp BinOp)
LLVM_C_ABI LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildZExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildSExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildIntCast2 (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, LLVMBool IsSigned, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
Deprecated: This cast is always signed.
LLVM_C_ABI LLVMOpcode LLVMGetCastOpcode (LLVMValueRef Src, LLVMBool SrcIsSigned, LLVMTypeRef DestTy, LLVMBool DestIsSigned)
LLVM_C_ABI LLVMValueRef LLVMBuildICmp (LLVMBuilderRef, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildPhi (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildCall2 (LLVMBuilderRef, LLVMTypeRef, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildCallWithOperandBundles (LLVMBuilderRef, LLVMTypeRef, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMOperandBundleRef *Bundles, unsigned NumBundles, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildSelect (LLVMBuilderRef, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef, LLVMValueRef List, LLVMTypeRef Ty, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef, LLVMValueRef VecVal, LLVMValueRef Index, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef, LLVMValueRef AggVal, unsigned Index, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFreeze (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildPtrDiff2 (LLVMBuilderRef, LLVMTypeRef ElemTy, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering ordering, LLVMBool singleThread, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildFenceSyncScope (LLVMBuilderRef B, LLVMAtomicOrdering ordering, unsigned SSID, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicRMWSyncScope (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, unsigned SSID)
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicCmpXchg (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, LLVMBool SingleThread)
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicCmpXchgSyncScope (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, unsigned SSID)
LLVM_C_ABI unsigned LLVMGetNumMaskElements (LLVMValueRef ShuffleVectorInst)
Get the number of elements in the mask of a ShuffleVector instruction.
LLVM_C_ABI int LLVMGetUndefMaskElem (void)
LLVM_C_ABI int LLVMGetMaskValue (LLVMValueRef ShuffleVectorInst, unsigned Elt)
Get the mask value at position Elt in the mask of a ShuffleVector instruction.
LLVM_C_ABI LLVMBool LLVMIsAtomicSingleThread (LLVMValueRef AtomicInst)
LLVM_C_ABI void LLVMSetAtomicSingleThread (LLVMValueRef AtomicInst, LLVMBool SingleThread)
LLVM_C_ABI LLVMBool LLVMIsAtomic (LLVMValueRef Inst)
Returns whether an instruction is an atomic instruction, e.g., atomicrmw, cmpxchg, fence, or loads and stores with atomic ordering.
LLVM_C_ABI unsigned LLVMGetAtomicSyncScopeID (LLVMValueRef AtomicInst)
Returns the synchronization scope ID of an atomic instruction.
LLVM_C_ABI void LLVMSetAtomicSyncScopeID (LLVMValueRef AtomicInst, unsigned SSID)
Sets the synchronization scope ID of an atomic instruction.
LLVM_C_ABI LLVMAtomicOrdering LLVMGetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst)
LLVM_C_ABI void LLVMSetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
LLVM_C_ABI LLVMAtomicOrdering LLVMGetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst)
LLVM_C_ABI void LLVMSetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Detailed Description
An instruction builder represents a point within a basic block and is the exclusive means of building instructions using the C interface.
Function Documentation
LLVM_ATTRIBUTE_C_DEPRECATED()
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMValueRef LLVMBuildNUWNegLLVMBuilderRef B, LLVMValueRef V, const char *Name, "Use LLVMBuildNeg + LLVMSetNUW instead.")
References B(), F, LHS, LLVM_C_ABI, LLVM_C_EXTERN_C_END, op, Ptr, RHS, SingleThread, and Size.
LLVMAddCase()
LLVM_C_ABI void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
Definition at line 3526 of file Core.cpp.
References llvm::unwrap().
LLVMAddClause()
LLVM_C_ABI void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
Definition at line 3543 of file Core.cpp.
References llvm::unwrap().
LLVMAddDestination()
LLVM_C_ABI void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
Definition at line 3531 of file Core.cpp.
References llvm::unwrap().
LLVMAddHandler()
LLVM_C_ABI void LLVMAddHandler (LLVMValueRef CatchSwitch, LLVMBasicBlockRef Dest)
Definition at line 3555 of file Core.cpp.
References llvm::unwrap().
LLVMAddMetadataToInst()
LLVM_C_ABI void LLVMAddMetadataToInst (LLVMBuilderRef Builder, LLVMValueRef Inst)
Adds the metadata registered with the given builder to the given instruction.
See also
llvm::IRBuilder::AddMetadataToInst()
Definition at line 3369 of file Core.cpp.
References llvm::unwrap().
LLVMBuildAdd()
LLVM_C_ABI LLVMValueRef LLVMBuildAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3623 of file Core.cpp.
References B(), CreateAdd(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildAddrSpaceCast()
LLVM_C_ABI LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4206 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildAggregateRet()
LLVM_C_ABI LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef B, LLVMValueRef * RetVals, unsigned N)
Definition at line 3399 of file Core.cpp.
References B(), N, llvm::unwrap(), and llvm::wrap().
LLVMBuildAlloca()
LLVM_C_ABI LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3896 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildAnd()
LLVM_C_ABI LLVMValueRef LLVMBuildAnd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3738 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayAlloca()
LLVM_C_ABI LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 3901 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayMalloc()
LLVM_C_ABI LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 3862 of file Core.cpp.
References B(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMBuildAShr()
LLVM_C_ABI LLVMValueRef LLVMBuildAShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3733 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicCmpXchg()
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicCmpXchg (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, LLVMBool SingleThread)
Definition at line 4397 of file Core.cpp.
References B(), mapFromLLVMOrdering(), Ptr, llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicCmpXchgSyncScope()
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicCmpXchgSyncScope (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, unsigned SSID)
Definition at line 4410 of file Core.cpp.
References B(), mapFromLLVMOrdering(), Ptr, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicRMW()
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
Definition at line 4375 of file Core.cpp.
References B(), mapFromLLVMOrdering(), mapFromLLVMRMWBinOp(), op, llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicRMWSyncScope()
LLVM_C_ABI LLVMValueRef LLVMBuildAtomicRMWSyncScope (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, unsigned SSID)
Definition at line 4386 of file Core.cpp.
References B(), mapFromLLVMOrdering(), mapFromLLVMRMWBinOp(), op, llvm::unwrap(), and llvm::wrap().
LLVMBuildBinOp()
LLVM_C_ABI LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3753 of file Core.cpp.
References B(), LHS, map_from_llvmopcode(), RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildBitCast()
LLVM_C_ABI LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4201 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildBr()
LLVM_C_ABI LLVMValueRef LLVMBuildBr (LLVMBuilderRef B, LLVMBasicBlockRef Dest)
Definition at line 3404 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCall2()
LLVM_C_ABI LLVMValueRef LLVMBuildCall2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 4286 of file Core.cpp.
References llvm::ArrayRef(), B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCallBr()
LLVM_C_ABI LLVMValueRef LLVMBuildCallBr (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMBasicBlockRef DefaultDest, LLVMBasicBlockRef * IndirectDests, unsigned NumIndirectDests, LLVMValueRef * Args, unsigned NumArgs, LLVMOperandBundleRef * Bundles, unsigned NumBundles, const char * Name)
Definition at line 3423 of file Core.cpp.
References llvm::ArrayRef(), B(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCallWithOperandBundles()
LLVM_C_ABI LLVMValueRef LLVMBuildCallWithOperandBundles (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMOperandBundleRef * Bundles, unsigned NumBundles, const char * Name)
Definition at line 4295 of file Core.cpp.
References llvm::ArrayRef(), B(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCast()
LLVM_C_ABI LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4229 of file Core.cpp.
References B(), map_from_llvmopcode(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchPad()
LLVM_C_ABI LLVMValueRef LLVMBuildCatchPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3477 of file Core.cpp.
References llvm::ArrayRef(), B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchRet()
LLVM_C_ABI LLVMValueRef LLVMBuildCatchRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
Definition at line 3510 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchSwitch()
LLVM_C_ABI LLVMValueRef LLVMBuildCatchSwitch (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMBasicBlockRef UnwindBB, unsigned NumHandlers, const char * Name)
Definition at line 3499 of file Core.cpp.
References B(), llvm::Constant::getNullValue(), llvm::Type::getTokenTy(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCleanupPad()
LLVM_C_ABI LLVMValueRef LLVMBuildCleanupPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3484 of file Core.cpp.
References llvm::ArrayRef(), B(), llvm::Constant::getNullValue(), llvm::Type::getTokenTy(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCleanupRet()
LLVM_C_ABI LLVMValueRef LLVMBuildCleanupRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
Definition at line 3516 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCondBr()
LLVM_C_ABI LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef B, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
Definition at line 3408 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuilderGetDefaultFPMathTag()
LLVM_C_ABI LLVMMetadataRef LLVMBuilderGetDefaultFPMathTag (LLVMBuilderRef Builder)
Get the dafult floating-point math metadata for a given builder.
See also
llvm::IRBuilder::getDefaultFPMathTag()
Definition at line 3385 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuilderSetDefaultFPMathTag()
LLVM_C_ABI void LLVMBuilderSetDefaultFPMathTag (LLVMBuilderRef Builder, LLVMMetadataRef FPMathTag)
Set the default floating-point math metadata for the given builder.
To clear the metadata, pass NULL to FPMathTag.
See also
llvm::IRBuilder::setDefaultFPMathTag()
Definition at line 3373 of file Core.cpp.
References llvm::unwrap().
LLVMBuildExactSDiv()
LLVM_C_ABI LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3698 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildExactUDiv()
LLVM_C_ABI LLVMValueRef LLVMBuildExactUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3688 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractElement()
LLVM_C_ABI LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef Index, const char * Name)
Definition at line 4321 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractValue()
LLVM_C_ABI LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef B, LLVMValueRef AggVal, unsigned Index, const char * Name)
Definition at line 4341 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFAdd()
LLVM_C_ABI LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3638 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFCmp()
LLVM_C_ABI LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef B, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 4273 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFDiv()
LLVM_C_ABI LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3703 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFence()
LLVM_C_ABI LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering ordering, LLVMBool singleThread, const char * Name)
Definition at line 4021 of file Core.cpp.
References B(), mapFromLLVMOrdering(), llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildFenceSyncScope()
LLVM_C_ABI LLVMValueRef LLVMBuildFenceSyncScope (LLVMBuilderRef B, LLVMAtomicOrdering ordering, unsigned SSID, const char * Name)
Definition at line 4030 of file Core.cpp.
References B(), mapFromLLVMOrdering(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFMul()
LLVM_C_ABI LLVMValueRef LLVMBuildFMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3678 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFNeg()
LLVM_C_ABI LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3777 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFPCast()
LLVM_C_ABI LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4253 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFPExt()
LLVM_C_ABI LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4186 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToSI()
LLVM_C_ABI LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4166 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToUI()
LLVM_C_ABI LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4161 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFPTrunc()
LLVM_C_ABI LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4181 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFree()
LLVM_C_ABI LLVMValueRef LLVMBuildFree (LLVMBuilderRef B, LLVMValueRef PointerVal)
Definition at line 3906 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFreeze()
LLVM_C_ABI LLVMValueRef LLVMBuildFreeze (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 4353 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFRem()
LLVM_C_ABI LLVMValueRef LLVMBuildFRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3718 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFSub()
LLVM_C_ABI LLVMValueRef LLVMBuildFSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3658 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildGEP2()
LLVM_C_ABI LLVMValueRef LLVMBuildGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 4037 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildGEPWithNoWrapFlags()
LLVM_C_ABI LLVMValueRef LLVMBuildGEPWithNoWrapFlags (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name, LLVMGEPNoWrapFlags NoWrapFlags)
Creates a GetElementPtr instruction.
Similar to LLVMBuildGEP2, but allows specifying the no-wrap flags.
See also
llvm::IRBuilder::CreateGEP()
Definition at line 4052 of file Core.cpp.
References B(), mapFromLLVMGEPNoWrapFlags(), llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalString()
LLVM_C_ABI LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char * Str, const char * Name)
Definition at line 4069 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalStringPtr()
LLVM_C_ABI LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char * Str, const char * Name)
Deprecated: Use LLVMBuildGlobalString instead, which has identical behavior.
Definition at line 4074 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildICmp()
LLVM_C_ABI LLVMValueRef LLVMBuildICmp (LLVMBuilderRef B, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 4266 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildInBoundsGEP2()
LLVM_C_ABI LLVMValueRef LLVMBuildInBoundsGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 4044 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildIndirectBr()
LLVM_C_ABI LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
Definition at line 3418 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertElement()
LLVM_C_ABI LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char * Name)
Definition at line 4327 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertValue()
LLVM_C_ABI LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef B, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char * Name)
Definition at line 4346 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildIntCast()
LLVM_C_ABI LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Deprecated: This cast is always signed.
Use LLVMBuildIntCast2 instead.
Definition at line 4247 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildIntCast2()
LLVM_C_ABI LLVMValueRef LLVMBuildIntCast2 (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, LLVMBool IsSigned, const char * Name)
Definition at line 4240 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildIntToPtr()
LLVM_C_ABI LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4196 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildInvoke2()
LLVM_C_ABI LLVMValueRef LLVMBuildInvoke2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char * Name)
Definition at line 3442 of file Core.cpp.
References llvm::ArrayRef(), B(), llvm::Catch, llvm::unwrap(), and llvm::wrap().
LLVMBuildInvokeWithOperandBundles()
LLVM_C_ABI LLVMValueRef LLVMBuildInvokeWithOperandBundles (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, LLVMOperandBundleRef * Bundles, unsigned NumBundles, const char * Name)
Definition at line 3451 of file Core.cpp.
References llvm::ArrayRef(), B(), llvm::Catch, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNotNull()
LLVM_C_ABI LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 4363 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNull()
LLVM_C_ABI LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 4358 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildLandingPad()
LLVM_C_ABI LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char * Name)
Definition at line 3465 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildLoad2()
LLVM_C_ABI LLVMValueRef LLVMBuildLoad2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PointerVal, const char * Name)
Definition at line 3910 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildLShr()
LLVM_C_ABI LLVMValueRef LLVMBuildLShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3728 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildMalloc()
LLVM_C_ABI LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3853 of file Core.cpp.
References B(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::unwrap(), and llvm::wrap().
LLVMBuildMemCpy()
LLVM_C_ABI LLVMValueRef LLVMBuildMemCpy (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memcpy between the specified pointers.
See also
llvm::IRRBuilder::CreateMemCpy()
Definition at line 3878 of file Core.cpp.
References B(), Size, llvm::unwrap(), and llvm::wrap().
LLVMBuildMemMove()
LLVM_C_ABI LLVMValueRef LLVMBuildMemMove (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memmove between the specified pointers.
See also
llvm::IRRBuilder::CreateMemMove()
Definition at line 3887 of file Core.cpp.
References B(), Size, llvm::unwrap(), and llvm::wrap().
LLVMBuildMemSet()
LLVM_C_ABI LLVMValueRef LLVMBuildMemSet (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Val, LLVMValueRef Len, unsigned Align)
Creates and inserts a memset to the specified pointer and the specified value.
See also
llvm::IRRBuilder::CreateMemSet()
Definition at line 3871 of file Core.cpp.
References B(), Ptr, llvm::unwrap(), and llvm::wrap().
LLVMBuildMul()
LLVM_C_ABI LLVMValueRef LLVMBuildMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3663 of file Core.cpp.
References B(), CreateMul(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNeg()
LLVM_C_ABI LLVMValueRef LLVMBuildNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3760 of file Core.cpp.
References B(), CreateNeg(), llvm::unwrap(), and llvm::wrap().
LLVMBuildNot()
LLVM_C_ABI LLVMValueRef LLVMBuildNot (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3781 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWAdd()
LLVM_C_ABI LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3628 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWMul()
LLVM_C_ABI LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3668 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWNeg()
LLVM_C_ABI LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3764 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWSub()
LLVM_C_ABI LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3648 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWAdd()
LLVM_C_ABI LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3633 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWMul()
LLVM_C_ABI LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3673 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWSub()
LLVM_C_ABI LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3653 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildOr()
LLVM_C_ABI LLVMValueRef LLVMBuildOr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3743 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildPhi()
LLVM_C_ABI LLVMValueRef LLVMBuildPhi (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 4282 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildPointerCast()
LLVM_C_ABI LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4235 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrDiff2()
LLVM_C_ABI LLVMValueRef LLVMBuildPtrDiff2 (LLVMBuilderRef B, LLVMTypeRef ElemTy, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 4368 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrToInt()
LLVM_C_ABI LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4191 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildResume()
LLVM_C_ABI LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
Definition at line 3495 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildRet()
LLVM_C_ABI LLVMValueRef LLVMBuildRet (LLVMBuilderRef B, LLVMValueRef V)
Definition at line 3395 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildRetVoid()
LLVM_C_ABI LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef B)
Definition at line 3391 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildSDiv()
LLVM_C_ABI LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3693 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildSelect()
LLVM_C_ABI LLVMValueRef LLVMBuildSelect (LLVMBuilderRef B, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char * Name)
Definition at line 4309 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildSExt()
LLVM_C_ABI LLVMValueRef LLVMBuildSExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4156 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildSExtOrBitCast()
LLVM_C_ABI LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4217 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildShl()
LLVM_C_ABI LLVMValueRef LLVMBuildShl (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3723 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildShuffleVector()
LLVM_C_ABI LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef B, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char * Name)
Definition at line 4334 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildSIToFP()
LLVM_C_ABI LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4176 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildSRem()
LLVM_C_ABI LLVMValueRef LLVMBuildSRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3713 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildStore()
LLVM_C_ABI LLVMValueRef LLVMBuildStore (LLVMBuilderRef B, LLVMValueRef Val, LLVMValueRef Ptr)
Definition at line 3915 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildStructGEP2()
LLVM_C_ABI LLVMValueRef LLVMBuildStructGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, unsigned Idx, const char * Name)
Definition at line 4062 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildSub()
LLVM_C_ABI LLVMValueRef LLVMBuildSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3643 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildSwitch()
LLVM_C_ABI LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef B, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
Definition at line 3413 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildTrunc()
LLVM_C_ABI LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4146 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildTruncOrBitCast()
LLVM_C_ABI LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4223 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildUDiv()
LLVM_C_ABI LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3683 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildUIToFP()
LLVM_C_ABI LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4171 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildUnreachable()
LLVM_C_ABI LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef B)
Definition at line 3522 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildURem()
LLVM_C_ABI LLVMValueRef LLVMBuildURem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3708 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildVAArg()
LLVM_C_ABI LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef B, LLVMValueRef List, LLVMTypeRef Ty, const char * Name)
Definition at line 4316 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildXor()
LLVM_C_ABI LLVMValueRef LLVMBuildXor (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3748 of file Core.cpp.
References B(), LHS, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildZExt()
LLVM_C_ABI LLVMValueRef LLVMBuildZExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4151 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMBuildZExtOrBitCast()
LLVM_C_ABI LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 4211 of file Core.cpp.
References B(), llvm::unwrap(), and llvm::wrap().
LLVMCanValueUseFastMathFlags()
LLVM_C_ABI LLVMBool LLVMCanValueUseFastMathFlags (LLVMValueRef Inst)
Check if a given value can potentially have fast math flags.
Will return true for floating point arithmetic instructions, and for select, phi, and call instructions whose type is a floating point type, or a vector or array thereof. See https://llvm.org/docs/LangRef.html#fast-math-flags
Definition at line 3836 of file Core.cpp.
References llvm::isa(), and llvm::unwrap().
LLVMClearInsertionPosition()
LLVM_C_ABI void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
Definition at line 3323 of file Core.cpp.
References llvm::unwrap().
LLVMCreateBuilder()
LLVM_C_ABI LLVMBuilderRef LLVMCreateBuilder (void)
Definition at line 3279 of file Core.cpp.
References LLVMCreateBuilderInContext(), and LLVMGetGlobalContext().
LLVMCreateBuilderInContext()
LLVM_C_ABI LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
Definition at line 3275 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateBuilder().
LLVMDisposeBuilder()
LLVM_C_ABI void LLVMDisposeBuilder (LLVMBuilderRef Builder)
Definition at line 3336 of file Core.cpp.
References llvm::unwrap().
LLVMGetArgOperand()
LLVM_C_ABI LLVMValueRef LLVMGetArgOperand (LLVMValueRef Funclet, unsigned i)
Definition at line 3580 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetAtomicRMWBinOp()
LLVM_C_ABI LLVMAtomicRMWBinOp LLVMGetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst)
Definition at line 4136 of file Core.cpp.
References mapToLLVMRMWBinOp(), and llvm::unwrap().
LLVMGetAtomicSyncScopeID()
LLVM_C_ABI unsigned LLVMGetAtomicSyncScopeID (LLVMValueRef AtomicInst)
Returns the synchronization scope ID of an atomic instruction.
Definition at line 4458 of file Core.cpp.
References assert(), llvm::getAtomicSyncScopeID(), I, and llvm::unwrap().
LLVMGetBuilderContext()
LLVM_C_ABI LLVMContextRef LLVMGetBuilderContext (LLVMBuilderRef Builder)
Obtain the context to which this builder is associated.
See also
llvm::IRBuilder::getContext()
Definition at line 3381 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetCastOpcode()
LLVM_C_ABI LLVMOpcode LLVMGetCastOpcode (LLVMValueRef Src, LLVMBool SrcIsSigned, LLVMTypeRef DestTy, LLVMBool DestIsSigned)
Definition at line 4258 of file Core.cpp.
References llvm::CastInst::getCastOpcode(), map_to_llvmopcode(), and llvm::unwrap().
LLVMGetClause()
LLVM_C_ABI LLVMValueRef LLVMGetClause (LLVMValueRef LandingPad, unsigned Idx)
Definition at line 3539 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetCmpXchgFailureOrdering()
LLVM_C_ABI LLVMAtomicOrdering LLVMGetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst)
Definition at line 4483 of file Core.cpp.
References llvm::cast(), mapToLLVMOrdering(), P, and llvm::unwrap().
LLVMGetCmpXchgSuccessOrdering()
LLVM_C_ABI LLVMAtomicOrdering LLVMGetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst)
Definition at line 4470 of file Core.cpp.
References llvm::cast(), mapToLLVMOrdering(), P, and llvm::unwrap().
LLVMGetCurrentDebugLocation()
LLVM_C_ABI LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
Deprecated: Returning the NULL location will crash.
Use LLVMGetCurrentDebugLocation2 instead.
Definition at line 3359 of file Core.cpp.
References llvm::MetadataAsValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetCurrentDebugLocation2()
LLVM_C_ABI LLVMMetadataRef LLVMGetCurrentDebugLocation2 (LLVMBuilderRef Builder)
Get location information used by debugging information.
See also
llvm::IRBuilder::getCurrentDebugLocation()
Definition at line 3342 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetExact()
LLVM_C_ABI LLVMBool LLVMGetExact (LLVMValueRef DivOrShrInst)
Definition at line 3805 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMGetFastMathFlags()
LLVM_C_ABI LLVMFastMathFlags LLVMGetFastMathFlags (LLVMValueRef FPMathInst)
Get the flags for which fast-math-style optimizations are allowed for this value.
Only valid on floating point instructions.
See also
LLVMCanValueUseFastMathFlags
Definition at line 3825 of file Core.cpp.
References llvm::cast(), mapToLLVMFastMathFlags(), P, and llvm::unwrap().
LLVMGetHandlers()
LLVM_C_ABI void LLVMGetHandlers (LLVMValueRef CatchSwitch, LLVMBasicBlockRef * Handlers)
Obtain the basic blocks acting as handlers for a catchswitch instruction.
The Handlers parameter should point to a pre-allocated array of LLVMBasicBlockRefs at least LLVMGetNumHandlers() large. On return, the first LLVMGetNumHandlers() entries in the array will be populated with LLVMBasicBlockRef instances.
Parameters
CatchSwitch The catchswitch instruction to operate on.
Handlers Memory address of an array to be filled with basic blocks.
Definition at line 3563 of file Core.cpp.
References H, llvm::CatchSwitchInst::handlers(), llvm::unwrap(), and llvm::wrap().
LLVMGetInsertBlock()
LLVM_C_ABI LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
Definition at line 3319 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetIsDisjoint()
LLVM_C_ABI LLVMBool LLVMGetIsDisjoint (LLVMValueRef Inst)
Gets whether the instruction has the disjoint flag set.
Only valid for or instructions.
Definition at line 3841 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMGetMaskValue()
LLVM_C_ABI int LLVMGetMaskValue (LLVMValueRef ShuffleVectorInst, unsigned Elt)
Get the mask value at position Elt in the mask of a ShuffleVector instruction.
\Returns the result of LLVMGetUndefMaskElem() if the mask value is poison at that position.
Definition at line 4427 of file Core.cpp.
References llvm::cast(), I, P, and llvm::unwrap().
LLVMGetNNeg()
LLVM_C_ABI LLVMBool LLVMGetNNeg (LLVMValueRef NonNegInst)
Gets if the instruction has the non-negative flag set.
Only valid for zext instructions.
Definition at line 3815 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMGetNSW()
LLVM_C_ABI LLVMBool LLVMGetNSW (LLVMValueRef ArithInst)
Definition at line 3795 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMGetNumClauses()
LLVM_C_ABI unsigned LLVMGetNumClauses (LLVMValueRef LandingPad)
Definition at line 3535 of file Core.cpp.
References llvm::unwrap().
LLVMGetNumHandlers()
LLVM_C_ABI unsigned LLVMGetNumHandlers (LLVMValueRef CatchSwitch)
Definition at line 3559 of file Core.cpp.
References llvm::unwrap().
LLVMGetNumMaskElements()
LLVM_C_ABI unsigned LLVMGetNumMaskElements (LLVMValueRef ShuffleVectorInst)
Get the number of elements in the mask of a ShuffleVector instruction.
Definition at line 4421 of file Core.cpp.
References llvm::cast(), I, P, and llvm::unwrap().
LLVMGetNUW()
LLVM_C_ABI LLVMBool LLVMGetNUW (LLVMValueRef ArithInst)
Definition at line 3785 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMGetOrdering()
LLVM_C_ABI LLVMAtomicOrdering LLVMGetOrdering (LLVMValueRef MemoryAccessInst)
Definition at line 4109 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), mapToLLVMOrdering(), P, and llvm::unwrap().
LLVMGetParentCatchSwitch()
LLVM_C_ABI LLVMValueRef LLVMGetParentCatchSwitch (LLVMValueRef CatchPad)
Get the parent catchswitch instruction of a catchpad instruction.
This only works on llvm::CatchPadInst instructions.
See also
llvm::CatchPadInst::getCatchSwitch()
Definition at line 3569 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetUndefMaskElem()
LLVM_C_ABI int LLVMGetUndefMaskElem (void)
Returns
a constant that specifies that the result of a ShuffleVectorInst is undefined.
Definition at line 4433 of file Core.cpp.
References llvm::PoisonMaskElem.
LLVMGetVolatile()
LLVM_C_ABI LLVMBool LLVMGetVolatile (LLVMValueRef MemoryAccessInst)
Definition at line 4079 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), P, and llvm::unwrap().
LLVMGetWeak()
LLVM_C_ABI LLVMBool LLVMGetWeak (LLVMValueRef CmpXchgInst)
Definition at line 4101 of file Core.cpp.
References llvm::unwrap().
LLVMInsertIntoBuilder()
LLVM_C_ABI void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
Definition at line 3327 of file Core.cpp.
References llvm::unwrap().
LLVMInsertIntoBuilderWithName()
LLVM_C_ABI void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char * Name)
Definition at line 3331 of file Core.cpp.
References llvm::unwrap().
LLVMIsAtomic()
LLVM_C_ABI LLVMBool LLVMIsAtomic (LLVMValueRef Inst)
Returns whether an instruction is an atomic instruction, e.g., atomicrmw, cmpxchg, fence, or loads and stores with atomic ordering.
Definition at line 4435 of file Core.cpp.
References llvm::unwrap().
LLVMIsAtomicSingleThread()
LLVM_C_ABI LLVMBool LLVMIsAtomicSingleThread (LLVMValueRef AtomicInst)
Definition at line 4439 of file Core.cpp.
References llvm::getAtomicSyncScopeID(), I, llvm::SyncScope::SingleThread, and llvm::unwrap().
LLVMIsCleanup()
LLVM_C_ABI LLVMBool LLVMIsCleanup (LLVMValueRef LandingPad)
Definition at line 3547 of file Core.cpp.
References llvm::unwrap().
LLVMPositionBuilder()
LLVM_C_ABI void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
Set the builder position before Instr but after any attached debug records, or if Instr is null set the position to the end of Block.
Definition at line 3290 of file Core.cpp.
References llvm::Block, LLVMPositionBuilderImpl(), and llvm::unwrap().
LLVMPositionBuilderAtEnd()
LLVM_C_ABI void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
Definition at line 3314 of file Core.cpp.
References llvm::Block, and llvm::unwrap().
LLVMPositionBuilderBefore()
LLVM_C_ABI void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
Set the builder position before Instr but after any attached debug records.
Definition at line 3303 of file Core.cpp.
References I, LLVMPositionBuilderImpl(), and llvm::unwrap().
LLVMPositionBuilderBeforeDbgRecords()
LLVM_C_ABI void LLVMPositionBuilderBeforeDbgRecords (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Inst)
Set the builder position before Instr and any attached debug records, or if Instr is null set the position to the end of Block.
Definition at line 3296 of file Core.cpp.
References llvm::Block, LLVMPositionBuilderImpl(), and llvm::unwrap().
LLVMPositionBuilderBeforeInstrAndDbgRecords()
LLVM_C_ABI void LLVMPositionBuilderBeforeInstrAndDbgRecords (LLVMBuilderRef Builder, LLVMValueRef Instr)
Set the builder position before Instr and any attached debug records.
Definition at line 3308 of file Core.cpp.
References I, LLVMPositionBuilderImpl(), and llvm::unwrap().
LLVMSetArgOperand()
LLVM_C_ABI void LLVMSetArgOperand (LLVMValueRef Funclet, unsigned i, LLVMValueRef value)
Definition at line 3584 of file Core.cpp.
References llvm::unwrap().
LLVMSetAtomicRMWBinOp()
LLVM_C_ABI void LLVMSetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst, LLVMAtomicRMWBinOp BinOp)
Definition at line 4140 of file Core.cpp.
References mapFromLLVMRMWBinOp(), and llvm::unwrap().
LLVMSetAtomicSingleThread()
LLVM_C_ABI void LLVMSetAtomicSingleThread (LLVMValueRef AtomicInst, LLVMBool SingleThread)
Definition at line 4448 of file Core.cpp.
References I, llvm::setAtomicSyncScopeID(), llvm::SyncScope::SingleThread, llvm::SyncScope::System, and llvm::unwrap().
LLVMSetAtomicSyncScopeID()
LLVM_C_ABI void LLVMSetAtomicSyncScopeID (LLVMValueRef AtomicInst, unsigned SSID)
Sets the synchronization scope ID of an atomic instruction.
Definition at line 4464 of file Core.cpp.
References assert(), I, llvm::setAtomicSyncScopeID(), and llvm::unwrap().
LLVMSetCleanup()
LLVM_C_ABI void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
Definition at line 3551 of file Core.cpp.
References llvm::unwrap().
LLVMSetCmpXchgFailureOrdering()
LLVM_C_ABI void LLVMSetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Definition at line 4488 of file Core.cpp.
References llvm::cast(), mapFromLLVMOrdering(), P, and llvm::unwrap().
LLVMSetCmpXchgSuccessOrdering()
LLVM_C_ABI void LLVMSetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Definition at line 4475 of file Core.cpp.
References llvm::cast(), mapFromLLVMOrdering(), P, and llvm::unwrap().
LLVMSetCurrentDebugLocation()
LLVM_C_ABI void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
Deprecated: Passing the NULL location will crash.
Use LLVMGetCurrentDebugLocation2 instead.
Definition at line 3353 of file Core.cpp.
References llvm::cast(), llvm::dwarf_linker::DebugLoc, and llvm::unwrap().
LLVMSetCurrentDebugLocation2()
LLVM_C_ABI void LLVMSetCurrentDebugLocation2 (LLVMBuilderRef Builder, LLVMMetadataRef Loc)
Set location information used by debugging information.
To clear the location metadata of the given instruction, pass NULL to Loc.
See also
llvm::IRBuilder::SetCurrentDebugLocation()
Definition at line 3346 of file Core.cpp.
References llvm::dwarf_linker::DebugLoc, and llvm::unwrap().
LLVMSetExact()
LLVM_C_ABI void LLVMSetExact (LLVMValueRef DivOrShrInst, LLVMBool IsExact)
Definition at line 3810 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMSetFastMathFlags()
LLVM_C_ABI void LLVMSetFastMathFlags (LLVMValueRef FPMathInst, LLVMFastMathFlags FMF)
Sets the flags for which fast-math-style optimizations are allowed for this value.
Only valid on floating point instructions.
See also
LLVMCanValueUseFastMathFlags
Definition at line 3831 of file Core.cpp.
References llvm::cast(), mapFromLLVMFastMathFlags(), P, and llvm::unwrap().
LLVMSetInstDebugLocation()
LLVM_C_ABI void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
Attempts to set the debug location for the given instruction using the current debug location for the given builder.
If the builder has no current debug location, this function is a no-op.
Deprecated
LLVMSetInstDebugLocation is deprecated in favor of the more general LLVMAddMetadataToInst.
See also
llvm::IRBuilder::SetInstDebugLocation()
Definition at line 3365 of file Core.cpp.
References llvm::unwrap().
LLVMSetIsDisjoint()
LLVM_C_ABI void LLVMSetIsDisjoint (LLVMValueRef Inst, LLVMBool IsDisjoint)
Sets the disjoint flag for the instruction.
Only valid for or instructions.
Definition at line 3846 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMSetNNeg()
LLVM_C_ABI void LLVMSetNNeg (LLVMValueRef NonNegInst, LLVMBool IsNonNeg)
Sets the non-negative flag for the instruction.
Only valid for zext instructions.
Definition at line 3820 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMSetNSW()
LLVM_C_ABI void LLVMSetNSW (LLVMValueRef ArithInst, LLVMBool HasNSW)
Definition at line 3800 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMSetNUW()
LLVM_C_ABI void LLVMSetNUW (LLVMValueRef ArithInst, LLVMBool HasNUW)
Definition at line 3790 of file Core.cpp.
References llvm::cast(), P, and llvm::unwrap().
LLVMSetOrdering()
LLVM_C_ABI void LLVMSetOrdering (LLVMValueRef MemoryAccessInst, LLVMAtomicOrdering Ordering)
Definition at line 4123 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), mapFromLLVMOrdering(), P, and llvm::unwrap().
LLVMSetParentCatchSwitch()
LLVM_C_ABI void LLVMSetParentCatchSwitch (LLVMValueRef CatchPad, LLVMValueRef CatchSwitch)
Set the parent catchswitch instruction of a catchpad instruction.
This only works on llvm::CatchPadInst instructions.
See also
llvm::CatchPadInst::setCatchSwitch()
Definition at line 3573 of file Core.cpp.
References llvm::unwrap().
LLVMSetVolatile()
LLVM_C_ABI void LLVMSetVolatile (LLVMValueRef MemoryAccessInst, LLVMBool IsVolatile)
Definition at line 4090 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), P, and llvm::unwrap().
LLVMSetWeak()
LLVM_C_ABI void LLVMSetWeak (LLVMValueRef CmpXchgInst, LLVMBool IsWeak)
Definition at line 4105 of file Core.cpp.
References llvm::unwrap().