LLVM: InsertValue
InsertValue
LLVM-C: C interface to LLVM » Core » Instructions
Functions in this group only apply to instructions that map to llvm::ExtractValue and llvm::InsertValue instances.
Functions
LLVM_C_ABI unsigned LLVMGetNumIndices (LLVMValueRef Inst)
Obtain the number of indices.
LLVM_C_ABI const unsigned * LLVMGetIndices (LLVMValueRef Inst)
Obtain the indices as an array.
Detailed Description
Functions in this group only apply to instructions that map to llvm::ExtractValue and llvm::InsertValue instances.
Function Documentation
LLVMGetIndices()
LLVM_C_ABI const unsigned * LLVMGetIndices (LLVMValueRef Inst)
Obtain the indices as an array.
Definition at line 3262 of file Core.cpp.
References llvm::dyn_cast(), I, IV, llvm_unreachable, and llvm::unwrap().
LLVMGetNumIndices()
LLVM_C_ABI unsigned LLVMGetNumIndices (LLVMValueRef Inst)
Obtain the number of indices.
NB: This also works on GEP operators.
Definition at line 3250 of file Core.cpp.
References llvm::dyn_cast(), GEP, I, IV, llvm_unreachable, and llvm::unwrap().