LLVM: Operand Bundles
Operand Bundles
LLVM-C: C interface to LLVM » Core
Functions in this group operate on LLVMOperandBundleRef instances that correspond to llvm::OperandBundleDef instances.
Functions
LLVM_C_ABI LLVMOperandBundleRef LLVMCreateOperandBundle (const char *Tag, size_t TagLen, LLVMValueRef *Args, unsigned NumArgs)
Create a new operand bundle.
LLVM_C_ABI void LLVMDisposeOperandBundle (LLVMOperandBundleRef Bundle)
Destroy an operand bundle.
LLVM_C_ABI const char * LLVMGetOperandBundleTag (LLVMOperandBundleRef Bundle, size_t *Len)
Obtain the tag of an operand bundle as a string.
LLVM_C_ABI unsigned LLVMGetNumOperandBundleArgs (LLVMOperandBundleRef Bundle)
Obtain the number of operands for an operand bundle.
LLVM_C_ABI LLVMValueRef LLVMGetOperandBundleArgAtIndex (LLVMOperandBundleRef Bundle, unsigned Index)
Obtain the operand for an operand bundle at the given index.
Detailed Description
Functions in this group operate on LLVMOperandBundleRef instances that correspond to llvm::OperandBundleDef instances.
See also
llvm::OperandBundleDef
Function Documentation
LLVMCreateOperandBundle()
LLVM_C_ABI LLVMOperandBundleRef LLVMCreateOperandBundle (const char * Tag, size_t TagLen, LLVMValueRef * Args, unsigned NumArgs)
Create a new operand bundle.
Every invocation should be paired with LLVMDisposeOperandBundle() or memory will be leaked.
Parameters
Tag Tag name of the operand bundle
TagLen Length of Tag
Args Memory address of an array of bundle operands
NumArgs Length of Args
Definition at line 2744 of file Core.cpp.
References llvm::ArrayRef(), llvm::unwrap(), and llvm::wrap().
LLVMDisposeOperandBundle()
LLVM_C_ABI void LLVMDisposeOperandBundle (LLVMOperandBundleRef Bundle)
Destroy an operand bundle.
This must be called for every created operand bundle or memory will be leaked.
Definition at line 2751 of file Core.cpp.
References llvm::unwrap().
LLVMGetNumOperandBundleArgs()
LLVM_C_ABI unsigned LLVMGetNumOperandBundleArgs (LLVMOperandBundleRef Bundle)
Obtain the number of operands for an operand bundle.
Parameters
Bundle Operand bundle to obtain operand count of.
Returns
The number of operands.
See also
OperandBundleDef::input_size()
Definition at line 2761 of file Core.cpp.
References llvm::unwrap().
LLVMGetOperandBundleArgAtIndex()
LLVM_C_ABI LLVMValueRef LLVMGetOperandBundleArgAtIndex (LLVMOperandBundleRef Bundle, unsigned Index)
Obtain the operand for an operand bundle at the given index.
Parameters
Bundle Operand bundle to obtain operand of.
Index An operand index, must be less than LLVMGetNumOperandBundleArgs().
Returns
The operand.
Definition at line 2765 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetOperandBundleTag()
LLVM_C_ABI const char * LLVMGetOperandBundleTag (LLVMOperandBundleRef Bundle, size_t * Len)
Obtain the tag of an operand bundle as a string.
Parameters
Bundle Operand bundle to obtain tag of.
Len Out parameter which holds the length of the returned string.
Returns
The tag name of Bundle.
See also
OperandBundleDef::getTag()
Definition at line 2755 of file Core.cpp.
References llvm::unwrap().