LLVM: Dwarf constants parsing functions
Dwarf constants parsing functions
These functions map their strings back to the corresponding enumeration value or return 0 if there is none, except for these exceptions:
Functions
LLVM_ABI unsigned llvm::dwarf::getTag (StringRef TagString)
LLVM_ABI unsigned llvm::dwarf::getOperationEncoding (StringRef OperationEncodingString)
LLVM_ABI unsigned llvm::dwarf::getSubOperationEncoding (unsigned OpEncoding, StringRef SubOperationEncodingString)
LLVM_ABI unsigned llvm::dwarf::getVirtuality (StringRef VirtualityString)
LLVM_ABI unsigned llvm::dwarf::getEnumKind (StringRef EnumKindString)
LLVM_ABI unsigned llvm::dwarf::getLanguage (StringRef LanguageString)
LLVM_ABI unsigned llvm::dwarf::getCallingConvention (StringRef LanguageString)
LLVM_ABI unsigned llvm::dwarf::getAttributeEncoding (StringRef EncodingString)
LLVM_ABI unsigned llvm::dwarf::getMacinfo (StringRef MacinfoString)
LLVM_ABI unsigned llvm::dwarf::getMacro (StringRef MacroString)
Detailed Description
These functions map their strings back to the corresponding enumeration value or return 0 if there is none, except for these exceptions:
getTag() returns DW_TAG_invalid on invalid input.
getVirtuality() returns DW_VIRTUALITY_invalid on invalid input.
getMacinfo() returns DW_MACINFO_invalid on invalid input.
Function Documentation
getAttributeEncoding()
unsigned llvm::dwarf::getAttributeEncoding (StringRef EncodingString)
Definition at line 274 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by llvm::LLParser::parseMDField().
getCallingConvention()
unsigned llvm::dwarf::getCallingConvention (StringRef LanguageString)
Definition at line 500 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by llvm::LLParser::parseMDField().
getEnumKind()
unsigned llvm::dwarf::getEnumKind (StringRef EnumKindString)
Definition at line 404 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), DW_APPLE_ENUM_KIND_invalid, and EnumKindString().
Referenced by llvm::LLParser::parseMDField().
getLanguage()
unsigned llvm::dwarf::getLanguage (StringRef LanguageString)
Definition at line 423 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), and LanguageString().
Referenced by llvm::LLParser::parseMDField().
getMacinfo()
unsigned llvm::dwarf::getMacinfo (StringRef MacinfoString)
Definition at line 572 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), DW_MACINFO_define, DW_MACINFO_end_file, DW_MACINFO_invalid, DW_MACINFO_start_file, DW_MACINFO_undef, DW_MACINFO_vendor_ext, and MacinfoString().
Referenced by llvm::LLParser::parseMDField().
getMacro()
unsigned llvm::dwarf::getMacro (StringRef MacroString)
Definition at line 604 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), DW_MACINFO_invalid, and MacroString().
getOperationEncoding()
unsigned llvm::dwarf::getOperationEncoding (StringRef OperationEncodingString)
Definition at line 165 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), DW_OP_LLVM_arg, DW_OP_LLVM_convert, DW_OP_LLVM_entry_value, DW_OP_LLVM_extract_bits_sext, DW_OP_LLVM_extract_bits_zext, DW_OP_LLVM_fragment, DW_OP_LLVM_implicit_pointer, DW_OP_LLVM_tag_offset, and OperationEncodingString().
getSubOperationEncoding()
unsigned llvm::dwarf::getSubOperationEncoding (unsigned OpEncoding, StringRef SubOperationEncodingString)
Definition at line 209 of file Dwarf.cpp.
References assert(), getLlvmUserOperationEncoding(), and SubOperationEncodingString().
getTag()
unsigned llvm::dwarf::getTag (StringRef TagString)
Definition at line 32 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), DW_TAG_invalid, and TagString().
Referenced by llvm::DWARFUnit::getLastChildEntry(), and llvm::LLParser::parseMDField().
getVirtuality()
unsigned llvm::dwarf::getVirtuality (StringRef VirtualityString)
Definition at line 385 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), DW_VIRTUALITY_invalid, and VirtualityString().
Referenced by llvm::LLParser::parseMDField().