LLVM: Bit Writer
Bit Writer
LLVM-C: C interface to LLVM
Functions
LLVM_C_ABI int LLVMWriteBitcodeToFile (LLVMModuleRef M, const char *Path)
Writes a module to the specified path.
LLVM_C_ABI int LLVMWriteBitcodeToFD (LLVMModuleRef M, int FD, int ShouldClose, int Unbuffered)
Writes a module to an open file descriptor.
LLVM_C_ABI int LLVMWriteBitcodeToFileHandle (LLVMModuleRef M, int Handle)
Deprecated for LLVMWriteBitcodeToFD.
LLVM_C_ABI LLVMMemoryBufferRef LLVMWriteBitcodeToMemoryBuffer (LLVMModuleRef M)
Writes a module to a new memory buffer and returns it.
Detailed Description
Function Documentation
LLVMWriteBitcodeToFD()
LLVM_C_ABI int LLVMWriteBitcodeToFD (LLVMModuleRef M, int FD, int ShouldClose, int Unbuffered)
Writes a module to an open file descriptor.
Returns 0 on success.
Definition at line 31 of file BitWriter.cpp.
References llvm::unwrap(), and llvm::WriteBitcodeToFile().
Referenced by LLVMWriteBitcodeToFileHandle().
LLVMWriteBitcodeToFile()
LLVM_C_ABI int LLVMWriteBitcodeToFile (LLVMModuleRef M, const char * Path)
Writes a module to the specified path.
Returns 0 on success.
Definition at line 20 of file BitWriter.cpp.
References llvm::sys::fs::OF_None, llvm::unwrap(), and llvm::WriteBitcodeToFile().
LLVMWriteBitcodeToFileHandle()
LLVM_C_ABI int LLVMWriteBitcodeToFileHandle (LLVMModuleRef M, int Handle)
Deprecated for LLVMWriteBitcodeToFD.
Writes a module to an open file descriptor. Returns 0 on success. Closes the Handle.
Definition at line 39 of file BitWriter.cpp.
References LLVMWriteBitcodeToFD().
LLVMWriteBitcodeToMemoryBuffer()
LLVM_C_ABI LLVMMemoryBufferRef LLVMWriteBitcodeToMemoryBuffer (LLVMModuleRef M)
Writes a module to a new memory buffer and returns it.
Definition at line 43 of file BitWriter.cpp.
References llvm::Data, llvm::MemoryBuffer::getMemBufferCopy(), llvm::raw_string_ostream::str(), llvm::unwrap(), llvm::wrap(), and llvm::WriteBitcodeToFile().