LLVM: lib/Support/InitLLVM.cpp File Reference
InitLLVM.cpp File Reference
#include "llvm/Support/InitLLVM.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/AutoConvert.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Signals.h"
Macros
#define STDIN_FILENO 0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2
Functions
void CleanupStdHandles (void *Cookie)
Macro Definition Documentation
STDERR_FILENO
#define STDERR_FILENO 2
Definition at line 31 of file InitLLVM.cpp.
Referenced by CleanupStdHandles(), llvm::errs(), llvm::InitLLVM::InitLLVM(), and llvm::raw_fd_ostream::raw_fd_ostream().
STDIN_FILENO
#define STDIN_FILENO 0
Definition at line 25 of file InitLLVM.cpp.
Referenced by CleanupStdHandles().
STDOUT_FILENO
#define STDOUT_FILENO 1
Definition at line 28 of file InitLLVM.cpp.
Referenced by CleanupStdHandles(), getFD(), llvm::InitLLVM::InitLLVM(), and llvm::outs().
Function Documentation
CleanupStdHandles()
void CleanupStdHandles (void * Cookie)
Definition at line 35 of file InitLLVM.cpp.
References llvm::errs(), llvm::raw_ostream::flush(), llvm::outs(), STDERR_FILENO, STDIN_FILENO, and STDOUT_FILENO.
Referenced by llvm::InitLLVM::InitLLVM(), and llvm::InitLLVM::~InitLLVM().