LLVM: lib/IR/Instructions.cpp File Reference
Instructions.cpp File Reference
#include "llvm/IR/Instructions.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ProfDataUtils.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CheckedArithmetic.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/ModRef.h"
#include "llvm/Support/TypeSize.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <optional>
#include <vector>
Functions
static Value * getAISize (LLVMContext &Context, Value *Amt)
static Align computeAllocaDefaultAlign (Type *Ty, InsertPosition Pos)
static Align computeLoadStoreDefaultAlign (Type *Ty, InsertPosition Pos)
template<typename IndexTy>
static Type * getIndexedTypeInternal (Type *Ty, ArrayRef< IndexTy > IdxList)
static Value * createPlaceholderForShuffleVector (Value *V)
static bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts)
static bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts)
static bool isReplicationMaskWithParams (ArrayRef< int > Mask, int ReplicationFactor, int VF)
static int matchShuffleAsBitRotate (ArrayRef< int > Mask, int NumSubElts)
Try to lower a vector shuffle as a bit rotation.
static bool hasNonZeroFPOperands (const CmpInst *Cmp)
static bool isImpliedTrueByMatchingCmp (CmpPredicate Pred1, CmpPredicate Pred2)
static bool isImpliedFalseByMatchingCmp (CmpPredicate Pred1, CmpPredicate Pred2)
Variables
static cl::opt< bool > DisableI2pP2iOpt ("disable-i2p-p2i-opt", cl::init(false), cl::desc("Disables inttoptr/ptrtoint roundtrip optimization"))
Function Documentation
computeAllocaDefaultAlign()
Align computeAllocaDefaultAlign (Type * Ty, InsertPosition Pos) static
Definition at line 1259 of file Instructions.cpp.
References assert(), DL, llvm::InsertPosition::getBasicBlock(), llvm::BasicBlock::getDataLayout(), llvm::BasicBlock::getParent(), and llvm::InsertPosition::isValid().
Referenced by llvm::AllocaInst::AllocaInst().
computeLoadStoreDefaultAlign()
Align computeLoadStoreDefaultAlign (Type * Ty, InsertPosition Pos) static
Definition at line 1317 of file Instructions.cpp.
References assert(), DL, llvm::InsertPosition::getBasicBlock(), llvm::BasicBlock::getDataLayout(), llvm::BasicBlock::getParent(), and llvm::InsertPosition::isValid().
Referenced by llvm::LoadInst::LoadInst(), and llvm::StoreInst::StoreInst().
createPlaceholderForShuffleVector()
Value * createPlaceholderForShuffleVector (Value * V) static
Definition at line 1720 of file Instructions.cpp.
References assert(), and llvm::PoisonValue::get().
Referenced by llvm::ShuffleVectorInst::ShuffleVectorInst(), and llvm::ShuffleVectorInst::ShuffleVectorInst().
getAISize()
Value * getAISize (LLVMContext & Context, Value * Amt) static
Definition at line 1247 of file Instructions.cpp.
References assert(), llvm::Type::getInt32Ty(), llvm::Value::getType(), llvm::isa(), and llvm::Type::isIntegerTy().
Referenced by llvm::AllocaInst::AllocaInst().
getIndexedTypeInternal()
template<typename IndexTy> Type * getIndexedTypeInternal (Type * Ty, ArrayRef< IndexTy > IdxList) static
Definition at line 1572 of file Instructions.cpp.
References llvm::ArrayRef< T >::empty(), llvm::GetElementPtrInst::getTypeAtIndex(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::GetElementPtrInst::getIndexedType(), llvm::GetElementPtrInst::getIndexedType(), and llvm::GetElementPtrInst::getIndexedType().
hasNonZeroFPOperands()
bool hasNonZeroFPOperands (const CmpInst * Cmp) static
Definition at line 3549 of file Instructions.cpp.
References llvm::dyn_cast(), LHS, llvm::PatternMatch::m_NonZeroNotDenormalFP(), llvm::PatternMatch::match(), and RHS.
Referenced by llvm::CmpInst::isEquivalence().
isIdentityMaskImpl()
bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 1935 of file Instructions.cpp.
References isSingleSourceMaskImpl().
Referenced by llvm::ShuffleVectorInst::isConcat(), llvm::ShuffleVectorInst::isIdentityMask(), llvm::ShuffleVectorInst::isIdentityWithExtract(), llvm::ShuffleVectorInst::isIdentityWithPadding(), and llvm::ShuffleVectorInst::isInsertSubvectorMask().
isImpliedFalseByMatchingCmp()
bool isImpliedFalseByMatchingCmp (CmpPredicate Pred1, CmpPredicate Pred2) static
Definition at line 3982 of file Instructions.cpp.
References llvm::ICmpInst::getInverseCmpPredicate(), and isImpliedTrueByMatchingCmp().
Referenced by llvm::ICmpInst::isImpliedByMatchingCmp().
isImpliedTrueByMatchingCmp()
bool isImpliedTrueByMatchingCmp (CmpPredicate Pred1, CmpPredicate Pred2) static
Definition at line 3952 of file Instructions.cpp.
References llvm::ICmpInst::getFlippedSignednessPredicate(), llvm::CmpPredicate::getMatching(), llvm::CmpPredicate::hasSameSign(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm::CmpInst::isSigned().
Referenced by llvm::ICmpInst::isImpliedByMatchingCmp(), and isImpliedFalseByMatchingCmp().
isReplicationMaskWithParams()
bool isReplicationMaskWithParams (ArrayRef< int > Mask, int ReplicationFactor, int VF) static
Definition at line 2236 of file Instructions.cpp.
References llvm::all_of(), assert(), llvm::PoisonMaskElem, llvm::seq(), and llvm::ArrayRef< T >::size().
Referenced by llvm::ShuffleVectorInst::isReplicationMask(), and llvm::ShuffleVectorInst::isReplicationMask().
isSingleSourceMaskImpl()
bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 1911 of file Instructions.cpp.
References assert(), and I.
Referenced by llvm::ShuffleVectorInst::isExtractSubvectorMask(), isIdentityMaskImpl(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), and llvm::ShuffleVectorInst::isSingleSourceMask().
matchShuffleAsBitRotate()
int matchShuffleAsBitRotate (ArrayRef< int > Mask, int NumSubElts) static
Try to lower a vector shuffle as a bit rotation.
Look for a repeated rotation pattern in each sub group. Returns an element-wise left bit rotation amount or -1 if failed.
Definition at line 2469 of file Instructions.cpp.
References assert(), and llvm::Offset.
Referenced by llvm::ShuffleVectorInst::isBitRotateMask(), lowerShuffleAsBitRotate(), and matchUnaryPermuteShuffle().
Variable Documentation
DisableI2pP2iOpt
cl::opt< bool > DisableI2pP2iOpt("disable-i2p-p2i-opt", cl::init(false), cl::desc("Disables inttoptr/ptrtoint roundtrip optimization")) ("disable-i2p-p2i-opt" , cl::init(false) , cl::desc("Disables inttoptr/ptrtoint roundtrip optimization")) static
Referenced by llvm::CastInst::isEliminableCastPair().