LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderGDB.h File Reference
JITLoaderGDB.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
#include "llvm/Support/Compiler.h"
#include <cstdint>
Classes
struct jit_code_entry
struct jit_descriptor
Enumerations
enum jit_actions_t { JIT_NOACTION = 0 , JIT_REGISTER_FN , JIT_UNREGISTER_FN }
Functions
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char *ArgData, size_t ArgSize)
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char *ArgData, size_t ArgSize)
Enumeration Type Documentation
jit_actions_t
enum jit_actions_t
Enumerator
JIT_NOACTION
JIT_REGISTER_FN
JIT_UNREGISTER_FN
Definition at line 23 of file JITLoaderGDB.h.
Function Documentation
llvm_orc_registerJITLoaderGDBAllocAction()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char * ArgData, size_t ArgSize)
Definition at line 77 of file JITLoaderGDB.cpp.
References __jit_debug_register_code(), appendJITDebugDescriptor(), llvm::release, and llvm::Error::success().
llvm_orc_registerJITLoaderGDBWrapper()
LLVM_ABI llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char * ArgData, size_t ArgSize)
Definition at line 93 of file JITLoaderGDB.cpp.
References __jit_debug_register_code(), appendJITDebugDescriptor(), llvm::release, and llvm::Error::success().