LLVM: lib/Analysis/KernelInfo.cpp File Reference
KernelInfo.cpp File Reference
#include "llvm/Analysis/KernelInfo.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
Macros
#define DEBUG_TYPE "kernel-info"
#define REMARK_PROPERTY(PROP_NAME)
Functions
static void identifyCallee (OptimizationRemark &R, const Module *M, const Value *V, StringRef Kind="")
static void identifyFunction (OptimizationRemark &R, const Function &F)
static void remarkAlloca (OptimizationRemarkEmitter &ORE, const Function &Caller, const AllocaInst &Alloca, TypeSize::ScalarTy StaticSize)
static void remarkCall (OptimizationRemarkEmitter &ORE, const Function &Caller, const CallBase &Call, StringRef CallKind, StringRef RemarkKind)
static void remarkFlatAddrspaceAccess (OptimizationRemarkEmitter &ORE, const Function &Caller, const Instruction &Inst)
static void remarkProperty (OptimizationRemarkEmitter &ORE, const Function &F, StringRef Name, int64_t Value)
static std::optional< int64_t > parseFnAttrAsInteger (Function &F, StringRef Name)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "kernel-info"
Definition at line 28 of file KernelInfo.cpp.
REMARK_PROPERTY
#define REMARK_PROPERTY (PROP_NAME)
Value:
  remarkProperty(ORE, F, #PROP_NAME, KI.PROP_NAME)
Function Documentation
identifyCallee()
void identifyCallee (OptimizationRemark & R, const Module * M, const Value * V, StringRef Kind = "") static
Definition at line 80 of file KernelInfo.cpp.
References llvm::dyn_cast(), and F.
Referenced by identifyFunction(), and remarkCall().
identifyFunction()
void identifyFunction (OptimizationRemark & R, const Function & F) static
Definition at line 99 of file KernelInfo.cpp.
References F, and identifyCallee().
Referenced by remarkAlloca(), remarkCall(), remarkFlatAddrspaceAccess(), and remarkProperty().
parseFnAttrAsInteger()
std::optional< int64_t > parseFnAttrAsInteger (Function & F, StringRef Name) static
Definition at line 276 of file KernelInfo.cpp.
References F.
remarkAlloca()
void remarkAlloca (OptimizationRemarkEmitter & ORE, const Function & Caller, const AllocaInst & Alloca, TypeSize::ScalarTy StaticSize) static
Definition at line 103 of file KernelInfo.cpp.
References DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), llvm::StringRef::empty(), llvm::findDVRDeclares(), llvm::DbgRecord::getDebugLoc(), llvm::DIVariable::getName(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::DbgVariableRecord::getVariable(), identifyFunction(), llvm::itostr(), llvm::Value::printAsOperand(), and llvm::DbgVariableRecord::Variable.
remarkCall()
void remarkCall (OptimizationRemarkEmitter & ORE, const Function & Caller, const CallBase & Call, StringRef CallKind, StringRef RemarkKind) static
Definition at line 141 of file KernelInfo.cpp.
References Call, DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), identifyCallee(), and identifyFunction().
remarkFlatAddrspaceAccess()
void remarkFlatAddrspaceAccess (OptimizationRemarkEmitter & ORE, const Function & Caller, const Instruction & Inst) static
Definition at line 154 of file KernelInfo.cpp.
References DEBUG_TYPE, llvm::dyn_cast(), llvm::OptimizationRemarkEmitter::emit(), llvm::Instruction::getOpcodeName(), llvm::Value::getType(), identifyFunction(), II, llvm::Type::isVoidTy(), and llvm::Value::printAsOperand().
remarkProperty()
void remarkProperty (OptimizationRemarkEmitter & ORE, const Function & F, StringRef Name, int64_t Value) static
Definition at line 265 of file KernelInfo.cpp.
References DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), F, identifyFunction(), and llvm::itostr().