LLVM: lib/Support/KnownBits.cpp File Reference
KnownBits.cpp File Reference
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Functions
static KnownBits computeForAddCarry (const KnownBits &LHS, const KnownBits &RHS, bool CarryZero, bool CarryOne)
static unsigned getMaxShiftAmount (const APInt &MaxValue, unsigned BitWidth)
static KnownBits computeForSatAddSub (bool Add, bool Signed, const KnownBits &LHS, const KnownBits &RHS)
static KnownBits avgComputeU (KnownBits LHS, KnownBits RHS, bool IsCeil)
static KnownBits divComputeLowBit (KnownBits Known, const KnownBits &LHS, const KnownBits &RHS, bool Exact)
Function Documentation
avgComputeU()
KnownBits avgComputeU (KnownBits LHS, KnownBits RHS, bool IsCeil) static
Definition at line 778 of file KnownBits.cpp.
References llvm::BitWidth, computeForAddCarry(), LHS, and RHS.
Referenced by llvm::KnownBits::avgCeilU(), and llvm::KnownBits::avgFloorU().
computeForAddCarry()
KnownBits computeForAddCarry (const KnownBits & LHS, const KnownBits & RHS, bool CarryZero, bool CarryOne) static
Definition at line 30 of file KnownBits.cpp.
References LHS, llvm::move(), llvm::KnownBits::One, RHS, and llvm::KnownBits::Zero.
Referenced by avgComputeU().
computeForSatAddSub()
KnownBits computeForSatAddSub (bool Add, bool Signed, const KnownBits & LHS, const KnownBits & RHS) static
Definition at line 608 of file KnownBits.cpp.
References llvm::Add, assert(), llvm::BitWidth, llvm::CallingConv::C, llvm::APInt::clearAllBits(), llvm::APInt::clearLowBits(), llvm::APInt::clearSignBit(), llvm::KnownBits::computeForAddSub(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), LHS, llvm::KnownBits::One, RHS, llvm::APInt::setSignBit(), Signed, and llvm::KnownBits::Zero.
Referenced by llvm::KnownBits::sadd_sat(), llvm::KnownBits::ssub_sat(), llvm::KnownBits::uadd_sat(), and llvm::KnownBits::usub_sat().
divComputeLowBit()
KnownBits divComputeLowBit (KnownBits Known, const KnownBits & LHS, const KnownBits & RHS, bool Exact) static
Definition at line 917 of file KnownBits.cpp.
References llvm::KnownBits::hasConflict(), LHS, llvm::KnownBits::One, RHS, llvm::KnownBits::setAllZero(), llvm::APInt::setBit(), llvm::APInt::setLowBits(), and llvm::KnownBits::Zero.
Referenced by llvm::KnownBits::sdiv(), and llvm::KnownBits::udiv().
getMaxShiftAmount()
unsigned getMaxShiftAmount (const APInt & MaxValue, unsigned BitWidth) static
Definition at line 278 of file KnownBits.cpp.
References llvm::BitWidth, llvm::APInt::extractBitsAsZExtValue(), llvm::APInt::getLimitedValue(), llvm::isPowerOf2_32(), and llvm::Log2_32().
Referenced by llvm::KnownBits::ashr(), llvm::KnownBits::lshr(), and llvm::KnownBits::shl().