LLVM: lib/AsmParser/LLParser.cpp File Reference
LLParser.cpp File Reference
#include "llvm/AsmParser/LLParser.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/AsmParser/LLToken.h"
#include "llvm/AsmParser/SlotMapping.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/ConstantRangeList.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/ModRef.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstring>
#include <optional>
#include <vector>
#include "llvm/IR/Attributes.inc"
#include "llvm/IR/Metadata.def"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define GET_ATTR_NAMES
#define ATTRIBUTE_ENUM(ENUM_NAME, DISPLAY_NAME)
#define CC_VLS_CASE(ABIVlen)
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS)
#define DECLARE_FIELD(NAME, TYPE, INIT)
#define NOP_FIELD(NAME, TYPE, INIT)
#define REQUIRE_FIELD(NAME, TYPE, INIT)
#define PARSE_MD_FIELD(NAME, TYPE, DEFAULT)
#define PARSE_MD_FIELDS()
#define GET_OR_DISTINCT(CLASS, ARGS)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
#define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)
Functions
static std::string getTypeString (Type *T)
static void dropIntrinsicWithUnknownMetadataArgument (IntrinsicInst *II)
static bool isValidVisibilityForLinkage (unsigned V, unsigned L)
static bool isValidDLLStorageClassForLinkage (unsigned S, unsigned L)
static void maybeSetDSOLocal (bool DSOLocal, GlobalValue &GV)
static bool isSanitizer (lltok::Kind Kind)
static Attribute::AttrKind tokenToAttribute (lltok::Kind Kind)
static bool upgradeMemoryAttr (MemoryEffects &ME, lltok::Kind Kind)
static GlobalValue * createGlobalFwdRef (Module *M, PointerType *PTy)
static unsigned parseOptionalLinkageAux (lltok::Kind Kind, bool &HasLinkage)
static std::optional< MemoryEffects::Location > keywordToLoc (lltok::Kind Tok)
static std::optional< ModRefInfo > keywordToModRef (lltok::Kind Tok)
static unsigned keywordToFPClassTest (lltok::Kind Tok)
bool isOldDbgFormatIntrinsic (StringRef Name)
static void resolveFwdRef (ValueInfo *Fwd, ValueInfo &Resolved)
Variables
static cl::opt< bool > AllowIncompleteIR ("allow-incomplete-ir", cl::init(false), cl::Hidden, cl::desc("Allow incomplete IR on a best effort basis (references to unknown " "metadata will be dropped)"))
static ValueInfo EmptyVI
static const auto FwdVIRef = (GlobalValueSummaryMapTy::value_type *)-8
Macro Definition Documentation
ATTRIBUTE_ENUM
#define ATTRIBUTE_ENUM (ENUM_NAME, DISPLAY_NAME)
Value:
  case lltok::kw_##DISPLAY_NAME: \
    return Attribute::ENUM_NAME;
CC_VLS_CASE
#define CC_VLS_CASE (ABIVlen)
Value:
  case ABIVlen:                                                                \
    CC = CallingConv::RISCV_VLSCall_##ABIVlen;                                 \
    break;
Referenced by llvm::RISCVTargetLowering::LowerFormalArguments().
DECLARE_FIELD
#define DECLARE_FIELD (NAME, TYPE, INIT)
Value:
TYPE NAME INIT
Definition at line 5343 of file LLParser.cpp.
GET_ATTR_NAMES
#define GET_ATTR_NAMES
GET_OR_DISTINCT
#define GET_OR_DISTINCT (CLASS, ARGS)
Value:
  (IsDistinct ? CLASS::getDistinct ARGS : CLASS::get ARGS)
Definition at line 5365 of file LLParser.cpp.
HANDLE_SPECIALIZED_MDNODE_LEAF
#define HANDLE_SPECIALIZED_MDNODE_LEAF (CLASS)
Value:
  if (Lex.getStrVal() == #CLASS)                                               \
    return parse##CLASS(N, IsDistinct);
NOP_FIELD
#define NOP_FIELD (NAME, TYPE, INIT)
Definition at line 5344 of file LLParser.cpp.
PARSE_MD_FIELD
#define PARSE_MD_FIELD (NAME, TYPE, DEFAULT)
Value:
  if (Lex.getStrVal() == #NAME)                                                \
    return parseMDField(#NAME, NAME);
Definition at line 5348 of file LLParser.cpp.
PARSE_MD_FIELDS
#define PARSE_MD_FIELDS ()
Value:
  VISIT_MD_FIELDS(DECLARE_FIELD, DECLARE_FIELD)                                \
  do {                                                                         \
    LocTy ClosingLoc;                                                          \
    if (parseMDFieldsImpl(                                                     \
            [&]() -> bool {                                                    \
              VISIT_MD_FIELDS(PARSE_MD_FIELD, PARSE_MD_FIELD)                  \
              return tokError(Twine("invalid field '") + Lex.getStrVal() +     \
                              "'");                                            \
            },                                                                 \
            ClosingLoc))                                                       \
      return true;                                                             \
    VISIT_MD_FIELDS(NOP_FIELD, REQUIRE_FIELD)                                  \
  } while (false)
Definition at line 5351 of file LLParser.cpp.
REQUIRE_FIELD
#define REQUIRE_FIELD (NAME, TYPE, INIT)
Value:
  if (!NAME.Seen)                                                              \
    return error(ClosingLoc, "missing required field '" #NAME "'");
Definition at line 5345 of file LLParser.cpp.
VISIT_MD_FIELDS [1/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(column, ColumnField, );                                             \
  REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(inlinedAt, MDField, );                                              \
  OPTIONAL(isImplicitCode, MDBoolField, (false));                              \
  OPTIONAL(atomGroup, MDUnsignedField, (0, UINT64_MAX));                       \
  OPTIONAL(atomRank, MDUnsignedField, (0, UINT8_MAX));
VISIT_MD_FIELDS [2/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(tag, DwarfTagField, );                                              \
  OPTIONAL(header, MDStringField, );                                           \
  OPTIONAL(operands, MDFieldList, );
VISIT_MD_FIELDS [3/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(scope, MDField, );                                                  \
  OPTIONAL(baseType, MDField, );                                               \
  OPTIONAL(size, MDUnsignedOrMDField, (0, UINT64_MAX));                        \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(lowerBound, MDSignedOrMDField, );                                   \
  OPTIONAL(upperBound, MDSignedOrMDField, );                                   \
  OPTIONAL(stride, MDSignedOrMDField, );                                       \
  OPTIONAL(bias, MDSignedOrMDField, );
VISIT_MD_FIELDS [4/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(count, MDSignedOrMDField, (-1, -1, INT64_MAX, false));              \
  OPTIONAL(lowerBound, MDSignedOrMDField, );                                   \
  OPTIONAL(upperBound, MDSignedOrMDField, );                                   \
  OPTIONAL(stride, MDSignedOrMDField, );
VISIT_MD_FIELDS [5/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(count, MDSignedOrMDField, );                                        \
  OPTIONAL(lowerBound, MDSignedOrMDField, );                                   \
  OPTIONAL(upperBound, MDSignedOrMDField, );                                   \
  OPTIONAL(stride, MDSignedOrMDField, );
VISIT_MD_FIELDS [6/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(name, MDStringField, );                                             \
  REQUIRED(value, MDAPSIntField, );                                            \
  OPTIONAL(isUnsigned, MDBoolField, (false));
VISIT_MD_FIELDS [7/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(tag, DwarfTagField, (dwarf::DW_TAG_base_type));                     \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(size, MDUnsignedOrMDField, (0, UINT64_MAX));                        \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(encoding, DwarfAttEncodingField, );                                 \
  OPTIONAL(num_extra_inhabitants, MDUnsignedField, (0, UINT32_MAX));           \
  OPTIONAL(flags, DIFlagField, );
VISIT_MD_FIELDS [8/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(tag, DwarfTagField, (dwarf::DW_TAG_base_type));                     \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(size, MDUnsignedOrMDField, (0, UINT64_MAX));                        \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(encoding, DwarfAttEncodingField, );                                 \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(kind, FixedPointKindField, );                                       \
  OPTIONAL(factor, MDSignedField, );                                           \
  OPTIONAL(numerator, MDAPSIntField, );                                        \
  OPTIONAL(denominator, MDAPSIntField, );
VISIT_MD_FIELDS [9/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(tag, DwarfTagField, (dwarf::DW_TAG_string_type));                   \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(stringLength, MDField, );                                           \
  OPTIONAL(stringLengthExpression, MDField, );                                 \
  OPTIONAL(stringLocationExpression, MDField, );                               \
  OPTIONAL(size, MDUnsignedOrMDField, (0, UINT64_MAX));                        \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(encoding, DwarfAttEncodingField, );
VISIT_MD_FIELDS [10/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(tag, DwarfTagField, );                                              \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(scope, MDField, );                                                  \
  REQUIRED(baseType, MDField, );                                               \
  OPTIONAL(size, MDUnsignedOrMDField, (0, UINT64_MAX));                        \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(offset, MDUnsignedOrMDField, (0, UINT64_MAX));                      \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(extraData, MDField, );                                              \
  OPTIONAL(dwarfAddressSpace, MDUnsignedField, (UINT32_MAX, UINT32_MAX));      \
  OPTIONAL(annotations, MDField, );                                            \
  OPTIONAL(ptrAuthKey, MDUnsignedField, (0, 7));                               \
  OPTIONAL(ptrAuthIsAddressDiscriminated, MDBoolField, );                      \
  OPTIONAL(ptrAuthExtraDiscriminator, MDUnsignedField, (0, 0xffff));           \
  OPTIONAL(ptrAuthIsaPointer, MDBoolField, );                                  \
  OPTIONAL(ptrAuthAuthenticatesNullValues, MDBoolField, );
VISIT_MD_FIELDS [11/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(tag, DwarfTagField, );                                              \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(scope, MDField, );                                                  \
  OPTIONAL(baseType, MDField, );                                               \
  OPTIONAL(size, MDUnsignedOrMDField, (0, UINT64_MAX));                        \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(offset, MDUnsignedOrMDField, (0, UINT64_MAX));                      \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(elements, MDField, );                                               \
  OPTIONAL(runtimeLang, DwarfLangField, );                                     \
  OPTIONAL(enumKind, DwarfEnumKindField, );                                    \
  OPTIONAL(vtableHolder, MDField, );                                           \
  OPTIONAL(templateParams, MDField, );                                         \
  OPTIONAL(identifier, MDStringField, );                                       \
  OPTIONAL(discriminator, MDField, );                                          \
  OPTIONAL(dataLocation, MDField, );                                           \
  OPTIONAL(associated, MDField, );                                             \
  OPTIONAL(allocated, MDField, );                                              \
  OPTIONAL(rank, MDSignedOrMDField, );                                         \
  OPTIONAL(annotations, MDField, );                                            \
  OPTIONAL(num_extra_inhabitants, MDUnsignedField, (0, UINT32_MAX));           \
  OPTIONAL(specification, MDField, );                                          \
  OPTIONAL(bitStride, MDField, );
VISIT_MD_FIELDS [12/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(cc, DwarfCCField, );                                                \
  REQUIRED(types, MDField, );
VISIT_MD_FIELDS [13/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(filename, MDStringField, );                                         \
  REQUIRED(directory, MDStringField, );                                        \
  OPTIONAL(checksumkind, ChecksumKindField, (DIFile::CSK_MD5));                \
  OPTIONAL(checksum, MDStringField, );                                         \
  OPTIONAL(source, MDStringField, );
VISIT_MD_FIELDS [14/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(language, DwarfLangField, );                                        \
  REQUIRED(file, MDField, (/* AllowNull */ false));                            \
  OPTIONAL(producer, MDStringField, );                                         \
  OPTIONAL(isOptimized, MDBoolField, );                                        \
  OPTIONAL(flags, MDStringField, );                                            \
  OPTIONAL(runtimeVersion, MDUnsignedField, (0, UINT32_MAX));                  \
  OPTIONAL(splitDebugFilename, MDStringField, );                               \
  OPTIONAL(emissionKind, EmissionKindField, );                                 \
  OPTIONAL(enums, MDField, );                                                  \
  OPTIONAL(retainedTypes, MDField, );                                          \
  OPTIONAL(globals, MDField, );                                                \
  OPTIONAL(imports, MDField, );                                                \
  OPTIONAL(macros, MDField, );                                                 \
  OPTIONAL(dwoId, MDUnsignedField, );                                          \
  OPTIONAL(splitDebugInlining, MDBoolField, = true);                           \
  OPTIONAL(debugInfoForProfiling, MDBoolField, = false);                       \
  OPTIONAL(nameTableKind, NameTableKindField, );                               \
  OPTIONAL(rangesBaseAddress, MDBoolField, = false);                           \
  OPTIONAL(sysroot, MDStringField, );                                          \
  OPTIONAL(sdk, MDStringField, );
VISIT_MD_FIELDS [15/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(scope, MDField, );                                                  \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(linkageName, MDStringField, );                                      \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(type, MDField, );                                                   \
  OPTIONAL(isLocal, MDBoolField, );                                            \
  OPTIONAL(isDefinition, MDBoolField, (true));                                 \
  OPTIONAL(scopeLine, LineField, );                                            \
  OPTIONAL(containingType, MDField, );                                         \
  OPTIONAL(virtuality, DwarfVirtualityField, );                                \
  OPTIONAL(virtualIndex, MDUnsignedField, (0, UINT32_MAX));                    \
  OPTIONAL(thisAdjustment, MDSignedField, (0, INT32_MIN, INT32_MAX));          \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(spFlags, DISPFlagField, );                                          \
  OPTIONAL(isOptimized, MDBoolField, );                                        \
  OPTIONAL(unit, MDField, );                                                   \
  OPTIONAL(templateParams, MDField, );                                         \
  OPTIONAL(declaration, MDField, );                                            \
  OPTIONAL(retainedNodes, MDField, );                                          \
  OPTIONAL(thrownTypes, MDField, );                                            \
  OPTIONAL(annotations, MDField, );                                            \
  OPTIONAL(targetFuncName, MDStringField, );                                   \
  OPTIONAL(keyInstructions, MDBoolField, );
VISIT_MD_FIELDS [16/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(column, ColumnField, );
VISIT_MD_FIELDS [17/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(file, MDField, );                                                   \
  REQUIRED(discriminator, MDUnsignedField, (0, UINT32_MAX));
VISIT_MD_FIELDS [18/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(scope, MDField, );                                                  \
  OPTIONAL(declaration, MDField, );                                            \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );
VISIT_MD_FIELDS [19/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(scope, MDField, );                                                  \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(exportSymbols, MDBoolField, );
VISIT_MD_FIELDS [20/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(type, DwarfMacinfoTypeField, );                                     \
  OPTIONAL(line, LineField, );                                                 \
  REQUIRED(name, MDStringField, );                                             \
  OPTIONAL(value, MDStringField, );
VISIT_MD_FIELDS [21/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(type, DwarfMacinfoTypeField, (dwarf::DW_MACINFO_start_file));       \
  OPTIONAL(line, LineField, );                                                 \
  REQUIRED(file, MDField, );                                                   \
  OPTIONAL(nodes, MDField, );
VISIT_MD_FIELDS [22/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(scope, MDField, );                                                  \
  REQUIRED(name, MDStringField, );                                             \
  OPTIONAL(configMacros, MDStringField, );                                     \
  OPTIONAL(includePath, MDStringField, );                                      \
  OPTIONAL(apinotes, MDStringField, );                                         \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(isDecl, MDBoolField, );
VISIT_MD_FIELDS [23/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(name, MDStringField, );                                             \
  REQUIRED(type, MDField, );                                                   \
  OPTIONAL(defaulted, MDBoolField, );
VISIT_MD_FIELDS [24/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(tag, DwarfTagField, (dwarf::DW_TAG_template_value_parameter));      \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(type, MDField, );                                                   \
  OPTIONAL(defaulted, MDBoolField, );                                          \
  REQUIRED(value, MDField, );
VISIT_MD_FIELDS [25/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(name, MDStringField, (/* AllowEmpty */ false));                     \
  OPTIONAL(scope, MDField, );                                                  \
  OPTIONAL(linkageName, MDStringField, );                                      \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(type, MDField, );                                                   \
  OPTIONAL(isLocal, MDBoolField, );                                            \
  OPTIONAL(isDefinition, MDBoolField, (true));                                 \
  OPTIONAL(templateParams, MDField, );                                         \
  OPTIONAL(declaration, MDField, );                                            \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(annotations, MDField, );
VISIT_MD_FIELDS [26/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(arg, MDUnsignedField, (0, UINT16_MAX));                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(type, MDField, );                                                   \
  OPTIONAL(flags, DIFlagField, );                                              \
  OPTIONAL(align, MDUnsignedField, (0, UINT32_MAX));                           \
  OPTIONAL(annotations, MDField, );
VISIT_MD_FIELDS [27/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(scope, MDField, (/* AllowNull */ false));                           \
  REQUIRED(name, MDStringField, );                                             \
  REQUIRED(file, MDField, );                                                   \
  REQUIRED(line, LineField, );                                                 \
  OPTIONAL(column, ColumnField, );                                             \
  OPTIONAL(isArtificial, MDBoolField, );                                       \
  OPTIONAL(coroSuspendIdx, MDUnsignedField, );
VISIT_MD_FIELDS [28/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(var, MDField, );                                                    \
  REQUIRED(expr, MDField, );
VISIT_MD_FIELDS [29/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(setter, MDStringField, );                                           \
  OPTIONAL(getter, MDStringField, );                                           \
  OPTIONAL(attributes, MDUnsignedField, (0, UINT32_MAX));                      \
  OPTIONAL(type, MDField, );
VISIT_MD_FIELDS [30/30]
#define VISIT_MD_FIELDS (OPTIONAL, REQUIRED)
Value:
  REQUIRED(tag, DwarfTagField, );                                              \
  REQUIRED(scope, MDField, );                                                  \
  OPTIONAL(entity, MDField, );                                                 \
  OPTIONAL(file, MDField, );                                                   \
  OPTIONAL(line, LineField, );                                                 \
  OPTIONAL(name, MDStringField, );                                             \
  OPTIONAL(elements, MDField, );
Function Documentation
createGlobalFwdRef()
GlobalValue * createGlobalFwdRef (Module * M, PointerType * PTy) inline static
Definition at line 1741 of file LLParser.cpp.
References llvm::GlobalValue::ExternalWeakLinkage, llvm::Type::getInt8Ty(), and llvm::GlobalValue::NotThreadLocal.
dropIntrinsicWithUnknownMetadataArgument()
void dropIntrinsicWithUnknownMetadataArgument (IntrinsicInst * II) static
Definition at line 151 of file LLParser.cpp.
References assert(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), II, llvm::isa(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getTypeString()
std::string getTypeString (Type * T) static
Definition at line 67 of file LLParser.cpp.
References llvm::raw_string_ostream::str(), and T.
Referenced by StackAccess::print().
isOldDbgFormatIntrinsic()
bool isOldDbgFormatIntrinsic (StringRef Name)
Definition at line 6595 of file LLParser.cpp.
References llvm::Intrinsic::lookupIntrinsicID().
isSanitizer()
bool isSanitizer (lltok::Kind Kind) static
Definition at line 1292 of file LLParser.cpp.
References llvm::lltok::kw_no_sanitize_address, llvm::lltok::kw_no_sanitize_hwaddress, and llvm::lltok::kw_sanitize_address_dyninit.
isValidDLLStorageClassForLinkage()
bool isValidDLLStorageClassForLinkage (unsigned S, unsigned L) static
Definition at line 1129 of file LLParser.cpp.
References llvm::GlobalValue::DefaultStorageClass, and llvm::GlobalValue::isLocalLinkage().
isValidVisibilityForLinkage()
bool isValidVisibilityForLinkage (unsigned V, unsigned L) static
Definition at line 1125 of file LLParser.cpp.
References llvm::GlobalValue::DefaultVisibility, and llvm::GlobalValue::isLocalLinkage().
keywordToFPClassTest()
unsigned keywordToFPClassTest (lltok::Kind Tok) static
Definition at line 2596 of file LLParser.cpp.
References llvm::fcAllFlags, llvm::fcInf, llvm::fcNan, llvm::fcNegInf, llvm::fcNegNormal, llvm::fcNegSubnormal, llvm::fcNegZero, llvm::fcNormal, llvm::fcPosInf, llvm::fcPosNormal, llvm::fcPosSubnormal, llvm::fcPosZero, llvm::fcQNan, llvm::fcSNan, llvm::fcSubnormal, llvm::fcZero, llvm::lltok::kw_all, llvm::lltok::kw_inf, llvm::lltok::kw_nan, llvm::lltok::kw_ninf, llvm::lltok::kw_nnorm, llvm::lltok::kw_norm, llvm::lltok::kw_nsub, llvm::lltok::kw_nzero, llvm::lltok::kw_pinf, llvm::lltok::kw_pnorm, llvm::lltok::kw_psub, llvm::lltok::kw_pzero, llvm::lltok::kw_qnan, llvm::lltok::kw_snan, llvm::lltok::kw_sub, and llvm::lltok::kw_zero.
keywordToLoc()
std::optional< MemoryEffects::Location > keywordToLoc (lltok::Kind Tok) static
Definition at line 2513 of file LLParser.cpp.
References llvm::ArgMem, llvm::ErrnoMem, llvm::InaccessibleMem, llvm::lltok::kw_argmem, llvm::lltok::kw_errnomem, and llvm::lltok::kw_inaccessiblemem.
keywordToModRef()
std::optional< ModRefInfo > keywordToModRef (lltok::Kind Tok) static
Definition at line 2526 of file LLParser.cpp.
References llvm::lltok::kw_none, llvm::lltok::kw_read, llvm::lltok::kw_readwrite, llvm::lltok::kw_write, llvm::Mod, llvm::ModRef, llvm::NoModRef, and llvm::Ref.
maybeSetDSOLocal()
void maybeSetDSOLocal (bool DSOLocal, GlobalValue & GV) static
Definition at line 1136 of file LLParser.cpp.
References llvm::GlobalValue::setDSOLocal().
parseOptionalLinkageAux()
unsigned parseOptionalLinkageAux (lltok::Kind Kind, bool & HasLinkage) static
Definition at line 2016 of file LLParser.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::lltok::kw_appending, llvm::lltok::kw_available_externally, llvm::lltok::kw_common, llvm::lltok::kw_extern_weak, llvm::lltok::kw_external, llvm::lltok::kw_internal, llvm::lltok::kw_linkonce, llvm::lltok::kw_linkonce_odr, llvm::lltok::kw_private, llvm::lltok::kw_weak, llvm::lltok::kw_weak_odr, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
resolveFwdRef()
void resolveFwdRef (ValueInfo * Fwd, ValueInfo & Resolved) static
Definition at line 9509 of file LLParser.cpp.
References assert(), llvm::ValueInfo::isReadOnly(), llvm::ValueInfo::isWriteOnly(), llvm::ValueInfo::setReadOnly(), and llvm::ValueInfo::setWriteOnly().
tokenToAttribute()
Attribute::AttrKind tokenToAttribute (lltok::Kind Kind) static
Definition at line 1524 of file LLParser.cpp.
References llvm::Attribute::None.
upgradeMemoryAttr()
bool upgradeMemoryAttr (MemoryEffects & ME, lltok::Kind Kind) static
Definition at line 1644 of file LLParser.cpp.
References llvm::MemoryEffectsBase< IRMemLocation >::argMemOnly(), llvm::MemoryEffectsBase< IRMemLocation >::inaccessibleMemOnly(), llvm::MemoryEffectsBase< IRMemLocation >::inaccessibleOrArgMemOnly(), llvm::lltok::kw_argmemonly, llvm::lltok::kw_inaccessiblemem_or_argmemonly, llvm::lltok::kw_inaccessiblememonly, llvm::MemoryEffectsBase< IRMemLocation >::none(), llvm::MemoryEffectsBase< IRMemLocation >::readOnly(), and llvm::MemoryEffectsBase< IRMemLocation >::writeOnly().
Variable Documentation
AllowIncompleteIR
cl::opt< bool > AllowIncompleteIR("allow-incomplete-ir", cl::init(false), cl::Hidden, cl::desc("Allow incomplete IR on a best effort basis (references to unknown " "metadata will be dropped)")) ("allow-incomplete-ir" , cl::init(false) , cl::Hidden , cl::desc("Allow incomplete IR on a best effort basis (references to unknown " "metadata will be dropped)")) static
EmptyVI
ValueInfo EmptyVI static
Initial value:
=
    ValueInfo(false, (GlobalValueSummaryMapTy::value_type *)-8)
Definition at line 9150 of file LLParser.cpp.
Referenced by llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::fixAliaseeLinks().
FwdVIRef
const auto FwdVIRef = (GlobalValueSummaryMapTy::value_type *)-8 static
Definition at line 9507 of file LLParser.cpp.