LLVM: lib/Transforms/Utils/LowerGlobalDtors.cpp File Reference
LowerGlobalDtors.cpp File Reference
Lower @llvm.global_dtors.
#include "llvm/Transforms/Utils/LowerGlobalDtors.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <map>
Macros
#define DEBUG_TYPE "lower-global-dtors"
Functions
INITIALIZE_PASS (LowerGlobalDtorsLegacyPass, DEBUG_TYPE, "Lower @llvm.global_dtors via `__cxa_atexit`", false, false) ModulePass *llvm
static bool runImpl (Module &M)
Detailed Description
Lower @llvm.global_dtors.
Implement @llvm.global_dtors by creating wrapper functions that are registered in @llvm.global_ctors and which contain a call to __cxa_atexit to register their destructor functions.
Definition in file LowerGlobalDtors.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-global-dtors"
Definition at line 32 of file LowerGlobalDtors.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LowerGlobalDtorsLegacyPass , DEBUG_TYPE , "Lower @llvm.global_dtors via `__cxa_atexit`" , false , false)
Definition at line 56 of file LowerGlobalDtors.cpp.
References llvm::createLowerGlobalDtorsLegacyPass(), and DEBUG_TYPE.
runImpl()
bool runImpl (Module & M) static
Definition at line 77 of file LowerGlobalDtors.cpp.
References llvm::appendToGlobalCtors(), llvm::CallingConv::C, llvm::cast(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::CallInst::Create(), llvm::Function::Create(), llvm::ReturnInst::Create(), llvm::dyn_cast(), llvm::GlobalVariable::eraseFromParent(), llvm::GlobalValue::ExternalWeakLinkage, F, llvm::ConstantPointerNull::get(), llvm::FunctionType::get(), llvm::PointerType::get(), llvm::FunctionCallee::getCallee(), llvm::ArrayType::getElementType(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::Type::getInt8Ty(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::ConstantArray::getType(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::HiddenVisibility, llvm::CmpInst::ICMP_NE, llvm::Constant::isNullValue(), llvm::Null, llvm::User::operands(), llvm::GlobalValue::PrivateLinkage, llvm::reverse(), llvm::GlobalValue::setVisibility(), and llvm::Constant::stripPointerCasts().