LLVM: lib/Target/M68k/MCTargetDesc/M68kAsmBackend.cpp File Reference
M68kAsmBackend.cpp File Reference
This file contains definitions for M68k assembler backend.
#include "MCTargetDesc/M68kBaseInfo.h"
#include "MCTargetDesc/M68kFixupKinds.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "M68k-asm-backend"
Functions
static unsigned getRelaxedOpcodeBranch (unsigned Op)
cc—Carry clear GE—Greater than or equal LS—Lower or same PL—Plus CS—Carry set GT—Greater than LT—Less than EQ—Equal HI—Higher MI—Minus VC—Overflow clear LE—Less than or equal NE—Not equal VS—Overflow set
static unsigned getRelaxedOpcode (unsigned Opcode)
Detailed Description
This file contains definitions for M68k assembler backend.
Definition in file M68kAsmBackend.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "M68k-asm-backend"
Definition at line 41 of file M68kAsmBackend.cpp.
Function Documentation
getRelaxedOpcode()
unsigned getRelaxedOpcode (unsigned Opcode) static
Definition at line 181 of file M68kAsmBackend.cpp.
References getRelaxedOpcodeBranch().
Referenced by llvm::RISCVAsmBackend::mayNeedRelaxation(), and llvm::RISCVAsmBackend::relaxInstruction().
getRelaxedOpcodeBranch()
unsigned getRelaxedOpcodeBranch (unsigned Op) static
cc—Carry clear GE—Greater than or equal LS—Lower or same PL—Plus CS—Carry set GT—Greater than LT—Less than EQ—Equal HI—Higher MI—Minus VC—Overflow clear LE—Less than or equal NE—Not equal VS—Overflow set
Definition at line 110 of file M68kAsmBackend.cpp.
Referenced by getRelaxedOpcode().