LLVM: lib/Object/MachOUniversalWriter.cpp File Reference
MachOUniversalWriter.cpp File Reference
#include "llvm/Object/MachOUniversalWriter.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBufferRef.h"
#include "llvm/Support/SwapByteOrder.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
Classes
struct FatArchTraits< FatArchTy >
struct FatArchTraits< MachO::fat_arch >
struct FatArchTraits< MachO::fat_arch_64 >
Typedefs
using MachoCPUTy = std::pair<uint32_t, uint32_t>
Functions
static uint32_t calculateFileAlignment (const MachOObjectFile &O)
static uint32_t calculateAlignment (const MachOObjectFile &ObjectFile)
static Expected< MachoCPUTy > getMachoCPUFromTriple (Triple TT)
static Expected< MachoCPUTy > getMachoCPUFromTriple (StringRef TT)
static MachoCPUTy getMachoCPUFromObjectFile (const MachOObjectFile &O)
template<typename FatArchTy>
static Expected< SmallVector< FatArchTy, 2 > > buildFatArchList (ArrayRef< Slice > Slices)
template<typename FatArchTy>
static Error writeUniversalArchsToStream (MachO::fat_header FatHeader, ArrayRef< Slice > Slices, raw_ostream &Out)
Variables
const std::string FatArchTraits< MachO::fat_arch >::StructName = "fat_arch"
const std::string FatArchTraits< MachO::fat_arch_64 >::StructName = "fat_arch_64"
Typedef Documentation
MachoCPUTy
using MachoCPUTy = std::pair<uint32_t, uint32_t>
Definition at line 103 of file MachOUniversalWriter.cpp.
Function Documentation
buildFatArchList()
template<typename FatArchTy> Expected< SmallVector< FatArchTy, 2 > > buildFatArchList (ArrayRef< Slice > Slices) static
Definition at line 261 of file MachOUniversalWriter.cpp.
References llvm::alignTo(), FatArchTraits< FatArchTy >::BitCount, llvm::createStringError(), llvm::Offset, FatArchTraits< FatArchTy >::OffsetLimit, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ArrayRef< T >::size(), and FatArchTraits< FatArchTy >::StructName.
Referenced by writeUniversalArchsToStream().
calculateAlignment()
uint32_t calculateAlignment (const MachOObjectFile & ObjectFile) static
Definition at line 69 of file MachOUniversalWriter.cpp.
References calculateFileAlignment(), llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_ARM64_32, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, and llvm::MachO::CPU_TYPE_X86_64.
Referenced by llvm::object::Slice::Slice().
calculateFileAlignment()
uint32_t calculateFileAlignment (const MachOObjectFile & O) static
Definition at line 37 of file MachOUniversalWriter.cpp.
References llvm::countr_zero(), llvm::object::MachOUniversalBinary::MaxSectionAlignment, and llvm::MachO::MH_OBJECT.
Referenced by calculateAlignment().
getMachoCPUFromObjectFile()
MachoCPUTy getMachoCPUFromObjectFile (const MachOObjectFile & O) static
Definition at line 120 of file MachOUniversalWriter.cpp.
Referenced by llvm::object::Slice::create().
getMachoCPUFromTriple() [1/2]
Expected< MachoCPUTy > getMachoCPUFromTriple (StringRef TT) static
Definition at line 116 of file MachOUniversalWriter.cpp.
References getMachoCPUFromTriple().
getMachoCPUFromTriple() [2/2]
Expected< MachoCPUTy > getMachoCPUFromTriple (Triple TT) static
Definition at line 105 of file MachOUniversalWriter.cpp.
References llvm::MachO::getCPUSubType(), and llvm::MachO::getCPUType().
Referenced by llvm::object::Slice::create(), llvm::object::Slice::create(), and getMachoCPUFromTriple().
writeUniversalArchsToStream()
template<typename FatArchTy> Error writeUniversalArchsToStream (MachO::fat_header FatHeader, ArrayRef< Slice > Slices, raw_ostream & Out) static
Definition at line 293 of file MachOUniversalWriter.cpp.
References assert(), buildFatArchList(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::object::FatHeader, llvm::raw_ostream::flush(), llvm::MemoryBufferRef::getBufferSize(), llvm::MemoryBufferRef::getBufferStart(), llvm::sys::IsLittleEndianHost, llvm::Offset, Size, llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Error::success(), llvm::MachO::swapStruct(), llvm::Expected< T >::takeError(), llvm::raw_ostream::write(), and llvm::raw_ostream::write_zeros().
Referenced by llvm::object::writeUniversalBinaryToStream().
Variable Documentation
FatArchTraits< MachO::fat_arch >::StructName
const std::string FatArchTraits< MachO::fat_arch >::StructName = "fat_arch"
Definition at line 250 of file MachOUniversalWriter.cpp.
FatArchTraits< MachO::fat_arch_64 >::StructName
const std::string FatArchTraits< MachO::fat_arch_64 >::StructName = "fat_arch_64"
Definition at line 257 of file MachOUniversalWriter.cpp.