LLVM: lib/MC/MCGOFFStreamer.cpp File Reference
MCGOFFStreamer.cpp File Reference
#include "llvm/MC/MCGOFFStreamer.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCGOFFObjectWriter.h"
#include "llvm/MC/TargetRegistry.h"
Functions
static void registerSectionHierarchy (MCAssembler &Asm, MCSectionGOFF *Section)
Function Documentation
registerSectionHierarchy()
void registerSectionHierarchy (MCAssembler & Asm, MCSectionGOFF * Section) static
Definition at line 30 of file MCGOFFStreamer.cpp.
References registerSectionHierarchy().
Referenced by llvm::MCGOFFStreamer::changeSection(), and registerSectionHierarchy().