LLVM: lib/MC/MCObjectStreamer.cpp File Reference
MCObjectStreamer.cpp File Reference
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCCodeView.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SourceMgr.h"
Functions
static std::optional< uint64_t > absoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo)
static bool canReuseDataFragment (const MCDataFragment &F, const MCAssembler &Assembler, const MCSubtargetInfo *STI)
static const MCExpr * buildSymbolDiff (MCObjectStreamer &OS, const MCSymbol *A, const MCSymbol *B, SMLoc Loc)
static void emitDwarfSetLineAddr (MCObjectStreamer &OS, MCDwarfLineTableParams Params, int64_t LineDelta, const MCSymbol *Label, int PointerSize)
static std::optional< std::pair< bool, std::string > > getOffsetAndDataFragment (const MCSymbol &Symbol, uint32_t &RelocOffset, MCDataFragment *&DF)
Variables
static const char *const BundlingNotImplementedMsg
Function Documentation
absoluteSymbolDiff()
std::optional< uint64_t > absoluteSymbolDiff (const MCSymbol * Hi, const MCSymbol * Lo) static
Definition at line 80 of file MCObjectStreamer.cpp.
References assert(), llvm::MCFragment::FT_Data, llvm::Hi, and llvm::Lo.
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128(), and llvm::MCObjectStreamer::emitDwarfAdvanceLineAddr().
buildSymbolDiff()
const MCExpr * buildSymbolDiff (MCObjectStreamer & OS, const MCSymbol * A, const MCSymbol * B, SMLoc Loc) static
Definition at line 451 of file MCObjectStreamer.cpp.
References A(), B(), llvm::MCBinaryExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCStreamer::getContext(), and llvm::MCBinaryExpr::Sub.
Referenced by llvm::MCPseudoProbe::emit(), llvm::MCObjectStreamer::emitDwarfAdvanceFrameAddr(), and llvm::MCObjectStreamer::emitDwarfAdvanceLineAddr().
canReuseDataFragment()
bool canReuseDataFragment (const MCDataFragment & F, const MCAssembler & Assembler, const MCSubtargetInfo * STI) static
Definition at line 134 of file MCObjectStreamer.cpp.
References F, and llvm::MCAssembler::isBundlingEnabled().
Referenced by llvm::MCObjectStreamer::getOrCreateDataFragment().
emitDwarfSetLineAddr()
void emitDwarfSetLineAddr (MCObjectStreamer & OS, MCDwarfLineTableParams Params, int64_t LineDelta, const MCSymbol * Label, int PointerSize) static
Definition at line 461 of file MCObjectStreamer.cpp.
References llvm::MCDwarfLineAddr::Emit(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitSymbolValue(), and llvm::MCStreamer::emitULEB128IntValue().
Referenced by llvm::MCObjectStreamer::emitDwarfAdvanceLineAddr().
getOffsetAndDataFragment()
std::optional< std::pair< bool, std::string > > getOffsetAndDataFragment (const MCSymbol & Symbol, uint32_t & RelocOffset, MCDataFragment *& DF) static
Definition at line 624 of file MCObjectStreamer.cpp.
References llvm::cast(), DF, llvm::MCExpr::evaluateAsRelocatable(), llvm::MCFragment::FT_Data, llvm::MCValue::getAddSym(), llvm::MCValue::getConstant(), llvm::MCSymbol::getFragment(), llvm::MCSymbol::getOffset(), llvm::MCValue::getSubSym(), llvm::MCValue::isAbsolute(), llvm::MCSymbol::isDefined(), and llvm::MCSymbol::isVariable().
Referenced by llvm::MCObjectStreamer::emitRelocDirective().
Variable Documentation
BundlingNotImplementedMsg
const char* const BundlingNotImplementedMsg static
Initial value:
=
  "Aligned bundling is not implemented for this object format"
Definition at line 421 of file MCObjectStreamer.cpp.
Referenced by llvm::MCObjectStreamer::emitBundleAlignMode(), llvm::MCObjectStreamer::emitBundleLock(), and llvm::MCObjectStreamer::emitBundleUnlock().