LLVM: lib/MC/MCSectionGOFF.cpp File Reference
MCSectionGOFF.cpp File Reference
#include "llvm/MC/MCSectionGOFF.h"
#include "llvm/BinaryFormat/GOFF.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void emitCATTR (raw_ostream &OS, StringRef Name, GOFF::ESDRmode Rmode, GOFF::ESDAlignment Alignment, GOFF::ESDLoadingBehavior LoadBehavior, GOFF::ESDExecutable Executable, bool IsReadOnly, uint32_t SortKey, uint8_t FillByteValue, StringRef PartName)
static void emitXATTR (raw_ostream &OS, StringRef Name, GOFF::ESDLinkageType Linkage, GOFF::ESDExecutable Executable, GOFF::ESDBindingScope BindingScope)
Function Documentation
emitCATTR()
void emitCATTR (raw_ostream & OS, StringRef Name, GOFF::ESDRmode Rmode, GOFF::ESDAlignment Alignment, GOFF::ESDLoadingBehavior LoadBehavior, GOFF::ESDExecutable Executable, bool IsReadOnly, uint32_t SortKey, uint8_t FillByteValue, StringRef PartName) static
Definition at line 15 of file MCSectionGOFF.cpp.
References llvm::StringRef::empty(), llvm::GOFF::ESD_EXE_CODE, llvm::GOFF::ESD_EXE_DATA, llvm::GOFF::ESD_LB_Deferred, llvm::GOFF::ESD_LB_NoLoad, llvm::GOFF::ESD_RMODE_24, llvm::GOFF::ESD_RMODE_31, llvm::GOFF::ESD_RMODE_64, and llvm::GOFF::ESD_RMODE_None.
Referenced by llvm::MCSectionGOFF::printSwitchToSection().
emitXATTR()
void emitXATTR (raw_ostream & OS, StringRef Name, GOFF::ESDLinkageType Linkage, GOFF::ESDExecutable Executable, GOFF::ESDBindingScope BindingScope) static
Definition at line 71 of file MCSectionGOFF.cpp.
References llvm::GOFF::ESD_BSC_ImportExport, llvm::GOFF::ESD_BSC_Library, llvm::GOFF::ESD_BSC_Module, llvm::GOFF::ESD_BSC_Section, llvm::GOFF::ESD_BSC_Unspecified, llvm::GOFF::ESD_EXE_CODE, llvm::GOFF::ESD_EXE_Unspecified, llvm::GOFF::ESD_LT_OS, and Linkage.
Referenced by llvm::MCSectionGOFF::printSwitchToSection().