LLVM: lib/Analysis/MemoryProfileInfo.cpp File Reference
MemoryProfileInfo.cpp File Reference
#include "llvm/Analysis/MemoryProfileInfo.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Constants.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Format.h"
Macros
#define DEBUG_TYPE "memory-profile-info"
Functions
LLVM_ABI cl::opt< bool > MemProfKeepAllNotColdContexts ("memprof-keep-all-not-cold-contexts", cl::init(false), cl::Hidden, cl::desc("Keep all non-cold contexts (increases cloning overheads)"))
static MDNode * createMIBNode (LLVMContext &Ctx, ArrayRef< uint64_t > MIBCallStack, AllocationType AllocType, ArrayRef< ContextTotalSize > ContextSizeInfo, const uint64_t MaxColdSize, uint64_t &TotalBytes, uint64_t &ColdBytes)
static void saveFilteredNewMIBNodes (std::vector< Metadata * > &NewMIBNodes, std::vector< Metadata * > &SavedMIBNodes, unsigned CallerContextLength, uint64_t TotalBytes, uint64_t ColdBytes)
Variables
cl::opt< bool > MemProfReportHintedSizes ("memprof-report-hinted-sizes", cl::init(false), cl::Hidden, cl::desc("Report total allocation sizes of hinted allocations"))
cl::opt< unsigned > MinClonedColdBytePercent ("memprof-cloning-cold-threshold", cl::init(100), cl::Hidden, cl::desc("Min percent of cold bytes to hint alloc cold during cloning"))
cl::opt< unsigned > MinCallsiteColdBytePercent ("memprof-callsite-cold-threshold", cl::init(100), cl::Hidden, cl::desc("Min percent of cold bytes at a callsite to discard non-cold " "contexts"))
cl::opt< unsigned > MinPercentMaxColdSize ("memprof-min-percent-max-cold-size", cl::init(100), cl::Hidden, cl::desc("Min percent of max cold bytes for critical cold context"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memory-profile-info"
Definition at line 23 of file MemoryProfileInfo.cpp.
Function Documentation
createMIBNode()
MDNode * createMIBNode (LLVMContext & Ctx, ArrayRef< uint64_t > MIBCallStack, AllocationType AllocType, ArrayRef< ContextTotalSize > ContextSizeInfo, const uint64_t MaxColdSize, uint64_t & TotalBytes, uint64_t & ColdBytes) static
Definition at line 187 of file MemoryProfileInfo.cpp.
References assert(), llvm::memprof::buildCallstackMetadata(), llvm::Cold, llvm::ArrayRef< T >::empty(), llvm::MDNode::get(), llvm::MDString::get(), llvm::ValueAsMetadata::get(), llvm::memprof::getAllocTypeAttributeString(), llvm::Type::getInt64Ty(), llvm::memprof::metadataIncludesAllContextSizeInfo(), MinCallsiteColdBytePercent, MinPercentMaxColdSize, llvm::MDTuple::push_back(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
MemProfKeepAllNotColdContexts()
LLVM_ABI cl::opt< bool > MemProfKeepAllNotColdContexts ("memprof-keep-all-not-cold-contexts" , cl::init(false) , cl::Hidden , cl::desc("Keep all non-cold contexts (increases cloning overheads)"))
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by saveFilteredNewMIBNodes().
saveFilteredNewMIBNodes()
void saveFilteredNewMIBNodes (std::vector< Metadata * > & NewMIBNodes, std::vector< Metadata * > & SavedMIBNodes, unsigned CallerContextLength, uint64_t TotalBytes, uint64_t ColdBytes) static
Definition at line 252 of file MemoryProfileInfo.cpp.
References llvm::append_range(), assert(), llvm::cast(), llvm::Cold, llvm::dyn_cast(), llvm::mdconst::dyn_extract(), llvm::errs(), llvm::format(), llvm::memprof::getMIBAllocType(), llvm::memprof::getMIBStackNode(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), I, llvm::make_filter_range(), MemProfKeepAllNotColdContexts(), MemProfReportHintedSizes, MinCallsiteColdBytePercent, and llvm::raw_string_ostream::str().
Variable Documentation
MemProfReportHintedSizes
cl::opt< bool > MemProfReportHintedSizes("memprof-report-hinted-sizes", cl::init(false), cl::Hidden, cl::desc("Report total allocation sizes of hinted allocations")) ("memprof-report-hinted-sizes" , cl::init(false) , cl::Hidden , cl::desc("Report total allocation sizes of hinted allocations"))
Referenced by llvm::memprof::CallStackTrie::addSingleAllocTypeAttribute(), llvm::memprof::metadataIncludesAllContextSizeInfo(), and saveFilteredNewMIBNodes().
MinCallsiteColdBytePercent
cl::opt< unsigned > MinCallsiteColdBytePercent("memprof-callsite-cold-threshold", cl::init(100), cl::Hidden, cl::desc("Min percent of cold bytes at a callsite to discard non-cold " "contexts")) ("memprof-callsite-cold-threshold" , cl::init(100) , cl::Hidden , cl::desc("Min percent of cold bytes at a callsite to discard non-cold " "contexts"))
Referenced by createMIBNode(), llvm::memprof::recordContextSizeInfoForAnalysis(), and saveFilteredNewMIBNodes().
MinClonedColdBytePercent
cl::opt< unsigned > MinClonedColdBytePercent("memprof-cloning-cold-threshold", cl::init(100), cl::Hidden, cl::desc("Min percent of cold bytes to hint alloc cold during cloning")) ("memprof-cloning-cold-threshold" , cl::init(100) , cl::Hidden , cl::desc("Min percent of cold bytes to hint alloc cold during cloning"))
Referenced by llvm::memprof::metadataIncludesAllContextSizeInfo().
MinPercentMaxColdSize
cl::opt< unsigned > MinPercentMaxColdSize("memprof-min-percent-max-cold-size", cl::init(100), cl::Hidden, cl::desc("Min percent of max cold bytes for critical cold context")) ("memprof-min-percent-max-cold-size" , cl::init(100) , cl::Hidden , cl::desc("Min percent of max cold bytes for critical cold context"))
Referenced by createMIBNode(), and llvm::memprof::metadataMayIncludeContextSizeInfo().