LLVM: lib/ProfileData/MemProfCommon.cpp File Reference
MemProfCommon.cpp File Reference
#include "llvm/ProfileData/MemProfCommon.h"
#include "llvm/ProfileData/MemProf.h"
#include "llvm/Support/BLAKE3.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/HashBuilder.h"
Functions
LLVM_ABI cl::opt< float > MemProfLifetimeAccessDensityColdThreshold ("memprof-lifetime-access-density-cold-threshold", cl::init(0.05), cl::Hidden, cl::desc("The threshold the lifetime access density (accesses per byte per " "lifetime sec) must be under to consider an allocation cold"))
LLVM_ABI cl::opt< unsigned > MemProfAveLifetimeColdThreshold ("memprof-ave-lifetime-cold-threshold", cl::init(200), cl::Hidden, cl::desc("The average lifetime (s) for an allocation to be considered " "cold"))
LLVM_ABI cl::opt< unsigned > MemProfMinAveLifetimeAccessDensityHotThreshold ("memprof-min-ave-lifetime-access-density-hot-threshold", cl::init(1000), cl::Hidden, cl::desc("The minimum TotalLifetimeAccessDensity / AllocCount for an " "allocation to be considered hot"))
LLVM_ABI cl::opt< bool > MemProfUseHotHints ("memprof-use-hot-hints", cl::init(false), cl::Hidden, cl::desc("Enable use of hot hints (only supported for " "unambigously hot allocations)"))
Function Documentation
MemProfAveLifetimeColdThreshold()
LLVM_ABI cl::opt< unsigned > MemProfAveLifetimeColdThreshold ("memprof-ave-lifetime-cold-threshold" , cl::init(200) , cl::Hidden , cl::desc("The average lifetime (s) for an allocation to be considered " "cold"))
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::memprof::getAllocType().
MemProfLifetimeAccessDensityColdThreshold()
LLVM_ABI cl::opt< float > MemProfLifetimeAccessDensityColdThreshold ("memprof-lifetime-access-density-cold-threshold" , cl::init(0.05) , cl::Hidden , cl::desc("The threshold the lifetime access density (accesses per byte per " "lifetime sec) must be under to consider an allocation cold"))
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::memprof::getAllocType().
MemProfMinAveLifetimeAccessDensityHotThreshold()
LLVM_ABI cl::opt< unsigned > MemProfMinAveLifetimeAccessDensityHotThreshold ("memprof-min-ave-lifetime-access-density-hot-threshold" , cl::init(1000) , cl::Hidden , cl::desc("The minimum TotalLifetimeAccessDensity / AllocCount for an " "allocation to be considered hot"))
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::memprof::getAllocType().
MemProfUseHotHints()
LLVM_ABI cl::opt< bool > MemProfUseHotHints ("memprof-use-hot-hints" , cl::init(false) , cl::Hidden , cl::desc("Enable use of hot hints (only supported for " "unambigously hot allocations)"))
References llvm::cl::Hidden, and llvm::cl::init().
Referenced by llvm::memprof::getAllocType().