LLVM: lib/ObjectYAML/MinidumpEmitter.cpp File Reference
MinidumpEmitter.cpp File Reference
#include "llvm/ObjectYAML/MinidumpYAML.h"
#include "llvm/ObjectYAML/yaml2obj.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::yaml
Functions
static LocationDescriptor layout (BlobAllocator &File, yaml::BinaryRef Data)
static size_t layout (BlobAllocator &File, MinidumpYAML::ExceptionStream &S)
static size_t layout (BlobAllocator &File, MinidumpYAML::Memory64ListStream &S)
static void layout (BlobAllocator &File, MemoryListStream::entry_type &Range)
static void layout (BlobAllocator &File, ModuleListStream::entry_type &M)
static void layout (BlobAllocator &File, ThreadListStream::entry_type &T)
template<typename EntryT>
static size_t layout (BlobAllocator &File, MinidumpYAML::detail::ListStream< EntryT > &S)
static Directory layout (BlobAllocator &File, Stream &S)
LLVM_ABI bool llvm::yaml::yaml2minidump (MinidumpYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
Function Documentation
layout() [1/8]
void layout (BlobAllocator & File, MemoryListStream::entry_type & Range) static
Definition at line 163 of file MinidumpEmitter.cpp.
References layout(), and Range.
layout() [2/8]
template<typename EntryT> size_t layout (BlobAllocator & File, MinidumpYAML::detail::ListStream< EntryT > & S) static
Definition at line 180 of file MinidumpEmitter.cpp.
References E(), llvm::MinidumpYAML::detail::ListStream< EntryT >::Entries, and layout().
layout() [3/8]
size_t layout (BlobAllocator & File, MinidumpYAML::ExceptionStream & S) static
Definition at line 122 of file MinidumpEmitter.cpp.
References layout(), llvm::MinidumpYAML::ExceptionStream::MDExceptionStream, llvm::minidump::ExceptionStream::ThreadContext, and llvm::MinidumpYAML::ExceptionStream::ThreadContext.
layout() [4/8]
size_t layout (BlobAllocator & File, MinidumpYAML::Memory64ListStream & S) static
Definition at line 139 of file MinidumpEmitter.cpp.
References llvm::minidump::Memory64ListHeader::BaseRVA, E(), llvm::MinidumpYAML::detail::ListStream< EntryT >::Entries, llvm::MinidumpYAML::Memory64ListStream::Header, and llvm::minidump::Memory64ListHeader::NumberOfMemoryRanges.
layout() [5/8]
void layout (BlobAllocator & File, ModuleListStream::entry_type & M) static
Definition at line 167 of file MinidumpEmitter.cpp.
References layout().
layout() [6/8]
Directory layout (BlobAllocator & File, Stream & S) static
Definition at line 197 of file MinidumpEmitter.cpp.
References llvm::ArrayRef(), llvm::arrayRefFromStringRef(), llvm::cast(), llvm::minidump::SystemInfo::CSDVersionRVA, llvm::MinidumpYAML::Stream::Exception, llvm::MinidumpYAML::MemoryInfoListStream::Infos, llvm::MinidumpYAML::Stream::Kind, layout(), llvm::MinidumpYAML::Stream::Memory64List, llvm::MinidumpYAML::Stream::MemoryInfoList, llvm::MinidumpYAML::Stream::MemoryList, llvm::MinidumpYAML::Stream::ModuleList, llvm::MinidumpYAML::Stream::RawContent, llvm::MinidumpYAML::RawContentStream::Size, llvm::MinidumpYAML::Stream::SystemInfo, llvm::MinidumpYAML::Stream::TextContent, llvm::MinidumpYAML::Stream::ThreadList, and llvm::MinidumpYAML::Stream::Type.
layout() [7/8]
void layout (BlobAllocator & File, ThreadListStream::entry_type & T) static
Definition at line 174 of file MinidumpEmitter.cpp.
References layout(), and T.
layout() [8/8]
LocationDescriptor layout (BlobAllocator & File, yaml::BinaryRef Data) static
Definition at line 117 of file MinidumpEmitter.cpp.
References llvm::Data.
Referenced by layout(), layout(), layout(), layout(), layout(), layout(), and llvm::yaml::yaml2minidump().