LLVM: lib/Target/Mips/MipsAsmPrinter.cpp File Reference
MipsAsmPrinter.cpp File Reference
#include "MipsAsmPrinter.h"
#include "MCTargetDesc/MipsABIInfo.h"
#include "MCTargetDesc/MipsBaseInfo.h"
#include "MCTargetDesc/MipsInstPrinter.h"
#include "MCTargetDesc/MipsMCAsmInfo.h"
#include "MCTargetDesc/MipsMCNaCl.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "MCTargetDesc/MipsTargetStreamer.h"
#include "Mips.h"
#include "MipsMCInstLower.h"
#include "MipsMachineFunction.h"
#include "MipsSubtarget.h"
#include "MipsTargetMachine.h"
#include "TargetInfo/MipsTargetInfo.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/TargetParser/Triple.h"
#include <cassert>
#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "MipsGenMCPseudoLowering.inc"
Macros
#define DEBUG_TYPE "mips-asm-printer"
Functions
static void emitDirectiveRelocJalr (const MachineInstr &MI, MCContext &OutContext, TargetMachine &TM, MCStreamer &OutStreamer, const MipsSubtarget &Subtarget)
INITIALIZE_PASS (MipsAsmPrinter, "mips-asm-printer", "Mips Assembly Printer", false, false) extern "C" LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsAsmPrinter()
Variables
cl::opt< bool > EmitJalrReloc
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-asm-printer"
Definition at line 73 of file MipsAsmPrinter.cpp.
Function Documentation
emitDirectiveRelocJalr()
void emitDirectiveRelocJalr (const MachineInstr & MI, MCContext & OutContext, TargetMachine & TM, MCStreamer & OutStreamer, const MipsSubtarget & Subtarget) static
Definition at line 156 of file MipsAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), llvm::drop_begin(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitRelocDirective(), llvm::MachineOperand::getMCSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MipsSubtarget::inMicroMipsMode(), llvm::MachineOperand::isMCSymbol(), MI, and llvm::MipsII::MO_JALR.
Referenced by llvm::MipsAsmPrinter::emitInstruction().
INITIALIZE_PASS()
INITIALIZE_PASS (MipsAsmPrinter , "mips-asm-printer" , "Mips Assembly Printer" , false , false)
Definition at line 1303 of file MipsAsmPrinter.cpp.
References A(), B(), llvm::getTheMips64elTarget(), llvm::getTheMips64Target(), llvm::getTheMipselTarget(), llvm::getTheMipsTarget(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, X, and Y.
Variable Documentation
EmitJalrReloc
cl::opt<bool> EmitJalrReloc extern