LLVM: lib/Target/Mips/MCTargetDesc/MipsMCTargetDesc.cpp File Reference
MipsMCTargetDesc.cpp File Reference
#include "MipsMCTargetDesc.h"
#include "MipsAsmBackend.h"
#include "MipsBaseInfo.h"
#include "MipsELFStreamer.h"
#include "MipsInstPrinter.h"
#include "MipsMCAsmInfo.h"
#include "MipsMCNaCl.h"
#include "MipsTargetStreamer.h"
#include "TargetInfo/MipsTargetInfo.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/TargetParser/Triple.h"
#include "MipsGenInstrInfo.inc"
#include "MipsGenSubtargetInfo.inc"
#include "MipsGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createMipsMCInstrInfo ()
static MCRegisterInfo * createMipsMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createMipsMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createMipsMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstPrinter * createMipsMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCStreamer * createMCStreamer (const Triple &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter)
static MCTargetStreamer * createMipsAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint)
static MCTargetStreamer * createMipsNullTargetStreamer (MCStreamer &S)
static MCTargetStreamer * createMipsObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCInstrAnalysis * createMipsMCInstrAnalysis (const MCInstrInfo *Info)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 40 of file MipsMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 39 of file MipsMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 46 of file MipsMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 43 of file MipsMCTargetDesc.cpp.
Function Documentation
createMCStreamer()
MCStreamer * createMCStreamer (const Triple & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter) static
Definition at line 197 of file MipsMCTargetDesc.cpp.
References llvm::createMipsELFStreamer(), llvm::createMipsNaClELFStreamer(), Emitter, and T.
createMipsAsmTargetStreamer()
MCTargetStreamer * createMipsAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint) static
Definition at line 211 of file MipsMCTargetDesc.cpp.
Referenced by LLVMInitializeMipsTargetMC().
createMipsMCAsmInfo()
MCAsmInfo * createMipsMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 172 of file MipsMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::createDefCfaRegister(), MRI, and Options.
Referenced by LLVMInitializeMipsTargetMC().
createMipsMCInstPrinter()
MCInstPrinter * createMipsMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 189 of file MipsMCTargetDesc.cpp.
References MRI, and T.
Referenced by LLVMInitializeMipsTargetMC().
createMipsMCInstrAnalysis()
MCInstrAnalysis * createMipsMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 259 of file MipsMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeMipsTargetMC().
createMipsMCInstrInfo()
MCInstrInfo * createMipsMCInstrInfo () static
Definition at line 154 of file MipsMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeMipsTargetMC().
createMipsMCRegisterInfo()
MCRegisterInfo * createMipsMCRegisterInfo (const Triple & TT) static
Definition at line 160 of file MipsMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeMipsTargetMC().
createMipsMCSubtargetInfo()
MCSubtargetInfo * createMipsMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 166 of file MipsMCTargetDesc.cpp.
References llvm::MIPS_MC::selectMipsCPU().
Referenced by LLVMInitializeMipsTargetMC().
createMipsNullTargetStreamer()
MCTargetStreamer * createMipsNullTargetStreamer (MCStreamer & S) static
Definition at line 217 of file MipsMCTargetDesc.cpp.
Referenced by LLVMInitializeMipsTargetMC().
createMipsObjectTargetStreamer()
MCTargetStreamer * createMipsObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 222 of file MipsMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getTargetTriple(), and llvm::Triple::isOSBinFormatCOFF().
Referenced by LLVMInitializeMipsTargetMC().
LLVMInitializeMipsTargetMC()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsTargetMC ()
Definition at line 263 of file MipsMCTargetDesc.cpp.
References createMCStreamer(), llvm::createMipsAsmBackend(), createMipsAsmTargetStreamer(), createMipsMCAsmInfo(), llvm::createMipsMCCodeEmitterEB(), llvm::createMipsMCCodeEmitterEL(), createMipsMCInstPrinter(), createMipsMCInstrAnalysis(), createMipsMCInstrInfo(), createMipsMCRegisterInfo(), createMipsMCSubtargetInfo(), createMipsNullTargetStreamer(), createMipsObjectTargetStreamer(), llvm::createMipsWinCOFFStreamer(), llvm::getTheMips64elTarget(), llvm::getTheMips64Target(), llvm::getTheMipselTarget(), llvm::getTheMipsTarget(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterCOFFStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), T, and X.