LLVM: lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp File Reference
MipsTargetStreamer.cpp File Reference
#include "MipsTargetStreamer.h"
#include "MCTargetDesc/MipsABIInfo.h"
#include "MCTargetDesc/MipsMCAsmInfo.h"
#include "MipsBaseInfo.h"
#include "MipsELFStreamer.h"
#include "MipsInstPrinter.h"
#include "MipsMCTargetDesc.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
Functions
static bool isMicroMips (const MCSubtargetInfo *STI)
static bool isMips32r6 (const MCSubtargetInfo *STI)
static void printHex32 (unsigned Value, raw_ostream &OS)
Function Documentation
isMicroMips()
bool isMicroMips (const MCSubtargetInfo * STI) static
Definition at line 42 of file MipsTargetStreamer.cpp.
References llvm::MCSubtargetInfo::hasFeature().
Referenced by llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MipsTargetStreamer::emitEmptyDelaySlot(), llvm::MipsTargetStreamer::emitNop(), and llvm::MipsSEInstrInfo::expandPostRAPseudo().
isMips32r6()
bool isMips32r6 (const MCSubtargetInfo * STI) static
Definition at line 46 of file MipsTargetStreamer.cpp.
References llvm::MCSubtargetInfo::hasFeature().
Referenced by llvm::MipsTargetStreamer::emitEmptyDelaySlot().
printHex32()
void printHex32 (unsigned Value, raw_ostream & OS) static
Definition at line 713 of file MipsTargetStreamer.cpp.
References llvm::raw_ostream::write_hex().
Referenced by llvm::MipsTargetAsmStreamer::emitFMask(), and llvm::MipsTargetAsmStreamer::emitMask().