LLVM: llvm::VPlanPatternMatch Namespace Reference
llvm::VPlanPatternMatch Namespace Reference
Classes
struct Argument_match
Match a call argument at a given argument index.
struct bind_ty
struct class_match
struct deferredval_ty
Stores a reference to the VPValue *, not the VPValue * itself, thus can be used in commutative matchers.
struct int_pred_ty
Match an integer constant or vector of constants if Pred::isValue returns true for the APInt.
struct IntrinsicID_match
Intrinsic matchers.
struct is_all_ones
struct is_specific_int
Match a specified integer value or vector of all elements of that value.
struct m_Intrinsic_Ty
Intrinsic matches are combinations of ID matchers, and argument matchers.
struct m_Intrinsic_Ty< T0 >
struct m_Intrinsic_Ty< T0, T1 >
struct m_Intrinsic_Ty< T0, T1, T2 >
struct match_combine_and
struct match_combine_or
Matching combinators.
struct Recipe_match
struct specificval_ty
Match a specified VPValue.
Typedefs
template<unsigned Bitwidth = 0>
using specific_intval = int_pred_ty<is_specific_int, Bitwidth>
template<unsigned Opcode, typename... RecipeTys>
using ZeroOpRecipe_match
template<typename Op0_t, unsigned Opcode, typename... RecipeTys>
using UnaryRecipe_match
template<typename Op0_t, unsigned Opcode>
using UnaryVPInstruction_match
template<unsigned Opcode>
using ZeroOpVPInstruction_match = ZeroOpRecipe_match<Opcode, VPInstruction>
template<typename Op0_t, unsigned Opcode>
using AllUnaryRecipe_match
template<typename Op0_t, typename Op1_t, unsigned Opcode, bool Commutative, typename... RecipeTys>
using BinaryRecipe_match
template<typename Op0_t, typename Op1_t, unsigned Opcode>
using BinaryVPInstruction_match
template<typename Op0_t, typename Op1_t, typename Op2_t, unsigned Opcode, bool Commutative, typename... RecipeTys>
using TernaryRecipe_match
template<typename Op0_t, typename Op1_t, typename Op2_t, unsigned Opcode>
using TernaryVPInstruction_match
template<typename Op0_t, typename Op1_t, unsigned Opcode, bool Commutative = false>
using AllBinaryRecipe_match
template<typename Op0_t, typename Op1_t, typename Op2_t, typename Op3_t, unsigned Opcode, bool Commutative, typename... RecipeTys>
using Recipe4Op_match
template<typename Op0_t, typename Op1_t, typename Op2_t, typename Op3_t, unsigned Opcode>
using VPInstruction4Op_match
template<typename Op0_t, typename Op1_t>
using GEPLikeRecipe_match
template<typename Op0_t, typename Op1_t, typename Op2_t, unsigned Opcode>
using AllTernaryRecipe_match
template<typename Op0_t, typename Op1_t, typename Op2_t>
using VPScalarIVSteps_match
template<typename Op0_t, typename Op1_t, typename Op2_t>
using VPDerivedIV_match
Functions
template<typename Val, typename Pattern>
bool match (Val *V, const Pattern &P)
template<typename Pattern>
bool match (VPUser *U, const Pattern &P)
class_match< VPValue > m_VPValue ()
Match an arbitrary VPValue and ignore it.
specificval_ty m_Specific (const VPValue *VPV)
deferredval_ty m_Deferred (VPValue *const &V)
Like m_Specific(), but works if the specific value to match is determined as part of the same match() expression.
specific_intval< 0 > m_SpecificInt (uint64_t V)
specific_intval< 1 > m_False ()
specific_intval< 1 > m_True ()
int_pred_ty< is_all_ones > m_AllOnes ()
Match an integer or vector with all bits set.
template<typename LTy, typename RTy>
match_combine_or< LTy, RTy > m_CombineOr (const LTy &L, const RTy &R)
Combine two pattern matchers matching L || R.
template<typename LTy, typename RTy>
match_combine_and< LTy, RTy > m_CombineAnd (const LTy &L, const RTy &R)
Combine two pattern matchers matching L && R.
bind_ty< VPValue > m_VPValue (VPValue *&V)
Match a VPValue, capturing it if we match.
bind_ty< VPInstruction > m_VPInstruction (VPInstruction *&V)
Match a VPInstruction, capturing if we match.
ZeroOpVPInstruction_match< VPInstruction::BuildVector > m_BuildVector ()
BuildVector is matches only its opcode, w/o matching its operands as the number of operands is not fixed.
template<unsigned Opcode, typename Op0_t>
UnaryVPInstruction_match< Op0_t, Opcode > m_VPInstruction (const Op0_t &Op0)
template<unsigned Opcode, typename Op0_t, typename Op1_t>
BinaryVPInstruction_match< Op0_t, Op1_t, Opcode > m_VPInstruction (const Op0_t &Op0, const Op1_t &Op1)
template<unsigned Opcode, typename Op0_t, typename Op1_t, typename Op2_t>
TernaryVPInstruction_match< Op0_t, Op1_t, Op2_t, Opcode > m_VPInstruction (const Op0_t &Op0, const Op1_t &Op1, const Op2_t &Op2)
template<unsigned Opcode, typename Op0_t, typename Op1_t, typename Op2_t, typename Op3_t>
VPInstruction4Op_match< Op0_t, Op1_t, Op2_t, Op3_t, Opcode > m_VPInstruction (const Op0_t &Op0, const Op1_t &Op1, const Op2_t &Op2, const Op3_t &Op3)
template<typename Op0_t>
UnaryVPInstruction_match< Op0_t, Instruction::Freeze > m_Freeze (const Op0_t &Op0)
template<typename Op0_t>
UnaryVPInstruction_match< Op0_t, VPInstruction::BranchOnCond > m_BranchOnCond (const Op0_t &Op0)
template<typename Op0_t>
UnaryVPInstruction_match< Op0_t, VPInstruction::Broadcast > m_Broadcast (const Op0_t &Op0)
template<typename Op0_t, typename Op1_t>
BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::ActiveLaneMask > m_ActiveLaneMask (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t>
BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::BranchOnCount > m_BranchOnCount (const Op0_t &Op0, const Op1_t &Op1)
template<unsigned Opcode, typename Op0_t>
AllUnaryRecipe_match< Op0_t, Opcode > m_Unary (const Op0_t &Op0)
template<typename Op0_t>
AllUnaryRecipe_match< Op0_t, Instruction::Trunc > m_Trunc (const Op0_t &Op0)
template<typename Op0_t>
AllUnaryRecipe_match< Op0_t, Instruction::ZExt > m_ZExt (const Op0_t &Op0)
template<typename Op0_t>
AllUnaryRecipe_match< Op0_t, Instruction::SExt > m_SExt (const Op0_t &Op0)
template<typename Op0_t>
match_combine_or< AllUnaryRecipe_match< Op0_t, Instruction::ZExt >, AllUnaryRecipe_match< Op0_t, Instruction::SExt > > m_ZExtOrSExt (const Op0_t &Op0)
template<unsigned Opcode, typename Op0_t, typename Op1_t, bool Commutative = false>
AllBinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative > m_Binary (const Op0_t &Op0, const Op1_t &Op1)
template<unsigned Opcode, typename Op0_t, typename Op1_t>
AllBinaryRecipe_match< Op0_t, Op1_t, Opcode, true > m_c_Binary (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t>
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul > m_Mul (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t>
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul, true > m_c_Mul (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t, bool Commutative = false>
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, Commutative > m_BinaryOr (const Op0_t &Op0, const Op1_t &Op1)
Match a binary OR operation.
template<typename Op0_t, typename Op1_t>
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, true > m_c_BinaryOr (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t>
GEPLikeRecipe_match< Op0_t, Op1_t > m_GetElementPtr (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t, typename Op2_t>
AllTernaryRecipe_match< Op0_t, Op1_t, Op2_t, Instruction::Select > m_Select (const Op0_t &Op0, const Op1_t &Op1, const Op2_t &Op2)
template<typename Op0_t>
match_combine_or< UnaryVPInstruction_match< Op0_t, VPInstruction::Not >, AllBinaryRecipe_match< int_pred_ty< is_all_ones >, Op0_t, Instruction::Xor, true > > m_Not (const Op0_t &Op0)
template<typename Op0_t, typename Op1_t>
match_combine_or< BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::LogicalAnd >, AllTernaryRecipe_match< Op0_t, Op1_t, specific_intval< 1 >, Instruction::Select > > m_LogicalAnd (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t>
AllTernaryRecipe_match< Op0_t, specific_intval< 1 >, Op1_t, Instruction::Select > m_LogicalOr (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t, typename Op1_t, typename Op2_t>
VPScalarIVSteps_match< Op0_t, Op1_t, Op2_t > m_ScalarIVSteps (const Op0_t &Op0, const Op1_t &Op1, const Op2_t &Op2)
template<typename Op0_t, typename Op1_t, typename Op2_t>
VPDerivedIV_match< Op0_t, Op1_t, Op2_t > m_DerivedIV (const Op0_t &Op0, const Op1_t &Op1, const Op2_t &Op2)
template<unsigned OpI, typename Opnd_t>
Argument_match< Opnd_t > m_Argument (const Opnd_t &Op)
Match a call argument.
template<Intrinsic::ID IntrID>
IntrinsicID_match m_Intrinsic ()
Match intrinsic calls like this: m_Intrinsic<Intrinsic::fabs>(m_VPValue(X), ...)
template<Intrinsic::ID IntrID, typename T0>
m_Intrinsic_Ty< T0 >::Ty m_Intrinsic (const T0 &Op0)
template<Intrinsic::ID IntrID, typename T0, typename T1>
m_Intrinsic_Ty< T0, T1 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2>
m_Intrinsic_Ty< T0, T1, T2 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3>
m_Intrinsic_Ty< T0, T1, T2, T3 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2, const T3 &Op3)
Typedef Documentation
AllBinaryRecipe_match
template<typename Op0_t, typename Op1_t, unsigned Opcode, bool Commutative = false> using llvm::VPlanPatternMatch::AllBinaryRecipe_match
Initial value:
    BinaryRecipe_match<Op0_t, Op1_t, Opcode, Commutative, VPWidenRecipe,
                       VPReplicateRecipe, VPWidenCastRecipe, VPInstruction>
Definition at line 315 of file VPlanPatternMatch.h.
AllTernaryRecipe_match
template<typename Op0_t, typename Op1_t, typename Op2_t, unsigned Opcode> using llvm::VPlanPatternMatch::AllTernaryRecipe_match
Initial value:
    Recipe_match<std::tuple<Op0_t, Op1_t, Op2_t>, Opcode, false,
                 VPReplicateRecipe, VPInstruction, VPWidenSelectRecipe>
Definition at line 477 of file VPlanPatternMatch.h.
AllUnaryRecipe_match
template<typename Op0_t, unsigned Opcode> using llvm::VPlanPatternMatch::AllUnaryRecipe_match
Initial value:
    UnaryRecipe_match<Op0_t, Opcode, VPWidenRecipe, VPReplicateRecipe,
                      VPWidenCastRecipe, VPInstruction>
Definition at line 289 of file VPlanPatternMatch.h.
BinaryRecipe_match
template<typename Op0_t, typename Op1_t, unsigned Opcode, bool Commutative, typename... RecipeTys> using llvm::VPlanPatternMatch::BinaryRecipe_match
Initial value:
    Recipe_match<std::tuple<Op0_t, Op1_t>, Opcode, Commutative, RecipeTys...>
Definition at line 295 of file VPlanPatternMatch.h.
BinaryVPInstruction_match
template<typename Op0_t, typename Op1_t, unsigned Opcode> using llvm::VPlanPatternMatch::BinaryVPInstruction_match
Initial value:
    BinaryRecipe_match<Op0_t, Op1_t, Opcode,  false,
                       VPInstruction>
Definition at line 299 of file VPlanPatternMatch.h.
GEPLikeRecipe_match
template<typename Op0_t, typename Op1_t> using llvm::VPlanPatternMatch::GEPLikeRecipe_match
Initial value:
    BinaryRecipe_match<Op0_t, Op1_t, Instruction::GetElementPtr, false,
                       VPWidenRecipe, VPReplicateRecipe, VPWidenGEPRecipe,
                       VPInstruction>
Definition at line 465 of file VPlanPatternMatch.h.
Recipe4Op_match
template<typename Op0_t, typename Op1_t, typename Op2_t, typename Op3_t, unsigned Opcode, bool Commutative, typename... RecipeTys> using llvm::VPlanPatternMatch::Recipe4Op_match
Initial value:
 Recipe_match<std::tuple<Op0_t, Op1_t, Op2_t, Op3_t>,
                                     Opcode, Commutative, RecipeTys...>
Definition at line 346 of file VPlanPatternMatch.h.
specific_intval
template<unsigned Bitwidth = 0> using llvm::VPlanPatternMatch::specific_intval = int_pred_ty<is_specific_int, Bitwidth>
Definition at line 129 of file VPlanPatternMatch.h.
TernaryRecipe_match
template<typename Op0_t, typename Op1_t, typename Op2_t, unsigned Opcode, bool Commutative, typename... RecipeTys> using llvm::VPlanPatternMatch::TernaryRecipe_match
Initial value:
 Recipe_match<std::tuple<Op0_t, Op1_t, Op2_t>,
                                         Opcode, Commutative, RecipeTys...>
Definition at line 305 of file VPlanPatternMatch.h.
TernaryVPInstruction_match
template<typename Op0_t, typename Op1_t, typename Op2_t, unsigned Opcode> using llvm::VPlanPatternMatch::TernaryVPInstruction_match
Initial value:
    TernaryRecipe_match<Op0_t, Op1_t, Op2_t, Opcode,  false,
                        VPInstruction>
Definition at line 309 of file VPlanPatternMatch.h.
UnaryRecipe_match
template<typename Op0_t, unsigned Opcode, typename... RecipeTys> using llvm::VPlanPatternMatch::UnaryRecipe_match
Initial value:
    Recipe_match<std::tuple<Op0_t>, Opcode, false, RecipeTys...>
Definition at line 278 of file VPlanPatternMatch.h.
UnaryVPInstruction_match
template<typename Op0_t, unsigned Opcode> using llvm::VPlanPatternMatch::UnaryVPInstruction_match
Initial value:
    UnaryRecipe_match<Op0_t, Opcode, VPInstruction>
Definition at line 282 of file VPlanPatternMatch.h.
VPDerivedIV_match
template<typename Op0_t, typename Op1_t, typename Op2_t> using llvm::VPlanPatternMatch::VPDerivedIV_match
Initial value:
    Recipe_match<std::tuple<Op0_t, Op1_t, Op2_t>, 0, false, VPDerivedIVRecipe>
Definition at line 526 of file VPlanPatternMatch.h.
VPInstruction4Op_match
template<typename Op0_t, typename Op1_t, typename Op2_t, typename Op3_t, unsigned Opcode> using llvm::VPlanPatternMatch::VPInstruction4Op_match
Initial value:
    Recipe4Op_match<Op0_t, Op1_t, Op2_t, Op3_t, Opcode,  false,
                    VPInstruction>
Definition at line 351 of file VPlanPatternMatch.h.
VPScalarIVSteps_match
template<typename Op0_t, typename Op1_t, typename Op2_t> using llvm::VPlanPatternMatch::VPScalarIVSteps_match
Initial value:
    TernaryRecipe_match<Op0_t, Op1_t, Op2_t, 0, false, VPScalarIVStepsRecipe>
Definition at line 516 of file VPlanPatternMatch.h.
ZeroOpRecipe_match
template<unsigned Opcode, typename... RecipeTys> using llvm::VPlanPatternMatch::ZeroOpRecipe_match
Initial value:
    Recipe_match<std::tuple<>, Opcode, false, RecipeTys...>
Definition at line 274 of file VPlanPatternMatch.h.
ZeroOpVPInstruction_match
template<unsigned Opcode> using llvm::VPlanPatternMatch::ZeroOpVPInstruction_match = ZeroOpRecipe_match<Opcode, VPInstruction>
Definition at line 286 of file VPlanPatternMatch.h.
Function Documentation
m_ActiveLaneMask()
template<typename Op0_t, typename Op1_t> BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::ActiveLaneMask > llvm::VPlanPatternMatch::m_ActiveLaneMask (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 383 of file VPlanPatternMatch.h.
References m_VPInstruction().
Referenced by simplifyBranchConditionForVFAndUF().
m_AllOnes()
int_pred_ty< is_all_ones > llvm::VPlanPatternMatch::m_AllOnes () inline
Match an integer or vector with all bits set.
For vectors, this includes constants with undefined elements.
Definition at line 149 of file VPlanPatternMatch.h.
Referenced by m_Not().
m_Argument()
template<unsigned OpI, typename Opnd_t> Argument_match< Opnd_t > llvm::VPlanPatternMatch::m_Argument (const Opnd_t & Op) inline
Match a call argument.
Definition at line 557 of file VPlanPatternMatch.h.
Referenced by m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), and m_Intrinsic().
m_Binary()
template<unsigned Opcode, typename Op0_t, typename Op1_t, bool Commutative = false> AllBinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative > llvm::VPlanPatternMatch::m_Binary (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 424 of file VPlanPatternMatch.h.
Referenced by llvm::VPPartialReductionRecipe::computeCost(), getOptimizableIVOf(), isConditionTrueViaVFAndUF(), m_BinaryOr(), m_c_Mul(), m_Mul(), optimizeVectorInductionWidthForTCAndVFUF(), and llvm::VPlanTransforms::truncateToMinimalBitwidths().
m_BinaryOr()
template<typename Op0_t, typename Op1_t, bool Commutative = false> AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, Commutative > llvm::VPlanPatternMatch::m_BinaryOr (const Op0_t & Op0, const Op1_t & Op1) inline
Match a binary OR operation.
Note that while conceptually the operands can be matched commutatively, Commutative defaults to false in line with the IR-based pattern matching infrastructure. Use m_c_BinaryOr for a commutative version of the matcher.
Definition at line 453 of file VPlanPatternMatch.h.
References m_Binary().
Referenced by llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), and m_c_BinaryOr().
m_BranchOnCond()
template<typename Op0_t> UnaryVPInstruction_match< Op0_t, VPInstruction::BranchOnCond > llvm::VPlanPatternMatch::m_BranchOnCond (const Op0_t & Op0) inline
Definition at line 371 of file VPlanPatternMatch.h.
References m_VPInstruction().
Referenced by addCanonicalIVRecipes(), llvm::VPlanTransforms::handleUncountableEarlyExit(), hasConditionalTerminator(), removeBranchOnConst(), and simplifyBranchConditionForVFAndUF().
m_BranchOnCount()
template<typename Op0_t, typename Op1_t> BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::BranchOnCount > llvm::VPlanPatternMatch::m_BranchOnCount (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 389 of file VPlanPatternMatch.h.
References m_VPInstruction().
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions(), hasConditionalTerminator(), llvm::VPlanTransforms::narrowInterleaveGroups(), and simplifyBranchConditionForVFAndUF().
m_Broadcast()
template<typename Op0_t> UnaryVPInstruction_match< Op0_t, VPInstruction::Broadcast > llvm::VPlanPatternMatch::m_Broadcast (const Op0_t & Op0) inline
Definition at line 377 of file VPlanPatternMatch.h.
References m_VPInstruction().
Referenced by optimizeVectorInductionWidthForTCAndVFUF().
m_BuildVector()
ZeroOpVPInstruction_match< VPInstruction::BuildVector > llvm::VPlanPatternMatch::m_BuildVector () inline
BuildVector is matches only its opcode, w/o matching its operands as the number of operands is not fixed.
Definition at line 321 of file VPlanPatternMatch.h.
Referenced by cloneForLane(), llvm::VPTransformState::get(), and simplifyRecipe().
m_c_Binary()
template<unsigned Opcode, typename Op0_t, typename Op1_t> AllBinaryRecipe_match< Op0_t, Op1_t, Opcode, true > llvm::VPlanPatternMatch::m_c_Binary (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 430 of file VPlanPatternMatch.h.
Referenced by getOptimizableIVOf(), and m_Not().
m_c_BinaryOr()
template<typename Op0_t, typename Op1_t> AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, true > llvm::VPlanPatternMatch::m_c_BinaryOr (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 460 of file VPlanPatternMatch.h.
References m_BinaryOr().
Referenced by simplifyRecipe().
m_c_Mul()
template<typename Op0_t, typename Op1_t> AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul, true > llvm::VPlanPatternMatch::m_c_Mul (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 443 of file VPlanPatternMatch.h.
References m_Binary().
m_CombineAnd()
template<typename LTy, typename RTy> match_combine_and< LTy, RTy > llvm::VPlanPatternMatch::m_CombineAnd (const LTy & L, const RTy & R) inline
Combine two pattern matchers matching L && R.
Definition at line 188 of file VPlanPatternMatch.h.
Referenced by m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), and m_Intrinsic().
m_CombineOr()
template<typename LTy, typename RTy> match_combine_or< LTy, RTy > llvm::VPlanPatternMatch::m_CombineOr (const LTy & L, const RTy & R) inline
Combine two pattern matchers matching L || R.
Definition at line 182 of file VPlanPatternMatch.h.
Referenced by m_LogicalAnd(), m_Not(), and m_ZExtOrSExt().
m_Deferred()
deferredval_ty llvm::VPlanPatternMatch::m_Deferred (VPValue *const & V) inline
Like m_Specific(), but works if the specific value to match is determined as part of the same match() expression.
For example: m_Mul(m_VPValue(X), m_Specific(X)) is incorrect, because m_Specific() will bind X before the pattern match starts. m_Mul(m_VPValue(X), m_Deferred(X)) is correct, and will check against whichever value m_VPValue(X) populated.
Definition at line 85 of file VPlanPatternMatch.h.
m_DerivedIV()
template<typename Op0_t, typename Op1_t, typename Op2_t> VPDerivedIV_match< Op0_t, Op1_t, Op2_t > llvm::VPlanPatternMatch::m_DerivedIV (const Op0_t & Op0, const Op1_t & Op1, const Op2_t & Op2) inline
Definition at line 531 of file VPlanPatternMatch.h.
Referenced by simplifyRecipe().
m_False()
specific_intval< 1 > llvm::VPlanPatternMatch::m_False () inline
Definition at line 135 of file VPlanPatternMatch.h.
Referenced by m_LogicalAnd(), removeBranchOnConst(), and simplifyBlends().
m_Freeze()
template<typename Op0_t> UnaryVPInstruction_match< Op0_t, Instruction::Freeze > llvm::VPlanPatternMatch::m_Freeze (const Op0_t & Op0) inline
Definition at line 365 of file VPlanPatternMatch.h.
References m_VPInstruction().
m_GetElementPtr()
template<typename Op0_t, typename Op1_t> GEPLikeRecipe_match< Op0_t, Op1_t > llvm::VPlanPatternMatch::m_GetElementPtr (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 471 of file VPlanPatternMatch.h.
Referenced by getOptimizableIVOf().
m_Intrinsic() [1/5]
template<Intrinsic::ID IntrID> IntrinsicID_match llvm::VPlanPatternMatch::m_Intrinsic () inline
Match intrinsic calls like this: m_Intrinsic<Intrinsic::fabs>(m_VPValue(X), ...)
Definition at line 607 of file VPlanPatternMatch.h.
Referenced by m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), and m_Intrinsic().
m_Intrinsic() [2/5]
template<Intrinsic::ID IntrID, typename T0> m_Intrinsic_Ty< T0 >::Ty llvm::VPlanPatternMatch::m_Intrinsic (const T0 & Op0) inline
Definition at line 612 of file VPlanPatternMatch.h.
References m_Argument(), m_CombineAnd(), and m_Intrinsic().
m_Intrinsic() [3/5]
template<Intrinsic::ID IntrID, typename T0, typename T1> m_Intrinsic_Ty< T0, T1 >::Ty llvm::VPlanPatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1) inline
Definition at line 617 of file VPlanPatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), and T1.
m_Intrinsic() [4/5]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2> m_Intrinsic_Ty< T0, T1, T2 >::Ty llvm::VPlanPatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2) inline
Definition at line 624 of file VPlanPatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), and T1.
m_Intrinsic() [5/5]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3> m_Intrinsic_Ty< T0, T1, T2, T3 >::Ty llvm::VPlanPatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2, const T3 & Op3) inline
Definition at line 631 of file VPlanPatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), and T1.
m_LogicalAnd()
template<typename Op0_t, typename Op1_t> match_combine_or< BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::LogicalAnd >, AllTernaryRecipe_match< Op0_t, Op1_t, specific_intval< 1 >, Instruction::Select > > llvm::VPlanPatternMatch::m_LogicalAnd (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 502 of file VPlanPatternMatch.h.
References m_CombineOr(), m_False(), m_Select(), and m_VPInstruction().
m_LogicalOr()
template<typename Op0_t, typename Op1_t> AllTernaryRecipe_match< Op0_t, specific_intval< 1 >, Op1_t, Instruction::Select > llvm::VPlanPatternMatch::m_LogicalOr (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 511 of file VPlanPatternMatch.h.
References m_Select(), and m_True().
m_Mul()
template<typename Op0_t, typename Op1_t> AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul > llvm::VPlanPatternMatch::m_Mul (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 436 of file VPlanPatternMatch.h.
References m_Binary().
m_Not()
template<typename Op0_t> match_combine_or< UnaryVPInstruction_match< Op0_t, VPInstruction::Not >, AllBinaryRecipe_match< int_pred_ty< is_all_ones >, Op0_t, Instruction::Xor, true > > llvm::VPlanPatternMatch::m_Not (const Op0_t & Op0) inline
Definition at line 492 of file VPlanPatternMatch.h.
References m_AllOnes(), m_c_Binary(), m_CombineOr(), and m_VPInstruction().
m_ScalarIVSteps()
template<typename Op0_t, typename Op1_t, typename Op2_t> VPScalarIVSteps_match< Op0_t, Op1_t, Op2_t > llvm::VPlanPatternMatch::m_ScalarIVSteps (const Op0_t & Op0, const Op1_t & Op1, const Op2_t & Op2) inline
Definition at line 521 of file VPlanPatternMatch.h.
m_Select()
template<typename Op0_t, typename Op1_t, typename Op2_t> AllTernaryRecipe_match< Op0_t, Op1_t, Op2_t, Instruction::Select > llvm::VPlanPatternMatch::m_Select (const Op0_t & Op0, const Op1_t & Op1, const Op2_t & Op2) inline
Definition at line 483 of file VPlanPatternMatch.h.
Referenced by m_LogicalAnd(), and m_LogicalOr().
m_SExt()
template<typename Op0_t> AllUnaryRecipe_match< Op0_t, Instruction::SExt > llvm::VPlanPatternMatch::m_SExt (const Op0_t & Op0) inline
Definition at line 410 of file VPlanPatternMatch.h.
References m_Unary().
Referenced by m_ZExtOrSExt().
m_Specific()
specificval_ty llvm::VPlanPatternMatch::m_Specific (const VPValue * VPV) inline
Definition at line 67 of file VPlanPatternMatch.h.
m_SpecificInt()
specific_intval< 0 > llvm::VPlanPatternMatch::m_SpecificInt (uint64_t V) inline
Definition at line 131 of file VPlanPatternMatch.h.
m_True()
specific_intval< 1 > llvm::VPlanPatternMatch::m_True () inline
Definition at line 139 of file VPlanPatternMatch.h.
Referenced by m_LogicalOr(), removeBranchOnConst(), and simplifyRecipe().
m_Trunc()
template<typename Op0_t> AllUnaryRecipe_match< Op0_t, Instruction::Trunc > llvm::VPlanPatternMatch::m_Trunc (const Op0_t & Op0) inline
Definition at line 400 of file VPlanPatternMatch.h.
References m_Unary().
m_Unary()
template<unsigned Opcode, typename Op0_t> AllUnaryRecipe_match< Op0_t, Opcode > llvm::VPlanPatternMatch::m_Unary (const Op0_t & Op0) inline
Definition at line 394 of file VPlanPatternMatch.h.
Referenced by m_SExt(), m_Trunc(), and m_ZExt().
m_VPInstruction() [1/5]
template<unsigned Opcode, typename Op0_t> UnaryVPInstruction_match< Op0_t, Opcode > llvm::VPlanPatternMatch::m_VPInstruction (const Op0_t & Op0) inline
Definition at line 327 of file VPlanPatternMatch.h.
m_VPInstruction() [2/5]
template<unsigned Opcode, typename Op0_t, typename Op1_t> BinaryVPInstruction_match< Op0_t, Op1_t, Opcode > llvm::VPlanPatternMatch::m_VPInstruction (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 333 of file VPlanPatternMatch.h.
m_VPInstruction() [3/5]
template<unsigned Opcode, typename Op0_t, typename Op1_t, typename Op2_t> TernaryVPInstruction_match< Op0_t, Op1_t, Op2_t, Opcode > llvm::VPlanPatternMatch::m_VPInstruction (const Op0_t & Op0, const Op1_t & Op1, const Op2_t & Op2) inline
Definition at line 339 of file VPlanPatternMatch.h.
m_VPInstruction() [4/5]
template<unsigned Opcode, typename Op0_t, typename Op1_t, typename Op2_t, typename Op3_t> VPInstruction4Op_match< Op0_t, Op1_t, Op2_t, Op3_t, Opcode > llvm::VPlanPatternMatch::m_VPInstruction (const Op0_t & Op0, const Op1_t & Op1, const Op2_t & Op2, const Op3_t & Op3) inline
Definition at line 358 of file VPlanPatternMatch.h.
m_VPInstruction() [5/5]
bind_ty< VPInstruction > llvm::VPlanPatternMatch::m_VPInstruction (VPInstruction *& V) inline
Match a VPInstruction, capturing if we match.
Definition at line 196 of file VPlanPatternMatch.h.
Referenced by llvm::VPlanTransforms::convertToConcreteRecipes(), m_ActiveLaneMask(), m_BranchOnCond(), m_BranchOnCount(), m_Broadcast(), m_Freeze(), m_LogicalAnd(), m_Not(), optimizeEarlyExitInductionUser(), optimizeLatchExitInductionUser(), preparePlanForMainVectorLoop(), simplifyRecipe(), and transformRecipestoEVLRecipes().
m_VPValue() [1/2]
class_match< VPValue > llvm::VPlanPatternMatch::m_VPValue () inline
Match an arbitrary VPValue and ignore it.
Definition at line 42 of file VPlanPatternMatch.h.
Referenced by addCanonicalIVRecipes(), llvm::VPPartialReductionRecipe::computeCost(), llvm::VPWidenSelectRecipe::computeCost(), llvm::VPlanTransforms::convertToConcreteRecipes(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), fixReductionScalarResumeWhenVectorizingEpilog(), getOptimizableIVOf(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleUncountableEarlyExit(), hasConditionalTerminator(), isConditionTrueViaVFAndUF(), llvm::VPlanTransforms::narrowInterleaveGroups(), optimizeEarlyExitInductionUser(), optimizeLatchExitInductionUser(), optimizeMaskToEVL(), removeBranchOnConst(), simplifyBlends(), simplifyBranchConditionForVFAndUF(), simplifyRecipe(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), tryToMatchAndCreateExtendedReduction(), and tryToMatchAndCreateMulAccumulateReduction().
m_VPValue() [2/2]
bind_ty< VPValue > llvm::VPlanPatternMatch::m_VPValue (VPValue *& V) inline
Match a VPValue, capturing it if we match.
Definition at line 193 of file VPlanPatternMatch.h.
m_ZExt()
template<typename Op0_t> AllUnaryRecipe_match< Op0_t, Instruction::ZExt > llvm::VPlanPatternMatch::m_ZExt (const Op0_t & Op0) inline
Definition at line 405 of file VPlanPatternMatch.h.
References m_Unary().
Referenced by m_ZExtOrSExt().
m_ZExtOrSExt()
template<typename Op0_t> match_combine_or< AllUnaryRecipe_match< Op0_t, Instruction::ZExt >, AllUnaryRecipe_match< Op0_t, Instruction::SExt > > llvm::VPlanPatternMatch::m_ZExtOrSExt (const Op0_t & Op0) inline
Definition at line 417 of file VPlanPatternMatch.h.
References m_CombineOr(), m_SExt(), and m_ZExt().
Referenced by fixReductionScalarResumeWhenVectorizingEpilog().
match() [1/2]
template<typename Val, typename Pattern> bool llvm::VPlanPatternMatch::match (Val * V, const Pattern & P)
Definition at line 28 of file VPlanPatternMatch.h.
References P.
Referenced by match().
match() [2/2]
template<typename Pattern> bool llvm::VPlanPatternMatch::match (VPUser * U, const Pattern & P)
Definition at line 32 of file VPlanPatternMatch.h.
References llvm::dyn_cast(), match(), and P.