LLVM: llvm::RISCVLoadFPImm Namespace Reference
llvm::RISCVLoadFPImm Namespace Reference
Functions
float getFPImm (unsigned Imm)
int getLoadFPImm (APFloat FPImm)
getLoadFPImm - Return a 5-bit binary encoding of the floating-point immediate value.
Function Documentation
getFPImm()
float llvm::RISCVLoadFPImm::getFPImm (unsigned Imm)
Definition at line 236 of file RISCVBaseInfo.cpp.
References assert(), llvm::bit_cast(), I, and llvm::LoadFP32ImmArr.
Referenced by llvm::RISCVInstPrinter::printFPImmOperand().
getLoadFPImm()
int llvm::RISCVLoadFPImm::getLoadFPImm (APFloat FPImm)
getLoadFPImm - Return a 5-bit binary encoding of the floating-point immediate value.
If the value cannot be represented as a 5-bit binary encoding, then return -1.
Definition at line 192 of file RISCVBaseInfo.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convert(), llvm::APFloat::getSemantics(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEsingle(), llvm::APFloat::isNegative(), llvm::APFloat::isSmallestNormalized(), llvm::LoadFP32ImmArr, llvm::lower_bound(), llvm::APFloatBase::opOK, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by llvm::RISCVTargetLowering::getLegalZfaFPImm().