LLVM: llvm::ir2vec Namespace Reference
llvm::ir2vec Namespace Reference
Classes
class Embedder
Embedder provides the interface to generate embeddings (vector representations) for instructions, basic blocks, and functions.
struct Embedding
Embedding is a datatype that wraps std::vector<double>.
class SymbolicEmbedder
Class for computing the Symbolic embeddings of IR2Vec.
class Vocabulary
Class for storing and accessing the IR2Vec vocabulary.
Typedefs
using InstEmbeddingsMap = DenseMap<const Instruction *, Embedding>
using BBEmbeddingsMap = DenseMap<const BasicBlock *, Embedding>
Functions
cl::opt< float > OpcWeight ("ir2vec-opc-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for opcode embeddings"), cl::cat(IR2VecCategory))
cl::opt< float > TypeWeight ("ir2vec-type-weight", cl::Optional, cl::init(0.5), cl::desc("Weight for type embeddings"), cl::cat(IR2VecCategory))
cl::opt< float > ArgWeight ("ir2vec-arg-weight", cl::Optional, cl::init(0.2), cl::desc("Weight for argument embeddings"), cl::cat(IR2VecCategory))
Variables
LLVM_ABI cl::opt< float > OpcWeight
LLVM_ABI cl::opt< float > TypeWeight
LLVM_ABI cl::opt< float > ArgWeight
static cl::OptionCategory IR2VecCategory ("IR2Vec Options")
static cl::opt< std::string > VocabFile ("ir2vec-vocab-path", cl::Optional, cl::desc("Path to the vocabulary file for IR2Vec"), cl::init(""), cl::cat(IR2VecCategory))
Typedef Documentation
BBEmbeddingsMap
using llvm::ir2vec::BBEmbeddingsMap = DenseMap<const BasicBlock *, Embedding>
Definition at line 131 of file IR2Vec.h.
InstEmbeddingsMap
using llvm::ir2vec::InstEmbeddingsMap = DenseMap<const Instruction *, Embedding>
Definition at line 130 of file IR2Vec.h.
Function Documentation
ArgWeight()
cl::opt< float > llvm::ir2vec::ArgWeight ("ir2vec-arg-weight" , cl::Optional , cl::init(0.2) , cl::desc("Weight for argument embeddings") , cl::cat(IR2VecCategory))
References llvm::cl::init(), IR2VecCategory, and llvm::cl::Optional.
OpcWeight()
cl::opt< float > llvm::ir2vec::OpcWeight ("ir2vec-opc-weight" , cl::Optional , cl::init(1.0) , cl::desc("Weight for opcode embeddings") , cl::cat(IR2VecCategory))
References llvm::cl::init(), IR2VecCategory, and llvm::cl::Optional.
TypeWeight()
cl::opt< float > llvm::ir2vec::TypeWeight ("ir2vec-type-weight" , cl::Optional , cl::init(0.5) , cl::desc("Weight for type embeddings") , cl::cat(IR2VecCategory))
References llvm::cl::init(), IR2VecCategory, and llvm::cl::Optional.
Variable Documentation
ArgWeight
cl::opt< float > llvm::ir2vec::ArgWeight("ir2vec-arg-weight", cl::Optional, cl::init(0.2), cl::desc("Weight for argument embeddings"), cl::cat(IR2VecCategory))
Referenced by llvm::IR2VecVocabAnalysis::run().
IR2VecCategory
cl::OptionCategory llvm::ir2vec::IR2VecCategory("IR2Vec Options") ("IR2Vec Options") static
Referenced by ArgWeight(), OpcWeight(), and TypeWeight().
OpcWeight
cl::opt< float > llvm::ir2vec::OpcWeight("ir2vec-opc-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for opcode embeddings"), cl::cat(IR2VecCategory))
Referenced by llvm::IR2VecVocabAnalysis::run().
TypeWeight
cl::opt< float > llvm::ir2vec::TypeWeight("ir2vec-type-weight", cl::Optional, cl::init(0.5), cl::desc("Weight for type embeddings"), cl::cat(IR2VecCategory))
Referenced by llvm::IR2VecVocabAnalysis::run().
VocabFile
cl::opt< std::string > llvm::ir2vec::VocabFile("ir2vec-vocab-path", cl::Optional, cl::desc("Path to the vocabulary file for IR2Vec"), cl::init(""), cl::cat(IR2VecCategory)) ("ir2vec-vocab-path" , cl::Optional , cl::desc("Path to the vocabulary file for IR2Vec") , cl::init("") , cl::cat(IR2VecCategory)) static
Referenced by llvm::IR2VecVocabAnalysis::run().