LLVM: llvm::dxbc::PSV Namespace Reference
llvm::dxbc::PSV Namespace Reference
Namespaces
namespace v0
namespace v1
namespace v2
namespace v3
Classes
struct ResourceFlags
Enumerations
enum class SemanticKind : uint8_t
enum class ComponentType : uint8_t
enum class InterpolationMode : uint8_t
enum class ResourceType : uint32_t
enum class ResourceKind : uint32_t
Functions
LLVM_ABI ArrayRef< EnumEntry< SemanticKind > > getSemanticKinds ()
LLVM_ABI ArrayRef< EnumEntry< ComponentType > > getComponentTypes ()
LLVM_ABI ArrayRef< EnumEntry< InterpolationMode > > getInterpolationModes ()
LLVM_ABI ArrayRef< EnumEntry< ResourceType > > getResourceTypes ()
LLVM_ABI ArrayRef< EnumEntry< ResourceKind > > getResourceKinds ()
Enumeration Type Documentation
ComponentType
enum class llvm::dxbc::PSV::ComponentType : uint8_t strong
Definition at line 390 of file DXContainer.h.
InterpolationMode
enum class llvm::dxbc::PSV::InterpolationMode : uint8_t strong
Definition at line 397 of file DXContainer.h.
ResourceKind
enum class llvm::dxbc::PSV::ResourceKind : uint32_t strong
Definition at line 411 of file DXContainer.h.
ResourceType
enum class llvm::dxbc::PSV::ResourceType : uint32_t strong
Definition at line 404 of file DXContainer.h.
SemanticKind
enum class llvm::dxbc::PSV::SemanticKind : uint8_t strong
Definition at line 383 of file DXContainer.h.
Function Documentation
getComponentTypes()
ArrayRef< EnumEntry< PSV::ComponentType > > llvm::dxbc::PSV::getComponentTypes ()
Definition at line 168 of file DXContainer.cpp.
References llvm::ArrayRef(), and ComponentTypeNames.
getInterpolationModes()
ArrayRef< EnumEntry< PSV::InterpolationMode > > llvm::dxbc::PSV::getInterpolationModes ()
Definition at line 178 of file DXContainer.cpp.
References llvm::ArrayRef(), and InterpolationModeNames.
getResourceKinds()
ArrayRef< EnumEntry< PSV::ResourceKind > > llvm::dxbc::PSV::getResourceKinds ()
Definition at line 198 of file DXContainer.cpp.
References llvm::ArrayRef(), and ResourceKindNames.
getResourceTypes()
ArrayRef< EnumEntry< PSV::ResourceType > > llvm::dxbc::PSV::getResourceTypes ()
Definition at line 188 of file DXContainer.cpp.
References llvm::ArrayRef(), and ResourceTypeNames.
getSemanticKinds()
ArrayRef< EnumEntry< PSV::SemanticKind > > llvm::dxbc::PSV::getSemanticKinds ()
Definition at line 158 of file DXContainer.cpp.
References llvm::ArrayRef(), and SemanticKindNames.