LLVM: llvm::directive Namespace Reference
llvm::directive Namespace Reference
Classes
struct Spelling
struct VersionRange
Functions
LLVM_ABI StringRef FindName (llvm::iterator_range< const Spelling * >, unsigned Version)
Function Documentation
FindName()
llvm::StringRef llvm::directive::FindName (llvm::iterator_range< const Spelling * > Range, unsigned Version)
Definition at line 22 of file Spelling.cpp.
References assert(), Contains(), llvm::isInt(), Range, and llvm::Version.