LLVM: llvm::orc Namespace Reference
llvm::orc Namespace Reference
Namespaces
namespace detail
namespace rt
namespace rt_alt
namespace rt_bootstrap
namespace shared
namespace SimpleRemoteEPCDefaultBootstrapSymbolNames
namespace tpctypes
Classes
class AbsoluteSymbolsMaterializationUnit
A MaterializationUnit implementation for pre-existing absolute symbols.
class AllocGroup
A pair of memory protections and allocation policies.
class AllocGroupSmallMap
A specialized small-map for AllocGroups.
class AsynchronousSymbolQuery
A symbol query that returns results via a callback when results are ready.
class BasicIRLayerMaterializationUnit
MaterializationUnit that materializes modules by calling the 'emit' method on the given IRLayer.
class BasicObjectLayerMaterializationUnit
Materializes the given object file (represented by a MemoryBuffer instance) by calling 'emit' on the given ObjectLayer.
class BlockFreqQuery
class CAPIDefinitionGenerator
class COFFImportFileScanner
class COFFPlatform
Mediates between COFF initialization and ExecutionSession state.
class COFFVCRuntimeBootstrapper
Bootstraps the vc runtime within jitdylibs.
class CompileOnDemandLayer
class ConcurrentIRCompiler
A thread-safe version of SimpleCompiler.
class CtorDtorIterator
This iterator provides a convenient way to iterate over the elements of an llvm.global_ctors/llvm.global_dtors instance.
class CtorDtorRunner
class DebugInfoPreservationPlugin
class DebugObject
The plugin creates a debug object from when JITLink starts processing the corresponding LinkGraph.
class DebugObjectManagerPlugin
Creates and manages DebugObjects for JITLink artifacts.
class DebugObjectRegistrar
Abstract interface for registering debug objects in the executor process.
class DebugObjectSection
class DefinitionGenerator
Definition generators can be attached to JITDylibs to generate new definitions for otherwise unresolved symbols during lookup.
class DLLImportDefinitionGenerator
A utility class to create COFF dllimport GOT symbols (__imp_*) and PLT stubs.
class DumpObjects
A function object that can be used as an ObjectTransformLayer transform to dump object files to disk at a specified path.
class DuplicateDefinition
class DylibManager
class DynamicLibrarySearchGenerator
A utility class to expose symbols found via dlsym to the JIT.
class EHFrameRegistrationPlugin
Adds AllocationActions to register and deregister eh-frame sections in the absence of native Platform support.
class ELFDebugObject
The current implementation of ELFDebugObject replicates the approach used in RuntimeDyld: It patches executable and data section headers in the given object buffer with load-addresses of their corresponding sections in target memory.
class ELFDebugObjectSection
class ELFNixPlatform
Mediates between ELFNix initialization and ExecutionSession state.
struct ELFPerObjectSectionsToRegister
class EPCDebugObjectRegistrar
Use ExecutorProcessControl to register debug objects locally or in a remote executor process.
class EPCDynamicLibrarySearchGenerator
class EPCGenericDylibManager
class EPCGenericJITLinkMemoryManager
class EPCGenericMemoryAccess
class EPCGenericRTDyldMemoryManager
Remote-mapped RuntimeDyld-compatible memory manager.
class EPCIndirectionUtils
Provides ExecutorProcessControl based indirect stubs, trampoline pool and lazy call through manager.
class EPCIndirectionUtilsAccess
class ExecutionSession
An ExecutionSession represents a running JIT program.
class ExecutorAddr
Represents an address in the executor process.
struct ExecutorAddrRange
Represents an address range in the exceutor process.
class ExecutorBootstrapService
class ExecutorNativePlatform
Configure the LLJIT instance to use the ORC runtime and the detected native target for the executor.
class ExecutorProcessControl
ExecutorProcessControl supports interaction with a JIT target process.
class ExecutorSymbolDef
Represents a defining location for a JIT symbol.
class FailedToMaterialize
Used to notify a JITDylib that the given set of symbols failed to materialize.
class FDSimpleRemoteEPCTransport
Uses read/write on FileDescriptors for transport.
class ForceLoadMachOArchiveMembers
For use with StaticLibraryDefinitionGenerators.
struct FunctionPairKeyEqual
struct FunctionPairKeyHash
class GDBJITDebugInfoRegistrationPlugin
For each object containing debug info, installs JITLink passes to synthesize a debug object and then register it via the GDB JIT-registration interface.
class GenericNamedTask
Base class for generic tasks.
class GenericNamedTaskImpl
Generic task implementation.
class IdleTask
IdleTask can be used as the basis for low-priority tasks, e.g.
class ImplSymbolMap
struct IndirectStubsAllocationSizes
class IndirectStubsManager
Base class for managing collections of named indirect stubs.
class InPlaceTaskDispatcher
Runs all tasks on the current thread.
class InProcessMemoryAccess
class InProcessMemoryMapper
class InProgressFullLookupState
class InProgressLookupFlagsState
class InProgressLookupState
class IRCompileLayer
class IRLayer
Interface for layers that accept LLVM IR.
class IRMaterializationUnit
IRMaterializationUnit is a convenient base class for MaterializationUnits wrapping LLVM IR.
class IRPartitionLayer
A layer that breaks up IR modules into smaller submodules that only contains looked up symbols.
class IRSpeculationLayer
class IRSymbolMapper
Maps IR global values to their linker symbol names / flags.
class IRTransformLayer
A layer that applies a transform to emitted modules.
class ItaniumCXAAtExitSupport
An interface for Itanium __cxa_atexit interposer implementations.
class JITCompileCallbackManager
Target-independent base class for compile callback management.
class JITDylib
Represents a JIT'd dynamic library.
class JITLinkRedirectableSymbolManager
class JITLinkReentryTrampolines
Produces trampolines on request using JITLink.
class JITSymbolNotFound
class JITTargetMachineBuilder
A utility class for building TargetMachines for JITs.
class JITTargetMachineBuilderPrinter
class LazyCallThroughManager
Manages a set of 'lazy call-through' trampolines.
class LazyObjectLinkingLayer
LazyObjectLinkingLayer is an adapter for ObjectLinkingLayer that builds lazy reexports for all function symbols in objects that are/ added to defer linking until the first call to a function defined in the object.
class LazyReexportsManager
class LazyReexportsMaterializationUnit
A materialization unit that builds lazy re-exports.
class LinkGraphLayer
class LinkGraphLinkingLayer
LinkGraphLinkingLayer links LinkGraphs into the Executor using JITLink.
class LinkGraphMaterializationUnit
MaterializationUnit for wrapping LinkGraphs.
class LLJIT
A pre-fabricated ORC JIT stack that can serve as an alternative to MCJIT.
class LLJITBuilder
Constructs LLJIT instances.
class LLJITBuilderSetters
class LLJITBuilderState
class LLLazyJIT
An extended version of LLJIT that supports lazy function-at-a-time compilation of LLVM IR.
class LLLazyJITBuilder
Constructs LLLazyJIT instances.
class LLLazyJITBuilderSetters
class LLLazyJITBuilderState
class LoadAndLinkDynLibrary
class LocalCXXRuntimeOverrides
class LocalCXXRuntimeOverridesBase
Support class for static dtor execution.
class LocalIndirectStubsInfo
class LocalIndirectStubsManager
IndirectStubsManager implementation for the host architecture, e.g.
class LocalJITCompileCallbackManager
Manage compile callbacks for in-process JITs.
class LocalLazyCallThroughManager
A lazy call-through manager that builds trampolines in the current process.
class LocalTrampolinePool
A trampoline pool for trampolines within the current process.
class LookupState
Wraps state for a lookup-in-progress.
class LookupTask
Lookups are usually run on the current thread, but in some cases they may be run as tasks, e.g.
struct MachO64LE
class MachOBuilder
struct MachOBuilderDylibLoadCommand
struct MachOBuilderLoadCommand
struct MachOBuilderLoadCommand< MachO::LC_ID_DYLIB >
struct MachOBuilderLoadCommand< MachO::LC_LOAD_DYLIB >
struct MachOBuilderLoadCommand< MachO::LC_LOAD_WEAK_DYLIB >
struct MachOBuilderLoadCommand< MachO::LC_RPATH >
struct MachOBuilderLoadCommandBase
Base type for MachOBuilder load command wrappers.
struct MachOBuilderLoadCommandImplBase
MachOBuilder load command wrapper type.
struct MachOHeaderInfo
class MachOPlatform
Mediates between MachO initialization and ExecutionSession state.
class MangleAndInterner
Mangles symbol names then uniques them in the context of an ExecutionSession.
class MapperJITLinkMemoryManager
class MaterializationResponsibility
Tracks responsibility for materialization, and mediates interactions between MaterializationUnits and JDs.
class MaterializationTask
A materialization task.
class MaterializationUnit
A MaterializationUnit represents a set of symbol definitions that can be materialized as a group, or individually discarded (when overriding definitions are encountered).
class MemoryAccess
APIs for manipulating memory in the target process.
class MemoryMapper
Manages mapping, content transfer and protections for JIT memory.
class MissingSymbolDefinitions
Errors of this type should be returned if a module fails to include definitions that are claimed by the module's associated MaterializationResponsibility.
class NonOwningSymbolStringPtr
Non-owning SymbolStringPool entry pointer.
class ObjectLayer
Interface for Layers that accept object files.
class ObjectLinkingLayer
An ObjectLayer implementation built on JITLink.
class ObjectTransformLayer
class OrcAArch64
class OrcGenericABI
Generic ORC ABI support.
class OrcI386
I386 support.
class OrcLoongArch64
class OrcMips32_Base
class OrcMips32Be
class OrcMips32Le
class OrcMips64
class ORCPlatformSupport
A Platform-support class that implements initialize / deinitialize by forwarding to ORC runtime dlopen / dlclose operations.
class OrcRiscv64
class OrcV2CAPIHelper
class OrcX86_64_Base
X86_64 code that's common to all ABIs.
class OrcX86_64_SysV
X86_64 support for SysV ABI (Linux, MacOSX).
class OrcX86_64_Win32
X86_64 support for Win32.
class PartitioningIRMaterializationUnit
struct PerfJITCodeLoadRecord
struct PerfJITCodeUnwindingInfoRecord
struct PerfJITDebugEntry
struct PerfJITDebugInfoRecord
struct PerfJITRecordBatch
struct PerfJITRecordPrefix
class PerfSupportPlugin
Log perf jitdump events for each object (see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/Documentation/jitdump-specification.txt).
class Platform
Platforms set up standard symbols and mediate interactions between dynamic initializers (e.g.
class RedirectableMaterializationUnit
RedirectableMaterializationUnit materializes redirectable symbol by invoking RedirectableSymbolManager::emitRedirectableSymbols.
class RedirectableSymbolManager
Base class for managing redirectable symbols in which a call gets redirected to another symbol in runtime.
class RedirectionManager
Base class for performing redirection of call to symbol to another symbol in runtime.
class ReexportsGenerator
ReexportsGenerator can be used with JITDylib::addGenerator to automatically re-export a subset of the source JITDylib's symbols in the target.
class ReExportsMaterializationUnit
A materialization unit for symbol aliases.
struct RemoteSymbolLookup
struct RemoteSymbolLookupSetElement
class ReOptimizeLayer
class ResourceManager
Listens for ResourceTracker operations.
class ResourceTracker
API to remove / transfer ownership of JIT resources.
class ResourceTrackerDefunct
class RTDyldObjectLinkingLayer
struct RuntimeFunction
class SectCreateMaterializationUnit
class SelfExecutorProcessControl
A ExecutorProcessControl implementation targeting the current process.
class SequenceBBQuery
class SharedMemoryMapper
class SimpleCompiler
Simple compile functor: Takes a single IR module and returns an ObjectFile.
class SimpleLazyReexportsSpeculator
class SimpleMachOHeaderMU
class SimpleRemoteEPC
struct SimpleRemoteEPCExecutorInfo
class SimpleRemoteEPCServer
A simple EPC server implementation.
class SimpleRemoteEPCTransport
class SimpleRemoteEPCTransportClient
class SpeculateQuery
class Speculator
class StaticInitGVIterator
This iterator provides a convenient way to iterate over GlobalValues that have initialization effects.
class StaticLibraryDefinitionGenerator
A utility class to expose symbols from a static library.
struct SymbolAliasMapEntry
struct SymbolDependenceGroup
A set of symbols and the their dependencies.
class SymbolInstance
A definition of a Symbol within a JITDylib.
class SymbolLinkagePromoter
Promotes private symbols to global hidden, and renames to prevent clashes with other promoted symbols.
class SymbolLookupSet
A set of symbols to look up, each associated with a SymbolLookupFlags value.
class SymbolsCouldNotBeRemoved
Used to notify clients that a set of symbols could not be removed.
class SymbolsNotFound
Used to notify clients when symbols can not be found during a lookup.
class SymbolStringPool
String pool for symbol names used by the JIT.
class SymbolStringPoolEntryUnsafe
Provides unsafe access to ownership operations on SymbolStringPtr.
class SymbolStringPtr
Pointer to a pooled string representing a symbol name.
class SymbolStringPtrBase
Base class for both owning and non-owning symbol-string ptrs.
class Task
Represents an abstract task for ORC to run.
class TaskDispatcher
Abstract base for classes that dispatch ORC Tasks.
class ThreadSafeContext
An LLVMContext together with an associated mutex that can be used to lock the context to prevent concurrent access by other threads.
class ThreadSafeModule
An LLVM Module together with a shared ThreadSafeContext.
class TMOwningSimpleCompiler
A SimpleCompiler that owns its TargetMachine.
class TrampolinePool
Base class for pools of compiler re-entry trampolines.
class UnexpectedSymbolDefinitions
Errors of this type should be returned if a module contains definitions for symbols that are not claimed by the module's associated MaterializationResponsibility.
class UnsatisfiedSymbolDependencies
Used to report failure due to unsatisfiable symbol dependencies.
class UnwindInfoManager
class UnwindInfoRegistrationPlugin
struct VTuneMethodBatch
struct VTuneMethodInfo
class VTuneSupportPlugin
Typedefs
using ResourceTrackerSP = IntrusiveRefCntPtr<ResourceTracker>
using JITDylibSP = IntrusiveRefCntPtr<JITDylib>
using ResourceKey = uintptr_t
using JITDylibSearchOrder
A list of (JITDylib*, JITDylibLookupFlags) pairs to be used as a search order during symbol lookup.
using SymbolAliasMap = DenseMap<SymbolStringPtr, SymbolAliasMapEntry>
A map of Symbols to (Symbol, Flags) pairs.
using SymbolsResolvedCallback = unique_function<void(Expected<SymbolMap>)>
Callback to notify client that symbols have been resolved.
using RegisterDependenciesFunction
Callback to register the dependencies for a given query.
using SymbolNameSet = DenseSet<SymbolStringPtr>
A set of symbol names (represented by SymbolStringPtrs for.
using SymbolNameVector = std::vector<SymbolStringPtr>
A vector of symbol names.
using SymbolMap = DenseMap<SymbolStringPtr, ExecutorSymbolDef>
A map from symbol names (as SymbolStringPtrs) to JITSymbols (address/flags pairs).
using SymbolFlagsMap = DenseMap<SymbolStringPtr, JITSymbolFlags>
A map from symbol names (as SymbolStringPtrs) to JITSymbolFlags.
using SymbolDependenceMap = DenseMap<JITDylib *, SymbolNameSet>
A map from JITDylibs to sets of symbols.
using ELFNixJITDylibDepInfo = std::vector<ExecutorAddr>
using ELFNixJITDylibDepInfoMap
using DeferredRuntimeFnMap
using ExecutorAddrDiff = uint64_t
using SimpleRemoteEPCArgBytesVector = SmallVector<char, 128>
using RemoteSymbolLookupSet = std::vector<RemoteSymbolLookupSetElement>
using VTuneLineTable = std::vector<std::pair<unsigned, unsigned>>
using VTuneMethodTable = std::vector<VTuneMethodInfo>
using VTuneStringTable = std::vector<std::string>
using VTuneUnloadedMethodIDs = SmallVector<std::pair<uint64_t, uint64_t>>
using GVPredicate = std::function<bool(const GlobalValue &)>
using GVModifier = std::function<void(GlobalValue &)>
using BaseT = RTTIExtends<ObjectTransformLayer, ObjectLayer>
Enumerations
enum class JITDylibLookupFlags { MatchExportedSymbolsOnly , MatchAllSymbols }
Lookup flags that apply to each dylib in the search order for a lookup.
enum class SymbolLookupFlags { RequiredSymbol , WeaklyReferencedSymbol }
Lookup flags that apply to each symbol in a lookup.
enum class LookupKind { Static , DLSym }
Describes the kind of lookup being performed.
enum class SymbolState : uint8_t {
Invalid , NeverSearched , Materializing , Resolved ,
Emitted , Ready = 0x3f
}
Represents the state that a symbol has reached during materialization.
enum class LinkableFileKind { Archive , RelocatableObject }
enum class LoadArchives { Never , Allowed , Required }
enum class MemProt { None = 0 , Read = 1U << 0 , Write = 1U << 1 , Exec = 1U << 2 }
Describes Read/Write/Exec permissions for memory.
enum class MemLifetime { Standard , Finalize , NoAlloc }
Describes a memory lifetime policy for memory to be allocated by a JITLinkMemoryManager.
enum class OrcErrorCode : int {
UnknownORCError = 1 , DuplicateDefinition , JITSymbolNotFound , RemoteAllocatorDoesNotExist ,
RemoteAllocatorIdAlreadyInUse , RemoteMProtectAddrUnrecognized , RemoteIndirectStubsOwnerDoesNotExist , RemoteIndirectStubsOwnerIdAlreadyInUse ,
RPCConnectionClosed , RPCCouldNotNegotiateFunction , RPCResponseAbandoned , UnexpectedRPCCall ,
UnexpectedRPCResponse , UnknownErrorCodeFromRemote , UnknownResourceHandle , MissingSymbolDefinitions ,
UnexpectedSymbolDefinitions
}
enum class PerfJITRecordType {
JIT_CODE_LOAD = 0 , JIT_CODE_MOVE = 1 , JIT_CODE_DEBUG_INFO = 2 , JIT_CODE_CLOSE = 3 ,
JIT_CODE_UNWINDING_INFO = 4 , JIT_CODE_MAX
}
enum class SimpleRemoteEPCOpcode : uint8_t {
Setup , Hangup , Result , CallWrapper ,
LastOpC = CallWrapper
}
enum DebugObjectFlags : int { ReportFinalSectionLoadAddresses = 1 << 0 , HasDebugSections = 1 << 1 }
Functions
std::unique_ptr< AbsoluteSymbolsMaterializationUnit > absoluteSymbols (SymbolMap Symbols)
Create an AbsoluteSymbolsMaterializationUnit with the given symbols.
LLVM_ABI IRSymbolMapper::ManglingOptions irManglingOptionsFromTargetOptions (const TargetOptions &Opts)
JITDylibSearchOrder makeJITDylibSearchOrder (ArrayRef< JITDylib * > JDs, JITDylibLookupFlags Flags=JITDylibLookupFlags::MatchExportedSymbolsOnly)
Convenience function for creating a search order from an ArrayRef of JITDylib*, all with the same flags.
std::unique_ptr< ReExportsMaterializationUnit > symbolAliases (SymbolAliasMap Aliases)
Create a ReExportsMaterializationUnit with the given aliases.
std::unique_ptr< ReExportsMaterializationUnit > reexports (JITDylib &SourceJD, SymbolAliasMap Aliases, JITDylibLookupFlags SourceJDLookupFlags=JITDylibLookupFlags::MatchExportedSymbolsOnly)
Create a materialization unit for re-exporting symbols from another JITDylib with alternative names/flags.
LLVM_ABI Expected< SymbolAliasMap > buildSimpleReexportsAliasMap (JITDylib &SourceJD, const SymbolNameSet &Symbols)
Build a SymbolAliasMap for the common case where you want to re-export symbols from another JITDylib with the same linkage/flags.
LLVM_ABI Error enableDebuggerSupport (LLJIT &J)
LLVM_ABI Error preserveDebugSections (jitlink::LinkGraph &G)
LLVM_ABI Expected< std::pair< std::unique_ptr< DWARFContext >, StringMap< std::unique_ptr< MemoryBuffer > > > > createDWARFContext (jitlink::LinkGraph &G)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolNameSet &Symbols)
Render a SymbolNameSet.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolNameVector &Symbols)
Render a SymbolNameVector.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, ArrayRef< SymbolStringPtr > Symbols)
Render an array of SymbolStringPtrs.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const JITSymbolFlags &Flags)
Render JITSymbolFlags.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolFlagsMap::value_type &KV)
Render a SymbolFlagsMap entry.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolMap::value_type &KV)
Render a SymbolMap entry.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolFlagsMap &SymbolFlags)
Render a SymbolFlagsMap.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolMap &Symbols)
Render a SymbolMap.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolDependenceMap::value_type &KV)
Render a SymbolDependenceMap entry.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolDependenceMap &Deps)
Render a SymbolDependendeMap.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const MaterializationUnit &MU)
Render a MaterializationUnit.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const JITDylibLookupFlags &JDLookupFlags)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolLookupFlags &LookupFlags)
Render a SymbolLookupFlags instance.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolLookupSet::value_type &KV)
Render a SymbolLookupSet entry.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolLookupSet &LookupSet)
Render a SymbolLookupSet.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const JITDylibSearchOrder &SearchOrder)
Render a JITDylibSearchOrder.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolAliasMap &Aliases)
Render a SymbolAliasMap.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolState &S)
Render a SymbolState.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const LookupKind &K)
Render a LookupKind.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolStringPool &SSP)
Dump a SymbolStringPool. Useful for debugging dangling-pointer crashes.
LLVM_ABI Expected< std::unique_ptr< EPCDebugObjectRegistrar > > createJITLoaderGDBRegistrar (ExecutionSession &ES, std::optional< ExecutorAddr > RegistrationFunctionDylib=std::nullopt)
Create a ExecutorProcessControl-based DebugObjectRegistrar that emits debug objects to the GDB JIT interface.
Error setUpInProcessLCTMReentryViaEPCIU (EPCIndirectionUtils &EPCIU)
This will call writeResolver on the given EPCIndirectionUtils instance to set up re-entry via a function that will directly return the trampoline landing address.
LLVM_ABI iterator_range< CtorDtorIterator > getConstructors (const Module &M)
Create an iterator range over the entries of the llvm.global_ctors array.
LLVM_ABI iterator_range< CtorDtorIterator > getDestructors (const Module &M)
Create an iterator range over the entries of the llvm.global_ctors array.
iterator_range< StaticInitGVIterator > getStaticInitGVs (Module &M)
Create an iterator range over the GlobalValues that contribute to static initialization.
LLVM_ABI Expected< SymbolNameSet > getDylibInterfaceFromDylib (ExecutionSession &ES, Twine Path)
Returns a SymbolNameSet containing the exported symbols defined in the given dylib.
LLVM_ABI Expected< SymbolNameSet > getDylibInterfaceFromTapiFile (ExecutionSession &ES, Twine Path)
Returns a SymbolNameSet containing the exported symbols defined in the relevant slice of the TapiUniversal file.
LLVM_ABI Expected< SymbolNameSet > getDylibInterface (ExecutionSession &ES, Twine Path)
Returns a SymbolNameSet containing the exported symbols defined in the relevant slice of the given file, which may be either a dylib or a tapi file.
LLVM_ABI Expected< std::unique_ptr< JITCompileCallbackManager > > createLocalCompileCallbackManager (const Triple &T, ExecutionSession &ES, ExecutorAddr ErrorHandlerAddress)
Create a local compile callback manager.
LLVM_ABI std::function< std::unique_ptr< IndirectStubsManager >()> createLocalIndirectStubsManagerBuilder (const Triple &T)
Create a local indirect stubs manager builder.
LLVM_ABI Constant * createIRTypedAddress (FunctionType &FT, ExecutorAddr Addr)
Build a function pointer of FunctionType with the given constant address.
LLVM_ABI GlobalVariable * createImplPointer (PointerType &PT, Module &M, const Twine &Name, Constant *Initializer)
Create a function pointer with the given type, name, and initializer in the given Module.
LLVM_ABI void makeStub (Function &F, Value &ImplPointer)
Turn a function declaration into a stub function that makes an indirect call using the given function pointer.
LLVM_ABI Function * cloneFunctionDecl (Module &Dst, const Function &F, ValueToValueMapTy *VMap=nullptr)
Clone a function declaration into a new module.
LLVM_ABI GlobalVariable * cloneGlobalVariableDecl (Module &Dst, const GlobalVariable &GV, ValueToValueMapTy *VMap=nullptr)
Clone a global variable declaration into a new module.
LLVM_ABI GlobalAlias * cloneGlobalAliasDecl (Module &Dst, const GlobalAlias &OrigA, ValueToValueMapTy &VMap)
Clone a global alias declaration into a new module.
LLVM_ABI Error addFunctionPointerRelocationsToCurrentSymbol (jitlink::Symbol &Sym, jitlink::LinkGraph &G, MCDisassembler &Disassembler, MCInstrAnalysis &MIA)
Introduce relocations to Sym in its own definition if there are any pointers formed via PC-relative address that do not already have a relocation.
LLVM_ABI Expected< std::unique_ptr< LazyReexportsManager > > createJITLinkLazyReexportsManager (ObjectLinkingLayer &ObjLinkingLayer, RedirectableSymbolManager &RSMgr, JITDylib &PlatformJD, LazyReexportsManager::Listener *L=nullptr)
LLVM_ABI Expected< std::unique_ptr< LazyCallThroughManager > > createLocalLazyCallThroughManager (const Triple &T, ExecutionSession &ES, ExecutorAddr ErrorHandlerAddr)
Create a LocalLazyCallThroughManager from the given triple and execution session.
std::unique_ptr< LazyReexportsMaterializationUnit > lazyReexports (LazyCallThroughManager &LCTManager, RedirectableSymbolManager &RSManager, JITDylib &SourceJD, SymbolAliasMap CallableAliases, ImplSymbolMap *SrcJDLoc=nullptr)
Define lazy-reexports based on the given SymbolAliasMap.
std::unique_ptr< MaterializationUnit > lazyReexports (LazyReexportsManager &LRM, SymbolAliasMap Reexports)
Define lazy-reexports based on the given SymbolAliasMap.
LLVM_ABI Error setUpOrcPlatformManually (LLJIT &J)
Configure the LLJIT instance to use orc runtime support.
LLVM_ABI Expected< JITDylibSP > setUpGenericLLVMIRPlatform (LLJIT &J)
Configure the LLJIT instance to scrape modules for llvm.global_ctors and llvm.global_dtors variables and (if present) build initialization and deinitialization functions.
LLVM_ABI Expected< JITDylibSP > setUpInactivePlatform (LLJIT &J)
Configure the LLJIT instance to disable platform support explicitly.
LLVM_ABI Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > loadLinkableFile (StringRef Path, const Triple &TT, LoadArchives LA, std::optional< StringRef > IdentifierOverride=std::nullopt)
Create a MemoryBuffer covering the "linkable" part of the given path.
LLVM_ABI void lookupAndRecordAddrs (unique_function< void(Error)> OnRecorded, ExecutionSession &ES, LookupKind K, const JITDylibSearchOrder &SearchOrder, std::vector< std::pair< SymbolStringPtr, ExecutorAddr * > > Pairs, SymbolLookupFlags LookupFlags=SymbolLookupFlags::RequiredSymbol)
Record addresses of the given symbols in the given ExecutorAddrs.
LLVM_ABI Error lookupAndRecordAddrs (ExecutionSession &ES, LookupKind K, const JITDylibSearchOrder &SearchOrder, std::vector< std::pair< SymbolStringPtr, ExecutorAddr * > > Pairs, SymbolLookupFlags LookupFlags=SymbolLookupFlags::RequiredSymbol)
Record addresses of the given symbols in the given ExecutorAddrs.
LLVM_ABI Error lookupAndRecordAddrs (ExecutorProcessControl &EPC, tpctypes::DylibHandle H, std::vector< std::pair< SymbolStringPtr, ExecutorAddr * > > Pairs, SymbolLookupFlags LookupFlags=SymbolLookupFlags::RequiredSymbol)
Record addresses of given symbols in the given ExecutorAddrs.
LLVM_ABI Error checkMachORelocatableObject (MemoryBufferRef Obj, const Triple &TT, bool ObjIsSlice)
Check that the given buffer contains a MachO object file compatible with the given triple.
LLVM_ABI Expected< std::unique_ptr< MemoryBuffer > > checkMachORelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple &TT, bool ObjIsSlice)
Check that the given buffer contains a MachO object file compatible with the given triple.
LLVM_ABI Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > loadMachOLinkableFile (StringRef Path, const Triple &TT, LoadArchives LA, std::optional< StringRef > IdentifierOverride=std::nullopt)
Load a relocatable object compatible with TT from Path.
LLVM_ABI Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > loadLinkableSliceFromMachOUniversalBinary (sys::fs::file_t FD, std::unique_ptr< MemoryBuffer > UBBuf, const Triple &TT, LoadArchives LA, StringRef UBPath, StringRef Identifier)
Load a compatible relocatable object (if available) from a MachO universal binary.
LLVM_ABI Expected< std::pair< size_t, size_t > > getMachOSliceRangeForTriple (object::MachOUniversalBinary &UB, const Triple &TT)
Utility for identifying the file-slice compatible with TT in a universal binary.
LLVM_ABI Expected< std::pair< size_t, size_t > > getMachOSliceRangeForTriple (MemoryBufferRef UBBuf, const Triple &TT)
Utility for identifying the file-slice compatible with TT in a universal binary.
template<typename MachOStruct>
size_t writeMachOStruct (MutableArrayRef< char > Buf, size_t Offset, MachOStruct S, bool SwapStruct)
LLVM_ABI MachOHeaderInfo getMachOHeaderInfoFromTriple (const Triple &TT)
LLVM_ABI void addInitSymbol (MaterializationUnit::Interface &I, ExecutionSession &ES, StringRef ObjFileName)
Adds an initializer symbol to the given MU interface.
LLVM_ABI Expected< MaterializationUnit::Interface > getObjectFileInterface (ExecutionSession &ES, MemoryBufferRef ObjBuffer)
Returns a MaterializationUnit::Interface for the object file contained in the given buffer, or an error if the buffer does not contain a valid object file.
template<typename ORCABI>
IndirectStubsAllocationSizes getIndirectStubsBlockSizes (unsigned MinStubs, unsigned RoundToMultipleOf=0)
ExecutorAddrDiff operator- (const ExecutorAddr &LHS, const ExecutorAddr &RHS)
Subtracting two addresses yields an offset.
ExecutorAddr operator+ (const ExecutorAddr &LHS, const ExecutorAddrDiff &RHS)
Adding an offset and an address yields an address.
ExecutorAddr operator+ (const ExecutorAddrDiff &LHS, const ExecutorAddr &RHS)
Adding an address and an offset yields an address.
ExecutorAddr operator- (const ExecutorAddr &LHS, const ExecutorAddrDiff &RHS)
Subtracting an offset from an address yields an address.
ExecutorAddrDiff operator% (const ExecutorAddr &LHS, const ExecutorAddrDiff &RHS)
Taking the modulus of an address and a diff yields a diff.
raw_ostream & operator<< (raw_ostream &OS, const ExecutorAddr &A)
raw_ostream & operator<< (raw_ostream &OS, const ExecutorAddrRange &R)
LLVM_ABI bool isMachOInitializerSection (StringRef SegName, StringRef SecName)
LLVM_ABI bool isMachOInitializerSection (StringRef QualifiedName)
raw_ostream & operator<< (raw_ostream &OS, MemProt MP)
Print a MemProt as an RWX triple.
sys::Memory::ProtectionFlags toSysMemoryProtectionFlags (MemProt MP)
Convert a MemProt value to a corresponding sys::Memory::ProtectionFlags value.
MemProt fromSysMemoryProtectionFlags (sys::Memory::ProtectionFlags PF)
Convert a sys::Memory::ProtectionFlags value to a corresponding MemProt value.
raw_ostream & operator<< (raw_ostream &OS, MemLifetime MLP)
Print a MemDeallocPolicy.
raw_ostream & operator<< (raw_ostream &OS, AllocGroup AG)
Print an AllocGroup.
LLVM_ABI bool isELFInitializerSection (StringRef SecName)
LLVM_ABI bool isCOFFInitializerSection (StringRef Name)
LLVM_ABI std::error_code orcError (OrcErrorCode ErrCode)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const SymbolStringPtrBase &Sym)
LLVM_ABI void addDefaultBootstrapValuesForHostProcess (StringMap< std::vector< char > > &BootstrapMap, StringMap< ExecutorAddr > &BootstrapSymbols)
LLVM_ABI Error registerEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Register frames in the given eh-frame section with libunwind.
LLVM_ABI Error deregisterEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Unregister frames in the given eh-frame section with libunwind.
LLVM_ABI int runAsMain (int(*Main)(int, char *[]), ArrayRef< std::string > Args, std::optional< StringRef > ProgramName=std::nullopt)
Run a main function, returning the result.
LLVM_ABI int runAsVoidFunction (int(*Func)(void))
LLVM_ABI int runAsIntFunction (int(*Func)(int), int Arg)
template<typename FnT>
std::unique_ptr< GenericNamedTask > makeGenericNamedTask (FnT &&Fn, std::string Desc)
Create a generic named task from a std::string description.
template<typename FnT>
std::unique_ptr< GenericNamedTask > makeGenericNamedTask (FnT &&Fn, const char *Desc=nullptr)
Create a generic named task from a const char * description.
LLVM_ABI ThreadSafeModule cloneToContext (const ThreadSafeModule &TSMW, ThreadSafeContext TSCtx, GVPredicate ShouldCloneDef=GVPredicate(), GVModifier UpdateClonedDefSource=GVModifier())
Clones teh given module onto the given context.
LLVM_ABI ThreadSafeModule cloneToNewContext (const ThreadSafeModule &TSMW, GVPredicate ShouldCloneDef=GVPredicate(), GVModifier UpdateClonedDefSource=GVModifier())
Clones the given module on to a new context.
static void addAliases (ExecutionSession &ES, SymbolAliasMap &Aliases, ArrayRef< std::pair< const char *, const char * > > AL)
Expected< SymbolAliasMap > buildSimpleReexportsAliasMap (JITDylib &SourceJD, SymbolNameSet Symbols)
static bool isDwarfSection (StringRef SectionName)
static Expected< std::unique_ptr< DebugObject > > createDebugObjectFromBuffer (ExecutionSession &ES, LinkGraph &G, JITLinkContext &Ctx, MemoryBufferRef ObjBuffer)
Creates a debug object based on the input object file from ObjectLinkingLayerJITLinkContext.
raw_ostream & operator<< (raw_ostream &OS, const ExecutorSymbolDef &Sym)
static void addAliases (ExecutionSession &ES, SymbolAliasMap &Aliases, ArrayRef< std::pair< const char *, const char * > > AL)
static JITTargetAddress reentry (JITTargetAddress LCTMAddr, JITTargetAddress TrampolineAddr)
LLVM_ATTRIBUTE_USED void linkComponents ()
static Expected< std::unique_ptr< MemoryBuffer > > checkCOFFRelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple &TT)
static Expected< std::unique_ptr< MemoryBuffer > > checkXCOFFRelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple &TT)
static Expected< std::unique_ptr< MemoryBuffer > > checkELFRelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple &TT)
static std::string objDesc (const MemoryBufferRef &Obj, const Triple &TT, bool ObjIsSlice)
template<typename HeaderType>
static Error checkMachORelocatableObject (MemoryBufferRef Obj, bool SwapEndianness, const Triple &TT, bool ObjIsSlice)
Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > loadMachORelocatableObject (StringRef Path, const Triple &TT, LoadArchives LA, std::optional< StringRef > IdentifierOverride)
static void addAliases (ExecutionSession &ES, SymbolAliasMap &Aliases, ArrayRef< std::pair< const char *, const char * > > AL)
template<typename MachOTraits>
jitlink::Block & createHeaderBlock (MachOPlatform &MOP, const MachOPlatform::HeaderOptions &Opts, JITDylib &JD, jitlink::LinkGraph &G, jitlink::Section &HeaderSection)
static Expected< MaterializationUnit::Interface > getMachOObjectFileSymbolInfo (ExecutionSession &ES, const object::MachOObjectFile &Obj)
static Expected< MaterializationUnit::Interface > getELFObjectFileSymbolInfo (ExecutionSession &ES, const object::ELFObjectFileBase &Obj)
static Expected< MaterializationUnit::Interface > getCOFFObjectFileSymbolInfo (ExecutionSession &ES, const object::COFFObjectFile &Obj)
Expected< MaterializationUnit::Interface > getXCOFFObjectFileSymbolInfo (ExecutionSession &ES, const object::ObjectFile &Obj)
Expected< MaterializationUnit::Interface > getGenericObjectFileSymbolInfo (ExecutionSession &ES, const object::ObjectFile &Obj)
static Error makeUnexpectedEOFError ()
static void lookupSymbolsAsyncHelper (EPCGenericDylibManager &DylibMgr, ArrayRef< DylibManager::LookupRequest > Request, std::vector< tpctypes::LookupResult > Result, DylibManager::SymbolLookupCompleteFn Complete)
Async helper to chain together calls to DylibMgr::lookupAsync to fulfill all all the requests.
void __register_frame (const void *)
void __deregister_frame (const void *)
Error registerFrameWrapper (const void *P)
Error deregisterFrameWrapper (const void *P)
template<typename HandleFDEFn>
Error walkLibunwindEHFrameSection (const char *const SectionStart, size_t SectionSize, HandleFDEFn HandleFDE)
Variables
LLVM_ABI RegisterDependenciesFunction NoDependenciesToRegister
This can be used as the value for a RegisterDependenciesFunction if there are no dependants to register with.
LLVM_ABI StringRef MachODataCommonSectionName = "__DATA,__common"
LLVM_ABI StringRef MachODataDataSectionName = "__DATA,__data"
LLVM_ABI StringRef MachOEHFrameSectionName = "__TEXT,__eh_frame"
LLVM_ABI StringRef MachOCompactUnwindSectionName = "__LD,__compact_unwind"
LLVM_ABI StringRef MachOCStringSectionName = "__TEXT,__cstring"
LLVM_ABI StringRef MachOModInitFuncSectionName = "__DATA,__mod_init_func"
LLVM_ABI StringRef MachOObjCCatListSectionName = "__DATA,__objc_catlist"
LLVM_ABI StringRef MachOObjCCatList2SectionName = "__DATA,__objc_catlist2"
LLVM_ABI StringRef MachOObjCClassListSectionName = "__DATA,__objc_classlist"
LLVM_ABI StringRef MachOObjCClassNameSectionName = "__TEXT,__objc_classname"
LLVM_ABI StringRef MachOObjCClassRefsSectionName = "__DATA,__objc_classrefs"
LLVM_ABI StringRef MachOObjCConstSectionName = "__DATA,__objc_const"
LLVM_ABI StringRef MachOObjCDataSectionName = "__DATA,__objc_data"
LLVM_ABI StringRef MachOObjCImageInfoSectionName = "__DATA,__objc_imageinfo"
LLVM_ABI StringRef MachOObjCMethNameSectionName = "__TEXT,__objc_methname"
LLVM_ABI StringRef MachOObjCMethTypeSectionName = "__TEXT,__objc_methtype"
LLVM_ABI StringRef MachOObjCNLCatListSectionName = "__DATA,__objc_nlcatlist"
LLVM_ABI StringRef MachOObjCNLClassListSectionName = "__DATA,__objc_nlclslist"
LLVM_ABI StringRef MachOObjCProtoListSectionName = "__DATA,__objc_protolist"
LLVM_ABI StringRef MachOObjCProtoRefsSectionName = "__DATA,__objc_protorefs"
LLVM_ABI StringRef MachOObjCSelRefsSectionName = "__DATA,__objc_selrefs"
LLVM_ABI StringRef MachOSwift5ProtoSectionName = "__TEXT,__swift5_proto"
LLVM_ABI StringRef MachOSwift5ProtosSectionName = "__TEXT,__swift5_protos"
LLVM_ABI StringRef MachOSwift5TypesSectionName = "__TEXT,__swift5_types"
LLVM_ABI StringRef MachOSwift5TypeRefSectionName = "__TEXT,__swift5_typeref"
LLVM_ABI StringRef MachOSwift5FieldMetadataSectionName = "__TEXT,__swift5_fieldmd"
LLVM_ABI StringRef MachOSwift5EntrySectionName = "__TEXT,__swift5_entry"
LLVM_ABI StringRef MachOTextTextSectionName = "__TEXT,__text"
LLVM_ABI StringRef MachOThreadBSSSectionName = "__DATA,__thread_bss"
LLVM_ABI StringRef MachOThreadDataSectionName = "__DATA,__thread_data"
LLVM_ABI StringRef MachOThreadVarsSectionName = "__DATA,__thread_vars"
LLVM_ABI StringRef MachOUnwindInfoSectionName = "__TEXT,__unwind_info"
LLVM_ABI StringRef MachOInitSectionNames [22]
LLVM_ABI StringRef ELFEHFrameSectionName = ".eh_frame"
LLVM_ABI StringRef ELFInitArrayFuncSectionName = ".init_array"
LLVM_ABI StringRef ELFInitFuncSectionName = ".init"
LLVM_ABI StringRef ELFFiniArrayFuncSectionName = ".fini_array"
LLVM_ABI StringRef ELFFiniFuncSectionName = ".fini"
LLVM_ABI StringRef ELFCtorArrayFuncSectionName = ".ctors"
LLVM_ABI StringRef ELFDtorArrayFuncSectionName = ".dtors"
LLVM_ABI StringRef ELFInitSectionNames [3]
LLVM_ABI StringRef ELFThreadBSSSectionName = ".tbss"
LLVM_ABI StringRef ELFThreadDataSectionName = ".tdata"
static const std::set< StringRef > DwarfSectionNames
static const char * AddFnName
static const char * RemoveFnName
static std::unique_ptr< UnwindInfoManager > Instance
static int(* RemoveFindDynamicUnwindSections)(void *) = nullptr
Typedef Documentation
BaseT
typedef RTTIExtends< RTDyldObjectLinkingLayer, ObjectLayer > llvm::orc::BaseT = RTTIExtends<ObjectTransformLayer, ObjectLayer>
Definition at line 17 of file ObjectTransformLayer.cpp.
DeferredRuntimeFnMap
using llvm::orc::DeferredRuntimeFnMap
Initial value:
 std::unordered_map<
    std::pair<RuntimeFunction *, RuntimeFunction *>,
    SmallVector<std::pair<shared::WrapperFunctionCall::ArgDataBufferType,
                          shared::WrapperFunctionCall::ArgDataBufferType>>,
    FunctionPairKeyHash, FunctionPairKeyEqual>
Definition at line 62 of file ELFNixPlatform.h.
ELFNixJITDylibDepInfo
using llvm::orc::ELFNixJITDylibDepInfo = std::vector<ExecutorAddr>
Definition at line 36 of file ELFNixPlatform.h.
ELFNixJITDylibDepInfoMap
using llvm::orc::ELFNixJITDylibDepInfoMap
Initial value:
    std::vector<std::pair<ExecutorAddr, ELFNixJITDylibDepInfo>>
Definition at line 37 of file ELFNixPlatform.h.
ExecutorAddrDiff
using llvm::orc::ExecutorAddrDiff = uint64_t
Definition at line 31 of file ExecutorAddress.h.
GVModifier
using llvm::orc::GVModifier = std::function<void(GlobalValue &)>
Definition at line 154 of file ThreadSafeModule.h.
GVPredicate
using llvm::orc::GVPredicate = std::function<bool(const GlobalValue &)>
Definition at line 153 of file ThreadSafeModule.h.
JITDylibSearchOrder
using llvm::orc::JITDylibSearchOrder
Initial value:
    std::vector<std::pair<JITDylib *, JITDylibLookupFlags>>
A list of (JITDylib*, JITDylibLookupFlags) pairs to be used as a search order during symbol lookup.
Definition at line 173 of file Core.h.
JITDylibSP
using llvm::orc::JITDylibSP = IntrusiveRefCntPtr<JITDylib>
Definition at line 53 of file Core.h.
RegisterDependenciesFunction
using llvm::orc::RegisterDependenciesFunction
Initial value:
    std::function<void(const SymbolDependenceMap &)>
Callback to register the dependencies for a given query.
Definition at line 419 of file Core.h.
RemoteSymbolLookupSet
using llvm::orc::RemoteSymbolLookupSet = std::vector<RemoteSymbolLookupSetElement>
Definition at line 148 of file SimpleRemoteEPCUtils.h.
ResourceKey
using llvm::orc::ResourceKey = uintptr_t
Definition at line 75 of file Core.h.
ResourceTrackerSP
using llvm::orc::ResourceTrackerSP = IntrusiveRefCntPtr<ResourceTracker>
Definition at line 52 of file Core.h.
SimpleRemoteEPCArgBytesVector
using llvm::orc::SimpleRemoteEPCArgBytesVector = SmallVector<char, 128>
Definition at line 53 of file SimpleRemoteEPCUtils.h.
SymbolAliasMap
using llvm::orc::SymbolAliasMap = DenseMap<SymbolStringPtr, SymbolAliasMapEntry>
A map of Symbols to (Symbol, Flags) pairs.
Definition at line 413 of file Core.h.
SymbolDependenceMap
using llvm::orc::SymbolDependenceMap = DenseMap<JITDylib *, SymbolNameSet>
A map from JITDylibs to sets of symbols.
Definition at line 43 of file CoreContainers.h.
SymbolFlagsMap
using llvm::orc::SymbolFlagsMap = DenseMap<SymbolStringPtr, JITSymbolFlags>
A map from symbol names (as SymbolStringPtrs) to JITSymbolFlags.
Definition at line 40 of file CoreContainers.h.
SymbolMap
using llvm::orc::SymbolMap = DenseMap<SymbolStringPtr, ExecutorSymbolDef>
A map from symbol names (as SymbolStringPtrs) to JITSymbols (address/flags pairs).
Definition at line 37 of file CoreContainers.h.
SymbolNameSet
using llvm::orc::SymbolNameSet = DenseSet<SymbolStringPtr>
A set of symbol names (represented by SymbolStringPtrs for.
Definition at line 30 of file CoreContainers.h.
SymbolNameVector
using llvm::orc::SymbolNameVector = std::vector<SymbolStringPtr>
A vector of symbol names.
Definition at line 33 of file CoreContainers.h.
SymbolsResolvedCallback
using llvm::orc::SymbolsResolvedCallback = unique_function<void(Expected<SymbolMap>)>
Callback to notify client that symbols have been resolved.
Definition at line 416 of file Core.h.
VTuneLineTable
using llvm::orc::VTuneLineTable = std::vector<std::pair<unsigned, unsigned>>
Definition at line 23 of file VTuneSharedStructs.h.
VTuneMethodTable
using llvm::orc::VTuneMethodTable = std::vector<VTuneMethodInfo>
Definition at line 42 of file VTuneSharedStructs.h.
VTuneStringTable
using llvm::orc::VTuneStringTable = std::vector<std::string>
Definition at line 43 of file VTuneSharedStructs.h.
VTuneUnloadedMethodIDs
using llvm::orc::VTuneUnloadedMethodIDs = SmallVector<std::pair<uint64_t, uint64_t>>
Definition at line 50 of file VTuneSharedStructs.h.
Enumeration Type Documentation
DebugObjectFlags
enum llvm::orc::DebugObjectFlags : int
Enumerator
ReportFinalSectionLoadAddresses
HasDebugSections
Definition at line 101 of file DebugObjectManagerPlugin.cpp.
JITDylibLookupFlags
enum class llvm::orc::JITDylibLookupFlags strong
Lookup flags that apply to each dylib in the search order for a lookup.
If MatchHiddenSymbolsOnly is used (the default) for a given dylib, then only symbols in that Dylib's interface will be searched. If MatchHiddenSymbols is used then symbols with hidden visibility will match as well.
Enumerator
MatchExportedSymbolsOnly
MatchAllSymbols
Definition at line 147 of file Core.h.
LinkableFileKind
enum class llvm::orc::LinkableFileKind strong
Enumerator
Archive
RelocatableObject
Definition at line 29 of file LoadLinkableFile.h.
LoadArchives
enum class llvm::orc::LoadArchives strong
Enumerator
Never
Allowed
Required
Definition at line 31 of file LoadLinkableFile.h.
LookupKind
enum class llvm::orc::LookupKind strong
Describes the kind of lookup being performed.
The lookup kind is passed to symbol generators (if they're invoked) to help them determine what definitions to generate.
Static – Lookup is being performed as-if at static link time (e.g. generators representing static archives should pull in new definitions).
DLSym – Lookup is being performed as-if at runtime (e.g. generators representing static archives should not pull in new definitions).
Enumerator
Static
DLSym
Definition at line 169 of file Core.h.
MemLifetime
enum class llvm::orc::MemLifetime strong
Describes a memory lifetime policy for memory to be allocated by a JITLinkMemoryManager.
All memory allocated by a call to JITLinkMemoryManager::allocate should be deallocated if a call is made to JITLinkMemoryManager::InFlightAllocation::abandon. The policies below apply to finalized allocations.
Enumerator
Standard
Standard memory should be allocated by the allocator and then deallocated when the deallocate method is called for the finalized allocation.
Finalize
Finalize memory should be allocated by the allocator, and then be overwritten and deallocated after all finalization functions have been run.
NoAlloc
NoAlloc memory should not be allocated by the JITLinkMemoryManager at all.
It is used for sections that don't need to be transferred to the executor process, typically metadata sections.
Definition at line 75 of file MemoryFlags.h.
MemProt
enum class llvm::orc::MemProt strong
Describes Read/Write/Exec permissions for memory.
Enumerator
None
Read
Write
Exec
Definition at line 27 of file MemoryFlags.h.
OrcErrorCode
enum class llvm::orc::OrcErrorCode : int strong
Enumerator
UnknownORCError
DuplicateDefinition
JITSymbolNotFound
RemoteAllocatorDoesNotExist
RemoteAllocatorIdAlreadyInUse
RemoteMProtectAddrUnrecognized
RemoteIndirectStubsOwnerDoesNotExist
RemoteIndirectStubsOwnerIdAlreadyInUse
RPCConnectionClosed
RPCCouldNotNegotiateFunction
RPCResponseAbandoned
UnexpectedRPCCall
UnexpectedRPCResponse
UnknownErrorCodeFromRemote
UnknownResourceHandle
MissingSymbolDefinitions
UnexpectedSymbolDefinitions
Definition at line 25 of file OrcError.h.
PerfJITRecordType
enum class llvm::orc::PerfJITRecordType strong
Enumerator
JIT_CODE_LOAD
JIT_CODE_MOVE
JIT_CODE_DEBUG_INFO
JIT_CODE_CLOSE
JIT_CODE_UNWINDING_INFO
JIT_CODE_MAX
Definition at line 24 of file PerfSharedStructs.h.
SimpleRemoteEPCOpcode
enum class llvm::orc::SimpleRemoteEPCOpcode : uint8_t strong
Enumerator
Setup
Hangup
Result
CallWrapper
LastOpC
Definition at line 38 of file SimpleRemoteEPCUtils.h.
SymbolLookupFlags
enum class llvm::orc::SymbolLookupFlags strong
Lookup flags that apply to each symbol in a lookup.
If RequiredSymbol is used (the default) for a given symbol then that symbol must be found during the lookup or the lookup will fail returning a SymbolNotFound error. If WeaklyReferencedSymbol is used and the given symbol is not found then the query will continue, and no result for the missing symbol will be present in the result (assuming the rest of the lookup succeeds).
Enumerator
RequiredSymbol
WeaklyReferencedSymbol
Definition at line 157 of file Core.h.
SymbolState
enum class llvm::orc::SymbolState : uint8_t strong
Represents the state that a symbol has reached during materialization.
Enumerator
Invalid
NeverSearched
No symbol should be in this state.
Materializing
Added to the symbol table, never queried.
Resolved
Queried, materialization begun.
Emitted
Assigned address, still materializing.
Ready
Emitted to memory, but waiting on transitive dependencies.
Definition at line 772 of file Core.h.
Function Documentation
__deregister_frame()
void llvm::orc::__deregister_frame (const void *)
Referenced by deregisterFrameWrapper().
__register_frame()
void llvm::orc::__register_frame (const void *)
Referenced by registerFrameWrapper().
absoluteSymbols()
std::unique_ptr< AbsoluteSymbolsMaterializationUnit > llvm::orc::absoluteSymbols (SymbolMap Symbols) inline
Create an AbsoluteSymbolsMaterializationUnit with the given symbols.
Useful for inserting absolute symbols into a JITDylib. E.g.:
JITDylib &JD = ...;
SymbolStringPtr Foo = ...;
ExecutorSymbolDef FooSym = ...;
if (auto Err = JD.define(absoluteSymbols({
      { Foo, FooSym },
      { Bar, BarSym }
    })))
  return Err;
Definition at line 53 of file AbsoluteSymbols.h.
Referenced by llvm::orc::Speculator::addSpeculationRuntime(), llvm::orc::COFFPlatform::Create(), llvm::orc::ELFNixPlatform::Create(), llvm::orc::MachOPlatform::Create(), llvm::orc::LocalCXXRuntimeOverrides::enable(), LLVMOrcAbsoluteSymbols(), and llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate().
addAliases() [1/3]
void llvm::orc::addAliases (ExecutionSession & ES, SymbolAliasMap & Aliases, ArrayRef< std::pair< const char *, const char * > > AL) static
Definition at line 254 of file COFFPlatform.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::JITSymbolFlags::Exported, and llvm::orc::ExecutionSession::intern().
Referenced by llvm::orc::COFFPlatform::setupJITDylib(), llvm::orc::COFFPlatform::standardPlatformAliases(), llvm::orc::ELFNixPlatform::standardPlatformAliases(), and llvm::orc::MachOPlatform::standardPlatformAliases().
addAliases() [2/3]
void llvm::orc::addAliases (ExecutionSession & ES, SymbolAliasMap & Aliases, ArrayRef< std::pair< const char *, const char * > > AL) static
Definition at line 307 of file ELFNixPlatform.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::JITSymbolFlags::Exported, and llvm::orc::ExecutionSession::intern().
addAliases() [3/3]
void llvm::orc::addAliases (ExecutionSession & ES, SymbolAliasMap & Aliases, ArrayRef< std::pair< const char *, const char * > > AL) static
Definition at line 386 of file MachOPlatform.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::JITSymbolFlags::Exported, and llvm::orc::ExecutionSession::intern().
addDefaultBootstrapValuesForHostProcess()
void llvm::orc::addDefaultBootstrapValuesForHostProcess (StringMap< std::vector< char > > & BootstrapMap, StringMap< ExecutorAddr > & BootstrapSymbols)
Definition at line 20 of file DefaultHostBootstrapValues.cpp.
References llvm::orc::rt::DeregisterEHFrameSectionAllocActionName, llvm::orc::ExecutorAddr::fromPtr(), llvm_orc_deregisterEHFrameSectionAllocAction(), llvm_orc_registerEHFrameSectionAllocAction(), and llvm::orc::rt::RegisterEHFrameSectionAllocActionName.
Referenced by llvm::orc::SelfExecutorProcessControl::SelfExecutorProcessControl().
addFunctionPointerRelocationsToCurrentSymbol()
Error llvm::orc::addFunctionPointerRelocationsToCurrentSymbol (jitlink::Symbol & Sym, jitlink::LinkGraph & G, MCDisassembler & Disassembler, MCInstrAnalysis & MIA)
Introduce relocations to Sym in its own definition if there are any pointers formed via PC-relative address that do not already have a relocation.
This is useful when introducing indirection via a stub function at link time without compiler support. If a function pointer is formed without a relocation, e.g. in the definition of foo
_foo:
  leaq -7(%rip), rax # form pointer to _foo without relocation
_bar:
  leaq (%rip), %rax  # uses X86_64_RELOC_SIGNED to '_foo'
the pointer to _foo computed by _foo and _bar may differ if we introduce a stub for _foo. If the pointer is used as a key, this may be observable to the program. This pass will attempt to introduce the missing "self-relocation" on the leaq instruction.
This is based on disassembly and should be considered "best effort". It may silently fail to add relocations.
Definition at line 380 of file IndirectionUtils.cpp.
References llvm::ArrayRef(), assert(), B(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains(), llvm::dbgs(), llvm::jitlink::x86_64::Delta32, llvm::MCInstrAnalysis::evaluateMemoryOperandAddress(), llvm::formatv(), G, llvm::jitlink::Symbol::getAddress(), llvm::jitlink::Symbol::getBlock(), llvm::MCDisassembler::getInstruction(), llvm::MCInstrAnalysis::getMemoryOperandRelocationOffset(), llvm::jitlink::Symbol::getName(), llvm::jitlink::Symbol::getOffset(), llvm::jitlink::Symbol::getSize(), llvm::MCDisassembler::getSubtargetInfo(), I, llvm::inconvertibleErrorCode(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), LLVM_DEBUG, llvm::make_error(), llvm::MCDisassembler::Success, llvm::Error::success(), and llvm::Triple::x86_64.
addInitSymbol()
void llvm::orc::addInitSymbol (MaterializationUnit::Interface & I, ExecutionSession & ES, StringRef ObjFileName)
Adds an initializer symbol to the given MU interface.
The init symbol's name is guaranteed to be unique within I, and will be of the form $.<ObjFileName>.__inits.<N>, where N is some integer.
Definition at line 24 of file ObjectFileInterface.cpp.
References assert(), I, llvm::orc::ExecutionSession::intern(), and llvm::JITSymbolFlags::MaterializationSideEffectsOnly.
Referenced by getCOFFObjectFileSymbolInfo(), getELFObjectFileSymbolInfo(), and getMachOObjectFileSymbolInfo().
buildSimpleReexportsAliasMap() [1/2]
LLVM_ABI Expected< SymbolAliasMap > llvm::orc::buildSimpleReexportsAliasMap (JITDylib & SourceJD, const SymbolNameSet & Symbols)
Build a SymbolAliasMap for the common case where you want to re-export symbols from another JITDylib with the same linkage/flags.
Referenced by buildSimpleReexportsAliasMap().
buildSimpleReexportsAliasMap() [2/2]
Expected< SymbolAliasMap > llvm::orc::buildSimpleReexportsAliasMap (JITDylib & SourceJD, SymbolNameSet Symbols)
Definition at line 491 of file Core.cpp.
References assert(), buildSimpleReexportsAliasMap(), llvm::orc::JITDylib::getExecutionSession(), llvm::orc::ExecutionSession::lookupFlags(), MatchAllSymbols, Result, and Static.
checkCOFFRelocatableObject()
Expected< std::unique_ptr< MemoryBuffer > > llvm::orc::checkCOFFRelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple & TT) static
Definition at line 22 of file LoadLinkableFile.cpp.
Referenced by loadLinkableFile().
checkELFRelocatableObject()
Expected< std::unique_ptr< MemoryBuffer > > llvm::orc::checkELFRelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple & TT) static
Definition at line 36 of file LoadLinkableFile.cpp.
Referenced by loadLinkableFile().
checkMachORelocatableObject() [1/3]
template<typename HeaderType> Error llvm::orc::checkMachORelocatableObject (MemoryBufferRef Obj, bool SwapEndianness, const Triple & TT, bool ObjIsSlice) static
Definition at line 33 of file MachO.cpp.
References llvm::Data, llvm::object::MachOObjectFile::getArch(), llvm::Triple::getArchTypeName(), llvm::MemoryBufferRef::getBuffer(), llvm::inconvertibleErrorCode(), llvm::make_error(), llvm::MachO::MH_OBJECT, objDesc(), and llvm::Error::success().
checkMachORelocatableObject() [2/3]
Error llvm::orc::checkMachORelocatableObject (MemoryBufferRef Obj, const Triple & TT, bool ObjIsSlice)
Check that the given buffer contains a MachO object file compatible with the given triple.
ObjIsSlice should be set to true if Obj is a slice of a universal binary (that fact will then be reported in the error messages).
Definition at line 59 of file MachO.cpp.
References checkMachORelocatableObject(), llvm::Data, llvm::MemoryBufferRef::getBuffer(), llvm::inconvertibleErrorCode(), llvm::make_error(), llvm::MachO::MH_CIGAM, llvm::MachO::MH_CIGAM_64, llvm::MachO::MH_MAGIC, llvm::MachO::MH_MAGIC_64, and objDesc().
Referenced by checkMachORelocatableObject(), checkMachORelocatableObject(), loadLinkableFile(), loadLinkableSliceFromMachOUniversalBinary(), and loadMachORelocatableObject().
checkMachORelocatableObject() [3/3]
Expected< std::unique_ptr< MemoryBuffer > > llvm::orc::checkMachORelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple & TT, bool ObjIsSlice)
Check that the given buffer contains a MachO object file compatible with the given triple.
This convenience overload returns the buffer if it passes all checks, otherwise it returns an error.
Definition at line 90 of file MachO.cpp.
References checkMachORelocatableObject().
checkXCOFFRelocatableObject()
Expected< std::unique_ptr< MemoryBuffer > > llvm::orc::checkXCOFFRelocatableObject (std::unique_ptr< MemoryBuffer > Obj, const Triple & TT) static
Definition at line 29 of file LoadLinkableFile.cpp.
Referenced by loadLinkableFile().
cloneFunctionDecl()
Function * llvm::orc::cloneFunctionDecl (Module & Dst, const Function & F, ValueToValueMapTy * VMap = nullptr)
Clone a function declaration into a new module.
This function can be used as the first step towards creating a callback stub (see makeStub).
If the VMap argument is non-null, a mapping will be added between F and the new declaration, and between each of F's arguments and the new declaration's arguments. This map can then be passed in to moveFunction to move the function body if required. Note: When moving functions between modules with these utilities, all decls should be cloned (and added to a single VMap) before any bodies are moved. This will ensure that references between functions all refer to the versions in the new module.
Definition at line 339 of file IndirectionUtils.cpp.
References llvm::Function::arg_begin(), llvm::cast(), llvm::Function::copyAttributesFrom(), llvm::Function::Create(), and F.
Referenced by extractSubModule().
cloneGlobalAliasDecl()
GlobalAlias * llvm::orc::cloneGlobalAliasDecl (Module & Dst, const GlobalAlias & OrigA, ValueToValueMapTy & VMap)
Clone a global alias declaration into a new module.
Definition at line 369 of file IndirectionUtils.cpp.
References assert(), llvm::GlobalAlias::create(), llvm::GlobalAlias::getAliasee(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::Type::getPointerAddressSpace(), llvm::GlobalValue::getType(), and llvm::GlobalValue::getValueType().
cloneGlobalVariableDecl()
GlobalVariable * llvm::orc::cloneGlobalVariableDecl (Module & Dst, const GlobalVariable & GV, ValueToValueMapTy * VMap = nullptr)
Clone a global variable declaration into a new module.
Definition at line 357 of file IndirectionUtils.cpp.
References llvm::GlobalVariable::copyAttributesFrom(), llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::GlobalValue::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::GlobalValue::getValueType(), and llvm::GlobalVariable::isConstant().
Referenced by extractSubModule().
cloneToContext()
ThreadSafeModule llvm::orc::cloneToContext (const ThreadSafeModule & TSMW, ThreadSafeContext TSCtx, GVPredicate ShouldCloneDef = GVPredicate(), GVModifier UpdateClonedDefSource = GVModifier())
Clones teh given module onto the given context.
Definition at line 17 of file ThreadSafeModule.cpp.
References assert(), llvm::cantFail(), llvm::CloneModule(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::parseBitcodeFile(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::orc::ThreadSafeContext::withContextDo(), llvm::orc::ThreadSafeModule::withModuleDo(), llvm::BitcodeWriter::writeModule(), llvm::BitcodeWriter::writeStrtab(), and llvm::BitcodeWriter::writeSymtab().
Referenced by cloneToNewContext().
cloneToNewContext()
ThreadSafeModule llvm::orc::cloneToNewContext (const ThreadSafeModule & TSMW, GVPredicate ShouldCloneDef = GVPredicate(), GVModifier UpdateClonedDefSource = GVModifier())
Clones the given module on to a new context.
Definition at line 66 of file ThreadSafeModule.cpp.
References assert(), and cloneToContext().
Referenced by extractSubModule().
createDebugObjectFromBuffer()
Expected< std::unique_ptr< DebugObject > > llvm::orc::createDebugObjectFromBuffer (ExecutionSession & ES, LinkGraph & G, JITLinkContext & Ctx, MemoryBufferRef ObjBuffer) static
Creates a debug object based on the input object file from ObjectLinkingLayerJITLinkContext.
Definition at line 376 of file DebugObjectManagerPlugin.cpp.
References llvm::orc::ELFDebugObject::Create(), createDebugObjectFromBuffer(), llvm::Triple::ELF, and G.
Referenced by createDebugObjectFromBuffer(), and llvm::orc::DebugObjectManagerPlugin::notifyMaterializing().
createDWARFContext()
Expected< std::pair< std::unique_ptr< DWARFContext >, StringMap< std::unique_ptr< MemoryBuffer > > > > llvm::orc::createDWARFContext (jitlink::LinkGraph & G)
Definition at line 95 of file DebugInfoSupport.cpp.
References llvm::DWARFContext::create(), llvm::dbgs(), G, llvm::inconvertibleErrorCode(), llvm::little, LLVM_DEBUG, and llvm::make_error().
Referenced by getMethodBatch().
createHeaderBlock()
template<typename MachOTraits> jitlink::Block & llvm::orc::createHeaderBlock (MachOPlatform & MOP, const MachOPlatform::HeaderOptions & Opts, JITDylib & JD, jitlink::LinkGraph & G, jitlink::Section & HeaderSection)
Definition at line 1742 of file MachOPlatform.cpp.
References B(), llvm::orc::MachOPlatform::HeaderOptions::BuildVersions, G, llvm::orc::MachOPlatform::getExecutionSession(), getMachOHeaderInfoFromTriple(), llvm::jitlink::JITLinkDylib::getName(), llvm::orc::ExecutionSession::getTargetTriple(), llvm::orc::MachOPlatform::HeaderOptions::IDDylib, llvm::orc::MachOPlatform::HeaderOptions::LoadDylibs, llvm::MachO::MH_DYLIB, P, and llvm::orc::MachOPlatform::HeaderOptions::RPaths.
createImplPointer()
GlobalVariable * llvm::orc::createImplPointer (PointerType & PT, Module & M, const Twine & Name, Constant * Initializer)
Create a function pointer with the given type, name, and initializer in the given Module.
Definition at line 281 of file IndirectionUtils.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::HiddenVisibility, and llvm::GlobalValue::NotThreadLocal.
createIRTypedAddress()
Constant * llvm::orc::createIRTypedAddress (FunctionType & FT, ExecutorAddr Addr)
Build a function pointer of FunctionType with the given constant address.
Usage example: Turn a trampoline address into a function pointer constant for use in a stub.
Definition at line 273 of file IndirectionUtils.cpp.
References llvm::PointerType::get(), llvm::Type::getContext(), llvm::Type::getInt64Ty(), llvm::ConstantExpr::getIntToPtr(), and llvm::orc::ExecutorAddr::getValue().
createJITLinkLazyReexportsManager()
Expected< std::unique_ptr< LazyReexportsManager > > llvm::orc::createJITLinkLazyReexportsManager (ObjectLinkingLayer & ObjLinkingLayer, RedirectableSymbolManager & RSMgr, JITDylib & PlatformJD, LazyReexportsManager::Listener * L = nullptr)
Definition at line 171 of file JITLinkReentryTrampolines.cpp.
References llvm::orc::JITLinkReentryTrampolines::Create(), and llvm::orc::LazyReexportsManager::Create().
createJITLoaderGDBRegistrar()
Expected< std::unique_ptr< EPCDebugObjectRegistrar > > llvm::orc::createJITLoaderGDBRegistrar (ExecutionSession & ES, std::optional< ExecutorAddr > RegistrationFunctionDylib = std::nullopt)
Create a ExecutorProcessControl-based DebugObjectRegistrar that emits debug objects to the GDB JIT interface.
This will use the EPC's lookupSymbols method to find the registration/deregistration function addresses by name.
If RegistrationFunctionsDylib is non-None then it will be searched to find the registration functions. If it is None then the process dylib will be loaded to find the registration functions.
Definition at line 16 of file EPCDebugObjectRegistrar.cpp.
References llvm::orc::SymbolLookupSet::add(), assert(), D(), llvm::orc::ExecutionSession::getExecutorProcessControl(), Result, and llvm::size().
Referenced by enableDebuggerSupport().
createLocalCompileCallbackManager()
Expected< std::unique_ptr< JITCompileCallbackManager > > llvm::orc::createLocalCompileCallbackManager (const Triple & T, ExecutionSession & ES, ExecutorAddr ErrorHandlerAddress)
Create a local compile callback manager.
The given target triple will determine the ABI, and the given ErrorHandlerAddress will be used by the resulting compile callback manager if a compile callback fails.
Definition at line 148 of file IndirectionUtils.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::inconvertibleErrorCode(), llvm::Triple::loongarch64, llvm::make_error(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::riscv64, T, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
createLocalIndirectStubsManagerBuilder()
std::function< std::unique_ptr< IndirectStubsManager >()> llvm::orc::createLocalIndirectStubsManagerBuilder (const Triple & T)
Create a local indirect stubs manager builder.
The given target triple will determine the ABI.
Definition at line 205 of file IndirectionUtils.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::Triple::loongarch64, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::riscv64, T, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by LLVMOrcCreateLocalIndirectStubsManager().
createLocalLazyCallThroughManager()
Expected< std::unique_ptr< LazyCallThroughManager > > llvm::orc::createLocalLazyCallThroughManager (const Triple & T, ExecutionSession & ES, ExecutorAddr ErrorHandlerAddr)
Create a LocalLazyCallThroughManager from the given triple and execution session.
Definition at line 109 of file LazyReexports.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::orc::LocalLazyCallThroughManager::Create(), llvm::inconvertibleErrorCode(), llvm::Triple::loongarch64, llvm::make_error(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::riscv64, T, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by LLVMOrcCreateLocalLazyCallThroughManager().
deregisterEHFrameSection()
Error llvm::orc::deregisterEHFrameSection (const void * EHFrameSectionAddr, size_t EHFrameSectionSize)
Unregister frames in the given eh-frame section with libunwind.
Definition at line 142 of file RegisterEHFrames.cpp.
References deregisterFrameWrapper(), and walkLibunwindEHFrameSection().
Referenced by deregisterEHFrameWrapper().
deregisterFrameWrapper()
Error llvm::orc::deregisterFrameWrapper (const void * P)
Definition at line 36 of file RegisterEHFrames.cpp.
References __deregister_frame(), P, and llvm::Error::success().
Referenced by deregisterEHFrameSection().
enableDebuggerSupport()
Error llvm::orc::enableDebuggerSupport (LLJIT & J)
Definition at line 21 of file DebuggerSupport.cpp.
References llvm::orc::GDBJITDebugInfoRegistrationPlugin::Create(), createJITLoaderGDBRegistrar(), llvm::dyn_cast(), llvm::Triple::ELF, llvm::orc::LLJIT::getExecutionSession(), llvm::Triple::getObjectFormatTypeName(), llvm::orc::LLJIT::getObjLinkingLayer(), llvm::orc::LLJIT::getProcessSymbolsJITDylib(), llvm::orc::LLJIT::getTargetTriple(), llvm::inconvertibleErrorCode(), llvm::Triple::MachO, llvm::make_error(), and llvm::Error::success().
Referenced by LLVMOrcLLJITEnableDebugSupport().
fromSysMemoryProtectionFlags()
MemProt llvm::orc::fromSysMemoryProtectionFlags (sys::Memory::ProtectionFlags PF) inline
Convert a sys::Memory::ProtectionFlags value to a corresponding MemProt value.
Definition at line 57 of file MemoryFlags.h.
References llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, None, Read, and Write.
getCOFFObjectFileSymbolInfo()
Expected< MaterializationUnit::Interface > llvm::orc::getCOFFObjectFileSymbolInfo (ExecutionSession & ES, const object::COFFObjectFile & Obj) static
Definition at line 151 of file ObjectFileInterface.cpp.
References addInitSymbol(), llvm::JITSymbolFlags::Callable, llvm::JITSymbolFlags::Exported, llvm::JITSymbolFlags::fromObjectSymbol(), llvm::object::COFFObjectFile::getCOFFSymbol(), llvm::object::Binary::getFileName(), llvm::object::COFFObjectFile::getNumberOfSections(), llvm::object::COFFObjectFile::getSection(), I, llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_SCN_LNK_COMDAT, llvm::orc::ExecutionSession::intern(), isCOFFInitializerSection(), llvm::COFF::isReservedSectionNumber(), llvm::object::ObjectFile::sections(), llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::SymbolRef::ST_File, llvm::object::ObjectFile::symbols(), llvm::Expected< T >::takeError(), and llvm::JITSymbolFlags::Weak.
Referenced by getObjectFileInterface().
getConstructors()
iterator_range< CtorDtorIterator > llvm::orc::getConstructors (const Module & M)
Create an iterator range over the entries of the llvm.global_ctors array.
Definition at line 85 of file ExecutionUtils.cpp.
References llvm::make_range().
getDestructors()
iterator_range< CtorDtorIterator > llvm::orc::getDestructors (const Module & M)
Create an iterator range over the entries of the llvm.global_ctors array.
Definition at line 91 of file ExecutionUtils.cpp.
References llvm::make_range().
getDylibInterface()
Expected< SymbolNameSet > llvm::orc::getDylibInterface (ExecutionSession & ES, Twine Path)
Returns a SymbolNameSet containing the exported symbols defined in the relevant slice of the given file, which may be either a dylib or a tapi file.
Definition at line 110 of file GetDylibInterface.cpp.
References llvm::createFileError(), getDylibInterfaceFromDylib(), getDylibInterfaceFromTapiFile(), llvm::identify_magic(), llvm::inconvertibleErrorCode(), llvm::file_magic::macho_dynamically_linked_shared_lib, llvm::file_magic::macho_universal_binary, llvm::make_error(), and llvm::file_magic::tapi_file.
getDylibInterfaceFromDylib()
Expected< SymbolNameSet > llvm::orc::getDylibInterfaceFromDylib (ExecutionSession & ES, Twine Path)
Returns a SymbolNameSet containing the exported symbols defined in the given dylib.
Definition at line 20 of file GetDylibInterface.cpp.
References llvm::MachO::CPU_SUBTYPE_MASK, llvm::object::createBinary(), llvm::createFileError(), llvm::dyn_cast(), llvm::MachO::getCPUSubType(), llvm::MachO::getCPUType(), llvm::MemoryBuffer::getFile(), llvm::orc::ExecutionSession::getTargetTriple(), llvm::inconvertibleErrorCode(), llvm::orc::ExecutionSession::intern(), llvm::isa(), llvm::make_error(), llvm::MachO::MH_DYLIB, and llvm::Triple::str().
Referenced by getDylibInterface().
getDylibInterfaceFromTapiFile()
Expected< SymbolNameSet > llvm::orc::getDylibInterfaceFromTapiFile (ExecutionSession & ES, Twine Path)
Returns a SymbolNameSet containing the exported symbols defined in the relevant slice of the TapiUniversal file.
Definition at line 77 of file GetDylibInterface.cpp.
References llvm::object::TapiUniversal::create(), llvm::createFileError(), llvm::MachO::getArchitectureFromCpuType(), llvm::MachO::getCPUSubType(), llvm::MachO::getCPUType(), llvm::MemoryBuffer::getFile(), llvm::orc::ExecutionSession::getTargetTriple(), and llvm::orc::ExecutionSession::intern().
Referenced by getDylibInterface().
getELFObjectFileSymbolInfo()
Expected< MaterializationUnit::Interface > llvm::orc::getELFObjectFileSymbolInfo (ExecutionSession & ES, const object::ELFObjectFileBase & Obj) static
Definition at line 97 of file ObjectFileInterface.cpp.
References addInitSymbol(), llvm::JITSymbolFlags::fromObjectSymbol(), llvm::object::Binary::getFileName(), I, llvm::orc::ExecutionSession::intern(), isELFInitializerSection(), llvm::object::ObjectFile::sections(), llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::SymbolRef::ST_File, llvm::ELF::STB_GNU_UNIQUE, llvm::object::ELFObjectFileBase::symbols(), llvm::Expected< T >::takeError(), and llvm::JITSymbolFlags::Weak.
Referenced by getObjectFileInterface().
getGenericObjectFileSymbolInfo()
Expected< MaterializationUnit::Interface > llvm::orc::getGenericObjectFileSymbolInfo (ExecutionSession & ES, const object::ObjectFile & Obj)
Definition at line 279 of file ObjectFileInterface.cpp.
References llvm::JITSymbolFlags::fromObjectSymbol(), I, llvm::orc::ExecutionSession::intern(), llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::SymbolRef::ST_File, llvm::object::ObjectFile::symbols(), and llvm::Expected< T >::takeError().
Referenced by getObjectFileInterface().
getIndirectStubsBlockSizes()
template<typename ORCABI> IndirectStubsAllocationSizes llvm::orc::getIndirectStubsBlockSizes (unsigned MinStubs, unsigned RoundToMultipleOf = 0)
Definition at line 38 of file OrcABISupport.h.
References llvm::alignTo(), and assert().
Referenced by llvm::orc::LocalIndirectStubsInfo< ORCABI >::create().
getMachOHeaderInfoFromTriple()
MachOHeaderInfo llvm::orc::getMachOHeaderInfoFromTriple (const Triple & TT)
Definition at line 1848 of file MachOPlatform.cpp.
References llvm::Triple::aarch64, llvm::MachO::CPU_SUBTYPE_ARM64_ALL, llvm::MachO::CPU_SUBTYPE_X86_64_ALL, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_X86_64, llvm_unreachable, and llvm::Triple::x86_64.
Referenced by createHeaderBlock().
getMachOObjectFileSymbolInfo()
Expected< MaterializationUnit::Interface > llvm::orc::getMachOObjectFileSymbolInfo (ExecutionSession & ES, const object::MachOObjectFile & Obj) static
Definition at line 40 of file ObjectFileInterface.cpp.
References addInitSymbol(), llvm::cantFail(), llvm::JITSymbolFlags::fromObjectSymbol(), llvm::object::Binary::getFileName(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::getSectionName(), llvm::object::MachOObjectFile::getSectionType(), I, llvm::orc::ExecutionSession::intern(), isMachOInitializerSection(), llvm::MachO::S_MOD_INIT_FUNC_POINTERS, llvm::MachO::SECTION_TYPE, llvm::object::ObjectFile::sections(), llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::SymbolRef::ST_File, llvm::object::ObjectFile::symbols(), and llvm::Expected< T >::takeError().
Referenced by getObjectFileInterface().
getMachOSliceRangeForTriple() [1/2]
Expected< std::pair< size_t, size_t > > llvm::orc::getMachOSliceRangeForTriple (MemoryBufferRef UBBuf, const Triple & TT)
Utility for identifying the file-slice compatible with TT in a universal binary.
Definition at line 224 of file MachO.cpp.
References llvm::object::MachOUniversalBinary::create(), and getMachOSliceRangeForTriple().
getMachOSliceRangeForTriple() [2/2]
Expected< std::pair< size_t, size_t > > llvm::orc::getMachOSliceRangeForTriple (object::MachOUniversalBinary & UB, const Triple & TT)
Utility for identifying the file-slice compatible with TT in a universal binary.
Definition at line 203 of file MachO.cpp.
References llvm::object::Binary::getFileName(), llvm::inconvertibleErrorCode(), llvm::make_error(), llvm::object::MachOUniversalBinary::objects(), and llvm::Triple::UnknownVendor.
Referenced by llvm::orc::StaticLibraryDefinitionGenerator::Create(), getMachOSliceRangeForTriple(), and loadLinkableSliceFromMachOUniversalBinary().
getObjectFileInterface()
Expected< MaterializationUnit::Interface > llvm::orc::getObjectFileInterface (ExecutionSession & ES, MemoryBufferRef ObjBuffer)
Returns a MaterializationUnit::Interface for the object file contained in the given buffer, or an error if the buffer does not contain a valid object file.
Definition at line 319 of file ObjectFileInterface.cpp.
References llvm::object::ObjectFile::createObjectFile(), llvm::dyn_cast(), getCOFFObjectFileSymbolInfo(), getELFObjectFileSymbolInfo(), getGenericObjectFileSymbolInfo(), getMachOObjectFileSymbolInfo(), and getXCOFFObjectFileSymbolInfo().
Referenced by llvm::orc::ObjectLayer::add(), llvm::orc::ObjectLayer::add(), llvm::orc::BasicObjectLayerMaterializationUnit::Create(), and llvm::orc::COFFPlatform::setupJITDylib().
getStaticInitGVs()
iterator_range< StaticInitGVIterator > llvm::orc::getStaticInitGVs (Module & M) inline
Create an iterator range over the GlobalValues that contribute to static initialization.
Definition at line 143 of file ExecutionUtils.h.
References llvm::make_range().
Referenced by llvm::orc::IRMaterializationUnit::IRMaterializationUnit().
getXCOFFObjectFileSymbolInfo()
Expected< MaterializationUnit::Interface > llvm::orc::getXCOFFObjectFileSymbolInfo (ExecutionSession & ES, const object::ObjectFile & Obj)
Definition at line 233 of file ObjectFileInterface.cpp.
References llvm::JITSymbolFlags::Exported, llvm::JITSymbolFlags::fromObjectSymbol(), I, llvm::orc::ExecutionSession::intern(), llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::SymbolRef::ST_File, llvm::object::ObjectFile::symbols(), and llvm::Expected< T >::takeError().
Referenced by getObjectFileInterface().
irManglingOptionsFromTargetOptions()
IRSymbolMapper::ManglingOptions llvm::orc::irManglingOptionsFromTargetOptions (const TargetOptions & Opts)
Definition at line 26 of file CompileUtils.cpp.
References llvm::orc::IRSymbolMapper::ManglingOptions::EmulatedTLS, and llvm::TargetOptions::EmulatedTLS.
Referenced by llvm::orc::ConcurrentIRCompiler::ConcurrentIRCompiler(), and llvm::orc::SimpleCompiler::SimpleCompiler().
isCOFFInitializerSection()
bool llvm::orc::isCOFFInitializerSection (StringRef Name)
Definition at line 50 of file ObjectFormats.cpp.
References llvm::StringRef::starts_with().
Referenced by getCOFFObjectFileSymbolInfo().
isDwarfSection()
bool llvm::orc::isDwarfSection (StringRef SectionName) static
Definition at line 231 of file DebugObjectManagerPlugin.cpp.
References DwarfSectionNames.
isELFInitializerSection()
bool llvm::orc::isELFInitializerSection (StringRef SecName)
Definition at line 41 of file ObjectFormats.cpp.
References ELFInitSectionNames.
Referenced by getELFObjectFileSymbolInfo().
isMachOInitializerSection() [1/2]
bool llvm::orc::isMachOInitializerSection (StringRef QualifiedName)
Definition at line 37 of file ObjectFormats.cpp.
References llvm::is_contained(), and MachOInitSectionNames.
isMachOInitializerSection() [2/2]
bool llvm::orc::isMachOInitializerSection (StringRef SegName, StringRef SecName)
Definition at line 65 of file MachOObjectFormat.cpp.
References assert(), and MachOInitSectionNames.
Referenced by getMachOObjectFileSymbolInfo().
lazyReexports() [1/2]
std::unique_ptr< LazyReexportsMaterializationUnit > llvm::orc::lazyReexports (LazyCallThroughManager & LCTManager, RedirectableSymbolManager & RSManager, JITDylib & SourceJD, SymbolAliasMap CallableAliases, ImplSymbolMap * SrcJDLoc = nullptr) inline
Define lazy-reexports based on the given SymbolAliasMap.
Each lazy re-export is a callable symbol that will look up and dispatch to the given aliasee on first call. All subsequent calls will go directly to the aliasee.
Definition at line 171 of file LazyReexports.h.
Referenced by llvm::orc::LazyObjectLinkingLayer::add(), llvm::orc::CompileOnDemandLayer::emit(), and LLVMOrcLazyReexports().
lazyReexports() [2/2]
std::unique_ptr< MaterializationUnit > llvm::orc::lazyReexports (LazyReexportsManager & LRM, SymbolAliasMap Reexports) inline
Define lazy-reexports based on the given SymbolAliasMap.
Each lazy re-export is a callable symbol that will look up and dispatch to the given aliasee on first call. All subsequent calls will go directly to the aliasee.
Definition at line 270 of file LazyReexports.h.
linkComponents()
LLVM_ATTRIBUTE_USED void llvm::orc::linkComponents ()
Definition at line 1345 of file LLJIT.cpp.
References llvm::errs(), LLVM_ATTRIBUTE_USED, llvm_orc_deregisterEHFrameSectionAllocAction(), and llvm_orc_registerEHFrameSectionAllocAction().
loadLinkableFile()
Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > llvm::orc::loadLinkableFile (StringRef Path, const Triple & TT, LoadArchives LA, std::optional< StringRef > IdentifierOverride = std::nullopt)
Create a MemoryBuffer covering the "linkable" part of the given path.
The path must contain a relocatable object file or universal binary, or (if AllowArchives is true) an archive.
If the path is a universal binary then it must contain a slice whose architecture matches the architecture in the triple (an error will be returned if there is no such slice, or if the triple does not specify an architectur).
If the path (or universal binary slice) is a relocatable object file then its architecture must match the architecture in the triple (if given).
If the path (or universal binary slice) is a relocatable object file then its format must match the format in the triple (if given).
No verification (e.g. architecture or format) is performed on the contents of archives.
If IdentifierOverride is provided then it will be used as the name of the resulting buffer, rather than Path.
Definition at line 42 of file LoadLinkableFile.cpp.
References Archive, llvm::file_magic::archive, checkCOFFRelocatableObject(), checkELFRelocatableObject(), checkMachORelocatableObject(), checkXCOFFRelocatableObject(), llvm::sys::fs::closeFile(), llvm::Triple::COFF, llvm::file_magic::coff_object, llvm::createFileError(), llvm::Triple::ELF, llvm::file_magic::elf_relocatable, llvm::MemoryBuffer::getOpenFile(), llvm::identify_magic(), llvm::inconvertibleErrorCode(), loadLinkableSliceFromMachOUniversalBinary(), llvm::Triple::MachO, llvm::file_magic::macho_object, llvm::file_magic::macho_universal_binary, llvm::make_error(), llvm::make_scope_exit(), Never, llvm::sys::fs::OF_None, llvm::sys::fs::openNativeFileForRead(), RelocatableObject, Required, llvm::Expected< T >::takeError(), llvm::Triple::UnknownObjectFormat, llvm::Triple::XCOFF, and llvm::file_magic::xcoff_object_64.
Referenced by llvm::orc::StaticLibraryDefinitionGenerator::Load().
loadLinkableSliceFromMachOUniversalBinary()
Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > llvm::orc::loadLinkableSliceFromMachOUniversalBinary (sys::fs::file_t FD, std::unique_ptr< MemoryBuffer > UBBuf, const Triple & TT, LoadArchives LA, StringRef UBPath, StringRef Identifier)
Load a compatible relocatable object (if available) from a MachO universal binary.
Path is only used for error reporting. Identifier will be used to name the resulting buffer.
Definition at line 143 of file MachO.cpp.
References Allowed, Archive, llvm::file_magic::archive, checkMachORelocatableObject(), llvm::object::MachOUniversalBinary::create(), getMachOSliceRangeForTriple(), llvm::MemoryBuffer::getOpenFileSlice(), llvm::identify_magic(), llvm::inconvertibleErrorCode(), llvm_unreachable, llvm::file_magic::macho_object, llvm::make_error(), Never, RelocatableObject, and Required.
Referenced by loadLinkableFile(), and loadMachORelocatableObject().
loadMachOLinkableFile()
LLVM_ABI Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > llvm::orc::loadMachOLinkableFile (StringRef Path, const Triple & TT, LoadArchives LA, std::optional< StringRef > IdentifierOverride = std::nullopt)
Load a relocatable object compatible with TT from Path.
If Path is a universal binary, this function will return a buffer for the slice compatible with Triple (if one is present).
References LLVM_ABI.
loadMachORelocatableObject()
Expected< std::pair< std::unique_ptr< MemoryBuffer >, LinkableFileKind > > llvm::orc::loadMachORelocatableObject (StringRef Path, const Triple & TT, LoadArchives LA, std::optional< StringRef > IdentifierOverride)
Definition at line 99 of file MachO.cpp.
References assert(), checkMachORelocatableObject(), llvm::sys::fs::closeFile(), llvm::createFileError(), llvm::MemoryBuffer::getOpenFile(), llvm::identify_magic(), llvm::inconvertibleErrorCode(), loadLinkableSliceFromMachOUniversalBinary(), llvm::Triple::MachO, llvm::file_magic::macho_object, llvm::file_magic::macho_universal_binary, llvm::make_error(), llvm::make_scope_exit(), Never, llvm::sys::fs::OF_None, llvm::sys::fs::openNativeFileForRead(), RelocatableObject, llvm::Expected< T >::takeError(), and llvm::Triple::UnknownObjectFormat.
lookupAndRecordAddrs() [1/3]
Error llvm::orc::lookupAndRecordAddrs (ExecutionSession & ES, LookupKind K, const JITDylibSearchOrder & SearchOrder, std::vector< std::pair< SymbolStringPtr, ExecutorAddr * > > Pairs, SymbolLookupFlags LookupFlags = SymbolLookupFlags::RequiredSymbol)
Record addresses of the given symbols in the given ExecutorAddrs.
Blocking version.
Definition at line 42 of file LookupAndRecordAddrs.cpp.
References lookupAndRecordAddrs().
lookupAndRecordAddrs() [2/3]
Error llvm::orc::lookupAndRecordAddrs (ExecutorProcessControl & EPC, tpctypes::DylibHandle H, std::vector< std::pair< SymbolStringPtr, ExecutorAddr * > > Pairs, SymbolLookupFlags LookupFlags = SymbolLookupFlags::RequiredSymbol)
Record addresses of given symbols in the given ExecutorAddrs.
ExecutorProcessControl lookup version. Lookups are always implicitly weak.
Definition at line 54 of file LookupAndRecordAddrs.cpp.
References llvm::orc::ExecutorProcessControl::getDylibMgr(), H, I, llvm::inconvertibleErrorCode(), llvm::orc::DylibManager::lookupSymbols(), llvm::make_error(), Result, and llvm::Error::success().
lookupAndRecordAddrs() [3/3]
void llvm::orc::lookupAndRecordAddrs (unique_function< void(Error)> OnRecorded, ExecutionSession & ES, LookupKind K, const JITDylibSearchOrder & SearchOrder, std::vector< std::pair< SymbolStringPtr, ExecutorAddr * > > Pairs, SymbolLookupFlags LookupFlags = SymbolLookupFlags::RequiredSymbol)
Record addresses of the given symbols in the given ExecutorAddrs.
Useful for making permanent records of symbol addreses to call or access in the executor (e.g. runtime support functions in Platform subclasses).
By default the symbols are looked up using SymbolLookupFlags::RequiredSymbol, and an error will be generated if any of the requested symbols are not defined.
If SymbolLookupFlags::WeaklyReferencedSymbol is used then any missing symbols will have their corresponding address objects set to zero, and this function will never generate an error (the caller will need to check addresses before using them).
Asynchronous version.
Definition at line 16 of file LookupAndRecordAddrs.cpp.
References I, llvm::orc::ExecutionSession::lookup(), NoDependenciesToRegister, Ready, Result, and llvm::Error::success().
Referenced by llvm::orc::PerfSupportPlugin::Create(), llvm::orc::COFFVCRuntimeBootstrapper::initializeStaticVCRuntime(), and lookupAndRecordAddrs().
lookupSymbolsAsyncHelper()
void llvm::orc::lookupSymbolsAsyncHelper (EPCGenericDylibManager & DylibMgr, ArrayRef< DylibManager::LookupRequest > Request, std::vector< tpctypes::LookupResult > Result, DylibManager::SymbolLookupCompleteFn Complete) static
Async helper to chain together calls to DylibMgr::lookupAsync to fulfill all all the requests.
FIXME: The dylib manager should support multiple LookupRequests natively.
Definition at line 35 of file SimpleRemoteEPC.cpp.
References llvm::append_range(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::orc::EPCGenericDylibManager::lookupAsync(), lookupSymbolsAsyncHelper(), and Result.
Referenced by lookupSymbolsAsyncHelper().
makeGenericNamedTask() [1/2]
template<typename FnT> std::unique_ptr< GenericNamedTask > llvm::orc::makeGenericNamedTask (FnT && Fn, const char * Desc = nullptr)
Create a generic named task from a const char * description.
Definition at line 89 of file TaskDispatch.h.
References llvm::orc::GenericNamedTask::DefaultDescription.
makeGenericNamedTask() [2/2]
template<typename FnT> std::unique_ptr< GenericNamedTask > llvm::orc::makeGenericNamedTask (FnT && Fn, std::string Desc)
Create a generic named task from a std::string description.
Definition at line 80 of file TaskDispatch.h.
Referenced by llvm::orc::ExecutorProcessControl::RunAsTask::operator()().
makeJITDylibSearchOrder()
JITDylibSearchOrder llvm::orc::makeJITDylibSearchOrder (ArrayRef< JITDylib * > JDs, JITDylibLookupFlags Flags = JITDylibLookupFlags::MatchExportedSymbolsOnly) inline
Convenience function for creating a search order from an ArrayRef of JITDylib*, all with the same flags.
Definition at line 178 of file Core.h.
References MatchExportedSymbolsOnly, and llvm::ArrayRef< T >::size().
Referenced by llvm::orc::PerfSupportPlugin::Create(), llvm::orc::VTuneSupportPlugin::Create(), llvm::orc::JITCompileCallbackManager::executeCompileCallback(), llvm::orc::COFFVCRuntimeBootstrapper::initializeStaticVCRuntime(), llvm::orc::ExecutionSession::lookup(), llvm::orc::LLJIT::lookupLinkerMangled(), llvm::orc::Speculator::registerSymbols(), llvm::orc::LazyCallThroughManager::resolveTrampolineLandingAddress(), and llvm::orc::CtorDtorRunner::run().
makeStub()
void llvm::orc::makeStub (Function & F, Value & ImplPointer)
Turn a function declaration into a stub function that makes an indirect call using the given function pointer.
Definition at line 290 of file IndirectionUtils.cpp.
References A(), assert(), Call, llvm::BasicBlock::Create(), and F.
makeUnexpectedEOFError()
Error llvm::orc::makeUnexpectedEOFError () static
Definition at line 133 of file SimpleRemoteEPCUtils.cpp.
References llvm::inconvertibleErrorCode(), and llvm::make_error().
objDesc()
std::string llvm::orc::objDesc (const MemoryBufferRef & Obj, const Triple & TT, bool ObjIsSlice) static
Definition at line 23 of file MachO.cpp.
References llvm::MemoryBufferRef::getBufferIdentifier().
Referenced by checkMachORelocatableObject(), and checkMachORelocatableObject().
operator%()
ExecutorAddrDiff llvm::orc::operator% (const ExecutorAddr & LHS, const ExecutorAddrDiff & RHS) inline
Taking the modulus of an address and a diff yields a diff.
Definition at line 216 of file ExecutorAddress.h.
References LHS, and RHS.
operator+() [1/2]
ExecutorAddr llvm::orc::operator+ (const ExecutorAddr & LHS, const ExecutorAddrDiff & RHS) inline
Adding an offset and an address yields an address.
Definition at line 198 of file ExecutorAddress.h.
References LHS, and RHS.
operator+() [2/2]
ExecutorAddr llvm::orc::operator+ (const ExecutorAddrDiff & LHS, const ExecutorAddr & RHS) inline
Adding an address and an offset yields an address.
Definition at line 204 of file ExecutorAddress.h.
References LHS, and RHS.
operator-() [1/2]
ExecutorAddrDiff llvm::orc::operator- (const ExecutorAddr & LHS, const ExecutorAddr & RHS) inline
Subtracting two addresses yields an offset.
Definition at line 192 of file ExecutorAddress.h.
References LHS, and RHS.
operator-() [2/2]
ExecutorAddr llvm::orc::operator- (const ExecutorAddr & LHS, const ExecutorAddrDiff & RHS) inline
Subtracting an offset from an address yields an address.
Definition at line 210 of file ExecutorAddress.h.
References LHS, and RHS.
operator<<() [1/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, AllocGroup AG) inline
Print an AllocGroup.
Definition at line 205 of file MemoryFlags.h.
operator<<() [2/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, ArrayRef< SymbolStringPtr > Symbols)
Render an array of SymbolStringPtrs.
Definition at line 148 of file DebugUtils.cpp.
operator<<() [3/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const ExecutorAddr & A) inline
Definition at line 283 of file ExecutorAddress.h.
References A(), and llvm::formatv().
operator<<() [4/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const ExecutorAddrRange & R) inline
Definition at line 287 of file ExecutorAddress.h.
References llvm::formatv().
operator<<() [5/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const ExecutorSymbolDef & Sym)
Definition at line 170 of file DebugUtils.cpp.
References llvm::orc::ExecutorSymbolDef::getAddress(), and llvm::orc::ExecutorSymbolDef::getFlags().
operator<<() [6/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const JITDylibLookupFlags & JDLookupFlags)
Definition at line 219 of file DebugUtils.cpp.
References llvm_unreachable, MatchAllSymbols, and MatchExportedSymbolsOnly.
operator<<() [7/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const JITDylibSearchOrder & SearchOrder)
Render a JITDylibSearchOrder.
Definition at line 250 of file DebugUtils.cpp.
References assert(), and llvm::drop_begin().
operator<<() [8/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const JITSymbolFlags & Flags)
Render JITSymbolFlags.
Definition at line 152 of file DebugUtils.cpp.
operator<<() [9/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const LookupKind & K)
Render a LookupKind.
Definition at line 209 of file DebugUtils.cpp.
References DLSym, llvm_unreachable, and Static.
operator<<() [10/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const MaterializationUnit & MU)
Render a MaterializationUnit.
Definition at line 202 of file DebugUtils.cpp.
References llvm::orc::MaterializationUnit::getName(), and llvm::orc::MaterializationUnit::getSymbols().
operator<<() [11/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolAliasMap & Aliases)
Render a SymbolAliasMap.
Definition at line 267 of file DebugUtils.cpp.
operator<<() [12/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolDependenceMap & Deps)
Render a SymbolDependendeMap.
Definition at line 197 of file DebugUtils.cpp.
operator<<() [13/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolDependenceMap::value_type & KV)
Render a SymbolDependenceMap entry.
Definition at line 192 of file DebugUtils.cpp.
operator<<() [14/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolFlagsMap & SymbolFlags)
Render a SymbolFlagsMap.
Definition at line 182 of file DebugUtils.cpp.
operator<<() [15/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolFlagsMap::value_type & KV)
Render a SymbolFlagsMap entry.
Definition at line 174 of file DebugUtils.cpp.
operator<<() [16/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolLookupFlags & LookupFlags)
Render a SymbolLookupFlags instance.
Definition at line 230 of file DebugUtils.cpp.
References llvm_unreachable, RequiredSymbol, and WeaklyReferencedSymbol.
operator<<() [17/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolLookupSet & LookupSet)
Render a SymbolLookupSet.
Definition at line 245 of file DebugUtils.cpp.
operator<<() [18/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolLookupSet::value_type & KV)
Render a SymbolLookupSet entry.
Definition at line 240 of file DebugUtils.cpp.
operator<<() [19/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolMap & Symbols)
Render a SymbolMap.
Definition at line 187 of file DebugUtils.cpp.
operator<<() [20/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolMap::value_type & KV)
Render a SymbolMap entry.
Definition at line 178 of file DebugUtils.cpp.
operator<<() [21/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolNameSet & Symbols)
Render a SymbolNameSet.
Definition at line 140 of file DebugUtils.cpp.
operator<<() [22/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolNameVector & Symbols)
Render a SymbolNameVector.
Definition at line 144 of file DebugUtils.cpp.
operator<<() [23/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolState & S)
Render a SymbolState.
Definition at line 276 of file DebugUtils.cpp.
References Emitted, Invalid, llvm_unreachable, Materializing, NeverSearched, Ready, and Resolved.
operator<<() [24/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolStringPool & SSP)
Dump a SymbolStringPool. Useful for debugging dangling-pointer crashes.
Definition at line 294 of file DebugUtils.cpp.
operator<<() [25/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, const SymbolStringPtrBase & Sym)
Definition at line 14 of file SymbolStringPool.cpp.
operator<<() [26/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, MemLifetime MLP) inline
Print a MemDeallocPolicy.
Definition at line 92 of file MemoryFlags.h.
References Finalize, NoAlloc, and Standard.
operator<<() [27/27]
raw_ostream & llvm::orc::operator<< (raw_ostream & OS, MemProt MP) inline
Print a MemProt as an RWX triple.
Definition at line 36 of file MemoryFlags.h.
References Exec, None, Read, and Write.
orcError()
std::error_code llvm::orc::orcError (OrcErrorCode ErrCode)
Definition at line 84 of file OrcError.cpp.
Referenced by llvm::orc::DuplicateDefinition::convertToErrorCode(), llvm::orc::FailedToMaterialize::convertToErrorCode(), llvm::orc::MissingSymbolDefinitions::convertToErrorCode(), llvm::orc::ResourceTrackerDefunct::convertToErrorCode(), llvm::orc::SymbolsCouldNotBeRemoved::convertToErrorCode(), llvm::orc::SymbolsNotFound::convertToErrorCode(), llvm::orc::UnexpectedSymbolDefinitions::convertToErrorCode(), and llvm::orc::UnsatisfiedSymbolDependencies::convertToErrorCode().
preserveDebugSections()
Error llvm::orc::preserveDebugSections (jitlink::LinkGraph & G)
Definition at line 77 of file DebugInfoSupport.cpp.
References llvm::dbgs(), G, llvm::inconvertibleErrorCode(), LLVM_DEBUG, llvm::make_error(), and llvm::Error::success().
Referenced by llvm::orc::DebugInfoPreservationPlugin::modifyPassConfig().
reentry()
JITTargetAddress llvm::orc::reentry (JITTargetAddress LCTMAddr, JITTargetAddress TrampolineAddr) static
Definition at line 409 of file EPCIndirectionUtils.cpp.
References llvm::jitTargetAddressToPointer().
Referenced by setUpInProcessLCTMReentryViaEPCIU().
reexports()
std::unique_ptr< ReExportsMaterializationUnit > llvm::orc::reexports (JITDylib & SourceJD, SymbolAliasMap Aliases, JITDylibLookupFlags SourceJDLookupFlags = JITDylibLookupFlags::MatchExportedSymbolsOnly) inline
Create a materialization unit for re-exporting symbols from another JITDylib with alternative names/flags.
SourceJD will be searched using the given JITDylibLookupFlags.
Definition at line 759 of file Core.h.
References MatchExportedSymbolsOnly.
Referenced by llvm::orc::CompileOnDemandLayer::emit(), and llvm::orc::ReexportsGenerator::tryToGenerate().
registerEHFrameSection()
Error llvm::orc::registerEHFrameSection (const void * EHFrameSectionAddr, size_t EHFrameSectionSize)
Register frames in the given eh-frame section with libunwind.
Definition at line 123 of file RegisterEHFrames.cpp.
References registerFrameWrapper(), and walkLibunwindEHFrameSection().
Referenced by registerEHFrameWrapper().
registerFrameWrapper()
Error llvm::orc::registerFrameWrapper (const void * P)
Definition at line 31 of file RegisterEHFrames.cpp.
References __register_frame(), P, and llvm::Error::success().
Referenced by registerEHFrameSection().
runAsIntFunction()
int llvm::orc::runAsIntFunction (int(* Func)(int), int Arg)
Definition at line 44 of file TargetExecutionUtils.cpp.
Referenced by llvm::orc::SelfExecutorProcessControl::runAsIntFunction(), and llvm::orc::rt_bootstrap::runAsIntFunctionWrapper().
runAsMain()
int llvm::orc::runAsMain (int(* Main)(int, char *[]), ArrayRef< std::string > Args, std::optional< StringRef > ProgramName = std::nullopt)
Run a main function, returning the result.
If the optional ProgramName argument is given then it will be inserted before the strings in Args as the first argument to the called function.
It is legal to have an empty argument list and no program name, however many main functions will expect a name argument at least, and will fail if none is provided.
Definition at line 16 of file TargetExecutionUtils.cpp.
References llvm::copy().
Referenced by llvm::orc::SelfExecutorProcessControl::runAsMain(), and llvm::orc::rt_bootstrap::runAsMainWrapper().
runAsVoidFunction()
int llvm::orc::runAsVoidFunction (int(* Func)(void))
Definition at line 42 of file TargetExecutionUtils.cpp.
Referenced by llvm::orc::SelfExecutorProcessControl::runAsVoidFunction(), and llvm::orc::rt_bootstrap::runAsVoidFunctionWrapper().
setUpGenericLLVMIRPlatform()
Expected< JITDylibSP > llvm::orc::setUpGenericLLVMIRPlatform (LLJIT & J)
Configure the LLJIT instance to scrape modules for llvm.global_ctors and llvm.global_dtors variables and (if present) build initialization and deinitialization functions.
Platform specific initialization configurations should be preferred where available.
Definition at line 1211 of file LLJIT.cpp.
setUpInactivePlatform()
Expected< JITDylibSP > llvm::orc::setUpInactivePlatform (LLJIT & J)
Configure the LLJIT instance to disable platform support explicitly.
This is useful in two cases: for platforms that don't have such requirements and for platforms, that we have no explicit support yet and that don't work well with the generic IR platform.
Definition at line 1271 of file LLJIT.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::orc::LLJIT::setPlatformSupport().
setUpInProcessLCTMReentryViaEPCIU()
Error llvm::orc::setUpInProcessLCTMReentryViaEPCIU (EPCIndirectionUtils & EPCIU)
This will call writeResolver on the given EPCIndirectionUtils instance to set up re-entry via a function that will directly return the trampoline landing address.
The EPCIndirectionUtils' LazyCallThroughManager must have been previously created via EPCIndirectionUtils::createLazyCallThroughManager.
The EPCIndirectionUtils' writeResolver method must not have been previously called.
This function is experimental and likely subject to revision.
Definition at line 420 of file EPCIndirectionUtils.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::orc::EPCIndirectionUtils::getLazyCallThroughManager(), reentry(), and llvm::orc::EPCIndirectionUtils::writeResolverBlock().
setUpOrcPlatformManually()
Error llvm::orc::setUpOrcPlatformManually (LLJIT & J)
Configure the LLJIT instance to use orc runtime support.
This overload assumes that the client has manually configured a Platform object.
Definition at line 1104 of file LLJIT.cpp.
References llvm::dbgs(), LLVM_DEBUG, llvm::orc::LLJIT::setPlatformSupport(), and llvm::Error::success().
symbolAliases()
std::unique_ptr< ReExportsMaterializationUnit > llvm::orc::symbolAliases (SymbolAliasMap Aliases) inline
Create a ReExportsMaterializationUnit with the given aliases.
Useful for defining symbol aliases.: E.g., given a JITDylib JD containing symbols "foo" and "bar", we can define aliases "baz" (for "foo") and "qux" (for "bar") with:
SymbolStringPtr Baz = ...;
SymbolStringPtr Qux = ...;
if (auto Err = JD.define(symbolAliases({
    {Baz, { Foo, JITSymbolFlags::Exported }},
    {Qux, { Bar, JITSymbolFlags::Weak }}}))
  return Err;
Definition at line 750 of file Core.h.
References MatchAllSymbols.
Referenced by llvm::orc::COFFPlatform::Create(), llvm::orc::ELFNixPlatform::Create(), llvm::orc::MachOPlatform::Create(), llvm::orc::COFFVCRuntimeBootstrapper::initializeStaticVCRuntime(), and llvm::orc::COFFPlatform::setupJITDylib().
toSysMemoryProtectionFlags()
sys::Memory::ProtectionFlags llvm::orc::toSysMemoryProtectionFlags (MemProt MP) inline
Convert a MemProt value to a corresponding sys::Memory::ProtectionFlags value.
Definition at line 44 of file MemoryFlags.h.
References Exec, llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, None, Read, and Write.
Referenced by llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::finalize(), and llvm::orc::InProcessMemoryMapper::initialize().
walkLibunwindEHFrameSection()
template<typename HandleFDEFn> Error llvm::orc::walkLibunwindEHFrameSection (const char *const SectionStart, size_t SectionSize, HandleFDEFn HandleFDE)
Definition at line 86 of file RegisterEHFrames.cpp.
References llvm::dbgs(), llvm::format(), I, LLVM_DEBUG, llvm::Offset, Size, and llvm::Error::success().
Referenced by deregisterEHFrameSection(), and registerEHFrameSection().
writeMachOStruct()
template<typename MachOStruct> size_t llvm::orc::writeMachOStruct (MutableArrayRef< char > Buf, size_t Offset, MachOStruct S, bool SwapStruct)
Definition at line 28 of file MachOBuilder.h.
References assert(), llvm::Offset, llvm::ArrayRef< T >::size(), and llvm::MachO::swapStruct().
Referenced by llvm::orc::MachOBuilder< MachOTraits >::Segment::write(), llvm::orc::MachOBuilderDylibLoadCommand< LCType >::write(), and llvm::orc::MachOBuilderLoadCommand< MachO::LC_RPATH >::write().
Variable Documentation
AddFnName
const char* llvm::orc::AddFnName static
Initial value:
=
    "__unw_add_find_dynamic_unwind_sections"
Definition at line 55 of file UnwindInfoManager.cpp.
Referenced by llvm::orc::UnwindInfoManager::TryEnable().
DwarfSectionNames
const std::set<StringRef> llvm::orc::DwarfSectionNames static
Initial value:
= {
#define HANDLE_DWARF_SECTION(ENUM_NAME, ELF_NAME, CMDLINE_NAME, OPTION)        \
}
Definition at line 224 of file DebugObjectManagerPlugin.cpp.
Referenced by isDwarfSection().
ELFCtorArrayFuncSectionName
StringRef llvm::orc::ELFCtorArrayFuncSectionName = ".ctors"
Definition at line 25 of file ObjectFormats.cpp.
ELFDtorArrayFuncSectionName
StringRef llvm::orc::ELFDtorArrayFuncSectionName = ".dtors"
Definition at line 26 of file ObjectFormats.cpp.
ELFEHFrameSectionName
StringRef llvm::orc::ELFEHFrameSectionName = ".eh_frame"
Definition at line 19 of file ObjectFormats.cpp.
ELFFiniArrayFuncSectionName
StringRef llvm::orc::ELFFiniArrayFuncSectionName = ".fini_array"
Definition at line 23 of file ObjectFormats.cpp.
ELFFiniFuncSectionName
StringRef llvm::orc::ELFFiniFuncSectionName = ".fini"
Definition at line 24 of file ObjectFormats.cpp.
ELFInitArrayFuncSectionName
StringRef llvm::orc::ELFInitArrayFuncSectionName = ".init_array"
Definition at line 21 of file ObjectFormats.cpp.
ELFInitFuncSectionName
StringRef llvm::orc::ELFInitFuncSectionName = ".init"
Definition at line 22 of file ObjectFormats.cpp.
ELFInitSectionNames
StringRef llvm::orc::ELFInitSectionNames
Initial value:
{
    ELFInitArrayFuncSectionName,
    ELFInitFuncSectionName,
    ELFCtorArrayFuncSectionName,
}
Definition at line 28 of file ObjectFormats.cpp.
Referenced by isELFInitializerSection().
ELFThreadBSSSectionName
StringRef llvm::orc::ELFThreadBSSSectionName = ".tbss"
Definition at line 34 of file ObjectFormats.cpp.
ELFThreadDataSectionName
StringRef llvm::orc::ELFThreadDataSectionName = ".tdata"
Definition at line 35 of file ObjectFormats.cpp.
Instance
std::unique_ptr<UnwindInfoManager> llvm::orc::Instance static
Definition at line 59 of file UnwindInfoManager.cpp.
Referenced by llvm::orc::UnwindInfoManager::deregisterSections(), llvm::orc::UnwindInfoManager::registerSections(), llvm::orc::UnwindInfoManager::TryEnable(), and llvm::orc::ExecutionSession::wrapAsyncWithSPS().
MachOCompactUnwindSectionName
StringRef llvm::orc::MachOCompactUnwindSectionName = "__LD,__compact_unwind"
Definition at line 21 of file MachOObjectFormat.cpp.
Referenced by llvm::jitlink::link_MachO_arm64(), and llvm::jitlink::link_MachO_x86_64().
MachOCStringSectionName
StringRef llvm::orc::MachOCStringSectionName = "__TEXT,__cstring"
Definition at line 22 of file MachOObjectFormat.cpp.
MachODataCommonSectionName
StringRef llvm::orc::MachODataCommonSectionName = "__DATA,__common"
Definition at line 18 of file MachOObjectFormat.cpp.
MachODataDataSectionName
StringRef llvm::orc::MachODataDataSectionName = "__DATA,__data"
Definition at line 19 of file MachOObjectFormat.cpp.
Referenced by llvm::jitlink::getMachODefaultRWDataSection().
MachOEHFrameSectionName
StringRef llvm::orc::MachOEHFrameSectionName = "__TEXT,__eh_frame"
Definition at line 20 of file MachOObjectFormat.cpp.
Referenced by llvm::jitlink::createEHFrameSplitterPass_MachO_arm64(), llvm::jitlink::createEHFrameSplitterPass_MachO_x86_64(), llvm::jitlink::MachOJITLinker_arm64::JITLinker< MachOJITLinker_arm64 >, llvm::jitlink::MachOJITLinker_x86_64::JITLinker< MachOJITLinker_x86_64 >, llvm::jitlink::link_MachO_arm64(), and llvm::jitlink::link_MachO_x86_64().
MachOInitSectionNames
StringRef llvm::orc::MachOInitSectionNames
Initial value:
= {
    MachOModInitFuncSectionName,         MachOObjCCatListSectionName,
    MachOObjCCatList2SectionName,        MachOObjCClassListSectionName,
    MachOObjCClassNameSectionName,       MachOObjCClassRefsSectionName,
    MachOObjCConstSectionName,           MachOObjCDataSectionName,
    MachOObjCImageInfoSectionName,       MachOObjCMethNameSectionName,
    MachOObjCMethTypeSectionName,        MachOObjCNLCatListSectionName,
    MachOObjCNLClassListSectionName,     MachOObjCProtoListSectionName,
    MachOObjCProtoRefsSectionName,       MachOObjCSelRefsSectionName,
    MachOSwift5ProtoSectionName,         MachOSwift5ProtosSectionName,
    MachOSwift5TypesSectionName,         MachOSwift5TypeRefSectionName,
    MachOSwift5FieldMetadataSectionName, MachOSwift5EntrySectionName,
}
Definition at line 51 of file MachOObjectFormat.cpp.
Referenced by isMachOInitializerSection(), and isMachOInitializerSection().
MachOModInitFuncSectionName
StringRef llvm::orc::MachOModInitFuncSectionName = "__DATA,__mod_init_func"
Definition at line 23 of file MachOObjectFormat.cpp.
MachOObjCCatList2SectionName
StringRef llvm::orc::MachOObjCCatList2SectionName = "__DATA,__objc_catlist2"
Definition at line 25 of file MachOObjectFormat.cpp.
MachOObjCCatListSectionName
StringRef llvm::orc::MachOObjCCatListSectionName = "__DATA,__objc_catlist"
Definition at line 24 of file MachOObjectFormat.cpp.
MachOObjCClassListSectionName
StringRef llvm::orc::MachOObjCClassListSectionName = "__DATA,__objc_classlist"
Definition at line 26 of file MachOObjectFormat.cpp.
MachOObjCClassNameSectionName
StringRef llvm::orc::MachOObjCClassNameSectionName = "__TEXT,__objc_classname"
Definition at line 27 of file MachOObjectFormat.cpp.
MachOObjCClassRefsSectionName
StringRef llvm::orc::MachOObjCClassRefsSectionName = "__DATA,__objc_classrefs"
Definition at line 28 of file MachOObjectFormat.cpp.
MachOObjCConstSectionName
StringRef llvm::orc::MachOObjCConstSectionName = "__DATA,__objc_const"
Definition at line 29 of file MachOObjectFormat.cpp.
MachOObjCDataSectionName
StringRef llvm::orc::MachOObjCDataSectionName = "__DATA,__objc_data"
Definition at line 30 of file MachOObjectFormat.cpp.
MachOObjCImageInfoSectionName
StringRef llvm::orc::MachOObjCImageInfoSectionName = "__DATA,__objc_imageinfo"
Definition at line 31 of file MachOObjectFormat.cpp.
MachOObjCMethNameSectionName
StringRef llvm::orc::MachOObjCMethNameSectionName = "__TEXT,__objc_methname"
Definition at line 32 of file MachOObjectFormat.cpp.
MachOObjCMethTypeSectionName
StringRef llvm::orc::MachOObjCMethTypeSectionName = "__TEXT,__objc_methtype"
Definition at line 33 of file MachOObjectFormat.cpp.
MachOObjCNLCatListSectionName
StringRef llvm::orc::MachOObjCNLCatListSectionName = "__DATA,__objc_nlcatlist"
Definition at line 34 of file MachOObjectFormat.cpp.
MachOObjCNLClassListSectionName
StringRef llvm::orc::MachOObjCNLClassListSectionName = "__DATA,__objc_nlclslist"
Definition at line 35 of file MachOObjectFormat.cpp.
MachOObjCProtoListSectionName
StringRef llvm::orc::MachOObjCProtoListSectionName = "__DATA,__objc_protolist"
Definition at line 36 of file MachOObjectFormat.cpp.
MachOObjCProtoRefsSectionName
StringRef llvm::orc::MachOObjCProtoRefsSectionName = "__DATA,__objc_protorefs"
Definition at line 37 of file MachOObjectFormat.cpp.
MachOObjCSelRefsSectionName
StringRef llvm::orc::MachOObjCSelRefsSectionName = "__DATA,__objc_selrefs"
Definition at line 38 of file MachOObjectFormat.cpp.
MachOSwift5EntrySectionName
StringRef llvm::orc::MachOSwift5EntrySectionName = "__TEXT,__swift5_entry"
Definition at line 44 of file MachOObjectFormat.cpp.
MachOSwift5FieldMetadataSectionName
StringRef llvm::orc::MachOSwift5FieldMetadataSectionName = "__TEXT,__swift5_fieldmd"
Definition at line 43 of file MachOObjectFormat.cpp.
MachOSwift5ProtoSectionName
StringRef llvm::orc::MachOSwift5ProtoSectionName = "__TEXT,__swift5_proto"
Definition at line 39 of file MachOObjectFormat.cpp.
MachOSwift5ProtosSectionName
StringRef llvm::orc::MachOSwift5ProtosSectionName = "__TEXT,__swift5_protos"
Definition at line 40 of file MachOObjectFormat.cpp.
MachOSwift5TypeRefSectionName
StringRef llvm::orc::MachOSwift5TypeRefSectionName = "__TEXT,__swift5_typeref"
Definition at line 42 of file MachOObjectFormat.cpp.
MachOSwift5TypesSectionName
StringRef llvm::orc::MachOSwift5TypesSectionName = "__TEXT,__swift5_types"
Definition at line 41 of file MachOObjectFormat.cpp.
MachOTextTextSectionName
StringRef llvm::orc::MachOTextTextSectionName = "__TEXT,__text"
Definition at line 45 of file MachOObjectFormat.cpp.
Referenced by llvm::jitlink::getMachODefaultTextSection().
MachOThreadBSSSectionName
StringRef llvm::orc::MachOThreadBSSSectionName = "__DATA,__thread_bss"
Definition at line 46 of file MachOObjectFormat.cpp.
MachOThreadDataSectionName
StringRef llvm::orc::MachOThreadDataSectionName = "__DATA,__thread_data"
Definition at line 47 of file MachOObjectFormat.cpp.
MachOThreadVarsSectionName
StringRef llvm::orc::MachOThreadVarsSectionName = "__DATA,__thread_vars"
Definition at line 48 of file MachOObjectFormat.cpp.
MachOUnwindInfoSectionName
StringRef llvm::orc::MachOUnwindInfoSectionName = "__TEXT,__unwind_info"
Definition at line 49 of file MachOObjectFormat.cpp.
Referenced by llvm::jitlink::link_MachO_arm64(), and llvm::jitlink::link_MachO_x86_64().
NoDependenciesToRegister
RegisterDependenciesFunction llvm::orc::NoDependenciesToRegister
Initial value:
=
    RegisterDependenciesFunction()
This can be used as the value for a RegisterDependenciesFunction if there are no dependants to register with.
Definition at line 38 of file Core.cpp.
Referenced by llvm::orc::JITLinkReentryTrampolines::emit(), LLVMOrcExecutionSessionLookup(), llvm::orc::ExecutionSession::lookup(), lookupAndRecordAddrs(), llvm::orc::SymbolInstance::lookupAsync(), llvm::orc::Platform::lookupInitSymbols(), llvm::orc::Platform::lookupInitSymbolsAsync(), llvm::orc::Speculator::registerSymbols(), and llvm::orc::LazyCallThroughManager::resolveTrampolineLandingAddress().
RemoveFindDynamicUnwindSections
int(* llvm::orc::RemoveFindDynamicUnwindSections) (void *) (void *) = nullptr static
Definition at line 60 of file UnwindInfoManager.cpp.
Referenced by llvm::orc::UnwindInfoManager::TryEnable(), and llvm::orc::UnwindInfoManager::~UnwindInfoManager().
RemoveFnName
const char* llvm::orc::RemoveFnName static
Initial value:
=
    "__unw_remove_find_dynamic_unwind_sections"
Definition at line 57 of file UnwindInfoManager.cpp.
Referenced by llvm::orc::UnwindInfoManager::TryEnable(), and llvm::orc::UnwindInfoManager::~UnwindInfoManager().