LLVM: llvm::dxil Namespace Reference
llvm::dxil Namespace Reference
Namespaces
namespace PointerTypeAnalysis
An analysis to compute the PointerTypes for pointers in a Module.
Classes
class AnyResourceExtType
struct Attributes
class BitcodeWriter
class CBufferDataLayout
class CBufferExtType
The dx.CBuffer target extension type.
struct ComputedShaderFlags
class DXILBitcodeWriter
class DXILOpBuilder
struct EntryProperties
class FeedbackTextureExtType
The dx.FeedbackTexture target extension type.
class LayoutExtType
The dx.Layout target extension type.
class LegacyCBufferLayout
struct ModuleMetadataInfo
struct ModuleShaderFlags
class MSTextureExtType
The dx.MSTexture target extension type.
class RawBufferExtType
The dx.RawBuffer target extension type.
class ResourceInfo
class ResourceTypeInfo
class RootSignatureAnalysis
class RootSignatureAnalysisPrinter
Printer pass for RootSignatureAnalysis results.
class RootSignatureAnalysisWrapper
Wrapper pass for the legacy pass manager.
class RootSignatureBindingInfo
class SamplerExtType
The dx.Sampler target extension type.
class ShaderFlagsAnalysis
class ShaderFlagsAnalysisPrinter
Printer pass for ShaderFlagsAnalysis results.
class ShaderFlagsAnalysisWrapper
Wrapper pass for the legacy pass manager.
class TextureExtType
The dx.Texture target extension type.
class TypedBufferExtType
The dx.TypedBuffer target extension type.
class ValueEnumerator
Typedefs
using PointerTypeMap = DenseMap<const Value *, Type *>
Enumerations
enum class ResourceCounterDirection { Increment , Decrement , Unknown , Invalid }
enum class ResourceClass : uint8_t { SRV = 0 , UAV , CBuffer , Sampler }
enum class ResourceKind : uint32_t {
Invalid = 0 , Texture1D , Texture2D , Texture2DMS ,
Texture3D , TextureCube , Texture1DArray , Texture2DArray ,
Texture2DMSArray , TextureCubeArray , TypedBuffer , RawBuffer ,
StructuredBuffer , CBuffer , Sampler , TBuffer ,
RTAccelerationStructure , FeedbackTexture2D , FeedbackTexture2DArray , NumEntries
}
The kind of resource for an SRV or UAV resource.
enum class ElementType : uint32_t {
Invalid = 0 , I1 , I16 , U16 ,
I32 , U32 , I64 , U64 ,
F16 , F32 , F64 , SNormF16 ,
UNormF16 , SNormF32 , UNormF32 , SNormF64 ,
UNormF64 , PackedS8x32 , PackedU8x32
}
The element type of an SRV or UAV resource.
enum class ExtPropTags : uint32_t { ElementType = 0 , StructuredBufferStride = 1 , SamplerFeedbackKind = 2 , Atomic64Use = 3 }
Metadata tags for extra resource properties.
enum class SamplerType : uint32_t { Default = 0 , Comparison = 1 , Mono = 2 }
enum class SamplerFeedbackType : uint32_t { MinMip = 0 , MipRegionUsed = 1 }
enum class OpCode : unsigned
enum class OpCodeClass : unsigned
enum class OpParamType : unsigned
enum class RootSignatureElementKind {
Error = 0 , RootFlags = 1 , RootConstants = 2 , SRV = 3 ,
UAV = 4 , CBV = 5 , DescriptorTable = 6 , StaticSamplers = 7
}
enum MetadataAbbrev : unsigned { LastPlusOne }
Functions
LLVM_ABI StringRef getResourceNameFromBindingCall (CallInst *CI)
Attributes operator| (Attributes a, Attributes b)
Attributes & operator|= (Attributes &a, Attributes &b)
static Error makeOpError (dxil::OpCode OpCode, Twine Msg)
void WriteDXILToFile (const Module &M, raw_ostream &Out)
Write the specified module to the specified raw output stream.
Variables
const unsigned MinWaveSize = 4
const unsigned MaxWaveSize = 128
Typedef Documentation
PointerTypeMap
using llvm::dxil::PointerTypeMap = DenseMap<const Value *, Type *>
Definition at line 26 of file PointerTypeAnalysis.h.
Enumeration Type Documentation
ElementType
enum class llvm::dxil::ElementType : uint32_t strong
The element type of an SRV or UAV resource.
Enumerator
Invalid
I1
I16
U16
I32
U32
I64
U64
F16
F32
F64
SNormF16
UNormF16
SNormF32
UNormF32
SNormF64
UNormF64
PackedS8x32
PackedU8x32
Definition at line 58 of file DXILABI.h.
ExtPropTags
enum class llvm::dxil::ExtPropTags : uint32_t strong
Metadata tags for extra resource properties.
Enumerator
ElementType
StructuredBufferStride
SamplerFeedbackKind
Atomic64Use
Definition at line 81 of file DXILABI.h.
MetadataAbbrev
enum llvm::dxil::MetadataAbbrev : unsigned
Enumerator
LastPlusOne
Definition at line 59 of file DXILBitcodeWriter.cpp.
OpCode
enum class llvm::dxil::OpCode : unsigned strong
Definition at line 18 of file DXILConstants.h.
OpCodeClass
enum class llvm::dxil::OpCodeClass : unsigned strong
Definition at line 23 of file DXILConstants.h.
OpParamType
enum class llvm::dxil::OpParamType : unsigned strong
Definition at line 28 of file DXILConstants.h.
ResourceClass
enum class llvm::dxil::ResourceClass : uint8_t strong
Enumerator
SRV
UAV
CBuffer
Sampler
Definition at line 25 of file DXILABI.h.
ResourceCounterDirection
enum class llvm::dxil::ResourceCounterDirection strong
Enumerator
Increment
Decrement
Unknown
Invalid
Definition at line 335 of file DXILResource.h.
ResourceKind
enum class llvm::dxil::ResourceKind : uint32_t strong
The kind of resource for an SRV or UAV resource.
Sometimes referred to as "Shape" in the DXIL docs.
Enumerator
Invalid
Texture1D
Texture2D
Texture2DMS
Texture3D
TextureCube
Texture1DArray
Texture2DArray
Texture2DMSArray
TextureCubeArray
TypedBuffer
RawBuffer
StructuredBuffer
CBuffer
Sampler
TBuffer
RTAccelerationStructure
FeedbackTexture2D
FeedbackTexture2DArray
NumEntries
Definition at line 34 of file DXILABI.h.
RootSignatureElementKind
enum class llvm::dxil::RootSignatureElementKind strong
Enumerator
Error
RootFlags
RootConstants
SRV
UAV
CBV
DescriptorTable
StaticSamplers
Definition at line 29 of file DXILRootSignature.h.
SamplerFeedbackType
enum class llvm::dxil::SamplerFeedbackType : uint32_t strong
Enumerator
MinMip
MipRegionUsed
Definition at line 94 of file DXILABI.h.
SamplerType
enum class llvm::dxil::SamplerType : uint32_t strong
Enumerator
Default
Comparison
Mono
Definition at line 88 of file DXILABI.h.
Function Documentation
getResourceNameFromBindingCall()
StringRef llvm::dxil::getResourceNameFromBindingCall (CallInst * CI)
Definition at line 790 of file DXILResource.cpp.
References assert(), llvm::dyn_cast(), llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), llvm::Function::getIntrinsicID(), and llvm_unreachable.
makeOpError()
Error llvm::dxil::makeOpError (dxil::OpCode OpCode, Twine Msg) static
Definition at line 487 of file DXILOpBuilder.cpp.
References Error, llvm::inconvertibleErrorCode(), and llvm::make_error().
Referenced by llvm::dxil::DXILOpBuilder::tryCreateOp().
operator|()
Attributes llvm::dxil::operator| (Attributes a, Attributes b) inline
Definition at line 38 of file DXILConstants.h.
operator|=()
Attributes & llvm::dxil::operator|= (Attributes & a, Attributes & b) inline
Definition at line 45 of file DXILConstants.h.
WriteDXILToFile()
void llvm::dxil::WriteDXILToFile (const Module & M, raw_ostream & Out)
Write the specified module to the specified raw output stream.
Write the specified module to the specified output stream.
For streams where it matters, the given stream should be in "binary" mode.
Definition at line 395 of file DXILBitcodeWriter.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::BWH_HeaderSize, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::raw_ostream::write(), and llvm::dxil::BitcodeWriter::writeModule().
Variable Documentation
MaxWaveSize
const unsigned llvm::dxil::MaxWaveSize = 128
Definition at line 100 of file DXILABI.h.
MinWaveSize
const unsigned llvm::dxil::MinWaveSize = 4
Definition at line 99 of file DXILABI.h.