LLVM: llvm::RISCVRI Namespace Reference
llvm::RISCVRI Namespace Reference
Enumerations
enum : uint8_t {
IsVRegClassShift = 0 , IsVRegClassShiftMask = 0b1 << IsVRegClassShift , VLMulShift = IsVRegClassShift + 1 , VLMulShiftMask = 0b11 << VLMulShift ,
NFShift = VLMulShift + 2 , NFShiftMask = 0b111 << NFShift
}
Functions
static bool isVRegClass (uint8_t TSFlags)
static RISCVVType::VLMUL getLMul (uint8_t TSFlags)
static unsigned getNF (uint8_t TSFlags)
Enumeration Type Documentation
anonymous enum
anonymous enum : uint8_t
Enumerator
IsVRegClassShift
IsVRegClassShiftMask
VLMulShift
VLMulShiftMask
NFShift
NFShiftMask
Definition at line 25 of file RISCVRegisterInfo.h.
Function Documentation
getLMul()
RISCVVType::VLMUL llvm::RISCVRI::getLMul (uint8_t TSFlags) inline static
Returns
the LMUL for the register class.
Definition at line 46 of file RISCVRegisterInfo.h.
References VLMulShift, and VLMulShiftMask.
Referenced by llvm::RISCVInstrInfo::copyPhysRegVector().
getNF()
unsigned llvm::RISCVRI::getNF (uint8_t TSFlags) inline static
Returns
the NF for the register class.
Definition at line 52 of file RISCVRegisterInfo.h.
References NFShift, and NFShiftMask.
Referenced by llvm::RISCVInstrInfo::copyPhysRegVector(), llvm::RISCVRegisterInfo::isVRNRegClass(), and llvm::RISCVRegisterInfo::isVRRegClass().
isVRegClass()
bool llvm::RISCVRI::isVRegClass (uint8_t TSFlags) inline static
Returns
the IsVRegClass for the register class.
Definition at line 41 of file RISCVRegisterInfo.h.
References IsVRegClassShift, and IsVRegClassShiftMask.
Referenced by llvm::RISCVRegisterInfo::isRVVRegClass(), isVectorRegClass(), llvm::RISCVRegisterInfo::isVRNRegClass(), and llvm::RISCVRegisterInfo::isVRRegClass().