LLVM: llvm::SDPatternMatch Namespace Reference
llvm::SDPatternMatch Namespace Reference
Classes
struct AllOnes_match
struct And
struct And< Pred, Preds... >
class BasicMatchContext
MatchContext can repurpose existing patterns to behave differently under a certain context.
struct BinaryOpc_match
struct CondCode_match
struct ConstantInt_match
struct DeferredValue_match
struct EffectiveOperands
Provide number of operands that are not chain or glue, as well as the first index of such operand.
struct EffectiveOperands< false >
struct m_Mask
struct m_SpecificMask
struct MaxMin_match
struct Not
struct NUses_match
struct Ones_match
struct Opcode_match
struct Operands_match
struct Operands_match< OpIdx, OpndPred, OpndPreds... >
struct Or
struct Or< Pred, Preds... >
struct ReassociatableOpc_match
struct Result_match
struct SDShuffle_match
Matching while capturing mask.
struct smax_pred_ty
struct smin_pred_ty
struct SpecificInt_match
struct SwitchContext
Switch to a different MatchContext for subsequent patterns.
struct TernaryOpc_match
struct TLI_pred_match
struct umax_pred_ty
struct umin_pred_ty
struct UnaryOpc_match
struct Value_bind
struct Value_match
struct ValueType_bind
struct ValueType_match
struct Zero_match
Functions
template<typename Pattern, typename MatchContext>
bool sd_context_match (SDValue N, const MatchContext &Ctx, Pattern &&P)
template<typename Pattern, typename MatchContext>
bool sd_context_match (SDNode *N, const MatchContext &Ctx, Pattern &&P)
template<typename Pattern>
bool sd_match (SDNode *N, const SelectionDAG *DAG, Pattern &&P)
template<typename Pattern>
bool sd_match (SDValue N, const SelectionDAG *DAG, Pattern &&P)
template<typename Pattern>
bool sd_match (SDNode *N, Pattern &&P)
template<typename Pattern>
bool sd_match (SDValue N, Pattern &&P)
Value_match m_Value ()
Match any valid SDValue.
Value_match m_Specific (SDValue N)
template<unsigned ResNo, typename Pattern>
Result_match< ResNo, Pattern > m_Result (const Pattern &P)
Match only if the SDValue is a certain result at ResNo.
DeferredValue_match m_Deferred (SDValue &V)
Similar to m_Specific, but the specific value to match is determined by another sub-pattern in the same sd_match() expression.
Opcode_match m_Opc (unsigned Opcode)
Opcode_match m_Undef ()
Opcode_match m_Poison ()
template<typename Pattern>
NUses_match< 1, Pattern > m_OneUse (const Pattern &P)
template<unsigned N, typename Pattern>
NUses_match< N, Pattern > m_NUses (const Pattern &P)
NUses_match< 1, Value_match > m_OneUse ()
template<unsigned N>
NUses_match< N, Value_match > m_NUses ()
Value_bind m_Value (SDValue &N)
template<typename PredFuncT, typename Pattern>
TLI_pred_match (const PredFuncT &Pred, const Pattern &P) -> TLI_pred_match< Pattern, PredFuncT >
template<typename Pattern>
auto m_LegalOp (const Pattern &P)
Match legal SDNodes based on the information provided by TargetLowering.
template<typename MatchContext, typename Pattern>
SwitchContext< MatchContext, Pattern > m_Context (const MatchContext &Ctx, Pattern &&P)
ValueType_bind m_VT (EVT &VT)
Retreive the ValueType of the current SDValue.
template<typename PredFuncT, typename Pattern>
ValueType_match (const PredFuncT &Pred, const Pattern &P) -> ValueType_match< Pattern, PredFuncT >
template<typename Pattern>
auto m_SpecificVT (EVT RefVT, const Pattern &P)
Match a specific ValueType.
auto m_SpecificVT (EVT RefVT)
auto m_Glue ()
auto m_OtherVT ()
template<typename Pattern>
auto m_SpecificScalarVT (EVT RefVT, const Pattern &P)
Match a scalar ValueType.
auto m_SpecificScalarVT (EVT RefVT)
template<typename Pattern>
auto m_SpecificVectorElementVT (EVT RefVT, const Pattern &P)
Match a vector ValueType.
auto m_SpecificVectorElementVT (EVT RefVT)
template<typename Pattern>
auto m_IntegerVT (const Pattern &P)
Match any integer ValueTypes.
auto m_IntegerVT ()
template<typename Pattern>
auto m_FloatingPointVT (const Pattern &P)
Match any floating point ValueTypes.
auto m_FloatingPointVT ()
template<typename Pattern>
auto m_VectorVT (const Pattern &P)
Match any vector ValueTypes.
auto m_VectorVT ()
template<typename Pattern>
auto m_FixedVectorVT (const Pattern &P)
Match fixed-length vector ValueTypes.
auto m_FixedVectorVT ()
template<typename Pattern>
auto m_ScalableVectorVT (const Pattern &P)
Match scalable vector ValueTypes.
auto m_ScalableVectorVT ()
template<typename Pattern>
auto m_LegalType (const Pattern &P)
Match legal ValueTypes based on the information provided by TargetLowering.
template<typename Pred>
Not (const Pred &P) -> Not< Pred >
template<typename Pred>
Not< Pred > m_Unless (const Pred &P)
Match if the inner pattern does NOT match.
template<typename... Preds>
And< Preds... > m_AllOf (const Preds &...preds)
template<typename... Preds>
Or< Preds... > m_AnyOf (const Preds &...preds)
template<typename... Preds>
auto m_NoneOf (const Preds &...preds)
template<typename... OpndPreds>
auto m_Node (unsigned Opcode, const OpndPreds &...preds)
template<typename T0_P, typename T1_P, typename T2_P>
TernaryOpc_match< T0_P, T1_P, T2_P > m_SetCC (const T0_P &LHS, const T1_P &RHS, const T2_P &CC)
template<typename T0_P, typename T1_P, typename T2_P>
TernaryOpc_match< T0_P, T1_P, T2_P, true, false > m_c_SetCC (const T0_P &LHS, const T1_P &RHS, const T2_P &CC)
template<typename T0_P, typename T1_P, typename T2_P>
TernaryOpc_match< T0_P, T1_P, T2_P > m_Select (const T0_P &Cond, const T1_P &T, const T2_P &F)
template<typename T0_P, typename T1_P, typename T2_P>
TernaryOpc_match< T0_P, T1_P, T2_P > m_VSelect (const T0_P &Cond, const T1_P &T, const T2_P &F)
template<typename T0_P, typename T1_P, typename T2_P>
Result_match< 0, TernaryOpc_match< T0_P, T1_P, T2_P > > m_Load (const T0_P &Ch, const T1_P &Ptr, const T2_P &Offset)
template<typename T0_P, typename T1_P, typename T2_P>
TernaryOpc_match< T0_P, T1_P, T2_P > m_InsertElt (const T0_P &Vec, const T1_P &Val, const T2_P &Idx)
template<typename LHS, typename RHS, typename IDX>
TernaryOpc_match< LHS, RHS, IDX > m_InsertSubvector (const LHS &Base, const RHS &Sub, const IDX &Idx)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_BinOp (unsigned Opc, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_c_BinOp (unsigned Opc, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, false, true > m_ChainedBinOp (unsigned Opc, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true, true > m_c_ChainedBinOp (unsigned Opc, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_Add (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_Sub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_Mul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_And (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_Or (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_DisjointOr (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
auto m_AddLike (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_Xor (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
auto m_BitwiseLogic (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_SMin (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
auto m_SMinLike (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_SMax (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
auto m_SMaxLike (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_UMin (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
auto m_UMinLike (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_UMax (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
auto m_UMaxLike (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_UDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_SDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_URem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_SRem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_Shl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_Sra (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_Srl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_Rotl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_Rotr (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_FAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_FSub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS, true > m_FMul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_FDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_FRem (const LHS &L, const RHS &R)
template<typename V1_t, typename V2_t>
BinaryOpc_match< V1_t, V2_t > m_Shuffle (const V1_t &v1, const V2_t &v2)
template<typename V1_t, typename V2_t, typename Mask_t>
SDShuffle_match< V1_t, V2_t, Mask_t > m_Shuffle (const V1_t &v1, const V2_t &v2, const Mask_t &mask)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_ExtractElt (const LHS &Vec, const RHS &Idx)
template<typename LHS, typename RHS>
BinaryOpc_match< LHS, RHS > m_ExtractSubvector (const LHS &Vec, const RHS &Idx)
template<typename Opnd>
UnaryOpc_match< Opnd > m_UnaryOp (unsigned Opc, const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd, true > m_ChainedUnaryOp (unsigned Opc, const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_BitCast (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_BSwap (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_BitReverse (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_ZExt (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_NNegZExt (const Opnd &Op)
template<typename Opnd>
auto m_SExt (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_AnyExt (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_Trunc (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_Abs (const Opnd &Op)
template<typename Opnd>
auto m_ZExtOrSelf (const Opnd &Op)
Match a zext or identity Allows to peek through optional extensions.
template<typename Opnd>
auto m_SExtOrSelf (const Opnd &Op)
Match a sext or identity Allows to peek through optional extensions.
template<typename Opnd>
auto m_SExtLike (const Opnd &Op)
template<typename Opnd>
Or< UnaryOpc_match< Opnd >, Opnd > m_AExtOrSelf (const Opnd &Op)
Match a aext or identity Allows to peek through optional extensions.
template<typename Opnd>
Or< UnaryOpc_match< Opnd >, Opnd > m_TruncOrSelf (const Opnd &Op)
Match a trunc or identity Allows to peek through optional truncations.
template<typename Opnd>
UnaryOpc_match< Opnd > m_VScale (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_FPToUI (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_FPToSI (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_Ctpop (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_Ctlz (const Opnd &Op)
template<typename Opnd>
UnaryOpc_match< Opnd > m_Cttz (const Opnd &Op)
ConstantInt_match m_ConstInt ()
Match any interger constants or splat of an integer constant.
ConstantInt_match m_ConstInt (APInt &V)
Match any interger constants or splat of an integer constant; return the specific constant or constant splat value.
SpecificInt_match m_SpecificInt (APInt V)
Match a specific integer constant or constant splat value.
SpecificInt_match m_SpecificInt (uint64_t V)
Ones_match m_One (bool AllowUndefs=false)
Zero_match m_Zero (bool AllowUndefs=false)
AllOnes_match m_AllOnes (bool AllowUndefs=false)
auto m_True ()
Match true boolean value based on the information provided by TargetLowering.
auto m_False ()
Match false boolean value based on the information provided by TargetLowering.
CondCode_match m_CondCode ()
Match any conditional code SDNode.
CondCode_match m_CondCode (ISD::CondCode &CC)
Match any conditional code SDNode and return its ISD::CondCode value.
CondCode_match m_SpecificCondCode (ISD::CondCode CC)
Match a conditional code SDNode with a specific ISD::CondCode.
template<typename ValTy>
BinaryOpc_match< Zero_match, ValTy, false > m_Neg (const ValTy &V)
Match a negate as a sub(0, v)
template<typename ValTy>
BinaryOpc_match< ValTy, AllOnes_match, true > m_Not (const ValTy &V)
Match a Not as a xor(v, -1) or xor(-1, v)
template<typename... PatternTs>
ReassociatableOpc_match< PatternTs... > m_ReassociatableAdd (const PatternTs &...Patterns)
template<typename... PatternTs>
ReassociatableOpc_match< PatternTs... > m_ReassociatableOr (const PatternTs &...Patterns)
template<typename... PatternTs>
ReassociatableOpc_match< PatternTs... > m_ReassociatableAnd (const PatternTs &...Patterns)
template<typename... PatternTs>
ReassociatableOpc_match< PatternTs... > m_ReassociatableMul (const PatternTs &...Patterns)
Function Documentation
m_Abs()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_Abs (const Opnd & Op) inline
Definition at line 1009 of file SDPatternMatch.h.
References llvm::ISD::ABS.
Referenced by combineBasicSADPattern().
m_Add()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_Add (const LHS & L, const RHS & R) inline
Definition at line 760 of file SDPatternMatch.h.
References llvm::ISD::ADD, LHS, and RHS.
Referenced by m_AddLike().
m_AddLike()
template<typename LHS, typename RHS> auto llvm::SDPatternMatch::m_AddLike (const LHS & L, const RHS & R) inline
Definition at line 791 of file SDPatternMatch.h.
References LHS, m_Add(), m_AnyOf(), m_DisjointOr(), and RHS.
m_AExtOrSelf()
template<typename Opnd> Or< UnaryOpc_match< Opnd >, Opnd > llvm::SDPatternMatch::m_AExtOrSelf (const Opnd & Op) inline
Match a aext or identity Allows to peek through optional extensions.
Definition at line 1032 of file SDPatternMatch.h.
References m_AnyExt().
m_AllOf()
template<typename... Preds> And< Preds... > llvm::SDPatternMatch::m_AllOf (const Preds &... preds)
Definition at line 429 of file SDPatternMatch.h.
Referenced by combineAdd(), combineAnd(), combineBasicSADPattern(), combineLogicBlendIntoConditionalNegate(), combineSCALAR_TO_VECTOR(), commuteSelect(), m_Node(), and matchPMADDWD().
m_AllOnes()
AllOnes_match llvm::SDPatternMatch::m_AllOnes (bool AllowUndefs = false) inline
Definition at line 1154 of file SDPatternMatch.h.
m_And()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_And (const LHS & L, const RHS & R) inline
Definition at line 775 of file SDPatternMatch.h.
References llvm::ISD::AND, LHS, and RHS.
Referenced by m_BitwiseLogic().
m_AnyExt()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_AnyExt (const Opnd & Op) inline
Definition at line 1001 of file SDPatternMatch.h.
References llvm::ISD::ANY_EXTEND.
Referenced by combineSCALAR_TO_VECTOR(), m_AExtOrSelf(), and visitORCommutative().
m_AnyOf()
template<typename... Preds> Or< Preds... > llvm::SDPatternMatch::m_AnyOf (const Preds &... preds)
Definition at line 433 of file SDPatternMatch.h.
Referenced by combineBasicSADPattern(), m_AddLike(), m_BitwiseLogic(), m_NoneOf(), m_SExtLike(), m_SExtOrSelf(), m_SMaxLike(), m_SMinLike(), m_UMaxLike(), m_UMinLike(), and m_ZExtOrSelf().
m_BinOp()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_BinOp (unsigned Opc, const LHS & L, const RHS & R) inline
Definition at line 737 of file SDPatternMatch.h.
References LHS, Opc, and RHS.
m_BitCast()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_BitCast (const Opnd & Op) inline
Definition at line 974 of file SDPatternMatch.h.
m_BitReverse()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_BitReverse (const Opnd & Op) inline
Definition at line 984 of file SDPatternMatch.h.
References llvm::ISD::BITREVERSE.
m_BitwiseLogic()
template<typename LHS, typename RHS> auto llvm::SDPatternMatch::m_BitwiseLogic (const LHS & L, const RHS & R) inline
Definition at line 801 of file SDPatternMatch.h.
References LHS, m_And(), m_AnyOf(), m_Or(), m_Xor(), and RHS.
m_BSwap()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_BSwap (const Opnd & Op) inline
Definition at line 979 of file SDPatternMatch.h.
References llvm::ISD::BSWAP.
m_c_BinOp()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_c_BinOp (unsigned Opc, const LHS & L, const RHS & R) inline
Definition at line 742 of file SDPatternMatch.h.
References LHS, Opc, and RHS.
m_c_ChainedBinOp()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true, true > llvm::SDPatternMatch::m_c_ChainedBinOp (unsigned Opc, const LHS & L, const RHS & R) inline
Definition at line 754 of file SDPatternMatch.h.
References LHS, Opc, and RHS.
m_c_SetCC()
template<typename T0_P, typename T1_P, typename T2_P> TernaryOpc_match< T0_P, T1_P, T2_P, true, false > llvm::SDPatternMatch::m_c_SetCC (const T0_P & LHS, const T1_P & RHS, const T2_P & CC) inline
Definition at line 544 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SETCC.
Referenced by isTruncateOf(), performAnyAllCombine(), and performBitcastCombine().
m_ChainedBinOp()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, false, true > llvm::SDPatternMatch::m_ChainedBinOp (unsigned Opc, const LHS & L, const RHS & R) inline
Definition at line 749 of file SDPatternMatch.h.
References LHS, Opc, and RHS.
m_ChainedUnaryOp()
template<typename Opnd> UnaryOpc_match< Opnd, true > llvm::SDPatternMatch::m_ChainedUnaryOp (unsigned Opc, const Opnd & Op) inline
Definition at line 969 of file SDPatternMatch.h.
References Opc.
m_CondCode() [1/2]
CondCode_match llvm::SDPatternMatch::m_CondCode () inline
Match any conditional code SDNode.
Definition at line 1221 of file SDPatternMatch.h.
Referenced by commuteSelect(), foldVSelectToSignBitSplatMask(), performAnyAllCombine(), and performBitcastCombine().
m_CondCode() [2/2]
CondCode_match llvm::SDPatternMatch::m_CondCode (ISD::CondCode & CC) inline
Match any conditional code SDNode and return its ISD::CondCode value.
Definition at line 1223 of file SDPatternMatch.h.
m_ConstInt() [1/2]
ConstantInt_match llvm::SDPatternMatch::m_ConstInt () inline
Match any interger constants or splat of an integer constant.
Definition at line 1090 of file SDPatternMatch.h.
Referenced by combineAdd(), combineShlAddIAddImpl(), detectUSatPattern(), foldSubCtlzNot(), m_False(), m_True(), llvm::SDPatternMatch::SpecificInt_match::match(), matchPMADDWD(), matchPMADDWD_2(), and reverseZExtICmpCombine().
m_ConstInt() [2/2]
ConstantInt_match llvm::SDPatternMatch::m_ConstInt (APInt & V) inline
Match any interger constants or splat of an integer constant; return the specific constant or constant splat value.
Definition at line 1093 of file SDPatternMatch.h.
m_Context()
template<typename MatchContext, typename Pattern> SwitchContext< MatchContext, Pattern > llvm::SDPatternMatch::m_Context (const MatchContext & Ctx, Pattern && P) inline
Definition at line 247 of file SDPatternMatch.h.
References P.
m_Ctlz()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_Ctlz (const Opnd & Op) inline
Definition at line 1059 of file SDPatternMatch.h.
References llvm::ISD::CTLZ.
Referenced by foldSubCtlzNot().
m_Ctpop()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_Ctpop (const Opnd & Op) inline
Definition at line 1055 of file SDPatternMatch.h.
References llvm::ISD::CTPOP.
m_Cttz()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_Cttz (const Opnd & Op) inline
Definition at line 1063 of file SDPatternMatch.h.
References llvm::ISD::CTTZ.
m_Deferred()
DeferredValue_match llvm::SDPatternMatch::m_Deferred (SDValue & V) inline
Similar to m_Specific, but the specific value to match is determined by another sub-pattern in the same sd_match() expression.
For instance, We cannot match (add V, V) with m_Add(m_Value(X), m_Specific(X)) since X is not initialized at the time it got copied into m_Specific. Instead, we should use m_Add(m_Value(X), m_Deferred(X)).
Definition at line 143 of file SDPatternMatch.h.
m_DisjointOr()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_DisjointOr (const LHS & L, const RHS & R) inline
Definition at line 785 of file SDPatternMatch.h.
References llvm::SDNodeFlags::Disjoint, LHS, llvm::ISD::OR, and RHS.
Referenced by m_AddLike().
m_ExtractElt()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_ExtractElt (const LHS & Vec, const RHS & Idx) inline
Definition at line 928 of file SDPatternMatch.h.
References llvm::ISD::EXTRACT_VECTOR_ELT, LHS, and RHS.
m_ExtractSubvector()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_ExtractSubvector (const LHS & Vec, const RHS & Idx) inline
Definition at line 933 of file SDPatternMatch.h.
References llvm::ISD::EXTRACT_SUBVECTOR, LHS, and RHS.
m_FAdd()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_FAdd (const LHS & L, const RHS & R) inline
Definition at line 892 of file SDPatternMatch.h.
References llvm::ISD::FADD, LHS, and RHS.
m_False()
auto llvm::SDPatternMatch::m_False () inline
Match false boolean value based on the information provided by TargetLowering.
Definition at line 1180 of file SDPatternMatch.h.
References llvm::TargetLoweringBase::getBooleanContents(), llvm::APInt::isZero(), m_ConstInt(), m_Value(), N, sd_match(), llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
m_FDiv()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_FDiv (const LHS & L, const RHS & R) inline
Definition at line 907 of file SDPatternMatch.h.
References llvm::ISD::FDIV, LHS, and RHS.
m_FixedVectorVT() [1/2]
auto llvm::SDPatternMatch::m_FixedVectorVT () inline
Definition at line 354 of file SDPatternMatch.h.
References m_Value().
m_FixedVectorVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_FixedVectorVT (const Pattern & P) inline
Match fixed-length vector ValueTypes.
Definition at line 351 of file SDPatternMatch.h.
References P.
m_FloatingPointVT() [1/2]
auto llvm::SDPatternMatch::m_FloatingPointVT () inline
Definition at line 337 of file SDPatternMatch.h.
References m_Value().
m_FloatingPointVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_FloatingPointVT (const Pattern & P) inline
Match any floating point ValueTypes.
Definition at line 334 of file SDPatternMatch.h.
References P.
m_FMul()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_FMul (const LHS & L, const RHS & R) inline
Definition at line 902 of file SDPatternMatch.h.
References llvm::ISD::FMUL, LHS, and RHS.
m_FPToSI()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_FPToSI (const Opnd & Op) inline
Definition at line 1051 of file SDPatternMatch.h.
References llvm::ISD::FP_TO_SINT.
m_FPToUI()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_FPToUI (const Opnd & Op) inline
Definition at line 1047 of file SDPatternMatch.h.
References llvm::ISD::FP_TO_UINT.
m_FRem()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_FRem (const LHS & L, const RHS & R) inline
Definition at line 912 of file SDPatternMatch.h.
References llvm::ISD::FREM, LHS, and RHS.
m_FSub()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_FSub (const LHS & L, const RHS & R) inline
Definition at line 897 of file SDPatternMatch.h.
References llvm::ISD::FSUB, LHS, and RHS.
m_Glue()
auto llvm::SDPatternMatch::m_Glue () inline
Definition at line 294 of file SDPatternMatch.h.
References m_SpecificVT().
m_InsertElt()
template<typename T0_P, typename T1_P, typename T2_P> TernaryOpc_match< T0_P, T1_P, T2_P > llvm::SDPatternMatch::m_InsertElt (const T0_P & Vec, const T1_P & Val, const T2_P & Idx) inline
Definition at line 570 of file SDPatternMatch.h.
References llvm::ISD::INSERT_VECTOR_ELT.
m_InsertSubvector()
template<typename LHS, typename RHS, typename IDX> TernaryOpc_match< LHS, RHS, IDX > llvm::SDPatternMatch::m_InsertSubvector (const LHS & Base, const RHS & Sub, const IDX & Idx) inline
Definition at line 577 of file SDPatternMatch.h.
References llvm::sampleprof::Base, llvm::ISD::INSERT_SUBVECTOR, LHS, and RHS.
Referenced by combineTargetShuffle().
m_IntegerVT() [1/2]
auto llvm::SDPatternMatch::m_IntegerVT () inline
Definition at line 329 of file SDPatternMatch.h.
References m_Value().
m_IntegerVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_IntegerVT (const Pattern & P) inline
Match any integer ValueTypes.
Definition at line 326 of file SDPatternMatch.h.
References P.
m_LegalOp()
template<typename Pattern> auto llvm::SDPatternMatch::m_LegalOp (const Pattern & P) inline
Match legal SDNodes based on the information provided by TargetLowering.
Definition at line 227 of file SDPatternMatch.h.
References llvm::TargetLoweringBase::isOperationLegal(), N, and P.
m_LegalType()
template<typename Pattern> auto llvm::SDPatternMatch::m_LegalType (const Pattern & P) inline
Match legal ValueTypes based on the information provided by TargetLowering.
Definition at line 369 of file SDPatternMatch.h.
References llvm::TargetLoweringBase::isTypeLegal(), N, and P.
m_Load()
template<typename T0_P, typename T1_P, typename T2_P> Result_match< 0, TernaryOpc_match< T0_P, T1_P, T2_P > > llvm::SDPatternMatch::m_Load (const T0_P & Ch, const T1_P & Ptr, const T2_P & Offset) inline
Definition at line 563 of file SDPatternMatch.h.
References m_Result(), llvm::Offset, and Ptr.
m_Mul()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_Mul (const LHS & L, const RHS & R) inline
Definition at line 770 of file SDPatternMatch.h.
References LHS, llvm::ISD::MUL, and RHS.
m_Neg()
template<typename ValTy> BinaryOpc_match< Zero_match, ValTy, false > llvm::SDPatternMatch::m_Neg (const ValTy & V) inline
Match a negate as a sub(0, v)
Definition at line 1233 of file SDPatternMatch.h.
References m_Sub(), and llvm::PatternMatch::m_Zero().
m_NNegZExt()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_NNegZExt (const Opnd & Op) inline
Definition at line 993 of file SDPatternMatch.h.
References llvm::SDNodeFlags::NonNeg, and llvm::ISD::ZERO_EXTEND.
Referenced by m_SExtLike().
m_Node()
template<typename... OpndPreds> auto llvm::SDPatternMatch::m_Node (unsigned Opcode, const OpndPreds &... preds)
Definition at line 471 of file SDPatternMatch.h.
References m_AllOf(), and m_Opc().
Referenced by combineAdd().
m_NoneOf()
template<typename... Preds> auto llvm::SDPatternMatch::m_NoneOf (const Preds &... preds)
Definition at line 437 of file SDPatternMatch.h.
References m_AnyOf(), and m_Unless().
m_Not()
template<typename ValTy> BinaryOpc_match< ValTy, AllOnes_match, true > llvm::SDPatternMatch::m_Not (const ValTy & V) inline
Match a Not as a xor(v, -1) or xor(-1, v)
Definition at line 1239 of file SDPatternMatch.h.
References llvm::PatternMatch::m_AllOnes(), and m_Xor().
m_NUses() [1/2]
template<unsigned N> NUses_match< N, Value_match > llvm::SDPatternMatch::m_NUses () inline
Definition at line 190 of file SDPatternMatch.h.
References m_Value().
m_NUses() [2/2]
template<unsigned N, typename Pattern> NUses_match< N, Pattern > llvm::SDPatternMatch::m_NUses (const Pattern & P) inline
Definition at line 183 of file SDPatternMatch.h.
References P.
m_One()
Ones_match llvm::SDPatternMatch::m_One (bool AllowUndefs = false) inline
Definition at line 1148 of file SDPatternMatch.h.
m_OneUse() [1/2]
NUses_match< 1, Value_match > llvm::SDPatternMatch::m_OneUse () inline
Definition at line 187 of file SDPatternMatch.h.
References m_Value().
Referenced by foldAndToUsubsat(), foldBitOrderCrossLogicOp(), foldMaskedMerge(), foldVSelectToSignBitSplatMask(), and visitORCommutative().
m_OneUse() [2/2]
template<typename Pattern> NUses_match< 1, Pattern > llvm::SDPatternMatch::m_OneUse (const Pattern & P) inline
Definition at line 179 of file SDPatternMatch.h.
References P.
m_Opc()
Opcode_match llvm::SDPatternMatch::m_Opc (unsigned Opcode) inline
Definition at line 158 of file SDPatternMatch.h.
Referenced by m_Node(), llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::match(), and matchPMADDWD().
m_Or()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_Or (const LHS & L, const RHS & R) inline
Definition at line 780 of file SDPatternMatch.h.
References LHS, llvm::ISD::OR, and RHS.
Referenced by m_BitwiseLogic().
m_OtherVT()
auto llvm::SDPatternMatch::m_OtherVT () inline
Definition at line 295 of file SDPatternMatch.h.
References m_SpecificVT().
m_Poison()
Opcode_match llvm::SDPatternMatch::m_Poison () inline
Definition at line 162 of file SDPatternMatch.h.
References llvm::ISD::POISON.
m_ReassociatableAdd()
template<typename... PatternTs> ReassociatableOpc_match< PatternTs... > llvm::SDPatternMatch::m_ReassociatableAdd (const PatternTs &... Patterns) inline
Definition at line 1302 of file SDPatternMatch.h.
References llvm::ISD::ADD.
m_ReassociatableAnd()
template<typename... PatternTs> ReassociatableOpc_match< PatternTs... > llvm::SDPatternMatch::m_ReassociatableAnd (const PatternTs &... Patterns) inline
Definition at line 1314 of file SDPatternMatch.h.
References llvm::ISD::AND.
m_ReassociatableMul()
template<typename... PatternTs> ReassociatableOpc_match< PatternTs... > llvm::SDPatternMatch::m_ReassociatableMul (const PatternTs &... Patterns) inline
Definition at line 1320 of file SDPatternMatch.h.
References llvm::ISD::MUL.
m_ReassociatableOr()
template<typename... PatternTs> ReassociatableOpc_match< PatternTs... > llvm::SDPatternMatch::m_ReassociatableOr (const PatternTs &... Patterns) inline
Definition at line 1308 of file SDPatternMatch.h.
References llvm::ISD::OR.
m_Result()
template<unsigned ResNo, typename Pattern> Result_match< ResNo, Pattern > llvm::SDPatternMatch::m_Result (const Pattern & P) inline
Match only if the SDValue is a certain result at ResNo.
Definition at line 124 of file SDPatternMatch.h.
References P.
Referenced by m_Load().
m_Rotl()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_Rotl (const LHS & L, const RHS & R) inline
Definition at line 882 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::ROTL.
m_Rotr()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_Rotr (const LHS & L, const RHS & R) inline
Definition at line 887 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::ROTR.
m_ScalableVectorVT() [1/2]
auto llvm::SDPatternMatch::m_ScalableVectorVT () inline
Definition at line 363 of file SDPatternMatch.h.
References m_Value().
m_ScalableVectorVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_ScalableVectorVT (const Pattern & P) inline
Match scalable vector ValueTypes.
Definition at line 360 of file SDPatternMatch.h.
References P.
m_SDiv()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_SDiv (const LHS & L, const RHS & R) inline
Definition at line 854 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SDIV.
m_Select()
template<typename T0_P, typename T1_P, typename T2_P> TernaryOpc_match< T0_P, T1_P, T2_P > llvm::SDPatternMatch::m_Select (const T0_P & Cond, const T1_P & T, const T2_P & F) inline
Definition at line 551 of file SDPatternMatch.h.
References Cond, F, llvm::ISD::SELECT, and T.
m_SetCC()
template<typename T0_P, typename T1_P, typename T2_P> TernaryOpc_match< T0_P, T1_P, T2_P > llvm::SDPatternMatch::m_SetCC (const T0_P & LHS, const T1_P & RHS, const T2_P & CC) inline
Definition at line 538 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SETCC.
Referenced by combineAnd(), combineSelect(), combineShiftLeft(), combineShiftRightLogical(), commuteSelect(), foldAddSubBoolOfMaskedVal(), and foldVSelectToSignBitSplatMask().
m_SExt()
template<typename Opnd> auto llvm::SDPatternMatch::m_SExt (const Opnd & Op) inline
Definition at line 997 of file SDPatternMatch.h.
References llvm::ISD::SIGN_EXTEND.
Referenced by m_SExtLike(), and m_SExtOrSelf().
m_SExtLike()
template<typename Opnd> auto llvm::SDPatternMatch::m_SExtLike (const Opnd & Op) inline
Definition at line 1025 of file SDPatternMatch.h.
References m_AnyOf(), m_NNegZExt(), and m_SExt().
m_SExtOrSelf()
template<typename Opnd> auto llvm::SDPatternMatch::m_SExtOrSelf (const Opnd & Op) inline
Match a sext or identity Allows to peek through optional extensions.
Definition at line 1021 of file SDPatternMatch.h.
References m_AnyOf(), and m_SExt().
m_Shl()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_Shl (const LHS & L, const RHS & R) inline
Definition at line 868 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SHL.
m_Shuffle() [1/2]
template<typename V1_t, typename V2_t> BinaryOpc_match< V1_t, V2_t > llvm::SDPatternMatch::m_Shuffle (const V1_t & v1, const V2_t & v2) inline
Definition at line 917 of file SDPatternMatch.h.
References llvm::ISD::VECTOR_SHUFFLE.
m_Shuffle() [2/2]
template<typename V1_t, typename V2_t, typename Mask_t> SDShuffle_match< V1_t, V2_t, Mask_t > llvm::SDPatternMatch::m_Shuffle (const V1_t & v1, const V2_t & v2, const Mask_t & mask) inline
Definition at line 923 of file SDPatternMatch.h.
m_SMax()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_SMax (const LHS & L, const RHS & R) inline
Definition at line 817 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SMAX.
m_SMaxLike()
template<typename LHS, typename RHS> auto llvm::SDPatternMatch::m_SMaxLike (const LHS & L, const RHS & R) inline
Definition at line 822 of file SDPatternMatch.h.
References LHS, m_AnyOf(), RHS, and llvm::ISD::SMAX.
m_SMin()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_SMin (const LHS & L, const RHS & R) inline
Definition at line 806 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SMIN.
m_SMinLike()
template<typename LHS, typename RHS> auto llvm::SDPatternMatch::m_SMinLike (const LHS & L, const RHS & R) inline
Definition at line 811 of file SDPatternMatch.h.
References LHS, m_AnyOf(), RHS, and llvm::ISD::SMIN.
m_Specific()
Value_match llvm::SDPatternMatch::m_Specific (SDValue N) inline
Definition at line 106 of file SDPatternMatch.h.
References assert(), and N.
m_SpecificCondCode()
CondCode_match llvm::SDPatternMatch::m_SpecificCondCode (ISD::CondCode CC) inline
Match a conditional code SDNode with a specific ISD::CondCode.
Definition at line 1227 of file SDPatternMatch.h.
Referenced by combineSelect(), combineShiftLeft(), combineShiftRightLogical(), foldAddSubBoolOfMaskedVal(), isTruncateOf(), and performAnyAllCombine().
m_SpecificInt() [1/2]
SpecificInt_match llvm::SDPatternMatch::m_SpecificInt (APInt V) inline
Match a specific integer constant or constant splat value.
Definition at line 1110 of file SDPatternMatch.h.
m_SpecificInt() [2/2]
SpecificInt_match llvm::SDPatternMatch::m_SpecificInt (uint64_t V) inline
Definition at line 1113 of file SDPatternMatch.h.
m_SpecificScalarVT() [1/2]
auto llvm::SDPatternMatch::m_SpecificScalarVT (EVT RefVT) inline
Definition at line 303 of file SDPatternMatch.h.
References m_Value().
m_SpecificScalarVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_SpecificScalarVT (EVT RefVT, const Pattern & P) inline
Match a scalar ValueType.
Definition at line 299 of file SDPatternMatch.h.
References P.
m_SpecificVectorElementVT() [1/2]
auto llvm::SDPatternMatch::m_SpecificVectorElementVT (EVT RefVT) inline
Definition at line 317 of file SDPatternMatch.h.
References m_Value().
m_SpecificVectorElementVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_SpecificVectorElementVT (EVT RefVT, const Pattern & P) inline
Match a vector ValueType.
Definition at line 310 of file SDPatternMatch.h.
References P.
Referenced by combineBasicSADPattern().
m_SpecificVT() [1/2]
auto llvm::SDPatternMatch::m_SpecificVT (EVT RefVT) inline
Definition at line 290 of file SDPatternMatch.h.
References m_Value().
m_SpecificVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_SpecificVT (EVT RefVT, const Pattern & P) inline
Match a specific ValueType.
Definition at line 287 of file SDPatternMatch.h.
References P.
Referenced by combineAdd(), combineAnd(), combineCastedMaskArithmetic(), combineSCALAR_TO_VECTOR(), m_Glue(), and m_OtherVT().
m_Sra()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_Sra (const LHS & L, const RHS & R) inline
Definition at line 873 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SRA.
Referenced by foldAndToUsubsat().
m_SRem()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_SRem (const LHS & L, const RHS & R) inline
Definition at line 863 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SREM.
m_Srl()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_Srl (const LHS & L, const RHS & R) inline
Definition at line 877 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SRL.
Referenced by combineAdd(), combinePMULH(), and reverseZExtICmpCombine().
m_Sub()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_Sub (const LHS & L, const RHS & R) inline
Definition at line 765 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::SUB.
Referenced by m_Neg().
m_True()
auto llvm::SDPatternMatch::m_True () inline
Match true boolean value based on the information provided by TargetLowering.
Definition at line 1160 of file SDPatternMatch.h.
References llvm::TargetLoweringBase::getBooleanContents(), llvm::APInt::isAllOnes(), llvm::APInt::isOne(), m_ConstInt(), m_Value(), N, sd_match(), llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
m_Trunc()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_Trunc (const Opnd & Op) inline
Definition at line 1005 of file SDPatternMatch.h.
References llvm::ISD::TRUNCATE.
Referenced by m_TruncOrSelf().
m_TruncOrSelf()
template<typename Opnd> Or< UnaryOpc_match< Opnd >, Opnd > llvm::SDPatternMatch::m_TruncOrSelf (const Opnd & Op) inline
Match a trunc or identity Allows to peek through optional truncations.
Definition at line 1039 of file SDPatternMatch.h.
References m_Trunc().
m_UDiv()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_UDiv (const LHS & L, const RHS & R) inline
Definition at line 850 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::UDIV.
m_UMax()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_UMax (const LHS & L, const RHS & R) inline
Definition at line 839 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::UMAX.
m_UMaxLike()
template<typename LHS, typename RHS> auto llvm::SDPatternMatch::m_UMaxLike (const LHS & L, const RHS & R) inline
Definition at line 844 of file SDPatternMatch.h.
References LHS, m_AnyOf(), RHS, and llvm::ISD::UMAX.
m_UMin()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_UMin (const LHS & L, const RHS & R) inline
Definition at line 828 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::UMIN.
m_UMinLike()
template<typename LHS, typename RHS> auto llvm::SDPatternMatch::m_UMinLike (const LHS & L, const RHS & R) inline
Definition at line 833 of file SDPatternMatch.h.
References LHS, m_AnyOf(), RHS, and llvm::ISD::UMIN.
m_UnaryOp()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_UnaryOp (unsigned Opc, const Opnd & Op) inline
Definition at line 965 of file SDPatternMatch.h.
References Opc.
Referenced by foldBitOrderCrossLogicOp().
m_Undef()
Opcode_match llvm::SDPatternMatch::m_Undef () inline
Definition at line 160 of file SDPatternMatch.h.
References llvm::ISD::UNDEF.
m_Unless()
template<typename Pred> Not< Pred > llvm::SDPatternMatch::m_Unless (const Pred & P) inline
Match if the inner pattern does NOT match.
Definition at line 425 of file SDPatternMatch.h.
References P.
Referenced by m_NoneOf().
m_URem()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS > llvm::SDPatternMatch::m_URem (const LHS & L, const RHS & R) inline
Definition at line 859 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::UREM.
m_Value() [1/2]
Value_match llvm::SDPatternMatch::m_Value () inline
Match any valid SDValue.
Definition at line 104 of file SDPatternMatch.h.
Referenced by m_False(), m_FixedVectorVT(), m_FloatingPointVT(), m_IntegerVT(), m_NUses(), m_OneUse(), m_ScalableVectorVT(), m_SpecificScalarVT(), m_SpecificVectorElementVT(), m_SpecificVT(), m_True(), and m_VectorVT().
m_Value() [2/2]
Value_bind llvm::SDPatternMatch::m_Value (SDValue & N) inline
Definition at line 205 of file SDPatternMatch.h.
References N.
m_VectorVT() [1/2]
auto llvm::SDPatternMatch::m_VectorVT () inline
Definition at line 346 of file SDPatternMatch.h.
References m_Value().
m_VectorVT() [2/2]
template<typename Pattern> auto llvm::SDPatternMatch::m_VectorVT (const Pattern & P) inline
Match any vector ValueTypes.
Definition at line 343 of file SDPatternMatch.h.
References P.
m_VScale()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_VScale (const Opnd & Op) inline
Definition at line 1043 of file SDPatternMatch.h.
m_VSelect()
template<typename T0_P, typename T1_P, typename T2_P> TernaryOpc_match< T0_P, T1_P, T2_P > llvm::SDPatternMatch::m_VSelect (const T0_P & Cond, const T1_P & T, const T2_P & F) inline
Definition at line 557 of file SDPatternMatch.h.
References Cond, F, T, and llvm::ISD::VSELECT.
Referenced by commuteSelect().
m_VT()
ValueType_bind llvm::SDPatternMatch::m_VT (EVT & VT) inline
Retreive the ValueType of the current SDValue.
Definition at line 265 of file SDPatternMatch.h.
m_Xor()
template<typename LHS, typename RHS> BinaryOpc_match< LHS, RHS, true > llvm::SDPatternMatch::m_Xor (const LHS & L, const RHS & R) inline
Definition at line 796 of file SDPatternMatch.h.
References LHS, RHS, and llvm::ISD::XOR.
Referenced by m_BitwiseLogic(), and m_Not().
m_Zero()
Zero_match llvm::SDPatternMatch::m_Zero (bool AllowUndefs = false) inline
Definition at line 1151 of file SDPatternMatch.h.
m_ZExt()
template<typename Opnd> UnaryOpc_match< Opnd > llvm::SDPatternMatch::m_ZExt (const Opnd & Op) inline
Definition at line 988 of file SDPatternMatch.h.
References llvm::ISD::ZERO_EXTEND.
Referenced by m_ZExtOrSelf().
m_ZExtOrSelf()
template<typename Opnd> auto llvm::SDPatternMatch::m_ZExtOrSelf (const Opnd & Op) inline
Match a zext or identity Allows to peek through optional extensions.
Definition at line 1015 of file SDPatternMatch.h.
References m_AnyOf(), and m_ZExt().
Not()
template<typename Pred> llvm::SDPatternMatch::Not (const Pred & P) -> Not< Pred >
References P.
sd_context_match() [1/2]
template<typename Pattern, typename MatchContext> bool llvm::SDPatternMatch::sd_context_match (SDNode * N, const MatchContext & Ctx, Pattern && P) nodiscard
Definition at line 63 of file SDPatternMatch.h.
References N, P, sd_context_match(), and SDValue().
sd_context_match() [2/2]
template<typename Pattern, typename MatchContext> bool llvm::SDPatternMatch::sd_context_match (SDValue N, const MatchContext & Ctx, Pattern && P) nodiscard
Definition at line 57 of file SDPatternMatch.h.
References N, and P.
Referenced by foldSubCtlzNot(), llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >::match(), llvm::SDPatternMatch::SpecificInt_match::match(), llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::match(), sd_context_match(), sd_match(), and sd_match().
sd_match() [1/4]
template<typename Pattern> bool llvm::SDPatternMatch::sd_match (SDNode * N, const SelectionDAG * DAG, Pattern && P) nodiscard
Definition at line 69 of file SDPatternMatch.h.
References N, P, and sd_context_match().
Referenced by combineAdd(), combineAnd(), combineAndNotOrIntoAndNotAnd(), combineAndXorSubWithBMI(), combineBasicSADPattern(), combineCastedMaskArithmetic(), combineLogicBlendIntoConditionalNegate(), combinePMULH(), combineSCALAR_TO_VECTOR(), combineSelect(), combineShiftLeft(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShiftToPMULH(), combineShlAddIAddImpl(), combineTargetShuffle(), commuteSelect(), detectSSatPattern(), detectSSatSPattern(), detectSSatUPattern(), detectUSatPattern(), detectUSatUPattern(), foldAddSubBoolOfMaskedVal(), foldAndToUsubsat(), foldBitOrderCrossLogicOp(), foldMaskedMerge(), foldVSelectToSignBitSplatMask(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), isTruncateOf(), m_False(), m_True(), matchLogicBlend(), matchPMADDWD(), matchPMADDWD_2(), performAnyAllCombine(), performBitcastCombine(), reverseZExtICmpCombine(), sd_match(), sd_match(), llvm::X86TargetLowering::shouldFoldSelectWithIdentityConstant(), and visitORCommutative().
sd_match() [2/4]
template<typename Pattern> bool llvm::SDPatternMatch::sd_match (SDNode * N, Pattern && P) nodiscard
Definition at line 79 of file SDPatternMatch.h.
References N, P, and sd_match().
sd_match() [3/4]
template<typename Pattern> bool llvm::SDPatternMatch::sd_match (SDValue N, const SelectionDAG * DAG, Pattern && P) nodiscard
Definition at line 74 of file SDPatternMatch.h.
References N, P, and sd_context_match().
sd_match() [4/4]
template<typename Pattern> bool llvm::SDPatternMatch::sd_match (SDValue N, Pattern && P) nodiscard
Definition at line 84 of file SDPatternMatch.h.
References N, P, and sd_match().
TLI_pred_match()
template<typename PredFuncT, typename Pattern> llvm::SDPatternMatch::TLI_pred_match (const PredFuncT & Pred, const Pattern & P) -> TLI_pred_match< Pattern, PredFuncT >
References P.
ValueType_match()
template<typename PredFuncT, typename Pattern> llvm::SDPatternMatch::ValueType_match (const PredFuncT & Pred, const Pattern & P) -> ValueType_match< Pattern, PredFuncT >
References P.