LLVM: llvm::mcdwarf Namespace Reference
llvm::mcdwarf Namespace Reference
Functions
LLVM_ABI MCSymbol * emitListsTableHeaderStart (MCStreamer &S)
Function Documentation
emitListsTableHeaderStart()
MCSymbol * llvm::mcdwarf::emitListsTableHeaderStart (MCStreamer & S)
Definition at line 44 of file MCDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCContext::createTempSymbol(), llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfFormat(), llvm::dwarf::getDwarfOffsetByteSize(), and llvm::MCContext::getDwarfVersion().
Referenced by emitGenDwarfRanges(), emitLoclistsTableHeader(), and emitRnglistsTableHeader().