LLVM: LLVMOrcLazyCallThroughManagerRef Namespace Reference
LLVMOrcLazyCallThroughManagerRef Namespace Reference
Classes
class OrcCAPIMaterializationUnit
Functions
static JITSymbolFlags toJITSymbolFlags (LLVMJITSymbolFlags F)
static LLVMJITSymbolFlags fromJITSymbolFlags (JITSymbolFlags JSF)
static SymbolNameSet toSymbolNameSet (LLVMOrcCSymbolsList Symbols)
static SymbolMap toSymbolMap (LLVMOrcCSymbolMapPairs Syms, size_t NumPairs)
static SymbolDependenceMap toSymbolDependenceMap (LLVMOrcCDependenceMapPairs Pairs, size_t NumPairs)
static LookupKind toLookupKind (LLVMOrcLookupKind K)
static LLVMOrcLookupKind fromLookupKind (LookupKind K)
static JITDylibLookupFlags toJITDylibLookupFlags (LLVMOrcJITDylibLookupFlags LF)
static LLVMOrcJITDylibLookupFlags fromJITDylibLookupFlags (JITDylibLookupFlags LF)
static SymbolLookupFlags toSymbolLookupFlags (LLVMOrcSymbolLookupFlags SLF)
static LLVMOrcSymbolLookupFlags fromSymbolLookupFlags (SymbolLookupFlags SLF)
static LLVMJITEvaluatedSymbol fromExecutorSymbolDef (const ExecutorSymbolDef &S)
Function Documentation
fromExecutorSymbolDef()
LLVMJITEvaluatedSymbol LLVMOrcLazyCallThroughManagerRef::fromExecutorSymbolDef (const ExecutorSymbolDef & S) static
Definition at line 251 of file OrcV2CBindings.cpp.
References fromExecutorSymbolDef(), fromJITSymbolFlags(), llvm::orc::ExecutorSymbolDef::getAddress(), llvm::orc::ExecutorSymbolDef::getFlags(), and llvm::orc::ExecutorAddr::getValue().
Referenced by fromExecutorSymbolDef().
fromJITDylibLookupFlags()
LLVMOrcJITDylibLookupFlags LLVMOrcLazyCallThroughManagerRef::fromJITDylibLookupFlags (JITDylibLookupFlags LF) static
Definition at line 220 of file OrcV2CBindings.cpp.
References fromJITDylibLookupFlags(), llvm_unreachable, LLVMOrcJITDylibLookupFlagsMatchAllSymbols, LLVMOrcJITDylibLookupFlagsMatchExportedSymbolsOnly, llvm::orc::MatchAllSymbols, and llvm::orc::MatchExportedSymbolsOnly.
Referenced by fromJITDylibLookupFlags().
fromJITSymbolFlags()
LLVMJITSymbolFlags LLVMOrcLazyCallThroughManagerRef::fromJITSymbolFlags (JITSymbolFlags JSF) static
Definition at line 138 of file OrcV2CBindings.cpp.
References llvm::JITSymbolFlags::Callable, llvm::JITSymbolFlags::Exported, F, fromJITSymbolFlags(), llvm::JITSymbolFlags::getTargetFlags(), LLVMJITSymbolGenericFlagsCallable, LLVMJITSymbolGenericFlagsExported, LLVMJITSymbolGenericFlagsMaterializationSideEffectsOnly, LLVMJITSymbolGenericFlagsWeak, llvm::JITSymbolFlags::MaterializationSideEffectsOnly, and llvm::JITSymbolFlags::Weak.
Referenced by fromExecutorSymbolDef(), and fromJITSymbolFlags().
fromLookupKind()
LLVMOrcLookupKind LLVMOrcLazyCallThroughManagerRef::fromLookupKind (LookupKind K) static
Definition at line 198 of file OrcV2CBindings.cpp.
References llvm::orc::DLSym, fromLookupKind(), llvm_unreachable, LLVMOrcLookupKindDLSym, LLVMOrcLookupKindStatic, and llvm::orc::Static.
Referenced by fromLookupKind().
fromSymbolLookupFlags()
LLVMOrcSymbolLookupFlags LLVMOrcLazyCallThroughManagerRef::fromSymbolLookupFlags (SymbolLookupFlags SLF) static
Definition at line 240 of file OrcV2CBindings.cpp.
References fromSymbolLookupFlags(), llvm_unreachable, LLVMOrcSymbolLookupFlagsRequiredSymbol, LLVMOrcSymbolLookupFlagsWeaklyReferencedSymbol, llvm::orc::RequiredSymbol, and llvm::orc::WeaklyReferencedSymbol.
Referenced by fromSymbolLookupFlags().
toJITDylibLookupFlags()
JITDylibLookupFlags LLVMOrcLazyCallThroughManagerRef::toJITDylibLookupFlags (LLVMOrcJITDylibLookupFlags LF) static
Definition at line 209 of file OrcV2CBindings.cpp.
References llvm_unreachable, LLVMOrcJITDylibLookupFlagsMatchAllSymbols, LLVMOrcJITDylibLookupFlagsMatchExportedSymbolsOnly, llvm::orc::MatchAllSymbols, llvm::orc::MatchExportedSymbolsOnly, and toJITDylibLookupFlags().
Referenced by toJITDylibLookupFlags().
toJITSymbolFlags()
JITSymbolFlags LLVMOrcLazyCallThroughManagerRef::toJITSymbolFlags (LLVMJITSymbolFlags F) static
Definition at line 120 of file OrcV2CBindings.cpp.
References llvm::JITSymbolFlags::Callable, llvm::JITSymbolFlags::Exported, F, llvm::JITSymbolFlags::getTargetFlags(), LLVMJITSymbolGenericFlagsCallable, LLVMJITSymbolGenericFlagsExported, LLVMJITSymbolGenericFlagsMaterializationSideEffectsOnly, LLVMJITSymbolGenericFlagsWeak, llvm::JITSymbolFlags::MaterializationSideEffectsOnly, toJITSymbolFlags(), and llvm::JITSymbolFlags::Weak.
Referenced by toJITSymbolFlags(), and toSymbolMap().
toLookupKind()
LookupKind LLVMOrcLazyCallThroughManagerRef::toLookupKind (LLVMOrcLookupKind K) static
Definition at line 188 of file OrcV2CBindings.cpp.
References llvm::orc::DLSym, llvm_unreachable, LLVMOrcLookupKindDLSym, LLVMOrcLookupKindStatic, llvm::orc::Static, and toLookupKind().
Referenced by toLookupKind().
toSymbolDependenceMap()
SymbolDependenceMap LLVMOrcLazyCallThroughManagerRef::toSymbolDependenceMap (LLVMOrcCDependenceMapPairs Pairs, size_t NumPairs) static
Definition at line 173 of file OrcV2CBindings.cpp.
References I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), LLVMOrcCSymbolsList::Length, LLVMOrcCDependenceMapPair::Names, LLVMOrcCSymbolsList::Symbols, toSymbolDependenceMap(), and llvm::unwrap().
Referenced by toSymbolDependenceMap().
toSymbolLookupFlags()
SymbolLookupFlags LLVMOrcLazyCallThroughManagerRef::toSymbolLookupFlags (LLVMOrcSymbolLookupFlags SLF) static
Definition at line 230 of file OrcV2CBindings.cpp.
References llvm_unreachable, LLVMOrcSymbolLookupFlagsRequiredSymbol, LLVMOrcSymbolLookupFlagsWeaklyReferencedSymbol, llvm::orc::RequiredSymbol, toSymbolLookupFlags(), and llvm::orc::WeaklyReferencedSymbol.
Referenced by toSymbolLookupFlags().
toSymbolMap()
SymbolMap LLVMOrcLazyCallThroughManagerRef::toSymbolMap (LLVMOrcCSymbolMapPairs Syms, size_t NumPairs) static
Definition at line 162 of file OrcV2CBindings.cpp.
References I, toJITSymbolFlags(), toSymbolMap(), and llvm::unwrap().
Referenced by toSymbolMap().
toSymbolNameSet()
SymbolNameSet LLVMOrcLazyCallThroughManagerRef::toSymbolNameSet (LLVMOrcCSymbolsList Symbols) static
Definition at line 154 of file OrcV2CBindings.cpp.
References I, llvm::orc::Result, toSymbolNameSet(), and llvm::unwrap().
Referenced by toSymbolNameSet().