LLVM: llvm::mc Namespace Reference
llvm::mc Namespace Reference
Classes
struct RegisterMCTargetOptionsFlags
Create this object with static storage to register mc-related command line options.
Functions
bool isRelocation (MCFixupKind FixupKind)
bool isRelocRelocation (MCFixupKind FixupKind)
LLVM_ABI bool getRelaxAll ()
LLVM_ABI std::optional< bool > getExplicitRelaxAll ()
LLVM_ABI bool getIncrementalLinkerCompatible ()
LLVM_ABI bool getFDPIC ()
LLVM_ABI int getDwarfVersion ()
LLVM_ABI bool getDwarf64 ()
LLVM_ABI EmitDwarfUnwindType getEmitDwarfUnwind ()
LLVM_ABI bool getEmitCompactUnwindNonCanonical ()
LLVM_ABI bool getShowMCInst ()
LLVM_ABI bool getFatalWarnings ()
LLVM_ABI bool getNoWarn ()
LLVM_ABI bool getNoDeprecatedWarn ()
LLVM_ABI bool getNoTypeCheck ()
LLVM_ABI bool getSaveTempLabels ()
LLVM_ABI bool getCrel ()
LLVM_ABI bool getImplicitMapSyms ()
LLVM_ABI bool getX86RelaxRelocations ()
LLVM_ABI bool getX86Sse2Avx ()
LLVM_ABI std::string getABIName ()
LLVM_ABI std::string getAsSecureLogFile ()
LLVM_ABI MCTargetOptions InitMCTargetOptionsFromFlags ()
Function Documentation
getABIName()
LLVM_ABI std::string llvm::mc::getABIName ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getAsSecureLogFile()
LLVM_ABI std::string llvm::mc::getAsSecureLogFile ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getCrel()
LLVM_ABI bool llvm::mc::getCrel ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getDwarf64()
LLVM_ABI bool llvm::mc::getDwarf64 ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getDwarfVersion()
LLVM_ABI int llvm::mc::getDwarfVersion ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getEmitCompactUnwindNonCanonical()
LLVM_ABI bool llvm::mc::getEmitCompactUnwindNonCanonical ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getEmitDwarfUnwind()
LLVM_ABI EmitDwarfUnwindType llvm::mc::getEmitDwarfUnwind ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getExplicitRelaxAll()
LLVM_ABI std::optional< bool > llvm::mc::getExplicitRelaxAll ()
References LLVM_ABI.
getFatalWarnings()
LLVM_ABI bool llvm::mc::getFatalWarnings ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getFDPIC()
LLVM_ABI bool llvm::mc::getFDPIC ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getImplicitMapSyms()
LLVM_ABI bool llvm::mc::getImplicitMapSyms ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getIncrementalLinkerCompatible()
LLVM_ABI bool llvm::mc::getIncrementalLinkerCompatible ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getNoDeprecatedWarn()
LLVM_ABI bool llvm::mc::getNoDeprecatedWarn ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getNoTypeCheck()
LLVM_ABI bool llvm::mc::getNoTypeCheck ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getNoWarn()
LLVM_ABI bool llvm::mc::getNoWarn ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getRelaxAll()
LLVM_ABI bool llvm::mc::getRelaxAll ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getSaveTempLabels()
LLVM_ABI bool llvm::mc::getSaveTempLabels ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getShowMCInst()
LLVM_ABI bool llvm::mc::getShowMCInst ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getX86RelaxRelocations()
LLVM_ABI bool llvm::mc::getX86RelaxRelocations ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
getX86Sse2Avx()
LLVM_ABI bool llvm::mc::getX86Sse2Avx ()
References LLVM_ABI.
Referenced by InitMCTargetOptionsFromFlags().
InitMCTargetOptionsFromFlags()
MCTargetOptions llvm::mc::InitMCTargetOptionsFromFlags ()
Definition at line 171 of file MCTargetOptionsCommandFlags.cpp.
References getABIName(), getAsSecureLogFile(), getCrel(), getDwarf64(), getDwarfVersion(), getEmitCompactUnwindNonCanonical(), getEmitDwarfUnwind(), getFatalWarnings(), getFDPIC(), getImplicitMapSyms(), getIncrementalLinkerCompatible(), getNoDeprecatedWarn(), getNoTypeCheck(), getNoWarn(), getRelaxAll(), getSaveTempLabels(), getShowMCInst(), getX86RelaxRelocations(), getX86Sse2Avx(), and Options.
Referenced by llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), and llvm::codegen::InitTargetOptionsFromCodeGenFlags().
isRelocation()
bool llvm::mc::isRelocation (MCFixupKind FixupKind) inline
Definition at line 130 of file MCFixup.h.
References llvm::FixupKind(), and llvm::FK_NONE.
Referenced by llvm::ARMAsmBackend::applyFixup(), llvm::AVRAsmBackend::applyFixup(), llvm::CSKYAsmBackend::applyFixup(), llvm::LoongArchAsmBackend::applyFixup(), llvm::RISCVAsmBackend::applyFixup(), llvm::ARMAsmBackend::getFixupKindInfo(), llvm::AVRAsmBackend::getFixupKindInfo(), llvm::CSKYAsmBackend::getFixupKindInfo(), llvm::LoongArchAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), llvm::RISCVAsmBackend::getFixupKindInfo(), and getPCRelHiFixup().
isRelocRelocation()
bool llvm::mc::isRelocRelocation (MCFixupKind FixupKind) inline
Definition at line 135 of file MCFixup.h.
References llvm::FirstLiteralRelocationKind, llvm::FixupKind(), and llvm::FK_NONE.
Referenced by llvm::ELFObjectWriter::recordRelocation().