LLVM: llvm::objcopy::macho Namespace Reference
llvm::objcopy::macho Namespace Reference
Classes
struct BindInfo
The location of the bind info inside the binary is described by LC_DYLD_INFO load command.
struct CodeSignatureInfo
When MachO binaries include a LC_CODE_SIGNATURE load command, the __LINKEDIT data segment will include a section corresponding to the LC_CODE_SIGNATURE load command.
struct ExportInfo
The location of the export info inside the binary is described by LC_DYLD_INFO load command.
struct IndirectSymbolEntry
struct IndirectSymbolTable
struct LazyBindInfo
The location of the lazy bind info inside the binary is described by LC_DYLD_INFO load command.
struct LinkData
struct LoadCommand
struct MachHeader
class MachOLayoutBuilder
class MachOReader
class MachOWriter
struct Object
class Reader
struct RebaseInfo
The location of the rebase info inside the binary is described by LC_DYLD_INFO load command.
struct RelocationInfo
struct Section
struct StringTable
The location of the string table inside the binary is described by LC_SYMTAB load command.
struct SymbolEntry
struct SymbolTable
The location of the symbol table inside the binary is described by LC_SYMTAB load command.
struct WeakBindInfo
The location of the weak bind info inside the binary is described by LC_DYLD_INFO load command.
Functions
LLVM_ABI Error executeObjcopyOnBinary (const CommonConfig &Config, const MachOConfig &MachOConfig, object::MachOObjectFile &In, raw_ostream &Out)
Apply the transformations described by Config and MachOConfig to In and writes the result into Out.
LLVM_ABI Error executeObjcopyOnMachOUniversalBinary (const MultiFormatConfig &Config, const object::MachOUniversalBinary &In, raw_ostream &Out)
Apply the transformations described by Config and MachOConfig to In and writes the result into Out.
Function Documentation
executeObjcopyOnBinary()
Error llvm::objcopy::macho::executeObjcopyOnBinary (const CommonConfig & Config, const MachOConfig & MachOConfig, object::MachOObjectFile & In, raw_ostream & Out)
Apply the transformations described by Config and MachOConfig to In and writes the result into Out.
Returns
any Error encountered whilst performing the operation.
Definition at line 486 of file MachOObjcopy.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::Triple::arm, llvm::objcopy::macho::Reader::create(), llvm::createFileError(), llvm::createStringError(), llvm::sys::path::filename(), llvm::objcopy::macho::MachOWriter::finalize(), handleArgs(), llvm::objcopy::CommonConfig::InputFilename, llvm::MachO::MH_PRELOAD, llvm::objcopy::CommonConfig::OutputFilename, PageSize, llvm::StringRef::str(), and llvm::objcopy::macho::MachOWriter::write().
Referenced by llvm::objcopy::executeObjcopyOnBinary(), and executeObjcopyOnMachOUniversalBinary().
executeObjcopyOnMachOUniversalBinary()
Error llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary (const MultiFormatConfig & Config, const object::MachOUniversalBinary & In, raw_ostream & Out)
Apply the transformations described by Config and MachOConfig to In and writes the result into Out.
Returns
any Error encountered whilst performing the operation.
Definition at line 523 of file MachOObjcopy.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::cast(), llvm::consumeError(), llvm::object::createBinary(), llvm::objcopy::createNewArchiveMembers(), llvm::createStringError(), llvm::objcopy::CommonConfig::DeterministicArchives, llvm::SmallVectorImpl< T >::emplace_back(), executeObjcopyOnBinary(), llvm::objcopy::MultiFormatConfig::getCommonConfig(), llvm::objcopy::MultiFormatConfig::getMachOConfig(), llvm::objcopy::CommonConfig::InputFilename, llvm::object::Archive::K_BSD, llvm::object::Archive::K_DARWIN, llvm::NormalSymtab, llvm::NoSymtab, llvm::StringRef::str(), llvm::Error::success(), llvm::Expected< T >::takeError(), llvm::writeArchiveToBuffer(), and llvm::object::writeUniversalBinaryToStream().
Referenced by llvm::objcopy::executeObjcopyOnBinary().