LLVM: llvm::DomTreeBuilder Namespace Reference
llvm::DomTreeBuilder Namespace Reference
Classes
struct SemiNCAInfo
Typedefs
using MBBDomTree = DomTreeBase<MachineBasicBlock>
using MBBUpdates = ArrayRef<llvm::cfg::Update<MachineBasicBlock *>>
using MBBDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, false>
using MBBPostDomTree = PostDomTreeBase<MachineBasicBlock>
using MBBPostDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, true>
using BBDomTree = DomTreeBase<BasicBlock>
using BBPostDomTree = PostDomTreeBase<BasicBlock>
using BBUpdates = ArrayRef<llvm::cfg::Update<BasicBlock *>>
using BBDomTreeGraphDiff = GraphDiff<BasicBlock *, false>
using BBPostDomTreeGraphDiff = GraphDiff<BasicBlock *, true>
Functions
template LLVM_TEMPLATE_ABI void Calculate< MBBDomTree > (MBBDomTree &DT)
template LLVM_TEMPLATE_ABI void CalculateWithUpdates< MBBDomTree > (MBBDomTree &DT, MBBUpdates U)
template LLVM_TEMPLATE_ABI void InsertEdge< MBBDomTree > (MBBDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template LLVM_TEMPLATE_ABI void DeleteEdge< MBBDomTree > (MBBDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template LLVM_TEMPLATE_ABI void ApplyUpdates< MBBDomTree > (MBBDomTree &DT, MBBDomTreeGraphDiff &, MBBDomTreeGraphDiff *)
template LLVM_TEMPLATE_ABI bool Verify< MBBDomTree > (const MBBDomTree &DT, MBBDomTree::VerificationLevel VL)
template LLVM_TEMPLATE_ABI void Calculate< MBBPostDomTree > (MBBPostDomTree &DT)
template LLVM_TEMPLATE_ABI void InsertEdge< MBBPostDomTree > (MBBPostDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template LLVM_TEMPLATE_ABI void DeleteEdge< MBBPostDomTree > (MBBPostDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template LLVM_TEMPLATE_ABI void ApplyUpdates< MBBPostDomTree > (MBBPostDomTree &DT, MBBPostDomTreeGraphDiff &, MBBPostDomTreeGraphDiff *)
template LLVM_TEMPLATE_ABI bool Verify< MBBPostDomTree > (const MBBPostDomTree &DT, MBBPostDomTree::VerificationLevel VL)
template LLVM_TEMPLATE_ABI void Calculate< BBDomTree > (BBDomTree &DT)
template LLVM_TEMPLATE_ABI void CalculateWithUpdates< BBDomTree > (BBDomTree &DT, BBUpdates U)
template LLVM_TEMPLATE_ABI void Calculate< BBPostDomTree > (BBPostDomTree &DT)
template LLVM_TEMPLATE_ABI void InsertEdge< BBDomTree > (BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_TEMPLATE_ABI void InsertEdge< BBPostDomTree > (BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_TEMPLATE_ABI void DeleteEdge< BBDomTree > (BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_TEMPLATE_ABI void DeleteEdge< BBPostDomTree > (BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template LLVM_TEMPLATE_ABI void ApplyUpdates< BBDomTree > (BBDomTree &DT, BBDomTreeGraphDiff &, BBDomTreeGraphDiff *)
template LLVM_TEMPLATE_ABI void ApplyUpdates< BBPostDomTree > (BBPostDomTree &DT, BBPostDomTreeGraphDiff &, BBPostDomTreeGraphDiff *)
template LLVM_TEMPLATE_ABI bool Verify< BBDomTree > (const BBDomTree &DT, BBDomTree::VerificationLevel VL)
template LLVM_TEMPLATE_ABI bool Verify< BBPostDomTree > (const BBPostDomTree &DT, BBPostDomTree::VerificationLevel VL)
template<typename DomTreeT>
void Calculate (DomTreeT &DT)
template<typename DomTreeT>
void CalculateWithUpdates (DomTreeT &DT, ArrayRef< typename DomTreeT::UpdateType > Updates)
template<typename DomTreeT>
void InsertEdge (DomTreeT &DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
template<typename DomTreeT>
void DeleteEdge (DomTreeT &DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
template<typename DomTreeT>
void ApplyUpdates (DomTreeT &DT, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > &PreViewCFG, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > *PostViewCFG)
template<typename DomTreeT>
bool Verify (const DomTreeT &DT, typename DomTreeT::VerificationLevel VL)
Typedef Documentation
BBDomTree
using llvm::DomTreeBuilder::BBDomTree = DomTreeBase<BasicBlock>
Definition at line 56 of file Dominators.h.
BBDomTreeGraphDiff
using llvm::DomTreeBuilder::BBDomTreeGraphDiff = GraphDiff<BasicBlock *, false>
Definition at line 61 of file Dominators.h.
BBPostDomTree
using llvm::DomTreeBuilder::BBPostDomTree = PostDomTreeBase<BasicBlock>
Definition at line 57 of file Dominators.h.
BBPostDomTreeGraphDiff
using llvm::DomTreeBuilder::BBPostDomTreeGraphDiff = GraphDiff<BasicBlock *, true>
Definition at line 62 of file Dominators.h.
BBUpdates
using llvm::DomTreeBuilder::BBUpdates = ArrayRef<llvm::cfg::Update<BasicBlock *>>
Definition at line 59 of file Dominators.h.
MBBDomTree
using llvm::DomTreeBuilder::MBBDomTree = DomTreeBase<MachineBasicBlock>
Definition at line 43 of file MachineDominators.h.
MBBDomTreeGraphDiff
using llvm::DomTreeBuilder::MBBDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, false>
Definition at line 45 of file MachineDominators.h.
MBBPostDomTree
using llvm::DomTreeBuilder::MBBPostDomTree = PostDomTreeBase<MachineBasicBlock>
Definition at line 26 of file MachinePostDominators.h.
MBBPostDomTreeGraphDiff
using llvm::DomTreeBuilder::MBBPostDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, true>
Definition at line 27 of file MachinePostDominators.h.
MBBUpdates
using llvm::DomTreeBuilder::MBBUpdates = ArrayRef<llvm::cfg::Update<MachineBasicBlock *>>
Definition at line 44 of file MachineDominators.h.
Function Documentation
ApplyUpdates()
template<typename DomTreeT> void llvm::DomTreeBuilder::ApplyUpdates (DomTreeT & DT, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > & PreViewCFG, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > * PostViewCFG)
Definition at line 1582 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates().
Referenced by llvm::DominatorTreeBase< BlockT, false >::applyUpdates(), llvm::DominatorTreeBase< BlockT, false >::applyUpdates(), ApplyUpdates< BBDomTree >(), ApplyUpdates< BBPostDomTree >(), ApplyUpdates< MBBDomTree >(), ApplyUpdates< MBBPostDomTree >(), llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBDomTree >(), and llvm::DomTreeBuilder::ApplyUpdates< DomTreeBuilder::BBPostDomTree >().
ApplyUpdates< BBDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::ApplyUpdates< BBDomTree > (BBDomTree & DT, BBDomTreeGraphDiff & , BBDomTreeGraphDiff *) extern
References ApplyUpdates(), and LLVM_TEMPLATE_ABI.
ApplyUpdates< BBPostDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::ApplyUpdates< BBPostDomTree > (BBPostDomTree & DT, BBPostDomTreeGraphDiff & , BBPostDomTreeGraphDiff *) extern
References ApplyUpdates(), and LLVM_TEMPLATE_ABI.
ApplyUpdates< MBBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::ApplyUpdates< MBBDomTree > (MBBDomTree & DT, MBBDomTreeGraphDiff & , MBBDomTreeGraphDiff *) extern
References ApplyUpdates(), and LLVM_TEMPLATE_ABI.
ApplyUpdates< MBBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::ApplyUpdates< MBBPostDomTree > (MBBPostDomTree & DT, MBBPostDomTreeGraphDiff & , MBBPostDomTreeGraphDiff *) extern
References ApplyUpdates(), and LLVM_TEMPLATE_ABI.
Calculate()
template<typename DomTreeT> void llvm::DomTreeBuilder::Calculate (DomTreeT & DT)
Definition at line 1552 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch().
Referenced by Calculate< BBDomTree >(), Calculate< BBPostDomTree >(), Calculate< MBBDomTree >(), Calculate< MBBPostDomTree >(), llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBDomTree >(), llvm::DomTreeBuilder::Calculate< DomTreeBuilder::BBPostDomTree >(), and llvm::DominatorTreeBase< BlockT, false >::recalculate().
Calculate< BBDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::Calculate< BBDomTree > (BBDomTree & DT) extern
References Calculate(), and LLVM_TEMPLATE_ABI.
Calculate< BBPostDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::Calculate< BBPostDomTree > (BBPostDomTree & DT) extern
References Calculate(), and LLVM_TEMPLATE_ABI.
Calculate< MBBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::Calculate< MBBDomTree > (MBBDomTree & DT) extern
References Calculate(), and LLVM_TEMPLATE_ABI.
Calculate< MBBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::Calculate< MBBPostDomTree > (MBBPostDomTree & DT) extern
References Calculate(), and LLVM_TEMPLATE_ABI.
CalculateWithUpdates()
template<typename DomTreeT> void llvm::DomTreeBuilder::CalculateWithUpdates (DomTreeT & DT, ArrayRef< typename DomTreeT::UpdateType > Updates)
Definition at line 1557 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch().
Referenced by CalculateWithUpdates< BBDomTree >(), CalculateWithUpdates< MBBDomTree >(), llvm::DomTreeBuilder::CalculateWithUpdates< DomTreeBuilder::BBDomTree >(), and llvm::DominatorTreeBase< BlockT, false >::recalculate().
CalculateWithUpdates< BBDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::CalculateWithUpdates< BBDomTree > (BBDomTree & DT, BBUpdates U) extern
References CalculateWithUpdates(), and LLVM_TEMPLATE_ABI.
CalculateWithUpdates< MBBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::CalculateWithUpdates< MBBDomTree > (MBBDomTree & DT, MBBUpdates U) extern
References CalculateWithUpdates(), and LLVM_TEMPLATE_ABI.
DeleteEdge()
template<typename DomTreeT> void llvm::DomTreeBuilder::DeleteEdge (DomTreeT & DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
Definition at line 1575 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), and std::swap().
Referenced by llvm::DominatorTreeBase< BlockT, false >::deleteEdge(), DeleteEdge< BBDomTree >(), DeleteEdge< BBPostDomTree >(), DeleteEdge< MBBDomTree >(), DeleteEdge< MBBPostDomTree >(), llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBDomTree >(), and llvm::DomTreeBuilder::DeleteEdge< DomTreeBuilder::BBPostDomTree >().
DeleteEdge< BBDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::DeleteEdge< BBDomTree > (BBDomTree & DT, BasicBlock * From, BasicBlock * To) extern
References DeleteEdge(), and LLVM_TEMPLATE_ABI.
DeleteEdge< BBPostDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::DeleteEdge< BBPostDomTree > (BBPostDomTree & DT, BasicBlock * From, BasicBlock * To) extern
References DeleteEdge(), and LLVM_TEMPLATE_ABI.
DeleteEdge< MBBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::DeleteEdge< MBBDomTree > (MBBDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
References DeleteEdge(), and LLVM_TEMPLATE_ABI.
DeleteEdge< MBBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::DeleteEdge< MBBPostDomTree > (MBBPostDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
References DeleteEdge(), and LLVM_TEMPLATE_ABI.
InsertEdge()
template<typename DomTreeT> void llvm::DomTreeBuilder::InsertEdge (DomTreeT & DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
Definition at line 1568 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), and std::swap().
Referenced by llvm::DominatorTreeBase< BlockT, false >::insertEdge(), InsertEdge< BBDomTree >(), InsertEdge< BBPostDomTree >(), InsertEdge< MBBDomTree >(), InsertEdge< MBBPostDomTree >(), llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBDomTree >(), and llvm::DomTreeBuilder::InsertEdge< DomTreeBuilder::BBPostDomTree >().
InsertEdge< BBDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::InsertEdge< BBDomTree > (BBDomTree & DT, BasicBlock * From, BasicBlock * To) extern
References InsertEdge(), and LLVM_TEMPLATE_ABI.
InsertEdge< BBPostDomTree >()
template LLVM_TEMPLATE_ABI void llvm::DomTreeBuilder::InsertEdge< BBPostDomTree > (BBPostDomTree & DT, BasicBlock * From, BasicBlock * To) extern
References InsertEdge(), and LLVM_TEMPLATE_ABI.
InsertEdge< MBBDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::InsertEdge< MBBDomTree > (MBBDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
References InsertEdge(), and LLVM_TEMPLATE_ABI.
InsertEdge< MBBPostDomTree >()
template LLVM_EXPORT_TEMPLATE void llvm::DomTreeBuilder::InsertEdge< MBBPostDomTree > (MBBPostDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
References InsertEdge(), and LLVM_TEMPLATE_ABI.
Verify()
template<typename DomTreeT> bool llvm::DomTreeBuilder::Verify (const DomTreeT & DT, typename DomTreeT::VerificationLevel VL)
Definition at line 1591 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsSameAsFreshTree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
Referenced by llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBDomTree >(), llvm::DomTreeBuilder::Verify< DomTreeBuilder::BBPostDomTree >(), llvm::DominatorTreeBase< BlockT, false >::verify(), Verify< BBDomTree >(), Verify< BBPostDomTree >(), Verify< MBBDomTree >(), and Verify< MBBPostDomTree >().
Verify< BBDomTree >()
template LLVM_TEMPLATE_ABI bool llvm::DomTreeBuilder::Verify< BBDomTree > (const BBDomTree & DT, BBDomTree::VerificationLevel VL) extern
References LLVM_TEMPLATE_ABI, and Verify().
Verify< BBPostDomTree >()
template LLVM_TEMPLATE_ABI bool llvm::DomTreeBuilder::Verify< BBPostDomTree > (const BBPostDomTree & DT, BBPostDomTree::VerificationLevel VL) extern
References LLVM_TEMPLATE_ABI, and Verify().
Verify< MBBDomTree >()
template LLVM_EXPORT_TEMPLATE bool llvm::DomTreeBuilder::Verify< MBBDomTree > (const MBBDomTree & DT, MBBDomTree::VerificationLevel VL) extern
References LLVM_TEMPLATE_ABI, and Verify().
Verify< MBBPostDomTree >()
template LLVM_EXPORT_TEMPLATE bool llvm::DomTreeBuilder::Verify< MBBPostDomTree > (const MBBPostDomTree & DT, MBBPostDomTree::VerificationLevel VL) extern
References LLVM_TEMPLATE_ABI, and Verify().