LLVM: llvm::hlsl::rootsig Namespace Reference
llvm::hlsl::rootsig Namespace Reference
Classes
struct DescriptorTable
struct DescriptorTableClause
class MetadataBuilder
struct OverlappingRanges
struct RangeInfo
struct Register
class ResourceRange
struct RootConstants
struct RootDescriptor
struct StaticSampler
Typedefs
using ClauseType = llvm::dxil::ResourceClass
using RootElement
Models RootElement : RootFlags | RootConstants | RootParam | DescriptorTable | DescriptorTableClause | StaticSampler.
Enumerations
enum class RegisterType { BReg , TReg , UReg , SReg }
enum class DescriptorType : uint8_t { SRV = 0 , UAV , CBuffer }
Functions
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const dxbc::RootFlags &Flags)
The following contains the serialization interface for root elements.
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const RootConstants &Constants)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const DescriptorTableClause &Clause)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const DescriptorTable &Table)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const RootDescriptor &Descriptor)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const StaticSampler &StaticSampler)
LLVM_ABI raw_ostream & operator<< (raw_ostream &OS, const RootElement &Element)
LLVM_ABI void dumpRootElements (raw_ostream &OS, ArrayRef< RootElement > Elements)
LLVM_ABI bool verifyRootFlag (uint32_t Flags)
LLVM_ABI bool verifyVersion (uint32_t Version)
LLVM_ABI bool verifyRegisterValue (uint32_t RegisterValue)
LLVM_ABI bool verifyRegisterSpace (uint32_t RegisterSpace)
LLVM_ABI bool verifyRootDescriptorFlag (uint32_t Version, uint32_t FlagsVal)
LLVM_ABI bool verifyRangeType (uint32_t Type)
LLVM_ABI bool verifyDescriptorRangeFlag (uint32_t Version, uint32_t Type, uint32_t FlagsVal)
LLVM_ABI bool verifyNumDescriptors (uint32_t NumDescriptors)
LLVM_ABI bool verifySamplerFilter (uint32_t Value)
LLVM_ABI bool verifyAddress (uint32_t Address)
LLVM_ABI bool verifyMipLODBias (float MipLODBias)
LLVM_ABI bool verifyMaxAnisotropy (uint32_t MaxAnisotropy)
LLVM_ABI bool verifyComparisonFunc (uint32_t ComparisonFunc)
LLVM_ABI bool verifyBorderColor (uint32_t BorderColor)
LLVM_ABI bool verifyLOD (float LOD)
LLVM_ABI llvm::SmallVector< OverlappingRanges > findOverlappingRanges (ArrayRef< RangeInfo > Infos)
The following conducts analysis on resource ranges to detect and report any overlaps in resource ranges.
template<typename T>
static std::optional< StringRef > getEnumName (const T Value, ArrayRef< EnumEntry< T > > Enums)
template<typename T>
static raw_ostream & printEnum (raw_ostream &OS, const T Value, ArrayRef< EnumEntry< T > > Enums)
template<typename T>
static raw_ostream & printFlags (raw_ostream &OS, const T Value, ArrayRef< EnumEntry< T > > Flags)
static raw_ostream & operator<< (raw_ostream &OS, const Register &Reg)
static raw_ostream & operator<< (raw_ostream &OS, const llvm::dxbc::ShaderVisibility &Visibility)
static raw_ostream & operator<< (raw_ostream &OS, const llvm::dxbc::SamplerFilter &Filter)
static raw_ostream & operator<< (raw_ostream &OS, const dxbc::TextureAddressMode &Address)
static raw_ostream & operator<< (raw_ostream &OS, const dxbc::ComparisonFunc &CompFunc)
static raw_ostream & operator<< (raw_ostream &OS, const dxbc::StaticBorderColor &BorderColor)
static raw_ostream & operator<< (raw_ostream &OS, const ClauseType &Type)
static raw_ostream & operator<< (raw_ostream &OS, const dxbc::RootDescriptorFlags &Flags)
static raw_ostream & operator<< (raw_ostream &OS, const llvm::dxbc::DescriptorRangeFlags &Flags)
static std::optional< StringRef > getResourceName (dxil::ResourceClass Class)
Variables
static const uint32_t NumDescriptorsUnbounded = 0xffffffff
static const uint32_t DescriptorTableOffsetAppend = 0xffffffff
static const EnumEntry< RegisterType > RegisterNames []
static const EnumEntry< dxil::ResourceClass > ResourceClassNames []
static const EnumEntry< dxil::ResourceClass > ResourceClassNames []
Typedef Documentation
ClauseType
using llvm::hlsl::rootsig::ClauseType = llvm::dxil::ResourceClass
Definition at line 85 of file HLSLRootSignature.h.
RootElement
using llvm::hlsl::rootsig::RootElement
Initial value:
    std::variant<dxbc::RootFlags, RootConstants, RootDescriptor,
                 DescriptorTable, DescriptorTableClause, StaticSampler>
Models RootElement : RootFlags | RootConstants | RootParam | DescriptorTable | DescriptorTableClause | StaticSampler.
A Root Signature is modeled in-memory by an array of RootElements. These aim to map closely to their DSL grammar reprsentation defined in the spec.
Each optional parameter has its default value defined in the struct, and, each mandatory parameter does not have a default initialization.
For the variants RootFlags, RootConstants, RootParam, StaticSampler and DescriptorTableClause: each data member maps directly to a parameter in the grammar.
The DescriptorTable is modelled by having its Clauses as the previous RootElements in the array, and it holds a data member for the Visibility parameter.
Definition at line 151 of file HLSLRootSignature.h.
Enumeration Type Documentation
DescriptorType
enum class llvm::hlsl::rootsig::DescriptorType : uint8_t strong
Enumerator
SRV
UAV
CBuffer
Definition at line 45 of file HLSLRootSignature.h.
RegisterType
enum class llvm::hlsl::rootsig::RegisterType strong
Enumerator
BReg
TReg
UReg
SReg
Definition at line 31 of file HLSLRootSignature.h.
Function Documentation
dumpRootElements()
void llvm::hlsl::rootsig::dumpRootElements (raw_ostream & OS, ArrayRef< RootElement > Elements)
Definition at line 230 of file HLSLRootSignature.cpp.
References llvm::First.
findOverlappingRanges()
llvm::SmallVector< OverlappingRanges > llvm::hlsl::rootsig::findOverlappingRanges (ArrayRef< RangeInfo > Infos)
The following conducts analysis on resource ranges to detect and report any overlaps in resource ranges.
A resource range overlaps with another resource range if they have:
equivalent ResourceClass (SRV, UAV, CBuffer, Sampler)
equivalent resource space
overlapping visbility
The algorithm is implemented in the following steps:
The user will collect RangeInfo from relevant RootElements:
RangeInfo will retain the interval, ResourceClass, Space and Visibility
It will also contain an index so that it can be associated to additional diagnostic information
The user is required to sort the RangeInfo's such that they are grouped together by ResourceClass and Space
Iterate through the collected RangeInfos by their groups
For each group we will have a ResourceRange for each visibility
As we iterate through we will: A: Insert the current RangeInfo into the corresponding Visibility ResourceRange B: Check for overlap with any overlapping Visibility ResourceRange
Definition at line 247 of file RootSignatureValidations.cpp.
References Allocator, assert(), llvm::ArrayRef< T >::drop_front(), Info, llvm::hlsl::rootsig::ResourceRange::insert(), llvm::is_sorted(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Range, llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::take_front(), and llvm::to_underlying().
getEnumName()
template<typename T> std::optional< StringRef > llvm::hlsl::rootsig::getEnumName (const T Value, ArrayRef< EnumEntry< T > > Enums) static
Definition at line 21 of file HLSLRootSignature.cpp.
References T.
Referenced by printEnum(), and printFlags().
getResourceName()
std::optional< StringRef > llvm::hlsl::rootsig::getResourceName (dxil::ResourceClass Class) static
Definition at line 30 of file RootSignatureMetadata.cpp.
References ResourceClassNames.
operator<<() [1/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const ClauseType & Type) static
Definition at line 121 of file HLSLRootSignature.cpp.
References llvm::ArrayRef(), printEnum(), ResourceClassNames, and llvm::to_underlying().
operator<<() [2/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const DescriptorTable & Table)
Definition at line 158 of file HLSLRootSignature.cpp.
References llvm::hlsl::rootsig::DescriptorTable::NumClauses, and llvm::hlsl::rootsig::DescriptorTable::Visibility.
operator<<() [3/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const DescriptorTableClause & Clause)
Definition at line 165 of file HLSLRootSignature.cpp.
References DescriptorTableOffsetAppend, and NumDescriptorsUnbounded.
operator<<() [4/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const dxbc::ComparisonFunc & CompFunc) static
Definition at line 100 of file HLSLRootSignature.cpp.
References llvm::dxbc::getComparisonFuncs(), and printEnum().
operator<<() [5/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const dxbc::RootDescriptorFlags & Flags) static
Definition at line 128 of file HLSLRootSignature.cpp.
References llvm::dxbc::getRootDescriptorFlags(), and printFlags().
operator<<() [6/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const dxbc::RootFlags & Flags)
The following contains the serialization interface for root elements.
Definition at line 142 of file HLSLRootSignature.cpp.
References llvm::dxbc::getRootFlags(), and printFlags().
operator<<() [7/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const dxbc::StaticBorderColor & BorderColor) static
Definition at line 107 of file HLSLRootSignature.cpp.
References llvm::dxbc::getStaticBorderColors(), and printEnum().
operator<<() [8/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const dxbc::TextureAddressMode & Address) static
Definition at line 93 of file HLSLRootSignature.cpp.
References llvm::Address, llvm::dxbc::getTextureAddressModes(), and printEnum().
operator<<() [9/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const llvm::dxbc::DescriptorRangeFlags & Flags) static
Definition at line 135 of file HLSLRootSignature.cpp.
References llvm::dxbc::getDescriptorRangeFlags(), and printFlags().
operator<<() [10/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const llvm::dxbc::SamplerFilter & Filter) static
Definition at line 86 of file HLSLRootSignature.cpp.
References llvm::Filter, llvm::dxbc::getSamplerFilters(), and printEnum().
operator<<() [11/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const llvm::dxbc::ShaderVisibility & Visibility) static
Definition at line 79 of file HLSLRootSignature.cpp.
References llvm::dxbc::getShaderVisibility(), and printEnum().
operator<<() [12/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const Register & Reg) static
Definition at line 72 of file HLSLRootSignature.cpp.
References printEnum(), Reg, and RegisterNames.
operator<<() [13/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const RootConstants & Constants)
Definition at line 150 of file HLSLRootSignature.cpp.
operator<<() [14/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const RootDescriptor & Descriptor)
Definition at line 181 of file HLSLRootSignature.cpp.
References llvm::hlsl::rootsig::RootDescriptor::Flags, llvm::hlsl::rootsig::RootDescriptor::Reg, llvm::hlsl::rootsig::RootDescriptor::Space, llvm::to_underlying(), llvm::hlsl::rootsig::RootDescriptor::Type, and llvm::hlsl::rootsig::RootDescriptor::Visibility.
operator<<() [15/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const RootElement & Element)
Definition at line 217 of file HLSLRootSignature.cpp.
operator<<() [16/16]
raw_ostream & llvm::hlsl::rootsig::operator<< (raw_ostream & OS, const StaticSampler & StaticSampler)
Definition at line 191 of file HLSLRootSignature.cpp.
printEnum()
template<typename T> raw_ostream & llvm::hlsl::rootsig::printEnum (raw_ostream & OS, const T Value, ArrayRef< EnumEntry< T > > Enums) static
Definition at line 30 of file HLSLRootSignature.cpp.
References getEnumName(), and T.
Referenced by operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), and operator<<().
printFlags()
template<typename T> raw_ostream & llvm::hlsl::rootsig::printFlags (raw_ostream & OS, const T Value, ArrayRef< EnumEntry< T > > Flags) static
Definition at line 39 of file HLSLRootSignature.cpp.
References llvm::countr_zero(), getEnumName(), T, and llvm::to_underlying().
Referenced by operator<<(), operator<<(), and operator<<().
verifyAddress()
bool llvm::hlsl::rootsig::verifyAddress (uint32_t Address)
Definition at line 143 of file RootSignatureValidations.cpp.
References llvm::Address.
Referenced by validate().
verifyBorderColor()
bool llvm::hlsl::rootsig::verifyBorderColor (uint32_t BorderColor)
Definition at line 171 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyComparisonFunc()
bool llvm::hlsl::rootsig::verifyComparisonFunc (uint32_t ComparisonFunc)
Definition at line 161 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyDescriptorRangeFlag()
bool llvm::hlsl::rootsig::verifyDescriptorRangeFlag (uint32_t Version, uint32_t Type, uint32_t FlagsVal)
Definition at line 66 of file RootSignatureValidations.cpp.
References llvm::popcount(), llvm::to_underlying(), and llvm::Version.
Referenced by validate().
verifyLOD()
bool llvm::hlsl::rootsig::verifyLOD (float LOD)
Definition at line 181 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyMaxAnisotropy()
bool llvm::hlsl::rootsig::verifyMaxAnisotropy (uint32_t MaxAnisotropy)
Definition at line 157 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyMipLODBias()
bool llvm::hlsl::rootsig::verifyMipLODBias (float MipLODBias)
Definition at line 153 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyNumDescriptors()
bool llvm::hlsl::rootsig::verifyNumDescriptors (uint32_t NumDescriptors)
Definition at line 128 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyRangeType()
bool llvm::hlsl::rootsig::verifyRangeType (uint32_t Type)
Definition at line 54 of file RootSignatureValidations.cpp.
References llvm::to_underlying().
Referenced by validate().
verifyRegisterSpace()
bool llvm::hlsl::rootsig::verifyRegisterSpace (uint32_t RegisterSpace)
Definition at line 31 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyRegisterValue()
bool llvm::hlsl::rootsig::verifyRegisterValue (uint32_t RegisterValue)
Definition at line 25 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyRootDescriptorFlag()
bool llvm::hlsl::rootsig::verifyRootDescriptorFlag (uint32_t Version, uint32_t FlagsVal)
Definition at line 35 of file RootSignatureValidations.cpp.
References assert(), llvm::popcount(), llvm::to_underlying(), and llvm::Version.
Referenced by validate().
verifyRootFlag()
bool llvm::hlsl::rootsig::verifyRootFlag (uint32_t Flags)
Definition at line 21 of file RootSignatureValidations.cpp.
Referenced by validate().
verifySamplerFilter()
bool llvm::hlsl::rootsig::verifySamplerFilter (uint32_t Value)
Definition at line 132 of file RootSignatureValidations.cpp.
Referenced by validate().
verifyVersion()
bool llvm::hlsl::rootsig::verifyVersion (uint32_t Version)
Definition at line 23 of file RootSignatureValidations.cpp.
References llvm::Version.
Referenced by validate().
Variable Documentation
DescriptorTableOffsetAppend
const uint32_t llvm::hlsl::rootsig::DescriptorTableOffsetAppend = 0xffffffff static
Definition at line 83 of file HLSLRootSignature.h.
Referenced by operator<<().
NumDescriptorsUnbounded
const uint32_t llvm::hlsl::rootsig::NumDescriptorsUnbounded = 0xffffffff static
Definition at line 82 of file HLSLRootSignature.h.
Referenced by operator<<().
RegisterNames
const EnumEntry<RegisterType> llvm::hlsl::rootsig::RegisterNames[] static
Initial value:
= {
    {"b", RegisterType::BReg},
    {"t", RegisterType::TReg},
    {"u", RegisterType::UReg},
    {"s", RegisterType::SReg},
}
Definition at line 65 of file HLSLRootSignature.cpp.
Referenced by operator<<().
ResourceClassNames [1/2]
const EnumEntry<dxil::ResourceClass> llvm::hlsl::rootsig::ResourceClassNames[] static
Initial value:
= {
    {"CBV", dxil::ResourceClass::CBuffer},
    {"SRV", dxil::ResourceClass::SRV},
    {"UAV", dxil::ResourceClass::UAV},
    {"Sampler", dxil::ResourceClass::Sampler},
}
Definition at line 114 of file HLSLRootSignature.cpp.
Referenced by getResourceName(), and operator<<().
ResourceClassNames [2/2]
const EnumEntry<dxil::ResourceClass> llvm::hlsl::rootsig::ResourceClassNames[] static
Initial value:
= {
    {"CBV", dxil::ResourceClass::CBuffer},
    {"SRV", dxil::ResourceClass::SRV},
    {"UAV", dxil::ResourceClass::UAV},
    {"Sampler", dxil::ResourceClass::Sampler},
}
Definition at line 23 of file RootSignatureMetadata.cpp.