LLVM: llvm::memtag Namespace Reference
llvm::memtag Namespace Reference
Classes
struct AllocaInfo
struct StackInfo
class StackInfoBuilder
Enumerations
enum class AllocaInterestingness { kUninteresting , kSafe , kInteresting }
Functions
bool forAllReachableExits (const DominatorTree &DT, const PostDominatorTree &PDT, const LoopInfo &LI, const Instruction *Start, const SmallVectorImpl< IntrinsicInst * > &Ends, const SmallVectorImpl< Instruction * > &RetVec, llvm::function_ref< void(Instruction *)> Callback)
bool isStandardLifetime (const SmallVectorImpl< IntrinsicInst * > &LifetimeStart, const SmallVectorImpl< IntrinsicInst * > &LifetimeEnd, const DominatorTree *DT, const LoopInfo *LI, size_t MaxLifetimes)
Instruction * getUntagLocationIfFunctionExit (Instruction &Inst)
uint64_t getAllocaSizeInBytes (const AllocaInst &AI)
void alignAndPadAlloca (memtag::AllocaInfo &Info, llvm::Align Align)
Value * readRegister (IRBuilder<> &IRB, StringRef Name)
Value * getFP (IRBuilder<> &IRB)
Value * getPC (const Triple &TargetTriple, IRBuilder<> &IRB)
Value * getAndroidSlotPtr (IRBuilder<> &IRB, int Slot)
void annotateDebugRecords (AllocaInfo &Info, unsigned int Tag)
Value * incrementThreadLong (IRBuilder<> &IRB, Value *ThreadLong, unsigned int Inc)
static DbgAssignIntrinsic * DynCastToDbgAssign (DbgVariableIntrinsic *DVI)
static DbgVariableRecord * DynCastToDbgAssign (DbgVariableRecord *DVR)
Enumeration Type Documentation
AllocaInterestingness
enum class llvm::memtag::AllocaInterestingness strong
Enumerator
kUninteresting
kSafe
kInteresting
Definition at line 68 of file MemoryTaggingSupport.h.
Function Documentation
alignAndPadAlloca()
void llvm::memtag::alignAndPadAlloca (memtag::AllocaInfo & Info, llvm::Align Align)
Definition at line 224 of file MemoryTaggingSupport.cpp.
References llvm::alignTo(), llvm::cast(), llvm::ArrayType::get(), llvm::StructType::get(), getAllocaSizeInBytes(), llvm::Type::getInt8Ty(), Info, and Size.
annotateDebugRecords()
void llvm::memtag::annotateDebugRecords (AllocaInfo & Info, unsigned int Tag)
Definition at line 308 of file MemoryTaggingSupport.cpp.
References llvm::DIExpression::appendOpsToArg(), llvm::dwarf::DW_OP_LLVM_tag_offset, DynCastToDbgAssign(), llvm::for_each(), Info, llvm::DIExpression::prependOpcodes(), and llvm::Tag.
DynCastToDbgAssign() [1/2]
DbgAssignIntrinsic * llvm::memtag::DynCastToDbgAssign (DbgVariableIntrinsic * DVI) static
Definition at line 300 of file MemoryTaggingSupport.cpp.
References llvm::dyn_cast().
Referenced by annotateDebugRecords().
DynCastToDbgAssign() [2/2]
DbgVariableRecord * llvm::memtag::DynCastToDbgAssign (DbgVariableRecord * DVR) static
Definition at line 304 of file MemoryTaggingSupport.cpp.
References llvm::DbgVariableRecord::isDbgAssign().
forAllReachableExits()
bool llvm::memtag::forAllReachableExits (const DominatorTree & DT, const PostDominatorTree & PDT, const LoopInfo & LI, const Instruction * Start, const SmallVectorImpl< IntrinsicInst * > & Ends, const SmallVectorImpl< Instruction * > & RetVec, llvm::function_ref< void(Instruction *)> Callback)
Definition at line 48 of file MemoryTaggingSupport.cpp.
References llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::PostDominatorTree::dominates(), llvm::for_each(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isPotentiallyReachable(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
getAllocaSizeInBytes()
uint64_t llvm::memtag::getAllocaSizeInBytes (const AllocaInst & AI)
Definition at line 219 of file MemoryTaggingSupport.cpp.
References DL, llvm::AllocaInst::getAllocationSize(), and llvm::Instruction::getDataLayout().
Referenced by alignAndPadAlloca(), and llvm::memtag::StackInfoBuilder::getAllocaInterestingness().
getAndroidSlotPtr()
Value * llvm::memtag::getAndroidSlotPtr (IRBuilder<> & IRB, int Slot)
Definition at line 289 of file MemoryTaggingSupport.cpp.
References llvm::IRBuilderBase::CreateCall(), llvm::IRBuilderBase::CreateConstGEP1_32(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getInt8Ty(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), and llvm::IRBuilderBase::getPtrTy().
getFP()
Value * llvm::memtag::getFP (IRBuilder<> & IRB)
Definition at line 279 of file MemoryTaggingSupport.cpp.
References llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreatePtrToInt(), F, llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getIntPtrTy(), llvm::BasicBlock::getParent(), and llvm::IRBuilderBase::getPtrTy().
getPC()
Value * llvm::memtag::getPC (const Triple & TargetTriple, IRBuilder<> & IRB)
Definition at line 271 of file MemoryTaggingSupport.cpp.
References llvm::Triple::aarch64, llvm::IRBuilderBase::CreatePtrToInt(), llvm::Triple::getArch(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getIntPtrTy(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), and readRegister().
getUntagLocationIfFunctionExit()
Instruction * llvm::memtag::getUntagLocationIfFunctionExit (Instruction & Inst)
Definition at line 102 of file MemoryTaggingSupport.cpp.
References llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), and llvm::isa().
Referenced by llvm::memtag::StackInfoBuilder::visit().
incrementThreadLong()
Value * llvm::memtag::incrementThreadLong (IRBuilder<> & IRB, Value * ThreadLong, unsigned int Inc)
Definition at line 332 of file MemoryTaggingSupport.cpp.
References assert(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateXor(), and llvm::Value::getType().
isStandardLifetime()
bool llvm::memtag::isStandardLifetime (const SmallVectorImpl< IntrinsicInst * > & LifetimeStart, const SmallVectorImpl< IntrinsicInst * > & LifetimeEnd, const DominatorTree * DT, const LoopInfo * LI, size_t MaxLifetimes)
Definition at line 89 of file MemoryTaggingSupport.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
readRegister()
Value * llvm::memtag::readRegister (IRBuilder<> & IRB, StringRef Name)
Definition at line 262 of file MemoryTaggingSupport.cpp.
References llvm::IRBuilderBase::CreateIntrinsic(), llvm::MDNode::get(), llvm::MetadataAsValue::get(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getIntPtrTy(), llvm::BasicBlock::getParent(), and llvm::GlobalValue::getParent().
Referenced by getPC().