LLVM: llvm::AArch64SysReg Namespace Reference
llvm::AArch64SysReg Namespace Reference
Classes
struct SysReg
Functions
uint32_t parseGenericRegister (StringRef Name)
std::string genericRegisterString (uint32_t Bits)
Function Documentation
genericRegisterString()
std::string llvm::AArch64SysReg::genericRegisterString (uint32_t Bits)
Definition at line 169 of file AArch64BaseInfo.cpp.
References assert(), and llvm::utostr().
Referenced by llvm::AArch64InstPrinter::printMRSSystemRegister(), and llvm::AArch64InstPrinter::printMSRSystemRegister().
parseGenericRegister()
uint32_t llvm::AArch64SysReg::parseGenericRegister (StringRef Name)
Definition at line 148 of file AArch64BaseInfo.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, and llvm::Regex::match().