LLVM: llvm::dxbc Namespace Reference
llvm::dxbc Namespace Reference
Namespaces
namespace PSV
namespace RTS0
Classes
struct AmplificationPSVInfo
struct BitcodeHeader
struct ContainerVersion
struct DomainPSVInfo
struct GeometryPSVInfo
struct Hash
struct Header
struct HullPSVInfo
struct MeshPSVInfo
struct PartHeader
Use this type to describe the size and type of a DXIL container part.
union PipelinePSVInfo
struct PixelPSVInfo
struct ProgramHeader
struct ProgramSignatureElement
struct ProgramSignatureHeader
struct ShaderHash
struct VertexPSVInfo
Enumerations
enum class HashFlags : uint32_t { None = 0 , IncludesSource = 1 }
enum class PartType { Unknown = 0 }
enum class FeatureFlags : uint64_t
enum class RootFlags : uint32_t
enum class RootDescriptorFlags : uint32_t
enum class DescriptorRangeFlags : uint32_t
enum class RootParameterType : uint32_t
enum class DescriptorRangeType : uint32_t
enum class ShaderVisibility : uint32_t
enum class SamplerFilter : uint32_t
enum class TextureAddressMode : uint32_t
enum class ComparisonFunc : uint32_t
enum class StaticBorderColor : uint32_t
enum class SigMinPrecision : uint32_t
enum class D3DSystemValue : uint32_t
enum class SigComponentType : uint32_t
enum class RootSignatureVersion { V1_0 = 0x1 , V1_1 = 0x2 }
Functions
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
Triple::EnvironmentType getShaderStage (uint32_t Kind)
LLVM_ABI ArrayRef< EnumEntry< RootFlags > > getRootFlags ()
LLVM_ABI ArrayRef< EnumEntry< RootDescriptorFlags > > getRootDescriptorFlags ()
LLVM_ABI ArrayRef< EnumEntry< DescriptorRangeFlags > > getDescriptorRangeFlags ()
LLVM_ABI ArrayRef< EnumEntry< RootParameterType > > getRootParameterTypes ()
LLVM_ABI ArrayRef< EnumEntry< DescriptorRangeType > > getDescriptorRangeTypes ()
bool isValidParameterType (uint32_t V)
LLVM_ABI ArrayRef< EnumEntry< ShaderVisibility > > getShaderVisibility ()
bool isValidShaderVisibility (uint32_t V)
LLVM_ABI ArrayRef< EnumEntry< SamplerFilter > > getSamplerFilters ()
LLVM_ABI ArrayRef< EnumEntry< TextureAddressMode > > getTextureAddressModes ()
LLVM_ABI ArrayRef< EnumEntry< ComparisonFunc > > getComparisonFuncs ()
LLVM_ABI ArrayRef< EnumEntry< StaticBorderColor > > getStaticBorderColors ()
LLVM_ABI PartType parsePartType (StringRef S)
LLVM_ABI ArrayRef< EnumEntry< SigMinPrecision > > getSigMinPrecisions ()
LLVM_ABI ArrayRef< EnumEntry< D3DSystemValue > > getD3DSystemValues ()
LLVM_ABI ArrayRef< EnumEntry< SigComponentType > > getSigComponentTypes ()
Enumeration Type Documentation
ComparisonFunc
enum class llvm::dxbc::ComparisonFunc : uint32_t strong
Definition at line 243 of file DXContainer.h.
D3DSystemValue
enum class llvm::dxbc::D3DSystemValue : uint32_t strong
Definition at line 585 of file DXContainer.h.
DescriptorRangeFlags
enum class llvm::dxbc::DescriptorRangeFlags : uint32_t strong
Definition at line 179 of file DXContainer.h.
DescriptorRangeType
enum class llvm::dxbc::DescriptorRangeType : uint32_t strong
Definition at line 195 of file DXContainer.h.
FeatureFlags
enum class llvm::dxbc::FeatureFlags : uint64_t strong
Definition at line 154 of file DXContainer.h.
HashFlags
enum class llvm::dxbc::HashFlags : uint32_t strong
Enumerator
None
IncludesSource
Definition at line 56 of file DXContainer.h.
PartType
enum class llvm::dxbc::PartType strong
Enumerator
Unknown
Definition at line 148 of file DXContainer.h.
RootDescriptorFlags
enum class llvm::dxbc::RootDescriptorFlags : uint32_t strong
Definition at line 170 of file DXContainer.h.
RootFlags
enum class llvm::dxbc::RootFlags : uint32_t strong
Definition at line 161 of file DXContainer.h.
RootParameterType
enum class llvm::dxbc::RootParameterType : uint32_t strong
Definition at line 188 of file DXContainer.h.
RootSignatureVersion
enum class llvm::dxbc::RootSignatureVersion strong
Enumerator
V1_0
V1_1
Definition at line 781 of file DXContainer.h.
SamplerFilter
enum class llvm::dxbc::SamplerFilter : uint32_t strong
Definition at line 229 of file DXContainer.h.
ShaderVisibility
enum class llvm::dxbc::ShaderVisibility : uint32_t strong
Definition at line 212 of file DXContainer.h.
SigComponentType
enum class llvm::dxbc::SigComponentType : uint32_t strong
Definition at line 592 of file DXContainer.h.
SigMinPrecision
enum class llvm::dxbc::SigMinPrecision : uint32_t strong
Definition at line 578 of file DXContainer.h.
StaticBorderColor
enum class llvm::dxbc::StaticBorderColor : uint32_t strong
Definition at line 250 of file DXContainer.h.
TextureAddressMode
enum class llvm::dxbc::TextureAddressMode : uint32_t strong
Definition at line 236 of file DXContainer.h.
Function Documentation
getComparisonFuncs()
ArrayRef< EnumEntry< ComparisonFunc > > llvm::dxbc::getComparisonFuncs ()
Definition at line 128 of file DXContainer.cpp.
References llvm::ArrayRef(), and ComparisonFuncNames.
Referenced by llvm::hlsl::rootsig::operator<<().
getD3DSystemValues()
ArrayRef< EnumEntry< D3DSystemValue > > llvm::dxbc::getD3DSystemValues ()
Definition at line 49 of file DXContainer.cpp.
References llvm::ArrayRef(), and D3DSystemValueNames.
getDescriptorRangeFlags()
ArrayRef< EnumEntry< DescriptorRangeFlags > > llvm::dxbc::getDescriptorRangeFlags ()
Definition at line 88 of file DXContainer.cpp.
References llvm::ArrayRef(), and DescriptorRangeFlagNames.
Referenced by llvm::hlsl::rootsig::operator<<().
getDescriptorRangeTypes()
LLVM_ABI ArrayRef< EnumEntry< DescriptorRangeType > > llvm::dxbc::getDescriptorRangeTypes ()
References LLVM_ABI.
getRootDescriptorFlags()
ArrayRef< EnumEntry< RootDescriptorFlags > > llvm::dxbc::getRootDescriptorFlags ()
Definition at line 78 of file DXContainer.cpp.
References llvm::ArrayRef(), and RootDescriptorFlagNames.
Referenced by llvm::hlsl::rootsig::operator<<().
getRootFlags()
ArrayRef< EnumEntry< RootFlags > > llvm::dxbc::getRootFlags ()
Definition at line 68 of file DXContainer.cpp.
References llvm::ArrayRef(), and RootFlagNames.
Referenced by llvm::hlsl::rootsig::operator<<().
getRootParameterTypes()
ArrayRef< EnumEntry< RootParameterType > > llvm::dxbc::getRootParameterTypes ()
Definition at line 148 of file DXContainer.cpp.
References llvm::ArrayRef(), and RootParameterTypes.
getSamplerFilters()
ArrayRef< EnumEntry< SamplerFilter > > llvm::dxbc::getSamplerFilters ()
Definition at line 108 of file DXContainer.cpp.
References llvm::ArrayRef(), and SamplerFilterNames.
Referenced by llvm::hlsl::rootsig::operator<<().
getShaderStage()
Triple::EnvironmentType llvm::dxbc::getShaderStage (uint32_t Kind) inline
Definition at line 46 of file DXContainer.h.
References llvm::Triple::Amplification, assert(), and llvm::Triple::Pixel.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping(), and llvm::object::DirectX::PSVRuntimeInfo::parse().
getShaderVisibility()
ArrayRef< EnumEntry< ShaderVisibility > > llvm::dxbc::getShaderVisibility ()
Definition at line 98 of file DXContainer.cpp.
References llvm::ArrayRef(), and ShaderVisibilityValues.
Referenced by llvm::hlsl::rootsig::operator<<().
getSigComponentTypes()
ArrayRef< EnumEntry< SigComponentType > > llvm::dxbc::getSigComponentTypes ()
Definition at line 59 of file DXContainer.cpp.
References llvm::ArrayRef(), and SigComponentTypes.
getSigMinPrecisions()
ArrayRef< EnumEntry< SigMinPrecision > > llvm::dxbc::getSigMinPrecisions ()
Definition at line 39 of file DXContainer.cpp.
References llvm::ArrayRef(), and SigMinPrecisionNames.
getStaticBorderColors()
ArrayRef< EnumEntry< StaticBorderColor > > llvm::dxbc::getStaticBorderColors ()
Definition at line 138 of file DXContainer.cpp.
References llvm::ArrayRef(), and StaticBorderColorValues.
Referenced by llvm::hlsl::rootsig::operator<<().
getTextureAddressModes()
ArrayRef< EnumEntry< TextureAddressMode > > llvm::dxbc::getTextureAddressModes ()
Definition at line 118 of file DXContainer.cpp.
References llvm::ArrayRef(), and TextureAddressModeNames.
Referenced by llvm::hlsl::rootsig::operator<<().
isValidParameterType()
bool llvm::dxbc::isValidParameterType (uint32_t V) inline
Definition at line 204 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), llvm::object::DirectX::RootSignature::getParameter(), and validate().
isValidShaderVisibility()
bool llvm::dxbc::isValidShaderVisibility (uint32_t V) inline
Definition at line 221 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and validate().
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
llvm::dxbc::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
parsePartType()
dxbc::PartType llvm::dxbc::parsePartType (StringRef S)
Definition at line 21 of file DXContainer.cpp.
References llvm::StringSwitch< T, R >::Default(), and Unknown.