LLVM: false Namespace Reference
false Namespace Reference
Classes
class Chain
A Chain is a sequence of instructions that are linked together by an accumulation operand.
struct GepNode
struct in_set
struct IntervalSorter
class LoopCarriedOrderDepsTracker
Add loop-carried chain dependencies.
struct SingleLoopExtractor
SingleLoopExtractor - For bugpoint.
struct SUnitWithMemInfo
This class holds an SUnit corresponding to a memory operation and other information related to the instruction.
Functions
raw_ostream & operator<< (raw_ostream &OS, const GepNode &GN)
template<typename NodeContainer>
void dump_node_container (raw_ostream &OS, const NodeContainer &S)
raw_ostream & operator<< (raw_ostream &OS, const NodeVect &S) LLVM_ATTRIBUTE_UNUSED
raw_ostream & operator<< (raw_ostream &OS, const NodeToUsesMap &M) LLVM_ATTRIBUTE_UNUSED
Function Documentation
dump_node_container()
template<typename NodeContainer> void false::dump_node_container (raw_ostream & OS, const NodeContainer & S)
Definition at line 268 of file HexagonCommonGEP.cpp.
References dump_node_container(), and I.
Referenced by dump_node_container(), and operator<<().
operator<<() [1/3]
raw_ostream & false::operator<< (raw_ostream & OS, const GepNode & GN)
Definition at line 211 of file HexagonCommonGEP.cpp.
operator<<() [2/3]
raw_ostream & false::operator<< (raw_ostream & OS, const NodeToUsesMap & M)
Definition at line 284 of file HexagonCommonGEP.cpp.
References I.
operator<<() [3/3]
raw_ostream & false::operator<< (raw_ostream & OS, const NodeVect & S)
Definition at line 277 of file HexagonCommonGEP.cpp.
References dump_node_container().