LLVM: lib/Target/NVPTX/MCTargetDesc/NVPTXTargetStreamer.cpp File Reference
NVPTXTargetStreamer.cpp File Reference
#include "NVPTXTargetStreamer.h"
#include "NVPTXUtilities.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
Functions
static bool isDwarfSection (const MCObjectFileInfo *FI, const MCSection *Section)
Function Documentation
isDwarfSection()
bool isDwarfSection (const MCObjectFileInfo * FI, const MCSection * Section) static
Definition at line 49 of file NVPTXTargetStreamer.cpp.
References llvm::MCObjectFileInfo::getDwarfAbbrevDWOSection(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::MCObjectFileInfo::getDwarfAccelNamespaceSection(), llvm::MCObjectFileInfo::getDwarfAccelNamesSection(), llvm::MCObjectFileInfo::getDwarfAccelObjCSection(), llvm::MCObjectFileInfo::getDwarfAccelTypesSection(), llvm::MCObjectFileInfo::getDwarfAddrSection(), llvm::MCObjectFileInfo::getDwarfARangesSection(), llvm::MCObjectFileInfo::getDwarfCUIndexSection(), llvm::MCObjectFileInfo::getDwarfDebugInlineSection(), llvm::MCObjectFileInfo::getDwarfDebugNamesSection(), llvm::MCObjectFileInfo::getDwarfFrameSection(), llvm::MCObjectFileInfo::getDwarfGnuPubNamesSection(), llvm::MCObjectFileInfo::getDwarfGnuPubTypesSection(), llvm::MCObjectFileInfo::getDwarfInfoDWOSection(), llvm::MCObjectFileInfo::getDwarfInfoSection(), llvm::MCObjectFileInfo::getDwarfLineDWOSection(), llvm::MCObjectFileInfo::getDwarfLineSection(), llvm::MCObjectFileInfo::getDwarfLineStrSection(), llvm::MCObjectFileInfo::getDwarfLocDWOSection(), llvm::MCObjectFileInfo::getDwarfLocSection(), llvm::MCObjectFileInfo::getDwarfMacinfoSection(), llvm::MCObjectFileInfo::getDwarfPubNamesSection(), llvm::MCObjectFileInfo::getDwarfPubTypesSection(), llvm::MCObjectFileInfo::getDwarfRangesSection(), llvm::MCObjectFileInfo::getDwarfStrDWOSection(), llvm::MCObjectFileInfo::getDwarfStrOffDWOSection(), llvm::MCObjectFileInfo::getDwarfStrOffSection(), llvm::MCObjectFileInfo::getDwarfStrSection(), llvm::MCObjectFileInfo::getDwarfSwiftASTSection(), llvm::MCObjectFileInfo::getDwarfTUIndexSection(), and llvm::MCObjectFileInfo::getDwarfTypesDWOSection().
Referenced by llvm::NVPTXTargetStreamer::changeSection(), llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >::forEachRelaRelocation(), llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >::forEachRelRelocation(), and llvm::jitlink::ELFLinkGraphBuilder< ELFT >::graphifySections().