LLVM: lib/Target/NVPTX/NVPTXAliasAnalysis.cpp File Reference
NVPTXAliasAnalysis.cpp File Reference
This is the NVPTX address space based alias analysis pass.
#include "NVPTXAliasAnalysis.h"
#include "MCTargetDesc/NVPTXBaseInfo.h"
#include "NVPTX.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "NVPTX-aa"
Functions
INITIALIZE_PASS (NVPTXAAWrapperPass, "nvptx-aa", "NVPTX Address space based Alias Analysis", false, true) INITIALIZE_PASS(NVPTXExternalAAWrapper
static unsigned getAddressSpace (const Value *V, unsigned MaxLookup)
static AliasResult::Kind getAliasResult (unsigned AS1, unsigned AS2)
static bool isConstOrParam (unsigned AS)
Variables
static cl::opt< unsigned > TraverseAddressSpacesLimit ("nvptx-traverse-address-aliasing-limit", cl::Hidden, cl::desc("Depth limit for finding address space through traversal"), cl::init(6))
nvptx aa wrapper
nvptx aa NVPTX Address space based Alias Analysis Wrapper
nvptx aa NVPTX Address space based Alias Analysis false
Detailed Description
This is the NVPTX address space based alias analysis pass.
Definition in file NVPTXAliasAnalysis.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "NVPTX-aa"
Definition at line 22 of file NVPTXAliasAnalysis.cpp.
Function Documentation
getAddressSpace()
unsigned getAddressSpace (const Value * V, unsigned MaxLookup) static
Definition at line 54 of file NVPTXAliasAnalysis.cpp.
References llvm::NVPTXAS::ADDRESS_SPACE_GENERIC, llvm::dyn_cast(), and llvm::getUnderlyingObject().
Referenced by llvm::NVPTXAAResult::alias(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::NVPTXAAResult::getModRefInfoMask(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::TargetLowering::LowerCallTo(), and llvm::SITargetLowering::lowerPREFETCH().
getAliasResult()
AliasResult::Kind getAliasResult (unsigned AS1, unsigned AS2) static
Definition at line 72 of file NVPTXAliasAnalysis.cpp.
References llvm::NVPTXAS::ADDRESS_SPACE_GENERIC, llvm::NVPTXAS::ADDRESS_SPACE_SHARED, llvm::NVPTXAS::ADDRESS_SPACE_SHARED_CLUSTER, llvm::AliasResult::MayAlias, and llvm::AliasResult::NoAlias.
Referenced by llvm::NVPTXAAResult::alias().
INITIALIZE_PASS()
INITIALIZE_PASS (NVPTXAAWrapperPass , "nvptx-aa" , "NVPTX Address space based Alias Analysis" , false , true)
isConstOrParam()
bool isConstOrParam (unsigned AS) static
Definition at line 110 of file NVPTXAliasAnalysis.cpp.
Referenced by llvm::NVPTXAAResult::getModRefInfoMask().
Variable Documentation
false
nvptx aa NVPTX Address space based Alias Analysis false
Definition at line 38 of file NVPTXAliasAnalysis.cpp.
TraverseAddressSpacesLimit
cl::opt< unsigned > TraverseAddressSpacesLimit("nvptx-traverse-address-aliasing-limit", cl::Hidden, cl::desc("Depth limit for finding address space through traversal"), cl::init(6)) ("nvptx-traverse-address-aliasing-limit" , cl::Hidden , cl::desc("Depth limit for finding address space through traversal") , cl::init(6)) static
Referenced by llvm::NVPTXAAResult::alias(), and llvm::NVPTXAAResult::getModRefInfoMask().
Wrapper
nvptx aa NVPTX Address space based Alias Analysis Wrapper
Definition at line 38 of file NVPTXAliasAnalysis.cpp.
wrapper
nvptx aa wrapper
Definition at line 37 of file NVPTXAliasAnalysis.cpp.