LLVM: lib/ObjCopy/Archive.cpp File Reference
Archive.cpp File Reference
#include "Archive.h"
#include "llvm/ObjCopy/CommonConfig.h"
#include "llvm/ObjCopy/MultiFormatConfig.h"
#include "llvm/ObjCopy/ObjCopy.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/FileOutputBuffer.h"
#include "llvm/Support/SmallVectorMemoryBuffer.h"
Functions
static Error deepWriteArchive (StringRef ArcName, ArrayRef< NewArchiveMember > NewMembers, SymtabWritingMode WriteSymtab, object::Archive::Kind Kind, bool Deterministic, bool Thin)
Function Documentation
deepWriteArchive()
Error deepWriteArchive (StringRef ArcName, ArrayRef< NewArchiveMember > NewMembers, SymtabWritingMode WriteSymtab, object::Archive::Kind Kind, bool Deterministic, bool Thin) static
Definition at line 60 of file Archive.cpp.
References llvm::FileOutputBuffer::create(), llvm::createFileError(), E(), llvm::ArrayRef< T >::empty(), llvm::FileOutputBuffer::F_executable, llvm::ArrayRef< T >::front(), llvm::object::Archive::K_BSD, llvm::object::Archive::K_DARWIN, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::writeArchive().
Referenced by llvm::objcopy::executeObjcopyOnArchive().