LLVM: lib/Target/PowerPC/MCTargetDesc/PPCMCAsmInfo.cpp File Reference
PPCMCAsmInfo.cpp File Reference
#include "MCTargetDesc/PPCMCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
Functions
static std::optional< int64_t > evaluateAsInt64 (uint16_t specifier, int64_t Value)
static bool evaluateAsRelocatable (const MCSpecifierExpr &Expr, MCValue &Res, const MCAssembler *Asm)
Variables
const MCAsmInfo::AtSpecifier elfAtSpecifiers []
const MCAsmInfo::AtSpecifier xcoffAtSpecifiers []
Function Documentation
evaluateAsInt64()
std::optional< int64_t > evaluateAsInt64 (uint16_t specifier, int64_t Value) static
Definition at line 112 of file PPCMCAsmInfo.cpp.
References llvm::PPC::S_HA, llvm::PPC::S_HI, llvm::PPC::S_HIGH, llvm::PPC::S_HIGHA, llvm::PPC::S_HIGHER, llvm::PPC::S_HIGHERA, llvm::PPC::S_HIGHEST, llvm::PPC::S_HIGHESTA, and llvm::PPC::S_LO.
Referenced by llvm::PPC::evaluateAsConstant(), and evaluateAsRelocatable().
evaluateAsRelocatable()
bool evaluateAsRelocatable (const MCSpecifierExpr & Expr, MCValue & Res, const MCAssembler * Asm) static
Definition at line 153 of file PPCMCAsmInfo.cpp.
References evaluateAsInt64(), llvm::MCExpr::evaluateAsRelocatable(), llvm::MCValue::get(), llvm::MCValue::getConstant(), llvm::MCSpecifierExpr::getSpecifier(), llvm::MCSpecifierExpr::getSubExpr(), llvm::MCValue::isAbsolute(), and llvm::MCValue::setSpecifier().
Referenced by llvm::PPCELFMCAsmInfo::evaluateAsRelocatableImpl(), and llvm::PPCXCOFFMCAsmInfo::evaluateAsRelocatableImpl().
Variable Documentation
elfAtSpecifiers
const MCAsmInfo::AtSpecifier elfAtSpecifiers[]
Definition at line 22 of file PPCMCAsmInfo.cpp.
Referenced by llvm::PPCELFMCAsmInfo::PPCELFMCAsmInfo().
xcoffAtSpecifiers
const MCAsmInfo::AtSpecifier xcoffAtSpecifiers[]
Initial value:
= {
    {PPC::S_AIX_TLSGD, "gd"},
    {PPC::S_AIX_TLSGDM, "m"},
    {PPC::S_AIX_TLSIE, "ie"},
    {PPC::S_AIX_TLSLD, "ld"},
    {PPC::S_AIX_TLSLE, "le"},
    {PPC::S_AIX_TLSML, "ml"},
    {PPC::S_L, "l"},
    {PPC::S_U, "u"},
}
Definition at line 99 of file PPCMCAsmInfo.cpp.
Referenced by llvm::PPCXCOFFMCAsmInfo::PPCXCOFFMCAsmInfo().