LLVM: include/llvm/Support/RecyclingAllocator.h File Reference
RecyclingAllocator.h File Reference
#include "llvm/Support/Recycler.h"
Classes
class llvm::RecyclingAllocator< AllocatorType, T, Size, Align >
RecyclingAllocator - This class wraps an Allocator, adding the functionality of recycling deleted objects.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
template<class AllocatorType, class T, size_t Size, size_t Align>
void * operator new (size_t size, llvm::RecyclingAllocator< AllocatorType, T, Size, Align > &Allocator)
template<class AllocatorType, class T, size_t Size, size_t Align>
void operator delete (void *E, llvm::RecyclingAllocator< AllocatorType, T, Size, Align > &A)
Function Documentation
operator delete()
template<class AllocatorType, class T, size_t Size, size_t Align> void operator delete (void * E, llvm::RecyclingAllocator< AllocatorType, T, Size, Align > & A) inline
Definition at line 70 of file RecyclingAllocator.h.
References A(), E(), Size, and T.
operator new()
template<class AllocatorType, class T, size_t Size, size_t Align> void * operator new (size_t size, llvm::RecyclingAllocator< AllocatorType, T, Size, Align > & Allocator) inline
Definition at line 62 of file RecyclingAllocator.h.
References Allocator, assert(), Size, and T.