LLVM: lib/CodeGen/RegAllocScore.cpp File Reference
RegAllocScore.cpp File Reference
#include "RegAllocScore.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "regalloc-score"
Functions
LLVM_ABI cl::opt< double > CopyWeight ("regalloc-copy-weight", cl::init(0.2), cl::Hidden)
LLVM_ABI cl::opt< double > LoadWeight ("regalloc-load-weight", cl::init(4.0), cl::Hidden)
LLVM_ABI cl::opt< double > StoreWeight ("regalloc-store-weight", cl::init(1.0), cl::Hidden)
LLVM_ABI cl::opt< double > CheapRematWeight ("regalloc-cheap-remat-weight", cl::init(0.2), cl::Hidden)
LLVM_ABI cl::opt< double > ExpensiveRematWeight ("regalloc-expensive-remat-weight", cl::init(1.0), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regalloc-score"
Definition at line 36 of file RegAllocScore.cpp.
Function Documentation
CheapRematWeight()
LLVM_ABI cl::opt< double > CheapRematWeight ("regalloc-cheap-remat-weight" , cl::init(0.2) , cl::Hidden)
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::RegAllocScore::getScore().
CopyWeight()
LLVM_ABI cl::opt< double > CopyWeight ("regalloc-copy-weight" , cl::init(0.2) , cl::Hidden)
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::RegAllocScore::getScore().
ExpensiveRematWeight()
LLVM_ABI cl::opt< double > ExpensiveRematWeight ("regalloc-expensive-remat-weight" , cl::init(1.0) , cl::Hidden)
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::RegAllocScore::getScore().
LoadWeight()
LLVM_ABI cl::opt< double > LoadWeight ("regalloc-load-weight" , cl::init(4.0) , cl::Hidden)
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::RegAllocScore::getScore().
StoreWeight()
LLVM_ABI cl::opt< double > StoreWeight ("regalloc-store-weight" , cl::init(1.0) , cl::Hidden)
References llvm::cl::Hidden, llvm::cl::init(), and LLVM_ABI.
Referenced by llvm::RegAllocScore::getScore().