LLVM: lib/Target/RISCV/RISCVPushPopOptimizer.cpp File Reference
RISCVPushPopOptimizer.cpp File Reference
#include "RISCVInstrInfo.h"
#include "RISCVMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineInstr.h"
Macros
#define RISCV_PUSH_POP_OPT_NAME "RISC-V Zcmp Push/Pop optimization pass"
Functions
INITIALIZE_PASS (RISCVPushPopOpt, "riscv-push-pop-opt", RISCV_PUSH_POP_OPT_NAME, false, false) static bool isPop(unsigned Opcode)
static unsigned getPopRetOpcode (unsigned PopOpcode, bool IsReturnZero)
Macro Definition Documentation
RISCV_PUSH_POP_OPT_NAME
#define RISCV_PUSH_POP_OPT_NAME "RISC-V Zcmp Push/Pop optimization pass"
Definition at line 20 of file RISCVPushPopOptimizer.cpp.
Referenced by INITIALIZE_PASS().
Function Documentation
getPopRetOpcode()
unsigned getPopRetOpcode (unsigned PopOpcode, bool IsReturnZero) static
Definition at line 59 of file RISCVPushPopOptimizer.cpp.
References assert(), isPop(), and llvm_unreachable.
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVPushPopOpt , "riscv-push-pop-opt" , RISCV_PUSH_POP_OPT_NAME , false , false)
Definition at line 46 of file RISCVPushPopOptimizer.cpp.
References isPop(), and RISCV_PUSH_POP_OPT_NAME.