LLVM: lib/Demangle/RustDemangle.cpp File Reference
RustDemangle.cpp File Reference
#include "llvm/Demangle/Demangle.h"
#include "llvm/Demangle/StringViewExtras.h"
#include "llvm/Demangle/Utility.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <limits>
#include <string_view>
Functions
static bool isDigit (const char C)
static bool isHexDigit (const char C)
static bool isLower (const char C)
static bool isUpper (const char C)
static bool isValid (const char C)
Returns true if C is a valid mangled character: <0-9a-zA-Z_>.
static bool parseBasicType (char C, BasicType &Type)
static bool isAsciiPrintable (uint64_t CodePoint)
Returns true if CodePoint represents a printable ASCII character.
static bool decodePunycodeDigit (char C, size_t &Value)
static void removeNullBytes (OutputBuffer &Output, size_t StartIdx)
static bool encodeUTF8 (size_t CodePoint, char *Output)
static bool decodePunycode (std::string_view Input, OutputBuffer &Output)
Function Documentation
decodePunycode()
bool decodePunycode (std::string_view Input, OutputBuffer & Output) static
Definition at line 1105 of file RustDemangle.cpp.
References llvm::sampleprof::Base, llvm::CallingConv::C, decodePunycodeDigit(), encodeUTF8(), OutputBuffer::getCurrentPosition(), I, OutputBuffer::insert(), isValid(), N, removeNullBytes(), and T.
decodePunycodeDigit()
bool decodePunycodeDigit (char C, size_t & Value) inline static
Definition at line 1047 of file RustDemangle.cpp.
References llvm::CallingConv::C, llvm::isDigit(), and llvm::isLower().
Referenced by decodePunycode().
encodeUTF8()
bool encodeUTF8 (size_t CodePoint, char * Output) inline static
Definition at line 1070 of file RustDemangle.cpp.
Referenced by decodePunycode(), and llvm::yaml::escape().
isAsciiPrintable()
bool isAsciiPrintable (uint64_t CodePoint) static
Returns true if CodePoint represents a printable ASCII character.
Definition at line 799 of file RustDemangle.cpp.
isDigit()
bool isDigit (const char C) inline static
Definition at line 170 of file RustDemangle.cpp.
References llvm::CallingConv::C.
isHexDigit()
bool isHexDigit (const char C) inline static
Definition at line 172 of file RustDemangle.cpp.
References llvm::CallingConv::C.
isLower()
bool isLower (const char C) inline static
Definition at line 176 of file RustDemangle.cpp.
References llvm::CallingConv::C.
isUpper()
bool isUpper (const char C) inline static
Definition at line 178 of file RustDemangle.cpp.
References llvm::CallingConv::C.
isValid()
bool isValid (const char C) inline static
Returns true if C is a valid mangled character: <0-9a-zA-Z_>.
Definition at line 181 of file RustDemangle.cpp.
References llvm::CallingConv::C, llvm::isDigit(), llvm::isLower(), and llvm::isUpper().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::assignTypeNames(), llvm::MachineIRBuilder::buildConstDbgValue(), llvm::MachineIRBuilder::buildDirectDbgValue(), llvm::MachineIRBuilder::buildFIDbgValue(), llvm::MachineIRBuilder::buildIndirectDbgValue(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::BuildMI(), llvm::BuildMI(), llvm::MachineIRBuilder::buildStore(), collectVirtRegShapes(), llvm::VPlan::cost(), decodePunycode(), llvm::DiagnosticInfoRegAllocFailure::DiagnosticInfoRegAllocFailure(), llvm::SparseMultiSet< PhysRegSUOper, identity< unsigned >, uint16_t >::findIndex(), llvm::OpenMPIRBuilder::getAfter(), llvm::OpenMPIRBuilder::getAfterIP(), llvm::OpenMPIRBuilder::getBody(), llvm::OpenMPIRBuilder::getBodyIP(), llvm::OpenMPIRBuilder::getCond(), llvm::OpenMPIRBuilder::getExit(), llvm::OpenMPIRBuilder::getFunction(), llvm::OpenMPIRBuilder::getHeader(), llvm::OpenMPIRBuilder::getIndVar(), llvm::OpenMPIRBuilder::getIndVarType(), llvm::OpenMPIRBuilder::getLatch(), llvm::OpenMPIRBuilder::getPreheaderIP(), llvm::OpenMPIRBuilder::getTripCount(), LowerINTRINSIC_W_CHAIN(), llvm::CombinerHelper::matchCombineInsertVecElts(), llvm::MachineMemOperand::print(), and llvm::RegisterBankInfo::InstructionMapping::verify().
parseBasicType()
bool parseBasicType (char C, BasicType & Type) static
Definition at line 386 of file RustDemangle.cpp.
References llvm::CallingConv::C.
removeNullBytes()
void removeNullBytes (OutputBuffer & Output, size_t StartIdx) static
Definition at line 1061 of file RustDemangle.cpp.
References OutputBuffer::getBuffer(), OutputBuffer::getCurrentPosition(), and OutputBuffer::setCurrentPosition().
Referenced by decodePunycode().