LLVM: lib/CodeGen/SelectionDAG/SDNodeInfo.cpp File Reference
SDNodeInfo.cpp File Reference
#include "llvm/CodeGen/SDNodeInfo.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
Functions
static void reportNodeError (const SelectionDAG &DAG, const SDNode *N, const Twine &Msg)
static void checkResultType (const SelectionDAG &DAG, const SDNode *N, unsigned ResIdx, EVT ExpectedVT)
static void checkOperandType (const SelectionDAG &DAG, const SDNode *N, unsigned OpIdx, EVT ExpectedVT)
Function Documentation
checkOperandType()
void checkOperandType (const SelectionDAG & DAG, const SDNode * N, unsigned OpIdx, EVT ExpectedVT) static
Definition at line 33 of file SDNodeInfo.cpp.
References llvm::EVT::getEVTString(), N, OpIdx, and reportNodeError().
Referenced by llvm::SDNodeInfo::verifyNode().
checkResultType()
void checkResultType (const SelectionDAG & DAG, const SDNode * N, unsigned ResIdx, EVT ExpectedVT) static
Definition at line 23 of file SDNodeInfo.cpp.
References llvm::EVT::getEVTString(), N, and reportNodeError().
Referenced by llvm::SDNodeInfo::verifyNode().
reportNodeError()
void reportNodeError (const SelectionDAG & DAG, const SDNode * N, const Twine & Msg) static
Definition at line 14 of file SDNodeInfo.cpp.
References N, and llvm::report_fatal_error().
Referenced by checkOperandType(), checkResultType(), and llvm::SDNodeInfo::verifyNode().