LLVM: lib/Target/AMDGPU/SIInstrInfo.cpp File Reference
SIInstrInfo.cpp File Reference
SI Implementation of TargetInstrInfo.
#include "SIInstrInfo.h"
#include "AMDGPU.h"
#include "AMDGPUInstrInfo.h"
#include "GCNHazardRecognizer.h"
#include "GCNSubtarget.h"
#include "SIMachineFunctionInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/MC/MCContext.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
#include "AMDGPUGenInstrInfo.inc"
#include "AMDGPUGenSearchableTables.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::AMDGPU
Macros
#define DEBUG_TYPE "si-instr-info"
#define GET_INSTRINFO_CTOR_DTOR
#define GET_D16ImageDimIntrinsics_IMPL
#define GET_ImageDimIntrinsicTable_IMPL
#define GET_RsrcIntrinsics_IMPL
#define GENERATE_RENAMED_GFX9_CASES(OPCODE)
Functions
static unsigned getNumOperandsNoGlue (SDNode *Node)
static bool nodesHaveSameOperandValue (SDNode *N0, SDNode *N1, AMDGPU::OpName OpName)
Returns true if both nodes have the same value for the given operand Op, or if both nodes do not have this operand.
static bool canRemat (const MachineInstr &MI)
static bool isStride64 (unsigned Opc)
static bool memOpsHaveSameBasePtr (const MachineInstr &MI1, ArrayRef< const MachineOperand * > BaseOps1, const MachineInstr &MI2, ArrayRef< const MachineOperand * > BaseOps2)
static void reportIllegalCopy (const SIInstrInfo *TII, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc, const char *Msg="illegal VGPR to SGPR copy")
static void indirectCopyToAGPR (const SIInstrInfo &TII, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc, RegScavenger &RS, bool RegsOverlap, Register ImpDefSuperReg=Register(), Register ImpUseSuperReg=Register())
Handle copying from SGPR to AGPR, or from AGPR to AGPR on GFX908.
static void expandSGPRCopy (const SIInstrInfo &TII, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc, const TargetRegisterClass *RC, bool Forward)
static unsigned getIndirectVGPRWriteMovRelPseudoOpc (unsigned VecSize)
static unsigned getIndirectSGPRWriteMovRelPseudo32 (unsigned VecSize)
static unsigned getIndirectSGPRWriteMovRelPseudo64 (unsigned VecSize)
static unsigned getSGPRSpillSaveOpcode (unsigned Size)
static unsigned getVGPRSpillSaveOpcode (unsigned Size)
static unsigned getAGPRSpillSaveOpcode (unsigned Size)
static unsigned getAVSpillSaveOpcode (unsigned Size)
static unsigned getWWMRegSpillSaveOpcode (unsigned Size, bool IsVectorSuperClass)
static unsigned getVectorRegSpillSaveOpcode (Register Reg, const TargetRegisterClass *RC, unsigned Size, const SIRegisterInfo &TRI, const SIMachineFunctionInfo &MFI)
static unsigned getSGPRSpillRestoreOpcode (unsigned Size)
static unsigned getVGPRSpillRestoreOpcode (unsigned Size)
static unsigned getAGPRSpillRestoreOpcode (unsigned Size)
static unsigned getAVSpillRestoreOpcode (unsigned Size)
static unsigned getWWMRegSpillRestoreOpcode (unsigned Size, bool IsVectorSuperClass)
static unsigned getVectorRegSpillRestoreOpcode (Register Reg, const TargetRegisterClass *RC, unsigned Size, const SIRegisterInfo &TRI, const SIMachineFunctionInfo &MFI)
static MachineInstr * swapRegAndNonRegOperand (MachineInstr &MI, MachineOperand &RegOp, MachineOperand &NonRegOp)
static MachineInstr * swapImmOperands (MachineInstr &MI, MachineOperand &NonRegOp1, MachineOperand &NonRegOp2)
static void preserveCondRegFlags (MachineOperand &CondReg, const MachineOperand &OrigCond)
static unsigned getNewFMAAKInst (const GCNSubtarget &ST, unsigned Opc)
static unsigned getNewFMAMKInst (const GCNSubtarget &ST, unsigned Opc)
static bool memOpsHaveSameBaseOperands (ArrayRef< const MachineOperand * > BaseOps1, ArrayRef< const MachineOperand * > BaseOps2)
static bool offsetsDoNotOverlap (LocationSize WidthA, int OffsetA, LocationSize WidthB, int OffsetB)
static bool getFoldableImm (Register Reg, const MachineRegisterInfo &MRI, int64_t &Imm, MachineInstr **DefMI=nullptr)
static bool getFoldableImm (const MachineOperand *MO, int64_t &Imm, MachineInstr **DefMI=nullptr)
static void updateLiveVariables (LiveVariables *LV, MachineInstr &MI, MachineInstr &NewMI)
static unsigned getNewFMAInst (const GCNSubtarget &ST, unsigned Opc)
static bool changesVGPRIndexingMode (const MachineInstr &MI)
static bool compareMachineOp (const MachineOperand &Op0, const MachineOperand &Op1)
static void copyFlagsToImplicitVCC (MachineInstr &MI, const MachineOperand &Orig)
static Register findImplicitSGPRRead (const MachineInstr &MI)
static bool shouldReadExec (const MachineInstr &MI)
static bool isRegOrFI (const MachineOperand &MO)
static bool isSubRegOf (const SIRegisterInfo &TRI, const MachineOperand &SuperVec, const MachineOperand &SubReg)
static const TargetRegisterClass * adjustAllocatableRegClass (const GCNSubtarget &ST, const SIRegisterInfo &RI, const MachineRegisterInfo &MRI, const MCInstrDesc &TID, unsigned RCID, bool IsAllocatable)
static void emitLoadScalarOpsFromVGPRLoop (const SIInstrInfo &TII, MachineRegisterInfo &MRI, MachineBasicBlock &LoopBB, MachineBasicBlock &BodyBB, const DebugLoc &DL, ArrayRef< MachineOperand * > ScalarOps)
static MachineBasicBlock * loadMBUFScalarOperandsFromVGPR (const SIInstrInfo &TII, MachineInstr &MI, ArrayRef< MachineOperand * > ScalarOps, MachineDominatorTree *MDT, MachineBasicBlock::iterator Begin=nullptr, MachineBasicBlock::iterator End=nullptr)
static std::tuple< unsigned, unsigned > extractRsrcPtr (const SIInstrInfo &TII, MachineInstr &MI, MachineOperand &Rsrc)
static unsigned subtargetEncodingFamily (const GCNSubtarget &ST)
static bool isRenamedInGFX9 (int Opcode)
static TargetInstrInfo::RegSubRegPair getRegOrUndef (const MachineOperand &RegOpnd)
static bool followSubRegDef (MachineInstr &MI, TargetInstrInfo::RegSubRegPair &RSR)
Variables
static cl::opt< unsigned > BranchOffsetBits ("amdgpu-s-branch-bits", cl::ReallyHidden, cl::init(16), cl::desc("Restrict range of branch instructions (DEBUG)"))
static cl::opt< bool > Fix16BitCopies ("amdgpu-fix-16-bit-physreg-copies", cl::desc("Fix copies between 32 and 16 bit registers by extending to 32 bit"), cl::init(true), cl::ReallyHidden)
static constexpr AMDGPU::OpName ModifierOpNames []
Detailed Description
SI Implementation of TargetInstrInfo.
Definition in file SIInstrInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-instr-info"
Definition at line 38 of file SIInstrInfo.cpp.
GENERATE_RENAMED_GFX9_CASES
#define GENERATE_RENAMED_GFX9_CASES (OPCODE)
Value:
  case OPCODE##_dpp:                                                           \
  case OPCODE##_e32:                                                           \
  case OPCODE##_e64:                                                           \
  case OPCODE##_e64_dpp:                                                       \
  case OPCODE##_sdwa:
Definition at line 9658 of file SIInstrInfo.cpp.
Referenced by isRenamedInGFX9().
GET_D16ImageDimIntrinsics_IMPL
#define GET_D16ImageDimIntrinsics_IMPL
Definition at line 44 of file SIInstrInfo.cpp.
GET_ImageDimIntrinsicTable_IMPL
#define GET_ImageDimIntrinsicTable_IMPL
Definition at line 45 of file SIInstrInfo.cpp.
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 40 of file SIInstrInfo.cpp.
GET_RsrcIntrinsics_IMPL
#define GET_RsrcIntrinsics_IMPL
Definition at line 46 of file SIInstrInfo.cpp.
Function Documentation
adjustAllocatableRegClass()
const TargetRegisterClass * adjustAllocatableRegClass (const GCNSubtarget & ST, const SIRegisterInfo & RI, const MachineRegisterInfo & MRI, const MCInstrDesc & TID, unsigned RCID, bool IsAllocatable) static
Definition at line 5795 of file SIInstrInfo.cpp.
References llvm::SIInstrFlags::DS, llvm::SIRegisterInfo::getProperlyAlignedRC(), llvm::SIRegisterInfo::getRegClass(), llvm::MCInstrDesc::mayLoad(), llvm::MCInstrDesc::mayStore(), llvm::SIInstrFlags::MIMG, MRI, llvm::SIInstrFlags::Spill, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::SIInstrInfo::getOpRegClass(), and llvm::SIInstrInfo::getRegClass().
canRemat()
bool canRemat (const MachineInstr & MI) static
Definition at line 108 of file SIInstrInfo.cpp.
References llvm::all_of(), llvm::SIInstrInfo::isSALU(), llvm::SIInstrInfo::isSDWA(), llvm::SIInstrInfo::isSMRD(), llvm::SIInstrInfo::isVOP1(), llvm::SIInstrInfo::isVOP2(), llvm::SIInstrInfo::isVOP3(), and MI.
Referenced by llvm::SIInstrInfo::isReallyTriviallyReMaterializable().
changesVGPRIndexingMode()
bool changesVGPRIndexingMode (const MachineInstr & MI) static
Definition at line 4226 of file SIInstrInfo.cpp.
References MI.
Referenced by llvm::SIInstrInfo::isSchedulingBoundary().
compareMachineOp()
bool compareMachineOp (const MachineOperand & Op0, const MachineOperand & Op1) static
Definition at line 4484 of file SIInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_Immediate, and llvm::MachineOperand::MO_Register.
Referenced by llvm::SIInstrInfo::verifyInstruction().
copyFlagsToImplicitVCC()
void copyFlagsToImplicitVCC (MachineInstr & MI, const MachineOperand & Orig) static
Definition at line 4622 of file SIInstrInfo.cpp.
References llvm::MachineOperand::isKill(), llvm::MachineOperand::isUndef(), and MI.
Referenced by llvm::SIInstrInfo::buildShrunkInst().
emitLoadScalarOpsFromVGPRLoop()
void emitLoadScalarOpsFromVGPRLoop (const SIInstrInfo & TII, MachineRegisterInfo & MRI, MachineBasicBlock & LoopBB, MachineBasicBlock & BodyBB, const DebugLoc & DL, ArrayRef< MachineOperand * > ScalarOps) static
Definition at line 6567 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::getUndefRegState(), I, llvm::RegState::Kill, Merge, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RegSize, TII, and TRI.
Referenced by loadMBUFScalarOperandsFromVGPR().
expandSGPRCopy()
void expandSGPRCopy (const SIInstrInfo & TII, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc, const TargetRegisterClass * RC, bool Forward) static
Definition at line 759 of file SIInstrInfo.cpp.
References llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineOperand::CreateReg(), DL, llvm::SIRegisterInfo::getChannelFromSubReg(), llvm::SIRegisterInfo::getRegSplitParts(), llvm::SIRegisterInfo::getSubRegFromChannel(), I, llvm::RegState::Implicit, MBB, MI, llvm::ArrayRef< T >::size(), std::swap(), and TII.
Referenced by llvm::SIInstrInfo::copyPhysReg().
extractRsrcPtr()
std::tuple< unsigned, unsigned > extractRsrcPtr (const SIInstrInfo & TII, MachineInstr & MI, MachineOperand & Rsrc) static
Definition at line 6820 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineFunction::getRegInfo(), llvm::Hi_32(), llvm::Lo_32(), MBB, MI, MRI, and TII.
Referenced by llvm::SIInstrInfo::legalizeOperands().
findImplicitSGPRRead()
Register findImplicitSGPRRead (const MachineInstr & MI) static
Definition at line 4706 of file SIInstrInfo.cpp.
References MI, and Register.
Referenced by llvm::SIInstrInfo::legalizeOperandsVOP2(), and llvm::SIInstrInfo::verifyInstruction().
followSubRegDef()
bool followSubRegDef (MachineInstr & MI, TargetInstrInfo::RegSubRegPair & RSR) static
Definition at line 9777 of file SIInstrInfo.cpp.
References getRegOrUndef(), llvm::getRegSequenceSubReg(), MI, llvm::TargetInstrInfo::RegSubRegPair::Reg, and llvm::TargetInstrInfo::RegSubRegPair::SubReg.
Referenced by llvm::getVRegSubRegDef().
getAGPRSpillRestoreOpcode()
unsigned getAGPRSpillRestoreOpcode (unsigned Size) static
Definition at line 1857 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillRestoreOpcode().
getAGPRSpillSaveOpcode()
unsigned getAGPRSpillSaveOpcode (unsigned Size) static
Definition at line 1628 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillSaveOpcode().
getAVSpillRestoreOpcode()
unsigned getAVSpillRestoreOpcode (unsigned Size) static
Definition at line 1892 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillRestoreOpcode().
getAVSpillSaveOpcode()
unsigned getAVSpillSaveOpcode (unsigned Size) static
Definition at line 1663 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillSaveOpcode().
getFoldableImm() [1/2]
bool getFoldableImm (const MachineOperand * MO, int64_t & Imm, MachineInstr ** DefMI = nullptr) static
Definition at line 3926 of file SIInstrInfo.cpp.
References DefMI, getFoldableImm(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::isReg(), and MRI.
getFoldableImm() [2/2]
bool getFoldableImm (Register Reg, const MachineRegisterInfo & MRI, int64_t & Imm, MachineInstr ** DefMI = nullptr) static
Definition at line 3912 of file SIInstrInfo.cpp.
References DefMI, llvm::SIInstrInfo::isFoldableCopy(), MRI, and Reg.
Referenced by llvm::SIInstrInfo::convertToThreeAddress(), getFoldableImm(), and llvm::SIInstrInfo::optimizeCompareInstr().
getIndirectSGPRWriteMovRelPseudo32()
unsigned getIndirectSGPRWriteMovRelPseudo32 (unsigned VecSize) static
Definition at line 1494 of file SIInstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::SIInstrInfo::getIndirectRegWriteMovRelPseudo().
getIndirectSGPRWriteMovRelPseudo64()
unsigned getIndirectSGPRWriteMovRelPseudo64 (unsigned VecSize) static
Definition at line 1523 of file SIInstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::SIInstrInfo::getIndirectRegWriteMovRelPseudo().
getIndirectVGPRWriteMovRelPseudoOpc()
unsigned getIndirectVGPRWriteMovRelPseudoOpc (unsigned VecSize) static
Definition at line 1465 of file SIInstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::SIInstrInfo::getIndirectRegWriteMovRelPseudo().
getNewFMAAKInst()
unsigned getNewFMAAKInst (const GCNSubtarget & ST, unsigned Opc) static
Definition at line 3493 of file SIInstrInfo.cpp.
References llvm_unreachable, and Opc.
Referenced by llvm::SIInstrInfo::convertToThreeAddress(), and llvm::SIInstrInfo::foldImmediate().
getNewFMAInst()
unsigned getNewFMAInst (const GCNSubtarget & ST, unsigned Opc) static
Definition at line 3947 of file SIInstrInfo.cpp.
References llvm_unreachable, and Opc.
Referenced by llvm::SIInstrInfo::convertToThreeAddress().
getNewFMAMKInst()
unsigned getNewFMAMKInst (const GCNSubtarget & ST, unsigned Opc) static
Definition at line 3525 of file SIInstrInfo.cpp.
References llvm_unreachable, and Opc.
Referenced by llvm::SIInstrInfo::convertToThreeAddress(), and llvm::SIInstrInfo::foldImmediate().
getNumOperandsNoGlue()
unsigned getNumOperandsNoGlue (SDNode * Node) static
Definition at line 73 of file SIInstrInfo.cpp.
References N.
Referenced by llvm::SIInstrInfo::areLoadsFromSameBasePtr().
getRegOrUndef()
TargetInstrInfo::RegSubRegPair getRegOrUndef (const MachineOperand & RegOpnd) static
Definition at line 9758 of file SIInstrInfo.cpp.
References assert(), llvm::getRegSubRegPair(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isUndef().
Referenced by followSubRegDef(), and llvm::getRegSequenceSubReg().
getSGPRSpillRestoreOpcode()
unsigned getSGPRSpillRestoreOpcode (unsigned Size) static
Definition at line 1785 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by llvm::SIInstrInfo::loadRegFromStackSlot().
getSGPRSpillSaveOpcode()
unsigned getSGPRSpillSaveOpcode (unsigned Size) static
Definition at line 1556 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by llvm::SIInstrInfo::storeRegToStackSlot().
getVectorRegSpillRestoreOpcode()
unsigned getVectorRegSpillRestoreOpcode (Register Reg, const TargetRegisterClass * RC, unsigned Size, const SIRegisterInfo & TRI, const SIMachineFunctionInfo & MFI) static
Definition at line 1940 of file SIInstrInfo.cpp.
References llvm::SIMachineFunctionInfo::checkFlag(), getAGPRSpillRestoreOpcode(), getAVSpillRestoreOpcode(), getVGPRSpillRestoreOpcode(), getWWMRegSpillRestoreOpcode(), Reg, Size, TRI, and llvm::AMDGPU::VirtRegFlag::WWM_REG.
Referenced by llvm::SIInstrInfo::loadRegFromStackSlot().
getVectorRegSpillSaveOpcode()
unsigned getVectorRegSpillSaveOpcode (Register Reg, const TargetRegisterClass * RC, unsigned Size, const SIRegisterInfo & TRI, const SIMachineFunctionInfo & MFI) static
Definition at line 1710 of file SIInstrInfo.cpp.
References llvm::SIMachineFunctionInfo::checkFlag(), getAGPRSpillSaveOpcode(), getAVSpillSaveOpcode(), getVGPRSpillSaveOpcode(), getWWMRegSpillSaveOpcode(), Reg, Size, TRI, and llvm::AMDGPU::VirtRegFlag::WWM_REG.
Referenced by llvm::SIInstrInfo::storeRegToStackSlot().
getVGPRSpillRestoreOpcode()
unsigned getVGPRSpillRestoreOpcode (unsigned Size) static
Definition at line 1820 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillRestoreOpcode().
getVGPRSpillSaveOpcode()
unsigned getVGPRSpillSaveOpcode (unsigned Size) static
Definition at line 1591 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillSaveOpcode().
getWWMRegSpillRestoreOpcode()
unsigned getWWMRegSpillRestoreOpcode (unsigned Size, bool IsVectorSuperClass) static
Definition at line 1927 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillRestoreOpcode().
getWWMRegSpillSaveOpcode()
unsigned getWWMRegSpillSaveOpcode (unsigned Size, bool IsVectorSuperClass) static
Definition at line 1698 of file SIInstrInfo.cpp.
References llvm_unreachable, and Size.
Referenced by getVectorRegSpillSaveOpcode().
indirectCopyToAGPR()
void indirectCopyToAGPR (const SIInstrInfo & TII, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc, RegScavenger & RS, bool RegsOverlap, Register ImpDefSuperReg = Register(), Register ImpUseSuperReg = Register()) static
Handle copying from SGPR to AGPR, or from AGPR to AGPR on GFX908.
It is not possible to have a direct copy in these cases on GFX908, so an intermediate VGPR copy is required.
Definition at line 640 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::RegScavenger::backward(), llvm::BuildMI(), contains(), llvm::RegState::Define, DL, E(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::SIRegisterInfo::getHWRegIndex(), llvm::getKillRegState(), llvm::MachineOperand::getReg(), llvm::SIRegisterInfo::getRegPressureLimit(), I, llvm::RegState::Implicit, llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::RegState::Kill, MBB, MI, llvm::RegScavenger::scavengeRegisterBackwards(), llvm::MachineOperand::setIsKill(), llvm::RegScavenger::setRegUsed(), and TII.
Referenced by llvm::SIInstrInfo::copyPhysReg().
isRegOrFI()
bool isRegOrFI (const MachineOperand & MO) static
Definition at line 4750 of file SIInstrInfo.cpp.
References llvm::MachineOperand::isFI(), and llvm::MachineOperand::isReg().
Referenced by llvm::SIInstrInfo::verifyInstruction().
isRenamedInGFX9()
bool isRenamedInGFX9 (int Opcode) static
Definition at line 9665 of file SIInstrInfo.cpp.
References GENERATE_RENAMED_GFX9_CASES.
Referenced by llvm::SIInstrInfo::pseudoToMCOpcode().
isStride64()
bool isStride64 (unsigned Opc) static
Definition at line 350 of file SIInstrInfo.cpp.
References Opc.
Referenced by llvm::SIInstrInfo::getMemOperandsWithOffsetWidth().
isSubRegOf()
bool isSubRegOf (const SIRegisterInfo & TRI, const MachineOperand & SuperVec, const MachineOperand & SubReg) static
Definition at line 4754 of file SIInstrInfo.cpp.
References llvm::MachineOperand::getReg(), SubReg, and TRI.
Referenced by llvm::SIInstrInfo::verifyInstruction().
loadMBUFScalarOperandsFromVGPR()
MachineBasicBlock * loadMBUFScalarOperandsFromVGPR (const SIInstrInfo & TII, MachineInstr & MI, ArrayRef< MachineOperand * > ScalarOps, MachineDominatorTree * MDT, MachineBasicBlock::iterator Begin = nullptr, MachineBasicBlock::iterator End = nullptr) static
Definition at line 6713 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::MachineFunction::CreateMachineBasicBlock(), DL, emitLoadScalarOpsFromVGPRLoop(), llvm::First, llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineFunction::insert(), llvm::RegState::Kill, llvm::MachineBasicBlock::LQR_Dead, MBB, MBBI, MI, MRI, llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::successors(), TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), and TRI.
Referenced by llvm::SIInstrInfo::legalizeOperands().
memOpsHaveSameBaseOperands()
bool memOpsHaveSameBaseOperands (ArrayRef< const MachineOperand * > BaseOps1, ArrayRef< const MachineOperand * > BaseOps2) static
Definition at line 3803 of file SIInstrInfo.cpp.
References E(), I, and llvm::ArrayRef< T >::size().
memOpsHaveSameBasePtr()
bool memOpsHaveSameBasePtr (const MachineInstr & MI1, ArrayRef< const MachineOperand * > BaseOps1, const MachineInstr & MI2, ArrayRef< const MachineOperand * > BaseOps2) static
Definition at line 528 of file SIInstrInfo.cpp.
References llvm::ArrayRef< T >::front(), llvm::getUnderlyingObject(), llvm::MachineInstr::hasOneMemOperand(), llvm::isa(), and llvm::MachineInstr::memoperands_begin().
Referenced by llvm::RISCVInstrInfo::shouldClusterMemOps(), and llvm::SIInstrInfo::shouldClusterMemOps().
nodesHaveSameOperandValue()
bool nodesHaveSameOperandValue (SDNode * N0, SDNode * N1, AMDGPU::OpName OpName) static
Returns true if both nodes have the same value for the given operand Op, or if both nodes do not have this operand.
Definition at line 82 of file SIInstrInfo.cpp.
References llvm::SDNode::getMachineOpcode(), and llvm::SDNode::getOperand().
Referenced by llvm::SIInstrInfo::areLoadsFromSameBasePtr().
offsetsDoNotOverlap()
bool offsetsDoNotOverlap (LocationSize WidthA, int OffsetA, LocationSize WidthB, int OffsetB) static
Definition at line 3814 of file SIInstrInfo.cpp.
References llvm::LocationSize::getValue(), and llvm::LocationSize::hasValue().
preserveCondRegFlags()
void preserveCondRegFlags (MachineOperand & CondReg, const MachineOperand & OrigCond) static
Definition at line 3210 of file SIInstrInfo.cpp.
References llvm::MachineOperand::isKill(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::setIsKill(), and llvm::MachineOperand::setIsUndef().
Referenced by llvm::SIInstrInfo::insertBranch(), and llvm::SIInstrInfo::insertSelect().
reportIllegalCopy()
void reportIllegalCopy (const SIInstrInfo * TII, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc, const char * Msg = "illegal VGPR to SGPR copy") static
Definition at line 623 of file SIInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::CallingConv::C, DL, llvm::DS_Error, llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::getKillRegState(), MBB, MI, and TII.
Referenced by llvm::SIInstrInfo::copyPhysReg().
shouldReadExec()
bool shouldReadExec (const MachineInstr & MI) static
Definition at line 4728 of file SIInstrInfo.cpp.
References llvm::SIInstrInfo::isSALU(), llvm::SIInstrInfo::isSMRD(), llvm::SIInstrInfo::isVALU(), and MI.
Referenced by llvm::SIInstrInfo::verifyInstruction().
subtargetEncodingFamily()
unsigned subtargetEncodingFamily (const GCNSubtarget & ST) static
Definition at line 9617 of file SIInstrInfo.cpp.
References llvm::AMDGPUSubtarget::GFX10, llvm::SIEncodingFamily::GFX10, llvm::AMDGPUSubtarget::GFX11, llvm::SIEncodingFamily::GFX11, llvm::AMDGPUSubtarget::GFX12, llvm::SIEncodingFamily::GFX12, llvm::SIEncodingFamily::GFX1250, llvm::AMDGPUSubtarget::GFX9, llvm_unreachable, llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::SIEncodingFamily::SI, llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, llvm::SIEncodingFamily::VI, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
Referenced by llvm::SIInstrInfo::pseudoToMCOpcode().
swapImmOperands()
MachineInstr * swapImmOperands (MachineInstr & MI, MachineOperand & NonRegOp1, MachineOperand & NonRegOp2) static
Definition at line 2773 of file SIInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getTargetFlags(), MI, llvm::MachineOperand::setImm(), and llvm::MachineOperand::setTargetFlags().
Referenced by llvm::SIInstrInfo::commuteInstructionImpl().
swapRegAndNonRegOperand()
MachineInstr * swapRegAndNonRegOperand (MachineInstr & MI, MachineOperand & RegOp, MachineOperand & NonRegOp) static
Definition at line 2744 of file SIInstrInfo.cpp.
References llvm::MachineOperand::ChangeToFrameIndex(), llvm::MachineOperand::ChangeToGA(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::getTargetFlags(), IsDead, llvm::MachineOperand::isDead(), llvm::MachineOperand::isDebug(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isUndef(), MI, Reg, llvm::MachineOperand::setSubReg(), llvm::MachineOperand::setTargetFlags(), and SubReg.
Referenced by llvm::SIInstrInfo::commuteInstructionImpl().
updateLiveVariables()
void updateLiveVariables (LiveVariables * LV, MachineInstr & MI, MachineInstr & NewMI) static
Definition at line 3935 of file SIInstrInfo.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, I, MI, and llvm::LiveVariables::replaceKillInstruction().
Referenced by llvm::SIInstrInfo::convertToThreeAddress().
Variable Documentation
BranchOffsetBits
cl::opt< unsigned > BranchOffsetBits("amdgpu-s-branch-bits", cl::ReallyHidden, cl::init(16), cl::desc("Restrict range of branch instructions (DEBUG)")) ("amdgpu-s-branch-bits" , cl::ReallyHidden , cl::init(16) , cl::desc("Restrict range of branch instructions (DEBUG)")) static
Referenced by llvm::SIInstrInfo::isBranchOffsetInRange().
Fix16BitCopies
cl::opt< bool > Fix16BitCopies("amdgpu-fix-16-bit-physreg-copies", cl::desc("Fix copies between 32 and 16 bit registers by extending to 32 bit"), cl::init(true), cl::ReallyHidden) ("amdgpu-fix-16-bit-physreg-copies" , cl::desc("Fix copies between 32 and 16 bit registers by extending to 32 bit") , cl::init(true) , cl::ReallyHidden) static
Referenced by llvm::SIInstrInfo::copyPhysReg().
ModifierOpNames
AMDGPU::OpName ModifierOpNames[] static constexpr
Initial value:
= {
    AMDGPU::OpName::src0_modifiers, AMDGPU::OpName::src1_modifiers,
    AMDGPU::OpName::src2_modifiers, AMDGPU::OpName::clamp,
    AMDGPU::OpName::omod,           AMDGPU::OpName::op_sel}
Definition at line 3455 of file SIInstrInfo.cpp.
Referenced by llvm::SIInstrInfo::hasAnyModifiersSet(), and llvm::SIInstrInfo::removeModOperands().