LLVM: lib/Target/AMDGPU/SIProgramInfo.cpp File Reference
SIProgramInfo.cpp File Reference
The SIProgramInfo tracks resource usage and hardware flags for kernels and entry functions.
#include "SIProgramInfo.h"
#include "GCNSubtarget.h"
#include "SIDefines.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/MC/MCExpr.h"
Functions
static uint64_t getComputePGMRSrc1Reg (const SIProgramInfo &ProgInfo, const GCNSubtarget &ST)
static uint64_t getPGMRSrc1Reg (const SIProgramInfo &ProgInfo, CallingConv::ID CC, const GCNSubtarget &ST)
static uint64_t getComputePGMRSrc2Reg (const SIProgramInfo &ProgInfo)
static const MCExpr * MaskShift (const MCExpr *Val, uint32_t Mask, uint32_t Shift, MCContext &Ctx)
Detailed Description
The SIProgramInfo tracks resource usage and hardware flags for kernels and entry functions.
Definition in file SIProgramInfo.cpp.
Function Documentation
getComputePGMRSrc1Reg()
uint64_t getComputePGMRSrc1Reg (const SIProgramInfo & ProgInfo, const GCNSubtarget & ST) static
Definition at line 81 of file SIProgramInfo.cpp.
References llvm::Triple::AMDHSA, llvm::SIProgramInfo::DebugMode, llvm::SIProgramInfo::DX10Clamp, llvm::SIProgramInfo::FloatMode, llvm::SIProgramInfo::FwdProgress, llvm::SIProgramInfo::IEEEMode, llvm::SIProgramInfo::MemOrdered, llvm::SIProgramInfo::Priority, llvm::SIProgramInfo::Priv, Reg, llvm::SIProgramInfo::RrWgMode, S_00B848_DEBUG_MODE, S_00B848_DX10_CLAMP, S_00B848_FLOAT_MODE, S_00B848_FWD_PROGRESS, S_00B848_IEEE_MODE, S_00B848_MEM_ORDERED, S_00B848_PRIORITY, S_00B848_PRIV, S_00B848_RR_WG_MODE, S_00B848_WGP_MODE, and llvm::SIProgramInfo::WgpMode.
Referenced by llvm::SIProgramInfo::getComputePGMRSrc1().
getComputePGMRSrc2Reg()
uint64_t getComputePGMRSrc2Reg (const SIProgramInfo & ProgInfo) static
Definition at line 143 of file SIProgramInfo.cpp.
References llvm::SIProgramInfo::EXCPEnable, llvm::SIProgramInfo::EXCPEnMSB, llvm::SIProgramInfo::LdsSize, Reg, S_00B84C_EXCP_EN, S_00B84C_EXCP_EN_MSB, S_00B84C_LDS_SIZE, S_00B84C_TG_SIZE_EN, S_00B84C_TGID_X_EN, S_00B84C_TGID_Y_EN, S_00B84C_TGID_Z_EN, S_00B84C_TIDIG_COMP_CNT, S_00B84C_TRAP_HANDLER, S_00B84C_USER_SGPR, llvm::SIProgramInfo::TGIdXEnable, llvm::SIProgramInfo::TGIdYEnable, llvm::SIProgramInfo::TGIdZEnable, llvm::SIProgramInfo::TGSizeEnable, llvm::SIProgramInfo::TIdIGCompCount, llvm::SIProgramInfo::TrapHandlerEnable, and llvm::SIProgramInfo::UserSGPR.
Referenced by llvm::SIProgramInfo::getComputePGMRSrc2().
getPGMRSrc1Reg()
uint64_t getPGMRSrc1Reg (const SIProgramInfo & ProgInfo, CallingConv::ID CC, const GCNSubtarget & ST) static
Definition at line 106 of file SIProgramInfo.cpp.
References llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::SIProgramInfo::DebugMode, llvm::SIProgramInfo::DX10Clamp, llvm::SIProgramInfo::FloatMode, llvm::SIProgramInfo::IEEEMode, llvm::SIProgramInfo::MemOrdered, llvm::SIProgramInfo::Priority, llvm::SIProgramInfo::Priv, Reg, llvm::SIProgramInfo::RrWgMode, S_00B028_MEM_ORDERED, S_00B128_MEM_ORDERED, S_00B228_MEM_ORDERED, S_00B228_WGP_MODE, S_00B428_MEM_ORDERED, S_00B428_WGP_MODE, S_00B848_DEBUG_MODE, S_00B848_DX10_CLAMP, S_00B848_FLOAT_MODE, S_00B848_IEEE_MODE, S_00B848_PRIORITY, S_00B848_PRIV, S_00B848_RR_WG_MODE, and llvm::SIProgramInfo::WgpMode.
Referenced by llvm::SIProgramInfo::getPGMRSrc1().
MaskShift()
const MCExpr * MaskShift (const MCExpr * Val, uint32_t Mask, uint32_t Shift, MCContext & Ctx) static
Definition at line 158 of file SIProgramInfo.cpp.
References llvm::MCConstantExpr::create(), llvm::MCBinaryExpr::createAnd(), and llvm::MCBinaryExpr::createShl().
Referenced by canEvaluateShiftedShift(), llvm::SIProgramInfo::getComputePGMRSrc1(), llvm::SIProgramInfo::getPGMRSrc1(), and tryToRecognizePopCount().