LLVM: lib/Target/SPIRV/SPIRVAsmPrinter.cpp File Reference
SPIRVAsmPrinter.cpp File Reference
#include "MCTargetDesc/SPIRVInstPrinter.h"
#include "SPIRV.h"
#include "SPIRVInstrInfo.h"
#include "SPIRVMCInstLower.h"
#include "SPIRVModuleAnalysis.h"
#include "SPIRVSubtarget.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "TargetInfo/SPIRVTargetInfo.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCSPIRVObjectWriter.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static bool isFuncOrHeaderInstr (const MachineInstr *MI, const SPIRVInstrInfo *TII)
static unsigned encodeVecTypeHint (Type *Ty)
static void addOpsFromMDNode (MDNode *MDN, MCInst &Inst, SPIRV::ModuleAnalysisInfo *MAI)
INITIALIZE_PASS (SPIRVAsmPrinter, "spirv-asm-printer", "SPIRV Assembly Printer", false, false) extern "C" LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSPIRVAsmPrinter()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 43 of file SPIRVAsmPrinter.cpp.
Function Documentation
addOpsFromMDNode()
void addOpsFromMDNode (MDNode * MDN, MCInst & Inst, SPIRV::ModuleAnalysisInfo * MAI) static
Definition at line 440 of file SPIRVAsmPrinter.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::CallingConv::C, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::dyn_cast(), llvm::SPIRV::ModuleAnalysisInfo::getFuncReg(), llvm::MCRegister::isValid(), and llvm::MDNode::operands().
encodeVecTypeHint()
unsigned encodeVecTypeHint (Type * Ty) static
Definition at line 411 of file SPIRVAsmPrinter.cpp.
References llvm::dyn_cast(), encodeVecTypeHint(), llvm_unreachable, and Size.
Referenced by encodeVecTypeHint().
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVAsmPrinter , "spirv-asm-printer" , "SPIRV Assembly Printer" , false , false)
Definition at line 657 of file SPIRVAsmPrinter.cpp.
References llvm::getTheSPIRV32Target(), llvm::getTheSPIRV64Target(), llvm::getTheSPIRVLogicalTarget(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, X, and Y.
isFuncOrHeaderInstr()
bool isFuncOrHeaderInstr (const MachineInstr * MI, const SPIRVInstrInfo * TII) static
Definition at line 259 of file SPIRVAsmPrinter.cpp.
References MI, and TII.