LLVM: lib/Support/StringRef.cpp File Reference
StringRef.cpp File Reference
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/edit_distance.h"
#include "llvm/Support/Error.h"
#include <bitset>
Functions
static int ascii_strncasecmp (StringRef LHS, StringRef RHS)
static unsigned GetAutoSenseRadix (StringRef &Str)
Function Documentation
ascii_strncasecmp()
int ascii_strncasecmp (StringRef LHS, StringRef RHS) static
Definition at line 27 of file StringRef.cpp.
References LHS, RHS, llvm::toLower(), and llvm::zip_equal().
Referenced by llvm::StringRef::compare_insensitive(), llvm::StringRef::ends_with_insensitive(), and llvm::StringRef::starts_with_insensitive().
GetAutoSenseRadix()
unsigned GetAutoSenseRadix (StringRef & Str) static
Definition at line 388 of file StringRef.cpp.
References llvm::isDigit().
Referenced by llvm::StringRef::consumeInteger(), and llvm::consumeUnsignedInteger().