LLVM: lib/TableGen/StringMatcher.cpp File Reference
StringMatcher.cpp File Reference
#include "llvm/TableGen/StringMatcher.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <map>
#include <string>
#include <utility>
#include <vector>
Functions
static unsigned FindFirstNonCommonLetter (ArrayRef< const StringMatcher::StringPair * > Matches)
FindFirstNonCommonLetter - Find the first character in the keys of the string pairs that is not shared across the whole set of strings.
Function Documentation
FindFirstNonCommonLetter()
unsigned FindFirstNonCommonLetter (ArrayRef< const StringMatcher::StringPair * > Matches) static
FindFirstNonCommonLetter - Find the first character in the keys of the string pairs that is not shared across the whole set of strings.
All strings are assumed to have the same length.
Definition at line 29 of file StringMatcher.cpp.
References assert(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::enumerate(), and llvm::ArrayRef< T >::size().