LLVM: llvm::MinidumpYAML::ExceptionStream Struct Reference
llvm::MinidumpYAML::ExceptionStream Struct Reference
ExceptionStream minidump stream.
#include "llvm/ObjectYAML/MinidumpYAML.h"
Public Member Functions
ExceptionStream ()
ExceptionStream (const minidump::ExceptionStream &MDExceptionStream, ArrayRef< uint8_t > ThreadContext)
Public Member Functions inherited from llvm::MinidumpYAML::Stream
Stream (StreamKind Kind, minidump::StreamType Type)
virtual ~Stream ()
Static Public Member Functions
static bool classof (const Stream *S)
Static Public Member Functions inherited from llvm::MinidumpYAML::Stream
static StreamKind getKind (minidump::StreamType Type)
Get the stream Kind used for representing streams of a given Type.
static std::unique_ptr< Stream > create (minidump::StreamType Type)
Create an empty stream of the given Type.
static Expected< std::unique_ptr< Stream > > create (const minidump::Directory &StreamDesc, const object::MinidumpFile &File)
Create a stream from the given stream directory entry.
Public Attributes
minidump::ExceptionStream MDExceptionStream
yaml::BinaryRef ThreadContext
Public Attributes inherited from llvm::MinidumpYAML::Stream
const StreamKind Kind
const minidump::StreamType Type
Additional Inherited Members
Public Types inherited from llvm::MinidumpYAML::Stream
enum class StreamKind {
Exception , MemoryInfoList , MemoryList , Memory64List ,
ModuleList , RawContent , SystemInfo , TextContent ,
ThreadList
}
Detailed Description
ExceptionStream minidump stream.
Definition at line 127 of file MinidumpYAML.h.
Constructor & Destructor Documentation
ExceptionStream() [1/2]
llvm::MinidumpYAML::ExceptionStream::ExceptionStream () inline
Definition at line 131 of file MinidumpYAML.h.
References llvm::MinidumpYAML::Stream::Exception, MDExceptionStream, and llvm::MinidumpYAML::Stream::Stream().
ExceptionStream() [2/2]
llvm::MinidumpYAML::ExceptionStream::ExceptionStream (const minidump::ExceptionStream & MDExceptionStream, ArrayRef< uint8_t > ThreadContext) inline explicit
Definition at line 135 of file MinidumpYAML.h.
References llvm::MinidumpYAML::Stream::Exception, MDExceptionStream, llvm::MinidumpYAML::Stream::Stream(), and ThreadContext.
Member Function Documentation
classof()
bool llvm::MinidumpYAML::ExceptionStream::classof (const Stream * S) inline static
Definition at line 140 of file MinidumpYAML.h.
References llvm::MinidumpYAML::Stream::Exception, llvm::MinidumpYAML::Stream::Kind, and llvm::MinidumpYAML::Stream::Stream().
Member Data Documentation
MDExceptionStream
minidump::ExceptionStream llvm::MinidumpYAML::ExceptionStream::MDExceptionStream
Definition at line 128 of file MinidumpYAML.h.
Referenced by ExceptionStream(), ExceptionStream(), and layout().
ThreadContext
yaml::BinaryRef llvm::MinidumpYAML::ExceptionStream::ThreadContext
Definition at line 129 of file MinidumpYAML.h.
Referenced by ExceptionStream(), and layout().
The documentation for this struct was generated from the following file:
include/llvm/ObjectYAML/MinidumpYAML.h