LLVM: llvm::GraphTraits< PostDominatorTree * > Struct Reference
llvm::GraphTraits< PostDominatorTree * > Struct Reference
#include "llvm/Analysis/PostDominators.h"
Public Types
using NodeRef
Public Types inherited from llvm::GraphTraits< DomTreeNode * >
using NodeRef
Public Types inherited from llvm::DomTreeGraphTraitsBase< DomTreeNode, DomTreeNode::const_iterator >
using NodeRef
using ChildIteratorType
using nodes_iterator
Static Public Member Functions
static NodeRef getEntryNode (PostDominatorTree *DT)
static nodes_iterator nodes_begin (PostDominatorTree *N)
static nodes_iterator nodes_end (PostDominatorTree *N)
Static Public Member Functions inherited from llvm::DomTreeGraphTraitsBase< DomTreeNode, DomTreeNode::const_iterator >
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static nodes_iterator nodes_begin (NodeRef N)
static nodes_iterator nodes_end (NodeRef N)
Detailed Description
Definition at line 101 of file PostDominators.h.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< PostDominatorTree * >::NodeRef
Definition at line 95 of file GraphTraits.h.
Member Function Documentation
getEntryNode()
NodeRef llvm::GraphTraits< PostDominatorTree * >::getEntryNode (PostDominatorTree * DT) inline static
Definition at line 103 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode().
Referenced by nodes_begin(), and nodes_end().
nodes_begin()
nodes_iterator llvm::GraphTraits< PostDominatorTree * >::nodes_begin (PostDominatorTree * N) inline static
Definition at line 107 of file PostDominators.h.
References llvm::df_begin(), getEntryNode(), and N.
nodes_end()
nodes_iterator llvm::GraphTraits< PostDominatorTree * >::nodes_end (PostDominatorTree * N) inline static
Definition at line 111 of file PostDominators.h.
References llvm::df_end(), getEntryNode(), and N.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/PostDominators.h