LLVM: llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode > Struct Template Reference
llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
ClassifyOp_match (const LHS_P &LHS, const Test_P &Tst)
template<typename OpTy>
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
LHS_P L
Test_P T
Detailed Description
template<typename LHS_P, typename Test_P, unsigned Opcode>
struct llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode >
Definition at line 770 of file MIPatternMatch.h.
Constructor & Destructor Documentation
ClassifyOp_match()
template<typename LHS_P, typename Test_P, unsigned Opcode> llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode >::ClassifyOp_match (const LHS_P & LHS, const Test_P & Tst) inline
Definition at line 774 of file MIPatternMatch.h.
References L, LHS, and T.
Member Function Documentation
match()
template<typename LHS_P, typename Test_P, unsigned Opcode> template<typename OpTy> bool llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 777 of file MIPatternMatch.h.
References llvm::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), L, LHS, llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::mi_match(), MRI, and T.
Member Data Documentation
L
template<typename LHS_P, typename Test_P, unsigned Opcode> LHS_P llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode >::L
Definition at line 771 of file MIPatternMatch.h.
Referenced by ClassifyOp_match(), and match().
T
template<typename LHS_P, typename Test_P, unsigned Opcode> Test_P llvm::MIPatternMatch::ClassifyOp_match< LHS_P, Test_P, Opcode >::T
Definition at line 772 of file MIPatternMatch.h.
Referenced by ClassifyOp_match(), and match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h