LLVM: llvm::GraphTraits< DOTMachineFuncInfo * > Struct Reference
llvm::GraphTraits< DOTMachineFuncInfo * > Struct Reference
#include "llvm/CodeGen/MachineCFGPrinter.h"
Public Types
using nodes_iterator = pointer_iterator<MachineFunction::const_iterator>
using NodeRef
Public Types inherited from llvm::GraphTraits< const MachineBasicBlock * >
using NodeRef = const MachineBasicBlock *
using ChildIteratorType = MachineBasicBlock::const_succ_iterator
Static Public Member Functions
static NodeRef getEntryNode (DOTMachineFuncInfo *CFGInfo)
static nodes_iterator nodes_begin (DOTMachineFuncInfo *CFGInfo)
static nodes_iterator nodes_end (DOTMachineFuncInfo *CFGInfo)
static size_t size (DOTMachineFuncInfo *CFGInfo)
Static Public Member Functions inherited from llvm::GraphTraits< const MachineBasicBlock * >
static NodeRef getEntryNode (const MachineBasicBlock *BB)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static unsigned getNumber (const MachineBasicBlock *BB)
Detailed Description
Definition at line 31 of file MachineCFGPrinter.h.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< DOTMachineFuncInfo * >::NodeRef
Definition at line 95 of file GraphTraits.h.
nodes_iterator
using llvm::GraphTraits< DOTMachineFuncInfo * >::nodes_iterator = pointer_iterator<MachineFunction::const_iterator>
Definition at line 38 of file MachineCFGPrinter.h.
Member Function Documentation
getEntryNode()
NodeRef llvm::GraphTraits< DOTMachineFuncInfo * >::getEntryNode (DOTMachineFuncInfo * CFGInfo) inline static
Definition at line 33 of file MachineCFGPrinter.h.
References llvm::DOTMachineFuncInfo::getFunction().
nodes_begin()
nodes_iterator llvm::GraphTraits< DOTMachineFuncInfo * >::nodes_begin (DOTMachineFuncInfo * CFGInfo) inline static
Definition at line 40 of file MachineCFGPrinter.h.
References llvm::MachineFunction::begin(), and llvm::DOTMachineFuncInfo::getFunction().
nodes_end()
nodes_iterator llvm::GraphTraits< DOTMachineFuncInfo * >::nodes_end (DOTMachineFuncInfo * CFGInfo) inline static
Definition at line 44 of file MachineCFGPrinter.h.
References llvm::MachineFunction::end(), and llvm::DOTMachineFuncInfo::getFunction().
size()
size_t llvm::GraphTraits< DOTMachineFuncInfo * >::size (DOTMachineFuncInfo * CFGInfo) inline static
Definition at line 48 of file MachineCFGPrinter.h.
References llvm::DOTMachineFuncInfo::getFunction(), and llvm::MachineFunction::size().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineCFGPrinter.h