LLVM: llvm::MDNodeKeyImpl< GenericDINode > Struct Reference
llvm::MDNodeKeyImpl< GenericDINode > Struct Reference
DenseMapInfo for GenericDINode.
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Tag, MDString *Header, ArrayRef< Metadata * > DwarfOps)
MDNodeKeyImpl (const GenericDINode *N)
bool isKeyOf (const GenericDINode *RHS) const
unsigned getHashValue () const
Public Member Functions inherited from llvm::MDNodeOpsKey
unsigned getHash () const
Static Public Member Functions
static unsigned calculateHash (GenericDINode *N)
Public Attributes
unsigned Tag
MDString * Header
Additional Inherited Members
Protected Member Functions inherited from llvm::MDNodeOpsKey
MDNodeOpsKey (ArrayRef< Metadata * > Ops)
template<class NodeTy>
MDNodeOpsKey (const NodeTy *N, unsigned Offset=0)
template<class NodeTy>
bool compareOps (const NodeTy *RHS, unsigned Offset=0) const
Static Protected Member Functions inherited from llvm::MDNodeOpsKey
static unsigned calculateHash (MDNode *N, unsigned Offset=0)
Detailed Description
DenseMapInfo for GenericDINode.
Definition at line 372 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< GenericDINode >::MDNodeKeyImpl (unsigned Tag, MDString * Header, ArrayRef< Metadata * > DwarfOps) inline
Definition at line 376 of file LLVMContextImpl.h.
References Header, llvm::MDNodeOpsKey::MDNodeOpsKey(), and Tag.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< GenericDINode >::MDNodeKeyImpl (const GenericDINode * N) inline
Definition at line 378 of file LLVMContextImpl.h.
References getTag(), Header, llvm::MDNodeOpsKey::MDNodeOpsKey(), N, and Tag.
Member Function Documentation
calculateHash()
unsigned llvm::MDNodeKeyImpl< GenericDINode >::calculateHash (GenericDINode * N) inline static
Definition at line 388 of file LLVMContextImpl.h.
References llvm::MDNodeOpsKey::calculateHash(), and N.
getHashValue()
unsigned llvm::MDNodeKeyImpl< GenericDINode >::getHashValue () const inline
Definition at line 386 of file LLVMContextImpl.h.
References llvm::MDNodeOpsKey::getHash(), llvm::hash_combine(), Header, and Tag.
isKeyOf()
bool llvm::MDNodeKeyImpl< GenericDINode >::isKeyOf (const GenericDINode * RHS) const inline
Definition at line 381 of file LLVMContextImpl.h.
References llvm::MDNodeOpsKey::compareOps(), Header, RHS, and Tag.
Member Data Documentation
Header
MDString* llvm::MDNodeKeyImpl< GenericDINode >::Header
Definition at line 374 of file LLVMContextImpl.h.
Referenced by getHashValue(), isKeyOf(), MDNodeKeyImpl(), and MDNodeKeyImpl().
Tag
unsigned llvm::MDNodeKeyImpl< GenericDINode >::Tag
Definition at line 373 of file LLVMContextImpl.h.
Referenced by getHashValue(), isKeyOf(), MDNodeKeyImpl(), and MDNodeKeyImpl().
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h