LLVM: llvm::logicalview::LVSourceLanguage Struct Reference
llvm::logicalview::LVSourceLanguage Struct Reference
A source language supported by any of the debug info representations.
#include "llvm/DebugInfo/LogicalView/Core/LVSourceLanguage.h"
Public Types
enum TaggedLanguage : uint32_t { Invalid = -1U }
Public Member Functions
LVSourceLanguage ()=default
LVSourceLanguage (llvm::dwarf::SourceLanguage SL)
LVSourceLanguage (llvm::codeview::SourceLanguage SL)
bool operator== (const LVSourceLanguage &SL) const
bool operator== (const LVSourceLanguage::TaggedLanguage &TL) const
bool isValid () const
TaggedLanguage get () const
LLVM_ABI StringRef getName () const
Static Public Attributes
static constexpr unsigned TagDwarf = 0x00
static constexpr unsigned TagCodeView = 0x01
Detailed Description
A source language supported by any of the debug info representations.
Definition at line 26 of file LVSourceLanguage.h.
Member Enumeration Documentation
TaggedLanguage
enum llvm::logicalview::LVSourceLanguage::TaggedLanguage : uint32_t
Enumerator
Invalid
Definition at line 30 of file LVSourceLanguage.h.
Constructor & Destructor Documentation
LVSourceLanguage() [1/3]
llvm::logicalview::LVSourceLanguage::LVSourceLanguage () default
Referenced by LVSourceLanguage(), LVSourceLanguage(), and operator==().
LVSourceLanguage() [2/3]
llvm::logicalview::LVSourceLanguage::LVSourceLanguage (llvm::dwarf::SourceLanguage SL) inline
Definition at line 43 of file LVSourceLanguage.h.
References LVSourceLanguage(), and TagDwarf.
LVSourceLanguage() [3/3]
llvm::logicalview::LVSourceLanguage::LVSourceLanguage (llvm::codeview::SourceLanguage SL) inline
Definition at line 45 of file LVSourceLanguage.h.
References LVSourceLanguage(), and TagCodeView.
Member Function Documentation
get()
TaggedLanguage llvm::logicalview::LVSourceLanguage::get () const inline
Definition at line 55 of file LVSourceLanguage.h.
Referenced by operator==(), and operator==().
getName()
StringRef LVSourceLanguage::getName () const
Definition at line 20 of file LVSourceLanguage.cpp.
References llvm::codeview::getSourceLanguageNames(), isValid(), llvm::dwarf::LanguageString(), llvm_unreachable, TagCodeView, and TagDwarf.
isValid()
bool llvm::logicalview::LVSourceLanguage::isValid () const inline
Definition at line 54 of file LVSourceLanguage.h.
References Invalid.
Referenced by getName(), and llvm::logicalview::LVScopeCompileUnit::printExtra().
operator==() [1/2]
bool llvm::logicalview::LVSourceLanguage::operator== (const LVSourceLanguage & SL) const inline
Definition at line 47 of file LVSourceLanguage.h.
References get(), and LVSourceLanguage().
operator==() [2/2]
bool llvm::logicalview::LVSourceLanguage::operator== (const LVSourceLanguage::TaggedLanguage & TL) const inline
Definition at line 50 of file LVSourceLanguage.h.
References get().
Member Data Documentation
TagCodeView
unsigned llvm::logicalview::LVSourceLanguage::TagCodeView = 0x01 static constexpr
Definition at line 28 of file LVSourceLanguage.h.
Referenced by getName(), and LVSourceLanguage().
TagDwarf
unsigned llvm::logicalview::LVSourceLanguage::TagDwarf = 0x00 static constexpr
Definition at line 27 of file LVSourceLanguage.h.
Referenced by getName(), and LVSourceLanguage().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVSourceLanguage.h
lib/DebugInfo/LogicalView/Core/LVSourceLanguage.cpp