LLVM: llvm::LaneBitmask Struct Reference
llvm::LaneBitmask Struct Reference
#include "llvm/MC/LaneBitmask.h"
Public Types
enum : unsigned { BitWidth = 8*sizeof(Type) }
using Type = uint64_t
Public Member Functions
constexpr LaneBitmask ()=default
constexpr LaneBitmask (Type V)
constexpr bool operator== (LaneBitmask M) const
constexpr bool operator!= (LaneBitmask M) const
constexpr bool operator< (LaneBitmask M) const
constexpr bool none () const
constexpr bool any () const
constexpr bool all () const
constexpr LaneBitmask operator~ () const
constexpr LaneBitmask operator| (LaneBitmask M) const
constexpr LaneBitmask operator& (LaneBitmask M) const
LaneBitmask & operator|= (LaneBitmask M)
LaneBitmask & operator&= (LaneBitmask M)
constexpr Type getAsInteger () const
unsigned getNumLanes () const
unsigned getHighestLane () const
Static Public Member Functions
static constexpr LaneBitmask getNone ()
static constexpr LaneBitmask getAll ()
static constexpr LaneBitmask getLane (unsigned Lane)
Static Public Attributes
static constexpr const char *const FormatStr = "%016llX"
Detailed Description
Definition at line 40 of file LaneBitmask.h.
Member Typedef Documentation
Type
using llvm::LaneBitmask::Type = uint64_t
Definition at line 42 of file LaneBitmask.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
BitWidth
Definition at line 43 of file LaneBitmask.h.
Constructor & Destructor Documentation
LaneBitmask() [1/2]
llvm::LaneBitmask::LaneBitmask () constexpr default
Referenced by getAll(), getLane(), getNone(), operator!=(), operator&(), operator&=(), operator<(), operator==(), operator|(), operator|=(), and operator~().
LaneBitmask() [2/2]
llvm::LaneBitmask::LaneBitmask (Type V) inline explicit constexpr
Definition at line 47 of file LaneBitmask.h.
Member Function Documentation
all()
bool llvm::LaneBitmask::all () const inline constexpr
Definition at line 54 of file LaneBitmask.h.
Referenced by llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), and llvm::rdf::LaneMaskIndex::getIndexForLaneMask().
any()
bool llvm::LaneBitmask::any () const inline constexpr
Definition at line 53 of file LaneBitmask.h.
Referenced by addRegLanes(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::RegPressureTracker::advance(), decreaseSetPressure(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::TargetRegisterInfo::getCoveringSubRegIndexes(), llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::RegPressureTracker::increaseRegPressure(), increaseSetPressure(), readsLaneSubset(), llvm::RegPressureTracker::recede(), llvm::LiveInterval::refineSubRanges(), removeRegLanes(), and llvm::GCNRegPressurePrinter::runOnMachineFunction().
getAll()
constexpr LaneBitmask llvm::LaneBitmask::getAll () inline static constexpr
Definition at line 82 of file LaneBitmask.h.
References LaneBitmask().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::MachineBasicBlock::addLiveIn(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), llvm::LiveIntervalCalc::calculate(), llvm::LiveIntervalCalc::constructMainRangeFromSubranges(), llvm::LiveIntervalCalc::extendToUses(), llvm::rdf::LaneMaskIndex::getLaneMaskForIndex(), llvm::ScheduleDAGInstrs::getLaneMaskForMO(), getLanesWithProperty(), getLanesWithProperty(), getLiveLanesAt(), llvm::RegPressureTracker::getLiveLanesAt(), llvm::rdf::DataFlowGraph::makeRegRef(), llvm::rdf::PhysicalRegisterInfo::mapTo(), llvm::rdf::RegisterRef::RegisterRef(), and llvm::LiveInterval::verify().
getAsInteger()
Type llvm::LaneBitmask::getAsInteger () const inline constexpr
Definition at line 74 of file LaneBitmask.h.
Referenced by llvm::SIRegisterInfo::getNumCoveredRegs(), and llvm::PrintLaneMask().
getHighestLane()
unsigned llvm::LaneBitmask::getHighestLane () const inline
Definition at line 77 of file LaneBitmask.h.
References llvm::Log2_64().
getLane()
constexpr LaneBitmask llvm::LaneBitmask::getLane (unsigned Lane) inline static constexpr
Definition at line 83 of file LaneBitmask.h.
References LaneBitmask().
getNone()
constexpr LaneBitmask llvm::LaneBitmask::getNone () inline static constexpr
Definition at line 81 of file LaneBitmask.h.
References LaneBitmask().
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::ScheduleDAGMILive::collectVRegUses(), computeLiveOuts(), llvm::LiveRegSet::contains(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::LiveRegSet::erase(), findUseBetween(), findUseBetween(), getLanesWithProperty(), getLanesWithProperty(), llvm::GCNRPTracker::getLastUsedLanes(), llvm::RegPressureTracker::getLastUsedLanes(), llvm::RegPressureTracker::getLiveThroughAt(), getRegLanes(), llvm::getRegPressure(), llvm::RegPressureTracker::initLiveThru(), llvm::LiveRegSet::insert(), llvm::GCNUpwardRPTracker::recede(), llvm::RegPressureTracker::recede(), llvm::GCNRPTarget::saveReg(), setRegZero(), llvm::LiveIntervals::shrinkToUses(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
getNumLanes()
unsigned llvm::LaneBitmask::getNumLanes () const inline
Definition at line 76 of file LaneBitmask.h.
References llvm::popcount().
Referenced by llvm::TargetRegisterInfo::getCoveringSubRegIndexes().
none()
bool llvm::LaneBitmask::none () const inline constexpr
Definition at line 52 of file LaneBitmask.h.
Referenced by llvm::RegisterOperands::adjustLaneLiveness(), llvm::LiveRangeEdit::allUsesAvailableAt(), llvm::GCNDownwardRPTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpDownwardPressure(), decreaseSetPressure(), findUseBetween(), findUseBetween(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::GCNRegPressure::inc(), llvm::RegPressureTracker::increaseRegPressure(), increaseSetPressure(), llvm::GCNUpwardRPTracker::recede(), llvm::RegPressureTracker::recede(), and llvm::LiveInterval::refineSubRanges().
operator!=()
bool llvm::LaneBitmask::operator!= (LaneBitmask M) const inline constexpr
Definition at line 50 of file LaneBitmask.h.
References LaneBitmask().
operator&()
LaneBitmask llvm::LaneBitmask::operator& (LaneBitmask M) const inline constexpr
Definition at line 62 of file LaneBitmask.h.
References LaneBitmask().
operator&=()
LaneBitmask & llvm::LaneBitmask::operator&= (LaneBitmask M) inline
Definition at line 69 of file LaneBitmask.h.
References LaneBitmask().
operator<()
bool llvm::LaneBitmask::operator< (LaneBitmask M) const inline constexpr
Definition at line 51 of file LaneBitmask.h.
References LaneBitmask().
operator==()
bool llvm::LaneBitmask::operator== (LaneBitmask M) const inline constexpr
Definition at line 49 of file LaneBitmask.h.
References LaneBitmask().
operator|()
LaneBitmask llvm::LaneBitmask::operator| (LaneBitmask M) const inline constexpr
Definition at line 59 of file LaneBitmask.h.
References LaneBitmask().
operator|=()
LaneBitmask & llvm::LaneBitmask::operator|= (LaneBitmask M) inline
Definition at line 65 of file LaneBitmask.h.
References LaneBitmask().
operator~()
LaneBitmask llvm::LaneBitmask::operator~ () const inline constexpr
Definition at line 56 of file LaneBitmask.h.
References LaneBitmask().
Member Data Documentation
FormatStr
const char* const llvm::LaneBitmask::FormatStr = "%016llX" static constexpr
Definition at line 44 of file LaneBitmask.h.
Referenced by llvm::PrintLaneMask().
The documentation for this struct was generated from the following file:
include/llvm/MC/LaneBitmask.h