LLVM: llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > > Struct Reference
llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > > Struct Reference
#include "llvm/IR/ModuleSummaryIndexYAML.h"
Static Public Member Functions
static void inputOne (IO &io, StringRef Key, std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > &V)
static void output (IO &io, std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > &V)
Detailed Description
Definition at line 66 of file ModuleSummaryIndexYAML.h.
Member Function Documentation
inputOne()
void llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >::inputOne (IO & io, StringRef Key, std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > & V) inline static
Definition at line 68 of file ModuleSummaryIndexYAML.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::yaml::IO::mapRequired(), P, and llvm::yaml::IO::setError().
output()
void llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >::output (IO & io, std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > & V) inline static
Definition at line 84 of file ModuleSummaryIndexYAML.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::yaml::IO::mapRequired(), P, and llvm::utostr().
The documentation for this struct was generated from the following file:
include/llvm/IR/ModuleSummaryIndexYAML.h