LLVM: llvm::SystemZRegisterInfo Struct Reference
llvm::SystemZRegisterInfo Struct Reference
#include "Target/SystemZ/SystemZRegisterInfo.h"
Public Member Functions
SystemZRegisterInfo (unsigned int RA, unsigned int HwMode)
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
getPointerRegClass - Return the register class to use to hold pointers.
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const override
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
bool getRegAllocationHints (Register VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > &Hints, const MachineFunction &MF, const VirtRegMap *VRM, const LiveRegMatrix *Matrix) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
const uint32_t * getNoPreservedMask () const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const override
bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC, LiveIntervals &LIS) const override
SrcRC and DstRC will be morphed into NewRC if this returns true.
Register getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 130 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
SystemZRegisterInfo()
SystemZRegisterInfo::SystemZRegisterInfo (unsigned int RA, unsigned int HwMode)
Definition at line 235 of file SystemZRegisterInfo.cpp.
References RA.
Member Function Documentation
eliminateFrameIndex()
bool SystemZRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const override
Definition at line 289 of file SystemZRegisterInfo.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::DIExpression::appendOffset(), llvm::DIExpression::appendOpsToArg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), DL, llvm::StackOffset::getFixed(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZII::HasIndex, llvm::RegState::Kill, MBB, MI, llvm::Offset, OpIdx, and TII.
getCalleeSavedRegs()
const MCPhysReg * SystemZRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 240 of file SystemZRegisterInfo.cpp.
References llvm::SystemZCallingConventionRegisters::getCalleeSavedRegs(), llvm::SystemZSubtarget::getSpecialRegisters(), and llvm::MachineFunction::getSubtarget().
getCallPreservedMask()
const uint32_t * SystemZRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 249 of file SystemZRegisterInfo.cpp.
References llvm::SystemZCallingConventionRegisters::getCallPreservedMask(), llvm::SystemZSubtarget::getSpecialRegisters(), and llvm::MachineFunction::getSubtarget().
getCrossCopyRegClass()
const TargetRegisterClass * SystemZRegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const override
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
Returns NULL if it is possible to copy between a two registers of the specified class.
Definition at line 446 of file SystemZRegisterInfo.cpp.
getFrameRegister()
Register SystemZRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 436 of file SystemZRegisterInfo.cpp.
References llvm::SystemZSubtarget::getSpecialRegisters(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
getNoPreservedMask()
const uint32_t * SystemZRegisterInfo::getNoPreservedMask () const override
Definition at line 257 of file SystemZRegisterInfo.cpp.
getPointerRegClass()
const TargetRegisterClass * llvm::SystemZRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const inline override
getPointerRegClass - Return the register class to use to hold pointers.
This is currently only used by LOAD_STACK_GUARD, which requires a non-r0 register, hence ADDR64.
Definition at line 138 of file SystemZRegisterInfo.h.
getRegAllocationHints()
bool SystemZRegisterInfo::getRegAllocationHints (Register VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > & Hints, const MachineFunction & MF, const VirtRegMap * VRM, const LiveRegMatrix * Matrix) const override
Definition at line 73 of file SystemZRegisterInfo.cpp.
References addHints(), llvm::SmallSet< T, N, C >::count(), DefMI, llvm::VirtRegMap::getPhys(), getRC32(), llvm::MachineOperand::getReg(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::MachineFunction::getRegInfo(), llvm::SystemZSubtarget::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::SystemZ::getTwoOperandOpcode(), llvm::SmallSet< T, N, C >::insert(), llvm::is_contained(), llvm::Register::isPhysical(), Matrix, MRI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Register, llvm::SmallVectorTemplateCommon< T, typename >::size(), and TRI.
getReservedRegs()
BitVector SystemZRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 262 of file SystemZRegisterInfo.cpp.
References llvm::SystemZSubtarget::getSpecialRegisters(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::MCRegAliasIterator::isValid(), and llvm::Reserved.
requiresFrameIndexScavenging()
bool llvm::SystemZRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Definition at line 158 of file SystemZRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::SystemZRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Definition at line 155 of file SystemZRegisterInfo.h.
shouldCoalesce()
bool SystemZRegisterInfo::shouldCoalesce (MachineInstr * MI, const TargetRegisterClass * SrcRC, unsigned SubReg, const TargetRegisterClass * DstRC, unsigned DstSubReg, const TargetRegisterClass * NewRC, LiveIntervals & LIS) const override
SrcRC and DstRC will be morphed into NewRC if this returns true.
Definition at line 383 of file SystemZRegisterInfo.cpp.
References assert(), llvm::LiveRange::beginIndex(), llvm::TargetRegisterClass::contains(), llvm::BitVector::count(), llvm::LiveRange::endIndex(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getInterval(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::TargetRegisterClass::getNumRegs(), llvm::MachineInstr::getParent(), llvm::TargetRegisterClass::hasSuperClassEq(), MBB, MI, llvm::BitVector::set(), and SubReg.
The documentation for this struct was generated from the following files:
lib/Target/SystemZ/SystemZRegisterInfo.h
lib/Target/SystemZ/SystemZRegisterInfo.cpp