LLVM: llvm::CRCTable Struct Reference
llvm::CRCTable Struct Reference
A custom std::array with 256 entries, that also has a print function.
#include "llvm/Analysis/HashRecognize.h"
Public Member Functions
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
A custom std::array with 256 entries, that also has a print function.
Definition at line 36 of file HashRecognize.h.
Member Function Documentation
dump()
void CRCTable::dump () const
Definition at line 654 of file HashRecognize.cpp.
References llvm::dbgs(), and print().
print()
void CRCTable::print (raw_ostream & OS) const
Definition at line 646 of file HashRecognize.cpp.
References I.
Referenced by dump(), and llvm::HashRecognize::print().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/HashRecognize.h
lib/Analysis/HashRecognize.cpp