LLVM: llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false > Struct Template Reference
llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false > Struct Template Reference
#include "llvm/Object/ELFTypes.h"
Public Member Functions
uint32_t getRInfo (bool isMips64EL) const
void setRInfo (uint32_t R, bool IsMips64EL)
uint32_t getSymbol (bool isMips64EL) const
unsigned char getType (bool isMips64EL) const
void setSymbol (uint32_t s, bool IsMips64EL)
void setType (unsigned char t, bool IsMips64EL)
void setSymbolAndType (uint32_t s, unsigned char t, bool IsMips64EL)
Public Attributes
Elf_Addr r_offset
Elf_Word r_info
Static Public Attributes
static const bool HasAddend = false
static const bool IsCrel = false
Detailed Description
template<endianness Endianness>
struct llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >
Definition at line 389 of file ELFTypes.h.
Member Function Documentation
getRInfo()
template<endianness Endianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::getRInfo (bool isMips64EL) const inline
Definition at line 396 of file ELFTypes.h.
References assert(), getRInfo(), isMips64EL(), and r_info.
Referenced by getRInfo(), getSymbol(), and getType().
getSymbol()
template<endianness Endianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::getSymbol (bool isMips64EL) const inline
Definition at line 407 of file ELFTypes.h.
References getRInfo(), and isMips64EL().
Referenced by setType().
getType()
template<endianness Endianness> unsigned char llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::getType (bool isMips64EL) const inline
Definition at line 410 of file ELFTypes.h.
References getRInfo(), and isMips64EL().
setRInfo()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::setRInfo (uint32_t R, bool IsMips64EL) inline
Definition at line 400 of file ELFTypes.h.
References assert(), and r_info.
Referenced by setSymbolAndType().
setSymbol()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::setSymbol (uint32_t s, bool IsMips64EL) inline
Definition at line 413 of file ELFTypes.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::setSymbolAndType (uint32_t s, unsigned char t, bool IsMips64EL) inline
Definition at line 419 of file ELFTypes.h.
References setRInfo().
Referenced by setSymbol(), and setType().
setType()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::setType (unsigned char t, bool IsMips64EL) inline
Definition at line 416 of file ELFTypes.h.
References getSymbol(), and setSymbolAndType().
Member Data Documentation
HasAddend
template<endianness Endianness> const bool llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::HasAddend = false static
Definition at line 391 of file ELFTypes.h.
IsCrel
template<endianness Endianness> const bool llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::IsCrel = false static
Definition at line 392 of file ELFTypes.h.
r_info
template<endianness Endianness> Elf_Word llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::r_info
Definition at line 394 of file ELFTypes.h.
Referenced by getRInfo(), and setRInfo().
r_offset
template<endianness Endianness> Elf_Addr llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::r_offset
Definition at line 393 of file ELFTypes.h.
The documentation for this struct was generated from the following file:
include/llvm/Object/ELFTypes.h