LLVM: llvm::User::value_op_iterator Struct Reference
llvm::User::value_op_iterator Struct Reference
Iterator for directly iterating over the operand Values.
#include "llvm/IR/User.h"
Public Member Functions
value_op_iterator (Use *U=nullptr)
Value * operator* () const
Value * operator-> () const
Public Member Functions inherited from llvm::iterator_adaptor_base< value_op_iterator, op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >
value_op_iterator & operator+= (difference_type n)
value_op_iterator & operator-= (difference_type n)
difference_type operator- (const value_op_iterator &RHS) const
value_op_iterator & operator++ ()
value_op_iterator & operator-- ()
Value * operator* () const
Public Member Functions inherited from llvm::iterator_facade_base< value_op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >
value_op_iterator operator+ (ptrdiff_t n) const
value_op_iterator operator- (ptrdiff_t n) const
value_op_iterator & operator++ ()
value_op_iterator & operator-- ()
bool operator!= (const value_op_iterator &RHS) const
bool operator> (const value_op_iterator &RHS) const
bool operator<= (const value_op_iterator &RHS) const
bool operator>= (const value_op_iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_adaptor_base< value_op_iterator, op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >
using difference_type
Public Types inherited from llvm::iterator_facade_base< value_op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Protected Types inherited from llvm::iterator_facade_base< value_op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >
enum
Protected Member Functions inherited from llvm::iterator_adaptor_base< value_op_iterator, op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >
iterator_adaptor_base ()=default
const op_iterator & wrapped () const
Protected Attributes inherited from llvm::iterator_adaptor_base< value_op_iterator, op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >
op_iterator I
Detailed Description
Iterator for directly iterating over the operand Values.
Definition at line 300 of file User.h.
Constructor & Destructor Documentation
value_op_iterator()
llvm::User::value_op_iterator::value_op_iterator (Use * U = nullptr) inline explicit
Definition at line 304 of file User.h.
References llvm::iterator_adaptor_base< value_op_iterator, op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >::iterator_adaptor_base().
Member Function Documentation
operator*()
Value * llvm::User::value_op_iterator::operator* () const inline
Definition at line 306 of file User.h.
References llvm::iterator_adaptor_base< value_op_iterator, op_iterator, std::random_access_iterator_tag, Value *, ptrdiff_t, Value *, Value * >::I, and llvm::Value::Value().
Referenced by operator->().
operator->()
Value * llvm::User::value_op_iterator::operator-> () const inline
Definition at line 307 of file User.h.
References operator*(), and llvm::Value::Value().
The documentation for this struct was generated from the following file:
include/llvm/IR/User.h