LLVM: llvm::gsym::CallSiteInfoCollection Struct Reference
llvm::gsym::CallSiteInfoCollection Struct Reference
#include "llvm/DebugInfo/GSYM/CallSiteInfo.h"
Public Member Functions
LLVM_ABI llvm::Error encode (FileWriter &O) const
Encode this CallSiteInfoCollection object into a FileWriter stream.
Static Public Member Functions
static LLVM_ABI llvm::Expected< CallSiteInfoCollection > decode (DataExtractor &Data)
Decode a CallSiteInfoCollection object from a binary data stream.
Public Attributes
std::vector< CallSiteInfo > CallSites
Detailed Description
Definition at line 77 of file CallSiteInfo.h.
Member Function Documentation
decode()
Expected< CallSiteInfoCollection > CallSiteInfoCollection::decode (DataExtractor & Data) static
Decode a CallSiteInfoCollection object from a binary data stream.
Parameters
Data The binary stream to read the data from.
Returns
A CallSiteInfoCollection or an error describing the issue.
Definition at line 80 of file CallSiteInfo.cpp.
References CallSites, llvm::createStringError(), llvm::Data, llvm::gsym::CallSiteInfo::decode(), llvm::Offset, and llvm::Expected< T >::takeError().
Referenced by llvm::gsym::FunctionInfo::decode(), and llvm::gsym::FunctionInfo::lookup().
encode()
Error CallSiteInfoCollection::encode (FileWriter & O) const
Encode this CallSiteInfoCollection object into a FileWriter stream.
Parameters
O The binary stream to write the data to.
Returns
An error object that indicates success or failure.
Definition at line 70 of file CallSiteInfo.cpp.
References CallSites, and llvm::Error::success().
Member Data Documentation
CallSites
std::vector<CallSiteInfo> llvm::gsym::CallSiteInfoCollection::CallSites
Definition at line 78 of file CallSiteInfo.h.
Referenced by decode(), llvm::gsym::GsymReader::dump(), encode(), and llvm::gsym::operator<<().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/GSYM/CallSiteInfo.h
lib/DebugInfo/GSYM/CallSiteInfo.cpp