LLVM: llvm::SysAlias Struct Reference
llvm::SysAlias Struct Reference
#include "Target/AArch64/Utils/AArch64BaseInfo.h"
Public Member Functions
constexpr SysAlias (const char *N, uint16_t E)
constexpr SysAlias (const char *N, uint16_t E, FeatureBitset F)
bool haveFeatures (FeatureBitset ActiveFeatures) const
FeatureBitset getRequiredFeatures () const
Public Attributes
const char * Name
uint16_t Encoding
FeatureBitset FeaturesRequired
Detailed Description
Definition at line 387 of file AArch64BaseInfo.h.
Constructor & Destructor Documentation
SysAlias() [1/2]
llvm::SysAlias::SysAlias (const char * N, uint16_t E) inline constexpr
Definition at line 392 of file AArch64BaseInfo.h.
References E(), Encoding, N, and Name.
Referenced by llvm::SysAliasImm::SysAliasImm(), llvm::SysAliasImm::SysAliasImm(), llvm::SysAliasReg::SysAliasReg(), and llvm::SysAliasReg::SysAliasReg().
SysAlias() [2/2]
llvm::SysAlias::SysAlias (const char * N, uint16_t E, FeatureBitset F) inline constexpr
Definition at line 393 of file AArch64BaseInfo.h.
References E(), Encoding, F, FeaturesRequired, N, and Name.
Member Function Documentation
getRequiredFeatures()
FeatureBitset llvm::SysAlias::getRequiredFeatures () const inline
Definition at line 401 of file AArch64BaseInfo.h.
References FeaturesRequired.
haveFeatures()
bool llvm::SysAlias::haveFeatures (FeatureBitset ActiveFeatures) const inline
Definition at line 396 of file AArch64BaseInfo.h.
References FeaturesRequired.
Referenced by llvm::AArch64InstPrinter::printSysAlias(), and llvm::AArch64InstPrinter::printSyspAlias().
Member Data Documentation
Encoding
uint16_t llvm::SysAlias::Encoding
Definition at line 389 of file AArch64BaseInfo.h.
Referenced by SysAlias(), and SysAlias().
FeaturesRequired
FeatureBitset llvm::SysAlias::FeaturesRequired
Definition at line 390 of file AArch64BaseInfo.h.
Referenced by getRequiredFeatures(), haveFeatures(), and SysAlias().
Name
const char* llvm::SysAlias::Name
Definition at line 388 of file AArch64BaseInfo.h.
Referenced by llvm::AArch64InstPrinter::printSysAlias(), llvm::AArch64InstPrinter::printSyspAlias(), SysAlias(), and SysAlias().
The documentation for this struct was generated from the following file:
lib/Target/AArch64/Utils/AArch64BaseInfo.h