LLVM: llvm::ms_demangle::PointerTypeNode Struct Reference
llvm::ms_demangle::PointerTypeNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
PointerTypeNode ()
void outputPre (OutputBuffer &OB, OutputFlags Flags) const override
void outputPost (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::TypeNode
TypeNode (NodeKind K)
void output (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Static Public Member Functions inherited from llvm::ms_demangle::TypeNode
static bool classof (const Node *N)
Public Attributes
PointerAffinity Affinity = PointerAffinity::None
QualifiedNameNode * ClassParent = nullptr
PointerAuthQualifierNode * PointerAuthQualifier = nullptr
TypeNode * Pointee = nullptr
Public Attributes inherited from llvm::ms_demangle::TypeNode
Qualifiers Quals = Q_None
Detailed Description
Definition at line 531 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
PointerTypeNode()
llvm::ms_demangle::PointerTypeNode::PointerTypeNode () inline
Definition at line 532 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::PointerType, and llvm::ms_demangle::TypeNode::TypeNode().
Member Function Documentation
classof()
bool llvm::ms_demangle::PointerTypeNode::classof (const Node * N) inline static
Definition at line 536 of file MicrosoftDemangleNodes.h.
References N, and llvm::ms_demangle::PointerType.
outputPost()
void PointerTypeNode::outputPost (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::TypeNode.
Definition at line 529 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::ArrayType, llvm::ms_demangle::FunctionSignature, and Pointee.
outputPre()
void PointerTypeNode::outputPre (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::TypeNode.
Definition at line 480 of file MicrosoftDemangleNodes.cpp.
References Affinity, llvm::ms_demangle::ArrayType, assert(), llvm::ms_demangle::FunctionSignatureNode::CallConvention, ClassParent, llvm::ms_demangle::FunctionSignature, llvm::ms_demangle::OF_NoCallingConvention, outputCallingConvention(), llvm::ms_demangle::FunctionSignatureNode::outputPre(), outputQualifiers(), outputSpaceIfNecessary(), Pointee, llvm::ms_demangle::Pointer, PointerAuthQualifier, llvm::ms_demangle::Q_Unaligned, llvm::ms_demangle::TypeNode::Quals, llvm::ms_demangle::Reference, and llvm::ms_demangle::RValueReference.
Member Data Documentation
Affinity
PointerAffinity llvm::ms_demangle::PointerTypeNode::Affinity = PointerAffinity::None
Definition at line 541 of file MicrosoftDemangleNodes.h.
Referenced by outputPre().
ClassParent
QualifiedNameNode* llvm::ms_demangle::PointerTypeNode::ClassParent = nullptr
Definition at line 544 of file MicrosoftDemangleNodes.h.
Referenced by outputPre().
Pointee
TypeNode* llvm::ms_demangle::PointerTypeNode::Pointee = nullptr
Definition at line 550 of file MicrosoftDemangleNodes.h.
Referenced by outputPost(), and outputPre().
PointerAuthQualifier
PointerAuthQualifierNode* llvm::ms_demangle::PointerTypeNode::PointerAuthQualifier = nullptr
Definition at line 546 of file MicrosoftDemangleNodes.h.
Referenced by outputPre().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp