LLVM: llvm::SizeOffsetValue Struct Reference
llvm::SizeOffsetValue Struct Reference
#include "llvm/Analysis/MemoryBuiltins.h"
Public Member Functions
SizeOffsetValue ()
SizeOffsetValue (Value *Size, Value *Offset)
LLVM_ABI SizeOffsetValue (const SizeOffsetWeakTrackingVH &SOT)
Public Member Functions inherited from llvm::SizeOffsetType< Value *, SizeOffsetValue >
SizeOffsetType ()=default
bool knownSize () const
bool knownOffset () const
bool anyKnown () const
bool bothKnown () const
bool operator== (const SizeOffsetType< Value *, SizeOffsetValue > &RHS) const
bool operator!= (const SizeOffsetType< Value *, SizeOffsetValue > &RHS) const
Static Public Member Functions
static bool known (Value *V)
Additional Inherited Members
Public Attributes inherited from llvm::SizeOffsetType< Value *, SizeOffsetValue >
Value * Size
Value * Offset
Detailed Description
Definition at line 314 of file MemoryBuiltins.h.
Constructor & Destructor Documentation
SizeOffsetValue() [1/3]
llvm::SizeOffsetValue::SizeOffsetValue () inline
Definition at line 315 of file MemoryBuiltins.h.
References llvm::SizeOffsetType< Value *, SizeOffsetValue >::SizeOffsetType().
SizeOffsetValue() [2/3]
llvm::SizeOffsetValue::SizeOffsetValue (Value * Size, Value * Offset) inline
Definition at line 316 of file MemoryBuiltins.h.
References llvm::SizeOffsetType< Value *, SizeOffsetValue >::Offset, llvm::SizeOffsetType< Value *, SizeOffsetValue >::Size, and llvm::SizeOffsetType< Value *, SizeOffsetValue >::SizeOffsetType().
SizeOffsetValue() [3/3]
SizeOffsetValue::SizeOffsetValue (const SizeOffsetWeakTrackingVH & SOT)
Definition at line 1177 of file MemoryBuiltins.cpp.
References llvm::SizeOffsetType< Value *, SizeOffsetValue >::Offset, llvm::SizeOffsetType< Value *, SizeOffsetValue >::Size, and llvm::SizeOffsetType< Value *, SizeOffsetValue >::SizeOffsetType().
Member Function Documentation
known()
bool llvm::SizeOffsetValue::known (Value * V) inline static
Definition at line 319 of file MemoryBuiltins.h.
The documentation for this struct was generated from the following files:
include/llvm/Analysis/MemoryBuiltins.h
lib/Analysis/MemoryBuiltins.cpp