LLVM: llvm::GraphTraits< CallGraphDOTInfo * > Struct Reference
llvm::GraphTraits< CallGraphDOTInfo * > Struct Reference
Public Types
typedef std::pair< const Function *const, std::unique_ptr< CallGraphNode > > PairTy
typedef mapped_iterator< CallGraph::const_iterator, decltype(&CGGetValuePtr)> nodes_iterator
using NodeRef
Public Types inherited from llvm::GraphTraits< const CallGraphNode * >
using NodeRef = const CallGraphNode *
using CGNPairTy = CallGraphNode::CallRecord
using EdgeRef = const CallGraphNode::CallRecord &
using ChildIteratorType
using ChildEdgeIteratorType = CallGraphNode::const_iterator
Static Public Member Functions
static NodeRef getEntryNode (CallGraphDOTInfo *CGInfo)
static const CallGraphNode * CGGetValuePtr (const PairTy &P)
static nodes_iterator nodes_begin (CallGraphDOTInfo *CGInfo)
static nodes_iterator nodes_end (CallGraphDOTInfo *CGInfo)
Static Public Member Functions inherited from llvm::GraphTraits< const CallGraphNode * >
static NodeRef getEntryNode (const CallGraphNode *CGN)
static const CallGraphNode * CGNGetValue (CGNPairTy P)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
static NodeRef edge_dest (EdgeRef E)
Detailed Description
Definition at line 117 of file CallPrinter.cpp.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< CallGraphDOTInfo * >::NodeRef
Definition at line 95 of file GraphTraits.h.
nodes_iterator
typedef mapped_iterator<CallGraph::const_iterator, decltype(&CGGetValuePtr)> llvm::GraphTraits< CallGraphDOTInfo * >::nodes_iterator
Definition at line 132 of file CallPrinter.cpp.
PairTy
typedef std::pair<const Function *const, std::unique_ptr<CallGraphNode> > llvm::GraphTraits< CallGraphDOTInfo * >::PairTy
Definition at line 125 of file CallPrinter.cpp.
Member Function Documentation
CGGetValuePtr()
const CallGraphNode * llvm::GraphTraits< CallGraphDOTInfo * >::CGGetValuePtr (const PairTy & P) inline static
Definition at line 126 of file CallPrinter.cpp.
References P.
Referenced by nodes_begin(), and nodes_end().
getEntryNode()
NodeRef llvm::GraphTraits< CallGraphDOTInfo * >::getEntryNode (CallGraphDOTInfo * CGInfo) inline static
Definition at line 119 of file CallPrinter.cpp.
References llvm::CallGraphDOTInfo::getCallGraph(), and llvm::CallGraph::getExternalCallingNode().
nodes_begin()
nodes_iterator llvm::GraphTraits< CallGraphDOTInfo * >::nodes_begin (CallGraphDOTInfo * CGInfo) inline static
Definition at line 134 of file CallPrinter.cpp.
References llvm::CallGraph::begin(), CGGetValuePtr(), and llvm::CallGraphDOTInfo::getCallGraph().
nodes_end()
nodes_iterator llvm::GraphTraits< CallGraphDOTInfo * >::nodes_end (CallGraphDOTInfo * CGInfo) inline static
Definition at line 137 of file CallPrinter.cpp.
References CGGetValuePtr(), llvm::CallGraph::end(), and llvm::CallGraphDOTInfo::getCallGraph().
The documentation for this struct was generated from the following file:
lib/Analysis/CallPrinter.cpp