LLVM: llvm::VPIRPhi Struct Reference
llvm::VPIRPhi Struct Reference
An overlay for VPIRInstructions wrapping PHI nodes enabling convenient use cast/dyn_cast/isa and execute() implementation.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPIRPhi (PHINode &PN)
PHINode & getIRPhi ()
void execute (VPTransformState &State) override
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
Public Member Functions inherited from llvm::VPIRInstruction
~VPIRInstruction () override=default
VPIRInstruction * clone () override
Clone the current recipe.
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Return the cost of this VPIRInstruction.
Instruction & getInstruction () const
bool usesScalars (const VPValue *Op) const override
Returns true if the VPUser uses scalars of operand Op.
bool onlyFirstPartUsed (const VPValue *Op) const override
Returns true if the VPUser only uses the first part of operand Op.
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the VPUser only uses the first lane of operand Op.
void extractLastLaneOfFirstOperand (VPBuilder &Builder)
Update the recipes first operand to the last lane of the operand using Builder.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
bool isScalarCast () const
Return true if the recipe is a scalar cast.
void setDebugLoc (DebugLoc NewDL)
Set the recipe's debug location to NewDL.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
Public Member Functions inherited from llvm::VPPhiAccessors
virtual ~VPPhiAccessors ()=default
VPValue * getIncomingValue (unsigned Idx) const
Returns the incoming VPValue with index Idx.
const VPBasicBlock * getIncomingBlock (unsigned Idx) const
Returns the incoming block with index Idx.
virtual unsigned getNumIncoming () const
Returns the number of incoming values, also number of incoming blocks.
void removeIncomingValueFor (VPBlockBase *IncomingBlock) const
Removes the incoming value for IncomingBlock, which must be a predecessor.
void printPhiOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the recipe.
Static Public Member Functions
static bool classof (const VPRecipeBase *U)
Static Public Member Functions inherited from llvm::VPIRInstruction
static VPIRInstruction * create (Instruction &I)
Create a new VPIRPhi for \I , if it is a PHINode, otherwise create a VPIRInstruction.
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Member Functions
const VPRecipeBase * getAsRecipe () const override
Return a VPRecipeBase* to the current object.
Protected Member Functions inherited from llvm::VPIRInstruction
VPIRInstruction (Instruction &I)
VPIRInstruction::create() should be used to create VPIRInstructions, as subclasses may need to be created, e.g.
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Detailed Description
An overlay for VPIRInstructions wrapping PHI nodes enabling convenient use cast/dyn_cast/isa and execute() implementation.
A single VPValue operand is allowed, and it is used to add a new incoming value for the single predecessor VPBB.
Definition at line 1328 of file VPlan.h.
Constructor & Destructor Documentation
VPIRPhi()
llvm::VPIRPhi::VPIRPhi (PHINode & PN) inline
Definition at line 1329 of file VPlan.h.
References llvm::VPIRInstruction::VPIRInstruction().
Member Function Documentation
classof()
bool llvm::VPIRPhi::classof (const VPRecipeBase * U) inline static
Definition at line 1331 of file VPlan.h.
References llvm::dyn_cast(), and llvm::isa().
execute()
void VPIRPhi::execute (VPTransformState & State) override virtual
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
Reimplemented from llvm::VPIRInstruction.
Definition at line 1330 of file VPlanRecipes.cpp.
References llvm::enumerate(), llvm::VPLane::getFirstLane(), llvm::BasicBlock::getFirstNonPHIIt(), getIRPhi(), llvm::VPLane::getLastLaneForVF(), llvm::VPRecipeBase::getParent(), llvm::VPBlockBase::getPredecessors(), llvm::vputils::isSingleScalar(), and llvm::VPUser::operands().
getAsRecipe()
const VPRecipeBase * llvm::VPIRPhi::getAsRecipe () const inline override protected virtual
Return a VPRecipeBase* to the current object.
Implements llvm::VPPhiAccessors.
Definition at line 1347 of file VPlan.h.
getIRPhi()
PHINode & llvm::VPIRPhi::getIRPhi () inline
Definition at line 1336 of file VPlan.h.
References llvm::cast(), and llvm::VPIRInstruction::getInstruction().
Referenced by execute().
print()
void VPIRPhi::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Reimplemented from llvm::VPIRInstruction.
Definition at line 1380 of file VPlanRecipes.cpp.
References llvm::enumerate(), llvm::VPUser::getNumOperands(), llvm::VPRecipeBase::getParent(), llvm::VPBlockBase::getPredecessors(), llvm::interleaveComma(), llvm::VPUser::operands(), and llvm::VPIRInstruction::print().
The documentation for this struct was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp