LLVM: llvm::codegen::RegisterCodeGenFlags Struct Reference
llvm::codegen::RegisterCodeGenFlags Struct Reference
Create this object with static storage to register codegen-related command line options.
#include "llvm/CodeGen/CommandFlags.h"
Public Member Functions
LLVM_ABI RegisterCodeGenFlags ()
Detailed Description
Create this object with static storage to register codegen-related command line options.
Definition at line 161 of file CommandFlags.h.
Constructor & Destructor Documentation
RegisterCodeGenFlags()
codegen::RegisterCodeGenFlags::RegisterCodeGenFlags ()
Definition at line 115 of file CommandFlags.cpp.
References llvm::All, llvm::Always, llvm::ARM, llvm::AssemblyFile, CGBINDOPT, clEnumValN, llvm::cl::CommaSeparated, llvm::DBX, llvm::Default, llvm::FloatABI::Default, llvm::DeploymentBased, llvm::DwarfCFI, llvm::DenormalMode::Dynamic, llvm::Reloc::DynamicNoPIC, llvm::EABI4, llvm::EABI5, EnableMachineFunctionSplitter, llvm::FPOpFusion::Fast, llvm::GDB, llvm::GNU, llvm::FloatABI::Hard, llvm::cl::Hidden, llvm::DenormalMode::IEEE, llvm::cl::init(), llvm::DenormalMode::Invalid, llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm::LLDB, llvm::CodeModel::Medium, llvm::Never, llvm::None, llvm::NonLeaf, llvm::Null, llvm::ObjectFile, llvm::Reloc::PIC_, llvm::DenormalMode::PositiveZero, llvm::ThreadModel::POSIX, llvm::DenormalMode::PreserveSign, RegisterCodeGenFlags(), llvm::Reserved, llvm::Reloc::ROPI, llvm::Reloc::ROPI_RWPI, llvm::Reloc::RWPI, llvm::SCE, llvm::ThreadModel::Single, llvm::SjLj, llvm::CodeModel::Small, llvm::FloatABI::Soft, llvm::FPOpFusion::Standard, llvm::Reloc::Static, llvm::FPOpFusion::Strict, llvm::CodeModel::Tiny, llvm::cl::values(), llvm::Wasm, and llvm::WinEH.
Referenced by RegisterCodeGenFlags().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/CommandFlags.h
lib/CodeGen/CommandFlags.cpp