LLVM: llvm::ConstantPtrAuthKeyType Struct Reference
llvm::ConstantPtrAuthKeyType Struct Reference
#include "IR/ConstantsContext.h"
Public Types
using TypeClass = typename ConstantInfo<ConstantPtrAuth>::TypeClass
Public Member Functions
ConstantPtrAuthKeyType (ArrayRef< Constant * > Operands)
ConstantPtrAuthKeyType (ArrayRef< Constant * > Operands, const ConstantPtrAuth *)
ConstantPtrAuthKeyType (const ConstantPtrAuth *C, SmallVectorImpl< Constant * > &Storage)
bool operator== (const ConstantPtrAuthKeyType &X) const
bool operator== (const ConstantPtrAuth *C) const
unsigned getHash () const
ConstantPtrAuth * create (TypeClass *Ty) const
Public Attributes
ArrayRef< Constant * > Operands
Detailed Description
Definition at line 507 of file ConstantsContext.h.
Member Typedef Documentation
TypeClass
using llvm::ConstantPtrAuthKeyType::TypeClass = typename ConstantInfo<ConstantPtrAuth>::TypeClass
Definition at line 538 of file ConstantsContext.h.
Constructor & Destructor Documentation
ConstantPtrAuthKeyType() [1/3]
llvm::ConstantPtrAuthKeyType::ConstantPtrAuthKeyType (ArrayRef< Constant * > Operands) inline
Definition at line 510 of file ConstantsContext.h.
References Operands.
Referenced by operator==().
ConstantPtrAuthKeyType() [2/3]
llvm::ConstantPtrAuthKeyType::ConstantPtrAuthKeyType (ArrayRef< Constant * > Operands, const ConstantPtrAuth *) inline
Definition at line 512 of file ConstantsContext.h.
References Operands.
ConstantPtrAuthKeyType() [3/3]
llvm::ConstantPtrAuthKeyType::ConstantPtrAuthKeyType (const ConstantPtrAuth * C, SmallVectorImpl< Constant * > & Storage) inline
Definition at line 515 of file ConstantsContext.h.
References assert(), llvm::CallingConv::C, llvm::cast(), E(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), I, Operands, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Member Function Documentation
create()
ConstantPtrAuth * llvm::ConstantPtrAuthKeyType::create (TypeClass * Ty) const inline
Definition at line 540 of file ConstantsContext.h.
References llvm::cast(), and Operands.
getHash()
unsigned llvm::ConstantPtrAuthKeyType::getHash () const inline
Definition at line 536 of file ConstantsContext.h.
References llvm::hash_combine_range(), and Operands.
operator==() [1/2]
bool llvm::ConstantPtrAuthKeyType::operator== (const ConstantPtrAuth * C) const inline
Definition at line 527 of file ConstantsContext.h.
References llvm::CallingConv::C, E(), I, and Operands.
operator==() [2/2]
bool llvm::ConstantPtrAuthKeyType::operator== (const ConstantPtrAuthKeyType & X) const inline
Definition at line 523 of file ConstantsContext.h.
References ConstantPtrAuthKeyType(), Operands, and X.
Member Data Documentation
Operands
ArrayRef<Constant *> llvm::ConstantPtrAuthKeyType::Operands
Definition at line 508 of file ConstantsContext.h.
Referenced by ConstantPtrAuthKeyType(), ConstantPtrAuthKeyType(), ConstantPtrAuthKeyType(), create(), getHash(), operator==(), and operator==().
The documentation for this struct was generated from the following file:
lib/IR/ConstantsContext.h