LLVM: llvm::memprof::LinearCallStackIdConverter Struct Reference
llvm::memprof::LinearCallStackIdConverter Struct Reference
#include "llvm/ProfileData/MemProfRadixTree.h"
Public Member Functions
LinearCallStackIdConverter ()=delete
LinearCallStackIdConverter (const unsigned char *CallStackBase, llvm::function_ref< Frame(LinearFrameId)> FrameIdToFrame)
std::vector< Frame > operator() (LinearCallStackId LinearCSId)
Public Attributes
const unsigned char * CallStackBase
llvm::function_ref< Frame(LinearFrameId)> FrameIdToFrame
Detailed Description
Definition at line 110 of file MemProfRadixTree.h.
Constructor & Destructor Documentation
LinearCallStackIdConverter() [1/2]
llvm::memprof::LinearCallStackIdConverter::LinearCallStackIdConverter () delete
LinearCallStackIdConverter() [2/2]
llvm::memprof::LinearCallStackIdConverter::LinearCallStackIdConverter (const unsigned char * CallStackBase, llvm::function_ref< Frame(LinearFrameId)> FrameIdToFrame) inline
Definition at line 115 of file MemProfRadixTree.h.
References CallStackBase, and FrameIdToFrame.
Member Function Documentation
operator()()
std::vector< Frame > llvm::memprof::LinearCallStackIdConverter::operator() (LinearCallStackId LinearCSId) inline
Definition at line 120 of file MemProfRadixTree.h.
References assert(), CallStackBase, FrameIdToFrame, Ptr, llvm::support::endian::read(), and llvm::support::endian::readNext().
Member Data Documentation
CallStackBase
const unsigned char* llvm::memprof::LinearCallStackIdConverter::CallStackBase
Definition at line 111 of file MemProfRadixTree.h.
Referenced by LinearCallStackIdConverter(), and operator()().
FrameIdToFrame
llvm::function_ref<Frame(LinearFrameId)> llvm::memprof::LinearCallStackIdConverter::FrameIdToFrame
Definition at line 112 of file MemProfRadixTree.h.
Referenced by LinearCallStackIdConverter(), and operator()().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProfRadixTree.h