LLVM: llvm::sframe::FuncDescEntry< E > Struct Template Reference
llvm::sframe::FuncDescEntry< E > Struct Template Reference
#include "llvm/BinaryFormat/SFrame.h"
Public Member Functions
uint8_t getPAuthKey () const
FDEType getFDEType () const
FREType getFREType () const
void setPAuthKey (uint8_t P)
void setFDEType (FDEType D)
void setFREType (FREType R)
void setFuncInfo (uint8_t PAuthKey, FDEType FDE, FREType FRE)
Public Attributes
detail::packed< int32_t, E > StartAddress
detail::packed< uint32_t, E > Size
detail::packed< uint32_t, E > StartFREOff
detail::packed< uint32_t, E > NumFREs
detail::packed< uint8_t, E > Info
detail::packed< uint8_t, E > RepSize
detail::packed< uint16_t, E > Padding2
Detailed Description
template<endianness E>
struct llvm::sframe::FuncDescEntry< E >
Definition at line 105 of file SFrame.h.
Member Function Documentation
getFDEType()
template<endianness E> FDEType llvm::sframe::FuncDescEntry< E >::getFDEType () const inline
Definition at line 115 of file SFrame.h.
References Info.
Referenced by setFREType(), and setPAuthKey().
getFREType()
template<endianness E> FREType llvm::sframe::FuncDescEntry< E >::getFREType () const inline
Definition at line 116 of file SFrame.h.
References Info.
Referenced by setFDEType(), and setPAuthKey().
getPAuthKey()
template<endianness E> uint8_t llvm::sframe::FuncDescEntry< E >::getPAuthKey () const inline
Definition at line 114 of file SFrame.h.
References Info.
Referenced by setFDEType(), and setFREType().
setFDEType()
template<endianness E> void llvm::sframe::FuncDescEntry< E >::setFDEType (FDEType D) inline
Definition at line 118 of file SFrame.h.
References D(), getFREType(), getPAuthKey(), and setFuncInfo().
setFREType()
template<endianness E> void llvm::sframe::FuncDescEntry< E >::setFREType (FREType R) inline
Definition at line 119 of file SFrame.h.
References getFDEType(), getPAuthKey(), and setFuncInfo().
setFuncInfo()
template<endianness E> void llvm::sframe::FuncDescEntry< E >::setFuncInfo (uint8_t PAuthKey, FDEType FDE, FREType FRE) inline
Definition at line 120 of file SFrame.h.
References Info.
Referenced by setFDEType(), setFREType(), and setPAuthKey().
setPAuthKey()
template<endianness E> void llvm::sframe::FuncDescEntry< E >::setPAuthKey (uint8_t P) inline
Definition at line 117 of file SFrame.h.
References getFDEType(), getFREType(), P, and setFuncInfo().
Member Data Documentation
Info
template<endianness E> detail::packed<uint8_t, E> llvm::sframe::FuncDescEntry< E >::Info
Definition at line 110 of file SFrame.h.
Referenced by getFDEType(), getFREType(), getPAuthKey(), and setFuncInfo().
NumFREs
template<endianness E> detail::packed<uint32_t, E> llvm::sframe::FuncDescEntry< E >::NumFREs
Definition at line 109 of file SFrame.h.
Padding2
template<endianness E> detail::packed<uint16_t, E> llvm::sframe::FuncDescEntry< E >::Padding2
Definition at line 112 of file SFrame.h.
RepSize
template<endianness E> detail::packed<uint8_t, E> llvm::sframe::FuncDescEntry< E >::RepSize
Definition at line 111 of file SFrame.h.
Size
template<endianness E> detail::packed<uint32_t, E> llvm::sframe::FuncDescEntry< E >::Size
Definition at line 107 of file SFrame.h.
StartAddress
template<endianness E> detail::packed<int32_t, E> llvm::sframe::FuncDescEntry< E >::StartAddress
Definition at line 106 of file SFrame.h.
StartFREOff
template<endianness E> detail::packed<uint32_t, E> llvm::sframe::FuncDescEntry< E >::StartFREOff
Definition at line 108 of file SFrame.h.
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/SFrame.h