LLVM: llvm::detail::PunnedPointer< Ptr > Struct Template Reference
llvm::detail::PunnedPointer< Ptr > Struct Template Reference
#include "llvm/ADT/PointerIntPair.h"
Public Member Functions
constexpr PunnedPointer (intptr_t i=0)
constexpr intptr_t asInt () const
constexpr operator intptr_t () const
constexpr PunnedPointer & operator= (intptr_t V)
Ptr * getPointerAddress ()
const Ptr * getPointerAddress () const
Detailed Description
template<typename Ptr>
struct llvm::detail::PunnedPointer< Ptr >
Definition at line 28 of file PointerIntPair.h.
Constructor & Destructor Documentation
PunnedPointer()
template<typename Ptr> llvm::detail::PunnedPointer< Ptr >::PunnedPointer (intptr_t i = 0) inline explicit constexpr
Definition at line 37 of file PointerIntPair.h.
Referenced by operator=().
Member Function Documentation
asInt()
template<typename Ptr> intptr_t llvm::detail::PunnedPointer< Ptr >::asInt () const inline constexpr
Definition at line 39 of file PointerIntPair.h.
Referenced by operator intptr_t().
getPointerAddress() [1/2]
template<typename Ptr> Ptr * llvm::detail::PunnedPointer< Ptr >::getPointerAddress () inline
Definition at line 52 of file PointerIntPair.h.
References Ptr.
getPointerAddress() [2/2]
template<typename Ptr> const Ptr * llvm::detail::PunnedPointer< Ptr >::getPointerAddress () const inline
Definition at line 53 of file PointerIntPair.h.
References Ptr.
operator intptr_t()
template<typename Ptr> llvm::detail::PunnedPointer< Ptr >::operator intptr_t () const inline constexpr
Definition at line 45 of file PointerIntPair.h.
References asInt().
operator=()
template<typename Ptr> PunnedPointer & llvm::detail::PunnedPointer< Ptr >::operator= (intptr_t V) inline constexpr
Definition at line 47 of file PointerIntPair.h.
References PunnedPointer().
The documentation for this struct was generated from the following file:
include/llvm/ADT/PointerIntPair.h