LLVM: llvm::ms_demangle::SymbolNode Struct Reference
llvm::ms_demangle::SymbolNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
SymbolNode (NodeKind K)
void output (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Public Attributes
QualifiedNameNode * Name = nullptr
Detailed Description
Definition at line 687 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
SymbolNode()
llvm::ms_demangle::SymbolNode::SymbolNode (NodeKind K) inline explicit
Definition at line 688 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::Node::Node().
Referenced by llvm::ms_demangle::EncodedStringLiteralNode::EncodedStringLiteralNode(), llvm::ms_demangle::FunctionSymbolNode::FunctionSymbolNode(), llvm::ms_demangle::LocalStaticGuardVariableNode::LocalStaticGuardVariableNode(), llvm::ms_demangle::SpecialTableSymbolNode::SpecialTableSymbolNode(), and llvm::ms_demangle::VariableSymbolNode::VariableSymbolNode().
Member Function Documentation
classof()
bool llvm::ms_demangle::SymbolNode::classof (const Node * N) inline static
Definition at line 691 of file MicrosoftDemangleNodes.h.
References N, llvm::ms_demangle::Node::Node(), llvm::ms_demangle::SymbolEnd, and llvm::ms_demangle::SymbolStart.
output()
void SymbolNode::output (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::Node.
Reimplemented in llvm::ms_demangle::VariableSymbolNode.
Definition at line 586 of file MicrosoftDemangleNodes.cpp.
References Name.
Referenced by llvm::microsoftDemangle().
Member Data Documentation
Name
QualifiedNameNode* llvm::ms_demangle::SymbolNode::Name = nullptr
Definition at line 696 of file MicrosoftDemangleNodes.h.
Referenced by llvm::ms_demangle::FunctionSymbolNode::output(), llvm::ms_demangle::LocalStaticGuardVariableNode::output(), llvm::ms_demangle::SpecialTableSymbolNode::output(), output(), llvm::ms_demangle::VariableSymbolNode::output(), and synthesizeVariable().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp