LLVM: llvm::format_provider< T, std::enable_if_t< support::detail::use_integral_formatter< T >::value > > Struct Template Reference
llvm::format_provider< T, std::enable_if_t< support::detail::use_integral_formatter< T >::value > > Struct Template Reference
Implementation of format_provider<T> for integral arithmetic types.
#include "llvm/Support/FormatProviders.h"
Static Public Member Functions
static void format (const T &V, llvm::raw_ostream &Stream, StringRef Style)
Additional Inherited Members
Static Protected Member Functions inherited from llvm::support::detail::HelperFunctions
static std::optional< size_t > parseNumericPrecision (StringRef Str)
static std::optional< HexPrintStyle > consumeHexStyle (StringRef &Str)
static size_t consumeNumHexDigits (StringRef &Str, HexPrintStyle Style, size_t Default)
Detailed Description
template<typename T>
struct llvm::format_provider< T, std::enable_if_t< support::detail::use_integral_formatter< T >::value > >
Implementation of format_provider<T> for integral arithmetic types.
The options string of an integral type has the grammar:
integer_options :: [style][digits] style :: digits :: <non-negative integer> 0-99
| style | Meaning | Example | Digits Meaning |
| | | Input | Output | |
| x- | Hex no prefix, lower | 42 | 2a | Minimum # digits | | X- | Hex no prefix, upper | 42 | 2A | Minimum # digits | | x+ / x | Hex + prefix, lower | 42 | 0x2a | Minimum # digits | | X+ / X | Hex + prefix, upper | 42 | 0x2A | Minimum # digits | | N / n | Digit grouped number | 123456 | 123,456 | Ignored | | D / d | Integer | 100000 | 100000 | Ignored |
| (empty) | Same as D / d | | | |
Definition at line 129 of file FormatProviders.h.
Member Function Documentation
format()
template<typename T> void llvm::format_provider< T, std::enable_if_t< support::detail::use_integral_formatter< T >::value > >::format (const T & V, llvm::raw_ostream & Stream, StringRef Style) inline static
Definition at line 134 of file FormatProviders.h.
References assert(), llvm::support::detail::HelperFunctions::consumeHexStyle(), llvm::support::detail::HelperFunctions::consumeNumHexDigits(), llvm::Integer, llvm::Number, T, llvm::write_hex(), and llvm::write_integer().
The documentation for this struct was generated from the following file:
include/llvm/Support/FormatProviders.h