LLVM: llvm::remarks::MetaSerializer Struct Reference
llvm::remarks::MetaSerializer Struct Reference abstract
This is the base class for a remark metadata serializer.
#include "llvm/Remarks/RemarkSerializer.h"
Public Member Functions
MetaSerializer (raw_ostream &OS)
virtual ~MetaSerializer ()=default
This is just an interface.
virtual void emit ()=0
Public Attributes
raw_ostream & OS
The open raw_ostream that the metadata is emitted to.
Detailed Description
This is the base class for a remark metadata serializer.
Definition at line 69 of file RemarkSerializer.h.
Constructor & Destructor Documentation
MetaSerializer()
llvm::remarks::MetaSerializer::MetaSerializer (raw_ostream & OS) inline
Definition at line 73 of file RemarkSerializer.h.
References OS.
Referenced by llvm::remarks::BitstreamMetaSerializer::BitstreamMetaSerializer(), llvm::remarks::BitstreamMetaSerializer::BitstreamMetaSerializer(), and llvm::remarks::YAMLMetaSerializer::YAMLMetaSerializer().
~MetaSerializer()
virtual llvm::remarks::MetaSerializer::~MetaSerializer () virtual default
This is just an interface.
Member Function Documentation
emit()
virtual void llvm::remarks::MetaSerializer::emit () pure virtual
Implemented in llvm::remarks::BitstreamMetaSerializer, and llvm::remarks::YAMLMetaSerializer.
Referenced by llvm::remarks::BitstreamRemarkSerializer::emit().
Member Data Documentation
OS
raw_ostream& llvm::remarks::MetaSerializer::OS
The open raw_ostream that the metadata is emitted to.
Definition at line 71 of file RemarkSerializer.h.
Referenced by llvm::remarks::BitstreamMetaSerializer::BitstreamMetaSerializer(), llvm::remarks::BitstreamMetaSerializer::BitstreamMetaSerializer(), llvm::remarks::BitstreamMetaSerializer::emit(), llvm::remarks::YAMLMetaSerializer::emit(), MetaSerializer(), and llvm::remarks::YAMLMetaSerializer::YAMLMetaSerializer().
The documentation for this struct was generated from the following file:
include/llvm/Remarks/RemarkSerializer.h