LLVM: llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags > Struct Template Reference
llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
BinaryOp_match (const LHS_P &LHS, const RHS_P &RHS)
template<typename OpTy>
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
LHS_P L
RHS_P R
Detailed Description
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false, unsigned Flags = MachineInstr::NoFlags>
struct llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags >
Definition at line 448 of file MIPatternMatch.h.
Constructor & Destructor Documentation
BinaryOp_match()
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false, unsigned Flags = MachineInstr::NoFlags> llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags >::BinaryOp_match (const LHS_P & LHS, const RHS_P & RHS) inline
Definition at line 452 of file MIPatternMatch.h.
References L, LHS, R, and RHS.
Member Function Documentation
match()
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false, unsigned Flags = MachineInstr::NoFlags> template<typename OpTy> bool llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 454 of file MIPatternMatch.h.
References llvm::MachineInstr::getFlags(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), L, llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::mi_match(), MRI, and R.
Member Data Documentation
L
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false, unsigned Flags = MachineInstr::NoFlags> LHS_P llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags >::L
Definition at line 449 of file MIPatternMatch.h.
Referenced by BinaryOp_match(), and match().
R
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false, unsigned Flags = MachineInstr::NoFlags> RHS_P llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable, Flags >::R
Definition at line 450 of file MIPatternMatch.h.
Referenced by BinaryOp_match(), and match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h