LLVM: llvm::ms_demangle::StructorIdentifierNode Struct Reference
llvm::ms_demangle::StructorIdentifierNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
StructorIdentifierNode ()
StructorIdentifierNode (bool IsDestructor)
void output (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::IdentifierNode
IdentifierNode (NodeKind K)
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Static Public Member Functions inherited from llvm::ms_demangle::IdentifierNode
static bool classof (const Node *N)
Public Attributes
IdentifierNode * Class = nullptr
bool IsDestructor = false
Public Attributes inherited from llvm::ms_demangle::IdentifierNode
NodeArrayNode * TemplateParams = nullptr
Additional Inherited Members
Protected Member Functions inherited from llvm::ms_demangle::IdentifierNode
void outputTemplateParameters (OutputBuffer &OB, OutputFlags Flags) const
Detailed Description
Definition at line 494 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
StructorIdentifierNode() [1/2]
llvm::ms_demangle::StructorIdentifierNode::StructorIdentifierNode () inline
Definition at line 495 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::IdentifierNode::IdentifierNode(), and llvm::ms_demangle::StructorIdentifier.
StructorIdentifierNode() [2/2]
llvm::ms_demangle::StructorIdentifierNode::StructorIdentifierNode (bool IsDestructor) inline explicit
Definition at line 496 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::IdentifierNode::IdentifierNode(), IsDestructor, and llvm::ms_demangle::StructorIdentifier.
Member Function Documentation
classof()
bool llvm::ms_demangle::StructorIdentifierNode::classof (const Node * N) inline static
Definition at line 502 of file MicrosoftDemangleNodes.h.
References N, and llvm::ms_demangle::StructorIdentifier.
output()
void StructorIdentifierNode::output (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::Node.
Definition at line 374 of file MicrosoftDemangleNodes.cpp.
References Class, IsDestructor, and llvm::ms_demangle::IdentifierNode::outputTemplateParameters().
Member Data Documentation
Class
IdentifierNode* llvm::ms_demangle::StructorIdentifierNode::Class = nullptr
Definition at line 507 of file MicrosoftDemangleNodes.h.
Referenced by output().
IsDestructor
bool llvm::ms_demangle::StructorIdentifierNode::IsDestructor = false
Definition at line 508 of file MicrosoftDemangleNodes.h.
Referenced by output(), and StructorIdentifierNode().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp