LLVM: llvm::mcdxbc::RootParametersContainer Struct Reference
llvm::mcdxbc::RootParametersContainer Struct Reference
#include "llvm/MC/DXContainerRootSignature.h"
Public Member Functions
void addInfo (dxbc::RTS0::v1::RootParameterHeader Header, size_t Location)
void addParameter (dxbc::RTS0::v1::RootParameterHeader Header, dxbc::RTS0::v1::RootConstants Constant)
void addInvalidParameter (dxbc::RTS0::v1::RootParameterHeader Header)
void addParameter (dxbc::RTS0::v1::RootParameterHeader Header, dxbc::RTS0::v2::RootDescriptor Descriptor)
void addParameter (dxbc::RTS0::v1::RootParameterHeader Header, DescriptorTable Table)
std::pair< uint32_t, uint32_t > getTypeAndLocForParameter (uint32_t Location) const
const dxbc::RTS0::v1::RootParameterHeader & getHeader (size_t Location) const
const dxbc::RTS0::v1::RootConstants & getConstant (size_t Index) const
const dxbc::RTS0::v2::RootDescriptor & getRootDescriptor (size_t Index) const
const DescriptorTable & getDescriptorTable (size_t Index) const
size_t size () const
SmallVector< RootParameterInfo >::const_iterator begin () const
SmallVector< RootParameterInfo >::const_iterator end () const
Public Attributes
SmallVector< RootParameterInfo > ParametersInfo
SmallVector< dxbc::RTS0::v1::RootConstants > Constants
SmallVector< dxbc::RTS0::v2::RootDescriptor > Descriptors
SmallVector< DescriptorTable > Tables
Detailed Description
Definition at line 38 of file DXContainerRootSignature.h.
Member Function Documentation
addInfo()
void llvm::mcdxbc::RootParametersContainer::addInfo (dxbc::RTS0::v1::RootParameterHeader Header, size_t Location) inline
Definition at line 45 of file DXContainerRootSignature.h.
References ParametersInfo.
Referenced by addInvalidParameter(), addParameter(), addParameter(), and addParameter().
addInvalidParameter()
void llvm::mcdxbc::RootParametersContainer::addInvalidParameter (dxbc::RTS0::v1::RootParameterHeader Header) inline
Definition at line 55 of file DXContainerRootSignature.h.
References addInfo().
addParameter() [1/3]
void llvm::mcdxbc::RootParametersContainer::addParameter (dxbc::RTS0::v1::RootParameterHeader Header, DescriptorTable Table) inline
Definition at line 65 of file DXContainerRootSignature.h.
References addInfo(), and Tables.
addParameter() [2/3]
void llvm::mcdxbc::RootParametersContainer::addParameter (dxbc::RTS0::v1::RootParameterHeader Header, dxbc::RTS0::v1::RootConstants Constant) inline
Definition at line 49 of file DXContainerRootSignature.h.
References addInfo(), and Constants.
Referenced by parseDescriptorTable(), parseRootConstants(), and parseRootDescriptors().
addParameter() [3/3]
void llvm::mcdxbc::RootParametersContainer::addParameter (dxbc::RTS0::v1::RootParameterHeader Header, dxbc::RTS0::v2::RootDescriptor Descriptor) inline
Definition at line 59 of file DXContainerRootSignature.h.
References addInfo(), and Descriptors.
begin()
SmallVector< RootParameterInfo >::const_iterator llvm::mcdxbc::RootParametersContainer::begin () const inline
Definition at line 96 of file DXContainerRootSignature.h.
References ParametersInfo.
end()
SmallVector< RootParameterInfo >::const_iterator llvm::mcdxbc::RootParametersContainer::end () const inline
Definition at line 99 of file DXContainerRootSignature.h.
References ParametersInfo.
getConstant()
const dxbc::RTS0::v1::RootConstants & llvm::mcdxbc::RootParametersContainer::getConstant (size_t Index) const inline
Definition at line 82 of file DXContainerRootSignature.h.
References Constants.
getDescriptorTable()
const DescriptorTable & llvm::mcdxbc::RootParametersContainer::getDescriptorTable (size_t Index) const inline
Definition at line 90 of file DXContainerRootSignature.h.
References Tables.
Referenced by validate().
getHeader()
const dxbc::RTS0::v1::RootParameterHeader & llvm::mcdxbc::RootParametersContainer::getHeader (size_t Location) const inline
Definition at line 77 of file DXContainerRootSignature.h.
References Info, and ParametersInfo.
getRootDescriptor()
const dxbc::RTS0::v2::RootDescriptor & llvm::mcdxbc::RootParametersContainer::getRootDescriptor (size_t Index) const inline
Definition at line 86 of file DXContainerRootSignature.h.
References Descriptors.
Referenced by validate().
getTypeAndLocForParameter()
std::pair< uint32_t, uint32_t > llvm::mcdxbc::RootParametersContainer::getTypeAndLocForParameter (uint32_t Location) const inline
Definition at line 72 of file DXContainerRootSignature.h.
References Info, and ParametersInfo.
size()
size_t llvm::mcdxbc::RootParametersContainer::size () const inline
Definition at line 94 of file DXContainerRootSignature.h.
References ParametersInfo.
Member Data Documentation
Constants
SmallVector<dxbc::RTS0::v1::RootConstants> llvm::mcdxbc::RootParametersContainer::Constants
Definition at line 41 of file DXContainerRootSignature.h.
Referenced by addParameter(), and getConstant().
Descriptors
SmallVector<dxbc::RTS0::v2::RootDescriptor> llvm::mcdxbc::RootParametersContainer::Descriptors
Definition at line 42 of file DXContainerRootSignature.h.
Referenced by addParameter(), and getRootDescriptor().
ParametersInfo
SmallVector<RootParameterInfo> llvm::mcdxbc::RootParametersContainer::ParametersInfo
Definition at line 39 of file DXContainerRootSignature.h.
Referenced by addInfo(), begin(), end(), getHeader(), getTypeAndLocForParameter(), and size().
Tables
SmallVector<DescriptorTable> llvm::mcdxbc::RootParametersContainer::Tables
Definition at line 43 of file DXContainerRootSignature.h.
Referenced by addParameter(), and getDescriptorTable().
The documentation for this struct was generated from the following file:
include/llvm/MC/DXContainerRootSignature.h