LLVM: RemoveLoadsIntoFakeUses Struct Reference
RemoveLoadsIntoFakeUses Struct Reference
Public Member Functions
bool run (MachineFunction &MF)
Detailed Description
Definition at line 71 of file RemoveLoadsIntoFakeUses.cpp.
Member Function Documentation
run()
bool RemoveLoadsIntoFakeUses::run (MachineFunction & MF)
Definition at line 103 of file RemoveLoadsIntoFakeUses.cpp.
References llvm::LivePhysRegs::addLiveOuts(), llvm::LivePhysRegs::available(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorImpl< T >::erase(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::hasFakeUses(), llvm::LivePhysRegs::init(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), LLVM_DEBUG, llvm::make_early_inc_range(), MBB, MI, MRI, llvm::post_order(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), llvm::LivePhysRegs::stepBackward(), TII, TRI, and llvm::MachineFunction::useDebugInstrRef().
The documentation for this struct was generated from the following file:
lib/CodeGen/RemoveLoadsIntoFakeUses.cpp