LLVM: llvm::DXContainerYAML::RootParameterYamlDesc Struct Reference
llvm::DXContainerYAML::RootParameterYamlDesc Struct Reference
#include "llvm/ObjectYAML/DXContainerYAML.h"
Public Member Functions
template<typename T>
T & getOrInsertImpl (RootParameterLocationYaml &ParamDesc, SmallVectorImpl< T > &Container)
RootConstantsYaml & getOrInsertConstants (RootParameterLocationYaml &ParamDesc)
RootDescriptorYaml & getOrInsertDescriptor (RootParameterLocationYaml &ParamDesc)
DescriptorTableYaml & getOrInsertTable (RootParameterLocationYaml &ParamDesc)
void insertLocation (RootParameterLocationYaml &Location)
Public Attributes
SmallVector< RootParameterLocationYaml > Locations
SmallVector< RootConstantsYaml > Constants
SmallVector< RootDescriptorYaml > Descriptors
SmallVector< DescriptorTableYaml > Tables
Detailed Description
Definition at line 131 of file DXContainerYAML.h.
Member Function Documentation
getOrInsertConstants()
RootConstantsYaml & llvm::DXContainerYAML::RootParameterYamlDesc::getOrInsertConstants (RootParameterLocationYaml & ParamDesc) inline
Definition at line 149 of file DXContainerYAML.h.
References Constants, and getOrInsertImpl().
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingContextTraits< DXContainerYAML::RootParameterLocationYaml, DXContainerYAML::RootSignatureYamlDesc >::mapping().
getOrInsertDescriptor()
RootDescriptorYaml & llvm::DXContainerYAML::RootParameterYamlDesc::getOrInsertDescriptor (RootParameterLocationYaml & ParamDesc) inline
Definition at line 154 of file DXContainerYAML.h.
References Descriptors, and getOrInsertImpl().
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingContextTraits< DXContainerYAML::RootParameterLocationYaml, DXContainerYAML::RootSignatureYamlDesc >::mapping().
getOrInsertImpl()
template<typename T> T & llvm::DXContainerYAML::RootParameterYamlDesc::getOrInsertImpl (RootParameterLocationYaml & ParamDesc, SmallVectorImpl< T > & Container) inline
Definition at line 139 of file DXContainerYAML.h.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::DXContainerYAML::RootParameterLocationYaml::IndexInSignature, llvm::SmallVectorTemplateCommon< T, typename >::size(), and T.
Referenced by getOrInsertConstants(), getOrInsertDescriptor(), and getOrInsertTable().
getOrInsertTable()
DescriptorTableYaml & llvm::DXContainerYAML::RootParameterYamlDesc::getOrInsertTable (RootParameterLocationYaml & ParamDesc) inline
Definition at line 158 of file DXContainerYAML.h.
References getOrInsertImpl(), and Tables.
Referenced by llvm::yaml::MappingContextTraits< DXContainerYAML::RootParameterLocationYaml, DXContainerYAML::RootSignatureYamlDesc >::mapping(), and llvm::readDescriptorRanges().
insertLocation()
void llvm::DXContainerYAML::RootParameterYamlDesc::insertLocation (RootParameterLocationYaml & Location) inline
Definition at line 162 of file DXContainerYAML.h.
References Locations.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::readDescriptorRanges().
Member Data Documentation
Constants
SmallVector<RootConstantsYaml> llvm::DXContainerYAML::RootParameterYamlDesc::Constants
Definition at line 134 of file DXContainerYAML.h.
Referenced by getOrInsertConstants().
Descriptors
SmallVector<RootDescriptorYaml> llvm::DXContainerYAML::RootParameterYamlDesc::Descriptors
Definition at line 135 of file DXContainerYAML.h.
Referenced by getOrInsertDescriptor().
Locations
SmallVector<RootParameterLocationYaml> llvm::DXContainerYAML::RootParameterYamlDesc::Locations
Definition at line 132 of file DXContainerYAML.h.
Referenced by insertLocation(), and llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping().
Tables
SmallVector<DescriptorTableYaml> llvm::DXContainerYAML::RootParameterYamlDesc::Tables
Definition at line 136 of file DXContainerYAML.h.
Referenced by getOrInsertTable().
The documentation for this struct was generated from the following file:
include/llvm/ObjectYAML/DXContainerYAML.h