LLVM: llvm::TargetLowering::MakeLibCallOptions Struct Reference
llvm::TargetLowering::MakeLibCallOptions Struct Reference
This structure is used to pass arguments to makeLibCall function.
#include "llvm/CodeGen/TargetLowering.h"
Public Member Functions
MakeLibCallOptions ()
MakeLibCallOptions & setIsSigned (bool Value=true)
MakeLibCallOptions & setNoReturn (bool Value=true)
MakeLibCallOptions & setDiscardResult (bool Value=true)
MakeLibCallOptions & setIsPostTypeLegalization (bool Value=true)
MakeLibCallOptions & setTypeListBeforeSoften (ArrayRef< EVT > OpsVT, EVT RetVT, bool Value=true)
MakeLibCallOptions & setOpsTypeOverrides (ArrayRef< Type * > OpsTypes)
Override the argument type for an operand.
Public Attributes
ArrayRef< EVT > OpsVTBeforeSoften
EVT RetVTBeforeSoften
ArrayRef< Type * > OpsTypeOverrides
bool IsSigned: 1
bool DoesNotReturn: 1
bool IsReturnValueUsed: 1
bool IsPostTypeLegalization: 1
bool IsSoften: 1
Detailed Description
This structure is used to pass arguments to makeLibCall function.
Definition at line 4870 of file TargetLowering.h.
Constructor & Destructor Documentation
MakeLibCallOptions()
llvm::TargetLowering::MakeLibCallOptions::MakeLibCallOptions () inline
Definition at line 4883 of file TargetLowering.h.
References DoesNotReturn, IsPostTypeLegalization, IsReturnValueUsed, IsSigned, and IsSoften.
Referenced by setDiscardResult(), setIsPostTypeLegalization(), setIsSigned(), setNoReturn(), setOpsTypeOverrides(), and setTypeListBeforeSoften().
Member Function Documentation
setDiscardResult()
MakeLibCallOptions & llvm::TargetLowering::MakeLibCallOptions::setDiscardResult (bool Value = true) inline
Definition at line 4897 of file TargetLowering.h.
References IsReturnValueUsed, and MakeLibCallOptions().
Referenced by llvm::SelectionDAGBuilder::visitSPDescriptorFailure().
setIsPostTypeLegalization()
MakeLibCallOptions & llvm::TargetLowering::MakeLibCallOptions::setIsPostTypeLegalization (bool Value = true) inline
Definition at line 4902 of file TargetLowering.h.
References IsPostTypeLegalization, and MakeLibCallOptions().
Referenced by llvm::TargetLowering::forceExpandWideMUL().
setIsSigned()
MakeLibCallOptions & llvm::TargetLowering::MakeLibCallOptions::setIsSigned (bool Value = true) inline
Definition at line 4887 of file TargetLowering.h.
References IsSigned, and MakeLibCallOptions().
Referenced by llvm::TargetLowering::forceExpandWideMUL().
setNoReturn()
MakeLibCallOptions & llvm::TargetLowering::MakeLibCallOptions::setNoReturn (bool Value = true) inline
Definition at line 4892 of file TargetLowering.h.
References DoesNotReturn, and MakeLibCallOptions().
setOpsTypeOverrides()
MakeLibCallOptions & llvm::TargetLowering::MakeLibCallOptions::setOpsTypeOverrides (ArrayRef< Type * > OpsTypes) inline
Override the argument type for an operand.
Leave the type as null to use the type from the operand's node.
Definition at line 4917 of file TargetLowering.h.
References MakeLibCallOptions(), and OpsTypeOverrides.
setTypeListBeforeSoften()
MakeLibCallOptions & llvm::TargetLowering::MakeLibCallOptions::setTypeListBeforeSoften (ArrayRef< EVT > OpsVT, EVT RetVT, bool Value = true) inline
Definition at line 4907 of file TargetLowering.h.
References IsSoften, MakeLibCallOptions(), OpsVTBeforeSoften, and RetVTBeforeSoften.
Referenced by llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), and llvm::TargetLowering::softenSetCCOperands().
Member Data Documentation
DoesNotReturn
bool llvm::TargetLowering::MakeLibCallOptions::DoesNotReturn
Definition at line 4878 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), MakeLibCallOptions(), and setNoReturn().
IsPostTypeLegalization
bool llvm::TargetLowering::MakeLibCallOptions::IsPostTypeLegalization
Definition at line 4880 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), MakeLibCallOptions(), and setIsPostTypeLegalization().
IsReturnValueUsed
bool llvm::TargetLowering::MakeLibCallOptions::IsReturnValueUsed
Definition at line 4879 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), MakeLibCallOptions(), and setDiscardResult().
IsSigned
bool llvm::TargetLowering::MakeLibCallOptions::IsSigned
Definition at line 4877 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), MakeLibCallOptions(), and setIsSigned().
IsSoften
bool llvm::TargetLowering::MakeLibCallOptions::IsSoften
Definition at line 4881 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), MakeLibCallOptions(), and setTypeListBeforeSoften().
OpsTypeOverrides
ArrayRef<Type *> llvm::TargetLowering::MakeLibCallOptions::OpsTypeOverrides
Definition at line 4875 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), and setOpsTypeOverrides().
OpsVTBeforeSoften
ArrayRef<EVT> llvm::TargetLowering::MakeLibCallOptions::OpsVTBeforeSoften
Definition at line 4873 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), and setTypeListBeforeSoften().
RetVTBeforeSoften
EVT llvm::TargetLowering::MakeLibCallOptions::RetVTBeforeSoften
Definition at line 4874 of file TargetLowering.h.
Referenced by llvm::TargetLowering::makeLibCall(), and setTypeListBeforeSoften().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/TargetLowering.h