LLVM: llvm::object::DirectX::RootParameterView Struct Reference
llvm::object::DirectX::RootParameterView Struct Reference
#include "llvm/Object/DXContainer.h"
Public Member Functions
RootParameterView (const dxbc::RTS0::v1::RootParameterHeader &H, StringRef P)
template<typename T>
Expected< T > readParameter ()
Public Attributes
const dxbc::RTS0::v1::RootParameterHeader & Header
StringRef ParamData
Detailed Description
Definition at line 125 of file DXContainer.h.
Constructor & Destructor Documentation
RootParameterView()
llvm::object::DirectX::RootParameterView::RootParameterView (const dxbc::RTS0::v1::RootParameterHeader & H, StringRef P) inline
Definition at line 129 of file DXContainer.h.
References H, Header, P, and ParamData.
Referenced by llvm::object::DirectX::DescriptorTableView::classof(), llvm::object::DirectX::RootConstantView::classof(), and llvm::object::DirectX::RootDescriptorView::classof().
Member Function Documentation
readParameter()
template<typename T> Expected< T > llvm::object::DirectX::RootParameterView::readParameter () inline
Definition at line 132 of file DXContainer.h.
References llvm::sys::IsBigEndianHost, llvm::make_error(), ParamData, llvm::object::parse_failed, Struct, and T.
Referenced by llvm::object::DirectX::RootConstantView::read(), and llvm::object::DirectX::RootDescriptorView::read().
Member Data Documentation
Header
const dxbc::RTS0::v1::RootParameterHeader& llvm::object::DirectX::RootParameterView::Header
Definition at line 126 of file DXContainer.h.
Referenced by RootParameterView().
ParamData
StringRef llvm::object::DirectX::RootParameterView::ParamData
Definition at line 127 of file DXContainer.h.
Referenced by llvm::object::DirectX::DescriptorTableView::read(), readParameter(), and RootParameterView().
The documentation for this struct was generated from the following file:
include/llvm/Object/DXContainer.h