LLVM: llvm::DXContainerYAML::StaticSamplerYamlDesc Struct Reference
llvm::DXContainerYAML::StaticSamplerYamlDesc Struct Reference
#include "llvm/ObjectYAML/DXContainerYAML.h"
Public Attributes
uint32_t Filter = llvm::to_underlying(dxbc::SamplerFilter::Anisotropic)
uint32_t AddressU = llvm::to_underlying(dxbc::TextureAddressMode::Wrap)
uint32_t AddressV = llvm::to_underlying(dxbc::TextureAddressMode::Wrap)
uint32_t AddressW = llvm::to_underlying(dxbc::TextureAddressMode::Wrap)
float MipLODBias = 0.f
uint32_t MaxAnisotropy = 16u
uint32_t ComparisonFunc
uint32_t BorderColor
float MinLOD = 0.f
float MaxLOD = std::numeric_limits<float>::max()
uint32_t ShaderRegister
uint32_t RegisterSpace
uint32_t ShaderVisibility
Detailed Description
Definition at line 167 of file DXContainerYAML.h.
Member Data Documentation
AddressU
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::AddressU = llvm::to_underlying(dxbc::TextureAddressMode::Wrap)
Definition at line 169 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
AddressV
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::AddressV = llvm::to_underlying(dxbc::TextureAddressMode::Wrap)
Definition at line 170 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
AddressW
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::AddressW = llvm::to_underlying(dxbc::TextureAddressMode::Wrap)
Definition at line 171 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
BorderColor
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::BorderColor
Initial value:
=
      llvm::to_underlying(dxbc::StaticBorderColor::OpaqueWhite)
Definition at line 176 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
ComparisonFunc
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::ComparisonFunc
Initial value:
=
      llvm::to_underlying(dxbc::ComparisonFunc::LessEqual)
Definition at line 174 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
Filter
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::Filter = llvm::to_underlying(dxbc::SamplerFilter::Anisotropic)
Definition at line 168 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
MaxAnisotropy
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::MaxAnisotropy = 16u
Definition at line 173 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
MaxLOD
float llvm::DXContainerYAML::StaticSamplerYamlDesc::MaxLOD = std::numeric_limits<float>::max()
Definition at line 179 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
MinLOD
float llvm::DXContainerYAML::StaticSamplerYamlDesc::MinLOD = 0.f
Definition at line 178 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
MipLODBias
float llvm::DXContainerYAML::StaticSamplerYamlDesc::MipLODBias = 0.f
Definition at line 172 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
RegisterSpace
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::RegisterSpace
Definition at line 181 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
ShaderRegister
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::ShaderRegister
Definition at line 180 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
ShaderVisibility
uint32_t llvm::DXContainerYAML::StaticSamplerYamlDesc::ShaderVisibility
Definition at line 182 of file DXContainerYAML.h.
Referenced by llvm::DXContainerYAML::RootSignatureYamlDesc::create(), and llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping().
The documentation for this struct was generated from the following file:
include/llvm/ObjectYAML/DXContainerYAML.h