LLVM: llvm::SPIRV::ModuleAnalysisInfo Struct Reference
llvm::SPIRV::ModuleAnalysisInfo Struct Reference
#include "Target/SPIRV/SPIRVModuleAnalysis.h"
Public Member Functions
MCRegister getFuncReg (const Function *F)
MCRegister getExtInstSetReg (unsigned SetNum)
InstrList & getMSInstrs (unsigned MSType)
void setSkipEmission (const MachineInstr *MI)
bool getSkipEmission (const MachineInstr *MI)
void setRegisterAlias (const MachineFunction *MF, Register Reg, MCRegister AliasReg)
MCRegister getRegisterAlias (const MachineFunction *MF, Register Reg)
bool hasRegisterAlias (const MachineFunction *MF, Register Reg)
unsigned getNextID ()
MCRegister getNextIDRegister ()
bool hasMBBRegister (const MachineBasicBlock &MBB)
MCRegister getOrCreateMBBRegister (const MachineBasicBlock &MBB)
Public Attributes
RequirementHandler Reqs
MemoryModel::MemoryModel Mem
AddressingModel::AddressingModel Addr
SourceLanguage::SourceLanguage SrcLang
unsigned SrcLangVersion
StringSet SrcExt
DenseMap< unsigned, MCRegister > ExtInstSetMap
SmallVector< const MachineInstr *, 4 > GlobalVarList
DenseMap< const Function *, MCRegister > FuncMap
DenseSet< const MachineInstr * > InstrsToDelete
RegisterAliasMapTy RegisterAliasTable
unsigned MaxID
InstrList MS [NUM_MODULE_SECTIONS]
DenseMap< std::pair< const MachineFunction *, int >, MCRegister > BBNumToRegMap
Detailed Description
Definition at line 136 of file SPIRVModuleAnalysis.h.
Member Function Documentation
getExtInstSetReg()
MCRegister llvm::SPIRV::ModuleAnalysisInfo::getExtInstSetReg (unsigned SetNum) inline
Definition at line 169 of file SPIRVModuleAnalysis.h.
References ExtInstSetMap.
Referenced by llvm::SPIRVMCInstLower::lower().
getFuncReg()
MCRegister llvm::SPIRV::ModuleAnalysisInfo::getFuncReg (const Function * F) inline
Definition at line 163 of file SPIRVModuleAnalysis.h.
References assert(), F, and FuncMap.
Referenced by addOpsFromMDNode(), and llvm::SPIRVMCInstLower::lower().
getMSInstrs()
InstrList & llvm::SPIRV::ModuleAnalysisInfo::getMSInstrs (unsigned MSType) inline
Definition at line 170 of file SPIRVModuleAnalysis.h.
References MS.
getNextID()
unsigned llvm::SPIRV::ModuleAnalysisInfo::getNextID () inline
Definition at line 193 of file SPIRVModuleAnalysis.h.
References MaxID.
Referenced by getNextIDRegister().
getNextIDRegister()
MCRegister llvm::SPIRV::ModuleAnalysisInfo::getNextIDRegister () inline
Definition at line 194 of file SPIRVModuleAnalysis.h.
References getNextID().
Referenced by getOrCreateMBBRegister().
getOrCreateMBBRegister()
MCRegister llvm::SPIRV::ModuleAnalysisInfo::getOrCreateMBBRegister (const MachineBasicBlock & MBB) inline
Definition at line 202 of file SPIRVModuleAnalysis.h.
References BBNumToRegMap, getNextIDRegister(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and MBB.
Referenced by llvm::SPIRVMCInstLower::lower().
getRegisterAlias()
MCRegister llvm::SPIRV::ModuleAnalysisInfo::getRegisterAlias (const MachineFunction * MF, Register Reg) inline
Definition at line 179 of file SPIRVModuleAnalysis.h.
References Reg, and RegisterAliasTable.
Referenced by llvm::SPIRVMCInstLower::lower().
getSkipEmission()
bool llvm::SPIRV::ModuleAnalysisInfo::getSkipEmission (const MachineInstr * MI) inline
Definition at line 172 of file SPIRVModuleAnalysis.h.
References InstrsToDelete, and MI.
hasMBBRegister()
bool llvm::SPIRV::ModuleAnalysisInfo::hasMBBRegister (const MachineBasicBlock & MBB) inline
Definition at line 197 of file SPIRVModuleAnalysis.h.
References BBNumToRegMap, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and MBB.
hasRegisterAlias()
bool llvm::SPIRV::ModuleAnalysisInfo::hasRegisterAlias (const MachineFunction * MF, Register Reg) inline
Definition at line 187 of file SPIRVModuleAnalysis.h.
References Reg, and RegisterAliasTable.
setRegisterAlias()
void llvm::SPIRV::ModuleAnalysisInfo::setRegisterAlias (const MachineFunction * MF, Register Reg, MCRegister AliasReg) inline
Definition at line 175 of file SPIRVModuleAnalysis.h.
References Reg, and RegisterAliasTable.
setSkipEmission()
void llvm::SPIRV::ModuleAnalysisInfo::setSkipEmission (const MachineInstr * MI) inline
Definition at line 171 of file SPIRVModuleAnalysis.h.
References InstrsToDelete, and MI.
Member Data Documentation
Addr
AddressingModel::AddressingModel llvm::SPIRV::ModuleAnalysisInfo::Addr
Definition at line 139 of file SPIRVModuleAnalysis.h.
BBNumToRegMap
DenseMap<std::pair<const MachineFunction *, int>, MCRegister> llvm::SPIRV::ModuleAnalysisInfo::BBNumToRegMap
Definition at line 161 of file SPIRVModuleAnalysis.h.
Referenced by getOrCreateMBBRegister(), and hasMBBRegister().
ExtInstSetMap
DenseMap<unsigned, MCRegister> llvm::SPIRV::ModuleAnalysisInfo::ExtInstSetMap
Definition at line 144 of file SPIRVModuleAnalysis.h.
Referenced by getExtInstSetReg().
FuncMap
DenseMap<const Function *, MCRegister> llvm::SPIRV::ModuleAnalysisInfo::FuncMap
Definition at line 148 of file SPIRVModuleAnalysis.h.
Referenced by getFuncReg().
GlobalVarList
SmallVector<const MachineInstr *, 4> llvm::SPIRV::ModuleAnalysisInfo::GlobalVarList
Definition at line 146 of file SPIRVModuleAnalysis.h.
InstrsToDelete
DenseSet<const MachineInstr *> llvm::SPIRV::ModuleAnalysisInfo::InstrsToDelete
Definition at line 151 of file SPIRVModuleAnalysis.h.
Referenced by getSkipEmission(), and setSkipEmission().
MaxID
unsigned llvm::SPIRV::ModuleAnalysisInfo::MaxID
Definition at line 157 of file SPIRVModuleAnalysis.h.
Referenced by getNextID().
Mem
MemoryModel::MemoryModel llvm::SPIRV::ModuleAnalysisInfo::Mem
Definition at line 138 of file SPIRVModuleAnalysis.h.
MS
InstrList llvm::SPIRV::ModuleAnalysisInfo::MS[NUM_MODULE_SECTIONS]
Definition at line 159 of file SPIRVModuleAnalysis.h.
Referenced by getMSInstrs().
RegisterAliasTable
RegisterAliasMapTy llvm::SPIRV::ModuleAnalysisInfo::RegisterAliasTable
Definition at line 155 of file SPIRVModuleAnalysis.h.
Referenced by getRegisterAlias(), hasRegisterAlias(), and setRegisterAlias().
Reqs
RequirementHandler llvm::SPIRV::ModuleAnalysisInfo::Reqs
Definition at line 137 of file SPIRVModuleAnalysis.h.
SrcExt
StringSet llvm::SPIRV::ModuleAnalysisInfo::SrcExt
Definition at line 142 of file SPIRVModuleAnalysis.h.
SrcLang
SourceLanguage::SourceLanguage llvm::SPIRV::ModuleAnalysisInfo::SrcLang
Definition at line 140 of file SPIRVModuleAnalysis.h.
SrcLangVersion
unsigned llvm::SPIRV::ModuleAnalysisInfo::SrcLangVersion
Definition at line 141 of file SPIRVModuleAnalysis.h.
The documentation for this struct was generated from the following file:
lib/Target/SPIRV/SPIRVModuleAnalysis.h