LLVM: llvm::memprof::CallStackIdConverter< MapTy > Struct Template Reference
llvm::memprof::CallStackIdConverter< MapTy > Struct Template Reference
#include "llvm/ProfileData/MemProfRadixTree.h"
Public Member Functions
CallStackIdConverter ()=delete
CallStackIdConverter (MapTy &Map, llvm::function_ref< Frame(FrameId)> FrameIdToFrame)
CallStackIdConverter (const CallStackIdConverter &)=delete
CallStackIdConverter & operator= (const CallStackIdConverter &)=delete
std::vector< Frame > operator() (CallStackId CSId)
Public Attributes
std::optional< CallStackId > LastUnmappedId
MapTy & Map
llvm::function_ref< Frame(FrameId)> FrameIdToFrame
Detailed Description
template<typename MapTy>
struct llvm::memprof::CallStackIdConverter< MapTy >
Definition at line 61 of file MemProfRadixTree.h.
Constructor & Destructor Documentation
CallStackIdConverter() [1/3]
template<typename MapTy> llvm::memprof::CallStackIdConverter< MapTy >::CallStackIdConverter () delete
Referenced by CallStackIdConverter(), and operator=().
CallStackIdConverter() [2/3]
template<typename MapTy> llvm::memprof::CallStackIdConverter< MapTy >::CallStackIdConverter (MapTy & Map, llvm::function_ref< Frame(FrameId)> FrameIdToFrame) inline
Definition at line 67 of file MemProfRadixTree.h.
References FrameIdToFrame, and Map.
CallStackIdConverter() [3/3]
template<typename MapTy> llvm::memprof::CallStackIdConverter< MapTy >::CallStackIdConverter (const CallStackIdConverter< MapTy > &) delete
References CallStackIdConverter().
Member Function Documentation
operator()()
template<typename MapTy> std::vector< Frame > llvm::memprof::CallStackIdConverter< MapTy >::operator() (CallStackId CSId) inline
Definition at line 77 of file MemProfRadixTree.h.
References llvm::memprof::detail::DerefIterator(), FrameIdToFrame, LastUnmappedId, Map, and llvm::SmallVectorTemplateCommon< T, typename >::size().
operator=()
template<typename MapTy> CallStackIdConverter & llvm::memprof::CallStackIdConverter< MapTy >::operator= (const CallStackIdConverter< MapTy > &) delete
References CallStackIdConverter().
Member Data Documentation
FrameIdToFrame
template<typename MapTy> llvm::function_ref<Frame(FrameId)> llvm::memprof::CallStackIdConverter< MapTy >::FrameIdToFrame
Definition at line 64 of file MemProfRadixTree.h.
Referenced by CallStackIdConverter(), and operator()().
LastUnmappedId
template<typename MapTy> std::optional<CallStackId> llvm::memprof::CallStackIdConverter< MapTy >::LastUnmappedId
Definition at line 62 of file MemProfRadixTree.h.
Referenced by getMemProfRecordV2(), and operator()().
Map
template<typename MapTy> MapTy& llvm::memprof::CallStackIdConverter< MapTy >::Map
Definition at line 63 of file MemProfRadixTree.h.
Referenced by CallStackIdConverter(), and operator()().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProfRadixTree.h