LLVM: llvm::SelectionDAG::DAGNodeDeletedListener Struct Reference
llvm::SelectionDAG::DAGNodeDeletedListener Struct Reference
#include "llvm/CodeGen/SelectionDAG.h"
Public Member Functions
DAGNodeDeletedListener (SelectionDAG &DAG, std::function< void(SDNode *, SDNode *)> Callback)
void NodeDeleted (SDNode *N, SDNode *E) override
The node N that was deleted and, if E is not null, an equivalent node E that replaced it.
Public Member Functions inherited from llvm::SelectionDAG::DAGUpdateListener
DAGUpdateListener (SelectionDAG &D)
virtual ~DAGUpdateListener ()
virtual void NodeUpdated (SDNode *N)
The node N that was updated.
virtual void NodeInserted (SDNode *N)
The node N that was inserted.
Public Attributes
std::function< void(SDNode *, SDNode *)> Callback
Public Attributes inherited from llvm::SelectionDAG::DAGUpdateListener
DAGUpdateListener *const Next
SelectionDAG & DAG
Detailed Description
Definition at line 346 of file SelectionDAG.h.
Constructor & Destructor Documentation
DAGNodeDeletedListener()
llvm::SelectionDAG::DAGNodeDeletedListener::DAGNodeDeletedListener (SelectionDAG & DAG, std::function< void(SDNode *, SDNode *)> Callback) inline
Definition at line 349 of file SelectionDAG.h.
References Callback, llvm::SelectionDAG::DAGUpdateListener::DAG, llvm::SelectionDAG::DAGUpdateListener::DAGUpdateListener(), llvm::move(), and llvm::SelectionDAG::SelectionDAG().
Member Function Documentation
NodeDeleted()
void llvm::SelectionDAG::DAGNodeDeletedListener::NodeDeleted (SDNode * N, SDNode * E) inline override virtual
The node N that was deleted and, if E is not null, an equivalent node E that replaced it.
Reimplemented from llvm::SelectionDAG::DAGUpdateListener.
Definition at line 353 of file SelectionDAG.h.
References Callback, E(), and N.
Member Data Documentation
Callback
std::function<void(SDNode *, SDNode *)> llvm::SelectionDAG::DAGNodeDeletedListener::Callback
Definition at line 347 of file SelectionDAG.h.
Referenced by DAGNodeDeletedListener(), and NodeDeleted().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/SelectionDAG.h
lib/CodeGen/SelectionDAG/SelectionDAG.cpp