LLVM: llvm::DenseMapInfo< object::SectionRef > Struct Reference
llvm::DenseMapInfo< object::SectionRef > Struct Reference
#include "llvm/Object/ObjectFile.h"
Static Public Member Functions
static bool isEqual (const object::SectionRef &A, const object::SectionRef &B)
static object::SectionRef getEmptyKey ()
static object::SectionRef getTombstoneKey ()
static unsigned getHashValue (const object::SectionRef &Sec)
Detailed Description
Definition at line 647 of file ObjectFile.h.
Member Function Documentation
getEmptyKey()
object::SectionRef llvm::DenseMapInfo< object::SectionRef >::getEmptyKey () inline static
Definition at line 652 of file ObjectFile.h.
getHashValue()
unsigned llvm::DenseMapInfo< object::SectionRef >::getHashValue (const object::SectionRef & Sec) inline static
Definition at line 660 of file ObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::object::SectionRef::getRawDataRefImpl(), llvm::hash_combine(), and llvm::object::DataRefImpl::p.
getTombstoneKey()
object::SectionRef llvm::DenseMapInfo< object::SectionRef >::getTombstoneKey () inline static
Definition at line 655 of file ObjectFile.h.
References llvm::object::DataRefImpl::p.
isEqual()
bool llvm::DenseMapInfo< object::SectionRef >::isEqual (const object::SectionRef & A, const object::SectionRef & B) inline static
Definition at line 648 of file ObjectFile.h.
References A(), and B().
The documentation for this struct was generated from the following file:
include/llvm/Object/ObjectFile.h