LLVM: llvm::InstCombineOptions Struct Reference
llvm::InstCombineOptions Struct Reference
#include "llvm/Transforms/InstCombine/InstCombine.h"
Public Member Functions
InstCombineOptions ()=default
InstCombineOptions & setVerifyFixpoint (bool Value)
InstCombineOptions & setMaxIterations (unsigned Value)
Public Attributes
bool VerifyFixpoint = false
unsigned MaxIterations = InstCombineDefaultMaxIterations
Detailed Description
Definition at line 31 of file InstCombine.h.
Constructor & Destructor Documentation
InstCombineOptions()
llvm::InstCombineOptions::InstCombineOptions () default
Referenced by setMaxIterations(), and setVerifyFixpoint().
Member Function Documentation
setMaxIterations()
InstCombineOptions & llvm::InstCombineOptions::setMaxIterations (unsigned Value) inline
Definition at line 43 of file InstCombine.h.
References InstCombineOptions(), and MaxIterations.
setVerifyFixpoint()
InstCombineOptions & llvm::InstCombineOptions::setVerifyFixpoint (bool Value) inline
Definition at line 38 of file InstCombine.h.
References InstCombineOptions(), and VerifyFixpoint.
Member Data Documentation
MaxIterations
unsigned llvm::InstCombineOptions::MaxIterations = InstCombineDefaultMaxIterations
Definition at line 34 of file InstCombine.h.
Referenced by combineInstructionsOverFunction(), and setMaxIterations().
VerifyFixpoint
bool llvm::InstCombineOptions::VerifyFixpoint = false
Definition at line 33 of file InstCombine.h.
Referenced by combineInstructionsOverFunction(), and setVerifyFixpoint().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/InstCombine/InstCombine.h