LLVM: llvm::DenseMapInfo< APFloat > Struct Reference
llvm::DenseMapInfo< APFloat > Struct Reference
#include "IR/LLVMContextImpl.h"
Static Public Member Functions
static APFloat getEmptyKey ()
static APFloat getTombstoneKey ()
static unsigned getHashValue (const APFloat &Key)
static bool isEqual (const APFloat &LHS, const APFloat &RHS)
Detailed Description
Definition at line 78 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
APFloat llvm::DenseMapInfo< APFloat >::getEmptyKey () inline static
Definition at line 79 of file LLVMContextImpl.h.
References llvm::APFloatBase::Bogus().
getHashValue()
unsigned llvm::DenseMapInfo< APFloat >::getHashValue (const APFloat & Key) inline static
Definition at line 84 of file LLVMContextImpl.h.
References llvm::hash_value(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
getTombstoneKey()
APFloat llvm::DenseMapInfo< APFloat >::getTombstoneKey () inline static
Definition at line 80 of file LLVMContextImpl.h.
References llvm::APFloatBase::Bogus().
isEqual()
bool llvm::DenseMapInfo< APFloat >::isEqual (const APFloat & LHS, const APFloat & RHS) inline static
Definition at line 88 of file LLVMContextImpl.h.
References LHS, and RHS.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h