LLVM: llvm::CodeViewYAML::detail::UnknownSymbolRecord Struct Reference
llvm::CodeViewYAML::detail::UnknownSymbolRecord Struct Reference
Public Member Functions
UnknownSymbolRecord (codeview::SymbolKind K)
void map (yaml::IO &io) override
CVSymbol toCodeViewSymbol (BumpPtrAllocator &Allocator, CodeViewContainer Container) const override
Error fromCodeViewSymbol (CVSymbol CVS) override
Public Member Functions inherited from llvm::CodeViewYAML::detail::SymbolRecordBase
SymbolRecordBase (codeview::SymbolKind K)
virtual ~SymbolRecordBase ()=default
Public Attributes
std::vector< uint8_t > Data
Public Attributes inherited from llvm::CodeViewYAML::detail::SymbolRecordBase
codeview::SymbolKind Kind
Detailed Description
Definition at line 274 of file CodeViewYAMLSymbols.cpp.
Constructor & Destructor Documentation
UnknownSymbolRecord()
llvm::CodeViewYAML::detail::UnknownSymbolRecord::UnknownSymbolRecord (codeview::SymbolKind K) inline explicit
Definition at line 275 of file CodeViewYAMLSymbols.cpp.
References llvm::CodeViewYAML::detail::SymbolRecordBase::SymbolRecordBase().
Member Function Documentation
fromCodeViewSymbol()
Error llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol (CVSymbol CVS) inline override virtual
Implements llvm::CodeViewYAML::detail::SymbolRecordBase.
Definition at line 291 of file CodeViewYAMLSymbols.cpp.
References Data, llvm::ArrayRef< T >::drop_front(), llvm::CodeViewYAML::detail::SymbolRecordBase::Kind, llvm::codeview::CVRecord< Kind >::kind(), llvm::codeview::CVRecord< Kind >::RecordData, and llvm::Error::success().
map()
void llvm::CodeViewYAML::detail::UnknownSymbolRecord::map (yaml::IO & io) override virtual
Implements llvm::CodeViewYAML::detail::SymbolRecordBase.
Definition at line 302 of file CodeViewYAMLSymbols.cpp.
References Data, llvm::yaml::IO::mapRequired(), and llvm::yaml::IO::outputting().
toCodeViewSymbol()
CVSymbol llvm::CodeViewYAML::detail::UnknownSymbolRecord::toCodeViewSymbol (BumpPtrAllocator & Allocator, CodeViewContainer Container) const inline override virtual
Implements llvm::CodeViewYAML::detail::SymbolRecordBase.
Definition at line 279 of file CodeViewYAMLSymbols.cpp.
References Data, and llvm::CodeViewYAML::detail::SymbolRecordBase::Kind.
Member Data Documentation
Data
std::vector<uint8_t> llvm::CodeViewYAML::detail::UnknownSymbolRecord::Data
Definition at line 297 of file CodeViewYAMLSymbols.cpp.
Referenced by fromCodeViewSymbol(), map(), and toCodeViewSymbol().
The documentation for this struct was generated from the following file:
lib/ObjectYAML/CodeViewYAMLSymbols.cpp