LLVM: llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > > Struct Reference
llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > > Struct Reference
Public Types
using TOCKey = std::pair<const MCSymbol *, PPCMCExpr::Specifier>
Static Public Member Functions
static TOCKey getEmptyKey ()
static TOCKey getTombstoneKey ()
static unsigned getHashValue (const TOCKey &PairVal)
static bool isEqual (const TOCKey &A, const TOCKey &B)
Detailed Description
Definition at line 109 of file PPCAsmPrinter.cpp.
Member Typedef Documentation
TOCKey
using llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::TOCKey = std::pair<const MCSymbol *, PPCMCExpr::Specifier>
Definition at line 110 of file PPCAsmPrinter.cpp.
Member Function Documentation
getEmptyKey()
TOCKey llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::getEmptyKey () inline static
Definition at line 112 of file PPCAsmPrinter.cpp.
References llvm::PPC::S_None.
getHashValue()
unsigned llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::getHashValue (const TOCKey & PairVal) inline static
Definition at line 116 of file PPCAsmPrinter.cpp.
References llvm::detail::combineHashValue().
getTombstoneKey()
TOCKey llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::getTombstoneKey () inline static
Definition at line 113 of file PPCAsmPrinter.cpp.
References llvm::PPC::S_None.
isEqual()
bool llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::isEqual (const TOCKey & A, const TOCKey & B) inline static
Definition at line 121 of file PPCAsmPrinter.cpp.
References A(), and B().
The documentation for this struct was generated from the following file:
lib/Target/PowerPC/PPCAsmPrinter.cpp