LLVM: llvm::ms_demangle::IdentifierNode Struct Reference
llvm::ms_demangle::IdentifierNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
IdentifierNode (NodeKind K)
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
virtual void output (OutputBuffer &OB, OutputFlags Flags) const =0
std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Public Attributes
NodeArrayNode * TemplateParams = nullptr
Protected Member Functions
void outputTemplateParameters (OutputBuffer &OB, OutputFlags Flags) const
Detailed Description
Definition at line 386 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
IdentifierNode()
llvm::ms_demangle::IdentifierNode::IdentifierNode (NodeKind K) inline explicit
Definition at line 387 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::Node::Node().
Referenced by llvm::ms_demangle::ConversionOperatorIdentifierNode::ConversionOperatorIdentifierNode(), llvm::ms_demangle::DynamicStructorIdentifierNode::DynamicStructorIdentifierNode(), llvm::ms_demangle::IntrinsicFunctionIdentifierNode::IntrinsicFunctionIdentifierNode(), llvm::ms_demangle::LiteralOperatorIdentifierNode::LiteralOperatorIdentifierNode(), llvm::ms_demangle::LocalStaticGuardIdentifierNode::LocalStaticGuardIdentifierNode(), llvm::ms_demangle::NamedIdentifierNode::NamedIdentifierNode(), llvm::ms_demangle::RttiBaseClassDescriptorNode::RttiBaseClassDescriptorNode(), llvm::ms_demangle::StructorIdentifierNode::StructorIdentifierNode(), llvm::ms_demangle::StructorIdentifierNode::StructorIdentifierNode(), and llvm::ms_demangle::VcallThunkIdentifierNode::VcallThunkIdentifierNode().
Member Function Documentation
classof()
bool llvm::ms_demangle::IdentifierNode::classof (const Node * N) inline static
Definition at line 389 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::IdentifierEnd, llvm::ms_demangle::IdentifierStart, N, and llvm::ms_demangle::Node::Node().
outputTemplateParameters()
void IdentifierNode::outputTemplateParameters (OutputBuffer & OB, OutputFlags Flags) const protected
Definition at line 223 of file MicrosoftDemangleNodes.cpp.
References TemplateParams.
Referenced by llvm::ms_demangle::ConversionOperatorIdentifierNode::output(), llvm::ms_demangle::IntrinsicFunctionIdentifierNode::output(), llvm::ms_demangle::LiteralOperatorIdentifierNode::output(), llvm::ms_demangle::NamedIdentifierNode::output(), and llvm::ms_demangle::StructorIdentifierNode::output().
Member Data Documentation
TemplateParams
NodeArrayNode* llvm::ms_demangle::IdentifierNode::TemplateParams = nullptr
Definition at line 394 of file MicrosoftDemangleNodes.h.
Referenced by outputTemplateParameters().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp