LLVM: llvm::yaml::ScalarEnumerationTraits< IFSSymbolType > Struct Reference
llvm::yaml::ScalarEnumerationTraits< IFSSymbolType > Struct Reference
YAML traits for ELFSymbolType.
Static Public Member Functions
static void enumeration (IO &IO, IFSSymbolType &SymbolType)
Detailed Description
YAML traits for ELFSymbolType.
Definition at line 32 of file IFSHandler.cpp.
Member Function Documentation
enumeration()
void llvm::yaml::ScalarEnumerationTraits< IFSSymbolType >::enumeration (IO & IO, IFSSymbolType & SymbolType) inline static
Definition at line 33 of file IFSHandler.cpp.
References llvm::yaml::IO::enumCase(), llvm::ifs::Func, llvm::yaml::IO::matchEnumFallback(), llvm::ifs::NoType, llvm::ifs::Object, llvm::yaml::IO::outputting(), llvm::ifs::TLS, and llvm::ifs::Unknown.
The documentation for this struct was generated from the following file:
lib/InterfaceStub/IFSHandler.cpp