LLVM: llvm::SimplifyCFGOptions Struct Reference
llvm::SimplifyCFGOptions Struct Reference
#include "llvm/Transforms/Utils/SimplifyCFGOptions.h"
Public Member Functions
SimplifyCFGOptions & bonusInstThreshold (int I)
SimplifyCFGOptions & forwardSwitchCondToPhi (bool B)
SimplifyCFGOptions & convertSwitchRangeToICmp (bool B)
SimplifyCFGOptions & convertSwitchToLookupTable (bool B)
SimplifyCFGOptions & needCanonicalLoops (bool B)
SimplifyCFGOptions & hoistCommonInsts (bool B)
SimplifyCFGOptions & hoistLoadsStoresWithCondFaulting (bool B)
SimplifyCFGOptions & sinkCommonInsts (bool B)
SimplifyCFGOptions & setAssumptionCache (AssumptionCache *Cache)
SimplifyCFGOptions & setSimplifyCondBranch (bool B)
SimplifyCFGOptions & speculateBlocks (bool B)
SimplifyCFGOptions & speculateUnpredictables (bool B)
Public Attributes
int BonusInstThreshold = 1
bool ForwardSwitchCondToPhi = false
bool ConvertSwitchRangeToICmp = false
bool ConvertSwitchToLookupTable = false
bool NeedCanonicalLoop = true
bool HoistCommonInsts = false
bool HoistLoadsStoresWithCondFaulting = false
bool SinkCommonInsts = false
bool SimplifyCondBranch = true
bool SpeculateBlocks = true
bool SpeculateUnpredictables = false
AssumptionCache * AC = nullptr
Detailed Description
Definition at line 23 of file SimplifyCFGOptions.h.
Member Function Documentation
bonusInstThreshold()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::bonusInstThreshold (int I) inline
Definition at line 39 of file SimplifyCFGOptions.h.
References BonusInstThreshold, and I.
convertSwitchRangeToICmp()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::convertSwitchRangeToICmp (bool B) inline
Definition at line 47 of file SimplifyCFGOptions.h.
References B(), and ConvertSwitchRangeToICmp.
convertSwitchToLookupTable()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::convertSwitchToLookupTable (bool B) inline
Definition at line 51 of file SimplifyCFGOptions.h.
References B(), and ConvertSwitchToLookupTable.
forwardSwitchCondToPhi()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::forwardSwitchCondToPhi (bool B) inline
Definition at line 43 of file SimplifyCFGOptions.h.
References B(), and ForwardSwitchCondToPhi.
hoistCommonInsts()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::hoistCommonInsts (bool B) inline
Definition at line 59 of file SimplifyCFGOptions.h.
References B(), and HoistCommonInsts.
hoistLoadsStoresWithCondFaulting()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::hoistLoadsStoresWithCondFaulting (bool B) inline
Definition at line 63 of file SimplifyCFGOptions.h.
References B(), and HoistLoadsStoresWithCondFaulting.
needCanonicalLoops()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::needCanonicalLoops (bool B) inline
Definition at line 55 of file SimplifyCFGOptions.h.
References B(), and NeedCanonicalLoop.
setAssumptionCache()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::setAssumptionCache (AssumptionCache * Cache) inline
Definition at line 71 of file SimplifyCFGOptions.h.
References AC.
setSimplifyCondBranch()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::setSimplifyCondBranch (bool B) inline
Definition at line 75 of file SimplifyCFGOptions.h.
References B(), and SimplifyCondBranch.
sinkCommonInsts()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::sinkCommonInsts (bool B) inline
Definition at line 67 of file SimplifyCFGOptions.h.
References B(), and SinkCommonInsts.
speculateBlocks()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::speculateBlocks (bool B) inline
Definition at line 80 of file SimplifyCFGOptions.h.
References B(), and SpeculateBlocks.
speculateUnpredictables()
SimplifyCFGOptions & llvm::SimplifyCFGOptions::speculateUnpredictables (bool B) inline
Definition at line 84 of file SimplifyCFGOptions.h.
References B(), and SpeculateUnpredictables.
Member Data Documentation
AC
AssumptionCache* llvm::SimplifyCFGOptions::AC = nullptr
Definition at line 36 of file SimplifyCFGOptions.h.
Referenced by setAssumptionCache().
BonusInstThreshold
int llvm::SimplifyCFGOptions::BonusInstThreshold = 1
Definition at line 24 of file SimplifyCFGOptions.h.
Referenced by bonusInstThreshold().
ConvertSwitchRangeToICmp
bool llvm::SimplifyCFGOptions::ConvertSwitchRangeToICmp = false
Definition at line 26 of file SimplifyCFGOptions.h.
Referenced by convertSwitchRangeToICmp().
ConvertSwitchToLookupTable
bool llvm::SimplifyCFGOptions::ConvertSwitchToLookupTable = false
Definition at line 27 of file SimplifyCFGOptions.h.
Referenced by convertSwitchToLookupTable().
ForwardSwitchCondToPhi
bool llvm::SimplifyCFGOptions::ForwardSwitchCondToPhi = false
Definition at line 25 of file SimplifyCFGOptions.h.
Referenced by forwardSwitchCondToPhi().
HoistCommonInsts
bool llvm::SimplifyCFGOptions::HoistCommonInsts = false
Definition at line 29 of file SimplifyCFGOptions.h.
Referenced by hoistCommonInsts().
HoistLoadsStoresWithCondFaulting
bool llvm::SimplifyCFGOptions::HoistLoadsStoresWithCondFaulting = false
Definition at line 30 of file SimplifyCFGOptions.h.
Referenced by hoistLoadsStoresWithCondFaulting().
NeedCanonicalLoop
bool llvm::SimplifyCFGOptions::NeedCanonicalLoop = true
Definition at line 28 of file SimplifyCFGOptions.h.
Referenced by needCanonicalLoops().
SimplifyCondBranch
bool llvm::SimplifyCFGOptions::SimplifyCondBranch = true
Definition at line 32 of file SimplifyCFGOptions.h.
Referenced by setSimplifyCondBranch().
SinkCommonInsts
bool llvm::SimplifyCFGOptions::SinkCommonInsts = false
Definition at line 31 of file SimplifyCFGOptions.h.
Referenced by sinkCommonInsts().
SpeculateBlocks
bool llvm::SimplifyCFGOptions::SpeculateBlocks = true
Definition at line 33 of file SimplifyCFGOptions.h.
Referenced by speculateBlocks().
SpeculateUnpredictables
bool llvm::SimplifyCFGOptions::SpeculateUnpredictables = false
Definition at line 34 of file SimplifyCFGOptions.h.
Referenced by speculateUnpredictables().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/Utils/SimplifyCFGOptions.h