LLVM: llvm::gsym::MergedFunctionsInfo Struct Reference
llvm::gsym::MergedFunctionsInfo Struct Reference
#include "llvm/DebugInfo/GSYM/MergedFunctionsInfo.h"
Public Member Functions
LLVM_ABI void clear ()
bool isValid ()
Query if a MergedFunctionsInfo object is valid.
LLVM_ABI llvm::Error encode (FileWriter &O) const
Encode this MergedFunctionsInfo object into FileWriter stream.
Static Public Member Functions
static LLVM_ABI llvm::Expected< std::vector< DataExtractor > > getFuncsDataExtractors (DataExtractor &Data)
Get a vector of DataExtractor objects for the functions in this MergedFunctionsInfo object.
static LLVM_ABI llvm::Expected< MergedFunctionsInfo > decode (DataExtractor &Data, uint64_t BaseAddr)
Decode an MergedFunctionsInfo object from a binary data stream.
Public Attributes
std::vector< FunctionInfo > MergedFunctions
Detailed Description
Definition at line 25 of file MergedFunctionsInfo.h.
Member Function Documentation
clear()
void MergedFunctionsInfo::clear ()
Definition at line 17 of file MergedFunctionsInfo.cpp.
References clear(), and MergedFunctions.
Referenced by clear().
decode()
llvm::Expected< MergedFunctionsInfo > MergedFunctionsInfo::decode (DataExtractor & Data, uint64_t BaseAddr) static
Decode an MergedFunctionsInfo object from a binary data stream.
Parameters
Data The binary stream to read the data from. This object must have the data for the MergedFunctionsInfo object starting at offset zero. The data can contain more data than needed.
BaseAddr The base address to use when encoding all address ranges.
Returns
An MergedFunctionsInfo or an error describing the issue that was encountered during decoding.
Definition at line 36 of file MergedFunctionsInfo.cpp.
References llvm::Data, llvm::gsym::FunctionInfo::decode(), getFuncsDataExtractors(), MergedFunctions, and llvm::Expected< T >::takeError().
Referenced by llvm::gsym::FunctionInfo::decode().
encode()
llvm::Error MergedFunctionsInfo::encode (FileWriter & O) const
Encode this MergedFunctionsInfo object into FileWriter stream.
Parameters
O The binary stream to write the data to at the current file position.
Returns
An error object that indicates success or failure for the encoding process.
Definition at line 19 of file MergedFunctionsInfo.cpp.
References F, llvm::gsym::FileWriter::fixup32(), llvm::Length, MergedFunctions, llvm::Error::success(), llvm::Expected< T >::takeError(), llvm::gsym::FileWriter::tell(), and llvm::gsym::FileWriter::writeU32().
getFuncsDataExtractors()
llvm::Expected< std::vector< DataExtractor > > MergedFunctionsInfo::getFuncsDataExtractors (DataExtractor & Data) static
Get a vector of DataExtractor objects for the functions in this MergedFunctionsInfo object.
Parameters
Data The binary stream to read the data from. This object must have the data for the MergedFunctionsInfo object starting at offset zero. The data can contain more data than needed.
Returns
An llvm::Expected containing a vector of DataExtractor objects on success, or an error object if parsing fails.
Definition at line 54 of file MergedFunctionsInfo.cpp.
References llvm::Count, llvm::createStringError(), llvm::Data, llvm::Offset, and Results.
Referenced by decode(), and llvm::gsym::GsymReader::lookupAll().
isValid()
bool llvm::gsym::MergedFunctionsInfo::isValid () inline
Query if a MergedFunctionsInfo object is valid.
Returns
A boolean indicating if this FunctionInfo is valid.
Definition at line 33 of file MergedFunctionsInfo.h.
References MergedFunctions.
Member Data Documentation
MergedFunctions
std::vector<FunctionInfo> llvm::gsym::MergedFunctionsInfo::MergedFunctions
Definition at line 26 of file MergedFunctionsInfo.h.
Referenced by clear(), decode(), llvm::gsym::GsymReader::dump(), encode(), and isValid().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/GSYM/MergedFunctionsInfo.h
lib/DebugInfo/GSYM/MergedFunctionsInfo.cpp