LLVM: llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs > Struct Template Reference
llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs > Struct Template Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Member Functions
ReassociatableOpc_match (unsigned Opcode, const PatternTs &...Patterns)
template<typename MatchContext>
bool match (const MatchContext &Ctx, SDValue N)
void collectLeaves (SDValue V, SmallVector< SDValue > &Leaves)
bool reassociatableMatchHelper (const ArrayRef< SmallBitVector > Matches, SmallBitVector &Used, size_t Curr=0)
Public Attributes
unsigned Opcode
std::tuple< PatternTs... > Patterns
Detailed Description
template<typename... PatternTs>
struct llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >
Definition at line 1243 of file SDPatternMatch.h.
Constructor & Destructor Documentation
ReassociatableOpc_match()
template<typename... PatternTs> llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >::ReassociatableOpc_match (unsigned Opcode, const PatternTs &... Patterns) inline
Definition at line 1247 of file SDPatternMatch.h.
References Opcode, and Patterns.
Member Function Documentation
collectLeaves()
template<typename... PatternTs> void llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >::collectLeaves (SDValue V, SmallVector< SDValue > & Leaves) inline
Definition at line 1274 of file SDPatternMatch.h.
References collectLeaves(), llvm::SmallVectorImpl< T >::emplace_back(), I, N, and Opcode.
Referenced by collectLeaves(), and match().
match()
template<typename... PatternTs> template<typename MatchContext> bool llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 1251 of file SDPatternMatch.h.
References collectLeaves(), I, N, P, Patterns, reassociatableMatchHelper(), llvm::SDPatternMatch::sd_context_match(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
reassociatableMatchHelper()
template<typename... PatternTs> bool llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >::reassociatableMatchHelper (const ArrayRef< SmallBitVector > Matches, SmallBitVector & Used, size_t Curr = 0) inline nodiscard
Definition at line 1284 of file SDPatternMatch.h.
References N, reassociatableMatchHelper(), llvm::ArrayRef< T >::size(), and llvm::size().
Referenced by match(), and reassociatableMatchHelper().
Member Data Documentation
Opcode
template<typename... PatternTs> unsigned llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >::Opcode
Definition at line 1244 of file SDPatternMatch.h.
Referenced by collectLeaves(), and ReassociatableOpc_match().
Patterns
template<typename... PatternTs> std::tuple<PatternTs...> llvm::SDPatternMatch::ReassociatableOpc_match< PatternTs >::Patterns
Definition at line 1245 of file SDPatternMatch.h.
Referenced by match(), and ReassociatableOpc_match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h