LLVM: llvm::SCEVPatternMatch::cst_pred_ty< Predicate > Struct Template Reference
llvm::SCEVPatternMatch::cst_pred_ty< Predicate > Struct Template Reference
#include "llvm/Analysis/ScalarEvolutionPatternMatch.h"
Public Member Functions
cst_pred_ty ()=default
cst_pred_ty (uint64_t V)
bool match (const SCEV *S) const
Public Member Functions inherited from Predicate
Predicate (std::function< bool(const MachineInstr &)> Pred)
bool operator() (const MachineInstr &MI) const
Predicate operator! () const
Predicate operator&& (const Predicate &RHS) const
Predicate operator|| (const Predicate &RHS) const
Detailed Description
template<typename Predicate>
struct llvm::SCEVPatternMatch::cst_pred_ty< Predicate >
Definition at line 25 of file ScalarEvolutionPatternMatch.h.
Constructor & Destructor Documentation
cst_pred_ty() [1/2]
template<typename Predicate> llvm::SCEVPatternMatch::cst_pred_ty< Predicate >::cst_pred_ty () default
cst_pred_ty() [2/2]
template<typename Predicate> llvm::SCEVPatternMatch::cst_pred_ty< Predicate >::cst_pred_ty (uint64_t V) inline
Definition at line 27 of file ScalarEvolutionPatternMatch.h.
Member Function Documentation
match()
template<typename Predicate> bool llvm::SCEVPatternMatch::cst_pred_ty< Predicate >::match (const SCEV * S) const inline
Definition at line 28 of file ScalarEvolutionPatternMatch.h.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::SCEV::getType(), llvm::isa(), and llvm::Type::isVectorTy().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/ScalarEvolutionPatternMatch.h