LLVM: llvm::HexagonVectorLoopCarriedReusePass Struct Reference
llvm::HexagonVectorLoopCarriedReusePass Struct Reference
Hexagon Vector Loop Carried Reuse Pass.
#include "Target/Hexagon/HexagonVectorLoopCarriedReuse.h"
Public Member Functions
HexagonVectorLoopCarriedReusePass ()=default
PreservedAnalyses run (Loop &L, LoopAnalysisManager &LAM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Run pass over the Loop.
Public Member Functions inherited from llvm::PassInfoMixin< HexagonVectorLoopCarriedReusePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< HexagonVectorLoopCarriedReusePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Hexagon Vector Loop Carried Reuse Pass.
Definition at line 128 of file HexagonVectorLoopCarriedReuse.h.
Constructor & Destructor Documentation
HexagonVectorLoopCarriedReusePass()
llvm::HexagonVectorLoopCarriedReusePass::HexagonVectorLoopCarriedReusePass () default
References LAM.
Referenced by run().
Member Function Documentation
run()
hexagon Hexagon specific predictive commoning for HVX false PreservedAnalyses HexagonVectorLoopCarriedReusePass::run (Loop & L, LoopAnalysisManager & LAM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Run pass over the Loop.
Definition at line 213 of file HexagonVectorLoopCarriedReuse.cpp.
References llvm::PreservedAnalyses::all(), HexagonVectorLoopCarriedReusePass(), LAM, llvm::PreservedAnalyses::preserveSet(), and run().
Referenced by run().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/HexagonVectorLoopCarriedReuse.h
lib/Target/Hexagon/HexagonVectorLoopCarriedReuse.cpp