LLVM: llvm::memprof::CallerCalleePairExtractor Struct Reference
llvm::memprof::CallerCalleePairExtractor Struct Reference
#include "llvm/ProfileData/MemProfRadixTree.h"
Public Member Functions
CallerCalleePairExtractor ()=delete
CallerCalleePairExtractor (const unsigned char *CallStackBase, llvm::function_ref< Frame(LinearFrameId)> FrameIdToFrame, unsigned RadixTreeSize)
void operator() (LinearCallStackId LinearCSId)
Public Attributes
const unsigned char * CallStackBase
llvm::function_ref< Frame(LinearFrameId)> FrameIdToFrame
DenseMap< uint64_t, SmallVector< CallEdgeTy, 0 > > CallerCalleePairs
BitVector Visited
Detailed Description
Definition at line 155 of file MemProfRadixTree.h.
Constructor & Destructor Documentation
CallerCalleePairExtractor() [1/2]
llvm::memprof::CallerCalleePairExtractor::CallerCalleePairExtractor () delete
CallerCalleePairExtractor() [2/2]
llvm::memprof::CallerCalleePairExtractor::CallerCalleePairExtractor (const unsigned char * CallStackBase, llvm::function_ref< Frame(LinearFrameId)> FrameIdToFrame, unsigned RadixTreeSize) inline
Definition at line 167 of file MemProfRadixTree.h.
References CallStackBase, FrameIdToFrame, and Visited.
Member Function Documentation
operator()()
void llvm::memprof::CallerCalleePairExtractor::operator() (LinearCallStackId LinearCSId) inline
Definition at line 174 of file MemProfRadixTree.h.
References assert(), CallerCalleePairs, CallStackBase, F, FrameIdToFrame, llvm::Offset, Ptr, llvm::support::endian::read(), llvm::support::endian::readNext(), and Visited.
Member Data Documentation
CallerCalleePairs
DenseMap<uint64_t, SmallVector<CallEdgeTy, 0> > llvm::memprof::CallerCalleePairExtractor::CallerCalleePairs
Definition at line 161 of file MemProfRadixTree.h.
Referenced by operator()().
CallStackBase
const unsigned char* llvm::memprof::CallerCalleePairExtractor::CallStackBase
Definition at line 157 of file MemProfRadixTree.h.
Referenced by CallerCalleePairExtractor(), and operator()().
FrameIdToFrame
llvm::function_ref<Frame(LinearFrameId)> llvm::memprof::CallerCalleePairExtractor::FrameIdToFrame
Definition at line 159 of file MemProfRadixTree.h.
Referenced by CallerCalleePairExtractor(), and operator()().
Visited
BitVector llvm::memprof::CallerCalleePairExtractor::Visited
Definition at line 164 of file MemProfRadixTree.h.
Referenced by CallerCalleePairExtractor(), and operator()().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProfRadixTree.h