LLVM: llvm::NewArchiveMember Struct Reference
llvm::NewArchiveMember Struct Reference
#include "llvm/Object/ArchiveWriter.h"
Public Member Functions
NewArchiveMember ()=default
LLVM_ABI NewArchiveMember (MemoryBufferRef BufRef)
LLVM_ABI object::Archive::Kind detectKindFromObject () const
Static Public Member Functions
static LLVM_ABI Expected< NewArchiveMember > getOldMember (const object::Archive::Child &OldMember, bool Deterministic)
static LLVM_ABI Expected< NewArchiveMember > getFile (StringRef FileName, bool Deterministic)
Public Attributes
std::unique_ptr< MemoryBuffer > Buf
StringRef MemberName
sys::TimePoint< std::chrono::seconds > ModTime
unsigned UID = 0
unsigned GID = 0
unsigned Perms = 0644
Detailed Description
Definition at line 21 of file ArchiveWriter.h.
Constructor & Destructor Documentation
NewArchiveMember() [1/2]
llvm::NewArchiveMember::NewArchiveMember () default
References LLVM_ABI.
Referenced by getFile(), and getOldMember().
NewArchiveMember() [2/2]
NewArchiveMember::NewArchiveMember (MemoryBufferRef BufRef)
Definition at line 56 of file ArchiveWriter.cpp.
References Buf, and MemberName.
Member Function Documentation
detectKindFromObject()
object::Archive::Kind NewArchiveMember::detectKindFromObject () const
Definition at line 60 of file ArchiveWriter.cpp.
References llvm::file_magic::bitcode, Buf, llvm::cast(), llvm::consumeError(), llvm::object::ObjectFile::createObjectFile(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::object::Archive::getDefaultKind(), llvm::object::Archive::getDefaultKindForTriple(), llvm::identify_magic(), llvm::isa(), llvm::object::Archive::K_AIXBIG, llvm::object::Archive::K_COFF, llvm::object::Archive::K_DARWIN, llvm::object::Archive::K_GNU, and llvm::Expected< T >::takeError().
getFile()
Expected< NewArchiveMember > NewArchiveMember::getFile (StringRef FileName, bool Deterministic) static
Definition at line 128 of file ArchiveWriter.cpp.
References assert(), llvm::sys::fs::closeFile(), llvm::sys::fs::directory_file, llvm::errorCodeToError(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getOpenFile(), llvm::is_a_directory, llvm::sys::fs::kInvalidFile, llvm::make_error_code(), NewArchiveMember(), llvm::sys::fs::openNativeFileForRead(), and llvm::sys::fs::status().
getOldMember()
Expected< NewArchiveMember > NewArchiveMember::getOldMember (const object::Archive::Child & OldMember, bool Deterministic) static
Definition at line 98 of file ArchiveWriter.cpp.
References llvm::Expected< T >::get(), llvm::object::Archive::Child::getAccessMode(), llvm::object::Archive::Child::getGID(), llvm::object::Archive::Child::getLastModified(), llvm::MemoryBuffer::getMemBuffer(), llvm::object::Archive::Child::getMemoryBufferRef(), llvm::object::Archive::Child::getUID(), NewArchiveMember(), and llvm::Expected< T >::takeError().
Referenced by llvm::objcopy::createNewArchiveMembers().
Member Data Documentation
Buf
std::unique_ptr<MemoryBuffer> llvm::NewArchiveMember::Buf
Definition at line 22 of file ArchiveWriter.h.
Referenced by detectKindFromObject(), getDefaultOutputPath(), and NewArchiveMember().
GID
unsigned llvm::NewArchiveMember::GID = 0
Definition at line 25 of file ArchiveWriter.h.
MemberName
StringRef llvm::NewArchiveMember::MemberName
Definition at line 23 of file ArchiveWriter.h.
Referenced by NewArchiveMember().
ModTime
sys::TimePoint<std::chrono::seconds> llvm::NewArchiveMember::ModTime
Definition at line 24 of file ArchiveWriter.h.
Perms
unsigned llvm::NewArchiveMember::Perms = 0644
Definition at line 25 of file ArchiveWriter.h.
UID
unsigned llvm::NewArchiveMember::UID = 0
Definition at line 25 of file ArchiveWriter.h.
The documentation for this struct was generated from the following files:
include/llvm/Object/ArchiveWriter.h
lib/Object/ArchiveWriter.cpp