LLVM: llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > > Struct Reference
llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > > Struct Reference
#include "llvm/ObjectYAML/XCOFFYAML.h"
Static Public Member Functions
static void mapping (IO &IO, std::unique_ptr< XCOFFYAML::AuxSymbolEnt > &AuxSym)
Detailed Description
Definition at line 268 of file XCOFFYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping (IO & IO, std::unique_ptr< XCOFFYAML::AuxSymbolEnt > & AuxSym) static
Definition at line 322 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::AUX_CSECT, llvm::XCOFFYAML::AUX_EXCEPT, llvm::XCOFFYAML::AUX_FCN, llvm::XCOFFYAML::AUX_FILE, llvm::XCOFFYAML::AUX_SECT, llvm::XCOFFYAML::AUX_STAT, llvm::XCOFFYAML::AUX_SYM, llvm::yaml::auxSymMapping(), llvm::cast(), llvm::yaml::IO::getContext(), llvm::XCOFFYAML::Object::Header, llvm::XCOFFYAML::FileHeader::Magic, mapping(), llvm::yaml::IO::mapRequired(), llvm::yaml::IO::outputting(), llvm::yaml::ResetAuxSym(), llvm::yaml::IO::setError(), and llvm::XCOFF::XCOFF64.
Referenced by mapping().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/XCOFFYAML.h
lib/ObjectYAML/XCOFFYAML.cpp