LLVM: llvm::RetainedKnowledge Struct Reference
llvm::RetainedKnowledge Struct Reference
Represent one information held inside an operand bundle of an llvm.assume.
#include "llvm/Analysis/AssumeBundleQueries.h"
Public Member Functions
RetainedKnowledge (Attribute::AttrKind AttrKind=Attribute::None, uint64_t ArgValue=0, Value *WasOn=nullptr)
bool operator== (RetainedKnowledge Other) const
bool operator!= (RetainedKnowledge Other) const
bool operator< (RetainedKnowledge Other) const
This is only intended for use in std::min/stdmax between attribute that only differ in ArgValue.
operator bool () const
Static Public Member Functions
static RetainedKnowledge none ()
Public Attributes
Attribute::AttrKind AttrKind = Attribute::None
uint64_t ArgValue = 0
Value * IRArgValue = nullptr
Value * WasOn = nullptr
Detailed Description
Represent one information held inside an operand bundle of an llvm.assume.
AttrKind is the property that holds. WasOn if not null is that Value for which AttrKind holds. ArgValue is optionally an argument of the attribute. For example if we know that P has an alignment of at least four:
AttrKind will be Attribute::Alignment.
WasOn will be P.
ArgValue will be 4.
Definition at line 102 of file AssumeBundleQueries.h.
Constructor & Destructor Documentation
RetainedKnowledge()
llvm::RetainedKnowledge::RetainedKnowledge (Attribute::AttrKind AttrKind = Attribute::None, uint64_t ArgValue = 0, Value * WasOn = nullptr) inline
Definition at line 107 of file AssumeBundleQueries.h.
References ArgValue, AttrKind, llvm::Attribute::None, and WasOn.
Referenced by none(), operator!=(), operator<(), and operator==().
Member Function Documentation
none()
RetainedKnowledge llvm::RetainedKnowledge::none () inline static
Definition at line 125 of file AssumeBundleQueries.h.
References RetainedKnowledge().
Referenced by llvm::getKnowledgeForValue(), llvm::getKnowledgeFromUse(), and llvm::simplifyRetainedKnowledge().
operator bool()
llvm::RetainedKnowledge::operator bool () const inline
Definition at line 124 of file AssumeBundleQueries.h.
References AttrKind, and llvm::Attribute::None.
operator!=()
bool llvm::RetainedKnowledge::operator!= (RetainedKnowledge Other) const inline
Definition at line 114 of file AssumeBundleQueries.h.
References llvm::Other, and RetainedKnowledge().
operator<()
bool llvm::RetainedKnowledge::operator< (RetainedKnowledge Other) const inline
This is only intended for use in std::min/stdmax between attribute that only differ in ArgValue.
Definition at line 117 of file AssumeBundleQueries.h.
References ArgValue, assert(), AttrKind, llvm::Attribute::None, llvm::Other, RetainedKnowledge(), and WasOn.
operator==()
bool llvm::RetainedKnowledge::operator== (RetainedKnowledge Other) const inline
Definition at line 110 of file AssumeBundleQueries.h.
References ArgValue, AttrKind, IRArgValue, llvm::Other, RetainedKnowledge(), and WasOn.
Member Data Documentation
ArgValue
uint64_t llvm::RetainedKnowledge::ArgValue = 0
Definition at line 104 of file AssumeBundleQueries.h.
Referenced by isDereferenceableAndAlignedPointer(), isDereferenceableAndAlignedPointerViaAssumption(), operator<(), operator==(), RetainedKnowledge(), and llvm::InstCombinerImpl::visitCallInst().
AttrKind
Attribute::AttrKind llvm::RetainedKnowledge::AttrKind = Attribute::None
Definition at line 103 of file AssumeBundleQueries.h.
Referenced by llvm::getKnowledgeFromUse(), isDereferenceableAndAlignedPointerViaAssumption(), operator bool(), operator<(), operator==(), RetainedKnowledge(), and llvm::InstCombinerImpl::visitCallInst().
IRArgValue
Value* llvm::RetainedKnowledge::IRArgValue = nullptr
Definition at line 105 of file AssumeBundleQueries.h.
Referenced by llvm::isDereferenceableAndAlignedInLoop(), and operator==().
WasOn
Value* llvm::RetainedKnowledge::WasOn = nullptr
Definition at line 106 of file AssumeBundleQueries.h.
Referenced by operator<(), operator==(), RetainedKnowledge(), and llvm::InstCombinerImpl::visitCallInst().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/AssumeBundleQueries.h