LLVM: llvm::ARM::WinEH::ExceptionDataRecord Struct Reference
llvm::ARM::WinEH::ExceptionDataRecord Struct Reference
#include "llvm/Support/ARMWinEH.h"
Public Member Functions
ExceptionDataRecord (const support::ulittle32_t *Data, bool isAArch64)
uint32_t FunctionLength () const
uint32_t FunctionLengthInBytesARM () const
uint32_t FunctionLengthInBytesAArch64 () const
uint8_t Vers () const
bool X () const
bool E () const
bool F () const
uint16_t EpilogueCount () const
uint8_t CodeWords () const
ArrayRef< support::ulittle32_t > EpilogueScopes () const
ArrayRef< uint8_t > UnwindByteCode () const
uint32_t ExceptionHandlerRVA () const
uint32_t ExceptionHandlerParameter () const
Public Attributes
const support::ulittle32_t * Data
bool isAArch64
Detailed Description
Definition at line 433 of file ARMWinEH.h.
Constructor & Destructor Documentation
ExceptionDataRecord()
llvm::ARM::WinEH::ExceptionDataRecord::ExceptionDataRecord (const support::ulittle32_t * Data, bool isAArch64) inline
Definition at line 437 of file ARMWinEH.h.
References Data, and isAArch64.
Member Function Documentation
CodeWords()
uint8_t llvm::ARM::WinEH::ExceptionDataRecord::CodeWords () const inline
Definition at line 478 of file ARMWinEH.h.
References Data, llvm::ARM::WinEH::HeaderWords(), and isAArch64.
Referenced by ExceptionHandlerParameter(), ExceptionHandlerRVA(), and UnwindByteCode().
E()
bool llvm::ARM::WinEH::ExceptionDataRecord::E () const inline
Definition at line 460 of file ARMWinEH.h.
References Data.
Referenced by EpilogueScopes(), ExceptionHandlerParameter(), ExceptionHandlerRVA(), and UnwindByteCode().
EpilogueCount()
uint16_t llvm::ARM::WinEH::ExceptionDataRecord::EpilogueCount () const inline
Definition at line 469 of file ARMWinEH.h.
References Data, llvm::ARM::WinEH::HeaderWords(), and isAArch64.
Referenced by EpilogueScopes(), ExceptionHandlerParameter(), ExceptionHandlerRVA(), and UnwindByteCode().
EpilogueScopes()
ArrayRef< support::ulittle32_t > llvm::ARM::WinEH::ExceptionDataRecord::EpilogueScopes () const inline
Definition at line 487 of file ARMWinEH.h.
References llvm::ArrayRef(), assert(), Data, E(), EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and llvm::Offset.
ExceptionHandlerParameter()
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerParameter () const inline
Definition at line 506 of file ARMWinEH.h.
References assert(), CodeWords(), Data, E(), EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and X().
ExceptionHandlerRVA()
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerRVA () const inline
Definition at line 501 of file ARMWinEH.h.
References assert(), CodeWords(), Data, E(), EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and X().
F()
bool llvm::ARM::WinEH::ExceptionDataRecord::F () const inline
Definition at line 464 of file ARMWinEH.h.
References assert(), Data, and isAArch64.
FunctionLength()
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::FunctionLength () const inline
Definition at line 440 of file ARMWinEH.h.
References Data.
Referenced by FunctionLengthInBytesAArch64(), and FunctionLengthInBytesARM().
FunctionLengthInBytesAArch64()
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::FunctionLengthInBytesAArch64 () const inline
Definition at line 448 of file ARMWinEH.h.
References FunctionLength().
FunctionLengthInBytesARM()
uint32_t llvm::ARM::WinEH::ExceptionDataRecord::FunctionLengthInBytesARM () const inline
Definition at line 444 of file ARMWinEH.h.
References FunctionLength().
UnwindByteCode()
ArrayRef< uint8_t > llvm::ARM::WinEH::ExceptionDataRecord::UnwindByteCode () const inline
Definition at line 493 of file ARMWinEH.h.
References llvm::ArrayRef(), CodeWords(), Data, E(), EpilogueCount(), llvm::ARM::WinEH::HeaderWords(), and llvm::Offset.
Vers()
uint8_t llvm::ARM::WinEH::ExceptionDataRecord::Vers () const inline
Definition at line 452 of file ARMWinEH.h.
References Data.
X()
bool llvm::ARM::WinEH::ExceptionDataRecord::X () const inline
Definition at line 456 of file ARMWinEH.h.
References Data.
Referenced by ExceptionHandlerParameter(), and ExceptionHandlerRVA().
Member Data Documentation
Data
const support::ulittle32_t* llvm::ARM::WinEH::ExceptionDataRecord::Data
Definition at line 434 of file ARMWinEH.h.
Referenced by CodeWords(), E(), EpilogueCount(), EpilogueScopes(), ExceptionDataRecord(), ExceptionHandlerParameter(), ExceptionHandlerRVA(), F(), FunctionLength(), llvm::ARM::WinEH::HeaderWords(), UnwindByteCode(), Vers(), and X().
isAArch64
bool llvm::ARM::WinEH::ExceptionDataRecord::isAArch64
Definition at line 435 of file ARMWinEH.h.
Referenced by CodeWords(), EpilogueCount(), ExceptionDataRecord(), F(), and llvm::ARM::WinEH::HeaderWords().
The documentation for this struct was generated from the following file:
include/llvm/Support/ARMWinEH.h