LLVM: llvm::yaml::MappingTraits< COFFYAML::SectionDataEntry > Struct Reference
llvm::yaml::MappingTraits< COFFYAML::SectionDataEntry > Struct Reference
#include "llvm/ObjectYAML/COFFYAML.h"
Static Public Member Functions
static void mapping (IO &IO, COFFYAML::SectionDataEntry &Sec)
Detailed Description
Definition at line 273 of file COFFYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< COFFYAML::SectionDataEntry >::mapping (IO & IO, COFFYAML::SectionDataEntry & Sec) static
Definition at line 657 of file COFFYAML.cpp.
References E(), llvm::yaml::IO::getContext(), H, llvm::COFF::is64Bit(), and llvm::yaml::IO::mapOptional().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/COFFYAML.h
lib/ObjectYAML/COFFYAML.cpp