LLVM: false::GepNode Struct Reference
false::GepNode Struct Reference
Public Types
enum {
None = 0 , Root = 0x01 , Internal = 0x02 , Used = 0x04 ,
InBounds = 0x08 , Pointer = 0x10
}
Public Member Functions
GepNode ()
GepNode (const GepNode *N)
Public Attributes
uint32_t Flags = 0
union {
GepNode * Parent
Value * BaseVal
};
Value * Idx = nullptr
Type * PTy = nullptr
Friends
raw_ostream & operator<< (raw_ostream &OS, const GepNode &GN)
Detailed Description
Definition at line 169 of file HexagonCommonGEP.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
None
Root
Internal
Used
InBounds
Pointer
Definition at line 170 of file HexagonCommonGEP.cpp.
Constructor & Destructor Documentation
GepNode() [1/2]
false::GepNode::GepNode () inline
Definition at line 200 of file HexagonCommonGEP.cpp.
References Parent.
Referenced by GepNode(), and operator<<.
GepNode() [2/2]
false::GepNode::GepNode (const GepNode * N) inline
Definition at line 201 of file HexagonCommonGEP.cpp.
References BaseVal, Flags, GepNode(), Idx, N, Parent, PTy, and Root.
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const GepNode & GN) friend
Definition at line 211 of file HexagonCommonGEP.cpp.
References BaseVal, llvm::cast(), llvm::dyn_cast(), Flags, GepNode(), llvm::Value::getName(), llvm::Type::getStructName(), llvm::Value::hasName(), Idx, InBounds, Internal, llvm::StructType::isLiteral(), llvm::Type::isStructTy(), Parent, Pointer, PTy, Root, and Used.
Member Data Documentation
[union]
union { ... } false::GepNode
BaseVal
Value* false::GepNode::BaseVal
Definition at line 193 of file HexagonCommonGEP.cpp.
Referenced by GepNode(), and operator<<.
Flags
uint32_t false::GepNode::Flags = 0
Definition at line 190 of file HexagonCommonGEP.cpp.
Referenced by GepNode(), and operator<<.
Idx
Value* false::GepNode::Idx = nullptr
Definition at line 195 of file HexagonCommonGEP.cpp.
Referenced by GepNode(), and operator<<.
Parent
GepNode* false::GepNode::Parent
Definition at line 192 of file HexagonCommonGEP.cpp.
Referenced by GepNode(), GepNode(), and operator<<.
PTy
Type* false::GepNode::PTy = nullptr
Definition at line 196 of file HexagonCommonGEP.cpp.
Referenced by GepNode(), and operator<<.
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/HexagonCommonGEP.cpp