LLVM: llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder Struct Reference
llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder Struct Reference
Helper to gather options relevant to the target machine creation.
#include "llvm/LTO/legacy/ThinLTOCodeGenerator.h"
Public Member Functions
LLVM_ABI std::unique_ptr< TargetMachine > create () const
Public Attributes
Triple TheTriple
std::string MCpu
std::string MAttr
TargetOptions Options
std::optional< Reloc::Model > RelocModel
CodeGenOptLevel CGOptLevel = CodeGenOptLevel::Aggressive
Detailed Description
Helper to gather options relevant to the target machine creation.
Definition at line 43 of file ThinLTOCodeGenerator.h.
Member Function Documentation
create()
std::unique_ptr< TargetMachine > TargetMachineBuilder::create () const
Definition at line 576 of file ThinLTOCodeGenerator.cpp.
References assert(), CGOptLevel, llvm::Target::createTargetMachine(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::SubtargetFeatures::getString(), llvm::TargetRegistry::lookupTarget(), MAttr, MCpu, Options, RelocModel, llvm::report_fatal_error(), and TheTriple.
Member Data Documentation
CGOptLevel
CodeGenOptLevel llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::CGOptLevel = CodeGenOptLevel::Aggressive
Definition at line 49 of file ThinLTOCodeGenerator.h.
Referenced by create().
MAttr
std::string llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::MAttr
Definition at line 46 of file ThinLTOCodeGenerator.h.
Referenced by create().
MCpu
std::string llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::MCpu
Definition at line 45 of file ThinLTOCodeGenerator.h.
Referenced by create(), and initTMBuilder().
Options
TargetOptions llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::Options
Definition at line 47 of file ThinLTOCodeGenerator.h.
Referenced by create().
RelocModel
std::optional<Reloc::Model> llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::RelocModel
Definition at line 48 of file ThinLTOCodeGenerator.h.
Referenced by create().
TheTriple
Triple llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::TheTriple
Definition at line 44 of file ThinLTOCodeGenerator.h.
Referenced by create(), and initTMBuilder().
The documentation for this struct was generated from the following files:
include/llvm/LTO/legacy/ThinLTOCodeGenerator.h
lib/LTO/ThinLTOCodeGenerator.cpp