LLVM: llvm::ArgDescriptor Struct Reference
llvm::ArgDescriptor Struct Reference
#include "Target/AMDGPU/AMDGPUArgumentUsageInfo.h"
Public Member Functions
ArgDescriptor (unsigned Val=0, unsigned Mask=~0u, bool IsStack=false, bool IsSet=false)
bool isSet () const
operator bool () const
bool isRegister () const
MCRegister getRegister () const
unsigned getStackOffset () const
unsigned getMask () const
bool isMasked () const
void print (raw_ostream &OS, const TargetRegisterInfo *TRI=nullptr) const
Static Public Member Functions
static ArgDescriptor createRegister (Register Reg, unsigned Mask=~0u)
static ArgDescriptor createStack (unsigned Offset, unsigned Mask=~0u)
static ArgDescriptor createArg (const ArgDescriptor &Arg, unsigned Mask)
Friends
struct AMDGPUFunctionArgInfo
class AMDGPUArgumentUsageInfo
Detailed Description
Definition at line 25 of file AMDGPUArgumentUsageInfo.h.
Constructor & Destructor Documentation
ArgDescriptor()
llvm::ArgDescriptor::ArgDescriptor (unsigned Val = 0, unsigned Mask = ~0u, bool IsStack = false, bool IsSet = false) inline
Definition at line 42 of file AMDGPUArgumentUsageInfo.h.
References Reg.
Referenced by createArg(), createRegister(), and createStack().
Member Function Documentation
createArg()
ArgDescriptor llvm::ArgDescriptor::createArg (const ArgDescriptor & Arg, unsigned Mask) inline static
Definition at line 54 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor(), and Reg.
Referenced by allocateVGPR32Input(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::AMDGPUCallLowering::passSpecialInputs(), and llvm::SITargetLowering::passSpecialInputs().
createRegister()
ArgDescriptor llvm::ArgDescriptor::createRegister (Register Reg, unsigned Mask = ~0u) inline static
Definition at line 46 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor(), and Reg.
Referenced by llvm::SIMachineFunctionInfo::addDispatchID(), llvm::SIMachineFunctionInfo::addDispatchPtr(), llvm::SIMachineFunctionInfo::addFlatScratchInit(), llvm::SIMachineFunctionInfo::addImplicitBufferPtr(), llvm::SIMachineFunctionInfo::addKernargSegmentPtr(), llvm::SIMachineFunctionInfo::addLDSKernelId(), llvm::SIMachineFunctionInfo::addPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::addPrivateSegmentSize(), llvm::SIMachineFunctionInfo::addPrivateSegmentWaveByteOffset(), llvm::SIMachineFunctionInfo::addQueuePtr(), llvm::SIMachineFunctionInfo::addWorkGroupIDX(), llvm::SIMachineFunctionInfo::addWorkGroupIDY(), llvm::SIMachineFunctionInfo::addWorkGroupIDZ(), llvm::SIMachineFunctionInfo::addWorkGroupInfo(), allocateSGPR32InputImpl(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), llvm::SITargetLowering::allocateSpecialInputVGPRsFixed(), allocateVGPR32Input(), llvm::AMDGPUFunctionArgInfo::fixedABILayout(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::SIMachineFunctionInfo::setPrivateSegmentWaveByteOffset(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
createStack()
ArgDescriptor llvm::ArgDescriptor::createStack (unsigned Offset, unsigned Mask = ~0u) inline static
Definition at line 50 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor(), and llvm::Offset.
Referenced by allocateVGPR32Input(), and llvm::GCNTargetMachine::parseMachineFunctionInfo().
getMask()
unsigned llvm::ArgDescriptor::getMask () const inline
Definition at line 80 of file AMDGPUArgumentUsageInfo.h.
References assert().
Referenced by llvm::AMDGPULegalizerInfo::buildLoadInputValue(), and llvm::AMDGPUTargetLowering::loadInputValue().
getRegister()
MCRegister llvm::ArgDescriptor::getRegister () const inline
Definition at line 70 of file AMDGPUArgumentUsageInfo.h.
References assert(), and Reg.
Referenced by allocateSGPR32Input(), allocateSGPR64Input(), llvm::AMDGPULegalizerInfo::buildLoadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), and llvm::AMDGPUCallLowering::passSpecialInputs().
getStackOffset()
unsigned llvm::ArgDescriptor::getStackOffset () const inline
Definition at line 75 of file AMDGPUArgumentUsageInfo.h.
References assert(), and StackOffset.
Referenced by llvm::AMDGPUTargetLowering::loadInputValue().
isMasked()
bool llvm::ArgDescriptor::isMasked () const inline
Definition at line 86 of file AMDGPUArgumentUsageInfo.h.
Referenced by llvm::AMDGPULegalizerInfo::buildLoadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), llvm::AMDGPUCallLowering::passSpecialInputs(), and llvm::SITargetLowering::passSpecialInputs().
isRegister()
bool llvm::ArgDescriptor::isRegister () const inline
Definition at line 66 of file AMDGPUArgumentUsageInfo.h.
Referenced by llvm::AMDGPUTargetLowering::loadInputValue(), and llvm::AMDGPUCallLowering::passSpecialInputs().
isSet()
bool llvm::ArgDescriptor::isSet () const inline
Definition at line 58 of file AMDGPUArgumentUsageInfo.h.
Referenced by operator bool().
operator bool()
llvm::ArgDescriptor::operator bool () const inline explicit
Definition at line 62 of file AMDGPUArgumentUsageInfo.h.
References isSet().
print()
void llvm::ArgDescriptor::print (raw_ostream & OS, const TargetRegisterInfo * TRI = nullptr) const
References TRI.
Referenced by llvm::operator<<().
Friends And Related Symbol Documentation
AMDGPUArgumentUsageInfo
friend class AMDGPUArgumentUsageInfo friend
Definition at line 28 of file AMDGPUArgumentUsageInfo.h.
References AMDGPUArgumentUsageInfo.
Referenced by AMDGPUArgumentUsageInfo.
AMDGPUFunctionArgInfo
friend struct AMDGPUFunctionArgInfo friend
Definition at line 27 of file AMDGPUArgumentUsageInfo.h.
References AMDGPUFunctionArgInfo.
Referenced by AMDGPUFunctionArgInfo.
Member Data Documentation
Reg
MCRegister llvm::ArgDescriptor::Reg
Definition at line 31 of file AMDGPUArgumentUsageInfo.h.
Referenced by ArgDescriptor(), createArg(), createRegister(), and getRegister().
StackOffset
unsigned llvm::ArgDescriptor::StackOffset
Definition at line 32 of file AMDGPUArgumentUsageInfo.h.
Referenced by getStackOffset().
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.h