LLVM: llvm::objcopy::elf::SRecord Struct Reference
llvm::objcopy::elf::SRecord Struct Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Types
enum Type : uint8_t {
S0 = 0 , S1 = 1 , S2 = 2 , S3 = 3 ,
S4 = 4 , S5 = 5 , S6 = 6 , S7 = 7 ,
S8 = 8 , S9 = 9
}
Public Member Functions
SRecLineData toString () const
uint8_t getCount () const
uint8_t getAddressSize () const
uint8_t getChecksum () const
size_t getSize () const
Static Public Member Functions
static SRecord getHeader (StringRef FileName)
static uint8_t getType (uint32_t Address)
Public Attributes
uint8_t Type
uint32_t Address
ArrayRef< uint8_t > Data
Detailed Description
Definition at line 421 of file ELFObject.h.
Member Enumeration Documentation
Type
enum llvm::objcopy::elf::SRecord::Type : uint8_t
Enumerator
S0
S1
S2
S3
S4
S5
S6
S7
S8
S9
Definition at line 434 of file ELFObject.h.
Member Function Documentation
getAddressSize()
uint8_t SRecord::getAddressSize () const
Definition at line 2977 of file ELFObject.cpp.
References S2, S3, S7, and S8.
Referenced by getCount(), getSize(), and toString().
getChecksum()
uint8_t SRecord::getChecksum () const
Definition at line 2961 of file ELFObject.cpp.
References Address, Data, and getCount().
Referenced by toString().
getCount()
uint8_t SRecord::getCount () const
Definition at line 2992 of file ELFObject.cpp.
References Data, llvm::DataSize, and getAddressSize().
Referenced by getChecksum(), and toString().
getHeader()
SRecord SRecord::getHeader (StringRef FileName) static
Definition at line 3006 of file ELFObject.cpp.
References Data, llvm::StringRef::data(), S0, llvm::StringRef::size(), and llvm::StringRef::slice().
getSize()
size_t SRecord::getSize () const
Definition at line 2972 of file ELFObject.cpp.
References Data, and getAddressSize().
Referenced by toString().
getType()
uint8_t SRecord::getType (uint32_t Address) static
Definition at line 2998 of file ELFObject.cpp.
References Address, llvm::isUInt(), S1, S2, and S3.
Referenced by llvm::objcopy::elf::SRECSectionWriterBase::writeRecords(), and llvm::objcopy::elf::SRECSectionWriterBase::writeSection().
toString()
SRecLineData SRecord::toString () const
Definition at line 2941 of file ELFObject.cpp.
References Address, assert(), Data, getAddressSize(), getChecksum(), getCount(), getSize(), toHexStr(), and X.
Member Data Documentation
Address
uint32_t llvm::objcopy::elf::SRecord::Address
Definition at line 423 of file ELFObject.h.
Referenced by getChecksum(), getType(), and toString().
Data
ArrayRef<uint8_t> llvm::objcopy::elf::SRecord::Data
Definition at line 424 of file ELFObject.h.
Referenced by getChecksum(), getCount(), getHeader(), getSize(), and toString().
Type
uint8_t llvm::objcopy::elf::SRecord::Type
Definition at line 422 of file ELFObject.h.
The documentation for this struct was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp