LLVM: llvm::CriticalEdgeSplittingOptions Struct Reference
llvm::CriticalEdgeSplittingOptions Struct Reference
Option class for critical edge splitting.
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Public Member Functions
CriticalEdgeSplittingOptions (DominatorTree *DT=nullptr, LoopInfo *LI=nullptr, MemorySSAUpdater *MSSAU=nullptr, PostDominatorTree *PDT=nullptr)
CriticalEdgeSplittingOptions & setMergeIdenticalEdges ()
CriticalEdgeSplittingOptions & setKeepOneInputPHIs ()
CriticalEdgeSplittingOptions & setPreserveLCSSA ()
CriticalEdgeSplittingOptions & setIgnoreUnreachableDests ()
CriticalEdgeSplittingOptions & unsetPreserveLoopSimplify ()
Public Attributes
DominatorTree * DT
PostDominatorTree * PDT
LoopInfo * LI
MemorySSAUpdater * MSSAU
bool MergeIdenticalEdges = false
bool KeepOneInputPHIs = false
bool PreserveLCSSA = false
bool IgnoreUnreachableDests = false
bool PreserveLoopSimplify = true
SplitCriticalEdge is guaranteed to preserve loop-simplify form if LI is provided.
Detailed Description
Option class for critical edge splitting.
This provides a builder interface for overriding the default options used during critical edge splitting.
Definition at line 149 of file BasicBlockUtils.h.
Constructor & Destructor Documentation
CriticalEdgeSplittingOptions()
llvm::CriticalEdgeSplittingOptions::CriticalEdgeSplittingOptions (DominatorTree * DT = nullptr, LoopInfo * LI = nullptr, MemorySSAUpdater * MSSAU = nullptr, PostDominatorTree * PDT = nullptr) inline
Definition at line 163 of file BasicBlockUtils.h.
References DT, LI, MSSAU, and PDT.
Referenced by setIgnoreUnreachableDests(), setKeepOneInputPHIs(), setMergeIdenticalEdges(), setPreserveLCSSA(), and unsetPreserveLoopSimplify().
Member Function Documentation
setIgnoreUnreachableDests()
CriticalEdgeSplittingOptions & llvm::CriticalEdgeSplittingOptions::setIgnoreUnreachableDests () inline
Definition at line 184 of file BasicBlockUtils.h.
References CriticalEdgeSplittingOptions(), and IgnoreUnreachableDests.
setKeepOneInputPHIs()
CriticalEdgeSplittingOptions & llvm::CriticalEdgeSplittingOptions::setKeepOneInputPHIs () inline
Definition at line 174 of file BasicBlockUtils.h.
References CriticalEdgeSplittingOptions(), and KeepOneInputPHIs.
setMergeIdenticalEdges()
CriticalEdgeSplittingOptions & llvm::CriticalEdgeSplittingOptions::setMergeIdenticalEdges () inline
Definition at line 169 of file BasicBlockUtils.h.
References CriticalEdgeSplittingOptions(), and MergeIdenticalEdges.
setPreserveLCSSA()
CriticalEdgeSplittingOptions & llvm::CriticalEdgeSplittingOptions::setPreserveLCSSA () inline
Definition at line 179 of file BasicBlockUtils.h.
References CriticalEdgeSplittingOptions(), and PreserveLCSSA.
Referenced by llvm::SplitEdge().
unsetPreserveLoopSimplify()
CriticalEdgeSplittingOptions & llvm::CriticalEdgeSplittingOptions::unsetPreserveLoopSimplify () inline
Definition at line 189 of file BasicBlockUtils.h.
References CriticalEdgeSplittingOptions(), and PreserveLoopSimplify.
Member Data Documentation
DT
DominatorTree* llvm::CriticalEdgeSplittingOptions::DT
Definition at line 150 of file BasicBlockUtils.h.
Referenced by CriticalEdgeSplittingOptions().
IgnoreUnreachableDests
bool llvm::CriticalEdgeSplittingOptions::IgnoreUnreachableDests = false
Definition at line 157 of file BasicBlockUtils.h.
Referenced by setIgnoreUnreachableDests().
KeepOneInputPHIs
bool llvm::CriticalEdgeSplittingOptions::KeepOneInputPHIs = false
Definition at line 155 of file BasicBlockUtils.h.
Referenced by setKeepOneInputPHIs().
LI
LoopInfo* llvm::CriticalEdgeSplittingOptions::LI
Definition at line 152 of file BasicBlockUtils.h.
Referenced by CriticalEdgeSplittingOptions().
MergeIdenticalEdges
bool llvm::CriticalEdgeSplittingOptions::MergeIdenticalEdges = false
Definition at line 154 of file BasicBlockUtils.h.
Referenced by setMergeIdenticalEdges().
MSSAU
MemorySSAUpdater* llvm::CriticalEdgeSplittingOptions::MSSAU
Definition at line 153 of file BasicBlockUtils.h.
Referenced by CriticalEdgeSplittingOptions().
PDT
PostDominatorTree* llvm::CriticalEdgeSplittingOptions::PDT
Definition at line 151 of file BasicBlockUtils.h.
Referenced by CriticalEdgeSplittingOptions().
PreserveLCSSA
bool llvm::CriticalEdgeSplittingOptions::PreserveLCSSA = false
Definition at line 156 of file BasicBlockUtils.h.
Referenced by setPreserveLCSSA().
PreserveLoopSimplify
bool llvm::CriticalEdgeSplittingOptions::PreserveLoopSimplify = true
SplitCriticalEdge is guaranteed to preserve loop-simplify form if LI is provided.
If it cannot be preserved, no splitting will take place. If it is not set, preserve loop-simplify form if possible.
Definition at line 161 of file BasicBlockUtils.h.
Referenced by unsetPreserveLoopSimplify().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/Utils/BasicBlockUtils.h