LLVM: llvm::AArch64::ExtensionSet Struct Reference
llvm::AArch64::ExtensionSet Struct Reference
#include "llvm/TargetParser/AArch64TargetParser.h"
Public Member Functions
ExtensionSet ()
LLVM_ABI void enable (ArchExtKind E)
LLVM_ABI void disable (ArchExtKind E)
LLVM_ABI void addCPUDefaults (const CpuInfo &CPU)
LLVM_ABI void addArchDefaults (const ArchInfo &Arch)
LLVM_ABI bool parseModifier (StringRef Modifier, const bool AllowNoDashForm=false)
LLVM_ABI void reconstructFromParsedFeatures (const std::vector< std::string > &Features, std::vector< std::string > &NonExtensions)
template<typename T>
void toLLVMFeatureList (std::vector< T > &Features) const
LLVM_ABI void dump () const
Public Attributes
ExtensionBitset Enabled
ExtensionBitset Touched
const ArchInfo * BaseArch
Detailed Description
Definition at line 171 of file AArch64TargetParser.h.
Constructor & Destructor Documentation
ExtensionSet()
llvm::AArch64::ExtensionSet::ExtensionSet () inline
Definition at line 181 of file AArch64TargetParser.h.
References BaseArch, Enabled, and Touched.
Member Function Documentation
addArchDefaults()
void AArch64::ExtensionSet::addArchDefaults (const ArchInfo & Arch)
Definition at line 344 of file AArch64TargetParser.cpp.
References BaseArch, llvm::dbgs(), llvm::AArch64::ArchInfo::DefaultExts, enable(), Extensions, LLVM_DEBUG, llvm::AArch64::ArchInfo::Name, and llvm::Bitset< NumBits >::test().
addCPUDefaults()
void AArch64::ExtensionSet::addCPUDefaults (const CpuInfo & CPU)
Definition at line 334 of file AArch64TargetParser.cpp.
References BaseArch, llvm::dbgs(), enable(), Extensions, LLVM_DEBUG, and llvm::Bitset< NumBits >::test().
disable()
void AArch64::ExtensionSet::disable (ArchExtKind E)
Definition at line 284 of file AArch64TargetParser.cpp.
References llvm::dbgs(), disable(), Enabled, LLVM_DEBUG, lookupExtensionByID(), and Touched.
Referenced by disable(), and parseModifier().
dump()
void AArch64::ExtensionSet::dump () const
Definition at line 396 of file AArch64TargetParser.cpp.
References F, llvm::outs(), and toLLVMFeatureList().
enable()
void AArch64::ExtensionSet::enable (ArchExtKind E)
Definition at line 252 of file AArch64TargetParser.cpp.
References BaseArch, llvm::dbgs(), enable(), Enabled, LLVM_DEBUG, lookupExtensionByID(), and Touched.
Referenced by addArchDefaults(), addCPUDefaults(), enable(), llvm::AArch64::getCpuSupportsMask(), llvm::AArch64::getFMVPriority(), and parseModifier().
parseModifier()
bool AArch64::ExtensionSet::parseModifier (StringRef Modifier, const bool AllowNoDashForm = false)
Definition at line 353 of file AArch64TargetParser.cpp.
References llvm::dbgs(), disable(), llvm::StringRef::drop_front(), enable(), LLVM_DEBUG, llvm::AArch64::parseArchExtension(), and llvm::StringRef::starts_with().
reconstructFromParsedFeatures()
void AArch64::ExtensionSet::reconstructFromParsedFeatures (const std::vector< std::string > & Features, std::vector< std::string > & NonExtensions)
Definition at line 378 of file AArch64TargetParser.cpp.
References assert(), Enabled, F, llvm::AArch64::targetFeatureToExtension(), and Touched.
toLLVMFeatureList()
template<typename T> void llvm::AArch64::ExtensionSet::toLLVMFeatureList (std::vector< T > & Features) const inline
Definition at line 219 of file AArch64TargetParser.h.
References BaseArch, E(), Enabled, Extensions, T, and Touched.
Referenced by dump().
Member Data Documentation
BaseArch
const ArchInfo* llvm::AArch64::ExtensionSet::BaseArch
Definition at line 179 of file AArch64TargetParser.h.
Referenced by addArchDefaults(), addCPUDefaults(), enable(), ExtensionSet(), and toLLVMFeatureList().
Enabled
ExtensionBitset llvm::AArch64::ExtensionSet::Enabled
Definition at line 173 of file AArch64TargetParser.h.
Referenced by disable(), enable(), ExtensionSet(), llvm::AArch64::getCpuSupportsMask(), llvm::AArch64::getFMVPriority(), reconstructFromParsedFeatures(), and toLLVMFeatureList().
Touched
ExtensionBitset llvm::AArch64::ExtensionSet::Touched
Definition at line 176 of file AArch64TargetParser.h.
Referenced by disable(), enable(), ExtensionSet(), reconstructFromParsedFeatures(), and toLLVMFeatureList().
The documentation for this struct was generated from the following files:
include/llvm/TargetParser/AArch64TargetParser.h
lib/TargetParser/AArch64TargetParser.cpp