LLVM: llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain > Struct Template Reference
llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain > Struct Template Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Member Functions
UnaryOpc_match (unsigned Opc, const Opnd_P &Op, std::optional< SDNodeFlags > Flgs=std::nullopt)
template<typename MatchContext>
bool match (const MatchContext &Ctx, SDValue N)
Public Attributes
unsigned Opcode
Opnd_P Opnd
std::optional< SDNodeFlags > Flags
Detailed Description
template<typename Opnd_P, bool ExcludeChain = false>
struct llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >
Definition at line 939 of file SDPatternMatch.h.
Constructor & Destructor Documentation
UnaryOpc_match()
template<typename Opnd_P, bool ExcludeChain = false> llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::UnaryOpc_match (unsigned Opc, const Opnd_P & Op, std::optional< SDNodeFlags > Flgs = std::nullopt) inline
Definition at line 943 of file SDPatternMatch.h.
References Flags, Opc, Opcode, and Opnd.
Member Function Documentation
match()
template<typename Opnd_P, bool ExcludeChain = false> template<typename MatchContext> bool llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 948 of file SDPatternMatch.h.
References assert(), llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::FirstIndex, Flags, llvm::SDPatternMatch::m_Opc(), N, Opcode, Opnd, llvm::SDPatternMatch::sd_context_match(), and llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::Size.
Member Data Documentation
Flags
template<typename Opnd_P, bool ExcludeChain = false> std::optional<SDNodeFlags> llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::Flags
Definition at line 942 of file SDPatternMatch.h.
Referenced by match(), and UnaryOpc_match().
Opcode
template<typename Opnd_P, bool ExcludeChain = false> unsigned llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::Opcode
Definition at line 940 of file SDPatternMatch.h.
Referenced by match(), and UnaryOpc_match().
Opnd
template<typename Opnd_P, bool ExcludeChain = false> Opnd_P llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::Opnd
Definition at line 941 of file SDPatternMatch.h.
Referenced by match(), and UnaryOpc_match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h