LLVM: llvm::DXILResourceMap::call_iterator Struct Reference
llvm::DXILResourceMap::call_iterator Struct Reference
#include "llvm/Analysis/DXILResource.h"
Public Member Functions
call_iterator ()=default
call_iterator (CallMapTy::iterator Iter)
CallInst * operator* () const
Public Member Functions inherited from llvm::iterator_adaptor_base< call_iterator, CallMapTy::iterator >
call_iterator & operator+= (difference_type n)
call_iterator & operator-= (difference_type n)
difference_type operator- (const call_iterator &RHS) const
call_iterator & operator++ ()
call_iterator & operator-- ()
std::conditional_t< std::is_same< typename std::iterator_traits< CallMapTy::iterator >::value_type, typename std::iterator_traits< CallMapTy::iterator >::value_type >::value, typename std::iterator_traits< CallMapTy::iterator >::reference, typename std::iterator_traits< CallMapTy::iterator >::value_type & > operator* () const
Public Member Functions inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
DerivedT operator+ (DifferenceTypeT n) const
DerivedT operator- (DifferenceTypeT n) const
DerivedT & operator++ ()
DerivedT operator++ (int)
DerivedT & operator-- ()
DerivedT operator-- (int)
bool operator!= (const DerivedT &RHS) const
bool operator> (const DerivedT &RHS) const
bool operator<= (const DerivedT &RHS) const
bool operator>= (const DerivedT &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (DifferenceTypeT n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_adaptor_base< call_iterator, CallMapTy::iterator >
using difference_type
Public Types inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
using iterator_category = IteratorCategoryT
using value_type = T
using difference_type = DifferenceTypeT
using pointer = PointerT
using reference = ReferenceT
Protected Types inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
enum { IsRandomAccess , IsBidirectional }
Protected Member Functions inherited from llvm::iterator_adaptor_base< call_iterator, CallMapTy::iterator >
iterator_adaptor_base ()=default
const CallMapTy::iterator & wrapped () const
Protected Attributes inherited from llvm::iterator_adaptor_base< call_iterator, CallMapTy::iterator >
CallMapTy::iterator I
Detailed Description
Definition at line 550 of file DXILResource.h.
Constructor & Destructor Documentation
call_iterator() [1/2]
llvm::DXILResourceMap::call_iterator::call_iterator () default
Referenced by call_iterator().
call_iterator() [2/2]
llvm::DXILResourceMap::call_iterator::call_iterator (CallMapTy::iterator Iter) inline
Definition at line 553 of file DXILResource.h.
References call_iterator(), llvm::iterator_adaptor_base< call_iterator, CallMapTy::iterator >::iterator_adaptor_base(), and llvm::move().
Member Function Documentation
operator*()
CallInst * llvm::DXILResourceMap::call_iterator::operator* () const inline
Definition at line 556 of file DXILResource.h.
References llvm::iterator_adaptor_base< call_iterator, CallMapTy::iterator >::I.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/DXILResource.h