LLVM: llvm::memprof::IndexedCallSiteInfo Struct Reference
llvm::memprof::IndexedCallSiteInfo Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
IndexedCallSiteInfo ()=default
IndexedCallSiteInfo (CallStackId CSId)
IndexedCallSiteInfo (CallStackId CSId, SmallVector< GlobalValue::GUID, 1 > CalleeGuids)
bool operator== (const IndexedCallSiteInfo &Other) const
bool operator!= (const IndexedCallSiteInfo &Other) const
Public Attributes
CallStackId CSId = 0
SmallVector< GlobalValue::GUID, 1 > CalleeGuids
Detailed Description
Definition at line 362 of file MemProf.h.
Constructor & Destructor Documentation
IndexedCallSiteInfo() [1/3]
llvm::memprof::IndexedCallSiteInfo::IndexedCallSiteInfo () default
Referenced by operator!=(), and operator==().
IndexedCallSiteInfo() [2/3]
llvm::memprof::IndexedCallSiteInfo::IndexedCallSiteInfo (CallStackId CSId) inline
Definition at line 369 of file MemProf.h.
References CSId.
IndexedCallSiteInfo() [3/3]
llvm::memprof::IndexedCallSiteInfo::IndexedCallSiteInfo (CallStackId CSId, SmallVector< GlobalValue::GUID, 1 > CalleeGuids) inline
Definition at line 370 of file MemProf.h.
References CalleeGuids, CSId, and llvm::move().
Member Function Documentation
operator!=()
bool llvm::memprof::IndexedCallSiteInfo::operator!= (const IndexedCallSiteInfo & Other) const inline
Definition at line 378 of file MemProf.h.
References IndexedCallSiteInfo(), operator==(), and llvm::Other.
operator==()
bool llvm::memprof::IndexedCallSiteInfo::operator== (const IndexedCallSiteInfo & Other) const inline
Definition at line 374 of file MemProf.h.
References CalleeGuids, CSId, IndexedCallSiteInfo(), and llvm::Other.
Member Data Documentation
CalleeGuids
SmallVector<GlobalValue::GUID, 1> llvm::memprof::IndexedCallSiteInfo::CalleeGuids
Definition at line 366 of file MemProf.h.
Referenced by IndexedCallSiteInfo(), and operator==().
CSId
CallStackId llvm::memprof::IndexedCallSiteInfo::CSId = 0
Definition at line 364 of file MemProf.h.
Referenced by IndexedCallSiteInfo(), IndexedCallSiteInfo(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h