LLVM: llvm::DWARFTypePrinter< DieType > Struct Template Reference
llvm::DWARFTypePrinter< DieType > Struct Template Reference
#include "llvm/DebugInfo/DWARF/DWARFTypePrinter.h"
Public Member Functions
DWARFTypePrinter (raw_ostream &OS)
void appendTypeTagName (dwarf::Tag T)
Dump the name encoded in the type tag.
void appendArrayType (const DieType &D)
DieType skipQualifiers (DieType D)
bool needsParens (DieType D)
void appendPointerLikeTypeBefore (DieType D, DieType Inner, StringRef Ptr)
DieType appendUnqualifiedNameBefore (DieType D, std::string *OriginalFullName=nullptr)
void appendUnqualifiedNameAfter (DieType D, DieType Inner, bool SkipFirstParamIfArtificial=false)
void appendQualifiedName (DieType D)
DieType appendQualifiedNameBefore (DieType D)
bool appendTemplateParameters (DieType D, bool *FirstParameter=nullptr)
void appendAndTerminateTemplateParameters (DieType D)
void decomposeConstVolatile (DieType &N, DieType &T, DieType &C, DieType &V)
void appendConstVolatileQualifierAfter (DieType N)
void appendConstVolatileQualifierBefore (DieType N)
void appendUnqualifiedName (DieType D, std::string *OriginalFullName=nullptr)
Recursively append the DIE type name when applicable.
void appendSubroutineNameAfter (DieType D, DieType Inner, bool SkipFirstParamIfArtificial, bool Const, bool Volatile)
void appendScopes (DieType D)
Public Attributes
raw_ostream & OS
bool Word = true
bool EndedWithTemplate = false
Detailed Description
template<typename DieType>
struct llvm::DWARFTypePrinter< DieType >
Definition at line 25 of file DWARFTypePrinter.h.
Constructor & Destructor Documentation
DWARFTypePrinter()
template<typename DieType> llvm::DWARFTypePrinter< DieType >::DWARFTypePrinter (raw_ostream & OS) inline
Definition at line 30 of file DWARFTypePrinter.h.
References OS.
Member Function Documentation
appendAndTerminateTemplateParameters()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendAndTerminateTemplateParameters (DieType D)
Definition at line 569 of file DWARFTypePrinter.h.
References appendTemplateParameters(), D(), EndedWithTemplate, OS, and Word.
appendArrayType()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendArrayType (const DieType & D)
Definition at line 96 of file DWARFTypePrinter.h.
References llvm::CallingConv::C, llvm::Count, D(), EndedWithTemplate, and OS.
Referenced by appendUnqualifiedNameAfter().
appendConstVolatileQualifierAfter()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendConstVolatileQualifierAfter (DieType N)
Definition at line 600 of file DWARFTypePrinter.h.
References appendSubroutineNameAfter(), appendUnqualifiedNameAfter(), llvm::CallingConv::C, decomposeConstVolatile(), N, llvm::detail::resolveReferencedType(), and T.
Referenced by appendUnqualifiedNameAfter().
appendConstVolatileQualifierBefore()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendConstVolatileQualifierBefore (DieType N)
Definition at line 613 of file DWARFTypePrinter.h.
References A(), appendQualifiedNameBefore(), llvm::CallingConv::C, decomposeConstVolatile(), N, OS, llvm::detail::resolveReferencedType(), T, and Word.
Referenced by appendUnqualifiedNameBefore().
appendPointerLikeTypeBefore()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendPointerLikeTypeBefore (DieType D, DieType Inner, StringRef Ptr)
Definition at line 182 of file DWARFTypePrinter.h.
References appendQualifiedNameBefore(), D(), EndedWithTemplate, needsParens(), OS, Ptr, and Word.
Referenced by appendUnqualifiedNameBefore().
appendQualifiedName()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendQualifiedName (DieType D)
Definition at line 403 of file DWARFTypePrinter.h.
References appendScopes(), appendUnqualifiedName(), and D().
Referenced by appendSubroutineNameAfter(), appendTemplateParameters(), appendUnqualifiedNameBefore(), and llvm::dumpTypeQualifiedName().
appendQualifiedNameBefore()
template<typename DieType> DieType llvm::DWARFTypePrinter< DieType >::appendQualifiedNameBefore (DieType D)
Definition at line 410 of file DWARFTypePrinter.h.
References appendScopes(), appendUnqualifiedNameBefore(), and D().
Referenced by appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), and appendUnqualifiedNameBefore().
appendScopes()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendScopes (DieType D)
Definition at line 781 of file DWARFTypePrinter.h.
References appendScopes(), appendUnqualifiedName(), D(), OS, and P.
Referenced by appendQualifiedName(), appendQualifiedNameBefore(), and appendScopes().
appendSubroutineNameAfter()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendSubroutineNameAfter (DieType D, DieType Inner, bool SkipFirstParamIfArtificial, bool Const, bool Volatile)
Definition at line 655 of file DWARFTypePrinter.h.
References appendQualifiedName(), appendUnqualifiedNameAfter(), D(), EndedWithTemplate, llvm::First, OS, P, llvm::detail::resolveReferencedType(), and T.
Referenced by appendConstVolatileQualifierAfter(), and appendUnqualifiedNameAfter().
appendTemplateParameters()
template<typename DieType> bool llvm::DWARFTypePrinter< DieType >::appendTemplateParameters (DieType D, bool * FirstParameter = nullptr)
Definition at line 417 of file DWARFTypePrinter.h.
References appendQualifiedName(), appendTemplateParameters(), assert(), llvm::CallingConv::C, D(), EndedWithTemplate, llvm::format(), OS, llvm::detail::resolveReferencedType(), T, llvm::detail::toString(), and TypeAttr.
Referenced by appendAndTerminateTemplateParameters(), appendTemplateParameters(), and appendUnqualifiedNameBefore().
appendTypeTagName()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendTypeTagName (dwarf::Tag T)
Dump the name encoded in the type tag.
Definition at line 84 of file DWARFTypePrinter.h.
References llvm::StringRef::ends_with(), OS, llvm::StringRef::size(), llvm::StringRef::starts_with(), llvm::StringRef::substr(), and T.
Referenced by appendUnqualifiedNameBefore().
appendUnqualifiedName()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendUnqualifiedName (DieType D, std::string * OriginalFullName = nullptr)
Recursively append the DIE type name when applicable.
Definition at line 646 of file DWARFTypePrinter.h.
References appendUnqualifiedNameAfter(), appendUnqualifiedNameBefore(), and D().
Referenced by appendQualifiedName(), appendScopes(), and llvm::dumpTypeUnqualifiedName().
appendUnqualifiedNameAfter()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameAfter (DieType D, DieType Inner, bool SkipFirstParamIfArtificial = false)
Definition at line 314 of file DWARFTypePrinter.h.
References appendArrayType(), appendConstVolatileQualifierAfter(), appendSubroutineNameAfter(), appendUnqualifiedNameAfter(), D(), needsParens(), OS, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::detail::resolveReferencedType(), llvm::raw_string_ostream::str(), and llvm::utohexstr().
Referenced by appendConstVolatileQualifierAfter(), appendSubroutineNameAfter(), appendUnqualifiedName(), and appendUnqualifiedNameAfter().
appendUnqualifiedNameBefore()
template<typename DieType> DieType llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameBefore (DieType D, std::string * OriginalFullName = nullptr)
Definition at line 196 of file DWARFTypePrinter.h.
References appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), appendQualifiedName(), appendQualifiedNameBefore(), appendTemplateParameters(), appendTypeTagName(), assert(), D(), EndedWithTemplate, needsParens(), llvm::StringRef::npos, OS, llvm::detail::resolveReferencedType(), T, llvm::detail::toString(), and Word.
Referenced by appendQualifiedNameBefore(), and appendUnqualifiedName().
decomposeConstVolatile()
template<typename DieType> void llvm::DWARFTypePrinter< DieType >::decomposeConstVolatile (DieType & N, DieType & T, DieType & C, DieType & V)
Definition at line 583 of file DWARFTypePrinter.h.
References llvm::CallingConv::C, N, llvm::detail::resolveReferencedType(), T, and llvm::Tag.
Referenced by appendConstVolatileQualifierAfter(), and appendConstVolatileQualifierBefore().
needsParens()
template<typename DieType> bool llvm::DWARFTypePrinter< DieType >::needsParens (DieType D)
Definition at line 175 of file DWARFTypePrinter.h.
References D(), and skipQualifiers().
Referenced by appendPointerLikeTypeBefore(), appendUnqualifiedNameAfter(), and appendUnqualifiedNameBefore().
skipQualifiers()
template<typename DieType> DieType llvm::DWARFTypePrinter< DieType >::skipQualifiers (DieType D)
Definition at line 167 of file DWARFTypePrinter.h.
References D(), and llvm::detail::resolveReferencedType().
Referenced by needsParens().
Member Data Documentation
EndedWithTemplate
template<typename DieType> bool llvm::DWARFTypePrinter< DieType >::EndedWithTemplate = false
Definition at line 28 of file DWARFTypePrinter.h.
Referenced by appendAndTerminateTemplateParameters(), appendArrayType(), appendPointerLikeTypeBefore(), appendSubroutineNameAfter(), appendTemplateParameters(), and appendUnqualifiedNameBefore().
OS
template<typename DieType> raw_ostream& llvm::DWARFTypePrinter< DieType >::OS
Definition at line 26 of file DWARFTypePrinter.h.
Referenced by appendAndTerminateTemplateParameters(), appendArrayType(), appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), appendScopes(), appendSubroutineNameAfter(), appendTemplateParameters(), appendTypeTagName(), appendUnqualifiedNameAfter(), appendUnqualifiedNameBefore(), and DWARFTypePrinter().
Word
template<typename DieType> bool llvm::DWARFTypePrinter< DieType >::Word = true
Definition at line 27 of file DWARFTypePrinter.h.
Referenced by appendAndTerminateTemplateParameters(), appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), and appendUnqualifiedNameBefore().
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFTypePrinter.h