LLVM: llvm::SuffixTreeLeafNode Struct Reference
llvm::SuffixTreeLeafNode Struct Reference
#include "llvm/Support/SuffixTreeNode.h"
Public Member Functions
unsigned getEndIdx () const override
unsigned getSuffixIdx () const
void setSuffixIdx (unsigned Idx)
Sets the start index of the suffix represented by this leaf to Idx.
SuffixTreeLeafNode (unsigned StartIdx, unsigned *EndIdx)
virtual ~SuffixTreeLeafNode ()=default
Public Member Functions inherited from llvm::SuffixTreeNode
NodeKind getKind () const
LLVM_ABI unsigned getStartIdx () const
LLVM_ABI unsigned getLeftLeafIdx () const
LLVM_ABI unsigned getRightLeafIdx () const
LLVM_ABI void setLeftLeafIdx (unsigned Idx)
Set the index of the left most leaf node of this node to Idx.
LLVM_ABI void setRightLeafIdx (unsigned Idx)
Set the index of the right most leaf node of this node to Idx.
LLVM_ABI void incrementStartIdx (unsigned Inc)
Advance this node's StartIdx by Inc.
LLVM_ABI void setConcatLen (unsigned Len)
Set the length of the string from the root to this node to Len.
LLVM_ABI unsigned getConcatLen () const
SuffixTreeNode (NodeKind Kind, unsigned StartIdx)
virtual ~SuffixTreeNode ()=default
Static Public Member Functions
static bool classof (const SuffixTreeNode *N)
Additional Inherited Members
Public Types inherited from llvm::SuffixTreeNode
enum class NodeKind { ST_Leaf , ST_Internal }
Static Public Attributes inherited from llvm::SuffixTreeNode
static const unsigned EmptyIdx = -1
Represents an undefined index in the suffix tree.
Detailed Description
Definition at line 162 of file SuffixTreeNode.h.
Constructor & Destructor Documentation
SuffixTreeLeafNode()
llvm::SuffixTreeLeafNode::SuffixTreeLeafNode (unsigned StartIdx, unsigned * EndIdx) inline
Definition at line 189 of file SuffixTreeNode.h.
References llvm::SuffixTreeNode::ST_Leaf, and llvm::SuffixTreeNode::SuffixTreeNode().
~SuffixTreeLeafNode()
virtual llvm::SuffixTreeLeafNode::~SuffixTreeLeafNode () virtual default
Member Function Documentation
classof()
bool llvm::SuffixTreeLeafNode::classof (const SuffixTreeNode * N) inline static
Definition at line 177 of file SuffixTreeNode.h.
References N, llvm::SuffixTreeNode::ST_Leaf, and llvm::SuffixTreeNode::SuffixTreeNode().
getEndIdx()
unsigned SuffixTreeLeafNode::getEndIdx () const override virtual
Returns
the end index of this node's substring in the entire string.
Implements llvm::SuffixTreeNode.
Definition at line 33 of file SuffixTreeNode.cpp.
References assert().
getSuffixIdx()
unsigned SuffixTreeLeafNode::getSuffixIdx () const
Returns
the start index of the suffix represented by this leaf.
Definition at line 38 of file SuffixTreeNode.cpp.
setSuffixIdx()
void SuffixTreeLeafNode::setSuffixIdx (unsigned Idx)
Sets the start index of the suffix represented by this leaf to Idx.
Definition at line 39 of file SuffixTreeNode.cpp.
The documentation for this struct was generated from the following files:
include/llvm/Support/SuffixTreeNode.h
lib/Support/SuffixTreeNode.cpp