LLVM: llvm::memprof::CallSiteInfo Struct Reference
llvm::memprof::CallSiteInfo Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
CallSiteInfo ()=default
CallSiteInfo (std::vector< Frame > Frames)
CallSiteInfo (std::vector< Frame > Frames, SmallVector< GlobalValue::GUID, 1 > CalleeGuids)
bool operator== (const CallSiteInfo &Other) const
bool operator!= (const CallSiteInfo &Other) const
Public Attributes
std::vector< Frame > Frames
SmallVector< GlobalValue::GUID, 1 > CalleeGuids
Detailed Description
Definition at line 497 of file MemProf.h.
Constructor & Destructor Documentation
CallSiteInfo() [1/3]
llvm::memprof::CallSiteInfo::CallSiteInfo () default
Referenced by operator!=(), and operator==().
CallSiteInfo() [2/3]
llvm::memprof::CallSiteInfo::CallSiteInfo (std::vector< Frame > Frames) inline
Definition at line 505 of file MemProf.h.
References Frames, and llvm::move().
CallSiteInfo() [3/3]
llvm::memprof::CallSiteInfo::CallSiteInfo (std::vector< Frame > Frames, SmallVector< GlobalValue::GUID, 1 > CalleeGuids) inline
Definition at line 506 of file MemProf.h.
References CalleeGuids, Frames, and llvm::move().
Member Function Documentation
operator!=()
bool llvm::memprof::CallSiteInfo::operator!= (const CallSiteInfo & Other) const inline
Definition at line 514 of file MemProf.h.
References CallSiteInfo(), operator==(), and llvm::Other.
operator==()
bool llvm::memprof::CallSiteInfo::operator== (const CallSiteInfo & Other) const inline
Definition at line 510 of file MemProf.h.
References CalleeGuids, CallSiteInfo(), Frames, and llvm::Other.
Member Data Documentation
CalleeGuids
SmallVector<GlobalValue::GUID, 1> llvm::memprof::CallSiteInfo::CalleeGuids
Definition at line 502 of file MemProf.h.
Referenced by CallSiteInfo(), llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::CallSiteInfoWithHex64Guids(), llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::denormalize(), and operator==().
Frames
std::vector<Frame> llvm::memprof::CallSiteInfo::Frames
Definition at line 499 of file MemProf.h.
Referenced by CallSiteInfo(), CallSiteInfo(), llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::denormalize(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h