LLVM: llvm::AMDGPUResourceUsageAnalysisImpl Struct Reference
llvm::AMDGPUResourceUsageAnalysisImpl Struct Reference
#include "Target/AMDGPU/AMDGPUResourceUsageAnalysis.h"
Classes
struct SIFunctionResourceInfo
Public Member Functions
SIFunctionResourceInfo analyzeResourceUsage (const MachineFunction &MF, uint32_t AssumedStackSizeForDynamicSizeObjects, uint32_t AssumedStackSizeForExternalCall) const
Static Public Attributes
static char ID
Detailed Description
Definition at line 28 of file AMDGPUResourceUsageAnalysis.h.
Member Function Documentation
analyzeResourceUsage()
AMDGPUResourceUsageAnalysisImpl::SIFunctionResourceInfo AMDGPUResourceUsageAnalysisImpl::analyzeResourceUsage (const MachineFunction & MF, uint32_t AssumedStackSizeForDynamicSizeObjects, uint32_t AssumedStackSizeForExternalCall) const
Definition at line 128 of file AMDGPUResourceUsageAnalysis.cpp.
References assert(), contains(), F, llvm::AMDGPUFunctionArgInfo::FLAT_SCRATCH_INIT, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getPreloadedReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SIMachineFunctionInfo::getUserSGPRInfo(), hasAnyNonFlatUseOfReg(), llvm::GCNUserSGPRUsageInfo::hasFlatScratchInit(), llvm::AMDGPU::isEntryFunctionCC(), llvm::SIMachineFunctionInfo::isStackRealigned(), llvm_unreachable, MBB, MI, MRI, llvm::report_fatal_error(), TII, and TRI.
Referenced by llvm::AMDGPUResourceUsageAnalysis::run(), and llvm::AMDGPUResourceUsageAnalysisWrapperPass::runOnMachineFunction().
Member Data Documentation
ID
char llvm::AMDGPUResourceUsageAnalysisImpl::ID static
Definition at line 30 of file AMDGPUResourceUsageAnalysis.h.
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPUResourceUsageAnalysis.h
lib/Target/AMDGPU/AMDGPUResourceUsageAnalysis.cpp