LLVM: llvm::CoroCleanupPass Struct Reference
llvm::CoroCleanupPass Struct Reference
#include "llvm/Transforms/Coroutines/CoroCleanup.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Public Member Functions inherited from llvm::PassInfoMixin< CoroCleanupPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< CoroCleanupPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 23 of file CoroCleanup.h.
Member Function Documentation
isRequired()
bool llvm::CoroCleanupPass::isRequired () inline static
Definition at line 25 of file CoroCleanup.h.
run()
PreservedAnalyses CoroCleanupPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 120 of file CoroCleanup.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::PreservedAnalyses::all(), declaresCoroCleanupIntrinsics(), F, FAM, MAM, llvm::PreservedAnalyses::none(), llvm::PreservedAnalyses::preserveSet(), and llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Coroutines/CoroCleanup.h
lib/Transforms/Coroutines/CoroCleanup.cpp