LLVM: llvm::cl::OptionValueBase< DataType, isClass > Struct Template Reference
llvm::cl::OptionValueBase< DataType, isClass > Struct Template Reference
#include "llvm/Support/CommandLine.h"
Public Types
using WrapperType = OptionValue<DataType>
Public Member Functions
bool hasValue () const
const DataType & getValue () const
template<class DT>
void setValue (const DT &)
bool compare (const DataType &) const
bool compare (const GenericOptionValue &) const override
Protected Member Functions
~OptionValueBase ()=default
Protected Member Functions inherited from llvm::cl::GenericOptionValue
GenericOptionValue ()=default
GenericOptionValue (const GenericOptionValue &)=default
GenericOptionValue & operator= (const GenericOptionValue &)=default
~GenericOptionValue ()=default
Detailed Description
template<class DataType, bool isClass>
struct llvm::cl::OptionValueBase< DataType, isClass >
Definition at line 551 of file CommandLine.h.
Member Typedef Documentation
WrapperType
template<class DataType, bool isClass> using llvm::cl::OptionValueBase< DataType, isClass >::WrapperType = OptionValue<DataType>
Definition at line 553 of file CommandLine.h.
Constructor & Destructor Documentation
~OptionValueBase()
template<class DataType, bool isClass> llvm::cl::OptionValueBase< DataType, isClass >::~OptionValueBase () protected default
Member Function Documentation
compare() [1/2]
template<class DataType, bool isClass> bool llvm::cl::OptionValueBase< DataType, isClass >::compare (const DataType &) const inline
Definition at line 563 of file CommandLine.h.
compare() [2/2]
template<class DataType, bool isClass> bool llvm::cl::OptionValueBase< DataType, isClass >::compare (const GenericOptionValue &) const inline override virtual
Implements llvm::cl::GenericOptionValue.
Definition at line 565 of file CommandLine.h.
References llvm::cl::GenericOptionValue::GenericOptionValue().
getValue()
template<class DataType, bool isClass> const DataType & llvm::cl::OptionValueBase< DataType, isClass >::getValue () const inline
Definition at line 557 of file CommandLine.h.
References llvm_unreachable.
hasValue()
template<class DataType, bool isClass> bool llvm::cl::OptionValueBase< DataType, isClass >::hasValue () const inline
Definition at line 555 of file CommandLine.h.
setValue()
template<class DataType, bool isClass> template<class DT> void llvm::cl::OptionValueBase< DataType, isClass >::setValue (const DT &) inline
Definition at line 560 of file CommandLine.h.
Referenced by llvm::cl::OptionValue< cl::boolOrDefault >::operator=(), llvm::cl::OptionValue< std::string >::operator=(), llvm::cl::OptionValue< cl::boolOrDefault >::OptionValue(), and llvm::cl::OptionValue< std::string >::OptionValue().
The documentation for this struct was generated from the following file:
include/llvm/Support/CommandLine.h