LLVM: llvm::CodeViewYAML::detail::SymbolRecordImpl< T > Struct Template Reference
llvm::CodeViewYAML::detail::SymbolRecordImpl< T > Struct Template Reference
Public Member Functions
SymbolRecordImpl (codeview::SymbolKind K)
void map (yaml::IO &io) override
codeview::CVSymbol toCodeViewSymbol (BumpPtrAllocator &Allocator, CodeViewContainer Container) const override
Error fromCodeViewSymbol (codeview::CVSymbol CVS) override
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
void map (IO &IO)
Public Member Functions inherited from llvm::CodeViewYAML::detail::SymbolRecordBase
SymbolRecordBase (codeview::SymbolKind K)
virtual ~SymbolRecordBase ()=default
Public Attributes
T Symbol
Public Attributes inherited from llvm::CodeViewYAML::detail::SymbolRecordBase
codeview::SymbolKind Kind
Detailed Description
template<typename T>
struct llvm::CodeViewYAML::detail::SymbolRecordImpl< T >
Definition at line 255 of file CodeViewYAMLSymbols.cpp.
Constructor & Destructor Documentation
SymbolRecordImpl()
template<typename T> llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::SymbolRecordImpl (codeview::SymbolKind K) inline explicit
Definition at line 256 of file CodeViewYAMLSymbols.cpp.
References Symbol, and llvm::CodeViewYAML::detail::SymbolRecordBase::SymbolRecordBase().
Member Function Documentation
fromCodeViewSymbol()
template<typename T> Error llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::fromCodeViewSymbol (codeview::CVSymbol CVS) inline override virtual
Implements llvm::CodeViewYAML::detail::SymbolRecordBase.
Definition at line 267 of file CodeViewYAMLSymbols.cpp.
References llvm::codeview::SymbolDeserializer::deserializeAs(), and Symbol.
map() [1/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< ScopeEndSym >::map (IO & IO)
Definition at line 300 of file CodeViewYAMLSymbols.cpp.
map() [2/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< Thunk32Sym >::map (IO & IO)
Definition at line 315 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [3/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< TrampolineSym >::map (IO & IO)
Definition at line 325 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [4/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< SectionSym >::map (IO & IO)
Definition at line 334 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [5/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< CoffGroupSym >::map (IO & IO)
Definition at line 343 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [6/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< ExportSym >::map (IO & IO)
Definition at line 351 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [7/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< ProcSym >::map (IO & IO)
Definition at line 357 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [8/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< RegisterSym >::map (IO & IO)
Definition at line 371 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [9/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< PublicSym32 >::map (IO & IO)
Definition at line 377 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [10/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< ProcRefSym >::map (IO & IO)
Definition at line 384 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [11/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< EnvBlockSym >::map (IO & IO)
Definition at line 391 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [12/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< InlineSiteSym >::map (IO & IO)
Definition at line 395 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [13/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< LocalSym >::map (IO & IO)
Definition at line 402 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [14/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DefRangeSym >::map (IO & IO)
Definition at line 409 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [15/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DefRangeSubfieldSym >::map (IO & IO)
Definition at line 415 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [16/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DefRangeRegisterSym >::map (IO & IO)
Definition at line 422 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [17/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DefRangeFramePointerRelSym >::map (IO & IO)
Definition at line 429 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [18/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DefRangeSubfieldRegisterSym >::map (IO & IO)
Definition at line 435 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [19/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DefRangeFramePointerRelFullScopeSym >::map (IO & IO)
Definition at line 444 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [20/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DefRangeRegisterRelSym >::map (IO & IO)
Definition at line 448 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [21/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< BlockSym >::map (IO & IO)
Definition at line 456 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [22/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< LabelSym >::map (IO & IO)
Definition at line 465 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [23/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< ObjNameSym >::map (IO & IO)
Definition at line 472 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [24/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< Compile2Sym >::map (IO & IO)
Definition at line 477 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [25/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< Compile3Sym >::map (IO & IO)
Definition at line 489 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [26/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< FrameProcSym >::map (IO & IO)
Definition at line 503 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [27/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< CallSiteInfoSym >::map (IO & IO)
Definition at line 515 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [28/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< FileStaticSym >::map (IO & IO)
Definition at line 521 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [29/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< HeapAllocationSiteSym >::map (IO & IO)
Definition at line 528 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [30/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< FrameCookieSym >::map (IO & IO)
Definition at line 535 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [31/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< CallerSym >::map (IO & IO)
Definition at line 541 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [32/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< UDTSym >::map (IO & IO)
Definition at line 545 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [33/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< BuildInfoSym >::map (IO & IO)
Definition at line 550 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [34/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< BPRelativeSym >::map (IO & IO)
Definition at line 554 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [35/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< RegRelativeSym >::map (IO & IO)
Definition at line 560 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [36/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< ConstantSym >::map (IO & IO)
Definition at line 567 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [37/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< DataSym >::map (IO & IO)
Definition at line 573 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [38/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< ThreadLocalDataSym >::map (IO & IO)
Definition at line 580 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [39/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< UsingNamespaceSym >::map (IO & IO)
Definition at line 587 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [40/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< AnnotationSym >::map (IO & IO)
Definition at line 591 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and Symbol.
map() [41/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< JumpTableSym >::map (IO & IO)
Definition at line 597 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [42/43]
void llvm::CodeViewYAML::detail::SymbolRecordImpl< HotPatchFuncSym >::map (IO & IO)
Definition at line 608 of file CodeViewYAMLSymbols.cpp.
References llvm::yaml::IO::mapRequired(), and Symbol.
map() [43/43]
template<typename T> void llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::map (yaml::IO & io) override virtual
Implements llvm::CodeViewYAML::detail::SymbolRecordBase.
toCodeViewSymbol()
template<typename T> codeview::CVSymbol llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::toCodeViewSymbol (BumpPtrAllocator & Allocator, CodeViewContainer Container) const inline override virtual
Implements llvm::CodeViewYAML::detail::SymbolRecordBase.
Definition at line 262 of file CodeViewYAMLSymbols.cpp.
References Symbol, and llvm::codeview::SymbolSerializer::writeOneSymbol().
Member Data Documentation
Symbol
template<typename T> T llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::Symbol mutable
Definition at line 271 of file CodeViewYAMLSymbols.cpp.
Referenced by fromCodeViewSymbol(), map(), SymbolRecordImpl(), and toCodeViewSymbol().
The documentation for this struct was generated from the following file:
lib/ObjectYAML/CodeViewYAMLSymbols.cpp