LLVM: llvm::ms_demangle::TypeNode Struct Reference
llvm::ms_demangle::TypeNode Struct Reference abstract
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
TypeNode (NodeKind K)
virtual void outputPre (OutputBuffer &OB, OutputFlags Flags) const =0
virtual void outputPost (OutputBuffer &OB, OutputFlags Flags) const =0
void output (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Public Attributes
Qualifiers Quals = Q_None
Detailed Description
Definition at line 317 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
TypeNode()
llvm::ms_demangle::TypeNode::TypeNode (NodeKind K) inline explicit
Definition at line 318 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::Node::Node().
Referenced by llvm::ms_demangle::ArrayTypeNode::ArrayTypeNode(), llvm::ms_demangle::CustomTypeNode::CustomTypeNode(), llvm::ms_demangle::FunctionSignatureNode::FunctionSignatureNode(), llvm::ms_demangle::FunctionSignatureNode::FunctionSignatureNode(), llvm::ms_demangle::IntrinsicNode::IntrinsicNode(), llvm::ms_demangle::PointerTypeNode::PointerTypeNode(), llvm::ms_demangle::PrimitiveTypeNode::PrimitiveTypeNode(), and llvm::ms_demangle::TagTypeNode::TagTypeNode().
Member Function Documentation
classof()
bool llvm::ms_demangle::TypeNode::classof (const Node * N) inline static
Definition at line 328 of file MicrosoftDemangleNodes.h.
References N, llvm::ms_demangle::Node::Node(), llvm::ms_demangle::TypeEnd, and llvm::ms_demangle::TypeStart.
output()
void llvm::ms_demangle::TypeNode::output (OutputBuffer & OB, OutputFlags Flags) const inline override virtual
Implements llvm::ms_demangle::Node.
Definition at line 323 of file MicrosoftDemangleNodes.h.
References outputPost(), and outputPre().
outputPost()
virtual void llvm::ms_demangle::TypeNode::outputPost (OutputBuffer & OB, OutputFlags Flags) const pure virtual
Implemented in llvm::ms_demangle::ArrayTypeNode, llvm::ms_demangle::CustomTypeNode, llvm::ms_demangle::FunctionSignatureNode, llvm::ms_demangle::PointerTypeNode, llvm::ms_demangle::PrimitiveTypeNode, llvm::ms_demangle::TagTypeNode, and llvm::ms_demangle::ThunkSignatureNode.
Referenced by output().
outputPre()
virtual void llvm::ms_demangle::TypeNode::outputPre (OutputBuffer & OB, OutputFlags Flags) const pure virtual
Implemented in llvm::ms_demangle::ArrayTypeNode, llvm::ms_demangle::CustomTypeNode, llvm::ms_demangle::FunctionSignatureNode, llvm::ms_demangle::PointerTypeNode, llvm::ms_demangle::PrimitiveTypeNode, llvm::ms_demangle::TagTypeNode, and llvm::ms_demangle::ThunkSignatureNode.
Referenced by output().
Member Data Documentation
Quals
Qualifiers llvm::ms_demangle::TypeNode::Quals = Q_None
Definition at line 332 of file MicrosoftDemangleNodes.h.
Referenced by llvm::ms_demangle::FunctionSignatureNode::outputPost(), llvm::ms_demangle::ArrayTypeNode::outputPre(), llvm::ms_demangle::PointerTypeNode::outputPre(), llvm::ms_demangle::PrimitiveTypeNode::outputPre(), and llvm::ms_demangle::TagTypeNode::outputPre().
The documentation for this struct was generated from the following file:
include/llvm/Demangle/MicrosoftDemangleNodes.h