LLVM: llvm::GraphTraits< BasicBlock * > Struct Reference
llvm::GraphTraits< BasicBlock * > Struct Reference
#include "llvm/IR/CFG.h"
Public Types
using NodeRef = BasicBlock *
using ChildIteratorType = succ_iterator
Static Public Member Functions
static NodeRef getEntryNode (BasicBlock *BB)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static unsigned getNumber (const BasicBlock *BB)
Detailed Description
Definition at line 301 of file CFG.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< BasicBlock * >::ChildIteratorType = succ_iterator
Definition at line 303 of file CFG.h.
NodeRef
using llvm::GraphTraits< BasicBlock * >::NodeRef = BasicBlock *
Definition at line 302 of file CFG.h.
Member Function Documentation
child_begin()
ChildIteratorType llvm::GraphTraits< BasicBlock * >::child_begin (NodeRef N) inline static
Definition at line 306 of file CFG.h.
References N, and llvm::succ_begin().
child_end()
ChildIteratorType llvm::GraphTraits< BasicBlock * >::child_end (NodeRef N) inline static
Definition at line 307 of file CFG.h.
References N, and llvm::succ_end().
getEntryNode()
NodeRef llvm::GraphTraits< BasicBlock * >::getEntryNode (BasicBlock * BB) inline static
Definition at line 305 of file CFG.h.
getNumber()
unsigned llvm::GraphTraits< BasicBlock * >::getNumber (const BasicBlock * BB) inline static
Definition at line 309 of file CFG.h.
References llvm::BasicBlock::getNumber().
The documentation for this struct was generated from the following file:
include/llvm/IR/CFG.h