LLVM: lib/Target/SystemZ/SystemZAsmPrinter.cpp File Reference
SystemZAsmPrinter.cpp File Reference
#include "SystemZAsmPrinter.h"
#include "MCTargetDesc/SystemZGNUInstPrinter.h"
#include "MCTargetDesc/SystemZHLASMInstPrinter.h"
#include "MCTargetDesc/SystemZMCAsmInfo.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "SystemZConstantPoolValue.h"
#include "SystemZMCInstLower.h"
#include "TargetInfo/SystemZTargetInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/GOFF.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Chrono.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ConvertEBCDIC.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define LOWER_LOW(NAME)
#define LOWER_HIGH(NAME)
#define EMIT_COMMENT(Str)
Functions
static MCInst lowerRILow (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerRIHigh (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerRIEfLow (const MachineInstr *MI, unsigned Opcode)
static const MCSymbolRefExpr * getTLSGetOffset (MCContext &Context)
static const MCSymbolRefExpr * getGlobalOffsetTable (MCContext &Context)
static void lowerAlignmentHint (const MachineInstr *MI, MCInst &LoweredMI, unsigned Opcode)
static MCInst lowerSubvectorLoad (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerSubvectorStore (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerVecEltExtraction (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerVecEltInsertion (const MachineInstr *MI, unsigned Opcode)
static unsigned EmitNop (MCContext &OutContext, MCStreamer &OutStreamer, unsigned NumBytes, const MCSubtargetInfo &STI)
static uint8_t getSpecifierFromModifier (SystemZCP::SystemZCPModifier Modifier)
static void printFormattedRegName (const MCAsmInfo *MAI, unsigned RegNo, raw_ostream &OS)
static void printReg (unsigned Reg, const MCAsmInfo *MAI, raw_ostream &OS)
static void printOperand (const MCOperand &MCOp, const MCAsmInfo *MAI, raw_ostream &OS)
static void printAddress (const MCAsmInfo *MAI, unsigned Base, const MCOperand &DispMO, unsigned Index, raw_ostream &OS)
static std::string getProductID (Module &M)
static uint32_t getProductVersion (Module &M)
static uint32_t getProductRelease (Module &M)
static uint32_t getProductPatch (Module &M)
static time_t getTranslationTime (Module &M)
static void emitPPA1Flags (std::unique_ptr< MCStreamer > &OutStreamer, bool VarArg, bool StackProtector, bool FPRMask, bool VRMask, bool EHBlock, bool HasName)
static void emitPPA1Name (std::unique_ptr< MCStreamer > &OutStreamer, StringRef OutName)
INITIALIZE_PASS (SystemZAsmPrinter, "systemz-asm-printer", "SystemZ Assembly Printer", false, false) extern "C" LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZAsmPrinter()
Macro Definition Documentation
EMIT_COMMENT
#define EMIT_COMMENT (Str)
Value:
  OutStreamer->AddComment(Twine("Offset ")                                     \
                              .concat(utostr(Offset))                          \
                              .concat(" " Str " ")                             \
                              .concat(Sym->getName()));
LOWER_HIGH
#define LOWER_HIGH (NAME)
Value:
  case SystemZ::NAME##64: LoweredMI = lowerRIHigh(MI, SystemZ::NAME); break
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
LOWER_LOW
#define LOWER_LOW (NAME)
Value:
  case SystemZ::NAME##64: LoweredMI = lowerRILow(MI, SystemZ::NAME); break
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
Function Documentation
EmitNop()
unsigned EmitNop (MCContext & OutContext, MCStreamer & OutStreamer, unsigned NumBytes, const MCSubtargetInfo & STI) static
Definition at line 752 of file SystemZAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), llvm_unreachable, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
emitPPA1Flags()
void emitPPA1Flags (std::unique_ptr< MCStreamer > & OutStreamer, bool VarArg, bool StackProtector, bool FPRMask, bool VRMask, bool EHBlock, bool HasName) static
Definition at line 1271 of file SystemZAsmPrinter.cpp.
References llvm::LLVM_MARK_AS_BITMASK_ENUM, and llvm::AsmPrinter::OutStreamer.
emitPPA1Name()
void emitPPA1Name (std::unique_ptr< MCStreamer > & OutStreamer, StringRef OutName) static
Definition at line 1359 of file SystemZAsmPrinter.cpp.
References llvm::ConverterEBCDIC::convertToEBCDIC(), llvm::XCOFF::NameSize, llvm::AsmPrinter::OutStreamer, llvm::StringRef::size(), llvm::SmallString< InternalLen >::str(), and llvm::StringRef::substr().
getGlobalOffsetTable()
const MCSymbolRefExpr * getGlobalOffsetTable (MCContext & Context) static
Definition at line 87 of file SystemZAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create().
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
getProductID()
std::string getProductID (Module & M) static
Definition at line 1187 of file SystemZAsmPrinter.cpp.
References llvm::cast().
getProductPatch()
uint32_t getProductPatch (Module & M) static
Definition at line 1210 of file SystemZAsmPrinter.cpp.
References llvm::mdconst::extract_or_null().
getProductRelease()
uint32_t getProductRelease (Module & M) static
Definition at line 1203 of file SystemZAsmPrinter.cpp.
References llvm::mdconst::extract_or_null().
getProductVersion()
uint32_t getProductVersion (Module & M) static
Definition at line 1196 of file SystemZAsmPrinter.cpp.
References llvm::mdconst::extract_or_null().
getSpecifierFromModifier()
uint8_t getSpecifierFromModifier (SystemZCP::SystemZCPModifier Modifier) static
Definition at line 988 of file SystemZAsmPrinter.cpp.
References llvm::SystemZCP::DTPOFF, llvm_unreachable, llvm::SystemZCP::NTPOFF, llvm::SystemZ::S_DTPOFF, llvm::SystemZ::S_NTPOFF, llvm::SystemZ::S_TLSGD, llvm::SystemZ::S_TLSLDM, llvm::SystemZCP::TLSGD, and llvm::SystemZCP::TLSLDM.
Referenced by llvm::SystemZAsmPrinter::emitMachineConstantPoolValue().
getTLSGetOffset()
const MCSymbolRefExpr * getTLSGetOffset (MCContext & Context) static
Definition at line 81 of file SystemZAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create(), and llvm::SystemZ::S_PLT.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
getTranslationTime()
time_t getTranslationTime (Module & M) static
Definition at line 1217 of file SystemZAsmPrinter.cpp.
References llvm::mdconst::extract_or_null().
INITIALIZE_PASS()
INITIALIZE_PASS (SystemZAsmPrinter , "systemz-asm-printer" , "SystemZ Assembly Printer" , false , false)
Definition at line 1744 of file SystemZAsmPrinter.cpp.
References llvm::getTheSystemZTarget(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, and X.
lowerAlignmentHint()
void lowerAlignmentHint (const MachineInstr * MI, MCInst & LoweredMI, unsigned Opcode) static
Definition at line 97 of file SystemZAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), MI, and llvm::MCInst::setOpcode().
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerRIEfLow()
MCInst lowerRIEfLow (const MachineInstr * MI, unsigned Opcode) static
Definition at line 71 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsGR64(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerRIHigh()
MCInst lowerRIHigh (const MachineInstr * MI, unsigned Opcode) static
Definition at line 57 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsGRH32(), and MI.
lowerRILow()
MCInst lowerRILow (const MachineInstr * MI, unsigned Opcode) static
Definition at line 43 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsGR32(), and MI.
lowerSubvectorLoad()
MCInst lowerSubvectorLoad (const MachineInstr * MI, unsigned Opcode) static
Definition at line 122 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsVR128(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerSubvectorStore()
MCInst lowerSubvectorStore (const MachineInstr * MI, unsigned Opcode) static
Definition at line 132 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsVR128(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerVecEltExtraction()
MCInst lowerVecEltExtraction (const MachineInstr * MI, unsigned Opcode) static
Definition at line 142 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsGR64(), llvm::SystemZMC::getRegAsVR128(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerVecEltInsertion()
MCInst lowerVecEltInsertion (const MachineInstr * MI, unsigned Opcode) static
Definition at line 151 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsVR128(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
printAddress()
void printAddress (const MCAsmInfo * MAI, unsigned Base, const MCOperand & DispMO, unsigned Index, raw_ostream & OS) static
Definition at line 1047 of file SystemZAsmPrinter.cpp.
References llvm::sampleprof::Base, llvm::AsmPrinter::MAI, printFormattedRegName(), and printOperand().
Referenced by llvm::SystemZAsmPrinter::PrintAsmMemoryOperand().
printFormattedRegName()
void printFormattedRegName (const MCAsmInfo * MAI, unsigned RegNo, raw_ostream & OS) static
Definition at line 1014 of file SystemZAsmPrinter.cpp.
References llvm::AD_HLASM, assert(), llvm::MCAsmInfo::getAssemblerDialect(), llvm::SystemZGNUInstPrinter::getRegisterName(), llvm::SystemZHLASMInstPrinter::getRegisterName(), llvm::AsmPrinter::MAI, and RegName.
Referenced by printAddress(), and printReg().
printOperand()
void printOperand (const MCOperand & MCOp, const MCAsmInfo * MAI, raw_ostream & OS) static
Definition at line 1035 of file SystemZAsmPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, llvm::AsmPrinter::MAI, llvm::MCAsmInfo::printExpr(), and llvm::printReg().
printReg()
void printReg (unsigned Reg, const MCAsmInfo * MAI, raw_ostream & OS) static
Definition at line 1028 of file SystemZAsmPrinter.cpp.
References llvm::AsmPrinter::MAI, printFormattedRegName(), and Reg.