LLVM: lib/TableGen/TableGenBackend.cpp File Reference
TableGenBackend.cpp File Reference
#include "llvm/TableGen/TableGenBackend.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
Classes
struct llvm::cl::OptionValue< FnT >
Functions
static void printLine (raw_ostream &OS, const Twine &Prefix, char Fill, StringRef Suffix)
Variables
const size_t MAX_LINE_LEN = 80U
static ManagedStatic< cl::opt< FnT >, OptCreatorT > CallbackFunction
Function Documentation
printLine()
void printLine (raw_ostream & OS, const Twine & Prefix, char Fill, StringRef Suffix) static
Definition at line 72 of file TableGenBackend.cpp.
References assert(), MAX_LINE_LEN, llvm::StringRef::size(), and llvm::raw_ostream::tell().
Referenced by llvm::emitSourceFileHeader().
Variable Documentation
CallbackFunction
ManagedStatic<cl::opt<FnT>, OptCreatorT> CallbackFunction static
Definition at line 53 of file TableGenBackend.cpp.
Referenced by llvm::TableGen::Emitter::ApplyCallback(), and llvm::TableGen::Emitter::Opt::Opt().
MAX_LINE_LEN
const size_t MAX_LINE_LEN = 80U
Definition at line 26 of file TableGenBackend.cpp.
Referenced by llvm::emitSourceFileHeader(), and printLine().