LLVM: lib/CodeGen/TargetLoweringObjectFileImpl.cpp File Reference
TargetLoweringObjectFileImpl.cpp File Reference
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/GOFF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/CodeGen/BasicBlockSectionUtils.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PseudoProbe.h"
#include "llvm/IR/Type.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAsmInfoDarwin.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCGOFFAttributes.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionGOFF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSectionXCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCSymbolGOFF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/Base64.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/TargetParser/Triple.h"
#include <cassert>
#include <string>
Functions
static void GetObjCImageInfo (Module &M, unsigned &Version, unsigned &Flags, StringRef &Section)
static SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K)
static bool hasPrefix (StringRef SectionName, StringRef Prefix)
static unsigned getELFSectionType (StringRef Name, SectionKind K)
static unsigned getELFSectionFlags (SectionKind K, const Triple &T)
static const Comdat * getELFComdat (const GlobalValue *GV)
static const MCSymbolELF * getLinkedToSymbol (const GlobalObject *GO, const TargetMachine &TM)
static unsigned getEntrySizeForKind (SectionKind Kind)
static StringRef getSectionPrefixForGlobal (SectionKind Kind, bool IsLarge)
Return the section prefix name used by options FunctionsSections and DataSections.
static SmallString< 128 > getELFSectionNameForGlobal (const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, unsigned EntrySize, bool UniqueSectionName, const MachineJumpTableEntry *JTE)
static unsigned calcUniqueIDUpdateFlagsAndSize (const GlobalObject *GO, StringRef SectionName, SectionKind Kind, const TargetMachine &TM, MCContext &Ctx, Mangler &Mang, unsigned &Flags, unsigned &EntrySize, unsigned &NextUniqueID, const bool Retain, const bool ForceUnique)
Calculate an appropriate unique ID for a section, and update Flags, EntrySize and NextUniqueID where appropriate.
static std::tuple< StringRef, bool, unsigned > getGlobalObjectInfo (const GlobalObject *GO, const TargetMachine &TM)
static StringRef handlePragmaClangSection (const GlobalObject *GO, SectionKind Kind)
static MCSection * selectExplicitSectionGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM, MCContext &Ctx, Mangler &Mang, unsigned &NextUniqueID, bool Retain, bool ForceUnique)
static MCSectionELF * selectELFSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool EmitUniqueSection, unsigned Flags, unsigned *NextUniqueID, const MCSymbolELF *AssociatedSymbol, const MachineJumpTableEntry *MJTE=nullptr)
static MCSection * selectELFSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool Retain, bool EmitUniqueSection, unsigned Flags, unsigned *NextUniqueID)
static MCSectionELF * getStaticStructorSection (MCContext &Ctx, bool UseInitArray, bool IsCtor, unsigned Priority, const MCSymbol *KeySym)
static void checkMachOComdat (const GlobalValue *GV)
static bool canUsePrivateLabel (const MCAsmInfo &AsmInfo, const MCSection &Section)
static unsigned getCOFFSectionFlags (SectionKind K, const TargetMachine &TM)
static const GlobalValue * getComdatGVForCOFF (const GlobalValue *GV)
static int getSelectionForCOFF (const GlobalValue *GV)
static StringRef getCOFFSectionNameForUniqueGlobal (SectionKind Kind)
static MCSectionCOFF * getCOFFStaticStructorSection (MCContext &Ctx, const Triple &T, bool IsCtor, unsigned Priority, const MCSymbol *KeySym, MCSectionCOFF *Default)
static std::string APIntToHexString (const APInt &AI)
static std::string scalarConstantToHexString (const Constant *C)
static const Comdat * getWasmComdat (const GlobalValue *GV)
static unsigned getWasmSectionFlags (SectionKind K, bool Retain)
static MCSectionWasm * selectWasmSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool EmitUniqueSection, unsigned *NextUniqueID, bool Retain)
Variables
static cl::opt< bool > JumpTableInFunctionSection ("jumptable-in-function-section", cl::Hidden, cl::init(false), cl::desc("Putting Jump Table in function section"))
Function Documentation
APIntToHexString()
std::string APIntToHexString (const APInt & AI) static
Definition at line 2102 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::APInt::getBitWidth(), Size, llvm::toString(), and llvm::transform().
Referenced by scalarConstantToHexString().
calcUniqueIDUpdateFlagsAndSize()
unsigned calcUniqueIDUpdateFlagsAndSize (const GlobalObject * GO, StringRef SectionName, SectionKind Kind, const TargetMachine & TM, MCContext & Ctx, Mangler & Mang, unsigned & Flags, unsigned & EntrySize, unsigned & NextUniqueID, const bool Retain, const bool ForceUnique) static
Calculate an appropriate unique ID for a section, and update Flags, EntrySize and NextUniqueID where appropriate.
Definition at line 705 of file TargetLoweringObjectFileImpl.cpp.
References getELFSectionNameForGlobal(), llvm::GlobalObject::getMetadata(), llvm::MCSection::NonUniqueID, Retain, llvm::ELF::SHF_GNU_RETAIN, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_MERGE, and llvm::ELF::SHF_SUNW_NODISCARD.
Referenced by selectExplicitSectionGlobal().
canUsePrivateLabel()
bool canUsePrivateLabel (const MCAsmInfo & AsmInfo, const MCSection & Section) static
Definition at line 1617 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCAsmInfoDarwin::isSectionAtomizableBySymbols().
Referenced by llvm::TargetLoweringObjectFileMachO::getNameWithPrefix().
checkMachOComdat()
void checkMachOComdat (const GlobalValue * GV) static
Definition at line 1351 of file TargetLoweringObjectFileImpl.cpp.
References llvm::CallingConv::C, llvm::GlobalValue::getComdat(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
getCOFFSectionFlags()
unsigned getCOFFSectionFlags (SectionKind K, const TargetMachine & TM) static
Definition at line 1647 of file TargetLoweringObjectFileImpl.cpp.
References llvm::COFF::IMAGE_SCN_CNT_CODE, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_LNK_REMOVE, llvm::COFF::IMAGE_SCN_MEM_16BIT, llvm::COFF::IMAGE_SCN_MEM_DISCARDABLE, llvm::COFF::IMAGE_SCN_MEM_EXECUTE, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, isThumb(), and llvm::Triple::thumb.
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getCOFFSectionNameForUniqueGlobal()
StringRef getCOFFSectionNameForUniqueGlobal (SectionKind Kind) static
Definition at line 1764 of file TargetLoweringObjectFileImpl.cpp.
Referenced by llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getCOFFStaticStructorSection()
MCSectionCOFF * getCOFFStaticStructorSection (MCContext & Ctx, const Triple & T, bool IsCtor, unsigned Priority, const MCSymbol * KeySym, MCSectionCOFF * Default) static
Definition at line 2005 of file TargetLoweringObjectFileImpl.cpp.
References Default, llvm::format(), llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, and T.
Referenced by llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), and llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection().
getComdatGVForCOFF()
const GlobalValue * getComdatGVForCOFF (const GlobalValue * GV) static
Definition at line 1686 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::CallingConv::C, llvm::GlobalValue::getComdat(), llvm::Module::getNamedValue(), llvm::GlobalValue::getParent(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), getSelectionForCOFF(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getELFComdat()
const Comdat * getELFComdat (const GlobalValue * GV) static
Definition at line 563 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::CallingConv::C, llvm::GlobalValue::getComdat(), llvm::Comdat::NoDeduplicate, and llvm::report_fatal_error().
Referenced by getGlobalObjectInfo(), and llvm::TargetLoweringObjectFileELF::getSectionForLSDA().
getELFKindForNamedSection()
SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K) static
Definition at line 455 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Triple::ELF, llvm::SectionKind::getBSS(), llvm::getInstrProfSectionName(), llvm::SectionKind::getMetadata(), llvm::SectionKind::getThreadBSS(), and llvm::SectionKind::getThreadData().
Referenced by selectExplicitSectionGlobal().
getELFSectionFlags()
unsigned getELFSectionFlags (SectionKind K, const Triple & T) static
Definition at line 529 of file TargetLoweringObjectFileImpl.cpp.
References llvm::ELF::SHF_AARCH64_PURECODE, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_ARM_PURECODE, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_TLS, llvm::ELF::SHF_WRITE, and T.
Referenced by llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction(), selectExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
getELFSectionNameForGlobal()
SmallString< 128 > getELFSectionNameForGlobal (const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, unsigned EntrySize, bool UniqueSectionName, const MachineJumpTableEntry * JTE) static
Definition at line 633 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::cast(), llvm::Cold, llvm::dyn_cast(), F, llvm::GlobalValue::getDataLayout(), llvm::DataLayout::getPreferredAlign(), getSectionPrefixForGlobal(), llvm::Hot, llvm::MachineJumpTableEntry::Hotness, llvm::Unknown, llvm::utostr(), and llvm::Align::value().
Referenced by calcUniqueIDUpdateFlagsAndSize(), and selectELFSectionForGlobal().
getELFSectionType()
unsigned getELFSectionType (StringRef Name, SectionKind K) static
Definition at line 502 of file TargetLoweringObjectFileImpl.cpp.
References hasPrefix(), llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_LLVM_LTO, llvm::ELF::SHT_LLVM_OFFLOADING, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PREINIT_ARRAY, and llvm::ELF::SHT_PROGBITS.
Referenced by selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
getEntrySizeForKind()
unsigned getEntrySizeForKind (SectionKind Kind) static
Definition at line 588 of file TargetLoweringObjectFileImpl.cpp.
References assert().
Referenced by selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
getGlobalObjectInfo()
std::tuple< StringRef, bool, unsigned > getGlobalObjectInfo (const GlobalObject * GO, const TargetMachine & TM) static
Definition at line 785 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::CallingConv::C, getELFComdat(), llvm::ELF::SHF_GROUP, and llvm::ELF::SHF_X86_64_LARGE.
Referenced by selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
getLinkedToSymbol()
const MCSymbolELF * getLinkedToSymbol (const GlobalObject * GO, const TargetMachine & TM) static
Definition at line 577 of file TargetLoweringObjectFileImpl.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::MDOperand::get(), llvm::GlobalObject::getMetadata(), and llvm::MDNode::getOperand().
Referenced by selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
GetObjCImageInfo()
void GetObjCImageInfo (Module & M, unsigned & Version, unsigned & Flags, StringRef & Section) static
Definition at line 84 of file TargetLoweringObjectFileImpl.cpp.
References llvm::cast(), llvm::mdconst::extract(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::Module::Require.
Referenced by llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), and llvm::TargetLoweringObjectFileMachO::emitModuleMetadata().
getSectionPrefixForGlobal()
StringRef getSectionPrefixForGlobal (SectionKind Kind, bool IsLarge) static
Return the section prefix name used by options FunctionsSections and DataSections.
Definition at line 614 of file TargetLoweringObjectFileImpl.cpp.
References llvm_unreachable.
Referenced by getELFSectionNameForGlobal(), and selectWasmSectionForGlobal().
getSelectionForCOFF()
int getSelectionForCOFF (const GlobalValue * GV) static
Definition at line 1703 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::CallingConv::C, llvm::dyn_cast(), llvm::Comdat::ExactMatch, llvm::GlobalValue::getAliaseeObject(), llvm::GlobalValue::getComdat(), getComdatGVForCOFF(), llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_COMDAT_SELECT_EXACT_MATCH, llvm::COFF::IMAGE_COMDAT_SELECT_LARGEST, llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_COMDAT_SELECT_SAME_SIZE, llvm::Comdat::Largest, llvm::Comdat::NoDeduplicate, and llvm::Comdat::SameSize.
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getStaticStructorSection()
MCSectionELF * getStaticStructorSection (MCContext & Ctx, bool UseInitArray, bool IsCtor, unsigned Priority, const MCSymbol * KeySym) static
Definition at line 1141 of file TargetLoweringObjectFileImpl.cpp.
References llvm::format(), llvm::MCSymbol::getName(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_PROGBITS, and llvm::utostr().
Referenced by llvm::TargetLoweringObjectFileELF::getStaticCtorSection(), and llvm::TargetLoweringObjectFileELF::getStaticDtorSection().
getWasmComdat()
const Comdat * getWasmComdat (const GlobalValue * GV) static
Definition at line 2184 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::CallingConv::C, llvm::GlobalValue::getComdat(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), and selectWasmSectionForGlobal().
getWasmSectionFlags()
unsigned getWasmSectionFlags (SectionKind K, bool Retain) static
Definition at line 2197 of file TargetLoweringObjectFileImpl.cpp.
References Retain, llvm::wasm::WASM_SEG_FLAG_RETAIN, llvm::wasm::WASM_SEG_FLAG_STRINGS, and llvm::wasm::WASM_SEG_FLAG_TLS.
Referenced by llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), and selectWasmSectionForGlobal().
handlePragmaClangSection()
StringRef handlePragmaClangSection (const GlobalObject * GO, SectionKind Kind) static
Definition at line 799 of file TargetLoweringObjectFileImpl.cpp.
References llvm::dyn_cast(), llvm::GlobalVariable::getAttributes(), llvm::GlobalObject::getSection(), and llvm::GlobalVariable::hasImplicitSection().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), and selectExplicitSectionGlobal().
hasPrefix()
bool hasPrefix (StringRef SectionName, StringRef Prefix) static
Definition at line 497 of file TargetLoweringObjectFileImpl.cpp.
Referenced by getELFSectionType().
scalarConstantToHexString()
std::string scalarConstantToHexString (const Constant * C) static
Definition at line 2113 of file TargetLoweringObjectFileImpl.cpp.
References APIntToHexString(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), E(), llvm::APInt::getZero(), I, llvm::isa(), and scalarConstantToHexString().
Referenced by llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), and scalarConstantToHexString().
selectELFSectionForGlobal() [1/2]
MCSectionELF * selectELFSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool EmitUniqueSection, unsigned Flags, unsigned * NextUniqueID, const MCSymbolELF * AssociatedSymbol, const MachineJumpTableEntry * MJTE = nullptr) static
Definition at line 876 of file TargetLoweringObjectFileImpl.cpp.
References getELFSectionNameForGlobal(), getELFSectionType(), getEntrySizeForKind(), getGlobalObjectInfo(), and llvm::MCSection::NonUniqueID.
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction(), selectELFSectionForGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
selectELFSectionForGlobal() [2/2]
MCSection * selectELFSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool Retain, bool EmitUniqueSection, unsigned Flags, unsigned * NextUniqueID) static
Definition at line 909 of file TargetLoweringObjectFileImpl.cpp.
References assert(), getLinkedToSymbol(), Retain, selectELFSectionForGlobal(), llvm::ELF::SHF_GNU_RETAIN, llvm::ELF::SHF_LINK_ORDER, and llvm::ELF::SHF_SUNW_NODISCARD.
selectExplicitSectionGlobal()
MCSection * selectExplicitSectionGlobal (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM, MCContext & Ctx, Mangler & Mang, unsigned & NextUniqueID, bool Retain, bool ForceUnique) static
Definition at line 820 of file TargetLoweringObjectFileImpl.cpp.
References assert(), calcUniqueIDUpdateFlagsAndSize(), llvm::LLVMContext::diagnose(), llvm::Value::getContext(), getELFKindForNamedSection(), getELFSectionFlags(), getELFSectionType(), getEntrySizeForKind(), getGlobalObjectInfo(), getLinkedToSymbol(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::Module::getSourceFileName(), handlePragmaClangSection(), Retain, and llvm::ELF::SHF_MERGE.
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction().
selectWasmSectionForGlobal()
MCSectionWasm * selectWasmSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool EmitUniqueSection, unsigned * NextUniqueID, bool Retain) static
Definition at line 2257 of file TargetLoweringObjectFileImpl.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), F, getSectionPrefixForGlobal(), getWasmComdat(), getWasmSectionFlags(), llvm::MCSection::NonUniqueID, and Retain.
Referenced by llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal().
Variable Documentation
JumpTableInFunctionSection
cl::opt< bool > JumpTableInFunctionSection("jumptable-in-function-section", cl::Hidden, cl::init(false), cl::desc("Putting Jump Table in function section")) ("jumptable-in-function-section" , cl::Hidden , cl::init(false) , cl::desc("Putting Jump Table in function section")) static
Referenced by llvm::TargetLoweringObjectFileCOFF::shouldPutJumpTableInFunctionSection().