LLVM: lib/Analysis/TargetLibraryInfo.cpp File Reference
TargetLibraryInfo.cpp File Reference
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Analysis/TargetLibraryInfo.def"
#include "llvm/Analysis/VecFuncs.def"
Macros
#define TLI_DEFINE_STRING
#define TLI_DEFINE_SIG
#define TLI_DEFINE_ACCELERATE_VECFUNCS
#define TLI_DEFINE_DARWIN_LIBSYSTEM_M_VECFUNCS
#define TLI_DEFINE_LIBMVEC_X86_VECFUNCS
#define TLI_DEFINE_LIBMVEC_AARCH64_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX, CC)
#define TLI_DEFINE_MASSV_VECFUNCS
#define TLI_DEFINE_SVML_VECFUNCS
#define TLI_DEFINE_SLEEFGNUABI_VF2_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, VABI_PREFIX)
#define TLI_DEFINE_SLEEFGNUABI_VF4_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, VABI_PREFIX)
#define TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX)
#define TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS_RISCV
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX)
#define TLI_DEFINE_ARMPL_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX, CC)
#define TLI_DEFINE_AMDLIBM_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX)
Typedefs
typedef std::array< FuncArgTypeID, 8 > FuncProtoTy
Enumerations
enum FuncArgTypeID : char {
Void = 0 , Bool , Int16 , Int32 ,
Int , IntPlus , Long , IntX ,
Int64 , LLong , SizeT , SSizeT ,
Flt , Dbl , LDbl , Floating ,
Ptr , Struct , Ellip , Same
}
Functions
static bool hasSinCosPiStret (const Triple &T)
static bool hasBcmp (const Triple &TT)
static bool isCallingConvCCompatible (CallingConv::ID CC, const Triple &TT, FunctionType *FuncTy)
static void initializeBase (TargetLibraryInfoImpl &TLI, const Triple &T)
static void initializeLibCalls (TargetLibraryInfoImpl &TLI, const Triple &T, ArrayRef< StringLiteral > StandardNames)
Initialize the set of available library functions based on the specified target triple.
static void initialize (TargetLibraryInfoImpl &TLI, const Triple &T, ArrayRef< StringLiteral > StandardNames)
Initialize the set of available library functions based on the specified target triple.
static StringRef sanitizeFunctionName (StringRef funcName)
static DenseMap< StringRef, LibFunc > buildIndexMap (ArrayRef< StringLiteral > StandardNames)
static bool matchType (FuncArgTypeID ArgTy, const Type *Ty, unsigned IntBits, unsigned SizeTBits)
static bool isValidProtoForSizeReturningNew (const FunctionType &FTy, LibFunc F, const Module &M, int SizeTSizeBits)
static bool compareByScalarFnName (const VecDesc &LHS, const VecDesc &RHS)
static bool compareByVectorFnName (const VecDesc &LHS, const VecDesc &RHS)
static bool compareWithScalarFnName (const VecDesc &LHS, StringRef S)
Variables
static cl::opt< TargetLibraryInfoImpl::VectorLibrary > ClVectorLibrary ("vector-library", cl::Hidden, cl::desc("Vector functions library"), cl::init(TargetLibraryInfoImpl::NoLibrary), cl::values(clEnumValN(TargetLibraryInfoImpl::NoLibrary, "none", "No vector functions library"), clEnumValN(TargetLibraryInfoImpl::Accelerate, "Accelerate", "Accelerate framework"), clEnumValN(TargetLibraryInfoImpl::DarwinLibSystemM, "Darwin_libsystem_m", "Darwin libsystem_m"), clEnumValN(TargetLibraryInfoImpl::LIBMVEC, "LIBMVEC", "GLIBC Vector Math library"), clEnumValN(TargetLibraryInfoImpl::MASSV, "MASSV", "IBM MASS vector library"), clEnumValN(TargetLibraryInfoImpl::SVML, "SVML", "Intel SVML library"), clEnumValN(TargetLibraryInfoImpl::SLEEFGNUABI, "sleefgnuabi", "SIMD Library for Evaluating Elementary Functions"), clEnumValN(TargetLibraryInfoImpl::ArmPL, "ArmPL", "Arm Performance Libraries"), clEnumValN(TargetLibraryInfoImpl::AMDLIBM, "AMDLIBM", "AMD vector math library")))
static const FuncProtoTy Signatures []
static const VecDesc VecFuncs_Accelerate []
static const VecDesc VecFuncs_DarwinLibSystemM []
static const VecDesc VecFuncs_LIBMVEC_X86 []
static const VecDesc VecFuncs_LIBMVEC_AARCH64 []
static const VecDesc VecFuncs_MASSV []
static const VecDesc VecFuncs_SVML []
static const VecDesc VecFuncs_SLEEFGNUABI_VF2 []
static const VecDesc VecFuncs_SLEEFGNUABI_VF4 []
static const VecDesc VecFuncs_SLEEFGNUABI_VFScalable []
static const VecDesc VecFuncs_SLEEFGNUABI_VFScalableRISCV []
static const VecDesc VecFuncs_ArmPL []
const VecDesc VecFuncs_AMDLIBM []
Macro Definition Documentation
TLI_DEFINE_ACCELERATE_VECFUNCS
#define TLI_DEFINE_ACCELERATE_VECFUNCS
TLI_DEFINE_AMDLIBM_VECFUNCS
#define TLI_DEFINE_AMDLIBM_VECFUNCS
TLI_DEFINE_ARMPL_VECFUNCS
#define TLI_DEFINE_ARMPL_VECFUNCS
TLI_DEFINE_DARWIN_LIBSYSTEM_M_VECFUNCS
#define TLI_DEFINE_DARWIN_LIBSYSTEM_M_VECFUNCS
TLI_DEFINE_LIBMVEC_AARCH64_VECFUNCS
#define TLI_DEFINE_LIBMVEC_AARCH64_VECFUNCS
TLI_DEFINE_LIBMVEC_X86_VECFUNCS
#define TLI_DEFINE_LIBMVEC_X86_VECFUNCS
TLI_DEFINE_MASSV_VECFUNCS
#define TLI_DEFINE_MASSV_VECFUNCS
TLI_DEFINE_SIG
#define TLI_DEFINE_SIG
TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS
#define TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS
TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS_RISCV
#define TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS_RISCV
TLI_DEFINE_SLEEFGNUABI_VF2_VECFUNCS
#define TLI_DEFINE_SLEEFGNUABI_VF2_VECFUNCS
TLI_DEFINE_SLEEFGNUABI_VF4_VECFUNCS
#define TLI_DEFINE_SLEEFGNUABI_VF4_VECFUNCS
TLI_DEFINE_STRING
#define TLI_DEFINE_STRING
TLI_DEFINE_SVML_VECFUNCS
#define TLI_DEFINE_SVML_VECFUNCS
TLI_DEFINE_VECFUNC [1/7]
#define TLI_DEFINE_VECFUNC (SCAL, VEC, VF, MASK, VABI_PREFIX)
Value:
  {SCAL, VEC, VF, MASK, VABI_PREFIX, /* CC = */ std::nullopt},
TLI_DEFINE_VECFUNC [2/7]
#define TLI_DEFINE_VECFUNC (SCAL, VEC, VF, MASK, VABI_PREFIX)
Value:
  {SCAL, VEC, VF, MASK, VABI_PREFIX, /* CC = */ std::nullopt},
TLI_DEFINE_VECFUNC [3/7]
#define TLI_DEFINE_VECFUNC (SCAL, VEC, VF, MASK, VABI_PREFIX)
Value:
  {SCAL, VEC, VF, MASK, VABI_PREFIX, /* CC = */ std::nullopt},
TLI_DEFINE_VECFUNC [4/7]
#define TLI_DEFINE_VECFUNC (SCAL, VEC, VF, MASK, VABI_PREFIX, CC)
Value:
  {SCAL, VEC, VF, MASK, VABI_PREFIX, CC},
TLI_DEFINE_VECFUNC [5/7]
#define TLI_DEFINE_VECFUNC (SCAL, VEC, VF, MASK, VABI_PREFIX, CC)
Value:
  {SCAL, VEC, VF, MASK, VABI_PREFIX, CC},
TLI_DEFINE_VECFUNC [6/7]
#define TLI_DEFINE_VECFUNC (SCAL, VEC, VF, VABI_PREFIX)
Value:
  {SCAL, VEC, VF, /* MASK = */ false, VABI_PREFIX, /* CC = */ std::nullopt},
TLI_DEFINE_VECFUNC [7/7]
#define TLI_DEFINE_VECFUNC (SCAL, VEC, VF, VABI_PREFIX)
Value:
  {SCAL, VEC, VF, /* MASK = */ false, VABI_PREFIX, /* CC = */ std::nullopt},
Typedef Documentation
FuncProtoTy
typedef std::array<FuncArgTypeID, 8> FuncProtoTy
Definition at line 83 of file TargetLibraryInfo.cpp.
Enumeration Type Documentation
FuncArgTypeID
enum FuncArgTypeID : char
Enumerator
Void
Bool
Int16
Int32
Int
IntPlus
Long
IntX
Int64
LLong
SizeT
SSizeT
Flt
Dbl
LDbl
Floating
Ptr
Struct
Ellip
Same
Definition at line 60 of file TargetLibraryInfo.cpp.
Function Documentation
buildIndexMap()
DenseMap< StringRef, LibFunc > buildIndexMap (ArrayRef< StringLiteral > StandardNames) static
Definition at line 998 of file TargetLibraryInfo.cpp.
References llvm::NumLibFuncs, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve().
Referenced by llvm::TargetLibraryInfoImpl::getLibFunc().
compareByScalarFnName()
bool compareByScalarFnName (const VecDesc & LHS, const VecDesc & RHS) static
Definition at line 1259 of file TargetLibraryInfo.cpp.
References LHS, and RHS.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctions().
compareByVectorFnName()
bool compareByVectorFnName (const VecDesc & LHS, const VecDesc & RHS) static
Definition at line 1263 of file TargetLibraryInfo.cpp.
References LHS, and RHS.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctions().
compareWithScalarFnName()
bool compareWithScalarFnName (const VecDesc & LHS, StringRef S) static
Definition at line 1267 of file TargetLibraryInfo.cpp.
References LHS.
Referenced by llvm::TargetLibraryInfoImpl::getVectorMappingInfo(), llvm::TargetLibraryInfoImpl::getWidestVF(), and llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
hasBcmp()
bool hasBcmp (const Triple & TT) static
Definition at line 111 of file TargetLibraryInfo.cpp.
Referenced by initializeLibCalls().
hasSinCosPiStret()
bool hasSinCosPiStret (const Triple & T) static
Definition at line 93 of file TargetLibraryInfo.cpp.
References T, and llvm::Triple::x86.
Referenced by initializeLibCalls().
initialize()
void initialize (TargetLibraryInfoImpl & TLI, const Triple & T, ArrayRef< StringLiteral > StandardNames) static
Initialize the set of available library functions based on the specified target triple.
This should be carefully written so that a missing target triple gets a sane set of defaults.
Definition at line 926 of file TargetLibraryInfo.cpp.
References initializeBase(), initializeLibCalls(), and T.
Referenced by llvm::OProfileWrapper::op_close_agent(), llvm::OProfileWrapper::op_major_version(), llvm::OProfileWrapper::op_minor_version(), llvm::OProfileWrapper::op_open_agent(), llvm::OProfileWrapper::op_unload_native_code(), llvm::OProfileWrapper::op_write_debug_line_info(), llvm::OProfileWrapper::op_write_native_code(), and llvm::TargetLibraryInfoImpl::TargetLibraryInfoImpl().
initializeBase()
void initializeBase (TargetLibraryInfoImpl & TLI, const Triple & T) static
Definition at line 164 of file TargetLibraryInfo.cpp.
References llvm::TargetLibraryInfo::initExtensionsForTriple(), llvm::TargetLibraryInfoImpl::setIntSize(), llvm::TargetLibraryInfoImpl::setShouldExtI32Param(), llvm::TargetLibraryInfoImpl::setShouldExtI32Return(), llvm::TargetLibraryInfoImpl::setShouldSignExtI32Param(), llvm::TargetLibraryInfoImpl::setShouldSignExtI32Return(), and T.
Referenced by initialize().
initializeLibCalls()
void initializeLibCalls (TargetLibraryInfoImpl & TLI, const Triple & T, ArrayRef< StringLiteral > StandardNames) static
Initialize the set of available library functions based on the specified target triple.
This should be carefully written so that a missing target triple gets a sane set of defaults.
Definition at line 184 of file TargetLibraryInfo.cpp.
References llvm::Triple::aarch64, llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib(), llvm::Triple::arm, ClVectorLibrary, llvm::Triple::Darwin, llvm::TargetLibraryInfoImpl::disableAllFunctions(), llvm::Triple::Emscripten, llvm::Triple::FreeBSD, hasBcmp(), hasSinCosPiStret(), llvm::Triple::IOS, llvm::Triple::Linux, llvm::Triple::MacOSX, llvm::TargetLibraryInfoImpl::setAvailable(), llvm::TargetLibraryInfoImpl::setAvailableWithName(), llvm::TargetLibraryInfoImpl::setUnavailable(), T, llvm::Triple::tce, llvm::Triple::TvOS, llvm::Triple::WatchOS, llvm::Triple::x86, llvm::Triple::x86_64, llvm::Triple::xcore, and llvm::Triple::XROS.
Referenced by initialize().
isCallingConvCCompatible()
bool isCallingConvCCompatible (CallingConv::ID CC, const Triple & TT, FunctionType * FuncTy) static
Definition at line 121 of file TargetLibraryInfo.cpp.
References llvm::CallingConv::ARM_AAPCS, llvm::CallingConv::ARM_AAPCS_VFP, llvm::CallingConv::ARM_APCS, and llvm::CallingConv::C.
isValidProtoForSizeReturningNew()
bool isValidProtoForSizeReturningNew (const FunctionType & FTy, LibFunc F, const Module & M, int SizeTSizeBits) static
Definition at line 1071 of file TargetLibraryInfo.cpp.
References F, llvm::PointerType::get(), llvm::StructType::get(), and llvm::Type::getIntNTy().
matchType()
bool matchType (FuncArgTypeID ArgTy, const Type * Ty, unsigned IntBits, unsigned SizeTBits) static
Definition at line 1024 of file TargetLibraryInfo.cpp.
References Bool, Dbl, Floating, Flt, Int, Int16, Int32, Int64, IntPlus, IntX, LDbl, LLong, llvm_unreachable, Long, Ptr, SizeT, SSizeT, Struct, and Void.
sanitizeFunctionName()
StringRef sanitizeFunctionName (StringRef funcName) static
Definition at line 986 of file TargetLibraryInfo.cpp.
References llvm::StringRef::contains(), llvm::GlobalValue::dropLLVMManglingEscape(), and llvm::StringRef::empty().
Referenced by llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::TargetLibraryInfoImpl::getVectorMappingInfo(), llvm::TargetLibraryInfoImpl::getWidestVF(), and llvm::TargetLibraryInfoImpl::isFunctionVectorizable().
Variable Documentation
ClVectorLibrary
cl::opt< TargetLibraryInfoImpl::VectorLibrary > ClVectorLibrary("vector-library", cl::Hidden, cl::desc("Vector functions library"), cl::init(TargetLibraryInfoImpl::NoLibrary), cl::values(clEnumValN(TargetLibraryInfoImpl::NoLibrary, "none", "No vector functions library"), clEnumValN(TargetLibraryInfoImpl::Accelerate, "Accelerate", "Accelerate framework"), clEnumValN(TargetLibraryInfoImpl::DarwinLibSystemM, "Darwin_libsystem_m", "Darwin libsystem_m"), clEnumValN(TargetLibraryInfoImpl::LIBMVEC, "LIBMVEC", "GLIBC Vector Math library"), clEnumValN(TargetLibraryInfoImpl::MASSV, "MASSV", "IBM MASS vector library"), clEnumValN(TargetLibraryInfoImpl::SVML, "SVML", "Intel SVML library"), clEnumValN(TargetLibraryInfoImpl::SLEEFGNUABI, "sleefgnuabi", "SIMD Library for Evaluating Elementary Functions"), clEnumValN(TargetLibraryInfoImpl::ArmPL, "ArmPL", "Arm Performance Libraries"), clEnumValN(TargetLibraryInfoImpl::AMDLIBM, "AMDLIBM", "AMD vector math library"))) ("vector-library" , cl::Hidden , cl::desc("Vector functions library") , cl::init(TargetLibraryInfoImpl::NoLibrary) , cl::values(clEnumValN(TargetLibraryInfoImpl::NoLibrary, "none", "No vector functions library"), clEnumValN(TargetLibraryInfoImpl::Accelerate, "Accelerate", "Accelerate framework"), clEnumValN(TargetLibraryInfoImpl::DarwinLibSystemM, "Darwin_libsystem_m", "Darwin libsystem_m"), clEnumValN(TargetLibraryInfoImpl::LIBMVEC, "LIBMVEC", "GLIBC Vector Math library"), clEnumValN(TargetLibraryInfoImpl::MASSV, "MASSV", "IBM MASS vector library"), clEnumValN(TargetLibraryInfoImpl::SVML, "SVML", "Intel SVML library"), clEnumValN(TargetLibraryInfoImpl::SLEEFGNUABI, "sleefgnuabi", "SIMD Library for Evaluating Elementary Functions"), clEnumValN(TargetLibraryInfoImpl::ArmPL, "ArmPL", "Arm Performance Libraries"), clEnumValN(TargetLibraryInfoImpl::AMDLIBM, "AMDLIBM", "AMD vector math library"))) static
Referenced by initializeLibCalls().
Signatures
const FuncProtoTy Signatures[] static
Initial value:
= {
#define TLI_DEFINE_SIG
}
Definition at line 85 of file TargetLibraryInfo.cpp.
Referenced by constructEntryMetadata(), emitEntryMD(), llvm::BalancedPartitioning::moveGain(), and translateMetadata().
VecFuncs_Accelerate
const VecDesc VecFuncs_Accelerate[] static
Initial value:
= {
#define TLI_DEFINE_ACCELERATE_VECFUNCS
}
Definition at line 1279 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_AMDLIBM
const VecDesc VecFuncs_AMDLIBM[]
Initial value:
= {
#define TLI_DEFINE_AMDLIBM_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX)                   \
}
Definition at line 1355 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_ArmPL
const VecDesc VecFuncs_ArmPL[] static
Initial value:
= {
#define TLI_DEFINE_ARMPL_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX, CC)               \
}
Definition at line 1347 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_DarwinLibSystemM
const VecDesc VecFuncs_DarwinLibSystemM[] static
Initial value:
= {
#define TLI_DEFINE_DARWIN_LIBSYSTEM_M_VECFUNCS
}
Definition at line 1285 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_LIBMVEC_AARCH64
const VecDesc VecFuncs_LIBMVEC_AARCH64[] static
Initial value:
= {
#define TLI_DEFINE_LIBMVEC_AARCH64_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX, CC)               \
}
Definition at line 1297 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_LIBMVEC_X86
const VecDesc VecFuncs_LIBMVEC_X86[] static
Initial value:
= {
#define TLI_DEFINE_LIBMVEC_X86_VECFUNCS
}
Definition at line 1291 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_MASSV
const VecDesc VecFuncs_MASSV[] static
Initial value:
= {
#define TLI_DEFINE_MASSV_VECFUNCS
}
Definition at line 1305 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_SLEEFGNUABI_VF2
const VecDesc VecFuncs_SLEEFGNUABI_VF2[] static
Initial value:
= {
#define TLI_DEFINE_SLEEFGNUABI_VF2_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, VABI_PREFIX)                         \
}
Definition at line 1317 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_SLEEFGNUABI_VF4
const VecDesc VecFuncs_SLEEFGNUABI_VF4[] static
Initial value:
= {
#define TLI_DEFINE_SLEEFGNUABI_VF4_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, VABI_PREFIX)                         \
}
Definition at line 1324 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_SLEEFGNUABI_VFScalable
const VecDesc VecFuncs_SLEEFGNUABI_VFScalable[] static
Initial value:
= {
#define TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX)                   \
}
Definition at line 1331 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_SLEEFGNUABI_VFScalableRISCV
const VecDesc VecFuncs_SLEEFGNUABI_VFScalableRISCV[] static
Initial value:
= {
#define TLI_DEFINE_SLEEFGNUABI_SCALABLE_VECFUNCS_RISCV
#define TLI_DEFINE_VECFUNC(SCAL, VEC, VF, MASK, VABI_PREFIX)                   \
}
Definition at line 1339 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().
VecFuncs_SVML
const VecDesc VecFuncs_SVML[] static
Initial value:
= {
#define TLI_DEFINE_SVML_VECFUNCS
}
Definition at line 1311 of file TargetLibraryInfo.cpp.
Referenced by llvm::TargetLibraryInfoImpl::addVectorizableFunctionsFromVecLib().