LLVM: lib/Support/TextEncoding.cpp File Reference
TextEncoding.cpp File Reference
This file provides utility classes to convert between different character encodings.
#include "llvm/Support/TextEncoding.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/ConvertEBCDIC.h"
#include <system_error>
Functions
static void normalizeCharSetName (StringRef CSName, SmallVectorImpl< char > &Normalized)
static std::optional< TextEncoding > getKnownEncoding (StringRef Name)
static LLVM_ATTRIBUTE_UNUSED void HandleOverflow (size_t &Capacity, char *&Output, size_t &OutputLength, SmallVectorImpl< char > &Result)
Detailed Description
This file provides utility classes to convert between different character encodings.
Definition in file TextEncoding.cpp.
Function Documentation
getKnownEncoding()
std::optional< TextEncoding > getKnownEncoding (StringRef Name) static
Definition at line 47 of file TextEncoding.cpp.
References llvm::SmallString< InternalLen >::equals(), llvm::IBM1047, normalizeCharSetName(), and llvm::UTF8.
Referenced by llvm::TextEncodingConverter::create().
HandleOverflow()
LLVM_ATTRIBUTE_UNUSED void HandleOverflow (size_t & Capacity, char *& Output, size_t & OutputLength, SmallVectorImpl< char > & Result) static
Definition at line 58 of file TextEncoding.cpp.
normalizeCharSetName()
void normalizeCharSetName (StringRef CSName, SmallVectorImpl< char > & Normalized) static
Definition at line 32 of file TextEncoding.cpp.
References llvm::isAlnum(), llvm::isDigit(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::toLower().
Referenced by getKnownEncoding().