LLVM: lib/ExecutionEngine/Orc/TargetProcess/UnwindInfoManager.cpp File Reference
UnwindInfoManager.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/UnwindInfoManager.h"
#include "llvm/ExecutionEngine/Orc/Shared/OrcRTBridge.h"
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::orc
Macros
#define DEBUG_TYPE "orc"
Functions
static orc::shared::CWrapperFunctionResult llvm_orc_rt_alt_UnwindInfoManager_register (const char *ArgData, size_t ArgSize)
static orc::shared::CWrapperFunctionResult llvm_orc_rt_alt_UnwindInfoManager_deregister (const char *ArgData, size_t ArgSize)
Variables
static const char * llvm::orc::AddFnName
static const char * llvm::orc::RemoveFnName
static std::unique_ptr< UnwindInfoManager > llvm::orc::Instance
static int(* llvm::orc::RemoveFindDynamicUnwindSections)(void *) = nullptr
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "orc"
Definition at line 17 of file UnwindInfoManager.cpp.
Function Documentation
llvm_orc_rt_alt_UnwindInfoManager_deregister()
orc::shared::CWrapperFunctionResult llvm_orc_rt_alt_UnwindInfoManager_deregister (const char * ArgData, size_t ArgSize) static
Definition at line 41 of file UnwindInfoManager.cpp.
References llvm::orc::UnwindInfoManager::deregisterSections(), and llvm::release.
Referenced by llvm::orc::UnwindInfoManager::addBootstrapSymbols().
llvm_orc_rt_alt_UnwindInfoManager_register()
orc::shared::CWrapperFunctionResult llvm_orc_rt_alt_UnwindInfoManager_register (const char * ArgData, size_t ArgSize) static
Definition at line 24 of file UnwindInfoManager.cpp.
References llvm::orc::UnwindInfoManager::registerSections(), and llvm::release.
Referenced by llvm::orc::UnwindInfoManager::addBootstrapSymbols().