LLVM: lib/Target/VE/VETargetMachine.cpp File Reference
VETargetMachine.cpp File Reference
#include "VETargetMachine.h"
#include "TargetInfo/VETargetInfo.h"
#include "VE.h"
#include "VEMachineFunctionInfo.h"
#include "VETargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include <optional>
Macros
#define DEBUG_TYPE "ve"
Functions
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVETarget ()
static std::string computeDataLayout (const Triple &T)
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static std::unique_ptr< TargetLoweringObjectFile > createTLOF ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ve"
Definition at line 27 of file VETargetMachine.cpp.
Function Documentation
computeDataLayout()
std::string computeDataLayout (const Triple & T) static
Definition at line 38 of file VETargetMachine.cpp.
References T.
createTLOF()
std::unique_ptr< TargetLoweringObjectFile > createTLOF () static
Definition at line 83 of file VETargetMachine.cpp.
getEffectiveRelocModel()
Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 70 of file VETargetMachine.cpp.
References llvm::Reloc::Static.
LLVMInitializeVETarget()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVETarget ()
Definition at line 29 of file VETargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheVETarget(), llvm::initializeVEAsmPrinterPass(), llvm::initializeVEDAGToDAGISelLegacyPass(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, and X.