LLVM: lib/Target/WebAssembly/AsmParser/WebAssemblyAsmParser.cpp File Reference
WebAssemblyAsmParser.cpp File Reference
This file is part of the WebAssembly Assembler.
#include "AsmParser/WebAssemblyAsmTypeCheck.h"
#include "MCTargetDesc/WebAssemblyMCAsmInfo.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "MCTargetDesc/WebAssemblyMCTypeUtilities.h"
#include "MCTargetDesc/WebAssemblyTargetStreamer.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/SourceMgr.h"
#include "WebAssemblyGenAsmMatcher.inc"
Macros
#define DEBUG_TYPE "wasm-asm-parser"
#define GET_ASSEMBLER_HEADER
#define GET_REGISTER_MATCHER
#define GET_SUBTARGET_FEATURE_NAME
#define GET_MATCHER_IMPLEMENTATION
Functions
static const char * getSubtargetFeatureName (uint64_t Val)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyAsmParser ()
StringRef getMnemonic (unsigned Opc)
Detailed Description
This file is part of the WebAssembly Assembler.
It contains code to translate a parsed .s file into MCInsts.
Definition in file WebAssemblyAsmParser.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-asm-parser"
Definition at line 40 of file WebAssemblyAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 312 of file WebAssemblyAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 1298 of file WebAssemblyAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 1296 of file WebAssemblyAsmParser.cpp.
GET_SUBTARGET_FEATURE_NAME
#define GET_SUBTARGET_FEATURE_NAME
Definition at line 1297 of file WebAssemblyAsmParser.cpp.
Function Documentation
getMnemonic()
StringRef getMnemonic (unsigned Opc)
Definition at line 1301 of file WebAssemblyAsmParser.cpp.
References assert(), and Opc.
Referenced by llvm::WebAssemblyAsmTypeCheck::typeCheck().
getSubtargetFeatureName()
const char * getSubtargetFeatureName (uint64_t Val) static
References Float, and llvm::Integer.
LLVMInitializeWebAssemblyAsmParser()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyAsmParser ()
Definition at line 1291 of file WebAssemblyAsmParser.cpp.
References llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), X, and Y.