LLVM: lib/CodeGen/WindowsSecureHotPatching.cpp File Reference
WindowsSecureHotPatching.cpp File Reference
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/LineIterator.h"
#include "llvm/Support/MemoryBuffer.h"
Macros
#define DEBUG_TYPE "windows-secure-hot-patch"
Functions
INITIALIZE_PASS (WindowsSecureHotPatching, "windows-secure-hot-patch", "Mark functions for Windows hot patch support", false, false) ModulePass *llvm
static bool TypeContainsPointers (Type *ty)
static bool globalVariableNeedsRedirect (GlobalVariable *GV)
static GlobalVariable * getOrCreateRefVariable (Function &F, SmallDenseMap< GlobalVariable *, GlobalVariable * > &RefMapping, GlobalVariable *GV)
static Value * rewriteGlobalVariablesInConstant (Constant *C, SmallDenseMap< GlobalVariable *, Value * > &GVLoadMap, IRBuilder<> &IRBuilderAtEntry)
static bool searchConstantExprForGlobalVariables (Value *V, SmallDenseMap< GlobalVariable *, Value * > &GVLoadMap, SmallVector< GlobalVariableUse > &GVUses)
Variables
static cl::opt< std::string > LLVMMSSecureHotPatchFunctionsFile ("ms-secure-hotpatch-functions-file", cl::value_desc("filename"), cl::desc("A file containing list of mangled function names to mark for " "Windows Secure Hot-Patching"))
static cl::list< std::string > LLVMMSSecureHotPatchFunctionsList ("ms-secure-hotpatch-functions-list", cl::value_desc("list"), cl::desc("A list of mangled function names to mark for Windows Secure " "Hot-Patching"), cl::CommaSeparated)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "windows-secure-hot-patch"
Definition at line 153 of file WindowsSecureHotPatching.cpp.
Function Documentation
getOrCreateRefVariable()
GlobalVariable * getOrCreateRefVariable (Function & F, SmallDenseMap< GlobalVariable *, GlobalVariable * > & RefMapping, GlobalVariable * GV) static
Definition at line 346 of file WindowsSecureHotPatching.cpp.
References llvm::concat(), llvm::dwarf_linker::DebugInfo, F, llvm::PointerType::get(), llvm::DIScope::getFile(), llvm::ConstantExpr::getGetElementPtr(), llvm::Value::getName(), llvm::DataLayout::getTypeSizeInBits(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::NotThreadLocal, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
globalVariableNeedsRedirect()
bool globalVariableNeedsRedirect (GlobalVariable * GV) static
Definition at line 294 of file WindowsSecureHotPatching.cpp.
References llvm::Value::getName(), llvm::GlobalValue::getValueType(), llvm::GlobalVariable::hasAttribute(), llvm::GlobalVariable::isConstant(), llvm::StringRef::starts_with(), and TypeContainsPointers().
Referenced by rewriteGlobalVariablesInConstant(), and searchConstantExprForGlobalVariables().
INITIALIZE_PASS()
INITIALIZE_PASS (WindowsSecureHotPatching , "windows-secure-hot-patch" , "Mark functions for Windows hot patch support" , false , false)
Definition at line 201 of file WindowsSecureHotPatching.cpp.
References llvm::createWindowsSecureHotPatchingPass().
rewriteGlobalVariablesInConstant()
Value * rewriteGlobalVariablesInConstant (Constant * C, SmallDenseMap< GlobalVariable *, Value * > & GVLoadMap, IRBuilder<> & IRBuilderAtEntry) static
Definition at line 396 of file WindowsSecureHotPatching.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::at(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), globalVariableNeedsRedirect(), llvm::IRBuilderBase::Insert(), OpIndex, llvm::SmallVectorTemplateBase< T, bool >::push_back(), rewriteGlobalVariablesInConstant(), and llvm::User::setOperand().
Referenced by rewriteGlobalVariablesInConstant().
searchConstantExprForGlobalVariables()
bool searchConstantExprForGlobalVariables (Value * V, SmallDenseMap< GlobalVariable *, Value * > & GVLoadMap, SmallVector< GlobalVariableUse > & GVUses) static
Definition at line 447 of file WindowsSecureHotPatching.cpp.
References llvm::dyn_cast(), globalVariableNeedsRedirect(), OpIndex, and searchConstantExprForGlobalVariables().
Referenced by searchConstantExprForGlobalVariables().
TypeContainsPointers()
bool TypeContainsPointers (Type * ty) static
Definition at line 270 of file WindowsSecureHotPatching.cpp.
References llvm::Type::ArrayTyID, llvm::Type::getArrayElementType(), llvm::Type::getStructElementType(), llvm::Type::getStructNumElements(), llvm::Type::getTypeID(), I, llvm::Type::PointerTyID, llvm::Type::StructTyID, and TypeContainsPointers().
Referenced by globalVariableNeedsRedirect(), and TypeContainsPointers().
Variable Documentation
LLVMMSSecureHotPatchFunctionsFile
cl::opt< std::string > LLVMMSSecureHotPatchFunctionsFile("ms-secure-hotpatch-functions-file", cl::value_desc("filename"), cl::desc("A file containing list of mangled function names to mark for " "Windows Secure Hot-Patching")) ("ms-secure-hotpatch-functions-file" , cl::value_desc("filename") , cl::desc("A file containing list of mangled function names to mark for " "Windows Secure Hot-Patching")) static
LLVMMSSecureHotPatchFunctionsList
cl::list< std::string > LLVMMSSecureHotPatchFunctionsList("ms-secure-hotpatch-functions-list", cl::value_desc("list"), cl::desc("A list of mangled function names to mark for Windows Secure " "Hot-Patching"), cl::CommaSeparated) ("ms-secure-hotpatch-functions-list" , cl::value_desc("list") , cl::desc("A list of mangled function names to mark for Windows Secure " "Hot-Patching") , cl::CommaSeparated) static