LLVM: lib/Target/X86/X86FrameLowering.cpp File Reference
X86FrameLowering.cpp File Reference
#include "X86FrameLowering.h"
#include "MCTargetDesc/X86MCTargetDesc.h"
#include "X86InstrBuilder.h"
#include "X86InstrInfo.h"
#include "X86MachineFunctionInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/EHPersonalities.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Target/TargetOptions.h"
#include <cstdlib>
Macros
#define DEBUG_TYPE "x86-fl"
Functions
STATISTIC (NumFrameLoopProbe, "Number of loop stack probes used in prologue")
STATISTIC (NumFrameExtraProbe, "Number of extra stack probes generated in prologue")
STATISTIC (NumFunctionUsingPush2Pop2, "Number of functions using push2/pop2")
static unsigned getSUBriOpcode (bool IsLP64)
static unsigned getADDriOpcode (bool IsLP64)
static unsigned getSUBrrOpcode (bool IsLP64)
static unsigned getADDrrOpcode (bool IsLP64)
static unsigned getANDriOpcode (bool IsLP64, int64_t Imm)
static unsigned getLEArOpcode (bool IsLP64)
static unsigned getMOVriOpcode (bool Use64BitReg, int64_t Imm)
static unsigned getPUSHOpcode (const X86Subtarget &ST)
static unsigned getPOPOpcode (const X86Subtarget &ST)
static unsigned getPUSH2Opcode (const X86Subtarget &ST)
static unsigned getPOP2Opcode (const X86Subtarget &ST)
static bool isEAXLiveIn (MachineBasicBlock &MBB)
static bool flagsNeedToBePreservedBeforeTheTerminators (const MachineBasicBlock &MBB)
Check if the flags need to be preserved before the terminators.
static unsigned calculateSetFPREG (uint64_t SPAdjust)
static bool isOpcodeRep (unsigned Opcode)
Return true if an opcode is part of the REP group of instructions.
static bool isFuncletReturnInstr (MachineInstr &MI)
static bool isTailCallOpcode (unsigned Opc)
static bool HasNestArgument (const MachineFunction *MF)
static unsigned GetScratchRegister (bool Is64Bit, bool IsLP64, const MachineFunction &MF, bool Primary)
GetScratchRegister - Get a temp register for performing work in the segmented stack and the Erlang/HiPE stack prologue.
static unsigned getHiPELiteral (NamedMDNode *HiPELiteralsMD, const StringRef LiteralName)
Lookup an ERTS parameter in the !hipe.literals named metadata node.
static bool blockEndIsUnreachable (const MachineBasicBlock &MBB, MachineBasicBlock::const_iterator MBBI)
static int computeFPBPAlignmentGap (MachineFunction &MF, const TargetRegisterClass *RC, unsigned NumSpilledRegs)
static bool isFPBPAccess (const MachineInstr &MI, Register FP, Register BP, const TargetRegisterInfo *TRI, bool &AccessFP, bool &AccessBP)
static bool isInvoke (const MachineInstr &MI, bool InsideEHLabels)
Variables
constexpr int64_t MaxSPChunk = (1LL << 31) - 1
static const uint64_t kSplitStackAvailable = 256
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-fl"
Definition at line 39 of file X86FrameLowering.cpp.
Function Documentation
blockEndIsUnreachable()
bool blockEndIsUnreachable (const MachineBasicBlock & MBB, MachineBasicBlock::const_iterator MBBI) static
Definition at line 3551 of file X86FrameLowering.cpp.
References llvm::all_of(), MBB, MBBI, and MI.
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr().
calculateSetFPREG()
unsigned calculateSetFPREG (uint64_t SPAdjust) static
Definition at line 1270 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::getFrameIndexReference().
computeFPBPAlignmentGap()
int computeFPBPAlignmentGap (MachineFunction & MF, const TargetRegisterClass * RC, unsigned NumSpilledRegs) static
Definition at line 4305 of file X86FrameLowering.cpp.
References llvm::alignTo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFunction::getSubtarget(), and TRI.
flagsNeedToBePreservedBeforeTheTerminators()
bool flagsNeedToBePreservedBeforeTheTerminators (const MachineBasicBlock & MBB) static
Check if the flags need to be preserved before the terminators.
This would be the case, if the eflags is live-in of the region composed by the terminators or live-out of that region, without being defined by a terminator.
Definition at line 192 of file X86FrameLowering.cpp.
References MBB, MI, and Reg.
Referenced by llvm::X86FrameLowering::canUseAsEpilogue().
getADDriOpcode()
unsigned getADDriOpcode (bool IsLP64) static
Definition at line 112 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::restoreWin32EHStackPointers().
getADDrrOpcode()
unsigned getADDrrOpcode (bool IsLP64) static
Definition at line 120 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitSPUpdate().
getANDriOpcode()
unsigned getANDriOpcode (bool IsLP64, int64_t Imm) static
Definition at line 124 of file X86FrameLowering.cpp.
getHiPELiteral()
unsigned getHiPELiteral (NamedMDNode * HiPELiteralsMD, const StringRef LiteralName) static
Lookup an ERTS parameter in the !hipe.literals named metadata node.
HiPE provides Erlang Runtime System-internal parameters, such as PCB offsets to fields it needs, through a named metadata node "hipe.literals" containing name-value pairs.
Definition at line 3529 of file X86FrameLowering.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::NamedMDNode::getNumOperands(), llvm::NamedMDNode::getOperand(), llvm::MDString::getString(), llvm::ValueAsMetadata::getValue(), llvm::ConstantInt::getZExtValue(), and llvm::report_fatal_error().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue().
getLEArOpcode()
unsigned getLEArOpcode (bool IsLP64) static
Definition at line 128 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitEpilogue().
getMOVriOpcode()
unsigned getMOVriOpcode (bool Use64BitReg, int64_t Imm) static
Definition at line 132 of file X86FrameLowering.cpp.
References llvm::isInt(), and llvm::isUInt().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitSPUpdate().
getPOP2Opcode()
unsigned getPOP2Opcode (const X86Subtarget & ST) static
Definition at line 171 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::restoreCalleeSavedRegisters().
getPOPOpcode()
unsigned getPOPOpcode (const X86Subtarget & ST) static
Definition at line 164 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitEpilogue(), and llvm::X86FrameLowering::restoreCalleeSavedRegisters().
getPUSH2Opcode()
unsigned getPUSH2Opcode (const X86Subtarget & ST) static
Definition at line 168 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::spillCalleeSavedRegisters().
getPUSHOpcode()
unsigned getPUSHOpcode (const X86Subtarget & ST) static
Definition at line 160 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
GetScratchRegister()
unsigned GetScratchRegister (bool Is64Bit, bool IsLP64, const MachineFunction & MF, bool Primary) static
GetScratchRegister - Get a temp register for performing work in the segmented stack and the Erlang/HiPE stack prologue.
Depending on platform and the properties of the function either one or two registers will be needed. Set primary to true for the first register, false for the second.
Definition at line 3230 of file X86FrameLowering.cpp.
References llvm::CallingConv::Fast, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), HasNestArgument(), llvm::CallingConv::HiPE, llvm::report_fatal_error(), llvm::CallingConv::Tail, and llvm::CallingConv::X86_FastCall.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
getSUBriOpcode()
unsigned getSUBriOpcode (bool IsLP64) static
Definition at line 108 of file X86FrameLowering.cpp.
getSUBrrOpcode()
unsigned getSUBrrOpcode (bool IsLP64) static
Definition at line 116 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitSPUpdate().
HasNestArgument()
bool HasNestArgument (const MachineFunction * MF) static
Definition at line 3216 of file X86FrameLowering.cpp.
References E(), F, llvm::MachineFunction::getFunction(), and I.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), and GetScratchRegister().
isEAXLiveIn()
bool isEAXLiveIn (MachineBasicBlock & MBB) static
Definition at line 175 of file X86FrameLowering.cpp.
References MBB, and Reg.
Referenced by llvm::X86FrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitSPUpdate().
isFPBPAccess()
bool isFPBPAccess (const MachineInstr & MI, Register FP, Register BP, const TargetRegisterInfo * TRI, bool & AccessFP, bool & AccessBP) static
Definition at line 4467 of file X86FrameLowering.cpp.
References FP, MI, and TRI.
Referenced by llvm::X86FrameLowering::spillFPBP().
isFuncletReturnInstr()
bool isFuncletReturnInstr (MachineInstr & MI) static
Definition at line 2333 of file X86FrameLowering.cpp.
References llvm_unreachable, and MI.
isInvoke()
bool isInvoke (const MachineInstr & MI, bool InsideEHLabels) static
Definition at line 4487 of file X86FrameLowering.cpp.
References MBB, MBBI, and MI.
Referenced by llvm::X86FrameLowering::spillFPBP().
isOpcodeRep()
bool isOpcodeRep (unsigned Opcode) static
Return true if an opcode is part of the REP group of instructions.
Definition at line 1475 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitPrologue().
isTailCallOpcode()
bool isTailCallOpcode (unsigned Opc) static
Definition at line 2399 of file X86FrameLowering.cpp.
References Opc.
STATISTIC() [1/3]
STATISTIC (NumFrameExtraProbe , "Number of extra stack probes generated in prologue")
STATISTIC() [2/3]
STATISTIC (NumFrameLoopProbe , "Number of loop stack probes used in prologue")
STATISTIC() [3/3]
STATISTIC (NumFunctionUsingPush2Pop2 , "Number of functions using push2/pop2")
Variable Documentation
kSplitStackAvailable
const uint64_t kSplitStackAvailable = 256 static
Definition at line 3266 of file X86FrameLowering.cpp.
MaxSPChunk
int64_t MaxSPChunk = (1LL << 31) - 1 constexpr
Definition at line 226 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitSPUpdate().