LLVM: lib/Target/X86/X86InstCombineIntrinsic.cpp File Reference
X86InstCombineIntrinsic.cpp File Reference
This file implements a TargetTransformInfo analysis pass specific to the X86 target machine.
#include "X86TargetTransformInfo.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include <optional>
Macros
#define DEBUG_TYPE "x86tti"
Functions
static Constant * getNegativeIsTrueBoolVec (Constant *V, const DataLayout &DL)
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
static Value * getBoolVecFromMask (Value *Mask, const DataLayout &DL)
Convert the x86 XMM integer vector mask to a vector of bools based on each element's most significant bit (the sign bit).
static Instruction * simplifyX86MaskedLoad (IntrinsicInst &II, InstCombiner &IC)
static bool simplifyX86MaskedStore (IntrinsicInst &II, InstCombiner &IC)
static Value * simplifyX86immShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86varShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86pack (IntrinsicInst &II, InstCombiner::BuilderTy &Builder, bool IsSigned)
static Value * simplifyX86pmulh (IntrinsicInst &II, InstCombiner::BuilderTy &Builder, bool IsSigned, bool IsRounding)
static Value * simplifyX86pmadd (IntrinsicInst &II, InstCombiner::BuilderTy &Builder, bool IsPMADDWD)
static Value * simplifyX86movmsk (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86addcarry (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyTernarylogic (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86insertps (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86extrq (IntrinsicInst &II, Value *Op0, ConstantInt *CILength, ConstantInt *CIIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86insertq (IntrinsicInst &II, Value *Op0, Value *Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86pshufb (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert pshufb* to shufflevector if the mask is constant.
static Value * simplifyX86vpermilvar (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
static Value * simplifyX86vpermv (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
static Value * simplifyX86vpermv3 (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermi2/vpermt2 to shufflevector if the mask is constant.
static bool simplifyX86VPERMMask (Instruction *II, bool IsBinary, InstCombiner &IC)
Detailed Description
This file implements a TargetTransformInfo analysis pass specific to the X86 target machine.
It uses the target's detailed information to provide more precise answers to certain TTI queries, while letting the target independent and default TTI implementations handle the rest.
Definition in file X86InstCombineIntrinsic.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86tti"
Definition at line 26 of file X86InstCombineIntrinsic.cpp.
Function Documentation
getBoolVecFromMask()
Value * getBoolVecFromMask (Value * Mask, const DataLayout & DL) static
Convert the x86 XMM integer vector mask to a vector of bools based on each element's most significant bit (the sign bit).
Definition at line 41 of file X86InstCombineIntrinsic.cpp.
References DL, llvm::dyn_cast(), getNegativeIsTrueBoolVec(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by simplifyX86MaskedLoad(), and simplifyX86MaskedStore().
getNegativeIsTrueBoolVec()
Constant * getNegativeIsTrueBoolVec (Constant * V, const DataLayout & DL) static
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
Definition at line 30 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::ConstantFoldCompareInstOperands(), DL, llvm::ConstantExpr::getBitCast(), llvm::VectorType::getInteger(), llvm::Constant::getNullValue(), and llvm::CmpInst::ICMP_SGT.
Referenced by getBoolVecFromMask(), and llvm::X86TTIImpl::instCombineIntrinsic().
simplifyTernarylogic()
Value * simplifyTernarylogic (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 669 of file X86InstCombineIntrinsic.cpp.
References A(), llvm::And, assert(), B(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), II, llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::match(), llvm::Or, and llvm::Xor.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86addcarry()
Value * simplifyX86addcarry (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 642 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::PoisonValue::get(), llvm::Type::getStructElementType(), llvm::Value::getType(), II, llvm::Type::isIntegerTy(), llvm::MIPatternMatch::m_ZeroInt(), and llvm::PatternMatch::match().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86extrq()
Value * simplifyX86extrq (IntrinsicInst & II, Value * Op0, ConstantInt * CILength, ConstantInt * CIIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 1796 of file X86InstCombineIntrinsic.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ConstantAggregateZero::get(), llvm::ConstantVector::get(), llvm::FixedVectorType::get(), llvm::UndefValue::get(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::ConstantInt::getValue(), llvm::APInt::getZExtValue(), II, llvm::Length, llvm::APInt::lshrInPlace(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86immShift()
Value * simplifyX86immShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 115 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::BitWidth, llvm::cast(), llvm::computeKnownBits(), llvm::Count, llvm::dyn_cast(), llvm::ConstantAggregateZero::get(), llvm::APInt::getBitsSet(), llvm::KnownBits::getMaxValue(), llvm::KnownBits::getMinValue(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), II, llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::APInt::isZero(), llvm::KnownBits::isZero(), llvm_unreachable, llvm::APInt::uge(), and llvm::APInt::ult().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86insertps()
Value * simplifyX86insertps (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 1737 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::ConstantAggregateZero::get(), and II.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86insertq()
Value * simplifyX86insertq (IntrinsicInst & II, Value * Op0, Value * Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 1885 of file X86InstCombineIntrinsic.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ConstantVector::get(), llvm::FixedVectorType::get(), llvm::UndefValue::get(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::APInt::getLowBitsSet(), llvm::APInt::getZExtValue(), II, llvm::Length, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::APInt::shl(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86MaskedLoad()
Instruction * simplifyX86MaskedLoad (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 58 of file X86InstCombineIntrinsic.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilderBase::CreateMaskedLoad(), getBoolVecFromMask(), llvm::InstCombiner::getDataLayout(), llvm::Constant::getNullValue(), II, llvm::isa(), Ptr, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86MaskedStore()
bool simplifyX86MaskedStore (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 82 of file X86InstCombineIntrinsic.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::InstCombiner::eraseInstFromFunction(), llvm::PointerType::get(), getBoolVecFromMask(), llvm::Value::getContext(), llvm::InstCombiner::getDataLayout(), II, llvm::isa(), and Ptr.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86movmsk()
Value * simplifyX86movmsk (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 611 of file X86InstCombineIntrinsic.cpp.
References llvm::cast(), llvm::VectorType::getInteger(), llvm::Type::getIntNTy(), llvm::Constant::getNullValue(), llvm::Value::getType(), II, and llvm::isa().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pack()
Value * simplifyX86pack (IntrinsicInst & II, InstCombiner::BuilderTy & Builder, bool IsSigned) static
Definition at line 433 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::UndefValue::get(), llvm::Constant::getIntegerValue(), llvm::APInt::getLowBitsSet(), getNumElements(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::Value::getType(), llvm::APInt::getZero(), II, llvm::isa(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::APInt::sext().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pmadd()
Value * simplifyX86pmadd (IntrinsicInst & II, InstCombiner::BuilderTy & Builder, bool IsPMADDWD) static
Definition at line 557 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::ConstantAggregateZero::get(), llvm::Value::getType(), llvm::Hi, I, II, llvm::isa(), llvm::Lo, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pmulh()
Value * simplifyX86pmulh (IntrinsicInst & II, InstCombiner::BuilderTy & Builder, bool IsSigned, bool IsRounding) static
Definition at line 499 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::ConstantAggregateZero::get(), llvm::FixedVectorType::get(), llvm::IntegerType::get(), llvm::FixedVectorType::getExtendedElementVectorType(), llvm::Value::getType(), II, llvm::isa(), LHS, llvm::PatternMatch::m_One(), llvm::PatternMatch::match(), Mul, and RHS.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pshufb()
Value * simplifyX86pshufb (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert pshufb* to shufflevector if the mask is constant.
Definition at line 1976 of file X86InstCombineIntrinsic.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::Constant::getNullValue(), I, II, and llvm::isa().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86varShift()
Value * simplifyX86varShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 297 of file X86InstCombineIntrinsic.cpp.
References llvm::all_of(), assert(), llvm::BitWidth, llvm::cast(), llvm::computeKnownBits(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::Type::getIntegerBitWidth(), llvm::KnownBits::getMaxValue(), llvm::Constant::getNullValue(), llvm::APInt::getZExtValue(), I, II, llvm::isa_and_nonnull(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::APInt::uge(), and llvm::APInt::ult().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86vpermilvar()
Value * simplifyX86vpermilvar (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
Definition at line 2021 of file X86InstCombineIntrinsic.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::APInt::getLoBits(), I, II, llvm::isa(), llvm::APInt::lshrInPlace(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86VPERMMask()
bool simplifyX86VPERMMask (Instruction * II, bool IsBinary, InstCombiner & IC) static
Definition at line 2138 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::cast(), llvm::APInt::getLowBitsSet(), II, llvm::isPowerOf2_32(), llvm::Log2_32(), and llvm::InstCombiner::SimplifyDemandedBits().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86vpermv()
Value * simplifyX86vpermv (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
Definition at line 2068 of file X86InstCombineIntrinsic.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), I, II, llvm::isa(), and Size.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86vpermv3()
Value * simplifyX86vpermv3 (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermi2/vpermt2 to shufflevector if the mask is constant.
Definition at line 2102 of file X86InstCombineIntrinsic.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), I, II, llvm::isa(), and Size.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().