LLVM: lib/Target/X86/X86IndirectBranchTracking.cpp File Reference
X86IndirectBranchTracking.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/IR/Module.h"
Macros
#define DEBUG_TYPE "x86-indirect-branch-tracking"
Functions
STATISTIC (NumEndBranchAdded, "Number of ENDBR instructions added")
static bool IsCallReturnTwice (llvm::MachineOperand &MOp)
static bool needsPrologueENDBR (MachineFunction &MF, const Module *M)
Variables
cl::opt< bool > IndirectBranchTracking ("x86-indirect-branch-tracking", cl::init(false), cl::Hidden, cl::desc("Enable X86 indirect branch tracking pass."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-indirect-branch-tracking"
Definition at line 30 of file X86IndirectBranchTracking.cpp.
Function Documentation
IsCallReturnTwice()
bool IsCallReturnTwice (llvm::MachineOperand & MOp) static
Definition at line 89 of file X86IndirectBranchTracking.cpp.
References llvm::dyn_cast(), llvm::MachineOperand::getGlobal(), and llvm::MachineOperand::isGlobal().
needsPrologueENDBR()
bool needsPrologueENDBR (MachineFunction & MF, const Module * M) static
Definition at line 100 of file X86IndirectBranchTracking.cpp.
References F, llvm::TargetMachine::getCodeModel(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getTarget(), and llvm::CodeModel::Large.
STATISTIC()
STATISTIC (NumEndBranchAdded , "Number of ENDBR instructions added")
Variable Documentation
IndirectBranchTracking
cl::opt< bool > IndirectBranchTracking("x86-indirect-branch-tracking", cl::init(false), cl::Hidden, cl::desc("Enable X86 indirect branch tracking pass.")) ("x86-indirect-branch-tracking" , cl::init(false) , cl::Hidden , cl::desc("Enable X86 indirect branch tracking pass."))