LLVM: lib/Target/X86/X86TileConfig.cpp File Reference
X86TileConfig.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TileShapeInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "tileconfig"
Functions
INITIALIZE_PASS_BEGIN (X86TileConfig, DEBUG_TYPE, "Tile Register Configure", false, false) INITIALIZE_PASS_END(X86TileConfig
Tile Register false unsigned getAMXRegNum (MachineRegisterInfo *MRI, Register Reg)
static void collectVirtRegShapes (MachineRegisterInfo *MRI, VirtRegMap &VRM, Register VirtReg, SmallVector< ShapeT, 8 > &Phys2Shapes)
static bool isAMXRegClass (MachineRegisterInfo *MRI, Register Reg)
Variables
DEBUG_TYPE
Tile Register Configure
Tile Register false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tileconfig"
Definition at line 38 of file X86TileConfig.cpp.
Function Documentation
collectVirtRegShapes()
void collectVirtRegShapes (MachineRegisterInfo * MRI, VirtRegMap & VRM, Register VirtReg, SmallVector< ShapeT, 8 > & Phys2Shapes) static
Definition at line 93 of file X86TileConfig.cpp.
References assert(), getAMXRegNum(), llvm::ShapeT::getCol(), llvm::VirtRegMap::getPhys(), llvm::ShapeT::getRow(), llvm::VirtRegMap::getShape(), llvm::ShapeT::getShapeNum(), isValid(), and MRI.
getAMXRegNum()
Tile Register false unsigned getAMXRegNum (MachineRegisterInfo * MRI, Register Reg)
Definition at line 77 of file X86TileConfig.cpp.
References getAMXRegNum(), MRI, and Reg.
Referenced by collectVirtRegShapes(), getAMXRegNum(), and isAMXRegClass().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86TileConfig , DEBUG_TYPE , "Tile Register Configure" , false , false)
References DEBUG_TYPE, and INITIALIZE_PASS_DEPENDENCY.
isAMXRegClass()
bool isAMXRegClass (MachineRegisterInfo * MRI, Register Reg) static
Definition at line 130 of file X86TileConfig.cpp.
References getAMXRegNum(), MRI, and Reg.
Variable Documentation
Configure
Tile Register Configure
Definition at line 74 of file X86TileConfig.cpp.
DEBUG_TYPE
DEBUG_TYPE
Definition at line 74 of file X86TileConfig.cpp.
false
Tile Register false
Definition at line 74 of file X86TileConfig.cpp.