LLVM: lib/Target/Xtensa/XtensaTargetMachine.cpp File Reference
XtensaTargetMachine.cpp File Reference
#include "XtensaTargetMachine.h"
#include "TargetInfo/XtensaTargetInfo.h"
#include "XtensaMachineFunctionInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/PassRegistry.h"
#include "llvm/Transforms/Scalar.h"
#include <optional>
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXtensaTarget ()
static std::string computeDataLayout (const Triple &TT, StringRef CPU, const TargetOptions &Options, bool IsLittle)
static Reloc::Model getEffectiveRelocModel (bool JIT, std::optional< Reloc::Model > RM)
Function Documentation
computeDataLayout()
std::string computeDataLayout (const Triple & TT, StringRef CPU, const TargetOptions & Options, bool IsLittle) static
Definition at line 35 of file XtensaTargetMachine.cpp.
References Options.
getEffectiveRelocModel()
Reloc::Model getEffectiveRelocModel (bool JIT, std::optional< Reloc::Model > RM) static
Definition at line 42 of file XtensaTargetMachine.cpp.
References llvm::Reloc::Static.
LLVMInitializeXtensaTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXtensaTarget ()
Definition at line 28 of file XtensaTargetMachine.cpp.
References A(), llvm::PassRegistry::getPassRegistry(), llvm::getTheXtensaTarget(), llvm::initializeXtensaAsmPrinterPass(), and LLVM_EXTERNAL_VISIBILITY.