LLVM: lib/Target/AArch64/MCTargetDesc/AArch64InstPrinter.cpp File Reference
AArch64InstPrinter.cpp File Reference
#include "AArch64InstPrinter.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "Utils/AArch64BaseInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <string>
#include "AArch64GenAsmWriter.inc"
#include "AArch64GenAsmWriter1.inc"
Classes
struct LdStNInstrDesc
Macros
#define DEBUG_TYPE "asm-printer"
#define GET_INSTRUCTION_NAME
#define PRINT_ALIAS_INSTR
#define GET_INSTRUCTION_NAME
#define PRINT_ALIAS_INSTR
Functions
static bool isTblTbxInstruction (unsigned Opcode, StringRef &Layout, bool &IsTbx)
static const LdStNInstrDesc * getLdStNInstrDesc (unsigned Opcode)
static MCRegister getNextVectorRegister (MCRegister Reg, unsigned Stride=1)
static bool isValidSysReg (const AArch64SysReg::SysReg &Reg, bool Read, const MCSubtargetInfo &STI)
static const AArch64SysReg::SysReg * lookupSysReg (unsigned Val, bool Read, const MCSubtargetInfo &STI)
Variables
static const LdStNInstrDesc LdStNInstInfo []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 34 of file AArch64InstPrinter.cpp.
GET_INSTRUCTION_NAME [1/2]
#define GET_INSTRUCTION_NAME
Definition at line 36 of file AArch64InstPrinter.cpp.
GET_INSTRUCTION_NAME [2/2]
#define GET_INSTRUCTION_NAME
Definition at line 36 of file AArch64InstPrinter.cpp.
PRINT_ALIAS_INSTR [1/2]
#define PRINT_ALIAS_INSTR
Definition at line 37 of file AArch64InstPrinter.cpp.
PRINT_ALIAS_INSTR [2/2]
#define PRINT_ALIAS_INSTR
Definition at line 37 of file AArch64InstPrinter.cpp.
Function Documentation
getLdStNInstrDesc()
const LdStNInstrDesc * getLdStNInstrDesc (unsigned Opcode) static
Definition at line 774 of file AArch64InstPrinter.cpp.
References Info, and LdStNInstInfo.
Referenced by llvm::AArch64AppleInstPrinter::printInst().
getNextVectorRegister()
MCRegister getNextVectorRegister (MCRegister Reg, unsigned Stride = 1) static
Definition at line 1649 of file AArch64InstPrinter.cpp.
References llvm_unreachable, and Reg.
Referenced by llvm::AArch64InstPrinter::printVectorList().
isTblTbxInstruction()
bool isTblTbxInstruction (unsigned Opcode, StringRef & Layout, bool & IsTbx) static
Definition at line 386 of file AArch64InstPrinter.cpp.
Referenced by llvm::AArch64AppleInstPrinter::printInst().
isValidSysReg()
bool isValidSysReg (const AArch64SysReg::SysReg & Reg, bool Read, const MCSubtargetInfo & STI) static
Definition at line 2016 of file AArch64InstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::Read, and Reg.
Referenced by lookupSysReg().
lookupSysReg()
const AArch64SysReg::SysReg * lookupSysReg (unsigned Val, bool Read, const MCSubtargetInfo & STI) static
Definition at line 2026 of file AArch64InstPrinter.cpp.
References isValidSysReg(), Range, llvm::Read, and Reg.
Referenced by llvm::AArch64InstPrinter::printMRSSystemRegister(), and llvm::AArch64InstPrinter::printMSRSystemRegister().
Variable Documentation
LdStNInstInfo
const LdStNInstrDesc LdStNInstInfo[] static
Definition at line 431 of file AArch64InstPrinter.cpp.
Referenced by getLdStNInstrDesc().