LLVM: lib/Target/AArch64/Disassembler/AArch64Disassembler.cpp File Reference
AArch64Disassembler.cpp File Reference
#include "AArch64Disassembler.h"
#include "AArch64ExternalSymbolizer.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "MCTargetDesc/AArch64MCTargetDesc.h"
#include "TargetInfo/AArch64TargetInfo.h"
#include "Utils/AArch64BaseInfo.h"
#include "llvm/MC/MCDecoder.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCRelocationInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include <memory>
#include "AArch64GenDisassemblerTables.inc"
#include "AArch64GenInstrInfo.inc"
Macros
#define DEBUG_TYPE "aarch64-disassembler"
#define Success MCDisassembler::Success
#define Fail MCDisassembler::Fail
#define SoftFail MCDisassembler::SoftFail
Typedefs
using DecodeStatus = MCDisassembler::DecodeStatus
Functions
template<int Bits>
static DecodeStatus DecodeSImm (MCInst &Inst, uint64_t Imm, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned RegClassID, unsigned FirstReg, unsigned NumRegsInClass>
static DecodeStatus DecodeSimpleRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR64x8ClassRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned Min, unsigned Max>
static DecodeStatus DecodeZPRMul2_MinMax (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned Min, unsigned Max>
static DecodeStatus DecodeZPR2Mul2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeZK (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPR4Mul4RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMatrixTileListRegisterClass (MCInst &Inst, unsigned RegMask, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZTRRegisterClass (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeMPRRegisterClass (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeMPR8RegisterClass (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeMPR16RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMPR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMPR128RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePPR2Mul2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFixedPointScaleImm32 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeFixedPointScaleImm64 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodePCRelLabel16 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodePCRelLabel19 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodePCRelLabel9 (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemExtend (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMRSSystemRegister (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSRSystemRegister (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMOVLaneInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftRImm (MCInst &Inst, unsigned Imm, unsigned Add)
static DecodeStatus DecodeVecShiftLImm (MCInst &Inst, unsigned Imm, unsigned Add)
static DecodeStatus DecodeVecShiftR64Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR64ImmNarrow (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR32Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR32ImmNarrow (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR16Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR16ImmNarrow (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR8Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL64Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL32Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL16Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL8Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeThreeAddrSRegInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeMoveImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeUnsignedLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSignedLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeExclusiveLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodePairLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeAuthLoadInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddSubERegInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeLogicalImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeModImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeModImmTiedInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeAdrInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddSubImmShift (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeUnconditionalBranch (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static bool isInvalidPState (uint64_t Op1, uint64_t Op2)
static DecodeStatus DecodeSystemPStateImm0_15Instruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSystemPStateImm0_1Instruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeTestAndBranch (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRSeqPairsClassRegisterClass (MCInst &Inst, unsigned RegClassID, unsigned RegNo, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeWSeqPairsClassRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeXSeqPairsClassRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSyspXzrInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSVELogicalImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeZeroImm (MCInst &Inst, const MCDisassembler *Decoder)
template<int ElementWidth>
static DecodeStatus DecodeImm8OptLsl (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSVEIncDecImm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSVCROp (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCPYMemOpInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSETMemOpInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSETMemGoOpInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodePRFMRegInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSMESpillFillInstruction (MCInst &Inst, uint32_t Bits, uint64_t Addr, const MCDisassembler *Decoder)
static MCDisassembler * createAArch64Disassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCSymbolizer * createAArch64ExternalSymbolizer (const Triple &TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAArch64Disassembler ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-disassembler"
Definition at line 33 of file AArch64Disassembler.cpp.
Fail
#define Fail MCDisassembler::Fail
Definition at line 43 of file AArch64Disassembler.cpp.
Referenced by checkedGetHex(), DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeAdrInstruction(), DecodeAuthLoadInstruction(), DecodeExclusiveLdStInstruction(), DecodeGPR64x8ClassRegisterClass(), DecodeGPRSeqPairsClassRegisterClass(), DecodeImm8OptLsl(), DecodeLogicalImmInstruction(), DecodeMatrixTileListRegisterClass(), DecodeMoveImmInstruction(), DecodePairLdStInstruction(), DecodePCRelLabel16(), DecodePPR2Mul2RegisterClass(), DecodePRFMRegInstruction(), DecodeSignedLdStInstruction(), DecodeSImm(), DecodeSimpleRegisterClass(), DecodeSVCROp(), DecodeSVELogicalImmInstruction(), DecodeSyspXzrInstruction(), DecodeSystemPStateImm0_15Instruction(), DecodeSystemPStateImm0_1Instruction(), DecodeThreeAddrSRegInstruction(), DecodeUnsignedLdStInstruction(), DecodeZK(), DecodeZPR2Mul2RegisterClass(), DecodeZPR4Mul4RegisterClass(), DecodeZPRMul2_MinMax(), llvm::object::MachOObjectFile::getChainedFixupsSegments(), parseThunkName(), NodeArray::printAsString(), llvm::sys::RetryAfterSignal(), safeToMergeTerminators(), and llvm::BTFParser::symbolize().
SoftFail
#define SoftFail MCDisassembler::SoftFail
Definition at line 44 of file AArch64Disassembler.cpp.
Referenced by DecodeAuthLoadInstruction(), DecodeExclusiveLdStInstruction(), DecodePairLdStInstruction(), and DecodeSignedLdStInstruction().
Success
#define Success MCDisassembler::Success
Definition at line 42 of file AArch64Disassembler.cpp.
Referenced by canRenameUntilSecondLoad(), collectMetadataInfo(), combineIRFlags(), computeLabelDiff(), llvm::AArch64PrologueEpilogueCommon::convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::convertToNonDenormSingle(), llvm::convertToNonDenormSingle(), createAtomicLibcall(), createCmpXchgInstFun(), DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeAdrInstruction(), DecodeAuthLoadInstruction(), DecodeExclusiveLdStInstruction(), DecodeFixedPointScaleImm32(), DecodeFixedPointScaleImm64(), DecodeFMOVLaneInstruction(), DecodeGPR64x8ClassRegisterClass(), DecodeGPRSeqPairsClassRegisterClass(), DecodeImm8OptLsl(), DecodeLogicalImmInstruction(), DecodeMatrixTileListRegisterClass(), DecodeMemExtend(), DecodeModImmInstruction(), DecodeModImmTiedInstruction(), DecodeMoveImmInstruction(), DecodeMPR128RegisterClass(), DecodeMPR16RegisterClass(), DecodeMPR32RegisterClass(), DecodeMPR64RegisterClass(), DecodeMPR8RegisterClass(), DecodeMPRRegisterClass(), DecodeMRSSystemRegister(), DecodeMSRSystemRegister(), DecodePairLdStInstruction(), DecodePCRelLabel16(), DecodePCRelLabel19(), DecodePCRelLabel9(), DecodePPR2Mul2RegisterClass(), DecodePRFMRegInstruction(), DecodeSignedLdStInstruction(), DecodeSImm(), DecodeSimpleRegisterClass(), DecodeSMESpillFillInstruction(), DecodeSVCROp(), DecodeSVEIncDecImm(), DecodeSVELogicalImmInstruction(), DecodeSyspXzrInstruction(), DecodeSystemPStateImm0_15Instruction(), DecodeSystemPStateImm0_1Instruction(), DecodeTestAndBranch(), DecodeThreeAddrSRegInstruction(), DecodeUnconditionalBranch(), DecodeUnsignedLdStInstruction(), DecodeVecShiftLImm(), DecodeVecShiftRImm(), DecodeZeroImm(), DecodeZK(), DecodeZPR2Mul2RegisterClass(), DecodeZPR4Mul4RegisterClass(), DecodeZPRMul2_MinMax(), DecodeZTRRegisterClass(), llvm::AtomicInfo::EmitAtomicCompareExchange(), llvm::AtomicInfo::EmitAtomicCompareExchangeLibcall(), llvm::AtomicInfo::EmitAtomicCompareExchangeOp(), llvm::LiveDebugVariables::LDVImpl::emitDebugValues(), llvm::AMDGPUAsmPrinter::emitEndOfAsmFile(), emitLoad(), emitStore(), llvm::GIMatchTableExecutor::executeMatchTable(), getCompoundInsn(), llvm::InformationCache::getOrCreateUniqueBlockExecutionSet(), llvm::ScheduleDAGTopologicalSort::GetSubGraph(), llvm::DWARFVerifier::handleDebugStrOffsets(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::Attributor::identifyDefaultAbstractAttributes(), LowerCMP_SWAP(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::AArch64CallLowering::lowerReturn(), llvm::M68kCallLowering::lowerReturn(), llvm::PPCCallLowering::lowerReturn(), mergeCompatibleInvokesImpl(), llvm::patchReplacementInstruction(), llvm::performOptimizedStructLayout(), llvm::RISCVAsmBackend::relaxInstruction(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::orc::SimpleRemoteEPCServer::Setup::setBootstrapMapValue(), sinkLastInstruction(), llvm::streamFile(), llvm::DWARFContext::verify(), and llvm::DWARFVerifier::verifyDebugStrOffsets().
Typedef Documentation
DecodeStatus
using DecodeStatus = MCDisassembler::DecodeStatus
Definition at line 36 of file AArch64Disassembler.cpp.
Function Documentation
createAArch64Disassembler()
MCDisassembler * createAArch64Disassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 1621 of file AArch64Disassembler.cpp.
References T.
Referenced by LLVMInitializeAArch64Disassembler().
createAArch64ExternalSymbolizer()
MCSymbolizer * createAArch64ExternalSymbolizer (const Triple & TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) static
Definition at line 1665 of file AArch64Disassembler.cpp.
Referenced by LLVMInitializeAArch64Disassembler().
DecodeAddSubERegInstruction()
DecodeStatus DecodeAddSubERegInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1050 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and Success.
DecodeAddSubImmShift()
DecodeStatus DecodeAddSubImmShift (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1238 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeAdrInstruction()
DecodeStatus DecodeAdrInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1223 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::SignExtend64(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeAuthLoadInstruction()
DecodeStatus DecodeAuthLoadInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1015 of file AArch64Disassembler.cpp.
References DecodeSImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), SoftFail, and Success.
DecodeCPYMemOpInstruction()
DecodeStatus DecodeCPYMemOpInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1475 of file AArch64Disassembler.cpp.
References DecodeSimpleRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeExclusiveLdStInstruction()
DecodeStatus DecodeExclusiveLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 757 of file AArch64Disassembler.cpp.
References DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), SoftFail, and Success.
DecodeFixedPointScaleImm32()
DecodeStatus DecodeFixedPointScaleImm32 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 198 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
DecodeFixedPointScaleImm64()
DecodeStatus DecodeFixedPointScaleImm64 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 207 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
DecodeFMOVLaneInstruction()
DecodeStatus DecodeFMOVLaneInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 276 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), llvm::MCD::fieldFromInstruction(), and Success.
DecodeGPR64x8ClassRegisterClass()
DecodeStatus DecodeGPR64x8ClassRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 60 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeGPRSeqPairsClassRegisterClass()
DecodeStatus DecodeGPRSeqPairsClassRegisterClass (MCInst & Inst, unsigned RegClassID, unsigned RegNo, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1361 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, Reg, and Success.
Referenced by DecodeWSeqPairsClassRegisterClass(), and DecodeXSeqPairsClassRegisterClass().
DecodeImm8OptLsl()
template<int ElementWidth> DecodeStatus DecodeImm8OptLsl (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1447 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, and Success.
DecodeLogicalImmInstruction()
DecodeStatus DecodeLogicalImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1125 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::AArch64_AM::isValidDecodeLogicalImmediate(), and Success.
DecodeMatrixTileListRegisterClass()
DecodeStatus DecodeMatrixTileListRegisterClass (MCInst & Inst, unsigned RegMask, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 124 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, and Success.
DecodeMemExtend()
DecodeStatus DecodeMemExtend (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 250 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
Referenced by DecodePRFMRegInstruction().
DecodeModImmInstruction()
DecodeStatus DecodeModImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1162 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and Success.
DecodeModImmTiedInstruction()
DecodeStatus DecodeModImmTiedInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1203 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), llvm::MCD::fieldFromInstruction(), and Success.
DecodeMoveImmInstruction()
DecodeStatus DecodeMoveImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 449 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeMPR128RegisterClass()
DecodeStatus DecodeMPR128RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 178 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Reg, and Success.
DecodeMPR16RegisterClass()
DecodeStatus DecodeMPR16RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 151 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Reg, and Success.
DecodeMPR32RegisterClass()
DecodeStatus DecodeMPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 160 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Reg, and Success.
DecodeMPR64RegisterClass()
DecodeStatus DecodeMPR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 169 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Reg, and Success.
DecodeMPR8RegisterClass()
DecodeStatus DecodeMPR8RegisterClass (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 145 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and Success.
DecodeMPRRegisterClass()
DecodeStatus DecodeMPRRegisterClass (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 139 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and Success.
Referenced by DecodeSMESpillFillInstruction().
DecodeMRSSystemRegister()
DecodeStatus DecodeMRSSystemRegister (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 258 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
DecodeMSRSystemRegister()
DecodeStatus DecodeMSRSystemRegister (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 268 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
DecodePairLdStInstruction()
DecodeStatus DecodePairLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 850 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::SignExtend64(), SoftFail, and Success.
DecodePCRelLabel16()
DecodeStatus DecodePCRelLabel16 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 214 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodePCRelLabel19()
DecodeStatus DecodePCRelLabel19 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 229 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCInst::getOpcode(), llvm::SignExtend64(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodePCRelLabel9()
DecodeStatus DecodePCRelLabel9 (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 240 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::SignExtend64(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodePPR2Mul2RegisterClass()
DecodeStatus DecodePPR2Mul2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 187 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodePRFMRegInstruction()
DecodeStatus DecodePRFMRegInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1561 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeMemExtend(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and Success.
DecodeSETMemGoOpInstruction()
DecodeStatus DecodeSETMemGoOpInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1535 of file AArch64Disassembler.cpp.
References DecodeSimpleRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeSETMemOpInstruction()
DecodeStatus DecodeSETMemOpInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1506 of file AArch64Disassembler.cpp.
References DecodeSimpleRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeSignedLdStInstruction()
DecodeStatus DecodeSignedLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 554 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::SignExtend64(), SoftFail, and Success.
DecodeSImm()
template<int Bits> DecodeStatus DecodeSImm (MCInst & Inst, uint64_t Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1432 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, and Success.
Referenced by DecodeAuthLoadInstruction().
DecodeSimpleRegisterClass()
template<unsigned RegClassID, unsigned FirstReg, unsigned NumRegsInClass> DecodeStatus DecodeSimpleRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 47 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeAdrInstruction(), DecodeAuthLoadInstruction(), DecodeCPYMemOpInstruction(), DecodeExclusiveLdStInstruction(), DecodeFMOVLaneInstruction(), DecodeLogicalImmInstruction(), DecodeModImmInstruction(), DecodeModImmTiedInstruction(), DecodeMoveImmInstruction(), DecodePairLdStInstruction(), DecodePRFMRegInstruction(), DecodeSETMemGoOpInstruction(), DecodeSETMemOpInstruction(), DecodeSignedLdStInstruction(), DecodeSMESpillFillInstruction(), DecodeSVELogicalImmInstruction(), DecodeSyspXzrInstruction(), DecodeTestAndBranch(), DecodeThreeAddrSRegInstruction(), and DecodeUnsignedLdStInstruction().
DecodeSMESpillFillInstruction()
DecodeStatus DecodeSMESpillFillInstruction (MCInst & Inst, uint32_t Bits, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1599 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeMPRRegisterClass(), DecodeSimpleRegisterClass(), llvm::MCD::fieldFromInstruction(), and Success.
DecodeSVCROp()
DecodeStatus DecodeSVCROp (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1466 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, and Success.
DecodeSVEIncDecImm()
DecodeStatus DecodeSVEIncDecImm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1459 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
DecodeSVELogicalImmInstruction()
DecodeStatus DecodeSVELogicalImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1409 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::AArch64_AM::isValidDecodeLogicalImmediate(), and Success.
DecodeSyspXzrInstruction()
DecodeStatus DecodeSyspXzrInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1387 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), and Success.
DecodeSystemPStateImm0_15Instruction()
DecodeStatus DecodeSystemPStateImm0_15Instruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1297 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), isInvalidPState(), and Success.
DecodeSystemPStateImm0_1Instruction()
DecodeStatus DecodeSystemPStateImm0_1Instruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1318 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), isInvalidPState(), and Success.
DecodeTestAndBranch()
DecodeStatus DecodeTestAndBranch (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1339 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), llvm::MCD::fieldFromInstruction(), llvm::SignExtend64(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeThreeAddrSRegInstruction()
DecodeStatus DecodeThreeAddrSRegInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 382 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and Success.
DecodeUnconditionalBranch()
DecodeStatus DecodeUnconditionalBranch (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1279 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCD::fieldFromInstruction(), llvm::SignExtend64(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeUnsignedLdStInstruction()
DecodeStatus DecodeUnsignedLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 488 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSimpleRegisterClass(), Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeVecShiftL16Imm()
DecodeStatus DecodeVecShiftL16Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 369 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm().
DecodeVecShiftL32Imm()
DecodeStatus DecodeVecShiftL32Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 363 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm().
DecodeVecShiftL64Imm()
DecodeStatus DecodeVecShiftL64Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 357 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm().
DecodeVecShiftL8Imm()
DecodeStatus DecodeVecShiftL8Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 375 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm().
DecodeVecShiftLImm()
DecodeStatus DecodeVecShiftLImm (MCInst & Inst, unsigned Imm, unsigned Add) static
Definition at line 309 of file AArch64Disassembler.cpp.
References llvm::Add, llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
Referenced by DecodeVecShiftL16Imm(), DecodeVecShiftL32Imm(), DecodeVecShiftL64Imm(), and DecodeVecShiftL8Imm().
DecodeVecShiftR16Imm()
DecodeStatus DecodeVecShiftR16Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 339 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm().
DecodeVecShiftR16ImmNarrow()
DecodeStatus DecodeVecShiftR16ImmNarrow (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 345 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm().
DecodeVecShiftR32Imm()
DecodeStatus DecodeVecShiftR32Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 327 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm().
DecodeVecShiftR32ImmNarrow()
DecodeStatus DecodeVecShiftR32ImmNarrow (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 333 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm().
DecodeVecShiftR64Imm()
DecodeStatus DecodeVecShiftR64Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 315 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm().
DecodeVecShiftR64ImmNarrow()
DecodeStatus DecodeVecShiftR64ImmNarrow (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 321 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm().
DecodeVecShiftR8Imm()
DecodeStatus DecodeVecShiftR8Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 351 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm().
DecodeVecShiftRImm()
DecodeStatus DecodeVecShiftRImm (MCInst & Inst, unsigned Imm, unsigned Add) static
Definition at line 303 of file AArch64Disassembler.cpp.
References llvm::Add, llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
Referenced by DecodeVecShiftR16Imm(), DecodeVecShiftR16ImmNarrow(), DecodeVecShiftR32Imm(), DecodeVecShiftR32ImmNarrow(), DecodeVecShiftR64Imm(), DecodeVecShiftR64ImmNarrow(), and DecodeVecShiftR8Imm().
DecodeWSeqPairsClassRegisterClass()
DecodeStatus DecodeWSeqPairsClassRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1374 of file AArch64Disassembler.cpp.
References DecodeGPRSeqPairsClassRegisterClass().
DecodeXSeqPairsClassRegisterClass()
DecodeStatus DecodeXSeqPairsClassRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1381 of file AArch64Disassembler.cpp.
References DecodeGPRSeqPairsClassRegisterClass().
DecodeZeroImm()
DecodeStatus DecodeZeroImm (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 1426 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and Success.
DecodeZK()
DecodeStatus DecodeZK (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 101 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR2Mul2RegisterClass()
template<unsigned Min, unsigned Max> DecodeStatus DecodeZPR2Mul2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 88 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, Reg, and Success.
DecodeZPR4Mul4RegisterClass()
DecodeStatus DecodeZPR4Mul4RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 112 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPRMul2_MinMax()
template<unsigned Min, unsigned Max> DecodeStatus DecodeZPRMul2_MinMax (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 75 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, Reg, and Success.
DecodeZTRRegisterClass()
DecodeStatus DecodeZTRRegisterClass (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 133 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and Success.
isInvalidPState()
bool isInvalidPState (uint64_t Op1, uint64_t Op2) static
Definition at line 1290 of file AArch64Disassembler.cpp.
Referenced by DecodeSystemPStateImm0_15Instruction(), and DecodeSystemPStateImm0_1Instruction().
LLVMInitializeAArch64Disassembler()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAArch64Disassembler ()
Definition at line 1674 of file AArch64Disassembler.cpp.
References createAArch64Disassembler(), createAArch64ExternalSymbolizer(), llvm::getTheAArch64_32Target(), llvm::getTheAArch64beTarget(), llvm::getTheAArch64leTarget(), llvm::getTheARM64_32Target(), llvm::getTheARM64Target(), llvm::TargetRegistry::RegisterMCDisassembler(), and llvm::TargetRegistry::RegisterMCSymbolizer().