LLVM: lib/Target/AArch64/AArch64MachineFunctionInfo.cpp File Reference
AArch64MachineFunctionInfo.cpp File Reference
This file implements AArch64-specific per-machine-function information.
#include "AArch64MachineFunctionInfo.h"
#include "AArch64InstrInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
Functions
static std::optional< uint64_t > getSVEStackSize (const AArch64FunctionInfo &MFI, uint64_t(AArch64FunctionInfo::*GetStackSize)() const)
static SignReturnAddress GetSignReturnAddress (const Function &F)
static bool ShouldSignWithBKey (const Function &F, const AArch64Subtarget &STI)
static bool hasELFSignedGOTHelper (const Function &F, const AArch64Subtarget *STI)
static bool isLRSpilled (const MachineFunction &MF)
Detailed Description
This file implements AArch64-specific per-machine-function information.
Definition in file AArch64MachineFunctionInfo.cpp.
Function Documentation
GetSignReturnAddress()
SignReturnAddress GetSignReturnAddress (const Function & F) static
Definition at line 67 of file AArch64MachineFunctionInfo.cpp.
References llvm::All, llvm::StringSwitch< T, R >::Case(), F, llvm::None, and llvm::NonLeaf.
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo(), and llvm::ARMFunctionInfo::ARMFunctionInfo().
getSVEStackSize()
std::optional< uint64_t > getSVEStackSize (const AArch64FunctionInfo & MFI, uint64_t(AArch64FunctionInfo::* GetStackSize)() const) static
Definition at line 28 of file AArch64MachineFunctionInfo.cpp.
References llvm::AArch64FunctionInfo::hasCalculatedStackSizeSVE().
Referenced by llvm::yaml::AArch64FunctionInfo::AArch64FunctionInfo().
hasELFSignedGOTHelper()
bool hasELFSignedGOTHelper (const Function & F, const AArch64Subtarget * STI) static
Definition at line 99 of file AArch64MachineFunctionInfo.cpp.
References llvm::mdconst::extract_or_null(), F, llvm::AArch64Subtarget::getTargetTriple(), and llvm::Triple::isOSBinFormatELF().
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo().
isLRSpilled()
bool isLRSpilled (const MachineFunction & MF) static
Definition at line 170 of file AArch64MachineFunctionInfo.cpp.
References llvm::any_of(), llvm::MachineFunction::getFrameInfo(), and Info.
Referenced by llvm::yaml::ARMFunctionInfo::ARMFunctionInfo(), llvm::AArch64FunctionInfo::needsShadowCallStackPrologueEpilogue(), and llvm::AArch64FunctionInfo::shouldSignReturnAddress().
ShouldSignWithBKey()
bool ShouldSignWithBKey (const Function & F, const AArch64Subtarget & STI) static
Definition at line 84 of file AArch64MachineFunctionInfo.cpp.
References assert(), F, llvm::AArch64Subtarget::getTargetTriple(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::Triple::isOSWindows().
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo().