LLVM: lib/Target/AArch64/MCTargetDesc/AArch64MCAsmInfo.cpp File Reference
AArch64MCAsmInfo.cpp File Reference
#include "AArch64MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/TargetParser/Triple.h"
Enumerations
enum AsmWriterVariantTy { Default = -1 , Generic = 0 , Apple = 1 }
Functions
static bool evaluate (const MCSpecifierExpr &Expr, MCValue &Res, const MCAssembler *Asm)
Variables
static cl::opt< AsmWriterVariantTy > AsmWriterVariant ("aarch64-neon-syntax", cl::init(Default), cl::desc("Choose style of NEON code to emit from AArch64 backend:"), cl::values(clEnumValN(Generic, "generic", "Emit generic NEON assembly"), clEnumValN(Apple, "apple", "Emit Apple-style NEON assembly")))
const MCAsmInfo::AtSpecifier COFFAtSpecifiers []
const MCAsmInfo::AtSpecifier ELFAtSpecifiers []
const MCAsmInfo::AtSpecifier MachOAtSpecifiers []
Enumeration Type Documentation
AsmWriterVariantTy
enum AsmWriterVariantTy
Enumerator
Default
Generic
Apple
Definition at line 22 of file AArch64MCAsmInfo.cpp.
Function Documentation
evaluate()
bool evaluate (const MCSpecifierExpr & Expr, MCValue & Res, const MCAssembler * Asm) static
Definition at line 123 of file AArch64MCAsmInfo.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), llvm::MCSpecifierExpr::getSpecifier(), llvm::MCSpecifierExpr::getSubExpr(), llvm::MCValue::getSubSym(), and llvm::MCValue::setSpecifier().
Referenced by llvm::AArch64MCAsmInfoDarwin::evaluateAsRelocatableImpl(), llvm::AArch64MCAsmInfoELF::evaluateAsRelocatableImpl(), llvm::AArch64MCAsmInfoGNUCOFF::evaluateAsRelocatableImpl(), llvm::AArch64MCAsmInfoMicrosoftCOFF::evaluateAsRelocatableImpl(), llvm::MipsCOFFMCAsmInfo::evaluateAsRelocatableImpl(), and llvm::MipsELFMCAsmInfo::evaluateAsRelocatableImpl().
Variable Documentation
AsmWriterVariant
cl::opt< AsmWriterVariantTy > AsmWriterVariant("aarch64-neon-syntax", cl::init(Default), cl::desc("Choose style of NEON code to emit from AArch64 backend:"), cl::values(clEnumValN(Generic, "generic", "Emit generic NEON assembly"), clEnumValN(Apple, "apple", "Emit Apple-style NEON assembly"))) ("aarch64-neon-syntax" , cl::init(Default) , cl::desc("Choose style of NEON code to emit from AArch64 backend:") , cl::values(clEnumValN(Generic, "generic", "Emit generic NEON assembly"), clEnumValN(Apple, "apple", "Emit Apple-style NEON assembly"))) static
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin(), and llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF().
COFFAtSpecifiers
const MCAsmInfo::AtSpecifier COFFAtSpecifiers[]
Initial value:
                                              = {
    {MCSymbolRefExpr::VK_COFF_IMGREL32, "IMGREL"},
    {AArch64::S_MACHO_PAGEOFF, "PAGEOFF"},
}
Definition at line 34 of file AArch64MCAsmInfo.cpp.
Referenced by llvm::AArch64MCAsmInfoGNUCOFF::AArch64MCAsmInfoGNUCOFF(), and llvm::AArch64MCAsmInfoMicrosoftCOFF::AArch64MCAsmInfoMicrosoftCOFF().
ELFAtSpecifiers
const MCAsmInfo::AtSpecifier ELFAtSpecifiers[]
Initial value:
                                             = {
    {AArch64::S_GOT, "GOT"},
    {AArch64::S_GOTPCREL, "GOTPCREL"},
    {AArch64::S_PLT, "PLT"},
    {AArch64::S_FUNCINIT, "FUNCINIT"},
}
Definition at line 39 of file AArch64MCAsmInfo.cpp.
Referenced by llvm::AArch64MCAsmInfoELF::AArch64MCAsmInfoELF().
MachOAtSpecifiers
const MCAsmInfo::AtSpecifier MachOAtSpecifiers[]
Initial value:
                                               = {
    {AArch64::S_MACHO_GOT, "GOT"},
    {AArch64::S_MACHO_GOTPAGE, "GOTPAGE"},
    {AArch64::S_MACHO_GOTPAGEOFF, "GOTPAGEOFF"},
    {AArch64::S_MACHO_PAGE, "PAGE"},
    {AArch64::S_MACHO_PAGEOFF, "PAGEOFF"},
    {AArch64::S_MACHO_TLVP, "TLVP"},
    {AArch64::S_MACHO_TLVPPAGE, "TLVPPAGE"},
    {AArch64::S_MACHO_TLVPPAGEOFF, "TLVPPAGEOFF"},
}
Definition at line 46 of file AArch64MCAsmInfo.cpp.
Referenced by llvm::AArch64MCAsmInfoDarwin::AArch64MCAsmInfoDarwin().