LLVM: lib/CAS/ActionCaches.cpp File Reference
ActionCaches.cpp File Reference
#include "BuiltinCAS.h"
#include "llvm/ADT/TrieRawHashMap.h"
#include "llvm/CAS/ActionCache.h"
#include "llvm/CAS/OnDiskKeyValueDB.h"
#include "llvm/CAS/UnifiedOnDiskCache.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/BLAKE3.h"
#include "llvm/Support/Errc.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::cas
Macros
#define DEBUG_TYPE "cas-action-caches"
Functions
static Error createResultCachePoisonedError (ArrayRef< uint8_t > KeyHash, const CASContext &Context, CASID Output, ArrayRef< uint8_t > ExistingOutput)
LLVM_ABI std::unique_ptr< ActionCache > llvm::cas::createInMemoryActionCache ()
Create an action cache in memory.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "cas-action-caches"
Definition at line 22 of file ActionCaches.cpp.
Function Documentation
createResultCachePoisonedError()
Error createResultCachePoisonedError (ArrayRef< uint8_t > KeyHash, const CASContext & Context, CASID Output, ArrayRef< uint8_t > ExistingOutput) static
Definition at line 104 of file ActionCaches.cpp.
References llvm::cas::CASID::create(), llvm::createStringError(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::cas::CASID::toString().