LLVM: lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCCodeEmitter.cpp File Reference
AMDGPUMCCodeEmitter.cpp File Reference
The AMDGPU code emitter produces machine code that can be executed directly on the GPU device.
#include "MCTargetDesc/AMDGPUFixupKinds.h"
#include "MCTargetDesc/AMDGPUMCExpr.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/APInt.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/EndianStream.h"
#include <optional>
#include "AMDGPUGenMCCodeEmitter.inc"
Functions
static void addFixup (SmallVectorImpl< MCFixup > &Fixups, uint32_t Offset, const MCExpr *Value, uint16_t Kind, bool PCRel=false)
template<typename IntTy>
static uint32_t getIntInlineImmEncoding (IntTy Imm)
static uint32_t getLit16Encoding (uint16_t Val, const MCSubtargetInfo &STI)
static uint32_t getLitBF16Encoding (uint16_t Val)
static uint32_t getLit32Encoding (uint32_t Val, const MCSubtargetInfo &STI)
static uint32_t getLit16IntEncoding (uint32_t Val, const MCSubtargetInfo &STI)
static uint32_t getLit64Encoding (const MCInstrDesc &Desc, uint64_t Val, const MCSubtargetInfo &STI, bool IsFP)
static bool needsPCRel (const MCExpr *Expr)
Detailed Description
The AMDGPU code emitter produces machine code that can be executed directly on the GPU device.
Definition in file AMDGPUMCCodeEmitter.cpp.
Function Documentation
addFixup()
void addFixup (SmallVectorImpl< MCFixup > & Fixups, uint32_t Offset, const MCExpr * Value, uint16_t Kind, bool PCRel = false) static
Definition at line 110 of file AMDGPUMCCodeEmitter.cpp.
References llvm::MCFixup::create(), and llvm::Offset.
getIntInlineImmEncoding()
template<typename IntTy> uint32_t getIntInlineImmEncoding (IntTy Imm) static
Definition at line 118 of file AMDGPUMCCodeEmitter.cpp.
Referenced by getLit16Encoding(), getLit32Encoding(), getLit64Encoding(), and getLitBF16Encoding().
getLit16Encoding()
uint32_t getLit16Encoding (uint16_t Val, const MCSubtargetInfo & STI) static
Definition at line 128 of file AMDGPUMCCodeEmitter.cpp.
References getIntInlineImmEncoding(), and llvm::MCSubtargetInfo::hasFeature().
getLit16IntEncoding()
uint32_t getLit16IntEncoding (uint32_t Val, const MCSubtargetInfo & STI) static
Definition at line 221 of file AMDGPUMCCodeEmitter.cpp.
References getLit32Encoding().
getLit32Encoding()
uint32_t getLit32Encoding (uint32_t Val, const MCSubtargetInfo & STI) static
Definition at line 185 of file AMDGPUMCCodeEmitter.cpp.
References llvm::bit_cast(), getIntInlineImmEncoding(), and llvm::MCSubtargetInfo::hasFeature().
Referenced by getLit16IntEncoding().
getLit64Encoding()
uint32_t getLit64Encoding (const MCInstrDesc & Desc, uint64_t Val, const MCSubtargetInfo & STI, bool IsFP) static
Definition at line 225 of file AMDGPUMCCodeEmitter.cpp.
References llvm::bit_cast(), getIntInlineImmEncoding(), llvm::MCSubtargetInfo::hasFeature(), llvm::isInt(), llvm::isUInt(), llvm::Lo_32(), llvm::SIInstrFlags::VOP3, and llvm::SIInstrFlags::VOP3P.
getLitBF16Encoding()
uint32_t getLitBF16Encoding (uint16_t Val) static
Definition at line 164 of file AMDGPUMCCodeEmitter.cpp.
References getIntInlineImmEncoding().
needsPCRel()
bool needsPCRel (const MCExpr * Expr) static
Definition at line 576 of file AMDGPUMCCodeEmitter.cpp.
References llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::AMDGPU::getSpecifier(), llvm_unreachable, needsPCRel(), llvm::AMDGPUMCExpr::S_ABS32_HI, llvm::AMDGPUMCExpr::S_ABS32_LO, llvm::AMDGPUMCExpr::S_ABS64, llvm::MCExpr::Specifier, llvm::MCBinaryExpr::Sub, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by needsPCRel().