LLVM: lib/Target/AMDGPU/MCA/AMDGPUCustomBehaviour.cpp File Reference
AMDGPUCustomBehaviour.cpp File Reference
This file implements methods from the AMDGPUCustomBehaviour class.
#include "AMDGPUCustomBehaviour.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/WithColor.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::mca
Functions
static CustomBehaviour * createAMDGPUCustomBehaviour (const MCSubtargetInfo &STI, const mca::SourceMgr &SrcMgr, const MCInstrInfo &MCII)
static InstrPostProcess * createAMDGPUInstrPostProcess (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTargetMCA ()
Extern function to initialize the targets for the AMDGPU backend.
Detailed Description
This file implements methods from the AMDGPUCustomBehaviour class.
Definition in file AMDGPUCustomBehaviour.cpp.
Function Documentation
createAMDGPUCustomBehaviour()
CustomBehaviour * createAMDGPUCustomBehaviour (const MCSubtargetInfo & STI, const mca::SourceMgr & SrcMgr, const MCInstrInfo & MCII) static
Definition at line 343 of file AMDGPUCustomBehaviour.cpp.
References llvm::SrcMgr.
Referenced by LLVMInitializeAMDGPUTargetMCA().
createAMDGPUInstrPostProcess()
InstrPostProcess * createAMDGPUInstrPostProcess (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) static
Definition at line 350 of file AMDGPUCustomBehaviour.cpp.
Referenced by LLVMInitializeAMDGPUTargetMCA().
LLVMInitializeAMDGPUTargetMCA()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTargetMCA ()
Extern function to initialize the targets for the AMDGPU backend.
Definition at line 358 of file AMDGPUCustomBehaviour.cpp.
References createAMDGPUCustomBehaviour(), createAMDGPUInstrPostProcess(), llvm::getTheGCNTarget(), llvm::getTheR600Target(), llvm::TargetRegistry::RegisterCustomBehaviour(), and llvm::TargetRegistry::RegisterInstrPostProcess().