LLVM: lib/Target/AMDGPU/MCTargetDesc/AMDGPUInstPrinter.cpp File Reference
AMDGPUInstPrinter.cpp File Reference
#include "AMDGPUInstPrinter.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "Utils/AMDGPUAsmUtils.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/TargetParser/TargetParser.h"
#include "AMDGPUGenAsmWriter.inc"
Functions
static MCRegister getRegForPrinting (MCRegister Reg, const MCRegisterInfo &MRI)
static MCRegister getRegFromMIA (MCRegister Reg, unsigned OpNo, const MCInstrDesc &Desc, const MCRegisterInfo &MRI, const AMDGPUMCInstrAnalysis &MIA)
static bool printImmediateFP16 (uint32_t Imm, const MCSubtargetInfo &STI, raw_ostream &O)
static bool printImmediateBFloat16 (uint32_t Imm, const MCSubtargetInfo &STI, raw_ostream &O)
static bool allOpsDefaultValue (const int *Ops, int NumOps, int Mod, bool IsPacked, bool HasDstSel)
static void printSwizzleBitmask (const uint16_t AndMask, const uint16_t OrMask, const uint16_t XorMask, raw_ostream &O)
Function Documentation
allOpsDefaultValue()
bool allOpsDefaultValue (const int * Ops, int NumOps, int Mod, bool IsPacked, bool HasDstSel) static
Definition at line 1296 of file AMDGPUInstPrinter.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, AbstractManglingParser< Derived, Alloc >::Ops, llvm::SISrcMods::DST_OP_SEL, I, Mod, and llvm::SISrcMods::OP_SEL_1.
getRegForPrinting()
MCRegister getRegForPrinting (MCRegister Reg, const MCRegisterInfo & MRI) static
Definition at line 340 of file AMDGPUInstPrinter.cpp.
References llvm::MCRegisterClass::getID(), llvm::MCRegisterClass::getRegister(), llvm::AMDGPU::getVGPRPhysRegClass(), llvm::AMDGPU::HWEncoding::IS_HI16, MRI, Reg, and llvm::AMDGPU::HWEncoding::REG_IDX_MASK.
Referenced by llvm::AMDGPUInstPrinter::printRegOperand().
getRegFromMIA()
MCRegister getRegFromMIA (MCRegister Reg, unsigned OpNo, const MCInstrDesc & Desc, const MCRegisterInfo & MRI, const AMDGPUMCInstrAnalysis & MIA) static
Definition at line 359 of file AMDGPUInstPrinter.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::AMDGPU::getVGPRLoweringOperandTables(), llvm::AMDGPU::AMDGPUMCInstrAnalysis::getVgprMSBs(), llvm::AMDGPU::getVGPRWithMSBs(), I, llvm::AMDGPU::HWEncoding::IS_VGPR, MRI, Opc, and Reg.
Referenced by llvm::AMDGPUInstPrinter::printRegOperand().
printImmediateBFloat16()
bool printImmediateBFloat16 (uint32_t Imm, const MCSubtargetInfo & STI, raw_ostream & O) static
Definition at line 547 of file AMDGPUInstPrinter.cpp.
References llvm::MCSubtargetInfo::hasFeature(), and llvm::AMDGPU::Imm.
printImmediateFP16()
bool printImmediateFP16 (uint32_t Imm, const MCSubtargetInfo & STI, raw_ostream & O) static
Definition at line 521 of file AMDGPUInstPrinter.cpp.
References llvm::MCSubtargetInfo::hasFeature(), and llvm::AMDGPU::Imm.
printSwizzleBitmask()
void printSwizzleBitmask (const uint16_t AndMask, const uint16_t OrMask, const uint16_t XorMask, raw_ostream & O) static
Definition at line 1697 of file AMDGPUInstPrinter.cpp.
References llvm::AMDGPU::Swizzle::BITMASK_MASK, and llvm::AMDGPU::Swizzle::BITMASK_WIDTH.
Referenced by llvm::AMDGPUInstPrinter::printSwizzle().