LLVM: lib/Target/AMDGPU/AMDGPUImageIntrinsicOptimizer.cpp File Reference
AMDGPUImageIntrinsicOptimizer.cpp File Reference
#include "AMDGPU.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPUTargetMachine.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "amdgpu-image-intrinsic-opt"
Functions
INITIALIZE_PASS(AMDGPUImageIntrinsicOptimizer, DEBUG_TYPE, "AMDGPU Image Intrinsic Optimizer", false, false) char AMDGPUImageIntrinsicOptimizer void addInstToMergeableList (IntrinsicInst *II, SmallVector< SmallVector< IntrinsicInst *, 4 > > &MergeableInsts, const AMDGPU::ImageDimIntrinsicInfo *ImageDimIntr)
BasicBlock::iterator collectMergeableInsts (BasicBlock::iterator I, BasicBlock::iterator E, SmallVector< SmallVector< IntrinsicInst *, 4 > > &MergeableInsts)
bool optimizeSection (ArrayRef< SmallVector< IntrinsicInst *, 4 > > MergeableInsts)
static bool imageIntrinsicOptimizerImpl (Function &F, const TargetMachine *TM)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-image-intrinsic-opt"
Definition at line 76 of file AMDGPUImageIntrinsicOptimizer.cpp.
Function Documentation
addInstToMergeableList()
INITIALIZE_PASS(AMDGPUImageIntrinsicOptimizer, DEBUG_TYPE, "AMDGPU Image Intrinsic Optimizer", false, false) char AMDGPUImageIntrinsicOptimizer void addInstToMergeableList (IntrinsicInst * II, SmallVector< SmallVector< IntrinsicInst *, 4 > > & MergeableInsts, const AMDGPU::ImageDimIntrinsicInfo * ImageDimIntr)
Definition at line 98 of file AMDGPUImageIntrinsicOptimizer.cpp.
References addInstToMergeableList(), assert(), llvm::cast(), const, llvm::dbgs(), E(), I, II, and LLVM_DEBUG.
Referenced by addInstToMergeableList(), and collectMergeableInsts().
collectMergeableInsts()
BasicBlock::iterator collectMergeableInsts (BasicBlock::iterator I, BasicBlock::iterator E, SmallVector< SmallVector< IntrinsicInst *, 4 > > & MergeableInsts)
Definition at line 142 of file AMDGPUImageIntrinsicOptimizer.cpp.
References addInstToMergeableList(), llvm::dbgs(), llvm::dyn_cast(), E(), llvm::AMDGPU::getImageDimIntrinsicInfo(), I, II, llvm::isa(), and LLVM_DEBUG.
Referenced by imageIntrinsicOptimizerImpl().
imageIntrinsicOptimizerImpl()
bool imageIntrinsicOptimizerImpl (Function & F, const TargetMachine * TM) static
Definition at line 283 of file AMDGPUImageIntrinsicOptimizer.cpp.
References collectMergeableInsts(), E(), F, llvm::TargetMachine::getSubtarget(), I, llvm::AMDGPU::isGFX11Plus(), Modified, llvm::none_of(), and optimizeSection().
Referenced by llvm::AMDGPUImageIntrinsicOptimizerPass::run().
optimizeSection()
bool optimizeSection (ArrayRef< SmallVector< IntrinsicInst *, 4 > > MergeableInsts)
Definition at line 176 of file AMDGPUImageIntrinsicOptimizer.cpp.
References B(), llvm::cast(), llvm::countr_zero(), llvm::dbgs(), llvm::divideCeil(), llvm::AMDGPU::ImageDimIntrinsicInfo::DMaskIndex, F, llvm::FixedVectorType::get(), llvm::PoisonValue::get(), llvm::AMDGPU::getImageDimIntrinsicInfo(), llvm::Intrinsic::getIntrinsicSignature(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), I, II, llvm::Type::isHalfTy(), LLVM_DEBUG, Modified, llvm::popcount(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::takeName(), llvm::APInt::udiv(), and llvm::AMDGPU::ImageDimIntrinsicInfo::VAddrEnd.
Referenced by imageIntrinsicOptimizerImpl().