LLVM: lib/Target/AMDGPU/AMDGPUISelDAGToDAG.cpp File Reference
AMDGPUISelDAGToDAG.cpp File Reference
Defines an instruction selector for the AMDGPU target.
#include "AMDGPUISelDAGToDAG.h"
#include "AMDGPU.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPUSubtarget.h"
#include "AMDGPUTargetMachine.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "MCTargetDesc/R600MCTargetDesc.h"
#include "R600RegisterInfo.h"
#include "SIISelLowering.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/Analysis/UniformityAnalysis.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "amdgpu-isel"
Functions
INITIALIZE_PASS_BEGIN (AMDGPUDAGToDAGISelLegacy, "amdgpu-isel", "AMDGPU DAG->DAG Pattern Instruction Selection", false, false) INITIALIZE_PASS_END(AMDGPUDAGToDAGISelLegacy
static bool getBaseWithOffsetUsingSplitOR (SelectionDAG &DAG, SDValue Addr, SDValue &N0, SDValue &N1)
static bool isNoUnsignedWrap (SDValue Addr)
static bool IsCopyFromSGPR (const SIRegisterInfo &TRI, SDValue Val)
static MemSDNode * findMemSDNode (SDNode *N)
static SDValue matchExtFromI32orI32 (SDValue Op, bool IsSigned, const SelectionDAG *DAG)
static SDValue SelectSAddrFI (SelectionDAG *CurDAG, SDValue SAddr)
static SDValue combineBallotPattern (SDValue VCMP, bool &Negate)
static unsigned gwsIntrinToOpcode (unsigned IntrID)
static MachineSDNode * buildRegSequence32 (SmallVectorImpl< SDValue > &Elts, llvm::SelectionDAG *CurDAG, const SDLoc &DL)
static MachineSDNode * buildRegSequence16 (SmallVectorImpl< SDValue > &Elts, llvm::SelectionDAG *CurDAG, const SDLoc &DL)
static MachineSDNode * buildRegSequence (SmallVectorImpl< SDValue > &Elts, llvm::SelectionDAG *CurDAG, const SDLoc &DL, unsigned ElementSize)
static void selectWMMAModsNegAbs (unsigned ModOpcode, unsigned &Mods, SmallVectorImpl< SDValue > &Elts, SDValue &Src, llvm::SelectionDAG *CurDAG, const SDLoc &DL, unsigned ElementSize)
static void checkWMMAElementsModifiersF16 (BuildVectorSDNode *BV, std::function< bool(SDValue)> ModifierCheck)
static SDValue matchBF16FPExtendLike (SDValue Op, bool &IsExtractHigh)
static std::pair< unsigned, uint8_t > BitOp3_Op (SDValue In, SmallVectorImpl< SDValue > &Src)
Variables
amdgpu isel
amdgpu AMDGPU DAG DAG Pattern Instruction Selection
amdgpu AMDGPU DAG DAG Pattern Instruction false
Detailed Description
Defines an instruction selector for the AMDGPU target.
Definition in file AMDGPUISelDAGToDAG.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-isel"
Definition at line 38 of file AMDGPUISelDAGToDAG.cpp.
Function Documentation
BitOp3_Op()
std::pair< unsigned, uint8_t > BitOp3_Op (SDValue In, SmallVectorImpl< SDValue > & Src) static
Definition at line 4209 of file AMDGPUISelDAGToDAG.cpp.
References llvm::ISD::AND, BitOp3_Op(), llvm::CallingConv::C, llvm::dyn_cast(), I, LHS, llvm::ISD::OR, RHS, and llvm::ISD::XOR.
buildRegSequence()
MachineSDNode * buildRegSequence (SmallVectorImpl< SDValue > & Elts, llvm::SelectionDAG * CurDAG, const SDLoc & DL, unsigned ElementSize) static
Definition at line 3733 of file AMDGPUISelDAGToDAG.cpp.
References buildRegSequence16(), buildRegSequence32(), DL, and llvm_unreachable.
buildRegSequence16()
MachineSDNode * buildRegSequence16 (SmallVectorImpl< SDValue > & Elts, llvm::SelectionDAG * CurDAG, const SDLoc & DL) static
Definition at line 3707 of file AMDGPUISelDAGToDAG.cpp.
References assert(), buildRegSequence32(), DL, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), isExtractHiElt(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by buildRegSequence().
buildRegSequence32()
MachineSDNode * buildRegSequence32 (SmallVectorImpl< SDValue > & Elts, llvm::SelectionDAG * CurDAG, const SDLoc & DL) static
Definition at line 3675 of file AMDGPUISelDAGToDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, llvm::SelectionDAG::getMachineNode(), llvm::SIRegisterInfo::getSubRegFromChannel(), llvm::SelectionDAG::getTargetConstant(), llvm_unreachable, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by buildRegSequence(), and buildRegSequence16().
checkWMMAElementsModifiersF16()
void checkWMMAElementsModifiersF16 (BuildVectorSDNode * BV, std::function< bool(SDValue)> ModifierCheck) static
Definition at line 3775 of file AMDGPUISelDAGToDAG.cpp.
References llvm::dyn_cast(), llvm::SDNode::getNumOperands(), and llvm::SDNode::getOperand().
combineBallotPattern()
SDValue combineBallotPattern (SDValue VCMP, bool & Negate) static
Definition at line 2814 of file AMDGPUISelDAGToDAG.cpp.
References assert(), llvm::cast(), Cond, llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::isBoolSGPR(), llvm::ISD::isExtOpcode(), llvm::isNullConstant(), llvm::ISD::SETEQ, and llvm::ISD::SETNE.
findMemSDNode()
MemSDNode * findMemSDNode (SDNode * N) static
Definition at line 1822 of file AMDGPUISelDAGToDAG.cpp.
References assert(), llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::isa(), llvm_unreachable, N, and llvm::AMDGPUTargetLowering::stripBitcast().
getBaseWithOffsetUsingSplitOR()
bool getBaseWithOffsetUsingSplitOR (SelectionDAG & DAG, SDValue Addr, SDValue & N0, SDValue & N1) static
Definition at line 905 of file AMDGPUISelDAGToDAG.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::isa(), llvm::SelectionDAG::isBaseWithConstantOffset(), llvm::Lo, and llvm::ISD::OR.
gwsIntrinToOpcode()
unsigned gwsIntrinToOpcode (unsigned IntrID) static
Definition at line 3008 of file AMDGPUISelDAGToDAG.cpp.
References llvm_unreachable.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUDAGToDAGISelLegacy , "amdgpu-isel" , "AMDGPU DAG->DAG Pattern Instruction Selection" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
IsCopyFromSGPR()
bool IsCopyFromSGPR (const SIRegisterInfo & TRI, SDValue Val) static
Definition at line 1731 of file AMDGPUISelDAGToDAG.cpp.
References llvm::cast(), llvm::ISD::CopyFromReg, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), Reg, and TRI.
isNoUnsignedWrap()
bool isNoUnsignedWrap (SDValue Addr) static
Definition at line 1366 of file AMDGPUISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::SDNode::getFlags(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDNodeFlags::hasNoUnsignedWrap(), and llvm::ISD::OR.
matchBF16FPExtendLike()
SDValue matchBF16FPExtendLike (SDValue Op, bool & IsExtractHigh) static
Definition at line 4067 of file AMDGPUISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::dyn_cast(), llvm::ConstantSDNode::getZExtValue(), and llvm::ISD::SHL.
matchExtFromI32orI32()
SDValue matchExtFromI32orI32 (SDValue Op, bool IsSigned, const SelectionDAG * DAG) static
Definition at line 1961 of file AMDGPUISelDAGToDAG.cpp.
References llvm::ISD::ANY_EXTEND, llvm::SDValue::getValueType(), llvm::ISD::SIGN_EXTEND, llvm::SelectionDAG::SignBitIsZero(), and llvm::ISD::ZERO_EXTEND.
SelectSAddrFI()
SDValue SelectSAddrFI (SelectionDAG * CurDAG, SDValue SAddr) static
Definition at line 2198 of file AMDGPUISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::cast(), llvm::dyn_cast(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetFrameIndex(), and llvm::isa().
selectWMMAModsNegAbs()
void selectWMMAModsNegAbs (unsigned ModOpcode, unsigned & Mods, SmallVectorImpl< SDValue > & Elts, SDValue & Src, llvm::SelectionDAG * CurDAG, const SDLoc & DL, unsigned ElementSize) static
Definition at line 3743 of file AMDGPUISelDAGToDAG.cpp.
References assert(), buildRegSequence(), DL, llvm::ISD::FABS, llvm::ISD::FNEG, llvm::SISrcMods::NEG, llvm::SISrcMods::NEG_HI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Variable Documentation
false
amdgpu AMDGPU DAG DAG Pattern Instruction false
Definition at line 145 of file AMDGPUISelDAGToDAG.cpp.
isel
amdgpu isel
Definition at line 144 of file AMDGPUISelDAGToDAG.cpp.
Selection
amdgpu AMDGPU DAG DAG Pattern Instruction Selection
Definition at line 145 of file AMDGPUISelDAGToDAG.cpp.
Referenced by llvm::logicalview::LVPatterns::addRequest(), llvm::logicalview::LVPatterns::addRequest(), llvm::logicalview::LVPatterns::addRequest(), llvm::logicalview::LVPatterns::addRequest(), llvm::logicalview::LVPatterns::addRequest(), llvm::MCContext::getCOFFSection(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::MCObjectFileInfo::getPseudoProbeSection(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().