LLVM: lib/Target/AMDGPU/Utils/AMDKernelCodeTUtils.cpp File Reference
AMDKernelCodeTUtils.cpp File Reference
#include "AMDKernelCodeTUtils.h"
#include "AMDKernelCodeT.h"
#include "SIDefines.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "Utils/SIDefinesUtils.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "Utils/AMDKernelCodeTInfo.h"
Classes
class PrintField
Macros
#define GEN_HAS_MEMBER(member)
#define RECORD(name, altName, print, parse)
#define QNAME(name)
#define FLD_T(name)
#define PRINTFIELD(sname, aname, name)
#define FIELD2(sname, aname, name)
#define FIELD(name)
#define PRINTCODEPROP(name)
#define PARSECODEPROP(name)
#define CODEPROP(name, shift)
#define PRINTCOMP(GetMacro, Shift)
#define PARSECOMP(SetMacro, Shift)
#define COMPPGM(name, aname, GetMacro, SetMacro, Shift)
#define COMPPGM1(name, aname, AccMacro)
#define COMPPGM2(name, aname, AccMacro)
#define RECORD(name, altName, print, parse)
#define QNAME(name)
#define FLD_T(name)
#define PRINTFIELD(sname, aname, name)
#define FIELD2(sname, aname, name)
#define FIELD(name)
#define PRINTCODEPROP(name)
#define PARSECODEPROP(name)
#define CODEPROP(name, shift)
#define PRINTCOMP(GetMacro, Shift)
#define PARSECOMP(SetMacro, Shift)
#define COMPPGM(name, aname, GetMacro, SetMacro, Shift)
#define COMPPGM1(name, aname, AccMacro)
#define COMPPGM2(name, aname, AccMacro)
#define RECORD(name, altName, print, parse)
#define QNAME(name)
#define FLD_T(name)
#define PRINTFIELD(sname, aname, name)
#define FIELD2(sname, aname, name)
#define FIELD(name)
#define PRINTCODEPROP(name)
#define PARSECODEPROP(name)
#define CODEPROP(name, shift)
#define PRINTCOMP(GetMacro, Shift)
#define PARSECOMP(SetMacro, Shift)
#define COMPPGM(name, aname, GetMacro, SetMacro, Shift)
#define COMPPGM1(name, aname, AccMacro)
#define COMPPGM2(name, aname, AccMacro)
#define RECORD(name, altName, print, parse)
#define QNAME(name)
#define FLD_T(name)
#define PRINTFIELD(sname, aname, name)
#define FIELD2(sname, aname, name)
#define FIELD(name)
#define PRINTCODEPROP(name)
#define PARSECODEPROP(name)
#define CODEPROP(name, shift)
#define PRINTCOMP(GetMacro, Shift)
#define PARSECOMP(SetMacro, Shift)
#define COMPPGM(name, aname, GetMacro, SetMacro, Shift)
#define COMPPGM1(name, aname, AccMacro)
#define COMPPGM2(name, aname, AccMacro)
#define COMPPGM1(name, aname, AccMacro)
#define COMPPGM2(name, aname, AccMacro)
#define PRINTFIELD(sname, aname, name)
#define PRINTCOMP(Complement, PGMType)
#define RECORD(name, altName, print, parse)
#define QNAME(name)
#define FLD_T(name)
#define FIELD2(sname, aname, name)
#define FIELD(name)
#define PRINTCODEPROP(name)
#define PARSECODEPROP(name)
#define CODEPROP(name, shift)
#define PARSECOMP(SetMacro, Shift)
#define COMPPGM(name, aname, GetMacro, SetMacro, Shift)
#define COMPPGM1(name, aname, AccMacro)
#define COMPPGM2(name, aname, AccMacro)
#define PARSECOMP(Complement, PGMType)
#define RECORD(name, altName, print, parse)
#define QNAME(name)
#define FLD_T(name)
#define PRINTFIELD(sname, aname, name)
#define FIELD2(sname, aname, name)
#define FIELD(name)
#define PRINTCODEPROP(name)
#define PARSECODEPROP(name)
#define CODEPROP(name, shift)
#define PRINTCOMP(GetMacro, Shift)
#define COMPPGM(name, aname, GetMacro, SetMacro, Shift)
Typedefs
using RetrieveFx = const MCExpr *&(*)(AMDGPUMCKernelCodeT &)
using PrintFx
using ParseFx = bool (*)(AMDGPUMCKernelCodeT &, MCAsmParser &, raw_ostream &)
Functions
static StringMap< int > createIndexMap (ArrayRef< StringLiteral > names, ArrayRef< StringLiteral > altNames)
static int get_amd_kernel_code_t_FieldIndex (StringRef name)
template<typename T, T AMDGPUMCKernelCodeT::* ptr, int shift, int width = 1>
static void printBitField (StringRef Name, const AMDGPUMCKernelCodeT &C, raw_ostream &OS, MCContext &, AMDGPUMCKernelCodeT::PrintHelper)
static bool expectAbsExpression (MCAsmParser &MCParser, int64_t &Value, raw_ostream &Err)
template<typename T, T AMDGPUMCKernelCodeT::* ptr>
static bool parseField (AMDGPUMCKernelCodeT &C, MCAsmParser &MCParser, raw_ostream &Err)
template<typename T, T AMDGPUMCKernelCodeT::* ptr, int shift, int width = 1>
static bool parseBitField (AMDGPUMCKernelCodeT &C, MCAsmParser &MCParser, raw_ostream &Err)
static bool parseExpr (MCAsmParser &MCParser, const MCExpr *&Value, raw_ostream &Err)
static void printAmdKernelCodeField (const AMDGPUMCKernelCodeT &C, int FldIndex, raw_ostream &OS, MCContext &Ctx, AMDGPUMCKernelCodeT::PrintHelper Helper)
Macro Definition Documentation
CODEPROP [1/6]
#define CODEPROP (name, shift)
Value:
RECORD(name, name, PRINTCODEPROP(shift), PARSECODEPROP(shift))
CODEPROP [2/6]
#define CODEPROP (name, shift)
Value:
RECORD(name, name, PRINTCODEPROP(shift), PARSECODEPROP(shift))
CODEPROP [3/6]
#define CODEPROP (name, shift)
Value:
RECORD(name, name, PRINTCODEPROP(shift), PARSECODEPROP(shift))
CODEPROP [4/6]
#define CODEPROP (name, shift)
Value:
RECORD(name, name, PRINTCODEPROP(shift), PARSECODEPROP(shift))
CODEPROP [5/6]
#define CODEPROP (name, shift)
Value:
RECORD(name, name, PRINTCODEPROP(shift), PARSECODEPROP(shift))
CODEPROP [6/6]
#define CODEPROP (name, shift)
Value:
RECORD(name, name, PRINTCODEPROP(shift), PARSECODEPROP(shift))
COMPPGM [1/6]
#define COMPPGM (name, aname, GetMacro, SetMacro, Shift)
Value:
RECORD(name, aname, PRINTCOMP(GetMacro, Shift), PARSECOMP(SetMacro, Shift))
COMPPGM [2/6]
#define COMPPGM (name, aname, GetMacro, SetMacro, Shift)
Value:
RECORD(name, aname, PRINTCOMP(GetMacro, Shift), PARSECOMP(SetMacro, Shift))
COMPPGM [3/6]
#define COMPPGM (name, aname, GetMacro, SetMacro, Shift)
Value:
RECORD(name, aname, PRINTCOMP(GetMacro, Shift), PARSECOMP(SetMacro, Shift))
COMPPGM [4/6]
#define COMPPGM (name, aname, GetMacro, SetMacro, Shift)
Value:
RECORD(name, aname, PRINTCOMP(GetMacro, Shift), PARSECOMP(SetMacro, Shift))
COMPPGM [5/6]
#define COMPPGM (name, aname, GetMacro, SetMacro, Shift)
Value:
RECORD(name, aname, PRINTCOMP(GetMacro, Shift), PARSECOMP(SetMacro, Shift))
COMPPGM [6/6]
#define COMPPGM (name, aname, GetMacro, SetMacro, Shift)
Value:
RECORD(name, aname, PRINTCOMP(GetMacro, Shift), PARSECOMP(SetMacro, Shift))
COMPPGM1 [1/6]
#define COMPPGM1 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B848_##AccMacro, S_00B848_##AccMacro, 0)
COMPPGM1 [2/6]
#define COMPPGM1 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B848_##AccMacro, S_00B848_##AccMacro, 0)
COMPPGM1 [3/6]
#define COMPPGM1 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B848_##AccMacro, S_00B848_##AccMacro, 0)
COMPPGM1 [4/6]
#define COMPPGM1 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B848_##AccMacro, S_00B848_##AccMacro, 0)
COMPPGM1 [5/6]
#define COMPPGM1 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B848_##AccMacro, C_00B848_##AccMacro, 0)
COMPPGM1 [6/6]
#define COMPPGM1 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, C_00B848_##AccMacro, S_00B848_##AccMacro, 0)
COMPPGM2 [1/6]
#define COMPPGM2 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B84C_##AccMacro, S_00B84C_##AccMacro, 32)
COMPPGM2 [2/6]
#define COMPPGM2 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B84C_##AccMacro, S_00B84C_##AccMacro, 32)
COMPPGM2 [3/6]
#define COMPPGM2 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B84C_##AccMacro, S_00B84C_##AccMacro, 32)
COMPPGM2 [4/6]
#define COMPPGM2 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B84C_##AccMacro, S_00B84C_##AccMacro, 32)
COMPPGM2 [5/6]
#define COMPPGM2 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, G_00B84C_##AccMacro, C_00B84C_##AccMacro, 32)
COMPPGM2 [6/6]
#define COMPPGM2 (name, aname, AccMacro)
Value:
COMPPGM(name, aname, C_00B84C_##AccMacro, S_00B84C_##AccMacro, 32)
FIELD [1/6]
#define FIELD (name)
Value:
FIELD2(name, name, name)
FIELD [2/6]
#define FIELD (name)
Value:
FIELD2(name, name, name)
FIELD [3/6]
#define FIELD (name)
Value:
FIELD2(name, name, name)
FIELD [4/6]
#define FIELD (name)
Value:
FIELD2(name, name, name)
FIELD [5/6]
#define FIELD (name)
Value:
FIELD2(name, name, name)
FIELD [6/6]
#define FIELD (name)
Value:
FIELD2(name, name, name)
FIELD2 [1/6]
#define FIELD2 (sname, aname, name)
Value:
RECORD(sname, aname, PRINTFIELD(sname, aname, name), parseField<FLD_T(name)>)
FIELD2 [2/6]
#define FIELD2 (sname, aname, name)
Value:
RECORD(sname, aname, PRINTFIELD(sname, aname, name), parseField<FLD_T(name)>)
FIELD2 [3/6]
#define FIELD2 (sname, aname, name)
Value:
RECORD(sname, aname, PRINTFIELD(sname, aname, name), parseField<FLD_T(name)>)
FIELD2 [4/6]
#define FIELD2 (sname, aname, name)
Value:
RECORD(sname, aname, PRINTFIELD(sname, aname, name), parseField<FLD_T(name)>)
FIELD2 [5/6]
#define FIELD2 (sname, aname, name)
Value:
RECORD(sname, aname, PRINTFIELD(sname, aname, name), parseField<FLD_T(name)>)
FIELD2 [6/6]
#define FIELD2 (sname, aname, name)
Value:
RECORD(sname, aname, PRINTFIELD(sname, aname, name), parseField<FLD_T(name)>)
FLD_T [1/6]
#define FLD_T (name)
Value:
decltype(QNAME(name)), &QNAME(name)
FLD_T [2/6]
#define FLD_T (name)
Value:
decltype(QNAME(name)), &QNAME(name)
FLD_T [3/6]
#define FLD_T (name)
Value:
decltype(QNAME(name)), &QNAME(name)
FLD_T [4/6]
#define FLD_T (name)
Value:
decltype(QNAME(name)), &QNAME(name)
FLD_T [5/6]
#define FLD_T (name)
Value:
decltype(QNAME(name)), &QNAME(name)
FLD_T [6/6]
#define FLD_T (name)
Value:
decltype(QNAME(name)), &QNAME(name)
GEN_HAS_MEMBER
#define GEN_HAS_MEMBER (member)
Value:
class HasMember##member {                                                    \
  template <typename U>                                                      \
  using check_member = decltype(std::declval<U>().member);                   \
                                                                             \
public:                                                                      \
  static constexpr bool RESULT =                                             \
      llvm::is_detected<check_member, AMDGPUMCKernelCodeT>::value;           \
};                                                                           \
class IsMCExpr##member {                                                     \
  template <typename U>                                                      \
  static constexpr auto HasMCExprType(int) -> std::bool_constant<            \
      HasMember##member::RESULT &&                                           \
      std::is_same_v<decltype(U::member), const MCExpr *>>;                  \
  template <typename U> static constexpr std::false_type HasMCExprType(...); \
                                                                             \
public:                                                                      \
  static constexpr bool RESULT =                                             \
      decltype(HasMCExprType<AMDGPUMCKernelCodeT>(0))::value;                \
};                                                                           \
class GetMember##member {                                                    \
public:                                                                      \
  static const MCExpr *Phony;                                                \
  template <typename U> static const MCExpr *&Get(U &C) {                    \
    if constexpr (IsMCExpr##member::RESULT)                                  \
      return C.member;                                                       \
    else                                                                     \
      return Phony;                                                          \
  }                                                                          \
};                                                                           \
const MCExpr *GetMember##member::Phony = nullptr;
Definition at line 41 of file AMDKernelCodeTUtils.cpp.
PARSECODEPROP [1/6]
#define PARSECODEPROP (name)
Value:
parseBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PARSECODEPROP [2/6]
#define PARSECODEPROP (name)
Value:
parseBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PARSECODEPROP [3/6]
#define PARSECODEPROP (name)
Value:
parseBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PARSECODEPROP [4/6]
#define PARSECODEPROP (name)
Value:
parseBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PARSECODEPROP [5/6]
#define PARSECODEPROP (name)
Value:
parseBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PARSECODEPROP [6/6]
#define PARSECODEPROP (name)
Value:
parseBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PARSECOMP [1/6]
#define PARSECOMP (Complement, PGMType)
Value:
[](AMDGPUMCKernelCodeT &C, MCAsmParser &MCParser,                            \
   raw_ostream &Err) -> bool {                                               \
  MCContext &Ctx = MCParser.getContext();                                    \
  const MCExpr *Value;                                                       \
  if (!parseExpr(MCParser, Value, Err))                                      \
    return false;                                                            \
  auto [Shift, Mask] = getShiftMask(Complement);                             \
  Value = maskShiftSet(Value, Mask, Shift, Ctx);                             \
  const MCExpr *Compl = MCConstantExpr::create(Complement, Ctx);             \
  if (PGMType == 0) {                                                        \
    C.compute_pgm_resource1_registers = MCBinaryExpr::createAnd(             \
        C.compute_pgm_resource1_registers, Compl, Ctx);                      \
    C.compute_pgm_resource1_registers = MCBinaryExpr::createOr(              \
        C.compute_pgm_resource1_registers, Value, Ctx);                      \
  } else {                                                                   \
    C.compute_pgm_resource2_registers = MCBinaryExpr::createAnd(             \
        C.compute_pgm_resource2_registers, Compl, Ctx);                      \
    C.compute_pgm_resource2_registers = MCBinaryExpr::createOr(              \
        C.compute_pgm_resource2_registers, Value, Ctx);                      \
  }                                                                          \
  return true;                                                               \
}
PARSECOMP [2/6]
#define PARSECOMP (SetMacro, Shift)
Value:
[](amd_kernel_code_t &C, MCAsmParser &MCParser, raw_ostream &Err) { \
   int64_t Value = 0; \
   if (!expectAbsExpression(MCParser, Value, Err)) \
     return false; \
   C.compute_pgm_resource_registers &= ~(SetMacro(0xFFFFFFFFFFFFFFFFULL) << Shift); \
   C.compute_pgm_resource_registers |= SetMacro(Value) << Shift; \
   return true; \
}
PARSECOMP [3/6]
#define PARSECOMP (SetMacro, Shift)
Value:
[](amd_kernel_code_t &C, MCAsmParser &MCParser, raw_ostream &Err) { \
   int64_t Value = 0; \
   if (!expectAbsExpression(MCParser, Value, Err)) \
     return false; \
   C.compute_pgm_resource_registers &= ~(SetMacro(0xFFFFFFFFFFFFFFFFULL) << Shift); \
   C.compute_pgm_resource_registers |= SetMacro(Value) << Shift; \
   return true; \
}
PARSECOMP [4/6]
#define PARSECOMP (SetMacro, Shift)
Value:
[](amd_kernel_code_t &C, MCAsmParser &MCParser, raw_ostream &Err) { \
   int64_t Value = 0; \
   if (!expectAbsExpression(MCParser, Value, Err)) \
     return false; \
   C.compute_pgm_resource_registers &= ~(SetMacro(0xFFFFFFFFFFFFFFFFULL) << Shift); \
   C.compute_pgm_resource_registers |= SetMacro(Value) << Shift; \
   return true; \
}
PARSECOMP [5/6]
#define PARSECOMP (SetMacro, Shift)
Value:
[](amd_kernel_code_t &C, MCAsmParser &MCParser, raw_ostream &Err) { \
   int64_t Value = 0; \
   if (!expectAbsExpression(MCParser, Value, Err)) \
     return false; \
   C.compute_pgm_resource_registers &= ~(SetMacro(0xFFFFFFFFFFFFFFFFULL) << Shift); \
   C.compute_pgm_resource_registers |= SetMacro(Value) << Shift; \
   return true; \
}
PARSECOMP [6/6]
#define PARSECOMP (SetMacro, Shift)
Value:
[](amd_kernel_code_t &C, MCAsmParser &MCParser, raw_ostream &Err) { \
   int64_t Value = 0; \
   if (!expectAbsExpression(MCParser, Value, Err)) \
     return false; \
   C.compute_pgm_resource_registers &= ~(SetMacro(0xFFFFFFFFFFFFFFFFULL) << Shift); \
   C.compute_pgm_resource_registers |= SetMacro(Value) << Shift; \
   return true; \
}
PRINTCODEPROP [1/6]
#define PRINTCODEPROP (name)
Value:
printBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PRINTCODEPROP [2/6]
#define PRINTCODEPROP (name)
Value:
printBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PRINTCODEPROP [3/6]
#define PRINTCODEPROP (name)
Value:
printBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PRINTCODEPROP [4/6]
#define PRINTCODEPROP (name)
Value:
printBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PRINTCODEPROP [5/6]
#define PRINTCODEPROP (name)
Value:
printBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PRINTCODEPROP [6/6]
#define PRINTCODEPROP (name)
Value:
printBitField<FLD_T(code_properties),\
              AMD_CODE_PROPERTY_##name##_SHIFT,\
              AMD_CODE_PROPERTY_##name##_WIDTH>
PRINTCOMP [1/6]
#define PRINTCOMP (Complement, PGMType)
Value:
[](StringRef Name, const AMDGPUMCKernelCodeT &C, raw_ostream &OS,            \
   MCContext &Ctx, AMDGPUMCKernelCodeT::PrintHelper Helper) {                \
  OS << Name << " = ";                                                       \
  auto [Shift, Mask] = getShiftMask(Complement);                             \
  const MCExpr *Value;                                                       \
  if (PGMType == 0) {                                                        \
    Value =                                                                  \
        maskShiftGet(C.compute_pgm_resource1_registers, Mask, Shift, Ctx);   \
  } else {                                                                   \
    Value =                                                                  \
        maskShiftGet(C.compute_pgm_resource2_registers, Mask, Shift, Ctx);   \
  }                                                                          \
  Helper(Value, OS, Ctx.getAsmInfo());                                       \
}
PRINTCOMP [2/6]
#define PRINTCOMP (GetMacro, Shift)
Value:
[](StringRef Name, const amd_kernel_code_t &C, raw_ostream &OS) { \
   printName(OS, Name) << \
     (int)GetMacro(C.compute_pgm_resource_registers >> Shift); \
}
PRINTCOMP [3/6]
#define PRINTCOMP (GetMacro, Shift)
Value:
[](StringRef Name, const amd_kernel_code_t &C, raw_ostream &OS) { \
   printName(OS, Name) << \
     (int)GetMacro(C.compute_pgm_resource_registers >> Shift); \
}
PRINTCOMP [4/6]
#define PRINTCOMP (GetMacro, Shift)
Value:
[](StringRef Name, const amd_kernel_code_t &C, raw_ostream &OS) { \
   printName(OS, Name) << \
     (int)GetMacro(C.compute_pgm_resource_registers >> Shift); \
}
PRINTCOMP [5/6]
#define PRINTCOMP (GetMacro, Shift)
Value:
[](StringRef Name, const amd_kernel_code_t &C, raw_ostream &OS) { \
   printName(OS, Name) << \
     (int)GetMacro(C.compute_pgm_resource_registers >> Shift); \
}
PRINTCOMP [6/6]
#define PRINTCOMP (GetMacro, Shift)
Value:
[](StringRef Name, const amd_kernel_code_t &C, raw_ostream &OS) { \
   printName(OS, Name) << \
     (int)GetMacro(C.compute_pgm_resource_registers >> Shift); \
}
PRINTFIELD [1/6]
#define PRINTFIELD (sname, aname, name)
Value:
printField<FLD_T(name)>
PRINTFIELD [2/6]
#define PRINTFIELD (sname, aname, name)
Value:
printField<FLD_T(name)>
PRINTFIELD [3/6]
#define PRINTFIELD (sname, aname, name)
Value:
printField<FLD_T(name)>
PRINTFIELD [4/6]
#define PRINTFIELD (sname, aname, name)
Value:
printField<FLD_T(name)>
PRINTFIELD [5/6]
#define PRINTFIELD (sname, aname, name)
Value:
printField<FLD_T(name)>
PRINTFIELD [6/6]
#define PRINTFIELD (sname, aname, name)
Value:
PrintField::printField<FLD_T(name)>
QNAME [1/6]
#define QNAME (name)
Value:
AMDGPUMCKernelCodeT::name
QNAME [2/6]
#define QNAME (name)
Value:
AMDGPUMCKernelCodeT::name
QNAME [3/6]
#define QNAME (name)
Value:
AMDGPUMCKernelCodeT::name
QNAME [4/6]
#define QNAME (name)
Value:
AMDGPUMCKernelCodeT::name
QNAME [5/6]
#define QNAME (name)
Value:
AMDGPUMCKernelCodeT::name
QNAME [6/6]
#define QNAME (name)
Value:
AMDGPUMCKernelCodeT::name
RECORD [1/6]
#define RECORD (name, altName, print, parse)
Value:
parse
RECORD [2/6]
#define RECORD (name, altName, print, parse)
Value:
print
RECORD [3/6]
#define RECORD (name, altName, print, parse)
Value:
GetMember##name::Get
RECORD [4/6]
#define RECORD (name, altName, print, parse)
Value:
(IsMCExpr##name::RESULT)
RECORD [5/6]
#define RECORD (name, altName, print, parse)
Value:
#altName
RECORD [6/6]
#define RECORD (name, altName, print, parse)
Value:
#name
Typedef Documentation
ParseFx
using ParseFx = bool (*)(AMDGPUMCKernelCodeT &, MCAsmParser &, raw_ostream &)
Definition at line 316 of file AMDKernelCodeTUtils.cpp.
PrintFx
using PrintFx
Initial value:
void (*)(StringRef, const AMDGPUMCKernelCodeT &, raw_ostream &,
                        MCContext &, AMDGPUMCKernelCodeT::PrintHelper Helper)
Definition at line 230 of file AMDKernelCodeTUtils.cpp.
RetrieveFx
using RetrieveFx = const MCExpr *&(*)(AMDGPUMCKernelCodeT &)
Definition at line 178 of file AMDKernelCodeTUtils.cpp.
Function Documentation
createIndexMap()
StringMap< int > createIndexMap (ArrayRef< StringLiteral > names, ArrayRef< StringLiteral > altNames) static
Definition at line 189 of file AMDKernelCodeTUtils.cpp.
References assert(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), and llvm::ArrayRef< T >::size().
Referenced by get_amd_kernel_code_t_FieldIndex().
expectAbsExpression()
bool expectAbsExpression (MCAsmParser & MCParser, int64_t & Value, raw_ostream & Err) static
Definition at line 263 of file AMDKernelCodeTUtils.cpp.
References llvm::AsmToken::Equal, llvm::MCAsmParser::getLexer(), llvm::AsmLexer::isNot(), llvm::AsmLexer::Lex(), and llvm::MCAsmParser::parseAbsoluteExpression().
Referenced by parseBitField(), and parseField().
get_amd_kernel_code_t_FieldIndex()
int get_amd_kernel_code_t_FieldIndex (StringRef name) static
Definition at line 200 of file AMDKernelCodeTUtils.cpp.
References createIndexMap(), and name.
Referenced by llvm::AMDGPU::AMDGPUMCKernelCodeT::ParseKernelCodeT().
parseBitField()
template<typename T, T AMDGPUMCKernelCodeT::* ptr, int shift, int width = 1> bool parseBitField (AMDGPUMCKernelCodeT & C, MCAsmParser & MCParser, raw_ostream & Err) static
Definition at line 290 of file AMDKernelCodeTUtils.cpp.
References llvm::CallingConv::C, expectAbsExpression(), and T.
parseExpr()
bool parseExpr (MCAsmParser & MCParser, const MCExpr *& Value, raw_ostream & Err) static
Definition at line 301 of file AMDKernelCodeTUtils.cpp.
References llvm::AsmToken::Equal, llvm::MCAsmParser::getLexer(), llvm::AsmLexer::isNot(), llvm::AsmLexer::Lex(), and llvm::MCAsmParser::parseExpression().
Referenced by llvm::AMDGPU::AMDGPUMCKernelCodeT::ParseKernelCodeT().
parseField()
template<typename T, T AMDGPUMCKernelCodeT::* ptr> bool parseField (AMDGPUMCKernelCodeT & C, MCAsmParser & MCParser, raw_ostream & Err) static
Definition at line 280 of file AMDKernelCodeTUtils.cpp.
References llvm::CallingConv::C, expectAbsExpression(), and T.
printAmdKernelCodeField()
void printAmdKernelCodeField (const AMDGPUMCKernelCodeT & C, int FldIndex, raw_ostream & OS, MCContext & Ctx, AMDGPUMCKernelCodeT::PrintHelper Helper) static
Definition at line 354 of file AMDKernelCodeTUtils.cpp.
References llvm::CallingConv::C, and Printer.
Referenced by llvm::AMDGPU::AMDGPUMCKernelCodeT::EmitKernelCodeT().
printBitField()
template<typename T, T AMDGPUMCKernelCodeT::* ptr, int shift, int width = 1> void printBitField (StringRef Name, const AMDGPUMCKernelCodeT & C, raw_ostream & OS, MCContext & , AMDGPUMCKernelCodeT::PrintHelper) static
Definition at line 223 of file AMDKernelCodeTUtils.cpp.
References llvm::CallingConv::C, and T.