LLVM: lib/Target/ARC/Disassembler/ARCDisassembler.cpp File Reference
ARCDisassembler.cpp File Reference
This file is part of the ARC Disassembler.
#include "ARC.h"
#include "ARCRegisterInfo.h"
#include "MCTargetDesc/ARCMCTargetDesc.h"
#include "TargetInfo/ARCTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoder.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "ARCGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "arc-disassembler"
Functions
static bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
static bool readInstruction64 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint64_t &Insn)
static bool readInstruction48 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint64_t &Insn)
static bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
template<unsigned B>
static DecodeStatus DecodeSignedOperand (MCInst &Inst, unsigned InsnS, uint64_t Address=0, const MCDisassembler *Decoder=nullptr)
template<unsigned B>
static DecodeStatus DecodeFromCyclicRange (MCInst &Inst, unsigned InsnS, uint64_t Address=0, const MCDisassembler *Decoder=nullptr)
template<unsigned B>
static DecodeStatus DecodeBranchTargetS (MCInst &Inst, unsigned InsnS, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMEMrs9 (MCInst &, unsigned, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeLdLImmInstruction (MCInst &, uint64_t, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeStLImmInstruction (MCInst &, uint64_t, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeLdRLImmInstruction (MCInst &, uint64_t, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeSOPwithRS12 (MCInst &, uint64_t, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeSOPwithRU6 (MCInst &, uint64_t, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeCCRU6Instruction (MCInst &, uint64_t, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeMoveHRegInstruction (MCInst &Inst, uint64_t, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeGPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGBR32ShortRegister (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static unsigned decodeCField (unsigned Insn)
static unsigned decodeBField (unsigned Insn)
static unsigned decodeAField (unsigned Insn)
static bool DecodeSymbolicOperand (MCInst &Inst, uint64_t Address, uint64_t Value, const MCDisassembler *Decoder)
static void DecodeSymbolicOperandOff (MCInst &Inst, uint64_t Address, uint64_t Offset, const MCDisassembler *Decoder)
static MCDisassembler * createARCDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCDisassembler ()
Variables
static const uint16_t GPR32DecoderTable []
Detailed Description
This file is part of the ARC Disassembler.
Definition in file ARCDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-disassembler"
Definition at line 30 of file ARCDisassembler.cpp.
Function Documentation
createARCDisassembler()
MCDisassembler * createARCDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 413 of file ARCDisassembler.cpp.
References T.
Referenced by LLVMInitializeARCDisassembler().
decodeAField()
unsigned decodeAField (unsigned Insn) static
Definition at line 167 of file ARCDisassembler.cpp.
References llvm::MCD::fieldFromInstruction().
Referenced by DecodeLdLImmInstruction(), and DecodeLdRLImmInstruction().
decodeBField()
unsigned decodeBField (unsigned Insn) static
Definition at line 162 of file ARCDisassembler.cpp.
References llvm::MCD::fieldFromInstruction().
Referenced by DecodeCCRU6Instruction(), DecodeLdLImmInstruction(), DecodeLdRLImmInstruction(), DecodeSOPwithRS12(), DecodeSOPwithRU6(), and DecodeStLImmInstruction().
DecodeBranchTargetS()
template<unsigned B> DecodeStatus DecodeBranchTargetS (MCInst & Inst, unsigned InsnS, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 199 of file ARCDisassembler.cpp.
References B(), DecodeSymbolicOperandOff(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeCCRU6Instruction()
DecodeStatus DecodeCCRU6Instruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 309 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::dbgs(), decodeBField(), DecodeGPR32RegisterClass(), llvm::MCD::fieldFromInstruction(), LLVM_DEBUG, and llvm::MCDisassembler::Success.
decodeCField()
unsigned decodeCField (unsigned Insn) static
Definition at line 158 of file ARCDisassembler.cpp.
References llvm::MCD::fieldFromInstruction().
Referenced by DecodeLdRLImmInstruction(), and DecodeStLImmInstruction().
DecodeFromCyclicRange()
template<unsigned B> DecodeStatus DecodeFromCyclicRange (MCInst & Inst, unsigned InsnS, uint64_t Address = 0, const MCDisassembler * Decoder = nullptr) static
Definition at line 220 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), B(), llvm::MCOperand::createImm(), llvm::max(), and llvm::MCDisassembler::Success.
DecodeGBR32ShortRegister()
DecodeStatus DecodeGBR32ShortRegister (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 146 of file ARCDisassembler.cpp.
References DecodeGPR32RegisterClass().
DecodeGPR32RegisterClass()
DecodeStatus DecodeGPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 133 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::dbgs(), llvm::MCDisassembler::Fail, GPR32DecoderTable, LLVM_DEBUG, Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeCCRU6Instruction(), DecodeGBR32ShortRegister(), DecodeLdLImmInstruction(), DecodeLdRLImmInstruction(), DecodeMEMrs9(), DecodeMoveHRegInstruction(), DecodeSOPwithRS12(), DecodeSOPwithRU6(), and DecodeStLImmInstruction().
DecodeLdLImmInstruction()
DecodeStatus DecodeLdLImmInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 248 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::dbgs(), decodeAField(), decodeBField(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeLdRLImmInstruction()
DecodeStatus DecodeLdRLImmInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 266 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::dbgs(), decodeAField(), decodeBField(), decodeCField(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeMEMrs9()
DecodeStatus DecodeMEMrs9 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Dec) static
Definition at line 171 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeMoveHRegInstruction()
DecodeStatus DecodeMoveHRegInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 283 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::dbgs(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), G, H, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeSignedOperand()
template<unsigned B> DecodeStatus DecodeSignedOperand (MCInst & Inst, unsigned InsnS, uint64_t Address = 0, const MCDisassembler * Decoder = nullptr) static
Definition at line 209 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), B(), llvm::MCOperand::createImm(), llvm::maskTrailingOnes(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeSOPwithRS12()
DecodeStatus DecodeSOPwithRS12 (MCInst & Inst, uint64_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 335 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), decodeBField(), DecodeGPR32RegisterClass(), llvm::MCD::fieldFromInstruction(), llvm::Lower, llvm::MCDisassembler::Success, and llvm::Upper.
DecodeSOPwithRU6()
DecodeStatus DecodeSOPwithRU6 (MCInst & Inst, uint64_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 324 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), decodeBField(), DecodeGPR32RegisterClass(), llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeStLImmInstruction()
DecodeStatus DecodeStLImmInstruction (MCInst & Inst, uint64_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 231 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::dbgs(), decodeBField(), decodeCField(), DecodeGPR32RegisterClass(), llvm::MCDisassembler::Fail, LLVM_DEBUG, and llvm::MCDisassembler::Success.
DecodeSymbolicOperand()
bool DecodeSymbolicOperand (MCInst & Inst, uint64_t Address, uint64_t Value, const MCDisassembler * Decoder) static
Definition at line 181 of file ARCDisassembler.cpp.
References llvm::MCDisassembler::tryAddingSymbolicOperand().
Referenced by DecodeSymbolicOperandOff().
DecodeSymbolicOperandOff()
void DecodeSymbolicOperandOff (MCInst & Inst, uint64_t Address, uint64_t Offset, const MCDisassembler * Decoder) static
Definition at line 189 of file ARCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeSymbolicOperand(), and llvm::Offset.
Referenced by DecodeBranchTargetS().
LLVMInitializeARCDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCDisassembler ()
Definition at line 419 of file ARCDisassembler.cpp.
References createARCDisassembler(), llvm::getTheARCTarget(), LLVM_EXTERNAL_VISIBILITY, and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction16()
bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 80 of file ARCDisassembler.cpp.
References Size.
readInstruction32()
bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 52 of file ARCDisassembler.cpp.
References Size.
Referenced by llvm::LanaiDisassembler::getInstruction().
readInstruction48()
bool readInstruction48 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint64_t & Insn) static
Definition at line 71 of file ARCDisassembler.cpp.
References Size.
readInstruction64()
bool readInstruction64 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint64_t & Insn) static
Definition at line 61 of file ARCDisassembler.cpp.
References Size.
Variable Documentation
GPR32DecoderTable
const uint16_t GPR32DecoderTable[] static
Initial value:
                                    = {
ARC::R0,  ARC::R1,    ARC::R2,  ARC::R3,   ARC::R4,  ARC::R5,  ARC::R6,
ARC::R7,  ARC::R8,    ARC::R9,  ARC::R10,  ARC::R11, ARC::R12, ARC::R13,
ARC::R14, ARC::R15,   ARC::R16, ARC::R17,  ARC::R18, ARC::R19, ARC::R20,
ARC::R21, ARC::R22,   ARC::R23, ARC::R24,  ARC::R25, ARC::GP,  ARC::FP,
ARC::SP,  ARC::ILINK, ARC::R30, ARC::BLINK}
Definition at line 126 of file ARCDisassembler.cpp.
Referenced by DecodeGPR32RegisterClass(), and DecodeGPR32RegisterClass().