LLVM: lib/Target/ARM/Disassembler/ARMDisassembler.cpp File Reference
ARMDisassembler.cpp File Reference
#include "ARMBaseInstrInfo.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "MCTargetDesc/ARMMCTargetDesc.h"
#include "TargetInfo/ARMTargetInfo.h"
#include "Utils/ARMBaseInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoder.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/SubtargetFeature.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <vector>
#include "ARMGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "arm-disassembler"
Typedefs
typedef DecodeStatus OperandDecoder(MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
Functions
static bool tryAddingSymbolicOperand (uint64_t Address, int32_t Value, bool isBranch, uint64_t InstSize, MCInst &MI, const MCDisassembler *Decoder)
tryAddingSymbolicOperand - trys to add a symbolic operand in place of the immediate Value in the MCInst.
static void tryAddingPcLoadReferenceComment (uint64_t Address, int Value, const MCDisassembler *Decoder)
tryAddingPcLoadReferenceComment - trys to add a comment as to what is being referenced by a load instruction with the base register that is the Pc.
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCLRMGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRnopcRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRnospRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRwithAPSRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRwithZRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRwithZRnospRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodetGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRPairRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRPairnospRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRspRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodetcGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecoderGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeHPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static bool PermitsD32 (const MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeDPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDPR_8RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSPR_8RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDPR_VFP2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDPairRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDPairSpacedRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMQQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMQQQQPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePredicateOperand (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeCCOutOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCCOutOperand (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeVpredNOperand (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeVpredROperand (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeSORegImmOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSORegRegOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRegListOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSPRRegListOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDPRRegListOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBitfieldMaskOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCopMemInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddrMode2IdxInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSORegMemOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeTSBInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddrMode3Instruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRFEInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCPSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeQADDInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMultipleWritebackInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeHINTInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2CPSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2HintSpaceInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2MOVTWInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeArmMOVTWInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSMLAInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSETPANInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeTSTInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddrModeImm12Operand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddrMode5Operand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddrMode5FP16Operand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddrMode7Operand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2BInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddrMode6Operand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLDInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVSTInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLDST1Instruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLDST2Instruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLDST3Instruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLDST4Instruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD1DupInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD2DupInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD3DupInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD4DupInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVMOVModImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVEModImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVEVADCInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVSHLMaxInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeShiftRight8Imm (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeShiftRight16Imm (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeShiftRight32Imm (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeShiftRight64Imm (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeTBLInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbAddSpecialReg (MCInst &Inst, uint16_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbBROperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2BROperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbCmpBROperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbAddrModeRR (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbAddrModeIS (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbAddrModePC (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbAddrModeSP (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2AddrModeSOReg (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2LoadLabel (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2LoadShift (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2Imm8 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2AddrModeImm8 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2LoadImm8 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2AddrModeImm12 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2LoadImm12 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2LoadT (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2Imm8S4 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2Imm7S4 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2AddrModeImm8s4 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2AddrModeImm7s4 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2AddrModeImm0_1020s4 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<int shift>
static DecodeStatus DecodeT2Imm7 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<int shift>
static DecodeStatus DecodeTAddrModeImm7 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<int shift, int WriteBack>
static DecodeStatus DecodeT2AddrModeImm7 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2LdStPre (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbAddSPImm (MCInst &Inst, uint16_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbAddSPReg (MCInst &Inst, uint16_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbCPS (MCInst &Inst, uint16_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePostIdxReg (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMveAddrModeRQ (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
template<int shift>
static DecodeStatus DecodeMveAddrModeQ (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbBLXOffset (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCoprocessor (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbTableBranch (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemBarrierOption (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumb2BCCInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2SOImm (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbBCCTargetOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThumbBLTargetOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeInstSyncBarrierOption (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSRMask (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBankedReg (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDoubleRegLoad (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDoubleRegStore (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLDRPreImm (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLDRPreReg (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSTRPreImm (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSTRPreReg (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD1LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVST1LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD2LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVST2LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD3LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVST3LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVLD4LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVST4LN (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVMOVSRR (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVMOVRRS (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeIT (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2LDRDPreInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2STRDPreInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2Adr (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2ShifterImmOperand (MCInst &Inst, uint32_t Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSwap (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVCVTD (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVCVTQ (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeNEONComplexLane64Instruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLDR (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecoderForMRRC2AndMCRR2 (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeForVMRSandVMSR (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<bool isSigned, bool isNeg, bool zeroPermitted, int size>
static DecodeStatus DecodeBFLabelOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBFAfterTargetOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePredNoALOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLOLoop (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLongShiftOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodetGPROddRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodetGPREvenRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRwithAPSR_NZCVnospRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVSCCLRM (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVPTMaskOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRestrictedIPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRestrictedSPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRestrictedUPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRestrictedFPPredicateOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVCVTImmOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static unsigned FixedRegForVSTRVLDR_SYSREG (unsigned Opcode)
template<bool Writeback>
static DecodeStatus DecodeVSTRVLDR_SYSREG (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVE_MEM_pre (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder, unsigned Rn, OperandDecoder RnDecoder, OperandDecoder AddrDecoder)
template<int shift>
static DecodeStatus DecodeMVE_MEM_1_pre (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<int shift>
static DecodeStatus DecodeMVE_MEM_2_pre (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<int shift>
static DecodeStatus DecodeMVE_MEM_3_pre (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned MinLog, unsigned MaxLog>
static DecodeStatus DecodePowerTwoOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned start>
static DecodeStatus DecodeMVEPairVectorIndexOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVEVMOVQtoDReg (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVEVMOVDRegtoQ (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVEOverlappingLongShift (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVEVCVTt1fp (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
template<bool scalar, OperandDecoder predicate_decoder>
static DecodeStatus DecodeMVEVCMP (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMveVCTP (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMVEVPNOT (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeT2AddSubSPImm (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLazyLoadStoreMul (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus checkDecodedInstruction (MCInst &MI, uint64_t &Size, uint64_t Address, raw_ostream &CS, uint32_t Insn, DecodeStatus Result)
static MCDisassembler * createARMDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMDisassembler ()
Variables
static const uint16_t GPRDecoderTable []
static const uint16_t CLRMGPRDecoderTable []
static const uint16_t GPRPairDecoderTable []
static const MCPhysReg SPRDecoderTable []
static const MCPhysReg DPRDecoderTable []
static const MCPhysReg QPRDecoderTable []
static const MCPhysReg DPairDecoderTable []
static const MCPhysReg DPairSpacedDecoderTable []
static const MCPhysReg QQPRDecoderTable []
static const MCPhysReg QQQQPRDecoderTable []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-disassembler"
Definition at line 37 of file ARMDisassembler.cpp.
Typedef Documentation
OperandDecoder
typedef DecodeStatus OperandDecoder(MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
Definition at line 160 of file ARMDisassembler.cpp.
Function Documentation
checkDecodedInstruction()
DecodeStatus checkDecodedInstruction (MCInst & MI, uint64_t & Size, uint64_t Address, raw_ostream & CS, uint32_t Insn, DecodeStatus Result) static
Definition at line 6107 of file ARMDisassembler.cpp.
References Cond, llvm::MCDisassembler::Fail, MI, and llvm::MCDisassembler::SoftFail.
createARMDisassembler()
MCDisassembler * createARMDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 6552 of file ARMDisassembler.cpp.
References T.
Referenced by LLVMInitializeARMDisassembler().
DecodeAddrMode2IdxInstruction()
DecodeStatus DecodeAddrMode2IdxInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1112 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRnopcRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::ARM_AM::getAM2Opc(), llvm::MCInst::getOpcode(), llvm::ARMII::IndexModePost, llvm::ARMII::IndexModePre, llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, Opc, P, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, llvm::MCDisassembler::SoftFail, llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
DecodeAddrMode3Instruction()
DecodeStatus DecodeAddrMode3Instruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1276 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::ARMII::IndexModePost, llvm::ARMII::IndexModePre, P, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeAddrMode5FP16Operand()
DecodeStatus DecodeAddrMode5FP16Operand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1914 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::ARM_AM::getAM5FP16Opc(), llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
DecodeAddrMode5Operand()
DecodeStatus DecodeAddrMode5Operand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1893 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::ARM_AM::getAM5Opc(), llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
DecodeAddrMode6Operand()
DecodeStatus DecodeAddrMode6Operand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1999 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeVLDInstruction(), and DecodeVSTInstruction().
DecodeAddrMode7Operand()
DecodeStatus DecodeAddrMode7Operand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1935 of file ARMDisassembler.cpp.
References DecodeGPRRegisterClass().
Referenced by DecodeLDR().
DecodeAddrModeImm12Operand()
DecodeStatus DecodeAddrModeImm12Operand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1872 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::Success, and tryAddingPcLoadReferenceComment().
Referenced by DecodeLDRPreImm(), and DecodeSTRPreImm().
DecodeArmMOVTWInstruction()
DecodeStatus DecodeArmMOVTWInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1764 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeBankedReg()
DecodeStatus DecodeBankedReg (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4150 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeBFAfterTargetOperand()
DecodeStatus DecodeBFAfterTargetOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5393 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeBFLabelOperand()
template<bool isSigned, bool isNeg, bool zeroPermitted, int size> DecodeStatus DecodeBFLabelOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5374 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, isNeg(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by DecodeLOLoop().
DecodeBitfieldMaskOperand()
DecodeStatus DecodeBitfieldMaskOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 870 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeBranchImmInstruction()
DecodeStatus DecodeBranchImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1969 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeCCOutOperand() [1/2]
DecodeStatus DecodeCCOutOperand (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 650 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), D(), and llvm::MCDisassembler::Success.
DecodeCCOutOperand() [2/2]
DecodeStatus DecodeCCOutOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 638 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2AddSubSPImm().
DecodeCLRMGPRRegisterClass()
DecodeStatus DecodeCLRMGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 227 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), CLRMGPRDecoderTable, llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by DecodeRegListOperand().
DecodeCopMemInstruction()
DecodeStatus DecodeCopMemInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 898 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::ARM_AM::getAM5Opc(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
DecodeCoprocessor()
DecodeStatus DecodeCoprocessor (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3887 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), llvm::isValidCoprocessorNumber(), and llvm::MCDisassembler::Success.
DecodeCPSInstruction()
DecodeStatus DecodeCPSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1480 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), mode, llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeQADDInstruction(), DecodeSMLAInstruction(), and DecodeSwap().
DecodeDoubleRegLoad()
DecodeStatus DecodeDoubleRegLoad (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4166 of file ARMDisassembler.cpp.
References Check, DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeDoubleRegStore()
DecodeStatus DecodeDoubleRegStore (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4188 of file ARMDisassembler.cpp.
References Check, DecodeGPRnopcRegisterClass(), DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeDPairRegisterClass()
DecodeStatus DecodeDPairRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 523 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), DPairDecoderTable, llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by DecodeTBLInstruction(), DecodeVLD1DupInstruction(), DecodeVLD2DupInstruction(), DecodeVLDInstruction(), and DecodeVSTInstruction().
DecodeDPairSpacedRegisterClass()
DecodeStatus DecodeDPairSpacedRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 546 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), DPairSpacedDecoderTable, llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by DecodeVLD2DupInstruction(), DecodeVLDInstruction(), and DecodeVSTInstruction().
DecodeDPR_8RegisterClass()
DecodeStatus DecodeDPR_8RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 471 of file ARMDisassembler.cpp.
References DecodeDPRRegisterClass(), and llvm::MCDisassembler::Fail.
DecodeDPR_VFP2RegisterClass()
DecodeStatus DecodeDPR_VFP2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 487 of file ARMDisassembler.cpp.
References DecodeDPRRegisterClass(), and llvm::MCDisassembler::Fail.
DecodeDPRRegisterClass()
DecodeStatus DecodeDPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 460 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), DPRDecoderTable, llvm::MCDisassembler::Fail, PermitsD32(), and llvm::MCDisassembler::Success.
Referenced by DecodeDPR_8RegisterClass(), DecodeDPR_VFP2RegisterClass(), DecodeDPRRegListOperand(), DecodeNEONComplexLane64Instruction(), DecodeTBLInstruction(), DecodeVCVTD(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVMOVModImmInstruction(), DecodeVSCCLRM(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), and DecodeVSTInstruction().
DecodeDPRRegListOperand()
DecodeStatus DecodeDPRRegListOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 843 of file ARMDisassembler.cpp.
References Check, DecodeDPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), PermitsD32(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeVSCCLRM().
DecodeForVMRSandVMSR()
DecodeStatus DecodeForVMRSandVMSR (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5322 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRnopcRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeGPRnopcRegisterClass()
DecodeStatus DecodeGPRnopcRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 241 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeAddrMode2IdxInstruction(), DecodeArmMOVTWInstruction(), DecodeDoubleRegStore(), DecodeForVMRSandVMSR(), DecodeLDR(), DecodeMveAddrModeRQ(), DecodePostIdxReg(), DecodeQADDInstruction(), DecoderForMRRC2AndMCRR2(), DecodeSMLAInstruction(), DecodeSORegRegOperand(), DecodeSwap(), DecodeT2AddrModeImm0_1020s4(), DecodeT2AddrModeImm7(), DecodeT2AddrModeImm7s4(), and DecodeVSTRVLDR_SYSREG().
DecodeGPRnospRegisterClass()
DecodeStatus DecodeGPRnospRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 254 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeGPRPairnospRegisterClass()
DecodeStatus DecodeGPRPairnospRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 342 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRPairDecoderTable, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeGPRPairRegisterClass()
DecodeStatus DecodeGPRPairRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 323 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRPairDecoderTable, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeDoubleRegLoad(), and DecodeDoubleRegStore().
DecodeGPRRegisterClass()
DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 216 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRDecoderTable, and llvm::MCDisassembler::Success.
Referenced by DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddrMode5FP16Operand(), DecodeAddrMode5Operand(), DecodeAddrMode6Operand(), DecodeAddrMode7Operand(), DecodeAddrModeImm12Operand(), DecodeCopMemInstruction(), DecodeDoubleRegLoad(), DecodeDoubleRegStore(), DecodeForVMRSandVMSR(), DecodeGPRnopcRegisterClass(), DecodeGPRnospRegisterClass(), DecodeGPRwithAPSRRegisterClass(), DecodeGPRwithZRRegisterClass(), DecodeLazyLoadStoreMul(), DecodeLDRPreImm(), DecodeLDRPreReg(), DecodeMemMultipleWritebackInstruction(), DecodeMVEVMOVDRegtoQ(), DecodeMVEVMOVQtoDReg(), DecodeRegListOperand(), DecodeRFEInstruction(), DecoderGPRRegisterClass(), DecodeSORegMemOperand(), DecodeSTRPreImm(), DecodeSTRPreReg(), DecodeT2AddrModeImm12(), DecodeT2AddrModeImm8(), DecodeT2AddrModeImm8s4(), DecodeT2AddrModeSOReg(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodetGPRRegisterClass(), DecodeThumbAddSPReg(), DecodeThumbTableBranch(), DecodeTSTInstruction(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVMOVRRS(), DecodeVMOVSRR(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), and DecodeVSTInstruction().
DecodeGPRspRegisterClass()
DecodeStatus DecodeGPRspRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 355 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRDecoderTable, and llvm::MCDisassembler::Success.
Referenced by DecodeT2AddSubSPImm().
DecodeGPRwithAPSR_NZCVnospRegisterClass()
DecodeStatus DecodeGPRwithAPSR_NZCVnospRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5515 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), GPRDecoderTable, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeGPRwithAPSRRegisterClass()
DecodeStatus DecodeGPRwithAPSRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 268 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), and llvm::MCDisassembler::Success.
DecodeGPRwithZRnospRegisterClass()
DecodeStatus DecodeGPRwithZRnospRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 301 of file ARMDisassembler.cpp.
References Check, DecodeGPRwithZRRegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeGPRwithZRRegisterClass()
DecodeStatus DecodeGPRwithZRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 283 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeGPRwithZRnospRegisterClass(), and DecodeMVEVCMP().
DecodeHINTInstruction()
DecodeStatus DecodeHINTInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1645 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeHPRRegisterClass()
DecodeStatus DecodeHPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 434 of file ARMDisassembler.cpp.
References DecodeSPRRegisterClass().
DecodeInstSyncBarrierOption()
DecodeStatus DecodeInstSyncBarrierOption (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4039 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeIT()
DecodeStatus DecodeIT (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4928 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), mask(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeLazyLoadStoreMul()
DecodeStatus DecodeLazyLoadStoreMul (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 6084 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeLDR()
DecodeStatus DecodeLDR (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5249 of file ARMDisassembler.cpp.
References Check, Cond, DecodeAddrMode7Operand(), DecodeGPRnopcRegisterClass(), DecodePostIdxReg(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeLDRPreImm()
DecodeStatus DecodeLDRPreImm (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4214 of file ARMDisassembler.cpp.
References Check, DecodeAddrModeImm12Operand(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeLDRPreReg()
DecodeStatus DecodeLDRPreReg (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4240 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSORegMemOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeLOLoop()
DecodeStatus DecodeLOLoop (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5414 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecodeBFLabelOperand(), DecodePredicateOperand(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeLongShiftOperand()
DecodeStatus DecodeLongShiftOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5479 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeMemBarrierOption()
DecodeStatus DecodeMemBarrierOption (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3922 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by DecodeThumb2BCCInstruction().
DecodeMemMultipleWritebackInstruction()
DecodeStatus DecodeMemMultipleWritebackInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1553 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeRegListOperand(), DecodeRFEInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeMQPRRegisterClass()
DecodeStatus DecodeMQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 556 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, QPRDecoderTable, and llvm::MCDisassembler::Success.
Referenced by DecodeMVE_MEM_3_pre(), DecodeMVE_MEM_pre(), DecodeMveAddrModeQ(), DecodeMveAddrModeRQ(), DecodeMVEModImmInstruction(), DecodeMVEVADCInstruction(), DecodeMVEVCMP(), DecodeMVEVCVTt1fp(), DecodeMVEVMOVDRegtoQ(), and DecodeMVEVMOVQtoDReg().
DecodeMQQPRRegisterClass()
DecodeStatus DecodeMQQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 572 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, QQPRDecoderTable, and llvm::MCDisassembler::Success.
DecodeMQQQQPRRegisterClass()
DecodeStatus DecodeMQQQQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 588 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, QQQQPRDecoderTable, and llvm::MCDisassembler::Success.
DecodeMSRMask()
DecodeStatus DecodeMSRMask (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4049 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeMVE_MEM_1_pre()
template<int shift> DecodeStatus DecodeMVE_MEM_1_pre (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5783 of file ARMDisassembler.cpp.
References DecodeMVE_MEM_pre(), DecodeTAddrModeImm7(), DecodetGPRRegisterClass(), and llvm::MCD::fieldFromInstruction().
DecodeMVE_MEM_2_pre()
template<int shift> DecodeStatus DecodeMVE_MEM_2_pre (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5793 of file ARMDisassembler.cpp.
References DecodeMVE_MEM_pre(), DecoderGPRRegisterClass(), DecodeT2AddrModeImm7(), and llvm::MCD::fieldFromInstruction().
DecodeMVE_MEM_3_pre()
template<int shift> DecodeStatus DecodeMVE_MEM_3_pre (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5803 of file ARMDisassembler.cpp.
References DecodeMQPRRegisterClass(), DecodeMVE_MEM_pre(), DecodeMveAddrModeQ(), and llvm::MCD::fieldFromInstruction().
DecodeMVE_MEM_pre()
DecodeStatus DecodeMVE_MEM_pre (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder, unsigned Rn, OperandDecoder RnDecoder, OperandDecoder AddrDecoder) inline static
Definition at line 5762 of file ARMDisassembler.cpp.
References Check, DecodeMQPRRegisterClass(), DecodeVpredNOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeMVE_MEM_1_pre(), DecodeMVE_MEM_2_pre(), and DecodeMVE_MEM_3_pre().
DecodeMveAddrModeQ()
template<int shift> DecodeStatus DecodeMveAddrModeQ (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3839 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeMVE_MEM_3_pre().
DecodeMveAddrModeRQ()
DecodeStatus DecodeMveAddrModeRQ (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3823 of file ARMDisassembler.cpp.
References Check, DecodeGPRnopcRegisterClass(), DecodeMQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeMVEModImmInstruction()
DecodeStatus DecodeMVEModImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2859 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeMQPRRegisterClass(), DecodeVpredROperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
DecodeMVEOverlappingLongShift()
DecodeStatus DecodeMVEOverlappingLongShift (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5889 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodePredicateOperand(), DecoderGPRRegisterClass(), DecodetGPREvenRegisterClass(), DecodetGPROddRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm_unreachable, llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeMVEPairVectorIndexOperand()
template<unsigned start> DecodeStatus DecodeMVEPairVectorIndexOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5827 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by DecodeMVEVMOVDRegtoQ(), and DecodeMVEVMOVQtoDReg().
DecodeMVEVADCInstruction()
DecodeStatus DecodeMVEVADCInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2885 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecodeMQPRRegisterClass(), DecodeVpredROperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeMVEVCMP()
template<bool scalar, OperandDecoder predicate_decoder> DecodeStatus DecodeMVEVCMP (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5992 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecodeGPRwithZRRegisterClass(), DecodeMQPRRegisterClass(), DecodeVpredNOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeMveVCTP()
DecodeStatus DecodeMveVCTP (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 6026 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecoderGPRRegisterClass(), DecodeVpredNOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeMVEVCVTt1fp()
DecodeStatus DecodeMVEVCVTt1fp (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5971 of file ARMDisassembler.cpp.
References Check, DecodeMQPRRegisterClass(), DecodeVCVTImmOperand(), DecodeVpredROperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeMVEVMOVDRegtoQ()
DecodeStatus DecodeMVEVMOVDRegtoQ (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5861 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodeMQPRRegisterClass(), DecodeMVEPairVectorIndexOperand(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeMVEVMOVQtoDReg()
DecodeStatus DecodeMVEVMOVQtoDReg (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5836 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodeMQPRRegisterClass(), DecodeMVEPairVectorIndexOperand(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeMVEVPNOT()
DecodeStatus DecodeMVEVPNOT (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 6037 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecodeVpredNOperand(), and llvm::MCDisassembler::Success.
DecodeNEONComplexLane64Instruction()
DecodeStatus DecodeNEONComplexLane64Instruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5217 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodeQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodePostIdxReg()
DecodeStatus DecodePostIdxReg (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3809 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeLDR().
DecodePowerTwoOperand()
template<unsigned MinLog, unsigned MaxLog> DecodeStatus DecodePowerTwoOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5813 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodePredicateOperand() [1/2]
DecodeStatus DecodePredicateOperand (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 626 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), D(), and llvm::MCDisassembler::Success.
DecodePredicateOperand() [2/2]
DecodeStatus DecodePredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 601 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCInstrInfo::get(), llvm::MCInst::getOpcode(), llvm::MCInstrDesc::isPredicable(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeArmMOVTWInstruction(), DecodeBranchImmInstruction(), DecodeCopMemInstruction(), DecodeDoubleRegLoad(), DecodeDoubleRegStore(), DecodeForVMRSandVMSR(), DecodeHINTInstruction(), DecodeLazyLoadStoreMul(), DecodeLDR(), DecodeLDRPreImm(), DecodeLDRPreReg(), DecodeLOLoop(), DecodeMemMultipleWritebackInstruction(), DecodeMVEOverlappingLongShift(), DecodeMVEVMOVDRegtoQ(), DecodeMVEVMOVQtoDReg(), DecodeQADDInstruction(), DecodeSMLAInstruction(), DecodeSTRPreImm(), DecodeSTRPreReg(), DecodeSwap(), DecodeT2AddSubSPImm(), DecodeT2Adr(), DecodeT2BInstruction(), DecodeT2CPSInstruction(), DecodeT2HintSpaceInstruction(), DecodeT2LDRDPreInstruction(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeT2STRDPreInstruction(), DecodeTBLInstruction(), DecodeThumb2BCCInstruction(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPImm(), DecodeThumbAddSPReg(), DecodeThumbTableBranch(), DecodeTSBInstruction(), DecodeTSTInstruction(), DecodeVCVTD(), DecodeVCVTQ(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVMOVModImmInstruction(), DecodeVMOVRRS(), DecodeVMOVSRR(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), and DecodeVSTInstruction().
DecodePredNoALOperand()
DecodeStatus DecodePredNoALOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5405 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeQADDInstruction()
DecodeStatus DecodeQADDInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1528 of file ARMDisassembler.cpp.
References Check, DecodeCPSInstruction(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeQPRRegisterClass()
DecodeStatus DecodeQPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 502 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, QPRDecoderTable, and llvm::MCDisassembler::Success.
Referenced by DecodeNEONComplexLane64Instruction(), DecodeVCVTQ(), DecodeVMOVModImmInstruction(), and DecodeVSHLMaxInstruction().
DecodeRegListOperand()
DecodeStatus DecodeRegListOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 770 of file ARMDisassembler.cpp.
References Check, DecodeCLRMGPRRegisterClass(), DecodeGPRRegisterClass(), llvm::MCInst::end(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeMemMultipleWritebackInstruction().
DecodeRestrictedFPPredicateOperand()
DecodeStatus DecodeRestrictedFPPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5637 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::EQ, llvm::MCDisassembler::Fail, llvm::ARMCC::GE, llvm::ARMCC::GT, llvm::ARMCC::LE, llvm::ARMCC::LT, llvm::ARMCC::NE, and llvm::MCDisassembler::Success.
DecodeRestrictedIPredicateOperand()
DecodeStatus DecodeRestrictedIPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5601 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::EQ, llvm::ARMCC::NE, and llvm::MCDisassembler::Success.
DecodeRestrictedSPredicateOperand()
DecodeStatus DecodeRestrictedSPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5608 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::GE, llvm::ARMCC::GT, llvm::ARMCC::LE, llvm::ARMCC::LT, and llvm::MCDisassembler::Success.
DecodeRestrictedUPredicateOperand()
DecodeStatus DecodeRestrictedUPredicateOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5630 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARMCC::HI, llvm::ARMCC::HS, and llvm::MCDisassembler::Success.
DecodeRFEInstruction()
DecodeStatus DecodeRFEInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1468 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeMemMultipleWritebackInstruction().
DecoderForMRRC2AndMCRR2()
DecodeStatus DecoderForMRRC2AndMCRR2 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5276 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecoderGPRRegisterClass()
DecodeStatus DecoderGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 397 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeLOLoop(), DecodeMVE_MEM_2_pre(), DecodeMVEOverlappingLongShift(), DecodeMveVCTP(), DecodeSORegImmOperand(), DecodeT2AddrModeImm7(), DecodeT2AddrModeSOReg(), DecodeT2Adr(), DecodeT2LDRDPreInstruction(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeT2STRDPreInstruction(), and DecodeThumbTableBranch().
DecodeSETPANInstruction()
DecodeStatus DecodeSETPANInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1821 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
Referenced by DecodeTSTInstruction().
DecodeShiftRight16Imm()
DecodeStatus DecodeShiftRight16Imm (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2939 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeShiftRight32Imm()
DecodeStatus DecodeShiftRight32Imm (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2946 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeShiftRight64Imm()
DecodeStatus DecodeShiftRight64Imm (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2953 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeShiftRight8Imm()
DecodeStatus DecodeShiftRight8Imm (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2932 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeSMLAInstruction()
DecodeStatus DecodeSMLAInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1792 of file ARMDisassembler.cpp.
References Check, DecodeCPSInstruction(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeSORegImmOperand()
DecodeStatus DecodeSORegImmOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 696 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check, llvm::MCOperand::createImm(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, and llvm::MCDisassembler::Success.
DecodeSORegMemOperand()
DecodeStatus DecodeSORegMemOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1217 of file ARMDisassembler.cpp.
References llvm::ARM_AM::add, llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::ARM_AM::getAM2Opc(), llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, llvm::ARM_AM::sub, and llvm::MCDisassembler::Success.
Referenced by DecodeLDRPreReg(), and DecodeSTRPreReg().
DecodeSORegRegOperand()
DecodeStatus DecodeSORegRegOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 734 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARM_AM::asr, Check, llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARM_AM::ror, and llvm::MCDisassembler::Success.
DecodeSPR_8RegisterClass()
DecodeStatus DecodeSPR_8RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 479 of file ARMDisassembler.cpp.
References DecodeSPRRegisterClass(), and llvm::MCDisassembler::Fail.
DecodeSPRRegisterClass()
DecodeStatus DecodeSPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 423 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, SPRDecoderTable, and llvm::MCDisassembler::Success.
Referenced by DecodeHPRRegisterClass(), DecodeSPR_8RegisterClass(), DecodeSPRRegListOperand(), DecodeVMOVRRS(), DecodeVMOVSRR(), and DecodeVSCCLRM().
DecodeSPRRegListOperand()
DecodeStatus DecodeSPRRegListOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 818 of file ARMDisassembler.cpp.
References Check, DecodeSPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeSTRPreImm()
DecodeStatus DecodeSTRPreImm (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4268 of file ARMDisassembler.cpp.
References Check, DecodeAddrModeImm12Operand(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeSTRPreReg()
DecodeStatus DecodeSTRPreReg (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4294 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSORegMemOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeSwap()
DecodeStatus DecodeSwap (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5069 of file ARMDisassembler.cpp.
References Check, DecodeCPSInstruction(), DecodeGPRnopcRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeT2AddrModeImm0_1020s4()
DecodeStatus DecodeT2AddrModeImm0_1020s4 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3627 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRnopcRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeT2AddrModeImm12()
DecodeStatus DecodeT2AddrModeImm12 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3417 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2LoadImm12().
DecodeT2AddrModeImm7()
template<int shift, int WriteBack> DecodeStatus DecodeT2AddrModeImm7 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3676 of file ARMDisassembler.cpp.
References Check, DecodeGPRnopcRegisterClass(), DecoderGPRRegisterClass(), DecodeT2Imm7(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeMVE_MEM_2_pre().
DecodeT2AddrModeImm7s4()
DecodeStatus DecodeT2AddrModeImm7s4 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3611 of file ARMDisassembler.cpp.
References Check, DecodeGPRnopcRegisterClass(), DecodeT2Imm7S4(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeVSTRVLDR_SYSREG().
DecodeT2AddrModeImm8()
DecodeStatus DecodeT2AddrModeImm8 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3284 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodeT2Imm8(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2LdStPre(), DecodeT2LoadImm8(), and DecodeT2LoadT().
DecodeT2AddrModeImm8s4()
DecodeStatus DecodeT2AddrModeImm8s4 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3595 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodeT2Imm8S4(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2LDRDPreInstruction(), and DecodeT2STRDPreInstruction().
DecodeT2AddrModeSOReg()
DecodeStatus DecodeT2AddrModeSOReg (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3102 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2LoadShift().
DecodeT2AddSubSPImm()
DecodeStatus DecodeT2AddSubSPImm (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 6047 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeCCOutOperand(), DecodeGPRspRegisterClass(), DecodePredicateOperand(), DecodeT2SOImm(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2Adr()
DecodeStatus DecodeT2Adr (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5031 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodePredicateOperand(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getNumOperands(), and llvm::MCInst::setOpcode().
DecodeT2BInstruction()
DecodeStatus DecodeT2BInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1941 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodePredicateOperand(), llvm::MCD::fieldFromInstruction(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeT2BROperand()
DecodeStatus DecodeT2BROperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3033 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
Referenced by DecodeThumb2BCCInstruction().
DecodeT2CPSInstruction()
DecodeStatus DecodeT2CPSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1668 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), mode, llvm::MCInst::setOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeT2HintSpaceInstruction()
DecodeStatus DecodeT2HintSpaceInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1713 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodePredicateOperand(), llvm::MCD::fieldFromInstruction(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2Imm7()
template<int shift> DecodeStatus DecodeT2Imm7 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3644 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2AddrModeImm7(), and DecodeTAddrModeImm7().
DecodeT2Imm7S4()
DecodeStatus DecodeT2Imm7S4 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3580 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2AddrModeImm7s4().
DecodeT2Imm8()
DecodeStatus DecodeT2Imm8 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3272 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2AddrModeImm8().
DecodeT2Imm8S4()
DecodeStatus DecodeT2Imm8S4 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3566 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2AddrModeImm8s4().
DecodeT2LDRDPreInstruction()
DecodeStatus DecodeT2LDRDPreInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4957 of file ARMDisassembler.cpp.
References Check, DecodePredicateOperand(), DecoderGPRRegisterClass(), DecodeT2AddrModeImm8s4(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), P, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeT2LdStPre()
DecodeStatus DecodeT2LdStPre (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3694 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeT2AddrModeImm8(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), load, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2LoadImm12()
DecodeStatus DecodeT2LoadImm12 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3444 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeT2AddrModeImm12(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2LoadImm8()
DecodeStatus DecodeT2LoadImm8 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3331 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeT2AddrModeImm8(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2LoadLabel()
DecodeStatus DecodeT2LoadLabel (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3132 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadShift(), and DecodeT2LoadT().
DecodeT2LoadShift()
DecodeStatus DecodeT2LoadShift (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3187 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeT2AddrModeSOReg(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2LoadT()
DecodeStatus DecodeT2LoadT (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3526 of file ARMDisassembler.cpp.
References Check, DecodePredicateOperand(), DecoderGPRRegisterClass(), DecodeT2AddrModeImm8(), DecodeT2LoadLabel(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeT2MOVTWInstruction()
DecodeStatus DecodeT2MOVTWInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1738 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodePredicateOperand(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeT2ShifterImmOperand()
DecodeStatus DecodeT2ShifterImmOperand (MCInst & Inst, uint32_t Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5058 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeT2SOImm()
DecodeStatus DecodeT2SOImm (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3975 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCD::fieldFromInstruction(), llvm::rotr(), and llvm::MCDisassembler::Success.
Referenced by DecodeT2AddSubSPImm().
DecodeT2STRDPreInstruction()
DecodeStatus DecodeT2STRDPreInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4995 of file ARMDisassembler.cpp.
References Check, DecodePredicateOperand(), DecoderGPRRegisterClass(), DecodeT2AddrModeImm8s4(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), P, llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeTAddrModeImm7()
template<int shift> DecodeStatus DecodeTAddrModeImm7 (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3659 of file ARMDisassembler.cpp.
References Check, DecodeT2Imm7(), DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
Referenced by DecodeMVE_MEM_1_pre().
DecodeTBLInstruction()
DecodeStatus DecodeTBLInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2960 of file ARMDisassembler.cpp.
References Check, DecodeDPairRegisterClass(), DecodeDPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), op, and llvm::MCDisassembler::Success.
DecodetcGPRRegisterClass()
DecodeStatus DecodetcGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 366 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodetGPREvenRegisterClass()
DecodeStatus DecodetGPREvenRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5503 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRDecoderTable, and llvm::MCDisassembler::Success.
Referenced by DecodeMVEOverlappingLongShift().
DecodetGPROddRegisterClass()
DecodeStatus DecodetGPROddRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5492 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRDecoderTable, and llvm::MCDisassembler::Success.
Referenced by DecodeMVEOverlappingLongShift().
DecodetGPRRegisterClass()
DecodeStatus DecodetGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 310 of file ARMDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by DecodeMVE_MEM_1_pre(), DecodeTAddrModeImm7(), DecodeThumbAddrModeIS(), DecodeThumbAddrModeRR(), and DecodeThumbAddSpecialReg().
DecodeThumb2BCCInstruction()
DecodeStatus DecodeThumb2BCCInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3932 of file ARMDisassembler.cpp.
References Check, DecodeMemBarrierOption(), DecodePredicateOperand(), DecodeT2BROperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeThumbAddrModeIS()
DecodeStatus DecodeThumbAddrModeIS (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3067 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeThumbAddrModePC()
DecodeStatus DecodeThumbAddrModePC (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3082 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingPcLoadReferenceComment().
DecodeThumbAddrModeRR()
DecodeStatus DecodeThumbAddrModeRR (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3051 of file ARMDisassembler.cpp.
References Check, DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeThumbAddrModeSP()
DecodeStatus DecodeThumbAddrModeSP (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3093 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
DecodeThumbAddSpecialReg()
DecodeStatus DecodeThumbAddSpecialReg (MCInst & Inst, uint16_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2998 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodePredicateOperand(), DecodetGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
DecodeThumbAddSPImm()
DecodeStatus DecodeThumbAddSPImm (MCInst & Inst, uint16_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3757 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodePredicateOperand(), llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeThumbAddSPReg()
DecodeStatus DecodeThumbAddSPReg (MCInst & Inst, uint16_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3770 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createReg(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
DecodeThumbBCCTargetOperand()
DecodeStatus DecodeThumbBCCTargetOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4006 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeThumbBLTargetOperand()
DecodeStatus DecodeThumbBLTargetOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4015 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeThumbBLXOffset()
DecodeStatus DecodeThumbBLXOffset (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3862 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeThumbBROperand()
DecodeStatus DecodeThumbBROperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3024 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::SignExtend32(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeThumbCmpBROperand()
DecodeStatus DecodeThumbCmpBROperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3042 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Success, and tryAddingSymbolicOperand().
DecodeThumbCPS()
DecodeStatus DecodeThumbCPS (MCInst & Inst, uint16_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3797 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeThumbTableBranch()
DecodeStatus DecodeThumbTableBranch (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 3903 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecoderGPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeTSBInstruction()
DecodeStatus DecodeTSBInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1261 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::ARM_TSB::CSYNC, DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
DecodeTSTInstruction()
DecodeStatus DecodeTSTInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1850 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSETPANInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeVCVTD()
DecodeStatus DecodeVCVTD (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5096 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodePredicateOperand(), DecodeVMOVModImmInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), op, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeVCVTImmOperand()
DecodeStatus DecodeVCVTImmOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5667 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeMVEVCVTt1fp().
DecodeVCVTQ()
DecodeStatus DecodeVCVTQ (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5156 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodePredicateOperand(), DecodeQPRRegisterClass(), DecodeVMOVModImmInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), op, llvm::MCInst::setOpcode(), and llvm::MCDisassembler::Success.
DecodeVLD1DupInstruction()
DecodeStatus DecodeVLD1DupInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2622 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeDPairRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVLD1LN()
DecodeStatus DecodeVLD1LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4320 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVLD2DupInstruction()
DecodeStatus DecodeVLD2DupInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2671 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVLD2LN()
DecodeStatus DecodeVLD2LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4454 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVLD3DupInstruction()
DecodeStatus DecodeVLD3DupInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2721 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and llvm::MCDisassembler::Success.
DecodeVLD3LN()
DecodeStatus DecodeVLD3LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4586 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVLD4DupInstruction()
DecodeStatus DecodeVLD4DupInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2758 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVLD4LN()
DecodeStatus DecodeVLD4LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4721 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVLDInstruction()
DecodeStatus DecodeVLDInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2017 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeAddrMode6Operand(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeVLDST1Instruction(), DecodeVLDST2Instruction(), DecodeVLDST3Instruction(), and DecodeVLDST4Instruction().
DecodeVLDST1Instruction()
DecodeStatus DecodeVLDST1Instruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2567 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), and load.
DecodeVLDST2Instruction()
DecodeStatus DecodeVLDST2Instruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2581 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), load, and llvm::size().
DecodeVLDST3Instruction()
DecodeStatus DecodeVLDST3Instruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2597 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), load, and llvm::size().
DecodeVLDST4Instruction()
DecodeStatus DecodeVLDST4Instruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2611 of file ARMDisassembler.cpp.
References DecodeVLDInstruction(), DecodeVSTInstruction(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), load, and llvm::size().
DecodeVMOVModImmInstruction()
DecodeStatus DecodeVMOVModImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2812 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodePredicateOperand(), DecodeQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeVCVTD(), and DecodeVCVTQ().
DecodeVMOVRRS()
DecodeStatus DecodeVMOVRRS (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4902 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeVMOVSRR()
DecodeStatus DecodeVMOVSRR (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4876 of file ARMDisassembler.cpp.
References Check, DecodeGPRRegisterClass(), DecodePredicateOperand(), DecodeSPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeVpredNOperand()
DecodeStatus DecodeVpredNOperand (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 659 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), D(), llvm::ARMVCC::None, and llvm::MCDisassembler::Success.
Referenced by DecodeMVE_MEM_pre(), DecodeMVEVCMP(), DecodeMveVCTP(), and DecodeMVEVPNOT().
DecodeVpredROperand()
DecodeStatus DecodeVpredROperand (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 672 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), D(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::ARMVCC::None, llvm::MCDisassembler::Success, and llvm::MCOI::TIED_TO.
Referenced by DecodeMVEModImmInstruction(), DecodeMVEVADCInstruction(), and DecodeMVEVCVTt1fp().
DecodeVPTMaskOperand()
DecodeStatus DecodeVPTMaskOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5569 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeVSCCLRM()
DecodeStatus DecodeVSCCLRM (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5532 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeDPRRegListOperand(), DecodeSPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::SoftFail, and llvm::MCDisassembler::Success.
DecodeVSHLMaxInstruction()
DecodeStatus DecodeVSHLMaxInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2911 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), DecodeDPRRegisterClass(), DecodePredicateOperand(), DecodeQPRRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVST1LN()
DecodeStatus DecodeVST1LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4388 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVST2LN()
DecodeStatus DecodeVST2LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4522 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVST3LN()
DecodeStatus DecodeVST3LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4657 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVST4LN()
DecodeStatus DecodeVST4LN (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 4803 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::size(), and llvm::MCDisassembler::Success.
DecodeVSTInstruction()
DecodeStatus DecodeVSTInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2295 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeAddrMode6Operand(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeGPRRegisterClass(), DecodePredicateOperand(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
Referenced by DecodeVLDST1Instruction(), DecodeVLDST2Instruction(), DecodeVLDST3Instruction(), and DecodeVLDST4Instruction().
DecodeVSTRVLDR_SYSREG()
template<bool Writeback> DecodeStatus DecodeVSTRVLDR_SYSREG (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 5718 of file ARMDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::ARMCC::AL, Check, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeGPRnopcRegisterClass(), DecodeT2AddrModeImm7s4(), llvm::MCDisassembler::Fail, llvm::MCD::fieldFromInstruction(), FixedRegForVSTRVLDR_SYSREG(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCDisassembler::getSubtargetInfo(), and llvm::MCDisassembler::Success.
FixedRegForVSTRVLDR_SYSREG()
unsigned FixedRegForVSTRVLDR_SYSREG (unsigned Opcode) static
Definition at line 5696 of file ARMDisassembler.cpp.
Referenced by DecodeVSTRVLDR_SYSREG().
LLVMInitializeARMDisassembler()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMDisassembler ()
Definition at line 6559 of file ARMDisassembler.cpp.
References createARMDisassembler(), llvm::getTheARMBETarget(), llvm::getTheARMLETarget(), llvm::getTheThumbBETarget(), llvm::getTheThumbLETarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
PermitsD32()
bool PermitsD32 (const MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 452 of file ARMDisassembler.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), and llvm::MCDisassembler::getSubtargetInfo().
Referenced by DecodeDPRRegisterClass(), and DecodeDPRRegListOperand().
tryAddingPcLoadReferenceComment()
void tryAddingPcLoadReferenceComment (uint64_t Address, int Value, const MCDisassembler * Decoder) static
tryAddingPcLoadReferenceComment - trys to add a comment as to what is being referenced by a load instruction with the base register that is the Pc.
These can often be values in a literal pool near the Address of the instruction. The Address of the instruction and its immediate Value are used as a possible literal pool entry. The SymbolLookUp call back will return the name of a symbol referenced by the literal pool's entry if the referenced address is that of a symbol. Or it will return a pointer to a literal 'C' string if the referenced address of the literal pool's entry is an address into a section with 'C' string literals.
Definition at line 195 of file ARMDisassembler.cpp.
References llvm::MCDisassembler::tryAddingPcLoadReferenceComment().
Referenced by DecodeAddrModeImm12Operand(), and DecodeThumbAddrModePC().
tryAddingSymbolicOperand()
bool tryAddingSymbolicOperand (uint64_t Address, int32_t Value, bool isBranch, uint64_t InstSize, MCInst & MI, const MCDisassembler * Decoder) static
tryAddingSymbolicOperand - trys to add a symbolic operand in place of the immediate Value in the MCInst.
The immediate Value has had any PC adjustment made by the caller. If the instruction is a branch instruction then isBranch is true, else false. If the getOpInfo() function was set as part of the setupForSymbolicDisassembly() call then that function is called to get any symbolic information at the Address for this instruction. If that returns non-zero then the symbolic information it returns is used to create an MCExpr and that is added as an operand to the MCInst. If getOpInfo() returns zero and isBranch is true then a symbol look up for Value is done and if a symbol is found an MCExpr is created with that, else an MCExpr with Value is created. This function returns true if it adds an operand to the MCInst and false otherwise.
Definition at line 176 of file ARMDisassembler.cpp.
References isBranch(), MI, and llvm::MCDisassembler::tryAddingSymbolicOperand().
Referenced by DecodeArmMOVTWInstruction(), DecodeBFAfterTargetOperand(), DecodeBFLabelOperand(), decodeBranch(), DecodeBranchImmInstruction(), DecodeT2BInstruction(), DecodeT2BROperand(), DecodeT2MOVTWInstruction(), DecodeThumbBCCTargetOperand(), DecodeThumbBLTargetOperand(), DecodeThumbBLXOffset(), DecodeThumbBROperand(), and DecodeThumbCmpBROperand().
Variable Documentation
CLRMGPRDecoderTable
const uint16_t CLRMGPRDecoderTable[] static
Initial value:
                                          = {
  ARM::R0, ARM::R1, ARM::R2, ARM::R3,
  ARM::R4, ARM::R5, ARM::R6, ARM::R7,
  ARM::R8, ARM::R9, ARM::R10, ARM::R11,
  ARM::R12, 0, ARM::LR, ARM::APSR
}
Definition at line 209 of file ARMDisassembler.cpp.
Referenced by DecodeCLRMGPRRegisterClass().
DPairDecoderTable
const MCPhysReg DPairDecoderTable[] static
Initial value:
                                         = {
  ARM::Q0,  ARM::D1_D2,   ARM::Q1,  ARM::D3_D4,   ARM::Q2,  ARM::D5_D6,
  ARM::Q3,  ARM::D7_D8,   ARM::Q4,  ARM::D9_D10,  ARM::Q5,  ARM::D11_D12,
  ARM::Q6,  ARM::D13_D14, ARM::Q7,  ARM::D15_D16, ARM::Q8,  ARM::D17_D18,
  ARM::Q9,  ARM::D19_D20, ARM::Q10, ARM::D21_D22, ARM::Q11, ARM::D23_D24,
  ARM::Q12, ARM::D25_D26, ARM::Q13, ARM::D27_D28, ARM::Q14, ARM::D29_D30,
  ARM::Q15
}
Definition at line 514 of file ARMDisassembler.cpp.
Referenced by DecodeDPairRegisterClass().
DPairSpacedDecoderTable
const MCPhysReg DPairSpacedDecoderTable[] static
Initial value:
                                               = {
  ARM::D0_D2,   ARM::D1_D3,   ARM::D2_D4,   ARM::D3_D5,
  ARM::D4_D6,   ARM::D5_D7,   ARM::D6_D8,   ARM::D7_D9,
  ARM::D8_D10,  ARM::D9_D11,  ARM::D10_D12, ARM::D11_D13,
  ARM::D12_D14, ARM::D13_D15, ARM::D14_D16, ARM::D15_D17,
  ARM::D16_D18, ARM::D17_D19, ARM::D18_D20, ARM::D19_D21,
  ARM::D20_D22, ARM::D21_D23, ARM::D22_D24, ARM::D23_D25,
  ARM::D24_D26, ARM::D25_D27, ARM::D26_D28, ARM::D27_D29,
  ARM::D28_D30, ARM::D29_D31
}
Definition at line 534 of file ARMDisassembler.cpp.
Referenced by DecodeDPairSpacedRegisterClass().
DPRDecoderTable
const MCPhysReg DPRDecoderTable[] static
Initial value:
                                       = {
     ARM::D0,  ARM::D1,  ARM::D2,  ARM::D3,
     ARM::D4,  ARM::D5,  ARM::D6,  ARM::D7,
     ARM::D8,  ARM::D9, ARM::D10, ARM::D11,
    ARM::D12, ARM::D13, ARM::D14, ARM::D15,
    ARM::D16, ARM::D17, ARM::D18, ARM::D19,
    ARM::D20, ARM::D21, ARM::D22, ARM::D23,
    ARM::D24, ARM::D25, ARM::D26, ARM::D27,
    ARM::D28, ARM::D29, ARM::D30, ARM::D31
}
Definition at line 440 of file ARMDisassembler.cpp.
Referenced by DecodeDPRRegisterClass().
GPRDecoderTable
const uint16_t GPRDecoderTable[] static
Initial value:
                                      = {
  ARM::R0, ARM::R1, ARM::R2, ARM::R3,
  ARM::R4, ARM::R5, ARM::R6, ARM::R7,
  ARM::R8, ARM::R9, ARM::R10, ARM::R11,
  ARM::R12, ARM::SP, ARM::LR, ARM::PC
}
Definition at line 202 of file ARMDisassembler.cpp.
Referenced by DecodeGPR8RegisterClass(), DecodeGPRRegisterClass(), DecodeGPRRegisterClass(), DecodeGPRRegisterClass(), DecodeGPRRegisterClass(), DecodeGPRspRegisterClass(), DecodeGPRwithAPSR_NZCVnospRegisterClass(), DecodeLD8loRegisterClass(), DecodeLD8RegisterClass(), decodeLoadStore(), decodeMemoryOpValue(), DecodemGPRRegisterClass(), DecodeRegSeqOperand(), decodeRiMemoryValue(), decodeRrMemoryValue(), DecodesGPRRegisterClass(), decodeSplsValue(), DecodetGPREvenRegisterClass(), and DecodetGPROddRegisterClass().
GPRPairDecoderTable
const uint16_t GPRPairDecoderTable[] static
Initial value:
                                          = {
  ARM::R0_R1, ARM::R2_R3,   ARM::R4_R5,  ARM::R6_R7,
  ARM::R8_R9, ARM::R10_R11, ARM::R12_SP
}
Definition at line 318 of file ARMDisassembler.cpp.
Referenced by DecodeDREGSRegisterClass(), DecodeGPRPairnospRegisterClass(), DecodeGPRPairRegisterClass(), DecodeGPRPairRegisterClass(), and DecodeIWREGSRegisterClass().
QPRDecoderTable
const MCPhysReg QPRDecoderTable[] static
Initial value:
                                       = {
     ARM::Q0,  ARM::Q1,  ARM::Q2,  ARM::Q3,
     ARM::Q4,  ARM::Q5,  ARM::Q6,  ARM::Q7,
     ARM::Q8,  ARM::Q9, ARM::Q10, ARM::Q11,
    ARM::Q12, ARM::Q13, ARM::Q14, ARM::Q15
}
Definition at line 495 of file ARMDisassembler.cpp.
Referenced by DecodeMQPRRegisterClass(), and DecodeQPRRegisterClass().
QQPRDecoderTable
const MCPhysReg QQPRDecoderTable[] static
Initial value:
                                        = {
     ARM::Q0_Q1,  ARM::Q1_Q2,  ARM::Q2_Q3,  ARM::Q3_Q4,
     ARM::Q4_Q5,  ARM::Q5_Q6,  ARM::Q6_Q7
}
Definition at line 567 of file ARMDisassembler.cpp.
Referenced by DecodeMQQPRRegisterClass().
QQQQPRDecoderTable
const MCPhysReg QQQQPRDecoderTable[] static
Initial value:
                                          = {
     ARM::Q0_Q1_Q2_Q3,  ARM::Q1_Q2_Q3_Q4,  ARM::Q2_Q3_Q4_Q5,
     ARM::Q3_Q4_Q5_Q6,  ARM::Q4_Q5_Q6_Q7
}
Definition at line 583 of file ARMDisassembler.cpp.
Referenced by DecodeMQQQQPRRegisterClass().
SPRDecoderTable
const MCPhysReg SPRDecoderTable[] static
Initial value:
                                       = {
     ARM::S0,  ARM::S1,  ARM::S2,  ARM::S3,
     ARM::S4,  ARM::S5,  ARM::S6,  ARM::S7,
     ARM::S8,  ARM::S9, ARM::S10, ARM::S11,
    ARM::S12, ARM::S13, ARM::S14, ARM::S15,
    ARM::S16, ARM::S17, ARM::S18, ARM::S19,
    ARM::S20, ARM::S21, ARM::S22, ARM::S23,
    ARM::S24, ARM::S25, ARM::S26, ARM::S27,
    ARM::S28, ARM::S29, ARM::S30, ARM::S31
}
Definition at line 412 of file ARMDisassembler.cpp.
Referenced by DecodeSPRRegisterClass().