LLVM: lib/Target/ARM/MCTargetDesc/ARMMCTargetDesc.cpp File Reference
ARMMCTargetDesc.cpp File Reference
#include "ARMMCTargetDesc.h"
#include "ARMAddressingModes.h"
#include "ARMBaseInfo.h"
#include "ARMInstPrinter.h"
#include "ARMMCAsmInfo.h"
#include "TargetInfo/ARMTargetInfo.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/TargetParser/Triple.h"
#include "ARMGenRegisterInfo.inc"
#include "ARMGenInstrInfo.inc"
#include "ARMGenSubtargetInfo.inc"
Macros
#define GET_REGINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
Functions
static bool getMCRDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static bool getMRCDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static bool getARMStoreDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static bool getARMLoadDeprecationInfo (MCInst &MI, const MCSubtargetInfo &STI, std::string &Info)
static MCInstrInfo * createARMMCInstrInfo ()
static MCRegisterInfo * createARMMCRegisterInfo (const Triple &Triple)
static MCAsmInfo * createARMMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TheTriple, const MCTargetOptions &Options)
static MCStreamer * createELFStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter)
static MCStreamer * createARMMachOStreamer (MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter)
static MCInstPrinter * createARMMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCRelocationInfo * createARMMCRelocationInfo (const Triple &TT, MCContext &Ctx)
static std::optional< uint64_t > evaluateMemOpAddrForAddrMode_i12 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static std::optional< uint64_t > evaluateMemOpAddrForAddrMode3 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static std::optional< uint64_t > evaluateMemOpAddrForAddrMode5 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static std::optional< uint64_t > evaluateMemOpAddrForAddrMode5FP16 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static std::optional< uint64_t > evaluateMemOpAddrForAddrModeT2_i8s4 (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static std::optional< uint64_t > evaluateMemOpAddrForAddrModeT2_pc (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
static std::optional< uint64_t > evaluateMemOpAddrForAddrModeT1_s (const MCInst &Inst, const MCInstrDesc &Desc, unsigned MemOpIndex, uint64_t Addr)
template<typename T, size_t N>
static bool instructionsMatch (const T(&Insns)[N], const uint8_t *Buf, llvm::endianness E)
static MCInstrAnalysis * createARMMCInstrAnalysis (const MCInstrInfo *Info)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 136 of file ARMMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 135 of file ARMMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 36 of file ARMMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 139 of file ARMMCTargetDesc.cpp.
Function Documentation
createARMMachOStreamer()
MCStreamer * createARMMachOStreamer (MCContext & Ctx, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter) static
Definition at line 365 of file ARMMCTargetDesc.cpp.
References llvm::createMachOStreamer(), and Emitter.
Referenced by LLVMInitializeARMTargetMC().
createARMMCAsmInfo()
MCAsmInfo * createARMMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TheTriple, const MCTargetOptions & Options) static
Definition at line 335 of file ARMMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSDarwin(), llvm::Triple::isOSWindows(), llvm::Triple::isWindowsMSVCEnvironment(), MRI, Options, and Reg.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstPrinter()
MCInstPrinter * createARMMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 372 of file ARMMCTargetDesc.cpp.
References MRI, and T.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstrAnalysis()
MCInstrAnalysis * createARMMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 755 of file ARMMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstrInfo()
MCInstrInfo * createARMMCInstrInfo () static
Definition at line 212 of file ARMMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeARMTargetMC().
createARMMCRegisterInfo()
MCRegisterInfo * createARMMCRegisterInfo (const Triple & Triple) static
Definition at line 328 of file ARMMCTargetDesc.cpp.
References llvm::ARM_MC::initLLVMToCVRegMapping(), and X.
Referenced by LLVMInitializeARMTargetMC().
createARMMCRelocationInfo()
MCRelocationInfo * createARMMCRelocationInfo (const Triple & TT, MCContext & Ctx) static
Definition at line 382 of file ARMMCTargetDesc.cpp.
References llvm::createARMMachORelocationInfo(), and llvm::createMCRelocationInfo().
Referenced by LLVMInitializeARMTargetMC().
createELFStreamer()
MCStreamer * createELFStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter) static
Definition at line 354 of file ARMMCTargetDesc.cpp.
References llvm::createARMELFStreamer(), Emitter, T, llvm::Triple::thumb, and llvm::Triple::thumbeb.
evaluateMemOpAddrForAddrMode3()
std::optional< uint64_t > evaluateMemOpAddrForAddrMode3 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 457 of file ARMMCTargetDesc.cpp.
References llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::ARM_AM::sub.
evaluateMemOpAddrForAddrMode5()
std::optional< uint64_t > evaluateMemOpAddrForAddrMode5 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 477 of file ARMMCTargetDesc.cpp.
References llvm::ARM_AM::getAM5Offset(), llvm::ARM_AM::getAM5Op(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::ARM_AM::sub.
evaluateMemOpAddrForAddrMode5FP16()
std::optional< uint64_t > evaluateMemOpAddrForAddrMode5FP16 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 496 of file ARMMCTargetDesc.cpp.
References llvm::ARM_AM::getAM5FP16Offset(), llvm::ARM_AM::getAM5FP16Op(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::ARM_AM::sub.
evaluateMemOpAddrForAddrMode_i12()
std::optional< uint64_t > evaluateMemOpAddrForAddrMode_i12 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 439 of file ARMMCTargetDesc.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), and llvm::MCOperand::isReg().
evaluateMemOpAddrForAddrModeT1_s()
std::optional< uint64_t > evaluateMemOpAddrForAddrModeT1_s (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 553 of file ARMMCTargetDesc.cpp.
References evaluateMemOpAddrForAddrModeT2_pc().
evaluateMemOpAddrForAddrModeT2_i8s4()
std::optional< uint64_t > evaluateMemOpAddrForAddrModeT2_i8s4 (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 516 of file ARMMCTargetDesc.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), and llvm::MCOperand::isReg().
evaluateMemOpAddrForAddrModeT2_pc()
std::optional< uint64_t > evaluateMemOpAddrForAddrModeT2_pc (const MCInst & Inst, const MCInstrDesc & Desc, unsigned MemOpIndex, uint64_t Addr) static
Definition at line 537 of file ARMMCTargetDesc.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm::MCOperand::isImm().
Referenced by evaluateMemOpAddrForAddrModeT1_s().
getARMLoadDeprecationInfo()
bool getARMLoadDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 106 of file ARMMCTargetDesc.cpp.
References assert(), llvm::MCSubtargetInfo::hasFeature(), Info, and MI.
getARMStoreDeprecationInfo()
bool getARMStoreDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 90 of file ARMMCTargetDesc.cpp.
References assert(), llvm::MCSubtargetInfo::hasFeature(), Info, and MI.
getMCRDeprecationInfo()
bool getMCRDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 39 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::hasFeature(), Info, and MI.
getMRCDeprecationInfo()
bool getMRCDeprecationInfo (MCInst & MI, const MCSubtargetInfo & STI, std::string & Info) static
Definition at line 78 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::hasFeature(), Info, and MI.
instructionsMatch()
template<typename T, size_t N> bool instructionsMatch (const T(&) Insns[N], const uint8_t * Buf, llvm::endianness E) static
Definition at line 624 of file ARMMCTargetDesc.cpp.
References E(), I, N, llvm::support::endian::read(), and T.
LLVMInitializeARMTargetMC()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMTargetMC ()
Definition at line 768 of file ARMMCTargetDesc.cpp.
References llvm::createARMBEAsmBackend(), llvm::createARMBEMCCodeEmitter(), llvm::createARMLEAsmBackend(), llvm::createARMLEMCCodeEmitter(), createARMMachOStreamer(), createARMMCAsmInfo(), createARMMCInstPrinter(), createARMMCInstrAnalysis(), createARMMCInstrInfo(), createARMMCRegisterInfo(), createARMMCRelocationInfo(), llvm::ARM_MC::createARMMCSubtargetInfo(), llvm::createARMNullTargetStreamer(), llvm::createARMObjectTargetStreamer(), llvm::createARMTargetAsmStreamer(), llvm::createARMWinCOFFStreamer(), llvm::createELFStreamer(), llvm::getTheARMBETarget(), llvm::getTheARMLETarget(), llvm::getTheThumbBETarget(), llvm::getTheThumbLETarget(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterCOFFStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMachOStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCRelocationInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), T, and X.