LLVM: lib/Target/ARM/ARMSelectionDAGInfo.cpp File Reference
ARMSelectionDAGInfo.cpp File Reference
#include "ARMSelectionDAGInfo.h"
#include "ARMTargetTransformInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/Support/CommandLine.h"
#include "ARMGenSDNodeInfo.inc"
Macros
#define GET_SDNODE_DESC
#define DEBUG_TYPE "arm-selectiondag-info"
#define MAKE_CASE(V)
Functions
static bool shouldGenerateInlineTPLoop (const ARMSubtarget &Subtarget, const SelectionDAG &DAG, ConstantSDNode *ConstantSize, Align Alignment, bool IsMemcpy)
Variables
static cl::opt< TPLoop::MemTransfer > EnableMemtransferTPLoop ("arm-memtransfer-tploop", cl::Hidden, cl::desc("Control conversion of memcpy to " "Tail predicated loops (WLSTP)"), cl::init(TPLoop::ForceDisabled), cl::values(clEnumValN(TPLoop::ForceDisabled, "force-disabled", "Don't convert memcpy to TP loop."), clEnumValN(TPLoop::ForceEnabled, "force-enabled", "Always convert memcpy to TP loop."), clEnumValN(TPLoop::Allow, "allow", "Allow (may be subject to certain conditions) " "conversion of memcpy to TP loop.")))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-selectiondag-info"
Definition at line 23 of file ARMSelectionDAGInfo.cpp.
GET_SDNODE_DESC
#define GET_SDNODE_DESC
Definition at line 18 of file ARMSelectionDAGInfo.cpp.
MAKE_CASE
#define MAKE_CASE (V)
Value:
case V:                                                                      \
  return #V;
Function Documentation
shouldGenerateInlineTPLoop()
bool shouldGenerateInlineTPLoop (const ARMSubtarget & Subtarget, const SelectionDAG & DAG, ConstantSDNode * ConstantSize, Align Alignment, bool IsMemcpy) static
Definition at line 225 of file ARMSelectionDAGInfo.cpp.
References EnableMemtransferTPLoop, F, llvm::TPLoop::ForceEnabled, llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::ARMSubtarget::getMaxInlineSizeThreshold(), llvm::ARMSubtarget::getMaxMemcpyTPInlineSizeThreshold(), and llvm::ConstantSDNode::getZExtValue().
Referenced by llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), and llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset().
Variable Documentation
EnableMemtransferTPLoop
cl::opt< TPLoop::MemTransfer > EnableMemtransferTPLoop("arm-memtransfer-tploop", cl::Hidden, cl::desc("Control conversion of memcpy to " "Tail predicated loops (WLSTP)"), cl::init(TPLoop::ForceDisabled), cl::values(clEnumValN(TPLoop::ForceDisabled, "force-disabled", "Don't convert memcpy to TP loop."), clEnumValN(TPLoop::ForceEnabled, "force-enabled", "Always convert memcpy to TP loop."), clEnumValN(TPLoop::Allow, "allow", "Allow (may be subject to certain conditions) " "conversion of memcpy to TP loop."))) ("arm-memtransfer-tploop" , cl::Hidden , cl::desc("Control conversion of memcpy to " "Tail predicated loops (WLSTP)") , cl::init(TPLoop::ForceDisabled) , cl::values(clEnumValN(TPLoop::ForceDisabled, "force-disabled", "Don't convert memcpy to TP loop."), clEnumValN(TPLoop::ForceEnabled, "force-enabled", "Always convert memcpy to TP loop."), clEnumValN(TPLoop::Allow, "allow", "Allow (may be subject to certain conditions) " "conversion of memcpy to TP loop."))) static
Referenced by shouldGenerateInlineTPLoop().