LLVM: lib/CodeGen/AsmPrinter/AsmPrinter.cpp File Reference
AsmPrinter.cpp File Reference
#include "llvm/CodeGen/AsmPrinter.h"
#include "CodeViewDebug.h"
#include "DwarfDebug.h"
#include "DwarfException.h"
#include "PseudoProbePrinter.h"
#include "WasmException.h"
#include "WinCFGuard.h"
#include "WinException.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/BasicBlockSectionsProfileReader.h"
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/GCMetadataPrinter.h"
#include "llvm/CodeGen/LazyMachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBlockHashInfo.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineOptimizationRemarkEmitter.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Config/config.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/EHPersonalities.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GCStrategy.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMRemarkStreamer.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PseudoProbe.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSchedule.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSectionXCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Object/ELFTypes.h"
#include "llvm/Pass.h"
#include "llvm/Remarks/RemarkStreamer.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VCSRevision.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/TargetParser/Triple.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <iterator>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>
Classes
class llvm::AddrLabelMap
Namespaces
namespace callgraph
Macros
#define DEBUG_TYPE "asm-printer"
Enumerations
enum class PGOMapFeaturesEnum {
None , FuncEntryCount , BBFreq , BrProb ,
PropellerCFG , All
}
enum callgraph::Flags : uint8_t { callgraph::None = 0 , callgraph::IsIndirectTarget = 1u << 0 , callgraph::HasDirectCallees = 1u << 1 , callgraph::HasIndirectCallees = 1u << 2 }
Functions
STATISTIC (EmittedInsts, "Number of machine instrs printed")
callgraph::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
static bool canBeHidden (const GlobalValue *GV, const MCAsmInfo &MAI)
static void emitComments (const MachineInstr &MI, const MCSubtargetInfo *STI, raw_ostream &CommentOS)
emitComments - Pretty-print comments for instructions.
static void emitKill (const MachineInstr *MI, AsmPrinter &AP)
static void emitFakeUse (const MachineInstr *MI, AsmPrinter &AP)
static bool emitDebugValueComment (const MachineInstr *MI, AsmPrinter &AP)
emitDebugValueComment - This method handles the target-independent form of DBG_VALUE, returning true if it was able to do so.
static bool emitDebugLabelComment (const MachineInstr *MI, AsmPrinter &AP)
This method handles the target-independent form of DBG_LABEL, returning true if it was able to do so.
static uint32_t getBBAddrMapMetadata (const MachineBasicBlock &MBB)
Returns the BB metadata to be emitted in the SHT_LLVM_BB_ADDR_MAP section for a given basic block.
static llvm::object::BBAddrMap::Features getBBAddrMapFeature (const MachineFunction &MF, int NumMBBSectionRanges, bool HasCalls, const CFGProfile *FuncCFGProfile)
static ConstantInt * extractNumericCGTypeId (const Function &F)
Extracts a generalized numeric type identifier of a Function's type from type metadata.
static bool needFuncLabels (const MachineFunction &MF, const AsmPrinter &Asm)
Returns true if function begin and end labels should be emitted.
static StringRef getMIMnemonic (const MachineInstr &MI, MCStreamer &Streamer)
static unsigned getNumGlobalVariableUses (const Constant *C, bool &HasNonGlobalUsers)
Compute the number of Global Variables that uses a Constant.
static bool isGOTEquivalentCandidate (const GlobalVariable *GV, unsigned &NumGOTEquivUsers, bool &HasNonGlobalUsers)
Only consider global GOT equivalents if at least one user is a cstexpr inside an initializer of another global variables.
static uint64_t globalSize (const llvm::GlobalVariable &G)
static bool shouldTagGlobal (const llvm::GlobalVariable &G)
static void tagGlobalDefinition (Module &M, GlobalVariable *G)
static void removeMemtagFromGlobal (GlobalVariable &G)
static void emitGlobalConstantImpl (const DataLayout &DL, const Constant *C, AsmPrinter &AP, const Constant *BaseCV=nullptr, uint64_t Offset=0, AsmPrinter::AliasMapTy *AliasList=nullptr)
static void emitGlobalConstantFP (const ConstantFP *CFP, AsmPrinter &AP)
static void emitGlobalConstantFP (APFloat APF, Type *ET, AsmPrinter &AP)
static int isRepeatedByteSequence (const ConstantDataSequential *V)
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
static int isRepeatedByteSequence (const Value *V, const DataLayout &DL)
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
static void emitGlobalAliasInline (AsmPrinter &AP, uint64_t Offset, AsmPrinter::AliasMapTy *AliasList)
static void emitGlobalConstantDataSequential (const DataLayout &DL, const ConstantDataSequential *CDS, AsmPrinter &AP, AsmPrinter::AliasMapTy *AliasList)
static void emitGlobalConstantArray (const DataLayout &DL, const ConstantArray *CA, AsmPrinter &AP, const Constant *BaseCV, uint64_t Offset, AsmPrinter::AliasMapTy *AliasList)
static void emitGlobalConstantLargeInt (const ConstantInt *CI, AsmPrinter &AP)
static void emitGlobalConstantVector (const DataLayout &DL, const Constant *CV, AsmPrinter &AP, AsmPrinter::AliasMapTy *AliasList)
static void emitGlobalConstantStruct (const DataLayout &DL, const ConstantStruct *CS, AsmPrinter &AP, const Constant *BaseCV, uint64_t Offset, AsmPrinter::AliasMapTy *AliasList)
static void handleIndirectSymViaGOTPCRel (AsmPrinter &AP, const MCExpr **ME, const Constant *BaseCst, uint64_t Offset)
Transform a not absolute MCExpr containing a reference to a GOT equivalent global, by a target specific GOT pc relative access to the final symbol.
static void PrintParentLoopComment (raw_ostream &OS, const MachineLoop *Loop, unsigned FunctionNumber)
PrintParentLoopComment - Print comments about parent loops of this one.
static void PrintChildLoopComment (raw_ostream &OS, const MachineLoop *Loop, unsigned FunctionNumber)
PrintChildLoopComment - Print comments about child loops within the loop for this basic block, with nesting.
static void emitBasicBlockLoopComments (const MachineBasicBlock &MBB, const MachineLoopInfo *LI, const AsmPrinter &AP)
emitBasicBlockLoopComments - Pretty-print comments for basic blocks.
Variables
static cl::bits< PGOMapFeaturesEnum > PgoAnalysisMapFeatures ("pgo-analysis-map", cl::Hidden, cl::CommaSeparated, cl::values(clEnumValN(PGOMapFeaturesEnum::None, "none", "Disable all options"), clEnumValN(PGOMapFeaturesEnum::FuncEntryCount, "func-entry-count", "Function Entry Count"), clEnumValN(PGOMapFeaturesEnum::BBFreq, "bb-freq", "Basic Block Frequency"), clEnumValN(PGOMapFeaturesEnum::BrProb, "br-prob", "Branch Probability"), clEnumValN(PGOMapFeaturesEnum::All, "all", "Enable all options")), cl::desc("Enable extended information within the SHT_LLVM_BB_ADDR_MAP that is " "extracted from PGO related analysis."))
static cl::opt< bool > PgoAnalysisMapEmitBBSectionsCfg ("pgo-analysis-map-emit-bb-sections-cfg", cl::desc("Enable the post-link cfg information from the basic block " "sections profile in the PGO analysis map"), cl::Hidden, cl::init(false))
static cl::opt< bool > BBAddrMapSkipEmitBBEntries ("basic-block-address-map-skip-bb-entries", cl::desc("Skip emitting basic block entries in the SHT_LLVM_BB_ADDR_MAP " "section. It's used to save binary size when BB entries are " "unnecessary for some PGOAnalysisMap features."), cl::Hidden, cl::init(false))
static cl::opt< bool > EmitJumpTableSizesSection ("emit-jump-table-sizes-section", cl::desc("Emit a section containing jump table addresses and sizes"), cl::Hidden, cl::init(false))
static cl::opt< bool > PrintLatency ("asm-print-latency", cl::desc("Print instruction latencies as verbose asm comments"), cl::Hidden, cl::init(false))
cl::opt< bool > EmitBBHash
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 142 of file AsmPrinter.cpp.
Enumeration Type Documentation
PGOMapFeaturesEnum
enum class PGOMapFeaturesEnum strong
Enumerator
None
FuncEntryCount
BBFreq
BrProb
PropellerCFG
All
Definition at line 148 of file AsmPrinter.cpp.
Function Documentation
canBeHidden()
bool canBeHidden (const GlobalValue * GV, const MCAsmInfo & MAI) static
Definition at line 679 of file AsmPrinter.cpp.
References llvm::GlobalValue::canBeOmittedFromSymbolTable(), and llvm::MCAsmInfo::hasWeakDefCanBeHiddenDirective().
Referenced by llvm::AsmPrinter::emitLinkage().
emitBasicBlockLoopComments()
void emitBasicBlockLoopComments (const MachineBasicBlock & MBB, const MachineLoopInfo * LI, const AsmPrinter & AP) static
emitBasicBlockLoopComments - Pretty-print comments for basic blocks.
Definition at line 4527 of file AsmPrinter.cpp.
References assert(), llvm::AsmPrinter::getFunctionNumber(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::BasicBlock::getNumber(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::raw_ostream::indent(), llvm::LoopBase< BlockT, LoopT >::isInnermost(), MBB, llvm::AsmPrinter::OutStreamer, PrintChildLoopComment(), and PrintParentLoopComment().
Referenced by llvm::AsmPrinter::emitBasicBlockStart().
emitComments()
void emitComments (const MachineInstr & MI, const MCSubtargetInfo * STI, raw_ostream & CommentOS) static
emitComments - Pretty-print comments for instructions.
Definition at line 1122 of file AsmPrinter.cpp.
References llvm::MCSchedModel::computeInstrLatency(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MCSubtargetInfo::getSchedModel(), llvm::MachineFunction::getSubtarget(), llvm::Latency, MI, PrintLatency, llvm::MachineInstr::ReloadReuse, Size, and TII.
Referenced by llvm::AsmPrinter::emitFunctionBody().
emitDebugLabelComment()
bool emitDebugLabelComment (const MachineInstr * MI, AsmPrinter & AP) static
This method handles the target-independent form of DBG_LABEL, returning true if it was able to do so.
A false return means the target will need to handle MI in EmitInstruction.
Definition at line 1316 of file AsmPrinter.cpp.
References llvm::dyn_cast(), MI, llvm::AsmPrinter::OutStreamer, and llvm::raw_svector_ostream::str().
Referenced by llvm::AsmPrinter::emitFunctionBody().
emitDebugValueComment()
bool emitDebugValueComment (const MachineInstr * MI, AsmPrinter & AP) static
emitDebugValueComment - This method handles the target-independent form of DBG_VALUE, returning true if it was able to do so.
A false return means the target will need to handle MI in EmitInstruction.
Definition at line 1209 of file AsmPrinter.cpp.
References llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::DIExpression::convertToNonVariadicExpression(), llvm::dyn_cast(), llvm::DIExpression::expr_ops(), llvm::StackOffset::getFixed(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::DIExpression::getNumElements(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::APFloatBase::IEEEdouble(), llvm::Type::isBFloatTy(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isHalfTy(), llvm_unreachable, llvm::AsmPrinter::MF, MI, llvm::MachineOperand::MO_CImmediate, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_FrameIndex, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_TargetIndex, llvm::Offset, llvm::dwarf::OperationEncodingString(), llvm::AsmPrinter::OutStreamer, llvm::printReg(), Reg, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by llvm::AsmPrinter::emitFunctionBody().
emitFakeUse()
void emitFakeUse (const MachineInstr * MI, AsmPrinter & AP) static
Definition at line 1191 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutStreamer, llvm::printReg(), and llvm::raw_string_ostream::str().
Referenced by llvm::AsmPrinter::emitFunctionBody().
emitGlobalAliasInline()
void emitGlobalAliasInline (AsmPrinter & AP, uint64_t Offset, AsmPrinter::AliasMapTy * AliasList) static
Definition at line 3935 of file AsmPrinter.cpp.
References llvm::AsmPrinter::getSymbol(), llvm::Offset, and llvm::AsmPrinter::OutStreamer.
Referenced by emitGlobalConstantDataSequential(), emitGlobalConstantImpl(), and emitGlobalConstantVector().
emitGlobalConstantArray()
void emitGlobalConstantArray (const DataLayout & DL, const ConstantArray * CA, AsmPrinter & AP, const Constant * BaseCV, uint64_t Offset, AsmPrinter::AliasMapTy * AliasList) static
Definition at line 3990 of file AsmPrinter.cpp.
References DL, E(), emitGlobalConstantImpl(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::ConstantArray::getType(), llvm::Value::getType(), I, isRepeatedByteSequence(), llvm::Offset, and llvm::AsmPrinter::OutStreamer.
Referenced by emitGlobalConstantImpl().
emitGlobalConstantDataSequential()
void emitGlobalConstantDataSequential (const DataLayout & DL, const ConstantDataSequential * CDS, AsmPrinter & AP, AsmPrinter::AliasMapTy * AliasList) static
Definition at line 3947 of file AsmPrinter.cpp.
References assert(), DL, E(), emitGlobalAliasInline(), emitGlobalConstantFP(), llvm::format(), llvm::ConstantDataSequential::getAsString(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::ConstantDataSequential::getElementAsInteger(), llvm::ConstantDataSequential::getElementByteSize(), llvm::ConstantDataSequential::getElementType(), llvm::ConstantDataSequential::getNumElements(), llvm::Value::getType(), I, llvm::isa(), isRepeatedByteSequence(), llvm::ConstantDataSequential::isString(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitGlobalConstantImpl().
emitGlobalConstantFP() [1/2]
void emitGlobalConstantFP (APFloat APF, Type * ET, AsmPrinter & AP) static
Definition at line 4081 of file AsmPrinter.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), DL, llvm::APInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::APInt::getNumWords(), llvm::APInt::getRawData(), llvm::DataLayout::isBigEndian(), llvm::Type::isPPC_FP128Ty(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::OutStreamer, llvm::Type::print(), and llvm::APFloat::toString().
emitGlobalConstantFP() [2/2]
void emitGlobalConstantFP (const ConstantFP * CFP, AsmPrinter & AP) static
Definition at line 4125 of file AsmPrinter.cpp.
References emitGlobalConstantFP(), llvm::Value::getType(), and llvm::ConstantFP::getValueAPF().
Referenced by emitGlobalConstantDataSequential(), emitGlobalConstantFP(), and emitGlobalConstantImpl().
emitGlobalConstantImpl()
void emitGlobalConstantImpl (const DataLayout & DL, const Constant * C, AsmPrinter & AP, const Constant * BaseCV = nullptr, uint64_t Offset = 0, AsmPrinter::AliasMapTy * AliasList = nullptr) static
Definition at line 4272 of file AsmPrinter.cpp.
References assert(), llvm::ConstantFoldConstant(), DL, llvm::dyn_cast(), emitGlobalAliasInline(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::format(), llvm::StructLayout::getElementOffset(), llvm::StructType::getNumElements(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetMachine::getTargetTriple(), llvm::Value::getType(), handleIndirectSymViaGOTPCRel(), llvm::Value::hasOneUse(), llvm::isa(), llvm::Triple::isOSBinFormatXCOFF(), llvm::AsmPrinter::isVerbose(), llvm::AsmPrinter::lowerConstant(), llvm::Offset, llvm::AsmPrinter::OutStreamer, Size, llvm::TargetLoweringObjectFile::supportIndirectSymViaGOTPCRel(), llvm::AsmPrinter::TM, and llvm::Value::user_back().
Referenced by llvm::AsmPrinter::emitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantImpl(), emitGlobalConstantStruct(), and emitGlobalConstantVector().
emitGlobalConstantLargeInt()
void emitGlobalConstantLargeInt (const ConstantInt * CI, AsmPrinter & AP) static
Definition at line 4129 of file AsmPrinter.cpp.
References llvm::alignTo(), assert(), llvm::BitWidth, DL, llvm::ConstantInt::getBitWidth(), llvm::AsmPrinter::getDataLayout(), llvm::APInt::getRawData(), llvm::Value::getType(), llvm::DataLayout::getTypeStoreSize(), llvm::ConstantInt::getValue(), llvm::APInt::lshrInPlace(), llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitGlobalConstantImpl(), and emitGlobalConstantVector().
emitGlobalConstantStruct()
void emitGlobalConstantStruct (const DataLayout & DL, const ConstantStruct * CS, AsmPrinter & AP, const Constant * BaseCV, uint64_t Offset, AsmPrinter::AliasMapTy * AliasList) static
Definition at line 4050 of file AsmPrinter.cpp.
References assert(), DL, E(), emitGlobalConstantImpl(), llvm::StructLayout::getElementOffset(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::StructLayout::getSizeInBytes(), llvm::ConstantStruct::getType(), I, llvm::Offset, llvm::AsmPrinter::OutStreamer, and Size.
Referenced by emitGlobalConstantImpl().
emitGlobalConstantVector()
void emitGlobalConstantVector (const DataLayout & DL, const Constant * CV, AsmPrinter & AP, AsmPrinter::AliasMapTy * AliasList) static
Definition at line 4012 of file AsmPrinter.cpp.
References llvm::cast(), llvm::ConstantFoldConstant(), DL, llvm::dyn_cast_or_null(), E(), emitGlobalAliasInline(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), llvm::IntegerType::get(), llvm::Constant::getAggregateElement(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::Value::getType(), I, llvm::AsmPrinter::OutStreamer, llvm::report_fatal_error(), and Size.
Referenced by emitGlobalConstantImpl().
emitKill()
void emitKill (const MachineInstr * MI, AsmPrinter & AP) static
Definition at line 1178 of file AsmPrinter.cpp.
References assert(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::AsmPrinter::MF, MI, llvm::AsmPrinter::OutStreamer, and llvm::printReg().
Referenced by llvm::AsmPrinter::emitFunctionBody().
extractNumericCGTypeId()
ConstantInt * extractNumericCGTypeId (const Function & F) static
Extracts a generalized numeric type identifier of a Function's type from type metadata.
Returns null if metadata cannot be found.
Definition at line 1709 of file AsmPrinter.cpp.
References llvm::cast(), F, llvm::Type::getInt64Ty(), llvm::MDString::getString(), and llvm::sampleprof::MD5Hash().
Referenced by llvm::AsmPrinter::emitCallGraphSection().
getBBAddrMapFeature()
llvm::object::BBAddrMap::Features getBBAddrMapFeature (const MachineFunction & MF, int NumMBBSectionRanges, bool HasCalls, const CFGProfile * FuncCFGProfile) static
Definition at line 1419 of file AsmPrinter.cpp.
References All, AllFeatures, BBAddrMapSkipEmitBBEntries, BBFreq, BrProb, EmitBBHash, llvm::LLVMContext::emitError(), FuncEntryCount, llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::hasBBSections(), HasCalls, None, PgoAnalysisMapEmitBBSectionsCfg, PgoAnalysisMapFeatures, and llvm::popcount().
Referenced by llvm::AsmPrinter::emitBBAddrMapSection().
getBBAddrMapMetadata()
uint32_t getBBAddrMapMetadata (const MachineBasicBlock & MBB) static
Returns the BB metadata to be emitted in the SHT_LLVM_BB_ADDR_MAP section for a given basic block.
This can be used to capture more precise profile information.
Definition at line 1409 of file AsmPrinter.cpp.
References llvm::object::BBAddrMap::BBEntry::Metadata::encode(), MBB, and TII.
Referenced by llvm::AsmPrinter::emitBBAddrMapSection().
getMIMnemonic()
StringRef getMIMnemonic (const MachineInstr & MI, MCStreamer & Streamer) static
Definition at line 1915 of file AsmPrinter.cpp.
References assert(), llvm::MCStreamer::getMnemonic(), MI, llvm::MCInst::setOpcode(), and TII.
Referenced by llvm::AsmPrinter::emitFunctionBody().
getNumGlobalVariableUses()
unsigned getNumGlobalVariableUses (const Constant * C, bool & HasNonGlobalUsers) static
Compute the number of Global Variables that uses a Constant.
Definition at line 2386 of file AsmPrinter.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), getNumGlobalVariableUses(), and llvm::isa().
Referenced by getNumGlobalVariableUses(), and isGOTEquivalentCandidate().
globalSize()
uint64_t globalSize (const llvm::GlobalVariable & G) static
Definition at line 2661 of file AsmPrinter.cpp.
References G, and llvm::Value::getType().
Referenced by shouldTagGlobal(), and tagGlobalDefinition().
handleIndirectSymViaGOTPCRel()
void handleIndirectSymViaGOTPCRel (AsmPrinter & AP, const MCExpr ** ME, const Constant * BaseCst, uint64_t Offset) static
Transform a not absolute MCExpr containing a reference to a GOT equivalent global, by a target specific GOT pc relative access to the final symbol.
Definition at line 4190 of file AsmPrinter.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::MCValue::getAddSym(), llvm::MCValue::getConstant(), llvm::TargetLoweringObjectFile::getIndirectSymViaGOTPCRel(), llvm::AsmPrinter::getObjFileLowering(), llvm::User::getOperand(), llvm::MCValue::getSubSym(), llvm::AsmPrinter::getSymbol(), llvm::AsmPrinter::GlobalGOTEquivs, llvm::MCValue::isAbsolute(), llvm::AsmPrinter::MMI, llvm::Offset, llvm::AsmPrinter::OutStreamer, and llvm::TargetLoweringObjectFile::supportGOTPCRelWithOffset().
Referenced by emitGlobalConstantImpl().
isGOTEquivalentCandidate()
bool isGOTEquivalentCandidate (const GlobalVariable * GV, unsigned & NumGOTEquivUsers, bool & HasNonGlobalUsers) static
Only consider global GOT equivalents if at least one user is a cstexpr inside an initializer of another global variables.
Also, don't handle cstexpr inside instructions. During global variable emission, candidates are skipped and are emitted later in case at least one cstexpr isn't replaced by a PC relative GOT entry access.
Definition at line 2409 of file AsmPrinter.cpp.
References llvm::dyn_cast(), getNumGlobalVariableUses(), llvm::User::getOperand(), llvm::GlobalValue::hasGlobalUnnamedAddr(), llvm::GlobalVariable::hasInitializer(), llvm::isa(), llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDiscardableIfUnused(), and llvm::Value::users().
Referenced by llvm::AsmPrinter::computeGlobalGOTEquivs().
isRepeatedByteSequence() [1/2]
int isRepeatedByteSequence (const ConstantDataSequential * V) static
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
If it is not a repeated sequence, return -1.
Definition at line 3889 of file AsmPrinter.cpp.
References assert(), llvm::CallingConv::C, and llvm::Data.
Referenced by emitGlobalConstantArray(), emitGlobalConstantDataSequential(), and isRepeatedByteSequence().
isRepeatedByteSequence() [2/2]
int isRepeatedByteSequence (const Value * V, const DataLayout & DL) static
isRepeatedByteSequence - Determine whether the given value is composed of a repeated sequence of identical bytes and return the byte value.
If it is not a repeated sequence, return -1.
Definition at line 3901 of file AsmPrinter.cpp.
References assert(), DL, llvm::dyn_cast(), isRepeatedByteSequence(), Op0, and Size.
needFuncLabels()
bool needFuncLabels (const MachineFunction & MF, const AsmPrinter & Asm) static
Returns true if function begin and end labels should be emitted.
Definition at line 1899 of file AsmPrinter.cpp.
References llvm::classifyEHPersonality(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getLandingPads(), llvm::Function::getPersonalityFn(), llvm::MachineFunction::hasEHFunclets(), llvm::GlobalObject::hasMetadata(), llvm::Function::hasPersonalityFn(), and llvm::isNoOpWithoutInvoke().
Referenced by llvm::AsmPrinter::emitFunctionBody(), and llvm::AsmPrinter::SetupMachineFunction().
PrintChildLoopComment()
void PrintChildLoopComment (raw_ostream & OS, const MachineLoop * Loop, unsigned FunctionNumber) static
PrintChildLoopComment - Print comments about child loops within the loop for this basic block, with nesting.
Definition at line 4514 of file AsmPrinter.cpp.
References llvm::raw_ostream::indent(), and PrintChildLoopComment().
Referenced by emitBasicBlockLoopComments(), and PrintChildLoopComment().
PrintParentLoopComment()
void PrintParentLoopComment (raw_ostream & OS, const MachineLoop * Loop, unsigned FunctionNumber) static
PrintParentLoopComment - Print comments about parent loops of this one.
Definition at line 4502 of file AsmPrinter.cpp.
References llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::BasicBlock::getNumber(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::raw_ostream::indent(), and PrintParentLoopComment().
Referenced by emitBasicBlockLoopComments(), and PrintParentLoopComment().
removeMemtagFromGlobal()
void removeMemtagFromGlobal (GlobalVariable & G) static
Definition at line 2733 of file AsmPrinter.cpp.
References G.
Referenced by llvm::AsmPrinter::doFinalization().
shouldTagGlobal()
bool shouldTagGlobal (const llvm::GlobalVariable & G) static
Definition at line 2667 of file AsmPrinter.cpp.
References G, and globalSize().
Referenced by llvm::AsmPrinter::doFinalization().
STATISTIC()
STATISTIC (EmittedInsts , "Number of machine instrs printed")
tagGlobalDefinition()
void tagGlobalDefinition (Module & M, GlobalVariable * G) static
Definition at line 2702 of file AsmPrinter.cpp.
References llvm::alignTo(), G, llvm::ConstantDataArray::get(), llvm::ConstantStruct::getAnon(), llvm::Value::getType(), globalSize(), and llvm::GlobalValue::None.
Referenced by llvm::AsmPrinter::doFinalization().
Variable Documentation
BBAddrMapSkipEmitBBEntries
cl::opt< bool > BBAddrMapSkipEmitBBEntries("basic-block-address-map-skip-bb-entries", cl::desc("Skip emitting basic block entries in the SHT_LLVM_BB_ADDR_MAP " "section. It's used to save binary size when BB entries are " "unnecessary for some PGOAnalysisMap features."), cl::Hidden, cl::init(false)) ("basic-block-address-map-skip-bb-entries" , cl::desc("Skip emitting basic block entries in the SHT_LLVM_BB_ADDR_MAP " "section. It's used to save binary size when BB entries are " "unnecessary for some PGOAnalysisMap features.") , cl::Hidden , cl::init(false)) static
Referenced by getBBAddrMapFeature().
EmitBBHash
cl::opt<bool> EmitBBHash extern
Referenced by llvm::TargetPassConfig::addMachinePasses(), llvm::AsmPrinter::getAnalysisUsage(), and getBBAddrMapFeature().
EmitJumpTableSizesSection
cl::opt< bool > EmitJumpTableSizesSection("emit-jump-table-sizes-section", cl::desc("Emit a section containing jump table addresses and sizes"), cl::Hidden, cl::init(false)) ("emit-jump-table-sizes-section" , cl::desc("Emit a section containing jump table addresses and sizes") , cl::Hidden , cl::init(false)) static
PgoAnalysisMapEmitBBSectionsCfg
cl::opt< bool > PgoAnalysisMapEmitBBSectionsCfg("pgo-analysis-map-emit-bb-sections-cfg", cl::desc("Enable the post-link cfg information from the basic block " "sections profile in the PGO analysis map"), cl::Hidden, cl::init(false)) ("pgo-analysis-map-emit-bb-sections-cfg" , cl::desc("Enable the post-link cfg information from the basic block " "sections profile in the PGO analysis map") , cl::Hidden , cl::init(false)) static
Referenced by getBBAddrMapFeature().
PgoAnalysisMapFeatures
cl::bits< PGOMapFeaturesEnum > PgoAnalysisMapFeatures("pgo-analysis-map", cl::Hidden, cl::CommaSeparated, cl::values(clEnumValN(PGOMapFeaturesEnum::None, "none", "Disable all options"), clEnumValN(PGOMapFeaturesEnum::FuncEntryCount, "func-entry-count", "Function Entry Count"), clEnumValN(PGOMapFeaturesEnum::BBFreq, "bb-freq", "Basic Block Frequency"), clEnumValN(PGOMapFeaturesEnum::BrProb, "br-prob", "Branch Probability"), clEnumValN(PGOMapFeaturesEnum::All, "all", "Enable all options")), cl::desc("Enable extended information within the SHT_LLVM_BB_ADDR_MAP that is " "extracted from PGO related analysis.")) ("pgo-analysis-map" , cl::Hidden , cl::CommaSeparated , cl::values(clEnumValN(PGOMapFeaturesEnum::None, "none", "Disable all options"), clEnumValN(PGOMapFeaturesEnum::FuncEntryCount, "func-entry-count", "Function Entry Count"), clEnumValN(PGOMapFeaturesEnum::BBFreq, "bb-freq", "Basic Block Frequency"), clEnumValN(PGOMapFeaturesEnum::BrProb, "br-prob", "Branch Probability"), clEnumValN(PGOMapFeaturesEnum::All, "all", "Enable all options")) , cl::desc("Enable extended information within the SHT_LLVM_BB_ADDR_MAP that is " "extracted from PGO related analysis.")) static
Referenced by llvm::AsmPrinter::emitFunctionBody(), and getBBAddrMapFeature().
PrintLatency
cl::opt< bool > PrintLatency("asm-print-latency", cl::desc("Print instruction latencies as verbose asm comments"), cl::Hidden, cl::init(false)) ("asm-print-latency" , cl::desc("Print instruction latencies as verbose asm comments") , cl::Hidden , cl::init(false)) static
Referenced by emitComments().