LLVM: lib/IR/Assumptions.cpp File Reference
Assumptions.cpp File Reference
#include "llvm/IR/Assumptions.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
Functions
static bool hasAssumption (const Attribute &A, const KnownAssumptionString &AssumptionStr)
static DenseSet< StringRef > getAssumptions (const Attribute &A)
template<typename AttrSite>
static bool addAssumptionsImpl (AttrSite &Site, const DenseSet< StringRef > &Assumptions)
Function Documentation
addAssumptionsImpl()
template<typename AttrSite> bool addAssumptionsImpl (AttrSite & Site, const DenseSet< StringRef > & Assumptions) static
Definition at line 49 of file Assumptions.cpp.
References llvm::AssumptionAttrKey, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), llvm::Attribute::get(), llvm::getAssumptions(), and llvm::set_union().
getAssumptions()
DenseSet< StringRef > getAssumptions (const Attribute & A) static
Definition at line 35 of file Assumptions.cpp.
References A(), assert(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert_range().
hasAssumption()
bool hasAssumption (const Attribute & A, const KnownAssumptionString & AssumptionStr) static
Definition at line 23 of file Assumptions.cpp.
References A(), assert(), and llvm::is_contained().