LLVM: lib/IR/AutoUpgrade.cpp File Reference
AutoUpgrade.cpp File Reference
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/AttributeMask.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/IntrinsicsRISCV.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/AMDGPUAddrSpace.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/NVPTXAddrSpace.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/TimeProfiler.h"
#include "llvm/TargetParser/Triple.h"
#include <cstdint>
#include <cstring>
#include <numeric>
Functions
static void rename (GlobalValue *GV)
static bool upgradePTESTIntrinsic (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool upgradeX86IntrinsicsWith8BitMask (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool upgradeX86MaskedFPCompare (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool upgradeX86MultiplyAddBytes (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool upgradeX86MultiplyAddWords (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool upgradeX86BF16Intrinsic (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool upgradeX86BF16DPIntrinsic (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool shouldUpgradeX86Intrinsic (Function *F, StringRef Name)
static bool upgradeX86IntrinsicFunction (Function *F, StringRef Name, Function *&NewFn)
static bool upgradeArmOrAarch64IntrinsicFunction (bool IsArm, Function *F, StringRef Name, Function *&NewFn)
static Intrinsic::ID shouldUpgradeNVPTXTMAG2SIntrinsics (Function *F, StringRef Name)
static Intrinsic::ID shouldUpgradeNVPTXSharedClusterIntrinsic (Function *F, StringRef Name)
static Intrinsic::ID shouldUpgradeNVPTXBF16Intrinsic (StringRef Name)
static bool consumeNVVMPtrAddrSpace (StringRef &Name)
static bool upgradeIntrinsicFunction1 (Function *F, Function *&NewFn, bool CanUpgradeDebugIntrinsicsToRecords)
static Value * upgradeX86PSLLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * upgradeX86PSRLDQIntrinsics (IRBuilder<> &Builder, Value *Op, unsigned Shift)
static Value * getX86MaskVec (IRBuilder<> &Builder, Value *Mask, unsigned NumElts)
static Value * emitX86Select (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * emitX86ScalarSelect (IRBuilder<> &Builder, Value *Mask, Value *Op0, Value *Op1)
static Value * upgradeX86ALIGNIntrinsics (IRBuilder<> &Builder, Value *Op0, Value *Op1, Value *Shift, Value *Passthru, Value *Mask, bool IsVALIGN)
static Value * upgradeX86VPERMT2Intrinsics (IRBuilder<> &Builder, CallBase &CI, bool ZeroMask, bool IndexForm)
static Value * upgradeX86BinaryIntrinsics (IRBuilder<> &Builder, CallBase &CI, Intrinsic::ID IID)
static Value * upgradeX86Rotate (IRBuilder<> &Builder, CallBase &CI, bool IsRotateRight)
static Value * upgradeX86vpcom (IRBuilder<> &Builder, CallBase &CI, unsigned Imm, bool IsSigned)
static Value * upgradeX86ConcatShift (IRBuilder<> &Builder, CallBase &CI, bool IsShiftRight, bool ZeroMask)
static Value * upgradeMaskedStore (IRBuilder<> &Builder, Value *Ptr, Value *Data, Value *Mask, bool Aligned)
static Value * upgradeMaskedLoad (IRBuilder<> &Builder, Value *Ptr, Value *Passthru, Value *Mask, bool Aligned)
static Value * upgradeAbs (IRBuilder<> &Builder, CallBase &CI)
static Value * upgradePMULDQ (IRBuilder<> &Builder, CallBase &CI, bool IsSigned)
static Value * applyX86MaskOn1BitsVec (IRBuilder<> &Builder, Value *Vec, Value *Mask)
static Value * upgradeMaskedCompare (IRBuilder<> &Builder, CallBase &CI, unsigned CC, bool Signed)
static Value * upgradeX86MaskedShift (IRBuilder<> &Builder, CallBase &CI, Intrinsic::ID IID)
static Value * upgradeMaskedMove (IRBuilder<> &Builder, CallBase &CI)
static Value * upgradeMaskToInt (IRBuilder<> &Builder, CallBase &CI)
static bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> &Builder, CallBase &CI, Value *&Rep)
static Value * upgradeNVVMIntrinsicCall (StringRef Name, CallBase *CI, Function *F, IRBuilder<> &Builder)
static Value * upgradeX86IntrinsicCall (StringRef Name, CallBase *CI, Function *F, IRBuilder<> &Builder)
static Value * upgradeAArch64IntrinsicCall (StringRef Name, CallBase *CI, Function *F, IRBuilder<> &Builder)
static Value * upgradeARMIntrinsicCall (StringRef Name, CallBase *CI, Function *F, IRBuilder<> &Builder)
static Value * upgradeAMDGCNIntrinsicCall (StringRef Name, CallBase *CI, Function *F, IRBuilder<> &Builder)
static MDNode * unwrapMAVOp (CallBase *CI, unsigned Op)
Helper to unwrap intrinsic call MetadataAsValue operands.
static Metadata * unwrapMAVMetadataOp (CallBase *CI, unsigned Op)
Helper to unwrap Metadata MetadataAsValue operands, such as the Value field.
static MDNode * getDebugLocSafe (const Instruction *I)
static void upgradeDbgIntrinsicToDbgRecord (StringRef Name, CallBase *CI)
Convert debug intrinsic calls to non-instruction debug records.
static Value * upgradeVectorSplice (CallBase *CI, IRBuilder<> &Builder)
static void upgradeNVVMFnVectorAttr (const StringRef Attr, const char DimC, GlobalValue *GV, const Metadata *V)
static bool isXYZ (StringRef S)
static bool upgradeSingleNVVMAnnotation (GlobalValue *GV, StringRef K, const Metadata *V)
static bool upgradeRetainReleaseMarker (Module &M)
This checks for objc retain release marker which should be upgraded.
static void setFunctionAttrIfNotSet (Function &F, StringRef FnAttrName, StringRef Value)
static void ConvertFunctionAttr (Function &F, bool Set, StringRef FnAttrName)
static bool isOldLoopArgument (Metadata *MD)
static MDString * upgradeLoopTag (LLVMContext &C, StringRef OldTag)
static Metadata * upgradeLoopArgument (Metadata *MD)
Variables
static cl::opt< bool > DisableAutoUpgradeDebugInfo ("disable-auto-upgrade-debug-info", cl::desc("Disable autoupgrade of debug info"))
Function Documentation
applyX86MaskOn1BitsVec()
Value * applyX86MaskOn1BitsVec (IRBuilder<> & Builder, Value * Vec, Value * Mask) static
Definition at line 2309 of file AutoUpgrade.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::Constant::getNullValue(), llvm::Value::getType(), and getX86MaskVec().
Referenced by llvm::UpgradeIntrinsicCall(), upgradeMaskedCompare(), and upgradeX86IntrinsicCall().
consumeNVVMPtrAddrSpace()
bool consumeNVVMPtrAddrSpace (StringRef & Name) static
Definition at line 1243 of file AutoUpgrade.cpp.
Referenced by upgradeIntrinsicFunction1(), and upgradeNVVMIntrinsicCall().
ConvertFunctionAttr()
void ConvertFunctionAttr (Function & F, bool Set, StringRef FnAttrName) static
Definition at line 6311 of file AutoUpgrade.cpp.
References A(), and F.
Referenced by llvm::copyModuleAttrToFunctions().
emitX86ScalarSelect()
Value * emitX86ScalarSelect (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 1995 of file AutoUpgrade.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::FixedVectorType::get(), and Op0.
Referenced by upgradeX86IntrinsicCall().
emitX86Select()
Value * emitX86Select (IRBuilder<> & Builder, Value * Mask, Value * Op0, Value * Op1) static
Definition at line 1983 of file AutoUpgrade.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), getX86MaskVec(), and Op0.
Referenced by upgradeAbs(), upgradeAVX512MaskToSelect(), upgradePMULDQ(), upgradeX86ALIGNIntrinsics(), upgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), upgradeX86IntrinsicCall(), upgradeX86MaskedShift(), upgradeX86Rotate(), and upgradeX86VPERMT2Intrinsics().
getDebugLocSafe()
MDNode * getDebugLocSafe (const Instruction * I) static
Definition at line 4783 of file AutoUpgrade.cpp.
References I.
Referenced by upgradeDbgIntrinsicToDbgRecord().
getX86MaskVec()
Value * getX86MaskVec (IRBuilder<> & Builder, Value * Mask, unsigned NumElts) static
Definition at line 1963 of file AutoUpgrade.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), llvm::FixedVectorType::get(), and llvm::isPowerOf2_32().
Referenced by applyX86MaskOn1BitsVec(), emitX86Select(), llvm::UpgradeIntrinsicCall(), upgradeMaskedLoad(), upgradeMaskedStore(), upgradeMaskToInt(), and upgradeX86IntrinsicCall().
isOldLoopArgument()
bool isOldLoopArgument (Metadata * MD) static
Definition at line 6415 of file AutoUpgrade.cpp.
References llvm::dyn_cast_or_null(), and T.
Referenced by llvm::upgradeInstructionLoopAttachment().
isXYZ()
bool isXYZ (StringRef S) inline static
Definition at line 5791 of file AutoUpgrade.cpp.
Referenced by upgradeSingleNVVMAnnotation().
rename()
void rename (GlobalValue * GV) static
Definition at line 64 of file AutoUpgrade.cpp.
References llvm::Value::getName(), and llvm::Value::setName().
Referenced by upgradeArmOrAarch64IntrinsicFunction(), upgradeIntrinsicFunction1(), upgradeNVVMIntrinsicCall(), upgradePTESTIntrinsic(), upgradeX86BF16DPIntrinsic(), upgradeX86BF16Intrinsic(), upgradeX86IntrinsicFunction(), upgradeX86IntrinsicsWith8BitMask(), upgradeX86MaskedFPCompare(), upgradeX86MultiplyAddBytes(), and upgradeX86MultiplyAddWords().
setFunctionAttrIfNotSet()
void setFunctionAttrIfNotSet (Function & F, StringRef FnAttrName, StringRef Value) static
Definition at line 6302 of file AutoUpgrade.cpp.
References F.
Referenced by llvm::copyModuleAttrToFunctions().
shouldUpgradeNVPTXBF16Intrinsic()
Intrinsic::ID shouldUpgradeNVPTXBF16Intrinsic (StringRef Name) static
Definition at line 1169 of file AutoUpgrade.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and llvm::Intrinsic::not_intrinsic.
Referenced by upgradeIntrinsicFunction1(), and upgradeNVVMIntrinsicCall().
shouldUpgradeNVPTXSharedClusterIntrinsic()
Intrinsic::ID shouldUpgradeNVPTXSharedClusterIntrinsic (Function * F, StringRef Name) static
Definition at line 1144 of file AutoUpgrade.cpp.
References llvm::NVPTXAS::ADDRESS_SPACE_SHARED, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), F, and llvm::Intrinsic::not_intrinsic.
Referenced by upgradeIntrinsicFunction1().
shouldUpgradeNVPTXTMAG2SIntrinsics()
Intrinsic::ID shouldUpgradeNVPTXTMAG2SIntrinsics (Function * F, StringRef Name) static
Definition at line 1097 of file AutoUpgrade.cpp.
References llvm::NVPTXAS::ADDRESS_SPACE_SHARED, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), F, llvm::Type::isIntegerTy(), and llvm::Intrinsic::not_intrinsic.
Referenced by upgradeIntrinsicFunction1().
shouldUpgradeX86Intrinsic()
bool shouldUpgradeX86Intrinsic (Function * F, StringRef Name) static
Definition at line 167 of file AutoUpgrade.cpp.
References F.
Referenced by upgradeX86IntrinsicFunction().
unwrapMAVMetadataOp()
Metadata * unwrapMAVMetadataOp (CallBase * CI, unsigned Op) static
Helper to unwrap Metadata MetadataAsValue operands, such as the Value field.
Definition at line 4776 of file AutoUpgrade.cpp.
References llvm::dyn_cast(), and llvm::CallBase::getArgOperand().
Referenced by upgradeDbgIntrinsicToDbgRecord().
unwrapMAVOp()
MDNode * unwrapMAVOp (CallBase * CI, unsigned Op) static
Helper to unwrap intrinsic call MetadataAsValue operands.
Return as a plain MDNode, as it's the verifier's job to check these are the correct types later.
Definition at line 4764 of file AutoUpgrade.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_if_present(), and llvm::CallBase::getArgOperand().
Referenced by upgradeDbgIntrinsicToDbgRecord().
upgradeAArch64IntrinsicCall()
Value * upgradeAArch64IntrinsicCall (StringRef Name, CallBase * CI, Function * F, IRBuilder<> & Builder) static
Definition at line 4478 of file AutoUpgrade.cpp.
References llvm::CallBase::args(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringSwitch< T, R >::Case(), llvm::dbgs(), llvm::StringSwitch< T, R >::Default(), llvm::SmallVectorTemplateCommon< T, typename >::end(), F, llvm::ConstantAggregateZero::get(), llvm::FixedVectorType::get(), llvm::ScalableVectorType::get(), llvm::Type::getBFloatTy(), llvm::Value::getName(), llvm::User::getOperand(), getType(), llvm::Value::getType(), llvm_unreachable, and llvm::Intrinsic::not_intrinsic.
Referenced by llvm::UpgradeIntrinsicCall().
upgradeAbs()
Value * upgradeAbs (IRBuilder<> & Builder, CallBase & CI) static
Definition at line 2269 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), emitX86Select(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), and Op0.
Referenced by upgradeX86IntrinsicCall().
upgradeAMDGCNIntrinsicCall()
Value * upgradeAMDGCNIntrinsicCall (StringRef Name, CallBase * CI, Function * F, IRBuilder<> & Builder) static
Definition at line 4625 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), llvm::CallBase::args(), assert(), llvm::cast(), llvm::MDBuilder::createRange(), llvm::dyn_cast(), F, llvm::AtomicRMWInst::FAdd, llvm::AMDGPUAS::FLAT_ADDRESS, llvm::AtomicRMWInst::FMax, llvm::AtomicRMWInst::FMin, llvm::MDNode::get(), llvm::VectorType::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getAttributes(), llvm::Type::getBFloatTy(), llvm::CallBase::getCallingConv(), llvm::Instruction::getDebugLoc(), llvm::User::getNumOperands(), llvm::CallBase::getOperandBundlesAsDefs(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::Type::isFloatTy(), llvm::isValidAtomicOrdering(), llvm::ConstantInt::isZero(), llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::NotAtomic, llvm::AMDGPUAS::PRIVATE_ADDRESS, llvm::SequentiallyConsistent, llvm::Instruction::setMetadata(), llvm::AtomicRMWInst::setVolatile(), llvm::StringSwitch< T, R >::StartsWith(), T1, llvm::AtomicRMWInst::UDecWrap, llvm::AtomicRMWInst::UIncWrap, llvm::Unordered, llvm::AtomicRMWInst::USubCond, and llvm::AtomicRMWInst::USubSat.
Referenced by llvm::UpgradeIntrinsicCall().
upgradeARMIntrinsicCall()
Value * upgradeARMIntrinsicCall (StringRef Name, CallBase * CI, Function * F, IRBuilder<> & Builder) static
Definition at line 4535 of file AutoUpgrade.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::CallBase::args(), F, llvm::FixedVectorType::get(), llvm::VectorType::get(), llvm::CallBase::getArgOperand(), llvm::CallBase::getIntrinsicID(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Value::getType(), and llvm_unreachable.
Referenced by llvm::UpgradeIntrinsicCall().
upgradeArmOrAarch64IntrinsicFunction()
bool upgradeArmOrAarch64IntrinsicFunction (bool IsArm, Function * F, StringRef Name, Function *& NewFn) static
Definition at line 772 of file AutoUpgrade.cpp.
References assert(), llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), llvm::cast(), Default, llvm::StringSwitch< T, R >::Default(), llvm::dyn_cast(), F, llvm::FixedVectorType::get(), llvm::VectorType::get(), llvm::Type::getBFloatTy(), llvm::Intrinsic::getOrInsertDeclaration(), Groups, llvm::Regex::match(), llvm::Intrinsic::not_intrinsic, rename(), llvm::size(), and llvm::StringSwitch< T, R >::StartsWith().
Referenced by upgradeIntrinsicFunction1().
upgradeAVX512MaskToSelect()
bool upgradeAVX512MaskToSelect (StringRef Name, IRBuilder<> & Builder, CallBase & CI, Value *& Rep) static
Definition at line 2393 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), llvm::CallBase::args(), emitX86Select(), llvm::CallBase::getArgOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::isFPOrFPVectorTy(), and llvm_unreachable.
Referenced by upgradeX86IntrinsicCall().
upgradeDbgIntrinsicToDbgRecord()
void upgradeDbgIntrinsicToDbgRecord (StringRef Name, CallBase * CI) static
Convert debug intrinsic calls to non-instruction debug records.
Name - Final part of the intrinsic name, e.g. 'value' in llvm.dbg.value. CI - The debug intrinsic call.
Definition at line 4792 of file AutoUpgrade.cpp.
References llvm::DIExpression::append(), llvm::CallBase::arg_size(), assert(), llvm::DbgVariableRecord::Assign, llvm::DbgLabelRecord::createUnresolvedDbgLabelRecord(), llvm::DbgVariableRecord::createUnresolvedDbgVariableRecord(), llvm::DbgVariableRecord::Declare, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::CallBase::getArgOperand(), llvm::Instruction::getDebugLoc(), getDebugLocSafe(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Offset, unwrapMAVMetadataOp(), unwrapMAVOp(), and llvm::DbgVariableRecord::Value.
Referenced by llvm::UpgradeIntrinsicCall().
upgradeIntrinsicFunction1()
bool upgradeIntrinsicFunction1 (Function * F, Function *& NewFn, bool CanUpgradeDebugIntrinsicsToRecords) static
Definition at line 1249 of file AutoUpgrade.cpp.
References assert(), llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), consumeNVVMPtrAddrSpace(), Default, llvm::StringSwitch< T, R >::Default(), F, llvm::Intrinsic::getOrInsertDeclaration(), Groups, llvm::Intrinsic::not_intrinsic, llvm::SmallVectorTemplateBase< T, bool >::push_back(), R2, rename(), shouldUpgradeNVPTXBF16Intrinsic(), shouldUpgradeNVPTXSharedClusterIntrinsic(), shouldUpgradeNVPTXTMAG2SIntrinsics(), llvm::StringSwitch< T, R >::StartsWith(), upgradeArmOrAarch64IntrinsicFunction(), and upgradeX86IntrinsicFunction().
Referenced by llvm::UpgradeIntrinsicFunction().
upgradeLoopArgument()
Metadata * upgradeLoopArgument (Metadata * MD) static
Definition at line 6439 of file AutoUpgrade.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::dyn_cast_or_null(), E(), llvm::MDTuple::get(), I, T, and upgradeLoopTag().
Referenced by llvm::upgradeInstructionLoopAttachment().
upgradeLoopTag()
MDString * upgradeLoopTag (LLVMContext & C, StringRef OldTag) static
Definition at line 6427 of file AutoUpgrade.cpp.
References assert(), llvm::CallingConv::C, llvm::StringRef::drop_front(), llvm::MDString::get(), llvm::StringRef::size(), and llvm::StringRef::starts_with().
Referenced by upgradeLoopArgument().
upgradeMaskedCompare()
Value * upgradeMaskedCompare (IRBuilder<> & Builder, CallBase & CI, unsigned CC, bool Signed) static
Definition at line 2331 of file AutoUpgrade.cpp.
References applyX86MaskOn1BitsVec(), llvm::CallBase::arg_size(), llvm::cast(), llvm::FixedVectorType::get(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, Op0, and Signed.
Referenced by upgradeX86IntrinsicCall().
upgradeMaskedLoad()
Value * upgradeMaskedLoad (IRBuilder<> & Builder, Value * Ptr, Value * Passthru, Value * Mask, bool Aligned) static
Definition at line 2248 of file AutoUpgrade.cpp.
References llvm::Aligned, llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), and getX86MaskVec().
Referenced by upgradeX86IntrinsicCall().
upgradeMaskedMove()
Value * upgradeMaskedMove (IRBuilder<> & Builder, CallBase & CI) static
Definition at line 2370 of file AutoUpgrade.cpp.
References A(), B(), llvm::CallBase::getArgOperand(), and Select.
Referenced by upgradeX86IntrinsicCall().
upgradeMaskedStore()
Value * upgradeMaskedStore (IRBuilder<> & Builder, Value * Ptr, Value * Data, Value * Mask, bool Aligned) static
Definition at line 2230 of file AutoUpgrade.cpp.
References llvm::Aligned, llvm::CallingConv::C, llvm::cast(), llvm::Data, llvm::dyn_cast(), and getX86MaskVec().
Referenced by upgradeX86IntrinsicCall().
upgradeMaskToInt()
Value * upgradeMaskToInt (IRBuilder<> & Builder, CallBase & CI) static
Definition at line 2384 of file AutoUpgrade.cpp.
References llvm::cast(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), and getX86MaskVec().
Referenced by upgradeX86IntrinsicCall().
upgradeNVVMFnVectorAttr()
void upgradeNVVMFnVectorAttr (const StringRef Attr, const char DimC, GlobalValue * GV, const Metadata * V) static
Definition at line 5758 of file AutoUpgrade.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), llvm::StringRef::empty(), llvm::mdconst::extract(), F, llvm::Length, llvm::StringRef::split(), and llvm::StringRef::trim().
Referenced by upgradeSingleNVVMAnnotation().
upgradeNVVMIntrinsicCall()
Value * upgradeNVVMIntrinsicCall (StringRef Name, CallBase * CI, Function * F, IRBuilder<> & Builder) static
Definition at line 2641 of file AutoUpgrade.cpp.
References llvm::Function::arg_size(), llvm::CallingConv::C, llvm::StringSwitch< T, R >::Case(), llvm::cast(), consumeNVVMPtrAddrSpace(), F, llvm::AtomicRMWInst::FAdd, llvm::FixedVectorType::get(), llvm::MDNode::get(), llvm::Function::getArg(), llvm::CallBase::getArgOperand(), llvm::Type::getBFloatTy(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::getScalarType(), llvm::Value::getType(), I, llvm::Type::isBFloatTy(), llvm::Type::isIntegerTy(), llvm::Intrinsic::not_intrinsic, rename(), llvm::SequentiallyConsistent, llvm::FastMathFlags::setApproxFunc(), shouldUpgradeNVPTXBF16Intrinsic(), llvm::AtomicRMWInst::UDecWrap, and llvm::AtomicRMWInst::UIncWrap.
Referenced by llvm::UpgradeIntrinsicCall().
upgradePMULDQ()
Value * upgradePMULDQ (IRBuilder<> & Builder, CallBase & CI, bool IsSigned) static
Definition at line 2279 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), emitX86Select(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), LHS, and RHS.
Referenced by upgradeX86IntrinsicCall().
upgradePTESTIntrinsic()
bool upgradePTESTIntrinsic (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 68 of file AutoUpgrade.cpp.
References F, llvm::FixedVectorType::get(), llvm::Type::getFloatTy(), llvm::Intrinsic::getOrInsertDeclaration(), and rename().
Referenced by upgradeX86IntrinsicFunction().
upgradeRetainReleaseMarker()
bool upgradeRetainReleaseMarker (Module & M) static
This checks for objc retain release marker which should be upgraded.
It returns true if module is modified.
Definition at line 5897 of file AutoUpgrade.cpp.
References llvm::dyn_cast_or_null(), llvm::Module::Error, llvm::MDString::get(), llvm::NamedMDNode::getOperand(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::UpgradeARCRuntime().
upgradeSingleNVVMAnnotation()
bool upgradeSingleNVVMAnnotation (GlobalValue * GV, StringRef K, const Metadata * V) static
Definition at line 5795 of file AutoUpgrade.cpp.
References llvm::cast(), llvm::mdconst::extract(), llvm::Attribute::get(), llvm::Value::getContext(), llvm::Attribute::getWithStackAlignment(), isXYZ(), isZero(), llvm::CallingConv::PTX_Kernel, and upgradeNVVMFnVectorAttr().
Referenced by llvm::UpgradeNVVMAnnotations().
upgradeVectorSplice()
Value * upgradeVectorSplice (CallBase * CI, IRBuilder<> & Builder) static
Definition at line 4842 of file AutoUpgrade.cpp.
References llvm::dyn_cast(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), llvm::Offset, and llvm::reportFatalUsageError().
Referenced by llvm::UpgradeIntrinsicCall().
upgradeX86ALIGNIntrinsics()
Value * upgradeX86ALIGNIntrinsics (IRBuilder<> & Builder, Value * Op0, Value * Op1, Value * Shift, Value * Passthru, Value * Mask, bool IsVALIGN) static
Definition at line 2012 of file AutoUpgrade.cpp.
References llvm::ArrayRef(), assert(), llvm::cast(), emitX86Select(), llvm::Constant::getNullValue(), llvm::isPowerOf2_32(), and Op0.
Referenced by upgradeX86IntrinsicCall().
upgradeX86BF16DPIntrinsic()
bool upgradeX86BF16DPIntrinsic (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 157 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getOrInsertDeclaration(), and rename().
Referenced by upgradeX86IntrinsicFunction().
upgradeX86BF16Intrinsic()
bool upgradeX86BF16Intrinsic (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 147 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getOrInsertDeclaration(), and rename().
Referenced by upgradeX86IntrinsicFunction().
upgradeX86BinaryIntrinsics()
Value * upgradeX86BinaryIntrinsics (IRBuilder<> & Builder, CallBase & CI, Intrinsic::ID IID) static
Definition at line 2117 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), emitX86Select(), llvm::User::getOperand(), llvm::Value::getType(), and Op0.
Referenced by upgradeX86IntrinsicCall().
upgradeX86ConcatShift()
Value * upgradeX86ConcatShift (IRBuilder<> & Builder, CallBase & CI, bool IsShiftRight, bool ZeroMask) static
Definition at line 2197 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), llvm::cast(), emitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::User::getOperand(), llvm::Value::getType(), Op0, and std::swap().
Referenced by upgradeX86IntrinsicCall().
upgradeX86IntrinsicCall()
Value * upgradeX86IntrinsicCall (StringRef Name, CallBase * CI, Function * F, IRBuilder<> & Builder) static
Definition at line 2800 of file AutoUpgrade.cpp.
References A(), AbstractManglingParser< Derived, Alloc >::Ops, llvm::Aligned, applyX86MaskOn1BitsVec(), llvm::CallBase::arg_size(), llvm::CallBase::args(), llvm::ArrayRef(), assert(), B(), llvm::CallingConv::C, llvm::cast(), llvm::Data, emitX86ScalarSelect(), emitX86Select(), F, llvm::ConstantAggregateZero::get(), llvm::ConstantAsMetadata::get(), llvm::FixedVectorType::get(), llvm::MDNode::get(), llvm::PoisonValue::get(), llvm::VectorType::get(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::Type::getHalfTy(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::VectorType::getInteger(), llvm::Instruction::getModule(), llvm::Constant::getNullValue(), getNumElements(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::ShuffleVectorInst::getShuffleMask(), getType(), llvm::Value::getType(), getX86MaskVec(), High, I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::isa(), llvm::Type::isIntegerTy(), LHS, llvm_unreachable, llvm::Offset, Op0, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), RHS, llvm::Instruction::setMetadata(), Size, std::swap(), upgradeAbs(), upgradeAVX512MaskToSelect(), upgradeMaskedCompare(), upgradeMaskedLoad(), upgradeMaskedMove(), upgradeMaskedStore(), upgradeMaskToInt(), upgradePMULDQ(), upgradeX86ALIGNIntrinsics(), upgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), upgradeX86MaskedShift(), upgradeX86PSLLDQIntrinsics(), upgradeX86PSRLDQIntrinsics(), upgradeX86Rotate(), upgradeX86vpcom(), and upgradeX86VPERMT2Intrinsics().
Referenced by llvm::UpgradeIntrinsicCall().
upgradeX86IntrinsicFunction()
bool upgradeX86IntrinsicFunction (Function * F, StringRef Name, Function *& NewFn) static
Definition at line 534 of file AutoUpgrade.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), F, llvm::Intrinsic::getOrInsertDeclaration(), llvm::Intrinsic::not_intrinsic, rename(), shouldUpgradeX86Intrinsic(), upgradePTESTIntrinsic(), upgradeX86BF16DPIntrinsic(), upgradeX86BF16Intrinsic(), upgradeX86IntrinsicsWith8BitMask(), upgradeX86MaskedFPCompare(), upgradeX86MultiplyAddBytes(), and upgradeX86MultiplyAddWords().
Referenced by upgradeIntrinsicFunction1().
upgradeX86IntrinsicsWith8BitMask()
bool upgradeX86IntrinsicsWith8BitMask (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 84 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::isIntegerTy(), and rename().
Referenced by upgradeX86IntrinsicFunction().
upgradeX86MaskedFPCompare()
bool upgradeX86MaskedFPCompare (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 100 of file AutoUpgrade.cpp.
References F, llvm::Intrinsic::getOrInsertDeclaration(), and rename().
Referenced by upgradeX86IntrinsicFunction().
upgradeX86MaskedShift()
Value * upgradeX86MaskedShift (IRBuilder<> & Builder, CallBase & CI, Intrinsic::ID IID) static
Definition at line 2363 of file AutoUpgrade.cpp.
References emitX86Select(), and llvm::CallBase::getArgOperand().
Referenced by upgradeX86IntrinsicCall().
upgradeX86MultiplyAddBytes()
bool upgradeX86MultiplyAddBytes (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 113 of file AutoUpgrade.cpp.
References llvm::cast(), F, llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::isVectorTy(), and rename().
Referenced by upgradeX86IntrinsicFunction().
upgradeX86MultiplyAddWords()
bool upgradeX86MultiplyAddWords (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 131 of file AutoUpgrade.cpp.
References llvm::cast(), F, llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::isVectorTy(), and rename().
Referenced by upgradeX86IntrinsicFunction().
upgradeX86PSLLDQIntrinsics()
Value * upgradeX86PSLLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 1897 of file AutoUpgrade.cpp.
References llvm::ArrayRef(), llvm::cast(), llvm::FixedVectorType::get(), and llvm::Constant::getNullValue().
Referenced by upgradeX86IntrinsicCall().
upgradeX86PSRLDQIntrinsics()
Value * upgradeX86PSRLDQIntrinsics (IRBuilder<> & Builder, Value * Op, unsigned Shift) static
Definition at line 1931 of file AutoUpgrade.cpp.
References llvm::ArrayRef(), llvm::cast(), llvm::FixedVectorType::get(), and llvm::Constant::getNullValue().
Referenced by upgradeX86IntrinsicCall().
upgradeX86Rotate()
Value * upgradeX86Rotate (IRBuilder<> & Builder, CallBase & CI, bool IsRotateRight) static
Definition at line 2132 of file AutoUpgrade.cpp.
References llvm::CallBase::arg_size(), llvm::cast(), emitX86Select(), llvm::CallBase::getArgOperand(), llvm::User::getOperand(), and llvm::Value::getType().
Referenced by upgradeX86IntrinsicCall().
upgradeX86vpcom()
Value * upgradeX86vpcom (IRBuilder<> & Builder, CallBase & CI, unsigned Imm, bool IsSigned) static
Definition at line 2158 of file AutoUpgrade.cpp.
References llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, LHS, llvm_unreachable, and RHS.
Referenced by upgradeX86IntrinsicCall().
upgradeX86VPERMT2Intrinsics()
Value * upgradeX86VPERMT2Intrinsics (IRBuilder<> & Builder, CallBase & CI, bool ZeroMask, bool IndexForm) static
Definition at line 2057 of file AutoUpgrade.cpp.
References emitX86Select(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm_unreachable, and std::swap().
Referenced by upgradeX86IntrinsicCall().
Variable Documentation
DisableAutoUpgradeDebugInfo
cl::opt< bool > DisableAutoUpgradeDebugInfo("disable-auto-upgrade-debug-info", cl::desc("Disable autoupgrade of debug info")) ("disable-auto-upgrade-debug-info" , cl::desc("Disable autoupgrade of debug info")) static
Referenced by llvm::UpgradeDebugInfo().