LLVM: lib/Bitcode/Reader/BitReader.cpp File Reference
BitReader.cpp File Reference
#include "llvm-c/BitReader.h"
#include "llvm-c/Core.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/MemoryBuffer.h"
#include <cstring>
#include <string>
Functions
LLVMBool LLVMParseBitcode (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage)
LLVMBool LLVMParseBitcode2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule)
LLVMBool LLVMParseBitcodeInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage)
LLVMBool LLVMParseBitcodeInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule)
LLVMBool LLVMGetBitcodeModuleInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
LLVMBool LLVMGetBitcodeModuleInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM)
Reads a module from the given memory buffer, returning via the OutMP parameter a module provider which performs lazy deserialization.
LLVMBool LLVMGetBitcodeModule (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
LLVMBool LLVMGetBitcodeModule2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM)
Function Documentation
LLVMGetBitcodeModule()
LLVMBool LLVMGetBitcodeModule (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Definition at line 124 of file BitReader.cpp.
References llvm::getGlobalContextForCAPI(), and LLVMGetBitcodeModuleInContext().
LLVMGetBitcodeModule2()
LLVMBool LLVMGetBitcodeModule2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM)
Definition at line 130 of file BitReader.cpp.
References llvm::getGlobalContextForCAPI(), and LLVMGetBitcodeModuleInContext2().
LLVMParseBitcode()
LLVMBool LLVMParseBitcode (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule, char ** OutMessage)
Definition at line 23 of file BitReader.cpp.
References llvm::getGlobalContextForCAPI(), and LLVMParseBitcodeInContext().
LLVMParseBitcode2()
LLVMBool LLVMParseBitcode2 (LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule)
Definition at line 29 of file BitReader.cpp.
References llvm::getGlobalContextForCAPI(), and LLVMParseBitcodeInContext2().