LLVM: lib/XRay/BlockVerifier.cpp File Reference
BlockVerifier.cpp File Reference
#include "llvm/XRay/BlockVerifier.h"
#include "llvm/Support/Error.h"
#include <bitset>
Functions
static constexpr unsigned long long mask (BlockVerifier::State S)
static constexpr std::size_t number (BlockVerifier::State S)
static StringRef recordToString (BlockVerifier::State R)
Function Documentation
mask()
constexpr unsigned long long mask (BlockVerifier::State S) static constexpr
Definition at line 16 of file BlockVerifier.cpp.
Referenced by llvm::AVRAsmBackend::applyFixup(), blend_epi16(), llvm::SwitchCG::CaseBits::CaseBits(), DecodeIT(), get_cpu_features(), llvm::DomainValue::getCommonDomains(), llvm::APInt::insertBits(), load_counters(), load_counters(), load_counters16(), load_counters4(), load_counters8(), llvm::PatternMatch::m_Shuffle(), llvm::SDPatternMatch::m_Shuffle(), llvm::RegisterMaskSDNode::SelectionDAG, llvm::APInt::setBits(), llvm::APInt::tcDivide(), and llvm::APInt::tcExtract().
number()
constexpr std::size_t number (BlockVerifier::State S) static constexpr
Definition at line 20 of file BlockVerifier.cpp.
Referenced by lto_codegen_debug_options_array(), lto_set_debug_options(), thinlto_debug_options(), and llvm::to_string().
recordToString()
StringRef recordToString (BlockVerifier::State R) static
Definition at line 24 of file BlockVerifier.cpp.
References llvm::xray::BlockVerifier::BufferExtents, llvm::xray::BlockVerifier::CallArg, llvm::xray::BlockVerifier::CustomEvent, llvm::xray::BlockVerifier::EndOfBuffer, llvm::xray::BlockVerifier::Function, llvm_unreachable, llvm::xray::BlockVerifier::NewBuffer, llvm::xray::BlockVerifier::NewCPUId, llvm::xray::BlockVerifier::PIDEntry, llvm::xray::BlockVerifier::StateMax, llvm::xray::BlockVerifier::TSCWrap, llvm::xray::BlockVerifier::TypedEvent, llvm::xray::BlockVerifier::Unknown, and llvm::xray::BlockVerifier::WallClockTime.
Referenced by llvm::xray::BlockVerifier::verify().