LLVM: lib/Transforms/Instrumentation/BoundsChecking.cpp File Reference
BoundsChecking.cpp File Reference
#include "llvm/Transforms/Instrumentation/BoundsChecking.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetFolder.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <utility>
Classes
class BuilderTy
Macros
#define DEBUG_TYPE "bounds-checking"
Functions
STATISTIC (ChecksAdded, "Bounds checks added")
STATISTIC (ChecksSkipped, "Bounds checks skipped")
STATISTIC (ChecksUnable, "Bounds checks unable to add")
static Value * getBoundsCheckCond (Value *Ptr, Value *InstVal, const DataLayout &DL, TargetLibraryInfo &TLI, ObjectSizeOffsetEvaluator &ObjSizeEval, BuilderTy &IRB, ScalarEvolution &SE)
Gets the conditions under which memory accessing instructions will overflow.
static CallInst * InsertTrap (BuilderTy &IRB, bool DebugTrapBB, std::optional< int8_t > GuardKind)
static CallInst * InsertCall (BuilderTy &IRB, bool MayReturn, StringRef Name)
template<typename GetTrapBBT>
static void insertBoundsCheck (Value *Or, BuilderTy &IRB, GetTrapBBT GetTrapBB)
Adds run-time bounds checks to memory accessing instructions.
static std::string getRuntimeCallName (const BoundsCheckingPass::Options::Runtime &Opts)
static bool addBoundsChecking (Function &F, TargetLibraryInfo &TLI, ScalarEvolution &SE, const BoundsCheckingPass::Options &Opts)
Variables
static cl::opt< bool > SingleTrapBB ("bounds-checking-single-trap", cl::desc("Use one trap block per function"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bounds-checking"
Definition at line 35 of file BoundsChecking.cpp.
Function Documentation
addBoundsChecking()
bool addBoundsChecking (Function & F, TargetLibraryInfo & TLI, ScalarEvolution & SE, const BoundsCheckingPass::Options & Opts) static
Definition at line 190 of file BoundsChecking.cpp.
References llvm::CallBase::addFnAttr(), llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateIntrinsic(), DL, llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::ObjectSizeOpts::EvalMode, llvm::ObjectSizeOpts::ExactUnderlyingSizeAndOffset, F, getBoundsCheckCond(), llvm::Function::getContext(), llvm::IRBuilderBase::getInt1Ty(), llvm::GlobalValue::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), getRuntimeCallName(), llvm::BoundsCheckingPass::Options::GuardKind, I, insertBoundsCheck(), InsertCall(), InsertTrap(), instructions, llvm::BoundsCheckingPass::Options::Merge, llvm::CallingConv::PreserveAll, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ObjectSizeOpts::RoundToAlign, llvm::BoundsCheckingPass::Options::Rt, llvm::CallBase::setCallingConv(), llvm::Instruction::setDebugLoc(), llvm::CallBase::setDoesNotReturn(), llvm::CallBase::setDoesNotThrow(), and SingleTrapBB.
Referenced by llvm::BoundsCheckingPass::run().
getBoundsCheckCond()
Value * getBoundsCheckCond (Value * Ptr, Value * InstVal, const DataLayout & DL, TargetLibraryInfo & TLI, ObjectSizeOffsetEvaluator & ObjSizeEval, BuilderTy & IRB, ScalarEvolution & SE) static
Gets the conditions under which memory accessing instructions will overflow.
Ptr is the pointer that will be read/written, and InstVal is either the result from the load or the value being stored. It is used to determine the size of memory block that is touched.
Returns the condition under which the access will overflow.
Definition at line 59 of file BoundsChecking.cpp.
References llvm::SizeOffsetType< T, C >::bothKnown(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::IRBuilderBase::CreateICmpSLT(), llvm::IRBuilderBase::CreateICmpULT(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateSub(), llvm::IRBuilderBase::CreateTypeSize(), llvm::dbgs(), DL, llvm::dyn_cast(), llvm::Value::getContext(), llvm::ConstantInt::getFalse(), llvm::ScalarEvolution::getSCEV(), llvm::Value::getType(), llvm::ScalarEvolution::getUnsignedRange(), llvm::ConstantInt::getValue(), LLVM_DEBUG, llvm::Offset, llvm::SizeOffsetType< T, C >::Offset, Size, llvm::SizeOffsetType< T, C >::Size, and llvm::APInt::slt().
Referenced by addBoundsChecking().
getRuntimeCallName()
std::string getRuntimeCallName (const BoundsCheckingPass::Options::Runtime & Opts) static
Definition at line 179 of file BoundsChecking.cpp.
References llvm::BoundsCheckingPass::Options::Runtime::HandlerPreserveAllRegs, llvm::BoundsCheckingPass::Options::Runtime::MayReturn, and llvm::BoundsCheckingPass::Options::Runtime::MinRuntime.
Referenced by addBoundsChecking().
insertBoundsCheck()
template<typename GetTrapBBT> void insertBoundsCheck (Value * Or, BuilderTy & IRB, GetTrapBBT GetTrapBB) static
Adds run-time bounds checks to memory accessing instructions.
Or is the condition that should guard the trap.
GetTrapBB is a callable that returns the trap BB to use on failure.
Definition at line 148 of file BoundsChecking.cpp.
References llvm::CallingConv::C, llvm::BranchInst::Create(), llvm::dyn_cast_or_null(), llvm::Instruction::eraseFromParent(), llvm::IRBuilderBase::GetInsertPoint(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), and llvm::BasicBlock::splitBasicBlock().
Referenced by addBoundsChecking().
InsertCall()
CallInst * InsertCall (BuilderTy & IRB, bool MayReturn, StringRef Name) static
Definition at line 128 of file BoundsChecking.cpp.
References B(), llvm::IRBuilderBase::CreateCall(), llvm::Function::getContext(), llvm::IRBuilderBase::GetInsertBlock(), llvm::Module::getOrInsertFunction(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), and llvm::Type::getVoidTy().
Referenced by addBoundsChecking().
InsertTrap()
CallInst * InsertTrap (BuilderTy & IRB, bool DebugTrapBB, std::optional< int8_t > GuardKind) static
Definition at line 111 of file BoundsChecking.cpp.
References llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getInt8Ty(), llvm::BasicBlock::getParent(), and llvm::Function::size().
Referenced by addBoundsChecking().
STATISTIC() [1/3]
STATISTIC (ChecksAdded , "Bounds checks added")
STATISTIC() [2/3]
STATISTIC (ChecksSkipped , "Bounds checks skipped")
STATISTIC() [3/3]
STATISTIC (ChecksUnable , "Bounds checks unable to add")
Variable Documentation
SingleTrapBB
cl::opt< bool > SingleTrapBB("bounds-checking-single-trap", cl::desc("Use one trap block per function")) ("bounds-checking-single-trap" , cl::desc("Use one trap block per function")) static
Referenced by addBoundsChecking().