LLVM: lib/Target/BPF/AsmParser/BPFAsmParser.cpp File Reference
BPFAsmParser.cpp File Reference
#include "MCTargetDesc/BPFMCAsmInfo.h"
#include "MCTargetDesc/BPFMCTargetDesc.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "BPFGenAsmMatcher.inc"
Macros
#define GET_ASSEMBLER_HEADER
#define GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
Functions
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFAsmParser ()
Macro Definition Documentation
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 58 of file BPFAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 286 of file BPFAsmParser.cpp.
GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_OPERAND_DIAGNOSTIC_TYPES
Definition at line 68 of file BPFAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 285 of file BPFAsmParser.cpp.
Function Documentation
LLVMInitializeBPFAsmParser()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFAsmParser ()
Definition at line 541 of file BPFAsmParser.cpp.
References llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, X, and Y.