LLVM: lib/Target/BPF/BPFISelLowering.cpp File Reference
BPFISelLowering.cpp File Reference
#include "BPFISelLowering.h"
#include "BPF.h"
#include "BPFSubtarget.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "BPFGenCallingConv.inc"
Macros
#define DEBUG_TYPE "bpf-lower"
#define SET_NEWCC(X, Y)
Functions
static void fail (const SDLoc &DL, SelectionDAG &DAG, const Twine &Msg, SDValue Val={})
static void resetRegMaskBit (const TargetRegisterInfo *TRI, uint32_t *RegMask, MCRegister Reg)
static uint32_t * regMaskFromTemplate (const TargetRegisterInfo *TRI, MachineFunction &MF, const uint32_t *BaseRegMask)
static void NegateCC (SDValue &LHS, SDValue &RHS, ISD::CondCode &CC)
static Function * createBPFUnreachable (Module *M)
static SDValue getTargetNode (ConstantPoolSDNode *N, const SDLoc &DL, EVT Ty, SelectionDAG &DAG, unsigned Flags)
static SDValue getTargetNode (JumpTableSDNode *N, const SDLoc &DL, EVT Ty, SelectionDAG &DAG, unsigned Flags)
Variables
static cl::opt< bool > BPFExpandMemcpyInOrder ("bpf-expand-memcpy-in-order", cl::Hidden, cl::init(false), cl::desc("Expand memcpy into load/store pairs in order"))
static cl::opt< unsigned > BPFMinimumJumpTableEntries ("bpf-min-jump-table-entries", cl::init(13), cl::Hidden, cl::desc("Set minimum number of entries to use a jump table on BPF"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bpf-lower"
Definition at line 36 of file BPFISelLowering.cpp.
SET_NEWCC
#define SET_NEWCC (X, Y)
Value:
case ISD::X: \
  if (is32BitCmp && HasJmp32) \
    NewCC = isSelectRROp ? BPF::Y##_rr_32 : BPF::Y##_ri_32; \
  else \
    NewCC = isSelectRROp ? BPF::Y##_rr : BPF::Y##_ri; \
  break
Referenced by llvm::BPFTargetLowering::EmitInstrWithCustomInserter().
Function Documentation
createBPFUnreachable()
Function * createBPFUnreachable (Module * M) static
Definition at line 775 of file BPFISelLowering.cpp.
References BPF_TRAP, llvm::CallingConv::C, llvm::Function::Create(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createSubroutineType(), llvm::GlobalValue::ExternalWeakLinkage, llvm::FunctionType::get(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::Type::getVoidTy(), llvm::Function::setCallingConv(), llvm::GlobalValue::setDSOLocal(), llvm::GlobalObject::setSection(), and llvm::Function::setSubprogram().
fail()
void fail (const SDLoc & DL, SelectionDAG & DAG, const Twine & Msg, SDValue Val = {}) static
Definition at line 46 of file BPFISelLowering.cpp.
References DL.
Referenced by checkAsyncContextProjectFunction(), checkAsyncFuncPointer(), checkConstantInt(), llvm::CoroAsyncEndInst::checkWellFormed(), checkWFAlloc(), checkWFDealloc(), and checkWFRetconPrototype().
getTargetNode() [1/2]
SDValue getTargetNode (ConstantPoolSDNode * N, const SDLoc & DL, EVT Ty, SelectionDAG & DAG, unsigned Flags) static
Definition at line 826 of file BPFISelLowering.cpp.
References DL, llvm::SelectionDAG::getTargetConstantPool(), and N.
getTargetNode() [2/2]
SDValue getTargetNode (JumpTableSDNode * N, const SDLoc & DL, EVT Ty, SelectionDAG & DAG, unsigned Flags) static
Definition at line 832 of file BPFISelLowering.cpp.
References DL, llvm::SelectionDAG::getTargetJumpTable(), and N.
NegateCC()
void NegateCC (SDValue & LHS, SDValue & RHS, ISD::CondCode & CC) static
Definition at line 700 of file BPFISelLowering.cpp.
References llvm::ISD::getSetCCSwappedOperands(), LHS, RHS, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETULE, llvm::ISD::SETULT, and std::swap().
regMaskFromTemplate()
uint32_t * regMaskFromTemplate (const TargetRegisterInfo * TRI, MachineFunction & MF, const uint32_t * BaseRegMask) static
Definition at line 465 of file BPFISelLowering.cpp.
References llvm::MachineFunction::allocateRegMask(), llvm::MachineOperand::getRegMaskSize(), and TRI.
resetRegMaskBit()
void resetRegMaskBit (const TargetRegisterInfo * TRI, uint32_t * RegMask, MCRegister Reg) static
Definition at line 459 of file BPFISelLowering.cpp.
References Reg, SubReg, and TRI.
Variable Documentation
BPFExpandMemcpyInOrder
cl::opt< bool > BPFExpandMemcpyInOrder("bpf-expand-memcpy-in-order", cl::Hidden, cl::init(false), cl::desc("Expand memcpy into load/store pairs in order")) ("bpf-expand-memcpy-in-order" , cl::Hidden , cl::init(false) , cl::desc("Expand memcpy into load/store pairs in order")) static
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
BPFMinimumJumpTableEntries
cl::opt< unsigned > BPFMinimumJumpTableEntries("bpf-min-jump-table-entries", cl::init(13), cl::Hidden, cl::desc("Set minimum number of entries to use a jump table on BPF")) ("bpf-min-jump-table-entries" , cl::init(13) , cl::Hidden , cl::desc("Set minimum number of entries to use a jump table on BPF")) static
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().