LLVM: lib/Target/BPF/BPFTargetMachine.cpp File Reference
BPFTargetMachine.cpp File Reference
#include "BPFTargetMachine.h"
#include "BPF.h"
#include "BPFTargetLoweringObjectFile.h"
#include "BPFTargetTransformInfo.h"
#include "MCTargetDesc/BPFMCAsmInfo.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/CodeGen/GlobalISel/IRTranslator.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/GlobalISel/Legalizer.h"
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/SimplifyCFG.h"
#include "llvm/Transforms/Utils/SimplifyCFGOptions.h"
#include <optional>
#include "llvm/Passes/TargetPassRegistry.inc"
Macros
#define GET_PASS_REGISTRY "BPFPassRegistry.def"
#define ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
#define ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
#define MODULE_ANALYSIS(NAME, CREATE_PASS)
#define MODULE_PASS(NAME, CREATE_PASS)
#define MODULE_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define FUNCTION_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_ALIAS_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_PASS(NAME, CREATE_PASS)
#define FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define LOOP_ANALYSIS(NAME, CREATE_PASS)
#define LOOP_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_ANALYSIS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define ADD_PASS(NAME, CREATE_PASS)
#define ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
#define MODULE_PASS(NAME, CREATE_PASS)
#define MODULE_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define FUNCTION_PASS(NAME, CREATE_PASS)
#define FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define LOOP_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_PASS_WITH_PARAMS(NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
#define MODULE_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_ANALYSIS(NAME, CREATE_PASS)
#define FUNCTION_ALIAS_ANALYSIS(NAME, CREATE_PASS)
#define LOOP_ANALYSIS(NAME, CREATE_PASS)
#define MACHINE_FUNCTION_ANALYSIS(NAME, CREATE_PASS)
Functions
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFTarget ()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static Expected< bool > parseBPFPreserveStaticOffsetOptions (StringRef Params)
Variables
static cl::opt< bool > DisableMIPeephole ("disable-bpf-peephole", cl::Hidden, cl::desc("Disable machine peepholes for BPF"))
static cl::opt< bool > DisableCheckUnreachable ("bpf-disable-trap-unreachable", cl::Hidden, cl::desc("Disable Trap Unreachable for BPF"))
Macro Definition Documentation
ADD_CLASS_PASS_TO_PASS_NAME
#define ADD_CLASS_PASS_TO_PASS_NAME (NAME, CREATE_PASS)
Value:
PIC->addClassToPassName(decltype(CREATE_PASS)::name(), NAME);
ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS
#define ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS (NAME, CLASS)
Value:
PIC->addClassToPassName(CLASS, NAME);
ADD_PASS
#define ADD_PASS (NAME, CREATE_PASS)
Value:
if (Name == NAME) {                                                          \
  PM.addPass(CREATE_PASS);                                                   \
  return true;                                                               \
}
ADD_PASS_WITH_PARAMS
#define ADD_PASS_WITH_PARAMS (NAME, CREATE_PASS, PARSER)
Value:
if (PassBuilder::checkParametrizedPassName(Name, NAME)) {                    \
  auto Params = PassBuilder::parsePassParameters(PARSER, Name, NAME);        \
  if (!Params) {                                                             \
    errs() << NAME ": " << toString(Params.takeError()) << '\n';             \
    return false;                                                            \
  }                                                                          \
  PM.addPass(CREATE_PASS(Params.get()));                                     \
  return true;                                                               \
}
FUNCTION_ALIAS_ANALYSIS [1/2]
#define FUNCTION_ALIAS_ANALYSIS (NAME, CREATE_PASS)
Value:
if (Name == NAME) {                                                          \
  AM.registerFunctionAnalysis<                                               \
      std::remove_reference_t<decltype(CREATE_PASS)>>();                     \
  return true;                                                               \
}
FUNCTION_ALIAS_ANALYSIS [2/2]
#define FUNCTION_ALIAS_ANALYSIS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
FUNCTION_ANALYSIS [1/2]
#define FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
AM.registerPass([&] { return CREATE_PASS; });
FUNCTION_ANALYSIS [2/2]
#define FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
FUNCTION_PASS [1/2]
#define FUNCTION_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
FUNCTION_PASS [2/2]
#define FUNCTION_PASS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
FUNCTION_PASS_WITH_PARAMS [1/2]
#define FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
FUNCTION_PASS_WITH_PARAMS [2/2]
#define FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
GET_PASS_REGISTRY
#define GET_PASS_REGISTRY "BPFPassRegistry.def"
LOOP_ANALYSIS [1/2]
#define LOOP_ANALYSIS (NAME, CREATE_PASS)
Value:
AM.registerPass([&] { return CREATE_PASS; });
LOOP_ANALYSIS [2/2]
#define LOOP_ANALYSIS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
LOOP_PASS [1/2]
#define LOOP_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
LOOP_PASS [2/2]
#define LOOP_PASS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MACHINE_FUNCTION_ANALYSIS [1/2]
#define MACHINE_FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
AM.registerPass([&] { return CREATE_PASS; });
MACHINE_FUNCTION_ANALYSIS [2/2]
#define MACHINE_FUNCTION_ANALYSIS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MACHINE_FUNCTION_PASS [1/2]
#define MACHINE_FUNCTION_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
MACHINE_FUNCTION_PASS [2/2]
#define MACHINE_FUNCTION_PASS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MACHINE_FUNCTION_PASS_WITH_PARAMS [1/2]
#define MACHINE_FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
MACHINE_FUNCTION_PASS_WITH_PARAMS [2/2]
#define MACHINE_FUNCTION_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
MODULE_ANALYSIS [1/2]
#define MODULE_ANALYSIS (NAME, CREATE_PASS)
Value:
AM.registerPass([&] { return CREATE_PASS; });
MODULE_ANALYSIS [2/2]
#define MODULE_ANALYSIS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MODULE_PASS [1/2]
#define MODULE_PASS (NAME, CREATE_PASS)
Value:
ADD_PASS(NAME, CREATE_PASS)
MODULE_PASS [2/2]
#define MODULE_PASS (NAME, CREATE_PASS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME(NAME, CREATE_PASS)
MODULE_PASS_WITH_PARAMS [1/2]
#define MODULE_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
ADD_PASS_WITH_PARAMS(NAME, CREATE_PASS, PARSER)
MODULE_PASS_WITH_PARAMS [2/2]
#define MODULE_PASS_WITH_PARAMS (NAME, CLASS, CREATE_PASS, PARSER, PARAMS)
Value:
ADD_CLASS_PASS_TO_PASS_NAME_WITH_PARAMS(NAME, CLASS)
Function Documentation
getEffectiveRelocModel()
Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 63 of file BPFTargetMachine.cpp.
References llvm::Reloc::PIC_.
LLVMInitializeBPFTarget()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFTarget ()
Definition at line 46 of file BPFTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), llvm::initializeBPFAsmPrinterPass(), llvm::initializeBPFCheckAndAdjustIRPass(), llvm::initializeBPFDAGToDAGISelLegacyPass(), llvm::initializeBPFMIPeepholePass(), llvm::initializeBPFMIPreEmitCheckingPass(), llvm::initializeBPFMIPreEmitPeepholePass(), llvm::initializeBPFMISimplifyPatchablePass(), llvm::initializeGlobalISel(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, X, and Y.
parseBPFPreserveStaticOffsetOptions()
Expected< bool > parseBPFPreserveStaticOffsetOptions (StringRef Params) static
Definition at line 117 of file BPFTargetMachine.cpp.
References llvm::PassBuilder::parseSinglePassOption().
Variable Documentation
DisableCheckUnreachable
cl::opt< bool > DisableCheckUnreachable("bpf-disable-trap-unreachable", cl::Hidden, cl::desc("Disable Trap Unreachable for BPF")) ("bpf-disable-trap-unreachable" , cl::Hidden , cl::desc("Disable Trap Unreachable for BPF")) static
Referenced by llvm::BPFTargetMachine::BPFTargetMachine().
DisableMIPeephole
cl::opt< bool > DisableMIPeephole("disable-bpf-peephole", cl::Hidden, cl::desc("Disable machine peepholes for BPF")) ("disable-bpf-peephole" , cl::Hidden , cl::desc("Disable machine peepholes for BPF")) static