LLVM: lib/IR/BuiltinGCs.cpp File Reference
BuiltinGCs.cpp File Reference
#include "llvm/IR/BuiltinGCs.h"
#include "llvm/IR/GCStrategy.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/Support/Casting.h"
Functions
static GCRegistry::Add< ErlangGC > A ("erlang", "erlang-compatible garbage collector")
static GCRegistry::Add< OcamlGC > B ("ocaml", "ocaml 3.10-compatible GC")
static GCRegistry::Add< ShadowStackGC > C ("shadow-stack", "Very portable GC for uncooperative code generators")
static GCRegistry::Add< StatepointGC > D ("statepoint-example", "an example strategy for statepoint")
static GCRegistry::Add< CoreCLRGC > E ("coreclr", "CoreCLR-compatible GC")
Function Documentation
A()
GCRegistry::Add< ErlangGC > A ("erlang" , "erlang-compatible garbage collector") static
Referenced by llvm::AAAddressSpace::AAAddressSpace(), llvm::AAAlign::AAAlign(), llvm::AAAllocationInfo::AAAllocationInfo(), llvm::AAAssumptionInfo::AAAssumptionInfo(), llvm::AADenormalFPMath::AADenormalFPMath(), llvm::AADereferenceable::AADereferenceable(), llvm::AAExecutionDomain::AAExecutionDomain(), llvm::AAGlobalValueInfo::AAGlobalValueInfo(), llvm::AAHeapToStack::AAHeapToStack(), llvm::AAIndirectCallInfo::AAIndirectCallInfo(), llvm::AAInstanceInfo::AAInstanceInfo(), llvm::AAInterFnReachability::AAInterFnReachability(), llvm::AAIntraFnReachability::AAIntraFnReachability(), llvm::AAIsDead::AAIsDead(), llvm::AAMemoryBehavior::AAMemoryBehavior(), llvm::AAMemoryLocation::AAMemoryLocation(), llvm::AAMustProgress::AAMustProgress(), llvm::AANoAlias::AANoAlias(), llvm::AANoAliasAddrSpace::AANoAliasAddrSpace(), llvm::AANoCapture::AANoCapture(), llvm::AANoFPClass::AANoFPClass(), llvm::AANoFree::AANoFree(), llvm::AANonConvergent::AANonConvergent(), llvm::AANonNull::AANonNull(), llvm::AANoRecurse::AANoRecurse(), llvm::AANoReturn::AANoReturn(), llvm::AANoSync::AANoSync(), llvm::AANoUndef::AANoUndef(), llvm::AANoUnwind::AANoUnwind(), llvm::AAPotentialConstantValues::AAPotentialConstantValues(), llvm::AAPotentialValues::AAPotentialValues(), llvm::AAPrivatizablePtr::AAPrivatizablePtr(), llvm::AAUndefinedBehavior::AAUndefinedBehavior(), llvm::AAValueConstantRange::AAValueConstantRange(), llvm::AAValueSimplify::AAValueSimplify(), llvm::AAWillReturn::AAWillReturn(), llvm::APIntOps::abds(), llvm::APIntOps::abdu(), absSCEVNoSignedOverflow(), llvm::opt::Option::accept(), llvm::Automaton< ActionT >::add(), llvm::ResourceSegments::add(), llvm::xray::LogBuilder::add(), llvm::AA::PointerInfo::State::addAccess(), addAccessAttr(), AddAliasScopeMetadata(), llvm::AAExecutionDomain::ExecutionDomainTy::addAlignedBarrier(), llvm::memprof::addAmbiguousAttribute(), llvm::ExecutionEngine::addArchive(), llvm::MCJIT::addArchive(), addArgumentAttrs(), llvm::AAExecutionDomain::ExecutionDomainTy::addAssumeInst(), llvm::AttrBuilder::addAttribute(), llvm::AttributeMask::addAttribute(), llvm::AttributeMask::addAttribute(), llvm::addAttributeAtIndex(), addByteCountSuffix(), llvm::opt::ArgList::addLastArg(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), addMemoryAttrs(), llvm::opt::ArgList::addOptInFlag(), llvm::addParamAttribute(), addRawAttributeValue(), llvm::LoongArchAsmBackend::addReloc(), llvm::RISCVAsmBackend::addReloc(), llvm::NVPTX::AddressSpaceToString(), llvm::addRuntimeChecks(), addSCEVNoOverflow(), llvm::memprof::CallStackTrie::addSingleAllocTypeAttribute(), llvm::opt::DerivedArgList::AddSynthesizedArg(), adjustDown(), adjustInliningThresholdUsingCallee(), adjustUp(), llvm::AIXException::AIXException(), llvm::AMDGPUAAResult::alias(), llvm::alignTo(), llvm::alignTo(), llvm::detail::AllocatorHolder< AllocatorTy >::AllocatorHolder(), llvm::detail::AllocatorHolder< AllocatorTy >::AllocatorHolder(), llvm::VETargetLowering::allowsMisalignedMemoryAccesses(), alwaysInlineImpl(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::opt::ArgList::append(), llvm::DWARFTypePrinter< DieType >::appendConstVolatileQualifierBefore(), llvm::cl::aliasopt::apply(), llvm::HexagonSubtarget::BankConflictMutation::apply(), llvm::jitlink::ppc64::applyFixup(), llvm::jitlink::systemz::applyFixup(), areConsecutiveOrMatch(), llvm::MemoryDepChecker::areDepsSafe(), AreEquivalentAddressValues(), areInSameBB(), llvm::AbstractDependenceGraphBuilder< GraphType >::areNodesMergeable(), llvm::AttributeFuncs::areOutlineCompatible(), llvm::ArgInfo::ArgInfo(), llvm::ARMException::ARMException(), arrayDataSize(), askForAssumedConstant(), llvm::AssertAlignSDNode::AssertAlignSDNode(), assignSlotsUsingVGPRBlocks(), attemptToFoldSymbolOffsetDifference(), llvm::AttrBuilder::AttrBuilder(), llvm::AttributeMask::AttributeMask(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::AttributeSpec(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::AttributeSpec(), llvm::AbstractAttribute::Attributor, BitsProperlyConcatenate(), bothUsedInPHI(), buildFrameType(), llvm::buildModuleSummaryIndex(), buildSymbolDiff(), buildSymbolDiff(), llvm::CallBase::bundleOperandHasAttr(), llvm::xray::CallArgRecord::CallArgRecord(), llvm::CallBase::CallBase(), llvm::Automaton< ActionT >::canAdd(), canBeMerged(), canComputePointerDiff(), canonicalizeAbs(), canonicalizeBitSelect(), canonicalizeICmpBool(), canonicalizeSaturatedSubtract(), llvm::AAInterFnReachability::canReach(), CanShareConstantPoolEntry(), ceilingOfQuotient(), llvm::MMRAMetadata::checkCompatibility(), checkCondition(), llvm::checkedMulAdd(), llvm::checkedMulAddUnsigned(), checkForAllInstructionsImpl(), llvm::IRSimilarity::IRSimilarityCandidate::checkRelativeLocations(), llvm::opt::ArgList::claimAllArgs(), clampReturnedValueStates(), llvm::Attribute::cmpKind(), coalescable(), collectBitParts(), collectBlockUseDef(), llvm::coro::collectSpillsFromArgs(), llvm::MMRAMetadata::combine(), combineAddSubWithShlAddSub(), combineFMA(), llvm::AA::combineOptionalValuesInAAValueLatice(), combinePExtTruncate(), combineShiftToAVG(), combineUADDO_CARRYDiamond(), combineVFMADD_VLWithVFNEG_VL(), llvm::commonAlignment(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::IRComparer< T >::compare(), llvm::object::compareAddress(), llvm::IRSimilarity::IRSimilarityCandidate::compareCommutativeOperandMapping(), compareNames(), llvm::IRSimilarity::IRSimilarityCandidate::compareNonCommutativeOperandMapping(), llvm::ValueDFS_Compare::comparePHIRelated(), compareSegmentsByOffset(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::BaseIndexOffset::computeAliasing(), computeAliasSummary(), llvm::computeConstantRange(), llvm::HexagonBlockRanges::computeDeadMap(), llvm::computeDelta(), computeKnownBits(), computeKnownBitsForPRMT(), computeKnownBitsFromCond(), computeKnownBitsFromLerpPattern(), computeKnownFPClassFromCond(), llvm::computeLTOCacheKey(), llvm::rdf::Liveness::computePhiInfo(), computePointerICmp(), computePRMT(), llvm::memprof::computeUndriftMap(), llvm::ImmutableListFactory< T >::concat(), llvm::MDNode::concatenate(), constantFold(), llvm::constructSeqOffsettoOrigRowMapping(), consumeFront(), llvm::AttrBuilder::contains(), llvm::AttrBuilder::contains(), llvm::AttributeMask::contains(), llvm::AttributeMask::contains(), llvm::AttributeMask::contains(), llvm::HexagonBlockRanges::IndexRange::contains(), llvm::rdf::NodeAttrs::contains(), convertArgumentInfo(), convertCalledGlobals(), convertCallSiteObjects(), ConvertFunctionAttr(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::copy(), llvm::StringRef::copy(), llvm::AArch64RegisterBankInfo::copyCost(), llvm::RegisterBankInfo::copyCost(), llvm::copyModuleAttrToFunctions(), llvm::coro::BaseCloner::create(), llvm::object::Slice::create(), llvm::VPBuilder::createFCmp(), llvm::AAAddressSpace::createForPosition(), llvm::AAAlign::createForPosition(), llvm::AAAllocationInfo::createForPosition(), llvm::AAAssumptionInfo::createForPosition(), llvm::AADenormalFPMath::createForPosition(), llvm::AADereferenceable::createForPosition(), llvm::AAExecutionDomain::createForPosition(), llvm::AAGlobalValueInfo::createForPosition(), llvm::AAHeapToStack::createForPosition(), llvm::AAIndirectCallInfo::createForPosition(), llvm::AAInstanceInfo::createForPosition(), llvm::AAInterFnReachability::createForPosition(), llvm::AAIntraFnReachability::createForPosition(), llvm::AAInvariantLoadPointer::createForPosition(), llvm::AAIsDead::createForPosition(), llvm::AAMemoryBehavior::createForPosition(), llvm::AAMemoryLocation::createForPosition(), llvm::AAMustProgress::createForPosition(), llvm::AANoAlias::createForPosition(), llvm::AANoAliasAddrSpace::createForPosition(), llvm::AANoCapture::createForPosition(), llvm::AANoFPClass::createForPosition(), llvm::AANoFree::createForPosition(), llvm::AANonConvergent::createForPosition(), llvm::AANonNull::createForPosition(), llvm::AANoRecurse::createForPosition(), llvm::AANoReturn::createForPosition(), llvm::AANoSync::createForPosition(), llvm::AANoUndef::createForPosition(), llvm::AANoUnwind::createForPosition(), llvm::AAPointerInfo::createForPosition(), llvm::AAPotentialConstantValues::createForPosition(), llvm::AAPotentialValues::createForPosition(), llvm::AAPrivatizablePtr::createForPosition(), llvm::AAUndefinedBehavior::createForPosition(), llvm::AAUnderlyingObjects::createForPosition(), llvm::AAValueConstantRange::createForPosition(), llvm::AAValueSimplify::createForPosition(), llvm::AAWillReturn::createForPosition(), createFunctionClones(), llvm::VPBuilder::createICmp(), llvm::orc::StaticLibraryDefinitionGenerator::createMemberBuffer(), llvm::ImutAVLFactory< ImutInfo >::createNode(), llvm::mustache::createNode(), createTargetMachine(), llvm::IRBuilderBase::CreateThreadLocalAddress(), llvm::orc::MapperJITLinkMemoryManager::CreateWithMapper(), llvm::orc::EPCGenericJITLinkMemoryManager::deallocate(), llvm::DebugHandlerBase::DebugHandlerBase(), llvm::DebugStr(), decompose(), llvm::Dependence::Dependence(), llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, jitlink::JITLinkMemoryManager::FinalizedAlloc >::deserialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< char >, ArrayRef< char > >::deserialize(), llvm::HexagonFrameLowering::determineCalleeSaves(), determinePointerAccessAttrs(), llvm::diagnoseDontCall(), llvm::DIEAbbrevData::DIEAbbrevData(), llvm::DIEAbbrevData::DIEAbbrevData(), llvm::DIEAbbrevSet::DIEAbbrevSet(), llvm::DIEHash::DIEHash(), llvm::DIEInlineString::DIEInlineString(), llvm::rdf::disjoint(), dominates(), dominates(), dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::DominatorTreeBase< BlockT, false >::dominates(), llvm::DominatorTreeBase< BlockT, false >::dominates(), llvm::MachineDominatorTree::dominates(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), llvm::DWARFFormValue::dump(), dumpAllocas(), llvm::dumpMaxRegPressure(), llvm::DwarfCFIException::DwarfCFIException(), llvm::DwarfCompileUnit::DwarfCompileUnit(), llvm::DwarfDebug::DwarfDebug(), llvm::DwarfStringPool::DwarfStringPool(), llvm::DwarfTypeUnit::DwarfTypeUnit(), llvm::DwarfUnit::DwarfUnit(), llvm::EHStreamer::EHStreamer(), llvm::BitTracker::MachineEvaluator::eIMM(), llvm::yaml::SequenceTraits< ArrayDocNode >::element(), eliminateConstraints(), llvm::DwarfStringPool::emit(), llvm::MCPseudoProbeSections::emit(), llvm::AsmPrinter::emitFunctionBody(), llvm::LoopVectorizationPlanner::emitInvalidCostRemarks(), llvm::TargetLoweringObjectFileCOFF::emitLinkerDirectives(), emitOrXorXorTree(), llvm::MCObjectStreamer::emitPendingAssignments(), llvm::MCELFStreamer::emitWeakReference(), emitWideAPInt(), llvm::dxil::DXILBitcodeWriter::emitWideAPInt(), llvm::CfiFunctionIndex::emplace(), llvm::json::Array::emplace(), llvm::json::Array::emplace_back(), llvm::Align::encode, llvm::encode(), llvm::MachineFunction::ensureAlignment(), llvm::EnumEntry< T >::EnumEntry(), llvm::rdf::PhysicalRegisterInfo::equal_to(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::InstrProfLookupTrait::EqualKey(), llvm::memprof::CallStackLookupTrait::EqualKey(), llvm::memprof::FrameLookupTrait::EqualKey(), llvm::memprof::RecordLookupTrait::EqualKey(), llvm::ARMConstantPoolConstant::equals(), llvm::ARMConstantPoolMBB::equals(), llvm::ARMConstantPoolSymbol::equals(), llvm::ARMConstantPoolValue::equals(), llvm::CSKYConstantPoolConstant::equals(), llvm::CSKYConstantPoolJT::equals(), llvm::CSKYConstantPoolMBB::equals(), llvm::CSKYConstantPoolSymbol::equals(), llvm::CSKYConstantPoolValue::equals(), llvm::RISCVConstantPoolValue::equals(), llvm::XtensaConstantPoolConstant::equals(), llvm::XtensaConstantPoolJumpTable::equals(), llvm::XtensaConstantPoolMBB::equals(), llvm::XtensaConstantPoolSymbol::equals(), llvm::XtensaConstantPoolValue::equals(), llvm::sys::fs::equivalent(), llvm::sys::fs::equivalent(), llvm::sys::fs::equivalent(), llvm::sys::fs::file_status::equivalent, llvm::vfs::FileSystem::equivalent(), equivalentAddressValues(), llvm::MDAttachments::erase(), llvm::rdf::DeadCodeElimination::erase(), llvm::opt::ArgList::eraseArg(), llvm::HexagonEvaluator::evaluate(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateSymbolicAdd(), llvm::VPWidenCastRecipe::execute(), llvm::VPWidenRecipe::execute(), llvm::WindowScheduler::expand(), expandFloatDotIntrinsic(), expandFSH64(), expandFunnelShiftIntrinsic(), expandIntegerDotIntrinsic(), expandUsubSat(), llvm::SCEVExpander::expandWrapPredicate(), llvm::cl::ExpansionContext::ExpansionContext(), llvm::ModuleSummaryIndex::exportToDot(), llvm::DWARFAbbreviationDeclaration::extract(), extractSubModule(), factorizeMinMaxTree(), llvm::AArch64CallLowering::fallBackToDAGISel(), fillOverallFunction(), llvm::LoongArch::fillValidCPUList(), llvm::AccelTableBase::finalize(), llvm::objcopy::elf::ASCIIHexWriter::finalize(), Find(), find(), llvm::find_singleton(), llvm::find_singleton_nested(), llvm::AArch64::ArchInfo::findBySubArch(), findCanonNumsForPHI(), findFuncPointers(), llvm::coverage::MCDCRecord::findIndependencePairs(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), findOrCreatePHIInBlock(), findRecipeWithMinAlign(), findStrip(), llvm::MCJIT::findSymbol(), llvm::symbolize::SymbolizableObjectFile::findSymbol(), findUses(), llvm::findValuesAffectedByCondition(), firstCommonClass(), fixupFPReturnAndCall(), floorOfQuotient(), foldAbsDiff(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldAndToXor(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), foldComplexAndOrPatterns(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOfUAddOv(), foldICmpOrXX(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpShlConstConst(), llvm::InstCombinerImpl::foldICmpShrConstConst(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::foldICmpWithZero(), foldICmpXorXX(), foldIntrinsicUsingDistributiveLaws(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldMulHigh(), foldNegativePower2AndShiftedMask(), foldNotXor(), foldOrToXor(), foldPowerOf2AndShiftedMask(), foldReduceOperandViaVQDOT(), foldSelectCmpBitcasts(), llvm::InstCombinerImpl::foldSelectEqualityTest(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::InstCombinerImpl::foldSPFofSPF(), llvm::InstCombinerImpl::foldSquareSumFP(), llvm::InstCombinerImpl::foldSquareSumInt(), foldUnsignedUnderflowCheck(), llvm::InstCombinerImpl::foldUsingDistributiveLaws(), foldXorToXor(), llvm::AAPointerInfo::forallInterferingAccesses(), llvm::FormattedBytes::FormattedBytes(), llvm::DIExpression::fragmentCmp(), llvm::DIExpression::fragmentsOverlap(), llvm::json::fromJSON(), fullyContains(), gcd(), llvm::detail::gcd(), llvm::detail::SlowDynamicAPInt::gcd, llvm::DynamicAPInt::gcd, llvm::HexagonInstrInfo::genAllInsnTimingClasses(), generateGatherLanePattern(), generateReproducer(), llvm::gep_type_begin(), llvm::gep_type_end(), llvm::AMDGPU::ClusterDimsAttr::get(), llvm::MDAttachments::get(), llvm::ScalarEvolution::getAddExpr(), getAlign(), llvm::AttributeSetNode::getAlignment(), llvm::MDAttachments::getAll(), llvm::AttributeSetNode::getAllocKind(), llvm::AttrBuilder::getAllocSizeArgs(), llvm::AttributeSetNode::getAllocSizeArgs(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::LoongArch::getArchFeatures(), llvm::SCCPInstVisitor::getArgAttributeVL(), llvm::FunctionLoweringInfo::getArgumentFrameIndex(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::SelectionDAG::getAssertAlign(), llvm::AAMemoryLocation::getAsStr(), llvm::AbstractAttribute::getAsStr(), llvm::AAPotentialConstantValues::getAssumedConstant(), llvm::AAValueConstantRange::getAssumedConstant(), llvm::AAValueConstantRange::getAssumedConstantRange(), getAssumptions(), llvm::getAssumptions(), llvm::getAssumptions(), llvm::AttrBuilder::getAttribute(), llvm::AttrBuilder::getAttribute(), llvm::AttributeSetNode::getAttribute(), llvm::AttributeSetNode::getAttributeType(), llvm::getBaseObjectSize(), llvm::MCAssembler::getBaseSymbol(), llvm::ARM::getCanonicalArchName(), llvm::AttributeSetNode::getCaptureInfo(), llvm::InstCostVisitor::getCodeSizeSavingsForArg(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion(), llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion(), llvm::RegionInfoBase< RegionTraits< MachineFunction > >::getCommonRegion(), llvm::TargetRegisterInfo::getCommonSubClass(), llvm::ExecutionEngine::getConstantValue(), getConstraintFromMemoryAccess(), llvm::object::ResourceSectionRef::getContents(), getContiguousRangeOfSetBits(), llvm::RISCVTTIImpl::getCostOfKeepingLiveOverCall(), llvm::vfs::FileSystem::getCurrentWorkingDirectory(), llvm::IRAttribute< AK, BaseType, AAType >::getDeducedAttributes(), llvm::AttributeSetNode::getDereferenceableBytes(), llvm::AttributeSetNode::getDereferenceableOrNullBytes(), llvm::coverage::MCDCRecord::TestVector::getDifferences(), llvm::orc::getDylibInterfaceFromTapiFile(), llvm::NonRelocatableStringpool::getEntriesForEmission(), llvm::GraphTraits< ArgumentGraphNode * >::getEntryNode(), llvm::CallBase::getFnAttr(), getFPBinOp(), getFPTernOp(), llvm::InstCombiner::getFreelyInvertedImpl(), getFSqrtDivOptPattern(), llvm::getFunctionAtVTableOffset(), llvm::InstrProfSymtab::getFunctionHashFromAddress(), llvm::LegacyDefaultAnalysisGraphTraits< AnalysisT, GraphT >::getGraph(), llvm::AccessAsInstructionInfo::getHashValue(), llvm::DenseMapInfo< AAPointerInfo::Access >::getHashValue(), getHashValueImpl(), getHexUint(), getImplicitCondFromMI(), llvm::InformationCache::getIndirectlyCallableFunctions(), llvm::AA::getInitialValueForObj(), llvm::AMDGPU::getIntegerPairAttribute(), llvm::AMDGPU::getIntegerVecAttribute(), llvm::HexagonSubtarget::getIntrinsicId(), llvm::AAValueConstantRange::getKnownConstantRange(), llvm::opt::ArgList::getLastArg(), llvm::opt::ArgList::getLastArgNoClaim(), llvm::opt::ArgList::getLastArgValue(), getLeastCommonType(), getLocalFunctionMetadata(), getMaskedICmpType(), getMaskedTypeForICmpPair(), llvm::CmpPredicate::getMatching(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::X86RegisterInfo::getMatchingSuperRegClass(), getMaxWidth(), llvm::AttributeSetNode::getMemoryEffects(), llvm::MDNode::getMergedCalleeTypeMetadata(), llvm::MDNode::getMergedCallsiteMetadata(), llvm::DILocation::getMergedLocation(), llvm::MDNode::getMergedMemProfMetadata(), llvm::MDNode::getMergedProfMetadata(), getMinimalBaseOfPointer(), llvm::GlobalValue::getMinUnnamedAddr(), llvm::sandboxir::GlobalValue::getMinUnnamedAddr(), getMinVisibility(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericAlignmentOrDereferenceable(), llvm::MDNode::getMostGenericFPMath(), llvm::MDNode::getMostGenericNoaliasAddrspace(), llvm::MDNode::getMostGenericRange(), llvm::MDNode::getMostGenericTBAA(), llvm::APIntOps::GetMostSignificantDifferentBit(), llvm::AttributeSetNode::getNoFPClass(), llvm::ISD::ArgFlagsTy::getNonZeroByValAlign(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::CallBase::getParamAttr(), llvm::CallBase::getParamAttr(), getPassedArgumentAndAdjustArgumentLocation(), getPassedArgumentInAlreadyOutlinedFunction(), getPotentialCopiesOfMemoryValue(), llvm::AA::getPotentialCopiesOfStoredValue(), llvm::AA::getPotentiallyLoadedValues(), getPRMT(), getPRMT(), GetQuadraticEquation(), getRange(), GetRangeFromMetadata(), llvm::AttrBuilder::getRawIntAttr(), llvm::RegScavenger::getScavengingFrameIndices(), llvm::AAPotentialValues::getSingleValue(), llvm::GenericCycleInfo< ContextT >::getSmallestCommonCycle(), llvm::GenericCycleInfo< ContextT >::getSmallestCommonCycle(), llvm::GenericCycleInfo< MachineSSAContext >::getSmallestCommonCycle(), llvm::GenericCycleInfo< MachineSSAContext >::getSmallestCommonCycle(), llvm::LoopInfoBase< BlockT, LoopT >::getSmallestCommonLoop(), llvm::LoopInfoBase< BlockT, LoopT >::getSmallestCommonLoop(), llvm::LoopInfoBase< BasicBlock, Loop >::getSmallestCommonLoop(), llvm::LoopInfoBase< BasicBlock, Loop >::getSmallestCommonLoop(), getSpillSlotSize(), getStableFunctionEntries(), llvm::AttributeSetNode::getStackAlignment(), llvm::opt::ArgList::getSubCommand(), getSymbolOffsetImpl(), llvm::DataLayout::getTypeAllocSize(), llvm::AttrBuilder::getTypeAttr(), llvm::ScalarEvolution::getUDivExpr(), getUnsigned(), llvm::AttributeSetNode::getUWTableKind(), llvm::AttributeSetNode::getVScaleRangeMax(), llvm::AttributeSetNode::getVScaleRangeMin(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithStackAlignment(), getZeroPaddedAdd(), greaterWithBias(), llvm::APIntOps::GreatestCommonDivisor(), llvm::InLineChangePrinter::handleFunctionCompare(), llvm::AA::hasAssumedIRAttr(), hasAssumption(), llvm::hasAssumption(), llvm::hasAssumption(), llvm::AttributeImpl::hasAttribute(), llvm::sampleprof::SampleContext::hasAttribute(), llvm::opt::ArgList::hasFlag(), llvm::opt::ArgList::hasFlag(), llvm::opt::ArgList::hasFlagNoClaim(), llvm::ArgInfo::hash_value, llvm::ReachingDefInfo::hasSameReachingDef(), HasSameValue(), llvm::SelectionDAG::haveNoCommonBitsSet(), haveNoCommonBitsSetCommutative(), haveNoCommonBitsSetSpecialCases(), haveNonOverlappingStorage(), llvm::VPlanTransforms::hoistPredicatedLoads(), hoistPreviousBeforeFORUsers(), llvm::rdf::NodeAllocator::id(), llvm::SCCPSolver::inferArgAttributes(), inferDomainOfAffine(), inferInitializes(), llvm::AbstractAttribute::initialize(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::mca::initializeUsedResources(), llvm::jitlink::initRelaxAux(), llvm::DiagnosticInfoOptimizationBase::insert(), llvm::json::Array::insert(), insertSpills(), instCombineMaxMinNM(), instCombineSVEUzp1(), instCombineSVEZip(), llvm::AAInterFnReachability::instructionCanReach(), llvm::ScalarEvolution::instructionCouldExistWithOperands(), llvm::DbgVariableFragmentInfo::intersect(), llvm::FMFSource::intersect(), llvm::MDNode::intersect(), llvm::ResourceSegments::intersects(), isAddSExtable(), llvm::APInt::isAligned(), isAllocDisjoint(), llvm::AMDGPU::isArgPassedInSGPR(), llvm::AAIntraFnReachability::isAssumedReachable(), llvm::AA::isAssumedReadNone(), llvm::AA::isAssumedReadOnly(), isAssumedReadOnlyOrReadNone(), llvm::AA::isAssumedThreadLocalObject(), llvm::InstructionOrdering::isBefore(), IsBetterCanonical(), isClampZeroToOne(), llvm::IRSimilarity::isClose(), llvm::isConsecutiveAccess(), isContiguous(), isContiguous(), llvm::SuspendCrossingInfo::isDefinitionAcrossSuspend(), llvm::AA::isDynamicallyUnique(), llvm::SlotIndex::isEarlierEqualInstr(), llvm::SlotIndex::isEarlierInstr(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::DenseMapInfo< AA::RangeTy >::isEqual(), llvm::DenseMapInfo< at::VarRecord >::isEqual(), llvm::DenseMapInfo< const SwitchSuccWrapper * >::isEqual(), llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex >::isEqual(), llvm::DenseMapInfo< DebugVariable >::isEqual(), llvm::DenseMapInfo< DIExpression::FragmentInfo >::isEqual(), llvm::DenseMapInfo< LocIdx >::isEqual(), llvm::DenseMapInfo< object::SectionRef >::isEqual(), llvm::DenseMapInfo< SlotWithTag >::isEqual(), llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::isEqual(), llvm::DenseMapInfo< ValueIDNum >::isEqual(), llvm::SelectionDAG::isEqualTo(), llvm::AAExecutionDomain::isExecutedInAlignedRegion(), isGuaranteedNotToBeUndefOrPoison(), llvm::vputils::isHeaderMask(), isHorizontalBinOp(), llvm::AAMustProgress::isImpliedByIR(), llvm::AANoAlias::isImpliedByIR(), llvm::AANoCapture::isImpliedByIR(), llvm::AANoFree::isImpliedByIR(), llvm::AANonNull::isImpliedByIR(), llvm::AANoSync::isImpliedByIR(), llvm::AANoUndef::isImpliedByIR(), llvm::AAWillReturn::isImpliedByIR(), llvm::IRAttribute< AK, BaseType, AAType >::isImpliedByIR(), llvm::AAWillReturn::isImpliedByMustprogressAndReadonly(), isImpliedCondICmps(), isInstructionPairAdd(), isInstructionPairMul(), llvm::BitTracker::MachineEvaluator::isInt(), isInvariantLoad(), llvm::isKnownInversion(), llvm::ScalarEvolution::isKnownMultipleOf(), llvm::isKnownNegation(), isKnownNonEqual(), isKnownNonZero(), llvm::HexagonTargetLowering::isLegalAddressingMode(), isMinMaxCmpSelectEliminable(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), isNoAliasOrByValArgument(), isNonEqualPointersWithRecursiveGEP(), llvm::AA::isNoSyncInst(), llvm::isNotVisibleOnUnwind(), isOnlyUsedInEntryBlock(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation(), llvm::AA::isPotentiallyAffectedByBarrier(), llvm::AA::isPotentiallyAffectedByBarrier(), isPotentiallyReachable(), llvm::AA::isPotentiallyReachable(), llvm::AA::isPotentiallyReachable(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachable(), llvm::DominatorTreeBase< BlockT, false >::isReachableFromEntry(), llvm::DominatorTreeBase< BlockT, false >::isReachableFromEntry(), llvm::APFloatBase::isRepresentableBy(), llvm::SlotIndex::isSameInstr(), isSameScalarConst(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), StrBoolAttr::isSet(), llvm::IRSimilarity::IRSimilarityCandidate::isSimilar(), isSortedByValueNo(), llvm::AMDGPUMachineModuleInfo::isSyncScopeInclusion(), llvm::isTheSameCluster(), isTriviallyUniform(), isUnsupportedFunction(), llvm::LoongArch::isValidArchName(), llvm::AA::isValidAtPosition(), llvm::AA::isValidInScope(), llvm::AAAddressSpace::isValidIRPositionForInit(), llvm::AAAlign::isValidIRPositionForInit(), llvm::AAAllocationInfo::isValidIRPositionForInit(), llvm::AADereferenceable::isValidIRPositionForInit(), llvm::AAGlobalValueInfo::isValidIRPositionForInit(), llvm::AAIndirectCallInfo::isValidIRPositionForInit(), llvm::AAInvariantLoadPointer::isValidIRPositionForInit(), llvm::AAIsDead::isValidIRPositionForInit(), llvm::AAMemoryBehavior::isValidIRPositionForInit(), llvm::AAMemoryLocation::isValidIRPositionForInit(), llvm::AANoAlias::isValidIRPositionForInit(), llvm::AANoAliasAddrSpace::isValidIRPositionForInit(), llvm::AANoCapture::isValidIRPositionForInit(), llvm::AANoFPClass::isValidIRPositionForInit(), llvm::AANoFree::isValidIRPositionForInit(), llvm::AANonNull::isValidIRPositionForInit(), llvm::AANoSync::isValidIRPositionForInit(), llvm::AAPointerInfo::isValidIRPositionForInit(), llvm::AAPotentialConstantValues::isValidIRPositionForInit(), llvm::AAPrivatizablePtr::isValidIRPositionForInit(), llvm::AAUnderlyingObjects::isValidIRPositionForInit(), llvm::AAValueConstantRange::isValidIRPositionForInit(), llvm::AbstractAttribute::isValidIRPositionForInit(), llvm::AbstractAttribute::isValidIRPositionForUpdate(), llvm::DominatorTreeBase< BlockT, false >::isVirtualRoot(), llvm::isWritableObject(), llvm::object::ViewArray< T >::iterator::iterator(), llvm::LazyCallGraph::LazyCallGraph(), llvm::detail::lcm(), llvm::DynamicAPInt::lcm, legalizeCallAttributes(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::cfg::LegalizeUpdates(), llvm::rdf::PhysicalRegisterInfo::less(), llvm::HexagonInstr::lessCore(), llvm::HexagonInstr::lessCVI(), llvm::HexagonResource::lessUnits(), llvm::HexagonResource::lessWeight(), llvm::LexicalScope::LexicalScope(), llvm::gsym::LineEntry::LineEntry(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVMAddAttributeAtIndex(), LLVMAddCallSiteAttribute(), LLVMAddTargetDependentFunctionAttr(), LLVMGetAttributesAtIndex(), LLVMGetCallSiteAttributes(), LLVMGetEnumAttributeKind(), LLVMGetEnumAttributeValue(), LLVMGetNextParam(), LLVMGetParams(), LLVMGetPreviousParam(), LLVMGetStringAttributeKind(), LLVMGetStringAttributeValue(), LLVMGetTypeAttributeValue(), LLVMInitializeAMDGPUAsmParser(), LLVMInitializeARMAsmParser(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMInitializeRISCVAsmParser(), LLVMInitializeRISCVAsmPrinter(), LLVMInitializeRISCVTarget(), LLVMInitializeRISCVTargetInfo(), LLVMInitializeSparcAsmParser(), LLVMInitializeVEAsmParser(), LLVMInitializeXtensaTarget(), LLVMIsEnumAttribute(), LLVMIsStringAttribute(), LLVMIsTypeAttribute(), LLVMSetParamAlignment(), llvm::coverage::CoverageMapping::load(), llvm::object::ResourceSectionRef::load(), llvm::orc::StaticLibraryDefinitionGenerator::loadAllObjectFileMembers(), loadObj(), llvm::ValueDFS_Compare::localComesBefore(), llvm::Align::Log2, llvm::MDAttachments::lookup(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), lowerBuildVectorViaPacking(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::AMDGPUTargetLowering::lowerFEXP(), LowerMUL(), LowerMULH(), LowerMULO(), lowerPrmtIntrinsic(), LowerShift(), llvm::LegalizerHelper::lowerVAArg(), llvm::HexagonTargetLowering::LowerVECTOR_SHIFT(), LowervXi8MulWithUNPCK(), llvm::MachineConstantPoolEntry::MachineConstantPoolEntry(), llvm::MachineConstantPoolEntry::MachineConstantPoolEntry(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::jitlink::LinkGraph::makeAbsolute(), makeCloneInPraceMap(), llvm::MachineFunction::makeDebugValueSubstitution(), llvm::jitlink::LinkGraph::makeExternal(), llvm::makeIntrusiveRefCnt(), llvm::orc::makeStub(), llvm::AbstractAttribute::manifest(), llvm::IRAttribute< AK, BaseType, AAType >::manifest(), llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< Argument >::mapping(), llvm::yaml::MappingTraits< SIArgument >::mapping(), llvm::markRegisterParameterAttributes(), markTails(), llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::match(), matchAccessTags(), matchDeMorgansLaws(), matchesAdd(), matchesOr(), matchesSquareSum(), matchMinMaxOfMinMax(), matchSelectAddSub(), matchSelectWithOptionalNotCond(), matchUAddWithOverflowConstantEdgeCases(), llvm::maximum(), llvm::maximumnum(), llvm::maxnum(), llvm::Align::MaybeAlign, llvm::HexagonBlockRanges::IndexRange::merge(), merge(), MergeAliasResults(), llvm::AbstractDependenceGraphBuilder< GraphType >::mergeNodes(), llvm::DDGBuilder::mergeNodes(), llvm::InstrProfWriter::mergeProfileKind(), MergeSeqs(), llvm::MinAlign(), llvm::MinAlign(), llvm::minimum(), llvm::minimumnum(), llvm::minnum(), minusSCEVNoSignedOverflow(), llvm::MMRAMetadata::MMRAMetadata(), mulSCEVNoSignedOverflow(), mulSCEVOverflow(), llvm::ConstantRange::multiply(), llvm::detail::DoubleAPFloat::multiply(), llvm::NextPowerOf2(), llvm::rdf::NodeAddr< NodeBase * >::NodeAddr(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyFinalized(), llvm::OperandBundleUse::operandHasAttr(), operator delete(), operator new(), llvm::AA::operator!=(), llvm::AAMDNodes::operator!=(), llvm::Attribute::operator!=(), llvm::CHIArg::operator!=(), llvm::codeview::operator!=(), llvm::codeview::TypeIndex::operator!=, llvm::detail::operator!=(), llvm::detail::operator!=(), llvm::DWARFDebugNames::NameIterator::operator!=, llvm::DWARFDebugNames::ValueIterator::operator!=, llvm::DynamicAPInt::operator!=, llvm::DynamicAPInt::operator!=, llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::RawLocationWrapper::operator!=, llvm::detail::operator%(), llvm::detail::operator%(), llvm::DynamicAPInt::operator%, llvm::DynamicAPInt::operator%, llvm::detail::operator%=(), llvm::DynamicAPInt::operator%=, EarlierIssuingCycle::operator()(), llvm::CompSpillWeight::operator()(), llvm::deref< T >::operator()(), llvm::orc::COFFImportFileScanner::operator()(), llvm::orc::ExecutorNativePlatform::operator()(), llvm::orc::ForceLoadMachOArchiveMembers::operator()(), llvm::rdf::RegisterRefEqualTo::operator()(), llvm::rdf::RegisterRefLess::operator()(), llvm::SystemZTargetStreamer::CmpMCInst::operator()(), llvm::ValueDFS_Compare::operator()(), std::hash< llvm::rdf::RegisterAggr >::operator()(), std::hash< llvm::rdf::RegisterRef >::operator()(), llvm::detail::operator*(), llvm::detail::operator*(), llvm::DynamicAPInt::operator*, llvm::DynamicAPInt::operator*, llvm::detail::operator*=(), llvm::DynamicAPInt::operator*=, llvm::codeview::TypeIndex::operator+, llvm::detail::operator+(), llvm::detail::operator+(), llvm::DynamicAPInt::operator+, llvm::DynamicAPInt::operator+, llvm::detail::operator+=(), llvm::DynamicAPInt::operator+=, llvm::codeview::TypeIndex::operator-, llvm::codeview::TypeIndex::operator-, llvm::detail::operator-(), llvm::detail::operator-(), llvm::DynamicAPInt::operator-, llvm::DynamicAPInt::operator-, llvm::detail::operator-=(), llvm::DynamicAPInt::operator-=, llvm::detail::operator/(), llvm::detail::operator/(), llvm::DynamicAPInt::operator/, llvm::DynamicAPInt::operator/, llvm::detail::operator/=(), llvm::DynamicAPInt::operator/=, llvm::Attribute::operator<(), llvm::codeview::operator<(), llvm::codeview::TypeIndex::operator<, llvm::DbgValueLoc::operator<, llvm::detail::operator<(), llvm::detail::operator<(), llvm::DynamicAPInt::operator<, llvm::DynamicAPInt::operator<, llvm::HexagonBlockRanges::IndexRange::operator<(), llvm::object::COFFSymbolRef::operator<, llvm::object::operator<(), llvm::operator<(), llvm::operator<(), llvm::RawLocationWrapper::operator<, llvm::codeview::operator<<(), llvm::NVPTX::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::orc::operator<<(), llvm::rdf::operator<<(), llvm::sandboxir::Action::operator<<, llvm::codeview::operator<=(), llvm::codeview::TypeIndex::operator<=, llvm::detail::operator<=(), llvm::detail::operator<=(), llvm::DynamicAPInt::operator<=, llvm::DynamicAPInt::operator<=, llvm::RawLocationWrapper::operator<=, llvm::pdb::DbiStreamBuilder::operator=(), llvm::pdb::InfoStreamBuilder::operator=(), llvm::AA::operator==(), llvm::AAMDNodes::operator==(), llvm::AppleAcceleratorTable::SameNameIterator::operator==, llvm::Attribute::operator==(), llvm::CHIArg::operator==(), llvm::codeview::operator==(), llvm::codeview::TypeIndex::operator==, llvm::DbgValueLoc::operator==, llvm::DbgValueLocEntry::operator==, llvm::detail::operator==(), llvm::detail::operator==(), llvm::DWARFDebugNames::NameIterator::operator==, llvm::DWARFDebugNames::ValueIterator::operator==, llvm::DynamicAPInt::operator==, llvm::DynamicAPInt::operator==, llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::RawLocationWrapper::operator==, llvm::rdf::RegisterAggr::operator==(), operator==(), llvm::codeview::operator>(), llvm::codeview::TypeIndex::operator>, llvm::detail::operator>(), llvm::detail::operator>(), llvm::DynamicAPInt::operator>, llvm::DynamicAPInt::operator>, llvm::RawLocationWrapper::operator>, llvm::codeview::operator>=(), llvm::codeview::TypeIndex::operator>=, llvm::detail::operator>=(), llvm::detail::operator>=(), llvm::DynamicAPInt::operator>=, llvm::DynamicAPInt::operator>=, llvm::RawLocationWrapper::operator>=, llvm::sys::fs::operator|(), llvm::sys::fs::operator|(), llvm::sys::fs::operator|=(), llvm::sys::fs::operator|=(), slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeShiftInOrChain(), llvm::GCOV::Options::Options(), llvm::SystemZELFFrameLowering::orderFrameObjects(), orderModule(), orderModule(), orderModule(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), llvm::AttrBuilder::overlaps(), llvm::HexagonBlockRanges::IndexRange::overlaps(), llvm::PagedVector< T, PageSize >::PagedVector(), llvm::AArch64::parseArch(), llvm::ARM::parseArch(), llvm::CSKY::parseArch(), llvm::ARM::parseArchExt(), llvm::CSKY::parseArchExt(), llvm::AArch64::parseArchExtension(), llvm::opt::OptTable::parseArgs(), llvm::cl::ParseCommandLineOptions(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::parseWidenableBranch(), performAddDotCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), performFADDCombine(), PerformFADDVCMLACombine(), PerformFMinMaxCombine(), performRNDRCombine(), PerformSETCCCombine(), performUADDVAddCombine(), performUADDVCombine(), performUADDVZextCombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), performVECTOR_SHUFFLECombine(), performVSELECTCombine(), PickMostRelevantLoop(), llvm::PowerOf2Ceil(), predictUseListOrder(), predictUseListOrder(), predictUseListOrder(), PrefixMatcher::PrefixMatcher(), llvm::AbstractAttribute::print(), llvm::DemandedBits::print(), llvm::MemoryDef::print(), llvm::opt::ArgList::print(), llvm::PhysicalRegisterUsageInfo::print(), llvm::rdf::PhysicalRegisterInfo::print(), llvm::rdf::PhysicalRegisterInfo::print(), llvm::Value::print(), llvm::SDNode::print_details(), llvm::NVPTXInstPrinter::printAtomicCode(), llvm::json::Path::Root::printErrorContext(), printFunctionArgExts(), llvm::Pattern::printVariableDefs(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), ProfileFoldOpInit(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::DominatorTreeBase< BlockT, false >::properlyDominates(), llvm::DominatorTreeBase< BlockT, false >::properlyDominates(), llvm::VPDominatorTree::properlyDominates(), llvm::PseudoProbeHandler::PseudoProbeHandler(), r0(), r1(), r2(), r3(), r4(), llvm::ConstantExprKeyType::rangesEqual(), llvm::GVNHoist::rank(), ReachabilityQueryInfo< ToTy >::ReachabilityQueryInfo(), llvm::GOFFObjectWriter::recordRelocation(), llvm::WinCOFFWriter::recordRelocation(), llvm::jitlink::relaxBlock(), llvm::AttrBuilder::remove(), llvm::removeASanIncompatibleFnAttributes(), RemoveAttribute(), llvm::AttrBuilder::removeAttribute(), llvm::AttrBuilder::removeAttribute(), removeUndefDbgLocsFromEntryBlock(), replaceSubOverflowUses(), llvm::AArch64::resolveCPUAlias(), llvm::object::resolveRISCV(), llvm::APIntOps::RoundingSDiv(), llvm::APIntOps::RoundingUDiv(), llvm::DropUnnecessaryAssumesPass::run(), llvm::LoadAndStorePromoter::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::OpenMPOptPass::run(), llvm::TypeFinder::run(), ObjCARCContract::run(), runAttributorLightOnFunctions(), runAttributorOnFunctions(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), runIPSCCP(), llvm::sandboxir::FunctionPass::runOnFunction(), llvm::sandboxir::FunctionPassManager::runOnFunction(), llvm::sandboxir::RegionsFromBBs::runOnFunction(), llvm::sandboxir::RegionsFromMetadata::runOnFunction(), llvm::sandboxir::SeedCollection::runOnFunction(), llvm::sandboxir::BottomUpVec::runOnRegion(), llvm::sandboxir::NullPass::runOnRegion(), llvm::sandboxir::PackReuse::runOnRegion(), llvm::sandboxir::PrintInstructionCount::runOnRegion(), llvm::sandboxir::PrintRegion::runOnRegion(), llvm::sandboxir::RegionPass::runOnRegion(), llvm::sandboxir::RegionPassManager::runOnRegion(), llvm::sandboxir::TransactionAcceptOrRevert::runOnRegion(), llvm::sandboxir::TransactionAlwaysAccept::runOnRegion(), llvm::sandboxir::TransactionAlwaysRevert::runOnRegion(), llvm::sandboxir::TransactionSave::runOnRegion(), runOpWithExpandOnOverflow(), llvm::sampleprof::SampleSorter< LocationT, SampleT >::SampleSorter(), llvm::SaturatingMultiplyAdd(), llvm::APIntOps::ScaleBitMask(), llvm::ScopedHashTable< MachineInstr *, unsigned, MachineInstrExpressionTrait, AllocatorTy >::ScopedHashTable(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< char >, ArrayRef< char > >::serialize(), llvm::rdf::NodeAttrs::set_flags(), llvm::rdf::NodeAttrs::set_kind(), llvm::rdf::NodeAttrs::set_type(), llvm::MCValue::setAddSym(), llvm::pdb::DbiStreamBuilder::setAge(), llvm::pdb::InfoStreamBuilder::setAge(), llvm::GVNPass::ValueTable::setAliasAnalysis(), llvm::MachineBasicBlock::setAlignment(), llvm::MachineBasicBlock::setAlignment(), llvm::MachineFunction::setAlignment(), llvm::sampleprof::SampleContext::setAllAttributes(), llvm::FunctionLoweringInfo::setArgumentFrameIndex(), llvm::MCAsmBackend::setAssembler(), llvm::MCObjectTargetWriter::setAssembler(), llvm::MCObjectWriter::setAssembler(), llvm::WinCOFFWriter::setAssembler(), llvm::sampleprof::SampleContext::setAttribute(), llvm::CallBase::setAttributes(), llvm::GlobalVariable::setAttributes(), llvm::rdf::NodeBase::setAttrs(), setInsertionPoint(), llvm::ISD::ArgFlagsTy::setMemAlign(), llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), simplifyAndInst(), simplifyAndOrWithICmpEq(), simplifyAssociativeBinOp(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), simplifyOp_VL(), simplifyOrInst(), simplifyOrLogic(), simplifyRecipe(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifySwitchWhenUMin(), simplifyTernarylogic(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), simplifyXorInst(), sinkInstruction(), sinkLoopInvariantInstructions(), sinkMinMaxInBB(), llvm::VPlanTransforms::sinkPredicatedStores(), sinkProxyReg(), sinkRecurrenceUsersAfterPrevious(), llvm::coro::sinkSpillUsesAfterCoroBegin(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< char >, ArrayRef< char > >::size(), llvm::yaml::SequenceTraits< ArrayDocNode >::size(), llvm::object::Slice::Slice(), llvm::SmallVector< BitWord >::SmallVector(), llvm::APIntOps::smax(), llvm::APIntOps::smin(), llvm::ConstantRange::smul_fast(), llvm::ConstantRange::smul_sat(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::sampleprof::sortFuncProfiles(), sortGlobalExprs(), sortIntervals(), llvm::DebugLocEntry::sortUniqueValues(), llvm::StringRef::split(), llvm::StringRef::split(), llvm::DINode::splitFlags(), llvm::VETargetLowering::splitMaskArithmetic(), llvm::SSAUpdaterImpl< UpdaterT >::SSAUpdaterImpl(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), startsWith(), STATISTIC(), llvm::storeToSameAddress(), llvm::StrCmpOptionName(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::StringMap(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::StringMap(), stripAndAccumulateOffsets(), StripAttr(), stripLoopMDLoc(), stripNonValidAttributesFromPrototype(), llvm::StrongType< NonRelocatableStringpool, UniqueTag >::StrongType(), llvm::BitTracker::MachineEvaluator::toInt(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::SCCPInstVisitor::trackValueOfArgument(), tryFactorization(), llvm::InstCombinerImpl::tryFactorizationFolds(), tryToMatchAndCreateExtendedReduction(), tryToMatchAndCreateMulAccumulateReduction(), tryToSimplifyOverflowMath(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), llvm::APIntOps::umax(), llvm::APIntOps::umin(), unifyBitWidth(), llvm::AbstractAttribute::update(), llvm::AbstractAttribute::updateImpl(), llvm::UpgradeAttributes(), llvm::UpgradeFunctionAttributes(), upgradeMaskedMove(), upgradeX86IntrinsicCall(), llvm::yaml::MappingTraits< ArchYAML::Archive >::validate(), llvm::validateDelinearizationResult(), llvm::dxil::ValueEnumerator::ValueEnumerator(), llvm::ValueEnumerator::ValueEnumerator(), TransferTracker::ValueToLocSort(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::ObjectSizeOffsetVisitor::visitArgument(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), llvm::WasmException::WasmException(), llvm::ScalarEvolution::willNotOverflow(), llvm::WinCFGuard::WinCFGuard(), llvm::WinException::WinException(), llvm::TimeTraceProfiler::write(), writeArrayData(), writeDIExpression(), llvm::dxil::DXILBitcodeWriter::writeIdentificationBlock(), llvm::InstrProfWriter::writeText(), writeWholeProgramDevirtResolution(), and llvm::ReachingDefInfo::~ReachingDefInfo().
B()
GCRegistry::Add< OcamlGC > B ("ocaml" , "ocaml 3.10-compatible GC") static
Referenced by llvm::APIntOps::abds(), llvm::APIntOps::abdu(), llvm::sandboxir::Action::Action(), llvm::VPlanTransforms::addActiveLaneMask(), llvm::addAllocSizeParamAttr(), addArgumentAttrs(), llvm::AttributeSet::addAttribute(), llvm::AttributeSet::addAttribute(), llvm::addAttributeAtIndex(), llvm::AttributeSet::addAttributes(), llvm::AttributeSet::addAttributes(), llvm::addAttributesAtIndex(), llvm::jitlink::BlockAddressMap::addBlock(), llvm::xray::Profile::addBlock(), llvm::jitlink::BlockAddressMap::addBlocks(), llvm::jitlink::BlockAddressMap::addBlocksWithoutChecking(), llvm::jitlink::BlockAddressMap::addBlockWithoutChecking(), llvm::FoldingSetNodeID::AddBoolean(), addDiscriminators(), llvm::addFnAttributes(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::codeview::DebugLinesSubsection::addLineAndColumnInfo(), llvm::codeview::DebugLinesSubsection::addLineInfo(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::addParamAttribute(), llvm::addParamAttributes(), llvm::CallBase::addParamAttrs(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), llvm::SpillPlacement::addPrefSpill(), addRawAttributeValue(), llvm::LoongArchAsmBackend::addReloc(), llvm::RISCVAsmBackend::addReloc(), llvm::addRetAttributes(), llvm::CallBase::addRetAttrs(), llvm::addRuntimeChecks(), addSaturatedDecorationToIntrinsic(), addSCEVNoOverflow(), llvm::addStringImm(), adjustedSumFreq(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AMDGPUAAResult::alias(), llvm::jitlink::alignToBlock(), llvm::jitlink::alignToBlock(), llvm::lowertypetests::ByteArrayBuilder::allocate(), allocateHSAUserSGPRs(), llvm::AMDGPUCombinerHelper::AMDGPUCombinerHelper(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::object::append(), llvm::jitlink::BasicLayout::apply(), llvm::CombinerHelper::applyCombineBuildUnmerge(), llvm::jitlink::aarch32::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::ppc64::applyFixup(), llvm::jitlink::systemz::applyFixup(), llvm::jitlink::x86::applyFixup(), llvm::jitlink::x86_64::applyFixup(), llvm::jitlink::XCOFFJITLinker_ppc64::applyFixup(), llvm::jitlink::aarch32::applyFixupArm(), llvm::jitlink::aarch32::applyFixupData(), llvm::jitlink::aarch32::applyFixupThumb(), llvm::AMDGPURegisterBankInfo::applyMappingBFE(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), llvm::AMDGPURegisterBankInfo::applyMappingImage(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingMAD_64_32(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::AMDGPURegisterBankInfo::applyMappingSMULU64(), llvm::jitlink::applyPACSigningToModInitPointers(), areConsecutiveOrMatch(), llvm::Bitfield::areContiguous(), llvm::MemoryDepChecker::areDepsSafe(), AreEquivalentAddressValues(), areInSameBB(), llvm::AbstractDependenceGraphBuilder< GraphType >::areNodesMergeable(), llvm::AttributeFuncs::areOutlineCompatible(), llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), aspaceMemCpy(), aspaceMemMove(), aspaceMemSet(), assignSlotsUsingVGPRBlocks(), attemptToFoldSymbolOffsetDifference(), llvm::pdb::BaseClassLayout::BaseClassLayout(), llvm::yaml::basic_collection_iterator< MappingNode, KeyValueNode >::basic_collection_iterator(), llvm::jitlink::BasicLayout::BasicLayout(), llvm::Bitset< AEK_NUM_EXTENSIONS >::Bitset(), BitsProperlyConcatenate(), llvm::BitTracker::BitValue::BitValue(), llvm::BlockDataT< T >::BlockDataT(), llvm::BlockDataT< T >::BlockDataT(), llvm::rdf::DataFlowGraph::build(), llvm::AMDGPULegalizerInfo::buildAbsGlobalAddress(), buildAddr64RSrc(), llvm::SPIRVGlobalRegistry::buildAssignPtr(), llvm::SPIRVGlobalRegistry::buildAssignType(), buildBitFieldInsert(), buildBufferLoad(), buildCopyFromRegs(), buildCopyToRegs(), buildExp(), buildFrameType(), llvm::buildIntrWithMD(), llvm::AMDGPULegalizerInfo::buildLoadInputValue(), buildMul(), llvm::AMDGPULegalizerInfo::buildMultiply(), buildNonAtomicBinOp(), buildOffsetSrc(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), llvm::AMDGPU::buildReadAnyLane(), llvm::AMDGPU::buildReadFirstLane(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), buildReadLane(), buildReadLane(), buildRegSequence(), buildRSRC(), buildSymbolDiff(), buildSymbolDiff(), llvm::AMDGPURegisterBankInfo::buildVCopy(), llvm::hlsl::BindingInfoBuilder::calculateBindingInfo(), llvm::codeview::DebugLinesSubsection::calculateSerializedSize(), calculateVectorIndex(), canBeMerged(), canComputePointerDiff(), canonicalizeBitSelect(), canonicalizeICmpBool(), canonicalizeSaturatedSubtract(), CanShareConstantPoolEntry(), castBufferRsrcArgToV4I32(), castBufferRsrcFromV4I32(), castBufferRsrcToV4I32(), ceilingOfQuotient(), llvm::CfiFunctionIndex::CfiFunctionIndex(), llvm::MMRAMetadata::checkCompatibility(), checkCondition(), llvm::checkedMulAdd(), llvm::checkedMulAddUnsigned(), checkOuterLoopInsts(), llvm::IRSimilarity::IRSimilarityCandidate::checkRelativeLocations(), llvm::BitTracker::RegisterCell::cl(), clampVectorIndex(), llvm::object::MinidumpFile::classof(), llvm::object::XCOFFObjectFile::classof(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::clear(), cloneLoopBlocks(), coalescable(), collectBitParts(), collectBlockUseDef(), llvm::MMRAMetadata::combine(), combineAddSubWithShlAddSub(), combineFMA(), llvm::AA::combineOptionalValuesInAAValueLatice(), combinePExtTruncate(), llvm::CombinerHelper::CombinerHelper(), combineUADDO_CARRYDiamond(), combineVFMADD_VLWithVFNEG_VL(), llvm::codeview::DebugLinesSubsection::commit(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::IRComparer< T >::compare(), llvm::object::compareAddress(), llvm::IRSimilarity::IRSimilarityCandidate::compareCommutativeOperandMapping(), compareNames(), llvm::IRSimilarity::IRSimilarityCandidate::compareNonCommutativeOperandMapping(), llvm::ValueDFS_Compare::comparePHIRelated(), compareSegmentsByOffset(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::BaseIndexOffset::computeAliasing(), llvm::computeDelta(), computeKnownBitsForPRMT(), computeKnownBitsFromCond(), computeKnownBitsFromLerpPattern(), computeKnownFPClassFromCond(), llvm::rdf::Liveness::computeLiveIns(), computePRMT(), llvm::memprof::computeUndriftMap(), computeUnlikelySuccessors(), llvm::MDNode::concatenate(), ConnectEpilog(), ConnectProlog(), llvm::OverflowingBinaryOperator::ConstantExpr, llvm::PossiblyExactOperator::ConstantExpr, llvm::AMDGPURegisterBankInfo::constrainOpWithReadfirstlane(), constrainRegToBank(), llvm::constructSeqOffsettoOrigRowMapping(), llvm::rdf::NodeAttrs::contains(), llvm::RegionBase< Tr >::contains(), llvm::SPIRV::ConvergenceRegion::ConvergenceRegion(), convertCalledGlobals(), convertCallSiteObjects(), convertFSqrtDivIntoFMul(), convertImageAddrToPacked(), convertStrToInt(), llvm::SimplifyCFGOptions::convertSwitchRangeToICmp(), llvm::SimplifyCFGOptions::convertSwitchToArithmetic(), llvm::SimplifyCFGOptions::convertSwitchToLookupTable(), convertToParamAS(), llvm::AArch64RegisterBankInfo::copyCost(), llvm::RegisterBankInfo::copyCost(), llvm::Bitset< AEK_NUM_EXTENSIONS >::count(), llvm::FeatureBitset::count(), llvm::CallBase::CountBundleInputs(), llvm::jitlink::SimpleSegmentAlloc::Create(), llvm::orc::StaticLibraryDefinitionGenerator::Create(), llvm::sampleprof::SampleProfileReader::create(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::SanitizerStatReport::create(), llvm::jitlink::aarch64::createAnonymousPointer(), llvm::jitlink::loongarch::createAnonymousPointer(), llvm::jitlink::ppc64::createAnonymousPointer(), llvm::jitlink::systemz::createAnonymousPointer(), llvm::jitlink::x86::createAnonymousPointer(), llvm::jitlink::x86_64::createAnonymousPointer(), llvm::jitlink::ppc64::createAnonymousPointerJumpStub(), CreateCallEx(), CreateCallEx2(), llvm::AArch64TargetLowering::createComplexDeinterleavingIR(), llvm::ARMTargetLowering::createComplexDeinterleavingIR(), llvm::TargetLoweringBase::createComplexDeinterleavingIR(), createDecorationIntrinsic(), llvm::jitlink::aarch64::createEmptyPointerSigningFunction(), llvm::jitlink::aarch32::GOTBuilder::createEntry(), createExtractsForLiveOuts(), CreateFailBB(), llvm::VPBuilder::createFCmp(), llvm::orc::createHeaderBlock(), llvm::VPBuilder::createICmp(), llvm::VPlanTransforms::createInterleaveGroups(), llvm::jitlink::createLocalHeaderBlock(), createMaskedBitTest(), llvm::createOrderedReduction(), llvm::jitlink::aarch64::createPointerJumpStubBlock(), llvm::jitlink::systemz::createPointerJumpStubBlock(), llvm::jitlink::x86::createPointerJumpStubBlock(), llvm::jitlink::x86_64::createPointerJumpStubBlock(), createPowWithIntegerExponent(), CreatePrologue(), llvm::jitlink::aarch64::createReentryTrampolineBlock(), llvm::jitlink::x86_64::createReentryTrampolineBlock(), createRoundingModeDecoration(), createSaturatedConversionDecoration(), llvm::createStepForVF(), llvm::jitlink::aarch32::createStubArmv7(), llvm::jitlink::aarch32::createStubPrev7(), llvm::jitlink::aarch32::createStubThumbv7(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), llvm::TileInfo::CreateTiledLoops(), CreateTripRemainder(), CreateVScaleMultiple(), llvm::BitTracker::RegisterCell::ct(), DbgGatherSalvagableDVI(), llvm::DCData::DCData(), llvm::DCData::DCData(), DecodeBranchTargetS(), llvm::object::decodeCrel(), DecodeFromCyclicRange(), decodeLLVMAttributesForBitcode(), DecodeSignedOperand(), decompose(), llvm::LLVMContextImpl::deleteTrailingDbgRecords(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), llvm::DFCalculateWorkObject< BlockT >::DFCalculateWorkObject(), llvm::rdf::disjoint(), doList(), dominates(), dominates(), dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::DominatorTreeBase< BlockT, false >::dominates(), llvm::DominatorTreeBase< BlockT, false >::dominates(), llvm::MachineDominatorTree::dominates(), llvm::doSystemDiff(), llvm::RISCV::DemandedFields::doUnion(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::dropOutOfDateUpdates(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), llvm::SuspendCrossingInfo::dump(), llvm::ms_demangle::Demangler::dumpBackReferences(), dumpMachineInstrRangeWithSlotIndex(), llvm::dumpMaxRegPressure(), llvm::objcopy::coff::dumpSection(), llvm::BitTracker::MachineEvaluator::eCLB(), llvm::BitTracker::MachineEvaluator::eCTB(), llvm::object::elf_relocation_iterator::elf_relocation_iterator(), llvm::object::elf_section_iterator::elf_section_iterator(), llvm::object::elf_symbol_iterator::elf_symbol_iterator(), llvm::objcopy::elf::ELFReader::ELFReader(), llvm::object::ELFRelocationRef::ELFRelocationRef(), llvm::object::ELFSectionRef::ELFSectionRef(), llvm::object::ELFSymbolRef::ELFSymbolRef(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), eliminateConstraints(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::DwarfStringPool::emit(), llvm::MCPseudoProbeSections::emit(), emitAssignName(), llvm::emitBCmp(), llvm::emitBinaryFloatFnCall(), llvm::emitBinaryFloatFnCall(), emitBinaryFloatFnCallHelper(), llvm::BitstreamWriter::emitBlob(), llvm::emitCalloc(), llvm::emitFPutC(), llvm::emitFPutS(), llvm::AsmPrinter::emitFunctionBody(), llvm::emitFWrite(), llvm::emitHotColdNew(), llvm::emitHotColdNewAligned(), llvm::emitHotColdNewAlignedNoThrow(), llvm::emitHotColdNewNoThrow(), llvm::emitHotColdSizeReturningNew(), llvm::emitHotColdSizeReturningNewAligned(), llvm::LoopVectorizationPlanner::emitInvalidCostRemarks(), llvm::AArch64InstrInfo::emitLdStWithAddr(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCCpy(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitMemCpyChk(), llvm::emitMemPCpy(), llvm::emitMemRChr(), emitOrXorXorTree(), llvm::HexagonFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::emitPutChar(), llvm::emitPutS(), emitReciprocalU64(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::emitStpCpy(), llvm::emitStpNCpy(), llvm::emitStrCat(), llvm::emitStrChr(), llvm::emitStrCpy(), llvm::emitStrDup(), llvm::emitStrLCat(), llvm::emitStrLCpy(), llvm::emitStrLen(), llvm::emitStrNCat(), llvm::emitStrNCmp(), llvm::emitStrNCpy(), emitTransformedIndex(), llvm::emitUnaryFloatFnCall(), llvm::emitUnaryFloatFnCall(), emitUnaryFloatFnCallHelper(), llvm::emitVSNPrintf(), llvm::emitVSPrintf(), llvm::emitWcsLen(), llvm::ELF::encodeCrel(), llvm::SparseMultiSet< PhysRegSUOper, MCRegUnit, MCRegUnitToIndex, uint16_t >::equal_range(), llvm::rdf::PhysicalRegisterInfo::equal_to(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::InstrProfLookupTrait::EqualKey(), llvm::memprof::CallStackLookupTrait::EqualKey(), llvm::memprof::FrameLookupTrait::EqualKey(), llvm::memprof::RecordLookupTrait::EqualKey(), llvm::sys::fs::equivalent(), llvm::sys::fs::equivalent(), llvm::sys::fs::equivalent(), llvm::sys::fs::file_status::equivalent, llvm::vfs::FileSystem::equivalent(), equivalentAddressValues(), llvm::rdf::DeadCodeElimination::erase(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateSymbolicAdd(), llvm::VPWidenRecipe::execute(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::BitstreamWriter::ExitBlock(), llvm::WindowScheduler::expand(), expandBinOp(), expandFloatDotIntrinsic(), expandFRem(), expandFSH64(), expandFunnelShiftIntrinsic(), expandIntegerDotIntrinsic(), expandProtectedFieldPtr(), expandToSwitch(), expandUDivOrURem(), expandUsubSat(), extendLow32IntoHigh32(), llvm::BitTracker::MachineEvaluator::eXTR(), llvm::BitTracker::RegisterCell::extract(), extractF64Exponent(), factorizeMinMaxTree(), llvm::IRBuilderBase::FastMathFlagGuard::FastMathFlagGuard(), llvm::FeatureBitArray::FeatureBitArray(), llvm::FeatureBitset::FeatureBitset(), llvm::gsym::FileEntry::FileEntry(), llvm::gsym::FileWriter::FileWriter(), llvm::BitTracker::RegisterCell::fill(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::opt::ArgList::filtered(), llvm::opt::ArgList::filtered_reverse(), llvm::AccelTableBase::finalize(), llvm::objcopy::elf::ASCIIHexWriter::finalize(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::jitlink::finalizeRelax(), llvm::DomSetType< BasicBlock, false >::find(), llvm::DomSetType< BasicBlock, false >::find(), llvm::MachineDominanceFrontier::find(), llvm::MachineDominanceFrontier::find(), findCFILocation(), findCommonType(), findForkedSCEVs(), llvm::coverage::MCDCRecord::findIndependencePairs(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), findRecipeWithMinAlign(), llvm::findValuesAffectedByCondition(), llvm::SanitizerStatReport::finish(), first_use_of_in_block(), firstCommonClass(), llvm::AMDGPULegalizerInfo::fixStoreSourceType(), floorOfQuotient(), llvm::AMDGPULibCalls::fold(), foldAbsDiff(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldAndToXor(), foldComplexAndOrPatterns(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOfUAddOv(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::foldICmpWithZero(), foldIntrinsicUsingDistributiveLaws(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldMulHigh(), foldNegativePower2AndShiftedMask(), foldNeonShift(), foldNotXor(), foldOrToXor(), foldPowerOf2AndShiftedMask(), foldReduceOperandViaVQDOT(), foldSelectCmpBitcasts(), llvm::InstCombinerImpl::foldSelectEqualityTest(), foldSelectICmpAndAnd(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectWithExtremeEqCond(), llvm::InstCombinerImpl::foldSPFofSPF(), llvm::InstCombinerImpl::foldSquareSumFP(), llvm::InstCombinerImpl::foldSquareSumInt(), foldUnsignedUnderflowCheck(), llvm::InstCombinerImpl::foldUsingDistributiveLaws(), foldXorToXor(), llvm::format_provider< bool >::format(), llvm::format_provider< codeview::GloballyHashedType >::format(), llvm::FormattedBytes::FormattedBytes(), llvm::SimplifyCFGOptions::forwardSwitchCondToPhi(), llvm::DIExpression::fragmentCmp(), llvm::DIExpression::fragmentsOverlap(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), fullyContains(), gcd(), llvm::detail::gcd(), llvm::detail::SlowDynamicAPInt::gcd, llvm::DynamicAPInt::gcd, llvm::GCOVBuffer::GCOVBuffer(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), llvm::IRComparer< T >::generateFunctionData(), generateGatherLanePattern(), llvm::msf::MSFBuilder::generateLayout(), generateReproducer(), llvm::AttributeSet::get(), llvm::AttributeSetNode::get(), llvm::get(), llvm::VarBitInit::get(), llvm::VPTransformState::get(), llvm::ScalarEvolution::getAddExpr(), llvm::HexagonFrameLowering::getAlignaInstr(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::objcarc::getAttachedARCFunction(), llvm::VarBitInit::getBit(), getBitcastWiderVectorElementOffset(), llvm::jitlink::LinkGraph::getBlockContentReader(), llvm::jitlink::LinkGraph::getBlockContentWriter(), llvm::jitlink::BlockAddressMap::getBlockCovering(), getBlockName(), llvm::SIScheduleBlockCreator::getBlocks(), llvm::getBranchProbability(), llvm::cas::ondisk::InternalRefArrayRef::getBuffer(), llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion(), llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion(), llvm::RegionInfoBase< RegionTraits< MachineFunction > >::getCommonRegion(), llvm::TargetRegisterInfo::getCommonSubClass(), getConstraintFromMemoryAccess(), llvm::object::ResourceSectionRef::getContents(), llvm::vfs::FileSystem::getCurrentWorkingDirectory(), llvm::Instruction::getDbgReinsertionPosition(), llvm::getDeadRegState(), llvm::getDebugRegState(), llvm::getDefRegState(), llvm::coverage::MCDCRecord::TestVector::getDifferences(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), llvm::codegen::getEnableBBAddrMap(), llvm::NonRelocatableStringpool::getEntriesForEmission(), llvm::GraphTraits< Inverse< VPBlockBase * > >::getEntryNode(), llvm::MachineBasicBlock::getFirstInstrTerminator(), llvm::MachineBasicBlock::getFirstTerminator(), getFPBinOp(), getFPTernOp(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::StatepointOpers::getGCPointerMap(), getHashValueImpl(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), llvm::AMDGPULegalizerInfo::getImplicitArgPtr(), getImplicitCondFromMI(), llvm::getImplRegState(), llvm::SlotIndexes::getIndexBefore(), getInstCondition(), llvm::getInternalReadRegState(), llvm::HexagonSubtarget::getIntrinsicId(), getIntToFPVal(), getIntTy(), llvm::AMDGPULegalizerInfo::getKernargParameterPtr(), llvm::getKillRegState(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::AMDGPULegalizerInfo::getLDSKernelId(), getLeastCommonType(), getLiveInRegsAt(), getLiveOutRegsAt(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), getMad(), llvm::DILocation::getMaskedDiscriminator(), getMaskedICmpType(), getMaskedTypeForICmpPair(), llvm::CmpPredicate::getMatching(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::X86RegisterInfo::getMatchingSuperRegClass(), getMaxWidth(), llvm::MDNode::getMergedCalleeTypeMetadata(), llvm::MDNode::getMergedCallsiteMetadata(), llvm::DILocation::getMergedLocation(), llvm::MDNode::getMergedMemProfMetadata(), llvm::MDNode::getMergedProfMetadata(), llvm::GlobalValue::getMinUnnamedAddr(), llvm::sandboxir::GlobalValue::getMinUnnamedAddr(), getMinVisibility(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericAlignmentOrDereferenceable(), llvm::MDNode::getMostGenericFPMath(), llvm::MDNode::getMostGenericNoaliasAddrspace(), llvm::MDNode::getMostGenericRange(), llvm::MDNode::getMostGenericTBAA(), llvm::APIntOps::GetMostSignificantDifferentBit(), llvm::rdf::Liveness::getNearestAliasedRef(), getNonDebugInstr(), llvm::jitlink::getOrCreateLocalMachOHeader(), llvm::getOrInsertLibFunc(), llvm::DomTreeNodeTraits< VPBlockBase >::getParent(), llvm::HvxSelector::getPerfectCompletions(), getPRMT(), getPRMT(), GetQuadraticEquation(), llvm::getRenamableRegState(), getRuntimeLoopRemainder(), getRuntimeLoopUnits(), llvm::getRuntimeVF(), llvm::AMDGPULegalizerInfo::getScaledLogInput(), llvm::GCNIterativeScheduler::getSchedulePressure(), llvm::jitlink::SimpleSegmentAlloc::getSegInfo(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), getSizeTTy(), VectorSlice::getSlicedVal(), llvm::GenericCycleInfo< ContextT >::getSmallestCommonCycle(), llvm::GenericCycleInfo< ContextT >::getSmallestCommonCycle(), llvm::GenericCycleInfo< MachineSSAContext >::getSmallestCommonCycle(), llvm::GenericCycleInfo< MachineSSAContext >::getSmallestCommonCycle(), llvm::LoopInfoBase< BlockT, LoopT >::getSmallestCommonLoop(), llvm::LoopInfoBase< BlockT, LoopT >::getSmallestCommonLoop(), llvm::LoopInfoBase< BasicBlock, Loop >::getSmallestCommonLoop(), llvm::LoopInfoBase< BasicBlock, Loop >::getSmallestCommonLoop(), getSqrtCall(), getStableFunctionEntries(), getStackGuard(), getStatepointArgs(), getSymbolOffsetImpl(), llvm::VPBuilder::getToInsertAfter(), llvm::LLVMContextImpl::getTrailingDbgRecords(), getTrueOrFalseValue(), llvm::getUndefRegState(), getUnmergePieces(), llvm::VPlan::getVectorLoopRegion(), llvm::VPlan::getVectorLoopRegion(), getZeroPaddedAdd(), llvm::object::GOFFSymbolRef::GOFFSymbolRef(), llvm::jitlink::COFFLinkGraphBuilder::graphifySections(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::graphifySections(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::graphifySymbols(), greaterWithBias(), llvm::APIntOps::GreatestCommonDivisor(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::InLineChangePrinter::handleFunctionCompare(), handleMemIntrinsicPtrUse(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::GenericUniformityAnalysisImpl< ContextT >::hasDivergentTerminator(), llvm::GenericUniformityInfo< ContextT >::hasDivergentTerminator(), llvm::GenericUniformityInfo< SSAContext >::hasDivergentTerminator(), llvm::HexagonInstrInfo::hasEHLabel(), llvm::ReachingDefInfo::hasSameReachingDef(), HasSameValue(), llvm::hasSingleElement(), llvm::HexagonInstrInfo::hasUncondBranch(), llvm::SelectionDAG::haveNoCommonBitsSet(), haveNoCommonBitsSetCommutative(), haveNoCommonBitsSetSpecialCases(), hoistAndMergeSGPRInits(), llvm::SimplifyCFGOptions::hoistCommonInsts(), llvm::SimplifyCFGOptions::hoistLoadsStoresWithCondFaulting(), llvm::VPlanTransforms::hoistPredicatedLoads(), hoistPreviousBeforeFORUsers(), llvm::rdf::NodeAllocator::id(), llvm::jitlink::BlockAddressMap::includeAllBlocks(), llvm::jitlink::BlockAddressMap::includeNonNull(), inferDomainOfAffine(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::mca::initializeUsedResources(), llvm::jitlink::initRelaxAux(), llvm::BitTracker::RegisterCell::insert(), InsertCall(), llvm::HexagonFrameLowering::insertCFIInstructions(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), llvm::IRBuilderBase::InsertPointGuard::InsertPointGuard(), llvm::VPBuilder::InsertPointGuard::InsertPointGuard(), insertSinCosCall(), InsertStackProtectors(), instCombineMaxMinNM(), instCombineSVEUzp1(), instCombineSVEZip(), llvm::HexagonBlockRanges::InstrIndexMap::InstrIndexMap(), llvm::FPMathOperator::Instruction, llvm::ScalarEvolution::instructionCouldExistWithOperands(), llvm::DbgVariableFragmentInfo::intersect(), llvm::FMFSource::intersect(), llvm::MDNode::intersect(), llvm::ResourceSegments::intersects(), llvm::VPlanTransforms::introduceMasksAndLinearize(), is_empty(), llvm::InstructionOrdering::isBefore(), IsBetterCanonical(), isClampZeroToOne(), llvm::IRSimilarity::isClose(), isCommutableVPERMV3Instruction(), llvm::isConsecutiveAccess(), isContiguous(), isContiguous(), llvm::jitlink::isCStringBlock(), llvm::SlotIndex::isEarlierEqualInstr(), llvm::SlotIndex::isEarlierInstr(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::DenseMapInfo< AA::RangeTy >::isEqual(), llvm::DenseMapInfo< at::VarRecord >::isEqual(), llvm::DenseMapInfo< const SwitchSuccWrapper * >::isEqual(), llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex >::isEqual(), llvm::DenseMapInfo< DebugVariable >::isEqual(), llvm::DenseMapInfo< DIExpression::FragmentInfo >::isEqual(), llvm::DenseMapInfo< LocIdx >::isEqual(), llvm::DenseMapInfo< object::SectionRef >::isEqual(), llvm::DenseMapInfo< SlotWithTag >::isEqual(), llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::isEqual(), llvm::DenseMapInfo< ValueIDNum >::isEqual(), llvm::SelectionDAG::isEqualTo(), llvm::vputils::isHeaderMask(), isHorizontalBinOp(), isImpliedCondICmps(), isInstructionPairAdd(), isInstructionPairMul(), IsInterestingCmp(), llvm::LiveRangeCalc::isJointlyDominated(), llvm::isKnownInversion(), llvm::isKnownNegation(), isKnownNonEqual(), isLoadOrMultipleLoads(), isMinMaxCmpSelectEliminable(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), isNonEqualPointersWithRecursiveGEP(), llvm::isOverflowIntrinsicNoWrap(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachable(), llvm::APFloatBase::isRepresentableBy(), llvm::SlotIndex::isSameInstr(), isSameScalarConst(), isSignExtendedW(), isSignExtendedW(), llvm::IRSimilarity::IRSimilarityCandidate::isSimilar(), isSortedByValueNo(), llvm::AArch64_AM::isSVEMoveMaskPreferredLogicalImmediate(), llvm::AMDGPUMachineModuleInfo::isSyncScopeInclusion(), llvm::isTheSameCluster(), jumpTableHasOtherUses(), llvm::detail::lcm(), llvm::DynamicAPInt::lcm, llvm::LegalizationArtifactCombiner::LegalizationArtifactCombiner(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeBufferAtomic(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBufferStore(), llvm::AMDGPULegalizerInfo::legalizeBuildVector(), llvm::AMDGPULegalizerInfo::legalizeBVHDualOrBVH8IntersectRayIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeBVHIntersectRayIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeConstHwRegRead(), llvm::AMDGPULegalizerInfo::legalizeCTLZ_CTTZ(), llvm::AMDGPULegalizerInfo::legalizeCTLZ_ZERO_UNDEF(), llvm::AMDGPULegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeDebugTrap(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFceil(), llvm::AMDGPULegalizerInfo::legalizeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV16(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFDIVFastIntrin(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFExp10Unsafe(), llvm::AMDGPULegalizerInfo::legalizeFExp2(), llvm::AMDGPULegalizerInfo::legalizeFExpUnsafe(), llvm::AMDGPULegalizerInfo::legalizeFExpUnsafeImpl(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFFREXP(), llvm::AMDGPULegalizerInfo::legalizeFlog2(), llvm::AMDGPULegalizerInfo::legalizeFlogCommon(), llvm::AMDGPULegalizerInfo::legalizeFlogUnsafe(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFPow(), llvm::AMDGPULegalizerInfo::legalizeFPTOI(), llvm::AMDGPULegalizerInfo::legalizeFrem(), llvm::AMDGPULegalizerInfo::legalizeFroundeven(), llvm::AMDGPULegalizerInfo::legalizeFSQRT(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF16(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF32(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF64(), llvm::AMDGPULegalizerInfo::legalizeGetFPEnv(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeIsAddrSpace(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeKernargMemParameter(), llvm::AMDGPULegalizerInfo::legalizeLaneOp(), llvm::AMDGPULegalizerInfo::legalizeLDSKernelId(), llvm::AMDGPULegalizerInfo::legalizeLoad(), llvm::AMDGPULegalizerInfo::legalizeMul(), llvm::AMDGPULegalizerInfo::legalizePointerAsRsrcIntrin(), llvm::AMDGPULegalizerInfo::legalizePreloadedArgIntrin(), llvm::LegalizerHelper::LegalizerHelper(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeSBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeSBufferPrefetch(), llvm::AMDGPULegalizerInfo::legalizeSetFPEnv(), llvm::AMDGPULegalizerInfo::legalizeSignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::AMDGPULegalizerInfo::legalizeStackSave(), llvm::AMDGPULegalizerInfo::legalizeStore(), llvm::AMDGPULegalizerInfo::legalizeTrap(), llvm::AMDGPULegalizerInfo::legalizeTrapEndpgm(), llvm::AMDGPULegalizerInfo::legalizeTrapHsa(), llvm::AMDGPULegalizerInfo::legalizeTrapHsaQueuePtr(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM64Impl(), llvm::cfg::LegalizeUpdates(), llvm::AMDGPULegalizerInfo::legalizeWaveID(), llvm::AMDGPULegalizerInfo::legalizeWorkGroupId(), llvm::AMDGPULegalizerInfo::legalizeWorkitemIDIntrinsic(), llvm::rdf::PhysicalRegisterInfo::less(), llvm::HexagonInstr::lessCore(), llvm::HexagonInstr::lessCVI(), llvm::HexagonResource::lessUnits(), llvm::HexagonResource::lessWeight(), llvm::LetRecord::LetRecord(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVMBuildAdd(), LLVMBuildAddrSpaceCast(), LLVMBuildAggregateRet(), LLVMBuildAlloca(), LLVMBuildAnd(), LLVMBuildArrayAlloca(), LLVMBuildArrayMalloc(), LLVMBuildAShr(), LLVMBuildAtomicCmpXchg(), LLVMBuildAtomicCmpXchgSyncScope(), LLVMBuildAtomicRMW(), LLVMBuildAtomicRMWSyncScope(), LLVMBuildBinOp(), LLVMBuildBitCast(), LLVMBuildBr(), LLVMBuildCall2(), LLVMBuildCallBr(), LLVMBuildCallWithOperandBundles(), LLVMBuildCast(), LLVMBuildCatchPad(), LLVMBuildCatchRet(), LLVMBuildCatchSwitch(), LLVMBuildCleanupPad(), LLVMBuildCleanupRet(), LLVMBuildCondBr(), LLVMBuildExactSDiv(), LLVMBuildExactUDiv(), LLVMBuildExtractElement(), LLVMBuildExtractValue(), LLVMBuildFAdd(), LLVMBuildFCmp(), LLVMBuildFDiv(), LLVMBuildFence(), LLVMBuildFenceSyncScope(), LLVMBuildFMul(), LLVMBuildFNeg(), LLVMBuildFPCast(), LLVMBuildFPExt(), LLVMBuildFPToSI(), LLVMBuildFPToUI(), LLVMBuildFPTrunc(), LLVMBuildFree(), LLVMBuildFreeze(), LLVMBuildFRem(), LLVMBuildFSub(), LLVMBuildGEP2(), LLVMBuildGEPWithNoWrapFlags(), LLVMBuildGlobalString(), LLVMBuildGlobalStringPtr(), LLVMBuildICmp(), LLVMBuildInBoundsGEP2(), LLVMBuildIndirectBr(), LLVMBuildInsertElement(), LLVMBuildInsertValue(), LLVMBuildIntCast(), LLVMBuildIntCast2(), LLVMBuildIntToPtr(), LLVMBuildInvoke2(), LLVMBuildInvokeWithOperandBundles(), LLVMBuildIsNotNull(), LLVMBuildIsNull(), LLVMBuildLandingPad(), LLVMBuildLoad2(), LLVMBuildLShr(), LLVMBuildMalloc(), LLVMBuildMemCpy(), LLVMBuildMemMove(), LLVMBuildMemSet(), LLVMBuildMul(), LLVMBuildNeg(), LLVMBuildNot(), LLVMBuildNSWAdd(), LLVMBuildNSWMul(), LLVMBuildNSWNeg(), LLVMBuildNSWSub(), LLVMBuildNUWAdd(), LLVMBuildNUWMul(), LLVMBuildNUWNeg(), LLVMBuildNUWSub(), LLVMBuildOr(), LLVMBuildPhi(), LLVMBuildPointerCast(), LLVMBuildPtrDiff2(), LLVMBuildPtrToInt(), LLVMBuildResume(), LLVMBuildRet(), LLVMBuildRetVoid(), LLVMBuildSDiv(), LLVMBuildSelect(), LLVMBuildSExt(), LLVMBuildSExtOrBitCast(), LLVMBuildShl(), LLVMBuildShuffleVector(), LLVMBuildSIToFP(), LLVMBuildSRem(), LLVMBuildStore(), LLVMBuildStructGEP2(), LLVMBuildSub(), LLVMBuildSwitch(), LLVMBuildTrunc(), LLVMBuildTruncOrBitCast(), LLVMBuildUDiv(), LLVMBuildUIToFP(), LLVMBuildUnreachable(), LLVMBuildURem(), LLVMBuildVAArg(), LLVMBuildXor(), LLVMBuildZExt(), LLVMBuildZExtOrBitCast(), LLVMInitializeAMDGPUAsmParser(), LLVMInitializeARMAsmParser(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMInitializeRISCVAsmParser(), LLVMInitializeRISCVAsmPrinter(), LLVMInitializeRISCVTarget(), LLVMInitializeRISCVTargetInfo(), LLVMInitializeSparcAsmParser(), LLVMSetNormalDest(), LLVMSetUnwindDest(), llvm::coverage::CoverageMapping::load(), llvm::object::ResourceSectionRef::load(), loadFDRLog(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::ValueDFS_Compare::localComesBefore(), lookForCompound(), llvm::LegalizerHelper::lowerBitCount(), lowerBuildVectorViaPacking(), llvm::AMDGPUTargetLowering::LowerF64ToF16Safe(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), lowerLoadRelative(), LowerMUL(), LowerMULH(), LowerMULO(), llvm::jitlink::aarch64::lowerPointer64AuthEdgesToSigningFunction(), lowerPrmtIntrinsic(), llvm::AMDGPUCallLowering::lowerReturn(), LowervXi8MulWithUNPCK(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), maintainNoSignedWrap(), llvm::make_filter_range(), llvm::MachineFunction::makeDebugValueSubstitution(), llvm::makeGuardControlFlowExplicit(), llvm::jitlink::makeTargetOutOfRangeError(), markAsImported(), llvm::rdf::DataFlowGraph::markBlock(), llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::match(), matchAccessTags(), llvm::CombinerHelper::matchAddEToAddO(), llvm::CombinerHelper::matchAddOfVScale(), llvm::CombinerHelper::matchAddOverflow(), llvm::CombinerHelper::matchAndOrDisjointMask(), llvm::CombinerHelper::matchCanonicalizeFCmp(), llvm::CombinerHelper::matchCanonicalizeICmp(), llvm::CombinerHelper::matchCastOfBuildVector(), llvm::CombinerHelper::matchCastOfSelect(), llvm::CombinerHelper::matchCombineExtractedVectorLoad(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineLoadWithAndMask(), llvm::CombinerHelper::matchCombineSubToAdd(), llvm::CombinerHelper::matchCombineUnmergeUndef(), llvm::CombinerHelper::matchCommuteShift(), matchDeMorgansLaws(), matchesAdd(), matchesOr(), matchesSquareSum(), llvm::CombinerHelper::matchExtOfExt(), llvm::CombinerHelper::matchExtractVectorElement(), llvm::CombinerHelper::matchExtractVectorElementWithBuildVector(), llvm::CombinerHelper::matchExtractVectorElementWithBuildVectorTrunc(), llvm::CombinerHelper::matchExtractVectorElementWithDifferentIndices(), llvm::CombinerHelper::matchExtractVectorElementWithShuffleVector(), llvm::CombinerHelper::matchFoldAMinusC1MinusC2(), llvm::CombinerHelper::matchFoldAMinusC1PlusC2(), llvm::CombinerHelper::matchFoldAPlusC1MinusC2(), llvm::CombinerHelper::matchFoldC1Minus2MinusC2(), llvm::CombinerHelper::matchFoldC2MinusAPlusC1(), llvm::CombinerHelper::matchFreezeOfSingleMaybePoisonOperand(), llvm::CombinerHelper::matchICmpToLHSKnownBits(), llvm::CombinerHelper::matchInsertVectorElementOOB(), llvm::CombinerHelper::matchMergeXAndUndef(), llvm::CombinerHelper::matchMergeXAndZero(), matchMinMaxOfMinMax(), llvm::CombinerHelper::matchMulOBy0(), llvm::CombinerHelper::matchMulOBy2(), llvm::CombinerHelper::matchMulOfVScale(), llvm::CombinerHelper::matchNarrowBinop(), llvm::CombinerHelper::matchNarrowBinopFeedingAnd(), llvm::CombinerHelper::matchNonNegZext(), llvm::CombinerHelper::matchOrShiftToFunnelShift(), llvm::CombinerHelper::matchOverlappingAnd(), llvm::CombinerHelper::matchReassocConstantInnerLHS(), llvm::CombinerHelper::matchReassocConstantInnerRHS(), llvm::CombinerHelper::matchReassocFoldConstantsInSubTree(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchRedundantSextInReg(), matchSelectAddSub(), llvm::CombinerHelper::matchSelectIMinMax(), matchSelectWithOptionalNotCond(), llvm::CombinerHelper::matchSextOfTrunc(), llvm::CombinerHelper::matchShlOfVScale(), llvm::CombinerHelper::matchShuffleDisjointMask(), llvm::CombinerHelper::matchShuffleUndefRHS(), llvm::CombinerHelper::matchSimplifyNegMinMax(), llvm::CombinerHelper::matchSubAddSameReg(), llvm::CombinerHelper::matchSuboCarryOut(), llvm::CombinerHelper::matchSubOfVScale(), llvm::CombinerHelper::matchTruncateOfExt(), matchUAddWithOverflowConstantEdgeCases(), llvm::CombinerHelper::matchUnmergeValuesAnyExtBuildVector(), llvm::CombinerHelper::matchZextOfTrunc(), llvm::orc::SectCreateMaterializationUnit::materialize(), llvm::maximum(), llvm::maximumnum(), llvm::maxnum(), mayLoopAccessLocation(), mayLoopAccessLocation(), llvm::MCAsmMacro::MCAsmMacro(), llvm::MCAsmMacro::MCAsmMacro(), memChrToCharCompare(), memoryIsNotModifiedBetween(), llvm::AttrBuilder::merge(), merge(), MergeAliasResults(), mergeComparisons(), llvm::AbstractDependenceGraphBuilder< GraphType >::mergeNodes(), llvm::DDGBuilder::mergeNodes(), llvm::InstrProfWriter::mergeProfileKind(), llvm::jitlink::LinkGraph::mergeSections(), MergeSeqs(), mergeVectorRegsToResultRegs(), llvm::MIBundleBuilder::MIBundleBuilder(), llvm::MinAlign(), llvm::MinAlign(), llvm::minimum(), llvm::minimumnum(), llvm::minnum(), minusSCEVNoSignedOverflow(), llvm::MMRAMetadata::MMRAMetadata(), llvm::Module::ModuleFlagEntry::ModuleFlagEntry(), llvm::Instruction::moveAfter(), llvm::Instruction::moveBeforePreserving(), llvm::Instruction::moveBeforePreserving(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::moveFrom(), moveInstrOut(), mulSCEVNoSignedOverflow(), mulSCEVOverflow(), llvm::ConstantRange::multiply(), llvm::detail::DoubleAPFloat::multiply(), llvm::LegalizerHelper::narrowScalarCTLZ(), llvm::LegalizerHelper::narrowScalarCTTZ(), llvm::LegalizerHelper::narrowScalarFLDEXP(), narrowSDivOrSRem(), narrowUDivOrURem(), nearest_common_dominatee(), nearest_common_dominator(), llvm::SimplifyCFGOptions::needCanonicalLoops(), llvm::onlyReadsMemory(), llvm::IRBuilderBase::OperandBundlesGuard::OperandBundlesGuard(), llvm::AA::operator!=(), llvm::AttrBuilder::operator!=(), llvm::codeview::operator!=(), llvm::codeview::TypeIndex::operator!=, llvm::detail::operator!=(), llvm::detail::operator!=(), llvm::DWARFDebugNames::NameIterator::operator!=, llvm::DWARFDebugNames::ValueIterator::operator!=, llvm::DynamicAPInt::operator!=, llvm::DynamicAPInt::operator!=, llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::RawLocationWrapper::operator!=, llvm::detail::operator%(), llvm::detail::operator%(), llvm::DynamicAPInt::operator%, llvm::DynamicAPInt::operator%, llvm::detail::operator%=(), llvm::DynamicAPInt::operator%=, EarlierIssuingCycle::operator()(), llvm::CompSpillWeight::operator()(), llvm::deref< T >::operator()(), llvm::jitlink::DWARFRecordSectionSplitter::operator()(), llvm::jitlink::EHFrameEdgeFixer::operator()(), llvm::jitlink::SEHFrameKeepAlivePass::operator()(), llvm::rdf::RegisterRefEqualTo::operator()(), llvm::rdf::RegisterRefLess::operator()(), llvm::SystemZTargetStreamer::CmpMCInst::operator()(), llvm::ValueDFS_Compare::operator()(), llvm::detail::operator*(), llvm::detail::operator*(), llvm::DynamicAPInt::operator*, llvm::DynamicAPInt::operator*, llvm::detail::operator*=(), llvm::DynamicAPInt::operator*=, llvm::detail::operator+(), llvm::detail::operator+(), llvm::DynamicAPInt::operator+, llvm::DynamicAPInt::operator+, llvm::detail::operator+=(), llvm::DynamicAPInt::operator+=, llvm::codeview::TypeIndex::operator-, llvm::detail::operator-(), llvm::detail::operator-(), llvm::DynamicAPInt::operator-, llvm::DynamicAPInt::operator-, llvm::detail::operator-=(), llvm::DynamicAPInt::operator-=, llvm::detail::operator/(), llvm::detail::operator/(), llvm::DynamicAPInt::operator/, llvm::DynamicAPInt::operator/, llvm::detail::operator/=(), llvm::DynamicAPInt::operator/=, llvm::codeview::operator<(), llvm::codeview::TypeIndex::operator<, llvm::DbgValueLoc::operator<, llvm::detail::operator<(), llvm::detail::operator<(), llvm::DynamicAPInt::operator<, llvm::DynamicAPInt::operator<, llvm::HexagonInstr::operator<(), llvm::object::COFFSymbolRef::operator<, llvm::object::operator<(), llvm::operator<(), llvm::operator<(), llvm::RawLocationWrapper::operator<, llvm::jitlink::operator<<(), llvm::rdf::operator<<(), llvm::codeview::operator<=(), llvm::codeview::TypeIndex::operator<=, llvm::detail::operator<=(), llvm::detail::operator<=(), llvm::DynamicAPInt::operator<=, llvm::DynamicAPInt::operator<=, llvm::RawLocationWrapper::operator<=, llvm::pdb::DbiStreamBuilder::operator=(), llvm::pdb::InfoStreamBuilder::operator=(), llvm::AA::operator==(), llvm::AppleAcceleratorTable::SameNameIterator::operator==, llvm::AttrBuilder::operator==(), llvm::codeview::operator==(), llvm::codeview::TypeIndex::operator==, llvm::DbgValueLoc::operator==, llvm::DbgValueLocEntry::operator==, llvm::detail::operator==(), llvm::detail::operator==(), llvm::DWARFDebugNames::NameIterator::operator==, llvm::DWARFDebugNames::ValueIterator::operator==, llvm::DynamicAPInt::operator==, llvm::DynamicAPInt::operator==, llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::RawLocationWrapper::operator==, operator==(), llvm::codeview::operator>(), llvm::codeview::TypeIndex::operator>, llvm::detail::operator>(), llvm::detail::operator>(), llvm::DynamicAPInt::operator>, llvm::DynamicAPInt::operator>, llvm::RawLocationWrapper::operator>, llvm::codeview::operator>=(), llvm::codeview::TypeIndex::operator>=, llvm::detail::operator>=(), llvm::detail::operator>=(), llvm::DynamicAPInt::operator>=, llvm::DynamicAPInt::operator>=, llvm::RawLocationWrapper::operator>=, llvm::sys::fs::operator|(), llvm::sys::fs::operator|(), llvm::sys::fs::operator|=(), llvm::sys::fs::operator|=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator~(), llvm::FeatureBitset::operator~(), optimizeBinaryDoubleFP(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), optimizeDoubleFP(), optimizeEarlyExitInductionUser(), slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::jitlink::systemz::optimizeGOTAndStubAccesses(), llvm::jitlink::x86::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), optimizeLatchExitInductionUser(), optimizeMemCmpConstantSize(), optimizeMemCmpVarSize(), optimizeModularFormat(), optimizeSection(), optimizeSymmetricCall(), optimizeUnaryDoubleFP(), llvm::GCOV::Options::Options(), llvm::SystemZELFFrameLowering::orderFrameObjects(), llvm::outliner::OutlinedFunction::OutlinedFunction(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), packImage16bitOpsToDwords(), parsePhysicalReg(), llvm::object::Parser::Parser(), parseWholeProgramDevirtResolutionByArg(), llvm::parseWidenableBranch(), llvm::peelLoop(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), PeepholePPC64ZExtGather(), performFADDCombine(), PerformFADDVCMLACombine(), PerformFMinMaxCombine(), performMulRdsvlCombine(), performRNDRCombine(), PerformSETCCCombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), performVECTOR_SHUFFLECombine(), performVSELECTCombine(), llvm::GVNExpression::PHIExpression::PHIExpression(), PickMostRelevantLoop(), llvm::CallBase::populateBundleOperandInfos(), llvm::HexagonInstrInfo::PredicateInstruction(), PrefixMatcher::PrefixMatcher(), llvm::jitlink::CompactUnwindManager< CURecTraits >::prepareForPrune(), llvm::lowertypetests::BitSetInfo::print(), llvm::PhysicalRegisterUsageInfo::print(), llvm::jitlink::printEdge(), printName(), printName(), llvm::Pattern::printVariableDefs(), processAbsIntrinsic(), llvm::jitlink::CompactUnwindManager< CURecTraits >::processAndReserveUnwindInfo(), processMinMaxIntrinsic(), processOverflowIntrinsic(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::xray::Profile::Profile(), ProfileFoldOpInit(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::DominatorTreeBase< BlockT, false >::properlyDominates(), llvm::DominatorTreeBase< BlockT, false >::properlyDominates(), llvm::VPDominatorTree::properlyDominates(), llvm::jitlink::prune(), r0(), r1(), r2(), r3(), r4(), llvm::ConstantExprKeyType::rangesEqual(), llvm::BitTracker::reached(), llvm::SymbolRemappingReader::read(), llvm::jitlink::aarch32::readAddend(), llvm::jitlink::aarch32::readAddendArm(), llvm::jitlink::aarch32::readAddendData(), llvm::jitlink::aarch32::readAddendThumb(), llvm::jitlink::readCFIRecordLength(), readGSIHashBuckets(), llvm::GOFFObjectWriter::recordRelocation(), llvm::WinCOFFWriter::recordRelocation(), reinsertVectorIndexAdd(), llvm::jitlink::relaxCall(), llvm::jitlink::relaxOnce(), llvm::rdf::DataFlowGraph::releaseBlock(), llvm::AttributeSet::removeAttribute(), llvm::AttributeSet::removeAttribute(), llvm::AttributeSet::removeAttributes(), llvm::jitlink::LinkGraph::removeBlock(), llvm::MemorySSAUpdater::removeDuplicatePhiEdgesBetween(), llvm::codegen::renderBoolStringAttr(), replaceSubOverflowUses(), replaceSymmetricNode(), replaceUnaryCall(), replaceWithConstant(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetLiveIns(), llvm::SSAUpdaterBulk::RewriteAllUses(), rewriteCall(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::rewriteLoopExitValues(), llvm::APIntOps::RoundingSDiv(), llvm::APIntOps::RoundingUDiv(), llvm::BitTracker::run(), llvm::CostModelPrinterPass::run(), llvm::dxil::PointerTypeAnalysis::run(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), llvm::LoadAndStorePromoter::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::SpeculativeExecutionPass::runImpl(), llvm::RewriteStatepointsForGC::runOnFunction(), runOnKernelFunction(), runOpWithExpandOnOverflow(), SalvageDVI(), llvm::sampleprof::SampleProfileReader::SampleProfileReader(), llvm::sampleprof::SampleProfileReaderBinary::SampleProfileReaderBinary(), llvm::sampleprof::SampleProfileReaderExtBinary::SampleProfileReaderExtBinary(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::SampleProfileReaderExtBinaryBase(), llvm::sampleprof::SampleProfileReaderGCC::SampleProfileReaderGCC(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::SampleProfileReaderItaniumRemapper(), llvm::sampleprof::SampleProfileReaderRawBinary::SampleProfileReaderRawBinary(), llvm::sampleprof::SampleProfileReaderText::SampleProfileReaderText(), llvm::sampleprof::SampleSorter< LocationT, SampleT >::SampleSorter(), llvm::SCEVExpander::SCEVExpanderCleaner, llvm::SchedRegion::SchedRegion(), llvm::SDNodeFlags::SDNode, llvm::jitlink::SectionRange::SectionRange(), llvm::FastMathFlags::setAllowContract(), llvm::FastMathFlags::setAllowReassoc(), llvm::FastMathFlags::setAllowReciprocal(), llvm::FastMathFlags::setApproxFunc(), llvm::setBranchProbability(), llvm::pdb::BulkPublic::setBucketIdx(), llvm::AMDGPURegisterBankInfo::setBufferOffsets(), llvm::pdb::DbiStreamBuilder::setBuildNumber(), llvm::CallBrInst::setDefaultDest(), llvm::msf::MSFBuilder::setDirectoryBlocksHint(), llvm::MachineFunction::setExposesReturnsTwice(), llvm::FastMathFlags::setFast(), llvm::DIE::setForceChildren(), llvm::codegen::setFunctionAttributes(), llvm::jitlink::COFFLinkGraphBuilder::setGraphBlock(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::setGraphBlock(), llvm::AVRMachineFunctionInfo::setHasAllocas(), llvm::sandboxir::Instruction::setHasAllowContract(), llvm::sandboxir::Instruction::setHasAllowReassoc(), llvm::sandboxir::Instruction::setHasAllowReciprocal(), llvm::sandboxir::Instruction::setHasApproxFunc(), llvm::MachineFrameInfo::setHasCopyImplyingStackAdjustment(), llvm::pdb::InfoStreamBuilder::setHashPDBContentsToGUID(), llvm::MachineFunction::setHasInlineAsm(), llvm::MachineFrameInfo::setHasMustTailInVarArgFunc(), llvm::sandboxir::Instruction::setHasNoInfs(), llvm::sandboxir::Instruction::setHasNoNaNs(), llvm::sandboxir::Instruction::setHasNoSignedWrap(), llvm::TruncInst::setHasNoSignedWrap(), llvm::sandboxir::Instruction::setHasNoSignedZeros(), llvm::sandboxir::Instruction::setHasNoUnsignedWrap(), llvm::TruncInst::setHasNoUnsignedWrap(), llvm::MachineFrameInfo::setHasOpaqueSPAdjustment(), llvm::AVRMachineFunctionInfo::setHasSpills(), llvm::AVRMachineFunctionInfo::setHasStackArgs(), llvm::MachineFrameInfo::setHasVAStart(), llvm::CallBrInst::setIndirectDest(), setInsertPointAfterDef(), setInsertPointSkippingPhis(), llvm::PossiblyDisjointInst::setIsDisjoint(), llvm::sandboxir::PossiblyDisjointInst::setIsDisjoint(), llvm::sandboxir::Instruction::setIsExact(), llvm::GetElementPtrInst::setIsInBounds(), llvm::SinkAndHoistLICMFlags::setIsSink(), llvm::remarks::RemarkLinker::setKeepAllRemarks(), llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::sandboxir::PossiblyNonNegInst::setNonNeg(), llvm::InvokeInst::setNormalDest(), llvm::FastMathFlags::setNoSignedZeros(), llvm::rdf::PhiUseNode::setPredecessor(), llvm::InlineAsm::Flag::setRegMayBeFolded(), llvm::ICmpInst::setSameSign(), llvm::SimplifyCFGOptions::setSimplifyCondBranch(), llvm::LLVMContextImpl::setTrailingDbgRecords(), llvm::InvokeInst::setUnwindDest(), llvm::setWidenableBranchCond(), llvm::SignExtend32(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::SignExtend64(), simplifyAndOrWithICmpEq(), simplifyAssociativeBinOp(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyBranchConditionForVFAndUF(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), simplifyOp_VL(), simplifyOrInst(), simplifyOrLogic(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifyTernarylogic(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), simplifyXorInst(), llvm::SimplifyCFGOptions::sinkCommonInsts(), sinkInstruction(), sinkLoopInvariantInstructions(), sinkMinMaxInBB(), llvm::VPlanTransforms::sinkPredicatedStores(), sinkProxyReg(), sinkRecurrenceUsersAfterPrevious(), llvm::coro::sinkSpillUsesAfterCoroBegin(), llvm::APIntOps::smax(), llvm::APIntOps::smin(), llvm::ConstantRange::smul_fast(), llvm::ConstantRange::smul_sat(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::sampleprof::sortFuncProfiles(), sortGlobalExprs(), sortIntervals(), llvm::DebugLocEntry::sortUniqueValues(), llvm::SimplifyCFGOptions::speculateBlocks(), llvm::SimplifyCFGOptions::speculateUnpredictables(), llvm::SPIRVCombinerHelper::SPIRVCombinerHelper(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), llvm::jitlink::LinkGraph::splitBlock(), llvm::AMDGPULegalizerInfo::splitBufferOffsets(), llvm::AMDGPURegisterBankInfo::splitBufferOffsets(), llvm::jitlink::splitCompactUnwindBlocks(), llvm::VETargetLowering::splitMaskArithmetic(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), STATISTIC(), llvm::storeToSameAddress(), llvm::StrCmpOptionName(), llvm::SuspendCrossingInfo::SuspendCrossingInfo(), SwapN(), llvm::object::symbol_iterator::symbol_iterator(), llvm::object::SymbolRef::SymbolRef(), toDebugS(), toggleSPDenormMode(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::jitlink::LinkGraph::transferBlock(), tryFactorization(), llvm::InstCombinerImpl::tryFactorizationFolds(), tryInsertCastToCommonAddrSpace(), llvm::CombinerHelper::tryReassocBinOp(), tryToMatchAndCreateMulAccumulateReduction(), tryToRecognizeTableBasedCttz(), tryToSimplifyOverflowMath(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), llvm::xray::TSCWrapRecord::TSCWrapRecord(), llvm::APIntOps::umax(), llvm::APIntOps::umin(), unifyBitWidth(), unmergeReadAnyLane(), llvm::MemoryPhi::unorderedDeleteIncomingBlock(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), unpackV2S16ToS32(), llvm::UnrollRuntimeLoopRemainder(), llvm::DWARFUnit::updateAddressDieMap(), llvm::MachineBasicBlock::updateTerminator(), llvm::UpgradeAttributes(), upgradeMaskedMove(), llvm::UpgradeModuleFlags(), upgradeX86IntrinsicCall(), llvm::validateDelinearizationResult(), llvm::json::Value::Value(), llvm::AA::ValueAndContext::ValueAndContext(), TransferTracker::ValueToLocSort(), llvm::AssumptionCacheTracker::verifyAnalysis(), llvm::GenericCycle< ContextT >::verifyCycle(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::InstCombinerImpl::visitCallInst(), llvm::jitlink::aarch32::GOTBuilder::visitEdge(), llvm::jitlink::aarch32::StubsManager_prev7::visitEdge(), llvm::jitlink::aarch32::StubsManager_v7::visitEdge(), llvm::jitlink::aarch64::GOTTableManager::visitEdge(), llvm::jitlink::aarch64::PLTTableManager::visitEdge(), llvm::jitlink::loongarch::GOTTableManager::visitEdge(), llvm::jitlink::loongarch::PLTTableManager::visitEdge(), llvm::jitlink::ppc64::PLTTableManager< Endianness >::visitEdge(), llvm::jitlink::ppc64::TOCTableManager< Endianness >::visitEdge(), llvm::jitlink::systemz::GOTTableManager::visitEdge(), llvm::jitlink::systemz::PLTTableManager::visitEdge(), llvm::jitlink::visitEdge(), llvm::jitlink::visitEdge(), llvm::jitlink::x86::GOTTableManager::visitEdge(), llvm::jitlink::x86::PLTTableManager::visitEdge(), llvm::jitlink::x86_64::GOTTableManager::visitEdge(), llvm::jitlink::x86_64::PLTTableManager::visitEdge(), llvm::jitlink::visitExistingEdges(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitICmpInst(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitXor(), llvm::widenWidenableBranch(), llvm::ScalarEvolution::willNotOverflow(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::TimeTraceProfiler::write(), llvm::object::writeStringTable(), llvm::InstrProfWriter::writeText(), llvm::object::xcoff_symbol_iterator::xcoff_symbol_iterator(), llvm::AttributeSet::~AttributeSet(), llvm::DwarfUnit::~DwarfUnit(), llvm::ReachingDefInfo::~ReachingDefInfo(), and llvm::jitlink::Section::~Section().
C()
GCRegistry::Add< ShadowStackGC > C ("shadow-stack" , "Very portable GC for uncooperative code generators") static
Examples
/Users/rift/code/llvm-doxygen/llvm-project-22.1.0/llvm/include/llvm/Transforms/Utils/Local.h.
Referenced by AbstractManglingParser< Derived, Alloc >::consumeIf(), llvm::jitlink::createLookupContinuation(), encodeComponent(), encodingBits(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVM_YAML_IS_SEQUENCE_VECTOR(), LLVMConstRealOfStringAndSize(), operator delete(), operator delete[](), operator new(), operator new[](), OutputBuffer::operator+=(), OutputBuffer::operator<<(), AbstractManglingParser< Derived, Alloc >::parseFloatingLiteral(), starts_with(), and STATISTIC().
D()
GCRegistry::Add< StatepointGC > D ("statepoint-example" , "an example strategy for statepoint") static
Referenced by llvm::AbstractDependenceGraphBuilder< GraphType >::AbstractDependenceGraphBuilder(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::add(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::add(), llvm::DwarfUnit::addGlobalTypeImpl(), llvm::SUnit::addPred(), addToFwdRegWorklist(), llvm::DWARFUnitVector::addUnitsForDWOSection(), llvm::DWARFUnitVector::addUnitsForSection(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::yaml::AliasNode::AliasNode(), llvm::AMDGPUFrameLowering::AMDGPUFrameLowering(), llvm::DWARFTypePrinter< DieType >::appendAndTerminateTemplateParameters(), llvm::DWARFTypePrinter< DieType >::appendArrayType(), appendDigit(), llvm::DWARFTypePrinter< DieType >::appendPointerLikeTypeBefore(), llvm::DWARFTypePrinter< DieType >::appendQualifiedName(), llvm::DWARFTypePrinter< DieType >::appendQualifiedNameBefore(), llvm::DWARFTypePrinter< DieType >::appendScopes(), llvm::DWARFTypePrinter< DieType >::appendSubroutineNameAfter(), llvm::DWARFTypePrinter< DieType >::appendTemplateParameters(), llvm::DWARFTypePrinter< DieType >::appendUnqualifiedName(), llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameAfter(), llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameBefore(), llvm::AppleAccelTableOffsetData::AppleAccelTableOffsetData(), llvm::AppleAccelTableTypeData::AppleAccelTableTypeData(), llvm::HexagonSubtarget::UsrOverflowMutation::apply(), llvm::DwarfCompileUnit::applyStmtList(), llvm::DwarfCompileUnit::attachLowHighPC(), llvm::DWARFDie::attribute_iterator::attribute_iterator(), llvm::DWARFDie::attribute_iterator::attribute_iterator(), llvm::yaml::MappingNode::basic_collection_iterator< MappingNode, KeyValueNode >, llvm::yaml::SequenceNode::basic_collection_iterator< SequenceNode, Node >, llvm::Instruction::BasicBlock, llvm::SwitchCG::BitTestBlock::BitTestBlock(), llvm::yaml::BlockScalarNode::BlockScalarNode(), llvm::HexagonPacketizerList::canPromoteToDotNew(), canSkipDef(), checkDependency(), checkDyldCommand(), checkDylibCommand(), llvm::VPRecipeBase::classof(), llvm::AArch64FunctionInfo::clearLinkerOptimizationHints(), llvm::MemorySSA::ClobberWalkerBase::ClobberWalkerBase(), llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::DILocation::cloneWithBaseDiscriminator(), collectPrivatizingConstructs(), combineTargetShuffle(), llvm::ProfileSummaryBuilder::computeDetailedSummary(), computeKnownBitsFromLerpPattern(), llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::GCNSchedStage::computeSUnitReadyCycle(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::InstrProfSymtab::create(), llvm::object::Decompressor::create(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::DWARFFormValue::createFromBlockValue(), llvm::mca::InstrBuilder::createInstruction(), llvm::AbstractDependenceGraphBuilder< GraphType >::createMemoryDependencyEdges(), llvm::xray::CustomEventRecord::CustomEventRecord(), llvm::xray::CustomEventRecordV5::CustomEventRecordV5(), llvm::SelectionDAG::DAGUpdateListener::DAGUpdateListener(), llvm::DataDependenceGraph::DataDependenceGraph(), llvm::DataDependenceGraph::DataDependenceGraph(), llvm::DDGBuilder::DDGBuilder(), debugAssign(), DecodeCCOutOperand(), llvm::DILocation::decodeDiscriminator(), DecodeFixedType(), DecodePredicateOperand(), DecodeVpredNOperand(), DecodeVpredROperand(), DeltaInfo::DeltaInfo(), llvm::GCNIterativeScheduler::detachSchedule(), llvm::diagnoseDontCall(), llvm::omp::DirectiveNameParser::DirectiveNameParser(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::SCEVDivision::divide(), llvm::dlangDemangle(), llvm::yaml::document_iterator::document_iterator(), llvm::ScaledNumberBase::dump(), dumpAttribute(), dumpExampleDependence(), llvm::DWARFDie::DWARFDie(), llvm::gsym::DwarfTransformer::DwarfTransformer(), llvm::DWARFVerifier::DWARFVerifier(), llvm::MCLOHContainer::emit(), llvm::APByteStreamer::emitDIERef(), llvm::BufferByteStreamer::emitDIERef(), llvm::ByteStreamer::emitDIERef(), llvm::HashingByteStreamer::emitDIERef(), llvm::DwarfDebug::endModule(), llvm::ScheduleDAGMI::enterRegion(), llvm::sampleprof::DefaultFunctionPruningStrategy::Erase(), factorizeMinMaxTree(), llvm::HexagonDAGToDAGISel::FastFDiv(), llvm::HexagonDAGToDAGISel::FDiv(), llvm::FileCheckString::FileCheckString(), llvm::gsym::FileEntry::FileEntry(), llvm::StringRef::find_insensitive(), llvm::DWARFDie::findRecursively(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), llvm::ExistsOpInit::Fold(), llvm::UnOpInit::Fold(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::FoldingSetNodeIDRef::FoldingSetNodeIDRef(), foldIntrinsicUsingDistributiveLaws(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldNegativePower2AndShiftedMask(), foldNotXor(), foldPowerOf2AndShiftedMask(), foldSelectCmpBitcasts(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::xray::FunctionRecord::FunctionRecord(), llvm::InLineChangePrinter::generateIRRepresentation(), llvm::SignedDivisionByConstantInfo::get(), llvm::UnsignedDivisionByConstantInfo::get(), llvm::rdf::Liveness::getAllReachedUses(), llvm::getArm64ECInsertionPointInMangledName(), llvm::json::Value::getAsInteger(), llvm::DILocation::getBaseDiscriminatorFromDiscriminator(), llvm::ScalarEvolution::getBlockDisposition(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::DILocation::getCopyIdentifierFromDiscriminator(), GetCpAsyncBulkTensorS2GReductionOpcode(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::DependenceGraphInfo< NodeType >::getDependenceString(), llvm::DwarfUnit::getDIE(), llvm::DWARFUnit::getDIEIndex(), llvm::DILocation::getDuplicationFactorFromDiscriminator(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfo, BranchProbabilityInfo >::getEdgeAttributes(), llvm::MCLOHContainer::getEmitSize(), llvm::WebAssemblyException::getExceptionDepth(), llvm::ScaledNumber< uint64_t >::getFraction(), llvm::StatepointOpers::getGCPointerMap(), llvm::DenseMapInfo< DebugVariable >::getHashValue(), llvm::omp::getLeafConstructs(), llvm::omp::getLeafConstructsOrSelf(), llvm::omp::getLeafOrCompositeConstructs(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::ScalarEvolution::getLoopDisposition(), llvm::DILocation::getMaskedDiscriminator(), getMaskedTypeForICmpPair(), llvm::ScalarEvolution::getMulExpr(), getNextComponentInDiscriminator(), llvm::SPIRVGlobalRegistry::getOrAddMemAliasingINTELInst(), getReg(), getReg(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::ScalarEvolution::getUDivCeilSCEV(), llvm::object::ELFFile< ELFT >::getVersionDefinitions(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::DWARFVerifier::handleAccelTables(), llvm::IndexedReference::hasTemporalReuse(), llvm::sandboxir::CollectDescr::hasVectorInputs(), llvm::orc::MachOPlatform::HeaderOptions::HeaderOptions(), llvm::MCInstrInfo::InitMCInstrInfo(), llvm::MCRegisterInfo::InitMCRegisterInfo(), llvm::DwarfUnit::insertDIE(), llvm::DwarfUnit::insertDIE(), llvm::mca::Instruction::Instruction(), llvm::mca::InstructionBase::InstructionBase(), llvm::interpretDecimal(), llvm::omp::isCombinedConstruct(), isCommutableVPERMV3Instruction(), llvm::omp::isCompositeConstruct(), llvm::isCurrentDebugType(), llvm::rdf::TargetOperandInfo::isFixedReg(), llvm::InductionDescriptor::isFPInductionPHI(), isHorizontalBinOp(), llvm::InductionDescriptor::isInductionPHI(), llvm::InductionDescriptor::isInductionPHI(), llvm::omp::isLeafConstruct(), llvm::omp::isPrivatizingConstruct(), isSafeToMove(), llvm::DwarfUnit::isShareableAcrossCUs(), isSignExtendedW(), isSignExtendedW(), llvm::DWARFDie::iterator::iterator(), llvm::OnDiskChainedHashTable< Info >::iterator::iterator(), llvm::SwitchCG::JumpTable::JumpTable(), llvm::ImutContainerInfo< T >::KeyOfValue(), llvm::ImutContainerInfo< T * >::KeyOfValue(), llvm::yaml::KeyValueNode::KeyValueNode(), llvm::LexicalScope::LexicalScope(), llvm::memprof::LineLocation::LineLocation(), llvm::sampleprof::LineLocation::LineLocation(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMLinkModules2(), llvm::AMDGPUTargetLowering::LowerF64ToF16Safe(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), llvm::MachinePassRegistryNode< PassCtorTy >::MachinePassRegistryNode(), llvm::MachineSchedRegistry::MachineSchedRegistry(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::RootDescriptorYaml >::mapping(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), matchMinMaxOfMinMax(), llvm::MCDecodedPseudoProbe::MCDecodedPseudoProbe(), llvm::MCPseudoProbeBase::MCPseudoProbeBase(), llvm::microsoftDemangle(), llvm::detail::DoubleAPFloat::multiply(), narrowUDivURem(), llvm::DWARFTypePrinter< DieType >::needsParens(), llvm::MachinePassRegistryListener< PassCtorTy >::NotifyAdd(), llvm::RegisterPassParser< RegistryClass >::NotifyAdd(), llvm::yaml::NullNode::NullNode(), llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >::operator()(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::object::operator<<(), llvm::operator<<(), llvm::pdb::operator<<(), operator<<(), llvm::InstrProfSymtab::operator=(), llvm::ARM::parseHWDiv(), populateDependencyMatrix(), llvm::orc::LLJITBuilderState::prepareForConstruction(), preservesBackwardDependence(), preservesForwardDependence(), llvm::cas::ondisk::OnDiskGraphDB::print(), llvm::DIEAbbrev::print(), llvm::ScaledNumberBase::print(), printDepMatrix(), processSDiv(), processSRem(), llvm::DIEAbbrev::Profile(), llvm::object::DirectX::PSVRuntimeInfo::PSVRuntimeInfo(), r0(), r1(), r2(), r3(), r4(), llvm::R600FrameLowering::R600FrameLowering(), llvm::InstrProfLookupTrait::ReadData(), llvm::memprof::CallStackLookupTrait::ReadData(), llvm::memprof::FrameLookupTrait::ReadData(), llvm::memprof::RecordLookupTrait::ReadData(), readData(), llvm::InstrProfLookupTrait::ReadKey(), llvm::memprof::CallStackLookupTrait::ReadKey(), llvm::memprof::FrameLookupTrait::ReadKey(), llvm::memprof::RecordLookupTrait::ReadKey(), llvm::InstrProfLookupTrait::ReadKeyDataLength(), llvm::memprof::CallStackLookupTrait::ReadKeyDataLength(), llvm::memprof::FrameLookupTrait::ReadKeyDataLength(), llvm::memprof::RecordLookupTrait::ReadKeyDataLength(), llvm::InstrProfLookupTrait::readValueProfilingData(), llvm::DefInit::Record, llvm::xray::RecordPrinter::RecordPrinter(), llvm::RegisterRegAlloc::RegisterRegAlloc(), llvm::RegisterRegAllocBase< SubClass >::RegisterRegAllocBase(), llvm::RegisterScheduler::RegisterScheduler(), llvm::SUnit::removePred(), llvm::MCContext::reportError(), llvm::MCContext::reportWarning(), llvm::detail::resolveReferencedType(), llvm::detail::resolveReferencedType(), resolveReferencedType(), rewriteMaterializableInstructions(), ObjCARCContract::run(), llvm::rustDemangle(), llvm::yaml::ScalarNode::ScalarNode(), llvm::InstrProfRecord::scale(), llvm::InstrProfValueSiteRecord::scale(), scale(), llvm::AAPointerInfo::RangeList::set_difference(), llvm::DbgEntity::setDIE(), llvm::SwingSchedulerDDGEdge::setDistance(), llvm::GVNPass::ValueTable::setDomTree(), llvm::ScheduleDAGInstrs::setDumpDirection(), llvm::sframe::FDEInfo< E >::setFDEType(), llvm::rdf::DefNode::setReachedDef(), llvm::Value::setValueSubclassData(), llvm::SIFrameLowering::SIFrameLowering(), llvm::SimpleRegistryEntry< T >::SimpleRegistryEntry(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), llvm::DWARFTypePrinter< DieType >::skipQualifiers(), SolveLinEquationWithOverflow(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::SIInstrInfo::splitFlatOffset(), llvm::stable_hash_combine(), llvm::gsym::StringTable::StringTable(), llvm::SystemZFrameLowering::SystemZFrameLowering(), llvm::TargetFrameLowering::TargetFrameLowering(), llvm::TensorSpec::toJSON(), llvm::ScaledNumberBase::toString(), toStringAPFloat(), tryFactorization(), llvm::InstCombinerImpl::tryFactorizationFolds(), llvm::xray::TypedEventRecord::TypedEventRecord(), llvm::detail::unwrapReferencedTypedefType(), llvm::cas::ondisk::OnDiskGraphDB::validate(), llvm::json::Value::Value(), llvm::object::iterator< RootParameterHeader >::ViewArray(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::SCEVDivision::visitConstant(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitICmpInst(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitXor(), llvm::object::writeImportLibrary(), and llvm::VPDef::~VPDef().
E()
GCRegistry::Add< CoreCLRGC > E ("coreclr" , "CoreCLR-compatible GC") static
Referenced by llvm::accumulate(), llvm::accumulate(), addAllTypesFromDWP(), llvm::FunctionSummary::addCall(), llvm::DGNode< DDGNode, DDGEdge >::addEdge(), llvm::ImmutableGraphBuilder< MachineGadgetGraph >::addEdge(), llvm::jitlink::Block::addEdge(), addImplicitDefs(), addInstToMergeableList(), addMask(), llvm::MCContext::addMCGenDwarfLabelEntry(), addModuleFlags(), AddParamAndFnBasicAttributes(), addRegionIntoQueue(), addRegionIntoQueue(), llvm::AddressRange::AddressRange(), llvm::WebAssemblyException::addSubException(), llvm::InstrProfSymtab::addVTableName(), llvm::GCNSubtarget::adjustSchedDependency(), llvm::BasicTTIImplBase< BasicTTIImpl >::allowsMisalignedMemoryAccesses(), allPhiOperandsUndefined(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), llvm::CCState::AnalyzeArgumentsSecondPass(), analyzeCompressibleUses(), analyzeExitPHIsForOutputUses(), annotateAllFunctions(), llvm::BitmaskEnumDetail::any(), llvm::orc::shared::TrivialSPSSequenceDeserialization< SPSElementTagT, SmallVectorImpl< T > >::append(), llvm::orc::shared::TrivialSPSSequenceDeserialization< SPSElementTagT, std::vector< T > >::append(), appendJITDebugDescriptor(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::appliesTo(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::appliesTo(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::appliesTo(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::appliesTo(), llvm::BitVector::apply(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::apply(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::SampleProfileInference< FT >::apply(), llvm::jitlink::aarch32::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::ppc64::applyFixup(), llvm::jitlink::x86::applyFixup(), llvm::jitlink::x86_64::applyFixup(), llvm::jitlink::aarch32::applyFixupArm(), llvm::jitlink::aarch32::applyFixupData(), llvm::jitlink::aarch32::applyFixupThumb(), llvm::MCTargetAsmParser::applySpecifier(), ARM64FindSegmentsInFunction(), bbHasFallthrough(), llvm::BitCodeAbbrevOp::BitCodeAbbrevOp(), llvm::yaml::ScalarBitSetTraits< support::detail::packed_endian_specific_integral< value_type, endian, alignment >, std::enable_if_t< has_ScalarBitSetTraits< value_type >::value > >::bitset(), llvm::remarks::BitstreamMetaParserHelper::BitstreamBlockParserHelper< BitstreamMetaParserHelper >, llvm::SwitchCG::BitTestBlock::BitTestBlock(), llvm::rdf::DataFlowGraph::build(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::buildOpSpirvDecorations(), buildTreeReduction(), calcPredicateUsingBooleans(), calcPredicateUsingInteger(), llvm::orc::shared::WrapperFunction< void(SPSTagTs...)>::callAsync(), canFallThroughTo(), llvm::cantFail(), llvm::cantFail(), canUseSiblingCall(), CC_AIX(), llvm::CfiFunctionIndex::CfiFunctionIndex(), llvm::mca::ResourceManager::checkAvailability(), checkDenormalAttributeInconsistency(), checkEFLAGSLive(), llvm::MCAsmParser::checkForValidSection(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), checkNode(), checkOrAndOpImpliedByOther(), checkOverlappingElement(), llvm::AArch64AuthMCExpr::classof(), llvm::AMDGPUMCExpr::classof(), llvm::DbgLabelRecord::classof(), llvm::DbgVariableRecord::classof(), llvm::GVNExpression::DeadExpression::classof(), llvm::MCBinaryExpr::classof(), llvm::MCConstantExpr::classof(), llvm::MCSpecifierExpr::classof(), llvm::MCSymbolRefExpr::classof(), llvm::MCTargetExpr::classof(), llvm::MCUnaryExpr::classof(), llvm::NVPTXFloatMCExpr::classof(), llvm::NVPTXGenericMCSymbolRefExpr::classof(), llvm::vfs::RedirectingFileSystem::DirectoryEntry::classof(), llvm::vfs::RedirectingFileSystem::DirectoryRemapEntry::classof(), llvm::vfs::RedirectingFileSystem::FileEntry::classof(), llvm::vfs::RedirectingFileSystem::RemapEntry::classof(), llvm::X86MCExpr::classof(), llvm::AnalysisManager< LazyCallGraph::SCC, LazyCallGraph & >::clearAnalysis(), llvm::orc::SymbolStringPool::clearDeadEntries(), collectInstructionDeps(), collectMergeableInsts(), collectVersions(), combineCONCAT_VECTORS(), combineConcatVectorOps(), combineConstantPoolLoads(), combineVPMADD(), combineWeightsBySorting(), compareCmp(), llvm::ImutAVLFactory< ImutInfo >::compareTreeWithSection(), computeAddrMap(), llvm::mca::computeBlockRThroughput(), computeConstraintToUse(), llvm::memprof::computeFrameHistogram(), llvm::mca::computeProcResourceMasks(), llvm::telemetry::Config::Config(), llvm::DirectedGraph< DDGNode, DDGEdge >::connect(), llvm::ConstantAggrKeyType< ConstantArray >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), constantFold(), constantIsDead(), ConstantPropUsersOf(), llvm::ConstantPtrAuthKeyType::ConstantPtrAuthKeyType(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::contains(), llvm::ImmutableList< T >::contains(), llvm::orc::LibraryResolver::SymbolQuery::contains(), llvm::LiveRange::Segment::containsInterval(), convertMRI(), convertStackObjects(), convertToGuardPredicates(), costShuffleViaVRegSplitting(), llvm::count(), llvm::DXContainerYAML::RootSignatureYamlDesc::create(), llvm::InstrProfSymtab::create(), llvm::InstrProfSymtab::create(), llvm::memprof::RawMemProfReader::create(), llvm::objcopy::coff::COFFReader::create(), llvm::objcopy::dxbc::DXContainerReader::create(), llvm::objcopy::xcoff::XCOFFReader::create(), llvm::object::ELFObjectFile< ELFT >::create(), createBSWAPShuffleMask(), createCBufferLoad(), llvm::DDGBuilder::createDefUseEdge(), llvm::jitlink::aarch64::createEmptyPointerSigningFunction(), createError(), createError(), llvm::createFileError(), llvm::createFileError(), llvm::FileError::createFileError, llvm::FileError::createFileError, llvm::vfs::ProxyOutputBackend::createFileImpl(), llvm::DDGBuilder::createMemoryEdge(), createPtr(), llvm::DDGBuilder::createRootedEdge(), createTempFile(), createTuple(), llvm::mca::InOrderIssueStage::cycleStart(), llvm::DDGEdge::DDGEdge(), llvm::DDGEdge::DDGEdge(), llvm::RecyclingAllocator< BumpPtrAllocator, char, AllocBytes, CacheLineBytes >::Deallocate(), deepWriteArchive(), llvm::DenseMap< const BlockT *, const BlockT * >::DenseMap(), llvm::orc::NonOwningSymbolStringPtr::DenseMapInfo< orc::NonOwningSymbolStringPtr >, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, DenseSetEmpty, ValueInfoT, DenseSetPair< ValueT > >, ValueInfoT >< ValueT, ValueInfoT >::DenseSetImpl(), llvm::IndexedMemProfReader::deserialize(), llvm::memprof::DataAccessProfData::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::deserialize(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SpecificBumpPtrAllocator< T >::DestroyAll(), llvm::AbstractDependenceGraphBuilder< GraphType >::destroyEdge(), determineSVEStackSizes(), llvm::DGEdge< DDGNode, DDGEdge >::DGEdge(), llvm::DGNode< DDGNode, DDGEdge >::DGNode(), llvm::DIEEntry::DIEEntry(), llvm::DIEExpr::DIEExpr(), llvm::vfs::OutputFile::discardOnDestroy(), llvm::PBQP::Graph< RegAllocSolverImpl >::disconnectEdge(), llvm::DistributeRange(), llvm::DominatorTree::dominates(), llvm::DominatorTree::dominates(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DomTreeUpdate::DomTreeUpdate(), doPromotion(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::dropOutOfDateUpdates(), llvm::mca::RegisterFile::dump(), dumpEdges(), dumpExpression(), dumpLoclistsSection(), dumpMachineInstrRangeWithSlotIndex(), llvm::objcopy::dxbc::dumpPartToFile(), dumpRemats(), llvm::objcopy::coff::dumpSection(), dumpSectionToFile(), dumpSectionToFile(), llvm::objcopy::wasm::dumpSectionToFile(), dumpSpills(), llvm::GraphTraits< const CallGraphNode * >::edge_dest(), llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::edge_dest(), llvm::GraphTraits< ValueInfo >::edge_dest(), llvm::jitlink::Block::edges_at(), llvm::jitlink::Block::edges_at(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantStruct(), emitGlobalConstantVector(), emitLocList(), emitSelectPseudo(), emitSelectPseudo(), llvm::LazyCallGraph::EdgeSequence::empty(), llvm::WinEH::FrameInfo::empty(), llvm::orc::LibraryResolver::SymbolEnumerator::enumerateSymbols(), llvm::yaml::ScalarEnumerationTraits< support::detail::packed_endian_specific_integral< value_type, endian, alignment >, std::enable_if_t< has_ScalarEnumerationTraits< value_type >::value > >::enumeration(), llvm::SparseMultiSet< PhysRegSUOper, MCRegUnit, MCRegUnitToIndex, uint16_t >::equal_range(), llvm::const_iterator< MemoryLocation >::erase(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::erase(), llvm::MachineBasicBlock::erase(), llvm::TinyPtrVector< ReachingDef >::erase(), llvm::TypeFinder::erase(), llvm::PriorityWorklist< T, VectorT, MapT >::erase_if(), llvm::CodeGenDataReader::error(), llvm::InstrProfReader::error(), llvm::Error::ErrorList, llvm::ErrorOr< T >::ErrorOr(), EstimateRuntime(), EvaluateCRExpr(), llvm::mca::InOrderIssueStage::execute(), llvm::mca::InstructionTables::execute(), llvm::GIMatchTableExecutor::executeMatchTable(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::objcopy::dxbc::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), expandMulToNAFSequence(), llvm::expectedToErrorOr(), llvm::expectedToOptional(), llvm::expectedToStdOptional(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::DWARFListType< ListEntryType >::extract(), extractConstantBits(), extractConstantWithoutWrapping(), extractFromBranchWeightMD(), llvm::objcopy::dxbc::extractPartAsObject(), extractValues(), llvm::orc::detail::WaitingOnGraph< JITDylib *, NonOwningSymbolStringPtr >::fail(), fatalOpenError(), llvm::FileLocRange::FileLocRange(), llvm::filterDbgVars(), llvm::opt::ArgList::filtered(), llvm::opt::ArgList::filtered_reverse(), findArrayDimensionsRec(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), findCommonType(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::DGNode< DDGNode, DDGEdge >::findEdgesTo(), llvm::DGNode< DDGNode, DDGEdge >::findEdgeTo(), findInitTrampolineFromBB(), findIrreducibleHeaders(), FindLastAluClause(), llvm::DWARFListTableBase< DWARFListType >::findList(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), findPotentialBlockers(), findSafeStoreForStoreStrongContraction(), findStrip(), first_use_of_in_block(), firstCommonClass(), fixIrreducible(), fixupIndexV4(), fixupIndexV5(), fixupShuffleMaskForPermutedSToV(), flattenTypes(), foldGEPOfPhi(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldNegativePower2AndShiftedMask(), foldNeonShift(), foldPatternedLoads(), foldPowerOf2AndShiftedMask(), forEachJumpTableBranch(), llvm::format_provider< Enum, std::enable_if_t< dwarf::EnumTraits< Enum >::value > >::format(), llvm::format_provider< llvm::json::Value >::format(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), gatherFileIDs(), generateAssignInstrs(), generateAssignType(), llvm::get(), llvm::get(), llvm::ImmutableGraphBuilder< MachineGadgetGraph >::get(), getAccelTable(), llvm::orc::LibraryResolver::SymbolQuery::getAllResults(), getAnnotation(), llvm::DagInit::getArgAndNames(), llvm::object::COFFObjectFile::getAuxSymbol(), llvm::MemoryPhi::getBasicBlockIndex(), llvm::object::ELFObjectFile< ELF32LE >::getBuildAttributes(), getBundledUseMI(), llvm::DebugLocStream::getBytes(), llvm::DebugLocStream::getComments(), getConstantVector(), llvm::IntervalTree< LVAddress, LVScope * >::getContaining(), getEarliestInsertPos(), llvm::ImmutableGraph< MachineInstr *, int >::getEdgeIndex(), llvm::PBQP::Graph< RegAllocSolverImpl >::getEdgeOtherNodeId(), getEmscriptenInvokeSymbolName(), getEnableSplitLTOUnitAndUnifiedFlag(), llvm::BitstreamEntry::getEndBlock(), llvm::DWARFDebugNames::NameIndex::getEntry(), llvm::objcarc::getEquivalentPHIs(), llvm::BitstreamEntry::getError(), getExtractIndex(), getFauxShuffleMask(), getFirstReloc(), llvm::jitlink::Block::getFixupAddress(), getGFNICtrlMask(), getHashForUdt(), llvm::IRSimilarity::IRInstructionDataTraits::getHashValue(), getImplicitCondFromMI(), llvm::SlotIndexes::getIndexAfter(), getInsertPt(), getInsertPt(), getInstrBB(), llvm::SIInstrInfo::getInstrLatency(), getLatestInsertPos(), GetLinearExpression(), getLiveInRegsAt(), getLiveOutRegsAt(), llvm::getLiveRegMap(), getLlvmUserOperationEncoding(), getMaskedTypeForICmpPair(), getMaxCalleeSavedReg(), getMemberOffsets(), getMemoryBufferForStream(), getNextBlock(), getNextMachineInstrInBB(), llvm::SlotIndexes::getNextNonNullIndex(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfo, BranchProbabilityInfo >::getNodeAttributes(), getNonDebugInstr(), getNumberOfRelocations(), llvm::EquivalenceClasses< BasicBlock * >::getNumClasses(), getObject(), llvm::object::getObject(), llvm::getOpVariableMBBIt(), getOrSelfReference(), getOutputSegmentMap(), getPdbPathFromExe(), llvm::getPerfectShuffleCost(), llvm::object::ELFFile< ELF32LE >::getPhNum(), llvm::object::XCOFFObjectFile::getRawData(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::BitstreamEntry::getRecord(), llvm::object::XCOFFRelocation< llvm::support::ubig32_t >::getRelocatedLength(), llvm::DWARFDataExtractor::getRelocatedValueImpl(), llvm::orc::LibraryResolver::SymbolQuery::getResolvedLib(), getSavedReg(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::XCOFFObjectFile::getSectionContents(), llvm::object::XCOFFObjectFile::getSectionFileOffsetToRawData(), llvm::object::ELFFile< ELF32LE >::getShNum(), llvm::object::ELFFile< ELF32LE >::getShStrNdx(), getShufflevectorNumGroups(), getSHUFPDImm(), getSourceLineHash(), llvm::InstrItineraryData::getStageLatency(), GetStringLengthH(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::BitstreamEntry::getSubBlock(), getSymbols(), getTagRecordHashForUdt(), getTargetConstantBitsFromNode(), getTargetMBB(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::getTotalMemory(), llvm::abi::TypeBuilder::getUnionType(), llvm::rdf::PhysicalRegisterInfo::getUnits(), getUnmergePieces(), llvm::orc::LibraryResolver::SymbolQuery::getUnresolvedSymbols(), getUUID(), llvm::object::ELFFile< ELFT >::getVersionDependencies(), getWaitStatesSince(), getzOSCalleeAndADA(), llvm::handleAllErrors(), llvm::handleAllErrors(), handleArgs(), handleArgs(), llvm::objcopy::coff::handleArgs(), llvm::objcopy::dxbc::handleArgs(), llvm::objcopy::wasm::handleArgs(), handleCompressedSection(), llvm::Error::handleErrors, HandleInlinedEHPad(), HandleInlinedLandingPad(), handleMaybeNoDataFoundError(), llvm::GEPOperator::hasAllConstantIndices(), llvm::GEPOperator::hasAllZeroIndices(), hasAnyUnrollPragma(), llvm::BitCodeAbbrevOp::hasEncodingData(), hasField(), hasHazard(), hasJumpTableInfoInBlock(), hasLiveThroughUse(), llvm::coverage::InstantiationGroup::hasName(), HasNestArgument(), hasObjCCategory(), hasOnlyUniformBranches(), hasProfileData(), hasReturnsTwiceAttr(), llvm::hasSingleElement(), llvm::AMDGPU::hasValueInRangeLikeMetadata(), haveSameOperands(), hoistAndMergeSGPRInits(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::identifyObject(), ignoreStrippedErrors(), imageIntrinsicOptimizerImpl(), indirectCopyToAGPR(), INITIALIZE_PASS(), llvm::mca::initializeUsedResources(), llvm::yaml::ScalarTraits< support::detail::packed_endian_specific_integral< value_type, endian, alignment >, std::enable_if_t< has_ScalarTraits< value_type >::value > >::input(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, DenseSetEmpty, ValueInfoT, DenseSetPair< ValueT > >, ValueInfoT >< ValueT, ValueInfoT >::insert(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::insert(), llvm::json::Array::insert(), llvm::json::Array::insert(), llvm::json::Object::insert(), llvm::MachineBasicBlock::insert(), llvm::NodeSet::insert(), llvm::SmallPtrSetImpl< MachineInstr * >::insert(), llvm::SmallSet< Register, 16 >::insert(), llvm::ValueMap< const Value *, WeakTrackingVH >::insert(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), insertNoDuplicates(), insertSpills(), insertValues(), instructionsMatch(), llvm::GVNExpression::int_op_inserter::int_op_inserter(), llvm::GVNExpression::int_op_inserter::int_op_inserter(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), inversePermutation(), llvm::is_contained(), llvm::is_contained(), isArgumentOrArgumentLike(), isARMMCExpr(), llvm::mca::RegisterFile::isAvailable(), llvm::TargetLoweringBase::isBeneficialToExpandPowI(), isBigEndianBitShift(), isBlockValidForExtraction(), isConcatMask(), isCondRelevantToAnyCallArgument(), isConstantPowerOf2(), isDenselyPacked(), isEphemeralValueOf(), llvm::DGEdge< DDGNode, DDGEdge >::isEqualTo(), llvm::X86MCExpr::isEqualTo(), isError(), isFixedVectorShuffle(), isFNEG(), isIdentity(), isImplicitFallthrough(), isKnownNonNaN(), isKnownNonZero(), llvm::ARM_MC::isLDMBaseRegInList(), isLRAvailable(), isOnlyReachableViaThisEdge(), isPoisonShift(), isProfitableToInterleave(), isRepeatedNonIdentityClusteredMask(), llvm::orc::LibraryResolver::SymbolQuery::isResolved(), IsSafeAndProfitableToMove(), isSafeAndProfitableToSinkLoad(), isSafeToMove(), isScalarToVector(), isSignExtendedW(), isSignExtendedW(), isSSA(), llvm::mca::ResourceManager::issueInstructionImpl(), isThumbI8Relocation(), llvm::BitCodeAbbrevOp::isValidEncoding(), llvm::SwitchCG::JumpTableHeader::JumpTableHeader(), llvm::AnonStructTypeKeyInfo::KeyTy::KeyTy(), layout(), layout(), layoutCOFF(), legalizeSpvExtractElt(), legalizeSpvInsertElt(), likeBitCastFromVector(), llvm::dwarf_linker::classic::DWARFLinker::link(), LLVM_YAML_IS_SEQUENCE_VECTOR(), LLVMGetSectionContents(), LLVMPrintModuleToFile(), LLVMRemarkParserGetNext(), llvm::LLVMRemarkSetupErrorInfo< ThisError >::LLVMRemarkSetupErrorInfo(), loadBinaryFormat(), loadFDRLog(), loadObj(), loadTestingFormat(), llvm::LazyCallGraph::EdgeSequence::lookup(), lookupExtensionByID(), LowerBUILD_VECTORAsVariablePermute(), LowerBUILD_VECTORvXbf16(), LowerCONCAT_VECTORS_i1(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), lowerIntNeonIntrinsic(), llvm::jitlink::aarch64::lowerPointer64AuthEdgesToSigningFunction(), LowerShift(), lowerToAddSubOrFMAddSub(), lowerVECTOR_SHUFFLEAsVSlide1(), LowerVectorArith(), llvm::codeview::make_error_code(), llvm::coverage::make_error_code(), llvm::make_error_code(), llvm::make_error_code(), llvm::make_error_code(), llvm::make_error_code(), llvm::make_error_code(), llvm::msf::make_error_code(), llvm::pdb::make_error_code(), llvm::pdb::make_error_code(), llvm::pdb::make_error_code(), llvm::make_fallible_end(), llvm::make_fallible_range(), llvm::make_filter_range(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::makeSafe(), mangleCoveragePath(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::mapOptional(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::mapping(), llvm::yaml::MappingTraits< COFFYAML::SectionDataEntry >::mapping(), markAliveBlocks(), llvm::SCEVPatternMatch::SCEVBinaryExpr_match< SCEVTy, Op0_t, Op1_t, WrapFlags, Commutable >::match(), llvm::SCEVPatternMatch::SCEVUnaryExpr_match< SCEVTy, Op0_t >::match(), MatchDiv(), MatchMul(), MatchRem(), llvm::Pattern::MatchResult::MatchResult(), llvm::Pattern::MatchResult::MatchResult(), llvm::Pattern::MatchResult::MatchResult(), matchScalarInAggregate(), matchSymmetricPhiNodesPair(), mayBeSRetTailCallCompatible(), memOpsHaveSameBaseOperands(), mergeAttributes(), mergeConditionalStoreToAddress(), mergeOperations(), llvm::MIBundleBuilder::MIBundleBuilder(), migrateDebugInfo(), llvm::Loc::MMI::MMI(), moveInstrOut(), narrowInterleaveGroupOp(), nearest_common_dominatee(), nearest_common_dominator(), needsFP(), llvm::jitlink::aarch32::needsStub(), llvm::SelectionDAG::DAGNodeDeletedListener::NodeDeleted(), llvm::NodeSet::NodeSet(), llvm::json::ObjectMapper::ObjectMapper(), llvm::GVNExpression::op_inserter::op_inserter(), llvm::GVNExpression::op_inserter::op_inserter(), operator delete(), llvm::BitmaskEnumDetail::operator!(), llvm::DGEdge< DDGNode, DDGEdge >::operator!=(), llvm::BitmaskEnumDetail::operator&(), llvm::BitmaskEnumDetail::operator&=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator&=(), llvm::FeatureBitset::operator&=(), llvm::SmallBitVector::operator&=(), llvm::ExitOnError::operator()(), llvm::ExitOnError::operator()(), llvm::jitlink::SEHFrameKeepAlivePass::operator()(), llvm::LessRecordRegister::operator()(), llvm::coverage::CoverageMappingIterator::operator*(), llvm::coverage::CoverageMappingIterator::operator->(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator<(), llvm::FeatureBitset::operator<(), llvm::BitmaskEnumDetail::operator<<(), llvm::Error::operator<<, llvm::GVNExpression::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::rdf::operator<<(), llvm::DDGEdge::operator=(), llvm::DDGEdge::operator=(), llvm::DGEdge< DDGNode, DDGEdge >::operator=(), llvm::EquivalenceClasses< BasicBlock * >::operator=(), llvm::ConstantAggrKeyType< ConstantArray >::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::ConstantPtrAuthKeyType::operator==(), llvm::detail::operator==(), llvm::DGEdge< DDGNode, DDGEdge >::operator==(), llvm::operator==(), llvm::operator==(), llvm::SmallBitVector::operator==(), llvm::BitmaskEnumDetail::operator>>(), llvm::LazyCallGraph::EdgeSequence::operator[](), llvm::BitmaskEnumDetail::operator^(), llvm::BitmaskEnumDetail::operator^=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator^=(), llvm::BitVector::operator^=(), llvm::FeatureBitset::operator^=(), llvm::SmallBitVector::operator^=(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::OperatorInfo(), llvm::BitmaskEnumDetail::operator|(), llvm::BitmaskEnumDetail::operator|=(), llvm::Bitset< AEK_NUM_EXTENSIONS >::operator|=(), llvm::BitVector::operator|=(), llvm::FeatureBitset::operator|=(), llvm::SmallBitVector::operator|=(), llvm::BitmaskEnumDetail::operator~(), OptimizeAwayTrappingUsesOfValue(), optimizeDivRem(), OptimizeExtractBits(), llvm::jitlink::x86::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), OptimizeNonTrivialIFuncs(), llvm::yaml::ScalarTraits< support::detail::packed_endian_specific_integral< value_type, endian, alignment >, std::enable_if_t< has_ScalarTraits< value_type >::value > >::output(), packCmovGroup(), packSegmentMask(), llvm::parallelFor(), llvm::json::parse(), llvm::memprof::YAMLMemProfReader::parse(), parseBackslash(), parseBitcodeFileImpl(), parseBraceExpansions(), AbstractManglingParser< Derived, Alloc >::parseConversionExpr(), AbstractManglingParser< Derived, Alloc >::parseDecltype(), AbstractManglingParser< Derived, Alloc >::parseExpr(), AbstractManglingParser< Derived, Alloc >::parseFunctionType(), parsePhysicalReg(), AbstractManglingParser< Derived, Alloc >::parsePrefixExpr(), percentDecode(), PerformADDVecReduce(), performCopyPropagation(), performExtractsShuffleAction(), PerformReduceShuffleCombine(), PerformTruncatingStoreCombine(), PerformVSELECTCombine(), phiNodeReplacement(), predictValueUseListOrder(), predictValueUseListOrderImpl(), predictValueUseListOrderImpl(), llvm::jitlink::CompactUnwindManager< CURecTraits >::prepareForPrune(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::print(), llvm::LoopBase< BlockT, LoopT >::print(), llvm::LoopInfoBase< BlockT, LoopT >::print(), printConstant(), printCustomRegMask(), llvm::SampleProfileLoaderBaseImpl< FT >::printEdgeWeight(), llvm::SampleProfileLoaderBaseImpl< MachineFunction >::printEdgeWeight(), printFPCLASSComments(), printFunctionArgExts(), ParameterPackExpansion::printLeft(), printMatch(), printMBB(), printMI(), printName(), printName(), printNode(), printNodeDOT(), printNoMatch(), printSpillReloadChain(), printZeroUpperMove(), processLoadCommands(), ProcessMatchResult(), processPSInputArgs(), llvm::product_of(), ProfileListInit(), promoteIndirectCalls(), promoteMemoryToRegister(), llvm::SampleProfileLoaderBaseImpl< FT >::propagateThroughEdges(), llvm::jitlink::prune(), llvm::json::Array::push_back(), llvm::json::Array::push_back(), llvm::LiveRange::Query(), r0(), r1(), r2(), r3(), r4(), llvm::memprof::RawMemProfReader::RawMemProfReader(), llvm::object::DirectX::RootDescriptorView::read(), llvm::support::endian::read16(), llvm::support::endian::read32(), llvm::support::endian::read64(), readCoverageMappingData(), llvm::readDescriptorRanges(), readIdentificationBlock(), readIdentificationCode(), readPropertyValueFromJSON(), llvm::PBQP::Graph< RegAllocSolverImpl >::reconnectEdge(), llvm::LessRecordRegister::RecordParts::RecordParts(), llvm::orc::InProcessMemoryMapper::release(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::release(), llvm::rdf::DataFlowGraph::releaseBlock(), llvm::object::XCOFFObjectFile::relocations(), remapOperands(), llvm::MapVector< StringRef, HashData >::remove_if(), llvm::SmallPtrSetImpl< MachineInstr * >::remove_if(), llvm::DGNode< DDGNode, DDGEdge >::removeEdge(), llvm::PBQP::Graph< RegAllocSolverImpl >::removeEdge(), removeEntryFromStack(), removeGlobalCtors(), llvm::DirectedGraph< DDGNode, DDGEdge >::removeNode(), removeNotes(), reorderReuses(), reorderScalars(), ReplaceAddWithADDP(), replaceAllUsesWith(), replaceAndRemoveSections(), replaceConstantExprOp(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::ConstantUniqueMap< ConstantArray >::replaceOperandsInPlace(), rescheduleCanonically(), llvm::BitVector::reset(), llvm::SmallBitVector::reset(), llvm::SmallBitVector::resize(), llvm::orc::LibraryResolver::SymbolQuery::resolve(), llvm::orc::DylibSymbolResolver::resolveAsync(), AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs(), llvm::mca::ResourceManager::ResourceManager(), rewriteGEPAsOffset(), rewriteMaterializableInstructions(), RewriteUsesOfClonedInstructions(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), ObjCARCContract::run(), runImpl(), llvm::orc::shared::WrapperFunctionCall::runWithSPSRet(), scalarConstantToHexString(), llvm::SchedRegion::SchedRegion(), llvm::object::XCOFFObjectFile::section_rel_end(), llvm::LiveRange::Segment::Segment(), llvm::mca::Scheduler::select(), llvm::memprof::DataAccessProfData::serialize(), llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >::serialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::serialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::serialize(), llvm::BitVector::set(), llvm::SmallBitVector::set(), llvm::set_difference(), llvm::set_intersect(), llvm::set_intersection_impl(), llvm::detail::set_intersects_impl(), llvm::set_subtract(), llvm::set_subtract(), llvm::set_union(), llvm::memprof::DataAccessProfData::setDataAccessProfile(), llvm::MCFragment::setDwarfAddrDelta(), llvm::IndexedInstrProf::Summary::setEntry(), llvm::SPIRVSubtarget::setEnv(), llvm::opt::OptTable::setInitialOptionsFromEnvironment(), llvm::MCFragment::setSFrameAddrDelta(), setupBBInfoEdges(), setupBranchForGuard(), llvm::orc::detail::WaitingOnGraph< JITDylib *, NonOwningSymbolStringPtr >::simplify(), simplifySwitchLookup(), simplifySwitchWhenUMin(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), sinkLastInstruction(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::size(), llvm::rdf::DataFlowGraph::DefStack::size(), skipPGOUse(), skipToNonAllocaInsertPt(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::SmallDenseMap(), llvm::SmallPtrSet< NodeRef, SmallSize >::SmallPtrSet(), llvm::SmallPtrSetIteratorImpl::SmallPtrSetIteratorImpl(), llvm::SmallString< 0 >::SmallString(), llvm::SmallVector< BitWord >::SmallVector(), sortBlocks(), llvm::json::sortedElements(), sortOpts(), llvm::jitlink::splitCompactUnwindBlocks(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::splitCriticalEdge(), llvm::StackMapParser< Endianness >::StackMapParser(), STATISTIC(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::StringMap(), llvm::sum_of(), sumEdgeCount(), llvm::orc::SymbolLookupSet::SymbolLookupSet(), llvm::SysAlias::SysAlias(), llvm::SysAlias::SysAlias(), llvm::SysAliasImm::SysAliasImm(), llvm::SysAliasImm::SysAliasImm(), llvm::SysAliasOptionalReg::SysAliasOptionalReg(), llvm::SysAliasOptionalReg::SysAliasOptionalReg(), llvm::SysAliasReg::SysAliasReg(), llvm::SysAliasReg::SysAliasReg(), llvm::CGDataError::take(), llvm::InstrProfError::take(), tileConfig(), llvm::to_underlying(), tokenizeWindowsCommandLineImpl(), llvm::AArch64::ExtensionSet::toLLVMFeatureList(), llvm::orc::shared::detail::toSPSSerializable(), llvm::detail::toString(), llvm::dwarf::toString(), llvm::dwarf::toString(), toStringAPFloat(), transferSRADebugInfo(), llvm::ImmutableGraphBuilder< MachineGadgetGraph >::trim(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), TryToShrinkGlobalToBoolean(), tryToVectorizeSequence(), llvm::xray::TypedEventRecord::TypedEventRecord(), llvm::BitmaskEnumDetail::Underlying(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_move(), llvm::MemoryPhi::unorderedDeleteIncoming(), llvm::MemoryPhi::unorderedDeleteIncomingIf(), llvm::unwrap(), unwrap(), unwrapExprVar(), updateCGAndAnalysisManagerForPass(), updatePostorderSequenceForEdgeInsertion(), upgrade(), upgradeLoopArgument(), validateInProcess(), llvm::json::OStream::value(), llvm::VarStreamArrayIterator< ValueType, Extractor >::VarStreamArrayIterator(), llvm::VarStreamArrayIterator< ValueType, Extractor >::VarStreamArrayIterator(), VectorizePTXValueVTs(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::LoopBase< BlockT, LoopT >::verifyLoopNest(), llvm::mca::verifyOperands(), llvm::jitlink::aarch32::GOTBuilder::visitEdge(), llvm::jitlink::aarch32::StubsManager_prev7::visitEdge(), llvm::jitlink::aarch32::StubsManager_v7::visitEdge(), llvm::jitlink::aarch64::GOTTableManager::visitEdge(), llvm::jitlink::aarch64::PLTTableManager::visitEdge(), llvm::jitlink::loongarch::GOTTableManager::visitEdge(), llvm::jitlink::loongarch::PLTTableManager::visitEdge(), llvm::jitlink::ppc64::PLTTableManager< Endianness >::visitEdge(), llvm::jitlink::ppc64::TOCTableManager< Endianness >::visitEdge(), llvm::jitlink::visitEdge(), llvm::jitlink::visitEdge(), llvm::jitlink::x86::GOTTableManager::visitEdge(), llvm::jitlink::x86::PLTTableManager::visitEdge(), llvm::jitlink::x86_64::GOTTableManager::visitEdge(), llvm::jitlink::x86_64::PLTTableManager::visitEdge(), llvm::SampleProfileLoaderBaseImpl< FT >::visitEdge(), llvm::SampleProfileLoaderBaseImpl< MachineFunction >::visitEdge(), llvm::Error::visitErrors, llvm::jitlink::visitExistingEdges(), wrap(), llvm::support::endian::write(), llvm::support::endian::write16(), llvm::support::endian::write32(), llvm::support::endian::write64(), writeCOFF(), writeFragment(), llvm::writeMemProfRadixTreeBased(), writeOutput(), and writePublics().