LLVM: lib/Analysis/CallPrinter.cpp File Reference
CallPrinter.cpp File Reference
#include "llvm/Analysis/CallPrinter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/HeatUtils.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/GraphWriter.h"
Classes
class llvm::CallGraphDOTInfo
struct llvm::GraphTraits< CallGraphDOTInfo * >
struct llvm::DOTGraphTraits< CallGraphDOTInfo * >
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
INITIALIZE_PASS(CallGraphViewer, "view-callgraph", "View call graph", false, false) char CallGraphDOTPrinter INITIALIZE_PASS (CallGraphDOTPrinter, "dot-callgraph", "Print call graph to 'dot' file", false, false) ModulePass *llvm
Variables
static cl::opt< bool > ShowHeatColors ("callgraph-heat-colors", cl::init(false), cl::Hidden, cl::desc("Show heat colors in call-graph"))
static cl::opt< bool > ShowEdgeWeight ("callgraph-show-weights", cl::init(false), cl::Hidden, cl::desc("Show edges labeled with weights"))
static cl::opt< bool > CallMultiGraph ("callgraph-multigraph", cl::init(false), cl::Hidden, cl::desc("Show call-multigraph (do not remove parallel edges)"))
static cl::opt< std::string > CallGraphDotFilenamePrefix ("callgraph-dot-filename-prefix", cl::Hidden, cl::desc("The prefix used for the CallGraph dot file names."))
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS(CallGraphViewer, "view-callgraph", "View call graph", false, false) char CallGraphDOTPrinter INITIALIZE_PASS (CallGraphDOTPrinter , "dot-callgraph" , "Print call graph to 'dot' file" , false , false)
Definition at line 346 of file CallPrinter.cpp.
References llvm::createCallGraphViewerPass().
Variable Documentation
CallGraphDotFilenamePrefix
cl::opt< std::string > CallGraphDotFilenamePrefix("callgraph-dot-filename-prefix", cl::Hidden, cl::desc("The prefix used for the CallGraph dot file names.")) ("callgraph-dot-filename-prefix" , cl::Hidden , cl::desc("The prefix used for the CallGraph dot file names.")) static
CallMultiGraph
cl::opt< bool > CallMultiGraph("callgraph-multigraph", cl::init(false), cl::Hidden, cl::desc("Show call-multigraph (do not remove parallel edges)")) ("callgraph-multigraph" , cl::init(false) , cl::Hidden , cl::desc("Show call-multigraph (do not remove parallel edges)")) static
Referenced by llvm::CallGraphDOTInfo::CallGraphDOTInfo(), and llvm::DOTGraphTraits< CallGraphDOTInfo * >::isNodeHidden().
ShowEdgeWeight
cl::opt< bool > ShowEdgeWeight("callgraph-show-weights", cl::init(false), cl::Hidden, cl::desc("Show edges labeled with weights")) ("callgraph-show-weights" , cl::init(false) , cl::Hidden , cl::desc("Show edges labeled with weights")) static
Referenced by llvm::DOTGraphTraits< CallGraphDOTInfo * >::getEdgeAttributes(), viewCFG(), and writeCFGToDotFile().
ShowHeatColors
cl::opt< bool > ShowHeatColors("callgraph-heat-colors", cl::init(false), cl::Hidden, cl::desc("Show heat colors in call-graph")) ("callgraph-heat-colors" , cl::init(false) , cl::Hidden , cl::desc("Show heat colors in call-graph")) static
Referenced by llvm::DOTGraphTraits< CallGraphDOTInfo * >::getNodeAttributes(), viewCFG(), and writeCFGToDotFile().