LLVM: lib/Frontend/HLSL/CBuffer.cpp File Reference
CBuffer.cpp File Reference
#include "llvm/Frontend/HLSL/CBuffer.h"
#include "llvm/Frontend/HLSL/HLSLResource.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
Functions
static SmallVector< size_t > getMemberOffsets (const DataLayout &DL, GlobalVariable *Handle, llvm::function_ref< bool(Type *)> IsPadding)
Function Documentation
getMemberOffsets()
SmallVector< size_t > getMemberOffsets (const DataLayout & DL, GlobalVariable * Handle, llvm::function_ref< bool(Type *)> IsPadding) static
Definition at line 19 of file CBuffer.cpp.
References assert(), llvm::cast(), DL, E(), llvm::StructLayout::getElementOffset(), llvm::GlobalValue::getValueType(), and I.
Referenced by llvm::hlsl::CBufferMetadata::get().