LLVM: lib/Analysis/CFG.cpp File Reference
CFG.cpp File Reference
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/CommandLine.h"
Classes
class SingleEntrySet< T >
Functions
static const Loop * getOutermostLoop (const LoopInfo *LI, const BasicBlock *BB)
template<class StopSetT>
static bool isReachableImpl (SmallVectorImpl< BasicBlock * > &Worklist, const StopSetT &StopSet, const SmallPtrSetImpl< BasicBlock * > *ExclusionSet, const DominatorTree *DT, const LoopInfo *LI)
static bool instructionDoesNotReturn (const Instruction &I)
static bool basicBlockCanReturn (const BasicBlock &BB)
Variables
static cl::opt< unsigned > DefaultMaxBBsToExplore ("dom-tree-reachability-max-bbs-to-explore", cl::Hidden, cl::desc("Max number of BBs to explore for reachability analysis"), cl::init(32))
Function Documentation
basicBlockCanReturn()
bool basicBlockCanReturn (const BasicBlock & BB) static
Definition at line 335 of file CFG.cpp.
References llvm::BasicBlock::getTerminator(), instructionDoesNotReturn(), llvm::isa(), and llvm::none_of().
Referenced by llvm::canReturn().
getOutermostLoop()
const Loop * getOutermostLoop (const LoopInfo * LI, const BasicBlock * BB) static
Definition at line 129 of file CFG.cpp.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor().
Referenced by isReachableImpl().
instructionDoesNotReturn()
bool instructionDoesNotReturn (const Instruction & I) static
Definition at line 327 of file CFG.cpp.
References llvm::dyn_cast(), and I.
Referenced by basicBlockCanReturn().
isReachableImpl()
template<class StopSetT> bool isReachableImpl (SmallVectorImpl< BasicBlock * > & Worklist, const StopSetT & StopSet, const SmallPtrSetImpl< BasicBlock * > * ExclusionSet, const DominatorTree * DT, const LoopInfo * LI) static
Definition at line 135 of file CFG.cpp.
References llvm::any_of(), llvm::SmallVectorImpl< T >::append(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::SmallPtrSetImpl< PtrType >::count(), DefaultMaxBBsToExplore, llvm::DominatorTree::dominates(), llvm::SmallPtrSetImplBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), getOutermostLoop(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::DominatorTree::isReachableFromEntry(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::succ_begin(), and llvm::succ_end().
Referenced by llvm::isManyPotentiallyReachableFromMany(), and llvm::isPotentiallyReachableFromMany().
Variable Documentation
DefaultMaxBBsToExplore
cl::opt< unsigned > DefaultMaxBBsToExplore("dom-tree-reachability-max-bbs-to-explore", cl::Hidden, cl::desc("Max number of BBs to explore for reachability analysis"), cl::init(32)) ("dom-tree-reachability-max-bbs-to-explore" , cl::Hidden , cl::desc("Max number of BBs to explore for reachability analysis") , cl::init(32)) static
Referenced by isReachableImpl().