LLVM: llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size > Class Template Reference
llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size > Class Template Reference
#include "llvm/ADT/EnumeratedArray.h"
Public Types
using iterator = typename ArrayTy::iterator
using const_iterator = typename ArrayTy::const_iterator
using reverse_iterator = typename ArrayTy::reverse_iterator
using const_reverse_iterator = typename ArrayTy::const_reverse_iterator
using value_type = ValueType
using reference = ValueType &
using const_reference = const ValueType &
using pointer = ValueType *
using const_pointer = const ValueType *
Public Member Functions
EnumeratedArray ()=default
EnumeratedArray (ValueType V)
EnumeratedArray (std::initializer_list< ValueType > Init)
const ValueType & operator[] (Enumeration Index) const
ValueType & operator[] (Enumeration Index)
IndexType size () const
bool empty () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
Detailed Description
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)>
class llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >
Definition at line 27 of file EnumeratedArray.h.
Member Typedef Documentation
const_iterator
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::const_iterator = typename ArrayTy::const_iterator
Definition at line 34 of file EnumeratedArray.h.
const_pointer
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::const_pointer = const ValueType *
Definition at line 42 of file EnumeratedArray.h.
const_reference
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::const_reference = const ValueType &
Definition at line 40 of file EnumeratedArray.h.
const_reverse_iterator
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::const_reverse_iterator = typename ArrayTy::const_reverse_iterator
Definition at line 36 of file EnumeratedArray.h.
iterator
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::iterator = typename ArrayTy::iterator
Definition at line 33 of file EnumeratedArray.h.
pointer
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::pointer = ValueType *
Definition at line 41 of file EnumeratedArray.h.
reference
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::reference = ValueType &
Definition at line 39 of file EnumeratedArray.h.
reverse_iterator
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::reverse_iterator = typename ArrayTy::reverse_iterator
Definition at line 35 of file EnumeratedArray.h.
value_type
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> using llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::value_type = ValueType
Definition at line 38 of file EnumeratedArray.h.
Constructor & Destructor Documentation
EnumeratedArray() [1/3]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray () default
Referenced by operator[]().
EnumeratedArray() [2/3]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray (ValueType V) inline
Definition at line 45 of file EnumeratedArray.h.
EnumeratedArray() [3/3]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray (std::initializer_list< ValueType > Init) inline
Definition at line 46 of file EnumeratedArray.h.
References assert(), llvm::copy(), and Size.
Member Function Documentation
begin() [1/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::begin () inline
Definition at line 63 of file EnumeratedArray.h.
begin() [2/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> const_iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::begin () const inline
Definition at line 64 of file EnumeratedArray.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
empty()
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> bool llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::empty () const inline
Definition at line 61 of file EnumeratedArray.h.
References llvm::size().
end() [1/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::end () inline
Definition at line 65 of file EnumeratedArray.h.
end() [2/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> const_iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::end () const inline
Definition at line 66 of file EnumeratedArray.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
operator[]() [1/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> ValueType & llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::operator[] (Enumeration Index) inline
Definition at line 56 of file EnumeratedArray.h.
References EnumeratedArray().
operator[]() [2/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> const ValueType & llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::operator[] (Enumeration Index) const inline
Definition at line 51 of file EnumeratedArray.h.
References assert(), and Size.
rbegin() [1/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> reverse_iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rbegin () inline
Definition at line 68 of file EnumeratedArray.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rbegin().
rbegin() [2/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> const_reverse_iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rbegin () const inline
Definition at line 69 of file EnumeratedArray.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rbegin().
rend() [1/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> reverse_iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rend () inline
Definition at line 70 of file EnumeratedArray.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rend().
rend() [2/2]
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> const_reverse_iterator llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rend () const inline
Definition at line 71 of file EnumeratedArray.h.
References llvm::SmallVectorTemplateCommon< T, typename >::rend().
size()
template<typename ValueType, typename Enumeration, Enumeration LargestEnum = Enumeration::Last, typename IndexType = int, IndexType Size = 1 + static_cast<IndexType>(LargestEnum)> IndexType llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::size () const inline
Definition at line 60 of file EnumeratedArray.h.
References Size.
The documentation for this class was generated from the following file:
include/llvm/ADT/EnumeratedArray.h