LLVM: llvm::ConstantAsMetadata Class Reference
llvm::ConstantAsMetadata Class Reference
#include "llvm/IR/Metadata.h"
Public Member Functions
Constant * getValue () const
Public Member Functions inherited from llvm::ValueAsMetadata
Value * getValue () const
Type * getType () const
LLVMContext & getContext () const
SmallVector< Metadata * > getAllArgListUsers ()
SmallVector< DbgVariableRecord * > getAllDbgVariableRecordUsers ()
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static ConstantAsMetadata * get (Constant *C)
static ConstantAsMetadata * getIfExists (Constant *C)
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::ValueAsMetadata
static LLVM_ABI ValueAsMetadata * get (Value *V)
static ConstantAsMetadata * getConstant (Value *C)
static LocalAsMetadata * getLocal (Value *Local)
static LLVM_ABI ValueAsMetadata * getIfExists (Value *V)
static ConstantAsMetadata * getConstantIfExists (Value *C)
static LocalAsMetadata * getLocalIfExists (Value *Local)
static LLVM_ABI void handleDeletion (Value *V)
static LLVM_ABI void handleRAUW (Value *From, Value *To)
static bool classof (const Metadata *MD)
Friends
class ValueAsMetadata
Additional Inherited Members
Public Types inherited from llvm::Metadata
enum MetadataKind
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::ValueAsMetadata
ValueAsMetadata (unsigned ID, Value *V)
~ValueAsMetadata ()=default
void replaceAllUsesWith (Metadata *MD)
Handle collisions after Value::replaceAllUsesWith().
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Definition at line 529 of file Metadata.h.
Member Function Documentation
classof()
bool llvm::ConstantAsMetadata::classof (const Metadata * MD) inline static
Definition at line 548 of file Metadata.h.
References llvm::Metadata::getMetadataID().
get()
ConstantAsMetadata * llvm::ConstantAsMetadata::get (Constant * C) inline static
Definition at line 536 of file Metadata.h.
References llvm::CallingConv::C, and llvm::ValueAsMetadata::getConstant().
Referenced by addFunctionTypeMutation(), llvm::GlobalObject::addTypeMetadata(), llvm::OpenMPIRBuilder::applySimd(), llvm::GlobalObject::copyMetadata(), createAccessTag(), llvm::DIBuilder::createBitFieldMemberType(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MDBuilder::createConstant(), llvm::DIBuilder::createInheritance(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), createRoundingModeDecoration(), createSaturatedConversionDecoration(), createStringMetadata(), DisableAllLoopOptsOnLoop(), llvm::embedBufferInModule(), emitDXILVersionTupleMD(), emitShaderModelVersionMD(), emitValidatorVersionMD(), llvm::AAMDNodes::extendToTBAA(), llvm::dxil::ResourceInfo::getAsMetadata(), getConstantOrNull(), getEntryPropAsMetadata(), llvm::DIBasicType::getImpl(), getKeyFPValMD(), getKeyValMD(), llvm::MDNode::getMostGenericNoaliasAddrspace(), llvm::MDNode::getMostGenericRange(), llvm::offloading::getOffloadingEntryInitializer(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateSubrange(), getTagValueAsMetadata(), llvm::ValueAsMetadata::handleRAUW(), LLVMMDNodeInContext(), LLVMValueAsMetadata(), lowerPtrAnnotation(), parseAnnotation(), llvm::LoopVectorizeHints::setAlreadyVectorized(), setAssignmentTrackingModuleFlag(), llvm::sandboxir::Region::setAux(), llvm::GlobalObject::setVCallVisibilityMetadata(), llvm::AAMDNodes::shiftTBAAStruct(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::UpgradeModuleFlags(), llvm::UpgradeTBAANode(), and upgradeX86IntrinsicCall().
getIfExists()
ConstantAsMetadata * llvm::ConstantAsMetadata::getIfExists (Constant * C) inline static
Definition at line 540 of file Metadata.h.
References llvm::CallingConv::C, and llvm::ValueAsMetadata::getConstantIfExists().
getValue()
Constant * llvm::ConstantAsMetadata::getValue () const inline
Definition at line 544 of file Metadata.h.
References llvm::cast(), and llvm::ValueAsMetadata::getValue().
Referenced by llvm::MDNodeKeyImpl< DISubrangeType >::getHashValue(), getSummaryFromMD(), llvm::MDNodeKeyImpl< DISubrange >::isKeyOf(), llvm::MDNodeKeyImpl< DISubrangeType >::isKeyOf(), and wrapConstantAsMetadata().
Friends And Related Symbol Documentation
ValueAsMetadata
friend class ValueAsMetadata friend
Definition at line 530 of file Metadata.h.
References llvm::CallingConv::C, and ValueAsMetadata.
Referenced by ValueAsMetadata.
The documentation for this class was generated from the following file:
include/llvm/IR/Metadata.h