LLVM: llvm::SPIRVGlobalRegistry Class Reference
llvm::SPIRVGlobalRegistry Class Reference
#include "Target/SPIRV/SPIRVGlobalRegistry.h"
Public Member Functions
SPIRVGlobalRegistry (unsigned PointerSize)
void setBound (unsigned V)
unsigned getBound ()
void addGlobalObject (const Value *V, const MachineFunction *MF, Register R)
const Value * getGlobalObject (const MachineFunction *MF, Register R)
void addReturnType (const Function *ArgF, TypedPointerType *DerivedTy)
const TypedPointerType * findReturnType (const Function *ArgF)
void addAssignPtrTypeInstr (Value *Val, CallInst *AssignPtrTyCI)
CallInst * findAssignPtrTypeInstr (const Value *Val)
void updateIfExistAssignPtrTypeInstr (Value *OldVal, Value *NewVal, bool DeleteOld)
void addMutated (Value *Val, Type *Ty)
Type * findMutated (const Value *Val)
void addValueAttrs (MachineInstr *Key, std::pair< Type *, std::string > Val)
bool findValueAttrs (const MachineInstr *Key, Type *&Ty, StringRef &Name)
void addDeducedElementType (Value *Val, Type *Ty)
Type * findDeducedElementType (const Value *Val)
void updateIfExistDeducedElementType (Value *OldVal, Value *NewVal, bool DeleteOld)
void addDeducedCompositeType (Value *Val, Type *Ty)
Type * findDeducedCompositeType (const Value *Val)
Type * getDeducedGlobalValueType (const GlobalValue *Global)
const MachineOperand * getFunctionDefinitionByUse (const MachineOperand *Use)
const MachineInstr * getFunctionDefinition (const Function *F)
const Function * getFunctionByDefinition (const MachineInstr *MI)
void recordFunctionPointer (const MachineOperand *MO, const Function *F)
void recordFunctionDefinition (const Function *F, const MachineOperand *MO)
bool hasConstFunPtr ()
void addForwardCall (const Function *F, MachineInstr *MI)
SmallPtrSet< MachineInstr *, 8 > * getForwardCalls (const Function *F)
SPIRVType * assignTypeToVReg (const Type *Type, Register VReg, MachineIRBuilder &MIRBuilder, SPIRV::AccessQualifier::AccessQualifier AQ, bool EmitIR)
SPIRVType * assignIntTypeToVReg (unsigned BitWidth, Register VReg, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * assignFloatTypeToVReg (unsigned BitWidth, Register VReg, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * assignVectTypeToVReg (SPIRVType *BaseType, unsigned NumElements, Register VReg, MachineInstr &I, const SPIRVInstrInfo &TII)
void assignSPIRVTypeToVReg (SPIRVType *Type, Register VReg, const MachineFunction &MF)
SPIRVType * getOrCreateSPIRVType (const Type *Type, MachineInstr &I, SPIRV::AccessQualifier::AccessQualifier AQ, bool EmitIR)
SPIRVType * getOrCreateSPIRVType (const Type *Type, MachineIRBuilder &MIRBuilder, SPIRV::AccessQualifier::AccessQualifier AQ, bool EmitIR)
const Type * getTypeForSPIRVType (const SPIRVType *Ty) const
SPIRVType * getPointeeType (SPIRVType *PtrType)
unsigned getPointeeTypeOp (Register PtrReg)
SPIRVType * getOrCreateSPIRVTypeByName (StringRef TypeStr, MachineIRBuilder &MIRBuilder, bool EmitIR, SPIRV::StorageClass::StorageClass SC=SPIRV::StorageClass::Function, SPIRV::AccessQualifier::AccessQualifier AQ=SPIRV::AccessQualifier::ReadWrite)
SPIRVType * getSPIRVTypeForVReg (Register VReg, const MachineFunction *MF=nullptr) const
SPIRVType * getResultType (Register VReg, MachineFunction *MF=nullptr)
bool hasSPIRVTypeForVReg (Register VReg) const
Register getSPIRVTypeID (const SPIRVType *SpirvType) const
MachineFunction * setCurrentFunc (MachineFunction &MF)
bool isAggregateType (SPIRVType *Type) const
bool isScalarOfType (Register VReg, unsigned TypeOpcode) const
bool isScalarOrVectorOfType (Register VReg, unsigned TypeOpcode) const
bool isResourceType (SPIRVType *Type) const
unsigned getScalarOrVectorComponentCount (Register VReg) const
unsigned getScalarOrVectorComponentCount (SPIRVType *Type) const
SPIRVType * getScalarOrVectorComponentType (Register VReg) const
SPIRVType * getScalarOrVectorComponentType (SPIRVType *Type) const
unsigned getScalarOrVectorBitWidth (const SPIRVType *Type) const
unsigned getNumScalarOrVectorTotalBitWidth (const SPIRVType *Type) const
const SPIRVType * retrieveScalarOrVectorIntType (const SPIRVType *Type) const
bool isScalarOrVectorSigned (const SPIRVType *Type) const
SPIRV::StorageClass::StorageClass getPointerStorageClass (Register VReg) const
SPIRV::StorageClass::StorageClass getPointerStorageClass (const SPIRVType *Type) const
unsigned getPointerSize () const
bool isBitcastCompatible (const SPIRVType *Type1, const SPIRVType *Type2) const
void invalidateMachineInstr (MachineInstr *MI)
Register buildConstantInt (uint64_t Val, MachineIRBuilder &MIRBuilder, SPIRVType *SpvType, bool EmitIR, bool ZeroAsNull=true)
Register getOrCreateConstInt (uint64_t Val, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII, bool ZeroAsNull=true)
Register createConstInt (const ConstantInt *CI, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII, bool ZeroAsNull)
Register getOrCreateConstFP (APFloat Val, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII, bool ZeroAsNull=true)
Register createConstFP (const ConstantFP *CF, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII, bool ZeroAsNull)
Register buildConstantFP (APFloat Val, MachineIRBuilder &MIRBuilder, SPIRVType *SpvType=nullptr)
Register getOrCreateConstVector (uint64_t Val, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII, bool ZeroAsNull=true)
Register getOrCreateConstVector (APFloat Val, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII, bool ZeroAsNull=true)
Register getOrCreateConstIntArray (uint64_t Val, size_t Num, MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII)
Register getOrCreateConsIntVector (uint64_t Val, MachineIRBuilder &MIRBuilder, SPIRVType *SpvType, bool EmitIR)
Register getOrCreateConstNullPtr (MachineIRBuilder &MIRBuilder, SPIRVType *SpvType)
Register buildConstantSampler (Register Res, unsigned AddrMode, unsigned Param, unsigned FilerMode, MachineIRBuilder &MIRBuilder)
Register getOrCreateUndef (MachineInstr &I, SPIRVType *SpvType, const SPIRVInstrInfo &TII)
Register buildGlobalVariable (Register Reg, SPIRVType *BaseType, StringRef Name, const GlobalValue *GV, SPIRV::StorageClass::StorageClass Storage, const MachineInstr *Init, bool IsConst, const std::optional< SPIRV::LinkageType::LinkageType > &LinkageType, MachineIRBuilder &MIRBuilder, bool IsInstSelector)
Register getOrCreateGlobalVariableWithBinding (const SPIRVType *VarType, uint32_t Set, uint32_t Binding, StringRef Name, MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * getOrCreateSPIRVType (unsigned BitWidth, MachineInstr &I, const SPIRVInstrInfo &TII, unsigned SPIRVOPcode, Type *LLVMTy)
SPIRVType * getOrCreateSPIRVFloatType (unsigned BitWidth, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * getOrCreateSPIRVBoolType (MachineIRBuilder &MIRBuilder, bool EmitIR)
SPIRVType * getOrCreateSPIRVBoolType (MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * getOrCreateSPIRVVectorType (SPIRVType *BaseType, unsigned NumElements, MachineIRBuilder &MIRBuilder, bool EmitIR)
SPIRVType * getOrCreateSPIRVVectorType (SPIRVType *BaseType, unsigned NumElements, MachineInstr &I, const SPIRVInstrInfo &TII)
SPIRVType * getOrCreateSPIRVPointerType (const Type *BaseType, MachineIRBuilder &MIRBuilder, SPIRV::StorageClass::StorageClass SC)
SPIRVType * getOrCreateSPIRVPointerType (const Type *BaseType, MachineInstr &I, SPIRV::StorageClass::StorageClass SC)
SPIRVType * getOrCreateSPIRVPointerType (SPIRVType *BaseType, MachineIRBuilder &MIRBuilder, SPIRV::StorageClass::StorageClass SC)
SPIRVType * changePointerStorageClass (SPIRVType *PtrType, SPIRV::StorageClass::StorageClass SC, MachineInstr &I)
SPIRVType * getOrCreateVulkanBufferType (MachineIRBuilder &MIRBuilder, Type *ElemType, SPIRV::StorageClass::StorageClass SC, bool IsWritable, bool EmitIr=false)
SPIRVType * getOrCreatePaddingType (MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateVulkanPushConstantType (MachineIRBuilder &MIRBuilder, Type *ElemType)
SPIRVType * getOrCreateLayoutType (MachineIRBuilder &MIRBuilder, const TargetExtType *T, bool EmitIr=false)
SPIRVType * getImageType (const TargetExtType *ExtensionType, const SPIRV::AccessQualifier::AccessQualifier Qualifier, MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateOpTypeSampler (MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateOpTypeSampledImage (SPIRVType *ImageType, MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateOpTypeCoopMatr (MachineIRBuilder &MIRBuilder, const TargetExtType *ExtensionType, const SPIRVType *ElemType, uint32_t Scope, uint32_t Rows, uint32_t Columns, uint32_t Use, bool EmitIR)
SPIRVType * getOrCreateOpTypePipe (MachineIRBuilder &MIRBuilder, SPIRV::AccessQualifier::AccessQualifier AccQual)
SPIRVType * getOrCreateOpTypeDeviceEvent (MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateOpTypeFunctionWithArgs (const Type *Ty, SPIRVType *RetType, const SmallVectorImpl< SPIRVType * > &ArgTypes, MachineIRBuilder &MIRBuilder)
SPIRVType * getOrCreateOpTypeByOpcode (const Type *Ty, MachineIRBuilder &MIRBuilder, unsigned Opcode)
SPIRVType * getOrCreateUnknownType (const Type *Ty, MachineIRBuilder &MIRBuilder, unsigned Opcode, const ArrayRef< MCOperand > Operands)
const TargetRegisterClass * getRegClass (SPIRVType *SpvType) const
LLT getRegType (SPIRVType *SpvType) const
MachineInstr * getOrAddMemAliasingINTELInst (MachineIRBuilder &MIRBuilder, const MDNode *AliasingListMD)
void buildMemAliasingOpDecorate (Register Reg, MachineIRBuilder &MIRBuilder, uint32_t Dec, const MDNode *GVarMD)
void replaceAllUsesWith (Value *Old, Value *New, bool DeleteOld=true)
void buildAssignType (IRBuilder<> &B, Type *Ty, Value *Arg)
void buildAssignPtr (IRBuilder<> &B, Type *ElemTy, Value *Arg)
void updateAssignType (CallInst *AssignCI, Value *Arg, Value *OfType)
Public Member Functions inherited from llvm::SPIRVIRMapping
bool add (SPIRV::IRHandle Handle, const MachineInstr *MI)
bool erase (const MachineInstr *MI)
const MachineInstr * findMI (SPIRV::IRHandle Handle, const MachineFunction *MF)
Register find (SPIRV::IRHandle Handle, const MachineFunction *MF)
bool add (const Type *PointeeTy, unsigned AddressSpace, const MachineInstr *MI)
Register find (const Type *PointeeTy, unsigned AddressSpace, const MachineFunction *MF)
const MachineInstr * findMI (const Type *PointeeTy, unsigned AddressSpace, const MachineFunction *MF)
bool add (const Value *V, const MachineInstr *MI)
bool add (const Type *T, bool RequiresExplicitLayout, const MachineInstr *MI)
bool add (const MachineInstr *Obj, const MachineInstr *MI)
Register find (const Value *V, const MachineFunction *MF)
Register find (const Type *T, bool RequiresExplicitLayout, const MachineFunction *MF)
Register find (const MachineInstr *MI, const MachineFunction *MF)
const MachineInstr * findMI (const Value *Obj, const MachineFunction *MF)
const MachineInstr * findMI (const Type *T, bool RequiresExplicitLayout, const MachineFunction *MF)
const MachineInstr * findMI (const MachineInstr *Obj, const MachineFunction *MF)
Public Attributes
MachineFunction * CurMF
Detailed Description
Definition at line 31 of file SPIRVGlobalRegistry.h.
Constructor & Destructor Documentation
SPIRVGlobalRegistry()
SPIRVGlobalRegistry::SPIRVGlobalRegistry (unsigned PointerSize)
Definition at line 91 of file SPIRVGlobalRegistry.cpp.
References CurMF, and nullptr.
Member Function Documentation
addAssignPtrTypeInstr()
void llvm::SPIRVGlobalRegistry::addAssignPtrTypeInstr (Value * Val, CallInst * AssignPtrTyCI) inline
Definition at line 138 of file SPIRVGlobalRegistry.h.
Referenced by buildAssignPtr(), and buildAssignType().
addDeducedCompositeType()
void llvm::SPIRVGlobalRegistry::addDeducedCompositeType (Value * Val, Type * Ty) inline
Definition at line 199 of file SPIRVGlobalRegistry.h.
addDeducedElementType()
void llvm::SPIRVGlobalRegistry::addDeducedElementType (Value * Val, Type * Ty) inline
Definition at line 183 of file SPIRVGlobalRegistry.h.
Referenced by buildAssignPtr(), and updateAssignType().
addForwardCall()
void llvm::SPIRVGlobalRegistry::addForwardCall (const Function * F, MachineInstr * MI) inline
Definition at line 269 of file SPIRVGlobalRegistry.h.
References F, and MI.
Referenced by llvm::SPIRVTargetLowering::finalizeLowering().
addGlobalObject()
void llvm::SPIRVGlobalRegistry::addGlobalObject (const Value * V, const MachineFunction * MF, Register R) inline
Definition at line 118 of file SPIRVGlobalRegistry.h.
Referenced by addConstantsToTrack(), and buildGlobalVariable().
addMutated()
void llvm::SPIRVGlobalRegistry::addMutated (Value * Val, Type * Ty) inline
Definition at line 159 of file SPIRVGlobalRegistry.h.
addReturnType()
void llvm::SPIRVGlobalRegistry::addReturnType (const Function * ArgF, TypedPointerType * DerivedTy) inline
Definition at line 127 of file SPIRVGlobalRegistry.h.
addValueAttrs()
void llvm::SPIRVGlobalRegistry::addValueAttrs (MachineInstr * Key, std::pair< Type *, std::string > Val) inline
Definition at line 168 of file SPIRVGlobalRegistry.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by generateAssignInstrs().
assignFloatTypeToVReg()
SPIRVType * SPIRVGlobalRegistry::assignFloatTypeToVReg (unsigned BitWidth, Register VReg, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 104 of file SPIRVGlobalRegistry.cpp.
References assignSPIRVTypeToVReg(), llvm::BitWidth, CurMF, getOrCreateSPIRVFloatType(), I, and TII.
assignIntTypeToVReg()
SPIRVType * SPIRVGlobalRegistry::assignIntTypeToVReg (unsigned BitWidth, Register VReg, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 94 of file SPIRVGlobalRegistry.cpp.
References assignSPIRVTypeToVReg(), llvm::BitWidth, CurMF, getOrCreateSPIRVIntegerType(), I, and TII.
Referenced by createConstInt().
assignSPIRVTypeToVReg()
void SPIRVGlobalRegistry::assignSPIRVTypeToVReg (SPIRVType * Type, Register VReg, const MachineFunction & MF)
Definition at line 130 of file SPIRVGlobalRegistry.cpp.
Referenced by assignFloatTypeToVReg(), assignIntTypeToVReg(), assignTypeToVReg(), assignVectTypeToVReg(), llvm::buildAPFixedPointInst(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicRMWInst(), llvm::buildBoolRegister(), buildConstantFP(), llvm::buildEnqueueKernel(), buildGlobalVariable(), llvm::buildNDRange(), convertPtrToInt(), createConstFP(), llvm::createVirtualRegister(), deduceAndAssignSpirvType(), generateAssignType(), llvm::generateGroupInst(), llvm::generateICarryBorrowInst(), llvm::generateImageSizeQueryInst(), llvm::generateReadImageInst(), llvm::genWorkgroupQuery(), getOrCreateConstNullPtr(), getOrCreateUndef(), insertBitcasts(), insertInlineAsmProcess(), legalizeSpvExtractElt(), legalizeSpvInsertElt(), llvm::processInstr(), propagateSPIRVType(), llvm::setRegClassType(), and llvm::updateRegType().
assignTypeToVReg()
SPIRVType * SPIRVGlobalRegistry::assignTypeToVReg (const Type * Type, Register VReg, MachineIRBuilder & MIRBuilder, SPIRV::AccessQualifier::AccessQualifier AQ, bool EmitIR)
Definition at line 121 of file SPIRVGlobalRegistry.cpp.
References assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::getMF(), and getOrCreateSPIRVType().
Referenced by buildConstantInt().
assignVectTypeToVReg()
SPIRVType * SPIRVGlobalRegistry::assignVectTypeToVReg (SPIRVType * BaseType, unsigned NumElements, Register VReg, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 112 of file SPIRVGlobalRegistry.cpp.
References assignSPIRVTypeToVReg(), CurMF, getOrCreateSPIRVVectorType(), I, and TII.
buildAssignPtr()
void SPIRVGlobalRegistry::buildAssignPtr (IRBuilder<> & B, Type * ElemTy, Value * Arg)
Definition at line 2141 of file SPIRVGlobalRegistry.cpp.
References addAssignPtrTypeInstr(), addDeducedElementType(), B(), llvm::buildIntrWithMD(), findAssignPtrTypeInstr(), llvm::PoisonValue::get(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::getPointerAddressSpace(), llvm::Value::getType(), and updateAssignType().
Referenced by replacePushConstantAccesses().
buildAssignType()
void SPIRVGlobalRegistry::buildAssignType (IRBuilder<> & B, Type * Ty, Value * Arg)
Definition at line 2121 of file SPIRVGlobalRegistry.cpp.
References addAssignPtrTypeInstr(), allowEmitFakeUse(), B(), llvm::buildIntrWithMD(), llvm::MDNode::get(), llvm::MDString::get(), llvm::MDTuple::get(), llvm::MetadataAsValue::get(), llvm::ValueAsMetadata::getConstant(), llvm::Value::getContext(), llvm::Value::getName(), llvm::getNormalizedPoisonValue(), llvm::Value::getType(), and llvm::Type::isAggregateType().
buildConstantFP()
Register SPIRVGlobalRegistry::buildConstantFP (APFloat Val, MachineIRBuilder & MIRBuilder, SPIRVType * SpvType = nullptr)
Definition at line 481 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::addNumImm(), llvm::MachineInstrBuilder::addUse(), assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildInstr(), llvm::SPIRVIRMapping::find(), llvm::Type::getFloatTy(), llvm::MachineIRBuilder::getMF(), getOrCreateSPIRVType(), getScalarOrVectorBitWidth(), getSPIRVTypeID(), llvm::Register::isValid(), and llvm::LLT::scalar().
Referenced by llvm::generateReadImageInst().
buildConstantInt()
Register SPIRVGlobalRegistry::buildConstantInt (uint64_t Val, MachineIRBuilder & MIRBuilder, SPIRVType * SpvType, bool EmitIR, bool ZeroAsNull = true)
Definition at line 432 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::addNumImm(), llvm::MachineInstrBuilder::addUse(), assert(), assignTypeToVReg(), llvm::BitWidth, llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildInstr(), llvm::cast(), llvm::constrainSelectedInstRegOperands(), CurMF, llvm::SPIRVIRMapping::find(), llvm::MachineIRBuilder::getMF(), getScalarOrVectorBitWidth(), getSPIRVTypeID(), getTypeForSPIRVType(), llvm::Register::isValid(), MRI, and llvm::LLT::scalar().
Referenced by llvm::buildConstantIntReg32(), llvm::buildNDRange(), llvm::buildSelectInst(), llvm::generateGroupInst(), llvm::genWorkgroupQuery(), llvm::getInlineSpirvType(), and getOrCreateOpTypeCoopMatr().
buildConstantSampler()
Register SPIRVGlobalRegistry::buildConstantSampler (Register Res, unsigned AddrMode, unsigned Param, unsigned FilerMode, MachineIRBuilder & MIRBuilder)
Definition at line 723 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineIRBuilder::getMRI(), getOrCreateOpTypeSampler(), getSPIRVTypeID(), and llvm::Register::isValid().
Referenced by llvm::generateReadImageInst(), and llvm::generateSampleImageInst().
buildGlobalVariable()
Register SPIRVGlobalRegistry::buildGlobalVariable (Register Reg, SPIRVType * BaseType, StringRef Name, const GlobalValue * GV, SPIRV::StorageClass::StorageClass Storage, const MachineInstr * Init, bool IsConst, const std::optional< SPIRV::LinkageType::LinkageType > & LinkageType, MachineIRBuilder & MIRBuilder, bool IsInstSelector)
Definition at line 746 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), addGlobalObject(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildCopy(), llvm::MachineIRBuilder::buildInstr(), llvm::buildOpDecorate(), llvm::buildOpName(), llvm::buildOpSpirvDecorations(), llvm::cast(), llvm::constrainSelectedInstRegOperands(), CurMF, llvm::GlobalValue::ExternalLinkage, llvm::SPIRVIRMapping::find(), llvm::GlobalVariable::getAlign(), llvm::MachineFunction::getFunction(), llvm::GlobalObject::getMetadata(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::Value::getName(), llvm::MachineInstr::getOperand(), llvm::GlobalValue::getParent(), getPointerSize(), llvm::MachineOperand::getReg(), llvm::getSpirvBuiltInIdByName(), getSPIRVTypeForVReg(), getSPIRVTypeID(), llvm::MachineFunction::getSubtarget(), getTypeForSPIRVType(), llvm::Value::hasName(), MRI, llvm::LLT::pointer(), llvm::Align::value(), and llvm::MaybeAlign::valueOrOne().
Referenced by getOrCreateGlobalVariableWithBinding().
buildMemAliasingOpDecorate()
void SPIRVGlobalRegistry::buildMemAliasingOpDecorate (Register Reg, MachineIRBuilder & MIRBuilder, uint32_t Dec, const MDNode * GVarMD)
Definition at line 2102 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstr::getOperand(), getOrAddMemAliasingINTELInst(), and llvm::MachineOperand::getReg().
Referenced by insertSpirvDecorations().
changePointerStorageClass()
SPIRVType * SPIRVGlobalRegistry::changePointerStorageClass (SPIRVType * PtrType, SPIRV::StorageClass::StorageClass SC, MachineInstr & I)
Definition at line 1909 of file SPIRVGlobalRegistry.cpp.
References assert(), getPointeeType(), getPointerStorageClass(), I, and storageClassRequiresExplictLayout().
Referenced by propagateSPIRVType().
createConstFP()
Register SPIRVGlobalRegistry::createConstFP (const ConstantFP * CF, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII, bool ZeroAsNull)
Definition at line 339 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::addNumImm(), llvm::MachineInstrBuilder::addUse(), assignSPIRVTypeToVReg(), llvm::APFloat::bitcastToAPInt(), llvm::BitWidth, llvm::MachineIRBuilder::buildInstr(), llvm::constrainSelectedInstRegOperands(), CurMF, llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getParent(), getScalarOrVectorBitWidth(), getSPIRVTypeID(), llvm::ConstantFP::getValue(), llvm::ConstantFP::getValueAPF(), llvm::APInt::getZExtValue(), I, llvm::APFloat::isPosZero(), llvm::LLT::scalar(), and TII.
Referenced by getOrCreateConstFP().
createConstInt()
Register SPIRVGlobalRegistry::createConstInt (const ConstantInt * CI, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII, bool ZeroAsNull)
Definition at line 390 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::addNumImm(), llvm::MachineInstrBuilder::addUse(), assignIntTypeToVReg(), llvm::BitWidth, llvm::MachineIRBuilder::buildInstr(), llvm::constrainSelectedInstRegOperands(), CurMF, llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getParent(), getScalarOrVectorBitWidth(), getSPIRVTypeID(), llvm::ConstantInt::getValue(), I, llvm::ConstantInt::isZero(), llvm::LLT::scalar(), and TII.
Referenced by getOrCreateConstInt().
findAssignPtrTypeInstr()
CallInst * llvm::SPIRVGlobalRegistry::findAssignPtrTypeInstr (const Value * Val) inline
Definition at line 142 of file SPIRVGlobalRegistry.h.
References nullptr.
Referenced by buildAssignPtr(), and updateIfExistAssignPtrTypeInstr().
findDeducedCompositeType()
Type * llvm::SPIRVGlobalRegistry::findDeducedCompositeType (const Value * Val) inline
Definition at line 203 of file SPIRVGlobalRegistry.h.
References nullptr.
Referenced by getDeducedGlobalValueType().
findDeducedElementType()
Type * llvm::SPIRVGlobalRegistry::findDeducedElementType (const Value * Val) inline
Definition at line 185 of file SPIRVGlobalRegistry.h.
References nullptr.
Referenced by getAtomicElemTy(), getDeducedGlobalValueType(), getFunctionPointerElemType(), and updateIfExistDeducedElementType().
findMutated()
Type * llvm::SPIRVGlobalRegistry::findMutated (const Value * Val) inline
Definition at line 161 of file SPIRVGlobalRegistry.h.
References nullptr.
Referenced by restoreMutatedType().
findReturnType()
const TypedPointerType * llvm::SPIRVGlobalRegistry::findReturnType (const Function * ArgF) inline
Definition at line 131 of file SPIRVGlobalRegistry.h.
References nullptr.
findValueAttrs()
bool llvm::SPIRVGlobalRegistry::findValueAttrs (const MachineInstr * Key, Type *& Ty, StringRef & Name) inline
Definition at line 172 of file SPIRVGlobalRegistry.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
getBound()
unsigned llvm::SPIRVGlobalRegistry::getBound () inline
Definition at line 116 of file SPIRVGlobalRegistry.h.
getDeducedGlobalValueType()
Type * llvm::SPIRVGlobalRegistry::getDeducedGlobalValueType (const GlobalValue * Global) inline
Definition at line 208 of file SPIRVGlobalRegistry.h.
References llvm::dyn_cast(), findDeducedCompositeType(), findDeducedElementType(), llvm::SPIRV::getOriginalFunctionType(), and llvm::Global.
Referenced by propagateSPIRVType().
getForwardCalls()
SmallPtrSet< MachineInstr *, 8 > * llvm::SPIRVGlobalRegistry::getForwardCalls (const Function * F) inline
Definition at line 275 of file SPIRVGlobalRegistry.h.
References F, and nullptr.
Referenced by validateForwardCalls().
getFunctionByDefinition()
const Function * llvm::SPIRVGlobalRegistry::getFunctionByDefinition (const MachineInstr * MI) inline
Definition at line 246 of file SPIRVGlobalRegistry.h.
References llvm::Function::end(), MI, and nullptr.
Referenced by validateForwardCalls().
getFunctionDefinition()
const MachineInstr * llvm::SPIRVGlobalRegistry::getFunctionDefinition (const Function * F) inline
Definition at line 237 of file SPIRVGlobalRegistry.h.
References F, and nullptr.
Referenced by validateFunCall().
getFunctionDefinitionByUse()
const MachineOperand * llvm::SPIRVGlobalRegistry::getFunctionDefinitionByUse (const MachineOperand * Use) inline
Definition at line 227 of file SPIRVGlobalRegistry.h.
References nullptr.
getGlobalObject()
const Value * llvm::SPIRVGlobalRegistry::getGlobalObject (const MachineFunction * MF, Register R) inline
Definition at line 121 of file SPIRVGlobalRegistry.h.
References nullptr.
getImageType()
SPIRVType * SPIRVGlobalRegistry::getImageType (const TargetExtType * ExtensionType, const SPIRV::AccessQualifier::AccessQualifier Qualifier, MachineIRBuilder & MIRBuilder)
Definition at line 1523 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::TargetExtType::getIntParameter(), llvm::TargetExtType::getNumIntParameters(), llvm::TargetExtType::getNumTypeParameters(), getOrCreateSPIRVType(), and llvm::TargetExtType::getTypeParameter().
Referenced by llvm::getSampledImageType(), and llvm::SPIRV::lowerBuiltinType().
getNumScalarOrVectorTotalBitWidth()
unsigned SPIRVGlobalRegistry::getNumScalarOrVectorTotalBitWidth (const SPIRVType * Type) const
Definition at line 1365 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::getImm(), and getSPIRVTypeForVReg().
Referenced by isBitcastCompatible().
getOrAddMemAliasingINTELInst()
MachineInstr * SPIRVGlobalRegistry::getOrAddMemAliasingINTELInst (MachineIRBuilder & MIRBuilder, const MDNode * AliasingListMD)
Definition at line 2051 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), D(), llvm::dyn_cast(), llvm::MachineInstrBuilder::getInstr(), llvm::MachineIRBuilder::getMRI(), llvm::MDNode::getNumOperands(), llvm::MachineInstr::insert(), MRI, llvm::MDNode::operands(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by addMemoryOperands(), and buildMemAliasingOpDecorate().
getOrCreateConsIntVector()
Register SPIRVGlobalRegistry::getOrCreateConsIntVector (uint64_t Val, MachineIRBuilder & MIRBuilder, SPIRVType * SpvType, bool EmitIR)
Definition at line 678 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::cast(), llvm::VectorType::getElementCount(), llvm::VectorType::getElementType(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), getScalarOrVectorBitWidth(), llvm::ConstantVector::getSplat(), getTypeForSPIRVType(), and llvm::Type::isVectorTy().
Referenced by llvm::buildSelectInst().
getOrCreateConstFP()
Register SPIRVGlobalRegistry::getOrCreateConstFP (APFloat Val, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII, bool ZeroAsNull = true)
Definition at line 326 of file SPIRVGlobalRegistry.cpp.
References createConstFP(), CurMF, llvm::SPIRVIRMapping::findMI(), I, MI, and TII.
getOrCreateConstInt()
Register SPIRVGlobalRegistry::getOrCreateConstInt (uint64_t Val, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII, bool ZeroAsNull = true)
Definition at line 377 of file SPIRVGlobalRegistry.cpp.
References llvm::cast(), createConstInt(), CurMF, llvm::SPIRVIRMapping::findMI(), getTypeForSPIRVType(), I, MI, and TII.
getOrCreateConstIntArray()
Register SPIRVGlobalRegistry::getOrCreateConstIntArray (uint64_t Val, size_t Num, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII)
Definition at line 614 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::cast(), llvm::PoisonValue::get(), llvm::ConstantStruct::getAnon(), llvm::ArrayType::getElementType(), llvm::ArrayType::getNumElements(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getScalarOrVectorBitWidth(), getSPIRVTypeForVReg(), getTypeForSPIRVType(), I, llvm::Type::isArrayTy(), and TII.
Referenced by llvm::buildNDRange().
getOrCreateConstNullPtr()
Register SPIRVGlobalRegistry::getOrCreateConstNullPtr (MachineIRBuilder & MIRBuilder, SPIRVType * SpvType)
Definition at line 695 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildInstr(), CurMF, llvm::dyn_cast(), llvm::SPIRVIRMapping::find(), llvm::ConstantTargetNone::get(), getPointeeType(), getSPIRVTypeID(), llvm::getTypedPointerWrapper(), getTypeForSPIRVType(), llvm::Register::isValid(), llvm::LLT::pointer(), and typeToAddressSpace().
Referenced by llvm::buildEnqueueKernel().
getOrCreateConstVector() [1/2]
Register SPIRVGlobalRegistry::getOrCreateConstVector (APFloat Val, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII, bool ZeroAsNull = true)
Definition at line 595 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::cast(), llvm::VectorType::getElementCount(), llvm::VectorType::getElementType(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), getScalarOrVectorBitWidth(), llvm::ConstantVector::getSplat(), getTypeForSPIRVType(), I, llvm::Type::isFloatingPointTy(), llvm::Type::isVectorTy(), and TII.
getOrCreateConstVector() [2/2]
Register SPIRVGlobalRegistry::getOrCreateConstVector (uint64_t Val, MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII, bool ZeroAsNull = true)
Definition at line 576 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::cast(), llvm::VectorType::getElementCount(), llvm::VectorType::getElementType(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), getScalarOrVectorBitWidth(), llvm::ConstantVector::getSplat(), getTypeForSPIRVType(), I, llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), and TII.
getOrCreateGlobalVariableWithBinding()
Register SPIRVGlobalRegistry::getOrCreateGlobalVariableWithBinding (const SPIRVType * VarType, uint32_t Set, uint32_t Binding, StringRef Name, MachineIRBuilder & MIRBuilder)
Definition at line 851 of file SPIRVGlobalRegistry.cpp.
References buildGlobalVariable(), llvm::buildOpDecorate(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineIRBuilder::getMRI(), and getPointerStorageClass().
getOrCreateLayoutType()
SPIRVType * SPIRVGlobalRegistry::getOrCreateLayoutType (MachineIRBuilder & MIRBuilder, const TargetExtType * T, bool EmitIr = false)
Definition at line 1496 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), assert(), llvm::buildOpMemberDecorate(), llvm::cast(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), llvm::SPIRV::handle(), I, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, MI, and T.
Referenced by llvm::getLayoutType().
getOrCreateOpTypeByOpcode()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode (const Type * Ty, MachineIRBuilder & MIRBuilder, unsigned Opcode)
Definition at line 1679 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineIRBuilder::buildInstr(), createTypeVReg(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), and MI.
Referenced by llvm::getNonParameterizedType().
getOrCreateOpTypeCoopMatr()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr (MachineIRBuilder & MIRBuilder, const TargetExtType * ExtensionType, const SPIRVType * ElemType, uint32_t Scope, uint32_t Rows, uint32_t Columns, uint32_t Use, bool EmitIR)
Definition at line 1650 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), buildConstantInt(), llvm::MachineIRBuilder::buildInstr(), llvm::cast(), createTypeVReg(), llvm::SPIRVIRMapping::findMI(), llvm::Type::getIntegerBitWidth(), llvm::MachineIRBuilder::getMF(), getOrCreateSPIRVIntegerType(), getSPIRVTypeID(), llvm::MachineFunction::getSubtarget(), getTypeForSPIRVType(), llvm::Type::isIntegerTy(), and MI.
Referenced by llvm::getCoopMatrType().
getOrCreateOpTypeDeviceEvent()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent (MachineIRBuilder & MIRBuilder)
Definition at line 1618 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineIRBuilder::buildInstr(), createTypeVReg(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::SPIRV::irhandle_event(), and MI.
Referenced by llvm::SPIRV::lowerBuiltinType().
getOrCreateOpTypeFunctionWithArgs()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypeFunctionWithArgs (const Type * Ty, SPIRVType * RetType, const SmallVectorImpl< SPIRVType * > & ArgTypes, MachineIRBuilder & MIRBuilder)
Definition at line 1039 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::cast(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), and MI.
Referenced by insertInlineAsmProcess().
getOrCreateOpTypePipe()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypePipe (MachineIRBuilder & MIRBuilder, SPIRV::AccessQualifier::AccessQualifier AccQual)
Definition at line 1602 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineIRBuilder::buildInstr(), createTypeVReg(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::SPIRV::irhandle_pipe(), and MI.
Referenced by llvm::getPipeType().
getOrCreateOpTypeSampledImage()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage (SPIRVType * ImageType, MachineIRBuilder & MIRBuilder)
Definition at line 1632 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), createTypeVReg(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getSPIRVTypeID(), llvm::MachineRegisterInfo::getVRegDef(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::SPIRV::irhandle_sampled_image(), and MI.
Referenced by llvm::generateReadImageInst(), llvm::generateSampleImageInst(), and llvm::getSampledImageType().
getOrCreateOpTypeSampler()
SPIRVType * SPIRVGlobalRegistry::getOrCreateOpTypeSampler (MachineIRBuilder & MIRBuilder)
Definition at line 1588 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineIRBuilder::buildInstr(), createTypeVReg(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::SPIRV::irhandle_sampler(), and MI.
Referenced by buildConstantSampler(), and llvm::getSamplerType().
getOrCreatePaddingType()
SPIRVType * SPIRVGlobalRegistry::getOrCreatePaddingType (MachineIRBuilder & MIRBuilder)
Definition at line 1464 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getContext(), llvm::Type::getInt8Ty(), llvm::MachineIRBuilder::getMF(), getOrCreateSPIRVIntegerType(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::SPIRV::irhandle_padding(), MI, and T.
Referenced by llvm::SPIRV::lowerBuiltinType().
getOrCreateSPIRVBoolType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVBoolType (MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 1844 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::BuildMI(), createTypeVReg(), CurMF, llvm::SPIRVIRMapping::findMI(), llvm::IntegerType::get(), llvm::MachineIRBuilder::getDL(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineIRBuilder::getInsertPt(), llvm::MachineIRBuilder::getMBB(), I, MI, and TII.
getOrCreateSPIRVBoolType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVBoolType (MachineIRBuilder & MIRBuilder, bool EmitIR)
Definition at line 1836 of file SPIRVGlobalRegistry.cpp.
References llvm::IntegerType::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), and getOrCreateSPIRVType().
Referenced by llvm::buildBoolRegister(), llvm::generateGroupInst(), and llvm::genWorkgroupQuery().
getOrCreateSPIRVFloatType()
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVFloatType (unsigned BitWidth, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 1815 of file SPIRVGlobalRegistry.cpp.
References llvm::BitWidth, CurMF, llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getHalfTy(), getOrCreateSPIRVType(), I, llvm_unreachable, and TII.
Referenced by assignFloatTypeToVReg().
getOrCreateSPIRVIntegerType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 1803 of file SPIRVGlobalRegistry.cpp.
References llvm::BitWidth, CurMF, llvm::IntegerType::get(), getOrCreateSPIRVType(), I, and TII.
getOrCreateSPIRVIntegerType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType (unsigned BitWidth, MachineIRBuilder & MIRBuilder)
Definition at line 1762 of file SPIRVGlobalRegistry.cpp.
References llvm::BitWidth, llvm::IntegerType::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), and getOrCreateSPIRVType().
Referenced by assignIntTypeToVReg(), llvm::buildConstantIntReg32(), llvm::buildEnqueueKernel(), deduceIntTypeFromResult(), llvm::SPIRVTargetLowering::finalizeLowering(), llvm::generateImageSizeQueryInst(), llvm::genWorkgroupQuery(), getOrCreateOpTypeCoopMatr(), getOrCreatePaddingType(), propagateSPIRVType(), and registerSpirvTypeForNewInstructions().
getOrCreateSPIRVPointerType() [1/3]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVPointerType (const Type * BaseType, MachineInstr & I, SPIRV::StorageClass::StorageClass SC)
Definition at line 1891 of file SPIRVGlobalRegistry.cpp.
References getOrCreateSPIRVPointerType(), and I.
getOrCreateSPIRVPointerType() [2/3]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVPointerType (const Type * BaseType, MachineIRBuilder & MIRBuilder, SPIRV::StorageClass::StorageClass SC)
Definition at line 1898 of file SPIRVGlobalRegistry.cpp.
References assert(), getOrCreateSPIRVType(), and storageClassRequiresExplictLayout().
Referenced by llvm::buildEnqueueKernel(), createNewPtrType(), deducePointerTypeFromResultRegister(), generateAssignInstrs(), getArgSPIRVType(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVTypeByName(), insertBitcasts(), legalizeSpvExtractElt(), validateLifetimeStart(), and validatePtrUnwrapStructField().
getOrCreateSPIRVPointerType() [3/3]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVPointerType (SPIRVType * BaseType, MachineIRBuilder & MIRBuilder, SPIRV::StorageClass::StorageClass SC)
Definition at line 1921 of file SPIRVGlobalRegistry.cpp.
References assert(), getOrCreateSPIRVPointerType(), getPointeeType(), getTypeForSPIRVType(), and storageClassRequiresExplictLayout().
getOrCreateSPIRVType() [1/3]
SPIRVType * llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType (const Type * Type, MachineInstr & I, SPIRV::AccessQualifier::AccessQualifier AQ, bool EmitIR) inline
Definition at line 304 of file SPIRVGlobalRegistry.h.
References getOrCreateSPIRVType(), and I.
Referenced by addConstantsToTrack(), assignTypeToVReg(), buildConstantFP(), llvm::buildNDRange(), createNewPtrType(), llvm::createVirtualRegister(), getArgSPIRVType(), llvm::getCoopMatrType(), getImageType(), llvm::getInlineSpirvType(), getOrCreateSPIRVBoolType(), llvm::getOrCreateSPIRVDeviceEventPointer(), getOrCreateSPIRVFloatType(), getOrCreateSPIRVIntegerType(), getOrCreateSPIRVIntegerType(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVType(), getOrCreateSPIRVType(), getOrCreateSPIRVTypeByName(), getOrCreateSPIRVVectorType(), getOrCreateVulkanBufferType(), getOrCreateVulkanPushConstantType(), insertInlineAsmProcess(), legalizeSpvExtractElt(), propagateSPIRVType(), llvm::setRegClassType(), and llvm::updateRegType().
getOrCreateSPIRVType() [2/3]
SPIRVType * llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType (const Type * Type, MachineIRBuilder & MIRBuilder, SPIRV::AccessQualifier::AccessQualifier AQ, bool EmitIR) inline
Definition at line 311 of file SPIRVGlobalRegistry.h.
References getOrCreateSPIRVType().
getOrCreateSPIRVType() [3/3]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVType (unsigned BitWidth, MachineInstr & I, const SPIRVInstrInfo & TII, unsigned SPIRVOPcode, Type * LLVMTy)
Definition at line 1777 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::BitWidth, llvm::BuildMI(), createTypeVReg(), CurMF, llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getDL(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineIRBuilder::getInsertPt(), llvm::MachineIRBuilder::getMBB(), I, MI, and TII.
getOrCreateSPIRVTypeByName()
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVTypeByName (StringRef TypeStr, MachineIRBuilder & MIRBuilder, bool EmitIR, SPIRV::StorageClass::StorageClass SC = SPIRV::StorageClass::Function, SPIRV::AccessQualifier::AccessQualifier AQ = SPIRV::AccessQualifier::ReadWrite)
Definition at line 1716 of file SPIRVGlobalRegistry.cpp.
References llvm::StringRef::consume_back(), llvm::StringRef::consume_front(), llvm::StringRef::find(), llvm::StringRef::getAsInteger(), llvm::Function::getContext(), llvm::MachineIRBuilder::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVType(), getOrCreateSPIRVVectorType(), llvm::hasBuiltinTypePrefix(), llvm::parseBasicTypeName(), llvm::SPIRV::parseBuiltinTypeNameToTargetExtType(), llvm::StringRef::str(), and llvm::StringRef::substr().
Referenced by llvm::generateAsyncCopy(), and llvm::generateSampleImageInst().
getOrCreateSPIRVVectorType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVVectorType (SPIRVType * BaseType, unsigned NumElements, MachineInstr & I, const SPIRVInstrInfo & TII)
Definition at line 1870 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::BuildMI(), createTypeVReg(), CurMF, llvm::SPIRVIRMapping::findMI(), llvm::FixedVectorType::get(), llvm::MachineIRBuilder::getDL(), llvm::MachineIRBuilder::getInsertPt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineIRBuilder::getMBB(), llvm::MachineInstr::getParent(), getSPIRVTypeID(), getTypeForSPIRVType(), I, MI, and TII.
getOrCreateSPIRVVectorType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getOrCreateSPIRVVectorType (SPIRVType * BaseType, unsigned NumElements, MachineIRBuilder & MIRBuilder, bool EmitIR)
Definition at line 1861 of file SPIRVGlobalRegistry.cpp.
References llvm::FixedVectorType::get(), getOrCreateSPIRVType(), and getTypeForSPIRVType().
Referenced by assignVectTypeToVReg(), llvm::buildBoolRegister(), deduceAndAssignTypeForGUnmerge(), deduceTypeFromResultRegister(), deduceTypeFromSingleOperand(), llvm::SPIRVTargetLowering::finalizeLowering(), llvm::generateGroupInst(), llvm::generateImageSizeQueryInst(), llvm::generateReadImageInst(), llvm::genWorkgroupQuery(), getOrCreateSPIRVTypeByName(), propagateSPIRVType(), and registerSpirvTypeForNewInstructions().
getOrCreateUndef()
Register SPIRVGlobalRegistry::getOrCreateUndef (MachineInstr & I, SPIRVType * SpvType, const SPIRVInstrInfo & TII)
Definition at line 1955 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assignSPIRVTypeToVReg(), llvm::BuildMI(), llvm::constrainSelectedInstRegOperands(), CurMF, llvm::SPIRVIRMapping::find(), llvm::UndefValue::get(), llvm::MachineIRBuilder::getDL(), llvm::MachineIRBuilder::getInsertPt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineIRBuilder::getMBB(), llvm::MachineInstr::getParent(), getSPIRVTypeID(), getTypeForSPIRVType(), I, llvm::Register::isValid(), llvm::LLT::scalar(), and TII.
getOrCreateUnknownType()
SPIRVType * SPIRVGlobalRegistry::getOrCreateUnknownType (const Type * Ty, MachineIRBuilder & MIRBuilder, unsigned Opcode, const ArrayRef< MCOperand > Operands)
Definition at line 1691 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), createTypeVReg(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), and MI.
Referenced by llvm::getInlineSpirvType().
getOrCreateVulkanBufferType()
SPIRVType * SPIRVGlobalRegistry::getOrCreateVulkanBufferType (MachineIRBuilder & MIRBuilder, Type * ElemType, SPIRV::StorageClass::StorageClass SC, bool IsWritable, bool EmitIr = false)
Definition at line 1435 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::buildOpDecorate(), llvm::buildOpMemberDecorate(), llvm::StructType::create(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), getOrCreateSPIRVType(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::SPIRV::irhandle_vkbuffer(), MI, storageClassRequiresExplictLayout(), and T.
Referenced by llvm::getVulkanBufferType().
getOrCreateVulkanPushConstantType()
SPIRVType * SPIRVGlobalRegistry::getOrCreateVulkanPushConstantType (MachineIRBuilder & MIRBuilder, Type * ElemType)
Definition at line 1475 of file SPIRVGlobalRegistry.cpp.
References llvm::SPIRVIRMapping::add(), llvm::buildOpDecorate(), llvm::SPIRVIRMapping::findMI(), llvm::MachineIRBuilder::getMF(), getOrCreateSPIRVType(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::SPIRV::irhandle_vkbuffer(), MI, and T.
Referenced by llvm::getVulkanPushConstantType().
getPointeeType()
SPIRVType * SPIRVGlobalRegistry::getPointeeType (SPIRVType * PtrType)
Definition at line 1391 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and getSPIRVTypeForVReg().
Referenced by llvm::buildAPFixedPointInst(), changePointerStorageClass(), deduceTypeFromPointerOperand(), llvm::SPIRVTargetLowering::enforcePtrTypeCompatibility(), llvm::generateICarryBorrowInst(), getOrCreateConstNullPtr(), getOrCreateSPIRVPointerType(), getPointeeTypeOp(), and validateLifetimeStart().
getPointeeTypeOp()
unsigned SPIRVGlobalRegistry::getPointeeTypeOp (Register PtrReg)
Definition at line 1397 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstr::getOpcode(), getPointeeType(), and getSPIRVTypeForVReg().
getPointerSize()
unsigned llvm::SPIRVGlobalRegistry::getPointerSize () const inline
Definition at line 416 of file SPIRVGlobalRegistry.h.
Referenced by llvm::buildEnqueueKernel(), buildGlobalVariable(), llvm::buildNDRange(), llvm::genWorkgroupQuery(), and getRegType().
getPointerStorageClass() [1/2]
SPIRV::StorageClass::StorageClass SPIRVGlobalRegistry::getPointerStorageClass (const SPIRVType * Type) const
Definition at line 1430 of file SPIRVGlobalRegistry.cpp.
References llvm::getImm().
getPointerStorageClass() [2/2]
SPIRV::StorageClass::StorageClass SPIRVGlobalRegistry::getPointerStorageClass (Register VReg) const
Definition at line 1422 of file SPIRVGlobalRegistry.cpp.
References assert(), getPointerStorageClass(), and getSPIRVTypeForVReg().
Referenced by llvm::buildAtomicLoadInst(), llvm::buildAtomicStoreInst(), llvm::buildMemSemanticsReg(), changePointerStorageClass(), llvm::generateCastToPtrInst(), getOrCreateGlobalVariableWithBinding(), getPointerStorageClass(), and propagateSPIRVType().
getRegClass()
const TargetRegisterClass * SPIRVGlobalRegistry::getRegClass (SPIRVType * SpvType) const
Definition at line 1988 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and getSPIRVTypeForVReg().
Referenced by llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicRMWInst(), llvm::buildBoolRegister(), buildOpBitcast(), convertPtrToInt(), llvm::createVirtualRegister(), generateAssignType(), llvm::generateReadImageInst(), legalizeSpvExtractElt(), legalizeSpvInsertElt(), llvm::processInstr(), propagateSPIRVType(), llvm::setRegClassIfNull(), llvm::setRegClassType(), and llvm::updateRegType().
getRegType()
LLT SPIRVGlobalRegistry::getRegType (SPIRVType * SpvType) const
Definition at line 2014 of file SPIRVGlobalRegistry.cpp.
References llvm::LLT::fixed_vector(), getAS(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getPointerSize(), llvm::MachineOperand::getReg(), getScalarOrVectorBitWidth(), getSPIRVTypeForVReg(), llvm::LLT::pointer(), and llvm::LLT::scalar().
Referenced by llvm::createVirtualRegister(), llvm::generateReadImageInst(), legalizeSpvInsertElt(), llvm::processInstr(), llvm::setRegClassType(), and llvm::updateRegType().
getResultType()
SPIRVType * SPIRVGlobalRegistry::getResultType (Register VReg, MachineFunction * MF = nullptr)
Definition at line 1234 of file SPIRVGlobalRegistry.cpp.
References CurMF, llvm::MachineFunction::getRegInfo(), getSPIRVTypeForVReg(), and llvm::getVRegDef().
Referenced by llvm::SPIRVTargetLowering::enforcePtrTypeCompatibility().
getScalarOrVectorBitWidth()
unsigned SPIRVGlobalRegistry::getScalarOrVectorBitWidth (const SPIRVType * Type) const
Definition at line 1351 of file SPIRVGlobalRegistry.cpp.
References assert(), getSPIRVTypeForVReg(), and llvm_unreachable.
Referenced by buildConstantFP(), buildConstantInt(), llvm::buildSelectInst(), createConstFP(), createConstInt(), llvm::generateBuiltinVar(), llvm::generateWaveInst(), getOrCreateConsIntVector(), getOrCreateConstIntArray(), getOrCreateConstVector(), getOrCreateConstVector(), getRegType(), and propagateSPIRVType().
getScalarOrVectorComponentCount() [1/2]
unsigned SPIRVGlobalRegistry::getScalarOrVectorComponentCount (Register VReg) const
Definition at line 1319 of file SPIRVGlobalRegistry.cpp.
References getScalarOrVectorComponentCount(), and getSPIRVTypeForVReg().
Referenced by llvm::generateConvertInst(), llvm::getBuiltinCallArguments(), getScalarOrVectorComponentCount(), and propagateSPIRVType().
getScalarOrVectorComponentCount() [2/2]
unsigned SPIRVGlobalRegistry::getScalarOrVectorComponentCount (SPIRVType * Type) const
Definition at line 1324 of file SPIRVGlobalRegistry.cpp.
References llvm::getImm().
getScalarOrVectorComponentType() [1/2]
SPIRVType * SPIRVGlobalRegistry::getScalarOrVectorComponentType (Register VReg) const
Definition at line 1333 of file SPIRVGlobalRegistry.cpp.
References getScalarOrVectorComponentType(), and getSPIRVTypeForVReg().
Referenced by deduceAndAssignTypeForGUnmerge(), deduceTypeFromResultRegister(), deduceTypeFromSingleOperand(), getScalarOrVectorComponentType(), legalizeSpvExtractElt(), and legalizeSpvInsertElt().
getScalarOrVectorComponentType() [2/2]
SPIRVType * SPIRVGlobalRegistry::getScalarOrVectorComponentType (SPIRVType * Type) const
Definition at line 1338 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::MachineInstr::getOpcode(), getSPIRVTypeForVReg(), and isScalarOrVectorOfType().
getSPIRVTypeForVReg()
SPIRVType * SPIRVGlobalRegistry::getSPIRVTypeForVReg (Register VReg, const MachineFunction * MF = nullptr) const
Definition at line 1223 of file SPIRVGlobalRegistry.cpp.
References CurMF.
Referenced by llvm::buildAPFixedPointInst(), llvm::buildAtomicCompareExchangeInst(), buildGlobalVariable(), llvm::buildNDRange(), buildOpBitcast(), deduceAndAssignTypeForGUnmerge(), deducePointerTypeFromResultRegister(), deduceTypeFromPointerOperand(), deduceTypeFromResultRegister(), deduceTypeFromSingleOperand(), ensureAssignTypeForTypeFolding(), llvm::SPIRVTargetLowering::finalizeLowering(), generateAssignInstrs(), llvm::generateCoopMatrInst(), llvm::generateDotOrFMulInst(), llvm::generateGroupInst(), llvm::generateICarryBorrowInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::generateIntelSubgroupsInst(), llvm::generateReadImageInst(), llvm::generateSampleImageInst(), llvm::genWorkgroupQuery(), llvm::getBuiltinCallArguments(), getNumScalarOrVectorTotalBitWidth(), getOrCreateConstIntArray(), getPointeeType(), getPointeeTypeOp(), getPointerStorageClass(), getRegClass(), getRegType(), getResultType(), getScalarOrVectorBitWidth(), getScalarOrVectorComponentCount(), getScalarOrVectorComponentType(), getScalarOrVectorComponentType(), hasSPIRVTypeForVReg(), insertBitcasts(), isScalarOfType(), isScalarOrVectorOfType(), legalizeSpvExtractElt(), legalizeSpvInsertElt(), lowerBitcasts(), llvm::SPIRV::lowerBuiltin(), llvm::processInstr(), propagateSPIRVType(), registerSpirvTypeForNewInstructions(), requiresSpirvType(), retrieveScalarOrVectorIntType(), llvm::setRegClassIfNull(), typesLogicallyMatch(), validateAccessChain(), validateFunCallMachineDef(), validateGroupWaitEventsPtr(), validateLifetimeStart(), validatePtrTypes(), and validatePtrUnwrapStructField().
getSPIRVTypeID()
Register SPIRVGlobalRegistry::getSPIRVTypeID (const SPIRVType * SpirvType) const
Definition at line 1066 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::iterator_range< IteratorT >::begin(), llvm::MachineInstr::defs(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::uses().
Referenced by addConstantsToTrack(), llvm::build2DBlockIOINTELInst(), llvm::buildAPFixedPointInst(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicFlagInst(), llvm::buildAtomicFloatingRMWInst(), llvm::buildAtomicLoadInst(), llvm::buildAtomicRMWInst(), llvm::buildBindlessImageINTELInst(), buildConstantFP(), buildConstantInt(), buildConstantSampler(), llvm::buildEnqueueKernel(), llvm::buildExtendedBitOpsInst(), buildGlobalVariable(), llvm::buildImageChannelDataTypeInst(), llvm::buildNDRange(), buildOpBitcast(), llvm::buildPipeInst(), llvm::buildTernaryBitwiseFunctionINTELInst(), createConstFP(), createConstInt(), doInsertBitcast(), generateAssignType(), llvm::generateAsyncCopy(), llvm::generateAtomicInst(), llvm::generateCastToPtrInst(), llvm::generateConstructInst(), llvm::generateConvertInst(), llvm::generateCoopMatrInst(), llvm::generateDotOrFMulInst(), llvm::generateEnqueueInst(), llvm::generateExtInst(), llvm::generateGroupInst(), llvm::generateGroupUniformInst(), llvm::generateICarryBorrowInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::generateIntelSubgroupsInst(), llvm::generateKernelClockInst(), llvm::generateLoadStoreInst(), llvm::generatePredicatedLoadStoreInst(), llvm::generateReadImageInst(), llvm::generateRelationalInst(), llvm::generateSampleImageInst(), llvm::generateSpecConstantInst(), llvm::generateVectorLoadStoreInst(), llvm::getBuiltinCallArguments(), llvm::getInlineSpirvType(), getOrCreateConstNullPtr(), getOrCreateOpTypeCoopMatr(), getOrCreateOpTypeSampledImage(), getOrCreateSPIRVVectorType(), getOrCreateUndef(), insertInlineAsmProcess(), llvm::SPIRVTargetLowering::insertLogicalCopyOnResult(), and llvm::SPIRV::lowerBuiltinType().
getTypeForSPIRVType()
const Type * llvm::SPIRVGlobalRegistry::getTypeForSPIRVType (const SPIRVType * Ty) const inline
Definition at line 318 of file SPIRVGlobalRegistry.h.
References assert().
Referenced by llvm::buildAPFixedPointInst(), llvm::buildBoolRegister(), buildConstantInt(), buildGlobalVariable(), fixFunctionTypeIfPtrArgs(), generateAssignInstrs(), getOrCreateConsIntVector(), getOrCreateConstInt(), getOrCreateConstIntArray(), getOrCreateConstNullPtr(), getOrCreateConstVector(), getOrCreateConstVector(), getOrCreateOpTypeCoopMatr(), getOrCreateSPIRVPointerType(), getOrCreateSPIRVVectorType(), getOrCreateSPIRVVectorType(), getOrCreateUndef(), legalizeSpvExtractElt(), validateFunCallMachineDef(), and validatePtrTypes().
hasConstFunPtr()
bool llvm::SPIRVGlobalRegistry::hasConstFunPtr () inline
Definition at line 266 of file SPIRVGlobalRegistry.h.
hasSPIRVTypeForVReg()
bool llvm::SPIRVGlobalRegistry::hasSPIRVTypeForVReg (Register VReg) const inline
Definition at line 350 of file SPIRVGlobalRegistry.h.
References getSPIRVTypeForVReg().
invalidateMachineInstr()
void SPIRVGlobalRegistry::invalidateMachineInstr (MachineInstr * MI)
Definition at line 227 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::dyn_cast(), llvm::SPIRVIRMapping::erase(), F, MI, and TII.
Referenced by addConstantsToTrack(), llvm::SPIRVCombinerHelper::applySPIRVFaceForward(), cleanupHelperInstructions(), foldConstantsIntoIntrinsics(), generateAssignInstrs(), insertBitcasts(), insertInlineAsmProcess(), insertSpirvDecorations(), lowerBitcasts(), and processBlockAddr().
isAggregateType()
bool llvm::SPIRVGlobalRegistry::isAggregateType (SPIRVType * Type) const inline
Definition at line 365 of file SPIRVGlobalRegistry.h.
isBitcastCompatible()
bool SPIRVGlobalRegistry::isBitcastCompatible (const SPIRVType * Type1, const SPIRVType * Type2) const
Definition at line 1402 of file SPIRVGlobalRegistry.cpp.
References getNumScalarOrVectorTotalBitWidth(), llvm::MachineInstr::getOpcode(), and retrieveScalarOrVectorIntType().
Referenced by buildOpBitcast(), and validatePtrTypes().
isResourceType()
bool SPIRVGlobalRegistry::isResourceType (SPIRVType * Type) const
Definition at line 1305 of file SPIRVGlobalRegistry.cpp.
isScalarOfType()
bool SPIRVGlobalRegistry::isScalarOfType (Register VReg, unsigned TypeOpcode) const
Definition at line 1284 of file SPIRVGlobalRegistry.cpp.
References assert(), and getSPIRVTypeForVReg().
Referenced by llvm::buildAtomicCompareExchangeInst(), and llvm::generateReadImageInst().
isScalarOrVectorOfType()
bool SPIRVGlobalRegistry::isScalarOrVectorOfType (Register VReg, unsigned TypeOpcode) const
Definition at line 1291 of file SPIRVGlobalRegistry.cpp.
References assert(), llvm::MachineInstr::getOpcode(), and getSPIRVTypeForVReg().
Referenced by llvm::SPIRVTargetLowering::finalizeLowering(), llvm::generateConvertInst(), llvm::generateDotOrFMulInst(), and getScalarOrVectorComponentType().
isScalarOrVectorSigned()
bool SPIRVGlobalRegistry::isScalarOrVectorSigned (const SPIRVType * Type) const
Definition at line 1386 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), and retrieveScalarOrVectorIntType().
recordFunctionDefinition()
void llvm::SPIRVGlobalRegistry::recordFunctionDefinition (const Function * F, const MachineOperand * MO) inline
Definition at line 260 of file SPIRVGlobalRegistry.h.
References F, and llvm::MachineOperand::getParent().
recordFunctionPointer()
void llvm::SPIRVGlobalRegistry::recordFunctionPointer (const MachineOperand * MO, const Function * F) inline
Definition at line 255 of file SPIRVGlobalRegistry.h.
References F.
replaceAllUsesWith()
void SPIRVGlobalRegistry::replaceAllUsesWith (Value * Old, Value * New, bool DeleteOld = true)
Definition at line 2114 of file SPIRVGlobalRegistry.cpp.
References llvm::Value::replaceAllUsesWith(), updateIfExistAssignPtrTypeInstr(), and updateIfExistDeducedElementType().
retrieveScalarOrVectorIntType()
const SPIRVType * SPIRVGlobalRegistry::retrieveScalarOrVectorIntType (const SPIRVType * Type) const
Definition at line 1379 of file SPIRVGlobalRegistry.cpp.
References getSPIRVTypeForVReg().
Referenced by isBitcastCompatible(), and isScalarOrVectorSigned().
setBound()
void llvm::SPIRVGlobalRegistry::setBound (unsigned V) inline
Definition at line 115 of file SPIRVGlobalRegistry.h.
setCurrentFunc()
MachineFunction * llvm::SPIRVGlobalRegistry::setCurrentFunc (MachineFunction & MF) inline
Definition at line 358 of file SPIRVGlobalRegistry.h.
References CurMF.
Referenced by llvm::SPIRVTargetLowering::finalizeLowering(), and validateFunCallMachineDef().
updateAssignType()
void SPIRVGlobalRegistry::updateAssignType (CallInst * AssignCI, Value * Arg, Value * OfType)
Definition at line 2160 of file SPIRVGlobalRegistry.cpp.
References addDeducedElementType(), llvm::buildMD(), llvm::cast(), getIntrinsicID(), llvm::Value::getType(), and llvm::CallBase::setArgOperand().
Referenced by buildAssignPtr().
updateIfExistAssignPtrTypeInstr()
void llvm::SPIRVGlobalRegistry::updateIfExistAssignPtrTypeInstr (Value * OldVal, Value * NewVal, bool DeleteOld) inline
Definition at line 147 of file SPIRVGlobalRegistry.h.
References findAssignPtrTypeInstr().
Referenced by replaceAllUsesWith().
updateIfExistDeducedElementType()
void llvm::SPIRVGlobalRegistry::updateIfExistDeducedElementType (Value * OldVal, Value * NewVal, bool DeleteOld) inline
Definition at line 190 of file SPIRVGlobalRegistry.h.
References findDeducedElementType().
Referenced by replaceAllUsesWith().
Member Data Documentation
CurMF
MachineFunction* llvm::SPIRVGlobalRegistry::CurMF
Definition at line 113 of file SPIRVGlobalRegistry.h.
Referenced by assignFloatTypeToVReg(), assignIntTypeToVReg(), assignVectTypeToVReg(), buildConstantInt(), buildGlobalVariable(), createConstFP(), createConstInt(), deduceAndAssignSpirvType(), getOrCreateConstFP(), getOrCreateConstInt(), getOrCreateConstNullPtr(), getOrCreateSPIRVBoolType(), getOrCreateSPIRVFloatType(), getOrCreateSPIRVIntegerType(), getOrCreateSPIRVType(), getOrCreateSPIRVVectorType(), getOrCreateUndef(), getResultType(), getSPIRVTypeForVReg(), requiresSpirvType(), setCurrentFunc(), and SPIRVGlobalRegistry().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVGlobalRegistry.h
lib/Target/SPIRV/SPIRVGlobalRegistry.cpp