LLVM: llvm::orc::BloomFilter Class Reference
llvm::orc::BloomFilter Class Reference
#include "llvm/ExecutionEngine/Orc/Shared/SymbolFilter.h"
Public Types
using HashFunc = std::function<uint32_t(StringRef)>
Public Member Functions
BloomFilter ()=default
BloomFilter (BloomFilter &&) noexcept=default
BloomFilter & operator= (BloomFilter &&) noexcept=default
BloomFilter (const BloomFilter &)=delete
BloomFilter & operator= (const BloomFilter &)=delete
BloomFilter (uint32_t SymbolCount, float FalsePositiveRate, HashFunc hashFn)
bool isInitialized () const
void add (StringRef Sym)
bool mayContain (StringRef Sym) const
bool isEmpty () const
Friends
class shared::SPSSerializationTraits< shared::SPSBloomFilter, BloomFilter >
Detailed Description
Definition at line 25 of file SymbolFilter.h.
Member Typedef Documentation
HashFunc
using llvm::orc::BloomFilter::HashFunc = std::function<uint32_t(StringRef)>
Definition at line 27 of file SymbolFilter.h.
Constructor & Destructor Documentation
BloomFilter() [1/4]
llvm::orc::BloomFilter::BloomFilter () default
Referenced by BloomFilter(), BloomFilter(), BloomFilter(), operator=(), and operator=().
BloomFilter() [2/4]
llvm::orc::BloomFilter::BloomFilter (BloomFilter &&) default noexcept
References BloomFilter().
BloomFilter() [3/4]
llvm::orc::BloomFilter::BloomFilter (const BloomFilter &) delete
References BloomFilter(), and const.
BloomFilter() [4/4]
llvm::orc::BloomFilter::BloomFilter (uint32_t SymbolCount, float FalsePositiveRate, HashFunc hashFn) inline
Definition at line 35 of file SymbolFilter.h.
References BloomFilter(), and llvm::move().
Member Function Documentation
add()
void llvm::orc::BloomFilter::add (StringRef Sym) inline
Definition at line 41 of file SymbolFilter.h.
References assert().
isEmpty()
bool llvm::orc::BloomFilter::isEmpty () const inline
Definition at line 50 of file SymbolFilter.h.
Referenced by mayContain().
isInitialized()
bool llvm::orc::BloomFilter::isInitialized () const inline
Definition at line 39 of file SymbolFilter.h.
mayContain()
bool llvm::orc::BloomFilter::mayContain (StringRef Sym) const inline
Definition at line 46 of file SymbolFilter.h.
References isEmpty().
operator=() [1/2]
BloomFilter & llvm::orc::BloomFilter::operator= (BloomFilter &&) default noexcept
References BloomFilter().
operator=() [2/2]
BloomFilter & llvm::orc::BloomFilter::operator= (const BloomFilter &) delete
References BloomFilter(), and const.
Friends And Related Symbol Documentation
shared::SPSSerializationTraits< shared::SPSBloomFilter, BloomFilter >
friend class shared::SPSSerializationTraits< shared::SPSBloomFilter, BloomFilter > friend
Definition at line 50 of file SymbolFilter.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/SymbolFilter.h