LLVM: llvm::SPIRV::ConvergenceRegionInfo Class Reference
llvm::SPIRV::ConvergenceRegionInfo Class Reference
#include "Target/SPIRV/Analysis/SPIRVConvergenceRegionAnalysis.h"
Public Member Functions
ConvergenceRegionInfo ()
ConvergenceRegionInfo (ConvergenceRegion *TopLevelRegion)
~ConvergenceRegionInfo ()
ConvergenceRegionInfo (const ConvergenceRegionInfo &LHS)=delete
ConvergenceRegionInfo & operator= (const ConvergenceRegionInfo &LHS)=delete
ConvergenceRegionInfo (ConvergenceRegionInfo &&LHS)
ConvergenceRegionInfo & operator= (ConvergenceRegionInfo &&LHS)
void releaseMemory ()
const ConvergenceRegion * getTopLevelRegion () const
ConvergenceRegion * getWritableTopLevelRegion () const
Detailed Description
Definition at line 93 of file SPIRVConvergenceRegionAnalysis.h.
Constructor & Destructor Documentation
ConvergenceRegionInfo() [1/4]
llvm::SPIRV::ConvergenceRegionInfo::ConvergenceRegionInfo () inline
Definition at line 98 of file SPIRVConvergenceRegionAnalysis.h.
References nullptr.
Referenced by ConvergenceRegionInfo(), ConvergenceRegionInfo(), operator=(), and operator=().
ConvergenceRegionInfo() [2/4]
llvm::SPIRV::ConvergenceRegionInfo::ConvergenceRegionInfo (ConvergenceRegion * TopLevelRegion) inline
Definition at line 102 of file SPIRVConvergenceRegionAnalysis.h.
~ConvergenceRegionInfo()
llvm::SPIRV::ConvergenceRegionInfo::~ConvergenceRegionInfo () inline
Definition at line 105 of file SPIRVConvergenceRegionAnalysis.h.
References releaseMemory().
ConvergenceRegionInfo() [3/4]
llvm::SPIRV::ConvergenceRegionInfo::ConvergenceRegionInfo (const ConvergenceRegionInfo & LHS) delete
References ConvergenceRegionInfo(), and LHS.
ConvergenceRegionInfo() [4/4]
llvm::SPIRV::ConvergenceRegionInfo::ConvergenceRegionInfo (ConvergenceRegionInfo && LHS) inline
Definition at line 110 of file SPIRVConvergenceRegionAnalysis.h.
References ConvergenceRegionInfo(), and LHS.
Member Function Documentation
getTopLevelRegion()
const ConvergenceRegion * llvm::SPIRV::ConvergenceRegionInfo::getTopLevelRegion () const inline
Definition at line 137 of file SPIRVConvergenceRegionAnalysis.h.
getWritableTopLevelRegion()
ConvergenceRegion * llvm::SPIRV::ConvergenceRegionInfo::getWritableTopLevelRegion () const inline
Definition at line 138 of file SPIRVConvergenceRegionAnalysis.h.
operator=() [1/2]
ConvergenceRegionInfo & llvm::SPIRV::ConvergenceRegionInfo::operator= (const ConvergenceRegionInfo & LHS) delete
References ConvergenceRegionInfo(), and LHS.
operator=() [2/2]
ConvergenceRegionInfo & llvm::SPIRV::ConvergenceRegionInfo::operator= (ConvergenceRegionInfo && LHS) inline
Definition at line 119 of file SPIRVConvergenceRegionAnalysis.h.
References ConvergenceRegionInfo(), LHS, and releaseMemory().
releaseMemory()
void llvm::SPIRV::ConvergenceRegionInfo::releaseMemory () inline
Definition at line 128 of file SPIRVConvergenceRegionAnalysis.h.
Referenced by operator=(), and ~ConvergenceRegionInfo().
The documentation for this class was generated from the following file:
lib/Target/SPIRV/Analysis/SPIRVConvergenceRegionAnalysis.h