LLVM: llvm::cas::ondisk::ObjectHandle Class Reference
llvm::cas::ondisk::ObjectHandle Class Reference
Handle for a loaded node object.
#include "llvm/CAS/OnDiskGraphDB.h"
Public Member Functions
ObjectHandle (uint64_t Opaque)
uint64_t getOpaqueData () const
Static Public Member Functions
static ObjectHandle fromFileOffset (FileOffset Offset)
static ObjectHandle fromMemory (uintptr_t Ptr)
Friends
bool operator== (const ObjectHandle &LHS, const ObjectHandle &RHS)
bool operator!= (const ObjectHandle &LHS, const ObjectHandle &RHS)
Detailed Description
Handle for a loaded node object.
Definition at line 199 of file OnDiskGraphDB.h.
Constructor & Destructor Documentation
ObjectHandle()
llvm::cas::ondisk::ObjectHandle::ObjectHandle (uint64_t Opaque) inline explicit
Definition at line 201 of file OnDiskGraphDB.h.
Referenced by fromFileOffset(), fromMemory(), operator!=, and operator==.
Member Function Documentation
fromFileOffset()
ObjectHandle ObjectHandle::fromFileOffset (FileOffset Offset) static
Definition at line 456 of file OnDiskGraphDB.cpp.
References assert(), ObjectHandle(), and llvm::Offset.
Referenced by llvm::cas::ondisk::OnDiskGraphDB::load().
fromMemory()
ObjectHandle ObjectHandle::fromMemory (uintptr_t Ptr) static
Definition at line 462 of file OnDiskGraphDB.cpp.
References assert(), and ObjectHandle().
Referenced by llvm::cas::ondisk::OnDiskGraphDB::load().
getOpaqueData()
uint64_t llvm::cas::ondisk::ObjectHandle::getOpaqueData () const inline
Definition at line 202 of file OnDiskGraphDB.h.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const ObjectHandle & LHS, const ObjectHandle & RHS) friend
Definition at line 210 of file OnDiskGraphDB.h.
References LHS, ObjectHandle(), and RHS.
operator==
bool operator== (const ObjectHandle & LHS, const ObjectHandle & RHS) friend
Definition at line 207 of file OnDiskGraphDB.h.
References LHS, ObjectHandle(), and RHS.
The documentation for this class was generated from the following files:
include/llvm/CAS/OnDiskGraphDB.h
lib/CAS/OnDiskGraphDB.cpp