LLVM: llvm::unique_function< R(P...) const > Class Template Reference
llvm::unique_function< R(P...) const > Class Template Reference
#include "llvm/ADT/FunctionExtras.h"
Public Member Functions
unique_function ()=default
unique_function (std::nullptr_t)
unique_function (unique_function &&)=default
unique_function (const unique_function &)=delete
unique_function & operator= (unique_function &&)=default
unique_function & operator= (const unique_function &)=delete
template<typename CallableT>
unique_function (CallableT Callable, detail::EnableUnlessSameType< CallableT, unique_function > *=nullptr, detail::EnableIfCallable< const CallableT, R, P... > *=nullptr)
R operator() (P... Params) const
Public Member Functions inherited from llvm::detail::UniqueFunctionBase< R, P... >
operator bool () const
Additional Inherited Members
Protected Types inherited from llvm::detail::UniqueFunctionBase< R, P... >
using AdjustedParamT
using CallPtrT
using MovePtrT
using DestroyPtrT
using CallbackPointerUnionT
Protected Member Functions inherited from llvm::detail::UniqueFunctionBase< R, P... >
bool isInlineStorage () const
bool isTrivialCallback () const
CallPtrT getTrivialCallback () const
NonTrivialCallbacks * getNonTrivialCallbacks () const
CallPtrT getCallPtr () const
void * getCalleePtr () const
void * getInlineStorage () const
void * getOutOfLineStorage () const
size_t getOutOfLineStorageSize () const
size_t getOutOfLineStorageAlignment () const
void setOutOfLineStorage (void *Ptr, size_t Size, size_t Alignment)
UniqueFunctionBase (CallableT Callable, CalledAs< CalledAsT >)
~UniqueFunctionBase ()
UniqueFunctionBase (UniqueFunctionBase &&RHS) noexcept
UniqueFunctionBase & operator= (UniqueFunctionBase &&RHS) noexcept
UniqueFunctionBase ()=default
Static Protected Member Functions inherited from llvm::detail::UniqueFunctionBase< R, P... >
static R CallImpl (void *CallableAddr, AdjustedParamT< ParamTs >... Params)
static void MoveImpl (void *LHSCallableAddr, void *RHSCallableAddr) noexcept
static void DestroyImpl (void *CallableAddr) noexcept
Protected Attributes inherited from llvm::detail::UniqueFunctionBase< R, P... >
union llvm::detail::UniqueFunctionBase::StorageUnionT StorageUnion
PointerIntPair< CallbackPointerUnionT, 1, bool > CallbackAndInlineFlag
Static Protected Attributes inherited from llvm::detail::UniqueFunctionBase< R, P... >
static constexpr size_t InlineStorageSize
static constexpr size_t InlineStorageAlign
Detailed Description
template<typename R, typename... P>
class llvm::unique_function< R(P...) const >
Definition at line 369 of file FunctionExtras.h.
Constructor & Destructor Documentation
unique_function() [1/5]
template<typename R, typename... P> llvm::unique_function< R(P...) const >::unique_function () default
Referenced by operator=(), operator=(), unique_function(), and unique_function().
unique_function() [2/5]
template<typename R, typename... P> llvm::unique_function< R(P...) const >::unique_function (std::nullptr_t) inline
Definition at line 375 of file FunctionExtras.h.
unique_function() [3/5]
template<typename R, typename... P> llvm::unique_function< R(P...) const >::unique_function (unique_function< R(P...) const > &&) default
References unique_function().
unique_function() [4/5]
template<typename R, typename... P> llvm::unique_function< R(P...) const >::unique_function (const unique_function< R(P...) const > &) delete
References unique_function().
unique_function() [5/5]
template<typename R, typename... P> template<typename CallableT> llvm::unique_function< R(P...) const >::unique_function (CallableT Callable, detail::EnableUnlessSameType< CallableT, unique_function< R(P...) const > > * = nullptr, detail::EnableIfCallable< const CallableT, R, P... > * = nullptr) inline
Definition at line 382 of file FunctionExtras.h.
References const.
Member Function Documentation
operator()()
template<typename R, typename... P> R llvm::unique_function< R(P...) const >::operator() (P... Params) const inline
Definition at line 389 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< R, P... >::getCalleePtr(), llvm::detail::UniqueFunctionBase< R, P... >::getCallPtr(), and P.
operator=() [1/2]
template<typename R, typename... P> unique_function & llvm::unique_function< R(P...) const >::operator= (const unique_function< R(P...) const > &) delete
References unique_function().
operator=() [2/2]
template<typename R, typename... P> unique_function & llvm::unique_function< R(P...) const >::operator= (unique_function< R(P...) const > &&) default
References unique_function().
The documentation for this class was generated from the following file:
include/llvm/ADT/FunctionExtras.h