LLVM: llvm::cas::ondisk::InternalRefArrayRef Class Reference
llvm::cas::ondisk::InternalRefArrayRef Class Reference
Array of internal node references.
#include "llvm/CAS/OnDiskGraphDB.h"
Classes
class iterator
Public Member Functions
size_t size () const
bool empty () const
bool operator== (const InternalRefArrayRef &RHS) const
iterator begin () const
iterator end () const
InternalRef operator[] (ptrdiff_t N) const
Array accessor.
bool is4B () const
bool is8B () const
ArrayRef< uint8_t > getBuffer () const
InternalRefArrayRef (std::nullopt_t=std::nullopt)
InternalRefArrayRef (ArrayRef< InternalRef > Refs)
InternalRefArrayRef (ArrayRef< InternalRef4B > Refs)
Detailed Description
Array of internal node references.
Definition at line 72 of file OnDiskGraphDB.h.
Constructor & Destructor Documentation
InternalRefArrayRef() [1/3]
llvm::cas::ondisk::InternalRefArrayRef::InternalRefArrayRef (std::nullopt_t = std::nullopt) inline
Definition at line 158 of file OnDiskGraphDB.h.
References llvm::cas::ondisk::InternalRef::getFromRawData().
Referenced by operator==().
InternalRefArrayRef() [2/3]
llvm::cas::ondisk::InternalRefArrayRef::InternalRefArrayRef (ArrayRef< InternalRef > Refs) inline
Definition at line 165 of file OnDiskGraphDB.h.
References begin(), and size().
InternalRefArrayRef() [3/3]
llvm::cas::ondisk::InternalRefArrayRef::InternalRefArrayRef (ArrayRef< InternalRef4B > Refs) inline
Definition at line 168 of file OnDiskGraphDB.h.
References begin(), and size().
Member Function Documentation
begin()
iterator llvm::cas::ondisk::InternalRefArrayRef::begin () const inline
Definition at line 140 of file OnDiskGraphDB.h.
Referenced by end(), llvm::cas::ondisk::OnDiskGraphDB::getObjectRefs(), InternalRefArrayRef(), InternalRefArrayRef(), operator==(), and operator[]().
empty()
bool llvm::cas::ondisk::InternalRefArrayRef::empty () const inline
Definition at line 75 of file OnDiskGraphDB.h.
end()
iterator llvm::cas::ondisk::InternalRefArrayRef::end () const inline
Definition at line 141 of file OnDiskGraphDB.h.
References begin().
Referenced by llvm::cas::ondisk::OnDiskGraphDB::getObjectRefs(), and operator==().
getBuffer()
ArrayRef< uint8_t > llvm::cas::ondisk::InternalRefArrayRef::getBuffer () const inline
Definition at line 149 of file OnDiskGraphDB.h.
References llvm::ArrayRef(), B(), llvm::cast(), and is4B().
is4B()
bool llvm::cas::ondisk::InternalRefArrayRef::is4B () const inline
Definition at line 146 of file OnDiskGraphDB.h.
References llvm::isa().
Referenced by getBuffer().
is8B()
bool llvm::cas::ondisk::InternalRefArrayRef::is8B () const inline
Definition at line 147 of file OnDiskGraphDB.h.
References llvm::isa().
operator==()
bool llvm::cas::ondisk::InternalRefArrayRef::operator== (const InternalRefArrayRef & RHS) const inline
Definition at line 136 of file OnDiskGraphDB.h.
References begin(), end(), InternalRefArrayRef(), RHS, and size().
operator[]()
InternalRef llvm::cas::ondisk::InternalRefArrayRef::operator[] (ptrdiff_t N) const inline
Array accessor.
Definition at line 144 of file OnDiskGraphDB.h.
References begin(), and N.
size()
size_t llvm::cas::ondisk::InternalRefArrayRef::size () const inline
Definition at line 74 of file OnDiskGraphDB.h.
Referenced by InternalRefArrayRef(), InternalRefArrayRef(), and operator==().
The documentation for this class was generated from the following file:
include/llvm/CAS/OnDiskGraphDB.h