LLVM: llvm::DwarfCompileUnit Class Reference
llvm::DwarfCompileUnit Class Reference final
#include "CodeGen/AsmPrinter/DwarfCompileUnit.h"
Classes
struct GlobalExpr
A pair of GlobalVariable and DIExpression.
struct BaseTypeRef
Public Types
using InlinedEntity = DbgValueHistoryMap::InlinedEntity
Find abstract variable associated with Var.
Public Member Functions
DwarfCompileUnit (unsigned UID, const DICompileUnit *Node, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU, UnitKind Kind=UnitKind::Full)
bool hasRangeLists () const
DwarfCompileUnit * getSkeleton () const
bool includeMinimalInlineScopes () const
bool emitFuncLineTableOffsets () const
void initStmtList ()
void applyStmtList (DIE &D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
MCSymbol * getLineTableStartSym () const
Get line table start symbol for this unit.
DIE * getOrCreateGlobalVariableDIE (const DIGlobalVariable *GV, ArrayRef< GlobalExpr > GlobalExprs)
Get or create global variable DIE.
DIE * getOrCreateCommonBlock (const DICommonBlock *CB, ArrayRef< GlobalExpr > GlobalExprs)
void addLocationAttribute (DIE *ToDIE, const DIGlobalVariable *GV, ArrayRef< GlobalExpr > GlobalExprs)
void addLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
addLabelAddress - Add a dwarf label attribute data and value using either DW_FORM_addr or DW_FORM_GNU_addr_index.
void addLocalLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
addLocalLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr only.
DwarfCompileUnit & getCU () override
unsigned getOrCreateSourceID (const DIFile *File) override
Look up the source ID for the given file.
void addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
void attachLowHighPC (DIE &D, const MCSymbol *Begin, const MCSymbol *End)
DIE & updateSubprogramScopeDIE (const DISubprogram *SP, const Function &F, MCSymbol *LineTableSym)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc, DW_AT_high_pc and DW_AT_LLVM_stmt_sequence attributes.
void constructScopeDIE (LexicalScope *Scope, DIE &ParentScopeDIE)
void addScopeRangeList (DIE &ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
void attachRangesOrLowHighPC (DIE &D, SmallVector< RangeSpan, 2 > Ranges)
void attachRangesOrLowHighPC (DIE &D, const SmallVectorImpl< InsnRange > &Ranges)
DIE * constructInlinedScopeDIE (LexicalScope *Scope, DIE &ParentScopeDIE)
This scope represents an inlined body of a function.
DIE * constructLexicalScopeDIE (LexicalScope *Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
DIE * getLexicalBlockDIE (const DILexicalBlock *LB)
Get a DIE for the given DILexicalBlock.
DIE * constructVariableDIE (DbgVariable &DV, bool Abstract=false)
Construct a DIE for the given DbgVariable.
DIE * constructVariableDIE (DbgVariable &DV, const LexicalScope &Scope, DIE *&ObjectPointer)
Convenience overload which writes the DIE pointer into an out variable ObjectPointer in addition to returning it.
DIE * constructLabelDIE (DbgLabel &DL, const LexicalScope &Scope)
Construct a DIE for the given DbgLabel.
void createBaseTypeDIEs ()
DIE * getOrCreateContextDIE (const DIScope *Ty) override
Construct a DIE for a given scope.
DIE * getOrCreateSubprogramDIE (const DISubprogram *SP, const Function *F, bool Minimal=false) override
DIE & constructSubprogramScopeDIE (const DISubprogram *Sub, const Function &F, LexicalScope *Scope, MCSymbol *LineTableSym)
Construct a DIE for this subprogram scope.
DIE * createAndAddScopeChildren (LexicalScope *Scope, DIE &ScopeDIE)
DIE & getOrCreateAbstractSubprogramDIE (const DISubprogram *SP)
Create an abstract subprogram DIE, that should later be populated by constructAbstractSubprogramScopeDIE.
void constructAbstractSubprogramScopeDIE (LexicalScope *Scope)
bool useGNUAnalogForDwarf5Feature () const
Whether to use the GNU analog for a DWARF5 tag, attribute, or location atom.
dwarf::Tag getDwarf5OrGNUTag (dwarf::Tag Tag) const
This takes a DWARF 5 tag and returns it or a GNU analog.
dwarf::Attribute getDwarf5OrGNUAttr (dwarf::Attribute Attr) const
This takes a DWARF 5 attribute and returns it or a GNU analog.
dwarf::LocationAtom getDwarf5OrGNULocationAtom (dwarf::LocationAtom Loc) const
This takes a DWARF 5 location atom and either returns it or a GNU analog.
DIE & constructCallSiteEntryDIE (DIE &ScopeDIE, const DISubprogram *CalleeSP, const Function *CalleeF, bool IsTail, const MCSymbol *PCAddr, const MCSymbol *CallAddr, MachineLocation CallTarget, int64_t Offset, DIType *AllocSiteTy)
Construct a call site entry DIE describing a call within Scope to a callee described by CalleeSP and CalleeF.
void constructCallSiteParmEntryDIEs (DIE &CallSiteDIE, SmallVector< DbgCallSiteParam, 4 > &Params)
Construct call site parameter DIEs for the CallSiteDIE.
DIE * getOrCreateImportedEntityDIE (const DIImportedEntity *IE)
Get or create a DIE for an imported entity.
DIE * constructImportedEntityDIE (const DIImportedEntity *IE)
void finishSubprogramDefinition (const DISubprogram *SP)
void finishEntityDefinition (const DbgEntity *Entity)
void attachLexicalScopesAbstractOrigins ()
DbgEntity * getExistingAbstractEntity (const DINode *Node)
void createAbstractEntity (const DINode *Node, LexicalScope *Scope)
void setSkeleton (DwarfCompileUnit &Skel)
Set the skeleton unit associated with this unit.
unsigned getHeaderSize () const override
Compute the size of a header for this unit, not including the initial length field.
unsigned getLength ()
void emitHeader (bool UseOffsets) override
Emit the header for this unit, not including the initial length field.
void addAddrTableBase ()
Add the DW_AT_addr_base attribute to the unit DIE.
MCSymbol * getMacroLabelBegin () const
void addGlobalName (StringRef Name, const DIE &Die, const DIScope *Context) override
Add a new global name to the compile unit.
void addGlobalNameForTypeUnit (StringRef Name, const DIScope *Context)
Add a new global name present in a type unit to this compile unit.
void addGlobalTypeImpl (const DIType *Ty, const DIE &Die, const DIScope *Context) override
Add a new global type to the compile unit.
void addGlobalTypeUnitType (const DIType *Ty, const DIScope *Context)
Add a new global type present in a type unit to this compile unit.
const StringMap< const DIE * > & getGlobalNames () const
const StringMap< const DIE * > & getGlobalTypes () const
void addVariableAddress (const DbgVariable &DV, DIE &Die, MachineLocation Location)
Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
void addAddress (DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
Add an address attribute to a die based on the location provided.
void addMemoryLocation (DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location, int64_t Offset)
Add a memory location exprloc to DIE with attribute Attribute at Location + Offset.
void addComplexAddress (const DIExpression *DIExpr, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable (navigating the extra location information encoded in the type) based on the starting location.
void addLocationList (DIE &Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
void applyCommonDbgVariableAttributes (const DbgVariable &Var, DIE &VariableDie)
Add attributes to Var which reflect the common attributes of VariableDie, namely those which are not dependant on the active variant.
void addExpr (DIELoc &Die, dwarf::Form Form, const MCExpr *Expr)
Add a Dwarf expression attribute data and value.
void applySubprogramAttributesToDefinition (const DISubprogram *SP, DIE &SPDie)
void applyLabelAttributes (const DbgLabel &Label, DIE &LabelDie)
const SmallVectorImpl< RangeSpan > & getRanges () const
getRanges - Get the list of ranges for this unit.
SmallVector< RangeSpan, 2 > takeRanges ()
void setBaseAddress (const MCSymbol *Base)
const MCSymbol * getBaseAddress () const
uint64_t getDWOId () const
void setDWOId (uint64_t DwoId)
bool hasDwarfPubSections () const
void addBaseTypeRef (DIEValueList &Die, int64_t Idx)
MDNodeSetVector & getDeferredLocalDecls ()
Public Member Functions inherited from llvm::DwarfUnit
unsigned getUniqueID () const
Gets Unique ID for this unit.
AsmPrinter * getAsmPrinter () const
MCSymbol * getLabelBegin () const
Get the the symbol for start of the section for this unit.
MCSymbol * getEndLabel () const
llvm::dwarf::SourceLanguage getSourceLanguage () const
const DICompileUnit * getCUNode () const
DwarfDebug & getDwarfDebug () const
bool hasContent () const
Return true if this compile unit has something to write out.
std::string getParentContextString (const DIScope *Context) const
Get string containing language specific context for a global name.
void addGlobalType (const DIType *Ty, const DIE &Die, const DIScope *Context)
DIE * getDIE (const DINode *D) const
Returns the DIE map slot for the specified debug variable.
DIELoc * getDIELoc ()
Returns a fresh newly allocated DIELoc.
void insertDIE (const DINode *Desc, DIE *D)
Insert DIE into the map.
void insertDIE (DIE *D)
void addFlag (DIE &Die, dwarf::Attribute Attribute)
Add a flag that is true to the DIE.
void addUInt (DIEValueList &Die, dwarf::Attribute Attribute, std::optional< dwarf::Form > Form, uint64_t Integer)
Add an unsigned integer attribute data and value.
void addUInt (DIEValueList &Block, dwarf::Form Form, uint64_t Integer)
void addSInt (DIEValueList &Die, dwarf::Attribute Attribute, std::optional< dwarf::Form > Form, int64_t Integer)
Add an signed integer attribute data and value.
void addSInt (DIEValueList &Die, std::optional< dwarf::Form > Form, int64_t Integer)
void addInt (DIE &Die, dwarf::Attribute Attribute, const APInt &Integer, bool Unsigned)
Add an integer attribute data and value; value may be any width.
void addString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
void addLabel (DIEValueList &Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol *Label)
Add a Dwarf label attribute data and value.
void addLabel (DIELoc &Die, dwarf::Form Form, const MCSymbol *Label)
void addSectionOffset (DIE &Die, dwarf::Attribute Attribute, uint64_t Integer)
Add an offset into a section attribute data and value.
void addOpAddress (DIELoc &Die, const MCSymbol *Sym)
Add a dwarf op address data and value using the form given and an op of either DW_FORM_addr or DW_FORM_GNU_addr_index.
void addPoolOpAddress (DIEValueList &Die, const MCSymbol *Label)
void addLabelDelta (DIEValueList &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
Add a label delta attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIE &Entry)
Add a DIE attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIEEntry Entry)
Add a DIE attribute data and value.
void addDIETypeSignature (DIE &Die, uint64_t Signature)
Add a type's DW_AT_signature and set the declaration flag.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIELoc *Loc)
Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIEBlock *Block)
Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, dwarf::Form Form, DIEBlock *Block)
void addBlock (DIE &Die, dwarf::Attribute Attribute, const DIExpression *Expr)
Add an expression as block data.
void addSourceLine (DIE &Die, unsigned Line, unsigned Column, const DIFile *File)
Add location information to specified debug information entry.
void addSourceLine (DIE &Die, const DILocalVariable *V)
void addSourceLine (DIE &Die, const DIGlobalVariable *G)
void addSourceLine (DIE &Die, const DISubprogram *SP)
void addSourceLine (DIE &Die, const DILabel *L)
void addSourceLine (DIE &Die, const DIType *Ty)
void addSourceLine (DIE &Die, const DIObjCProperty *Ty)
void addConstantValue (DIE &Die, const ConstantInt *CI, const DIType *Ty)
Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const APInt &Val, const DIType *Ty)
void addConstantValue (DIE &Die, const APInt &Val, bool Unsigned)
void addConstantValue (DIE &Die, uint64_t Val, const DIType *Ty)
void addConstantValue (DIE &Die, bool Unsigned, uint64_t Val)
void addConstantFPValue (DIE &Die, const ConstantFP *CFP)
Add constant value entry in variable DIE.
void addLinkageName (DIE &Die, StringRef LinkageName)
Add a linkage name, if it isn't empty.
void addTemplateParams (DIE &Buffer, DINodeArray TParams)
Add template parameters in buffer.
void addThrownTypes (DIE &Die, DINodeArray ThrownTypes)
Add thrown types.
void addAccess (DIE &Die, DINode::DIFlags Flags)
Add the accessibility attribute.
void addType (DIE &Entity, const DIType *Ty, dwarf::Attribute Attribute=dwarf::DW_AT_type)
Add a new type attribute to the specified entity.
DIE * getOrCreateNameSpace (const DINamespace *NS)
DIE * getOrCreateModule (const DIModule *M)
void applySubprogramAttributes (const DISubprogram *SP, DIE &SPDie, bool SkipSPAttributes=false)
DIE * createTypeDIE (const DIScope *Context, DIE &ContextDIE, const DIType *Ty)
Creates type DIE with specific context.
virtual DIE * getOrCreateTypeDIE (const MDNode *TyNode)
Find existing DIE or create new DIE for the given type.
void constructContainingTypeDIEs ()
Construct DIEs for types that contain vtables.
std::optional< unsigned > constructSubprogramArguments (DIE &Buffer, DITypeRefArray Args)
Construct function argument DIEs.
DIE & createAndAddDIE (dwarf::Tag Tag, DIE &Parent, const DINode *N=nullptr)
Create a DIE with the given Tag, add the DIE to its parent, and call insertDIE if MD is not null.
bool useSegmentedStringOffsetsTable () const
void addStringOffsetsStart ()
Add the DW_AT_str_offsets_base attribute to the unit DIE.
void addRnglistsBase ()
Add the DW_AT_rnglists_base attribute to the unit DIE.
void constructTypeDIE (DIE &Buffer, const DICompositeType *CTy)
void addSectionDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addSectionDelta - Add a label delta attribute data and value.
void addSectionLabel (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label, const MCSymbol *Sec)
Add a Dwarf section label attribute data and value.
void addAnnotation (DIE &Buffer, DINodeArray Annotations)
Add DW_TAG_LLVM_annotation.
DIE * createTypeDIE (const DICompositeType *Ty)
Get context owner's DIE.
void updateAcceleratorTables (const DIScope *Context, const DIType *Ty, const DIE &TyDIE)
If this is a named finished type then include it in the list of types for the accelerator tables.
Public Member Functions inherited from llvm::DIEUnit
LLVM_ABI DIEUnit (dwarf::Tag UnitTag)
DIEUnit (const DIEUnit &RHS)=delete
DIEUnit (DIEUnit &&RHS)=delete
void operator= (const DIEUnit &RHS)=delete
void operator= (const DIEUnit &&RHS)=delete
void setSection (MCSection *Section)
Set the section that this DIEUnit will be emitted into.
MCSection * getSection () const
Return the section that this DIEUnit will be emitted into.
void setDebugSectionOffset (uint64_t O)
uint64_t getDebugSectionOffset () const
DIE & getUnitDie ()
const DIE & getUnitDie () const
Public Attributes
std::vector< BaseTypeRef > ExprRefedBaseTypes
Additional Inherited Members
Protected Member Functions inherited from llvm::DwarfUnit
DwarfUnit (dwarf::Tag, const DICompileUnit *Node, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU, unsigned UniqueID=0)
bool applySubprogramDefinitionAttributes (const DISubprogram *SP, DIE &SPDie, bool Minimal)
bool isShareableAcrossCUs (const DINode *D) const
Check whether the DIE for this MDNode can be shared across CUs.
template<typename T>
void addAttribute (DIEValueList &Die, dwarf::Attribute Attribute, dwarf::Form Form, T &&Value)
~DwarfUnit () override
DIE * getOrCreateStaticMemberDIE (const DIDerivedType *DT)
Create new static data member DIE.
void emitCommonHeader (bool UseOffsets, dwarf::UnitType UT)
Emit the common part of the header for this unit.
bool shouldPlaceInUnitDIE (const DISubprogram *SP, bool Minimal)
DIE * getOrCreateSubprogramContextDIE (const DISubprogram *SP, bool IgnoreScope)
Protected Member Functions inherited from llvm::DIEUnit
virtual ~DIEUnit ()=default
.debug_info or .debug_types absolute section offset.
Protected Attributes inherited from llvm::DwarfUnit
unsigned UniqueID
A numeric ID unique among all CUs in the module.
const DICompileUnit * CUNode
MDNode for the compile unit.
BumpPtrAllocator DIEValueAllocator
AsmPrinter * Asm
Target of Dwarf emission.
MCSymbol * LabelBegin = nullptr
The start of the unit within its section.
MCSymbol * EndLabel = nullptr
Emitted at the end of the CU and used to compute the CU Length field.
DwarfDebug * DD
DwarfFile * DU
DIE * IndexTyDie = nullptr
An anonymous type for index type. Owned by DIEUnit.
DenseMap< const MDNode *, DIE * > MDNodeToDieMap
Tracks the mapping of unit level debug information variables to debug information entries.
std::vector< DIEBlock * > DIEBlocks
A list of all the DIEBlocks in use.
std::vector< DIELoc * > DIELocs
A list of all the DIELocs in use.
DenseMap< DIE *, const DINode * > ContainingTypeMap
This map is used to keep track of subprogram DIEs that need DW_AT_containing_type attribute.
Detailed Description
Definition at line 45 of file DwarfCompileUnit.h.
Member Typedef Documentation
InlinedEntity
using llvm::DwarfCompileUnit::InlinedEntity = DbgValueHistoryMap::InlinedEntity
Find abstract variable associated with Var.
Definition at line 343 of file DwarfCompileUnit.h.
Constructor & Destructor Documentation
DwarfCompileUnit()
DwarfCompileUnit::DwarfCompileUnit (unsigned UID, const DICompileUnit * Node, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU, UnitKind Kind = UnitKind::Full)
Definition at line 99 of file DwarfCompileUnit.cpp.
References A(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DwarfUnit(), GetCompileUnitType(), llvm::DIEUnit::getUnitDie(), and llvm::DwarfUnit::insertDIE().
Referenced by getCU(), getSkeleton(), and setSkeleton().
Member Function Documentation
addAddress()
void DwarfCompileUnit::addAddress (DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Add an address attribute to a die based on the location provided.
Definition at line 1684 of file DwarfCompileUnit.cpp.
Referenced by addVariableAddress(), constructCallSiteEntryDIE(), constructCallSiteParmEntryDIEs(), and updateSubprogramScopeDIE().
addAddrTableBase()
void DwarfCompileUnit::addAddrTableBase ()
Add the DW_AT_addr_base attribute to the unit DIE.
Definition at line 1803 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfAddrSection(), and llvm::DIEUnit::getUnitDie().
addBaseTypeRef()
void DwarfCompileUnit::addBaseTypeRef (DIEValueList & Die, int64_t Idx)
Definition at line 1812 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addAttribute(), and llvm::DwarfUnit::DIEValueAllocator.
addComplexAddress()
void DwarfCompileUnit::addComplexAddress (const DIExpression * DIExpr, DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable (navigating the extra location information encoded in the type) based on the starting location.
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable given the extra address information encoded in the DbgVariable, starting from the starting location.
Add the DWARF information to the die.
Definition at line 1704 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfExpression::addExpression(), llvm::DwarfExpression::addFragmentOffset(), llvm::DwarfExpression::addMachineRegExpression(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, llvm::DwarfExpression::beginEntryValueExpression(), llvm::DwarfUnit::DIEValueAllocator, llvm::DIEDwarfExpression::finalize(), llvm::DIExpression::isEntryValue(), llvm::DwarfExpression::setLocation(), llvm::DwarfExpression::TagOffset, and TRI.
Referenced by addVariableAddress().
addExpr()
void DwarfCompileUnit::addExpr (DIELoc & Die, dwarf::Form Form, const MCExpr * Expr)
Add a Dwarf expression attribute data and value.
Definition at line 1773 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addAttribute().
Referenced by addLocationAttribute().
addGlobalName()
void DwarfCompileUnit::addGlobalName (StringRef Name, const DIE & Die, const DIScope * Context) override virtual
Add a new global name to the compile unit.
addGlobalName - Add a new global name to the compile unit.
Implements llvm::DwarfUnit.
Definition at line 1611 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), and hasDwarfPubSections().
Referenced by applySubprogramAttributesToDefinition(), getOrCreateCommonBlock(), and getOrCreateGlobalVariableDIE().
addGlobalNameForTypeUnit()
void DwarfCompileUnit::addGlobalNameForTypeUnit (StringRef Name, const DIScope * Context)
Add a new global name present in a type unit to this compile unit.
Definition at line 1619 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), llvm::DIEUnit::getUnitDie(), and hasDwarfPubSections().
Referenced by llvm::DwarfTypeUnit::addGlobalName().
addGlobalTypeImpl()
void DwarfCompileUnit::addGlobalTypeImpl (const DIType * Ty, const DIE & Die, const DIScope * Context) override virtual
Add a new global type to the compile unit.
Add a new global type to the unit.
Implements llvm::DwarfUnit.
Definition at line 1632 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), and hasDwarfPubSections().
addGlobalTypeUnitType()
void DwarfCompileUnit::addGlobalTypeUnitType (const DIType * Ty, const DIScope * Context)
Add a new global type present in a type unit to this compile unit.
Definition at line 1640 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), llvm::DIEUnit::getUnitDie(), and hasDwarfPubSections().
Referenced by llvm::DwarfTypeUnit::addGlobalTypeImpl().
addLabelAddress()
void DwarfCompileUnit::addLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLabelAddress - Add a dwarf label attribute data and value using either DW_FORM_addr or DW_FORM_GNU_addr_index.
addLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr or DW_FORM_GNU_addr_index.
Definition at line 109 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addAttribute(), llvm::DwarfUnit::addBlock(), addLocalLabelAddress(), llvm::DwarfUnit::addPoolOpAddress(), assert(), llvm::sampleprof::Base, llvm::DwarfUnit::DD, and llvm::DwarfUnit::DIEValueAllocator.
Referenced by attachLowHighPC(), constructCallSiteEntryDIE(), and finishEntityDefinition().
addLocalLabelAddress()
void DwarfCompileUnit::addLocalLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLocalLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr only.
Definition at line 149 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addAttribute().
Referenced by addLabelAddress().
addLocationAttribute()
void DwarfCompileUnit::addLocationAttribute (DIE * ToDIE, const DIGlobalVariable * GV, ArrayRef< GlobalExpr > GlobalExprs)
Definition at line 244 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addConstantValue(), addExpr(), llvm::DwarfUnit::addLinkageName(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addSInt(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, assert(), llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::NVPTXAS::DWARF_ADDR_global_space, llvm::DIExpression::extractAddressClass(), llvm::DIExpression::getElement(), llvm::DIGlobalVariable::getLinkageName(), llvm::DIVariable::getName(), llvm::Global, llvm::DIExpression::isConstant(), llvm::Reloc::PIC_, llvm::Reloc::ROPI_RWPI, llvm::Reloc::RWPI, llvm::ArrayRef< T >::size(), translateToNVVMDWARFAddrSpace(), and llvm::DIExpression::UnsignedConstant.
Referenced by getOrCreateCommonBlock(), and getOrCreateGlobalVariableDIE().
addLocationList()
void DwarfCompileUnit::addLocationList (DIE & Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
Definition at line 1731 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addAttribute(), and llvm::DwarfUnit::DD.
addMemoryLocation()
void DwarfCompileUnit::addMemoryLocation (DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location, int64_t Offset)
Add a memory location exprloc to DIE with attribute Attribute at Location + Offset.
Definition at line 1691 of file DwarfCompileUnit.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::DIExpression::appendOffset(), and assert().
Referenced by constructCallSiteEntryDIE().
addRange()
void DwarfCompileUnit::addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
Definition at line 438 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, and Range.
Referenced by llvm::DwarfDebug::endFunctionImpl().
addScopeRangeList()
void DwarfCompileUnit::addScopeRangeList (DIE & ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
Definition at line 654 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addSectionDelta(), llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::DwarfUnit::DU, llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfRangesSection(), and Range.
Referenced by attachRangesOrLowHighPC().
addVariableAddress()
void DwarfCompileUnit::addVariableAddress (const DbgVariable & DV, DIE & Die, MachineLocation Location)
Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
Definition at line 1652 of file DwarfCompileUnit.cpp.
References addAddress(), and addComplexAddress().
applyCommonDbgVariableAttributes()
void DwarfCompileUnit::applyCommonDbgVariableAttributes (const DbgVariable & Var, DIE & VariableDie)
Add attributes to Var which reflect the common attributes of VariableDie, namely those which are not dependant on the active variant.
Definition at line 1739 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addAnnotation(), llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addType(), llvm::DwarfUnit::addUInt(), llvm::DbgVariable::getName(), llvm::DbgVariable::getType(), llvm::DbgVariable::getVariable(), and llvm::DbgVariable::isArtificial().
Referenced by constructVariableDIE(), and finishEntityDefinition().
applyLabelAttributes()
void DwarfCompileUnit::applyLabelAttributes (const DbgLabel & Label, DIE & LabelDie)
Definition at line 1758 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addUInt(), llvm::DILabel::getCoroSuspendIdx(), and llvm::DILabel::isArtificial().
Referenced by constructLabelDIE(), and finishEntityDefinition().
applyStmtList()
void DwarfCompileUnit::applyStmtList (DIE & D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
Definition at line 482 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::Asm, D(), llvm::MCSection::getBeginSymbol(), and llvm::MCObjectFileInfo::getDwarfLineSection().
applySubprogramAttributesToDefinition()
void DwarfCompileUnit::applySubprogramAttributesToDefinition (const DISubprogram * SP, DIE & SPDie)
Definition at line 1778 of file DwarfCompileUnit.cpp.
References addGlobalName(), llvm::DwarfUnit::applySubprogramAttributes(), and includeMinimalInlineScopes().
Referenced by finishSubprogramDefinition().
attachLexicalScopesAbstractOrigins()
void DwarfCompileUnit::attachLexicalScopesAbstractOrigins ()
Definition at line 1540 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), and lookup().
attachLowHighPC()
void DwarfCompileUnit::attachLowHighPC (DIE & D, const MCSymbol * Begin, const MCSymbol * End)
Definition at line 488 of file DwarfCompileUnit.cpp.
References addLabelAddress(), llvm::DwarfUnit::addLabelDelta(), assert(), D(), llvm::DwarfUnit::DD, llvm::MCSymbol::isDefined(), and llvm::isRangeRelaxable().
Referenced by attachRangesOrLowHighPC().
attachRangesOrLowHighPC() [1/2]
void DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, const SmallVectorImpl< InsnRange > & Ranges)
Definition at line 702 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::DwarfUnit::EndLabel, MBB, and llvm::SmallVectorImpl< T >::reserve().
attachRangesOrLowHighPC() [2/2]
void DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, SmallVector< RangeSpan, 2 > Ranges)
Definition at line 687 of file DwarfCompileUnit.cpp.
References addScopeRangeList(), assert(), attachLowHighPC(), llvm::RangeSpan::Begin, llvm::DwarfUnit::DD, and llvm::RangeSpan::End.
Referenced by attachRangesOrLowHighPC(), constructInlinedScopeDIE(), constructLexicalScopeDIE(), and updateSubprogramScopeDIE().
constructAbstractSubprogramScopeDIE()
void DwarfCompileUnit::constructAbstractSubprogramScopeDIE (LexicalScope * Scope)
Definition at line 1252 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::cast(), and createAndAddScopeChildren().
constructCallSiteEntryDIE()
DIE & DwarfCompileUnit::constructCallSiteEntryDIE (DIE & ScopeDIE, const DISubprogram * CalleeSP, const Function * CalleeF, bool IsTail, const MCSymbol * PCAddr, const MCSymbol * CallAddr, MachineLocation CallTarget, int64_t Offset, DIType * AllocSiteTy)
Construct a call site entry DIE describing a call within Scope to a callee described by CalleeSP and CalleeF.
IsTail specifies whether the call is a tail call. PCAddr points to the PC value after the call instruction. CallAddr points to the PC value at the call instruction (or is null). CallTarget a location holding the target address for an indirect call. For direct calls CallTarget register is set to 0. Offset from CallTarget register value if the location is indirect.
Definition at line 1323 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addFlag(), addLabelAddress(), llvm::DwarfUnit::addLinkageName(), AddLinkageNamesToDeclCallOriginsForTuning(), addMemoryLocation(), llvm::DwarfUnit::addType(), llvm::DwarfUnit::Asm, assert(), llvm::DwarfUnit::createAndAddDIE(), llvm::DwarfUnit::DD, llvm::DIE::findAttribute(), getDwarf5OrGNUAttr(), getDwarf5OrGNUTag(), getOrCreateSubprogramDIE(), llvm::MachineLocation::getReg(), llvm::MachineLocation::isIndirect(), TRI, and useGNUAnalogForDwarf5Feature().
constructCallSiteParmEntryDIEs()
void DwarfCompileUnit::constructCallSiteParmEntryDIEs (DIE & CallSiteDIE, SmallVector< DbgCallSiteParam, 4 > & Params)
Construct call site parameter DIEs for the CallSiteDIE.
The Params were collected by the collectCallSiteParameters. Note: The order of parameters does not matter, since debuggers recognize call site parameters by the DW_AT_location attribute.
Definition at line 1400 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addBlock(), llvm::DIE::addChild(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DIEValueAllocator, llvm::DwarfDebug::emitDebugLocValue(), llvm::DIEDwarfExpression::finalize(), llvm::DIE::get(), getDwarf5OrGNUAttr(), getDwarf5OrGNUTag(), llvm::DwarfUnit::insertDIE(), and llvm::DwarfExpression::setCallSiteParamValueFlag().
constructImportedEntityDIE()
DIE * DwarfCompileUnit::constructImportedEntityDIE (const DIImportedEntity * IE)
Definition at line 1424 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), assert(), llvm::cast(), constructImportedEntityDIE(), llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::dyn_cast(), llvm::DIE::get(), llvm::DwarfUnit::getDIE(), llvm::Module::getName(), getOrCreateGlobalVariableDIE(), getOrCreateImportedEntityDIE(), llvm::DwarfUnit::getOrCreateModule(), llvm::DwarfUnit::getOrCreateNameSpace(), getOrCreateSubprogramDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfUnit::insertDIE(), lookup(), and T.
Referenced by constructImportedEntityDIE(), and getOrCreateImportedEntityDIE().
constructInlinedScopeDIE()
DIE * DwarfCompileUnit::constructInlinedScopeDIE (LexicalScope * Scope, DIE & ParentScopeDIE)
This scope represents an inlined body of a function.
Construct a DIE to represent this concrete inlined copy of the function.
Definition at line 736 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addUInt(), assert(), attachRangesOrLowHighPC(), llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::DIE::get(), llvm::getDISubprogram(), and getOrCreateSourceID().
Referenced by constructScopeDIE().
constructLabelDIE()
DIE * DwarfCompileUnit::constructLabelDIE (DbgLabel & DL, const LexicalScope & Scope)
Construct a DIE for the given DbgLabel.
Definition at line 1012 of file DwarfCompileUnit.cpp.
References applyLabelAttributes(), llvm::DwarfUnit::DIEValueAllocator, DL, llvm::DIE::get(), and llvm::DwarfUnit::insertDIE().
Referenced by createAndAddScopeChildren().
constructLexicalScopeDIE()
DIE * DwarfCompileUnit::constructLexicalScopeDIE (LexicalScope * Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
Definition at line 773 of file DwarfCompileUnit.cpp.
References assert(), attachRangesOrLowHighPC(), llvm::count(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, and llvm::DIE::get().
Referenced by constructScopeDIE().
constructScopeDIE()
void DwarfCompileUnit::constructScopeDIE (LexicalScope * Scope, DIE & ParentScopeDIE)
Definition at line 622 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), assert(), constructInlinedScopeDIE(), constructLexicalScopeDIE(), createAndAddScopeChildren(), llvm::DwarfUnit::DD, and llvm::isa().
Referenced by createAndAddScopeChildren().
constructSubprogramScopeDIE()
DIE & DwarfCompileUnit::constructSubprogramScopeDIE (const DISubprogram * Sub, const Function & F, LexicalScope * Scope, MCSymbol * LineTableSym)
Construct a DIE for this subprogram scope.
Definition at line 1127 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), llvm::DwarfUnit::addDIEEntry(), assert(), createAndAddScopeChildren(), llvm::DwarfUnit::DIEValueAllocator, F, llvm::DIE::get(), includeMinimalInlineScopes(), llvm::DITypeRefArray::size(), llvm::Sub, and updateSubprogramScopeDIE().
Referenced by llvm::DwarfDebug::endFunctionImpl().
constructVariableDIE() [1/2]
DIE * DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, bool Abstract = false)
Construct a DIE for the given DbgVariable.
Definition at line 798 of file DwarfCompileUnit.cpp.
References applyCommonDbgVariableAttributes(), llvm::DbgVariable::asVariant(), llvm::DwarfUnit::DIEValueAllocator, llvm::DIE::get(), llvm::DbgVariable::getTag(), llvm::DbgVariable::getVariable(), llvm::DwarfUnit::insertDIE(), and llvm::DbgEntity::setDIE().
Referenced by constructVariableDIE(), and createAndAddScopeChildren().
constructVariableDIE() [2/2]
DIE * DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, const LexicalScope & Scope, DIE *& ObjectPointer)
Convenience overload which writes the DIE pointer into an out variable ObjectPointer in addition to returning it.
Definition at line 1003 of file DwarfCompileUnit.cpp.
References constructVariableDIE(), and llvm::DbgVariable::isObjectPointer().
createAbstractEntity()
void DwarfCompileUnit::createAbstractEntity (const DINode * Node, LexicalScope * Scope)
Definition at line 1561 of file DwarfCompileUnit.cpp.
References assert(), llvm::cast(), llvm::DwarfUnit::DU, and llvm::isa().
Referenced by llvm::DwarfDebug::endFunctionImpl().
createAndAddScopeChildren()
DIE * DwarfCompileUnit::createAndAddScopeChildren (LexicalScope * Scope, DIE & ScopeDIE)
Definition at line 1157 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), constructLabelDIE(), constructScopeDIE(), constructVariableDIE(), createAndAddScopeChildren(), llvm::DwarfUnit::DD, DL, llvm::DwarfUnit::DU, includeMinimalInlineScopes(), llvm::isa(), and sortLocalVars().
Referenced by constructAbstractSubprogramScopeDIE(), constructScopeDIE(), constructSubprogramScopeDIE(), and createAndAddScopeChildren().
createBaseTypeDIEs()
void DwarfCompileUnit::createBaseTypeDIEs ()
Definition at line 1817 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChildFront(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addUInt(), llvm::dwarf::AttributeEncodingString(), llvm::DwarfUnit::DIEValueAllocator, llvm::divideCeil(), ExprRefedBaseTypes, llvm::DIE::get(), llvm::DIEUnit::getUnitDie(), llvm::reverse(), and llvm::Twine::toStringRef().
emitFuncLineTableOffsets()
bool DwarfCompileUnit::emitFuncLineTableOffsets () const
Definition at line 1799 of file DwarfCompileUnit.cpp.
References EmitFuncLineTableOffsetsOption.
Referenced by updateSubprogramScopeDIE().
emitHeader()
void DwarfCompileUnit::emitHeader (bool UseOffsets) override virtual
Emit the header for this unit, not including the initial length field.
Implements llvm::DwarfUnit.
Definition at line 1576 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::DwarfUnit::emitCommonHeader(), getDWOId(), and llvm::DwarfUnit::LabelBegin.
finishEntityDefinition()
void DwarfCompileUnit::finishEntityDefinition (const DbgEntity * Entity)
Label may be used to generate DW_AT_low_pc, so put it outside if/else block.
Definition at line 1507 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::addAccelName(), llvm::DwarfUnit::addDIEEntry(), addLabelAddress(), applyCommonDbgVariableAttributes(), applyLabelAttributes(), llvm::DwarfUnit::CUNode, llvm::dyn_cast(), llvm::DbgEntity::getDIE(), llvm::DwarfUnit::getDwarfDebug(), llvm::DbgEntity::getEntity(), getExistingAbstractEntity(), and llvm_unreachable.
finishSubprogramDefinition()
void DwarfCompileUnit::finishSubprogramDefinition (const DISubprogram * SP)
Definition at line 1493 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), applySubprogramAttributesToDefinition(), assert(), D(), llvm::DwarfUnit::getDIE(), includeMinimalInlineScopes(), and lookup().
getBaseAddress()
const MCSymbol * llvm::DwarfCompileUnit::getBaseAddress () const inline
Definition at line 429 of file DwarfCompileUnit.h.
getCU()
DwarfCompileUnit & llvm::DwarfCompileUnit::getCU () inline override virtual
Implements llvm::DwarfUnit.
Definition at line 229 of file DwarfCompileUnit.h.
References DwarfCompileUnit().
Referenced by getOrCreateCommonBlock().
getDeferredLocalDecls()
MDNodeSetVector & llvm::DwarfCompileUnit::getDeferredLocalDecls () inline
Definition at line 438 of file DwarfCompileUnit.h.
getDwarf5OrGNUAttr()
dwarf::Attribute DwarfCompileUnit::getDwarf5OrGNUAttr (dwarf::Attribute Attr) const
This takes a DWARF 5 attribute and returns it or a GNU analog.
Definition at line 1288 of file DwarfCompileUnit.cpp.
References llvm_unreachable, and useGNUAnalogForDwarf5Feature().
Referenced by constructCallSiteEntryDIE(), and constructCallSiteParmEntryDIEs().
getDwarf5OrGNULocationAtom()
dwarf::LocationAtom DwarfCompileUnit::getDwarf5OrGNULocationAtom (dwarf::LocationAtom Loc) const
This takes a DWARF 5 location atom and either returns it or a GNU analog.
Definition at line 1312 of file DwarfCompileUnit.cpp.
References llvm_unreachable, and useGNUAnalogForDwarf5Feature().
getDwarf5OrGNUTag()
dwarf::Tag DwarfCompileUnit::getDwarf5OrGNUTag (dwarf::Tag Tag) const
This takes a DWARF 5 tag and returns it or a GNU analog.
Definition at line 1274 of file DwarfCompileUnit.cpp.
References llvm_unreachable, and useGNUAnalogForDwarf5Feature().
Referenced by constructCallSiteEntryDIE(), and constructCallSiteParmEntryDIEs().
getDWOId()
uint64_t llvm::DwarfCompileUnit::getDWOId () const inline
Definition at line 431 of file DwarfCompileUnit.h.
Referenced by emitHeader().
getExistingAbstractEntity()
DbgEntity * DwarfCompileUnit::getExistingAbstractEntity (const DINode * Node)
Definition at line 1553 of file DwarfCompileUnit.cpp.
References I.
Referenced by llvm::DwarfDebug::endFunctionImpl(), and finishEntityDefinition().
getGlobalNames()
const StringMap< const DIE * > & llvm::DwarfCompileUnit::getGlobalNames () const inline
Definition at line 385 of file DwarfCompileUnit.h.
getGlobalTypes()
const StringMap< const DIE * > & llvm::DwarfCompileUnit::getGlobalTypes () const inline
Definition at line 386 of file DwarfCompileUnit.h.
getHeaderSize()
unsigned llvm::DwarfCompileUnit::getHeaderSize () const inline override virtual
Compute the size of a header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 350 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::DD, and llvm::DwarfUnit::getHeaderSize().
Referenced by getLength().
getLength()
unsigned llvm::DwarfCompileUnit::getLength () inline
Definition at line 357 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::Asm, getHeaderSize(), llvm::DIE::getSize(), and llvm::DIEUnit::getUnitDie().
getLexicalBlockDIE()
DIE * DwarfCompileUnit::getLexicalBlockDIE (const DILexicalBlock * LB)
Get a DIE for the given DILexicalBlock.
Note that this function assumes that the DIE has been already created and it's an error, if it hasn't.
Definition at line 1842 of file DwarfCompileUnit.cpp.
References assert(), and llvm::DILocalScope::getSubprogram().
Referenced by getOrCreateContextDIE().
getLineTableStartSym()
MCSymbol * llvm::DwarfCompileUnit::getLineTableStartSym () const inline
Get line table start symbol for this unit.
Definition at line 190 of file DwarfCompileUnit.h.
getMacroLabelBegin()
MCSymbol * llvm::DwarfCompileUnit::getMacroLabelBegin () const inline
Definition at line 367 of file DwarfCompileUnit.h.
getOrCreateAbstractSubprogramDIE()
DIE & DwarfCompileUnit::getOrCreateAbstractSubprogramDIE (const DISubprogram * SP)
Create an abstract subprogram DIE, that should later be populated by constructAbstractSubprogramScopeDIE.
Definition at line 1205 of file DwarfCompileUnit.cpp.
References lookup().
getOrCreateCommonBlock()
DIE * DwarfCompileUnit::getOrCreateCommonBlock (const DICommonBlock * CB, ArrayRef< GlobalExpr > GlobalExprs)
Definition at line 421 of file DwarfCompileUnit.cpp.
References addGlobalName(), addLocationAttribute(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::createAndAddDIE(), llvm::StringRef::empty(), getCU(), llvm::DICommonBlock::getDecl(), llvm::DwarfUnit::getDIE(), llvm::DICommonBlock::getFile(), llvm::DICommonBlock::getLineNo(), llvm::DICommonBlock::getName(), getOrCreateContextDIE(), and llvm::DICommonBlock::getScope().
Referenced by getOrCreateGlobalVariableDIE().
getOrCreateContextDIE()
DIE * DwarfCompileUnit::getOrCreateContextDIE (const DIScope * Ty) override virtual
Construct a DIE for a given scope.
This instance of 'getOrCreateContextDIE()' can handle DILocalScope.
Reimplemented from llvm::DwarfUnit.
Definition at line 1856 of file DwarfCompileUnit.cpp.
References llvm::cast(), llvm::dyn_cast(), getLexicalBlockDIE(), llvm::DwarfUnit::getOrCreateContextDIE(), and llvm::isa_and_nonnull().
Referenced by getOrCreateCommonBlock(), getOrCreateGlobalVariableDIE(), and getOrCreateImportedEntityDIE().
getOrCreateGlobalVariableDIE()
DIE * DwarfCompileUnit::getOrCreateGlobalVariableDIE (const DIGlobalVariable * GV, ArrayRef< GlobalExpr > GlobalExprs)
Get or create global variable DIE.
Definition at line 178 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addAnnotation(), llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addFlag(), addGlobalName(), addLocationAttribute(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addTemplateParams(), llvm::DwarfUnit::addType(), llvm::DwarfUnit::addUInt(), assert(), llvm::DwarfUnit::createAndAddDIE(), llvm::dyn_cast(), llvm::StringRef::empty(), llvm::DIVariable::getAlignInBytes(), llvm::DIGlobalVariable::getAnnotations(), llvm::DwarfUnit::getDIE(), llvm::DIGlobalVariable::getDisplayName(), llvm::DIVariable::getName(), getOrCreateCommonBlock(), getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DIVariable::getScope(), llvm::DIGlobalVariable::getStaticDataMemberDeclaration(), llvm::DINode::getTag(), llvm::DIGlobalVariable::getTemplateParams(), llvm::DIVariable::getType(), llvm::DIGlobalVariable::isDefinition(), and llvm::DIGlobalVariable::isLocalToUnit().
Referenced by constructImportedEntityDIE().
getOrCreateImportedEntityDIE()
DIE * DwarfCompileUnit::getOrCreateImportedEntityDIE (const DIImportedEntity * IE)
Get or create a DIE for an imported entity.
Definition at line 1478 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), assert(), constructImportedEntityDIE(), llvm::DwarfUnit::getDIE(), and getOrCreateContextDIE().
Referenced by constructImportedEntityDIE().
getOrCreateSourceID()
unsigned DwarfCompileUnit::getOrCreateSourceID (const DIFile * File) override virtual
Look up the source ID for the given file.
If none currently exists, create a new ID and insert it in the line table.
Implements llvm::DwarfUnit.
Definition at line 158 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, and llvm::DwarfUnit::getUniqueID().
Referenced by constructInlinedScopeDIE().
getOrCreateSubprogramDIE()
DIE * DwarfCompileUnit::getOrCreateSubprogramDIE (const DISubprogram * SP, const Function * F, bool Minimal = false) override virtual
Reimplemented from llvm::DwarfUnit.
Definition at line 1872 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, F, and llvm::DwarfUnit::getOrCreateSubprogramDIE().
Referenced by constructCallSiteEntryDIE(), constructImportedEntityDIE(), and updateSubprogramScopeDIE().
getRanges()
const SmallVectorImpl< RangeSpan > & llvm::DwarfCompileUnit::getRanges () const inline
getRanges - Get the list of ranges for this unit.
Definition at line 425 of file DwarfCompileUnit.h.
getSkeleton()
DwarfCompileUnit * llvm::DwarfCompileUnit::getSkeleton () const inline
Definition at line 176 of file DwarfCompileUnit.h.
References DwarfCompileUnit().
Referenced by llvm::DwarfDebug::endFunctionImpl().
hasDwarfPubSections()
bool DwarfCompileUnit::hasDwarfPubSections () const
Definition at line 1591 of file DwarfCompileUnit.cpp.
References llvm::Apple, llvm::DICompileUnit::Apple, llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DICompileUnit::Default, llvm::DICompileUnit::GNU, includeMinimalInlineScopes(), llvm_unreachable, and llvm::DICompileUnit::None.
Referenced by addGlobalName(), addGlobalNameForTypeUnit(), addGlobalTypeImpl(), and addGlobalTypeUnitType().
hasRangeLists()
bool llvm::DwarfCompileUnit::hasRangeLists () const inline
Definition at line 174 of file DwarfCompileUnit.h.
includeMinimalInlineScopes()
bool DwarfCompileUnit::includeMinimalInlineScopes () const
Definition at line 1794 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm::DwarfUnit::getCUNode(), llvm::DICompileUnit::getEmissionKind(), and llvm::DICompileUnit::LineTablesOnly.
Referenced by applySubprogramAttributesToDefinition(), constructSubprogramScopeDIE(), createAndAddScopeChildren(), finishSubprogramDefinition(), hasDwarfPubSections(), and updateSubprogramScopeDIE().
initStmtList()
void DwarfCompileUnit::initStmtList ()
Definition at line 461 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfLineSection(), llvm::DwarfUnit::getUniqueID(), and llvm::DIEUnit::getUnitDie().
setBaseAddress()
void llvm::DwarfCompileUnit::setBaseAddress (const MCSymbol * Base) inline
Definition at line 428 of file DwarfCompileUnit.h.
References llvm::sampleprof::Base.
setDWOId()
void llvm::DwarfCompileUnit::setDWOId (uint64_t DwoId) inline
Definition at line 432 of file DwarfCompileUnit.h.
setSkeleton()
void llvm::DwarfCompileUnit::setSkeleton (DwarfCompileUnit & Skel) inline
Set the skeleton unit associated with this unit.
Definition at line 348 of file DwarfCompileUnit.h.
References DwarfCompileUnit().
takeRanges()
SmallVector< RangeSpan, 2 > llvm::DwarfCompileUnit::takeRanges () inline
Definition at line 426 of file DwarfCompileUnit.h.
updateSubprogramScopeDIE()
DIE & DwarfCompileUnit::updateSubprogramScopeDIE (const DISubprogram * SP, const Function & F, MCSymbol * LineTableSym)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc, DW_AT_high_pc and DW_AT_LLVM_stmt_sequence attributes.
If there are global variables in this scope then create and insert DIEs for these variables.
Definition at line 541 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addBlock(), llvm::DwarfExpression::addExpression(), llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::addSectionLabel(), llvm::DwarfUnit::addSInt(), llvm::DwarfUnit::addUInt(), llvm::DwarfExpression::addWasmLocation(), llvm::DwarfUnit::Asm, assert(), attachRangesOrLowHighPC(), llvm::TargetFrameLowering::DwarfFrameBase::CFA, llvm::DwarfUnit::CUNode, llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, emitFuncLineTableOffsets(), F, llvm::DIEDwarfExpression::finalize(), llvm::TargetFrameLowering::getDwarfFrameBase(), getOrCreateSubprogramDIE(), includeMinimalInlineScopes(), llvm::TargetFrameLowering::DwarfFrameBase::WasmFrameBase::Index, llvm::Register::isPhysicalRegister(), llvm::TargetFrameLowering::DwarfFrameBase::Kind, llvm::TargetFrameLowering::DwarfFrameBase::WasmFrameBase::Kind, llvm::TargetFrameLowering::DwarfFrameBase::Location, llvm::TargetFrameLowering::DwarfFrameBase::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::TargetFrameLowering::DwarfFrameBase::Reg, llvm::TargetFrameLowering::DwarfFrameBase::Register, and llvm::TargetFrameLowering::DwarfFrameBase::WasmLoc.
Referenced by constructSubprogramScopeDIE().
useGNUAnalogForDwarf5Feature()
bool DwarfCompileUnit::useGNUAnalogForDwarf5Feature () const
Whether to use the GNU analog for a DWARF5 tag, attribute, or location atom.
Only applicable when emitting otherwise DWARF4-compliant debug info.
Definition at line 1270 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD.
Referenced by constructCallSiteEntryDIE(), getDwarf5OrGNUAttr(), getDwarf5OrGNULocationAtom(), and getDwarf5OrGNUTag().
Member Data Documentation
ExprRefedBaseTypes
std::vector<BaseTypeRef> llvm::DwarfCompileUnit::ExprRefedBaseTypes
Definition at line 206 of file DwarfCompileUnit.h.
Referenced by createBaseTypeDIEs().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfCompileUnit.h
lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp