LLVM: llvm::sandboxir::RegionsFromBBs Class Reference
llvm::sandboxir::RegionsFromBBs Class Reference final
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Passes/RegionsFromBBs.h"
Public Member Functions
RegionsFromBBs (StringRef Pipeline)
bool runOnFunction (Function &F, const Analyses &A) final
\Returns true if it modifies F.
void printPipeline (raw_ostream &OS) const final
Similar to print() but adds a newline. Used for testing.
Public Member Functions inherited from llvm::sandboxir::FunctionPass
FunctionPass (StringRef Name)
Name can't contain any spaces or start with '-'.
Public Member Functions inherited from llvm::sandboxir::Pass
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()=default
StringRef getName () const
\Returns the name of the pass.
virtual void print (raw_ostream &OS) const
LLVM_ABI_FOR_TEST virtual LLVM_DUMP_METHOD void dump () const
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::Pass
const std::string Name
The pass name.
Detailed Description
Definition at line 23 of file RegionsFromBBs.h.
Constructor & Destructor Documentation
RegionsFromBBs()
llvm::sandboxir::RegionsFromBBs::RegionsFromBBs (StringRef Pipeline)
Definition at line 16 of file RegionsFromBBs.cpp.
References llvm::sandboxir::FunctionPass::FunctionPass().
Member Function Documentation
printPipeline()
void llvm::sandboxir::RegionsFromBBs::printPipeline (raw_ostream & OS) const inline final virtual
Similar to print() but adds a newline. Used for testing.
Reimplemented from llvm::sandboxir::Pass.
Definition at line 30 of file RegionsFromBBs.h.
References llvm::sandboxir::Pass::getName().
runOnFunction()
bool llvm::sandboxir::RegionsFromBBs::runOnFunction (Function & F, const Analyses & A) final virtual
\Returns true if it modifies F.
Implements llvm::sandboxir::FunctionPass.
Definition at line 20 of file RegionsFromBBs.cpp.
References A(), llvm::SmallVectorTemplateCommon< T, typename >::back(), F, I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Passes/RegionsFromBBs.h
lib/Transforms/Vectorize/SandboxVectorizer/Passes/RegionsFromBBs.cpp