LLVM: llvm::jitlink::x86_64::PLTTableManager Class Reference
llvm::jitlink::x86_64::PLTTableManager Class Reference
Procedure Linkage Table Builder.
#include "llvm/ExecutionEngine/JITLink/x86_64.h"
Public Member Functions
PLTTableManager (LinkGraph &G, GOTTableManager &GOT)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Section & getStubsSection (LinkGraph &G)
LLVM_ABI void registerExistingEntries ()
Public Member Functions inherited from llvm::jitlink::TableManager< PLTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Public Attributes
GOTTableManager & GOT
Section * StubsSection = nullptr
Detailed Description
Procedure Linkage Table Builder.
Definition at line 736 of file x86_64.h.
Constructor & Destructor Documentation
PLTTableManager()
llvm::jitlink::x86_64::PLTTableManager::PLTTableManager (LinkGraph & G, GOTTableManager & GOT) inline
Definition at line 740 of file x86_64.h.
References G, getSectionName(), GOT, registerExistingEntries(), and StubsSection.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::x86_64::PLTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 761 of file x86_64.h.
References llvm::jitlink::x86_64::createAnonymousPointerJumpStub(), G, getStubsSection(), and GOT.
getSectionName()
StringRef llvm::jitlink::x86_64::PLTTableManager::getSectionName () inline static
Definition at line 738 of file x86_64.h.
Referenced by getStubsSection(), and PLTTableManager().
getStubsSection()
Section & llvm::jitlink::x86_64::PLTTableManager::getStubsSection (LinkGraph & G) inline
Definition at line 767 of file x86_64.h.
References llvm::orc::Exec, G, getSectionName(), llvm::orc::Read, and StubsSection.
Referenced by createEntry().
registerExistingEntries()
void llvm::jitlink::x86_64::PLTTableManager::registerExistingEntries ()
Definition at line 101 of file x86_64.cpp.
References assert(), llvm::jitlink::TableManager< PLTTableManager >::registerPreExistingEntry(), and StubsSection.
Referenced by PLTTableManager().
visitEdge()
bool llvm::jitlink::x86_64::PLTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 745 of file x86_64.h.
References B(), llvm::jitlink::x86_64::BranchPCRel32, llvm::jitlink::x86_64::BranchPCRel32ToPtrJumpStubBypassable, llvm::dbgs(), DEBUG_WITH_TYPE, E(), llvm::formatv(), G, and llvm::jitlink::TableManager< PLTTableManager >::getEntryForTarget().
Member Data Documentation
GOT
GOTTableManager& llvm::jitlink::x86_64::PLTTableManager::GOT
Definition at line 776 of file x86_64.h.
Referenced by createEntry(), and PLTTableManager().
StubsSection
Section* llvm::jitlink::x86_64::PLTTableManager::StubsSection = nullptr
Definition at line 777 of file x86_64.h.
Referenced by getStubsSection(), PLTTableManager(), and registerExistingEntries().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/x86_64.h
lib/ExecutionEngine/JITLink/x86_64.cpp