LLVM: llvm::VPMatchContext Class Reference
llvm::VPMatchContext Class Reference
#include "CodeGen/SelectionDAG/MatchContext.h"
Public Member Functions
VPMatchContext (SelectionDAG &DAG, const TargetLowering &TLI, SDNode *_Root)
unsigned getRootBaseOpcode ()
bool match (SDValue OpVal, unsigned Opc) const
whether OpVal is a node that is functionally compatible with the NodeType Opc
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand, SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDNodeFlags Flags)
bool isOperationLegal (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT, bool LegalOnly=false) const
unsigned getNumOperands (SDValue N) const
Detailed Description
Definition at line 52 of file MatchContext.h.
Constructor & Destructor Documentation
VPMatchContext()
llvm::VPMatchContext::VPMatchContext (SelectionDAG & DAG, const TargetLowering & TLI, SDNode * _Root) inline
Definition at line 60 of file MatchContext.h.
References assert(), llvm::ISD::getVPExplicitVectorLengthIdx(), and llvm::ISD::getVPMaskIdx().
Member Function Documentation
getNode() [1/6]
SDValue llvm::VPMatchContext::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2) inline
Definition at line 120 of file MatchContext.h.
References assert(), DL, llvm::ISD::getVPExplicitVectorLengthIdx(), llvm::ISD::getVPForBaseOpcode(), and llvm::ISD::getVPMaskIdx().
getNode() [2/6]
SDValue llvm::VPMatchContext::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDNodeFlags Flags) inline
Definition at line 146 of file MatchContext.h.
References assert(), DL, llvm::ISD::getVPExplicitVectorLengthIdx(), llvm::ISD::getVPForBaseOpcode(), and llvm::ISD::getVPMaskIdx().
getNode() [3/6]
SDValue llvm::VPMatchContext::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3) inline
Definition at line 128 of file MatchContext.h.
References assert(), DL, llvm::ISD::getVPExplicitVectorLengthIdx(), llvm::ISD::getVPForBaseOpcode(), and llvm::ISD::getVPMaskIdx().
getNode() [4/6]
SDValue llvm::VPMatchContext::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDNodeFlags Flags) inline
Definition at line 155 of file MatchContext.h.
References assert(), DL, llvm::ISD::getVPExplicitVectorLengthIdx(), llvm::ISD::getVPForBaseOpcode(), and llvm::ISD::getVPMaskIdx().
getNode() [5/6]
SDValue llvm::VPMatchContext::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand) inline
Definition at line 112 of file MatchContext.h.
References assert(), DL, llvm::ISD::getVPExplicitVectorLengthIdx(), llvm::ISD::getVPForBaseOpcode(), and llvm::ISD::getVPMaskIdx().
getNode() [6/6]
SDValue llvm::VPMatchContext::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand, SDNodeFlags Flags) inline
Definition at line 137 of file MatchContext.h.
References assert(), DL, llvm::ISD::getVPExplicitVectorLengthIdx(), llvm::ISD::getVPForBaseOpcode(), and llvm::ISD::getVPMaskIdx().
getNumOperands()
unsigned llvm::VPMatchContext::getNumOperands (SDValue N) const inline
Definition at line 175 of file MatchContext.h.
References N.
getRootBaseOpcode()
unsigned llvm::VPMatchContext::getRootBaseOpcode () inline
Definition at line 74 of file MatchContext.h.
References assert(), and llvm::ISD::getBaseOpcodeForVP().
isOperationLegal()
bool llvm::VPMatchContext::isOperationLegal (unsigned Op, EVT VT) const inline
Definition at line 164 of file MatchContext.h.
References llvm::ISD::getVPForBaseOpcode().
isOperationLegalOrCustom()
bool llvm::VPMatchContext::isOperationLegalOrCustom (unsigned Op, EVT VT, bool LegalOnly = false) const inline
Definition at line 169 of file MatchContext.h.
References llvm::ISD::getVPForBaseOpcode().
match()
bool llvm::VPMatchContext::match (SDValue OpVal, unsigned Opc) const inline
whether OpVal is a node that is functionally compatible with the NodeType Opc
Definition at line 83 of file MatchContext.h.
References llvm::ISD::getBaseOpcodeForVP(), llvm::SDNode::getFlags(), llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::getVPExplicitVectorLengthIdx(), llvm::ISD::getVPMaskIdx(), llvm::SDNodeFlags::hasNoFPExcept(), llvm::ISD::isConstantSplatVectorAllOnes(), llvm::SDNode::isVPOpcode(), and Opc.
The documentation for this class was generated from the following file:
lib/CodeGen/SelectionDAG/MatchContext.h