LLVM: llvm::orc::EPCGenericDylibManager Class Reference
llvm::orc::EPCGenericDylibManager Class Reference
#include "llvm/ExecutionEngine/Orc/EPCGenericDylibManager.h"
Classes
struct SymbolAddrs
Function addresses for memory access.
Public Types
using SymbolLookupCompleteFn
Public Member Functions
EPCGenericDylibManager (ExecutorProcessControl &EPC, SymbolAddrs SAs)
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
LLVM_ABI Expected< tpctypes::DylibHandle > open (StringRef Path, uint64_t Mode)
Loads the dylib with the given name.
Expected< tpctypes::LookupResult > lookup (tpctypes::DylibHandle H, const SymbolLookupSet &Lookup)
Looks up symbols within the given dylib.
Expected< tpctypes::LookupResult > lookup (tpctypes::DylibHandle H, const RemoteSymbolLookupSet &Lookup)
Looks up symbols within the given dylib.
LLVM_ABI void lookupAsync (tpctypes::DylibHandle H, const SymbolLookupSet &Lookup, SymbolLookupCompleteFn Complete)
Looks up symbols within the given dylib.
LLVM_ABI void lookupAsync (tpctypes::DylibHandle H, const RemoteSymbolLookupSet &Lookup, SymbolLookupCompleteFn Complete)
Looks up symbols within the given dylib.
Static Public Member Functions
static LLVM_ABI Expected< EPCGenericDylibManager > CreateWithDefaultBootstrapSymbols (ExecutorProcessControl &EPC)
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Detailed Description
Definition at line 31 of file EPCGenericDylibManager.h.
Member Typedef Documentation
SymbolLookupCompleteFn
using llvm::orc::EPCGenericDylibManager::SymbolLookupCompleteFn
Initial value:
unique_function<void(Expected<tpctypes::LookupResult>)>
Definition at line 71 of file EPCGenericDylibManager.h.
Constructor & Destructor Documentation
EPCGenericDylibManager()
llvm::orc::EPCGenericDylibManager::EPCGenericDylibManager (ExecutorProcessControl & EPC, SymbolAddrs SAs) inline
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Definition at line 47 of file EPCGenericDylibManager.h.
Member Function Documentation
CreateWithDefaultBootstrapSymbols()
Expected< EPCGenericDylibManager > llvm::orc::EPCGenericDylibManager::CreateWithDefaultBootstrapSymbols (ExecutorProcessControl & EPC) static
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Definition at line 63 of file EPCGenericDylibManager.cpp.
lookup() [1/2]
Expected< tpctypes::LookupResult > llvm::orc::EPCGenericDylibManager::lookup (tpctypes::DylibHandle H, const RemoteSymbolLookupSet & Lookup) inline
Looks up symbols within the given dylib.
Definition at line 63 of file EPCGenericDylibManager.h.
References H, Lookup(), and lookupAsync().
lookup() [2/2]
Expected< tpctypes::LookupResult > llvm::orc::EPCGenericDylibManager::lookup (tpctypes::DylibHandle H, const SymbolLookupSet & Lookup) inline
Looks up symbols within the given dylib.
Definition at line 54 of file EPCGenericDylibManager.h.
References H, Lookup(), and lookupAsync().
lookupAsync() [1/2]
void llvm::orc::EPCGenericDylibManager::lookupAsync (tpctypes::DylibHandle H, const RemoteSymbolLookupSet & Lookup, SymbolLookupCompleteFn Complete)
Looks up symbols within the given dylib.
Definition at line 103 of file EPCGenericDylibManager.cpp.
References llvm::cantFail(), H, Lookup(), and lookupAsync().
lookupAsync() [2/2]
void llvm::orc::EPCGenericDylibManager::lookupAsync (tpctypes::DylibHandle H, const SymbolLookupSet & Lookup, SymbolLookupCompleteFn Complete)
Looks up symbols within the given dylib.
Definition at line 84 of file EPCGenericDylibManager.cpp.
References llvm::cantFail(), H, Lookup(), and lookupAsync().
Referenced by lookup(), lookup(), lookupAsync(), lookupAsync(), and llvm::orc::lookupSymbolsAsyncHelper().
open()
Expected< tpctypes::DylibHandle > llvm::orc::EPCGenericDylibManager::open (StringRef Path, uint64_t Mode)
Loads the dylib with the given name.
Definition at line 74 of file EPCGenericDylibManager.cpp.
References H, Mode, and open().
Referenced by open().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/EPCGenericDylibManager.h
lib/ExecutionEngine/Orc/EPCGenericDylibManager.cpp