LLVM: llvm::orc::LazyCallThroughManager Class Reference
llvm::orc::LazyCallThroughManager Class Reference
Manages a set of 'lazy call-through' trampolines.
#include "llvm/ExecutionEngine/Orc/LazyReexports.h"
Classes
struct ReexportsEntry
Public Types
using NotifyResolvedFunction
Public Member Functions
LLVM_ABI LazyCallThroughManager (ExecutionSession &ES, ExecutorAddr ErrorHandlerAddr, TrampolinePool *TP)
LLVM_ABI Expected< ExecutorAddr > getCallThroughTrampoline (JITDylib &SourceJD, SymbolStringPtr SymbolName, NotifyResolvedFunction NotifyResolved)
LLVM_ABI void resolveTrampolineLandingAddress (ExecutorAddr TrampolineAddr, TrampolinePool::NotifyLandingResolvedFunction NotifyLandingResolved)
virtual ~LazyCallThroughManager ()=default
Protected Types
using NotifyLandingResolvedFunction
Protected Member Functions
LLVM_ABI ExecutorAddr reportCallThroughError (Error Err)
LLVM_ABI Expected< ReexportsEntry > findReexport (ExecutorAddr TrampolineAddr)
LLVM_ABI Error notifyResolved (ExecutorAddr TrampolineAddr, ExecutorAddr ResolvedAddr)
void setTrampolinePool (TrampolinePool &TP)
Detailed Description
Manages a set of 'lazy call-through' trampolines.
These are compiler re-entry trampolines that are pre-bound to look up a given symbol in a given JITDylib, then jump to that address. Since compilation of symbols is triggered on first lookup, these call-through trampolines can be used to implement lazy compilation.
The easiest way to construct these call-throughs is using the lazyReexport function.
Definition at line 40 of file LazyReexports.h.
Member Typedef Documentation
NotifyLandingResolvedFunction
using llvm::orc::LazyCallThroughManager::NotifyLandingResolvedFunction protected
Initial value:
TrampolinePool::NotifyLandingResolvedFunction
Definition at line 62 of file LazyReexports.h.
NotifyResolvedFunction
using llvm::orc::LazyCallThroughManager::NotifyResolvedFunction
Initial value:
unique_function<Error(ExecutorAddr ResolvedAddr)>
Definition at line 42 of file LazyReexports.h.
Constructor & Destructor Documentation
LazyCallThroughManager()
llvm::orc::LazyCallThroughManager::LazyCallThroughManager (ExecutionSession & ES, ExecutorAddr ErrorHandlerAddr, TrampolinePool * TP)
Definition at line 21 of file LazyReexports.cpp.
~LazyCallThroughManager()
virtual llvm::orc::LazyCallThroughManager::~LazyCallThroughManager () virtual default
Member Function Documentation
findReexport()
Expected< LazyCallThroughManager::ReexportsEntry > llvm::orc::LazyCallThroughManager::findReexport (ExecutorAddr TrampolineAddr) protected
Definition at line 48 of file LazyReexports.cpp.
References llvm::createStringError(), llvm::formatv(), I, and llvm::inconvertibleErrorCode().
Referenced by resolveTrampolineLandingAddress().
getCallThroughTrampoline()
Expected< ExecutorAddr > llvm::orc::LazyCallThroughManager::getCallThroughTrampoline (JITDylib & SourceJD, SymbolStringPtr SymbolName, NotifyResolvedFunction NotifyResolved)
Definition at line 26 of file LazyReexports.cpp.
References assert().
notifyResolved()
Error llvm::orc::LazyCallThroughManager::notifyResolved (ExecutorAddr TrampolineAddr, ExecutorAddr ResolvedAddr) protected
Definition at line 58 of file LazyReexports.cpp.
References I, and llvm::Error::success().
Referenced by resolveTrampolineLandingAddress().
reportCallThroughError()
ExecutorAddr llvm::orc::LazyCallThroughManager::reportCallThroughError (Error Err) protected
Definition at line 42 of file LazyReexports.cpp.
Referenced by resolveTrampolineLandingAddress().
resolveTrampolineLandingAddress()
void llvm::orc::LazyCallThroughManager::resolveTrampolineLandingAddress (ExecutorAddr TrampolineAddr, TrampolinePool::NotifyLandingResolvedFunction NotifyLandingResolved)
Definition at line 73 of file LazyReexports.cpp.
References assert(), findReexport(), llvm::orc::makeJITDylibSearchOrder(), llvm::orc::MatchAllSymbols, llvm::orc::NoDependenciesToRegister, notifyResolved(), llvm::orc::Ready, reportCallThroughError(), llvm::orc::Result, and llvm::orc::Static.
setTrampolinePool()
void llvm::orc::LazyCallThroughManager::setTrampolinePool (TrampolinePool & TP) inline protected
Definition at line 74 of file LazyReexports.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LazyReexports.h
lib/ExecutionEngine/Orc/LazyReexports.cpp