LLVM: llvm::MCSymbolGOFF Class Reference
llvm::MCSymbolGOFF Class Reference
#include "llvm/MC/MCSymbolGOFF.h"
Public Member Functions
MCSymbolGOFF (const MCSymbolTableEntry *Name, bool IsTemporary)
void setADA (MCSectionGOFF *AssociatedDataArea)
MCSectionGOFF * getADA () const
bool isExternal () const
void setExternal (bool Value) const
void setHidden (bool Value=true)
bool isHidden () const
bool isExported () const
void setWeak (bool Value=true)
bool isWeak () const
void setCodeData (GOFF::ESDExecutable Value)
GOFF::ESDExecutable getCodeData () const
void setLinkage (GOFF::ESDLinkageType Value)
GOFF::ESDLinkageType getLinkage () const
GOFF::ESDBindingScope getBindingScope () const
GOFF::ESDBindingStrength getBindingStrength () const
bool setSymbolAttribute (MCSymbolAttr Attribute)
bool isInEDSection () const
Public Member Functions inherited from llvm::MCSymbol
StringRef getName () const
getName - Get the symbol name.
bool isRegistered () const
void setIsRegistered (bool Value) const
void setUsedInReloc () const
bool isUsedInReloc () const
uint32_t getIndex () const
Get the (implementation defined) index.
void setIndex (uint32_t Value) const
Set the (implementation defined) index.
uint64_t getOffset () const
void setOffset (uint64_t Value)
uint64_t getCommonSize () const
Return the size of a 'common' symbol.
void setCommon (uint64_t Size, Align Alignment)
Mark this symbol as being 'common'.
MaybeAlign getCommonAlignment () const
Return the alignment of a 'common' symbol.
bool declareCommon (uint64_t Size, Align Alignment)
Declare this symbol as being 'common'.
bool isCommon () const
Is this a 'common' symbol.
MCFragment * getFragment () const
bool isWeakExternal () const
LLVM_ABI void print (raw_ostream &OS, const MCAsmInfo *MAI) const
print - Print the value to the stream OS.
LLVM_ABI void dump () const
dump - Print the value to stderr.
bool isTemporary () const
isTemporary - Check if this is an assembler temporary symbol.
bool isRedefinable () const
Check if this symbol is redefinable.
void setRedefinable (bool Value)
Mark this symbol as redefinable.
void redefineIfPossible ()
Prepare this symbol to be redefined.
bool isResolving () const
void setIsResolving (bool V)
bool isDefined () const
isDefined - Check if this symbol is defined (i.e., it has an address).
bool isInSection () const
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
bool isUndefined () const
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
bool isAbsolute () const
isAbsolute - Check if this is an absolute symbol.
MCSection & getSection () const
Get the section associated with a defined, non-absolute symbol.
void setFragment (MCFragment *F) const
Mark the symbol as defined in the fragment F.
bool isVariable () const
isVariable - Check if this is a variable symbol.
const MCExpr * getVariableValue () const
Get the expression of the variable symbol.
LLVM_ABI void setVariableValue (const MCExpr *Value)
Additional Inherited Members
Protected Types inherited from llvm::MCSymbol
enum Kind : uint8_t { Regular , Equated , Common }
enum : unsigned { NumCommonAlignmentBits = 5 }
The alignment of the symbol if it is 'common'.
enum : unsigned { NumFlagsBits = 16 }
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
using NameEntryStorageTy
The name for a symbol.
Protected Member Functions inherited from llvm::MCSymbol
MCSymbol (const MCSymbolTableEntry *Name, bool isTemporary)
MCSymbol (const MCSymbol &)=default
MCSymbol & operator= (const MCSymbol &)=delete
LLVM_ABI void * operator new (size_t s, const MCSymbolTableEntry *Name, MCContext &Ctx)
uint32_t getFlags () const
Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value) const
Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask) const
Modify the flags via a mask.
Protected Attributes inherited from llvm::MCSymbol
MCFragment * Fragment = nullptr
If a symbol has a Fragment, the section is implied, so we only need one pointer.
unsigned kind: 2
The symbol kind.
unsigned HasName: 1
True if this symbol is named.
unsigned IsTemporary: 1
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
unsigned IsRedefinable: 1
True if this symbol can be redefined.
unsigned IsRegistered: 1
unsigned IsExternal: 1
True if this symbol is visible outside this translation unit.
unsigned IsPrivateExtern: 1
Mach-O specific: This symbol is private extern.
unsigned IsWeakExternal: 1
This symbol is weak external.
unsigned IsUsedInReloc: 1
True if we have created a relocation that uses this symbol.
unsigned IsResolving: 1
Used to detect cyclic dependency like a = a + 1 and a = b; b = a.
unsigned CommonAlignLog2: NumCommonAlignmentBits
uint32_t Flags: NumFlagsBits
uint32_t Index = 0
Index field, for use by the object file implementation.
union {
uint64_t Offset
The offset to apply to the fragment address to form this symbol's value.
uint64_t CommonSize
The size of the symbol, if it is 'common'.
const MCExpr * Value
If non-null, the value for a variable symbol.
};
Static Protected Attributes inherited from llvm::MCSymbol
static LLVM_ABI MCFragment * AbsolutePseudoFragment = &SentinelFragment
Detailed Description
Definition at line 25 of file MCSymbolGOFF.h.
Constructor & Destructor Documentation
MCSymbolGOFF()
llvm::MCSymbolGOFF::MCSymbolGOFF (const MCSymbolTableEntry * Name, bool IsTemporary) inline
Definition at line 38 of file MCSymbolGOFF.h.
References llvm::MCSymbol::IsTemporary, and llvm::MCSymbol::MCSymbol().
Member Function Documentation
getADA()
MCSectionGOFF * llvm::MCSymbolGOFF::getADA () const inline
Definition at line 45 of file MCSymbolGOFF.h.
getBindingScope()
GOFF::ESDBindingScope llvm::MCSymbolGOFF::getBindingScope () const inline
Definition at line 65 of file MCSymbolGOFF.h.
References llvm::GOFF::ESD_BSC_ImportExport, llvm::GOFF::ESD_BSC_Library, llvm::GOFF::ESD_BSC_Section, llvm::MCSymbol::isDefined(), isExported(), and isExternal().
Referenced by llvm::SystemZHLASMAsmStreamer::emitLabel().
getBindingStrength()
GOFF::ESDBindingStrength llvm::MCSymbolGOFF::getBindingStrength () const inline
Definition at line 72 of file MCSymbolGOFF.h.
References llvm::GOFF::ESD_BST_Strong, llvm::GOFF::ESD_BST_Weak, and isWeak().
getCodeData()
GOFF::ESDExecutable llvm::MCSymbolGOFF::getCodeData () const inline
Definition at line 60 of file MCSymbolGOFF.h.
Referenced by llvm::SystemZHLASMAsmStreamer::emitLabel().
getLinkage()
GOFF::ESDLinkageType llvm::MCSymbolGOFF::getLinkage () const inline
Definition at line 63 of file MCSymbolGOFF.h.
Referenced by llvm::SystemZHLASMAsmStreamer::emitLabel().
isExported()
bool llvm::MCSymbolGOFF::isExported () const inline
Definition at line 54 of file MCSymbolGOFF.h.
References isHidden().
Referenced by getBindingScope().
isExternal()
bool llvm::MCSymbolGOFF::isExternal () const inline
Definition at line 47 of file MCSymbolGOFF.h.
References llvm::MCSymbol::IsExternal.
Referenced by getBindingScope().
isHidden()
bool llvm::MCSymbolGOFF::isHidden () const inline
Definition at line 53 of file MCSymbolGOFF.h.
References llvm::MCSymbol::getFlags().
Referenced by isExported().
isInEDSection()
bool llvm::MCSymbolGOFF::isInEDSection () const inline
Definition at line 79 of file MCSymbolGOFF.h.
References llvm::MCSymbol::getSection(), and llvm::MCSymbol::isInSection().
Referenced by llvm::SystemZHLASMAsmStreamer::emitLabel().
isWeak()
bool llvm::MCSymbolGOFF::isWeak () const inline
Definition at line 57 of file MCSymbolGOFF.h.
References llvm::MCSymbol::getFlags().
Referenced by getBindingStrength().
setADA()
void llvm::MCSymbolGOFF::setADA (MCSectionGOFF * AssociatedDataArea) inline
Definition at line 41 of file MCSymbolGOFF.h.
Referenced by llvm::TargetLoweringObjectFileGOFF::getModuleMetadata().
setCodeData()
void llvm::MCSymbolGOFF::setCodeData (GOFF::ESDExecutable Value) inline
Definition at line 59 of file MCSymbolGOFF.h.
References llvm::MCSymbol::Value.
Referenced by llvm::TargetLoweringObjectFileGOFF::getModuleMetadata(), and setSymbolAttribute().
setExternal()
void llvm::MCSymbolGOFF::setExternal (bool Value) const inline
Definition at line 48 of file MCSymbolGOFF.h.
References llvm::MCSymbol::IsExternal, and llvm::MCSymbol::Value.
Referenced by llvm::TargetLoweringObjectFileGOFF::getModuleMetadata(), and setSymbolAttribute().
setHidden()
void llvm::MCSymbolGOFF::setHidden (bool Value = true) inline
Definition at line 50 of file MCSymbolGOFF.h.
References llvm::MCSymbol::modifyFlags(), and llvm::MCSymbol::Value.
Referenced by setSymbolAttribute().
setLinkage()
void llvm::MCSymbolGOFF::setLinkage (GOFF::ESDLinkageType Value) inline
Definition at line 62 of file MCSymbolGOFF.h.
References llvm::MCSymbol::Value.
Referenced by llvm::TargetLoweringObjectFileGOFF::getModuleMetadata(), and setSymbolAttribute().
setSymbolAttribute()
bool MCSymbolGOFF::setSymbolAttribute (MCSymbolAttr Attribute)
Definition at line 15 of file MCSymbolGOFF.cpp.
References llvm::GOFF::ESD_EXE_CODE, llvm::GOFF::ESD_EXE_DATA, llvm::GOFF::ESD_LT_OS, llvm::GOFF::ESD_LT_XPLink, llvm::MCSA_AltEntry, llvm::MCSA_Cold, llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, llvm::MCSA_Exported, llvm::MCSA_Extern, llvm::MCSA_Global, llvm::MCSA_Hidden, llvm::MCSA_IndirectSymbol, llvm::MCSA_Internal, llvm::MCSA_Invalid, llvm::MCSA_LazyReference, llvm::MCSA_LGlobal, llvm::MCSA_Local, llvm::MCSA_Memtag, llvm::MCSA_NoDeadStrip, llvm::MCSA_OSLinkage, llvm::MCSA_PrivateExtern, llvm::MCSA_Protected, llvm::MCSA_Reference, llvm::MCSA_SymbolResolver, llvm::MCSA_Weak, llvm::MCSA_WeakAntiDep, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::MCSA_WeakReference, llvm::MCSA_XPLinkage, setCodeData(), setExternal(), setHidden(), setLinkage(), and setWeak().
setWeak()
void llvm::MCSymbolGOFF::setWeak (bool Value = true) inline
Definition at line 56 of file MCSymbolGOFF.h.
References llvm::MCSymbol::modifyFlags(), and llvm::MCSymbol::Value.
Referenced by llvm::TargetLoweringObjectFileGOFF::getModuleMetadata(), and setSymbolAttribute().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSymbolGOFF.h
lib/MC/MCSymbolGOFF.cpp