LLVM: llvm::NoopStatistic Class Reference
llvm::NoopStatistic Class Reference
#include "llvm/ADT/Statistic.h"
Public Member Functions
constexpr NoopStatistic (const char *, const char *, const char *)
uint64_t getValue () const
operator uint64_t () const
const NoopStatistic & operator= (uint64_t Val)
const NoopStatistic & operator++ ()
uint64_t operator++ (int)
const NoopStatistic & operator-- ()
uint64_t operator-- (int)
const NoopStatistic & operator+= (const uint64_t &V)
const NoopStatistic & operator-= (const uint64_t &V)
void updateMax (uint64_t V)
Detailed Description
Definition at line 132 of file Statistic.h.
Constructor & Destructor Documentation
NoopStatistic()
llvm::NoopStatistic::NoopStatistic (const char * , const char * , const char *) inline constexpr
Definition at line 134 of file Statistic.h.
Referenced by operator++(), operator+=(), operator--(), operator-=(), and operator=().
Member Function Documentation
getValue()
uint64_t llvm::NoopStatistic::getValue () const inline
Definition at line 137 of file Statistic.h.
operator uint64_t()
llvm::NoopStatistic::operator uint64_t () const inline
Definition at line 140 of file Statistic.h.
operator++() [1/2]
const NoopStatistic & llvm::NoopStatistic::operator++ () inline
Definition at line 144 of file Statistic.h.
References NoopStatistic().
operator++() [2/2]
uint64_t llvm::NoopStatistic::operator++ (int) inline
Definition at line 146 of file Statistic.h.
operator+=()
const NoopStatistic & llvm::NoopStatistic::operator+= (const uint64_t & V) inline
Definition at line 152 of file Statistic.h.
References NoopStatistic().
operator--() [1/2]
const NoopStatistic & llvm::NoopStatistic::operator-- () inline
Definition at line 148 of file Statistic.h.
References NoopStatistic().
operator--() [2/2]
uint64_t llvm::NoopStatistic::operator-- (int) inline
Definition at line 150 of file Statistic.h.
operator-=()
const NoopStatistic & llvm::NoopStatistic::operator-= (const uint64_t & V) inline
Definition at line 154 of file Statistic.h.
References NoopStatistic().
operator=()
const NoopStatistic & llvm::NoopStatistic::operator= (uint64_t Val) inline
Definition at line 142 of file Statistic.h.
References NoopStatistic().
updateMax()
void llvm::NoopStatistic::updateMax (uint64_t V) inline
Definition at line 156 of file Statistic.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/Statistic.h