LLVM: llvm::GCNSubtarget Class Reference
llvm::GCNSubtarget Class Reference final
#include "Target/AMDGPU/GCNSubtarget.h"
Public Types
enum class TrapHandlerAbi { NONE = 0x00 , AMDHSA = 0x01 }
enum class TrapID { LLVMAMDHSATrap = 0x02 , LLVMAMDHSADebugTrap = 0x03 }
Public Types inherited from llvm::AMDGPUSubtarget
enum Generation {
INVALID = 0 , R600 = 1 , R700 = 2 , EVERGREEN = 3 ,
NORTHERN_ISLANDS = 4 , SOUTHERN_ISLANDS = 5 , SEA_ISLANDS = 6 , VOLCANIC_ISLANDS = 7 ,
GFX9 = 8 , GFX10 = 9 , GFX11 = 10 , GFX12 = 11
}
Public Member Functions
GCNSubtarget (const Triple &TT, StringRef GPU, StringRef FS, const GCNTargetMachine &TM)
~GCNSubtarget () override
GCNSubtarget & initializeSubtargetDependencies (const Triple &TT, StringRef GPU, StringRef FS)
void checkSubtargetFeatures (const Function &F) const
Diagnose inconsistent subtarget features before attempting to codegen function F.
const SIInstrInfo * getInstrInfo () const override
const SIFrameLowering * getFrameLowering () const override
const SITargetLowering * getTargetLowering () const override
const SIRegisterInfo * getRegisterInfo () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
const CallLowering * getCallLowering () const override
const InlineAsmLowering * getInlineAsmLowering () const override
InstructionSelector * getInstructionSelector () const override
const LegalizerInfo * getLegalizerInfo () const override
const AMDGPURegisterBankInfo * getRegBankInfo () const override
const AMDGPU::IsaInfo::AMDGPUTargetID & getTargetID () const
const InstrItineraryData * getInstrItineraryData () const override
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Generation getGeneration () const
bool isGFX11Plus () const
unsigned getMaxWaveScratchSize () const
unsigned getKnownHighZeroBitsForFrameIndex () const
Return the number of high bits known to be zero for a frame index.
int getLDSBankCount () const
unsigned getMaxPrivateElementSize (bool ForBufferRSrc=false) const
unsigned getConstantBusLimit (unsigned Opcode) const
bool zeroesHigh16BitsOfDest (unsigned Opcode) const
Returns if the result of this instruction with a 16-bit result returned in a 32-bit register implicitly zeroes the high 16-bits, rather than preserve the original value.
bool supportsWGP () const
bool hasIntClamp () const
bool hasFP64 () const
bool hasMIMG_R128 () const
bool hasHWFP64 () const
bool hasHalfRate64Ops () const
bool hasFullRate64Ops () const
bool hasAddr64 () const
bool hasFlat () const
bool hasOnlyRevVALUShifts () const
bool hasFractBug () const
bool hasMed3_16 () const
bool hasMin3Max3_16 () const
bool hasFmaMixInsts () const
bool hasFmaMixBF16Insts () const
bool hasFMA () const
bool hasSwap () const
bool hasScalarPackInsts () const
bool hasScalarMulHiInsts () const
bool hasScalarSubwordLoads () const
TrapHandlerAbi getTrapHandlerAbi () const
bool supportsGetDoorbellID () const
bool hasUsableDSOffset () const
True if the offset field of DS instructions works as expected.
bool unsafeDSOffsetFoldingEnabled () const
bool hasUsableDivScaleConditionOutput () const
Condition output from div_scale is usable.
bool hasReadVCCZBug () const
Extra wait hazard is needed in some cases before s_cbranch_vccnz/s_cbranch_vccz.
bool partialVCCWritesUpdateVCCZ () const
Writes to VCC_LO/VCC_HI update the VCCZ flag.
bool hasSMRDReadVALUDefHazard () const
A read of an SGPR by SMRD instruction requires 4 wait states when the SGPR was written by a VALU instruction.
bool hasVMEMReadSGPRVALUDefHazard () const
A read of an SGPR by a VMEM instruction requires 5 wait states when the SGPR was written by a VALU Instruction.
bool hasRFEHazards () const
unsigned getSetRegWaitStates () const
Number of hazard wait states for s_setreg_b32/s_setreg_imm32_b32.
bool dumpCode () const
unsigned getMaxLocalMemSizeWithWaveCount (unsigned WaveCount, const Function &) const
Return the amount of LDS that can be used that will not restrict the occupancy lower than WaveCount.
bool supportsMinMaxDenormModes () const
bool hasDenormModeInst () const
bool useFlatForGlobal () const
bool useDS128 () const
bool hasDS96AndDS128 () const
bool haveRoundOpsF64 () const
Have v_trunc_f64, v_ceil_f64, v_rndne_f64.
bool privateMemoryResourceIsRangeChecked () const
bool usePRTStrictNull () const
bool hasAutoWaitcntBeforeBarrier () const
bool supportsBackOffBarrier () const
bool hasUnalignedBufferAccess () const
bool hasUnalignedBufferAccessEnabled () const
bool hasUnalignedDSAccess () const
bool hasUnalignedDSAccessEnabled () const
bool hasUnalignedScratchAccess () const
bool hasUnalignedScratchAccessEnabled () const
bool hasUnalignedAccessMode () const
bool hasRelaxedBufferOOBMode () const
bool hasApertureRegs () const
bool isTrapHandlerEnabled () const
bool isXNACKEnabled () const
bool isTgSplitEnabled () const
bool isCuModeEnabled () const
bool isPreciseMemoryEnabled () const
bool hasFlatAddressSpace () const
bool hasFlatScrRegister () const
bool hasFlatInstOffsets () const
bool hasFlatGlobalInsts () const
bool hasFlatScratchInsts () const
bool hasFlatScratchSTMode () const
bool hasFlatScratchSVSMode () const
bool hasScalarFlatScratchInsts () const
bool enableFlatScratch () const
bool hasGlobalAddTidInsts () const
bool hasAtomicCSub () const
bool hasMTBUFInsts () const
bool hasFormattedMUBUFInsts () const
bool hasExportInsts () const
bool hasVINTERPEncoding () const
bool hasLdsAtomicAddF64 () const
bool hasMultiDwordFlatScratchAddressing () const
bool hasFlatSegmentOffsetBug () const
bool hasFlatLgkmVMemCountInOrder () const
bool hasD16LoadStore () const
bool d16PreservesUnusedBits () const
bool hasD16Images () const
bool ldsRequiresM0Init () const
Return if most LDS instructions have an m0 use that require m0 to be initialized.
bool hasGWSAutoReplay () const
bool hasGWSSemaReleaseAll () const
bool hasAddNoCarry () const
bool hasScalarAddSub64 () const
bool hasScalarSMulU64 () const
bool hasUnpackedD16VMem () const
bool isMesaGfxShader (const Function &F) const
bool hasMad64_32 () const
bool hasSDWAOmod () const
bool hasSDWAScalar () const
bool hasSDWASdst () const
bool hasSDWAMac () const
bool hasSDWAOutModsVOPC () const
bool hasDLInsts () const
bool hasFmacF64Inst () const
bool hasDot1Insts () const
bool hasDot2Insts () const
bool hasDot3Insts () const
bool hasDot4Insts () const
bool hasDot5Insts () const
bool hasDot6Insts () const
bool hasDot7Insts () const
bool hasDot8Insts () const
bool hasDot9Insts () const
bool hasDot10Insts () const
bool hasDot11Insts () const
bool hasDot12Insts () const
bool hasDot13Insts () const
bool hasMAIInsts () const
bool hasFP8Insts () const
bool hasFP8ConversionInsts () const
bool hasMcastLoadInsts () const
bool hasCubeInsts () const
bool hasLerpInst () const
bool hasSadInsts () const
bool hasQsadInsts () const
bool hasCvtNormInsts () const
bool hasCvtPkNormVOP2Insts () const
bool hasCvtPkNormVOP3Insts () const
bool hasFP8E5M3Insts () const
bool hasPkFmacF16Inst () const
bool hasAtomicFMinFMaxF32GlobalInsts () const
bool hasAtomicFMinFMaxF64GlobalInsts () const
bool hasAtomicFMinFMaxF32FlatInsts () const
bool hasAtomicFMinFMaxF64FlatInsts () const
bool hasAtomicDsPkAdd16Insts () const
bool hasAtomicFlatPkAdd16Insts () const
bool hasAtomicFaddInsts () const
bool hasAtomicFaddRtnInsts () const
bool hasAtomicFaddNoRtnInsts () const
bool hasAtomicBufferGlobalPkAddF16NoRtnInsts () const
bool hasAtomicBufferGlobalPkAddF16Insts () const
bool hasAtomicGlobalPkAddBF16Inst () const
bool hasAtomicBufferPkAddBF16Inst () const
bool hasFlatAtomicFaddF32Inst () const
bool hasFlatBufferGlobalAtomicFaddF64Inst () const
bool hasMemoryAtomicFaddF32DenormalSupport () const
bool supportsAgentScopeFineGrainedRemoteMemoryAtomics () const
bool hasEmulatedSystemScopeAtomics () const
bool hasDefaultComponentZero () const
bool hasDefaultComponentBroadcast () const
bool hasNoSdstCMPX () const
bool hasVscnt () const
bool hasGetWaveIdInst () const
bool hasSMemTimeInst () const
bool hasShaderCyclesRegister () const
bool hasShaderCyclesHiLoRegisters () const
bool hasVOP3Literal () const
bool hasNoDataDepHazard () const
bool vmemWriteNeedsExpWaitcnt () const
bool hasInstPrefetch () const
bool hasPrefetch () const
bool hasVmemPrefInsts () const
bool hasSafeSmemPrefetch () const
bool hasSafeCUPrefetch () const
bool hasSCmpK () const
Align getStackAlignment () const
bool enableMachineScheduler () const override
bool useAA () const override
bool enableSubRegLiveness () const override
void setScalarizeGlobalBehavior (bool b)
bool getScalarizeGlobalBehavior () const
bool enableEarlyIfConversion () const override
void overrideSchedPolicy (MachineSchedPolicy &Policy, const SchedRegion &Region) const override
void overridePostRASchedPolicy (MachineSchedPolicy &Policy, const SchedRegion &Region) const override
void mirFileLoaded (MachineFunction &MF) const override
unsigned getMaxNumUserSGPRs () const
bool hasSMemRealTime () const
bool hasMovrel () const
bool hasVGPRIndexMode () const
bool useVGPRIndexMode () const
bool hasScalarCompareEq64 () const
bool hasScalarDwordx3Loads () const
bool hasScalarStores () const
bool hasScalarAtomics () const
bool hasLDSFPAtomicAddF32 () const
bool hasLDSFPAtomicAddF64 () const
bool hasPermLaneX16 () const
bool hasPermLane64 () const
bool hasDPP () const
bool hasDPPBroadcasts () const
bool hasDPPWavefrontShifts () const
bool hasDPP8 () const
bool hasDPALU_DPP () const
bool hasDPPSrc1SGPR () const
bool hasPackedFP32Ops () const
bool hasPkMovB32 () const
bool hasFmaakFmamkF32Insts () const
bool hasFmaakFmamkF64Insts () const
bool hasImageInsts () const
bool hasExtendedImageInsts () const
bool hasR128A16 () const
bool hasA16 () const
bool hasG16 () const
bool hasOffset3fBug () const
bool hasImageStoreD16Bug () const
bool hasImageGather4D16Bug () const
bool hasMADIntraFwdBug () const
bool hasMSAALoadDstSelBug () const
bool hasPrivEnabledTrap2NopBug () const
bool hasNSAEncoding () const
bool hasNonNSAEncoding () const
bool hasPartialNSAEncoding () const
unsigned getNSAMaxSize (bool HasSampler=false) const
bool hasGFX10_AEncoding () const
bool hasGFX10_BEncoding () const
bool hasGFX10_3Insts () const
bool hasMadF16 () const
bool hasMovB64 () const
bool hasLshlAddU64Inst () const
bool hasScaleOffset () const
bool hasFlatGVSMode () const
bool hasSignedGVSOffset () const
bool enableSIScheduler () const
bool loadStoreOptEnabled () const
bool hasSGPRInitBug () const
bool hasUserSGPRInit16Bug () const
bool hasNegativeScratchOffsetBug () const
bool hasNegativeUnalignedScratchOffsetBug () const
bool hasMFMAInlineLiteralBug () const
bool has12DWordStoreHazard () const
bool hasDwordx3LoadStores () const
bool hasReadM0MovRelInterpHazard () const
bool hasReadM0SendMsgHazard () const
bool hasReadM0LdsDmaHazard () const
bool hasReadM0LdsDirectHazard () const
bool hasVcmpxPermlaneHazard () const
bool hasVMEMtoScalarWriteHazard () const
bool hasSMEMtoVectorWriteHazard () const
bool hasLDSMisalignedBug () const
bool hasInstFwdPrefetchBug () const
bool hasVcmpxExecWARHazard () const
bool hasLdsBranchVmemWARHazard () const
bool hasShift64HighRegBug () const
bool hasTransForwardingHazard () const
bool hasDstSelForwardingHazard () const
bool hasDOTOpSelHazard () const
bool hasVDecCoExecHazard () const
bool hasNSAtoVMEMBug () const
bool hasNSAClauseBug () const
bool hasHardClauses () const
bool hasGFX90AInsts () const
bool hasFPAtomicToDenormModeHazard () const
bool hasVOP3DPP () const
bool hasLdsDirect () const
bool hasLdsWaitVMSRC () const
bool hasVALUPartialForwardingHazard () const
bool hasVALUTransUseHazard () const
bool hasCvtScaleForwardingHazard () const
bool requiresCodeObjectV6 () const
bool useVGPRBlockOpsForCSR () const
bool hasGloballyAddressableScratch () const
bool hasVALUMaskWriteHazard () const
bool hasVALUReadSGPRHazard () const
bool setRegModeNeedsVNOPs () const
bool needsAlignedVGPRs () const
Return if operations acting on VGPR tuples require even alignment.
bool hasSPackHL () const
Return true if the target has the S_PACK_HL_B32_B16 instruction.
bool hasCompressedExport () const
Return true if the target's EXP instruction has the COMPR flag, which affects the meaning of the EN (enable) bits.
bool hasNullExportTarget () const
Return true if the target's EXP instruction supports the NULL export target.
bool has1_5xVGPRs () const
bool hasVOPDInsts () const
bool hasFlatScratchSVSSwizzleBug () const
bool hasDelayAlu () const
Return true if the target has the S_DELAY_ALU instruction.
bool hasPackedTID () const
bool hasGFX940Insts () const
bool hasGFX950Insts () const
bool hasLDSLoadB96_B128 () const
Returns true if the target supports global_load_lds_dwordx3/global_load_lds_dwordx4 or buffer_load_dwordx3/buffer_load_dwordx4 with the lds bit.
bool hasVMemToLDSLoad () const
bool hasSALUFloatInsts () const
bool hasPseudoScalarTrans () const
bool hasRestrictedSOffset () const
bool hasRequiredExportPriority () const
bool hasVmemWriteVgprInOrder () const
bool hasExtendedWaitCounts () const
bool hasNoF16PseudoScalarTransInlineConstants () const
bool hasXF32Insts () const
bool hasPKF32InstsReplicatingLower32BitsOfScalarInput () const
bool hasBitOp3Insts () const
bool hasPermlane16Swap () const
bool hasPermlane32Swap () const
bool hasAshrPkInsts () const
bool hasMinimum3Maximum3F32 () const
bool hasMinimum3Maximum3F16 () const
bool hasMin3Max3PKF16 () const
bool hasTanhInsts () const
bool hasTensorCvtLutInsts () const
bool hasAddPC64Inst () const
bool has1024AddressableVGPRs () const
bool hasSetregVGPRMSBFixup () const
bool hasMinimum3Maximum3PKF16 () const
bool hasTransposeLoadF4F6Insts () const
bool hasExpertSchedulingMode () const
bool hasWaitXCnt () const
bool has64BitLiterals () const
bool hasPointSampleAccel () const
bool hasLdsBarrierArriveAtomic () const
unsigned maxHardClauseLength () const
bool hasPrngInst () const
bool hasBVHDualAndBVH8Insts () const
unsigned getOccupancyWithNumSGPRs (unsigned SGPRs) const
Return the maximum number of waves per SIMD for kernels using SGPRs SGPRs.
unsigned getOccupancyWithNumVGPRs (unsigned VGPRs, unsigned DynamicVGPRBlockSize) const
Return the maximum number of waves per SIMD for kernels using VGPRs VGPRs.
std::pair< unsigned, unsigned > computeOccupancy (const Function &F, unsigned LDSSize=0, unsigned NumSGPRs=0, unsigned NumVGPRs=0) const
Subtarget's minimum/maximum occupancy, in number of waves per EU, that can be achieved when the only function running on a CU is F, each workgroup uses LDSSize bytes of LDS, and each wave uses NumSGPRs SGPRs and NumVGPRs VGPRs.
bool flatScratchIsPointer () const
bool flatScratchIsArchitected () const
bool hasArchitectedSGPRs () const
bool hasGDS () const
bool hasGWS () const
bool hasMergedShaders () const
bool hasLegacyGeometry () const
bool hasKernargPreload () const
bool hasSplitBarriers () const
bool hasCvtFP8VOP1Bug () const
bool hasAtomicCSubNoRtnInsts () const
bool hasDX10ClampMode () const
bool hasIEEEMode () const
bool hasIEEEMinimumMaximumInsts () const
bool hasRrWGMode () const
bool hasSignedScratchOffsets () const
bool hasGFX1250Insts () const
bool hasVOPD3 () const
bool hasAddSubU64Insts () const
bool hasMadU32Inst () const
bool hasVectorMulU64 () const
bool hasMadU64U32NoCarry () const
bool hasIntMinMax64 () const
bool hasAddMinMaxInsts () const
bool hasPkAddMinMaxInsts () const
bool hasPkMinMax3Insts () const
bool hasSGetShaderCyclesInst () const
bool hasSetPrioIncWgInst () const
bool hasSWakeupBarrier () const
bool hasGetPCZeroExtension () const
bool needsKernArgPreloadProlog () const
bool hasCondSubInsts () const
bool hasSubClampInsts () const
unsigned getSGPRAllocGranule () const
unsigned getSGPREncodingGranule () const
unsigned getTotalNumSGPRs () const
unsigned getAddressableNumSGPRs () const
unsigned getMinNumSGPRs (unsigned WavesPerEU) const
unsigned getMaxNumSGPRs (unsigned WavesPerEU, bool Addressable) const
unsigned getBaseReservedNumSGPRs (const bool HasFlatScratch) const
unsigned getReservedNumSGPRs (const MachineFunction &MF) const
unsigned getReservedNumSGPRs (const Function &F) const
unsigned getMaxNumPreloadedSGPRs () const
unsigned getBaseMaxNumSGPRs (const Function &F, std::pair< unsigned, unsigned > WavesPerEU, unsigned PreloadedSGPRs, unsigned ReservedNumSGPRs) const
unsigned getMaxNumSGPRs (const MachineFunction &MF) const
unsigned getMaxNumSGPRs (const Function &F) const
unsigned getVGPRAllocGranule (unsigned DynamicVGPRBlockSize) const
unsigned getVGPREncodingGranule () const
unsigned getTotalNumVGPRs () const
unsigned getAddressableNumArchVGPRs () const
unsigned getAddressableNumVGPRs (unsigned DynamicVGPRBlockSize) const
unsigned getMinNumVGPRs (unsigned WavesPerEU, unsigned DynamicVGPRBlockSize) const
unsigned getMaxNumVGPRs (unsigned WavesPerEU, unsigned DynamicVGPRBlockSize) const
unsigned getBaseMaxNumVGPRs (const Function &F, std::pair< unsigned, unsigned > NumVGPRBounds) const
unsigned getMaxNumVGPRs (const Function &F) const
unsigned getMaxNumAGPRs (const Function &F) const
std::pair< unsigned, unsigned > getMaxNumVectorRegs (const Function &F) const
Return a pair of maximum numbers of VGPRs and AGPRs that meet the number of waves per execution unit required for the function MF.
unsigned getMaxNumVGPRs (const MachineFunction &MF) const
bool supportsWave32 () const
bool supportsWave64 () const
bool isWave32 () const
bool isWave64 () const
bool isWaveSizeKnown () const
Returns if the wavesize of this subtarget is known reliable.
const TargetRegisterClass * getBoolRC () const
unsigned getMaxWorkGroupsPerCU (unsigned FlatWorkGroupSize) const override
unsigned getMinFlatWorkGroupSize () const override
unsigned getMaxFlatWorkGroupSize () const override
unsigned getWavesPerEUForWorkGroup (unsigned FlatWorkGroupSize) const override
unsigned getMinWavesPerEU () const override
void adjustSchedDependency (SUnit *Def, int DefOpIdx, SUnit *Use, int UseOpIdx, SDep &Dep, const TargetSchedModel *SchedModel) const override
bool shouldClusterStores () const
unsigned getNSAThreshold (const MachineFunction &MF) const
bool requiresNopBeforeDeallocVGPRs () const
bool requiresWaitIdleBeforeGetReg () const
bool isDynamicVGPREnabled () const
unsigned getDynamicVGPRBlockSize () const
bool requiresDisjointEarlyClobberAndUndef () const override
bool hasDsAtomicAsyncBarrierArriveB64PipeBug () const
bool hasScratchBaseForwardingHazard () const
bool hasFlatScratchHiInB64InstHazard () const
bool hasClusters () const
bool requiresWaitXCntForSingleAccessInstructions () const
unsigned getSNopBits () const
bool has45BitNumRecordsBufferResource () const
bool requiresWaitsBeforeSystemScopeStores () const
bool supportsBPermute () const
bool supportsWaveWideBPermute () const
unsigned getMaxWavesPerEU () const
Public Member Functions inherited from llvm::AMDGPUSubtarget
AMDGPUSubtarget (Triple TT)
std::pair< unsigned, unsigned > getDefaultFlatWorkGroupSize (CallingConv::ID CC) const
std::pair< unsigned, unsigned > getFlatWorkGroupSizes (const Function &F) const
std::optional< unsigned > getReqdWorkGroupSize (const Function &F, unsigned Dim) const
bool hasWavefrontsEvenlySplittingXDim (const Function &F, bool REquiresUniformYZ=false) const
std::pair< unsigned, unsigned > getWavesPerEU (const Function &F) const
std::pair< unsigned, unsigned > getWavesPerEU (const Function &F, std::pair< unsigned, unsigned > FlatWorkGroupSizes) const
Overload which uses the specified values for the flat work group sizes, rather than querying the function itself.
std::pair< unsigned, unsigned > getWavesPerEU (std::pair< unsigned, unsigned > FlatWorkGroupSizes, unsigned LDSBytes, const Function &F) const
Overload which uses the specified values for the flat workgroup sizes and LDS space rather than querying the function itself.
std::pair< unsigned, unsigned > getEffectiveWavesPerEU (std::pair< unsigned, unsigned > RequestedWavesPerEU, std::pair< unsigned, unsigned > FlatWorkGroupSizes, unsigned LDSBytes) const
Returns the target minimum/maximum number of waves per EU.
unsigned getMaxLocalMemSizeWithWaveCount (unsigned WaveCount, const Function &) const
Return the amount of LDS that can be used that will not restrict the occupancy lower than WaveCount.
std::pair< unsigned, unsigned > getOccupancyWithWorkGroupSizes (uint32_t LDSBytes, const Function &F) const
Subtarget's minimum/maximum occupancy, in number of waves per EU, that can be achieved when the only function running on a CU is F and each workgroup running the function requires LDSBytes bytes of LDS space.
std::pair< unsigned, unsigned > getOccupancyWithWorkGroupSizes (uint32_t LDSBytes, std::pair< unsigned, unsigned > FlatWorkGroupSizes) const
Overload which uses the specified values for the flat work group sizes, rather than querying the function itself.
std::pair< unsigned, unsigned > getOccupancyWithWorkGroupSizes (const MachineFunction &MF) const
Subtarget's minimum/maximum occupancy, in number of waves per EU, that can be achieved when the only function running on a CU is MF.
bool isAmdHsaOS () const
bool isAmdPalOS () const
bool isMesa3DOS () const
bool isMesaKernel (const Function &F) const
bool isAmdHsaOrMesa (const Function &F) const
bool isGCN () const
bool isGCN3Encoding () const
bool has16BitInsts () const
bool hasTrue16BitInsts () const
Return true if the subtarget supports True16 instructions.
bool useRealTrue16Insts () const
Return true if real (non-fake) variants of True16 instructions using 16-bit registers should be code-generated.
bool hasD16Writes32BitVgpr () const
bool hasBF16TransInsts () const
bool hasBF16ConversionInsts () const
bool hasBF16PackedInsts () const
bool hasMadMixInsts () const
bool hasFP8ConversionScaleInsts () const
bool hasBF8ConversionScaleInsts () const
bool hasFP4ConversionScaleInsts () const
bool hasFP6BF6ConversionScaleInsts () const
bool hasF16BF16ToFP6BF6ConversionScaleInsts () const
bool hasCvtPkF16F32Inst () const
bool hasF32ToF16BF16ConversionSRInsts () const
bool hasMadMacF32Insts () const
bool hasDsSrc2Insts () const
bool hasSDWA () const
bool hasVOP3PInsts () const
bool hasMulI24 () const
bool hasMulU24 () const
bool hasSMulHi () const
bool hasInv2PiInlineImm () const
bool hasFminFmaxLegacy () const
bool hasTrigReducedRange () const
bool hasFastFMAF32 () const
bool isPromoteAllocaEnabled () const
unsigned getWavefrontSize () const
unsigned getWavefrontSizeLog2 () const
unsigned getLocalMemorySize () const
Return the maximum number of bytes of LDS available for all workgroups running on the same WGP or CU.
unsigned getAddressableLocalMemorySize () const
Return the maximum number of bytes of LDS that can be allocated to a single workgroup.
unsigned getEUsPerCU () const
Number of SIMDs/EUs (execution units) per "CU" ("compute unit"), where the "CU" is the unit onto which workgroups are mapped.
Align getAlignmentForImplicitArgPtr () const
unsigned getExplicitKernelArgOffset () const
Returns the offset in bytes from the start of the input buffer of the first explicit kernel argument.
unsigned getMaxWavesPerEU () const
unsigned getMaxWorkitemID (const Function &Kernel, unsigned Dimension) const
Return the maximum workitem ID value in the function, for the given (0, 1, 2) dimension.
SmallVector< unsigned > getMaxNumWorkGroups (const Function &F) const
Return the number of work groups for the function.
bool isSingleLaneExecution (const Function &Kernel) const
Return true if only a single workitem can be active in a wave.
bool makeLIDRangeMetadata (Instruction *I) const
Creates value range metadata on an workitemid.* intrinsic call or load.
unsigned getImplicitArgNumBytes (const Function &F) const
uint64_t getExplicitKernArgSize (const Function &F, Align &MaxAlign) const
unsigned getKernArgSegmentSize (const Function &F, Align &MaxAlign) const
AMDGPUDwarfFlavour getAMDGPUDwarfFlavour () const
virtual ~AMDGPUSubtarget ()=default
Static Public Member Functions
static bool hasHalfRate64Ops (const TargetSubtargetInfo &STI)
Static Public Member Functions inherited from llvm::AMDGPUSubtarget
static const AMDGPUSubtarget & get (const MachineFunction &MF)
static const AMDGPUSubtarget & get (const TargetMachine &TM, const Function &F)
Protected Attributes
AMDGPU::IsaInfo::AMDGPUTargetID TargetID
unsigned Gen = INVALID
InstrItineraryData InstrItins
int LDSBankCount = 0
unsigned MaxPrivateElementSize = 0
bool FastDenormalF32 = false
bool HalfRate64Ops = false
bool FullRate64Ops = false
bool FlatForGlobal = false
bool AutoWaitcntBeforeBarrier = false
bool BackOffBarrier = false
bool UnalignedScratchAccess = false
bool UnalignedAccessMode = false
bool RelaxedBufferOOBMode = false
bool HasApertureRegs = false
bool SupportsXNACK = false
bool KernargPreload = false
bool EnableXNACK = false
bool EnableTgSplit = false
bool EnableCuMode = false
bool TrapHandler = false
bool EnablePreciseMemory = false
bool EnableLoadStoreOpt = false
bool EnableUnsafeDSOffsetFolding = false
bool EnableSIScheduler = false
bool EnableDS128 = false
bool EnablePRTStrictNull = false
bool DumpCode = false
bool AssemblerPermissiveWavesize = false
bool FP64 = false
bool FMA = false
bool MIMG_R128 = false
bool CIInsts = false
bool GFX8Insts = false
bool GFX9Insts = false
bool GFX90AInsts = false
bool GFX940Insts = false
bool GFX950Insts = false
bool GFX10Insts = false
bool GFX11Insts = false
bool GFX12Insts = false
bool GFX1250Insts = false
bool GFX10_3Insts = false
bool GFX7GFX8GFX9Insts = false
bool SGPRInitBug = false
bool UserSGPRInit16Bug = false
bool NegativeScratchOffsetBug = false
bool NegativeUnalignedScratchOffsetBug = false
bool HasSMemRealTime = false
bool HasIntClamp = false
bool HasFmaMixInsts = false
bool HasFmaMixBF16Insts = false
bool HasMovrel = false
bool HasVGPRIndexMode = false
bool HasScalarDwordx3Loads = false
bool HasScalarStores = false
bool HasScalarAtomics = false
bool HasSDWAOmod = false
bool HasSDWAScalar = false
bool HasSDWASdst = false
bool HasSDWAMac = false
bool HasSDWAOutModsVOPC = false
bool HasDPP = false
bool HasDPP8 = false
bool HasDPALU_DPP = false
bool HasDPPSrc1SGPR = false
bool HasPackedFP32Ops = false
bool HasImageInsts = false
bool HasExtendedImageInsts = false
bool HasR128A16 = false
bool HasA16 = false
bool HasG16 = false
bool HasNSAEncoding = false
bool HasPartialNSAEncoding = false
bool GFX10_AEncoding = false
bool GFX10_BEncoding = false
bool HasDLInsts = false
bool HasFmacF64Inst = false
bool HasDot1Insts = false
bool HasDot2Insts = false
bool HasDot3Insts = false
bool HasDot4Insts = false
bool HasDot5Insts = false
bool HasDot6Insts = false
bool HasDot7Insts = false
bool HasDot8Insts = false
bool HasDot9Insts = false
bool HasDot10Insts = false
bool HasDot11Insts = false
bool HasDot12Insts = false
bool HasDot13Insts = false
bool HasMAIInsts = false
bool HasFP8Insts = false
bool HasFP8ConversionInsts = false
bool HasMcastLoadInsts = false
bool HasCubeInsts = false
bool HasLerpInst = false
bool HasSadInsts = false
bool HasQsadInsts = false
bool HasCvtNormInsts = false
bool HasCvtPkNormVOP2Insts = false
bool HasCvtPkNormVOP3Insts = false
bool HasFP8E5M3Insts = false
bool HasCvtFP8Vop1Bug = false
bool HasPkFmacF16Inst = false
bool HasAtomicFMinFMaxF32GlobalInsts = false
bool HasAtomicFMinFMaxF64GlobalInsts = false
bool HasAtomicFMinFMaxF32FlatInsts = false
bool HasAtomicFMinFMaxF64FlatInsts = false
bool HasAtomicDsPkAdd16Insts = false
bool HasAtomicFlatPkAdd16Insts = false
bool HasAtomicFaddRtnInsts = false
bool HasAtomicFaddNoRtnInsts = false
bool HasMemoryAtomicFaddF32DenormalSupport = false
bool HasAtomicBufferGlobalPkAddF16NoRtnInsts = false
bool HasAtomicBufferGlobalPkAddF16Insts = false
bool HasAtomicCSubNoRtnInsts = false
bool HasAtomicGlobalPkAddBF16Inst = false
bool HasAtomicBufferPkAddBF16Inst = false
bool HasFlatAtomicFaddF32Inst = false
bool HasFlatBufferGlobalAtomicFaddF64Inst = false
bool HasDefaultComponentZero = false
bool HasAgentScopeFineGrainedRemoteMemoryAtomics = false
bool HasEmulatedSystemScopeAtomics = false
bool HasDefaultComponentBroadcast = false
bool HasXF32Insts = false
unsigned MaxHardClauseLength = 0
The maximum number of instructions that may be placed within an S_CLAUSE, which is one greater than the maximum argument to S_CLAUSE.
bool SupportsSRAMECC = false
bool DynamicVGPR = false
bool DynamicVGPRBlockSize32 = false
bool HasVMemToLDSLoad = false
bool RequiresAlignVGPR = false
bool EnableSRAMECC = false
bool HasNoSdstCMPX = false
bool HasVscnt = false
bool HasWaitXcnt = false
bool HasGetWaveIdInst = false
bool HasSMemTimeInst = false
bool HasShaderCyclesRegister = false
bool HasShaderCyclesHiLoRegisters = false
bool HasVOP3Literal = false
bool HasNoDataDepHazard = false
bool FlatAddressSpace = false
bool FlatInstOffsets = false
bool FlatGlobalInsts = false
bool FlatScratchInsts = false
bool FlatGVSMode = false
bool ScalarFlatScratchInsts = false
bool HasArchitectedFlatScratch = false
bool EnableFlatScratch = false
bool HasArchitectedSGPRs = false
bool HasGDS = false
bool HasGWS = false
bool AddNoCarryInsts = false
bool HasUnpackedD16VMem = false
bool LDSMisalignedBug = false
bool HasMFMAInlineLiteralBug = false
bool UnalignedBufferAccess = false
bool UnalignedDSAccess = false
bool HasPackedTID = false
bool ScalarizeGlobal = false
bool HasSALUFloatInsts = false
bool HasPseudoScalarTrans = false
bool HasRestrictedSOffset = false
bool Has64BitLiterals = false
bool Has1024AddressableVGPRs = false
bool HasSetregVGPRMSBFixup = false
bool HasBitOp3Insts = false
bool HasTanhInsts = false
bool HasTensorCvtLutInsts = false
bool HasTransposeLoadF4F6Insts = false
bool HasPrngInst = false
bool HasBVHDualAndBVH8Insts = false
bool HasPermlane16Swap = false
bool HasPermlane32Swap = false
bool HasVcmpxPermlaneHazard = false
bool HasVMEMtoScalarWriteHazard = false
bool HasSMEMtoVectorWriteHazard = false
bool HasInstFwdPrefetchBug = false
bool HasVmemPrefInsts = false
bool HasSafeSmemPrefetch = false
bool HasSafeCUPrefetch = false
bool HasVcmpxExecWARHazard = false
bool HasLdsBranchVmemWARHazard = false
bool HasNSAtoVMEMBug = false
bool HasNSAClauseBug = false
bool HasOffset3fBug = false
bool HasFlatSegmentOffsetBug = false
bool HasImageStoreD16Bug = false
bool HasImageGather4D16Bug = false
bool HasMSAALoadDstSelBug = false
bool HasPrivEnabledTrap2NopBug = false
bool Has1_5xVGPRs = false
bool HasMADIntraFwdBug = false
bool HasVOPDInsts = false
bool HasVALUTransUseHazard = false
bool HasRequiredExportPriority = false
bool HasVmemWriteVgprInOrder = false
bool HasAshrPkInsts = false
bool HasIEEEMinimumMaximumInsts = false
bool HasMinimum3Maximum3F32 = false
bool HasMinimum3Maximum3F16 = false
bool HasMin3Max3PKF16 = false
bool HasMinimum3Maximum3PKF16 = false
bool HasLshlAddU64Inst = false
bool HasAddSubU64Insts = false
bool HasMadU32Inst = false
bool HasAddMinMaxInsts = false
bool HasPkAddMinMaxInsts = false
bool HasPointSampleAccel = false
bool HasLdsBarrierArriveAtomic = false
bool HasSetPrioIncWgInst = false
bool HasSWakeupBarrier = false
bool RequiresCOV6 = false
bool UseBlockVGPROpsForCSR = false
bool HasGloballyAddressableScratch = false
bool Has45BitNumRecordsBufferResource = false
bool HasClusters = false
bool RequiresWaitsBeforeSystemScopeStores = false
bool FeatureDisable = false
Protected Attributes inherited from llvm::AMDGPUSubtarget
bool GCN3Encoding = false
bool Has16BitInsts = false
bool HasTrue16BitInsts = false
bool HasFP8ConversionScaleInsts = false
bool HasBF8ConversionScaleInsts = false
bool HasFP4ConversionScaleInsts = false
bool HasFP6BF6ConversionScaleInsts = false
bool HasF16BF16ToFP6BF6ConversionScaleInsts = false
bool HasCvtPkF16F32Inst = false
bool HasF32ToF16BF16ConversionSRInsts = false
bool EnableRealTrue16Insts = false
bool EnableD16Writes32BitVgpr = false
bool HasBF16TransInsts = false
bool HasBF16ConversionInsts = false
bool HasBF16PackedInsts = false
bool HasMadMixInsts = false
bool HasMadMacF32Insts = false
bool HasDsSrc2Insts = false
bool HasSDWA = false
bool HasVOP3PInsts = false
bool HasMulI24 = true
bool HasMulU24 = true
bool HasSMulHi = false
bool HasInv2PiInlineImm = false
bool HasFminFmaxLegacy = true
bool EnablePromoteAlloca = false
bool HasTrigReducedRange = false
bool FastFMAF32 = false
unsigned EUsPerCU = 4
unsigned MaxWavesPerEU = 10
unsigned LocalMemorySize = 0
unsigned AddressableLocalMemorySize = 0
char WavefrontSizeLog2 = 0
Detailed Description
Definition at line 33 of file GCNSubtarget.h.
Member Enumeration Documentation
TrapHandlerAbi
enum class llvm::GCNSubtarget::TrapHandlerAbi strong
Enumerator
NONE
AMDHSA
Definition at line 40 of file GCNSubtarget.h.
TrapID
enum class llvm::GCNSubtarget::TrapID strong
Enumerator
LLVMAMDHSATrap
LLVMAMDHSADebugTrap
Definition at line 45 of file GCNSubtarget.h.
Constructor & Destructor Documentation
GCNSubtarget()
GCNSubtarget::GCNSubtarget (const Triple & TT, StringRef GPU, StringRef FS, const GCNTargetMachine & TM)
Definition at line 167 of file GCNSubtarget.cpp.
References llvm::AMDGPUSubtarget::AMDGPUSubtarget(), llvm::AMDGPUSubtarget::EUsPerCU, llvm::AMDGPU::IsaInfo::getEUsPerCU(), llvm::AMDGPU::IsaInfo::getMaxWavesPerEU(), getStackAlignment(), getTargetLowering(), initializeSubtargetDependencies(), InstrItins, llvm::AMDGPUSubtarget::MaxWavesPerEU, and TargetID.
Referenced by initializeSubtargetDependencies(), and ~GCNSubtarget().
~GCNSubtarget()
GCNSubtarget::~GCNSubtarget () override default
References F, and GCNSubtarget().
Member Function Documentation
adjustSchedDependency()
void GCNSubtarget::adjustSchedDependency (SUnit * Def, int DefOpIdx, SUnit * Use, int UseOpIdx, SDep & Dep, const TargetSchedModel * SchedModel) const override
Definition at line 630 of file GCNSubtarget.cpp.
References llvm::SDep::Data, E(), getInstrItineraryData(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::SDep::getKind(), llvm::SDep::getLatency(), llvm::MachineInstr::getParent(), llvm::SDep::getReg(), getRegisterInfo(), I, llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isBundle(), llvm::SDep::setLatency(), and TRI.
checkSubtargetFeatures()
void GCNSubtarget::checkSubtargetFeatures (const Function & F) const
Diagnose inconsistent subtarget features before attempting to codegen function F.
Definition at line 158 of file GCNSubtarget.cpp.
References F.
Referenced by llvm::AMDGPUDAGToDAGISel::runOnMachineFunction(), and llvm::AMDGPUInstructionSelector::setupMF().
computeOccupancy()
std::pair< unsigned, unsigned > GCNSubtarget::computeOccupancy (const Function & F, unsigned LDSSize = 0, unsigned NumSGPRs = 0, unsigned NumVGPRs = 0) const
Subtarget's minimum/maximum occupancy, in number of waves per EU, that can be achieved when the only function running on a CU is F, each workgroup uses LDSSize bytes of LDS, and each wave uses NumSGPRs SGPRs and NumVGPRs VGPRs.
The flat workgroup sizes associated to the function are a range, so this returns a range as well.
Note that occupancy can be affected by the scratch allocation as well, but we do not have enough information to compute it.
Definition at line 440 of file GCNSubtarget.cpp.
References F, llvm::AMDGPU::getDynamicVGPRBlockSize(), getDynamicVGPRBlockSize(), getOccupancyWithNumSGPRs(), getOccupancyWithNumVGPRs(), llvm::AMDGPUSubtarget::getOccupancyWithWorkGroupSizes(), and isDynamicVGPREnabled().
d16PreservesUnusedBits()
bool llvm::GCNSubtarget::d16PreservesUnusedBits () const inline
Definition at line 738 of file GCNSubtarget.h.
References hasD16LoadStore(), and TargetID.
dumpCode()
bool llvm::GCNSubtarget::dumpCode () const inline
Definition at line 549 of file GCNSubtarget.h.
References DumpCode.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction().
enableEarlyIfConversion()
bool llvm::GCNSubtarget::enableEarlyIfConversion () const inline override
Definition at line 1056 of file GCNSubtarget.h.
enableFlatScratch()
bool llvm::GCNSubtarget::enableFlatScratch () const inline
Definition at line 694 of file GCNSubtarget.h.
References EnableFlatScratch, flatScratchIsArchitected(), and hasFlatScratchInsts().
Referenced by getMaxPrivateElementSize().
enableMachineScheduler()
bool llvm::GCNSubtarget::enableMachineScheduler () const inline override
Definition at line 1039 of file GCNSubtarget.h.
enableSIScheduler()
bool llvm::GCNSubtarget::enableSIScheduler () const inline
Definition at line 1212 of file GCNSubtarget.h.
References EnableSIScheduler.
Referenced by overrideSchedPolicy().
enableSubRegLiveness()
bool llvm::GCNSubtarget::enableSubRegLiveness () const inline override
Definition at line 1045 of file GCNSubtarget.h.
flatScratchIsArchitected()
bool llvm::GCNSubtarget::flatScratchIsArchitected () const inline
Returns
true if the flat_scratch register is initialized by the HW. In this case it is readonly.
Definition at line 1517 of file GCNSubtarget.h.
References HasArchitectedFlatScratch.
Referenced by enableFlatScratch().
flatScratchIsPointer()
bool llvm::GCNSubtarget::flatScratchIsPointer () const inline
Returns
true if the flat_scratch register should be initialized with the pointer to the wave's scratch memory rather than a size and offset.
Definition at line 1511 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
getAddressableNumArchVGPRs()
unsigned llvm::GCNSubtarget::getAddressableNumArchVGPRs () const inline
Returns
Addressable number of architectural VGPRs supported by the subtarget.
Definition at line 1709 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getAddressableNumArchVGPRs().
getAddressableNumSGPRs()
unsigned llvm::GCNSubtarget::getAddressableNumSGPRs () const inline
Returns
Addressable number of SGPRs supported by the subtarget.
Definition at line 1635 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getAddressableNumSGPRs().
getAddressableNumVGPRs()
unsigned llvm::GCNSubtarget::getAddressableNumVGPRs (unsigned DynamicVGPRBlockSize) const inline
Returns
Addressable number of VGPRs supported by the subtarget.
Definition at line 1714 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getAddressableNumVGPRs().
getBaseMaxNumSGPRs()
unsigned GCNSubtarget::getBaseMaxNumSGPRs (const Function & F, std::pair< unsigned, unsigned > WavesPerEU, unsigned PreloadedSGPRs, unsigned ReservedNumSGPRs) const
Returns
max num SGPRs. This is the common utility function called by MachineFunction and Function variants of getMaxNumSGPRs.
Definition at line 457 of file GCNSubtarget.cpp.
References F, llvm::AMDGPU::IsaInfo::FIXED_NUM_SGPRS_FOR_INIT_BUG, getMaxNumSGPRs(), getMinNumSGPRs(), and hasSGPRInitBug().
Referenced by getMaxNumSGPRs(), and getMaxNumSGPRs().
getBaseMaxNumVGPRs()
unsigned GCNSubtarget::getBaseMaxNumVGPRs (const Function & F, std::pair< unsigned, unsigned > NumVGPRBounds) const
Returns
max num VGPRs. This is the common utility function called by MachineFunction and Function variants of getMaxNumVGPRs.
Definition at line 541 of file GCNSubtarget.cpp.
References F, and hasGFX90AInsts().
Referenced by getMaxNumVGPRs().
getBaseReservedNumSGPRs()
unsigned GCNSubtarget::getBaseReservedNumSGPRs (const bool HasFlatScratch) const
Returns
Reserved number of SGPRs. This is common utility function called by MachineFunction and Function variants of getReservedNumSGPRs.
Definition at line 410 of file GCNSubtarget.cpp.
References getGeneration(), llvm::AMDGPUSubtarget::GFX10, HasArchitectedFlatScratch, isXNACKEnabled(), llvm::AMDGPUSubtarget::SEA_ISLANDS, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
Referenced by getReservedNumSGPRs(), and getReservedNumSGPRs().
getBoolRC()
const TargetRegisterClass * llvm::GCNSubtarget::getBoolRC () const inline
Definition at line 1788 of file GCNSubtarget.h.
References llvm::SIRegisterInfo::getBoolRC(), and getRegisterInfo().
getCallLowering()
const CallLowering * llvm::GCNSubtarget::getCallLowering () const inline override
Definition at line 343 of file GCNSubtarget.h.
getConstantBusLimit()
unsigned GCNSubtarget::getConstantBusLimit (unsigned Opcode) const
Definition at line 196 of file GCNSubtarget.cpp.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX10.
getDynamicVGPRBlockSize()
unsigned llvm::GCNSubtarget::getDynamicVGPRBlockSize () const inline
Definition at line 1842 of file GCNSubtarget.h.
References DynamicVGPRBlockSize32.
Referenced by computeOccupancy(), and getMaxNumVGPRs().
getFrameLowering()
const SIFrameLowering * llvm::GCNSubtarget::getFrameLowering () const inline override
Definition at line 329 of file GCNSubtarget.h.
getGeneration()
Generation llvm::GCNSubtarget::getGeneration () const inline
Definition at line 373 of file GCNSubtarget.h.
References Gen.
Referenced by createOccupancy(), flatScratchIsPointer(), getBaseReservedNumSGPRs(), getConstantBusLimit(), getMaxWaveScratchSize(), getNSAThreshold(), getOccupancyWithNumSGPRs(), getSetRegWaitStates(), getSNopBits(), has12DWordStoreHazard(), hasAddr64(), hasD16Images(), hasD16LoadStore(), hasDenormModeInst(), hasDPPBroadcasts(), hasDPPWavefrontShifts(), hasDsAtomicAsyncBarrierArriveB64PipeBug(), hasDX10ClampMode(), hasExpertSchedulingMode(), hasExtendedWaitCounts(), hasFlat(), hasFlatLgkmVMemCountInOrder(), hasFlatScratchHiInB64InstHazard(), hasFlatScratchSVSSwizzleBug(), hasFmaakFmamkF32Insts(), hasFPAtomicToDenormModeHazard(), hasFractBug(), hasGWSAutoReplay(), hasIEEEMode(), hasInstPrefetch(), hasLdsDirect(), hasLdsWaitVMSRC(), hasLegacyGeometry(), hasMad64_32(), hasMed3_16(), hasMergedShaders(), hasMin3Max3_16(), hasMultiDwordFlatScratchAddressing(), hasNoF16PseudoScalarTransInlineConstants(), hasNonNSAEncoding(), hasOnlyRevVALUShifts(), hasPermLane64(), hasPermLaneX16(), hasPKF32InstsReplicatingLower32BitsOfScalarInput(), hasReadM0LdsDirectHazard(), hasReadM0LdsDmaHazard(), hasReadM0MovRelInterpHazard(), hasReadM0SendMsgHazard(), hasReadVCCZBug(), hasRFEHazards(), hasRrWGMode(), hasScalarAddSub64(), hasScalarCompareEq64(), hasScalarSMulU64(), hasScalarSubwordLoads(), hasSCmpK(), hasScratchBaseForwardingHazard(), hasSignedScratchOffsets(), hasSMRDReadVALUDefHazard(), hasSplitBarriers(), hasUsableDivScaleConditionOutput(), hasUsableDSOffset(), hasVALUMaskWriteHazard(), hasVALUPartialForwardingHazard(), hasVMEMReadSGPRVALUDefHazard(), hasVOP3DPP(), initializeSubtargetDependencies(), isGFX11Plus(), ldsRequiresM0Init(), partialVCCWritesUpdateVCCZ(), privateMemoryResourceIsRangeChecked(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), setRegModeNeedsVNOPs(), shouldClusterStores(), supportsBPermute(), supportsGetDoorbellID(), supportsMinMaxDenormModes(), supportsWave32(), supportsWaveWideBPermute(), supportsWGP(), vmemWriteNeedsExpWaitcnt(), and zeroesHigh16BitsOfDest().
getInlineAsmLowering()
const InlineAsmLowering * llvm::GCNSubtarget::getInlineAsmLowering () const inline override
Definition at line 347 of file GCNSubtarget.h.
getInstrInfo()
const SIInstrInfo * llvm::GCNSubtarget::getInstrInfo () const inline override
Definition at line 325 of file GCNSubtarget.h.
Referenced by llvm::SITargetLowering::AddMemOpInit(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::bundleInstWithWaitcnt(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::SIProgramInfo::getFunctionCodeSize(), llvm::SITargetLowering::getPrefLoopAlignment(), llvm::SITargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PostISelFolding(), llvm::SITargetLowering::splitKillBlock(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getInstrItineraryData()
const InstrItineraryData * llvm::GCNSubtarget::getInstrItineraryData () const inline override
Definition at line 367 of file GCNSubtarget.h.
References InstrItins.
Referenced by adjustSchedDependency().
getInstructionSelector()
InstructionSelector * llvm::GCNSubtarget::getInstructionSelector () const inline override
Definition at line 351 of file GCNSubtarget.h.
getKnownHighZeroBitsForFrameIndex()
unsigned llvm::GCNSubtarget::getKnownHighZeroBitsForFrameIndex () const inline
Return the number of high bits known to be zero for a frame index.
Definition at line 394 of file GCNSubtarget.h.
References llvm::countl_zero(), getMaxWaveScratchSize(), and llvm::AMDGPUSubtarget::getWavefrontSizeLog2().
Referenced by llvm::SITargetLowering::LowerFormalArguments().
getLDSBankCount()
int llvm::GCNSubtarget::getLDSBankCount () const inline
Definition at line 398 of file GCNSubtarget.h.
References LDSBankCount.
getLegalizerInfo()
const LegalizerInfo * llvm::GCNSubtarget::getLegalizerInfo () const inline override
Definition at line 355 of file GCNSubtarget.h.
getMaxFlatWorkGroupSize()
unsigned llvm::GCNSubtarget::getMaxFlatWorkGroupSize () const inline override virtual
Returns
Maximum flat work group size supported by the subtarget.
Implements llvm::AMDGPUSubtarget.
Definition at line 1804 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMaxFlatWorkGroupSize().
getMaxLocalMemSizeWithWaveCount()
unsigned llvm::GCNSubtarget::getMaxLocalMemSizeWithWaveCount (unsigned WaveCount, const Function &) const
Return the amount of LDS that can be used that will not restrict the occupancy lower than WaveCount.
getMaxNumAGPRs()
unsigned llvm::GCNSubtarget::getMaxNumAGPRs (const Function & F) const inline
Definition at line 1750 of file GCNSubtarget.h.
References F, and getMaxNumVGPRs().
getMaxNumPreloadedSGPRs()
unsigned GCNSubtarget::getMaxNumPreloadedSGPRs () const
Returns
Maximum number of preloaded SGPRs for the subtarget.
Definition at line 511 of file GCNSubtarget.cpp.
Referenced by getMaxNumSGPRs().
getMaxNumSGPRs() [1/3]
unsigned GCNSubtarget::getMaxNumSGPRs (const Function & F) const
Returns
Maximum number of SGPRs that meets number of waves per execution unit requirement for function F, or number of SGPRs explicitly requested using "amdgpu-num-sgpr" attribute attached to function F.
Value that meets number of waves per execution unit requirement if explicitly requested value cannot be converted to integer, violates subtarget's specifications, or does not meet number of waves per execution unit requirement.
Definition at line 536 of file GCNSubtarget.cpp.
References F, getBaseMaxNumSGPRs(), getMaxNumPreloadedSGPRs(), getReservedNumSGPRs(), and llvm::AMDGPUSubtarget::getWavesPerEU().
getMaxNumSGPRs() [2/3]
unsigned GCNSubtarget::getMaxNumSGPRs (const MachineFunction & MF) const
Returns
Maximum number of SGPRs that meets number of waves per execution unit requirement for function MF, or number of SGPRs explicitly requested using "amdgpu-num-sgpr" attribute attached to function MF.
Value that meets number of waves per execution unit requirement if explicitly requested value cannot be converted to integer, violates subtarget's specifications, or does not meet number of waves per execution unit requirement.
Definition at line 504 of file GCNSubtarget.cpp.
References F, getBaseMaxNumSGPRs(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getNumPreloadedSGPRs(), getReservedNumSGPRs(), and llvm::SIMachineFunctionInfo::getWavesPerEU().
getMaxNumSGPRs() [3/3]
unsigned llvm::GCNSubtarget::getMaxNumSGPRs (unsigned WavesPerEU, bool Addressable) const inline
Returns
Maximum number of SGPRs that meets the given number of waves per execution unit requirement supported by the subtarget.
Definition at line 1647 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMaxNumSGPRs().
Referenced by getBaseMaxNumSGPRs().
getMaxNumUserSGPRs()
unsigned llvm::GCNSubtarget::getMaxNumUserSGPRs () const inline
Definition at line 1068 of file GCNSubtarget.h.
References llvm::AMDGPU::getMaxNumUserSGPRs().
getMaxNumVectorRegs()
std::pair< unsigned, unsigned > GCNSubtarget::getMaxNumVectorRegs (const Function & F) const
Return a pair of maximum numbers of VGPRs and AGPRs that meet the number of waves per execution unit required for the function MF.
Definition at line 574 of file GCNSubtarget.cpp.
References llvm::alignTo(), assert(), F, llvm::AMDGPU::getIntegerPairAttribute(), getMaxNumVGPRs(), has1024AddressableVGPRs(), hasGFX90AInsts(), and hasMAIInsts().
getMaxNumVGPRs() [1/3]
unsigned GCNSubtarget::getMaxNumVGPRs (const Function & F) const
Returns
Maximum number of VGPRs that meets number of waves per execution unit requirement for function F, or number of VGPRs explicitly requested using "amdgpu-num-vgpr" attribute attached to function F.
Value that meets number of waves per execution unit requirement if explicitly requested value cannot be converted to integer, violates subtarget's specifications, or does not meet number of waves per execution unit requirement.
Definition at line 556 of file GCNSubtarget.cpp.
References F, getBaseMaxNumVGPRs(), llvm::AMDGPU::getDynamicVGPRBlockSize(), getDynamicVGPRBlockSize(), getMaxNumVGPRs(), getMinNumVGPRs(), llvm::AMDGPUSubtarget::getWavesPerEU(), and isDynamicVGPREnabled().
getMaxNumVGPRs() [2/3]
unsigned GCNSubtarget::getMaxNumVGPRs (const MachineFunction & MF) const
Returns
Maximum number of VGPRs that meets number of waves per execution unit requirement for function MF, or number of VGPRs explicitly requested using "amdgpu-num-vgpr" attribute attached to function MF.
Value that meets number of waves per execution unit requirement if explicitly requested value cannot be converted to integer, violates subtarget's specifications, or does not meet number of waves per execution unit requirement.
Definition at line 569 of file GCNSubtarget.cpp.
References llvm::MachineFunction::getFunction(), and getMaxNumVGPRs().
getMaxNumVGPRs() [3/3]
unsigned llvm::GCNSubtarget::getMaxNumVGPRs (unsigned WavesPerEU, unsigned DynamicVGPRBlockSize) const inline
Returns
the maximum number of VGPRs that can be used and still achieved at least the specified number of waves WavesPerEU.
Definition at line 1728 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMaxNumVGPRs().
Referenced by getMaxNumAGPRs(), getMaxNumVectorRegs(), getMaxNumVGPRs(), and getMaxNumVGPRs().
getMaxPrivateElementSize()
unsigned llvm::GCNSubtarget::getMaxPrivateElementSize (bool ForBufferRSrc = false) const inline
Definition at line 402 of file GCNSubtarget.h.
References enableFlatScratch(), and MaxPrivateElementSize.
Referenced by llvm::SITargetLowering::canMergeStoresTo().
getMaxWaveScratchSize()
unsigned llvm::GCNSubtarget::getMaxWaveScratchSize () const inline
Definition at line 379 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX11, and llvm::AMDGPUSubtarget::GFX12.
Referenced by getKnownHighZeroBitsForFrameIndex().
getMaxWavesPerEU()
unsigned llvm::AMDGPUSubtarget::getMaxWavesPerEU () const inline
Returns
Maximum number of waves per execution unit supported by the subtarget without any kind of limitation.
Definition at line 382 of file AMDGPUSubtarget.h.
Referenced by getOccupancyWithNumSGPRs().
getMaxWorkGroupsPerCU()
unsigned llvm::GCNSubtarget::getMaxWorkGroupsPerCU (unsigned FlatWorkGroupSize) const inline override virtual
Returns
Maximum number of work groups per compute unit supported by the subtarget and limited by given FlatWorkGroupSize.
Implements llvm::AMDGPUSubtarget.
Definition at line 1794 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMaxWorkGroupsPerCU().
getMinFlatWorkGroupSize()
unsigned llvm::GCNSubtarget::getMinFlatWorkGroupSize () const inline override virtual
Returns
Minimum flat work group size supported by the subtarget.
Implements llvm::AMDGPUSubtarget.
Definition at line 1799 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMinFlatWorkGroupSize().
getMinNumSGPRs()
unsigned llvm::GCNSubtarget::getMinNumSGPRs (unsigned WavesPerEU) const inline
Returns
Minimum number of SGPRs that meets the given number of waves per execution unit requirement supported by the subtarget.
Definition at line 1641 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMinNumSGPRs().
Referenced by getBaseMaxNumSGPRs().
getMinNumVGPRs()
unsigned llvm::GCNSubtarget::getMinNumVGPRs (unsigned WavesPerEU, unsigned DynamicVGPRBlockSize) const inline
Returns
the minimum number of VGPRs that will prevent achieving more than the specified number of waves WavesPerEU.
Definition at line 1720 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMinNumVGPRs().
Referenced by getMaxNumVGPRs().
getMinWavesPerEU()
unsigned llvm::GCNSubtarget::getMinWavesPerEU () const inline override virtual
Returns
Minimum number of waves per execution unit supported by the subtarget.
Implements llvm::AMDGPUSubtarget.
Definition at line 1817 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getMinWavesPerEU().
getNSAMaxSize()
unsigned llvm::GCNSubtarget::getNSAMaxSize (bool HasSampler = false) const inline
Definition at line 1182 of file GCNSubtarget.h.
References llvm::AMDGPU::getNSAMaxSize().
getNSAThreshold()
unsigned GCNSubtarget::getNSAThreshold (const MachineFunction & MF) const
Definition at line 675 of file GCNSubtarget.cpp.
References llvm::Function::getFnAttributeAsParsedInteger(), llvm::MachineFunction::getFunction(), getGeneration(), llvm::AMDGPUSubtarget::GFX12, and NSAThreshold.
getOccupancyWithNumSGPRs()
unsigned GCNSubtarget::getOccupancyWithNumSGPRs (unsigned SGPRs) const
Return the maximum number of waves per SIMD for kernels using SGPRs SGPRs.
Definition at line 397 of file GCNSubtarget.cpp.
References getGeneration(), getMaxWavesPerEU(), and llvm::AMDGPU::IsaInfo::getOccupancyWithNumSGPRs().
Referenced by computeOccupancy().
getOccupancyWithNumVGPRs()
unsigned GCNSubtarget::getOccupancyWithNumVGPRs (unsigned VGPRs, unsigned DynamicVGPRBlockSize) const
Return the maximum number of waves per SIMD for kernels using VGPRs VGPRs.
Definition at line 403 of file GCNSubtarget.cpp.
References llvm::AMDGPU::IsaInfo::getNumWavesPerEUWithNumVGPRs().
Referenced by computeOccupancy().
getRegBankInfo()
const AMDGPURegisterBankInfo * llvm::GCNSubtarget::getRegBankInfo () const inline override
Definition at line 359 of file GCNSubtarget.h.
getRegisterInfo()
const SIRegisterInfo * llvm::GCNSubtarget::getRegisterInfo () const inline override
Definition at line 337 of file GCNSubtarget.h.
Referenced by adjustSchedDependency(), llvm::GCNTargetMachine::convertFuncInfoToYAML(), llvm::AMDGPUAsmPrinter::emitInstruction(), getBoolRC(), llvm::SITargetLowering::insertCopiesSplitCSR(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::SITargetLowering::LowerReturn(), and llvm::SITargetLowering::SITargetLowering().
getReservedNumSGPRs() [1/2]
unsigned GCNSubtarget::getReservedNumSGPRs (const Function & F) const
Returns
Reserved number of SGPRs for given function F.
Definition at line 431 of file GCNSubtarget.cpp.
References F, getBaseReservedNumSGPRs(), and hasFlatAddressSpace().
getReservedNumSGPRs() [2/2]
unsigned GCNSubtarget::getReservedNumSGPRs (const MachineFunction & MF) const
Returns
Reserved number of SGPRs for given machine function MF.
Definition at line 426 of file GCNSubtarget.cpp.
References getBaseReservedNumSGPRs(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getUserSGPRInfo(), and llvm::GCNUserSGPRUsageInfo::hasFlatScratchInit().
Referenced by getMaxNumSGPRs(), and getMaxNumSGPRs().
getScalarizeGlobalBehavior()
bool llvm::GCNSubtarget::getScalarizeGlobalBehavior () const inline
Definition at line 1050 of file GCNSubtarget.h.
References ScalarizeGlobal.
getSelectionDAGInfo()
const SelectionDAGTargetInfo * GCNSubtarget::getSelectionDAGInfo () const override
Definition at line 192 of file GCNSubtarget.cpp.
getSetRegWaitStates()
unsigned llvm::GCNSubtarget::getSetRegWaitStates () const inline
Number of hazard wait states for s_setreg_b32/s_setreg_imm32_b32.
Definition at line 545 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SEA_ISLANDS.
getSGPRAllocGranule()
unsigned llvm::GCNSubtarget::getSGPRAllocGranule () const inline
Returns
SGPR allocation granularity supported by the subtarget.
Definition at line 1620 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getSGPRAllocGranule().
getSGPREncodingGranule()
unsigned llvm::GCNSubtarget::getSGPREncodingGranule () const inline
Returns
SGPR encoding granularity supported by the subtarget.
Definition at line 1625 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getSGPREncodingGranule().
getSNopBits()
unsigned llvm::GCNSubtarget::getSNopBits () const inline
Returns
the number of significant bits in the immediate field of the S_NOP instruction.
Definition at line 1882 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX12, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
getStackAlignment()
Align llvm::GCNSubtarget::getStackAlignment () const inline
Definition at line 1037 of file GCNSubtarget.h.
Referenced by GCNSubtarget().
getTargetID()
const AMDGPU::IsaInfo::AMDGPUTargetID & llvm::GCNSubtarget::getTargetID () const inline
Definition at line 363 of file GCNSubtarget.h.
References TargetID.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction().
getTargetLowering()
const SITargetLowering * llvm::GCNSubtarget::getTargetLowering () const inline override
Definition at line 333 of file GCNSubtarget.h.
Referenced by GCNSubtarget(), and getTM().
getTotalNumSGPRs()
unsigned llvm::GCNSubtarget::getTotalNumSGPRs () const inline
Returns
Total number of SGPRs supported by the subtarget.
Definition at line 1630 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getTotalNumSGPRs().
getTotalNumVGPRs()
unsigned llvm::GCNSubtarget::getTotalNumVGPRs () const inline
Returns
Total number of VGPRs supported by the subtarget.
Definition at line 1703 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getTotalNumVGPRs().
getTrapHandlerAbi()
TrapHandlerAbi llvm::GCNSubtarget::getTrapHandlerAbi () const inline
Definition at line 493 of file GCNSubtarget.h.
References AMDHSA, llvm::AMDGPUSubtarget::isAmdHsaOS(), and NONE.
getVGPRAllocGranule()
unsigned llvm::GCNSubtarget::getVGPRAllocGranule (unsigned DynamicVGPRBlockSize) const inline
Returns
VGPR allocation granularity supported by the subtarget.
Definition at line 1693 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getVGPRAllocGranule().
getVGPREncodingGranule()
unsigned llvm::GCNSubtarget::getVGPREncodingGranule () const inline
Returns
VGPR encoding granularity supported by the subtarget.
Definition at line 1698 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getVGPREncodingGranule().
getWavesPerEUForWorkGroup()
unsigned llvm::GCNSubtarget::getWavesPerEUForWorkGroup (unsigned FlatWorkGroupSize) const inline override virtual
Returns
Number of waves per execution unit required to support the given FlatWorkGroupSize.
Implements llvm::AMDGPUSubtarget.
Definition at line 1811 of file GCNSubtarget.h.
References llvm::AMDGPU::IsaInfo::getWavesPerEUForWorkGroup().
has1024AddressableVGPRs()
bool llvm::GCNSubtarget::has1024AddressableVGPRs () const inline
Definition at line 1452 of file GCNSubtarget.h.
References Has1024AddressableVGPRs.
Referenced by getMaxNumVectorRegs().
has12DWordStoreHazard()
bool llvm::GCNSubtarget::has12DWordStoreHazard () const inline
Definition at line 1238 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS.
has1_5xVGPRs()
bool llvm::GCNSubtarget::has1_5xVGPRs () const inline
Definition at line 1372 of file GCNSubtarget.h.
References Has1_5xVGPRs.
has45BitNumRecordsBufferResource()
bool llvm::GCNSubtarget::has45BitNumRecordsBufferResource () const inline
Returns
true if the sub-target supports buffer resource (V#) with 45-bit num_records.
Definition at line 1892 of file GCNSubtarget.h.
References Has45BitNumRecordsBufferResource.
has64BitLiterals()
bool llvm::GCNSubtarget::has64BitLiterals () const inline
Definition at line 1472 of file GCNSubtarget.h.
References Has64BitLiterals.
hasA16()
bool llvm::GCNSubtarget::hasA16 () const inline
Definition at line 1158 of file GCNSubtarget.h.
References HasA16.
hasAddMinMaxInsts()
bool llvm::GCNSubtarget::hasAddMinMaxInsts () const inline
Definition at line 1587 of file GCNSubtarget.h.
References HasAddMinMaxInsts.
hasAddNoCarry()
bool llvm::GCNSubtarget::hasAddNoCarry () const inline
Returns
true if the target has integer add/sub instructions that do not produce a carry-out. This includes v_add_[iu]32, v_sub_[iu]32, v_add_[iu]16, and v_sub_[iu]16, all of which support the clamp modifier for saturation.
Definition at line 770 of file GCNSubtarget.h.
References AddNoCarryInsts.
hasAddPC64Inst()
bool llvm::GCNSubtarget::hasAddPC64Inst () const inline
Definition at line 1450 of file GCNSubtarget.h.
References GFX1250Insts.
hasAddr64()
bool llvm::GCNSubtarget::hasAddr64 () const inline
Definition at line 443 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
Referenced by initializeSubtargetDependencies().
hasAddSubU64Insts()
bool llvm::GCNSubtarget::hasAddSubU64Insts () const inline
Definition at line 1571 of file GCNSubtarget.h.
References HasAddSubU64Insts.
hasApertureRegs()
bool llvm::GCNSubtarget::hasApertureRegs () const inline
Definition at line 639 of file GCNSubtarget.h.
References HasApertureRegs.
hasArchitectedSGPRs()
bool llvm::GCNSubtarget::hasArchitectedSGPRs () const inline
Returns
true if the architected SGPRs are enabled.
Definition at line 1520 of file GCNSubtarget.h.
References HasArchitectedSGPRs.
hasAshrPkInsts()
bool llvm::GCNSubtarget::hasAshrPkInsts () const inline
Definition at line 1434 of file GCNSubtarget.h.
References HasAshrPkInsts.
hasAtomicBufferGlobalPkAddF16Insts()
bool llvm::GCNSubtarget::hasAtomicBufferGlobalPkAddF16Insts () const inline
Definition at line 933 of file GCNSubtarget.h.
References HasAtomicBufferGlobalPkAddF16Insts.
hasAtomicBufferGlobalPkAddF16NoRtnInsts()
bool llvm::GCNSubtarget::hasAtomicBufferGlobalPkAddF16NoRtnInsts () const inline
Definition at line 929 of file GCNSubtarget.h.
References HasAtomicBufferGlobalPkAddF16NoRtnInsts.
hasAtomicBufferPkAddBF16Inst()
bool llvm::GCNSubtarget::hasAtomicBufferPkAddBF16Inst () const inline
Definition at line 941 of file GCNSubtarget.h.
References HasAtomicBufferPkAddBF16Inst.
hasAtomicCSub()
bool llvm::GCNSubtarget::hasAtomicCSub () const inline
Definition at line 703 of file GCNSubtarget.h.
References GFX10_BEncoding.
hasAtomicCSubNoRtnInsts()
bool llvm::GCNSubtarget::hasAtomicCSubNoRtnInsts () const inline
Definition at line 1548 of file GCNSubtarget.h.
References HasAtomicCSubNoRtnInsts.
hasAtomicDsPkAdd16Insts()
bool llvm::GCNSubtarget::hasAtomicDsPkAdd16Insts () const inline
Definition at line 917 of file GCNSubtarget.h.
References HasAtomicDsPkAdd16Insts.
hasAtomicFaddInsts()
bool llvm::GCNSubtarget::hasAtomicFaddInsts () const inline
Definition at line 921 of file GCNSubtarget.h.
References HasAtomicFaddNoRtnInsts, and HasAtomicFaddRtnInsts.
hasAtomicFaddNoRtnInsts()
bool llvm::GCNSubtarget::hasAtomicFaddNoRtnInsts () const inline
Definition at line 927 of file GCNSubtarget.h.
References HasAtomicFaddNoRtnInsts.
hasAtomicFaddRtnInsts()
bool llvm::GCNSubtarget::hasAtomicFaddRtnInsts () const inline
Definition at line 925 of file GCNSubtarget.h.
References HasAtomicFaddRtnInsts.
hasAtomicFlatPkAdd16Insts()
bool llvm::GCNSubtarget::hasAtomicFlatPkAdd16Insts () const inline
Definition at line 919 of file GCNSubtarget.h.
References HasAtomicFlatPkAdd16Insts.
hasAtomicFMinFMaxF32FlatInsts()
bool llvm::GCNSubtarget::hasAtomicFMinFMaxF32FlatInsts () const inline
Definition at line 909 of file GCNSubtarget.h.
References HasAtomicFMinFMaxF32FlatInsts.
hasAtomicFMinFMaxF32GlobalInsts()
bool llvm::GCNSubtarget::hasAtomicFMinFMaxF32GlobalInsts () const inline
Definition at line 901 of file GCNSubtarget.h.
References HasAtomicFMinFMaxF32GlobalInsts.
hasAtomicFMinFMaxF64FlatInsts()
bool llvm::GCNSubtarget::hasAtomicFMinFMaxF64FlatInsts () const inline
Definition at line 913 of file GCNSubtarget.h.
References HasAtomicFMinFMaxF64FlatInsts.
hasAtomicFMinFMaxF64GlobalInsts()
bool llvm::GCNSubtarget::hasAtomicFMinFMaxF64GlobalInsts () const inline
Definition at line 905 of file GCNSubtarget.h.
References HasAtomicFMinFMaxF64GlobalInsts.
hasAtomicGlobalPkAddBF16Inst()
bool llvm::GCNSubtarget::hasAtomicGlobalPkAddBF16Inst () const inline
Definition at line 937 of file GCNSubtarget.h.
References HasAtomicGlobalPkAddBF16Inst.
hasAutoWaitcntBeforeBarrier()
bool llvm::GCNSubtarget::hasAutoWaitcntBeforeBarrier () const inline
Definition at line 599 of file GCNSubtarget.h.
References AutoWaitcntBeforeBarrier.
hasBitOp3Insts()
bool llvm::GCNSubtarget::hasBitOp3Insts () const inline
Definition at line 1430 of file GCNSubtarget.h.
References HasBitOp3Insts.
hasBVHDualAndBVH8Insts()
bool llvm::GCNSubtarget::hasBVHDualAndBVH8Insts () const inline
Definition at line 1485 of file GCNSubtarget.h.
References HasBVHDualAndBVH8Insts.
hasClusters()
bool llvm::GCNSubtarget::hasClusters () const inline
Returns
true if the subtarget supports clusters of workgroups.
Definition at line 1871 of file GCNSubtarget.h.
References HasClusters.
hasCompressedExport()
bool llvm::GCNSubtarget::hasCompressedExport () const inline
Return true if the target's EXP instruction has the COMPR flag, which affects the meaning of the EN (enable) bits.
Definition at line 1366 of file GCNSubtarget.h.
References GFX11Insts.
hasCondSubInsts()
bool llvm::GCNSubtarget::hasCondSubInsts () const inline
Definition at line 1615 of file GCNSubtarget.h.
References GFX12Insts.
hasCubeInsts()
bool llvm::GCNSubtarget::hasCubeInsts () const inline
Definition at line 881 of file GCNSubtarget.h.
References HasCubeInsts.
hasCvtFP8VOP1Bug()
bool llvm::GCNSubtarget::hasCvtFP8VOP1Bug () const inline
Definition at line 1544 of file GCNSubtarget.h.
References HasCvtFP8Vop1Bug.
hasCvtNormInsts()
bool llvm::GCNSubtarget::hasCvtNormInsts () const inline
Definition at line 889 of file GCNSubtarget.h.
References HasCvtNormInsts.
hasCvtPkNormVOP2Insts()
bool llvm::GCNSubtarget::hasCvtPkNormVOP2Insts () const inline
Definition at line 891 of file GCNSubtarget.h.
References HasCvtPkNormVOP2Insts.
hasCvtPkNormVOP3Insts()
bool llvm::GCNSubtarget::hasCvtPkNormVOP3Insts () const inline
Definition at line 893 of file GCNSubtarget.h.
References HasCvtPkNormVOP3Insts.
hasCvtScaleForwardingHazard()
bool llvm::GCNSubtarget::hasCvtScaleForwardingHazard () const inline
Definition at line 1340 of file GCNSubtarget.h.
References GFX950Insts.
hasD16Images()
bool llvm::GCNSubtarget::hasD16Images () const inline
Definition at line 742 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
hasD16LoadStore()
bool llvm::GCNSubtarget::hasD16LoadStore () const inline
Definition at line 734 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
Referenced by d16PreservesUnusedBits().
hasDefaultComponentBroadcast()
bool llvm::GCNSubtarget::hasDefaultComponentBroadcast () const inline
Definition at line 974 of file GCNSubtarget.h.
References HasDefaultComponentBroadcast.
hasDefaultComponentZero()
bool llvm::GCNSubtarget::hasDefaultComponentZero () const inline
Definition at line 972 of file GCNSubtarget.h.
References HasDefaultComponentZero.
hasDelayAlu()
bool llvm::GCNSubtarget::hasDelayAlu () const inline
Return true if the target has the S_DELAY_ALU instruction.
Definition at line 1379 of file GCNSubtarget.h.
References GFX11Insts.
hasDenormModeInst()
bool llvm::GCNSubtarget::hasDenormModeInst () const inline
Returns
If target supports S_DENORM_MODE.
Definition at line 563 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX10.
hasDLInsts()
bool llvm::GCNSubtarget::hasDLInsts () const inline
Definition at line 811 of file GCNSubtarget.h.
References HasDLInsts.
hasDot10Insts()
bool llvm::GCNSubtarget::hasDot10Insts () const inline
Definition at line 853 of file GCNSubtarget.h.
References HasDot10Insts.
hasDot11Insts()
bool llvm::GCNSubtarget::hasDot11Insts () const inline
Definition at line 857 of file GCNSubtarget.h.
References HasDot11Insts.
hasDot12Insts()
bool llvm::GCNSubtarget::hasDot12Insts () const inline
Definition at line 861 of file GCNSubtarget.h.
References HasDot12Insts.
hasDot13Insts()
bool llvm::GCNSubtarget::hasDot13Insts () const inline
Definition at line 865 of file GCNSubtarget.h.
References HasDot13Insts.
hasDot1Insts()
bool llvm::GCNSubtarget::hasDot1Insts () const inline
Definition at line 817 of file GCNSubtarget.h.
References HasDot1Insts.
hasDot2Insts()
bool llvm::GCNSubtarget::hasDot2Insts () const inline
Definition at line 821 of file GCNSubtarget.h.
References HasDot2Insts.
hasDot3Insts()
bool llvm::GCNSubtarget::hasDot3Insts () const inline
Definition at line 825 of file GCNSubtarget.h.
References HasDot3Insts.
hasDot4Insts()
bool llvm::GCNSubtarget::hasDot4Insts () const inline
Definition at line 829 of file GCNSubtarget.h.
References HasDot4Insts.
hasDot5Insts()
bool llvm::GCNSubtarget::hasDot5Insts () const inline
Definition at line 833 of file GCNSubtarget.h.
References HasDot5Insts.
hasDot6Insts()
bool llvm::GCNSubtarget::hasDot6Insts () const inline
Definition at line 837 of file GCNSubtarget.h.
References HasDot6Insts.
hasDot7Insts()
bool llvm::GCNSubtarget::hasDot7Insts () const inline
Definition at line 841 of file GCNSubtarget.h.
References HasDot7Insts.
hasDot8Insts()
bool llvm::GCNSubtarget::hasDot8Insts () const inline
Definition at line 845 of file GCNSubtarget.h.
References HasDot8Insts.
hasDot9Insts()
bool llvm::GCNSubtarget::hasDot9Insts () const inline
Definition at line 849 of file GCNSubtarget.h.
References HasDot9Insts.
hasDOTOpSelHazard()
bool llvm::GCNSubtarget::hasDOTOpSelHazard () const inline
Definition at line 1307 of file GCNSubtarget.h.
References GFX11Insts, and GFX940Insts.
hasDPALU_DPP()
bool llvm::GCNSubtarget::hasDPALU_DPP () const inline
Definition at line 1125 of file GCNSubtarget.h.
References HasDPALU_DPP.
hasDPP()
bool llvm::GCNSubtarget::hasDPP () const inline
Definition at line 1109 of file GCNSubtarget.h.
References HasDPP.
hasDPP8()
bool llvm::GCNSubtarget::hasDPP8 () const inline
Definition at line 1121 of file GCNSubtarget.h.
References HasDPP8.
hasDPPBroadcasts()
bool llvm::GCNSubtarget::hasDPPBroadcasts () const inline
Definition at line 1113 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX10, and HasDPP.
hasDPPSrc1SGPR()
bool llvm::GCNSubtarget::hasDPPSrc1SGPR () const inline
Definition at line 1129 of file GCNSubtarget.h.
References HasDPPSrc1SGPR.
hasDPPWavefrontShifts()
bool llvm::GCNSubtarget::hasDPPWavefrontShifts () const inline
Definition at line 1117 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX10, and HasDPP.
hasDS96AndDS128()
bool llvm::GCNSubtarget::hasDS96AndDS128 () const inline
Returns
If target supports ds_read/write_b96/128.
Definition at line 578 of file GCNSubtarget.h.
References CIInsts.
hasDsAtomicAsyncBarrierArriveB64PipeBug()
bool llvm::GCNSubtarget::hasDsAtomicAsyncBarrierArriveB64PipeBug () const inline
Definition at line 1854 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasDstSelForwardingHazard()
bool llvm::GCNSubtarget::hasDstSelForwardingHazard () const inline
Definition at line 1304 of file GCNSubtarget.h.
References GFX940Insts.
hasDwordx3LoadStores()
bool llvm::GCNSubtarget::hasDwordx3LoadStores () const inline
Definition at line 1243 of file GCNSubtarget.h.
References CIInsts.
hasDX10ClampMode()
bool llvm::GCNSubtarget::hasDX10ClampMode () const inline
Definition at line 1551 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasEmulatedSystemScopeAtomics()
bool llvm::GCNSubtarget::hasEmulatedSystemScopeAtomics () const inline
Returns
true is HW emulates system scope atomics unsupported by the PCI-e via CAS loop.
Definition at line 968 of file GCNSubtarget.h.
References HasEmulatedSystemScopeAtomics.
Referenced by globalMemoryFPAtomicIsLegal().
hasExpertSchedulingMode()
bool llvm::GCNSubtarget::hasExpertSchedulingMode () const inline
Returns
true if the target supports expert scheduling mode 2 which relies on the compiler to insert waits to avoid hazards between VMEM and VALU instructions in some instances.
Definition at line 1465 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasExportInsts()
bool llvm::GCNSubtarget::hasExportInsts () const inline
Definition at line 711 of file GCNSubtarget.h.
References hasGFX1250Insts(), and hasGFX940Insts().
hasExtendedImageInsts()
bool llvm::GCNSubtarget::hasExtendedImageInsts () const inline
Definition at line 1150 of file GCNSubtarget.h.
References HasExtendedImageInsts.
hasExtendedWaitCounts()
bool llvm::GCNSubtarget::hasExtendedWaitCounts () const inline
Returns
true if the target uses LOADcnt/SAMPLEcnt/BVHcnt, DScnt/KMcnt and STOREcnt rather than VMcnt, LGKMcnt and VScnt respectively.
Definition at line 1412 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasFlat()
bool llvm::GCNSubtarget::hasFlat () const inline
Definition at line 447 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS.
Referenced by initializeSubtargetDependencies().
hasFlatAddressSpace()
bool llvm::GCNSubtarget::hasFlatAddressSpace () const inline
Definition at line 661 of file GCNSubtarget.h.
References FlatAddressSpace.
Referenced by getReservedNumSGPRs(), and hasFlatScrRegister().
hasFlatAtomicFaddF32Inst()
bool llvm::GCNSubtarget::hasFlatAtomicFaddF32Inst () const inline
Definition at line 945 of file GCNSubtarget.h.
References HasFlatAtomicFaddF32Inst.
hasFlatBufferGlobalAtomicFaddF64Inst()
bool llvm::GCNSubtarget::hasFlatBufferGlobalAtomicFaddF64Inst () const inline
Returns
true if the target has flat, global, and buffer atomic fadd for double.
Definition at line 949 of file GCNSubtarget.h.
References HasFlatBufferGlobalAtomicFaddF64Inst.
hasFlatGlobalInsts()
bool llvm::GCNSubtarget::hasFlatGlobalInsts () const inline
Definition at line 673 of file GCNSubtarget.h.
References FlatGlobalInsts.
hasFlatGVSMode()
bool llvm::GCNSubtarget::hasFlatGVSMode () const inline
Definition at line 1207 of file GCNSubtarget.h.
References FlatGVSMode.
hasFlatInstOffsets()
bool llvm::GCNSubtarget::hasFlatInstOffsets () const inline
Definition at line 669 of file GCNSubtarget.h.
References FlatInstOffsets.
hasFlatLgkmVMemCountInOrder()
bool llvm::GCNSubtarget::hasFlatLgkmVMemCountInOrder () const inline
Definition at line 730 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasFlatScratchHiInB64InstHazard()
bool llvm::GCNSubtarget::hasFlatScratchHiInB64InstHazard () const inline
Definition at line 1866 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX12, and GFX1250Insts.
hasFlatScratchInsts()
bool llvm::GCNSubtarget::hasFlatScratchInsts () const inline
Definition at line 677 of file GCNSubtarget.h.
References FlatScratchInsts.
Referenced by enableFlatScratch(), and hasFlatScratchSTMode().
hasFlatScratchSTMode()
bool llvm::GCNSubtarget::hasFlatScratchSTMode () const inline
Definition at line 684 of file GCNSubtarget.h.
References hasFlatScratchInsts(), hasGFX10_3Insts(), and hasGFX940Insts().
hasFlatScratchSVSMode()
bool llvm::GCNSubtarget::hasFlatScratchSVSMode () const inline
Definition at line 688 of file GCNSubtarget.h.
References GFX11Insts, and GFX940Insts.
hasFlatScratchSVSSwizzleBug()
bool llvm::GCNSubtarget::hasFlatScratchSVSSwizzleBug () const inline
Definition at line 1376 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
hasFlatScrRegister()
bool llvm::GCNSubtarget::hasFlatScrRegister () const inline
Definition at line 665 of file GCNSubtarget.h.
References hasFlatAddressSpace().
hasFlatSegmentOffsetBug()
bool llvm::GCNSubtarget::hasFlatSegmentOffsetBug () const inline
Definition at line 726 of file GCNSubtarget.h.
References HasFlatSegmentOffsetBug.
hasFMA()
bool llvm::GCNSubtarget::hasFMA () const inline
Definition at line 475 of file GCNSubtarget.h.
References FMA.
hasFmaakFmamkF32Insts()
bool llvm::GCNSubtarget::hasFmaakFmamkF32Insts () const inline
Definition at line 1140 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX10, and hasGFX940Insts().
hasFmaakFmamkF64Insts()
bool llvm::GCNSubtarget::hasFmaakFmamkF64Insts () const inline
Definition at line 1144 of file GCNSubtarget.h.
References hasGFX1250Insts().
hasFmacF64Inst()
bool llvm::GCNSubtarget::hasFmacF64Inst () const inline
Definition at line 815 of file GCNSubtarget.h.
References HasFmacF64Inst.
hasFmaMixBF16Insts()
bool llvm::GCNSubtarget::hasFmaMixBF16Insts () const inline
Definition at line 473 of file GCNSubtarget.h.
References HasFmaMixBF16Insts.
hasFmaMixInsts()
bool llvm::GCNSubtarget::hasFmaMixInsts () const inline
Definition at line 469 of file GCNSubtarget.h.
References HasFmaMixInsts.
hasFormattedMUBUFInsts()
bool llvm::GCNSubtarget::hasFormattedMUBUFInsts () const inline
Definition at line 709 of file GCNSubtarget.h.
References hasGFX1250Insts().
hasFP64()
bool llvm::GCNSubtarget::hasFP64 () const inline
Definition at line 423 of file GCNSubtarget.h.
References FP64.
Referenced by initializeSubtargetDependencies().
hasFP8ConversionInsts()
bool llvm::GCNSubtarget::hasFP8ConversionInsts () const inline
Definition at line 877 of file GCNSubtarget.h.
References HasFP8ConversionInsts.
hasFP8E5M3Insts()
bool llvm::GCNSubtarget::hasFP8E5M3Insts () const inline
Definition at line 895 of file GCNSubtarget.h.
References HasFP8E5M3Insts.
hasFP8Insts()
bool llvm::GCNSubtarget::hasFP8Insts () const inline
Definition at line 873 of file GCNSubtarget.h.
References HasFP8Insts.
hasFPAtomicToDenormModeHazard()
bool llvm::GCNSubtarget::hasFPAtomicToDenormModeHazard () const inline
Definition at line 1324 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX10.
hasFractBug()
bool llvm::GCNSubtarget::hasFractBug () const inline
Definition at line 457 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS.
hasFullRate64Ops()
bool llvm::GCNSubtarget::hasFullRate64Ops () const inline
Definition at line 439 of file GCNSubtarget.h.
References FullRate64Ops.
hasG16()
bool llvm::GCNSubtarget::hasG16 () const inline
Definition at line 1160 of file GCNSubtarget.h.
References HasG16.
hasGDS()
bool llvm::GCNSubtarget::hasGDS () const inline
Returns
true if Global Data Share is supported.
Definition at line 1523 of file GCNSubtarget.h.
References HasGDS.
hasGetPCZeroExtension()
bool llvm::GCNSubtarget::hasGetPCZeroExtension () const inline
Definition at line 1607 of file GCNSubtarget.h.
References GFX1250Insts, and GFX12Insts.
hasGetWaveIdInst()
bool llvm::GCNSubtarget::hasGetWaveIdInst () const inline
Definition at line 986 of file GCNSubtarget.h.
References HasGetWaveIdInst.
hasGFX10_3Insts()
bool llvm::GCNSubtarget::hasGFX10_3Insts () const inline
Definition at line 1194 of file GCNSubtarget.h.
References GFX10_3Insts.
Referenced by hasFlatScratchSTMode(), and hasSubClampInsts().
hasGFX10_AEncoding()
bool llvm::GCNSubtarget::hasGFX10_AEncoding () const inline
Definition at line 1186 of file GCNSubtarget.h.
References GFX10_AEncoding.
hasGFX10_BEncoding()
bool llvm::GCNSubtarget::hasGFX10_BEncoding () const inline
Definition at line 1190 of file GCNSubtarget.h.
References GFX10_BEncoding.
hasGFX1250Insts()
bool llvm::GCNSubtarget::hasGFX1250Insts () const inline
Definition at line 1566 of file GCNSubtarget.h.
References GFX1250Insts.
Referenced by hasExportInsts(), hasFmaakFmamkF64Insts(), hasFormattedMUBUFInsts(), hasLdsAtomicAddF64(), hasMTBUFInsts(), hasVINTERPEncoding(), and supportsWave64().
hasGFX90AInsts()
bool llvm::GCNSubtarget::hasGFX90AInsts () const inline
Definition at line 1322 of file GCNSubtarget.h.
References GFX90AInsts.
Referenced by getBaseMaxNumVGPRs(), getMaxNumVectorRegs(), hasLdsAtomicAddF64(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
hasGFX940Insts()
bool llvm::GCNSubtarget::hasGFX940Insts () const inline
Definition at line 1385 of file GCNSubtarget.h.
References GFX940Insts.
Referenced by hasExportInsts(), hasFlatScratchSTMode(), and hasFmaakFmamkF32Insts().
hasGFX950Insts()
bool llvm::GCNSubtarget::hasGFX950Insts () const inline
Definition at line 1389 of file GCNSubtarget.h.
References GFX950Insts.
Referenced by hasLDSLoadB96_B128().
hasGlobalAddTidInsts()
bool llvm::GCNSubtarget::hasGlobalAddTidInsts () const inline
Definition at line 699 of file GCNSubtarget.h.
References GFX10_BEncoding.
hasGloballyAddressableScratch()
bool llvm::GCNSubtarget::hasGloballyAddressableScratch () const inline
Definition at line 1346 of file GCNSubtarget.h.
References HasGloballyAddressableScratch.
Referenced by getPrivateAtomicExpansionKind().
hasGWS()
bool llvm::GCNSubtarget::hasGWS () const inline
Returns
true if Global Wave Sync is supported.
Definition at line 1526 of file GCNSubtarget.h.
References HasGWS.
hasGWSAutoReplay()
bool llvm::GCNSubtarget::hasGWSAutoReplay () const inline
Definition at line 757 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasGWSSemaReleaseAll()
bool llvm::GCNSubtarget::hasGWSSemaReleaseAll () const inline
Returns
if target has ds_gws_sema_release_all instruction.
Definition at line 762 of file GCNSubtarget.h.
References CIInsts.
hasHalfRate64Ops() [1/2]
bool llvm::GCNSubtarget::hasHalfRate64Ops () const inline
Definition at line 435 of file GCNSubtarget.h.
References HalfRate64Ops.
hasHalfRate64Ops() [2/2]
bool llvm::GCNSubtarget::hasHalfRate64Ops (const TargetSubtargetInfo & STI) static
hasHardClauses()
bool llvm::GCNSubtarget::hasHardClauses () const inline
Definition at line 1320 of file GCNSubtarget.h.
References MaxHardClauseLength.
hasHWFP64()
bool llvm::GCNSubtarget::hasHWFP64 () const inline
Definition at line 431 of file GCNSubtarget.h.
References FP64.
hasIEEEMinimumMaximumInsts()
bool llvm::GCNSubtarget::hasIEEEMinimumMaximumInsts () const inline
Definition at line 1557 of file GCNSubtarget.h.
References HasIEEEMinimumMaximumInsts.
hasIEEEMode()
bool llvm::GCNSubtarget::hasIEEEMode () const inline
Definition at line 1554 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasImageGather4D16Bug()
bool llvm::GCNSubtarget::hasImageGather4D16Bug () const inline
Definition at line 1168 of file GCNSubtarget.h.
References HasImageGather4D16Bug.
hasImageInsts()
bool llvm::GCNSubtarget::hasImageInsts () const inline
Definition at line 1146 of file GCNSubtarget.h.
References HasImageInsts.
hasImageStoreD16Bug()
bool llvm::GCNSubtarget::hasImageStoreD16Bug () const inline
Definition at line 1166 of file GCNSubtarget.h.
References HasImageStoreD16Bug.
hasInstFwdPrefetchBug()
bool llvm::GCNSubtarget::hasInstFwdPrefetchBug () const inline
Definition at line 1280 of file GCNSubtarget.h.
References HasInstFwdPrefetchBug.
hasInstPrefetch()
bool llvm::GCNSubtarget::hasInstPrefetch () const inline
Definition at line 1014 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX10, and llvm::AMDGPUSubtarget::GFX11.
hasIntClamp()
bool llvm::GCNSubtarget::hasIntClamp () const inline
Definition at line 419 of file GCNSubtarget.h.
References HasIntClamp.
hasIntMinMax64()
bool llvm::GCNSubtarget::hasIntMinMax64 () const inline
Definition at line 1584 of file GCNSubtarget.h.
References GFX1250Insts.
hasKernargPreload()
bool llvm::GCNSubtarget::hasKernargPreload () const inline
Definition at line 1538 of file GCNSubtarget.h.
References KernargPreload.
Referenced by needsKernArgPreloadProlog().
hasLdsAtomicAddF64()
bool llvm::GCNSubtarget::hasLdsAtomicAddF64 () const inline
Definition at line 718 of file GCNSubtarget.h.
References hasGFX1250Insts(), and hasGFX90AInsts().
hasLdsBarrierArriveAtomic()
bool llvm::GCNSubtarget::hasLdsBarrierArriveAtomic () const inline
Definition at line 1476 of file GCNSubtarget.h.
References HasLdsBarrierArriveAtomic.
hasLdsBranchVmemWARHazard()
bool llvm::GCNSubtarget::hasLdsBranchVmemWARHazard () const inline
Definition at line 1288 of file GCNSubtarget.h.
References HasLdsBranchVmemWARHazard.
hasLdsDirect()
bool llvm::GCNSubtarget::hasLdsDirect () const inline
Definition at line 1330 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
hasLDSFPAtomicAddF32()
bool llvm::GCNSubtarget::hasLDSFPAtomicAddF32 () const inline
Definition at line 1100 of file GCNSubtarget.h.
References GFX8Insts.
hasLDSFPAtomicAddF64()
bool llvm::GCNSubtarget::hasLDSFPAtomicAddF64 () const inline
Definition at line 1101 of file GCNSubtarget.h.
References GFX1250Insts, and GFX90AInsts.
hasLDSLoadB96_B128()
bool llvm::GCNSubtarget::hasLDSLoadB96_B128 () const inline
Returns true if the target supports global_load_lds_dwordx3/global_load_lds_dwordx4 or buffer_load_dwordx3/buffer_load_dwordx4 with the lds bit.
Definition at line 1394 of file GCNSubtarget.h.
References hasGFX950Insts().
hasLDSMisalignedBug()
bool llvm::GCNSubtarget::hasLDSMisalignedBug () const inline
Definition at line 1276 of file GCNSubtarget.h.
References EnableCuMode, and LDSMisalignedBug.
hasLdsWaitVMSRC()
bool llvm::GCNSubtarget::hasLdsWaitVMSRC () const inline
Definition at line 1332 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasLegacyGeometry()
bool llvm::GCNSubtarget::hasLegacyGeometry () const inline
Definition at line 1535 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
hasLerpInst()
bool llvm::GCNSubtarget::hasLerpInst () const inline
Definition at line 883 of file GCNSubtarget.h.
References HasLerpInst.
hasLshlAddU64Inst()
bool llvm::GCNSubtarget::hasLshlAddU64Inst () const inline
Definition at line 1202 of file GCNSubtarget.h.
References HasLshlAddU64Inst.
hasMad64_32()
bool llvm::GCNSubtarget::hasMad64_32 () const inline
Definition at line 787 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SEA_ISLANDS.
hasMadF16()
bool GCNSubtarget::hasMadF16 () const
Definition at line 387 of file GCNSubtarget.cpp.
Referenced by llvm::SITargetLowering::SITargetLowering().
hasMADIntraFwdBug()
bool llvm::GCNSubtarget::hasMADIntraFwdBug () const inline
Definition at line 1170 of file GCNSubtarget.h.
References HasMADIntraFwdBug.
hasMadU32Inst()
bool llvm::GCNSubtarget::hasMadU32Inst () const inline
Definition at line 1574 of file GCNSubtarget.h.
References HasMadU32Inst.
hasMadU64U32NoCarry()
bool llvm::GCNSubtarget::hasMadU64U32NoCarry () const inline
Definition at line 1581 of file GCNSubtarget.h.
References GFX1250Insts.
hasMAIInsts()
bool llvm::GCNSubtarget::hasMAIInsts () const inline
Definition at line 869 of file GCNSubtarget.h.
References HasMAIInsts.
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getHSAKernelProps(), getMaxNumVectorRegs(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
hasMcastLoadInsts()
bool llvm::GCNSubtarget::hasMcastLoadInsts () const inline
Definition at line 879 of file GCNSubtarget.h.
References HasMcastLoadInsts.
hasMed3_16()
bool llvm::GCNSubtarget::hasMed3_16 () const inline
Definition at line 461 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasMemoryAtomicFaddF32DenormalSupport()
bool llvm::GCNSubtarget::hasMemoryAtomicFaddF32DenormalSupport () const inline
Returns
true if the target's flat, global, and buffer atomic fadd for float supports denormal handling.
Definition at line 955 of file GCNSubtarget.h.
References HasMemoryAtomicFaddF32DenormalSupport.
hasMergedShaders()
bool llvm::GCNSubtarget::hasMergedShaders () const inline
Returns
true if the machine has merged shaders in which s0-s7 are reserved by the hardware and user SGPRs start at s8
Definition at line 1530 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasMFMAInlineLiteralBug()
bool llvm::GCNSubtarget::hasMFMAInlineLiteralBug () const inline
Definition at line 1234 of file GCNSubtarget.h.
References HasMFMAInlineLiteralBug.
hasMIMG_R128()
bool llvm::GCNSubtarget::hasMIMG_R128 () const inline
Definition at line 427 of file GCNSubtarget.h.
References MIMG_R128.
hasMin3Max3_16()
bool llvm::GCNSubtarget::hasMin3Max3_16 () const inline
Definition at line 465 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
Referenced by supportsMin3Max3().
hasMin3Max3PKF16()
bool llvm::GCNSubtarget::hasMin3Max3PKF16 () const inline
Definition at line 1444 of file GCNSubtarget.h.
References HasMin3Max3PKF16.
Referenced by supportsMin3Max3().
hasMinimum3Maximum3F16()
bool llvm::GCNSubtarget::hasMinimum3Maximum3F16 () const inline
Definition at line 1440 of file GCNSubtarget.h.
References HasMinimum3Maximum3F16.
Referenced by supportsMin3Max3().
hasMinimum3Maximum3F32()
bool llvm::GCNSubtarget::hasMinimum3Maximum3F32 () const inline
Definition at line 1436 of file GCNSubtarget.h.
References HasMinimum3Maximum3F32.
Referenced by supportsMin3Max3().
hasMinimum3Maximum3PKF16()
bool llvm::GCNSubtarget::hasMinimum3Maximum3PKF16 () const inline
Definition at line 1456 of file GCNSubtarget.h.
References HasMinimum3Maximum3PKF16.
Referenced by supportsMin3Max3().
hasMovB64()
bool llvm::GCNSubtarget::hasMovB64 () const inline
Definition at line 1200 of file GCNSubtarget.h.
References GFX1250Insts, and GFX940Insts.
hasMovrel()
bool llvm::GCNSubtarget::hasMovrel () const inline
Definition at line 1076 of file GCNSubtarget.h.
References HasMovrel.
Referenced by useVGPRIndexMode().
hasMSAALoadDstSelBug()
bool llvm::GCNSubtarget::hasMSAALoadDstSelBug () const inline
Definition at line 1172 of file GCNSubtarget.h.
References HasMSAALoadDstSelBug.
hasMTBUFInsts()
bool llvm::GCNSubtarget::hasMTBUFInsts () const inline
Definition at line 707 of file GCNSubtarget.h.
References hasGFX1250Insts().
hasMultiDwordFlatScratchAddressing()
bool llvm::GCNSubtarget::hasMultiDwordFlatScratchAddressing () const inline
Definition at line 722 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasNegativeScratchOffsetBug()
bool llvm::GCNSubtarget::hasNegativeScratchOffsetBug () const inline
Definition at line 1228 of file GCNSubtarget.h.
References NegativeScratchOffsetBug.
hasNegativeUnalignedScratchOffsetBug()
bool llvm::GCNSubtarget::hasNegativeUnalignedScratchOffsetBug () const inline
Definition at line 1230 of file GCNSubtarget.h.
References NegativeUnalignedScratchOffsetBug.
hasNoDataDepHazard()
bool llvm::GCNSubtarget::hasNoDataDepHazard () const inline
Definition at line 1006 of file GCNSubtarget.h.
References HasNoDataDepHazard.
hasNoF16PseudoScalarTransInlineConstants()
bool llvm::GCNSubtarget::hasNoF16PseudoScalarTransInlineConstants () const inline
Returns
true if inline constants are not supported for F16 pseudo scalar transcendentals.
Definition at line 1416 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasNonNSAEncoding()
bool llvm::GCNSubtarget::hasNonNSAEncoding () const inline
Definition at line 1178 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasNoSdstCMPX()
bool llvm::GCNSubtarget::hasNoSdstCMPX () const inline
Definition at line 978 of file GCNSubtarget.h.
References HasNoSdstCMPX.
hasNSAClauseBug()
bool llvm::GCNSubtarget::hasNSAClauseBug () const inline
Definition at line 1318 of file GCNSubtarget.h.
References HasNSAClauseBug.
hasNSAEncoding()
bool llvm::GCNSubtarget::hasNSAEncoding () const inline
Definition at line 1176 of file GCNSubtarget.h.
References HasNSAEncoding.
hasNSAtoVMEMBug()
bool llvm::GCNSubtarget::hasNSAtoVMEMBug () const inline
Definition at line 1314 of file GCNSubtarget.h.
References HasNSAtoVMEMBug.
hasNullExportTarget()
bool llvm::GCNSubtarget::hasNullExportTarget () const inline
Return true if the target's EXP instruction supports the NULL export target.
Definition at line 1370 of file GCNSubtarget.h.
References GFX11Insts.
hasOffset3fBug()
bool llvm::GCNSubtarget::hasOffset3fBug () const inline
Definition at line 1162 of file GCNSubtarget.h.
References HasOffset3fBug.
Referenced by llvm::AMDGPUAsmPrinter::emitInstruction().
hasOnlyRevVALUShifts()
bool llvm::GCNSubtarget::hasOnlyRevVALUShifts () const inline
Definition at line 453 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
hasPackedFP32Ops()
bool llvm::GCNSubtarget::hasPackedFP32Ops () const inline
Definition at line 1131 of file GCNSubtarget.h.
References HasPackedFP32Ops.
hasPackedTID()
bool llvm::GCNSubtarget::hasPackedTID () const inline
Definition at line 1381 of file GCNSubtarget.h.
References HasPackedTID.
hasPartialNSAEncoding()
bool llvm::GCNSubtarget::hasPartialNSAEncoding () const inline
Definition at line 1180 of file GCNSubtarget.h.
References HasPartialNSAEncoding.
hasPermlane16Swap()
bool llvm::GCNSubtarget::hasPermlane16Swap () const inline
Definition at line 1432 of file GCNSubtarget.h.
References HasPermlane16Swap.
hasPermlane32Swap()
bool llvm::GCNSubtarget::hasPermlane32Swap () const inline
Definition at line 1433 of file GCNSubtarget.h.
References HasPermlane32Swap.
hasPermLane64()
bool llvm::GCNSubtarget::hasPermLane64 () const inline
Returns
true if the subtarget has the v_permlane64_b32 instruction.
Definition at line 1107 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
hasPermLaneX16()
bool llvm::GCNSubtarget::hasPermLaneX16 () const inline
Returns
true if the subtarget has the v_permlanex16_b32 instruction.
Definition at line 1104 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX10.
hasPkAddMinMaxInsts()
bool llvm::GCNSubtarget::hasPkAddMinMaxInsts () const inline
Definition at line 1590 of file GCNSubtarget.h.
References HasPkAddMinMaxInsts.
hasPKF32InstsReplicatingLower32BitsOfScalarInput()
bool llvm::GCNSubtarget::hasPKF32InstsReplicatingLower32BitsOfScalarInput () const inline
Returns
true if the target has packed f32 instructions that only read 32 bits from a scalar operand (SGPR or literal) and replicates the bits to both channels.
Definition at line 1426 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX12, and GFX1250Insts.
hasPkFmacF16Inst()
bool llvm::GCNSubtarget::hasPkFmacF16Inst () const inline
Definition at line 897 of file GCNSubtarget.h.
References HasPkFmacF16Inst.
hasPkMinMax3Insts()
bool llvm::GCNSubtarget::hasPkMinMax3Insts () const inline
Definition at line 1593 of file GCNSubtarget.h.
References GFX1250Insts.
hasPkMovB32()
bool llvm::GCNSubtarget::hasPkMovB32 () const inline
Definition at line 1136 of file GCNSubtarget.h.
References GFX90AInsts.
hasPointSampleAccel()
bool llvm::GCNSubtarget::hasPointSampleAccel () const inline
Definition at line 1474 of file GCNSubtarget.h.
References HasPointSampleAccel.
hasPrefetch()
bool llvm::GCNSubtarget::hasPrefetch () const inline
Definition at line 1018 of file GCNSubtarget.h.
References GFX12Insts.
hasPrivEnabledTrap2NopBug()
bool llvm::GCNSubtarget::hasPrivEnabledTrap2NopBug () const inline
Definition at line 1174 of file GCNSubtarget.h.
References HasPrivEnabledTrap2NopBug.
hasPrngInst()
bool llvm::GCNSubtarget::hasPrngInst () const inline
Definition at line 1483 of file GCNSubtarget.h.
References HasPrngInst.
hasPseudoScalarTrans()
bool llvm::GCNSubtarget::hasPseudoScalarTrans () const inline
Definition at line 1402 of file GCNSubtarget.h.
References HasPseudoScalarTrans.
hasQsadInsts()
bool llvm::GCNSubtarget::hasQsadInsts () const inline
Definition at line 887 of file GCNSubtarget.h.
References HasQsadInsts.
hasR128A16()
bool llvm::GCNSubtarget::hasR128A16 () const inline
Definition at line 1154 of file GCNSubtarget.h.
References HasR128A16.
hasReadM0LdsDirectHazard()
bool llvm::GCNSubtarget::hasReadM0LdsDirectHazard () const inline
Definition at line 1260 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasReadM0LdsDmaHazard()
bool llvm::GCNSubtarget::hasReadM0LdsDmaHazard () const inline
Definition at line 1256 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasReadM0MovRelInterpHazard()
bool llvm::GCNSubtarget::hasReadM0MovRelInterpHazard () const inline
Definition at line 1247 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
hasReadM0SendMsgHazard()
bool llvm::GCNSubtarget::hasReadM0SendMsgHazard () const inline
Definition at line 1251 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX9, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
hasReadVCCZBug()
bool llvm::GCNSubtarget::hasReadVCCZBug () const inline
Extra wait hazard is needed in some cases before s_cbranch_vccnz/s_cbranch_vccz.
Definition at line 519 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SEA_ISLANDS.
hasRelaxedBufferOOBMode()
bool llvm::GCNSubtarget::hasRelaxedBufferOOBMode () const inline
Definition at line 637 of file GCNSubtarget.h.
References RelaxedBufferOOBMode.
hasRequiredExportPriority()
bool llvm::GCNSubtarget::hasRequiredExportPriority () const inline
Definition at line 1406 of file GCNSubtarget.h.
References HasRequiredExportPriority.
hasRestrictedSOffset()
bool llvm::GCNSubtarget::hasRestrictedSOffset () const inline
Definition at line 1404 of file GCNSubtarget.h.
References HasRestrictedSOffset.
Referenced by selectSOffset().
hasRFEHazards()
bool llvm::GCNSubtarget::hasRFEHazards () const inline
Definition at line 540 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
hasRrWGMode()
bool llvm::GCNSubtarget::hasRrWGMode () const inline
Definition at line 1560 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasSadInsts()
bool llvm::GCNSubtarget::hasSadInsts () const inline
Definition at line 885 of file GCNSubtarget.h.
References HasSadInsts.
hasSafeCUPrefetch()
bool llvm::GCNSubtarget::hasSafeCUPrefetch () const inline
Definition at line 1024 of file GCNSubtarget.h.
References HasSafeCUPrefetch.
hasSafeSmemPrefetch()
bool llvm::GCNSubtarget::hasSafeSmemPrefetch () const inline
Definition at line 1022 of file GCNSubtarget.h.
References HasSafeSmemPrefetch.
hasSALUFloatInsts()
bool llvm::GCNSubtarget::hasSALUFloatInsts () const inline
Definition at line 1400 of file GCNSubtarget.h.
References HasSALUFloatInsts.
hasScalarAddSub64()
bool llvm::GCNSubtarget::hasScalarAddSub64 () const inline
Definition at line 774 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasScalarAtomics()
bool llvm::GCNSubtarget::hasScalarAtomics () const inline
Definition at line 1096 of file GCNSubtarget.h.
References HasScalarAtomics.
hasScalarCompareEq64()
bool llvm::GCNSubtarget::hasScalarCompareEq64 () const inline
Definition at line 1086 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
hasScalarDwordx3Loads()
bool llvm::GCNSubtarget::hasScalarDwordx3Loads () const inline
Definition at line 1090 of file GCNSubtarget.h.
References HasScalarDwordx3Loads.
hasScalarFlatScratchInsts()
bool llvm::GCNSubtarget::hasScalarFlatScratchInsts () const inline
Definition at line 690 of file GCNSubtarget.h.
References ScalarFlatScratchInsts.
hasScalarMulHiInsts()
bool llvm::GCNSubtarget::hasScalarMulHiInsts () const inline
Definition at line 487 of file GCNSubtarget.h.
References GFX9Insts.
hasScalarPackInsts()
bool llvm::GCNSubtarget::hasScalarPackInsts () const inline
Definition at line 483 of file GCNSubtarget.h.
References GFX9Insts.
hasScalarSMulU64()
bool llvm::GCNSubtarget::hasScalarSMulU64 () const inline
Definition at line 776 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasScalarStores()
bool llvm::GCNSubtarget::hasScalarStores () const inline
Definition at line 1092 of file GCNSubtarget.h.
References HasScalarStores.
hasScalarSubwordLoads()
bool llvm::GCNSubtarget::hasScalarSubwordLoads () const inline
Definition at line 491 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasScaleOffset()
bool llvm::GCNSubtarget::hasScaleOffset () const inline
Definition at line 1205 of file GCNSubtarget.h.
References GFX1250Insts.
hasSCmpK()
bool llvm::GCNSubtarget::hasSCmpK () const inline
Definition at line 1027 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasScratchBaseForwardingHazard()
bool llvm::GCNSubtarget::hasScratchBaseForwardingHazard () const inline
Definition at line 1860 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX12, and GFX1250Insts.
hasSDWAMac()
bool llvm::GCNSubtarget::hasSDWAMac () const inline
Definition at line 803 of file GCNSubtarget.h.
References HasSDWAMac.
hasSDWAOmod()
bool llvm::GCNSubtarget::hasSDWAOmod () const inline
Definition at line 791 of file GCNSubtarget.h.
References HasSDWAOmod.
hasSDWAOutModsVOPC()
bool llvm::GCNSubtarget::hasSDWAOutModsVOPC () const inline
Definition at line 807 of file GCNSubtarget.h.
References HasSDWAOutModsVOPC.
hasSDWAScalar()
bool llvm::GCNSubtarget::hasSDWAScalar () const inline
Definition at line 795 of file GCNSubtarget.h.
References HasSDWAScalar.
hasSDWASdst()
bool llvm::GCNSubtarget::hasSDWASdst () const inline
Definition at line 799 of file GCNSubtarget.h.
References HasSDWASdst.
hasSetPrioIncWgInst()
bool llvm::GCNSubtarget::hasSetPrioIncWgInst () const inline
Definition at line 1599 of file GCNSubtarget.h.
References HasSetPrioIncWgInst.
hasSetregVGPRMSBFixup()
bool llvm::GCNSubtarget::hasSetregVGPRMSBFixup () const inline
Definition at line 1454 of file GCNSubtarget.h.
References HasSetregVGPRMSBFixup.
hasSGetShaderCyclesInst()
bool llvm::GCNSubtarget::hasSGetShaderCyclesInst () const inline
Definition at line 1596 of file GCNSubtarget.h.
References GFX1250Insts.
hasSGPRInitBug()
bool llvm::GCNSubtarget::hasSGPRInitBug () const inline
Definition at line 1220 of file GCNSubtarget.h.
References SGPRInitBug.
Referenced by getBaseMaxNumSGPRs().
hasShaderCyclesHiLoRegisters()
bool llvm::GCNSubtarget::hasShaderCyclesHiLoRegisters () const inline
Definition at line 998 of file GCNSubtarget.h.
References HasShaderCyclesHiLoRegisters.
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter().
hasShaderCyclesRegister()
bool llvm::GCNSubtarget::hasShaderCyclesRegister () const inline
Definition at line 994 of file GCNSubtarget.h.
References HasShaderCyclesRegister.
hasShift64HighRegBug()
bool llvm::GCNSubtarget::hasShift64HighRegBug () const inline
Definition at line 1294 of file GCNSubtarget.h.
References GFX90AInsts, and GFX940Insts.
hasSignedGVSOffset()
bool llvm::GCNSubtarget::hasSignedGVSOffset () const inline
Definition at line 1210 of file GCNSubtarget.h.
References GFX1250Insts.
hasSignedScratchOffsets()
bool llvm::GCNSubtarget::hasSignedScratchOffsets () const inline
Returns
true if VADDR and SADDR fields in VSCRATCH can use negative values.
Definition at line 1564 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasSMemRealTime()
bool llvm::GCNSubtarget::hasSMemRealTime () const inline
Definition at line 1072 of file GCNSubtarget.h.
References HasSMemRealTime.
hasSMemTimeInst()
bool llvm::GCNSubtarget::hasSMemTimeInst () const inline
Definition at line 990 of file GCNSubtarget.h.
References HasSMemTimeInst.
hasSMEMtoVectorWriteHazard()
bool llvm::GCNSubtarget::hasSMEMtoVectorWriteHazard () const inline
Definition at line 1272 of file GCNSubtarget.h.
References HasSMEMtoVectorWriteHazard.
hasSMRDReadVALUDefHazard()
bool llvm::GCNSubtarget::hasSMRDReadVALUDefHazard () const inline
A read of an SGPR by SMRD instruction requires 4 wait states when the SGPR was written by a VALU instruction.
Definition at line 530 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS.
hasSPackHL()
bool llvm::GCNSubtarget::hasSPackHL () const inline
Return true if the target has the S_PACK_HL_B32_B16 instruction.
Definition at line 1362 of file GCNSubtarget.h.
References GFX11Insts.
hasSplitBarriers()
bool llvm::GCNSubtarget::hasSplitBarriers () const inline
Definition at line 1541 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX12.
hasSubClampInsts()
bool llvm::GCNSubtarget::hasSubClampInsts () const inline
Definition at line 1617 of file GCNSubtarget.h.
References hasGFX10_3Insts().
hasSWakeupBarrier()
bool llvm::GCNSubtarget::hasSWakeupBarrier () const inline
Definition at line 1602 of file GCNSubtarget.h.
References HasSWakeupBarrier.
hasSwap()
bool llvm::GCNSubtarget::hasSwap () const inline
Definition at line 479 of file GCNSubtarget.h.
References GFX9Insts.
hasTanhInsts()
bool llvm::GCNSubtarget::hasTanhInsts () const inline
Definition at line 1446 of file GCNSubtarget.h.
References HasTanhInsts.
hasTensorCvtLutInsts()
bool llvm::GCNSubtarget::hasTensorCvtLutInsts () const inline
Definition at line 1448 of file GCNSubtarget.h.
References HasTensorCvtLutInsts.
hasTransForwardingHazard()
bool llvm::GCNSubtarget::hasTransForwardingHazard () const inline
Definition at line 1300 of file GCNSubtarget.h.
References GFX940Insts.
hasTransposeLoadF4F6Insts()
bool llvm::GCNSubtarget::hasTransposeLoadF4F6Insts () const inline
Definition at line 1460 of file GCNSubtarget.h.
References HasTransposeLoadF4F6Insts.
hasUnalignedAccessMode()
bool llvm::GCNSubtarget::hasUnalignedAccessMode () const inline
Definition at line 633 of file GCNSubtarget.h.
References UnalignedAccessMode.
hasUnalignedBufferAccess()
bool llvm::GCNSubtarget::hasUnalignedBufferAccess () const inline
Definition at line 609 of file GCNSubtarget.h.
References UnalignedBufferAccess.
hasUnalignedBufferAccessEnabled()
bool llvm::GCNSubtarget::hasUnalignedBufferAccessEnabled () const inline
Definition at line 613 of file GCNSubtarget.h.
References UnalignedAccessMode, and UnalignedBufferAccess.
hasUnalignedDSAccess()
bool llvm::GCNSubtarget::hasUnalignedDSAccess () const inline
Definition at line 617 of file GCNSubtarget.h.
References UnalignedDSAccess.
hasUnalignedDSAccessEnabled()
bool llvm::GCNSubtarget::hasUnalignedDSAccessEnabled () const inline
Definition at line 621 of file GCNSubtarget.h.
References UnalignedAccessMode, and UnalignedDSAccess.
hasUnalignedScratchAccess()
bool llvm::GCNSubtarget::hasUnalignedScratchAccess () const inline
Definition at line 625 of file GCNSubtarget.h.
References UnalignedScratchAccess.
hasUnalignedScratchAccessEnabled()
bool llvm::GCNSubtarget::hasUnalignedScratchAccessEnabled () const inline
Definition at line 629 of file GCNSubtarget.h.
References UnalignedAccessMode, and UnalignedScratchAccess.
hasUnpackedD16VMem()
bool llvm::GCNSubtarget::hasUnpackedD16VMem () const inline
Definition at line 778 of file GCNSubtarget.h.
References HasUnpackedD16VMem.
hasUsableDivScaleConditionOutput()
bool llvm::GCNSubtarget::hasUsableDivScaleConditionOutput () const inline
Condition output from div_scale is usable.
Definition at line 513 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS.
hasUsableDSOffset()
bool llvm::GCNSubtarget::hasUsableDSOffset () const inline
True if the offset field of DS instructions works as expected.
On SI, the offset uses a 16-bit adder and does not always wrap properly.
Definition at line 504 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SEA_ISLANDS.
hasUserSGPRInit16Bug()
bool llvm::GCNSubtarget::hasUserSGPRInit16Bug () const inline
Definition at line 1224 of file GCNSubtarget.h.
References isWave32(), and UserSGPRInit16Bug.
hasVALUMaskWriteHazard()
bool llvm::GCNSubtarget::hasVALUMaskWriteHazard () const inline
Definition at line 1350 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
hasVALUPartialForwardingHazard()
bool llvm::GCNSubtarget::hasVALUPartialForwardingHazard () const inline
Definition at line 1334 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
hasVALUReadSGPRHazard()
bool llvm::GCNSubtarget::hasVALUReadSGPRHazard () const inline
Definition at line 1352 of file GCNSubtarget.h.
References GFX1250Insts, and GFX12Insts.
hasVALUTransUseHazard()
bool llvm::GCNSubtarget::hasVALUTransUseHazard () const inline
Definition at line 1338 of file GCNSubtarget.h.
References HasVALUTransUseHazard.
hasVcmpxExecWARHazard()
bool llvm::GCNSubtarget::hasVcmpxExecWARHazard () const inline
Definition at line 1284 of file GCNSubtarget.h.
References HasVcmpxExecWARHazard.
hasVcmpxPermlaneHazard()
bool llvm::GCNSubtarget::hasVcmpxPermlaneHazard () const inline
Definition at line 1264 of file GCNSubtarget.h.
References HasVcmpxPermlaneHazard.
hasVDecCoExecHazard()
bool llvm::GCNSubtarget::hasVDecCoExecHazard () const inline
Definition at line 1310 of file GCNSubtarget.h.
References GFX940Insts.
hasVectorMulU64()
bool llvm::GCNSubtarget::hasVectorMulU64 () const inline
Definition at line 1577 of file GCNSubtarget.h.
References GFX1250Insts.
hasVGPRIndexMode()
bool llvm::GCNSubtarget::hasVGPRIndexMode () const inline
Definition at line 1080 of file GCNSubtarget.h.
References HasVGPRIndexMode.
Referenced by useVGPRIndexMode().
hasVINTERPEncoding()
bool llvm::GCNSubtarget::hasVINTERPEncoding () const inline
Definition at line 715 of file GCNSubtarget.h.
References GFX11Insts, and hasGFX1250Insts().
hasVmemPrefInsts()
bool llvm::GCNSubtarget::hasVmemPrefInsts () const inline
Definition at line 1020 of file GCNSubtarget.h.
References HasVmemPrefInsts.
hasVMEMReadSGPRVALUDefHazard()
bool llvm::GCNSubtarget::hasVMEMReadSGPRVALUDefHazard () const inline
A read of an SGPR by a VMEM instruction requires 5 wait states when the SGPR was written by a VALU Instruction.
Definition at line 536 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
hasVMemToLDSLoad()
bool llvm::GCNSubtarget::hasVMemToLDSLoad () const inline
Definition at line 1398 of file GCNSubtarget.h.
References HasVMemToLDSLoad.
hasVMEMtoScalarWriteHazard()
bool llvm::GCNSubtarget::hasVMEMtoScalarWriteHazard () const inline
Definition at line 1268 of file GCNSubtarget.h.
References HasVMEMtoScalarWriteHazard.
hasVmemWriteVgprInOrder()
bool llvm::GCNSubtarget::hasVmemWriteVgprInOrder () const inline
Definition at line 1408 of file GCNSubtarget.h.
References HasVmemWriteVgprInOrder.
hasVOP3DPP()
bool llvm::GCNSubtarget::hasVOP3DPP () const inline
Definition at line 1328 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
hasVOP3Literal()
bool llvm::GCNSubtarget::hasVOP3Literal () const inline
Definition at line 1002 of file GCNSubtarget.h.
References HasVOP3Literal.
hasVOPD3()
bool llvm::GCNSubtarget::hasVOPD3 () const inline
Definition at line 1568 of file GCNSubtarget.h.
References GFX1250Insts.
hasVOPDInsts()
bool llvm::GCNSubtarget::hasVOPDInsts () const inline
Definition at line 1374 of file GCNSubtarget.h.
References HasVOPDInsts.
hasVscnt()
bool llvm::GCNSubtarget::hasVscnt () const inline
Definition at line 982 of file GCNSubtarget.h.
References HasVscnt.
hasWaitXCnt()
bool llvm::GCNSubtarget::hasWaitXCnt () const inline
Returns
true if the target has s_wait_xcnt insertion. Supported for GFX1250.
Definition at line 1469 of file GCNSubtarget.h.
References HasWaitXcnt.
hasXF32Insts()
bool llvm::GCNSubtarget::hasXF32Insts () const inline
Returns
true if the target has instructions with xf32 format support.
Definition at line 1421 of file GCNSubtarget.h.
References HasXF32Insts.
haveRoundOpsF64()
bool llvm::GCNSubtarget::haveRoundOpsF64 () const inline
Have v_trunc_f64, v_ceil_f64, v_rndne_f64.
Definition at line 583 of file GCNSubtarget.h.
References CIInsts.
initializeSubtargetDependencies()
GCNSubtarget & GCNSubtarget::initializeSubtargetDependencies (const Triple & TT, StringRef GPU, StringRef FS)
Definition at line 57 of file GCNSubtarget.cpp.
References llvm::AMDGPUSubtarget::AddressableLocalMemorySize, llvm::Triple::AMDHSA, assert(), llvm::dbgs(), FlatForGlobal, GCNSubtarget(), Gen, getGeneration(), llvm::AMDGPU::IsaInfo::getLocalMemorySize(), llvm::AMDGPUSubtarget::getWavefrontSizeLog2(), llvm::AMDGPUSubtarget::GFX10, llvm::AMDGPUSubtarget::GFX9, hasAddr64(), hasFlat(), llvm::AMDGPUSubtarget::HasFminFmaxLegacy, hasFP64(), llvm::AMDGPUSubtarget::HasSMulHi, llvm::AMDGPUSubtarget::INVALID, llvm::AMDGPUSubtarget::isAmdHsaOS(), LDSBankCount, LLVM_DEBUG, llvm::AMDGPUSubtarget::LocalMemorySize, MaxPrivateElementSize, ParseSubtargetFeatures(), llvm::AMDGPUSubtarget::SEA_ISLANDS, llvm::AMDGPUSubtarget::SOUTHERN_ISLANDS, TargetID, llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS, and llvm::AMDGPUSubtarget::WavefrontSizeLog2.
Referenced by GCNSubtarget().
isCuModeEnabled()
bool llvm::GCNSubtarget::isCuModeEnabled () const inline
Definition at line 655 of file GCNSubtarget.h.
References EnableCuMode.
isDynamicVGPREnabled()
bool llvm::GCNSubtarget::isDynamicVGPREnabled () const inline
Definition at line 1841 of file GCNSubtarget.h.
References DynamicVGPR.
Referenced by computeOccupancy(), and getMaxNumVGPRs().
isGFX11Plus()
bool llvm::GCNSubtarget::isGFX11Plus () const inline
Definition at line 377 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
isMesaGfxShader()
bool llvm::GCNSubtarget::isMesaGfxShader (const Function & F) const inline
Definition at line 783 of file GCNSubtarget.h.
References F, llvm::AMDGPUSubtarget::isMesa3DOS(), and llvm::AMDGPU::isShader().
isPreciseMemoryEnabled()
bool llvm::GCNSubtarget::isPreciseMemoryEnabled () const inline
Definition at line 659 of file GCNSubtarget.h.
References EnablePreciseMemory.
isTgSplitEnabled()
bool llvm::GCNSubtarget::isTgSplitEnabled () const inline
Definition at line 651 of file GCNSubtarget.h.
References EnableTgSplit.
isTrapHandlerEnabled()
bool llvm::GCNSubtarget::isTrapHandlerEnabled () const inline
Definition at line 643 of file GCNSubtarget.h.
References TrapHandler.
isWave32()
bool llvm::GCNSubtarget::isWave32 () const inline
Definition at line 1772 of file GCNSubtarget.h.
References llvm::AMDGPUSubtarget::getWavefrontSize().
Referenced by hasUserSGPRInit16Bug(), mirFileLoaded(), and supportsWaveWideBPermute().
isWave64()
bool llvm::GCNSubtarget::isWave64 () const inline
Definition at line 1776 of file GCNSubtarget.h.
References llvm::AMDGPUSubtarget::getWavefrontSize().
Referenced by lowerWaveShuffle().
isWaveSizeKnown()
bool llvm::GCNSubtarget::isWaveSizeKnown () const inline
Returns if the wavesize of this subtarget is known reliable.
This is false only for the a default target-cpu that does not have an explicit +wavefrontsize target feature.
Definition at line 1783 of file GCNSubtarget.h.
isXNACKEnabled()
bool llvm::GCNSubtarget::isXNACKEnabled () const inline
Definition at line 647 of file GCNSubtarget.h.
References TargetID.
Referenced by getBaseReservedNumSGPRs(), and needsConstrainedOpcode().
ldsRequiresM0Init()
bool llvm::GCNSubtarget::ldsRequiresM0Init () const inline
Return if most LDS instructions have an m0 use that require m0 to be initialized.
Definition at line 748 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
loadStoreOptEnabled()
bool llvm::GCNSubtarget::loadStoreOptEnabled () const inline
Definition at line 1216 of file GCNSubtarget.h.
References EnableLoadStoreOpt.
maxHardClauseLength()
unsigned llvm::GCNSubtarget::maxHardClauseLength () const inline
Returns
The maximum number of instructions that can be enclosed in an S_CLAUSE on the given subtarget, or 0 for targets that do not support that instruction.
Definition at line 1481 of file GCNSubtarget.h.
References MaxHardClauseLength.
mirFileLoaded()
void GCNSubtarget::mirFileLoaded (MachineFunction & MF) const override
Definition at line 376 of file GCNSubtarget.cpp.
References isWave32(), MBB, and MI.
needsAlignedVGPRs()
bool llvm::GCNSubtarget::needsAlignedVGPRs () const inline
Return if operations acting on VGPR tuples require even alignment.
Definition at line 1359 of file GCNSubtarget.h.
References RequiresAlignVGPR.
needsKernArgPreloadProlog()
bool llvm::GCNSubtarget::needsKernArgPreloadProlog () const inline
Definition at line 1611 of file GCNSubtarget.h.
References GFX1250Insts, and hasKernargPreload().
overridePostRASchedPolicy()
void GCNSubtarget::overridePostRASchedPolicy (MachineSchedPolicy & Policy, const SchedRegion & Region) const override
Definition at line 339 of file GCNSubtarget.cpp.
References llvm::dbgs(), F, llvm::Attribute::getValueAsString(), llvm::Attribute::isValid(), LLVM_DEBUG, llvm::MachineSchedPolicy::OnlyBottomUp, and llvm::MachineSchedPolicy::OnlyTopDown.
overrideSchedPolicy()
void GCNSubtarget::overrideSchedPolicy (MachineSchedPolicy & Policy, const SchedRegion & Region) const override
Definition at line 322 of file GCNSubtarget.cpp.
References enableSIScheduler(), llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, llvm::MachineSchedPolicy::ShouldTrackLaneMasks, and llvm::MachineSchedPolicy::ShouldTrackPressure.
ParseSubtargetFeatures()
void llvm::GCNSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Referenced by initializeSubtargetDependencies().
partialVCCWritesUpdateVCCZ()
bool llvm::GCNSubtarget::partialVCCWritesUpdateVCCZ () const inline
Writes to VCC_LO/VCC_HI update the VCCZ flag.
Definition at line 524 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX10.
privateMemoryResourceIsRangeChecked()
bool llvm::GCNSubtarget::privateMemoryResourceIsRangeChecked () const inline
Returns
If MUBUF instructions always perform range checking, even for buffer resources used for private memory access.
Definition at line 589 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
requiresCodeObjectV6()
bool llvm::GCNSubtarget::requiresCodeObjectV6 () const inline
Definition at line 1342 of file GCNSubtarget.h.
References RequiresCOV6.
requiresDisjointEarlyClobberAndUndef()
bool llvm::GCNSubtarget::requiresDisjointEarlyClobberAndUndef () const inline override
Definition at line 1846 of file GCNSubtarget.h.
requiresNopBeforeDeallocVGPRs()
bool llvm::GCNSubtarget::requiresNopBeforeDeallocVGPRs () const inline
Definition at line 1835 of file GCNSubtarget.h.
References GFX1250Insts.
requiresWaitIdleBeforeGetReg()
bool llvm::GCNSubtarget::requiresWaitIdleBeforeGetReg () const inline
Definition at line 1839 of file GCNSubtarget.h.
References GFX1250Insts.
requiresWaitsBeforeSystemScopeStores()
bool llvm::GCNSubtarget::requiresWaitsBeforeSystemScopeStores () const inline
Definition at line 1896 of file GCNSubtarget.h.
References RequiresWaitsBeforeSystemScopeStores.
requiresWaitXCntForSingleAccessInstructions()
bool llvm::GCNSubtarget::requiresWaitXCntForSingleAccessInstructions () const inline
Returns
true if the subtarget requires a wait for xcnt before VMEM accesses that must never be repeated in the event of a page fault/re-try. Atomic stores/rmw and all volatile accesses fall under this criteria.
Definition at line 1876 of file GCNSubtarget.h.
References GFX1250Insts.
setRegModeNeedsVNOPs()
bool llvm::GCNSubtarget::setRegModeNeedsVNOPs () const inline
Definition at line 1354 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX12, and GFX1250Insts.
setScalarizeGlobalBehavior()
void llvm::GCNSubtarget::setScalarizeGlobalBehavior (bool b) inline
Definition at line 1049 of file GCNSubtarget.h.
References ScalarizeGlobal.
shouldClusterStores()
bool llvm::GCNSubtarget::shouldClusterStores () const inline
Definition at line 1827 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX11.
supportsAgentScopeFineGrainedRemoteMemoryAtomics()
bool llvm::GCNSubtarget::supportsAgentScopeFineGrainedRemoteMemoryAtomics () const inline
Returns
true if atomic operations targeting fine-grained memory work correctly at device scope, in allocations in host or peer PCIe device memory.
Definition at line 962 of file GCNSubtarget.h.
References HasAgentScopeFineGrainedRemoteMemoryAtomics.
Referenced by globalMemoryFPAtomicIsLegal().
supportsBackOffBarrier()
bool llvm::GCNSubtarget::supportsBackOffBarrier () const inline
Returns
true if the target supports backing off of s_barrier instructions when an exception is raised.
Definition at line 605 of file GCNSubtarget.h.
References BackOffBarrier.
supportsBPermute()
bool llvm::GCNSubtarget::supportsBPermute () const inline
Definition at line 1900 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
supportsGetDoorbellID()
bool llvm::GCNSubtarget::supportsGetDoorbellID () const inline
Definition at line 497 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
supportsMinMaxDenormModes()
bool llvm::GCNSubtarget::supportsMinMaxDenormModes () const inline
Definition at line 558 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX9.
supportsWave32()
bool llvm::GCNSubtarget::supportsWave32 () const inline
Definition at line 1768 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::GFX10.
supportsWave64()
bool llvm::GCNSubtarget::supportsWave64 () const inline
Definition at line 1770 of file GCNSubtarget.h.
References hasGFX1250Insts().
supportsWaveWideBPermute()
bool llvm::GCNSubtarget::supportsWaveWideBPermute () const inline
Definition at line 1904 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX12, llvm::AMDGPUSubtarget::GFX9, and isWave32().
Referenced by lowerWaveShuffle().
supportsWGP()
bool llvm::GCNSubtarget::supportsWGP () const inline
Definition at line 413 of file GCNSubtarget.h.
References getGeneration(), llvm::AMDGPUSubtarget::GFX10, and GFX1250Insts.
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getHSAKernelProps().
unsafeDSOffsetFoldingEnabled()
bool llvm::GCNSubtarget::unsafeDSOffsetFoldingEnabled () const inline
Definition at line 508 of file GCNSubtarget.h.
References EnableUnsafeDSOffsetFolding.
useAA()
bool GCNSubtarget::useAA () const override
Definition at line 395 of file GCNSubtarget.cpp.
References UseAA.
useDS128()
bool llvm::GCNSubtarget::useDS128 () const inline
Returns
If target supports ds_read/write_b128 and user enables generation of ds_read/write_b128.
Definition at line 573 of file GCNSubtarget.h.
References CIInsts, and EnableDS128.
useFlatForGlobal()
bool llvm::GCNSubtarget::useFlatForGlobal () const inline
Definition at line 567 of file GCNSubtarget.h.
References FlatForGlobal.
usePRTStrictNull()
bool llvm::GCNSubtarget::usePRTStrictNull () const inline
Returns
If target requires PRT Struct NULL support (zero result registers for sparse texture support).
Definition at line 595 of file GCNSubtarget.h.
References EnablePRTStrictNull.
useVGPRBlockOpsForCSR()
bool llvm::GCNSubtarget::useVGPRBlockOpsForCSR () const inline
Definition at line 1344 of file GCNSubtarget.h.
References UseBlockVGPROpsForCSR.
useVGPRIndexMode()
bool GCNSubtarget::useVGPRIndexMode () const
Definition at line 391 of file GCNSubtarget.cpp.
References EnableVGPRIndexMode, hasMovrel(), and hasVGPRIndexMode().
vmemWriteNeedsExpWaitcnt()
bool llvm::GCNSubtarget::vmemWriteNeedsExpWaitcnt () const inline
Definition at line 1010 of file GCNSubtarget.h.
References getGeneration(), and llvm::AMDGPUSubtarget::SEA_ISLANDS.
zeroesHigh16BitsOfDest()
bool GCNSubtarget::zeroesHigh16BitsOfDest (unsigned Opcode) const
Returns if the result of this instruction with a 16-bit result returned in a 32-bit register implicitly zeroes the high 16-bits, rather than preserve the original value.
This list was mostly derived from experimentation.
Definition at line 224 of file GCNSubtarget.cpp.
References getGeneration(), llvm::AMDGPUSubtarget::GFX9, and llvm::AMDGPUSubtarget::VOLCANIC_ISLANDS.
Member Data Documentation
AddNoCarryInsts
bool llvm::GCNSubtarget::AddNoCarryInsts = false protected
Definition at line 235 of file GCNSubtarget.h.
Referenced by hasAddNoCarry().
AssemblerPermissiveWavesize
bool llvm::GCNSubtarget::AssemblerPermissiveWavesize = false protected
Definition at line 101 of file GCNSubtarget.h.
AutoWaitcntBeforeBarrier
bool llvm::GCNSubtarget::AutoWaitcntBeforeBarrier = false protected
Definition at line 76 of file GCNSubtarget.h.
Referenced by hasAutoWaitcntBeforeBarrier().
BackOffBarrier
bool llvm::GCNSubtarget::BackOffBarrier = false protected
Definition at line 77 of file GCNSubtarget.h.
Referenced by supportsBackOffBarrier().
CIInsts
bool llvm::GCNSubtarget::CIInsts = false protected
Definition at line 107 of file GCNSubtarget.h.
Referenced by hasDS96AndDS128(), hasDwordx3LoadStores(), hasGWSSemaReleaseAll(), haveRoundOpsF64(), and useDS128().
DumpCode
bool llvm::GCNSubtarget::DumpCode = false protected
Definition at line 100 of file GCNSubtarget.h.
Referenced by dumpCode().
DynamicVGPR
bool llvm::GCNSubtarget::DynamicVGPR = false protected
Definition at line 206 of file GCNSubtarget.h.
Referenced by isDynamicVGPREnabled().
DynamicVGPRBlockSize32
bool llvm::GCNSubtarget::DynamicVGPRBlockSize32 = false protected
Definition at line 207 of file GCNSubtarget.h.
Referenced by getDynamicVGPRBlockSize().
EnableCuMode
bool llvm::GCNSubtarget::EnableCuMode = false protected
Definition at line 90 of file GCNSubtarget.h.
Referenced by hasLDSMisalignedBug(), and isCuModeEnabled().
EnableDS128
bool llvm::GCNSubtarget::EnableDS128 = false protected
Definition at line 98 of file GCNSubtarget.h.
Referenced by useDS128().
EnableFlatScratch
bool llvm::GCNSubtarget::EnableFlatScratch = false protected
Definition at line 231 of file GCNSubtarget.h.
Referenced by enableFlatScratch().
EnableLoadStoreOpt
bool llvm::GCNSubtarget::EnableLoadStoreOpt = false protected
Definition at line 95 of file GCNSubtarget.h.
Referenced by loadStoreOptEnabled().
EnablePreciseMemory
bool llvm::GCNSubtarget::EnablePreciseMemory = false protected
Definition at line 92 of file GCNSubtarget.h.
Referenced by isPreciseMemoryEnabled().
EnablePRTStrictNull
bool llvm::GCNSubtarget::EnablePRTStrictNull = false protected
Definition at line 99 of file GCNSubtarget.h.
Referenced by usePRTStrictNull().
EnableSIScheduler
bool llvm::GCNSubtarget::EnableSIScheduler = false protected
Definition at line 97 of file GCNSubtarget.h.
Referenced by enableSIScheduler().
EnableSRAMECC
bool llvm::GCNSubtarget::EnableSRAMECC = false protected
Definition at line 213 of file GCNSubtarget.h.
EnableTgSplit
bool llvm::GCNSubtarget::EnableTgSplit = false protected
Definition at line 89 of file GCNSubtarget.h.
Referenced by isTgSplitEnabled().
EnableUnsafeDSOffsetFolding
bool llvm::GCNSubtarget::EnableUnsafeDSOffsetFolding = false protected
Definition at line 96 of file GCNSubtarget.h.
Referenced by unsafeDSOffsetFoldingEnabled().
EnableXNACK
bool llvm::GCNSubtarget::EnableXNACK = false protected
Definition at line 87 of file GCNSubtarget.h.
FastDenormalF32
bool llvm::GCNSubtarget::FastDenormalF32 = false protected
Definition at line 70 of file GCNSubtarget.h.
FeatureDisable
bool llvm::GCNSubtarget::FeatureDisable = false protected
Definition at line 306 of file GCNSubtarget.h.
FlatAddressSpace
bool llvm::GCNSubtarget::FlatAddressSpace = false protected
Definition at line 224 of file GCNSubtarget.h.
Referenced by hasFlatAddressSpace().
FlatForGlobal
bool llvm::GCNSubtarget::FlatForGlobal = false protected
Definition at line 75 of file GCNSubtarget.h.
Referenced by initializeSubtargetDependencies(), and useFlatForGlobal().
FlatGlobalInsts
bool llvm::GCNSubtarget::FlatGlobalInsts = false protected
Definition at line 226 of file GCNSubtarget.h.
Referenced by hasFlatGlobalInsts().
FlatGVSMode
bool llvm::GCNSubtarget::FlatGVSMode = false protected
Definition at line 228 of file GCNSubtarget.h.
Referenced by hasFlatGVSMode().
FlatInstOffsets
bool llvm::GCNSubtarget::FlatInstOffsets = false protected
Definition at line 225 of file GCNSubtarget.h.
Referenced by hasFlatInstOffsets().
FlatScratchInsts
bool llvm::GCNSubtarget::FlatScratchInsts = false protected
Definition at line 227 of file GCNSubtarget.h.
Referenced by hasFlatScratchInsts().
FMA
bool llvm::GCNSubtarget::FMA = false protected
Definition at line 105 of file GCNSubtarget.h.
Referenced by hasFMA().
FP64
bool llvm::GCNSubtarget::FP64 = false protected
Definition at line 104 of file GCNSubtarget.h.
Referenced by hasFP64(), and hasHWFP64().
FullRate64Ops
bool llvm::GCNSubtarget::FullRate64Ops = false protected
Definition at line 72 of file GCNSubtarget.h.
Referenced by hasFullRate64Ops().
Gen
unsigned llvm::GCNSubtarget::Gen = INVALID protected
Definition at line 64 of file GCNSubtarget.h.
Referenced by getGeneration(), and initializeSubtargetDependencies().
GFX10_3Insts
bool llvm::GCNSubtarget::GFX10_3Insts = false protected
Definition at line 117 of file GCNSubtarget.h.
Referenced by hasGFX10_3Insts().
GFX10_AEncoding
bool llvm::GCNSubtarget::GFX10_AEncoding = false protected
Definition at line 149 of file GCNSubtarget.h.
Referenced by hasGFX10_AEncoding().
GFX10_BEncoding
bool llvm::GCNSubtarget::GFX10_BEncoding = false protected
Definition at line 150 of file GCNSubtarget.h.
Referenced by hasAtomicCSub(), hasGFX10_BEncoding(), and hasGlobalAddTidInsts().
GFX10Insts
bool llvm::GCNSubtarget::GFX10Insts = false protected
Definition at line 113 of file GCNSubtarget.h.
GFX11Insts
bool llvm::GCNSubtarget::GFX11Insts = false protected
Definition at line 114 of file GCNSubtarget.h.
Referenced by hasCompressedExport(), hasDelayAlu(), hasDOTOpSelHazard(), hasFlatScratchSVSMode(), hasNullExportTarget(), hasSPackHL(), and hasVINTERPEncoding().
GFX1250Insts
bool llvm::GCNSubtarget::GFX1250Insts = false protected
Definition at line 116 of file GCNSubtarget.h.
Referenced by hasAddPC64Inst(), hasFlatScratchHiInB64InstHazard(), hasGetPCZeroExtension(), hasGFX1250Insts(), hasIntMinMax64(), hasLDSFPAtomicAddF64(), hasMadU64U32NoCarry(), hasMovB64(), hasPKF32InstsReplicatingLower32BitsOfScalarInput(), hasPkMinMax3Insts(), hasScaleOffset(), hasScratchBaseForwardingHazard(), hasSGetShaderCyclesInst(), hasSignedGVSOffset(), hasVALUReadSGPRHazard(), hasVectorMulU64(), hasVOPD3(), needsKernArgPreloadProlog(), requiresNopBeforeDeallocVGPRs(), requiresWaitIdleBeforeGetReg(), requiresWaitXCntForSingleAccessInstructions(), setRegModeNeedsVNOPs(), and supportsWGP().
GFX12Insts
bool llvm::GCNSubtarget::GFX12Insts = false protected
Definition at line 115 of file GCNSubtarget.h.
Referenced by hasCondSubInsts(), hasGetPCZeroExtension(), hasPrefetch(), and hasVALUReadSGPRHazard().
GFX7GFX8GFX9Insts
bool llvm::GCNSubtarget::GFX7GFX8GFX9Insts = false protected
Definition at line 118 of file GCNSubtarget.h.
GFX8Insts
bool llvm::GCNSubtarget::GFX8Insts = false protected
Definition at line 108 of file GCNSubtarget.h.
Referenced by hasLDSFPAtomicAddF32().
GFX90AInsts
bool llvm::GCNSubtarget::GFX90AInsts = false protected
Definition at line 110 of file GCNSubtarget.h.
Referenced by hasGFX90AInsts(), hasLDSFPAtomicAddF64(), hasPkMovB32(), and hasShift64HighRegBug().
GFX940Insts
bool llvm::GCNSubtarget::GFX940Insts = false protected
Definition at line 111 of file GCNSubtarget.h.
Referenced by hasDOTOpSelHazard(), hasDstSelForwardingHazard(), hasFlatScratchSVSMode(), hasGFX940Insts(), hasMovB64(), hasShift64HighRegBug(), hasTransForwardingHazard(), and hasVDecCoExecHazard().
GFX950Insts
bool llvm::GCNSubtarget::GFX950Insts = false protected
Definition at line 112 of file GCNSubtarget.h.
Referenced by hasCvtScaleForwardingHazard(), and hasGFX950Insts().
GFX9Insts
bool llvm::GCNSubtarget::GFX9Insts = false protected
Definition at line 109 of file GCNSubtarget.h.
Referenced by hasScalarMulHiInsts(), hasScalarPackInsts(), and hasSwap().
HalfRate64Ops
bool llvm::GCNSubtarget::HalfRate64Ops = false protected
Definition at line 71 of file GCNSubtarget.h.
Referenced by hasHalfRate64Ops().
Has1024AddressableVGPRs
bool llvm::GCNSubtarget::Has1024AddressableVGPRs = false protected
Definition at line 247 of file GCNSubtarget.h.
Referenced by has1024AddressableVGPRs().
Has1_5xVGPRs
bool llvm::GCNSubtarget::Has1_5xVGPRs = false protected
Definition at line 274 of file GCNSubtarget.h.
Referenced by has1_5xVGPRs().
Has45BitNumRecordsBufferResource
bool llvm::GCNSubtarget::Has45BitNumRecordsBufferResource = false protected
Definition at line 300 of file GCNSubtarget.h.
Referenced by has45BitNumRecordsBufferResource().
Has64BitLiterals
bool llvm::GCNSubtarget::Has64BitLiterals = false protected
Definition at line 246 of file GCNSubtarget.h.
Referenced by has64BitLiterals().
HasA16
bool llvm::GCNSubtarget::HasA16 = false protected
Definition at line 145 of file GCNSubtarget.h.
Referenced by hasA16().
HasAddMinMaxInsts
bool llvm::GCNSubtarget::HasAddMinMaxInsts = false protected
Definition at line 289 of file GCNSubtarget.h.
Referenced by hasAddMinMaxInsts().
HasAddSubU64Insts
bool llvm::GCNSubtarget::HasAddSubU64Insts = false protected
Definition at line 287 of file GCNSubtarget.h.
Referenced by hasAddSubU64Insts().
HasAgentScopeFineGrainedRemoteMemoryAtomics
bool llvm::GCNSubtarget::HasAgentScopeFineGrainedRemoteMemoryAtomics = false protected
Definition at line 197 of file GCNSubtarget.h.
Referenced by supportsAgentScopeFineGrainedRemoteMemoryAtomics().
HasApertureRegs
bool llvm::GCNSubtarget::HasApertureRegs = false protected
Definition at line 81 of file GCNSubtarget.h.
Referenced by hasApertureRegs().
HasArchitectedFlatScratch
bool llvm::GCNSubtarget::HasArchitectedFlatScratch = false protected
Definition at line 230 of file GCNSubtarget.h.
Referenced by flatScratchIsArchitected(), and getBaseReservedNumSGPRs().
HasArchitectedSGPRs
bool llvm::GCNSubtarget::HasArchitectedSGPRs = false protected
Definition at line 232 of file GCNSubtarget.h.
Referenced by hasArchitectedSGPRs().
HasAshrPkInsts
bool llvm::GCNSubtarget::HasAshrPkInsts = false protected
Definition at line 280 of file GCNSubtarget.h.
Referenced by hasAshrPkInsts().
HasAtomicBufferGlobalPkAddF16Insts
bool llvm::GCNSubtarget::HasAtomicBufferGlobalPkAddF16Insts = false protected
Definition at line 190 of file GCNSubtarget.h.
Referenced by hasAtomicBufferGlobalPkAddF16Insts().
HasAtomicBufferGlobalPkAddF16NoRtnInsts
bool llvm::GCNSubtarget::HasAtomicBufferGlobalPkAddF16NoRtnInsts = false protected
Definition at line 189 of file GCNSubtarget.h.
Referenced by hasAtomicBufferGlobalPkAddF16NoRtnInsts().
HasAtomicBufferPkAddBF16Inst
bool llvm::GCNSubtarget::HasAtomicBufferPkAddBF16Inst = false protected
Definition at line 193 of file GCNSubtarget.h.
Referenced by hasAtomicBufferPkAddBF16Inst().
HasAtomicCSubNoRtnInsts
bool llvm::GCNSubtarget::HasAtomicCSubNoRtnInsts = false protected
Definition at line 191 of file GCNSubtarget.h.
Referenced by hasAtomicCSubNoRtnInsts().
HasAtomicDsPkAdd16Insts
bool llvm::GCNSubtarget::HasAtomicDsPkAdd16Insts = false protected
Definition at line 184 of file GCNSubtarget.h.
Referenced by hasAtomicDsPkAdd16Insts().
HasAtomicFaddNoRtnInsts
bool llvm::GCNSubtarget::HasAtomicFaddNoRtnInsts = false protected
Definition at line 187 of file GCNSubtarget.h.
Referenced by hasAtomicFaddInsts(), and hasAtomicFaddNoRtnInsts().
HasAtomicFaddRtnInsts
bool llvm::GCNSubtarget::HasAtomicFaddRtnInsts = false protected
Definition at line 186 of file GCNSubtarget.h.
Referenced by hasAtomicFaddInsts(), and hasAtomicFaddRtnInsts().
HasAtomicFlatPkAdd16Insts
bool llvm::GCNSubtarget::HasAtomicFlatPkAdd16Insts = false protected
Definition at line 185 of file GCNSubtarget.h.
Referenced by hasAtomicFlatPkAdd16Insts().
HasAtomicFMinFMaxF32FlatInsts
bool llvm::GCNSubtarget::HasAtomicFMinFMaxF32FlatInsts = false protected
Definition at line 182 of file GCNSubtarget.h.
Referenced by hasAtomicFMinFMaxF32FlatInsts().
HasAtomicFMinFMaxF32GlobalInsts
bool llvm::GCNSubtarget::HasAtomicFMinFMaxF32GlobalInsts = false protected
Definition at line 180 of file GCNSubtarget.h.
Referenced by hasAtomicFMinFMaxF32GlobalInsts().
HasAtomicFMinFMaxF64FlatInsts
bool llvm::GCNSubtarget::HasAtomicFMinFMaxF64FlatInsts = false protected
Definition at line 183 of file GCNSubtarget.h.
Referenced by hasAtomicFMinFMaxF64FlatInsts().
HasAtomicFMinFMaxF64GlobalInsts
bool llvm::GCNSubtarget::HasAtomicFMinFMaxF64GlobalInsts = false protected
Definition at line 181 of file GCNSubtarget.h.
Referenced by hasAtomicFMinFMaxF64GlobalInsts().
HasAtomicGlobalPkAddBF16Inst
bool llvm::GCNSubtarget::HasAtomicGlobalPkAddBF16Inst = false protected
Definition at line 192 of file GCNSubtarget.h.
Referenced by hasAtomicGlobalPkAddBF16Inst().
HasBitOp3Insts
bool llvm::GCNSubtarget::HasBitOp3Insts = false protected
Definition at line 249 of file GCNSubtarget.h.
Referenced by hasBitOp3Insts().
HasBVHDualAndBVH8Insts
bool llvm::GCNSubtarget::HasBVHDualAndBVH8Insts = false protected
Definition at line 254 of file GCNSubtarget.h.
Referenced by hasBVHDualAndBVH8Insts().
HasClusters
bool llvm::GCNSubtarget::HasClusters = false protected
Definition at line 302 of file GCNSubtarget.h.
Referenced by hasClusters().
HasCubeInsts
bool llvm::GCNSubtarget::HasCubeInsts = false protected
Definition at line 170 of file GCNSubtarget.h.
Referenced by hasCubeInsts().
HasCvtFP8Vop1Bug
bool llvm::GCNSubtarget::HasCvtFP8Vop1Bug = false protected
Definition at line 178 of file GCNSubtarget.h.
Referenced by hasCvtFP8VOP1Bug().
HasCvtNormInsts
bool llvm::GCNSubtarget::HasCvtNormInsts = false protected
Definition at line 174 of file GCNSubtarget.h.
Referenced by hasCvtNormInsts().
HasCvtPkNormVOP2Insts
bool llvm::GCNSubtarget::HasCvtPkNormVOP2Insts = false protected
Definition at line 175 of file GCNSubtarget.h.
Referenced by hasCvtPkNormVOP2Insts().
HasCvtPkNormVOP3Insts
bool llvm::GCNSubtarget::HasCvtPkNormVOP3Insts = false protected
Definition at line 176 of file GCNSubtarget.h.
Referenced by hasCvtPkNormVOP3Insts().
HasDefaultComponentBroadcast
bool llvm::GCNSubtarget::HasDefaultComponentBroadcast = false protected
Definition at line 199 of file GCNSubtarget.h.
Referenced by hasDefaultComponentBroadcast().
HasDefaultComponentZero
bool llvm::GCNSubtarget::HasDefaultComponentZero = false protected
Definition at line 196 of file GCNSubtarget.h.
Referenced by hasDefaultComponentZero().
HasDLInsts
bool llvm::GCNSubtarget::HasDLInsts = false protected
Definition at line 151 of file GCNSubtarget.h.
Referenced by hasDLInsts().
HasDot10Insts
bool llvm::GCNSubtarget::HasDot10Insts = false protected
Definition at line 162 of file GCNSubtarget.h.
Referenced by hasDot10Insts().
HasDot11Insts
bool llvm::GCNSubtarget::HasDot11Insts = false protected
Definition at line 163 of file GCNSubtarget.h.
Referenced by hasDot11Insts().
HasDot12Insts
bool llvm::GCNSubtarget::HasDot12Insts = false protected
Definition at line 164 of file GCNSubtarget.h.
Referenced by hasDot12Insts().
HasDot13Insts
bool llvm::GCNSubtarget::HasDot13Insts = false protected
Definition at line 165 of file GCNSubtarget.h.
Referenced by hasDot13Insts().
HasDot1Insts
bool llvm::GCNSubtarget::HasDot1Insts = false protected
Definition at line 153 of file GCNSubtarget.h.
Referenced by hasDot1Insts().
HasDot2Insts
bool llvm::GCNSubtarget::HasDot2Insts = false protected
Definition at line 154 of file GCNSubtarget.h.
Referenced by hasDot2Insts().
HasDot3Insts
bool llvm::GCNSubtarget::HasDot3Insts = false protected
Definition at line 155 of file GCNSubtarget.h.
Referenced by hasDot3Insts().
HasDot4Insts
bool llvm::GCNSubtarget::HasDot4Insts = false protected
Definition at line 156 of file GCNSubtarget.h.
Referenced by hasDot4Insts().
HasDot5Insts
bool llvm::GCNSubtarget::HasDot5Insts = false protected
Definition at line 157 of file GCNSubtarget.h.
Referenced by hasDot5Insts().
HasDot6Insts
bool llvm::GCNSubtarget::HasDot6Insts = false protected
Definition at line 158 of file GCNSubtarget.h.
Referenced by hasDot6Insts().
HasDot7Insts
bool llvm::GCNSubtarget::HasDot7Insts = false protected
Definition at line 159 of file GCNSubtarget.h.
Referenced by hasDot7Insts().
HasDot8Insts
bool llvm::GCNSubtarget::HasDot8Insts = false protected
Definition at line 160 of file GCNSubtarget.h.
Referenced by hasDot8Insts().
HasDot9Insts
bool llvm::GCNSubtarget::HasDot9Insts = false protected
Definition at line 161 of file GCNSubtarget.h.
Referenced by hasDot9Insts().
HasDPALU_DPP
bool llvm::GCNSubtarget::HasDPALU_DPP = false protected
Definition at line 139 of file GCNSubtarget.h.
Referenced by hasDPALU_DPP().
HasDPP
bool llvm::GCNSubtarget::HasDPP = false protected
Definition at line 137 of file GCNSubtarget.h.
Referenced by hasDPP(), hasDPPBroadcasts(), and hasDPPWavefrontShifts().
HasDPP8
bool llvm::GCNSubtarget::HasDPP8 = false protected
Definition at line 138 of file GCNSubtarget.h.
Referenced by hasDPP8().
HasDPPSrc1SGPR
bool llvm::GCNSubtarget::HasDPPSrc1SGPR = false protected
Definition at line 140 of file GCNSubtarget.h.
Referenced by hasDPPSrc1SGPR().
HasEmulatedSystemScopeAtomics
bool llvm::GCNSubtarget::HasEmulatedSystemScopeAtomics = false protected
Definition at line 198 of file GCNSubtarget.h.
Referenced by hasEmulatedSystemScopeAtomics().
HasExtendedImageInsts
bool llvm::GCNSubtarget::HasExtendedImageInsts = false protected
Definition at line 143 of file GCNSubtarget.h.
Referenced by hasExtendedImageInsts().
HasFlatAtomicFaddF32Inst
bool llvm::GCNSubtarget::HasFlatAtomicFaddF32Inst = false protected
Definition at line 194 of file GCNSubtarget.h.
Referenced by hasFlatAtomicFaddF32Inst().
HasFlatBufferGlobalAtomicFaddF64Inst
bool llvm::GCNSubtarget::HasFlatBufferGlobalAtomicFaddF64Inst = false protected
Definition at line 195 of file GCNSubtarget.h.
Referenced by hasFlatBufferGlobalAtomicFaddF64Inst().
HasFlatSegmentOffsetBug
bool llvm::GCNSubtarget::HasFlatSegmentOffsetBug = false protected
Definition at line 269 of file GCNSubtarget.h.
Referenced by hasFlatSegmentOffsetBug().
HasFmacF64Inst
bool llvm::GCNSubtarget::HasFmacF64Inst = false protected
Definition at line 152 of file GCNSubtarget.h.
Referenced by hasFmacF64Inst().
HasFmaMixBF16Insts
bool llvm::GCNSubtarget::HasFmaMixBF16Insts = false protected
Definition at line 126 of file GCNSubtarget.h.
Referenced by hasFmaMixBF16Insts().
HasFmaMixInsts
bool llvm::GCNSubtarget::HasFmaMixInsts = false protected
Definition at line 125 of file GCNSubtarget.h.
Referenced by hasFmaMixInsts().
HasFP8ConversionInsts
bool llvm::GCNSubtarget::HasFP8ConversionInsts = false protected
Definition at line 168 of file GCNSubtarget.h.
Referenced by hasFP8ConversionInsts().
HasFP8E5M3Insts
bool llvm::GCNSubtarget::HasFP8E5M3Insts = false protected
Definition at line 177 of file GCNSubtarget.h.
Referenced by hasFP8E5M3Insts().
HasFP8Insts
bool llvm::GCNSubtarget::HasFP8Insts = false protected
Definition at line 167 of file GCNSubtarget.h.
Referenced by hasFP8Insts().
HasG16
bool llvm::GCNSubtarget::HasG16 = false protected
Definition at line 146 of file GCNSubtarget.h.
Referenced by hasG16().
HasGDS
bool llvm::GCNSubtarget::HasGDS = false protected
Definition at line 233 of file GCNSubtarget.h.
Referenced by hasGDS().
HasGetWaveIdInst
bool llvm::GCNSubtarget::HasGetWaveIdInst = false protected
Definition at line 218 of file GCNSubtarget.h.
Referenced by hasGetWaveIdInst().
HasGloballyAddressableScratch
bool llvm::GCNSubtarget::HasGloballyAddressableScratch = false protected
Definition at line 298 of file GCNSubtarget.h.
Referenced by hasGloballyAddressableScratch().
HasGWS
bool llvm::GCNSubtarget::HasGWS = false protected
Definition at line 234 of file GCNSubtarget.h.
Referenced by hasGWS().
HasIEEEMinimumMaximumInsts
bool llvm::GCNSubtarget::HasIEEEMinimumMaximumInsts = false protected
Definition at line 281 of file GCNSubtarget.h.
Referenced by hasIEEEMinimumMaximumInsts().
HasImageGather4D16Bug
bool llvm::GCNSubtarget::HasImageGather4D16Bug = false protected
Definition at line 271 of file GCNSubtarget.h.
Referenced by hasImageGather4D16Bug().
HasImageInsts
bool llvm::GCNSubtarget::HasImageInsts = false protected
Definition at line 142 of file GCNSubtarget.h.
Referenced by hasImageInsts().
HasImageStoreD16Bug
bool llvm::GCNSubtarget::HasImageStoreD16Bug = false protected
Definition at line 270 of file GCNSubtarget.h.
Referenced by hasImageStoreD16Bug().
HasInstFwdPrefetchBug
bool llvm::GCNSubtarget::HasInstFwdPrefetchBug = false protected
Definition at line 260 of file GCNSubtarget.h.
Referenced by hasInstFwdPrefetchBug().
HasIntClamp
bool llvm::GCNSubtarget::HasIntClamp = false protected
Definition at line 124 of file GCNSubtarget.h.
Referenced by hasIntClamp().
HasLdsBarrierArriveAtomic
bool llvm::GCNSubtarget::HasLdsBarrierArriveAtomic = false protected
Definition at line 292 of file GCNSubtarget.h.
Referenced by hasLdsBarrierArriveAtomic().
HasLdsBranchVmemWARHazard
bool llvm::GCNSubtarget::HasLdsBranchVmemWARHazard = false protected
Definition at line 265 of file GCNSubtarget.h.
Referenced by hasLdsBranchVmemWARHazard().
HasLerpInst
bool llvm::GCNSubtarget::HasLerpInst = false protected
Definition at line 171 of file GCNSubtarget.h.
Referenced by hasLerpInst().
HasLshlAddU64Inst
bool llvm::GCNSubtarget::HasLshlAddU64Inst = false protected
Definition at line 286 of file GCNSubtarget.h.
Referenced by hasLshlAddU64Inst().
HasMADIntraFwdBug
bool llvm::GCNSubtarget::HasMADIntraFwdBug = false protected
Definition at line 275 of file GCNSubtarget.h.
Referenced by hasMADIntraFwdBug().
HasMadU32Inst
bool llvm::GCNSubtarget::HasMadU32Inst = false protected
Definition at line 288 of file GCNSubtarget.h.
Referenced by hasMadU32Inst().
HasMAIInsts
bool llvm::GCNSubtarget::HasMAIInsts = false protected
Definition at line 166 of file GCNSubtarget.h.
Referenced by hasMAIInsts().
HasMcastLoadInsts
bool llvm::GCNSubtarget::HasMcastLoadInsts = false protected
Definition at line 169 of file GCNSubtarget.h.
Referenced by hasMcastLoadInsts().
HasMemoryAtomicFaddF32DenormalSupport
bool llvm::GCNSubtarget::HasMemoryAtomicFaddF32DenormalSupport = false protected
Definition at line 188 of file GCNSubtarget.h.
Referenced by hasMemoryAtomicFaddF32DenormalSupport().
HasMFMAInlineLiteralBug
bool llvm::GCNSubtarget::HasMFMAInlineLiteralBug = false protected
Definition at line 238 of file GCNSubtarget.h.
Referenced by hasMFMAInlineLiteralBug().
HasMin3Max3PKF16
bool llvm::GCNSubtarget::HasMin3Max3PKF16 = false protected
Definition at line 284 of file GCNSubtarget.h.
Referenced by hasMin3Max3PKF16().
HasMinimum3Maximum3F16
bool llvm::GCNSubtarget::HasMinimum3Maximum3F16 = false protected
Definition at line 283 of file GCNSubtarget.h.
Referenced by hasMinimum3Maximum3F16().
HasMinimum3Maximum3F32
bool llvm::GCNSubtarget::HasMinimum3Maximum3F32 = false protected
Definition at line 282 of file GCNSubtarget.h.
Referenced by hasMinimum3Maximum3F32().
HasMinimum3Maximum3PKF16
bool llvm::GCNSubtarget::HasMinimum3Maximum3PKF16 = false protected
Definition at line 285 of file GCNSubtarget.h.
Referenced by hasMinimum3Maximum3PKF16().
HasMovrel
bool llvm::GCNSubtarget::HasMovrel = false protected
Definition at line 127 of file GCNSubtarget.h.
Referenced by hasMovrel().
HasMSAALoadDstSelBug
bool llvm::GCNSubtarget::HasMSAALoadDstSelBug = false protected
Definition at line 272 of file GCNSubtarget.h.
Referenced by hasMSAALoadDstSelBug().
HasNoDataDepHazard
bool llvm::GCNSubtarget::HasNoDataDepHazard = false protected
Definition at line 223 of file GCNSubtarget.h.
Referenced by hasNoDataDepHazard().
HasNoSdstCMPX
bool llvm::GCNSubtarget::HasNoSdstCMPX = false protected
Definition at line 215 of file GCNSubtarget.h.
Referenced by hasNoSdstCMPX().
HasNSAClauseBug
bool llvm::GCNSubtarget::HasNSAClauseBug = false protected
Definition at line 267 of file GCNSubtarget.h.
Referenced by hasNSAClauseBug().
HasNSAEncoding
bool llvm::GCNSubtarget::HasNSAEncoding = false protected
Definition at line 147 of file GCNSubtarget.h.
Referenced by hasNSAEncoding().
HasNSAtoVMEMBug
bool llvm::GCNSubtarget::HasNSAtoVMEMBug = false protected
Definition at line 266 of file GCNSubtarget.h.
Referenced by hasNSAtoVMEMBug().
HasOffset3fBug
bool llvm::GCNSubtarget::HasOffset3fBug = false protected
Definition at line 268 of file GCNSubtarget.h.
Referenced by hasOffset3fBug().
HasPackedFP32Ops
bool llvm::GCNSubtarget::HasPackedFP32Ops = false protected
Definition at line 141 of file GCNSubtarget.h.
Referenced by hasPackedFP32Ops().
HasPackedTID
bool llvm::GCNSubtarget::HasPackedTID = false protected
Definition at line 241 of file GCNSubtarget.h.
Referenced by hasPackedTID().
HasPartialNSAEncoding
bool llvm::GCNSubtarget::HasPartialNSAEncoding = false protected
Definition at line 148 of file GCNSubtarget.h.
Referenced by hasPartialNSAEncoding().
HasPermlane16Swap
bool llvm::GCNSubtarget::HasPermlane16Swap = false protected
Definition at line 255 of file GCNSubtarget.h.
Referenced by hasPermlane16Swap().
HasPermlane32Swap
bool llvm::GCNSubtarget::HasPermlane32Swap = false protected
Definition at line 256 of file GCNSubtarget.h.
Referenced by hasPermlane32Swap().
HasPkAddMinMaxInsts
bool llvm::GCNSubtarget::HasPkAddMinMaxInsts = false protected
Definition at line 290 of file GCNSubtarget.h.
Referenced by hasPkAddMinMaxInsts().
HasPkFmacF16Inst
bool llvm::GCNSubtarget::HasPkFmacF16Inst = false protected
Definition at line 179 of file GCNSubtarget.h.
Referenced by hasPkFmacF16Inst().
HasPointSampleAccel
bool llvm::GCNSubtarget::HasPointSampleAccel = false protected
Definition at line 291 of file GCNSubtarget.h.
Referenced by hasPointSampleAccel().
HasPrivEnabledTrap2NopBug
bool llvm::GCNSubtarget::HasPrivEnabledTrap2NopBug = false protected
Definition at line 273 of file GCNSubtarget.h.
Referenced by hasPrivEnabledTrap2NopBug().
HasPrngInst
bool llvm::GCNSubtarget::HasPrngInst = false protected
Definition at line 253 of file GCNSubtarget.h.
Referenced by hasPrngInst().
HasPseudoScalarTrans
bool llvm::GCNSubtarget::HasPseudoScalarTrans = false protected
Definition at line 244 of file GCNSubtarget.h.
Referenced by hasPseudoScalarTrans().
HasQsadInsts
bool llvm::GCNSubtarget::HasQsadInsts = false protected
Definition at line 173 of file GCNSubtarget.h.
Referenced by hasQsadInsts().
HasR128A16
bool llvm::GCNSubtarget::HasR128A16 = false protected
Definition at line 144 of file GCNSubtarget.h.
Referenced by hasR128A16().
HasRequiredExportPriority
bool llvm::GCNSubtarget::HasRequiredExportPriority = false protected
Definition at line 278 of file GCNSubtarget.h.
Referenced by hasRequiredExportPriority().
HasRestrictedSOffset
bool llvm::GCNSubtarget::HasRestrictedSOffset = false protected
Definition at line 245 of file GCNSubtarget.h.
Referenced by hasRestrictedSOffset().
HasSadInsts
bool llvm::GCNSubtarget::HasSadInsts = false protected
Definition at line 172 of file GCNSubtarget.h.
Referenced by hasSadInsts().
HasSafeCUPrefetch
bool llvm::GCNSubtarget::HasSafeCUPrefetch = false protected
Definition at line 263 of file GCNSubtarget.h.
Referenced by hasSafeCUPrefetch().
HasSafeSmemPrefetch
bool llvm::GCNSubtarget::HasSafeSmemPrefetch = false protected
Definition at line 262 of file GCNSubtarget.h.
Referenced by hasSafeSmemPrefetch().
HasSALUFloatInsts
bool llvm::GCNSubtarget::HasSALUFloatInsts = false protected
Definition at line 243 of file GCNSubtarget.h.
Referenced by hasSALUFloatInsts().
HasScalarAtomics
bool llvm::GCNSubtarget::HasScalarAtomics = false protected
Definition at line 131 of file GCNSubtarget.h.
Referenced by hasScalarAtomics().
HasScalarDwordx3Loads
bool llvm::GCNSubtarget::HasScalarDwordx3Loads = false protected
Definition at line 129 of file GCNSubtarget.h.
Referenced by hasScalarDwordx3Loads().
HasScalarStores
bool llvm::GCNSubtarget::HasScalarStores = false protected
Definition at line 130 of file GCNSubtarget.h.
Referenced by hasScalarStores().
HasSDWAMac
bool llvm::GCNSubtarget::HasSDWAMac = false protected
Definition at line 135 of file GCNSubtarget.h.
Referenced by hasSDWAMac().
HasSDWAOmod
bool llvm::GCNSubtarget::HasSDWAOmod = false protected
Definition at line 132 of file GCNSubtarget.h.
Referenced by hasSDWAOmod().
HasSDWAOutModsVOPC
bool llvm::GCNSubtarget::HasSDWAOutModsVOPC = false protected
Definition at line 136 of file GCNSubtarget.h.
Referenced by hasSDWAOutModsVOPC().
HasSDWAScalar
bool llvm::GCNSubtarget::HasSDWAScalar = false protected
Definition at line 133 of file GCNSubtarget.h.
Referenced by hasSDWAScalar().
HasSDWASdst
bool llvm::GCNSubtarget::HasSDWASdst = false protected
Definition at line 134 of file GCNSubtarget.h.
Referenced by hasSDWASdst().
HasSetPrioIncWgInst
bool llvm::GCNSubtarget::HasSetPrioIncWgInst = false protected
Definition at line 293 of file GCNSubtarget.h.
Referenced by hasSetPrioIncWgInst().
HasSetregVGPRMSBFixup
bool llvm::GCNSubtarget::HasSetregVGPRMSBFixup = false protected
Definition at line 248 of file GCNSubtarget.h.
Referenced by hasSetregVGPRMSBFixup().
HasShaderCyclesHiLoRegisters
bool llvm::GCNSubtarget::HasShaderCyclesHiLoRegisters = false protected
Definition at line 221 of file GCNSubtarget.h.
Referenced by hasShaderCyclesHiLoRegisters().
HasShaderCyclesRegister
bool llvm::GCNSubtarget::HasShaderCyclesRegister = false protected
Definition at line 220 of file GCNSubtarget.h.
Referenced by hasShaderCyclesRegister().
HasSMemRealTime
bool llvm::GCNSubtarget::HasSMemRealTime = false protected
Definition at line 123 of file GCNSubtarget.h.
Referenced by hasSMemRealTime().
HasSMemTimeInst
bool llvm::GCNSubtarget::HasSMemTimeInst = false protected
Definition at line 219 of file GCNSubtarget.h.
Referenced by hasSMemTimeInst().
HasSMEMtoVectorWriteHazard
bool llvm::GCNSubtarget::HasSMEMtoVectorWriteHazard = false protected
Definition at line 259 of file GCNSubtarget.h.
Referenced by hasSMEMtoVectorWriteHazard().
HasSWakeupBarrier
bool llvm::GCNSubtarget::HasSWakeupBarrier = false protected
Definition at line 294 of file GCNSubtarget.h.
Referenced by hasSWakeupBarrier().
HasTanhInsts
bool llvm::GCNSubtarget::HasTanhInsts = false protected
Definition at line 250 of file GCNSubtarget.h.
Referenced by hasTanhInsts().
HasTensorCvtLutInsts
bool llvm::GCNSubtarget::HasTensorCvtLutInsts = false protected
Definition at line 251 of file GCNSubtarget.h.
Referenced by hasTensorCvtLutInsts().
HasTransposeLoadF4F6Insts
bool llvm::GCNSubtarget::HasTransposeLoadF4F6Insts = false protected
Definition at line 252 of file GCNSubtarget.h.
Referenced by hasTransposeLoadF4F6Insts().
HasUnpackedD16VMem
bool llvm::GCNSubtarget::HasUnpackedD16VMem = false protected
Definition at line 236 of file GCNSubtarget.h.
Referenced by hasUnpackedD16VMem().
HasVALUTransUseHazard
bool llvm::GCNSubtarget::HasVALUTransUseHazard = false protected
Definition at line 277 of file GCNSubtarget.h.
Referenced by hasVALUTransUseHazard().
HasVcmpxExecWARHazard
bool llvm::GCNSubtarget::HasVcmpxExecWARHazard = false protected
Definition at line 264 of file GCNSubtarget.h.
Referenced by hasVcmpxExecWARHazard().
HasVcmpxPermlaneHazard
bool llvm::GCNSubtarget::HasVcmpxPermlaneHazard = false protected
Definition at line 257 of file GCNSubtarget.h.
Referenced by hasVcmpxPermlaneHazard().
HasVGPRIndexMode
bool llvm::GCNSubtarget::HasVGPRIndexMode = false protected
Definition at line 128 of file GCNSubtarget.h.
Referenced by hasVGPRIndexMode().
HasVmemPrefInsts
bool llvm::GCNSubtarget::HasVmemPrefInsts = false protected
Definition at line 261 of file GCNSubtarget.h.
Referenced by hasVmemPrefInsts().
HasVMemToLDSLoad
bool llvm::GCNSubtarget::HasVMemToLDSLoad = false protected
Definition at line 208 of file GCNSubtarget.h.
Referenced by hasVMemToLDSLoad().
HasVMEMtoScalarWriteHazard
bool llvm::GCNSubtarget::HasVMEMtoScalarWriteHazard = false protected
Definition at line 258 of file GCNSubtarget.h.
Referenced by hasVMEMtoScalarWriteHazard().
HasVmemWriteVgprInOrder
bool llvm::GCNSubtarget::HasVmemWriteVgprInOrder = false protected
Definition at line 279 of file GCNSubtarget.h.
Referenced by hasVmemWriteVgprInOrder().
HasVOP3Literal
bool llvm::GCNSubtarget::HasVOP3Literal = false protected
Definition at line 222 of file GCNSubtarget.h.
Referenced by hasVOP3Literal().
HasVOPDInsts
bool llvm::GCNSubtarget::HasVOPDInsts = false protected
Definition at line 276 of file GCNSubtarget.h.
Referenced by hasVOPDInsts().
HasVscnt
bool llvm::GCNSubtarget::HasVscnt = false protected
Definition at line 216 of file GCNSubtarget.h.
Referenced by hasVscnt().
HasWaitXcnt
bool llvm::GCNSubtarget::HasWaitXcnt = false protected
Definition at line 217 of file GCNSubtarget.h.
Referenced by hasWaitXCnt().
HasXF32Insts
bool llvm::GCNSubtarget::HasXF32Insts = false protected
Definition at line 200 of file GCNSubtarget.h.
Referenced by hasXF32Insts().
InstrItins
InstrItineraryData llvm::GCNSubtarget::InstrItins protected
Definition at line 65 of file GCNSubtarget.h.
Referenced by GCNSubtarget(), and getInstrItineraryData().
KernargPreload
bool llvm::GCNSubtarget::KernargPreload = false protected
Definition at line 83 of file GCNSubtarget.h.
Referenced by hasKernargPreload().
LDSBankCount
int llvm::GCNSubtarget::LDSBankCount = 0 protected
Definition at line 66 of file GCNSubtarget.h.
Referenced by getLDSBankCount(), and initializeSubtargetDependencies().
LDSMisalignedBug
bool llvm::GCNSubtarget::LDSMisalignedBug = false protected
Definition at line 237 of file GCNSubtarget.h.
Referenced by hasLDSMisalignedBug().
MaxHardClauseLength
unsigned llvm::GCNSubtarget::MaxHardClauseLength = 0 protected
The maximum number of instructions that may be placed within an S_CLAUSE, which is one greater than the maximum argument to S_CLAUSE.
A value of 0 indicates a lack of S_CLAUSE support.
Definition at line 204 of file GCNSubtarget.h.
Referenced by hasHardClauses(), and maxHardClauseLength().
MaxPrivateElementSize
unsigned llvm::GCNSubtarget::MaxPrivateElementSize = 0 protected
Definition at line 67 of file GCNSubtarget.h.
Referenced by getMaxPrivateElementSize(), and initializeSubtargetDependencies().
MIMG_R128
bool llvm::GCNSubtarget::MIMG_R128 = false protected
Definition at line 106 of file GCNSubtarget.h.
Referenced by hasMIMG_R128().
NegativeScratchOffsetBug
bool llvm::GCNSubtarget::NegativeScratchOffsetBug = false protected
Definition at line 121 of file GCNSubtarget.h.
Referenced by hasNegativeScratchOffsetBug().
NegativeUnalignedScratchOffsetBug
bool llvm::GCNSubtarget::NegativeUnalignedScratchOffsetBug = false protected
Definition at line 122 of file GCNSubtarget.h.
Referenced by hasNegativeUnalignedScratchOffsetBug().
RelaxedBufferOOBMode
bool llvm::GCNSubtarget::RelaxedBufferOOBMode = false protected
Definition at line 80 of file GCNSubtarget.h.
Referenced by hasRelaxedBufferOOBMode().
RequiresAlignVGPR
bool llvm::GCNSubtarget::RequiresAlignVGPR = false protected
Definition at line 209 of file GCNSubtarget.h.
Referenced by needsAlignedVGPRs().
RequiresCOV6
bool llvm::GCNSubtarget::RequiresCOV6 = false protected
Definition at line 296 of file GCNSubtarget.h.
Referenced by requiresCodeObjectV6().
RequiresWaitsBeforeSystemScopeStores
bool llvm::GCNSubtarget::RequiresWaitsBeforeSystemScopeStores = false protected
Definition at line 303 of file GCNSubtarget.h.
Referenced by requiresWaitsBeforeSystemScopeStores().
ScalarFlatScratchInsts
bool llvm::GCNSubtarget::ScalarFlatScratchInsts = false protected
Definition at line 229 of file GCNSubtarget.h.
Referenced by hasScalarFlatScratchInsts().
ScalarizeGlobal
bool llvm::GCNSubtarget::ScalarizeGlobal = false protected
Definition at line 242 of file GCNSubtarget.h.
Referenced by getScalarizeGlobalBehavior(), and setScalarizeGlobalBehavior().
SGPRInitBug
bool llvm::GCNSubtarget::SGPRInitBug = false protected
Definition at line 119 of file GCNSubtarget.h.
Referenced by hasSGPRInitBug().
SupportsSRAMECC
bool llvm::GCNSubtarget::SupportsSRAMECC = false protected
Definition at line 205 of file GCNSubtarget.h.
SupportsXNACK
bool llvm::GCNSubtarget::SupportsXNACK = false protected
Definition at line 82 of file GCNSubtarget.h.
TargetID
AMDGPU::IsaInfo::AMDGPUTargetID llvm::GCNSubtarget::TargetID protected
Definition at line 63 of file GCNSubtarget.h.
Referenced by d16PreservesUnusedBits(), GCNSubtarget(), getTargetID(), initializeSubtargetDependencies(), and isXNACKEnabled().
TrapHandler
bool llvm::GCNSubtarget::TrapHandler = false protected
Definition at line 91 of file GCNSubtarget.h.
Referenced by isTrapHandlerEnabled().
UnalignedAccessMode
bool llvm::GCNSubtarget::UnalignedAccessMode = false protected
Definition at line 79 of file GCNSubtarget.h.
Referenced by hasUnalignedAccessMode(), hasUnalignedBufferAccessEnabled(), hasUnalignedDSAccessEnabled(), and hasUnalignedScratchAccessEnabled().
UnalignedBufferAccess
bool llvm::GCNSubtarget::UnalignedBufferAccess = false protected
Definition at line 239 of file GCNSubtarget.h.
Referenced by hasUnalignedBufferAccess(), and hasUnalignedBufferAccessEnabled().
UnalignedDSAccess
bool llvm::GCNSubtarget::UnalignedDSAccess = false protected
Definition at line 240 of file GCNSubtarget.h.
Referenced by hasUnalignedDSAccess(), and hasUnalignedDSAccessEnabled().
UnalignedScratchAccess
bool llvm::GCNSubtarget::UnalignedScratchAccess = false protected
Definition at line 78 of file GCNSubtarget.h.
Referenced by hasUnalignedScratchAccess(), and hasUnalignedScratchAccessEnabled().
UseBlockVGPROpsForCSR
bool llvm::GCNSubtarget::UseBlockVGPROpsForCSR = false protected
Definition at line 297 of file GCNSubtarget.h.
Referenced by useVGPRBlockOpsForCSR().
UserSGPRInit16Bug
bool llvm::GCNSubtarget::UserSGPRInit16Bug = false protected
Definition at line 120 of file GCNSubtarget.h.
Referenced by hasUserSGPRInit16Bug().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSubtarget.h
lib/Target/AMDGPU/GCNSubtarget.cpp