LLVM: llvm::DbgValueRangeTable Class Reference
llvm::DbgValueRangeTable Class Reference
Utility class used to find and store the live debug ranges for variables in a module.
#include "llvm/Transforms/Utils/DebugSSAUpdater.h"
Public Member Functions
LLVM_ABI_FOR_TEST void addVariable (Function *F, DebugVariableAggregate DVA)
bool hasVariableEntry (DebugVariableAggregate DVA) const
bool hasSingleLocEntry (DebugVariableAggregate DVA) const
ArrayRef< DbgRangeEntry > getVariableRanges (DebugVariableAggregate DVA)
DbgValueDef getSingleLoc (DebugVariableAggregate DVA)
void printValues (DebugVariableAggregate DVA, raw_ostream &OS)
Detailed Description
Utility class used to find and store the live debug ranges for variables in a module.
This class uses the DebugSSAUpdater for each variable added with addVariable to find either a single-location value, e.g. #dbg_declare, or a set of live value ranges corresponding to the set of #dbg_value records.
Definition at line 340 of file DebugSSAUpdater.h.
Member Function Documentation
addVariable()
void DbgValueRangeTable::addVariable (Function * F, DebugVariableAggregate DVA)
Definition at line 229 of file DebugSSAUpdater.cpp.
References assert(), llvm::cast(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), F, llvm::filterDbgVars(), llvm::for_each(), llvm::DebugVariable::getInlinedAt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::DILocalVariable::getScope(), llvm::DebugVariable::getVariable(), I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), isContained(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
getSingleLoc()
DbgValueDef llvm::DbgValueRangeTable::getSingleLoc (DebugVariableAggregate DVA) inline
Definition at line 357 of file DebugSSAUpdater.h.
getVariableRanges()
ArrayRef< DbgRangeEntry > llvm::DbgValueRangeTable::getVariableRanges (DebugVariableAggregate DVA) inline
Definition at line 354 of file DebugSSAUpdater.h.
hasSingleLocEntry()
bool llvm::DbgValueRangeTable::hasSingleLocEntry (DebugVariableAggregate DVA) const inline
Definition at line 351 of file DebugSSAUpdater.h.
Referenced by printValues().
hasVariableEntry()
bool llvm::DbgValueRangeTable::hasVariableEntry (DebugVariableAggregate DVA) const inline
Definition at line 347 of file DebugSSAUpdater.h.
Referenced by printValues().
printValues()
void DbgValueRangeTable::printValues (DebugVariableAggregate DVA, raw_ostream & OS)
Definition at line 345 of file DebugSSAUpdater.cpp.
References llvm::DebugVariable::getInlinedAt(), llvm::DIVariable::getName(), llvm::DebugVariable::getVariable(), hasSingleLocEntry(), and hasVariableEntry().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/DebugSSAUpdater.h
lib/Transforms/Utils/DebugSSAUpdater.cpp