LLVM: llvm::AMDGPUArgumentUsageInfo Class Reference
llvm::AMDGPUArgumentUsageInfo Class Reference
#include "Target/AMDGPU/AMDGPUArgumentUsageInfo.h"
Public Member Functions
void print (raw_ostream &OS, const Module *M=nullptr) const
void clear ()
void setFuncArgInfo (const Function &F, const AMDGPUFunctionArgInfo &ArgInfo)
const AMDGPUFunctionArgInfo & lookupFuncArgInfo (const Function &F) const
bool invalidate (Module &M, const PreservedAnalyses &PA, ModuleAnalysisManager::Invalidator &Inv)
Static Public Attributes
static const AMDGPUFunctionArgInfo ExternFunctionInfo
static const AMDGPUFunctionArgInfo FixedABIFunctionInfo = AMDGPUFunctionArgInfo::fixedABILayout()
Detailed Description
Definition at line 175 of file AMDGPUArgumentUsageInfo.h.
Member Function Documentation
clear()
void llvm::AMDGPUArgumentUsageInfo::clear () inline
Definition at line 185 of file AMDGPUArgumentUsageInfo.h.
invalidate()
bool AMDGPUArgumentUsageInfo::invalidate (Module & M, const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator & Inv)
Definition at line 80 of file AMDGPUArgumentUsageInfo.cpp.
References llvm::PreservedAnalyses::getChecker().
lookupFuncArgInfo()
const AMDGPUFunctionArgInfo & AMDGPUArgumentUsageInfo::lookupFuncArgInfo (const Function & F) const
Definition at line 185 of file AMDGPUArgumentUsageInfo.cpp.
References F, FixedABIFunctionInfo, and I.
print()
void AMDGPUArgumentUsageInfo::print (raw_ostream & OS, const Module * M = nullptr) const
Definition at line 54 of file AMDGPUArgumentUsageInfo.cpp.
setFuncArgInfo()
void llvm::AMDGPUArgumentUsageInfo::setFuncArgInfo (const Function & F, const AMDGPUFunctionArgInfo & ArgInfo) inline
Definition at line 187 of file AMDGPUArgumentUsageInfo.h.
References F.
Referenced by llvm::SITargetLowering::LowerFormalArguments().
Member Data Documentation
ExternFunctionInfo
const AMDGPUFunctionArgInfo llvm::AMDGPUArgumentUsageInfo::ExternFunctionInfo static
Definition at line 180 of file AMDGPUArgumentUsageInfo.h.
FixedABIFunctionInfo
const AMDGPUFunctionArgInfo AMDGPUArgumentUsageInfo::FixedABIFunctionInfo = AMDGPUFunctionArgInfo::fixedABILayout() static
Definition at line 181 of file AMDGPUArgumentUsageInfo.h.
Referenced by lookupFuncArgInfo(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::SITargetLowering::passSpecialInputs(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.h
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.cpp