LLVM: llvm::vfs::OnDiskOutputBackend Class Reference
llvm::vfs::OnDiskOutputBackend Class Reference
An output backend that creates files on disk, wrapping APIs in sys::fs.
#include "llvm/Support/VirtualOutputBackends.h"
Classes
struct OutputSettings
On disk output settings.
Public Member Functions
Error makeAbsolute (SmallVectorImpl< char > &Path) const
Resolve an absolute path.
IntrusiveRefCntPtr< OnDiskOutputBackend > clone () const
OnDiskOutputBackend ()=default
Public Member Functions inherited from llvm::vfs::OutputBackend
IntrusiveRefCntPtr< OutputBackend > clone () const
Get a backend that points to the same destination as this one but that has independent settings.
LLVM_ABI Expected< OutputFile > createFile (const Twine &Path, std::optional< OutputConfig > Config=std::nullopt)
Create a file.
virtual ~OutputBackend ()=default
Public Member Functions inherited from llvm::RefCountedBase< OutputBackend >
unsigned UseCount () const
void Retain () const
void Release () const
Public Attributes
OutputSettings Settings
Settings for this backend.
Protected Member Functions
IntrusiveRefCntPtr< OutputBackend > cloneImpl () const override
Must be thread-safe.
LLVM_ABI Expected< std::unique_ptr< OutputFileImpl > > createFileImpl (StringRef Path, std::optional< OutputConfig > Config) override
Create a file for Path.
Protected Member Functions inherited from llvm::vfs::OutputBackend
OutputBackend ()=default
Protected Member Functions inherited from llvm::RefCountedBase< OutputBackend >
RefCountedBase ()=default
RefCountedBase & operator= (const RefCountedBase &)=delete
~RefCountedBase ()
Detailed Description
An output backend that creates files on disk, wrapping APIs in sys::fs.
Definition at line 79 of file VirtualOutputBackends.h.
Constructor & Destructor Documentation
OnDiskOutputBackend()
llvm::vfs::OnDiskOutputBackend::OnDiskOutputBackend () default
Member Function Documentation
clone()
IntrusiveRefCntPtr< OnDiskOutputBackend > llvm::vfs::OnDiskOutputBackend::clone () const inline
Definition at line 108 of file VirtualOutputBackends.h.
References llvm::makeIntrusiveRefCnt(), and Settings.
Referenced by cloneImpl().
cloneImpl()
IntrusiveRefCntPtr< OutputBackend > llvm::vfs::OnDiskOutputBackend::cloneImpl () const inline override protected virtual
Must be thread-safe.
Virtual function has a different name than clone() so that implementations can override the return value.
Implements llvm::vfs::OutputBackend.
Definition at line 83 of file VirtualOutputBackends.h.
References clone().
createFileImpl()
Expected< std::unique_ptr< OutputFileImpl > > OnDiskOutputBackend::createFileImpl (StringRef Path, std::optional< OutputConfig > Config) override protected virtual
Create a file for Path.
Must be thread-safe.
Precondition
Config is valid or std::nullopt.
Implements llvm::vfs::OutputBackend.
Definition at line 607 of file VirtualOutputBackends.cpp.
References makeAbsolute(), llvm::sys::sandbox::scopedDisable(), and Settings.
makeAbsolute()
Error OnDiskOutputBackend::makeAbsolute (SmallVectorImpl< char > & Path) const
Resolve an absolute path.
Definition at line 599 of file VirtualOutputBackends.cpp.
References llvm::vfs::convertToOutputError(), llvm::sys::fs::make_absolute(), and llvm::sys::sandbox::scopedDisable().
Referenced by createFileImpl().
Member Data Documentation
Settings
OutputSettings llvm::vfs::OnDiskOutputBackend::Settings
Settings for this backend.
Access is not thread-safe.
Definition at line 119 of file VirtualOutputBackends.h.
Referenced by clone(), and createFileImpl().
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualOutputBackends.h
lib/Support/VirtualOutputBackends.cpp