LLVM: llvm::object::CompressedOffloadBundle Class Reference
llvm::object::CompressedOffloadBundle Class Reference
#include "llvm/Object/OffloadBundle.h"
Classes
struct CompressedBundleHeader
Static Public Member Functions
static llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > compress (llvm::compression::Params P, const llvm::MemoryBuffer &Input, uint16_t Version, raw_ostream *VerboseStream=nullptr)
static llvm::Expected< std::unique_ptr< llvm::MemoryBuffer > > decompress (const llvm::MemoryBuffer &Input, raw_ostream *VerboseStream=nullptr)
Static Public Attributes
static const uint16_t DefaultVersion = 3
Detailed Description
Definition at line 47 of file OffloadBundle.h.
Member Function Documentation
compress()
Expected< std::unique_ptr< MemoryBuffer > > CompressedOffloadBundle::compress (llvm::compression::Params P, const llvm::MemoryBuffer & Input, uint16_t Version, raw_ostream * VerboseStream = nullptr) static
Definition at line 297 of file OffloadBundle.cpp.
References llvm::compression::compress(), llvm::createStringError(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::MD5::final(), llvm::format(), llvm::format_hex(), formatWithCommas(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::Timer::getTotalTime(), llvm::TimeRecord::getWallTime(), llvm::compression::zlib::isAvailable(), llvm::compression::zstd::isAvailable(), OffloadBundlerTimerGroup, P, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Timer::startTimer(), llvm::Timer::stopTimer(), llvm::MD5::update(), llvm::Version, llvm::raw_ostream::write(), and llvm::compression::Zstd.
decompress()
Expected< std::unique_ptr< MemoryBuffer > > CompressedOffloadBundle::decompress (const llvm::MemoryBuffer & Input, raw_ostream * VerboseStream = nullptr) static
Definition at line 511 of file OffloadBundle.cpp.
References llvm::object::CompressedOffloadBundle::CompressedBundleHeader::CompressionFormat, llvm::createStringError(), llvm::compression::decompress(), llvm::object::CompressedOffloadBundle::CompressedBundleHeader::FileSize, llvm::MD5::final(), llvm::format(), llvm::format_hex(), formatWithCommas(), getHeaderSize(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::Timer::getTotalTime(), llvm::TimeRecord::getWallTime(), llvm::object::CompressedOffloadBundle::CompressedBundleHeader::Hash, llvm::identify_magic(), llvm::file_magic::offload_bundle_compressed, OffloadBundlerTimerGroup, llvm::StringRef::size(), llvm::Timer::startTimer(), llvm::Timer::stopTimer(), llvm::StringRef::substr(), llvm::Expected< T >::takeError(), llvm::toString(), llvm::object::CompressedOffloadBundle::CompressedBundleHeader::tryParse(), llvm::object::CompressedOffloadBundle::CompressedBundleHeader::UncompressedFileSize, llvm::MD5::update(), llvm::object::CompressedOffloadBundle::CompressedBundleHeader::Version, and llvm::compression::Zlib.
Referenced by extractOffloadBundle().
Member Data Documentation
DefaultVersion
const uint16_t llvm::object::CompressedOffloadBundle::DefaultVersion = 3 inline static
Definition at line 62 of file OffloadBundle.h.
The documentation for this class was generated from the following files:
include/llvm/Object/OffloadBundle.h
lib/Object/OffloadBundle.cpp