LLVM: llvm::hlsl::CBufferMetadata Class Reference
llvm::hlsl::CBufferMetadata Class Reference
#include "llvm/Frontend/HLSL/CBuffer.h"
Public Types
using iterator = SmallVector<CBufferMapping>::iterator
Public Member Functions
iterator begin ()
iterator end ()
void eraseFromModule ()
Static Public Member Functions
static std::optional< CBufferMetadata > get (Module &M, llvm::function_ref< bool(Type *)> IsPadding)
Detailed Description
Definition at line 42 of file CBuffer.h.
Member Typedef Documentation
iterator
using llvm::hlsl::CBufferMetadata::iterator = SmallVector<CBufferMapping>::iterator
Definition at line 52 of file CBuffer.h.
Member Function Documentation
begin()
iterator llvm::hlsl::CBufferMetadata::begin () inline
Definition at line 53 of file CBuffer.h.
end()
iterator llvm::hlsl::CBufferMetadata::end () inline
Definition at line 54 of file CBuffer.h.
eraseFromModule()
void CBufferMetadata::eraseFromModule ()
Definition at line 74 of file CBuffer.cpp.
get()
std::optional< CBufferMetadata > CBufferMetadata::get (Module & M, llvm::function_ref< bool(Type *)> IsPadding) static
Definition at line 39 of file CBuffer.cpp.
References assert(), llvm::cast(), getMemberOffsets(), I, llvm::hlsl::CBufferMapping::Members, and llvm::NamedMDNode::operands().
Referenced by replaceCBufferAccesses(), and replaceCBufferAccesses().
The documentation for this class was generated from the following files:
include/llvm/Frontend/HLSL/CBuffer.h
lib/Frontend/HLSL/CBuffer.cpp