LLVM: llvm::EmbedBitcodePass Class Reference
llvm::EmbedBitcodePass Class Reference
Pass embeds a copy of the module optimized with the provided pass pipeline into a global variable.
#include "llvm/Transforms/IPO/EmbedBitcodePass.h"
Public Member Functions
EmbedBitcodePass (EmbedBitcodeOptions Opts)
EmbedBitcodePass (bool IsThinLTO, bool EmitLTOSummary)
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &)
Public Member Functions inherited from llvm::PassInfoMixin< EmbedBitcodePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< EmbedBitcodePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass embeds a copy of the module optimized with the provided pass pipeline into a global variable.
Definition at line 38 of file EmbedBitcodePass.h.
Constructor & Destructor Documentation
EmbedBitcodePass() [1/2]
llvm::EmbedBitcodePass::EmbedBitcodePass (EmbedBitcodeOptions Opts) inline
Definition at line 43 of file EmbedBitcodePass.h.
References EmbedBitcodePass().
Referenced by EmbedBitcodePass().
EmbedBitcodePass() [2/2]
llvm::EmbedBitcodePass::EmbedBitcodePass (bool IsThinLTO, bool EmitLTOSummary) inline
Definition at line 45 of file EmbedBitcodePass.h.
Member Function Documentation
isRequired()
bool llvm::EmbedBitcodePass::isRequired () inline static
Definition at line 50 of file EmbedBitcodePass.h.
run()
PreservedAnalyses EmbedBitcodePass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 25 of file EmbedBitcodePass.cpp.
References llvm::Triple::COFF, llvm::Data, llvm::Triple::ELF, llvm::embedBufferInModule(), llvm::PreservedAnalyses::none(), llvm::reportFatalUsageError(), llvm::BitcodeWriterPass::run(), llvm::ThinLTOBitcodeWriterPass::run(), and T.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/EmbedBitcodePass.h
lib/Transforms/IPO/EmbedBitcodePass.cpp