LLVM: llvm::IRChangedTester Class Reference
llvm::IRChangedTester Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
IRChangedTester ()
~IRChangedTester () override
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Public Member Functions inherited from llvm::IRChangedPrinter
IRChangedPrinter (bool VerboseMode)
~IRChangedPrinter () override
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Public Member Functions inherited from llvm::ChangeReporter< std::string >
virtual ~ChangeReporter ()
void saveIRBeforePass (Any IR, StringRef PassID, StringRef PassName)
void handleIRAfterPass (Any IR, StringRef PassID, StringRef PassName)
void handleInvalidatedPass (StringRef PassID)
Protected Member Functions
void handleIR (const std::string &IR, StringRef PassID)
void handleInitialIR (Any IR) override
void omitAfter (StringRef PassID, std::string &Name) override
void handleInvalidated (StringRef PassID) override
void handleFiltered (StringRef PassID, std::string &Name) override
void handleIgnored (StringRef PassID, std::string &Name) override
void handleAfter (StringRef PassID, std::string &Name, const std::string &Before, const std::string &After, Any) override
Protected Member Functions inherited from llvm::IRChangedPrinter
void generateIRRepresentation (Any IR, StringRef PassID, std::string &Output) override
Protected Member Functions inherited from llvm::TextChangeReporter< std::string >
TextChangeReporter (bool Verbose)
void handleInitialIR (Any IR) override
void omitAfter (StringRef PassID, std::string &Name) override
void handleInvalidated (StringRef PassID) override
void handleFiltered (StringRef PassID, std::string &Name) override
void handleIgnored (StringRef PassID, std::string &Name) override
Protected Member Functions inherited from llvm::ChangeReporter< std::string >
ChangeReporter (bool RunInVerboseMode)
void registerRequiredCallbacks (PassInstrumentationCallbacks &PIC)
Additional Inherited Members
Protected Attributes inherited from llvm::TextChangeReporter< std::string >
raw_ostream & Out
Protected Attributes inherited from llvm::ChangeReporter< std::string >
std::vector< std::string > BeforeStack
bool InitialIR
const bool VerboseMode
Detailed Description
Definition at line 302 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
IRChangedTester()
llvm::IRChangedTester::IRChangedTester () inline
Definition at line 304 of file StandardInstrumentations.h.
References llvm::IRChangedPrinter::IRChangedPrinter().
~IRChangedTester()
IRChangedTester::~IRChangedTester () override default
References handleAfter(), handleFiltered(), handleIgnored(), handleInitialIR(), handleInvalidated(), handleIR(), IR, omitAfter(), and PIC.
Member Function Documentation
handleAfter()
void IRChangedTester::handleAfter (StringRef PassID, std::string & Name, const std::string & Before, const std::string & After, Any) override protected virtual
Reimplemented from llvm::IRChangedPrinter.
Definition at line 585 of file StandardInstrumentations.cpp.
References handleIR().
Referenced by ~IRChangedTester().
handleFiltered()
void IRChangedTester::handleFiltered (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 583 of file StandardInstrumentations.cpp.
Referenced by ~IRChangedTester().
handleIgnored()
void IRChangedTester::handleIgnored (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 584 of file StandardInstrumentations.cpp.
Referenced by ~IRChangedTester().
handleInitialIR()
void IRChangedTester::handleInitialIR (Any IR) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 573 of file StandardInstrumentations.cpp.
References llvm::IRChangedPrinter::generateIRRepresentation(), handleIR(), and IR.
Referenced by ~IRChangedTester().
handleInvalidated()
void IRChangedTester::handleInvalidated (StringRef PassID) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 582 of file StandardInstrumentations.cpp.
Referenced by ~IRChangedTester().
handleIR()
void IRChangedTester::handleIR (const std::string & IR, StringRef PassID) protected
Definition at line 547 of file StandardInstrumentations.cpp.
References llvm::cleanUpTempFiles(), llvm::dbgs(), llvm::sys::ExecuteAndWait(), llvm::sys::findProgramByName(), and llvm::prepareTempFiles().
Referenced by handleAfter(), handleInitialIR(), and ~IRChangedTester().
omitAfter()
void IRChangedTester::omitAfter (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< std::string >.
Definition at line 581 of file StandardInstrumentations.cpp.
Referenced by ~IRChangedTester().
registerCallbacks()
void IRChangedTester::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 542 of file StandardInstrumentations.cpp.
References PIC, and llvm::ChangeReporter< IRUnitT >::registerRequiredCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp