LLVM: llvm::orc::MapperJITLinkMemoryManager::InFlightAlloc Class Reference
llvm::orc::MapperJITLinkMemoryManager::InFlightAlloc Class Reference
Public Member Functions
InFlightAlloc (MapperJITLinkMemoryManager &Parent, LinkGraph &G, ExecutorAddr AllocAddr, std::vector< MemoryMapper::AllocInfo::SegInfo > Segs)
void finalize (OnFinalizedFunction OnFinalize) override
Called to transfer working memory to the target and apply finalization.
void abandon (OnAbandonedFunction OnFinalize) override
Called prior to finalization if the allocation should be abandoned.
Public Member Functions inherited from llvm::jitlink::JITLinkMemoryManager::InFlightAlloc
virtual ~InFlightAlloc ()
Expected< FinalizedAlloc > finalize ()
Synchronous convenience version of finalize.
Additional Inherited Members
Public Types inherited from llvm::jitlink::JITLinkMemoryManager::InFlightAlloc
using OnFinalizedFunction = unique_function<void(Expected<FinalizedAlloc>)>
using OnAbandonedFunction = unique_function<void(Error)>
Detailed Description
Definition at line 19 of file MapperJITLinkMemoryManager.cpp.
Constructor & Destructor Documentation
InFlightAlloc()
llvm::orc::MapperJITLinkMemoryManager::InFlightAlloc::InFlightAlloc (MapperJITLinkMemoryManager & Parent, LinkGraph & G, ExecutorAddr AllocAddr, std::vector< MemoryMapper::AllocInfo::SegInfo > Segs) inline
Definition at line 22 of file MapperJITLinkMemoryManager.cpp.
References llvm::orc::MapperJITLinkMemoryManager::MapperJITLinkMemoryManager(), and llvm::move().
Member Function Documentation
abandon()
void llvm::orc::MapperJITLinkMemoryManager::InFlightAlloc::abandon (OnAbandonedFunction OnAbandoned) inline override virtual
Called prior to finalization if the allocation should be abandoned.
Implements llvm::jitlink::JITLinkMemoryManager::InFlightAlloc.
Definition at line 45 of file MapperJITLinkMemoryManager.cpp.
finalize()
void llvm::orc::MapperJITLinkMemoryManager::InFlightAlloc::finalize (OnFinalizedFunction OnFinalized) inline override virtual
Called to transfer working memory to the target and apply finalization.
Implements llvm::jitlink::JITLinkMemoryManager::InFlightAlloc.
Definition at line 27 of file MapperJITLinkMemoryManager.cpp.
References llvm::orc::MemoryMapper::AllocInfo::Actions, llvm::orc::MemoryMapper::AllocInfo::MappingBase, llvm::orc::Result, llvm::orc::MemoryMapper::AllocInfo::Segments, and std::swap().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/MapperJITLinkMemoryManager.cpp