LLVM: llvm::DIStringType Class Reference
llvm::DIStringType Class Reference
String type, Fortran CHARACTER(n).
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DIStringType,(unsigned Tag, StringRef Name, uint64_t SizeInBits, uint32_t AlignInBits),(Tag, Name, nullptr, nullptr, nullptr, SizeInBits, AlignInBits, 0)) DEFINE_MDNODE_GET(DIStringType
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding DEFINE_MDNODE_GET (DIStringType,(unsigned Tag, StringRef Name, Metadata *StringLength, Metadata *StringLengthExp, Metadata *StringLocationExp, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding),(Tag, Name, StringLength, StringLengthExp, StringLocationExp, SizeInBits, AlignInBits, Encoding)) DEFINE_MDNODE_GET(DIStringType
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned Encoding TempDIStringType clone () const
DIVariable * getStringLength () const
DIExpression * getStringLengthExp () const
DIExpression * getStringLocationExp () const
unsigned getEncoding () const
Metadata * getRawStringLength () const
Metadata * getRawStringLengthExp () const
Metadata * getRawStringLocationExp () const
Public Member Functions inherited from llvm::DIType
TempDIType clone () const
unsigned getLine () const
LLVM_ABI uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
uint32_t getNumExtraInhabitants () const
DIFlags getFlags () const
DIScope * getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
Metadata * getRawSizeInBits () const
uint64_t getSizeInBits () const
Metadata * getRawOffsetInBits () const
uint64_t getOffsetInBits () const
TempDIType cloneWithFlags (DIFlags NewFlags) const
Returns a new temporary DIType with updated Flags.
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isBitField () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isTypePassByValue () const
bool isTypePassByReference () const
bool isBigEndian () const
bool isLittleEndian () const
bool getExportSymbols () const
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
LLVM_ABI StringRef getName () const
LLVM_ABI DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
LLVM_ABI dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
LLVM_ABI TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
LLVM_ABI void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
bool hasGeneralizedMDString ()
Check if this is a valid generalized type metadata node.
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
LLVM_ABI void resolveCycles ()
Resolve cycles.
LLVM_ABI void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
LLVM_ABI bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
LLVM_ABI void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
LLVM_ABI void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
LLVM_ABI void dumpTree () const
User-friendly dump in tree shape.
LLVM_ABI void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIType
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static LLVM_ABI DIFlags getFlag (StringRef Flag)
static LLVM_ABI StringRef getFlagString (DIFlags Flag)
static LLVM_ABI DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static LLVM_ABI void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static LLVM_ABI MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static LLVM_ABI MDNode * intersect (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericNoaliasAddrspace (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
static LLVM_ABI MDNode * getMergedMemProfMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCallsiteMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCalleeTypeMetadata (const MDNode *A, const MDNode *B)
static LLVM_ABI CaptureComponents toCaptureComponents (const MDNode *MD)
Convert !captures metadata to CaptureComponents. MD may be nullptr.
static LLVM_ABI MDNode * fromCaptureComponents (LLVMContext &Ctx, CaptureComponents CC)
Convert CaptureComponents to !captures metadata.
Public Attributes
unsigned Tag
unsigned MDString * Name
unsigned MDString Metadata * StringLength
unsigned MDString Metadata Metadata * StringLengthExp
unsigned MDString Metadata Metadata Metadata * StringLocationExp
unsigned MDString Metadata Metadata Metadata uint64_t SizeInBits
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t AlignInBits
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Tag
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Name
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned StringLength
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned StringLengthExp
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned StringLocationExp
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned SizeInBits
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned AlignInBits
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned Tag
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString * Name
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata * StringLength
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata * StringLengthExp
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata * StringLocationExp
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata * SizeInBits
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t AlignInBits
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned Encoding
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned Tag
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned Name
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned StringLength
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned StringLengthExp
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned StringLocationExp
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned SizeInBits
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned AlignInBits
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIType
DIType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags, ArrayRef< Metadata * > Ops)
~DIType ()=default
void init (unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags)
void mutate (unsigned Tag, unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags)
Change fields in place.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~DINode ()=default
template<class Ty>
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
LLVM_ABI MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~MDNode ()=default
LLVM_ABI void * operator new (size_t Size, size_t NumOps, StorageType Storage)
LLVM_ABI void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
LLVM_ABI void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
LLVM_ABI void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
LLVM_ABI void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T, class StoreT>
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T>
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Static Protected Attributes inherited from llvm::DIType
static constexpr unsigned N_OPERANDS = 5
Detailed Description
String type, Fortran CHARACTER(n).
Definition at line 1168 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
bool llvm::DIStringType::classof (const Metadata * MD) inline static
Definition at line 1251 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned Encoding TempDIStringType llvm::DIStringType::clone () const inline
Definition at line 1249 of file DebugInfoMetadata.h.
References clone().
Referenced by clone().
DEFINE_MDNODE_GET() [1/2]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding llvm::DIStringType::DEFINE_MDNODE_GET (DIStringType , (unsigned Tag, StringRef Name, Metadata *StringLength, Metadata *StringLengthExp, Metadata *StringLocationExp, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding) , (Tag, Name, StringLength, StringLengthExp, StringLocationExp, SizeInBits, AlignInBits, Encoding))
References AlignInBits, DEFINE_MDNODE_GET(), Name, SizeInBits, StringLength, StringLengthExp, StringLocationExp, and Tag.
DEFINE_MDNODE_GET() [2/2]
llvm::DIStringType::DEFINE_MDNODE_GET (DIStringType , (unsigned Tag, StringRef Name, uint64_t SizeInBits, uint32_t AlignInBits) , (Tag, Name, nullptr, nullptr, nullptr, SizeInBits, AlignInBits, 0))
References AlignInBits, DEFINE_MDNODE_GET(), Name, SizeInBits, and Tag.
Referenced by DEFINE_MDNODE_GET(), and DEFINE_MDNODE_GET().
getEncoding()
unsigned llvm::DIStringType::getEncoding () const inline
Definition at line 1267 of file DebugInfoMetadata.h.
getRawStringLength()
Metadata * llvm::DIStringType::getRawStringLength () const inline
Definition at line 1269 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getStringLength().
getRawStringLengthExp()
Metadata * llvm::DIStringType::getRawStringLengthExp () const inline
Definition at line 1271 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getStringLengthExp().
getRawStringLocationExp()
Metadata * llvm::DIStringType::getRawStringLocationExp () const inline
Definition at line 1275 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getStringLocationExp().
getStringLength()
DIVariable * llvm::DIStringType::getStringLength () const inline
Definition at line 1255 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawStringLength().
getStringLengthExp()
DIExpression * llvm::DIStringType::getStringLengthExp () const inline
Definition at line 1259 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawStringLengthExp().
getStringLocationExp()
DIExpression * llvm::DIStringType::getStringLocationExp () const inline
Definition at line 1263 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawStringLocationExp().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1169 of file DebugInfoMetadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
MDNode
friend class MDNode friend
Definition at line 1170 of file DebugInfoMetadata.h.
References AbstractManglingParser< Derived, Alloc >::Ops, AlignInBits, llvm::CallingConv::C, llvm::DIType::DIType(), MDNode, llvm::DIType::N_OPERANDS, llvm::Metadata::Storage, and Tag.
Referenced by MDNode.
Member Data Documentation
AlignInBits [1/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::AlignInBits
Definition at line 1247 of file DebugInfoMetadata.h.
AlignInBits [2/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t llvm::DIStringType::AlignInBits
Definition at line 1244 of file DebugInfoMetadata.h.
AlignInBits [3/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::AlignInBits
Definition at line 1233 of file DebugInfoMetadata.h.
AlignInBits [4/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t llvm::DIStringType::AlignInBits
Definition at line 1230 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), and MDNode.
Encoding [1/2]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::Encoding
Definition at line 1245 of file DebugInfoMetadata.h.
Encoding [2/2]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::Encoding
Definition at line 1231 of file DebugInfoMetadata.h.
Name [1/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::Name
Definition at line 1246 of file DebugInfoMetadata.h.
Name [2/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString* llvm::DIStringType::Name
Definition at line 1242 of file DebugInfoMetadata.h.
Name [3/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::Name
Definition at line 1232 of file DebugInfoMetadata.h.
Name [4/4]
unsigned MDString* llvm::DIStringType::Name
Definition at line 1228 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), and DEFINE_MDNODE_GET().
SizeInBits [1/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::SizeInBits
Definition at line 1247 of file DebugInfoMetadata.h.
SizeInBits [2/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata* llvm::DIStringType::SizeInBits
Definition at line 1244 of file DebugInfoMetadata.h.
SizeInBits [3/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::SizeInBits
Definition at line 1233 of file DebugInfoMetadata.h.
SizeInBits [4/4]
unsigned MDString Metadata Metadata Metadata uint64_t llvm::DIStringType::SizeInBits
Definition at line 1230 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), and DEFINE_MDNODE_GET().
StringLength [1/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::StringLength
Definition at line 1246 of file DebugInfoMetadata.h.
StringLength [2/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata* llvm::DIStringType::StringLength
Definition at line 1242 of file DebugInfoMetadata.h.
StringLength [3/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::StringLength
Definition at line 1232 of file DebugInfoMetadata.h.
StringLength [4/4]
unsigned MDString Metadata* llvm::DIStringType::StringLength
Definition at line 1228 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET().
StringLengthExp [1/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::StringLengthExp
Definition at line 1246 of file DebugInfoMetadata.h.
StringLengthExp [2/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata* llvm::DIStringType::StringLengthExp
Definition at line 1243 of file DebugInfoMetadata.h.
StringLengthExp [3/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::StringLengthExp
Definition at line 1232 of file DebugInfoMetadata.h.
StringLengthExp [4/4]
unsigned MDString Metadata Metadata* llvm::DIStringType::StringLengthExp
Definition at line 1229 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET().
StringLocationExp [1/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::StringLocationExp
Definition at line 1247 of file DebugInfoMetadata.h.
StringLocationExp [2/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata* llvm::DIStringType::StringLocationExp
Definition at line 1243 of file DebugInfoMetadata.h.
StringLocationExp [3/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::StringLocationExp
Definition at line 1233 of file DebugInfoMetadata.h.
StringLocationExp [4/4]
unsigned MDString Metadata Metadata Metadata* llvm::DIStringType::StringLocationExp
Definition at line 1229 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET().
Tag [1/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned MDString Metadata Metadata Metadata Metadata uint32_t unsigned llvm::DIStringType::Tag
Definition at line 1246 of file DebugInfoMetadata.h.
Tag [2/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned Encoding unsigned llvm::DIStringType::Tag
Definition at line 1242 of file DebugInfoMetadata.h.
Tag [3/4]
unsigned MDString Metadata Metadata Metadata uint64_t uint32_t unsigned llvm::DIStringType::Tag
Definition at line 1232 of file DebugInfoMetadata.h.
Tag [4/4]
unsigned llvm::DIStringType::Tag
Definition at line 1228 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), and MDNode.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp