LLVM: llvm::ARMOverrideBypasses Class Reference
llvm::ARMOverrideBypasses Class Reference abstract
Post-process the DAG to create cluster edges between instrs that may be fused by the processor into a single operation.
#include "Target/ARM/ARMLatencyMutations.h"
Public Member Functions
ARMOverrideBypasses (const ARMBaseInstrInfo *t, AAResults *a)
void apply (ScheduleDAGInstrs *DAGInstrs) override
Public Member Functions inherited from llvm::ScheduleDAGMutation
virtual ~ScheduleDAGMutation ()=default
Protected Member Functions
unsigned makeBundleAssumptions (SUnit &ISU, SDep &Dep)
bool memoryRAWHazard (SUnit &ISU, SDep &Dep, unsigned latency)
Static Protected Member Functions
static void setBidirLatencies (SUnit &SrcSU, SDep &SrcDep, unsigned latency)
static bool zeroOutputDependences (SUnit &ISU, SDep &Dep)
Protected Attributes
const ARMBaseInstrInfo * TII
AAResults * AA
ScheduleDAGInstrs * DAG = nullptr
Detailed Description
Post-process the DAG to create cluster edges between instrs that may be fused by the processor into a single operation.
Definition at line 27 of file ARMLatencyMutations.h.
Constructor & Destructor Documentation
ARMOverrideBypasses()
llvm::ARMOverrideBypasses::ARMOverrideBypasses (const ARMBaseInstrInfo * t, AAResults * a) inline
Definition at line 29 of file ARMLatencyMutations.h.
References AA, and TII.
Member Function Documentation
apply()
void llvm::ARMOverrideBypasses::apply (ScheduleDAGInstrs * DAGInstrs) override virtual
Implements llvm::ScheduleDAGMutation.
Definition at line 953 of file ARMLatencyMutations.cpp.
References DAG, llvm::ScheduleDAG::ExitSU, llvm::SUnit::getInstr(), llvm::SUnit::isBoundaryNode(), and llvm::ScheduleDAG::SUnits.
makeBundleAssumptions()
unsigned llvm::ARMOverrideBypasses::makeBundleAssumptions (SUnit & ISU, SDep & Dep) protected
Definition at line 529 of file ARMLatencyMutations.cpp.
References llvm::SUnit::getInstr(), llvm::MachineInstr::getOpcode(), llvm::SDep::getReg(), llvm::SDep::getSUnit(), llvm::SDep::isAssignedRegDep(), setBidirLatencies(), and TII.
memoryRAWHazard()
bool llvm::ARMOverrideBypasses::memoryRAWHazard (SUnit & ISU, SDep & Dep, unsigned latency) protected
Definition at line 553 of file ARMLatencyMutations.cpp.
References AA, llvm::cast(), llvm::PseudoSourceValue::FixedStack, llvm::SUnit::getInstr(), llvm::SDep::getSUnit(), llvm::SDep::isNormalMemory(), llvm::MachineInstr::memoperands(), llvm::AliasResult::MustAlias, and setBidirLatencies().
setBidirLatencies()
void llvm::ARMOverrideBypasses::setBidirLatencies (SUnit & SrcSU, SDep & SrcDep, unsigned latency) static protected
Definition at line 491 of file ARMLatencyMutations.cpp.
References llvm::SDep::getSUnit(), llvm::SUnit::Preds, llvm::Reverse, llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::SDep::setLatency(), and llvm::SDep::setSUnit().
Referenced by makeBundleAssumptions(), memoryRAWHazard(), and zeroOutputDependences().
zeroOutputDependences()
bool llvm::ARMOverrideBypasses::zeroOutputDependences (SUnit & ISU, SDep & Dep) static protected
Definition at line 513 of file ARMLatencyMutations.cpp.
References llvm::SDep::getKind(), llvm::SDep::Output, and setBidirLatencies().
Member Data Documentation
AA
AAResults* llvm::ARMOverrideBypasses::AA protected
Definition at line 39 of file ARMLatencyMutations.h.
Referenced by ARMOverrideBypasses(), and memoryRAWHazard().
DAG
ScheduleDAGInstrs* llvm::ARMOverrideBypasses::DAG = nullptr protected
Definition at line 40 of file ARMLatencyMutations.h.
Referenced by apply().
TII
const ARMBaseInstrInfo* llvm::ARMOverrideBypasses::TII protected
Definition at line 38 of file ARMLatencyMutations.h.
Referenced by ARMOverrideBypasses(), and makeBundleAssumptions().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMLatencyMutations.h
lib/Target/ARM/ARMLatencyMutations.cpp