LLVM: llvm::lsp::Logger Class Reference
llvm::lsp::Logger Class Reference
This class represents the main interface for logging, and allows for filtering logging based on different levels of severity or significance.
#include "llvm/Support/LSP/Logging.h"
Public Types
enum class Level { Debug , Info , Error }
The level of significance for a log message.
Static Public Member Functions
static LLVM_ABI_FOR_TEST void setLogLevel (Level LogLevel)
Set the severity level of the logger.
template<typename... Ts>
static void debug (const char *Fmt, Ts &&...Vals)
Initiate a log message at various severity levels.
template<typename... Ts>
static void info (const char *Fmt, Ts &&...Vals)
template<typename... Ts>
static void error (const char *Fmt, Ts &&...Vals)
Detailed Description
This class represents the main interface for logging, and allows for filtering logging based on different levels of severity or significance.
Definition at line 21 of file Logging.h.
Member Enumeration Documentation
Level
enum class llvm::lsp::Logger::Level strong
The level of significance for a log message.
Enumerator
Debug
Info
Error
Definition at line 24 of file Logging.h.
Member Function Documentation
debug()
template<typename... Ts> void llvm::lsp::Logger::debug (const char * Fmt, Ts &&... Vals) inline static
Initiate a log message at various severity levels.
These should be called after a call to initialize.
Definition at line 31 of file Logging.h.
References Debug, and llvm::formatv().
error()
template<typename... Ts> void llvm::lsp::Logger::error (const char * Fmt, Ts &&... Vals) inline static
Definition at line 37 of file Logging.h.
References Error, and llvm::formatv().
Referenced by llvm::lsp::MessageHandler::onReply(), and llvm::lsp::JSONTransport::run().
info()
template<typename... Ts> void llvm::lsp::Logger::info (const char * Fmt, Ts &&... Vals) inline static
Definition at line 34 of file Logging.h.
References llvm::formatv(), and Info.
Referenced by llvm::lsp::MessageHandler::onCall(), llvm::lsp::MessageHandler::onNotify(), llvm::lsp::MessageHandler::onReply(), llvm::lsp::MessageHandler::outgoingNotification(), and llvm::lsp::MessageHandler::outgoingRequest().
setLogLevel()
void Logger::setLogLevel (Level LogLevel) static
Set the severity level of the logger.
Definition at line 16 of file Logging.cpp.
References llvm::get().
The documentation for this class was generated from the following files:
include/llvm/Support/LSP/Logging.h
lib/Support/LSP/Logging.cpp