LLVM: llvm::lsp::MessageHandler Class Reference
llvm::lsp::MessageHandler Class Reference
A handler used to process the incoming transport messages.
#include "llvm/Support/LSP/Transport.h"
Public Member Functions
MessageHandler (JSONTransport &Transport)
bool onNotify (StringRef Method, llvm::json::Value Value)
bool onCall (StringRef Method, llvm::json::Value Params, llvm::json::Value Id)
bool onReply (llvm::json::Value Id, llvm::Expected< llvm::json::Value > Result)
template<typename Param, typename Result, typename ThisT>
void method (llvm::StringLiteral Method, ThisT *ThisPtr, void(ThisT::*Handler)(const Param &, Callback< Result >))
template<typename Param, typename ThisT>
void notification (llvm::StringLiteral Method, ThisT *ThisPtr, void(ThisT::*Handler)(const Param &))
template<typename T>
OutgoingNotification< T > outgoingNotification (llvm::StringLiteral Method)
Create an OutgoingNotification object used for the given method.
template<typename Param, typename Result>
OutgoingRequest< Param > outgoingRequest (llvm::StringLiteral Method, OutgoingRequestCallback< Result > Callback)
Create an OutgoingRequest function that, when called, sends a request with the given method via the transport.
Static Public Member Functions
template<typename T>
static llvm::Expected< T > parse (const llvm::json::Value &Raw, StringRef PayloadName, StringRef PayloadKind)
Detailed Description
A handler used to process the incoming transport messages.
Definition at line 160 of file Transport.h.
Constructor & Destructor Documentation
MessageHandler()
llvm::lsp::MessageHandler::MessageHandler (JSONTransport & Transport) inline
Definition at line 162 of file Transport.h.
Member Function Documentation
method()
template<typename Param, typename Result, typename ThisT> void llvm::lsp::MessageHandler::method (llvm::StringLiteral Method, ThisT * ThisPtr, void(ThisT::* Handler)(const Param &, Callback< Result >)) inline
Definition at line 189 of file Transport.h.
References llvm::lsp::Method, llvm::lsp::Parameter, and parse().
notification()
template<typename Param, typename ThisT> void llvm::lsp::MessageHandler::notification (llvm::StringLiteral Method, ThisT * ThisPtr, void(ThisT::* Handler)(const Param &)) inline
Definition at line 203 of file Transport.h.
References llvm::consumeError(), llvm::handleErrors(), llvm::lsp::Method, llvm::lsp::Parameter, and parse().
onCall()
bool MessageHandler::onCall (llvm::StringRef Method, llvm::json::Value Params, llvm::json::Value Id)
Definition at line 101 of file Transport.cpp.
References llvm::lsp::Logger::info(), llvm::make_error(), llvm::lsp::Method, and llvm::lsp::MethodNotFound.
onNotify()
bool MessageHandler::onNotify (llvm::StringRef Method, llvm::json::Value Value)
Definition at line 86 of file Transport.cpp.
References llvm::lsp::Logger::info(), and llvm::lsp::Method.
onReply()
bool MessageHandler::onReply (llvm::json::Value Id, llvm::Expected< llvm::json::Value > Result)
Definition at line 117 of file Transport.cpp.
References llvm::consumeError(), llvm::debugString(), llvm::lsp::Logger::error(), and llvm::lsp::Logger::info().
outgoingNotification()
template<typename T> OutgoingNotification< T > llvm::lsp::MessageHandler::outgoingNotification (llvm::StringLiteral Method) inline
Create an OutgoingNotification object used for the given method.
Definition at line 222 of file Transport.h.
References llvm::lsp::Logger::info(), llvm::lsp::Method, and T.
outgoingRequest()
template<typename Param, typename Result> OutgoingRequest< Param > llvm::lsp::MessageHandler::outgoingRequest (llvm::StringLiteral Method, OutgoingRequestCallback< Result > Callback) inline
Create an OutgoingRequest function that, when called, sends a request with the given method via the transport.
Should the outgoing request be met with a response, the result JSON is parsed and the response callback is invoked.
Definition at line 236 of file Transport.h.
References llvm::debugString(), llvm::formatv(), llvm::lsp::Logger::info(), llvm::lsp::Method, llvm::lsp::Parameter, and parse().
parse()
template<typename T> llvm::Expected< T > llvm::lsp::MessageHandler::parse (const llvm::json::Value & Raw, StringRef PayloadName, StringRef PayloadKind) inline static
Definition at line 169 of file Transport.h.
References llvm::fmt_consume(), llvm::formatv(), llvm::lsp::fromJSON(), llvm::json::Path::Root::getError(), llvm::lsp::InvalidParams, llvm::make_error(), llvm::json::Path::Root::printErrorContext(), and T.
Referenced by method(), notification(), and outgoingRequest().
The documentation for this class was generated from the following files:
include/llvm/Support/LSP/Transport.h
lib/Support/LSP/Transport.cpp