LLVM: llvm::cas::CacheKey Class Reference
llvm::cas::CacheKey Class Reference
A key for caching an operation.
#include "llvm/CAS/ActionCache.h"
Public Member Functions
StringRef getKey () const
LLVM_ABI CacheKey (const CASID &ID)
LLVM_ABI_FOR_TEST CacheKey (const ObjectProxy &Proxy)
CacheKey (const ObjectStore &CAS, const ObjectRef &Ref)
Detailed Description
A key for caching an operation.
It is implemented as a bag of bytes and provides a convenient constructor for CAS types.
Definition at line 32 of file ActionCache.h.
Constructor & Destructor Documentation
CacheKey() [1/3]
CacheKey::CacheKey (const CASID & ID)
Definition at line 18 of file ActionCache.cpp.
Referenced by CacheKey().
CacheKey() [2/3]
CacheKey::CacheKey (const ObjectProxy & Proxy)
Definition at line 19 of file ActionCache.cpp.
References CacheKey().
CacheKey() [3/3]
CacheKey::CacheKey (const ObjectStore & CAS, const ObjectRef & Ref)
Definition at line 21 of file ActionCache.cpp.
Member Function Documentation
getKey()
StringRef llvm::cas::CacheKey::getKey () const inline
Definition at line 34 of file ActionCache.h.
Referenced by llvm::cas::ActionCache::get(), and llvm::cas::ActionCache::put().
The documentation for this class was generated from the following files:
include/llvm/CAS/ActionCache.h
lib/CAS/ActionCache.cpp