LLVM: llvm::ArrayRef< T > Class Template Reference
llvm::ArrayRef< T > Class Template Reference
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
#include "llvm/ADT/ArrayRef.h"
Inherited by llvm::MutableArrayRef< T >.
Public Types
using value_type = T
using pointer = value_type *
using const_pointer = const value_type *
using reference = value_type &
using const_reference = const value_type &
using iterator = const_pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using size_type = size_t
using difference_type = ptrdiff_t
Public Member Functions
Constructors
ArrayRef ()=default
Construct an empty ArrayRef.
ArrayRef (const T &OneElt LLVM_LIFETIME_BOUND)
Construct an ArrayRef from a single element.
constexpr ArrayRef (const T *data LLVM_LIFETIME_BOUND, size_t length)
Construct an ArrayRef from a pointer and length.
constexpr ArrayRef (const T *begin LLVM_LIFETIME_BOUND, const T *end)
Construct an ArrayRef from a range.
template<typename C, typename = std::enable_if_t< std::conjunction_v< std::is_convertible< decltype(std::declval<const C &>().data()) *, const T *const *>, std::is_integral<decltype(std::declval<const C &>().size())>>
constexpr ArrayRef (const C &V)
Construct an ArrayRef from a type that has a data() method that returns a pointer convertible to const T *.
template<size_t N>
constexpr ArrayRef (const T(&Arr LLVM_LIFETIME_BOUND)[N])
Construct an ArrayRef from a C array.
constexpr ArrayRef (std::initializer_list< T > Vec LLVM_LIFETIME_BOUND)
Construct an ArrayRef from a std::initializer_list.
template<typename U, typename = std::enable_if_t< std::is_convertible_v<U *const *, T *const *>>>
ArrayRef (const iterator_range< U * > &Range)
Construct an ArrayRef<T> from iterator_range<U*>.
Simple Operations
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
empty - Check if the array is empty.
const T * data () const
size_t size () const
size - Get the array size.
const T & front () const
front - Get the first element.
const T & back () const
back - Get the last element.
const T & consume_front ()
consume_front() - Returns the first element and drops it from ArrayRef.
const T & consume_back ()
consume_back() - Returns the last element and drops it from ArrayRef.
template<typename Allocator>
MutableArrayRef< T > copy (Allocator &A)
bool equals (ArrayRef RHS) const
equals - Check for element-wise equality.
ArrayRef< T > slice (size_t N, size_t M) const
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
ArrayRef< T > slice (size_t N) const
slice(n) - Chop off the first N elements of the array.
ArrayRef< T > drop_front (size_t N=1) const
Drop the first N elements of the array.
ArrayRef< T > drop_back (size_t N=1) const
Drop the last N elements of the array.
template<class PredicateT>
ArrayRef< T > drop_while (PredicateT Pred) const
Return a copy of *this with the first N elements satisfying the given predicate removed.
template<class PredicateT>
ArrayRef< T > drop_until (PredicateT Pred) const
Return a copy of *this with the first N elements not satisfying the given predicate removed.
ArrayRef< T > take_front (size_t N=1) const
Return a copy of *this with only the first N elements.
ArrayRef< T > take_back (size_t N=1) const
Return a copy of *this with only the last N elements.
template<class PredicateT>
ArrayRef< T > take_while (PredicateT Pred) const
Return the first N elements of this Array that satisfy the given predicate.
template<class PredicateT>
ArrayRef< T > take_until (PredicateT Pred) const
Return the first N elements of this Array that don't satisfy the given predicate.
Operator Overloads
const T & operator[] (size_t Index) const
template<typename U>
std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & operator= (U &&Temporary)=delete
Disallow accidental assignment from a temporary.
template<typename U>
std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & operator= (std::initializer_list< U >)=delete
Disallow accidental assignment from a temporary.
Expensive Operations
std::vector< T > vec () const
Conversion operators
operator std::vector< T > () const
Detailed Description
template<typename T>
class llvm::ArrayRef< T >
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
a start pointer and a length. It allows various APIs to take consecutive elements easily and conveniently.
This class does not own the underlying data, it is expected to be used in situations where the data resides in some other buffer, whose lifetime extends past that of the ArrayRef. For this reason, it is not in general safe to store an ArrayRef.
This is intended to be trivially copyable, so it should be passed by value.
Definition at line 40 of file ArrayRef.h.
Member Typedef Documentation
const_iterator
template<typename T> using llvm::ArrayRef< T >::const_iterator = const_pointer
Definition at line 48 of file ArrayRef.h.
const_pointer
template<typename T> using llvm::ArrayRef< T >::const_pointer = const value_type *
Definition at line 44 of file ArrayRef.h.
const_reference
template<typename T> using llvm::ArrayRef< T >::const_reference = const value_type &
Definition at line 46 of file ArrayRef.h.
const_reverse_iterator
template<typename T> using llvm::ArrayRef< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 50 of file ArrayRef.h.
difference_type
template<typename T> using llvm::ArrayRef< T >::difference_type = ptrdiff_t
Definition at line 52 of file ArrayRef.h.
iterator
template<typename T> using llvm::ArrayRef< T >::iterator = const_pointer
Definition at line 47 of file ArrayRef.h.
pointer
template<typename T> using llvm::ArrayRef< T >::pointer = value_type *
Definition at line 43 of file ArrayRef.h.
reference
template<typename T> using llvm::ArrayRef< T >::reference = value_type &
Definition at line 45 of file ArrayRef.h.
reverse_iterator
template<typename T> using llvm::ArrayRef< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 49 of file ArrayRef.h.
size_type
template<typename T> using llvm::ArrayRef< T >::size_type = size_t
Definition at line 51 of file ArrayRef.h.
value_type
template<typename T> using llvm::ArrayRef< T >::value_type = T
Definition at line 42 of file ArrayRef.h.
Constructor & Destructor Documentation
ArrayRef() [1/8]
template<typename T> llvm::ArrayRef< T >::ArrayRef () default
Construct an empty ArrayRef.
ArrayRef() [2/8]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T &OneElt LLVM_LIFETIME_BOUND) inline
Construct an ArrayRef from a single element.
Definition at line 69 of file ArrayRef.h.
ArrayRef() [3/8]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T *data LLVM_LIFETIME_BOUND, size_t length) inline constexpr
Construct an ArrayRef from a pointer and length.
Definition at line 73 of file ArrayRef.h.
ArrayRef() [4/8]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T *begin LLVM_LIFETIME_BOUND, const T * end) inline constexpr
Construct an ArrayRef from a range.
Definition at line 78 of file ArrayRef.h.
ArrayRef() [5/8]
template<typename T> template<typename C, typename = std::enable_if_t< std::conjunction_v< std::is_convertible< decltype(std::declval<const C &>().data()) *, const T *const *>, std::is_integral<decltype(std::declval<const C &>().size())>> llvm::ArrayRef< T >::ArrayRef (const C & V) inline constexpr
Construct an ArrayRef from a type that has a data() method that returns a pointer convertible to const T *.
Definition at line 94 of file ArrayRef.h.
ArrayRef() [6/8]
template<typename T> template<size_t N> llvm::ArrayRef< T >::ArrayRef (const T(&) LLVM_LIFETIME_BOUND[N]) inline constexpr
Construct an ArrayRef from a C array.
Definition at line 99 of file ArrayRef.h.
ArrayRef() [7/8]
template<typename T> llvm::ArrayRef< T >::ArrayRef (std::initializer_list< T > Vec LLVM_LIFETIME_BOUND) inline constexpr
Construct an ArrayRef from a std::initializer_list.
Definition at line 110 of file ArrayRef.h.
ArrayRef() [8/8]
template<typename T> template<typename U, typename = std::enable_if_t< std::is_convertible_v<U *const *, T *const *>>> llvm::ArrayRef< T >::ArrayRef (const iterator_range< U * > & Range) inline
Construct an ArrayRef<T> from iterator_range<U*>.
This uses SFINAE to ensure that this is only used for iterator ranges over plain pointer iterators.
Definition at line 123 of file ArrayRef.h.
Member Function Documentation
back()
template<typename T> const T & llvm::ArrayRef< T >::back () const inline
back - Get the last element.
Definition at line 151 of file ArrayRef.h.
Referenced by llvm::addParamAttribute(), llvm::DIExpression::appendToStack(), canSinkStoreWithNoAliasCheck(), llvm::RandomIRBuilder::connectToSink(), llvm::object::ELFFile< ELFT >::dynamicEntries(), isMaskedLoadCompress(), isSwitchDense(), llvm::RandomIRBuilder::newSink(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::orc::shared::runDeallocActions(), simplifyGEPInst(), simplifyInstructionWithOperands(), and llvm::SLPVectorizerPass::vectorizeCmpInsts().
begin()
template<typename T> iterator llvm::ArrayRef< T >::begin () const inline
Definition at line 130 of file ArrayRef.h.
Referenced by addMask(), llvm::DebugLocEntry::addValues(), llvm::MCObjectStreamer::appendContents(), llvm::object::DynamicRelocRef::arm64x_reloc_begin(), llvm::const_iterator< MemoryLocation >::assign(), llvm::DIExpressionCursor::assignNewExpr(), buildFixItLine(), calcPredicateUsingInteger(), llvm::Interpreter::callFunction(), canonicalizeDwarfOperations(), canSinkStoreWithNoAliasCheck(), slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::collectGlobalObjectNameStrings(), combineX86ShufflesRecursively(), llvm::ComputeLinearIndex(), computeMemberData(), llvm::concatenateVectors(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), CreateGCRelocates(), createMergedFunction(), llvm::DIExpression::elements_begin(), llvm::MCDwarfFrameEmitter::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::FindInsertedValue(), gatherPossiblyVectorizableLoads(), llvm::gsym::GsymReader::getAddressOffsetIndex(), llvm::DagInit::getArgNo(), llvm::omp::getCompoundConstruct(), llvm::StructLayout::getElementContainingOffset(), llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), llvm::HexagonRegisterInfo::getHexagonSubRegIndex(), llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), llvm::X86RegisterInfo::getLargestLegalSuperClass(), llvm::omp::getLeafOrCompositeConstructs(), getNoopInput(), llvm::getShuffleMaskWithWidestElts(), growShuffleMask(), handleCallSite(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), insertCandidatesWithPendingInjections(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::omp::isCompositeConstruct(), isFixedVectorShuffle(), llvm::LiveRange::isLiveAtIndexes(), isMaskedLoadCompress(), isSubset(), llvm::coverage::CoverageMapping::load(), lookupLLVMIntrinsicByName(), lowerV8I16GeneralSingleInputShuffle(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), mergeComparisons(), optimizeDwarfOperations(), llvm::CallBase::populateBundleOperandInfos(), llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readFixedString(), llvm::MachineFunction::setCallSiteLandingPad(), llvm::X86MachineFunctionInfo::setPreallocatedArgOffsets(), llvm::setProfMetadata(), llvm::gsym::GsymCreator::setUUID(), llvm::MCFragment::setVarContents(), llvm::sandboxir::Scheduler::trySchedule(), llvm::misexpect::verifyMisExpect(), llvm::offloading::wrapSYCLBinaries(), writeDIE(), and writeToResolutionFile().
consume_back()
template<typename T> const T & llvm::ArrayRef< T >::consume_back () inline
consume_back() - Returns the last element and drops it from ArrayRef.
Definition at line 164 of file ArrayRef.h.
consume_front()
template<typename T> const T & llvm::ArrayRef< T >::consume_front () inline
consume_front() - Returns the first element and drops it from ArrayRef.
Definition at line 157 of file ArrayRef.h.
Referenced by allSameType(), computeCommonAlignment(), llvm::constructSeqOffsettoOrigRowMapping(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), and PrintMessage().
copy()
template<typename T> template<typename Allocator> MutableArrayRef< T > llvm::ArrayRef< T >::copy (Allocator & A) inline
Definition at line 171 of file ArrayRef.h.
data()
template<typename T> const T * llvm::ArrayRef< T >::data () const inline
Definition at line 139 of file ArrayRef.h.
Referenced by llvm::codeview::DebugChecksumsSubsection::addChecksum(), analyzeHeader(), llvm::orc::SelfExecutorProcessControl::callWrapperAsync(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::ConstantFoldGetElementPtr(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::MutableArrayRef< char >::data(), discoverTypeIndices(), discoverTypeIndices(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), llvm::object::doesXCOFFTracebackTableBegin(), dumpLocationExpr(), llvm::object::ELFFile< ELFT >::dynamicEntries(), eat12Bytes(), eat16Bytes(), eatBytes(), llvm::X86_MC::findX86_64PltEntries(), llvm::X86_MC::findX86PltEntries(), llvm::codeview::forEachCodeViewRecord(), llvm::fullyRecomputeLiveIns(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::codeview::getBytesAsCharacters(), llvm::object::ResourceSectionRef::getContents(), llvm::object::COFFObjectFile::getDebugPDBInfo(), getExpressionFrameOffset(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantExpr::getGetElementPtr(), llvm::DenseMapInfo< ArrayRef< T >, void >::getHashValue(), M68kDisassembler::getInstruction(), getLEB128(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::getSectionName(), getUUID(), llvm::MipsTargetLowering::HandleByVal(), handleFieldList(), handleMethodOverloadList(), llvm::pdb::hashStringV2(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::codeview::CodeViewRecordIO::mapGuid(), nextLEB(), parseImmediate(), llvm::BinaryStreamReader::readArray(), readBinaryIdsInternal(), llvm::jitlink::CompactUnwindTraits< CRTPImpl, PtrSize >::readEncoding(), readInstruction32(), llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readObject(), llvm::jitlink::CompactUnwindTraits< CRTPImpl, PtrSize >::readPCRangeSize(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), llvm::jitlink::Block::setContent(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent(), llvm::stable_hash_combine(), verifyNoteSection(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), and writeWithCommas().
drop_back()
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::drop_back (size_t N = 1) const inline
Drop the last N elements of the array.
Definition at line 201 of file ArrayRef.h.
Referenced by llvm::DIExpression::appendToStack(), EltsFromConsecutiveLoads(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), llvm::sampleprof::SampleContext::isPrefixOf(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::orc::shared::runDeallocActions(), simplifyGEPInst(), simplifyInstructionWithOperands(), and llvm::cas::ondisk::OnDiskGraphDB::validate().
drop_front()
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::drop_front (size_t N = 1) const inline
Drop the first N elements of the array.
Definition at line 195 of file ArrayRef.h.
Referenced by buildCopyFromRegs(), clusterSortPtrAccesses(), combineShuffleToZeroExtendVectorInReg(), computeBlockRuns(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), dropInitialDeref(), llvm::objcopy::dxbc::dumpPartToFile(), FindFirstNonCommonLetter(), llvm::codeview::forEachCodeViewRecord(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), llvm::fuzzerop::gepDescriptor(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), llvm::DIExpression::getSingleLocationExpressionElements(), handleFieldList(), handleMethodOverloadList(), handlePointer(), llvm::codeview::GloballyHashedType::hashType(), llvm::orc::lookupSymbolsAsyncHelper(), llvm::IntegerInclusiveIntervalUtils::mergeAdjacentIntervals(), optimizeModularFormat(), readMemprof(), resolveTypeIndexReferences(), translateLoopMetadata(), llvm::pdb::typesetItemList(), and writeWithCommas().
drop_until()
template<typename T> template<class PredicateT> ArrayRef< T > llvm::ArrayRef< T >::drop_until (PredicateT Pred) const inline
Return a copy of *this with the first N elements not satisfying the given predicate removed.
Definition at line 214 of file ArrayRef.h.
drop_while()
template<typename T> template<class PredicateT> ArrayRef< T > llvm::ArrayRef< T >::drop_while (PredicateT Pred) const inline
Return a copy of *this with the first N elements satisfying the given predicate removed.
Definition at line 208 of file ArrayRef.h.
Referenced by llvm::constructSeqOffsettoOrigRowMapping().
empty()
template<typename T> bool llvm::ArrayRef< T >::empty () const inline
empty - Check if the array is empty.
Definition at line 137 of file ArrayRef.h.
Referenced by llvm::lto::LTO::add(), llvm::orc::IRSymbolMapper::add(), addBasicBlockMetadata(), llvm::codeview::DebugChecksumsSubsection::addChecksum(), addMask(), llvm::LazyCallGraph::addSplitRefRecursiveFunctions(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), addVPMetadata(), slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::adjustExtracts(), llvm::annotateValueSite(), llvm::MCObjectStreamer::appendContents(), llvm::DIExpression::appendToStack(), llvm::DominatorTreeBase< BlockT, false >::applyUpdates(), llvm::AttributeListImpl::AttributeListImpl(), buildCompressMask(), buildExtractionBlockSet(), buildFixItLine(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildInstr(), canClobberPhysRegDefs(), canClobberReachingPhysRegUse(), CC_AArch64_Custom_Block(), CC_ARM_AAPCS_Custom_Aggregate(), CC_X86_64_I128(), llvm::cloneAndAdaptNoAliasScopes(), llvm::cloneAndAdaptNoAliasScopes(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::collectGlobalObjectNameStrings(), combineOrders(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), computeBlockRuns(), computeCalleeSaveRegisterPairs(), computeExcessPressureDelta(), computeMergedBranchWeights(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertValueInstruction(), llvm::constructSeqOffsettoOrigRowMapping(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::coverage::BinaryCoverageReader::create(), createMIBNode(), llvm::OpenMPIRBuilder::createReductionsGPU(), llvm::OpenMPIRBuilder::createSingle(), createTaskWithPrivatesTy(), deepWriteArchive(), llvm::FileCheckPatternContext::defineCmdlineVariables(), doesNotNeedToSchedule(), llvm::objcopy::dxbc::dumpPartToFile(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::BPFAsmPrinter::emitJumpTableInfo(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::object::MachOObjectFile::exports(), llvm::sandboxir::DependencyGraph::extend(), llvm::ThreadSafeTrieRawHashMapBase::find(), FindFirstNonCommonLetter(), llvm::FindInsertedValue(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), foldSwitchToSelect(), llvm::codeview::forEachCodeViewRecord(), gatherPossiblyVectorizableLoads(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::InstrProfCorrelator::get(), llvm::RecordRecTy::get(), getBuildDwordsVector(), llvm::MCSchedModel::getBypassDelayCycles(), llvm::omp::getCompoundConstruct(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::RegAllocBase::getErrorAssignment(), getExpressionFrameOffset(), getFeatures(), llvm::MCSchedModel::getForwardingDelayCycles(), llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), llvm::HexagonRegisterInfo::getHexagonSubRegIndex(), getIndexedTypeInternal(), getIntrinsicNameImpl(), getMaxCalleeSavedReg(), llvm::DebugLoc::getMergedLocations(), llvm::DILocation::getMergedLocations(), getOpenFileImpl(), getOrInsertIntrinsicDeclarationImpl(), llvm::SystemZTTIImpl::getScalarizationOverhead(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::object::MachOObjectFile::getSegmentContents(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::X86TTIImpl::getShuffleCost(), getShufflevectorNumGroups(), slpvectorizer::BoUpSLP::getTreeCost(), llvm::DFAPacketizer::getUsedResources(), getUUID(), llvm::CallLowering::handleAssignments(), llvm::SelectionDAGBuilder::handleDebugValue(), handleFieldList(), handleMethodOverloadList(), llvm::ThreadSafeTrieRawHashMapBase::insert(), llvm::LanaiInstrInfo::insertBranch(), insertLifetimeMarkersSurroundingCall(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), insertUseHolderAfter(), llvm::sandboxir::Interval< T >::Interval(), slpvectorizer::BoUpSLP::isIdentityOrder(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), isMaskedLoadCompress(), llvm::ConstantRangeList::isOrderedRanges(), isReverseOrder(), llvm::coverage::CoverageMapping::load(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), llvm::orc::lookupSymbolsAsyncHelper(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::BPFCallLowering::lowerReturn(), llvm::M68kCallLowering::lowerReturn(), llvm::MipsCallLowering::lowerReturn(), llvm::PPCCallLowering::lowerReturn(), llvm::RISCVCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), lowerV8I16GeneralSingleInputShuffle(), llvm::fuzzerop::matchFirstLengthWAnyType(), llvm::fuzzerop::matchFirstType(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::IntegerInclusiveIntervalUtils::mergeAdjacentIntervals(), mergeComparisons(), llvm::operator<<(), llvm::raw_ostream::operator<<(), optimizeModularFormat(), llvm::performOptimizedStructLayout(), postUnswitch(), llvm::VPIRMetadata::print(), llvm::IntegerInclusiveIntervalUtils::printIntervals(), PrintMessage(), slpvectorizer::BoUpSLP::processBuildVector(), llvm::promoteCallWithVTableCmp(), llvm::PromoteMemToReg(), llvm::propagateMetadata(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::LazyCallGraph::removeDeadFunctions(), slpvectorizer::BoUpSLP::removeInstructionsAndOperands(), slpvectorizer::BoUpSLP::reorderBottomToTop(), slpvectorizer::BoUpSLP::reorderTopToBottom(), resolveTypeIndexReferences(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), llvm::AVRFrameLowering::restoreCalleeSavedRegisters(), llvm::CSKYFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::SIRegisterInfo::restoreSGPR(), llvm::lto::LTO::run(), llvm::orc::shared::runDeallocActions(), llvm::MCJIT::runFunction(), llvm::MachineInstr::setMemRefs(), llvm::SelectionDAG::setNodeMemRefs(), llvm::VFABI::setVectorVariantNames(), llvm::RISCVInstrInfo::shouldClusterMemOps(), llvm::SIInstrInfo::shouldClusterMemOps(), simplifyGEPInst(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::CSKYFrameLowering::spillCalleeSavedRegisters(), llvm::LoongArchFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillSGPR(), SplitBlockPredecessorsImpl(), llvm::cas::ondisk::OnDiskGraphDB::store(), llvm::CodeViewYAML::toCodeViewSubsectionList(), slpvectorizer::BoUpSLP::transformNodes(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), llvm::pdb::typesetItemList(), llvm::SLPVectorizerPass::vectorizeCmpInsts(), slpvectorizer::BoUpSLP::vectorizeTree(), llvm::VPInterleaveBase::VPInterleaveBase(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), and writeWithCommas().
end()
template<typename T> iterator llvm::ArrayRef< T >::end () const inline
Definition at line 131 of file ArrayRef.h.
Referenced by addMask(), llvm::DebugLocEntry::addValues(), allSameBlock(), allSameOpcode(), llvm::object::DynamicRelocRef::arm64x_reloc_end(), llvm::const_iterator< MemoryLocation >::assign(), llvm::DIExpressionCursor::assignNewExpr(), llvm::ELFAttrs::attrTypeAsString(), llvm::ELFAttrs::attrTypeFromString(), buildFixItLine(), llvm::Interpreter::callFunction(), canSinkStoreWithNoAliasCheck(), slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::collectGlobalObjectNameStrings(), combineX86ShufflesRecursively(), CompressEVEXImpl(), llvm::ComputeLinearIndex(), llvm::concatenateVectors(), convertSSEToAVX(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), CreateGCRelocates(), createMergedFunction(), llvm::DIExpression::elements_end(), llvm::MCDwarfFrameEmitter::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::FindInsertedValue(), findTargetSubtable(), gatherPossiblyVectorizableLoads(), llvm::gsym::GsymReader::getAddressOffsetIndex(), llvm::DagInit::getArgNo(), llvm::omp::getCompoundConstruct(), llvm::StructLayout::getElementContainingOffset(), getExpressionFrameOffset(), llvm::getFMA3Group(), llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), getGEPCosts(), llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), llvm::X86RegisterInfo::getLargestLegalSuperClass(), llvm::omp::getLeafOrCompositeConstructs(), getLEB128(), llvm::sandboxir::VecUtils::getLowest(), getNewOpcFromTable(), getNoopInput(), getRegLanes(), getSameOpcode(), llvm::getShuffleMaskWithWidestElts(), growShuffleMask(), handleCallSite(), llvm::pdb::hashStringV1(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), insertCandidatesWithPendingInjections(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::omp::isCompositeConstruct(), isFixedVectorShuffle(), llvm::LiveRange::isLiveAtIndexes(), isMaskedLoadCompress(), isSubset(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), llvm::coverage::CoverageMapping::load(), Lookup(), lookupFoldTableImpl(), lookupLLVMIntrinsicByName(), lowerV8I16GeneralSingleInputShuffle(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), mergeComparisons(), llvm::CallBase::populateBundleOperandInfos(), llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read(), llvm::MachineFunction::setCallSiteLandingPad(), llvm::X86MachineFunctionInfo::setPreallocatedArgOffsets(), llvm::setProfMetadata(), llvm::gsym::GsymCreator::setUUID(), llvm::DbgValueHistoryMap::trimLocationRanges(), llvm::misexpect::verifyMisExpect(), and writeToResolutionFile().
equals()
template<typename T> bool llvm::ArrayRef< T >::equals (ArrayRef< T > RHS) const inline
equals - Check for element-wise equality.
Definition at line 178 of file ArrayRef.h.
Referenced by combineTargetShuffle(), and llvm::operator==().
front()
template<typename T> const T & llvm::ArrayRef< T >::front () const inline
front - Get the first element.
Definition at line 145 of file ArrayRef.h.
Referenced by buildCompressMask(), buildCopyToRegs(), llvm::CSEMIRBuilder::buildInstr(), calcPredicateUsingInteger(), calculateShufflevectorMask(), canConvertToFMA(), canSinkInstructions(), canSinkStoreWithNoAliasCheck(), slpvectorizer::BoUpSLP::canVectorizeLoads(), clusterSortPtrAccesses(), computeBlockRuns(), llvm::constructSeqOffsettoOrigRowMapping(), convertToGuardPredicates(), DecodeFixedType(), deepWriteArchive(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), gatherPossiblyVectorizableLoads(), generateNewInstTree(), llvm::InstrProfCorrelator::get(), getCommonMetadata(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::RegAllocBase::getErrorAssignment(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::sandboxir::VecUtils::getLowest(), getShufflevectorNumGroups(), llvm::DFAPacketizer::getUsedResources(), handleFieldList(), hasSupportedLoopDepth(), isFreeConcat(), isMaskedLoadCompress(), isSwitchDense(), llvm::coverage::CoverageMapping::load(), llvm::orc::lookupSymbolsAsyncHelper(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), memOpsHaveSameBasePtr(), memOpsHaveSameBasePtr(), mergeCompatibleInvokesImpl(), mergeConsecutivePartStores(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), shortBundleName(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), llvm::RISCVInstrInfo::shouldClusterMemOps(), llvm::SIInstrInfo::shouldClusterMemOps(), and llvm::widenShuffleMaskElts().
operator std::vector< T >()
template<typename T> llvm::ArrayRef< T >::operator std::vector< T > () const inline
Definition at line 278 of file ArrayRef.h.
operator=() [1/2]
template<typename T> template<typename U> std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & llvm::ArrayRef< T >::operator= (std::initializer_list< U >) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
operator=() [2/2]
template<typename T> template<typename U> std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & llvm::ArrayRef< T >::operator= (U && Temporary) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
Referenced by llvm::OwningArrayRef< T >::operator=().
operator[]()
template<typename T> const T & llvm::ArrayRef< T >::operator[] (size_t Index) const inline
Definition at line 247 of file ArrayRef.h.
rbegin()
template<typename T> reverse_iterator llvm::ArrayRef< T >::rbegin () const inline
Definition at line 133 of file ArrayRef.h.
Referenced by EltsFromConsecutiveLoads(), getNoopInput(), getPropIndex(), llvm::ScheduleDAGMI::initQueues(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
rend()
template<typename T> reverse_iterator llvm::ArrayRef< T >::rend () const inline
Definition at line 134 of file ArrayRef.h.
Referenced by EltsFromConsecutiveLoads(), getNoopInput(), getPropIndex(), llvm::ScheduleDAGMI::initQueues(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
size()
template<typename T> size_t llvm::ArrayRef< T >::size () const inline
size - Get the array size.
Definition at line 142 of file ArrayRef.h.
Referenced by llvm::dwarf_linker::parallel::DIEGenerator::addBlockAttribute(), llvm::codeview::DebugChecksumsSubsection::addChecksum(), llvm::dwarf_linker::parallel::DIEGenerator::addLocationAttribute(), llvm::DwarfCompileUnit::addLocationAttribute(), addMask(), addOperands(), llvm::gsym::GsymReader::addressForIndex(), addSaveRestoreRegs(), llvm::msf::MSFBuilder::addStream(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), llvm::InstrProfRecord::addValueData(), llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::DbgVariableRecord::addVariableLocationOps(), addVPMetadata(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateRegBlock(), allocateSGPR32InputImpl(), allocateVGPR32Input(), llvm::analyzeArguments(), slpvectorizer::BoUpSLP::analyzeConstantStrideCandidate(), analyzeHeader(), slpvectorizer::BoUpSLP::analyzeRtStrideCandidate(), llvm::object::ELFFile< ELFT >::android_relas(), llvm::MCObjectStreamer::appendContents(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyUpdates(), llvm::yaml::BinaryRef::binary_size(), buildBitSets(), buildClonedLoopBlocks(), buildClonedLoops(), buildCompressMask(), buildCopyFromRegs(), buildCopyToRegs(), llvm::memprof::MemProfSummary::buildDataAccessSummary(), buildFatArchList(), llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstr(), llvm::BuildMI(), llvm::AMDGPULegalizerInfo::buildMultiply(), buildNew(), llvm::codelayout::calcExtTspScore(), llvm::codelayout::calcExtTspScore(), calcPredicateUsingBooleans(), calcPredicateUsingInteger(), llvm::calculateRegisterUsageForPlan(), calculateRtStride(), llvm::Interpreter::callFunction(), llvm::orc::SelfExecutorProcessControl::callWrapperAsync(), canonicalHeaderAndLatch(), canonicalizeDwarfOperations(), llvm::sandboxir::LegalityAnalysis::canVectorize(), slpvectorizer::BoUpSLP::canVectorizeLoads(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), checkARM64Instructions(), CheckForLiveRegDefMasked(), checkOperandCount(), llvm::cleanUpTempFiles(), llvm::cloneAndAdaptNoAliasScopes(), llvm::cloneAndAdaptNoAliasScopes(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::MachineInstr::cloneMergedMemRefs(), clusterSortPtrAccesses(), llvm::FunctionComparator::cmpOperations(), coerceArguments(), llvm::collectGlobalObjectNameStrings(), combineOrders(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), CompareSCEVComplexity(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::compareTypes(), llvm::LoopVectorizationPlanner::computeBestVF(), llvm::codelayout::computeCacheDirectedLayout(), computeCalleeSaveRegisterPairs(), computeExcessPressureDelta(), llvm::codelayout::computeExtTspLayout(), computeIndirectRegIndex(), llvm::SelectionDAG::computeKnownBits(), computeKnownFPClass(), llvm::ComputeMappedEditDistance(), computeMaxPressureDelta(), computeMemberData(), computeMergedBranchWeights(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::mca::computeProcResourceMasks(), llvm::concatenateVectors(), llvm::ConstantFoldGetElementPtr(), llvm::ConstraintSystem::ConstraintSystem(), convertToGuardPredicates(), llvm::detail::IEEEFloat::convertToInteger(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::GlobalObject::copyMetadata(), llvm::SIInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), costShuffleViaSplitting(), costShuffleViaVRegSplitting(), llvm::CallBrInst::Create(), llvm::GetElementPtrConstantExpr::Create(), llvm::GetElementPtrInst::Create(), llvm::sandboxir::GetElementPtrInst::create(), createAndCheckVectorTypesForPromotion(), llvm::jitlink::ppc64::createAnonymousPointerJumpStub(), llvm::MDBuilder::createBranchWeights(), CreateGCRelocates(), createIndexMap(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::jitlink::LinkGraph::createMutableContentBlock(), llvm::createPHIsForSplitLoopExit(), llvm::OpenMPIRBuilder::createReductions(), llvm::OpenMPIRBuilder::createReductionsGPU(), llvm::createSanitizerCtorAndInitFunctions(), llvm::OpenMPIRBuilder::createScan(), llvm::OpenMPIRBuilder::createSections(), llvm::OpenMPIRBuilder::createSingle(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAATypeNode(), createThunk(), createTuple(), decodeBBAddrMapImpl(), DecodeIITType(), llvm::DecodePSHUFBMask(), DecodeRegisterClass(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::object::Decompressor::decompress(), llvm::DeleteDeadBlocks(), llvm::GCNIterativeScheduler::detachSchedule(), llvm::object::doesXCOFFTracebackTableBegin(), dumpLocationExpr(), llvm::objcopy::dxbc::dumpPartToFile(), llvm::dumpRegSetPressure(), llvm::objcopy::coff::dumpSection(), llvm::objcopy::wasm::dumpSectionToFile(), eat12Bytes(), eat16Bytes(), eatBytes(), EltsFromConsecutiveLoads(), llvm::MCDwarfLineTableHeader::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::BPFAsmPrinter::emitJumpTableInfo(), llvm::OpenMPIRBuilder::emitTargetKernel(), expandBufferLoadIntrinsic(), expandSGPRCopy(), llvm::ThreadSafeTrieRawHashMap< DataT, sizeof(HashType)>::find(), llvm::ThreadSafeTrieRawHashMap< DataT, sizeof(HashType)>::find(), findBestNonTrivialUnswitchCandidate(), FindFirstNonCommonLetter(), llvm::FindInsertedValue(), findLiveReferences(), llvm::wholeprogramdevirt::findLowestOffset(), FindSequence(), llvm::lto::findThinLTOModule(), llvm::X86_MC::findX86_64PltEntries(), llvm::X86_MC::findX86PltEntries(), llvm::fitWeights(), fixupOrderingIndices(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldSwitchToSelect(), llvm::InstCombinerImpl::foldVectorBinop(), llvm::codeview::forEachCodeViewRecord(), formSplatFromShuffles(), llvm::CodeViewYAML::fromDebugH(), llvm::fullyRecomputeLiveIns(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), gatherPossiblyVectorizableLoads(), generateNewInstTree(), llvm::Attribute::get(), llvm::CondOpInit::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::DagInit::get(), llvm::InstrProfCorrelator::get(), llvm::RecordKeeper::getAllDerivedDefinitions(), getAltInstrMask(), llvm::getBitcodeFileContents(), getBuildDwordsVector(), llvm::codeview::getBytesAsCharacters(), llvm::object::ResourceSectionRef::getContents(), llvm::cas::builtin::BuiltinCAS::getDataSize(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::getDeinterleavedVectorType(), llvm::getDescImpl(), llvm::object::ELFFile< ELFT >::getEntry(), llvm::codeview::VFTableShapeRecord::getEntryCount(), getExpressionFrameOffset(), llvm::MachineFunction::getFilterIDFor(), llvm::CCState::getFirstUnallocated(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getGetElementPtr(), getHalfShuffleMask(), llvm::sys::detail::getHostCPUNameForARM(), getHostCPUNameForARMFromComponents(), llvm::AArch64Disassembler::getInstruction(), llvm::AMDGPUDisassembler::getInstruction(), llvm::BasicTTIImplBase< BasicTTIImpl >::getInterleavedMemoryOpCost(), llvm::HexagonTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), getLEB128(), getMaxCalleeSavedReg(), llvm::DebugLoc::getMergedLocations(), llvm::DILocation::getMergedLocations(), getNoopInput(), getOpenFileImpl(), llvm::HvxSelector::getPerfectCompletions(), getPropIndex(), llvm::AArch64RegisterInfo::getRegAllocationHints(), llvm::MachineTraceMetrics::Trace::getResourceDepth(), llvm::MachineTraceMetrics::Trace::getResourceLength(), getSameOpcode(), llvm::SystemZTTIImpl::getScalarizationOverhead(), llvm::object::WasmObjectFile::getSectionSize(), llvm::getShuffleMaskWithWidestElts(), getShufflevectorNumGroups(), getStatepointArgs(), getStatepointBundles(), llvm::abi::TypeBuilder::getUnionType(), llvm::RegPressureTracker::getUpwardPressureDelta(), getUUID(), llvm::SelectionDAG::getVTList(), llvm::CodeViewYAML::GlobalHash::GlobalHash(), growShuffleMask(), handleAllocSite(), llvm::MipsTargetLowering::HandleByVal(), handleCallSite(), llvm::cas::BuiltinObjectHasher< HasherT >::hashObject(), llvm::pdb::hashStringV2(), hasSupportedLoopDepth(), llvm::mustache::hasTextAhead(), llvm::hasUTF16ByteOrderMark(), hasUTF8ByteOrderMark(), shuffles::hi(), incomingValuesAreCompatible(), llvm::coro::AnyRetconABI::init(), llvm::ThreadSafeTrieRawHashMapBase::insert(), llvm::LanaiInstrInfo::insertBranch(), insertCandidatesWithPendingInjections(), llvm::insertMultibyteShift(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), interleaveVectors(), inversePermutation(), isBigEndian(), llvm::omp::isCompositeConstruct(), isFixedVectorShuffle(), isFreeConcat(), slpvectorizer::BoUpSLP::isIdentityOrder(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), slpvectorizer::BoUpSLP::isLoadCombineCandidate(), isMaskedLoadCompress(), llvm::ConstantRangeList::isOrderedRanges(), isReplicationMaskWithParams(), isReverseOrder(), isShuffleEquivalent(), isStrictSubset(), isSubset(), isSwitchDense(), isTargetShuffleEquivalent(), llvm::BinaryItemTraits< codeview::CVSymbol >::length(), llvm::codeview::limitSymbolArrayToScope(), shuffles::lo(), llvm::coverage::CoverageMapping::load(), llvm::object::ResourceSectionRef::load(), lowerBitreverseShuffle(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::RISCVTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleaveIntrinsicToStore(), llvm::RISCVTargetLowering::lowerInterleaveIntrinsicToStore(), llvm::AArch64CallLowering::lowerReturn(), llvm::SPIRVCallLowering::lowerReturn(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), llvm::orc::makeJITDylibSearchOrder(), llvm::TargetLowering::makeLibCall(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::fuzzerop::matchSecondType(), llvm::CombinerHelper::matchShuffleUndefRHS(), memOpsHaveSameBaseOperands(), mergeComparisons(), mergeCompatibleInvokes(), mergeCompatibleInvokesImpl(), mergeConsecutivePartStores(), mergeVectorRegsToResultRegs(), multikeySort(), needsConstrainedOpcode(), nextByte(), nextLEB(), llvm::sampleprof::SampleContext::operator<(), llvm::raw_ostream::operator<<(), optimizeDwarfOperations(), slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeModularFormat(), OptimizeNonTrivialIFuncs(), llvm::OwningArrayRef< T >::OwningArrayRef(), packSegmentMask(), llvm::ELFCompactAttrParser::parse(), llvm::object::DirectX::PSVRuntimeInfo::parse(), parseImmediate(), llvm::ELFCompactAttrParser::parseStringAttribute(), peek(), llvm::AsmLexer::peekTokens(), performBlockTailMerging(), llvm::performOptimizedStructLayout(), populateReductionFunction(), llvm::prepareTempFiles(), llvm::prettyPrintBaseTypeRef(), llvm::VPIRMetadata::print(), processPSInputArgs(), llvm::processShuffleMasks(), llvm::AttributeImpl::Profile(), ProfileCondOpInit(), ProfileRecordRecTy(), llvm::propagateMetadata(), llvm::cas::ondisk::OnDiskKeyValueDB::put(), llvm::detail::BCRecordCoding< ElementTy >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), readBinaryIdsInternal(), llvm::orc::InProcessMemoryAccess::readBuffersAsync(), llvm::AppendingBinaryByteStream::readBytes(), llvm::BinaryStreamReader::readCString(), llvm::jitlink::CompactUnwindTraits< CRTPImpl, PtrSize >::readEncoding(), llvm::BinaryStreamReader::readFixedString(), readInstruction16(), readInstruction16(), readInstruction16(), readInstruction16(), readInstruction24(), readInstruction32(), readInstruction32(), readInstruction32(), readInstruction32(), readInstruction32(), readInstruction64(), readInstruction64(), llvm::BinaryStreamReader::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::jitlink::CompactUnwindTraits< CRTPImpl, PtrSize >::readPCRangeSize(), llvm::orc::InProcessMemoryAccess::readPointersAsync(), llvm::orc::InProcessMemoryAccess::readStringsAsync(), llvm::orc::InProcessMemoryAccess::readUInt16sAsync(), llvm::orc::InProcessMemoryAccess::readUInt32sAsync(), llvm::orc::InProcessMemoryAccess::readUInt64sAsync(), llvm::orc::InProcessMemoryAccess::readUInt8sAsync(), llvm::readWideAPInt(), rebuildLoopAfterUnswitch(), llvm::BuildVectorSDNode::recastRawBits(), llvm::recognizeBSwapOrBitReverseIdiom(), recomputeLiveInValues(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::jitlink::relaxBlock(), relocationViaAlloca(), slpvectorizer::BoUpSLP::reorderBottomToTop(), slpvectorizer::BoUpSLP::reorderTopToBottom(), replicateMask(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::IRTranslator::runOnMachineFunction(), SelectOpcodeFromVT(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), llvm::StableFunctionMapRecord::serialize(), llvm::jitlink::Block::setContent(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent(), LiveDebugValues::DbgValue::setDbgOpIDs(), llvm::jitlink::Block::setMutableContent(), llvm::SelectionDAG::setNodeMemRefs(), llvm::MCDecodedPseudoProbeInlineTree::setProbes(), setupBranchForGuard(), llvm::MCFragment::setVarContents(), shortBundleName(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), shouldUnrollMultiExitLoop(), simplifyExtractValueInst(), simplifyGEPInst(), llvm::simplifyInstructionWithOperands(), simplifyInstructionWithOperands(), llvm::mca::SourceMgr::size(), llvm::sortPtrAccesses(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::XtensaFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillSGPR(), splitGlobal(), splitMask(), llvm::stable_hash_combine(), stackFrameIncludesInlinedCallStack(), llvm::ARMBaseInstrInfo::SubsumesPredicate(), llvm::PPCInstrInfo::SubsumesPredicate(), llvm::orc::SymbolLookupSet::SymbolLookupSet(), llvm::OpenMPIRBuilder::tileLoops(), llvm::ConstantRangeListAttributeImpl::totalSizeToAlloc(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), llvm::pdb::typesetItemList(), unswitchNontrivialInvariants(), UpdateAnalysisInformation(), UpdatePHINodes(), shuffles::vdeal(), shuffles::vdealb4w(), shuffles::vdealvdd(), llvm::misexpect::verifyMisExpect(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::orc::DebugObject::visitSectionLoadAddresses(), llvm::orc::DebugObject::visitSections(), shuffles::vpack(), shuffles::vshuff(), shuffles::vshuffvdd(), llvm::WebAssembly::wasmSymbolSetType(), llvm::widenShuffleMaskElts(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::offloading::wrapSYCLBinaries(), llvm::write(), llvm::writeArchiveToStream(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::BinaryStreamWriter::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), writeDIE(), llvm::writeIndex(), llvm::orc::writeMachOStruct(), llvm::sampleprof::SampleProfileWriterBinary::writeSummary(), writeSymbolMap(), writeUniversalArchsToStream(), llvm::object::writeUniversalBinaryToStream(), and writeWithCommas().
slice() [1/2]
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::slice (size_t N) const inline
slice(n) - Chop off the first N elements of the array.
Definition at line 192 of file ArrayRef.h.
slice() [2/2]
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::slice (size_t N, size_t M) const inline
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
Definition at line 186 of file ArrayRef.h.
Referenced by llvm::CCState::AllocateRegBlock(), buildNew(), buildTreeReduction(), slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldInsertValueInstruction(), DecodeFixedType(), llvm::dlltoolDriverMain(), eat12Bytes(), eat16Bytes(), eatBytes(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::FindInsertedValue(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::getBitcodeFileContents(), llvm::MCFragment::getFixups(), getIndexedTypeInternal(), llvm::AMDGPUDisassembler::getInstruction(), getShufflevectorNumGroups(), llvm::jitlink::Symbol::getSymbolContent(), llvm::MCFragment::getVarFixups(), llvm::pdb::hashStringV2(), llvm::codeview::GloballyHashedType::hashType(), isHorizontalBinOp(), isLexicographicallyPositive(), llvm::libDriverMain(), llvm::MCInstPrinter::matchAliasPatterns(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::jitlink::ppc64::pickStub(), slpvectorizer::BoUpSLP::processBuildVector(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::AppendingBinaryByteStream::readBytes(), llvm::msf::MappedBlockStream::readBytes(), llvm::AppendingBinaryByteStream::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::jitlink::relaxBlock(), llvm::Interpreter::runFunction(), simplifyExtractValueInst(), and llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
take_back()
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::take_back (size_t N = 1) const inline
Return a copy of *this with only the last N elements.
Definition at line 226 of file ArrayRef.h.
Referenced by shuffles::hi().
take_front()
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::take_front (size_t N = 1) const inline
Return a copy of *this with only the first N elements.
Definition at line 219 of file ArrayRef.h.
Referenced by buildCopyFromRegs(), llvm::codeview::forEachCodeViewRecord(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), llvm::codeview::GloballyHashedType::hashType(), llvm::object::MinidumpFile::Memory64Iterator::inc(), llvm::sampleprof::SampleContext::isPrefixOf(), shuffles::lo(), llvm::BinaryItemStream< T, Traits >::readBytes(), stackFrameIncludesInlinedCallStack(), llvm::pdb::typesetItemList(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and writeWithCommas().
take_until()
template<typename T> template<class PredicateT> ArrayRef< T > llvm::ArrayRef< T >::take_until (PredicateT Pred) const inline
Return the first N elements of this Array that don't satisfy the given predicate.
Definition at line 240 of file ArrayRef.h.
take_while()
template<typename T> template<class PredicateT> ArrayRef< T > llvm::ArrayRef< T >::take_while (PredicateT Pred) const inline
Return the first N elements of this Array that satisfy the given predicate.
Definition at line 234 of file ArrayRef.h.
vec()
template<typename T> std::vector< T > llvm::ArrayRef< T >::vec () const inline
Definition at line 271 of file ArrayRef.h.
Referenced by combineDIExpressions().
The documentation for this class was generated from the following files:
include/llvm/ADT/APInt.h
include/llvm/ADT/ArrayRef.h