LLVM: llvm::FileError Class Reference
llvm::FileError Class Reference final
This class wraps a filename and another Error.
#include "llvm/Support/Error.h"
Public Member Functions
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::string messageWithoutFileInfo () const
StringRef getFileName () const
Error takeError ()
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
Public Member Functions inherited from llvm::ErrorInfo< FileError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual std::string message () const
Return the error message as a string.
template<typename ErrorInfoT>
bool isA () const
Static Public Attributes
static char ID = 0
Friends
Error createFileError (const Twine &F, Error E)
Concatenate a source file path and/or name with an Error.
Error createFileError (const Twine &F, size_t Line, Error E)
Concatenate a source file path and/or name with line number and an Error.
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< FileError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
This class wraps a filename and another Error.
In some cases, an error needs to live along a 'source' name, in order to show more detailed information to the user.
Definition at line 1342 of file Error.h.
Member Function Documentation
convertToErrorCode()
std::error_code llvm::FileError::convertToErrorCode () const override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 103 of file Error.cpp.
getFileName()
StringRef llvm::FileError::getFileName () const inline
Definition at line 1363 of file Error.h.
log()
void llvm::FileError::log (raw_ostream & OS) const inline override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 1348 of file Error.h.
References assert().
messageWithoutFileInfo()
std::string llvm::FileError::messageWithoutFileInfo () const inline
Definition at line 1356 of file Error.h.
takeError()
Error llvm::FileError::takeError () inline
Definition at line 1365 of file Error.h.
Friends And Related Symbol Documentation
createFileError [1/2]
Error createFileError (const Twine & F, Error E) friend
Concatenate a source file path and/or name with an Error.
The resulting Error is unchecked.
Definition at line 1399 of file Error.h.
References E(), and F.
createFileError [2/2]
Error createFileError (const Twine & F, size_t Line, Error E) friend
Concatenate a source file path and/or name with line number and an Error.
The resulting Error is unchecked.
Definition at line 1405 of file Error.h.
References E(), and F.
Member Data Documentation
ID
char llvm::FileError::ID = 0 static
Definition at line 1370 of file Error.h.
The documentation for this class was generated from the following files:
include/llvm/Support/Error.h
lib/Testing/Support/Error.cpp