LLVM: llvm::MDNode Class Reference
llvm::MDNode Class Reference
Metadata node.
#include "llvm/IR/Metadata.h"
Public Types
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
LLVM_ABI TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
LLVM_ABI void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
bool hasGeneralizedMDString ()
Check if this is a valid generalized type metadata node.
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
LLVM_ABI void resolveCycles ()
Resolve cycles.
LLVM_ABI void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
LLVM_ABI bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
LLVM_ABI void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
LLVM_ABI void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
LLVM_ABI void dumpTree () const
User-friendly dump in tree shape.
LLVM_ABI void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static LLVM_ABI void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static LLVM_ABI MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static LLVM_ABI MDNode * intersect (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericNoaliasAddrspace (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
static LLVM_ABI MDNode * getMergedMemProfMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCallsiteMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCalleeTypeMetadata (const MDNode *A, const MDNode *B)
static LLVM_ABI CaptureComponents toCaptureComponents (const MDNode *MD)
Convert !captures metadata to CaptureComponents. MD may be nullptr.
static LLVM_ABI MDNode * fromCaptureComponents (LLVMContext &Ctx, CaptureComponents CC)
Convert CaptureComponents to !captures metadata.
Protected Types
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions
LLVM_ABI MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~MDNode ()=default
LLVM_ABI void * operator new (size_t Size, size_t NumOps, StorageType Storage)
LLVM_ABI void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
LLVM_ABI void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
LLVM_ABI void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
LLVM_ABI void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions
template<class T, class StoreT>
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T>
static T * storeImpl (T *N, StorageType Storage)
Friends
class ReplaceableMetadataImpl
class LLVMContextImpl
class DIAssignID
Additional Inherited Members
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Metadata node.
Metadata nodes can be uniqued, like constants, or distinct. Temporary metadata nodes (with full support for RAUW) can be used to delay uniquing until forward references are known. The basic metadata node is an MDTuple.
There is limited support for RAUW at construction time. At construction time, if any operand is a temporary node (or an unresolved uniqued node, which indicates a transitive temporary operand), the node itself will be unresolved. As soon as all operands become resolved, it will drop RAUW support permanently.
If an unresolved node is part of a cycle, resolveCycles() needs to be called on some member of the cycle once all temporary nodes have been replaced.
MDNodes can be large or small, as well as resizable or non-resizable. Large MDNodes' operands are allocated in a separate storage vector, whereas small MDNodes' operands are co-allocated. Distinct and temporary MDnodes are resizable, but only MDTuples support this capability.
Clients can add operands to resizable MDNodes using push_back().
Definition at line 1078 of file Metadata.h.
Member Typedef Documentation
mutable_op_range
using llvm::MDNode::mutable_op_range = iterator_range<MDOperand *> protected
Definition at line 1214 of file Metadata.h.
op_iterator
using llvm::MDNode::op_iterator = const MDOperand *
Definition at line 1429 of file Metadata.h.
op_range
using llvm::MDNode::op_range = iterator_range<op_iterator>
Definition at line 1430 of file Metadata.h.
Constructor & Destructor Documentation
MDNode() [1/2]
MDNode::MDNode (LLVMContext & Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2 = {}) protected
Definition at line 652 of file Metadata.cpp.
References isUniqued(), llvm::Metadata::Metadata(), setOperand(), and llvm::Metadata::Storage.
Referenced by concatenate(), deleteTemporary(), fromCaptureComponents(), getMergedCalleeTypeMetadata(), getMergedCallsiteMetadata(), getMergedMemProfMetadata(), getMergedProfMetadata(), getMostGenericAliasScope(), getMostGenericAlignmentOrDereferenceable(), getMostGenericFPMath(), getMostGenericNoaliasAddrspace(), getMostGenericRange(), getMostGenericTBAA(), intersect(), MDNode(), op_begin(), op_end(), operator new(), operator=(), and toCaptureComponents().
~MDNode()
llvm::MDNode::~MDNode () protected default
References AbstractManglingParser< Derived, Alloc >::NumOps, LLVM_ABI, and llvm::Metadata::Storage.
MDNode() [2/2]
llvm::MDNode::MDNode (const MDNode &) delete
References MDNode().
Member Function Documentation
classof()
bool llvm::MDNode::classof (const Metadata * MD) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 1451 of file Metadata.h.
References llvm::Metadata::getMetadataID(), and llvm::Metadata::Metadata().
clone()
TempMDNode MDNode::clone () const
Create a (temporary) clone of this.
Definition at line 669 of file Metadata.cpp.
References llvm::Metadata::getMetadataID(), and llvm_unreachable.
Referenced by llvm::DIType::clone(), cloneAndReplaceParentScope(), and updateSubprogramLinkageName().
concatenate()
MDNode * MDNode::concatenate (MDNode * A, MDNode * B) static
Methods for metadata merging.
Definition at line 1109 of file Metadata.cpp.
References A(), B(), llvm::SetVector< T, Vector, Set, N >::getArrayRef(), getOrSelfReference(), llvm::SetVector< T, Vector, Set, N >::insert(), and MDNode().
Referenced by AddAliasScopeMetadata(), llvm::LoopVersioning::getNoAliasMetadataFor(), PropagateCallSiteMetadata(), and propagateMemProfHelper().
deleteTemporary()
void MDNode::deleteTemporary (MDNode * N) static
Deallocate a node created by getTemporary.
Calls replaceAllUsesWith(nullptr) before deleting, so any remaining references will be reset.
Definition at line 1045 of file Metadata.cpp.
References assert(), MDNode(), and N.
Referenced by LLVMDisposeTemporaryMDNode(), LLVMMetadataReplaceAllUsesWith(), and llvm::TempMDNodeDeleter::operator()().
dropAllReferences()
void MDNode::dropAllReferences () protected
Definition at line 909 of file Metadata.cpp.
References getNumOperands(), I, and setOperand().
dumpTree() [1/2]
LLVM_DUMP_METHOD void MDNode::dumpTree () const
User-friendly dump in tree shape.
If M is provided, metadata nodes will be numbered canonically; otherwise, pointer addresses are substituted.
Note: this uses an explicit overload instead of default arguments so that the nullptr version is easy to call from a debugger.
Definition at line 5501 of file AsmWriter.cpp.
References dumpTree().
Referenced by dumpTree().
dumpTree() [2/2]
LLVM_DUMP_METHOD void MDNode::dumpTree (const Module * M) const
Definition at line 5504 of file AsmWriter.cpp.
References llvm::dbgs(), and printTree().
fromCaptureComponents()
MDNode * MDNode::fromCaptureComponents (LLVMContext & Ctx, CaptureComponents CC) static
Convert CaptureComponents to !captures metadata.
The return value may be nullptr.
Definition at line 1456 of file Metadata.cpp.
References assert(), llvm::capturesAddress(), llvm::capturesAddressIsNullOnly(), llvm::capturesAll(), llvm::capturesFullProvenance(), llvm::capturesNothing(), llvm::capturesReadProvenanceOnly(), get(), llvm::MDString::get(), MDNode(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by combineMetadata().
get()
MDTuple * llvm::MDNode::get (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1569 of file Metadata.h.
References llvm::MDTuple::get().
Referenced by llvm::adaptNoAliasScopes(), AddAliasScopeMetadata(), addFunctionTypeMutation(), addModuleFlags(), addRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), llvm::annotateValueSite(), llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), applyParallelAccessesMetadata(), llvm::OpenMPIRBuilder::applySimd(), llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata(), llvm::SPIRVGlobalRegistry::buildAssignType(), llvm::memprof::buildCallstackMetadata(), buildFrameDebugInfo(), llvm::buildMD(), llvm::hlsl::rootsig::MetadataBuilder::BuildRootSignature(), canonicalizeMetadataForValue(), llvm::DILocation::cloneWithDiscriminator(), collectCallSiteParameters(), llvm::DIExpression::constantFold(), constructEntryMetadata(), llvm::DIExpression::convertToNonVariadicExpression(), llvm::DIExpression::convertToUndefExpression(), llvm::DIExpression::convertToVariadicExpression(), llvm::GlobalObject::copyMetadata(), llvm::copyRangeMetadata(), createAccessTag(), llvm::MDBuilder::createAliasScope(), llvm::MDBuilder::createAliasScopeDomain(), llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createBasicType(), llvm::DIBuilder::createBinaryFixedPointType(), llvm::DIBuilder::createBitFieldMemberType(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MDBuilder::createBranchWeights(), llvm::MDBuilder::createCallbackEncoding(), llvm::MDBuilder::createCallees(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCommonBlock(), llvm::DIBuilder::createConstantValueExpression(), llvm::DIBuilder::createDecimalFixedPointType(), createDecorationIntrinsic(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createExpression(), CreateFailBB(), llvm::DIBuilder::createFile(), llvm::DIBuilder::createForwardDecl(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), llvm::DIBuilder::createFriend(), llvm::MDBuilder::createFunctionEntryCount(), llvm::MDBuilder::createGlobalObjectSectionPrefix(), llvm::DIBuilder::createGlobalVariableExpression(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::DIBuilder::createLabel(), llvm::DIBuilder::createLexicalBlockFile(), llvm::MDBuilder::createLLVMStats(), createLocalVariable(), llvm::DIBuilder::createMacro(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMemberType(), llvm::createMemCpyLoopKnownSize(), createMIBNode(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), createOrReplaceFragment(), llvm::MDBuilder::createPCSections(), llvm::createPGONameMetadata(), llvm::DIBuilder::createPointerType(), llvm::MDBuilder::createPseudoProbeDesc(), llvm::DIBuilder::createPtrAuthQualifiedType(), llvm::DIBuilder::createQualifiedType(), llvm::MDBuilder::createRange(), llvm::DIBuilder::createRationalFixedPointType(), llvm::DIBuilder::createReferenceType(), createRoundingModeDecoration(), llvm::MDBuilder::createRTTIPointerPrologue(), createSaturatedConversionDecoration(), llvm::DIBuilder::createSetType(), llvm::DIBuilder::createStaticMemberType(), createStringMetadata(), llvm::DIBuilder::createStringType(), llvm::DIBuilder::createStringType(), llvm::DIBuilder::createStringType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubrangeType(), llvm::DIBuilder::createSubroutineType(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAARoot(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::DIBuilder::createTemplateAlias(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::MDBuilder::createUnpredictable(), llvm::DIBuilder::createUnspecifiedType(), llvm::DIBuilder::createVariantMemberType(), llvm::DIBuilder::createVariantMemberType(), llvm::DIBuilder::createVariantPart(), llvm::DIBuilder::createVectorType(), llvm::MipsInstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), DisableAllLoopOptsOnLoop(), dropInitialDeref(), llvm::Instruction::dropLocation(), llvm::embedBufferInModule(), llvm::emitAMDGPUPrintfCall(), emitAssignName(), emitDbgAssign(), emitDXILVersionTupleMD(), TransferTracker::emitMOLoc(), emitResourceMetadata(), emitShaderModelVersionMD(), emitTopLevelLibraryNode(), emitValidatorVersionMD(), llvm::InstrumentationIRBuilder::ensureDebugInfo(), llvm::AAMDNodes::extendToTBAA(), llvm::DIExpression::extractAddressClass(), extractMDNode(), llvm::DIBuilder::finalize(), findBasePointer(), findPrologueEndLoc(), FixupDebugInfoForOutlinedFunction(), fixupDebugInfoPostExtraction(), llvm::DIExpression::foldConstantMath(), fromCaptureComponents(), llvm::TypedTrackingMDRef< MDNode >::get(), llvm::dxil::ResourceInfo::getAsMetadata(), llvm::getDebugValueLoc(), getEntryPropAsMetadata(), llvm::DebugLoc::getFnDebugLoc(), llvm::DbgLabelRecord::getLabel(), getMergedCalleeTypeMetadata(), llvm::DILocation::getMergedLocation(), getMostGenericNoaliasAddrspace(), getMostGenericRange(), llvm::LoopVersioning::getNoAliasMetadataFor(), llvm::offloading::getOffloadingEntryInitializer(), getOrCreateDebugLoc(), llvm::DIBuilder::getOrCreateGenericSubrange(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateTypeArray(), getOrSelfReference(), getSubprogram(), llvm::DILocation::getWithoutAtom(), HandleByValArgumentInit(), hostParallelCallback(), llvm::FunctionImporter::importFunctions(), inlineDebugLoc(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::SampleProfileProber::instrumentOneFunc(), interpretValues(), llvm::intersectAccessGroups(), llvm::DebugLoc::isSameSourceLocation(), LLVMDIBuilderCreateDebugLocation(), LLVMMDNodeInContext(), LLVMMDNodeInContext2(), lowerKernelArguments(), lowerPtrAnnotation(), llvm::makeFollowupLoopID(), markLoadsAsInvariant(), llvm::MDBuilder::mergeCallbackEncodings(), migrateDebugInfo(), moveFunctionData(), parseAnnotation(), postUnswitch(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::DIExpression::prependOpcodes(), processUse(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::memtag::readRegister(), llvm::RemapSourceAtom(), llvm::DIExpression::replaceArg(), llvm::DebugLoc::replaceInlinedAtSubprogram(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::AssignGUIDPass::run(), runImpl(), runOnFunction(), llvm::scaleProfData(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::sandboxir::Region::setAux(), llvm::setExplicitlyUnknownBranchWeights(), llvm::setExplicitlyUnknownFunctionEntryCount(), llvm::setKCFIType(), llvm::Loop::setLoopAlreadyUnrolled(), llvm::Loop::setLoopMustProgress(), llvm::IRBuilderBase::SetNoSanitizeMetadata(), llvm::Instruction::setNoSanitizeMetadata(), llvm::GlobalObject::setVCallVisibilityMetadata(), llvm::AAMDNodes::shiftTBAAStruct(), shortenAssignment(), splitGlobal(), stripLoopMDLoc(), llvm::stripNonLineTableDebugInfo(), transferSRADebugInfo(), translateBranchMetadata(), translateLoopMetadata(), TryToShrinkGlobalToBoolean(), llvm::uniteAccessGroups(), llvm::OpenMPIRBuilder::unrollLoopFull(), llvm::OpenMPIRBuilder::unrollLoopHeuristic(), llvm::OpenMPIRBuilder::unrollLoopPartial(), updateDVIWithLocation(), updateDVIWithLocations(), updateLoopMetadataDebugLocationsRecursive(), upgradeAMDGCNIntrinsicCall(), llvm::UpgradeModuleFlags(), llvm::UpgradeNVVMAnnotations(), upgradeNVVMIntrinsicCall(), llvm::UpgradeTBAANode(), upgradeX86IntrinsicCall(), and llvm::InstCombinerImpl::visitCallInst().
getContext()
LLVMContext & llvm::MDNode::getContext () const inline
Definition at line 1242 of file Metadata.h.
Referenced by llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), buildFrameDebugInfo(), llvm::DIBasicType::cloneImpl(), llvm::DILocation::cloneWithDiscriminator(), llvm::DIExpression::constantFold(), llvm::DIExpression::convertToNonVariadicExpression(), llvm::DIExpression::convertToUndefExpression(), llvm::DIExpression::convertToVariadicExpression(), createAccessTag(), llvm::DbgVariableRecord::createDebugIntrinsic(), llvm::DIExpression::createFragmentExpression(), createOrReplaceFragment(), dropInitialDeref(), TransferTracker::emitMOLoc(), llvm::AAMDNodes::extendToTBAA(), llvm::DIExpression::extractAddressClass(), fixupLineNumbers(), llvm::DIExpression::foldConstantMath(), llvm::DILocation::getMergedLocation(), llvm::DILocation::getWithoutAtom(), llvm::makeFollowupLoopID(), llvm::DIExpression::prependOpcodes(), llvm::at::remapAssignID(), llvm::DIExpression::replaceArg(), llvm::DbgVariableIntrinsic::setVariable(), llvm::AAMDNodes::shiftTBAAStruct(), storeDistinctInContext(), transferSRADebugInfo(), llvm::uniteAccessGroups(), updateLoopMetadataDebugLocationsImpl(), and llvm::UpgradeTBAANode().
getDistinct()
MDTuple * llvm::MDNode::getDistinct (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1577 of file Metadata.h.
References llvm::MDTuple::getDistinct().
Referenced by addBasicBlockMetadata(), llvm::DebugLoc::appendInlinedAt(), applyParallelAccessesMetadata(), llvm::DICompositeType::buildODRType(), llvm::MDBuilder::createAnonymousAARoot(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createGlobalVariableExpression(), llvm::DIBuilder::createLexicalBlock(), fixupLineNumbers(), getSubprogram(), llvm::makePostTransformationMetadata(), llvm::sandboxir::Region::Region(), stripLoopMDLoc(), and updateLoopMetadataDebugLocationsImpl().
getIfExists()
MDTuple * llvm::MDNode::getIfExists (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1573 of file Metadata.h.
References llvm::MDTuple::getIfExists().
getMergedCalleeTypeMetadata()
MDNode * MDNode::getMergedCalleeTypeMetadata (const MDNode * A, const MDNode * B) static
Definition at line 1300 of file Metadata.cpp.
References A(), B(), get(), llvm::SmallPtrSetImpl< PtrType >::insert(), MDNode(), llvm::Metadata::Metadata(), and N.
Referenced by combineMetadata().
getMergedCallsiteMetadata()
MDNode * MDNode::getMergedCallsiteMetadata (MDNode * A, MDNode * B) static
Definition at line 631 of file MemoryProfileInfo.cpp.
References A(), B(), and MDNode().
Referenced by combineMetadata().
getMergedMemProfMetadata()
MDNode * MDNode::getMergedMemProfMetadata (MDNode * A, MDNode * B) static
Definition at line 622 of file MemoryProfileInfo.cpp.
References A(), B(), and MDNode().
Referenced by combineMetadata().
getMergedProfMetadata()
MDNode * MDNode::getMergedProfMetadata (MDNode * A, MDNode * B, const Instruction * AInstr, const Instruction * BInstr) static
Merge !prof metadata from two instructions.
Currently only implemented with direct callsites with branch weights.
Definition at line 1218 of file Metadata.cpp.
References A(), assert(), B(), llvm::dyn_cast(), llvm::CallBase::getCalledFunction(), llvm::Instruction::getMetadata(), I, and MDNode().
Referenced by combineMetadata().
getMostGenericAliasScope()
MDNode * MDNode::getMostGenericAliasScope (MDNode * A, MDNode * B) static
Definition at line 1136 of file Metadata.cpp.
References A(), B(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::dyn_cast(), llvm::SetVector< T, Vector, Set, N >::empty(), llvm::SetVector< T, Vector, Set, N >::getArrayRef(), getDomain(), getOrSelfReference(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), MDNode(), and nullptr.
Referenced by combineMetadata(), llvm::AAMDNodes::concat(), llvm::AAMDNodes::merge(), and llvm::propagateMetadata().
getMostGenericAlignmentOrDereferenceable()
MDNode * MDNode::getMostGenericAlignmentOrDereferenceable (MDNode * A, MDNode * B) static
Definition at line 1428 of file Metadata.cpp.
References A(), B(), llvm::mdconst::extract(), llvm::ConstantInt::getZExtValue(), and MDNode().
Referenced by combineMetadata().
getMostGenericFPMath()
MDNode * MDNode::getMostGenericFPMath (MDNode * A, MDNode * B) static
Definition at line 1168 of file Metadata.cpp.
References A(), B(), llvm::mdconst::extract(), and MDNode().
Referenced by combineMetadata(), convertFSqrtDivIntoFMul(), and llvm::propagateMetadata().
getMostGenericNoaliasAddrspace()
MDNode * MDNode::getMostGenericNoaliasAddrspace (MDNode * A, MDNode * B) static
Definition at line 1391 of file Metadata.cpp.
References A(), B(), llvm::mdconst::extract(), llvm::ConstantAsMetadata::get(), get(), I, llvm::ConstantRangeList::intersectWith(), MDNode(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by combineMetadata(), llvm::AAMDNodes::concat(), and llvm::AAMDNodes::merge().
getMostGenericRange()
MDNode * MDNode::getMostGenericRange (MDNode * A, MDNode * B) static
Definition at line 1318 of file Metadata.cpp.
References A(), addRange(), B(), llvm::mdconst::extract(), llvm::ConstantAsMetadata::get(), get(), llvm::ConstantInt::getValue(), I, MDNode(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Range, llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), Size, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::APInt::slt(), and tryMergeRange().
Referenced by combineMetadata().
getMostGenericTBAA()
MDNode * MDNode::getMostGenericTBAA (MDNode * A, MDNode * B) static
Definition at line 497 of file TypeBasedAliasAnalysis.cpp.
References A(), B(), matchAccessTags(), and MDNode().
Referenced by combineMetadata(), llvm::AAMDNodes::merge(), and llvm::propagateMetadata().
getNumOperands()
unsigned llvm::MDNode::getNumOperands () const inline
Return number of MDNode operands.
Definition at line 1448 of file Metadata.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::memprof::CallStackTrie::addCallStack(), addRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), addToAccessGroupList(), llvm::buildOpSpirvDecorations(), llvm::cacheAnnotationFromMD(), computeFunctionSummary(), createAccessTag(), dropAllReferences(), extractFromBranchWeightMD(), llvm::SPIRV::extractFunctionTypeFromMetadata(), llvm::extractProfTotalWeight(), llvm::findOptionMDForLoopID(), llvm::findStringMetadataForLoop(), getConstInt(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), GetFunctionFromMDNode(), llvm::AMDGPUMachineFunction::getLDSKernelIdMetadata(), llvm::MachineInstr::getLocCookieMD(), llvm::Loop::getLoopID(), llvm::MachineLoop::getLoopID(), llvm::memprof::getMIBAllocType(), llvm::memprof::getMIBStackNode(), llvm::getNumBranchWeights(), llvm::GenericDINode::getNumDwarfOperands(), getOperand(), llvm::getOptionalBoolLoopAttribute(), llvm::SPIRVGlobalRegistry::getOrAddMemAliasingINTELInst(), llvm::DILocation::getRawInlinedAt(), getSummaryFromMD(), llvm::GetUnrollMetadata(), getValMD(), llvm::getValueProfDataFromInst(), hasGeneralizedMDString(), llvm::AMDGPU::hasValueInRangeLikeMetadata(), haveCommonPrefix(), llvm::intersectAccessGroups(), llvm::isExplicitlyUnknownProfileMetadata(), isKeyValuePair(), isLoopMDCompatible(), AliasScopeTracker::isNoAliasScopeDeclDead(), IsRootTBAANode(), IsScalarTBAANodeImpl(), isStructPathTBAA(), isTargetMD(), isTBAAVtableAccess(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::makeFollowupLoopID(), llvm::mayHaveValueProfileOfKind(), llvm::MDBuilder::mergeCallbackEncodings(), llvm::MDTuple::pop_back(), propagateMemProfHelper(), llvm::MDTuple::push_back(), saveFilteredNewMIBNodes(), llvm::Loop::setLoopID(), setOperand(), llvm::AAMDNodes::shiftTBAAStruct(), translateBranchMetadata(), translateLoopMetadata(), unrollAndJamCountPragmaValue(), unrollCountPragmaValue(), updateLoopMetadataDebugLocationsImpl(), llvm::UpgradeTBAANode(), and llvm::TBAAVerifier::visitTBAAMetadata().
getNumTemporaryUses()
unsigned llvm::MDNode::getNumTemporaryUses () const inline
Definition at line 1274 of file Metadata.h.
References assert(), and isTemporary().
getNumUnresolved()
unsigned llvm::MDNode::getNumUnresolved () const inline protected
Definition at line 1367 of file Metadata.h.
Referenced by isResolved(), and storeDistinctInContext().
getOperand()
const MDOperand & llvm::MDNode::getOperand (unsigned I) const inline
Definition at line 1442 of file Metadata.h.
References assert(), getNumOperands(), and I.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), AccessQualFromMD(), llvm::DwarfUnit::addAnnotation(), llvm::memprof::CallStackTrie::addCallStack(), addRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), ArgTypeFromMD(), llvm::buildOpSpirvDecorations(), llvm::cacheAnnotationFromMD(), llvm::cacheAnnotationFromMD(), llvm::MachineFunction::CallSiteInfo::CallSiteInfo(), computeFunctionSummary(), llvm::MDBuilder::createMutableTBAAAccessTag(), llvm::MachineInstr::emitInlineAsmError(), llvm::AsmPrinter::emitPCSections(), exportKernelRuntimeHandles(), extractFromBranchWeightMD(), llvm::SPIRV::extractFunctionTypeFromMetadata(), llvm::extractProfTotalWeight(), llvm::findOptionMDForLoopID(), llvm::findStringMetadataForLoop(), foldConstantsIntoIntrinsics(), generateAssignInstrs(), GetArgMD(), llvm::AbstractCallSite::getCallbackUses(), getConstInt(), getCoopAtomicOperandsInfo(), llvm::GenericDINode::getDwarfOperand(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), getEnqueuedBlockSymbolName(), llvm::FPMathOperator::getFPAccuracy(), GetFunctionFromMDNode(), llvm::AMDGPUMachineFunction::getLDSKernelIdMetadata(), getLinkedToSymbol(), llvm::SelectionDAG::getLoad(), llvm::MachineInstr::getLocCookieMD(), llvm::Loop::getLoopID(), llvm::MachineLoop::getLoopID(), llvm::memprof::getMIBAllocType(), llvm::memprof::getMIBStackNode(), getOCLKernelArgAttribute(), llvm::DIMacroNode::getOperandAs(), llvm::DINode::getOperandAs(), llvm::getOptionalBoolLoopAttribute(), llvm::DICompositeType::getRawAllocated(), llvm::DICompositeType::getRawAnnotations(), llvm::DIDerivedType::getRawAnnotations(), llvm::DIGlobalVariable::getRawAnnotations(), llvm::DILocalVariable::getRawAnnotations(), llvm::DICompositeType::getRawAssociated(), llvm::DICompositeType::getRawBaseType(), llvm::DISubrangeType::getRawBaseType(), llvm::DISubrangeType::getRawBias(), llvm::DICompositeType::getRawBitStride(), llvm::DIGenericSubrange::getRawCountNode(), llvm::DICompositeType::getRawDataLocation(), llvm::DICommonBlock::getRawDecl(), llvm::DICompositeType::getRawDiscriminator(), llvm::DICompositeType::getRawElements(), llvm::DIMacroFile::getRawElements(), llvm::DICompileUnit::getRawEnumTypes(), llvm::DIGlobalVariableExpression::getRawExpression(), llvm::DIDerivedType::getRawExtraData(), llvm::DICommonBlock::getRawFile(), llvm::DILabel::getRawFile(), llvm::DIMacroFile::getRawFile(), llvm::DIObjCProperty::getRawFile(), llvm::DIScope::getRawFile(), llvm::DIVariable::getRawFile(), llvm::DICompileUnit::getRawGlobalVariables(), llvm::DICompileUnit::getRawImportedEntities(), llvm::DILocation::getRawInlinedAt(), llvm::DIGenericSubrange::getRawLowerBound(), llvm::DISubrangeType::getRawLowerBound(), llvm::DICompileUnit::getRawMacros(), llvm::DIType::getRawOffsetInBits(), llvm::DICompositeType::getRawRank(), llvm::DICompileUnit::getRawRetainedTypes(), llvm::DICommonBlock::getRawScope(), llvm::DILabel::getRawScope(), llvm::DILexicalBlockBase::getRawScope(), llvm::DILocation::getRawScope(), llvm::DINamespace::getRawScope(), llvm::DIType::getRawScope(), llvm::DIVariable::getRawScope(), llvm::DIType::getRawSizeInBits(), llvm::DICompositeType::getRawSpecification(), llvm::DIGlobalVariable::getRawStaticDataMemberDeclaration(), llvm::DIGenericSubrange::getRawStride(), llvm::DISubrangeType::getRawStride(), llvm::DIStringType::getRawStringLength(), llvm::DIStringType::getRawStringLengthExp(), llvm::DIStringType::getRawStringLocationExp(), llvm::DICompositeType::getRawTemplateParams(), llvm::DIGlobalVariable::getRawTemplateParams(), llvm::DIObjCProperty::getRawType(), llvm::DITemplateParameter::getRawType(), llvm::DIVariable::getRawType(), llvm::DISubroutineType::getRawTypeArray(), llvm::DIGenericSubrange::getRawUpperBound(), llvm::DISubrangeType::getRawUpperBound(), llvm::DIGlobalVariableExpression::getRawVariable(), llvm::DICompositeType::getRawVTableHolder(), getSummaryFromMD(), llvm::RISCVTargetLowering::getTargetMMOFlags(), llvm::GetUnrollMetadata(), getValMD(), llvm::DITemplateValueParameter::getValue(), llvm::getValueProfDataFromInst(), hasAnyUnrollPragma(), llvm::hasBranchWeightOrigin(), hasGeneralizedMDString(), llvm::AMDGPU::hasValueInRangeLikeMetadata(), llvm::isExplicitlyUnknownProfileMetadata(), isKeyValuePair(), isLoopMDCompatible(), AliasScopeTracker::isNoAliasScopeDeclDead(), IsScalarTBAANodeImpl(), isStructPathTBAA(), isTargetMD(), isTBAAVtableAccess(), llvm::lookupPGONameFromMetadata(), llvm::makeFollowupLoopID(), llvm::mayHaveValueProfileOfKind(), llvm::MDBuilder::mergeCallbackEncodings(), replaceOperandWith(), saveFilteredNewMIBNodes(), llvm::Loop::setLoopID(), llvm::AAMDNodes::shiftTBAAStruct(), translateBranchMetadata(), translateLoopMetadata(), unrollAndJamCountPragmaValue(), unrollCountPragmaValue(), updateLoopMetadataDebugLocationsImpl(), llvm::UpgradeTBAANode(), and llvm::TBAAVerifier::visitTBAAMetadata().
getTemporary()
TempMDTuple llvm::MDNode::getTemporary (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1581 of file Metadata.h.
References llvm::MDTuple::getTemporary().
Referenced by llvm::DIBasicType::cloneImpl(), llvm::DIBuilder::createReplaceableCompositeType(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTempGlobalVariableFwdDecl(), llvm::DIBuilder::createTempMacroFile(), and translateLoopMetadata().
hasGeneralizedMDString()
bool llvm::MDNode::hasGeneralizedMDString () inline
Check if this is a valid generalized type metadata node.
Definition at line 1268 of file Metadata.h.
References llvm::cast(), getNumOperands(), getOperand(), and llvm::isa().
intersect()
MDNode * MDNode::intersect (MDNode * A, MDNode * B) static
Definition at line 1123 of file Metadata.cpp.
References A(), B(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SetVector< T, Vector, Set, N >::getArrayRef(), getOrSelfReference(), MDNode(), llvm::Metadata::Metadata(), and llvm::SetVector< T, Vector, Set, N >::remove_if().
Referenced by combineMetadata(), llvm::AAMDNodes::concat(), llvm::AAMDNodes::merge(), and llvm::propagateMetadata().
isAlwaysReplaceable()
bool llvm::MDNode::isAlwaysReplaceable () const inline
Definition at line 1265 of file Metadata.h.
References llvm::Metadata::getMetadataID().
Referenced by isReplaceable().
isDistinct()
bool llvm::MDNode::isDistinct () const inline
Definition at line 1261 of file Metadata.h.
References llvm::Metadata::Distinct, and llvm::Metadata::Storage.
Referenced by llvm::DIType::mutate().
isReplaceable()
bool llvm::MDNode::isReplaceable () const inline
Definition at line 1264 of file Metadata.h.
References isAlwaysReplaceable(), and isTemporary().
Referenced by replaceAllUsesWith().
isResolved()
bool llvm::MDNode::isResolved () const inline
Check if node is fully resolved.
If isTemporary(), this always returns false; if isDistinct(), this always returns true.
If isUniqued(), returns true if this has already dropped RAUW support (because all operands are resolved).
As forward declarations are resolved, their containers should get resolved automatically. However, if this (or one of its operands) is involved in a cycle, resolveCycles() needs to be called explicitly.
Definition at line 1258 of file Metadata.h.
References getNumUnresolved(), and isTemporary().
Referenced by resolve(), resolveCycles(), and storeDistinctInContext().
isTBAAVtableAccess()
bool MDNode::isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Definition at line 474 of file TypeBasedAliasAnalysis.cpp.
References llvm::dyn_cast(), getNumOperands(), getOperand(), isStructPathTBAA(), and llvm::Tag.
isTemporary()
bool llvm::MDNode::isTemporary () const inline
Definition at line 1262 of file Metadata.h.
References llvm::Metadata::Storage, and llvm::Metadata::Temporary.
Referenced by getNumTemporaryUses(), isReplaceable(), isResolved(), and llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment().
isUniqued()
bool llvm::MDNode::isUniqued () const inline
Definition at line 1260 of file Metadata.h.
References llvm::Metadata::Storage, and llvm::Metadata::Uniqued.
Referenced by MDNode(), replaceOperandWith(), llvm::DILexicalBlockBase::replaceScope(), resize(), resolve(), and setOperand().
mutable_begin()
MDOperand * llvm::MDNode::mutable_begin () inline protected
Definition at line 1211 of file Metadata.h.
Referenced by mutable_operands(), op_begin(), replaceOperandWith(), and setOperand().
mutable_end()
MDOperand * llvm::MDNode::mutable_end () inline protected
Definition at line 1212 of file Metadata.h.
Referenced by mutable_operands(), and op_end().
mutable_operands()
mutable_op_range llvm::MDNode::mutable_operands () inline protected
Definition at line 1216 of file Metadata.h.
References mutable_begin(), and mutable_end().
op_begin()
op_iterator llvm::MDNode::op_begin () const inline
Definition at line 1432 of file Metadata.h.
References MDNode(), and mutable_begin().
Referenced by llvm::GenericDINode::dwarf_op_begin(), and haveCommonPrefix().
op_end()
op_iterator llvm::MDNode::op_end () const inline
Definition at line 1436 of file Metadata.h.
References MDNode(), and mutable_end().
Referenced by llvm::GenericDINode::dwarf_op_end(), and haveCommonPrefix().
operands()
ArrayRef< MDOperand > llvm::MDNode::operands () const inline
Definition at line 1440 of file Metadata.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), addBasicBlockMetadata(), llvm::memprof::CallStackTrie::addCallStack(), addOpsFromMDNode(), addToAccessGroupList(), llvm::MachineFunction::CallSiteInfo::CallSiteInfo(), checkAllocContextIds(), llvm::ScopedNoAliasAAResult::collectScopedDomains(), llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), llvm::AsmPrinter::emitPCSections(), llvm::AAMDNodes::extendToTBAA(), llvm::findOptionMDForLoopID(), getAllocaName(), llvm::AbstractCallSite::getCallbackUses(), getOCLKernelArgAttribute(), llvm::SPIRVGlobalRegistry::getOrAddMemAliasingINTELInst(), getSummaryFromMD(), llvm::GetUnrollMetadata(), llvm::intersectAccessGroups(), llvm::Loop::isAnnotatedParallel(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), propagateMemProfHelper(), resolveCycles(), toCaptureComponents(), translateLoopMetadata(), and updateLoopMetadataDebugLocationsImpl().
operator delete() [1/3]
void llvm::MDNode::operator delete (void * , unsigned) inline protected
Required by std, but never called.
Definition at line 1200 of file Metadata.h.
References llvm_unreachable.
operator delete() [2/3]
void llvm::MDNode::operator delete (void * , unsigned , bool) inline protected
Required by std, but never called.
Definition at line 1205 of file Metadata.h.
References llvm_unreachable.
operator delete() [3/3]
void MDNode::operator delete (void * Mem) protected
Definition at line 645 of file Metadata.cpp.
References H, and N.
operator new() [1/2]
void * MDNode::operator new (size_t Size, size_t NumOps, StorageType Storage) protected
Definition at line 635 of file Metadata.cpp.
operator new() [2/2]
void * llvm::MDNode::operator new (size_t) delete
References LLVM_ABI, MDNode(), and N.
operator=()
void llvm::MDNode::operator= (const MDNode &) delete
References MDNode().
printTree() [1/2]
void MDNode::printTree (raw_ostream & OS, const Module * M = nullptr) const
Print in tree shape.
Prints definition of this in tree shape.
If M is provided, metadata nodes will be numbered canonically; otherwise, pointer addresses are substituted.
Definition at line 5426 of file AsmWriter.cpp.
References printMetadataImpl().
Referenced by dumpTree().
printTree() [2/2]
void MDNode::printTree (raw_ostream & OS, ModuleSlotTracker & MST, const Module * M = nullptr) const
Definition at line 5432 of file AsmWriter.cpp.
References printMetadataImpl().
replaceAllUsesWith()
void llvm::MDNode::replaceAllUsesWith (Metadata * MD) inline
RAUW a temporary.
Precondition
isTemporary() must be true.
Definition at line 1282 of file Metadata.h.
References assert(), isReplaceable(), and llvm::Metadata::Metadata().
Referenced by llvm::at::RAUW().
replaceOperandWith()
void MDNode::replaceOperandWith (unsigned I, Metadata * New)
Replace a specific operand.
Definition at line 1072 of file Metadata.cpp.
References getOperand(), I, isUniqued(), llvm::Metadata::Metadata(), mutable_begin(), and setOperand().
Referenced by addBasicBlockMetadata(), addRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), buildFrameDebugInfo(), llvm::MDBuilder::createAnonymousAARoot(), DisableAllLoopOptsOnLoop(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), llvm::GenericDINode::replaceDwarfOperandWith(), llvm::DICompositeType::replaceElements(), llvm::DIMacroFile::replaceElements(), llvm::DICompileUnit::replaceEnumTypes(), llvm::DICompileUnit::replaceGlobalVariables(), llvm::DICompileUnit::replaceImportedEntities(), llvm::DICompileUnit::replaceMacros(), llvm::DICompileUnit::replaceRetainedTypes(), llvm::DICompositeType::replaceTemplateParams(), llvm::DICompositeType::replaceVTableHolder(), stripLoopMDLoc(), and updateLoopMetadataDebugLocationsImpl().
replaceWithDistinct()
template<class T> std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > llvm::MDNode::replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a distinct one.
Create a distinct version of N – in place, if possible – and return it. Takes ownership of the temporary node.
Definition at line 1327 of file Metadata.h.
References llvm::cast(), and N.
Referenced by llvm::DIBuilder::createArtificialSubprogram().
replaceWithPermanent()
template<class T> std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > llvm::MDNode::replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a permanent one.
Try to create a uniqued version of N – in place, if possible – and return it. If N cannot be uniqued, return a distinct node instead.
Definition at line 1305 of file Metadata.h.
References llvm::cast(), and N.
replaceWithUniqued()
template<class T> std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > llvm::MDNode::replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a uniqued one.
Create a uniqued version of N – in place, if possible – and return it. Takes ownership of the temporary node.
Precondition
N does not self-reference.
Definition at line 1317 of file Metadata.h.
References llvm::cast(), and N.
Referenced by cloneAndReplaceParentScope(), llvm::coro::BaseCloner::create(), createTypeWithFlags(), llvm::DIBuilder::replaceTemporary(), and updateSubprogramLinkageName().
resize()
void llvm::MDNode::resize (size_t NumOps) inline protected
Resize the node to hold NumOps operands.
Precondition
isTemporary() or isDistinct()
MetadataID == MDTupleKind
Definition at line 1379 of file Metadata.h.
References AbstractManglingParser< Derived, Alloc >::NumOps, assert(), llvm::Metadata::getMetadataID(), and isUniqued().
Referenced by llvm::MDTuple::pop_back(), and llvm::MDTuple::push_back().
resolve()
void MDNode::resolve ()
Resolve a unique, unresolved node.
Definition at line 797 of file Metadata.cpp.
References assert(), isResolved(), isUniqued(), and setNumUnresolved().
Referenced by resolveCycles().
resolveCycles()
void MDNode::resolveCycles ()
Resolve cycles.
Once all forward declarations have been resolved, force cycles to be resolved.
Precondition
No operands (or operands' operands, etc.) have isTemporary().
Definition at line 843 of file Metadata.cpp.
References assert(), llvm::dyn_cast_or_null(), isResolved(), N, operands(), and resolve().
setNumUnresolved()
void llvm::MDNode::setNumUnresolved (unsigned N) inline protected
Definition at line 1369 of file Metadata.h.
References N.
Referenced by resolve().
setOperand()
void MDNode::setOperand (unsigned I, Metadata * New) protected
Set an operand.
Sets the operand directly, without worrying about uniquing.
Definition at line 1084 of file Metadata.cpp.
References assert(), getNumOperands(), I, isUniqued(), llvm::Metadata::Metadata(), mutable_begin(), and llvm::MDOperand::reset().
Referenced by dropAllReferences(), MDNode(), llvm::MDTuple::push_back(), replaceOperandWith(), and llvm::DILexicalBlockBase::replaceScope().
storeDistinctInContext()
void MDNode::storeDistinctInContext () protected
Definition at line 1051 of file Metadata.cpp.
References assert(), llvm::Metadata::Distinct, llvm::LLVMContextImpl::DistinctMDNodes, getContext(), llvm::Metadata::getMetadataID(), getNumUnresolved(), isResolved(), llvm_unreachable, llvm::LLVMContext::pImpl, and llvm::Metadata::Storage.
storeImpl() [1/2]
template<class T> T * llvm::MDNode::storeImpl (T * N, StorageType Storage) static protected
Definition at line 28 of file MetadataImpl.h.
References llvm::Metadata::Distinct, llvm_unreachable, N, llvm::Metadata::Storage, T, llvm::Metadata::Temporary, and llvm::Metadata::Uniqued.
storeImpl() [2/2]
template<class T, class StoreT> T * llvm::MDNode::storeImpl (T * N, StorageType Storage, StoreT & Store) static protected
Definition at line 42 of file MetadataImpl.h.
References llvm::Metadata::Distinct, N, llvm::Metadata::Storage, T, llvm::Metadata::Temporary, and llvm::Metadata::Uniqued.
toCaptureComponents()
CaptureComponents MDNode::toCaptureComponents (const MDNode * MD) static
Convert !captures metadata to CaptureComponents. MD may be nullptr.
Definition at line 1439 of file Metadata.cpp.
References llvm::Address, llvm::AddressIsNull, llvm::All, llvm::StringSwitch< T, R >::Case(), llvm::cast(), MDNode(), llvm::Metadata::Metadata(), llvm::None, operands(), llvm::Provenance, and llvm::ReadProvenance.
Referenced by combineMetadata(), and llvm::DetermineUseCaptureKind().
Friends And Related Symbol Documentation
DIAssignID
friend class DIAssignID friend
Definition at line 1081 of file Metadata.h.
References AbstractManglingParser< Derived, Alloc >::NumOps, and DIAssignID.
Referenced by DIAssignID.
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1080 of file Metadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
ReplaceableMetadataImpl
friend class ReplaceableMetadataImpl friend
Definition at line 1079 of file Metadata.h.
References ReplaceableMetadataImpl.
Referenced by ReplaceableMetadataImpl.
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/Analysis/MemoryProfileInfo.cpp
lib/Analysis/TypeBasedAliasAnalysis.cpp
lib/IR/AsmWriter.cpp
lib/IR/Metadata.cpp
lib/IR/MetadataImpl.h