LLVM: llvm::cl::ExpansionContext Class Reference
llvm::cl::ExpansionContext Class Reference
Contains options that control response file expansion.
#include "llvm/Support/CommandLine.h"
Public Member Functions
LLVM_ABI ExpansionContext (BumpPtrAllocator &A, TokenizerCallback T, vfs::FileSystem *FS=nullptr)
ExpansionContext & setMarkEOLs (bool X)
ExpansionContext & setRelativeNames (bool X)
ExpansionContext & setCurrentDir (StringRef X)
ExpansionContext & setSearchDirs (ArrayRef< StringRef > X)
ExpansionContext & setVFS (vfs::FileSystem *X)
LLVM_ABI bool findConfigFile (StringRef FileName, SmallVectorImpl< char > &FilePath)
Looks for the specified configuration file.
LLVM_ABI Error readConfigFile (StringRef CfgFile, SmallVectorImpl< const char * > &Argv)
Reads command line options from the given configuration file.
LLVM_ABI Error expandResponseFiles (SmallVectorImpl< const char * > &Argv)
Expands constructs "@file" in the provided array of arguments recursively.
Detailed Description
Contains options that control response file expansion.
Definition at line 2191 of file CommandLine.h.
Constructor & Destructor Documentation
ExpansionContext()
ExpansionContext::ExpansionContext (BumpPtrAllocator & A, TokenizerCallback T, vfs::FileSystem * FS = nullptr)
Definition at line 1403 of file CommandLine.cpp.
References A(), llvm::get(), and T.
Referenced by setCurrentDir(), setMarkEOLs(), setRelativeNames(), setSearchDirs(), and setVFS().
Member Function Documentation
expandResponseFiles()
Error ExpansionContext::expandResponseFiles (SmallVectorImpl< const char * > & Argv)
Expands constructs "@file" in the provided array of arguments recursively.
Expand response files on a command line recursively using the given StringSaver and tokenization strategy.
Definition at line 1251 of file CommandLine.cpp.
References llvm::sys::path::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallString< InternalLen >::c_str(), llvm::createStringError(), llvm::drop_begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::vfs::Status::equivalent(), llvm::SmallVectorImpl< T >::erase(), F, llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), I, llvm::SmallVectorImpl< T >::insert(), llvm::sys::path::is_relative(), llvm::no_such_file_or_directory, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::Error::success().
Referenced by llvm::cl::ExpandResponseFiles(), llvm::cl::expandResponseFiles(), and readConfigFile().
findConfigFile()
bool ExpansionContext::findConfigFile (StringRef FileName, SmallVectorImpl< char > & FilePath)
Looks for the specified configuration file.
Parameters
[in] FileName Name of the file to search for.
[out] FilePath File absolute path, if it was found.
Returns
True if file was found.
If the specified file name contains a directory separator, it is searched for by its absolute path. Otherwise looks for file sequentially in directories specified by SearchDirs field.
Definition at line 1407 of file CommandLine.cpp.
References llvm::sys::path::append(), llvm::SmallString< InternalLen >::assign(), llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::sys::path::has_parent_path(), llvm::sys::path::is_relative(), llvm::sys::path::native, and llvm::sys::fs::regular_file.
readConfigFile()
Error ExpansionContext::readConfigFile (StringRef CfgFile, SmallVectorImpl< const char * > & Argv)
Reads command line options from the given configuration file.
Parameters
[in] CfgFile Path to configuration file.
[out] Argv Array to which the read options are added.
Returns
true if the file was successfully read.
It reads content of the specified file, tokenizes it and expands "@file" commands resolving file names in them relative to the directory where CfgFilename resides. It also expands "<CFGDIR>" to the base path of the current config file.
Definition at line 1444 of file CommandLine.cpp.
References llvm::SmallString< InternalLen >::assign(), expandResponseFiles(), llvm::sys::path::is_relative(), llvm::make_error(), and llvm::SmallString< InternalLen >::str().
setCurrentDir()
ExpansionContext & llvm::cl::ExpansionContext::setCurrentDir (StringRef X) inline
Definition at line 2236 of file CommandLine.h.
References ExpansionContext(), and X.
setMarkEOLs()
ExpansionContext & llvm::cl::ExpansionContext::setMarkEOLs (bool X) inline
Definition at line 2226 of file CommandLine.h.
References ExpansionContext(), and X.
setRelativeNames()
ExpansionContext & llvm::cl::ExpansionContext::setRelativeNames (bool X) inline
Definition at line 2231 of file CommandLine.h.
References ExpansionContext(), and X.
setSearchDirs()
ExpansionContext & llvm::cl::ExpansionContext::setSearchDirs (ArrayRef< StringRef > X) inline
Definition at line 2241 of file CommandLine.h.
References ExpansionContext(), and X.
setVFS()
ExpansionContext & llvm::cl::ExpansionContext::setVFS (vfs::FileSystem * X) inline
Definition at line 2246 of file CommandLine.h.
References ExpansionContext(), and X.
The documentation for this class was generated from the following files:
include/llvm/Support/CommandLine.h
lib/Support/CommandLine.cpp