LLVM: llvm::NVPTXRegisterInfo Class Reference
llvm::NVPTXRegisterInfo Class Reference
#include "Target/NVPTX/NVPTXRegisterInfo.h"
Public Member Functions
NVPTXRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
NVPTX Callee Saved Registers.
BitVector getReservedRegs (const MachineFunction &MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
Register getFrameLocalRegister (const MachineFunction &MF) const
UniqueStringSaver & getStrPool () const
const char * getName (unsigned RegNo) const
void addToDebugRegisterMap (uint64_t preEncodedVirtualRegister, StringRef RegisterName) const
void clearDebugRegisterMap () const
int64_t getDwarfRegNum (MCRegister RegNum, bool isEH) const override
int64_t getDwarfRegNumForVirtReg (Register RegNum, bool isEH) const override
Detailed Description
Definition at line 24 of file NVPTXRegisterInfo.h.
Constructor & Destructor Documentation
NVPTXRegisterInfo()
NVPTXRegisterInfo::NVPTXRegisterInfo ()
Definition at line 78 of file NVPTXRegisterInfo.cpp.
Member Function Documentation
addToDebugRegisterMap()
void NVPTXRegisterInfo::addToDebugRegisterMap (uint64_t preEncodedVirtualRegister, StringRef RegisterName) const
Definition at line 161 of file NVPTXRegisterInfo.cpp.
References encodeRegisterForDwarf().
clearDebugRegisterMap()
void NVPTXRegisterInfo::clearDebugRegisterMap () const
Definition at line 140 of file NVPTXRegisterInfo.cpp.
eliminateFrameIndex()
bool NVPTXRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 104 of file NVPTXRegisterInfo.cpp.
References assert(), llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineFrameInfo::getObjectOffset(), II, MI, and llvm::Offset.
getCalleeSavedRegs()
const MCPhysReg * NVPTXRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
NVPTX Callee Saved Registers.
Definition at line 86 of file NVPTXRegisterInfo.cpp.
getDwarfRegNum()
int64_t NVPTXRegisterInfo::getDwarfRegNum (MCRegister RegNum, bool isEH) const override
Definition at line 169 of file NVPTXRegisterInfo.cpp.
References encodeRegisterForDwarf(), llvm::NVPTXInstPrinter::getRegisterName(), and llvm::MCRegister::id().
getDwarfRegNumForVirtReg()
int64_t NVPTXRegisterInfo::getDwarfRegNumForVirtReg (Register RegNum, bool isEH) const override
Definition at line 179 of file NVPTXRegisterInfo.cpp.
References assert(), llvm::Register::id(), llvm::Register::isVirtual(), and lookup().
getFrameLocalRegister()
Register NVPTXRegisterInfo::getFrameLocalRegister (const MachineFunction & MF) const
Definition at line 134 of file NVPTXRegisterInfo.cpp.
References llvm::MachineFunction::getTarget(), and llvm::NVPTXTargetMachine::is64Bit().
Referenced by CombineCVTAToLocal(), and llvm::NVPTXFrameLowering::emitPrologue().
getFrameRegister()
Register NVPTXRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 127 of file NVPTXRegisterInfo.cpp.
References llvm::MachineFunction::getTarget(), and llvm::NVPTXTargetMachine::is64Bit().
Referenced by eliminateFrameIndex(), and llvm::NVPTXFrameLowering::emitPrologue().
getName()
const char * llvm::NVPTXRegisterInfo::getName (unsigned RegNo) const inline
Definition at line 57 of file NVPTXRegisterInfo.h.
References llvm::StringRef::data(), getStrPool(), and llvm::UniqueStringSaver::save().
getReservedRegs()
BitVector NVPTXRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 91 of file NVPTXRegisterInfo.cpp.
References llvm::Reserved.
getStrPool()
UniqueStringSaver & llvm::NVPTXRegisterInfo::getStrPool () const inline
Definition at line 53 of file NVPTXRegisterInfo.h.
Referenced by getName().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXRegisterInfo.h
lib/Target/NVPTX/NVPTXRegisterInfo.cpp