LLVM: llvm::AMDGPU::RegBankLegalizeHelper Class Reference
llvm::AMDGPU::RegBankLegalizeHelper Class Reference
#include "Target/AMDGPU/AMDGPURegBankLegalizeHelper.h"
Public Member Functions
RegBankLegalizeHelper (MachineIRBuilder &B, const MachineUniformityInfo &MUI, const RegisterBankInfo &RBI, const RegBankLegalizeRules &RBLRules)
bool findRuleAndApplyMapping (MachineInstr &MI)
bool applyMappingPHI (MachineInstr &MI)
void applyMappingTrivial (MachineInstr &MI)
Detailed Description
Definition at line 30 of file AMDGPURegBankLegalizeHelper.h.
Constructor & Destructor Documentation
RegBankLegalizeHelper()
RegBankLegalizeHelper::RegBankLegalizeHelper (MachineIRBuilder & B, const MachineUniformityInfo & MUI, const RegisterBankInfo & RBI, const RegBankLegalizeRules & RBLRules)
Definition at line 32 of file AMDGPURegBankLegalizeHelper.cpp.
References nullptr.
Member Function Documentation
applyMappingPHI()
bool RegBankLegalizeHelper::applyMappingPHI (MachineInstr & MI)
Definition at line 1437 of file AMDGPURegBankLegalizeHelper.cpp.
References DefMI, MI, llvm::LLT::pointer(), llvm::reportGISelFailure(), llvm::LLT::scalar(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), and UseReg().
applyMappingTrivial()
void RegBankLegalizeHelper::applyMappingTrivial (MachineInstr & MI)
Definition at line 1499 of file AMDGPURegBankLegalizeHelper.cpp.
References assert(), MI, and verifyRegBankOnOperands().
findRuleAndApplyMapping()
bool RegBankLegalizeHelper::findRuleAndApplyMapping (MachineInstr & MI)
Definition at line 42 of file AMDGPURegBankLegalizeHelper.cpp.
References llvm::AMDGPU::RegBankLLTMapping::DstOpMapping, llvm::AMDGPU::SetOfRulesForOpcode::findMappingForMI(), MI, OpIdx, llvm::reportGISelFailure(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::AMDGPU::RegBankLLTMapping::SrcOpMapping.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPURegBankLegalizeHelper.h
lib/Target/AMDGPU/AMDGPURegBankLegalizeHelper.cpp