LLVM: llvm::DiagnosticInfoDontCall Class Reference
llvm::DiagnosticInfoDontCall Class Reference
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoDontCall (StringRef CalleeName, StringRef Note, DiagnosticSeverity DS, uint64_t LocCookie)
StringRef getFunctionName () const
StringRef getNote () const
uint64_t getLocCookie () const
void print (DiagnosticPrinter &DP) const override
Print using the given DP a user-friendly message.
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Definition at line 1195 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoDontCall()
llvm::DiagnosticInfoDontCall::DiagnosticInfoDontCall (StringRef CalleeName, StringRef Note, DiagnosticSeverity DS, uint64_t LocCookie) inline
Definition at line 1201 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), and llvm::DK_DontCall.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoDontCall::classof (const DiagnosticInfo * DI) inline static
Definition at line 1209 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_DontCall, and llvm::DiagnosticInfo::getKind().
getFunctionName()
StringRef llvm::DiagnosticInfoDontCall::getFunctionName () const inline
Definition at line 1205 of file DiagnosticInfo.h.
Referenced by print().
getLocCookie()
uint64_t llvm::DiagnosticInfoDontCall::getLocCookie () const inline
Definition at line 1207 of file DiagnosticInfo.h.
getNote()
StringRef llvm::DiagnosticInfoDontCall::getNote () const inline
Definition at line 1206 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoDontCall::print (DiagnosticPrinter & DP) const override virtual
Print using the given DP a user-friendly message.
This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implements llvm::DiagnosticInfo.
Definition at line 497 of file DiagnosticInfo.cpp.
References llvm::demangle(), llvm::DS_Error, getFunctionName(), getNote(), and llvm::DiagnosticInfo::getSeverity().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp