LLVM: llvm::SPIRV::ConvergenceRegion Class Reference
llvm::SPIRV::ConvergenceRegion Class Reference
#include "Target/SPIRV/Analysis/SPIRVConvergenceRegionAnalysis.h"
Public Member Functions
ConvergenceRegion (DominatorTree &DT, LoopInfo &LI, Function &F)
ConvergenceRegion (DominatorTree &DT, LoopInfo &LI, std::optional< IntrinsicInst * > ConvergenceToken, BasicBlock *Entry, SmallPtrSet< BasicBlock *, 8 > &&Blocks, SmallPtrSet< BasicBlock *, 2 > &&Exits)
ConvergenceRegion (ConvergenceRegion &&CR)
~ConvergenceRegion ()
ConvergenceRegion & operator= (ConvergenceRegion &&CR)=delete
ConvergenceRegion (const ConvergenceRegion &other)=delete
ConvergenceRegion & operator= (const ConvergenceRegion &other)=delete
bool contains (const BasicBlock *BB) const
void releaseMemory ()
void dump (const unsigned IndentSize=0) const
Public Attributes
ConvergenceRegion * Parent = nullptr
SmallVector< ConvergenceRegion * > Children = {}
std::optional< IntrinsicInst * > ConvergenceToken = std::nullopt
BasicBlock * Entry = nullptr
SmallPtrSet< BasicBlock *, 2 > Exits = {}
SmallPtrSet< BasicBlock *, 8 > Blocks = {}
Detailed Description
Definition at line 40 of file SPIRVConvergenceRegionAnalysis.h.
Constructor & Destructor Documentation
ConvergenceRegion() [1/4]
ConvergenceRegion::ConvergenceRegion (DominatorTree & DT, LoopInfo & LI, Function & F)
Definition at line 113 of file SPIRVConvergenceRegionAnalysis.cpp.
References B(), Blocks, ConvergenceToken, Entry, Exits, F, llvm::SPIRV::getConvergenceToken(), llvm::isa(), nullptr, and Parent.
Referenced by ConvergenceRegion(), ConvergenceRegion(), operator=(), and operator=().
ConvergenceRegion() [2/4]
ConvergenceRegion::ConvergenceRegion (DominatorTree & DT, LoopInfo & LI, std::optional< IntrinsicInst * > ConvergenceToken, BasicBlock * Entry, SmallPtrSet< BasicBlock *, 8 > && Blocks, SmallPtrSet< BasicBlock *, 2 > && Exits)
Definition at line 125 of file SPIRVConvergenceRegionAnalysis.cpp.
References assert(), Blocks, ConvergenceToken, Entry, Exits, and llvm::move().
ConvergenceRegion() [3/4]
llvm::SPIRV::ConvergenceRegion::ConvergenceRegion (ConvergenceRegion && CR) inline
Definition at line 68 of file SPIRVConvergenceRegionAnalysis.h.
References Blocks, Children, ConvergenceRegion(), ConvergenceToken, Entry, Exits, llvm::move(), and Parent.
~ConvergenceRegion()
llvm::SPIRV::ConvergenceRegion::~ConvergenceRegion () inline
Definition at line 75 of file SPIRVConvergenceRegionAnalysis.h.
References releaseMemory().
ConvergenceRegion() [4/4]
llvm::SPIRV::ConvergenceRegion::ConvergenceRegion (const ConvergenceRegion & other) delete
References ConvergenceRegion().
Member Function Documentation
contains()
bool llvm::SPIRV::ConvergenceRegion::contains (const BasicBlock * BB) const inline
Definition at line 83 of file SPIRVConvergenceRegionAnalysis.h.
References Blocks.
dump()
void ConvergenceRegion::dump (const unsigned IndentSize = 0) const
Definition at line 146 of file SPIRVConvergenceRegionAnalysis.cpp.
References llvm::Block, Blocks, Children, ConvergenceToken, llvm::dbgs(), Entry, Exits, and Parent.
operator=() [1/2]
ConvergenceRegion & llvm::SPIRV::ConvergenceRegion::operator= (const ConvergenceRegion & other) delete
References ConvergenceRegion().
operator=() [2/2]
ConvergenceRegion & llvm::SPIRV::ConvergenceRegion::operator= (ConvergenceRegion && CR) delete
References ConvergenceRegion().
releaseMemory()
void ConvergenceRegion::releaseMemory ()
Definition at line 136 of file SPIRVConvergenceRegionAnalysis.cpp.
References Children, and Parent.
Referenced by ~ConvergenceRegion().
Member Data Documentation
Blocks
SmallPtrSet<BasicBlock *, 8> llvm::SPIRV::ConvergenceRegion::Blocks = {}
Definition at line 56 of file SPIRVConvergenceRegionAnalysis.h.
Referenced by contains(), ConvergenceRegion(), ConvergenceRegion(), ConvergenceRegion(), dump(), and getExitFor().
Children
SmallVector<ConvergenceRegion *> llvm::SPIRV::ConvergenceRegion::Children = {}
Definition at line 48 of file SPIRVConvergenceRegionAnalysis.h.
Referenced by ConvergenceRegion(), dump(), findParentRegion(), and releaseMemory().
ConvergenceToken
std::optional<IntrinsicInst *> llvm::SPIRV::ConvergenceRegion::ConvergenceToken = std::nullopt
Definition at line 50 of file SPIRVConvergenceRegionAnalysis.h.
Referenced by ConvergenceRegion(), ConvergenceRegion(), ConvergenceRegion(), and dump().
Entry
BasicBlock* llvm::SPIRV::ConvergenceRegion::Entry = nullptr
Definition at line 52 of file SPIRVConvergenceRegionAnalysis.h.
Referenced by ConvergenceRegion(), ConvergenceRegion(), ConvergenceRegion(), and dump().
Exits
SmallPtrSet<BasicBlock *, 2> llvm::SPIRV::ConvergenceRegion::Exits = {}
Definition at line 54 of file SPIRVConvergenceRegionAnalysis.h.
Referenced by ConvergenceRegion(), ConvergenceRegion(), ConvergenceRegion(), dump(), and getExitFor().
Parent
ConvergenceRegion* llvm::SPIRV::ConvergenceRegion::Parent = nullptr
Definition at line 46 of file SPIRVConvergenceRegionAnalysis.h.
Referenced by ConvergenceRegion(), ConvergenceRegion(), dump(), and releaseMemory().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/Analysis/SPIRVConvergenceRegionAnalysis.h
lib/Target/SPIRV/Analysis/SPIRVConvergenceRegionAnalysis.cpp