LLVM: llvm::GraphWriter< GraphType > Class Template Reference
llvm::GraphWriter< GraphType > Class Template Reference
#include "llvm/Support/GraphWriter.h"
Public Member Functions
GraphWriter (raw_ostream &o, const GraphType &g, bool SN)
~GraphWriter () override=default
Public Member Functions inherited from llvm::GraphWriterBase< GraphType, GraphWriter< GraphType > >
GraphWriterBase (raw_ostream &o, const GraphType &g, bool SN)
virtual ~GraphWriterBase ()=default
void writeGraph (const std::string &Title="")
void writeHeader (const std::string &Title)
void writeFooter ()
void writeNodes ()
bool isNodeHidden (NodeRef Node)
void writeNode (NodeRef Node)
void writeEdge (NodeRef Node, unsigned edgeidx, child_iterator EI)
void emitSimpleNode (const void *ID, const std::string &Attr, const std::string &Label, unsigned NumEdgeSources=0, const std::vector< std::string > *EdgeSourceLabels=nullptr)
emitSimpleNode - Outputs a simple (non-record) node
void emitEdge (const void *SrcNodeID, int SrcNodePort, const void *DestNodeID, int DestNodePort, const std::string &Attrs)
emitEdge - Output an edge from a simple node into the graph...
raw_ostream & getOStream ()
getOStream - Get the raw output stream into the graph file.
Additional Inherited Members
Protected Types inherited from llvm::GraphWriterBase< GraphType, GraphWriter< GraphType > >
using DOTTraits
using GTraits
using NodeRef
using node_iterator
using child_iterator
Protected Member Functions inherited from llvm::GraphWriterBase< GraphType, GraphWriter< GraphType > >
GraphWriter< GraphType > & getDerived ()
bool getEdgeSourceLabels (raw_ostream &O, NodeRef Node)
Protected Attributes inherited from llvm::GraphWriterBase< GraphType, GraphWriter< GraphType > >
raw_ostream & O
const GraphType & G
bool RenderUsingHTML
DOTTraits DTraits
Detailed Description
template<typename GraphType>
class llvm::GraphWriter< GraphType >
Definition at line 368 of file GraphWriter.h.
Constructor & Destructor Documentation
GraphWriter()
template<typename GraphType> llvm::GraphWriter< GraphType >::GraphWriter (raw_ostream & o, const GraphType & g, bool SN) inline
Definition at line 370 of file GraphWriter.h.
References g(), GraphWriter(), and llvm::GraphWriterBase< GraphType, GraphWriter< GraphType > >::GraphWriterBase().
Referenced by GraphWriter().
~GraphWriter()
template<typename GraphType> llvm::GraphWriter< GraphType >::~GraphWriter () override default
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ScheduleDAG.h
include/llvm/Support/GraphWriter.h