LLVM: llvm::sandboxir::OverflowingBinaryOperator Class Reference
llvm::sandboxir::OverflowingBinaryOperator Class Reference
#include "llvm/SandboxIR/Operator.h"
Public Member Functions
bool hasNoUnsignedWrap () const
bool hasNoSignedWrap () const
unsigned getNoWrapKind () const
Public Member Functions inherited from llvm::sandboxir::Operator
Operator ()=delete
void * operator new (size_t s)=delete
bool hasPoisonGeneratingFlags () const
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Instruction *From)
static bool classof (const ConstantExpr *From)
static bool classof (const Value *From)
Static Public Member Functions inherited from llvm::sandboxir::Operator
static bool classof (const Instruction *)
static bool classof (const ConstantExpr *)
static bool classof (const Value *From)
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
virtual Use getOperandUseInternal (unsigned OpIdx, bool Verify) const =0
\Returns the Use for the OpIdx'th operand.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
virtual unsigned getUseOperandNo (const Use &Use) const =0
\Returns the operand index of Use.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 35 of file Operator.h.
Member Function Documentation
classof() [1/3]
bool llvm::sandboxir::OverflowingBinaryOperator::classof (const ConstantExpr * From) inline static
Definition at line 50 of file Operator.h.
References llvm::cast(), llvm::OverflowingBinaryOperator::classof(), and llvm::sandboxir::Value::Val.
classof() [2/3]
bool llvm::sandboxir::OverflowingBinaryOperator::classof (const Instruction * From) inline static
Definition at line 46 of file Operator.h.
References llvm::cast(), llvm::OverflowingBinaryOperator::classof(), and llvm::sandboxir::Value::Val.
classof() [3/3]
bool llvm::sandboxir::OverflowingBinaryOperator::classof (const Value * From) inline static
Definition at line 54 of file Operator.h.
References llvm::OverflowingBinaryOperator::classof(), and llvm::sandboxir::Value::Val.
getNoWrapKind()
unsigned llvm::sandboxir::OverflowingBinaryOperator::getNoWrapKind () const inline
Definition at line 43 of file Operator.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasNoSignedWrap()
bool llvm::sandboxir::OverflowingBinaryOperator::hasNoSignedWrap () const inline
Definition at line 40 of file Operator.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasNoUnsignedWrap()
bool llvm::sandboxir::OverflowingBinaryOperator::hasNoUnsignedWrap () const inline
Definition at line 37 of file Operator.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Operator.h