LLVM: llvm::DiagnosticInfoPGOProfile Class Reference
llvm::DiagnosticInfoPGOProfile Class Reference
Diagnostic information for the PGO profiler.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoPGOProfile (const char *FileName, const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity=DS_Error)
void print (DiagnosticPrinter &DP) const override
const char * getFileName () const
const Twine & getMsg () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for the PGO profiler.
Definition at line 303 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoPGOProfile()
llvm::DiagnosticInfoPGOProfile::DiagnosticInfoPGOProfile (const char * FileName, const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity = DS_Error) inline
Definition at line 305 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_PGOProfile, llvm::DS_Error, and LLVM_LIFETIME_BOUND.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoPGOProfile::classof (const DiagnosticInfo * DI) inline static
Definition at line 313 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_PGOProfile, and llvm::DiagnosticInfo::getKind().
getFileName()
const char * llvm::DiagnosticInfoPGOProfile::getFileName () const inline
Definition at line 317 of file DiagnosticInfo.h.
Referenced by print().
getMsg()
const Twine & llvm::DiagnosticInfoPGOProfile::getMsg () const inline
Definition at line 318 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoPGOProfile::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 139 of file DiagnosticInfo.cpp.
References getFileName(), and getMsg().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp