LLVM: llvm::ThreadSafeTrieRawHashMapBase::ImplType Class Reference
llvm::ThreadSafeTrieRawHashMapBase::ImplType Class Reference final
Public Member Functions
TrieSubtrie * save (std::unique_ptr< TrieSubtrie > S)
TrieSubtrie * getRoot ()
void operator delete (void *Ptr)
Static Public Member Functions
static std::unique_ptr< ImplType > create (size_t StartBit, size_t NumBits)
static void * operator new (size_t Size)
Public Attributes
ThreadSafeAllocator< BumpPtrAllocator > ContentAlloc
FIXME: This should take a function that allocates and constructs the content lazily (taking the hash as a separate parameter), in case of collision.
Friends
class TrailingObjects
Detailed Description
Definition at line 163 of file TrieRawHashMap.cpp.
Member Function Documentation
create()
std::unique_ptr< ImplType > llvm::ThreadSafeTrieRawHashMapBase::ImplType::create (size_t StartBit, size_t NumBits) inline static
Definition at line 167 of file TrieRawHashMap.cpp.
References Size.
Referenced by TrailingObjects.
getRoot()
TrieSubtrie * llvm::ThreadSafeTrieRawHashMapBase::ImplType::getRoot () inline
Definition at line 193 of file TrieRawHashMap.cpp.
References llvm::TrailingObjects< ThreadSafeTrieRawHashMapBase::ImplType, TrieSubtrie >::getTrailingObjects().
operator delete()
void llvm::ThreadSafeTrieRawHashMapBase::ImplType::operator delete (void * Ptr) inline
Definition at line 196 of file TrieRawHashMap.cpp.
operator new()
void * llvm::ThreadSafeTrieRawHashMapBase::ImplType::operator new (size_t Size) inline static
Definition at line 195 of file TrieRawHashMap.cpp.
References Size.
save()
TrieSubtrie * llvm::ThreadSafeTrieRawHashMapBase::ImplType::save (std::unique_ptr< TrieSubtrie > S) inline
Definition at line 177 of file TrieRawHashMap.cpp.
References assert(), getRoot(), and llvm::Next.
Friends And Related Symbol Documentation
TrailingObjects
friend class TrailingObjects friend
Definition at line 204 of file TrieRawHashMap.cpp.
References create(), if(), llvm::ThreadSafeTrieRawHashMapBase::ThreadSafeTrieRawHashMapBase(), and TrailingObjects.
Referenced by TrailingObjects.
Member Data Documentation
ContentAlloc
ThreadSafeAllocator<BumpPtrAllocator> llvm::ThreadSafeTrieRawHashMapBase::ImplType::ContentAlloc
FIXME: This should take a function that allocates and constructs the content lazily (taking the hash as a separate parameter), in case of collision.
Definition at line 201 of file TrieRawHashMap.cpp.
The documentation for this class was generated from the following file:
lib/Support/TrieRawHashMap.cpp