LLVM: llvm::CaptureInfo Class Reference
llvm::CaptureInfo Class Reference
Represents which components of the pointer may be captured in which location.
#include "llvm/Support/ModRef.h"
Public Member Functions
CaptureInfo (CaptureComponents OtherComponents, CaptureComponents RetComponents)
CaptureInfo (CaptureComponents Components)
bool isRetOnly () const
Whether the pointer is only captured via the return value.
CaptureComponents getRetComponents () const
Get components potentially captured by the return value.
CaptureComponents getOtherComponents () const
Get components potentially captured through locations other than the return value.
operator CaptureComponents () const
Get the potentially captured components of the pointer (regardless of location).
bool operator== (CaptureInfo Other) const
bool operator!= (CaptureInfo Other) const
CaptureInfo operator| (CaptureInfo Other) const
Compute union of CaptureInfos.
CaptureInfo operator& (CaptureInfo Other) const
Compute intersection of CaptureInfos.
CaptureInfo & operator|= (CaptureInfo Other)
Compute union of CaptureInfos in-place.
CaptureInfo & operator&= (CaptureInfo Other)
Compute intersection of CaptureInfos in-place.
uint32_t toIntValue () const
Convert CaptureInfo into an encoded integer value (used by captures attribute).
Static Public Member Functions
static CaptureInfo none ()
Create CaptureInfo that does not capture any components of the pointer.
static CaptureInfo all ()
Create CaptureInfo that may capture all components of the pointer.
static CaptureInfo retOnly (CaptureComponents RetComponents=CaptureComponents::All)
Create CaptureInfo that may only capture via the return value.
static CaptureInfo createFromIntValue (uint32_t Data)
Detailed Description
Represents which components of the pointer may be captured in which location.
This represents the captures(...) attribute in IR.
For more information on the precise semantics see LangRef.
Definition at line 359 of file ModRef.h.
Constructor & Destructor Documentation
CaptureInfo() [1/2]
llvm::CaptureInfo::CaptureInfo (CaptureComponents OtherComponents, CaptureComponents RetComponents) inline
Definition at line 364 of file ModRef.h.
Referenced by all(), createFromIntValue(), none(), operator!=(), operator&(), operator&=(), operator==(), operator|(), operator|=(), and retOnly().
CaptureInfo() [2/2]
llvm::CaptureInfo::CaptureInfo (CaptureComponents Components) inline
Definition at line 368 of file ModRef.h.
Member Function Documentation
all()
CaptureInfo llvm::CaptureInfo::all () inline static
Create CaptureInfo that may capture all components of the pointer.
Definition at line 375 of file ModRef.h.
References llvm::All, and CaptureInfo().
Referenced by llvm::AttributeSet::getCaptureInfo(), llvm::AttributeSetNode::getCaptureInfo(), and llvm::CallBase::getCaptureInfo().
createFromIntValue()
CaptureInfo llvm::CaptureInfo::createFromIntValue (uint32_t Data) inline static
Definition at line 430 of file ModRef.h.
References CaptureInfo(), and llvm::Data.
Referenced by llvm::Attribute::getCaptureInfo().
getOtherComponents()
CaptureComponents llvm::CaptureInfo::getOtherComponents () const inline
Get components potentially captured through locations other than the return value.
Definition at line 391 of file ModRef.h.
Referenced by llvm::AAResults::callCapturesBefore(), llvm::DetermineUseCaptureKind(), llvm::CallBase::hasArgumentWithAdditionalReturnCaptureComponents(), and llvm::operator<<().
getRetComponents()
CaptureComponents llvm::CaptureInfo::getRetComponents () const inline
Get components potentially captured by the return value.
Definition at line 387 of file ModRef.h.
Referenced by llvm::DetermineUseCaptureKind(), llvm::CallBase::hasArgumentWithAdditionalReturnCaptureComponents(), and llvm::operator<<().
isRetOnly()
bool llvm::CaptureInfo::isRetOnly () const inline
Whether the pointer is only captured via the return value.
Definition at line 384 of file ModRef.h.
References llvm::capturesNothing().
none()
CaptureInfo llvm::CaptureInfo::none () inline static
Create CaptureInfo that does not capture any components of the pointer.
Definition at line 372 of file ModRef.h.
References CaptureInfo(), and llvm::None.
Referenced by addArgumentAttrs(), decodeLLVMAttributesForBitcode(), llvm::CallBase::getCaptureInfo(), llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy(), llvm::AANoCapture::isImpliedByIR(), and setDoesNotCapture().
operator CaptureComponents()
llvm::CaptureInfo::operator CaptureComponents () const inline
Get the potentially captured components of the pointer (regardless of location).
Definition at line 395 of file ModRef.h.
operator!=()
bool llvm::CaptureInfo::operator!= (CaptureInfo Other) const inline
Definition at line 402 of file ModRef.h.
References CaptureInfo(), and llvm::Other.
operator&()
CaptureInfo llvm::CaptureInfo::operator& (CaptureInfo Other) const inline
Compute intersection of CaptureInfos.
Definition at line 411 of file ModRef.h.
References CaptureInfo(), and llvm::Other.
operator&=()
CaptureInfo & llvm::CaptureInfo::operator&= (CaptureInfo Other) inline
Compute intersection of CaptureInfos in-place.
Definition at line 424 of file ModRef.h.
References CaptureInfo(), and llvm::Other.
operator==()
bool llvm::CaptureInfo::operator== (CaptureInfo Other) const inline
Definition at line 397 of file ModRef.h.
References CaptureInfo(), and llvm::Other.
operator|()
CaptureInfo llvm::CaptureInfo::operator| (CaptureInfo Other) const inline
Compute union of CaptureInfos.
Definition at line 405 of file ModRef.h.
References CaptureInfo(), and llvm::Other.
operator|=()
CaptureInfo & llvm::CaptureInfo::operator|= (CaptureInfo Other) inline
Compute union of CaptureInfos in-place.
Definition at line 417 of file ModRef.h.
References CaptureInfo(), and llvm::Other.
retOnly()
CaptureInfo llvm::CaptureInfo::retOnly (CaptureComponents RetComponents = CaptureComponents::All) inline static
Create CaptureInfo that may only capture via the return value.
Definition at line 379 of file ModRef.h.
References llvm::All, CaptureInfo(), and llvm::None.
toIntValue()
uint32_t llvm::CaptureInfo::toIntValue () const inline
Convert CaptureInfo into an encoded integer value (used by captures attribute).
Definition at line 437 of file ModRef.h.
Referenced by llvm::AttrBuilder::addCapturesAttr(), and llvm::Attribute::getWithCaptureInfo().
The documentation for this class was generated from the following file:
include/llvm/Support/ModRef.h