LLVM: llvm::DiagnosticInfoLegalizationFailure Class Reference
llvm::DiagnosticInfoLegalizationFailure Class Reference
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoLegalizationFailure (const Twine &MsgStr LLVM_LIFETIME_BOUND, const Function &Fn, const DiagnosticLocation &Loc, DiagnosticSeverity Severity=DS_Error)
const Twine & getMsgStr () const
void print (DiagnosticPrinter &DP) const override
Print using the given DP a user-friendly message.
Public Member Functions inherited from llvm::DiagnosticInfoWithLocationBase
DiagnosticInfoWithLocationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const Function &Fn, const DiagnosticLocation &Loc)
Fn is the function where the diagnostic is being emitted.
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
std::string getLocationStr () const
Return a string with the location information for this diagnostic in the format "file:line:col".
void getLocation (StringRef &RelativePath, unsigned &Line, unsigned &Column) const
Return location information for this diagnostic in three parts: the relative source file path, line number and column.
std::string getAbsolutePath () const
Return the absolute path tot the file.
const Function & getFunction () const
DiagnosticLocation getLocation () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Definition at line 386 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoLegalizationFailure()
llvm::DiagnosticInfoLegalizationFailure::DiagnosticInfoLegalizationFailure (const Twine &MsgStr LLVM_LIFETIME_BOUND, const Function & Fn, const DiagnosticLocation & Loc, DiagnosticSeverity Severity = DS_Error) inline
Definition at line 393 of file DiagnosticInfo.h.
References llvm::DiagnosticInfoWithLocationBase::DiagnosticInfoWithLocationBase(), llvm::DK_LegalizationFailure, llvm::DS_Error, and LLVM_LIFETIME_BOUND.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoLegalizationFailure::classof (const DiagnosticInfo * DI) inline static
Definition at line 405 of file DiagnosticInfo.h.
References llvm::DK_LegalizationFailure, and llvm::DiagnosticInfo::getKind().
getMsgStr()
const Twine & llvm::DiagnosticInfoLegalizationFailure::getMsgStr () const inline
Definition at line 401 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoLegalizationFailure::print (DiagnosticPrinter & DP) const override virtual
Print using the given DP a user-friendly message.
This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implements llvm::DiagnosticInfo.
Definition at line 84 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoWithLocationBase::getLocationStr(), and getMsgStr().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp