LLVM: llvm::DIArgList Class Reference
llvm::DIArgList Class Reference
List of ValueAsMetadata, to be used as an argument to a dbg.value intrinsic.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
ArrayRef< ValueAsMetadata * > getArgs () const
iterator args_begin ()
iterator args_end ()
SmallVector< DbgVariableRecord * > getAllDbgVariableRecordUsers ()
LLVM_ABI void handleChangedOperand (void *Ref, Metadata *New)
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static LLVM_ABI DIArgList * get (LLVMContext &Context, ArrayRef< ValueAsMetadata * > Args)
static bool classof (const Metadata *MD)
Friends
class ReplaceableMetadataImpl
class LLVMContextImpl
Additional Inherited Members
Public Types inherited from llvm::Metadata
enum MetadataKind
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
List of ValueAsMetadata, to be used as an argument to a dbg.value intrinsic.
Definition at line 4648 of file DebugInfoMetadata.h.
Member Function Documentation
args_begin()
iterator llvm::DIArgList::args_begin () inline
Definition at line 4672 of file DebugInfoMetadata.h.
args_end()
iterator llvm::DIArgList::args_end () inline
Definition at line 4673 of file DebugInfoMetadata.h.
classof()
bool llvm::DIArgList::classof (const Metadata * MD) inline static
Definition at line 4675 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID(), and llvm::Metadata::Metadata().
get()
DIArgList * DIArgList::get (LLVMContext & Context, ArrayRef< ValueAsMetadata * > Args) static
Definition at line 2614 of file DebugInfoMetadata.cpp.
Referenced by llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::DbgVariableRecord::addVariableLocationOps(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::DbgVariableRecord::replaceVariableLocationOp(), llvm::DbgVariableRecord::replaceVariableLocationOp(), restorePreTransformState(), and updateDVIWithLocations().
getAllDbgVariableRecordUsers()
SmallVector< DbgVariableRecord * > llvm::DIArgList::getAllDbgVariableRecordUsers () inline
Definition at line 4679 of file DebugInfoMetadata.h.
References llvm::ReplaceableMetadataImpl::getAllDbgVariableRecordUsers().
Referenced by findDbgIntrinsics().
getArgs()
ArrayRef< ValueAsMetadata * > llvm::DIArgList::getArgs () const inline
Definition at line 4670 of file DebugInfoMetadata.h.
Referenced by llvm::ValueEnumerator::incorporateFunction().
handleChangedOperand()
void DIArgList::handleChangedOperand (void * Ref, Metadata * New)
Definition at line 2624 of file DebugInfoMetadata.cpp.
References assert(), llvm::cast_or_null(), llvm::LLVMContextImpl::DIArgLists, llvm::PoisonValue::get(), llvm::ValueAsMetadata::get(), llvm::ReplaceableMetadataImpl::getContext(), llvm::getUniqued(), llvm::isa(), llvm::Metadata::Metadata(), llvm::LLVMContext::pImpl, llvm::pImpl, llvm::Ref, and llvm::ReplaceableMetadataImpl::replaceAllUsesWith().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 4650 of file DebugInfoMetadata.h.
References LLVMContextImpl, llvm::Metadata::Metadata(), ReplaceableMetadataImpl, and llvm::Metadata::Uniqued.
Referenced by LLVMContextImpl.
ReplaceableMetadataImpl
friend class ReplaceableMetadataImpl friend
Definition at line 4649 of file DebugInfoMetadata.h.
References ReplaceableMetadataImpl.
Referenced by LLVMContextImpl, and ReplaceableMetadataImpl.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp