LLVM: llvm::MCSectionCOFF Class Reference
llvm::MCSectionCOFF Class Reference final
This represents a section on Windows.
#include "llvm/MC/MCSectionCOFF.h"
Public Member Functions
bool shouldOmitSectionDirective (StringRef Name) const
Decides whether a '.section' directive should be printed before the section name.
unsigned getCharacteristics () const
MCSymbol * getCOMDATSymbol () const
int getSelection () const
void setSelection (int Selection) const
bool isUnique () const
unsigned getUniqueID () const
unsigned getOrAssignWinCFISectionID (unsigned *NextID) const
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
StringRef getName () const
bool isText () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
Align getAlign () const
void setAlignment (Align Value)
void ensureMinAlignment (Align MinAlignment)
Makes sure that Alignment is at least MinAlignment.
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
unsigned firstLinkerRelaxable () const
bool isLinkerRelaxable () const
void setFirstLinkerRelaxable (unsigned Order)
MCFragment & getDummyFragment ()
FragList * curFragList () const
iterator begin () const
iterator end () const
void dump (DenseMap< const MCFragment *, SmallVector< const MCSymbol *, 0 > > *FragToSyms=nullptr) const
bool isBssSection () const
Check whether this section is "virtual", that is has no actual object file contents.
Static Public Member Functions
static bool isImplicitlyDiscardable (StringRef Name)
Friends
class MCContext
class MCAsmInfoCOFF
Additional Inherited Members
Public Attributes inherited from llvm::MCSection
friend MCAssembler
friend MCObjectStreamer
Static Public Attributes inherited from llvm::MCSection
static constexpr unsigned NonUniqueID = ~0U
Protected Member Functions inherited from llvm::MCSection
MCSection (StringRef Name, bool IsText, bool IsBss, MCSymbol *Begin)
Protected Attributes inherited from llvm::MCSection
StringRef Name
Detailed Description
This represents a section on Windows.
Definition at line 27 of file MCSectionCOFF.h.
Member Function Documentation
getCharacteristics()
unsigned llvm::MCSectionCOFF::getCharacteristics () const inline
Definition at line 73 of file MCSectionCOFF.h.
Referenced by llvm::MCContext::getAssociativeCOFFSection().
getCOMDATSymbol()
MCSymbol * llvm::MCSectionCOFF::getCOMDATSymbol () const inline
Definition at line 74 of file MCSectionCOFF.h.
Referenced by llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), llvm::MCContext::getCOFFSection(), and llvm::WinCOFFWriter::writeObject().
getOrAssignWinCFISectionID()
unsigned llvm::MCSectionCOFF::getOrAssignWinCFISectionID (unsigned * NextID) const inline
Definition at line 82 of file MCSectionCOFF.h.
getSelection()
int llvm::MCSectionCOFF::getSelection () const inline
Definition at line 75 of file MCSectionCOFF.h.
getUniqueID()
unsigned llvm::MCSectionCOFF::getUniqueID () const inline
Definition at line 80 of file MCSectionCOFF.h.
isImplicitlyDiscardable()
bool llvm::MCSectionCOFF::isImplicitlyDiscardable (StringRef Name) inline static
Definition at line 88 of file MCSectionCOFF.h.
References llvm::MCSection::Name.
isUnique()
bool llvm::MCSectionCOFF::isUnique () const inline
Definition at line 79 of file MCSectionCOFF.h.
References llvm::MCSection::NonUniqueID.
Referenced by shouldOmitSectionDirective().
setSelection()
void MCSectionCOFF::setSelection (int Selection) const
Definition at line 89 of file MCAsmInfoCOFF.cpp.
References assert(), and llvm::COFF::IMAGE_SCN_LNK_COMDAT.
shouldOmitSectionDirective()
bool MCSectionCOFF::shouldOmitSectionDirective (StringRef Name) const
Decides whether a '.section' directive should be printed before the section name.
Definition at line 78 of file MCAsmInfoCOFF.cpp.
References isUnique(), and llvm::MCSection::Name.
Friends And Related Symbol Documentation
MCAsmInfoCOFF
friend class MCAsmInfoCOFF friend
Definition at line 54 of file MCSectionCOFF.h.
References MCAsmInfoCOFF, llvm::MCSection::MCSection(), and llvm::MCSection::Name.
Referenced by MCAsmInfoCOFF.
MCContext
friend class MCContext friend
Definition at line 53 of file MCSectionCOFF.h.
References MCContext.
Referenced by MCContext.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSectionCOFF.h
lib/MC/MCAsmInfoCOFF.cpp