LLVM: llvm::SelectionDAGISel Class Reference
llvm::SelectionDAGISel Class Reference abstract
SelectionDAGISel - This is the common base class used for SelectionDAG-based pattern-matching instruction selectors.
#include "llvm/CodeGen/SelectionDAGISel.h"
Public Types
enum BuiltinOpcodes {
OPC_Scope , OPC_RecordNode , OPC_RecordChild0 , OPC_RecordChild1 ,
OPC_RecordChild2 , OPC_RecordChild3 , OPC_RecordChild4 , OPC_RecordChild5 ,
OPC_RecordChild6 , OPC_RecordChild7 , OPC_RecordMemRef , OPC_CaptureGlueInput ,
OPC_CaptureDeactivationSymbol , OPC_MoveChild , OPC_MoveChild0 , OPC_MoveChild1 ,
OPC_MoveChild2 , OPC_MoveChild3 , OPC_MoveChild4 , OPC_MoveChild5 ,
OPC_MoveChild6 , OPC_MoveChild7 , OPC_MoveSibling , OPC_MoveSibling0 ,
OPC_MoveSibling1 , OPC_MoveSibling2 , OPC_MoveSibling3 , OPC_MoveSibling4 ,
OPC_MoveSibling5 , OPC_MoveSibling6 , OPC_MoveSibling7 , OPC_MoveParent ,
OPC_CheckSame , OPC_CheckChild0Same , OPC_CheckChild1Same , OPC_CheckChild2Same ,
OPC_CheckChild3Same , OPC_CheckPatternPredicate , OPC_CheckPatternPredicate0 , OPC_CheckPatternPredicate1 ,
OPC_CheckPatternPredicate2 , OPC_CheckPatternPredicate3 , OPC_CheckPatternPredicate4 , OPC_CheckPatternPredicate5 ,
OPC_CheckPatternPredicate6 , OPC_CheckPatternPredicate7 , OPC_CheckPatternPredicateTwoByte , OPC_CheckPredicate ,
OPC_CheckPredicate0 , OPC_CheckPredicate1 , OPC_CheckPredicate2 , OPC_CheckPredicate3 ,
OPC_CheckPredicate4 , OPC_CheckPredicate5 , OPC_CheckPredicate6 , OPC_CheckPredicate7 ,
OPC_CheckPredicateWithOperands , OPC_CheckOpcode , OPC_SwitchOpcode , OPC_CheckType ,
OPC_CheckTypeI32 , OPC_CheckTypeI64 , OPC_CheckTypeRes , OPC_SwitchType ,
OPC_CheckChild0Type , OPC_CheckChild1Type , OPC_CheckChild2Type , OPC_CheckChild3Type ,
OPC_CheckChild4Type , OPC_CheckChild5Type , OPC_CheckChild6Type , OPC_CheckChild7Type ,
OPC_CheckChild0TypeI32 , OPC_CheckChild1TypeI32 , OPC_CheckChild2TypeI32 , OPC_CheckChild3TypeI32 ,
OPC_CheckChild4TypeI32 , OPC_CheckChild5TypeI32 , OPC_CheckChild6TypeI32 , OPC_CheckChild7TypeI32 ,
OPC_CheckChild0TypeI64 , OPC_CheckChild1TypeI64 , OPC_CheckChild2TypeI64 , OPC_CheckChild3TypeI64 ,
OPC_CheckChild4TypeI64 , OPC_CheckChild5TypeI64 , OPC_CheckChild6TypeI64 , OPC_CheckChild7TypeI64 ,
OPC_CheckInteger , OPC_CheckChild0Integer , OPC_CheckChild1Integer , OPC_CheckChild2Integer ,
OPC_CheckChild3Integer , OPC_CheckChild4Integer , OPC_CheckCondCode , OPC_CheckChild2CondCode ,
OPC_CheckValueType , OPC_CheckComplexPat , OPC_CheckComplexPat0 , OPC_CheckComplexPat1 ,
OPC_CheckComplexPat2 , OPC_CheckComplexPat3 , OPC_CheckComplexPat4 , OPC_CheckComplexPat5 ,
OPC_CheckComplexPat6 , OPC_CheckComplexPat7 , OPC_CheckAndImm , OPC_CheckOrImm ,
OPC_CheckImmAllOnesV , OPC_CheckImmAllZerosV , OPC_CheckFoldableChainNode , OPC_EmitInteger ,
OPC_EmitIntegerI8 , OPC_EmitIntegerI16 , OPC_EmitIntegerI32 , OPC_EmitIntegerI64 ,
OPC_EmitRegister , OPC_EmitRegisterI32 , OPC_EmitRegisterI64 , OPC_EmitRegister2 ,
OPC_EmitConvertToTarget , OPC_EmitConvertToTarget0 , OPC_EmitConvertToTarget1 , OPC_EmitConvertToTarget2 ,
OPC_EmitConvertToTarget3 , OPC_EmitConvertToTarget4 , OPC_EmitConvertToTarget5 , OPC_EmitConvertToTarget6 ,
OPC_EmitConvertToTarget7 , OPC_EmitMergeInputChains , OPC_EmitMergeInputChains1_0 , OPC_EmitMergeInputChains1_1 ,
OPC_EmitMergeInputChains1_2 , OPC_EmitCopyToReg , OPC_EmitCopyToReg0 , OPC_EmitCopyToReg1 ,
OPC_EmitCopyToReg2 , OPC_EmitCopyToReg3 , OPC_EmitCopyToReg4 , OPC_EmitCopyToReg5 ,
OPC_EmitCopyToReg6 , OPC_EmitCopyToReg7 , OPC_EmitCopyToRegTwoByte , OPC_EmitNodeXForm ,
OPC_EmitNode , OPC_EmitNode0 , OPC_EmitNode1 , OPC_EmitNode2 ,
OPC_EmitNode1None , OPC_EmitNode2None , OPC_EmitNode0Chain , OPC_EmitNode1Chain ,
OPC_EmitNode2Chain , OPC_MorphNodeTo , OPC_MorphNodeTo0 , OPC_MorphNodeTo1 ,
OPC_MorphNodeTo2 , OPC_MorphNodeTo1None , OPC_MorphNodeTo2None , OPC_MorphNodeTo0Chain ,
OPC_MorphNodeTo1Chain , OPC_MorphNodeTo2Chain , OPC_MorphNodeTo1GlueInput , OPC_MorphNodeTo2GlueInput ,
OPC_MorphNodeTo1GlueOutput , OPC_MorphNodeTo2GlueOutput , OPC_CompleteMatch , OPC_Coverage
}
enum {
OPFL_None = 0 , OPFL_Chain = 1 , OPFL_GlueInput = 2 , OPFL_GlueOutput = 4 ,
OPFL_MemRefs = 8 , OPFL_Variadic0 = 1 << 4 , OPFL_Variadic1 = 2 << 4 , OPFL_Variadic2 = 3 << 4 ,
OPFL_Variadic3 = 4 << 4 , OPFL_Variadic4 = 5 << 4 , OPFL_Variadic5 = 6 << 4 , OPFL_Variadic6 = 7 << 4 ,
OPFL_Variadic7 = 8 << 4 , OPFL_VariadicInfo = 15 << 4
}
Public Member Functions
SelectionDAGISel (TargetMachine &tm, CodeGenOptLevel OL=CodeGenOptLevel::Default)
virtual ~SelectionDAGISel ()
BatchAAResults * getBatchAA () const
Returns a (possibly null) pointer to the current BatchAAResults.
const TargetLowering * getTargetLowering () const
void initializeAnalysisResults (MachineFunctionAnalysisManager &MFAM)
void initializeAnalysisResults (MachineFunctionPass &MFP)
virtual bool runOnMachineFunction (MachineFunction &mf)
virtual void emitFunctionEntryCode ()
virtual void PreprocessISelDAG ()
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
virtual void PostprocessISelDAG ()
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
virtual void Select (SDNode *N)=0
Main hook for targets to transform nodes into machine nodes.
virtual bool SelectInlineAsmMemoryOperand (const SDValue &Op, InlineAsm::ConstraintCode ConstraintID, std::vector< SDValue > &OutOps)
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255).
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255).
virtual bool CheckPatternPredicate (unsigned PredNo) const
CheckPatternPredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicate (SDValue Op, unsigned PredNo) const
CheckNodePredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicateWithOperands (SDValue Op, unsigned PredNo, ArrayRef< SDValue > Operands) const
CheckNodePredicateWithOperands - This function is generated by tblgen in the target.
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
void SelectCodeCommon (SDNode *NodeToMatch, const uint8_t *MatcherTable, unsigned TableSize)
virtual bool ComplexPatternFuncMutatesDAG () const
Return true if complex patterns for this target can mutate the DAG.
bool mayRaiseFPException (SDNode *Node) const
Return whether the node may raise an FP exception.
bool isOrEquivalentToAdd (const SDNode *N) const
Static Public Member Functions
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOptLevel OptLevel, bool IgnoreChains=false)
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
static void InvalidateNodeId (SDNode *N)
static int getUninvalidatedNodeId (SDNode *N)
static void EnforceNodeIdInvariant (SDNode *N)
static int getNumFixedFromVariadicInfo (unsigned Flags)
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Public Attributes
TargetMachine & TM
const TargetLibraryInfo * LibInfo
const RTLIB::RuntimeLibcallsInfo * RuntimeLibCallInfo
std::unique_ptr< FunctionLoweringInfo > FuncInfo
std::unique_ptr< SwiftErrorValueTracking > SwiftError
MachineFunction * MF
MachineModuleInfo * MMI
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
std::unique_ptr< SelectionDAGBuilder > SDB
std::optional< BatchAAResults > BatchAA
AssumptionCache * AC = nullptr
GCFunctionInfo * GFI = nullptr
SSPLayoutInfo * SP = nullptr
const TargetTransformInfo * TTI = nullptr
CodeGenOptLevel OptLevel
const TargetInstrInfo * TII
const TargetLowering * TLI
bool FastISelFailed
SmallPtrSet< const Instruction *, 4 > ElidedArgCopyInstrs
std::unique_ptr< OptimizationRemarkEmitter > ORE
Current optimization remark emitter.
bool MatchFilterFuncName = false
True if the function currently processing is in the function printing list (i.e.
StringRef FuncName
Protected Member Functions
void ReplaceUses (SDValue F, SDValue T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
void ReplaceUses (SDNode *F, SDNode *T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceNode (SDNode *F, SDNode *T)
Replace all uses of F with T, then remove F from the DAG.
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops, const SDLoc &DL)
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen.
virtual StringRef getPatternForIndex (unsigned index)
getPatternForIndex - Patterns selected by tablegen during ISEL
virtual StringRef getIncludePathForIndex (unsigned index)
getIncludePathForIndex - get the td source location of pattern instantiation
bool shouldOptForSize (const MachineFunction *MF) const
Protected Attributes
unsigned DAGSize = 0
DAGSize - Size of DAG being instruction selected.
Detailed Description
SelectionDAGISel - This is the common base class used for SelectionDAG-based pattern-matching instruction selectors.
Definition at line 45 of file SelectionDAGISel.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OPFL_None
OPFL_Chain
OPFL_GlueInput
OPFL_GlueOutput
OPFL_MemRefs
OPFL_Variadic0
OPFL_Variadic1
OPFL_Variadic2
OPFL_Variadic3
OPFL_Variadic4
OPFL_Variadic5
OPFL_Variadic6
OPFL_Variadic7
OPFL_VariadicInfo
Definition at line 323 of file SelectionDAGISel.h.
BuiltinOpcodes
enum llvm::SelectionDAGISel::BuiltinOpcodes
Enumerator
OPC_Scope
OPC_RecordNode
OPC_RecordChild0
OPC_RecordChild1
OPC_RecordChild2
OPC_RecordChild3
OPC_RecordChild4
OPC_RecordChild5
OPC_RecordChild6
OPC_RecordChild7
OPC_RecordMemRef
OPC_CaptureGlueInput
OPC_CaptureDeactivationSymbol
OPC_MoveChild
OPC_MoveChild0
OPC_MoveChild1
OPC_MoveChild2
OPC_MoveChild3
OPC_MoveChild4
OPC_MoveChild5
OPC_MoveChild6
OPC_MoveChild7
OPC_MoveSibling
OPC_MoveSibling0
OPC_MoveSibling1
OPC_MoveSibling2
OPC_MoveSibling3
OPC_MoveSibling4
OPC_MoveSibling5
OPC_MoveSibling6
OPC_MoveSibling7
OPC_MoveParent
OPC_CheckSame
OPC_CheckChild0Same
OPC_CheckChild1Same
OPC_CheckChild2Same
OPC_CheckChild3Same
OPC_CheckPatternPredicate
OPC_CheckPatternPredicate0
OPC_CheckPatternPredicate1
OPC_CheckPatternPredicate2
OPC_CheckPatternPredicate3
OPC_CheckPatternPredicate4
OPC_CheckPatternPredicate5
OPC_CheckPatternPredicate6
OPC_CheckPatternPredicate7
OPC_CheckPatternPredicateTwoByte
OPC_CheckPredicate
OPC_CheckPredicate0
OPC_CheckPredicate1
OPC_CheckPredicate2
OPC_CheckPredicate3
OPC_CheckPredicate4
OPC_CheckPredicate5
OPC_CheckPredicate6
OPC_CheckPredicate7
OPC_CheckPredicateWithOperands
OPC_CheckOpcode
OPC_SwitchOpcode
OPC_CheckType
OPC_CheckTypeI32
OPC_CheckTypeI64
OPC_CheckTypeRes
OPC_SwitchType
OPC_CheckChild0Type
OPC_CheckChild1Type
OPC_CheckChild2Type
OPC_CheckChild3Type
OPC_CheckChild4Type
OPC_CheckChild5Type
OPC_CheckChild6Type
OPC_CheckChild7Type
OPC_CheckChild0TypeI32
OPC_CheckChild1TypeI32
OPC_CheckChild2TypeI32
OPC_CheckChild3TypeI32
OPC_CheckChild4TypeI32
OPC_CheckChild5TypeI32
OPC_CheckChild6TypeI32
OPC_CheckChild7TypeI32
OPC_CheckChild0TypeI64
OPC_CheckChild1TypeI64
OPC_CheckChild2TypeI64
OPC_CheckChild3TypeI64
OPC_CheckChild4TypeI64
OPC_CheckChild5TypeI64
OPC_CheckChild6TypeI64
OPC_CheckChild7TypeI64
OPC_CheckInteger
OPC_CheckChild0Integer
OPC_CheckChild1Integer
OPC_CheckChild2Integer
OPC_CheckChild3Integer
OPC_CheckChild4Integer
OPC_CheckCondCode
OPC_CheckChild2CondCode
OPC_CheckValueType
OPC_CheckComplexPat
OPC_CheckComplexPat0
OPC_CheckComplexPat1
OPC_CheckComplexPat2
OPC_CheckComplexPat3
OPC_CheckComplexPat4
OPC_CheckComplexPat5
OPC_CheckComplexPat6
OPC_CheckComplexPat7
OPC_CheckAndImm
OPC_CheckOrImm
OPC_CheckImmAllOnesV
OPC_CheckImmAllZerosV
OPC_CheckFoldableChainNode
OPC_EmitInteger
OPC_EmitIntegerI8
OPC_EmitIntegerI16
OPC_EmitIntegerI32
OPC_EmitIntegerI64
OPC_EmitRegister
OPC_EmitRegisterI32
OPC_EmitRegisterI64
OPC_EmitRegister2
OPC_EmitConvertToTarget
OPC_EmitConvertToTarget0
OPC_EmitConvertToTarget1
OPC_EmitConvertToTarget2
OPC_EmitConvertToTarget3
OPC_EmitConvertToTarget4
OPC_EmitConvertToTarget5
OPC_EmitConvertToTarget6
OPC_EmitConvertToTarget7
OPC_EmitMergeInputChains
OPC_EmitMergeInputChains1_0
OPC_EmitMergeInputChains1_1
OPC_EmitMergeInputChains1_2
OPC_EmitCopyToReg
OPC_EmitCopyToReg0
OPC_EmitCopyToReg1
OPC_EmitCopyToReg2
OPC_EmitCopyToReg3
OPC_EmitCopyToReg4
OPC_EmitCopyToReg5
OPC_EmitCopyToReg6
OPC_EmitCopyToReg7
OPC_EmitCopyToRegTwoByte
OPC_EmitNodeXForm
OPC_EmitNode
OPC_EmitNode0
OPC_EmitNode1
OPC_EmitNode2
OPC_EmitNode1None
OPC_EmitNode2None
OPC_EmitNode0Chain
OPC_EmitNode1Chain
OPC_EmitNode2Chain
OPC_MorphNodeTo
OPC_MorphNodeTo0
OPC_MorphNodeTo1
OPC_MorphNodeTo2
OPC_MorphNodeTo1None
OPC_MorphNodeTo2None
OPC_MorphNodeTo0Chain
OPC_MorphNodeTo1Chain
OPC_MorphNodeTo2Chain
OPC_MorphNodeTo1GlueInput
OPC_MorphNodeTo2GlueInput
OPC_MorphNodeTo1GlueOutput
OPC_MorphNodeTo2GlueOutput
OPC_CompleteMatch
OPC_Coverage
Definition at line 141 of file SelectionDAGISel.h.
Constructor & Destructor Documentation
SelectionDAGISel()
SelectionDAGISel::SelectionDAGISel (TargetMachine & tm, CodeGenOptLevel OL = CodeGenOptLevel::Default) explicit
Definition at line 404 of file SelectionDAGISel.cpp.
References CurDAG, FuncInfo, llvm::PassRegistry::getPassRegistry(), llvm::initializeAAResultsWrapperPassPass(), llvm::initializeBranchProbabilityInfoWrapperPassPass(), llvm::initializeGCModuleInfoPass(), llvm::initializeTargetLibraryInfoWrapperPassPass(), OptLevel, SDB, SwiftError, and TM.
Referenced by llvm::AMDGPUDAGToDAGISel::AMDGPUDAGToDAGISel(), llvm::HexagonDAGToDAGISel::HexagonDAGToDAGISel(), llvm::LoongArchDAGToDAGISel::LoongArchDAGToDAGISel(), llvm::MipsDAGToDAGISel::MipsDAGToDAGISel(), llvm::NVPTXDAGToDAGISel::NVPTXDAGToDAGISel(), and llvm::RISCVDAGToDAGISel::RISCVDAGToDAGISel().
~SelectionDAGISel()
SelectionDAGISel::~SelectionDAGISel () virtual
Definition at line 418 of file SelectionDAGISel.cpp.
References CurDAG.
Member Function Documentation
CheckAndMask()
bool SelectionDAGISel::CheckAndMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255).
If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an AND, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 2234 of file SelectionDAGISel.cpp.
References CurDAG, and llvm::APInt::isSubsetOf().
Referenced by CheckAndImm().
CheckComplexPattern()
virtual bool llvm::SelectionDAGISel::CheckComplexPattern (SDNode * Root, SDNode * Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > & Result) inline virtual
Definition at line 437 of file SelectionDAGISel.h.
References llvm_unreachable, and N.
Referenced by SelectCodeCommon().
CheckNodePredicate()
virtual bool llvm::SelectionDAGISel::CheckNodePredicate (SDValue Op, unsigned PredNo) const inline virtual
CheckNodePredicate - This function is generated by tblgen in the target.
It runs node predicate number PredNo and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 422 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by CheckNodePredicate(), and SelectCodeCommon().
CheckNodePredicateWithOperands()
virtual bool llvm::SelectionDAGISel::CheckNodePredicateWithOperands (SDValue Op, unsigned PredNo, ArrayRef< SDValue > Operands) const inline virtual
CheckNodePredicateWithOperands - This function is generated by tblgen in the target.
It runs node predicate number PredNo and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 432 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
CheckOrMask()
bool SelectionDAGISel::CheckOrMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255).
If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an OR, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 2266 of file SelectionDAGISel.cpp.
References CurDAG, llvm::APInt::isSubsetOf(), and llvm::KnownBits::One.
Referenced by CheckOrImm().
CheckPatternPredicate()
virtual bool llvm::SelectionDAGISel::CheckPatternPredicate (unsigned PredNo) const inline virtual
CheckPatternPredicate - This function is generated by tblgen in the target.
It runs the specified pattern predicate and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 414 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by CheckPatternPredicate(), and SelectCodeCommon().
ComplexPatternFuncMutatesDAG()
virtual bool llvm::SelectionDAGISel::ComplexPatternFuncMutatesDAG () const inline virtual
Return true if complex patterns for this target can mutate the DAG.
Reimplemented in llvm::HexagonDAGToDAGISel.
Definition at line 452 of file SelectionDAGISel.h.
Referenced by SelectCodeCommon().
emitFunctionEntryCode()
virtual void llvm::SelectionDAGISel::emitFunctionEntryCode () inline virtual
Reimplemented in llvm::HexagonDAGToDAGISel.
Definition at line 98 of file SelectionDAGISel.h.
EnforceNodeIdInvariant()
void SelectionDAGISel::EnforceNodeIdInvariant (SDNode * N) static
Definition at line 1244 of file SelectionDAGISel.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::empty(), InvalidateNodeId(), N, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by ReplaceNode(), ReplaceUses(), ReplaceUses(), and ReplaceUses().
getBatchAA()
BatchAAResults * llvm::SelectionDAGISel::getBatchAA () const inline
Returns a (possibly null) pointer to the current BatchAAResults.
Definition at line 85 of file SelectionDAGISel.h.
References BatchAA.
Referenced by runOnMachineFunction().
getIncludePathForIndex()
virtual StringRef llvm::SelectionDAGISel::getIncludePathForIndex (unsigned index) inline protected virtual
getIncludePathForIndex - get the td source location of pattern instantiation
Definition at line 394 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
getNumFixedFromVariadicInfo()
int llvm::SelectionDAGISel::getNumFixedFromVariadicInfo (unsigned Flags) inline static
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Definition at line 344 of file SelectionDAGISel.h.
References OPFL_VariadicInfo.
Referenced by SelectCodeCommon().
getPatternForIndex()
virtual StringRef llvm::SelectionDAGISel::getPatternForIndex (unsigned index) inline protected virtual
getPatternForIndex - Patterns selected by tablegen during ISEL
Definition at line 389 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
getTargetLowering()
const TargetLowering * llvm::SelectionDAGISel::getTargetLowering () const inline
Definition at line 91 of file SelectionDAGISel.h.
References TLI.
Referenced by llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::AMDGPUDAGToDAGISel::PostprocessISelDAG(), and llvm::AMDGPUDAGToDAGISel::Select().
getUninvalidatedNodeId()
int SelectionDAGISel::getUninvalidatedNodeId (SDNode * N) static
Definition at line 1269 of file SelectionDAGISel.cpp.
References N.
Referenced by insertDAGNode(), and insertDAGNode().
initializeAnalysisResults() [1/2]
void SelectionDAGISel::initializeAnalysisResults (MachineFunctionAnalysisManager & MFAM)
Definition at line 479 of file SelectionDAGISel.cpp.
References AC, BatchAA, CurDAG, FAM, FuncInfo, FuncName, llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), GFI, llvm::Function::hasGC(), llvm::isAssignmentTrackingEnabled(), llvm::isFunctionInPrintList(), LibInfo, maintainPGOProfile(), MatchFilterFuncName, MF, MMI, llvm::None, OptLevel, ORE, RegInfo, SP, TII, TLI, TM, TTI, and UseMBPI.
initializeAnalysisResults() [2/2]
void SelectionDAGISel::initializeAnalysisResults (MachineFunctionPass & MFP)
Definition at line 536 of file SelectionDAGISel.cpp.
References AC, BatchAA, CurDAG, FuncInfo, FuncName, llvm::AAResultsWrapperPass::getAAResults(), llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisIfAvailable(), llvm::Value::getName(), llvm::GlobalValue::getParent(), GFI, llvm::Function::hasGC(), llvm::isAssignmentTrackingEnabled(), llvm::isFunctionInPrintList(), LibInfo, maintainPGOProfile(), MatchFilterFuncName, MF, MMI, llvm::None, OptLevel, ORE, RegInfo, SP, TII, TLI, TM, TTI, and UseMBPI.
InvalidateNodeId()
void SelectionDAGISel::InvalidateNodeId (SDNode * N) static
Definition at line 1263 of file SelectionDAGISel.cpp.
References N.
Referenced by EnforceNodeIdInvariant(), insertDAGNode(), and insertDAGNode().
IsLegalToFold()
bool SelectionDAGISel::IsLegalToFold (SDValue N, SDNode * U, SDNode * Root, CodeGenOptLevel OptLevel, bool IgnoreChains = false) static
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
FIXME: This is a static member function because the MSP430/X86 targets, which uses it during isel. This could become a proper member.
Definition at line 2417 of file SelectionDAGISel.cpp.
References findNonImmUse(), llvm::SDNode::getGluedUser(), llvm::SDNode::getNumValues(), llvm::SDNode::getValueType(), N, llvm::None, and OptLevel.
Referenced by llvm::RISCVDAGToDAGISel::Select(), and SelectCodeCommon().
isOrEquivalentToAdd()
bool SelectionDAGISel::isOrEquivalentToAdd (const SDNode * N) const
Definition at line 4462 of file SelectionDAGISel.cpp.
References A(), assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::MachineFrameInfo::getObjectAlign(), MF, N, and llvm::ISD::OR.
IsProfitableToFold()
bool SelectionDAGISel::IsProfitableToFold (SDValue N, SDNode * U, SDNode * Root) const virtual
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
Definition at line 2408 of file SelectionDAGISel.cpp.
References N, llvm::None, and OptLevel.
Referenced by llvm::RISCVDAGToDAGISel::Select(), and SelectCodeCommon().
mayRaiseFPException()
bool SelectionDAGISel::mayRaiseFPException (SDNode * Node) const
Return whether the node may raise an FP exception.
Definition at line 4446 of file SelectionDAGISel.cpp.
References CurDAG, llvm::SelectionDAGTargetInfo::mayRaiseFPException(), N, and TII.
Referenced by SelectCodeCommon().
PostprocessISelDAG()
virtual void llvm::SelectionDAGISel::PostprocessISelDAG () inline virtual
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
Reimplemented in llvm::AMDGPUDAGToDAGISel, and llvm::RISCVDAGToDAGISel.
Definition at line 106 of file SelectionDAGISel.h.
PreprocessISelDAG()
virtual void llvm::SelectionDAGISel::PreprocessISelDAG () inline virtual
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
Reimplemented in llvm::AMDGPUDAGToDAGISel, llvm::HexagonDAGToDAGISel, and llvm::RISCVDAGToDAGISel.
Definition at line 102 of file SelectionDAGISel.h.
Referenced by INITIALIZE_PASS().
ReplaceNode()
void llvm::SelectionDAGISel::ReplaceNode (SDNode * F, SDNode * T) inline protected
Replace all uses of F with T, then remove F from the DAG.
Definition at line 377 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, and T.
Referenced by llvm::HexagonDAGToDAGISel::FastFDiv(), llvm::HexagonDAGToDAGISel::FDiv(), llvm::AMDGPUDAGToDAGISel::Select(), llvm::RISCVDAGToDAGISel::Select(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectExtractSubvector(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::RISCVDAGToDAGISel::selectSF_VC_X_SE(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::RISCVDAGToDAGISel::selectVSETVLI(), llvm::RISCVDAGToDAGISel::selectVSSEG(), llvm::RISCVDAGToDAGISel::selectVSXSEG(), llvm::RISCVDAGToDAGISel::selectXSfmmVSET(), llvm::RISCVDAGToDAGISel::tryIndexedLoad(), llvm::RISCVDAGToDAGISel::tryShrinkShlLogicImm(), llvm::RISCVDAGToDAGISel::trySignedBitfieldExtract(), llvm::RISCVDAGToDAGISel::trySignedBitfieldInsertInSign(), llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldExtract(), and llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldInsertInZero().
ReplaceUses() [1/3]
void llvm::SelectionDAGISel::ReplaceUses (const SDValue * F, const SDValue * T, unsigned Num) inline protected
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
Definition at line 363 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, getNode(), and T.
ReplaceUses() [2/3]
void llvm::SelectionDAGISel::ReplaceUses (SDNode * F, SDNode * T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 371 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, and T.
ReplaceUses() [3/3]
void llvm::SelectionDAGISel::ReplaceUses (SDValue F, SDValue T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 356 of file SelectionDAGISel.h.
References CurDAG, EnforceNodeIdInvariant(), F, and T.
Referenced by llvm::AMDGPUDAGToDAGISel::PostprocessISelDAG(), llvm::RISCVDAGToDAGISel::Select(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::RISCVDAGToDAGISel::selectVLSEG(), llvm::RISCVDAGToDAGISel::selectVLSEGFF(), llvm::RISCVDAGToDAGISel::selectVLXSEG(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), and llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic().
runOnMachineFunction()
bool SelectionDAGISel::runOnMachineFunction (MachineFunction & mf) virtual
Reimplemented in llvm::AMDGPUDAGToDAGISel, llvm::HexagonDAGToDAGISel, llvm::LoongArchDAGToDAGISel, llvm::MipsDAGToDAGISel, llvm::NVPTXDAGToDAGISel, and llvm::RISCVDAGToDAGISel.
Definition at line 593 of file SelectionDAGISel.cpp.
References AC, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::cast(), CurDAG, llvm::dbgs(), llvm::LLVMContext::diagnose(), DL, EnableFastISelFallbackReport, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), FastISelFailed, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), FuncInfo, FuncName, getBatchAA(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), GFI, llvm::MachineFrameInfo::hasCalls(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::isa(), ISEL_DUMP, llvm::Register::isVirtual(), LibInfo, LLVM_DEBUG, MBB, MF, MI, MRI, llvm::None, OptLevel, llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RegInfo, SDB, llvm::MachineFrameInfo::setHasCalls(), llvm::succ_empty(), SwiftError, TII, TLI, TRI, TTI, llvm::MachineFunction::useDebugInstrRef(), and UseMI.
Referenced by llvm::AMDGPUDAGToDAGISel::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::runOnMachineFunction(), llvm::LoongArchDAGToDAGISel::runOnMachineFunction(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), and llvm::RISCVDAGToDAGISel::runOnMachineFunction().
RunSDNodeXForm()
virtual SDValue llvm::SelectionDAGISel::RunSDNodeXForm (SDValue V, unsigned XFormNo) inline virtual
Definition at line 443 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
Select()
virtual void llvm::SelectionDAGISel::Select (SDNode * N) pure virtual
Main hook for targets to transform nodes into machine nodes.
Implemented in llvm::AMDGPUDAGToDAGISel, llvm::HexagonDAGToDAGISel, llvm::LoongArchDAGToDAGISel, and llvm::RISCVDAGToDAGISel.
References N.
SelectCodeCommon()
void SelectionDAGISel::SelectCodeCommon (SDNode * NodeToMatch, const uint8_t * MatcherTable, unsigned TableSize)
Definition at line 3297 of file SelectionDAGISel.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::ANNOTATION_LABEL, llvm::any_of(), llvm::ISD::ARITH_FENCE, assert(), llvm::ISD::AssertAlign, llvm::ISD::AssertNoFPClass, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::ISD::BasicBlock, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), CheckAndImm(), CheckChild2CondCode(), CheckChildInteger(), CheckChildSame(), CheckChildType(), CheckComplexPattern(), CheckCondCode(), CheckInteger(), CheckNodePredicate(), CheckNodePredicateWithOperands(), CheckOpcode(), CheckOrImm(), CheckPatternPredicate(), CheckSame(), CheckValueType(), llvm::SmallVectorImpl< T >::clear(), ComplexPatternFuncMutatesDAG(), llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::CONVERGENCECTRL_ANCHOR, llvm::ISD::CONVERGENCECTRL_ENTRY, llvm::ISD::CONVERGENCECTRL_LOOP, llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, CurDAG, llvm::dbgs(), llvm::ISD::DEACTIVATION_SYMBOL, llvm::ISD::DELETED_NODE, llvm::dyn_cast(), llvm::ISD::EH_LABEL, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ISD::EntryToken, llvm::erase(), llvm::ISD::FAKE_USE, llvm::ISD::FREEZE, getIncludePathForIndex(), llvm::SDValue::getNode(), getNumFixedFromVariadicInfo(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), getPatternForIndex(), GetSignedVBR(), getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDNode::getValueType(), llvm::SDValue::getValueType(), GetVBR(), HandleMergeInputChains(), llvm::ISD::HANDLENODE, llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::is_contained(), llvm::ISD::isConstantSplatVectorAllOnes(), llvm::ISD::isConstantSplatVectorAllZeros(), IsLegalToFold(), llvm::SDNode::isMachineOpcode(), IsPredicateKnownToFail(), IsProfitableToFold(), llvm::ISD::JUMP_TABLE_DEBUG_INFO, llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, LLVM_DEBUG, mayRaiseFPException(), llvm::ISD::MCSymbol, llvm::ISD::MDNODE_SDNODE, llvm::ISD::MEMBARRIER, N, llvm::SDNodeFlags::NoFPExcept, Opc, OPC_CaptureDeactivationSymbol, OPC_CaptureGlueInput, OPC_CheckAndImm, OPC_CheckChild0Integer, OPC_CheckChild0Same, OPC_CheckChild0Type, OPC_CheckChild0TypeI32, OPC_CheckChild0TypeI64, OPC_CheckChild1Integer, OPC_CheckChild1Same, OPC_CheckChild1Type, OPC_CheckChild1TypeI32, OPC_CheckChild1TypeI64, OPC_CheckChild2CondCode, OPC_CheckChild2Integer, OPC_CheckChild2Same, OPC_CheckChild2Type, OPC_CheckChild2TypeI32, OPC_CheckChild2TypeI64, OPC_CheckChild3Integer, OPC_CheckChild3Same, OPC_CheckChild3Type, OPC_CheckChild3TypeI32, OPC_CheckChild3TypeI64, OPC_CheckChild4Integer, OPC_CheckChild4Type, OPC_CheckChild4TypeI32, OPC_CheckChild4TypeI64, OPC_CheckChild5Type, OPC_CheckChild5TypeI32, OPC_CheckChild5TypeI64, OPC_CheckChild6Type, OPC_CheckChild6TypeI32, OPC_CheckChild6TypeI64, OPC_CheckChild7Type, OPC_CheckChild7TypeI32, OPC_CheckChild7TypeI64, OPC_CheckComplexPat, OPC_CheckComplexPat0, OPC_CheckComplexPat1, OPC_CheckComplexPat2, OPC_CheckComplexPat3, OPC_CheckComplexPat4, OPC_CheckComplexPat5, OPC_CheckComplexPat6, OPC_CheckComplexPat7, OPC_CheckCondCode, OPC_CheckFoldableChainNode, OPC_CheckImmAllOnesV, OPC_CheckImmAllZerosV, OPC_CheckInteger, OPC_CheckOpcode, OPC_CheckOrImm, OPC_CheckPatternPredicate, OPC_CheckPatternPredicate0, OPC_CheckPatternPredicate1, OPC_CheckPatternPredicate2, OPC_CheckPatternPredicate3, OPC_CheckPatternPredicate4, OPC_CheckPatternPredicate5, OPC_CheckPatternPredicate6, OPC_CheckPatternPredicate7, OPC_CheckPatternPredicateTwoByte, OPC_CheckPredicate, OPC_CheckPredicate0, OPC_CheckPredicate1, OPC_CheckPredicate2, OPC_CheckPredicate3, OPC_CheckPredicate4, OPC_CheckPredicate5, OPC_CheckPredicate6, OPC_CheckPredicate7, OPC_CheckPredicateWithOperands, OPC_CheckSame, OPC_CheckType, OPC_CheckTypeI32, OPC_CheckTypeI64, OPC_CheckTypeRes, OPC_CheckValueType, OPC_CompleteMatch, OPC_Coverage, OPC_EmitConvertToTarget, OPC_EmitConvertToTarget0, OPC_EmitConvertToTarget1, OPC_EmitConvertToTarget2, OPC_EmitConvertToTarget3, OPC_EmitConvertToTarget4, OPC_EmitConvertToTarget5, OPC_EmitConvertToTarget6, OPC_EmitConvertToTarget7, OPC_EmitCopyToReg, OPC_EmitCopyToReg0, OPC_EmitCopyToReg1, OPC_EmitCopyToReg2, OPC_EmitCopyToReg3, OPC_EmitCopyToReg4, OPC_EmitCopyToReg5, OPC_EmitCopyToReg6, OPC_EmitCopyToReg7, OPC_EmitCopyToRegTwoByte, OPC_EmitInteger, OPC_EmitIntegerI16, OPC_EmitIntegerI32, OPC_EmitIntegerI64, OPC_EmitIntegerI8, OPC_EmitMergeInputChains, OPC_EmitMergeInputChains1_0, OPC_EmitMergeInputChains1_1, OPC_EmitMergeInputChains1_2, OPC_EmitNode, OPC_EmitNode0, OPC_EmitNode0Chain, OPC_EmitNode1, OPC_EmitNode1Chain, OPC_EmitNode1None, OPC_EmitNode2, OPC_EmitNode2Chain, OPC_EmitNode2None, OPC_EmitNodeXForm, OPC_EmitRegister, OPC_EmitRegister2, OPC_EmitRegisterI32, OPC_EmitRegisterI64, OPC_MorphNodeTo, OPC_MorphNodeTo0, OPC_MorphNodeTo0Chain, OPC_MorphNodeTo1, OPC_MorphNodeTo1Chain, OPC_MorphNodeTo1GlueInput, OPC_MorphNodeTo1GlueOutput, OPC_MorphNodeTo1None, OPC_MorphNodeTo2, OPC_MorphNodeTo2Chain, OPC_MorphNodeTo2GlueInput, OPC_MorphNodeTo2GlueOutput, OPC_MorphNodeTo2None, OPC_MoveChild, OPC_MoveChild0, OPC_MoveChild1, OPC_MoveChild2, OPC_MoveChild3, OPC_MoveChild4, OPC_MoveChild5, OPC_MoveChild6, OPC_MoveChild7, OPC_MoveParent, OPC_MoveSibling, OPC_MoveSibling0, OPC_MoveSibling1, OPC_MoveSibling2, OPC_MoveSibling3, OPC_MoveSibling4, OPC_MoveSibling5, OPC_MoveSibling6, OPC_MoveSibling7, OPC_RecordChild0, OPC_RecordChild1, OPC_RecordChild2, OPC_RecordChild3, OPC_RecordChild4, OPC_RecordChild5, OPC_RecordChild6, OPC_RecordChild7, OPC_RecordMemRef, OPC_RecordNode, OPC_Scope, OPC_SwitchOpcode, OPC_SwitchType, OPFL_Chain, OPFL_GlueInput, OPFL_GlueOutput, OPFL_MemRefs, OPFL_None, OPFL_VariadicInfo, OptLevel, llvm::ISD::PATCHPOINT, llvm::ISD::POISON, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::ISD::PSEUDO_PROBE, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::READ_REGISTER, llvm::ISD::Register, llvm::ISD::RegisterMask, llvm::ISD::RELOC_NONE, ReplaceUses(), llvm::SmallVectorImpl< T >::resize(), RunSDNodeXForm(), llvm::SDNode::setNodeId(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ISD::STACKMAP, llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstant, llvm::ISD::TargetConstantFP, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetFrameIndex, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetJumpTable, TII, TLI, llvm::ISD::TokenFactor, llvm::ISD::UNDEF, llvm::SDNode::use_empty(), llvm::SDNode::uses(), and llvm::ISD::WRITE_REGISTER.
SelectInlineAsmMemoryOperand()
virtual bool llvm::SelectionDAGISel::SelectInlineAsmMemoryOperand (const SDValue & Op, InlineAsm::ConstraintCode ConstraintID, std::vector< SDValue > & OutOps) inline virtual
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
If this does not match or is not implemented, return true. The resultant operands (which will appear in the machine instruction) should be added to the OutOps vector.
Reimplemented in llvm::HexagonDAGToDAGISel, llvm::LoongArchDAGToDAGISel, llvm::NVPTXDAGToDAGISel, and llvm::RISCVDAGToDAGISel.
Definition at line 117 of file SelectionDAGISel.h.
Referenced by SelectInlineAsmMemoryOperands().
SelectInlineAsmMemoryOperands()
void SelectionDAGISel::SelectInlineAsmMemoryOperands (std::vector< SDValue > & Ops, const SDLoc & DL) protected
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen.
Others should not call it.
Definition at line 2299 of file SelectionDAGISel.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::append_range(), assert(), CurDAG, DL, llvm::InlineAsm::Func, getValueType(), llvm::InlineAsm::Mem, llvm::InlineAsm::Op_AsmString, llvm::InlineAsm::Op_ExtraInfo, llvm::InlineAsm::Op_FirstOperand, llvm::InlineAsm::Op_InputChain, llvm::InlineAsm::Op_MDNode, llvm::report_fatal_error(), and SelectInlineAsmMemoryOperand().
shouldOptForSize()
bool llvm::SelectionDAGISel::shouldOptForSize (const MachineFunction * MF) const inline protected
Definition at line 398 of file SelectionDAGISel.h.
References CurDAG, and MF.
Member Data Documentation
AC
AssumptionCache* llvm::SelectionDAGISel::AC = nullptr
Definition at line 58 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), initializeAnalysisResults(), and runOnMachineFunction().
BatchAA
std::optional<BatchAAResults> llvm::SelectionDAGISel::BatchAA mutable
Definition at line 57 of file SelectionDAGISel.h.
Referenced by getBatchAA(), initializeAnalysisResults(), and initializeAnalysisResults().
CurDAG
SelectionDAG* llvm::SelectionDAGISel::CurDAG
Definition at line 55 of file SelectionDAGISel.h.
Referenced by llvm::RISCVDAGToDAGISel::addVectorLoadStoreOperands(), llvm::RISCVDAGToDAGISel::areOffsetsWithinAlignment(), CheckAndMask(), CheckOrMask(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::HexagonDAGToDAGISel::FastFDiv(), llvm::HexagonDAGToDAGISel::FDiv(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::HexagonDAGToDAGISel::HvxSelector, initializeAnalysisResults(), initializeAnalysisResults(), IsPredicateKnownToFail(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), llvm::AMDGPUDAGToDAGISel::matchLoadD16FromBuildVector(), mayRaiseFPException(), llvm::RISCVDAGToDAGISel::orDisjoint(), llvm::AMDGPUDAGToDAGISel::PostprocessISelDAG(), llvm::RISCVDAGToDAGISel::PostprocessISelDAG(), llvm::AMDGPUDAGToDAGISel::PreprocessISelDAG(), llvm::HexagonDAGToDAGISel::PreprocessISelDAG(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), ReplaceNode(), ReplaceUses(), ReplaceUses(), ReplaceUses(), runOnMachineFunction(), llvm::AMDGPUDAGToDAGISel::Select(), llvm::RISCVDAGToDAGISel::Select(), llvm::LoongArchDAGToDAGISel::SelectAddrConstant(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::RISCVDAGToDAGISel::SelectAddrFrameIndex(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::LoongArchDAGToDAGISel::SelectAddrRegImm12(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm9(), llvm::RISCVDAGToDAGISel::SelectAddrRegImmLsb00000(), llvm::RISCVDAGToDAGISel::SelectAddrRegRegScale(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectAnyImmediate(), llvm::HexagonDAGToDAGISel::SelectAnyInt(), llvm::LoongArchDAGToDAGISel::SelectBaseAddr(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::AMDGPUDAGToDAGISel::SelectBuildVector(), SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectExtractSubvector(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::HexagonDAGToDAGISel::SelectGlobalAddress(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::LoongArchDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::NVPTXDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::RISCVDAGToDAGISel::SelectInlineAsmMemoryOperand(), SelectInlineAsmMemoryOperands(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWChain(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), llvm::RISCVDAGToDAGISel::selectInvLogicImm(), SelectionDAGISel(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::RISCVDAGToDAGISel::selectRVVSimm5(), llvm::RISCVDAGToDAGISel::selectScalarFPAsInt(), llvm::RISCVDAGToDAGISel::selectSETCC(), llvm::RISCVDAGToDAGISel::selectSExtBits(), llvm::LoongArchDAGToDAGISel::selectSExti32(), llvm::RISCVDAGToDAGISel::selectSF_VC_X_SE(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::RISCVDAGToDAGISel::selectShiftMask(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::RISCVDAGToDAGISel::selectSHXADD_UWOp(), llvm::RISCVDAGToDAGISel::selectSHXADDOp(), llvm::RISCVDAGToDAGISel::selectSimm5Shl2(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::AMDGPUDAGToDAGISel::SelectVectorShuffle(), llvm::RISCVDAGToDAGISel::selectVLOp(), llvm::RISCVDAGToDAGISel::selectVLSEG(), llvm::RISCVDAGToDAGISel::selectVLSEGFF(), llvm::RISCVDAGToDAGISel::selectVLXSEG(), llvm::RISCVDAGToDAGISel::selectVSETVLI(), llvm::LoongArchDAGToDAGISel::selectVSplatImm(), llvm::RISCVDAGToDAGISel::selectVSplatSimm5(), llvm::RISCVDAGToDAGISel::selectVSplatSimm5Plus1(), llvm::RISCVDAGToDAGISel::selectVSplatSimm5Plus1NoDec(), llvm::RISCVDAGToDAGISel::selectVSplatSimm5Plus1NonZero(), llvm::RISCVDAGToDAGISel::selectVSplatUimm(), llvm::LoongArchDAGToDAGISel::selectVSplatUimmInvPow2(), llvm::LoongArchDAGToDAGISel::selectVSplatUimmPow2(), llvm::RISCVDAGToDAGISel::selectVSSEG(), llvm::RISCVDAGToDAGISel::selectVSXSEG(), llvm::RISCVDAGToDAGISel::selectXSfmmVSET(), llvm::RISCVDAGToDAGISel::selectZExtBits(), llvm::LoongArchDAGToDAGISel::selectZExti32(), shouldOptForSize(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), llvm::RISCVDAGToDAGISel::tryIndexedLoad(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), llvm::RISCVDAGToDAGISel::tryShrinkShlLogicImm(), llvm::RISCVDAGToDAGISel::trySignedBitfieldExtract(), llvm::RISCVDAGToDAGISel::trySignedBitfieldInsertInSign(), llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldExtract(), llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldInsertInZero(), and ~SelectionDAGISel().
DAGSize
unsigned llvm::SelectionDAGISel::DAGSize = 0 protected
DAGSize - Size of DAG being instruction selected.
Definition at line 352 of file SelectionDAGISel.h.
ElidedArgCopyInstrs
SmallPtrSet<const Instruction *, 4> llvm::SelectionDAGISel::ElidedArgCopyInstrs
Definition at line 66 of file SelectionDAGISel.h.
FastISelFailed
bool llvm::SelectionDAGISel::FastISelFailed
Definition at line 65 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
FuncInfo
std::unique_ptr<FunctionLoweringInfo> llvm::SelectionDAGISel::FuncInfo
Definition at line 50 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), initializeAnalysisResults(), runOnMachineFunction(), and SelectionDAGISel().
FuncName
StringRef llvm::SelectionDAGISel::FuncName
Definition at line 78 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), initializeAnalysisResults(), and runOnMachineFunction().
GFI
GCFunctionInfo* llvm::SelectionDAGISel::GFI = nullptr
Definition at line 59 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), initializeAnalysisResults(), and runOnMachineFunction().
LibInfo
const TargetLibraryInfo* llvm::SelectionDAGISel::LibInfo
Definition at line 48 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), initializeAnalysisResults(), and runOnMachineFunction().
MatchFilterFuncName
bool llvm::SelectionDAGISel::MatchFilterFuncName = false
True if the function currently processing is in the function printing list (i.e.
-filter-print-funcs). This is primarily used by ISEL_DUMP, which spans in multiple member functions. Storing the filter result here so that we only need to do the filtering once.
Definition at line 77 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), and initializeAnalysisResults().
MF
MachineFunction* llvm::SelectionDAGISel::MF
Definition at line 52 of file SelectionDAGISel.h.
Referenced by llvm::AMDGPUDAGToDAGISel::AMDGPUDAGToDAGISel(), llvm::createBURRListDAGScheduler(), llvm::createDAGLinearizer(), llvm::createDefaultScheduler(), llvm::createFastDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::createVLIWDAGScheduler(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), initializeAnalysisResults(), initializeAnalysisResults(), isOrEquivalentToAdd(), llvm::NVPTXDAGToDAGISel::NVPTXDAGToDAGISel(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::AMDGPUDAGToDAGISel::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::runOnMachineFunction(), llvm::LoongArchDAGToDAGISel::runOnMachineFunction(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), llvm::RISCVDAGToDAGISel::runOnMachineFunction(), runOnMachineFunction(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), and shouldOptForSize().
MMI
MachineModuleInfo* llvm::SelectionDAGISel::MMI
Definition at line 53 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), and initializeAnalysisResults().
OptLevel
CodeGenOptLevel llvm::SelectionDAGISel::OptLevel
Definition at line 62 of file SelectionDAGISel.h.
Referenced by llvm::AMDGPUDAGToDAGISel::AMDGPUDAGToDAGISel(), llvm::AMDGPUDAGToDAGISel::AMDGPUDAGToDAGISel(), llvm::HexagonDAGToDAGISel::HexagonDAGToDAGISel(), initializeAnalysisResults(), initializeAnalysisResults(), IsLegalToFold(), IsProfitableToFold(), llvm::LoongArchDAGToDAGISel::LoongArchDAGToDAGISel(), llvm::NVPTXDAGToDAGISel::NVPTXDAGToDAGISel(), llvm::NVPTXDAGToDAGISel::NVPTXDAGToDAGISel(), llvm::RISCVDAGToDAGISel::RISCVDAGToDAGISel(), runOnMachineFunction(), SelectCodeCommon(), and SelectionDAGISel().
ORE
std::unique_ptr<OptimizationRemarkEmitter> llvm::SelectionDAGISel::ORE
Current optimization remark emitter.
Used to report things like combines and FastISel failures.
Definition at line 70 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), and initializeAnalysisResults().
RegInfo
MachineRegisterInfo* llvm::SelectionDAGISel::RegInfo
Definition at line 54 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), initializeAnalysisResults(), and runOnMachineFunction().
RuntimeLibCallInfo
const RTLIB::RuntimeLibcallsInfo* llvm::SelectionDAGISel::RuntimeLibCallInfo
Definition at line 49 of file SelectionDAGISel.h.
SDB
std::unique_ptr<SelectionDAGBuilder> llvm::SelectionDAGISel::SDB
Definition at line 56 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), and SelectionDAGISel().
SP
SSPLayoutInfo* llvm::SelectionDAGISel::SP = nullptr
Definition at line 60 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), and initializeAnalysisResults().
SwiftError
std::unique_ptr<SwiftErrorValueTracking> llvm::SelectionDAGISel::SwiftError
Definition at line 51 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), and SelectionDAGISel().
TII
const TargetInstrInfo* llvm::SelectionDAGISel::TII
Definition at line 63 of file SelectionDAGISel.h.
Referenced by llvm::RISCVDAGToDAGISel::hasAllNBitUsers(), initializeAnalysisResults(), initializeAnalysisResults(), mayRaiseFPException(), runOnMachineFunction(), and SelectCodeCommon().
TLI
const TargetLowering* llvm::SelectionDAGISel::TLI
Definition at line 64 of file SelectionDAGISel.h.
Referenced by llvm::createDefaultScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), getTargetLowering(), initializeAnalysisResults(), initializeAnalysisResults(), IsPredicateKnownToFail(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), runOnMachineFunction(), llvm::RISCVDAGToDAGISel::Select(), and SelectCodeCommon().
TM
TargetMachine& llvm::SelectionDAGISel::TM
Definition at line 47 of file SelectionDAGISel.h.
Referenced by llvm::AMDGPUDAGToDAGISel::AMDGPUDAGToDAGISel(), llvm::AMDGPUDAGToDAGISel::AMDGPUDAGToDAGISel(), initializeAnalysisResults(), initializeAnalysisResults(), llvm::LoongArchDAGToDAGISel::LoongArchDAGToDAGISel(), llvm::Mips16DAGToDAGISel::Mips16DAGToDAGISel(), llvm::MipsDAGToDAGISel::MipsDAGToDAGISel(), llvm::MipsSEDAGToDAGISel::MipsSEDAGToDAGISel(), llvm::RISCVDAGToDAGISel::Select(), and SelectionDAGISel().
TTI
const TargetTransformInfo* llvm::SelectionDAGISel::TTI = nullptr
Definition at line 61 of file SelectionDAGISel.h.
Referenced by initializeAnalysisResults(), initializeAnalysisResults(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAGISel.h
lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp