LLVM: llvm::TGTimer Class Reference
llvm::TGTimer Class Reference
#include "llvm/TableGen/TGTimer.h"
Public Member Functions
TGTimer ()=default
~TGTimer ()=default
void startPhaseTiming ()
Start phase timing; called if the –time-phases option is specified.
void startTimer (StringRef Name)
Start timing a phase. Automatically stops any previous phase timer.
void stopTimer ()
Stop timing a phase.
void startBackendTimer (StringRef Name)
Start timing the overall backend.
void stopBackendTimer ()
Stop timing the overall backend.
void stopPhaseTiming ()
Stop phase timing and print the report.
Detailed Description
Definition at line 24 of file TGTimer.h.
Constructor & Destructor Documentation
TGTimer()
llvm::TGTimer::TGTimer () default
~TGTimer()
llvm::TGTimer::~TGTimer () default
Member Function Documentation
startBackendTimer()
void TGTimer::startBackendTimer (StringRef Name)
Start timing the overall backend.
If the backend itself starts a timer, then this timer is cleared.
Definition at line 41 of file TGTimer.cpp.
References startTimer().
startPhaseTiming()
void llvm::TGTimer::startPhaseTiming () inline
Start phase timing; called if the –time-phases option is specified.
Definition at line 35 of file TGTimer.h.
startTimer()
void TGTimer::startTimer (StringRef Name)
Start timing a phase. Automatically stops any previous phase timer.
Definition at line 18 of file TGTimer.cpp.
Referenced by startBackendTimer().
stopBackendTimer()
void TGTimer::stopBackendTimer ()
Stop timing the overall backend.
Definition at line 49 of file TGTimer.cpp.
References stopTimer().
stopPhaseTiming()
void llvm::TGTimer::stopPhaseTiming () inline
Stop phase timing and print the report.
Definition at line 54 of file TGTimer.h.
stopTimer()
void TGTimer::stopTimer ()
Stop timing a phase.
Definition at line 33 of file TGTimer.cpp.
References assert().
Referenced by stopBackendTimer().
The documentation for this class was generated from the following files:
include/llvm/TableGen/TGTimer.h
lib/TableGen/TGTimer.cpp