LLVM: llvm::DWARFDebugPubTable Class Reference
llvm::DWARFDebugPubTable Class Reference
Represents structure for holding and parsing .debug_pub* tables.
#include "llvm/DebugInfo/DWARF/DWARFDebugPubTable.h"
Classes
struct Entry
struct Set
Each table consists of sets of variable length entries.
Public Member Functions
DWARFDebugPubTable ()=default
LLVM_ABI void extract (DWARFDataExtractor Data, bool GnuStyle, function_ref< void(Error)> RecoverableErrorHandler)
LLVM_ABI void dump (raw_ostream &OS) const
ArrayRef< Set > getData ()
Detailed Description
Represents structure for holding and parsing .debug_pub* tables.
Definition at line 27 of file DWARFDebugPubTable.h.
Constructor & Destructor Documentation
DWARFDebugPubTable()
llvm::DWARFDebugPubTable::DWARFDebugPubTable () default
References llvm::Data, and LLVM_ABI.
Member Function Documentation
dump()
void DWARFDebugPubTable::dump (raw_ostream & OS) const
Definition at line 93 of file DWARFDebugPubTable.cpp.
References llvm::StringRef::data(), llvm::format(), llvm::dwarf::FormatString(), llvm::dwarf::GDBIndexEntryKindString(), llvm::dwarf::GDBIndexEntryLinkageString(), and llvm::dwarf::getDwarfOffsetByteSize().
Referenced by dumpPubTableSection().
extract()
void DWARFDebugPubTable::extract (DWARFDataExtractor Data, bool GnuStyle, function_ref< void(Error)> RecoverableErrorHandler)
Definition at line 22 of file DWARFDebugPubTable.cpp.
References llvm::CallingConv::C, llvm::createStringError(), llvm::Data, llvm::DWARFDebugPubTable::Set::Entries, llvm::DWARFDebugPubTable::Set::Format, llvm::DataExtractor::getCStrRef(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::DWARFDataExtractorBase< Relocator >::getRelocatedValue(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getUnsigned(), llvm::invalid_argument, llvm::DWARFDebugPubTable::Set::Length, llvm::DWARFDebugPubTable::Set::Offset, llvm::Offset, llvm::DWARFDebugPubTable::Set::Size, llvm::toString(), and llvm::DWARFDebugPubTable::Set::Version.
Referenced by dumpPubTableSection().
getData()
ArrayRef< Set > llvm::DWARFDebugPubTable::getData () inline
Definition at line 83 of file DWARFDebugPubTable.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugPubTable.h
lib/DebugInfo/DWARF/DWARFDebugPubTable.cpp