LLVM: llvm::SPIRVIRMapping Class Reference
llvm::SPIRVIRMapping Class Reference
#include "Target/SPIRV/SPIRVIRMapping.h"
Public Member Functions
bool add (SPIRV::IRHandle Handle, const MachineInstr *MI)
bool erase (const MachineInstr *MI)
const MachineInstr * findMI (SPIRV::IRHandle Handle, const MachineFunction *MF)
Register find (SPIRV::IRHandle Handle, const MachineFunction *MF)
bool add (const Type *PointeeTy, unsigned AddressSpace, const MachineInstr *MI)
Register find (const Type *PointeeTy, unsigned AddressSpace, const MachineFunction *MF)
const MachineInstr * findMI (const Type *PointeeTy, unsigned AddressSpace, const MachineFunction *MF)
bool add (const Value *V, const MachineInstr *MI)
bool add (const Type *T, bool RequiresExplicitLayout, const MachineInstr *MI)
bool add (const MachineInstr *Obj, const MachineInstr *MI)
Register find (const Value *V, const MachineFunction *MF)
Register find (const Type *T, bool RequiresExplicitLayout, const MachineFunction *MF)
Register find (const MachineInstr *MI, const MachineFunction *MF)
const MachineInstr * findMI (const Value *Obj, const MachineFunction *MF)
const MachineInstr * findMI (const Type *T, bool RequiresExplicitLayout, const MachineFunction *MF)
const MachineInstr * findMI (const MachineInstr *Obj, const MachineFunction *MF)
Detailed Description
Definition at line 184 of file SPIRVIRMapping.h.
Member Function Documentation
add() [1/5]
bool llvm::SPIRVIRMapping::add (const MachineInstr * Obj, const MachineInstr * MI) inline
Definition at line 265 of file SPIRVIRMapping.h.
References add(), llvm::SPIRV::handle(), and MI.
add() [2/5]
bool llvm::SPIRVIRMapping::add (const Type * PointeeTy, unsigned AddressSpace, const MachineInstr * MI) inline
Definition at line 241 of file SPIRVIRMapping.h.
References add(), llvm::SPIRV::irhandle_pointee(), and MI.
add() [3/5]
bool llvm::SPIRVIRMapping::add (const Type * T, bool RequiresExplicitLayout, const MachineInstr * MI) inline
Definition at line 258 of file SPIRVIRMapping.h.
References add(), llvm::SPIRV::handle(), llvm::SPIRV::irhandle_explict_layout_type(), MI, T, and llvm::SPIRV::type_has_layout_decoration().
add() [4/5]
bool llvm::SPIRVIRMapping::add (const Value * V, const MachineInstr * MI) inline
Definition at line 254 of file SPIRVIRMapping.h.
References add(), llvm::SPIRV::handle(), and MI.
add() [5/5]
bool llvm::SPIRVIRMapping::add (SPIRV::IRHandle Handle, const MachineInstr * MI) inline
Definition at line 189 of file SPIRVIRMapping.h.
References assert(), llvm::SPIRV::getIRHandleMF(), llvm::SPIRV::getMIKey(), and MI.
Referenced by add(), add(), add(), add(), addConstantsToTrack(), llvm::SPIRVGlobalRegistry::buildConstantFP(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::SPIRVGlobalRegistry::createConstFP(), llvm::SPIRVGlobalRegistry::createConstInt(), generateAssignInstrs(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), llvm::SPIRVGlobalRegistry::getOrCreateLayoutType(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeFunctionWithArgs(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampler(), llvm::SPIRVGlobalRegistry::getOrCreatePaddingType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::SPIRVGlobalRegistry::getOrCreateUnknownType(), llvm::SPIRVGlobalRegistry::getOrCreateVulkanBufferType(), llvm::SPIRVGlobalRegistry::getOrCreateVulkanPushConstantType(), and insertInlineAsmProcess().
erase()
bool llvm::SPIRVIRMapping::erase (const MachineInstr * MI) inline
Definition at line 211 of file SPIRVIRMapping.h.
References MI.
Referenced by findMI(), and llvm::SPIRVGlobalRegistry::invalidateMachineInstr().
find() [1/5]
Register llvm::SPIRVIRMapping::find (const MachineInstr * MI, const MachineFunction * MF) inline
Definition at line 280 of file SPIRVIRMapping.h.
References find(), llvm::SPIRV::handle(), and MI.
find() [2/5]
Register llvm::SPIRVIRMapping::find (const Type * PointeeTy, unsigned AddressSpace, const MachineFunction * MF) inline
Definition at line 245 of file SPIRVIRMapping.h.
References find(), and llvm::SPIRV::irhandle_pointee().
find() [3/5]
Register llvm::SPIRVIRMapping::find (const Type * T, bool RequiresExplicitLayout, const MachineFunction * MF) inline
Definition at line 273 of file SPIRVIRMapping.h.
References find(), llvm::SPIRV::handle(), llvm::SPIRV::irhandle_explict_layout_type(), T, and llvm::SPIRV::type_has_layout_decoration().
find() [4/5]
Register llvm::SPIRVIRMapping::find (const Value * V, const MachineFunction * MF) inline
Definition at line 269 of file SPIRVIRMapping.h.
References find(), and llvm::SPIRV::handle().
find() [5/5]
Register llvm::SPIRVIRMapping::find (SPIRV::IRHandle Handle, const MachineFunction * MF) inline
Definition at line 235 of file SPIRVIRMapping.h.
References findMI(), MI, and Register.
Referenced by addConstantsToTrack(), llvm::SPIRVGlobalRegistry::buildConstantFP(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), find(), find(), find(), find(), generateAssignInstrs(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), and llvm::SPIRVGlobalRegistry::getOrCreateUndef().
findMI() [1/5]
const MachineInstr * llvm::SPIRVIRMapping::findMI (const MachineInstr * Obj, const MachineFunction * MF) inline
Definition at line 295 of file SPIRVIRMapping.h.
References findMI(), and llvm::SPIRV::handle().
findMI() [2/5]
const MachineInstr * llvm::SPIRVIRMapping::findMI (const Type * PointeeTy, unsigned AddressSpace, const MachineFunction * MF) inline
Definition at line 249 of file SPIRVIRMapping.h.
References findMI(), and llvm::SPIRV::irhandle_pointee().
findMI() [3/5]
const MachineInstr * llvm::SPIRVIRMapping::findMI (const Type * T, bool RequiresExplicitLayout, const MachineFunction * MF) inline
Definition at line 288 of file SPIRVIRMapping.h.
References findMI(), llvm::SPIRV::handle(), llvm::SPIRV::irhandle_explict_layout_type(), T, and llvm::SPIRV::type_has_layout_decoration().
findMI() [4/5]
const MachineInstr * llvm::SPIRVIRMapping::findMI (const Value * Obj, const MachineFunction * MF) inline
Definition at line 284 of file SPIRVIRMapping.h.
References findMI(), and llvm::SPIRV::handle().
findMI() [5/5]
const MachineInstr * llvm::SPIRVIRMapping::findMI (SPIRV::IRHandle Handle, const MachineFunction * MF) inline
Definition at line 219 of file SPIRVIRMapping.h.
References assert(), erase(), llvm::SPIRV::getIRHandleMF(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getVRegDef(), MI, Reg, and llvm::SPIRV::to_hash().
Referenced by find(), findMI(), findMI(), findMI(), findMI(), llvm::SPIRVGlobalRegistry::getOrCreateConstFP(), llvm::SPIRVGlobalRegistry::getOrCreateConstInt(), llvm::SPIRVGlobalRegistry::getOrCreateLayoutType(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeFunctionWithArgs(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampler(), llvm::SPIRVGlobalRegistry::getOrCreatePaddingType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUnknownType(), llvm::SPIRVGlobalRegistry::getOrCreateVulkanBufferType(), and llvm::SPIRVGlobalRegistry::getOrCreateVulkanPushConstantType().
The documentation for this class was generated from the following file:
lib/Target/SPIRV/SPIRVIRMapping.h