LLVM: llvm::VPBuilder Class Reference
llvm::VPBuilder Class Reference
VPlan-based builder utility analogous to IRBuilder.
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Classes
class VPInsertPoint
InsertPoint - A saved insertion point.
class InsertPointGuard
RAII object that stores the current insertion point and restores it when the object is destroyed.
Public Member Functions
VPBuilder ()=default
VPBuilder (VPBasicBlock *InsertBB)
VPBuilder (VPRecipeBase *InsertPt)
VPBuilder (VPBasicBlock *TheBB, VPBasicBlock::iterator IP)
void clearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
VPBasicBlock * getInsertBlock () const
VPBasicBlock::iterator getInsertPoint () const
void restoreIP (VPInsertPoint IP)
Sets the current insert point to a previously-saved location.
void setInsertPoint (VPBasicBlock *TheBB)
This specifies that created VPInstructions should be appended to the end of the specified block.
void setInsertPoint (VPBasicBlock *TheBB, VPBasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void setInsertPoint (VPRecipeBase *IP)
This specifies that created instructions should be inserted at the specified point.
void insert (VPRecipeBase *R)
Insert R at the current insertion point.
VPInstruction * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Instruction *Inst=nullptr, const VPIRFlags &Flags={}, const VPIRMetadata &MD={}, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
VPInstruction * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL, const Twine &Name="")
VPInstruction * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, const VPIRFlags &Flags, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Type *ResultTy, const VPIRFlags &Flags={}, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createOverflowingOp (unsigned Opcode, ArrayRef< VPValue * > Operands, VPRecipeWithIRFlags::WrapFlagsTy WrapFlags={false, false}, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createNot (VPValue *Operand, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createAnd (VPValue *LHS, VPValue *RHS, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createOr (VPValue *LHS, VPValue *RHS, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createLogicalAnd (VPValue *LHS, VPValue *RHS, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createSelect (VPValue *Cond, VPValue *TrueVal, VPValue *FalseVal, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="", std::optional< FastMathFlags > FMFs=std::nullopt)
VPInstruction * createICmp (CmpInst::Predicate Pred, VPValue *A, VPValue *B, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
Create a new ICmp VPInstruction with predicate Pred and operands A and B.
VPInstruction * createFCmp (CmpInst::Predicate Pred, VPValue *A, VPValue *B, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
Create a new FCmp VPInstruction with predicate Pred and operands A and B.
VPInstruction * createPtrAdd (VPValue *Ptr, VPValue *Offset, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createNoWrapPtrAdd (VPValue *Ptr, VPValue *Offset, GEPNoWrapFlags GEPFlags, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPInstruction * createWidePtrAdd (VPValue *Ptr, VPValue *Offset, DebugLoc DL=DebugLoc::getUnknown(), const Twine &Name="")
VPPhi * createScalarPhi (ArrayRef< VPValue * > IncomingValues, DebugLoc DL, const Twine &Name="")
VPValue * createElementCount (Type *Ty, ElementCount EC)
VPDerivedIVRecipe * createDerivedIV (InductionDescriptor::InductionKind Kind, FPMathOperator *FPBinOp, VPIRValue *Start, VPValue *Current, VPValue *Step, const Twine &Name="")
Convert the input value Current to the corresponding value of an induction with Start and Step values, using Start + Current * Step.
VPInstruction * createScalarCast (Instruction::CastOps Opcode, VPValue *Op, Type *ResultTy, DebugLoc DL, const VPIRFlags &Flags={}, const VPIRMetadata &Metadata={})
VPValue * createScalarZExtOrTrunc (VPValue *Op, Type *ResultTy, Type *SrcTy, DebugLoc DL)
VPWidenCastRecipe * createWidenCast (Instruction::CastOps Opcode, VPValue *Op, Type *ResultTy)
VPScalarIVStepsRecipe * createScalarIVSteps (Instruction::BinaryOps InductionOpcode, FPMathOperator *FPBinOp, VPValue *IV, VPValue *Step, VPValue *VF, DebugLoc DL)
VPExpandSCEVRecipe * createExpandSCEV (const SCEV *Expr)
Static Public Member Functions
static VPBuilder getToInsertAfter (VPRecipeBase *R)
Create a VPBuilder to insert after R.
Detailed Description
VPlan-based builder utility analogous to IRBuilder.
Definition at line 54 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
VPBuilder() [1/4]
llvm::VPBuilder::VPBuilder () default
Referenced by getToInsertAfter(), and llvm::VPBuilder::InsertPointGuard::InsertPointGuard().
VPBuilder() [2/4]
llvm::VPBuilder::VPBuilder (VPBasicBlock * InsertBB) inline
Definition at line 75 of file LoopVectorizationPlanner.h.
References setInsertPoint().
VPBuilder() [3/4]
llvm::VPBuilder::VPBuilder (VPRecipeBase * InsertPt) inline
Definition at line 76 of file LoopVectorizationPlanner.h.
References setInsertPoint().
VPBuilder() [4/4]
llvm::VPBuilder::VPBuilder (VPBasicBlock * TheBB, VPBasicBlock::iterator IP) inline
Definition at line 77 of file LoopVectorizationPlanner.h.
References setInsertPoint().
Member Function Documentation
clearInsertionPoint()
void llvm::VPBuilder::clearInsertionPoint () inline
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 83 of file LoopVectorizationPlanner.h.
Referenced by restoreIP().
createAnd()
VPInstruction * llvm::VPBuilder::createAnd (VPValue * LHS, VPValue * RHS, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 198 of file LoopVectorizationPlanner.h.
References DL, llvm::DebugLoc::getUnknown(), LHS, and RHS.
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions().
createDerivedIV()
VPDerivedIVRecipe * llvm::VPBuilder::createDerivedIV (InductionDescriptor::InductionKind Kind, FPMathOperator * FPBinOp, VPIRValue * Start, VPValue * Current, VPValue * Step, const Twine & Name = "") inline
Convert the input value Current to the corresponding value of an induction with Start and Step values, using Start + Current * Step.
Definition at line 298 of file LoopVectorizationPlanner.h.
Referenced by tryToComputeEndValueForInduction().
createElementCount()
VPValue * llvm::VPBuilder::createElementCount (Type * Ty, ElementCount EC) inline
Definition at line 282 of file LoopVectorizationPlanner.h.
References createNaryOp(), createOverflowingOp(), llvm::VPlan::getConstantInt(), getInsertBlock(), llvm::VPBlockBase::getPlan(), and llvm::VPInstruction::VScale.
Referenced by llvm::VPlanTransforms::narrowInterleaveGroups().
createExpandSCEV()
VPExpandSCEVRecipe * llvm::VPBuilder::createExpandSCEV (const SCEV * Expr) inline
Definition at line 345 of file LoopVectorizationPlanner.h.
createFCmp()
VPInstruction * llvm::VPBuilder::createFCmp (CmpInst::Predicate Pred, VPValue * A, VPValue * B, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Create a new FCmp VPInstruction with predicate Pred and operands A and B.
Definition at line 244 of file LoopVectorizationPlanner.h.
References A(), assert(), B(), DL, llvm::CmpInst::FIRST_FCMP_PREDICATE, llvm::DebugLoc::getUnknown(), and llvm::CmpInst::LAST_FCMP_PREDICATE.
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions().
createICmp()
VPInstruction * llvm::VPBuilder::createICmp (CmpInst::Predicate Pred, VPValue * A, VPValue * B, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Create a new ICmp VPInstruction with predicate Pred and operands A and B.
Definition at line 233 of file LoopVectorizationPlanner.h.
References A(), assert(), B(), DL, llvm::CmpInst::FIRST_ICMP_PREDICATE, llvm::DebugLoc::getUnknown(), and llvm::CmpInst::LAST_ICMP_PREDICATE.
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions().
createLogicalAnd()
VPInstruction * llvm::VPBuilder::createLogicalAnd (VPValue * LHS, VPValue * RHS, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 214 of file LoopVectorizationPlanner.h.
References createNaryOp(), DL, llvm::DebugLoc::getUnknown(), LHS, llvm::VPInstruction::LogicalAnd, and RHS.
createNaryOp() [1/4]
VPInstruction * llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, const VPIRFlags & Flags, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 168 of file LoopVectorizationPlanner.h.
References DL, and llvm::DebugLoc::getUnknown().
createNaryOp() [2/4]
VPInstruction * llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL, const Twine & Name = "") inline
Definition at line 164 of file LoopVectorizationPlanner.h.
References DL.
createNaryOp() [3/4]
VPInstruction * llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Instruction * Inst = nullptr, const VPIRFlags & Flags = {}, const VPIRMetadata & MD = {}, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
Definition at line 153 of file LoopVectorizationPlanner.h.
Referenced by llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::attachCheckBlock(), createElementCount(), createLogicalAnd(), createSelect(), llvm::VPlanTransforms::expandBranchOnTwoConds(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleUncountableEarlyExit(), preparePlanForMainVectorLoop(), simplifyBranchConditionForVFAndUF(), and llvm::VPlanTransforms::updateScalarResumePhis().
createNaryOp() [4/4]
VPInstruction * llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Type * ResultTy, const VPIRFlags & Flags = {}, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 176 of file LoopVectorizationPlanner.h.
createNot()
VPInstruction * llvm::VPBuilder::createNot (VPValue * Operand, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 192 of file LoopVectorizationPlanner.h.
References DL, llvm::DebugLoc::getUnknown(), and llvm::VPInstruction::Not.
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions().
createNoWrapPtrAdd()
VPInstruction * llvm::VPBuilder::createNoWrapPtrAdd (VPValue * Ptr, VPValue * Offset, GEPNoWrapFlags GEPFlags, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 261 of file LoopVectorizationPlanner.h.
References DL, llvm::DebugLoc::getUnknown(), llvm::Offset, and llvm::VPInstruction::PtrAdd.
createOr()
VPInstruction * llvm::VPBuilder::createOr (VPValue * LHS, VPValue * RHS, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 205 of file LoopVectorizationPlanner.h.
References DL, llvm::DebugLoc::getUnknown(), LHS, and RHS.
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions().
createOverflowingOp()
VPInstruction * llvm::VPBuilder::createOverflowingOp (unsigned Opcode, ArrayRef< VPValue * > Operands, VPRecipeWithIRFlags::WrapFlagsTy WrapFlags = {false, false}, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 184 of file LoopVectorizationPlanner.h.
Referenced by createElementCount(), and llvm::VPlanTransforms::narrowInterleaveGroups().
createPtrAdd()
VPInstruction * llvm::VPBuilder::createPtrAdd (VPValue * Ptr, VPValue * Offset, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 253 of file LoopVectorizationPlanner.h.
References DL, llvm::DebugLoc::getUnknown(), llvm::GEPNoWrapFlags::none(), llvm::Offset, and llvm::VPInstruction::PtrAdd.
createScalarCast()
VPInstruction * llvm::VPBuilder::createScalarCast (Instruction::CastOps Opcode, VPValue * Op, Type * ResultTy, DebugLoc DL, const VPIRFlags & Flags = {}, const VPIRMetadata & Metadata = {}) inline
Definition at line 306 of file LoopVectorizationPlanner.h.
References DL.
Referenced by createScalarZExtOrTrunc(), optimizeMaskToEVL(), and tryToComputeEndValueForInduction().
createScalarIVSteps()
VPScalarIVStepsRecipe * llvm::VPBuilder::createScalarIVSteps (Instruction::BinaryOps InductionOpcode, FPMathOperator * FPBinOp, VPValue * IV, VPValue * Step, VPValue * VF, DebugLoc DL) inline
Definition at line 337 of file LoopVectorizationPlanner.h.
References DL, llvm::FPMathOperator::getFastMathFlags(), and IV.
createScalarPhi()
VPPhi * llvm::VPBuilder::createScalarPhi (ArrayRef< VPValue * > IncomingValues, DebugLoc DL, const Twine & Name = "") inline
Definition at line 277 of file LoopVectorizationPlanner.h.
References DL.
Referenced by addInitialSkeleton(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPRegionBlock::dissolveToCFGLoop(), and preparePlanForMainVectorLoop().
createScalarZExtOrTrunc()
VPValue * llvm::VPBuilder::createScalarZExtOrTrunc (VPValue * Op, Type * ResultTy, Type * SrcTy, DebugLoc DL) inline
Definition at line 314 of file LoopVectorizationPlanner.h.
References createScalarCast(), DL, and llvm::Type::getScalarSizeInBits().
Referenced by simplifyKnownEVL().
createSelect()
VPInstruction * llvm::VPBuilder::createSelect (VPValue * Cond, VPValue * TrueVal, VPValue * FalseVal, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "", std::optional< FastMathFlags > FMFs = std::nullopt) inline
Definition at line 221 of file LoopVectorizationPlanner.h.
References Cond, createNaryOp(), DL, and llvm::DebugLoc::getUnknown().
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions().
createWidenCast()
VPWidenCastRecipe * llvm::VPBuilder::createWidenCast (Instruction::CastOps Opcode, VPValue * Op, Type * ResultTy) inline
Definition at line 325 of file LoopVectorizationPlanner.h.
createWidePtrAdd()
VPInstruction * llvm::VPBuilder::createWidePtrAdd (VPValue * Ptr, VPValue * Offset, DebugLoc DL = DebugLoc::getUnknown(), const Twine & Name = "") inline
Definition at line 269 of file LoopVectorizationPlanner.h.
References DL, llvm::DebugLoc::getUnknown(), llvm::GEPNoWrapFlags::none(), llvm::Offset, and llvm::VPInstruction::WidePtrAdd.
getInsertBlock()
VPBasicBlock * llvm::VPBuilder::getInsertBlock () const inline
Definition at line 88 of file LoopVectorizationPlanner.h.
Referenced by createElementCount(), and llvm::VPBuilder::InsertPointGuard::InsertPointGuard().
getInsertPoint()
VPBasicBlock::iterator llvm::VPBuilder::getInsertPoint () const inline
Definition at line 89 of file LoopVectorizationPlanner.h.
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions(), and llvm::VPBuilder::InsertPointGuard::InsertPointGuard().
getToInsertAfter()
VPBuilder llvm::VPBuilder::getToInsertAfter (VPRecipeBase * R) inline static
Create a VPBuilder to insert after R.
Definition at line 92 of file LoopVectorizationPlanner.h.
References B(), and VPBuilder().
Referenced by llvm::VPlanTransforms::addActiveLaneMask().
insert()
void llvm::VPBuilder::insert (VPRecipeBase * R) inline
Insert R at the current insertion point.
Definition at line 149 of file LoopVectorizationPlanner.h.
restoreIP()
void llvm::VPBuilder::restoreIP (VPInsertPoint IP) inline
Sets the current insert point to a previously-saved location.
Definition at line 119 of file LoopVectorizationPlanner.h.
References clearInsertionPoint(), llvm::VPBuilder::VPInsertPoint::getBlock(), llvm::VPBuilder::VPInsertPoint::getPoint(), llvm::VPBuilder::VPInsertPoint::isSet(), and setInsertPoint().
setInsertPoint() [1/3]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB) inline
This specifies that created VPInstructions should be appended to the end of the specified block.
Definition at line 128 of file LoopVectorizationPlanner.h.
References assert(), and llvm::VPBasicBlock::end().
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::handleMaxMinNumReductions(), restoreIP(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), VPBuilder(), VPBuilder(), and VPBuilder().
setInsertPoint() [2/3]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB, VPBasicBlock::iterator IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 136 of file LoopVectorizationPlanner.h.
setInsertPoint() [3/3]
void llvm::VPBuilder::setInsertPoint (VPRecipeBase * IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 143 of file LoopVectorizationPlanner.h.
References llvm::ilist_node_impl< OptionsT >::getIterator(), and llvm::VPRecipeBase::getParent().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h