LLVM: llvm::sys::fs::file_status Class Reference
llvm::sys::fs::file_status Class Reference
Represents the result of a call to sys::fs::status().
#include "llvm/Support/FileSystem.h"
Public Member Functions
file_status ()=default
file_status (file_type Type)
file_status (file_type Type, perms Perms, dev_t Dev, nlink_t Links, ino_t Ino, time_t ATime, uint32_t ATimeNSec, time_t MTime, uint32_t MTimeNSec, uid_t UID, gid_t GID, off_t Size)
LLVM_ABI UniqueID getUniqueID () const
LLVM_ABI uint32_t getLinkCount () const
Public Member Functions inherited from llvm::sys::fs::basic_file_status
basic_file_status ()=default
basic_file_status (file_type Type)
basic_file_status (file_type Type, perms Perms, time_t ATime, uint32_t ATimeNSec, time_t MTime, uint32_t MTimeNSec, uid_t UID, gid_t GID, off_t Size)
file_type type () const
perms permissions () const
LLVM_ABI TimePoint getLastAccessedTime () const
The file access time as reported from the underlying file system.
LLVM_ABI TimePoint getLastModificationTime () const
The file modification time as reported from the underlying file system.
uint32_t getUser () const
uint32_t getGroup () const
uint64_t getSize () const
void type (file_type v)
void permissions (perms p)
Friends
LLVM_ABI friend bool equivalent (file_status A, file_status B)
Do file_status's represent the same thing?
Additional Inherited Members
Protected Attributes inherited from llvm::sys::fs::basic_file_status
time_t fs_st_atime = 0
time_t fs_st_mtime = 0
uint32_t fs_st_atime_nsec = 0
uint32_t fs_st_mtime_nsec = 0
uid_t fs_st_uid = 0
gid_t fs_st_gid = 0
off_t fs_st_size = 0
file_type Type = file_type::status_error
perms Perms = perms_not_known
Detailed Description
Represents the result of a call to sys::fs::status().
Definition at line 222 of file FileSystem.h.
Constructor & Destructor Documentation
file_status() [1/3]
llvm::sys::fs::file_status::file_status () default
Referenced by equivalent.
file_status() [2/3]
llvm::sys::fs::file_status::file_status (file_type Type) inline explicit
Definition at line 238 of file FileSystem.h.
References llvm::sys::fs::basic_file_status::basic_file_status(), and llvm::sys::fs::basic_file_status::Type.
file_status() [3/3]
llvm::sys::fs::file_status::file_status (file_type Type, perms Perms, dev_t Dev, nlink_t Links, ino_t Ino, time_t ATime, uint32_t ATimeNSec, time_t MTime, uint32_t MTimeNSec, uid_t UID, gid_t GID, off_t Size) inline
Definition at line 241 of file FileSystem.h.
References llvm::sys::fs::basic_file_status::basic_file_status(), llvm::sys::fs::basic_file_status::Perms, and llvm::sys::fs::basic_file_status::Type.
Member Function Documentation
getLinkCount()
LLVM_ABI uint32_t llvm::sys::fs::file_status::getLinkCount () const
References LLVM_ABI.
getUniqueID()
LLVM_ABI UniqueID llvm::sys::fs::file_status::getUniqueID () const
References LLVM_ABI.
Friends And Related Symbol Documentation
equivalent
LLVM_ABI friend bool equivalent (file_status A, file_status B) friend
Do file_status's represent the same thing?
Parameters
A Input file_status.
B Input file_status.
assert(status_known(A) || status_known(B));
Returns
True if A and B both represent the same file system entity, false otherwise.
References A(), B(), file_status(), and LLVM_ABI.
The documentation for this class was generated from the following file:
include/llvm/Support/FileSystem.h