LLVM: llvm::LoongArchInstrInfo Class Reference
llvm::LoongArchInstrInfo Class Reference
#include "Target/LoongArch/LoongArchInstrInfo.h"
Public Member Functions
LoongArchInstrInfo (const LoongArchSubtarget &STI)
const LoongArchRegisterInfo & getRegisterInfo () const
MCInst getNop () const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, Register DstReg, Register SrcReg, bool KillSrc, bool RenamableDest=false, bool RenamableSrc=false) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass *RC, Register VReg, MachineInstr::MIFlag Flags=MachineInstr::NoFlags) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, Register DstReg, int FrameIndex, const TargetRegisterClass *RC, Register VReg, unsigned SubReg=0, MachineInstr::MIFlag Flags=MachineInstr::NoFlags) const override
void movImm (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, Register DstReg, uint64_t Val, MachineInstr::MIFlag Flag=MachineInstr::NoFlags) const
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
bool isAsCheapAsAMove (const MachineInstr &MI) const override
MachineBasicBlock * getBranchDestBlock (const MachineInstr &MI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
bool isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
bool isSafeToMove (const MachineInstr &MI, const MachineBasicBlock *MBB, const MachineFunction &MF) const override
bool isSchedulingBoundary (const MachineInstr &MI, const MachineBasicBlock *MBB, const MachineFunction &MF) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &dl, int *BytesAdded=nullptr) const override
void insertIndirectBranch (MachineBasicBlock &MBB, MachineBasicBlock &NewDestBB, MachineBasicBlock &RestoreBB, const DebugLoc &DL, int64_t BrOffset, RegScavenger *RS) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableBitmaskMachineOperandTargetFlags () const override
bool canFoldIntoAddrMode (const MachineInstr &MemI, Register Reg, const MachineInstr &AddrI, ExtAddrMode &AM) const override
MachineInstr * emitLdStWithAddr (MachineInstr &MemI, const ExtAddrMode &AM) const override
Protected Attributes
const LoongArchSubtarget & STI
Detailed Description
Definition at line 26 of file LoongArchInstrInfo.h.
Constructor & Destructor Documentation
LoongArchInstrInfo()
LoongArchInstrInfo::LoongArchInstrInfo (const LoongArchSubtarget & STI) explicit
Definition at line 29 of file LoongArchInstrInfo.cpp.
References STI.
Member Function Documentation
analyzeBranch()
bool LoongArchInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 299 of file LoongArchInstrInfo.cpp.
References Cond, getBranchDestBlock(), llvm::MachineInstrBundleIterator< Ty, IsReverse >::getReverse(), I, MBB, parseCondBranch(), and TBB.
canFoldIntoAddrMode()
bool LoongArchInstrInfo::canFoldIntoAddrMode (const MachineInstr & MemI, Register Reg, const MachineInstr & AddrI, ExtAddrMode & AM) const override
Definition at line 793 of file LoongArchInstrInfo.cpp.
References llvm::ExtAddrMode::BaseReg, llvm::ExtAddrMode::Basic, llvm::ExtAddrMode::Displacement, llvm::ExtAddrMode::Form, llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isImm(), llvm::isInt(), llvm::MachineOperand::isReg(), llvm::isShiftedInt(), llvm::ExtAddrMode::Scale, llvm::ExtAddrMode::ScaledReg, llvm::SignExtend64(), and STI.
copyPhysReg()
void LoongArchInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, Register DstReg, Register SrcReg, bool KillSrc, bool RenamableDest = false, bool RenamableSrc = false) const override
Definition at line 41 of file LoongArchInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), DL, llvm::get(), llvm::getKillRegState(), llvm_unreachable, MBB, MBBI, and Opc.
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > LoongArchInstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 729 of file LoongArchInstrInfo.cpp.
References llvm::LoongArchII::MO_DIRECT_FLAG_MASK.
emitLdStWithAddr()
MachineInstr * LoongArchInstrInfo::emitLdStWithAddr (MachineInstr & MemI, const ExtAddrMode & AM) const override
Definition at line 906 of file LoongArchInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::ExtAddrMode::BaseReg, llvm::BuildMI(), llvm::RegState::Define, llvm::ExtAddrMode::Displacement, DL, llvm::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getFlags(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineInstr::mayLoad(), MBB, llvm::MachineInstr::memoperands(), llvm::ExtAddrMode::Scale, llvm::ExtAddrMode::ScaledReg, llvm::MachineInstrBuilder::setMemRefs(), and llvm::MachineInstrBuilder::setMIFlags().
getBranchDestBlock()
MachineBasicBlock * LoongArchInstrInfo::getBranchDestBlock (const MachineInstr & MI) const override
Definition at line 280 of file LoongArchInstrInfo.cpp.
References assert(), and MI.
Referenced by analyzeBranch().
getInstSizeInBytes()
unsigned LoongArchInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
Definition at line 234 of file LoongArchInstrInfo.cpp.
References assert(), llvm::TargetMachine::getMCAsmInfo(), llvm::StatepointOpers::getNumPatchBytes(), llvm::MachineFunction::getTarget(), and MI.
Referenced by insertBranch(), and removeBranch().
getNop()
MCInst LoongArchInstrInfo::getNop () const override
Definition at line 34 of file LoongArchInstrInfo.cpp.
References llvm::MCInstBuilder::addImm(), and llvm::MCInstBuilder::addReg().
getRegisterInfo()
const LoongArchRegisterInfo & llvm::LoongArchInstrInfo::getRegisterInfo () const inline
Definition at line 32 of file LoongArchInstrInfo.h.
getSerializableBitmaskMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > LoongArchInstrInfo::getSerializableBitmaskMachineOperandTargetFlags () const override
Definition at line 786 of file LoongArchInstrInfo.cpp.
References llvm::ArrayRef().
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > LoongArchInstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 735 of file LoongArchInstrInfo.cpp.
References llvm::ArrayRef().
insertBranch()
unsigned LoongArchInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & dl, int * BytesAdded = nullptr) const override
Definition at line 580 of file LoongArchInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), Cond, DL, llvm::get(), llvm::getImm(), getInstSizeInBytes(), MBB, MI, and TBB.
insertIndirectBranch()
void LoongArchInstrInfo::insertIndirectBranch (MachineBasicBlock & MBB, MachineBasicBlock & NewDestBB, MachineBasicBlock & RestoreBB, const DebugLoc & DL, int64_t BrOffset, RegScavenger * RS) const override
Definition at line 618 of file LoongArchInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addSym(), assert(), llvm::MachineBasicBlock::back(), llvm::BuildMI(), llvm::MCContext::createNamedTempSymbol(), DL, llvm::MachineBasicBlock::end(), llvm::get(), llvm::LoongArchMachineFunctionInfo::getBranchRelaxationSpillFrameIndex(), llvm::MachineFunction::getContext(), llvm::MachineFunction::getInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), II, llvm::isInt(), llvm::RegState::Kill, loadRegFromStackSlot(), MBB, llvm::LoongArchII::MO_PCADD_HI, llvm::LoongArchII::MO_PCADD_LO, llvm::LoongArchII::MO_PCREL_HI, llvm::LoongArchII::MO_PCREL_LO, MRI, Register, llvm::report_fatal_error(), llvm::MachineOperand::setMBB(), llvm::MachineInstr::setPreInstrSymbol(), STI, storeRegToStackSlot(), and TRI.
isAsCheapAsAMove()
bool LoongArchInstrInfo::isAsCheapAsAMove (const MachineInstr & MI) const override
Definition at line 264 of file LoongArchInstrInfo.cpp.
References MI.
isBranchOffsetInRange()
bool LoongArchInstrInfo::isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
Definition at line 359 of file LoongArchInstrInfo.cpp.
References llvm::isInt(), and llvm_unreachable.
isSafeToMove()
bool LoongArchInstrInfo::isSafeToMove (const MachineInstr & MI, const MachineBasicBlock * MBB, const MachineFunction & MF) const override
Definition at line 382 of file LoongArchInstrInfo.cpp.
References llvm::LoongArchII::getDirectFlags(), llvm::MachineFunction::getSubtarget(), MBB, MI, llvm::LoongArchII::MO_DESC64_PC_HI, llvm::LoongArchII::MO_DESC64_PC_LO, llvm::LoongArchII::MO_DESC_CALL, llvm::LoongArchII::MO_DESC_LD, llvm::LoongArchII::MO_DESC_PC_HI, llvm::LoongArchII::MO_DESC_PC_LO, llvm::LoongArchII::MO_GD_PC_HI, llvm::LoongArchII::MO_GOT_PC64_HI, llvm::LoongArchII::MO_GOT_PC64_LO, llvm::LoongArchII::MO_GOT_PC_HI, llvm::LoongArchII::MO_GOT_PC_LO, llvm::LoongArchII::MO_IE_PC64_HI, llvm::LoongArchII::MO_IE_PC64_LO, llvm::LoongArchII::MO_IE_PC_HI, llvm::LoongArchII::MO_IE_PC_LO, llvm::LoongArchII::MO_LD_PC_HI, llvm::LoongArchII::MO_PCREL64_HI, llvm::LoongArchII::MO_PCREL64_LO, llvm::LoongArchII::MO_PCREL_HI, llvm::LoongArchII::MO_PCREL_LO, and STI.
Referenced by isSchedulingBoundary().
isSchedulingBoundary()
bool LoongArchInstrInfo::isSchedulingBoundary (const MachineInstr & MI, const MachineBasicBlock * MBB, const MachineFunction & MF) const override
Definition at line 535 of file LoongArchInstrInfo.cpp.
References isSafeToMove(), llvm::TargetInstrInfo::isSchedulingBoundary(), MBB, and MI.
loadRegFromStackSlot()
void LoongArchInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, Register DstReg, int FrameIndex, const TargetRegisterClass * RC, Register VReg, unsigned SubReg = 0, MachineInstr::MIFlag Flags = MachineInstr::NoFlags) const override
Definition at line 151 of file LoongArchInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), DL, llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), I, llvm_unreachable, MBB, llvm::MachineMemOperand::MOLoad, and SubReg.
Referenced by insertIndirectBranch().
movImm()
void LoongArchInstrInfo::movImm (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, Register DstReg, uint64_t Val, MachineInstr::MIFlag Flag = MachineInstr::NoFlags) const
Definition at line 189 of file LoongArchInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), DL, llvm::LoongArchMatInt::generateInstSeq(), llvm::get(), llvm::isInt(), llvm::RegState::Kill, MBB, MBBI, llvm::report_fatal_error(), llvm::MachineInstrBuilder::setMIFlag(), and STI.
removeBranch()
unsigned LoongArchInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 547 of file LoongArchInstrInfo.cpp.
References getInstSizeInBytes(), I, and MBB.
reverseBranchCondition()
bool LoongArchInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 721 of file LoongArchInstrInfo.cpp.
References assert(), Cond, llvm::getImm(), and getOppositeBranchOpc().
storeRegToStackSlot()
void LoongArchInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass * RC, Register VReg, MachineInstr::MIFlag Flags = MachineInstr::NoFlags) const override
Definition at line 114 of file LoongArchInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::dwarf_linker::DebugLoc, llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), I, llvm_unreachable, MBB, llvm::MachineMemOperand::MOStore, and TRI.
Referenced by insertIndirectBranch().
Member Data Documentation
STI
const LoongArchSubtarget& llvm::LoongArchInstrInfo::STI protected
Definition at line 109 of file LoongArchInstrInfo.h.
Referenced by canFoldIntoAddrMode(), insertIndirectBranch(), isSafeToMove(), LoongArchInstrInfo(), and movImm().
The documentation for this class was generated from the following files:
lib/Target/LoongArch/LoongArchInstrInfo.h
lib/Target/LoongArch/LoongArchInstrInfo.cpp