LLVM: llvm::vfs::detail::InMemoryDirectory Class Reference
llvm::vfs::detail::InMemoryDirectory Class Reference
Public Types
using const_iterator = decltype(Entries)::const_iterator
Public Member Functions
InMemoryDirectory (Status Stat)
Status getStatus (const Twine &RequestedName) const override
Return the Status for this node.
UniqueID getUniqueID () const
InMemoryNode * getChild (StringRef Name) const
InMemoryNode * addChild (StringRef Name, std::unique_ptr< InMemoryNode > Child)
const_iterator begin () const
const_iterator end () const
std::string toString (unsigned Indent) const override
Public Member Functions inherited from llvm::vfs::detail::InMemoryNode
InMemoryNode (llvm::StringRef FileName, InMemoryNodeKind Kind)
virtual ~InMemoryNode ()=default
StringRef getFileName () const
Get the filename of this node (the name without the directory part).
InMemoryNodeKind getKind () const
Static Public Member Functions
static bool classof (const InMemoryNode *N)
Detailed Description
Definition at line 798 of file VirtualFileSystem.cpp.
Member Typedef Documentation
const_iterator
using llvm::vfs::detail::InMemoryDirectory::const_iterator = decltype(Entries)::const_iterator
Definition at line 826 of file VirtualFileSystem.cpp.
Constructor & Destructor Documentation
InMemoryDirectory()
llvm::vfs::detail::InMemoryDirectory::InMemoryDirectory (Status Stat) inline
Definition at line 803 of file VirtualFileSystem.cpp.
References getName(), llvm::vfs::detail::IME_Directory, llvm::vfs::detail::InMemoryNode::InMemoryNode(), and llvm::move().
Member Function Documentation
addChild()
InMemoryNode * llvm::vfs::detail::InMemoryDirectory::addChild (StringRef Name, std::unique_ptr< InMemoryNode > Child) inline
Definition at line 822 of file VirtualFileSystem.cpp.
References llvm::vfs::detail::InMemoryNode::InMemoryNode().
begin()
const_iterator llvm::vfs::detail::InMemoryDirectory::begin () const inline
Definition at line 828 of file VirtualFileSystem.cpp.
classof()
bool llvm::vfs::detail::InMemoryDirectory::classof (const InMemoryNode * N) inline static
Definition at line 839 of file VirtualFileSystem.cpp.
References llvm::vfs::detail::IME_Directory, llvm::vfs::detail::InMemoryNode::InMemoryNode(), and N.
end()
const_iterator llvm::vfs::detail::InMemoryDirectory::end () const inline
Definition at line 829 of file VirtualFileSystem.cpp.
getChild()
InMemoryNode * llvm::vfs::detail::InMemoryDirectory::getChild (StringRef Name) const inline
Definition at line 815 of file VirtualFileSystem.cpp.
References I, and llvm::vfs::detail::InMemoryNode::InMemoryNode().
getStatus()
Status llvm::vfs::detail::InMemoryDirectory::getStatus (const Twine & RequestedName) const inline override virtual
Return the Status for this node.
RequestedName should be the name through which the caller referred to this node. It will override Status::Name in the return value, to mimic the behavior of RealFile.
Implements llvm::vfs::detail::InMemoryNode.
Definition at line 809 of file VirtualFileSystem.cpp.
References llvm::vfs::Status::copyWithNewName().
getUniqueID()
UniqueID llvm::vfs::detail::InMemoryDirectory::getUniqueID () const inline
Definition at line 813 of file VirtualFileSystem.cpp.
toString()
std::string llvm::vfs::detail::InMemoryDirectory::toString (unsigned Indent) const inline override virtual
Implements llvm::vfs::detail::InMemoryNode.
Definition at line 831 of file VirtualFileSystem.cpp.
The documentation for this class was generated from the following file:
lib/Support/VirtualFileSystem.cpp