LLVM: llvm::DbgSSABlock Class Reference
llvm::DbgSSABlock Class Reference
#include "llvm/Transforms/Utils/DebugSSAUpdater.h"
Public Types
using PHIListT = SmallVector<DbgSSAPhi, 1>
Public Member Functions
DbgSSABlock (BasicBlock &BB, DebugSSAUpdater &Updater)
DbgSSABlockPredIterator pred_begin ()
DbgSSABlockPredIterator pred_end ()
iterator_range< DbgSSABlockPredIterator > predecessors ()
DbgSSABlockSuccIterator succ_begin ()
DbgSSABlockSuccIterator succ_end ()
iterator_range< DbgSSABlockSuccIterator > successors ()
DbgSSAPhi * newPHI ()
SSAUpdater has requested a PHI: create that within this block record.
PHIListT & phis ()
SSAUpdater wishes to know what PHIs already exist in this block.
Public Attributes
BasicBlock & BB
DebugSSAUpdater & Updater
PHIListT PHIList
List of PHIs in this block.
Detailed Description
Definition at line 166 of file DebugSSAUpdater.h.
Member Typedef Documentation
PHIListT
using llvm::DbgSSABlock::PHIListT = SmallVector<DbgSSAPhi, 1>
Definition at line 170 of file DebugSSAUpdater.h.
Constructor & Destructor Documentation
DbgSSABlock()
llvm::DbgSSABlock::DbgSSABlock (BasicBlock & BB, DebugSSAUpdater & Updater) inline
Definition at line 175 of file DebugSSAUpdater.h.
References BB, and Updater.
Member Function Documentation
newPHI()
DbgSSAPhi * llvm::DbgSSABlock::newPHI () inline
SSAUpdater has requested a PHI: create that within this block record.
Definition at line 203 of file DebugSSAUpdater.h.
References assert(), and PHIList.
Referenced by llvm::SSAUpdaterTraits< DebugSSAUpdater >::CreateEmptyPHI(), and llvm::DebugSSAUpdater::getValueInMiddleOfBlock().
phis()
PHIListT & llvm::DbgSSABlock::phis () inline
SSAUpdater wishes to know what PHIs already exist in this block.
Definition at line 211 of file DebugSSAUpdater.h.
References PHIList.
pred_begin()
DbgSSABlockPredIterator llvm::DbgSSABlock::pred_begin () inline
Definition at line 178 of file DebugSSAUpdater.h.
References BB, llvm::pred_begin(), and Updater.
Referenced by llvm::SSAUpdaterTraits< DebugSSAUpdater >::FindPredecessorBlocks(), and predecessors().
pred_end()
DbgSSABlockPredIterator llvm::DbgSSABlock::pred_end () inline
Definition at line 182 of file DebugSSAUpdater.h.
References BB, llvm::pred_end(), and Updater.
Referenced by llvm::SSAUpdaterTraits< DebugSSAUpdater >::FindPredecessorBlocks(), and predecessors().
predecessors()
iterator_range< DbgSSABlockPredIterator > llvm::DbgSSABlock::predecessors () inline
Definition at line 186 of file DebugSSAUpdater.h.
References llvm::iterator_range(), pred_begin(), and pred_end().
Referenced by llvm::DebugSSAUpdater::getValueInMiddleOfBlock().
succ_begin()
DbgSSABlockSuccIterator llvm::DbgSSABlock::succ_begin () inline
Definition at line 190 of file DebugSSAUpdater.h.
References BB, llvm::succ_begin(), and Updater.
Referenced by llvm::SSAUpdaterTraits< DebugSSAUpdater >::BlkSucc_begin(), and successors().
succ_end()
DbgSSABlockSuccIterator llvm::DbgSSABlock::succ_end () inline
Definition at line 194 of file DebugSSAUpdater.h.
References BB, llvm::succ_end(), and Updater.
Referenced by llvm::SSAUpdaterTraits< DebugSSAUpdater >::BlkSucc_end(), and successors().
successors()
iterator_range< DbgSSABlockSuccIterator > llvm::DbgSSABlock::successors () inline
Definition at line 198 of file DebugSSAUpdater.h.
References llvm::iterator_range(), succ_begin(), and succ_end().
Member Data Documentation
BB
BasicBlock& llvm::DbgSSABlock::BB
Definition at line 168 of file DebugSSAUpdater.h.
Referenced by DbgSSABlock(), pred_begin(), pred_end(), succ_begin(), and succ_end().
PHIList
PHIListT llvm::DbgSSABlock::PHIList
List of PHIs in this block.
There should only ever be one, but this needs to be a list for the SSAUpdater.
Definition at line 173 of file DebugSSAUpdater.h.
Referenced by newPHI(), and phis().
Updater
DebugSSAUpdater& llvm::DbgSSABlock::Updater
Definition at line 169 of file DebugSSAUpdater.h.
Referenced by DbgSSABlock(), pred_begin(), pred_end(), succ_begin(), and succ_end().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Utils/DebugSSAUpdater.h