LLVM: llvm::ScalarEvolution::FoldID Class Reference
llvm::ScalarEvolution::FoldID Class Reference
#include "llvm/Analysis/ScalarEvolution.h"
Public Member Functions
FoldID (SCEVTypes C, const SCEV *Op, const Type *Ty)
FoldID (unsigned short C)
unsigned computeHash () const
bool operator== (const FoldID &RHS) const
Detailed Description
Definition at line 1430 of file ScalarEvolution.h.
Constructor & Destructor Documentation
FoldID() [1/2]
llvm::ScalarEvolution::FoldID::FoldID (SCEVTypes C, const SCEV * Op, const Type * Ty) inline
Definition at line 1436 of file ScalarEvolution.h.
References assert().
Referenced by operator==().
FoldID() [2/2]
llvm::ScalarEvolution::FoldID::FoldID (unsigned short C) inline
Definition at line 1441 of file ScalarEvolution.h.
Member Function Documentation
computeHash()
unsigned llvm::ScalarEvolution::FoldID::computeHash () const inline
Definition at line 1443 of file ScalarEvolution.h.
References llvm::detail::combineHashValue().
Referenced by llvm::DenseMapInfo< ScalarEvolution::FoldID >::getHashValue().
operator==()
bool llvm::ScalarEvolution::FoldID::operator== (const FoldID & RHS) const inline
Definition at line 1449 of file ScalarEvolution.h.
References FoldID(), and RHS.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolution.h