LLVM: llvm::AsmPrinter Class Reference
llvm::AsmPrinter Class Reference
This class is intended to be used as a driving class for all asm writers.
#include "llvm/CodeGen/AsmPrinter.h"
Classes
struct MBBSectionRange
Map a basic block section ID to the begin and end symbols of that section which determine the section's range.
struct XRayFunctionEntry
struct Structor
llvm.global_ctors and llvm.global_dtors are arrays of Structor structs.
Public Types
enum class CFISection : unsigned { None = 0 , EH = 1 , Debug = 2 }
enum class SledKind : uint8_t {
FUNCTION_ENTER = 0 , FUNCTION_EXIT = 1 , TAIL_CALL = 2 , LOG_ARGS_ENTER = 3 ,
CUSTOM_EVENT = 4 , TYPED_EVENT = 5
}
using GOTEquivUsePair = std::pair<const GlobalVariable *, unsigned>
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
using AliasMapTy = DenseMap<uint64_t, SmallVector<const GlobalAlias *, 1>>
Print a general LLVM constant to the .s file.
Public Member Functions
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isDwarf64 () const
unsigned int getDwarfOffsetByteSize () const
Returns 4 for DWARF32 and 8 for DWARF64.
unsigned int getUnitLengthFieldByteSize () const
Returns 4 for DWARF32 and 12 for DWARF64.
dwarf::FormParams getDwarfFormParams () const
Returns information about the byte size of DW_FORM values.
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getMBBExceptionSym (const MachineBasicBlock &MBB)
MCSymbol * getAddrLabelSymbol (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
MCSymbol * createCallsiteEndSymbol (const MachineBasicBlock &MBB)
Creates a new symbol to be used for the end of a callsite at the specified basic block.
void takeDeletedSymbolsForFunction (const Function *F, std::vector< MCSymbol * > &Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
MCSymbol * getSymbolPreferLocal (const GlobalValue &GV) const
Similar to getSymbol() but preferred for references.
bool doesDwarfUseRelocationsAcrossSections () const
void setDwarfUsesRelocationsAcrossSections (bool Enable)
StringRef getConstantSectionSuffix (const Constant *C) const
Returns a section suffix (hot or unlikely) for the constant if profiles are available.
void handleCallsiteForCallgraph (FunctionCallGraphInfo &FuncCGInfo, const MachineFunction::CallSiteInfoMap &CallSitesInfoMap, const MachineInstr &MI)
If MI is an indirect call, add expected type IDs to indirect type ids list.
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
bool doFinalization (Module &M) override
Shut down the asmprinter.
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void emitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitStackUsage (const MachineFunction &MF)
void emitBBAddrMapSection (const MachineFunction &MF)
void emitKCFITrapEntry (const MachineFunction &MF, const MCSymbol *Symbol)
virtual void emitKCFITypeId (const MachineFunction &MF)
void emitCallGraphSection (const MachineFunction &MF, FunctionCallGraphInfo &FuncCGInfo)
Emits .llvm.callgraph section.
void emitPseudoProbe (const MachineInstr &MI)
void emitRemarksSection (remarks::RemarkStreamer &RS)
void emitPCSectionsLabel (const MachineFunction &MF, const MDNode &MD)
Emits a label as reference for PC sections.
void emitPCSections (const MachineFunction &MF)
Emits the PC sections collected from instructions.
CFISection getFunctionCFISectionType (const Function &F) const
Get the CFISection type for a function.
CFISection getFunctionCFISectionType (const MachineFunction &MF) const
Get the CFISection type for a function.
CFISection getModuleCFISectionType () const
Get the CFISection type for the module.
bool hasDebugInfo () const
Returns true if valid debug info is present.
bool needsSEHMoves ()
bool usesCFIWithoutEH () const
Since emitting CFI unwind information is entangled with supporting the exceptions, this returns true for platforms which use CFI unwind information for other purposes (debugging, sanitizers, ...) when MCAsmInfo::ExceptionsType == ExceptionHandling::None.
virtual void emitConstantPool ()
Print to the current output stream assembly representations of the constants in the constant pool MCP.
virtual void emitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
virtual void emitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool emitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void preprocessXXStructorList (const DataLayout &DL, const Constant *List, SmallVector< Structor, 8 > &Structors)
This method gathers an array of Structors and then sorts them out by Priority.
virtual void emitXXStructorList (const DataLayout &DL, const Constant *List, bool IsCtor)
This method emits llvm.global_ctors or llvm.global_dtors list.
void emitAlignment (Align Alignment, const GlobalObject *GV=nullptr, unsigned MaxBytesToEmit=0) const
Emit an alignment directive to the specified power of two boundary.
virtual const MCExpr * lowerConstant (const Constant *CV, const Constant *BaseCV=nullptr, uint64_t Offset=0)
Lower the specified LLVM Constant to an MCExpr.
void emitGlobalConstant (const DataLayout &DL, const Constant *CV, AliasMapTy *AliasList=nullptr)
EmitGlobalConstant - Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps ()
Emit the stack maps.
void addAsmPrinterHandler (std::unique_ptr< AsmPrinterHandler > Handler)
virtual void emitStartOfAsmFile (Module &)
This virtual method can be overridden by targets that want to emit something at the start of their file.
virtual void emitEndOfAsmFile (Module &)
This virtual method can be overridden by targets that want to emit something at the end of their file.
virtual void emitFunctionBodyStart ()
Targets can override this to emit stuff before the first basic block in the function.
virtual void emitFunctionBodyEnd ()
Targets can override this to emit stuff after the last basic block in the function.
virtual void emitBasicBlockStart (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the start of a basic block.
virtual void emitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual void emitInstruction (const MachineInstr *)
Targets should implement this to emit instructions.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void emitFunctionEntryLabel ()
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
virtual void emitFunctionDescriptor ()
virtual void emitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void emitXXStructor (const DataLayout &DL, const Constant *CV)
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
virtual const MCExpr * lowerConstantPtrAuth (const ConstantPtrAuth &CPA)
virtual const MCExpr * lowerBlockAddressConstant (const BlockAddress &BA)
Lower the specified BlockAddress to an MCExpr.
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
virtual const MCSubtargetInfo * getIFuncMCSubtargetInfo () const
getSubtargetInfo() cannot be used where this is needed because we don't have a MachineFunction when we're lowering a GlobalIFunc, and getSubtargetInfo requires one.
virtual void emitMachOIFuncStubBody (Module &M, const GlobalIFunc &GI, MCSymbol *LazyPointer)
virtual void emitMachOIFuncStubHelperBody (Module &M, const GlobalIFunc &GI, MCSymbol *LazyPointer)
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (const Twine &Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void emitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void emitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void emitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void emitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void emitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
virtual void emitTTypeReference (const GlobalValue *GV, unsigned Encoding)
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4- or 8-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-or 8-byte offset of a string from the start of its section.
void emitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset" or ".quad Label + Offset" depending on the DWARF format.
void emitDwarfLengthOrOffset (uint64_t Value) const
Emit 32- or 64-bit value depending on the DWARF format.
void emitDwarfUnitLength (uint64_t Length, const Twine &Comment) const
Emit a unit length field.
MCSymbol * emitDwarfUnitLength (const Twine &Prefix, const Twine &Comment) const
Emit a unit length field.
void emitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
virtual void emitDebugValue (const MCExpr *Value, unsigned Size) const
Emit the directive and value for debug thread local expression.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T>
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
virtual std::tuple< const MCSymbol *, uint64_t, const MCSymbol *, codeview::JumpTableEntrySize > getCodeViewJumpTableInfo (int JTI, const MachineInstr *BranchInstr, const MCSymbol *BranchLabel) const
Gets information required to create a CodeView debug symbol for a jump table.
void emitCOFFReplaceableFunctionData (Module &M)
Emits symbols and data to allow functions marked with the loader-replaceable attribute to be replaceable.
void emitCOFFFeatureSymbol (Module &M)
Emits the @feat.00 symbol indicating the features enabled in this module.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, StringRef Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void PrintSymbolOperand (const MachineOperand &MO, raw_ostream &OS)
Print the MachineOperand as a symbol.
virtual bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS)
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS)
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
virtual void emitInlineAsmStart () const
Let the target do anything it needs to do before emitting inlineasm.
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo, const MachineInstr *MI)
Let the target do anything it needs to do after emitting inlineasm.
void emitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
virtual void emitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
StringRef getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Member Functions
static Align getGVAlignment (const GlobalObject *GV, const DataLayout &DL, Align InAlign=Align(1))
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI = nullptr
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineDominatorTree.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE = nullptr
Optimization remark emitter.
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
DenseMap< const MachineBasicBlock *, SmallVector< MCSymbol *, 1 > > CurrentFnCallsiteEndSymbols
Vector of symbols marking the end of the callsites in the current function, keyed by their containing basic block.
const StaticDataProfileInfo * SDPI = nullptr
Provides the profile information for constants.
const ProfileSummaryInfo * PSI = nullptr
The profile summary information.
MapVector< MBBSectionID, MBBSectionRange > MBBSectionRanges
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
Protected Member Functions
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer, char &ID=AsmPrinter::ID)
virtual void emitJumpTableEntry (const MachineJumpTableInfo &MJTI, const MachineBasicBlock *MBB, unsigned uid) const
EmitJumpTableEntry - Emit a jump table entry for the specified MBB to the current stream.
virtual void emitGlobalAlias (const Module &M, const GlobalAlias &GA)
virtual bool shouldEmitWeakSwiftAsyncExtendedFramePointerFlags () const
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes
MCSymbol * CurrentFnBegin = nullptr
MCSymbol * CurrentFnBeginLocal = nullptr
For dso_local functions, the current $local alias for the function.
SmallVector< std::unique_ptr< AsmPrinterHandler >, 1 > EHHandlers
A handle to the EH info emitter (if present).
SmallVector< std::unique_ptr< AsmPrinterHandler >, 2 > Handlers
size_t NumUserHandlers = 0
StackMaps SM
Detailed Description
This class is intended to be used as a driving class for all asm writers.
Definition at line 91 of file AsmPrinter.h.
Member Typedef Documentation
AliasMapTy
using llvm::AsmPrinter::AliasMapTy = DenseMap<uint64_t, SmallVector<const GlobalAlias *, 1>>
Print a general LLVM constant to the .s file.
On AIX, when an alias refers to a sub-element of a global variable, the label of that alias needs to be emitted before the corresponding element.
Definition at line 562 of file AsmPrinter.h.
GOTEquivUsePair
using llvm::AsmPrinter::GOTEquivUsePair = std::pair<const GlobalVariable *, unsigned>
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
Definition at line 162 of file AsmPrinter.h.
Member Enumeration Documentation
CFISection
enum class llvm::AsmPrinter::CFISection : unsigned strong
Enumerator
None
Do not emit either .eh_frame or .debug_frame.
EH
Emit .eh_frame.
Debug
Emit .debug_frame.
Definition at line 166 of file AsmPrinter.h.
SledKind
enum class llvm::AsmPrinter::SledKind : uint8_t strong
Enumerator
FUNCTION_ENTER
FUNCTION_EXIT
TAIL_CALL
LOG_ARGS_ENTER
CUSTOM_EVENT
TYPED_EVENT
Definition at line 389 of file AsmPrinter.h.
Constructor & Destructor Documentation
AsmPrinter()
AsmPrinter::AsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer, char & ID = AsmPrinter::ID) protected
Definition at line 414 of file AsmPrinter.cpp.
References llvm::MachineFunctionPass::MachineFunctionPass(), MAI, llvm::move(), OutContext, OutStreamer, SM, and TM.
Referenced by llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), llvm::ARMAsmPrinter::ARMAsmPrinter(), llvm::BPFAsmPrinter::BPFAsmPrinter(), llvm::CSKYAsmPrinter::CSKYAsmPrinter(), GetBlockAddressSymbol(), GetBlockAddressSymbol(), llvm::HexagonAsmPrinter::HexagonAsmPrinter(), llvm::LoongArchAsmPrinter::LoongArchAsmPrinter(), llvm::M68kAsmPrinter::M68kAsmPrinter(), llvm::MipsAsmPrinter::MipsAsmPrinter(), llvm::NVPTXAsmPrinter::NVPTXAsmPrinter(), llvm::R600AsmPrinter::R600AsmPrinter(), llvm::SystemZAsmPrinter::SystemZAsmPrinter(), llvm::WebAssemblyAsmPrinter::WebAssemblyAsmPrinter(), llvm::X86AsmPrinter::X86AsmPrinter(), and llvm::XtensaAsmPrinter::XtensaAsmPrinter().
~AsmPrinter()
AsmPrinter::~AsmPrinter () override
Definition at line 424 of file AsmPrinter.cpp.
References assert(), Handlers, and NumUserHandlers.
Member Function Documentation
addAsmPrinterHandler()
void AsmPrinter::addAsmPrinterHandler (std::unique_ptr< AsmPrinterHandler > Handler)
Definition at line 4793 of file AsmPrinter.cpp.
References Handlers, and NumUserHandlers.
computeGlobalGOTEquivs()
void AsmPrinter::computeGlobalGOTEquivs (Module & M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
Unnamed constant global variables solely contaning a pointer to another globals variable is equivalent to a GOT table entry; it contains the the address of another symbol.
One optimization is to replace accesses to these proxies by using the GOT entry for the final global instead. Hence, we select GOT equivalent candidates among all the module global variables, avoid emitting them unnecessarily and finally replace references to them by pc relative accesses to GOT entries.
Optimize it and replace accesses to these "GOT equivalents" by using the GOT entry for the final global instead. Compute GOT equivalent candidates among all global variables to avoid emitting them if possible later on, after it use is replaced by a GOT entry access.
Definition at line 2436 of file AsmPrinter.cpp.
References G, getObjFileLowering(), getSymbol(), GlobalGOTEquivs, and isGOTEquivalentCandidate().
Referenced by doFinalization().
createCallsiteEndSymbol()
MCSymbol * AsmPrinter::createCallsiteEndSymbol (const MachineBasicBlock & MBB)
Creates a new symbol to be used for the end of a callsite at the specified basic block.
Definition at line 3023 of file AsmPrinter.cpp.
References CurrentFnCallsiteEndSymbols, MBB, and MF.
Referenced by emitFunctionBody().
createTempSymbol()
MCSymbol * AsmPrinter::createTempSymbol (const Twine & Name) const
Definition at line 4428 of file AsmPrinter.cpp.
References OutContext.
Referenced by emitFunctionBody(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), llvm::X86AsmPrinter::emitInstruction(), getMBBExceptionSym(), and SetupMachineFunction().
doesDwarfUseRelocationsAcrossSections()
bool llvm::AsmPrinter::doesDwarfUseRelocationsAcrossSections () const inline
Definition at line 364 of file AsmPrinter.h.
Referenced by emitDwarfStringOffset(), emitDwarfSymbolReference(), llvm::DIEString::emitValue(), and getDwarfFormParams().
doFinalization()
bool AsmPrinter::doFinalization (Module & M) override virtual
Shut down the asmprinter.
If you override this in your pass, you must make sure to call it explicitly.
Reimplemented from llvm::Pass.
Reimplemented in llvm::BPFAsmPrinter, and llvm::NVPTXAsmPrinter.
Definition at line 2739 of file AsmPrinter.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), computeGlobalGOTEquivs(), llvm::MCSymbolRefExpr::create(), llvm::GlobalValue::DefaultVisibility, DL, llvm::dyn_cast(), EHHandlers, emitAlignment(), emitEndOfAsmFile(), emitGlobalAlias(), emitGlobalGOTEquivs(), emitGlobalVariable(), emitLinkage(), llvm::TargetLoweringObjectFile::emitModuleMetadata(), emitRemarksSection(), emitStackMaps(), emitVisibility(), llvm::GlobalValue::ExternalWeakLinkage, F, G, llvm::Pass::getAnalysisIfAvailable(), llvm::MCObjectFileInfo::getDataSection(), llvm::Function::getFunction(), llvm::TargetLoweringObjectFile::getFunctionEntryPointSymbol(), llvm::MachineModuleInfoCOFF::GetGVStubList(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MCSymbol::getName(), getObjFileLowering(), getSymbol(), llvm::PointerType::getUnqual(), llvm::Global, Handlers, I, llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_LNK_COMDAT, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::SmallPtrSetImpl< PtrType >::insert(), MAI, llvm::MCSA_Global, llvm::MCSA_WeakReference, MF, MI, MMI, NumUserHandlers, OutContext, OutStreamer, llvm::SmallVectorTemplateBase< T, bool >::push_back(), removeMemtagFromGlobal(), llvm::reverse(), shouldEmitWeakSwiftAsyncExtendedFramePointerFlags(), shouldTagGlobal(), llvm::ELF::SHT_LLVM_SYMPART, llvm::ELF::SHT_PROGBITS, tagGlobalDefinition(), TM, and llvm::Value::use_empty().
Referenced by llvm::AMDGPUAsmPrinter::doFinalization(), llvm::BPFAsmPrinter::doFinalization(), and llvm::NVPTXAsmPrinter::doFinalization().
doInitialization()
bool AsmPrinter::doInitialization (Module & M) override virtual
Set up the AsmPrinter when we are working on a new module.
If your pass overrides this, it must make sure to explicitly call this implementation.
Reimplemented from llvm::Pass.
Reimplemented in llvm::BPFAsmPrinter, llvm::NVPTXAsmPrinter, llvm::SystemZAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 492 of file AsmPrinter.cpp.
References llvm::AIX, llvm::ARM, assert(), llvm::DwarfCFI, EH, EHHandlers, emitStartOfAsmFile(), llvm::mdconst::extract_or_null(), F, llvm::sys::path::filename(), llvm::Pass::getAnalysisIfAvailable(), getFunctionCFISectionType(), llvm::MCSymbolXCOFF::getSymbolTableName(), Handlers, hasDebugInfo(), llvm::MCSymbolXCOFF::hasRename(), I, llvm::WinEH::Invalid, llvm::WinEH::Itanium, llvm_unreachable, MAI, MI, MMI, None, llvm::None, OutContext, OutStreamer, llvm::PseudoProbeDescMetadataName, llvm::SjLj, TM, usesCFIWithoutEH(), llvm::Wasm, llvm::WinEH, llvm::WinEH::X86, and llvm::ZOS.
Referenced by llvm::AMDGPUAsmPrinter::doInitialization(), llvm::BPFAsmPrinter::doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), llvm::SystemZAsmPrinter::doInitialization(), and llvm::X86AsmPrinter::doInitialization().
emitAlignment()
void AsmPrinter::emitAlignment (Align Alignment, const GlobalObject * GV = nullptr, unsigned MaxBytesToEmit = 0) const
Emit an alignment directive to the specified power of two boundary.
If a global value is specified, and if that global has an explicit alignment requested, it will override the alignment request if required for correctness.
Definition at line 3676 of file AsmPrinter.cpp.
References getCurrentSection(), llvm::GlobalValue::getDataLayout(), getGVAlignment(), getSubtargetInfo(), MF, OutStreamer, and TM.
Referenced by doFinalization(), emitBasicBlockStart(), emitConstantPool(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), emitGlobalVariable(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitPatchableFunctionEntries(), llvm::X86AsmPrinter::emitStartOfAsmFile(), emitXXStructorList(), llvm::SystemZAsmPrinter::emitXXStructorList(), and llvm::ARMAsmPrinter::runOnMachineFunction().
emitBasicBlockEnd()
void AsmPrinter::emitBasicBlockEnd (const MachineBasicBlock & MBB) virtual
Targets can override this to emit stuff at the end of a basic block.
Reimplemented in llvm::MipsAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 4659 of file AsmPrinter.cpp.
References EHHandlers, Handlers, and MBB.
Referenced by llvm::MipsAsmPrinter::emitBasicBlockEnd(), llvm::X86AsmPrinter::emitBasicBlockEnd(), and emitFunctionBody().
emitBasicBlockStart()
void AsmPrinter::emitBasicBlockStart (const MachineBasicBlock & MBB) virtual
Targets can override this to emit stuff at the start of a basic block.
emitBasicBlockStart - This method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
By default, this method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
Reimplemented in llvm::AMDGPUAsmPrinter.
Definition at line 4567 of file AsmPrinter.cpp.
References assert(), EHHandlers, emitAlignment(), emitBasicBlockLoopComments(), getAddrLabelSymbolToEmit(), getObjFileLowering(), Handlers, llvm::BasicBlock::hasAddressTaken(), isVerbose(), MAI, MBB, MF, MLI, OutStreamer, TM, and llvm::WinEH.
Referenced by llvm::AMDGPUAsmPrinter::emitBasicBlockStart(), and emitFunctionBody().
emitBBAddrMapSection()
void AsmPrinter::emitBBAddrMapSection (const MachineFunction & MF)
Definition at line 1455 of file AsmPrinter.cpp.
References assert(), CurrentFnCallsiteEndSymbols, emitLabelDifferenceAsULEB128(), llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisIfAvailable(), getBBAddrMapFeature(), getBBAddrMapMetadata(), llvm::MCObjectFileInfo::getBBAddrMapSection(), llvm::CFGProfile::getBlockCount(), llvm::MachineBlockFrequencyInfo::getBlockFreq(), llvm::CFGProfile::getEdgeCount(), llvm::MachineBranchProbabilityInfo::getEdgeProbability(), llvm::BlockFrequency::getFrequency(), getFunctionBegin(), llvm::BasicBlockSectionsProfileReader::getFunctionCFGProfile(), llvm::BranchProbability::getNumerator(), getObjFileLowering(), getPointerSize(), HasCalls, MBB, MBBSectionRanges, MF, and OutStreamer.
Referenced by emitFunctionBody().
emitCallGraphSection()
void AsmPrinter::emitCallGraphSection (const MachineFunction & MF, FunctionCallGraphInfo & FuncCGInfo)
Emits .llvm.callgraph section.
Definition at line 1724 of file AsmPrinter.cpp.
References assert(), extractNumericCGTypeId(), F, llvm::MCObjectFileInfo::getCallGraphSection(), getCurrentSection(), getObjFileLowering(), getSymbol(), callgraph::HasDirectCallees, callgraph::HasIndirectCallees, callgraph::IsIndirectTarget, MF, callgraph::None, OutStreamer, and TM.
Referenced by emitFunctionBody().
emitCallSiteOffset()
void AsmPrinter::emitCallSiteOffset (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
Definition at line 184 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_uleb128, emitLabelDifference(), emitLabelDifferenceAsULEB128(), GetSizeOfEncodedValue(), llvm::Hi, and llvm::Lo.
emitCallSiteValue()
void AsmPrinter::emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
Definition at line 193 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_uleb128, emitULEB128(), GetSizeOfEncodedValue(), and OutStreamer.
emitCFIInstruction() [1/2]
void AsmPrinter::emitCFIInstruction (const MachineInstr & MI)
Definition at line 1370 of file AsmPrinter.cpp.
References llvm::ARM, llvm::DwarfCFI, emitCFIInstruction(), getFunctionCFISectionType(), I, MAI, MBB, MF, MI, None, and usesCFIWithoutEH().
Referenced by emitCFIInstruction(), and emitFunctionBody().
emitCFIInstruction() [2/2]
void AsmPrinter::emitCFIInstruction (const MCCFIInstruction & Inst) const
Emit frame instruction to describe the layout of the frame.
Definition at line 205 of file AsmPrinterDwarf.cpp.
References llvm::MCCFIInstruction::getAddressSpace(), llvm::MCCFIInstruction::getComment(), llvm::MCCFIInstruction::getLoc(), llvm::MCCFIInstruction::getOffset(), llvm::MCCFIInstruction::getOperation(), llvm::MCCFIInstruction::getRegister(), llvm::MCCFIInstruction::getRegister2(), llvm::MCCFIInstruction::getValues(), llvm_unreachable, llvm::MCCFIInstruction::OpAdjustCfaOffset, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaOffset, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpEscape, llvm::MCCFIInstruction::OpGnuArgsSize, llvm::MCCFIInstruction::OpLLVMDefAspaceCfa, llvm::MCCFIInstruction::OpNegateRAState, llvm::MCCFIInstruction::OpNegateRAStateWithPC, llvm::MCCFIInstruction::OpOffset, llvm::MCCFIInstruction::OpRegister, llvm::MCCFIInstruction::OpRememberState, llvm::MCCFIInstruction::OpRestore, llvm::MCCFIInstruction::OpRestoreState, llvm::MCCFIInstruction::OpSameValue, llvm::MCCFIInstruction::OpUndefined, llvm::MCCFIInstruction::OpValOffset, llvm::MCCFIInstruction::OpWindowSave, and OutStreamer.
emitCOFFFeatureSymbol()
void AsmPrinter::emitCOFFFeatureSymbol (Module & M)
Emits the @feat.00 symbol indicating the features enabled in this module.
Definition at line 5070 of file AsmPrinter.cpp.
References assert(), llvm::MCConstantExpr::create(), llvm::COFF::GuardCF, llvm::COFF::GuardEHCont, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_NULL, llvm::COFF::Kernel, llvm::MCSA_Global, MMI, OutStreamer, llvm::COFF::SafeSEH, TM, and llvm::Triple::x86.
Referenced by llvm::X86AsmPrinter::emitStartOfAsmFile().
emitCOFFReplaceableFunctionData()
void AsmPrinter::emitCOFFReplaceableFunctionData (Module & M)
Emits symbols and data to allow functions marked with the loader-replaceable attribute to be replaceable.
Definition at line 5005 of file AsmPrinter.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), F, llvm::MCSymbol::getName(), llvm::HybridPatchableTargetSuffix, llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_DTYPE_NULL, MMI, OutContext, OutStreamer, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and TM.
Referenced by llvm::X86AsmPrinter::emitStartOfAsmFile().
emitConstantPool()
void AsmPrinter::emitConstantPool () virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented in llvm::ARMAsmPrinter, llvm::CSKYAsmPrinter, llvm::MipsAsmPrinter, llvm::WebAssemblyAsmPrinter, and llvm::XtensaAsmPrinter.
Definition at line 3108 of file AsmPrinter.cpp.
References llvm::alignTo(), llvm::CallingConv::C, llvm::MachineConstantPoolEntry::ConstVal, emitAlignment(), emitGlobalConstant(), emitMachineConstantPoolValue(), llvm::MachineConstantPoolEntry::getAlign(), llvm::MachineConstantPool::getConstants(), getConstantSectionSuffix(), GetCPISymbol(), getDataLayout(), getObjFileLowering(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::MachineConstantPoolEntry::getSectionKind(), llvm::MachineConstantPoolEntry::getSizeInBytes(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::MCSymbol::isUndefined(), llvm::MachineConstantPoolEntry::MachineCPVal, MF, llvm::Offset, OutStreamer, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::MachineConstantPoolEntry::Val.
Referenced by llvm::MipsAsmPrinter::emitConstantPool().
emitDebugValue()
void AsmPrinter::emitDebugValue (const MCExpr * Value, unsigned Size) const virtual
Emit the directive and value for debug thread local expression.
Value - The value to emit. Size - The size of the integer (in bytes) to emit.
Reimplemented in llvm::MipsAsmPrinter.
Definition at line 950 of file AsmPrinter.cpp.
References OutStreamer, and Size.
Referenced by llvm::MipsAsmPrinter::emitDebugValue(), and llvm::DIEExpr::emitValue().
emitDwarfAbbrev()
void AsmPrinter::emitDwarfAbbrev (const DIEAbbrev & Abbrev) const
Definition at line 304 of file AsmPrinterDwarf.cpp.
References llvm::DIEAbbrev::Emit(), emitULEB128(), and llvm::DIEAbbrev::getNumber().
Referenced by emitDwarfAbbrevs().
emitDwarfAbbrevs()
template<typename T> void llvm::AsmPrinter::emitDwarfAbbrevs (const T & Abbrevs) const inline
Emit Dwarf abbreviation table.
Definition at line 830 of file AsmPrinter.h.
References emitDwarfAbbrev(), emitULEB128(), and T.
Referenced by llvm::DIEAbbrevSet::Emit().
emitDwarfDIE()
void AsmPrinter::emitDwarfDIE (const DIE & Die) const
Recursively emit Dwarf DIE tree.
Definition at line 269 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::AccessibilityString(), assert(), llvm::dwarf::AttributeString(), llvm::DIE::children(), emitDwarfDIE(), emitInt8(), emitULEB128(), llvm::DIE::getAbbrevNumber(), llvm::DIE::getOffset(), llvm::DIE::getSize(), llvm::DIE::getTag(), llvm::DIE::hasChildren(), isVerbose(), OutStreamer, llvm::dwarf::TagString(), llvm::Twine::utohexstr(), and llvm::DIEValueList::values().
Referenced by emitDwarfDIE().
emitDwarfLengthOrOffset()
void AsmPrinter::emitDwarfLengthOrOffset (uint64_t Value) const
Emit 32- or 64-bit value depending on the DWARF format.
Definition at line 169 of file AsmPrinterDwarf.cpp.
References assert(), getDwarfOffsetByteSize(), isDwarf64(), and OutStreamer.
emitDwarfOffset()
void AsmPrinter::emitDwarfOffset (const MCSymbol * Label, uint64_t Offset) const
Emit something like ".long Label + Offset" or ".quad Label + Offset" depending on the DWARF format.
Definition at line 165 of file AsmPrinterDwarf.cpp.
References emitLabelPlusOffset(), getDwarfOffsetByteSize(), and llvm::Offset.
emitDwarfStringOffset() [1/2]
void AsmPrinter::emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4- or 8-byte offset of a string from the start of its section.
When possible, emit a DwarfStringPool section offset without any relocations, and without using the symbol. Otherwise, defers to emitDwarfSymbolReference().
The length of the emitted value depends on the DWARF format.
Definition at line 154 of file AsmPrinterDwarf.cpp.
References assert(), doesDwarfUseRelocationsAcrossSections(), emitDwarfSymbolReference(), getDwarfOffsetByteSize(), llvm::DwarfStringPoolEntry::Offset, OutStreamer, and llvm::DwarfStringPoolEntry::Symbol.
Referenced by emitDwarfStringOffset().
emitDwarfStringOffset() [2/2]
void llvm::AsmPrinter::emitDwarfStringOffset (DwarfStringPoolEntryRef S) const inline
Emit the 4-or 8-byte offset of a string from the start of its section.
Definition at line 786 of file AsmPrinter.h.
References emitDwarfStringOffset().
emitDwarfSymbolReference()
void AsmPrinter::emitDwarfSymbolReference (const MCSymbol * Label, bool ForceOffset = false) const
Emit a reference to a symbol for use in dwarf.
Different object formats represent this in different ways. Some use a relocation others encode the label offset in its section.
Definition at line 131 of file AsmPrinterDwarf.cpp.
References assert(), doesDwarfUseRelocationsAcrossSections(), emitLabelDifference(), getDwarfOffsetByteSize(), isDwarf64(), MAI, and OutStreamer.
Referenced by emitDwarfStringOffset(), and llvm::DIELocList::emitValue().
emitDwarfUnitLength() [1/2]
MCSymbol * AsmPrinter::emitDwarfUnitLength (const Twine & Prefix, const Twine & Comment) const
Emit a unit length field.
The actual format, DWARF32 or DWARF64, is chosen according to the settings. Return the end symbol generated inside, the caller needs to emit it.
Definition at line 179 of file AsmPrinterDwarf.cpp.
References OutStreamer.
emitDwarfUnitLength() [2/2]
void AsmPrinter::emitDwarfUnitLength (uint64_t Length, const Twine & Comment) const
Emit a unit length field.
The actual format, DWARF32 or DWARF64, is chosen according to the settings.
Definition at line 174 of file AsmPrinterDwarf.cpp.
References llvm::Length, and OutStreamer.
emitEncodingByte()
void AsmPrinter::emitEncodingByte (unsigned Val, const char * Desc = nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
EmitEncodingByte - Emit a .byte 42 directive that corresponds to an encoding.
If verbose assembly output is enabled, we output comments describing the encoding. Desc is a string saying what the encoding is specifying (e.g. "LSDA").
If verbose assembly output is enabled, we output comments describing the encoding. Desc is an optional string saying what the encoding is specifying (e.g. "LSDA").
Definition at line 89 of file AsmPrinterDwarf.cpp.
References DecodeDWARFEncoding(), isVerbose(), and OutStreamer.
emitEndOfAsmFile()
virtual void llvm::AsmPrinter::emitEndOfAsmFile (Module &) inline virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::CSKYAsmPrinter, llvm::HexagonAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::SystemZAsmPrinter, llvm::WebAssemblyAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 599 of file AsmPrinter.h.
Referenced by doFinalization().
emitFrameAlloc()
void AsmPrinter::emitFrameAlloc (const MachineInstr & MI)
Definition at line 1396 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::create(), MI, OutContext, and OutStreamer.
Referenced by emitFunctionBody().
emitFunctionBody()
void AsmPrinter::emitFunctionBody ()
This method emits the body and trailer for a function.
EmitFunctionBody - This method emits the body and trailer for a function.
Definition at line 1963 of file AsmPrinter.cpp.
References A(), assert(), B(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CallsiteIndex, llvm::MCSymbolRefExpr::create(), createCallsiteEndSymbol(), llvm::MCBinaryExpr::createSub(), createTempSymbol(), CurrentFnBegin, CurrentFnBeginLocal, CurrentFnSym, CurrentFnSymForSize, DEBUG_TYPE, EHHandlers, emitBasicBlockEnd(), emitBasicBlockStart(), emitBBAddrMapSection(), emitCallGraphSection(), emitCFIInstruction(), emitComments(), emitDebugLabelComment(), emitDebugValueComment(), emitFakeUse(), emitFrameAlloc(), emitFunctionBodyEnd(), emitFunctionBodyStart(), emitImplicitDef(), emitInstruction(), emitJumpTableInfo(), emitKill(), emitNops(), emitPatchableFunctionEntries(), emitPCSections(), emitPCSectionsLabel(), emitPseudoProbe(), emitStackSizeSection(), emitStackUsage(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), F, llvm::Pass::getAnalysisIfAvailable(), GetBlockAddressSymbol(), getMIMnemonic(), llvm::MCInst::getOpcode(), getSubtargetInfo(), handleCallsiteForCallgraph(), Handlers, llvm::MCSymbol::isDefined(), isVerbose(), MAI, MBB, MBBSectionRanges, llvm::MCSA_Global, llvm::MCSA_Weak, MDT, MF, MI, MLI, MMI, needFuncLabels(), ORE, OutContext, OutStreamer, PgoAnalysisMapFeatures, llvm::sort(), llvm::Triple::SPIRV, and TM.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), and llvm::X86AsmPrinter::runOnMachineFunction().
emitFunctionBodyEnd()
virtual void llvm::AsmPrinter::emitFunctionBodyEnd () inline virtual
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::CSKYAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::SystemZAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 607 of file AsmPrinter.h.
Referenced by emitFunctionBody().
emitFunctionBodyStart()
virtual void llvm::AsmPrinter::emitFunctionBodyStart () inline virtual
Targets can override this to emit stuff before the first basic block in the function.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::WebAssemblyAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 603 of file AsmPrinter.h.
Referenced by emitFunctionBody(), and llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart().
emitFunctionDescriptor()
virtual void llvm::AsmPrinter::emitFunctionDescriptor () inline virtual
Definition at line 628 of file AsmPrinter.h.
References llvm_unreachable.
emitFunctionEntryLabel()
void AsmPrinter::emitFunctionEntryLabel () virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::MipsAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 1107 of file AsmPrinter.cpp.
References CurrentFnBeginLocal, CurrentFnSym, getSymbolPreferLocal(), llvm::MCSA_ELF_TypeFunction, MF, OutStreamer, and TM.
Referenced by llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), and llvm::SystemZAsmPrinter::emitFunctionEntryLabel().
emitGlobalAlias()
void AsmPrinter::emitGlobalAlias (const Module & M, const GlobalAlias & GA) protected virtual
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 2474 of file AsmPrinter.cpp.
References assert(), llvm::MCConstantExpr::create(), DL, emitLinkage(), emitVisibility(), llvm::GlobalAlias::getAliasee(), llvm::GlobalAlias::getAliaseeObject(), getObjFileLowering(), getSymbol(), getSymbolPreferLocal(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::getVisibility(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasPrivateLinkage(), llvm::GlobalValue::hasWeakLinkage(), llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::isa(), llvm::Type::isFunctionTy(), llvm::Type::isSized(), lowerConstant(), MAI, llvm::MCSA_AltEntry, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_Global, llvm::MCSA_WeakReference, OutContext, OutStreamer, llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, Size, llvm::Constant::stripPointerCasts(), and TM.
Referenced by doFinalization(), and llvm::ARMAsmPrinter::emitGlobalAlias().
emitGlobalConstant()
void AsmPrinter::emitGlobalConstant (const DataLayout & DL, const Constant * CV, AliasMapTy * AliasList = nullptr)
EmitGlobalConstant - Print a general LLVM constant to the .s file.
Definition at line 4386 of file AsmPrinter.cpp.
References DL, emitGlobalConstantImpl(), getSymbol(), llvm::Value::getType(), MAI, OutStreamer, and Size.
Referenced by emitConstantPool(), emitGlobalVariable(), llvm::ARMAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), emitKCFITypeId(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitPCSections(), and emitXXStructor().
emitGlobalGOTEquivs()
void AsmPrinter::emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit such globals we previously omitted in EmitGlobalVariable.
Definition at line 2457 of file AsmPrinter.cpp.
References emitGlobalVariable(), getObjFileLowering(), GlobalGOTEquivs, I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by doFinalization().
emitGlobalVariable()
void AsmPrinter::emitGlobalVariable (const GlobalVariable * GV) virtual
Emit the specified global variable to the .s file.
EmitGlobalVariable - Emit the specified global variable to the .s file.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::NVPTXAsmPrinter, and llvm::WebAssemblyAsmPrinter.
Definition at line 753 of file AsmPrinter.cpp.
References llvm::Triple::aarch64, assert(), llvm::MCConstantExpr::create(), DL, emitAlignment(), emitGlobalConstant(), emitLinkage(), emitSpecialLLVMGlobal(), emitVisibility(), llvm::GlobalValue::getDataLayout(), GetExternalSymbolSymbol(), getGVAlignment(), llvm::GlobalVariable::getInitializer(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MCSymbol::getName(), getObjFileLowering(), llvm::GlobalValue::getParent(), getSymbol(), getSymbolPreferLocal(), llvm::MCObjectFileInfo::getTLSBSSSection(), llvm::MCObjectFileInfo::getTLSExtraDataSection(), llvm::GlobalValue::getType(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::getVisibility(), GlobalGOTEquivs, Handlers, llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::SectionKind::isBSS(), llvm::SectionKind::isBSSLocal(), llvm::MCSection::isBssSection(), llvm::SectionKind::isCommon(), llvm::GlobalValue::isDeclaration(), llvm::MCSymbol::isDefined(), llvm::GlobalValue::isTagged(), llvm::SectionKind::isThreadBSS(), llvm::SectionKind::isThreadData(), llvm::GlobalValue::isThreadLocal(), llvm::SectionKind::isThreadLocal(), llvm::MCSymbol::isVariable(), isVerbose(), MAI, llvm::MCSA_ELF_TypeObject, llvm::MCSA_Local, llvm::MCSA_Memtag, llvm::LCOMM::NoAlignment, OutContext, OutStreamer, llvm::Value::printAsOperand(), llvm::MCSymbol::redefineIfPossible(), llvm::TargetLoweringObjectFile::SectionForGlobal(), Size, T, and TM.
Referenced by doFinalization(), emitGlobalGOTEquivs(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::ARMAsmPrinter::emitGlobalVariable(), and llvm::WebAssemblyAsmPrinter::emitGlobalVariable().
emitImplicitDef()
void AsmPrinter::emitImplicitDef (const MachineInstr * MI) const virtual
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
emitImplicitDef - This method emits the specified machine instruction that is an implicit def.
Reimplemented in llvm::AMDGPUAsmPrinter.
Definition at line 1166 of file AsmPrinter.cpp.
References MF, MI, OutStreamer, llvm::printReg(), and llvm::raw_svector_ostream::str().
Referenced by emitFunctionBody().
emitInitialRawDwarfLocDirective()
void AsmPrinter::emitInitialRawDwarfLocDirective (const MachineFunction & MF)
Emits inital debug location directive.
Definition at line 462 of file AsmPrinter.cpp.
References assert(), MF, and OutStreamer.
emitInlineAsmEnd()
void AsmPrinter::emitInlineAsmEnd (const MCSubtargetInfo & StartInfo, const MCSubtargetInfo * EndInfo, const MachineInstr * MI) virtual
Let the target do anything it needs to do after emitting inlineasm.
This callback can be used restore the original mode in case the inlineasm contains directives to switch modes. StartInfo - the original subtarget info before inline asm EndInfo - the final subtarget info after parsing the inline asm, or NULL if the value is unknown.
Reimplemented in llvm::ARMAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 521 of file AsmPrinterInlineAsm.cpp.
References MI.
emitInlineAsmStart()
void AsmPrinter::emitInlineAsmStart () const virtual
Let the target do anything it needs to do before emitting inlineasm.
StartInfo - the subtarget info before parsing inline asm
Definition at line 519 of file AsmPrinterInlineAsm.cpp.
emitInstruction()
virtual void llvm::AsmPrinter::emitInstruction (const MachineInstr *) inline virtual
Targets should implement this to emit instructions.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::BPFAsmPrinter, llvm::CSKYAsmPrinter, llvm::HexagonAsmPrinter, llvm::LoongArchAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::R600AsmPrinter, llvm::SystemZAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::X86AsmPrinter, and llvm::XtensaAsmPrinter.
Definition at line 619 of file AsmPrinter.h.
References llvm_unreachable.
Referenced by emitFunctionBody().
emitInt16()
void AsmPrinter::emitInt16 (int Value) const
Emit a short directive and value.
Definition at line 3608 of file AsmPrinter.cpp.
References OutStreamer.
emitInt32()
void AsmPrinter::emitInt32 (int Value) const
Emit a long directive and value.
Definition at line 3611 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by llvm::SystemZAsmPrinter::emitXXStructorList().
emitInt64()
void AsmPrinter::emitInt64 (uint64_t Value) const
Emit a long long directive and value.
Definition at line 3630 of file AsmPrinter.cpp.
References OutStreamer.
emitInt8()
void AsmPrinter::emitInt8 (int Value) const
Emit a byte directive and value.
Definition at line 3605 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by emitDwarfDIE(), and llvm::DIEInlineString::emitValue().
emitJumpTableEntry()
void AsmPrinter::emitJumpTableEntry (const MachineJumpTableInfo & MJTI, const MachineBasicBlock * MBB, unsigned uid) const protected virtual
EmitJumpTableEntry - Emit a jump table entry for the specified MBB to the current stream.
Definition at line 3352 of file AsmPrinter.cpp.
References assert(), llvm::sampleprof::Base, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MachineJumpTableInfo::EK_BlockAddress, llvm::MachineJumpTableInfo::EK_Custom32, llvm::MachineJumpTableInfo::EK_GPRel32BlockAddress, llvm::MachineJumpTableInfo::EK_GPRel64BlockAddress, llvm::MachineJumpTableInfo::EK_Inline, llvm::MachineJumpTableInfo::EK_LabelDifference32, llvm::MachineJumpTableInfo::EK_LabelDifference64, getDataLayout(), llvm::MachineJumpTableInfo::getEntryKind(), llvm::MachineJumpTableInfo::getEntrySize(), GetJTSetSymbol(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm_unreachable, MAI, MBB, MF, OutContext, and OutStreamer.
emitJumpTableInfo()
void AsmPrinter::emitJumpTableInfo () virtual
Print assembly representations of the jump tables used by the current function to the current output stream.
Reimplemented in llvm::BPFAsmPrinter, llvm::LoongArchAsmPrinter, and llvm::WebAssemblyAsmPrinter.
Definition at line 3184 of file AsmPrinter.cpp.
References llvm::Cold, llvm::MachineJumpTableInfo::getJumpTables(), MF, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::seq(), TM, and llvm::to_vector().
Referenced by emitFunctionBody(), and llvm::LoongArchAsmPrinter::emitJumpTableInfo().
emitKCFITrapEntry()
void AsmPrinter::emitKCFITrapEntry (const MachineFunction & MF, const MCSymbol * Symbol)
Definition at line 1613 of file AsmPrinter.cpp.
References llvm::MCObjectFileInfo::getKCFITrapSection(), getObjFileLowering(), MF, OutContext, and OutStreamer.
emitKCFITypeId()
void AsmPrinter::emitKCFITypeId (const MachineFunction & MF) virtual
Reimplemented in llvm::X86AsmPrinter.
Definition at line 1630 of file AsmPrinter.cpp.
References emitGlobalConstant(), llvm::mdconst::extract(), F, and MF.
emitLabelDifference()
void AsmPrinter::emitLabelDifference (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
This implicitly uses .set if it is available.
This implicitly uses .set if it avoids relocations.
Definition at line 3637 of file AsmPrinter.cpp.
References llvm::Hi, llvm::Lo, OutStreamer, and Size.
Referenced by emitCallSiteOffset(), emitDwarfSymbolReference(), emitPCSections(), and llvm::DIEDelta::emitValue().
emitLabelDifferenceAsULEB128()
void AsmPrinter::emitLabelDifferenceAsULEB128 (const MCSymbol * Hi, const MCSymbol * Lo) const
Emit something like ".uleb128 Hi-Lo".
Definition at line 3643 of file AsmPrinter.cpp.
References llvm::Hi, llvm::Lo, and OutStreamer.
Referenced by emitBBAddrMapSection(), emitCallSiteOffset(), and emitPCSections().
emitLabelPlusOffset()
void AsmPrinter::emitLabelPlusOffset (const MCSymbol * Label, uint64_t Offset, unsigned Size, bool IsSectionRelative = false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
EmitLabelPlusOffset - Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
This implicitly uses .set if it is available.
Definition at line 3651 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), MAI, llvm::Offset, OutContext, OutStreamer, and Size.
Referenced by emitDwarfOffset(), emitLabelReference(), and llvm::DIEEntry::emitValue().
emitLabelReference()
void llvm::AsmPrinter::emitLabelReference (const MCSymbol * Label, unsigned Size, bool IsSectionRelative = false) const inline
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
Definition at line 750 of file AsmPrinter.h.
References emitLabelPlusOffset(), and Size.
Referenced by llvm::DIELabel::emitValue().
emitLinkage()
void AsmPrinter::emitLinkage (const GlobalValue * GV, MCSymbol * GVSym) const virtual
This emits linkage information about GVSym based on GV, if this is supported by the target.
Definition at line 686 of file AsmPrinter.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, canBeHidden(), llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::getLinkage(), llvm::GlobalValue::hasComdat(), llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, MAI, llvm::MCSA_Global, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, OutStreamer, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by doFinalization(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), emitGlobalAlias(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), and llvm::X86AsmPrinter::emitKCFITypeId().
emitMachineConstantPoolValue()
void AsmPrinter::emitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) virtual
Reimplemented in llvm::ARMAsmPrinter, llvm::CSKYAsmPrinter, llvm::SystemZAsmPrinter, and llvm::XtensaAsmPrinter.
Definition at line 4406 of file AsmPrinter.cpp.
References llvm_unreachable.
Referenced by emitConstantPool(), and llvm::MipsAsmPrinter::emitInstruction().
emitMachOIFuncStubBody()
virtual void llvm::AsmPrinter::emitMachOIFuncStubBody (Module & M, const GlobalIFunc & GI, MCSymbol * LazyPointer) inline virtual
Definition at line 665 of file AsmPrinter.h.
References llvm_unreachable.
emitMachOIFuncStubHelperBody()
virtual void llvm::AsmPrinter::emitMachOIFuncStubHelperBody (Module & M, const GlobalIFunc & GI, MCSymbol * LazyPointer) inline virtual
Definition at line 671 of file AsmPrinter.h.
References llvm_unreachable.
emitNops()
void AsmPrinter::emitNops (unsigned N)
Emit N NOP instructions.
Definition at line 4418 of file AsmPrinter.cpp.
References EmitToStreamer(), MF, N, and OutStreamer.
Referenced by emitFunctionBody(), llvm::HexagonAsmPrinter::EmitSled(), llvm::LoongArchAsmPrinter::emitSled(), llvm::LoongArchAsmPrinter::LowerPATCHABLE_FUNCTION_ENTER(), and llvm::LoongArchAsmPrinter::LowerSTATEPOINT().
emitPatchableFunctionEntries()
void AsmPrinter::emitPatchableFunctionEntries ()
Definition at line 4921 of file AsmPrinter.cpp.
References CurrentFnSym, CurrentPatchableFunctionEntrySym, emitAlignment(), F, getPointerSize(), MAI, MF, llvm::MCSection::NonUniqueID, OutContext, OutStreamer, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_PROGBITS, and TM.
Referenced by emitFunctionBody().
emitPCSections()
void AsmPrinter::emitPCSections (const MachineFunction & MF)
Emits the PC sections collected from instructions.
Definition at line 1804 of file AsmPrinter.cpp.
References assert(), llvm::sampleprof::Base, llvm::CallingConv::C, llvm::cast(), llvm::StringRef::contains(), DL, llvm::dyn_cast(), emitGlobalConstant(), emitLabelDifference(), emitLabelDifferenceAsULEB128(), emitULEB128(), F, llvm::StringRef::find(), getFunctionBegin(), getFunctionEnd(), getObjFileLowering(), llvm::MDNode::getOperand(), llvm::MCObjectFileInfo::getPCSection(), getPointerSize(), llvm::isa(), llvm::CodeModel::Large, llvm::CodeModel::Medium, MF, llvm::MDNode::operands(), OutStreamer, Size, and llvm::StringRef::substr().
Referenced by emitFunctionBody().
emitPCSectionsLabel()
void AsmPrinter::emitPCSectionsLabel (const MachineFunction & MF, const MDNode & MD)
Emits a label as reference for PC sections.
Definition at line 1797 of file AsmPrinter.cpp.
References MF, and OutStreamer.
Referenced by emitFunctionBody().
emitPseudoProbe()
void AsmPrinter::emitPseudoProbe (const MachineInstr & MI)
Definition at line 1637 of file AsmPrinter.cpp.
References MI.
Referenced by emitFunctionBody().
emitRemarksSection()
void AsmPrinter::emitRemarksSection (remarks::RemarkStreamer & RS)
Definition at line 2629 of file AsmPrinter.cpp.
References assert(), llvm::sys::fs::make_absolute(), llvm::remarks::RemarkSerializer::metaSerializer(), OutContext, and OutStreamer.
Referenced by doFinalization().
emitSLEB128()
void AsmPrinter::emitSLEB128 (int64_t Value, const char * Desc = nullptr) const
Emit the specified signed leb128 value.
EmitSLEB128 - emit the specified signed leb128 value.
Definition at line 3614 of file AsmPrinter.cpp.
References isVerbose(), and OutStreamer.
Referenced by llvm::DIEAbbrev::Emit().
emitSpecialLLVMGlobal()
bool AsmPrinter::emitSpecialLLVMGlobal (const GlobalVariable * GV)
Check to see if the specified global is a special global used by LLVM.
EmitSpecialLLVMGlobal - Check to see if the specified global is a special global used by LLVM.
If so, emit it and return true, otherwise do nothing and return false.
Definition at line 3405 of file AsmPrinter.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), llvm::LLVMContext::emitError(), emitXXStructorList(), llvm::Value::getContext(), llvm::GlobalValue::getDataLayout(), llvm::GlobalVariable::getInitializer(), llvm::Value::getName(), llvm::Value::getNameOrAsOperand(), llvm::GlobalObject::getSection(), getSymbol(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::COFF::IMAGE_SCN_LNK_INFO, MAI, OutContext, and OutStreamer.
Referenced by emitGlobalVariable().
emitStackMaps()
void AsmPrinter::emitStackMaps ()
Emit the stack maps.
Definition at line 4772 of file AsmPrinter.cpp.
References assert(), llvm::Pass::getAnalysisIfAvailable(), I, MI, and SM.
Referenced by doFinalization().
emitStackSizeSection()
void AsmPrinter::emitStackSizeSection (const MachineFunction & MF)
Definition at line 1648 of file AsmPrinter.cpp.
References getFunctionBegin(), getObjFileLowering(), llvm::MachineFrameInfo::getStackSize(), llvm::MCObjectFileInfo::getStackSizesSection(), llvm::MachineFrameInfo::getUnsafeStackSize(), llvm::MachineFrameInfo::hasVarSizedObjects(), MF, OutStreamer, and TM.
Referenced by emitFunctionBody().
emitStackUsage()
void AsmPrinter::emitStackUsage (const MachineFunction & MF)
Definition at line 1674 of file AsmPrinter.cpp.
References llvm::errs(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFrameInfo::getUnsafeStackSize(), llvm::MachineFrameInfo::hasVarSizedObjects(), MF, llvm::sys::fs::OF_Text, and OutputFilename.
Referenced by emitFunctionBody().
emitStartOfAsmFile()
virtual void llvm::AsmPrinter::emitStartOfAsmFile (Module &) inline virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::CSKYAsmPrinter, llvm::HexagonAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::SystemZAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 595 of file AsmPrinter.h.
Referenced by doInitialization(), and llvm::SystemZAsmPrinter::emitStartOfAsmFile().
EmitToStreamer()
void AsmPrinter::EmitToStreamer (MCStreamer & S, const MCInst & Inst)
Definition at line 458 of file AsmPrinter.cpp.
References llvm::MCStreamer::emitInstruction(), and getSubtargetInfo().
Referenced by llvm::X86AsmPrinter::emitBasicBlockEnd(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::BPFAsmPrinter::emitInstruction(), llvm::LoongArchAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::R600AsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::WebAssemblyAsmPrinter::emitInstruction(), llvm::XtensaAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitJumpTableInsts(), emitNops(), llvm::HexagonAsmPrinter::EmitSled(), llvm::LoongArchAsmPrinter::emitSled(), llvm::CSKYAsmPrinter::EmitToStreamer(), llvm::LoongArchAsmPrinter::LowerSTATEPOINT(), and llvm::ARMAsmPrinter::runOnMachineFunction().
emitTTypeReference()
void AsmPrinter::emitTTypeReference (const GlobalValue * GV, unsigned Encoding) virtual
Emit reference to a ttype global with a specified encoding.
Definition at line 120 of file AsmPrinterDwarf.cpp.
References getObjFileLowering(), GetSizeOfEncodedValue(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), MMI, OutStreamer, and TM.
emitULEB128()
void AsmPrinter::emitULEB128 (uint64_t Value, const char * Desc = nullptr, unsigned PadTo = 0) const
Emit the specified unsigned leb128 value.
Definition at line 3621 of file AsmPrinter.cpp.
References isVerbose(), and OutStreamer.
Referenced by llvm::DIEAbbrev::Emit(), emitCallSiteValue(), emitDwarfAbbrev(), emitDwarfAbbrevs(), emitDwarfDIE(), emitPCSections(), llvm::DIEBaseTypeRef::emitValue(), llvm::DIEEntry::emitValue(), and llvm::DIELocList::emitValue().
emitVisibility()
void AsmPrinter::emitVisibility (MCSymbol * Sym, unsigned Visibility, bool IsDefinition = true) const
This emits visibility information about symbol, if this is supported by the target.
Definition at line 4670 of file AsmPrinter.cpp.
References llvm::GlobalValue::HiddenVisibility, MAI, llvm::MCSA_Invalid, OutStreamer, and llvm::GlobalValue::ProtectedVisibility.
Referenced by doFinalization(), emitGlobalAlias(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), and llvm::WebAssemblyAsmPrinter::emitGlobalVariable().
emitXRayTable()
void AsmPrinter::emitXRayTable ()
Emit a table with all XRay instrumentation points.
Definition at line 4818 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), CurrentFnBegin, CurrentFnSym, F, llvm::SectionKind::getReadOnly(), llvm::SectionKind::getReadOnlyWithRel(), llvm_unreachable, MAI, MF, llvm::MCSection::NonUniqueID, OutContext, OutStreamer, llvm::MachO::S_ATTR_LIVE_SUPPORT, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHT_PROGBITS, Sleds, and TM.
Referenced by llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::HexagonAsmPrinter::runOnMachineFunction(), llvm::LoongArchAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::SystemZAsmPrinter::runOnMachineFunction(), and llvm::X86AsmPrinter::runOnMachineFunction().
emitXXStructor()
virtual void llvm::AsmPrinter::emitXXStructor (const DataLayout & DL, const Constant * CV) inline virtual
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 636 of file AsmPrinter.h.
References DL, and emitGlobalConstant().
Referenced by emitXXStructorList().
emitXXStructorList()
void AsmPrinter::emitXXStructorList (const DataLayout & DL, const Constant * List, bool IsCtor) virtual
This method emits llvm.global_ctors or llvm.global_dtors list.
EmitXXStructorList - Emit the ctor or dtor list taking into account the init priority.
Reimplemented in llvm::SystemZAsmPrinter.
Definition at line 3525 of file AsmPrinter.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), DL, emitAlignment(), emitXXStructor(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getObjFileLowering(), getSymbol(), llvm::GlobalValue::isDeclarationForLinker(), OutStreamer, preprocessXXStructorList(), and TM.
Referenced by emitSpecialLLVMGlobal(), and llvm::SystemZAsmPrinter::emitXXStructorList().
getAddrLabelSymbol()
MCSymbol * llvm::AsmPrinter::getAddrLabelSymbol (const BasicBlock * BB) inline
Return the symbol to be used for the specified basic block when its address is taken.
This cannot be its normal LBB label because the block may be accessed outside its containing function.
Definition at line 314 of file AsmPrinter.h.
References getAddrLabelSymbolToEmit().
Referenced by GetBlockAddressSymbol(), and GetBlockAddressSymbol().
getAddrLabelSymbolToEmit()
ArrayRef< MCSymbol * > AsmPrinter::getAddrLabelSymbolToEmit (const BasicBlock * BB)
Return the symbol to be used for the specified basic block when its address is taken.
If other blocks were RAUW'd to this one, we may have to emit them as well, return the whole set.
Definition at line 311 of file AsmPrinter.cpp.
References OutContext.
Referenced by emitBasicBlockStart(), and getAddrLabelSymbol().
getAnalysisUsage()
void AsmPrinter::getAnalysisUsage (AnalysisUsage & AU) const override virtual
Record analysis usage.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter.
Definition at line 480 of file AsmPrinter.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::AnalysisUsage::addUsedIfAvailable(), EmitBBHash, llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by llvm::AMDGPUAsmPrinter::getAnalysisUsage(), and llvm::NVPTXAsmPrinter::getAnalysisUsage().
GetBlockAddressSymbol() [1/2]
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BasicBlock * BB) const
Definition at line 4437 of file AsmPrinter.cpp.
References AsmPrinter(), and getAddrLabelSymbol().
GetBlockAddressSymbol() [2/2]
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BlockAddress * BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
Definition at line 4432 of file AsmPrinter.cpp.
References AsmPrinter(), getAddrLabelSymbol(), and llvm::BlockAddress::getBasicBlock().
Referenced by emitFunctionBody(), EmitInlineAsmStr(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), getMCSymbolForTOCPseudoMO(), llvm::HexagonLowerToMC(), lowerBlockAddressConstant(), llvm::lowerLoongArchMachineOperandToMCOperand(), LowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), llvm::XtensaAsmPrinter::LowerSymbolOperand(), llvm::M68kAsmPrinter::PrintAsmMemoryOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::BPFAsmPrinter::printOperand(), and llvm::MipsAsmPrinter::printOperand().
getCodeViewJumpTableInfo()
std::tuple< const MCSymbol *, uint64_t, const MCSymbol *, codeview::JumpTableEntrySize > AsmPrinter::getCodeViewJumpTableInfo (int JTI, const MachineInstr * BranchInstr, const MCSymbol * BranchLabel) const virtual
Gets information required to create a CodeView debug symbol for a jump table.
Return value is <Base Address, Base Offset, Branch Address, Entry Size>
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 4992 of file AsmPrinter.cpp.
References llvm::sampleprof::Base, llvm::cast(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::codeview::Int32, MF, and MMI.
getConstantSectionSuffix()
StringRef AsmPrinter::getConstantSectionSuffix (const Constant * C) const
Returns a section suffix (hot or unlikely) for the constant if profiles are available.
Returns empty string otherwise.
Definition at line 3097 of file AsmPrinter.cpp.
References llvm::CallingConv::C, PSI, SDPI, and TM.
Referenced by emitConstantPool().
GetCPISymbol()
MCSymbol * AsmPrinter::GetCPISymbol (unsigned CPID) const virtual
Return the symbol for the specified constant pool entry.
GetCPISymbol - Return the symbol for the specified constant pool entry.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 4446 of file AsmPrinter.cpp.
References llvm::MachineConstantPoolEntry::Alignment, llvm::CallingConv::C, llvm::MachineConstantPoolEntry::ConstVal, DL, getDataLayout(), getFunctionNumber(), getObjFileLowering(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::MachineConstantPoolEntry::getSectionKind(), getSubtargetInfo(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::MCSA_Global, MF, OutContext, OutStreamer, TM, and llvm::MachineConstantPoolEntry::Val.
Referenced by emitConstantPool(), llvm::MipsAsmPrinter::emitInstruction(), llvm::XtensaAsmPrinter::emitMachineConstantPoolEntry(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::GetConstantPoolIndexSymbol(), getMCSymbolForTOCPseudoMO(), llvm::HexagonLowerToMC(), llvm::lowerLoongArchMachineOperandToMCOperand(), LowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), llvm::HexagonAsmPrinter::printOperand(), and smallData().
getCurrentSection()
const MCSection * AsmPrinter::getCurrentSection () const
Return the current section we are emitting to.
getCurrentSection() - Return the current section we are emitting to.
Definition at line 476 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by emitAlignment(), and emitCallGraphSection().
getDataLayout()
const DataLayout & AsmPrinter::getDataLayout () const
Return information about data layout.
Definition at line 442 of file AsmPrinter.cpp.
References assert(), and MMI.
Referenced by llvm::DwarfExpression::addConstantFP(), emitConstantPool(), llvm::X86AsmPrinter::emitEndOfAsmFile(), emitGlobalConstantFP(), emitGlobalConstantLargeInt(), llvm::ARMAsmPrinter::emitInstruction(), emitJumpTableEntry(), llvm::BPFAsmPrinter::emitJumpTableInfo(), llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::ARMAsmPrinter::GetCPISymbol(), GetCPISymbol(), GetExternalSymbolSymbol(), GetJTSetSymbol(), GetSymbolFromOperand(), lowerConstant(), and llvm::MipsAsmPrinter::printOperand().
getDwarfDebug() [1/2]
DwarfDebug * llvm::AsmPrinter::getDwarfDebug () inline
Definition at line 275 of file AsmPrinter.h.
Referenced by llvm::DwarfDebug::emitDebugLocValue(), and llvm::DIELocList::emitValue().
getDwarfDebug() [2/2]
DwarfDebug * llvm::AsmPrinter::getDwarfDebug () const inline
Definition at line 276 of file AsmPrinter.h.
getDwarfFormParams()
dwarf::FormParams AsmPrinter::getDwarfFormParams () const
Returns information about the byte size of DW_FORM values.
Definition at line 4979 of file AsmPrinter.cpp.
References doesDwarfUseRelocationsAcrossSections(), getDwarfVersion(), MAI, and OutStreamer.
Referenced by llvm::DIEDelta::emitValue(), llvm::DIEEntry::emitValue(), llvm::DIEExpr::emitValue(), and llvm::DIELabel::emitValue().
getDwarfOffsetByteSize()
unsigned int AsmPrinter::getDwarfOffsetByteSize () const
Returns 4 for DWARF32 and 8 for DWARF64.
Definition at line 4974 of file AsmPrinter.cpp.
References llvm::dwarf::getDwarfOffsetByteSize(), and OutStreamer.
Referenced by emitDwarfLengthOrOffset(), emitDwarfOffset(), emitDwarfStringOffset(), and emitDwarfSymbolReference().
getDwarfVersion()
uint16_t AsmPrinter::getDwarfVersion () const
Definition at line 4962 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by llvm::DIEAbbrev::Emit(), llvm::DwarfDebug::emitDebugLocValue(), llvm::DebugLocEntry::finalize(), and getDwarfFormParams().
GetExternalSymbolSymbol()
MCSymbol * AsmPrinter::GetExternalSymbolSymbol (const Twine & Sym) const
Return the MCSymbol for the specified ExternalSymbol.
Definition at line 4495 of file AsmPrinter.cpp.
References getDataLayout(), llvm::Mangler::getNameWithPrefix(), and OutContext.
Referenced by llvm::X86AsmPrinter::emitEndOfAsmFile(), emitGlobalVariable(), llvm::ARMAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol(), handleCallsiteForCallgraph(), llvm::HexagonLowerToMC(), llvm::lowerLoongArchMachineOperandToMCOperand(), LowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::XtensaAsmPrinter::LowerSymbolOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), and llvm::BPFAsmPrinter::printOperand().
getFunctionBegin()
MCSymbol * llvm::AsmPrinter::getFunctionBegin () const inline
Definition at line 304 of file AsmPrinter.h.
References CurrentFnBegin.
Referenced by emitBBAddrMapSection(), emitPCSections(), and emitStackSizeSection().
getFunctionCFISectionType() [1/2]
AsmPrinter::CFISection AsmPrinter::getFunctionCFISectionType (const Function & F) const
Get the CFISection type for a function.
Definition at line 1339 of file AsmPrinter.cpp.
References Debug, llvm::DwarfCFI, EH, F, hasDebugInfo(), MAI, None, and TM.
Referenced by doInitialization(), emitCFIInstruction(), and getFunctionCFISectionType().
getFunctionCFISectionType() [2/2]
AsmPrinter::CFISection AsmPrinter::getFunctionCFISectionType (const MachineFunction & MF) const
Get the CFISection type for a function.
Definition at line 1358 of file AsmPrinter.cpp.
References getFunctionCFISectionType(), and MF.
getFunctionEnd()
MCSymbol * llvm::AsmPrinter::getFunctionEnd () const inline
Definition at line 305 of file AsmPrinter.h.
Referenced by emitPCSections().
getFunctionFrameSymbol()
virtual const MCSymbol * llvm::AsmPrinter::getFunctionFrameSymbol () const inline virtual
Return symbol for the function pseudo stack if the stack frame is not a register based.
Reimplemented in llvm::NVPTXAsmPrinter.
Definition at line 302 of file AsmPrinter.h.
getFunctionNumber()
unsigned AsmPrinter::getFunctionNumber () const
Return a unique ID for the current function.
getFunctionNumber - Return a unique ID for the current function.
Definition at line 434 of file AsmPrinter.cpp.
References MF.
Referenced by emitBasicBlockLoopComments(), llvm::AMDGPUAsmPrinter::emitBasicBlockStart(), llvm::ARMAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::GetCPISymbol(), GetCPISymbol(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), GetJTSetSymbol(), llvm::MipsAsmPrinter::printOperand(), and PrintSpecial().
getGVAlignment()
Align AsmPrinter::getGVAlignment (const GlobalObject * GV, const DataLayout & DL, Align InAlign = Align(1)) static
Return the alignment for the specified GV.
getGVAlignment - Return the alignment to use for the specified global value.
This rounds up to the preferred alignment if possible and legal.
Definition at line 386 of file AsmPrinter.cpp.
References assert(), DL, llvm::dyn_cast(), F, and llvm::GlobalObject::hasSection().
Referenced by emitAlignment(), and emitGlobalVariable().
getIFuncMCSubtargetInfo()
virtual const MCSubtargetInfo * llvm::AsmPrinter::getIFuncMCSubtargetInfo () const inline virtual
getSubtargetInfo() cannot be used where this is needed because we don't have a MachineFunction when we're lowering a GlobalIFunc, and getSubtargetInfo requires one.
Override the implementation in targets that support the Mach-O IFunc lowering.
Definition at line 661 of file AsmPrinter.h.
getISAEncoding()
virtual unsigned llvm::AsmPrinter::getISAEncoding () inline virtual
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 814 of file AsmPrinter.h.
GetJTISymbol()
MCSymbol * AsmPrinter::GetJTISymbol (unsigned JTID, bool isLinkerPrivate = false) const
Return the symbol for the specified jump table entry.
GetJTISymbol - Return the symbol for the specified jump table entry.
Definition at line 4476 of file AsmPrinter.cpp.
References MF, and OutContext.
Referenced by llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::GetJumpTableSymbol(), getMCSymbolForTOCPseudoMO(), llvm::HexagonLowerToMC(), llvm::lowerLoongArchMachineOperandToMCOperand(), LowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), and smallData().
GetJTSetSymbol()
MCSymbol * AsmPrinter::GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
GetJTSetSymbol - Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
Definition at line 4482 of file AsmPrinter.cpp.
References DL, getDataLayout(), getFunctionNumber(), and OutContext.
Referenced by emitJumpTableEntry().
getMBBExceptionSym()
MCSymbol * AsmPrinter::getMBBExceptionSym (const MachineBasicBlock & MBB)
Definition at line 3016 of file AsmPrinter.cpp.
References createTempSymbol(), and MBB.
Referenced by llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
getModuleCFISectionType()
CFISection llvm::AsmPrinter::getModuleCFISectionType () const inline
Get the CFISection type for the module.
Definition at line 491 of file AsmPrinter.h.
getNameWithPrefix()
void AsmPrinter::getNameWithPrefix (SmallVectorImpl< char > & Name, const GlobalValue * GV) const
Definition at line 726 of file AsmPrinter.cpp.
References getObjFileLowering(), and TM.
Referenced by llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), and llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel().
getObjFileLowering()
const TargetLoweringObjectFile & AsmPrinter::getObjFileLowering () const
Return information about object file lowering.
Definition at line 438 of file AsmPrinter.cpp.
References TM.
Referenced by computeGlobalGOTEquivs(), llvm::AMDGPUAsmPrinter::doFinalization(), doFinalization(), emitBasicBlockStart(), emitBBAddrMapSection(), emitCallGraphSection(), emitConstantPool(), llvm::XtensaAsmPrinter::emitConstantPool(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), emitGlobalAlias(), emitGlobalConstantImpl(), emitGlobalGOTEquivs(), emitGlobalVariable(), llvm::BPFAsmPrinter::emitJumpTableInfo(), emitKCFITrapEntry(), emitPCSections(), emitStackSizeSection(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), emitTTypeReference(), emitXXStructorList(), llvm::SystemZAsmPrinter::emitXXStructorList(), GetCPISymbol(), getNameWithPrefix(), getSymbolWithGlobalValueBase(), handleIndirectSymViaGOTPCRel(), lowerConstant(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
getPointerSize()
unsigned AsmPrinter::getPointerSize () const
Return the pointer size from the TargetMachine.
Definition at line 449 of file AsmPrinter.cpp.
References TM.
Referenced by emitBBAddrMapSection(), emitPatchableFunctionEntries(), emitPCSections(), and llvm::SystemZAsmPrinter::SystemZAsmPrinter().
GetSizeOfEncodedValue()
unsigned AsmPrinter::GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
GetSizeOfEncodedValue - Return the size of the encoding in bytes.
Definition at line 102 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_omit, llvm::dwarf::DW_EH_PE_udata2, llvm::dwarf::DW_EH_PE_udata4, llvm::dwarf::DW_EH_PE_udata8, llvm_unreachable, and MAI.
Referenced by emitCallSiteOffset(), emitCallSiteValue(), and emitTTypeReference().
getSubtargetInfo()
const MCSubtargetInfo & AsmPrinter::getSubtargetInfo () const
Return information about subtarget.
Definition at line 453 of file AsmPrinter.cpp.
References assert(), and MF.
Referenced by emitAlignment(), llvm::X86AsmPrinter::emitBasicBlockEnd(), emitFunctionBody(), llvm::ARMAsmPrinter::emitInstruction(), llvm::BPFAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::LoongArchAsmPrinter::emitInstruction(), llvm::M68kAsmPrinter::emitInstruction(), llvm::R600AsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::LoongArchAsmPrinter::emitSled(), EmitToStreamer(), GetCPISymbol(), and llvm::HexagonAsmPrinter::HexagonProcessInstruction().
getSymbol()
MCSymbol * AsmPrinter::getSymbol (const GlobalValue * GV) const
Definition at line 731 of file AsmPrinter.cpp.
References TM.
Referenced by computeGlobalGOTEquivs(), doFinalization(), emitCallGraphSection(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::EmitFunctionAttributes(), emitGlobalAlias(), emitGlobalAliasInline(), emitGlobalConstant(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), emitSpecialLLVMGlobal(), emitXXStructorList(), llvm::SystemZAsmPrinter::emitXXStructorList(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), getMCSymbolForTOCPseudoMO(), GetSymbolFromOperand(), handleCallsiteForCallgraph(), handleIndirectSymViaGOTPCRel(), llvm::HexagonLowerToMC(), lowerConstant(), LowerOperand(), llvm::XtensaAsmPrinter::LowerSymbolOperand(), llvm::BPFAsmPrinter::printOperand(), SetupMachineFunction(), and smallData().
getSymbolPreferLocal()
MCSymbol * AsmPrinter::getSymbolPreferLocal (const GlobalValue & GV) const
Similar to getSymbol() but preferred for references.
On ELF, this uses a local symbol if a reference to GV is guaranteed to be resolved to the definition in the same module.
Definition at line 735 of file AsmPrinter.cpp.
References llvm::GlobalValue::canBenefitFromLocalAlias(), llvm::PIELevel::Default, llvm::GlobalValue::getParent(), getSymbolWithGlobalValueBase(), llvm::GlobalValue::isDSOLocal(), llvm::Reloc::Static, and TM.
Referenced by emitFunctionEntryLabel(), emitGlobalAlias(), emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::lowerLoongArchMachineOperandToMCOperand(), and PrintSymbolOperand().
getSymbolWithGlobalValueBase()
MCSymbol * AsmPrinter::getSymbolWithGlobalValueBase (const GlobalValue * GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
Definition at line 4489 of file AsmPrinter.cpp.
References getObjFileLowering(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), and TM.
Referenced by getSymbolPreferLocal().
getUnitLengthFieldByteSize()
unsigned int AsmPrinter::getUnitLengthFieldByteSize () const
Returns 4 for DWARF32 and 12 for DWARF64.
Definition at line 4985 of file AsmPrinter.cpp.
References llvm::dwarf::getUnitLengthFieldByteSize(), and OutStreamer.
handleCallsiteForCallgraph()
void AsmPrinter::handleCallsiteForCallgraph (FunctionCallGraphInfo & FuncCGInfo, const MachineFunction::CallSiteInfoMap & CallSitesInfoMap, const MachineInstr & MI)
If MI is an indirect call, add expected type IDs to indirect type ids list.
If MI is a direct call add the callee symbol to direct callsites list of FuncCGInfo.
Definition at line 1927 of file AsmPrinter.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm::ConstantInt::getZExtValue(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isSymbol(), llvm_unreachable, MI, llvm::MachineOperand::MO_ExternalSymbol, and llvm::MachineOperand::MO_GlobalAddress.
Referenced by emitFunctionBody().
hasDebugInfo()
bool llvm::AsmPrinter::hasDebugInfo () const inline
Returns true if valid debug info is present.
Definition at line 494 of file AsmPrinter.h.
Referenced by llvm::NVPTXAsmPrinter::doFinalization(), doInitialization(), and getFunctionCFISectionType().
isBlockOnlyReachableByFallthrough()
bool AsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const virtual
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented in llvm::HexagonAsmPrinter.
Definition at line 4710 of file AsmPrinter.cpp.
References MBB, MI, and OP.
Referenced by llvm::AMDGPUAsmPrinter::emitBasicBlockStart(), and llvm::HexagonAsmPrinter::isBlockOnlyReachableByFallthrough().
isDwarf64()
bool AsmPrinter::isDwarf64 () const
Definition at line 4970 of file AsmPrinter.cpp.
References llvm::dwarf::DWARF64, and OutStreamer.
Referenced by emitDwarfLengthOrOffset(), and emitDwarfSymbolReference().
isPositionIndependent()
bool AsmPrinter::isPositionIndependent () const
Definition at line 429 of file AsmPrinter.cpp.
References TM.
Referenced by llvm::ARMAsmPrinter::emitJumpTableAddrs(), and llvm::MipsAsmPrinter::emitStartOfAsmFile().
isVerbose()
bool llvm::AsmPrinter::isVerbose () const inline
Return true if assembly output should contain comments.
Definition at line 295 of file AsmPrinter.h.
Referenced by emitBasicBlockStart(), emitDwarfDIE(), emitEncodingByte(), emitFunctionBody(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::WebAssemblyAsmPrinter::emitInstruction(), emitSLEB128(), emitULEB128(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and llvm::R600AsmPrinter::runOnMachineFunction().
lowerBlockAddressConstant()
const MCExpr * AsmPrinter::lowerBlockAddressConstant (const BlockAddress & BA) virtual
Lower the specified BlockAddress to an MCExpr.
Definition at line 4441 of file AsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create(), GetBlockAddressSymbol(), and OutContext.
Referenced by lowerConstant().
lowerConstant()
const MCExpr * AsmPrinter::lowerConstant (const Constant * CV, const Constant * BaseCV = nullptr, uint64_t Offset = 0) virtual
Lower the specified LLVM Constant to an MCExpr.
When BaseCV is present, we are lowering the element at BaseCV plus Offset.
Reimplemented in llvm::AMDGPUAsmPrinter, and llvm::R600AsmPrinter.
Definition at line 3699 of file AsmPrinter.cpp.
References llvm::sampleprof::Base, llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldConstant(), llvm::ConstantFoldIntegerCast(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), DL, llvm::dyn_cast(), getDataLayout(), getObjFileLowering(), llvm::APInt::getSExtValue(), getSymbol(), llvm::Value::getType(), llvm::isa(), llvm::IsConstantOffsetFromGlobal(), llvm::Constant::isNullValue(), llvm_unreachable, lowerBlockAddressConstant(), lowerConstant(), lowerConstantPtrAuth(), llvm::TargetLoweringObjectFile::lowerDSOLocalEquivalent(), llvm::TargetLoweringObjectFile::lowerRelativeReference(), MF, NC, llvm::Offset, OutContext, and TM.
Referenced by llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), emitGlobalAlias(), emitGlobalConstantImpl(), llvm::XtensaAsmPrinter::emitMachineConstantPoolEntry(), llvm::AMDGPUAsmPrinter::lowerConstant(), lowerConstant(), and llvm::R600AsmPrinter::lowerConstant().
lowerConstantPtrAuth()
virtual const MCExpr * llvm::AsmPrinter::lowerConstantPtrAuth (const ConstantPtrAuth & CPA) inline virtual
Definition at line 640 of file AsmPrinter.h.
References llvm::report_fatal_error().
Referenced by lowerConstant().
needsSEHMoves()
bool AsmPrinter::needsSEHMoves ()
Definition at line 1362 of file AsmPrinter.cpp.
References MAI, and MF.
preprocessXXStructorList()
void AsmPrinter::preprocessXXStructorList (const DataLayout & DL, const Constant * List, SmallVector< Structor, 8 > & Structors)
This method gathers an array of Structors and then sorts them out by Priority.
Parameters
List The initializer of llvm.global_ctors or llvm.global_dtors array.
[out] Structors Sorted Structor structs by Priority.
Definition at line 3486 of file AsmPrinter.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::cast(), llvm::AsmPrinter::Structor::ComdatKey, DL, llvm::dyn_cast(), llvm::AsmPrinter::Structor::Func, llvm::ConstantInt::getLimitedValue(), llvm::User::getOperand(), llvm::isa(), llvm::AsmPrinter::Structor::Priority, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::stable_sort(), and TM.
Referenced by emitXXStructorList(), and llvm::SystemZAsmPrinter::emitXXStructorList().
PrintAsmMemoryOperand()
bool AsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented in llvm::ARMAsmPrinter, llvm::BPFAsmPrinter, llvm::CSKYAsmPrinter, llvm::HexagonAsmPrinter, llvm::LoongArchAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::SystemZAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::X86AsmPrinter, and llvm::XtensaAsmPrinter.
Definition at line 513 of file AsmPrinterInlineAsm.cpp.
References MI.
Referenced by EmitInlineAsmStr(), llvm::CSKYAsmPrinter::PrintAsmMemoryOperand(), llvm::M68kAsmPrinter::PrintAsmMemoryOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmMemoryOperand(), and PrintAsmOperand().
PrintAsmOperand()
bool AsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & O) virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate for machine specific ExtraCodes or when the arch-independent handling would be too complex otherwise.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::BPFAsmPrinter, llvm::CSKYAsmPrinter, llvm::HexagonAsmPrinter, llvm::LoongArchAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::SystemZAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::X86AsmPrinter, and llvm::XtensaAsmPrinter.
Definition at line 471 of file AsmPrinterInlineAsm.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), MI, PrintAsmMemoryOperand(), and PrintSymbolOperand().
Referenced by EmitInlineAsmStr(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::BPFAsmPrinter::PrintAsmOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::LoongArchAsmPrinter::PrintAsmOperand(), llvm::M68kAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::X86AsmPrinter::PrintAsmOperand(), and llvm::XtensaAsmPrinter::PrintAsmOperand().
printOffset()
void AsmPrinter::printOffset (int64_t Offset, raw_ostream & OS) const
This is just convenient handler for printing offsets.
Definition at line 4411 of file AsmPrinter.cpp.
References llvm::Offset.
Referenced by llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintSymbolOperand(), and PrintSymbolOperand().
PrintSpecial()
void AsmPrinter::PrintSpecial (const MachineInstr * MI, raw_ostream & OS, StringRef Code) const virtual
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
PrintSpecial - Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
This can be useful for portably encoding the comment character or other bits of target-specific knowledge into the asmstrings. The syntax used is ${:comment}. Targets can override this to add support for their own strange codes.
Definition at line 434 of file AsmPrinterInlineAsm.cpp.
References DL, getFunctionNumber(), MAI, MF, MI, llvm::report_fatal_error(), and llvm::raw_string_ostream::str().
Referenced by EmitInlineAsmStr().
PrintSymbolOperand()
void AsmPrinter::PrintSymbolOperand (const MachineOperand & MO, raw_ostream & OS) virtual
Print the MachineOperand as a symbol.
Targets with complex handling of symbol references should override the base implementation.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 461 of file AsmPrinterInlineAsm.cpp.
References assert(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getOffset(), getSymbolPreferLocal(), llvm::MachineOperand::isGlobal(), MAI, llvm::MCSymbol::print(), and printOffset().
Referenced by llvm::M68kAsmPrinter::PrintAsmMemoryOperand(), PrintAsmOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::LoongArchAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::printOperand(), and llvm::MipsAsmPrinter::printOperand().
recordSled()
void AsmPrinter::recordSled (MCSymbol * Sled, const MachineInstr & MI, SledKind Kind, uint8_t Version = 0)
Definition at line 4908 of file AsmPrinter.cpp.
References CurrentFnSym, F, FUNCTION_ENTER, LOG_ARGS_ENTER, MI, Sleds, and llvm::Version.
Referenced by llvm::HexagonAsmPrinter::EmitSled(), and llvm::LoongArchAsmPrinter::emitSled().
runOnMachineFunction()
bool llvm::AsmPrinter::runOnMachineFunction (MachineFunction & MF) inline override virtual
Emit the specified function out to the OutStreamer.
Implements llvm::MachineFunctionPass.
Reimplemented in llvm::CSKYAsmPrinter, llvm::HexagonAsmPrinter, llvm::LoongArchAsmPrinter, llvm::M68kAsmPrinter, llvm::MipsAsmPrinter, llvm::NVPTXAsmPrinter, llvm::R600AsmPrinter, llvm::SystemZAsmPrinter, llvm::WebAssemblyAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 441 of file AsmPrinter.h.
References emitFunctionBody(), MF, and SetupMachineFunction().
Referenced by llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::HexagonAsmPrinter::runOnMachineFunction(), llvm::LoongArchAsmPrinter::runOnMachineFunction(), llvm::M68kAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::NVPTXAsmPrinter::runOnMachineFunction(), llvm::SystemZAsmPrinter::runOnMachineFunction(), and llvm::WebAssemblyAsmPrinter::runOnMachineFunction().
setDwarfUsesRelocationsAcrossSections()
void llvm::AsmPrinter::setDwarfUsesRelocationsAcrossSections (bool Enable) inline
Definition at line 368 of file AsmPrinter.h.
References Enable.
setDwarfVersion()
void AsmPrinter::setDwarfVersion (uint16_t Version)
Definition at line 4966 of file AsmPrinter.cpp.
References OutStreamer, and llvm::Version.
SetupMachineFunction()
void AsmPrinter::SetupMachineFunction (MachineFunction & MF) virtual
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
Definition at line 3031 of file AsmPrinter.cpp.
References assert(), createTempSymbol(), CurrentFnBegin, CurrentFnBeginLocal, CurrentFnCallsiteEndSymbols, CurrentFnDescSym, CurrentFnSym, CurrentFnSymForSize, F, llvm::Pass::getAnalysis(), llvm::TargetLoweringObjectFile::getFunctionEntryPointSymbol(), getObjFileLowering(), getSymbol(), MAI, MBBSectionRanges, MF, needFuncLabels(), ORE, and TM.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), and llvm::X86AsmPrinter::runOnMachineFunction().
shouldEmitWeakSwiftAsyncExtendedFramePointerFlags()
virtual bool llvm::AsmPrinter::shouldEmitWeakSwiftAsyncExtendedFramePointerFlags () const inline protected virtual
Reimplemented in llvm::X86AsmPrinter.
Definition at line 988 of file AsmPrinter.h.
Referenced by doFinalization().
takeDeletedSymbolsForFunction()
void AsmPrinter::takeDeletedSymbolsForFunction (const Function * F, std::vector< MCSymbol * > & Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
This prevents emitting a reference to a symbol that has no definition.
Definition at line 319 of file AsmPrinter.cpp.
References F.
usesCFIWithoutEH()
bool AsmPrinter::usesCFIWithoutEH () const
Since emitting CFI unwind information is entangled with supporting the exceptions, this returns true for platforms which use CFI unwind information for other purposes (debugging, sanitizers, ...) when MCAsmInfo::ExceptionsType == ExceptionHandling::None.
Definition at line 1366 of file AsmPrinter.cpp.
References MAI, and None.
Referenced by doInitialization(), and emitCFIInstruction().
Member Data Documentation
CurrentFnBegin
MCSymbol* llvm::AsmPrinter::CurrentFnBegin = nullptr protected
Definition at line 220 of file AsmPrinter.h.
Referenced by emitFunctionBody(), llvm::X86AsmPrinter::emitInstruction(), emitXRayTable(), getFunctionBegin(), and SetupMachineFunction().
CurrentFnBeginLocal
MCSymbol* llvm::AsmPrinter::CurrentFnBeginLocal = nullptr protected
For dso_local functions, the current $local alias for the function.
Definition at line 223 of file AsmPrinter.h.
Referenced by emitFunctionBody(), emitFunctionEntryLabel(), and SetupMachineFunction().
CurrentFnCallsiteEndSymbols
DenseMap<const MachineBasicBlock *, SmallVector<MCSymbol *, 1> > llvm::AsmPrinter::CurrentFnCallsiteEndSymbols
Vector of symbols marking the end of the callsites in the current function, keyed by their containing basic block.
The callsite symbols of each block are stored in the order they appear in that block.
Definition at line 144 of file AsmPrinter.h.
Referenced by createCallsiteEndSymbol(), emitBBAddrMapSection(), and SetupMachineFunction().
CurrentFnDescSym
MCSymbol* llvm::AsmPrinter::CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
This is created at the beginning of each call to SetupMachineFunction().
Definition at line 132 of file AsmPrinter.h.
Referenced by SetupMachineFunction().
CurrentFnSym
MCSymbol* llvm::AsmPrinter::CurrentFnSym = nullptr
The symbol for the current function.
This is recalculated at the beginning of each call to runOnMachineFunction().
Definition at line 128 of file AsmPrinter.h.
Referenced by emitFunctionBody(), llvm::MipsAsmPrinter::emitFunctionBodyEnd(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::X86AsmPrinter::emitFunctionBodyStart(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), llvm::MipsAsmPrinter::emitFunctionEntryLabel(), emitPatchableFunctionEntries(), emitXRayTable(), recordSled(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
CurrentFnSymForSize
MCSymbol* llvm::AsmPrinter::CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
using the .size directive). By default, this is equal to CurrentFnSym.
Definition at line 137 of file AsmPrinter.h.
Referenced by emitFunctionBody(), and SetupMachineFunction().
CurrentPatchableFunctionEntrySym
MCSymbol* llvm::AsmPrinter::CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
Definition at line 124 of file AsmPrinter.h.
Referenced by llvm::X86AsmPrinter::emitInstruction(), and emitPatchableFunctionEntries().
EHHandlers
SmallVector<std::unique_ptr<AsmPrinterHandler>, 1> llvm::AsmPrinter::EHHandlers protected
A handle to the EH info emitter (if present).
Definition at line 228 of file AsmPrinter.h.
Referenced by doFinalization(), doInitialization(), emitBasicBlockEnd(), emitBasicBlockStart(), and emitFunctionBody().
GlobalGOTEquivs
MapVector<const MCSymbol *, GOTEquivUsePair> llvm::AsmPrinter::GlobalGOTEquivs
Definition at line 163 of file AsmPrinter.h.
Referenced by computeGlobalGOTEquivs(), emitGlobalGOTEquivs(), emitGlobalVariable(), and handleIndirectSymViaGOTPCRel().
Handlers
SmallVector<std::unique_ptr<AsmPrinterHandler>, 2> llvm::AsmPrinter::Handlers protected
Definition at line 233 of file AsmPrinter.h.
Referenced by addAsmPrinterHandler(), doFinalization(), doInitialization(), llvm::BPFAsmPrinter::doInitialization(), emitBasicBlockEnd(), emitBasicBlockStart(), emitFunctionBody(), emitGlobalVariable(), and ~AsmPrinter().
MAI
const MCAsmInfo* llvm::AsmPrinter::MAI = nullptr
Target Asm Printer information.
Definition at line 97 of file AsmPrinter.h.
Referenced by AsmPrinter(), doFinalization(), doInitialization(), llvm::BPFAsmPrinter::doInitialization(), emitBasicBlockStart(), emitCFIInstruction(), emitDwarfSymbolReference(), llvm::X86AsmPrinter::emitEndOfAsmFile(), emitFunctionBody(), emitGlobalAlias(), emitGlobalConstant(), emitGlobalVariable(), EmitInlineAsmStr(), emitJumpTableEntry(), llvm::X86AsmPrinter::emitKCFITypeId(), emitLabelPlusOffset(), emitLinkage(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), emitPatchableFunctionEntries(), emitSpecialLLVMGlobal(), emitVisibility(), emitXRayTable(), getDwarfFormParams(), getFunctionCFISectionType(), GetSizeOfEncodedValue(), needsSEHMoves(), printAddress(), llvm::LoongArchAsmPrinter::PrintAsmMemoryOperand(), llvm::M68kAsmPrinter::PrintAsmMemoryOperand(), llvm::SystemZAsmPrinter::PrintAsmMemoryOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), printFormattedRegName(), llvm::ARMAsmPrinter::printOperand(), llvm::HexagonAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), printOperand(), printReg(), PrintSpecial(), llvm::ARMAsmPrinter::PrintSymbolOperand(), PrintSymbolOperand(), SetupMachineFunction(), and usesCFIWithoutEH().
MBBSectionRanges
MapVector<MBBSectionID, MBBSectionRange> llvm::AsmPrinter::MBBSectionRanges
Definition at line 158 of file AsmPrinter.h.
Referenced by emitBBAddrMapSection(), emitFunctionBody(), and SetupMachineFunction().
MDT
MachineDominatorTree* llvm::AsmPrinter::MDT = nullptr
This is a pointer to the current MachineDominatorTree.
Definition at line 115 of file AsmPrinter.h.
Referenced by emitFunctionBody().
MF
MachineFunction* llvm::AsmPrinter::MF = nullptr
The current machine function.
Definition at line 109 of file AsmPrinter.h.
Referenced by createCallsiteEndSymbol(), doFinalization(), emitAlignment(), emitBasicBlockStart(), emitBBAddrMapSection(), emitCallGraphSection(), emitCFIInstruction(), emitConstantPool(), llvm::WebAssemblyAsmPrinter::emitConstantPool(), llvm::XtensaAsmPrinter::emitConstantPool(), llvm::DwarfDebug::emitDebugLocValue(), emitDebugValueComment(), emitFakeUse(), llvm::MipsAsmPrinter::emitFrameDirective(), emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::MipsAsmPrinter::emitFunctionBodyStart(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::X86AsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPUAsmPrinter::emitImplicitDef(), emitImplicitDef(), emitInitialRawDwarfLocDirective(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::R600AsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), emitJumpTableEntry(), emitJumpTableInfo(), llvm::BPFAsmPrinter::emitJumpTableInfo(), llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitKCFITrapEntry(), emitKCFITypeId(), llvm::X86AsmPrinter::emitKCFITypeId(), emitKill(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitNops(), emitPatchableFunctionEntries(), emitPCSections(), emitPCSectionsLabel(), emitStackSizeSection(), emitStackUsage(), emitXRayTable(), getCodeViewJumpTableInfo(), GetCPISymbol(), getFunctionCFISectionType(), getFunctionNumber(), GetJTISymbol(), llvm::BPFAsmPrinter::getJTPublicSymbol(), getSubtargetInfo(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), lowerConstant(), llvm::AMDGPUAsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LoongArchAsmPrinter::LowerPATCHABLE_FUNCTION_ENTER(), llvm::CSKYAsmPrinter::lowerPseudoInstExpansion(), needsSEHMoves(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), PrintSpecial(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), runOnMachineFunction(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::LoongArchAsmPrinter::runOnMachineFunction(), llvm::M68kAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::SystemZAsmPrinter::runOnMachineFunction(), llvm::WebAssemblyAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
MLI
MachineLoopInfo* llvm::AsmPrinter::MLI = nullptr
This is a pointer to the current MachineLoopInfo.
Definition at line 118 of file AsmPrinter.h.
Referenced by emitBasicBlockStart(), and emitFunctionBody().
MMI
MachineModuleInfo* llvm::AsmPrinter::MMI = nullptr
This is a pointer to the current MachineModuleInfo.
Definition at line 112 of file AsmPrinter.h.
Referenced by doFinalization(), doInitialization(), emitCOFFFeatureSymbol(), emitCOFFReplaceableFunctionData(), llvm::WebAssemblyAsmPrinter::emitConstantPool(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), emitFunctionBody(), llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::X86AsmPrinter::emitStartOfAsmFile(), emitTTypeReference(), getCodeViewJumpTableInfo(), getDataLayout(), and handleIndirectSymViaGOTPCRel().
NumUserHandlers
size_t llvm::AsmPrinter::NumUserHandlers = 0 protected
Definition at line 234 of file AsmPrinter.h.
Referenced by addAsmPrinterHandler(), doFinalization(), and ~AsmPrinter().
ORE
MachineOptimizationRemarkEmitter* llvm::AsmPrinter::ORE = nullptr
Optimization remark emitter.
Definition at line 121 of file AsmPrinter.h.
Referenced by emitFunctionBody(), and SetupMachineFunction().
OutContext
MCContext& llvm::AsmPrinter::OutContext
This is the context for the output file that we are streaming.
This owns all of the global MC-related objects for the generated translation unit.
Definition at line 101 of file AsmPrinter.h.
Referenced by AsmPrinter(), createTempSymbol(), llvm::CSKYAsmPrinter::CSKYAsmPrinter(), llvm::AMDGPUAsmPrinter::doFinalization(), doFinalization(), doInitialization(), EmitCamlGlobal(), emitCOFFReplaceableFunctionData(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::MipsAsmPrinter::emitEndOfAsmFile(), llvm::SystemZAsmPrinter::emitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), emitFrameAlloc(), llvm::WebAssemblyAsmPrinter::EmitFunctionAttributes(), emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), emitGlobalAlias(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::BPFAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::R600AsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::WebAssemblyAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), emitJumpTableEntry(), llvm::BPFAsmPrinter::emitJumpTableInfo(), llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitKCFITrapEntry(), llvm::X86AsmPrinter::emitKCFITypeId(), emitLabelPlusOffset(), llvm::XtensaAsmPrinter::emitMachineConstantPoolEntry(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), EmitNop(), emitPatchableFunctionEntries(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), emitRemarksSection(), llvm::HexagonAsmPrinter::EmitSled(), llvm::LoongArchAsmPrinter::emitSled(), emitSpecialLLVMGlobal(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), emitXRayTable(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::SystemZAsmPrinter::emitXXStructorList(), getAddrLabelSymbolToEmit(), llvm::ARMAsmPrinter::GetCPISymbol(), GetCPISymbol(), GetExternalSymbolSymbol(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), GetJTISymbol(), llvm::BPFAsmPrinter::getJTPublicSymbol(), GetJTSetSymbol(), llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol(), GetSymbolFromOperand(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), lowerBlockAddressConstant(), llvm::AMDGPUAsmPrinter::lowerConstant(), lowerConstant(), llvm::R600AsmPrinter::lowerConstant(), llvm::AMDGPUAsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), llvm::XtensaAsmPrinter::LowerSymbolOperand(), LowerSymbolOperand(), lowerSymbolOperand(), lowerSymbolOperand(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and smallData().
OutStreamer
std::unique_ptr<MCStreamer> llvm::AsmPrinter::OutStreamer
This is the MCStreamer object for the file we are generating.
This contains the transient state for the current translation unit that we are generating (such as the current section etc).
Definition at line 106 of file AsmPrinter.h.
Referenced by llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), AsmPrinter(), llvm::AMDGPUAsmPrinter::doFinalization(), doFinalization(), llvm::NVPTXAsmPrinter::doFinalization(), doInitialization(), llvm::DIEAbbrevSet::Emit(), emitAlignment(), llvm::X86AsmPrinter::emitBasicBlockEnd(), emitBasicBlockLoopComments(), emitBasicBlockStart(), emitBBAddrMapSection(), emitCallGraphSection(), emitCallSiteValue(), EmitCamlGlobal(), emitCFIInstruction(), emitCOFFFeatureSymbol(), emitCOFFReplaceableFunctionData(), emitConstantPool(), llvm::XtensaAsmPrinter::emitConstantPool(), emitDebugLabelComment(), emitDebugValue(), emitDebugValueComment(), emitDwarfDIE(), emitDwarfLengthOrOffset(), emitDwarfStringOffset(), emitDwarfSymbolReference(), emitDwarfUnitLength(), emitDwarfUnitLength(), emitEncodingByte(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::CSKYAsmPrinter::emitEndOfAsmFile(), llvm::HexagonAsmPrinter::emitEndOfAsmFile(), llvm::MipsAsmPrinter::emitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), emitFakeUse(), emitFrameAlloc(), llvm::WebAssemblyAsmPrinter::EmitFunctionAttributes(), emitFunctionBody(), llvm::ARMAsmPrinter::emitFunctionBodyEnd(), llvm::MipsAsmPrinter::emitFunctionBodyEnd(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), llvm::X86AsmPrinter::emitFunctionBodyEnd(), llvm::X86AsmPrinter::emitFunctionBodyStart(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), llvm::MipsAsmPrinter::emitFunctionEntryLabel(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), emitGlobalAlias(), emitGlobalAliasInline(), emitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitImplicitDef(), emitImplicitDef(), emitInitialRawDwarfLocDirective(), llvm::ARMAsmPrinter::emitInlineAsmEnd(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::BPFAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::LoongArchAsmPrinter::emitInstruction(), llvm::M68kAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::R600AsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::WebAssemblyAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::XtensaAsmPrinter::emitInstruction(), emitInt16(), emitInt32(), emitInt64(), emitInt8(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), emitJumpTableEntry(), llvm::BPFAsmPrinter::emitJumpTableInfo(), llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitKCFITrapEntry(), llvm::X86AsmPrinter::emitKCFITypeId(), emitKill(), emitLabelDifference(), emitLabelDifferenceAsULEB128(), emitLabelPlusOffset(), emitLinkage(), llvm::XtensaAsmPrinter::emitMachineConstantPoolEntry(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), EmitNop(), emitNops(), emitPatchableFunctionEntries(), emitPCSections(), emitPCSectionsLabel(), emitPPA1Flags(), emitPPA1Name(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), emitRemarksSection(), emitSLEB128(), llvm::HexagonAsmPrinter::EmitSled(), llvm::LoongArchAsmPrinter::emitSled(), emitSpecialLLVMGlobal(), emitStackSizeSection(), llvm::ARMAsmPrinter::emitStartOfAsmFile(), llvm::M68kAsmPrinter::emitStartOfAsmFile(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), llvm::CSKYAsmPrinter::EmitToStreamer(), emitTTypeReference(), emitULEB128(), llvm::DIEEntry::emitValue(), llvm::DIEInlineString::emitValue(), emitVisibility(), emitXRayTable(), llvm::ARMAsmPrinter::emitXXStructor(), emitXXStructorList(), llvm::SystemZAsmPrinter::emitXXStructorList(), GetCPISymbol(), getCurrentSection(), getDwarfFormParams(), getDwarfOffsetByteSize(), getDwarfVersion(), llvm::AMDGPUAsmPrinter::getTargetStreamer(), llvm::WebAssemblyAsmPrinter::getTargetStreamer(), getUnitLengthFieldByteSize(), handleIndirectSymViaGOTPCRel(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), isDwarf64(), llvm::LoongArchAsmPrinter::LowerSTATEPOINT(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::NVPTXAsmPrinter::runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and setDwarfVersion().
PSI
const ProfileSummaryInfo* llvm::AsmPrinter::PSI = nullptr
The profile summary information.
Definition at line 150 of file AsmPrinter.h.
Referenced by getConstantSectionSuffix(), and llvm::X86AsmPrinter::runOnMachineFunction().
SDPI
const StaticDataProfileInfo* llvm::AsmPrinter::SDPI = nullptr
Provides the profile information for constants.
Definition at line 147 of file AsmPrinter.h.
Referenced by getConstantSectionSuffix(), and llvm::X86AsmPrinter::runOnMachineFunction().
Sleds
SmallVector<XRayFunctionEntry, 4> llvm::AsmPrinter::Sleds
Definition at line 414 of file AsmPrinter.h.
Referenced by emitXRayTable(), and recordSled().
SM
StackMaps llvm::AsmPrinter::SM protected
Definition at line 236 of file AsmPrinter.h.
Referenced by AsmPrinter(), llvm::SystemZAsmPrinter::doInitialization(), llvm::X86AsmPrinter::doInitialization(), emitStackMaps(), and llvm::LoongArchAsmPrinter::LowerSTATEPOINT().
TM
TargetMachine& llvm::AsmPrinter::TM
Target machine description.
Definition at line 94 of file AsmPrinter.h.
Referenced by llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), llvm::ARMAsmPrinter::ARMAsmPrinter(), AsmPrinter(), llvm::CSKYAsmPrinter::CSKYAsmPrinter(), doFinalization(), llvm::AMDGPUAsmPrinter::doInitialization(), doInitialization(), llvm::NVPTXAsmPrinter::doInitialization(), emitAlignment(), emitBasicBlockStart(), emitCallGraphSection(), emitCOFFFeatureSymbol(), emitCOFFReplaceableFunctionData(), llvm::XtensaAsmPrinter::emitConstantPool(), llvm::DwarfDebug::emitDebugLocValue(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::AMDGPUAsmPrinter::emitEndOfAsmFile(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::CSKYAsmPrinter::emitEndOfAsmFile(), llvm::HexagonAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), emitGlobalAlias(), emitGlobalConstantImpl(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), emitJumpTableInfo(), llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitPatchableFunctionEntries(), emitStackSizeSection(), llvm::ARMAsmPrinter::emitStartOfAsmFile(), llvm::CSKYAsmPrinter::emitStartOfAsmFile(), llvm::HexagonAsmPrinter::emitStartOfAsmFile(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::SystemZAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), emitTTypeReference(), emitXRayTable(), llvm::ARMAsmPrinter::emitXXStructor(), emitXXStructorList(), llvm::SystemZAsmPrinter::emitXXStructorList(), getConstantSectionSuffix(), GetCPISymbol(), llvm::MipsAsmPrinter::getCurrentABIString(), getFunctionCFISectionType(), llvm::AMDGPUAsmPrinter::getGlobalSTI(), llvm::ARMAsmPrinter::getISAEncoding(), getNameWithPrefix(), getObjFileLowering(), getPointerSize(), getSymbol(), getSymbolPreferLocal(), getSymbolWithGlobalValueBase(), llvm::ARMAsmPrinter::getTM(), llvm::HexagonAsmPrinter::HexagonAsmPrinter(), isPositionIndependent(), llvm::LoongArchAsmPrinter::LoongArchAsmPrinter(), llvm::AMDGPUAsmPrinter::lowerConstant(), lowerConstant(), llvm::R600AsmPrinter::lowerConstant(), llvm::M68kAsmPrinter::M68kAsmPrinter(), llvm::MipsAsmPrinter::MipsAsmPrinter(), llvm::NVPTXAsmPrinter::NVPTXAsmPrinter(), preprocessXXStructorList(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::R600AsmPrinter::R600AsmPrinter(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), SetupMachineFunction(), llvm::SystemZAsmPrinter::SystemZAsmPrinter(), llvm::WebAssemblyAsmPrinter::WebAssemblyAsmPrinter(), llvm::X86AsmPrinter::X86AsmPrinter(), and llvm::XtensaAsmPrinter::XtensaAsmPrinter().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AsmPrinter.h
lib/CodeGen/AsmPrinter/AsmPrinter.cpp
lib/CodeGen/AsmPrinter/AsmPrinterDwarf.cpp
lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp