LLVM: llvm::vfs::OutputError Class Reference
llvm::vfs::OutputError Class Reference
Error related to an OutputFile.
#include "llvm/Support/VirtualOutputError.h"
Public Member Functions
StringRef getOutputPath () const
void log (raw_ostream &OS) const override
Print an error message to an output stream.
OutputError (const Twine &OutputPath, std::error_code EC)
OutputError (const Twine &OutputPath, OutputErrorCode EV)
Public Member Functions inherited from llvm::ErrorInfo< OutputError, ECError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ECError
void setErrorCode (std::error_code EC)
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual std::string message () const
Return the error message as a string.
template<typename ErrorInfoT>
bool isA () const
Static Public Attributes
static LLVM_ABI char ID = 0
Static Public Attributes inherited from llvm::ECError
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< OutputError, ECError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfo< ECError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Protected Member Functions inherited from llvm::ECError
ECError ()=default
ECError (std::error_code EC)
Protected Attributes inherited from llvm::ECError
std::error_code EC
Detailed Description
Error related to an OutputFile.
Derives from ECError and adds getOutputPath().
Definition at line 38 of file VirtualOutputError.h.
Constructor & Destructor Documentation
OutputError() [1/2]
llvm::vfs::OutputError::OutputError (const Twine & OutputPath, std::error_code EC) inline
Definition at line 48 of file VirtualOutputError.h.
References assert(), llvm::ECError::EC, llvm::ECError::ECError(), and OutputError().
Referenced by OutputError(), and OutputError().
OutputError() [2/2]
llvm::vfs::OutputError::OutputError (const Twine & OutputPath, OutputErrorCode EV) inline
Definition at line 53 of file VirtualOutputError.h.
References assert(), llvm::ECError::EC, llvm::ECError::ECError(), llvm::vfs::make_error_code(), and OutputError().
Member Function Documentation
getOutputPath()
StringRef llvm::vfs::OutputError::getOutputPath () const inline
Definition at line 42 of file VirtualOutputError.h.
Referenced by log().
log()
void OutputError::log (raw_ostream & OS) const override virtual
Print an error message to an output stream.
Reimplemented from llvm::ECError.
Definition at line 27 of file VirtualOutputError.cpp.
References getOutputPath(), and llvm::ECError::log().
Referenced by llvm::vfs::OutputConfigError::log(), and llvm::vfs::TempFileOutputError::log().
Member Data Documentation
ID
char OutputError::ID = 0 static
Definition at line 46 of file VirtualOutputError.h.
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualOutputError.h
lib/Support/VirtualOutputError.cpp