LLVM: llvm::orc::BloomFilterBuilder Class Reference
llvm::orc::BloomFilterBuilder Class Reference
#include "llvm/ExecutionEngine/Orc/Shared/SymbolFilter.h"
Public Types
using HashFunc = BloomFilter::HashFunc
Public Member Functions
BloomFilterBuilder ()=default
BloomFilterBuilder & setFalsePositiveRate (float Rate)
BloomFilterBuilder & setHashFunction (HashFunc Fn)
BloomFilter build (ArrayRef< StringRef > Symbols) const
Detailed Description
Definition at line 97 of file SymbolFilter.h.
Member Typedef Documentation
HashFunc
using llvm::orc::BloomFilterBuilder::HashFunc = BloomFilter::HashFunc
Definition at line 99 of file SymbolFilter.h.
Constructor & Destructor Documentation
BloomFilterBuilder()
llvm::orc::BloomFilterBuilder::BloomFilterBuilder () default
Referenced by setFalsePositiveRate(), and setHashFunction().
Member Function Documentation
build()
BloomFilter llvm::orc::BloomFilterBuilder::build (ArrayRef< StringRef > Symbols) const inline
Definition at line 114 of file SymbolFilter.h.
References assert(), and F.
Referenced by llvm::orc::LibraryInfo::ensureFilterBuilt().
setFalsePositiveRate()
BloomFilterBuilder & llvm::orc::BloomFilterBuilder::setFalsePositiveRate (float Rate) inline
Definition at line 103 of file SymbolFilter.h.
References assert(), and BloomFilterBuilder().
setHashFunction()
BloomFilterBuilder & llvm::orc::BloomFilterBuilder::setHashFunction (HashFunc Fn) inline
Definition at line 109 of file SymbolFilter.h.
References BloomFilterBuilder().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/SymbolFilter.h