LLVM: llvm::GVNExpression::AggregateValueExpression Class Reference
llvm::GVNExpression::AggregateValueExpression Class Reference final
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Types
using int_arg_iterator = unsigned *
using const_int_arg_iterator = const unsigned *
Public Types inherited from llvm::GVNExpression::BasicExpression
using op_iterator = Value **
using const_op_iterator = Value *const *
Public Member Functions
AggregateValueExpression (unsigned NumOperands, unsigned NumIntOperands)
AggregateValueExpression ()=delete
AggregateValueExpression (const AggregateValueExpression &)=delete
AggregateValueExpression & operator= (const AggregateValueExpression &)=delete
~AggregateValueExpression () override
int_arg_iterator int_op_begin ()
int_arg_iterator int_op_end ()
const_int_arg_iterator int_op_begin () const
const_int_arg_iterator int_op_end () const
unsigned int_op_size () const
bool int_op_empty () const
void int_op_push_back (unsigned IntOperand)
void allocateIntOperands (BumpPtrAllocator &Allocator)
bool equals (const Expression &Other) const override
hash_code getHashValue () const override
void printInternal (raw_ostream &OS, bool PrintEType) const override
Public Member Functions inherited from llvm::GVNExpression::BasicExpression
BasicExpression (unsigned NumOperands)
BasicExpression (unsigned NumOperands, ExpressionType ET)
BasicExpression ()=delete
BasicExpression (const BasicExpression &)=delete
BasicExpression & operator= (const BasicExpression &)=delete
~BasicExpression () override
void swapOperands (unsigned First, unsigned Second)
Swap two operands.
Value * getOperand (unsigned N) const
void setOperand (unsigned N, Value *V)
unsigned getNumOperands () const
op_iterator op_begin ()
op_iterator op_end ()
const_op_iterator op_begin () const
const_op_iterator op_end () const
iterator_range< op_iterator > operands ()
iterator_range< const_op_iterator > operands () const
void op_push_back (Value *Arg)
bool op_empty () const
void allocateOperands (RecyclerType &Recycler, BumpPtrAllocator &Allocator)
void deallocateOperands (RecyclerType &Recycler)
void setType (Type *T)
Type * getType () const
bool equals (const Expression &Other) const override
hash_code getHashValue () const override
void printInternal (raw_ostream &OS, bool PrintEType) const override
Public Member Functions inherited from llvm::GVNExpression::Expression
Expression (ExpressionType ET=ET_Base, unsigned O=~2U)
Expression (const Expression &)=delete
Expression & operator= (const Expression &)=delete
virtual ~Expression ()
bool operator!= (const Expression &Other) const
bool operator== (const Expression &Other) const
hash_code getComputedHash () const
virtual bool exactlyEquals (const Expression &Other) const
unsigned getOpcode () const
void setOpcode (unsigned opcode)
ExpressionType getExpressionType () const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::BasicExpression
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::Expression
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
Detailed Description
Definition at line 417 of file GVNExpression.h.
Member Typedef Documentation
const_int_arg_iterator
using llvm::GVNExpression::AggregateValueExpression::const_int_arg_iterator = const unsigned *
Definition at line 438 of file GVNExpression.h.
int_arg_iterator
using llvm::GVNExpression::AggregateValueExpression::int_arg_iterator = unsigned *
Definition at line 437 of file GVNExpression.h.
Constructor & Destructor Documentation
AggregateValueExpression() [1/3]
llvm::GVNExpression::AggregateValueExpression::AggregateValueExpression (unsigned NumOperands, unsigned NumIntOperands) inline
Definition at line 424 of file GVNExpression.h.
References llvm::GVNExpression::BasicExpression::BasicExpression(), and llvm::GVNExpression::ET_AggregateValue.
Referenced by AggregateValueExpression(), equals(), and operator=().
AggregateValueExpression() [2/3]
llvm::GVNExpression::AggregateValueExpression::AggregateValueExpression () delete
AggregateValueExpression() [3/3]
llvm::GVNExpression::AggregateValueExpression::AggregateValueExpression (const AggregateValueExpression &) delete
References AggregateValueExpression().
~AggregateValueExpression()
AggregateValueExpression::~AggregateValueExpression () override default
Member Function Documentation
allocateIntOperands()
void llvm::GVNExpression::AggregateValueExpression::allocateIntOperands (BumpPtrAllocator & Allocator) inline
Definition at line 455 of file GVNExpression.h.
References Allocator, and assert().
classof()
bool llvm::GVNExpression::AggregateValueExpression::classof (const Expression * EB) inline static
Definition at line 433 of file GVNExpression.h.
References llvm::GVNExpression::ET_AggregateValue, and llvm::GVNExpression::Expression::getExpressionType().
equals()
bool llvm::GVNExpression::AggregateValueExpression::equals (const Expression & Other) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 460 of file GVNExpression.h.
References AggregateValueExpression(), llvm::cast(), llvm::GVNExpression::BasicExpression::equals(), int_op_begin(), int_op_end(), and llvm::Other.
getHashValue()
hash_code llvm::GVNExpression::AggregateValueExpression::getHashValue () const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 468 of file GVNExpression.h.
References llvm::GVNExpression::BasicExpression::getHashValue(), llvm::hash_combine(), llvm::hash_combine_range(), int_op_begin(), and int_op_end().
int_op_begin() [1/2]
int_arg_iterator llvm::GVNExpression::AggregateValueExpression::int_op_begin () inline
Definition at line 440 of file GVNExpression.h.
Referenced by equals(), and getHashValue().
int_op_begin() [2/2]
const_int_arg_iterator llvm::GVNExpression::AggregateValueExpression::int_op_begin () const inline
Definition at line 442 of file GVNExpression.h.
int_op_empty()
bool llvm::GVNExpression::AggregateValueExpression::int_op_empty () const inline
Definition at line 447 of file GVNExpression.h.
int_op_end() [1/2]
int_arg_iterator llvm::GVNExpression::AggregateValueExpression::int_op_end () inline
Definition at line 441 of file GVNExpression.h.
Referenced by equals(), and getHashValue().
int_op_end() [2/2]
const_int_arg_iterator llvm::GVNExpression::AggregateValueExpression::int_op_end () const inline
Definition at line 443 of file GVNExpression.h.
int_op_push_back()
void llvm::GVNExpression::AggregateValueExpression::int_op_push_back (unsigned IntOperand) inline
Definition at line 448 of file GVNExpression.h.
References assert().
int_op_size()
unsigned llvm::GVNExpression::AggregateValueExpression::int_op_size () const inline
Definition at line 446 of file GVNExpression.h.
Referenced by printInternal().
operator=()
AggregateValueExpression & llvm::GVNExpression::AggregateValueExpression::operator= (const AggregateValueExpression &) delete
References AggregateValueExpression().
printInternal()
void llvm::GVNExpression::AggregateValueExpression::printInternal (raw_ostream & OS, bool PrintEType) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 474 of file GVNExpression.h.
References int_op_size(), and llvm::GVNExpression::BasicExpression::printInternal().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/GVNExpression.h
lib/Transforms/Scalar/NewGVN.cpp