LLVM: llvm::PlaceSafepointsPass Class Reference
llvm::PlaceSafepointsPass Class Reference
#include "llvm/Transforms/Scalar/PlaceSafepoints.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, const TargetLibraryInfo &TLI)
void cleanup ()
Public Member Functions inherited from llvm::PassInfoMixin< PlaceSafepointsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< PlaceSafepointsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 59 of file PlaceSafepoints.h.
Member Function Documentation
cleanup()
void llvm::PlaceSafepointsPass::cleanup () inline
Definition at line 65 of file PlaceSafepoints.h.
run()
PreservedAnalyses PlaceSafepointsPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 376 of file PlaceSafepoints.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::none(), and runImpl().
runImpl()
bool PlaceSafepointsPass::runImpl (Function & F, const TargetLibraryInfo & TLI)
Definition at line 250 of file PlaceSafepoints.cpp.
References llvm::legacy::FunctionPassManager::add(), llvm::append_range(), assert(), llvm::DominatorTree::dominates(), llvm::SetVector< T, Vector, Set, N >::empty(), enableBackedgeSafepoints(), enableCallSafepoints(), enableEntrySafepoints(), F, findLocationForEntrySafepoint(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), llvm::SetVector< T, Vector, Set, N >::insert(), InsertSafepointPoll(), isGCSafepointPoll(), Modified, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), llvm::removeUnreachableBlocks(), llvm::legacy::FunctionPassManager::run(), shouldRewriteFunction(), llvm::sort(), SplitBackedge, llvm::SplitEdge(), llvm::successors(), and llvm::unique().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/PlaceSafepoints.h
lib/Transforms/Scalar/PlaceSafepoints.cpp