LLVM: llvm::objcopy::elf::BinarySectionWriter Class Reference
llvm::objcopy::elf::BinarySectionWriter Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
~BinarySectionWriter () override=default
Error visit (const SymbolTableSection &Sec) override
Error visit (const RelocationSection &Sec) override
Error visit (const GnuDebugLinkSection &Sec) override
Error visit (const GroupSection &Sec) override
Error visit (const SectionIndexSection &Sec) override
Error visit (const CompressedSection &Sec) override
Error visit (const DecompressedSection &Sec) override
BinarySectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionWriter
~SectionWriter () override=default
Error visit (const Section &Sec) override
Error visit (const OwnedDataSection &Sec) override
Error visit (const StringTableSection &Sec) override
Error visit (const DynamicRelocationSection &Sec) override
SectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionVisitor
virtual ~SectionVisitor ()=default
Additional Inherited Members
Protected Attributes inherited from llvm::objcopy::elf::SectionWriter
WritableMemoryBuffer & Out
Detailed Description
Definition at line 181 of file ELFObject.h.
Constructor & Destructor Documentation
~BinarySectionWriter()
llvm::objcopy::elf::BinarySectionWriter::~BinarySectionWriter () override default
BinarySectionWriter()
llvm::objcopy::elf::BinarySectionWriter::BinarySectionWriter (WritableMemoryBuffer & Buf) inline explicit
Definition at line 193 of file ELFObject.h.
References llvm::objcopy::elf::SectionWriter::SectionWriter().
Referenced by llvm::objcopy::elf::IHexSectionWriterBase::IHexSectionWriterBase(), and llvm::objcopy::elf::SRECSectionWriterBase::SRECSectionWriterBase().
Member Function Documentation
visit() [1/7]
Error BinarySectionWriter::visit (const CompressedSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SRECSectionWriterBase.
Definition at line 527 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Name, and llvm::operation_not_permitted.
visit() [2/7]
Error BinarySectionWriter::visit (const DecompressedSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SRECSectionWriterBase.
Definition at line 496 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Name, and llvm::operation_not_permitted.
visit() [3/7]
Error BinarySectionWriter::visit (const GnuDebugLinkSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SRECSectionWriterBase.
Definition at line 176 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Name, and llvm::operation_not_permitted.
visit() [4/7]
Error BinarySectionWriter::visit (const GroupSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SRECSectionWriterBase.
Definition at line 181 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Name, and llvm::operation_not_permitted.
visit() [5/7]
Error BinarySectionWriter::visit (const RelocationSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SRECSectionWriterBase.
Definition at line 170 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Name, and llvm::operation_not_permitted.
visit() [6/7]
Error BinarySectionWriter::visit (const SectionIndexSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SRECSectionWriterBase.
Definition at line 158 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Name, and llvm::operation_not_permitted.
visit() [7/7]
Error BinarySectionWriter::visit (const SymbolTableSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SRECSectionWriterBase.
Definition at line 164 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Name, and llvm::operation_not_permitted.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp