LLVM: llvm::Clause Class Reference
llvm::Clause Class Reference
#include "llvm/TableGen/DirectiveEmitter.h"
Public Member Functions
Clause (const Record *Def)
StringRef getClangClass () const
StringRef getFlangClass () const
std::string getFormattedParserClassName () const
std::string getClangAccSpelling () const
StringRef getEnumName () const
std::vector< const Record * > getClauseVals () const
bool skipFlangUnparser () const
bool isValueOptional () const
bool isValueList () const
StringRef getDefaultValue () const
bool isImplicit () const
std::vector< StringRef > getAliases () const
StringRef getPrefix () const
bool isPrefixOptional () const
Public Member Functions inherited from llvm::BaseRecord
BaseRecord (const Record *Def)
std::vector< Spelling::Value > getSpellings () const
StringRef getSpellingForIdentifier () const
std::string getFormattedName () const
bool isDefault () const
StringRef getRecordName () const
const Record * getRecord () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::BaseRecord
static std::string getSnakeName (StringRef Name)
static std::string getUpperCamelName (StringRef Name, StringRef Sep)
Protected Attributes inherited from llvm::BaseRecord
const Record * Def
Detailed Description
Definition at line 279 of file DirectiveEmitter.h.
Constructor & Destructor Documentation
Clause()
llvm::Clause::Clause (const Record * Def) inline
Definition at line 281 of file DirectiveEmitter.h.
References llvm::BaseRecord::BaseRecord(), and llvm::BaseRecord::Def.
Member Function Documentation
getAliases()
std::vector< StringRef > llvm::Clause::getAliases () const inline
Definition at line 338 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getClangAccSpelling()
std::string llvm::Clause::getClangAccSpelling () const inline
Definition at line 306 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def, llvm::BaseRecord::getSpellingForIdentifier(), and llvm::BaseRecord::getUpperCamelName().
getClangClass()
StringRef llvm::Clause::getClangClass () const inline
Definition at line 284 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getClauseVals()
std::vector< const Record * > llvm::Clause::getClauseVals () const inline
Definition at line 320 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getDefaultValue()
StringRef llvm::Clause::getDefaultValue () const inline
Definition at line 332 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getEnumName()
StringRef llvm::Clause::getEnumName () const inline
Definition at line 316 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getFlangClass()
StringRef llvm::Clause::getFlangClass () const inline
Definition at line 289 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
getFormattedParserClassName()
std::string llvm::Clause::getFormattedParserClassName () const inline
Definition at line 298 of file DirectiveEmitter.h.
References llvm::BaseRecord::getSpellingForIdentifier(), and llvm::BaseRecord::getUpperCamelName().
getPrefix()
StringRef llvm::Clause::getPrefix () const inline
Definition at line 342 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
isImplicit()
bool llvm::Clause::isImplicit () const inline
Definition at line 336 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
isPrefixOptional()
bool llvm::Clause::isPrefixOptional () const inline
Definition at line 344 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
isValueList()
bool llvm::Clause::isValueList () const inline
Definition at line 330 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
isValueOptional()
bool llvm::Clause::isValueOptional () const inline
Definition at line 328 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
skipFlangUnparser()
bool llvm::Clause::skipFlangUnparser () const inline
Definition at line 324 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def.
The documentation for this class was generated from the following file:
include/llvm/TableGen/DirectiveEmitter.h