LLVM: llvm::PseudoProbeHandler Class Reference
llvm::PseudoProbeHandler Class Reference
#include "CodeGen/AsmPrinter/PseudoProbePrinter.h"
Public Member Functions
PseudoProbeHandler (AsmPrinter *A)
void emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const DILocation *DebugLoc)
Detailed Description
Definition at line 27 of file PseudoProbePrinter.h.
Constructor & Destructor Documentation
PseudoProbeHandler()
llvm::PseudoProbeHandler::PseudoProbeHandler (AsmPrinter * A) inline
Definition at line 41 of file PseudoProbePrinter.h.
References A().
Member Function Documentation
emitPseudoProbe()
void PseudoProbeHandler::emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const DILocation * DebugLoc)
Definition at line 39 of file PseudoProbePrinter.cpp.
References assert(), llvm::Block, llvm::SmallVectorImpl< T >::emplace_back(), llvm::EnableFSDiscriminator, llvm::PseudoProbeDwarfDiscriminator::extractProbeIndex(), llvm::sampleprof::FunctionSamples::getCanonicalCoroFnName(), llvm::GlobalValue::getGUIDAssumingExternalLinkage(), llvm::Guid, llvm::reverse(), and VerifyGuidExistence.
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/PseudoProbePrinter.h
lib/CodeGen/AsmPrinter/PseudoProbePrinter.cpp