LLVM: llvm::SMLoc Class Reference
llvm::SMLoc Class Reference
Represents a location in source code.
#include "llvm/Support/SMLoc.h"
Public Member Functions
constexpr SMLoc ()=default
constexpr bool isValid () const
constexpr bool operator== (SMLoc RHS) const
constexpr bool operator!= (SMLoc RHS) const
constexpr const char * getPointer () const
Static Public Member Functions
static SMLoc getFromPointer (const char *Ptr)
Detailed Description
Represents a location in source code.
Definition at line 22 of file SMLoc.h.
Constructor & Destructor Documentation
SMLoc()
llvm::SMLoc::SMLoc () constexpr default
Referenced by getFromPointer(), operator!=(), and operator==().
Member Function Documentation
getFromPointer()
SMLoc llvm::SMLoc::getFromPointer (const char * Ptr) inline static
Definition at line 35 of file SMLoc.h.
References SMLoc().
Referenced by llvm::yaml::BlockScalarNode::BlockScalarNode(), llvm::FileCheckString::CheckDag(), llvm::FileCheckString::CheckNext(), llvm::FileCheckString::CheckSame(), llvm::X86Operand::CreateToken(), llvm::SourceMgr::FindLocForLineAndColumn(), llvm::ErrorDiagnostic::get(), llvm::AsmToken::getEndLoc(), llvm::AsmLexer::getLoc(), llvm::AsmToken::getLoc(), llvm::LLLexer::getLoc(), llvm::TGLexer::getLoc(), llvm::TGLexer::getLocRange(), llvm::SourceMgr::GetMessage(), llvm::LLLexer::getPrevTokEndLineColumnPos(), llvm::LLLexer::getTokLineColumnPos(), incrementLoc(), isAngleBracketString(), isAngleBracketString(), parseCC(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parsePattern(), parseRD(), llvm::parseType(), llvm::PrintError(), llvm::Pattern::printVariableDefs(), llvm::PrintWarning(), ProcessMatchResult(), llvm::FileCheck::readCheckFile(), llvm::yaml::ScalarNode::ScalarNode(), and llvm::yaml::Scanner::setError().
getPointer()
const char * llvm::SMLoc::getPointer () const inline constexpr
Definition at line 33 of file SMLoc.h.
Referenced by llvm::lsp::TextDocumentContentChangeEvent::applyTo(), llvm::lsp::Range::getAsSMRange(), isAngleBracketString(), isAngleBracketString(), parseCC(), llvm::LLParser::parseDIExpressionBodyAtBeginning(), parseRD(), llvm::LLParser::parseTypeAtBeginning(), rewritesSort(), and rewritesSort().
isValid()
bool llvm::SMLoc::isValid () const inline constexpr
Definition at line 28 of file SMLoc.h.
Referenced by llvm::lsp::Range::getAsSMRange(), and llvm::SourceMgr::PrintMessage().
operator!=()
bool llvm::SMLoc::operator!= (SMLoc RHS) const inline constexpr
Definition at line 31 of file SMLoc.h.
References RHS, and SMLoc().
operator==()
bool llvm::SMLoc::operator== (SMLoc RHS) const inline constexpr
Definition at line 30 of file SMLoc.h.
References RHS, and SMLoc().
The documentation for this class was generated from the following file:
include/llvm/Support/SMLoc.h