LLVM: llvm::logicalview::LVReader Class Reference
llvm::logicalview::LVReader Class Reference
The logical reader owns of all the logical elements created during the debug information parsing.
#include "llvm/DebugInfo/LogicalView/Core/LVReader.h"
Public Member Functions
LVReader ()=delete
LVReader (StringRef InputFilename, StringRef FileFormatName, ScopedPrinter &W, LVBinaryType BinaryType=LVBinaryType::NONE)
LVReader (const LVReader &)=delete
LVReader & operator= (const LVReader &)=delete
virtual ~LVReader ()=default
LVOperation * createOperation (LVSmall OpCode, ArrayRef< LVUnsigned > Operands)
StringRef getFilename (LVObject *Object, size_t Index) const
StringRef getFilename () const
void setFilename (std::string Name)
StringRef getFileFormatName () const
raw_ostream & outputStream ()
bool isBinaryTypeNone () const
bool isBinaryTypeELF () const
bool isBinaryTypeCOFF () const
LVScopeCompileUnit * getCompileUnit () const
void setCompileUnit (LVScope *Scope)
void setCompileUnitCPUType (codeview::CPUType Type)
codeview::CPUType getCompileUnitCPUType ()
LVScopeRoot * getScopesRoot () const
Error doPrint ()
Error doLoad ()
virtual std::string getRegisterName (LVSmall Opcode, ArrayRef< uint64_t > Operands)
LVSectionIndex getDotTextSectionIndex () const
virtual LVSectionIndex getSectionIndex (LVScope *Scope)
virtual bool isSystemEntry (LVElement *Element, StringRef Name={}) const
LVSplitContext & getSplitContext ()
void notifyAddedElement (LVLine *Line)
void notifyAddedElement (LVScope *Scope)
void notifyAddedElement (LVSymbol *Symbol)
void notifyAddedElement (LVType *Type)
const LVLines & getLines () const
const LVScopes & getScopes () const
const LVSymbols & getSymbols () const
const LVTypes & getTypes () const
bool doPrintLine (const LVLine *Line) const
bool doPrintLocation (const LVLocation *Location) const
bool doPrintScope (const LVScope *Scope) const
bool doPrintSymbol (const LVSymbol *Symbol) const
bool doPrintType (const LVType *Type) const
void print (raw_ostream &OS) const
virtual void printRecords (raw_ostream &OS) const
void dump () const
Static Public Member Functions
static LVReader & getInstance ()
static void setInstance (LVReader *Reader)
Protected Member Functions
void addSectionRange (LVSectionIndex SectionIndex, LVScope *Scope)
void addSectionRange (LVSectionIndex SectionIndex, LVScope *Scope, LVAddress LowerAddress, LVAddress UpperAddress)
LVRange * getSectionRanges (LVSectionIndex SectionIndex)
void addCompileUnitOffset (LVOffset Offset, LVScopeCompileUnit *CompileUnit)
LVElement * createElement (dwarf::Tag Tag)
virtual Error createScopes ()
std::string createAlternativePath (StringRef From)
virtual Error printScopes ()
virtual Error printMatchedElements (bool UseMatchedElements)
virtual void sortScopes ()
Protected Attributes
LVElement * CurrentElement = nullptr
LVScope * CurrentScope = nullptr
LVSymbol * CurrentSymbol = nullptr
LVType * CurrentType = nullptr
LVLine * CurrentLine = nullptr
LVOffset CurrentOffset = 0
std::vector< LVAddressRange > CurrentRanges
LVScopeRoot * Root = nullptr
std::string InputFilename
std::string FileFormatName
ScopedPrinter & W
raw_ostream & OS
LVScopeCompileUnit * CompileUnit = nullptr
LVSectionIndex DotTextSectionIndex = UndefinedSectionIndex
Detailed Description
The logical reader owns of all the logical elements created during the debug information parsing.
For its creation it uses a specific bump allocator for each type of logical element.
Definition at line 61 of file LVReader.h.
Constructor & Destructor Documentation
LVReader() [1/3]
llvm::logicalview::LVReader::LVReader () delete
Referenced by getInstance(), llvm::logicalview::LVBinaryReader::LVBinaryReader(), LVReader(), operator=(), and setInstance().
LVReader() [2/3]
llvm::logicalview::LVReader::LVReader (StringRef InputFilename, StringRef FileFormatName, ScopedPrinter & W, LVBinaryType BinaryType = LVBinaryType::NONE) inline
Definition at line 198 of file LVReader.h.
References FileFormatName, InputFilename, llvm::logicalview::NONE, llvm::logicalview::options(), OS, and W.
LVReader() [3/3]
llvm::logicalview::LVReader::LVReader (const LVReader &) delete
References LVReader().
~LVReader()
virtual llvm::logicalview::LVReader::~LVReader () virtual default
Member Function Documentation
addCompileUnitOffset()
void llvm::logicalview::LVReader::addCompileUnitOffset (LVOffset Offset, LVScopeCompileUnit * CompileUnit) inline protected
Definition at line 160 of file LVReader.h.
References CompileUnit, and llvm::Offset.
addSectionRange() [1/2]
void LVReader::addSectionRange (LVSectionIndex SectionIndex, LVScope * Scope) protected
Definition at line 197 of file LVReader.cpp.
References llvm::logicalview::LVRange::addEntry(), and getSectionRanges().
Referenced by llvm::logicalview::LVDWARFReader::createScopes().
addSectionRange() [2/2]
void LVReader::addSectionRange (LVSectionIndex SectionIndex, LVScope * Scope, LVAddress LowerAddress, LVAddress UpperAddress) protected
Definition at line 202 of file LVReader.cpp.
References llvm::logicalview::LVRange::addEntry(), and getSectionRanges().
createAlternativePath()
std::string llvm::logicalview::LVReader::createAlternativePath (StringRef From) inline protected
Definition at line 181 of file LVReader.h.
References llvm::sys::path::append(), llvm::sys::path::convert_to_slash(), llvm::sys::path::filename(), InputFilename, llvm::sys::path::parent_path(), llvm::sys::path::posix, and llvm::sys::path::windows.
Referenced by llvm::logicalview::LVDWARFReader::createScopes().
createElement()
LVElement * LVReader::createElement (dwarf::Tag Tag) protected
Definition at line 219 of file LVReader.cpp.
References CompileUnit, CurrentOffset, CurrentRanges, CurrentScope, CurrentSymbol, CurrentType, llvm::dbgs(), LLVM_DEBUG, llvm::logicalview::options(), and llvm::dwarf::TagString().
createOperation()
LVOperation * llvm::logicalview::LVReader::createOperation (LVSmall OpCode, ArrayRef< LVUnsigned > Operands) inline
Definition at line 258 of file LVReader.h.
createScopes()
virtual Error llvm::logicalview::LVReader::createScopes () inline protected virtual
Reimplemented in llvm::logicalview::LVCodeViewReader, and llvm::logicalview::LVDWARFReader.
Definition at line 167 of file LVReader.h.
References FileFormatName, getFilename(), llvm::logicalview::options(), Root, and llvm::Error::success().
Referenced by llvm::logicalview::LVCodeViewReader::createScopes(), llvm::logicalview::LVDWARFReader::createScopes(), and doLoad().
doLoad()
Error LVReader::doLoad ()
Definition at line 460 of file LVReader.cpp.
References llvm::logicalview::LVPatterns::addGenericPatterns(), llvm::logicalview::LVPatterns::addOffsetPatterns(), checkIntegrityScopesTree(), createScopes(), llvm::inconvertibleErrorCode(), llvm::make_error(), llvm::logicalview::options(), llvm::logicalview::patterns(), Root, Select, setInstance(), sortScopes(), llvm::Error::success(), and llvm::logicalview::LVPatterns::updateReportOptions().
doPrint()
Error LVReader::doPrint ()
Definition at line 501 of file LVReader.cpp.
References llvm::logicalview::options(), printMatchedElements(), printScopes(), setInstance(), and llvm::Error::success().
Referenced by llvm::logicalview::LVCompare::execute().
doPrintLine()
bool llvm::logicalview::LVReader::doPrintLine (const LVLine * Line) const inline
Definition at line 333 of file LVReader.h.
References llvm::logicalview::patterns().
doPrintLocation()
bool llvm::logicalview::LVReader::doPrintLocation (const LVLocation * Location) const inline
Definition at line 336 of file LVReader.h.
References llvm::logicalview::patterns().
doPrintScope()
bool llvm::logicalview::LVReader::doPrintScope (const LVScope * Scope) const inline
Definition at line 339 of file LVReader.h.
References llvm::logicalview::patterns().
doPrintSymbol()
bool llvm::logicalview::LVReader::doPrintSymbol (const LVSymbol * Symbol) const inline
Definition at line 342 of file LVReader.h.
References llvm::logicalview::patterns().
doPrintType()
bool llvm::logicalview::LVReader::doPrintType (const LVType * Type) const inline
Definition at line 345 of file LVReader.h.
References llvm::logicalview::patterns().
dump()
void llvm::logicalview::LVReader::dump () const inline
Definition at line 356 of file LVReader.h.
References llvm::dbgs(), and print().
getCompileUnit()
LVScopeCompileUnit * llvm::logicalview::LVReader::getCompileUnit () const inline
Definition at line 273 of file LVReader.h.
References CompileUnit.
Referenced by llvm::logicalview::getReaderCompileUnit().
getCompileUnitCPUType()
codeview::CPUType llvm::logicalview::LVReader::getCompileUnitCPUType () inline
Definition at line 281 of file LVReader.h.
References CompileUnit.
Referenced by llvm::logicalview::LVCodeViewReader::getRegisterName().
getDotTextSectionIndex()
LVSectionIndex llvm::logicalview::LVReader::getDotTextSectionIndex () const inline
Definition at line 297 of file LVReader.h.
References DotTextSectionIndex.
Referenced by llvm::logicalview::LVSymbolTable::getIndex(), getSectionIndex(), and llvm::logicalview::LVSymbolTable::update().
getFileFormatName()
StringRef llvm::logicalview::LVReader::getFileFormatName () const inline
Definition at line 265 of file LVReader.h.
References FileFormatName.
getFilename() [1/2]
StringRef llvm::logicalview::LVReader::getFilename () const inline
Definition at line 263 of file LVReader.h.
References InputFilename.
Referenced by llvm::logicalview::LVDWARFReader::createScopes().
getFilename() [2/2]
StringRef LVReader::getFilename (LVObject * Object, size_t Index) const
Definition at line 182 of file LVReader.cpp.
References CompileUnit.
Referenced by llvm::logicalview::LVElement::setFile().
getInstance()
LVReader & LVReader::getInstance () static
Definition at line 152 of file LVReader.cpp.
References CurrentReader, llvm_unreachable, LVReader(), and llvm::outs().
Referenced by llvm::logicalview::getReader().
getLines()
const LVLines & llvm::logicalview::LVReader::getLines () const inline
Definition at line 327 of file LVReader.h.
getRegisterName()
virtual std::string llvm::logicalview::LVReader::getRegisterName (LVSmall Opcode, ArrayRef< uint64_t > Operands) inline virtual
Reimplemented in llvm::logicalview::LVCodeViewReader, and llvm::logicalview::LVDWARFReader.
Definition at line 291 of file LVReader.h.
References llvm_unreachable.
Referenced by llvm::logicalview::LVOperation::getOperandsCodeViewInfo(), and llvm::logicalview::LVOperation::getOperandsDWARFInfo().
getScopes()
const LVScopes & llvm::logicalview::LVReader::getScopes () const inline
Definition at line 328 of file LVReader.h.
getScopesRoot()
LVScopeRoot * llvm::logicalview::LVReader::getScopesRoot () const inline
Definition at line 286 of file LVReader.h.
References Root.
Referenced by llvm::logicalview::LVCompare::execute().
getSectionIndex()
virtual LVSectionIndex llvm::logicalview::LVReader::getSectionIndex (LVScope * Scope) inline virtual
Reimplemented in llvm::logicalview::LVBinaryReader.
Definition at line 298 of file LVReader.h.
References getDotTextSectionIndex().
Referenced by llvm::logicalview::LVElement::printLinkageName().
getSectionRanges()
LVRange * LVReader::getSectionRanges (LVSectionIndex SectionIndex) protected
Definition at line 208 of file LVReader.cpp.
References assert(), and Range.
Referenced by addSectionRange(), addSectionRange(), llvm::logicalview::LVDWARFReader::createScopes(), and llvm::logicalview::LVBinaryReader::processLines().
getSplitContext()
LVSplitContext & llvm::logicalview::LVReader::getSplitContext () inline
Definition at line 307 of file LVReader.h.
Referenced by llvm::logicalview::getReaderSplitContext().
getSymbols()
const LVSymbols & llvm::logicalview::LVReader::getSymbols () const inline
Definition at line 329 of file LVReader.h.
getTypes()
const LVTypes & llvm::logicalview::LVReader::getTypes () const inline
Definition at line 330 of file LVReader.h.
isBinaryTypeCOFF()
bool llvm::logicalview::LVReader::isBinaryTypeCOFF () const inline
Definition at line 271 of file LVReader.h.
References llvm::logicalview::COFF.
isBinaryTypeELF()
bool llvm::logicalview::LVReader::isBinaryTypeELF () const inline
Definition at line 270 of file LVReader.h.
References llvm::logicalview::ELF.
isBinaryTypeNone()
bool llvm::logicalview::LVReader::isBinaryTypeNone () const inline
Definition at line 269 of file LVReader.h.
References llvm::logicalview::NONE.
isSystemEntry()
virtual bool llvm::logicalview::LVReader::isSystemEntry (LVElement * Element, StringRef Name = {}) const inline virtual
Reimplemented in llvm::logicalview::LVCodeViewReader.
Definition at line 302 of file LVReader.h.
Referenced by llvm::logicalview::LVScopeFunction::setName(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
notifyAddedElement() [1/4]
void llvm::logicalview::LVReader::notifyAddedElement (LVLine * Line) inline
Definition at line 310 of file LVReader.h.
References llvm::logicalview::options().
Referenced by llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVScopeCompileUnit::addedElement(), and llvm::logicalview::LVScopeCompileUnit::addedElement().
notifyAddedElement() [2/4]
void llvm::logicalview::LVReader::notifyAddedElement (LVScope * Scope) inline
Definition at line 314 of file LVReader.h.
References llvm::logicalview::options().
notifyAddedElement() [3/4]
void llvm::logicalview::LVReader::notifyAddedElement (LVSymbol * Symbol) inline
Definition at line 318 of file LVReader.h.
References llvm::logicalview::options().
notifyAddedElement() [4/4]
void llvm::logicalview::LVReader::notifyAddedElement (LVType * Type) inline
Definition at line 322 of file LVReader.h.
References llvm::logicalview::options().
operator=()
LVReader & llvm::logicalview::LVReader::operator= (const LVReader &) delete
References LVReader().
outputStream()
raw_ostream & llvm::logicalview::LVReader::outputStream () inline
Definition at line 267 of file LVReader.h.
References OS.
Referenced by llvm::logicalview::LVScope::doPrint(), and llvm::logicalview::LVScopeRoot::doPrintMatches().
print()
void LVReader::print (raw_ostream & OS) const
Definition at line 549 of file LVReader.cpp.
References llvm::dbgs(), LLVM_DEBUG, and OS.
printMatchedElements()
Error LVReader::printMatchedElements (bool UseMatchedElements) protected virtual
Definition at line 542 of file LVReader.cpp.
References OS, and Root.
Referenced by doPrint().
printRecords()
virtual void llvm::logicalview::LVReader::printRecords (raw_ostream & OS) const inline virtual
Reimplemented in llvm::logicalview::LVCodeViewReader.
Definition at line 353 of file LVReader.h.
References OS.
Referenced by llvm::logicalview::LVScope::doPrint().
printScopes()
Error LVReader::printScopes () protected virtual
Definition at line 526 of file LVReader.cpp.
References llvm::logicalview::options(), OS, Root, and llvm::Error::success().
Referenced by doPrint().
setCompileUnit()
void llvm::logicalview::LVReader::setCompileUnit (LVScope * Scope) inline
Definition at line 274 of file LVReader.h.
References assert(), and CompileUnit.
Referenced by llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::logicalview::LVCompare::execute(), llvm::logicalview::LVScopeCompileUnit::printSizes(), llvm::logicalview::LVScopeRoot::processRangeInformation(), and llvm::logicalview::LVScope::resolveElements().
setCompileUnitCPUType()
void llvm::logicalview::LVReader::setCompileUnitCPUType (codeview::CPUType Type) inline
Definition at line 278 of file LVReader.h.
References CompileUnit.
setFilename()
void llvm::logicalview::LVReader::setFilename (std::string Name) inline
Definition at line 264 of file LVReader.h.
References InputFilename.
setInstance()
void LVReader::setInstance (LVReader * Reader) static
Definition at line 158 of file LVReader.cpp.
References CurrentReader, and LVReader().
Referenced by doLoad(), doPrint(), and llvm::logicalview::LVCompare::execute().
sortScopes()
virtual void llvm::logicalview::LVReader::sortScopes () inline protected virtual
Reimplemented in llvm::logicalview::LVCodeViewReader, and llvm::logicalview::LVDWARFReader.
Definition at line 194 of file LVReader.h.
Referenced by doLoad().
Member Data Documentation
CompileUnit
LVScopeCompileUnit* llvm::logicalview::LVReader::CompileUnit = nullptr protected
Definition at line 149 of file LVReader.h.
Referenced by addCompileUnitOffset(), createElement(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVDWARFReader::createScopes(), getCompileUnit(), getCompileUnitCPUType(), getFilename(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVBinaryReader::processLines(), setCompileUnit(), and setCompileUnitCPUType().
CurrentElement
LVElement* llvm::logicalview::LVReader::CurrentElement = nullptr protected
Definition at line 134 of file LVReader.h.
CurrentLine
LVLine* llvm::logicalview::LVReader::CurrentLine = nullptr protected
Definition at line 138 of file LVReader.h.
CurrentOffset
LVOffset llvm::logicalview::LVReader::CurrentOffset = 0 protected
Definition at line 139 of file LVReader.h.
Referenced by createElement().
CurrentRanges
std::vector<LVAddressRange> llvm::logicalview::LVReader::CurrentRanges protected
Definition at line 142 of file LVReader.h.
Referenced by createElement().
CurrentScope
LVScope* llvm::logicalview::LVReader::CurrentScope = nullptr protected
Definition at line 135 of file LVReader.h.
Referenced by createElement().
CurrentSymbol
LVSymbol* llvm::logicalview::LVReader::CurrentSymbol = nullptr protected
Definition at line 136 of file LVReader.h.
Referenced by createElement().
CurrentType
LVType* llvm::logicalview::LVReader::CurrentType = nullptr protected
Definition at line 137 of file LVReader.h.
Referenced by createElement().
DotTextSectionIndex
LVSectionIndex llvm::logicalview::LVReader::DotTextSectionIndex = UndefinedSectionIndex protected
Definition at line 152 of file LVReader.h.
Referenced by getDotTextSectionIndex(), llvm::logicalview::LVBinaryReader::getSectionIndex(), and llvm::logicalview::LVBinaryReader::mapVirtualAddress().
FileFormatName
std::string llvm::logicalview::LVReader::FileFormatName protected
Definition at line 146 of file LVReader.h.
Referenced by llvm::logicalview::LVCodeViewReader::createScopes(), llvm::logicalview::LVDWARFReader::createScopes(), createScopes(), getFileFormatName(), llvm::logicalview::LVBinaryReader::LVBinaryReader(), llvm::logicalview::LVCodeViewReader::LVCodeViewReader(), llvm::logicalview::LVCodeViewReader::LVCodeViewReader(), llvm::logicalview::LVDWARFReader::LVDWARFReader(), and LVReader().
InputFilename
std::string llvm::logicalview::LVReader::InputFilename protected
Definition at line 145 of file LVReader.h.
Referenced by createAlternativePath(), getFilename(), LVReader(), and setFilename().
OS
raw_ostream& llvm::logicalview::LVReader::OS protected
Definition at line 148 of file LVReader.h.
Referenced by LVReader(), outputStream(), llvm::logicalview::LVBinaryReader::print(), llvm::logicalview::LVCodeViewReader::print(), llvm::logicalview::LVDWARFReader::print(), print(), printMatchedElements(), llvm::logicalview::LVCodeViewReader::printRecords(), printRecords(), and printScopes().
Root
LVScopeRoot* llvm::logicalview::LVReader::Root = nullptr protected
Definition at line 144 of file LVReader.h.
Referenced by llvm::logicalview::LVCodeViewReader::createScopes(), llvm::logicalview::LVDWARFReader::createScopes(), createScopes(), doLoad(), getScopesRoot(), printMatchedElements(), printScopes(), llvm::logicalview::LVCodeViewReader::sortScopes(), and llvm::logicalview::LVDWARFReader::sortScopes().
W
ScopedPrinter& llvm::logicalview::LVReader::W protected
Definition at line 147 of file LVReader.h.
Referenced by llvm::logicalview::LVCodeViewReader::createScopes(), llvm::logicalview::LVDWARFReader::createScopes(), llvm::logicalview::LVBinaryReader::LVBinaryReader(), llvm::logicalview::LVCodeViewReader::LVCodeViewReader(), llvm::logicalview::LVCodeViewReader::LVCodeViewReader(), llvm::logicalview::LVDWARFReader::LVDWARFReader(), and LVReader().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVReader.h
lib/DebugInfo/LogicalView/Core/LVReader.cpp