LLVM: llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService Class Reference
llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService Class Reference final
#include "llvm/ExecutionEngine/Orc/TargetProcess/ExecutorSharedMemoryMapperService.h"
Public Member Functions
~ExecutorSharedMemoryMapperService () override=default
Expected< std::pair< ExecutorAddr, std::string > > reserve (uint64_t Size)
Expected< ExecutorAddr > initialize (ExecutorAddr Reservation, tpctypes::SharedMemoryFinalizeRequest &FR)
Error deinitialize (const std::vector< ExecutorAddr > &Bases)
Error release (const std::vector< ExecutorAddr > &Bases)
Error shutdown () override
void addBootstrapSymbols (StringMap< ExecutorAddr > &M) override
Public Member Functions inherited from llvm::orc::ExecutorBootstrapService
virtual ~ExecutorBootstrapService ()
Detailed Description
Definition at line 29 of file ExecutorSharedMemoryMapperService.h.
Constructor & Destructor Documentation
~ExecutorSharedMemoryMapperService()
llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::~ExecutorSharedMemoryMapperService () override default
References addBootstrapSymbols(), deinitialize(), release(), reserve(), and shutdown().
Member Function Documentation
addBootstrapSymbols()
void llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::addBootstrapSymbols (StringMap< ExecutorAddr > & M) override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 310 of file ExecutorSharedMemoryMapperService.cpp.
References llvm::orc::rt::ExecutorSharedMemoryMapperServiceDeinitializeWrapperName, llvm::orc::rt::ExecutorSharedMemoryMapperServiceInitializeWrapperName, llvm::orc::rt::ExecutorSharedMemoryMapperServiceInstanceName, llvm::orc::rt::ExecutorSharedMemoryMapperServiceReleaseWrapperName, llvm::orc::rt::ExecutorSharedMemoryMapperServiceReserveWrapperName, and llvm::orc::ExecutorAddr::fromPtr().
Referenced by ~ExecutorSharedMemoryMapperService().
deinitialize()
Error llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::deinitialize (const std::vector< ExecutorAddr > & Bases)
Definition at line 205 of file ExecutorSharedMemoryMapperService.cpp.
References llvm::sampleprof::Base, llvm::find(), llvm::joinErrors(), llvm::reverse(), llvm::orc::shared::runDeallocActions(), and llvm::Error::success().
Referenced by release(), and ~ExecutorSharedMemoryMapperService().
initialize()
Expected< ExecutorAddr > llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::initialize (ExecutorAddr Reservation, tpctypes::SharedMemoryFinalizeRequest & FR)
Definition at line 140 of file ExecutorSharedMemoryMapperService.cpp.
References llvm::orc::tpctypes::SharedMemoryFinalizeRequest::Actions, llvm::errnoAsErrorCode(), llvm::errorCodeToError(), llvm::orc::Exec, llvm::inconvertibleErrorCode(), llvm::sys::Memory::InvalidateInstructionCache(), llvm::make_error(), llvm::mapWindowsError(), llvm::orc::Read, llvm::orc::shared::runFinalizeActions(), llvm::orc::tpctypes::SharedMemoryFinalizeRequest::Segments, and llvm::orc::Write.
release()
Error llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::release (const std::vector< ExecutorAddr > & Bases)
Definition at line 234 of file ExecutorSharedMemoryMapperService.cpp.
References llvm::sampleprof::Base, deinitialize(), E(), llvm::errnoAsErrorCode(), llvm::errorCodeToError(), llvm::inconvertibleErrorCode(), llvm::joinErrors(), llvm::make_error(), llvm::mapWindowsError(), Size, and llvm::Error::success().
Referenced by shutdown(), and ~ExecutorSharedMemoryMapperService().
reserve()
Expected< std::pair< ExecutorAddr, std::string > > llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::reserve (uint64_t Size)
Definition at line 52 of file ExecutorSharedMemoryMapperService.cpp.
References llvm::Data, llvm::errnoAsErrorCode(), llvm::errorCodeToError(), llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::Process::getProcessId(), llvm::BLAKE3::hash(), llvm::inconvertibleErrorCode(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::make_error(), llvm::mapWindowsError(), and Size.
Referenced by ~ExecutorSharedMemoryMapperService().
shutdown()
Error llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::shutdown () override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 298 of file ExecutorSharedMemoryMapperService.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), release(), and llvm::Error::success().
Referenced by ~ExecutorSharedMemoryMapperService().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/ExecutorSharedMemoryMapperService.h
lib/ExecutionEngine/Orc/TargetProcess/ExecutorSharedMemoryMapperService.cpp