LLVM: llvm::DXILResourcePrinterPass Class Reference
llvm::DXILResourcePrinterPass Class Reference
Printer pass for the DXILResourceAnalysis results.
#include "llvm/Analysis/DXILResource.h"
Public Member Functions
DXILResourcePrinterPass (raw_ostream &OS)
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< DXILResourcePrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< DXILResourcePrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the DXILResourceAnalysis results.
Definition at line 620 of file DXILResource.h.
Constructor & Destructor Documentation
DXILResourcePrinterPass()
llvm::DXILResourcePrinterPass::DXILResourcePrinterPass (raw_ostream & OS) inline explicit
Definition at line 624 of file DXILResource.h.
Member Function Documentation
isRequired()
bool llvm::DXILResourcePrinterPass::isRequired () inline static
Definition at line 628 of file DXILResource.h.
run()
PreservedAnalyses DXILResourcePrinterPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 1117 of file DXILResource.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::DXILResourceMap::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILResource.h
lib/Analysis/DXILResource.cpp