LLVM: llvm::MCSectionELF Class Reference
llvm::MCSectionELF Class Reference final
This represents a section on linux, lots of unix variants and some bare metal systems.
#include "llvm/MC/MCSectionELF.h"
Public Member Functions
unsigned getType () const
unsigned getFlags () const
unsigned getEntrySize () const
void setFlags (unsigned F)
const MCSymbolELF * getGroup () const
bool isComdat () const
bool isUnique () const
unsigned getUniqueID () const
const MCSection * getLinkedToSection () const
const MCSymbol * getLinkedToSymbol () const
void setOffsets (uint64_t Start, uint64_t End)
std::pair< uint64_t, uint64_t > getOffsets () const
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
StringRef getName () const
bool isText () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
Align getAlign () const
void setAlignment (Align Value)
void ensureMinAlignment (Align MinAlignment)
Makes sure that Alignment is at least MinAlignment.
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
unsigned firstLinkerRelaxable () const
bool isLinkerRelaxable () const
void setFirstLinkerRelaxable (unsigned Order)
MCFragment & getDummyFragment ()
FragList * curFragList () const
iterator begin () const
iterator end () const
void dump (DenseMap< const MCFragment *, SmallVector< const MCSymbol *, 0 > > *FragToSyms=nullptr) const
bool isBssSection () const
Check whether this section is "virtual", that is has no actual object file contents.
Friends
class MCContext
class MCAsmInfoELF
Additional Inherited Members
Public Attributes inherited from llvm::MCSection
friend MCAssembler
friend MCObjectStreamer
Static Public Attributes inherited from llvm::MCSection
static constexpr unsigned NonUniqueID = ~0U
Protected Member Functions inherited from llvm::MCSection
MCSection (StringRef Name, bool IsText, bool IsBss, MCSymbol *Begin)
Protected Attributes inherited from llvm::MCSection
StringRef Name
Detailed Description
This represents a section on linux, lots of unix variants and some bare metal systems.
Definition at line 27 of file MCSectionELF.h.
Member Function Documentation
getEntrySize()
unsigned llvm::MCSectionELF::getEntrySize () const inline
Definition at line 75 of file MCSectionELF.h.
getFlags()
unsigned llvm::MCSectionELF::getFlags () const inline
Definition at line 74 of file MCSectionELF.h.
Referenced by llvm::MCObjectFileInfo::getPseudoProbeDescSection(), llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), and llvm::ELFObjectWriter::useSectionSymbol().
getGroup()
const MCSymbolELF * llvm::MCSectionELF::getGroup () const inline
Definition at line 77 of file MCSectionELF.h.
Referenced by llvm::MCObjectFileInfo::getBBAddrMapSection(), llvm::MCObjectFileInfo::getCallGraphSection(), llvm::MCObjectFileInfo::getKCFITrapSection(), and llvm::MCObjectFileInfo::getStackSizesSection().
getLinkedToSection()
const MCSection * llvm::MCSectionELF::getLinkedToSection () const inline
Definition at line 83 of file MCSectionELF.h.
References llvm::MCSection::MCSection().
getLinkedToSymbol()
const MCSymbol * llvm::MCSectionELF::getLinkedToSymbol () const inline
Definition at line 86 of file MCSectionELF.h.
getOffsets()
std::pair< uint64_t, uint64_t > llvm::MCSectionELF::getOffsets () const inline
Definition at line 92 of file MCSectionELF.h.
getType()
unsigned llvm::MCSectionELF::getType () const inline
Definition at line 73 of file MCSectionELF.h.
Referenced by llvm::ELFObjectWriter::usesRela().
getUniqueID()
unsigned llvm::MCSectionELF::getUniqueID () const inline
Definition at line 81 of file MCSectionELF.h.
Referenced by llvm::MCObjectFileInfo::getBBAddrMapSection(), llvm::MCObjectFileInfo::getCallGraphSection(), llvm::MCObjectFileInfo::getKCFITrapSection(), and llvm::MCObjectFileInfo::getStackSizesSection().
isComdat()
bool llvm::MCSectionELF::isComdat () const inline
Definition at line 78 of file MCSectionELF.h.
isUnique()
bool llvm::MCSectionELF::isUnique () const inline
Definition at line 80 of file MCSectionELF.h.
References llvm::MCSection::NonUniqueID.
setFlags()
void llvm::MCSectionELF::setFlags (unsigned F) inline
Definition at line 76 of file MCSectionELF.h.
References F.
setOffsets()
void llvm::MCSectionELF::setOffsets (uint64_t Start, uint64_t End) inline
Definition at line 88 of file MCSectionELF.h.
Friends And Related Symbol Documentation
MCAsmInfoELF
friend class MCAsmInfoELF friend
Definition at line 55 of file MCSectionELF.h.
References MCAsmInfoELF, llvm::MCSection::MCSection(), llvm::MCSection::Name, and llvm::ELF::SHF_GROUP.
Referenced by MCAsmInfoELF.
MCContext
friend class MCContext friend
Definition at line 54 of file MCSectionELF.h.
References MCContext.
Referenced by MCContext.
The documentation for this class was generated from the following file:
include/llvm/MC/MCSectionELF.h