LLVM: llvm::DIContext Class Reference
llvm::DIContext Class Reference abstract
#include "llvm/DebugInfo/DIContext.h"
Public Types
enum DIContextKind { CK_DWARF , CK_PDB , CK_BTF , CK_GSYM }
Public Member Functions
DIContext (DIContextKind K)
virtual ~DIContext ()=default
DIContextKind getKind () const
virtual void dump (raw_ostream &OS, DIDumpOptions DumpOpts)=0
virtual bool verify (raw_ostream &OS, DIDumpOptions DumpOpts={})
virtual std::optional< DILineInfo > getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual std::optional< DILineInfo > getLineInfoForDataAddress (object::SectionedAddress Address)=0
virtual DILineInfoTable getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DIInliningInfo getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual std::vector< DILocal > getLocalsForAddress (object::SectionedAddress Address)=0
Detailed Description
Definition at line 242 of file DIContext.h.
Member Enumeration Documentation
DIContextKind
enum llvm::DIContext::DIContextKind
Enumerator
CK_DWARF
CK_PDB
CK_BTF
CK_GSYM
Definition at line 244 of file DIContext.h.
Constructor & Destructor Documentation
DIContext()
llvm::DIContext::DIContext (DIContextKind K) inline
Definition at line 246 of file DIContext.h.
Referenced by llvm::BTFContext::BTFContext(), llvm::DWARFContext::classof(), llvm::gsym::GsymContext::classof(), llvm::pdb::PDBContext::classof(), llvm::DWARFContext::DWARFContext(), llvm::gsym::GsymContext::GsymContext(), and llvm::pdb::PDBContext::PDBContext().
~DIContext()
virtual llvm::DIContext::~DIContext () virtual default
Member Function Documentation
dump()
virtual void llvm::DIContext::dump (raw_ostream & OS, DIDumpOptions DumpOpts) pure virtual
Implemented in llvm::BTFContext, llvm::DWARFContext, llvm::gsym::GsymContext, and llvm::pdb::PDBContext.
getInliningInfoForAddress()
virtual DIInliningInfo llvm::DIContext::getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::BTFContext, llvm::DWARFContext, llvm::gsym::GsymContext, and llvm::pdb::PDBContext.
getKind()
DIContextKind llvm::DIContext::getKind () const inline
Definition at line 249 of file DIContext.h.
Referenced by llvm::DWARFContext::classof(), llvm::gsym::GsymContext::classof(), and llvm::pdb::PDBContext::classof().
getLineInfoForAddress()
virtual std::optional< DILineInfo > llvm::DIContext::getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::BTFContext, llvm::DWARFContext, llvm::gsym::GsymContext, and llvm::pdb::PDBContext.
getLineInfoForAddressRange()
virtual DILineInfoTable llvm::DIContext::getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::BTFContext, llvm::DWARFContext, llvm::gsym::GsymContext, and llvm::pdb::PDBContext.
getLineInfoForDataAddress()
virtual std::optional< DILineInfo > llvm::DIContext::getLineInfoForDataAddress (object::SectionedAddress Address) pure virtual
Implemented in llvm::BTFContext, llvm::DWARFContext, llvm::gsym::GsymContext, and llvm::pdb::PDBContext.
getLocalsForAddress()
virtual std::vector< DILocal > llvm::DIContext::getLocalsForAddress (object::SectionedAddress Address) pure virtual
Implemented in llvm::BTFContext, llvm::DWARFContext, llvm::gsym::GsymContext, and llvm::pdb::PDBContext.
verify()
virtual bool llvm::DIContext::verify (raw_ostream & OS, DIDumpOptions DumpOpts = {}) inline virtual
Reimplemented in llvm::DWARFContext.
Definition at line 253 of file DIContext.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DIContext.h