LLVM: llvm::FunctionImporter::ImportIDTable Class Reference
llvm::FunctionImporter::ImportIDTable Class Reference
#include "llvm/Transforms/IPO/FunctionImport.h"
Public Types
using ImportIDTy = uint32_t
Public Member Functions
ImportIDTable ()=default
ImportIDTable (const ImportIDTable &)=delete
ImportIDTable & operator= (const ImportIDTable &)=delete
std::pair< ImportIDTy, ImportIDTy > createImportIDs (StringRef FromModule, GlobalValue::GUID GUID)
std::optional< std::pair< ImportIDTy, ImportIDTy > > getImportIDs (StringRef FromModule, GlobalValue::GUID GUID)
std::tuple< StringRef, GlobalValue::GUID, GlobalValueSummary::ImportKind > lookup (ImportIDTy ImportID) const
std::tuple< StringRef, GlobalValue::GUID, GlobalValueSummary::ImportKind > operator() (ImportIDTable::ImportIDTy ImportID) const
Detailed Description
Definition at line 111 of file FunctionImport.h.
Member Typedef Documentation
ImportIDTy
using llvm::FunctionImporter::ImportIDTable::ImportIDTy = uint32_t
Definition at line 113 of file FunctionImport.h.
Constructor & Destructor Documentation
ImportIDTable() [1/2]
llvm::FunctionImporter::ImportIDTable::ImportIDTable () default
Referenced by ImportIDTable(), and operator=().
ImportIDTable() [2/2]
llvm::FunctionImporter::ImportIDTable::ImportIDTable (const ImportIDTable &) delete
References ImportIDTable().
Member Function Documentation
createImportIDs()
std::pair< ImportIDTy, ImportIDTy > llvm::FunctionImporter::ImportIDTable::createImportIDs (StringRef FromModule, GlobalValue::GUID GUID) inline
Definition at line 124 of file FunctionImport.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
getImportIDs()
std::optional< std::pair< ImportIDTy, ImportIDTy > > llvm::FunctionImporter::ImportIDTable::getImportIDs (StringRef FromModule, GlobalValue::GUID GUID) inline
Definition at line 134 of file FunctionImport.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
lookup()
std::tuple< StringRef, GlobalValue::GUID, GlobalValueSummary::ImportKind > llvm::FunctionImporter::ImportIDTable::lookup (ImportIDTy ImportID) const inline
Definition at line 145 of file FunctionImport.h.
References llvm::GlobalValueSummary::Declaration, and llvm::GlobalValueSummary::Definition.
Referenced by operator()().
operator()()
std::tuple< StringRef, GlobalValue::GUID, GlobalValueSummary::ImportKind > llvm::FunctionImporter::ImportIDTable::operator() (ImportIDTable::ImportIDTy ImportID) const inline
Definition at line 157 of file FunctionImport.h.
References lookup().
operator=()
ImportIDTable & llvm::FunctionImporter::ImportIDTable::operator= (const ImportIDTable &) delete
References ImportIDTable().
The documentation for this class was generated from the following file:
include/llvm/Transforms/IPO/FunctionImport.h