LLVM: llvm::codeview::ExportSym Class Reference
llvm::codeview::ExportSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
ExportSym (SymbolRecordKind Kind)
ExportSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
uint16_t Ordinal = 0
ExportFlags Flags = ExportFlags::None
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 705 of file SymbolRecord.h.
Constructor & Destructor Documentation
ExportSym() [1/2]
llvm::codeview::ExportSym::ExportSym (SymbolRecordKind Kind) inline explicit
Definition at line 707 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by ExportSym().
ExportSym() [2/2]
llvm::codeview::ExportSym::ExportSym (uint32_t RecordOffset) inline explicit
Definition at line 708 of file SymbolRecord.h.
References ExportSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Data Documentation
Flags
ExportFlags llvm::codeview::ExportSym::Flags = ExportFlags::None
Definition at line 712 of file SymbolRecord.h.
Name
StringRef llvm::codeview::ExportSym::Name
Definition at line 713 of file SymbolRecord.h.
Ordinal
uint16_t llvm::codeview::ExportSym::Ordinal = 0
Definition at line 711 of file SymbolRecord.h.
RecordOffset
uint32_t llvm::codeview::ExportSym::RecordOffset = 0
Definition at line 715 of file SymbolRecord.h.
Referenced by ExportSym().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h