LLVM: llvm::sandboxir::UseSet Class Reference
llvm::sandboxir::UseSet Class Reference
Tracks the change of the source Value of a sandboxir::Use.
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
UseSet (const Use &U)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Tracks the change of the source Value of a sandboxir::Use.
Definition at line 140 of file Tracker.h.
Constructor & Destructor Documentation
UseSet()
llvm::sandboxir::UseSet::UseSet (const Use & U) inline
Definition at line 145 of file Tracker.h.
References llvm::sandboxir::get().
Member Function Documentation
accept()
void llvm::sandboxir::UseSet::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 147 of file Tracker.h.
dump() [1/2]
void UseSet::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 80 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::UseSet::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 149 of file Tracker.h.
revert()
void llvm::sandboxir::UseSet::revert (Tracker & Tracker) inline final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 146 of file Tracker.h.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp