LLVM: llvm::jitlink::x86_64::GOTTableManager Class Reference
llvm::jitlink::x86_64::GOTTableManager Class Reference
Global Offset Table Builder.
#include "llvm/ExecutionEngine/JITLink/x86_64.h"
Public Member Functions
GOTTableManager (LinkGraph &G)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< GOTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Detailed Description
Global Offset Table Builder.
Definition at line 671 of file x86_64.h.
Constructor & Destructor Documentation
GOTTableManager()
llvm::jitlink::x86_64::GOTTableManager::GOTTableManager (LinkGraph & G) inline
Definition at line 675 of file x86_64.h.
References G, and getSectionName().
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::x86_64::GOTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 719 of file x86_64.h.
References llvm::jitlink::x86_64::createAnonymousPointer(), and G.
getSectionName()
StringRef llvm::jitlink::x86_64::GOTTableManager::getSectionName () inline static
Definition at line 673 of file x86_64.h.
Referenced by GOTTableManager().
visitEdge()
bool llvm::jitlink::x86_64::GOTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 680 of file x86_64.h.
References assert(), B(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::jitlink::x86_64::Delta32, llvm::jitlink::x86_64::Delta64, llvm::jitlink::x86_64::Delta64FromGOT, E(), llvm::formatv(), G, llvm::jitlink::TableManager< GOTTableManager >::getEntryForTarget(), llvm::jitlink::x86_64::PCRel32GOTLoadRelaxable, llvm::jitlink::x86_64::PCRel32GOTLoadREXRelaxable, llvm::jitlink::x86_64::RequestGOTAndTransformToDelta32, llvm::jitlink::x86_64::RequestGOTAndTransformToDelta64, llvm::jitlink::x86_64::RequestGOTAndTransformToDelta64FromGOT, llvm::jitlink::x86_64::RequestGOTAndTransformToPCRel32GOTLoadRelaxable, and llvm::jitlink::x86_64::RequestGOTAndTransformToPCRel32GOTLoadREXRelaxable.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/x86_64.h
lib/ExecutionEngine/JITLink/x86_64.cpp