LLVM: llvm::VerifierPass Class Reference
llvm::VerifierPass Class Reference
Create a verifier pass.
#include "llvm/IR/Verifier.h"
Public Member Functions
VerifierPass (bool FatalErrors=true)
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
LLVM_ABI PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< VerifierPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< VerifierPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Create a verifier pass.
Check a module or function for validity. This is essentially a pass wrapped around the above verifyFunction and verifyModule routines and functionality. When the pass detects a verification error it is always printed to stderr, and by default they are fatal. You can override that by passing false to FatalErrors.
Note that this creates a pass suitable for the legacy pass manager. It has nothing to do with VerifierPass.
Definition at line 134 of file Verifier.h.
Constructor & Destructor Documentation
VerifierPass()
llvm::VerifierPass::VerifierPass (bool FatalErrors = true) inline explicit
Definition at line 138 of file Verifier.h.
Member Function Documentation
isRequired()
bool llvm::VerifierPass::isRequired () inline static
Definition at line 142 of file Verifier.h.
run() [1/2]
PreservedAnalyses VerifierPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 8203 of file Verifier.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::report_fatal_error().
run() [2/2]
PreservedAnalyses VerifierPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 8195 of file Verifier.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::report_fatal_error().
The documentation for this class was generated from the following files:
include/llvm/IR/Verifier.h
lib/IR/Verifier.cpp