LLVM: llvm::AMDGPU::SetOfRulesForOpcode Class Reference
llvm::AMDGPU::SetOfRulesForOpcode Class Reference
#include "Target/AMDGPU/AMDGPURegBankLegalizeRules.h"
Public Member Functions
SetOfRulesForOpcode ()
SetOfRulesForOpcode (FastRulesTypes FastTypes)
const RegBankLLTMapping * findMappingForMI (const MachineInstr &MI, const MachineRegisterInfo &MRI, const MachineUniformityInfo &MUI) const
void addRule (RegBankLegalizeRule Rule)
void addFastRuleDivergent (UniformityLLTOpPredicateID Ty, RegBankLLTMapping RuleApplyIDs)
void addFastRuleUniform (UniformityLLTOpPredicateID Ty, RegBankLLTMapping RuleApplyIDs)
Detailed Description
Definition at line 272 of file AMDGPURegBankLegalizeRules.h.
Constructor & Destructor Documentation
SetOfRulesForOpcode() [1/2]
SetOfRulesForOpcode::SetOfRulesForOpcode () default
References MI, and MRI.
SetOfRulesForOpcode() [2/2]
SetOfRulesForOpcode::SetOfRulesForOpcode (FastRulesTypes FastTypes)
Definition at line 215 of file AMDGPURegBankLegalizeRules.cpp.
Member Function Documentation
addFastRuleDivergent()
void SetOfRulesForOpcode::addFastRuleDivergent (UniformityLLTOpPredicateID Ty, RegBankLLTMapping RuleApplyIDs)
Definition at line 283 of file AMDGPURegBankLegalizeRules.cpp.
References assert().
addFastRuleUniform()
void SetOfRulesForOpcode::addFastRuleUniform (UniformityLLTOpPredicateID Ty, RegBankLLTMapping RuleApplyIDs)
Definition at line 290 of file AMDGPURegBankLegalizeRules.cpp.
References assert().
addRule()
void SetOfRulesForOpcode::addRule (RegBankLegalizeRule Rule)
Definition at line 279 of file AMDGPURegBankLegalizeRules.cpp.
findMappingForMI()
const RegBankLLTMapping * SetOfRulesForOpcode::findMappingForMI (const MachineInstr & MI, const MachineRegisterInfo & MRI, const MachineUniformityInfo & MUI) const
Definition at line 251 of file AMDGPURegBankLegalizeRules.cpp.
References llvm::GenericUniformityInfo< ContextT >::isUniform(), LLTToBId(), LLTToId(), MI, MRI, llvm::AMDGPU::NoFastRules, and llvm::AMDGPU::StandardB.
Referenced by llvm::AMDGPU::RegBankLegalizeHelper::findRuleAndApplyMapping().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPURegBankLegalizeRules.h
lib/Target/AMDGPU/AMDGPURegBankLegalizeRules.cpp