LLVM: llvm::cas::ActionCache Class Reference
llvm::cas::ActionCache Class Reference abstract
A cache from a key (that describes an action) to the result of performing that action.
#include "llvm/CAS/ActionCache.h"
Public Member Functions
Expected< std::optional< CASID > > get (const CacheKey &ActionKey, bool CanBeDistributed=false) const
Get a previously computed result for ActionKey.
Error put (const CacheKey &ActionKey, const CASID &Result, bool CanBeDistributed=false)
Cache Result for the ActionKey computation.
virtual Error validate () const =0
Validate the ActionCache contents.
virtual ~ActionCache ()=default
Protected Member Functions
virtual Expected< std::optional< CASID > > getImpl (ArrayRef< uint8_t > ResolvedKey, bool CanBeDistributed) const =0
virtual Error putImpl (ArrayRef< uint8_t > ResolvedKey, const CASID &Result, bool CanBeDistributed)=0
ActionCache (const CASContext &Context)
const CASContext & getContext () const
Detailed Description
A cache from a key (that describes an action) to the result of performing that action.
Actions are expected to be pure. Storing mappings from one action to multiple results will result in error (cache poisoning).
Definition at line 49 of file ActionCache.h.
Constructor & Destructor Documentation
~ActionCache()
virtual llvm::cas::ActionCache::~ActionCache () virtual default
ActionCache()
llvm::cas::ActionCache::ActionCache (const CASContext & Context) inline protected
Definition at line 92 of file ActionCache.h.
Member Function Documentation
get()
Expected< std::optional< CASID > > llvm::cas::ActionCache::get (const CacheKey & ActionKey, bool CanBeDistributed = false) const inline
Get a previously computed result for ActionKey.
Parameters
CanBeDistributed is a hint to the underlying implementation that if it is true, the lookup is profitable to be done on a distributed caching level, not just locally. The implementation is free to ignore this flag.
Definition at line 58 of file ActionCache.h.
References getImpl(), and llvm::cas::CacheKey::getKey().
getContext()
const CASContext & llvm::cas::ActionCache::getContext () const inline protected
Definition at line 94 of file ActionCache.h.
Referenced by put().
getImpl()
virtual Expected< std::optional< CASID > > llvm::cas::ActionCache::getImpl (ArrayRef< uint8_t > ResolvedKey, bool CanBeDistributed) const protected pure virtual
Referenced by get().
put()
Error llvm::cas::ActionCache::put (const CacheKey & ActionKey, const CASID & Result, bool CanBeDistributed = false) inline
Cache Result for the ActionKey computation.
Parameters
CanBeDistributed is a hint to the underlying implementation that if it is true, the association is profitable to be done on a distributed caching level, not just locally. The implementation is free to ignore this flag.
Definition at line 69 of file ActionCache.h.
References assert(), getContext(), llvm::cas::CacheKey::getKey(), and putImpl().
putImpl()
virtual Error llvm::cas::ActionCache::putImpl (ArrayRef< uint8_t > ResolvedKey, const CASID & Result, bool CanBeDistributed) protected pure virtual
Referenced by put().
validate()
virtual Error llvm::cas::ActionCache::validate () const pure virtual
Validate the ActionCache contents.
The documentation for this class was generated from the following files:
include/llvm/CAS/ActionCache.h
lib/CAS/ActionCache.cpp