LLVM: llvm::TextEncodingConverter Class Reference
llvm::TextEncodingConverter Class Reference
Utility class to convert between different character encodings.
#include "llvm/Support/TextEncoding.h"
Public Member Functions
TextEncodingConverter (const TextEncodingConverter &)=delete
TextEncodingConverter & operator= (const TextEncodingConverter &)=delete
TextEncodingConverter (TextEncodingConverter &&Other)
TextEncodingConverter & operator= (TextEncodingConverter &&Other)
~TextEncodingConverter ()=default
std::error_code convert (StringRef Source, SmallVectorImpl< char > &Result) const
Converts a string.
ErrorOr< std::string > convert (StringRef Source) const
Static Public Member Functions
static LLVM_ABI ErrorOr< TextEncodingConverter > create (TextEncoding From, TextEncoding To)
Creates a TextEncodingConverter instance.
static LLVM_ABI ErrorOr< TextEncodingConverter > create (StringRef From, StringRef To)
Creates a TextEncodingConverter instance.
Detailed Description
Utility class to convert between different character encodings.
Definition at line 82 of file TextEncoding.h.
Constructor & Destructor Documentation
TextEncodingConverter() [1/2]
llvm::TextEncodingConverter::TextEncodingConverter (const TextEncodingConverter &) delete
TextEncodingConverter() [2/2]
llvm::TextEncodingConverter::TextEncodingConverter (TextEncodingConverter && Other) inline
Definition at line 111 of file TextEncoding.h.
References llvm::move().
~TextEncodingConverter()
llvm::TextEncodingConverter::~TextEncodingConverter () default
Member Function Documentation
convert() [1/2]
ErrorOr< std::string > llvm::TextEncodingConverter::convert (StringRef Source) const inline
Definition at line 131 of file TextEncoding.h.
convert() [2/2]
std::error_code llvm::TextEncodingConverter::convert (StringRef Source, SmallVectorImpl< char > & Result) const inline
Converts a string.
Parameters
[in] Source source string
[out] Result container for converted string
Returns
error code in case something went wrong
Definition at line 126 of file TextEncoding.h.
create() [1/2]
ErrorOr< TextEncodingConverter > TextEncodingConverter::create (StringRef From, StringRef To) static
Creates a TextEncodingConverter instance.
Returns std::errc::invalid_argument in case the requested conversion is not supported.
Parameters
[in] From name of the source character encoding
[in] To name of the target character encoding
Returns
a TextEncodingConverter instance or an error code
Definition at line 322 of file TextEncoding.cpp.
References create(), getKnownEncoding(), and llvm::StringRef::str().
create() [2/2]
ErrorOr< TextEncodingConverter > TextEncodingConverter::create (TextEncoding From, TextEncoding To) static
Creates a TextEncodingConverter instance.
Returns std::errc::invalid_argument in case the requested conversion is not supported.
Parameters
[in] From the source character encoding
[in] To the target character encoding
Returns
a TextEncodingConverter instance or an error code
Definition at line 304 of file TextEncoding.cpp.
References Conversion, llvm::IBM1047, and llvm::UTF8.
Referenced by create().
operator=() [1/2]
TextEncodingConverter & llvm::TextEncodingConverter::operator= (const TextEncodingConverter &) delete
operator=() [2/2]
TextEncodingConverter & llvm::TextEncodingConverter::operator= (TextEncodingConverter && Other) inline
Definition at line 114 of file TextEncoding.h.
References llvm::Other.
The documentation for this class was generated from the following files:
include/llvm/Support/TextEncoding.h
lib/Support/TextEncoding.cpp