LLVM: llvm::logicalview::LVElement Class Reference
llvm::logicalview::LVElement Class Reference
#include "llvm/DebugInfo/LogicalView/Core/LVElement.h"
Public Member Functions
LVElement (LVSubclassID ID)
LVElement (const LVElement &)=delete
LVElement & operator= (const LVElement &)=delete
~LVElement () override=default
LVSubclassID getSubclassID () const
PROPERTY (Property, IsLine)
PROPERTY (Property, IsScope)
PROPERTY (Property, IsSymbol)
PROPERTY (Property, IsType)
PROPERTY (Property, IsEnumClass)
PROPERTY (Property, IsExternal)
PROPERTY (Property, HasType)
PROPERTY (Property, HasAugmentedName)
PROPERTY (Property, IsTypedefReduced)
PROPERTY (Property, IsArrayResolved)
PROPERTY (Property, IsMemberPointerResolved)
PROPERTY (Property, IsTemplateResolved)
PROPERTY (Property, IsInlined)
PROPERTY (Property, IsInlinedAbstract)
PROPERTY (Property, InvalidFilename)
PROPERTY (Property, HasReference)
PROPERTY (Property, HasReferenceAbstract)
PROPERTY (Property, HasReferenceExtension)
PROPERTY (Property, HasReferenceSpecification)
PROPERTY (Property, QualifiedResolved)
PROPERTY (Property, IncludeInPrint)
PROPERTY (Property, IsStatic)
PROPERTY (Property, TransformName)
PROPERTY (Property, IsScoped)
PROPERTY (Property, IsNested)
PROPERTY (Property, IsScopedAlready)
PROPERTY (Property, IsArtificial)
PROPERTY (Property, IsReferencedType)
PROPERTY (Property, IsSystem)
PROPERTY (Property, OffsetFromTypeIndex)
PROPERTY (Property, IsAnonymous)
bool isNamed () const override
bool isTyped () const override
bool isFiled () const override
bool getIsKindType () const
bool getIsKindScope () const
StringRef getName () const override
void setName (StringRef ElementName) override
StringRef getPathname () const
void setFilename (StringRef Filename)
void setQualifiedName (StringRef Name)
StringRef getQualifiedName () const
size_t getNameIndex () const
size_t getQualifiedNameIndex () const
void setInnerComponent ()
void setInnerComponent (StringRef Name)
StringRef getTypeName () const
virtual StringRef getProducer () const
virtual void setProducer (StringRef ProducerName)
virtual LVSourceLanguage getSourceLanguage () const
virtual void setSourceLanguage (LVSourceLanguage SL)
virtual bool isCompileUnit () const
virtual bool isRoot () const
virtual void setReference (LVElement *Element)
virtual void setReference (LVScope *Scope)
virtual void setReference (LVSymbol *Symbol)
virtual void setReference (LVType *Type)
virtual void setLinkageName (StringRef LinkageName)
virtual StringRef getLinkageName () const
virtual size_t getLinkageNameIndex () const
virtual uint32_t getCallLineNumber () const
virtual void setCallLineNumber (uint32_t Number)
virtual size_t getCallFilenameIndex () const
virtual void setCallFilenameIndex (size_t Index)
size_t getFilenameIndex () const
void setFilenameIndex (size_t Index)
void setFile (LVElement *Reference=nullptr)
virtual bool isBase () const
virtual bool isTemplateParam () const
uint32_t getStorageSizeInBytes () const
virtual uint32_t getBitSize () const
virtual void setBitSize (uint32_t Size)
virtual int64_t getCount () const
virtual void setCount (int64_t Value)
virtual int64_t getLowerBound () const
virtual void setLowerBound (int64_t Value)
virtual int64_t getUpperBound () const
virtual void setUpperBound (int64_t Value)
virtual std::pair< unsigned, unsigned > getBounds () const
virtual void setBounds (unsigned Lower, unsigned Upper)
virtual uint32_t getDiscriminator () const
virtual void setDiscriminator (uint32_t Value)
virtual StringRef getValue () const
virtual void setValue (StringRef Value)
virtual size_t getValueIndex () const
uint32_t getAccessibilityCode () const
void setAccessibilityCode (uint32_t Access)
StringRef accessibilityString (uint32_t Access=dwarf::DW_ACCESS_private) const
std::optional< uint32_t > getAccessibilityCode (codeview::MemberAccess Access)
void setAccessibilityCode (codeview::MemberAccess Access)
uint32_t getInlineCode () const
void setInlineCode (uint32_t Code)
StringRef inlineCodeString (uint32_t Code) const
uint32_t getVirtualityCode () const
void setVirtualityCode (uint32_t Virtuality)
StringRef virtualityString (uint32_t Virtuality=dwarf::DW_VIRTUALITY_none) const
std::optional< uint32_t > getVirtualityCode (codeview::MethodKind Virtuality)
void setVirtualityCode (codeview::MethodKind Virtuality)
StringRef externalString () const
LVElement * getType () const
LVType * getTypeAsType () const
LVScope * getTypeAsScope () const
void setType (LVElement *Element=nullptr)
void setGenericType (LVElement *Element)
StringRef getTypeQualifiedName () const
StringRef typeAsString () const
std::string typeOffsetAsString () const
std::string discriminatorAsString () const
LVScope * traverseParents (LVScopeGetFunction GetFunction) const
LVScope * getFunctionParent () const
virtual LVScope * getCompileUnitParent () const
void printReference (raw_ostream &OS, bool Full, LVElement *Parent) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent, LVScope *Scope) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent) const
void resolveFullname (LVElement *BaseType, StringRef Name=emptyString())
void generateName (std::string &Prefix) const
void generateName ()
virtual bool removeElement (LVElement *Element)
virtual void updateLevel (LVScope *Parent, bool Moved=false)
virtual void resolve ()
virtual void resolveExtra ()
virtual void resolveName ()
virtual void resolveReferences ()
void resolveParents ()
bool referenceMatch (const LVElement *Element) const
bool equals (const LVElement *Element) const
virtual void report (LVComparePass Pass)
Public Member Functions inherited from llvm::logicalview::LVObject
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
virtual LVAddress getLowerAddress () const
virtual void setLowerAddress (LVAddress Address)
virtual LVAddress getUpperAddress () const
virtual void setUpperAddress (LVAddress Address)
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
virtual const char * kind () const
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
virtual std::string noLineAsString (bool ShowZero) const
virtual std::string lineNumberAsString (bool ShowZero=false) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
virtual Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
virtual void print (raw_ostream &OS, bool Full=true) const
virtual void printExtra (raw_ostream &OS, bool Full=true) const
void dump () const
uint32_t getID () const
Static Public Member Functions
static LVElementDispatch & getDispatch ()
Protected Member Functions
void printFileIndex (raw_ostream &OS, bool Full=true) const override
Protected Member Functions inherited from llvm::logicalview::LVObject
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
Protected Attributes
LVElement * ElementType = nullptr
Detailed Description
Definition at line 75 of file LVElement.h.
Constructor & Destructor Documentation
LVElement() [1/2]
llvm::logicalview::LVElement::LVElement (LVSubclassID ID) inline
Definition at line 141 of file LVElement.h.
Referenced by llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVLine::classof(), llvm::logicalview::LVScope::classof(), llvm::logicalview::LVSymbol::classof(), llvm::logicalview::LVType::classof(), llvm::logicalview::LVScope::doPrint(), equals(), getType(), llvm::logicalview::LVType::getUnderlyingType(), LVElement(), llvm::logicalview::LVLine::LVLine(), llvm::logicalview::LVScope::LVScope(), llvm::logicalview::LVSymbol::LVSymbol(), llvm::logicalview::LVType::LVType(), operator=(), printLinkageName(), printLinkageName(), printReference(), referenceMatch(), removeElement(), llvm::logicalview::LVScope::removeElement(), llvm::logicalview::LVScope::report(), llvm::logicalview::LVScope::resolve(), resolveFullname(), llvm::logicalview::LVScope::resolveName(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVScope::resolveReferences(), llvm::logicalview::LVSymbol::resolveReferences(), llvm::logicalview::LVType::resolveReferences(), setFile(), setGenericType(), setReference(), llvm::logicalview::LVSymbol::setReference(), setType(), llvm::logicalview::LVType::setUnderlyingType(), typeOffsetAsString(), and llvm::logicalview::LVScope::updateLevel().
LVElement() [2/2]
llvm::logicalview::LVElement::LVElement (const LVElement &) delete
References LVElement().
~LVElement()
llvm::logicalview::LVElement::~LVElement () override default
Member Function Documentation
accessibilityString()
StringRef LVElement::accessibilityString (uint32_t Access = dwarf::DW_ACCESS_private) const
Definition at line 123 of file LVElement.cpp.
References Access, llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, and getAccessibilityCode().
Referenced by llvm::logicalview::LVScopeFunction::printExtra(), and llvm::logicalview::LVTypeImport::printExtra().
discriminatorAsString()
std::string LVElement::discriminatorAsString () const
Definition at line 58 of file LVElement.cpp.
References llvm::logicalview::Discriminator, getDiscriminator(), llvm::logicalview::options(), and llvm::String.
Referenced by llvm::logicalview::LVScopeFunction::printExtra().
equals()
bool LVElement::equals (const LVElement * Element) const
Definition at line 474 of file LVElement.cpp.
References llvm::dbgs(), llvm::logicalview::LVObject::Element, equals(), llvm::logicalview::formattedKind(), llvm::logicalview::formattedName(), getFilenameIndex(), llvm::logicalview::LVObject::getLevel(), llvm::logicalview::LVObject::getLineNumber(), getName(), getNameIndex(), llvm::logicalview::LVObject::getOffset(), getQualifiedName(), getQualifiedNameIndex(), getType(), llvm::logicalview::hexSquareString(), llvm::logicalview::LVObject::kind(), LLVM_DEBUG, LVElement(), and llvm::logicalview::options().
Referenced by equals(), llvm::logicalview::LVLine::equals(), llvm::logicalview::LVScope::equals(), llvm::logicalview::LVSymbol::equals(), llvm::logicalview::LVType::equals(), and llvm::logicalview::LVTypeParam::equals().
externalString()
StringRef LVElement::externalString () const
Definition at line 150 of file LVElement.cpp.
Referenced by llvm::logicalview::LVScopeFunction::printExtra().
generateName() [1/2]
void LVElement::generateName ()
Definition at line 258 of file LVElement.cpp.
References generateName(), llvm::logicalview::Name, and setName().
Referenced by generateName(), llvm::logicalview::LVScope::resolveName(), and llvm::logicalview::LVType::resolveName().
generateName() [2/2]
void LVElement::generateName (std::string & Prefix) const
Definition at line 243 of file LVElement.cpp.
References llvm::erase_if(), llvm::logicalview::LVObject::getParentScope(), llvm::logicalview::LVObject::isLined(), llvm::logicalview::LVObject::lineNumberAsString(), and llvm::logicalview::LVObject::Scope.
getAccessibilityCode() [1/2]
uint32_t llvm::logicalview::LVElement::getAccessibilityCode () const inline
Definition at line 278 of file LVElement.h.
Referenced by accessibilityString(), and setAccessibilityCode().
getAccessibilityCode() [2/2]
std::optional< uint32_t > LVElement::getAccessibilityCode (codeview::MemberAccess Access)
Definition at line 137 of file LVElement.cpp.
References Access, llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::codeview::Private, llvm::codeview::Protected, and llvm::codeview::Public.
getBitSize()
virtual uint32_t llvm::logicalview::LVElement::getBitSize () const inline virtual
Reimplemented in llvm::logicalview::LVScope, llvm::logicalview::LVSymbol, and llvm::logicalview::LVType.
Definition at line 256 of file LVElement.h.
Referenced by getStorageSizeInBytes().
getBounds()
virtual std::pair< unsigned, unsigned > llvm::logicalview::LVElement::getBounds () const inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 265 of file LVElement.h.
getCallFilenameIndex()
virtual size_t llvm::logicalview::LVElement::getCallFilenameIndex () const inline virtual
Reimplemented in llvm::logicalview::LVScopeFunctionInlined.
Definition at line 242 of file LVElement.h.
getCallLineNumber()
virtual uint32_t llvm::logicalview::LVElement::getCallLineNumber () const inline virtual
Reimplemented in llvm::logicalview::LVScopeFunctionInlined.
Definition at line 240 of file LVElement.h.
getCompileUnitParent()
LVScope * LVElement::getCompileUnitParent () const virtual
Reimplemented in llvm::logicalview::LVScope, and llvm::logicalview::LVScopeCompileUnit.
Definition at line 429 of file LVElement.cpp.
References traverseParents().
Referenced by llvm::logicalview::LVScope::getCompileUnitParent().
getCount()
virtual int64_t llvm::logicalview::LVElement::getCount () const inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 259 of file LVElement.h.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord().
getDiscriminator()
virtual uint32_t llvm::logicalview::LVElement::getDiscriminator () const inline virtual
Reimplemented in llvm::logicalview::LVLineDebug, and llvm::logicalview::LVScopeFunctionInlined.
Definition at line 269 of file LVElement.h.
Referenced by discriminatorAsString(), and llvm::logicalview::LVLine::lineNumberAsString().
getDispatch()
LVElementDispatch & llvm::logicalview::LVElement::getDispatch () inline static
Definition at line 377 of file LVElement.h.
Referenced by llvm::logicalview::LVPatterns::LVPatterns().
getFilenameIndex()
size_t llvm::logicalview::LVElement::getFilenameIndex () const inline
Definition at line 244 of file LVElement.h.
Referenced by equals(), llvm::logicalview::LVLineDebug::equals(), llvm::logicalview::LVScopeAggregate::equals(), getPathname(), printFileIndex(), and setFile().
getFunctionParent()
LVScope * LVElement::getFunctionParent () const
Definition at line 425 of file LVElement.cpp.
References traverseParents().
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getInlineCode()
uint32_t llvm::logicalview::LVElement::getInlineCode () const inline
Definition at line 291 of file LVElement.h.
Referenced by inlineCodeString(), and llvm::logicalview::LVScopeFunction::printExtra().
getIsKindScope()
bool llvm::logicalview::LVElement::getIsKindScope () const inline
Definition at line 188 of file LVElement.h.
References ElementType.
Referenced by llvm::logicalview::LVTypeParam::encodeTemplateArgument().
getIsKindType()
bool llvm::logicalview::LVElement::getIsKindType () const inline
Definition at line 187 of file LVElement.h.
References ElementType.
Referenced by llvm::logicalview::LVTypeParam::encodeTemplateArgument().
getLinkageName()
virtual StringRef llvm::logicalview::LVElement::getLinkageName () const inline virtual
Reimplemented in llvm::logicalview::LVScopeFunction, and llvm::logicalview::LVSymbol.
Definition at line 237 of file LVElement.h.
Referenced by printLinkageName(), printLinkageName(), and llvm::logicalview::LVScope::resolveName().
getLinkageNameIndex()
virtual size_t llvm::logicalview::LVElement::getLinkageNameIndex () const inline virtual
Reimplemented in llvm::logicalview::LVScopeFunction, and llvm::logicalview::LVSymbol.
Definition at line 238 of file LVElement.h.
getLowerBound()
virtual int64_t llvm::logicalview::LVElement::getLowerBound () const inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 261 of file LVElement.h.
getName()
StringRef llvm::logicalview::LVElement::getName () const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 192 of file LVElement.h.
References llvm::logicalview::getStringPool().
Referenced by checkIntegrityScopesTree(), llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVTypeParam::encodeTemplateArgument(), equals(), llvm::logicalview::LVScopeModule::equals(), llvm::logicalview::LVTypeSubrange::equals(), llvm::logicalview::LVScope::getQualifiedName(), llvm::logicalview::LVLogicalVisitor::inlineSiteAnnotation(), llvm::logicalview::LVCodeViewReader::isSystemEntry(), llvm::logicalview::LVLineAssembler::printExtra(), llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeArray::printExtra(), llvm::logicalview::LVScopeCompileUnit::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFormalPack::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVScopeModule::printExtra(), llvm::logicalview::LVScopeNamespace::printExtra(), llvm::logicalview::LVScopeRoot::printExtra(), llvm::logicalview::LVScopeTemplatePack::printExtra(), llvm::logicalview::LVType::printExtra(), llvm::logicalview::LVTypeDefinition::printExtra(), llvm::logicalview::LVTypeEnumerator::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::logicalview::LVTypeParam::printExtra(), llvm::logicalview::LVTypeSubrange::printExtra(), llvm::logicalview::LVCompare::printItem(), llvm::logicalview::LVLogicalVisitor::printMemberBegin(), llvm::logicalview::LVLogicalVisitor::printTypeBegin(), llvm::logicalview::LVTypeDefinition::resolveExtra(), resolveFullname(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVScope::resolveReferencesChain(), llvm::logicalview::LVSymbol::resolveReferencesChain(), llvm::logicalview::LVType::resolveReferencesChain(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getNameIndex()
size_t llvm::logicalview::LVElement::getNameIndex () const inline
Definition at line 213 of file LVElement.h.
Referenced by equals(), and llvm::logicalview::LVScopeCompileUnit::equals().
getPathname()
StringRef llvm::logicalview::LVElement::getPathname () const inline
Definition at line 198 of file LVElement.h.
References getFilenameIndex(), and llvm::logicalview::getStringPool().
Referenced by llvm::logicalview::LVLineDebug::printExtra(), printFileIndex(), and llvm::logicalview::LVCompare::printItem().
getProducer()
virtual StringRef llvm::logicalview::LVElement::getProducer () const inline virtual
Reimplemented in llvm::logicalview::LVScopeCompileUnit.
Definition at line 222 of file LVElement.h.
getQualifiedName()
StringRef llvm::logicalview::LVElement::getQualifiedName () const inline
Definition at line 209 of file LVElement.h.
References llvm::logicalview::getStringPool().
Referenced by llvm::logicalview::LVScope::encodeTemplateArguments(), and equals().
getQualifiedNameIndex()
size_t llvm::logicalview::LVElement::getQualifiedNameIndex () const inline
Definition at line 214 of file LVElement.h.
Referenced by equals().
getSourceLanguage()
virtual LVSourceLanguage llvm::logicalview::LVElement::getSourceLanguage () const inline virtual
Reimplemented in llvm::logicalview::LVScopeCompileUnit.
Definition at line 225 of file LVElement.h.
getStorageSizeInBytes()
uint32_t llvm::logicalview::LVElement::getStorageSizeInBytes () const inline
Definition at line 253 of file LVElement.h.
References llvm::divideCeil(), llvm::logicalview::DWARF_CHAR_BIT, and getBitSize().
Referenced by llvm::logicalview::LVScope::printExtra(), and llvm::logicalview::LVType::printExtra().
getSubclassID()
LVSubclassID llvm::logicalview::LVElement::getSubclassID () const inline
Definition at line 148 of file LVElement.h.
getType()
LVElement * llvm::logicalview::LVElement::getType () const inline
Definition at line 311 of file LVElement.h.
References ElementType, and LVElement().
Referenced by equals(), llvm::logicalview::LVTypeParam::equals(), llvm::logicalview::LVTypeDefinition::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::logicalview::LVScopeArray::resolveExtra(), llvm::logicalview::LVTypeDefinition::resolveExtra(), llvm::logicalview::LVScope::resolveName(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVScope::resolveReferences(), llvm::logicalview::LVScopeFunction::resolveReferences(), llvm::logicalview::LVSymbol::resolveReferences(), llvm::logicalview::LVType::resolveReferences(), and typeOffsetAsString().
getTypeAsScope()
LVScope * LVElement::getTypeAsScope () const
Definition at line 35 of file LVElement.cpp.
References ElementType.
Referenced by llvm::logicalview::LVTypeParam::encodeTemplateArgument(), llvm::logicalview::LVTypeDefinition::getUnderlyingType(), and llvm::logicalview::LVTypeDefinition::resolveExtra().
getTypeAsType()
LVType * LVElement::getTypeAsType () const
Definition at line 29 of file LVElement.cpp.
References ElementType.
Referenced by llvm::logicalview::LVTypeParam::encodeTemplateArgument(), and llvm::logicalview::LVTypeDefinition::getUnderlyingType().
getTypeName()
StringRef LVElement::getTypeName () const
Definition at line 73 of file LVElement.cpp.
References ElementType.
Referenced by llvm::logicalview::LVTypeSubrange::equals(), llvm::logicalview::LVTypeParam::printExtra(), llvm::logicalview::LVTypeSubrange::printExtra(), llvm::logicalview::LVScopeArray::resolveExtra(), and typeAsString().
getTypeQualifiedName()
StringRef llvm::logicalview::LVElement::getTypeQualifiedName () const inline
Definition at line 326 of file LVElement.h.
References ElementType.
Referenced by llvm::logicalview::LVTypeParam::encodeTemplateArgument(), llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), and llvm::logicalview::LVTypeParam::printExtra().
getUpperBound()
virtual int64_t llvm::logicalview::LVElement::getUpperBound () const inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 263 of file LVElement.h.
getValue()
virtual StringRef llvm::logicalview::LVElement::getValue () const inline virtual
Reimplemented in llvm::logicalview::LVSymbol, llvm::logicalview::LVTypeEnumerator, and llvm::logicalview::LVTypeParam.
Definition at line 273 of file LVElement.h.
getValueIndex()
virtual size_t llvm::logicalview::LVElement::getValueIndex () const inline virtual
Reimplemented in llvm::logicalview::LVSymbol, llvm::logicalview::LVTypeEnumerator, and llvm::logicalview::LVTypeParam.
Definition at line 275 of file LVElement.h.
getVirtualityCode() [1/2]
uint32_t llvm::logicalview::LVElement::getVirtualityCode () const inline
Definition at line 296 of file LVElement.h.
Referenced by setVirtualityCode(), and virtualityString().
getVirtualityCode() [2/2]
std::optional< uint32_t > LVElement::getVirtualityCode (codeview::MethodKind Virtuality)
Definition at line 184 of file LVElement.cpp.
References llvm::codeview::IntroducingVirtual, llvm::codeview::PureIntroducingVirtual, llvm::codeview::PureVirtual, and llvm::codeview::Virtual.
inlineCodeString()
StringRef LVElement::inlineCodeString (uint32_t Code) const
Definition at line 154 of file LVElement.cpp.
References llvm::codeview::Code, llvm::dwarf::DW_INL_declared_inlined, llvm::dwarf::DW_INL_declared_not_inlined, llvm::dwarf::DW_INL_inlined, llvm::dwarf::DW_INL_not_inlined, and getInlineCode().
Referenced by llvm::logicalview::LVScopeFunction::printExtra().
isBase()
virtual bool llvm::logicalview::LVElement::isBase () const inline virtual
Reimplemented in llvm::logicalview::LVType.
Definition at line 250 of file LVElement.h.
isCompileUnit()
virtual bool llvm::logicalview::LVElement::isCompileUnit () const inline virtual
Reimplemented in llvm::logicalview::LVScope.
Definition at line 228 of file LVElement.h.
Referenced by resolveParents().
isFiled()
bool llvm::logicalview::LVElement::isFiled () const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 184 of file LVElement.h.
isNamed()
bool llvm::logicalview::LVElement::isNamed () const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 182 of file LVElement.h.
Referenced by llvm::logicalview::LVScopeAggregate::equals(), llvm::logicalview::LVScope::resolveName(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVScope::resolveReferencesChain(), and llvm::logicalview::LVSymbol::resolveReferencesChain().
isRoot()
virtual bool llvm::logicalview::LVElement::isRoot () const inline virtual
Reimplemented in llvm::logicalview::LVScope.
Definition at line 229 of file LVElement.h.
Referenced by resolveParents().
isTemplateParam()
virtual bool llvm::logicalview::LVElement::isTemplateParam () const inline virtual
Reimplemented in llvm::logicalview::LVType.
Definition at line 251 of file LVElement.h.
isTyped()
bool llvm::logicalview::LVElement::isTyped () const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 183 of file LVElement.h.
References ElementType.
operator=()
LVElement & llvm::logicalview::LVElement::operator= (const LVElement &) delete
References LVElement().
printFileIndex()
void LVElement::printFileIndex (raw_ostream & OS, bool Full = true) const override protected virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 519 of file LVElement.cpp.
References llvm::format(), llvm::logicalview::formattedName(), getFilenameIndex(), getPathname(), llvm::logicalview::options(), and llvm::logicalview::LVObject::printAttributes().
printLinkageName() [1/2]
void LVElement::printLinkageName (raw_ostream & OS, bool Full, LVElement * Parent) const
Definition at line 547 of file LVElement.cpp.
References llvm::Full, getLinkageName(), LVElement(), llvm::logicalview::options(), and llvm::logicalview::LVObject::printAttributes().
printLinkageName() [2/2]
void LVElement::printLinkageName (raw_ostream & OS, bool Full, LVElement * Parent, LVScope * Scope) const
Definition at line 555 of file LVElement.cpp.
References llvm::Full, getLinkageName(), llvm::logicalview::getReader(), llvm::logicalview::LVReader::getSectionIndex(), LVElement(), llvm::logicalview::options(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVObject::Scope, llvm::logicalview::Text, and llvm::Twine::utohexstr().
Referenced by llvm::logicalview::LVScopeFunction::printExtra(), and llvm::logicalview::LVSymbol::printExtra().
printReference()
void LVElement::printReference (raw_ostream & OS, bool Full, LVElement * Parent) const
Definition at line 539 of file LVElement.cpp.
References llvm::Full, llvm::logicalview::LVObject::getLineNumber(), LVElement(), llvm::logicalview::options(), llvm::logicalview::LVObject::printAttributes(), and llvm::logicalview::LVObject::referenceAsString().
PROPERTY() [1/31]
llvm::logicalview::LVElement::PROPERTY (Property , HasAugmentedName)
PROPERTY() [2/31]
llvm::logicalview::LVElement::PROPERTY (Property , HasReference)
PROPERTY() [3/31]
llvm::logicalview::LVElement::PROPERTY (Property , HasReferenceAbstract)
PROPERTY() [4/31]
llvm::logicalview::LVElement::PROPERTY (Property , HasReferenceExtension)
PROPERTY() [5/31]
llvm::logicalview::LVElement::PROPERTY (Property , HasReferenceSpecification)
PROPERTY() [6/31]
llvm::logicalview::LVElement::PROPERTY (Property , HasType)
PROPERTY() [7/31]
llvm::logicalview::LVElement::PROPERTY (Property , IncludeInPrint)
PROPERTY() [8/31]
llvm::logicalview::LVElement::PROPERTY (Property , InvalidFilename)
PROPERTY() [9/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsAnonymous)
PROPERTY() [10/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsArrayResolved)
PROPERTY() [11/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsArtificial)
PROPERTY() [12/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsEnumClass)
PROPERTY() [13/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsExternal)
PROPERTY() [14/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsInlined)
PROPERTY() [15/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsInlinedAbstract)
PROPERTY() [16/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsLine)
PROPERTY() [17/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsMemberPointerResolved)
PROPERTY() [18/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsNested)
PROPERTY() [19/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsReferencedType)
PROPERTY() [20/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsScope)
PROPERTY() [21/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsScoped)
PROPERTY() [22/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsScopedAlready)
PROPERTY() [23/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsStatic)
PROPERTY() [24/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsSymbol)
PROPERTY() [25/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsSystem)
PROPERTY() [26/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsTemplateResolved)
PROPERTY() [27/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsType)
PROPERTY() [28/31]
llvm::logicalview::LVElement::PROPERTY (Property , IsTypedefReduced)
PROPERTY() [29/31]
llvm::logicalview::LVElement::PROPERTY (Property , OffsetFromTypeIndex)
PROPERTY() [30/31]
llvm::logicalview::LVElement::PROPERTY (Property , QualifiedResolved)
PROPERTY() [31/31]
llvm::logicalview::LVElement::PROPERTY (Property , TransformName)
referenceMatch()
bool LVElement::referenceMatch (const LVElement * Element) const
Definition at line 469 of file LVElement.cpp.
References llvm::logicalview::LVObject::Element, and LVElement().
Referenced by llvm::logicalview::LVScopeFunction::equals(), llvm::logicalview::LVScopeNamespace::equals(), and llvm::logicalview::LVSymbol::equals().
removeElement()
virtual bool llvm::logicalview::LVElement::removeElement (LVElement * Element) inline virtual
Reimplemented in llvm::logicalview::LVScope.
Definition at line 354 of file LVElement.h.
References llvm::logicalview::LVObject::Element, and LVElement().
report()
virtual void llvm::logicalview::LVElement::report (LVComparePass Pass) inline virtual
Reimplemented in llvm::logicalview::LVLine, llvm::logicalview::LVScope, llvm::logicalview::LVSymbol, and llvm::logicalview::LVType.
Definition at line 375 of file LVElement.h.
resolve()
void LVElement::resolve () virtual
Reimplemented in llvm::logicalview::LVScope.
Definition at line 199 of file LVElement.cpp.
References resolveExtra(), resolveName(), resolveParents(), and resolveReferences().
Referenced by llvm::logicalview::LVScope::resolve().
resolveExtra()
virtual void llvm::logicalview::LVElement::resolveExtra () inline virtual
Reimplemented in llvm::logicalview::LVScopeArray, llvm::logicalview::LVScopeFunction, llvm::logicalview::LVScopeFunctionInlined, llvm::logicalview::LVScopeFunctionType, llvm::logicalview::LVTypeDefinition, and llvm::logicalview::LVTypeSubrange.
Definition at line 364 of file LVElement.h.
Referenced by resolve().
resolveFullname()
void LVElement::resolveFullname (LVElement * BaseType, StringRef Name = emptyString())
Definition at line 273 of file LVElement.cpp.
References assert(), llvm::dbgs(), llvm::dwarf::DW_TAG_unaligned, llvm::logicalview::emptyString(), getName(), llvm::logicalview::LVObject::getTag(), LLVM_DEBUG, llvm_unreachable, LVElement(), llvm::logicalview::Name, setName(), llvm::StringRef::size(), and llvm::logicalview::typeVoid().
Referenced by llvm::logicalview::LVScopeArray::resolveExtra(), llvm::logicalview::LVTypeDefinition::resolveExtra(), llvm::logicalview::LVScope::resolveName(), and llvm::logicalview::LVType::resolveName().
resolveName()
void LVElement::resolveName () virtual
Reimplemented in llvm::logicalview::LVScope, llvm::logicalview::LVSymbol, and llvm::logicalview::LVType.
Definition at line 224 of file LVElement.cpp.
References llvm::logicalview::options().
Referenced by resolve(), llvm::logicalview::LVScope::resolveName(), llvm::logicalview::LVSymbol::resolveName(), and llvm::logicalview::LVType::resolveName().
resolveParents()
void LVElement::resolveParents ()
Definition at line 233 of file LVElement.cpp.
References llvm::logicalview::LVObject::getParentScope(), isCompileUnit(), and isRoot().
Referenced by resolve().
resolveReferences()
virtual void llvm::logicalview::LVElement::resolveReferences () inline virtual
Reimplemented in llvm::logicalview::LVScope, llvm::logicalview::LVScopeFunction, llvm::logicalview::LVSymbol, and llvm::logicalview::LVType.
Definition at line 366 of file LVElement.h.
Referenced by resolve().
setAccessibilityCode() [1/2]
void llvm::logicalview::LVElement::setAccessibilityCode (codeview::MemberAccess Access) inline
Definition at line 285 of file LVElement.h.
References Access, and getAccessibilityCode().
setAccessibilityCode() [2/2]
void llvm::logicalview::LVElement::setAccessibilityCode (uint32_t Access) inline
Definition at line 279 of file LVElement.h.
References Access.
setBitSize()
virtual void llvm::logicalview::LVElement::setBitSize (uint32_t Size) inline virtual
Reimplemented in llvm::logicalview::LVScope, llvm::logicalview::LVSymbol, and llvm::logicalview::LVType.
Definition at line 257 of file LVElement.h.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord().
setBounds()
virtual void llvm::logicalview::LVElement::setBounds (unsigned Lower, unsigned Upper) inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 266 of file LVElement.h.
setCallFilenameIndex()
virtual void llvm::logicalview::LVElement::setCallFilenameIndex (size_t Index) inline virtual
Reimplemented in llvm::logicalview::LVScopeFunctionInlined.
Definition at line 243 of file LVElement.h.
setCallLineNumber()
virtual void llvm::logicalview::LVElement::setCallLineNumber (uint32_t Number) inline virtual
Reimplemented in llvm::logicalview::LVScopeFunctionInlined.
Definition at line 241 of file LVElement.h.
setCount()
virtual void llvm::logicalview::LVElement::setCount (int64_t Value) inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 260 of file LVElement.h.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord().
setDiscriminator()
virtual void llvm::logicalview::LVElement::setDiscriminator (uint32_t Value) inline virtual
Reimplemented in llvm::logicalview::LVLineDebug, and llvm::logicalview::LVScopeFunctionInlined.
Definition at line 270 of file LVElement.h.
setFile()
void LVElement::setFile (LVElement * Reference = nullptr)
Definition at line 373 of file LVElement.cpp.
References llvm::logicalview::Filename, llvm::logicalview::LVReader::getFilename(), getFilenameIndex(), llvm::logicalview::getReader(), LVElement(), llvm::logicalview::options(), setFilename(), setFilenameIndex(), and llvm::StringRef::size().
Referenced by llvm::logicalview::LVScope::resolveReferences(), llvm::logicalview::LVSymbol::resolveReferences(), and llvm::logicalview::LVType::resolveReferences().
setFilename()
void LVElement::setFilename (StringRef Filename)
Definition at line 101 of file LVElement.cpp.
References llvm::logicalview::Filename, and getStringIndex().
Referenced by setFile().
setFilenameIndex()
void llvm::logicalview::LVElement::setFilenameIndex (size_t Index) inline
Definition at line 245 of file LVElement.h.
Referenced by llvm::logicalview::LVLogicalVisitor::processLines(), and setFile().
setGenericType()
void LVElement::setGenericType (LVElement * Element)
Definition at line 42 of file LVElement.cpp.
References llvm::logicalview::LVObject::Element, LVElement(), llvm::logicalview::options(), and setType().
Referenced by llvm::logicalview::LVSymbol::resolveReferences().
setInlineCode()
void llvm::logicalview::LVElement::setInlineCode (uint32_t Code) inline
Definition at line 292 of file LVElement.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
setInnerComponent() [1/2]
void llvm::logicalview::LVElement::setInnerComponent () inline
Definition at line 216 of file LVElement.h.
References getName(), and setInnerComponent().
Referenced by setInnerComponent().
setInnerComponent() [2/2]
void LVElement::setInnerComponent (StringRef Name)
Definition at line 106 of file LVElement.cpp.
References llvm::logicalview::getInnerComponent(), llvm::logicalview::Name, and setName().
setLinkageName()
virtual void llvm::logicalview::LVElement::setLinkageName (StringRef LinkageName) inline virtual
Reimplemented in llvm::logicalview::LVScopeFunction, and llvm::logicalview::LVSymbol.
Definition at line 236 of file LVElement.h.
Referenced by llvm::logicalview::LVBinaryReader::createInstructions().
setLowerBound()
virtual void llvm::logicalview::LVElement::setLowerBound (int64_t Value) inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 262 of file LVElement.h.
setName()
void LVElement::setName (StringRef ElementName) override virtual
Reimplemented from llvm::logicalview::LVObject.
Reimplemented in llvm::logicalview::LVScopeFunction.
Definition at line 95 of file LVElement.cpp.
References llvm::logicalview::LVStringPool::getIndex(), getStringIndex(), and llvm::logicalview::getStringPool().
Referenced by generateName(), llvm::logicalview::LVScopeArray::resolveExtra(), llvm::logicalview::LVTypeDefinition::resolveExtra(), llvm::logicalview::LVTypeSubrange::resolveExtra(), resolveFullname(), llvm::logicalview::LVScope::resolveName(), llvm::logicalview::LVScope::resolveReferencesChain(), llvm::logicalview::LVSymbol::resolveReferencesChain(), setInnerComponent(), llvm::logicalview::LVScopeFunction::setName(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), and llvm::logicalview::LVLogicalVisitor::visitKnownRecord().
setProducer()
virtual void llvm::logicalview::LVElement::setProducer (StringRef ProducerName) inline virtual
Reimplemented in llvm::logicalview::LVScopeCompileUnit.
Definition at line 223 of file LVElement.h.
setQualifiedName()
void llvm::logicalview::LVElement::setQualifiedName (StringRef Name) inline
Definition at line 206 of file LVElement.h.
References llvm::logicalview::getStringPool().
setReference() [1/4]
virtual void llvm::logicalview::LVElement::setReference (LVElement * Element) inline virtual
Reimplemented in llvm::logicalview::LVScopeAggregate, llvm::logicalview::LVScopeFunction, llvm::logicalview::LVScopeNamespace, and llvm::logicalview::LVSymbol.
Definition at line 231 of file LVElement.h.
References llvm::logicalview::LVObject::Element, and LVElement().
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
setReference() [2/4]
virtual void llvm::logicalview::LVElement::setReference (LVScope * Scope) inline virtual
Reimplemented in llvm::logicalview::LVScopeAggregate, llvm::logicalview::LVScopeFunction, and llvm::logicalview::LVScopeNamespace.
Definition at line 232 of file LVElement.h.
References llvm::logicalview::LVObject::Scope.
setReference() [3/4]
virtual void llvm::logicalview::LVElement::setReference (LVSymbol * Symbol) inline virtual
Reimplemented in llvm::logicalview::LVSymbol.
Definition at line 233 of file LVElement.h.
References llvm::logicalview::LVObject::Symbol.
setReference() [4/4]
virtual void llvm::logicalview::LVElement::setReference (LVType * Type) inline virtual
Definition at line 234 of file LVElement.h.
setSourceLanguage()
virtual void llvm::logicalview::LVElement::setSourceLanguage (LVSourceLanguage SL) inline virtual
Reimplemented in llvm::logicalview::LVScopeCompileUnit.
Definition at line 226 of file LVElement.h.
setType()
void llvm::logicalview::LVElement::setType (LVElement * Element = nullptr) inline
Definition at line 315 of file LVElement.h.
References llvm::logicalview::LVObject::Element, ElementType, and LVElement().
Referenced by llvm::logicalview::LVScopeFunction::resolveReferences(), llvm::logicalview::LVSymbol::resolveReferences(), setGenericType(), llvm::logicalview::LVTypeDefinition::setUnderlyingType(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
setUpperBound()
virtual void llvm::logicalview::LVElement::setUpperBound (int64_t Value) inline virtual
Reimplemented in llvm::logicalview::LVTypeSubrange.
Definition at line 264 of file LVElement.h.
setValue()
virtual void llvm::logicalview::LVElement::setValue (StringRef Value) inline virtual
Reimplemented in llvm::logicalview::LVSymbol, llvm::logicalview::LVTypeEnumerator, and llvm::logicalview::LVTypeParam.
Definition at line 274 of file LVElement.h.
setVirtualityCode() [1/2]
void llvm::logicalview::LVElement::setVirtualityCode (codeview::MethodKind Virtuality) inline
Definition at line 303 of file LVElement.h.
References getVirtualityCode().
setVirtualityCode() [2/2]
void llvm::logicalview::LVElement::setVirtualityCode (uint32_t Virtuality) inline
Definition at line 297 of file LVElement.h.
traverseParents()
LVScope * LVElement::traverseParents (LVScopeGetFunction GetFunction) const
Definition at line 418 of file LVElement.cpp.
References llvm::logicalview::LVObject::getParentScope().
Referenced by getCompileUnitParent(), and getFunctionParent().
typeAsString()
StringRef LVElement::typeAsString () const
Definition at line 68 of file LVElement.cpp.
References getTypeName(), and llvm::logicalview::typeVoid().
Referenced by llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), and llvm::logicalview::LVScopeFunctionType::resolveExtra().
typeOffsetAsString()
std::string LVElement::typeOffsetAsString () const
Definition at line 115 of file LVElement.cpp.
References llvm::logicalview::LVObject::Element, getType(), llvm::logicalview::hexSquareString(), LVElement(), and llvm::logicalview::options().
Referenced by llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeArray::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVTypeDefinition::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::logicalview::LVTypeParam::printExtra(), and llvm::logicalview::LVTypeSubrange::printExtra().
updateLevel()
void LVElement::updateLevel (LVScope * Parent, bool Moved = false) virtual
Reimplemented in llvm::logicalview::LVScope.
Definition at line 266 of file LVElement.cpp.
References llvm::logicalview::LVObject::setLevel().
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownMember(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
virtualityString()
StringRef LVElement::virtualityString (uint32_t Virtuality = dwarf::DW_VIRTUALITY_none) const
Definition at line 170 of file LVElement.cpp.
References getVirtualityCode().
Referenced by llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVSymbol::printExtra(), and llvm::logicalview::LVTypeImport::printExtra().
Member Data Documentation
ElementType
LVElement* llvm::logicalview::LVElement::ElementType = nullptr protected
Definition at line 135 of file LVElement.h.
Referenced by getIsKindScope(), getIsKindType(), getType(), getTypeAsScope(), getTypeAsType(), getTypeName(), getTypeQualifiedName(), isTyped(), llvm::logicalview::LVScopeArray::resolveExtra(), and setType().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVElement.h
lib/DebugInfo/LogicalView/Core/LVElement.cpp