LLVM: llvm::RewriteRope Class Reference
llvm::RewriteRope Class Reference
RewriteRope - A powerful string class.
#include "llvm/ADT/RewriteRope.h"
Public Types
using iterator = RopePieceBTree::iterator
using const_iterator = RopePieceBTree::iterator
Public Member Functions
RewriteRope ()=default
RewriteRope (const RewriteRope &RHS)
RewriteRope & operator= (const RewriteRope &)=delete
iterator begin () const
iterator end () const
unsigned size () const
void clear ()
void assign (const char *Start, const char *End)
void insert (unsigned Offset, const char *Start, const char *End)
void erase (unsigned Offset, unsigned NumBytes)
Detailed Description
RewriteRope - A powerful string class.
This class supports extremely efficient insertions and deletions into the middle of it, even for ridiculously long strings.
Definition at line 172 of file RewriteRope.h.
Member Typedef Documentation
const_iterator
using llvm::RewriteRope::const_iterator = RopePieceBTree::iterator
Definition at line 190 of file RewriteRope.h.
iterator
using llvm::RewriteRope::iterator = RopePieceBTree::iterator
Definition at line 189 of file RewriteRope.h.
Constructor & Destructor Documentation
RewriteRope() [1/2]
llvm::RewriteRope::RewriteRope () default
Referenced by operator=(), and RewriteRope().
RewriteRope() [2/2]
llvm::RewriteRope::RewriteRope (const RewriteRope & RHS) inline
Definition at line 183 of file RewriteRope.h.
References RewriteRope(), and RHS.
Member Function Documentation
assign()
void llvm::RewriteRope::assign (const char * Start, const char * End) inline
Definition at line 198 of file RewriteRope.h.
References clear().
begin()
iterator llvm::RewriteRope::begin () const inline
Definition at line 192 of file RewriteRope.h.
clear()
void llvm::RewriteRope::clear () inline
Definition at line 196 of file RewriteRope.h.
Referenced by assign().
end()
iterator llvm::RewriteRope::end () const inline
Definition at line 193 of file RewriteRope.h.
erase()
void llvm::RewriteRope::erase (unsigned Offset, unsigned NumBytes) inline
Definition at line 211 of file RewriteRope.h.
References assert(), llvm::Offset, and size().
insert()
void llvm::RewriteRope::insert (unsigned Offset, const char * Start, const char * End) inline
Definition at line 204 of file RewriteRope.h.
References assert(), llvm::Offset, and size().
operator=()
RewriteRope & llvm::RewriteRope::operator= (const RewriteRope &) delete
References RewriteRope().
size()
unsigned llvm::RewriteRope::size () const inline
Definition at line 194 of file RewriteRope.h.
Referenced by erase(), and insert().
The documentation for this class was generated from the following files:
include/llvm/ADT/RewriteRope.h
lib/Support/RewriteRope.cpp