LLVM: llvm::codeview::DefRangeFramePointerRelSym Class Reference
llvm::codeview::DefRangeFramePointerRelSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
DefRangeFramePointerRelSym (SymbolRecordKind Kind)
DefRangeFramePointerRelSym (uint32_t RecordOffset)
uint32_t getRelocationOffset () const
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
DefRangeFramePointerRelHeader Hdr
LocalVariableAddrRange Range
std::vector< LocalVariableAddrGap > Gaps
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 562 of file SymbolRecord.h.
Constructor & Destructor Documentation
DefRangeFramePointerRelSym() [1/2]
llvm::codeview::DefRangeFramePointerRelSym::DefRangeFramePointerRelSym (SymbolRecordKind Kind) inline explicit
Definition at line 566 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by DefRangeFramePointerRelSym().
DefRangeFramePointerRelSym() [2/2]
llvm::codeview::DefRangeFramePointerRelSym::DefRangeFramePointerRelSym (uint32_t RecordOffset) inline explicit
Definition at line 568 of file SymbolRecord.h.
References DefRangeFramePointerRelSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Function Documentation
getRelocationOffset()
uint32_t llvm::codeview::DefRangeFramePointerRelSym::getRelocationOffset () const inline
Definition at line 572 of file SymbolRecord.h.
References RecordOffset.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Member Data Documentation
Gaps
std::vector<LocalVariableAddrGap> llvm::codeview::DefRangeFramePointerRelSym::Gaps
Definition at line 578 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Hdr
DefRangeFramePointerRelHeader llvm::codeview::DefRangeFramePointerRelSym::Hdr
Definition at line 576 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Range
LocalVariableAddrRange llvm::codeview::DefRangeFramePointerRelSym::Range
Definition at line 577 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
RecordOffset
uint32_t llvm::codeview::DefRangeFramePointerRelSym::RecordOffset = 0
Definition at line 580 of file SymbolRecord.h.
Referenced by DefRangeFramePointerRelSym(), and getRelocationOffset().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h