LLVM: llvm::sandboxir::LegalityResult Class Reference
llvm::sandboxir::LegalityResult Class Reference
The legality outcome is represented by a class rather than an enum class because in some cases the legality checks are expensive and look for a particular instruction that can be passed along to the vectorizer to avoid repeating the same expensive computation.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h"
Public Member Functions
virtual ~LegalityResult ()=default
LegalityResultID getSubclassID () const
virtual void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Protected Member Functions
LegalityResult (LegalityResultID ID)
Only Legality can create LegalityResults.
LegalityResult (const LegalityResult &)=delete
We shouldn't need copies.
LegalityResult & operator= (const LegalityResult &)=delete
Protected Attributes
LegalityResultID ID
Friends
class LegalityAnalysis
raw_ostream & operator<< (raw_ostream &OS, const LegalityResult &LR)
Detailed Description
The legality outcome is represented by a class rather than an enum class because in some cases the legality checks are expensive and look for a particular instruction that can be passed along to the vectorizer to avoid repeating the same expensive computation.
Definition at line 158 of file Legality.h.
Constructor & Destructor Documentation
LegalityResult() [1/2]
llvm::sandboxir::LegalityResult::LegalityResult (LegalityResultID ID) inline protected
Only Legality can create LegalityResults.
Definition at line 162 of file Legality.h.
References ID.
Referenced by llvm::sandboxir::DiamondReuse::classof(), llvm::sandboxir::DiamondReuseMultiInput::classof(), llvm::sandboxir::DiamondReuseWithShuffle::classof(), llvm::sandboxir::Widen::classof(), llvm::sandboxir::DiamondReuse::LegalityAnalysis, llvm::sandboxir::DiamondReuseMultiInput::LegalityAnalysis, llvm::sandboxir::DiamondReuseWithShuffle::LegalityAnalysis, llvm::sandboxir::Widen::LegalityAnalysis, LegalityResult(), operator<<, and operator=().
LegalityResult() [2/2]
llvm::sandboxir::LegalityResult::LegalityResult (const LegalityResult &) protected delete
We shouldn't need copies.
References LegalityResult().
~LegalityResult()
virtual llvm::sandboxir::LegalityResult::~LegalityResult () virtual default
Member Function Documentation
dump()
void llvm::sandboxir::LegalityResult::dump () const
Definition at line 26 of file Legality.cpp.
References llvm::dbgs(), and print().
getSubclassID()
LegalityResultID llvm::sandboxir::LegalityResult::getSubclassID () const inline
Definition at line 171 of file Legality.h.
References ID.
Referenced by llvm::sandboxir::DiamondReuse::classof(), llvm::sandboxir::DiamondReuseMultiInput::classof(), llvm::sandboxir::DiamondReuseWithShuffle::classof(), llvm::sandboxir::Pack::classof(), and llvm::sandboxir::Widen::classof().
operator=()
LegalityResult & llvm::sandboxir::LegalityResult::operator= (const LegalityResult &) protected delete
References LegalityResult().
print()
virtual void llvm::sandboxir::LegalityResult::print (raw_ostream & OS) const inline virtual
Reimplemented in llvm::sandboxir::LegalityResultWithReason.
Definition at line 173 of file Legality.h.
References llvm::sandboxir::ToStr::getLegalityResultID(), and ID.
Referenced by dump(), operator<<, and llvm::sandboxir::LegalityResultWithReason::print().
Friends And Related Symbol Documentation
LegalityAnalysis
friend class LegalityAnalysis friend
Definition at line 163 of file Legality.h.
References LegalityAnalysis.
Referenced by LegalityAnalysis.
operator<<
raw_ostream & operator<< (raw_ostream & OS, const LegalityResult & LR) friend
Definition at line 177 of file Legality.h.
References LegalityResult(), and print().
Member Data Documentation
ID
LegalityResultID llvm::sandboxir::LegalityResult::ID protected
Definition at line 160 of file Legality.h.
Referenced by getSubclassID(), LegalityResult(), and print().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h
lib/Transforms/Vectorize/SandboxVectorizer/Legality.cpp