LLVM: llvm::mca::Instrument Class Reference
llvm::mca::Instrument Class Reference
#include "llvm/MCA/CustomBehaviour.h"
Public Member Functions
Instrument (StringRef Desc, StringRef Data)
Instrument ()
virtual ~Instrument ()=default
StringRef getDesc () const
StringRef getData () const
Detailed Description
Definition at line 118 of file CustomBehaviour.h.
Constructor & Destructor Documentation
Instrument() [1/2]
llvm::mca::Instrument::Instrument (StringRef Desc, StringRef Data) inline
Definition at line 126 of file CustomBehaviour.h.
Referenced by Instrument(), llvm::mca::LatencyInstrument::LatencyInstrument(), llvm::mca::RISCVLMULInstrument::RISCVLMULInstrument(), and llvm::mca::RISCVSEWInstrument::RISCVSEWInstrument().
Instrument() [2/2]
llvm::mca::Instrument::Instrument () inline
Definition at line 128 of file CustomBehaviour.h.
References Instrument().
~Instrument()
virtual llvm::mca::Instrument::~Instrument () virtual default
Member Function Documentation
getData()
StringRef llvm::mca::Instrument::getData () const inline
Definition at line 133 of file CustomBehaviour.h.
Referenced by llvm::mca::RISCVLMULInstrument::getLMUL(), llvm::mca::RISCVInstrumentManager::getSchedClassID(), and llvm::mca::RISCVSEWInstrument::getSEW().
getDesc()
StringRef llvm::mca::Instrument::getDesc () const inline
Definition at line 132 of file CustomBehaviour.h.
The documentation for this class was generated from the following file:
include/llvm/MCA/CustomBehaviour.h