LLVM: llvm::abi::FloatType Class Reference
llvm::abi::FloatType Class Reference
#include "llvm/ABI/Types.h"
Public Member Functions
FloatType (const fltSemantics &FloatSemantics, Align ABIAlign)
const fltSemantics * getSemantics () const
Public Member Functions inherited from llvm::abi::Type
TypeKind getKind () const
TypeSize getSizeInBits () const
Align getAlignment () const
TypeSize getTypeAllocSize () const
bool isVoid () const
bool isInteger () const
bool isFloat () const
bool isPointer () const
bool isArray () const
bool isVector () const
bool isRecord () const
bool isMemberPointer () const
bool isComplex () const
Static Public Member Functions
static bool classof (const Type *T)
Additional Inherited Members
Protected Member Functions inherited from llvm::abi::Type
Type (TypeKind K, TypeSize SizeInBits, Align ABIAlign)
Protected Attributes inherited from llvm::abi::Type
TypeKind Kind
TypeSize SizeInBits
Align ABIAlignment
Detailed Description
Definition at line 132 of file Types.h.
Constructor & Destructor Documentation
FloatType()
llvm::abi::FloatType::FloatType (const fltSemantics & FloatSemantics, Align ABIAlign) inline
Definition at line 137 of file Types.h.
References Float, llvm::abi::Type::getSizeInBits(), and llvm::abi::Type::Type().
Member Function Documentation
classof()
bool llvm::abi::FloatType::classof (const Type * T) inline static
Definition at line 144 of file Types.h.
References llvm::abi::Float, T, and llvm::abi::Type::Type().
getSemantics()
const fltSemantics * llvm::abi::FloatType::getSemantics () const inline
Definition at line 143 of file Types.h.
The documentation for this class was generated from the following file:
include/llvm/ABI/Types.h