LLVM: llvm::sandboxir::Scheduler Class Reference
llvm::sandboxir::Scheduler Class Reference
The list scheduler.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Scheduler.h"
Public Member Functions
Scheduler (AAResults &AA, Context &Ctx)
~Scheduler ()
LLVM_ABI bool trySchedule (ArrayRef< Instruction * > Instrs)
Tries to build a schedule that includes all of Instrs scheduled at the same scheduling cycle.
void clear ()
Clear the scheduler's state, including the DAG.
void dump (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Friends
class SchedulerInternalsAttorney
Detailed Description
The list scheduler.
Definition at line 163 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler()
llvm::sandboxir::Scheduler::Scheduler (AAResults & AA, Context & Ctx) inline
Definition at line 219 of file Scheduler.h.
References I.
~Scheduler()
llvm::sandboxir::Scheduler::~Scheduler () inline
Definition at line 225 of file Scheduler.h.
Member Function Documentation
clear()
void llvm::sandboxir::Scheduler::clear () inline
Clear the scheduler's state, including the DAG.
Definition at line 236 of file Scheduler.h.
References assert().
dump() [1/2]
void llvm::sandboxir::Scheduler::dump () const
Definition at line 357 of file Scheduler.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::Scheduler::dump (raw_ostream & OS) const
Definition at line 347 of file Scheduler.cpp.
trySchedule()
bool llvm::sandboxir::Scheduler::trySchedule (ArrayRef< Instruction * > Instrs)
Tries to build a schedule that includes all of Instrs scheduled at the same scheduling cycle.
This essentially checks that there are no dependencies among Instrs. This function may involve scheduling intermediate instructions or canceling and re-scheduling if needed. \Returns true on success, false otherwise.
Definition at line 290 of file Scheduler.cpp.
References llvm::all_of(), llvm::any_of(), assert(), llvm::ArrayRef< T >::begin(), llvm::drop_begin(), llvm::sandboxir::VecUtils::getLowest(), I, llvm_unreachable, and N.
Friends And Related Symbol Documentation
SchedulerInternalsAttorney
friend class SchedulerInternalsAttorney friend
Definition at line 171 of file Scheduler.h.
References I, LLVM_ABI, and SchedulerInternalsAttorney.
Referenced by SchedulerInternalsAttorney.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Scheduler.h
lib/Transforms/Vectorize/SandboxVectorizer/Scheduler.cpp