LLVM: llvm::DebugVariableAggregate Class Reference
llvm::DebugVariableAggregate Class Reference
Identifies a unique instance of a whole variable (discards/ignores fragment information).
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
LLVM_ABI DebugVariableAggregate (const DbgVariableRecord *DVR)
DebugVariableAggregate (const DebugVariable &V)
Public Member Functions inherited from llvm::DebugVariable
LLVM_ABI DebugVariable (const DbgVariableRecord *DVR)
DebugVariable (const DILocalVariable *Var, std::optional< FragmentInfo > FragmentInfo, const DILocation *InlinedAt)
DebugVariable (const DILocalVariable *Var, const DIExpression *DIExpr, const DILocation *InlinedAt)
const DILocalVariable * getVariable () const
std::optional< FragmentInfo > getFragment () const
const DILocation * getInlinedAt () const
FragmentInfo getFragmentOrDefault () const
bool operator== (const DebugVariable &Other) const
bool operator< (const DebugVariable &Other) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::DebugVariable
static bool isDefaultFragment (const FragmentInfo F)
Detailed Description
Identifies a unique instance of a whole variable (discards/ignores fragment information).
Definition at line 4774 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DebugVariableAggregate() [1/2]
DebugVariableAggregate::DebugVariableAggregate (const DbgVariableRecord * DVR)
Definition at line 57 of file DebugInfoMetadata.cpp.
References llvm::DebugVariable::DebugVariable(), getDebugLoc(), llvm::DebugVariable::getInlinedAt(), and llvm::DebugVariable::getVariable().
DebugVariableAggregate() [2/2]
llvm::DebugVariableAggregate::DebugVariableAggregate (const DebugVariable & V) inline
Definition at line 4777 of file DebugInfoMetadata.h.
References llvm::DebugVariable::DebugVariable(), llvm::DebugVariable::getInlinedAt(), and llvm::DebugVariable::getVariable().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp