LLVM: llvm::MachineLoopPrinterPass Class Reference
llvm::MachineLoopPrinterPass Class Reference
Printer pass for the LoopAnalysis results.
#include "llvm/CodeGen/MachineLoopInfo.h"
Public Member Functions
MachineLoopPrinterPass (raw_ostream &OS)
LLVM_ABI PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< MachineLoopPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< MachineLoopPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the LoopAnalysis results.
Definition at line 151 of file MachineLoopInfo.h.
Constructor & Destructor Documentation
MachineLoopPrinterPass()
llvm::MachineLoopPrinterPass::MachineLoopPrinterPass (raw_ostream & OS) inline explicit
Definition at line 155 of file MachineLoopInfo.h.
Member Function Documentation
isRequired()
bool llvm::MachineLoopPrinterPass::isRequired () inline static
Definition at line 158 of file MachineLoopInfo.h.
run()
PreservedAnalyses MachineLoopPrinterPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 45 of file MachineLoopInfo.cpp.
References llvm::PreservedAnalyses::all(), llvm::MachineFunction::getName(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::print().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineLoopInfo.h
lib/CodeGen/MachineLoopInfo.cpp