LLVM: llvm::codeview::MemberFuncIdRecord Class Reference
llvm::codeview::MemberFuncIdRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
MemberFuncIdRecord ()=default
MemberFuncIdRecord (TypeRecordKind Kind)
MemberFuncIdRecord (TypeIndex ClassType, TypeIndex FunctionType, StringRef Name)
TypeIndex getClassType () const
TypeIndex getFunctionType () const
StringRef getName () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex ClassType
TypeIndex FunctionType
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 217 of file TypeRecord.h.
Constructor & Destructor Documentation
MemberFuncIdRecord() [1/3]
llvm::codeview::MemberFuncIdRecord::MemberFuncIdRecord () default
MemberFuncIdRecord() [2/3]
llvm::codeview::MemberFuncIdRecord::MemberFuncIdRecord (TypeRecordKind Kind) inline explicit
Definition at line 220 of file TypeRecord.h.
References llvm::codeview::TypeRecord::Kind, and llvm::codeview::TypeRecord::TypeRecord().
MemberFuncIdRecord() [3/3]
llvm::codeview::MemberFuncIdRecord::MemberFuncIdRecord (TypeIndex ClassType, TypeIndex FunctionType, StringRef Name) inline
Definition at line 221 of file TypeRecord.h.
References ClassType, FunctionType, Name, and llvm::codeview::TypeRecord::TypeRecord().
Member Function Documentation
getClassType()
TypeIndex llvm::codeview::MemberFuncIdRecord::getClassType () const inline
Definition at line 226 of file TypeRecord.h.
References ClassType.
Referenced by llvm::pdb::NativeInlineSiteSymbol::getName().
getFunctionType()
TypeIndex llvm::codeview::MemberFuncIdRecord::getFunctionType () const inline
Definition at line 227 of file TypeRecord.h.
References FunctionType.
getName()
StringRef llvm::codeview::MemberFuncIdRecord::getName () const inline
Definition at line 228 of file TypeRecord.h.
References Name.
Member Data Documentation
ClassType
TypeIndex llvm::codeview::MemberFuncIdRecord::ClassType
Definition at line 230 of file TypeRecord.h.
Referenced by getClassType(), and MemberFuncIdRecord().
FunctionType
TypeIndex llvm::codeview::MemberFuncIdRecord::FunctionType
Definition at line 231 of file TypeRecord.h.
Referenced by getFunctionType(), and MemberFuncIdRecord().
Name
StringRef llvm::codeview::MemberFuncIdRecord::Name
Definition at line 232 of file TypeRecord.h.
Referenced by getName(), and MemberFuncIdRecord().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h