LLVM: llvm::CrashRecoveryContextReleaseRefCleanup< T > Class Template Reference
llvm::CrashRecoveryContextReleaseRefCleanup< T > Class Template Reference
Cleanup handler that reclaims resource by calling its method 'Release'.
#include "llvm/Support/CrashRecoveryContext.h"
Public Member Functions
CrashRecoveryContextReleaseRefCleanup (CrashRecoveryContext *context, T *resource)
void recoverResources () override
Public Member Functions inherited from llvm::CrashRecoveryContextCleanup
virtual ~CrashRecoveryContextCleanup ()
CrashRecoveryContext * getContext () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextReleaseRefCleanup< T >, T >
static CrashRecoveryContextReleaseRefCleanup< T > * create (T *x)
Creates cleanup handler.
Public Attributes inherited from llvm::CrashRecoveryContextCleanup
bool cleanupFired = false
Protected Member Functions inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextReleaseRefCleanup< T >, T >
CrashRecoveryContextCleanupBase (CrashRecoveryContext *context, T *resource)
Protected Member Functions inherited from llvm::CrashRecoveryContextCleanup
CrashRecoveryContextCleanup (CrashRecoveryContext *context)
Protected Attributes inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextReleaseRefCleanup< T >, T >
T * resource
Protected Attributes inherited from llvm::CrashRecoveryContextCleanup
CrashRecoveryContext * context = nullptr
Detailed Description
template<typename T>
class llvm::CrashRecoveryContextReleaseRefCleanup< T >
Cleanup handler that reclaims resource by calling its method 'Release'.
Definition at line 207 of file CrashRecoveryContext.h.
Constructor & Destructor Documentation
CrashRecoveryContextReleaseRefCleanup()
template<typename T> llvm::CrashRecoveryContextReleaseRefCleanup< T >::CrashRecoveryContextReleaseRefCleanup (CrashRecoveryContext * context, T * resource) inline
Definition at line 210 of file CrashRecoveryContext.h.
References llvm::CrashRecoveryContextCleanup::context, llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextReleaseRefCleanup< T >, T >::CrashRecoveryContextCleanupBase(), CrashRecoveryContextReleaseRefCleanup(), llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextReleaseRefCleanup< T >, T >::resource, and T.
Referenced by CrashRecoveryContextReleaseRefCleanup().
Member Function Documentation
recoverResources()
template<typename T> void llvm::CrashRecoveryContextReleaseRefCleanup< T >::recoverResources () inline override virtual
Implements llvm::CrashRecoveryContextCleanup.
Definition at line 215 of file CrashRecoveryContext.h.
References llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextReleaseRefCleanup< T >, T >::resource.
The documentation for this class was generated from the following file:
include/llvm/Support/CrashRecoveryContext.h