LLVM: llvm::vfs::RedirectingFileSystem::DirectoryEntry Class Reference
llvm::vfs::RedirectingFileSystem::DirectoryEntry Class Reference
A directory in the vfs with explicitly specified contents.
#include "llvm/Support/VirtualFileSystem.h"
Public Types
using iterator = decltype(Contents)::iterator
Public Member Functions
DirectoryEntry (StringRef Name, std::vector< std::unique_ptr< Entry > > Contents, Status S)
Constructs a directory entry with explicitly specified contents.
DirectoryEntry (StringRef Name, Status S)
Constructs an empty directory entry.
Status getStatus ()
void addContent (std::unique_ptr< Entry > Content)
Entry * getLastContent () const
iterator contents_begin ()
iterator contents_end ()
Public Member Functions inherited from llvm::vfs::RedirectingFileSystem::Entry
Entry (EntryKind K, StringRef Name)
virtual ~Entry ()=default
StringRef getName () const
EntryKind getKind () const
Static Public Member Functions
static bool classof (const Entry *E)
Detailed Description
A directory in the vfs with explicitly specified contents.
Definition at line 828 of file VirtualFileSystem.h.
Member Typedef Documentation
iterator
using llvm::vfs::RedirectingFileSystem::DirectoryEntry::iterator = decltype(Contents)::iterator
Definition at line 851 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
DirectoryEntry() [1/2]
llvm::vfs::RedirectingFileSystem::DirectoryEntry::DirectoryEntry (StringRef Name, std::vector< std::unique_ptr< Entry > > Contents, Status S) inline
Constructs a directory entry with explicitly specified contents.
Definition at line 834 of file VirtualFileSystem.h.
References llvm::vfs::RedirectingFileSystem::EK_Directory, llvm::vfs::RedirectingFileSystem::Entry::Entry(), and llvm::move().
DirectoryEntry() [2/2]
llvm::vfs::RedirectingFileSystem::DirectoryEntry::DirectoryEntry (StringRef Name, Status S) inline
Constructs an empty directory entry.
Definition at line 840 of file VirtualFileSystem.h.
References llvm::vfs::RedirectingFileSystem::EK_Directory, llvm::vfs::RedirectingFileSystem::Entry::Entry(), and llvm::move().
Member Function Documentation
addContent()
void llvm::vfs::RedirectingFileSystem::DirectoryEntry::addContent (std::unique_ptr< Entry > Content) inline
Definition at line 845 of file VirtualFileSystem.h.
classof()
bool llvm::vfs::RedirectingFileSystem::DirectoryEntry::classof (const Entry * E) inline static
Definition at line 856 of file VirtualFileSystem.h.
References E(), llvm::vfs::RedirectingFileSystem::EK_Directory, and llvm::vfs::RedirectingFileSystem::Entry::Entry().
contents_begin()
iterator llvm::vfs::RedirectingFileSystem::DirectoryEntry::contents_begin () inline
Definition at line 853 of file VirtualFileSystem.h.
contents_end()
iterator llvm::vfs::RedirectingFileSystem::DirectoryEntry::contents_end () inline
Definition at line 854 of file VirtualFileSystem.h.
getLastContent()
Entry * llvm::vfs::RedirectingFileSystem::DirectoryEntry::getLastContent () const inline
Definition at line 849 of file VirtualFileSystem.h.
References llvm::vfs::RedirectingFileSystem::Entry::Entry().
getStatus()
Status llvm::vfs::RedirectingFileSystem::DirectoryEntry::getStatus () inline
Definition at line 843 of file VirtualFileSystem.h.
The documentation for this class was generated from the following file:
include/llvm/Support/VirtualFileSystem.h