LLVM: llvm::FunctionToLoopPassAdaptor Class Reference
llvm::FunctionToLoopPassAdaptor Class Reference
#include "llvm/Transforms/Scalar/LoopPassManager.h"
Public Types
using PassConceptT
Public Member Functions
FunctionToLoopPassAdaptor (std::unique_ptr< PassConceptT > Pass, bool UseMemorySSA=false, bool LoopNestMode=false)
LLVM_ABI PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Runs the loop passes across every loop in the function.
LLVM_ABI void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
bool isLoopNestMode () const
Public Member Functions inherited from llvm::PassInfoMixin< FunctionToLoopPassAdaptor >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< FunctionToLoopPassAdaptor >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 398 of file LoopPassManager.h.
Member Typedef Documentation
PassConceptT
using llvm::FunctionToLoopPassAdaptor::PassConceptT
Initial value:
detail::PassConcept<Loop, LoopAnalysisManager,
                    LoopStandardAnalysisResults &, LPMUpdater &>
Definition at line 401 of file LoopPassManager.h.
Constructor & Destructor Documentation
FunctionToLoopPassAdaptor()
llvm::FunctionToLoopPassAdaptor::FunctionToLoopPassAdaptor (std::unique_ptr< PassConceptT > Pass, bool UseMemorySSA = false, bool LoopNestMode = false) inline explicit
Definition at line 405 of file LoopPassManager.h.
References llvm::move().
Member Function Documentation
isLoopNestMode()
bool llvm::FunctionToLoopPassAdaptor::isLoopNestMode () const inline
Definition at line 422 of file LoopPassManager.h.
isRequired()
bool llvm::FunctionToLoopPassAdaptor::isRequired () inline static
Definition at line 420 of file LoopPassManager.h.
printPipeline()
void FunctionToLoopPassAdaptor::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 186 of file LoopPassManager.cpp.
run()
PreservedAnalyses FunctionToLoopPassAdaptor::run (Function & F, FunctionAnalysisManager & AM)
Runs the loop passes across every loop in the function.
Definition at line 193 of file LoopPassManager.cpp.
References llvm::PreservedAnalyses::all(), llvm::any_cast(), llvm::appendLoopsToWorklist(), assert(), llvm::LoopStandardAnalysisResults::DT, llvm::LoopInfoBase< BlockT, LoopT >::empty(), llvm::PriorityWorklist< T, VectorT, MapT >::empty(), F, llvm::PreservedAnalyses::getChecker(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), IR, llvm::isSpecialPass(), LAM, llvm::LoopStandardAnalysisResults::LI, llvm::LoopStandardAnalysisResults::MSSA, llvm::PriorityWorklist< T, VectorT, MapT >::pop_back_val(), llvm::PassInstrumentation::popBeforeNonSkippedPassCallback(), llvm::PassInstrumentation::pushBeforeNonSkippedPassCallback(), llvm::reportFatalUsageError(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runAfterPassInvalidated(), llvm::PassInstrumentation::runBeforePass(), llvm::LoopStandardAnalysisResults::SE, llvm::LPMUpdater::skipCurrentLoop(), llvm::DominatorTreeBase< NodeT, IsPostDom >::verify(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::ScalarEvolution::verify(), llvm::VerifyDomInfo, llvm::VerifyLoopInfo, llvm::VerifyMemorySSA, llvm::MemorySSA::verifyMemorySSA(), and llvm::VerifySCEV.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopPassManager.h
lib/Transforms/Scalar/LoopPassManager.cpp