LLVM: llvm::MCValue Class Reference
llvm::MCValue Class Reference
#include "llvm/MC/MCValue.h"
Public Member Functions
MCValue ()=default
int64_t getConstant () const
void setConstant (int64_t C)
uint32_t getSpecifier () const
void setSpecifier (uint32_t S)
const MCSymbol * getAddSym () const
void setAddSym (const MCSymbol *A)
const MCSymbol * getSubSym () const
bool isAbsolute () const
Is this an absolute (as opposed to relocatable) value.
Static Public Member Functions
static MCValue get (const MCSymbol *SymA, const MCSymbol *SymB=nullptr, int64_t Val=0, uint32_t Specifier=0)
static MCValue get (int64_t Val)
Friends
class MCAssembler
class MCExpr
Detailed Description
Definition at line 30 of file MCValue.h.
Constructor & Destructor Documentation
MCValue()
llvm::MCValue::MCValue () default
Referenced by get(), and get().
Member Function Documentation
get() [1/2]
MCValue llvm::MCValue::get (const MCSymbol * SymA, const MCSymbol * SymB = nullptr, int64_t Val = 0, uint32_t Specifier = 0) inline static
Definition at line 56 of file MCValue.h.
References MCValue().
Referenced by llvm::LoongArchAsmBackend::addReloc(), llvm::RISCVAsmBackend::addReloc(), llvm::AVRAsmBackend::applyFixup(), evaluateAsRelocatable(), llvm::AMDGPUMCExpr::evaluateAsRelocatableImpl(), llvm::AVRMCAsmInfo::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), MCCOFFSectionNumberTargetExpr::evaluateAsRelocatableImpl(), MCCOFFSectionOffsetTargetExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateSymbolicAdd(), llvm::RISCVAsmBackend::isPCRelFixupResolved(), and llvm::RISCVAsmBackend::maybeAddVendorReloc().
get() [2/2]
MCValue llvm::MCValue::get (int64_t Val) inline static
Definition at line 66 of file MCValue.h.
References MCValue().
getAddSym()
const MCSymbol * llvm::MCValue::getAddSym () const inline
Definition at line 49 of file MCValue.h.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::RISCVAsmBackend::evaluateFixup(), getPCRelHiFixup(), handleIndirectSymViaGOTPCRel(), llvm::MCAssembler::isThumbFunc(), and llvm::MCAssembler::layout().
getConstant()
int64_t llvm::MCValue::getConstant () const inline
Definition at line 44 of file MCValue.h.
Referenced by evaluateAsRelocatable(), llvm::AMDGPUMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::RISCVAsmBackend::evaluateFixup(), llvm::AArch64_ELFTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::ARMElfTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::RISCVELFTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::X86_64ELFTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), getNode(), handleIndirectSymViaGOTPCRel(), and llvm::MCAssembler::layout().
getSpecifier()
uint32_t llvm::MCValue::getSpecifier () const inline
Definition at line 46 of file MCValue.h.
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl().
getSubSym()
const MCSymbol * llvm::MCValue::getSubSym () const inline
Definition at line 51 of file MCValue.h.
Referenced by evaluate(), evaluate(), llvm::MCAsmInfo::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), handleIndirectSymViaGOTPCRel(), llvm::RISCVAsmBackend::isPCRelFixupResolved(), and llvm::MCAssembler::layout().
isAbsolute()
bool llvm::MCValue::isAbsolute () const inline
Is this an absolute (as opposed to relocatable) value.
Definition at line 54 of file MCValue.h.
Referenced by llvm::DelayedMCExprs::assignDocNode(), evaluateAsRelocatable(), llvm::AMDGPUMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), handleIndirectSymViaGOTPCRel(), and llvm::DelayedMCExprs::resolveDelayedExpressions().
setAddSym()
void llvm::MCValue::setAddSym (const MCSymbol * A) inline
Definition at line 50 of file MCValue.h.
References A().
setConstant()
void llvm::MCValue::setConstant (int64_t C) inline
Definition at line 45 of file MCValue.h.
References llvm::CallingConv::C.
setSpecifier()
void llvm::MCValue::setSpecifier (uint32_t S) inline
Definition at line 47 of file MCValue.h.
Referenced by evaluate(), evaluate(), evaluateAsRelocatable(), llvm::MCAsmInfo::evaluateAsRelocatableImpl(), llvm::SystemZMCAsmInfoGOFF::evaluateAsRelocatableImpl(), and llvm::VEELFMCAsmInfo::evaluateAsRelocatableImpl().
Friends And Related Symbol Documentation
MCAssembler
friend class MCAssembler friend
Definition at line 41 of file MCValue.h.
References MCAssembler.
Referenced by MCAssembler.
MCExpr
friend class MCExpr friend
Definition at line 42 of file MCValue.h.
References MCExpr.
Referenced by MCExpr.
The documentation for this class was generated from the following files:
include/llvm/MC/MCValue.h
lib/MC/MCValue.cpp