LLVM: llvm::StringSaver Class Reference
llvm::StringSaver Class Reference final
Saves strings in the provided stable storage and returns a StringRef with a stable character pointer.
#include "llvm/Support/StringSaver.h"
Public Member Functions
StringSaver (BumpPtrAllocator &Alloc)
BumpPtrAllocator & getAllocator () const
StringRef save (const char *S)
LLVM_ABI StringRef save (StringRef S)
LLVM_ABI StringRef save (const Twine &S)
StringRef save (const std::string &S)
Detailed Description
Saves strings in the provided stable storage and returns a StringRef with a stable character pointer.
Definition at line 22 of file StringSaver.h.
Constructor & Destructor Documentation
StringSaver()
llvm::StringSaver::StringSaver (BumpPtrAllocator & Alloc) inline
Definition at line 26 of file StringSaver.h.
Member Function Documentation
getAllocator()
BumpPtrAllocator & llvm::StringSaver::getAllocator () const inline
Definition at line 28 of file StringSaver.h.
Referenced by llvm::cl::ExpandResponseFiles(), and llvm::cl::expandResponseFiles().
save() [1/4]
StringRef llvm::StringSaver::save (const char * S) inline
Definition at line 31 of file StringSaver.h.
References save().
Referenced by llvm::MCContext::allocateString(), ExpandBasePaths(), getSearchPaths(), llvm::libDriverMain(), save(), save(), llvm::cl::TokenizeGNUCommandLine(), and tokenizeWindowsCommandLineImpl().
save() [2/4]
StringRef llvm::StringSaver::save (const std::string & S) inline
Definition at line 34 of file StringSaver.h.
References save().
Referenced by save().
save() [3/4]
StringRef StringSaver::save (const Twine & S)
Definition at line 23 of file StringSaver.cpp.
References save(), and llvm::Twine::toStringRef().
save() [4/4]
StringRef StringSaver::save (StringRef S)
Definition at line 15 of file StringSaver.cpp.
References llvm::StringRef::data(), llvm::StringRef::empty(), P, and llvm::StringRef::size().
The documentation for this class was generated from the following files:
include/llvm/Support/StringSaver.h
lib/Support/StringSaver.cpp