LLVM: llvm::codeview::DefRangeRegisterSym Class Reference
llvm::codeview::DefRangeRegisterSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
DefRangeRegisterSym (SymbolRecordKind Kind)
DefRangeRegisterSym (uint32_t RecordOffset)
uint32_t getRelocationOffset () const
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
DefRangeRegisterHeader Hdr
LocalVariableAddrRange Range
std::vector< LocalVariableAddrGap > Gaps
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 517 of file SymbolRecord.h.
Constructor & Destructor Documentation
DefRangeRegisterSym() [1/2]
llvm::codeview::DefRangeRegisterSym::DefRangeRegisterSym (SymbolRecordKind Kind) inline explicit
Definition at line 519 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by DefRangeRegisterSym().
DefRangeRegisterSym() [2/2]
llvm::codeview::DefRangeRegisterSym::DefRangeRegisterSym (uint32_t RecordOffset) inline explicit
Definition at line 520 of file SymbolRecord.h.
References DefRangeRegisterSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Function Documentation
getRelocationOffset()
uint32_t llvm::codeview::DefRangeRegisterSym::getRelocationOffset () const inline
Definition at line 524 of file SymbolRecord.h.
References RecordOffset.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Member Data Documentation
Gaps
std::vector<LocalVariableAddrGap> llvm::codeview::DefRangeRegisterSym::Gaps
Definition at line 528 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Hdr
DefRangeRegisterHeader llvm::codeview::DefRangeRegisterSym::Hdr
Definition at line 526 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Range
LocalVariableAddrRange llvm::codeview::DefRangeRegisterSym::Range
Definition at line 527 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
RecordOffset
uint32_t llvm::codeview::DefRangeRegisterSym::RecordOffset = 0
Definition at line 530 of file SymbolRecord.h.
Referenced by DefRangeRegisterSym(), and getRelocationOffset().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h