LLVM: llvm::msgpack::MapDocNode Class Reference
llvm::msgpack::MapDocNode Class Reference
A DocNode that is a map.
#include "llvm/BinaryFormat/MsgPackDocument.h"
Public Member Functions
MapDocNode ()=default
MapDocNode (DocNode &N)
size_t size () const
bool empty () const
MapTy::iterator begin ()
MapTy::iterator end ()
MapTy::iterator find (DocNode Key)
LLVM_ABI MapTy::iterator find (StringRef Key)
Find the key in the MapDocNode.
MapTy::iterator erase (MapTy::const_iterator I)
size_t erase (DocNode Key)
MapTy::iterator erase (MapTy::const_iterator First, MapTy::const_iterator Second)
LLVM_ABI DocNode & operator[] (StringRef S)
Member access.
LLVM_ABI DocNode & operator[] (DocNode Key)
Member access, with convenience versions for an integer key.
LLVM_ABI DocNode & operator[] (int Key)
Member access for MapDocNode for integer key.
LLVM_ABI DocNode & operator[] (unsigned Key)
LLVM_ABI DocNode & operator[] (int64_t Key)
LLVM_ABI DocNode & operator[] (uint64_t Key)
Public Member Functions inherited from llvm::msgpack::DocNode
DocNode ()
bool isMap () const
bool isArray () const
bool isScalar () const
bool isString () const
bool isEmpty () const
Type getKind () const
Document * getDocument () const
int64_t & getInt ()
uint64_t & getUInt ()
bool & getBool ()
double & getFloat ()
int64_t getInt () const
uint64_t getUInt () const
bool getBool () const
double getFloat () const
StringRef getString () const
MemoryBufferRef getBinary () const
ArrayDocNode & getArray (bool Convert=false)
Get an ArrayDocNode for an array node.
MapDocNode & getMap (bool Convert=false)
Get a MapDocNode for a map node.
LLVM_ABI std::string toString () const
Convert this node to a string, assuming it is scalar.
LLVM_ABI StringRef fromString (StringRef S, StringRef Tag="")
Convert the StringRef and use it to set this DocNode (assuming scalar).
DocNode & operator= (const char *Val)
Convenience assignment operators.
LLVM_ABI DocNode & operator= (StringRef Val)
LLVM_ABI DocNode & operator= (MemoryBufferRef Val)
LLVM_ABI DocNode & operator= (bool Val)
LLVM_ABI DocNode & operator= (int Val)
LLVM_ABI DocNode & operator= (unsigned Val)
LLVM_ABI DocNode & operator= (int64_t Val)
LLVM_ABI DocNode & operator= (uint64_t Val)
LLVM_ABI DocNode & operator= (double Val)
Additional Inherited Members
Public Types inherited from llvm::msgpack::DocNode
typedef std::map< DocNode, DocNode > MapTy
typedef std::vector< DocNode > ArrayTy
Protected Attributes inherited from llvm::msgpack::DocNode
union {
int64_t Int
uint64_t UInt
bool Bool
double Float
StringRef Raw
ArrayTy * Array
MapTy * Map
};
Detailed Description
A DocNode that is a map.
Definition at line 227 of file MsgPackDocument.h.
Constructor & Destructor Documentation
MapDocNode() [1/2]
llvm::msgpack::MapDocNode::MapDocNode () default
MapDocNode() [2/2]
llvm::msgpack::MapDocNode::MapDocNode (DocNode & N) inline
Definition at line 230 of file MsgPackDocument.h.
References assert(), llvm::msgpack::DocNode::DocNode(), llvm::msgpack::DocNode::getKind(), llvm::msgpack::Map, and N.
Member Function Documentation
begin()
MapTy::iterator llvm::msgpack::MapDocNode::begin () inline
Definition at line 235 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Map.
empty()
bool llvm::msgpack::MapDocNode::empty () const inline
Definition at line 234 of file MsgPackDocument.h.
References size().
end()
MapTy::iterator llvm::msgpack::MapDocNode::end () inline
Definition at line 236 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Map.
erase() [1/3]
size_t llvm::msgpack::MapDocNode::erase (DocNode Key) inline
Definition at line 240 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::DocNode(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::msgpack::DocNode::Map.
erase() [2/3]
MapTy::iterator llvm::msgpack::MapDocNode::erase (MapTy::const_iterator First, MapTy::const_iterator Second) inline
Definition at line 241 of file MsgPackDocument.h.
References llvm::First, and llvm::msgpack::DocNode::Map.
erase() [3/3]
MapTy::iterator llvm::msgpack::MapDocNode::erase (MapTy::const_iterator I) inline
Definition at line 239 of file MsgPackDocument.h.
References I, and llvm::msgpack::DocNode::Map.
find() [1/2]
MapTy::iterator llvm::msgpack::MapDocNode::find (DocNode Key) inline
Definition at line 237 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::DocNode(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::msgpack::DocNode::Map.
Referenced by find().
find() [2/2]
DocNode::MapTy::iterator MapDocNode::find (StringRef Key)
Find the key in the MapDocNode.
Definition at line 30 of file MsgPackDocument.cpp.
References find(), llvm::msgpack::DocNode::getDocument(), and getNode().
operator[]() [1/6]
DocNode & MapDocNode::operator[] (DocNode Key)
Member access, with convenience versions for an integer key.
Member access for MapDocNode.
Definition at line 41 of file MsgPackDocument.cpp.
References assert(), llvm::msgpack::DocNode::DocNode(), llvm::msgpack::DocNode::getDocument(), llvm::msgpack::Document::getEmptyNode(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and N.
operator[]() [2/6]
DocNode & MapDocNode::operator[] (int Key)
Member access for MapDocNode for integer key.
Definition at line 52 of file MsgPackDocument.cpp.
References llvm::msgpack::DocNode::DocNode(), llvm::msgpack::DocNode::getDocument(), llvm::msgpack::Document::getNode(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
operator[]() [3/6]
DocNode & MapDocNode::operator[] (int64_t Key)
Definition at line 58 of file MsgPackDocument.cpp.
References llvm::msgpack::DocNode::DocNode(), llvm::msgpack::DocNode::getDocument(), llvm::msgpack::Document::getNode(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
operator[]() [4/6]
DocNode & MapDocNode::operator[] (StringRef S)
Member access.
Member access for MapDocNode.
The string data must remain valid for the lifetime of the Document.
Definition at line 36 of file MsgPackDocument.cpp.
References llvm::msgpack::DocNode::DocNode(), llvm::msgpack::DocNode::getDocument(), and llvm::msgpack::Document::getNode().
operator[]() [5/6]
DocNode & MapDocNode::operator[] (uint64_t Key)
Definition at line 61 of file MsgPackDocument.cpp.
References llvm::msgpack::DocNode::DocNode(), llvm::msgpack::DocNode::getDocument(), llvm::msgpack::Document::getNode(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
operator[]() [6/6]
DocNode & MapDocNode::operator[] (unsigned Key)
Definition at line 55 of file MsgPackDocument.cpp.
References llvm::msgpack::DocNode::DocNode(), llvm::msgpack::DocNode::getDocument(), llvm::msgpack::Document::getNode(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
size()
size_t llvm::msgpack::MapDocNode::size () const inline
Definition at line 233 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Map.
Referenced by empty().
The documentation for this class was generated from the following files:
include/llvm/BinaryFormat/MsgPackDocument.h
lib/BinaryFormat/MsgPackDocument.cpp