LLVM: llvm::codeview::ProcedureRecord Class Reference
llvm::codeview::ProcedureRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
ProcedureRecord ()=default
ProcedureRecord (TypeRecordKind Kind)
ProcedureRecord (TypeIndex ReturnType, CallingConvention CallConv, FunctionOptions Options, uint16_t ParameterCount, TypeIndex ArgumentList)
TypeIndex getReturnType () const
CallingConvention getCallConv () const
FunctionOptions getOptions () const
uint16_t getParameterCount () const
TypeIndex getArgumentList () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex ReturnType
CallingConvention CallConv = CallingConvention::NearC
FunctionOptions Options = FunctionOptions::None
uint16_t ParameterCount = 0
TypeIndex ArgumentList
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 146 of file TypeRecord.h.
Constructor & Destructor Documentation
ProcedureRecord() [1/3]
llvm::codeview::ProcedureRecord::ProcedureRecord () default
ProcedureRecord() [2/3]
llvm::codeview::ProcedureRecord::ProcedureRecord (TypeRecordKind Kind) inline explicit
Definition at line 149 of file TypeRecord.h.
References llvm::codeview::TypeRecord::Kind, and llvm::codeview::TypeRecord::TypeRecord().
ProcedureRecord() [3/3]
llvm::codeview::ProcedureRecord::ProcedureRecord (TypeIndex ReturnType, CallingConvention CallConv, FunctionOptions Options, uint16_t ParameterCount, TypeIndex ArgumentList) inline
Definition at line 150 of file TypeRecord.h.
References ArgumentList, CallConv, Options, ParameterCount, ReturnType, and llvm::codeview::TypeRecord::TypeRecord().
Member Function Documentation
getArgumentList()
TypeIndex llvm::codeview::ProcedureRecord::getArgumentList () const inline
Definition at line 161 of file TypeRecord.h.
References ArgumentList.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), and llvm::logicalview::LVTypeVisitor::visitKnownRecord().
getCallConv()
CallingConvention llvm::codeview::ProcedureRecord::getCallConv () const inline
Definition at line 158 of file TypeRecord.h.
References CallConv.
getOptions()
FunctionOptions llvm::codeview::ProcedureRecord::getOptions () const inline
Definition at line 159 of file TypeRecord.h.
References Options.
getParameterCount()
uint16_t llvm::codeview::ProcedureRecord::getParameterCount () const inline
Definition at line 160 of file TypeRecord.h.
References ParameterCount.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), and llvm::logicalview::LVTypeVisitor::visitKnownRecord().
getReturnType()
TypeIndex llvm::codeview::ProcedureRecord::getReturnType () const inline
Definition at line 157 of file TypeRecord.h.
References ReturnType.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), and llvm::logicalview::LVTypeVisitor::visitKnownRecord().
Member Data Documentation
ArgumentList
TypeIndex llvm::codeview::ProcedureRecord::ArgumentList
Definition at line 167 of file TypeRecord.h.
Referenced by getArgumentList(), and ProcedureRecord().
CallConv
CallingConvention llvm::codeview::ProcedureRecord::CallConv = CallingConvention::NearC
Definition at line 164 of file TypeRecord.h.
Referenced by getCallConv(), and ProcedureRecord().
Options
FunctionOptions llvm::codeview::ProcedureRecord::Options = FunctionOptions::None
Definition at line 165 of file TypeRecord.h.
Referenced by getOptions(), and ProcedureRecord().
ParameterCount
uint16_t llvm::codeview::ProcedureRecord::ParameterCount = 0
Definition at line 166 of file TypeRecord.h.
Referenced by getParameterCount(), and ProcedureRecord().
ReturnType
TypeIndex llvm::codeview::ProcedureRecord::ReturnType
Definition at line 163 of file TypeRecord.h.
Referenced by getReturnType(), and ProcedureRecord().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h