LLVM: llvm::lsp::JSONTransportInputOverFile Class Reference
llvm::lsp::JSONTransportInputOverFile Class Reference
Concrete implementation of the JSONTransportInput that reads from a file.
#include "llvm/Support/LSP/Transport.h"
Public Member Functions
JSONTransportInputOverFile (std::FILE *In, JSONStreamStyle Style=JSONStreamStyle::Standard)
bool hasError () const final
bool isEndOfInput () const final
LLVM_ABI_FOR_TEST LogicalResult readDelimitedMessage (std::string &Json) final
For lit tests we support a simplified syntax:
LLVM_ABI_FOR_TEST LogicalResult readStandardMessage (std::string &Json) final
Public Member Functions inherited from llvm::lsp::JSONTransportInput
JSONTransportInput (JSONStreamStyle Style=JSONStreamStyle::Standard)
virtual ~JSONTransportInput ()=default
LogicalResult readMessage (std::string &Json)
Read in a message from the input stream.
Detailed Description
Concrete implementation of the JSONTransportInput that reads from a file.
Definition at line 76 of file Transport.h.
Constructor & Destructor Documentation
JSONTransportInputOverFile()
llvm::lsp::JSONTransportInputOverFile::JSONTransportInputOverFile (std::FILE * In, JSONStreamStyle Style = JSONStreamStyle::Standard) inline explicit
Definition at line 78 of file Transport.h.
References llvm::lsp::JSONTransportInput::JSONTransportInput(), and llvm::lsp::Standard.
Member Function Documentation
hasError()
bool llvm::lsp::JSONTransportInputOverFile::hasError () const inline final virtual
Implements llvm::lsp::JSONTransportInput.
Definition at line 82 of file Transport.h.
References const.
Referenced by readStandardMessage().
isEndOfInput()
bool llvm::lsp::JSONTransportInputOverFile::isEndOfInput () const inline final virtual
Implements llvm::lsp::JSONTransportInput.
Definition at line 83 of file Transport.h.
References const.
readDelimitedMessage()
LogicalResult JSONTransportInputOverFile::readDelimitedMessage (std::string & Json) final virtual
For lit tests we support a simplified syntax:
messages are delimited by '// --—' on a line by itself
lines starting with // are ignored. This is a testing path, so favor simplicity over performance here. When returning failure: feof(), ferror(), or shutdownRequested() will be set.
Implements llvm::lsp::JSONTransportInput.
Definition at line 353 of file Transport.cpp.
References llvm::failure(), readLine(), llvm::StringRef::starts_with(), and llvm::succeeded().
readStandardMessage()
LogicalResult JSONTransportInputOverFile::readStandardMessage (std::string & Json) final virtual
Implements llvm::lsp::JSONTransportInput.
Definition at line 306 of file Transport.cpp.
References llvm::StringRef::consume_front(), llvm::StringRef::empty(), llvm::failed(), llvm::failure(), llvm::getAsUnsignedInteger(), hasError(), llvm::Read, readLine(), llvm::success(), and llvm::StringRef::trim().
The documentation for this class was generated from the following files:
include/llvm/Support/LSP/Transport.h
lib/Support/LSP/Transport.cpp