LLVM: llvm::UnsetInit Class Reference
llvm::UnsetInit Class Reference final
'?' - Represents an uninitialized value.
#include "llvm/TableGen/Record.h"
Public Member Functions
UnsetInit (const UnsetInit &)=delete
UnsetInit & operator= (const UnsetInit &)=delete
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
const Init * getCastTo (const RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
const Init * convertInitializerTo (const RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
const Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
bool isComplete () const override
Is this a complete value with no unset (uninitialized) subvalues?
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations?
std::string getAsString () const override
Get the string representation of the Init.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual const Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This function is used to implement the bit range selection operator.
virtual const RecTy * getFieldType (const StringInit *FieldName) const
This function is used to implement the FieldInit class.
virtual const Init * resolveReferences (Resolver &R) const
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Static Public Member Functions
static bool classof (const Init *I)
static UnsetInit * get (RecordKeeper &RK)
Get the singleton unset Init.
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_InstancesOpInit , IK_AnonymousNameInit ,
IK_StringInit , IK_VarInit , IK_VarBitInit , IK_VarDefInit ,
IK_LastTypedInit , IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.).
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
'?' - Represents an uninitialized value.
Definition at line 453 of file Record.h.
Constructor & Destructor Documentation
UnsetInit()
llvm::UnsetInit::UnsetInit (const UnsetInit &) delete
Member Function Documentation
classof()
bool llvm::UnsetInit::classof (const Init * I) inline static
Definition at line 465 of file Record.h.
References I, llvm::Init::IK_UnsetInit, and llvm::Init::Init().
convertInitializerTo()
const Init * UnsetInit::convertInitializerTo (const RecTy * Ty) const override virtual
Convert to a value whose type is Ty, or return null if this is not possible.
This can happen if the value's type is convertible to Ty, but there are unresolved references.
Implements llvm::Init.
Definition at line 395 of file Record.cpp.
References llvm::Init::Init().
get()
UnsetInit * UnsetInit::get (RecordKeeper & RK) static
Get the singleton unset Init.
Definition at line 389 of file Record.cpp.
Referenced by llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), llvm::RecordVal::RecordVal(), and llvm::RecordVal::RecordVal().
getAsString()
std::string llvm::UnsetInit::getAsString () const inline override virtual
Get the string representation of the Init.
Implements llvm::Init.
Definition at line 486 of file Record.h.
getBit()
const Init * llvm::UnsetInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 478 of file Record.h.
References llvm::Init::Init().
getCastTo()
const Init * UnsetInit::getCastTo (const RecTy * Ty) const override virtual
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Otherwise, return null.
Implements llvm::Init.
Definition at line 393 of file Record.cpp.
References llvm::Init::Init().
getRecordKeeper()
RecordKeeper & llvm::UnsetInit::getRecordKeeper () const inline
Get the record keeper that initialized this Init.
Definition at line 473 of file Record.h.
isComplete()
bool llvm::UnsetInit::isComplete () const inline override virtual
Is this a complete value with no unset (uninitialized) subvalues?
Reimplemented from llvm::Init.
Definition at line 481 of file Record.h.
isConcrete()
bool llvm::UnsetInit::isConcrete () const inline override virtual
Is this a concrete and fully resolved value without any references or stuck operations?
Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 483 of file Record.h.
operator=()
UnsetInit & llvm::UnsetInit::operator= (const UnsetInit &) delete
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp