LLVM: llvm::GCOVProfilerPass Class Reference
llvm::GCOVProfilerPass Class Reference
The gcov-style instrumentation pass.
#include "llvm/Transforms/Instrumentation/GCOVProfiler.h"
Public Member Functions
GCOVProfilerPass (const GCOVOptions &Options=GCOVOptions::getDefault(), IntrusiveRefCntPtr< vfs::FileSystem > VFS=vfs::getRealFileSystem())
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< GCOVProfilerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GCOVProfilerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The gcov-style instrumentation pass.
Definition at line 22 of file GCOVProfiler.h.
Constructor & Destructor Documentation
GCOVProfilerPass()
llvm::GCOVProfilerPass::GCOVProfilerPass (const GCOVOptions & Options = GCOVOptions::getDefault(), IntrusiveRefCntPtr< vfs::FileSystem > VFS = vfs::getRealFileSystem()) inline
Definition at line 24 of file GCOVProfiler.h.
References llvm::GCOVOptions::getDefault(), llvm::vfs::getRealFileSystem(), llvm::move(), and Options.
Member Function Documentation
run()
PreservedAnalyses GCOVProfilerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 560 of file GCOVProfiling.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/GCOVProfiler.h
lib/Transforms/Instrumentation/GCOVProfiling.cpp