LLVM: llvm::vfs::RedirectingFileSystemParser Class Reference
llvm::vfs::RedirectingFileSystemParser Class Reference
A helper class to hold the common YAML parsing state.
Public Member Functions
RedirectingFileSystemParser (yaml::Stream &S)
bool parse (yaml::Node *Root, RedirectingFileSystem *FS)
Static Public Member Functions
static RedirectingFileSystem::Entry * lookupOrCreateEntry (RedirectingFileSystem *FS, StringRef Name, RedirectingFileSystem::Entry *ParentEntry=nullptr)
Detailed Description
A helper class to hold the common YAML parsing state.
Definition at line 1663 of file VirtualFileSystem.cpp.
Constructor & Destructor Documentation
RedirectingFileSystemParser()
llvm::vfs::RedirectingFileSystemParser::RedirectingFileSystemParser (yaml::Stream & S) inline
Definition at line 2083 of file VirtualFileSystem.cpp.
Member Function Documentation
lookupOrCreateEntry()
RedirectingFileSystem::Entry * llvm::vfs::RedirectingFileSystemParser::lookupOrCreateEntry (RedirectingFileSystem * FS, StringRef Name, RedirectingFileSystem::Entry * ParentEntry = nullptr) inline static
Definition at line 1773 of file VirtualFileSystem.cpp.
References llvm::sys::fs::all_all, llvm::cast(), llvm::sys::fs::directory_file, llvm::dyn_cast(), llvm::vfs::getNextVirtualUniqueID(), and llvm::make_range().
Referenced by llvm::vfs::RedirectingFileSystem::create().
parse()
bool llvm::vfs::RedirectingFileSystemParser::parse (yaml::Node * Root, RedirectingFileSystem * FS) inline
Definition at line 2086 of file VirtualFileSystem.cpp.
References llvm::dyn_cast(), error, llvm::vfs::RedirectingFileSystem::Fallthrough, llvm::StringRef::getAsInteger(), I, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm_unreachable, llvm::vfs::RedirectingFileSystem::RedirectOnly, and llvm::Version.
The documentation for this class was generated from the following file:
lib/Support/VirtualFileSystem.cpp