LLVM: llvm::MipsTargetAsmStreamer Class Reference
llvm::MipsTargetAsmStreamer Class Reference
#include "Target/Mips/MCTargetDesc/MipsTargetStreamer.h"
Public Member Functions
MipsTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS)
void emitGPRel32Value (const MCExpr *) override
void emitGPRel64Value (const MCExpr *) override
void emitDTPRel32Value (const MCExpr *) override
void emitDTPRel64Value (const MCExpr *) override
void emitTPRel32Value (const MCExpr *) override
void emitTPRel64Value (const MCExpr *) override
void emitDirectiveSetMicroMips () override
void emitDirectiveSetNoMicroMips () override
void emitDirectiveSetMips16 () override
void emitDirectiveSetNoMips16 () override
void emitDirectiveSetReorder () override
void emitDirectiveSetNoReorder () override
void emitDirectiveSetMacro () override
void emitDirectiveSetNoMacro () override
void emitDirectiveSetMsa () override
void emitDirectiveSetNoMsa () override
void emitDirectiveSetMt () override
void emitDirectiveSetNoMt () override
void emitDirectiveSetCRC () override
void emitDirectiveSetNoCRC () override
void emitDirectiveSetVirt () override
void emitDirectiveSetNoVirt () override
void emitDirectiveSetGINV () override
void emitDirectiveSetNoGINV () override
void emitDirectiveSetAt () override
void emitDirectiveSetAtWithArg (unsigned RegNo) override
void emitDirectiveSetNoAt () override
void emitDirectiveEnd (StringRef Name) override
void emitDirectiveEnt (const MCSymbol &Symbol) override
void emitDirectiveAbiCalls () override
void emitDirectiveNaN2008 () override
void emitDirectiveNaNLegacy () override
void emitDirectiveOptionPic0 () override
void emitDirectiveOptionPic2 () override
void emitDirectiveInsn () override
void emitFrame (MCRegister StackReg, unsigned StackSize, MCRegister ReturnReg) override
void emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override
void emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override
void emitDirectiveSetArch (StringRef Arch) override
void emitDirectiveSetMips0 () override
void emitDirectiveSetMips1 () override
void emitDirectiveSetMips2 () override
void emitDirectiveSetMips3 () override
void emitDirectiveSetMips4 () override
void emitDirectiveSetMips5 () override
void emitDirectiveSetMips32 () override
void emitDirectiveSetMips32R2 () override
void emitDirectiveSetMips32R3 () override
void emitDirectiveSetMips32R5 () override
void emitDirectiveSetMips32R6 () override
void emitDirectiveSetMips64 () override
void emitDirectiveSetMips64R2 () override
void emitDirectiveSetMips64R3 () override
void emitDirectiveSetMips64R5 () override
void emitDirectiveSetMips64R6 () override
void emitDirectiveSetDsp () override
void emitDirectiveSetDspr2 () override
void emitDirectiveSetNoDsp () override
void emitDirectiveSetMips3D () override
void emitDirectiveSetNoMips3D () override
void emitDirectiveSetPop () override
void emitDirectiveSetPush () override
void emitDirectiveSetSoftFloat () override
void emitDirectiveSetHardFloat () override
void emitDirectiveCpAdd (MCRegister Reg) override
void emitDirectiveCpLoad (MCRegister Reg) override
void emitDirectiveCpLocal (MCRegister Reg) override
bool emitDirectiveCpRestore (int Offset, function_ref< MCRegister()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI) override
Emit a .cprestore directive.
void emitDirectiveCpsetup (MCRegister Reg, int RegOrOffset, const MCSymbol &Sym, bool IsReg) override
void emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister) override
void emitDirectiveModuleFP () override
void emitDirectiveModuleOddSPReg () override
void emitDirectiveModuleSoftFloat () override
void emitDirectiveModuleHardFloat () override
void emitDirectiveModuleMT () override
void emitDirectiveModuleCRC () override
void emitDirectiveModuleNoCRC () override
void emitDirectiveModuleVirt () override
void emitDirectiveModuleNoVirt () override
void emitDirectiveModuleGINV () override
void emitDirectiveModuleNoGINV () override
void emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value) override
void emitDirectiveSetOddSPReg () override
void emitDirectiveSetNoOddSPReg () override
Public Member Functions inherited from llvm::MipsTargetStreamer
MipsTargetStreamer (MCStreamer &S)
virtual void setPic (bool Value)
virtual void setUsesMicroMips ()
void emitR (unsigned Opcode, MCRegister Reg0, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitII (unsigned Opcode, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRX (unsigned Opcode, MCRegister Reg0, MCOperand Op1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRI (unsigned Opcode, MCRegister Reg0, int32_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRR (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRX (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, MCOperand Op2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRR (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, MCRegister Reg2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRRX (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, MCRegister Reg2, MCOperand Op3, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRI (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, int16_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRIII (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, int16_t Imm0, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitAddu (MCRegister DstReg, MCRegister SrcReg, MCRegister TrgReg, bool Is64Bit, const MCSubtargetInfo *STI)
void emitDSLL (MCRegister DstReg, MCRegister SrcReg, int16_t ShiftAmount, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitEmptyDelaySlot (bool hasShortDelaySlot, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitNop (SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitStoreWithImmOffset (unsigned Opcode, MCRegister SrcReg, MCRegister BaseReg, int64_t Offset, function_ref< MCRegister()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a store instruction with an offset.
void emitLoadWithImmOffset (unsigned Opcode, MCRegister DstReg, MCRegister BaseReg, int64_t Offset, MCRegister TmpReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a load instruction with an immediate offset.
void emitGPRestore (int Offset, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit the $gp restore operation for .cprestore.
void forbidModuleDirective ()
void reallowModuleDirective ()
bool isModuleDirectiveAllowed ()
template<class PredicateLibrary>
void updateABIInfo (const PredicateLibrary &P)
MipsABIFlagsSection & getABIFlagsSection ()
const MipsABIInfo & getABI () const
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MipsTargetStreamer
std::optional< MipsABIInfo > ABI
MipsABIFlagsSection ABIFlagsSection
bool GPRInfoSet
unsigned GPRBitMask
int GPROffset
bool FPRInfoSet
unsigned FPRBitMask
int FPROffset
bool FrameInfoSet
int FrameOffset
unsigned FrameReg
MCRegister GPReg
unsigned ReturnReg
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 216 of file MipsTargetStreamer.h.
Constructor & Destructor Documentation
MipsTargetAsmStreamer()
MipsTargetAsmStreamer::MipsTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS)
Definition at line 393 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::MipsTargetStreamer().
Member Function Documentation
emitDirectiveAbiCalls()
void MipsTargetAsmStreamer::emitDirectiveAbiCalls () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 552 of file MipsTargetStreamer.cpp.
emitDirectiveCpAdd()
void MipsTargetAsmStreamer::emitDirectiveCpAdd (MCRegister Reg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 732 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsInstPrinter::getRegisterName(), and llvm::StringRef::lower().
emitDirectiveCpLoad()
void MipsTargetAsmStreamer::emitDirectiveCpLoad (MCRegister Reg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 738 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsInstPrinter::getRegisterName(), and llvm::StringRef::lower().
emitDirectiveCpLocal()
void MipsTargetAsmStreamer::emitDirectiveCpLocal (MCRegister Reg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 744 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveCpLocal(), llvm::MipsInstPrinter::getRegisterName(), and llvm::StringRef::lower().
emitDirectiveCpRestore()
bool MipsTargetAsmStreamer::emitDirectiveCpRestore (int Offset, function_ref< MCRegister()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo * STI) override virtual
Emit a .cprestore directive.
If the offset is out of range then it will be synthesized using the assembler temporary.
GetATReg() is a callback that can be used to obtain the current assembler temporary and is only called when the assembler temporary is required. It must handle the case where no assembler temporary is available (typically by reporting an error).
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 750 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveCpRestore(), and llvm::Offset.
emitDirectiveCpreturn()
void MipsTargetAsmStreamer::emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 777 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveCpsetup()
void MipsTargetAsmStreamer::emitDirectiveCpsetup (MCRegister Reg, int RegOrOffset, const MCSymbol & Sym, bool IsReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 758 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCSymbol::getName(), llvm::MipsInstPrinter::getRegisterName(), and llvm::StringRef::lower().
emitDirectiveEnd()
void MipsTargetAsmStreamer::emitDirectiveEnd (StringRef Name) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 544 of file MipsTargetStreamer.cpp.
emitDirectiveEnt()
void MipsTargetAsmStreamer::emitDirectiveEnt (const MCSymbol & Symbol) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 548 of file MipsTargetStreamer.cpp.
emitDirectiveInsn()
void MipsTargetAsmStreamer::emitDirectiveInsn () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 568 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveInsn().
emitDirectiveModuleCRC()
void MipsTargetAsmStreamer::emitDirectiveModuleCRC () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 827 of file MipsTargetStreamer.cpp.
emitDirectiveModuleFP()
void MipsTargetAsmStreamer::emitDirectiveModuleFP () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 783 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, and llvm::MipsABIFlagsSection::SOFT.
emitDirectiveModuleGINV()
void MipsTargetAsmStreamer::emitDirectiveModuleGINV () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 843 of file MipsTargetStreamer.cpp.
emitDirectiveModuleHardFloat()
void MipsTargetAsmStreamer::emitDirectiveModuleHardFloat () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 819 of file MipsTargetStreamer.cpp.
emitDirectiveModuleMT()
void MipsTargetAsmStreamer::emitDirectiveModuleMT () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 823 of file MipsTargetStreamer.cpp.
emitDirectiveModuleNoCRC()
void MipsTargetAsmStreamer::emitDirectiveModuleNoCRC () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 831 of file MipsTargetStreamer.cpp.
emitDirectiveModuleNoGINV()
void MipsTargetAsmStreamer::emitDirectiveModuleNoGINV () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 847 of file MipsTargetStreamer.cpp.
emitDirectiveModuleNoVirt()
void MipsTargetAsmStreamer::emitDirectiveModuleNoVirt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 839 of file MipsTargetStreamer.cpp.
emitDirectiveModuleOddSPReg()
void MipsTargetAsmStreamer::emitDirectiveModuleOddSPReg () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 799 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, and llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg().
emitDirectiveModuleSoftFloat()
void MipsTargetAsmStreamer::emitDirectiveModuleSoftFloat () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 815 of file MipsTargetStreamer.cpp.
emitDirectiveModuleVirt()
void MipsTargetAsmStreamer::emitDirectiveModuleVirt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 835 of file MipsTargetStreamer.cpp.
emitDirectiveNaN2008()
void MipsTargetAsmStreamer::emitDirectiveNaN2008 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 554 of file MipsTargetStreamer.cpp.
emitDirectiveNaNLegacy()
void MipsTargetAsmStreamer::emitDirectiveNaNLegacy () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 556 of file MipsTargetStreamer.cpp.
emitDirectiveOptionPic0()
void MipsTargetAsmStreamer::emitDirectiveOptionPic0 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 560 of file MipsTargetStreamer.cpp.
emitDirectiveOptionPic2()
void MipsTargetAsmStreamer::emitDirectiveOptionPic2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 564 of file MipsTargetStreamer.cpp.
emitDirectiveSetArch()
void MipsTargetAsmStreamer::emitDirectiveSetArch (StringRef Arch) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 581 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetArch().
emitDirectiveSetAt()
void MipsTargetAsmStreamer::emitDirectiveSetAt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 529 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetAt().
emitDirectiveSetAtWithArg()
void MipsTargetAsmStreamer::emitDirectiveSetAtWithArg (unsigned RegNo) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 534 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetAtWithArg().
emitDirectiveSetCRC()
void MipsTargetAsmStreamer::emitDirectiveSetCRC () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 499 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetCRC().
emitDirectiveSetDsp()
void MipsTargetAsmStreamer::emitDirectiveSetDsp () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 666 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetDsp().
emitDirectiveSetDspr2()
void MipsTargetAsmStreamer::emitDirectiveSetDspr2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 671 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetDspr2().
emitDirectiveSetFp()
void MipsTargetAsmStreamer::emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 791 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, and llvm::MipsTargetStreamer::emitDirectiveSetFp().
emitDirectiveSetGINV()
void MipsTargetAsmStreamer::emitDirectiveSetGINV () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 519 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetGINV().
emitDirectiveSetHardFloat()
void MipsTargetAsmStreamer::emitDirectiveSetHardFloat () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 706 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetHardFloat().
emitDirectiveSetMacro()
void MipsTargetAsmStreamer::emitDirectiveSetMacro () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 469 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMacro().
emitDirectiveSetMicroMips()
void MipsTargetAsmStreamer::emitDirectiveSetMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 439 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetMips0()
void MipsTargetAsmStreamer::emitDirectiveSetMips0 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 586 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips0().
emitDirectiveSetMips1()
void MipsTargetAsmStreamer::emitDirectiveSetMips1 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 591 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips1().
emitDirectiveSetMips16()
void MipsTargetAsmStreamer::emitDirectiveSetMips16 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 449 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetMips2()
void MipsTargetAsmStreamer::emitDirectiveSetMips2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 596 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips2().
emitDirectiveSetMips3()
void MipsTargetAsmStreamer::emitDirectiveSetMips3 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 601 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips3().
emitDirectiveSetMips32()
void MipsTargetAsmStreamer::emitDirectiveSetMips32 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 616 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32().
emitDirectiveSetMips32R2()
void MipsTargetAsmStreamer::emitDirectiveSetMips32R2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 621 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32R2().
emitDirectiveSetMips32R3()
void MipsTargetAsmStreamer::emitDirectiveSetMips32R3 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 626 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32R3().
emitDirectiveSetMips32R5()
void MipsTargetAsmStreamer::emitDirectiveSetMips32R5 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 631 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32R5().
emitDirectiveSetMips32R6()
void MipsTargetAsmStreamer::emitDirectiveSetMips32R6 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 636 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32R6().
emitDirectiveSetMips3D()
void MipsTargetAsmStreamer::emitDirectiveSetMips3D () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 681 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips3D().
emitDirectiveSetMips4()
void MipsTargetAsmStreamer::emitDirectiveSetMips4 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 606 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips4().
emitDirectiveSetMips5()
void MipsTargetAsmStreamer::emitDirectiveSetMips5 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 611 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips5().
emitDirectiveSetMips64()
void MipsTargetAsmStreamer::emitDirectiveSetMips64 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 641 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64().
emitDirectiveSetMips64R2()
void MipsTargetAsmStreamer::emitDirectiveSetMips64R2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 646 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64R2().
emitDirectiveSetMips64R3()
void MipsTargetAsmStreamer::emitDirectiveSetMips64R3 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 651 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64R3().
emitDirectiveSetMips64R5()
void MipsTargetAsmStreamer::emitDirectiveSetMips64R5 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 656 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64R5().
emitDirectiveSetMips64R6()
void MipsTargetAsmStreamer::emitDirectiveSetMips64R6 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 661 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64R6().
emitDirectiveSetMsa()
void MipsTargetAsmStreamer::emitDirectiveSetMsa () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 479 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMsa().
emitDirectiveSetMt()
void MipsTargetAsmStreamer::emitDirectiveSetMt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 489 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMt().
emitDirectiveSetNoAt()
void MipsTargetAsmStreamer::emitDirectiveSetNoAt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 539 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoAt().
emitDirectiveSetNoCRC()
void MipsTargetAsmStreamer::emitDirectiveSetNoCRC () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 504 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoCRC().
emitDirectiveSetNoDsp()
void MipsTargetAsmStreamer::emitDirectiveSetNoDsp () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 676 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoDsp().
emitDirectiveSetNoGINV()
void MipsTargetAsmStreamer::emitDirectiveSetNoGINV () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 524 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoGINV().
emitDirectiveSetNoMacro()
void MipsTargetAsmStreamer::emitDirectiveSetNoMacro () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 474 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMacro().
emitDirectiveSetNoMicroMips()
void MipsTargetAsmStreamer::emitDirectiveSetNoMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 444 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetNoMips16()
void MipsTargetAsmStreamer::emitDirectiveSetNoMips16 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 454 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMips16().
emitDirectiveSetNoMips3D()
void MipsTargetAsmStreamer::emitDirectiveSetNoMips3D () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 686 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMips3D().
emitDirectiveSetNoMsa()
void MipsTargetAsmStreamer::emitDirectiveSetNoMsa () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 484 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMsa().
emitDirectiveSetNoMt()
void MipsTargetAsmStreamer::emitDirectiveSetNoMt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 494 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMt().
emitDirectiveSetNoOddSPReg()
void MipsTargetAsmStreamer::emitDirectiveSetNoOddSPReg () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 810 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoOddSPReg().
emitDirectiveSetNoReorder()
void MipsTargetAsmStreamer::emitDirectiveSetNoReorder () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 464 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetNoVirt()
void MipsTargetAsmStreamer::emitDirectiveSetNoVirt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 514 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoVirt().
emitDirectiveSetOddSPReg()
void MipsTargetAsmStreamer::emitDirectiveSetOddSPReg () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 805 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetOddSPReg().
emitDirectiveSetPop()
void MipsTargetAsmStreamer::emitDirectiveSetPop () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 691 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetPop().
emitDirectiveSetPush()
void MipsTargetAsmStreamer::emitDirectiveSetPush () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 696 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetPush().
emitDirectiveSetReorder()
void MipsTargetAsmStreamer::emitDirectiveSetReorder () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 459 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetReorder().
emitDirectiveSetSoftFloat()
void MipsTargetAsmStreamer::emitDirectiveSetSoftFloat () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 701 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetSoftFloat().
emitDirectiveSetVirt()
void MipsTargetAsmStreamer::emitDirectiveSetVirt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 509 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetVirt().
emitDTPRel32Value()
void MipsTargetAsmStreamer::emitDTPRel32Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 397 of file MipsTargetStreamer.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCTargetStreamer::getStreamer(), and llvm::MCAsmInfo::printExpr().
emitDTPRel64Value()
void MipsTargetAsmStreamer::emitDTPRel64Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 404 of file MipsTargetStreamer.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCTargetStreamer::getStreamer(), and llvm::MCAsmInfo::printExpr().
emitFMask()
void MipsTargetAsmStreamer::emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 725 of file MipsTargetStreamer.cpp.
References printHex32().
emitFrame()
void MipsTargetAsmStreamer::emitFrame (MCRegister StackReg, unsigned StackSize, MCRegister ReturnReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 573 of file MipsTargetStreamer.cpp.
References llvm::MipsInstPrinter::getRegisterName(), llvm::StringRef::lower(), and llvm::MipsTargetStreamer::ReturnReg.
emitGPRel32Value()
void MipsTargetAsmStreamer::emitGPRel32Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 425 of file MipsTargetStreamer.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCTargetStreamer::getStreamer(), and llvm::MCAsmInfo::printExpr().
emitGPRel64Value()
void MipsTargetAsmStreamer::emitGPRel64Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 432 of file MipsTargetStreamer.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCTargetStreamer::getStreamer(), and llvm::MCAsmInfo::printExpr().
emitMask()
void MipsTargetAsmStreamer::emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 718 of file MipsTargetStreamer.cpp.
References printHex32().
emitTPRel32Value()
void MipsTargetAsmStreamer::emitTPRel32Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 411 of file MipsTargetStreamer.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCTargetStreamer::getStreamer(), and llvm::MCAsmInfo::printExpr().
emitTPRel64Value()
void MipsTargetAsmStreamer::emitTPRel64Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 418 of file MipsTargetStreamer.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCTargetStreamer::getStreamer(), and llvm::MCAsmInfo::printExpr().
The documentation for this class was generated from the following files:
lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.h
lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp