LLVM: llvm::sandboxir::OpaqueValue Class Reference
llvm::sandboxir::OpaqueValue Class Reference
#include "llvm/SandboxIR/Value.h"
Public Member Functions
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
virtual void dumpCommonHeader (raw_ostream &OS) const
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Value *From)
Protected Member Functions
OpaqueValue (llvm::Value *V, Context &Ctx)
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Friends
class Context
Additional Inherited Members
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 292 of file Value.h.
Constructor & Destructor Documentation
OpaqueValue()
llvm::sandboxir::OpaqueValue::OpaqueValue (llvm::Value * V, Context & Ctx) inline protected
Definition at line 294 of file Value.h.
References Context, llvm::sandboxir::Value::Ctx, OpaqueValue(), and llvm::sandboxir::Value::Value().
Referenced by OpaqueValue().
Member Function Documentation
classof()
bool llvm::sandboxir::OpaqueValue::classof (const Value * From) inline static
Definition at line 299 of file Value.h.
References llvm::sandboxir::Value::getSubclassID(), and llvm::sandboxir::Value::Value().
dumpOS()
void llvm::sandboxir::OpaqueValue::dumpOS (raw_ostream & OS) const inline override virtual
Implements llvm::sandboxir::Value.
Definition at line 307 of file Value.h.
References llvm::sandboxir::Value::dumpCommonPrefix(), and llvm::sandboxir::Value::dumpCommonSuffix().
verify()
void llvm::sandboxir::OpaqueValue::verify () const inline override virtual
Should crash if there is something wrong with the instruction.
Implements llvm::sandboxir::Value.
Definition at line 303 of file Value.h.
References assert(), llvm::isa(), and llvm::sandboxir::Value::Val.
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 296 of file Value.h.
References Context.
Referenced by Context, and OpaqueValue().
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Value.h