LLVM: llvm::BaseRecord Class Reference
llvm::BaseRecord Class Reference
#include "llvm/TableGen/DirectiveEmitter.h"
Public Member Functions
BaseRecord (const Record *Def)
std::vector< Spelling::Value > getSpellings () const
StringRef getSpellingForIdentifier () const
std::string getFormattedName () const
bool isDefault () const
StringRef getRecordName () const
const Record * getRecord () const
Static Public Member Functions
static std::string getSnakeName (StringRef Name)
static std::string getUpperCamelName (StringRef Name, StringRef Sep)
Protected Attributes
const Record * Def
Detailed Description
Definition at line 145 of file DirectiveEmitter.h.
Constructor & Destructor Documentation
BaseRecord()
llvm::BaseRecord::BaseRecord (const Record * Def) inline
Definition at line 147 of file DirectiveEmitter.h.
References Def.
Referenced by llvm::Clause::Clause(), llvm::Directive::Directive(), and llvm::EnumVal::EnumVal().
Member Function Documentation
getFormattedName()
std::string llvm::BaseRecord::getFormattedName () const inline
Definition at line 212 of file DirectiveEmitter.h.
References Def, getSnakeName(), and getSpellingForIdentifier().
getRecord()
const Record * llvm::BaseRecord::getRecord () const inline
Definition at line 223 of file DirectiveEmitter.h.
References Def.
getRecordName()
StringRef llvm::BaseRecord::getRecordName () const inline
Definition at line 221 of file DirectiveEmitter.h.
References Def.
getSnakeName()
std::string llvm::BaseRecord::getSnakeName (StringRef Name) inline static
Definition at line 177 of file DirectiveEmitter.h.
References N, and llvm::replace().
Referenced by getFormattedName().
getSpellingForIdentifier()
StringRef llvm::BaseRecord::getSpellingForIdentifier () const inline
Definition at line 157 of file DirectiveEmitter.h.
References getSpellings(), llvm::directive::VersionRange::Min, llvm::directive::Spelling::Name, and llvm::directive::Spelling::Versions.
Referenced by llvm::Clause::getClangAccSpelling(), llvm::Directive::getClangAccSpelling(), getFormattedName(), and llvm::Clause::getFormattedParserClassName().
getSpellings()
std::vector< Spelling::Value > llvm::BaseRecord::getSpellings () const inline
Definition at line 149 of file DirectiveEmitter.h.
References Def, and llvm::transform().
Referenced by getSpellingForIdentifier().
getUpperCamelName()
std::string llvm::BaseRecord::getUpperCamelName (StringRef Name, StringRef Sep) inline static
Definition at line 187 of file DirectiveEmitter.h.
References llvm::CallingConv::C, if(), and llvm::transform().
Referenced by llvm::Clause::getClangAccSpelling(), llvm::Directive::getClangAccSpelling(), and llvm::Clause::getFormattedParserClassName().
isDefault()
bool llvm::BaseRecord::isDefault () const inline
Definition at line 218 of file DirectiveEmitter.h.
References Def.
Member Data Documentation
Def
const Record* llvm::BaseRecord::Def protected
Definition at line 226 of file DirectiveEmitter.h.
Referenced by BaseRecord(), llvm::Clause::Clause(), llvm::Directive::Directive(), llvm::EnumVal::EnumVal(), llvm::Clause::getAliases(), llvm::Directive::getAllowedClauses(), llvm::Directive::getAllowedExclusiveClauses(), llvm::Directive::getAllowedOnceClauses(), llvm::Directive::getAssociation(), llvm::Directive::getCategory(), llvm::Clause::getClangAccSpelling(), llvm::Clause::getClangClass(), llvm::Clause::getClauseVals(), llvm::Clause::getDefaultValue(), llvm::Clause::getEnumName(), llvm::Clause::getFlangClass(), getFormattedName(), llvm::Directive::getLeafConstructs(), llvm::Clause::getPrefix(), getRecord(), getRecordName(), llvm::Directive::getRequiredClauses(), llvm::Directive::getSourceLanguages(), getSpellings(), llvm::EnumVal::getValue(), isDefault(), llvm::Clause::isImplicit(), llvm::Clause::isPrefixOptional(), llvm::EnumVal::isUserVisible(), llvm::Clause::isValueList(), llvm::Clause::isValueOptional(), and llvm::Clause::skipFlangUnparser().
The documentation for this class was generated from the following file:
include/llvm/TableGen/DirectiveEmitter.h