LLVM: llvm::RegionNode Class Reference
llvm::RegionNode Class Reference
#include "llvm/Analysis/RegionInfo.h"
Public Member Functions
RegionNode (Region *Parent, BasicBlock *Entry, bool isSubRegion=false)
bool operator== (const Region &RN) const
Public Member Functions inherited from llvm::RegionNodeBase< RegionTraits< Function > >
BasicBlock * getNodeAs () const
Region * getNodeAs () const
MachineBasicBlock * getNodeAs () const
MachineRegion * getNodeAs () const
RegionNodeBase & operator= (const RegionNodeBase &)=delete
RegionT * getParent () const
Get the parent Region of this RegionNode.
BlockT * getEntry () const
Get the entry BasicBlock of this RegionNode.
bool isSubRegion () const
Is this RegionNode a subregion?
Additional Inherited Members
Public Types inherited from llvm::RegionNodeBase< RegionTraits< Function > >
using BlockT
using RegionT
Protected Member Functions inherited from llvm::RegionNodeBase< RegionTraits< Function > >
RegionNodeBase (RegionT *Parent, BlockT *Entry, bool isSubRegion=false)
Create a RegionNode.
Detailed Description
Definition at line 877 of file RegionInfo.h.
Constructor & Destructor Documentation
RegionNode()
llvm::RegionNode::RegionNode (Region * Parent, BasicBlock * Entry, bool isSubRegion = false) inline
Definition at line 879 of file RegionInfo.h.
References llvm::RegionNodeBase< RegionTraits< Function > >::isSubRegion(), and llvm::RegionNodeBase< RegionTraits< Function > >::RegionNodeBase().
Referenced by operator==().
Member Function Documentation
operator==()
bool llvm::RegionNode::operator== (const Region & RN) const inline
Definition at line 882 of file RegionInfo.h.
References RegionNode().
The documentation for this class was generated from the following file:
include/llvm/Analysis/RegionInfo.h