LLVM: llvm::orc::ObjectFileLoader Class Reference
llvm::orc::ObjectFileLoader Class Reference
Loads an object file and provides access to it.
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h"
Public Member Functions
ObjectFileLoader (StringRef Path)
Construct an object file loader from the given path.
ObjectFileLoader (const ObjectFileLoader &)=delete
ObjectFileLoader & operator= (const ObjectFileLoader &)=delete
ObjectFileLoader (ObjectFileLoader &&)=default
ObjectFileLoader & operator= (ObjectFileLoader &&)=default
Expected< object::ObjectFile & > getObjectFile ()
Get the loaded object file, or return an error if loading failed.
Static Public Member Functions
static bool isArchitectureCompatible (const object::ObjectFile &Obj)
Detailed Description
Loads an object file and provides access to it.
Owns the underlying ObjectFile and ensures it is valid. Any errors encountered during construction are stored and returned when attempting to access the file.
Definition at line 189 of file LibraryScanner.h.
Constructor & Destructor Documentation
ObjectFileLoader() [1/3]
llvm::orc::ObjectFileLoader::ObjectFileLoader (StringRef Path) inline explicit
Construct an object file loader from the given path.
Definition at line 192 of file LibraryScanner.h.
References llvm::consumeError().
Referenced by ObjectFileLoader(), ObjectFileLoader(), operator=(), and operator=().
ObjectFileLoader() [2/3]
llvm::orc::ObjectFileLoader::ObjectFileLoader (const ObjectFileLoader &) delete
References ObjectFileLoader().
ObjectFileLoader() [3/3]
llvm::orc::ObjectFileLoader::ObjectFileLoader (ObjectFileLoader &&) default
References ObjectFileLoader().
Member Function Documentation
getObjectFile()
Expected< object::ObjectFile & > llvm::orc::ObjectFileLoader::getObjectFile () inline
Get the loaded object file, or return an error if loading failed.
Definition at line 209 of file LibraryScanner.h.
References llvm::createStringError(), and llvm::inconvertibleErrorCode().
Referenced by llvm::orc::LibraryResolver::SymbolEnumerator::enumerateSymbols(), and llvm::orc::DylibPathValidator::isSharedLibrary().
isArchitectureCompatible()
bool llvm::orc::ObjectFileLoader::isArchitectureCompatible (const object::ObjectFile & Obj) static
Definition at line 52 of file LibraryScanner.cpp.
References llvm::Triple::getArch(), llvm::Triple::getObjectFormat(), and llvm::sys::getProcessTriple().
operator=() [1/2]
ObjectFileLoader & llvm::orc::ObjectFileLoader::operator= (const ObjectFileLoader &) delete
References ObjectFileLoader().
operator=() [2/2]
ObjectFileLoader & llvm::orc::ObjectFileLoader::operator= (ObjectFileLoader &&) default
References ObjectFileLoader().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryScanner.cpp