LLVM: llvm::jitlink::XCOFFLinkGraphBuilder Class Reference
llvm::jitlink::XCOFFLinkGraphBuilder Class Reference
#include "ExecutionEngine/JITLink/XCOFFLinkGraphBuilder.h"
Public Member Functions
virtual ~XCOFFLinkGraphBuilder ()=default
Expected< std::unique_ptr< LinkGraph > > buildGraph ()
XCOFFLinkGraphBuilder (const object::XCOFFObjectFile &Obj, std::shared_ptr< orc::SymbolStringPool > SSP, Triple TT, SubtargetFeatures Features, LinkGraph::GetEdgeKindNameFunction GetEdgeKindName)
LinkGraph & getGraph () const
const object::XCOFFObjectFile & getObject () const
Detailed Description
Definition at line 26 of file XCOFFLinkGraphBuilder.h.
Constructor & Destructor Documentation
~XCOFFLinkGraphBuilder()
virtual llvm::jitlink::XCOFFLinkGraphBuilder::~XCOFFLinkGraphBuilder () virtual default
XCOFFLinkGraphBuilder()
llvm::jitlink::XCOFFLinkGraphBuilder::XCOFFLinkGraphBuilder (const object::XCOFFObjectFile & Obj, std::shared_ptr< orc::SymbolStringPool > SSP, Triple TT, SubtargetFeatures Features, LinkGraph::GetEdgeKindNameFunction GetEdgeKindName)
Definition at line 33 of file XCOFFLinkGraphBuilder.cpp.
References getFileName(), and llvm::move().
Member Function Documentation
buildGraph()
Expected< std::unique_ptr< LinkGraph > > llvm::jitlink::XCOFFLinkGraphBuilder::buildGraph ()
Definition at line 404 of file XCOFFLinkGraphBuilder.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Referenced by llvm::jitlink::createLinkGraphFromXCOFFObject_ppc64().
getGraph()
LinkGraph & llvm::jitlink::XCOFFLinkGraphBuilder::getGraph () const inline
Definition at line 36 of file XCOFFLinkGraphBuilder.h.
getObject()
const object::XCOFFObjectFile & llvm::jitlink::XCOFFLinkGraphBuilder::getObject () const inline
Definition at line 37 of file XCOFFLinkGraphBuilder.h.
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/XCOFFLinkGraphBuilder.h
lib/ExecutionEngine/JITLink/XCOFFLinkGraphBuilder.cpp