LLVM: llvm::mca::RISCVLMULInstrument Class Reference
llvm::mca::RISCVLMULInstrument Class Reference
#include "Target/RISCV/MCA/RISCVCustomBehaviour.h"
Public Member Functions
RISCVLMULInstrument (StringRef Data)
~RISCVLMULInstrument () override=default
uint8_t getLMUL () const
Public Member Functions inherited from llvm::mca::Instrument
Instrument (StringRef Desc, StringRef Data)
Instrument ()
virtual ~Instrument ()=default
StringRef getDesc () const
StringRef getData () const
Static Public Member Functions
static bool isDataValid (StringRef Data)
Static Public Attributes
static const StringRef DESC_NAME = "RISCV-LMUL"
Detailed Description
Definition at line 29 of file RISCVCustomBehaviour.h.
Constructor & Destructor Documentation
RISCVLMULInstrument()
llvm::mca::RISCVLMULInstrument::RISCVLMULInstrument (StringRef Data) inline explicit
Definition at line 34 of file RISCVCustomBehaviour.h.
References DESC_NAME, and llvm::mca::Instrument::Instrument().
~RISCVLMULInstrument()
llvm::mca::RISCVLMULInstrument::~RISCVLMULInstrument () override default
Member Function Documentation
getLMUL()
uint8_t llvm::mca::RISCVLMULInstrument::getLMUL () const
Definition at line 50 of file RISCVCustomBehaviour.cpp.
References assert(), llvm::StringSwitch< T, R >::Case(), llvm::mca::Instrument::getData(), and isDataValid().
Referenced by llvm::mca::RISCVInstrumentManager::getSchedClassID().
isDataValid()
bool llvm::mca::RISCVLMULInstrument::isDataValid (llvm::StringRef Data) static
Definition at line 43 of file RISCVCustomBehaviour.cpp.
References llvm::StringSwitch< T, R >::Cases(), and Default.
Referenced by llvm::mca::RISCVInstrumentManager::createInstrument(), and getLMUL().
Member Data Documentation
DESC_NAME
const llvm::StringRef llvm::mca::RISCVLMULInstrument::DESC_NAME = "RISCV-LMUL" static
Definition at line 31 of file RISCVCustomBehaviour.h.
Referenced by llvm::mca::RISCVInstrumentManager::createInstrument(), llvm::mca::RISCVInstrumentManager::createInstruments(), llvm::mca::RISCVInstrumentManager::getSchedClassID(), RISCVLMULInstrument(), and llvm::mca::RISCVInstrumentManager::supportsInstrumentType().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCA/RISCVCustomBehaviour.h
lib/Target/RISCV/MCA/RISCVCustomBehaviour.cpp