LLVM: llvm::LLParser Class Reference
llvm::LLParser Class Reference
#include "llvm/AsmParser/LLParser.h"
Public Types
typedef LLLexer::LocTy LocTy
Public Member Functions
LLParser (StringRef F, SourceMgr &SM, SMDiagnostic &Err, Module *M, ModuleSummaryIndex *Index, LLVMContext &Context, SlotMapping *Slots=nullptr, AsmParserContext *ParserContext=nullptr)
bool Run (bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback=[](StringRef, StringRef) { return std::nullopt;})
Run: module ::= toplevelentity*.
bool parseStandaloneConstantValue (Constant *&C, const SlotMapping *Slots)
bool parseTypeAtBeginning (Type *&Ty, unsigned &Read, const SlotMapping *Slots)
bool parseDIExpressionBodyAtBeginning (MDNode *&Result, unsigned &Read, const SlotMapping *Slots)
LLVMContext & getContext ()
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDAPSIntField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDUnsignedField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, LineField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, ColumnField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfTagField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfMacinfoTypeField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfVirtualityField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfEnumKindField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfLangField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfSourceLangNameField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfCCField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, EmissionKindField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, FixedPointKindField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, NameTableKindField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DwarfAttEncodingField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, DIFlagField &Result)
DIFlagField ::= uint32 ::= DIFlagVector ::= DIFlagVector '|' DIFlagFwdDecl '|' uint32 '|' DIFlagPublic.
template<>
bool parseMDField (LocTy Loc, StringRef Name, DISPFlagField &Result)
DISPFlagField ::= uint32 ::= DISPFlagVector ::= DISPFlagVector '|' DISPFlag* '|' uint32.
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDSignedField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDBoolField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDSignedOrMDField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDUnsignedOrMDField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDStringField &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, MDFieldList &Result)
template<>
bool parseMDField (LocTy Loc, StringRef Name, ChecksumKindField &Result)
Detailed Description
Definition at line 108 of file LLParser.h.
Member Typedef Documentation
LocTy
typedef LLLexer::LocTy llvm::LLParser::LocTy
Definition at line 110 of file LLParser.h.
Constructor & Destructor Documentation
LLParser()
llvm::LLParser::LLParser (StringRef F, SourceMgr & SM, SMDiagnostic & Err, Module * M, ModuleSummaryIndex * Index, LLVMContext & Context, SlotMapping * Slots = nullptr, AsmParserContext * ParserContext = nullptr) inline
Definition at line 194 of file LLParser.h.
References F, nullptr, and SM().
Member Function Documentation
getContext()
LLVMContext & llvm::LLParser::getContext () inline
Definition at line 215 of file LLParser.h.
parseDIExpressionBodyAtBeginning()
bool LLParser::parseDIExpressionBodyAtBeginning (MDNode *& Result, unsigned & Read, const SlotMapping * Slots)
Definition at line 123 of file LLParser.cpp.
References llvm::SMLoc::getPointer(), and llvm::Read.
Referenced by llvm::parseDIExpressionBodyAtBeginning().
parseMDField() [1/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, ChecksumKindField & Result)
Definition at line 5371 of file LLParser.cpp.
References llvm::lltok::ChecksumKind, and llvm::DIFile::getChecksumKind().
parseMDField() [2/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, ColumnField & Result)
Definition at line 4947 of file LLParser.cpp.
parseMDField() [3/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DIFlagField & Result)
DIFlagField ::= uint32 ::= DIFlagVector ::= DIFlagVector '|' DIFlagFwdDecl '|' uint32 '|' DIFlagPublic.
Definition at line 5163 of file LLParser.cpp.
References llvm::lltok::APSInt, llvm::lltok::bar, llvm::lltok::DIFlag, and llvm::DINode::getFlag().
parseMDField() [4/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DISPFlagField & Result)
DISPFlagField ::= uint32 ::= DISPFlagVector ::= DISPFlagVector '|' DISPFlag* '|' uint32.
Definition at line 5203 of file LLParser.cpp.
References llvm::lltok::APSInt, llvm::lltok::bar, llvm::lltok::DISPFlag, and llvm::DISubprogram::getFlag().
parseMDField() [5/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfAttEncodingField & Result)
Definition at line 5140 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfAttEncoding, and llvm::dwarf::getAttributeEncoding().
parseMDField() [6/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfCCField & Result)
Definition at line 5065 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfCC, and llvm::dwarf::getCallingConvention().
parseMDField() [7/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfEnumKindField & Result)
Definition at line 5009 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::dwarf::DW_APPLE_ENUM_KIND_invalid, llvm::lltok::DwarfEnumKind, and llvm::dwarf::getEnumKind().
parseMDField() [8/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfLangField & Result)
Definition at line 5028 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfLang, and llvm::dwarf::getLanguage().
parseMDField() [9/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfMacinfoTypeField & Result)
Definition at line 4970 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::dwarf::DW_MACINFO_invalid, llvm::lltok::DwarfMacinfo, and llvm::dwarf::getMacinfo().
parseMDField() [10/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfSourceLangNameField & Result)
Definition at line 5046 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::DwarfSourceLangName, and llvm::dwarf::getSourceLanguageName().
parseMDField() [11/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfTagField & Result)
Definition at line 4952 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::dwarf::DW_TAG_invalid, llvm::lltok::DwarfTag, and llvm::dwarf::getTag().
parseMDField() [12/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, DwarfVirtualityField & Result)
Definition at line 4990 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::dwarf::DW_VIRTUALITY_invalid, llvm::lltok::DwarfVirtuality, and llvm::dwarf::getVirtuality().
parseMDField() [13/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, EmissionKindField & Result)
Definition at line 5083 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::EmissionKind, and llvm::DICompileUnit::getEmissionKind().
parseMDField() [14/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, FixedPointKindField & Result)
Definition at line 5102 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::lltok::FixedPointKind, and llvm::DIFixedPointType::getFixedPointKind().
parseMDField() [15/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, LineField & Result)
Definition at line 4943 of file LLParser.cpp.
parseMDField() [16/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDAPSIntField & Result)
Definition at line 4917 of file LLParser.cpp.
References llvm::lltok::APSInt.
parseMDField() [17/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDBoolField & Result)
Definition at line 5258 of file LLParser.cpp.
References llvm::lltok::kw_false, and llvm::lltok::kw_true.
parseMDField() [18/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDField & Result)
Definition at line 5274 of file LLParser.cpp.
References llvm::lltok::kw_null.
parseMDField() [19/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDFieldList & Result)
Definition at line 5361 of file LLParser.cpp.
parseMDField() [20/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDSignedField & Result)
Definition at line 5239 of file LLParser.cpp.
References llvm::lltok::APSInt, and assert().
parseMDField() [21/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDSignedOrMDField & Result)
Definition at line 5292 of file LLParser.cpp.
References llvm::lltok::APSInt.
parseMDField() [22/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDStringField & Result)
Definition at line 5338 of file LLParser.cpp.
References error, and llvm::MDString::get().
parseMDField() [23/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDUnsignedField & Result)
Definition at line 4927 of file LLParser.cpp.
References llvm::lltok::APSInt, and assert().
parseMDField() [24/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, MDUnsignedOrMDField & Result)
Definition at line 5315 of file LLParser.cpp.
References llvm::lltok::APSInt.
parseMDField() [25/25]
template<> bool llvm::LLParser::parseMDField (LocTy Loc, StringRef Name, NameTableKindField & Result)
Definition at line 5121 of file LLParser.cpp.
References llvm::lltok::APSInt, assert(), llvm::DICompileUnit::getNameTableKind(), and llvm::lltok::NameTableKind.
parseStandaloneConstantValue()
bool LLParser::parseStandaloneConstantValue (Constant *& C, const SlotMapping * Slots)
Definition at line 94 of file LLParser.cpp.
References llvm::CallingConv::C, llvm::lltok::Eof, and error.
Referenced by llvm::parseConstantValue().
parseTypeAtBeginning()
bool LLParser::parseTypeAtBeginning (Type *& Ty, unsigned & Read, const SlotMapping * Slots)
Definition at line 107 of file LLParser.cpp.
References llvm::SMLoc::getPointer(), and llvm::Read.
Referenced by llvm::parseTypeAtBeginning().
Run()
bool LLParser::Run (bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback = [](StringRef, StringRef) { return std::nullopt; })
Run: module ::= toplevelentity*.
Definition at line 75 of file LLParser.cpp.
References error.
Referenced by parseAssemblyInto(), and parseSummaryIndexAssemblyInto().
The documentation for this class was generated from the following files:
include/llvm/AsmParser/LLParser.h
lib/AsmParser/LLParser.cpp