LLVM: llvm::SelectionDAG Class Reference
llvm::SelectionDAG Class Reference
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
#include "llvm/CodeGen/SelectionDAG.h"
Classes
struct DAGUpdateListener
Clients of various APIs that cause global effects on the DAG can optionally implement this interface.
struct DAGNodeDeletedListener
struct DAGNodeInsertedListener
class FlagInserter
Help to insert SDNodeFlags automatically in transforming.
Public Types
enum OverflowKind { OFK_Never , OFK_Sometime , OFK_Always }
Used to represent the possible overflow behavior of an operation.
using allnodes_const_iterator = ilist<SDNode>::const_iterator
using allnodes_iterator = ilist<SDNode>::iterator
Public Member Functions
LLVM_ABI SelectionDAG (const TargetMachine &TM, CodeGenOptLevel)
SelectionDAG (const SelectionDAG &)=delete
SelectionDAG & operator= (const SelectionDAG &)=delete
LLVM_ABI ~SelectionDAG ()
LLVM_ABI void init (MachineFunction &NewMF, OptimizationRemarkEmitter &NewORE, Pass *PassPtr, const TargetLibraryInfo *LibraryInfo, UniformityInfo *UA, ProfileSummaryInfo *PSIin, BlockFrequencyInfo *BFIin, MachineModuleInfo &MMI, FunctionVarLocs const *FnVarLocs)
Prepare this SelectionDAG to process code in the given MachineFunction.
void init (MachineFunction &NewMF, OptimizationRemarkEmitter &NewORE, MachineFunctionAnalysisManager &AM, const TargetLibraryInfo *LibraryInfo, UniformityInfo *UA, ProfileSummaryInfo *PSIin, BlockFrequencyInfo *BFIin, MachineModuleInfo &MMI, FunctionVarLocs const *FnVarLocs)
void setFunctionLoweringInfo (FunctionLoweringInfo *FuncInfo)
LLVM_ABI void clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
MachineFunction & getMachineFunction () const
const Pass * getPass () const
MachineFunctionAnalysisManager * getMFAM ()
CodeGenOptLevel getOptLevel () const
const DataLayout & getDataLayout () const
const TargetMachine & getTarget () const
const TargetSubtargetInfo & getSubtarget () const
template<typename STC>
const STC & getSubtarget () const
const TargetLowering & getTargetLoweringInfo () const
const TargetLibraryInfo & getLibInfo () const
const SelectionDAGTargetInfo & getSelectionDAGInfo () const
const UniformityInfo * getUniformityInfo () const
const FunctionVarLocs * getFunctionVarLocs () const
Returns the result of the AssignmentTrackingAnalysis pass if it's available, otherwise return nullptr.
LLVMContext * getContext () const
OptimizationRemarkEmitter & getORE () const
ProfileSummaryInfo * getPSI () const
BlockFrequencyInfo * getBFI () const
MachineModuleInfo * getMMI () const
FlagInserter * getFlagInserter ()
void setFlagInserter (FlagInserter *FI)
LLVM_DUMP_METHOD void dumpDotGraph (const Twine &FileName, const Twine &Title)
Just dump dot graph to a user-provided path and title.
LLVM_ABI void viewGraph (const std::string &Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
LLVM_ABI void viewGraph ()
LLVM_ABI void clearGraphAttrs ()
Clear all previously defined node graph attributes.
LLVM_ABI void setGraphAttrs (const SDNode *N, const char *Attrs)
Set graph attributes for a node. (eg. "color=red".).
LLVM_ABI std::string getGraphAttrs (const SDNode *N) const
Get graph attributes for a node.
LLVM_ABI void setGraphColor (const SDNode *N, const char *Color)
Convenience for setting node color attribute.
LLVM_ABI void setSubgraphColor (SDNode *N, const char *Color)
Convenience for setting subgraph color attribute.
allnodes_const_iterator allnodes_begin () const
allnodes_const_iterator allnodes_end () const
allnodes_iterator allnodes_begin ()
allnodes_iterator allnodes_end ()
ilist< SDNode >::size_type allnodes_size () const
iterator_range< allnodes_iterator > allnodes ()
iterator_range< allnodes_const_iterator > allnodes () const
const SDValue & getRoot () const
Return the root tag of the SelectionDAG.
SDValue getEntryNode () const
Return the token chain corresponding to the entry of the function.
const SDValue & setRoot (SDValue N)
Set the current root tag of the SelectionDAG.
LLVM_ABI void Combine (CombineLevel Level, BatchAAResults *BatchAA, CodeGenOptLevel OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
LLVM_ABI bool LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
LLVM_ABI void Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
LLVM_ABI bool LegalizeOp (SDNode *N, SmallSetVector< SDNode *, 16 > &UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
LLVM_ABI bool LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
LLVM_ABI void RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
LLVM_ABI void DeleteNode (SDNode *N)
Remove the specified node from the system.
LLVM_ABI SDVTList getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
LLVM_ABI SDVTList getVTList (EVT VT1, EVT VT2)
LLVM_ABI SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3)
LLVM_ABI SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
LLVM_ABI SDVTList getVTList (ArrayRef< EVT > VTs)
LLVM_ABI SDValue getGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, bool isTargetGA=false, unsigned TargetFlags=0)
SDValue getTargetGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, unsigned TargetFlags=0)
LLVM_ABI SDValue getDeactivationSymbol (const GlobalValue *GV)
LLVM_ABI SDValue getFrameIndex (int FI, EVT VT, bool isTarget=false)
SDValue getTargetFrameIndex (int FI, EVT VT)
LLVM_ABI SDValue getJumpTable (int JTI, EVT VT, bool isTarget=false, unsigned TargetFlags=0)
SDValue getTargetJumpTable (int JTI, EVT VT, unsigned TargetFlags=0)
LLVM_ABI SDValue getJumpTableDebugInfo (int JTI, SDValue Chain, const SDLoc &DL)
LLVM_ABI SDValue getConstantPool (const Constant *C, EVT VT, MaybeAlign Align=std::nullopt, int Offs=0, bool isT=false, unsigned TargetFlags=0)
SDValue getTargetConstantPool (const Constant *C, EVT VT, MaybeAlign Align=std::nullopt, int Offset=0, unsigned TargetFlags=0)
LLVM_ABI SDValue getConstantPool (MachineConstantPoolValue *C, EVT VT, MaybeAlign Align=std::nullopt, int Offs=0, bool isT=false, unsigned TargetFlags=0)
SDValue getTargetConstantPool (MachineConstantPoolValue *C, EVT VT, MaybeAlign Align=std::nullopt, int Offset=0, unsigned TargetFlags=0)
LLVM_ABI SDValue getBasicBlock (MachineBasicBlock *MBB)
LLVM_ABI SDValue getExternalSymbol (const char *Sym, EVT VT)
LLVM_ABI SDValue getExternalSymbol (RTLIB::LibcallImpl LCImpl, EVT VT)
LLVM_ABI SDValue getTargetExternalSymbol (const char *Sym, EVT VT, unsigned TargetFlags=0)
LLVM_ABI SDValue getTargetExternalSymbol (RTLIB::LibcallImpl LCImpl, EVT VT, unsigned TargetFlags=0)
LLVM_ABI SDValue getMCSymbol (MCSymbol *Sym, EVT VT)
LLVM_ABI SDValue getValueType (EVT)
LLVM_ABI SDValue getRegister (Register Reg, EVT VT)
LLVM_ABI SDValue getRegisterMask (const uint32_t *RegMask)
LLVM_ABI SDValue getEHLabel (const SDLoc &dl, SDValue Root, MCSymbol *Label)
LLVM_ABI SDValue getLabelNode (unsigned Opcode, const SDLoc &dl, SDValue Root, MCSymbol *Label)
LLVM_ABI SDValue getBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, bool isTarget=false, unsigned TargetFlags=0)
SDValue getTargetBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, unsigned TargetFlags=0)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, Register Reg, SDValue N)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, Register Reg, SDValue N, SDValue Glue)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, SDValue Reg, SDValue N, SDValue Glue)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, Register Reg, EVT VT)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, Register Reg, EVT VT, SDValue Glue)
LLVM_ABI SDValue getCondCode (ISD::CondCode Cond)
LLVM_ABI SDValue getVectorShuffle (EVT VT, const SDLoc &dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDValue > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDUse > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getSplatBuildVector (EVT VT, const SDLoc &DL, SDValue Op)
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
SDValue getSplatVector (EVT VT, const SDLoc &DL, SDValue Op)
SDValue getSplat (EVT VT, const SDLoc &DL, SDValue Op)
Returns a node representing a splat of one value into all lanes of the provided vector type.
LLVM_ABI SDValue getStepVector (const SDLoc &DL, EVT ResVT, const APInt &StepVal)
Returns a vector of type ResVT whose elements contain the linear sequence <0, Step, Step * 2, Step * 3, ...>.
LLVM_ABI SDValue getStepVector (const SDLoc &DL, EVT ResVT)
Returns a vector of type ResVT whose elements contain the linear sequence <0, 1, 2, 3, ...>.
LLVM_ABI SDValue getCommutedVectorShuffle (const ShuffleVectorSDNode &SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
SDValue getExtractVectorElt (const SDLoc &DL, EVT VT, SDValue Vec, unsigned Idx)
Extract element at Idx from Vec.
SDValue getInsertVectorElt (const SDLoc &DL, SDValue Vec, SDValue Elt, unsigned Idx)
Insert Elt into Vec at offset Idx.
SDValue getInsertSubvector (const SDLoc &DL, SDValue Vec, SDValue SubVec, unsigned Idx)
Insert SubVec at the Idx element of Vec.
SDValue getExtractSubvector (const SDLoc &DL, EVT VT, SDValue Vec, unsigned Idx)
Return the VT typed sub-vector of Vec at Idx.
LLVM_ABI SDValue getFPExtendOrRound (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
LLVM_ABI std::pair< SDValue, SDValue > getStrictFPExtendOrRound (SDValue Op, SDValue Chain, const SDLoc &DL, EVT VT)
Convert Op, which must be a STRICT operation of float type, to the float type VT, by either extending or rounding (by truncation).
LLVM_ABI SDValue getAnyExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
LLVM_ABI SDValue getSExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
LLVM_ABI SDValue getZExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
SDValue getExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT, unsigned Opcode)
Convert Op, which must be of integer type, to the integer type VT, by either any/sign/zero-extending (depending on IsAny / IsSigned) or truncating it.
SDValue getExtOrTrunc (bool IsSigned, SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign/zero-extending (depending on IsSigned) or truncating it.
LLVM_ABI SDValue getBitcastedAnyExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by first bitcasting (from potential vector) to corresponding scalar type then either any-extending or truncating it.
LLVM_ABI SDValue getBitcastedSExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by first bitcasting (from potential vector) to corresponding scalar type then either sign-extending or truncating it.
LLVM_ABI SDValue getBitcastedZExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by first bitcasting (from potential vector) to corresponding scalar type then either zero-extending or truncating it.
LLVM_ABI SDValue getZeroExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
LLVM_ABI SDValue getVPZeroExtendInReg (SDValue Op, SDValue Mask, SDValue EVL, const SDLoc &DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
LLVM_ABI SDValue getPtrExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
LLVM_ABI SDValue getPtrExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
LLVM_ABI SDValue getBoolExtOrTrunc (SDValue Op, const SDLoc &SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
LLVM_ABI SDValue getNegative (SDValue Val, const SDLoc &DL, EVT VT)
Create negative operation as (SUB 0, Val).
LLVM_ABI SDValue getNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
LLVM_ABI SDValue getLogicalNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
LLVM_ABI SDValue getVPLogicalNOT (const SDLoc &DL, SDValue Val, SDValue Mask, SDValue EVL, EVT VT)
Create a vector-predicated logical NOT operation as (VP_XOR Val, BooleanOne, Mask, EVL).
LLVM_ABI SDValue getVPZExtOrTrunc (const SDLoc &DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be an integer vector, to the vector-type VT, by performing either vector-predicated zext or truncating it.
LLVM_ABI SDValue getVPPtrExtOrTrunc (const SDLoc &DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be of integer type, to the vector-type integer type VT, by either truncating it or performing either vector-predicated zero or sign extension as appropriate extension for the pointer's semantics.
LLVM_ABI SDValue getMemBasePlusOffset (SDValue Base, TypeSize Offset, const SDLoc &DL, const SDNodeFlags Flags=SDNodeFlags())
Returns sum of the base pointer and offset.
LLVM_ABI SDValue getMemBasePlusOffset (SDValue Base, SDValue Offset, const SDLoc &DL, const SDNodeFlags Flags=SDNodeFlags())
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Ptr, TypeSize Offset)
Create an add instruction with appropriate flags when used for addressing some offset of an object.
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Ptr, SDValue Offset)
SDValue getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc &DL)
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
SDValue getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc &DL)
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
SDValue getCALLSEQ_END (SDValue Chain, uint64_t Size1, uint64_t Size2, SDValue Glue, const SDLoc &DL)
LLVM_ABI bool isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
SDValue getUNDEF (EVT VT)
Return an UNDEF node. UNDEF does not have a useful SDLoc.
SDValue getPOISON (EVT VT)
Return a POISON node. POISON does not have a useful SDLoc.
LLVM_ABI SDValue getVScale (const SDLoc &DL, EVT VT, APInt MulImm)
Return a node that represents the runtime scaling 'MulImm * RuntimeVL'.
LLVM_ABI SDValue getElementCount (const SDLoc &DL, EVT VT, ElementCount EC)
LLVM_ABI SDValue getTypeSize (const SDLoc &DL, EVT VT, TypeSize TS)
LLVM_ABI SDValue getMaskFromElementCount (const SDLoc &DL, EVT VT, ElementCount Len)
Return a vector with the first 'Len' lanes set to true and remaining lanes set to false.
SDValue getGLOBAL_OFFSET_TABLE (EVT VT)
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, ArrayRef< SDValue > Ops)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT)
Gets or creates the specified node.
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5, const SDNodeFlags Flags)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
LLVM_ABI SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
LLVM_ABI SDValue getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
LLVM_ABI std::pair< SDValue, SDValue > getMemcmp (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, const CallInst *CI)
Lower a memcmp operation into a target library call and return the resulting chain and call result as SelectionDAG SDValues.
LLVM_ABI std::pair< SDValue, SDValue > getStrcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, const CallInst *CI)
Lower a strcpy operation into a target library call and return the resulting chain and call result as SelectionDAG SDValues.
LLVM_ABI std::pair< SDValue, SDValue > getStrlen (SDValue Chain, const SDLoc &dl, SDValue Src, const CallInst *CI)
Lower a strlen operation into a target library call and return the resulting chain and call result as SelectionDAG SDValues.
LLVM_ABI SDValue getMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, const CallInst *CI, std::optional< bool > OverrideTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes &AAInfo=AAMDNodes(), BatchAAResults *BatchAA=nullptr)
LLVM_ABI SDValue getMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, const CallInst *CI, std::optional< bool > OverrideTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes &AAInfo=AAMDNodes(), BatchAAResults *BatchAA=nullptr)
LLVM_ABI SDValue getMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, const CallInst *CI, MachinePointerInfo DstPtrInfo, const AAMDNodes &AAInfo=AAMDNodes())
LLVM_ABI SDValue getAtomicMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
LLVM_ABI SDValue getAtomicMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
LLVM_ABI SDValue getAtomicMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Value, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
SDValue getSetCC (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Chain=SDValue(), bool IsSignaling=false)
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
SDValue getSetCCVP (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Mask, SDValue EVL)
Helper function to make it easier to build VP_SETCCs if you just have an ISD::CondCode instead of an SDValue.
SDValue getSelect (const SDLoc &DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS, SDNodeFlags Flags=SDNodeFlags())
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
SDValue getSelectCC (const SDLoc &DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond, SDNodeFlags Flags=SDNodeFlags())
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
LLVM_ABI SDValue simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
LLVM_ABI SDValue simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
LLVM_ABI SDValue simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y, SDNodeFlags Flags)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
LLVM_ABI SDValue getVAArg (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
LLVM_ABI SDValue getAtomicCmpSwap (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand *MMO)
Gets a node for an atomic cmpxchg op.
LLVM_ABI SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
LLVM_ABI SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::LoadExtType ExtType=ISD::NON_EXTLOAD)
Gets a node for an atomic op, produces result and chain and takes N operands.
LLVM_ABI SDValue getAtomicLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO)
LLVM_ABI SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, LocationSize Size=LocationSize::precise(0), const AAMDNodes &AAInfo=AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, MaybeAlign Alignment=std::nullopt, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, LocationSize Size=LocationSize::precise(0), const AAMDNodes &AAInfo=AAMDNodes())
LLVM_ABI SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand *MMO)
LLVM_ABI SDValue getLifetimeNode (bool IsStart, const SDLoc &dl, SDValue Chain, int FrameIndex)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the FrameIndex.
LLVM_ABI SDValue getPseudoProbeNode (const SDLoc &Dl, SDValue Chain, uint64_t Guid, uint64_t Index, uint32_t Attr)
Creates a PseudoProbeSDNode with function GUID Guid and the index of the block Index it is probing, as well as the attributes attr of the probe.
LLVM_ABI SDValue getMergeValues (ArrayRef< SDValue > Ops, const SDLoc &dl)
Create a MERGE_VALUES node from the given operands.
LLVM_ABI SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
LLVM_ABI SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO)
LLVM_ABI SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
LLVM_ABI SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand *MMO)
LLVM_ABI SDValue getIndexedLoad (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
LLVM_ABI SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
LLVM_ABI SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand *MMO)
LLVM_ABI SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
Helper function to build ISD::STORE nodes.
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
LLVM_ABI SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachineMemOperand *MMO)
LLVM_ABI SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
LLVM_ABI SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand *MMO)
LLVM_ABI SDValue getIndexedStore (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
LLVM_ABI SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Offset, EVT SVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false)
LLVM_ABI SDValue getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, const MDNode *Ranges=nullptr, bool IsExpanding=false)
SDValue getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr, bool IsExpanding=false)
LLVM_ABI SDValue getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
LLVM_ABI SDValue getLoadVP (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, const MDNode *Ranges=nullptr, bool IsExpanding=false)
LLVM_ABI SDValue getLoadVP (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachineMemOperand *MMO, bool IsExpanding=false)
LLVM_ABI SDValue getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, bool IsExpanding=false)
LLVM_ABI SDValue getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
LLVM_ABI SDValue getIndexedLoadVP (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
LLVM_ABI SDValue getStoreVP (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false, bool IsCompressing=false)
LLVM_ABI SDValue getTruncStoreVP (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, bool IsCompressing=false)
LLVM_ABI SDValue getTruncStoreVP (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand *MMO, bool IsCompressing=false)
LLVM_ABI SDValue getIndexedStoreVP (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
LLVM_ABI SDValue getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
LLVM_ABI SDValue getStridedLoadVP (EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachineMemOperand *MMO, bool IsExpanding=false)
LLVM_ABI SDValue getExtStridedLoadVP (ISD::LoadExtType ExtType, const SDLoc &DL, EVT VT, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
LLVM_ABI SDValue getStridedStoreVP (SDValue Chain, const SDLoc &DL, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false, bool IsCompressing=false)
LLVM_ABI SDValue getTruncStridedStoreVP (SDValue Chain, const SDLoc &DL, SDValue Val, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand *MMO, bool IsCompressing=false)
LLVM_ABI SDValue getGatherVP (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType)
LLVM_ABI SDValue getScatterVP (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType)
LLVM_ABI SDValue getMaskedLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Base, SDValue Offset, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, ISD::LoadExtType, bool IsExpanding=false)
LLVM_ABI SDValue getIndexedMaskedLoad (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
LLVM_ABI SDValue getMaskedStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Base, SDValue Offset, SDValue Mask, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false, bool IsCompressing=false)
LLVM_ABI SDValue getIndexedMaskedStore (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
LLVM_ABI SDValue getMaskedGather (SDVTList VTs, EVT MemVT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType, ISD::LoadExtType ExtTy)
LLVM_ABI SDValue getMaskedScatter (SDVTList VTs, EVT MemVT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType, bool IsTruncating=false)
LLVM_ABI SDValue getMaskedHistogram (SDVTList VTs, EVT MemVT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType)
LLVM_ABI SDValue getLoadFFVP (EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachineMemOperand *MMO)
LLVM_ABI SDValue getGetFPEnv (SDValue Chain, const SDLoc &dl, SDValue Ptr, EVT MemVT, MachineMemOperand *MMO)
LLVM_ABI SDValue getSetFPEnv (SDValue Chain, const SDLoc &dl, SDValue Ptr, EVT MemVT, MachineMemOperand *MMO)
LLVM_ABI SDValue getSrcValue (const Value *v)
Construct a node to track a Value* through the backend.
LLVM_ABI SDValue getMDNode (const MDNode *MD)
Return an MDNodeSDNode which holds an MDNode.
LLVM_ABI SDValue getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
LLVM_ABI SDValue getAddrSpaceCast (const SDLoc &dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
LLVM_ABI SDValue getFreeze (SDValue V)
Return a freeze using the SDLoc of the value operand.
LLVM_ABI SDValue getFreeze (SDValue V, const APInt &DemandedElts, bool PoisonOnly=false)
Return a freeze of V if any of the demanded elts may be undef or poison.
LLVM_ABI SDValue getAssertAlign (const SDLoc &DL, SDValue V, Align A)
Return an AssertAlignSDNode.
LLVM_ABI void canonicalizeCommutativeBinop (unsigned Opcode, SDValue &N1, SDValue &N2) const
Swap N1 and N2 if Opcode is a commutative binary opcode and the canonical form expects the opposite order.
LLVM_ABI SDValue getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
LLVM_ABI SDValue expandVAArg (SDNode *Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
LLVM_ABI SDValue expandVACopy (SDNode *Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
LLVM_ABI SDValue getSymbolFunctionGlobalAddress (SDValue Op, Function **TargetFunction=nullptr)
Return a GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
LLVM_ABI SDNode * UpdateNodeOperands (SDNode *N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
LLVM_ABI SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2)
LLVM_ABI SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3)
LLVM_ABI SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
LLVM_ABI SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
LLVM_ABI SDNode * UpdateNodeOperands (SDNode *N, ArrayRef< SDValue > Ops)
LLVM_ABI SDValue getTokenFactor (const SDLoc &DL, SmallVectorImpl< SDValue > &Vals)
Creates a new TokenFactor containing Vals.
LLVM_ABI void setNodeMemRefs (MachineSDNode *N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
LLVM_ABI bool calculateDivergence (SDNode *N)
LLVM_ABI void updateDivergence (SDNode *N)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
LLVM_ABI SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
LLVM_ABI SDNode * MorphNodeTo (SDNode *N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
LLVM_ABI SDNode * mutateStrictFPToFP (SDNode *Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, ArrayRef< SDValue > Ops)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
LLVM_ABI MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, SDVTList VTs, ArrayRef< SDValue > Ops)
LLVM_ABI SDValue getTargetExtractSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
LLVM_ABI SDValue getTargetInsertSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
LLVM_ABI SDNode * getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags, bool AllowCommute=false)
Get the specified node if it's already available, or else return NULL.
LLVM_ABI SDNode * getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, bool AllowCommute=false)
getNodeIfExists - Get the specified node if it's already available, or else return NULL.
LLVM_ABI bool doesNodeExist (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
Check if a node exists without modifying its flags.
LLVM_ABI SDDbgValue * getDbgValue (DIVariable *Var, DIExpression *Expr, SDNode *N, unsigned R, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a SDDbgValue node.
LLVM_ABI SDDbgValue * getConstantDbgValue (DIVariable *Var, DIExpression *Expr, const Value *C, const DebugLoc &DL, unsigned O)
Creates a constant SDDbgValue node.
LLVM_ABI SDDbgValue * getFrameIndexDbgValue (DIVariable *Var, DIExpression *Expr, unsigned FI, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
LLVM_ABI SDDbgValue * getFrameIndexDbgValue (DIVariable *Var, DIExpression *Expr, unsigned FI, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
LLVM_ABI SDDbgValue * getVRegDbgValue (DIVariable *Var, DIExpression *Expr, Register VReg, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a VReg SDDbgValue node.
LLVM_ABI SDDbgValue * getDbgValueList (DIVariable *Var, DIExpression *Expr, ArrayRef< SDDbgOperand > Locs, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc &DL, unsigned O, bool IsVariadic)
Creates a SDDbgValue node from a list of locations.
LLVM_ABI SDDbgLabel * getDbgLabel (DILabel *Label, const DebugLoc &DL, unsigned O)
Creates a SDDbgLabel node.
LLVM_ABI void transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits=0, unsigned SizeInBits=0, bool InvalidateDbg=true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
LLVM_ABI void RemoveDeadNode (SDNode *N)
Remove the specified node from the system.
LLVM_ABI void RemoveDeadNodes (SmallVectorImpl< SDNode * > &DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
LLVM_ABI void ReplaceAllUsesWith (SDValue From, SDValue To)
Modify anything using 'From' to use 'To' instead.
LLVM_ABI void ReplaceAllUsesWith (SDNode *From, SDNode *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
LLVM_ABI void ReplaceAllUsesWith (SDNode *From, const SDValue *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
LLVM_ABI void ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
LLVM_ABI void ReplaceAllUsesOfValuesWith (const SDValue *From, const SDValue *To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
LLVM_ABI SDValue makeEquivalentMemoryOrdering (SDValue OldChain, SDValue NewMemOpChain)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
LLVM_ABI SDValue makeEquivalentMemoryOrdering (LoadSDNode *OldLoad, SDValue NewMemOp)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
LLVM_ABI void getTopologicallyOrderedNodes (SmallVectorImpl< const SDNode * > &SortedNodes) const
Get all the nodes in their topological order without modifying any states.
LLVM_ABI unsigned AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
void RepositionNode (allnodes_iterator Position, SDNode *N)
Move node N in the AllNodes list to be immediately before the given iterator Position.
LLVM_ABI void AddDbgValue (SDDbgValue *DB, bool isParameter)
Add a dbg_value SDNode.
LLVM_ABI void AddDbgLabel (SDDbgLabel *DB)
Add a dbg_label SDNode.
ArrayRef< SDDbgValue * > GetDbgValues (const SDNode *SD) const
Get the debug values which reference the given SDNode.
bool hasDebugValues () const
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
SDDbgInfo::DbgIterator DbgBegin () const
SDDbgInfo::DbgIterator DbgEnd () const
SDDbgInfo::DbgIterator ByvalParmDbgBegin () const
SDDbgInfo::DbgIterator ByvalParmDbgEnd () const
SDDbgInfo::DbgLabelIterator DbgLabelBegin () const
SDDbgInfo::DbgLabelIterator DbgLabelEnd () const
LLVM_ABI void salvageDebugInfo (SDNode &N)
To be invoked on an SDNode that is slated to be erased.
LLVM_ABI void dump (bool Sorted=false) const
Dump the textual format of this DAG.
LLVM_ABI Align getReducedAlign (EVT VT, bool UseABI)
In most cases this function returns the ABI alignment for a given type, except for illegal vector types where the alignment exceeds that of the stack.
LLVM_ABI SDValue CreateStackTemporary (TypeSize Bytes, Align Alignment)
Create a stack temporary based on the size in bytes and the alignment.
LLVM_ABI SDValue CreateStackTemporary (EVT VT, unsigned minAlign=1)
Create a stack temporary, suitable for holding the specified value type.
LLVM_ABI SDValue CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
LLVM_ABI SDValue FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode *GA, const SDNode *N2)
LLVM_ABI SDValue FoldConstantArithmetic (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, SDNodeFlags Flags=SDNodeFlags())
LLVM_ABI SDValue foldConstantFPMath (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops)
Fold floating-point operations when all operands are constants and/or undefined.
LLVM_ABI SDValue FoldConstantBuildVector (BuildVectorSDNode *BV, const SDLoc &DL, EVT DstEltVT)
Fold BUILD_VECTOR of constants/undefs to the destination type BUILD_VECTOR of constants/undefs elements.
LLVM_ABI SDValue FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc &dl)
Constant fold a setcc to true or false.
LLVM_ABI bool SignBitIsZero (SDValue Op, unsigned Depth=0) const
Return true if the sign bit of Op is known to be zero.
LLVM_ABI bool SignBitIsZeroFP (SDValue Op, unsigned Depth=0) const
Return true if the sign bit of Op is known to be zero, for a floating-point value.
LLVM_ABI bool MaskedValueIsZero (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero.
LLVM_ABI bool MaskedValueIsZero (SDValue Op, const APInt &Mask, const APInt &DemandedElts, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
LLVM_ABI bool MaskedVectorIsZero (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return true if 'Op' is known to be zero in DemandedElts.
LLVM_ABI bool MaskedValueIsAllOnes (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if '(Op & Mask) == Mask'.
LLVM_ABI APInt computeVectorKnownZeroElements (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
For each demanded element of a vector, see if it is known to be zero.
LLVM_ABI KnownBits computeKnownBits (SDValue Op, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
LLVM_ABI KnownBits computeKnownBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
LLVM_ABI OverflowKind computeOverflowForSignedAdd (SDValue N0, SDValue N1) const
Determine if the result of the signed addition of 2 nodes can overflow.
LLVM_ABI OverflowKind computeOverflowForUnsignedAdd (SDValue N0, SDValue N1) const
Determine if the result of the unsigned addition of 2 nodes can overflow.
OverflowKind computeOverflowForAdd (bool IsSigned, SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 nodes can overflow.
bool willNotOverflowAdd (bool IsSigned, SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 nodes can never overflow.
LLVM_ABI OverflowKind computeOverflowForSignedSub (SDValue N0, SDValue N1) const
Determine if the result of the signed sub of 2 nodes can overflow.
LLVM_ABI OverflowKind computeOverflowForUnsignedSub (SDValue N0, SDValue N1) const
Determine if the result of the unsigned sub of 2 nodes can overflow.
OverflowKind computeOverflowForSub (bool IsSigned, SDValue N0, SDValue N1) const
Determine if the result of the sub of 2 nodes can overflow.
bool willNotOverflowSub (bool IsSigned, SDValue N0, SDValue N1) const
Determine if the result of the sub of 2 nodes can never overflow.
LLVM_ABI OverflowKind computeOverflowForSignedMul (SDValue N0, SDValue N1) const
Determine if the result of the signed mul of 2 nodes can overflow.
LLVM_ABI OverflowKind computeOverflowForUnsignedMul (SDValue N0, SDValue N1) const
Determine if the result of the unsigned mul of 2 nodes can overflow.
OverflowKind computeOverflowForMul (bool IsSigned, SDValue N0, SDValue N1) const
Determine if the result of the mul of 2 nodes can overflow.
bool willNotOverflowMul (bool IsSigned, SDValue N0, SDValue N1) const
Determine if the result of the mul of 2 nodes can never overflow.
LLVM_ABI bool isKnownToBeAPowerOfTwo (SDValue Val, unsigned Depth=0) const
Test if the given value is known to have exactly one bit set.
LLVM_ABI bool isKnownToBeAPowerOfTwoFP (SDValue Val, unsigned Depth=0) const
Test if the given fp value is known to be an integer power-of-2, either positive or negative.
LLVM_ABI unsigned ComputeNumSignBits (SDValue Op, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
LLVM_ABI unsigned ComputeNumSignBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
LLVM_ABI unsigned ComputeMaxSignificantBits (SDValue Op, unsigned Depth=0) const
Get the upper bound on bit size for this Value Op as a signed integer.
LLVM_ABI unsigned ComputeMaxSignificantBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Get the upper bound on bit size for this Value Op as a signed integer.
LLVM_ABI bool isGuaranteedNotToBeUndefOrPoison (SDValue Op, bool PoisonOnly=false, unsigned Depth=0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
LLVM_ABI bool isGuaranteedNotToBeUndefOrPoison (SDValue Op, const APInt &DemandedElts, bool PoisonOnly=false, unsigned Depth=0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
bool isGuaranteedNotToBePoison (SDValue Op, unsigned Depth=0) const
Return true if this function can prove that Op is never poison.
bool isGuaranteedNotToBePoison (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return true if this function can prove that Op is never poison.
LLVM_ABI bool canCreateUndefOrPoison (SDValue Op, const APInt &DemandedElts, bool PoisonOnly=false, bool ConsiderFlags=true, unsigned Depth=0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
LLVM_ABI bool canCreateUndefOrPoison (SDValue Op, bool PoisonOnly=false, bool ConsiderFlags=true, unsigned Depth=0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
LLVM_ABI bool isADDLike (SDValue Op, bool NoWrap=false) const
Return true if the specified operand is an ISD::OR or ISD::XOR node that can be treated as an ISD::ADD node.
LLVM_ABI bool isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
LLVM_ABI bool isKnownNeverNaN (SDValue Op, const APInt &DemandedElts, bool SNaN=false, unsigned Depth=0) const
Test whether the given SDValue (or all elements of it, if it is a vector) is known to never be NaN in DemandedElts.
LLVM_ABI bool isKnownNeverNaN (SDValue Op, bool SNaN=false, unsigned Depth=0) const
Test whether the given SDValue (or all elements of it, if it is a vector) is known to never be NaN.
bool isKnownNeverSNaN (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
bool isKnownNeverSNaN (SDValue Op, unsigned Depth=0) const
LLVM_ABI bool isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
LLVM_ABI bool isKnownNeverZero (SDValue Op, unsigned Depth=0) const
Test whether the given SDValue is known to contain non-zero value(s).
LLVM_ABI bool cannotBeOrderedNegativeFP (SDValue Op) const
Test whether the given float value is known to be positive.
LLVM_ABI bool canIgnoreSignBitOfZero (const SDUse &Use) const
Check if a use of a float value is insensitive to signed zeros.
LLVM_ABI bool canIgnoreSignBitOfZero (SDValue Op) const
Check if at most two uses of a value are insensitive to signed zeros.
LLVM_ABI bool isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
LLVM_ABI bool haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
LLVM_ABI bool isSplatValue (SDValue V, const APInt &DemandedElts, APInt &UndefElts, unsigned Depth=0) const
Test whether V has a splatted value for all the demanded elements.
LLVM_ABI bool isSplatValue (SDValue V, bool AllowUndefs=false) const
Test whether V has a splatted value.
LLVM_ABI SDValue getSplatSourceVector (SDValue V, int &SplatIndex)
If V is a splatted value, return the source vector and its splat index.
LLVM_ABI SDValue getSplatValue (SDValue V, bool LegalTypes=false)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
LLVM_ABI std::optional< ConstantRange > getValidShiftAmountRange (SDValue V, const APInt &DemandedElts, unsigned Depth) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the valid constant range.
LLVM_ABI std::optional< unsigned > getValidShiftAmount (SDValue V, const APInt &DemandedElts, unsigned Depth=0) const
If a SHL/SRA/SRL node V has a uniform shift amount that is less than the element bit-width of the shift node, return it.
LLVM_ABI std::optional< unsigned > getValidShiftAmount (SDValue V, unsigned Depth=0) const
If a SHL/SRA/SRL node V has a uniform shift amount that is less than the element bit-width of the shift node, return it.
LLVM_ABI std::optional< unsigned > getValidMinimumShiftAmount (SDValue V, const APInt &DemandedElts, unsigned Depth=0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the minimum possible value.
LLVM_ABI std::optional< unsigned > getValidMinimumShiftAmount (SDValue V, unsigned Depth=0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the minimum possible value.
LLVM_ABI std::optional< unsigned > getValidMaximumShiftAmount (SDValue V, const APInt &DemandedElts, unsigned Depth=0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the maximum possible value.
LLVM_ABI std::optional< unsigned > getValidMaximumShiftAmount (SDValue V, unsigned Depth=0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the maximum possible value.
LLVM_ABI SDValue matchBinOpReduction (SDNode *Extract, ISD::NodeType &BinOp, ArrayRef< ISD::NodeType > CandidateBinOps, bool AllowPartials=false)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
LLVM_ABI SDValue UnrollVectorOp (SDNode *N, unsigned ResNE=0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
LLVM_ABI std::pair< SDValue, SDValue > UnrollVectorOverflowOp (SDNode *N, unsigned ResNE=0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
LLVM_ABI bool areNonVolatileConsecutiveLoads (LoadSDNode *LD, LoadSDNode *Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
LLVM_ABI MaybeAlign InferPtrAlign (SDValue Ptr) const
Infer alignment of a load / store address.
LLVM_ABI std::pair< SDValue, SDValue > SplitScalar (const SDValue &N, const SDLoc &DL, const EVT &LoVT, const EVT &HiVT)
Split the scalar node with EXTRACT_ELEMENT using the provided VTs and return the low/high part.
LLVM_ABI std::pair< EVT, EVT > GetSplitDestVTs (const EVT &VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
LLVM_ABI std::pair< EVT, EVT > GetDependentSplitDestVTs (const EVT &VT, const EVT &EnvVT, bool *HiIsEmpty) const
Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
LLVM_ABI std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL, const EVT &LoVT, const EVT &HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provided VTs and return the low/high part.
std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL)
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
LLVM_ABI std::pair< SDValue, SDValue > SplitEVL (SDValue N, EVT VecVT, const SDLoc &DL)
Split the explicit vector length parameter of a VP operation.
std::pair< SDValue, SDValue > SplitVectorOperand (const SDNode *N, unsigned OpNo)
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
LLVM_ABI SDValue WidenVector (const SDValue &N, const SDLoc &DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
LLVM_ABI void ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > &Args, unsigned Start=0, unsigned Count=0, EVT EltVT=EVT())
Append the extracted elements from Start to Count out of the vector Op in Args.
LLVM_ABI Align getEVTAlign (EVT MemoryVT) const
Compute the default alignment value for the given type.
LLVM_ABI bool isConstantIntBuildVectorOrConstantInt (SDValue N, bool AllowOpaques=true) const
Test whether the given value is a constant int or similar node.
LLVM_ABI bool isConstantFPBuildVectorOrConstantFP (SDValue N) const
Test whether the given value is a constant FP or similar node.
bool isConstantValueOfAnyType (SDValue N) const
LLVM_ABI std::optional< bool > isBoolConstant (SDValue N) const
Check if a value \op N is a constant using the target's BooleanContent for its type.
void addCallSiteInfo (const SDNode *Node, CallSiteInfo &&CallInfo)
Set CallSiteInfo to be associated with Node.
CallSiteInfo getCallSiteInfo (const SDNode *Node)
Return CallSiteInfo associated with Node, or a default if none exists.
void addHeapAllocSite (const SDNode *Node, MDNode *MD)
Set HeapAllocSite to be associated with Node.
MDNode * getHeapAllocSite (const SDNode *Node) const
Return HeapAllocSite associated with Node, or nullptr if none exists.
void addPCSections (const SDNode *Node, MDNode *MD)
Set PCSections to be associated with Node.
void addMMRAMetadata (const SDNode *Node, MDNode *MMRA)
Set MMRAMetadata to be associated with Node.
MDNode * getPCSections (const SDNode *Node) const
Return PCSections associated with Node, or nullptr if none exists.
MDNode * getMMRAMetadata (const SDNode *Node) const
Return the MMRA MDNode associated with Node, or nullptr if none exists.
void addCalledGlobal (const SDNode *Node, const GlobalValue *GV, unsigned OpFlags)
Set CalledGlobal to be associated with Node.
std::optional< CalledGlobalInfo > getCalledGlobal (const SDNode *Node)
Return CalledGlobal associated with Node, or a nullopt if none exists.
void addNoMergeSiteInfo (const SDNode *Node, bool NoMerge)
Set NoMergeSiteInfo to be associated with Node if NoMerge is true.
bool getNoMergeSiteInfo (const SDNode *Node) const
Return NoMerge info associated with Node.
LLVM_ABI void copyExtraInfo (SDNode *From, SDNode *To)
Copy extra info associated with one node to another.
DenormalMode getDenormalMode (EVT VT) const
Return the current function's default denormal handling kind for the given floating point type.
LLVM_ABI bool shouldOptForSize () const
LLVM_ABI SDValue getNeutralElement (unsigned Opcode, const SDLoc &DL, EVT VT, SDNodeFlags Flags)
Get the (commutative) neutral element for the given opcode, if it exists.
bool isSafeToSpeculativelyExecute (unsigned Opcode) const
Some opcodes may create immediate undefined behavior when used with some values (integer division-by-zero for example).
bool isSafeToSpeculativelyExecuteNode (const SDNode *N) const
Check if the provided node is save to speculatively executed given its current arguments.
LLVM_ABI SDValue makeStateFunctionCall (unsigned LibFunc, SDValue Ptr, SDValue InChain, const SDLoc &DLoc)
Helper used to make a call to a library function that has one argument of pointer type.
LLVM_ABI SDValue getConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
Create a ConstantSDNode wrapping a constant value.
LLVM_ABI SDValue getConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
LLVM_ABI SDValue getSignedConstant (int64_t Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
LLVM_ABI SDValue getAllOnesConstant (const SDLoc &DL, EVT VT, bool IsTarget=false, bool IsOpaque=false)
LLVM_ABI SDValue getConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
LLVM_ABI SDValue getIntPtrConstant (uint64_t Val, const SDLoc &DL, bool isTarget=false)
LLVM_ABI SDValue getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc &DL)
LLVM_ABI SDValue getShiftAmountConstant (const APInt &Val, EVT VT, const SDLoc &DL)
LLVM_ABI SDValue getVectorIdxConstant (uint64_t Val, const SDLoc &DL, bool isTarget=false)
SDValue getTargetConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getSignedTargetConstant (int64_t Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
LLVM_ABI SDValue getBoolConstant (bool V, const SDLoc &DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
LLVM_ABI SDValue getConstantFP (double Val, const SDLoc &DL, EVT VT, bool isTarget=false)
Create a ConstantFPSDNode wrapping a constant value.
LLVM_ABI SDValue getConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT, bool isTarget=false)
LLVM_ABI SDValue getConstantFP (const ConstantFP &V, const SDLoc &DL, EVT VT, bool isTarget=false)
SDValue getTargetConstantFP (double Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const ConstantFP &Val, const SDLoc &DL, EVT VT)
Static Public Member Functions
static LLVM_ABI unsigned getHasPredecessorMaxSteps ()
static unsigned getOpcode_EXTEND (unsigned Opcode)
Convert *_EXTEND_VECTOR_INREG to *_EXTEND opcode.
static unsigned getOpcode_EXTEND_VECTOR_INREG (unsigned Opcode)
Convert *_EXTEND to *_EXTEND_VECTOR_INREG opcode.
Public Attributes
bool NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
Static Public Attributes
static constexpr unsigned MaxRecursionDepth = 6
Friends
struct DAGUpdateListener
DAGUpdateListener is a friend so it can manipulate the listener stack.
Detailed Description
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
This DAG is constructed as the first step of instruction selection in order to allow implementation of machine specific optimizations and code simplifications.
The representation used by the SelectionDAG is a target-independent representation, which has some similarities to the GCC RTL representation, but is significantly more simple, powerful, and is a graph form instead of a linear form.
Definition at line 229 of file SelectionDAG.h.
Member Typedef Documentation
allnodes_const_iterator
using llvm::SelectionDAG::allnodes_const_iterator = ilist<SDNode>::const_iterator
Definition at line 556 of file SelectionDAG.h.
allnodes_iterator
using llvm::SelectionDAG::allnodes_iterator = ilist<SDNode>::iterator
Definition at line 561 of file SelectionDAG.h.
Member Enumeration Documentation
OverflowKind
enum llvm::SelectionDAG::OverflowKind
Used to represent the possible overflow behavior of an operation.
Never: the operation cannot overflow. Always: the operation will always overflow. Sometime: the operation may or may not overflow.
Enumerator
OFK_Never
OFK_Sometime
OFK_Always
Definition at line 2138 of file SelectionDAG.h.
Constructor & Destructor Documentation
SelectionDAG() [1/2]
SelectionDAG::SelectionDAG (const TargetMachine & TM, CodeGenOptLevel OL) explicit
Definition at line 1360 of file SelectionDAG.cpp.
References getEntryNode(), and getVTList().
Referenced by llvm::SelectionDAG::DAGNodeDeletedListener::DAGNodeDeletedListener(), llvm::SelectionDAG::DAGNodeInsertedListener::DAGNodeInsertedListener(), llvm::SelectionDAG::DAGUpdateListener::DAGUpdateListener(), llvm::SelectionDAG::FlagInserter::FlagInserter(), llvm::SelectionDAG::FlagInserter::FlagInserter(), operator=(), and SelectionDAG().
SelectionDAG() [2/2]
llvm::SelectionDAG::SelectionDAG (const SelectionDAG &) delete
References SelectionDAG().
~SelectionDAG()
SelectionDAG::~SelectionDAG ()
Definition at line 1388 of file SelectionDAG.cpp.
References assert().
Member Function Documentation
addCalledGlobal()
void llvm::SelectionDAG::addCalledGlobal (const SDNode * Node, const GlobalValue * GV, unsigned OpFlags) inline
Set CalledGlobal to be associated with Node.
Definition at line 2578 of file SelectionDAG.h.
addCallSiteInfo()
void llvm::SelectionDAG::addCallSiteInfo (const SDNode * Node, CallSiteInfo && CallInfo) inline
Set CallSiteInfo to be associated with Node.
Definition at line 2541 of file SelectionDAG.h.
Referenced by llvm::RISCVTargetLowering::LowerCall().
AddDbgLabel()
void SelectionDAG::AddDbgLabel (SDDbgLabel * DB)
Add a dbg_label SDNode.
Definition at line 12817 of file SelectionDAG.cpp.
AddDbgValue()
void SelectionDAG::AddDbgValue (SDDbgValue * DB, bool isParameter)
Add a dbg_value SDNode.
AddDbgValue - Add a dbg_value SDNode.
If SD is non-null that means the value is produced by SD.
Definition at line 12807 of file SelectionDAG.cpp.
References assert().
Referenced by handleDanglingVariadicDebugInfo(), salvageDebugInfo(), and transferDbgValues().
addHeapAllocSite()
void llvm::SelectionDAG::addHeapAllocSite (const SDNode * Node, MDNode * MD) inline
Set HeapAllocSite to be associated with Node.
Definition at line 2550 of file SelectionDAG.h.
addMMRAMetadata()
void llvm::SelectionDAG::addMMRAMetadata (const SDNode * Node, MDNode * MMRA) inline
Set MMRAMetadata to be associated with Node.
Definition at line 2563 of file SelectionDAG.h.
addNoMergeSiteInfo()
void llvm::SelectionDAG::addNoMergeSiteInfo (const SDNode * Node, bool NoMerge) inline
Set NoMergeSiteInfo to be associated with Node if NoMerge is true.
Definition at line 2590 of file SelectionDAG.h.
Referenced by llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::LowerCall().
addPCSections()
void llvm::SelectionDAG::addPCSections (const SDNode * Node, MDNode * MD) inline
Set PCSections to be associated with Node.
Definition at line 2559 of file SelectionDAG.h.
allnodes() [1/2]
iterator_range< allnodes_iterator > llvm::SelectionDAG::allnodes () inline
Definition at line 570 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
Referenced by AssignTopologicalOrder(), dump(), getTopologicallyOrderedNodes(), and RemoveDeadNodes().
allnodes() [2/2]
iterator_range< allnodes_const_iterator > llvm::SelectionDAG::allnodes () const inline
Definition at line 573 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
allnodes_begin() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_begin () inline
Definition at line 563 of file SelectionDAG.h.
allnodes_begin() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_begin () const inline
Definition at line 558 of file SelectionDAG.h.
Referenced by allnodes(), allnodes(), AssignTopologicalOrder(), and Legalize().
allnodes_end() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_end () inline
Definition at line 564 of file SelectionDAG.h.
allnodes_end() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_end () const inline
Definition at line 559 of file SelectionDAG.h.
Referenced by allnodes(), allnodes(), and Legalize().
allnodes_size()
ilist< SDNode >::size_type llvm::SelectionDAG::allnodes_size () const inline
Definition at line 566 of file SelectionDAG.h.
Referenced by AssignTopologicalOrder().
areNonVolatileConsecutiveLoads()
bool SelectionDAG::areNonVolatileConsecutiveLoads (LoadSDNode * LD, LoadSDNode * Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
Check that both are nonvolatile and if LD is loading 'Bytes' bytes from a location that is 'Dist' units away from the location that the 'Base' load is loading from.
Definition at line 13566 of file SelectionDAG.cpp.
References llvm::sampleprof::Base, llvm::EVT::getSizeInBits(), llvm::BaseIndexOffset::match(), and llvm::Offset.
Referenced by areLoadedOffsetButOtherwiseSame(), combineBVOfConsecutiveLoads(), combineINSERT_SUBVECTOR(), and EltsFromConsecutiveLoads().
AssignTopologicalOrder()
unsigned SelectionDAG::AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
AssignTopologicalOrder - Assign a unique node id for each node in the DAG based on their topological order.
Returns the number of nodes.
It returns the maximum id and a vector of the SDNodes* in assigned order by reference.
Definition at line 12680 of file SelectionDAG.cpp.
References allnodes(), allnodes_begin(), allnodes_size(), assert(), llvm::checkForCycles(), llvm::dbgs(), llvm::SDNode::dumprFull(), llvm::ISD::EntryToken, I, llvm_unreachable, llvm::make_early_inc_range(), N, and P.
Referenced by Legalize().
ByvalParmDbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgBegin () const inline
Definition at line 2022 of file SelectionDAG.h.
Referenced by dump().
ByvalParmDbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgEnd () const inline
Definition at line 2025 of file SelectionDAG.h.
Referenced by dump().
calculateDivergence()
bool SelectionDAG::calculateDivergence (SDNode * N)
Definition at line 12550 of file SelectionDAG.cpp.
References assert(), gluePropagatesDivergence(), and N.
Referenced by updateDivergence().
canCreateUndefOrPoison() [1/2]
bool SelectionDAG::canCreateUndefOrPoison (SDValue Op, bool PoisonOnly = false, bool ConsiderFlags = true, unsigned Depth = 0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
ConsiderFlags controls whether poison producing flags on the instruction are considered. This can be used to see if the instruction could still introduce undef or poison even without poison generating flags which might be on the instruction. (i.e. could the result of Op->dropPoisonGeneratingFlags() still create poison or undef)
Definition at line 5604 of file SelectionDAG.cpp.
References canCreateUndefOrPoison(), llvm::Depth, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), llvm::EVT::isFixedLengthVector(), and PoisonOnly.
canCreateUndefOrPoison() [2/2]
bool SelectionDAG::canCreateUndefOrPoison (SDValue Op, const APInt & DemandedElts, bool PoisonOnly = false, bool ConsiderFlags = true, unsigned Depth = 0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
The DemandedElts argument limits the check to the requested vector elements.
ConsiderFlags controls whether poison producing flags on the instruction are considered. This can be used to see if the instruction could still introduce undef or poison even without poison generating flags which might be on the instruction. (i.e. could the result of Op->dropPoisonGeneratingFlags() still create poison or undef)
Definition at line 5615 of file SelectionDAG.cpp.
References llvm::ISD::ABDS, llvm::ISD::ABDU, llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::ISD::AND, llvm::ISD::AssertAlign, llvm::ISD::AssertNoFPClass, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::AVGCEILS, llvm::ISD::AVGCEILU, llvm::ISD::AVGFLOORS, llvm::ISD::AVGFLOORU, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::cast(), computeKnownBits(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::CTLS, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::Depth, llvm::enumerate(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMUL, llvm::ISD::FMULADD, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_TO_SINT_SAT, llvm::ISD::FP_TO_UINT_SAT, llvm::ISD::FREEZE, llvm::ISD::FREM, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::ISD::FSUB, llvm::KnownBits::getMaxValue(), getValidMaximumShiftAmount(), llvm::EVT::getVectorMinNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, isKnownNeverZero(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::OR, llvm::ISD::PARITY, PoisonOnly, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SADDO_CARRY, llvm::ISD::SADDSAT, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SCMP, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULO, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SSUBO, llvm::ISD::SSUBO_CARRY, llvm::ISD::SSUBSAT, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UADDO_CARRY, llvm::ISD::UADDSAT, llvm::ISD::UCMP, llvm::APInt::uge(), llvm::APInt::ugt(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULO, llvm::ISD::USUBO, llvm::ISD::USUBO_CARRY, llvm::ISD::USUBSAT, llvm::ISD::VECTOR_COMPRESS, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by canCreateUndefOrPoison(), and isGuaranteedNotToBeUndefOrPoison().
canIgnoreSignBitOfZero() [1/2]
bool SelectionDAG::canIgnoreSignBitOfZero (const SDUse & Use) const
Check if a use of a float value is insensitive to signed zeros.
Definition at line 6191 of file SelectionDAG.cpp.
References assert(), llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FSUB, llvm::User::getOperand(), llvm::Use::getOperandNo(), llvm::Use::getUser(), isKnownNeverZeroFloat(), llvm::Other, and llvm::ISD::SETCC.
Referenced by foldFPToIntToFP().
canIgnoreSignBitOfZero() [2/2]
bool SelectionDAG::canIgnoreSignBitOfZero (SDValue Op) const
Check if at most two uses of a value are insensitive to signed zeros.
Definition at line 6221 of file SelectionDAG.cpp.
References llvm::all_of().
cannotBeOrderedNegativeFP()
bool SelectionDAG::cannotBeOrderedNegativeFP (SDValue Op) const
Test whether the given float value is known to be positive.
+0.0, +inf and +nan are considered positive, -0.0, -inf and -nan are not.
Definition at line 6174 of file SelectionDAG.cpp.
References llvm::ISD::FABS, llvm::ISD::FEXP, llvm::ISD::FEXP10, llvm::ISD::FEXP2, llvm::isConstOrConstSplatFP(), and llvm_unreachable.
canonicalizeCommutativeBinop()
void SelectionDAG::canonicalizeCommutativeBinop (unsigned Opcode, SDValue & N1, SDValue & N2) const
Swap N1 and N2 if Opcode is a commutative binary opcode and the canonical form expects the opposite order.
Definition at line 7631 of file SelectionDAG.cpp.
References llvm::SDValue::getOpcode(), isConstantFPBuildVectorOrConstantFP(), isConstantIntBuildVectorOrConstantInt(), llvm::ISD::SPLAT_VECTOR, llvm::ISD::STEP_VECTOR, and std::swap().
Referenced by getNode(), and getNode().
clear()
void SelectionDAG::clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
Definition at line 1449 of file SelectionDAG.cpp.
References llvm::fill(), and getEntryNode().
clearGraphAttrs()
void SelectionDAG::clearGraphAttrs ()
Clear all previously defined node graph attributes.
clearGraphAttrs - Clear all previously defined node graph attributes.
Intended to be used from a debugging tool (eg. gdb).
Definition at line 179 of file SelectionDAGPrinter.cpp.
References llvm::errs().
Combine()
void SelectionDAG::Combine (CombineLevel Level, BatchAAResults * BatchAA, CodeGenOptLevel OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
This is the entry point for the file.
The Level argument controls whether Combine is allowed to produce nodes and types that are illegal on the target.
This is the main entry point to this class.
Definition at line 30750 of file DAGCombiner.cpp.
computeKnownBits() [1/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements.
Definition at line 3304 of file SelectionDAG.cpp.
References llvm::ISD::ABDS, llvm::KnownBits::abds(), llvm::ISD::ABDU, llvm::KnownBits::abdu(), llvm::ISD::ABS, llvm::KnownBits::abs(), llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::KnownBits::anyext(), llvm::KnownBits::ashr(), assert(), llvm::ISD::AssertAlign, llvm::ISD::AssertNoFPClass, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_SWAP, llvm::ISD::AVGCEILS, llvm::KnownBits::avgCeilS(), llvm::ISD::AVGCEILU, llvm::KnownBits::avgCeilU(), llvm::ISD::AVGFLOORS, llvm::KnownBits::avgFloorS(), llvm::ISD::AVGFLOORU, llvm::KnownBits::avgFloorU(), llvm::bit_width(), llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::BitWidth, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::KnownBits::byteSwap(), llvm::CallingConv::C, llvm::cast(), llvm::APInt::clearAllBits(), llvm::APInt::clearBit(), llvm::APInt::clearBits(), llvm::APInt::clearLowBits(), llvm::KnownBits::computeForAddCarry(), llvm::KnownBits::computeForAddSub(), llvm::KnownBits::computeForSubBorrow(), computeKnownBits(), llvm::computeKnownBitsFromRangeMetadata(), ComputeNumSignBits(), llvm::KnownBits::concat(), llvm::ISD::CONCAT_VECTORS, llvm::APInt::countl_zero(), llvm::KnownBits::countMaxLeadingZeros(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMaxTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::Depth, llvm::dyn_cast(), llvm::enumerate(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::KnownBits::extractBits(), F, llvm::fcNan, llvm::fcNegative, llvm::fcPositive, llvm::ISD::FGETSIGN, llvm::ISD::FP_TO_UINT_SAT, llvm::ISD::FrameIndex, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::Constant::getAggregateElement(), llvm::getAlign(), llvm::APInt::getAllOnes(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitsSetFrom(), llvm::APInt::getBitWidth(), llvm::KnownBits::getBitWidth(), getDataLayout(), llvm::MachineFunction::getFunction(), llvm::APInt::getHiBits(), llvm::APInt::getLowBitsSet(), getMachineFunction(), llvm::ShuffleVectorSDNode::getMask(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::getShuffleDemandedElts(), llvm::EVT::getSizeInBits(), llvm::Constant::getSplatValue(), llvm::Value::getType(), llvm::ConstantRange::getUnsignedMax(), getValidMinimumShiftAmount(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::getVScaleRange(), I, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::KnownBits::insertBits(), llvm::KnownBits::intersectWith(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::ISD::isEXTLoad(), llvm::EVT::isFloatingPoint(), isGuaranteedNotToBeUndefOrPoison(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::APInt::isNegative(), llvm::KnownBits::isNegative(), llvm::ISD::isNON_EXTLoad(), llvm::APInt::isNonNegative(), llvm::KnownBits::isNonNegative(), llvm::KnownBits::isNonZero(), llvm::APInt::isPowerOf2(), llvm::EVT::isScalableVector(), llvm::ISD::isSEXTLoad(), llvm::isUIntN(), llvm::KnownBits::isUnknown(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::ISD::isZEXTLoad(), llvm::ISD::LOAD, llvm::Log2(), llvm::APInt::logBase2(), llvm::KnownBits::lshr(), llvm::KnownBits::makeConstant(), llvm::KnownBits::makeNegative(), llvm::KnownBits::makeNonNegative(), MaxRecursionDepth, llvm::ISD::MERGE_VALUES, llvm::ISD::MGATHER, llvm::ISD::MLOAD, llvm::ISD::MUL, llvm::KnownBits::mul(), llvm::ISD::MULHS, llvm::KnownBits::mulhs(), llvm::ISD::MULHU, llvm::KnownBits::mulhu(), llvm::ConstantRange::multiply(), llvm::ISD::NON_EXTLOAD, llvm::Offset, llvm::KnownBits::One, llvm::ISD::OR, llvm::ISD::PARITY, llvm::KnownBits::resetAll(), llvm::KnownBits::reverseBits(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::APInt::rotr(), llvm::ISD::SADDO, llvm::ISD::SADDO_CARRY, llvm::ISD::SCALAR_TO_VECTOR, llvm::APIntOps::ScaleBitMask(), llvm::ISD::SDIV, llvm::KnownBits::sdiv(), llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::KnownBits::setAllConflict(), llvm::KnownBits::setAllZero(), llvm::APInt::setBit(), llvm::APInt::setBitsFrom(), llvm::ISD::SETCC, llvm::ISD::SETCCCARRY, llvm::APInt::setHighBits(), llvm::APInt::setLowBits(), llvm::KnownBits::sext(), llvm::KnownBits::sextInReg(), llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::APInt::shl(), llvm::KnownBits::shl(), llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, llvm::ArrayRef< T >::size(), llvm::APInt::sle(), llvm::ISD::SMAX, llvm::KnownBits::smax(), llvm::ISD::SMIN, llvm::KnownBits::smin(), llvm::ISD::SMUL_LOHI, llvm::ISD::SMULO, llvm::Splat, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SPLAT_VECTOR_PARTS, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::KnownBits::srem(), llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::ISD::SSUBO_CARRY, llvm::ISD::STEP_VECTOR, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::SUB, llvm::Sub, llvm::ISD::SUBC, std::swap(), llvm::ISD::TargetFrameIndex, llvm::ConstantRange::toKnownBits(), llvm::KnownBits::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UADDO_CARRY, llvm::ISD::UDIV, llvm::KnownBits::udiv(), llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::KnownBits::umax(), llvm::ISD::UMIN, llvm::KnownBits::umin(), llvm::ISD::UMUL_LOHI, llvm::APInt::umul_ov(), umul_ov(), llvm::ISD::UMULO, llvm::KnownBits::unionWith(), llvm::ISD::UREM, llvm::KnownBits::urem(), llvm::KnownBits::usub_sat(), llvm::ISD::USUBO, llvm::ISD::USUBO_CARRY, llvm::ISD::USUBSAT, llvm::ISD::VECTOR_COMPRESS, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSCALE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, llvm::APInt::zext(), llvm::KnownBits::zext(), llvm::ISD::ZEXTLOAD, and llvm::KnownBits::zextOrTrunc().
computeKnownBits() [2/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
For vectors, the known bits are those that are shared by every vector element. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
For vectors, the known bits are those that are shared by every vector element.
Definition at line 3289 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isFixedLengthVector().
Referenced by adjustForRedundantAnd(), llvm::TargetLowering::BuildUDIV(), canCreateUndefOrPoison(), checkDot4MulSignedness(), checkZExtBool(), combineANDOfSETCCToCZERO(), combineArithReduction(), combineFaddCFmul(), combineFMulcFCMulc(), combineMOVMSK(), combineMul(), combineMulToPMADD52(), combineOrAndToBitfieldInsert(), combinePMULH(), combinePTESTCC(), combineSCALAR_TO_VECTOR(), combineSelect(), combineSetCC(), combineShiftToAVG(), combineTruncate(), combineVPMADD52LH(), computeKnownBits(), computeKnownBits(), computeKnownBitsBinOp(), computeKnownBitsForHorizontalOperation(), computeKnownBitsForPMADDUBSW(), computeKnownBitsForPMADDWD(), computeKnownBitsForPRMT(), computeKnownBitsForPSADBW(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SITargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), ComputeNumSignBits(), computeOverflowForSignedMul(), computeOverflowForSignedSub(), computeOverflowForUnsignedAdd(), computeOverflowForUnsignedMul(), computeOverflowForUnsignedSub(), detectExtMul(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandFixedPointDiv(), getPack(), getValidShiftAmountRange(), haveNoCommonBitsSet(), isBitfieldPositioningOp(), isKnownNeverZero(), isSafeSignedCMN(), isTruncateOf(), isWordAligned(), LowerAndToBT(), LowerAndToBTST(), LowerCTPOP(), LowerMINMAX(), LowerMUL(), llvm::SITargetLowering::lowerSET_ROUNDING(), LowerShift(), lowerShuffleWithVPMOV(), LowerVectorAllEqual(), MaskedValueIsAllOnes(), MaskedValueIsZero(), MaskedValueIsZero(), MaskedVectorIsZero(), matchBinaryShuffle(), matchTruncateWithPACK(), matchVPMADD52(), narrowBitOpRMW(), narrowIndex(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), performANDCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performORCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSIGN_EXTEND_INREGCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), performUADDVCombine(), provablyDisjointOr(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegReg(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), tryBitfieldInsertOpFromOr(), and tryBitfieldInsertOpFromOrAndImm().
ComputeMaxSignificantBits() [1/2]
unsigned SelectionDAG::ComputeMaxSignificantBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Get the upper bound on bit size for this Value Op as a signed integer.
i.e. x == sext(trunc(x to MaxSignedBits) to bitwidth(x)). Similar to the APInt::getSignificantBits function. Helper wrapper to ComputeNumSignBits.
Definition at line 5371 of file SelectionDAG.cpp.
References ComputeNumSignBits(), and llvm::Depth.
ComputeMaxSignificantBits() [2/2]
unsigned SelectionDAG::ComputeMaxSignificantBits (SDValue Op, unsigned Depth = 0) const
Get the upper bound on bit size for this Value Op as a signed integer.
i.e. x == sext(trunc(x to MaxSignedBits) to bitwidth(x)). Similar to the APInt::getSignificantBits function. Helper wrapper to ComputeNumSignBits.
Definition at line 5365 of file SelectionDAG.cpp.
References ComputeNumSignBits(), and llvm::Depth.
Referenced by combineConcatVectorOps(), combineMulToPMADDWD(), combinePMULH(), detectExtMul(), EmitCmp(), llvm::TargetLowering::expandMUL_LOHI(), getPack(), lowerBuildVectorOfConstants(), llvm::AMDGPUTargetLowering::numBitsSigned(), and llvm::TargetLowering::SimplifyDemandedBits().
ComputeNumSignBits() [1/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. The DemandedElts argument allows us to only collect the minimum sign bits of the requested vector elements. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 4675 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::AND, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_SWAP, llvm::ISD::AVGCEILS, llvm::ISD::AVGFLOORS, llvm::ISD::BITCAST, llvm::BitWidth, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::CallingConv::C, llvm::cast(), llvm::APInt::clearBit(), llvm::APInt::clearBits(), computeKnownBits(), ComputeNumSignBits(), llvm::ISD::CONCAT_VECTORS, llvm::KnownBits::countMinSignBits(), llvm::Depth, llvm::dyn_cast(), llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FP_TO_SINT_SAT, llvm::ISD::FREEZE, llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnes(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitWidth(), llvm::ConstantRange::getBitWidth(), llvm::getConstantRangeFromMetadata(), getDataLayout(), llvm::ShuffleVectorSDNode::getMask(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::SDValue::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::getShuffleDemandedElts(), llvm::ConstantRange::getSignedMax(), llvm::ConstantRange::getSignedMin(), getValidMinimumShiftAmount(), getValidShiftAmountRange(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::ISD::isExtOpcode(), llvm::EVT::isFloatingPoint(), isGuaranteedNotToBeUndefOrPoison(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::KnownBits::isNonNegative(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::ISD::LOAD, MaxRecursionDepth, llvm::ISD::MERGE_VALUES, llvm::ISD::MUL, llvm::ISD::NON_EXTLOAD, llvm::ISD::OR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SADDO_CARRY, llvm::APIntOps::ScaleBitMask(), llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETCCCARRY, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ConstantRange::signExtend(), llvm::ArrayRef< T >::size(), llvm::APInt::sle(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULO, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SSUBO, llvm::ISD::SSUBO_CARRY, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::SUB, llvm::Sub, std::swap(), T, llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UADDO_CARRY, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULO, llvm::ISD::USUBO, llvm::ISD::USUBO_CARRY, llvm::ISD::VECTOR_COMPRESS, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, llvm::ConstantRange::zeroExtend(), llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::APInt::zext(), and llvm::ISD::ZEXTLOAD.
ComputeNumSignBits() [2/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 4663 of file SelectionDAG.cpp.
References ComputeNumSignBits(), llvm::Depth, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isFixedLengthVector().
Referenced by canReduceVMulWidth(), combineAnd(), combineAndMaskToShift(), combineAndnp(), combineBitOpWithPACK(), combineGatherScatter(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMulToPMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineSelect(), combineSetCCMOVMSK(), combineShiftToAVG(), combineSIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVectorPack(), combineVSelectWithAllOnesOrZeros(), computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), ComputeMaxSignificantBits(), ComputeMaxSignificantBits(), ComputeNumSignBits(), ComputeNumSignBits(), computeNumSignBitsBinOp(), llvm::AArch64TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::RISCVTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), computeOverflowForSignedAdd(), computeOverflowForSignedMul(), computeOverflowForSignedSub(), EmitCmp(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandFixedPointDiv(), foldAddSubMasked1(), getFauxShuffleMask(), getNode(), isS16(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerEXTEND_VECTOR_INREG(), LowerMINMAX(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerShiftByScalarImmediate(), lowerShuffleWithVPMOV(), LowerTruncateVecI1(), lowerVectorIntrinsicScalars(), LowerVSETCC(), matchBinaryShuffle(), matchShuffleWithPACK(), matchTruncateWithPACK(), matchUnaryShuffle(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performVectorShiftCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), selectUmullSmull(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), and llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode().
computeOverflowForAdd()
OverflowKind llvm::SelectionDAG::computeOverflowForAdd (bool IsSigned, SDValue N0, SDValue N1) const inline
Determine if the result of the addition of 2 nodes can overflow.
Definition at line 2153 of file SelectionDAG.h.
References computeOverflowForSignedAdd(), and computeOverflowForUnsignedAdd().
Referenced by willNotOverflowAdd().
computeOverflowForMul()
OverflowKind llvm::SelectionDAG::computeOverflowForMul (bool IsSigned, SDValue N0, SDValue N1) const inline
Determine if the result of the mul of 2 nodes can overflow.
Definition at line 2193 of file SelectionDAG.h.
References computeOverflowForSignedMul(), and computeOverflowForUnsignedMul().
Referenced by willNotOverflowMul().
computeOverflowForSignedAdd()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowForSignedAdd (SDValue N0, SDValue N1) const
Determine if the result of the signed addition of 2 nodes can overflow.
Definition at line 4458 of file SelectionDAG.cpp.
References ComputeNumSignBits(), llvm::isNullConstant(), OFK_Never, and OFK_Sometime.
Referenced by computeOverflowForAdd().
computeOverflowForSignedMul()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowForSignedMul (SDValue N0, SDValue N1) const
Determine if the result of the signed mul of 2 nodes can overflow.
Definition at line 4540 of file SelectionDAG.cpp.
References llvm::BitWidth, computeKnownBits(), ComputeNumSignBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::KnownBits::isNonNegative(), llvm::isNullConstant(), llvm::isOneConstant(), OFK_Never, and OFK_Sometime.
Referenced by computeOverflowForMul().
computeOverflowForSignedSub()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowForSignedSub (SDValue N0, SDValue N1) const
Determine if the result of the signed sub of 2 nodes can overflow.
Definition at line 4496 of file SelectionDAG.cpp.
References computeKnownBits(), ComputeNumSignBits(), llvm::ConstantRange::fromKnownBits(), llvm::isNullConstant(), mapOverflowResult(), OFK_Never, and llvm::ConstantRange::signedSubMayOverflow().
Referenced by computeOverflowForSub().
computeOverflowForSub()
OverflowKind llvm::SelectionDAG::computeOverflowForSub (bool IsSigned, SDValue N0, SDValue N1) const inline
Determine if the result of the sub of 2 nodes can overflow.
Definition at line 2173 of file SelectionDAG.h.
References computeOverflowForSignedSub(), and computeOverflowForUnsignedSub().
Referenced by willNotOverflowSub().
computeOverflowForUnsignedAdd()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowForUnsignedAdd (SDValue N0, SDValue N1) const
Determine if the result of the unsigned addition of 2 nodes can overflow.
Definition at line 4473 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::ConstantRange::fromKnownBits(), llvm::KnownBits::getMaxValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getResNo(), llvm::isNullConstant(), mapOverflowResult(), OFK_Never, llvm::APInt::ult(), llvm::ISD::UMUL_LOHI, and llvm::ConstantRange::unsignedAddMayOverflow().
Referenced by computeOverflowForAdd().
computeOverflowForUnsignedMul()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowForUnsignedMul (SDValue N0, SDValue N1) const
Determine if the result of the unsigned mul of 2 nodes can overflow.
Definition at line 4527 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::ConstantRange::fromKnownBits(), llvm::isNullConstant(), llvm::isOneConstant(), mapOverflowResult(), OFK_Never, and llvm::ConstantRange::unsignedMulMayOverflow().
Referenced by computeOverflowForMul().
computeOverflowForUnsignedSub()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowForUnsignedSub (SDValue N0, SDValue N1) const
Determine if the result of the unsigned sub of 2 nodes can overflow.
Definition at line 4514 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::ConstantRange::fromKnownBits(), llvm::isNullConstant(), mapOverflowResult(), OFK_Never, and llvm::ConstantRange::unsignedSubMayOverflow().
Referenced by computeOverflowForSub().
computeVectorKnownZeroElements()
APInt SelectionDAG::computeVectorKnownZeroElements (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
For each demanded element of a vector, see if it is known to be zero.
Definition at line 2874 of file SelectionDAG.cpp.
References assert(), llvm::Depth, llvm::APInt::getBitWidth(), llvm::APInt::getOneBitSet(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZero(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), MaskedVectorIsZero(), and llvm::APInt::setBit().
Referenced by combineShuffleToZeroExtendVectorInReg().
copyExtraInfo()
void SelectionDAG::copyExtraInfo (SDNode * From, SDNode * To)
Copy extra info associated with one node to another.
Definition at line 14309 of file SelectionDAG.cpp.
References assert(), llvm::SmallPtrSetImplBase::clear(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains(), llvm::dbgs(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::errs(), getEntryNode(), llvm::SDValue::getNode(), I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, LLVM_LIKELY, N, and std::swap().
Referenced by ReplaceAllUsesOfValuesWith(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), ReplaceAllUsesWith(), and ReplaceAllUsesWith().
CreateStackTemporary() [1/3]
SDValue SelectionDAG::CreateStackTemporary (EVT VT, unsigned minAlign = 1)
Create a stack temporary, suitable for holding the specified value type.
If minAlign is specified, the slot size will have at least that alignment.
Definition at line 2616 of file SelectionDAG.cpp.
References CreateStackTemporary(), getContext(), getDataLayout(), getPrefTypeAlign(), llvm::EVT::getStoreSize(), and llvm::EVT::getTypeForEVT().
CreateStackTemporary() [2/3]
SDValue SelectionDAG::CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
Definition at line 2623 of file SelectionDAG.cpp.
References assert(), CreateStackTemporary(), DL, getContext(), getDataLayout(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::EVT::getStoreSize(), llvm::EVT::getTypeForEVT(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
CreateStackTemporary() [3/3]
SDValue SelectionDAG::CreateStackTemporary (TypeSize Bytes, Align Alignment)
Create a stack temporary based on the size in bytes and the alignment.
Definition at line 2603 of file SelectionDAG.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), getDataLayout(), getFrameIndex(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::TargetFrameLowering::getStackIDForScalableVectors(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
Referenced by CreateStackTemporary(), CreateStackTemporary(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorSplice(), LowerATOMIC_STORE(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), and llvm::X86TargetLowering::ReplaceNodeResults().
DbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgBegin () const inline
Definition at line 2019 of file SelectionDAG.h.
Referenced by dump().
DbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgEnd () const inline
Definition at line 2020 of file SelectionDAG.h.
Referenced by dump().
DbgLabelBegin()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelBegin () const inline
Definition at line 2029 of file SelectionDAG.h.
DbgLabelEnd()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelEnd () const inline
Definition at line 2032 of file SelectionDAG.h.
DeleteNode()
void SelectionDAG::DeleteNode (SDNode * N)
Remove the specified node from the system.
This node must have no referrers.
Definition at line 1087 of file SelectionDAG.cpp.
References N.
Referenced by Legalize().
doesNodeExist()
bool SelectionDAG::doesNodeExist (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
Check if a node exists without modifying its flags.
doesNodeExist - Check if a node exists without modifying its flags.
Definition at line 11936 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
Referenced by canEmitConjunction(), combineConcatVectorOps(), EmitCmp(), llvm::TargetLowering::expandIntMINMAX(), foldAndOrOfSETCC(), performCSELCombine(), and llvm::TargetLowering::SimplifySetCC().
dump()
LLVM_DUMP_METHOD void SelectionDAG::dump (bool Sorted = false) const
Dump the textual format of this DAG.
Print nodes in sorted orders if Sorted is true.
Definition at line 1078 of file SelectionDAGDumper.cpp.
References allnodes(), ByvalParmDbgBegin(), ByvalParmDbgEnd(), DbgBegin(), DbgEnd(), llvm::dbgs(), DumpNodes(), getNode(), getRoot(), getTopologicallyOrderedNodes(), LLVM_DUMP_METHOD, llvm::make_range(), N, llvm::SmallVectorImpl< T >::reserve(), shouldPrintInline(), and VerboseDAGDumping.
dumpDotGraph()
LLVM_DUMP_METHOD void SelectionDAG::dumpDotGraph (const Twine & FileName, const Twine & Title)
Just dump dot graph to a user-provided path and title.
This doesn't open the dot viewer program and helps visualization when outside debugging session. FileName expects absolute path. If provided without any path separators then the file will be created in the current directory. Error will be emitted if the path is insane.
Definition at line 171 of file SelectionDAGPrinter.cpp.
References llvm::dumpDotGraphToFile(), and LLVM_DUMP_METHOD.
expandVAArg()
SDValue SelectionDAG::expandVAArg (SDNode * Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
Definition at line 2522 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::cast(), getConstant(), getContext(), getDataLayout(), getLoad(), getNode(), getSignedConstant(), getStore(), getTargetLoweringInfo(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValue(), and llvm::SDValue::getValueType().
expandVACopy()
SDValue SelectionDAG::expandVACopy (SDNode * Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
Definition at line 2556 of file SelectionDAG.cpp.
References llvm::cast(), getDataLayout(), getLoad(), getStore(), getTargetLoweringInfo(), and llvm::SDValue::getValue().
Referenced by LowerVACOPY().
ExtractVectorElements()
void SelectionDAG::ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > & Args, unsigned Start = 0, unsigned Count = 0, EVT EltVT = EVT())
Append the extracted elements from Start to Count out of the vector Op in Args.
If Count is 0, all of the elements will be extracted. The extracted elements will have type EVT if it is provided, and otherwise their type will be Op's element type.
Definition at line 13732 of file SelectionDAG.cpp.
References llvm::Count, getExtractVectorElt(), llvm::EVT::getVectorElementType(), and llvm::EVT::getVectorNumElements().
Referenced by adjustLoadValueTypeImpl(), llvm::TargetLowering::expandVecReduce(), llvm::TargetLowering::expandVecReduceSeq(), getBuildVectorizedValue(), getDWordFromOffset(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), lowerSTOREVector(), padEltsToUndef(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), replaceLoadVector(), scalarizeBinOpOfSplats(), llvm::AMDGPUTargetLowering::splitVector(), UnrollVectorOverflowOp(), unrollVectorShift(), and widenVectorToPartType().
FoldConstantArithmetic()
SDValue SelectionDAG::FoldConstantArithmetic (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, SDNodeFlags Flags = SDNodeFlags())
Definition at line 6971 of file SelectionDAG.cpp.
References llvm::ISD::ABS, llvm::APInt::abs(), AbstractManglingParser< Derived, Alloc >::NumOps, AbstractManglingParser< Derived, Alloc >::Ops, llvm::APFloat::add(), llvm::all_of(), llvm::ISD::ANY_EXTEND, llvm::APInt::ashrInPlace(), assert(), llvm::ISD::BF16_TO_FP, llvm::APFloatBase::BFloat(), llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::APInt::byteSwap(), llvm::CallingConv::C, llvm::cast(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::CONDCODE, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::APFloat::convert(), llvm::APFloat::convertFromAPInt(), llvm::APInt::countl_zero(), llvm::APInt::countr_zero(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, DL, llvm::dyn_cast(), llvm::ISD::FABS, llvm::ISD::FCEIL, llvm::ISD::FFLOOR, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMULADD, llvm::ISD::FNEG, foldConstantFPMath(), FoldSTEP_VECTOR(), FoldSymbolOffset(), FoldValue(), FoldValueWithUndef(), llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_TO_BF16, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FSHL, llvm::APIntOps::fshl(), llvm::ISD::FSHR, llvm::APIntOps::fshr(), llvm::ISD::FTRUNC, llvm::APFloat::fusedMultiplyAdd(), getBitcast(), llvm::APInt::getBitWidth(), getBuildVector(), getConstant(), getConstantFP(), getContext(), getDataLayout(), llvm::TargetLoweringBase::getExtendForContent(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::EVT::getFltSemantics(), getNode(), getOpcode(), llvm::SDValue::getOpcode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getSplatVector(), getStepVector(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZero(), I, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm::isa(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::ISD::isConstantSplatVector(), llvm::EVT::isFixedLengthVector(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::SDValue::isUndef(), isUndef(), llvm::EVT::isVector(), llvm::ISD::MUL, llvm::APFloat::multiply(), NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::APFloatBase::opInexact, llvm::APFloatBase::opInvalidOp, llvm::APFloatBase::opOK, llvm::peekThroughBitcasts(), llvm::APInt::popcount(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::BuildVectorSDNode::recastRawBits(), llvm::APInt::reverseBits(), llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloatBase::rmTowardNegative, llvm::APFloatBase::rmTowardPositive, llvm::APFloatBase::rmTowardZero, llvm::ISD::SETCC, llvm::APInt::sextOrTrunc(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ISD::SPLAT_VECTOR, llvm::ISD::STEP_VECTOR, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::TargetLoweringBase::TypeLegal, llvm::ISD::UINT_TO_FP, llvm::ISD::ZERO_EXTEND, and llvm::APInt::zextOrTrunc().
Referenced by combineGatherScatter(), combineSelect(), foldAddSubOfSignBit(), foldBinOpIntoSelectIfProfitable(), foldBinOpIntoSelectIfProfitable(), getNode(), getNode(), getNode(), getTargetVShiftByConstNode(), getTargetVShiftNode(), LowerRotate(), PromoteMaskArithmetic(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyDemandedVectorElts().
FoldConstantBuildVector()
SDValue SelectionDAG::FoldConstantBuildVector (BuildVectorSDNode * BV, const SDLoc & DL, EVT DstEltVT)
Fold BUILD_VECTOR of constants/undefs to the destination type BUILD_VECTOR of constants/undefs elements.
Definition at line 7522 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::cast(), DL, FoldConstantBuildVector(), getBitcast(), getBuildVector(), getConstant(), llvm::BuildVectorSDNode::getConstantRawBits(), getContext(), getDataLayout(), llvm::EVT::getIntegerVT(), getNode(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), I, llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::SDNode::op_values(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ISD::TRUNCATE.
Referenced by FoldConstantBuildVector().
foldConstantFPMath()
SDValue SelectionDAG::foldConstantFPMath (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops)
Fold floating-point operations when all operands are constants and/or undefined.
Definition at line 7435 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::APFloat::add(), llvm::APFloat::convert(), llvm::APFloat::copySign(), llvm::APFloat::divide(), DL, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXIMUMNUM, llvm::ISD::FMAXNUM, llvm::ISD::FMINIMUM, llvm::ISD::FMINIMUMNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FP_ROUND, llvm::ISD::FREM, llvm::ISD::FSUB, getConstantFP(), llvm::EVT::getFltSemantics(), llvm::APFloat::getNaN(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::isConstOrConstSplatFP(), llvm::APFloat::isSignaling(), llvm::SDValue::isUndef(), llvm::maximum(), llvm::maximumnum(), llvm::maxnum(), llvm::minimum(), llvm::minimumnum(), llvm::minnum(), llvm::APFloat::mod(), llvm::APFloat::multiply(), llvm::APFloatBase::rmNearestTiesToEven, and llvm::APFloat::subtract().
Referenced by FoldConstantArithmetic().
FoldSetCC()
SDValue SelectionDAG::FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc & dl)
Constant fold a setcc to true or false.
Definition at line 2640 of file SelectionDAG.cpp.
References assert(), llvm::APFloatBase::cmpEqual, llvm::APFloatBase::cmpGreaterThan, llvm::APFloatBase::cmpLessThan, llvm::APFloatBase::cmpUnordered, llvm::ICmpInst::compare(), Cond, llvm::dyn_cast(), getBoolConstant(), getConstant(), llvm::getICmpCondCode(), llvm::EVT::getScalarType(), getSetCC(), llvm::ISD::getSetCCSwappedOperands(), llvm::EVT::getSimpleVT(), getUNDEF(), llvm::ISD::getUnorderedFlavor(), llvm::SDValue::getValueType(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::ISD::isTrueWhenEqual(), llvm::SDValue::isUndef(), llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, and llvm::TargetLoweringBase::UndefinedBooleanContent.
Referenced by getNode(), and llvm::TargetLowering::SimplifySetCC().
FoldSymbolOffset()
SDValue SelectionDAG::FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode * GA, const SDNode * N2)
Definition at line 6924 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::dyn_cast(), llvm::GlobalAddressSDNode::getGlobal(), getGlobalAddress(), llvm::GlobalAddressSDNode::getOffset(), llvm::SDNode::getOpcode(), llvm::ISD::GlobalAddress, llvm::Offset, llvm::ISD::PTRADD, and llvm::ISD::SUB.
Referenced by FoldConstantArithmetic().
getAddrSpaceCast()
SDValue SelectionDAG::getAddrSpaceCast (const SDLoc & dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
Definition at line 2479 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::ISD::ADDRSPACECAST, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), and N.
Referenced by combineLoad(), combineStore(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerSTACKRESTORE(), llvm::NVPTXTargetLowering::LowerSTACKSAVE(), performLOADCombine(), performSTORECombine(), refinePtrAS(), and UnrollVectorOp().
getAllOnesConstant()
SDValue SelectionDAG::getAllOnesConstant (const SDLoc & DL, EVT VT, bool IsTarget = false, bool IsOpaque = false)
Definition at line 1794 of file SelectionDAG.cpp.
References DL, llvm::APInt::getAllOnes(), getConstant(), and llvm::EVT::getScalarSizeInBits().
Referenced by combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineAndLoadToBZHI(), combineBitcastToBoolVector(), combineMinMaxReduction(), combinePTESTCC(), combineSelectToBinOp(), combineSetCC(), combineSetCCMOVMSK(), combineVectorCompare(), combineVectorShiftImm(), combineVectorSizedSetCCEquality(), ConvertCarryValueToCarryFlag(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandRoundInexactToOdd(), llvm::TargetLowering::expandVPCTLZ(), llvm::TargetLowering::expandVPCTTZ(), expandVPFunnelShift(), foldBoolSelectToLogic(), foldSubCtlzNot(), foldXorTruncShiftIntoCmp(), getBoolConstant(), getNeutralElement(), getNode(), getNOT(), getOnesVector(), getTargetVShiftNode(), getWideningInterleave(), isConditionalZeroOrAllOnes(), isConditionalZeroOrAllOnes(), LowerADDSUBO_CARRY(), LowerBUILD_VECTORvXi1(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), lowerSelectToBinOp(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), LowerSIGN_EXTEND_Mask(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerVectorAllEqual(), LowerVSETCC(), lowerWaveShuffle(), MatchVectorAllEqualTest(), performAddCSelIntoCSinc(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performSIGN_EXTEND_INREGCombine(), performSignExtendInRegCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), ReplaceATOMIC_LOAD_128Results(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifySetCC(), and simplifySetCCWithCTPOP().
getAnyExtOrTrunc()
SDValue SelectionDAG::getAnyExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
Definition at line 1490 of file SelectionDAG.cpp.
References llvm::ISD::ANY_EXTEND, llvm::EVT::bitsGT(), DL, getNode(), and llvm::ISD::TRUNCATE.
Referenced by combineAVX512SetCCToKMOV(), combineBitcast(), combineExtractVectorElt(), combineSCALAR_TO_VECTOR(), combineStore(), combineToExtendBoolVectorInReg(), createMMXBuildVector(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), getBitcastedAnyExtOrTrunc(), getCopyFromPartsVector(), getCopyToPartsVector(), getExtOrTrunc(), getNode(), getVectorBitwiseReduce(), LowerADDRSPACECAST(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerFunnelShift(), lowerLaneOp(), lowerSELECT(), performBuildShuffleExtendCombine(), PerformVSELECTCombine(), llvm::HexagonTargetLowering::ReplaceNodeResults(), and replaceProxyReg().
getAssertAlign()
SDValue SelectionDAG::getAssertAlign (const SDLoc & DL, SDValue V, Align A)
Return an AssertAlignSDNode.
Definition at line 7594 of file SelectionDAG.cpp.
References A(), AddNodeIDNode(), assert(), llvm::ISD::AssertAlign, DL, llvm::SDValue::getValueType(), getVTList(), llvm::EVT::isInteger(), N, and NewSDValueDbgMsg().
getAtomic() [1/2]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
Definition at line 9616 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_FADD, llvm::ISD::ATOMIC_LOAD_FMAX, llvm::ISD::ATOMIC_LOAD_FMAXIMUM, llvm::ISD::ATOMIC_LOAD_FMIN, llvm::ISD::ATOMIC_LOAD_FMINIMUM, llvm::ISD::ATOMIC_LOAD_FSUB, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UDEC_WRAP, llvm::ISD::ATOMIC_LOAD_UINC_WRAP, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_USUB_COND, llvm::ISD::ATOMIC_LOAD_USUB_SAT, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, getAtomic(), llvm::SDValue::getValueType(), and getVTList().
Referenced by combineSetCCAtomicArith(), getAtomic(), getAtomicCmpSwap(), getAtomicLoad(), LowerATOMIC_STORE(), llvm::VETargetLowering::lowerATOMIC_SWAP(), and lowerAtomicArith().
getAtomic() [2/2]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::LoadExtType ExtType = ISD::NON_EXTLOAD)
Gets a node for an atomic op, produces result and chain and takes N operands.
Definition at line 9575 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::cast_or_null(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), N, and NewSDValueDbgMsg().
getAtomicCmpSwap()
SDValue SelectionDAG::getAtomicCmpSwap (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand * MMO)
Gets a node for an atomic cmpxchg op.
There are two valid Opcodes. ISD::ATOMIC_CMO_SWAP produces the value loaded and a chain result. ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS produces the value loaded, a success flag (initially i1), and a chain.
Definition at line 9604 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, getAtomic(), and llvm::SDValue::getValueType().
getAtomicLoad()
SDValue SelectionDAG::getAtomicLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 9644 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::ATOMIC_LOAD, getAtomic(), and getVTList().
Referenced by reduceANDOfAtomicLoad(), and tryToFoldExtOfAtomicLoad().
getAtomicMemcpy()
SDValue SelectionDAG::getAtomicMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 9310 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::DataLayout::getIntPtrType(), llvm::RTLIB::getMEMCPY_ELEMENT_UNORDERED_ATOMIC(), llvm::Type::getVoidTy(), llvm::report_fatal_error(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), and Size.
getAtomicMemmove()
SDValue SelectionDAG::getAtomicMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 9416 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::DataLayout::getIntPtrType(), llvm::RTLIB::getMEMMOVE_ELEMENT_UNORDERED_ATOMIC(), llvm::Type::getVoidTy(), llvm::report_fatal_error(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), and Size.
getAtomicMemset()
SDValue SelectionDAG::getAtomicMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Value, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
Definition at line 9543 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::Type::getInt8Ty(), llvm::RTLIB::getMEMSET_ELEMENT_UNORDERED_ATOMIC(), llvm::Type::getVoidTy(), llvm::report_fatal_error(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), and Size.
getBasicBlock()
SDValue SelectionDAG::getBasicBlock (MachineBasicBlock * MBB)
Definition at line 2033 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BasicBlock, getVTList(), MBB, and N.
Referenced by AddNodeIDCustom().
getBFI()
BlockFrequencyInfo * llvm::SelectionDAG::getBFI () const inline
Definition at line 514 of file SelectionDAG.h.
getBitcast()
SDValue SelectionDAG::getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
Use getNode to set a custom SDLoc.
Definition at line 2472 of file SelectionDAG.cpp.
References llvm::ISD::BITCAST, and getNode().
Referenced by addShuffleForVecExtend(), adjustBitcastSrcVectorSSE1(), canonicalizeBitSelect(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithHorizOp(), canonicalizeShuffleVectorByLane(), canonicalizeShuffleWithOp(), combineAnd(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndNotIntoVANDN(), combineAndnp(), combineAndShuffleNot(), combineArithReduction(), combineBasicSADPattern(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBitOpWithMOVMSK(), combineBitOpWithPACK(), combineBitOpWithShift(), combineBITREVERSE(), combineBlendOfPermutes(), combineBROADCAST_LOAD(), combineCastedMaskArithmetic(), combineCMP(), combineCompareEqual(), combineCONCAT_VECTORS(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineConstantPoolLoads(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddCFmul(), combineFMulcFCMulc(), combineFneg(), combineFP_EXTEND(), combineFP_ROUND(), combineHorizOpWithShuffle(), combineINSERT_SUBVECTOR(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMinMaxReduction(), combineMOVMSK(), combineMulToPMADDWD(), combineOr(), combinePMULDQ(), combinePMULH(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineSCALAR_TO_VECTOR(), combineScalarAndWithMaskSetcc(), combineSelect(), combineSetCCMOVMSK(), combineShuffleOfBitcast(), combineShuffleToAnyExtendVectorInreg(), combineShuffleToZeroExtendVectorInReg(), combineSIntToFP(), combineStore(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToFPTruncExtElt(), combineTruncationShuffle(), combineVectorCompareAndMaskUnaryOp(), combineVectorHADDSUB(), combineVectorPack(), combineVectorShiftImm(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVPDPBUSDPattern(), combineVSelectWithAllOnesOrZeros(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), combineXor(), constructDup(), convertIntLogicToFPLogic(), convertShiftLeftToScale(), convertTwoLoadsAndCmpToVCMPEQUB(), createMMXBuildVector(), createVariablePermute(), EltsFromConsecutiveLoads(), expandBitCastF128ToI128(), expandBitCastI128ToF128(), llvm::TargetLowering::expandIS_FPCLASS(), llvm::TargetLowering::expandUINT_TO_FP(), ExtractBitFromMaskVector(), FixupMMXIntrinsicTypes(), FoldConstantArithmetic(), FoldConstantBuildVector(), FoldIntToFPToInt(), GeneratePerfectShuffle(), generateSToVPermutedForVecShuffle(), getAVX2GatherNode(), getBitcastedAnyExtOrTrunc(), getBitcastedSExtOrTrunc(), getBitcastedZExtOrTrunc(), getBuildDwordsVector(), getCanonicalConstSplat(), getConstVector(), getConstVector(), getCopyFromPartsVector(), getCopyToPartsVector(), getDataClassTest(), getDeinterleaveShiftAndTrunc(), getFlagsOfCmpZeroFori1(), getMaskNode(), getMemsetValue(), llvm::X86TargetLowering::getNegatedExpression(), getOnesVector(), getPack(), getScalarMaskingNode(), getScalarValueForVectorElement(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getv64i1Argument(), getVCIXISDNodeWCHAIN(), getVectorBitwiseReduce(), getVShift(), getWideningInterleave(), getWideningSpread(), getZeroVector(), llvm::TargetLowering::IncrementMemoryAddress(), isHorizontalBinOp(), IsNOT(), isNOT(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), llvm::SystemZTargetLowering::joinRegisterPartsIntoValue(), lower128BitShuffle(), lower256BitShuffle(), lower512BitShuffle(), LowerATOMIC_STORE(), LowerAVXExtend(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBitreverseShuffle(), lowerBSWAP(), lowerBUILD_VECTOR(), LowerBUILD_VECTORvXbf16(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), lowerBuildVectorOfConstants(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::HexagonTargetLowering::LowerCall(), LowerCTPOP(), LowerEXTEND_VECTOR_INREG(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerFMINIMUM_FMAXIMUM(), llvm::SITargetLowering::LowerFormalArguments(), LowerFunnelShift(), LowerHorizontalByteSum(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), lowerIntNeonIntrinsic(), lowerLaneOp(), LowerLoad(), lowerMasksToReg(), LowerMINMAX(), LowerMUL(), LowerMULH(), llvm::RISCVTargetLowering::LowerOperation(), lowerRegToMasks(), llvm::HexagonTargetLowering::LowerReturn(), LowerRotate(), LowerSCALAR_TO_VECTOR(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), lowerShuffleAsBitMask(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificExtension(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPSHUFB(), lowerShuffleWithUNPCK256(), lowerShuffleWithVPMOV(), LowerStore(), lowerSTOREVector(), LowerTruncateVecI1(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4F32Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8F16Shuffle(), lowerV8F32Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_IsReverse(), lowerVECTOR_SHUFFLEAsByteRotate(), lowerVECTOR_SHUFFLEAsLanePermuteAndShuffle(), lowerVECTOR_SHUFFLEAsRotate(), lowerVECTOR_SHUFFLEAsShift(), lowerVECTOR_SHUFFLEAsVSlide1(), lowerVECTOR_SHUFFLEAsZeroOrAnyExtend(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVectorAllEqual(), LowerVectorCTLZ_GFNI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), lowerVectorIntrinsicScalars(), LowerVectorMatch(), LowerVSETCC(), LowervXi8MulWithUNPCK(), lowerVZIP(), lowerWaveShuffle(), lowerX86FPLogicOp(), matchPERM(), narrowExtractedVectorBinOp(), narrowExtractedVectorSelect(), packImage16bitOpsToDwords(), Passv64i1ArgInRegs(), performBITCASTCombine(), performBitcastCombine(), PerformBUILD_VECTORCombine(), performCONCAT_VECTORSCombine(), performConcatVectorsCombine(), performConvertFPCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performMulCombine(), performSETCC_BITCASTCombine(), performUzpCombine(), performVANDNCombine(), performVECTOR_SHUFFLECombine(), performVECTOR_SHUFFLECombine(), processVCIXOperands(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceBuildVecToShuffleWithZero(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), ReplaceBITCAST(), replaceLoadVector(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), scalarizeVectorStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), splitAndLowerShuffle(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::SystemZTargetLowering::splitValueIntoRegisterParts(), takeInexpensiveLog2(), truncateVectorWithNARROW(), truncateVectorWithPACK(), tryCombineNeonFcvtFP16ToI16(), tryWidenMaskForShuffle(), tryWidenMaskForShuffle(), llvm::X86TargetLowering::visitMaskedLoad(), llvm::X86TargetLowering::visitMaskedStore(), widenBuildVec(), widenBuildVector(), and widenShuffleMask().
getBitcastedAnyExtOrTrunc()
SDValue SelectionDAG::getBitcastedAnyExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by first bitcasting (from potential vector) to corresponding scalar type then either any-extending or truncating it.
Definition at line 1508 of file SelectionDAG.cpp.
References assert(), DL, getAnyExtOrTrunc(), getBitcast(), llvm::EVT::getIntegerVT(), llvm::SDValue::getValueType(), llvm::EVT::isVector(), and Size.
Referenced by getDWordFromOffset(), and matchPERM().
getBitcastedSExtOrTrunc()
SDValue SelectionDAG::getBitcastedSExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by first bitcasting (from potential vector) to corresponding scalar type then either sign-extending or truncating it.
Definition at line 1523 of file SelectionDAG.cpp.
References assert(), DL, getBitcast(), llvm::MVT::getIntegerVT(), getSExtOrTrunc(), llvm::SDValue::getValueType(), llvm::EVT::isVector(), and Size.
getBitcastedZExtOrTrunc()
SDValue SelectionDAG::getBitcastedZExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by first bitcasting (from potential vector) to corresponding scalar type then either zero-extending or truncating it.
Definition at line 1538 of file SelectionDAG.cpp.
References assert(), DL, getBitcast(), llvm::MVT::getIntegerVT(), llvm::SDValue::getValueType(), getZExtOrTrunc(), llvm::EVT::isVector(), and Size.
getBlockAddress()
SDValue SelectionDAG::getBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, bool isTarget = false, unsigned TargetFlags = 0)
Definition at line 2421 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BlockAddress, getVTList(), N, llvm::Offset, Opc, and llvm::ISD::TargetBlockAddress.
Referenced by getTargetBlockAddress(), and llvm::LanaiTargetLowering::LowerBlockAddress().
getBoolConstant()
SDValue SelectionDAG::getBoolConstant (bool V, const SDLoc & DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
Definition at line 1645 of file SelectionDAG.cpp.
References DL, getAllOnesConstant(), getConstant(), llvm_unreachable, llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
Referenced by llvm::TargetLowering::expandIS_FPCLASS(), llvm::TargetLowering::expandMultipleResultFPLibCall(), FoldSetCC(), getDataClassTest(), getLogicalNOT(), getVPLogicalNOT(), performSETCCCombine(), llvm::TargetLowering::SimplifySetCC(), and UnrollVectorOverflowOp().
getBoolExtOrTrunc()
SDValue SelectionDAG::getBoolExtOrTrunc (SDValue Op, const SDLoc & SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
Definition at line 1553 of file SelectionDAG.cpp.
References llvm::EVT::bitsLE(), getNode(), and llvm::ISD::TRUNCATE.
Referenced by combineCarryDiamond(), combineSelectAsExtAnd(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandUADDSUBO(), and llvm::TargetLowering::SimplifySetCC().
getBuildVector() [1/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDUse > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 882 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::BUILD_VECTOR, DL, and getNode().
getBuildVector() [2/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDValue > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 873 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::BUILD_VECTOR, DL, and getNode().
Referenced by adjustLoadValueTypeImpl(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), BuildExactUDIV(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineADDToSUB(), combineConcatVectorOfScalars(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineShuffleOfScalars(), combineStore(), combineToExtendBoolVectorInReg(), combineX86ShuffleChain(), CompactSwizzlableVector(), convertLocVTToValVT(), convertShiftLeftToScale(), ExtendToType(), extractSubVector(), extractSubVector(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), FoldConstantBuildVector(), GenerateFixedLengthSVETBL(), GenerateTBL(), getBuildDwordsVector(), getBuildVectorizedValue(), getBuildVectorSplat(), getConstant(), getConstVector(), getConstVector(), getCopyFromPartsVector(), getDWordFromOffset(), getGeneralPermuteNode(), getGFNICtrlMask(), llvm::TargetLowering::getNegatedExpression(), getStepVector(), getTargetVShiftNode(), getVectorShuffle(), incDecVectorConstant(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBUILD_VECTOR(), lowerBuildVectorOfConstants(), lowerBuildVectorToBitOp(), LowerBuildVectorv4x32(), lowerBuildVectorViaDominantValues(), lowerBuildVectorViaPacking(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), lowerDisjointIndicesShuffle(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerINT_TO_FP_vXi64(), lowerLaneOp(), lowerMSABinaryBitImmIntr(), lowerMSASplatZExt(), LowerShift(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsSpecificExtension(), lowerShuffleWithPSHUFB(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), lowerSTOREVector(), LowerTruncateVectorStore(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerV16I8Shuffle(), lowerV8I16Shuffle(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), lowerVECTOR_SHUFFLE_VSHUF(), lowerVECTOR_SHUFFLE_XVPERM(), lowerVECTOR_SHUFFLE_XVSHUF(), lowerVECTOR_SHUFFLEAsVRGatherVX(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), NormalizeBuildVector(), packImage16bitOpsToDwords(), padEltsToUndef(), PerformBUILD_VECTORCombine(), performBUILD_VECTORCombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performVECTOR_SHUFFLECombine(), performVSelectCombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReconstructShuffleWithRuntimeMask(), ReorganizeVector(), ReplaceINTRINSIC_W_CHAIN(), replaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::SimplifyDemandedVectorElts(), SkipExtensionForVMULL(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), llvm::AMDGPUTargetLowering::splitVector(), takeInexpensiveLog2(), tryBuildVectorShuffle(), tryToConvertShuffleOfTbl2ToTbl4(), tryToFoldExtendOfConstant(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), widenBuildVec(), widenBuildVector(), and widenVectorToPartType().
getCalledGlobal()
std::optional< CalledGlobalInfo > llvm::SelectionDAG::getCalledGlobal (const SDNode * Node) inline
Return CalledGlobal associated with Node, or a nullopt if none exists.
Definition at line 2583 of file SelectionDAG.h.
References I.
getCALLSEQ_END() [1/2]
SDValue llvm::SelectionDAG::getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc & DL) inline
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
CALLSEQ_END does not have a useful SDLoc.
Definition at line 1161 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::CALLSEQ_END, DL, llvm::SDValue::getNode(), getNode(), and getVTList().
Referenced by getCALLSEQ_END(), GetTLSADDR(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), and PrepareTailCall().
getCALLSEQ_END() [2/2]
SDValue llvm::SelectionDAG::getCALLSEQ_END (SDValue Chain, uint64_t Size1, uint64_t Size2, SDValue Glue, const SDLoc & DL) inline
Definition at line 1173 of file SelectionDAG.h.
References DL, getCALLSEQ_END(), and getIntPtrConstant().
getCALLSEQ_START()
SDValue llvm::SelectionDAG::getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc & DL) inline
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
Definition at line 1149 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::CALLSEQ_START, DL, getIntPtrConstant(), getNode(), and getVTList().
Referenced by GetTLSADDR(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), and llvm::AMDGPUTargetLowering::lowerUnhandledCall().
getCallSiteInfo()
CallSiteInfo llvm::SelectionDAG::getCallSiteInfo (const SDNode * Node) inline
Return CallSiteInfo associated with Node, or a default if none exists.
Definition at line 2545 of file SelectionDAG.h.
References CallSiteInfo, and I.
getCommutedVectorShuffle()
SDValue SelectionDAG::getCommutedVectorShuffle (const ShuffleVectorSDNode & SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
Example: shuffle A, B, <0,5,2,7> -> shuffle B, A, <4,1,6,3>
Definition at line 2357 of file SelectionDAG.cpp.
References llvm::ShuffleVectorSDNode::commuteMask(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), getVectorShuffle(), and Op0.
Referenced by lowerVECTOR_SHUFFLE().
getCondCode()
SDValue SelectionDAG::getCondCode (ISD::CondCode Cond)
Definition at line 2099 of file SelectionDAG.cpp.
References Cond, and N.
Referenced by combine_CC(), combine_CC(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), llvm::TargetLowering::expandVPCTTZElements(), getSelectCC(), getSetCC(), getSetCCVP(), llvm::TargetLowering::LegalizeSetCCCondCode(), lowerBALLOTIntrinsic(), lowerFCMPIntrinsic(), lowerICMPIntrinsic(), LowerTruncatei1(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), LowerVSETCC(), performIntrinsicCombine(), performVSelectCombine(), splitVSETCC(), and tryConvertSVEWideCompare().
getConstant() [1/3]
SDValue SelectionDAG::getConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1666 of file SelectionDAG.cpp.
References DL, and getConstant().
getConstant() [2/3]
SDValue SelectionDAG::getConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1671 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::append_range(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ISD::BITCAST, llvm::ISD::Constant, DL, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::APInt::extractBits(), llvm::ConstantInt::getBitWidth(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getSplat(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), llvm::isa(), isBigEndian(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), N, NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), Opc, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::APInt::sextOrTrunc(), llvm::ISD::SPLAT_VECTOR, llvm::ISD::SPLAT_VECTOR_PARTS, llvm::ISD::TargetConstant, llvm::TargetLoweringBase::TypeExpandInteger, llvm::TargetLoweringBase::TypePromoteInteger, and llvm::APInt::zextOrTrunc().
getConstant() [3/3]
SDValue SelectionDAG::getConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Create a ConstantSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal).
Definition at line 1660 of file SelectionDAG.cpp.
References DL, getConstant(), and llvm::EVT::getScalarSizeInBits().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), adjustForSubtraction(), adjustForTestUnderMask(), adjustICmpTruncate(), AdjustLength(), adjustSubwordCmp(), adjustZeroCmp(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), bitcastf32Toi32(), buildCallOperands(), BuildExactSDIV(), BuildExactUDIV(), BuildIntrinsicOp(), BuildIntrinsicOp(), BuildIntrinsicOp(), llvm::SITargetLowering::buildRSRC(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::buildSDIVPow2WithCMov(), llvm::TargetLowering::BuildUDIV(), canonicalizePRMTInput(), canonicalizeShuffleVectorByLane(), carryFlagToValue(), checkSignTestSetCCCombine(), clampDynamicVectorIndex(), combine_CC(), combine_CC(), combineAcrossLanesIntrinsic(), combineADC(), combineAdd(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineADDToSUB(), combineAnd(), combineAndLoadToBZHI(), combineAndnp(), CombineANDShift(), combineAndXorSubWithBMI(), combineArithReduction(), combineAVG(), combineAVX512SetCCToKMOV(), CombineBaseUpdate(), combineBitcast(), combineBitcastToBoolVector(), combineCarryDiamond(), combineCarryThroughADD(), combineCMov(), combineCMP(), combineCompareEqual(), combineCONCAT_VECTORS(), combineConcatVectorOps(), combineDeMorganOfBoolean(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFP_EXTEND(), combineGatherScatter(), combinei64TruncSrlConstant(), combineI8TruncStore(), combineKSHIFT(), combineM68kBrCond(), combineMinMaxReduction(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineMulToPMADDWD(), combineMulWide(), combineNarrowableShiftedLoad(), combineOr(), combineOrAndToBitfieldInsert(), combineOrToBitfieldInsert(), combinePMULDQ(), combinePredicateReduction(), combinePRMT(), combinePTESTCC(), combineSCALAR_TO_VECTOR(), combineScalarAndWithMaskSetcc(), combineSelect(), llvm::VETargetLowering::combineSelect(), llvm::VETargetLowering::combineSelectCC(), combineSelectOfTwoConstants(), combineSetCC(), combineSetCCAtomicArith(), combineSetCCMOVMSK(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShiftOfShiftedLogic(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShiftToMULH(), combineStore(), combineSub(), combineSubOfBoolean(), combineSubSetcc(), combineSVEReductionFP(), combineSVEReductionInt(), combineSVEReductionOrderedFP(), combineToExtendBoolVectorInReg(), combineTruncOfSraSext(), combineTruncSelectToSMaxUSat(), combineUADDO_CARRYDiamond(), combineV3I8LoadExt(), combineVectorCompare(), combineVectorMulToSraBitcast(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), CombineVMOVDRRCandidateWithVecOp(), combineVPMADD(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), combineX86AddSub(), combineX86ShuffleChain(), combineXorToBitfieldInsert(), constantFoldBFE(), constructDup(), constructRetValue(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), ConvertCarryFlagToCarryValue(), ConvertCarryValueToCarryFlag(), convertFixedMaskToScalableVector(), convertFromF16(), convertFromScalableVector(), ConvertSETCCToXori(), convertShiftLeftToScale(), convertToF16(), convertToScalableVector(), convertTwoLoadsAndCmpToVCMPEQUB(), convertValVTToLocVT(), CreateCopyOfByValArgument(), CreateCopyOfByValArgument(), CreateCopyOfByValArgument(), createFPCmp(), createLoadLR(), createPSADBW(), createSetFPEnvNodes(), createStoreLR(), createVariablePermute(), createVPDPBUSD(), llvm::TargetLowering::CTTZTableLookup(), customLegalizeToWOp(), EltsFromConsecutiveLoads(), EmitCMP(), emitConditionalComparison(), emitConstantSizeRepmov(), emitConstantSizeRepstos(), emitFloatCompareMask(), emitMemMemImm(), emitRestoreZALazySave(), emitSETCC(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::RISCVSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), EmitTest(), emitVectorComparison(), Expand64BitShift(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandBITREVERSE(), llvm::TargetLowering::expandBSWAP(), llvm::TargetLowering::expandCLMUL(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandFP_TO_UINT(), expandFSH64(), llvm::TargetLowering::expandFunnelShift(), llvm::TargetLowering::expandIntMINMAX(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandIS_FPCLASS(), expandMul(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), expandMulToAddOrSubOfShl(), expandMulToNAFSequence(), expandMulToShlAddShlAdd(), llvm::TargetLowering::expandROT(), llvm::TargetLowering::expandRoundInexactToOdd(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandShiftParts(), llvm::TargetLowering::expandShlSat(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorFindLastActive(), llvm::TargetLowering::expandVectorSplice(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPBSWAP(), llvm::TargetLowering::expandVPCTLZ(), llvm::TargetLowering::expandVPCTPOP(), llvm::TargetLowering::expandVPCTTZ(), llvm::TargetLowering::expandVPCTTZElements(), expandVPFunnelShift(), ExtendToType(), extractF64Exponent(), extractShiftForRotate(), fillVector(), finalizeTS1AM(), foldAddSubBoolOfMaskedVal(), foldAndOrOfSETCC(), foldAndToUsubsat(), FoldConstantArithmetic(), FoldConstantBuildVector(), foldCSELofCTTZ(), foldExtendedSignBitTest(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldReduceOperandViaVQDOT(), foldSelectOfConstantsUsingSra(), foldSelectOfCTTZOrCTLZ(), FoldSetCC(), foldSetCCWithFunnelShift(), FoldSTEP_VECTOR(), foldVectorXorShiftIntoCmp(), llvm::TargetLowering::forceExpandMultiply(), llvm::TargetLowering::forceExpandWideMUL(), genConstMult(), generateEquivalentSub(), GenerateFixedLengthSVETBL(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAllOnesConstant(), getARMIndexedAddressParts(), getAVX512Node(), getBitTestCondition(), getBoolConstant(), getBoundedStrlen(), getBuildVectorSplat(), getCanonicalConstSplat(), getCCResult(), getCondCode(), getConstant(), getConstant(), getConstant(), getConstVector(), getConstVector(), llvm::RegsForValue::getCopyFromRegs(), getCSAddressAndShifts(), getDataClassTest(), getDefaultVLOps(), getDeinterleaveShiftAndTrunc(), getDWordFromOffset(), GetExponent(), getFixedOrScalableQuantity(), getFlagsOfCmpZeroFori1(), getGeneralPermuteNode(), getGFNICtrlMask(), llvm::AMDGPUTargetLowering::getHiHalf64(), getIntPtrConstant(), llvm::AMDGPUTargetLowering::getLoHalf64(), getMaskFromElementCount(), getMaskNode(), getMemsetStringVal(), getMemsetValue(), getMVEIndexedAddressParts(), getNegative(), getNeutralElement(), getNode(), getNode(), getNode(), getPack(), getPMOVMSKB(), llvm::AVRTargetLowering::getPostIndexedAddressParts(), getPredicateForScalableVector(), getPRMT(), getPRMT(), getPTest(), getPTrue(), getReductionSDNode(), getScaledOffsetForBitWidth(), getSETCC(), getSETCC(), getShiftAmountConstant(), getShlAddShlAdd(), getShuffleScalarElt(), getSignedConstant(), GetSignificand(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getStepVector(), getSVEPredicateBitCast(), getT2IndexedAddressParts(), getTargetConstant(), getTargetConstant(), getTargetConstant(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getTruncatedUSUBSAT(), getUniformBase(), getVectorBitwiseReduce(), getVectorIdxConstant(), llvm::TargetLowering::getVectorSubVecPointer(), getVPZeroExtendInReg(), getVScale(), getWideningInterleave(), getWideningSpread(), getZeroExtendInReg(), getZeroVector(), getzOSCalleeAndADA(), incDecVectorConstant(), llvm::TargetLowering::IncrementMemoryAddress(), insert1BitVector(), IntCondCCodeToICC(), isConditionalZeroOrAllOnes(), isConditionalZeroOrAllOnes(), IsSingleInstrConstant(), legalizeIntrinsicImmArg(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), LowerABS(), lowerAddrSpaceCast(), LowerADDSAT_SUBSAT(), LowerAndToBT(), LowerAndToBTST(), LowerAsSplatVectorLoad(), LowerATOMIC_FENCE(), LowerAVXExtend(), lowerBALLOTIntrinsic(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBitreverseShuffle(), llvm::LanaiTargetLowering::LowerBR_CC(), LowerBR_CC(), lowerBSWAP(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORToVIDUP(), LowerBUILD_VECTORvXi1(), lowerBuildVectorOfConstants(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), LowerBuildVectorv16i8(), lowerBuildVectorViaPacking(), lowerBuildVectorViaVID(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), lowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), llvm::AMDGPUTargetLowering::lowerCTLZResults(), LowerCTPOP(), LowerCTPOP(), LowerCTTZ(), lowerCttzElts(), lowerCvtRSIntrinsics(), lowerDisjointIndicesShuffle(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), llvm::AMDGPUTargetLowering::LowerF64ToF16Safe(), lowerFABSorFNEG(), lowerFCOPYSIGN(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::lowerFEXP(), LowerFGETSIGN(), LowerFLDEXP(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), LowerFMINIMUM_FMAXIMUM(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP16_TO_FP(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), LowerFP_TO_INT_SAT(), lowerFP_TO_INT_SAT(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), LowerFunnelShift(), llvm::SITargetLowering::lowerGET_ROUNDING(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerGR128ToI128(), LowerHorizontalByteSum(), lowerI128ToGR128(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), LowerLabelRef(), lowerLaneOp(), llvm::MipsTargetLowering::lowerLOAD(), lowerLoadF128(), lowerLoadI1(), LowerMemOpCallTo(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSASplatImm(), lowerMSASplatZExt(), llvm::LanaiTargetLowering::LowerMUL(), LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), LowerMULO(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), lowerOverflowArithmetic(), LowerPARITY(), LowerPredicateLoad(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerPREFETCH(), LowerPREFETCH(), lowerPrmtIntrinsic(), lowerReductionSeq(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerRotate(), LowerSaturatingConditional(), lowerScalarInsert(), lowerScalarSplat(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), LowerSELECTWithCmpZero(), llvm::SITargetLowering::lowerSET_FPENV(), llvm::SITargetLowering::lowerSET_ROUNDING(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsSpecificExtension(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleWithEXPAND(), lowerShuffleWithPSHUFB(), LowerSIGN_EXTEND_Mask(), LowerSMELdrStr(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerSTACKADDRESS(), llvm::NVPTXTargetLowering::LowerSTACKSAVE(), lowerStoreF128(), lowerStoreI1(), LowerSVEIntrinsicEXT(), LowerTruncatei1(), LowerTruncateVecI1(), LowerTruncateVectorStore(), LowerUADDSUBO_CARRY(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16I8Shuffle(), lowerV8I16Shuffle(), llvm::VETargetLowering::lowerVAARG(), LowerVecReduce(), LowerVecReduceMinMax(), lowerVECTOR_COMPRESS(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_IsReverse(), lowerVECTOR_SHUFFLE_VREPLVEI(), lowerVECTOR_SHUFFLE_VSHUF4I(), lowerVECTOR_SHUFFLE_XVINSVE0(), lowerVECTOR_SHUFFLE_XVPERM(), lowerVECTOR_SHUFFLE_XVPERMI(), lowerVECTOR_SHUFFLE_XVREPLVEI(), lowerVECTOR_SHUFFLEAsByteRotate(), lowerVECTOR_SHUFFLEAsRotate(), lowerVECTOR_SHUFFLEAsShift(), lowerVECTOR_SHUFFLEAsVRGatherVX(), lowerVECTOR_SHUFFLEAsVSlidedown(), lowerVECTOR_SHUFFLEAsVSlideup(), lowerVECTOR_SHUFFLEAsZeroOrAnyExtend(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVectorAllEqual(), lowerVectorBitClear(), lowerVectorBitClearImm(), lowerVectorBitRevImm(), lowerVectorBitSetImm(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZ_GFNI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), lowerVectorIntrinsicScalars(), LowerVectorMatch(), lowerVectorPickVE2GR(), lowerVectorSplatImm(), LowerVSETCC(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowervXi8MulWithUNPCK(), lowerVZIP(), lowerWaveShuffle(), lowerX86CmpEqZeroToCtlzSrl(), LowerXALUO(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), matchMergedBFX(), matchPERM(), matchPMADDWD(), MatchVectorAllEqualTest(), memsetStore(), narrowBitOpRMW(), narrowIndex(), NormalizeBuildVector(), optimizeIncrementingWhile(), optimizeLogicalImm(), overflowFlagToValue(), llvm::SITargetLowering::passSpecialInputs(), performAddCSelIntoCSinc(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performAddSubIntoVectorOp(), performAddUADDVCombine(), performANDCombine(), performANDCombine(), performANDCombine(), performANDORCSELCombine(), performANDSCombine(), performANDSETCCCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), performBitcastCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performCONCAT_VECTORSCombine(), performConcatVectorsCombine(), performCONDCombine(), performConvertFPCombine(), PerformCSETCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDSPShiftCombine(), performDUPCombine(), performExtBinopLoadFold(), PerformEXTRACTCombine(), PerformExtractEltCombine(), PerformExtractEltToVMOVRRD(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFirstTrueTestVectorCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFP_TO_INT_SATCombine(), performGlobalAddressCombine(), performInsertSubvectorCombine(), performInterleavedMaskedStoreCombine(), performINTRINSIC_WO_CHAINCombine(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), performLastTrueTestVectorCombine(), performLDNT1Combine(), PerformLongShiftCombine(), PerformMinMaxCombine(), PerformMinMaxToSatCombine(), PerformMULCombine(), performMulCombine(), performMulRdsvlCombine(), performMulVectorCmpZeroCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), performORCombine(), performORCombine(), PerformORCombineToBFI(), PerformPREDICATE_CASTCombine(), performRNDRCombine(), performScalarToVectorCombine(), performSELECT_CCCombine(), performSetccAddFolding(), performSETCCCombine(), performSETCCCombine(), PerformShiftCombine(), performSHLCombine(), performSHLCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), PerformSHLSimplify(), PerformShuffleVMOVNCombine(), performSignExtendCombine(), performSPLIT_PAIR_F64Combine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSRACombine(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRLCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), PerformSTORECombine(), performSTORECombine(), PerformSUBCombine(), performSUBCombine(), performSubsToAndsCombine(), performSubWithBorrowCombine(), performSVEAndCombine(), performTBZCombine(), performTruncateCombine(), PerformTruncatingStoreCombine(), performUnpackCombine(), performUzpCombine(), performVANDNCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDUPCombine(), performVecReduceAddCombine(), performVecReduceAddCombineWithUADDLP(), performVECTOR_SHUFFLECombine(), performVectorDeinterleaveCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), PerformVMulVCTPCombine(), performVP_REVERSECombine(), performVP_STORECombine(), PerformVSELECTCombine(), performVSelectCombine(), PerformVSetCCToVCTPCombine(), PerformXORCombine(), performXORCombine(), performZExtDeinterleaveShuffleCombine(), performZExtUZPCombine(), prepareTS1AM(), promoteExtBeforeAdd(), reassociateCSELOperandsForCSE(), llvm::AArch64TargetLowering::ReconstructShuffle(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), refineUniformBase(), ReplaceBITCAST(), replaceLoadVector(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), replaceVPICKVE2GRResults(), resolveSources(), reverseZExtICmpCombine(), SaturateWidenedDIVFIX(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::TargetLowering::ShrinkDemandedConstant(), simplifyAssumingCCVal(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::LoongArchTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyDivRem(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCIntoEq(), simplifySetCCWithCTPOP(), simplifyShift(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), llvm::AMDGPUTargetLowering::split64BitValue(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), splitStores(), splitStoreSplat(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::AMDGPUTargetLowering::splitVector(), llvm::AMDGPUTargetLowering::storeStackInputValue(), takeInexpensiveLog2(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), transformAddShlImm(), TranslateM68kCC(), translateSetCCForBranch(), translateSetCCForBranch(), TranslateX86CC(), truncateVecElts(), truncateVecElts(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), TryCombineBaseUpdate(), tryCombineMULLWithUZP1(), tryCombineShiftImm(), tryConvertSVEWideCompare(), tryDemorganOfBooleanCondition(), tryExtendDUPToExtractHigh(), tryFoldMADwithSRL(), tryFoldSelectIntoOp(), tryFoldToZero(), tryFormConcatFromShuffle(), tryLowerSmallVectorExtLoad(), TryMULWIDECombine(), trySVESplat64(), tryToConvertShuffleOfTbl2ToTbl4(), tryToFoldExtendOfConstant(), UnpackFromArgumentSlot(), UnrollVectorOverflowOp(), unrollVectorShift(), valueToCarryFlag(), vectorToScalarBitmask(), llvm::X86TargetLowering::visitMaskedLoad(), widenBuildVec(), WidenVector(), and widenVectorOpsToi8().
getConstantDbgValue()
SDDbgValue * SelectionDAG::getConstantDbgValue (DIVariable * Var, DIExpression * Expr, const Value * C, const DebugLoc & DL, unsigned O)
Creates a constant SDDbgValue node.
Constant.
Definition at line 11963 of file SelectionDAG.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), DL, and llvm::SDDbgOperand::fromConst().
getConstantFP() [1/3]
SDValue SelectionDAG::getConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1823 of file SelectionDAG.cpp.
References DL, getConstantFP(), and getContext().
getConstantFP() [2/3]
SDValue SelectionDAG::getConstantFP (const ConstantFP & V, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1828 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::ConstantFP, DL, getContext(), llvm::EVT::getScalarType(), getSplat(), llvm::Value::getType(), llvm::ConstantFP::getValue(), getVTList(), llvm::isa(), llvm::EVT::isFloatingPoint(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), Opc, and llvm::ISD::TargetConstantFP.
getConstantFP() [3/3]
SDValue SelectionDAG::getConstantFP (double Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Create a ConstantFPSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal). The forms that take a double should only be used for simple constants that can be exactly represented in VT. No checks are made.
Definition at line 1867 of file SelectionDAG.cpp.
References llvm::APFloat::convert(), DL, getConstantFP(), llvm::EVT::getFltSemantics(), llvm::EVT::getScalarType(), llvm_unreachable, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by combineBitcast(), combineExtractWithShuffle(), combineFneg(), combineFP_ROUND(), combineVSelectWithAllOnesOrZeros(), EltsFromConsecutiveLoads(), expandExp(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::TargetLowering::expandFP_TO_UINT(), expandFP_TO_UINT_SSE(), llvm::TargetLowering::expandIS_FPCLASS(), expandLog(), ExpandPowI(), llvm::TargetLowering::expandUINT_TO_FP(), FoldConstantArithmetic(), foldConstantFPMath(), foldFPToIntToFP(), getConstantFP(), getConstantFP(), getF32Constant(), getInvertedVectorForFMA(), llvm::AMDGPUTargetLowering::getIsFinite(), llvm::AMDGPUTargetLowering::getIsLtSmallestNormal(), getMemsetValue(), llvm::TargetLowering::getNegatedExpression(), getNeutralElement(), getNode(), getNode(), getRVVFPReductionOpAndOperands(), llvm::AMDGPUTargetLowering::getScaledLogInput(), getShuffleScalarElt(), llvm::TargetLowering::getSqrtInputTest(), llvm::TargetLowering::getSqrtResultForDenormInput(), getTargetConstantFP(), getTargetConstantFP(), getTargetConstantFP(), getZeroVector(), LowerFABSorFNEG(), LowerFCanonicalize(), llvm::AMDGPUTargetLowering::LowerFCEIL(), LowerFCOPYSIGN(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP10Unsafe(), llvm::AMDGPUTargetLowering::lowerFEXP2(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafe(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafeImpl(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::AMDGPUTargetLowering::LowerFLOG2(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), llvm::AMDGPUTargetLowering::LowerFLOGUnsafe(), LowerFMINIMUM_FMAXIMUM(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), lowerFREM(), llvm::AMDGPUTargetLowering::LowerFROUND(), LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerShuffleAsBitMask(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performInsertSubvectorCombine(), llvm::AMDGPUTargetLowering::performRcpCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyFPBinop(), and strictFPExtFromF16().
getConstantPool() [1/2]
SDValue SelectionDAG::getConstantPool (const Constant * C, EVT VT, MaybeAlign Align = std::nullopt, int Offs = 0, bool isT = false, unsigned TargetFlags = 0)
Definition at line 1977 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::CallingConv::C, llvm::ISD::ConstantPool, llvm::DataLayout::getABITypeAlign(), getDataLayout(), llvm::DataLayout::getPrefTypeAlign(), getVTList(), N, NewSDValueDbgMsg(), llvm::Offset, Opc, shouldOptForSize(), and llvm::ISD::TargetConstantPool.
Referenced by combineConcatVectorOps(), combineTargetShuffle(), llvm::TargetLowering::CTTZTableLookup(), getAddressForMemoryInput(), getTargetConstantPool(), getTargetConstantPool(), lowerBuildVectorAsBroadcast(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle().
getConstantPool() [2/2]
SDValue SelectionDAG::getConstantPool (MachineConstantPoolValue * C, EVT VT, MaybeAlign Align = std::nullopt, int Offs = 0, bool isT = false, unsigned TargetFlags = 0)
Definition at line 2007 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::CallingConv::C, llvm::ISD::ConstantPool, getDataLayout(), llvm::DataLayout::getPrefTypeAlign(), getVTList(), N, llvm::Offset, Opc, and llvm::ISD::TargetConstantPool.
getContext()
LLVMContext * llvm::SelectionDAG::getContext () const inline
Definition at line 511 of file SelectionDAG.h.
Referenced by AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), addShuffleForVecExtend(), adjustLoadValueTypeImpl(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::buildSDIVPow2WithCMov(), llvm::TargetLowering::BuildUDIV(), BuildVectorFromScalar(), canCombineShuffleToExtendVectorInreg(), canFoldInAddressingMode(), checkIntrinsicImmArg(), CollectOpsToWiden(), combineAdd(), combineAnd(), combineAndShuffleNot(), combineArithReduction(), combineBasicSADPattern(), combineBinOpOfExtractToReduceTree(), combineBinOpOfZExt(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBoolVectorAndTruncateStore(), combineCMP(), combineCONCAT_VECTORS(), combineConcatVectorOfCasts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineEXTEND_VECTOR_INREG(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFMinNumFMaxNum(), combineFP_EXTEND(), combineFP_ROUND(), combineGatherScatter(), combinei64TruncSrlConstant(), combineI8TruncStore(), combineLoad(), combineMinNumMaxNumImpl(), combineMulToPMADDWD(), combineOr(), combinePMULH(), combinePredicateReduction(), combineScalarAndWithMaskSetcc(), combineSelect(), combineShiftAnd1ToBitTest(), combineShiftToAVG(), combineShiftToMULH(), combineShuffleToZeroExtendVectorInReg(), combineSIntToFP(), combineStore(), combineStoreValueFPToInt(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToFPTruncExtElt(), combineTruncateWithSat(), combineUIntToFP(), combineV3I8LoadExt(), combineVectorMulToSraBitcast(), combineVectorSizedSetCCEquality(), CombineVMOVDRRCandidateWithVecOp(), combineVPDPBUSDPattern(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), concatSubVectors(), constructRetValue(), convertIntLogicToFPLogic(), createPSADBW(), CreateStackTemporary(), CreateStackTemporary(), llvm::TargetLowering::CTTZTableLookup(), detectPMADDUBSW(), DoubleVectorWidth(), earlyExpandDIVFIX(), EltsFromConsecutiveLoads(), emitErrorAndReplaceIntrinsicResults(), emitFloatCompareMask(), emitIntrinsicErrorMessage(), emitIntrinsicWithChainErrorMessage(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), emitSMEStateSaveRestore(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), emitVectorComparison(), errorUnsupported(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandCLMUL(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandIntMINMAX(), llvm::TargetLowering::expandIS_FPCLASS(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::TargetLowering::expandPartialReduceMLA(), llvm::TargetLowering::expandRoundInexactToOdd(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandShiftParts(), llvm::TargetLowering::expandShlSat(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), llvm::TargetLowering::expandVecReduce(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorFindLastActive(), llvm::TargetLowering::expandVectorSplice(), llvm::TargetLowering::expandVPCTPOP(), llvm::TargetLowering::expandVPCTTZElements(), extractSubVector(), extractSubVector(), fail(), findMemType(), findMoreOptimalIndexType(), FoldConstantArithmetic(), FoldConstantBuildVector(), foldExtendVectorInregToExtendOfSubvector(), foldShuffleOfConcatUndefs(), foldXorTruncShiftIntoCmp(), llvm::TargetLowering::forceExpandWideMUL(), GenerateFixedLengthSVETBL(), getAtomicMemcpy(), getAtomicMemmove(), getAtomicMemset(), getBuildVectorizedValue(), getConstant(), getConstantFP(), getConstantFP(), getCopyFromParts(), getCopyFromPartsVector(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), GetDependentSplitDestVTs(), getEVTAlign(), llvm::AMDGPUTargetLowering::getIsFinite(), llvm::AMDGPUTargetLowering::getIsLtSmallestNormal(), getLargeExternalSymbol(), getMaskFromElementCount(), getMemcmp(), getMemcpy(), getMemcpyLoadsAndStores(), getMemmove(), getMemmoveLoadsAndStores(), getMemset(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getPredicateForScalableVector(), getPrefTypeAlign(), getPrefTypeAlign(), getPTest(), getReducedAlign(), getRegistersForValue(), llvm::AMDGPUTargetLowering::getScaledLogInput(), getSplatValue(), GetSplitDestVTs(), llvm::AMDGPUTargetLowering::getSplitDestVTs(), llvm::TargetLowering::getSqrtInputTest(), getStrcpy(), getStrlen(), GetTLSADDR(), getUniformBase(), getVectorBitwiseReduce(), llvm::TargetLowering::getVectorElementPointer(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), isSaturatingMinMax(), isUpperSubvectorUndef(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), legalizeIntrinsicImmArg(), legalizeScatterGatherIndexType(), LowerADDSAT_SUBSAT(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerAsSplatVectorLoad(), lowerBitreverseShuffle(), lowerBuildVectorAsBroadcast(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP10Unsafe(), llvm::AMDGPUTargetLowering::lowerFEXP2(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafe(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFLDEXP(), LowerFMINIMUM_FMAXIMUM(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerICMPIntrinsic(), lowerLaneOp(), LowerMSCATTER(), LowerMULO(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::NVPTXTargetLowering::LowerSTACKRESTORE(), llvm::NVPTXTargetLowering::LowerSTACKSAVE(), LowerStore(), lowerSTOREVector(), LowerSVEIntrinsicEXT(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToVVP(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVECTOR_SHUFFLE(), LowerVectorAllEqual(), lowerVectorBitClearImm(), lowerVectorBitRevImm(), lowerVectorBitSetImm(), LowerVectorExtend(), lowerVectorPickVE2GR(), lowerVectorSplatImm(), LowerVSETCC(), llvm::VETargetLowering::lowerVVP_LOAD_STORE(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::TargetLowering::makeLibCall(), makeStateFunctionCall(), matchBinOpReduction(), matchPMADDWD(), matchPMADDWD_2(), narrowExtractedVectorBinOp(), narrowIndex(), performActiveLaneMaskCombine(), PerformARMBUILD_VECTORCombine(), performBITCASTCombine(), PerformBUILD_VECTORCombine(), performBuildShuffleExtendCombine(), performBuildVectorCombine(), performConcatVectorsCombine(), performConvertFPCombine(), performCTPOPCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDUPCombine(), performExtBinopLoadFold(), PerformExtractFpToIntStores(), PerformInsertEltCombine(), performLOADCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformMinMaxFpToSatCombine(), performMSTORECombine(), performMulVectorCmpZeroCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), performSelectCombine(), performSETCC_BITCASTCombine(), performSETCCCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSignExtendInRegCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), performSunpkloCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformTruncatingStoreCombine(), performUADDVZextCombine(), PerformUMinFpToSatCombine(), performUnpackCombine(), performUzpCombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), performVECTOR_SHUFFLECombine(), performVectorExtCombine(), PromoteBinOpToF32(), llvm::TargetLoweringBase::promoteTargetBoolean(), promoteToConstantPool(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), replaceAtomicSwap128(), replaceLoadVector(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceProxyReg(), reportInvalidTensormapReplaceUsage(), reverseZExtICmpCombine(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), shouldTransformMulToShiftsAddsSubs(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), skipExtensionForVectorMULL(), llvm::TargetLowering::softenSetCCOperands(), splitStores(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), splitVector(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateVectorWithNARROW(), truncateVectorWithPACK(), tryCombineMULLWithUZP1(), tryFormConcatFromShuffle(), tryToReplaceScalarFPConversionWithSVE(), tryToWidenSetCCOperands(), UnrollVectorOp(), UnrollVectorOverflowOp(), widenAbs(), widenBuildVec(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), widenVec(), WidenVector(), widenVectorOpsToi8(), and widenVectorToPartType().
getCopyFromReg() [1/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, Register Reg, EVT VT) inline
Definition at line 844 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::CopyFromReg, getNode(), getRegister(), getVTList(), and Reg.
Referenced by llvm::AArch64TargetLowering::changeStreamingMode(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), emitSMEStateSaveRestore(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyFromRegs(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), getReadTimeStampCounter(), GetTLSADDR(), getv64i1Argument(), getzOSCalleeAndADA(), llvm::SystemZTargetLowering::LowerAsmOutputForConstraint(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), lowerBALLOTIntrinsic(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), lowerCallResult(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSTACKADDRESS(), llvm::SITargetLowering::LowerSTACKSAVE(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), performDivRemCombine(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceZeroVectorStore(), llvm::AMDGPUTargetLowering::storeStackInputValue(), unpack64(), unpackF64OnLA32DSoftABI(), unpackF64OnRV32DSoftABI(), unpackFromRegLoc(), unpackFromRegLoc(), and unpackFromRegLoc().
getCopyFromReg() [2/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, Register Reg, EVT VT, SDValue Glue) inline
Definition at line 853 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ArrayRef(), llvm::ISD::CopyFromReg, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), and Reg.
getCopyToReg() [1/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, Register Reg, SDValue N) inline
Definition at line 818 of file SelectionDAG.h.
References llvm::ISD::CopyToReg, getNode(), getRegister(), N, and Reg.
Referenced by emitRepmovs(), emitRepstos(), emitRestoreZALazySave(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyToRegs(), llvm::MipsTargetLowering::getOpndList(), GetTLSADDR(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SelectionDAGBuilder::LowerCallTo(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::SITargetLowering::PostISelFolding(), prepareDescriptorIndirectCall(), and llvm::X86TargetLowering::ReplaceNodeResults().
getCopyToReg() [2/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, Register Reg, SDValue N, SDValue Glue) inline
Definition at line 827 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ArrayRef(), llvm::ISD::CopyToReg, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), N, and Reg.
getCopyToReg() [3/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, SDValue Reg, SDValue N, SDValue Glue) inline
Definition at line 836 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ArrayRef(), llvm::ISD::CopyToReg, llvm::SDValue::getNode(), getNode(), getVTList(), N, and Reg.
getDataLayout()
const DataLayout & llvm::SelectionDAG::getDataLayout () const inline
Definition at line 498 of file SelectionDAG.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addShuffleForVecExtend(), analyzeCallOperands(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), BuildExactUDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::buildSDIVPow2WithCMov(), llvm::TargetLowering::BuildUDIV(), canCombineShuffleToExtendVectorInreg(), canFoldInAddressingMode(), combineBVOfVecSExt(), combineConcatVectorOps(), combineFMinNumFMaxNum(), combineGatherScatter(), combineLoad(), combinePredicateReduction(), combineShiftAnd1ToBitTest(), combineShuffleToAnyExtendVectorInreg(), combineShuffleToZeroExtendVectorInReg(), combineStore(), combineTargetShuffle(), combineTruncationShuffle(), combineVSelectWithAllOnesOrZeros(), computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), ComputeNumSignBits(), createGPRPairNode(), createGPRPairNodei64(), createMMXBuildVector(), createSetFPEnvNodes(), CreateStackTemporary(), CreateStackTemporary(), CreateStackTemporary(), llvm::TargetLowering::CTTZTableLookup(), EltsFromConsecutiveLoads(), emitRestoreZALazySave(), emitSMEStateSaveRestore(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandBITREVERSE(), llvm::TargetLowering::expandBSWAP(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandIntMINMAX(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::TargetLowering::expandRoundInexactToOdd(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandShiftParts(), llvm::TargetLowering::expandShlSat(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), expandVACopy(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPBSWAP(), llvm::TargetLowering::expandVPCTLZ(), llvm::TargetLowering::expandVPCTPOP(), FoldConstantArithmetic(), FoldConstantBuildVector(), foldXorTruncShiftIntoCmp(), llvm::TargetLowering::forceExpandWideMUL(), getADAEntry(), getAddressForMemoryInput(), getAtomicMemcpy(), getAtomicMemmove(), getAtomicMemset(), getAVX2GatherNode(), getConstant(), getConstantPool(), getConstantPool(), getCopyFromParts(), getCopyToParts(), getEVTAlign(), getGatherNode(), getGlobalAddress(), getIntPtrConstant(), llvm::AMDGPUTargetLowering::getIsFinite(), llvm::AMDGPUTargetLowering::getIsLtSmallestNormal(), getJumpTableDebugInfo(), getLifetimeNode(), getLoadStackGuard(), getMaskFromElementCount(), getMemcmp(), getMemcpy(), getMemcpyLoadsAndStores(), getMemmove(), getMemmoveLoadsAndStores(), getMemset(), getMemsetStores(), getMemsetStringVal(), getNode(), getNode(), llvm::M68kTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), getPPCf128HiElementSelector(), getPrefetchNode(), getPrefTypeAlign(), getPrefTypeAlign(), getReducedAlign(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::AMDGPUTargetLowering::getScaledLogInput(), getScatterNode(), getShiftAmountConstant(), getShiftAmountOperand(), llvm::PPC::getSplatIdxForPPCMnemonics(), llvm::TargetLowering::getSqrtInputTest(), getStrcpy(), getStrlen(), getSymbolFunctionGlobalAddress(), getTagSymNode(), getUniformBase(), getVectorIdxConstant(), getzOSCalleeAndADA(), getZT0FrameIndex(), InferPtrAlign(), isBLACompatibleAddress(), isExtendedBUILD_VECTOR(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), IsPredicateKnownToFail(), llvm::PPC::isVMRGEOShuffleMask(), llvm::PPC::isVMRGHShuffleMask(), llvm::PPC::isVMRGLShuffleMask(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), llvm::PPC::isVSLDOIShuffleMask(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerBlockAddress(), lowerBuildVectorAsBroadcast(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::LanaiTargetLowering::LowerConstantPool(), LowerCTPOP(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerF64Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP10Unsafe(), llvm::AMDGPUTargetLowering::lowerFEXP2(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafe(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFMINIMUM_FMAXIMUM(), LowerFNEGorFABS(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), LowerMemOpCallTo(), LowerMULO(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerPredicateStore(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), LowerRETURNADDR(), llvm::NVPTXTargetLowering::LowerSTACKRESTORE(), llvm::NVPTXTargetLowering::LowerSTACKSAVE(), LowerSTORE(), lowerSTOREVector(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), LowerVASTART(), LowerVASTART(), LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::SparcTargetLowering::makeAddress(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::TargetLowering::makeLibCall(), makeStateFunctionCall(), matchPERM(), narrowExtractedVectorLoad(), PerformBITCASTCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performLOADCombine(), performMULCombine(), PerformSTORECombine(), performSTORECombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformTruncatingStoreCombine(), performUzpCombine(), PerformVMOVRRDCombine(), llvm::TargetLoweringBase::promoteTargetBoolean(), promoteToConstantPool(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceBuildVecToShuffleWithZero(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceLoadVector(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifySetCC(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), transformCallee(), unpackFromMemLoc(), unpackFromMemLoc(), unpackFromMemLoc(), UnrollVectorOverflowOp(), vectorToScalarBitmask(), llvm::SDNodeInfo::verifyNode(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getDbgLabel()
SDDbgLabel * SelectionDAG::getDbgLabel (DILabel * Label, const DebugLoc & DL, unsigned O)
Creates a SDDbgLabel node.
Definition at line 12241 of file SelectionDAG.cpp.
References assert(), llvm::cast(), and DL.
getDbgValue()
SDDbgValue * SelectionDAG::getDbgValue (DIVariable * Var, DIExpression * Expr, SDNode * N, unsigned R, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a SDDbgValue node.
getDbgValue - Creates a SDDbgValue node.
SDNode
Definition at line 11951 of file SelectionDAG.cpp.
References assert(), llvm::cast(), DL, llvm::SDDbgOperand::fromNode(), and N.
getDbgValueList()
SDDbgValue * SelectionDAG::getDbgValueList (DIVariable * Var, DIExpression * Expr, ArrayRef< SDDbgOperand > Locs, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc & DL, unsigned O, bool IsVariadic)
Creates a SDDbgValue node from a list of locations.
Definition at line 12013 of file SelectionDAG.cpp.
References assert(), llvm::cast(), and DL.
Referenced by handleDanglingVariadicDebugInfo(), salvageDebugInfo(), and transferDbgValues().
GetDbgValues()
ArrayRef< SDDbgValue * > llvm::SelectionDAG::GetDbgValues (const SDNode * SD) const inline
Get the debug values which reference the given SDNode.
Definition at line 2010 of file SelectionDAG.h.
Referenced by ProcessSDDbgValues(), salvageDebugInfo(), and transferDbgValues().
getDeactivationSymbol()
SDValue SelectionDAG::getDeactivationSymbol (const GlobalValue * GV)
Definition at line 1919 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::DEACTIVATION_SYMBOL, getVTList(), and N.
getDenormalMode()
DenormalMode llvm::SelectionDAG::getDenormalMode (EVT VT) const inline
Return the current function's default denormal handling kind for the given floating point type.
Definition at line 2605 of file SelectionDAG.h.
References llvm::EVT::getFltSemantics().
GetDependentSplitDestVTs()
std::pair< EVT, EVT > SelectionDAG::GetDependentSplitDestVTs (const EVT & VT, const EVT & EnvVT, bool * HiIsEmpty) const
Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
GetDependentSplitDestVTs - Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
Sets the HisIsEmpty flag when hi type has zero storage size.
Sets the HiIsEmpty flag when hi type has zero storage size.
Definition at line 13660 of file SelectionDAG.cpp.
References assert(), getContext(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorVT(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
getEHLabel()
SDValue SelectionDAG::getEHLabel (const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 2397 of file SelectionDAG.cpp.
References llvm::ISD::EH_LABEL, and getLabelNode().
getElementCount()
SDValue SelectionDAG::getElementCount (const SDLoc & DL, EVT VT, ElementCount EC)
Definition at line 2142 of file SelectionDAG.cpp.
References DL, and getFixedOrScalableQuantity().
Referenced by llvm::RISCVTargetLowering::computeVLMax(), getMaskFromElementCount(), lowerCttzElts(), lowerVECTOR_SHUFFLE(), performActiveLaneMaskCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), and SplitEVL().
getEntryNode()
SDValue llvm::SelectionDAG::getEntryNode () const inline
Return the token chain corresponding to the entry of the function.
Definition at line 581 of file SelectionDAG.h.
Referenced by llvm::AMDGPUTargetLowering::addTokenForArgument(), clear(), combineConcatVectorOps(), combineTargetShuffle(), copyExtraInfo(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegisterRaw(), llvm::TargetLowering::CTTZTableLookup(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorSplice(), getADAEntry(), llvm::MipsTargetLowering::getAddrLocal(), getFLUSHW(), getFRAMEADDR(), getLargeExternalSymbol(), getLargeGlobalAddress(), getStackArgumentTokenFactor(), GetTLSADDR(), getzOSCalleeAndADA(), HandleMergeInputChains(), llvm::AMDGPUTargetLowering::loadStackInputValue(), lowerBALLOTIntrinsic(), lowerBuildVectorAsBroadcast(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFCanonicalize(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), llvm::TargetLowering::makeLibCall(), performDivRemCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::SITargetLowering::PostISelFolding(), promoteXINT_TO_FP(), llvm::SITargetLowering::ReplaceNodeResults(), replaceZeroVectorStore(), SelectionDAG(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle().
getEVTAlign()
Align SelectionDAG::getEVTAlign (EVT MemoryVT) const
Compute the default alignment value for the given type.
Definition at line 1352 of file SelectionDAG.cpp.
References llvm::PointerType::get(), llvm::DataLayout::getABITypeAlign(), getContext(), getDataLayout(), and llvm::EVT::getTypeForEVT().
Referenced by getLoad(), getLoadStackGuard(), getLoadVP(), getMemIntrinsicNode(), getStore(), getTruncStore(), llvm::NVPTXTargetLowering::LowerCall(), and lowerMSTORE().
getExternalSymbol() [1/2]
SDValue SelectionDAG::getExternalSymbol (const char * Sym, EVT VT)
Definition at line 2061 of file SelectionDAG.cpp.
References getVTList(), and N.
Referenced by emitSMEStateSaveRestore(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMultipleResultFPLibCall(), getAtomicMemcpy(), getAtomicMemmove(), getAtomicMemset(), getExternalSymbol(), getMemcmp(), getMemcpy(), getMemmove(), getMemset(), getStrcpy(), getStrlen(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::TargetLowering::makeLibCall(), and makeStateFunctionCall().
getExternalSymbol() [2/2]
SDValue SelectionDAG::getExternalSymbol (RTLIB::LibcallImpl LCImpl, EVT VT)
Definition at line 2069 of file SelectionDAG.cpp.
References llvm::StringRef::data(), and getExternalSymbol().
getExtLoad() [1/2]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand * MMO)
Definition at line 9921 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
getExtLoad() [2/2]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 9910 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
Referenced by adjustSubwordCmp(), combineEXTEND_VECTOR_INREG(), combineLoad(), llvm::TargetLowering::CTTZTableLookup(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getMemcpyLoadsAndStores(), lowerLOADi1(), LowerPredicateLoad(), lowerVECTOR_SHUFFLE(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtractVectorEltCombine(), performFPExtendCombine(), performLOADCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), PerformVMOVrhCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), llvm::TargetLowering::scalarizeVectorLoad(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), unpackFromMemLoc(), unpackFromMemLoc(), unpackFromMemLoc(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getExtLoadVP() [1/2]
SDValue SelectionDAG::getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 10152 of file SelectionDAG.cpp.
References getLoadVP(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
getExtLoadVP() [2/2]
SDValue SelectionDAG::getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, bool IsExpanding = false)
Definition at line 10139 of file SelectionDAG.cpp.
References getLoadVP(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
getExtOrTrunc() [1/2]
SDValue llvm::SelectionDAG::getExtOrTrunc (bool IsSigned, SDValue Op, const SDLoc & DL, EVT VT) inline
Convert Op, which must be of integer type, to the integer type VT, by either sign/zero-extending (depending on IsSigned) or truncating it.
Definition at line 1046 of file SelectionDAG.h.
References DL, getSExtOrTrunc(), and getZExtOrTrunc().
getExtOrTrunc() [2/2]
SDValue llvm::SelectionDAG::getExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT, unsigned Opcode) inline
Convert Op, which must be of integer type, to the integer type VT, by either any/sign/zero-extending (depending on IsAny / IsSigned) or truncating it.
Definition at line 1030 of file SelectionDAG.h.
References llvm::ISD::ANY_EXTEND, DL, getAnyExtOrTrunc(), getSExtOrTrunc(), getZExtOrTrunc(), llvm_unreachable, llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
Referenced by combineShiftToAVG(), combineShiftToMULH(), earlyExpandDIVFIX(), expandDivFix(), LowerShift(), and PerformMinMaxFpToSatCombine().
getExtractSubvector()
SDValue llvm::SelectionDAG::getExtractSubvector (const SDLoc & DL, EVT VT, SDValue Vec, unsigned Idx) inline
Return the VT typed sub-vector of Vec at Idx.
Definition at line 968 of file SelectionDAG.h.
References DL, llvm::ISD::EXTRACT_SUBVECTOR, getNode(), and getVectorIdxConstant().
Referenced by combineBinOpOfExtractToReduceTree(), convertFromScalableVector(), llvm::TargetLowering::expandPartialReduceMLA(), extractSubVector(), getZeroPaddedAdd(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), lowerBitreverseShuffle(), lowerBUILD_VECTOR(), lowerBuildVectorOfConstants(), LowerFLDEXP(), lowerScalarInsert(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLEAsVSlidedown(), lowerVZIP(), matchBinOpReduction(), matchSplatAsGather(), llvm::RISCVTargetLowering::PerformDAGCombine(), and SplitVector().
getExtractVectorElt()
SDValue llvm::SelectionDAG::getExtractVectorElt (const SDLoc & DL, EVT VT, SDValue Vec, unsigned Idx) inline
Extract element at Idx from Vec.
See EXTRACT_VECTOR_ELT description for result type handling.
Definition at line 946 of file SelectionDAG.h.
References DL, llvm::ISD::EXTRACT_VECTOR_ELT, getNode(), and getVectorIdxConstant().
Referenced by llvm::TargetLowering::expandVECTOR_COMPRESS(), ExtractVectorElements(), getMemsetStores(), getNode(), getRVVFPReductionOpAndOperands(), getSplatValue(), LowerFLDEXP(), llvm::RISCVTargetLowering::LowerOperation(), lowerReductionSeq(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorStore(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), and UnrollVectorOp().
getExtStridedLoadVP()
SDValue SelectionDAG::getExtStridedLoadVP (ISD::LoadExtType ExtType, const SDLoc & DL, EVT VT, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 10360 of file SelectionDAG.cpp.
References DL, getStridedLoadVP(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
getFlagInserter()
FlagInserter * llvm::SelectionDAG::getFlagInserter () inline
Definition at line 517 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::FlagInserter::FlagInserter().
getFPExtendOrRound()
SDValue SelectionDAG::getFPExtendOrRound (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
Definition at line 1469 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, getIntPtrConstant(), and getNode().
Referenced by emitIntrinsicWithCC(), llvm::TargetLowering::expandRoundInexactToOdd(), getCopyFromPartsVector(), getNode(), LowerFLDEXP(), llvm::RISCVTargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerUINT_TO_FP_i32(), llvm::RISCVTargetLowering::PerformDAGCombine(), and PromoteBinOpToF32().
getFrameIndex()
SDValue SelectionDAG::getFrameIndex (int FI, EVT VT, bool isTarget = false)
Definition at line 1934 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::FrameIndex, getVTList(), N, Opc, and llvm::ISD::TargetFrameIndex.
Referenced by llvm::X86TargetLowering::BuildFILD(), CalculateTailCallArgDest(), CreateStackTemporary(), emitRestoreZALazySave(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), getAddressForMemoryInput(), getLifetimeNode(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getTargetFrameIndex(), getZT0FrameIndex(), llvm::AMDGPUTargetLowering::loadStackInputValue(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerINTRINSIC_W_CHAIN(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), LowerVASTART(), LowerVASTART(), unpack64(), unpackF64OnLA32DSoftABI(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), unpackFromMemLoc(), and unpackFromMemLoc().
getFrameIndexDbgValue() [1/2]
SDDbgValue * SelectionDAG::getFrameIndexDbgValue (DIVariable * Var, DIExpression * Expr, unsigned FI, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
FrameIndex with dependencies.
Definition at line 11987 of file SelectionDAG.cpp.
References assert(), llvm::cast(), DL, and llvm::SDDbgOperand::fromFrameIdx().
getFrameIndexDbgValue() [2/2]
SDDbgValue * SelectionDAG::getFrameIndexDbgValue (DIVariable * Var, DIExpression * Expr, unsigned FI, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
FrameIndex.
Definition at line 11976 of file SelectionDAG.cpp.
References assert(), llvm::cast(), DL, and getFrameIndexDbgValue().
Referenced by getFrameIndexDbgValue().
getFreeze() [1/2]
SDValue SelectionDAG::getFreeze (SDValue V)
Return a freeze using the SDLoc of the value operand.
Definition at line 2501 of file SelectionDAG.cpp.
References llvm::ISD::FREEZE, and getNode().
Referenced by combinePredicateReduction(), combinePTESTCC(), combineSelectToBinOp(), combineVSelectWithAllOnesOrZeros(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandIntMINMAX(), llvm::TargetLowering::expandVECTOR_COMPRESS(), foldBoolSelectToLogic(), foldSelectWithIdentityConstant(), foldVSelectToSignBitSplatMask(), getFreeze(), getNode(), LowerABD(), LowerAVXCONCAT_VECTORS(), llvm::RISCVTargetLowering::LowerOperation(), lowerSELECT(), lowerSelectToBinOp(), LowerShiftByScalarImmediate(), lowerVECTOR_SHUFFLEAsZeroOrAnyExtend(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedVectorElts(), and simplifySelect().
getFreeze() [2/2]
SDValue SelectionDAG::getFreeze (SDValue V, const APInt & DemandedElts, bool PoisonOnly = false)
Return a freeze of V if any of the demanded elts may be undef or poison.
If PoisonOnly is true, then only check for poison elements.
Definition at line 2505 of file SelectionDAG.cpp.
References getFreeze(), isGuaranteedNotToBeUndefOrPoison(), and PoisonOnly.
getFunctionVarLocs()
const FunctionVarLocs * llvm::SelectionDAG::getFunctionVarLocs () const inline
Returns the result of the AssignmentTrackingAnalysis pass if it's available, otherwise return nullptr.
Definition at line 510 of file SelectionDAG.h.
getGatherVP()
SDValue SelectionDAG::getGatherVP (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType)
Definition at line 10454 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::isa(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), N, and NewSDValueDbgMsg().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine().
getGetFPEnv()
SDValue SelectionDAG::getGetFPEnv (SDValue Chain, const SDLoc & dl, SDValue Ptr, EVT MemVT, MachineMemOperand * MMO)
Definition at line 10795 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::ISD::GET_FPENV_MEM, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), N, and NewSDValueDbgMsg().
getGLOBAL_OFFSET_TABLE()
SDValue llvm::SelectionDAG::getGLOBAL_OFFSET_TABLE (EVT VT) inline
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
Definition at line 1205 of file SelectionDAG.h.
References getNode(), and llvm::ISD::GLOBAL_OFFSET_TABLE.
Referenced by llvm::HexagonTargetLowering::LowerGLOBALADDRESS().
getGlobalAddress()
SDValue SelectionDAG::getGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, bool isTargetGA = false, unsigned TargetFlags = 0)
Definition at line 1885 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::BitWidth, DL, getDataLayout(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::GlobalValue::getType(), getVTList(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::GlobalValue::isThreadLocal(), N, llvm::Offset, Opc, llvm::SignExtend64(), llvm::ISD::TargetGlobalAddress, and llvm::ISD::TargetGlobalTLSAddress.
Referenced by FoldSymbolOffset(), llvm::VETargetLowering::getPICJumpTableRelocBase(), getSymbolFunctionGlobalAddress(), getTargetGlobalAddress(), llvm::TargetLowering::LowerToTLSEmulatedModel(), and performGlobalAddressCombine().
getGraphAttrs()
std::string SelectionDAG::getGraphAttrs (const SDNode * N) const
Get graph attributes for a node.
getGraphAttrs - Get graph attributes for a node.
(eg. "color=red".) Used from getNodeAttributes.
Definition at line 203 of file SelectionDAGPrinter.cpp.
References llvm::errs(), I, and N.
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::getNodeAttributes().
getHasPredecessorMaxSteps()
unsigned SelectionDAG::getHasPredecessorMaxSteps () static
Definition at line 120 of file SelectionDAG.cpp.
References MaxSteps.
Referenced by canFoldStoreIntoLibCallOutputPointers(), getPostIndexedLoadStoreOp(), and shouldCombineToPostInc().
getHeapAllocSite()
MDNode * llvm::SelectionDAG::getHeapAllocSite (const SDNode * Node) const inline
Return HeapAllocSite associated with Node, or nullptr if none exists.
Definition at line 2554 of file SelectionDAG.h.
References I.
getIndexedLoad()
SDValue SelectionDAG::getIndexedLoad (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 9929 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, llvm::cast(), getLoad(), llvm::SDValue::getValueType(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, and llvm::Offset.
getIndexedLoadVP()
SDValue SelectionDAG::getIndexedLoadVP (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 10161 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, llvm::cast(), getLoadVP(), llvm::SDValue::getValueType(), llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, and llvm::Offset.
getIndexedMaskedLoad()
SDValue SelectionDAG::getIndexedMaskedLoad (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 10576 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, llvm::cast(), getMaskedLoad(), llvm::SDValue::getValueType(), and llvm::Offset.
getIndexedMaskedStore()
SDValue SelectionDAG::getIndexedMaskedStore (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 10625 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, llvm::cast(), getMaskedStore(), and llvm::Offset.
getIndexedStore()
SDValue SelectionDAG::getIndexedStore (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 10046 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, llvm::cast(), getStore(), and llvm::Offset.
Referenced by llvm::HexagonTargetLowering::LowerStore().
getIndexedStoreVP()
SDValue SelectionDAG::getIndexedStoreVP (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 10286 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::sampleprof::Base, llvm::cast(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, NewSDValueDbgMsg(), and llvm::Offset.
getInsertSubvector()
SDValue llvm::SelectionDAG::getInsertSubvector (const SDLoc & DL, SDValue Vec, SDValue SubVec, unsigned Idx) inline
Insert SubVec at the Idx element of Vec.
Definition at line 961 of file SelectionDAG.h.
References DL, getNode(), llvm::SDValue::getValueType(), getVectorIdxConstant(), and llvm::ISD::INSERT_SUBVECTOR.
Referenced by combineBinOpToReduce(), convertToScalableVector(), llvm::TargetLowering::expandVectorFindLastActive(), getDeinterleaveShiftAndTrunc(), getZeroPaddedAdd(), insertSubVector(), lowerBitreverseShuffle(), lowerBUILD_VECTOR(), llvm::RISCVTargetLowering::LowerOperation(), lowerReductionSeq(), lowerScalarInsert(), lowerVECTOR_SHUFFLE(), lowerVZIP(), matchSplatAsGather(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), widenSubVector(), and WidenVector().
getInsertVectorElt()
SDValue llvm::SelectionDAG::getInsertVectorElt (const SDLoc & DL, SDValue Vec, SDValue Elt, unsigned Idx) inline
Insert Elt into Vec at offset Idx.
See INSERT_VECTOR_ELT description for element type handling.
Definition at line 954 of file SelectionDAG.h.
References DL, getNode(), llvm::SDValue::getValueType(), getVectorIdxConstant(), and llvm::ISD::INSERT_VECTOR_ELT.
Referenced by BuildVectorFromScalar(), CollectOpsToWiden(), lowerBuildVectorOfConstants(), lowerBuildVectorViaDominantValues(), llvm::RISCVTargetLowering::LowerOperation(), and performINSERT_VECTOR_ELTCombine().
getIntPtrConstant()
SDValue SelectionDAG::getIntPtrConstant (uint64_t Val, const SDLoc & DL, bool isTarget = false)
Definition at line 1800 of file SelectionDAG.cpp.
References DL, getConstant(), and getDataLayout().
Referenced by buildCallOperands(), combineBVZEXTLOAD(), CompactSwizzlableVector(), CreateCopyOfByValArgument(), emitConstantSizeRepmov(), emitConstantSizeRepstos(), emitRepmovsB(), emitRepstosB(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), extractSubVector(), getCALLSEQ_END(), getCALLSEQ_START(), getCopyToParts(), getFPExtendOrRound(), getFRAMEADDR(), getParamsForOneTrueMaskedElt(), getStrictFPExtendOrRound(), GetTLSADDR(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerClusterLaunchControlQueryCancel(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), lowerCvtRSIntrinsics(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerEXTRACT_SUBVECTOR(), LowerFCOPYSIGN(), LowerFLDEXP(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), lowerINT_TO_FP(), lowerMasksToReg(), lowerMSTORE(), llvm::RISCVTargetLowering::LowerOperation(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerSDIV(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), lowerSTOREVector(), LowerTcgen05MMADisableOutputLane(), lowerTcgen05St(), LowerToTLSExecModel(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerVAARG(), llvm::VETargetLowering::lowerVAARG(), llvm::HexagonTargetLowering::LowerVACOPY(), LowerVACOPY(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::PPCTargetLowering::PerformDAGCombine(), performFPExtendCombine(), PerformTruncatingStoreCombine(), prepareDescriptorIndirectCall(), promoteXINT_TO_FP(), ReorganizeVector(), replaceAtomicSwap128(), replaceLoadVector(), and SplitScalar().
getJumpTable()
SDValue SelectionDAG::getJumpTable (int JTI, EVT VT, bool isTarget = false, unsigned TargetFlags = 0)
Definition at line 1950 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), getVTList(), llvm::ISD::JumpTable, N, Opc, and llvm::ISD::TargetJumpTable.
Referenced by getTargetJumpTable().
getJumpTableDebugInfo()
SDValue SelectionDAG::getJumpTableDebugInfo (int JTI, SDValue Chain, const SDLoc & DL)
Definition at line 1970 of file SelectionDAG.cpp.
References DL, getDataLayout(), getNode(), llvm::TargetLoweringBase::getPointerTy(), getTargetConstant(), getTargetLoweringInfo(), and llvm::ISD::JUMP_TABLE_DEBUG_INFO.
Referenced by llvm::RISCVTargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandIndirectJTBranch(), and llvm::X86TargetLowering::expandIndirectJTBranch().
getLabelNode()
SDValue SelectionDAG::getLabelNode (unsigned Opcode, const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 2402 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), and N.
Referenced by getEHLabel().
getLibInfo()
const TargetLibraryInfo & llvm::SelectionDAG::getLibInfo () const inline
Definition at line 505 of file SelectionDAG.h.
getLifetimeNode()
SDValue SelectionDAG::getLifetimeNode (bool IsStart, const SDLoc & dl, SDValue Chain, int FrameIndex)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the FrameIndex.
Definition at line 9722 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), getDataLayout(), llvm::SDLoc::getDebugLoc(), getFrameIndex(), llvm::SDLoc::getIROrder(), getTargetLoweringInfo(), getVTList(), llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, N, and NewSDValueDbgMsg().
getLoad() [1/5]
SDValue SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 9903 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::UNINDEXED.
getLoad() [2/5]
SDValue SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
This function will set the MOLoad flag on MMOFlags, but you can set it if you want. The MOStore flag must not be set.
Definition at line 9893 of file SelectionDAG.cpp.
References getLoad(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::UNINDEXED.
Referenced by bitcastf32Toi32(), llvm::X86TargetLowering::BuildFILD(), combineBVOfConsecutiveLoads(), combineConcatVectorOps(), combineEXTRACT_SUBVECTOR(), combineExtractFromVectorLoad(), combineExtractWithShuffle(), combineLoad(), combineMaskedLoadConstantMask(), combineMOVDQ2Q(), combineStore(), combineTargetShuffle(), combineTruncate(), combineV3I8LoadExt(), convertMLOADToLoadWithUsedBytesMask(), convertTwoLoadsAndCmpToVCMPEQUB(), EltsFromConsecutiveLoads(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), expandf64Toi32(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), expandVACopy(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorSplice(), getADAEntry(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrLocal(), llvm::MipsTargetLowering::getDllimportVariable(), getExtLoad(), getExtLoad(), getFRAMEADDR(), getIndexedLoad(), getLargeExternalSymbol(), getLargeGlobalAddress(), getLoad(), getLoad(), getLoad(), getLoad(), getMemmoveLoadsAndStores(), GetTLSADDR(), getzOSCalleeAndADA(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), llvm::NVPTXTargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerF128Load(), llvm::SparcTargetLowering::LowerF128Op(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerLoad(), LowerLoad(), lowerLoadF128(), lowerLoadI1(), lowerMSALoadIntr(), llvm::RISCVTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), lowerShuffleAsBroadcast(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerUINT_TO_FP_i64(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), LowerVAARG(), llvm::VETargetLowering::lowerVAARG(), lowerVECTOR_SHUFFLE(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), narrowBitOpRMW(), narrowExtractedVectorLoad(), performConcatVectorsCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtBinopLoadFold(), performIntToFpCombine(), performLOADCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToWideningLoad(), PerformVMOVhrCombine(), PerformVMOVRRDCombine(), prepareDescriptorIndirectCall(), reduceMaskedLoadToScalarLoad(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), tryLowerSmallVectorExtLoad(), unpack64(), unpackF64OnLA32DSoftABI(), and unpackF64OnRV32DSoftABI().
getLoad() [3/5]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand * MMO)
Definition at line 9836 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), llvm::cast_or_null(), llvm::mdconst::extract(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MDNode::getOperand(), llvm::MachineMemOperand::getPointerInfo(), llvm::MachineMemOperand::getRanges(), llvm::EVT::getRawBits(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), Indexed, llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::ISD::LOAD, N, NewSDValueDbgMsg(), llvm::ISD::NON_EXTLOAD, llvm::Offset, and llvm::ISD::UNINDEXED.
getLoad() [4/5]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Definition at line 9812 of file SelectionDAG.cpp.
References assert(), getLoad(), getMachineFunction(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::Offset, Size, and llvm::MachinePointerInfo::V.
getLoad() [5/5]
SDValue llvm::SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr) inline
Definition at line 1504 of file SelectionDAG.h.
References getEVTAlign(), getLoad(), llvm::MachineMemOperand::MONone, and llvm::Offset.
getLoadFFVP()
SDValue SelectionDAG::getLoadFFVP (EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachineMemOperand * MMO)
Definition at line 10767 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::cast(), DL, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getFlags(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), N, and NewSDValueDbgMsg().
getLoadVP() [1/5]
SDValue SelectionDAG::getLoadVP (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 10131 of file SelectionDAG.cpp.
References getLoadVP(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::UNINDEXED.
getLoadVP() [2/5]
SDValue SelectionDAG::getLoadVP (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, const MDNode * Ranges = nullptr, bool IsExpanding = false)
Definition at line 10118 of file SelectionDAG.cpp.
References getLoadVP(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::UNINDEXED.
getLoadVP() [3/5]
SDValue SelectionDAG::getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 10077 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast_or_null(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), Indexed, N, NewSDValueDbgMsg(), llvm::Offset, and llvm::ISD::UNINDEXED.
getLoadVP() [4/5]
SDValue SelectionDAG::getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, const MDNode * Ranges = nullptr, bool IsExpanding = false)
Definition at line 10056 of file SelectionDAG.cpp.
References assert(), getLoadVP(), getMachineFunction(), llvm::EVT::getStoreSize(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::Offset, Size, and llvm::MachinePointerInfo::V.
Referenced by getExtLoadVP(), getExtLoadVP(), getIndexedLoadVP(), getLoadVP(), getLoadVP(), getLoadVP(), and getLoadVP().
getLoadVP() [5/5]
SDValue llvm::SelectionDAG::getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr, bool IsExpanding = false) inline
Definition at line 1574 of file SelectionDAG.h.
References getEVTAlign(), getLoadVP(), llvm::MachineMemOperand::MONone, and llvm::Offset.
getLogicalNOT()
SDValue SelectionDAG::getLogicalNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
Definition at line 1620 of file SelectionDAG.cpp.
References DL, getBoolConstant(), getNode(), and llvm::ISD::XOR.
Referenced by extractBooleanFlip(), llvm::RISCVTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerUAddSubOCarry(), PerformORCombine_i1(), performVECTOR_SHUFFLECombine(), and performVSELECTCombine().
getMachineFunction()
MachineFunction & llvm::SelectionDAG::getMachineFunction () const inline
Definition at line 493 of file SelectionDAG.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildCallOperands(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildSREMPow2(), CalculateTailCallSPDiff(), llvm::AArch64TargetLowering::changeStreamingMode(), combineConcatVectorOps(), combineFMA(), combineFMADDSUB(), combineFMinNumFMaxNum(), combineFneg(), combineI8TruncStore(), combineMul(), combineStore(), combineTargetShuffle(), combineV3I8LoadExt(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), llvm::BaseIndexOffset::computeAliasing(), computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::SITargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::TargetLowering::CTTZTableLookup(), llvm::SITargetLowering::denormalsEnabledForType(), EmitCmp(), emitConstantSizeRepmov(), emitConstantSizeRepstos(), emitLockedStackOp(), llvm::AArch64SelectionDAGInfo::EmitMOPS(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), emitRestoreZALazySave(), emitSMEStateSaveRestore(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemmove(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::RISCVSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), llvm::BaseIndexOffset::equalBaseIndex(), errorUnsupported(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandIS_FPCLASS(), expandMul(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorFindLastActive(), llvm::TargetLowering::expandVectorSplice(), fail(), fixupFuncForFI(), getADAEntry(), getAddressForMemoryInput(), llvm::MipsTargetLowering::getAddrLocal(), getBROADCAST_LOAD(), getCopyFromParts(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), llvm::MipsTargetLowering::getGlobalReg(), getLargeExternalSymbol(), getLargeGlobalAddress(), getLoad(), getLoadStackGuard(), getLoadVP(), getMemcpyLoadsAndStores(), getMemIntrinsicNode(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::MipsTargetLowering::getOpndList(), llvm::VETargetLowering::getPICJumpTableRelocBase(), getReducedAlign(), getRegistersForValue(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getStore(), getTagSymNode(), GetTLSADDR(), getTruncStore(), getTruncStoreVP(), getv64i1Argument(), getVCIXISDNodeWCHAIN(), getVScale(), getzOSCalleeAndADA(), hasReturnsTwiceAttr(), InferPointerInfo(), InferPtrAlign(), llvm::SITargetLowering::isCanonicalized(), isConsecutiveLSLoc(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isEligibleToFoldADDIForFasterLocalAccesses(), llvm::SITargetLowering::isFMADLegal(), llvm::SITargetLowering::isFPExtFoldable(), llvm::TargetLowering::isInTailCallPosition(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverZero(), isThreadPointerAcquisitionNode(), IsWebAssemblyLocal(), legalizeScatterGatherIndexType(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), LowerATOMIC_STORE(), lowerBuildVectorAsBroadcast(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::HexagonTargetLowering::LowerFDIV(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerInterruptReturn(), LowerINTRINSIC_W_CHAIN(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), lowerShuffleAsBroadcast(), llvm::NVPTXTargetLowering::LowerSTACKRESTORE(), llvm::NVPTXTargetLowering::LowerSTACKSAVE(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), LowerToTLSLocalDynamicModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVACOPY(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), LowerVASTART(), LowerVASTART(), LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), lowerVECTOR_SHUFFLE(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), MarkEHGuard(), MarkEHRegistrationNode(), narrowExtractedVectorLoad(), llvm::AMDGPUTargetLowering::needsDenormHandlingF32(), llvm::SITargetLowering::passSpecialInputs(), performBRCONDCombine(), performCONCAT_VECTORSCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformFADDCombineWithOperands(), performMemPairCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), performVP_REVERSECombine(), performVP_STORECombine(), llvm::SITargetLowering::PostISelFolding(), llvm::AArch64TargetLowering::preferredShiftLegalizationStrategy(), llvm::RISCVTargetLowering::preferredShiftLegalizationStrategy(), llvm::X86TargetLowering::preferredShiftLegalizationStrategy(), processVCIXOperands(), promoteToConstantPool(), promoteVCIXScalar(), recoverFramePointer(), reduceVMULWidth(), replaceAtomicSwap128(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), reportInvalidTensormapReplaceUsage(), selectI64Imm(), setAlignFlagsForFI(), setUsesTOCBasePtr(), shouldGenerateInlineTPLoop(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifySetCC(), splitStores(), llvm::AMDGPUTargetLowering::storeStackInputValue(), StoreTailCallArgumentsToStackSlot(), transformCallee(), tryMemPairCombine(), llvm::X86InstrInfo::unfoldMemoryOperand(), unpack64(), unpackF64OnLA32DSoftABI(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), unpackFromMemLoc(), unpackFromMemLoc(), unpackFromRegLoc(), unpackFromRegLoc(), unpackFromRegLoc(), updateForAIXShLibTLSModelOpt(), and viewGraph().
getMachineNode() [1/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 11842 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [2/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
getMachineNode - These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
Note that getMachineNode returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one.
Definition at line 11761 of file SelectionDAG.cpp.
References getMachineNode(), and getVTList().
Referenced by buildRegSequence16(), buildRegSequence32(), llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), llvm::VETargetLowering::combineTRUNCATE(), convertFromF16(), llvm::SITargetLowering::copyToM0(), createGPRPairNode(), createGPRPairNode2xi32(), emitLockedStackOp(), llvm::AArch64SelectionDAGInfo::EmitMOPS(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), expandBitCastI128ToF128(), expandIntrinsicWChainHelper(), getDataClassTest(), getLeftShift(), getLoadStackGuard(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getPrefetchNode(), getTargetExtractSubreg(), getTargetInsertSubreg(), InvertCarryFlag(), isWorthFoldingIntoOrrWithShift(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::VETargetLowering::lowerATOMIC_FENCE(), lowerBUILD_VECTOR(), lowerBuildVectorViaPacking(), llvm::SITargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerF128Load(), LowerF128Store(), LowerF64Op(), LowerFNEGorFABS(), llvm::VETargetLowering::LowerFormalArguments(), lowerI128ToGR128(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINTRINSIC_W_CHAIN(), lowerLoadF128(), lowerLoadI1(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerPtrAuthGlobalAddressStatically(), llvm::VETargetLowering::LowerReturn(), lowerStoreF128(), lowerStoreI1(), optimizeLogicalImm(), llvm::SITargetLowering::PostISelFolding(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceCMP_XCHG_128Results(), llvm::PPCTargetLowering::SelectAddressRegImm(), selectConstantAddr(), selectI64Imm(), selectI64Imm(), selectI64ImmDirect(), selectI64ImmDirectPrefix(), selectImm(), selectImmSeq(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), SelectSAddrFI(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), Widen(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getMachineNode() [3/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 11789 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [4/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1)
Definition at line 11767 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [5/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 11774 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [6/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 11781 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [7/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 11811 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [8/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 11835 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [9/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
Definition at line 11818 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [10/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 11826 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [11/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 11795 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [12/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 11803 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineNode(), and getVTList().
getMachineNode() [13/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 11849 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::cast(), DL, N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
getMaskedGather()
SDValue SelectionDAG::getMaskedGather (SDVTList VTs, EVT MemVT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType, ISD::LoadExtType ExtTy)
Definition at line 10636 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::isa(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), llvm::ISD::MGATHER, N, and NewSDValueDbgMsg().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine(), performMaskedGatherScatterCombine(), and rebuildGatherScatter().
getMaskedHistogram()
SDValue SelectionDAG::getMaskedHistogram (SDVTList VTs, EVT MemVT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType)
Definition at line 10729 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), llvm::ISD::EXPERIMENTAL_VECTOR_HISTOGRAM, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::isa(), N, and NewSDValueDbgMsg().
Referenced by performMaskedGatherScatterCombine().
getMaskedLoad()
SDValue SelectionDAG::getMaskedLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Base, SDValue Offset, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, ISD::LoadExtType ExtTy, bool IsExpanding = false)
Definition at line 10541 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::sampleprof::Base, llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), Indexed, llvm::ISD::MLOAD, N, NewSDValueDbgMsg(), llvm::Offset, and llvm::ISD::UNINDEXED.
Referenced by combineMaskedLoad(), combineMaskedLoadConstantMask(), getIndexedMaskedLoad(), LowerMLOAD(), LowerMLOAD(), llvm::RISCVTargetLowering::PerformDAGCombine(), performLDNT1Combine(), performUnpackCombine(), and tryToFoldExtOfMaskedLoad().
getMaskedScatter()
SDValue SelectionDAG::getMaskedScatter (SDVTList VTs, EVT MemVT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType, bool IsTruncating = false)
Definition at line 10683 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::isa(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), llvm::ISD::MSCATTER, N, and NewSDValueDbgMsg().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine(), performMaskedGatherScatterCombine(), and rebuildGatherScatter().
getMaskedStore()
SDValue SelectionDAG::getMaskedStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Base, SDValue Offset, SDValue Mask, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 10587 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::sampleprof::Base, llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), Indexed, llvm::ISD::MSTORE, N, NewSDValueDbgMsg(), llvm::Offset, and llvm::ISD::UNINDEXED.
Referenced by combineMaskedStore(), foldToMaskedStore(), getIndexedMaskedStore(), LowerINTRINSIC_W_CHAIN(), LowerMSTORE(), llvm::RISCVTargetLowering::PerformDAGCombine(), performMSTORECombine(), and performSTNT1Combine().
getMaskFromElementCount()
SDValue SelectionDAG::getMaskFromElementCount (const SDLoc & DL, EVT VT, ElementCount Len)
Return a vector with the first 'Len' lanes set to true and remaining lanes set to false.
The mask's ValueType is the same as when comparing vectors of type VT.
Definition at line 2151 of file SelectionDAG.cpp.
References DL, llvm::ISD::GET_ACTIVE_LANE_MASK, getConstant(), getContext(), getDataLayout(), getElementCount(), and getNode().
getMCSymbol()
SDValue SelectionDAG::getMCSymbol (MCSymbol * Sym, EVT VT)
Definition at line 2074 of file SelectionDAG.cpp.
References getVTList(), and N.
Referenced by recoverFramePointer(), and transformCallee().
getMDNode()
SDValue SelectionDAG::getMDNode (const MDNode * MD)
Return an MDNodeSDNode which holds an MDNode.
Definition at line 2457 of file SelectionDAG.cpp.
References AddNodeIDNode(), getVTList(), llvm::ISD::MDNODE_SDNODE, and N.
Referenced by llvm::PPCTargetLowering::CollectTargetIntrinsicOperands().
getMemBasePlusOffset() [1/2]
SDValue SelectionDAG::getMemBasePlusOffset (SDValue Base, SDValue Offset, const SDLoc & DL, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 8616 of file SelectionDAG.cpp.
References llvm::ISD::ADD, assert(), DL, getNode(), llvm::SDValue::getValueType(), llvm::Offset, llvm::ISD::PTRADD, and llvm::SDNodeFlags::setInBounds().
getMemBasePlusOffset() [2/2]
SDValue SelectionDAG::getMemBasePlusOffset (SDValue Base, TypeSize Offset, const SDLoc & DL, const SDNodeFlags Flags = SDNodeFlags())
Returns sum of the base pointer and offset.
Unlike getObjectPtrOffset this does not set NoUnsignedWrap and InBounds by default.
Definition at line 8609 of file SelectionDAG.cpp.
References llvm::sampleprof::Base, DL, getMemBasePlusOffset(), getTypeSize(), and llvm::Offset.
Referenced by combineI8TruncStore(), combineLoad(), combineStore(), combineTargetShuffle(), combineTruncate(), combineV3I8LoadExt(), llvm::TargetLowering::CTTZTableLookup(), EmitUnrolledSetTag(), getBROADCAST_LOAD(), getMemBasePlusOffset(), getObjectPtrOffset(), getObjectPtrOffset(), getParamsForOneTrueMaskedElt(), llvm::TargetLowering::getVectorSubVecPointer(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), lowerShuffleAsBroadcast(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerVECTOR_SHUFFLE(), narrowBitOpRMW(), narrowExtractedVectorLoad(), performLOADCombine(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), and splitVectorStore().
getMemcmp()
std::pair< SDValue, SDValue > SelectionDAG::getMemcmp (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, const CallInst * CI)
Lower a memcmp operation into a target library call and return the resulting chain and call result as SelectionDAG SDValues.
Definition at line 9148 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::Type::getInt32Ty(), llvm::DataLayout::getIntPtrType(), llvm::PointerType::getUnqual(), isInTailCallPositionWrapper(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), and Size.
Referenced by llvm::PPCSelectionDAGInfo::EmitTargetCodeForMemcmp().
getMemcpy()
SDValue SelectionDAG::getMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, const CallInst * CI, std::optional< bool > OverrideTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes & AAInfo = AAMDNodes(), BatchAAResults * BatchAA = nullptr)
Definition at line 9229 of file SelectionDAG.cpp.
References assert(), checkAddrSpaceIsValidForLibcall(), llvm::dyn_cast(), llvm::MachinePointerInfo::getAddrSpace(), getContext(), getDataLayout(), getExternalSymbol(), getMemcpyLoadsAndStores(), llvm::PointerType::getUnqual(), llvm::ConstantSDNode::getZExtValue(), isInTailCallPositionWrapper(), llvm::ConstantSDNode::isZero(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), and Size.
Referenced by CreateCopyOfByValArgument(), CreateCopyOfByValArgument(), CreateCopyOfByValArgument(), CreateCopyOfByValArgument(), emitConstantSizeRepmov(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::HexagonTargetLowering::LowerVACOPY(), and LowerVACOPY().
getMemIntrinsicNode() [1/3]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand * MMO)
Definition at line 9679 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::ISD::BUILTIN_OP_END, llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, llvm::ISD::PREFETCH, and llvm::SDVTList::VTs.
getMemIntrinsicNode() [2/3]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags Flags = MachineMemOperand::MOLoad | MachineMemOperand::MOStore, LocationSize Size = LocationSize::precise(0), const AAMDNodes & AAInfo = AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
Opcode may be INTRINSIC_VOID, INTRINSIC_W_CHAIN, or a target-specific memory-referencing opcode
Definition at line 9664 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getMachineFunction(), getMemIntrinsicNode(), llvm::EVT::getStoreSize(), llvm::LocationSize::precise(), and Size.
Referenced by llvm::X86TargetLowering::BuildFILD(), combineBitcast(), combineBVZEXTLOAD(), combineMaskedStore(), combinePackingMovIntoStore(), combineStore(), combineTargetShuffle(), CombineVLDDUP(), combineX86CloadCstore(), createLoadLR(), createSetFPEnvNodes(), createStoreLR(), EltsFromConsecutiveLoads(), EmitMaskedTruncSStore(), llvm::RISCVSelectionDAGInfo::EmitTargetCodeForMemset(), EmitTruncSStore(), EmitUnrolledSetTag(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), getAVX2GatherNode(), getBROADCAST_LOAD(), getGatherNode(), getMemIntrinsicNode(), getMemIntrinsicNode(), getScatterNode(), LowerATOMIC_STORE(), lowerAtomicArithWithLOCK(), lowerBuildVectorAsBroadcast(), LowerCMP_SWAP(), lowerFixedVectorSegLoadIntrinsics(), lowerFixedVectorSegStoreIntrinsics(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMSCATTER(), lowerMSTORE(), llvm::RISCVTargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), lowerShuffleAsBroadcast(), LowerSTORE(), LowerStore(), lowerSTOREVector(), lowerTcgen05Ld(), LowerTcgen05MMADisableOutputLane(), lowerTcgen05St(), lowerUINT_TO_FP_vXi32(), lowerVECTOR_SHUFFLE(), narrowLoadToVZLoad(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformMVEVLDCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformVDUPCombine(), replaceAtomicSwap128(), ReplaceINTRINSIC_W_CHAIN(), replaceLoadVector(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), TryCombineBaseUpdate(), tryMemPairCombine(), llvm::X86TargetLowering::visitMaskedLoad(), and llvm::X86TargetLowering::visitMaskedStore().
getMemIntrinsicNode() [3/3]
SDValue llvm::SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, MaybeAlign Alignment = std::nullopt, MachineMemOperand::Flags Flags = MachineMemOperand::MOLoad | MachineMemOperand::MOStore, LocationSize Size = LocationSize::precise(0), const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1441 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, getEVTAlign(), getMemIntrinsicNode(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::LocationSize::precise(), and Size.
getMemmove()
SDValue SelectionDAG::getMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, const CallInst * CI, std::optional< bool > OverrideTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes & AAInfo = AAMDNodes(), BatchAAResults * BatchAA = nullptr)
Definition at line 9344 of file SelectionDAG.cpp.
References checkAddrSpaceIsValidForLibcall(), llvm::dyn_cast(), llvm::MachinePointerInfo::getAddrSpace(), getContext(), getDataLayout(), getExternalSymbol(), getMemmoveLoadsAndStores(), llvm::PointerType::getUnqual(), llvm::ConstantSDNode::getZExtValue(), isInTailCallPositionWrapper(), llvm::ConstantSDNode::isZero(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), and Size.
getMemset()
SDValue SelectionDAG::getMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, const CallInst * CI, MachinePointerInfo DstPtrInfo, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 9450 of file SelectionDAG.cpp.
References assert(), checkAddrSpaceIsValidForLibcall(), DL, llvm::dyn_cast(), llvm::funcReturnsFirstArgOfCall(), llvm::MachinePointerInfo::getAddrSpace(), getContext(), getDataLayout(), getExternalSymbol(), getMemsetStores(), getTarget(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::ConstantSDNode::getZExtValue(), llvm::isInTailCallPosition(), llvm::isNullConstant(), llvm::CallInst::isTailCall(), llvm::ConstantSDNode::isZero(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::CallLoweringInfo::setTailCall(), and Size.
Referenced by emitConstantSizeRepstos().
getMergeValues()
SDValue SelectionDAG::getMergeValues (ArrayRef< SDValue > Ops, const SDLoc & dl)
Create a MERGE_VALUES node from the given operands.
getMergeValues - Create a MERGE_VALUES node from the given operands.
Definition at line 9653 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getNode(), getVTList(), llvm::ISD::MERGE_VALUES, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
Referenced by combineFP_EXTEND(), combineFP_ROUND(), combineV3I8LoadExt(), combineVectorCompareAndMaskUnaryOp(), combineX86AddSub(), combineX86SubCmpForFlags(), constructRetValue(), emitIntrinsicWithChainErrorMessage(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), FixupMMXIntrinsicTypes(), getAVX2GatherNode(), getGatherNode(), getVCIXISDNodeWCHAIN(), lowerADDSUBO_CARRY(), llvm::VETargetLowering::lowerATOMIC_SWAP(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), LowerF128Load(), lowerFixedVectorSegLoadIntrinsics(), llvm::SITargetLowering::LowerFormalArguments(), LowerFP16_TO_FP(), LowerFP_TO_FP16(), llvm::SITargetLowering::lowerGET_FPENV(), llvm::SITargetLowering::lowerGET_ROUNDING(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerINTRINSIC_W_CHAIN(), lowerIntrinsicWChain(), llvm::HexagonTargetLowering::LowerLoad(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), lowerLoadF128(), lowerLOADi1(), lowerLoadI1(), lowerLoadVector(), LowerMGATHER(), LowerMLOAD(), LowerMLOAD(), LowerMULO(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerREADCYCLECOUNTER(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerSTACKADDRESS(), llvm::NVPTXTargetLowering::LowerSTACKSAVE(), llvm::SITargetLowering::LowerSTACKSAVE(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::HexagonTargetLowering::LowerUAddSubOCarry(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUINT_TO_FP_i32(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), LowerVSETCC(), LowerXALUO(), llvm::RISCVTargetLowering::PerformDAGCombine(), performGatherLoadCombine(), performLD1Combine(), performLD1ReplicateCombine(), performLDNT1Combine(), performLOADCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformLongShiftCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), performRNDRCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformVMOVRRDCombine(), SplitStrictFPVectorOp(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryLowerSmallVectorExtLoad(), tryMemPairCombine(), UnrollVectorOp(), llvm::SystemZTargetLowering::useLibCall(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), and widenVectorOpsToi8().
getMFAM()
MachineFunctionAnalysisManager * llvm::SelectionDAG::getMFAM () inline
Definition at line 495 of file SelectionDAG.h.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::SITargetLowering::passSpecialInputs().
getMMI()
MachineModuleInfo * llvm::SelectionDAG::getMMI () const inline
Definition at line 515 of file SelectionDAG.h.
getMMRAMetadata()
MDNode * llvm::SelectionDAG::getMMRAMetadata (const SDNode * Node) const inline
Return the MMRA MDNode associated with Node, or nullptr if none exists.
Definition at line 2573 of file SelectionDAG.h.
getNegative()
SDValue SelectionDAG::getNegative (SDValue Val, const SDLoc & DL, EVT VT)
Create negative operation as (SUB 0, Val).
Definition at line 1611 of file SelectionDAG.cpp.
References DL, getConstant(), getNode(), and llvm::ISD::SUB.
Referenced by combineAddOfBooleanXor(), combineAddOrSubToADCOrSBB(), combineAnd(), combineMul(), combinePredicateReduction(), combineSelectToBinOp(), combineSetCC(), combineX86AddSub(), llvm::TargetLowering::expandFunnelShift(), LowerABS(), lowerAtomicArith(), lowerSelectToBinOp(), LowerSELECTWithCmpZero(), LowerShift(), LowerVectorCTLZ_GFNI(), performCONCAT_VECTORSCombine(), performCTPOPCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performNegCMovCombine(), performNegCSelCombine(), performSIGN_EXTEND_INREGCombine(), performVECTOR_SHUFFLECombine(), and performVSELECTCombine().
getNeutralElement()
SDValue SelectionDAG::getNeutralElement (unsigned Opcode, const SDLoc & DL, EVT VT, SDNodeFlags Flags)
Get the (commutative) neutral element for the given opcode, if it exists.
Definition at line 14224 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::APFloat::changeSign(), DL, llvm::ISD::FADD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, getAllOnesConstant(), getConstant(), getConstantFP(), llvm::EVT::getFltSemantics(), llvm::APFloat::getInf(), llvm::APFloat::getLargest(), llvm::APFloat::getQNaN(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::EVT::getSizeInBits(), llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::UMAX, llvm::ISD::UMIN, and llvm::ISD::XOR.
Referenced by tryFoldSelectIntoOp().
getNode() [1/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 11089 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, getNode(), and getVTList().
getNode() [2/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Definition at line 11097 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, getNode(), and getVTList().
getNode() [3/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT)
Gets or creates the specified node.
Definition at line 6442 of file SelectionDAG.cpp.
References AddNodeIDNode(), DL, getVTList(), N, and NewSDValueDbgMsg().
getNode() [4/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
Definition at line 10951 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, llvm::get(), and getNode().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), AddRequiredExtensionForVMULL(), addShuffleForVecExtend(), llvm::AMDGPUTargetLowering::addTokenForArgument(), adjustBitcastSrcVectorSSE1(), adjustForTestUnderMask(), adjustICmp128(), AdjustLength(), adjustLoadValueTypeImpl(), buildCallOperands(), BuildExactSDIV(), BuildExactUDIV(), buildFromShuffleMostly(), BuildIntrinsicOp(), BuildIntrinsicOp(), BuildIntrinsicOp(), buildMergeScalars(), buildPCRelGlobalAddress(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::buildSDIVPow2WithCMov(), buildTreeReduction(), llvm::TargetLowering::BuildUDIV(), BuildVectorFromScalar(), BuildVSLDOI(), canonicalizeBitSelect(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithHorizOp(), canonicalizeShuffleVectorByLane(), canonicalizeShuffleWithOp(), carryFlagToValue(), chainLoadsAndStoresForMemcpy(), llvm::AArch64TargetLowering::changeStreamingMode(), checkIntrinsicImmArg(), checkSignTestSetCCCombine(), clampDynamicVectorIndex(), CollectOpsToWiden(), combine_CC(), combine_CC(), combineAcrossLanesIntrinsic(), combineADC(), combineAdd(), combineAddOfPMADDWD(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineADDToMAT_PCREL_ADDR(), combineADDToSUB(), combineADDX(), combineAnd(), combineAndLoadToBZHI(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndNotIntoVANDN(), combineAndNotOrIntoAndNotAnd(), combineAndnp(), combineANDOfSETCCToCZERO(), combineAndOrForCcmpCtest(), CombineANDShift(), combineAndShuffleNot(), combineAndXorSubWithBMI(), combineArithReduction(), combineAVG(), combineAVX512SetCCToKMOV(), combineBasicSADPattern(), combineBinOpOfExtractToReduceTree(), combineBinOpOfZExt(), combineBinOpToReduce(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBitOpWithMOVMSK(), combineBitOpWithPACK(), combineBitOpWithShift(), combineBoolVectorAndTruncateStore(), combineBrCond(), combineCarryDiamond(), combineCarryThroughADD(), combineCastedMaskArithmetic(), combineCMov(), combineCMP(), combineCommutableSHUFP(), combineCompareEqual(), combineConcatVectorOfCasts(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfScalars(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOfSplats(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineDeMorganOfBoolean(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddCFmul(), combineFAndFNotToFAndn(), combineFMA(), combineFMADDSUB(), combineFMinFMax(), llvm::AMDGPUTargetLowering::combineFMinMaxLegacy(), llvm::AMDGPUTargetLowering::combineFMinMaxLegacyImpl(), combineFMinNumFMaxNum(), combineFMulcFCMulc(), combineFneg(), combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), combineFP_TO_xINT_SAT(), combineFPToSInt(), combineFunnelShift(), combineGatherScatter(), combineHorizOpWithShuffle(), combinei64TruncSrlConstant(), combineI8TruncStore(), combineINSERT_SUBVECTOR(), combineKSHIFT(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineLRINT_LLRINT(), combineM68kBrCond(), combineMADConstOne(), combineMinMaxReduction(), combineMinNumMaxNumImpl(), combineMOVMSK(), combineMul(), combineMulSelectConstOne(), combineMulSpecial(), combineMulToPMADD52(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineMulWide(), combineNarrowableShiftedLoad(), combineOr(), combineOrAndToBitfieldInsert(), combineOrCmpEqZeroToCtlzSrl(), combineOrOfCZERO(), combineOrToBitfieldInsert(), combineOrXorWithSETCC(), combinePExtTruncate(), combinePMULDQ(), combinePMULH(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineSBB(), combineSCALAR_TO_VECTOR(), combineScalarAndWithMaskSetcc(), combineSelect(), llvm::VETargetLowering::combineSelect(), combineSelectAndUse(), combineSelectAndUse(), combineSelectAndUse(), combineSelectAsExtAnd(), llvm::VETargetLowering::combineSelectCC(), combineSelectOfTwoConstants(), combineSelectToBinOp(), combineSetCC(), combineSetCCMOVMSK(), combineSext(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShiftOfShiftedLogic(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShiftToAVG(), combineShiftToMULH(), combineShiftToPMULH(), combineShlAddIAddImpl(), combineShuffleToAddSubOrFMAddSub(), combineShuffleToAnyExtendVectorInreg(), combineShuffleToFMAddSub(), combineShuffleToZeroExtendVectorInReg(), combineSignExtendInReg(), combineSIntToFP(), combineStore(), combineStoreValueFPToInt(), combineSub(), combineSubABS(), combineSubOfBoolean(), combineSubSetcc(), combineSubShiftToOrcB(), combineSUBX(), combineSVEBitSel(), combineSVEPrefetchVecBaseImmOff(), combineSVEReductionFP(), combineSVEReductionInt(), combineSVEReductionOrderedFP(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), combineToFPTruncExtElt(), combineToHorizontalAddSub(), combineToVCPOP(), combineToVWMACC(), combineTruncate(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineTruncOfSraSext(), combineTruncSelectToSMaxUSat(), combineTruncToVnclip(), combineUADDO_CARRYDiamond(), combineUIntToFP(), combineV3I8LoadExt(), combineVectorCompareAndMaskUnaryOp(), combineVectorHADDSUB(), combineVectorInsert(), combineVectorMulToSraBitcast(), combineVectorPack(), combineVectorShiftImm(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVFMADD_VLWithVFNEG_VL(), CombineVMOVDRRCandidateWithVecOp(), combineVPDPBUSDPattern(), combineVPMADD52LH(), combineVqdotAccum(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), combineVTRUNC(), combineVWADDSUBWSelect(), combineX86AddSub(), combineX86CloadCstore(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86SubCmpForFlags(), combineXor(), combineXorSubCTLZ(), combineXorToBitfieldInsert(), combineZext(), CompactSwizzlableVector(), ConstantBuildVector(), constructDup(), constructRetValue(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), ConvertCarryFlagToCarryValue(), ConvertCarryValueToCarryFlag(), convertFixedMaskToScalableVector(), convertFPToInt(), convertFromF16(), convertFromScalableVector(), convertIntLogicToFPLogic(), convertIntToFP(), convertLocVTToValVT(), convertLocVTToValVT(), convertLocVTToValVT(), convertLocVTToValVT(), convertMergedOpToPredOp(), ConvertSelectToConcatVector(), ConvertSETCCToXori(), convertShiftLeftToScale(), convertToF16(), convertToScalableVector(), convertTwoLoadsAndCmpToVCMPEQUB(), convertValVTToLocVT(), convertValVTToLocVT(), convertValVTToLocVT(), convertValVTToLocVT(), correctParamType(), createCMovFP(), createFPCmp(), createLoadLR(), createMemMemNode(), createMMXBuildVector(), createPSADBW(), createSetFPEnvNodes(), createStoreLR(), createVariablePermute(), createVPDPBUSD(), llvm::TargetLowering::CTTZTableLookup(), customLegalizeToWOp(), customLegalizeToWOp(), customLegalizeToWOpWithSExt(), customLegalizeToWOpWithSExt(), CustomNonLegalBITCASTResults(), detectPMADDUBSW(), detectUSatPattern(), distributeOpThroughSelect(), DoubleVectorWidth(), dump(), EltsFromConsecutiveLoads(), EmitAVX512Test(), EmitCMP(), EmitCmp(), emitCmp(), emitComparison(), emitConditionalComparison(), emitConstantSizeRepmov(), emitConstantSizeRepstos(), emitFloatCompareMask(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), emitMemMemReg(), llvm::AArch64SelectionDAGInfo::EmitMOPS(), emitOrXorXorTree(), emitRepmovs(), emitRepstos(), emitRestoreZALazySave(), emitSETCC(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), emitStrictFPComparison(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::RISCVSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), EmitTest(), EmitUnrolledSetTag(), emitVectorComparison(), Expand64BitShift(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandAVG(), expandBitCastF128ToI128(), llvm::TargetLowering::expandBITREVERSE(), llvm::TargetLowering::expandBSWAP(), ExpandBVWithShuffles(), llvm::TargetLowering::expandCLMUL(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandCTTZ(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), expandExp(), expandExp2(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFMINNUM_FMAXNUM(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandFP_TO_UINT(), expandFP_TO_UINT_SSE(), expandFSH64(), llvm::TargetLowering::expandFunnelShift(), ExpandHorizontalBinOp(), llvm::RISCVTargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandIndirectJTBranch(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandIntMINMAX(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandIS_FPCLASS(), expandLog(), expandLog10(), expandLog2(), expandMul(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), expandMulToAddOrSubOfShl(), expandMulToNAFSequence(), expandMulToShlAddShlAdd(), llvm::TargetLowering::expandPartialReduceMLA(), expandPow(), ExpandPowI(), ExpandREAD_REGISTER(), llvm::TargetLowering::expandREM(), llvm::TargetLowering::expandROT(), llvm::TargetLowering::expandRoundInexactToOdd(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandShiftParts(), llvm::TargetLowering::expandShlSat(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandV4F32ToV2F64(), expandVAArg(), llvm::TargetLowering::expandVecReduce(), llvm::TargetLowering::expandVecReduceSeq(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorFindLastActive(), llvm::TargetLowering::expandVectorNaryOpBySplitting(), llvm::TargetLowering::expandVectorSplice(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPBSWAP(), llvm::TargetLowering::expandVPCTLZ(), llvm::TargetLowering::expandVPCTPOP(), llvm::TargetLowering::expandVPCTTZ(), llvm::TargetLowering::expandVPCTTZElements(), expandVPFunnelShift(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendToType(), ExtractBitFromMaskVector(), extractF64Exponent(), extractLOHI(), extractShiftForRotate(), extractSubVector(), fillVector(), finalizeTS1AM(), findMoreOptimalIndexType(), FixupMMXIntrinsicTypes(), foldADCToCINC(), foldAddSubBoolOfMaskedVal(), foldAddSubMasked1(), foldAddSubOfSignBit(), foldAndOrOfSETCC(), foldAndToUsubsat(), foldBinOpIntoSelectIfProfitable(), foldBinOpIntoSelectIfProfitable(), foldBitOrderCrossLogicOp(), FoldConstantArithmetic(), FoldConstantBuildVector(), foldCSELOfCSEL(), foldCSELofCTTZ(), foldCSELofLASTB(), foldExtendedSignBitTest(), foldExtendVectorInregToExtendOfSubvector(), foldExtractSubvectorFromShuffleVector(), foldFPToIntToFP(), llvm::AMDGPUTargetLowering::foldFreeOpFromSelect(), foldIndexIntoBase(), FoldIntToFPToInt(), foldLogicOfShifts(), foldLogicTreeOfShifts(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedMerge(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldOverflowCheck(), foldReduceOperandViaVQDOT(), foldSelectOfConstantsUsingSra(), foldSelectOfCTTZOrCTLZ(), foldSelectWithIdentityConstant(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldShuffleOfConcatUndefs(), foldSubCtlzNot(), foldToSaturated(), foldVSelectToSignBitSplatMask(), foldXorTruncShiftIntoCmp(), llvm::TargetLowering::forceExpandMultiply(), llvm::TargetLowering::forceExpandWideMUL(), fpExtendHelper(), genConstMult(), generateComparison(), generateEquivalentSub(), GenerateFixedLengthSVETBL(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), getADAEntry(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrGPRel(), llvm::MipsTargetLowering::getAddrLocal(), llvm::MipsTargetLowering::getAddrNonPIC(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAllOnesMask(), getAnyExtOrTrunc(), getAVX512Node(), getAVX512TruncNode(), getBitcast(), getBitSelect(), getBitTestCondition(), getBMIMatchingOp(), getBoolExtOrTrunc(), getBoundedStrlen(), getBT(), getBuildVector(), getBuildVector(), getBuildVectorSplat(), getCALLSEQ_END(), getCALLSEQ_START(), getCCResult(), getConstant(), getCopyFromParts(), getCopyFromPartsVector(), getCopyFromReg(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), getCopyToReg(), getCopyToReg(), getCopyToReg(), llvm::RegsForValue::getCopyToRegs(), getCSAddressAndShifts(), getDataClassTest(), getDeinterleaveShiftAndTrunc(), llvm::MipsTargetLowering::getDllimportSymbol(), getDWordFromOffset(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getEstimate(), GetExponent(), getEXTEND_VECTOR_INREG(), GetExtendHigh(), getExtractSubvector(), getExtractVectorElt(), getExtractVectorizedValue(), getFlagsOfCmpZeroFori1(), getFLUSHW(), getFPBinOp(), getFPExtendOrRound(), getFPTernOp(), getFRAMEADDR(), getFreeze(), getGeneralPermuteNode(), getGLOBAL_OFFSET_TABLE(), llvm::AMDGPUTargetLowering::getHiHalf64(), getHopForBuildVector(), getI128Select(), getInsertSubvector(), getInsertVectorElt(), llvm::AMDGPUTargetLowering::getIsFinite(), getJumpTableDebugInfo(), getKnownUndefForVectorBinop(), getLargeExternalSymbol(), getLargeGlobalAddress(), getLimitedPrecisionExp2(), getLoadExtOrTrunc(), getLogicalNOT(), llvm::AMDGPUTargetLowering::getLoHalf64(), getMad(), getMad64_32(), getMaskFromElementCount(), getMaskNode(), getMemBasePlusOffset(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getMergeValues(), getMul24(), getNarrowMaskForInterleavedOps(), llvm::AMDGPUTargetLowering::getNegatedExpression(), llvm::PPCTargetLowering::getNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), llvm::X86TargetLowering::getNegatedExpression(), getNegative(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNOT(), getPack(), getPermuteNode(), llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), llvm::M68kTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), getPMOVMSKB(), getPOISON(), getPopFromX87Reg(), getPRMT(), getPTest(), getPTrue(), llvm::AMDGPUTargetLowering::getRecipEstimate(), llvm::LoongArchTargetLowering::getRecipEstimate(), getReductionSDNode(), getRegistersForValue(), getScalarMaskingNode(), llvm::AMDGPUTargetLowering::getScaledLogInput(), getScaledOffsetForBitWidth(), getSelect(), getSelectCC(), getSETCC(), getSETCC(), getSETCC(), getSetCC(), getSetCCVP(), getSExtOrTrunc(), getShlAddShlAdd(), getShuffleHalfVectors(), GetSignificand(), getSplatBuildVector(), getSplatVector(), llvm::AMDGPUTargetLowering::getSqrtEstimate(), llvm::LoongArchTargetLowering::getSqrtEstimate(), llvm::NVPTXTargetLowering::getSqrtEstimate(), llvm::TargetLowering::getSqrtInputTest(), getStackArgumentTokenFactor(), getStepVector(), getSToVPermuted(), getStrictFPExtendOrRound(), getSVEPredicateBitCast(), getTargetVShiftByConstNode(), getTargetVShiftNode(), GetTLSADDR(), getTokenFactor(), getTruncatedUSUBSAT(), getUNDEF(), getv64i1Argument(), getVAArg(), getVCIXISDNodeVOID(), getVCIXISDNodeWCHAIN(), getVectorBitwiseReduce(), getVectorMaskingNode(), getVectorShuffle(), llvm::TargetLowering::getVectorSubVecPointer(), getVPLogicalNOT(), getVPZeroExtendInReg(), getVPZExtOrTrunc(), getVScale(), getVShift(), getVSlidedown(), getVSlideup(), getWideningInterleave(), getWideningSpread(), getX86XALUOOp(), getZeroExtendInReg(), getZeroPaddedAdd(), getZeroVector(), getZExtOrTrunc(), getzOSCalleeAndADA(), handleCMSEValue(), HandleMergeInputChains(), llvm::TargetLowering::IncrementMemoryAddress(), initAccumulator(), insert1BitVector(), InsertBitToMaskVector(), isFNEG(), isFusableLoadOpStorePattern(), isFusableLoadOpStorePattern(), IsNOT(), isNOT(), isUpperSubvectorUndef(), joinDwords(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), legalizeIntrinsicImmArg(), legalizeScatterGatherIndexType(), llvm::TargetLowering::LegalizeSetCCCondCode(), legalizeSVEGatherPrefetchOffsVec(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerABD(), LowerABS(), LowerADDRSPACECAST(), LowerADDRSPACECAST(), lowerAddrSpaceCast(), LowerADDSAT_SUBSAT(), LowerADDSUBO_CARRY(), lowerADDSUBO_CARRY(), LowerADDSUBSAT(), lowerAddSubToHorizontalOp(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), LowerAsSplatVectorLoad(), llvm::HexagonTargetLowering::LowerATOMIC_FENCE(), LowerATOMIC_FENCE(), LowerATOMIC_FENCE(), LowerATOMIC_FENCE(), llvm::VETargetLowering::lowerATOMIC_FENCE(), LowerATOMIC_STORE(), llvm::VETargetLowering::lowerATOMIC_SWAP(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), lowerBALLOTIntrinsic(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBitreverseShuffle(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::LanaiTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::LanaiTargetLowering::LowerBR_CC(), llvm::MSP430TargetLowering::LowerBR_CC(), LowerBR_CC(), LowerBRCOND(), lowerBSWAP(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), lowerBUILD_VECTORAsBroadCastLoad(), LowerBUILD_VECTORToVIDUP(), LowerBUILD_VECTORvXbf16(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), lowerBuildVectorOfConstants(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), lowerBuildVectorViaDominantValues(), lowerBuildVectorViaPacking(), lowerBuildVectorViaVID(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), LowerCallResult(), lowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerClusterLaunchControlQueryCancel(), LowerCMP_SWAP(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::LanaiTargetLowering::LowerConstantPool(), LowerConvertLow(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), lowerCTLZCTPOP(), llvm::AMDGPUTargetLowering::lowerCTLZResults(), LowerCTPOP(), LowerCTPOP(), LowerCTTZ(), LowerCTTZ(), lowerCttzElts(), LowerCVTPS2PH(), lowerCvtRSIntrinsics(), lowerDisjointIndicesShuffle(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::VETargetLowering::lowerEH_SJLJ_LONGJMP(), llvm::VETargetLowering::lowerEH_SJLJ_SETJMP(), llvm::VETargetLowering::lowerEH_SJLJ_SETUP_DISPATCH(), LowerEXTEND_VECTOR_INREG(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_VECTOR_ELT(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), LowerF64Op(), llvm::AMDGPUTargetLowering::LowerF64ToF16Safe(), LowerFABSorFNEG(), lowerFABSorFNEG(), LowerFCanonicalize(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), LowerFCOPYSIGN(), lowerFCOPYSIGN(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP10Unsafe(), llvm::AMDGPUTargetLowering::lowerFEXP2(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafe(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafeImpl(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFGETSIGN(), lowerFixedVectorSegLoadIntrinsics(), lowerFixedVectorSegStoreIntrinsics(), LowerFLDEXP(), LowerFLDEXP(), llvm::AMDGPUTargetLowering::LowerFLOG2(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), llvm::AMDGPUTargetLowering::LowerFLOGUnsafe(), lowerFMAXIMUM_FMINIMUM(), LowerFMINIMUM_FMAXIMUM(), llvm::AMDGPUTargetLowering::LowerFNEARBYINT(), LowerFNEGorFABS(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP16_TO_FP(), llvm::SITargetLowering::lowerFP_EXTEND(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT(), lowerFP_TO_INT(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), LowerFP_TO_INT_SAT(), lowerFP_TO_INT_SAT(), LowerFP_TO_SINT(), lowerFP_TO_SINT_STORE(), lowerFPToIntToFP(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), lowerFREM(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), LowerFunnelShift(), LowerFunnelShift(), llvm::SITargetLowering::lowerGET_FPENV(), llvm::SITargetLowering::lowerGET_ROUNDING(), lowerGetVectorLength(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerGR128Binary(), lowerGR128ToI128(), LowerHorizontalByteSum(), lowerI128ToGR128(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerICMPIntrinsic(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), lowerINT_TO_FP(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), lowerIntNeonIntrinsic(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), llvm::HexagonTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), llvm::HexagonTargetLowering::LowerJumpTable(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerLabelRef(), lowerLaneOp(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), lowerLoadF128(), lowerLOADi1(), lowerLoadI1(), lowerMasksToReg(), LowerMemOpCallTo(), LowerMGATHER(), LowerMINMAX(), LowerMLOAD(), LowerMLOAD(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatZExt(), lowerMSAStoreIntr(), LowerMSCATTER(), lowerMSTORE(), llvm::LanaiTargetLowering::LowerMUL(), LowerMUL(), LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), LowerMULO(), llvm::AArch64TargetLowering::LowerOperation(), llvm::ARMTargetLowering::LowerOperation(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), lowerOverflowArithmetic(), LowerPARITY(), LowerPredicateLoad(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerPREFETCH(), LowerPREFETCH(), LowerPREFETCH(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), llvm::HexagonTargetLowering::LowerREADSTEADYCOUNTER(), lowerReductionSeq(), lowerRegToMasks(), llvm::AMDGPUTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), lowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLE(), LowerRotate(), LowerSaturatingConditional(), LowerSCALAR_TO_VECTOR(), lowerScalarInsert(), lowerScalarSplat(), LowerSDIV(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), lowerSELECT(), llvm::LanaiTargetLowering::LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), lowerSelectToBinOp(), LowerSELECTWithCmpZero(), llvm::SITargetLowering::lowerSET_FPENV(), llvm::SITargetLowering::lowerSET_ROUNDING(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), llvm::MSP430TargetLowering::LowerShifts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitMask(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificExtension(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleWithEXPAND(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithSHUFPS(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK(), lowerShuffleWithUNPCK256(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), LowerSINT_TO_FP(), LowerSMELdrStr(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerSTACKADDRESS(), llvm::NVPTXTargetLowering::LowerSTACKRESTORE(), llvm::NVPTXTargetLowering::LowerSTACKSAVE(), llvm::SITargetLowering::LowerSTACKSAVE(), LowerSTORE(), LowerSTORE(), LowerStore(), lowerStoreF128(), lowerStoreI1(), lowerSTOREVector(), LowerSVEIntrinsicDUP(), LowerSVEIntrinsicEXT(), LowerSVEIntrinsicIndex(), lowerTcgen05Ld(), LowerTcgen05MMADisableOutputLane(), lowerTcgen05St(), lowerToAddSubOrFMAddSub(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerTruncate(), LowerTruncatei1(), LowerTruncateVecI1(), LowerTruncateVecPack(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUADDSUBO_CARRY(), llvm::HexagonTargetLowering::LowerUAddSubOCarry(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), LowerVAARG(), llvm::VETargetLowering::lowerVAARG(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), LowerVecReduce(), LowerVecReduceMinMax(), lowerVECTOR_COMPRESS(), llvm::HexagonTargetLowering::LowerVECTOR_SHIFT(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_IsReverse(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VILVH(), lowerVECTOR_SHUFFLE_VILVL(), lowerVECTOR_SHUFFLE_VPACKEV(), lowerVECTOR_SHUFFLE_VPACKOD(), lowerVECTOR_SHUFFLE_VPICKEV(), lowerVECTOR_SHUFFLE_VPICKOD(), lowerVECTOR_SHUFFLE_VREPLVEI(), lowerVECTOR_SHUFFLE_VSHF(), lowerVECTOR_SHUFFLE_VSHUF(), lowerVECTOR_SHUFFLE_VSHUF4I(), lowerVECTOR_SHUFFLE_XVILVH(), lowerVECTOR_SHUFFLE_XVILVL(), lowerVECTOR_SHUFFLE_XVINSVE0(), lowerVECTOR_SHUFFLE_XVPERM(), lowerVECTOR_SHUFFLE_XVPERMI(), lowerVECTOR_SHUFFLE_XVPICKEV(), lowerVECTOR_SHUFFLE_XVPICKOD(), lowerVECTOR_SHUFFLE_XVREPLVEI(), lowerVECTOR_SHUFFLE_XVSHUF(), lowerVECTOR_SHUFFLEAsByteRotate(), lowerVECTOR_SHUFFLEAsRotate(), lowerVECTOR_SHUFFLEAsShift(), lowerVECTOR_SHUFFLEAsVRGatherVX(), lowerVECTOR_SHUFFLEAsVSlide1(), lowerVECTOR_SHUFFLEAsVSlideup(), lowerVECTOR_SHUFFLEAsZeroOrAnyExtend(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVECTOR_SHUFFLEUsingOneOff(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllEqual(), LowerVectorArith(), lowerVectorBitClear(), lowerVectorBitClearImm(), lowerVectorBitRevImm(), lowerVectorBitSetImm(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZ_GFNI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), LowerVectorExtend(), LowerVectorFP_TO_INT(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), LowerVectorINT_TO_FP(), lowerVectorIntrinsicScalars(), LowerVectorMatch(), lowerVectorPickVE2GR(), lowerVectorSplatImm(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorXRINT_XROUND(), LowerVSETCC(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowervXi8MulWithUNPCK(), lowerVZIP(), lowerWaveShuffle(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), lowerX86FPLogicOp(), LowerXALUO(), LowerXALUO(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), makeEquivalentMemoryOrdering(), llvm::SparcTargetLowering::makeHiLoPair(), llvm::VETargetLowering::makeHiLoPair(), matchBSwapHWordOrAndAnd(), matchMergedBFX(), matchPERM(), matchPMADDWD(), matchPMADDWD_2(), matchSplatAsGather(), matchTruncateWithPACK(), MatchVectorAllEqualTest(), mergeHighParts(), moveBelowOrigChain(), narrowBitOpRMW(), narrowExtractedVectorBinOp(), narrowIndex(), narrowInsertExtractVectorBinOp(), narrowVectorSelect(), optimizeLogicalImm(), overflowFlagToValue(), packImage16bitOpsToDwords(), partitionShuffleOfConcats(), llvm::SITargetLowering::passSpecialInputs(), performActiveLaneMaskCombine(), performADDCombine(), performAddCombineForShiftedOperands(), performAddCombineSubShift(), PerformADDCombineWithOperands(), performAddCSelIntoCSinc(), PerformAddcSubcCombine(), performAddDotCombine(), PerformAddeSubeCombine(), performAddSubIntoVectorOp(), performAddSubLongCombine(), performAddTruncShiftCombine(), performAddUADDVCombine(), PerformADDVecReduce(), PerformANDCombine(), performANDCombine(), performANDCombine(), performANDCombine(), performANDCombine(), performANDORCSELCombine(), performANDSCombine(), performANDSETCCCombine(), performAnyAllCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::performAssertSZExtCombine(), PerformBFICombine(), PerformBITCASTCombine(), performBITCASTCombine(), performBitcastCombine(), performBITREV_WCombine(), performBITREVERSECombine(), performBR_CCCombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), performBRCONDCombine(), performBSPExpandForSVE(), PerformBUILD_VECTORCombine(), performBUILD_VECTORCombine(), performBuildShuffleExtendCombine(), performBuildVectorCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCMovFPCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCONDCombine(), performConvertFPCombine(), performCSELCombine(), PerformCSETCombine(), performCTLZCombine(), performCTPOPCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), performDivRemCombine(), performDSPShiftCombine(), performDUPCombine(), performDupLane128Combine(), performExtBinopLoadFold(), PerformExtendCombine(), performExtendCombine(), PerformEXTRACTCombine(), PerformExtractEltCombine(), PerformExtractEltToVMOVRRD(), performExtractLastActiveCombine(), performExtractSubvectorCombine(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFADDCombine(), PerformFADDCombineWithOperands(), PerformFADDVCMLACombine(), PerformFAddVSelectCombine(), performFlagSettingCombine(), PerformFMinMaxCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), performFPExtendCombine(), performFpToIntCombine(), performGatherLoadCombine(), performGLD1Combine(), performGlobalAddressCombine(), PerformHWLoopCombine(), performINSERT_VECTOR_ELTCombine(), PerformInsertEltCombine(), PerformInsertSubvectorCombine(), performInsertSubvectorCombine(), performInsertVectorEltCombine(), performInterleavedMaskedStoreCombine(), performINTRINSIC_WO_CHAINCombine(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), performIntrinsicCombine(), performIntToFpCombine(), performLD1Combine(), performLD1ReplicateCombine(), performLDNT1Combine(), performLOADCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), PerformLongShiftCombine(), performMADD_MSUBCombine(), PerformMinMaxCombine(), PerformMinMaxFpToSatCombine(), PerformMinMaxToSatCombine(), PerformMULCombine(), performMULCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), performMulCombine(), performMulCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performMulLoHiCombine(), performMulRdsvlCombine(), performMulVectorCmpZeroCombine(), performMulVectorExtendCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformMVEVMULLCombine(), performNegCMovCombine(), performNegCSelCombine(), performNVCASTCombine(), PerformORCombine(), performORCombine(), performORCombine(), performORCombine(), PerformORCombine_i1(), PerformORCombineToBFI(), PerformORCombineToSMULWBT(), performOrXorChainCombine(), PerformPREDICATE_CASTCombine(), performPTestFirstCombine(), PerformReduceShuffleCombine(), PerformREMCombine(), performRNDRCombine(), performScalarToVectorCombine(), performScatterStoreCombine(), performSELECT_CCCombine(), PerformSELECTCombine(), performSELECTCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSelectCombine(), PerformSELECTShiftCombine(), performSETCC_BITCASTCombine(), performSetccAddFolding(), PerformSETCCCombine(), performSETCCCombine(), performSETCCCombine(), performSETCCCombine(), performSETCCCombine(), performSetccMergeZeroCombine(), PerformShiftCombine(), performSHLCombine(), performSHLCombine(), performSHLCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), PerformSHLSimplify(), PerformShuffleVMOVNCombine(), performSIGN_EXTEND_INREGCombine(), performSignExtendCombine(), PerformSignExtendInregCombine(), performSignExtendInRegCombine(), performSignExtendSetCCCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSRACombine(), performSRACombine(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRLCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performST1Combine(), performSTNT1Combine(), PerformSTORECombine(), performSTORECombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), performSubAddMULCombine(), PerformSUBCombine(), performSUBCombine(), PerformSubCSINCCombine(), performSubsToAndsCombine(), performSubWithBorrowCombine(), performSunpkloCombine(), performSVEAndCombine(), performSVEMulAddSubCombine(), performTBZCombine(), performTRUNCATECombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), performTruncateCombine(), performTruncateCombine(), PerformTruncatingStoreCombine(), performUADDVAddCombine(), performUADDVCombine(), performUADDVZextCombine(), PerformUMinFpToSatCombine(), PerformUMLALCombine(), performUzpCombine(), performVANDNCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDUPCombine(), PerformVDUPLANECombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), performVecReduceAddCombineWithUADDLP(), performVECREDUCECombine(), PerformVECTOR_REG_CASTCombine(), PerformVECTOR_SHUFFLECombine(), performVECTOR_SHUFFLECombine(), performVectorCompareAndMaskUnaryOpCombine(), performVectorDeinterleaveCombine(), performVectorExtCombine(), performVectorExtendCombine(), performVectorExtendToFPCombine(), performVectorNonNegToFPCombine(), performVectorTruncZeroCombine(), PerformVMOVDRRCombine(), PerformVMOVhrCombine(), PerformVMOVNCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), PerformVMulVCTPCombine(), performVP_REVERSECombine(), performVP_STORECombine(), performVP_TRUNCATECombine(), PerformVQDMULHCombine(), PerformVQDMULHCombine(), PerformVSELECTCombine(), PerformVSELECTCombine(), performVSELECTCombine(), performVSELECTCombine(), performVSelectCombine(), PerformVSetCCToVCTPCombine(), PerformXORCombine(), performXORCombine(), performXORCombine(), performZExtDeinterleaveShuffleCombine(), performZExtUZPCombine(), prepareDescriptorIndirectCall(), prepareIndirectCall(), PrepareTailCall(), prepareTS1AM(), PromoteBinOpToF32(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), PromoteMaskArithmetic(), PromoteMVEPredVector(), llvm::TargetLoweringBase::promoteTargetBoolean(), promoteToConstantPool(), promoteVCIXScalar(), promoteXINT_TO_FP(), pushAddIntoCmovOfConsts(), reassociateCSELOperandsForCSE(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReconstructShuffleWithRuntimeMask(), ReconstructTruncateFromBuildVector(), recoverFramePointer(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), refineUniformBase(), ReorganizeVector(), ReplaceAddWithADDP(), ReplaceAllUsesWith(), ReplaceAllUsesWith(), ReplaceATOMIC_LOAD_128Results(), replaceAtomicSwap128(), ReplaceBITCAST(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceCMP_XCHG_128Results(), ReplaceCopyFromReg_128(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), replaceLoadVector(), ReplaceLongIntrinsic(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceProxyReg(), ReplaceREADCYCLECOUNTER(), ReplaceReductionResults(), replaceVecCondBranchResults(), replaceVPICKVE2GRResults(), resolveSources(), reverseZExtICmpCombine(), SaturateWidenedDIVFIX(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), scalarizeExtractedBinOp(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::TargetLowering::ShrinkDemandedConstant(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), signExtendBitcastSrcVector(), signExtendBitcastSrcVector(), simplifyAssumingCCVal(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::LoongArchTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyMul24(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCIntoEq(), simplifySetCCWithCTPOP(), sinkProxyReg(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), splatPartsI64WithVL(), llvm::AMDGPUTargetLowering::split64BitValue(), SplitAndExtendv16i1(), splitAndLowerShuffle(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), llvm::SITargetLowering::splitBinaryVectorOp(), SplitEVL(), SplitOpsAndApply(), SplitScalar(), splitStores(), splitStoreSplat(), SplitStrictFPVectorOp(), llvm::SITargetLowering::splitTernaryVectorOp(), llvm::SITargetLowering::splitUnaryVectorOp(), llvm::PPCTargetLowering::splitValueIntoRegisterParts(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), SplitVector(), llvm::AMDGPUTargetLowering::splitVector(), splitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), SplitVectorOp(), splitVectorOp(), SplitVectorReductionOp(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), SplitVPOp(), splitVSETCC(), llvm::AMDGPUTargetLowering::storeStackInputValue(), stripModuloOnShift(), takeInexpensiveLog2(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), transformAddImmMulImm(), transformAddShlImm(), translateSetCCForBranch(), translateSetCCForBranch(), truncateAVX512SetCCNoBWI(), truncateScalarIntegerArg(), truncateVecElts(), truncateVecElts(), truncateVectorWithNARROW(), truncateVectorWithPACK(), truncateVectorWithPACKSS(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), TryCombineBaseUpdate(), tryCombineCRC32(), tryCombineExtendRShTrunc(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryCombineMULLWithUZP1(), tryCombineNeonFcvtFP16ToI16(), tryCombineShiftImm(), tryConvertSVEWideCompare(), tryDemorganOfBooleanCondition(), TryDistrubutionADDVecReduce(), tryExtendDUPToExtractHigh(), tryFoldMADwithSRL(), tryFoldSelectIntoOp(), tryFormConcatFromShuffle(), tryLowerSmallVectorExtLoad(), tryLowerToBSL(), tryLowerToSLI(), TryMatchTrue(), TryMULWIDECombine(), trySimplifySrlAddToRshrnb(), trySQDMULHCombine(), trySVESplat64(), trySwapVSelectOperands(), tryToConvertShuffleOfTbl2ToTbl4(), tryToFoldExtendOfConstant(), tryToFoldExtendSelectLoad(), tryToFoldExtOfAtomicLoad(), tryToFoldExtOfLoad(), tryToFoldExtOfMaskedLoad(), tryToReplaceScalarFPConversionWithSVE(), tryToWidenSetCCOperands(), TryWideExtMulCombine(), unpack64(), unpackF64OnLA32DSoftABI(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), valueToCarryFlag(), vectorizeExtractedCast(), vectorToScalarBitmask(), visitORCommutative(), widenAbs(), widenBuildVector(), widenCtPop(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), widenVec(), WidenVector(), widenVectorOpsToi8(), widenVectorToPartType(), and WinDBZCheckDenominator().
getNode() [5/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 10967 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [6/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Definition at line 10975 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::ISD::BR_CC, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::ISD::DELETED_NODE, DL, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), getNode(), llvm::EVT::getScalarType(), getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), N, NewSDValueDbgMsg(), and llvm::ISD::SELECT_CC.
getNode() [7/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2)
Definition at line 7623 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [8/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags)
Definition at line 7652 of file SelectionDAG.cpp.
References llvm::ISD::ABDS, llvm::ISD::ABDU, AbstractManglingParser< Derived, Alloc >::Ops, llvm::ISD::ADD, AddNodeIDNode(), llvm::ISD::AND, assert(), llvm::ISD::AssertNoFPClass, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::AVGCEILS, llvm::ISD::AVGCEILU, llvm::ISD::AVGFLOORS, llvm::ISD::AVGFLOORU, llvm::EVT::bitsLE(), llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, canonicalizeCommutativeBinop(), llvm::cast(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::DELETED_NODE, DL, llvm::dyn_cast(), llvm::ISD::EntryToken, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMUL, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT_SAT, llvm::ISD::FP_TO_UINT_SAT, llvm::ISD::FREM, llvm::ISD::FSUB, getAllOnesConstant(), getAnyExtOrTrunc(), llvm::SDNode::getAsZExtVal(), getConstant(), llvm::SDNode::getConstantOperandAPInt(), getDataLayout(), getExtractVectorElt(), getFPExtendOrRound(), getNode(), getNOT(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPOISON(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), getSExtOrTrunc(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorMinNumElements(), llvm::EVT::getVectorNumElements(), getVScale(), getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::isa(), llvm::ConstantSDNode::isAllOnes(), llvm::isConstOrConstSplat(), llvm::EVT::isFixedLengthVector(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::ConstantSDNode::isZero(), llvm::Log2_32_Ceil(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, N, NewSDValueDbgMsg(), llvm::ISD::OR, llvm::ISD::POISON, llvm::ISD::PTRADD, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDSAT, llvm::ISD::SCMP, llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, simplifyFPBinop(), simplifyShift(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SSHLSAT, llvm::ISD::SSUBSAT, llvm::ISD::SUB, std::swap(), llvm::ISD::TargetConstant, llvm::to_underlying(), llvm::ISD::TokenFactor, llvm::ISD::UADDSAT, llvm::ISD::UCMP, llvm::ISD::UDIV, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UNDEF, llvm::ISD::UREM, llvm::ISD::USHLSAT, llvm::ISD::USUBSAT, llvm::ISD::VSCALE, and llvm::ISD::XOR.
getNode() [9/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3)
Definition at line 8214 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [10/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags)
Definition at line 8222 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::cast(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::DELETED_NODE, DL, llvm::dyn_cast(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::FMA, llvm::ISD::FMAD, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), FoldSetCC(), llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::get(), llvm::SDNode::getAsAPIntVal(), llvm::SDNode::getAsZExtVal(), llvm::APInt::getBitsSet(), llvm::APInt::getBitWidth(), getDataLayout(), llvm::APInt::getOneBitSet(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorMinNumElements(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::hasKnownScalarFactor(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::isa(), llvm::EVT::isFixedLengthVector(), llvm::EVT::isFloatingPoint(), isGuaranteedNotToBePoison(), llvm::EVT::isInteger(), llvm::isNullConstant(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm_unreachable, N, NewSDValueDbgMsg(), llvm::ISD::PARTIAL_REDUCE_FMLA, llvm::ISD::PARTIAL_REDUCE_SMLA, llvm::ISD::PARTIAL_REDUCE_SUMLA, llvm::ISD::PARTIAL_REDUCE_UMLA, llvm::ISD::POISON, llvm::ISD::SELECT, llvm::ISD::SETCC, simplifySelect(), llvm::ISD::UNDEF, llvm::ISD::VECTOR_COMPRESS, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VECTOR_SPLICE_LEFT, llvm::ISD::VECTOR_SPLICE_RIGHT, and llvm::ISD::VSELECT.
getNode() [11/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 8488 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [12/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, const SDNodeFlags Flags)
Definition at line 8481 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [13/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 8503 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [14/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5, const SDNodeFlags Flags)
Definition at line 8496 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [15/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand)
Definition at line 6459 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [16/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand, const SDNodeFlags Flags)
Definition at line 6467 of file SelectionDAG.cpp.
References llvm::ISD::ABS, AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, assert(), llvm::ISD::BF16_TO_FP, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::EVT::bitsGT(), llvm::EVT::bitsLE(), llvm::EVT::bitsLT(), llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, ComputeNumSignBits(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DELETED_NODE, DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FCEIL, llvm::ISD::FFLOOR, llvm::ISD::FNEG, FoldBUILD_VECTOR(), FoldConstantArithmetic(), llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_BF16, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREEZE, llvm::ISD::FTRUNC, llvm::APInt::getBitsSetFrom(), getConstant(), getConstantFP(), llvm::SDValue::getConstantOperandAPInt(), llvm::SDValue::getConstantOperandVal(), llvm::SDNode::getFlags(), llvm::SDValue::getNode(), getNode(), getNOT(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPOISON(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::SDValue::getScalarValueSizeInBits(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorMinNumElements(), getVScale(), getVTList(), llvm::SDNodeFlags::hasNonNeg(), llvm::isa(), llvm::EVT::isFloatingPoint(), isGuaranteedNotToBeUndefOrPoison(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm_unreachable, MaskedValueIsZero(), llvm::ISD::MERGE_VALUES, N, NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::ISD::POISON, llvm::ISD::SCALAR_TO_VECTOR, llvm::SDNodeFlags::setNonNeg(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SPLAT_VECTOR, llvm::ISD::STEP_VECTOR, llvm::ISD::TargetConstant, llvm::ISD::TokenFactor, transferDbgValues(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::ISD::VECREDUCE_ADD, llvm::ISD::VECREDUCE_AND, llvm::ISD::VECREDUCE_OR, llvm::ISD::VECREDUCE_SMAX, llvm::ISD::VECREDUCE_SMIN, llvm::ISD::VECREDUCE_UMAX, llvm::ISD::VECREDUCE_UMIN, llvm::ISD::VECREDUCE_XOR, llvm::ISD::VSCALE, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
getNode() [17/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList)
Definition at line 11284 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [18/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, ArrayRef< SDValue > Ops)
Definition at line 11103 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [19/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Definition at line 11111 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::ISD::AND, assert(), llvm::EVT::bitsLT(), llvm::CallingConv::C, canonicalizeCommutativeBinop(), llvm::ISD::DELETED_NODE, DL, llvm::dyn_cast(), llvm::APInt::extractBits(), llvm::ISD::FFREXP, llvm::frexp(), getConstant(), getConstantFP(), getFreeze(), getNode(), getNOT(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), getSignedConstant(), getValueType(), llvm::EVT::getVectorElementCount(), llvm::Hi, llvm::isConstOrConstSplat(), llvm::APFloat::isFinite(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::ConstantSDNode::isZero(), llvm::Lo, llvm::ISD::MERGE_VALUES, Mul, N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, llvm::APFloatBase::rmNearestTiesToEven, llvm::ISD::SADDO, llvm::ISD::SADDO_CARRY, llvm::APInt::sext(), llvm::ISD::SMUL_LOHI, llvm::ISD::SSUBO, llvm::ISD::SSUBO_CARRY, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::TargetConstant, llvm::APInt::trunc(), llvm::ISD::UADDO, llvm::ISD::UADDO_CARRY, llvm::ISD::UMUL_LOHI, llvm::ISD::USUBO, llvm::ISD::USUBO_CARRY, llvm::SDVTList::VTs, llvm::ISD::XOR, and llvm::APInt::zext().
getNode() [20/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N)
Definition at line 11289 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [21/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2)
Definition at line 11295 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [22/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
Definition at line 11301 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [23/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 11307 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNode() [24/24]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 11313 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, DL, and getNode().
getNodeIfExists() [1/2]
SDNode * SelectionDAG::getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, bool AllowCommute = false)
getNodeIfExists - Get the specified node if it's already available, or else return NULL.
Definition at line 11899 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, and getNodeIfExists().
getNodeIfExists() [2/2]
SDNode * SelectionDAG::getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags, bool AllowCommute = false)
Get the specified node if it's already available, or else return NULL.
Definition at line 11908 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), Lookup(), llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
Referenced by combineBitcastToBoolVector(), combineSetCC(), combineX86AddSub(), getInvertedVectorForFMA(), getNodeIfExists(), performDUPCombine(), PerformExtractFpToIntStores(), performFlagSettingCombine(), performScalarToVectorCombine(), and tryToWidenSetCCOperands().
getNoMergeSiteInfo()
bool llvm::SelectionDAG::getNoMergeSiteInfo (const SDNode * Node) const inline
Return NoMerge info associated with Node.
Definition at line 2595 of file SelectionDAG.h.
References I.
getNOT()
SDValue SelectionDAG::getNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
getNOT - Create a bitwise NOT operation as (XOR Val, -1).
Definition at line 1616 of file SelectionDAG.cpp.
References DL, getAllOnesConstant(), getNode(), and llvm::ISD::XOR.
Referenced by combineAndNotOrIntoAndNotAnd(), combineAndnp(), combineAndXorSubWithBMI(), combineAVX512SetCCToKMOV(), combineMOVMSK(), combineSelect(), combineSelectOfTwoConstants(), combineSetCC(), combineSub(), combineSVEBitSel(), combineVectorPack(), combineVSelectWithAllOnesOrZeros(), combineXor(), emitFloatCompareMask(), emitVectorComparison(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandFunnelShift(), foldAndOrOfSETCC(), foldExtendedSignBitTest(), foldToMaskedStore(), foldVSelectToSignBitSplatMask(), getDataClassTest(), getI128Select(), getNode(), getNode(), getNode(), llvm::TargetLowering::LegalizeSetCCCondCode(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerMSABitClear(), lowerSELECT(), LowerVectorAllEqual(), lowerVectorBitClear(), LowerVSETCC(), LowerVSETCC(), narrowBitOpRMW(), performAnyAllCombine(), performBSPExpandForSVE(), performConcatVectorsCombine(), performINTRINSIC_WO_CHAINCombine(), performVANDNCombine(), performXORCombine(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), TryMatchTrue(), and visitORCommutative().
getObjectPtrOffset() [1/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Ptr, SDValue Offset) inline
Definition at line 1139 of file SelectionDAG.h.
References getMemBasePlusOffset(), llvm::SDNodeFlags::InBounds, llvm::SDNodeFlags::NoUnsignedWrap, and llvm::Offset.
getObjectPtrOffset() [2/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Ptr, TypeSize Offset) inline
Create an add instruction with appropriate flags when used for addressing some offset of an object.
i.e. if a load is split into multiple components, create an add nuw (or ptradd nuw inbounds) from the base pointer to the offset.
Definition at line 1134 of file SelectionDAG.h.
References getMemBasePlusOffset(), llvm::SDNodeFlags::InBounds, llvm::SDNodeFlags::NoUnsignedWrap, and llvm::Offset.
Referenced by llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), performExtractVectorEltCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::TargetLowering::SimplifySetCC(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
getOpcode_EXTEND()
unsigned llvm::SelectionDAG::getOpcode_EXTEND (unsigned Opcode) inline static
Convert *_EXTEND_VECTOR_INREG to *_EXTEND opcode.
Definition at line 984 of file SelectionDAG.h.
References llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm_unreachable, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by combineEXTEND_VECTOR_INREG(), and foldExtendVectorInregToExtendOfSubvector().
getOpcode_EXTEND_VECTOR_INREG()
unsigned llvm::SelectionDAG::getOpcode_EXTEND_VECTOR_INREG (unsigned Opcode) inline static
Convert *_EXTEND to *_EXTEND_VECTOR_INREG opcode.
Definition at line 1000 of file SelectionDAG.h.
References llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm_unreachable, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by combineEXTRACT_SUBVECTOR(), getEXTEND_VECTOR_INREG(), LowerAVXExtend(), and matchUnaryShuffle().
getOptLevel()
CodeGenOptLevel llvm::SelectionDAG::getOptLevel () const inline
Definition at line 497 of file SelectionDAG.h.
Referenced by llvm::FunctionLoweringInfo::set().
getORE()
OptimizationRemarkEmitter & llvm::SelectionDAG::getORE () const inline
Definition at line 512 of file SelectionDAG.h.
getPass()
const Pass * llvm::SelectionDAG::getPass () const inline
Definition at line 494 of file SelectionDAG.h.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::SITargetLowering::passSpecialInputs().
getPCSections()
MDNode * llvm::SelectionDAG::getPCSections (const SDNode * Node) const inline
Return PCSections associated with Node, or nullptr if none exists.
Definition at line 2567 of file SelectionDAG.h.
getPOISON()
SDValue llvm::SelectionDAG::getPOISON (EVT VT) inline
Return a POISON node. POISON does not have a useful SDLoc.
Definition at line 1189 of file SelectionDAG.h.
References getNode(), and llvm::ISD::POISON.
Referenced by adjustLoadValueTypeImpl(), buildFromShuffleMostly(), DoubleVectorWidth(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), llvm::TargetLowering::expandVectorFindLastActive(), getBuildDwordsVector(), getNode(), getNode(), llvm::SITargetLowering::LowerCall(), lowerFCMPIntrinsic(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerICMPIntrinsic(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), lowerWaveShuffle(), padEltsToUndef(), llvm::SITargetLowering::passSpecialInputs(), performBuildVectorCombine(), llvm::SITargetLowering::ReplaceNodeResults(), and llvm::AMDGPUTargetLowering::SplitVectorLoad().
getPseudoProbeNode()
SDValue SelectionDAG::getPseudoProbeNode (const SDLoc & Dl, SDValue Chain, uint64_t Guid, uint64_t Index, uint32_t Attr)
Creates a PseudoProbeSDNode with function GUID Guid and the index of the block Index it is probing, as well as the attributes attr of the probe.
Definition at line 9749 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), llvm::Guid, N, NewSDValueDbgMsg(), and llvm::ISD::PSEUDO_PROBE.
getPSI()
ProfileSummaryInfo * llvm::SelectionDAG::getPSI () const inline
Definition at line 513 of file SelectionDAG.h.
getPtrExtendInReg()
SDValue SelectionDAG::getPtrExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
This may be either a zero extend or a sign extend.
Definition at line 1605 of file SelectionDAG.cpp.
References DL, and getZeroExtendInReg().
getPtrExtOrTrunc()
SDValue SelectionDAG::getPtrExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
Definition at line 1599 of file SelectionDAG.cpp.
References DL, and getZExtOrTrunc().
Referenced by getLoadStackGuard().
getReducedAlign()
Align SelectionDAG::getReducedAlign (EVT VT, bool UseABI)
In most cases this function returns the ABI alignment for a given type, except for illegal vector types where the alignment exceeds that of the stack.
In such cases we attempt to break the vector down to a legal type and return the ABI alignment for that instead.
Definition at line 2570 of file SelectionDAG.cpp.
References DL, getContext(), getDataLayout(), getMachineFunction(), llvm::TargetFrameLowering::getStackAlign(), llvm::EVT::getTypeForEVT(), and llvm::EVT::isVector().
Referenced by llvm::TargetLowering::expandVECTOR_COMPRESS(), and llvm::TargetLowering::expandVectorSplice().
getRegister()
SDValue SelectionDAG::getRegister (Register Reg, EVT VT)
Definition at line 2367 of file SelectionDAG.cpp.
References AddNodeIDNode(), getVTList(), N, and llvm::ISD::Register.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildCallOperands(), createCMovFP(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), emitLockedStackOp(), emitRestoreZALazySave(), EmitUnrolledSetTag(), extractPtrauthBlendDiscriminators(), extractPtrauthBlendDiscriminators(), getADAEntry(), llvm::MipsTargetLowering::getAddrGPRel(), getCopyFromReg(), getCopyFromReg(), getCopyToReg(), getCopyToReg(), getDefaultScalableVLOps(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsTargetLowering::getGlobalReg(), llvm::MipsTargetLowering::getOpndList(), getPopFromX87Reg(), getPrefetchNode(), llvm::SITargetLowering::legalizeTargetIndependentNode(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), LowerMemOpCallTo(), lowerMSTORE(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), lowerVECTOR_SHUFFLE(), lowerVectorIntrinsicScalars(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), llvm::SITargetLowering::PostISelFolding(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegRegOnly(), selectConstantAddr(), llvm::PPCTargetLowering::SelectForceXFormMode(), selectImmSeq(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), selectSOffset(), and splatPartsI64WithVL().
getRegisterMask()
SDValue SelectionDAG::getRegisterMask (const uint32_t * RegMask)
Definition at line 2383 of file SelectionDAG.cpp.
References AddNodeIDNode(), getVTList(), N, and llvm::ISD::RegisterMask.
Referenced by buildCallOperands(), llvm::AArch64TargetLowering::changeStreamingMode(), emitRestoreZALazySave(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), and llvm::VETargetLowering::lowerToTLSGeneralDynamicModel().
getRoot()
const SDValue & llvm::SelectionDAG::getRoot () const inline
Return the root tag of the SelectionDAG.
Definition at line 578 of file SelectionDAG.h.
Referenced by llvm::checkForCycles(), dump(), Legalize(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), RemoveDeadNode(), RemoveDeadNodes(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), ReplaceAllUsesWith(), and ReplaceAllUsesWith().
getScatterVP()
SDValue SelectionDAG::getScatterVP (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType)
Definition at line 10497 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::isa(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), N, and NewSDValueDbgMsg().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine().
getSelect()
SDValue llvm::SelectionDAG::getSelect (const SDLoc & DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS, SDNodeFlags Flags = SDNodeFlags()) inline
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
Definition at line 1370 of file SelectionDAG.h.
References assert(), Cond, DL, getNode(), LHS, RHS, llvm::ISD::SELECT, and llvm::ISD::VSELECT.
Referenced by llvm::TargetLowering::BuildUDIV(), combineAnd(), combineAndnp(), combineConcatVectorOps(), combineFMinNumFMaxNum(), combineLogicBlendIntoPBLENDV(), combineMaskedLoadConstantMask(), combineSelect(), commuteSelect(), llvm::TargetLowering::CTTZTableLookup(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandIntMINMAX(), llvm::TargetLowering::expandRoundInexactToOdd(), llvm::TargetLowering::expandShlSat(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorFindLastActive(), foldBinOpIntoSelectIfProfitable(), foldBinOpIntoSelectIfProfitable(), foldSelectWithIdentityConstant(), llvm::TargetLowering::getNegatedExpression(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), lowerCttzElts(), lowerFMAXIMUM_FMINIMUM(), LowerFMINIMUM_FMAXIMUM(), lowerFREM(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), lowerINT_TO_FP_vXi64(), llvm::RISCVTargetLowering::LowerOperation(), LowerRotate(), lowerSELECT(), LowerShift(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBlend(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), llvm::HexagonTargetLowering::LowerVSELECT(), lowerWaveShuffle(), LowerZERO_EXTEND_Mask(), narrowExtractedVectorSelect(), PerformADDCombineWithOperands(), llvm::RISCVTargetLowering::PerformDAGCombine(), performSelectCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), signExtendBitcastSrcVector(), signExtendBitcastSrcVector(), takeInexpensiveLog2(), tryFoldSelectIntoOp(), tryToFoldExtendOfConstant(), tryToFoldExtendSelectLoad(), UnrollVectorOverflowOp(), and useInversedSetcc().
getSelectCC()
SDValue llvm::SelectionDAG::getSelectCC (const SDLoc & DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond, SDNodeFlags Flags = SDNodeFlags()) inline
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1380 of file SelectionDAG.h.
References Cond, DL, getCondCode(), getNode(), llvm::SDValue::getValueType(), LHS, RHS, and llvm::ISD::SELECT_CC.
Referenced by llvm::TargetLowering::createSelectForFMINNUM_FMAXNUM(), createVariablePermute(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandMUL_LOHI(), llvm::AMDGPUTargetLowering::LowerF64ToF16Safe(), lowerFP_TO_INT_SAT(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::R600TargetLowering::PerformDAGCombine(), and performFP_TO_INT_SATCombine().
getSelectionDAGInfo()
const SelectionDAGTargetInfo & llvm::SelectionDAG::getSelectionDAGInfo () const inline
Definition at line 506 of file SelectionDAG.h.
Referenced by combineCVTP2I_CVTTP2I(), combineFMA(), combineToVWMACC(), combineVFMADD_VLWithVFNEG_VL(), and performVFMADD_VLCombine().
getSetCC()
SDValue llvm::SelectionDAG::getSetCC (const SDLoc & DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Chain = SDValue(), bool IsSignaling = false) inline
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1341 of file SelectionDAG.h.
References assert(), Cond, DL, getCondCode(), getNode(), llvm::EVT::isVector(), LHS, RHS, llvm::ISD::SETCC, llvm::ISD::SETCC_INVALID, llvm::ISD::STRICT_FSETCC, and llvm::ISD::STRICT_FSETCCS.
Referenced by llvm::TargetLowering::buildSDIVPow2WithCMov(), llvm::TargetLowering::BuildUDIV(), combineAdd(), combineAnd(), combineBitcast(), combineExtractVectorElt(), combineExtSetcc(), combineFMinNumFMaxNum(), combineOr(), combinePredicateReduction(), combineSelect(), combineSetCC(), combineShiftAnd1ToBitTest(), combineSubOfBoolean(), combineToExtendBoolVectorInReg(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), commuteSelect(), ConvertCarryFlagToCarryValue(), convertIntLogicToFPLogic(), convertTwoLoadsAndCmpToVCMPEQUB(), llvm::TargetLowering::CTTZTableLookup(), emitOrXorXorTree(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandCTLZ(), llvm::TargetLowering::expandCTTZ(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::TargetLowering::expandFP_TO_UINT(), llvm::TargetLowering::expandIntMINMAX(), llvm::TargetLowering::expandIS_FPCLASS(), llvm::TargetLowering::expandMULO(), llvm::TargetLowering::expandRoundInexactToOdd(), llvm::TargetLowering::expandSADDSUBO(), llvm::TargetLowering::expandShiftParts(), llvm::TargetLowering::expandShlSat(), llvm::TargetLowering::expandUADDSUBO(), llvm::TargetLowering::expandVECTOR_COMPRESS(), foldAndOrOfSETCC(), FoldSetCC(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldVectorXorShiftIntoCmp(), foldVectorXorShiftIntoCmp(), foldXorTruncShiftIntoCmp(), getDataClassTest(), llvm::AMDGPUTargetLowering::getIsFinite(), llvm::AMDGPUTargetLowering::getIsLtSmallestNormal(), llvm::AMDGPUTargetLowering::getScaledLogInput(), llvm::TargetLowering::getSqrtInputTest(), llvm::TargetLowering::LegalizeSetCCCondCode(), lower1BitShuffle(), LowerADDSAT_SUBSAT(), lowerBUILD_VECTOR(), lowerCttzElts(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerEXTEND_VECTOR_INREG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP10Unsafe(), llvm::AMDGPUTargetLowering::lowerFEXP2(), llvm::AMDGPUTargetLowering::lowerFEXPUnsafe(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), lowerFMAXIMUM_FMINIMUM(), LowerFMINIMUM_FMAXIMUM(), llvm::HexagonTargetLowering::LowerFormalArguments(), lowerFREM(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::SITargetLowering::lowerGET_ROUNDING(), lowerINT_TO_FP_vXi64(), LowerIntVSETCC_AVX512(), LowerMULH(), LowerMULO(), llvm::RISCVTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), LowerShiftByScalarImmediate(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerTruncateVecI1(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), lowerVECTOR_SHUFFLE(), LowerVectorAllEqual(), LowerVectorCTLZInRegLUT(), LowerVSETCC(), lowerWaveShuffle(), performBitcastCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performMulVectorCmpZeroCombine(), performOrXorChainCombine(), performSELECTCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSETCCCombine(), performSETCCCombine(), performSETCCCombine(), performSignExtendSetCCCombine(), performVSelectCombine(), performXORCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), reverseZExtICmpCombine(), scalarizeExtractedBinOp(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), llvm::TargetLowering::softenSetCCOperands(), truncateAVX512SetCCNoBWI(), tryDemorganOfBooleanCondition(), trySwapVSelectOperands(), useInversedSetcc(), and widenVectorOpsToi8().
getSetCCVP()
SDValue llvm::SelectionDAG::getSetCCVP (const SDLoc & DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Mask, SDValue EVL) inline
Helper function to make it easier to build VP_SETCCs if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1358 of file SelectionDAG.h.
References assert(), Cond, DL, getCondCode(), getNode(), LHS, RHS, and llvm::ISD::SETCC_INVALID.
Referenced by llvm::TargetLowering::LegalizeSetCCCondCode().
getSetFPEnv()
SDValue SelectionDAG::getSetFPEnv (SDValue Chain, const SDLoc & dl, SDValue Ptr, EVT MemVT, MachineMemOperand * MMO)
Definition at line 10822 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), N, NewSDValueDbgMsg(), and llvm::ISD::SET_FPENV_MEM.
getSExtOrTrunc()
SDValue SelectionDAG::getSExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
Definition at line 1496 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, getNode(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::TRUNCATE.
Referenced by combineAdd(), combineGatherScatter(), combineShuffleOfScalars(), combineToExtendBoolVectorInReg(), createVPDPBUSD(), llvm::TargetLowering::CTTZTableLookup(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandCMP(), llvm::TargetLowering::expandFP_TO_SINT(), foldCONCAT_VECTORS(), getBitcastedSExtOrTrunc(), getExtOrTrunc(), getExtOrTrunc(), getNode(), LowerADDSUBSAT(), LowerBITCAST(), LowerFLDEXP(), llvm::HexagonTargetLowering::LowerLoad(), LowerMULO(), llvm::HexagonTargetLowering::LowerSETCC(), llvm::HexagonTargetLowering::LowerVECTOR_SHIFT(), LowerVectorAllEqual(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerVSETCC(), llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulLoHiCombine(), and vectorToScalarBitmask().
getShiftAmountConstant() [1/2]
SDValue SelectionDAG::getShiftAmountConstant (const APInt & Val, EVT VT, const SDLoc & DL)
Definition at line 1812 of file SelectionDAG.cpp.
References assert(), DL, llvm::EVT::getScalarSizeInBits(), getShiftAmountConstant(), llvm::APInt::getZExtValue(), and llvm::APInt::ult().
getShiftAmountConstant() [2/2]
SDValue SelectionDAG::getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc & DL)
Definition at line 1805 of file SelectionDAG.cpp.
References assert(), DL, getConstant(), getDataLayout(), and llvm::EVT::isInteger().
Referenced by llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::buildSDIVPow2WithCMov(), llvm::TargetLowering::BuildUDIV(), combineExtractWithShuffle(), combineNarrowableShiftedLoad(), combinePMULH(), combineTruncate(), combineXorToBitfieldInsert(), llvm::TargetLowering::CTTZTableLookup(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandCLMUL(), llvm::TargetLowering::expandCTPOP(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), expandMulToNAFSequence(), llvm::TargetLowering::expandUINT_TO_FP(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVPCTPOP(), extractShiftForRotate(), foldSubCtlzNot(), foldVSelectToSignBitSplatMask(), llvm::TargetLowering::forceExpandMultiply(), llvm::TargetLowering::forceExpandWideMUL(), getCopyFromParts(), getCopyToParts(), GetExponent(), getLimitedPrecisionExp2(), getShiftAmountConstant(), llvm::AMDGPUTargetLowering::loadInputValue(), LowerCTPOP(), LowerFunnelShift(), LowerINTRINSIC_W_CHAIN(), llvm::RISCVTargetLowering::LowerOperation(), LowerRotate(), lowerWaveShuffle(), matchBSwapHWordOrAndAnd(), narrowBitOpRMW(), llvm::SITargetLowering::passSpecialInputs(), performBITCASTCombine(), performBitcastCombine(), performCONDCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), and visitORCommutative().
getShiftAmountOperand()
SDValue SelectionDAG::getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
getShiftAmountOperand - Return the specified value casted to the target's desired shift amount type.
Definition at line 2514 of file SelectionDAG.cpp.
References getDataLayout(), getZExtOrTrunc(), and llvm::EVT::isVector().
Referenced by LowerCTPOP(), and UnrollVectorOp().
getSignedConstant()
SDValue SelectionDAG::getSignedConstant (int64_t Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1788 of file SelectionDAG.cpp.
References DL, getConstant(), llvm::EVT::getScalarSizeInBits(), and Size.
Referenced by llvm::TargetLowering::BuildSDIV(), combineOrAndToBitfieldInsert(), combineOrToBitfieldInsert(), combineSetCC(), combineShlAddIAddImpl(), constantFoldBFE(), emitMemMemReg(), expandVAArg(), foldMaskedShiftToScaledMask(), getAArch64Cmp(), getCSAddressAndShifts(), getNode(), llvm::AVRTargetLowering::getPreIndexedAddressParts(), getSignedTargetConstant(), isBLACompatibleAddress(), lowerBuildVectorOfConstants(), lowerBuildVectorViaVID(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), LowerFP_TO_INT_SAT(), llvm::RISCVTargetLowering::LowerOperation(), lowerShuffleAsBlend(), llvm::VETargetLowering::lowerVAARG(), lowerVECTOR_SHUFFLE_VSHUF(), LowerVECTOR_SHUFFLEv8i8(), narrowBitOpRMW(), performCONCAT_VECTORSCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performMulRdsvlCombine(), performORCombine(), performORCombine(), performSELECT_CCCombine(), performSETCCCombine(), performSETCCCombine(), performVP_REVERSECombine(), performVP_STORECombine(), transformAddImmMulImm(), translateSetCCForBranch(), tryCombineShiftImm(), and tryConvertSVEWideCompare().
getSignedTargetConstant()
SDValue llvm::SelectionDAG::getSignedTargetConstant (int64_t Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 719 of file SelectionDAG.h.
References DL, and getSignedConstant().
Referenced by accumulateOffset(), llvm::PPC::get_VSPLTI_elt(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::M68kTargetLowering::LowerAsmOperandForConstraint(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), selectConstantAddr(), selectImm(), selectImmSeq(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), and selectVSplatImmHelper().
getSplat()
SDValue llvm::SelectionDAG::getSplat (EVT VT, const SDLoc & DL, SDValue Op) inline
Returns a node representing a splat of one value into all lanes of the provided vector type.
This is a utility which returns either a BUILD_VECTOR or SPLAT_VECTOR depending on the scalability of the desired vector type.
Definition at line 923 of file SelectionDAG.h.
References assert(), DL, getSplatBuildVector(), getSplatVector(), llvm::EVT::isScalableVector(), and llvm::EVT::isVector().
Referenced by combineToExtendBoolVectorInReg(), llvm::TargetLowering::expandVPCTTZElements(), getConstant(), getConstantFP(), isNOT(), lowerVECTOR_SHUFFLE(), performCONCAT_VECTORSCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performVANDNCombine(), refineUniformBase(), scalarizeBinOpOfSplats(), and takeInexpensiveLog2().
getSplatBuildVector()
SDValue llvm::SelectionDAG::getSplatBuildVector (EVT VT, const SDLoc & DL, SDValue Op) inline
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
VT must be a vector type. Op's type must be the same as (or, for integers, a type wider than) VT's element type.
Definition at line 890 of file SelectionDAG.h.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::EVT::bitsLE(), llvm::ISD::BUILD_VECTOR, DL, getNode(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isInteger(), and llvm::ISD::UNDEF.
Referenced by combineGatherScatter(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), getMemsetValue(), getSplat(), getVectorShuffle(), lowerBUILD_VECTOR(), lowerBuildVectorAsBlend(), and lowerBuildVectorViaDominantValues().
getSplatSourceVector()
SDValue SelectionDAG::getSplatSourceVector (SDValue V, int & SplatIndex)
If V is a splatted value, return the source vector and its splat index.
Definition at line 3104 of file SelectionDAG.cpp.
References assert(), llvm::cast(), llvm::countr_one(), llvm::APInt::getAllOnes(), getUNDEF(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), isSplatValue(), llvm::APInt::isSubsetOf(), llvm::peekThroughExtractSubvectors(), llvm::ISD::SPLAT_VECTOR, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by getSplatValue(), LowerFunnelShift(), LowerRotate(), LowerShiftByScalarVariable(), and scalarizeBinOpOfSplats().
getSplatValue()
SDValue SelectionDAG::getSplatValue (SDValue V, bool LegalTypes = false)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
If LegalTypes is true, this method may only return a legally-typed splat value. If it cannot legalize the splatted value it will return SDValue().
Definition at line 3156 of file SelectionDAG.cpp.
References llvm::EVT::bitsLT(), getContext(), getExtractVectorElt(), llvm::EVT::getScalarType(), getSplatSourceVector(), and llvm::EVT::isInteger().
Referenced by canLowerSRLToRoundingShiftForVT(), findMoreOptimalIndexType(), foldIndexIntoBase(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformVSetCCToVCTPCombine(), and refineUniformBase().
getSplatVector()
SDValue llvm::SelectionDAG::getSplatVector (EVT VT, const SDLoc & DL, SDValue Op) inline
Definition at line 907 of file SelectionDAG.h.
References assert(), llvm::EVT::bitsLE(), DL, getNode(), llvm::EVT::getVectorElementType(), llvm::EVT::isInteger(), llvm::ISD::SPLAT_VECTOR, and llvm::ISD::UNDEF.
Referenced by BuildExactSDIV(), BuildExactUDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), FoldConstantArithmetic(), getSplat(), getWideningInterleave(), lowerBUILD_VECTOR(), LowerVectorMatch(), and trySVESplat64().
GetSplitDestVTs()
std::pair< EVT, EVT > SelectionDAG::GetSplitDestVTs (const EVT & VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
GetSplitDestVTs - Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
Definition at line 13645 of file SelectionDAG.cpp.
References getContext(), llvm::EVT::getHalfNumVectorElementsVT(), and llvm::EVT::isVector().
Referenced by llvm::TargetLowering::expandVectorNaryOpBySplitting(), LowerCVTPS2PH(), LowerMULO(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), SplitStrictFPVectorOp(), llvm::SITargetLowering::splitTernaryVectorOp(), SplitVector(), SplitVectorOp(), splitVectorOp(), SplitVPOp(), and splitVSETCC().
getSrcValue()
SDValue SelectionDAG::getSrcValue (const Value * v)
Construct a node to track a Value* through the backend.
Definition at line 2442 of file SelectionDAG.cpp.
References AddNodeIDNode(), getVTList(), N, and llvm::ISD::SRCVALUE.
getStackArgumentTokenFactor()
SDValue SelectionDAG::getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
getStackArgumentTokenFactor - Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
This is used in tail call lowering to protect stack arguments from being clobbered.
Definition at line 8514 of file SelectionDAG.cpp.
References llvm::dyn_cast(), getEntryNode(), getNode(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::TokenFactor, and users.
Referenced by llvm::LoongArchTargetLowering::LowerCall().
getStepVector() [1/2]
SDValue SelectionDAG::getStepVector (const SDLoc & DL, EVT ResVT)
Returns a vector of type ResVT whose elements contain the linear sequence <0, 1, 2, 3, ...>.
Definition at line 2159 of file SelectionDAG.cpp.
References DL, llvm::EVT::getScalarSizeInBits(), and getStepVector().
getStepVector() [2/2]
SDValue SelectionDAG::getStepVector (const SDLoc & DL, EVT ResVT, const APInt & StepVal)
Returns a vector of type ResVT whose elements contain the linear sequence <0, Step, Step * 2, Step * 3, ...>.
Definition at line 2164 of file SelectionDAG.cpp.
References assert(), DL, llvm::APInt::getBitWidth(), getBuildVector(), getConstant(), getNode(), llvm::EVT::getScalarSizeInBits(), getTargetConstant(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ISD::STEP_VECTOR.
Referenced by llvm::TargetLowering::expandVectorFindLastActive(), llvm::TargetLowering::expandVPCTTZElements(), findMoreOptimalIndexType(), FoldConstantArithmetic(), getStepVector(), and LowerSVEIntrinsicIndex().
getStore() [1/4]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 9963 of file SelectionDAG.cpp.
References getStore(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
getStore() [2/4]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Helper function to build ISD::STORE nodes.
This function will set the MOStore flag on MMOFlags, but you can set it if you want. The MOLoad and MOInvariant flags must not be set.
Definition at line 9943 of file SelectionDAG.cpp.
References assert(), getMachineFunction(), getStore(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, Size, and llvm::MachinePointerInfo::V.
Referenced by combineBoolVectorAndTruncateStore(), combineI8TruncStore(), combineStore(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVAArg(), expandVACopy(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorSplice(), foldTruncStoreOfExt(), getIndexedStore(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getStore(), getStore(), getStore(), getTruncStore(), LowerATOMIC_STORE(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), LowerF128Store(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerFP_TO_SINT_STORE(), LowerMemOpCallTo(), lowerMSAStoreIntr(), llvm::RISCVTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), LowerSTORE(), LowerStore(), lowerStoreF128(), lowerStoreI1(), LowerTruncateVectorStore(), LowerVAARG(), llvm::VETargetLowering::lowerVAARG(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), LowerVASTART(), LowerVASTART(), LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), memsetStore(), narrowBitOpRMW(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), PerformSTORECombine(), performSTORECombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformTruncatingStoreCombine(), reduceMaskedStoreToScalarStore(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), splitStores(), splitStoreSplat(), splitVectorStore(), llvm::AMDGPUTargetLowering::storeStackInputValue(), and StoreTailCallArgumentsToStackSlot().
getStore() [3/4]
SDValue llvm::SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1530 of file SelectionDAG.h.
References getEVTAlign(), getStore(), llvm::SDValue::getValueType(), and llvm::MachineMemOperand::MONone.
getStore() [4/4]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Offset, EVT SVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false)
Definition at line 9970 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), Indexed, llvm::EVT::isInteger(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), llvm::Offset, llvm::ISD::STORE, and llvm::ISD::UNINDEXED.
getStoreVP()
SDValue SelectionDAG::getStoreVP (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 10177 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), Indexed, N, NewSDValueDbgMsg(), llvm::Offset, and llvm::ISD::UNINDEXED.
Referenced by getTruncStoreVP(), and llvm::RISCVTargetLowering::PerformDAGCombine().
getStrcpy()
std::pair< SDValue, SDValue > SelectionDAG::getStrcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, const CallInst * CI)
Lower a strcpy operation into a target library call and return the resulting chain and call result as SelectionDAG SDValues.
Definition at line 9176 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::Value::getType(), llvm::PointerType::getUnqual(), isInTailCallPositionWrapper(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), and llvm::TargetLowering::CallLoweringInfo::setTailCall().
Referenced by llvm::PPCSelectionDAGInfo::EmitTargetCodeForStrcpy().
getStrictFPExtendOrRound()
std::pair< SDValue, SDValue > SelectionDAG::getStrictFPExtendOrRound (SDValue Op, SDValue Chain, const SDLoc & DL, EVT VT)
Convert Op, which must be a STRICT operation of float type, to the float type VT, by either extending or rounding (by truncation).
Definition at line 1477 of file SelectionDAG.cpp.
References assert(), llvm::EVT::bitsEq(), llvm::EVT::bitsGT(), DL, getIntPtrConstant(), llvm::SDValue::getNode(), getNode(), llvm::ISD::STRICT_FP_EXTEND, and llvm::ISD::STRICT_FP_ROUND.
Referenced by llvm::RISCVTargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), and LowerUINT_TO_FP_i32().
getStridedLoadVP() [1/2]
SDValue SelectionDAG::getStridedLoadVP (EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 10350 of file SelectionDAG.cpp.
References DL, getStridedLoadVP(), getUNDEF(), llvm::SDValue::getValueType(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::UNINDEXED.
getStridedLoadVP() [2/2]
SDValue SelectionDAG::getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 10316 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), DL, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), Indexed, N, NewSDValueDbgMsg(), llvm::Offset, and llvm::ISD::UNINDEXED.
Referenced by getExtStridedLoadVP(), getStridedLoadVP(), performCONCAT_VECTORSCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), and performVP_REVERSECombine().
getStridedStoreVP()
SDValue SelectionDAG::getStridedStoreVP (SDValue Chain, const SDLoc & DL, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 10369 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::cast(), DL, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::SDValue::getValueType(), getVTList(), Indexed, N, NewSDValueDbgMsg(), llvm::Offset, and llvm::ISD::UNINDEXED.
Referenced by getTruncStridedStoreVP(), and performVP_STORECombine().
getStrlen()
std::pair< SDValue, SDValue > SelectionDAG::getStrlen (SDValue Chain, const SDLoc & dl, SDValue Src, const CallInst * CI)
Lower a strlen operation into a target library call and return the resulting chain and call result as SelectionDAG SDValues.
Definition at line 9202 of file SelectionDAG.cpp.
References getContext(), getDataLayout(), getExternalSymbol(), llvm::Value::getType(), llvm::PointerType::getUnqual(), isInTailCallPositionWrapper(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), and llvm::TargetLowering::CallLoweringInfo::setTailCall().
Referenced by llvm::PPCSelectionDAGInfo::EmitTargetCodeForStrlen().
getSubtarget() [1/2]
template<typename STC> const STC & llvm::SelectionDAG::getSubtarget () const inline
Definition at line 501 of file SelectionDAG.h.
getSubtarget() [2/2]
const TargetSubtargetInfo & llvm::SelectionDAG::getSubtarget () const inline
Definition at line 500 of file SelectionDAG.h.
Referenced by adjustICmp128(), buildPCRelGlobalAddress(), combineCommutableSHUFP(), emitComparison(), emitConditionalComparison(), emitStrictFPComparison(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::RISCVSelectionDAGInfo::EmitTargetCodeForMemset(), findMoreOptimalIndexType(), GenerateFixedLengthSVETBL(), getPTrue(), GetTLSADDR(), init(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), lowerMSASplatZExt(), lowerTensormapReplaceElemtype(), lowerTensormapReplaceSwizzleMode(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), optimizeIncrementingWhile(), patchMatchingInput(), performBuildVectorCombine(), performSVEMulAddSubCombine(), performTBISimplification(), recoverFramePointer(), truncateVecElts(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryLowerSmallVectorExtLoad(), tryLowerToBSL(), unpackF64OnRV32DSoftABI(), vectorToScalarBitmask(), and llvm::SDNodeInfo::verifyNode().
getSymbolFunctionGlobalAddress()
SDValue SelectionDAG::getSymbolFunctionGlobalAddress (SDValue Op, Function ** TargetFunction = nullptr)
Return a GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
Additionally can provide the matched function. Panic if the function doesn't exist.
Definition at line 12845 of file SelectionDAG.cpp.
References assert(), llvm::cast(), llvm::GlobalValue::getAddressSpace(), getDataLayout(), llvm::Module::getFunction(), getGlobalAddress(), llvm::GlobalValue::getParent(), llvm::isa(), and llvm::report_fatal_error().
Referenced by llvm::NVPTXTargetLowering::LowerCall().
getTarget()
const TargetMachine & llvm::SelectionDAG::getTarget () const inline
Definition at line 499 of file SelectionDAG.h.
Referenced by canOptimizeTLSDFormToXForm(), combineFaddCFmul(), combineFMinFMax(), combineFMinNumFMaxNum(), combineSelect(), llvm::RISCVTargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandIndirectJTBranch(), llvm::X86TargetLowering::expandIndirectJTBranch(), foldFPToIntToFP(), getMemset(), GetTLSADDR(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isEligibleToFoldADDIForFasterLocalAccesses(), isInTailCallPositionWrapper(), isKnownNeverNaN(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), LowerFMINIMUM_FMAXIMUM(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), and transformCallee().
getTargetBlockAddress()
SDValue llvm::SelectionDAG::getTargetBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 813 of file SelectionDAG.h.
References getBlockAddress(), and llvm::Offset.
Referenced by getTargetNode(), getTargetNode(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetConstant() [1/3]
SDValue llvm::SelectionDAG::getTargetConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 711 of file SelectionDAG.h.
References DL, and getConstant().
getTargetConstant() [2/3]
SDValue llvm::SelectionDAG::getTargetConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 715 of file SelectionDAG.h.
References DL, and getConstant().
getTargetConstant() [3/3]
SDValue llvm::SelectionDAG::getTargetConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 707 of file SelectionDAG.h.
References DL, and getConstant().
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildPCRelGlobalAddress(), buildRegSequence16(), buildRegSequence32(), llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), canonicalizeBitSelect(), llvm::AArch64TargetLowering::changeStreamingMode(), checkCVTFixedPointOperandWithFBits(), llvm::SITargetLowering::CollectTargetIntrinsicOperands(), combineADC(), combineAddOrSubToADCOrSBB(), combineAndMaskToShift(), combineAndOrForCcmpCtest(), combineBitcastToBoolVector(), combineBrCond(), combineCMov(), combineCommutableSHUFP(), combineCompareEqual(), combineConcatVectorOps(), combineEXTRACT_SUBVECTOR(), combineExtractWithShuffle(), combineFP16_TO_FP(), combineFP_ROUND(), combineFunnelShift(), combineINSERT_SUBVECTOR(), combineKSHIFT(), combineShlAddIAddImpl(), combineStore(), combineSVEPrefetchVecBaseImmOff(), combineTargetShuffle(), llvm::VETargetLowering::combineTRUNCATE(), combineVectorShiftImm(), combineX86CloadCstore(), combineX86ShuffleChain(), combineX86SubCmpForFlags(), createGPRPairNode(), createGPRPairNode2xi32(), createMMXBuildVector(), createSetFPEnvNodes(), createVariablePermute(), EmitAVX512Test(), emitCmp(), emitLockedStackOp(), emitRestoreZALazySave(), emitSETCC(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::RISCVSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), expandBitCastI128ToF128(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), expandFP_TO_UINT_SSE(), expandMul(), expandMulToShlAddShlAdd(), ExtractBitFromMaskVector(), extractPtrauthBlendDiscriminators(), extractPtrauthBlendDiscriminators(), GenerateFixedLengthSVETBL(), GenerateTBL(), llvm::PPC::get_VSPLTI_elt(), getADAEntry(), getAL(), getAVX2GatherNode(), getCopyFromParts(), getDataClassTest(), getGatherNode(), getGeneralPermuteNode(), getIntOperandsFromRegisterString(), getJumpTableDebugInfo(), getLeftShift(), getPack(), getPermuteNode(), getPrefetchNode(), getPTrue(), getScatterNode(), getSETCC(), getShlAddShlAdd(), getSHUFPDImmForMask(), getSPDenormModeValue(), getStepVector(), getTargetExtractSubreg(), getTargetInsertSubreg(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getUniformBase(), getV4X86ShuffleImm8ForMask(), getVAArg(), getVShift(), getVSlidedown(), getVSlideup(), getZeroVector(), insert1BitVector(), InvertCarryFlag(), isVMOVModifiedImm(), isWorthFoldingIntoOrrWithShift(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerABD(), LowerABS(), LowerADDRSPACECAST(), llvm::AVRTargetLowering::LowerAsmOperandForConstraint(), llvm::LanaiTargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::SITargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::VETargetLowering::lowerATOMIC_FENCE(), LowerBITREVERSE(), LowerBuildVectorv4x32(), llvm::SITargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), LowerCMP_SWAP(), LowerCONCAT_VECTORSvXi1(), LowerCTLZ(), LowerCTTZ(), LowerCTTZ(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerF128Load(), LowerF128Store(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP2(), lowerFixedVectorSegLoadIntrinsics(), lowerFixedVectorSegStoreIntrinsics(), LowerFLDEXP(), llvm::AMDGPUTargetLowering::LowerFLOG2(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), LowerFMINIMUM_FMAXIMUM(), llvm::VETargetLowering::LowerFormalArguments(), LowerFP_TO_FP16(), lowerFP_TO_INT_SAT(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), llvm::SITargetLowering::lowerGET_FPENV(), llvm::SITargetLowering::lowerGET_ROUNDING(), lowerGetVectorLength(), LowerINTRINSIC_W_CHAIN(), lowerLaneOp(), lowerLoadF128(), lowerLoadI1(), LowerMLOAD(), LowerMUL(), llvm::RISCVTargetLowering::LowerOperation(), LowerPREFETCH(), LowerPtrAuthGlobalAddressStatically(), lowerReductionSeq(), llvm::SITargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), LowerRotate(), lowerSelectToBinOp(), LowerSELECTWithCmpZero(), llvm::SITargetLowering::lowerSET_FPENV(), llvm::SITargetLowering::lowerSET_ROUNDING(), LowerShift(), LowerShiftByScalarImmediate(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsShift(), lowerShuffleAsSpecificExtension(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleWithSHUFPD(), lowerShuffleWithSSE4A(), LowerSMELdrStr(), LowerSTORE(), lowerStoreF128(), lowerStoreI1(), lowerUINT_TO_FP_vXi32(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4F64Shuffle(), lowerV8F64Shuffle(), lowerV8I16Shuffle(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), lowerVECTOR_SHUFFLE_XVSHUF(), LowerVectorCTLZ_GFNI(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorIntrinsicScalars(), LowerVectorMatch(), lowerVectorXRINT_XROUND(), LowerVSETCC(), lowerWaveShuffle(), optimizeLogicalImm(), parseTexFail(), performActiveLaneMaskCombine(), performAddTruncShiftCombine(), performConcatVectorsCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), performFpToIntCombine(), PerformHWLoopCombine(), performVANDNCombine(), performZExtUZPCombine(), PromoteMVEPredVector(), ReconstructShuffleWithRuntimeMask(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), llvm::PPCTargetLowering::SelectAddressRegImm(), selectConstantAddr(), selectI64Imm(), selectI64Imm(), selectI64ImmDirect(), selectI64ImmDirectPrefix(), selectImm(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), transformAddShlImm(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), tryCombineShiftImm(), tryLowerToSLI(), tryOrrWithShift(), trySimplifySrlAddToRshrnb(), tryToConvertShuffleOfTbl2ToTbl4(), llvm::X86TargetLowering::visitMaskedLoad(), llvm::X86TargetLowering::visitMaskedStore(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getTargetConstantFP() [1/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT) inline
Definition at line 746 of file SelectionDAG.h.
References DL, and getConstantFP().
getTargetConstantFP() [2/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const ConstantFP & Val, const SDLoc & DL, EVT VT) inline
Definition at line 749 of file SelectionDAG.h.
References DL, and getConstantFP().
getTargetConstantFP() [3/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (double Val, const SDLoc & DL, EVT VT) inline
Definition at line 743 of file SelectionDAG.h.
References DL, and getConstantFP().
getTargetConstantPool() [1/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (const Constant * C, EVT VT, MaybeAlign Align = std::nullopt, int Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 778 of file SelectionDAG.h.
References llvm::CallingConv::C, getConstantPool(), and llvm::Offset.
Referenced by getLargeExternalSymbol(), getLargeGlobalAddress(), getTargetNode(), getTargetNode(), getTargetNode(), llvm::XtensaTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::LanaiTargetLowering::LowerConstantPool(), promoteToConstantPool(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetConstantPool() [2/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (MachineConstantPoolValue * C, EVT VT, MaybeAlign Align = std::nullopt, int Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 787 of file SelectionDAG.h.
References llvm::CallingConv::C, getConstantPool(), and llvm::Offset.
getTargetExternalSymbol() [1/2]
SDValue SelectionDAG::getTargetExternalSymbol (const char * Sym, EVT VT, unsigned TargetFlags = 0)
Definition at line 2083 of file SelectionDAG.cpp.
References getVTList(), and N.
Referenced by emitRestoreZALazySave(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), getTagSymNode(), getTargetExternalSymbol(), GetTLSADDR(), getzOSCalleeAndADA(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::VETargetLowering::lowerDYNAMIC_STACKALLOC(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), selectBaseADDR(), transformCallee(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetExternalSymbol() [2/2]
SDValue SelectionDAG::getTargetExternalSymbol (RTLIB::LibcallImpl LCImpl, EVT VT, unsigned TargetFlags = 0)
Definition at line 2093 of file SelectionDAG.cpp.
References llvm::StringRef::data(), and getTargetExternalSymbol().
getTargetExtractSubreg()
SDValue SelectionDAG::getTargetExtractSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
getTargetExtractSubreg - A convenience function for creating TargetOpcode::EXTRACT_SUBREG nodes.
Definition at line 11879 of file SelectionDAG.cpp.
References DL, getMachineNode(), and getTargetConstant().
Referenced by llvm::SITargetLowering::buildRSRC(), convertToF16(), expandBitCastF128ToI128(), LowerF64Op(), LowerFNEGorFABS(), lowerGR128Binary(), lowerGR128ToI128(), narrowIfNeeded(), NarrowVector(), performSTORECombine(), ReplaceCMP_SWAP_128Results(), and ReplaceCMP_SWAP_64Results().
getTargetFrameIndex()
SDValue llvm::SelectionDAG::getTargetFrameIndex (int FI, EVT VT) inline
Definition at line 764 of file SelectionDAG.h.
References getFrameIndex().
Referenced by addStackMapLiveVars(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), selectBaseADDR(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), and SelectSAddrFI().
getTargetGlobalAddress()
SDValue llvm::SelectionDAG::getTargetGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, unsigned TargetFlags = 0) inline
Definition at line 758 of file SelectionDAG.h.
References DL, and getGlobalAddress().
Referenced by buildPCRelGlobalAddress(), combineADDToMAT_PCREL_ADDR(), foldADDIForFasterLocalAccesses(), getADAEntry(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getTargetNode(), getTargetNode(), GetTLSADDR(), getzOSCalleeAndADA(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), selectBaseADDR(), transformCallee(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetInsertSubreg()
SDValue SelectionDAG::getTargetInsertSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
getTargetInsertSubreg - A convenience function for creating TargetOpcode::INSERT_SUBREG nodes.
Definition at line 11889 of file SelectionDAG.cpp.
References DL, getMachineNode(), and getTargetConstant().
Referenced by convertFromF16(), LowerF64Op(), LowerFNEGorFABS(), and Widen().
getTargetJumpTable()
SDValue llvm::SelectionDAG::getTargetJumpTable (int JTI, EVT VT, unsigned TargetFlags = 0) inline
Definition at line 769 of file SelectionDAG.h.
References getJumpTable().
Referenced by llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), getTargetNode(), getTargetNode(), getTargetNode(), llvm::HexagonTargetLowering::LowerJumpTable(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), and llvm::VETargetLowering::withTargetFlags().
getTargetLoweringInfo()
const TargetLowering & llvm::SelectionDAG::getTargetLoweringInfo () const inline
Definition at line 504 of file SelectionDAG.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), buildFromShuffleMostly(), canonicalizeShuffleWithOp(), combineAdd(), combineAddOrSubToADCOrSBB(), combineAnd(), combineAndNotOrIntoAndNotAnd(), combineAndnp(), combineAndShuffleNot(), combineBEXTR(), combineBinOpOfZExt(), combineBitcast(), combineBitcastToBoolVector(), combineBITREVERSE(), combineBT(), combineCMP(), combineCONCAT_VECTORS(), combineConcatVectorOfCasts(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractFromVectorLoad(), combineExtractVectorElt(), combineFMA(), combineFMADDSUB(), combineFMinNumFMaxNum(), combineFneg(), combineFunnelShift(), combineGatherScatter(), combineKSHIFT(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineLRINT_LLRINT(), combineMaskedLoad(), combineMaskedStore(), combineMOVMSK(), combineOr(), combinePDEP(), combinePMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineScalarAndWithMaskSetcc(), combineSelect(), combineSelectAsExtAnd(), combineSelectOfTwoConstants(), combineSetCC(), combineShiftAnd1ToBitTest(), combineShuffle(), combineShuffleToFMAddSub(), combineStore(), combineTargetShuffle(), combineTESTP(), combineToVCPOP(), combineTruncate(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineTruncSelectToSMaxUSat(), combineVectorInsert(), combineVectorMulToSraBitcast(), combineVectorShiftImm(), combineVectorShiftVar(), combineVEXTRACT_STORE(), combineVPMADD(), combineVPMADD52LH(), combineVSelectToBLENDV(), combineVTRUNC(), combineX86GatherScatter(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), combineXor(), createMMXBuildVector(), createSetFPEnvNodes(), detectEvenOddMultiplyOperand(), EltsFromConsecutiveLoads(), emitRestoreZALazySave(), expandBitCastF128ToI128(), expandBitCastI128ToF128(), ExpandPowI(), expandVAArg(), expandVACopy(), llvm::TargetLowering::expandVectorFindLastActive(), foldAndOrOfSETCC(), foldBoolSelectToLogic(), foldCONCAT_VECTORS(), foldExtendedSignBitTest(), foldExtractSubvectorFromShuffleVector(), foldSelectWithIdentityConstant(), foldShuffleOfConcatUndefs(), foldSubCtlzNot(), foldToMaskedStore(), foldVSelectToSignBitSplatMask(), foldXorTruncShiftIntoCmp(), formSplatFromShuffles(), getADAEntry(), getAddressForMemoryInput(), getAVX2GatherNode(), getAVX512Node(), getAVX512TruncNode(), getBT(), getConstVector(), getConstVector(), getContainerForFixedLengthVector(), getContainerForFixedLengthVector(), getCopyFromParts(), getCopyFromPartsVector(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), getGatherNode(), getJumpTableDebugInfo(), getKnownUndefForVectorBinop(), getLifetimeNode(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetValue(), getPredicateForFixedLengthVector(), getPredicateForScalableVector(), getPrefetchNode(), getPTest(), getRegistersForValue(), getScatterNode(), getSVEPredicateBitCast(), getTagSymNode(), getUniformBase(), getVCIXISDNodeWCHAIN(), getZeroVector(), getzOSCalleeAndADA(), getZT0FrameIndex(), isAddSubOrSubAdd(), isBLACompatibleAddress(), isConsecutiveLSLoc(), isKnownToBeAPowerOfTwo(), IsNOT(), isNOT(), isPackedVectorType(), LowerABD(), LowerADDRSPACECAST(), LowerADDSAT_SUBSAT(), LowerADDSUBO_CARRY(), LowerATOMIC_STORE(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), LowerCTPOP(), LowerCTPOP(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFMINIMUM_FMAXIMUM(), lowerGR128ToI128(), lowerI128ToGR128(), LowerMemOpCallTo(), LowerMSCATTER(), LowerMULO(), LowerRotate(), LowerShiftParts(), lowerShuffleAsElementInsertion(), lowerShuffleAsShift(), LowerStore(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), LowerVASTART(), LowerVASTART(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLEAsShift(), LowerVectorAllEqual(), LowerVSETCC(), LowerXALUO(), matchLSNode(), matchRotateSub(), matchSplatAsGather(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowInsertExtractVectorBinOp(), narrowShuffle(), patchMatchingInput(), performAddCSelIntoCSinc(), performAddSubIntoVectorOp(), PerformANDCombine(), performANDCombine(), PerformARMBUILD_VECTORCombine(), performBICiCombine(), performBuildVectorCombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performExtBinopLoadFold(), PerformExtendCombine(), PerformExtractEltToVMOVRRD(), performExtractLastActiveCombine(), PerformFADDCombineWithOperands(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), performFpToIntCombine(), performGatherLoadCombine(), PerformInsertSubvectorCombine(), performInsertSubvectorCombine(), performInterleavedMaskedStoreCombine(), PerformLOADCombine(), performLOADCombine(), PerformMinMaxFpToSatCombine(), PerformORCombine(), PerformPREDICATE_CASTCombine(), performScatterStoreCombine(), performSelectCombine(), PerformShiftCombine(), PerformSTORECombine(), performSTORECombine(), performTBISimplification(), PerformTruncatingStoreCombine(), PerformUMinFpToSatCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), performVectorDeinterleaveCombine(), PerformVMOVhrCombine(), PerformVMOVNCombine(), performVMSKLTZCombine(), performVP_TRUNCATECombine(), PerformVQMOVNCombine(), PerformVSetCCToVCTPCombine(), PerformXORCombine(), performXORCombine(), PromoteMaskArithmetic(), reduceBuildVecToShuffleWithZero(), refineIndexType(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), scalarizeExtractedBinOp(), shouldTransformMulToShiftsAddsSubs(), ShrinkLoadReplaceStoreWithStore(), simplifyMul24(), transformCallee(), tryWidenMaskForShuffle(), tryWidenMaskForShuffle(), vectorToScalarBitmask(), llvm::SDNodeInfo::verifyNode(), widenAbs(), widenBuildVec(), widenBuildVector(), widenCtPop(), widenShuffleMask(), and widenVectorToPartType().
getTokenFactor()
SDValue SelectionDAG::getTokenFactor (const SDLoc & DL, SmallVectorImpl< SDValue > & Vals)
Creates a new TokenFactor containing Vals.
If Vals contains 64k values or more, move values into new TokenFactors in 64k-1 blocks, until the final TokenFactor has less than 64k operands.
Definition at line 14211 of file SelectionDAG.cpp.
References llvm::ArrayRef(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), DL, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SDNode::getMaxNumOperands(), getNode(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ISD::TokenFactor.
Referenced by llvm::NVPTXTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), and llvm::NVPTXTargetLowering::LowerFormalArguments().
getTopologicallyOrderedNodes()
void SelectionDAG::getTopologicallyOrderedNodes (SmallVectorImpl< const SDNode * > & SortedNodes) const
Get all the nodes in their topological order without modifying any states.
Definition at line 12764 of file SelectionDAG.cpp.
References allnodes(), assert(), llvm::checkForCycles(), llvm::SmallVectorImpl< T >::clear(), llvm::ISD::EntryToken, llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::ISD::HANDLENODE, N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by dump().
getTruncStore() [1/3]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand * MMO)
Definition at line 10039 of file SelectionDAG.cpp.
References getStore(), getUNDEF(), llvm::SDValue::getValueType(), and llvm::ISD::UNINDEXED.
getTruncStore() [2/3]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 10019 of file SelectionDAG.cpp.
References assert(), getMachineFunction(), llvm::EVT::getStoreSize(), getTruncStore(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, and llvm::MachinePointerInfo::V.
Referenced by chainLoadsAndStoresForMemcpy(), combineStore(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getAddressForMemoryInput(), getMemcpyLoadsAndStores(), getTruncStore(), getTruncStore(), LowerINTRINSIC_W_CHAIN(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerStore(), PerformExtractFpToIntStores(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), performSTORECombine(), llvm::TargetLowering::scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
getTruncStore() [3/3]
SDValue llvm::SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1546 of file SelectionDAG.h.
References getEVTAlign(), getTruncStore(), and llvm::MachineMemOperand::MONone.
getTruncStoreVP() [1/2]
SDValue SelectionDAG::getTruncStoreVP (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand * MMO, bool IsCompressing = false)
Definition at line 10237 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), llvm::cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), getStoreVP(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), llvm::EVT::isInteger(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), and llvm::ISD::UNINDEXED.
getTruncStoreVP() [2/2]
SDValue SelectionDAG::getTruncStoreVP (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, bool IsCompressing = false)
Definition at line 10215 of file SelectionDAG.cpp.
References assert(), getMachineFunction(), llvm::EVT::getStoreSize(), getTruncStoreVP(), llvm::SDValue::getValueType(), InferPointerInfo(), llvm::PointerUnion< PTs >::isNull(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, and llvm::MachinePointerInfo::V.
Referenced by getTruncStoreVP().
getTruncStridedStoreVP()
SDValue SelectionDAG::getTruncStridedStoreVP (SDValue Chain, const SDLoc & DL, SDValue Val, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand * MMO, bool IsCompressing = false)
Definition at line 10405 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), llvm::cast(), DL, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), getStridedStoreVP(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), llvm::EVT::isInteger(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), and llvm::ISD::UNINDEXED.
getTypeSize()
SDValue SelectionDAG::getTypeSize (const SDLoc & DL, EVT VT, TypeSize TS)
Definition at line 2147 of file SelectionDAG.cpp.
References DL, and getFixedOrScalableQuantity().
Referenced by llvm::TargetLowering::expandVectorSplice(), getMemBasePlusOffset(), and llvm::TargetLowering::IncrementMemoryAddress().
getUNDEF()
SDValue llvm::SelectionDAG::getUNDEF (EVT VT) inline
Return an UNDEF node. UNDEF does not have a useful SDLoc.
Definition at line 1184 of file SelectionDAG.h.
References getNode(), and llvm::ISD::UNDEF.
Referenced by addShuffleForVecExtend(), buildMergeScalars(), buildScalarToVector(), llvm::TargetLowering::BuildUDIV(), canonicalizeShuffleMaskWithHorizOp(), collectConcatOps(), CollectOpsToWiden(), combineArithReduction(), combineBasicSADPattern(), combineBinOpToReduce(), combineBitcast(), combineBitcastToBoolVector(), combineBlendOfPermutes(), combineBVOfConsecutiveLoads(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfExtracts(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFP_EXTEND(), combineFP_TO_xINT_SAT(), combineI8TruncStore(), combineINSERT_SUBVECTOR(), combineLRINT_LLRINT(), combineMaskedLoadConstantMask(), combineSelect(), combineSetCCAtomicArith(), combineShuffleOfBitcast(), combineShuffleOfScalars(), combineShuffleOfSplatVal(), combineSVEReductionOrderedFP(), combineTargetShuffle(), combineToHorizontalAddSub(), combineTruncateWithSat(), combineTruncToVnclip(), combineVectorPack(), combineVPDPBUSDPattern(), combineVqdotAccum(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), combineXorSubCTLZ(), CompactSwizzlableVector(), concatSubVectors(), convertLocVTToValVT(), convertShiftLeftToScale(), convertToScalableVector(), convertToScalableVector(), createMMXBuildVector(), EltsFromConsecutiveLoads(), emitErrorAndReplaceIntrinsicResults(), emitFloatCompareMask(), emitIntrinsicWithChainErrorMessage(), EmitTruncSStore(), emitVectorComparison(), ExpandBVWithShuffles(), ExpandHorizontalBinOp(), expandV4F32ToV2F64(), ExtendToType(), extractSubVector(), fillSubVectorFromBuildVector(), FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), FoldConstantBuildVector(), foldConstantFPMath(), foldExtractSubvectorFromShuffleVector(), FoldSetCC(), getConstVector(), getConstVector(), getCopyFromPartsVector(), getDeinterleaveShiftAndTrunc(), getExtLoad(), getExtLoad(), getExtLoadVP(), getExtLoadVP(), getExtStridedLoadVP(), getGeneralPermuteNode(), getHopForBuildVector(), getInvertedVectorForFMA(), getKnownUndefForVectorBinop(), getLoad(), getLoad(), getLoadVP(), getLoadVP(), getNode(), getNode(), getNode(), getShuffleHalfVectors(), getShuffleScalarElt(), getShuffleVectorZeroOrUndef(), getSplatSourceVector(), getStore(), getStridedLoadVP(), getTargetVShiftNode(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), getVectorShuffle(), getVectorShuffle(), getWideningInterleave(), insert1BitVector(), isAddSubOrSubAdd(), isFNEG(), isHopBuildVector(), isHorizontalBinOpPart(), joinDwords(), lower1BitShuffle(), LowerAsSplatVectorLoad(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), LowerBITCAST(), LowerBITREVERSE_XOP(), lowerBitreverseShuffle(), lowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), lowerBuildVectorOfConstants(), LowerBuildVectorOfFPTrunc(), LowerBuildVectorv4x32(), lowerBuildVectorViaDominantValues(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), LowerCTLZ(), LowerCTTZ(), lowerDisjointIndicesShuffle(), LowerEXTEND_VECTOR_INREG(), lowerFixedVectorSegLoadIntrinsics(), lowerFixedVectorSegStoreIntrinsics(), LowerFLDEXP(), lowerFMAXIMUM_FMINIMUM(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), lowerFP_TO_INT_SAT(), lowerINT_TO_FP_vXi64(), LowerINTRINSIC_W_CHAIN(), llvm::MipsTargetLowering::lowerLOAD(), LowerMSCATTER(), LowerMUL(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateStore(), lowerReductionSeq(), LowerSCALAR_TO_VECTOR(), lowerScalarInsert(), lowerScalarSplat(), LowerShift(), LowerShiftByScalarImmediate(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificExtension(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithPSHUFB(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK256(), LowerSIGN_EXTEND_Mask(), LowerStore(), LowerTruncateVectorStore(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), lowerVECTOR_COMPRESS(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_IsReverse(), lowerVECTOR_SHUFFLE_VREPLVEI(), lowerVECTOR_SHUFFLE_XVPERM(), lowerVECTOR_SHUFFLE_XVREPLVEI(), lowerVECTOR_SHUFFLEAsLanePermuteAndShuffle(), lowerVECTOR_SHUFFLEAsVRGatherVX(), lowerVECTOR_SHUFFLEAsVSlide1(), lowerVECTOR_SHUFFLEAsVSlidedown(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorIntrinsicScalars(), lowerVectorPickVE2GR(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVZIP(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsInsertPS(), matchShuffleWithUNPCK(), matchSplatAsGather(), NormalizeBuildVector(), partitionShuffleOfConcats(), PerformARMBUILD_VECTORCombine(), performBuildShuffleExtendCombine(), performConcatVectorsCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDUPCombine(), performDupLane128Combine(), performLDNT1Combine(), performLOADCombine(), PerformMinMaxCombine(), performMulCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), performSHLCombine(), performSPLIT_PAIR_F64Combine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSTNT1Combine(), performSTORECombine(), PerformTruncatingStoreCombine(), performUnpackCombine(), performUzpCombine(), PerformVECTOR_REG_CASTCombine(), PerformVECTOR_SHUFFLECombine(), performVECTOR_SHUFFLECombine(), performVP_TRUNCATECombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReconstructShuffleWithRuntimeMask(), ReplaceAddWithADDP(), replaceAtomicSwap128(), ReplaceCMP_SWAP_64Results(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyDivRem(), simplifyFPBinop(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyShift(), splatPartsI64WithVL(), splitAndLowerShuffle(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), truncateVectorWithPACK(), tryBuildVectorShuffle(), tryCombineMULLWithUZP1(), tryToFoldExtendOfConstant(), tryToReplaceScalarFPConversionWithSVE(), UnrollVectorOp(), UnrollVectorOverflowOp(), vectorizeExtractedCast(), widenBuildVector(), widenSubVector(), widenVec(), WidenVector(), WidenVector(), and widenVectorToPartType().
getUniformityInfo()
const UniformityInfo * llvm::SelectionDAG::getUniformityInfo () const inline
Definition at line 507 of file SelectionDAG.h.
Referenced by llvm::FunctionLoweringInfo::set().
getVAArg()
SDValue SelectionDAG::getVAArg (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
Definition at line 10945 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getNode(), getTargetConstant(), getVTList(), and llvm::ISD::VAARG.
getValidMaximumShiftAmount() [1/2]
std::optional< unsigned > SelectionDAG::getValidMaximumShiftAmount (SDValue V, const APInt & DemandedElts, unsigned Depth = 0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the maximum possible value.
Definition at line 3266 of file SelectionDAG.cpp.
References assert(), llvm::Depth, getValidShiftAmountRange(), llvm::ISD::SHL, llvm::ISD::SRA, and llvm::ISD::SRL.
Referenced by canCreateUndefOrPoison(), getValidMaximumShiftAmount(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyMultipleUseDemandedBits().
getValidMaximumShiftAmount() [2/2]
std::optional< unsigned > SelectionDAG::getValidMaximumShiftAmount (SDValue V, unsigned Depth = 0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the maximum possible value.
Definition at line 3278 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnes(), getValidMaximumShiftAmount(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isFixedLengthVector().
getValidMinimumShiftAmount() [1/2]
std::optional< unsigned > SelectionDAG::getValidMinimumShiftAmount (SDValue V, const APInt & DemandedElts, unsigned Depth = 0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the minimum possible value.
Definition at line 3245 of file SelectionDAG.cpp.
References assert(), llvm::Depth, getValidShiftAmountRange(), llvm::ISD::SHL, llvm::ISD::SRA, and llvm::ISD::SRL.
Referenced by combineGatherScatter(), computeKnownBits(), ComputeNumSignBits(), and getValidMinimumShiftAmount().
getValidMinimumShiftAmount() [2/2]
std::optional< unsigned > SelectionDAG::getValidMinimumShiftAmount (SDValue V, unsigned Depth = 0) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the minimum possible value.
Definition at line 3257 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnes(), getValidMinimumShiftAmount(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isFixedLengthVector().
getValidShiftAmount() [1/2]
std::optional< unsigned > SelectionDAG::getValidShiftAmount (SDValue V, const APInt & DemandedElts, unsigned Depth = 0) const
If a SHL/SRA/SRL node V has a uniform shift amount that is less than the element bit-width of the shift node, return it.
Definition at line 3223 of file SelectionDAG.cpp.
References assert(), llvm::Depth, getValidShiftAmountRange(), llvm::ISD::SHL, llvm::ISD::SRA, and llvm::ISD::SRL.
Referenced by checkSignTestSetCCCombine(), combinei64TruncSrlConstant(), getValidShiftAmount(), matchTruncateWithPACK(), and llvm::TargetLowering::SimplifyDemandedBits().
getValidShiftAmount() [2/2]
std::optional< unsigned > SelectionDAG::getValidShiftAmount (SDValue V, unsigned Depth = 0) const
If a SHL/SRA/SRL node V has a uniform shift amount that is less than the element bit-width of the shift node, return it.
Definition at line 3236 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnes(), getValidShiftAmount(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isFixedLengthVector().
getValidShiftAmountRange()
std::optional< ConstantRange > SelectionDAG::getValidShiftAmountRange (SDValue V, const APInt & DemandedElts, unsigned Depth) const
If a SHL/SRA/SRL node V has shift amounts that are all less than the element bit-width of the shift node, return the valid constant range.
Definition at line 3174 of file SelectionDAG.cpp.
References assert(), llvm::BitWidth, computeKnownBits(), llvm::Depth, llvm::dyn_cast(), llvm::ConstantRange::fromKnownBits(), llvm::KnownBits::getMaxValue(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::APInt::uge(), llvm::APInt::ugt(), and llvm::APInt::ult().
Referenced by ComputeNumSignBits(), getValidMaximumShiftAmount(), getValidMinimumShiftAmount(), and getValidShiftAmount().
getValueType()
SDValue SelectionDAG::getValueType (EVT VT)
Definition at line 2047 of file SelectionDAG.cpp.
References llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::EVT::isSimple(), N, and llvm::MVT::SimpleTy.
Referenced by addShuffleForVecExtend(), combineShiftRightArithmetic(), convertLocVTToValVT(), customLegalizeToWOpWithSExt(), customLegalizeToWOpWithSExt(), emitRepmovs(), emitRepstos(), FoldConstantArithmetic(), getAArch64Cmp(), getCopyFromParts(), llvm::RegsForValue::getCopyFromRegs(), getNode(), getNode(), LowerBUILD_VECTOR_i1(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::SITargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP_TO_INT_SAT(), LowerINSERT_VECTOR_ELT_i1(), lowerMSACopyIntr(), llvm::MSP430TargetLowering::LowerShifts(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), lowerVectorPickVE2GR(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performGatherLoadCombine(), performLD1Combine(), PerformMinMaxCombine(), PerformMinMaxFpToSatCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), performScatterStoreCombine(), performSETCCCombine(), performSignExtendCombine(), performSignExtendInRegCombine(), performSRACombine(), performST1Combine(), PerformUMinFpToSatCombine(), PromoteMaskArithmetic(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceVPICKVE2GRResults(), scalarizeExtractedBinOp(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::softenSetCCOperands(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateScalarIntegerArg(), truncateVectorWithPACKSS(), UnpackFromArgumentSlot(), UnrollVectorOp(), and unrollVectorShift().
getVectorIdxConstant()
SDValue SelectionDAG::getVectorIdxConstant (uint64_t Val, const SDLoc & DL, bool isTarget = false)
Definition at line 1818 of file SelectionDAG.cpp.
References DL, getConstant(), and getDataLayout().
Referenced by buildFromShuffleMostly(), combineArithReduction(), combineAVX512SetCCToKMOV(), combineBitcast(), combineBitcastToBoolVector(), combineCompareEqual(), combineConcatVectorOps(), combineEXTRACT_SUBVECTOR(), combineExtractFromVectorLoad(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), combineI8TruncStore(), combineINSERT_SUBVECTOR(), combineKSHIFT(), combineMinMaxReduction(), combineSelect(), combineStoreValueFPToInt(), combineTargetShuffle(), combineTruncateWithSat(), combineVectorSizedSetCCEquality(), convertIntLogicToFPLogic(), CustomNonLegalBITCASTResults(), detectPMADDUBSW(), EltsFromConsecutiveLoads(), ExtendToType(), ExtractBitFromMaskVector(), foldExtractSubvectorFromShuffleVector(), GeneratePerfectShuffle(), getCopyFromPartsVector(), getCopyToPartsVector(), getDataClassTest(), getExtractSubvector(), getExtractVectorElt(), getExtractVectorizedValue(), getInsertSubvector(), getInsertVectorElt(), getMaskNode(), getScalarMaskingNode(), getShuffleHalfVectors(), insert1BitVector(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), lowerAddSubToHorizontalOp(), LowerAVXCONCAT_VECTORS(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerCONCAT_VECTORSvXi1(), LowerEXTRACT_SUBVECTOR(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFMINIMUM_FMAXIMUM(), LowerFP16_TO_FP(), LowerFP_TO_FP16(), lowerFPToIntToFP(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), lowerLaneOp(), LowerLoad(), LowerMGATHER(), LowerMLOAD(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUndefHalf(), LowerSIGN_EXTEND_Mask(), LowerStore(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), LowerVECTOR_SHUFFLEUsingOneOff(), LowerZERO_EXTEND_Mask(), matchPMADDWD_2(), narrowExtractedVectorBinOp(), performBuildVectorCombine(), PerformInsertSubvectorCombine(), performInsertSubvectorCombine(), performLOADCombine(), performSTORECombine(), performSunpkloCombine(), performTruncateCombine(), PerformVQDMULHCombine(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), scalarizeVectorStore(), SplitAndExtendv16i1(), SplitVector(), llvm::AMDGPUTargetLowering::splitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryToReplaceScalarFPConversionWithSVE(), vectorizeExtractedCast(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), and widenVectorToPartType().
getVectorShuffle()
SDValue SelectionDAG::getVectorShuffle (EVT VT, const SDLoc & dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
The number of elements in VT, which must be a vector type, must match the number of mask elements NumElts. An integer mask element equal to -1 is treated as undefined.
Definition at line 2186 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::all_of(), assert(), llvm::ISD::BITCAST, commuteShuffle(), llvm::copy(), llvm::dyn_cast(), llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getNode(), llvm::SDNode::getOperand(), getSplatBuildVector(), llvm::BuildVectorSDNode::getSplatValue(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::isNullConstant(), llvm::SDValue::isUndef(), N, NewSDValueDbgMsg(), llvm::BitVector::none(), llvm::Offset, llvm::Splat, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by addShuffleForVecExtend(), buildFromShuffleMostly(), llvm::TargetLowering::buildLegalVectorShuffle(), BuildVSLDOI(), combineAddOfPMADDWD(), combineAndShuffleNot(), combineArithReduction(), combineBasicSADPattern(), combineBITREVERSE(), combineBlendOfPermutes(), combineBVOfConsecutiveLoads(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineFP_ROUND(), combineHorizOpWithShuffle(), combineINSERT_SUBVECTOR(), combineMinMaxReduction(), combinePMULDQ(), combineSelect(), combineShuffleOfBitcast(), combineShuffleOfSplatVal(), combineSIntToFP(), combineToExtendBoolVectorInReg(), combineToHorizontalAddSub(), combineVPDPBUSDPattern(), createVariablePermute(), EltsFromConsecutiveLoads(), ExpandBVWithShuffles(), expandV4F32ToV2F64(), foldExtractSubvectorFromShuffleVector(), foldShuffleOfConcatUndefs(), formSplatFromShuffles(), GeneratePerfectShuffle(), getCommutedVectorShuffle(), getPack(), getScalarMaskingNode(), getShuffleHalfVectors(), getShuffleVectorZeroOrUndef(), getSToVPermuted(), getTargetVShiftNode(), getVectorShuffle(), isFNEG(), lower128BitShuffle(), lower1BitShuffle(), lower256BitShuffle(), lower512BitShuffle(), LowerAsSplatVectorLoad(), lowerBuildVectorAsBlend(), LowerBuildVectorv4x32(), LowerConvertLow(), lowerDisjointIndicesShuffle(), LowerEXTEND_VECTOR_INREG(), LowerMUL(), LowerMULH(), LowerReverse_VECTOR_SHUFFLE(), LowerRotate(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificExtension(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUNPCK256(), LowerSIGN_EXTEND(), lowerToAddSubOrFMAddSub(), LowerTruncateVecI1(), LowerUINT_TO_FP_i64(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV8F16Shuffle(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_IsReverse(), lowerVECTOR_SHUFFLEAsLanePermuteAndShuffle(), lowerVECTOR_SHUFFLEAsVRGatherVX(), LowerVECTOR_SHUFFLEUsingMovs(), lowerVSELECTtoVectorShuffle(), LowerVSETCC(), partitionShuffleOfConcats(), performBuildShuffleExtendCombine(), performConcatVectorsCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtBinopLoadFold(), performMulCombine(), performSelectCombine(), PerformTruncatingStoreCombine(), PerformVECTOR_SHUFFLECombine(), performVECTOR_SHUFFLECombine(), performVECTOR_SHUFFLECombine(), PerformVQDMULHCombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceVMULWidth(), ReplaceAddWithADDP(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), splitAndLowerShuffle(), truncateVectorWithPACK(), tryWidenMaskForShuffle(), tryWidenMaskForShuffle(), vectorizeExtractedCast(), and widenShuffleMask().
getVPLogicalNOT()
SDValue SelectionDAG::getVPLogicalNOT (const SDLoc & DL, SDValue Val, SDValue Mask, SDValue EVL, EVT VT)
Create a vector-predicated logical NOT operation as (VP_XOR Val, BooleanOne, Mask, EVL).
Definition at line 1625 of file SelectionDAG.cpp.
References DL, getBoolConstant(), and getNode().
getVPPtrExtOrTrunc()
SDValue SelectionDAG::getVPPtrExtOrTrunc (const SDLoc & DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be of integer type, to the vector-type integer type VT, by either truncating it or performing either vector-predicated zero or sign extension as appropriate extension for the pointer's semantics.
This function just redirects to getVPZExtOrTrunc right now.
Definition at line 1631 of file SelectionDAG.cpp.
References DL, and getVPZExtOrTrunc().
getVPZeroExtendInReg()
SDValue SelectionDAG::getVPZeroExtendInReg (SDValue Op, SDValue Mask, SDValue EVL, const SDLoc & DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
Definition at line 1580 of file SelectionDAG.cpp.
References assert(), llvm::EVT::bitsLE(), DL, getConstant(), llvm::APInt::getLowBitsSet(), getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorElementCount(), llvm::EVT::isInteger(), and llvm::EVT::isVector().
getVPZExtOrTrunc()
SDValue SelectionDAG::getVPZExtOrTrunc (const SDLoc & DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be an integer vector, to the vector-type VT, by performing either vector-predicated zext or truncating it.
The Op will be returned as-is if Op and VT are vectors containing integer with same width.
Definition at line 1636 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), DL, and getNode().
Referenced by getVPPtrExtOrTrunc().
getVRegDbgValue()
SDDbgValue * SelectionDAG::getVRegDbgValue (DIVariable * Var, DIExpression * Expr, Register VReg, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a VReg SDDbgValue node.
VReg.
Definition at line 12002 of file SelectionDAG.cpp.
References assert(), llvm::cast(), DL, and llvm::SDDbgOperand::fromVReg().
getVScale()
SDValue SelectionDAG::getVScale (const SDLoc & DL, EVT VT, APInt MulImm)
Return a node that represents the runtime scaling 'MulImm * RuntimeVL'.
Definition at line 2112 of file SelectionDAG.cpp.
References assert(), llvm::CallingConv::C, DL, F, llvm::APInt::getBitWidth(), getConstant(), getMachineFunction(), getNode(), llvm::ConstantRange::getSingleElement(), llvm::EVT::getSizeInBits(), llvm::getVScaleRange(), and llvm::ISD::VSCALE.
Referenced by clampDynamicVectorIndex(), GenerateFixedLengthSVETBL(), getFixedOrScalableQuantity(), getNode(), getNode(), and llvm::TargetLowering::getVectorSubVecPointer().
getVTList() [1/5]
SDVTList SelectionDAG::getVTList (ArrayRef< EVT > VTs)
Definition at line 11387 of file SelectionDAG.cpp.
References llvm::copy(), and llvm::ArrayRef< T >::size().
getVTList() [2/5]
SDVTList SelectionDAG::getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
Definition at line 11320 of file SelectionDAG.cpp.
References llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), and makeVTList().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canEmitConjunction(), llvm::AArch64TargetLowering::changeStreamingMode(), CloneNodeWithValues(), combineADC(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineADDX(), combineBitcast(), combineBitcastToBoolVector(), combineBVZEXTLOAD(), combineCMov(), combineCMP(), combineConcatVectorOps(), combineMaskedStore(), combineSBB(), combineSetCC(), combineStore(), combineSubSetcc(), combineSUBX(), combineSVEPrefetchVecBaseImmOff(), combineTargetShuffle(), CombineVLDDUP(), combineX86AddSub(), combineXorSubCTLZ(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), ConvertCarryFlagToCarryValue(), ConvertCarryValueToCarryFlag(), convertFPToInt(), convertIntToFP(), createLoadLR(), createMemMemNode(), createSetFPEnvNodes(), createStoreLR(), EltsFromConsecutiveLoads(), EmitCmp(), emitCmp(), emitComparison(), emitIntrinsicWithCCAndChain(), EmitMaskedTruncSStore(), emitRepmovs(), emitRepstos(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::RISCVSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), EmitTest(), EmitTruncSStore(), EmitUnrolledSetTag(), Expand64BitShift(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), llvm::TargetLowering::expandIntMINMAX(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), ExpandREAD_REGISTER(), llvm::TargetLowering::expandREM(), expandV4F32ToV2F64(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), FixupMMXIntrinsicTypes(), foldAndOrOfSETCC(), GeneratePerfectShuffle(), getAArch64XALUOOp(), llvm::MipsTargetLowering::getAddrGPRel(), getAddrSpaceCast(), getAssertAlign(), getAtomic(), getAtomicLoad(), getAVX2GatherNode(), getBasicBlock(), getBlockAddress(), getBoundedStrlen(), getBROADCAST_LOAD(), getCALLSEQ_END(), getCALLSEQ_START(), getConstant(), getConstantFP(), getConstantPool(), getConstantPool(), getCopyFromParts(), getCopyFromReg(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToReg(), getCopyToReg(), getDeactivationSymbol(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getExternalSymbol(), getFlagsOfCmpZeroFori1(), getFPBinOp(), getFPTernOp(), getFrameIndex(), getGatherNode(), getGetFPEnv(), getGlobalAddress(), getIndexedStoreVP(), getInvertedVectorForFMA(), getJumpTable(), getLabelNode(), getLifetimeNode(), getLoad(), getLoadFFVP(), getLoadVP(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMachineNode(), getMad64_32(), getMaskedLoad(), getMaskedStore(), getMCSymbol(), getMDNode(), getMergeValues(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getNode(), getPopFromX87Reg(), getPseudoProbeNode(), getRegister(), getRegisterMask(), getScatterNode(), getSetFPEnv(), getSrcValue(), getStore(), getStoreVP(), getStridedLoadVP(), getStridedStoreVP(), getTargetExternalSymbol(), GetTLSADDR(), getTruncStoreVP(), getTruncStridedStoreVP(), getVAArg(), getVCIXISDNodeWCHAIN(), getVectorShuffle(), getX86XALUOOp(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), legalizeSVEGatherPrefetchOffsVec(), LowerABD(), LowerABS(), LowerADDSAT_SUBSAT(), LowerADDSUBO_CARRY(), lowerADDSUBO_CARRY(), LowerATOMIC_STORE(), llvm::VETargetLowering::lowerATOMIC_SWAP(), lowerAtomicArithWithLOCK(), lowerBUILD_VECTORAsBroadCastLoad(), LowerBUILD_VECTORToVIDUP(), lowerBuildVectorAsBroadcast(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerCMP_SWAP(), LowerCTLZ(), LowerCTTZ(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerEH_SJLJ_SETJMP(), lowerFixedVectorSegLoadIntrinsics(), lowerFixedVectorSegStoreIntrinsics(), llvm::SITargetLowering::lowerGET_FPENV(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMSCATTER(), lowerMSTORE(), LowerMULO(), llvm::RISCVTargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), lowerOverflowArithmetic(), LowerPARITY(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), llvm::HexagonTargetLowering::LowerREADSTEADYCOUNTER(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerSELECTWithCmpZero(), LowerSETCCCARRY(), lowerShuffleAsBroadcast(), LowerSTORE(), LowerStore(), lowerSTOREVector(), lowerTcgen05Ld(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), LowerUADDSUBO_CARRY(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerUINT_TO_FP_vXi32(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVectorExtend(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), mutateStrictFPToFP(), narrowLoadToVZLoad(), PerformADDVecReduce(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCONDCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDUPCombine(), PerformExtractFpToIntStores(), performFlagSettingCombine(), performGatherLoadCombine(), PerformHWLoopCombine(), performLD1Combine(), performMaskedGatherScatterCombine(), PerformMVEVLDCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), performRNDRCombine(), performScatterStoreCombine(), PerformSETCCCombine(), performSignExtendInRegCombine(), PerformUMLALCombine(), PerformVDUPCombine(), PerformVECREDUCE_ADDCombine(), PerformVMOVhrCombine(), reassociateCSELOperandsForCSE(), ReplaceATOMIC_LOAD_128Results(), replaceAtomicSwap128(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceCMP_XCHG_128Results(), ReplaceINTRINSIC_W_CHAIN(), replaceLoadVector(), ReplaceLongIntrinsic(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), SelectionDAG(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), SplitStrictFPVectorOp(), TryCombineBaseUpdate(), tryMemPairCombine(), tryToWidenSetCCOperands(), UnrollVectorOverflowOp(), valueToCarryFlag(), llvm::X86TargetLowering::visitMaskedLoad(), llvm::X86TargetLowering::visitMaskedStore(), and widenVectorOpsToi8().
getVTList() [3/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2)
Definition at line 11327 of file SelectionDAG.cpp.
References llvm::EVT::getRawBits().
getVTList() [4/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3)
Definition at line 11345 of file SelectionDAG.cpp.
References llvm::EVT::getRawBits().
getVTList() [5/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
Definition at line 11365 of file SelectionDAG.cpp.
References llvm::EVT::getRawBits().
getZeroExtendInReg()
SDValue SelectionDAG::getZeroExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
Definition at line 1562 of file SelectionDAG.cpp.
References llvm::ISD::AND, assert(), llvm::EVT::bitsLE(), DL, getConstant(), llvm::APInt::getLowBitsSet(), getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorElementCount(), llvm::EVT::isInteger(), and llvm::EVT::isVector().
Referenced by combineExtSetcc(), combinei64TruncSrlConstant(), combineStore(), getPtrExtendInReg(), LowerADDRSPACECAST(), lowerFP_TO_INT_SAT(), llvm::MSP430TargetLowering::LowerShifts(), LowerStore(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performFP_TO_INT_SATCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), PromoteMaskArithmetic(), scalarizeExtractedBinOp(), llvm::TargetLowering::SimplifyDemandedBits(), truncateVectorWithPACKUS(), and tryFoldMADwithSRL().
getZExtOrTrunc()
SDValue SelectionDAG::getZExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
Definition at line 1502 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, getNode(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineAnd(), combineAndLoadToBZHI(), combineBitcast(), combineBitcastvxi1(), combineBoolVectorAndTruncateStore(), combineCompareEqual(), combineExtractVectorElt(), combineExtractWithShuffle(), combineOr(), combinePredicateReduction(), combineSCALAR_TO_VECTOR(), combineScalarAndWithMaskSetcc(), combineSelect(), combineSetCC(), combineSetCCMOVMSK(), combineShiftAnd1ToBitTest(), combineShuffleOfScalars(), combineToVCPOP(), combineTruncate(), combineXor(), ConvertCarryFlagToCarryValue(), ConvertCarryValueToCarryFlag(), createPSADBW(), createVariablePermute(), createVPDPBUSD(), earlyExpandDIVFIX(), emitMemMemReg(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), Expand64BitShift(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandVectorFindLastActive(), llvm::TargetLowering::expandVPCTTZElements(), foldAddSubBoolOfMaskedVal(), foldCONCAT_VECTORS(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldSelectOfCTTZOrCTLZ(), getBitcastedZExtOrTrunc(), getExtOrTrunc(), getExtOrTrunc(), getFlagsOfCmpZeroFori1(), getPTest(), getPtrExtOrTrunc(), getShiftAmountOperand(), getTargetVShiftNode(), llvm::TargetLowering::getVectorSubVecPointer(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::TargetLowering::LegalizeSetCCCondCode(), lowerBALLOTIntrinsic(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), LowerCTPOP(), llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::AMDGPUTargetLowering::LowerF64ToF16Safe(), lowerFCMPIntrinsic(), LowerFGETSIGN(), LowerFunnelShift(), lowerICMPIntrinsic(), LowerINTRINSIC_W_CHAIN(), llvm::HexagonTargetLowering::LowerLoad(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerShift(), llvm::HexagonTargetLowering::LowerVECTOR_SHIFT(), lowerX86CmpEqZeroToCtlzSrl(), narrowBitOpRMW(), performAnyAllCombine(), performBITCASTCombine(), performBitcastCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performMulLoHiCombine(), performRNDRCombine(), performSETCC_BITCASTCombine(), performSETCCCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformUMinFpToSatCombine(), PerformVSetCCToVCTPCombine(), replaceBoolVectorBitcast(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), takeInexpensiveLog2(), TryMatchTrue(), visitORCommutative(), widenAbs(), and widenCtPop().
hasDebugValues()
bool llvm::SelectionDAG::hasDebugValues () const inline
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
Definition at line 2017 of file SelectionDAG.h.
haveNoCommonBitsSet()
bool SelectionDAG::haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
As an example, this can allow an 'add' to be transformed into an 'or'.
Definition at line 6297 of file SelectionDAG.cpp.
References A(), assert(), B(), computeKnownBits(), llvm::KnownBits::haveNoCommonBitsSet(), and haveNoCommonBitsSetCommutative().
Referenced by getPointerConstIncrement(), and isADDLike().
InferPtrAlign()
MaybeAlign SelectionDAG::InferPtrAlign (SDValue Ptr) const
Infer alignment of a load / store address.
InferPtrAlignment - Infer alignment of a load / store address.
Return std::nullopt if it cannot be inferred.
Definition at line 13594 of file SelectionDAG.cpp.
References llvm::cast(), llvm::commonAlignment(), llvm::computeKnownBits(), llvm::KnownBits::countMinTrailingZeros(), llvm::dyn_cast(), llvm::SDValue::getConstantOperandVal(), getDataLayout(), llvm::MachineFunction::getFrameInfo(), getMachineFunction(), llvm::SDValue::getNode(), llvm::MachineFrameInfo::getObjectAlign(), llvm::SDValue::getOperand(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::GlobalValue::getType(), llvm::isa(), and isBaseWithConstantOffset().
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and LowerAsSplatVectorLoad().
init() [1/2]
void llvm::SelectionDAG::init (MachineFunction & NewMF, OptimizationRemarkEmitter & NewORE, MachineFunctionAnalysisManager & AM, const TargetLibraryInfo * LibraryInfo, UniformityInfo * UA, ProfileSummaryInfo * PSIin, BlockFrequencyInfo * BFIin, MachineModuleInfo & MMI, FunctionVarLocs const * FnVarLocs) inline
Definition at line 476 of file SelectionDAG.h.
References init().
init() [2/2]
void SelectionDAG::init (MachineFunction & NewMF, OptimizationRemarkEmitter & NewORE, Pass * PassPtr, const TargetLibraryInfo * LibraryInfo, UniformityInfo * UA, ProfileSummaryInfo * PSIin, BlockFrequencyInfo * BFIin, MachineModuleInfo & MMI, FunctionVarLocs const * FnVarLocs)
Prepare this SelectionDAG to process code in the given MachineFunction.
Definition at line 1368 of file SelectionDAG.cpp.
References llvm::TargetSubtargetInfo::getSelectionDAGInfo(), getSubtarget(), and llvm::TargetSubtargetInfo::getTargetLowering().
Referenced by init().
isADDLike()
bool SelectionDAG::isADDLike (SDValue Op, bool NoWrap = false) const
Return true if the specified operand is an ISD::OR or ISD::XOR node that can be treated as an ISD::ADD node.
or(x,y) == add(x,y) iff haveNoCommonBitsSet(x,y) xor(x,y) == add(x,y) iff isMinSignedConstant(y) && !NoWrap If NoWrap is true, this will not match ISD::XOR.
Definition at line 5788 of file SelectionDAG.cpp.
References haveNoCommonBitsSet(), llvm::isMinSignedConstant(), llvm::ISD::OR, and llvm::ISD::XOR.
Referenced by isBaseWithConstantOffset().
isBaseWithConstantOffset()
bool SelectionDAG::isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
This handles the equivalence: X|Cst == X+Cst iff X&Cst = 0.
Definition at line 5798 of file SelectionDAG.cpp.
References llvm::isa(), and isADDLike().
Referenced by getBaseWithConstantOffset(), getBaseWithOffsetUsingSplitOR(), InferPtrAlign(), llvm::SITargetLowering::isReassocProfitable(), LowerAsSplatVectorLoad(), and replaceZeroVectorStore().
isBoolConstant()
std::optional< bool > SelectionDAG::isBoolConstant (SDValue N) const
Check if a value \op N is a constant using the target's BooleanContent for its type.
Definition at line 14155 of file SelectionDAG.cpp.
References llvm::EVT::getScalarSizeInBits(), llvm::APInt::isAllOnes(), llvm::isConstOrConstSplat(), llvm::APInt::isOne(), llvm::APInt::isZero(), llvm_unreachable, N, llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
Referenced by extractBooleanFlip(), and simplifySelect().
isConstantFPBuildVectorOrConstantFP()
bool SelectionDAG::isConstantFPBuildVectorOrConstantFP (SDValue N) const
Test whether the given value is a constant FP or similar node.
Definition at line 14141 of file SelectionDAG.cpp.
References llvm::isa(), llvm::ISD::isBuildVectorOfConstantFPSDNodes(), N, and llvm::ISD::SPLAT_VECTOR.
Referenced by canonicalizeCommutativeBinop(), and isConstantValueOfAnyType().
isConstantIntBuildVectorOrConstantInt()
bool SelectionDAG::isConstantIntBuildVectorOrConstantInt (SDValue N, bool AllowOpaques = true) const
Test whether the given value is a constant int or similar node.
Definition at line 14117 of file SelectionDAG.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::ISD::GlobalAddress, llvm::isa(), llvm::ISD::isBuildVectorOfConstantSDNodes(), N, llvm::peekThroughBitcasts(), and llvm::ISD::SPLAT_VECTOR.
Referenced by canonicalizeCommutativeBinop(), combineAndNotOrIntoAndNotAnd(), combinePMULDQ(), combinePTESTCC(), combineSetCC(), combineSub(), foldAddSubOfSignBit(), isConstantValueOfAnyType(), performSubAddMULCombine(), llvm::TargetLowering::SimplifySetCC(), and stripConstantMask().
isConstantValueOfAnyType()
bool llvm::SelectionDAG::isConstantValueOfAnyType (SDValue N) const inline
Returns
true if N is any kind of constant or build_vector of constants, int or float. If a vector, it may not necessarily be a splat.
Definition at line 2531 of file SelectionDAG.h.
References isConstantFPBuildVectorOrConstantFP(), isConstantIntBuildVectorOrConstantInt(), and N.
Referenced by llvm::AMDGPUTargetLowering::performSelectCombine(), and simplifySelect().
isEqualTo()
bool SelectionDAG::isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
This is true if they are the same value, or if one is negative zero and the other positive zero.
Definition at line 6231 of file SelectionDAG.cpp.
References A(), B(), and llvm::dyn_cast().
Referenced by combineSelect().
isGuaranteedNotToBePoison() [1/2]
bool llvm::SelectionDAG::isGuaranteedNotToBePoison (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const inline
Return true if this function can prove that Op is never poison.
The DemandedElts argument limits the check to the requested vector elements.
Definition at line 2269 of file SelectionDAG.h.
References llvm::Depth, and isGuaranteedNotToBeUndefOrPoison().
isGuaranteedNotToBePoison() [2/2]
bool llvm::SelectionDAG::isGuaranteedNotToBePoison (SDValue Op, unsigned Depth = 0) const inline
Return true if this function can prove that Op is never poison.
Definition at line 2263 of file SelectionDAG.h.
References llvm::Depth, and isGuaranteedNotToBeUndefOrPoison().
Referenced by getNode(), and simplifySelect().
isGuaranteedNotToBeUndefOrPoison() [1/2]
bool SelectionDAG::isGuaranteedNotToBeUndefOrPoison (SDValue Op, bool PoisonOnly = false, unsigned Depth = 0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
Definition at line 5378 of file SelectionDAG.cpp.
References llvm::Depth, llvm::ISD::FREEZE, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), llvm::EVT::isFixedLengthVector(), isGuaranteedNotToBeUndefOrPoison(), and PoisonOnly.
Referenced by computeKnownBits(), ComputeNumSignBits(), getFreeze(), getNode(), isGuaranteedNotToBePoison(), isGuaranteedNotToBePoison(), isGuaranteedNotToBeUndefOrPoison(), isGuaranteedNotToBeUndefOrPoison(), llvm::X86TargetLowering::isGuaranteedNotToBeUndefOrPoisonForTargetNode(), and llvm::TargetLowering::SimplifyDemandedVectorElts().
isGuaranteedNotToBeUndefOrPoison() [2/2]
bool SelectionDAG::isGuaranteedNotToBeUndefOrPoison (SDValue Op, const APInt & DemandedElts, bool PoisonOnly = false, unsigned Depth = 0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
The DemandedElts argument limits the check to the requested vector elements.
Definition at line 5391 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::all_of(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, canCreateUndefOrPoison(), llvm::cast(), llvm::APInt::clearBit(), llvm::APInt::clearBits(), llvm::ISD::CONDCODE, llvm::ISD::CopyFromReg, llvm::ISD::CTPOP, llvm::Depth, llvm::dyn_cast(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FrameIndex, llvm::ISD::FREEZE, llvm::APInt::getBitWidth(), llvm::APInt::getOneBitSet(), llvm::getShuffleDemandedElts(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isFixedLengthVector(), isGuaranteedNotToBeUndefOrPoison(), llvm::isIntOrFPConstant(), llvm::APInt::isZero(), MaxRecursionDepth, llvm::ISD::MUL, llvm::ISD::OR, llvm::peekThroughInsertVectorElt(), llvm::ISD::POISON, PoisonOnly, llvm::ISD::SADDSAT, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SSHLSAT, llvm::ISD::SSUBSAT, llvm::ISD::SUB, llvm::Sub, llvm::ISD::TargetFrameIndex, llvm::ISD::TRUNCATE, llvm::ISD::UADDSAT, llvm::APInt::ugt(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UNDEF, llvm::ISD::USHLSAT, llvm::ISD::USUBSAT, llvm::ISD::VALUETYPE, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::APInt::zext().
isKnownNeverNaN() [1/2]
bool SelectionDAG::isKnownNeverNaN (SDValue Op, bool SNaN = false, unsigned Depth = 0) const
Test whether the given SDValue (or all elements of it, if it is a vector) is known to never be NaN.
If SNaN is true, returns if Op is known to never be a signaling NaN (it may still be a qNaN).
Definition at line 5803 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), llvm::EVT::isFixedLengthVector(), and isKnownNeverNaN().
isKnownNeverNaN() [2/2]
bool SelectionDAG::isKnownNeverNaN (SDValue Op, const APInt & DemandedElts, bool SNaN = false, unsigned Depth = 0) const
Test whether the given SDValue (or all elements of it, if it is a vector) is known to never be NaN in DemandedElts.
If SNaN is true, returns if Op is known to never be a signaling NaN (it may still be a qNaN).
Definition at line 5817 of file SelectionDAG.cpp.
References assert(), llvm::ISD::AssertNoFPClass, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::CallingConv::C, llvm::Depth, llvm::dyn_cast(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FABS, llvm::ISD::FACOS, llvm::ISD::FADD, llvm::ISD::FASIN, llvm::ISD::FATAN, llvm::ISD::FATAN2, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::fcNan, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FCOSH, llvm::fcSNan, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP10, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLDEXP, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXIMUMNUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINIMUMNUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FMULADD, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FROUNDEVEN, llvm::ISD::FSIN, llvm::ISD::FSINH, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTAN, llvm::ISD::FTANH, llvm::ISD::FTRUNC, llvm::APInt::getBitsSet(), llvm::APInt::getOneBitSet(), getTarget(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), I, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isFixedLengthVector(), isKnownNeverNaN(), isKnownNeverSNaN(), llvm::APInt::isZero(), llvm::ISD::LLRINT, llvm::ISD::LLROUND, llvm::ISD::LRINT, llvm::ISD::LROUND, MaxRecursionDepth, Options, llvm::ISD::SELECT, llvm::APInt::shl(), llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, and llvm::APInt::zext().
Referenced by arebothOperandsNotNan(), combineFMinNumFMaxNum(), combineSelect(), emitFloatCompareMask(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFMINNUM_FMAXNUM(), isKnownNeverNaN(), isKnownNeverNaN(), llvm::AMDGPUTargetLowering::isKnownNeverNaNForTargetNode(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverSNaN(), isKnownNeverSNaN(), isLegalToCombineMinNumMaxNum(), lowerFMAXIMUM_FMINIMUM(), and LowerFMINIMUM_FMAXIMUM().
isKnownNeverSNaN() [1/2]
bool llvm::SelectionDAG::isKnownNeverSNaN (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const inline
Returns
true if Op is known to never be a signaling NaN in DemandedElts.
Definition at line 2330 of file SelectionDAG.h.
References llvm::Depth, and isKnownNeverNaN().
Referenced by arebothOperandsNotSNan(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFMINNUM_FMAXNUM(), llvm::SITargetLowering::isCanonicalized(), and isKnownNeverNaN().
isKnownNeverSNaN() [2/2]
bool llvm::SelectionDAG::isKnownNeverSNaN (SDValue Op, unsigned Depth = 0) const inline
Returns
true if Op is known to never be a signaling NaN.
Definition at line 2336 of file SelectionDAG.h.
References llvm::Depth, and isKnownNeverNaN().
isKnownNeverZero()
bool SelectionDAG::isKnownNeverZero (SDValue Op, unsigned Depth = 0) const
Test whether the given SDValue is known to contain non-zero value(s).
Definition at line 6020 of file SelectionDAG.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, assert(), llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, llvm::CallingConv::C, computeKnownBits(), llvm::ConstantRange::contains(), llvm::ISD::CTPOP, llvm::Depth, F, llvm::ConstantRange::getBitWidth(), llvm::KnownBits::getBitWidth(), llvm::MachineFunction::getFunction(), getMachineFunction(), llvm::KnownBits::getMaxValue(), llvm::getVScaleRange(), isKnownNeverZero(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonZero(), llvm::isNullConstant(), llvm::KnownBits::isStrictlyPositive(), llvm::APInt::isZero(), llvm::APInt::lshr(), llvm::ISD::matchUnaryPredicate(), MaxRecursionDepth, llvm::ISD::MUL, llvm::ConstantRange::multiply(), llvm::KnownBits::ne(), llvm::KnownBits::One, Op0, llvm::ISD::OR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SDIV, llvm::ISD::SELECT, llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::UADDSAT, llvm::ISD::UDIV, llvm::APInt::ult(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::VSCALE, llvm::ISD::VSELECT, and llvm::ISD::ZERO_EXTEND.
Referenced by canCreateUndefOrPoison(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), isCMN(), isKnownNeverZero(), isKnownToBeAPowerOfTwo(), isSafeToSpeculativelyExecuteNode(), LowerCTLZ(), LowerCTTZ(), LowerShift(), and simplifySetCCWithCTPOP().
isKnownNeverZeroFloat()
bool SelectionDAG::isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
Definition at line 6011 of file SelectionDAG.cpp.
References assert(), llvm::CallingConv::C, and llvm::ISD::matchUnaryFpPredicate().
Referenced by canIgnoreSignBitOfZero(), combineSelect(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandFMINNUM_FMAXNUM(), and LowerFMINIMUM_FMAXIMUM().
isKnownToBeAPowerOfTwo()
bool SelectionDAG::isKnownToBeAPowerOfTwo (SDValue Val, unsigned Depth = 0) const
Test if the given value is known to have exactly one bit set.
This differs from computeKnownBits in that it doesn't necessarily determine which bit is set.
Definition at line 4569 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::BitWidth, llvm::ISD::BUILD_VECTOR, llvm::CallingConv::C, llvm::Depth, llvm::dyn_cast(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::isConstOrConstSplat(), isKnownNeverZero(), isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Deferred(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_Value(), llvm::ISD::matchUnaryPredicate(), MaxRecursionDepth, llvm::SDNode::ops(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::SDPatternMatch::sd_match(), llvm::ISD::SELECT, llvm::ISD::SHL, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRL, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::VSCALE, llvm::ISD::VSELECT, X, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSelect(), isKnownToBeAPowerOfTwo(), and isKnownToBeAPowerOfTwoFP().
isKnownToBeAPowerOfTwoFP()
bool SelectionDAG::isKnownToBeAPowerOfTwoFP (SDValue Val, unsigned Depth = 0) const
Test if the given fp value is known to be an integer power-of-2, either positive or negative.
Definition at line 4653 of file SelectionDAG.cpp.
References llvm::Depth, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::isConstOrConstSplatFP(), isKnownToBeAPowerOfTwo(), llvm::ISD::SINT_TO_FP, and llvm::ISD::UINT_TO_FP.
isSafeToSpeculativelyExecute()
bool llvm::SelectionDAG::isSafeToSpeculativelyExecute (unsigned Opcode) const inline
Some opcodes may create immediate undefined behavior when used with some values (integer division-by-zero for example).
Therefore, these operations are not generally safe to move around or change.
Definition at line 2618 of file SelectionDAG.h.
References llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SREM, llvm::ISD::UDIV, llvm::ISD::UDIVREM, and llvm::ISD::UREM.
Referenced by isSafeToSpeculativelyExecuteNode(), and performBUILD_VECTORCombine().
isSafeToSpeculativelyExecuteNode()
bool llvm::SelectionDAG::isSafeToSpeculativelyExecuteNode (const SDNode * N) const inline
Check if the provided node is save to speculatively executed given its current arguments.
So, while udiv the opcode is not safe to speculatively execute, a given udiv node may be if the denominator is known nonzero.
Definition at line 2636 of file SelectionDAG.h.
References isKnownNeverZero(), isSafeToSpeculativelyExecute(), N, and llvm::ISD::UDIV.
Referenced by foldSelectWithIdentityConstant().
isSplatValue() [1/2]
bool SelectionDAG::isSplatValue (SDValue V, bool AllowUndefs = false) const
Test whether V has a splatted value.
Helper wrapper to main isSplatValue function.
Definition at line 3090 of file SelectionDAG.cpp.
References assert(), llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), isSplatValue(), and llvm::EVT::isVector().
isSplatValue() [2/2]
bool SelectionDAG::isSplatValue (SDValue V, const APInt & DemandedElts, APInt & UndefElts, unsigned Depth = 0) const
Test whether V has a splatted value for all the demanded elements.
isSplatValue - Return true if the vector V has the same value across all DemandedElts.
On success UndefElts will indicate the elements that have UNDEF values instead of the splat value, this is only guaranteed to be correct for DemandedElts.
NOTE: The function will return true for a demanded splat of UNDEF values.
For scalable vectors, we don't know the number of lanes at compile time. Instead, we use a 1 bit APInt to represent a conservative value for all lanes; that is, that one bit value is implicitly splatted across all lanes.
Definition at line 2899 of file SelectionDAG.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, assert(), llvm::ISD::BITCAST, llvm::BitWidth, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::cast(), llvm::Depth, llvm::ISD::EXTRACT_SUBVECTOR, llvm::APInt::extractBits(), llvm::APInt::getAllOnes(), llvm::APInt::getBitWidth(), llvm::APInt::getOneBitSet(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::APInt::getSplat(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZero(), I, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), isSplatValue(), llvm::EVT::isVector(), isZero(), llvm::APInt::isZero(), MaxRecursionDepth, llvm::ISD::OR, llvm::APIntOps::ScaleBitMask(), llvm::APInt::setBit(), llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SUB, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, and llvm::APInt::zext().
Referenced by canonicalizeShuffleWithOp(), combineConcatVectorOps(), combineShuffleOfSplatVal(), combineX86ShuffleChain(), getSplatSourceVector(), isOnlyUsedByStores(), isSplatValue(), isSplatValue(), LowerRotate(), lowerShuffleAsSplitOrBlend(), lowerVECTOR_SHUFFLE(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), splitVector(), and tryCombineMULLWithUZP1().
isUndef()
bool SelectionDAG::isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
Definition at line 6946 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::any_of(), assert(), llvm::SDValue::getNode(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::isNullConstant(), llvm::SDValue::isUndef(), llvm::SDNode::op_values(), llvm::ISD::SDIV, llvm::ISD::SREM, llvm::ISD::UDIV, and llvm::ISD::UREM.
Referenced by FoldConstantArithmetic(), and simplifyDivRem().
Legalize()
void SelectionDAG::Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
This is the entry point for the file.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 6228 of file LegalizeDAG.cpp.
References allnodes_begin(), allnodes_end(), AssignTopologicalOrder(), DeleteNode(), llvm::SmallPtrSetImpl< PtrType >::erase(), getNode(), getRoot(), llvm::SmallPtrSetImpl< PtrType >::insert(), Legalizer, N, and RemoveDeadNodes().
LegalizeOp()
bool SelectionDAG::LegalizeOp (SDNode * N, SmallSetVector< SDNode *, 16 > & UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
Returns
true if N is a valid, legal node after calling this.
This essentially runs a single recursive walk of the Legalize process over the given node (and its operands). This can be used to incrementally legalize the DAG. All of the nodes which are directly replaced, potentially including N, are added to the output parameter UpdatedNodes so that the delta to the DAG can be understood by the caller.
When this returns false, N has been legalized in a way that make the pointer passed in no longer valid. It may have even been deleted from the DAG, and so it shouldn't be used further. When this returns true, the N passed in is a legal node, and can be immediately processed as such. This may still have done some work on the DAG, and will still populate UpdatedNodes with any new nodes replacing those originally in the DAG.
Definition at line 6277 of file LegalizeDAG.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallPtrSetImpl< PtrType >::insert(), Legalizer, and N.
LegalizeTypes()
bool SelectionDAG::LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
Returns "true" if it made any changes.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 1053 of file LegalizeTypes.cpp.
References llvm::DAGTypeLegalizer::run().
LegalizeVectors()
bool SelectionDAG::LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
This is necessary as a separate step from Legalize because unrolling a vector operation can introduce illegal types, which requires running LegalizeTypes again.
This returns true if it made any changes; in that case, LegalizeTypes is called again before Legalize.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 2408 of file LegalizeVectorOps.cpp.
makeEquivalentMemoryOrdering() [1/2]
SDValue SelectionDAG::makeEquivalentMemoryOrdering (LoadSDNode * OldLoad, SDValue NewMemOp)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
This ensures that the new memory node will have the same relative memory dependency position as the old load. Returns the new merged load chain.
Definition at line 12837 of file SelectionDAG.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDValue::getValue(), llvm::isa(), and makeEquivalentMemoryOrdering().
makeEquivalentMemoryOrdering() [2/2]
SDValue SelectionDAG::makeEquivalentMemoryOrdering (SDValue OldChain, SDValue NewMemOpChain)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
This ensures that the new memory node will have the same relative memory dependency position as the old load. Returns the new merged load chain.
Definition at line 12819 of file SelectionDAG.cpp.
References assert(), getNode(), llvm::SDValue::getValueType(), llvm::isa(), ReplaceAllUsesOfValueWith(), llvm::ISD::TokenFactor, UpdateNodeOperands(), and llvm::SDValue::use_empty().
Referenced by combineBROADCAST_LOAD(), combineBVOfConsecutiveLoads(), combineConstantPoolLoads(), combineEXTRACT_SUBVECTOR(), combineExtractFromVectorLoad(), combineLoad(), combineStore(), combineTruncate(), EltsFromConsecutiveLoads(), getBROADCAST_LOAD(), lowerShuffleAsBroadcast(), lowerVECTOR_SHUFFLE(), makeEquivalentMemoryOrdering(), narrowExtractedVectorLoad(), performCONCAT_VECTORSCombine(), performExtBinopLoadFold(), performExtractVectorEltCombine(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
makeStateFunctionCall()
SDValue SelectionDAG::makeStateFunctionCall (unsigned LibFunc, SDValue Ptr, SDValue InChain, const SDLoc & DLoc)
Helper used to make a call to a library function that has one argument of pointer type.
Such functions include 'fegetmode', 'fesetenv' and some others, which are used to get or set floating-point state. They have one argument of pointer type, which points to the memory region containing bits of the floating-point state. The value returned by such function is ignored in the created call.
Parameters
LibFunc Reference to library function (value of RTLIB::Libcall).
Ptr Pointer used to save/load state.
InChain Ingoing token chain.
Returns
Outgoing chain token.
Definition at line 14289 of file SelectionDAG.cpp.
References assert(), getContext(), getDataLayout(), getExternalSymbol(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::Type::getVoidTy(), llvm::reportFatalUsageError(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), and llvm::TargetLowering::CallLoweringInfo::setLibCallee().
MaskedValueIsAllOnes()
bool SelectionDAG::MaskedValueIsAllOnes (SDValue Op, const APInt & Mask, unsigned Depth = 0) const
Return true if '(Op & Mask) == Mask'.
MaskedValueIsAllOnes - Return true if '(Op & Mask) == Mask'.
Op and Mask are known to be the same type.
Definition at line 2869 of file SelectionDAG.cpp.
References computeKnownBits(), and llvm::Depth.
MaskedValueIsZero() [1/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, const APInt & DemandedElts, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero in DemandedElts.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2855 of file SelectionDAG.cpp.
References computeKnownBits(), and llvm::Depth.
MaskedValueIsZero() [2/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2847 of file SelectionDAG.cpp.
References computeKnownBits(), and llvm::Depth.
Referenced by combine_CC(), combine_CC(), combineAddOfBooleanXor(), combineAddOfPMADDWD(), combineAnd(), combineCMP(), combineDeMorganOfBoolean(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineSetCC(), combineSubShiftToOrcB(), combineTargetShuffle(), combineVectorPack(), combineXorToBitfieldInsert(), combineZext(), EmitCmp(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMUL_LOHI(), foldMaskAndShiftToScale(), getBT(), getFauxShuffleMask(), getNode(), getTruncatedUSUBSAT(), isTruncWithZeroHighBitsInput(), isTruncWithZeroHighBitsInput(), LowerPARITY(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), matchLSNode(), matchShuffleWithPACK(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformORCombineToBFI(), performSETCCCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), selectUmullSmull(), ShrinkLoadReplaceStoreWithStore(), SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), and tryDemorganOfBooleanCondition().
MaskedVectorIsZero()
bool SelectionDAG::MaskedVectorIsZero (SDValue V, const APInt & DemandedElts, unsigned Depth = 0) const
Return true if 'Op' is known to be zero in DemandedElts.
MaskedVectorIsZero - Return true if 'Op' is known to be zero in DemandedElts.
We use this predicate to simplify operations downstream.
Definition at line 2863 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::KnownBits::isZero().
Referenced by combineOr(), computeVectorKnownZeroElements(), isTargetShuffleEquivalent(), matchBinaryShuffle(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
matchBinOpReduction()
SDValue SelectionDAG::matchBinOpReduction (SDNode * Extract, ISD::NodeType & BinOp, ArrayRef< ISD::NodeType > CandidateBinOps, bool AllowPartials = false)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
The reduction must use one of the opcodes listed in /p CandidateBinOps and on success /p BinOp will contain the matching opcode. Returns the vector that is being reduced on, or SDValue() if a reduction was not matched. If AllowPartials is set then in the case of a reduction pattern that only matches the first few stages, the extracted subvector of the start of the reduction is returned.
Definition at line 13291 of file SelectionDAG.cpp.
References llvm::dyn_cast(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::SDValue::getConstantOperandAPInt(), getContext(), getExtractSubvector(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::EVT::getVectorVT(), llvm::isNullConstant(), llvm_unreachable, llvm::Log2_32(), llvm::none_of(), and Op0.
Referenced by combineArithReduction(), combineBasicSADPattern(), combineMinMaxReduction(), combinePredicateReduction(), combineVPDPBUSDPattern(), and MatchVectorAllEqualTest().
MorphNodeTo()
SDNode * SelectionDAG::MorphNodeTo (SDNode * N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
MorphNodeTo - This mutates the specified node to have the specified return type, opcode, and operands.
Note that MorphNodeTo returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one. Note that the SDLoc need not be the same.
Using MorphNodeTo is faster than creating a new node and swapping it in with ReplaceAllUsesWith both because it often avoids allocating a new node, and because it doesn't require CSE recalculation for any of the node's users.
However, note that MorphNodeTo recursively deletes dead nodes from the DAG. As a consequence it isn't appropriate to use from within the DAG combiner or the legalizer which maintain worklists that would need to be updated when deleting things.
Definition at line 11660 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AddNodeIDNode(), llvm::dyn_cast(), llvm::SmallPtrSetImplBase::empty(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), N, llvm::SDVTList::NumVTs, Opc, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveDeadNodes(), llvm::Use::set(), and llvm::SDVTList::VTs.
Referenced by CloneNodeWithValues(), llvm::NVPTXTargetLowering::LowerCall(), mutateStrictFPToFP(), and SelectNodeTo().
mutateStrictFPToFP()
SDNode * SelectionDAG::mutateStrictFPToFP (SDNode * Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
The node must be a strict FP node.
Definition at line 11713 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), getVTList(), llvm_unreachable, MorphNodeTo(), RemoveDeadNode(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), and llvm::SDNode::setNodeId().
operator=()
SelectionDAG & llvm::SelectionDAG::operator= (const SelectionDAG &) delete
References LLVM_ABI, and SelectionDAG().
RemoveDeadNode()
void SelectionDAG::RemoveDeadNode (SDNode * N)
Remove the specified node from the system.
If any of its operands then becomes dead, remove them as well. Inform UpdateListener for each node deleted.
Definition at line 1076 of file SelectionDAG.cpp.
References getRoot(), N, and RemoveDeadNodes().
Referenced by foldADDIForFasterLocalAccesses(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::TargetLowering::getCheaperOrNeutralNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), llvm::SITargetLowering::legalizeTargetIndependentNode(), mutateStrictFPToFP(), and SelectNodeTo().
RemoveDeadNodes() [1/2]
void SelectionDAG::RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
RemoveDeadNodes - This method deletes all unreachable nodes in the SelectionDAG.
Definition at line 1022 of file SelectionDAG.cpp.
References allnodes(), getRoot(), llvm::HandleSDNode::getValue(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RemoveDeadNodes(), and setRoot().
Referenced by Legalize(), MorphNodeTo(), RemoveDeadNode(), and RemoveDeadNodes().
RemoveDeadNodes() [2/2]
void SelectionDAG::RemoveDeadNodes (SmallVectorImpl< SDNode * > & DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
RemoveDeadNodes - This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
Definition at line 1042 of file SelectionDAG.cpp.
References llvm::ISD::DELETED_NODE, llvm::SmallVectorTemplateCommon< T, typename >::empty(), I, N, llvm::SelectionDAG::DAGUpdateListener::Next, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Use::set(), and llvm::SDNode::use_empty().
ReplaceAllUsesOfValuesWith()
void SelectionDAG::ReplaceAllUsesOfValuesWith (const SDValue * From, const SDValue * To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
ReplaceAllUsesOfValuesWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
This correctly handles the case where there is an overlap between the From values and the To values.
The same value may appear in both the From and To list. The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 12615 of file SelectionDAG.cpp.
References copyExtraInfo(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), llvm::Use::getUser(), ReplaceAllUsesOfValueWith(), llvm::Use::set(), llvm::sort(), transferDbgValues(), Uses, and llvm::SDNode::uses().
ReplaceAllUsesOfValueWith()
void SelectionDAG::ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
ReplaceAllUsesOfValueWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 12440 of file SelectionDAG.cpp.
References copyExtraInfo(), llvm::SDValue::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getResNo(), getRoot(), llvm::SDUse::getUser(), llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), updateDivergence(), llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), adjustSubwordCmp(), combineBitcast(), combineCarryDiamond(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineExtractWithShuffle(), combineMOVDQ2Q(), combineSelect(), combineSetCCAtomicArith(), combineSIntToFP(), combineTargetShuffle(), combineVSelectToBLENDV(), combineX86INT_TO_FP(), emitIntrinsicWithCCAndChain(), EmitTest(), llvm::TargetLowering::expandMultipleResultFPLibCall(), lowerBUILD_VECTORAsBroadCastLoad(), lowerBuildVectorAsBroadcast(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), makeEquivalentMemoryOrdering(), mutateStrictFPToFP(), performConcatVectorsCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDivRemCombine(), performExtractVectorEltCombine(), PerformHWLoopCombine(), performIntToFpCombine(), PerformORCombineToSMULWBT(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), performUnpackCombine(), PerformVDUPCombine(), performVectorDeinterleaveCombine(), PerformVMOVhrCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), performVP_REVERSECombine(), reduceANDOfAtomicLoad(), reduceVSXSwap(), ReplaceAllUsesOfValuesWith(), SkipExtensionForVMULL(), tryToFoldExtOfAtomicLoad(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), tryToFoldExtOfMaskedLoad(), and widenBuildVec().
ReplaceAllUsesWith() [1/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, const SDValue * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version can replace From with any result values. To must match the number and types of values returned by From.
Definition at line 12389 of file SelectionDAG.cpp.
References copyExtraInfo(), getNode(), llvm::SDNode::getNumValues(), getRoot(), llvm::SDUse::getUser(), llvm::SDValue::getValueType(), llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), updateDivergence(), llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
ReplaceAllUsesWith() [2/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, SDNode * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version assumes that for each value of From, there is a corresponding value in To in the same position with the same type.
Definition at line 12331 of file SelectionDAG.cpp.
References assert(), copyExtraInfo(), getNode(), llvm::SDNode::getNumValues(), getRoot(), llvm::SDUse::getUser(), llvm::SDNode::getValueType(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDNode::isDivergent(), setRoot(), transferDbgValues(), updateDivergence(), llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
ReplaceAllUsesWith() [3/3]
void SelectionDAG::ReplaceAllUsesWith (SDValue FromN, SDValue To)
Modify anything using 'From' to use 'To' instead.
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG. Use the first version if 'From' is known to have a single result, use the second if you have two nodes with identical results (or if 'To' has a superset of the results of 'From'), use the third otherwise.
These methods all take an optional UpdateListener, which (if not null) is informed about nodes that are deleted and modified due to recursive changes in the dag.
These functions only replace all existing uses. It's possible that as these replacements are being performed, CSE may cause the From node to be given new uses. These new uses of From are left in place, and not automatically transferred to To.
This can cause recursive merging of nodes in the DAG.
This version assumes From has a single result value.
Definition at line 12278 of file SelectionDAG.cpp.
References assert(), copyExtraInfo(), llvm::SDValue::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getResNo(), getRoot(), llvm::SDUse::getUser(), llvm::SDNode::isDivergent(), llvm::Use::set(), setRoot(), transferDbgValues(), updateDivergence(), llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by emitComparison(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LowerAVXCONCAT_VECTORS(), lowerShufflePairAsUNPCKAndPermute(), mutateStrictFPToFP(), narrowBitOpRMW(), performCONDCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), PerformHWLoopCombine(), PerformLongShiftCombine(), performSETCCCombine(), performSTORECombine(), reassociateCSELOperandsForCSE(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), SelectNodeTo(), tryCombineMULLWithUZP1(), and tryMemPairCombine().
RepositionNode()
void llvm::SelectionDAG::RepositionNode (allnodes_iterator Position, SDNode * N) inline
Move node N in the AllNodes list to be immediately before the given iterator Position.
This may be used to update the topological ordering when the list of nodes is modified.
Definition at line 1998 of file SelectionDAG.h.
References N.
Referenced by insertDAGNode(), and insertDAGNode().
salvageDebugInfo()
void SelectionDAG::salvageDebugInfo (SDNode & N)
To be invoked on an SDNode that is slated to be erased.
This function mirrors llvm::salvageDebugInfo.
Definition at line 12107 of file SelectionDAG.cpp.
References llvm::ISD::ADD, AddDbgValue(), llvm::any_of(), llvm::DIExpression::appendOffset(), llvm::DIExpression::appendOpsToArg(), assert(), llvm::DIExpression::convertToVariadicExpression(), llvm::dbgs(), llvm::dwarf::DW_OP_LLVM_arg, llvm::dyn_cast(), llvm::SDDbgOperand::fromFrameIdx(), llvm::SDDbgOperand::fromNode(), getDbgValueList(), GetDbgValues(), llvm::DIExpression::getExtOps(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), llvm::SDValue::getValueSizeInBits(), llvm::isa(), LLVM_DEBUG, N, llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SDDbgOperand::SDNODE, and llvm::ISD::TRUNCATE.
SelectNodeTo() [1/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
SelectNodeTo - These are wrappers around MorphNodeTo that accept a machine opcode.
Note that target opcodes are stored as ~TargetOpcode in the node opcode field. The resultant node is returned.
Definition at line 11553 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
Referenced by SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), SelectNodeTo(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), and tryOrrWithShift().
SelectNodeTo() [2/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 11582 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getVTList(), N, and SelectNodeTo().
SelectNodeTo() [3/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1)
Definition at line 11559 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getVTList(), N, and SelectNodeTo().
SelectNodeTo() [4/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 11566 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getVTList(), N, and SelectNodeTo().
SelectNodeTo() [5/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 11574 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getVTList(), N, and SelectNodeTo().
SelectNodeTo() [6/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2)
Definition at line 11594 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [7/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 11588 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getVTList(), N, and SelectNodeTo().
SelectNodeTo() [8/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 11600 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getVTList(), N, and SelectNodeTo().
SelectNodeTo() [9/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 11607 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, getVTList(), N, and SelectNodeTo().
SelectNodeTo() [10/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 11615 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, MorphNodeTo(), N, RemoveDeadNode(), and ReplaceAllUsesWith().
setFlagInserter()
void llvm::SelectionDAG::setFlagInserter (FlagInserter * FI) inline
Definition at line 518 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::FlagInserter::FlagInserter().
setFunctionLoweringInfo()
void llvm::SelectionDAG::setFunctionLoweringInfo (FunctionLoweringInfo * FuncInfo) inline
Definition at line 485 of file SelectionDAG.h.
setGraphAttrs()
void SelectionDAG::setGraphAttrs (const SDNode * N, const char * Attrs)
Set graph attributes for a node. (eg. "color=red".).
setGraphAttrs - Set graph attributes for a node.
(eg. "color=red".)
Definition at line 191 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and N.
setGraphColor()
void SelectionDAG::setGraphColor (const SDNode * N, const char * Color)
Convenience for setting node color attribute.
setGraphColor - Convenience for setting node color attribute.
Definition at line 221 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and N.
setNodeMemRefs()
void SelectionDAG::setNodeMemRefs (MachineSDNode * N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
Definition at line 11529 of file SelectionDAG.cpp.
References llvm::copy(), llvm::ArrayRef< T >::empty(), N, and llvm::ArrayRef< T >::size().
Referenced by CloneNodeWithValues(), llvm::AArch64SelectionDAGInfo::EmitMOPS(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), getLoadStackGuard(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceCMP_XCHG_128Results(), and llvm::X86InstrInfo::unfoldMemoryOperand().
setRoot()
const SDValue & llvm::SelectionDAG::setRoot (SDValue N) inline
Set the current root tag of the SelectionDAG.
Definition at line 587 of file SelectionDAG.h.
References assert(), llvm::checkForCycles(), and N.
Referenced by llvm::TargetLowering::LowerCallTo(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), RemoveDeadNodes(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), ReplaceAllUsesWith(), and ReplaceAllUsesWith().
setSubgraphColor()
void SelectionDAG::setSubgraphColor (SDNode * N, const char * Color)
Convenience for setting subgraph color attribute.
setSubgraphColor - Convenience for setting subgraph color attribute.
Definition at line 265 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and N.
shouldOptForSize()
bool SelectionDAG::shouldOptForSize () const
Definition at line 1395 of file SelectionDAG.cpp.
References llvm::shouldOptimizeForSize().
Referenced by combineX86ShuffleChain(), combineX86ShufflesConstants(), llvm::TargetLowering::expandDIVREMByConstant(), ExpandPowI(), getConstantPool(), LowerAndToBT(), lowerBuildVectorAsBroadcast(), lowerBuildVectorOfConstants(), lowerBuildVectorViaDominantValues(), lowerConstant(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), LowerFunnelShift(), lowerShuffleAsBlend(), shouldLowerMemFuncForSize(), and shouldUseHorizontalOp().
SignBitIsZero()
bool SelectionDAG::SignBitIsZero (SDValue Op, unsigned Depth = 0) const
Return true if the sign bit of Op is known to be zero.
SignBitIsZero - Return true if the sign bit of Op is known to be zero.
We use this predicate to simplify operations downstream.
Definition at line 2796 of file SelectionDAG.cpp.
References llvm::BitWidth, llvm::Depth, llvm::APInt::getSignMask(), and MaskedValueIsZero().
Referenced by canReduceVMulWidth(), checkSignTestSetCCCombine(), combineUIntToFP(), llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandIntMINMAX(), getCmp(), LowerVSETCC(), matchExtFromI32orI32(), and performVectorNonNegToFPCombine().
SignBitIsZeroFP()
bool SelectionDAG::SignBitIsZeroFP (SDValue Op, unsigned Depth = 0) const
Return true if the sign bit of Op is known to be zero, for a floating-point value.
Definition at line 2802 of file SelectionDAG.cpp.
References llvm::ISD::ARITH_FENCE, llvm::ISD::AssertNoFPClass, llvm::Depth, llvm::ISD::FABS, llvm::fcNan, llvm::fcNegative, llvm::ISD::FEXP, llvm::ISD::FEXP10, llvm::ISD::FEXP2, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXIMUMNUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINIMUMNUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm_unreachable, MaxRecursionDepth, Opc, and SignBitIsZeroFP().
Referenced by SignBitIsZeroFP().
simplifyFPBinop()
SDValue SelectionDAG::simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y, SDNodeFlags Flags)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
Definition at line 10900 of file SelectionDAG.cpp.
References llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FSUB, getConstantFP(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::isConstOrConstSplatFP(), llvm::APFloat::isExactlyValue(), llvm::APFloat::isNegZero(), llvm::APFloat::isPosZero(), llvm::APFloat::isZero(), X, and Y.
Referenced by getNode().
simplifySelect()
SDValue SelectionDAG::simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
Definition at line 10849 of file SelectionDAG.cpp.
References llvm::CallingConv::C, Cond, F, getFreeze(), isBoolConstant(), isConstantValueOfAnyType(), isGuaranteedNotToBePoison(), and T.
Referenced by combineSelect(), and getNode().
simplifyShift()
SDValue SelectionDAG::simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
Definition at line 10872 of file SelectionDAG.cpp.
References getConstant(), getUNDEF(), llvm::isNullOrNullSplat(), llvm::ISD::matchUnaryPredicate(), X, and Y.
Referenced by getNode().
SplitEVL()
std::pair< SDValue, SDValue > SelectionDAG::SplitEVL (SDValue N, EVT VecVT, const SDLoc & DL)
Split the explicit vector length parameter of a VP operation.
Definition at line 13710 of file SelectionDAG.cpp.
References assert(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::divideCoefficientBy(), DL, getElementCount(), getNode(), llvm::EVT::getVectorElementCount(), llvm::Hi, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownEven(), llvm::Lo, N, llvm::ISD::UMIN, and llvm::ISD::USUBSAT.
Referenced by SplitVectorReductionOp(), and SplitVPOp().
SplitScalar()
std::pair< SDValue, SDValue > SelectionDAG::SplitScalar (const SDValue & N, const SDLoc & DL, const EVT & LoVT, const EVT & HiVT)
Split the scalar node with EXTRACT_ELEMENT using the provided VTs and return the low/high part.
Definition at line 13630 of file SelectionDAG.cpp.
References assert(), DL, llvm::ISD::EXTRACT_ELEMENT, getIntPtrConstant(), getNode(), llvm::Hi, llvm::EVT::isVector(), llvm::Lo, and N.
Referenced by createGPRPairNode(), createGPRPairNodei64(), Expand64BitShift(), expandBitCastI128ToF128(), llvm::TargetLowering::expandDIVREMByConstant(), getMaskNode(), initAccumulator(), LowerBITCAST(), lowerI128ToGR128(), llvm::AArch64TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerVectorAllEqual(), lowerVectorIntrinsicScalars(), LowerWRITE_REGISTER(), Passv64i1ArgInRegs(), PerformADDVecReduce(), performMADD_MSUBCombine(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), replaceCMP_XCHG_128Results(), ReplaceLongIntrinsic(), llvm::X86TargetLowering::ReplaceNodeResults(), splatSplitI64WithVL(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), and WinDBZCheckDenominator().
SplitVector() [1/2]
std::pair< SDValue, SDValue > llvm::SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL) inline
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 2489 of file SelectionDAG.h.
References DL, GetSplitDestVTs(), N, and SplitVector().
SplitVector() [2/2]
std::pair< SDValue, SDValue > SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL, const EVT & LoVT, const EVT & HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provided VTs and return the low/high part.
SplitVector - Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 13690 of file SelectionDAG.cpp.
References assert(), DL, llvm::ISD::EXTRACT_SUBVECTOR, getExtractSubvector(), getNode(), getVectorIdxConstant(), llvm::EVT::getVectorMinNumElements(), llvm::Hi, llvm::EVT::isScalableVector(), llvm::Lo, and N.
Referenced by combineHorizOpWithShuffle(), combinePredicateReduction(), llvm::TargetLowering::expandVecReduce(), llvm::TargetLowering::expandVectorNaryOpBySplitting(), getPMOVMSKB(), getVectorBitwiseReduce(), isHorizontalBinOp(), LowerVecReduceMinMax(), LowerVectorAllEqual(), performBITCASTCombine(), ReplaceAddWithADDP(), llvm::X86TargetLowering::ReplaceNodeResults(), SplitStrictFPVectorOp(), SplitVector(), SplitVectorOp(), SplitVectorOperand(), SplitVectorReductionOp(), and SplitVPOp().
SplitVectorOperand()
std::pair< SDValue, SDValue > llvm::SelectionDAG::SplitVectorOperand (const SDNode * N, unsigned OpNo) inline
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 2501 of file SelectionDAG.h.
References N, and SplitVector().
Referenced by LowerCVTPS2PH(), LowerTruncate(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), llvm::SITargetLowering::splitBinaryVectorOp(), llvm::SITargetLowering::splitTernaryVectorOp(), and llvm::SITargetLowering::splitUnaryVectorOp().
transferDbgValues()
void SelectionDAG::transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits = 0, unsigned SizeInBits = 0, bool InvalidateDbg = true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
If InvalidateDbg is set, debug values are invalidated after they are transferred.
Definition at line 12025 of file SelectionDAG.cpp.
References AddDbgValue(), assert(), llvm::DIExpression::createFragmentExpression(), llvm::SDDbgOperand::fromNode(), getDbgValueList(), GetDbgValues(), llvm::SDNode::getHasDebugValue(), llvm::SDNode::getIROrder(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), llvm::is_contained(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by getNode(), ReplaceAllUsesOfValuesWith(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), ReplaceAllUsesWith(), and ReplaceAllUsesWith().
UnrollVectorOp()
SDValue SelectionDAG::UnrollVectorOp (SDNode * N, unsigned ResNE = 0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
If the ResNE is 0, fully unroll the vector op. If ResNE is less than the width of the vector op, unroll up to ResNE. If the ResNE is greater than the width of the vector op, unroll the vector op and fill the end of the resulting vector with UNDEFS.
Definition at line 13406 of file SelectionDAG.cpp.
References llvm::ISD::ADDRSPACECAST, assert(), llvm::cast(), getAddrSpaceCast(), getBuildVector(), getContext(), getExtractVectorElt(), getMergeValues(), getNode(), getShiftAmountOperand(), getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::EVT::isVector(), N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SELECT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::VSELECT.
Referenced by llvm::TargetLowering::expandABD(), llvm::TargetLowering::expandAddSubSat(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::TargetLowering::expandIntMINMAX(), llvm::TargetLowering::expandShlSat(), llvm::RISCVTargetLowering::LowerOperation(), llvm::SITargetLowering::lowerROTR(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), and unrollVectorShift().
UnrollVectorOverflowOp()
std::pair< SDValue, SDValue > SelectionDAG::UnrollVectorOverflowOp (SDNode * N, unsigned ResNE = 0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
This is a separate function because those opcodes have two results.
Definition at line 13516 of file SelectionDAG.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), ExtractVectorElements(), getBoolConstant(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), getSelect(), getUNDEF(), llvm::SDValue::getValue(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::SADDO, llvm::ISD::SMULO, llvm::ISD::SSUBO, llvm::ISD::UADDO, llvm::ISD::UMULO, and llvm::ISD::USUBO.
updateDivergence()
void SelectionDAG::updateDivergence (SDNode * N)
Definition at line 12569 of file SelectionDAG.cpp.
References llvm::append_range(), calculateDivergence(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), N, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), ReplaceAllUsesWith(), ReplaceAllUsesWith(), UpdateNodeOperands(), UpdateNodeOperands(), and UpdateNodeOperands().
UpdateNodeOperands() [1/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, ArrayRef< SDValue > Ops)
Definition at line 11487 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::NumOps, AbstractManglingParser< Derived, Alloc >::Ops, assert(), N, and updateDivergence().
UpdateNodeOperands() [2/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
UpdateNodeOperands - Mutate the specified node in-place to have the specified operands.
If the resultant node already exists in the DAG, this does not modify the specified node, instead it returns the node that already exists. If the resultant node does not exist in the DAG, the input node is returned. As a degenerate case, if you specify the same input operands as the node already has, the input node is returned.
Definition at line 11413 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
Referenced by foldADDIForFasterLocalAccesses(), llvm::SITargetLowering::legalizeTargetIndependentNode(), makeEquivalentMemoryOrdering(), moveBelowOrigChain(), llvm::AMDGPUTargetLowering::performIntrinsicWOChainCombine(), UpdateNodeOperands(), UpdateNodeOperands(), and UpdateNodeOperands().
UpdateNodeOperands() [3/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2)
Definition at line 11438 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
UpdateNodeOperands() [4/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 11467 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, N, and UpdateNodeOperands().
UpdateNodeOperands() [5/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
Definition at line 11473 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, N, and UpdateNodeOperands().
UpdateNodeOperands() [6/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
Definition at line 11480 of file SelectionDAG.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, N, and UpdateNodeOperands().
viewGraph() [1/2]
void SelectionDAG::viewGraph ()
Definition at line 159 of file SelectionDAGPrinter.cpp.
References viewGraph().
Referenced by viewGraph().
viewGraph() [2/2]
void SelectionDAG::viewGraph (const std::string & Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
viewGraph - Pop up a ghostview window with the reachable parts of the DAG rendered using 'dot'.
Definition at line 146 of file SelectionDAGPrinter.cpp.
References llvm::errs(), getMachineFunction(), getName(), and llvm::ViewGraph().
WidenVector()
SDValue SelectionDAG::WidenVector (const SDValue & N, const SDLoc & DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
Definition at line 13725 of file SelectionDAG.cpp.
References DL, getContext(), getInsertSubvector(), getUNDEF(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), N, and llvm::NextPowerOf2().
willNotOverflowAdd()
bool llvm::SelectionDAG::willNotOverflowAdd (bool IsSigned, SDValue N0, SDValue N1) const inline
Determine if the result of the addition of 2 nodes can never overflow.
Definition at line 2160 of file SelectionDAG.h.
References computeOverflowForAdd(), and OFK_Never.
Referenced by combineAdd(), combineShiftToAVG(), and promoteExtBeforeAdd().
willNotOverflowMul()
bool llvm::SelectionDAG::willNotOverflowMul (bool IsSigned, SDValue N0, SDValue N1) const inline
Determine if the result of the mul of 2 nodes can never overflow.
Definition at line 2200 of file SelectionDAG.h.
References computeOverflowForMul(), and OFK_Never.
willNotOverflowSub()
bool llvm::SelectionDAG::willNotOverflowSub (bool IsSigned, SDValue N0, SDValue N1) const inline
Determine if the result of the sub of 2 nodes can never overflow.
Definition at line 2180 of file SelectionDAG.h.
References computeOverflowForSub(), and OFK_Never.
Referenced by llvm::TargetLowering::expandABD().
Friends And Related Symbol Documentation
DAGUpdateListener
friend struct DAGUpdateListener friend
DAGUpdateListener is a friend so it can manipulate the listener stack.
Definition at line 402 of file SelectionDAG.h.
References N.
Member Data Documentation
MaxRecursionDepth
unsigned llvm::SelectionDAG::MaxRecursionDepth = 6 static constexpr
Definition at line 459 of file SelectionDAG.h.
Referenced by checkBitcastSrcVectorSize(), checkBitcastSrcVectorSize(), collectInstructionDeps(), combineBitcastToBoolVector(), combineConcatVectorOps(), computeKnownBits(), ComputeNumSignBits(), EltsFromConsecutiveLoads(), llvm::PPCTargetLowering::getNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), getShuffleScalarElt(), getTargetShuffleInputs(), getUsefulBits(), llvm::RISCVDAGToDAGISel::hasAllNBitUsers(), isFNEG(), isGuaranteedNotToBeUndefOrPoison(), isKnownNeverNaN(), isKnownNeverZero(), isKnownToBeAPowerOfTwo(), isSplatValue(), PromoteMaskArithmetic(), llvm::SelectionDAGBuilder::shouldKeepJumpConditionsTogether(), SignBitIsZeroFP(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), and takeInexpensiveLog2().
NewNodesMustHaveLegalTypes
bool llvm::SelectionDAG::NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
This is important after type legalization since any illegally typed nodes generated after this point will not experience type legalization.
Definition at line 398 of file SelectionDAG.h.
Referenced by combineBinOpOfExtractToReduceTree(), FoldConstantArithmetic(), getConstant(), and getNode().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAG.h
lib/CodeGen/SelectionDAG/DAGCombiner.cpp
lib/CodeGen/SelectionDAG/LegalizeDAG.cpp
lib/CodeGen/SelectionDAG/LegalizeTypes.cpp
lib/CodeGen/SelectionDAG/LegalizeVectorOps.cpp
lib/CodeGen/SelectionDAG/SelectionDAG.cpp
lib/CodeGen/SelectionDAG/SelectionDAGDumper.cpp
lib/CodeGen/SelectionDAG/SelectionDAGPrinter.cpp