LLVM: llvm::objcopy::elf::DynamicRelocationSection Class Reference
llvm::objcopy::elf::DynamicRelocationSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
DynamicRelocationSection (ArrayRef< uint8_t > Data)
Error accept (SectionVisitor &) const override
Error accept (MutableSectionVisitor &Visitor) override
Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override
Public Member Functions inherited from llvm::objcopy::elf::RelocSectionWithSymtabBase< DynamicSymbolTableSection >
Error initialize (SectionTableRef SecTable) override
void finalize () override
Public Member Functions inherited from llvm::objcopy::elf::RelocationSectionBase
const SectionBase * getSection () const
void setSection (SectionBase *Sec)
StringRef getNamePrefix () const
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
virtual void markSymbols ()
virtual void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &)
virtual bool hasContents () const
virtual ArrayRef< uint8_t > getContents () const
virtual void onRemove ()
virtual void restoreSymTabLink (SymbolTableSection &)
Static Public Member Functions
static bool classof (const SectionBase *S)
Static Public Member Functions inherited from llvm::objcopy::elf::RelocationSectionBase
static bool classof (const SectionBase *S)
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Protected Member Functions inherited from llvm::objcopy::elf::RelocSectionWithSymtabBase< DynamicSymbolTableSection >
RelocSectionWithSymtabBase ()=default
Protected Attributes inherited from llvm::objcopy::elf::RelocSectionWithSymtabBase< DynamicSymbolTableSection >
DynamicSymbolTableSection * Symbols
Protected Attributes inherited from llvm::objcopy::elf::RelocationSectionBase
SectionBase * SecToApplyRel = nullptr
Detailed Description
Definition at line 1001 of file ELFObject.h.
Constructor & Destructor Documentation
DynamicRelocationSection()
llvm::objcopy::elf::DynamicRelocationSection::DynamicRelocationSection (ArrayRef< uint8_t > Data) inline explicit
Definition at line 1009 of file ELFObject.h.
References llvm::Data.
Member Function Documentation
accept() [1/2]
Error DynamicRelocationSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 1040 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error DynamicRelocationSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 1036 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
classof()
bool llvm::objcopy::elf::DynamicRelocationSection::classof (const SectionBase * S) inline static
Definition at line 1017 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::OriginalFlags, llvm::objcopy::elf::SectionBase::OriginalType, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_REL, and llvm::ELF::SHT_RELA.
removeSectionReferences()
Error DynamicRelocationSection::removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1044 of file ELFObject.cpp.
References assert(), llvm::createStringError(), llvm::invalid_argument, llvm::objcopy::elf::RelocationSectionBase::SecToApplyRel, llvm::Error::success(), llvm::objcopy::elf::RelocSectionWithSymtabBase< DynamicSymbolTableSection >::Symbols, and ToRemove.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp