LLVM: llvm::ProfileAnnotatorImpl Class Reference
llvm::ProfileAnnotatorImpl Class Reference final
Public Member Functions
ProfileAnnotatorImpl (const Function &F, ArrayRef< uint64_t > Counters)
uint64_t getBBCount (const BasicBlock &BB)
Friends
class ProfileAnnotator
Detailed Description
Definition at line 56 of file CtxProfAnalysis.cpp.
Constructor & Destructor Documentation
ProfileAnnotatorImpl()
llvm::ProfileAnnotatorImpl::ProfileAnnotatorImpl (const Function & F, ArrayRef< uint64_t > Counters) inline
Definition at line 314 of file CtxProfAnalysis.cpp.
References assert(), llvm::Count, llvm::count_if(), llvm::CtxProfAnalysis::getBBInstrumentation(), I, llvm::isa(), llvm::pred_size(), llvm::succ_size(), and llvm::successors().
Member Function Documentation
getBBCount()
uint64_t llvm::ProfileAnnotatorImpl::getBBCount (const BasicBlock & BB) inline
Definition at line 362 of file CtxProfAnalysis.cpp.
Friends And Related Symbol Documentation
ProfileAnnotator
friend class ProfileAnnotator friend
Definition at line 57 of file CtxProfAnalysis.cpp.
References llvm::Count, and ProfileAnnotator.
Referenced by ProfileAnnotator.
The documentation for this class was generated from the following file:
lib/Analysis/CtxProfAnalysis.cpp