LLVM: llvm::object::TapiUniversal::ObjectForArch Class Reference
llvm::object::TapiUniversal::ObjectForArch Class Reference
#include "llvm/Object/TapiUniversal.h"
Public Member Functions
ObjectForArch (const TapiUniversal *Parent, int Index)
ObjectForArch getNext () const
bool operator== (const ObjectForArch &Other) const
uint32_t getCPUType () const
uint32_t getCPUSubType () const
StringRef getArchFlagName () const
std::string getInstallName () const
bool isTopLevelLib () const
LLVM_ABI Expected< std::unique_ptr< TapiFile > > getAsObjectFile () const
Detailed Description
Definition at line 31 of file TapiUniversal.h.
Constructor & Destructor Documentation
ObjectForArch()
llvm::object::TapiUniversal::ObjectForArch::ObjectForArch (const TapiUniversal * Parent, int Index) inline
Definition at line 36 of file TapiUniversal.h.
References llvm::object::TapiUniversal::TapiUniversal().
Referenced by getNext(), and operator==().
Member Function Documentation
getArchFlagName()
StringRef llvm::object::TapiUniversal::ObjectForArch::getArchFlagName () const inline
Definition at line 57 of file TapiUniversal.h.
References llvm::MachO::getArchitectureName().
getAsObjectFile()
Expected< std::unique_ptr< TapiFile > > TapiUniversal::ObjectForArch::getAsObjectFile () const
Definition at line 48 of file TapiUniversal.cpp.
References assert(), and isTopLevelLib().
getCPUSubType()
uint32_t llvm::object::TapiUniversal::ObjectForArch::getCPUSubType () const inline
Definition at line 51 of file TapiUniversal.h.
References llvm::MachO::getCPUTypeFromArchitecture().
getCPUType()
uint32_t llvm::object::TapiUniversal::ObjectForArch::getCPUType () const inline
Definition at line 45 of file TapiUniversal.h.
References llvm::MachO::getCPUTypeFromArchitecture().
getInstallName()
std::string llvm::object::TapiUniversal::ObjectForArch::getInstallName () const inline
Definition at line 61 of file TapiUniversal.h.
Referenced by isTopLevelLib().
getNext()
ObjectForArch llvm::object::TapiUniversal::ObjectForArch::getNext () const inline
Definition at line 39 of file TapiUniversal.h.
References ObjectForArch().
isTopLevelLib()
bool llvm::object::TapiUniversal::ObjectForArch::isTopLevelLib () const inline
Definition at line 65 of file TapiUniversal.h.
References getInstallName().
Referenced by getAsObjectFile().
operator==()
bool llvm::object::TapiUniversal::ObjectForArch::operator== (const ObjectForArch & Other) const inline
Definition at line 41 of file TapiUniversal.h.
References ObjectForArch().
The documentation for this class was generated from the following files:
include/llvm/Object/TapiUniversal.h
lib/Object/TapiUniversal.cpp