LLVM: llvm::RecTy Class Reference
llvm::RecTy Class Reference abstract
#include "llvm/TableGen/Record.h"
Public Types
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.).
Public Member Functions
RecTy (RecTyKind K, RecordKeeper &RK)
virtual ~RecTy ()=default
RecTyKind getRecTyKind () const
RecordKeeper & getRecordKeeper () const
Return the RecordKeeper that uniqued this Type.
virtual std::string getAsString () const =0
void print (raw_ostream &OS) const
void dump () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
Return true if all values of 'this' type can be converted to the specified type.
virtual bool typeIsA (const RecTy *RHS) const
Return true if 'this' type is equal to or a subtype of RHS.
const ListRecTy * getListTy () const
Returns the type representing list<thistype>.
Detailed Description
Definition at line 61 of file Record.h.
Member Enumeration Documentation
RecTyKind
enum llvm::RecTy::RecTyKind
Subclass discriminator (for dyn_cast<> et al.).
Enumerator
BitRecTyKind
BitsRecTyKind
IntRecTyKind
StringRecTyKind
ListRecTyKind
DagRecTyKind
RecordRecTyKind
Definition at line 64 of file Record.h.
Constructor & Destructor Documentation
RecTy()
llvm::RecTy::RecTy (RecTyKind K, RecordKeeper & RK) inline
Definition at line 83 of file Record.h.
Referenced by llvm::BitRecTy::classof(), llvm::BitsRecTy::classof(), llvm::DagRecTy::classof(), llvm::IntRecTy::classof(), llvm::ListRecTy::classof(), llvm::RecordRecTy::classof(), llvm::StringRecTy::classof(), llvm::ListRecTy::get(), llvm::ListRecTy::getElementType(), llvm::ListRecTy::RecTy::getListTy, llvm::ListRecTy::typeIsA(), llvm::RecordRecTy::typeIsA(), typeIsA(), llvm::BitRecTy::typeIsConvertibleTo(), llvm::BitsRecTy::typeIsConvertibleTo(), llvm::IntRecTy::typeIsConvertibleTo(), llvm::ListRecTy::typeIsConvertibleTo(), llvm::RecordRecTy::typeIsConvertibleTo(), typeIsConvertibleTo(), and llvm::StringRecTy::typeIsConvertibleTo().
~RecTy()
virtual llvm::RecTy::~RecTy () virtual default
Member Function Documentation
dump()
LLVM_DUMP_METHOD void RecTy::dump () const
Definition at line 135 of file Record.cpp.
References llvm::errs(), LLVM_DUMP_METHOD, and llvm::print().
getAsString()
virtual std::string llvm::RecTy::getAsString () const pure virtual
Implemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Referenced by llvm::UnOpInit::Fold(), llvm::BinOpInit::getAsString(), llvm::UnOpInit::getAsString(), and print().
getListTy()
const ListRecTy * RecTy::getListTy () const
Returns the type representing list<thistype>.
Definition at line 138 of file Record.cpp.
Referenced by llvm::resolveTypes().
getRecordKeeper()
RecordKeeper & llvm::RecTy::getRecordKeeper () const inline
Return the RecordKeeper that uniqued this Type.
Definition at line 89 of file Record.h.
Referenced by llvm::ListInit::get(), and llvm::ListRecTy::RecTy::getListTy.
getRecTyKind()
RecTyKind llvm::RecTy::getRecTyKind () const inline
Definition at line 86 of file Record.h.
Referenced by llvm::BitRecTy::classof(), llvm::BitsRecTy::classof(), llvm::DagRecTy::classof(), llvm::IntRecTy::classof(), llvm::ListRecTy::classof(), llvm::RecordRecTy::classof(), and llvm::StringRecTy::classof().
print()
void llvm::RecTy::print (raw_ostream & OS) const inline
Definition at line 92 of file Record.h.
References getAsString().
typeIsA()
bool RecTy::typeIsA (const RecTy * RHS) const virtual
Return true if 'this' type is equal to or a subtype of RHS.
For example, a bit set is not an int, but they are convertible.
Reimplemented in llvm::ListRecTy, and llvm::RecordRecTy.
Definition at line 149 of file Record.cpp.
References RecTy().
Referenced by llvm::UnOpInit::Fold().
typeIsConvertibleTo()
bool RecTy::typeIsConvertibleTo (const RecTy * RHS) const virtual
Return true if all values of 'this' type can be converted to the specified type.
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 144 of file Record.cpp.
References assert(), and RecTy().
Referenced by llvm::BitRecTy::typeIsConvertibleTo(), and llvm::BitsRecTy::typeIsConvertibleTo().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp