LLVM: llvm::orc::JITLinkReentryTrampolines Class Reference
llvm::orc::JITLinkReentryTrampolines Class Reference
Produces trampolines on request using JITLink.
#include "llvm/ExecutionEngine/Orc/JITLinkReentryTrampolines.h"
Classes
class TrampolineAddrScraperPlugin
Public Types
using EmitTrampolineFn
using OnTrampolinesReadyFn
Public Member Functions
LLVM_ABI JITLinkReentryTrampolines (ObjectLinkingLayer &ObjLinkingLayer, EmitTrampolineFn EmitTrampoline)
JITLinkReentryTrampolines (JITLinkReentryTrampolines &&)=delete
JITLinkReentryTrampolines & operator= (JITLinkReentryTrampolines &&)=delete
LLVM_ABI void emit (ResourceTrackerSP RT, size_t NumTrampolines, OnTrampolinesReadyFn OnTrampolinesReady)
Static Public Member Functions
static LLVM_ABI Expected< std::unique_ptr< JITLinkReentryTrampolines > > Create (ObjectLinkingLayer &ObjLinkingLayer)
Create trampolines using the default reentry trampoline function for the session triple.
Detailed Description
Produces trampolines on request using JITLink.
Definition at line 36 of file JITLinkReentryTrampolines.h.
Member Typedef Documentation
EmitTrampolineFn
using llvm::orc::JITLinkReentryTrampolines::EmitTrampolineFn
Initial value:
unique_function<jitlink::Symbol &(
     jitlink::LinkGraph &G, jitlink::Section &Sec,
     jitlink::Symbol &ReentrySym)>
Definition at line 38 of file JITLinkReentryTrampolines.h.
OnTrampolinesReadyFn
using llvm::orc::JITLinkReentryTrampolines::OnTrampolinesReadyFn
Initial value:
unique_function<void(
     Expected<std::vector<ExecutorSymbolDef>> EntryAddrs)>
Definition at line 41 of file JITLinkReentryTrampolines.h.
Constructor & Destructor Documentation
JITLinkReentryTrampolines() [1/2]
llvm::orc::JITLinkReentryTrampolines::JITLinkReentryTrampolines (ObjectLinkingLayer & ObjLinkingLayer, EmitTrampolineFn EmitTrampoline)
Definition at line 108 of file JITLinkReentryTrampolines.cpp.
References llvm::move().
Referenced by JITLinkReentryTrampolines(), and operator=().
JITLinkReentryTrampolines() [2/2]
llvm::orc::JITLinkReentryTrampolines::JITLinkReentryTrampolines (JITLinkReentryTrampolines &&) delete
References JITLinkReentryTrampolines().
Member Function Documentation
Create()
Expected< std::unique_ptr< JITLinkReentryTrampolines > > llvm::orc::JITLinkReentryTrampolines::Create (ObjectLinkingLayer & ObjLinkingLayer) static
Create trampolines using the default reentry trampoline function for the session triple.
Definition at line 86 of file JITLinkReentryTrampolines.cpp.
References llvm::Triple::aarch64, llvm::jitlink::aarch64::createAnonymousReentryTrampoline(), llvm::jitlink::x86_64::createAnonymousReentryTrampoline(), llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::Triple::x86_64.
Referenced by llvm::orc::createJITLinkLazyReexportsManager().
emit()
void llvm::orc::JITLinkReentryTrampolines::emit (ResourceTrackerSP RT, size_t NumTrampolines, OnTrampolinesReadyFn OnTrampolinesReady)
Definition at line 117 of file JITLinkReentryTrampolines.cpp.
References llvm::orc::Exec, G, llvm::IntrusiveRefCntPtr< T >::get(), llvm::jitlink::getGenericEdgeKindName(), I, llvm::orc::MatchAllSymbols, llvm::orc::NoDependenciesToRegister, llvm::orc::Read, llvm::orc::Ready, llvm::orc::Result, llvm::jitlink::SideEffectsOnly, llvm::orc::Static, llvm::jitlink::Strong, and llvm::orc::WeaklyReferencedSymbol.
operator=()
JITLinkReentryTrampolines & llvm::orc::JITLinkReentryTrampolines::operator= (JITLinkReentryTrampolines &&) delete
References JITLinkReentryTrampolines(), and LLVM_ABI.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/JITLinkReentryTrampolines.h
lib/ExecutionEngine/Orc/JITLinkReentryTrampolines.cpp