LLVM: llvm::UniqueMachineInstr Class Reference
llvm::UniqueMachineInstr Class Reference
A class that wraps MachineInstrs and derives from FoldingSetNode in order to be uniqued in a CSEMap.
#include "llvm/CodeGen/GlobalISel/CSEInfo.h"
Public Member Functions
LLVM_ABI void Profile (FoldingSetNodeID &ID)
-----— UniqueMachineInstr ----------—//
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Friends
class GISelCSEInfo
Detailed Description
A class that wraps MachineInstrs and derives from FoldingSetNode in order to be uniqued in a CSEMap.
The tradeoff here is extra memory allocations for UniqueMachineInstr vs making MachineInstr bigger.
Definition at line 31 of file CSEInfo.h.
Member Function Documentation
Profile()
Analysis containing CSE true void UniqueMachineInstr::Profile (FoldingSetNodeID & ID)
-----— UniqueMachineInstr ----------—//
Definition at line 31 of file CSEInfo.cpp.
References llvm::GISelInstProfileBuilder::addNodeID(), and Profile().
Referenced by Profile().
Friends And Related Symbol Documentation
GISelCSEInfo
friend class GISelCSEInfo friend
Definition at line 32 of file CSEInfo.h.
References GISelCSEInfo.
Referenced by GISelCSEInfo.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CSEInfo.h
lib/CodeGen/GlobalISel/CSEInfo.cpp