LLVM: llvm::AMDGPUInstructionSelector Class Reference
llvm::AMDGPUInstructionSelector Class Reference final
#include "Target/AMDGPU/AMDGPUInstructionSelector.h"
Public Member Functions
AMDGPUInstructionSelector (const GCNSubtarget &STI, const AMDGPURegisterBankInfo &RBI, const AMDGPUTargetMachine &TM)
bool select (MachineInstr &I) override
Select the (possibly generic) instruction I to only use target-specific opcodes.
void setupMF (MachineFunction &MF, GISelValueTracking *VT, CodeGenCoverage *CoverageInfo, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) override
Setup per-MF executor state.
Public Member Functions inherited from llvm::InstructionSelector
~InstructionSelector () override
Public Member Functions inherited from llvm::GIMatchTableExecutor
virtual ~GIMatchTableExecutor ()=default
virtual void setupGeneratedPerFunctionState (MachineFunction &MF)=0
Static Public Member Functions
static const char * getName ()
Static Public Member Functions inherited from llvm::GIMatchTableExecutor
static LLVM_ATTRIBUTE_ALWAYS_INLINE uint64_t fastDecodeULEB128 (const uint8_t *LLVM_ATTRIBUTE_RESTRICT MatchTable, uint64_t &CurrentIdx)
Additional Inherited Members
Public Attributes inherited from llvm::InstructionSelector
MachineOptimizationRemarkEmitter * MORE = nullptr
GISelObserverWrapper * AllObservers = nullptr
Note: InstructionSelect does not track changed instructions.
Public Attributes inherited from llvm::GIMatchTableExecutor
CodeGenCoverage * CoverageInfo = nullptr
GISelValueTracking * VT = nullptr
MachineFunction * MF = nullptr
ProfileSummaryInfo * PSI = nullptr
BlockFrequencyInfo * BFI = nullptr
MachineBasicBlock * CurMBB = nullptr
Protected Types inherited from llvm::GIMatchTableExecutor
using ComplexRendererFns
using RecordedMIVector = SmallVector<MachineInstr *, 4>
using NewMIVector = SmallVector<MachineInstrBuilder, 4>
Protected Member Functions inherited from llvm::GIMatchTableExecutor
bool shouldOptForSize (const MachineFunction *MF) const
LLVM_ABI GIMatchTableExecutor ()
template<class TgtExecutor, class PredicateBitset, class ComplexMatcherMemFn, class CustomRendererFn>
bool executeMatchTable (TgtExecutor &Exec, MatcherState &State, const ExecInfoTy< PredicateBitset, ComplexMatcherMemFn, CustomRendererFn > &ExecInfo, MachineIRBuilder &Builder, const uint8_t *MatchTable, const TargetInstrInfo &TII, MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI, const RegisterBankInfo &RBI, const PredicateBitset &AvailableFeatures, CodeGenCoverage *CoverageInfo) const
Execute a given matcher table and return true if the match was successful and false otherwise.
virtual const uint8_t * getMatchTable () const
virtual bool testImmPredicate_I64 (unsigned, int64_t) const
virtual bool testImmPredicate_APInt (unsigned, const APInt &) const
virtual bool testImmPredicate_APFloat (unsigned, const APFloat &) const
virtual bool testMIPredicate_MI (unsigned, const MachineInstr &, const MatcherState &State) const
virtual bool testMOPredicate_MO (unsigned, const MachineOperand &, const MatcherState &State) const
virtual bool testSimplePredicate (unsigned) const
virtual bool runCustomAction (unsigned, const MatcherState &State, NewMIVector &OutMIs) const
LLVM_ABI bool isOperandImmEqual (const MachineOperand &MO, int64_t Value, const MachineRegisterInfo &MRI, bool Splat=false) const
LLVM_ABI bool isBaseWithConstantOffset (const MachineOperand &Root, const MachineRegisterInfo &MRI) const
Return true if the specified operand is a G_PTR_ADD with a G_CONSTANT on the right-hand side.
LLVM_ABI bool isObviouslySafeToFold (MachineInstr &MI, MachineInstr &IntoMI) const
Return true if MI can obviously be folded into IntoMI.
Static Protected Member Functions inherited from llvm::GIMatchTableExecutor
template<typename Ty>
static Ty readBytesAs (const uint8_t *MatchTable)
static ArrayRef< MachineOperand > getRemainingOperands (const MachineInstr &MI, unsigned FirstVarOp)
Detailed Description
Definition at line 48 of file AMDGPUInstructionSelector.h.
Constructor & Destructor Documentation
AMDGPUInstructionSelector()
AMDGPUInstructionSelector::AMDGPUInstructionSelector (const GCNSubtarget & STI, const AMDGPURegisterBankInfo & RBI, const AMDGPUTargetMachine & TM)
Definition at line 43 of file AMDGPUInstructionSelector.cpp.
References GET_GLOBALISEL_PREDICATES_INIT, and GET_GLOBALISEL_TEMPORARIES_INIT.
Member Function Documentation
getName()
const char * llvm::AMDGPUInstructionSelector::getName () static
References llvm::GIMatchTableExecutor::BFI, llvm::GIMatchTableExecutor::CoverageInfo, llvm::GIMatchTableExecutor::MF, llvm::GIMatchTableExecutor::PSI, and llvm::GIMatchTableExecutor::VT.
select()
bool AMDGPUInstructionSelector::select (MachineInstr & I) override virtual
Select the (possibly generic) instruction I to only use target-specific opcodes.
It is OK to insert multiple instructions, but they cannot be generic pre-isel instructions.
Returns
whether selection succeeded.
Precondition
I.getParent() && I.getParent()->getParent()
Postcondition
if returns true: for I in all mutated/inserted instructions: !isPreISelGenericOpcode(I.getOpcode())
Implements llvm::InstructionSelector.
Definition at line 4257 of file AMDGPUInstructionSelector.cpp.
References assert(), llvm::GIMatchTableExecutor::CoverageInfo, llvm::AMDGPU::getImageDimIntrinsicInfo(), llvm::AMDGPU::getIntrinsicID(), I, and llvm::LLT::scalar().
setupMF()
void AMDGPUInstructionSelector::setupMF (MachineFunction & mf, GISelValueTracking * vt, CodeGenCoverage * covinfo, ProfileSummaryInfo * psi, BlockFrequencyInfo * bfi) override virtual
Setup per-MF executor state.
Reimplemented from llvm::GIMatchTableExecutor.
Definition at line 59 of file AMDGPUInstructionSelector.cpp.
References llvm::GIMatchTableExecutor::BFI, llvm::GCNSubtarget::checkSubtargetFeatures(), llvm::GIMatchTableExecutor::CoverageInfo, llvm::GIMatchTableExecutor::MF, llvm::GIMatchTableExecutor::PSI, llvm::GIMatchTableExecutor::setupMF(), and llvm::GIMatchTableExecutor::VT.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUInstructionSelector.h
lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp