LLVM: llvm::object::SFrameParser< E >::FallibleFREIterator Class Reference
llvm::object::SFrameParser< E >::FallibleFREIterator Class Reference
#include "llvm/Object/SFrameParser.h"
Public Member Functions
FallibleFREIterator (ArrayRef< uint8_t > Data, sframe::FREType FREType, uint32_t Idx, uint32_t Size, uint64_t Offset)
LLVM_ABI Error inc ()
const FrameRowEntry & operator* () const
Friends
bool operator== (const FallibleFREIterator &LHS, const FallibleFREIterator &RHS)
Detailed Description
template<endianness E>
class llvm::object::SFrameParser< E >::FallibleFREIterator
Definition at line 85 of file SFrameParser.h.
Constructor & Destructor Documentation
FallibleFREIterator()
template<endianness E> llvm::object::SFrameParser< E >::FallibleFREIterator::FallibleFREIterator (ArrayRef< uint8_t > Data, sframe::FREType FREType, uint32_t Idx, uint32_t Size, uint64_t Offset) inline
Definition at line 89 of file SFrameParser.h.
Referenced by operator==.
Member Function Documentation
inc()
template<endianness E> Error SFrameParser::FallibleFREIterator::inc ()
Definition at line 158 of file SFrameParser.cpp.
References llvm::object::createError(), llvm::formatv(), readFRE(), and llvm::Error::success().
operator*()
template<endianness E> const FrameRowEntry & llvm::object::SFrameParser< E >::FallibleFREIterator::operator* () const inline
Definition at line 94 of file SFrameParser.h.
Friends And Related Symbol Documentation
operator==
template<endianness E> bool operator== (const FallibleFREIterator & LHS, const FallibleFREIterator & RHS) friend
Definition at line 96 of file SFrameParser.h.
References assert(), FallibleFREIterator(), LHS, and RHS.
The documentation for this class was generated from the following files:
include/llvm/Object/SFrameParser.h
lib/Object/SFrameParser.cpp