LLVM: llvm::jitlink::loongarch::GOTTableManager Class Reference
llvm::jitlink::loongarch::GOTTableManager Class Reference
Global Offset Table Builder.
#include "llvm/ExecutionEngine/JITLink/loongarch.h"
Public Member Functions
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< GOTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Detailed Description
Global Offset Table Builder.
Definition at line 461 of file loongarch.h.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::loongarch::GOTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 492 of file loongarch.h.
References llvm::jitlink::loongarch::createAnonymousPointer(), and G.
getSectionName()
StringRef llvm::jitlink::loongarch::GOTTableManager::getSectionName () inline static
Definition at line 463 of file loongarch.h.
visitEdge()
bool llvm::jitlink::loongarch::GOTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 465 of file loongarch.h.
References assert(), B(), llvm::dbgs(), DEBUG_WITH_TYPE, E(), llvm::formatv(), G, llvm::jitlink::TableManager< GOTTableManager >::getEntryForTarget(), llvm::jitlink::loongarch::Page20, llvm::jitlink::loongarch::PageOffset12, llvm::jitlink::loongarch::PCAddHi20, llvm::jitlink::loongarch::RequestGOTAndTransformToPage20, llvm::jitlink::loongarch::RequestGOTAndTransformToPageOffset12, and llvm::jitlink::loongarch::RequestGOTAndTransformToPCAddHi20.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/loongarch.h