LLVM: llvm::LibcallLoweringInfo Class Reference
llvm::LibcallLoweringInfo Class Reference
Tracks which library functions to use for a particular subtarget.
#include "llvm/CodeGen/LibcallLoweringInfo.h"
Public Member Functions
LLVM_ABI LibcallLoweringInfo (const RTLIB::RuntimeLibcallsInfo &RTLCI, const TargetSubtargetInfo &Subtarget)
const RTLIB::RuntimeLibcallsInfo & getRuntimeLibcallsInfo () const
LLVM_ABI const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
LLVM_ABI RTLIB::LibcallImpl getLibcallImpl (RTLIB::Libcall Call) const
Return the lowering's selection of implementation call for Call.
LLVM_ABI void setLibcallImpl (RTLIB::Libcall Call, RTLIB::LibcallImpl Impl)
Rename the default libcall routine name for the specified libcall.
LLVM_ABI CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
LLVM_ABI CallingConv::ID getLibcallImplCallingConv (RTLIB::LibcallImpl Call) const
Get the CallingConv that should be used for the specified libcall.
RTLIB::LibcallImpl getMemcpyImpl () const
Return a function impl compatible with RTLIB::MEMCPY, or RTLIB::Unsupported if fully unsupported.
Detailed Description
Tracks which library functions to use for a particular subtarget.
Definition at line 22 of file LibcallLoweringInfo.h.
Constructor & Destructor Documentation
LibcallLoweringInfo()
LibcallLoweringInfo::LibcallLoweringInfo (const RTLIB::RuntimeLibcallsInfo & RTLCI, const TargetSubtargetInfo & Subtarget)
Definition at line 17 of file LibcallLoweringInfo.cpp.
References llvm::RTLIB::RuntimeLibcallsInfo::getLibcallFromImpl(), llvm::TargetSubtargetInfo::initLibcallLoweringInfo(), and llvm::RTLIB::libcall_impls().
Member Function Documentation
getLibcallCallingConv()
LLVM_ABI CallingConv::ID llvm::LibcallLoweringInfo::getLibcallCallingConv (RTLIB::Libcall Call) const inline
Definition at line 57 of file LibcallLoweringInfo.h.
References LLVM_ABI.
getLibcallImpl()
LLVM_ABI RTLIB::LibcallImpl llvm::LibcallLoweringInfo::getLibcallImpl (RTLIB::Libcall Call) const inline
Return the lowering's selection of implementation call for Call.
Definition at line 46 of file LibcallLoweringInfo.h.
References LLVM_ABI.
Referenced by getMemcpyImpl().
getLibcallImplCallingConv()
LLVM_ABI CallingConv::ID llvm::LibcallLoweringInfo::getLibcallImplCallingConv (RTLIB::LibcallImpl Call) const inline
Get the CallingConv that should be used for the specified libcall.
Definition at line 63 of file LibcallLoweringInfo.h.
getLibcallName()
LLVM_ABI const char * llvm::LibcallLoweringInfo::getLibcallName (RTLIB::Libcall Call) const inline
Get the libcall routine name for the specified libcall.
Definition at line 39 of file LibcallLoweringInfo.h.
References llvm::StringRef::data(), llvm::RTLIB::RuntimeLibcallsInfo::getLibcallImplName(), and LLVM_ABI.
getMemcpyImpl()
RTLIB::LibcallImpl llvm::LibcallLoweringInfo::getMemcpyImpl () const inline
Return a function impl compatible with RTLIB::MEMCPY, or RTLIB::Unsupported if fully unsupported.
Definition at line 69 of file LibcallLoweringInfo.h.
References getLibcallImpl().
getRuntimeLibcallsInfo()
const RTLIB::RuntimeLibcallsInfo & llvm::LibcallLoweringInfo::getRuntimeLibcallsInfo () const inline
Definition at line 33 of file LibcallLoweringInfo.h.
setLibcallImpl()
LLVM_ABI void llvm::LibcallLoweringInfo::setLibcallImpl (RTLIB::Libcall Call, RTLIB::LibcallImpl Impl) inline
Rename the default libcall routine name for the specified libcall.
Definition at line 51 of file LibcallLoweringInfo.h.
References LLVM_ABI.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LibcallLoweringInfo.h
lib/CodeGen/LibcallLoweringInfo.cpp