LLVM: llvm::MachineConstantPoolValue Class Reference
llvm::MachineConstantPoolValue Class Reference abstract
Abstract base class for all machine specific constantpool value subclasses.
#include "llvm/CodeGen/MachineConstantPool.h"
Public Member Functions
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
virtual int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment)=0
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID)=0
virtual void print (raw_ostream &O) const =0
print - Implement operator<<
Detailed Description
Abstract base class for all machine specific constantpool value subclasses.
Definition at line 35 of file MachineConstantPool.h.
Constructor & Destructor Documentation
MachineConstantPoolValue()
llvm::MachineConstantPoolValue::MachineConstantPoolValue (Type * ty) inline explicit
Definition at line 41 of file MachineConstantPool.h.
Referenced by llvm::ARMConstantPoolValue::ARMConstantPoolValue(), llvm::ARMConstantPoolValue::ARMConstantPoolValue(), llvm::CSKYConstantPoolValue::CSKYConstantPoolValue(), llvm::SystemZConstantPoolValue::SystemZConstantPoolValue(), llvm::XtensaConstantPoolValue::XtensaConstantPoolValue(), and llvm::XtensaConstantPoolValue::XtensaConstantPoolValue().
~MachineConstantPoolValue()
virtual llvm::MachineConstantPoolValue::~MachineConstantPoolValue () virtual default
Member Function Documentation
addSelectionDAGCSEId()
virtual void llvm::MachineConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) pure virtual
Implemented in llvm::ARMConstantPoolConstant, llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, llvm::ARMConstantPoolValue, llvm::CSKYConstantPoolConstant, llvm::CSKYConstantPoolJT, llvm::CSKYConstantPoolMBB, llvm::CSKYConstantPoolSymbol, llvm::CSKYConstantPoolValue, llvm::RISCVConstantPoolValue, llvm::SystemZConstantPoolValue, llvm::XtensaConstantPoolConstant, llvm::XtensaConstantPoolJumpTable, llvm::XtensaConstantPoolMBB, llvm::XtensaConstantPoolSymbol, and llvm::XtensaConstantPoolValue.
Referenced by AddNodeIDCustom().
getExistingMachineCPValue()
virtual int llvm::MachineConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) pure virtual
Implemented in llvm::ARMConstantPoolConstant, llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, llvm::ARMConstantPoolValue, llvm::CSKYConstantPoolConstant, llvm::CSKYConstantPoolJT, llvm::CSKYConstantPoolMBB, llvm::CSKYConstantPoolSymbol, llvm::CSKYConstantPoolValue, llvm::RISCVConstantPoolValue, llvm::SystemZConstantPoolValue, llvm::XtensaConstantPoolConstant, llvm::XtensaConstantPoolJumpTable, llvm::XtensaConstantPoolMBB, llvm::XtensaConstantPoolSymbol, and llvm::XtensaConstantPoolValue.
getSizeInBytes()
unsigned MachineConstantPoolValue::getSizeInBytes (const DataLayout & DL) const virtual
Definition at line 1462 of file MachineFunction.cpp.
References DL.
getType()
Type * llvm::MachineConstantPoolValue::getType () const inline
Definition at line 44 of file MachineConstantPool.h.
Referenced by llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), and llvm::SystemZConstantPoolValue::SystemZConstantPoolValue().
print()
virtual void llvm::MachineConstantPoolValue::print (raw_ostream & O) const pure virtual
print - Implement operator<<
Implemented in llvm::ARMConstantPoolConstant, llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, llvm::ARMConstantPoolValue, llvm::CSKYConstantPoolConstant, llvm::CSKYConstantPoolJT, llvm::CSKYConstantPoolMBB, llvm::CSKYConstantPoolSymbol, llvm::CSKYConstantPoolValue, llvm::RISCVConstantPoolValue, llvm::SystemZConstantPoolValue, llvm::XtensaConstantPoolConstant, llvm::XtensaConstantPoolJumpTable, llvm::XtensaConstantPoolMBB, llvm::XtensaConstantPoolSymbol, and llvm::XtensaConstantPoolValue.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineConstantPool.h
lib/CodeGen/MachineFunction.cpp