LLVM: llvm::mca::LatencyInstrument Class Reference
llvm::mca::LatencyInstrument Class Reference
#include "llvm/MCA/CustomBehaviour.h"
Public Member Functions
LatencyInstrument (StringRef Data)
bool hasValue () const
unsigned getLatency () const
Public Member Functions inherited from llvm::mca::Instrument
Instrument (StringRef Desc, StringRef Data)
Instrument ()
virtual ~Instrument ()=default
StringRef getDesc () const
StringRef getData () const
Static Public Attributes
static const StringRef DESC_NAME = "LATENCY"
Detailed Description
Definition at line 136 of file CustomBehaviour.h.
Constructor & Destructor Documentation
LatencyInstrument()
llvm::mca::LatencyInstrument::LatencyInstrument (StringRef Data) inline
Definition at line 141 of file CustomBehaviour.h.
References DESC_NAME, if(), and llvm::mca::Instrument::Instrument().
Member Function Documentation
getLatency()
unsigned llvm::mca::LatencyInstrument::getLatency () const inline
Definition at line 152 of file CustomBehaviour.h.
hasValue()
bool llvm::mca::LatencyInstrument::hasValue () const inline
Definition at line 151 of file CustomBehaviour.h.
Referenced by llvm::mca::InstrumentManager::canCustomize().
Member Data Documentation
DESC_NAME
const llvm::StringRef llvm::mca::LatencyInstrument::DESC_NAME = "LATENCY" static
Definition at line 140 of file CustomBehaviour.h.
Referenced by llvm::mca::InstrumentManager::canCustomize(), llvm::mca::InstrumentManager::createInstrument(), llvm::mca::InstrumentManager::customize(), LatencyInstrument(), and llvm::mca::InstrumentManager::supportsInstrumentType().
The documentation for this class was generated from the following files:
include/llvm/MCA/CustomBehaviour.h
lib/MCA/CustomBehaviour.cpp