LLVM: llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion Class Reference
llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion Class Reference final
Target region entries info.
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
Public Member Functions
OffloadEntryInfoTargetRegion ()
OffloadEntryInfoTargetRegion (unsigned Order, Constant *Addr, Constant *ID, OMPTargetRegionEntryKind Flags)
Constant * getID () const
void setID (Constant *V)
Public Member Functions inherited from llvm::OffloadEntriesInfoManager::OffloadEntryInfo
bool isValid () const
unsigned getOrder () const
OffloadingEntryInfoKinds getKind () const
uint32_t getFlags () const
void setFlags (uint32_t NewFlags)
Constant * getAddress () const
void setAddress (Constant *V)
Static Public Member Functions
static bool classof (const OffloadEntryInfo *Info)
Static Public Member Functions inherited from llvm::OffloadEntriesInfoManager::OffloadEntryInfo
static bool classof (const OffloadEntryInfo *Info)
Additional Inherited Members
Public Types inherited from llvm::OffloadEntriesInfoManager::OffloadEntryInfo
enum OffloadingEntryInfoKinds : unsigned { OffloadingEntryInfoTargetRegion = 0 , OffloadingEntryInfoDeviceGlobalVar = 1 , OffloadingEntryInfoInvalid = ~0u }
Kind of a given entry.
Protected Member Functions inherited from llvm::OffloadEntriesInfoManager::OffloadEntryInfo
OffloadEntryInfo ()=delete
OffloadEntryInfo (OffloadingEntryInfoKinds Kind)
OffloadEntryInfo (OffloadingEntryInfoKinds Kind, unsigned Order, uint32_t Flags)
~OffloadEntryInfo ()=default
Detailed Description
Target region entries info.
Definition at line 331 of file OMPIRBuilder.h.
Constructor & Destructor Documentation
OffloadEntryInfoTargetRegion() [1/2]
llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::OffloadEntryInfoTargetRegion () inline
Definition at line 336 of file OMPIRBuilder.h.
References llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadEntryInfo(), and llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadingEntryInfoTargetRegion.
OffloadEntryInfoTargetRegion() [2/2]
llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::OffloadEntryInfoTargetRegion (unsigned Order, Constant * Addr, Constant * ID, OMPTargetRegionEntryKind Flags) inline explicit
Definition at line 338 of file OMPIRBuilder.h.
References llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadEntryInfo(), llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadingEntryInfoTargetRegion, and llvm::OffloadEntriesInfoManager::OffloadEntryInfo::setAddress().
Member Function Documentation
classof()
bool llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::classof (const OffloadEntryInfo * Info) inline static
Definition at line 351 of file OMPIRBuilder.h.
References Info, llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadEntryInfo(), and llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadingEntryInfoTargetRegion.
getID()
Constant * llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::getID () const inline
Definition at line 346 of file OMPIRBuilder.h.
setID()
void llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::setID (Constant * V) inline
Definition at line 347 of file OMPIRBuilder.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/Frontend/OpenMP/OMPIRBuilder.h