LLVM: llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT > Class Template Reference
llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT > Class Template Reference
SparseSet - Fast set implementation for objects that can be identified by small unsigned keys.
#include "llvm/ADT/SparseSet.h"
Public Types
using value_type = ValueT
using reference = ValueT &
using const_reference = const ValueT &
using pointer = ValueT *
using const_pointer = const ValueT *
using iterator = typename DenseT::iterator
using const_iterator = typename DenseT::const_iterator
Public Member Functions
SparseSet ()=default
SparseSet (const SparseSet &)=delete
SparseSet & operator= (const SparseSet &)=delete
SparseSet (SparseSet &&)=default
void setUniverse (unsigned U)
setUniverse - Set the universe size which determines the largest key the set can hold.
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
bool empty () const
empty - Returns true if the set is empty.
size_type size () const
size - Returns the number of elements in the set.
void clear ()
clear - Clears the set.
iterator findIndex (unsigned Idx)
findIndex - Find an element by its index.
iterator find (const KeyT &Key)
find - Find an element by its key.
const_iterator find (const KeyT &Key) const
bool contains (const KeyT &Key) const
Check if the set contains the given Key.
size_type count (const KeyT &Key) const
count - Returns 1 if this set contains an element identified by Key, 0 otherwise.
std::pair< iterator, bool > insert (const ValueT &Val)
insert - Attempts to insert a new element.
ValueT & operator[] (const KeyT &Key)
array subscript - If an element already exists with this key, return it.
ValueT pop_back_val ()
iterator erase (iterator I)
erase - Erases an existing element identified by a valid iterator.
bool erase (const KeyT &Key)
erase - Erases an element identified by Key, if it exists.
Detailed Description
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t>
class llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >
SparseSet - Fast set implementation for objects that can be identified by small unsigned keys.
SparseSet allocates memory proportional to the size of the key universe, so it is not recommended for building composite data structures. It is useful for algorithms that require a single set with fast operations.
Compared to DenseSet and DenseMap, SparseSet provides constant-time fast clear() and iteration as fast as a vector. The find(), insert(), and erase() operations are all constant time, and typically faster than a hash table. The iteration order doesn't depend on numerical key values, it only depends on the order of insert() and erase() operations. When no elements have been erased, the iteration order is the insertion order.
Compared to BitVector, SparseSet<unsigned> uses 8x-40x more memory, but offers constant-time clear() and size() operations as well as fast iteration independent on the size of the universe.
SparseSet contains a dense vector holding all the objects and a sparse array holding indexes into the dense vector. Most of the memory is used by the sparse array which is the size of the key universe. The SparseT template parameter provides a space/speed tradeoff for sets holding many elements.
When SparseT is uint32_t, find() only touches 2 cache lines, but the sparse array uses 4 x Universe bytes.
When SparseT is uint8_t (the default), find() touches up to 2+[N/256] cache lines, but the sparse array is 4x smaller. N is the number of elements in the set.
For sets that may grow to thousands of elements, SparseT should be set to uint16_t or uint32_t.
Template Parameters
ValueT The type of objects in the set.
KeyT The type of the key, which is passed to the key functor.
KeyFunctorT A functor that computes an unsigned index from KeyT.
SparseT An unsigned integer type. See above.
Definition at line 117 of file SparseSet.h.
Member Typedef Documentation
const_iterator
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> using llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::const_iterator = typename DenseT::const_iterator
Definition at line 168 of file SparseSet.h.
const_pointer
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> using llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::const_pointer = const ValueT *
Definition at line 139 of file SparseSet.h.
const_reference
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> using llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::const_reference = const ValueT &
Definition at line 137 of file SparseSet.h.
iterator
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> using llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::iterator = typename DenseT::iterator
Definition at line 167 of file SparseSet.h.
pointer
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> using llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::pointer = ValueT *
Definition at line 138 of file SparseSet.h.
reference
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> using llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::reference = ValueT &
Definition at line 136 of file SparseSet.h.
value_type
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> using llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::value_type = ValueT
Definition at line 135 of file SparseSet.h.
Constructor & Destructor Documentation
SparseSet() [1/3]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::SparseSet () default
SparseSet() [2/3]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::SparseSet (const SparseSet< ValueT, KeyT, KeyFunctorT, SparseT > &) delete
SparseSet() [3/3]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::SparseSet (SparseSet< ValueT, KeyT, KeyFunctorT, SparseT > &&) default
Member Function Documentation
begin() [1/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::begin () inline nodiscard
Definition at line 172 of file SparseSet.h.
begin() [2/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> const_iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::begin () const inline nodiscard
Definition at line 170 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::erase(), llvm::SparseSet< MCPhysReg, MCPhysReg >::findIndex(), and insertDeleteInstructions().
clear()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> void llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::clear () inline
clear - Clears the set.
This is a very fast constant time operation.
Definition at line 190 of file SparseSet.h.
contains()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> bool llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::contains (const KeyT & Key) const inline nodiscard
Check if the set contains the given Key.
Parameters
Key A valid key to find.
Definition at line 232 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::count().
count()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> size_type llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::count (const KeyT & Key) const inline nodiscard
count - Returns 1 if this set contains an element identified by Key, 0 otherwise.
Definition at line 239 of file SparseSet.h.
Referenced by UpdatePredRedefs().
empty()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> bool llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::empty () const inline nodiscard
empty - Returns true if the set is empty.
This is not the same as BitVector::empty().
Definition at line 179 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::setUniverse().
end() [1/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::end () inline nodiscard
Definition at line 173 of file SparseSet.h.
end() [2/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> const_iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::end () const inline nodiscard
Definition at line 171 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::contains(), llvm::SparseSet< MCPhysReg, MCPhysReg >::erase(), llvm::SparseSet< MCPhysReg, MCPhysReg >::erase(), llvm::SparseSet< MCPhysReg, MCPhysReg >::findIndex(), llvm::SparseSet< MCPhysReg, MCPhysReg >::insert(), insertDeleteInstructions(), updatePhysDepsDownwards(), and updatePhysDepsUpwards().
erase() [1/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> bool llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::erase (const KeyT & Key) inline
erase - Erases an element identified by Key, if it exists.
Parameters
Key The key identifying the element to erase.
Returns
True when an element was erased, false if no element was found.
Definition at line 306 of file SparseSet.h.
erase() [2/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::erase (iterator I) inline
erase - Erases an existing element identified by a valid iterator.
This invalidates all iterators, but erase() returns an iterator pointing to the next element. This makes it possible to erase selected elements while iterating over the set:
for (SparseSet::iterator I = Set.begin(); I != Set.end();) if (test(*I)) I = Set.erase(I); else ++I;
Note that end() changes when elements are erased, unlike std::list.
Definition at line 287 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::erase(), insertDeleteInstructions(), updatePhysDepsDownwards(), and updatePhysDepsUpwards().
find() [1/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::find (const KeyT & Key) inline nodiscard
find - Find an element by its key.
Parameters
Key A valid key to find.
Returns
An iterator to the element identified by key, or end().
Definition at line 221 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::contains(), llvm::SparseSet< MCPhysReg, MCPhysReg >::erase(), updatePhysDepsDownwards(), and updatePhysDepsUpwards().
find() [2/2]
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> const_iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::find (const KeyT & Key) const inline nodiscard
Definition at line 225 of file SparseSet.h.
findIndex()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> iterator llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::findIndex (unsigned Idx) inline
findIndex - Find an element by its index.
Parameters
Idx A valid index to find.
Returns
An iterator to the element identified by key, or end().
Definition at line 200 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::find(), llvm::SparseSet< MCPhysReg, MCPhysReg >::find(), and llvm::SparseSet< MCPhysReg, MCPhysReg >::insert().
insert()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> std::pair< iterator, bool > llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::insert (const ValueT & Val) inline
insert - Attempts to insert a new element.
If Val is successfully inserted, return (I, true), where I is an iterator pointing to the newly inserted element.
If the set already contains an element with the same key as Val, return (I, false), where I is an iterator pointing to the existing element.
Insertion invalidates all iterators.
Definition at line 253 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::operator[](), and UpdatePredRedefs().
operator=()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> SparseSet & llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::operator= (const SparseSet< ValueT, KeyT, KeyFunctorT, SparseT > &) delete
operator[]()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> ValueT & llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::operator[] (const KeyT & Key) inline
array subscript - If an element already exists with this key, return it.
Otherwise, automatically construct a new value from Key, insert it, and return the newly inserted element.
Definition at line 266 of file SparseSet.h.
pop_back_val()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> ValueT llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::pop_back_val () inline
Definition at line 268 of file SparseSet.h.
setUniverse()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> void llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::setUniverse (unsigned U) inline
setUniverse - Set the universe size which determines the largest key the set can hold.
The universe must be sized before any elements can be added.
Parameters
U Universe size. All object keys must be less than U.
Definition at line 152 of file SparseSet.h.
Referenced by UpdatePredRedefs().
size()
template<typename ValueT, typename KeyT = unsigned, typename KeyFunctorT = identity, typename SparseT = uint8_t> size_type llvm::SparseSet< ValueT, KeyT, KeyFunctorT, SparseT >::size () const inline nodiscard
size - Returns the number of elements in the set.
This is not the same as BitVector::size() which returns the size of the universe.
Definition at line 186 of file SparseSet.h.
Referenced by llvm::SparseSet< MCPhysReg, MCPhysReg >::erase(), llvm::SparseSet< MCPhysReg, MCPhysReg >::findIndex(), and llvm::SparseSet< MCPhysReg, MCPhysReg >::insert().
The documentation for this class was generated from the following file:
include/llvm/ADT/SparseSet.h