LLVM: llvm::VPTypeAnalysis Class Reference
llvm::VPTypeAnalysis Class Reference
An analysis for type-inference for VPValues.
#include "Transforms/Vectorize/VPlanAnalysis.h"
Public Member Functions
VPTypeAnalysis (const VPlan &Plan)
Type * inferScalarType (const VPValue *V)
Infer the type of V. Returns the scalar type of V.
LLVMContext & getContext ()
Return the LLVMContext used by the analysis.
Detailed Description
An analysis for type-inference for VPValues.
It infers the scalar type for a given VPValue by bottom-up traversing through defining recipes until root nodes with known types are reached (e.g. live-ins or load recipes). The types are then propagated top down through operations. Note that the analysis caches the inferred types. A new analysis object must be constructed once a VPlan has been modified in a way that invalidates any of the previously inferred types.
Definition at line 42 of file VPlanAnalysis.h.
Constructor & Destructor Documentation
VPTypeAnalysis()
VPTypeAnalysis::VPTypeAnalysis (const VPlan & Plan)
Definition at line 27 of file VPlanAnalysis.cpp.
References getContext(), and llvm::VPlan::getVectorLoopRegion().
Member Function Documentation
getContext()
LLVMContext & llvm::VPTypeAnalysis::getContext () inline
Return the LLVMContext used by the analysis.
Definition at line 65 of file VPlanAnalysis.h.
Referenced by tryToFoldLiveIns(), and VPTypeAnalysis().
inferScalarType()
Type * VPTypeAnalysis::inferScalarType (const VPValue * V)
Infer the type of V. Returns the scalar type of V.
Definition at line 255 of file VPlanAnalysis.cpp.
References assert(), llvm::TypeSwitch< T, ResultT >::Case(), llvm::dyn_cast(), inferScalarType(), and llvm::isa().
Referenced by llvm::calculateRegisterUsageForPlan(), llvm::VPlanTransforms::canonicalizeEVLLoops(), collectComplementaryPredicatedMemOps(), llvm::VPlanTransforms::convertToConcreteRecipes(), llvm::VPlanTransforms::createInLoopReductionRecipes(), createScalarIVSteps(), expandVPWidenIntOrFpInduction(), expandVPWidenPointerInduction(), llvm::vputils::getSCEVExprForVPValue(), inferScalarType(), isConsecutiveInterleaveGroup(), llvm::VPlanTransforms::materializeBackedgeTakenCount(), llvm::VPlanTransforms::materializePacksAndUnpacks(), llvm::VPlanTransforms::materializeVectorTripCount(), llvm::VPlanTransforms::materializeVFAndVFxUF(), optimizeEarlyExitInductionUser(), optimizeLatchExitInductionUser(), optimizeMaskToEVL(), simplifyRecipe(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), tryToComputeEndValueForInduction(), tryToFoldLiveIns(), and willGenerateVectors().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanAnalysis.h
lib/Transforms/Vectorize/VPlanAnalysis.cpp