LLVM: llvm::sandboxir::ConstantStruct Class Reference
llvm::sandboxir::ConstantStruct Class Reference final
#include "llvm/SandboxIR/Constant.h"
Public Member Functions
StructType * getType () const
Specialization - reduce amount of casting.
Public Member Functions inherited from llvm::sandboxir::Constant
sandboxir::Context & getParent () const
unsigned getUseOperandNo (const Use &Use) const override
\Returns the operand index of Use.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static LLVM_ABI Constant * get (StructType *T, ArrayRef< Constant * > V)
template<typename... Csts>
static std::enable_if_t< are_base_of< Constant, Csts... >::value, Constant * > get (StructType *T, Csts *...Vs)
static Constant * getAnon (ArrayRef< Constant * > V, bool Packed=false)
Return an anonymous struct that has the specified elements.
static Constant * getAnon (Context &Ctx, ArrayRef< Constant * > V, bool Packed=false)
static LLVM_ABI StructType * getTypeForElements (Context &Ctx, ArrayRef< Constant * > V, bool Packed=false)
This version of the method allows an empty list.
static StructType * getTypeForElements (ArrayRef< Constant * > V, bool Packed=false)
Return an anonymous struct type to use for a constant with the specified set of elements.
static bool classof (const Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::ConstantAggregate
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::Constant
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Friends
class Context
Additional Inherited Members
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Protected Member Functions inherited from llvm::sandboxir::ConstantAggregate
ConstantAggregate (ClassID ID, llvm::Constant *C, Context &Ctx)
Protected Member Functions inherited from llvm::sandboxir::Constant
Constant (llvm::Constant *C, sandboxir::Context &SBCtx)
Constant (ClassID ID, llvm::Constant *C, sandboxir::Context &SBCtx)
Use getOperandUseInternal (unsigned OpIdx, bool Verify) const override
\Returns the Use for the OpIdx'th operand.
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 378 of file Constant.h.
Member Function Documentation
classof()
bool llvm::sandboxir::ConstantStruct::classof (const Value * From) inline static
For isa/dyn_cast.
Definition at line 418 of file Constant.h.
References llvm::sandboxir::Value::getSubclassID().
get() [1/2]
Constant * llvm::sandboxir::ConstantStruct::get (StructType * T, ArrayRef< Constant * > V) static
Definition at line 154 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, llvm::ConstantStruct::get(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and T.
get() [2/2]
template<typename... Csts> std::enable_if_t< are_base_of< Constant, Csts... >::value, Constant * > llvm::sandboxir::ConstantStruct::get (StructType * T, Csts *... Vs) inline static
Definition at line 388 of file Constant.h.
References llvm::sandboxir::get(), and T.
getAnon() [1/2]
Constant * llvm::sandboxir::ConstantStruct::getAnon (ArrayRef< Constant * > V, bool Packed = false) inline static
Return an anonymous struct that has the specified elements.
If the struct is possibly empty, then you must specify a context.
Definition at line 393 of file Constant.h.
References llvm::sandboxir::get(), and getTypeForElements().
getAnon() [2/2]
Constant * llvm::sandboxir::ConstantStruct::getAnon (Context & Ctx, ArrayRef< Constant * > V, bool Packed = false) inline static
Definition at line 396 of file Constant.h.
References Context, llvm::sandboxir::Value::Ctx, llvm::sandboxir::get(), and getTypeForElements().
getType()
StructType * llvm::sandboxir::ConstantStruct::getType () const inline
Specialization - reduce amount of casting.
Definition at line 413 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::getType().
getTypeForElements() [1/2]
StructType * llvm::sandboxir::ConstantStruct::getTypeForElements (ArrayRef< Constant * > V, bool Packed = false) inline static
Return an anonymous struct type to use for a constant with the specified set of elements.
The list must not be empty.
Definition at line 405 of file Constant.h.
References assert(), llvm::sandboxir::Value::getContext(), and getTypeForElements().
getTypeForElements() [2/2]
StructType * llvm::sandboxir::ConstantStruct::getTypeForElements (Context & Ctx, ArrayRef< Constant * > V, bool Packed = false) static
This version of the method allows an empty list.
Definition at line 165 of file Constant.cpp.
References Context, llvm::sandboxir::Value::Ctx, llvm::sandboxir::StructType::get(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
Referenced by getAnon(), getAnon(), and getTypeForElements().
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 381 of file Constant.h.
References Context, LLVM_ABI, and T.
Referenced by Context, getAnon(), and getTypeForElements().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Constant.h
lib/SandboxIR/Constant.cpp