LLVM: llvm::abi::IntegerType Class Reference
llvm::abi::IntegerType Class Reference
#include "llvm/ABI/Types.h"
Public Member Functions
IntegerType (uint64_t BitWidth, Align ABIAlign, bool IsSigned, bool IsBitInt=false)
bool isSigned () const
bool isBitInt () const
bool isBool () const
Public Member Functions inherited from llvm::abi::Type
TypeKind getKind () const
TypeSize getSizeInBits () const
Align getAlignment () const
TypeSize getTypeAllocSize () const
bool isVoid () const
bool isInteger () const
bool isFloat () const
bool isPointer () const
bool isArray () const
bool isVector () const
bool isRecord () const
bool isMemberPointer () const
bool isComplex () const
Static Public Member Functions
static bool classof (const Type *T)
Additional Inherited Members
Protected Member Functions inherited from llvm::abi::Type
Type (TypeKind K, TypeSize SizeInBits, Align ABIAlign)
Protected Attributes inherited from llvm::abi::Type
TypeKind Kind
TypeSize SizeInBits
Align ABIAlignment
Detailed Description
Definition at line 110 of file Types.h.
Constructor & Destructor Documentation
IntegerType()
llvm::abi::IntegerType::IntegerType (uint64_t BitWidth, Align ABIAlign, bool IsSigned, bool IsBitInt = false) inline
Definition at line 116 of file Types.h.
References llvm::BitWidth, and llvm::abi::Type::Type().
Member Function Documentation
classof()
bool llvm::abi::IntegerType::classof (const Type * T) inline static
Definition at line 127 of file Types.h.
References llvm::abi::Integer, T, and llvm::abi::Type::Type().
isBitInt()
bool llvm::abi::IntegerType::isBitInt () const inline
Definition at line 122 of file Types.h.
isBool()
bool llvm::abi::IntegerType::isBool () const inline
Definition at line 123 of file Types.h.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), and llvm::abi::Type::getSizeInBits().
isSigned()
bool llvm::abi::IntegerType::isSigned () const inline
Definition at line 121 of file Types.h.
The documentation for this class was generated from the following file:
include/llvm/ABI/Types.h