LLVM: llvm::jitlink::loongarch::PLTTableManager Class Reference
llvm::jitlink::loongarch::PLTTableManager Class Reference
Procedure Linkage Table Builder.
#include "llvm/ExecutionEngine/JITLink/loongarch.h"
Public Member Functions
PLTTableManager (GOTTableManager &GOT)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Section & getStubsSection (LinkGraph &G)
Public Member Functions inherited from llvm::jitlink::TableManager< PLTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Public Attributes
GOTTableManager & GOT
Section * StubsSection = nullptr
Detailed Description
Procedure Linkage Table Builder.
Definition at line 508 of file loongarch.h.
Constructor & Destructor Documentation
PLTTableManager()
llvm::jitlink::loongarch::PLTTableManager::PLTTableManager (GOTTableManager & GOT) inline
Definition at line 510 of file loongarch.h.
References GOT.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::loongarch::PLTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 529 of file loongarch.h.
References llvm::jitlink::loongarch::createAnonymousPointerJumpStub(), G, getStubsSection(), and GOT.
getSectionName()
StringRef llvm::jitlink::loongarch::PLTTableManager::getSectionName () inline static
Definition at line 512 of file loongarch.h.
Referenced by getStubsSection().
getStubsSection()
Section & llvm::jitlink::loongarch::PLTTableManager::getStubsSection (LinkGraph & G) inline
Definition at line 535 of file loongarch.h.
References llvm::orc::Exec, G, getSectionName(), llvm::orc::Read, and StubsSection.
Referenced by createEntry().
visitEdge()
bool llvm::jitlink::loongarch::PLTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 514 of file loongarch.h.
References B(), llvm::jitlink::loongarch::Branch26PCRel, llvm::jitlink::loongarch::Call30PCRel, llvm::jitlink::loongarch::Call36PCRel, llvm::dbgs(), DEBUG_WITH_TYPE, E(), llvm::formatv(), G, and llvm::jitlink::TableManager< PLTTableManager >::getEntryForTarget().
Member Data Documentation
GOT
GOTTableManager& llvm::jitlink::loongarch::PLTTableManager::GOT
Definition at line 542 of file loongarch.h.
Referenced by createEntry(), and PLTTableManager().
StubsSection
Section* llvm::jitlink::loongarch::PLTTableManager::StubsSection = nullptr
Definition at line 543 of file loongarch.h.
Referenced by getStubsSection().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/loongarch.h