LLVM: llvm::IndexedInstrProfReader Class Reference
llvm::IndexedInstrProfReader Class Reference
Reader for the indexed binary instrprof format.
#include "llvm/ProfileData/InstrProfReader.h"
Public Member Functions
IndexedInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer, std::unique_ptr< MemoryBuffer > RemappingBuffer=nullptr)
IndexedInstrProfReader (const IndexedInstrProfReader &)=delete
IndexedInstrProfReader & operator= (const IndexedInstrProfReader &)=delete
uint64_t getVersion () const override
Return the profile version.
bool isIRLevelProfile () const override
bool hasCSIRLevelProfile () const override
bool instrEntryBBEnabled () const override
bool instrLoopEntriesEnabled () const override
Return true if the profile instruments all loop entries.
bool hasSingleByteCoverage () const override
Return true if the profile has single byte counters representing coverage.
bool functionEntryOnly () const override
Return true if the profile only instruments function entries.
bool hasMemoryProfile () const override
Return true if profile includes a memory profile.
bool hasTemporalProfile () const override
Return true if this has a temporal profile.
InstrProfKind getProfileKind () const override
Returns a BitsetEnum describing the attributes of the indexed instr profile.
Error readHeader () override
Read the file header.
Error readNextRecord (NamedInstrProfRecord &Record) override
Read a single record.
Expected< NamedInstrProfRecord > getInstrProfRecord (StringRef FuncName, uint64_t FuncHash, StringRef DeprecatedFuncName="", uint64_t *MismatchedFuncSum=nullptr)
Return the NamedInstrProfRecord associated with FuncName and FuncHash.
Expected< memprof::MemProfRecord > getMemProfRecord (uint64_t FuncNameHash)
Return the memprof record for the function identified by llvm::md5(Name).
DenseMap< uint64_t, SmallVector< memprof::CallEdgeTy, 0 > > getMemProfCallerCalleePairs ()
memprof::AllMemProfData getAllMemProfData () const
Error getFunctionCounts (StringRef FuncName, uint64_t FuncHash, std::vector< uint64_t > &Counts)
Fill Counts with the profile data for the given function name.
Error getFunctionBitmap (StringRef FuncName, uint64_t FuncHash, BitVector &Bitmap)
Fill Bitmap with the profile data for the given function name.
uint64_t getMaximumFunctionCount (bool UseCS)
Return the maximum of all known function counts.
void setValueProfDataEndianness (llvm::endianness Endianness)
InstrProfSymtab & getSymtab () override
Return the PGO symtab.
ProfileSummary & getSummary (bool UseCS)
Return the profile summary.
memprof::MemProfSummary * getMemProfSummary () const
Return the MemProf summary. Will be null if unavailable (version < 4).
memprof::DataAccessProfData * getDataAccessProfileData () const
Returns non-owned pointer to the data access profile data.
Error readBinaryIds (std::vector< llvm::object::BuildID > &BinaryIds) override
Read a list of binary ids.
Error printBinaryIds (raw_ostream &OS) override
Print binary ids.
Public Member Functions inherited from llvm::InstrProfReader
InstrProfReader ()=default
virtual ~InstrProfReader ()=default
InstrProfIterator begin ()
Iterator over profile data.
InstrProfIterator end ()
LLVM_ABI void accumulateCounts (CountSumOrPercent &Sum, bool IsCS)
Compute the sum of counts and return in Sum.
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
Error getError ()
Get the current error.
virtual SmallVector< TemporalProfTraceTy > & getTemporalProfTraces (std::optional< uint64_t > Weight={})
uint64_t getTemporalProfTraceStreamSize ()
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &DataBuffer)
Return true if the given buffer is in an indexed instrprof format.
static Expected< std::unique_ptr< IndexedInstrProfReader > > create (const Twine &Path, vfs::FileSystem &FS, const Twine &RemappingPath="")
Factory method to create an indexed reader.
static Expected< std::unique_ptr< IndexedInstrProfReader > > create (std::unique_ptr< MemoryBuffer > Buffer, std::unique_ptr< MemoryBuffer > RemappingBuffer=nullptr)
Static Public Member Functions inherited from llvm::InstrProfReader
static LLVM_ABI Expected< std::unique_ptr< InstrProfReader > > create (const Twine &Path, vfs::FileSystem &FS, const InstrProfCorrelator *Correlator=nullptr, const object::BuildIDFetcher *BIDFetcher=nullptr, const InstrProfCorrelator::ProfCorrelatorKind BIDFetcherCorrelatorKind=InstrProfCorrelator::ProfCorrelatorKind::NONE, std::function< void(Error)> Warn=nullptr)
Factory method to create an appropriately typed reader for the given instrprof file.
static LLVM_ABI Expected< std::unique_ptr< InstrProfReader > > create (std::unique_ptr< MemoryBuffer > Buffer, const InstrProfCorrelator *Correlator=nullptr, const object::BuildIDFetcher *BIDFetcher=nullptr, const InstrProfCorrelator::ProfCorrelatorKind BIDFetcherCorrelatorKind=InstrProfCorrelator::ProfCorrelatorKind::NONE, std::function< void(Error)> Warn=nullptr)
Additional Inherited Members
Protected Member Functions inherited from llvm::InstrProfReader
Error error (instrprof_error Err, const std::string &ErrMsg="")
Set the current error and return same.
Error error (Error &&E)
Error success ()
Clear the current error and return a successful one.
Protected Attributes inherited from llvm::InstrProfReader
std::unique_ptr< InstrProfSymtab > Symtab
SmallVector< TemporalProfTraceTy > TemporalProfTraces
A list of temporal profile traces.
uint64_t TemporalProfTraceStreamSize = 0
The total number of temporal profile traces seen.
Detailed Description
Reader for the indexed binary instrprof format.
Definition at line 744 of file InstrProfReader.h.
Constructor & Destructor Documentation
IndexedInstrProfReader() [1/2]
llvm::IndexedInstrProfReader::IndexedInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer, std::unique_ptr< MemoryBuffer > RemappingBuffer = nullptr) inline
Definition at line 776 of file InstrProfReader.h.
References llvm::move().
Referenced by IndexedInstrProfReader(), and operator=().
IndexedInstrProfReader() [2/2]
llvm::IndexedInstrProfReader::IndexedInstrProfReader (const IndexedInstrProfReader &) delete
References IndexedInstrProfReader().
Member Function Documentation
create() [1/2]
Expected< std::unique_ptr< IndexedInstrProfReader > > IndexedInstrProfReader::create (const Twine & Path, vfs::FileSystem & FS, const Twine & RemappingPath = "") static
Factory method to create an indexed reader.
Definition at line 203 of file InstrProfReader.cpp.
References create(), llvm::setupMemoryBuffer(), and llvm::Twine::str().
Referenced by annotateAllFunctions(), create(), llvm::coverage::CoverageMapping::load(), and llvm::MemProfUsePass::run().
create() [2/2]
Expected< std::unique_ptr< IndexedInstrProfReader > > IndexedInstrProfReader::create (std::unique_ptr< MemoryBuffer > Buffer, std::unique_ptr< MemoryBuffer > RemappingBuffer = nullptr) static
Definition at line 225 of file InstrProfReader.cpp.
References llvm::bad_magic, hasFormat(), initializeReader(), and llvm::make_error().
functionEntryOnly()
bool llvm::IndexedInstrProfReader::functionEntryOnly () const inline override virtual
Return true if the profile only instruments function entries.
Implements llvm::InstrProfReader.
Definition at line 803 of file InstrProfReader.h.
getAllMemProfData()
memprof::AllMemProfData llvm::IndexedInstrProfReader::getAllMemProfData () const inline
Definition at line 848 of file InstrProfReader.h.
getDataAccessProfileData()
memprof::DataAccessProfData * llvm::IndexedInstrProfReader::getDataAccessProfileData () const inline
Returns non-owned pointer to the data access profile data.
Will be null if unavailable (version < 4).
Definition at line 910 of file InstrProfReader.h.
getFunctionBitmap()
Error IndexedInstrProfReader::getFunctionBitmap (StringRef FuncName, uint64_t FuncHash, BitVector & Bitmap)
Fill Bitmap with the profile data for the given function name.
Definition at line 1602 of file InstrProfReader.cpp.
References llvm::BitVector::apply(), assert(), error, llvm::FuncHash, getInstrProfRecord(), I, llvm::little, N, llvm::support::endian::read(), llvm::BitVector::resize(), llvm::InstrProfReader::success(), and X.
getFunctionCounts()
Error IndexedInstrProfReader::getFunctionCounts (StringRef FuncName, uint64_t FuncHash, std::vector< uint64_t > & Counts)
Fill Counts with the profile data for the given function name.
Definition at line 1591 of file InstrProfReader.cpp.
References error, llvm::FuncHash, getInstrProfRecord(), and llvm::InstrProfReader::success().
getInstrProfRecord()
Expected< NamedInstrProfRecord > IndexedInstrProfReader::getInstrProfRecord (StringRef FuncName, uint64_t FuncHash, StringRef DeprecatedFuncName = "", uint64_t * MismatchedFuncSum = nullptr)
Return the NamedInstrProfRecord associated with FuncName and FuncHash.
When return a hash_mismatch error and MismatchedFuncSum is not nullptr, the sum of all counters in the mismatched function will be set to MismatchedFuncSum. If there are multiple instances of mismatched functions, MismatchedFuncSum returns the maximum. If FuncName is not found, try to lookup DeprecatedFuncName to handle profiles built by older compilers.
Definition at line 1372 of file InstrProfReader.cpp.
References llvm::Data, error, llvm::FuncHash, llvm::handleErrors(), llvm::NamedInstrProfRecord::hasCSFlagInHash(), llvm::hash_mismatch, I, llvm::make_error(), llvm::Error::success(), and llvm::unknown_function.
Referenced by getFunctionBitmap(), and getFunctionCounts().
getMaximumFunctionCount()
uint64_t llvm::IndexedInstrProfReader::getMaximumFunctionCount (bool UseCS) inline
Return the maximum of all known function counts.
UseCS indicates whether to use the context-sensitive count.
Definition at line 862 of file InstrProfReader.h.
References assert().
getMemProfCallerCalleePairs()
DenseMap< uint64_t, SmallVector< memprof::CallEdgeTy, 0 > > llvm::IndexedInstrProfReader::getMemProfCallerCalleePairs () inline
Definition at line 844 of file InstrProfReader.h.
getMemProfRecord()
Expected< memprof::MemProfRecord > llvm::IndexedInstrProfReader::getMemProfRecord (uint64_t FuncNameHash) inline
Return the memprof record for the function identified by llvm::md5(Name).
Definition at line 839 of file InstrProfReader.h.
getMemProfSummary()
memprof::MemProfSummary * llvm::IndexedInstrProfReader::getMemProfSummary () const inline
Return the MemProf summary. Will be null if unavailable (version < 4).
Definition at line 904 of file InstrProfReader.h.
getProfileKind()
InstrProfKind llvm::IndexedInstrProfReader::getProfileKind () const inline override virtual
Returns a BitsetEnum describing the attributes of the indexed instr profile.
Implements llvm::InstrProfReader.
Definition at line 813 of file InstrProfReader.h.
getSummary()
ProfileSummary & llvm::IndexedInstrProfReader::getSummary (bool UseCS) inline
Return the profile summary.
UseCS indicates whether to use the context-sensitive summary.
Definition at line 893 of file InstrProfReader.h.
References assert().
getSymtab()
InstrProfSymtab & IndexedInstrProfReader::getSymtab () override virtual
Return the PGO symtab.
There are three different readers: Raw, Text, and Indexed profile readers. The first two types of readers are used only by llvm-profdata tool, while the indexed profile reader is also used by llvm-cov tool and the compiler (backend or frontend). Since creating PGO symtab can create significant runtime and memory overhead (as it touches data for the whole program), InstrProfSymtab for the indexed profile reader should be created on demand and it is recommended to be only used for dumping purpose with llvm-proftool, not with the compiler.
Implements llvm::InstrProfReader.
Definition at line 1351 of file InstrProfReader.cpp.
References llvm::consumeError(), error, llvm::InstrProfReader::Symtab, and llvm::InstrProfError::take().
getVersion()
uint64_t llvm::IndexedInstrProfReader::getVersion () const inline override virtual
Return the profile version.
Implements llvm::InstrProfReader.
Definition at line 785 of file InstrProfReader.h.
hasCSIRLevelProfile()
bool llvm::IndexedInstrProfReader::hasCSIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 787 of file InstrProfReader.h.
hasFormat()
bool IndexedInstrProfReader::hasFormat (const MemoryBuffer & DataBuffer) static
Return true if the given buffer is in an indexed instrprof format.
Definition at line 1169 of file InstrProfReader.cpp.
References llvm::little, llvm::IndexedInstrProf::Magic, and llvm::support::endian::read().
Referenced by create(), and llvm::InstrProfReader::create().
hasMemoryProfile()
bool llvm::IndexedInstrProfReader::hasMemoryProfile () const inline override virtual
Return true if profile includes a memory profile.
Implements llvm::InstrProfReader.
Definition at line 805 of file InstrProfReader.h.
hasSingleByteCoverage()
bool llvm::IndexedInstrProfReader::hasSingleByteCoverage () const inline override virtual
Return true if the profile has single byte counters representing coverage.
Implements llvm::InstrProfReader.
Definition at line 799 of file InstrProfReader.h.
hasTemporalProfile()
bool llvm::IndexedInstrProfReader::hasTemporalProfile () const inline override virtual
Return true if this has a temporal profile.
Implements llvm::InstrProfReader.
Definition at line 807 of file InstrProfReader.h.
instrEntryBBEnabled()
bool llvm::IndexedInstrProfReader::instrEntryBBEnabled () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 791 of file InstrProfReader.h.
instrLoopEntriesEnabled()
bool llvm::IndexedInstrProfReader::instrLoopEntriesEnabled () const inline override virtual
Return true if the profile instruments all loop entries.
Implements llvm::InstrProfReader.
Definition at line 795 of file InstrProfReader.h.
isIRLevelProfile()
bool llvm::IndexedInstrProfReader::isIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 786 of file InstrProfReader.h.
operator=()
IndexedInstrProfReader & llvm::IndexedInstrProfReader::operator= (const IndexedInstrProfReader &) delete
References IndexedInstrProfReader().
printBinaryIds()
Error IndexedInstrProfReader::printBinaryIds (raw_ostream & OS) override virtual
Print binary ids.
Reimplemented from llvm::InstrProfReader.
Definition at line 1650 of file InstrProfReader.cpp.
References printBinaryIdsInternal(), readBinaryIds(), and llvm::Error::success().
readBinaryIds()
Error IndexedInstrProfReader::readBinaryIds (std::vector< llvm::object::BuildID > & BinaryIds) override virtual
Read a list of binary ids.
Reimplemented from llvm::InstrProfReader.
Definition at line 1644 of file InstrProfReader.cpp.
References llvm::little, and readBinaryIdsInternal().
Referenced by printBinaryIds().
readHeader()
Error IndexedInstrProfReader::readHeader () override virtual
Read the file header.
Implements llvm::InstrProfReader.
Definition at line 1234 of file InstrProfReader.cpp.
References llvm::bad_header, error, llvm::IndexedInstrProf::Last, llvm::make_error(), llvm::malformed, llvm::IndexedInstrProf::Header::readFromBuffer(), llvm::support::endian::readNext(), llvm::IndexedInstrProf::Header::size(), llvm::InstrProfReader::success(), llvm::InstrProfReader::TemporalProfTraces, llvm::InstrProfReader::TemporalProfTraceStreamSize, llvm::truncated, llvm::unsupported_hash_type, VARIANT_MASK_CSIR_PROF, VARIANT_MASK_MEMPROF, and VARIANT_MASK_TEMPORAL_PROF.
readNextRecord()
Error IndexedInstrProfReader::readNextRecord (NamedInstrProfRecord & Record) override virtual
Read a single record.
Implements llvm::InstrProfReader.
Definition at line 1629 of file InstrProfReader.cpp.
References llvm::Data, error, and llvm::InstrProfReader::success().
setValueProfDataEndianness()
void llvm::IndexedInstrProfReader::setValueProfDataEndianness (llvm::endianness Endianness) inline
Definition at line 882 of file InstrProfReader.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp