LLVM: llvm::jitlink::SectionRange Class Reference
llvm::jitlink::SectionRange Class Reference
Represents a section address range via a pair of Block pointers to the first and last Blocks in the section.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Member Functions
SectionRange ()=default
SectionRange (const Section &Sec)
Block * getFirstBlock () const
Block * getLastBlock () const
bool empty () const
orc::ExecutorAddr getStart () const
orc::ExecutorAddr getEnd () const
orc::ExecutorAddrDiff getSize () const
orc::ExecutorAddrRange getRange () const
Detailed Description
Represents a section address range via a pair of Block pointers to the first and last Blocks in the section.
Definition at line 836 of file JITLink.h.
Constructor & Destructor Documentation
SectionRange() [1/2]
llvm::jitlink::SectionRange::SectionRange () default
SectionRange() [2/2]
llvm::jitlink::SectionRange::SectionRange (const Section & Sec) inline
Definition at line 839 of file JITLink.h.
References B(), llvm::iterator_range< IteratorT >::begin(), llvm::jitlink::Section::blocks(), and llvm::iterator_range< IteratorT >::empty().
Member Function Documentation
empty()
bool llvm::jitlink::SectionRange::empty () const inline
Definition at line 858 of file JITLink.h.
References assert().
getEnd()
orc::ExecutorAddr llvm::jitlink::SectionRange::getEnd () const inline
Definition at line 865 of file JITLink.h.
Referenced by getRange(), and getSize().
getFirstBlock()
Block * llvm::jitlink::SectionRange::getFirstBlock () const inline
Definition at line 850 of file JITLink.h.
References assert().
getLastBlock()
Block * llvm::jitlink::SectionRange::getLastBlock () const inline
Definition at line 854 of file JITLink.h.
References assert().
getRange()
orc::ExecutorAddrRange llvm::jitlink::SectionRange::getRange () const inline
Definition at line 870 of file JITLink.h.
References getEnd(), and getStart().
Referenced by llvm::orc::EHFrameRegistrationPlugin::modifyPassConfig().
getSize()
orc::ExecutorAddrDiff llvm::jitlink::SectionRange::getSize () const inline
Definition at line 868 of file JITLink.h.
References getEnd(), and getStart().
getStart()
orc::ExecutorAddr llvm::jitlink::SectionRange::getStart () const inline
Definition at line 862 of file JITLink.h.
Referenced by getRange(), getSize(), and llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h