LLVM: llvm::xray::BlockVerifier Class Reference
llvm::xray::BlockVerifier Class Reference
#include "llvm/XRay/BlockVerifier.h"
Public Types
enum class State : std::size_t {
Unknown , BufferExtents , NewBuffer , WallClockTime ,
PIDEntry , NewCPUId , TSCWrap , CustomEvent ,
TypedEvent , Function , CallArg , EndOfBuffer ,
StateMax
}
Public Member Functions
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Error verify ()
void reset ()
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
Definition at line 21 of file BlockVerifier.h.
Member Enumeration Documentation
State
enum class llvm::xray::BlockVerifier::State : std::size_t strong
Enumerator
Unknown
BufferExtents
NewBuffer
WallClockTime
PIDEntry
NewCPUId
TSCWrap
CustomEvent
TypedEvent
Function
CallArg
EndOfBuffer
StateMax
Definition at line 24 of file BlockVerifier.h.
Member Function Documentation
reset()
void BlockVerifier::reset ()
Definition at line 204 of file BlockVerifier.cpp.
References Unknown.
verify()
Error BlockVerifier::verify ()
Definition at line 185 of file BlockVerifier.cpp.
References CallArg, llvm::createStringError(), CustomEvent, data, EndOfBuffer, Function, NewCPUId, recordToString(), llvm::Error::success(), TSCWrap, and TypedEvent.
visit() [1/12]
Error BlockVerifier::visit (BufferExtents &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 139 of file BlockVerifier.cpp.
References BufferExtents.
visit() [2/12]
Error BlockVerifier::visit (CallArgRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 167 of file BlockVerifier.cpp.
References CallArg.
visit() [3/12]
Error BlockVerifier::visit (CustomEventRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 155 of file BlockVerifier.cpp.
References CustomEvent.
visit() [4/12]
Error BlockVerifier::visit (CustomEventRecordV5 &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 159 of file BlockVerifier.cpp.
References CustomEvent.
visit() [5/12]
Error BlockVerifier::visit (EndBufferRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 177 of file BlockVerifier.cpp.
References EndOfBuffer.
visit() [6/12]
Error BlockVerifier::visit (FunctionRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 181 of file BlockVerifier.cpp.
References Function.
visit() [7/12]
Error BlockVerifier::visit (NewBufferRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 173 of file BlockVerifier.cpp.
References NewBuffer.
visit() [8/12]
Error BlockVerifier::visit (NewCPUIDRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 147 of file BlockVerifier.cpp.
References NewCPUId.
visit() [9/12]
Error BlockVerifier::visit (PIDRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 171 of file BlockVerifier.cpp.
References PIDEntry.
visit() [10/12]
Error BlockVerifier::visit (TSCWrapRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 151 of file BlockVerifier.cpp.
References TSCWrap.
visit() [11/12]
Error BlockVerifier::visit (TypedEventRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 163 of file BlockVerifier.cpp.
References TypedEvent.
visit() [12/12]
Error BlockVerifier::visit (WallclockRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 143 of file BlockVerifier.cpp.
References WallClockTime.
The documentation for this class was generated from the following files:
include/llvm/XRay/BlockVerifier.h
lib/XRay/BlockVerifier.cpp