LLVM: llvm::cas::ondisk::InternalRef4B Class Reference
llvm::cas::ondisk::InternalRef4B Class Reference
Compact 4 byte reference inside OnDiskGraphDB for smaller references.
#include "llvm/CAS/OnDiskGraphDB.h"
Public Member Functions
FileOffset getFileOffset () const
uint32_t getRawData () const
operator InternalRef () const
Static Public Member Functions
static std::optional< InternalRef4B > tryToShrink (InternalRef Ref)
Shrink to 4B reference.
Friends
class InternalRef
Detailed Description
Compact 4 byte reference inside OnDiskGraphDB for smaller references.
Definition at line 48 of file OnDiskGraphDB.h.
Member Function Documentation
getFileOffset()
FileOffset llvm::cas::ondisk::InternalRef4B::getFileOffset () const inline
Definition at line 50 of file OnDiskGraphDB.h.
Referenced by operator InternalRef().
getRawData()
uint32_t llvm::cas::ondisk::InternalRef4B::getRawData () const inline
Definition at line 51 of file OnDiskGraphDB.h.
operator InternalRef()
llvm::cas::ondisk::InternalRef4B::operator InternalRef () const inline
Definition at line 61 of file OnDiskGraphDB.h.
References getFileOffset(), and llvm::cas::ondisk::InternalRef::getFromOffset().
tryToShrink()
std::optional< InternalRef4B > llvm::cas::ondisk::InternalRef4B::tryToShrink (InternalRef Ref) inline static
Shrink to 4B reference.
Definition at line 54 of file OnDiskGraphDB.h.
References InternalRef, llvm::Offset, and llvm::Ref.
Friends And Related Symbol Documentation
InternalRef
friend class InternalRef friend
Definition at line 66 of file OnDiskGraphDB.h.
References InternalRef.
Referenced by InternalRef, and tryToShrink().
The documentation for this class was generated from the following file:
include/llvm/CAS/OnDiskGraphDB.h