LLVM: llvm::MBBReachingDefsInfo Class Reference
llvm::MBBReachingDefsInfo Class Reference
#include "llvm/CodeGen/ReachingDefAnalysis.h"
Public Member Functions
void init (unsigned NumBlockIDs)
unsigned numBlockIDs () const
void startBasicBlock (unsigned MBBNumber, unsigned NumRegUnits)
void append (unsigned MBBNumber, MCRegUnit Unit, int Def)
void prepend (unsigned MBBNumber, MCRegUnit Unit, int Def)
void replaceFront (unsigned MBBNumber, MCRegUnit Unit, int Def)
void clear ()
ArrayRef< ReachingDef > defs (unsigned MBBNumber, MCRegUnit Unit) const
Detailed Description
Definition at line 70 of file ReachingDefAnalysis.h.
Member Function Documentation
append()
void llvm::MBBReachingDefsInfo::append (unsigned MBBNumber, MCRegUnit Unit, int Def) inline
Definition at line 80 of file ReachingDefAnalysis.h.
clear()
void llvm::MBBReachingDefsInfo::clear () inline
Definition at line 94 of file ReachingDefAnalysis.h.
defs()
ArrayRef< ReachingDef > llvm::MBBReachingDefsInfo::defs (unsigned MBBNumber, MCRegUnit Unit) const inline
Definition at line 96 of file ReachingDefAnalysis.h.
References llvm::ArrayRef().
init()
void llvm::MBBReachingDefsInfo::init (unsigned NumBlockIDs) inline
Definition at line 72 of file ReachingDefAnalysis.h.
numBlockIDs()
unsigned llvm::MBBReachingDefsInfo::numBlockIDs () const inline
Definition at line 74 of file ReachingDefAnalysis.h.
prepend()
void llvm::MBBReachingDefsInfo::prepend (unsigned MBBNumber, MCRegUnit Unit, int Def) inline
Definition at line 84 of file ReachingDefAnalysis.h.
replaceFront()
void llvm::MBBReachingDefsInfo::replaceFront (unsigned MBBNumber, MCRegUnit Unit, int Def) inline
Definition at line 89 of file ReachingDefAnalysis.h.
References assert(), and llvm::begin().
startBasicBlock()
void llvm::MBBReachingDefsInfo::startBasicBlock (unsigned MBBNumber, unsigned NumRegUnits) inline
Definition at line 76 of file ReachingDefAnalysis.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/ReachingDefAnalysis.h