LLVM: llvm::LibcallLoweringInfoWrapper Class Reference
llvm::LibcallLoweringInfoWrapper Class Reference
#include "llvm/CodeGen/LibcallLoweringInfo.h"
Public Member Functions
LibcallLoweringInfoWrapper ()
const LibcallLoweringInfo & getLibcallLowering (const TargetSubtargetInfo &Subtarget) const
const LibcallLoweringModuleAnalysisResult & getResult () const
bool doInitialization (Module &M) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
StringRef getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (const Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 123 of file LibcallLoweringInfo.h.
Constructor & Destructor Documentation
LibcallLoweringInfoWrapper()
LibcallLoweringInfoWrapper::LibcallLoweringInfoWrapper ()
Definition at line 60 of file LibcallLoweringInfo.cpp.
References ID, llvm::ImmutablePass::ImmutablePass(), and LibcallLoweringInfoWrapper().
Referenced by LibcallLoweringInfoWrapper().
Member Function Documentation
doInitialization()
bool LibcallLoweringInfoWrapper::doInitialization (Module &) override virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 62 of file LibcallLoweringInfo.cpp.
References llvm::Pass::getAnalysis().
getAnalysisUsage()
void LibcallLoweringInfoWrapper::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 67 of file LibcallLoweringInfo.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
getLibcallLowering()
const LibcallLoweringInfo & llvm::LibcallLoweringInfoWrapper::getLibcallLowering (const TargetSubtargetInfo & Subtarget) const inline
Definition at line 131 of file LibcallLoweringInfo.h.
getResult()
const LibcallLoweringModuleAnalysisResult & llvm::LibcallLoweringInfoWrapper::getResult () const inline
Definition at line 135 of file LibcallLoweringInfo.h.
releaseMemory()
void LibcallLoweringInfoWrapper::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 72 of file LibcallLoweringInfo.cpp.
Member Data Documentation
ID
libcall lowering Library Function Lowering true char LibcallLoweringInfoWrapper::ID = 0 static
Definition at line 127 of file LibcallLoweringInfo.h.
Referenced by LibcallLoweringInfoWrapper().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LibcallLoweringInfo.h
lib/CodeGen/LibcallLoweringInfo.cpp