LLVM: llvm::LLVMRemarkFileHandle Class Reference
llvm::LLVMRemarkFileHandle Class Reference final
RAII handle that manages the lifetime of the ToolOutputFile used to output remarks.
#include "llvm/IR/LLVMRemarkStreamer.h"
Public Member Functions
LLVMRemarkFileHandle ()
LLVMRemarkFileHandle (std::unique_ptr< ToolOutputFile > OutputFile, LLVMContext &Ctx)
ToolOutputFile * get ()
operator bool ()
std::unique_ptr< ToolOutputFile > releaseFile ()
Finalize remark emission and release the underlying ToolOutputFile.
void finalize ()
ToolOutputFile & operator* ()
ToolOutputFile * operator-> ()
Detailed Description
RAII handle that manages the lifetime of the ToolOutputFile used to output remarks.
On destruction (or when calling releaseFile()), this handle ensures that the optimization remarks are finalized and the RemarkStreamer is correctly deregistered from the LLVMContext.
Definition at line 90 of file LLVMRemarkStreamer.h.
Constructor & Destructor Documentation
LLVMRemarkFileHandle() [1/2]
llvm::LLVMRemarkFileHandle::LLVMRemarkFileHandle () inline
Definition at line 117 of file LLVMRemarkStreamer.h.
References nullptr.
LLVMRemarkFileHandle() [2/2]
llvm::LLVMRemarkFileHandle::LLVMRemarkFileHandle (std::unique_ptr< ToolOutputFile > OutputFile, LLVMContext & Ctx) inline
Definition at line 119 of file LLVMRemarkStreamer.h.
References llvm::move().
Member Function Documentation
finalize()
void llvm::LLVMRemarkFileHandle::finalize () inline
Definition at line 132 of file LLVMRemarkStreamer.h.
Referenced by llvm::lto::finalizeOptimizationRemarks(), and releaseFile().
get()
ToolOutputFile * llvm::LLVMRemarkFileHandle::get () inline
Definition at line 123 of file LLVMRemarkStreamer.h.
operator bool()
llvm::LLVMRemarkFileHandle::operator bool () inline explicit
Definition at line 124 of file LLVMRemarkStreamer.h.
operator*()
ToolOutputFile & llvm::LLVMRemarkFileHandle::operator* () inline
Definition at line 134 of file LLVMRemarkStreamer.h.
operator->()
ToolOutputFile * llvm::LLVMRemarkFileHandle::operator-> () inline
Definition at line 135 of file LLVMRemarkStreamer.h.
releaseFile()
std::unique_ptr< ToolOutputFile > llvm::LLVMRemarkFileHandle::releaseFile () inline
Finalize remark emission and release the underlying ToolOutputFile.
Definition at line 127 of file LLVMRemarkStreamer.h.
References finalize().
The documentation for this class was generated from the following file:
include/llvm/IR/LLVMRemarkStreamer.h