LLVM: llvm::BasicBlockSectionsProfileReaderWrapperPass Class Reference
llvm::BasicBlockSectionsProfileReaderWrapperPass Class Reference
#include "llvm/CodeGen/BasicBlockSectionsProfileReader.h"
Public Member Functions
BasicBlockSectionsProfileReaderWrapperPass (const MemoryBuffer *Buf)
BasicBlockSectionsProfileReaderWrapperPass ()
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
bool isFunctionHot (StringRef FuncName) const
SmallVector< BBClusterInfo > getClusterInfoForFunction (StringRef FuncName) const
SmallVector< SmallVector< unsigned > > getClonePathsForFunction (StringRef FuncName) const
const CFGProfile * getFunctionCFGProfile (StringRef FuncName) const
uint64_t getEdgeCount (StringRef FuncName, const UniqueBBID &SrcBBID, const UniqueBBID &DestBBID) const
SmallVector< CallsiteID > getPrefetchTargetsForFunction (StringRef FuncName) const
bool doInitialization (Module &M) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
BasicBlockSectionsProfileReader & getBBSPR ()
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
StringRef getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Public Attributes
BasicBlockSectionsProfileReader BBSPR
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (const Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 220 of file BasicBlockSectionsProfileReader.h.
Constructor & Destructor Documentation
BasicBlockSectionsProfileReaderWrapperPass() [1/2]
llvm::BasicBlockSectionsProfileReaderWrapperPass::BasicBlockSectionsProfileReaderWrapperPass (const MemoryBuffer * Buf) inline
Definition at line 225 of file BasicBlockSectionsProfileReader.h.
References BBSPR, llvm::PassRegistry::getPassRegistry(), ID, llvm::ImmutablePass::ImmutablePass(), and llvm::initializeBasicBlockSectionsProfileReaderWrapperPassPass().
BasicBlockSectionsProfileReaderWrapperPass() [2/2]
llvm::BasicBlockSectionsProfileReaderWrapperPass::BasicBlockSectionsProfileReaderWrapperPass () inline
Definition at line 231 of file BasicBlockSectionsProfileReader.h.
References BBSPR, llvm::PassRegistry::getPassRegistry(), ID, llvm::ImmutablePass::ImmutablePass(), and llvm::initializeBasicBlockSectionsProfileReaderWrapperPassPass().
Member Function Documentation
doInitialization()
bool BasicBlockSectionsProfileReaderWrapperPass::doInitialization (Module &) override virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 520 of file BasicBlockSectionsProfileReader.cpp.
References assert(), BBSPR, F, llvm::sys::path::remove_leading_dotslash(), and llvm::report_fatal_error().
getBBSPR()
BasicBlockSectionsProfileReader & BasicBlockSectionsProfileReaderWrapperPass::getBBSPR ()
Definition at line 589 of file BasicBlockSectionsProfileReader.cpp.
References BBSPR.
getClonePathsForFunction()
SmallVector< SmallVector< unsigned > > BasicBlockSectionsProfileReaderWrapperPass::getClonePathsForFunction (StringRef FuncName) const
Definition at line 565 of file BasicBlockSectionsProfileReader.cpp.
References BBSPR.
getClusterInfoForFunction()
SmallVector< BBClusterInfo > BasicBlockSectionsProfileReaderWrapperPass::getClusterInfoForFunction (StringRef FuncName) const
Definition at line 559 of file BasicBlockSectionsProfileReader.cpp.
References BBSPR.
getEdgeCount()
uint64_t BasicBlockSectionsProfileReaderWrapperPass::getEdgeCount (StringRef FuncName, const UniqueBBID & SrcBBID, const UniqueBBID & DestBBID) const
Definition at line 576 of file BasicBlockSectionsProfileReader.cpp.
References BBSPR.
getFunctionCFGProfile()
const CFGProfile * BasicBlockSectionsProfileReaderWrapperPass::getFunctionCFGProfile (StringRef FuncName) const
Definition at line 571 of file BasicBlockSectionsProfileReader.cpp.
References BBSPR.
getPassName()
StringRef llvm::BasicBlockSectionsProfileReaderWrapperPass::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 237 of file BasicBlockSectionsProfileReader.h.
getPrefetchTargetsForFunction()
SmallVector< CallsiteID > BasicBlockSectionsProfileReaderWrapperPass::getPrefetchTargetsForFunction (StringRef FuncName) const
Definition at line 583 of file BasicBlockSectionsProfileReader.cpp.
References BBSPR.
isFunctionHot()
bool BasicBlockSectionsProfileReaderWrapperPass::isFunctionHot (StringRef FuncName) const
Definition at line 553 of file BasicBlockSectionsProfileReader.cpp.
References BBSPR.
Member Data Documentation
BBSPR
BasicBlockSectionsProfileReader llvm::BasicBlockSectionsProfileReaderWrapperPass::BBSPR
Definition at line 223 of file BasicBlockSectionsProfileReader.h.
Referenced by BasicBlockSectionsProfileReaderWrapperPass(), BasicBlockSectionsProfileReaderWrapperPass(), doInitialization(), getBBSPR(), getClonePathsForFunction(), getClusterInfoForFunction(), getEdgeCount(), getFunctionCFGProfile(), getPrefetchTargetsForFunction(), and isFunctionHot().
ID
char BasicBlockSectionsProfileReaderWrapperPass::ID = 0 static
Definition at line 222 of file BasicBlockSectionsProfileReader.h.
Referenced by BasicBlockSectionsProfileReaderWrapperPass(), and BasicBlockSectionsProfileReaderWrapperPass().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/BasicBlockSectionsProfileReader.h
lib/CodeGen/BasicBlockSectionsProfileReader.cpp