LLVM: llvm::orc::LLJIT::PlatformSupport Class Reference
llvm::orc::LLJIT::PlatformSupport Class Reference abstract
Initializer support for LLJIT.
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
virtual ~PlatformSupport ()
virtual Error initialize (JITDylib &JD)=0
virtual Error deinitialize (JITDylib &JD)=0
Static Protected Member Functions
static void setInitTransform (LLJIT &J, IRTransformLayer::TransformFunction T)
Detailed Description
Initializer support for LLJIT.
Definition at line 49 of file LLJIT.h.
Constructor & Destructor Documentation
~PlatformSupport()
llvm::orc::LLJIT::PlatformSupport::~PlatformSupport () virtual default
Member Function Documentation
deinitialize()
virtual Error llvm::orc::LLJIT::PlatformSupport::deinitialize (JITDylib & JD) pure virtual
Implemented in llvm::orc::ORCPlatformSupport.
References llvm::orc::LLJIT::LLJIT(), setInitTransform(), and T.
initialize()
virtual Error llvm::orc::LLJIT::PlatformSupport::initialize (JITDylib & JD) pure virtual
Implemented in llvm::orc::ORCPlatformSupport.
setInitTransform()
void llvm::orc::LLJIT::PlatformSupport::setInitTransform (LLJIT & J, IRTransformLayer::TransformFunction T) static protected
Definition at line 672 of file LLJIT.cpp.
References llvm::orc::LLJIT::InitHelperTransformLayer, llvm::orc::LLJIT::LLJIT(), and T.
Referenced by deinitialize().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LLJIT.h
lib/ExecutionEngine/Orc/LLJIT.cpp