LLVM: llvm::AtomicInfo Class Reference
llvm::AtomicInfo Class Reference abstract
#include "llvm/Frontend/Atomic/Atomic.h"
Public Member Functions
AtomicInfo (IRBuilderBase *Builder, Type *Ty, uint64_t AtomicSizeInBits, uint64_t ValueSizeInBits, Align AtomicAlign, Align ValueAlign, bool UseLibcall, IRBuilderBase::InsertPoint AllocaIP)
virtual ~AtomicInfo ()=default
Align getAtomicAlignment () const
uint64_t getAtomicSizeInBits () const
uint64_t getValueSizeInBits () const
bool shouldUseLibcall () const
Type * getAtomicTy () const
virtual Value * getAtomicPointer () const =0
virtual void decorateWithTBAA (Instruction *I)=0
virtual AllocaInst * CreateAlloca (Type *Ty, const Twine &Name) const =0
bool hasPadding () const
LLVMContext & getLLVMContext () const
LLVM_ABI bool shouldCastToInt (Type *ValTy, bool CmpXchg)
LLVM_ABI Value * EmitAtomicLoadOp (AtomicOrdering AO, bool IsVolatile, bool CmpXchg=false)
LLVM_ABI CallInst * EmitAtomicLibcall (StringRef fnName, Type *ResultType, ArrayRef< Value * > Args)
Value * getAtomicSizeValue () const
LLVM_ABI std::pair< Value *, Value * > EmitAtomicCompareExchangeLibcall (Value *ExpectedVal, Value *DesiredVal, AtomicOrdering Success, AtomicOrdering Failure)
Value * castToAtomicIntPointer (Value *addr) const
Value * getAtomicAddressAsAtomicIntPointer () const
LLVM_ABI std::pair< Value *, Value * > EmitAtomicCompareExchangeOp (Value *ExpectedVal, Value *DesiredVal, AtomicOrdering Success, AtomicOrdering Failure, bool IsVolatile=false, bool IsWeak=false)
LLVM_ABI std::pair< Value *, Value * > EmitAtomicCompareExchange (Value *ExpectedVal, Value *DesiredVal, AtomicOrdering Success, AtomicOrdering Failure, bool IsVolatile, bool IsWeak)
LLVM_ABI std::pair< LoadInst *, AllocaInst * > EmitAtomicLoadLibcall (AtomicOrdering AO)
LLVM_ABI void EmitAtomicStoreLibcall (AtomicOrdering AO, Value *Source)
Protected Attributes
IRBuilderBase * Builder
Type * Ty
uint64_t AtomicSizeInBits
uint64_t ValueSizeInBits
Align AtomicAlign
Align ValueAlign
bool UseLibcall
IRBuilderBase::InsertPoint AllocaIP
Detailed Description
Definition at line 17 of file Atomic.h.
Constructor & Destructor Documentation
AtomicInfo()
llvm::AtomicInfo::AtomicInfo (IRBuilderBase * Builder, Type * Ty, uint64_t AtomicSizeInBits, uint64_t ValueSizeInBits, Align AtomicAlign, Align ValueAlign, bool UseLibcall, IRBuilderBase::InsertPoint AllocaIP) inline
Definition at line 29 of file Atomic.h.
References AllocaIP, AtomicAlign, AtomicSizeInBits, Builder, Ty, UseLibcall, ValueAlign, and ValueSizeInBits.
~AtomicInfo()
virtual llvm::AtomicInfo::~AtomicInfo () virtual default
Member Function Documentation
castToAtomicIntPointer()
Value * llvm::AtomicInfo::castToAtomicIntPointer (Value * addr) const inline
Definition at line 82 of file Atomic.h.
Referenced by getAtomicAddressAsAtomicIntPointer().
CreateAlloca()
virtual AllocaInst * llvm::AtomicInfo::CreateAlloca (Type * Ty, const Twine & Name) const pure virtual
Implemented in llvm::OpenMPIRBuilder::AtomicInfo.
References Ty.
Referenced by EmitAtomicLoadLibcall().
decorateWithTBAA()
virtual void llvm::AtomicInfo::decorateWithTBAA (Instruction * I) pure virtual
Implemented in llvm::OpenMPIRBuilder::AtomicInfo.
References I.
Referenced by EmitAtomicLoadOp().
EmitAtomicCompareExchange()
std::pair< Value *, Value * > AtomicInfo::EmitAtomicCompareExchange (Value * ExpectedVal, Value * DesiredVal, AtomicOrdering Success, AtomicOrdering Failure, bool IsVolatile, bool IsWeak)
Definition at line 184 of file Atomic.cpp.
References EmitAtomicCompareExchangeLibcall(), EmitAtomicCompareExchangeOp(), shouldUseLibcall(), and Success.
EmitAtomicCompareExchangeLibcall()
std::pair< Value *, Value * > AtomicInfo::EmitAtomicCompareExchangeLibcall (Value * ExpectedVal, Value * DesiredVal, AtomicOrdering Success, AtomicOrdering Failure)
Definition at line 57 of file Atomic.cpp.
References EmitAtomicLibcall(), llvm::IntegerType::get(), getAtomicPointer(), getAtomicSizeValue(), llvm::Type::getInt1Ty(), llvm::Constant::getIntegerValue(), getLLVMContext(), and Success.
Referenced by EmitAtomicCompareExchange().
EmitAtomicCompareExchangeOp()
std::pair< Value *, Value * > AtomicInfo::EmitAtomicCompareExchangeOp (Value * ExpectedVal, Value * DesiredVal, AtomicOrdering Success, AtomicOrdering Failure, bool IsVolatile = false, bool IsWeak = false)
Definition at line 89 of file Atomic.cpp.
References Builder, getAtomicAddressAsAtomicIntPointer(), getAtomicAlignment(), Success, and llvm::SyncScope::System.
Referenced by EmitAtomicCompareExchange().
EmitAtomicLibcall()
CallInst * AtomicInfo::EmitAtomicLibcall (StringRef fnName, Type * ResultType, ArrayRef< Value * > Args)
Definition at line 37 of file Atomic.cpp.
References llvm::AttrBuilder::addAttribute(), Builder, llvm::FunctionType::get(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by EmitAtomicCompareExchangeLibcall().
EmitAtomicLoadLibcall()
std::pair< LoadInst *, AllocaInst * > AtomicInfo::EmitAtomicLoadLibcall (AtomicOrdering AO)
Definition at line 107 of file Atomic.cpp.
References AllocaIP, Builder, CreateAlloca(), DL, llvm::FunctionType::get(), getAtomicPointer(), getAtomicSizeInBits(), llvm::Type::getInt32Ty(), llvm::Type::getIntNTy(), getLLVMContext(), getName(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::AllocaInst::setAlignment(), llvm::toCABI(), and Ty.
Referenced by llvm::OpenMPIRBuilder::createAtomicRead().
EmitAtomicLoadOp()
Value * AtomicInfo::EmitAtomicLoadOp (AtomicOrdering AO, bool IsVolatile, bool CmpXchg = false)
Definition at line 22 of file Atomic.cpp.
References AtomicAlign, AtomicSizeInBits, Builder, decorateWithTBAA(), llvm::IntegerType::get(), getAtomicPointer(), getLLVMContext(), shouldCastToInt(), and Ty.
EmitAtomicStoreLibcall()
void AtomicInfo::EmitAtomicStoreLibcall (AtomicOrdering AO, Value * Source)
Definition at line 148 of file Atomic.cpp.
References AllocaIP, Builder, DL, llvm::FunctionType::get(), getAtomicPointer(), llvm::Type::getInt32Ty(), getLLVMContext(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::toCABI().
Referenced by llvm::OpenMPIRBuilder::createAtomicWrite().
getAtomicAddressAsAtomicIntPointer()
Value * llvm::AtomicInfo::getAtomicAddressAsAtomicIntPointer () const inline
Definition at line 86 of file Atomic.h.
References castToAtomicIntPointer(), and getAtomicPointer().
Referenced by EmitAtomicCompareExchangeOp().
getAtomicAlignment()
Align llvm::AtomicInfo::getAtomicAlignment () const inline
Definition at line 38 of file Atomic.h.
References AtomicAlign.
Referenced by EmitAtomicCompareExchangeOp().
getAtomicPointer()
virtual Value * llvm::AtomicInfo::getAtomicPointer () const pure virtual
Implemented in llvm::OpenMPIRBuilder::AtomicInfo.
Referenced by EmitAtomicCompareExchangeLibcall(), EmitAtomicLoadLibcall(), EmitAtomicLoadOp(), EmitAtomicStoreLibcall(), and getAtomicAddressAsAtomicIntPointer().
getAtomicSizeInBits()
uint64_t llvm::AtomicInfo::getAtomicSizeInBits () const inline
Definition at line 39 of file Atomic.h.
References AtomicSizeInBits.
Referenced by EmitAtomicLoadLibcall().
getAtomicSizeValue()
Value * llvm::AtomicInfo::getAtomicSizeValue () const inline
Definition at line 67 of file Atomic.h.
References AtomicSizeInBits, llvm::IntegerType::get(), and getLLVMContext().
Referenced by EmitAtomicCompareExchangeLibcall().
getAtomicTy()
Type * llvm::AtomicInfo::getAtomicTy () const inline
Definition at line 42 of file Atomic.h.
References Ty.
getLLVMContext()
LLVMContext & llvm::AtomicInfo::getLLVMContext () const inline
Definition at line 57 of file Atomic.h.
References Builder.
Referenced by EmitAtomicCompareExchangeLibcall(), EmitAtomicLoadLibcall(), EmitAtomicLoadOp(), EmitAtomicStoreLibcall(), and getAtomicSizeValue().
getValueSizeInBits()
uint64_t llvm::AtomicInfo::getValueSizeInBits () const inline
Definition at line 40 of file Atomic.h.
References ValueSizeInBits.
hasPadding()
bool llvm::AtomicInfo::hasPadding () const inline
Definition at line 55 of file Atomic.h.
References AtomicSizeInBits, and ValueSizeInBits.
shouldCastToInt()
bool AtomicInfo::shouldCastToInt (Type * ValTy, bool CmpXchg)
Definition at line 16 of file Atomic.cpp.
Referenced by EmitAtomicLoadOp().
shouldUseLibcall()
bool llvm::AtomicInfo::shouldUseLibcall () const inline
Definition at line 41 of file Atomic.h.
References UseLibcall.
Referenced by EmitAtomicCompareExchange().
Member Data Documentation
AllocaIP
IRBuilderBase::InsertPoint llvm::AtomicInfo::AllocaIP protected
Definition at line 26 of file Atomic.h.
Referenced by AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo(), EmitAtomicLoadLibcall(), and EmitAtomicStoreLibcall().
AtomicAlign
Align llvm::AtomicInfo::AtomicAlign protected
Definition at line 23 of file Atomic.h.
Referenced by AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo(), EmitAtomicLoadOp(), and getAtomicAlignment().
AtomicSizeInBits
uint64_t llvm::AtomicInfo::AtomicSizeInBits protected
Definition at line 21 of file Atomic.h.
Referenced by AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo(), EmitAtomicLoadOp(), getAtomicSizeInBits(), getAtomicSizeValue(), and hasPadding().
Builder
IRBuilderBase* llvm::AtomicInfo::Builder protected
Definition at line 19 of file Atomic.h.
Referenced by AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::CreateAlloca(), EmitAtomicCompareExchangeOp(), EmitAtomicLibcall(), EmitAtomicLoadLibcall(), EmitAtomicLoadOp(), EmitAtomicStoreLibcall(), and getLLVMContext().
Ty
Type* llvm::AtomicInfo::Ty protected
Definition at line 20 of file Atomic.h.
Referenced by AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo(), CreateAlloca(), llvm::OpenMPIRBuilder::AtomicInfo::CreateAlloca(), EmitAtomicLoadLibcall(), EmitAtomicLoadOp(), and getAtomicTy().
UseLibcall
bool llvm::AtomicInfo::UseLibcall protected
Definition at line 25 of file Atomic.h.
Referenced by AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo(), and shouldUseLibcall().
ValueAlign
Align llvm::AtomicInfo::ValueAlign protected
Definition at line 24 of file Atomic.h.
Referenced by AtomicInfo(), and llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo().
ValueSizeInBits
uint64_t llvm::AtomicInfo::ValueSizeInBits protected
Definition at line 22 of file Atomic.h.
Referenced by AtomicInfo(), llvm::OpenMPIRBuilder::AtomicInfo::AtomicInfo(), getValueSizeInBits(), and hasPadding().
The documentation for this class was generated from the following files:
include/llvm/Frontend/Atomic/Atomic.h
lib/Frontend/Atomic/Atomic.cpp