LLVM: llvm::logicalview::LVObject Class Reference
llvm::logicalview::LVObject Class Reference
#include "llvm/DebugInfo/LogicalView/Core/LVObject.h"
Public Member Functions
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
virtual bool isNamed () const
virtual bool isTyped () const
virtual bool isFiled () const
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
virtual StringRef getName () const
virtual void setName (StringRef ObjectName)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
virtual LVAddress getLowerAddress () const
virtual void setLowerAddress (LVAddress Address)
virtual LVAddress getUpperAddress () const
virtual void setUpperAddress (LVAddress Address)
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
virtual const char * kind () const
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
virtual std::string noLineAsString (bool ShowZero) const
virtual std::string lineNumberAsString (bool ShowZero=false) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
virtual Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
virtual void print (raw_ostream &OS, bool Full=true) const
virtual void printExtra (raw_ostream &OS, bool Full=true) const
void dump () const
uint32_t getID () const
Protected Member Functions
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
virtual void printFileIndex (raw_ostream &OS, bool Full=true) const
Detailed Description
Definition at line 118 of file LVObject.h.
Constructor & Destructor Documentation
LVObject()
llvm::logicalview::LVObject::LVObject () inline
Definition at line 201 of file LVObject.h.
~LVObject()
virtual llvm::logicalview::LVObject::~LVObject () virtual default
Member Function Documentation
doPrint()
Error LVObject::doPrint (bool Split, bool Match, bool Print, raw_ostream & OS, bool Full = true) const virtual
Reimplemented in llvm::logicalview::LVScope.
Definition at line 108 of file LVObject.cpp.
References llvm::Full, print(), and llvm::Error::success().
dump()
void llvm::logicalview::LVObject::dump () const inline
Definition at line 317 of file LVObject.h.
References llvm::dbgs(), and print().
getAttr()
dwarf::Attribute llvm::logicalview::LVObject::getAttr () const inline
Definition at line 234 of file LVObject.h.
Referenced by llvm::logicalview::LVLocation::setKind().
getID()
uint32_t llvm::logicalview::LVObject::getID () const inline
Definition at line 320 of file LVObject.h.
Referenced by checkIntegrityScopesTree(), and printAttributes().
getLevel()
LVLevel llvm::logicalview::LVObject::getLevel () const inline
Definition at line 244 of file LVObject.h.
Referenced by llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVElement::equals(), printAttributes(), and llvm::logicalview::LVScopeCompileUnit::printLocalNames().
getLineNumber()
uint32_t llvm::logicalview::LVObject::getLineNumber () const inline
Definition at line 274 of file LVObject.h.
Referenced by llvm::logicalview::LVElement::equals(), llvm::logicalview::LVLine::lineNumberAsString(), lineNumberAsString(), llvm::logicalview::LVCompare::printItem(), llvm::logicalview::LVElement::printReference(), and llvm::logicalview::LVLocation::validateRanges().
getLowerAddress()
virtual LVAddress llvm::logicalview::LVObject::getLowerAddress () const inline virtual
Reimplemented in llvm::logicalview::LVLocation.
Definition at line 269 of file LVObject.h.
getName()
virtual StringRef llvm::logicalview::LVObject::getName () const inline virtual
Reimplemented in llvm::logicalview::LVElement.
Definition at line 247 of file LVObject.h.
getOffset()
LVOffset llvm::logicalview::LVObject::getOffset () const inline
Definition at line 240 of file LVObject.h.
Referenced by llvm::logicalview::LVScope::addMissingElements(), llvm::logicalview::LVScope::addObject(), llvm::logicalview::LVScopeCompileUnit::addSize(), llvm::logicalview::LVElement::equals(), printAttributes(), printAttributes(), llvm::logicalview::LVLogicalVisitor::printMemberBegin(), and llvm::logicalview::LVLogicalVisitor::printTypeBegin().
getOpcode()
LVSmall llvm::logicalview::LVObject::getOpcode () const inline
Definition at line 236 of file LVObject.h.
getParent()
LVElement * llvm::logicalview::LVObject::getParent () const inline
Definition at line 250 of file LVObject.h.
References assert().
getParentScope()
LVScope * llvm::logicalview::LVObject::getParentScope () const inline
Definition at line 255 of file LVObject.h.
References assert().
Referenced by llvm::logicalview::LVSymbol::calculateCoverage(), llvm::logicalview::LVScope::equals(), llvm::logicalview::LVSymbol::fillLocationGaps(), llvm::logicalview::LVElement::generateName(), llvm::logicalview::LVScope::getQualifiedName(), llvm::logicalview::LVLogicalVisitor::inlineSiteAnnotation(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVElement::resolveParents(), llvm::logicalview::LVElement::traverseParents(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getParentSymbol()
LVSymbol * llvm::logicalview::LVObject::getParentSymbol () const inline
Definition at line 260 of file LVObject.h.
References assert().
Referenced by llvm::logicalview::LVLocationSymbol::printExtra(), and llvm::logicalview::LVLocation::setKind().
getTag()
dwarf::Tag llvm::logicalview::LVObject::getTag () const inline
Definition at line 232 of file LVObject.h.
Referenced by llvm::logicalview::LVElement::resolveFullname().
getUpperAddress()
virtual LVAddress llvm::logicalview::LVObject::getUpperAddress () const inline virtual
Reimplemented in llvm::logicalview::LVLocation.
Definition at line 271 of file LVObject.h.
indentAsString() [1/2]
std::string LVObject::indentAsString () const
Definition at line 38 of file LVObject.cpp.
References indentAsString(), and llvm::logicalview::options().
Referenced by indentAsString(), print(), and llvm::logicalview::LVScopeCompileUnit::printLocalNames().
indentAsString() [2/2]
std::string LVObject::indentAsString (LVLevel Level) const
Definition at line 33 of file LVObject.cpp.
isFiled()
virtual bool llvm::logicalview::LVObject::isFiled () const inline virtual
Reimplemented in llvm::logicalview::LVElement.
Definition at line 228 of file LVObject.h.
isLined()
bool llvm::logicalview::LVObject::isLined () const inline
Definition at line 229 of file LVObject.h.
Referenced by llvm::logicalview::LVElement::generateName().
isNamed()
virtual bool llvm::logicalview::LVObject::isNamed () const inline virtual
Reimplemented in llvm::logicalview::LVElement.
Definition at line 226 of file LVObject.h.
isTyped()
virtual bool llvm::logicalview::LVObject::isTyped () const inline virtual
Reimplemented in llvm::logicalview::LVElement.
Definition at line 227 of file LVObject.h.
kind()
virtual const char * llvm::logicalview::LVObject::kind () const inline virtual
Reimplemented in llvm::logicalview::LVLine, llvm::logicalview::LVLocation, llvm::logicalview::LVScope, llvm::logicalview::LVSymbol, and llvm::logicalview::LVType.
Definition at line 277 of file LVObject.h.
Referenced by checkIntegrityScopesTree(), llvm::logicalview::LVElement::equals(), and llvm::logicalview::LVCompare::printItem().
lineAsString()
std::string LVObject::lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const protected
Definition at line 50 of file LVObject.cpp.
References llvm::logicalview::Discriminator, noLineAsString(), and llvm::logicalview::options().
Referenced by llvm::logicalview::LVLine::lineNumberAsString(), lineNumberAsString(), and llvm::logicalview::LVScopeFunctionInlined::lineNumberAsString().
lineNumberAsString()
virtual std::string llvm::logicalview::LVObject::lineNumberAsString (bool ShowZero = false) const inline virtual
Reimplemented in llvm::logicalview::LVLine, and llvm::logicalview::LVScopeFunctionInlined.
Definition at line 287 of file LVObject.h.
References getLineNumber(), and lineAsString().
Referenced by llvm::logicalview::LVElement::generateName(), lineNumberAsStringStripped(), print(), llvm::logicalview::LVCompare::printItem(), and llvm::logicalview::LVScopeCompileUnit::printLocalNames().
lineNumberAsStringStripped()
std::string LVObject::lineNumberAsStringStripped (bool ShowZero = false) const
Definition at line 73 of file LVObject.cpp.
References lineNumberAsString().
markBranchAsMissing()
void LVObject::markBranchAsMissing ()
Definition at line 96 of file LVObject.cpp.
noLineAsString()
std::string LVObject::noLineAsString (bool ShowZero) const virtual
Reimplemented in llvm::logicalview::LVLine, and llvm::logicalview::LVLineAssembler.
Definition at line 45 of file LVObject.cpp.
Referenced by lineAsString(), and llvm::logicalview::LVLine::noLineAsString().
operator=()
LVObject & llvm::logicalview::LVObject::operator= (const LVObject &) delete
print()
void LVObject::print (raw_ostream & OS, bool Full = true) const virtual
Reimplemented in llvm::logicalview::LVLine, llvm::logicalview::LVLocation, llvm::logicalview::LVRange, llvm::logicalview::LVScope, llvm::logicalview::LVScopeCompileUnit, llvm::logicalview::LVScopeRoot, llvm::logicalview::LVSymbol, and llvm::logicalview::LVType.
Definition at line 156 of file LVObject.cpp.
References llvm::Full, indentAsString(), lineNumberAsString(), printAttributes(), and printFileIndex().
Referenced by doPrint(), llvm::logicalview::LVLine::print(), llvm::logicalview::LVLocation::print(), llvm::logicalview::LVScope::print(), llvm::logicalview::LVSymbol::print(), and llvm::logicalview::LVType::print().
printAttributes() [1/2]
void LVObject::printAttributes (raw_ostream & OS, bool Full, StringRef Name, LVObject * Parent, StringRef Value, bool UseQuotes = false, bool PrintRef = false) const
Definition at line 114 of file LVObject.cpp.
References llvm::format(), llvm::logicalview::formattedName(), llvm::Full, getOffset(), llvm::logicalview::hexSquareString(), llvm::logicalview::Name, llvm::logicalview::options(), and PrintRef.
printAttributes() [2/2]
void LVObject::printAttributes (raw_ostream & OS, bool Full = true) const
Definition at line 137 of file LVObject.cpp.
References getID(), getLevel(), getOffset(), llvm::logicalview::hexSquareString(), and llvm::logicalview::options().
Referenced by print(), llvm::logicalview::LVScope::printEncodedArgs(), llvm::logicalview::LVLocationSymbol::printExtra(), llvm::logicalview::LVScopeCompileUnit::printExtra(), llvm::logicalview::LVElement::printFileIndex(), llvm::logicalview::LVCompare::printItem(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVElement::printLinkageName(), and llvm::logicalview::LVElement::printReference().
printExtra()
virtual void llvm::logicalview::LVObject::printExtra (raw_ostream & OS, bool Full = true) const inline virtual
Reimplemented in llvm::logicalview::LVLine, llvm::logicalview::LVLineAssembler, llvm::logicalview::LVLineDebug, llvm::logicalview::LVLocation, llvm::logicalview::LVLocationSymbol, llvm::logicalview::LVRange, llvm::logicalview::LVScope, llvm::logicalview::LVScopeAggregate, llvm::logicalview::LVScopeAlias, llvm::logicalview::LVScopeArray, llvm::logicalview::LVScopeCompileUnit, llvm::logicalview::LVScopeEnumeration, llvm::logicalview::LVScopeFormalPack, llvm::logicalview::LVScopeFunction, llvm::logicalview::LVScopeFunctionInlined, llvm::logicalview::LVScopeModule, llvm::logicalview::LVScopeNamespace, llvm::logicalview::LVScopeRoot, llvm::logicalview::LVScopeTemplatePack, llvm::logicalview::LVSymbol, llvm::logicalview::LVType, llvm::logicalview::LVTypeDefinition, llvm::logicalview::LVTypeEnumerator, llvm::logicalview::LVTypeImport, llvm::logicalview::LVTypeParam, and llvm::logicalview::LVTypeSubrange.
Definition at line 314 of file LVObject.h.
printFileIndex()
virtual void llvm::logicalview::LVObject::printFileIndex (raw_ostream & OS, bool Full = true) const inline protected virtual
Reimplemented in llvm::logicalview::LVElement.
Definition at line 198 of file LVObject.h.
Referenced by print().
PROPERTY() [1/19]
llvm::logicalview::LVObject::PROPERTY (Property , HasCodeViewLocation)
PROPERTY() [2/19]
llvm::logicalview::LVObject::PROPERTY (Property , HasMoved)
PROPERTY() [3/19]
llvm::logicalview::LVObject::PROPERTY (Property , HasPattern)
PROPERTY() [4/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsAdded)
PROPERTY() [5/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsDiscarded)
PROPERTY() [6/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsFileFromReference)
PROPERTY() [7/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsFinalized)
PROPERTY() [8/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsGeneratedName)
PROPERTY() [9/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsGlobalReference)
PROPERTY() [10/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsInCompare)
PROPERTY() [11/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsLineFromReference)
PROPERTY() [12/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsLocation)
PROPERTY() [13/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsMatched)
PROPERTY() [14/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsMissing)
PROPERTY() [15/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsMissingLink)
PROPERTY() [16/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsOptimized)
PROPERTY() [17/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsReferenced)
PROPERTY() [18/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsResolved)
PROPERTY() [19/19]
llvm::logicalview::LVObject::PROPERTY (Property , IsResolvedName)
referenceAsString()
std::string LVObject::referenceAsString (uint32_t LineNumber, bool Spaces) const protected
Definition at line 77 of file LVObject.cpp.
References llvm::String.
Referenced by llvm::logicalview::LVElement::printReference().
resetParent()
void llvm::logicalview::LVObject::resetParent () inline
Definition at line 267 of file LVObject.h.
setAttr()
void llvm::logicalview::LVObject::setAttr (dwarf::Attribute Attr) inline
Definition at line 235 of file LVObject.h.
References Attr.
setLevel()
void llvm::logicalview::LVObject::setLevel (LVLevel Level) inline
Definition at line 245 of file LVObject.h.
Referenced by setParent(), setParent(), llvm::logicalview::LVElement::updateLevel(), and llvm::logicalview::LVScope::updateLevel().
setLineNumber()
void llvm::logicalview::LVObject::setLineNumber (uint32_t Number) inline
Definition at line 275 of file LVObject.h.
Referenced by llvm::logicalview::LVLogicalVisitor::inlineSiteAnnotation(), and llvm::logicalview::LVLogicalVisitor::processLines().
setLowerAddress()
virtual void llvm::logicalview::LVObject::setLowerAddress (LVAddress Address) inline virtual
Reimplemented in llvm::logicalview::LVLocation.
Definition at line 270 of file LVObject.h.
setName()
virtual void llvm::logicalview::LVObject::setName (StringRef ObjectName) inline virtual
Reimplemented in llvm::logicalview::LVElement, and llvm::logicalview::LVScopeFunction.
Definition at line 248 of file LVObject.h.
setOffset()
void llvm::logicalview::LVObject::setOffset (LVOffset DieOffset) inline
Definition at line 241 of file LVObject.h.
Referenced by llvm::logicalview::LVLocationSymbol::addObject(), llvm::logicalview::LVLogicalVisitor::createElement(), and llvm::logicalview::LVLine::setAddress().
setOpcode()
void llvm::logicalview::LVObject::setOpcode (LVSmall Opcode) inline
Definition at line 237 of file LVObject.h.
References Opcode.
setParent() [1/2]
void LVObject::setParent (LVScope * Scope)
Definition at line 87 of file LVObject.cpp.
References Scope, and setLevel().
setParent() [2/2]
void LVObject::setParent (LVSymbol * Symbol)
Definition at line 91 of file LVObject.cpp.
References setLevel(), and Symbol.
setTag()
void llvm::logicalview::LVObject::setTag (dwarf::Tag Tag) inline
Definition at line 233 of file LVObject.h.
References Tag.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
setUpperAddress()
virtual void llvm::logicalview::LVObject::setUpperAddress (LVAddress Address) inline virtual
Reimplemented in llvm::logicalview::LVLocation.
Definition at line 272 of file LVObject.h.
Member Data Documentation
Attr
dwarf::Attribute llvm::logicalview::LVObject::Attr
Definition at line 147 of file LVObject.h.
Referenced by llvm::logicalview::LVSymbol::addLocation(), llvm::logicalview::LVSymbol::addLocationConstant(), and setAttr().
Element
LVElement* llvm::logicalview::LVObject::Element
Definition at line 162 of file LVObject.h.
Referenced by llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScopeCompileUnit::addInvalidOffset(), llvm::logicalview::LVScopeCompileUnit::addMatched(), llvm::logicalview::LVLine::classof(), llvm::logicalview::LVScope::classof(), llvm::logicalview::LVSymbol::classof(), llvm::logicalview::LVType::classof(), llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVElement::equals(), llvm::logicalview::LVScopeCompileUnit::lineRange(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), llvm::logicalview::LVScopeCompileUnit::printWarnings(), llvm::logicalview::LVElement::referenceMatch(), llvm::logicalview::LVElement::removeElement(), llvm::logicalview::LVScope::removeElement(), llvm::logicalview::LVScope::report(), llvm::logicalview::LVScope::resolve(), llvm::logicalview::LVScope::resolveReferences(), llvm::logicalview::LVSymbol::resolveReferences(), llvm::logicalview::LVType::resolveReferences(), llvm::logicalview::LVElement::setGenericType(), llvm::logicalview::LVElement::setReference(), llvm::logicalview::LVScopeAggregate::setReference(), llvm::logicalview::LVScopeFunction::setReference(), llvm::logicalview::LVScopeNamespace::setReference(), llvm::logicalview::LVSymbol::setReference(), llvm::logicalview::LVElement::setType(), llvm::logicalview::LVType::setUnderlyingType(), llvm::logicalview::LVTypeDefinition::setUnderlyingType(), llvm::logicalview::LVElement::typeOffsetAsString(), and llvm::logicalview::LVScope::updateLevel().
Opcode
LVSmall llvm::logicalview::LVObject::Opcode
Definition at line 148 of file LVObject.h.
Referenced by llvm::logicalview::LVSymbol::addLocationOperands(), llvm::logicalview::LVLocation::addObject(), llvm::logicalview::LVLocationSymbol::addObject(), setOpcode(), and llvm::logicalview::LVLocationSymbol::~LVLocationSymbol().
Scope
LVScope* llvm::logicalview::LVObject::Scope
Definition at line 163 of file LVObject.h.
Referenced by llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVRange::addEntry(), llvm::logicalview::LVRange::addEntry(), llvm::logicalview::LVScopeCompileUnit::addLineZero(), llvm::logicalview::LVScopeCompileUnit::addMatched(), llvm::logicalview::LVScopeCompileUnit::addPublicName(), llvm::logicalview::LVScopeCompileUnit::addSize(), llvm::logicalview::LVSymbol::calculateCoverage(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::logicalview::LVScope::equalNumberOfChildren(), llvm::logicalview::LVScope::equals(), llvm::logicalview::LVScopeAggregate::equals(), llvm::logicalview::LVScopeAlias::equals(), llvm::logicalview::LVScopeArray::equals(), llvm::logicalview::LVScopeCompileUnit::equals(), llvm::logicalview::LVScopeEnumeration::equals(), llvm::logicalview::LVScopeFormalPack::equals(), llvm::logicalview::LVScopeFunction::equals(), llvm::logicalview::LVScopeFunctionInlined::equals(), llvm::logicalview::LVScopeModule::equals(), llvm::logicalview::LVScopeNamespace::equals(), llvm::logicalview::LVScopeRoot::equals(), llvm::logicalview::LVScopeTemplatePack::equals(), llvm::logicalview::LVScope::findEqualScope(), llvm::logicalview::LVScopeAggregate::findEqualScope(), llvm::logicalview::LVScopeFunction::findEqualScope(), llvm::logicalview::LVScopeNamespace::findEqualScope(), llvm::logicalview::LVScopeCompileUnit::findPublicName(), llvm::logicalview::LVElement::generateName(), llvm::logicalview::LVRange::getEntry(), llvm::logicalview::LVScope::getLocations(), llvm::logicalview::LVScope::getRanges(), llvm::logicalview::LVScope::getRanges(), llvm::logicalview::LVScopeCompileUnit::increment(), llvm::logicalview::LVRange::print(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), llvm::logicalview::LVScopeCompileUnit::printSizes(), llvm::logicalview::LVScopeRoot::processRangeInformation(), llvm::logicalview::LVScopeCompileUnit::propagatePatternMatch(), llvm::logicalview::LVScope::resolveElements(), llvm::logicalview::LVScopeFunction::resolveReferences(), setParent(), llvm::logicalview::LVElement::setReference(), llvm::logicalview::LVScopeAggregate::setReference(), llvm::logicalview::LVScopeFunction::setReference(), llvm::logicalview::LVScopeNamespace::setReference(), llvm::logicalview::LVScope::sort(), llvm::logicalview::LVRange::startSearch(), llvm::logicalview::LVScopeRoot::transformScopedName(), llvm::logicalview::LVScope::traverseParentsAndChildren(), llvm::logicalview::LVRange::~LVRange(), llvm::logicalview::LVScopeAlias::~LVScopeAlias(), llvm::logicalview::LVScopeArray::~LVScopeArray(), llvm::logicalview::LVScopeEnumeration::~LVScopeEnumeration(), llvm::logicalview::LVScopeFormalPack::~LVScopeFormalPack(), llvm::logicalview::LVScopeModule::~LVScopeModule(), and llvm::logicalview::LVScopeTemplatePack::~LVScopeTemplatePack().
Symbol
LVSymbol* llvm::logicalview::LVObject::Symbol
Definition at line 164 of file LVObject.h.
Referenced by llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScopeCompileUnit::addInvalidCoverage(), llvm::logicalview::LVScope::addMissingElements(), llvm::logicalview::LVSymbol::equals(), llvm::logicalview::LVScope::getLocations(), llvm::logicalview::LVSymbol::getParameters(), llvm::logicalview::LVScopeCompileUnit::increment(), llvm::logicalview::LVLocation::print(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVScopeCompileUnit::printWarnings(), llvm::logicalview::LVScopeFunctionType::resolveExtra(), setParent(), llvm::logicalview::LVElement::setReference(), and llvm::logicalview::LVSymbol::setReference().
Tag
dwarf::Tag llvm::logicalview::LVObject::Tag
Definition at line 146 of file LVObject.h.
Referenced by setTag().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVObject.h
lib/DebugInfo/LogicalView/Core/LVObject.cpp