LLVM: llvm::VPIRMetadata Class Reference
llvm::VPIRMetadata Class Reference
Helper to manage IR metadata for recipes.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPIRMetadata ()=default
VPIRMetadata (Instruction &I)
Adds metatadata that can be preserved from the original instruction I.
VPIRMetadata (const VPIRMetadata &Other)=default
Copy constructor for cloning.
VPIRMetadata & operator= (const VPIRMetadata &Other)=default
void applyMetadata (Instruction &I) const
Add all metadata to I.
void setMetadata (unsigned Kind, MDNode *Node)
Set metadata with kind Kind to Node.
void intersect (const VPIRMetadata &MD)
Intersect this VPIRMetadata object with MD, keeping only metadata nodes that are common to both.
MDNode * getMetadata (unsigned Kind) const
Get metadata of kind Kind. Returns nullptr if not found.
void print (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print metadata with node IDs.
Detailed Description
Helper to manage IR metadata for recipes.
It filters out metadata that cannot be propagated.
Definition at line 980 of file VPlan.h.
Constructor & Destructor Documentation
VPIRMetadata() [1/3]
llvm::VPIRMetadata::VPIRMetadata () default
Referenced by intersect(), operator=(), llvm::VPInstruction::VPInstruction(), llvm::VPInterleaveBase::VPInterleaveBase(), VPIRMetadata(), and llvm::VPWidenMemoryRecipe::VPWidenMemoryRecipe().
VPIRMetadata() [2/3]
llvm::VPIRMetadata::VPIRMetadata (Instruction & I) inline
Adds metatadata that can be preserved from the original instruction I.
Definition at line 988 of file VPlan.h.
References llvm::getMetadataToPropagate(), and I.
VPIRMetadata() [3/3]
llvm::VPIRMetadata::VPIRMetadata (const VPIRMetadata & Other) default
Copy constructor for cloning.
References VPIRMetadata().
Member Function Documentation
applyMetadata()
void VPIRMetadata::applyMetadata (Instruction & I) const
Add all metadata to I.
Definition at line 1725 of file VPlanRecipes.cpp.
References I.
Referenced by llvm::VPInterleaveEVLRecipe::execute(), llvm::VPInterleaveRecipe::execute(), llvm::VPWidenCallRecipe::execute(), llvm::VPWidenCastRecipe::execute(), llvm::VPWidenIntrinsicRecipe::execute(), llvm::VPWidenLoadEVLRecipe::execute(), llvm::VPWidenLoadRecipe::execute(), llvm::VPWidenRecipe::execute(), llvm::VPWidenStoreEVLRecipe::execute(), llvm::VPWidenStoreRecipe::execute(), and scalarizeInstruction().
getMetadata()
MDNode * llvm::VPIRMetadata::getMetadata (unsigned Kind) const inline
Get metadata of kind Kind. Returns nullptr if not found.
Definition at line 1016 of file VPlan.h.
References llvm::find_if(), and P.
intersect()
void VPIRMetadata::intersect (const VPIRMetadata & MD)
Intersect this VPIRMetadata object with MD, keeping only metadata nodes that are common to both.
Definition at line 1730 of file VPlanRecipes.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::Other, and VPIRMetadata().
Referenced by llvm::VPlanTransforms::createInterleaveGroups(), and getCommonMetadata().
operator=()
VPIRMetadata & llvm::VPIRMetadata::operator= (const VPIRMetadata & Other) default
References I, and VPIRMetadata().
print()
void VPIRMetadata::print (raw_ostream & O, VPSlotTracker & SlotTracker) const
Print metadata with node IDs.
Definition at line 1744 of file VPlanRecipes.cpp.
References assert(), llvm::ArrayRef< T >::empty(), llvm::interleaveComma(), Node::printAsOperand(), and llvm::ArrayRef< T >::size().
setMetadata()
void llvm::VPIRMetadata::setMetadata (unsigned Kind, MDNode * Node) inline
Set metadata with kind Kind to Node.
If metadata with Kind already exists, it will be replaced. Otherwise, it will be added.
Definition at line 1000 of file VPlan.h.
References llvm::find_if(), and P.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp