LLVM: llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager Class Reference
llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager Class Reference
Simple page-based allocator.
#include "llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorMemoryManager.h"
Public Member Functions
~SimpleExecutorMemoryManager () override
Expected< ExecutorAddr > reserve (uint64_t Size)
Expected< ExecutorAddr > initialize (tpctypes::FinalizeRequest &FR)
Error deinitialize (const std::vector< ExecutorAddr > &InitKeys)
Error release (const std::vector< ExecutorAddr > &Bases)
Error shutdown () override
void addBootstrapSymbols (StringMap< ExecutorAddr > &M) override
Public Member Functions inherited from llvm::orc::ExecutorBootstrapService
virtual ~ExecutorBootstrapService ()
Detailed Description
Simple page-based allocator.
Definition at line 33 of file SimpleExecutorMemoryManager.h.
Constructor & Destructor Documentation
~SimpleExecutorMemoryManager()
llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::~SimpleExecutorMemoryManager () override
Definition at line 21 of file SimpleExecutorMemoryManager.cpp.
References assert().
Member Function Documentation
addBootstrapSymbols()
void llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::addBootstrapSymbols (StringMap< ExecutorAddr > & M) override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 199 of file SimpleExecutorMemoryManager.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::orc::rt::SimpleExecutorMemoryManagerDeinitializeWrapperName, llvm::orc::rt::SimpleExecutorMemoryManagerInitializeWrapperName, llvm::orc::rt::SimpleExecutorMemoryManagerInstanceName, llvm::orc::rt::SimpleExecutorMemoryManagerReleaseWrapperName, and llvm::orc::rt::SimpleExecutorMemoryManagerReserveWrapperName.
deinitialize()
Error llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::deinitialize (const std::vector< ExecutorAddr > & InitKeys)
Definition at line 115 of file SimpleExecutorMemoryManager.cpp.
References llvm::joinErrors(), llvm::reverse(), and llvm::Error::success().
initialize()
Expected< ExecutorAddr > llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::initialize (tpctypes::FinalizeRequest & FR)
Definition at line 38 of file SimpleExecutorMemoryManager.cpp.
References llvm::orc::tpctypes::FinalizeRequest::Actions, assert(), llvm::orc::ExecutorAddrRange::End, llvm::errorCodeToError(), llvm::orc::Exec, llvm::formatv(), llvm::inconvertibleErrorCode(), llvm::sys::Memory::InvalidateInstructionCache(), LLVM_UNLIKELY, llvm::make_error(), llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, llvm::sys::Memory::protectMappedMemory(), llvm::orc::tpctypes::FinalizeRequest::Segments, llvm::orc::ExecutorAddrRange::size(), llvm::orc::ExecutorAddrRange::Start, llvm::orc::ExecutorAddr::toPtr(), and llvm::orc::toSysMemoryProtectionFlags().
release()
Error llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::release (const std::vector< ExecutorAddr > & Bases)
Definition at line 145 of file SimpleExecutorMemoryManager.cpp.
References llvm::sampleprof::Base, llvm::copy(), llvm::errorCodeToError(), llvm::formatv(), llvm::inconvertibleErrorCode(), llvm::joinErrors(), llvm::make_error(), llvm::sys::Memory::releaseMappedMemory(), llvm::reverse(), and llvm::Error::success().
Referenced by shutdown().
reserve()
Expected< ExecutorAddr > llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::reserve (uint64_t Size)
Definition at line 25 of file SimpleExecutorMemoryManager.cpp.
References llvm::sys::Memory::allocateMappedMemory(), assert(), llvm::errorCodeToError(), llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, and Size.
shutdown()
Error llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::shutdown () override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 186 of file SimpleExecutorMemoryManager.cpp.
References llvm::sampleprof::Base, llvm::orc::ExecutorAddr::fromPtr(), and release().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorMemoryManager.h
lib/ExecutionEngine/Orc/TargetProcess/SimpleExecutorMemoryManager.cpp