LLVM: llvm::DiagnosticInfoMisExpect Class Reference
llvm::DiagnosticInfoMisExpect Class Reference
Diagnostic information for MisExpect analysis.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoMisExpect (const Instruction *Inst, const Twine &Msg LLVM_LIFETIME_BOUND)
void print (DiagnosticPrinter &DP) const override
const Twine & getMsg () const
Public Member Functions inherited from llvm::DiagnosticInfoWithLocationBase
DiagnosticInfoWithLocationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const Function &Fn, const DiagnosticLocation &Loc)
Fn is the function where the diagnostic is being emitted.
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
std::string getLocationStr () const
Return a string with the location information for this diagnostic in the format "file:line:col".
void getLocation (StringRef &RelativePath, unsigned &Line, unsigned &Column) const
Return location information for this diagnostic in three parts: the relative source file path, line number and column.
std::string getAbsolutePath () const
Return the absolute path tot the file.
const Function & getFunction () const
DiagnosticLocation getLocation () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for MisExpect analysis.
Definition at line 1129 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoMisExpect()
DiagnosticInfoMisExpect::DiagnosticInfoMisExpect (const Instruction * Inst, const Twine &Msg LLVM_LIFETIME_BOUND)
Definition at line 459 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoWithLocationBase::DiagnosticInfoWithLocationBase(), llvm::DK_MisExpect, llvm::DS_Warning, getDebugLoc(), and getParent().
Member Function Documentation
classof()
bool llvm::DiagnosticInfoMisExpect::classof (const DiagnosticInfo * DI) inline static
Definition at line 1137 of file DiagnosticInfo.h.
References llvm::DK_MisExpect, and llvm::DiagnosticInfo::getKind().
getMsg()
const Twine & llvm::DiagnosticInfoMisExpect::getMsg () const inline
Definition at line 1141 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoMisExpect::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 466 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoWithLocationBase::getLocationStr(), and getMsg().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp