LLVM: llvm::PassBuilder Class Reference
llvm::PassBuilder Class Reference
This class provides access to building LLVM's passes.
#include "llvm/Passes/PassBuilder.h"
Classes
struct PipelineElement
A struct to capture parsed pass pipeline names.
Public Member Functions
LLVM_ABI PassBuilder (TargetMachine *TM=nullptr, PipelineTuningOptions PTO=PipelineTuningOptions(), std::optional< PGOOptions > PGOOpt=std::nullopt, PassInstrumentationCallbacks *PIC=nullptr, IntrusiveRefCntPtr< vfs::FileSystem > FS=vfs::getRealFileSystem())
LLVM_ABI void crossRegisterProxies (LoopAnalysisManager &LAM, FunctionAnalysisManager &FAM, CGSCCAnalysisManager &CGAM, ModuleAnalysisManager &MAM, MachineFunctionAnalysisManager *MFAM=nullptr)
Cross register the analysis managers through their proxies.
LLVM_ABI void registerModuleAnalyses (ModuleAnalysisManager &MAM)
Registers all available module analysis passes.
LLVM_ABI void registerCGSCCAnalyses (CGSCCAnalysisManager &CGAM)
Registers all available CGSCC analysis passes.
LLVM_ABI void registerFunctionAnalyses (FunctionAnalysisManager &FAM)
Registers all available function analysis passes.
LLVM_ABI void registerLoopAnalyses (LoopAnalysisManager &LAM)
Registers all available loop analysis passes.
LLVM_ABI void registerMachineFunctionAnalyses (MachineFunctionAnalysisManager &MFAM)
Registers all available machine function analysis passes.
LLVM_ABI FunctionPassManager buildFunctionSimplificationPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the core LLVM function canonicalization and simplification pipeline.
LLVM_ABI ModulePassManager buildModuleSimplificationPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the core LLVM module canonicalization and simplification pipeline.
LLVM_ABI ModuleInlinerWrapperPass buildInlinerPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the module pipeline that performs inlining as well as the inlining-driven cleanups.
LLVM_ABI ModulePassManager buildModuleInlinerPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the module pipeline that performs inlining with module inliner pass.
LLVM_ABI ModulePassManager buildModuleOptimizationPipeline (OptimizationLevel Level, ThinOrFullLTOPhase LTOPhase)
Construct the core LLVM module optimization pipeline.
LLVM_ABI ModulePassManager buildPerModuleDefaultPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase=ThinOrFullLTOPhase::None)
Build a per-module default optimization pipeline.
LLVM_ABI ModulePassManager buildFatLTODefaultPipeline (OptimizationLevel Level, bool ThinLTO, bool EmitSummary)
Build a fat object default optimization pipeline.
LLVM_ABI ModulePassManager buildThinLTOPreLinkDefaultPipeline (OptimizationLevel Level)
Build a pre-link, ThinLTO-targeting default optimization pipeline to a pass manager.
LLVM_ABI ModulePassManager buildThinLTODefaultPipeline (OptimizationLevel Level, const ModuleSummaryIndex *ImportSummary)
Build a ThinLTO default optimization pipeline to a pass manager.
LLVM_ABI ModulePassManager buildLTOPreLinkDefaultPipeline (OptimizationLevel Level)
Build a pre-link, LTO-targeting default optimization pipeline to a pass manager.
LLVM_ABI ModulePassManager buildLTODefaultPipeline (OptimizationLevel Level, ModuleSummaryIndex *ExportSummary)
Build an LTO default optimization pipeline to a pass manager.
LLVM_ABI ModulePassManager buildO0DefaultPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase=ThinOrFullLTOPhase::None)
Build an O0 pipeline with the minimal semantically required passes.
LLVM_ABI AAManager buildDefaultAAPipeline ()
Build the default AAManager with the default alias analysis pipeline registered.
LLVM_ABI Error parsePassPipeline (ModulePassManager &MPM, StringRef PipelineText)
Parse a textual pass pipeline description into a ModulePassManager.
LLVM_ABI Error parsePassPipeline (CGSCCPassManager &CGPM, StringRef PipelineText)
{{@ Parse a textual pass pipeline description into a specific PassManager
LLVM_ABI Error parsePassPipeline (FunctionPassManager &FPM, StringRef PipelineText)
LLVM_ABI Error parsePassPipeline (LoopPassManager &LPM, StringRef PipelineText)
LLVM_ABI Error parsePassPipeline (MachineFunctionPassManager &MFPM, StringRef PipelineText)
Parse a textual MIR pipeline into the provided MachineFunctionPass manager.
LLVM_ABI Error parseAAPipeline (AAManager &AA, StringRef PipelineText)
Parse a textual alias analysis pipeline into the provided AA manager.
LLVM_ABI std::optional< RegAllocFilterFunc > parseRegAllocFilter (StringRef RegAllocFilterName)
Parse RegAllocFilterName to get RegAllocFilterFunc.
LLVM_ABI void printPassNames (raw_ostream &OS)
Print pass names.
void registerPeepholeEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerLateLoopOptimizationsEPCallback (const std::function< void(LoopPassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerLoopOptimizerEndEPCallback (const std::function< void(LoopPassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerScalarOptimizerLateEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerCGSCCOptimizerLateEPCallback (const std::function< void(CGSCCPassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerVectorizerStartEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerVectorizerEndEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerPipelineStartEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerPipelineEarlySimplificationEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel, ThinOrFullLTOPhase)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerOptimizerEarlyEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel, ThinOrFullLTOPhase Phase)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerOptimizerLastEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel, ThinOrFullLTOPhase)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerFullLinkTimeOptimizationEarlyEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerFullLinkTimeOptimizationLastEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel)> &C)
Register a callback for a default optimizer pipeline extension point.
void registerParseAACallback (const std::function< bool(StringRef Name, AAManager &AA)> &C)
Register a callback for parsing an AliasAnalysis Name to populate the given AAManager AA.
void registerAnalysisRegistrationCallback (const std::function< void(CGSCCAnalysisManager &)> &C)
{{@ Register callbacks for analysis registration with this PassBuilder instance.
void registerAnalysisRegistrationCallback (const std::function< void(FunctionAnalysisManager &)> &C)
void registerAnalysisRegistrationCallback (const std::function< void(LoopAnalysisManager &)> &C)
void registerAnalysisRegistrationCallback (const std::function< void(ModuleAnalysisManager &)> &C)
void registerAnalysisRegistrationCallback (const std::function< void(MachineFunctionAnalysisManager &)> &C)
void registerPipelineParsingCallback (const std::function< bool(StringRef Name, CGSCCPassManager &, ArrayRef< PipelineElement >)> &C)
{{@ Register pipeline parsing callbacks with this pass builder instance.
void registerPipelineParsingCallback (const std::function< bool(StringRef Name, FunctionPassManager &, ArrayRef< PipelineElement >)> &C)
void registerPipelineParsingCallback (const std::function< bool(StringRef Name, LoopPassManager &, ArrayRef< PipelineElement >)> &C)
void registerPipelineParsingCallback (const std::function< bool(StringRef Name, ModulePassManager &, ArrayRef< PipelineElement >)> &C)
void registerPipelineParsingCallback (const std::function< bool(StringRef Name, MachineFunctionPassManager &, ArrayRef< PipelineElement >)> &C)
void registerRegClassFilterParsingCallback (const std::function< RegAllocFilterFunc(StringRef)> &C)
Register callbacks to parse target specific filter field if regalloc pass needs it.
LLVM_ABI void registerParseTopLevelPipelineCallback (const std::function< bool(ModulePassManager &, ArrayRef< PipelineElement >)> &C)
Register a callback for a top-level pipeline entry.
LLVM_ABI void addPGOInstrPassesForO0 (ModulePassManager &MPM, bool RunProfileGen, bool IsCS, bool AtomicCounterUpdate, std::string ProfileFile, std::string ProfileRemappingFile)
Add PGOInstrumenation passes for O0 only.
PassInstrumentationCallbacks * getPassInstrumentationCallbacks () const
Returns PIC.
IntrusiveRefCntPtr< vfs::FileSystem > getVirtualFileSystemPtr () const
Returns the virtual file system.
LLVM_ABI void invokePeepholeEPCallbacks (FunctionPassManager &FPM, OptimizationLevel Level)
LLVM_ABI void invokeLateLoopOptimizationsEPCallbacks (LoopPassManager &LPM, OptimizationLevel Level)
LLVM_ABI void invokeLoopOptimizerEndEPCallbacks (LoopPassManager &LPM, OptimizationLevel Level)
LLVM_ABI void invokeScalarOptimizerLateEPCallbacks (FunctionPassManager &FPM, OptimizationLevel Level)
LLVM_ABI void invokeCGSCCOptimizerLateEPCallbacks (CGSCCPassManager &CGPM, OptimizationLevel Level)
LLVM_ABI void invokeVectorizerStartEPCallbacks (FunctionPassManager &FPM, OptimizationLevel Level)
LLVM_ABI void invokeVectorizerEndEPCallbacks (FunctionPassManager &FPM, OptimizationLevel Level)
LLVM_ABI void invokeOptimizerEarlyEPCallbacks (ModulePassManager &MPM, OptimizationLevel Level, ThinOrFullLTOPhase Phase)
LLVM_ABI void invokeOptimizerLastEPCallbacks (ModulePassManager &MPM, OptimizationLevel Level, ThinOrFullLTOPhase Phase)
LLVM_ABI void invokeFullLinkTimeOptimizationEarlyEPCallbacks (ModulePassManager &MPM, OptimizationLevel Level)
LLVM_ABI void invokeFullLinkTimeOptimizationLastEPCallbacks (ModulePassManager &MPM, OptimizationLevel Level)
LLVM_ABI void invokePipelineStartEPCallbacks (ModulePassManager &MPM, OptimizationLevel Level)
LLVM_ABI void invokePipelineEarlySimplificationEPCallbacks (ModulePassManager &MPM, OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Static Public Member Functions
static bool checkParametrizedPassName (StringRef Name, StringRef PassName)
template<typename ParametersParseCallableT>
static auto parsePassParameters (ParametersParseCallableT &&Parser, StringRef Name, StringRef PassName) -> decltype(Parser(StringRef{}))
This performs customized parsing of pass name with parameters.
static LLVM_ABI Expected< bool > parseSinglePassOption (StringRef Params, StringRef OptionName, StringRef PassName)
Handle passes only accept one bool-valued parameter.
Detailed Description
This class provides access to building LLVM's passes.
Its members provide the baseline state available to passes during their construction. The PassRegistry.def file specifies how to construct all of the built-in passes, and those may reference these members during construction.
Definition at line 114 of file PassBuilder.h.
Constructor & Destructor Documentation
PassBuilder()
PassBuilder::PassBuilder (TargetMachine * TM = nullptr, PipelineTuningOptions PTO = PipelineTuningOptions(), std::optional< PGOOptions > PGOOpt = std::nullopt, PassInstrumentationCallbacks * PIC = nullptr, IntrusiveRefCntPtr< vfs::FileSystem > FS = vfs::getRealFileSystem()) explicit
Definition at line 505 of file PassBuilder.cpp.
References if(), llvm::move(), and registerPipelineParsingCallback().
Member Function Documentation
addPGOInstrPassesForO0()
void PassBuilder::addPGOInstrPassesForO0 (ModulePassManager & MPM, bool RunProfileGen, bool IsCS, bool AtomicCounterUpdate, std::string ProfileFile, std::string ProfileRemappingFile)
Add PGOInstrumenation passes for O0 only.
Definition at line 902 of file PassBuilderPipelines.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), assert(), llvm::CSFDO, llvm::FDO, and Options.
Referenced by buildO0DefaultPipeline().
buildDefaultAAPipeline()
AAManager PassBuilder::buildDefaultAAPipeline ()
Build the default AAManager with the default alias analysis pipeline registered.
This also adds target-specific alias analyses registered via TargetMachine::registerDefaultAliasAnalyses().
Definition at line 2437 of file PassBuilderPipelines.cpp.
References llvm::EnableGlobalAnalyses.
Referenced by parseAAPipeline(), and registerFunctionAnalyses().
buildFatLTODefaultPipeline()
ModulePassManager PassBuilder::buildFatLTODefaultPipeline (OptimizationLevel Level, bool ThinLTO, bool EmitSummary)
Build a fat object default optimization pipeline.
This builds a pipeline that runs the LTO/ThinLTO pre-link pipeline, and emits a section containing the pre-link bitcode along side the object code generated in non-LTO compilation.
Definition at line 1754 of file PassBuilderPipelines.cpp.
References addAnnotationRemarksPass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::lowertypetests::All, buildLTOPreLinkDefaultPipeline(), buildModuleOptimizationPipeline(), buildThinLTODefaultPipeline(), buildThinLTOPreLinkDefaultPipeline(), llvm::createModuleToPostOrderCGSCCPassAdaptor(), llvm::None, llvm::OptimizationLevel::O0, and llvm::PGOOptions::SampleUse.
buildFunctionSimplificationPipeline()
FunctionPassManager PassBuilder::buildFunctionSimplificationPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the core LLVM function canonicalization and simplification pipeline.
This is a long pipeline and uses most of the per-function optimization passes in LLVM to canonicalize and simplify the IR. It is suitable to run repeatedly over the IR and is not expected to destroy important information about the semantics of the IR.
Note that Level cannot be O0 here. The pipelines produced are only intended for use when attempting to optimize code. If frontends require some transformations for semantic reasons, they should explicitly build them.
Phase indicates the current ThinLTO phase.
Definition at line 586 of file PassBuilderPipelines.cpp.
References llvm::ExtraLoopPassManager< MarkerTy >::addPass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass(), llvm::AreStatisticsEnabled(), assert(), llvm::createFunctionToLoopPassAdaptor(), llvm::EnableConstraintElimination, llvm::EnableDFAJumpThreading, llvm::EnableGVNHoist, llvm::EnableGVNSink, llvm::EnableJumpTableToSwitch, llvm::EnableKnowledgeRetention, llvm::EnableLoopFlatten, llvm::EnableLoopHeaderDuplication, llvm::FullLTOPostLink, invokeLateLoopOptimizationsEPCallbacks(), invokeLoopOptimizerEndEPCallbacks(), invokePeepholeEPCallbacks(), invokeScalarOptimizerLateEPCallbacks(), llvm::PGOOptions::IRUse, isLTOPreLink(), llvm::ModifyCFG, llvm::OptimizationLevel::O0, llvm::OptimizationLevel::O3, llvm::OptimizationLevel::Oz, Phase, llvm::RunNewGVN, llvm::PGOOptions::SampleUse, llvm::ThinLTOPostLink, and llvm::ThinLTOPreLink.
Referenced by buildInlinerPipeline(), and buildModuleInlinerPipeline().
buildInlinerPipeline()
ModuleInlinerWrapperPass PassBuilder::buildInlinerPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the module pipeline that performs inlining as well as the inlining-driven cleanups.
Definition at line 936 of file PassBuilderPipelines.cpp.
References llvm::ModuleInlinerWrapperPass::addModulePass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::AttributorRun, buildFunctionSimplificationPipeline(), llvm::CGSCC, llvm::CGSCCInliner, llvm::createCGSCCToFunctionPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), llvm::InlineParams::EnableDeferral, llvm::EnableGlobalAnalyses, llvm::EnablePGOInlineDeferral, llvm::getInlineParams(), getInlineParamsFromOptLevel(), llvm::InlineParams::HotCallSiteThreshold, invokeCGSCCOptimizerLateEPCallbacks(), isLTOPreLink(), llvm::MaxDevirtIterations, llvm::OptimizationLevel::O0, llvm::OptimizationLevel::O2, llvm::OptimizationLevel::O3, llvm::PerformMandatoryInliningsFirst, Phase, llvm::PGOOptions::SampleUse, llvm::ThinLTOPreLink, and llvm::UseInlineAdvisor.
Referenced by buildModuleSimplificationPipeline().
buildLTODefaultPipeline()
ModulePassManager PassBuilder::buildLTODefaultPipeline (OptimizationLevel Level, ModuleSummaryIndex * ExportSummary)
Build an LTO default optimization pipeline to a pass manager.
This provides a good default optimization pipeline for link-time optimization and code generation. It is particularly tuned to fit well when IR coming into the LTO phase was first run through buildLTOPreLinkDefaultPipeline, and the two coordinate closely.
Definition at line 1944 of file PassBuilderPipelines.cpp.
References addAnnotationRemarksPass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass(), llvm::lowertypetests::Assume, buildCoroWrapper(), llvm::CGSCCInliner, llvm::createCGSCCToFunctionPassAdaptor(), llvm::createFunctionToLoopPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), llvm::createModuleToPostOrderCGSCCPassAdaptor(), llvm::PGOOptions::CSIRInstr, llvm::PGOOptions::CSIRUse, llvm::EnableConstraintElimination, llvm::EnableGlobalAnalyses, llvm::EnableHotColdSplit, llvm::EnableLoopFlatten, llvm::EnableMemProfContextDisambiguation, llvm::EnableModuleInliner, llvm::FullLTOPostLink, getInlineParamsFromOptLevel(), invokeFullLinkTimeOptimizationEarlyEPCallbacks(), invokeFullLinkTimeOptimizationLastEPCallbacks(), invokePeepholeEPCallbacks(), invokeVectorizerEndEPCallbacks(), invokeVectorizerStartEPCallbacks(), llvm::ModifyCFG, llvm::OptimizationLevel::O0, llvm::OptimizationLevel::O1, llvm::Optimize, llvm::OptimizationLevel::Os, llvm::OptimizationLevel::Oz, llvm::RunNewGVN, llvm::PGOOptions::SampleUse, llvm::UseInlineAdvisor, and llvm::ModuleSummaryIndex::withSupportsHotColdNew().
buildLTOPreLinkDefaultPipeline()
ModulePassManager PassBuilder::buildLTOPreLinkDefaultPipeline (OptimizationLevel Level)
Build a pre-link, LTO-targeting default optimization pipeline to a pass manager.
This adds the pre-link optimizations tuned to work well with a later LTO run. It works to minimize the IR which needs to be analyzed without making irreversible decisions which could be made better during the LTO run.
Definition at line 1937 of file PassBuilderPipelines.cpp.
References buildPerModuleDefaultPipeline(), and llvm::FullLTOPreLink.
Referenced by buildFatLTODefaultPipeline().
buildModuleInlinerPipeline()
ModulePassManager PassBuilder::buildModuleInlinerPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the module pipeline that performs inlining with module inliner pass.
Definition at line 1035 of file PassBuilderPipelines.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), buildFunctionSimplificationPipeline(), llvm::createModuleToFunctionPassAdaptor(), llvm::createModuleToPostOrderCGSCCPassAdaptor(), llvm::InlineParams::EnableDeferral, llvm::EnablePGOInlineDeferral, getInlineParamsFromOptLevel(), llvm::InlineParams::HotCallSiteThreshold, isLTOPreLink(), llvm::OptimizationLevel::O0, Phase, llvm::PGOOptions::SampleUse, llvm::ThinLTOPostLink, llvm::ThinLTOPreLink, llvm::UseCtxProfile, and llvm::UseInlineAdvisor.
Referenced by buildModuleSimplificationPipeline(), and buildThinLTODefaultPipeline().
buildModuleOptimizationPipeline()
ModulePassManager PassBuilder::buildModuleOptimizationPipeline (OptimizationLevel Level, ThinOrFullLTOPhase LTOPhase)
Construct the core LLVM module optimization pipeline.
This pipeline focuses on optimizing the execution speed of the IR. It uses cost modeling and thresholds to balance code growth against runtime improvements. It includes vectorization and other information destroying transformations. It also cannot generally be run repeatedly on a module without potentially seriously regressing either runtime performance of the code or serious code size growth.
Note that Level cannot be O0 here. The pipelines produced are only intended for use when attempting to optimize code. If frontends require some transformations for semantic reasons, they should explicitly build them.
Definition at line 1468 of file PassBuilderPipelines.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass(), llvm::lowertypetests::Assume, llvm::CGSCCInliner, llvm::createFunctionToLoopPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), llvm::PGOOptions::CSIRInstr, llvm::PGOOptions::CSIRUse, llvm::EnableCHR, llvm::EnableGlobalAnalyses, llvm::EnableHotColdSplit, llvm::EnableIROutliner, llvm::EnableLoopHeaderDuplication, llvm::EnableMatrix, llvm::EnableModuleInliner, getInlineParamsFromOptLevel(), invokeOptimizerEarlyEPCallbacks(), invokeOptimizerLastEPCallbacks(), invokeVectorizerEndEPCallbacks(), invokeVectorizerStartEPCallbacks(), isLTOPostLink(), isLTOPreLink(), llvm::None, llvm::OptimizationLevel::O3, llvm::OptimizationLevel::Oz, llvm::RunPartialInlining, llvm::UseInlineAdvisor, and llvm::UseLoopVersioningLICM.
Referenced by buildFatLTODefaultPipeline(), buildPerModuleDefaultPipeline(), and buildThinLTODefaultPipeline().
buildModuleSimplificationPipeline()
ModulePassManager PassBuilder::buildModuleSimplificationPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Construct the core LLVM module canonicalization and simplification pipeline.
This pipeline focuses on canonicalizing and simplifying the entire module of IR. Much like the function simplification pipeline above, it is suitable to run repeatedly over the IR and is not expected to destroy important information. It does, however, perform inlining and other heuristic based simplifications that are not strictly reversible.
Note that Level cannot be O0 here. The pipelines produced are only intended for use when attempting to optimize code. If frontends require some transformations for semantic reasons, they should explicitly build them.
Phase indicates the current ThinLTO phase.
Definition at line 1083 of file PassBuilderPipelines.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), assert(), llvm::lowertypetests::Assume, llvm::AttributorRun, buildInlinerPipeline(), buildModuleInlinerPipeline(), llvm::createModuleToFunctionPassAdaptor(), llvm::PGOOptions::CSIRInstr, llvm::CTXPROF, llvm::EnableModuleInliner, llvm::EnableSampledInstr, llvm::FlattenedProfileUsed, llvm::FullLTOPostLink, llvm::InstrumentColdFuncOnlyPath, invokePeepholeEPCallbacks(), invokePipelineEarlySimplificationEPCallbacks(), llvm::PGOOptions::IRInstr, llvm::PGOOptions::IRUse, llvm::PGOCtxProfLoweringPass::isCtxIRPGOInstrEnabled(), isLTOPreLink(), llvm::ModifyCFG, llvm::MODULE, llvm::OptimizationLevel::O0, llvm::OptimizationLevel::O3, llvm::OptimizationLevel::Os, llvm::OptimizationLevel::Oz, llvm::PGOInstrumentColdFunctionOnly, Phase, llvm::PGOOptions::SampleUse, llvm::ThinLTOPostLink, llvm::ThinLTOPreLink, and llvm::UseCtxProfile.
Referenced by buildPerModuleDefaultPipeline(), buildThinLTODefaultPipeline(), and buildThinLTOPreLinkDefaultPipeline().
buildO0DefaultPipeline()
ModulePassManager PassBuilder::buildO0DefaultPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase = ThinOrFullLTOPhase::None)
Build an O0 pipeline with the minimal semantically required passes.
This should only be used for non-LTO and LTO pre-link pipelines.
Definition at line 2314 of file PassBuilderPipelines.cpp.
References addAnnotationRemarksPass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), addPGOInstrPassesForO0(), assert(), buildCoroWrapper(), llvm::createFunctionToLoopPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), llvm::createModuleToPostOrderCGSCCPassAdaptor(), llvm::EnableMatrix, invokeCGSCCOptimizerLateEPCallbacks(), invokeLateLoopOptimizationsEPCallbacks(), invokeLoopOptimizerEndEPCallbacks(), invokeOptimizerEarlyEPCallbacks(), invokeOptimizerLastEPCallbacks(), invokePipelineEarlySimplificationEPCallbacks(), invokePipelineStartEPCallbacks(), invokeScalarOptimizerLateEPCallbacks(), invokeVectorizerEndEPCallbacks(), invokeVectorizerStartEPCallbacks(), llvm::PGOOptions::IRInstr, llvm::PGOOptions::IRUse, llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::isEmpty(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::isEmpty(), isLTOPreLink(), llvm::None, llvm::OptimizationLevel::O0, Phase, and llvm::PGOOptions::SampleUse.
Referenced by buildPerModuleDefaultPipeline(), and buildThinLTOPreLinkDefaultPipeline().
buildPerModuleDefaultPipeline()
ModulePassManager PassBuilder::buildPerModuleDefaultPipeline (OptimizationLevel Level, ThinOrFullLTOPhase Phase = ThinOrFullLTOPhase::None)
Build a per-module default optimization pipeline.
This provides a good default optimization pipeline for per-module optimization and code generation without any link-time optimization. It typically correspond to frontend "-O[123]" options for optimization levels O1, O2 and O3 resp.
Definition at line 1706 of file PassBuilderPipelines.cpp.
References addAnnotationRemarksPass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), assert(), buildModuleOptimizationPipeline(), buildModuleSimplificationPipeline(), buildO0DefaultPipeline(), llvm::createModuleToFunctionPassAdaptor(), invokePipelineStartEPCallbacks(), isLTOPreLink(), llvm::None, llvm::OptimizationLevel::O0, Phase, and llvm::PGOOptions::SampleUse.
Referenced by buildLTOPreLinkDefaultPipeline().
buildThinLTODefaultPipeline()
ModulePassManager PassBuilder::buildThinLTODefaultPipeline (OptimizationLevel Level, const ModuleSummaryIndex * ImportSummary)
Build a ThinLTO default optimization pipeline to a pass manager.
This provides a good default optimization pipeline for link-time optimization and code generation. It is particularly tuned to fit well when IR coming into the LTO phase was first run through buildThinLTOPreLinkDefaultPipeline, and the two coordinate closely.
Definition at line 1864 of file PassBuilderPipelines.cpp.
References addAnnotationRemarksPass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::lowertypetests::Assume, buildCoroWrapper(), buildModuleInlinerPipeline(), buildModuleOptimizationPipeline(), buildModuleSimplificationPipeline(), llvm::EnableMemProfContextDisambiguation, llvm::OptimizationLevel::O0, llvm::PGOOptions::SampleUse, llvm::ThinLTOPostLink, llvm::UseCtxProfile, and llvm::ModuleSummaryIndex::withSupportsHotColdNew().
Referenced by buildFatLTODefaultPipeline().
buildThinLTOPreLinkDefaultPipeline()
ModulePassManager PassBuilder::buildThinLTOPreLinkDefaultPipeline (OptimizationLevel Level)
Build a pre-link, ThinLTO-targeting default optimization pipeline to a pass manager.
This adds the pre-link optimizations tuned to prepare a module for a ThinLTO run. It works to minimize the IR which needs to be analyzed without making irreversible decisions which could be made better during the LTO run.
Definition at line 1803 of file PassBuilderPipelines.cpp.
References addAnnotationRemarksPass(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), buildModuleSimplificationPipeline(), buildO0DefaultPipeline(), llvm::createModuleToFunctionPassAdaptor(), invokeOptimizerEarlyEPCallbacks(), invokeOptimizerLastEPCallbacks(), invokePipelineStartEPCallbacks(), llvm::OptimizationLevel::O0, llvm::RunPartialInlining, llvm::PGOOptions::SampleUse, llvm::ThinLTOPreLink, and llvm::UseCtxProfile.
Referenced by buildFatLTODefaultPipeline().
checkParametrizedPassName()
bool llvm::PassBuilder::checkParametrizedPassName (StringRef Name, StringRef PassName) inline static
Definition at line 687 of file PassBuilder.h.
References PassName.
Referenced by isLoopNestPassName(), and isLoopPassName().
crossRegisterProxies()
void PassBuilder::crossRegisterProxies (LoopAnalysisManager & LAM, FunctionAnalysisManager & FAM, CGSCCAnalysisManager & CGAM, ModuleAnalysisManager & MAM, MachineFunctionAnalysisManager * MFAM = nullptr)
Cross register the analysis managers through their proxies.
This is an interface that can be used to cross register each AnalysisManager with all the others analysis managers.
Definition at line 2566 of file PassBuilder.cpp.
References CGAM, FAM, LAM, MAM, and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass().
getPassInstrumentationCallbacks()
PassInstrumentationCallbacks * llvm::PassBuilder::getPassInstrumentationCallbacks () const inline
Returns PIC.
External libraries can use this to register pass instrumentation callbacks.
Definition at line 642 of file PassBuilder.h.
getVirtualFileSystemPtr()
IntrusiveRefCntPtr< vfs::FileSystem > llvm::PassBuilder::getVirtualFileSystemPtr () const inline
Returns the virtual file system.
Definition at line 647 of file PassBuilder.h.
invokeCGSCCOptimizerLateEPCallbacks()
void PassBuilder::invokeCGSCCOptimizerLateEPCallbacks (CGSCCPassManager & CGPM, OptimizationLevel Level)
Definition at line 365 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildInlinerPipeline(), and buildO0DefaultPipeline().
invokeFullLinkTimeOptimizationEarlyEPCallbacks()
void PassBuilder::invokeFullLinkTimeOptimizationEarlyEPCallbacks (ModulePassManager & MPM, OptimizationLevel Level)
Definition at line 392 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildLTODefaultPipeline().
invokeFullLinkTimeOptimizationLastEPCallbacks()
void PassBuilder::invokeFullLinkTimeOptimizationLastEPCallbacks (ModulePassManager & MPM, OptimizationLevel Level)
Definition at line 397 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildLTODefaultPipeline().
invokeLateLoopOptimizationsEPCallbacks()
void PassBuilder::invokeLateLoopOptimizationsEPCallbacks (LoopPassManager & LPM, OptimizationLevel Level)
Definition at line 350 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildFunctionSimplificationPipeline(), and buildO0DefaultPipeline().
invokeLoopOptimizerEndEPCallbacks()
void PassBuilder::invokeLoopOptimizerEndEPCallbacks (LoopPassManager & LPM, OptimizationLevel Level)
Definition at line 355 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildFunctionSimplificationPipeline(), and buildO0DefaultPipeline().
invokeOptimizerEarlyEPCallbacks()
void PassBuilder::invokeOptimizerEarlyEPCallbacks (ModulePassManager & MPM, OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Definition at line 380 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C, and Phase.
Referenced by buildModuleOptimizationPipeline(), buildO0DefaultPipeline(), and buildThinLTOPreLinkDefaultPipeline().
invokeOptimizerLastEPCallbacks()
void PassBuilder::invokeOptimizerLastEPCallbacks (ModulePassManager & MPM, OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Definition at line 386 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C, and Phase.
Referenced by buildModuleOptimizationPipeline(), buildO0DefaultPipeline(), and buildThinLTOPreLinkDefaultPipeline().
invokePeepholeEPCallbacks()
void PassBuilder::invokePeepholeEPCallbacks (FunctionPassManager & FPM, OptimizationLevel Level)
Definition at line 345 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildFunctionSimplificationPipeline(), buildLTODefaultPipeline(), and buildModuleSimplificationPipeline().
invokePipelineEarlySimplificationEPCallbacks()
void PassBuilder::invokePipelineEarlySimplificationEPCallbacks (ModulePassManager & MPM, OptimizationLevel Level, ThinOrFullLTOPhase Phase)
Definition at line 407 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C, and Phase.
Referenced by buildModuleSimplificationPipeline(), and buildO0DefaultPipeline().
invokePipelineStartEPCallbacks()
void PassBuilder::invokePipelineStartEPCallbacks (ModulePassManager & MPM, OptimizationLevel Level)
Definition at line 402 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildO0DefaultPipeline(), buildPerModuleDefaultPipeline(), and buildThinLTOPreLinkDefaultPipeline().
invokeScalarOptimizerLateEPCallbacks()
void PassBuilder::invokeScalarOptimizerLateEPCallbacks (FunctionPassManager & FPM, OptimizationLevel Level)
Definition at line 360 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildFunctionSimplificationPipeline(), and buildO0DefaultPipeline().
invokeVectorizerEndEPCallbacks()
void PassBuilder::invokeVectorizerEndEPCallbacks (FunctionPassManager & FPM, OptimizationLevel Level)
Definition at line 375 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildLTODefaultPipeline(), buildModuleOptimizationPipeline(), and buildO0DefaultPipeline().
invokeVectorizerStartEPCallbacks()
void PassBuilder::invokeVectorizerStartEPCallbacks (FunctionPassManager & FPM, OptimizationLevel Level)
Definition at line 370 of file PassBuilderPipelines.cpp.
References llvm::CallingConv::C.
Referenced by buildLTODefaultPipeline(), buildModuleOptimizationPipeline(), and buildO0DefaultPipeline().
parseAAPipeline()
Error PassBuilder::parseAAPipeline (AAManager & AA, StringRef PipelineText)
Parse a textual alias analysis pipeline into the provided AA manager.
The format of the textual AA pipeline is a comma separated list of AA pass names:
basic-aa,globals-aa,...
The AA manager is set up such that the provided alias analyses are tried in the order specified. See the AAManaager documentation for details about the logic used. This routine just provides the textual mapping between AA names and the analyses to register with the manager.
Returns false if the text cannot be parsed cleanly. The specific state of the AA manager is unspecified if such an error is encountered and this returns false.
Definition at line 2726 of file PassBuilder.cpp.
References buildDefaultAAPipeline(), llvm::StringRef::empty(), llvm::formatv(), llvm::inconvertibleErrorCode(), llvm::make_error(), llvm::StringRef::split(), and llvm::Error::success().
parsePassParameters()
template<typename ParametersParseCallableT> auto llvm::PassBuilder::parsePassParameters (ParametersParseCallableT && Parser, StringRef Name, StringRef PassName) -> decltype(Parser(StringRef{})) inline static
This performs customized parsing of pass name with parameters.
We do not need parametrization of passes in textual pipeline very often, yet on a rare occasion ability to specify parameters right there can be useful.
Name - parameterized specification of a pass from a textual pipeline is a string in a form of : PassName '<' parameter-list '>'
Parameter list is being parsed by the parser callable argument, Parser, It takes a string-ref of parameters and returns either StringError or a parameter list in a form of a custom parameters type, all wrapped into Expected<> template class.
Definition at line 712 of file PassBuilder.h.
References PassName.
parsePassPipeline() [1/5]
Error PassBuilder::parsePassPipeline (CGSCCPassManager & CGPM, StringRef PipelineText)
{{@ Parse a textual pass pipeline description into a specific PassManager
Automatic deduction of an appropriate pass manager stack is not supported. For example, to insert a loop pass 'lpass' into a FunctionPassManager, this is the valid pipeline text:
function(lpass)
Definition at line 2653 of file PassBuilder.cpp.
References llvm::formatv(), llvm::StringRef::front(), llvm::inconvertibleErrorCode(), isCGSCCPassName(), llvm::make_error(), and llvm::Error::success().
parsePassPipeline() [2/5]
Error PassBuilder::parsePassPipeline (FunctionPassManager & FPM, StringRef PipelineText)
Definition at line 2676 of file PassBuilder.cpp.
References llvm::formatv(), llvm::StringRef::front(), llvm::inconvertibleErrorCode(), isFunctionPassName(), llvm::make_error(), and llvm::Error::success().
parsePassPipeline() [3/5]
Error PassBuilder::parsePassPipeline (LoopPassManager & LPM, StringRef PipelineText)
Definition at line 2698 of file PassBuilder.cpp.
References llvm::formatv(), llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::Error::success().
parsePassPipeline() [4/5]
Error PassBuilder::parsePassPipeline (MachineFunctionPassManager & MFPM, StringRef PipelineText)
Parse a textual MIR pipeline into the provided MachineFunctionPass manager.
The format of the textual machine pipeline is a comma separated list of machine pass names:
machine-funciton-pass,machine-module-pass,...
There is no need to specify the pass nesting, and this function currently cannot handle the pass nesting.
Definition at line 2712 of file PassBuilder.cpp.
References llvm::formatv(), llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::Error::success().
parsePassPipeline() [5/5]
Error PassBuilder::parsePassPipeline (ModulePassManager & MPM, StringRef PipelineText)
Parse a textual pass pipeline description into a ModulePassManager.
The format of the textual pass pipeline description looks something like:
module(function(instcombine,sroa),dce,cgscc(inliner,function(...)),...)
Pass managers have ()s describing the nest structure of passes. All passes are comma separated. As a special shortcut, if the very first pass is not a module pass (as a module pass manager is), this will automatically form the shortest stack of pass managers that allow inserting that first pass. So, assuming function passes 'fpassN', CGSCC passes 'cgpassN', and loop passes 'lpassN', all of these are valid:
fpass1,fpass2,fpass3 cgpass1,cgpass2,cgpass3 lpass1,lpass2,lpass3
And they are equivalent to the following (resp.):
module(function(fpass1,fpass2,fpass3)) module(cgscc(cgpass1,cgpass2,cgpass3)) module(function(loop(lpass1,lpass2,lpass3)))
This shortcut is especially useful for debugging and testing small pass combinations.
The sequence of passes aren't necessarily the exact same kind of pass. You can mix different levels implicitly if adaptor passes are defined to make them work. For example,
mpass1,fpass1,fpass2,mpass2,lpass1
This pipeline uses only one pass manager: the top-level module manager. fpass1,fpass2 and lpass1 are added into the top-level module manager using only adaptor passes. No nested function/loop pass managers are added. The purpose is to allow easy pass testing when the user specifically want the pass to run under a adaptor directly. This is preferred when a pipeline is largely of one type, but one or just a few passes are of different types(See PassBuilder.cpp for examples).
Definition at line 2602 of file PassBuilder.cpp.
References llvm::CallingConv::C, llvm::formatv(), llvm::StringRef::front(), llvm::inconvertibleErrorCode(), isCGSCCPassName(), isFunctionPassName(), isLoopNestPassName(), isLoopPassName(), isMachineFunctionPassName(), isModulePassName(), llvm::make_error(), and llvm::Error::success().
parseRegAllocFilter()
std::optional< RegAllocFilterFunc > PassBuilder::parseRegAllocFilter (StringRef RegAllocFilterName)
Parse RegAllocFilterName to get RegAllocFilterFunc.
Definition at line 2747 of file PassBuilder.cpp.
References llvm::CallingConv::C, and F.
parseSinglePassOption()
Expected< bool > PassBuilder::parseSinglePassOption (StringRef Params, StringRef OptionName, StringRef PassName) static
Handle passes only accept one bool-valued parameter.
Returns
false when Params is empty.
Definition at line 737 of file PassBuilder.cpp.
References llvm::StringRef::empty(), llvm::formatv(), llvm::inconvertibleErrorCode(), llvm::make_error(), PassName, and llvm::StringRef::split().
Referenced by parseBPFPreserveStaticOffsetOptions().
printPassNames()
void PassBuilder::printPassNames (raw_ostream & OS)
Print pass names.
Definition at line 2764 of file PassBuilder.cpp.
registerAnalysisRegistrationCallback() [1/5]
void llvm::PassBuilder::registerAnalysisRegistrationCallback (const std::function< void(CGSCCAnalysisManager &)> & C) inline
{{@ Register callbacks for analysis registration with this PassBuilder instance.
Callees register their analyses with the given AnalysisManager objects.
Definition at line 563 of file PassBuilder.h.
References llvm::CallingConv::C.
registerAnalysisRegistrationCallback() [2/5]
void llvm::PassBuilder::registerAnalysisRegistrationCallback (const std::function< void(FunctionAnalysisManager &)> & C) inline
Definition at line 567 of file PassBuilder.h.
References llvm::CallingConv::C.
registerAnalysisRegistrationCallback() [3/5]
void llvm::PassBuilder::registerAnalysisRegistrationCallback (const std::function< void(LoopAnalysisManager &)> & C) inline
Definition at line 571 of file PassBuilder.h.
References llvm::CallingConv::C.
registerAnalysisRegistrationCallback() [4/5]
void llvm::PassBuilder::registerAnalysisRegistrationCallback (const std::function< void(MachineFunctionAnalysisManager &)> & C) inline
Definition at line 579 of file PassBuilder.h.
References llvm::CallingConv::C.
registerAnalysisRegistrationCallback() [5/5]
void llvm::PassBuilder::registerAnalysisRegistrationCallback (const std::function< void(ModuleAnalysisManager &)> & C) inline
Definition at line 575 of file PassBuilder.h.
References llvm::CallingConv::C.
registerCGSCCAnalyses()
void PassBuilder::registerCGSCCAnalyses (CGSCCAnalysisManager & CGAM)
Registers all available CGSCC analysis passes.
This is an interface that can be used to populate a CGSCCAnalysisManager with all registered CGSCC analyses. Callers can still manually register any additional analyses. Callers can also pre-register analyses and this will not override those.
Definition at line 656 of file PassBuilder.cpp.
References llvm::CallingConv::C, and CGAM.
registerCGSCCOptimizerLateEPCallback()
void llvm::PassBuilder::registerCGSCCOptimizerLateEPCallback (const std::function< void(CGSCCPassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding CallGraphSCC passes at the end of the main CallGraphSCC passes and before any function simplification passes run by CGPassManager.
Definition at line 468 of file PassBuilder.h.
References llvm::CallingConv::C.
registerFullLinkTimeOptimizationEarlyEPCallback()
void llvm::PassBuilder::registerFullLinkTimeOptimizationEarlyEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimizations at the start of the full LTO pipeline.
Definition at line 539 of file PassBuilder.h.
References llvm::CallingConv::C.
registerFullLinkTimeOptimizationLastEPCallback()
void llvm::PassBuilder::registerFullLinkTimeOptimizationLastEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimizations at the end of the full LTO pipeline.
Definition at line 548 of file PassBuilder.h.
References llvm::CallingConv::C.
registerFunctionAnalyses()
void PassBuilder::registerFunctionAnalyses (FunctionAnalysisManager & FAM)
Registers all available function analysis passes.
This is an interface that can be used to populate a FunctionAnalysisManager with all registered function analyses. Callers can still manually register any additional analyses. Callers can also pre-register analyses and this will not override those.
Definition at line 665 of file PassBuilder.cpp.
References buildDefaultAAPipeline(), llvm::CallingConv::C, and FAM.
registerLateLoopOptimizationsEPCallback()
void llvm::PassBuilder::registerLateLoopOptimizationsEPCallback (const std::function< void(LoopPassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding late loop canonicalization and simplification passes. This is the last point in the loop optimization pipeline before loop deletion. Each pass added here must be an instance of LoopPass. This is the place to add passes that can remove loops, such as target- specific loop idiom recognition.
Definition at line 437 of file PassBuilder.h.
References llvm::CallingConv::C.
registerLoopAnalyses()
void PassBuilder::registerLoopAnalyses (LoopAnalysisManager & LAM)
Registers all available loop analysis passes.
This is an interface that can be used to populate a LoopAnalysisManager with all registered loop analyses. Callers can still manually register any additional analyses.
Definition at line 697 of file PassBuilder.cpp.
References llvm::CallingConv::C, and LAM.
registerLoopOptimizerEndEPCallback()
void llvm::PassBuilder::registerLoopOptimizerEndEPCallback (const std::function< void(LoopPassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding loop passes to the end of the loop optimizer.
Definition at line 447 of file PassBuilder.h.
References llvm::CallingConv::C.
registerMachineFunctionAnalyses()
void PassBuilder::registerMachineFunctionAnalyses (MachineFunctionAnalysisManager & MFAM)
Registers all available machine function analysis passes.
This is an interface that can be used to populate a MachineFunctionAnalysisManager with all registered function analyses. Callers can still manually register any additional analyses. Callers can also pre-register analyses and this will not override those.
Definition at line 686 of file PassBuilder.cpp.
References llvm::CallingConv::C.
registerModuleAnalyses()
void PassBuilder::registerModuleAnalyses (ModuleAnalysisManager & MAM)
Registers all available module analysis passes.
This is an interface that can be used to populate a ModuleAnalysisManager with all registered module analyses. Callers can still manually register any additional analyses. Callers can also pre-register analyses and this will not override those.
Definition at line 647 of file PassBuilder.cpp.
References llvm::CallingConv::C, and MAM.
registerOptimizerEarlyEPCallback()
void llvm::PassBuilder::registerOptimizerEarlyEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel, ThinOrFullLTOPhase Phase)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimizations before the function optimization pipeline.
Definition at line 519 of file PassBuilder.h.
References llvm::CallingConv::C, and Phase.
registerOptimizerLastEPCallback()
void llvm::PassBuilder::registerOptimizerLastEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel, ThinOrFullLTOPhase)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimizations at the very end of the function optimization pipeline.
Definition at line 529 of file PassBuilder.h.
References llvm::CallingConv::C.
registerParseAACallback()
void llvm::PassBuilder::registerParseAACallback (const std::function< bool(StringRef Name, AAManager &AA)> & C) inline
Register a callback for parsing an AliasAnalysis Name to populate the given AAManager AA.
Definition at line 555 of file PassBuilder.h.
References llvm::CallingConv::C.
registerParseTopLevelPipelineCallback()
void PassBuilder::registerParseTopLevelPipelineCallback (const std::function< bool(ModulePassManager &, ArrayRef< PipelineElement >)> & C)
Register a callback for a top-level pipeline entry.
If the PassManager type is not given at the top level of the pipeline text, this Callback should be used to determine the appropriate stack of PassManagers and populate the passed ModulePassManager.
Definition at line 2844 of file PassBuilder.cpp.
References llvm::CallingConv::C.
registerPeepholeEPCallback()
void llvm::PassBuilder::registerPeepholeEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding passes that perform peephole optimizations similar to the instruction combiner. These passes will be inserted after each instance of the instruction combiner pass.
Definition at line 423 of file PassBuilder.h.
References llvm::CallingConv::C.
registerPipelineEarlySimplificationEPCallback()
void llvm::PassBuilder::registerPipelineEarlySimplificationEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel, ThinOrFullLTOPhase)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimization right after passes that do basic simplification of the input IR.
Definition at line 509 of file PassBuilder.h.
References llvm::CallingConv::C.
registerPipelineParsingCallback() [1/5]
void llvm::PassBuilder::registerPipelineParsingCallback (const std::function< bool(StringRef Name, CGSCCPassManager &, ArrayRef< PipelineElement >)> & C) inline
{{@ Register pipeline parsing callbacks with this pass builder instance.
Using these callbacks, callers can parse both a single pass name, as well as entire sub-pipelines, and populate the PassManager instance accordingly.
Definition at line 589 of file PassBuilder.h.
References llvm::CallingConv::C.
Referenced by PassBuilder().
registerPipelineParsingCallback() [2/5]
void llvm::PassBuilder::registerPipelineParsingCallback (const std::function< bool(StringRef Name, FunctionPassManager &, ArrayRef< PipelineElement >)> & C) inline
Definition at line 594 of file PassBuilder.h.
References llvm::CallingConv::C.
registerPipelineParsingCallback() [3/5]
void llvm::PassBuilder::registerPipelineParsingCallback (const std::function< bool(StringRef Name, LoopPassManager &, ArrayRef< PipelineElement >)> & C) inline
Definition at line 599 of file PassBuilder.h.
References llvm::CallingConv::C.
registerPipelineParsingCallback() [4/5]
void llvm::PassBuilder::registerPipelineParsingCallback (const std::function< bool(StringRef Name, MachineFunctionPassManager &, ArrayRef< PipelineElement >)> & C) inline
Definition at line 609 of file PassBuilder.h.
References llvm::CallingConv::C.
registerPipelineParsingCallback() [5/5]
void llvm::PassBuilder::registerPipelineParsingCallback (const std::function< bool(StringRef Name, ModulePassManager &, ArrayRef< PipelineElement >)> & C) inline
Definition at line 604 of file PassBuilder.h.
References llvm::CallingConv::C.
registerPipelineStartEPCallback()
void llvm::PassBuilder::registerPipelineStartEPCallback (const std::function< void(ModulePassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimization once at the start of the pipeline. This does not apply to 'backend' compiles (LTO and ThinLTO link-time pipelines).
Definition at line 500 of file PassBuilder.h.
References llvm::CallingConv::C.
registerRegClassFilterParsingCallback()
void llvm::PassBuilder::registerRegClassFilterParsingCallback (const std::function< RegAllocFilterFunc(StringRef)> & C) inline
Register callbacks to parse target specific filter field if regalloc pass needs it.
E.g. AMDGPU requires regalloc passes can handle sgpr and vgpr separately.
Definition at line 619 of file PassBuilder.h.
References llvm::CallingConv::C.
registerScalarOptimizerLateEPCallback()
void llvm::PassBuilder::registerScalarOptimizerLateEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimization passes after most of the main optimizations, but before the last cleanup-ish optimizations.
Definition at line 457 of file PassBuilder.h.
References llvm::CallingConv::C.
registerVectorizerEndEPCallback()
void llvm::PassBuilder::registerVectorizerEndEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimization passes after the vectorizer and other highly target specific optimization passes are executed.
Definition at line 490 of file PassBuilder.h.
References llvm::CallingConv::C.
registerVectorizerStartEPCallback()
void llvm::PassBuilder::registerVectorizerStartEPCallback (const std::function< void(FunctionPassManager &, OptimizationLevel)> & C) inline
Register a callback for a default optimizer pipeline extension point.
This extension point allows adding optimization passes before the vectorizer and other highly target specific optimization passes are executed.
Definition at line 479 of file PassBuilder.h.
References llvm::CallingConv::C.
The documentation for this class was generated from the following files:
include/llvm/Passes/PassBuilder.h
lib/Passes/PassBuilder.cpp
lib/Passes/PassBuilderPipelines.cpp