LLVM: llvm::RegisterRegAllocBase< SubClass > Class Template Reference
llvm::RegisterRegAllocBase< SubClass > Class Template Reference
RegisterRegAllocBase class - Track the registration of register allocators.
#include "llvm/CodeGen/RegAllocRegistry.h"
Public Types
using FunctionPassCtor = FunctionPass *(*)()
Public Member Functions
RegisterRegAllocBase (const char *N, const char *D, FunctionPassCtor C)
~RegisterRegAllocBase ()
SubClass * getNext () const
Public Member Functions inherited from llvm::MachinePassRegistryNode< FunctionPass *(*)()>
MachinePassRegistryNode (const char *N, const char *D, FunctionPass *C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
StringRef getName () const
StringRef getDescription () const
FunctionPass * getCtor () const
void setNext (MachinePassRegistryNode *N)
Static Public Member Functions
static SubClass * getList ()
static FunctionPassCtor getDefault ()
static void setDefault (FunctionPassCtor C)
static void setListener (MachinePassRegistryListener< FunctionPassCtor > *L)
Static Public Attributes
static MachinePassRegistry< FunctionPassCtor > Registry
Detailed Description
template<class SubClass>
class llvm::RegisterRegAllocBase< SubClass >
RegisterRegAllocBase class - Track the registration of register allocators.
Definition at line 30 of file RegAllocRegistry.h.
Member Typedef Documentation
FunctionPassCtor
template<class SubClass> using llvm::RegisterRegAllocBase< SubClass >::FunctionPassCtor = FunctionPass *(*)()
Definition at line 32 of file RegAllocRegistry.h.
Constructor & Destructor Documentation
RegisterRegAllocBase()
template<class SubClass> llvm::RegisterRegAllocBase< SubClass >::RegisterRegAllocBase (const char * N, const char * D, FunctionPassCtor C) inline
Definition at line 36 of file RegAllocRegistry.h.
References llvm::CallingConv::C, D(), llvm::MachinePassRegistryNode< FunctionPass *(*)()>::MachinePassRegistryNode(), N, and Registry.
~RegisterRegAllocBase()
template<class SubClass> llvm::RegisterRegAllocBase< SubClass >::~RegisterRegAllocBase () inline
Definition at line 41 of file RegAllocRegistry.h.
References Registry.
Member Function Documentation
getDefault()
template<class SubClass> FunctionPassCtor llvm::RegisterRegAllocBase< SubClass >::getDefault () inline static
Definition at line 52 of file RegAllocRegistry.h.
References Registry.
getList()
template<class SubClass> SubClass * llvm::RegisterRegAllocBase< SubClass >::getList () inline static
Definition at line 48 of file RegAllocRegistry.h.
References Registry.
getNext()
template<class SubClass> SubClass * llvm::RegisterRegAllocBase< SubClass >::getNext () const inline
Definition at line 44 of file RegAllocRegistry.h.
References llvm::MachinePassRegistryNode< PassCtorTy >::getNext().
setDefault()
template<class SubClass> void llvm::RegisterRegAllocBase< SubClass >::setDefault (FunctionPassCtor C) inline static
Definition at line 54 of file RegAllocRegistry.h.
References llvm::CallingConv::C, and Registry.
setListener()
template<class SubClass> void llvm::RegisterRegAllocBase< SubClass >::setListener (MachinePassRegistryListener< FunctionPassCtor > * L) inline static
Definition at line 56 of file RegAllocRegistry.h.
References Registry.
Member Data Documentation
Registry
template<class SubClass> MachinePassRegistry<FunctionPassCtor> llvm::RegisterRegAllocBase< SubClass >::Registry static
Definition at line 34 of file RegAllocRegistry.h.
Referenced by getDefault(), getList(), RegisterRegAllocBase(), setDefault(), setListener(), and ~RegisterRegAllocBase().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/RegAllocRegistry.h