LLVM: llvm::sandboxir::CollectDescr::ExtractElementDescr Class Reference
llvm::sandboxir::CollectDescr::ExtractElementDescr Class Reference
Describes how to get a value element.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h"
Public Member Functions
ExtractElementDescr (Action *V, int ExtractIdx)
ExtractElementDescr (Value *V)
Action * getValue () const
Value * getScalar () const
bool needsExtract () const
int getExtractIdx () const
Detailed Description
Describes how to get a value element.
If the value is a vector then it also provides the index to extract it from.
Definition at line 256 of file Legality.h.
Constructor & Destructor Documentation
ExtractElementDescr() [1/2]
llvm::sandboxir::CollectDescr::ExtractElementDescr::ExtractElementDescr (Action * V, int ExtractIdx) inline
Definition at line 262 of file Legality.h.
ExtractElementDescr() [2/2]
llvm::sandboxir::CollectDescr::ExtractElementDescr::ExtractElementDescr (Value * V) inline
Definition at line 264 of file Legality.h.
Member Function Documentation
getExtractIdx()
int llvm::sandboxir::CollectDescr::ExtractElementDescr::getExtractIdx () const inline
Definition at line 268 of file Legality.h.
getScalar()
Value * llvm::sandboxir::CollectDescr::ExtractElementDescr::getScalar () const inline
Definition at line 266 of file Legality.h.
References llvm::cast().
getValue()
Action * llvm::sandboxir::CollectDescr::ExtractElementDescr::getValue () const inline
Definition at line 265 of file Legality.h.
References llvm::cast().
needsExtract()
bool llvm::sandboxir::CollectDescr::ExtractElementDescr::needsExtract () const inline
Definition at line 267 of file Legality.h.
References llvm::isa().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Legality.h