LLVM: llvm::orc::EHFrameRegistrationPlugin Class Reference
llvm::orc::EHFrameRegistrationPlugin Class Reference
Adds AllocationActions to register and deregister eh-frame sections in the absence of native Platform support.
#include "llvm/ExecutionEngine/Orc/EHFrameRegistrationPlugin.h"
Public Member Functions
EHFrameRegistrationPlugin (ExecutorAddr RegisterEHFrame, ExecutorAddr DeregisterEHFrame)
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::PassConfiguration &PassConfig) override
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (JITDylib &JD, ResourceKey K) override
void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey) override
Public Member Functions inherited from llvm::orc::LinkGraphLinkingLayer::Plugin
virtual ~Plugin ()
virtual void notifyMaterializing (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::JITLinkContext &Ctx, MemoryBufferRef InputObject)
virtual Error notifyEmitted (MaterializationResponsibility &MR)
Static Public Member Functions
static Expected< std::unique_ptr< EHFrameRegistrationPlugin > > Create (ExecutionSession &ES)
Detailed Description
Adds AllocationActions to register and deregister eh-frame sections in the absence of native Platform support.
Definition at line 26 of file EHFrameRegistrationPlugin.h.
Constructor & Destructor Documentation
EHFrameRegistrationPlugin()
llvm::orc::EHFrameRegistrationPlugin::EHFrameRegistrationPlugin (ExecutorAddr RegisterEHFrame, ExecutorAddr DeregisterEHFrame) inline
Definition at line 32 of file EHFrameRegistrationPlugin.h.
Member Function Documentation
Create()
Expected< std::unique_ptr< EHFrameRegistrationPlugin > > llvm::orc::EHFrameRegistrationPlugin::Create (ExecutionSession & ES) static
Definition at line 22 of file EHFrameRegistrationPlugin.cpp.
References llvm::orc::ExecutorProcessControl::getBootstrapSymbols(), and llvm::orc::ExecutionSession::getExecutorProcessControl().
Referenced by llvm::orc::LLJIT::setUpGenericLLVMIRPlatform.
modifyPassConfig()
void llvm::orc::EHFrameRegistrationPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & G, jitlink::PassConfiguration & PassConfig) override virtual
Reimplemented from llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 38 of file EHFrameRegistrationPlugin.cpp.
References llvm::cantFail(), G, llvm::jitlink::getEHFrameSection(), llvm::jitlink::SectionRange::getRange(), llvm::jitlink::LinkGraph::getTargetTriple(), llvm::Triple::isOSBinFormatMachO(), modifyPassConfig(), llvm::jitlink::PassConfiguration::PostFixupPasses, llvm::jitlink::PassConfiguration::PrePrunePasses, and llvm::Error::success().
Referenced by modifyPassConfig().
notifyFailed()
Error llvm::orc::EHFrameRegistrationPlugin::notifyFailed (MaterializationResponsibility & MR) inline override virtual
Implements llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 40 of file EHFrameRegistrationPlugin.h.
References llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::EHFrameRegistrationPlugin::notifyRemovingResources (JITDylib & JD, ResourceKey K) inline override virtual
Implements llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 43 of file EHFrameRegistrationPlugin.h.
References llvm::Error::success().
notifyTransferringResources()
void llvm::orc::EHFrameRegistrationPlugin::notifyTransferringResources (JITDylib & JD, ResourceKey DstKey, ResourceKey SrcKey) inline override virtual
Implements llvm::orc::LinkGraphLinkingLayer::Plugin.
Definition at line 46 of file EHFrameRegistrationPlugin.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/EHFrameRegistrationPlugin.h
lib/ExecutionEngine/Orc/EHFrameRegistrationPlugin.cpp