LLVM: llvm::MCSFrameEmitter Class Reference
llvm::MCSFrameEmitter Class Reference
#include "llvm/MC/MCSFrame.h"
Static Public Member Functions
static void emit (MCObjectStreamer &Streamer)
static void encodeFuncOffset (MCContext &C, uint64_t Offset, SmallVectorImpl< char > &Out, MCFragment *FDEFrag)
Detailed Description
Definition at line 28 of file MCSFrame.h.
Member Function Documentation
emit()
void MCSFrameEmitter::emit (MCObjectStreamer & Streamer) static
Definition at line 587 of file MCSFrame.cpp.
References llvm::MCObjectStreamer::emitLabel(), Emitter, llvm::MCStreamer::getContext(), llvm::MCStreamer::getDwarfFrameInfos(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getSFrameABIArch(), and llvm::MCStreamer::switchSection().
Referenced by llvm::MCObjectStreamer::emitFrames().
encodeFuncOffset()
void MCSFrameEmitter::encodeFuncOffset (MCContext & C, uint64_t Offset, SmallVectorImpl< char > & Out, MCFragment * FDEFrag) static
Definition at line 617 of file MCSFrame.cpp.
References assert(), llvm::big, llvm::CallingConv::C, llvm::MCFragment::getVarContents(), I, llvm::isUInt(), llvm::little, llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), T, and llvm::support::endian::write().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSFrame.h
lib/MC/MCSFrame.cpp