LLVM: llvm::xray::Record Class Reference
llvm::xray::Record Class Reference abstract
#include "llvm/XRay/FDRRecords.h"
Public Types
enum class RecordKind {
RK_Metadata , RK_Metadata_BufferExtents , RK_Metadata_WallClockTime , RK_Metadata_NewCPUId ,
RK_Metadata_TSCWrap , RK_Metadata_CustomEvent , RK_Metadata_CustomEventV5 , RK_Metadata_CallArg ,
RK_Metadata_PIDEntry , RK_Metadata_NewBuffer , RK_Metadata_EndOfBuffer , RK_Metadata_TypedEvent ,
RK_Metadata_LastMetadata , RK_Function
}
Public Member Functions
Record (const Record &)=delete
Record (Record &&)=delete
Record & operator= (const Record &)=delete
Record & operator= (Record &&)=delete
Record (RecordKind T)
RecordKind getRecordType () const
virtual Error apply (RecordVisitor &V)=0
virtual ~Record ()=default
Static Public Member Functions
static LLVM_ABI StringRef kindToString (RecordKind K)
Detailed Description
Definition at line 31 of file FDRRecords.h.
Member Enumeration Documentation
RecordKind
enum class llvm::xray::Record::RecordKind strong
Enumerator
RK_Metadata
RK_Metadata_BufferExtents
RK_Metadata_WallClockTime
RK_Metadata_NewCPUId
RK_Metadata_TSCWrap
RK_Metadata_CustomEvent
RK_Metadata_CustomEventV5
RK_Metadata_CallArg
RK_Metadata_PIDEntry
RK_Metadata_NewBuffer
RK_Metadata_EndOfBuffer
RK_Metadata_TypedEvent
RK_Metadata_LastMetadata
RK_Function
Definition at line 33 of file FDRRecords.h.
Constructor & Destructor Documentation
Record() [1/3]
llvm::xray::Record::Record (const Record &) delete
References Record().
Referenced by llvm::xray::FunctionRecord::classof(), llvm::xray::MetadataRecord::classof(), llvm::xray::FunctionRecord::FunctionRecord(), llvm::xray::FunctionRecord::FunctionRecord(), llvm::xray::MetadataRecord::MetadataRecord(), operator=(), operator=(), Record(), and Record().
Record() [2/3]
llvm::xray::Record::Record (Record &&) delete
References Record().
Record() [3/3]
llvm::xray::Record::Record (RecordKind T) inline explicit
Definition at line 60 of file FDRRecords.h.
~Record()
virtual llvm::xray::Record::~Record () virtual default
Member Function Documentation
apply()
virtual Error llvm::xray::Record::apply (RecordVisitor & V) pure virtual
Implemented in llvm::xray::BufferExtents, llvm::xray::CallArgRecord, llvm::xray::CustomEventRecord, llvm::xray::CustomEventRecordV5, llvm::xray::EndBufferRecord, llvm::xray::FunctionRecord, llvm::xray::NewBufferRecord, llvm::xray::NewCPUIDRecord, llvm::xray::PIDRecord, llvm::xray::TSCWrapRecord, llvm::xray::TypedEventRecord, and llvm::xray::WallclockRecord.
getRecordType()
RecordKind llvm::xray::Record::getRecordType () const inline
Definition at line 62 of file FDRRecords.h.
kindToString()
StringRef Record::kindToString (RecordKind K) static
Definition at line 31 of file FDRRecords.cpp.
References RK_Function, RK_Metadata, RK_Metadata_BufferExtents, RK_Metadata_CallArg, RK_Metadata_CustomEvent, RK_Metadata_CustomEventV5, RK_Metadata_EndOfBuffer, RK_Metadata_LastMetadata, RK_Metadata_NewBuffer, RK_Metadata_NewCPUId, RK_Metadata_PIDEntry, RK_Metadata_TSCWrap, RK_Metadata_TypedEvent, and RK_Metadata_WallClockTime.
Referenced by llvm::xray::FileBasedRecordProducer::produce().
operator=() [1/2]
Record & llvm::xray::Record::operator= (const Record &) delete
References Record().
operator=() [2/2]
Record & llvm::xray::Record::operator= (Record &&) delete
References Record().
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRRecords.h
lib/XRay/FDRRecords.cpp