LLVM: llvm::FeatureBitArray Class Reference
llvm::FeatureBitArray Class Reference
Class used to store the subtarget bits in the tables created by tablegen.
#include "llvm/TargetParser/SubtargetFeature.h"
Public Member Functions
constexpr FeatureBitArray (const std::array< uint64_t, MAX_SUBTARGET_WORDS > &B)
const FeatureBitset & getAsBitset () const
Public Member Functions inherited from llvm::FeatureBitset
constexpr FeatureBitset ()=default
constexpr FeatureBitset (std::initializer_list< unsigned > Init)
FeatureBitset & set ()
constexpr FeatureBitset & set (unsigned I)
constexpr FeatureBitset & reset (unsigned I)
constexpr FeatureBitset & flip (unsigned I)
constexpr bool operator[] (unsigned I) const
constexpr bool test (unsigned I) const
constexpr size_t size () const
bool any () const
bool none () const
size_t count () const
constexpr FeatureBitset & operator^= (const FeatureBitset &RHS)
constexpr FeatureBitset operator^ (const FeatureBitset &RHS) const
constexpr FeatureBitset & operator&= (const FeatureBitset &RHS)
constexpr FeatureBitset operator& (const FeatureBitset &RHS) const
constexpr FeatureBitset & operator|= (const FeatureBitset &RHS)
constexpr FeatureBitset operator| (const FeatureBitset &RHS) const
constexpr FeatureBitset operator~ () const
bool operator== (const FeatureBitset &RHS) const
bool operator!= (const FeatureBitset &RHS) const
bool operator< (const FeatureBitset &Other) const
Additional Inherited Members
Protected Member Functions inherited from llvm::FeatureBitset
constexpr FeatureBitset (const std::array< uint64_t, MAX_SUBTARGET_WORDS > &B)
Detailed Description
Class used to store the subtarget bits in the tables created by tablegen.
Definition at line 157 of file SubtargetFeature.h.
Constructor & Destructor Documentation
FeatureBitArray()
llvm::FeatureBitArray::FeatureBitArray (const std::array< uint64_t, MAX_SUBTARGET_WORDS > & B) inline constexpr
Definition at line 159 of file SubtargetFeature.h.
References B(), and llvm::FeatureBitset::FeatureBitset().
Member Function Documentation
getAsBitset()
const FeatureBitset & llvm::FeatureBitArray::getAsBitset () const inline
Definition at line 162 of file SubtargetFeature.h.
References llvm::FeatureBitset::FeatureBitset().
Referenced by ApplyFeatureFlag(), llvm::getCPUDefaultTargetFeatures(), getFeatures(), and llvm::MCSubtargetInfo::ToggleFeature().
The documentation for this class was generated from the following file:
include/llvm/TargetParser/SubtargetFeature.h