LLVM: llvm::LoongArchMachineFunctionInfo Class Reference
llvm::LoongArchMachineFunctionInfo Class Reference
LoongArchMachineFunctionInfo - This class is derived from MachineFunctionInfo and contains private LoongArch-specific information for each MachineFunction.
#include "Target/LoongArch/LoongArchMachineFunctionInfo.h"
Public Member Functions
LoongArchMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
unsigned getVarArgsSaveSize () const
void setVarArgsSaveSize (int Size)
unsigned getCalleeSavedStackSize () const
void setCalleeSavedStackSize (unsigned Size)
unsigned getArgumentStackSize () const
void setArgumentStackSize (unsigned size)
int getBranchRelaxationSpillFrameIndex ()
void setBranchRelaxationSpillFrameIndex (int Index)
void addIncomingByValArgs (SDValue Val)
SDValue getIncomingByValArgs (int Idx)
unsigned getIncomingByValArgsSize () const
void addSExt32Register (Register Reg)
bool isSExt32Register (Register Reg) const
void setJumpInfo (MachineInstr *JrMI, int JTIIdx)
unsigned getJumpInfoSize ()
MachineInstr * getJumpInfoJrMI (unsigned Idx)
int getJumpInfoJTIIndex (unsigned Idx)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy, typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
LoongArchMachineFunctionInfo - This class is derived from MachineFunctionInfo and contains private LoongArch-specific information for each MachineFunction.
Definition at line 25 of file LoongArchMachineFunctionInfo.h.
Constructor & Destructor Documentation
LoongArchMachineFunctionInfo()
llvm::LoongArchMachineFunctionInfo::LoongArchMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 54 of file LoongArchMachineFunctionInfo.h.
References F.
Referenced by clone().
Member Function Documentation
addIncomingByValArgs()
void llvm::LoongArchMachineFunctionInfo::addIncomingByValArgs (SDValue Val) inline
Definition at line 83 of file LoongArchMachineFunctionInfo.h.
addSExt32Register()
void llvm::LoongArchMachineFunctionInfo::addSExt32Register (Register Reg) inline
Definition at line 87 of file LoongArchMachineFunctionInfo.h.
References Reg.
Referenced by unpackFromRegLoc().
clone()
MachineFunctionInfo * llvm::LoongArchMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const inline override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 58 of file LoongArchMachineFunctionInfo.h.
References Allocator, llvm::MachineFunction::cloneInfo(), and LoongArchMachineFunctionInfo().
getArgumentStackSize()
unsigned llvm::LoongArchMachineFunctionInfo::getArgumentStackSize () const inline
Definition at line 73 of file LoongArchMachineFunctionInfo.h.
getBranchRelaxationSpillFrameIndex()
int llvm::LoongArchMachineFunctionInfo::getBranchRelaxationSpillFrameIndex () inline
Definition at line 76 of file LoongArchMachineFunctionInfo.h.
Referenced by llvm::LoongArchInstrInfo::insertIndirectBranch(), and llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
getCalleeSavedStackSize()
unsigned llvm::LoongArchMachineFunctionInfo::getCalleeSavedStackSize () const inline
Definition at line 70 of file LoongArchMachineFunctionInfo.h.
getIncomingByValArgs()
SDValue llvm::LoongArchMachineFunctionInfo::getIncomingByValArgs (int Idx) inline
Definition at line 84 of file LoongArchMachineFunctionInfo.h.
getIncomingByValArgsSize()
unsigned llvm::LoongArchMachineFunctionInfo::getIncomingByValArgsSize () const inline
Definition at line 85 of file LoongArchMachineFunctionInfo.h.
getJumpInfoJrMI()
MachineInstr * llvm::LoongArchMachineFunctionInfo::getJumpInfoJrMI (unsigned Idx) inline
Definition at line 97 of file LoongArchMachineFunctionInfo.h.
getJumpInfoJTIIndex()
int llvm::LoongArchMachineFunctionInfo::getJumpInfoJTIIndex (unsigned Idx) inline
Definition at line 98 of file LoongArchMachineFunctionInfo.h.
getJumpInfoSize()
unsigned llvm::LoongArchMachineFunctionInfo::getJumpInfoSize () inline
Definition at line 96 of file LoongArchMachineFunctionInfo.h.
Referenced by llvm::LoongArchAsmPrinter::emitJumpTableInfo().
getVarArgsFrameIndex()
int llvm::LoongArchMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 64 of file LoongArchMachineFunctionInfo.h.
getVarArgsSaveSize()
unsigned llvm::LoongArchMachineFunctionInfo::getVarArgsSaveSize () const inline
Definition at line 67 of file LoongArchMachineFunctionInfo.h.
isSExt32Register()
bool llvm::LoongArchMachineFunctionInfo::isSExt32Register (Register Reg) const inline
Definition at line 89 of file LoongArchMachineFunctionInfo.h.
References llvm::is_contained(), and Reg.
Referenced by isSignExtendedW().
setArgumentStackSize()
void llvm::LoongArchMachineFunctionInfo::setArgumentStackSize (unsigned size) inline
Definition at line 74 of file LoongArchMachineFunctionInfo.h.
References llvm::size().
setBranchRelaxationSpillFrameIndex()
void llvm::LoongArchMachineFunctionInfo::setBranchRelaxationSpillFrameIndex (int Index) inline
Definition at line 79 of file LoongArchMachineFunctionInfo.h.
Referenced by llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
setCalleeSavedStackSize()
void llvm::LoongArchMachineFunctionInfo::setCalleeSavedStackSize (unsigned Size) inline
Definition at line 71 of file LoongArchMachineFunctionInfo.h.
References Size.
setJumpInfo()
void llvm::LoongArchMachineFunctionInfo::setJumpInfo (MachineInstr * JrMI, int JTIIdx) inline
Definition at line 93 of file LoongArchMachineFunctionInfo.h.
setVarArgsFrameIndex()
void llvm::LoongArchMachineFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 65 of file LoongArchMachineFunctionInfo.h.
setVarArgsSaveSize()
void llvm::LoongArchMachineFunctionInfo::setVarArgsSaveSize (int Size) inline
Definition at line 68 of file LoongArchMachineFunctionInfo.h.
References Size.
The documentation for this class was generated from the following file:
lib/Target/LoongArch/LoongArchMachineFunctionInfo.h