LLVM: llvm::object::DirectX::PSVRuntimeInfo Class Reference
llvm::object::DirectX::PSVRuntimeInfo Class Reference
#include "llvm/Object/DXContainer.h"
Public Member Functions
PSVRuntimeInfo (StringRef D)
LLVM_ABI Error parse (uint16_t ShaderKind)
uint32_t getSize () const
uint32_t getResourceCount () const
ResourceArray getResources () const
uint32_t getVersion () const
uint32_t getResourceStride () const
const InfoStruct & getInfo () const
template<typename T>
const T * getInfoAs () const
StringRef getStringTable () const
ArrayRef< uint32_t > getSemanticIndexTable () const
LLVM_ABI uint8_t getSigInputCount () const
LLVM_ABI uint8_t getSigOutputCount () const
LLVM_ABI uint8_t getSigPatchOrPrimCount () const
SigElementArray getSigInputElements () const
SigElementArray getSigOutputElements () const
SigElementArray getSigPatchOrPrimElements () const
ViewArray< uint32_t > getOutputVectorMasks (size_t Idx) const
ViewArray< uint32_t > getPatchOrPrimMasks () const
ViewArray< uint32_t > getInputOutputMap (size_t Idx) const
ViewArray< uint32_t > getInputPatchMap () const
ViewArray< uint32_t > getPatchOutputMap () const
uint32_t getSigElementStride () const
bool usesViewID () const
uint8_t getInputVectorCount () const
ArrayRef< uint8_t > getOutputVectorCounts () const
uint8_t getPatchConstOrPrimVectorCount () const
Detailed Description
Definition at line 303 of file DXContainer.h.
Constructor & Destructor Documentation
PSVRuntimeInfo()
llvm::object::DirectX::PSVRuntimeInfo::PSVRuntimeInfo (StringRef D) inline
Definition at line 329 of file DXContainer.h.
References D().
Member Function Documentation
getInfo()
const InfoStruct & llvm::object::DirectX::PSVRuntimeInfo::getInfo () const inline
Definition at line 348 of file DXContainer.h.
getInfoAs()
template<typename T> const T * llvm::object::DirectX::PSVRuntimeInfo::getInfoAs () const inline
Definition at line 350 of file DXContainer.h.
References P, and T.
Referenced by getInputVectorCount(), getOutputVectorCounts(), getPatchConstOrPrimVectorCount(), and usesViewID().
getInputOutputMap()
ViewArray< uint32_t > llvm::object::DirectX::PSVRuntimeInfo::getInputOutputMap (size_t Idx) const inline
Definition at line 393 of file DXContainer.h.
References assert().
getInputPatchMap()
ViewArray< uint32_t > llvm::object::DirectX::PSVRuntimeInfo::getInputPatchMap () const inline
Definition at line 398 of file DXContainer.h.
getInputVectorCount()
uint8_t llvm::object::DirectX::PSVRuntimeInfo::getInputVectorCount () const inline
Definition at line 409 of file DXContainer.h.
References getInfoAs(), and P.
Referenced by parse().
getOutputVectorCounts()
ArrayRef< uint8_t > llvm::object::DirectX::PSVRuntimeInfo::getOutputVectorCounts () const inline
Definition at line 415 of file DXContainer.h.
References getInfoAs(), and P.
Referenced by parse().
getOutputVectorMasks()
ViewArray< uint32_t > llvm::object::DirectX::PSVRuntimeInfo::getOutputVectorMasks (size_t Idx) const inline
Definition at line 386 of file DXContainer.h.
References assert().
getPatchConstOrPrimVectorCount()
uint8_t llvm::object::DirectX::PSVRuntimeInfo::getPatchConstOrPrimVectorCount () const inline
Definition at line 421 of file DXContainer.h.
References getInfoAs(), and P.
Referenced by parse().
getPatchOrPrimMasks()
ViewArray< uint32_t > llvm::object::DirectX::PSVRuntimeInfo::getPatchOrPrimMasks () const inline
Definition at line 391 of file DXContainer.h.
getPatchOutputMap()
ViewArray< uint32_t > llvm::object::DirectX::PSVRuntimeInfo::getPatchOutputMap () const inline
Definition at line 399 of file DXContainer.h.
getResourceCount()
uint32_t llvm::object::DirectX::PSVRuntimeInfo::getResourceCount () const inline
Definition at line 335 of file DXContainer.h.
getResources()
ResourceArray llvm::object::DirectX::PSVRuntimeInfo::getResources () const inline
Definition at line 336 of file DXContainer.h.
getResourceStride()
uint32_t llvm::object::DirectX::PSVRuntimeInfo::getResourceStride () const inline
Definition at line 346 of file DXContainer.h.
getSemanticIndexTable()
ArrayRef< uint32_t > llvm::object::DirectX::PSVRuntimeInfo::getSemanticIndexTable () const inline
Definition at line 372 of file DXContainer.h.
getSigElementStride()
uint32_t llvm::object::DirectX::PSVRuntimeInfo::getSigElementStride () const inline
Definition at line 401 of file DXContainer.h.
getSigInputCount()
uint8_t DirectX::PSVRuntimeInfo::getSigInputCount () const
Definition at line 493 of file DXContainer.cpp.
References P.
Referenced by parse().
getSigInputElements()
SigElementArray llvm::object::DirectX::PSVRuntimeInfo::getSigInputElements () const inline
Definition at line 380 of file DXContainer.h.
getSigOutputCount()
uint8_t DirectX::PSVRuntimeInfo::getSigOutputCount () const
Definition at line 503 of file DXContainer.cpp.
References P.
Referenced by parse().
getSigOutputElements()
SigElementArray llvm::object::DirectX::PSVRuntimeInfo::getSigOutputElements () const inline
Definition at line 381 of file DXContainer.h.
getSigPatchOrPrimCount()
uint8_t DirectX::PSVRuntimeInfo::getSigPatchOrPrimCount () const
Definition at line 513 of file DXContainer.cpp.
References P.
Referenced by parse().
getSigPatchOrPrimElements()
SigElementArray llvm::object::DirectX::PSVRuntimeInfo::getSigPatchOrPrimElements () const inline
Definition at line 382 of file DXContainer.h.
getSize()
uint32_t llvm::object::DirectX::PSVRuntimeInfo::getSize () const inline
Definition at line 334 of file DXContainer.h.
getStringTable()
StringRef llvm::object::DirectX::PSVRuntimeInfo::getStringTable () const inline
Definition at line 371 of file DXContainer.h.
getVersion()
uint32_t llvm::object::DirectX::PSVRuntimeInfo::getVersion () const inline
Definition at line 338 of file DXContainer.h.
Referenced by parse().
parse()
Error DirectX::PSVRuntimeInfo::parse (uint16_t ShaderKind)
Definition at line 290 of file DXContainer.cpp.
References llvm::alignTo(), llvm::Triple::Domain, getInputVectorCount(), getOutputVectorCounts(), getPatchConstOrPrimVectorCount(), llvm::dxbc::getShaderStage(), getSigInputCount(), getSigOutputCount(), getSigPatchOrPrimCount(), getVersion(), llvm::Triple::Hull, I, llvm::sys::IsBigEndianHost, llvm::object::DirectX::parseFailed(), readInteger(), readStruct(), llvm::ArrayRef< T >::size(), llvm::StringRef::size(), llvm::StringRef::substr(), llvm::Error::success(), usesViewID(), llvm::Vector, X, and Y.
usesViewID()
bool llvm::object::DirectX::PSVRuntimeInfo::usesViewID () const inline
Definition at line 403 of file DXContainer.h.
References getInfoAs(), and P.
Referenced by parse().
The documentation for this class was generated from the following files:
include/llvm/Object/DXContainer.h
lib/Object/DXContainer.cpp