LLVM: llvm::SystemZMCInstLower Class Reference
llvm::SystemZMCInstLower Class Reference
#include "Target/SystemZ/SystemZMCInstLower.h"
Public Member Functions
SystemZMCInstLower (MCContext &ctx, SystemZAsmPrinter &asmPrinter)
void lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand lowerOperand (const MachineOperand &MO) const
const MCExpr * getExpr (const MachineOperand &MO, SystemZ::Specifier) const
Detailed Description
Definition at line 24 of file SystemZMCInstLower.h.
Constructor & Destructor Documentation
SystemZMCInstLower()
SystemZMCInstLower::SystemZMCInstLower (MCContext & ctx, SystemZAsmPrinter & asmPrinter)
Definition at line 32 of file SystemZMCInstLower.cpp.
Member Function Documentation
getExpr()
const MCExpr * SystemZMCInstLower::getExpr (const MachineOperand & MO, SystemZ::Specifier Spec) const
Definition at line 36 of file SystemZMCInstLower.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MachineOperand::getBlockAddress(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, and llvm::Offset.
Referenced by lowerOperand().
lower()
void SystemZMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 94 of file SystemZMCInstLower.cpp.
References llvm::MCInst::addOperand(), lowerOperand(), MI, and llvm::MCInst::setOpcode().
lowerOperand()
MCOperand SystemZMCInstLower::lowerOperand (const MachineOperand & MO) const
Definition at line 79 of file SystemZMCInstLower.cpp.
References llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getExpr(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), getSpecifierForTFlags(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::MachineOperand::MO_Immediate, and llvm::MachineOperand::MO_Register.
Referenced by lower().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZMCInstLower.h
lib/Target/SystemZ/SystemZMCInstLower.cpp