LLVM: llvm::DiagnosticInfoRegAllocFailure Class Reference
llvm::DiagnosticInfoRegAllocFailure Class Reference
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoRegAllocFailure (const Twine &MsgStr, const Function &Fn, const DiagnosticLocation &DL, DiagnosticSeverity Severity=DS_Error)
MsgStr is the message to be reported to the frontend.
DiagnosticInfoRegAllocFailure (const Twine &MsgStr, const Function &Fn, DiagnosticSeverity Severity=DS_Error)
const Twine & getMsgStr () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfoWithLocationBase
DiagnosticInfoWithLocationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const Function &Fn, const DiagnosticLocation &Loc)
Fn is the function where the diagnostic is being emitted.
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
std::string getLocationStr () const
Return a string with the location information for this diagnostic in the format "file:line:col".
void getLocation (StringRef &RelativePath, unsigned &Line, unsigned &Column) const
Return location information for this diagnostic in three parts: the relative source file path, line number and column.
std::string getAbsolutePath () const
Return the absolute path tot the file.
const Function & getFunction () const
DiagnosticLocation getLocation () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Definition at line 436 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoRegAllocFailure() [1/2]
DiagnosticInfoRegAllocFailure::DiagnosticInfoRegAllocFailure (const Twine & MsgStr, const Function & Fn, const DiagnosticLocation & DL, DiagnosticSeverity Severity = DS_Error)
MsgStr is the message to be reported to the frontend.
This class does not copy MsgStr, therefore the reference must be valid for the whole life time of the Diagnostic.
Definition at line 88 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoWithLocationBase::DiagnosticInfoWithLocationBase(), llvm::DK_RegAllocFailure, DL, getSubprogram(), and isValid().
DiagnosticInfoRegAllocFailure() [2/2]
DiagnosticInfoRegAllocFailure::DiagnosticInfoRegAllocFailure (const Twine & MsgStr, const Function & Fn, DiagnosticSeverity Severity = DS_Error)
Definition at line 95 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoWithLocationBase::DiagnosticInfoWithLocationBase(), llvm::DK_RegAllocFailure, and getSubprogram().
Member Function Documentation
classof()
bool llvm::DiagnosticInfoRegAllocFailure::classof (const DiagnosticInfo * DI) inline static
Definition at line 458 of file DiagnosticInfo.h.
References llvm::DK_RegAllocFailure, and llvm::DiagnosticInfo::getKind().
getMsgStr()
const Twine & llvm::DiagnosticInfoRegAllocFailure::getMsgStr () const inline
Definition at line 453 of file DiagnosticInfo.h.
print()
void DiagnosticInfoRegAllocFailure::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 101 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoWithLocationBase::getFunction(), and llvm::DiagnosticInfoWithLocationBase::getLocationStr().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp