LLVM: llvm::MachO::ObjCInterfaceRecord Class Reference
llvm::MachO::ObjCInterfaceRecord Class Reference
#include "llvm/TextAPI/Record.h"
Public Member Functions
ObjCInterfaceRecord (StringRef Name, RecordLinkage Linkage, ObjCIFSymbolKind SymType)
bool hasExceptionAttribute () const
bool isCompleteInterface () const
bool isExportedSymbol (ObjCIFSymbolKind CurrType) const
LLVM_ABI RecordLinkage getLinkageForSymbol (ObjCIFSymbolKind CurrType) const
LLVM_ABI void updateLinkageForSymbols (ObjCIFSymbolKind SymType, RecordLinkage Link)
LLVM_ABI bool addObjCCategory (ObjCCategoryRecord *Record)
LLVM_ABI std::vector< ObjCCategoryRecord * > getObjCCategories () const
Public Member Functions inherited from llvm::MachO::ObjCContainerRecord
ObjCContainerRecord (StringRef Name, RecordLinkage Linkage)
LLVM_ABI ObjCIVarRecord * addObjCIVar (StringRef IVar, RecordLinkage Linkage)
LLVM_ABI ObjCIVarRecord * findObjCIVar (StringRef IVar) const
LLVM_ABI std::vector< ObjCIVarRecord * > getObjCIVars () const
RecordLinkage getLinkage () const
Public Member Functions inherited from llvm::MachO::Record
Record ()=default
Record (StringRef Name, RecordLinkage Linkage, SymbolFlags Flags)
bool isWeakDefined () const
bool isWeakReferenced () const
bool isThreadLocalValue () const
bool isData () const
bool isText () const
bool isInternal () const
bool isUndefined () const
bool isExported () const
bool isRexported () const
bool isVerified () const
void setVerify (bool V=true)
StringRef getName () const
SymbolFlags getFlags () const
Additional Inherited Members
Protected Attributes inherited from llvm::MachO::Record
StringRef Name
RecordLinkage Linkage
SymbolFlags Flags
bool Verified
Detailed Description
Definition at line 192 of file Record.h.
Constructor & Destructor Documentation
ObjCInterfaceRecord()
llvm::MachO::ObjCInterfaceRecord::ObjCInterfaceRecord (StringRef Name, RecordLinkage Linkage, ObjCIFSymbolKind SymType) inline
Definition at line 194 of file Record.h.
References llvm::MachO::Record::Linkage, llvm::MachO::Record::Name, llvm::MachO::ObjCContainerRecord::ObjCContainerRecord(), and updateLinkageForSymbols().
Member Function Documentation
addObjCCategory()
bool ObjCInterfaceRecord::addObjCCategory (ObjCCategoryRecord * Record)
Definition at line 220 of file RecordsSlice.cpp.
References llvm::MachO::Record::Name.
getLinkageForSymbol()
RecordLinkage ObjCInterfaceRecord::getLinkageForSymbol (ObjCIFSymbolKind CurrType) const
Definition at line 99 of file RecordsSlice.cpp.
References assert(), llvm::MachO::Class, llvm::MachO::EHType, llvm_unreachable, and llvm::MachO::MetaClass.
Referenced by isExportedSymbol().
getObjCCategories()
std::vector< ObjCCategoryRecord * > ObjCInterfaceRecord::getObjCCategories () const
Definition at line 252 of file RecordsSlice.cpp.
Referenced by llvm::MachO::SymbolConverter::visitObjCInterface().
hasExceptionAttribute()
bool llvm::MachO::ObjCInterfaceRecord::hasExceptionAttribute () const inline
Definition at line 200 of file Record.h.
References llvm::MachO::Unknown.
Referenced by llvm::MachO::SymbolConverter::visitObjCInterface().
isCompleteInterface()
bool llvm::MachO::ObjCInterfaceRecord::isCompleteInterface () const inline
Definition at line 203 of file Record.h.
References llvm::MachO::Rexported.
Referenced by llvm::MachO::SymbolConverter::visitObjCInterface().
isExportedSymbol()
bool llvm::MachO::ObjCInterfaceRecord::isExportedSymbol (ObjCIFSymbolKind CurrType) const inline
Definition at line 207 of file Record.h.
References getLinkageForSymbol(), and llvm::MachO::Rexported.
Referenced by llvm::MachO::SymbolConverter::visitObjCInterface().
updateLinkageForSymbols()
void ObjCInterfaceRecord::updateLinkageForSymbols (ObjCIFSymbolKind SymType, RecordLinkage Link)
Definition at line 114 of file RecordsSlice.cpp.
References llvm::MachO::Class, llvm::MachO::EHType, llvm::MachO::Record::Linkage, and llvm::MachO::MetaClass.
Referenced by ObjCInterfaceRecord().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/Record.h
lib/TextAPI/RecordsSlice.cpp