LLVM: llvm::MemTransferBase< BaseCL > Class Template Reference
llvm::MemTransferBase< BaseCL > Class Template Reference
Common base class for all memory transfer intrinsics.
#include "llvm/IR/IntrinsicInst.h"
Public Member Functions
Value * getRawSource () const
Return the arguments to the instruction.
const Use & getRawSourceUse () const
Use & getRawSourceUse ()
Value * getSource () const
This is just like getRawSource, but it strips off any cast instructions that feed it, giving the original input.
unsigned getSourceAddressSpace () const
MaybeAlign getSourceAlign () const
void setSource (Value *Ptr)
void setSourceAlignment (MaybeAlign Alignment)
void setSourceAlignment (Align Alignment)
Detailed Description
template<class BaseCL>
class llvm::MemTransferBase< BaseCL >
Common base class for all memory transfer intrinsics.
Simply provides common methods.
Definition at line 1066 of file IntrinsicInst.h.
Member Function Documentation
getRawSource()
template<class BaseCL> Value * llvm::MemTransferBase< BaseCL >::getRawSource () const inline
Return the arguments to the instruction.
Definition at line 1072 of file IntrinsicInst.h.
Referenced by canOverlap(), llvm::expandAtomicMemCpyAsLoop(), llvm::expandMemCpyAsLoop(), llvm::expandMemMoveAsLoop(), llvm::MemoryLocation::getForSource(), getSource(), getSourceAddressSpace(), and setSource().
getRawSourceUse() [1/2]
template<class BaseCL> Use & llvm::MemTransferBase< BaseCL >::getRawSourceUse () inline
Definition at line 1078 of file IntrinsicInst.h.
getRawSourceUse() [2/2]
template<class BaseCL> const Use & llvm::MemTransferBase< BaseCL >::getRawSourceUse () const inline
Definition at line 1075 of file IntrinsicInst.h.
getSource()
template<class BaseCL> Value * llvm::MemTransferBase< BaseCL >::getSource () const inline
This is just like getRawSource, but it strips off any cast instructions that feed it, giving the original input.
The returned value is guaranteed to be a pointer.
Definition at line 1083 of file IntrinsicInst.h.
References getRawSource(), and llvm::Value::stripPointerCasts().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), expandMemCpy(), llvm::VNCoercion::getConstantMemInstValueForLoad(), llvm::VNCoercion::getMemInstValueForLoad(), and overreadUndefContents().
getSourceAddressSpace()
template<class BaseCL> unsigned llvm::MemTransferBase< BaseCL >::getSourceAddressSpace () const inline
Definition at line 1085 of file IntrinsicInst.h.
References llvm::cast(), getRawSource(), and getType().
getSourceAlign()
template<class BaseCL> MaybeAlign llvm::MemTransferBase< BaseCL >::getSourceAlign () const inline
Definition at line 1089 of file IntrinsicInst.h.
Referenced by llvm::expandAtomicMemCpyAsLoop(), llvm::expandMemCpyAsLoop(), and llvm::expandMemMoveAsLoop().
setSource()
template<class BaseCL> void llvm::MemTransferBase< BaseCL >::setSource (Value * Ptr) inline
Definition at line 1093 of file IntrinsicInst.h.
References assert(), getRawSource(), getType(), and llvm::Value::getType().
setSourceAlignment() [1/2]
template<class BaseCL> void llvm::MemTransferBase< BaseCL >::setSourceAlignment (Align Alignment) inline
Definition at line 1106 of file IntrinsicInst.h.
References llvm::Attribute::getWithAlignment().
setSourceAlignment() [2/2]
template<class BaseCL> void llvm::MemTransferBase< BaseCL >::setSourceAlignment (MaybeAlign Alignment) inline
Definition at line 1099 of file IntrinsicInst.h.
References llvm::Attribute::getWithAlignment().
The documentation for this class was generated from the following file:
include/llvm/IR/IntrinsicInst.h