LLVM: llvm::DXILMetadataAnalysisWrapperPass Class Reference
llvm::DXILMetadataAnalysisWrapperPass Class Reference
Legacy pass.
#include "llvm/Analysis/DXILMetadataAnalysis.h"
Public Member Functions
DXILMetadataAnalysisWrapperPass ()
~DXILMetadataAnalysisWrapperPass () override
const dxil::ModuleMetadataInfo & getModuleMetadata () const
dxil::ModuleMetadataInfo & getModuleMetadata ()
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool runOnModule (Module &M) override
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void print (raw_ostream &OS, const Module *M) const override
print - Print out the internal state of the pass.
void dump () const
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
StringRef getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (const Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Legacy pass.
Definition at line 74 of file DXILMetadataAnalysis.h.
Constructor & Destructor Documentation
DXILMetadataAnalysisWrapperPass()
DXILMetadataAnalysisWrapperPass::DXILMetadataAnalysisWrapperPass ()
Definition at line 127 of file DXILMetadataAnalysis.cpp.
References ID, and llvm::ModulePass::ModulePass().
~DXILMetadataAnalysisWrapperPass()
DXILMetadataAnalysisWrapperPass::~DXILMetadataAnalysisWrapperPass () override default
Member Function Documentation
dump()
LLVM_DUMP_METHOD void DXILMetadataAnalysisWrapperPass::dump () const
Definition at line 155 of file DXILMetadataAnalysis.cpp.
References llvm::dbgs(), and print().
getAnalysisUsage()
void DXILMetadataAnalysisWrapperPass::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 132 of file DXILMetadataAnalysis.cpp.
References llvm::AnalysisUsage::setPreservesAll().
getModuleMetadata() [1/2]
dxil::ModuleMetadataInfo & llvm::DXILMetadataAnalysisWrapperPass::getModuleMetadata () inline
Definition at line 86 of file DXILMetadataAnalysis.h.
getModuleMetadata() [2/2]
const dxil::ModuleMetadataInfo & llvm::DXILMetadataAnalysisWrapperPass::getModuleMetadata () const inline
Definition at line 83 of file DXILMetadataAnalysis.h.
print()
void DXILMetadataAnalysisWrapperPass::print (raw_ostream & OS, const Module * M) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 144 of file DXILMetadataAnalysis.cpp.
References llvm::dbgs().
Referenced by dump().
releaseMemory()
void DXILMetadataAnalysisWrapperPass::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 142 of file DXILMetadataAnalysis.cpp.
runOnModule()
bool DXILMetadataAnalysisWrapperPass::runOnModule (Module & M) override virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 137 of file DXILMetadataAnalysis.cpp.
References collectMetadataInfo().
Member Data Documentation
ID
char llvm::DXILMetadataAnalysisWrapperPass::ID static
Definition at line 78 of file DXILMetadataAnalysis.h.
Referenced by DXILMetadataAnalysisWrapperPass().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILMetadataAnalysis.h
lib/Analysis/DXILMetadataAnalysis.cpp