LLVM: llvm::pdb::VTableLayoutItem Class Reference
llvm::pdb::VTableLayoutItem Class Reference
#include "llvm/DebugInfo/PDB/UDTLayout.h"
Public Member Functions
LLVM_ABI VTableLayoutItem (const UDTLayoutBase &Parent, std::unique_ptr< PDBSymbolTypeVTable > VTable)
uint32_t getElementSize () const
Public Member Functions inherited from llvm::pdb::LayoutItemBase
LayoutItemBase (const UDTLayoutBase *Parent, const PDBSymbol *Symbol, const std::string &Name, uint32_t OffsetInParent, uint32_t Size, bool IsElided)
virtual ~LayoutItemBase ()=default
uint32_t deepPaddingSize () const
virtual uint32_t immediatePadding () const
virtual uint32_t tailPadding () const
const UDTLayoutBase * getParent () const
StringRef getName () const
uint32_t getOffsetInParent () const
uint32_t getSize () const
uint32_t getLayoutSize () const
const PDBSymbol * getSymbol () const
const BitVector & usedBytes () const
bool isElided () const
virtual bool isVBPtr () const
uint32_t containsOffset (uint32_t Off) const
Additional Inherited Members
Protected Attributes inherited from llvm::pdb::LayoutItemBase
const PDBSymbol * Symbol = nullptr
const UDTLayoutBase * Parent = nullptr
BitVector UsedBytes
std::string Name
uint32_t OffsetInParent = 0
uint32_t SizeOf = 0
uint32_t LayoutSize = 0
bool IsElided = false
Detailed Description
Definition at line 100 of file UDTLayout.h.
Constructor & Destructor Documentation
VTableLayoutItem()
VTableLayoutItem::VTableLayoutItem (const UDTLayoutBase & Parent, std::unique_ptr< PDBSymbolTypeVTable > VTable)
Definition at line 98 of file UDTLayout.cpp.
References llvm::cast(), llvm::get(), getTypeLength(), llvm::pdb::LayoutItemBase::LayoutItemBase(), llvm::move(), and llvm::pdb::LayoutItemBase::Parent.
Member Function Documentation
getElementSize()
uint32_t llvm::pdb::VTableLayoutItem::getElementSize () const inline
Definition at line 105 of file UDTLayout.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/UDTLayout.h
lib/DebugInfo/PDB/UDTLayout.cpp