LLVM: llvm::jitlink::x86::PLTTableManager Class Reference
llvm::jitlink::x86::PLTTableManager Class Reference
Procedure Linkage Table Builder.
#include "llvm/ExecutionEngine/JITLink/x86.h"
Public Member Functions
PLTTableManager (GOTTableManager &GOT)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Section & getStubsSection (LinkGraph &G)
Public Member Functions inherited from llvm::jitlink::TableManager< PLTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Public Attributes
GOTTableManager & GOT
Section * PLTSection = nullptr
Detailed Description
Procedure Linkage Table Builder.
Definition at line 364 of file x86.h.
Constructor & Destructor Documentation
PLTTableManager()
llvm::jitlink::x86::PLTTableManager::PLTTableManager (GOTTableManager & GOT) inline
Definition at line 366 of file x86.h.
References GOT.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::x86::PLTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 386 of file x86.h.
References llvm::jitlink::x86::createAnonymousPointerJumpStub(), G, getStubsSection(), and GOT.
getSectionName()
StringRef llvm::jitlink::x86::PLTTableManager::getSectionName () inline static
Definition at line 368 of file x86.h.
Referenced by getStubsSection().
getStubsSection()
Section & llvm::jitlink::x86::PLTTableManager::getStubsSection (LinkGraph & G) inline
Definition at line 392 of file x86.h.
References llvm::orc::Exec, G, getSectionName(), PLTSection, and llvm::orc::Read.
Referenced by createEntry().
visitEdge()
bool llvm::jitlink::x86::PLTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 370 of file x86.h.
References B(), llvm::jitlink::x86::BranchPCRel32, llvm::jitlink::x86::BranchPCRel32ToPtrJumpStubBypassable, llvm::dbgs(), DEBUG_WITH_TYPE, E(), llvm::formatv(), G, and llvm::jitlink::TableManager< PLTTableManager >::getEntryForTarget().
Member Data Documentation
GOT
GOTTableManager& llvm::jitlink::x86::PLTTableManager::GOT
Definition at line 399 of file x86.h.
Referenced by createEntry(), and PLTTableManager().
PLTSection
Section* llvm::jitlink::x86::PLTTableManager::PLTSection = nullptr
Definition at line 400 of file x86.h.
Referenced by getStubsSection().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/x86.h