LLVM: llvm::hlsl::rootsig::MetadataParser Class Reference
llvm::hlsl::rootsig::MetadataParser Class Reference
#include "llvm/Frontend/HLSL/RootSignatureMetadata.h"
Public Member Functions
MetadataParser (MDNode *Root)
LLVM_ABI llvm::Expected< llvm::mcdxbc::RootSignatureDesc > ParseRootSignature (uint32_t Version)
Detailed Description
Definition at line 81 of file RootSignatureMetadata.h.
Constructor & Destructor Documentation
MetadataParser()
llvm::hlsl::rootsig::MetadataParser::MetadataParser (MDNode * Root) inline
Definition at line 83 of file RootSignatureMetadata.h.
Member Function Documentation
ParseRootSignature()
Expected< mcdxbc::RootSignatureDesc > llvm::hlsl::rootsig::MetadataParser::ParseRootSignature (uint32_t Version)
Definition at line 766 of file RootSignatureMetadata.cpp.
References llvm::dyn_cast(), llvm::formatv(), llvm::joinErrors(), llvm::Error::success(), llvm::mcdxbc::RootSignatureDesc::Version, and llvm::Version.
Referenced by analyzeModule().
The documentation for this class was generated from the following files:
include/llvm/Frontend/HLSL/RootSignatureMetadata.h
lib/Frontend/HLSL/RootSignatureMetadata.cpp