LLVM: llvm::AddressProbesMap Class Reference
llvm::AddressProbesMap Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
auto find (uint64_t From, uint64_t To) const
auto find (uint64_t Address) const
Detailed Description
Definition at line 225 of file MCPseudoProbe.h.
Member Function Documentation
find() [1/2]
auto llvm::AddressProbesMap::find (uint64_t Address) const inline
Definition at line 240 of file MCPseudoProbe.h.
References llvm::end(), and llvm::make_range().
find() [2/2]
auto llvm::AddressProbesMap::find (uint64_t From, uint64_t To) const inline
Definition at line 236 of file MCPseudoProbe.h.
References llvm::make_range().
The documentation for this class was generated from the following file:
include/llvm/MC/MCPseudoProbe.h