LLVM: llvm::jitlink::SimpleSegmentAlloc Class Reference
llvm::jitlink::SimpleSegmentAlloc Class Reference
A utility class for making simple allocations using JITLinkMemoryManager.
#include "llvm/ExecutionEngine/JITLink/JITLinkMemoryManager.h"
Classes
struct Segment
Describes a segment to be allocated.
struct SegmentInfo
Describes the segment working memory and executor address.
Public Types
using SegmentMap = orc::AllocGroupSmallMap<Segment>
using OnCreatedFunction = unique_function<void(Expected<SimpleSegmentAlloc>)>
using OnFinalizedFunction
using OnAbandonedFunction = unique_function<void(Error)>
Public Member Functions
LLVM_ABI SimpleSegmentAlloc (SimpleSegmentAlloc &&)
LLVM_ABI SimpleSegmentAlloc & operator= (SimpleSegmentAlloc &&)
LLVM_ABI ~SimpleSegmentAlloc ()
LLVM_ABI SegmentInfo getSegInfo (orc::AllocGroup AG)
Returns the SegmentInfo for the given group.
void finalize (OnFinalizedFunction OnFinalized)
Finalize all groups (async version).
Expected< JITLinkMemoryManager::FinalizedAlloc > finalize ()
Finalize all groups.
void abandon (OnAbandonedFunction OnAbandoned)
Free allocated memory if finalize won't be called.
Static Public Member Functions
static LLVM_ABI void Create (JITLinkMemoryManager &MemMgr, std::shared_ptr< orc::SymbolStringPool > SSP, Triple TT, const JITLinkDylib *JD, SegmentMap Segments, OnCreatedFunction OnCreated)
static LLVM_ABI Expected< SimpleSegmentAlloc > Create (JITLinkMemoryManager &MemMgr, std::shared_ptr< orc::SymbolStringPool > SSP, Triple TT, const JITLinkDylib *JD, SegmentMap Segments)
Detailed Description
A utility class for making simple allocations using JITLinkMemoryManager.
SimpleSegementAlloc takes a mapping of AllocGroups to Segments and uses this to create a LinkGraph with one Section (containing one Block) per Segment. Clients can obtain a pointer to the working memory and executor address of that block using the Segment's AllocGroup. Once memory has been populated, clients can call finalize to finalize the memory.
Note: Segments with MemLifetime::NoAlloc are not permitted, since they would not be useful, and their presence is likely to indicate a bug.
Definition at line 299 of file JITLinkMemoryManager.h.
Member Typedef Documentation
OnAbandonedFunction
using llvm::jitlink::SimpleSegmentAlloc::OnAbandonedFunction = unique_function<void(Error)>
Definition at line 324 of file JITLinkMemoryManager.h.
OnCreatedFunction
using llvm::jitlink::SimpleSegmentAlloc::OnCreatedFunction = unique_function<void(Expected<SimpleSegmentAlloc>)>
Definition at line 319 of file JITLinkMemoryManager.h.
OnFinalizedFunction
using llvm::jitlink::SimpleSegmentAlloc::OnFinalizedFunction
Initial value:
JITLinkMemoryManager::InFlightAlloc::OnFinalizedFunction
Definition at line 321 of file JITLinkMemoryManager.h.
SegmentMap
using llvm::jitlink::SimpleSegmentAlloc::SegmentMap = orc::AllocGroupSmallMap<Segment>
Definition at line 317 of file JITLinkMemoryManager.h.
Constructor & Destructor Documentation
SimpleSegmentAlloc()
llvm::jitlink::SimpleSegmentAlloc::SimpleSegmentAlloc (SimpleSegmentAlloc &&) default
References LLVM_ABI, and SimpleSegmentAlloc().
Referenced by Create(), operator=(), and SimpleSegmentAlloc().
~SimpleSegmentAlloc()
llvm::jitlink::SimpleSegmentAlloc::~SimpleSegmentAlloc () default
References LLVM_ABI.
Member Function Documentation
abandon()
void llvm::jitlink::SimpleSegmentAlloc::abandon (OnAbandonedFunction OnAbandoned) inline
Free allocated memory if finalize won't be called.
Definition at line 354 of file JITLinkMemoryManager.h.
Create() [1/2]
Expected< SimpleSegmentAlloc > llvm::jitlink::SimpleSegmentAlloc::Create (JITLinkMemoryManager & MemMgr, std::shared_ptr< orc::SymbolStringPool > SSP, Triple TT, const JITLinkDylib * JD, SegmentMap Segments) static
Definition at line 206 of file JITLinkMemoryManager.cpp.
References Create().
Create() [2/2]
void llvm::jitlink::SimpleSegmentAlloc::Create (JITLinkMemoryManager & MemMgr, std::shared_ptr< orc::SymbolStringPool > SSP, Triple TT, const JITLinkDylib * JD, SegmentMap Segments, OnCreatedFunction OnCreated) static
Definition at line 146 of file JITLinkMemoryManager.cpp.
References llvm::alignTo(), llvm::jitlink::JITLinkMemoryManager::allocate(), assert(), B(), Create(), llvm::jitlink::getGenericEdgeKindName(), llvm::orc::ExecutorAddr::getValue(), llvm::orc::NoAlloc, llvm::orc::AllocGroup::NumGroups, and SimpleSegmentAlloc().
Referenced by Create(), Create(), and llvm::orc::ELFDebugObjectPlugin::notifyMaterializing().
finalize() [1/2]
Expected< JITLinkMemoryManager::FinalizedAlloc > llvm::jitlink::SimpleSegmentAlloc::finalize () inline
Finalize all groups.
Definition at line 349 of file JITLinkMemoryManager.h.
finalize() [2/2]
void llvm::jitlink::SimpleSegmentAlloc::finalize (OnFinalizedFunction OnFinalized) inline
Finalize all groups (async version).
Definition at line 344 of file JITLinkMemoryManager.h.
getSegInfo()
SimpleSegmentAlloc::SegmentInfo llvm::jitlink::SimpleSegmentAlloc::getSegInfo (orc::AllocGroup AG)
Returns the SegmentInfo for the given group.
Definition at line 224 of file JITLinkMemoryManager.cpp.
References B(), getSegInfo(), and I.
Referenced by getSegInfo(), and llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
operator=()
SimpleSegmentAlloc & llvm::jitlink::SimpleSegmentAlloc::operator= (SimpleSegmentAlloc &&) default
References LLVM_ABI, and SimpleSegmentAlloc().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLinkMemoryManager.h
lib/ExecutionEngine/JITLink/JITLinkMemoryManager.cpp