LLVM: llvm::BlockToIndexMapping Class Reference
llvm::BlockToIndexMapping Class Reference
#include "llvm/Transforms/Coroutines/SuspendCrossingInfo.h"
Public Member Functions
size_t size () const
BlockToIndexMapping (Function &F)
size_t blockToIndex (BasicBlock const *BB) const
BasicBlock * indexToBlock (unsigned Index) const
Detailed Description
Definition at line 32 of file SuspendCrossingInfo.h.
Constructor & Destructor Documentation
BlockToIndexMapping()
llvm::BlockToIndexMapping::BlockToIndexMapping (Function & F) inline
Definition at line 38 of file SuspendCrossingInfo.h.
References F, and llvm::sort().
Member Function Documentation
blockToIndex()
size_t llvm::BlockToIndexMapping::blockToIndex (BasicBlock const * BB) const inline
Definition at line 44 of file SuspendCrossingInfo.h.
References assert(), I, and llvm::lower_bound().
indexToBlock()
BasicBlock * llvm::BlockToIndexMapping::indexToBlock (unsigned Index) const inline
Definition at line 50 of file SuspendCrossingInfo.h.
size()
size_t llvm::BlockToIndexMapping::size () const inline
Definition at line 36 of file SuspendCrossingInfo.h.
The documentation for this class was generated from the following file:
include/llvm/Transforms/Coroutines/SuspendCrossingInfo.h