LLVM: llvm::FunctionToMachineFunctionPassAdaptor Class Reference
llvm::FunctionToMachineFunctionPassAdaptor Class Reference
#include "llvm/CodeGen/MachinePassManager.h"
Public Types
using PassConceptT
Public Member Functions
FunctionToMachineFunctionPassAdaptor (std::unique_ptr< PassConceptT > Pass)
LLVM_ABI PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Runs the function pass across every function in the function.
LLVM_ABI void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< FunctionToMachineFunctionPassAdaptor >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< FunctionToMachineFunctionPassAdaptor >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 191 of file MachinePassManager.h.
Member Typedef Documentation
PassConceptT
using llvm::FunctionToMachineFunctionPassAdaptor::PassConceptT
Initial value:
detail::PassConcept<MachineFunction, MachineFunctionAnalysisManager>
Definition at line 194 of file MachinePassManager.h.
Constructor & Destructor Documentation
FunctionToMachineFunctionPassAdaptor()
llvm::FunctionToMachineFunctionPassAdaptor::FunctionToMachineFunctionPassAdaptor (std::unique_ptr< PassConceptT > Pass) inline explicit
Definition at line 197 of file MachinePassManager.h.
References llvm::move().
Member Function Documentation
isRequired()
bool llvm::FunctionToMachineFunctionPassAdaptor::isRequired () inline static
Definition at line 207 of file MachinePassManager.h.
printPipeline()
void FunctionToMachineFunctionPassAdaptor::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 136 of file MachinePassManager.cpp.
run()
PreservedAnalyses FunctionToMachineFunctionPassAdaptor::run (Function & F, FunctionAnalysisManager & FAM)
Runs the function pass across every function in the function.
Definition at line 112 of file MachinePassManager.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::PassInstrumentation::runAfterPass(), and llvm::PassInstrumentation::runBeforePass().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePassManager.h
lib/CodeGen/MachinePassManager.cpp