LLVM: llvm::CodeGenPassBuilder< DerivedT, TargetMachineT > Class Template Reference
llvm::CodeGenPassBuilder< DerivedT, TargetMachineT > Class Template Reference
This class provides access to building LLVM's passes.
#include "llvm/Passes/CodeGenPassBuilder.h"
Public Member Functions
CodeGenPassBuilder (TargetMachineT &TM, const CGPassBuilderOption &Opts, PassInstrumentationCallbacks *PIC)
Error buildPipeline (ModulePassManager &MPM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType) const
PassInstrumentationCallbacks * getPassInstrumentationCallbacks () const
Protected Types
template<typename PassT>
using is_module_pass_t
template<typename PassT>
using is_function_pass_t
template<typename PassT>
using is_machine_function_pass_t
using CreateMCStreamer
Protected Member Functions
template<typename PassT>
void addFunctionPass (PassT &&Pass, PassManagerWrapper &PMW, bool Force=false, StringRef Name=PassT::name()) const
template<typename PassT>
void addModulePass (PassT &&Pass, PassManagerWrapper &PMW, bool Force=false, StringRef Name=PassT::name()) const
template<typename PassT>
void addMachineFunctionPass (PassT &&Pass, PassManagerWrapper &PMW, bool Force=false, StringRef Name=PassT::name()) const
void flushFPMsToMPM (PassManagerWrapper &PMW, bool FreeMachineFunctions=false) const
void requireCGSCCOrder (PassManagerWrapper &PMW) const
void stopAddingInCGSCCOrder (PassManagerWrapper &PMW) const
template<typename TMC>
TMC & getTM () const
CodeGenOptLevel getOptLevel () const
bool isGlobalISelAbortEnabled () const
Check whether or not GlobalISel should abort on error.
bool reportDiagnosticWhenGlobalISelFallback () const
Check whether or not a diagnostic should be emitted when GlobalISel uses the fallback path.
Error addInstSelector (PassManagerWrapper &PMW) const
addInstSelector - This method should install an instruction selector pass, which converts from LLVM code to machine instructions.
void addGlobalMergePass (PassManagerWrapper &PMW) const
Target can override this to add GlobalMergePass before all IR passes.
void addILPOpts (PassManagerWrapper &PMW) const
Add passes that optimize instruction level parallelism for out-of-order targets.
void addPreRegAlloc (PassManagerWrapper &PMW) const
This method may be implemented by targets that want to run passes immediately before register allocation.
void addPreRewrite (PassManagerWrapper &PMW) const
addPreRewrite - Add passes to the optimized register allocation pipeline after register allocation is complete, but before virtual registers are rewritten to physical registers.
void addPostRewrite (PassManagerWrapper &PMW) const
Add passes to be run immediately after virtual registers are rewritten to physical registers.
void addPostRegAlloc (PassManagerWrapper &PMW) const
This method may be implemented by targets that want to run passes after register allocation pass pipeline but before prolog-epilog insertion.
void addPreSched2 (PassManagerWrapper &PMW) const
This method may be implemented by targets that want to run passes after prolog-epilog insertion and before the second instruction scheduling pass.
void addPreEmitPass (PassManagerWrapper &PMW) const
This pass may be implemented by targets that want to run passes immediately before machine code is emitted.
void addPreEmitPass2 (PassManagerWrapper &PMW) const
Targets may add passes immediately before machine code is emitted in this callback.
void addPreISel (PassManagerWrapper &PMW) const
{{@ For GlobalISel
Error addIRTranslator (PassManagerWrapper &PMW) const
This method should install an IR translator pass, which converts from LLVM code to machine instructions with possibly generic opcodes.
void addPreLegalizeMachineIR (PassManagerWrapper &PMW) const
This method may be implemented by targets that want to run passes immediately before legalization.
Error addLegalizeMachineIR (PassManagerWrapper &PMW) const
This method should install a legalize pass, which converts the instruction sequence into one that can be selected by the target.
void addPreRegBankSelect (PassManagerWrapper &PMW) const
This method may be implemented by targets that want to run passes immediately before the register bank selection.
Error addRegBankSelect (PassManagerWrapper &PMW) const
This method should install a register bank selector pass, which assigns register banks to virtual registers without a register class or register banks.
void addPreGlobalInstructionSelect (PassManagerWrapper &PMW) const
This method may be implemented by targets that want to run passes immediately before the (global) instruction selection.
Error addGlobalInstructionSelect (PassManagerWrapper &PMWM) const
This method should install a (global) instruction selector pass, which converts possibly generic instructions to fully target-specific instructions, thereby constraining all generic virtual registers to register classes.
void addISelPasses (PassManagerWrapper &PMW) const
High level function that adds all passes necessary to go from llvm IR representation to the MI representation.
Error addCoreISelPasses (PassManagerWrapper &PMW) const
Add the actual instruction selection passes.
Error addMachinePasses (PassManagerWrapper &PMW) const
Add the complete, standard set of LLVM CodeGen passes.
void addPassesToHandleExceptions (PassManagerWrapper &PMW) const
Add passes to lower exception handling for the code generator.
void addIRPasses (PassManagerWrapper &PMW) const
Add common target configurable passes that perform LLVM IR to IR transforms following machine independent optimization.
void addCodeGenPrepare (PassManagerWrapper &PMW) const
Add pass to prepare the LLVM IR for code generation.
void addISelPrepare (PassManagerWrapper &PMW) const
Add common passes that perform LLVM IR to IR transforms in preparation for instruction selection.
void addMachineSSAOptimization (PassManagerWrapper &PMW) const
Methods with trivial inline returns are convenient points in the common codegen pass pipeline where targets may insert passes.
Error addFastRegAlloc (PassManagerWrapper &PMW) const
addFastRegAlloc - Add the minimum set of target-independent passes that are required for fast register allocation.
void addOptimizedRegAlloc (PassManagerWrapper &PMW) const
addOptimizedRegAlloc - Add passes related to register allocation.
void addMachineLateOptimization (PassManagerWrapper &PMW) const
Add passes that optimize machine instructions after register allocation.
void addGCPasses (PassManagerWrapper &PMW) const
addGCPasses - Add late codegen passes that analyze code for garbage collection.
void addBlockPlacement (PassManagerWrapper &PMW) const
Add standard basic block placement passes.
void addPostBBSections (PassManagerWrapper &PMW) const
void addAsmPrinter (PassManagerWrapper &PMW, CreateMCStreamer) const
void addTargetRegisterAllocator (PassManagerWrapper &PMW, bool Optimized) const
Utilities for targets to add passes to the pass manager.
void addRegAllocPass (PassManagerWrapper &PMW, bool Optimized) const
addMachinePasses helper to create the target-selected or overriden regalloc pass.
Error addRegAssignmentFast (PassManagerWrapper &PMW) const
Add core register alloator passes which do the actual register assignment and rewriting.
Error addRegAssignmentOptimized (PassManagerWrapper &PMWM) const
template<typename... PassTs>
void disablePass ()
Allow the target to disable a specific pass by default.
template<typename TargetPassT, typename InsertedPassT>
void insertPass (InsertedPassT &&Pass) const
Insert InsertedPass pass after TargetPass pass.
Protected Attributes
TargetMachineT & TM
CGPassBuilderOption Opt
PassInstrumentationCallbacks * PIC
Detailed Description
template<typename DerivedT, typename TargetMachineT>
class llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >
This class provides access to building LLVM's passes.
Its members provide the baseline state available to passes during their construction. The MachinePassRegistry.def file specifies how to construct all of the built-in passes, and those may reference these members during construction.
Definition at line 173 of file CodeGenPassBuilder.h.
Member Typedef Documentation
CreateMCStreamer
template<typename DerivedT, typename TargetMachineT> using llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::CreateMCStreamer protected
Initial value:
std::function<Expected<std::unique_ptr<MCStreamer>>(MCContext &)>
Definition at line 490 of file CodeGenPassBuilder.h.
is_function_pass_t
template<typename DerivedT, typename TargetMachineT> template<typename PassT> using llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::is_function_pass_t protected
Initial value:
decltype(std::declval<PassT &>().run(
     std::declval<Function &>(), std::declval<FunctionAnalysisManager &>()))
Definition at line 212 of file CodeGenPassBuilder.h.
is_machine_function_pass_t
template<typename DerivedT, typename TargetMachineT> template<typename PassT> using llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::is_machine_function_pass_t protected
Initial value:
decltype(std::declval<PassT &>().run(
     std::declval<MachineFunction &>(),
     std::declval<MachineFunctionAnalysisManager &>()))
Definition at line 216 of file CodeGenPassBuilder.h.
is_module_pass_t
template<typename DerivedT, typename TargetMachineT> template<typename PassT> using llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::is_module_pass_t protected
Initial value:
decltype(std::declval<PassT &>().run(
     std::declval<Module &>(), std::declval<ModuleAnalysisManager &>()))
Definition at line 208 of file CodeGenPassBuilder.h.
Constructor & Destructor Documentation
CodeGenPassBuilder()
template<typename DerivedT, typename TargetMachineT> llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::CodeGenPassBuilder (TargetMachineT & TM, const CGPassBuilderOption & Opts, PassInstrumentationCallbacks * PIC) inline explicit
Definition at line 175 of file CodeGenPassBuilder.h.
Member Function Documentation
addAsmPrinter()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addAsmPrinter (PassManagerWrapper & PMW, CreateMCStreamer) const inline protected
Definition at line 492 of file CodeGenPassBuilder.h.
addBlockPlacement()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addBlockPlacement (PassManagerWrapper & PMW) const protected
Add standard basic block placement passes.
Definition at line 1300 of file CodeGenPassBuilder.h.
References addMachineFunctionPass(), and Opt.
addCodeGenPrepare()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addCodeGenPrepare (PassManagerWrapper & PMW) const protected
Add pass to prepare the LLVM IR for code generation.
This should be done before exception handling preparation passes.
Definition at line 820 of file CodeGenPassBuilder.h.
References addFunctionPass(), getOptLevel(), llvm::None, Opt, and TM.
addCoreISelPasses()
template<typename Derived, typename TargetMachineT> Error llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addCoreISelPasses (PassManagerWrapper & PMW) const protected
Add the actual instruction selection passes.
This does not include preparation passes on IR.
Definition at line 859 of file CodeGenPassBuilder.h.
References addGlobalInstructionSelect(), addInstSelector(), addIRTranslator(), addLegalizeMachineIR(), addMachineFunctionPass(), addRegBankSelect(), isGlobalISelAbortEnabled(), llvm::None, Opt, reportDiagnosticWhenGlobalISelFallback(), llvm::Error::success(), and TM.
Referenced by buildPipeline().
addFastRegAlloc()
template<typename Derived, typename TargetMachineT> Error llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addFastRegAlloc (PassManagerWrapper & PMW) const protected
addFastRegAlloc - Add the minimum set of target-independent passes that are required for fast register allocation.
Add the minimum set of target-independent passes that are required for register allocation.
No coalescing or scheduling.
Definition at line 1198 of file CodeGenPassBuilder.h.
References addMachineFunctionPass().
Referenced by addMachinePasses().
addFunctionPass()
template<typename DerivedT, typename TargetMachineT> template<typename PassT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addFunctionPass (PassT && Pass, PassManagerWrapper & PMW, bool Force = false, StringRef Name = PassT::name()) const inline protected
Definition at line 221 of file CodeGenPassBuilder.h.
Referenced by addCodeGenPrepare(), addIRPasses(), addISelPasses(), addISelPrepare(), and addPassesToHandleExceptions().
addGCPasses()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addGCPasses (PassManagerWrapper & PMW) const inline protected
addGCPasses - Add late codegen passes that analyze code for garbage collection.
This should return true if GC info should be printed after these passes.
Definition at line 483 of file CodeGenPassBuilder.h.
addGlobalInstructionSelect()
template<typename DerivedT, typename TargetMachineT> Error llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addGlobalInstructionSelect (PassManagerWrapper & PMWM) const inline protected
This method should install a (global) instruction selector pass, which converts possibly generic instructions to fully target-specific instructions, thereby constraining all generic virtual registers to register classes.
Definition at line 421 of file CodeGenPassBuilder.h.
Referenced by addCoreISelPasses().
addGlobalMergePass()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addGlobalMergePass (PassManagerWrapper & PMW) const inline protected
Target can override this to add GlobalMergePass before all IR passes.
Definition at line 323 of file CodeGenPassBuilder.h.
addILPOpts()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addILPOpts (PassManagerWrapper & PMW) const inline protected
Add passes that optimize instruction level parallelism for out-of-order targets.
These passes are run while the machine code is still in SSA form, so they can use MachineTraceMetrics to control their heuristics.
All passes added here should preserve the MachineDominatorTree, MachineLoopInfo, and MachineTraceMetrics analyses.
Definition at line 331 of file CodeGenPassBuilder.h.
addInstSelector()
template<typename DerivedT, typename TargetMachineT> Error llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addInstSelector (PassManagerWrapper & PMW) const inline protected
addInstSelector - This method should install an instruction selector pass, which converts from LLVM code to machine instructions.
Definition at line 317 of file CodeGenPassBuilder.h.
Referenced by addCoreISelPasses().
addIRPasses()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addIRPasses (PassManagerWrapper & PMW) const protected
Add common target configurable passes that perform LLVM IR to IR transforms following machine independent optimization.
Definition at line 693 of file CodeGenPassBuilder.h.
References addFunctionPass(), addModulePass(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass(), llvm::createFunctionToLoopPassAdaptor(), flushFPMsToMPM(), getOptLevel(), llvm::PassInfoMixin< ShadowStackGCLoweringPass >::name(), llvm::None, Opt, and TM.
addIRTranslator()
template<typename DerivedT, typename TargetMachineT> Error llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addIRTranslator (PassManagerWrapper & PMW) const inline protected
This method should install an IR translator pass, which converts from LLVM code to machine instructions with possibly generic opcodes.
Definition at line 385 of file CodeGenPassBuilder.h.
Referenced by addCoreISelPasses().
addISelPasses()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addISelPasses (PassManagerWrapper & PMW) const protected
High level function that adds all passes necessary to go from llvm IR representation to the MI representation.
Adds IR based lowering and target specific optimization passes and finally the core instruction selection passes.
Definition at line 675 of file CodeGenPassBuilder.h.
References addFunctionPass(), addModulePass(), addPassesToHandleExceptions(), getOptLevel(), and TM.
Referenced by buildPipeline().
addISelPrepare()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addISelPrepare (PassManagerWrapper & PMW) const protected
Add common passes that perform LLVM IR to IR transforms in preparation for instruction selection.
Definition at line 831 of file CodeGenPassBuilder.h.
References addFunctionPass(), llvm::dbgs(), getOptLevel(), llvm::None, Opt, requireCGSCCOrder(), and TM.
addLegalizeMachineIR()
template<typename DerivedT, typename TargetMachineT> Error llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addLegalizeMachineIR (PassManagerWrapper & PMW) const inline protected
This method should install a legalize pass, which converts the instruction sequence into one that can be selected by the target.
Definition at line 396 of file CodeGenPassBuilder.h.
Referenced by addCoreISelPasses().
addMachineFunctionPass()
template<typename DerivedT, typename TargetMachineT> template<typename PassT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addMachineFunctionPass (PassT && Pass, PassManagerWrapper & PMW, bool Force = false, StringRef Name = PassT::name()) const inline protected
Definition at line 245 of file CodeGenPassBuilder.h.
Referenced by addBlockPlacement(), addCoreISelPasses(), addFastRegAlloc(), addMachineLateOptimization(), addMachinePasses(), addMachineSSAOptimization(), addOptimizedRegAlloc(), addRegAllocPass(), addRegAssignmentOptimized(), addTargetRegisterAllocator(), and buildPipeline().
addMachineLateOptimization()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addMachineLateOptimization (PassManagerWrapper & PMW) const protected
Add passes that optimize machine instructions after register allocation.
Post RegAlloc Pass Configuration.
Add passes that optimize machine instructions after register allocation.
Definition at line 1279 of file CodeGenPassBuilder.h.
References addMachineFunctionPass(), Opt, and TM.
addMachinePasses()
template<typename Derived, typename TargetMachineT> Error llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addMachinePasses (PassManagerWrapper & PMW) const protected
Add the complete, standard set of LLVM CodeGen passes.
Add the complete set of target-independent postISel code generator passes.
Fully developed targets will not generally override this.
This can be read as the standard order of major LLVM CodeGen stages. Stages with nontrivial configuration or multiple passes are broken out below in addStage routines.
Any CodeGenPassBuilder<Derived, TargetMachine>::addXX routine may be overriden by the Target. The addPre/Post methods with empty header implementations allow injecting target-specific fixups just before or after major stages. Additionally, targets have the flexibility to change pass order within a stage by overriding default implementation of addStage routines below. Each technique has maintainability tradeoffs because alternate pass orders are not well supported. addPre/Post works better if the target pass is easily tied to a common pass. But if it has subtle dependencies on multiple passes, the target should override the stage instead.
Add passes that optimize machine instructions after register allocation.
Definition at line 954 of file CodeGenPassBuilder.h.
References addFastRegAlloc(), addMachineFunctionPass(), addModulePass(), flushFPMsToMPM(), getOptLevel(), getTM(), llvm::NeverOutline, llvm::None, Opt, Options, llvm::Error::success(), llvm::TargetDefault, and TM.
Referenced by buildPipeline().
addMachineSSAOptimization()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addMachineSSAOptimization (PassManagerWrapper & PMW) const protected
Methods with trivial inline returns are convenient points in the common codegen pass pipeline where targets may insert passes.
Add passes that optimize machine instructions in SSA form.
Methods with out-of-line standard implementations are major CodeGen stages called by addMachinePasses. Some targets may override major stages when inserting passes is insufficient, but maintaining overriden stages is more work. addMachineSSAOptimization - Add standard passes that optimize machine instructions in SSA form.
Definition at line 1077 of file CodeGenPassBuilder.h.
References addMachineFunctionPass(), and Opt.
addModulePass()
template<typename DerivedT, typename TargetMachineT> template<typename PassT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addModulePass (PassT && Pass, PassManagerWrapper & PMW, bool Force = false, StringRef Name = PassT::name()) const inline protected
Definition at line 232 of file CodeGenPassBuilder.h.
Referenced by addIRPasses(), addISelPasses(), addMachinePasses(), and buildPipeline().
addOptimizedRegAlloc()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addOptimizedRegAlloc (PassManagerWrapper & PMW) const protected
addOptimizedRegAlloc - Add passes related to register allocation.
Add standard target-independent passes that are tightly coupled with optimized register allocation, including coalescing, machine instruction scheduling, and register allocation itself.
CodeGenTargetMachineImpl provides standard regalloc passes for most targets.
Definition at line 1209 of file CodeGenPassBuilder.h.
References addMachineFunctionPass(), addRegAssignmentOptimized(), Opt, and TM.
addPassesToHandleExceptions()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addPassesToHandleExceptions (PassManagerWrapper & PMW) const protected
Add passes to lower exception handling for the code generator.
Turn exception handling constructs into something the code generators can handle.
Definition at line 773 of file CodeGenPassBuilder.h.
References addFunctionPass(), llvm::AIX, llvm::ARM, assert(), llvm::DwarfCFI, llvm::MCAsmInfo::getExceptionHandlingType(), llvm::None, llvm::SjLj, TM, llvm::Wasm, llvm::WinEH, and llvm::ZOS.
Referenced by addISelPasses().
addPostBBSections()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPostBBSections (PassManagerWrapper & PMW) const inline protected
Definition at line 488 of file CodeGenPassBuilder.h.
addPostRegAlloc()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPostRegAlloc (PassManagerWrapper & PMW) const inline protected
This method may be implemented by targets that want to run passes after register allocation pass pipeline but before prolog-epilog insertion.
Definition at line 357 of file CodeGenPassBuilder.h.
addPostRewrite()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPostRewrite (PassManagerWrapper & PMW) const inline protected
Add passes to be run immediately after virtual registers are rewritten to physical registers.
Definition at line 353 of file CodeGenPassBuilder.h.
addPreEmitPass()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreEmitPass (PassManagerWrapper & PMW) const inline protected
This pass may be implemented by targets that want to run passes immediately before machine code is emitted.
Definition at line 365 of file CodeGenPassBuilder.h.
addPreEmitPass2()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreEmitPass2 (PassManagerWrapper & PMW) const inline protected
Targets may add passes immediately before machine code is emitted in this callback.
This is called even later than addPreEmitPass.
Definition at line 372 of file CodeGenPassBuilder.h.
addPreGlobalInstructionSelect()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreGlobalInstructionSelect (PassManagerWrapper & PMW) const inline protected
This method may be implemented by targets that want to run passes immediately before the (global) instruction selection.
Definition at line 415 of file CodeGenPassBuilder.h.
addPreISel()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreISel (PassManagerWrapper & PMW) const inline protected
{{@ For GlobalISel
addPreISel - This method should add any "last minute" LLVM->LLVM passes (which are run just before instruction selector).
Definition at line 379 of file CodeGenPassBuilder.h.
addPreLegalizeMachineIR()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreLegalizeMachineIR (PassManagerWrapper & PMW) const inline protected
This method may be implemented by targets that want to run passes immediately before legalization.
Definition at line 392 of file CodeGenPassBuilder.h.
addPreRegAlloc()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreRegAlloc (PassManagerWrapper & PMW) const inline protected
This method may be implemented by targets that want to run passes immediately before register allocation.
Definition at line 335 of file CodeGenPassBuilder.h.
addPreRegBankSelect()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreRegBankSelect (PassManagerWrapper & PMW) const inline protected
This method may be implemented by targets that want to run passes immediately before the register bank selection.
Definition at line 403 of file CodeGenPassBuilder.h.
addPreRewrite()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreRewrite (PassManagerWrapper & PMW) const inline protected
addPreRewrite - Add passes to the optimized register allocation pipeline after register allocation is complete, but before virtual registers are rewritten to physical registers.
These passes must preserve VirtRegMap and LiveIntervals, and when running after RABasic or RAGreedy, they should take advantage of LiveRegMatrix. When these passes run, VirtRegMap contains legal physreg assignments for all virtual registers.
Note if the target overloads addRegAssignAndRewriteOptimized, this may not be honored. This is also not generally used for the fast variant, where the allocation and rewriting are done in one pass.
Definition at line 349 of file CodeGenPassBuilder.h.
addPreSched2()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPreSched2 (PassManagerWrapper & PMW) const inline protected
This method may be implemented by targets that want to run passes after prolog-epilog insertion and before the second instruction scheduling pass.
Definition at line 361 of file CodeGenPassBuilder.h.
addRegAllocPass()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addRegAllocPass (PassManagerWrapper & PMW, bool Optimized) const protected
addMachinePasses helper to create the target-selected or overriden regalloc pass.
Find and instantiate the register allocation pass requested by this target at the current optimization level.
Different register allocators are defined as separate passes because they may require different analysis.
This helper ensures that the -regalloc-npm= option is always available, even for targets that override the default allocator.
Definition at line 1146 of file CodeGenPassBuilder.h.
References addMachineFunctionPass(), llvm::Default, llvm::Fast, llvm::Greedy, Opt, and llvm::reportFatalUsageError().
Referenced by addRegAssignmentFast(), and addRegAssignmentOptimized().
addRegAssignmentFast()
template<typename Derived, typename TargetMachineT> Error llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addRegAssignmentFast (PassManagerWrapper & PMW) const protected
Add core register alloator passes which do the actual register assignment and rewriting.
Returns
true if any passes were added.
Definition at line 1168 of file CodeGenPassBuilder.h.
References addRegAllocPass(), and llvm::Error::success().
addRegAssignmentOptimized()
template<typename Derived, typename TargetMachineT> Error llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addRegAssignmentOptimized (PassManagerWrapper & PMWM) const protected
Definition at line 1176 of file CodeGenPassBuilder.h.
References addMachineFunctionPass(), addRegAllocPass(), and llvm::Error::success().
Referenced by addOptimizedRegAlloc().
addRegBankSelect()
template<typename DerivedT, typename TargetMachineT> Error llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addRegBankSelect (PassManagerWrapper & PMW) const inline protected
This method should install a register bank selector pass, which assigns register banks to virtual registers without a register class or register banks.
Definition at line 408 of file CodeGenPassBuilder.h.
Referenced by addCoreISelPasses().
addTargetRegisterAllocator()
template<typename Derived, typename TargetMachineT> void llvm::CodeGenPassBuilder< Derived, TargetMachineT >::addTargetRegisterAllocator (PassManagerWrapper & PMW, bool Optimized) const protected
Utilities for targets to add passes to the pass manager.
Register Allocation Pass Configuration.
createTargetRegisterAllocator - Create the register allocator pass for this target at the current optimization level.
Instantiate the default register allocator pass for this target for either the optimized or unoptimized allocation path. This will be added to the pass manager by addFastRegAlloc in the unoptimized case or addOptimizedRegAlloc in the optimized case.
A target that uses the standard regalloc pass order for fast or optimized allocation may still override this for per-target regalloc selection. But -regalloc-npm=... always takes precedence. If a target does not want to allow users to set -regalloc-npm=... at all, check if Opt.RegAlloc == RegAllocType::Unset.
Definition at line 1131 of file CodeGenPassBuilder.h.
References addMachineFunctionPass().
buildPipeline()
template<typename Derived, typename TargetMachineT> Error llvm::CodeGenPassBuilder< Derived, TargetMachineT >::buildPipeline (ModulePassManager & MPM, raw_pwrite_stream & Out, raw_pwrite_stream * DwoOut, CodeGenFileType FileType) const
Definition at line 563 of file CodeGenPassBuilder.h.
References addCoreISelPasses(), addISelPasses(), addMachineFunctionPass(), addMachinePasses(), addModulePass(), flushFPMsToMPM(), llvm::TargetPassConfig::getStartStopInfo(), llvm::Null, Opt, PIC, and llvm::TargetPassConfig::willCompleteCodeGenPipeline().
Referenced by llvm::R600TargetMachine::buildCodeGenPipeline().
disablePass()
template<typename DerivedT, typename TargetMachineT> template<typename... PassTs> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::disablePass () inline protected
Allow the target to disable a specific pass by default.
Backend can declare unwanted passes in constructor.
Definition at line 515 of file CodeGenPassBuilder.h.
flushFPMsToMPM()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::flushFPMsToMPM (PassManagerWrapper & PMW, bool FreeMachineFunctions = false) const inline protected
Definition at line 258 of file CodeGenPassBuilder.h.
Referenced by addIRPasses(), addMachinePasses(), and buildPipeline().
getOptLevel()
template<typename DerivedT, typename TargetMachineT> CodeGenOptLevel llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::getOptLevel () const inline protected
Definition at line 299 of file CodeGenPassBuilder.h.
Referenced by addCodeGenPrepare(), addIRPasses(), addISelPasses(), addISelPrepare(), and addMachinePasses().
getPassInstrumentationCallbacks()
template<typename DerivedT, typename TargetMachineT> PassInstrumentationCallbacks * llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::getPassInstrumentationCallbacks () const inline
Definition at line 202 of file CodeGenPassBuilder.h.
getTM()
template<typename DerivedT, typename TargetMachineT> template<typename TMC> TMC & llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::getTM () const inline protected
Definition at line 298 of file CodeGenPassBuilder.h.
Referenced by addMachinePasses().
insertPass()
template<typename DerivedT, typename TargetMachineT> template<typename TargetPassT, typename InsertedPassT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::insertPass (InsertedPassT && Pass) const inline protected
Insert InsertedPass pass after TargetPass pass.
Only machine function passes are supported.
Definition at line 523 of file CodeGenPassBuilder.h.
isGlobalISelAbortEnabled()
template<typename DerivedT, typename TargetMachineT> bool llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::isGlobalISelAbortEnabled () const inline protected
Check whether or not GlobalISel should abort on error.
When this is disabled, GlobalISel will fall back on SDISel instead of erroring out.
Definition at line 304 of file CodeGenPassBuilder.h.
Referenced by addCoreISelPasses().
reportDiagnosticWhenGlobalISelFallback()
template<typename DerivedT, typename TargetMachineT> bool llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::reportDiagnosticWhenGlobalISelFallback () const inline protected
Check whether or not a diagnostic should be emitted when GlobalISel uses the fallback path.
In other words, it will emit a diagnostic when GlobalISel failed and isGlobalISelAbortEnabled is false.
Definition at line 311 of file CodeGenPassBuilder.h.
Referenced by addCoreISelPasses().
requireCGSCCOrder()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::requireCGSCCOrder (PassManagerWrapper & PMW) const inline protected
Definition at line 278 of file CodeGenPassBuilder.h.
Referenced by addISelPrepare().
stopAddingInCGSCCOrder()
template<typename DerivedT, typename TargetMachineT> void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::stopAddingInCGSCCOrder (PassManagerWrapper & PMW) const inline protected
Definition at line 286 of file CodeGenPassBuilder.h.
Member Data Documentation
Opt
template<typename DerivedT, typename TargetMachineT> CGPassBuilderOption llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::Opt protected
Definition at line 295 of file CodeGenPassBuilder.h.
Referenced by addBlockPlacement(), addCodeGenPrepare(), addCoreISelPasses(), addIRPasses(), addISelPrepare(), addMachineLateOptimization(), addMachinePasses(), addMachineSSAOptimization(), addOptimizedRegAlloc(), addRegAllocPass(), and buildPipeline().
PIC
template<typename DerivedT, typename TargetMachineT> PassInstrumentationCallbacks* llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::PIC protected
Definition at line 296 of file CodeGenPassBuilder.h.
Referenced by buildPipeline().
TM
template<typename DerivedT, typename TargetMachineT> TargetMachineT& llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::TM protected
Definition at line 294 of file CodeGenPassBuilder.h.
Referenced by addCodeGenPrepare(), addCoreISelPasses(), addIRPasses(), addISelPasses(), addISelPrepare(), addMachineLateOptimization(), addMachinePasses(), addOptimizedRegAlloc(), and addPassesToHandleExceptions().
The documentation for this class was generated from the following file:
include/llvm/Passes/CodeGenPassBuilder.h