LLVM: llvm::EscapeEnumerator Class Reference
llvm::EscapeEnumerator Class Reference
EscapeEnumerator - This is a little algorithm to find all escape points from a function so that "finally"-style code can be inserted.
#include "llvm/Transforms/Utils/EscapeEnumerator.h"
Public Member Functions
EscapeEnumerator (Function &F, const char *N="cleanup", bool HandleExceptions=true, DomTreeUpdater *DTU=nullptr)
IRBuilder * Next ()
Detailed Description
EscapeEnumerator - This is a little algorithm to find all escape points from a function so that "finally"-style code can be inserted.
In addition to finding the existing return and unwind instructions, it also (if necessary) transforms any call instructions into invokes and sends them to a landing pad.
Definition at line 29 of file EscapeEnumerator.h.
Constructor & Destructor Documentation
EscapeEnumerator()
llvm::EscapeEnumerator::EscapeEnumerator (Function & F, const char * N = "cleanup", bool HandleExceptions = true, DomTreeUpdater * DTU = nullptr) inline
Definition at line 41 of file EscapeEnumerator.h.
References llvm::begin(), llvm::end(), and N.
Member Function Documentation
Next()
IRBuilder * EscapeEnumerator::Next ()
Definition at line 30 of file EscapeEnumerator.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::classifyEHPersonality(), llvm::BasicBlock::Create(), llvm::LandingPadInst::Create(), llvm::ResumeInst::Create(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::StructType::get(), llvm::FunctionCallee::getCallee(), getDefaultPersonalityFn(), llvm::Type::getInt32Ty(), llvm::BasicBlock::getTerminatingMustTailCall(), llvm::BasicBlock::getTerminator(), llvm::PointerType::getUnqual(), I, II, llvm::isa(), llvm::isScopedEHPersonality(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::LandingPadInst::setCleanup(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/EscapeEnumerator.h
lib/Transforms/Utils/EscapeEnumerator.cpp