LLVM: llvm::SmallSetIterator< T, N, C > Class Template Reference
llvm::SmallSetIterator< T, N, C > Class Template Reference
SmallSetIterator - This class implements a const_iterator for SmallSet by delegating to the underlying SmallVector or Set iterators.
#include "llvm/ADT/SmallSet.h"
Public Member Functions
SmallSetIterator (SetIterTy SetIter)
SmallSetIterator (VecIterTy VecIter)
~SmallSetIterator ()
SmallSetIterator (const SmallSetIterator &Other)
SmallSetIterator (SmallSetIterator &&Other)
SmallSetIterator & operator= (const SmallSetIterator &Other)
SmallSetIterator & operator= (SmallSetIterator &&Other)
bool operator== (const SmallSetIterator &RHS) const
SmallSetIterator & operator++ ()
const T & operator* () const
Public Member Functions inherited from llvm::iterator_facade_base< SmallSetIterator< T, N, C >, std::forward_iterator_tag, T >
SmallSetIterator< T, N, C > operator+ (std::ptrdiff_t n) const
SmallSetIterator< T, N, C > operator- (std::ptrdiff_t n) const
SmallSetIterator< T, N, C > & operator++ ()
SmallSetIterator< T, N, C > & operator-- ()
bool operator!= (const SmallSetIterator< T, N, C > &RHS) const
bool operator> (const SmallSetIterator< T, N, C > &RHS) const
bool operator<= (const SmallSetIterator< T, N, C > &RHS) const
bool operator>= (const SmallSetIterator< T, N, C > &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< SmallSetIterator< T, N, C >, std::forward_iterator_tag, T >
enum
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
template<typename T, unsigned N, typename C>
class llvm::SmallSetIterator< T, N, C >
SmallSetIterator - This class implements a const_iterator for SmallSet by delegating to the underlying SmallVector or Set iterators.
Definition at line 33 of file SmallSet.h.
Constructor & Destructor Documentation
SmallSetIterator() [1/4]
template<typename T, unsigned N, typename C> llvm::SmallSetIterator< T, N, C >::SmallSetIterator (SetIterTy SetIter) inline
Definition at line 50 of file SmallSet.h.
References SetIter.
Referenced by operator++(), operator=(), operator=(), operator==(), SmallSetIterator(), and SmallSetIterator().
SmallSetIterator() [2/4]
template<typename T, unsigned N, typename C> llvm::SmallSetIterator< T, N, C >::SmallSetIterator (VecIterTy VecIter) inline
Definition at line 52 of file SmallSet.h.
References VecIter.
~SmallSetIterator()
template<typename T, unsigned N, typename C> llvm::SmallSetIterator< T, N, C >::~SmallSetIterator () inline
Definition at line 56 of file SmallSet.h.
References SetIter, and VecIter.
SmallSetIterator() [3/4]
template<typename T, unsigned N, typename C> llvm::SmallSetIterator< T, N, C >::SmallSetIterator (const SmallSetIterator< T, N, C > & Other) inline
Definition at line 63 of file SmallSet.h.
References llvm::Other, SetIter, SmallSetIterator(), and VecIter.
SmallSetIterator() [4/4]
template<typename T, unsigned N, typename C> llvm::SmallSetIterator< T, N, C >::SmallSetIterator (SmallSetIterator< T, N, C > && Other) inline
Definition at line 72 of file SmallSet.h.
References llvm::Other, SetIter, SmallSetIterator(), and VecIter.
Member Function Documentation
operator*()
template<typename T, unsigned N, typename C> const T & llvm::SmallSetIterator< T, N, C >::operator* () const inline
Definition at line 125 of file SmallSet.h.
References SetIter, T, and VecIter.
operator++()
template<typename T, unsigned N, typename C> SmallSetIterator & llvm::SmallSetIterator< T, N, C >::operator++ () inline
Definition at line 117 of file SmallSet.h.
References SetIter, SmallSetIterator(), and VecIter.
operator=() [1/2]
template<typename T, unsigned N, typename C> SmallSetIterator & llvm::SmallSetIterator< T, N, C >::operator= (const SmallSetIterator< T, N, C > & Other) inline
Definition at line 81 of file SmallSet.h.
References llvm::Other, SetIter, SmallSetIterator(), and VecIter.
operator=() [2/2]
template<typename T, unsigned N, typename C> SmallSetIterator & llvm::SmallSetIterator< T, N, C >::operator= (SmallSetIterator< T, N, C > && Other) inline
Definition at line 95 of file SmallSet.h.
References llvm::Other, SetIter, SmallSetIterator(), and VecIter.
operator==()
template<typename T, unsigned N, typename C> bool llvm::SmallSetIterator< T, N, C >::operator== (const SmallSetIterator< T, N, C > & RHS) const inline
Definition at line 109 of file SmallSet.h.
References RHS, SetIter, SmallSetIterator(), and VecIter.
Member Data Documentation
SetIter
template<typename T, unsigned N, typename C> SetIterTy llvm::SmallSetIterator< T, N, C >::SetIter
Definition at line 43 of file SmallSet.h.
Referenced by operator*(), operator++(), operator=(), operator=(), operator==(), SmallSetIterator(), SmallSetIterator(), SmallSetIterator(), and ~SmallSetIterator().
VecIter
template<typename T, unsigned N, typename C> VecIterTy llvm::SmallSetIterator< T, N, C >::VecIter
Definition at line 44 of file SmallSet.h.
Referenced by operator*(), operator++(), operator=(), operator=(), operator==(), SmallSetIterator(), SmallSetIterator(), SmallSetIterator(), and ~SmallSetIterator().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallSet.h