LLVM: llvm::SmallVectorTemplateCommon< T, typename > Class Template Reference
llvm::SmallVectorTemplateCommon< T, typename > Class Template Reference
This is the part of SmallVectorTemplateBase which does not depend on whether the type T is a POD.
#include "llvm/ADT/SmallVector.h"
Inherits llvm::SmallVectorBase< SmallVectorSizeType< T > >.
Inherited by llvm::SmallVectorTemplateBase< T, true >, llvm::SmallVectorTemplateBase< T, bool >, and llvm::SmallVectorTemplateBase< T, true >.
Public Types
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using reverse_iterator = std::reverse_iterator<iterator>
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
size_t capacity () const
bool empty () const
size_t size () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Member Functions
void * getFirstEl () const
Find the address of the first element.
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
template<class ItTy>
void assertSafeToReferenceAfterClear (ItTy From, ItTy To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy>
void assertSafeToAddRange (ItTy From, ItTy To)
Check whether any part of the range will be invalidated by growing.
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
LLVM_ABI void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
LLVM_ABI void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Static Protected Member Functions
template<class U>
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Additional Inherited Members
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Detailed Description
template<typename T, typename = void>
class llvm::SmallVectorTemplateCommon< T, typename >
This is the part of SmallVectorTemplateBase which does not depend on whether the type T is a POD.
The extra dummy template argument is used by ArrayRef to avoid unnecessarily requiring T to be complete.
Definition at line 122 of file SmallVector.h.
Member Typedef Documentation
const_iterator
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_iterator = const T *
Definition at line 258 of file SmallVector.h.
const_pointer
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_pointer = const T *
Definition at line 266 of file SmallVector.h.
const_reference
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_reference = const T &
Definition at line 264 of file SmallVector.h.
const_reverse_iterator
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 260 of file SmallVector.h.
difference_type
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::difference_type = ptrdiff_t
Definition at line 255 of file SmallVector.h.
iterator
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::iterator = T *
Definition at line 257 of file SmallVector.h.
pointer
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::pointer = T *
Definition at line 265 of file SmallVector.h.
reference
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::reference = T &
Definition at line 263 of file SmallVector.h.
reverse_iterator
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 261 of file SmallVector.h.
size_type
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::size_type = size_t
Definition at line 254 of file SmallVector.h.
value_type
template<typename T, typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::value_type = T
Definition at line 256 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateCommon()
template<typename T, typename = void> llvm::SmallVectorTemplateCommon< T, typename >::SmallVectorTemplateCommon (size_t Size) inline protected
Definition at line 137 of file SmallVector.h.
References getFirstEl(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::Size.
Referenced by llvm::SmallVectorTemplateBase< T, bool >::SmallVectorTemplateBase(), and llvm::SmallVectorTemplateBase< T, true >::SmallVectorTemplateBase().
Member Function Documentation
assertSafeToAdd()
template<typename T, typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAdd (const void * Elt, size_t N = 1) inline protected
Check whether Elt will be invalidated by increasing the size of the vector by N.
Definition at line 198 of file SmallVector.h.
References assertSafeToReferenceAfterResize(), N, and size().
Referenced by assertSafeToAddRange().
assertSafeToAddRange()
template<typename T, typename = void> template<class ItTy> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange (ItTy From, ItTy To) inline protected
Check whether any part of the range will be invalidated by growing.
Definition at line 219 of file SmallVector.h.
References assertSafeToAdd(), and T.
Referenced by llvm::const_iterator< MemoryLocation >::append(), and llvm::const_iterator< MemoryLocation >::insert().
assertSafeToReferenceAfterClear()
template<typename T, typename = void> template<class ItTy> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterClear (ItTy From, ItTy To) inline protected
Check whether any part of the range will be invalidated by clearing.
Definition at line 204 of file SmallVector.h.
References assertSafeToReferenceAfterResize().
Referenced by llvm::const_iterator< MemoryLocation >::assign().
assertSafeToReferenceAfterResize()
template<typename T, typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterResize (const void * Elt, size_t NewSize) inline protected
Check whether Elt will be invalidated by resizing the vector to NewSize.
Definition at line 190 of file SmallVector.h.
References assert(), and isSafeToReferenceAfterResize().
Referenced by assertSafeToAdd(), and assertSafeToReferenceAfterClear().
back() [1/2]
template<typename T, typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::back () inline
Definition at line 314 of file SmallVector.h.
References assert(), empty(), and end().
Referenced by AddParamAndFnBasicAttributes(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::RISCVDAGToDAGISel::addVectorLoadStoreOperands(), advanceToNextLeafType(), analyzeCompressibleUses(), llvm::Annotations::Annotations(), llvm::A57ChainingConstraint::apply(), ARM64FindSegmentsInFunction(), buildBitSets(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), CalcNodeSethiUllmanNumber(), canRewriteGEPAsOffset(), slpvectorizer::BoUpSLP::canVectorizeLoads(), checkIfSupported(), checkOrAndOpImpliedByOther(), combineBVOfConsecutiveLoads(), combineHorizOpWithShuffle(), combineX86ShuffleChainWithExtract(), computeFunctionSummary(), llvm::RegBankSelect::computeMapping(), ComputePostOrders(), llvm::ConstantFoldTerminator(), llvm::convertUsersOfConstantsToInstructions(), llvm::coro::BaseCloner::create(), createFunctionClones(), llvm::sandboxir::Region::createRegionsFromMD(), createTblForTrunc(), llvm::ScheduleDAGSDNodes::dumpNode(), EltsFromConsecutiveLoads(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::StringToOffsetTable::EmitStringTableDef(), llvm::const_iterator< MemoryLocation >::emplace_back(), llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), ExpandBVWithShuffles(), llvm::cl::ExpansionContext::expandResponseFiles(), ExtractSymbol(), llvm::ControlFlowHub::finalize(), findContiguousCases(), llvm::FindFunctionBackedges(), firstRealType(), llvm::ScalarEvolution::getAddRecExpr(), getAllLexicalIndexes(), getBranchWeights(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::sys::detail::getHostCPUNameForARM(), llvm::logicalview::getInnerComponent(), llvm::VPlan::getMiddleBlock(), getPrefixes(), llvm::Intrinsic::getType(), llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack(), llvm::SmallVectorTemplateBase< T, true >::growAndEmplaceBack(), hoistConditionalLoadsStores(), llvm::cas::ObjectStore::importObject(), loadCSE(), loadNaiveFormatLog(), llvm::PPCInstrInfo::loadRegFromStackSlotNoUpd(), llvm::AArch64CallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), lowerShuffleViaVRegSplitting(), llvm::CombinerHelper::matchRepeatedFPDivisor(), MatchVectorAllEqualTest(), llvm::LegalizerHelper::narrowScalar(), nextRealType(), llvm::orc::normalizePathSegments(), ParseFunctionArgs(), llvm::IntegerInclusiveIntervalUtils::parseIntervals(), parseScalarValue(), llvm::performOptimizedStructLayout(), phiNodeReplacement(), llvm::const_iterator< MemoryLocation >::pop_back_val(), llvm::AsmPrinter::preprocessXXStructorList(), slpvectorizer::BoUpSLP::processBuildVector(), llvm::GCOVFunction::propagateCounts(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::sys::path::remove_dots(), llvm::MemoryDependenceResults::removeInstruction(), removeRedundantBlockingStores(), replaceAccess(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::returnTypeIsEligibleForTailCall(), llvm::ScalarEvolution::LoopGuards::rewrite(), llvm::HipStdParAcceleratorCodeSelectionPass::run(), llvm::HipStdParMathFixupPass::run(), llvm::sandboxir::RegionsFromBBs::runOnFunction(), llvm::SelectionDAGISel::SelectCodeCommon(), selectConstantAddr(), simplifySwitchOfPowersOfTwo(), simplifyWithOpsReplaced(), sortBlocks(), sortLocalVars(), llvm::CallLowering::splitToValueTypes(), llvm::PPCInstrInfo::storeRegToStackSlotNoUpd(), swapMIOperands(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), takeInexpensiveLog2(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), llvm::UnrollLoop(), unswitchNontrivialInvariants(), llvm::DominatorTreeBase< BlockT, false >::updateDFSNumbers(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitAddExpr(), SCEVCastSinkingRewriter::visitAddExpr(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitAddRecExpr(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitMulExpr(), SCEVCastSinkingRewriter::visitMulExpr(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitSequentialUMinExpr(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitSMinExpr(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitUMaxExpr(), and llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visitUMinExpr().
back() [2/2]
template<typename T, typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::back () const inline
Definition at line 318 of file SmallVector.h.
References assert(), empty(), and end().
begin() [1/2]
template<typename T, typename = void> iterator llvm::SmallVectorTemplateCommon< T, typename >::begin () inline
Definition at line 273 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX.
Referenced by llvm::logicalview::LVScope::addMissingElements(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::InstrProfWriter::addTemporalProfileTraces(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::MipsInstrInfo::analyzeBranch(), analyzeExitPHIsForOutputUses(), analyzeLoopUnrollCost(), slpvectorizer::BoUpSLP::analyzeRtStrideCandidate(), llvm::OpenMPIRBuilder::MapInfosTy::append(), llvm::RISCVVectorMaskDAGMutation::apply(), llvm::const_iterator< MemoryLocation >::assign(), llvm::const_iterator< MemoryLocation >::assignRemote(), llvm::codeview::DebugInlineeLinesSubsection::begin(), llvm::ConstantRangeList::begin(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::begin(), llvm::MMRAMetadata::begin(), llvm::RecordStreamer::begin(), buildOverlapMapAndRecordDeclares(), slpvectorizer::BoUpSLP::calculateTreeCostAndTrimNonProfitable(), callBufferedPrintfArgPush(), canPredictSuccessors(), slpvectorizer::BoUpSLP::canVectorizeLoads(), checkDependencies(), llvm::const_iterator< MemoryLocation >::clear(), TransferTracker::clobberMloc(), collectConcatOps(), llvm::mca::RegisterFile::collectWrites(), combineBitcastvxi1(), combineINSERT_SUBVECTOR(), combineX86ShufflesRecursively(), llvm::computeAccessFunctions(), llvm::AccelTableBase::computeBucketCount(), computeCalleeSaveRegisterPairs(), llvm::RandomIRBuilder::connectToSink(), llvm::ScalarEvolution::convertSCEVToAddRecWithPredicates(), costShuffleViaSplitting(), costShuffleViaVRegSplitting(), llvm::IntervalTree< LVAddress, LVScope * >::create(), createCandidatesFromSuffixTree(), createTblForTrunc(), createUniqueEntity(), data(), data(), llvm::DataDependenceGraph::DataDependenceGraph(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), determineGPRegsToClear(), llvm::DWARFContext::dwo_info_section_units(), llvm::DWARFContext::dwo_types_section_units(), llvm::MipsAsmPrinter::emitEndOfAsmFile(), llvm::AsmPrinter::emitFunctionBody(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::AsmPrinter::emitXXStructorList(), end(), end(), llvm::LegalizerHelper::equalizeVectorShuffleLengths(), llvm::const_iterator< MemoryLocation >::erase(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::jitlink::finalizeBlockRelax(), llvm::findArrayDimensions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::RegBankSelect::findBestMapping(), llvm::cl::ExpansionContext::findConfigFile(), findContiguousCases(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::RandomIRBuilder::findOrCreateSource(), slpvectorizer::BoUpSLP::findReusedOrderedScalars(), front(), front(), llvm::WebAssemblyAsmTypeCheck::funcDecl(), llvm::RISCVMatInt::generateInstSeq(), llvm::ScalarEvolution::getAddRecExpr(), llvm::opt::ArgList::getAllArgValues(), llvm::Attribute::getAsString(), llvm::SelectionDAG::getConstant(), llvm::SampleContextTracker::getContextString(), llvm::RegsForValue::getCopyFromRegs(), llvm::GenericCycle< ContextT >::getExitBlocks(), getFauxShuffleMask(), getGatherLanePattern(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::RegisterBankInfo::getOperandsMapping(), getOrCreateFrameHelper(), getPreStartForExtend(), slpvectorizer::BoUpSLP::getReorderingData(), getSalvageOpsForGEP(), getSchedRegions(), llvm::GetShadowBytesAfterScope(), llvm::X86TTIImpl::getShuffleCost(), llvm::gsym::LookupResult::getSourceFile(), llvm::object::MinidumpFile::getString(), llvm::getSuperRegs(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), slpvectorizer::BoUpSLP::getTreeCost(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), getVCIXISDNodeVOID(), getVCIXISDNodeWCHAIN(), llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), llvm::SmallVectorTemplateBase< T, true >::growAndAssign(), llvm::SDNode::hasPredecessorHelper(), llvm::DWARFContext::info_section_units(), initializeUniqueCases(), llvm::InlineFunctionImpl(), llvm::const_iterator< MemoryLocation >::insert(), llvm::const_iterator< MemoryLocation >::insert(), llvm::ConstantRangeList::insert(), insertParsePoints(), llvm::CallLowering::insertSRetIncomingArgument(), instCombineConvertFromSVBool(), isFreeConcat(), isHorizontalBinOp(), isRangeInStorage(), isReferenceToStorage(), isSafeToReferenceAfterResize(), isUpperSubvectorUndef(), isVECTOR_SHUFFLE_SPLATI(), isWideDUPMask(), llvm::coverage::CoverageMapping::load(), llvm::MipsSEInstrInfo::loadImmediate(), lowerBUILD_VECTOR(), llvm::SITargetLowering::LowerFormalArguments(), LowerInterruptReturn(), lowerLaneOp(), lowerShuffleViaVRegSplitting(), lowerStatepointMetaArgs(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), shuffles::mask(), matchBinaryPermuteShuffle(), matchScalarReduction(), mergeDebugLocs(), mergeVectorRegsToResultRegs(), llvm::sys::unicode::nameToCodepoint(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), llvm::const_iterator< MemoryLocation >::operator<(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::const_iterator< MemoryLocation >::operator==(), llvm::NVPTXScopes::operator[](), operator[](), operator[](), slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::X86FrameLowering::orderFrameObjects(), llvm::SPIRVExtensionsParser::parse(), parseScalarValue(), performCONCAT_VECTORSCombine(), llvm::performOptimizedStructLayout(), populateDependencyMatrix(), slpvectorizer::BoUpSLP::processBuildVector(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVBinaryReader::processLines(), readArray(), llvm::sys::fs::readNativeFileToEOF(), llvm::BinaryStreamReader::readSLEB128(), llvm::BinaryStreamReader::readULEB128(), llvm::readWideAPInt(), llvm::AArch64TargetLowering::ReconstructShuffle(), removeCCOut(), removeCondCode(), RemovePreallocated(), removeRedundantDbgLocsUsingBackwardScan(), removeVPTCondCode(), rend(), rend(), slpvectorizer::BoUpSLP::reorderBottomToTop(), reorderOrder(), reorderReuses(), reorderSubVector(), slpvectorizer::BoUpSLP::reorderTopToBottom(), resolveSources(), llvm::FunctionSpecializer::run(), llvm::InlinerPass::run(), llvm::SelectionDAGISel::SelectCodeCommon(), setUsedInitializer(), simplifyInstructionWithOperands(), SimplifyValuePattern(), sinkInstruction(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), llvm::IntervalTree< LVAddress, LVScope * >::sortIntervals(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), splitVector(), llvm::Regex::sub(), llvm::SmallVectorImpl< T >::swap(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::object::ELFFile< ELFT >::toMappedAddr(), toStringAPFloat(), llvm::const_iterator< MemoryLocation >::truncate(), tryFoldCommutativeMath(), tryFoldCommutativeMathWithArgInBetween(), tryFoldConstants(), tryFoldNoOpMath(), llvm::LegalizationArtifactCombiner::tryFoldUnmergeCast(), tryToFindDuplicates(), tryToVectorizeSequence(), llvm::coverage::mcdc::TVIdxBuilder::TVIdxBuilder(), llvm::DWARFContext::types_section_units(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), upgradeAArch64IntrinsicCall(), shuffles::vdealvdd(), slpvectorizer::BoUpSLP::vectorizeTree(), llvm::GenericCycle< ContextT >::verifyCycle(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::InstCombinerImpl::visitLandingPadInst(), shuffles::vshuffvdd(), llvm::WriteBitcodeToFile(), llvm::dxil::WriteDXILToFile(), and llvm::const_iterator< MemoryLocation >::~SmallVectorImpl().
begin() [2/2]
template<typename T, typename = void> const_iterator llvm::SmallVectorTemplateCommon< T, typename >::begin () const inline
Definition at line 274 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX.
capacity()
template<typename T, typename = void> size_t llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity () const inline
Definition at line 81 of file SmallVector.h.
Referenced by llvm::const_iterator< MemoryLocation >::assign(), capacity_in_bytes(), llvm::const_iterator< MemoryLocation >::emplace_back(), isSafeToReferenceAfterResize(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::const_iterator< MemoryLocation >::reserve(), and reserveForParamAndGetAddressImpl().
capacity_in_bytes()
template<typename T, typename = void> size_t llvm::SmallVectorTemplateCommon< T, typename >::capacity_in_bytes () const inline
Definition at line 289 of file SmallVector.h.
References capacity(), and T.
data() [1/2]
template<typename T, typename = void> pointer llvm::SmallVectorTemplateCommon< T, typename >::data () inline
Return a pointer to the vector's buffer, even if empty().
Definition at line 292 of file SmallVector.h.
References begin().
Referenced by llvm::c_str(), collectAddressSymbols(), CollectOpsToWiden(), llvm::object::CompressedOffloadBundle::compress(), llvm::pdb::DIASession::createFromExe(), llvm::pdb::DIASession::createFromPdb(), llvm::orc::deserializeModule(), llvm::ConnectedVNInfoEqClasses::Distribute(), emitExternalFile(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::MCStreamer::emitIntValue(), llvm::COFF::encodeSectionName(), llvm::pdb::DIARawSymbol::findChildren(), llvm::pdb::DIARawSymbol::findChildrenByAddr(), llvm::pdb::DIARawSymbol::findChildrenByRVA(), llvm::pdb::DIARawSymbol::findChildrenByVA(), GenerateFixedLengthSVETBL(), GenerateTBL(), llvm::omp::getCompoundConstruct(), llvm::pdb::DIARawSymbol::getDataBytes(), LLVMDisasmInstruction(), LLVMOrcExecutionSessionLookup(), lowerV8I16GeneralSingleInputShuffle(), llvm::Regex::match(), matchUnaryPermuteShuffle(), llvm::sys::path::native(), llvm::performOptimizedStructLayout(), llvm::ReadByteArrayFromGlobal(), llvm::sys::path::remove_dots(), llvm::LiveIntervals::splitSeparateComponents(), llvm::Twine::toNullTerminatedStringRef(), llvm::Twine::toStringRef(), llvm::mcdxbc::RootSignatureDesc::write(), llvm::mcdxbc::Signature::write(), llvm::WriteBitcodeToFile(), llvm::objcopy::elf::IHexSectionWriter::writeData(), llvm::BitcodeWriter::writeSymtab(), writeUniversalArchsToStream(), and llvm::sampleprof::SampleProfileWriter::writeWithSizeLimitInternal().
data() [2/2]
template<typename T, typename = void> const_pointer llvm::SmallVectorTemplateCommon< T, typename >::data () const inline
Return a pointer to the vector's buffer, even if empty().
Definition at line 294 of file SmallVector.h.
References begin().
empty()
template<typename T, typename = void> bool llvm::SmallVectorBase< SmallVectorSizeType< T > >::empty () const inline nodiscard
Definition at line 83 of file SmallVector.h.
Referenced by llvm::PMDataManager::add(), AddAliasScopeMetadata(), addAllGlobalValueUsers(), addBlockAndPredsToSet(), addBoundsChecking(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), addRange(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addTemplateParamNames(), llvm::InstrProfWriter::addTemporalProfileTraces(), llvm::DbgValueRangeTable::addVariable(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), allPathsGoThroughCold(), allUsersAreInFunction(), allUsesOfLoadAndStores(), allUsesOfLoadedValueWillTrapIfNull(), allZeroIndices(), llvm::LanaiInstrInfo::analyzeBranch(), slpvectorizer::BoUpSLP::analyzeConstantStrideCandidate(), analyzeLoopUnrollCost(), slpvectorizer::BoUpSLP::analyzeRtStrideCandidate(), llvm::Annotations::Annotations(), llvm::appendReversedLoopsToWorklist(), llvm::A57ChainingConstraint::apply(), llvm::RISCVVectorMaskDAGMutation::apply(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingSMULU64(), llvm::MemorySSAUpdater::applyUpdates(), llvm::AMDGPUCallLowering::areCalleeOutgoingArgsTailCallable(), argsAreStructReturn(), llvm::RegBankSelect::assignInstr(), llvm::RegBankSelect::assignRegisterBanks(), back(), back(), llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::build(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoops(), llvm::CSEMIRBuilder::buildInstr(), llvm::CombinerHelper::buildSDivOrSRemUsingMul(), buildTreeReduction(), llvm::CombinerHelper::buildUDivOrURemUsingMul(), CalcNodeSethiUllmanNumber(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateClrEHStateNumbers(), llvm::calculateCXXStateForAsynchEH(), llvm::calculateSEHStateForAsynchEH(), callIsStructReturn(), canFoldStoreIntoLibCallOutputPointers(), canonicalizePHIOperands(), llvm::canReturn(), llvm::ScalarEvolution::canReuseInstruction(), canRewriteGEPAsOffset(), llvm::TailDuplicator::canTailDuplicate(), slpvectorizer::BoUpSLP::canVectorizeLoads(), CC_LoongArch(), llvm::CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), llvm::MCGOFFStreamer::changeSection(), llvm::PatternMatch::undef_match::check(), checkClobberSanity(), llvm::Attributor::checkForAllUses(), checkIfSupported(), checkMixedPrecision(), checkVectorTypesForPromotion(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), cleanupSinglePredPHIs(), clearAssumptionsOfUsers(), llvm::CloneAndPruneIntoFromInst(), cloneLoopNest(), codegen(), llvm::OpenMPIRBuilder::OutlineInfo::collectBlocks(), collectBlockUseDef(), collectCastInstrs(), collectEHScopeMembers(), llvm::collectEphemeralRecipesForVPlan(), collectHomogenousInstGraphLoopInvariants(), llvm::LoopVectorizationCostModel::collectInLoopReductions(), llvm::DDGNode::collectInstructions(), collectLeaves(), llvm::collectPossibleValues(), collectSRATypes(), collectTransitivePredecessors(), collectUnswitchCandidates(), llvm::colorEHFunclets(), combineHorizOpWithShuffle(), combineOp_VLToVWOp_VL(), combineOrCmpEqZeroToCtlzSrl(), combineRedundantDWordShuffle(), combineToHorizontalAddSub(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::FunctionComparator::compare(), computeBlocksDominatingExits(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), computeFunctionSummary(), ModuleImportsManager::computeImportForModule(), ComputeLiveInBlocks(), llvm::computeMinimumValueSizes(), ComputePostOrders(), computeUnlikelySuccessors(), llvm::SMSchedule::computeUnpipelineableNodes(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantAggrKeyType< ConstantArray >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), llvm::ConstantPtrAuthKeyType::ConstantPtrAuthKeyType(), ConstHasGlobalValuePredicate(), llvm::LiveIntervalCalc::constructMainRangeFromSubranges(), containsUnreachable(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::MachO::convertToInterfaceFile(), convertToParamAS(), llvm::convertUsersOfConstantsToInstructions(), llvm::convertUTF8ToUTF16String(), llvm::SelectionDAG::copyExtraInfo(), createBBClusterInfoForFunction(), llvm::VPlanTransforms::createInterleaveGroups(), llvm::AbstractDependenceGraphBuilder< GraphType >::createMemoryDependencyEdges(), llvm::MDBuilder::createPCSections(), llvm::OpenMPIRBuilder::createTargetData(), createTblForTrunc(), deleteDeadBlocksFromLoop(), llvm::delinearize(), llvm::delinearizeFixedSizeArray(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), determinePointerAccessAttrs(), doPromotion(), dropIntrinsicWithUnknownMetadataArgument(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), llvm::DWARFDie::dump(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), llvm::SMSchedule::earliestCycleInChain(), llvm::ehAwareSplitEdge(), llvm::LiveRangeEdit::eliminateDeadDefs(), eliminateDeadSwitchCases(), eliminateSwiftError(), llvm::embedBitcodeInModule(), llvm::AsmPrinter::emitCOFFReplaceableFunctionData(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::PPCFrameLowering::emitEpilogue(), emitExternalFile(), EmitGenDwarfInfo(), llvm::LoopVectorizationPlanner::emitInvalidCostRemarks(), LiveDebugValues::MLocTracker::emitLoc(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::OpenMPIRBuilder::emitOffloadingArrays(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::PPCFrameLowering::emitPrologue(), emitResourceMetadata(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::dwarf_linker::classic::DwarfStreamer::emitStringOffsets(), llvm::OpenMPIRBuilder::emitTargetTask(), emitTaskDependencies(), llvm::OpenMPIRBuilder::emitUsed(), llvm::AsmPrinter::emitXXStructorList(), llvm::SystemZAsmPrinter::emitXXStructorList(), llvm::SelectionDAGISel::EnforceNodeIdInvariant(), eraseDeadBBsAndChildren(), eraseDeadBBsAndChildren(), llvm::SCEVExpander::eraseDeadInstructions(), llvm::GIMatchTableExecutor::executeMatchTable(), ExpandBasePaths(), llvm::SCEVExpander::expandUnionPredicate(), explicifyGuards(), ExtendUsesToFormExtLoad(), feedsIntoVectorReduction(), llvm::DIBuilder::finalize(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::findAllocaForValue(), llvm::CodeExtractor::findAllocas(), findArgParts(), llvm::findArrayDimensions(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), findBasePointer(), llvm::RegBankSelect::findBestMapping(), llvm::rdf::FuncNode::findBlock(), findBuildAggregate(), findDependencies(), llvm::findDevirtualizableCallsForTypeTest(), llvm::DGNode< DDGNode, DDGEdge >::findEdgesTo(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::FindFunctionBackedges(), llvm::DirectedGraph< DDGNode, DDGEdge >::findIncomingEdgesToNode(), findNextInsertLocation(), llvm::DWARFDie::findRecursively(), findRefEdges(), slpvectorizer::BoUpSLP::findReusedOrderedScalars(), llvm::findValuesAffectedByCondition(), llvm::PGOContextualProfile::flatten(), llvm::foldBranchToCommonDest(), foldConsecutiveStores(), foldGEPChainAsStructAccess(), foldGEPChainAsU8Access(), foldICmpOrXorSubChain(), foldInlineAsmMemOperand(), llvm::InstCombinerImpl::foldPtrToIntOrAddrOfGEP(), forEachUser(), llvm::ScalarEvolution::forgetBlockAndLoopDispositions(), llvm::ScalarEvolution::forgetLoop(), llvm::formDedicatedExitBlocks(), formLCSSAForInstructionsImpl(), formLCSSAImpl(), forwardStoredOnceStore(), front(), front(), functionWillReturn(), llvm::MCResourceInfo::gatherResourceInfo(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqLeadingZeros(), generateReproducer(), llvm::ScalarEvolution::getAddExpr(), llvm::dxil::ResourceInfo::getAsMetadata(), llvm::Attributor::getAssumedConstant(), llvm::Attributor::getAssumedSimplified(), llvm::Attributor::getAssumedSimplifiedValues(), getBaseType(), getCastsForInductionPHI(), llvm::DependenceGraphInfo< NodeType >::getDependencies(), llvm::DominatorTreeBase< BlockT, false >::getDescendants(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::getEHScopeMembership(), getEmscriptenInvokeSymbolName(), getEntryPropAsMetadata(), getFunctionNameAndStartLineForAddress(), llvm::ReachingDefInfo::getGlobalUses(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::sys::detail::getHostCPUNameForARM(), llvm::getIndexExpressionsFromGEP(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::RISCVTTIImpl::getIntrinsicInstrCost(), llvm::WebAssembly::getLibcallSignature(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), getMaskForArgs(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::BasicAAResult::getModRefInfoMask(), llvm::ScalarEvolution::getMulExpr(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::LoopNest::getPerfectLoops(), AMDGPURegBankLegalizeCombiner::getReadAnyLaneSrcs(), llvm::vputils::getRecipesForUncountableExit(), llvm::AArch64RegisterInfo::getRegAllocationHints(), slpvectorizer::BoUpSLP::getReorderingData(), getSameOpcode(), slpvectorizer::BoUpSLP::getSpillCost(), llvm::opt::ArgList::getSubCommand(), getTargetConstantBitsFromNode(), llvm::logicalview::LVScope::getTemplateParameterTypes(), llvm::AMDGPU::getTransitiveUsesOfLDS(), llvm::Intrinsic::getType(), llvm::BasicTTIImplBase< BasicTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::getUnderlyingObjectAggressive(), llvm::getUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::DebugSSAUpdater::getValueInMiddleOfBlock(), slpvectorizer::BoUpSLP::getVectorElementSize(), growShuffleMask(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::VPlanTransforms::handleMaxMinNumReductions(), HandleMergeInputChains(), hasAllNBitUsers(), hasAllNBitUsers(), hasCallsInBlocksBetween(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), hasHardUserWithinLoop(), llvm::hasPartialIVCondition(), llvm::SDNode::hasPredecessorHelper(), hoistMulAddAssociation(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::cas::ObjectStore::importObject(), indirectGlobals(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::InlineFunctionImpl(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertBlockBefore(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), insertParsePoints(), insertPHI(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), insertSpills(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), isBlockValidForExtraction(), llvm::AMDGPU::isClobberedInFunction(), isConditionalOnXorOfPHIs(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isEphemeralValueOf(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::SCEVExpander::isHighCostExpansion(), isHorizontalBinOp(), isKnownNonNullFromDominatingCondition(), isLoadCombineCandidate(), isLoopDead(), isNonEscapingGlobalNoAliasWithLoad(), isNotInCycle(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantMemory(), isPotentiallyReachable(), llvm::isPotentiallyReachable(), isPTruePromoted(), isReachableAmongDominated(), isReachableImpl(), llvm::isSafeToDestroyConstant(), isSafeToMove(), isSaveReachableThroughClean(), isSignExtendedW(), isSignExtendedW(), IsStoredObjCPointer(), isSuccOrder(), llvm::mca::ResourceManager::issueInstructionImpl(), slpvectorizer::BoUpSLP::isTreeTinyAndNotFullyVectorizable(), isUsedByLoadStoreAddress(), llvm::object::WasmSectionOrderChecker::isValidSectionOrder(), IsValueFullyAvailableInBlock(), isVectorPromotionViable(), llvm::SMSchedule::latestCycleInChain(), llvm::Legalizer::legalizeMachineFunction(), LinearizeExprTree(), loadCSE(), lowerAllowChecks(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), lowerCallResult(), llvm::TargetLowering::LowerCallTo(), lowerConstant(), llvm::lowerConstantIntrinsics(), llvm::LowerDbgDeclare(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerGuardIntrinsic(), llvm::PhiLoweringHelper::lowerPhis(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), lowerWidenableCondition(), llvm::IRAttribute< AK, BaseType, AAType >::manifest(), markAliveBlocks(), markAllReachable(), markKernelArgsAsInreg(), markTails(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::Pattern::match(), matchMergedBFX(), maybeHandleGlobals(), memoryIsNotModifiedBetween(), mergeBlocksIntoPredecessors(), llvm::Instruction::mergeDIAssignID(), mergeEltWithShuffle(), llvm::RISCVInstrInfo::movImm(), llvm::mustExecuteUBIfPoisonOnPathTo(), llvm::VPlanTransforms::narrowInterleaveGroups(), llvm::LegalizerHelper::narrowScalar(), llvm::EscapeEnumerator::Next(), llvm::nonStrictlyPostDominate(), llvm::orc::normalizePathSegments(), GlobalsImporter::onImportingSummary(), llvm::orc::SequenceBBQuery::operator()(), llvm::LockstepReverseIterator< EarlyFailure >::operator++(), llvm::LockstepReverseIterator< EarlyFailure >::operator--(), slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::TargetInstrInfo::optimizeLoadInstr(), optimizeLoopExitWithUnknownExitCount(), OptimizeNonTrivialIFuncs(), llvm::AArch64FrameLowering::orderFrameObjects(), llvm::HexagonFrameLowering::orderFrameObjects(), llvm::X86FrameLowering::orderFrameObjects(), llvm::MachO::PackedVersion::parse32(), llvm::MachO::PackedVersion::parse64(), parseCondition(), llvm::IntegerInclusiveIntervalUtils::parseIntervals(), parseScalarValue(), llvm::ELFCompactAttrParser::parseSubsection(), performBranchToCommonDestFolding(), llvm::performOptimizedStructLayout(), llvm::PointerMayBeCaptured(), poisonGuaranteesUB(), populateWorklist(), PrepareTailCall(), llvm::cas::ondisk::OnDiskGraphDB::print(), llvm::printLoop(), PrintLoopInfo(), printSyncScope(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::JumpThreadingPass::processBranchOnXOR(), slpvectorizer::BoUpSLP::processBuildVector(), processCallSite(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVBinaryReader::processLines(), llvm::processShuffleMasks(), llvm::JumpThreadingPass::processThreadableEdges(), promoteArguments(), llvm::promoteLoopAccessesToScalars(), llvm::GCOVFunction::propagateCounts(), llvm::SwiftErrorValueTracking::propagateVRegs(), rebuildLoopAfterUnswitch(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), recomputeLoopBlockSet(), ReconstructShuffleWithRuntimeMask(), recursivelyDeleteDeadRecipes(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), TransferTracker::redefVar(), reduceDbgValsBackwardScan(), reduceDbgValsForwardScan(), ReduceLoopStrength(), llvm::DotCfgChangeReporter::registerCallbacks(), llvm::Attributor::registerFunctionSignatureRewrite(), registerSpirvTypeForNewInstructions(), relocationViaAlloca(), rematerializeLiveValuesAtUses(), llvm::sys::path::remove_dots(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::PMDataManager::removeDeadPasses(), llvm::AMDGPU::removeFnAttrFromReachable(), removeFromUsedList(), removeGEPBuiltinsInFunc(), llvm::MemoryDependenceResults::removeInstruction(), slpvectorizer::BoUpSLP::removeInstructionsAndOperands(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdges(), removePAICalls(), removeRedundantDbgInstrsUsingBackwardScan(), slpvectorizer::BoUpSLP::reorderBottomToTop(), reorderOrder(), slpvectorizer::BoUpSLP::reorderTopToBottom(), replaceAccess(), replaceConstantExprOp(), llvm::coro::replaceCoroFree(), llvm::replaceDbgUsesWithUndef(), replaceLoopPHINodesWithPreheaderValues(), llvm::SSAUpdaterBulk::RewriteAndOptimizeAllUses(), rewriteDebugUsers(), rewriteNonInstructionUses(), rewritePHIs(), llvm::BPFASpaceCastSimplifyPass::run(), llvm::CallBrPreparePass::run(), llvm::CoroSplitPass::run(), llvm::DropUnnecessaryAssumesPass::run(), llvm::GenericCycleInfoCompute< ContextT >::run(), llvm::GlobalDCEPass::run(), llvm::InlinerPass::run(), llvm::KCFIPass::run(), llvm::LoopSinkPass::run(), RemoveLoadsIntoFakeUses::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::LoopVectorizePass::runImpl(), runImpl(), runImpl(), runImpl(), runImpl(), runMoveAutoInit(), llvm::RewriteStatepointsForGC::runOnFunction(), salvageDbgAssignAddress(), llvm::salvageDebugInfo(), llvm::salvageDebugInfoForDbgValues(), salvageDebugInfoImpl(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), searchPredecessors(), llvm::SelectionDAGISel::SelectCodeCommon(), selectConstantAddr(), selectImm(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::SUnit::setDepthDirty(), llvm::VPRegionBlock::setEntry(), llvm::VPRegionBlock::setExiting(), llvm::MCContext::setGenDwarfRootFile(), llvm::SUnit::setHeightDirty(), setRequiredFeatureString(), llvm::MIRParserImpl::setupRegisterInfo(), shouldTransformMulToShiftsAddsSubs(), simplifyAMDGCNImageIntrinsic(), simplifyCommonValuePhi(), llvm::simplifyLoop(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), simplifySwitchWhenUMin(), llvm::coro::sinkSpillUsesAfterCoroBegin(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), SoleWriteToDeadLocal(), sortBlocks(), sortLocalVars(), llvm::RABasic::spillInterferences(), llvm::DominatorTreeBase< BlockT, false >::Split(), llvm::coro::AnyRetconABI::splitCoroutine(), llvm::coro::AsyncABI::splitCoroutine(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SplitIndirectBrCriticalEdges(), llvm::SplitKnownCriticalEdge(), SplitLandingPadPredecessorsImpl(), SRAGlobal(), stripDeadDebugInfoImpl(), stripGCRelocates(), substituteSimpleCopyRegs(), llvm::coro::suppressCoroAllocs(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::cl::TokenizeGNUCommandLine(), tokenizeWindowsCommandLineImpl(), llvm::objcopy::macho::MachOWriter::totalSize(), transformResourcePointers(), llvm::LoopTraversal::traverse(), tryBuildVectorShuffle(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), AMDGPURegBankLegalizeCombiner::tryEliminateReadAnyLane(), trySwitchToSelect(), llvm::InstCombinerImpl::tryToSinkInstruction(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), tryToVectorizeSequence(), llvm::coverage::mcdc::TVIdxBuilder::TVIdxBuilder(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), unswitchTrivialSwitch(), updateCallGraphAfterCoroutineSplit(), llvm::DominatorTreeBase< BlockT, false >::updateDFSNumbers(), llvm::SelectionDAG::updateDivergence(), updateLiveness(), llvm::JumpThreadingPass::updateSSA(), usersDominator(), llvm::cas::ObjectStore::validateTree(), valueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::PHITransAddr::verify(), llvm::ScalarEvolution::verify(), verifyCTRBranch(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), llvm::SelectionDAGBuilder::visitDbgInfo(), visitDomSubTree(), visitPointers(), llvm::LazyCallGraph::visitReferences(), llvm::objcopy::elf::BinaryWriter::write(), llvm::writeArchiveToStream(), and llvm::dxil::WriteDXILToFile().
end() [1/2]
template<typename T, typename = void> iterator llvm::SmallVectorTemplateCommon< T, typename >::end () inline
Definition at line 275 of file SmallVector.h.
References begin(), and size().
Referenced by addData(), llvm::logicalview::LVScope::addMissingElements(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), llvm::RecurrenceDescriptor::AddReductionVar(), addRegLanes(), llvm::InstrProfWriter::addTemporalProfileTraces(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::CCState::AnalyzeArgumentsSecondPass(), analyzeLoopUnrollCost(), slpvectorizer::BoUpSLP::analyzeRtStrideCandidate(), llvm::const_iterator< MemoryLocation >::append(), llvm::const_iterator< MemoryLocation >::append(), llvm::OpenMPIRBuilder::MapInfosTy::append(), llvm::const_iterator< MemoryLocation >::assign(), llvm::const_iterator< MemoryLocation >::assignRemote(), back(), back(), buildOverlapMapAndRecordDeclares(), checkDependencies(), checkIfSupported(), checkVectorTypesForPromotion(), llvm::const_iterator< MemoryLocation >::clear(), collectVirtualRegUses(), combineBitcastvxi1(), combineINSERT_SUBVECTOR(), combineX86ShufflesRecursively(), llvm::computeAccessFunctions(), computeCalleeSaveRegisterPairs(), llvm::RandomIRBuilder::connectToSink(), llvm::ScalarEvolution::convertSCEVToAddRecWithPredicates(), llvm::IntervalTree< LVAddress, LVScope * >::create(), createTblForTrunc(), llvm::DataDependenceGraph::DataDependenceGraph(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), llvm::ARMFrameLowering::determineCalleeSaves(), determineGPRegsToClear(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::DWARFContext::dwo_types_section_units(), llvm::AsmPrinter::emitFunctionBody(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::AsmPrinter::emitXXStructorList(), llvm::const_iterator< MemoryLocation >::emplace_back(), llvm::codeview::DebugInlineeLinesSubsection::end(), llvm::ConstantRangeList::end(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::end(), llvm::MMRAMetadata::end(), llvm::RecordStreamer::end(), llvm::const_iterator< MemoryLocation >::erase(), llvm::const_iterator< MemoryLocation >::erase(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::findArrayDimensions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::cl::ExpansionContext::findConfigFile(), findContiguousCases(), findInfo(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::RandomIRBuilder::findOrCreateSource(), slpvectorizer::BoUpSLP::findReusedOrderedScalars(), llvm::WebAssemblyAsmTypeCheck::funcDecl(), llvm::ScalarEvolution::getAddRecExpr(), llvm::opt::ArgList::getAllArgValues(), llvm::Attribute::getAsString(), llvm::SelectionDAG::getConstant(), llvm::SampleContextTracker::getContextString(), llvm::coverage::LineCoverageIterator::getEnd(), llvm::GenericCycle< ContextT >::getExitBlocks(), getFauxShuffleMask(), getGatherLanePattern(), llvm::sys::detail::getHostCPUNameForARM(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::RegisterBankInfo::getOperandsMapping(), getPreStartForExtend(), slpvectorizer::BoUpSLP::getReorderingData(), getSchedRegions(), llvm::gsym::LookupResult::getSourceFile(), llvm::getSuperRegs(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), slpvectorizer::BoUpSLP::getTreeCost(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), llvm::SDNode::hasPredecessorHelper(), llvm::InlineFunctionImpl(), llvm::const_iterator< MemoryLocation >::insert(), llvm::const_iterator< MemoryLocation >::insert(), llvm::ConstantRangeList::insert(), insertParsePoints(), isFreeConcat(), isHorizontalBinOp(), isRangeInStorage(), isReferenceToStorage(), isUpperSubvectorUndef(), isVECTOR_SHUFFLE_SPLATI(), isWideDUPMask(), llvm::coverage::CoverageMapping::load(), llvm::MipsSEInstrInfo::loadImmediate(), TransferTracker::loadInlocs(), TransferTracker::loadVarInloc(), lowerBUILD_VECTOR(), llvm::SITargetLowering::LowerFormalArguments(), lowerLaneOp(), lowerShuffleViaVRegSplitting(), lowerStatepointMetaArgs(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), shuffles::mask(), matchBinaryPermuteShuffle(), mergePartStores(), llvm::sys::unicode::nameToCodepoint(), llvm::sys::unicode::nearestMatchesForCodepointName(), llvm::const_iterator< MemoryLocation >::operator<(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::const_iterator< MemoryLocation >::operator==(), llvm::NVPTXScopes::operator[](), slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::X86FrameLowering::orderFrameObjects(), llvm::SPIRVExtensionsParser::parse(), performCONCAT_VECTORSCombine(), llvm::performOptimizedStructLayout(), placeSources(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), populateDependencyMatrix(), slpvectorizer::BoUpSLP::processBuildVector(), llvm::logicalview::LVBinaryReader::processLines(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), rbegin(), rbegin(), readMemprof(), llvm::BinaryStreamReader::readSLEB128(), llvm::BinaryStreamReader::readULEB128(), llvm::RegPressureTracker::recede(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::AArch64TargetLowering::ReconstructShuffle(), RemoveInstInputs(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdges(), RemovePreallocated(), removeRedundantDbgLocsUsingBackwardScan(), removeRegLanes(), reorderOrder(), reorderReuses(), replaceConstantExprOp(), resolveSources(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::FunctionSpecializer::run(), llvm::InlinerPass::run(), llvm::SelectionDAGISel::SelectCodeCommon(), setRegZero(), setUsedInitializer(), SimplifyValuePattern(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), sortGlobalExprs(), llvm::IntervalTree< LVAddress, LVScope * >::sortIntervals(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), splitVector(), llvm::Regex::sub(), llvm::SmallVectorImpl< T >::swap(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), toStringAPFloat(), llvm::const_iterator< MemoryLocation >::truncate(), tryToFindDuplicates(), tryToVectorizeSequence(), llvm::DWARFContext::types_section_units(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), upgradeAArch64IntrinsicCall(), slpvectorizer::BoUpSLP::vectorizeTree(), llvm::GenericCycle< ContextT >::verifyCycle(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), and verifySubExpr().
end() [2/2]
template<typename T, typename = void> const_iterator llvm::SmallVectorTemplateCommon< T, typename >::end () const inline
Definition at line 276 of file SmallVector.h.
References begin(), and size().
front() [1/2]
template<typename T, typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::front () inline
Definition at line 305 of file SmallVector.h.
References assert(), begin(), and empty().
Referenced by llvm::MCPseudoProbeInlineTree::addPseudoProbe(), calcPredicateUsingBooleans(), slpvectorizer::BoUpSLP::calculateTreeCostAndTrimNonProfitable(), canConvertToFMA(), slpvectorizer::BoUpSLP::canVectorizeLoads(), combineHorizOpWithShuffle(), combineX86ShuffleChainWithExtract(), llvm::convertUsersOfConstantsToInstructions(), createPHIsForSelects(), llvm::ARMFrameLowering::determineCalleeSaves(), EltsFromConsecutiveLoads(), llvm::StringToOffsetTable::EmitStringTableDef(), ExtractImmediate(), ExtractSymbol(), llvm::ControlFlowHub::finalize(), findContiguousCases(), slpvectorizer::BoUpSLP::findReusedOrderedScalars(), llvm::RISCVMatInt::generateInstSeq(), getBranchWeights(), llvm::logicalview::getInnerComponent(), llvm::TargetInstrInfo::getMemOperandWithOffset(), llvm::codeview::getModifiedType(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), slpvectorizer::BoUpSLP::getReorderingData(), slpvectorizer::BoUpSLP::getRootNodeTypeWithNoCast(), getSameOpcode(), llvm::opt::ArgList::getSubCommand(), llvm::SelectionDAG::getTopologicallyOrderedNodes(), slpvectorizer::BoUpSLP::getTreeCost(), llvm::cas::ObjectStore::importObject(), llvm::intersectAccessGroups(), isMaskedLoadCompress(), llvm::Legalizer::legalizeMachineFunction(), slpvectorizer::BoUpSLP::processBuildVector(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), slpvectorizer::BoUpSLP::VLOperands::reorder(), reorderScalars(), llvm::coro::replaceCoroFree(), llvm::SSAUpdaterBulk::RewriteAndOptimizeAllUses(), simplifySwitchOfPowersOfTwo(), sinkLastInstruction(), sinkScalarOperands(), tryToFindDuplicates(), tryToVectorizeSequence(), llvm::UnrollLoop(), llvm::InstCombinerImpl::visitGetElementPtrInst(), widenVectorOpsToi8(), llvm::objcopy::elf::BinaryWriter::write(), llvm::dxil::WriteDXILToFile(), llvm::writeIndexToFile(), and llvm::writeThinLinkBitcodeToFile().
front() [2/2]
template<typename T, typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::front () const inline
Definition at line 309 of file SmallVector.h.
References assert(), begin(), and empty().
getFirstEl()
template<typename T, typename = void> void * llvm::SmallVectorTemplateCommon< T, typename >::getFirstEl () const inline protected
Find the address of the first element.
For this pointer math to be valid with small-size of 0 for T with lots of alignment, it's important that SmallVectorStorage is properly-aligned even for small-size of 0.
Definition at line 130 of file SmallVector.h.
References offsetof.
Referenced by grow_pod(), isSmall(), llvm::SmallVectorTemplateBase< T, bool >::mallocForGrow(), resetToSmall(), and SmallVectorTemplateCommon().
grow_pod()
template<typename T, typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::grow_pod (size_t MinSize, size_t TSize) inline protected
Definition at line 139 of file SmallVector.h.
References getFirstEl(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::grow_pod().
Referenced by llvm::SmallVectorTemplateBase< T, true >::grow().
isRangeInStorage()
template<typename T, typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isRangeInStorage (const void * First, const void * Last) const inline protected
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
Definition at line 167 of file SmallVector.h.
References begin(), end(), llvm::First, and llvm::Last.
Referenced by llvm::const_iterator< MemoryLocation >::erase().
isReferenceToRange()
template<typename T, typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToRange (const void * V, const void * First, const void * Last) const inline protected
Return true if V is an internal reference to the given range.
Definition at line 154 of file SmallVector.h.
References llvm::First, and llvm::Last.
Referenced by isReferenceToStorage().
isReferenceToStorage()
template<typename T, typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage (const void * V) const inline protected
Return true if V is an internal reference to this vector.
Definition at line 161 of file SmallVector.h.
References begin(), end(), and isReferenceToRange().
Referenced by llvm::const_iterator< MemoryLocation >::erase(), llvm::const_iterator< MemoryLocation >::insert(), llvm::const_iterator< MemoryLocation >::insert(), and isSafeToReferenceAfterResize().
isSafeToReferenceAfterResize()
template<typename T, typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isSafeToReferenceAfterResize (const void * Elt, size_t NewSize) inline protected
Return true unless Elt will be invalidated by resizing the vector to NewSize.
Definition at line 176 of file SmallVector.h.
References begin(), capacity(), isReferenceToStorage(), LLVM_LIKELY, and size().
Referenced by assertSafeToReferenceAfterResize().
isSmall()
template<typename T, typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isSmall () const inline protected
Return true if this is a smallvector which has not had dynamic memory allocated for it.
Definition at line 145 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, and getFirstEl().
Referenced by llvm::const_iterator< MemoryLocation >::assignRemote(), llvm::SmallVectorImpl< T >::swap(), llvm::SmallVectorTemplateBase< T, bool >::takeAllocationForGrow(), and llvm::const_iterator< MemoryLocation >::~SmallVectorImpl().
max_size()
template<typename T, typename = void> size_type llvm::SmallVectorTemplateCommon< T, typename >::max_size () const inline
Definition at line 285 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::SizeTypeMax(), and T.
operator[]() [1/2]
template<typename T, typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::operator[] (size_type idx) inline
Definition at line 296 of file SmallVector.h.
References assert(), begin(), and size().
operator[]() [2/2]
template<typename T, typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::operator[] (size_type idx) const inline
Definition at line 300 of file SmallVector.h.
References assert(), begin(), and size().
rbegin() [1/2]
template<typename T, typename = void> reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rbegin () inline
Definition at line 279 of file SmallVector.h.
References end().
Referenced by EltsFromConsecutiveLoads(), eraseNewInstructions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), foldICmpOrXorSubChain(), llvm::rdf::Liveness::getNearestAliasedRef(), getNoopInput(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rbegin(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rbegin(), rewriteAccessChain(), and llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef().
rbegin() [2/2]
template<typename T, typename = void> const_reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rbegin () const inline
Definition at line 280 of file SmallVector.h.
References end().
rend() [1/2]
template<typename T, typename = void> reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rend () inline
Definition at line 281 of file SmallVector.h.
References begin().
Referenced by EltsFromConsecutiveLoads(), eraseNewInstructions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), foldICmpOrXorSubChain(), llvm::rdf::Liveness::getNearestAliasedRef(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rend(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::rend(), and rewriteAccessChain().
rend() [2/2]
template<typename T, typename = void> const_reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rend () const inline
Definition at line 282 of file SmallVector.h.
References begin().
reserveForParamAndGetAddressImpl()
template<typename T, typename = void> template<class U> const T * llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl (U * This, const T & Elt, size_t N) inline static protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 235 of file SmallVector.h.
References capacity(), LLVM_LIKELY, LLVM_UNLIKELY, N, and T.
Referenced by llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress(), and llvm::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress().
resetToSmall()
template<typename T, typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall () inline protected
Put this vector in a state of being small.
Definition at line 148 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, llvm::SmallVectorBase< SmallVectorSizeType< T > >::Capacity, getFirstEl(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::Size.
size()
template<typename T, typename = void> size_t llvm::SmallVectorBase< SmallVectorSizeType< T > >::size () const inline
Definition at line 80 of file SmallVector.h.
Referenced by AddAliasScopeMetadata(), llvm::SelectionDAGBuilder::addDanglingDebugInfo(), addData(), addEdge(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), llvm::logicalview::LVScope::addMissingElements(), llvm::bfi_detail::IrreducibleGraph::addNodesInLoop(), llvm::addParamAttribute(), llvm::mca::RegisterFile::addRegisterRead(), llvm::DbgValueRangeTable::addVariable(), addVPMetadata(), adjustCostForPairing(), llvm::SITargetLowering::allocatePreloadKernArgSGPRs(), analyzeArgSplit(), AnalyzeArguments(), llvm::CCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallOperands(), analyzeCallOperands(), llvm::CCState::AnalyzeCallResult(), analyzeCompressibleUses(), analyzeExitPHIsForOutputUses(), llvm::CCState::AnalyzeFormalArguments(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::CCState::AnalyzeReturn(), slpvectorizer::BoUpSLP::analyzeRtStrideCandidate(), llvm::const_iterator< MemoryLocation >::append(), llvm::const_iterator< MemoryLocation >::append(), appendToGlobalArray(), llvm::BitVector::apply(), llvm::RISCVVectorMaskDAGMutation::apply(), llvm::CombinerHelper::applyCombineShuffleToBuildVector(), llvm::CombinerHelper::applyCombineUnmergeConstant(), llvm::CombinerHelper::applyCombineUnmergeMergeToPlainValues(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingSMULU64(), areLoadedOffsetButOtherwiseSame(), ARM64FindSegmentsInFunction(), assertSafeToAdd(), llvm::const_iterator< MemoryLocation >::assign(), llvm::object::BigArchive::BigArchive(), llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::build(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildCopyFromRegs(), llvm::buildEnqueueKernel(), BuildExactSDIV(), BuildExactUDIV(), buildFromShuffleMostly(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), buildRegSequence(), buildRegSequence16(), buildRegSequence32(), llvm::TargetLowering::BuildSDIV(), BuildSubAggregate(), llvm::TargetLowering::BuildUDIV(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineIRBuilder::buildUnmerge(), llvm::calculateRegisterUsageForPlan(), calculateRtStride(), canLoopBeDeleted(), llvm::LoongArchTargetLowering::CanLowerReturn(), llvm::RISCVTargetLowering::CanLowerReturn(), llvm::RISCVCallLowering::canLowerReturn(), llvm::X86InstrInfo::canMakeTailCallConditional(), canMergeParamLoadStoresStartingAt(), canonicalizeBitSelect(), canonicalizeShuffleMaskWithHorizOp(), llvm::MachineBasicBlock::canPredictBranchProbabilities(), canPredictSuccessors(), canProfitablyRuntimeUnrollMultiExitLoop(), canSplitCallSite(), canUseSiblingCall(), slpvectorizer::BoUpSLP::canVectorizeLoads(), canWidenShuffleElements(), CC_AArch64_Custom_Block(), CC_ARM_AAPCS_Custom_Aggregate(), CC_LoongArch(), llvm::CC_RISCV(), CC_X86_32_I128_FP128(), CC_X86_32_MCUInReg(), CC_X86_32_RegCall_Assign2Regs(), CC_X86_64_I128(), chainLoadsAndStoresForMemcpy(), checkDependencies(), llvm::Attributor::checkForAllUses(), checkHVXPipes(), TransferTracker::checkInstForNewValues(), checkOrAndOpImpliedByOther(), llvm::CCState::CheckReturn(), llvm::CallLowering::checkReturn(), llvm::checkVOPDRegConstraints(), llvm::CloneAndPruneIntoFromInst(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), clusterSortPtrAccesses(), llvm::collectChildrenInLoop(), collectComplementaryPredicatedMemOps(), collectConcatOps(), llvm::collectGlobalObjectNameStrings(), collectMetadataInfo(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::mca::RegisterFile::collectWrites(), combineAnd(), CombineBaseUpdate(), combineBitcastvxi1(), combineConcatVectorOps(), combineExtractVectorElt(), combineINSERT_SUBVECTOR(), combineOp_VLToVWOp_VL(), combineOr(), combineSelect(), combineSetCCMOVMSK(), combineShuffleToZeroExtendVectorInReg(), combineTargetShuffle(), combineToConsecutiveLoads(), combineVectorShiftImm(), combineVPMADD(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), completeEphemeralValues(), llvm::object::CompressedOffloadBundle::compress(), llvm::EHStreamer::computeActionsTable(), llvm::ComputeASanStackFrameDescription(), llvm::ComputeASanStackFrameLayout(), llvm::WasmException::computeCallSiteTable(), computeFunctionSummary(), computeHeadersSize(), computeParamInfo(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::computeValueLLTs(), llvm::concatenateVectors(), llvm::ConstantFoldTerminator(), ConstructSSAForLoadSet(), convertImageAddrToPacked(), llvm::convertUTF8ToUTF16String(), createCBufferLoad(), llvm::createCFAOffset(), createDefCFAExpression(), createDefCFAExpression(), createDefCFAOffset(), createMergedFunction(), CreateNewABI(), llvm::OpenMPIRBuilder::createOffloadMapnames(), llvm::MDBuilder::createPCSections(), createTblForTrunc(), llvm::sys::fs::createUniquePath(), llvm::mca::ExecuteStage::cycleEnd(), LiveDebugValues::VLocTracker::defVar(), llvm::DependenceInfo::depends(), llvm::orc::deserializeModule(), DoLowering(), doPromotion(), dumpBytes(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), llvm::yaml::SequenceTraits< SmallVector< memprof::GUIDHex64 > >::element(), llvm::embedBitcodeInModule(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::AsmPrinter::emitConstantPool(), emitDarwinBCHeaderAndTrailer(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::emitDWARF5AccelTable(), llvm::PPCFrameLowering::emitEpilogue(), emitExternalFile(), EmitGenDwarfInfo(), llvm::AMDGPUAsmPrinter::emitInstruction(), LiveDebugValues::MLocTracker::emitLoc(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::OpenMPIRBuilder::emitNonContiguousDescriptor(), llvm::OpenMPIRBuilder::emitOffloadingArrays(), llvm::PPCFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::MCStreamer::emitSLEB128IntValue(), emitTargetCall(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), llvm::OpenMPIRBuilder::emitTargetTask(), emitTaskDependencies(), llvm::MCStreamer::emitULEB128IntValue(), llvm::OpenMPIRBuilder::emitUsed(), llvm::const_iterator< MemoryLocation >::emplace_back(), llvm::CodeViewContext::encodeDefRange(), encodeFunctionSignature(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::COFF::encodeSectionName(), end(), end(), llvm::logicalview::LVLine::equals(), llvm::logicalview::LVScope::equals(), llvm::logicalview::LVSymbol::equals(), llvm::logicalview::LVType::equals(), llvm::Evaluator::EvaluateFunction(), llvm::GIMatchTableExecutor::executeMatchTable(), ExpandBVWithShuffles(), llvm::AArch64_IMM::expandMOVImm(), expandMOVImmSimple(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::mir2vec::MIRVocabulary::extractBaseOpcodeName(), llvm::extractBranchWeights(), llvm::extractParts(), llvm::LegalizerHelper::fewerElementsVectorReductions(), fillIndirectionTable(), llvm::ControlFlowHub::finalize(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::CodeExtractor::findAllocas(), llvm::findArrayDimensions(), findArrayDimensionsRec(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), findBestInsertionSet(), findBuildAggregate(), findContiguousCases(), findForkedSCEVs(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::sampleprof::FunctionSamples::findFunctionSamples(), llvm::FindInsertedValue(), findOrCreatePHIInBlock(), findRematerializationCandidates(), slpvectorizer::BoUpSLP::findReusedOrderedScalars(), llvm::AMDGPU::RegBankLegalizeHelper::findRuleAndApplyMapping(), llvm::MachineInstr::findTiedOperandIdx(), llvm::SplitEditor::finish(), llvm::DWARFUnitVector::finishedInfoUnits(), fixupShuffleMaskForPermutedSToV(), llvm::PGOContextualProfile::flatten(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), llvm::foldBranchToCommonDest(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::FoldConstantBuildVector(), llvm::DIExpression::foldConstantMath(), foldExtractSubvectorFromShuffleVector(), foldInlineAsmMemOperand(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::InstCombinerImpl::foldPHIArgGEPIntoPHI(), foldSelectShuffleOfSelectShuffle(), foldTwoEntryPHINode(), llvm::memtag::forAllReachableExits(), llvm::InformationCache::foreachUse(), llvm::FmtAlign::format(), formLCSSAForInstructionsImpl(), forwardSwitchConditionToPHI(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), generateGatherLanePattern(), llvm::LoongArchMatInt::generateInstSeq(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqLeadingZeros(), generateNewInstTree(), llvm::PredIteratorCache::get(), llvm::RecordRecTy::get(), llvm::TargetInstrInfo::getAccumulatorReassociationPatterns(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), getAppleRuntimeUnrollPreferences(), llvm::Attributor::getAssumedSimplifiedValues(), llvm::omp::getBestVariantMatchForContext(), getBranchWeights(), getBuildVectorizedValue(), llvm::getDisjunctionWeights(), llvm::MCContext::getELFSection(), getEmscriptenInvokeSymbolName(), llvm::GenericCycle< ContextT >::getExitBlocks(), llvm::object::SFrameParser< E >::getExtraOffsets(), getFauxShuffleMask(), getFPFastMathDefaultInfo(), getGEPCosts(), llvm::sys::detail::getHostCPUNameForARM(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::DWARFContext::getInliningInfoForAddress(), llvm::logicalview::getInnerComponent(), getInstSeqCost(), llvm::AArch64TTIImpl::getIntImmCost(), getIntOperandFromRegisterString(), getIntOperandsFromRegisterString(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::RISCVTTIImpl::getIntrinsicInstrCost(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), getMatchedEntries(), llvm::ExpressionFormat::getMatchingString(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), getMemcpyLoadsAndStores(), llvm::TargetInstrInfo::getMemOperandWithOffset(), getMinAnalyzeableBackedgeTakenCount(), getMnemonicOpsEndInd(), llvm::MDNode::getMostGenericRange(), getNarrowMaskForInterleavedOps(), getNoopInput(), llvm::DWARFUnitVector::getNumInfoUnits(), llvm::DWARFUnitVector::getNumTypesUnits(), llvm::DWARFUnitVector::getNumUnits(), getOpEnabled(), getOpRefinementSteps(), getOrCreateFrameHelper(), llvm::DXContainerYAML::RootParameterYamlDesc::getOrInsertImpl(), llvm::HvxSelector::getPerfectCompletions(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), getPreStartForExtend(), llvm::FileCollectorFileSystem::getRealPath(), llvm::AArch64RegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), getRegListInd(), slpvectorizer::BoUpSLP::getReorderingData(), llvm::DominatorTreeBase< BlockT, false >::getRoot(), getSameOpcode(), llvm::GetShadowBytes(), llvm::GCNTTIImpl::getShuffleCost(), getShuffleInput(), llvm::opt::ArgList::getSubCommand(), getTargetConstantBitsFromNode(), getTargetShuffleMask(), llvm::SelectionDAG::getTokenFactor(), llvm::SelectionDAG::getTopologicallyOrderedNodes(), slpvectorizer::BoUpSLP::getTreeCost(), getTwoPredecessors(), llvm::BasicTTIImplBase< BasicTTIImpl >::getTypeBasedIntrinsicInstrCost(), getTypeWithoutPadding(), llvm::ScalarEvolution::getUDivExpr(), getUnmergeResults(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::SSAUpdaterImpl< UpdaterT >::GetValue(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::getValueProfDataFromInst(), getVariantMatchScore(), llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack(), llvm::CallLowering::handleAssignments(), HandleMergeInputChains(), handleNBranch(), hasHazard(), llvm::HexagonMCShuffle(), hoistLockstepIdenticalDbgVariableRecords(), hoistMulAddAssociation(), hoistPreviousBeforeFORUsers(), llvm::cas::ObjectStore::importObject(), INITIALIZE_PASS(), INITIALIZE_PASS(), initializeUniqueCases(), llvm::mca::initializeUsedResources(), llvm::InlineFunctionImpl(), llvm::const_iterator< MemoryLocation >::insert(), llvm::const_iterator< MemoryLocation >::insert(), llvm::insertDebugValuesForPHIs(), insertInlineAsm(), insertInlineAsmProcess(), insertParsePoints(), llvm::CallLowering::insertSRetIncomingArgument(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), insertValues(), instCombineSVEDupqLane(), llvm::intersectAccessGroups(), isCheapImmediate(), isConstantPowerOf2(), llvm::X86::isConstantSplat(), isFNEG(), llvm::AArch64TargetLowering::isFPImmLegal(), llvm::VPBlockUtils::isHeader(), isHorizontalBinOp(), isInvalidVOPDY(), isMaskedLoadCompress(), IsMemoryAssignmentError(), llvm::AArch64TargetLowering::isMulAddWithConstProfitable(), isPointerValueDeadOnEntryToFunction(), isPotentiallyReachable(), isProfitable(), isSafeToReferenceAfterResize(), isSlicingProfitable(), llvm::memtag::isStandardLifetime(), llvm::mca::ResourceManager::issueInstructionImpl(), slpvectorizer::BoUpSLP::isTreeTinyAndNotFullyVectorizable(), isUpperSubvectorUndef(), isVECTOR_SHUFFLE_SPLATI(), llvm::LiveRange::join(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm_getMetadata(), LLVMCopyModuleFlagsMetadata(), LLVMDisasmInstruction(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), LLVMGetRelocationTypeName(), LLVMOrcExecutionSessionLookup(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::object::ELFFile< ELFT >::loadVersionMap(), llvm::lookupBuiltin(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerBUILD_VECTOR(), lowerBuildVectorViaPacking(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), lowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerCONCAT_VECTORS_i1(), lowerConstant(), llvm::LegalizerHelper::lowerExtract(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AArch64TargetLowering::lowerInterleaveIntrinsicToStore(), lowerPtrAnnotation(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerShift(), lowerShuffleAsBlend(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleViaVRegSplitting(), lowerShuffleWithUndefHalf(), lowerStatepointMetaArgs(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I32Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), lowerVECTOR_SHUFFLE_XVSHUF(), lowerVECTOR_SHUFFLEAsVRGatherVX(), lowerVECTOR_SHUFFLEAsVSlidedown(), llvm::makeFollowupLoopID(), makeStatepointExplicit(), makeStatepointExplicitImpl(), llvm::Pattern::match(), llvm::Regex::match(), matchBinaryPermuteShuffle(), llvm::CombinerHelper::matchCombineMergeUnmerge(), llvm::Intrinsic::matchIntrinsicSignature(), matchIntrinsicType(), llvm::CombinerHelper::matchNotCmp(), matchPERM(), llvm::CombinerHelper::matchRepeatedFPDivisor(), matchScalarReduction(), matchShuffleAsByteRotate(), matchShuffleAsByteRotate(), MatchVectorAllEqualTest(), MaybePredicatedInst(), llvm::GlobalMergeFunc::merge(), llvm::MergeBasicBlockIntoOnlyPred(), mergePartStores(), mergeVectorRegsToResultRegs(), llvm::LegalizerHelper::moreElementsVector(), llvm::RISCVInstrInfo::movImm(), llvm::InjectorIRStrategy::mutate(), llvm::InsertCFGStrategy::mutate(), llvm::InsertFunctionStrategy::mutate(), llvm::SinkInstructionStrategy::mutate(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::LegalizerHelper::narrowScalarShiftByConstantMultiway(), llvm::sys::unicode::nearestMatchesForCodepointName(), llvm::EscapeEnumerator::Next(), llvm::Triple::normalize(), numberOfInstrToLoadImm(), Predicate::operator&&(), llvm::memprof::CallStackIdConverter< MapTy >::operator()(), llvm::orc::BlockFreqQuery::operator()(), llvm::BitTracker::RegisterCell::operator<<, llvm::raw_ostream::operator<<(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::BitTracker::RegisterCell::operator==(), llvm::const_iterator< MemoryLocation >::operator==(), operator[](), operator[](), Predicate::operator||(), OptimizeAwayTrappingUsesOfValue(), llvm::PPCInstrInfo::optimizeCompareInstr(), slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeLoopExitWithUnknownExitCount(), optimizeModularFormat(), llvm::HexagonFrameLowering::orderFrameObjects(), llvm::SystemZELFFrameLowering::orderFrameObjects(), packSegmentMask(), llvm::CallLowering::parametersInCSRMatch(), llvm::TargetLowering::parametersInCSRMatch(), llvm::MachO::PackedVersion::parse32(), llvm::MachO::PackedVersion::parse64(), parseAnnotation(), llvm::ARM::parseBranchProtection(), llvm::SPIRV::parseBuiltinCallArgumentBaseType(), llvm::cl::ParseCommandLineOptions(), parseScalarValue(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::MCContext::parseSymbol(), performBitcastCombine(), performExtBinopLoadFold(), performInterleavedMaskedStoreCombine(), llvm::performOptimizedStructLayout(), performOrXorChainCombine(), PerformSplittingToWideningLoad(), performVECTOR_SHUFFLECombine(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, true >::pop_back(), llvm::const_iterator< MemoryLocation >::pop_back_n(), populateDependencyMatrix(), llvm::SystemZInstrInfo::prepareCompareSwapOperands(), llvm::prepareTempFiles(), llvm::InstCombinerImpl::prepareWorklist(), previousEqual(), PrintLoopInfo(), processBlockAddr(), llvm::JumpThreadingPass::processBranchOnXOR(), slpvectorizer::BoUpSLP::processBuildVector(), processCallSite(), ProcessElementList(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVBinaryReader::processLines(), processSwitchesConstants(), llvm::JumpThreadingPass::processThreadableEdges(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::coverage::RawCoverageMappingReader::read(), llvm::SymbolRemappingReader::read(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::sys::fs::readNativeFileToEOF(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::BitstreamCursor::readRecord(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::RecursivelyDeleteTriviallyDeadInstructionsPermissive(), llvm::TargetInstrInfo::reduceAccumulatorTree(), llvm::LegalizerHelper::reduceLoadStoreWidth(), RefineErrorLoc(), RefineErrorLoc(), relocationViaAlloca(), rematerializeLiveValuesAtUses(), llvm::sys::path::remove_dots(), removeFromUsedList(), removeGlobalCtors(), removeIdenticalIndexPair(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdges(), llvm::MemorySSAUpdater::removeMemoryAccess(), removeRedundantBlockingStores(), slpvectorizer::BoUpSLP::reorderBottomToTop(), reorderReuses(), reorderScalars(), replaceArgumentUses(), llvm::X86InstrInfo::replaceBranchWithTailCall(), llvm::CallGraphNode::replaceCallEdge(), replaceLoadVector(), replaceUndefValuesInPhi(), llvm::const_iterator< MemoryLocation >::resize(), resolveSources(), resolveTargetShuffleInputsAndMask(), RestoreSpillList(), llvm::CallLowering::resultsCompatible(), llvm::LanaiInstrInfo::reverseBranchCondition(), llvm::DropUnnecessaryAssumesPass::run(), llvm::FunctionSpecializer::run(), llvm::InlinerPass::run(), llvm::ModuleInlinerPass::run(), llvm::LoopVectorizePass::runImpl(), runImpl(), runIPSCCP(), runMoveAutoInit(), llvm::salvageDebugInfoForDbgValues(), SalvageDVI(), scaleShuffleElements(), llvm::SelectionDAGISel::SelectCodeCommon(), selectImm(), llvm::FastISel::selectPatchpoint(), selectWMMAModsNegAbs(), selectWMMAModsNegAbs(), llvm::StableFunctionMapRecord::serialize(), setSpecialRefs(), setUsedInitializer(), llvm::SIMachineFunctionInfo::shiftWwmVGPRsToLowestRange(), llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm(), shouldTryInjectBasingOnMetadata(), shouldUseFrameHelper(), simplifyBranchConditionForVFAndUF(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::simplifyLoop(), simplifyRecipe(), simplifySelectInst(), simplifySwitchOfPowersOfTwo(), SimplifyValuePattern(), simplifyWithOpsReplaced(), sinkCommonCodeFromPredecessors(), sinkInstruction(), sinkLastInstruction(), sinkLifetimeStartMarkers(), sinkRecurrenceUsersAfterPrevious(), sinkScalarOperands(), llvm::yaml::SequenceTraits< SmallVector< memprof::GUIDHex64 > >::size(), size_in_bytes(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), llvm::DominatorTreeBase< BlockT, false >::Split(), llvm::SubtargetFeatures::Split(), splitAddSubImm(), llvm::splitBlockBefore(), SplitBlockImpl(), splitCallSite(), llvm::coro::AnyRetconABI::splitCoroutine(), llvm::coro::AsyncABI::splitCoroutine(), llvm::CallLowering::splitToValueTypes(), splitVector(), StoreTailCallArgumentsToStackSlot(), llvm::Regex::sub(), substituteSimpleCopyRegs(), llvm::SmallVectorImpl< T >::swap(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::BTFParser::symbolize(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::JumpThreadingPass::threadEdge(), llvm::TimerGroup::TimerGroup(), llvm::CodeViewYAML::toDebugH(), llvm::mustache::tokenize(), llvm::Twine::toNullTerminatedStringRef(), llvm::Twine::toStringRef(), transformGlobalArray(), transformInitializer(), translateLoopMetadata(), llvm::PHITransAddr::translateWithInsertion(), llvm::Triple::Triple(), llvm::const_iterator< MemoryLocation >::truncate(), tryBuildVectorShuffle(), AMDGPURegBankLegalizeCombiner::tryEliminateReadAnyLane(), AMDGPURegBankLegalizeCombiner::tryMatchUnmergeDefs(), tryMergeRange(), trySwitchToSelect(), tryToFindDuplicates(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), tryToVectorizeSequence(), llvm::coverage::mcdc::TVIdxBuilder::TVIdxBuilder(), llvm::IntEqClasses::uncompress(), unifyLoopExits(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), unswitchTrivialSwitch(), UpdateAnalysisInformation(), llvm::DominatorTreeBase< BlockT, false >::updateBlockNumbers(), updateBranchWeights(), updateIDTMetaData(), llvm::UpgradeModuleFlags(), llvm::UpgradeNVVMAnnotations(), upgradeRetainReleaseMarker(), validateMemOp(), ValidateMVEStore(), llvm::HexagonShuffler::ValidResourceUsage(), llvm::SLPVectorizerPass::vectorizeCmpInsts(), VectorizePTXValueVTs(), slpvectorizer::BoUpSLP::vectorizeTree(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::SCEVDivision::visitAddExpr(), llvm::SelectionDAGBuilder::visitDbgInfo(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::SCEVDivision::visitMulExpr(), widenBuildVector(), llvm::widenShuffleMaskElts(), llvm::widenShuffleMaskElts(), widenVectorOpsToi8(), llvm::coverage::CoverageFilenamesSectionWriter::write(), llvm::mcdxbc::RootSignatureDesc::write(), llvm::mcdxbc::Signature::write(), llvm::objcopy::elf::BinaryWriter::write(), llvm::writeArchiveToStream(), llvm::WriteBitcodeToFile(), llvm::objcopy::elf::IHexSectionWriter::writeData(), llvm::dxil::WriteDXILToFile(), llvm::writeIndexToFile(), llvm::writeMemProfSchema(), llvm::DXContainerObjectWriter::writeObject(), llvm::BitcodeWriter::writeSymtab(), llvm::writeThinLinkBitcodeToFile(), writeUniversalArchsToStream(), and llvm::sampleprof::SampleProfileWriter::writeWithSizeLimitInternal().
size_in_bytes()
template<typename T, typename = void> size_type llvm::SmallVectorTemplateCommon< T, typename >::size_in_bytes () const inline
Definition at line 284 of file SmallVector.h.
References size(), and T.
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallVector.h