LLVM: llvm::ms_demangle::Demangler Class Reference
llvm::ms_demangle::Demangler Class Reference
#include "llvm/Demangle/MicrosoftDemangle.h"
Public Member Functions
Demangler ()=default
virtual ~Demangler ()=default
DEMANGLE_ABI SymbolNode * parse (std::string_view &MangledName)
DEMANGLE_ABI TagTypeNode * parseTagUniqueName (std::string_view &MangledName)
DEMANGLE_ABI void dumpBackReferences ()
Public Attributes
bool Error = false
Friends
std::optional< size_t > llvm::getArm64ECInsertionPointInMangledName (std::string_view MangledName)
Detailed Description
Definition at line 145 of file MicrosoftDemangle.h.
Constructor & Destructor Documentation
Demangler()
Demangler::Demangler () default
Definition at line 556 of file DLangDemangle.cpp.
~Demangler()
virtual llvm::ms_demangle::Demangler::~Demangler () virtual default
References DEMANGLE_ABI.
Member Function Documentation
dumpBackReferences()
void Demangler::dumpBackReferences ()
Definition at line 2476 of file MicrosoftDemangle.cpp.
References B(), I, llvm::ms_demangle::OF_Default, and T.
parse()
SymbolNode * Demangler::parse (std::string_view & MangledName)
Definition at line 880 of file MicrosoftDemangle.cpp.
References consumeFront(), and Error.
parseTagUniqueName()
TagTypeNode * Demangler::parseTagUniqueName (std::string_view & MangledName)
Definition at line 906 of file MicrosoftDemangle.cpp.
References consumeFront(), and Error.
Friends And Related Symbol Documentation
llvm::getArm64ECInsertionPointInMangledName
std::optional< size_t > llvm::getArm64ECInsertionPointInMangledName (std::string_view MangledName) friend
Member Data Documentation
Error
bool llvm::ms_demangle::Demangler::Error = false
Definition at line 160 of file MicrosoftDemangle.h.
Referenced by parse(), and parseTagUniqueName().
The documentation for this class was generated from the following files:
include/llvm/Demangle/MicrosoftDemangle.h
lib/Demangle/DLangDemangle.cpp
lib/Demangle/MicrosoftDemangle.cpp
lib/Demangle/RustDemangle.cpp