LLVM: llvm::codeview::ObjNameSym Class Reference
llvm::codeview::ObjNameSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
ObjNameSym ()
ObjNameSym (SymbolRecordKind Kind)
ObjNameSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
uint32_t Signature = 0
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 677 of file SymbolRecord.h.
Constructor & Destructor Documentation
ObjNameSym() [1/3]
llvm::codeview::ObjNameSym::ObjNameSym () inline explicit
Definition at line 679 of file SymbolRecord.h.
References ObjNameSym(), and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by ObjNameSym(), and ObjNameSym().
ObjNameSym() [2/3]
llvm::codeview::ObjNameSym::ObjNameSym (SymbolRecordKind Kind) inline explicit
Definition at line 680 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
ObjNameSym() [3/3]
llvm::codeview::ObjNameSym::ObjNameSym (uint32_t RecordOffset) inline explicit
Definition at line 681 of file SymbolRecord.h.
References ObjNameSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Data Documentation
Name
StringRef llvm::codeview::ObjNameSym::Name
Definition at line 686 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
RecordOffset
uint32_t llvm::codeview::ObjNameSym::RecordOffset = 0
Definition at line 688 of file SymbolRecord.h.
Referenced by ObjNameSym().
Signature
uint32_t llvm::codeview::ObjNameSym::Signature = 0
Definition at line 685 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h