LLVM: llvm::OnDiskIterableChainedHashTable< Info >::key_iterator Class Reference
llvm::OnDiskIterableChainedHashTable< Info >::key_iterator Class Reference
Iterates over all of the keys in the table.
#include "llvm/Support/OnDiskHashTable.h"
Public Types
using value_type = external_key_type
Public Member Functions
key_iterator (const unsigned char *const Ptr, offset_type NumEntries, Info *InfoObj)
key_iterator ()
key_iterator & operator++ ()
key_iterator operator++ (int)
internal_key_type getInternalKey () const
value_type operator* () const
Detailed Description
template<typename Info>
class llvm::OnDiskIterableChainedHashTable< Info >::key_iterator
Iterates over all of the keys in the table.
Definition at line 504 of file OnDiskHashTable.h.
Member Typedef Documentation
value_type
template<typename Info> using llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::value_type = external_key_type
Definition at line 508 of file OnDiskHashTable.h.
Constructor & Destructor Documentation
key_iterator() [1/2]
template<typename Info> llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::key_iterator (const unsigned char *const Ptr, offset_type NumEntries, Info * InfoObj) inline
Definition at line 510 of file OnDiskHashTable.h.
References Info.
Referenced by operator++(), and operator++().
key_iterator() [2/2]
template<typename Info> llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::key_iterator () inline
Definition at line 513 of file OnDiskHashTable.h.
Member Function Documentation
getInternalKey()
template<typename Info> internal_key_type llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::getInternalKey () const inline
Definition at line 525 of file OnDiskHashTable.h.
Referenced by operator*().
operator*()
template<typename Info> value_type llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator* () const inline
Definition at line 535 of file OnDiskHashTable.h.
References getInternalKey().
operator++() [1/2]
template<typename Info> key_iterator & llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator++ () inline
Definition at line 515 of file OnDiskHashTable.h.
References key_iterator().
operator++() [2/2]
template<typename Info> key_iterator llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator++ (int) inline
Definition at line 519 of file OnDiskHashTable.h.
References key_iterator().
The documentation for this class was generated from the following file:
include/llvm/Support/OnDiskHashTable.h