LLVM: llvm::NVPTXSubtarget Class Reference
llvm::NVPTXSubtarget Class Reference
#include "Target/NVPTX/NVPTXSubtarget.h"
Public Member Functions
NVPTXSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const NVPTXTargetMachine &TM)
This constructor initializes the data members to match that of the specified module.
~NVPTXSubtarget () override
const TargetFrameLowering * getFrameLowering () const override
const NVPTXInstrInfo * getInstrInfo () const override
const NVPTXRegisterInfo * getRegisterInfo () const override
const NVPTXTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool hasPTXWithFamilySMs (unsigned PTXVersion, ArrayRef< unsigned > SMVersions) const
bool hasPTXWithAccelSMs (unsigned PTXVersion, ArrayRef< unsigned > SMVersions) const
bool has256BitVectorLoadStore (unsigned AS) const
bool hasUsedBytesMaskPragma () const
bool hasAtomAddF64 () const
bool hasAtomScope () const
bool hasAtomBitwise64 () const
bool hasAtomMinMax64 () const
bool hasAtomCas16 () const
bool hasAtomSwap128 () const
bool hasClusters () const
bool hasLDG () const
bool hasHWROT32 () const
bool hasBrx () const
bool hasFP16Math () const
bool hasBF16Math () const
bool allowFP16Math () const
bool hasMaskOperator () const
bool hasNoReturn () const
bool hasMemoryOrdering () const
bool hasSplitAcquireAndReleaseFences () const
bool hasRelaxedMMIO () const
bool hasDotInstructions () const
bool hasTcgen05InstSupport () const
bool hasTcgen05ShiftSupport () const
bool hasTcgen05MMAScaleInputDImm () const
bool hasTcgen05MMAI8Kind () const
bool hasTcgen05MMASparseMxf4nvf4 () const
bool hasTcgen05MMASparseMxf4 () const
bool hasReduxSyncF32 () const
bool hasMMABlockScale () const
bool hasMMASparseBlockScaleF4 () const
bool hasF32x2Instructions () const
bool hasTMABlackwellSupport () const
bool hasFP8ConversionSupport () const
bool hasNarrowFPConversionSupport () const
bool hasTensormapReplaceSupport () const
bool hasTensormapReplaceElemtypeSupport (unsigned value) const
bool hasTensormapReplaceSwizzleAtomicitySupport () const
bool hasTensormapReplaceSwizzleModeSupport (unsigned value) const
bool hasClusterLaunchControlTryCancelMulticastSupport () const
bool hasSetMaxNRegSupport () const
bool hasLdStmatrixBlackwellSupport () const
bool hasPTXASUnreachableBug () const
bool hasCvtaParam () const
bool hasConvertWithStochasticRounding () const
unsigned int getFullSmVersion () const
unsigned int getSmVersion () const
unsigned int getSmFamilyVersion () const
bool hasArchAccelFeatures () const
bool hasFamilySpecificFeatures () const
std::string getTargetName () const
bool hasTargetName () const
bool hasNativeBF16Support (int Opcode) const
unsigned getMaxRequiredAlignment () const
unsigned getMinCmpXchgSizeInBits () const
unsigned getPTXVersion () const
NVPTXSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
void failIfClustersUnsupported (std::string const &FailureMessage) const
Detailed Description
Definition at line 32 of file NVPTXSubtarget.h.
Constructor & Destructor Documentation
NVPTXSubtarget()
NVPTXSubtarget::NVPTXSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const NVPTXTargetMachine & TM)
This constructor initializes the data members to match that of the specified module.
Definition at line 148 of file NVPTXSubtarget.cpp.
References getSmVersion(), and initializeSubtargetDependencies().
Referenced by initializeSubtargetDependencies().
~NVPTXSubtarget()
NVPTXSubtarget::~NVPTXSubtarget () override default
Member Function Documentation
allowFP16Math()
bool NVPTXSubtarget::allowFP16Math () const
Definition at line 197 of file NVPTXSubtarget.cpp.
References hasFP16Math(), and NoF16Math.
failIfClustersUnsupported()
void NVPTXSubtarget::failIfClustersUnsupported (std::string const & FailureMessage) const
Definition at line 237 of file NVPTXSubtarget.cpp.
References llvm::formatv(), getFullSmVersion(), hasClusters(), and llvm::report_fatal_error().
getFrameLowering()
const TargetFrameLowering * llvm::NVPTXSubtarget::getFrameLowering () const inline override
Definition at line 65 of file NVPTXSubtarget.h.
getFullSmVersion()
unsigned int llvm::NVPTXSubtarget::getFullSmVersion () const inline
Definition at line 272 of file NVPTXSubtarget.h.
Referenced by failIfClustersUnsupported(), getSmFamilyVersion(), getSmVersion(), hasArchAccelFeatures(), and hasFamilySpecificFeatures().
getInstrInfo()
const NVPTXInstrInfo * llvm::NVPTXSubtarget::getInstrInfo () const inline override
Definition at line 68 of file NVPTXSubtarget.h.
getMaxRequiredAlignment()
unsigned llvm::NVPTXSubtarget::getMaxRequiredAlignment () const inline
Definition at line 308 of file NVPTXSubtarget.h.
getMinCmpXchgSizeInBits()
unsigned llvm::NVPTXSubtarget::getMinCmpXchgSizeInBits () const inline
Definition at line 310 of file NVPTXSubtarget.h.
getPTXVersion()
unsigned llvm::NVPTXSubtarget::getPTXVersion () const inline
Definition at line 312 of file NVPTXSubtarget.h.
Referenced by llvm::NVPTXAsmPrinter::doInitialization(), hasNativeBF16Support(), hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
getRegisterInfo()
const NVPTXRegisterInfo * llvm::NVPTXSubtarget::getRegisterInfo () const inline override
Definition at line 69 of file NVPTXSubtarget.h.
Referenced by isCVTAToLocalCombinationCandidate().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * NVPTXSubtarget::getSelectionDAGInfo () const override
Definition at line 159 of file NVPTXSubtarget.cpp.
getSmFamilyVersion()
unsigned int llvm::NVPTXSubtarget::getSmFamilyVersion () const inline
Definition at line 274 of file NVPTXSubtarget.h.
References getFullSmVersion().
Referenced by hasPTXWithFamilySMs().
getSmVersion()
unsigned int llvm::NVPTXSubtarget::getSmVersion () const inline
Definition at line 273 of file NVPTXSubtarget.h.
References getFullSmVersion().
Referenced by llvm::NVPTXAsmPrinter::doInitialization(), hasNativeBF16Support(), hasPTXWithAccelSMs(), hasPTXWithFamilySMs(), initializeSubtargetDependencies(), and NVPTXSubtarget().
getTargetLowering()
const NVPTXTargetLowering * llvm::NVPTXSubtarget::getTargetLowering () const inline override
Definition at line 72 of file NVPTXSubtarget.h.
Referenced by handleByValParam(), and runOnDeviceFunction().
getTargetName()
std::string llvm::NVPTXSubtarget::getTargetName () const inline
Definition at line 294 of file NVPTXSubtarget.h.
Referenced by initializeSubtargetDependencies().
has256BitVectorLoadStore()
bool llvm::NVPTXSubtarget::has256BitVectorLoadStore (unsigned AS) const inline
Definition at line 90 of file NVPTXSubtarget.h.
References llvm::NVPTXAS::ADDRESS_SPACE_GLOBAL.
Referenced by getVectorLoweringShape().
hasArchAccelFeatures()
bool llvm::NVPTXSubtarget::hasArchAccelFeatures () const inline
Definition at line 281 of file NVPTXSubtarget.h.
References getFullSmVersion().
Referenced by hasFamilySpecificFeatures(), and hasPTXWithAccelSMs().
hasAtomAddF64()
bool llvm::NVPTXSubtarget::hasAtomAddF64 () const inline
Definition at line 97 of file NVPTXSubtarget.h.
hasAtomBitwise64()
bool llvm::NVPTXSubtarget::hasAtomBitwise64 () const inline
Definition at line 99 of file NVPTXSubtarget.h.
hasAtomCas16()
bool llvm::NVPTXSubtarget::hasAtomCas16 () const inline
Definition at line 101 of file NVPTXSubtarget.h.
hasAtomMinMax64()
bool llvm::NVPTXSubtarget::hasAtomMinMax64 () const inline
Definition at line 100 of file NVPTXSubtarget.h.
hasAtomScope()
bool llvm::NVPTXSubtarget::hasAtomScope () const inline
Definition at line 98 of file NVPTXSubtarget.h.
hasAtomSwap128()
bool llvm::NVPTXSubtarget::hasAtomSwap128 () const inline
Definition at line 102 of file NVPTXSubtarget.h.
Referenced by replaceAtomicSwap128().
hasBF16Math()
bool llvm::NVPTXSubtarget::hasBF16Math () const inline
Definition at line 108 of file NVPTXSubtarget.h.
Referenced by hasNativeBF16Support().
hasBrx()
bool llvm::NVPTXSubtarget::hasBrx () const inline
Definition at line 106 of file NVPTXSubtarget.h.
hasClusterLaunchControlTryCancelMulticastSupport()
bool llvm::NVPTXSubtarget::hasClusterLaunchControlTryCancelMulticastSupport () const inline
Definition at line 241 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasClusters()
bool llvm::NVPTXSubtarget::hasClusters () const inline
Definition at line 103 of file NVPTXSubtarget.h.
Referenced by failIfClustersUnsupported().
hasConvertWithStochasticRounding()
bool llvm::NVPTXSubtarget::hasConvertWithStochasticRounding () const inline
Definition at line 269 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs().
hasCvtaParam()
bool llvm::NVPTXSubtarget::hasCvtaParam () const inline
Definition at line 268 of file NVPTXSubtarget.h.
Referenced by handleByValParam().
hasDotInstructions()
bool llvm::NVPTXSubtarget::hasDotInstructions () const inline
Definition at line 121 of file NVPTXSubtarget.h.
hasF32x2Instructions()
bool NVPTXSubtarget::hasF32x2Instructions () const
Definition at line 201 of file NVPTXSubtarget.cpp.
References NoF32x2.
Referenced by getVectorLoweringShape().
hasFamilySpecificFeatures()
bool llvm::NVPTXSubtarget::hasFamilySpecificFeatures () const inline
Definition at line 289 of file NVPTXSubtarget.h.
References getFullSmVersion(), and hasArchAccelFeatures().
Referenced by hasPTXWithFamilySMs().
hasFP16Math()
bool llvm::NVPTXSubtarget::hasFP16Math () const inline
Definition at line 107 of file NVPTXSubtarget.h.
Referenced by allowFP16Math().
hasFP8ConversionSupport()
bool llvm::NVPTXSubtarget::hasFP8ConversionSupport () const inline
Definition at line 193 of file NVPTXSubtarget.h.
hasHWROT32()
bool llvm::NVPTXSubtarget::hasHWROT32 () const inline
Definition at line 105 of file NVPTXSubtarget.h.
hasLDG()
bool llvm::NVPTXSubtarget::hasLDG () const inline
Definition at line 104 of file NVPTXSubtarget.h.
Referenced by canLowerToLDG().
hasLdStmatrixBlackwellSupport()
bool llvm::NVPTXSubtarget::hasLdStmatrixBlackwellSupport () const inline
Definition at line 254 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasMaskOperator()
bool llvm::NVPTXSubtarget::hasMaskOperator () const inline
Definition at line 110 of file NVPTXSubtarget.h.
hasMemoryOrdering()
bool llvm::NVPTXSubtarget::hasMemoryOrdering () const inline
Definition at line 114 of file NVPTXSubtarget.h.
hasMMABlockScale()
bool llvm::NVPTXSubtarget::hasMMABlockScale () const inline
Definition at line 170 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasMMASparseBlockScaleF4()
bool llvm::NVPTXSubtarget::hasMMASparseBlockScaleF4 () const inline
Definition at line 174 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs().
hasNarrowFPConversionSupport()
bool llvm::NVPTXSubtarget::hasNarrowFPConversionSupport () const inline
Definition at line 207 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasNativeBF16Support()
bool NVPTXSubtarget::hasNativeBF16Support (int Opcode) const
Definition at line 205 of file NVPTXSubtarget.cpp.
References llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FRINT, llvm::ISD::FROUNDEVEN, llvm::ISD::FSUB, llvm::ISD::FTRUNC, getPTXVersion(), getSmVersion(), hasBF16Math(), llvm::ISD::SELECT, llvm::ISD::SELECT_CC, and llvm::ISD::SETCC.
hasNoReturn()
bool llvm::NVPTXSubtarget::hasNoReturn () const inline
Definition at line 111 of file NVPTXSubtarget.h.
hasPTXASUnreachableBug()
bool llvm::NVPTXSubtarget::hasPTXASUnreachableBug () const inline
Definition at line 267 of file NVPTXSubtarget.h.
hasPTXWithAccelSMs()
bool NVPTXSubtarget::hasPTXWithAccelSMs (unsigned PTXVersion, ArrayRef< unsigned > SMVersions) const
Definition at line 182 of file NVPTXSubtarget.cpp.
References llvm::any_of(), getPTXVersion(), getSmVersion(), hasArchAccelFeatures(), and SM().
Referenced by hasClusterLaunchControlTryCancelMulticastSupport(), hasConvertWithStochasticRounding(), hasLdStmatrixBlackwellSupport(), hasMMABlockScale(), hasMMASparseBlockScaleF4(), hasNarrowFPConversionSupport(), hasReduxSyncF32(), hasSetMaxNRegSupport(), hasTcgen05InstSupport(), hasTcgen05MMAI8Kind(), hasTcgen05MMAScaleInputDImm(), hasTcgen05MMASparseMxf4(), hasTcgen05MMASparseMxf4nvf4(), hasTcgen05ShiftSupport(), hasTensormapReplaceElemtypeSupport(), hasTensormapReplaceSupport(), hasTensormapReplaceSwizzleAtomicitySupport(), hasTensormapReplaceSwizzleModeSupport(), and hasTMABlackwellSupport().
hasPTXWithFamilySMs()
bool NVPTXSubtarget::hasPTXWithFamilySMs (unsigned PTXVersion, ArrayRef< unsigned > SMVersions) const
Definition at line 163 of file NVPTXSubtarget.cpp.
References llvm::any_of(), getPTXVersion(), getSmFamilyVersion(), getSmVersion(), hasFamilySpecificFeatures(), and SM().
Referenced by hasClusterLaunchControlTryCancelMulticastSupport(), hasLdStmatrixBlackwellSupport(), hasMMABlockScale(), hasNarrowFPConversionSupport(), hasReduxSyncF32(), hasSetMaxNRegSupport(), hasTcgen05InstSupport(), hasTcgen05MMAScaleInputDImm(), hasTensormapReplaceElemtypeSupport(), hasTensormapReplaceSupport(), hasTensormapReplaceSwizzleAtomicitySupport(), and hasTMABlackwellSupport().
hasReduxSyncF32()
bool llvm::NVPTXSubtarget::hasReduxSyncF32 () const inline
Definition at line 166 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasRelaxedMMIO()
bool llvm::NVPTXSubtarget::hasRelaxedMMIO () const inline
Definition at line 120 of file NVPTXSubtarget.h.
hasSetMaxNRegSupport()
bool llvm::NVPTXSubtarget::hasSetMaxNRegSupport () const inline
Definition at line 247 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasSplitAcquireAndReleaseFences()
bool llvm::NVPTXSubtarget::hasSplitAcquireAndReleaseFences () const inline
Definition at line 116 of file NVPTXSubtarget.h.
hasTargetName()
bool llvm::NVPTXSubtarget::hasTargetName () const inline
Definition at line 297 of file NVPTXSubtarget.h.
hasTcgen05InstSupport()
bool llvm::NVPTXSubtarget::hasTcgen05InstSupport () const inline
Definition at line 132 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasTcgen05MMAI8Kind()
bool llvm::NVPTXSubtarget::hasTcgen05MMAI8Kind () const inline
Definition at line 151 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs().
hasTcgen05MMAScaleInputDImm()
bool llvm::NVPTXSubtarget::hasTcgen05MMAScaleInputDImm () const inline
Definition at line 147 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasTcgen05MMASparseMxf4()
bool llvm::NVPTXSubtarget::hasTcgen05MMASparseMxf4 () const inline
Definition at line 161 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs().
hasTcgen05MMASparseMxf4nvf4()
bool llvm::NVPTXSubtarget::hasTcgen05MMASparseMxf4nvf4 () const inline
Definition at line 156 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs().
hasTcgen05ShiftSupport()
bool llvm::NVPTXSubtarget::hasTcgen05ShiftSupport () const inline
Definition at line 140 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs().
hasTensormapReplaceElemtypeSupport()
bool llvm::NVPTXSubtarget::hasTensormapReplaceElemtypeSupport (unsigned value) const inline
Definition at line 219 of file NVPTXSubtarget.h.
References llvm::nvvm::B4x16, hasPTXWithAccelSMs(), hasPTXWithFamilySMs(), and hasTensormapReplaceSupport().
Referenced by lowerTensormapReplaceElemtype().
hasTensormapReplaceSupport()
bool llvm::NVPTXSubtarget::hasTensormapReplaceSupport () const inline
Definition at line 213 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
Referenced by hasTensormapReplaceElemtypeSupport(), and hasTensormapReplaceSwizzleModeSupport().
hasTensormapReplaceSwizzleAtomicitySupport()
bool llvm::NVPTXSubtarget::hasTensormapReplaceSwizzleAtomicitySupport () const inline
Definition at line 228 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasTensormapReplaceSwizzleModeSupport()
bool llvm::NVPTXSubtarget::hasTensormapReplaceSwizzleModeSupport (unsigned value) const inline
Definition at line 234 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), hasTensormapReplaceSupport(), and llvm::nvvm::SWIZZLE_96B.
Referenced by lowerTensormapReplaceSwizzleMode().
hasTMABlackwellSupport()
bool llvm::NVPTXSubtarget::hasTMABlackwellSupport () const inline
Definition at line 186 of file NVPTXSubtarget.h.
References hasPTXWithAccelSMs(), and hasPTXWithFamilySMs().
hasUsedBytesMaskPragma()
bool llvm::NVPTXSubtarget::hasUsedBytesMaskPragma () const inline
Definition at line 94 of file NVPTXSubtarget.h.
Referenced by convertMLOADToLoadWithUsedBytesMask().
initializeSubtargetDependencies()
NVPTXSubtarget & NVPTXSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 119 of file NVPTXSubtarget.cpp.
References llvm::formatv(), getMinPTXVersionForSM(), getSmVersion(), getTargetName(), NVPTXSubtarget(), ParseSubtargetFeatures(), and llvm::reportFatalUsageError().
Referenced by NVPTXSubtarget().
ParseSubtargetFeatures()
void llvm::NVPTXSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Referenced by initializeSubtargetDependencies().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXSubtarget.h
lib/Target/NVPTX/NVPTXSubtarget.cpp