LLVM: llvm::memtag::StackInfoBuilder Class Reference
llvm::memtag::StackInfoBuilder Class Reference
#include "llvm/Transforms/Utils/MemoryTaggingSupport.h"
Public Member Functions
StackInfoBuilder (const StackSafetyGlobalInfo *SSI, const char *DebugType)
void visit (OptimizationRemarkEmitter &ORE, Instruction &Inst)
AllocaInterestingness getAllocaInterestingness (const AllocaInst &AI)
StackInfo & get ()
Detailed Description
Definition at line 73 of file MemoryTaggingSupport.h.
Constructor & Destructor Documentation
StackInfoBuilder()
llvm::memtag::StackInfoBuilder::StackInfoBuilder (const StackSafetyGlobalInfo * SSI, const char * DebugType) inline
Definition at line 75 of file MemoryTaggingSupport.h.
Member Function Documentation
get()
StackInfo & llvm::memtag::StackInfoBuilder::get () inline
Definition at line 80 of file MemoryTaggingSupport.h.
getAllocaInterestingness()
AllocaInterestingness llvm::memtag::StackInfoBuilder::getAllocaInterestingness (const AllocaInst & AI)
Definition at line 175 of file MemoryTaggingSupport.cpp.
References llvm::memtag::getAllocaSizeInBytes(), llvm::AllocaInst::getAllocatedType(), llvm::isAllocaPromotable(), llvm::Type::isScalableTy(), llvm::Type::isSized(), llvm::AllocaInst::isStaticAlloca(), llvm::AllocaInst::isSwiftError(), llvm::AllocaInst::isUsedWithInAlloca(), llvm::memtag::kInteresting, llvm::memtag::kSafe, and llvm::memtag::kUninteresting.
Referenced by visit().
visit()
void llvm::memtag::StackInfoBuilder::visit (OptimizationRemarkEmitter & ORE, Instruction & Inst)
Definition at line 114 of file MemoryTaggingSupport.cpp.
References llvm::memtag::AllocaInfo::DbgVariableRecords, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::OptimizationRemarkEmitter::emit(), llvm::filterDbgVars(), llvm::for_each(), getAllocaInterestingness(), llvm::Instruction::getDbgRecordRange(), llvm::memtag::getUntagLocationIfFunctionExit(), II, llvm::memtag::kInteresting, llvm::memtag::kSafe, and llvm::memtag::kUninteresting.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/MemoryTaggingSupport.h
lib/Transforms/Utils/MemoryTaggingSupport.cpp