LLVM: AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList Class Reference
AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList Class Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
ScopedTemplateParamList (AbstractManglingParser *TheParser)
~ScopedTemplateParamList ()
TemplateParamList * params ()
Detailed Description
template<typename Derived, typename Alloc>
class AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList
Definition at line 2764 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
ScopedTemplateParamList()
template<typename Derived, typename Alloc> AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::ScopedTemplateParamList (AbstractManglingParser * TheParser) inline
Definition at line 2770 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::AbstractManglingParser(), and AbstractManglingParser< Derived, Alloc >::TemplateParams.
~ScopedTemplateParamList()
template<typename Derived, typename Alloc> AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::~ScopedTemplateParamList () inline
Definition at line 2775 of file ItaniumDemangle.h.
References DEMANGLE_ASSERT.
Member Function Documentation
params()
template<typename Derived, typename Alloc> TemplateParamList * AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::params () inline
Definition at line 2780 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::parseTemplateParamDecl(), and AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h