LLVM: llvm::AppleAcceleratorTable Class Reference
llvm::AppleAcceleratorTable Class Reference
This implements the Apple accelerator table format, a precursor of the DWARF 5 accelerator table format.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Classes
class Entry
Apple-specific implementation of an Accelerator Entry.
class SameNameIterator
An iterator for Entries all having the same string as key.
struct EntryWithName
class Iterator
An iterator for all entries in the table.
Public Member Functions
AppleAcceleratorTable (const DWARFDataExtractor &AccelSection, DataExtractor StringSection)
Error extract () override
uint32_t getNumBuckets () const
uint32_t getNumHashes () const
uint32_t getSizeHdr () const
uint32_t getHeaderDataLength () const
uint32_t getHashDataEntryLength () const
Returns the size of one HashData entry.
ArrayRef< std::pair< HeaderData::AtomType, HeaderData::Form > > getAtomsDesc ()
Return the Atom description, which can be used to interpret the raw values of the Accelerator Entries in this table.
bool containsAtomType (HeaderData::AtomType AtomTy) const
Returns true iff AtomTy is one of the atoms available in Entries of this table.
bool validateForms ()
std::pair< uint64_t, dwarf::Tag > readAtoms (uint64_t *HashDataOffset)
Return information related to the DWARF DIE we're looking for when performing a lookup by name.
void dump (raw_ostream &OS) const override
iterator_range< SameNameIterator > equal_range (StringRef Key) const
Look up all entries in the accelerator table matching Key.
auto entries () const
Lookup all entries in the accelerator table.
Public Member Functions inherited from llvm::DWARFAcceleratorTable
DWARFAcceleratorTable (const DWARFDataExtractor &AccelSection, DataExtractor StringSection)
virtual ~DWARFAcceleratorTable ()
DWARFAcceleratorTable (const DWARFAcceleratorTable &)=delete
void operator= (const DWARFAcceleratorTable &)=delete
Additional Inherited Members
Protected Attributes inherited from llvm::DWARFAcceleratorTable
DWARFDataExtractor AccelSection
DataExtractor StringSection
Detailed Description
This implements the Apple accelerator table format, a precursor of the DWARF 5 accelerator table format.
Definition at line 101 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
AppleAcceleratorTable()
llvm::AppleAcceleratorTable::AppleAcceleratorTable (const DWARFDataExtractor & AccelSection, DataExtractor StringSection) inline
Definition at line 331 of file DWARFAcceleratorTable.h.
References llvm::DWARFAcceleratorTable::AccelSection, llvm::DWARFAcceleratorTable::DWARFAcceleratorTable(), and llvm::DWARFAcceleratorTable::StringSection.
Referenced by llvm::AppleAcceleratorTable::EntryWithName::EntryWithName(), llvm::AppleAcceleratorTable::Iterator::Iterator(), and llvm::AppleAcceleratorTable::SameNameIterator::SameNameIterator().
Member Function Documentation
containsAtomType()
bool llvm::AppleAcceleratorTable::containsAtomType (HeaderData::AtomType AtomTy) const inline
Returns true iff AtomTy is one of the atoms available in Entries of this table.
Definition at line 350 of file DWARFAcceleratorTable.h.
References llvm::is_contained(), and llvm::make_first_range().
dump()
LLVM_DUMP_METHOD void AppleAcceleratorTable::dump (raw_ostream & OS) const override virtual
Implements llvm::DWARFAcceleratorTable.
Definition at line 213 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFAcceleratorTable::AccelSection, formatAtom(), llvm::formatv(), getHashDataEntryLength(), LLVM_DUMP_METHOD, llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Twine::utohexstr().
Referenced by llvm::DWARFContext::dump().
entries()
auto llvm::AppleAcceleratorTable::entries () const inline
Lookup all entries in the accelerator table.
Definition at line 371 of file DWARFAcceleratorTable.h.
References llvm::make_range().
equal_range()
iterator_range< AppleAcceleratorTable::SameNameIterator > AppleAcceleratorTable::equal_range (StringRef Key) const
Look up all entries in the accelerator table matching Key.
Definition at line 362 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFAcceleratorTable::AccelSection, llvm::djbHash(), getHashDataEntryLength(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::make_range().
extract()
Error AppleAcceleratorTable::extract () override virtual
Implements llvm::DWARFAcceleratorTable.
Definition at line 43 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFAcceleratorTable::AccelSection, llvm::createStringError(), llvm::dwarf::DWARF32, llvm::dwarf::FormEncodingString(), llvm::dwarf::getFixedFormByteSize(), llvm::illegal_byte_sequence, llvm::not_supported, llvm::Offset, offsetof, and llvm::Error::success().
getAtomsDesc()
ArrayRef< std::pair< AppleAcceleratorTable::HeaderData::AtomType, AppleAcceleratorTable::HeaderData::Form > > AppleAcceleratorTable::getAtomsDesc ()
Return the Atom description, which can be used to interpret the raw values of the Accelerator Entries in this table.
Definition at line 103 of file DWARFAcceleratorTable.cpp.
Referenced by readAtoms(), and validateForms().
getHashDataEntryLength()
uint32_t llvm::AppleAcceleratorTable::getHashDataEntryLength () const inline
Returns the size of one HashData entry.
Definition at line 342 of file DWARFAcceleratorTable.h.
Referenced by dump(), and equal_range().
getHeaderDataLength()
uint32_t AppleAcceleratorTable::getHeaderDataLength () const
Definition at line 97 of file DWARFAcceleratorTable.cpp.
getNumBuckets()
uint32_t AppleAcceleratorTable::getNumBuckets () const
Definition at line 92 of file DWARFAcceleratorTable.cpp.
getNumHashes()
uint32_t AppleAcceleratorTable::getNumHashes () const
Definition at line 95 of file DWARFAcceleratorTable.cpp.
getSizeHdr()
uint32_t AppleAcceleratorTable::getSizeHdr () const
Definition at line 96 of file DWARFAcceleratorTable.cpp.
readAtoms()
std::pair< uint64_t, dwarf::Tag > AppleAcceleratorTable::readAtoms (uint64_t * HashDataOffset)
Return information related to the DWARF DIE we're looking for when performing a lookup by name.
Parameters
HashDataOffset an offset into the hash data table
Returns
<DieOffset, DieTag> DieOffset is the offset into the .debug_info section for the DIE related to the input hash data offset. DieTag is the tag of the DIE
Definition at line 127 of file DWARFAcceleratorTable.cpp.
References llvm::DWARFAcceleratorTable::AccelSection, llvm::dwarf::DW_ATOM_die_offset, llvm::dwarf::DW_ATOM_die_tag, llvm::dwarf::DW_INVALID_OFFSET, llvm::DWARFFormValue::extractValue(), llvm::DWARFFormValue::getAsUnsignedConstant(), and getAtomsDesc().
validateForms()
bool AppleAcceleratorTable::validateForms ()
Definition at line 107 of file DWARFAcceleratorTable.cpp.
References llvm::dwarf::DW_ATOM_die_offset, llvm::dwarf::DW_ATOM_die_tag, llvm::dwarf::DW_ATOM_type_flags, llvm::DWARFFormValue::FC_Constant, llvm::DWARFFormValue::FC_Flag, getAtomsDesc(), llvm::DWARFFormValue::getForm(), and llvm::DWARFFormValue::isFormClass().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp