LLVM: llvm::orc::LibraryResolver Class Reference
llvm::orc::LibraryResolver Class Reference
Scans libraries and resolves Symbols across user and system paths.
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h"
Classes
class SymbolEnumerator
class SymbolQuery
Tracks a set of symbols and the libraries where they are resolved.
struct Setup
Public Types
using OnSearchComplete = unique_function<void(SymbolQuery &)>
Public Member Functions
LibraryResolver ()=delete
LibraryResolver (const Setup &S)
~LibraryResolver ()=default
void dump ()
void searchSymbolsInLibraries (ArrayRef< StringRef > SymList, OnSearchComplete OnComplete, const SearchConfig &Config=SearchConfig())
Friends
class LibraryResolutionDriver
Detailed Description
Scans libraries and resolves Symbols across user and system paths.
Supports symbol enumeration and filtering via SymbolEnumerator, and tracks symbol resolution results through SymbolQuery. Thread-safe and uses LibraryScanHelper for efficient path resolution and caching.
Definition at line 379 of file LibraryResolver.h.
Member Typedef Documentation
OnSearchComplete
using llvm::orc::LibraryResolver::OnSearchComplete = unique_function<void(SymbolQuery &)>
Definition at line 521 of file LibraryResolver.h.
Constructor & Destructor Documentation
LibraryResolver() [1/2]
llvm::orc::LibraryResolver::LibraryResolver () delete
LibraryResolver() [2/2]
llvm::orc::LibraryResolver::LibraryResolver (const Setup & S) explicit
Definition at line 33 of file LibraryResolver.cpp.
~LibraryResolver()
llvm::orc::LibraryResolver::~LibraryResolver () default
Member Function Documentation
dump()
void llvm::orc::LibraryResolver::dump () inline
Definition at line 523 of file LibraryResolver.h.
References llvm::dbgs(), llvm::Lib, and llvm::orc::Loaded.
searchSymbolsInLibraries()
void llvm::orc::LibraryResolver::searchSymbolsInLibraries (ArrayRef< StringRef > SymList, OnSearchComplete OnComplete, const SearchConfig & Config = SearchConfig())
Definition at line 338 of file LibraryResolver.cpp.
References llvm::orc::LibraryResolver::SymbolQuery::allResolved(), llvm::dbgs(), llvm::orc::LibraryResolver::SymbolQuery::getAllResults(), llvm::Lib, LLVM_DEBUG, llvm::orc::SearchConfig::Options, llvm::orc::SearchPolicy::Plan, llvm::orc::SearchConfig::Policy, and searchSymbolsInLibraries().
Referenced by searchSymbolsInLibraries().
Friends And Related Symbol Documentation
LibraryResolutionDriver
friend class LibraryResolutionDriver friend
Definition at line 380 of file LibraryResolver.h.
References LibraryResolutionDriver.
Referenced by LibraryResolutionDriver.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryResolver.cpp