LLVM: llvm::SpecialCaseList::Section Class Reference
llvm::SpecialCaseList::Section Class Reference
#include "llvm/Support/SpecialCaseList.h"
Classes
class SectionImpl
Public Member Functions
LLVM_ABI Section (StringRef Name, unsigned FileIdx, bool UseGlobs)
LLVM_ABI Section (Section &&)
LLVM_ABI ~Section ()
StringRef name () const
LLVM_ABI bool matchName (StringRef Name) const
unsigned fileIndex () const
LLVM_ABI unsigned getLastMatch (StringRef Prefix, StringRef Query, StringRef Category) const
LLVM_ABI bool hasPrefix (StringRef Prefix) const
Returns true if the section has any entries for the given prefix.
Friends
class SpecialCaseList
Detailed Description
Definition at line 119 of file SpecialCaseList.h.
Constructor & Destructor Documentation
Section() [1/2]
llvm::SpecialCaseList::Section::Section (StringRef Name, unsigned FileIdx, bool UseGlobs)
Definition at line 423 of file SpecialCaseList.cpp.
References Section().
Referenced by Section(), and Section().
Section() [2/2]
llvm::SpecialCaseList::Section::Section (Section &&) default
References LLVM_ABI, and Section().
~Section()
llvm::SpecialCaseList::Section::~Section () default
References LLVM_ABI.
Member Function Documentation
fileIndex()
unsigned llvm::SpecialCaseList::Section::fileIndex () const inline
Definition at line 132 of file SpecialCaseList.h.
getLastMatch()
unsigned llvm::SpecialCaseList::Section::getLastMatch (StringRef Prefix, StringRef Query, StringRef Category) const
Definition at line 449 of file SpecialCaseList.cpp.
hasPrefix()
bool llvm::SpecialCaseList::Section::hasPrefix (StringRef Prefix) const
Returns true if the section has any entries for the given prefix.
Definition at line 457 of file SpecialCaseList.cpp.
matchName()
bool llvm::SpecialCaseList::Section::matchName (StringRef Name) const
Definition at line 432 of file SpecialCaseList.cpp.
name()
StringRef llvm::SpecialCaseList::Section::name () const inline
Definition at line 126 of file SpecialCaseList.h.
Friends And Related Symbol Documentation
SpecialCaseList
friend class SpecialCaseList friend
Definition at line 143 of file SpecialCaseList.h.
References SpecialCaseList.
Referenced by SpecialCaseList.
The documentation for this class was generated from the following files:
include/llvm/Support/SpecialCaseList.h
lib/Support/SpecialCaseList.cpp