LLVM: llvm::IRBuilderBase::OperandBundlesGuard Class Reference
llvm::IRBuilderBase::OperandBundlesGuard Class Reference
#include "llvm/IR/IRBuilder.h"
Public Member Functions
OperandBundlesGuard (IRBuilderBase &B)
OperandBundlesGuard (const OperandBundlesGuard &)=delete
OperandBundlesGuard & operator= (const OperandBundlesGuard &)=delete
~OperandBundlesGuard ()
Detailed Description
Definition at line 460 of file IRBuilder.h.
Constructor & Destructor Documentation
OperandBundlesGuard() [1/2]
llvm::IRBuilderBase::OperandBundlesGuard::OperandBundlesGuard (IRBuilderBase & B) inline
Definition at line 465 of file IRBuilder.h.
References B(), and llvm::IRBuilderBase::IRBuilderBase().
Referenced by OperandBundlesGuard(), and operator=().
OperandBundlesGuard() [2/2]
llvm::IRBuilderBase::OperandBundlesGuard::OperandBundlesGuard (const OperandBundlesGuard &) delete
References OperandBundlesGuard().
~OperandBundlesGuard()
llvm::IRBuilderBase::OperandBundlesGuard::~OperandBundlesGuard () inline
Definition at line 471 of file IRBuilder.h.
Member Function Documentation
operator=()
OperandBundlesGuard & llvm::IRBuilderBase::OperandBundlesGuard::operator= (const OperandBundlesGuard &) delete
References OperandBundlesGuard().
The documentation for this class was generated from the following file:
include/llvm/IR/IRBuilder.h