LLVM: llvm::XCoreSelectionDAGInfo Class Reference
llvm::XCoreSelectionDAGInfo Class Reference
#include "Target/XCore/XCoreSelectionDAGInfo.h"
Public Member Functions
XCoreSelectionDAGInfo ()
SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override
Emit target-specific code that performs a memcpy.
Public Member Functions inherited from llvm::SelectionDAGGenTargetInfo
~SelectionDAGGenTargetInfo () override
const char * getTargetNodeName (unsigned Opcode) const override
Returns the name of the given target-specific opcode, suitable for debug printing.
bool isTargetMemoryOpcode (unsigned Opcode) const override
Returns true if a node with the given target-specific opcode has a memory operand.
bool isTargetStrictFPOpcode (unsigned Opcode) const override
Returns true if a node with the given target-specific opcode has strict floating-point semantics.
void verifyTargetNode (const SelectionDAG &DAG, const SDNode *N) const override
Checks that the given target-specific node is valid. Aborts if it is not.
Public Member Functions inherited from llvm::SelectionDAGTargetInfo
SelectionDAGTargetInfo ()=default
SelectionDAGTargetInfo (const SelectionDAGTargetInfo &)=delete
SelectionDAGTargetInfo & operator= (const SelectionDAGTargetInfo &)=delete
virtual ~SelectionDAGTargetInfo ()
virtual bool mayRaiseFPException (unsigned Opcode) const
Returns true if a node with the given target-specific opcode may raise a floating-point exception.
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memmove.
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const
Emit target-specific code that performs a memset.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, const CallInst *CI) const
Emit target-specific code that performs a memcmp/bcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy, const CallInst *CI) const
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, const CallInst *CI) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
virtual SDValue EmitTargetCodeForSetTag (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Addr, SDValue Size, MachinePointerInfo DstPtrInfo, bool ZeroData) const
virtual bool disableGenericCombines (CodeGenOptLevel OptLevel) const
Additional Inherited Members
Protected Member Functions inherited from llvm::SelectionDAGGenTargetInfo
SelectionDAGGenTargetInfo (const SDNodeInfo &GenNodeInfo)
Protected Attributes inherited from llvm::SelectionDAGGenTargetInfo
const SDNodeInfo & GenNodeInfo
Detailed Description
Definition at line 23 of file XCoreSelectionDAGInfo.h.
Constructor & Destructor Documentation
XCoreSelectionDAGInfo()
XCoreSelectionDAGInfo::XCoreSelectionDAGInfo ()
Definition at line 23 of file XCoreSelectionDAGInfo.cpp.
References llvm::SelectionDAGGenTargetInfo::SelectionDAGGenTargetInfo().
Member Function Documentation
EmitTargetCodeForMemcpy()
SDValue XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override virtual
Emit target-specific code that performs a memcpy.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 26 of file XCoreSelectionDAGInfo.cpp.
References llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getExternalSymbol(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::SDValue::getValueSizeInBits(), llvm::Type::getVoidTy(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), and Size.
The documentation for this class was generated from the following files:
lib/Target/XCore/XCoreSelectionDAGInfo.h
lib/Target/XCore/XCoreSelectionDAGInfo.cpp