LLVM: llvm::orc::TrampolinePool Class Reference
llvm::orc::TrampolinePool Class Reference abstract
Base class for pools of compiler re-entry trampolines.
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Public Types
using NotifyLandingResolvedFunction
using ResolveLandingFunction
Public Member Functions
virtual ~TrampolinePool ()
Expected< ExecutorAddr > getTrampoline ()
Get an available trampoline address.
void releaseTrampoline (ExecutorAddr TrampolineAddr)
Returns the given trampoline to the pool for re-use.
Protected Member Functions
virtual Error grow ()=0
Protected Attributes
std::mutex TPMutex
std::vector< ExecutorAddr > AvailableTrampolines
Detailed Description
Base class for pools of compiler re-entry trampolines.
These trampolines are callable addresses that save all register state before calling a supplied function to return the trampoline landing address, then restore all state before jumping to that address. They are used by various ORC APIs to support lazy compilation
Definition at line 65 of file IndirectionUtils.h.
Member Typedef Documentation
NotifyLandingResolvedFunction
using llvm::orc::TrampolinePool::NotifyLandingResolvedFunction
Initial value:
unique_function<void(ExecutorAddr) const>
Definition at line 67 of file IndirectionUtils.h.
ResolveLandingFunction
using llvm::orc::TrampolinePool::ResolveLandingFunction
Initial value:
unique_function<void(
     ExecutorAddr TrampolineAddr,
     NotifyLandingResolvedFunction OnLandingResolved) const>
Definition at line 70 of file IndirectionUtils.h.
Constructor & Destructor Documentation
~TrampolinePool()
llvm::orc::TrampolinePool::~TrampolinePool () virtual default
Member Function Documentation
getTrampoline()
Expected< ExecutorAddr > llvm::orc::TrampolinePool::getTrampoline () inline
Get an available trampoline address.
Returns an error if no trampoline can be created.
Definition at line 78 of file IndirectionUtils.h.
References assert(), AvailableTrampolines, grow(), and TPMutex.
grow()
virtual Error llvm::orc::TrampolinePool::grow () protected pure virtual
Referenced by getTrampoline().
releaseTrampoline()
void llvm::orc::TrampolinePool::releaseTrampoline (ExecutorAddr TrampolineAddr) inline
Returns the given trampoline to the pool for re-use.
Definition at line 91 of file IndirectionUtils.h.
References AvailableTrampolines, and TPMutex.
Member Data Documentation
AvailableTrampolines
std::vector<ExecutorAddr> llvm::orc::TrampolinePool::AvailableTrampolines protected
Definition at line 100 of file IndirectionUtils.h.
Referenced by getTrampoline(), and releaseTrampoline().
TPMutex
std::mutex llvm::orc::TrampolinePool::TPMutex protected
Definition at line 99 of file IndirectionUtils.h.
Referenced by getTrampoline(), and releaseTrampoline().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IndirectionUtils.h
lib/ExecutionEngine/Orc/IndirectionUtils.cpp