LLVM: llvm::ArgumentInit Class Reference
llvm::ArgumentInit Class Reference final
#include "llvm/TableGen/Record.h"
Public Types
enum Kind { Positional , Named }
Public Member Functions
ArgumentInit (const ArgumentInit &)=delete
ArgumentInit & operator= (const ArgumentInit &)=delete
RecordKeeper & getRecordKeeper () const
bool isPositional () const
bool isNamed () const
const Init * getValue () const
unsigned getIndex () const
const Init * getName () const
const ArgumentInit * cloneWithValue (const Init *Value) const
void Profile (FoldingSetNodeID &ID) const
const Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a literal form.
bool isComplete () const override
Is this a complete value with no unset (uninitialized) subvalues?
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations?
const Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
const Init * getCastTo (const RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
const Init * convertInitializerTo (const RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual const Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This function is used to implement the bit range selection operator.
virtual const RecTy * getFieldType (const StringInit *FieldName) const
This function is used to implement the FieldInit class.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static const ArgumentInit * get (const Init *Value, ArgAuxType Aux)
Protected Member Functions
ArgumentInit (const Init *Value, ArgAuxType Aux)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_InstancesOpInit , IK_AnonymousNameInit ,
IK_StringInit , IK_VarInit , IK_VarBitInit , IK_VarDefInit ,
IK_LastTypedInit , IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.).
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
Definition at line 491 of file Record.h.
Member Enumeration Documentation
Kind
enum llvm::ArgumentInit::Kind
Enumerator
Positional
Named
Definition at line 493 of file Record.h.
Constructor & Destructor Documentation
ArgumentInit() [1/2]
llvm::ArgumentInit::ArgumentInit (const Init * Value, ArgAuxType Aux) inline explicit protected
Definition at line 503 of file Record.h.
References llvm::Init::IK_ArgumentInit, and llvm::Init::Init().
Referenced by ArgumentInit(), cloneWithValue(), get(), and operator=().
ArgumentInit() [2/2]
llvm::ArgumentInit::ArgumentInit (const ArgumentInit &) delete
References ArgumentInit().
Member Function Documentation
classof()
bool llvm::ArgumentInit::classof (const Init * I) inline static
Definition at line 510 of file Record.h.
References I, llvm::Init::IK_ArgumentInit, and llvm::Init::Init().
cloneWithValue()
const ArgumentInit * llvm::ArgumentInit::cloneWithValue (const Init * Value) const inline
Definition at line 528 of file Record.h.
References ArgumentInit(), get(), and llvm::Init::Init().
Referenced by resolveReferences().
convertInitializerTo()
const Init * llvm::ArgumentInit::convertInitializerTo (const RecTy * Ty) const inline override virtual
Convert to a value whose type is Ty, or return null if this is not possible.
This can happen if the value's type is convertible to Ty, but there are unresolved references.
Implements llvm::Init.
Definition at line 550 of file Record.h.
References llvm::Init::convertInitializerTo(), and llvm::Init::Init().
get()
const ArgumentInit * ArgumentInit::get (const Init * Value, ArgAuxType Aux) static
Definition at line 414 of file Record.cpp.
References detail::RecordKeeperImpl::Allocator, ArgumentInit(), llvm::FoldingSetImpl< Derived, T >::FindNodeOrInsertPos(), llvm::RecordKeeper::getImpl(), I, llvm::Init::Init(), llvm::FoldingSetImpl< Derived, T >::InsertNode(), ProfileArgumentInit(), and detail::RecordKeeperImpl::TheArgumentInitPool.
Referenced by cloneWithValue().
getAsString()
std::string llvm::ArgumentInit::getAsString () const inline override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 535 of file Record.h.
References llvm::Init::getAsString(), getIndex(), getName(), isNamed(), isPositional(), and llvm_unreachable.
getBit()
const Init * llvm::ArgumentInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 546 of file Record.h.
References llvm::Init::getBit(), and llvm::Init::Init().
getCastTo()
const Init * llvm::ArgumentInit::getCastTo (const RecTy * Ty) const inline override virtual
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Otherwise, return null.
Implements llvm::Init.
Definition at line 547 of file Record.h.
References llvm::Init::getCastTo(), and llvm::Init::Init().
getIndex()
unsigned llvm::ArgumentInit::getIndex () const inline
Definition at line 520 of file Record.h.
References assert(), and isPositional().
Referenced by getAsString().
getName()
const Init * llvm::ArgumentInit::getName () const inline
Definition at line 524 of file Record.h.
References assert(), llvm::Init::Init(), and isNamed().
Referenced by getAsString().
getRecordKeeper()
RecordKeeper & llvm::ArgumentInit::getRecordKeeper () const inline
Definition at line 512 of file Record.h.
getValue()
const Init * llvm::ArgumentInit::getValue () const inline
Definition at line 519 of file Record.h.
References llvm::Init::Init().
isComplete()
bool llvm::ArgumentInit::isComplete () const inline override virtual
Is this a complete value with no unset (uninitialized) subvalues?
Reimplemented from llvm::Init.
Definition at line 544 of file Record.h.
isConcrete()
bool llvm::ArgumentInit::isConcrete () const inline override virtual
Is this a concrete and fully resolved value without any references or stuck operations?
Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 545 of file Record.h.
isNamed()
bool llvm::ArgumentInit::isNamed () const inline
Definition at line 517 of file Record.h.
References Named.
Referenced by getAsString(), and getName().
isPositional()
bool llvm::ArgumentInit::isPositional () const inline
Definition at line 516 of file Record.h.
References Positional.
Referenced by getAsString(), and getIndex().
operator=()
ArgumentInit & llvm::ArgumentInit::operator= (const ArgumentInit &) delete
References ArgumentInit().
Profile()
void ArgumentInit::Profile (FoldingSetNodeID & ID) const
Definition at line 410 of file Record.cpp.
References ProfileArgumentInit().
resolveReferences()
const Init * ArgumentInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 430 of file Record.cpp.
References cloneWithValue(), and llvm::Init::Init().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp