LLVM: llvm::orc::SymbolStringPtrBase Class Reference
llvm::orc::SymbolStringPtrBase Class Reference
Base class for both owning and non-owning symbol-string ptrs.
#include "llvm/ExecutionEngine/Orc/SymbolStringPool.h"
Public Member Functions
SymbolStringPtrBase ()=default
SymbolStringPtrBase (std::nullptr_t)
operator bool () const
StringRef operator* () const
bool poolEntryIsAlive () const
Protected Types
using PoolEntry = SymbolStringPool::PoolMapEntry
using PoolEntryPtr = PoolEntry *
Protected Member Functions
SymbolStringPtrBase (PoolEntryPtr S)
size_t getRefCount () const
Static Protected Member Functions
static bool isRealPoolEntry (PoolEntryPtr P)
Protected Attributes
PoolEntryPtr S = nullptr
Static Protected Attributes
static constexpr uintptr_t EmptyBitPattern
static constexpr uintptr_t TombstoneBitPattern
static constexpr uintptr_t InvalidPtrMask
Friends
class SymbolStringPool
class SymbolStringPoolEntryUnsafe
struct DenseMapInfo< SymbolStringPtr >
struct DenseMapInfo< NonOwningSymbolStringPtr >
bool operator== (SymbolStringPtrBase LHS, SymbolStringPtrBase RHS)
bool operator!= (SymbolStringPtrBase LHS, SymbolStringPtrBase RHS)
bool operator< (SymbolStringPtrBase LHS, SymbolStringPtrBase RHS)
LLVM_ABI friend raw_ostream & operator<< (raw_ostream &OS, const SymbolStringPtrBase &Sym)
Detailed Description
Base class for both owning and non-owning symbol-string ptrs.
All symbol-string ptrs are convertible to bool, dereferenceable and comparable.
SymbolStringPtrBases are default-constructible and constructible from nullptr to enable comparison with these values.
Definition at line 73 of file SymbolStringPool.h.
Member Typedef Documentation
PoolEntry
using llvm::orc::SymbolStringPtrBase::PoolEntry = SymbolStringPool::PoolMapEntry protected
Definition at line 113 of file SymbolStringPool.h.
PoolEntryPtr
using llvm::orc::SymbolStringPtrBase::PoolEntryPtr = PoolEntry * protected
Definition at line 114 of file SymbolStringPool.h.
Constructor & Destructor Documentation
SymbolStringPtrBase() [1/3]
llvm::orc::SymbolStringPtrBase::SymbolStringPtrBase () default
Referenced by llvm::orc::NonOwningSymbolStringPtr::NonOwningSymbolStringPtr(), operator!=, operator<, operator<<, operator==, llvm::orc::SymbolStringPtr::SymbolStringPtr(), and llvm::orc::SymbolStringPtr::SymbolStringPtr().
SymbolStringPtrBase() [2/3]
llvm::orc::SymbolStringPtrBase::SymbolStringPtrBase (std::nullptr_t) inline
Definition at line 81 of file SymbolStringPool.h.
SymbolStringPtrBase() [3/3]
llvm::orc::SymbolStringPtrBase::SymbolStringPtrBase (PoolEntryPtr S) inline protected
Definition at line 116 of file SymbolStringPool.h.
References S.
Member Function Documentation
getRefCount()
size_t llvm::orc::SymbolStringPtrBase::getRefCount () const inline protected
Definition at line 136 of file SymbolStringPool.h.
References isRealPoolEntry(), and S.
isRealPoolEntry()
bool llvm::orc::SymbolStringPtrBase::isRealPoolEntry (PoolEntryPtr P) inline static protected
Definition at line 131 of file SymbolStringPool.h.
References InvalidPtrMask, and P.
Referenced by getRefCount(), poolEntryIsAlive(), and llvm::orc::SymbolStringPtr::SymbolStringPtr().
operator bool()
llvm::orc::SymbolStringPtrBase::operator bool () const inline explicit
Definition at line 83 of file SymbolStringPool.h.
References S.
operator*()
StringRef llvm::orc::SymbolStringPtrBase::operator* () const inline
Definition at line 85 of file SymbolStringPool.h.
References S.
poolEntryIsAlive()
bool llvm::orc::SymbolStringPtrBase::poolEntryIsAlive () const inline
Definition at line 107 of file SymbolStringPool.h.
References isRealPoolEntry(), and S.
Referenced by llvm::orc::SymbolStringPtr::SymbolStringPtr().
Friends And Related Symbol Documentation
DenseMapInfo< NonOwningSymbolStringPtr >
friend struct DenseMapInfo< NonOwningSymbolStringPtr > friend
Definition at line 75 of file SymbolStringPool.h.
References SymbolStringPoolEntryUnsafe.
DenseMapInfo< SymbolStringPtr >
friend struct DenseMapInfo< SymbolStringPtr > friend
Definition at line 75 of file SymbolStringPool.h.
operator!=
bool operator!= (SymbolStringPtrBase LHS, SymbolStringPtrBase RHS) friend
Definition at line 91 of file SymbolStringPool.h.
References LHS, RHS, and SymbolStringPtrBase().
operator<
bool operator< (SymbolStringPtrBase LHS, SymbolStringPtrBase RHS) friend
Definition at line 95 of file SymbolStringPool.h.
References LHS, RHS, and SymbolStringPtrBase().
operator<<
LLVM_ABI friend raw_ostream & operator<< (raw_ostream & OS, const SymbolStringPtrBase & Sym) friend
Definition at line 14 of file SymbolStringPool.cpp.
References llvm::StringMapEntry< ValueTy >::first(), S, and SymbolStringPtrBase().
operator==
bool operator== (SymbolStringPtrBase LHS, SymbolStringPtrBase RHS) friend
Definition at line 87 of file SymbolStringPool.h.
References LHS, RHS, and SymbolStringPtrBase().
SymbolStringPool
friend class SymbolStringPool friend
Definition at line 74 of file SymbolStringPool.h.
References SymbolStringPool.
Referenced by SymbolStringPool.
SymbolStringPoolEntryUnsafe
friend class SymbolStringPoolEntryUnsafe friend
Definition at line 75 of file SymbolStringPool.h.
Referenced by DenseMapInfo< NonOwningSymbolStringPtr >.
Member Data Documentation
EmptyBitPattern
uintptr_t llvm::orc::SymbolStringPtrBase::EmptyBitPattern static constexpr protected
Initial value:
                                       =
std::numeric_limits<uintptr_t>::max()
<< PointerLikeTypeTraits<PoolEntryPtr>::NumLowBitsAvailable
Definition at line 118 of file SymbolStringPool.h.
InvalidPtrMask
uintptr_t llvm::orc::SymbolStringPtrBase::InvalidPtrMask static constexpr protected
Initial value:
                                      =
(std::numeric_limits<uintptr_t>::max() - 3)
<< PointerLikeTypeTraits<PoolEntryPtr>::NumLowBitsAvailable
Definition at line 126 of file SymbolStringPool.h.
Referenced by isRealPoolEntry().
S
PoolEntryPtr llvm::orc::SymbolStringPtrBase::S = nullptr protected
Definition at line 140 of file SymbolStringPool.h.
Referenced by llvm::orc::SymbolStringPoolEntryUnsafe::from(), getRefCount(), llvm::orc::SymbolStringPoolEntryUnsafe::moveToSymbolStringPtr(), operator bool(), operator*(), operator<<, llvm::orc::SymbolStringPtr::operator=(), llvm::orc::SymbolStringPtr::operator=(), poolEntryIsAlive(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), and SymbolStringPtrBase().
TombstoneBitPattern
uintptr_t llvm::orc::SymbolStringPtrBase::TombstoneBitPattern static constexpr protected
Initial value:
                                           =
(std::numeric_limits<uintptr_t>::max() - 1)
<< PointerLikeTypeTraits<PoolEntryPtr>::NumLowBitsAvailable
Definition at line 122 of file SymbolStringPool.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/SymbolStringPool.h