LLVM: llvm::MCPseudoProbeDecoder Class Reference
llvm::MCPseudoProbeDecoder Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Types
using Uint64Set = DenseSet<uint64_t>
using Uint64Map = DenseMap<uint64_t, uint64_t>
Public Member Functions
LLVM_ABI bool buildGUID2FuncDescMap (const uint8_t *Start, std::size_t Size, bool IsMMapped=false)
template<bool IsTopLevelFunc>
bool countRecords (bool &Discard, uint32_t &ProbeCount, uint32_t &InlinedCount, const Uint64Set &GuidFilter)
LLVM_ABI bool buildAddress2ProbeMap (const uint8_t *Start, std::size_t Size, const Uint64Set &GuildFilter, const Uint64Map &FuncStartAddrs)
LLVM_ABI void printGUID2FuncDescMap (raw_ostream &OS)
LLVM_ABI void printProbeForAddress (raw_ostream &OS, uint64_t Address)
LLVM_ABI void printProbesForAllAddresses (raw_ostream &OS)
LLVM_ABI const MCDecodedPseudoProbe * getCallProbeForAddr (uint64_t Address) const
LLVM_ABI const MCPseudoProbeFuncDesc * getFuncDescForGUID (uint64_t GUID) const
LLVM_ABI void getInlineContextForProbe (const MCDecodedPseudoProbe *Probe, SmallVectorImpl< MCPseudoProbeFrameLocation > &InlineContextStack, bool IncludeLeaf) const
const AddressProbesMap & getAddress2ProbesMap () const
AddressProbesMap & getAddress2ProbesMap ()
const GUIDProbeFunctionMap & getGUID2FuncDescMap () const
LLVM_ABI const MCPseudoProbeFuncDesc * getInlinerDescForProbe (const MCDecodedPseudoProbe *Probe) const
const MCDecodedPseudoProbeInlineTree & getDummyInlineRoot () const
void addInjectedProbe (const MCDecodedPseudoProbe &Probe, uint64_t Address)
size_t getNumInjectedProbes (const MCDecodedPseudoProbeInlineTree *Parent) const
auto getInjectedProbes (MCDecodedPseudoProbeInlineTree *Parent)
ArrayRef< MCDecodedPseudoProbeInlineTree > getInlineTreeVec () const
Detailed Description
Definition at line 388 of file MCPseudoProbe.h.
Member Typedef Documentation
Uint64Map
using llvm::MCPseudoProbeDecoder::Uint64Map = DenseMap<uint64_t, uint64_t>
Definition at line 434 of file MCPseudoProbe.h.
Uint64Set
using llvm::MCPseudoProbeDecoder::Uint64Set = DenseSet<uint64_t>
Definition at line 433 of file MCPseudoProbe.h.
Member Function Documentation
addInjectedProbe()
void llvm::MCPseudoProbeDecoder::addInjectedProbe (const MCDecodedPseudoProbe & Probe, uint64_t Address) inline
Definition at line 498 of file MCPseudoProbe.h.
References llvm::MCDecodedPseudoProbe::getInlineTreeNode().
buildAddress2ProbeMap()
bool MCPseudoProbeDecoder::buildAddress2ProbeMap (const uint8_t * Start, std::size_t Size, const Uint64Set & GuildFilter, const Uint64Map & FuncStartAddrs)
Definition at line 615 of file MCPseudoProbe.cpp.
References assert(), buildAddress2ProbeMap(), countRecords(), llvm::enumerate(), I, llvm::make_second_range(), llvm::MutableArrayRef(), Size, and llvm::sort().
Referenced by buildAddress2ProbeMap().
buildGUID2FuncDescMap()
bool MCPseudoProbeDecoder::buildGUID2FuncDescMap (const uint8_t * Start, std::size_t Size, bool IsMMapped = false)
Definition at line 375 of file MCPseudoProbe.cpp.
References assert(), llvm::cantFail(), llvm::errorOrToExpected(), llvm::XCOFF::NameSize, Size, and llvm::sort().
countRecords()
template<bool IsTopLevelFunc> bool MCPseudoProbeDecoder::countRecords (bool & Discard, uint32_t & ProbeCount, uint32_t & InlinedCount, const Uint64Set & GuidFilter)
Definition at line 537 of file MCPseudoProbe.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), countRecords(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), llvm::Guid, llvm::hasDiscriminator(), I, and llvm::isSentinelProbe().
Referenced by buildAddress2ProbeMap(), and countRecords().
getAddress2ProbesMap() [1/2]
AddressProbesMap & llvm::MCPseudoProbeDecoder::getAddress2ProbesMap () inline
Definition at line 485 of file MCPseudoProbe.h.
getAddress2ProbesMap() [2/2]
const AddressProbesMap & llvm::MCPseudoProbeDecoder::getAddress2ProbesMap () const inline
Definition at line 481 of file MCPseudoProbe.h.
getCallProbeForAddr()
const MCDecodedPseudoProbe * MCPseudoProbeDecoder::getCallProbeForAddr (uint64_t Address) const
Definition at line 691 of file MCPseudoProbe.cpp.
getDummyInlineRoot()
const MCDecodedPseudoProbeInlineTree & llvm::MCPseudoProbeDecoder::getDummyInlineRoot () const inline
Definition at line 494 of file MCPseudoProbe.h.
getFuncDescForGUID()
const MCPseudoProbeFuncDesc * MCPseudoProbeDecoder::getFuncDescForGUID (uint64_t GUID) const
Definition at line 715 of file MCPseudoProbe.cpp.
References assert().
Referenced by getInlineContextForProbe(), and getInlinerDescForProbe().
getGUID2FuncDescMap()
const GUIDProbeFunctionMap & llvm::MCPseudoProbeDecoder::getGUID2FuncDescMap () const inline
Definition at line 487 of file MCPseudoProbe.h.
getInjectedProbes()
auto llvm::MCPseudoProbeDecoder::getInjectedProbes (MCDecodedPseudoProbeInlineTree * Parent) inline
Definition at line 511 of file MCPseudoProbe.h.
References assert(), and llvm::iterator_range().
getInlineContextForProbe()
void MCPseudoProbeDecoder::getInlineContextForProbe (const MCDecodedPseudoProbe * Probe, SmallVectorImpl< MCPseudoProbeFrameLocation > & InlineContextStack, bool IncludeLeaf) const
Definition at line 721 of file MCPseudoProbe.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), getFuncDescForGUID(), llvm::MCDecodedPseudoProbe::getGuid(), llvm::MCPseudoProbeBase::getIndex(), and llvm::MCDecodedPseudoProbe::getInlineContext().
getInlinerDescForProbe()
const MCPseudoProbeFuncDesc * MCPseudoProbeDecoder::getInlinerDescForProbe (const MCDecodedPseudoProbe * Probe) const
Definition at line 735 of file MCPseudoProbe.cpp.
References getFuncDescForGUID(), llvm::MCDecodedPseudoProbe::getInlineTreeNode(), llvm::MCPseudoProbeInlineTreeBase< ProbesType, DerivedProbeInlineTreeType, InlinedProbeTreeMap >::Guid, llvm::MCDecodedPseudoProbeInlineTree::hasInlineSite(), and llvm::MCPseudoProbeInlineTreeBase< ProbesType, DerivedProbeInlineTreeType, InlinedProbeTreeMap >::Parent.
getInlineTreeVec()
ArrayRef< MCDecodedPseudoProbeInlineTree > llvm::MCPseudoProbeDecoder::getInlineTreeVec () const inline
Definition at line 517 of file MCPseudoProbe.h.
getNumInjectedProbes()
size_t llvm::MCPseudoProbeDecoder::getNumInjectedProbes (const MCDecodedPseudoProbeInlineTree * Parent) const inline
Definition at line 504 of file MCPseudoProbe.h.
printGUID2FuncDescMap()
void MCPseudoProbeDecoder::printGUID2FuncDescMap (raw_ostream & OS)
Definition at line 663 of file MCPseudoProbe.cpp.
References I.
printProbeForAddress()
void MCPseudoProbeDecoder::printProbeForAddress (raw_ostream & OS, uint64_t Address)
Definition at line 669 of file MCPseudoProbe.cpp.
printProbesForAllAddresses()
void MCPseudoProbeDecoder::printProbesForAllAddresses (raw_ostream & OS)
Definition at line 677 of file MCPseudoProbe.cpp.
References INT64_MAX.
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp