LLVM: llvm::MachineModuleSlotTracker Class Reference
llvm::MachineModuleSlotTracker Class Reference
#include "llvm/CodeGen/MachineModuleSlotTracker.h"
Public Member Functions
MachineModuleSlotTracker (MFGetterFnT Fn, const MachineFunction *MF, bool ShouldInitializeAllMetadata=true)
~MachineModuleSlotTracker () override
void collectMachineMDNodes (MachineMDNodeListType &L) const
Public Member Functions inherited from llvm::ModuleSlotTracker
ModuleSlotTracker (SlotTracker &Machine, const Module *M, const Function *F=nullptr)
Wrap a preinitialized SlotTracker.
ModuleSlotTracker (const Module *M, bool ShouldInitializeAllMetadata=true)
Construct a slot tracker from a module.
virtual ~ModuleSlotTracker ()
Destructor to clean up storage.
SlotTracker * getMachine ()
Lazily creates a slot tracker.
const Module * getModule () const
const Function * getCurrentFunction () const
void incorporateFunction (const Function &F)
Incorporate the given function.
int getLocalSlot (const Value *V)
Return the slot number of the specified local value.
void setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Module *, bool)>)
void setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Function *, bool)>)
void collectMDNodes (MachineMDNodeListType &L, unsigned LB, unsigned UB) const
Additional Inherited Members
Public Types inherited from llvm::ModuleSlotTracker
using MachineMDNodeListType
Detailed Description
Definition at line 26 of file MachineModuleSlotTracker.h.
Constructor & Destructor Documentation
MachineModuleSlotTracker()
MachineModuleSlotTracker::MachineModuleSlotTracker (MFGetterFnT Fn, const MachineFunction * MF, bool ShouldInitializeAllMetadata = true)
Definition at line 66 of file MachineModuleSlotTracker.cpp.
References getFunction(), getParent(), llvm::ModuleSlotTracker::ModuleSlotTracker(), and llvm::ModuleSlotTracker::setProcessHook().
~MachineModuleSlotTracker()
MachineModuleSlotTracker::~MachineModuleSlotTracker () override default
References collectMachineMDNodes().
Member Function Documentation
collectMachineMDNodes()
void MachineModuleSlotTracker::collectMachineMDNodes (MachineMDNodeListType & L) const
Definition at line 61 of file MachineModuleSlotTracker.cpp.
References llvm::ModuleSlotTracker::collectMDNodes().
Referenced by convertMachineMetadataNodes(), and ~MachineModuleSlotTracker().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleSlotTracker.h
lib/CodeGen/MachineModuleSlotTracker.cpp