LLVM: llvm::AMDGPUArgumentUsageInfoWrapperLegacy Class Reference
llvm::AMDGPUArgumentUsageInfoWrapperLegacy Class Reference
#include "Target/AMDGPU/AMDGPUArgumentUsageInfo.h"
Public Member Functions
AMDGPUArgumentUsageInfoWrapperLegacy ()
AMDGPUArgumentUsageInfo & getArgUsageInfo ()
const AMDGPUArgumentUsageInfo & getArgUsageInfo () const
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool doInitialization (Module &M) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
bool doFinalization (Module &M) override
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void print (raw_ostream &OS, const Module *M=nullptr) const override
print - Print out the internal state of the pass.
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
StringRef getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (const Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 197 of file AMDGPUArgumentUsageInfo.h.
Constructor & Destructor Documentation
AMDGPUArgumentUsageInfoWrapperLegacy()
llvm::AMDGPUArgumentUsageInfoWrapperLegacy::AMDGPUArgumentUsageInfoWrapperLegacy () inline
Definition at line 203 of file AMDGPUArgumentUsageInfo.h.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::ImmutablePass::ImmutablePass(), and llvm::initializeAMDGPUArgumentUsageInfoWrapperLegacyPass().
Member Function Documentation
doFinalization()
bool llvm::AMDGPUArgumentUsageInfoWrapperLegacy::doFinalization (Module &) inline override virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 220 of file AMDGPUArgumentUsageInfo.h.
doInitialization()
bool llvm::AMDGPUArgumentUsageInfoWrapperLegacy::doInitialization (Module &) inline override virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 215 of file AMDGPUArgumentUsageInfo.h.
getAnalysisUsage()
void llvm::AMDGPUArgumentUsageInfoWrapperLegacy::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 211 of file AMDGPUArgumentUsageInfo.h.
References llvm::AnalysisUsage::setPreservesAll().
getArgUsageInfo() [1/2]
AMDGPUArgumentUsageInfo & llvm::AMDGPUArgumentUsageInfoWrapperLegacy::getArgUsageInfo () inline
Definition at line 208 of file AMDGPUArgumentUsageInfo.h.
Referenced by llvm::SITargetLowering::LowerFormalArguments().
getArgUsageInfo() [2/2]
const AMDGPUArgumentUsageInfo & llvm::AMDGPUArgumentUsageInfoWrapperLegacy::getArgUsageInfo () const inline
Definition at line 209 of file AMDGPUArgumentUsageInfo.h.
print()
void llvm::AMDGPUArgumentUsageInfoWrapperLegacy::print (raw_ostream & OS, const Module * M = nullptr) const inline override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 225 of file AMDGPUArgumentUsageInfo.h.
Member Data Documentation
ID
char llvm::AMDGPUArgumentUsageInfoWrapperLegacy::ID static
Definition at line 201 of file AMDGPUArgumentUsageInfo.h.
Referenced by AMDGPUArgumentUsageInfoWrapperLegacy().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.h