LLVM: llvm::AMDGPU::ClusterDimsAttr Class Reference
llvm::AMDGPU::ClusterDimsAttr Class Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Types
enum class Kind { Unknown , NoCluster , VariableDims , FixedDims }
Public Member Functions
ClusterDimsAttr ()=default
Kind getKind () const
bool isUnknown () const
bool isNoCluster () const
bool isFixedDims () const
bool isVariableDims () const
void setUnknown ()
void setNoCluster ()
void setVariableDims ()
const std::array< unsigned, 3 > & getDims () const
bool operator== (const ClusterDimsAttr &RHS) const
std::string to_string () const
Static Public Member Functions
static ClusterDimsAttr get (const Function &F)
Detailed Description
Definition at line 1873 of file AMDGPUBaseInfo.h.
Member Enumeration Documentation
Kind
enum class llvm::AMDGPU::ClusterDimsAttr::Kind strong
Enumerator
Unknown
NoCluster
VariableDims
FixedDims
Definition at line 1875 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
ClusterDimsAttr()
llvm::AMDGPU::ClusterDimsAttr::ClusterDimsAttr () default
Referenced by get(), operator==(), setNoCluster(), setUnknown(), and setVariableDims().
Member Function Documentation
get()
ClusterDimsAttr llvm::AMDGPU::ClusterDimsAttr::get (const Function & F) static
Definition at line 3731 of file AMDGPUBaseInfo.cpp.
References A(), llvm::all_of(), ClusterDimsAttr(), F, FixedDims, llvm::AMDGPU::getIntegerVecAttribute(), NoCluster, Unknown, and VariableDims.
Referenced by llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
getDims()
const std::array< unsigned, 3 > & llvm::AMDGPU::ClusterDimsAttr::getDims () const
Returns
the dims stored. Note that this function can only be called if the kind is Fixed.
Definition at line 3702 of file AMDGPUBaseInfo.cpp.
References assert(), and isFixedDims().
Referenced by llvm::AMDGPULegalizerInfo::loadInputValue().
getKind()
Kind llvm::AMDGPU::ClusterDimsAttr::getKind () const inline
Definition at line 1879 of file AMDGPUBaseInfo.h.
Referenced by isFixedDims(), isNoCluster(), isUnknown(), isVariableDims(), llvm::AMDGPULegalizerInfo::legalizeWorkGroupId(), and to_string().
isFixedDims()
bool llvm::AMDGPU::ClusterDimsAttr::isFixedDims () const inline
Definition at line 1885 of file AMDGPUBaseInfo.h.
References FixedDims, and getKind().
Referenced by getDims(), and llvm::AMDGPULegalizerInfo::loadInputValue().
isNoCluster()
bool llvm::AMDGPU::ClusterDimsAttr::isNoCluster () const inline
Definition at line 1883 of file AMDGPUBaseInfo.h.
References getKind(), and NoCluster.
isUnknown()
bool llvm::AMDGPU::ClusterDimsAttr::isUnknown () const inline
Definition at line 1881 of file AMDGPUBaseInfo.h.
References getKind(), and Unknown.
isVariableDims()
bool llvm::AMDGPU::ClusterDimsAttr::isVariableDims () const inline
Definition at line 1887 of file AMDGPUBaseInfo.h.
References getKind(), and VariableDims.
operator==()
bool llvm::AMDGPU::ClusterDimsAttr::operator== (const ClusterDimsAttr & RHS) const inline
Definition at line 1899 of file AMDGPUBaseInfo.h.
References ClusterDimsAttr(), and RHS.
setNoCluster()
void llvm::AMDGPU::ClusterDimsAttr::setNoCluster () inline
Definition at line 1891 of file AMDGPUBaseInfo.h.
References ClusterDimsAttr(), and NoCluster.
setUnknown()
void llvm::AMDGPU::ClusterDimsAttr::setUnknown () inline
Definition at line 1889 of file AMDGPUBaseInfo.h.
References ClusterDimsAttr(), and Unknown.
setVariableDims()
void llvm::AMDGPU::ClusterDimsAttr::setVariableDims () inline
Definition at line 1893 of file AMDGPUBaseInfo.h.
References ClusterDimsAttr(), and VariableDims.
to_string()
std::string llvm::AMDGPU::ClusterDimsAttr::to_string () const
Definition at line 3707 of file AMDGPUBaseInfo.cpp.
References llvm::SmallString< InternalLen >::c_str(), FixedDims, getKind(), llvm_unreachable, NoCluster, Unknown, and VariableDims.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp