LLVM: ObjCARCContract Class Reference
ObjCARCContract Class Reference
Public Member Functions
bool init (Module &M)
bool run (Function &F, AAResults *AA, DominatorTree *DT)
bool hasCFGChanged () const
Detailed Description
Definition at line 71 of file ObjCARCContract.cpp.
Member Function Documentation
hasCFGChanged()
bool ObjCARCContract::hasCFGChanged () const inline
Definition at line 113 of file ObjCARCContract.cpp.
Referenced by llvm::ObjCARCContractPass::run().
init()
bool ObjCARCContract::init (Module & M)
Definition at line 566 of file ObjCARCContract.cpp.
References llvm::objcarc::getRVInstMarker(), Module, llvm::objcarc::ModuleHasARC(), and useClaimRuntimeCall().
Referenced by llvm::ObjCARCContractPass::run(), and ObjCARCContractLegacyPass::runOnFunction().
run()
bool ObjCARCContract::run (Function & F, AAResults * AA, DominatorTree * DT)
Definition at line 581 of file ObjCARCContract.cpp.
References A(), assert(), llvm::BasicBlock::back(), llvm::cast(), llvm::classifyEHPersonality(), llvm::colorEHFunclets(), D(), llvm::dbgs(), llvm::dyn_cast(), E(), llvm::objcarc::EnableARCOpts, F, llvm::objcarc::getEquivalentPHIs(), llvm::BasicBlock::getFirstNonPHIIt(), llvm::PHINode::getIncomingValueNumForOperand(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Use::getOperandNo(), llvm::PHINode::getOperandNumForIncomingValue(), llvm::Value::getType(), llvm::objcarc::hasAttachedCallOpBundle(), I, llvm::inst_begin(), llvm::inst_end(), llvm::isa(), llvm::isScopedEHPersonality(), LLVM_DEBUG, PHI, and llvm::CallInst::setTailCall().
Referenced by llvm::ObjCARCContractPass::run(), and ObjCARCContractLegacyPass::runOnFunction().
The documentation for this class was generated from the following file:
lib/Transforms/ObjCARC/ObjCARCContract.cpp