LLVM: llvm::LanaiInstPrinter Class Reference
llvm::LanaiInstPrinter Class Reference
#include "Target/Lanai/MCTargetDesc/LanaiInstPrinter.h"
Public Member Functions
LanaiInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printPredicateOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMemRiOperand (const MCInst *MI, int OpNo, raw_ostream &O)
void printMemRrOperand (const MCInst *MI, int OpNo, raw_ostream &O)
void printMemSplsOperand (const MCInst *MI, int OpNo, raw_ostream &O)
void printCCOperand (const MCInst *MI, int OpNo, raw_ostream &O)
void printHi16ImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printHi16AndImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLo16AndImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
std::pair< const char *, uint64_t > getMnemonic (const MCInst &MI) const override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, uint64_t Address, raw_ostream &OS)
void printCustomAliasOperand (const MCInst *MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O)
void printRegName (raw_ostream &OS, MCRegister Reg) override
Print the assembler register name.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
bool getUseColor () const
void setUseColor (bool Value)
WithMarkup markup (raw_ostream &OS, Markup M)
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
Additional Inherited Members
Public Types inherited from llvm::MCInstPrinter
enum class Markup { Immediate , Register , Target , Memory }
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool UseColor = false
True if we are printing colored assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
SmallVector< raw_ostream::Colors, 4 > ColorStack {raw_ostream::Colors::RESET}
Detailed Description
Definition at line 21 of file LanaiInstPrinter.h.
Constructor & Destructor Documentation
LanaiInstPrinter()
llvm::LanaiInstPrinter::LanaiInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 23 of file LanaiInstPrinter.h.
References llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MCInstPrinter(), llvm::MCInstPrinter::MII, and llvm::MCInstPrinter::MRI.
Member Function Documentation
getMnemonic()
std::pair< const char *, uint64_t > llvm::LanaiInstPrinter::getMnemonic (const MCInst & MI) const override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
References MI.
getRegisterName()
const char * llvm::LanaiInstPrinter::getRegisterName (MCRegister Reg) static
References MI, and Reg.
Referenced by printMemoryBaseRegister(), printMemRrOperand(), printOperand(), and printRegName().
printAliasInstr()
bool llvm::LanaiInstPrinter::printAliasInstr (const MCInst * MI, uint64_t Address, raw_ostream & OS)
References MI.
Referenced by printInst().
printCCOperand()
void LanaiInstPrinter::printCCOperand (const MCInst * MI, int OpNo, raw_ostream & O)
Definition at line 281 of file LanaiInstPrinter.cpp.
References llvm::getImm(), MI, and llvm::LPCC::UNKNOWN.
printCustomAliasOperand()
void llvm::LanaiInstPrinter::printCustomAliasOperand (const MCInst * MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O)
References MI, and OpIdx.
printHi16AndImmOperand()
void LanaiInstPrinter::printHi16AndImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 185 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::MAI, and MI.
printHi16ImmOperand()
void LanaiInstPrinter::printHi16ImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 173 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::MAI, and MI.
printInst()
void LanaiInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 137 of file LanaiInstPrinter.cpp.
References MI, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::LanaiInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
References MI.
Referenced by printInst().
printLo16AndImmOperand()
void LanaiInstPrinter::printLo16AndImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 197 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::MAI, and MI.
printMemImmOperand()
void LanaiInstPrinter::printMemImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 159 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::MAI, and MI.
printMemRiOperand()
void LanaiInstPrinter::printMemRiOperand (const MCInst * MI, int OpNo, raw_ostream & O)
Definition at line 233 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInstPrinter::MAI, MI, printMemoryBaseRegister(), and printMemoryImmediateOffset().
printMemRrOperand()
void LanaiInstPrinter::printMemRrOperand (const MCInst * MI, int OpNo, raw_ostream & O)
Definition at line 247 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), getRegisterName(), llvm::LPAC::isPostOp(), llvm::LPAC::isPreOp(), llvm::MCOperand::isReg(), llvm::LPAC::lanaiAluCodeToString(), and MI.
printMemSplsOperand()
void LanaiInstPrinter::printMemSplsOperand (const MCInst * MI, int OpNo, raw_ostream & O)
Definition at line 267 of file LanaiInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInstPrinter::MAI, MI, printMemoryBaseRegister(), and printMemoryImmediateOffset().
printOperand()
void LanaiInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 146 of file LanaiInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), getRegisterName(), llvm::MCInstPrinter::MAI, and MI.
printPredicateOperand()
void LanaiInstPrinter::printPredicateOperand (const MCInst * MI, unsigned OpNum, raw_ostream & O)
Definition at line 292 of file LanaiInstPrinter.cpp.
References llvm::getImm(), llvm::LPCC::ICC_T, MI, and llvm::LPCC::UNKNOWN.
printRegName()
void LanaiInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 31 of file LanaiInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
The documentation for this class was generated from the following files:
lib/Target/Lanai/MCTargetDesc/LanaiInstPrinter.h
lib/Target/Lanai/MCTargetDesc/LanaiInstPrinter.cpp