LLVM: llvm::vfs::ProxyOutputBackend Class Reference
llvm::vfs::ProxyOutputBackend Class Reference
A helper class for proxying another backend, with the default implementation to forward to the underlying backend.
#include "llvm/Support/VirtualOutputBackends.h"
Public Member Functions
ProxyOutputBackend (IntrusiveRefCntPtr< OutputBackend > UnderlyingBackend)
Public Member Functions inherited from llvm::vfs::OutputBackend
IntrusiveRefCntPtr< OutputBackend > clone () const
Get a backend that points to the same destination as this one but that has independent settings.
LLVM_ABI Expected< OutputFile > createFile (const Twine &Path, std::optional< OutputConfig > Config=std::nullopt)
Create a file.
virtual ~OutputBackend ()=default
Public Member Functions inherited from llvm::RefCountedBase< OutputBackend >
unsigned UseCount () const
void Retain () const
void Release () const
Protected Member Functions
Expected< std::unique_ptr< OutputFileImpl > > createFileImpl (StringRef Path, std::optional< OutputConfig > Config) override
Create a file for Path.
OutputBackend & getUnderlyingBackend () const
Protected Member Functions inherited from llvm::vfs::OutputBackend
virtual IntrusiveRefCntPtr< OutputBackend > cloneImpl () const =0
Must be thread-safe.
OutputBackend ()=default
Protected Member Functions inherited from llvm::RefCountedBase< OutputBackend >
RefCountedBase ()=default
RefCountedBase & operator= (const RefCountedBase &)=delete
~RefCountedBase ()
Detailed Description
A helper class for proxying another backend, with the default implementation to forward to the underlying backend.
Definition at line 50 of file VirtualOutputBackends.h.
Constructor & Destructor Documentation
ProxyOutputBackend()
llvm::vfs::ProxyOutputBackend::ProxyOutputBackend (IntrusiveRefCntPtr< OutputBackend > UnderlyingBackend) inline
Definition at line 69 of file VirtualOutputBackends.h.
References assert(), and llvm::move().
Referenced by llvm::vfs::makeMirroringOutputBackend().
Member Function Documentation
createFileImpl()
Expected< std::unique_ptr< OutputFileImpl > > llvm::vfs::ProxyOutputBackend::createFileImpl (StringRef Path, std::optional< OutputConfig > Config) inline override protected virtual
Create a file for Path.
Must be thread-safe.
Precondition
Config is valid or std::nullopt.
Implements llvm::vfs::OutputBackend.
Definition at line 59 of file VirtualOutputBackends.h.
References E().
Referenced by llvm::vfs::makeFilteringOutputBackend().
getUnderlyingBackend()
OutputBackend & llvm::vfs::ProxyOutputBackend::getUnderlyingBackend () const inline protected
Definition at line 66 of file VirtualOutputBackends.h.
References llvm::vfs::OutputBackend::OutputBackend().
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualOutputBackends.h
lib/Support/VirtualOutputBackends.cpp