LLVM: llvm::VPRecipeBase Class Reference
llvm::VPRecipeBase Class Reference abstract
VPRecipeBase is a base class modeling a sequence of one or more output IR instructions.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL=DebugLoc::getUnknown())
~VPRecipeBase () override=default
virtual VPRecipeBase * clone ()=0
Clone the current recipe.
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
VPRegionBlock * getRegion ()
const VPRegionBlock * getRegion () const
virtual void execute (VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
bool isScalarCast () const
Return true if the recipe is a scalar cast.
void setDebugLoc (DebugLoc NewDL)
Set the recipe's debug location to NewDL.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override final
Print the recipe, delegating to printRecipe().
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPRecipeValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPRecipeValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
LLVM_ABI_FOR_TEST void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool usesFirstLaneOnly (const VPValue *Op) const
Returns true if the VPUser only uses the first lane of operand Op.
virtual bool usesFirstPartOnly (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Static Public Member Functions
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Member Functions
virtual InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const
Compute the cost of this recipe either using a recipe's specialized implementation or using the legacy cost model and the underlying instructions.
virtual void printRecipe (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const =0
Each concrete VPRecipe prints itself, without printing common information, like debug info or metadata.
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Friends
class VPBlockUtils
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Detailed Description
VPRecipeBase is a base class modeling a sequence of one or more output IR instructions.
VPRecipeBase owns the VPValues it defines through VPDef and is responsible for deleting its defined values. Single-value recipes must inherit from VPSingleDef instead of inheriting from both VPRecipeBase and VPValue separately.
Definition at line 384 of file VPlan.h.
Constructor & Destructor Documentation
VPRecipeBase()
llvm::VPRecipeBase::VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL = DebugLoc::getUnknown()) inline
Definition at line 398 of file VPlan.h.
References llvm::DebugLoc::getUnknown(), llvm::VPDef::VPDef(), and llvm::VPUser::VPUser().
Referenced by llvm::VPInterleaveBase::classof(), llvm::VPSingleDefRecipe::classof(), llvm::VPWidenMemoryRecipe::classof(), clone(), execute(), insertAfter(), insertBefore(), moveAfter(), llvm::VPBranchOnMaskRecipe::VPBranchOnMaskRecipe(), llvm::VPHistogramRecipe::VPHistogramRecipe(), llvm::VPInterleaveBase::VPInterleaveBase(), llvm::VPIRInstruction::VPIRInstruction(), llvm::VPSingleDefRecipe::VPSingleDefRecipe(), llvm::VPSingleDefRecipe::VPSingleDefRecipe(), and llvm::VPWidenMemoryRecipe::VPWidenMemoryRecipe().
~VPRecipeBase()
llvm::VPRecipeBase::~VPRecipeBase () override default
Member Function Documentation
classof() [1/2]
bool llvm::VPRecipeBase::classof (const VPDef * D) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 454 of file VPlan.h.
References D(), and llvm::VPDef::VPDef().
classof() [2/2]
bool llvm::VPRecipeBase::classof (const VPUser * U) inline static
Definition at line 459 of file VPlan.h.
References llvm::VPUser::VPUser().
clone()
virtual VPRecipeBase * llvm::VPRecipeBase::clone () pure virtual
Clone the current recipe.
Implemented in llvm::VPActiveLaneMaskPHIRecipe, llvm::VPBlendRecipe, llvm::VPBranchOnMaskRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPDerivedIVRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPExpandSCEVRecipe, llvm::VPExpressionRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPHistogramRecipe, llvm::VPInstruction, llvm::VPInstructionWithType, llvm::VPInterleaveBase, llvm::VPInterleaveEVLRecipe, llvm::VPInterleaveRecipe, llvm::VPIRInstruction, llvm::VPPhi, llvm::VPPredInstPHIRecipe, llvm::VPRecipeWithIRFlags, llvm::VPReductionEVLRecipe, llvm::VPReductionPHIRecipe, llvm::VPReductionRecipe, llvm::VPReplicateRecipe, llvm::VPScalarIVStepsRecipe, llvm::VPSingleDefRecipe, llvm::VPVectorEndPointerRecipe, llvm::VPVectorPointerRecipe, llvm::VPWidenCallRecipe, llvm::VPWidenCanonicalIVRecipe, llvm::VPWidenCastRecipe, llvm::VPWidenGEPRecipe, llvm::VPWidenIntOrFpInductionRecipe, llvm::VPWidenIntrinsicRecipe, llvm::VPWidenLoadRecipe, llvm::VPWidenMemoryRecipe, llvm::VPWidenPHIRecipe, llvm::VPWidenPointerInductionRecipe, llvm::VPWidenRecipe, and llvm::VPWidenStoreRecipe.
References VPRecipeBase().
computeCost()
InstructionCost VPRecipeBase::computeCost (ElementCount VF, VPCostContext & Ctx) const protected virtual
Compute the cost of this recipe either using a recipe's specialized implementation or using the legacy cost model and the underlying instructions.
Reimplemented in llvm::VPBlendRecipe, llvm::VPBranchOnMaskRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPDerivedIVRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPExpandSCEVRecipe, llvm::VPExpressionRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPHeaderPHIRecipe, llvm::VPHistogramRecipe, llvm::VPInstruction, llvm::VPInstructionWithType, llvm::VPInterleaveBase, llvm::VPIRInstruction, llvm::VPPredInstPHIRecipe, llvm::VPReductionRecipe, llvm::VPReplicateRecipe, llvm::VPScalarIVStepsRecipe, llvm::VPVectorEndPointerRecipe, llvm::VPVectorPointerRecipe, llvm::VPWidenCallRecipe, llvm::VPWidenCanonicalIVRecipe, llvm::VPWidenCastRecipe, llvm::VPWidenGEPRecipe, llvm::VPWidenIntrinsicRecipe, llvm::VPWidenLoadEVLRecipe, llvm::VPWidenMemoryRecipe, llvm::VPWidenRecipe, and llvm::VPWidenStoreEVLRecipe.
Definition at line 299 of file VPlanRecipes.cpp.
References llvm_unreachable.
Referenced by cost().
cost()
InstructionCost VPRecipeBase::cost (ElementCount VF, VPCostContext & Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
Also takes care of printing the cost for debugging.
Definition at line 265 of file VPlanRecipes.cpp.
References computeCost(), llvm::dbgs(), llvm::VPDef::dump(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ForceTargetInstructionCost, InstructionCost, llvm::InstructionCost::isValid(), llvm::ElementCount::isVector(), and LLVM_DEBUG.
Referenced by execute().
eraseFromParent()
iplist< VPRecipeBase >::iterator VPRecipeBase::eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Returns
an iterator pointing to the element after the erased one
Definition at line 249 of file VPlanRecipes.cpp.
References assert(), llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >::getIterator(), getParent(), and llvm::VPBasicBlock::getRecipeList().
Referenced by llvm::VPlanTransforms::addActiveLaneMask(), addCanonicalIVRecipes(), addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPlanTransforms::createInterleaveGroups(), createReplicateRegion(), execute(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::introduceMasksAndLinearize(), preparePlanForMainVectorLoop(), and removeRedundantCanonicalIVs().
execute()
virtual void llvm::VPRecipeBase::execute (VPTransformState & State) pure virtual
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
Implemented in llvm::VPActiveLaneMaskPHIRecipe, llvm::VPBlendRecipe, llvm::VPBranchOnMaskRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPDerivedIVRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPExpandSCEVRecipe, llvm::VPExpressionRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPHeaderPHIRecipe, llvm::VPHistogramRecipe, llvm::VPInstruction, llvm::VPInstructionWithType, llvm::VPInterleaveBase, llvm::VPInterleaveEVLRecipe, llvm::VPInterleaveRecipe, llvm::VPIRInstruction, llvm::VPIRPhi, llvm::VPPhi, llvm::VPPredInstPHIRecipe, llvm::VPRecipeWithIRFlags, llvm::VPReductionEVLRecipe, llvm::VPReductionPHIRecipe, llvm::VPReductionRecipe, llvm::VPReplicateRecipe, llvm::VPScalarIVStepsRecipe, llvm::VPVectorEndPointerRecipe, llvm::VPVectorPointerRecipe, llvm::VPWidenCallRecipe, llvm::VPWidenCanonicalIVRecipe, llvm::VPWidenCastRecipe, llvm::VPWidenGEPRecipe, llvm::VPWidenInductionRecipe, llvm::VPWidenIntOrFpInductionRecipe, llvm::VPWidenIntrinsicRecipe, llvm::VPWidenLoadEVLRecipe, llvm::VPWidenLoadRecipe, llvm::VPWidenMemoryRecipe, llvm::VPWidenPHIRecipe, llvm::VPWidenPointerInductionRecipe, llvm::VPWidenRecipe, llvm::VPWidenStoreEVLRecipe, and llvm::VPWidenStoreRecipe.
References cost(), eraseFromParent(), I, insertAfter(), insertBefore(), moveAfter(), moveBefore(), removeFromParent(), and VPRecipeBase().
getDebugLoc()
DebugLoc llvm::VPRecipeBase::getDebugLoc () const inline
Returns the debug location of the recipe.
Definition at line 479 of file VPlan.h.
Referenced by addCanonicalIVRecipes(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPActiveLaneMaskPHIRecipe::clone(), llvm::VPCanonicalIVPHIRecipe::clone(), llvm::VPHistogramRecipe::clone(), llvm::VPInstructionWithType::clone(), llvm::VPVectorEndPointerRecipe::clone(), llvm::VPVectorPointerRecipe::clone(), llvm::VPWidenCastRecipe::clone(), llvm::VPWidenIntOrFpInductionRecipe::clone(), llvm::VPWidenIntrinsicRecipe::clone(), llvm::VPWidenPointerInductionRecipe::clone(), createReplicateRegion(), llvm::VPInstructionWithType::execute(), llvm::VPPhi::execute(), expandVPWidenIntOrFpInduction(), llvm::VPRecipeBuilder::handleReplication(), optimizeMaskToEVL(), print(), scalarizeInstruction(), scalarizeVPWidenPointerInduction(), tryToComputeEndValueForInduction(), llvm::VPRecipeBuilder::tryToCreateWidenNonPhiRecipe(), and tryToReplaceALMWithWideALM().
getParent() [1/2]
VPBasicBlock * llvm::VPRecipeBase::getParent () inline
Returns
the VPBasicBlock which this VPRecipe belongs to.
Definition at line 408 of file VPlan.h.
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPInstruction::dump(), eraseFromParent(), llvm::VPActiveLaneMaskPHIRecipe::execute(), llvm::VPFirstOrderRecurrencePHIRecipe::execute(), llvm::VPIRPhi::execute(), llvm::VPPhi::execute(), llvm::VPReductionPHIRecipe::execute(), expandVPWidenIntOrFpInduction(), llvm::VPPhiAccessors::getIncomingBlock(), llvm::VPSlotTracker::getOrCreateName(), getRegion(), getRegion(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::VPlanTransforms::hoistPredicatedLoads(), hoistPreviousBeforeFORUsers(), insertAfter(), insertBefore(), isDefinedInsideLoopRegions(), optimizeMaskToEVL(), removeFromParent(), scalarizeInstruction(), llvm::VPBuilder::setInsertPoint(), llvm::VPlanTransforms::sinkPredicatedStores(), and transformRecipestoEVLRecipes().
getParent() [2/2]
const VPBasicBlock * llvm::VPRecipeBase::getParent () const inline
Definition at line 409 of file VPlan.h.
getRegion() [1/2]
VPRegionBlock * llvm::VPRecipeBase::getRegion () inline
Returns
the VPRegionBlock which the recipe belongs to.
Definition at line 4253 of file VPlan.h.
References llvm::VPBlockBase::getParent(), and getParent().
Referenced by llvm::VPReplicateRecipe::computeCost(), hoistPreviousBeforeFORUsers(), llvm::VPWidenIntOrFpInductionRecipe::isCanonical(), and scalarizeInstruction().
getRegion() [2/2]
const VPRegionBlock * llvm::VPRecipeBase::getRegion () const inline
Definition at line 4257 of file VPlan.h.
References llvm::VPBlockBase::getParent(), and getParent().
insertAfter()
void VPRecipeBase::insertAfter (VPRecipeBase * InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
Definition at line 236 of file VPlanRecipes.cpp.
References assert(), llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), llvm::VPBasicBlock::insert(), and VPRecipeBase().
Referenced by execute(), llvm::VPlanTransforms::materializePacksAndUnpacks(), moveAfter(), and tryToReplaceALMWithWideALM().
insertBefore() [1/2]
void VPRecipeBase::insertBefore (VPBasicBlock & BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
Definition at line 229 of file VPlanRecipes.cpp.
References assert(), llvm::VPBasicBlock::end(), I, and llvm::VPBasicBlock::insert().
insertBefore() [2/2]
void VPRecipeBase::insertBefore (VPRecipeBase * InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
Definition at line 222 of file VPlanRecipes.cpp.
References assert(), llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), llvm::VPBasicBlock::insert(), and VPRecipeBase().
Referenced by llvm::VPlanTransforms::createHeaderPhiRecipes(), execute(), llvm::VPlanTransforms::expandSCEVs(), llvm::VPlanTransforms::materializePacksAndUnpacks(), moveBefore(), narrowToSingleScalarRecipes(), optimizeMaskToEVL(), sinkScalarOperands(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::tryToConvertVPInstructionsToVPRecipes(), tryToCreateAbstractReductionRecipe(), and tryToMatchAndCreateMulAccumulateReduction().
isPhi()
bool VPRecipeBase::isPhi () const
Returns true for PHI-like recipes.
Definition at line 304 of file VPlanRecipes.cpp.
References llvm::VPDef::getVPDefID(), and llvm::isa().
isScalarCast()
bool VPRecipeBase::isScalarCast () const
Return true if the recipe is a scalar cast.
Definition at line 309 of file VPlanRecipes.cpp.
References llvm::dyn_cast(), and llvm::Instruction::isCast().
Referenced by llvm::VPInstructionWithType::execute(), and llvm::VPInstruction::isSingleScalar().
mayHaveSideEffects()
bool VPRecipeBase::mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
Definition at line 159 of file VPlanRecipes.cpp.
References assert(), llvm::VPInstruction::BranchOnCond, llvm::VPInstruction::BranchOnCount, llvm::VPInstruction::BranchOnTwoConds, llvm::cast(), llvm::Function::doesNotThrow(), llvm::dyn_cast_or_null(), llvm::VPDef::getVPDefID(), llvm::VPDef::getVPSingleValue(), I, mayHaveSideEffects(), mayWriteToMemory(), and llvm::Function::willReturn().
Referenced by mayHaveSideEffects().
mayReadFromMemory()
bool VPRecipeBase::mayReadFromMemory () const
Returns true if the recipe may read from memory.
Definition at line 109 of file VPlanRecipes.cpp.
References assert(), llvm::cast(), llvm::dyn_cast_or_null(), llvm::VPDef::getVPDefID(), llvm::VPDef::getVPSingleValue(), and I.
Referenced by mayReadOrWriteMemory().
mayReadOrWriteMemory()
bool llvm::VPRecipeBase::mayReadOrWriteMemory () const inline
Returns true if the recipe may read from or write to memory.
Definition at line 474 of file VPlan.h.
References mayReadFromMemory(), and mayWriteToMemory().
mayWriteToMemory()
bool VPRecipeBase::mayWriteToMemory () const
Returns true if the recipe may write to memory.
Definition at line 50 of file VPlanRecipes.cpp.
References assert(), llvm::cast(), llvm::dyn_cast_or_null(), llvm::VPDef::getVPDefID(), llvm::VPDef::getVPSingleValue(), and I.
Referenced by mayHaveSideEffects(), and mayReadOrWriteMemory().
moveAfter()
void VPRecipeBase::moveAfter (VPRecipeBase * MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
Definition at line 254 of file VPlanRecipes.cpp.
References insertAfter(), removeFromParent(), and VPRecipeBase().
Referenced by execute(), and llvm::VPlanTransforms::handleMaxMinNumReductions().
moveBefore()
void VPRecipeBase::moveBefore (VPBasicBlock & BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
Precondition
I is a valid iterator into BB.
Definition at line 259 of file VPlanRecipes.cpp.
References I, insertBefore(), and removeFromParent().
Referenced by execute(), llvm::VPlanTransforms::handleMultiUseReductions(), preparePlanForMainVectorLoop(), and sinkScalarOperands().
print()
void VPRecipeBase::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const final override virtual
Print the recipe, delegating to printRecipe().
Implements llvm::VPDef.
Definition at line 372 of file VPlanRecipes.cpp.
References llvm::dyn_cast(), getDebugLoc(), llvm::Metadata::print(), and printRecipe().
Referenced by llvm::VPBasicBlock::print().
printRecipe()
virtual void llvm::VPRecipeBase::printRecipe (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const protected pure virtual
Each concrete VPRecipe prints itself, without printing common information, like debug info or metadata.
Implemented in llvm::VPActiveLaneMaskPHIRecipe, llvm::VPBlendRecipe, llvm::VPBranchOnMaskRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPDerivedIVRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPExpandSCEVRecipe, llvm::VPExpressionRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPHeaderPHIRecipe, llvm::VPHistogramRecipe, llvm::VPInstruction, llvm::VPInstructionWithType, llvm::VPInterleaveEVLRecipe, llvm::VPInterleaveRecipe, llvm::VPIRInstruction, llvm::VPIRPhi, llvm::VPPhi, llvm::VPPredInstPHIRecipe, llvm::VPReductionEVLRecipe, llvm::VPReductionPHIRecipe, llvm::VPReductionRecipe, llvm::VPReplicateRecipe, llvm::VPScalarIVStepsRecipe, llvm::VPVectorEndPointerRecipe, llvm::VPVectorPointerRecipe, llvm::VPWidenCallRecipe, llvm::VPWidenCanonicalIVRecipe, llvm::VPWidenCastRecipe, llvm::VPWidenGEPRecipe, llvm::VPWidenIntOrFpInductionRecipe, llvm::VPWidenIntrinsicRecipe, llvm::VPWidenLoadEVLRecipe, llvm::VPWidenLoadRecipe, llvm::VPWidenPHIRecipe, llvm::VPWidenPointerInductionRecipe, llvm::VPWidenRecipe, llvm::VPWidenStoreEVLRecipe, and llvm::VPWidenStoreRecipe.
Referenced by print().
removeFromParent()
void VPRecipeBase::removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
Definition at line 243 of file VPlanRecipes.cpp.
References assert(), llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >::getIterator(), getParent(), llvm::VPBasicBlock::getRecipeList(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by execute(), moveAfter(), and moveBefore().
setDebugLoc()
void llvm::VPRecipeBase::setDebugLoc (DebugLoc NewDL) inline
Set the recipe's debug location to NewDL.
Definition at line 485 of file VPlan.h.
Friends And Related Symbol Documentation
VPBlockUtils
friend class VPBlockUtils friend
Definition at line 389 of file VPlan.h.
References VPBlockUtils.
Referenced by VPBlockUtils.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp