LLVM: llvm::LiveVariablesPrinterPass Class Reference
llvm::LiveVariablesPrinterPass Class Reference
#include "llvm/CodeGen/LiveVariables.h"
Public Member Functions
LiveVariablesPrinterPass (raw_ostream &OS)
LLVM_ABI PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< LiveVariablesPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< LiveVariablesPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 313 of file LiveVariables.h.
Constructor & Destructor Documentation
LiveVariablesPrinterPass()
llvm::LiveVariablesPrinterPass::LiveVariablesPrinterPass (raw_ostream & OS) inline explicit
Definition at line 318 of file LiveVariables.h.
Member Function Documentation
isRequired()
bool llvm::LiveVariablesPrinterPass::isRequired () inline static
Definition at line 321 of file LiveVariables.h.
run()
PreservedAnalyses LiveVariablesPrinterPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 52 of file LiveVariables.cpp.
References llvm::PreservedAnalyses::all(), llvm::MachineFunction::getName(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::print().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveVariables.h
lib/CodeGen/LiveVariables.cpp