LLVM: StaleMatcher Class Reference
StaleMatcher Class Reference
The object is used to identify and match basic blocks given their hashes.
Public Member Functions
void init (const std::vector< MachineBasicBlock * > &Blocks, const std::vector< BlendedBlockHash > &Hashes)
Initialize stale matcher.
MachineBasicBlock * matchBlock (BlendedBlockHash BlendedHash) const
Find the most similar block for a given hash.
Detailed Description
The object is used to identify and match basic blocks given their hashes.
Definition at line 37 of file BasicBlockMatchingAndInference.cpp.
Member Function Documentation
init()
void StaleMatcher::init (const std::vector< MachineBasicBlock * > & Blocks, const std::vector< BlendedBlockHash > & Hashes) inline
Initialize stale matcher.
Definition at line 40 of file BasicBlockMatchingAndInference.cpp.
References assert(), llvm::Block, and I.
matchBlock()
MachineBasicBlock * StaleMatcher::matchBlock (BlendedBlockHash BlendedHash) const inline
Find the most similar block for a given hash.
Definition at line 52 of file BasicBlockMatchingAndInference.cpp.
References llvm::Block, llvm::BlendedBlockHash::distance(), and llvm::BlendedBlockHash::getOpcodeHash().
The documentation for this class was generated from the following file:
lib/CodeGen/BasicBlockMatchingAndInference.cpp