LLVM: llvm::lto::DTLTO Class Reference
llvm::lto::DTLTO Class Reference
#include "llvm/DTLTO/DTLTO.h"
Public Member Functions
LLVM_ABI DTLTO (Config Conf, ThinBackend Backend, unsigned ParallelCodeGenParallelismLevel, LTOKind LTOMode, StringRef LinkerOutputFile, bool SaveTemps)
LLVM_ABI Expected< std::shared_ptr< InputFile > > addInput (std::unique_ptr< InputFile > InputPtr) override
Public Member Functions inherited from llvm::lto::LTO
LLVM_ABI LTO (Config Conf, ThinBackend Backend={}, unsigned ParallelCodeGenParallelismLevel=1, LTOKind LTOMode=LTOK_Default)
Create an LTO object.
virtual LLVM_ABI ~LTO ()
LLVM_ABI Error add (std::unique_ptr< InputFile > Obj, ArrayRef< SymbolResolution > Res)
Add an input file to the LTO link, using the provided symbol resolutions.
LLVM_ABI unsigned getMaxTasks () const
Returns an upper bound on the number of tasks that the client may expect.
LLVM_ABI Error run (AddStreamFn AddStream, FileCache Cache={})
Runs the LTO pipeline.
virtual Expected< std::shared_ptr< lto::InputFile > > addInput (std::unique_ptr< lto::InputFile > InputPtr)
Protected Member Functions
LLVM_ABI llvm::Error serializeInputsForDistribution () override
LLVM_ABI void cleanup () override
Additional Inherited Members
Public Types inherited from llvm::lto::LTO
enum LTOKind { LTOK_Default , LTOK_UnifiedRegular , LTOK_UnifiedThin }
Unified LTO modes.
Static Public Member Functions inherited from llvm::lto::LTO
static LLVM_ABI SmallVector< const char * > getRuntimeLibcallSymbols (const Triple &TT)
Static method that returns a list of libcall symbols that can be generated by LTO but might not be visible from bitcode symbol table.
Detailed Description
Definition at line 34 of file DTLTO.h.
Constructor & Destructor Documentation
DTLTO()
LLVM_ABI llvm::lto::DTLTO::DTLTO (Config Conf, ThinBackend Backend, unsigned ParallelCodeGenParallelismLevel, LTOKind LTOMode, StringRef LinkerOutputFile, bool SaveTemps) inline
Definition at line 38 of file DTLTO.h.
References assert(), LLVM_ABI, and llvm::move().
Member Function Documentation
addInput()
Expected< std::shared_ptr< lto::InputFile > > lto::DTLTO::addInput (std::unique_ptr< InputFile > InputPtr) override
Definition at line 156 of file DTLTO.cpp.
References llvm::sys::path::append(), llvm::StringRef::empty(), llvm::sys::path::filename(), llvm::sys::Process::getProcessId(), N, llvm::sys::path::parent_path(), llvm::BitcodeModule::setModuleIdentifier(), llvm::Error::success(), and llvm::Expected< T >::takeError().
cleanup()
void lto::DTLTO::cleanup () override protected virtual
Reimplemented from llvm::lto::LTO.
Definition at line 250 of file DTLTO.cpp.
References llvm::lto::LTO::cleanup(), llvm::errs(), and llvm::sys::fs::remove().
serializeInputsForDistribution()
llvm::Error lto::DTLTO::serializeInputsForDistribution () override protected virtual
Reimplemented from llvm::lto::LTO.
Definition at line 232 of file DTLTO.cpp.
References llvm::sys::RemoveFileOnSignal(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/DTLTO/DTLTO.h
lib/DTLTO/DTLTO.cpp