LLVM: llvm::sandboxir::CreateAndInsertInst Class Reference
llvm::sandboxir::CreateAndInsertInst Class Reference final
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
CreateAndInsertInst (Instruction *NewI)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 413 of file Tracker.h.
Constructor & Destructor Documentation
CreateAndInsertInst()
llvm::sandboxir::CreateAndInsertInst::CreateAndInsertInst (Instruction * NewI) inline
Definition at line 417 of file Tracker.h.
Member Function Documentation
accept()
void llvm::sandboxir::CreateAndInsertInst::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 419 of file Tracker.h.
dump() [1/2]
void CreateAndInsertInst::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 301 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::CreateAndInsertInst::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 421 of file Tracker.h.
revert()
void CreateAndInsertInst::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 298 of file Tracker.cpp.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp