LLVM: llvm::FileCheckPatternContext Class Reference
llvm::FileCheckPatternContext Class Reference
Class holding the Pattern global state, shared by all patterns: tables holding values of variables and whether they are defined or not at any given time in the matching process.
#include "FileCheck/FileCheckImpl.h"
Public Member Functions
LLVM_ABI_FOR_TEST Expected< StringRef > getPatternVarValue (StringRef VarName)
LLVM_ABI_FOR_TEST Error defineCmdlineVariables (ArrayRef< StringRef > CmdlineDefines, SourceMgr &SM)
Defines string and numeric variables from definitions given on the command line, passed as a vector of [#]VAR=VAL strings in CmdlineDefines.
LLVM_ABI_FOR_TEST void createLineVariable ()
Create @LINE pseudo variable.
LLVM_ABI_FOR_TEST void clearLocalVars ()
Undefines local variables (variables whose name does not start with a '$' sign), i.e.
Friends
class Pattern
Detailed Description
Class holding the Pattern global state, shared by all patterns: tables holding values of variables and whether they are defined or not at any given time in the matching process.
Definition at line 432 of file FileCheckImpl.h.
Member Function Documentation
clearLocalVars()
void FileCheckPatternContext::clearLocalVars ()
Undefines local variables (variables whose name does not start with a '$' sign), i.e.
removes them from GlobalVariableTable and from GlobalNumericVariableTable and also clears the value of numeric variables.
Definition at line 2694 of file FileCheck.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
createLineVariable()
void FileCheckPatternContext::createLineVariable ()
Create @LINE pseudo variable.
Value is set when pattern are being matched.
Definition at line 1812 of file FileCheck.cpp.
References assert(), and llvm::ExpressionFormat::Unsigned.
defineCmdlineVariables()
Error FileCheckPatternContext::defineCmdlineVariables (ArrayRef< StringRef > CmdlineDefines, SourceMgr & SM)
Defines string and numeric variables from definitions given on the command line, passed as a vector of [#]VAR=VAL strings in CmdlineDefines.
Returns
an error list containing diagnostics against SM for all definition parsing failures, if any, or Success otherwise.
Definition at line 2556 of file FileCheck.cpp.
References assert(), llvm::ArrayRef< T >::empty(), llvm::StringRef::empty(), llvm::ExpressionAST::eval(), llvm::ErrorDiagnostic::get(), llvm::Expression::getAST(), llvm::MemoryBuffer::getMemBufferCopy(), I, llvm::joinErrors(), llvm::StringRef::npos, llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parseVariable(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), SM(), llvm::StringRef::split(), llvm::StringRef::substr(), llvm::Error::success(), and llvm::Expected< T >::takeError().
getPatternVarValue()
Expected< StringRef > FileCheckPatternContext::getPatternVarValue (StringRef VarName)
Returns
the value of string variable VarName or an error if no such variable has been defined.
Definition at line 1414 of file FileCheck.cpp.
References llvm::make_error().
Friends And Related Symbol Documentation
Pattern
friend class Pattern friend
Definition at line 433 of file FileCheckImpl.h.
References args, LLVM_ABI_FOR_TEST, Pattern, and SM().
Referenced by Pattern.
The documentation for this class was generated from the following files:
lib/FileCheck/FileCheckImpl.h
lib/FileCheck/FileCheck.cpp