LLVM: llvm::codeview::InlineSiteSym Class Reference
llvm::codeview::InlineSiteSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
InlineSiteSym (SymbolRecordKind Kind)
InlineSiteSym (uint32_t RecordOffset)
iterator_range< BinaryAnnotationIterator > annotations () const
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
uint32_t Parent = 0
uint32_t End = 0
TypeIndex Inlinee
std::vector< uint8_t > AnnotationData
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 365 of file SymbolRecord.h.
Constructor & Destructor Documentation
InlineSiteSym() [1/2]
llvm::codeview::InlineSiteSym::InlineSiteSym (SymbolRecordKind Kind) inline explicit
Definition at line 367 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by InlineSiteSym().
InlineSiteSym() [2/2]
llvm::codeview::InlineSiteSym::InlineSiteSym (uint32_t RecordOffset) inline explicit
Definition at line 368 of file SymbolRecord.h.
References InlineSiteSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Function Documentation
annotations()
iterator_range< BinaryAnnotationIterator > llvm::codeview::InlineSiteSym::annotations () const inline
Definition at line 372 of file SymbolRecord.h.
References AnnotationData, and llvm::make_range().
Referenced by inlineSiteContainsAddress().
Member Data Documentation
AnnotationData
std::vector<uint8_t> llvm::codeview::InlineSiteSym::AnnotationData
Definition at line 380 of file SymbolRecord.h.
Referenced by annotations().
End
uint32_t llvm::codeview::InlineSiteSym::End = 0
Definition at line 378 of file SymbolRecord.h.
Referenced by llvm::pdb::NativeFunctionSymbol::findInlineFramesByVA(), and llvm::codeview::getScopeEndOffset().
Inlinee
TypeIndex llvm::codeview::InlineSiteSym::Inlinee
Definition at line 379 of file SymbolRecord.h.
Parent
uint32_t llvm::codeview::InlineSiteSym::Parent = 0
Definition at line 377 of file SymbolRecord.h.
Referenced by llvm::codeview::getScopeParentOffset().
RecordOffset
uint32_t llvm::codeview::InlineSiteSym::RecordOffset = 0
Definition at line 382 of file SymbolRecord.h.
Referenced by InlineSiteSym().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h