LLVM: llvm::abi::VectorType Class Reference
llvm::abi::VectorType Class Reference
#include "llvm/ABI/Types.h"
Public Member Functions
VectorType (const Type *ElementType, ElementCount NumElements, Align ABIAlign)
const Type * getElementType () const
ElementCount getNumElements () const
Public Member Functions inherited from llvm::abi::Type
TypeKind getKind () const
TypeSize getSizeInBits () const
Align getAlignment () const
TypeSize getTypeAllocSize () const
bool isVoid () const
bool isInteger () const
bool isFloat () const
bool isPointer () const
bool isArray () const
bool isVector () const
bool isRecord () const
bool isMemberPointer () const
bool isComplex () const
Static Public Member Functions
static bool classof (const Type *T)
Additional Inherited Members
Protected Member Functions inherited from llvm::abi::Type
Type (TypeKind K, TypeSize SizeInBits, Align ABIAlign)
Protected Attributes inherited from llvm::abi::Type
TypeKind Kind
TypeSize SizeInBits
Align ABIAlignment
Detailed Description
Definition at line 212 of file Types.h.
Constructor & Destructor Documentation
VectorType()
llvm::abi::VectorType::VectorType (const Type * ElementType, ElementCount NumElements, Align ABIAlign) inline
Definition at line 218 of file Types.h.
References llvm::abi::Type::getSizeInBits(), and llvm::abi::Type::Type().
Member Function Documentation
classof()
bool llvm::abi::VectorType::classof (const Type * T) inline static
Definition at line 229 of file Types.h.
References T, llvm::abi::Type::Type(), and llvm::abi::Vector.
getElementType()
const Type * llvm::abi::VectorType::getElementType () const inline
Definition at line 226 of file Types.h.
References llvm::abi::Type::Type().
getNumElements()
ElementCount llvm::abi::VectorType::getNumElements () const inline
Definition at line 227 of file Types.h.
The documentation for this class was generated from the following file:
include/llvm/ABI/Types.h