LLVM: llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > Class Reference
llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > Class Reference
#include "llvm/Transforms/Scalar/LoopPassManager.h"
Public Member Functions
PassManager ()=default
PassManager (PassManager &&Arg)
PassManager & operator= (PassManager &&RHS)
LLVM_ABI PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
LLVM_ABI void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
template<typename PassT>
LLVM_ATTRIBUTE_MINSIZE void addPass (PassT &&Pass)
bool isEmpty () const
size_t getNumLoopPasses () const
size_t getNumLoopNestPasses () const
LLVM_ABI PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &G, CGSCCUpdateResult &UR)
LLVM_ABI PreservedAnalyses run (MachineFunction &, AnalysisManager< MachineFunction > &)
PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &G, CGSCCUpdateResult &UR)
Explicitly specialize the pass manager run method to handle call graph updates.
Public Member Functions inherited from llvm::PassInfoMixin< DerivedT >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< DerivedT >
static StringRef name ()
Gets the name of the pass we are mixed into.
Static Public Member Functions inherited from llvm::PassInfoMixin< PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Protected Types
using LoopPassConceptT
using LoopNestPassConceptT
using PassConceptT
Protected Member Functions
template<typename IRUnitT, typename PassT>
std::optional< PreservedAnalyses > runSinglePass (IRUnitT &IR, PassT &Pass, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U, PassInstrumentation &PI)
Run either a loop pass or a loop-nest pass.
LLVM_ABI PreservedAnalyses runWithLoopNestPasses (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
LLVM_ABI PreservedAnalyses runWithoutLoopNestPasses (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Protected Attributes
BitVector IsLoopNestPass
std::vector< std::unique_ptr< LoopPassConceptT > > LoopPasses
std::vector< std::unique_ptr< LoopNestPassConceptT > > LoopNestPasses
std::vector< std::unique_ptr< PassConceptT > > Passes
Detailed Description
Definition at line 71 of file LoopPassManager.h.
Member Typedef Documentation
LoopNestPassConceptT
using llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopNestPassConceptT protected
Initial value:
detail::PassConcept<LoopNest, LoopAnalysisManager,
                    LoopStandardAnalysisResults &, LPMUpdater &>
Definition at line 141 of file LoopPassManager.h.
LoopPassConceptT
using llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopPassConceptT protected
Initial value:
detail::PassConcept<Loop, LoopAnalysisManager,
                    LoopStandardAnalysisResults &, LPMUpdater &>
Definition at line 138 of file LoopPassManager.h.
PassConceptT
using llvm::PassManager< Loop, LoopAnalysisManager, ExtraArgTs >::PassConceptT protected
Definition at line 222 of file PassManager.h.
Constructor & Destructor Documentation
PassManager() [1/2]
llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::PassManager () explicit default
Referenced by operator=(), and PassManager().
PassManager() [2/2]
llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::PassManager (PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > && Arg) inline
Definition at line 83 of file LoopPassManager.h.
References IsLoopNestPass, LoopNestPasses, LoopPasses, llvm::move(), and PassManager().
Member Function Documentation
addPass()
template<typename PassT> LLVM_ATTRIBUTE_MINSIZE void llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass (PassT && Pass) inline
Definition at line 108 of file LoopPassManager.h.
References IsLoopNestPass, LLVM_ATTRIBUTE_MINSIZE, LoopNestPasses, and LoopPasses.
Referenced by llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addIRPasses(), llvm::PassBuilder::buildFunctionSimplificationPipeline(), llvm::PassBuilder::buildLTODefaultPipeline(), llvm::PassBuilder::buildModuleOptimizationPipeline(), llvm::createFunctionToLoopPassAdaptor(), llvm::AArch64TargetMachine::registerPassBuilderCallbacks(), llvm::HexagonTargetMachine::registerPassBuilderCallbacks(), and llvm::RISCVTargetMachine::registerPassBuilderCallbacks().
getNumLoopNestPasses()
size_t llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::getNumLoopNestPasses () const inline
Definition at line 135 of file LoopPassManager.h.
References LoopNestPasses.
getNumLoopPasses()
size_t llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::getNumLoopPasses () const inline
Definition at line 134 of file LoopPassManager.h.
References LoopPasses.
isEmpty()
bool llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::isEmpty () const inline
Definition at line 130 of file LoopPassManager.h.
References LoopNestPasses, and LoopPasses.
Referenced by llvm::PassBuilder::buildO0DefaultPipeline().
isRequired()
bool llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::isRequired () inline static
Definition at line 132 of file LoopPassManager.h.
operator=()
PassManager & llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::operator= (PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > && RHS) inline
Definition at line 88 of file LoopPassManager.h.
References IsLoopNestPass, LoopNestPasses, LoopPasses, PassManager(), and RHS.
printPipeline()
LLVM_ABI void llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
run() [1/4]
LLVM_ABI PreservedAnalyses llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run (LazyCallGraph::SCC & InitialC, CGSCCAnalysisManager & AM, LazyCallGraph & G, CGSCCUpdateResult & UR)
run() [2/4]
PreservedAnalyses llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run (LazyCallGraph::SCC & InitialC, CGSCCAnalysisManager & AM, LazyCallGraph & G, CGSCCUpdateResult & UR)
Explicitly specialize the pass manager run method to handle call graph updates.
Definition at line 68 of file CGSCCPassManager.cpp.
run() [3/4]
LLVM_ABI PreservedAnalyses llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
References LLVM_ABI.
run() [4/4]
LLVM_ABI PreservedAnalyses llvm::PassManager< MachineFunction >::run (MachineFunction & , AnalysisManager< MachineFunction > &)
runSinglePass()
template<typename IRUnitT, typename PassT> std::optional< PreservedAnalyses > llvm::LoopPassManager::runSinglePass (IRUnitT & IR, PassT & Pass, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U, PassInstrumentation & PI) protected
Run either a loop pass or a loop-nest pass.
Returns std::nullopt if PassInstrumentation's BeforePass returns false. Otherwise, returns the preserved analyses of the pass.
Definition at line 361 of file LoopPassManager.h.
References IR.
Referenced by runWithLoopNestPasses(), and runWithoutLoopNestPasses().
runWithLoopNestPasses()
PreservedAnalyses LoopPassManager::runWithLoopNestPasses (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U) protected
Definition at line 63 of file LoopPassManager.cpp.
References llvm::PreservedAnalyses::all(), assert(), llvm::LoopNest::getLoopNest(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), IsLoopNestPass, LoopNestPasses, LoopPasses, runSinglePass(), and llvm::LoopStandardAnalysisResults::SE.
runWithoutLoopNestPasses()
PreservedAnalyses LoopPassManager::runWithoutLoopNestPasses (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U) protected
Definition at line 146 of file LoopPassManager.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), LoopPasses, and runSinglePass().
Member Data Documentation
IsLoopNestPass
BitVector llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::IsLoopNestPass protected
Definition at line 147 of file LoopPassManager.h.
Referenced by addPass(), operator=(), PassManager(), and runWithLoopNestPasses().
LoopNestPasses
std::vector<std::unique_ptr<LoopNestPassConceptT> > llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopNestPasses protected
Definition at line 149 of file LoopPassManager.h.
Referenced by addPass(), getNumLoopNestPasses(), isEmpty(), operator=(), PassManager(), and runWithLoopNestPasses().
LoopPasses
std::vector<std::unique_ptr<LoopPassConceptT> > llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopPasses protected
Definition at line 148 of file LoopPassManager.h.
Referenced by addPass(), getNumLoopPasses(), isEmpty(), operator=(), PassManager(), runWithLoopNestPasses(), and runWithoutLoopNestPasses().
Passes
std::vector<std::unique_ptr<PassConceptT> > llvm::PassManager< Loop, LoopAnalysisManager, ExtraArgTs >::Passes protected
Definition at line 225 of file PassManager.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopPassManager.h
include/llvm/IR/PassManagerImpl.h
lib/Transforms/Scalar/LoopPassManager.cpp