LLVM: llvm::coverage::FunctionRecordIterator Class Reference
llvm::coverage::FunctionRecordIterator Class Reference
Iterator over Functions, optionally filtered to a single file.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Member Functions
FunctionRecordIterator (ArrayRef< FunctionRecord > Records_, StringRef Filename="", ArrayRef< unsigned > RecordIndices_={})
FunctionRecordIterator ()
bool operator== (const FunctionRecordIterator &RHS) const
const FunctionRecord & operator* () const
FunctionRecordIterator & operator++ ()
Public Member Functions inherited from llvm::iterator_facade_base< FunctionRecordIterator, std::forward_iterator_tag, FunctionRecord >
FunctionRecordIterator operator+ (std::ptrdiff_t n) const
FunctionRecordIterator operator- (std::ptrdiff_t n) const
FunctionRecordIterator & operator++ ()
FunctionRecordIterator & operator-- ()
bool operator!= (const FunctionRecordIterator &RHS) const
bool operator> (const FunctionRecordIterator &RHS) const
bool operator<= (const FunctionRecordIterator &RHS) const
bool operator>= (const FunctionRecordIterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< FunctionRecordIterator, std::forward_iterator_tag, FunctionRecord >
enum
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Iterator over Functions, optionally filtered to a single file.
When filtering to a single file, the iterator requires a list of potential indices where to find the desired records to avoid quadratic behavior when repeatedly iterating over functions from different files.
Definition at line 765 of file CoverageMapping.h.
Constructor & Destructor Documentation
FunctionRecordIterator() [1/2]
llvm::coverage::FunctionRecordIterator::FunctionRecordIterator (ArrayRef< FunctionRecord > Records_, StringRef Filename = "", ArrayRef< unsigned > RecordIndices_ = {}) inline
Definition at line 778 of file CoverageMapping.h.
Referenced by operator++(), and operator==().
FunctionRecordIterator() [2/2]
llvm::coverage::FunctionRecordIterator::FunctionRecordIterator () inline
Definition at line 793 of file CoverageMapping.h.
References llvm::begin().
Member Function Documentation
operator*()
const FunctionRecord & llvm::coverage::FunctionRecordIterator::operator* () const inline
Definition at line 799 of file CoverageMapping.h.
operator++()
FunctionRecordIterator & llvm::coverage::FunctionRecordIterator::operator++ () inline
Definition at line 801 of file CoverageMapping.h.
References FunctionRecordIterator().
operator==()
bool llvm::coverage::FunctionRecordIterator::operator== (const FunctionRecordIterator & RHS) const inline
Definition at line 795 of file CoverageMapping.h.
References FunctionRecordIterator(), and RHS.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMapping.h
lib/ProfileData/Coverage/CoverageMapping.cpp