LLVM: llvm::ir2vec::VocabStorage Class Reference
llvm::ir2vec::VocabStorage Class Reference
Generic storage class for section-based vocabularies.
#include "llvm/Analysis/IR2Vec.h"
Classes
class const_iterator
Iterator support for section-based access.
Public Types
using VocabMap = std::map<std::string, Embedding>
Public Member Functions
VocabStorage ()=default
Default constructor creates empty storage (invalid state).
LLVM_ABI VocabStorage (std::vector< std::vector< Embedding > > &&SectionData)
Create a VocabStorage with pre-organized section data.
VocabStorage (VocabStorage &&)=default
VocabStorage & operator= (VocabStorage &&)=default
VocabStorage (const VocabStorage &)=delete
VocabStorage & operator= (const VocabStorage &)=delete
size_t size () const
Get total number of entries across all sections.
unsigned getNumSections () const
Get number of sections.
const std::vector< Embedding > & operator[] (unsigned SectionId) const
Section-based access: Storage[sectionId][localIndex].
unsigned getDimension () const
Get vocabulary dimension.
bool isValid () const
Check if vocabulary is valid (has data).
const_iterator begin () const
const_iterator end () const
Static Public Member Functions
static Error parseVocabSection (StringRef Key, const json::Value &ParsedVocabValue, VocabMap &TargetVocab, unsigned &Dim)
Parse a vocabulary section from JSON and populate the target vocabulary map.
Detailed Description
Generic storage class for section-based vocabularies.
VocabStorage provides a generic foundation for storing and accessing embeddings organized into sections.
Definition at line 151 of file IR2Vec.h.
Member Typedef Documentation
VocabMap
using llvm::ir2vec::VocabStorage::VocabMap = std::map<std::string, Embedding>
Definition at line 217 of file IR2Vec.h.
Constructor & Destructor Documentation
VocabStorage() [1/4]
llvm::ir2vec::VocabStorage::VocabStorage () default
Default constructor creates empty storage (invalid state).
References LLVM_ABI.
Referenced by llvm::ir2vec::VocabStorage::const_iterator::const_iterator(), llvm::ir2vec::Vocabulary::createDummyVocabForTest(), operator=(), operator=(), VocabStorage(), and VocabStorage().
VocabStorage() [2/4]
VocabStorage::VocabStorage (std::vector< std::vector< Embedding > > && SectionData)
Create a VocabStorage with pre-organized section data.
Definition at line 252 of file IR2Vec.cpp.
References assert(), llvm::move(), and Size.
VocabStorage() [3/4]
llvm::ir2vec::VocabStorage::VocabStorage (VocabStorage &&) default
References VocabStorage().
VocabStorage() [4/4]
llvm::ir2vec::VocabStorage::VocabStorage (const VocabStorage &) delete
References VocabStorage().
Member Function Documentation
begin()
const_iterator llvm::ir2vec::VocabStorage::begin () const inline
Definition at line 212 of file IR2Vec.h.
end()
const_iterator llvm::ir2vec::VocabStorage::end () const inline
Definition at line 213 of file IR2Vec.h.
References getNumSections().
getDimension()
unsigned llvm::ir2vec::VocabStorage::getDimension () const inline
Get vocabulary dimension.
Definition at line 190 of file IR2Vec.h.
Referenced by llvm::mir2vec::MIRVocabulary::create().
getNumSections()
unsigned llvm::ir2vec::VocabStorage::getNumSections () const inline
Get number of sections.
Definition at line 179 of file IR2Vec.h.
Referenced by end(), and llvm::ir2vec::VocabStorage::const_iterator::operator++().
isValid()
bool llvm::ir2vec::VocabStorage::isValid () const inline
Check if vocabulary is valid (has data).
Definition at line 193 of file IR2Vec.h.
Referenced by llvm::mir2vec::MIRVocabulary::create().
operator=() [1/2]
VocabStorage & llvm::ir2vec::VocabStorage::operator= (const VocabStorage &) delete
References VocabStorage().
operator=() [2/2]
VocabStorage & llvm::ir2vec::VocabStorage::operator= (VocabStorage &&) default
References VocabStorage().
operator[]()
const std::vector< Embedding > & llvm::ir2vec::VocabStorage::operator[] (unsigned SectionId) const inline
Section-based access: Storage[sectionId][localIndex].
Definition at line 184 of file IR2Vec.h.
References assert().
parseVocabSection()
Error VocabStorage::parseVocabSection (StringRef Key, const json::Value & ParsedVocabValue, VocabMap & TargetVocab, unsigned & Dim) static
Parse a vocabulary section from JSON and populate the target vocabulary map.
Definition at line 316 of file IR2Vec.cpp.
References llvm::createStringError(), llvm::json::fromJSON(), llvm::json::Object::get(), llvm::json::Value::getAsObject(), llvm::illegal_byte_sequence, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::invalid_argument, and llvm::Error::success().
size()
size_t llvm::ir2vec::VocabStorage::size () const inline
Get total number of entries across all sections.
Definition at line 176 of file IR2Vec.h.
Referenced by llvm::ir2vec::VocabStorage::const_iterator::operator*().
The documentation for this class was generated from the following files:
include/llvm/Analysis/IR2Vec.h
lib/Analysis/IR2Vec.cpp