LLVM: XtensaAsmParser Class Reference
XtensaAsmParser Class Reference
Public Types
enum XtensaMatchResultTy { Match_Dummy = FIRST_TARGET_MATCH_RESULT_TY }
Public Types inherited from llvm::MCTargetAsmParser
enum MatchResultTy {
Match_InvalidOperand , Match_InvalidTiedOperand , Match_MissingFeature , Match_MnemonicFail ,
Match_Success , Match_NearMisses , FIRST_TARGET_MATCH_RESULT_TY
}
Public Member Functions
XtensaAsmParser (const MCSubtargetInfo &STI, MCAsmParser &Parser, const MCInstrInfo &MII, const MCTargetOptions &Options)
bool hasWindowed () const
Public Member Functions inherited from llvm::MCTargetAsmParser
MCTargetAsmParser (const MCTargetAsmParser &)=delete
MCTargetAsmParser & operator= (const MCTargetAsmParser &)=delete
~MCTargetAsmParser () override
const MCSubtargetInfo & getSTI () const
const FeatureBitset & getAvailableFeatures () const
void setAvailableFeatures (const FeatureBitset &Value)
bool isParsingMSInlineAsm ()
void setParsingMSInlineAsm (bool Value)
MCTargetOptions getTargetOptions () const
void setSemaCallback (MCAsmParserSemaCallback *Callback)
virtual bool parsePrimaryExpr (const MCExpr *&Res, SMLoc &EndLoc)
virtual bool parseDataExpr (const MCExpr *&Res)
virtual bool parseInstruction (ParseInstructionInfo &Info, StringRef Name, AsmToken Token, OperandVector &Operands)
virtual bool ParseDirective (AsmToken DirectiveID)
ParseDirective - Parse a target specific assembler directive This method is deprecated, use 'parseDirective' instead.
virtual bool omitRegisterFromClobberLists (MCRegister Reg)
Allows targets to let registers opt out of clobber lists.
virtual unsigned checkEarlyTargetMatchPredicate (MCInst &Inst, const OperandVector &Operands)
Validate the instruction match against any complex target predicates before rendering any operands to it.
virtual unsigned checkTargetMatchPredicate (MCInst &Inst)
checkTargetMatchPredicate - Validate the instruction match against any complex target predicates not expressible via match classes.
virtual void convertToMapAndConstraints (unsigned Kind, const OperandVector &Operands)=0
virtual bool areEqualRegs (const MCParsedAsmOperand &Op1, const MCParsedAsmOperand &Op2) const
Returns whether two operands are registers and are equal.
virtual bool equalIsAsmAssignment ()
virtual bool isLabel (AsmToken &Token)
virtual bool tokenIsStartOfStatement (AsmToken::TokenKind Token)
virtual const MCExpr * applySpecifier (const MCExpr *E, uint32_t, MCContext &Ctx)
virtual void doBeforeLabelEmit (MCSymbol *Symbol, SMLoc IDLoc)
virtual void onLabelParsed (MCSymbol *Symbol)
virtual void flushPendingInstructions (MCStreamer &Out)
Ensure that all previously parsed instructions have been emitted to the output streamer, if the target does not emit them immediately.
virtual void onBeginOfFile ()
virtual void onEndOfFile ()
Public Member Functions inherited from llvm::MCAsmParserExtension
MCAsmParserExtension (const MCAsmParserExtension &)=delete
MCAsmParserExtension & operator= (const MCAsmParserExtension &)=delete
virtual ~MCAsmParserExtension ()
virtual void Initialize (MCAsmParser &Parser)
Initialize the extension for parsing using the given Parser.
MCContext & getContext ()
AsmLexer & getLexer ()
const AsmLexer & getLexer () const
MCAsmParser & getParser ()
const MCAsmParser & getParser () const
SourceMgr & getSourceManager ()
MCStreamer & getStreamer ()
bool Warning (SMLoc L, const Twine &Msg)
bool Error (SMLoc L, const Twine &Msg, SMRange Range=SMRange())
void Note (SMLoc L, const Twine &Msg)
bool TokError (const Twine &Msg)
const AsmToken & Lex ()
const AsmToken & getTok ()
bool parseToken (AsmToken::TokenKind T, const Twine &Msg="unexpected token")
bool parseEOL ()
bool parseMany (function_ref< bool()> parseOne, bool hasComma=true)
bool parseOptionalToken (AsmToken::TokenKind T)
bool parseDirectiveCGProfile (StringRef, SMLoc)
parseDirectiveCGProfile ::= .cg_profile identifier, identifier, <number>
bool maybeParseUniqueID (int64_t &UniqueID)
bool check (bool P, const Twine &Msg)
bool check (bool P, SMLoc Loc, const Twine &Msg)
bool addErrorSuffix (const Twine &Suffix)
bool HasBracketExpressions () const
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetAsmParser
MCTargetAsmParser (MCTargetOptions const &, const MCSubtargetInfo &STI, const MCInstrInfo &MII)
MCSubtargetInfo & copySTI ()
Create a copy of STI and return a non-const reference to it.
Protected Member Functions inherited from llvm::MCAsmParserExtension
MCAsmParserExtension ()
Static Protected Member Functions inherited from llvm::MCAsmParserExtension
template<typename T, bool(T::*)(StringRef, SMLoc) Handler>
static bool HandleDirective (MCAsmParserExtension *Target, StringRef Directive, SMLoc DirectiveLoc)
Protected Attributes inherited from llvm::MCTargetAsmParser
FeatureBitset AvailableFeatures
AvailableFeatures - The current set of available features.
bool ParsingMSInlineAsm = false
ParsingMSInlineAsm - Are we parsing ms-style inline assembly?
MCAsmParserSemaCallback * SemaCallback = nullptr
SemaCallback - The Sema callback implementation.
MCTargetOptions MCOptions
Set of options which affects instrumentation of inline assembly.
const MCSubtargetInfo * STI
Current STI.
const MCInstrInfo & MII
Protected Attributes inherited from llvm::MCAsmParserExtension
bool BracketExpressionsSupported = false
Detailed Description
Definition at line 37 of file XtensaAsmParser.cpp.
Member Enumeration Documentation
XtensaMatchResultTy
enum XtensaAsmParser::XtensaMatchResultTy
Enumerator
Match_Dummy
Definition at line 87 of file XtensaAsmParser.cpp.
Constructor & Destructor Documentation
XtensaAsmParser()
XtensaAsmParser::XtensaAsmParser (const MCSubtargetInfo & STI, MCAsmParser & Parser, const MCInstrInfo & MII, const MCTargetOptions & Options) inline
Definition at line 94 of file XtensaAsmParser.cpp.
References llvm::MCAsmParserExtension::getContext(), llvm::MCTargetAsmParser::MCTargetAsmParser(), llvm::MCTargetAsmParser::MII, Options, llvm::MCTargetAsmParser::setAvailableFeatures(), and llvm::MCTargetAsmParser::STI.
Member Function Documentation
hasWindowed()
bool XtensaAsmParser::hasWindowed () const inline
Definition at line 101 of file XtensaAsmParser.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), and llvm::MCTargetAsmParser::getSTI().
The documentation for this class was generated from the following file:
lib/Target/Xtensa/AsmParser/XtensaAsmParser.cpp