LLVM: llvm::X86InstPrinterCommon Class Reference
llvm::X86InstPrinterCommon Class Reference abstract
#include "Target/X86/MCTargetDesc/X86InstPrinterCommon.h"
Public Member Functions
virtual void printExprOperand (raw_ostream &OS, const MCExpr &E)
virtual void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)=0
void printCondCode (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printCondFlags (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printSSEAVXCC (const MCInst *MI, unsigned Op, raw_ostream &OS)
void printVPCOMMnemonic (const MCInst *MI, raw_ostream &OS)
void printVPCMPMnemonic (const MCInst *MI, raw_ostream &OS)
void printCMPMnemonic (const MCInst *MI, bool IsVCmp, raw_ostream &OS)
void printRoundingControl (const MCInst *MI, unsigned Op, raw_ostream &O)
void printPCRelImm (const MCInst *MI, uint64_t Address, unsigned OpNo, raw_ostream &O)
value (e.g.
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
virtual std::pair< const char *, uint64_t > getMnemonic (const MCInst &MI) const =0
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
virtual void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS)=0
Print the specified MCInst to the specified raw_ostream.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, MCRegister Reg)
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
bool getUseColor () const
void setUseColor (bool Value)
WithMarkup markup (raw_ostream &OS, Markup M)
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Protected Member Functions
void printInstFlags (const MCInst *MI, raw_ostream &O, const MCSubtargetInfo &STI)
void printOptionalSegReg (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printVKPair (const MCInst *MI, unsigned OpNo, raw_ostream &OS)
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Additional Inherited Members
Public Types inherited from llvm::MCInstPrinter
enum class Markup { Immediate , Register , Target , Memory }
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool UseColor = false
True if we are printing colored assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
SmallVector< raw_ostream::Colors, 4 > ColorStack {raw_ostream::Colors::RESET}
Detailed Description
Definition at line 22 of file X86InstPrinterCommon.h.
Member Function Documentation
MCInstPrinter()
llvm::MCInstPrinter::MCInstPrinter (const MCAsmInfo & mai, const MCInstrInfo & mii, const MCRegisterInfo & mri) inline
Definition at line 90 of file MCInstPrinter.h.
printCMPMnemonic()
void X86InstPrinterCommon::printCMPMnemonic (const MCInst * MI, bool IsVCmp, raw_ostream & OS)
Definition at line 240 of file X86InstPrinterCommon.cpp.
References llvm_unreachable, MI, and printSSEAVXCC().
Referenced by llvm::X86ATTInstPrinter::printVecCompareInstr(), and llvm::X86IntelInstPrinter::printVecCompareInstr().
printCondCode()
void X86InstPrinterCommon::printCondCode (const MCInst * MI, unsigned Op, raw_ostream & OS)
Definition at line 33 of file X86InstPrinterCommon.cpp.
References llvm_unreachable, MI, and Opc.
printCondFlags()
void X86InstPrinterCommon::printCondFlags (const MCInst * MI, unsigned Op, raw_ostream & OS)
Definition at line 62 of file X86InstPrinterCommon.cpp.
References assert(), MI, and llvm::StringRef::rtrim().
printExprOperand()
void X86InstPrinterCommon::printExprOperand (raw_ostream & OS, const MCExpr & E) virtual
Reimplemented in llvm::X86ATTInstPrinter.
Definition at line 29 of file X86InstPrinterCommon.cpp.
References llvm::MCInstPrinter::MAI.
Referenced by printPCRelImm().
printInstFlags()
void X86InstPrinterCommon::printInstFlags (const MCInst * MI, raw_ostream & O, const MCSubtargetInfo & STI) protected
Definition at line 394 of file X86InstPrinterCommon.cpp.
References llvm::X86II::EVEX_NF, llvm::X86II::ExplicitEVEXPrefix, llvm::X86II::ExplicitOpPrefixMask, llvm::X86II::ExplicitVEXPrefix, llvm::X86II::getMemoryOperandNo(), llvm::X86II::getOperandBias(), llvm::MCSubtargetInfo::hasFeature(), llvm::X86::IP_HAS_AD_SIZE, llvm::X86::IP_HAS_LOCK, llvm::X86::IP_HAS_NOTRACK, llvm::X86::IP_HAS_REPEAT, llvm::X86::IP_HAS_REPEAT_NE, llvm::X86::IP_USE_DISP32, llvm::X86::IP_USE_DISP8, llvm::X86::IP_USE_EVEX, llvm::X86::IP_USE_VEX, llvm::X86::IP_USE_VEX2, llvm::X86::IP_USE_VEX3, llvm::X86II::LOCK, MI, llvm::MCInstPrinter::MII, llvm::X86_MC::needsAddressSizeOverride(), and llvm::X86II::NOTRACK.
Referenced by llvm::X86ATTInstPrinter::printInst(), and llvm::X86IntelInstPrinter::printInst().
printOperand()
virtual void llvm::X86InstPrinterCommon::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) pure virtual
Implemented in llvm::X86ATTInstPrinter, and llvm::X86IntelInstPrinter.
References MI.
Referenced by printOptionalSegReg().
printOptionalSegReg()
void X86InstPrinterCommon::printOptionalSegReg (const MCInst * MI, unsigned OpNo, raw_ostream & O) protected
Definition at line 386 of file X86InstPrinterCommon.cpp.
References MI, and printOperand().
Referenced by llvm::X86ATTInstPrinter::printMemOffset(), llvm::X86IntelInstPrinter::printMemOffset(), llvm::X86ATTInstPrinter::printMemReference(), llvm::X86IntelInstPrinter::printMemReference(), llvm::X86ATTInstPrinter::printSrcIdx(), and llvm::X86IntelInstPrinter::printSrcIdx().
printPCRelImm()
void X86InstPrinterCommon::printPCRelImm (const MCInst * MI, uint64_t Address, unsigned OpNo, raw_ostream & O)
value (e.g.
for jumps and calls). In Intel-style these print slightly differently than normal immediates. For example, a $ is not emitted.
Address The address of the next instruction.
See also
MCInstPrinter::printInst
Definition at line 356 of file X86InstPrinterCommon.cpp.
References assert(), llvm::dyn_cast(), llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::formatImm(), llvm::MCInstPrinter::Immediate, llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::markup(), MI, llvm::MCInstPrinter::PrintBranchImmAsAddress, printExprOperand(), llvm::MCInstPrinter::SymbolizeOperands, and llvm::MCInstPrinter::Target.
Referenced by llvm::X86ATTInstPrinter::printInst().
printRoundingControl()
void X86InstPrinterCommon::printRoundingControl (const MCInst * MI, unsigned Op, raw_ostream & O)
Definition at line 330 of file X86InstPrinterCommon.cpp.
References llvm_unreachable, MI, llvm::X86::TO_NEAREST_INT, llvm::X86::TO_NEG_INF, llvm::X86::TO_POS_INF, and llvm::X86::TO_ZERO.
printSSEAVXCC()
void X86InstPrinterCommon::printSSEAVXCC (const MCInst * MI, unsigned Op, raw_ostream & OS)
Definition at line 83 of file X86InstPrinterCommon.cpp.
References llvm_unreachable, and MI.
Referenced by printCMPMnemonic(), and printVPCMPMnemonic().
printVKPair()
void X86InstPrinterCommon::printVKPair (const MCInst * MI, unsigned OpNo, raw_ostream & OS) protected
Definition at line 446 of file X86InstPrinterCommon.cpp.
References llvm_unreachable, MI, and llvm::MCInstPrinter::printRegName().
printVPCMPMnemonic()
void X86InstPrinterCommon::printVPCMPMnemonic (const MCInst * MI, raw_ostream & OS)
Definition at line 153 of file X86InstPrinterCommon.cpp.
References llvm_unreachable, MI, and printSSEAVXCC().
Referenced by llvm::X86ATTInstPrinter::printVecCompareInstr(), and llvm::X86IntelInstPrinter::printVecCompareInstr().
printVPCOMMnemonic()
void X86InstPrinterCommon::printVPCOMMnemonic (const MCInst * MI, raw_ostream & OS)
Definition at line 123 of file X86InstPrinterCommon.cpp.
References llvm_unreachable, and MI.
Referenced by llvm::X86ATTInstPrinter::printVecCompareInstr(), and llvm::X86IntelInstPrinter::printVecCompareInstr().
The documentation for this class was generated from the following files:
lib/Target/X86/MCTargetDesc/X86InstPrinterCommon.h
lib/Target/X86/MCTargetDesc/X86InstPrinterCommon.cpp