LLVM: llvm::CFIInstBuilder Class Reference
llvm::CFIInstBuilder Class Reference
Helper class for creating CFI instructions and inserting them into MIR.
#include "llvm/CodeGen/CFIInstBuilder.h"
Public Member Functions
CFIInstBuilder (MachineBasicBlock &MBB, MachineBasicBlock::iterator InsertPt, MachineInstr::MIFlag MIFlag, bool IsEH=true)
CFIInstBuilder (MachineBasicBlock *MBB, MachineInstr::MIFlag MIFlag, bool IsEH=true)
void setInsertPoint (MachineBasicBlock::iterator IP)
void insertCFIInst (const MCCFIInstruction &CFIInst) const
void buildDefCFA (MCRegister Reg, int64_t Offset) const
void buildDefCFARegister (MCRegister Reg) const
void buildDefCFAOffset (int64_t Offset, MCSymbol *Label=nullptr) const
void buildAdjustCFAOffset (int64_t Adjustment) const
void buildOffset (MCRegister Reg, int64_t Offset) const
void buildNegateRAState () const
void buildNegateRAStateWithPC () const
void buildRegister (MCRegister Reg1, MCRegister Reg2) const
void buildWindowSave () const
void buildRestore (MCRegister Reg) const
void buildUndefined (MCRegister Reg) const
void buildSameValue (MCRegister Reg) const
void buildEscape (StringRef Bytes, StringRef Comment="") const
Detailed Description
Helper class for creating CFI instructions and inserting them into MIR.
Definition at line 20 of file CFIInstBuilder.h.
Constructor & Destructor Documentation
CFIInstBuilder() [1/2]
llvm::CFIInstBuilder::CFIInstBuilder (MachineBasicBlock & MBB, MachineBasicBlock::iterator InsertPt, MachineInstr::MIFlag MIFlag, bool IsEH = true) inline
Definition at line 39 of file CFIInstBuilder.h.
References llvm::get(), getParent(), and setInsertPoint().
Referenced by CFIInstBuilder().
CFIInstBuilder() [2/2]
llvm::CFIInstBuilder::CFIInstBuilder (MachineBasicBlock * MBB, MachineInstr::MIFlag MIFlag, bool IsEH = true) inline
Definition at line 48 of file CFIInstBuilder.h.
References CFIInstBuilder(), and llvm::end().
Member Function Documentation
buildAdjustCFAOffset()
void llvm::CFIInstBuilder::buildAdjustCFAOffset (int64_t Adjustment) const inline
Definition at line 74 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createAdjustCfaOffset(), and insertCFIInst().
Referenced by llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr().
buildDefCFA()
void llvm::CFIInstBuilder::buildDefCFA (MCRegister Reg, int64_t Offset) const inline
Definition at line 60 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::cfiDefCfa(), insertCFIInst(), llvm::Offset, and Reg.
Referenced by llvm::RISCVFrameLowering::allocateStack(), llvm::AArch64EpilogueEmitter::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
buildDefCFAOffset()
void llvm::CFIInstBuilder::buildDefCFAOffset (int64_t Offset, MCSymbol * Label = nullptr) const inline
Definition at line 70 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::cfiDefCfaOffset(), insertCFIInst(), and llvm::Offset.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::RISCVFrameLowering::allocateStack(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::AArch64PrologueEpilogueCommon::convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
buildDefCFARegister()
void llvm::CFIInstBuilder::buildDefCFARegister (MCRegister Reg) const inline
Definition at line 65 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createDefCfaRegister(), insertCFIInst(), and Reg.
Referenced by llvm::RISCVFrameLowering::allocateStack(), llvm::ARMFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
buildEscape()
void llvm::CFIInstBuilder::buildEscape (StringRef Bytes, StringRef Comment = "") const inline
Definition at line 116 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createEscape(), and insertCFIInst().
Referenced by emitSCSPrologue().
buildNegateRAState()
void llvm::CFIInstBuilder::buildNegateRAState () const inline
Definition at line 83 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createNegateRAState(), and insertCFIInst().
buildNegateRAStateWithPC()
void llvm::CFIInstBuilder::buildNegateRAStateWithPC () const inline
Definition at line 87 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createNegateRAStateWithPC(), and insertCFIInst().
buildOffset()
void llvm::CFIInstBuilder::buildOffset (MCRegister Reg, int64_t Offset) const inline
Definition at line 78 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createOffset(), insertCFIInst(), llvm::Offset, and Reg.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::ARMFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
buildRegister()
void llvm::CFIInstBuilder::buildRegister (MCRegister Reg1, MCRegister Reg2) const inline
Definition at line 91 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createRegister(), and insertCFIInst().
Referenced by llvm::SparcFrameLowering::emitPrologue(), and llvm::ARMBaseInstrInfo::insertOutlinedCall().
buildRestore()
void llvm::CFIInstBuilder::buildRestore (MCRegister Reg) const inline
Definition at line 101 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createRestore(), insertCFIInst(), and Reg.
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), emitSCSEpilogue(), and llvm::ARMBaseInstrInfo::insertOutlinedCall().
buildSameValue()
void llvm::CFIInstBuilder::buildSameValue (MCRegister Reg) const inline
Definition at line 111 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createSameValue(), insertCFIInst(), and Reg.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks().
buildUndefined()
void llvm::CFIInstBuilder::buildUndefined (MCRegister Reg) const inline
Definition at line 106 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createUndefined(), insertCFIInst(), and Reg.
buildWindowSave()
void llvm::CFIInstBuilder::buildWindowSave () const inline
Definition at line 97 of file CFIInstBuilder.h.
References llvm::MCCFIInstruction::createWindowSave(), and insertCFIInst().
Referenced by llvm::SparcFrameLowering::emitPrologue().
insertCFIInst()
void llvm::CFIInstBuilder::insertCFIInst (const MCCFIInstruction & CFIInst) const inline
Definition at line 54 of file CFIInstBuilder.h.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::BuildMI(), and llvm::MachineInstrBuilder::setMIFlag().
Referenced by buildAdjustCFAOffset(), buildDefCFA(), buildDefCFAOffset(), buildDefCFARegister(), buildEscape(), buildNegateRAState(), buildNegateRAStateWithPC(), buildOffset(), buildRegister(), buildRestore(), buildSameValue(), buildUndefined(), buildWindowSave(), llvm::AArch64PrologueEmitter::emitPrologue(), and llvm::RISCVFrameLowering::emitPrologue().
setInsertPoint()
void llvm::CFIInstBuilder::setInsertPoint (MachineBasicBlock::iterator IP) inline
Definition at line 52 of file CFIInstBuilder.h.
Referenced by CFIInstBuilder(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), and llvm::Thumb1FrameLowering::emitPrologue().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/CFIInstBuilder.h