LLVM: llvm::ELFExtendedAttrParser Class Reference
llvm::ELFExtendedAttrParser Class Reference
#include "llvm/Support/ELFAttrParserExtended.h"
Public Member Functions
~ELFExtendedAttrParser () override
Error parse (ArrayRef< uint8_t > Section, llvm::endianness Endian) override
std::optional< unsigned > getAttributeValue (unsigned Tag) const override
std::optional< unsigned > getAttributeValue (StringRef BuildAttrSubsectionName, unsigned Tag) const override
std::optional< StringRef > getAttributeString (unsigned Tag) const override
std::optional< StringRef > getAttributeString (StringRef BuildAttrSubsectionName, unsigned Tag) const override
ELFExtendedAttrParser (ScopedPrinter *Sw, const std::vector< SubsectionAndTagToTagName > TagsNamesMap)
ELFExtendedAttrParser (const std::vector< SubsectionAndTagToTagName > TagsNamesMap)
Public Member Functions inherited from llvm::ELFAttributeParser
virtual ~ELFAttributeParser ()=default
Protected Member Functions
StringRef getTagName (const StringRef &BuildAttrSubsectionName, const unsigned Tag)
Protected Attributes
ScopedPrinter * Sw
DataExtractor De {ArrayRef<uint8_t>{}, true, 0}
DataExtractor::Cursor Cursor {0}
SmallVector< BuildAttributeSubSection, 8 > SubSectionVec
const std::vector< SubsectionAndTagToTagName > TagsNamesMap
Detailed Description
Definition at line 25 of file ELFAttrParserExtended.h.
Constructor & Destructor Documentation
~ELFExtendedAttrParser()
llvm::ELFExtendedAttrParser::~ELFExtendedAttrParser () inline override
Definition at line 39 of file ELFAttrParserExtended.h.
References Cursor.
ELFExtendedAttrParser() [1/2]
llvm::ELFExtendedAttrParser::ELFExtendedAttrParser (ScopedPrinter * Sw, const std::vector< SubsectionAndTagToTagName > TagsNamesMap) inline
Definition at line 49 of file ELFAttrParserExtended.h.
References Sw, and TagsNamesMap.
Referenced by llvm::AArch64AttributeParser::AArch64AttributeParser(), and llvm::AArch64AttributeParser::AArch64AttributeParser().
ELFExtendedAttrParser() [2/2]
llvm::ELFExtendedAttrParser::ELFExtendedAttrParser (const std::vector< SubsectionAndTagToTagName > TagsNamesMap) inline
Definition at line 53 of file ELFAttrParserExtended.h.
References nullptr, Sw, and TagsNamesMap.
Member Function Documentation
getAttributeString() [1/2]
std::optional< StringRef > ELFExtendedAttrParser::getAttributeString (StringRef BuildAttrSubsectionName, unsigned Tag) const override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 53 of file ELFAttrParserExtended.cpp.
References SubSectionVec.
getAttributeString() [2/2]
std::optional< StringRef > ELFExtendedAttrParser::getAttributeString (unsigned Tag) const override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 45 of file ELFAttrParserExtended.cpp.
References assert().
getAttributeValue() [1/2]
std::optional< unsigned > ELFExtendedAttrParser::getAttributeValue (StringRef BuildAttrSubsectionName, unsigned Tag) const override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 32 of file ELFAttrParserExtended.cpp.
References SubSectionVec.
getAttributeValue() [2/2]
std::optional< unsigned > ELFExtendedAttrParser::getAttributeValue (unsigned Tag) const override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 24 of file ELFAttrParserExtended.cpp.
References assert().
getTagName()
StringRef ELFExtendedAttrParser::getTagName (const StringRef & BuildAttrSubsectionName, const unsigned Tag) protected
Definition at line 66 of file ELFAttrParserExtended.cpp.
References TagsNamesMap.
Referenced by parse().
parse()
Error ELFExtendedAttrParser::parse (ArrayRef< uint8_t > Section, llvm::endianness Endian) override virtual
Reimplemented from llvm::ELFAttributeParser.
Definition at line 76 of file ELFAttrParserExtended.cpp.
References llvm::consumeError(), llvm::BuildAttributeSubSection::Content, llvm::createStringError(), Cursor, De, llvm::ELFAttrs::Format_Version, getTagName(), llvm::invalid_argument, llvm::BuildAttributeSubSection::IsOptional, llvm::little, llvm::BuildAttributeSubSection::Name, llvm::BuildAttributeSubSection::ParameterType, llvm::ELFAttrs::Section, llvm::StringRef::size(), SubSectionVec, and Sw.
Member Data Documentation
Cursor
DataExtractor::Cursor llvm::ELFExtendedAttrParser::Cursor {0} protected
Definition at line 29 of file ELFAttrParserExtended.h.
Referenced by parse(), and ~ELFExtendedAttrParser().
De
DataExtractor llvm::ELFExtendedAttrParser::De {ArrayRef<uint8_t>{}, true, 0} protected
Definition at line 28 of file ELFAttrParserExtended.h.
Referenced by parse().
SubSectionVec
SmallVector<BuildAttributeSubSection, 8> llvm::ELFExtendedAttrParser::SubSectionVec protected
Definition at line 32 of file ELFAttrParserExtended.h.
Referenced by getAttributeString(), getAttributeValue(), and parse().
Sw
ScopedPrinter* llvm::ELFExtendedAttrParser::Sw protected
Definition at line 27 of file ELFAttrParserExtended.h.
Referenced by llvm::AArch64AttributeParser::AArch64AttributeParser(), ELFExtendedAttrParser(), ELFExtendedAttrParser(), and parse().
TagsNamesMap
const std::vector<SubsectionAndTagToTagName> llvm::ELFExtendedAttrParser::TagsNamesMap protected
Definition at line 34 of file ELFAttrParserExtended.h.
Referenced by ELFExtendedAttrParser(), ELFExtendedAttrParser(), and getTagName().
The documentation for this class was generated from the following files:
include/llvm/Support/ELFAttrParserExtended.h
lib/Support/ELFAttrParserExtended.cpp