LLVM: llvm::AMDGPU::VOPD::ComponentProps Class Reference
llvm::AMDGPU::VOPD::ComponentProps Class Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Member Functions
ComponentProps ()=default
ComponentProps (const MCInstrDesc &OpDesc, bool VOP3Layout=false)
unsigned getCompSrcOperandsNum () const
unsigned getCompParsedSrcOperandsNum () const
bool hasMandatoryLiteral () const
unsigned getMandatoryLiteralCompOperandIndex () const
bool hasRegSrcOperand (unsigned CompSrcIdx) const
bool hasSrc2Acc () const
unsigned getCompVOPD3ModsNum () const
unsigned getOpcode () const
unsigned isVOP3 () const
int getBitOp3OperandIdx () const
Detailed Description
Definition at line 696 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
ComponentProps() [1/2]
llvm::AMDGPU::VOPD::ComponentProps::ComponentProps () default
Referenced by llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo(), and llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo().
ComponentProps() [2/2]
llvm::AMDGPU::VOPD::ComponentProps::ComponentProps (const MCInstrDesc & OpDesc, bool VOP3Layout = false)
Definition at line 844 of file AMDGPUBaseInfo.cpp.
References assert(), llvm::AMDGPU::VOPD::DST, llvm::AMDGPU::VOPD::DST_NUM, llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInstrDesc::getOpcode(), llvm::MCInstrDesc::getOperandConstraint(), llvm::AMDGPU::hasNamedOperand(), llvm::AMDGPU::isSISrcFPOperand(), llvm::AMDGPU::VOPD::MAX_SRC_NUM, llvm::AMDGPU::OPERAND_KIMM32, llvm::MCInstrDesc::operands(), llvm::AMDGPU::VOPD::SRC0, llvm::AMDGPU::VOPD::SRC1, llvm::AMDGPU::VOPD::SRC2, llvm::MCOI::TIED_TO, llvm::MCInstrDesc::TSFlags, and llvm::SIInstrFlags::VOP3.
Member Function Documentation
getBitOp3OperandIdx()
int llvm::AMDGPU::VOPD::ComponentProps::getBitOp3OperandIdx () const
Definition at line 890 of file AMDGPUBaseInfo.cpp.
Referenced by llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo(), and llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo().
getCompParsedSrcOperandsNum()
unsigned llvm::AMDGPU::VOPD::ComponentProps::getCompParsedSrcOperandsNum () const inline
Definition at line 713 of file AMDGPUBaseInfo.h.
Referenced by llvm::AMDGPU::VOPD::ComponentInfo::getIndexInParsedOperands().
getCompSrcOperandsNum()
unsigned llvm::AMDGPU::VOPD::ComponentProps::getCompSrcOperandsNum () const inline
Definition at line 710 of file AMDGPUBaseInfo.h.
getCompVOPD3ModsNum()
unsigned llvm::AMDGPU::VOPD::ComponentProps::getCompVOPD3ModsNum () const inline
Definition at line 738 of file AMDGPUBaseInfo.h.
Referenced by llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo(), and llvm::AMDGPU::VOPD::ComponentInfo::ComponentInfo().
getMandatoryLiteralCompOperandIndex()
unsigned llvm::AMDGPU::VOPD::ComponentProps::getMandatoryLiteralCompOperandIndex () const inline
Definition at line 722 of file AMDGPUBaseInfo.h.
References assert(), and hasMandatoryLiteral().
getOpcode()
unsigned llvm::AMDGPU::VOPD::ComponentProps::getOpcode () const inline
Definition at line 741 of file AMDGPUBaseInfo.h.
hasMandatoryLiteral()
bool llvm::AMDGPU::VOPD::ComponentProps::hasMandatoryLiteral () const inline
Definition at line 718 of file AMDGPUBaseInfo.h.
Referenced by getMandatoryLiteralCompOperandIndex().
hasRegSrcOperand()
bool llvm::AMDGPU::VOPD::ComponentProps::hasRegSrcOperand (unsigned CompSrcIdx) const inline
Definition at line 729 of file AMDGPUBaseInfo.h.
References assert(), and llvm::AMDGPU::VOPD::MAX_SRC_NUM.
hasSrc2Acc()
bool llvm::AMDGPU::VOPD::ComponentProps::hasSrc2Acc () const inline
Definition at line 735 of file AMDGPUBaseInfo.h.
isVOP3()
unsigned llvm::AMDGPU::VOPD::ComponentProps::isVOP3 () const inline
Definition at line 744 of file AMDGPUBaseInfo.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp