LLVM: llvm::pdb::TpiStream Class Reference
llvm::pdb::TpiStream Class Reference
#include "llvm/DebugInfo/PDB/Native/TpiStream.h"
Public Member Functions
LLVM_ABI TpiStream (PDBFile &File, std::unique_ptr< msf::MappedBlockStream > Stream)
LLVM_ABI ~TpiStream ()
LLVM_ABI Error reload ()
LLVM_ABI PdbRaw_TpiVer getTpiVersion () const
LLVM_ABI uint32_t TypeIndexBegin () const
LLVM_ABI uint32_t TypeIndexEnd () const
LLVM_ABI uint32_t getNumTypeRecords () const
LLVM_ABI uint16_t getTypeHashStreamIndex () const
LLVM_ABI uint16_t getTypeHashStreamAuxIndex () const
LLVM_ABI uint32_t getHashKeySize () const
LLVM_ABI uint32_t getNumHashBuckets () const
LLVM_ABI FixedStreamArray< support::ulittle32_t > getHashValues () const
LLVM_ABI FixedStreamArray< codeview::TypeIndexOffset > getTypeIndexOffsets () const
LLVM_ABI HashTable< support::ulittle32_t > & getHashAdjusters ()
LLVM_ABI codeview::CVTypeRange types (bool *HadError) const
const codeview::CVTypeArray & typeArray () const
codeview::LazyRandomTypeCollection & typeCollection ()
LLVM_ABI Expected< codeview::TypeIndex > findFullDeclForForwardRef (codeview::TypeIndex ForwardRefTI) const
LLVM_ABI std::vector< codeview::TypeIndex > findRecordsByName (StringRef Name) const
LLVM_ABI codeview::CVType getType (codeview::TypeIndex Index)
LLVM_ABI BinarySubstreamRef getTypeRecordsSubstream () const
LLVM_ABI Error commit ()
LLVM_ABI void buildHashMap ()
LLVM_ABI bool supportsTypeLookup () const
Friends
class TpiStreamBuilder
Detailed Description
Definition at line 35 of file TpiStream.h.
Constructor & Destructor Documentation
TpiStream()
TpiStream::TpiStream (PDBFile & File, std::unique_ptr< msf::MappedBlockStream > Stream)
Definition at line 35 of file TpiStream.cpp.
References llvm::move().
Referenced by findFullDeclForForwardRef(), and findRecordsByName().
~TpiStream()
TpiStream::~TpiStream () default
References LLVM_ABI.
Member Function Documentation
buildHashMap()
void TpiStream::buildHashMap ()
Definition at line 143 of file TpiStream.cpp.
References llvm::codeview::TypeIndex::toArrayIndex().
Referenced by findFullDeclForForwardRef(), and findRecordsByName().
commit()
Error TpiStream::commit ()
Definition at line 245 of file TpiStream.cpp.
References llvm::Error::success().
findFullDeclForForwardRef()
Expected< TypeIndex > TpiStream::findFullDeclForForwardRef (codeview::TypeIndex ForwardRefTI) const
Definition at line 179 of file TpiStream.cpp.
References buildHashMap(), F, llvm::codeview::TagRecord::getName(), llvm::codeview::TagRecord::getUniqueName(), llvm::pdb::hashTagRecord(), llvm::codeview::TagRecord::hasUniqueName(), llvm::codeview::isUdtForwardRef(), llvm::codeview::CVRecord< Kind >::kind(), supportsTypeLookup(), llvm::Expected< T >::takeError(), and TpiStream().
findRecordsByName()
std::vector< TypeIndex > TpiStream::findRecordsByName (StringRef Name) const
Definition at line 159 of file TpiStream.cpp.
References buildHashMap(), llvm::codeview::computeTypeName(), llvm::pdb::hashStringV1(), supportsTypeLookup(), and TpiStream().
getHashAdjusters()
HashTable< support::ulittle32_t > & TpiStream::getHashAdjusters ()
Definition at line 237 of file TpiStream.cpp.
getHashKeySize()
uint32_t TpiStream::getHashKeySize () const
Definition at line 141 of file TpiStream.cpp.
getHashValues()
FixedStreamArray< support::ulittle32_t > TpiStream::getHashValues () const
Definition at line 229 of file TpiStream.cpp.
getNumHashBuckets()
uint32_t TpiStream::getNumHashBuckets () const
Definition at line 140 of file TpiStream.cpp.
getNumTypeRecords()
uint32_t TpiStream::getNumTypeRecords () const
Definition at line 128 of file TpiStream.cpp.
References TypeIndexBegin(), and TypeIndexEnd().
Referenced by reload().
getTpiVersion()
PdbRaw_TpiVer TpiStream::getTpiVersion () const
Definition at line 119 of file TpiStream.cpp.
getType()
codeview::CVType TpiStream::getType (codeview::TypeIndex Index)
Definition at line 220 of file TpiStream.cpp.
References assert().
getTypeHashStreamAuxIndex()
uint16_t TpiStream::getTypeHashStreamAuxIndex () const
Definition at line 136 of file TpiStream.cpp.
getTypeHashStreamIndex()
uint16_t TpiStream::getTypeHashStreamIndex () const
Definition at line 132 of file TpiStream.cpp.
getTypeIndexOffsets()
FixedStreamArray< TypeIndexOffset > TpiStream::getTypeIndexOffsets () const
Definition at line 233 of file TpiStream.cpp.
Referenced by reload().
getTypeRecordsSubstream()
BinarySubstreamRef TpiStream::getTypeRecordsSubstream () const
Definition at line 225 of file TpiStream.cpp.
reload()
Error TpiStream::reload ()
Definition at line 40 of file TpiStream.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::consumeError(), llvm::pdb::corrupt_file, llvm::codeview::EC, getNumTypeRecords(), getTypeIndexOffsets(), llvm::pdb::kInvalidStreamIndex, llvm::make_error(), llvm::pdb::MaxTpiHashBuckets, llvm::pdb::MinTpiHashBuckets, llvm::pdb::PdbTpiV80, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readObject(), llvm::BinaryStreamReader::readSubstream(), llvm::BinaryStreamReader::setOffset(), and llvm::Error::success().
supportsTypeLookup()
bool TpiStream::supportsTypeLookup () const
Definition at line 176 of file TpiStream.cpp.
Referenced by findFullDeclForForwardRef(), and findRecordsByName().
typeArray()
const codeview::CVTypeArray & llvm::pdb::TpiStream::typeArray () const inline
Definition at line 60 of file TpiStream.h.
typeCollection()
codeview::LazyRandomTypeCollection & llvm::pdb::TpiStream::typeCollection () inline
Definition at line 62 of file TpiStream.h.
TypeIndexBegin()
uint32_t TpiStream::TypeIndexBegin () const
Definition at line 124 of file TpiStream.cpp.
Referenced by getNumTypeRecords().
TypeIndexEnd()
uint32_t TpiStream::TypeIndexEnd () const
Definition at line 126 of file TpiStream.cpp.
Referenced by getNumTypeRecords().
types()
CVTypeRange TpiStream::types (bool * HadError) const
Definition at line 241 of file TpiStream.cpp.
References llvm::make_range().
Friends And Related Symbol Documentation
TpiStreamBuilder
friend class TpiStreamBuilder friend
Definition at line 36 of file TpiStream.h.
References LLVM_ABI, and TpiStreamBuilder.
Referenced by TpiStreamBuilder.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/TpiStream.h
lib/DebugInfo/PDB/Native/TpiStream.cpp