LLVM: llvm::orc::DylibSubstitutor Class Reference
llvm::orc::DylibSubstitutor Class Reference
Performs placeholder substitution in dynamic library paths.
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h"
Public Member Functions
void configure (StringRef loaderPath)
std::string substitute (StringRef input) const
Detailed Description
Performs placeholder substitution in dynamic library paths.
Configures known placeholders (like @loader_path) and replaces them in input paths with their resolved values.
Definition at line 168 of file LibraryScanner.h.
Member Function Documentation
configure()
void llvm::orc::DylibSubstitutor::configure (StringRef loaderPath)
Definition at line 271 of file LibraryScanner.cpp.
References llvm::StringRef::empty(), llvm::sys::fs::getMainExecutable(), llvm::sys::fs::is_directory(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::sys::path::remove_filename(), and llvm::StringRef::str().
Referenced by llvm::orc::DylibResolver::configure(), and llvm::orc::DylibResolver::resolvelinkerFlag().
substitute()
std::string llvm::orc::DylibSubstitutor::substitute (StringRef input) const inline
Definition at line 172 of file LibraryScanner.h.
References llvm::StringRef::drop_front(), llvm::StringRef::starts_with_insensitive(), and llvm::StringRef::str().
Referenced by llvm::orc::SearchPathResolver::resolve(), and llvm::orc::DylibResolver::resolvelinkerFlag().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryScanner.cpp