LLVM: llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder Class Reference
llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder Class Reference
Build SuperNodes from (definition-set, dependence-set) pairs.
#include "llvm/ExecutionEngine/Orc/WaitingOnGraph.h"
Public Member Functions
void add (ContainerElementsMap Defs, ContainerElementsMap Deps)
std::vector< std::unique_ptr< SuperNode > > takeSuperNodes ()
Detailed Description
template<typename ContainerIdT, typename ElementIdT>
class llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder
Build SuperNodes from (definition-set, dependence-set) pairs.
Coalesces definition-sets with identical dependence-sets.
Definition at line 207 of file WaitingOnGraph.h.
Member Function Documentation
add()
template<typename ContainerIdT, typename ElementIdT> void llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder::add (ContainerElementsMap Defs, ContainerElementsMap Deps) inline
Definition at line 209 of file WaitingOnGraph.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, and ToRemove.
takeSuperNodes()
template<typename ContainerIdT, typename ElementIdT> std::vector< std::unique_ptr< SuperNode > > llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder::takeSuperNodes () inline
Definition at line 230 of file WaitingOnGraph.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/WaitingOnGraph.h