LLVM: llvm::GFConstant Class Reference
llvm::GFConstant Class Reference
An floating-point-like constant.
#include "llvm/CodeGen/GlobalISel/Utils.h"
Public Types
enum class GFConstantKind { Scalar , FixedVector , ScalableVector }
Public Member Functions
GFConstant (ArrayRef< APFloat > Values)
GFConstant (const APFloat &Value, GFConstantKind Kind)
GFConstantKind getKind () const
Returns the kind of of this constant, e.g, Scalar.
const_iterator begin () const
const_iterator end () const
size_t size () const
LLVM_ABI APFloat getScalarValue () const
Returns the value, if this constant is a scalar.
Static Public Member Functions
static LLVM_ABI std::optional< GFConstant > getConstant (Register Const, const MachineRegisterInfo &MRI)
Detailed Description
An floating-point-like constant.
It abstracts over scalar, fixed-length vectors, and scalable vectors. In the common case, it provides a common API and feels like an APFloat, while still providing low-level access. It can be used for constant-folding.
bool isZero() abstracts over the kind.
switch(const.getKind()) { } provides low-level access.
Definition at line 688 of file Utils.h.
Member Enumeration Documentation
GFConstantKind
enum class llvm::GFConstant::GFConstantKind strong
Enumerator
Scalar
FixedVector
ScalableVector
Definition at line 693 of file Utils.h.
Constructor & Destructor Documentation
GFConstant() [1/2]
llvm::GFConstant::GFConstant (ArrayRef< APFloat > Values) inline
Definition at line 700 of file Utils.h.
Referenced by getConstant().
GFConstant() [2/2]
llvm::GFConstant::GFConstant (const APFloat & Value, GFConstantKind Kind) inline
Definition at line 702 of file Utils.h.
Member Function Documentation
begin()
const_iterator llvm::GFConstant::begin () const inline
Definition at line 709 of file Utils.h.
References assert(), and ScalableVector.
end()
const_iterator llvm::GFConstant::end () const inline
Definition at line 715 of file Utils.h.
References assert(), and ScalableVector.
getConstant()
std::optional< GFConstant > llvm::GFConstant::getConstant (Register Const, const MachineRegisterInfo & MRI) static
Definition at line 2106 of file Utils.cpp.
References llvm::dyn_cast(), llvm::getDefIgnoringCopies(), llvm::getFConstantVRegValWithLookThrough(), GFConstant(), I, MRI, ScalableVector, Scalar, and llvm::Splat.
Referenced by llvm::CombinerHelper::matchCanonicalizeFCmp().
getKind()
GFConstantKind llvm::GFConstant::getKind () const inline
Returns the kind of of this constant, e.g, Scalar.
Definition at line 707 of file Utils.h.
getScalarValue()
APFloat llvm::GFConstant::getScalarValue () const
Returns the value, if this constant is a scalar.
Definition at line 2099 of file Utils.cpp.
References assert(), and Scalar.
size()
size_t llvm::GFConstant::size () const inline
Definition at line 721 of file Utils.h.
References assert(), and FixedVector.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/Utils.h
lib/CodeGen/GlobalISel/Utils.cpp