LLVM: llvm::sandboxir::SeedContainer::iterator Class Reference
llvm::sandboxir::SeedContainer::iterator Class Reference
#include "llvm/Transforms/Vectorize/SandboxVectorizer/SeedCollector.h"
Public Types
using difference_type = std::ptrdiff_t
using value_type = SeedBundle
using pointer = value_type *
using reference = value_type &
using iterator_category = std::input_iterator_tag
Public Member Functions
iterator (BundleMapT &Map, BundleMapT::iterator MapIt, ValT *Vec, int VecIdx)
Iterates over the Map of SeedBundle Vectors, starting at MapIt, and Vec at VecIdx, skipping vectors that are completely used.
value_type & operator* ()
void skipUsed ()
iterator & operator++ ()
iterator operator++ (int)
bool operator== (const iterator &Other) const
bool operator!= (const iterator &Other) const
Detailed Description
Definition at line 200 of file SeedCollector.h.
Member Typedef Documentation
difference_type
using llvm::sandboxir::SeedContainer::iterator::difference_type = std::ptrdiff_t
Definition at line 207 of file SeedCollector.h.
iterator_category
using llvm::sandboxir::SeedContainer::iterator::iterator_category = std::input_iterator_tag
Definition at line 211 of file SeedCollector.h.
pointer
using llvm::sandboxir::SeedContainer::iterator::pointer = value_type *
Definition at line 209 of file SeedCollector.h.
reference
using llvm::sandboxir::SeedContainer::iterator::reference = value_type &
Definition at line 210 of file SeedCollector.h.
value_type
using llvm::sandboxir::SeedContainer::iterator::value_type = SeedBundle
Definition at line 208 of file SeedCollector.h.
Constructor & Destructor Documentation
iterator()
llvm::sandboxir::SeedContainer::iterator::iterator (BundleMapT & Map, BundleMapT::iterator MapIt, ValT * Vec, int VecIdx) inline
Iterates over the Map of SeedBundle Vectors, starting at MapIt, and Vec at VecIdx, skipping vectors that are completely used.
Iteration order over the keys {Pointer, Type, Opcode} follows DenseMap iteration order. For a given key, the vectors of SeedBundles will be returned in insertion order. As in the pseudo code below:
for Key,Value in Bundles for SeedBundleVector in Value for SeedBundle in SeedBundleVector if !SeedBundle.allUsed() ...
Note that the bundles themselves may have additional ordering, created by the subclasses by insertAt. The bundles themselves may also have used instructions.
Definition at line 232 of file SeedCollector.h.
Referenced by operator!=(), operator++(), operator++(), and operator==().
Member Function Documentation
operator!=()
bool llvm::sandboxir::SeedContainer::iterator::operator!= (const iterator & Other) const inline
Definition at line 268 of file SeedCollector.h.
References iterator(), and llvm::Other.
operator*()
value_type & llvm::sandboxir::SeedContainer::iterator::operator* () inline
Definition at line 234 of file SeedCollector.h.
References assert().
operator++() [1/2]
iterator & llvm::sandboxir::SeedContainer::iterator::operator++ () inline
Definition at line 244 of file SeedCollector.h.
References assert(), iterator(), and skipUsed().
operator++() [2/2]
iterator llvm::sandboxir::SeedContainer::iterator::operator++ (int) inline
Definition at line 259 of file SeedCollector.h.
References iterator().
operator==()
bool llvm::sandboxir::SeedContainer::iterator::operator== (const iterator & Other) const inline
Definition at line 264 of file SeedCollector.h.
References assert(), iterator(), and llvm::Other.
skipUsed()
void llvm::sandboxir::SeedContainer::iterator::skipUsed () inline
Definition at line 239 of file SeedCollector.h.
References llvm::sandboxir::SeedContainer::size().
Referenced by operator++().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Vectorize/SandboxVectorizer/SeedCollector.h