LLVM: llvm::RegisterOperands Class Reference
llvm::RegisterOperands Class Reference
List of registers defined and used by a machine instruction.
#include "llvm/CodeGen/RegisterPressure.h"
Public Member Functions
LLVM_ABI void collect (const MachineInstr &MI, const TargetRegisterInfo &TRI, const MachineRegisterInfo &MRI, bool TrackLaneMasks, bool IgnoreDead)
Analyze the given instruction MI and fill in the Uses, Defs and DeadDefs list based on the MachineOperand flags.
LLVM_ABI void detectDeadDefs (const MachineInstr &MI, const LiveIntervals &LIS)
Use liveness information to find dead defs not marked with a dead flag and move them to the DeadDefs vector.
LLVM_ABI void adjustLaneLiveness (const LiveIntervals &LIS, const MachineRegisterInfo &MRI, SlotIndex Pos, MachineInstr *AddFlagsMI=nullptr)
Use liveness information to find out which uses/defs are partially undefined/dead and adjust the VRegMaskOrUnits accordingly.
Public Attributes
SmallVector< VRegMaskOrUnit, 8 > Uses
List of virtual registers and register units read by the instruction.
SmallVector< VRegMaskOrUnit, 8 > Defs
List of virtual registers and register units defined by the instruction which are not dead.
SmallVector< VRegMaskOrUnit, 8 > DeadDefs
List of virtual registers and register units defined by the instruction but dead.
Detailed Description
List of registers defined and used by a machine instruction.
Definition at line 167 of file RegisterPressure.h.
Member Function Documentation
adjustLaneLiveness()
void RegisterOperands::adjustLaneLiveness (const LiveIntervals & LIS, const MachineRegisterInfo & MRI, SlotIndex Pos, MachineInstr * AddFlagsMI = nullptr)
Use liveness information to find out which uses/defs are partially undefined/dead and adjust the VRegMaskOrUnits accordingly.
If AddFlagsMI is given then missing read-undef and dead flags will be added to the instruction.
Definition at line 598 of file RegisterPressure.cpp.
References llvm::VirtRegOrUnit::asVirtualReg(), DeadDefs, Defs, llvm::SlotIndex::getBaseIndex(), llvm::SlotIndex::getDeadSlot(), getLiveLanesAt(), I, llvm::VirtRegOrUnit::isVirtualReg(), MRI, llvm::LaneBitmask::none(), P, llvm::MachineInstr::setRegisterDefReadUndef(), and Uses.
Referenced by llvm::RegPressureTracker::advance(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::GCNDownwardRPTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), llvm::RegPressureTracker::recede(), llvm::GCNSchedStage::revertScheduling(), llvm::ScheduleDAGMILive::scheduleMI(), and llvm::GCNIterativeScheduler::scheduleRegion().
collect()
void RegisterOperands::collect (const MachineInstr & MI, const TargetRegisterInfo & TRI, const MachineRegisterInfo & MRI, bool TrackLaneMasks, bool IgnoreDead)
Analyze the given instruction MI and fill in the Uses, Defs and DeadDefs list based on the MachineOperand flags.
Definition at line 568 of file RegisterPressure.cpp.
References Collector, MI, MRI, and TRI.
Referenced by llvm::RegPressureTracker::advance(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::GCNDownwardRPTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), llvm::RegPressureTracker::recede(), llvm::GCNSchedStage::revertScheduling(), llvm::ScheduleDAGMILive::scheduleMI(), llvm::GCNIterativeScheduler::scheduleRegion(), and llvm::PPCInstrInfo::shouldReduceRegisterPressure().
detectDeadDefs()
void RegisterOperands::detectDeadDefs (const MachineInstr & MI, const LiveIntervals & LIS)
Use liveness information to find dead defs not marked with a dead flag and move them to the DeadDefs vector.
Definition at line 579 of file RegisterPressure.cpp.
References DeadDefs, Defs, llvm::LiveIntervals::getInstructionIndex(), getLiveRange(), llvm::LiveQueryResult::isDeadDef(), MI, and llvm::LiveRange::Query().
Referenced by llvm::RegPressureTracker::bumpUpwardPressure(), llvm::RegPressureTracker::recede(), llvm::GCNSchedStage::revertScheduling(), and llvm::ScheduleDAGMILive::scheduleMI().
Member Data Documentation
DeadDefs
SmallVector<VRegMaskOrUnit, 8> llvm::RegisterOperands::DeadDefs
List of virtual registers and register units defined by the instruction but dead.
Definition at line 176 of file RegisterPressure.h.
Referenced by adjustLaneLiveness(), llvm::RegPressureTracker::advance(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), detectDeadDefs(), and llvm::RegPressureTracker::recede().
Defs
SmallVector<VRegMaskOrUnit, 8> llvm::RegisterOperands::Defs
List of virtual registers and register units defined by the instruction which are not dead.
Definition at line 173 of file RegisterPressure.h.
Referenced by llvm::PressureDiffs::addInstruction(), adjustLaneLiveness(), llvm::RegPressureTracker::advance(), llvm::GCNDownwardRPTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), detectDeadDefs(), and llvm::RegPressureTracker::recede().
Uses
SmallVector<VRegMaskOrUnit, 8> llvm::RegisterOperands::Uses
List of virtual registers and register units read by the instruction.
Definition at line 170 of file RegisterPressure.h.
Referenced by llvm::PressureDiffs::addInstruction(), adjustLaneLiveness(), llvm::RegPressureTracker::advance(), llvm::GCNDownwardRPTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), and llvm::RegPressureTracker::recede().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterPressure.h
lib/CodeGen/RegisterPressure.cpp