LLVM: llvm::ir2vec::VocabStorage::const_iterator Class Reference
llvm::ir2vec::VocabStorage::const_iterator Class Reference
Iterator support for section-based access.
#include "llvm/Analysis/IR2Vec.h"
Public Member Functions
const_iterator (const VocabStorage *Storage, unsigned SectionId, size_t LocalIndex)
LLVM_ABI const Embedding & operator* () const
LLVM_ABI const_iterator & operator++ ()
LLVM_ABI bool operator== (const const_iterator &Other) const
LLVM_ABI bool operator!= (const const_iterator &Other) const
Detailed Description
Iterator support for section-based access.
Definition at line 196 of file IR2Vec.h.
Constructor & Destructor Documentation
const_iterator()
llvm::ir2vec::VocabStorage::const_iterator::const_iterator (const VocabStorage * Storage, unsigned SectionId, size_t LocalIndex) inline
Definition at line 202 of file IR2Vec.h.
References llvm::ir2vec::VocabStorage::VocabStorage().
Referenced by operator!=(), and operator==().
Member Function Documentation
operator!=()
bool VocabStorage::const_iterator::operator!= (const const_iterator & Other) const
Definition at line 311 of file IR2Vec.cpp.
References const_iterator(), and llvm::Other.
operator*()
const Embedding & VocabStorage::const_iterator::operator* () const
Definition at line 285 of file IR2Vec.cpp.
References assert(), and llvm::ir2vec::VocabStorage::size().
operator++()
VocabStorage::const_iterator & VocabStorage::const_iterator::operator++ ()
Definition at line 292 of file IR2Vec.cpp.
References assert(), and llvm::ir2vec::VocabStorage::getNumSections().
operator==()
bool VocabStorage::const_iterator::operator== (const const_iterator & Other) const
Definition at line 305 of file IR2Vec.cpp.
References const_iterator(), and llvm::Other.
The documentation for this class was generated from the following files:
include/llvm/Analysis/IR2Vec.h
lib/Analysis/IR2Vec.cpp