LLVM: llvm::LibcallLoweringModuleAnalysisResult Class Reference
llvm::LibcallLoweringModuleAnalysisResult Class Reference
Record a mapping from subtarget to LibcallLoweringInfo.
#include "llvm/CodeGen/LibcallLoweringInfo.h"
Public Member Functions
LibcallLoweringModuleAnalysisResult ()=default
LibcallLoweringModuleAnalysisResult (RTLIB::RuntimeLibcallsInfo &RTLCI)
void init (const RTLIB::RuntimeLibcallsInfo *RT)
void clear ()
LLVM_ABI bool invalidate (Module &, const PreservedAnalyses &, ModuleAnalysisManager::Invalidator &)
const LibcallLoweringInfo & getLibcallLowering (const TargetSubtargetInfo &Subtarget) const
Detailed Description
Record a mapping from subtarget to LibcallLoweringInfo.
Definition at line 81 of file LibcallLoweringInfo.h.
Constructor & Destructor Documentation
LibcallLoweringModuleAnalysisResult() [1/2]
llvm::LibcallLoweringModuleAnalysisResult::LibcallLoweringModuleAnalysisResult () default
LibcallLoweringModuleAnalysisResult() [2/2]
llvm::LibcallLoweringModuleAnalysisResult::LibcallLoweringModuleAnalysisResult (RTLIB::RuntimeLibcallsInfo & RTLCI) inline
Definition at line 90 of file LibcallLoweringInfo.h.
Member Function Documentation
clear()
void llvm::LibcallLoweringModuleAnalysisResult::clear () inline
Definition at line 95 of file LibcallLoweringInfo.h.
getLibcallLowering()
const LibcallLoweringInfo & llvm::LibcallLoweringModuleAnalysisResult::getLibcallLowering (const TargetSubtargetInfo & Subtarget) const inline
Definition at line 104 of file LibcallLoweringInfo.h.
Referenced by canEmitLibcall(), and canEmitMemcpy().
init()
void llvm::LibcallLoweringModuleAnalysisResult::init (const RTLIB::RuntimeLibcallsInfo * RT) inline
Definition at line 93 of file LibcallLoweringInfo.h.
Referenced by llvm::LibcallLoweringModuleAnalysis::run().
invalidate()
bool LibcallLoweringModuleAnalysisResult::invalidate (Module & , const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator &)
Definition at line 37 of file LibcallLoweringInfo.cpp.
References llvm::PreservedAnalyses::getChecker().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LibcallLoweringInfo.h
lib/CodeGen/LibcallLoweringInfo.cpp