LLVM: llvm::orc::IRLayer Class Reference
llvm::orc::IRLayer Class Reference abstract
Interface for layers that accept LLVM IR.
#include "llvm/ExecutionEngine/Orc/Layer.h"
Public Member Functions
IRLayer (ExecutionSession &ES, const IRSymbolMapper::ManglingOptions *&MO)
virtual ~IRLayer ()
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this layer.
const IRSymbolMapper::ManglingOptions *& getManglingOptions () const
Get the mangling options for this layer.
void setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit)
Sets the CloneToNewContextOnEmit flag (false by default).
bool getCloneToNewContextOnEmit () const
Returns the current value of the CloneToNewContextOnEmit flag.
virtual Error add (ResourceTrackerSP RT, ThreadSafeModule TSM)
Add a MaterializatinoUnit representing the given IR to the JITDylib targeted by the given tracker.
Error add (JITDylib &JD, ThreadSafeModule TSM)
Adds a MaterializationUnit representing the given IR to the given JITDylib.
virtual void emit (std::unique_ptr< MaterializationResponsibility > R, ThreadSafeModule TSM)=0
Emit should materialize the given IR.
Detailed Description
Interface for layers that accept LLVM IR.
Definition at line 68 of file Layer.h.
Constructor & Destructor Documentation
IRLayer()
llvm::orc::IRLayer::IRLayer (ExecutionSession & ES, const IRSymbolMapper::ManglingOptions *& MO) inline
Definition at line 70 of file Layer.h.
Referenced by llvm::orc::CompileOnDemandLayer::CompileOnDemandLayer(), llvm::orc::IRCompileLayer::IRCompileLayer(), llvm::orc::IRPartitionLayer::IRPartitionLayer(), llvm::orc::IRSpeculationLayer::IRSpeculationLayer(), llvm::orc::IRTransformLayer::IRTransformLayer(), and llvm::orc::ReOptimizeLayer::ReOptimizeLayer().
~IRLayer()
llvm::orc::IRLayer::~IRLayer () virtual default
Member Function Documentation
add() [1/2]
Error llvm::orc::IRLayer::add (JITDylib & JD, ThreadSafeModule TSM) inline
Adds a MaterializationUnit representing the given IR to the given JITDylib.
If RT is not specif
Definition at line 105 of file Layer.h.
References add(), and llvm::orc::JITDylib::getDefaultResourceTracker().
add() [2/2]
Error llvm::orc::IRLayer::add (ResourceTrackerSP RT, ThreadSafeModule TSM) virtual
Add a MaterializatinoUnit representing the given IR to the JITDylib targeted by the given tracker.
Definition at line 24 of file Layer.cpp.
References assert(), and getManglingOptions().
Referenced by add().
emit()
virtual void llvm::orc::IRLayer::emit (std::unique_ptr< MaterializationResponsibility > R, ThreadSafeModule TSM) pure virtual
Emit should materialize the given IR.
Implemented in llvm::orc::CompileOnDemandLayer, llvm::orc::IRCompileLayer, llvm::orc::IRPartitionLayer, llvm::orc::IRSpeculationLayer, llvm::orc::IRTransformLayer, and llvm::orc::ReOptimizeLayer.
getCloneToNewContextOnEmit()
bool llvm::orc::IRLayer::getCloneToNewContextOnEmit () const inline
Returns the current value of the CloneToNewContextOnEmit flag.
Definition at line 97 of file Layer.h.
getExecutionSession()
ExecutionSession & llvm::orc::IRLayer::getExecutionSession () inline
Returns the ExecutionSession for this layer.
Definition at line 76 of file Layer.h.
Referenced by llvm::orc::CompileOnDemandLayer::emit(), llvm::orc::IRCompileLayer::emit(), llvm::orc::IRPartitionLayer::emit(), and llvm::orc::IRTransformLayer::emit().
getManglingOptions()
const IRSymbolMapper::ManglingOptions *& llvm::orc::IRLayer::getManglingOptions () const inline
Get the mangling options for this layer.
Definition at line 79 of file Layer.h.
Referenced by add(), llvm::orc::CompileOnDemandLayer::CompileOnDemandLayer(), llvm::orc::CompileOnDemandLayer::emit(), llvm::orc::IRPartitionLayer::emit(), llvm::orc::IRPartitionLayer::IRPartitionLayer(), llvm::orc::IRSpeculationLayer::IRSpeculationLayer(), llvm::orc::IRTransformLayer::IRTransformLayer(), and llvm::orc::ReOptimizeLayer::ReOptimizeLayer().
setCloneToNewContextOnEmit()
void llvm::orc::IRLayer::setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit) inline
Sets the CloneToNewContextOnEmit flag (false by default).
When set, IR modules added to this layer will be cloned on to a new context before emit is called. This can be used by clients who want to load all IR using one LLVMContext (to save memory via type and constant uniquing), but want to move Modules to fresh contexts before compiling them to enable concurrent compilation. Single threaded clients, or clients who load every module on a new context, need not set this.
Definition at line 92 of file Layer.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Layer.h
lib/ExecutionEngine/Orc/Layer.cpp