LLVM: llvm::FunctionAnalysisManagerMachineFunctionProxy::Result Class Reference
llvm::FunctionAnalysisManagerMachineFunctionProxy::Result Class Reference
#include "llvm/CodeGen/MachinePassManager.h"
Public Member Functions
Result (FunctionAnalysisManager &FAM)
Result (Result &&Arg)
Result & operator= (Result &&RHS)
FunctionAnalysisManager & getManager ()
Accessor for the analysis manager.
LLVM_ABI bool invalidate (MachineFunction &IR, const PreservedAnalyses &PA, MachineFunctionAnalysisManager::Invalidator &Inv)
Handler for invalidation of the outer IR unit, IRUnitT.
Detailed Description
Definition at line 132 of file MachinePassManager.h.
Constructor & Destructor Documentation
Result() [1/2]
llvm::FunctionAnalysisManagerMachineFunctionProxy::Result::Result (FunctionAnalysisManager & FAM) inline explicit
Definition at line 134 of file MachinePassManager.h.
Referenced by operator=(), and Result().
Result() [2/2]
llvm::FunctionAnalysisManagerMachineFunctionProxy::Result::Result (Result && Arg) inline
Definition at line 136 of file MachinePassManager.h.
References llvm::move(), and Result().
Member Function Documentation
getManager()
FunctionAnalysisManager & llvm::FunctionAnalysisManagerMachineFunctionProxy::Result::getManager () inline
Accessor for the analysis manager.
Definition at line 153 of file MachinePassManager.h.
invalidate()
bool FunctionAnalysisManagerMachineFunctionProxy::Result::invalidate (MachineFunction & IR, const PreservedAnalyses & PA, MachineFunctionAnalysisManager::Invalidator & Inv)
Handler for invalidation of the outer IR unit, IRUnitT.
If the proxy analysis itself is not preserved, we assume that the set of inner IR objects contained in IRUnit may have changed. In this case, we have to call clear() on the inner analysis manager, as it may now have stale pointers to its inner IR objects.
Regardless of whether the proxy analysis is marked as preserved, all of the analyses in the inner analysis manager are potentially invalidated based on the set of preserved analyses.
Definition at line 37 of file MachinePassManager.cpp.
References IR.
operator=()
Result & llvm::FunctionAnalysisManagerMachineFunctionProxy::Result::operator= (Result && RHS) inline
Definition at line 143 of file MachinePassManager.h.
References Result(), and RHS.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePassManager.h
lib/CodeGen/MachinePassManager.cpp