LLVM: llvm::codeview::DefRangeFramePointerRelFullScopeSym Class Reference
llvm::codeview::DefRangeFramePointerRelFullScopeSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
DefRangeFramePointerRelFullScopeSym (SymbolRecordKind Kind)
DefRangeFramePointerRelFullScopeSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
int32_t Offset = 0
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 619 of file SymbolRecord.h.
Constructor & Destructor Documentation
DefRangeFramePointerRelFullScopeSym() [1/2]
llvm::codeview::DefRangeFramePointerRelFullScopeSym::DefRangeFramePointerRelFullScopeSym (SymbolRecordKind Kind) inline explicit
Definition at line 621 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by DefRangeFramePointerRelFullScopeSym().
DefRangeFramePointerRelFullScopeSym() [2/2]
llvm::codeview::DefRangeFramePointerRelFullScopeSym::DefRangeFramePointerRelFullScopeSym (uint32_t RecordOffset) inline explicit
Definition at line 623 of file SymbolRecord.h.
References DefRangeFramePointerRelFullScopeSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Data Documentation
Offset
int32_t llvm::codeview::DefRangeFramePointerRelFullScopeSym::Offset = 0
Definition at line 627 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
RecordOffset
uint32_t llvm::codeview::DefRangeFramePointerRelFullScopeSym::RecordOffset = 0
Definition at line 629 of file SymbolRecord.h.
Referenced by DefRangeFramePointerRelFullScopeSym().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h