LLVM: llvm::PBQP::RegAlloc::AllowedRegVector Class Reference
llvm::PBQP::RegAlloc::AllowedRegVector Class Reference
Holds a vector of the allowed physical regs for a vreg.
#include "llvm/CodeGen/RegAllocPBQP.h"
Public Member Functions
AllowedRegVector ()=default
AllowedRegVector (AllowedRegVector &&)=default
AllowedRegVector (const std::vector< MCRegister > &OptVec)
unsigned size () const
MCRegister operator[] (size_t I) const
bool operator== (const AllowedRegVector &Other) const
bool operator!= (const AllowedRegVector &Other) const
Friends
hash_code hash_value (const AllowedRegVector &OptRegs)
Detailed Description
Holds a vector of the allowed physical regs for a vreg.
Definition at line 94 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
AllowedRegVector() [1/3]
llvm::PBQP::RegAlloc::AllowedRegVector::AllowedRegVector () default
Referenced by AllowedRegVector(), hash_value, operator!=(), and operator==().
AllowedRegVector() [2/3]
llvm::PBQP::RegAlloc::AllowedRegVector::AllowedRegVector (AllowedRegVector &&) default
References AllowedRegVector().
AllowedRegVector() [3/3]
llvm::PBQP::RegAlloc::AllowedRegVector::AllowedRegVector (const std::vector< MCRegister > & OptVec) inline
Definition at line 101 of file RegAllocPBQP.h.
References llvm::copy(), and size().
Member Function Documentation
operator!=()
bool llvm::PBQP::RegAlloc::AllowedRegVector::operator!= (const AllowedRegVector & Other) const inline
Definition at line 115 of file RegAllocPBQP.h.
References AllowedRegVector(), and llvm::Other.
operator==()
bool llvm::PBQP::RegAlloc::AllowedRegVector::operator== (const AllowedRegVector & Other) const inline
Definition at line 109 of file RegAllocPBQP.h.
References AllowedRegVector(), and llvm::Other.
operator[]()
MCRegister llvm::PBQP::RegAlloc::AllowedRegVector::operator[] (size_t I) const inline
Definition at line 107 of file RegAllocPBQP.h.
References I.
size()
unsigned llvm::PBQP::RegAlloc::AllowedRegVector::size () const inline
Definition at line 106 of file RegAllocPBQP.h.
Referenced by AllowedRegVector().
Friends And Related Symbol Documentation
hash_value
hash_code hash_value (const AllowedRegVector & OptRegs) friend
Definition at line 124 of file RegAllocPBQP.h.
References AllowedRegVector(), llvm::hash_combine(), and llvm::hash_combine_range().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/RegAllocPBQP.h