LLVM: llvm::orc::LibraryInfo Class Reference
llvm::orc::LibraryInfo Class Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h"
Public Member Functions
LibraryInfo (const LibraryInfo &)=delete
LibraryInfo & operator= (const LibraryInfo &)=delete
LibraryInfo (std::string FilePath, LibState S, PathType K, std::optional< BloomFilter > Filter=std::nullopt)
StringRef getBasePath () const
StringRef getFileName () const
std::string getFullPath () const
void setFilter (BloomFilter F)
void ensureFilterBuilt (const BloomFilterBuilder &FB, ArrayRef< StringRef > Symbols)
bool mayContain (StringRef Symbol) const
bool hasFilter () const
LibState getState () const
PathType getKind () const
void setState (LibState s)
bool operator== (const LibraryInfo &other) const
Detailed Description
Definition at line 32 of file LibraryResolver.h.
Constructor & Destructor Documentation
LibraryInfo() [1/2]
llvm::orc::LibraryInfo::LibraryInfo (const LibraryInfo &) delete
References LibraryInfo().
Referenced by LibraryInfo(), operator=(), and operator==().
LibraryInfo() [2/2]
llvm::orc::LibraryInfo::LibraryInfo (std::string FilePath, LibState S, PathType K, std::optional< BloomFilter > Filter = std::nullopt) inline
Definition at line 37 of file LibraryResolver.h.
References llvm::move().
Member Function Documentation
ensureFilterBuilt()
void llvm::orc::LibraryInfo::ensureFilterBuilt (const BloomFilterBuilder & FB, ArrayRef< StringRef > Symbols) inline
Definition at line 53 of file LibraryResolver.h.
References llvm::orc::BloomFilterBuilder::build().
getBasePath()
StringRef llvm::orc::LibraryInfo::getBasePath () const inline
Definition at line 41 of file LibraryResolver.h.
References llvm::sys::path::parent_path().
getFileName()
StringRef llvm::orc::LibraryInfo::getFileName () const inline
Definition at line 42 of file LibraryResolver.h.
References llvm::sys::path::filename().
getFullPath()
std::string llvm::orc::LibraryInfo::getFullPath () const inline
Definition at line 44 of file LibraryResolver.h.
getKind()
PathType llvm::orc::LibraryInfo::getKind () const inline
Definition at line 73 of file LibraryResolver.h.
getState()
LibState llvm::orc::LibraryInfo::getState () const inline
Definition at line 72 of file LibraryResolver.h.
hasFilter()
bool llvm::orc::LibraryInfo::hasFilter () const inline
Definition at line 67 of file LibraryResolver.h.
Referenced by mayContain().
mayContain()
bool llvm::orc::LibraryInfo::mayContain (StringRef Symbol) const inline
Definition at line 61 of file LibraryResolver.h.
References assert(), and hasFilter().
operator=()
LibraryInfo & llvm::orc::LibraryInfo::operator= (const LibraryInfo &) delete
References LibraryInfo().
operator==()
bool llvm::orc::LibraryInfo::operator== (const LibraryInfo & other) const inline
Definition at line 77 of file LibraryResolver.h.
References LibraryInfo().
setFilter()
void llvm::orc::LibraryInfo::setFilter (BloomFilter F) inline
Definition at line 46 of file LibraryResolver.h.
References F.
setState()
void llvm::orc::LibraryInfo::setState (LibState s) inline
Definition at line 75 of file LibraryResolver.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h