LLVM: llvm::xray::Profile Class Reference
llvm::xray::Profile Class Reference
Profile instances are thread-compatible.
#include "llvm/XRay/Profile.h"
Classes
struct Data
struct Block
Public Types
using ThreadID = uint64_t
using PathID = unsigned
using FuncID = int32_t
using const_iterator = BlockList::const_iterator
Public Member Functions
LLVM_ABI Expected< std::vector< FuncID > > expandPath (PathID P) const
Provides a sequence of function IDs from a previously interned PathID.
LLVM_ABI PathID internPath (ArrayRef< FuncID > P)
The stack represented in |P| must be in stack order (leaf to root).
LLVM_ABI Error addBlock (Block &&B)
Appends a fully-formed Block instance into the Profile.
Profile ()=default
~Profile ()=default
Profile (Profile &&O) noexcept
Profile & operator= (Profile &&O) noexcept
LLVM_ABI Profile (const Profile &)
LLVM_ABI Profile & operator= (const Profile &)
const_iterator begin () const
const_iterator end () const
bool empty () const
Friends
void swap (Profile &L, Profile &R)
Detailed Description
Profile instances are thread-compatible.
Definition at line 51 of file Profile.h.
Member Typedef Documentation
const_iterator
using llvm::xray::Profile::const_iterator = BlockList::const_iterator
Definition at line 140 of file Profile.h.
FuncID
using llvm::xray::Profile::FuncID = int32_t
Definition at line 55 of file Profile.h.
PathID
using llvm::xray::Profile::PathID = unsigned
Definition at line 54 of file Profile.h.
ThreadID
using llvm::xray::Profile::ThreadID = uint64_t
Definition at line 53 of file Profile.h.
Constructor & Destructor Documentation
Profile() [1/3]
llvm::xray::Profile::Profile () default
Referenced by operator=(), operator=(), Profile(), Profile(), and swap.
~Profile()
llvm::xray::Profile::~Profile () default
Profile() [2/3]
llvm::xray::Profile::Profile (Profile && O) inline noexcept
Definition at line 88 of file Profile.h.
References Profile().
Profile() [3/3]
Profile::Profile (const Profile & O)
Definition at line 24 of file Profile.cpp.
References B(), llvm::cantFail(), internPath(), llvm::xray::Profile::Block::PathData, Profile(), and llvm::xray::Profile::Block::Thread.
Member Function Documentation
addBlock()
Error Profile::addBlock (Block && B)
Appends a fully-formed Block instance into the Profile.
Returns an error condition in the following cases:
The PathData component of the Block is empty
Definition at line 119 of file Profile.cpp.
References B(), llvm::make_error(), and llvm::Error::success().
Referenced by llvm::xray::mergeProfilesByStack(), and llvm::xray::mergeProfilesByThread().
begin()
const_iterator llvm::xray::Profile::begin () const inline
Definition at line 141 of file Profile.h.
empty()
bool llvm::xray::Profile::empty () const inline
Definition at line 143 of file Profile.h.
end()
const_iterator llvm::xray::Profile::end () const inline
Definition at line 142 of file Profile.h.
expandPath()
Expected< std::vector< Profile::FuncID > > Profile::expandPath (PathID P) const
Provides a sequence of function IDs from a previously interned PathID.
Returns an error if |P| had not been interned before into the Profile.
Definition at line 129 of file Profile.cpp.
References llvm::make_error(), and P.
internPath()
Profile::PathID Profile::internPath (ArrayRef< FuncID > P)
The stack represented in |P| must be in stack order (leaf to root).
This will always return the same PathID for |P| that has the same sequence.
Definition at line 141 of file Profile.cpp.
References assert(), llvm::find_if(), N, P, and llvm::reverse().
Referenced by llvm::xray::mergeProfilesByStack(), llvm::xray::mergeProfilesByThread(), and Profile().
operator=() [1/2]
Profile & Profile::operator= (const Profile & O)
Definition at line 36 of file Profile.cpp.
References P, and Profile().
operator=() [2/2]
Profile & llvm::xray::Profile::operator= (Profile && O) inline noexcept
Definition at line 93 of file Profile.h.
References Profile().
Friends And Related Symbol Documentation
swap
void swap (Profile & L, Profile & R) friend
Definition at line 105 of file Profile.h.
References Profile(), swap, and std::swap().
Referenced by swap.
The documentation for this class was generated from the following files:
include/llvm/XRay/Profile.h
lib/XRay/Profile.cpp