LLVM: llvm::BoundsCheckingPass Class Reference
llvm::BoundsCheckingPass Class Reference
A pass to instrument code and perform run-time bounds checking on loads, stores, and other memory intrinsics.
#include "llvm/Transforms/Instrumentation/BoundsChecking.h"
Classes
struct Options
Public Member Functions
BoundsCheckingPass (Options Opts)
LLVM_ABI PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
LLVM_ABI void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< BoundsCheckingPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< BoundsCheckingPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A pass to instrument code and perform run-time bounds checking on loads, stores, and other memory intrinsics.
Definition at line 22 of file BoundsChecking.h.
Constructor & Destructor Documentation
BoundsCheckingPass()
llvm::BoundsCheckingPass::BoundsCheckingPass (Options Opts) inline
Definition at line 39 of file BoundsChecking.h.
Member Function Documentation
isRequired()
bool llvm::BoundsCheckingPass::isRequired () inline static
Definition at line 41 of file BoundsChecking.h.
printPipeline()
void BoundsCheckingPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 305 of file BoundsChecking.cpp.
References printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses BoundsCheckingPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 295 of file BoundsChecking.cpp.
References addBoundsChecking(), llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/BoundsChecking.h
lib/Transforms/Instrumentation/BoundsChecking.cpp