LLVM: llvm::opt::OptSpecifier Class Reference
llvm::opt::OptSpecifier Class Reference
OptSpecifier - Wrapper class for abstracting references to option IDs.
#include "llvm/Option/OptSpecifier.h"
Public Member Functions
OptSpecifier ()=default
OptSpecifier (bool)=delete
OptSpecifier (unsigned ID)
LLVM_ABI OptSpecifier (const Option *Opt)
bool isValid () const
unsigned getID () const
bool operator== (OptSpecifier Opt) const
bool operator!= (OptSpecifier Opt) const
Detailed Description
OptSpecifier - Wrapper class for abstracting references to option IDs.
Definition at line 20 of file OptSpecifier.h.
Constructor & Destructor Documentation
OptSpecifier() [1/4]
llvm::opt::OptSpecifier::OptSpecifier () default
Referenced by operator!=(), and operator==().
OptSpecifier() [2/4]
llvm::opt::OptSpecifier::OptSpecifier (bool) explicit delete
OptSpecifier() [3/4]
llvm::opt::OptSpecifier::OptSpecifier (unsigned ID) inline
Definition at line 26 of file OptSpecifier.h.
OptSpecifier() [4/4]
OptSpecifier::OptSpecifier (const Option * Opt)
Definition at line 77 of file OptTable.cpp.
References getID().
Member Function Documentation
getID()
unsigned llvm::opt::OptSpecifier::getID () const inline
Definition at line 31 of file OptSpecifier.h.
Referenced by llvm::opt::OptTable::getOption(), llvm::opt::Option::matches(), operator==(), and OptSpecifier().
isValid()
bool llvm::opt::OptSpecifier::isValid () const inline
Definition at line 29 of file OptSpecifier.h.
operator!=()
bool llvm::opt::OptSpecifier::operator!= (OptSpecifier Opt) const inline
Definition at line 34 of file OptSpecifier.h.
References OptSpecifier().
operator==()
bool llvm::opt::OptSpecifier::operator== (OptSpecifier Opt) const inline
Definition at line 33 of file OptSpecifier.h.
References getID(), and OptSpecifier().
The documentation for this class was generated from the following files:
include/llvm/Option/OptSpecifier.h
lib/Option/OptTable.cpp