LLVM: llvm::object::BasicSymbolRef Class Reference
llvm::object::BasicSymbolRef Class Reference
This is a value type class that represents a single symbol in the list of symbols in the object file.
#include "llvm/Object/SymbolicFile.h"
Public Types
enum Flags : unsigned {
SF_None = 0 , SF_Undefined = 1U << 0 , SF_Global = 1U << 1 , SF_Weak = 1U << 2 ,
SF_Absolute = 1U << 3 , SF_Common = 1U << 4 , SF_Indirect = 1U << 5 , SF_Exported = 1U << 6 ,
SF_FormatSpecific = 1U << 7 , SF_Thumb = 1U << 8 , SF_Hidden = 1U << 9 , SF_Const = 1U << 10 ,
SF_Executable = 1U << 11
}
Public Member Functions
BasicSymbolRef ()=default
BasicSymbolRef (DataRefImpl SymbolP, const SymbolicFile *Owner)
bool operator== (const BasicSymbolRef &Other) const
bool operator< (const BasicSymbolRef &Other) const
void moveNext ()
Error printName (raw_ostream &OS) const
Expected< uint32_t > getFlags () const
Get symbol flags (bitwise OR of SymbolRef::Flags).
DataRefImpl getRawDataRefImpl () const
const SymbolicFile * getObject () const
Detailed Description
This is a value type class that represents a single symbol in the list of symbols in the object file.
Definition at line 104 of file SymbolicFile.h.
Member Enumeration Documentation
Flags
enum llvm::object::BasicSymbolRef::Flags : unsigned
Enumerator
SF_None
SF_Undefined
SF_Global
SF_Weak
SF_Absolute
SF_Common
SF_Indirect
SF_Exported
SF_FormatSpecific
SF_Thumb
SF_Hidden
SF_Const
SF_Executable
Definition at line 109 of file SymbolicFile.h.
Constructor & Destructor Documentation
BasicSymbolRef() [1/2]
llvm::object::BasicSymbolRef::BasicSymbolRef () default
References BasicSymbolRef(), and Owner.
Referenced by BasicSymbolRef(), operator<(), operator==(), llvm::object::SymbolRef::SymbolRef(), and llvm::object::SymbolRef::SymbolRef().
BasicSymbolRef() [2/2]
llvm::object::BasicSymbolRef::BasicSymbolRef (DataRefImpl SymbolP, const SymbolicFile * Owner) inline
Definition at line 187 of file SymbolicFile.h.
References Owner.
Member Function Documentation
getFlags()
Expected< uint32_t > llvm::object::BasicSymbolRef::getFlags () const inline
Get symbol flags (bitwise OR of SymbolRef::Flags).
Definition at line 207 of file SymbolicFile.h.
Referenced by isArchiveSymbol(), and llvm::orc::shouldIgnoreSymbol().
getObject()
const SymbolicFile * llvm::object::BasicSymbolRef::getObject () const inline
Definition at line 215 of file SymbolicFile.h.
Referenced by llvm::object::ELFSymbolRef::getObject(), llvm::object::GOFFSymbolRef::getObject(), llvm::object::SymbolRef::getObject(), and llvm::object::SymbolRef::SymbolRef().
getRawDataRefImpl()
DataRefImpl llvm::object::BasicSymbolRef::getRawDataRefImpl () const inline
Definition at line 211 of file SymbolicFile.h.
Referenced by llvm::object::SymbolRef::getAddress(), llvm::object::SymbolRef::getAlignment(), llvm::object::ELFSymbolRef::getBinding(), llvm::object::SymbolRef::getCommonSize(), llvm::object::ELFSymbolRef::getELFType(), llvm::object::XCOFFSymbolRef::getEntryAddress(), llvm::object::SymbolRef::getName(), llvm::object::ELFSymbolRef::getOther(), llvm::object::ELFObjectFileBase::getPltEntries(), llvm::object::SymbolRef::getSection(), llvm::object::ELFSymbolRef::getSize(), llvm::object::GOFFSymbolRef::getSize(), llvm::object::XCOFFSymbolRef::getSize(), llvm::object::XCOFFSymbolRef::getSymbol32(), llvm::object::XCOFFSymbolRef::getSymbol64(), llvm::object::GOFFSymbolRef::getSymbolGOFFFlags(), llvm::object::GOFFSymbolRef::getSymbolGOFFType(), llvm::object::COFFObjectFile::getSymbolSectionID(), llvm::object::MachOObjectFile::getSymbolSectionID(), llvm::object::XCOFFObjectFile::getSymbolSectionID(), llvm::object::SymbolRef::getType(), llvm::object::SymbolRef::getValue(), llvm::object::XCOFFSymbolRef::getValue32(), llvm::object::XCOFFSymbolRef::getValue64(), llvm::object::WasmObjectFile::getWasmSymbol(), llvm::jitlink::getXCOFFSymbolContainingSymbolRef(), and llvm::jitlink::printSymbolEntry().
moveNext()
void llvm::object::BasicSymbolRef::moveNext () inline
Definition at line 199 of file SymbolicFile.h.
operator<()
bool llvm::object::BasicSymbolRef::operator< (const BasicSymbolRef & Other) const inline
Definition at line 195 of file SymbolicFile.h.
References BasicSymbolRef(), and llvm::Other.
operator==()
bool llvm::object::BasicSymbolRef::operator== (const BasicSymbolRef & Other) const inline
Definition at line 191 of file SymbolicFile.h.
References BasicSymbolRef(), and llvm::Other.
printName()
Error llvm::object::BasicSymbolRef::printName (raw_ostream & OS) const inline
Definition at line 203 of file SymbolicFile.h.
The documentation for this class was generated from the following file:
include/llvm/Object/SymbolicFile.h