LLVM: llvm::DebugCounter Class Reference
llvm::DebugCounter Class Reference
#include "llvm/Support/DebugCounter.h"
Classes
class CounterInfo
Struct to store counter info.
struct CounterState
Public Member Functions
LLVM_ABI void push_back (const std::string &)
LLVM_DUMP_METHOD void dump () const
LLVM_ABI void print (raw_ostream &OS) const
CounterInfo * getCounterInfo (StringRef Name) const
unsigned int getNumCounters () const
std::pair< StringRef, StringRef > getCounterDesc (CounterInfo *Info) const
MapVector< StringRef, CounterInfo * >::const_iterator begin () const
MapVector< StringRef, CounterInfo * >::const_iterator end () const
void activateAllCounters ()
Static Public Member Functions
static LLVM_ABI void printChunks (raw_ostream &OS, ArrayRef< IntegerInclusiveInterval > Intervals)
static LLVM_ABI bool parseChunks (StringRef Str, IntegerInclusiveIntervalUtils::IntervalList &Res)
Return true on parsing error and print the error message on the llvm::errs().
static LLVM_ABI DebugCounter & instance ()
Returns a reference to the singleton instance.
static void registerCounter (CounterInfo *Info)
static LLVM_ABI bool shouldExecuteImpl (CounterInfo &Counter)
static bool shouldExecute (CounterInfo &Counter)
static bool isCounterSet (CounterInfo &Info)
static CounterState getCounterState (CounterInfo &Info)
static void setCounterState (CounterInfo &Info, CounterState State)
Protected Member Functions
void addCounter (CounterInfo *Info)
bool handleCounterIncrement (CounterInfo &Info)
Protected Attributes
MapVector< StringRef, CounterInfo * > Counters
bool ShouldPrintCounter = false
bool ShouldPrintCounterQueries = false
bool BreakOnLast = false
Detailed Description
Definition at line 58 of file DebugCounter.h.
Member Function Documentation
activateAllCounters()
void llvm::DebugCounter::activateAllCounters () inline
Definition at line 163 of file DebugCounter.h.
References _, and Counters.
addCounter()
void llvm::DebugCounter::addCounter (CounterInfo * Info) inline protected
Definition at line 169 of file DebugCounter.h.
References Counters, and Info.
Referenced by registerCounter().
begin()
MapVector< StringRef, CounterInfo * >::const_iterator llvm::DebugCounter::begin () const inline
Definition at line 156 of file DebugCounter.h.
References Counters.
dump()
LLVM_DUMP_METHOD void DebugCounter::dump () const
Definition at line 197 of file DebugCounter.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
end()
MapVector< StringRef, CounterInfo * >::const_iterator llvm::DebugCounter::end () const inline
Definition at line 159 of file DebugCounter.h.
References Counters.
getCounterDesc()
std::pair< StringRef, StringRef > llvm::DebugCounter::getCounterDesc (CounterInfo * Info) const inline
Definition at line 151 of file DebugCounter.h.
References Info.
getCounterInfo()
CounterInfo * llvm::DebugCounter::getCounterInfo (StringRef Name) const inline
Definition at line 143 of file DebugCounter.h.
References Counters.
Referenced by print(), and push_back().
getCounterState()
CounterState llvm::DebugCounter::getCounterState (CounterInfo & Info) inline static
Definition at line 124 of file DebugCounter.h.
References Info.
getNumCounters()
unsigned int llvm::DebugCounter::getNumCounters () const inline
Definition at line 148 of file DebugCounter.h.
References Counters.
handleCounterIncrement()
bool DebugCounter::handleCounterIncrement (CounterInfo & Info) protected
Handle consecutive blocks.
Definition at line 161 of file DebugCounter.cpp.
References BreakOnLast, and LLVM_BUILTIN_DEBUGTRAP.
instance()
DebugCounter & DebugCounter::instance () static
Returns a reference to the singleton instance.
Definition at line 113 of file DebugCounter.cpp.
References Owner.
Referenced by llvm::initDebugCounterOptions(), registerCounter(), and shouldExecuteImpl().
isCounterSet()
bool llvm::DebugCounter::isCounterSet (CounterInfo & Info) inline static
Definition at line 116 of file DebugCounter.h.
References Info.
parseChunks()
LLVM_ABI bool llvm::DebugCounter::parseChunks (StringRef Str, IntegerInclusiveIntervalUtils::IntervalList & Res) static
Return true on parsing error and print the error message on the llvm::errs().
References LLVM_ABI.
print()
void DebugCounter::print (raw_ostream & OS) const
Definition at line 148 of file DebugCounter.cpp.
References llvm::CallingConv::C, Counters, getCounterInfo(), llvm::left_justify(), printChunks(), and llvm::sort().
Referenced by dump().
printChunks()
void llvm::DebugCounter::printChunks (raw_ostream & OS, ArrayRef< IntegerInclusiveInterval > Intervals) static
Definition at line 13 of file DebugCounter.cpp.
References llvm::IntegerInclusiveIntervalUtils::printIntervals().
Referenced by print().
push_back()
void DebugCounter::push_back (const std::string & Val)
Definition at line 117 of file DebugCounter.cpp.
References llvm::errs(), getCounterInfo(), llvm::handleAllErrors(), llvm::IntegerInclusiveIntervalUtils::parseIntervals(), and llvm::StringRef::split().
registerCounter()
void llvm::DebugCounter::registerCounter (CounterInfo * Info) inline static
Definition at line 102 of file DebugCounter.h.
References addCounter(), Info, and instance().
Referenced by llvm::DebugCounter::CounterInfo::CounterInfo().
setCounterState()
void llvm::DebugCounter::setCounterState (CounterInfo & Info, CounterState State) inline static
Definition at line 129 of file DebugCounter.h.
References Info.
shouldExecute()
bool llvm::DebugCounter::shouldExecute (CounterInfo & Counter) inline static
Definition at line 107 of file DebugCounter.h.
References shouldExecuteImpl().
Referenced by checkCondition(), DCEInstruction(), findRenameRegForSameLdStRegPair(), llvm::getKnowledgeFromBundle(), llvm::Attributor::getOrCreateAAFor(), slpvectorizer::BoUpSLP::isTreeTinyAndNotFullyVectorizable(), llvm::Negator::Negate(), optimizeDivRem(), optimizeSQRT(), llvm::InstCombinerImpl::run(), and llvm::InstructionSelect::selectMachineFunction().
shouldExecuteImpl()
bool DebugCounter::shouldExecuteImpl (CounterInfo & Counter) static
Definition at line 186 of file DebugCounter.cpp.
References llvm::dbgs(), and instance().
Referenced by shouldExecute().
Member Data Documentation
BreakOnLast
bool llvm::DebugCounter::BreakOnLast = false protected
Definition at line 178 of file DebugCounter.h.
Referenced by handleCounterIncrement().
Counters
MapVector<StringRef, CounterInfo *> llvm::DebugCounter::Counters protected
Definition at line 172 of file DebugCounter.h.
Referenced by activateAllCounters(), addCounter(), begin(), end(), getCounterInfo(), getNumCounters(), and print().
ShouldPrintCounter
bool llvm::DebugCounter::ShouldPrintCounter = false protected
Definition at line 174 of file DebugCounter.h.
ShouldPrintCounterQueries
bool llvm::DebugCounter::ShouldPrintCounterQueries = false protected
Definition at line 176 of file DebugCounter.h.
The documentation for this class was generated from the following files:
include/llvm/Support/DebugCounter.h
lib/Support/DebugCounter.cpp