LLVM: llvm::mca::ReleaseAtCycles Class Reference
llvm::mca::ReleaseAtCycles Class Reference
This class represents the number of cycles per resource (fractions of cycles).
#include "llvm/MCA/Support.h"
Public Member Functions
ReleaseAtCycles ()
ReleaseAtCycles (unsigned Cycles, unsigned ResourceUnits=1)
operator double () const
unsigned getNumerator () const
unsigned getDenominator () const
LLVM_ABI ReleaseAtCycles & operator+= (const ReleaseAtCycles &RHS)
Detailed Description
This class represents the number of cycles per resource (fractions of cycles).
That quantity is managed here as a ratio, and accessed via the double cast-operator below. The two quantities, number of cycles and number of resources, are kept separate. This is used by the ResourcePressureView to calculate the average resource cycles per instruction/iteration.
Definition at line 52 of file Support.h.
Constructor & Destructor Documentation
ReleaseAtCycles() [1/2]
llvm::mca::ReleaseAtCycles::ReleaseAtCycles () inline
Definition at line 56 of file Support.h.
Referenced by operator+=().
ReleaseAtCycles() [2/2]
llvm::mca::ReleaseAtCycles::ReleaseAtCycles (unsigned Cycles, unsigned ResourceUnits = 1) inline
Definition at line 57 of file Support.h.
Member Function Documentation
getDenominator()
unsigned llvm::mca::ReleaseAtCycles::getDenominator () const inline
Definition at line 66 of file Support.h.
getNumerator()
unsigned llvm::mca::ReleaseAtCycles::getNumerator () const inline
Definition at line 65 of file Support.h.
operator double()
llvm::mca::ReleaseAtCycles::operator double () const inline
Definition at line 60 of file Support.h.
References assert().
operator+=()
ReleaseAtCycles & llvm::mca::ReleaseAtCycles::operator+= (const ReleaseAtCycles & RHS)
Definition at line 24 of file Support.cpp.
References ReleaseAtCycles(), and RHS.
The documentation for this class was generated from the following files:
include/llvm/MCA/Support.h
lib/MCA/Support.cpp