LLVM: llvm::MCSymbolXCOFF Class Reference
llvm::MCSymbolXCOFF Class Reference
#include "llvm/MC/MCSymbolXCOFF.h"
Public Types
enum CodeModel : uint8_t { CM_Small , CM_Large }
Public Member Functions
MCSymbolXCOFF (const MCSymbolTableEntry *Name, bool isTemporary)
bool isExternal () const
void setExternal (bool Value) const
void setStorageClass (XCOFF::StorageClass SC)
XCOFF::StorageClass getStorageClass () const
StringRef getUnqualifiedName () const
MCSectionXCOFF * getRepresentedCsect () const
void setRepresentedCsect (MCSectionXCOFF *C)
void setVisibilityType (XCOFF::VisibilityType SVT)
XCOFF::VisibilityType getVisibilityType () const
bool hasRename () const
void setSymbolTableName (StringRef STN)
StringRef getSymbolTableName () const
bool isEHInfo () const
void setEHInfo () const
bool hasPerSymbolCodeModel () const
CodeModel getPerSymbolCodeModel () const
void setPerSymbolCodeModel (MCSymbolXCOFF::CodeModel Model)
Public Member Functions inherited from llvm::MCSymbol
StringRef getName () const
getName - Get the symbol name.
bool isRegistered () const
void setIsRegistered (bool Value) const
void setUsedInReloc () const
bool isUsedInReloc () const
uint32_t getIndex () const
Get the (implementation defined) index.
void setIndex (uint32_t Value) const
Set the (implementation defined) index.
uint64_t getOffset () const
void setOffset (uint64_t Value)
uint64_t getCommonSize () const
Return the size of a 'common' symbol.
void setCommon (uint64_t Size, Align Alignment)
Mark this symbol as being 'common'.
MaybeAlign getCommonAlignment () const
Return the alignment of a 'common' symbol.
bool declareCommon (uint64_t Size, Align Alignment)
Declare this symbol as being 'common'.
bool isCommon () const
Is this a 'common' symbol.
MCFragment * getFragment () const
bool isWeakExternal () const
LLVM_ABI void print (raw_ostream &OS, const MCAsmInfo *MAI) const
print - Print the value to the stream OS.
LLVM_ABI void dump () const
dump - Print the value to stderr.
bool isTemporary () const
isTemporary - Check if this is an assembler temporary symbol.
bool isRedefinable () const
Check if this symbol is redefinable.
void setRedefinable (bool Value)
Mark this symbol as redefinable.
void redefineIfPossible ()
Prepare this symbol to be redefined.
bool isResolving () const
void setIsResolving (bool V)
bool isDefined () const
isDefined - Check if this symbol is defined (i.e., it has an address).
bool isInSection () const
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
bool isUndefined () const
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
bool isAbsolute () const
isAbsolute - Check if this is an absolute symbol.
MCSection & getSection () const
Get the section associated with a defined, non-absolute symbol.
void setFragment (MCFragment *F) const
Mark the symbol as defined in the fragment F.
bool isVariable () const
isVariable - Check if this is a variable symbol.
const MCExpr * getVariableValue () const
Get the expression of the variable symbol.
LLVM_ABI void setVariableValue (const MCExpr *Value)
Static Public Member Functions
static StringRef getUnqualifiedName (StringRef Name)
Additional Inherited Members
Protected Types inherited from llvm::MCSymbol
enum Kind : uint8_t { Regular , Equated , Common }
enum : unsigned { NumCommonAlignmentBits = 5 }
The alignment of the symbol if it is 'common'.
enum : unsigned { NumFlagsBits = 16 }
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
using NameEntryStorageTy
The name for a symbol.
Protected Member Functions inherited from llvm::MCSymbol
MCSymbol (const MCSymbolTableEntry *Name, bool isTemporary)
MCSymbol (const MCSymbol &)=default
MCSymbol & operator= (const MCSymbol &)=delete
LLVM_ABI void * operator new (size_t s, const MCSymbolTableEntry *Name, MCContext &Ctx)
uint32_t getFlags () const
Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value) const
Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask) const
Modify the flags via a mask.
Protected Attributes inherited from llvm::MCSymbol
MCFragment * Fragment = nullptr
If a symbol has a Fragment, the section is implied, so we only need one pointer.
unsigned kind: 2
The symbol kind.
unsigned HasName: 1
True if this symbol is named.
unsigned IsTemporary: 1
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
unsigned IsRedefinable: 1
True if this symbol can be redefined.
unsigned IsRegistered: 1
unsigned IsExternal: 1
True if this symbol is visible outside this translation unit.
unsigned IsPrivateExtern: 1
Mach-O specific: This symbol is private extern.
unsigned IsWeakExternal: 1
This symbol is weak external.
unsigned IsUsedInReloc: 1
True if we have created a relocation that uses this symbol.
unsigned IsResolving: 1
Used to detect cyclic dependency like a = a + 1 and a = b; b = a.
unsigned CommonAlignLog2: NumCommonAlignmentBits
uint32_t Flags: NumFlagsBits
uint32_t Index = 0
Index field, for use by the object file implementation.
union {
uint64_t Offset
The offset to apply to the fragment address to form this symbol's value.
uint64_t CommonSize
The size of the symbol, if it is 'common'.
const MCExpr * Value
If non-null, the value for a variable symbol.
};
Static Protected Attributes inherited from llvm::MCSymbol
static LLVM_ABI MCFragment * AbsolutePseudoFragment = &SentinelFragment
Detailed Description
Definition at line 20 of file MCSymbolXCOFF.h.
Member Enumeration Documentation
CodeModel
enum llvm::MCSymbolXCOFF::CodeModel : uint8_t
Enumerator
CM_Small
CM_Large
Definition at line 28 of file MCSymbolXCOFF.h.
Constructor & Destructor Documentation
MCSymbolXCOFF()
llvm::MCSymbolXCOFF::MCSymbolXCOFF (const MCSymbolTableEntry * Name, bool isTemporary) inline
Definition at line 25 of file MCSymbolXCOFF.h.
References llvm::MCSymbol::isTemporary(), and llvm::MCSymbol::MCSymbol().
Member Function Documentation
getPerSymbolCodeModel()
CodeModel llvm::MCSymbolXCOFF::getPerSymbolCodeModel () const inline
Definition at line 80 of file MCSymbolXCOFF.h.
References assert(), and hasPerSymbolCodeModel().
getRepresentedCsect()
MCSectionXCOFF * MCSymbolXCOFF::getRepresentedCsect () const
Definition at line 13 of file MCSymbolXCOFF.cpp.
References assert(), and getSymbolTableName().
getStorageClass()
XCOFF::StorageClass llvm::MCSymbolXCOFF::getStorageClass () const inline
Definition at line 46 of file MCSymbolXCOFF.h.
References assert().
getSymbolTableName()
StringRef llvm::MCSymbolXCOFF::getSymbolTableName () const inline
Definition at line 68 of file MCSymbolXCOFF.h.
References getUnqualifiedName(), and hasRename().
Referenced by llvm::AsmPrinter::doInitialization(), getRepresentedCsect(), and setRepresentedCsect().
getUnqualifiedName() [1/2]
StringRef llvm::MCSymbolXCOFF::getUnqualifiedName () const inline
Definition at line 51 of file MCSymbolXCOFF.h.
References llvm::MCSymbol::getName(), and getUnqualifiedName().
Referenced by getSymbolTableName(), and getUnqualifiedName().
getUnqualifiedName() [2/2]
StringRef llvm::MCSymbolXCOFF::getUnqualifiedName (StringRef Name) inline static
Definition at line 30 of file MCSymbolXCOFF.h.
References assert(), and llvm::StringRef::empty().
Referenced by llvm::MCContext::getXCOFFSection().
getVisibilityType()
XCOFF::VisibilityType llvm::MCSymbolXCOFF::getVisibilityType () const inline
Definition at line 59 of file MCSymbolXCOFF.h.
hasPerSymbolCodeModel()
bool llvm::MCSymbolXCOFF::hasPerSymbolCodeModel () const inline
Definition at line 78 of file MCSymbolXCOFF.h.
Referenced by getPerSymbolCodeModel().
hasRename()
bool llvm::MCSymbolXCOFF::hasRename () const inline
Definition at line 61 of file MCSymbolXCOFF.h.
Referenced by llvm::AsmPrinter::doInitialization(), and getSymbolTableName().
isEHInfo()
bool llvm::MCSymbolXCOFF::isEHInfo () const inline
Definition at line 74 of file MCSymbolXCOFF.h.
References llvm::MCSymbol::getFlags().
isExternal()
bool llvm::MCSymbolXCOFF::isExternal () const inline
Definition at line 40 of file MCSymbolXCOFF.h.
References llvm::MCSymbol::IsExternal.
setEHInfo()
void llvm::MCSymbolXCOFF::setEHInfo () const inline
Definition at line 76 of file MCSymbolXCOFF.h.
References llvm::MCSymbol::modifyFlags().
Referenced by llvm::TargetLoweringObjectFileXCOFF::getEHInfoTableSymbol().
setExternal()
void llvm::MCSymbolXCOFF::setExternal (bool Value) const inline
Definition at line 41 of file MCSymbolXCOFF.h.
References llvm::MCSymbol::IsExternal, and llvm::MCSymbol::Value.
setPerSymbolCodeModel()
void llvm::MCSymbolXCOFF::setPerSymbolCodeModel (MCSymbolXCOFF::CodeModel Model) inline
Definition at line 86 of file MCSymbolXCOFF.h.
Referenced by setOptionalCodeModel().
setRepresentedCsect()
void MCSymbolXCOFF::setRepresentedCsect (MCSectionXCOFF * C)
Definition at line 22 of file MCSymbolXCOFF.cpp.
References assert(), llvm::CallingConv::C, and getSymbolTableName().
setStorageClass()
void llvm::MCSymbolXCOFF::setStorageClass (XCOFF::StorageClass SC) inline
Definition at line 42 of file MCSymbolXCOFF.h.
setSymbolTableName()
void llvm::MCSymbolXCOFF::setSymbolTableName (StringRef STN) inline
Definition at line 63 of file MCSymbolXCOFF.h.
setVisibilityType()
void llvm::MCSymbolXCOFF::setVisibilityType (XCOFF::VisibilityType SVT) inline
Definition at line 57 of file MCSymbolXCOFF.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSymbolXCOFF.h
lib/MC/MCSymbolXCOFF.cpp