LLVM: llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, jitlink::JITLinkMemoryManager::FinalizedAlloc > Class Reference
llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, jitlink::JITLinkMemoryManager::FinalizedAlloc > Class Reference
FIXME: This specialization should be moved into TargetProcessControlTypes.h (or wherever those types get merged to) once ORC depends on JITLink.
#include "llvm/ExecutionEngine/Orc/EPCGenericJITLinkMemoryManager.h"
Static Public Member Functions
static size_t size (const jitlink::JITLinkMemoryManager::FinalizedAlloc &FA)
static bool serialize (SPSOutputBuffer &OB, const jitlink::JITLinkMemoryManager::FinalizedAlloc &FA)
static bool deserialize (SPSInputBuffer &IB, jitlink::JITLinkMemoryManager::FinalizedAlloc &FA)
Detailed Description
FIXME: This specialization should be moved into TargetProcessControlTypes.h (or wherever those types get merged to) once ORC depends on JITLink.
Definition at line 72 of file EPCGenericJITLinkMemoryManager.h.
Member Function Documentation
deserialize()
bool llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, jitlink::JITLinkMemoryManager::FinalizedAlloc >::deserialize (SPSInputBuffer & IB, jitlink::JITLinkMemoryManager::FinalizedAlloc & FA) inline static
Definition at line 86 of file EPCGenericJITLinkMemoryManager.h.
References A().
serialize()
bool llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, jitlink::JITLinkMemoryManager::FinalizedAlloc >::serialize (SPSOutputBuffer & OB, const jitlink::JITLinkMemoryManager::FinalizedAlloc & FA) inline static
Definition at line 80 of file EPCGenericJITLinkMemoryManager.h.
References llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::getAddress().
size()
size_t llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, jitlink::JITLinkMemoryManager::FinalizedAlloc >::size (const jitlink::JITLinkMemoryManager::FinalizedAlloc & FA) inline static
Definition at line 75 of file EPCGenericJITLinkMemoryManager.h.
References llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::getAddress().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/EPCGenericJITLinkMemoryManager.h