LLVM: MCCOFFSectionNumberTargetExpr Class Reference
MCCOFFSectionNumberTargetExpr Class Reference final
MCExpr that represents the physical number for the sections that contains a symbol.
Public Member Functions
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
LLVM_ABI void dump () const
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res) const
Try to evaluate the expression to an absolute value.
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
LLVM_ABI bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
LLVM_ABI bool evaluateKnownAbsolute (int64_t &Res, const MCAssembler &Asm) const
Aggressive variant of evaluateAsRelocatable when relocations are unavailable (e.g.
LLVM_ABI bool evaluateAsRelocatable (MCValue &Res, const MCAssembler *Asm) const
Try to evaluate the expression to a relocatable value, i.e.
LLVM_ABI bool evaluateAsValue (MCValue &Res, const MCAssembler &Asm) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
LLVM_ABI MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static MCCOFFSectionNumberTargetExpr * create (const MCSymbol &SectionSymbol, const WinCOFFObjectWriter &Writer, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCExpr
static LLVM_ABI bool evaluateSymbolicAdd (const MCAssembler *, bool, const MCValue &, const MCValue &, MCValue &)
Additional Inherited Members
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary , Constant , SymbolRef , Unary ,
Specifier , Target
}
Protected Types inherited from llvm::MCExpr
using Spec = uint16_t
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
LLVM_ABI bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, bool InSet) const
unsigned getSubclassData () const
Detailed Description
MCExpr that represents the physical number for the sections that contains a symbol.
Definition at line 47 of file MCWinCOFFStreamer.cpp.
Member Function Documentation
create()
MCCOFFSectionNumberTargetExpr * MCCOFFSectionNumberTargetExpr::create (const MCSymbol & SectionSymbol, const WinCOFFObjectWriter & Writer, MCContext & Ctx) inline static
Definition at line 57 of file MCWinCOFFStreamer.cpp.
Referenced by llvm::MCWinCOFFStreamer::emitCOFFSecNumber().
evaluateAsRelocatableImpl()
bool MCCOFFSectionNumberTargetExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAssembler * Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 67 of file MCWinCOFFStreamer.cpp.
References assert(), and llvm::MCValue::get().
findAssociatedFragment()
MCFragment * MCCOFFSectionNumberTargetExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 80 of file MCWinCOFFStreamer.cpp.
printImpl()
void MCCOFFSectionNumberTargetExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 62 of file MCWinCOFFStreamer.cpp.
visitUsedExpr()
void MCCOFFSectionNumberTargetExpr::visitUsedExpr (MCStreamer & Streamer) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 76 of file MCWinCOFFStreamer.cpp.
The documentation for this class was generated from the following file:
lib/MC/MCWinCOFFStreamer.cpp