LLVM: llvm::MCNopsFragment Class Reference
llvm::MCNopsFragment Class Reference
#include "llvm/MC/MCSection.h"
Public Member Functions
MCNopsFragment (int64_t NumBytes, int64_t ControlledNopLength, SMLoc L, const MCSubtargetInfo &STI)
int64_t getNumBytes () const
int64_t getControlledNopLength () const
SMLoc getLoc () const
Public Member Functions inherited from llvm::MCFragment
LLVM_ABI MCFragment (FragmentType Kind=MCFragment::FT_Data, bool HasInstructions=false)
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
MCFragment * getNext () const
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
LLVM_ABI const MCSymbol * getAtom () const
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it?
LLVM_ABI void dump () const
const MCSubtargetInfo * getSubtargetInfo () const
Retrieve the MCSubTargetInfo in effect when the instruction was encoded.
void setHasInstructions (const MCSubtargetInfo &STI)
Record that the fragment contains instructions with the MCSubtargetInfo in effect when the instruction was encoded.
bool isLinkerRelaxable () const
void setLinkerRelaxable ()
bool getAllowAutoPadding () const
void setAllowAutoPadding (bool V)
MutableArrayRef< char > getContents ()
ArrayRef< char > getContents () const
LLVM_ABI void setVarContents (ArrayRef< char > Contents)
void clearVarContents ()
MutableArrayRef< char > getVarContents ()
ArrayRef< char > getVarContents () const
size_t getFixedSize () const
size_t getVarSize () const
size_t getSize () const
void clearFixups ()
LLVM_ABI void addFixup (MCFixup Fixup)
LLVM_ABI void appendFixups (ArrayRef< MCFixup > Fixups)
MutableArrayRef< MCFixup > getFixups ()
ArrayRef< MCFixup > getFixups () const
LLVM_ABI void setVarFixups (ArrayRef< MCFixup > Fixups)
void clearVarFixups ()
MutableArrayRef< MCFixup > getVarFixups ()
ArrayRef< MCFixup > getVarFixups () const
unsigned getOpcode () const
ArrayRef< MCOperand > getOperands () const
MCInst getInst () const
void setInst (const MCInst &Inst)
void makeAlign (Align Alignment, int64_t Fill, uint8_t FillLen, unsigned MaxBytesToEmit)
Align getAlignment () const
int64_t getAlignFill () const
uint8_t getAlignFillLen () const
unsigned getAlignMaxBytesToEmit () const
bool hasAlignEmitNops () const
void makeLEB (bool IsSigned, const MCExpr *Value)
const MCExpr & getLEBValue () const
void setLEBValue (const MCExpr *Expr)
bool isLEBSigned () const
const MCExpr & getDwarfAddrDelta () const
void setDwarfAddrDelta (const MCExpr *E)
int64_t getDwarfLineDelta () const
void setDwarfLineDelta (int64_t LineDelta)
const MCExpr & getSFrameAddrDelta () const
void setSFrameAddrDelta (const MCExpr *E)
MCFragment * getSFrameFDE () const
void setSFrameFDE (MCFragment *F)
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Data , FT_Relaxable , FT_Align , FT_Fill ,
FT_LEB , FT_Nops , FT_Org , FT_Dwarf ,
FT_DwarfFrame , FT_SFrame , FT_BoundaryAlign , FT_SymbolId ,
FT_CVInlineLines , FT_CVDefRange
}
Protected Attributes inherited from llvm::MCFragment
const MCSubtargetInfo * STI = nullptr
Detailed Description
Definition at line 358 of file MCSection.h.
Constructor & Destructor Documentation
MCNopsFragment()
llvm::MCNopsFragment::MCNopsFragment (int64_t NumBytes, int64_t ControlledNopLength, SMLoc L, const MCSubtargetInfo & STI) inline
Definition at line 368 of file MCSection.h.
References llvm::MCFragment::FT_Nops, llvm::MCFragment::MCFragment(), and llvm::MCFragment::STI.
Member Function Documentation
classof()
bool llvm::MCNopsFragment::classof (const MCFragment * F) inline static
Definition at line 380 of file MCSection.h.
References F, llvm::MCFragment::FT_Nops, and llvm::MCFragment::MCFragment().
getControlledNopLength()
int64_t llvm::MCNopsFragment::getControlledNopLength () const inline
Definition at line 376 of file MCSection.h.
Referenced by writeFragment().
getLoc()
SMLoc llvm::MCNopsFragment::getLoc () const inline
Definition at line 378 of file MCSection.h.
Referenced by writeFragment().
getNumBytes()
int64_t llvm::MCNopsFragment::getNumBytes () const inline
Definition at line 375 of file MCSection.h.
Referenced by writeFragment().
The documentation for this class was generated from the following file:
include/llvm/MC/MCSection.h