LLVM: llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator Class Reference
llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator Class Reference
Public Member Functions
PHI_iterator (DbgSSAPhi *P)
PHI_iterator (DbgSSAPhi *P, bool)
PHI_iterator & operator++ ()
bool operator== (const PHI_iterator &X) const
bool operator!= (const PHI_iterator &X) const
DbgValueDef getIncomingValue ()
DbgSSABlock * getIncomingBlock ()
Detailed Description
Definition at line 136 of file DebugSSAUpdater.cpp.
Constructor & Destructor Documentation
PHI_iterator() [1/2]
llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::PHI_iterator (DbgSSAPhi * P) inline explicit
Definition at line 142 of file DebugSSAUpdater.cpp.
References P.
Referenced by operator!=(), operator++(), and operator==().
PHI_iterator() [2/2]
llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::PHI_iterator (DbgSSAPhi * P, bool) inline
Definition at line 144 of file DebugSSAUpdater.cpp.
References P.
Member Function Documentation
getIncomingBlock()
DbgSSABlock * llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::getIncomingBlock () inline
Definition at line 155 of file DebugSSAUpdater.cpp.
getIncomingValue()
DbgValueDef llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::getIncomingValue () inline
Definition at line 154 of file DebugSSAUpdater.cpp.
operator!=()
bool llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::operator!= (const PHI_iterator & X) const inline
Definition at line 152 of file DebugSSAUpdater.cpp.
References llvm::operator==(), PHI_iterator(), and X.
operator++()
PHI_iterator & llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::operator++ () inline
Definition at line 147 of file DebugSSAUpdater.cpp.
References PHI_iterator().
operator==()
bool llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator::operator== (const PHI_iterator & X) const inline
Definition at line 151 of file DebugSSAUpdater.cpp.
References PHI_iterator(), and X.
The documentation for this class was generated from the following file:
lib/Transforms/Utils/DebugSSAUpdater.cpp