LLVM: llvm::sandboxir::GlobalValue Class Reference
llvm::sandboxir::GlobalValue Class Reference
#include "llvm/SandboxIR/Constant.h"
Public Types
using LinkageTypes = llvm::GlobalValue::LinkageTypes
using UnnamedAddr = llvm::GlobalValue::UnnamedAddr
using VisibilityTypes = llvm::GlobalValue::VisibilityTypes
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Public Member Functions
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
LLVM_ABI void setUnnamedAddr (UnnamedAddr V)
bool hasComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
LLVM_ABI void setVisibility (VisibilityTypes V)
Public Member Functions inherited from llvm::sandboxir::Constant
sandboxir::Context & getParent () const
unsigned getUseOperandNo (const Use &Use) const override
\Returns the operand index of Use.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
Static Public Member Functions inherited from llvm::sandboxir::Constant
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Protected Member Functions
GlobalValue (ClassID ID, llvm::GlobalValue *C, Context &Ctx)
Protected Member Functions inherited from llvm::sandboxir::Constant
Constant (llvm::Constant *C, sandboxir::Context &SBCtx)
Constant (ClassID ID, llvm::Constant *C, sandboxir::Context &SBCtx)
Use getOperandUseInternal (unsigned OpIdx, bool Verify) const override
\Returns the Use for the OpIdx'th operand.
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Friends
class Context
Additional Inherited Members
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 887 of file Constant.h.
Member Typedef Documentation
LinkageTypes
using llvm::sandboxir::GlobalValue::LinkageTypes = llvm::GlobalValue::LinkageTypes
Definition at line 894 of file Constant.h.
UnnamedAddr
using llvm::sandboxir::GlobalValue::UnnamedAddr = llvm::GlobalValue::UnnamedAddr
Definition at line 924 of file Constant.h.
VisibilityTypes
using llvm::sandboxir::GlobalValue::VisibilityTypes = llvm::GlobalValue::VisibilityTypes
Definition at line 938 of file Constant.h.
Constructor & Destructor Documentation
GlobalValue()
llvm::sandboxir::GlobalValue::GlobalValue (ClassID ID, llvm::GlobalValue * C, Context & Ctx) inline protected
Definition at line 889 of file Constant.h.
References llvm::CallingConv::C, llvm::sandboxir::Constant::Constant(), Context, and llvm::sandboxir::Value::Ctx.
Referenced by llvm::sandboxir::GlobalObject::GlobalObject().
Member Function Documentation
classof()
bool llvm::sandboxir::GlobalValue::classof (const sandboxir::Value * From) inline static
For isa/dyn_cast.
Definition at line 896 of file Constant.h.
References llvm::sandboxir::Value::getSubclassID().
getAddressSpace()
unsigned llvm::sandboxir::GlobalValue::getAddressSpace () const inline
Definition at line 908 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getMinUnnamedAddr()
UnnamedAddr llvm::sandboxir::GlobalValue::getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B) inline static
Definition at line 931 of file Constant.h.
References A(), B(), and llvm::GlobalValue::getMinUnnamedAddr().
getUnnamedAddr()
UnnamedAddr llvm::sandboxir::GlobalValue::getUnnamedAddr () const inline
Definition at line 926 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setUnnamedAddr().
getVisibility()
VisibilityTypes llvm::sandboxir::GlobalValue::getVisibility () const inline
Definition at line 939 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setVisibility().
hasAtLeastLocalUnnamedAddr()
bool llvm::sandboxir::GlobalValue::hasAtLeastLocalUnnamedAddr () const inline
Returns true if this value's address is not significant in this module.
This attribute is intended to be used only by the code generator and LTO to allow the linker to decide whether the global needs to be in the symbol table. It should probably not be used in optimizations, as the value may have uses outside the module; use hasGlobalUnnamedAddr() instead.
Definition at line 920 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasComdat()
bool llvm::sandboxir::GlobalValue::hasComdat () const inline
Definition at line 935 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasDefaultVisibility()
bool llvm::sandboxir::GlobalValue::hasDefaultVisibility () const inline
Definition at line 942 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasGlobalUnnamedAddr()
bool llvm::sandboxir::GlobalValue::hasGlobalUnnamedAddr () const inline
Definition at line 911 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasHiddenVisibility()
bool llvm::sandboxir::GlobalValue::hasHiddenVisibility () const inline
Definition at line 945 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
hasProtectedVisibility()
bool llvm::sandboxir::GlobalValue::hasProtectedVisibility () const inline
Definition at line 948 of file Constant.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
setUnnamedAddr()
void llvm::sandboxir::GlobalValue::setUnnamedAddr (UnnamedAddr V)
Definition at line 386 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, getUnnamedAddr(), setUnnamedAddr(), and llvm::sandboxir::Value::Val.
Referenced by setUnnamedAddr().
setVisibility()
void llvm::sandboxir::GlobalValue::setVisibility (VisibilityTypes V)
Definition at line 393 of file Constant.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, getVisibility(), setVisibility(), and llvm::sandboxir::Value::Val.
Referenced by setVisibility().
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 891 of file Constant.h.
References Context.
Referenced by Context, and GlobalValue().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Constant.h
lib/SandboxIR/Constant.cpp