LLVM: llvm::cas::ObjectHandle Class Reference
llvm::cas::ObjectHandle Class Reference
Handle to a loaded object in a ObjectStore instance.
#include "llvm/CAS/CASReference.h"
Public Member Functions
void print (raw_ostream &OS) const
Print internal ref and/or CASID. Only suitable for debugging.
LLVM_DUMP_METHOD void dump () const
Public Member Functions inherited from llvm::cas::ReferenceBase
uint64_t getInternalRef (const ObjectStore &ExpectedCAS) const
Get an internal reference.
unsigned getDenseMapHash () const
Helper functions for DenseMapInfo.
bool isDenseMapEmpty () const
bool isDenseMapTombstone () const
bool isDenseMapSentinel () const
Friends
class ObjectStore
class ReferenceBase
bool operator== (const ObjectHandle &LHS, const ObjectHandle &RHS)
bool operator!= (const ObjectHandle &LHS, const ObjectHandle &RHS)
Additional Inherited Members
Protected Member Functions inherited from llvm::cas::ReferenceBase
void print (raw_ostream &OS, const ObjectHandle &This) const
void print (raw_ostream &OS, const ObjectRef &This) const
bool hasSameInternalRef (const ReferenceBase &RHS) const
ReferenceBase (const ObjectStore *CAS, uint64_t InternalRef, bool IsHandle)
ReferenceBase (DenseMapEmptyTag)
ReferenceBase (DenseMapTombstoneTag)
Static Protected Member Functions inherited from llvm::cas::ReferenceBase
static constexpr uint64_t getDenseMapEmptyRef ()
static constexpr uint64_t getDenseMapTombstoneRef ()
Detailed Description
Handle to a loaded object in a ObjectStore instance.
ObjectHandle encapulates a loaded object in the CAS. You need one of these to inspect the content of an object: to look at its stored data and references.
Definition at line 150 of file CASReference.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void ObjectHandle::dump () const
Definition at line 26 of file ObjectStore.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
print()
void llvm::cas::ObjectHandle::print (raw_ostream & OS) const inline
Print internal ref and/or CASID. Only suitable for debugging.
Definition at line 160 of file CASReference.h.
References llvm::cas::ReferenceBase::print().
Referenced by dump().
Friends And Related Symbol Documentation
ObjectStore
friend class ObjectStore friend
Definition at line 165 of file CASReference.h.
References ObjectStore.
Referenced by ObjectStore, and ReferenceBase.
operator!=
bool operator!= (const ObjectHandle & LHS, const ObjectHandle & RHS) friend
Definition at line 155 of file CASReference.h.
References LHS, and RHS.
operator==
bool operator== (const ObjectHandle & LHS, const ObjectHandle & RHS) friend
Definition at line 152 of file CASReference.h.
References LHS, and RHS.
ReferenceBase
friend class ReferenceBase friend
Definition at line 166 of file CASReference.h.
References ObjectStore, ReferenceBase, and llvm::cas::ReferenceBase::ReferenceBase().
Referenced by ReferenceBase.
The documentation for this class was generated from the following files:
include/llvm/CAS/CASReference.h
lib/CAS/ObjectStore.cpp