LLVM: llvm::ReassociatePass Class Reference
llvm::ReassociatePass Class Reference
Reassociate commutative expressions.
#include "llvm/Transforms/Scalar/Reassociate.h"
Classes
struct PairMapValue
Public Types
using OrderedSet
Public Member Functions
LLVM_ABI PreservedAnalyses run (Function &F, FunctionAnalysisManager &)
Public Member Functions inherited from llvm::PassInfoMixin< ReassociatePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Protected Attributes
DenseMap< BasicBlock *, unsigned > RankMap
DenseMap< AssertingVH< Value >, unsigned > ValueRankMap
OrderedSet RedoInsts
DenseMap< std::pair< Value *, Value * >, PairMapValue > PairMap [NumBinaryOps]
bool MadeChange
Static Protected Attributes
static const unsigned GlobalReassociateLimit = 10
static const unsigned NumBinaryOps
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ReassociatePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Reassociate commutative expressions.
Definition at line 74 of file Reassociate.h.
Member Typedef Documentation
OrderedSet
using llvm::ReassociatePass::OrderedSet
Initial value:
SetVector<AssertingVH<Instruction>, std::deque<AssertingVH<Instruction>>>
Definition at line 76 of file Reassociate.h.
Member Function Documentation
run()
PreservedAnalyses ReassociatePass::run (Function & F, FunctionAnalysisManager &)
Definition at line 2549 of file Reassociate.cpp.
References llvm::PreservedAnalyses::all(), assert(), llvm::SetVector< T, Vector, Set, N >::empty(), F, I, II, llvm::isInstructionTriviallyDead(), MadeChange, PairMap, llvm::SetVector< T, Vector, Set, N >::pop_back_val(), llvm::PreservedAnalyses::preserveSet(), RankMap, RedoInsts, and ValueRankMap.
Member Data Documentation
GlobalReassociateLimit
const unsigned llvm::ReassociatePass::GlobalReassociateLimit = 10 static protected
Definition at line 85 of file Reassociate.h.
MadeChange
bool llvm::ReassociatePass::MadeChange protected
Definition at line 97 of file Reassociate.h.
Referenced by run().
NumBinaryOps
const unsigned llvm::ReassociatePass::NumBinaryOps static protected
Initial value:
                               =
Instruction::BinaryOpsEnd - Instruction::BinaryOpsBegin
Definition at line 86 of file Reassociate.h.
PairMap
DenseMap<std::pair<Value *, Value *>, PairMapValue> llvm::ReassociatePass::PairMap[NumBinaryOps] protected
Definition at line 95 of file Reassociate.h.
Referenced by run().
RankMap
DenseMap<BasicBlock *, unsigned> llvm::ReassociatePass::RankMap protected
Definition at line 80 of file Reassociate.h.
Referenced by run().
RedoInsts
OrderedSet llvm::ReassociatePass::RedoInsts protected
Definition at line 82 of file Reassociate.h.
Referenced by run().
ValueRankMap
DenseMap<AssertingVH<Value>, unsigned> llvm::ReassociatePass::ValueRankMap protected
Definition at line 81 of file Reassociate.h.
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/Reassociate.h
lib/Transforms/Scalar/Reassociate.cpp