LLVM: llvm::ProfileAnnotator Class Reference
llvm::ProfileAnnotator Class Reference
#include "llvm/Analysis/CtxProfAnalysis.h"
Public Member Functions
LLVM_ABI ProfileAnnotator (const Function &F, ArrayRef< uint64_t > RawCounters)
LLVM_ABI uint64_t getBBCount (const BasicBlock &BB) const
LLVM_ABI bool getSelectInstrProfile (SelectInst &SI, uint64_t &TrueCount, uint64_t &FalseCount) const
LLVM_ABI bool getOutgoingBranchWeights (BasicBlock &BB, SmallVectorImpl< uint64_t > &Profile, uint64_t &MaxCount) const
LLVM_ABI ~ProfileAnnotator ()
Detailed Description
Definition at line 168 of file CtxProfAnalysis.h.
Constructor & Destructor Documentation
ProfileAnnotator()
ProfileAnnotator::ProfileAnnotator (const Function & F, ArrayRef< uint64_t > RawCounters)
Definition at line 367 of file CtxProfAnalysis.cpp.
References F.
~ProfileAnnotator()
ProfileAnnotator::~ProfileAnnotator () default
References LLVM_ABI.
Member Function Documentation
getBBCount()
uint64_t ProfileAnnotator::getBBCount (const BasicBlock & BB) const
Definition at line 373 of file CtxProfAnalysis.cpp.
getOutgoingBranchWeights()
bool ProfileAnnotator::getOutgoingBranchWeights (BasicBlock & BB, SmallVectorImpl< uint64_t > & Profile, uint64_t & MaxCount) const
Definition at line 400 of file CtxProfAnalysis.cpp.
References llvm::BasicBlock::getTerminator(), Profile, Size, and llvm::succ_size().
getSelectInstrProfile()
bool ProfileAnnotator::getSelectInstrProfile (SelectInst & SI, uint64_t & TrueCount, uint64_t & FalseCount) const
Definition at line 377 of file CtxProfAnalysis.cpp.
References assert(), llvm::Counters, and llvm::CtxProfAnalysis::getSelectInstrumentation().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CtxProfAnalysis.h
lib/Analysis/CtxProfAnalysis.cpp