LLVM: llvm::codeview::SymbolRecord Class Reference
llvm::codeview::SymbolRecord Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
SymbolRecordKind getKind () const
Public Attributes
SymbolRecordKind Kind
Protected Member Functions
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 30 of file SymbolRecord.h.
Constructor & Destructor Documentation
SymbolRecord()
llvm::codeview::SymbolRecord::SymbolRecord (SymbolRecordKind Kind) inline explicit protected
Definition at line 32 of file SymbolRecord.h.
References Kind.
Referenced by llvm::codeview::AnnotationSym::AnnotationSym(), llvm::codeview::AnnotationSym::AnnotationSym(), llvm::codeview::BlockSym::BlockSym(), llvm::codeview::BlockSym::BlockSym(), llvm::codeview::BPRelativeSym::BPRelativeSym(), llvm::codeview::BPRelativeSym::BPRelativeSym(), llvm::codeview::BuildInfoSym::BuildInfoSym(), llvm::codeview::BuildInfoSym::BuildInfoSym(), llvm::codeview::CallerSym::CallerSym(), llvm::codeview::CallerSym::CallerSym(), llvm::codeview::CallSiteInfoSym::CallSiteInfoSym(), llvm::codeview::CallSiteInfoSym::CallSiteInfoSym(), llvm::codeview::CoffGroupSym::CoffGroupSym(), llvm::codeview::CoffGroupSym::CoffGroupSym(), llvm::codeview::Compile2Sym::Compile2Sym(), llvm::codeview::Compile2Sym::Compile2Sym(), llvm::codeview::Compile3Sym::Compile3Sym(), llvm::codeview::Compile3Sym::Compile3Sym(), llvm::codeview::Compile3Sym::Compile3Sym(), llvm::codeview::ConstantSym::ConstantSym(), llvm::codeview::ConstantSym::ConstantSym(), llvm::codeview::DataSym::DataSym(), llvm::codeview::DataSym::DataSym(), llvm::codeview::DefRangeFramePointerRelFullScopeSym::DefRangeFramePointerRelFullScopeSym(), llvm::codeview::DefRangeFramePointerRelFullScopeSym::DefRangeFramePointerRelFullScopeSym(), llvm::codeview::DefRangeFramePointerRelSym::DefRangeFramePointerRelSym(), llvm::codeview::DefRangeFramePointerRelSym::DefRangeFramePointerRelSym(), llvm::codeview::DefRangeRegisterRelSym::DefRangeRegisterRelSym(), llvm::codeview::DefRangeRegisterRelSym::DefRangeRegisterRelSym(), llvm::codeview::DefRangeRegisterSym::DefRangeRegisterSym(), llvm::codeview::DefRangeRegisterSym::DefRangeRegisterSym(), llvm::codeview::DefRangeSubfieldRegisterSym::DefRangeSubfieldRegisterSym(), llvm::codeview::DefRangeSubfieldRegisterSym::DefRangeSubfieldRegisterSym(), llvm::codeview::DefRangeSubfieldSym::DefRangeSubfieldSym(), llvm::codeview::DefRangeSubfieldSym::DefRangeSubfieldSym(), llvm::codeview::DefRangeSym::DefRangeSym(), llvm::codeview::DefRangeSym::DefRangeSym(), llvm::codeview::EnvBlockSym::EnvBlockSym(), llvm::codeview::EnvBlockSym::EnvBlockSym(), llvm::codeview::ExportSym::ExportSym(), llvm::codeview::ExportSym::ExportSym(), llvm::codeview::FileStaticSym::FileStaticSym(), llvm::codeview::FileStaticSym::FileStaticSym(), llvm::codeview::FrameCookieSym::FrameCookieSym(), llvm::codeview::FrameCookieSym::FrameCookieSym(), llvm::codeview::FrameProcSym::FrameProcSym(), llvm::codeview::FrameProcSym::FrameProcSym(), llvm::codeview::HeapAllocationSiteSym::HeapAllocationSiteSym(), llvm::codeview::HeapAllocationSiteSym::HeapAllocationSiteSym(), llvm::codeview::HotPatchFuncSym::HotPatchFuncSym(), llvm::codeview::HotPatchFuncSym::HotPatchFuncSym(), llvm::codeview::InlineSiteSym::InlineSiteSym(), llvm::codeview::InlineSiteSym::InlineSiteSym(), llvm::codeview::JumpTableSym::JumpTableSym(), llvm::codeview::JumpTableSym::JumpTableSym(), llvm::codeview::LabelSym::LabelSym(), llvm::codeview::LabelSym::LabelSym(), llvm::codeview::LocalSym::LocalSym(), llvm::codeview::LocalSym::LocalSym(), llvm::codeview::ObjNameSym::ObjNameSym(), llvm::codeview::ObjNameSym::ObjNameSym(), llvm::codeview::ObjNameSym::ObjNameSym(), llvm::codeview::ProcRefSym::ProcRefSym(), llvm::codeview::ProcRefSym::ProcRefSym(), llvm::codeview::ProcSym::ProcSym(), llvm::codeview::ProcSym::ProcSym(), llvm::codeview::PublicSym32::PublicSym32(), llvm::codeview::PublicSym32::PublicSym32(), llvm::codeview::PublicSym32::PublicSym32(), llvm::codeview::RegisterSym::RegisterSym(), llvm::codeview::RegisterSym::RegisterSym(), llvm::codeview::RegRelativeSym::RegRelativeSym(), llvm::codeview::RegRelativeSym::RegRelativeSym(), llvm::codeview::ScopeEndSym::ScopeEndSym(), llvm::codeview::ScopeEndSym::ScopeEndSym(), llvm::codeview::SectionSym::SectionSym(), llvm::codeview::SectionSym::SectionSym(), llvm::codeview::ThreadLocalDataSym::ThreadLocalDataSym(), llvm::codeview::ThreadLocalDataSym::ThreadLocalDataSym(), llvm::codeview::Thunk32Sym::Thunk32Sym(), llvm::codeview::Thunk32Sym::Thunk32Sym(), llvm::codeview::TrampolineSym::TrampolineSym(), llvm::codeview::TrampolineSym::TrampolineSym(), llvm::codeview::UDTSym::UDTSym(), llvm::codeview::UDTSym::UDTSym(), llvm::codeview::UsingNamespaceSym::UsingNamespaceSym(), and llvm::codeview::UsingNamespaceSym::UsingNamespaceSym().
Member Function Documentation
getKind()
SymbolRecordKind llvm::codeview::SymbolRecord::getKind () const inline
Definition at line 35 of file SymbolRecord.h.
References Kind.
Member Data Documentation
Kind
SymbolRecordKind llvm::codeview::SymbolRecord::Kind
Definition at line 37 of file SymbolRecord.h.
Referenced by llvm::codeview::AnnotationSym::AnnotationSym(), llvm::codeview::BlockSym::BlockSym(), llvm::codeview::BPRelativeSym::BPRelativeSym(), llvm::codeview::BuildInfoSym::BuildInfoSym(), llvm::codeview::CallerSym::CallerSym(), llvm::codeview::CallerSym::CallerSym(), llvm::codeview::CallSiteInfoSym::CallSiteInfoSym(), llvm::codeview::CoffGroupSym::CoffGroupSym(), llvm::codeview::CoffGroupSym::CoffGroupSym(), llvm::codeview::Compile2Sym::Compile2Sym(), llvm::codeview::Compile3Sym::Compile3Sym(), llvm::codeview::ConstantSym::ConstantSym(), llvm::codeview::DataSym::DataSym(), llvm::codeview::DefRangeFramePointerRelFullScopeSym::DefRangeFramePointerRelFullScopeSym(), llvm::codeview::DefRangeFramePointerRelSym::DefRangeFramePointerRelSym(), llvm::codeview::DefRangeRegisterRelSym::DefRangeRegisterRelSym(), llvm::codeview::DefRangeRegisterSym::DefRangeRegisterSym(), llvm::codeview::DefRangeSubfieldRegisterSym::DefRangeSubfieldRegisterSym(), llvm::codeview::DefRangeSubfieldSym::DefRangeSubfieldSym(), llvm::codeview::DefRangeSym::DefRangeSym(), llvm::codeview::EnvBlockSym::EnvBlockSym(), llvm::codeview::ExportSym::ExportSym(), llvm::codeview::FileStaticSym::FileStaticSym(), llvm::codeview::FrameCookieSym::FrameCookieSym(), llvm::codeview::FrameProcSym::FrameProcSym(), getKind(), llvm::codeview::HeapAllocationSiteSym::HeapAllocationSiteSym(), llvm::codeview::HotPatchFuncSym::HotPatchFuncSym(), llvm::codeview::InlineSiteSym::InlineSiteSym(), llvm::codeview::JumpTableSym::JumpTableSym(), llvm::codeview::LabelSym::LabelSym(), llvm::codeview::LocalSym::LocalSym(), llvm::codeview::ObjNameSym::ObjNameSym(), llvm::codeview::ProcRefSym::ProcRefSym(), llvm::codeview::ProcSym::ProcSym(), llvm::codeview::ProcSym::ProcSym(), llvm::codeview::PublicSym32::PublicSym32(), llvm::codeview::RegisterSym::RegisterSym(), llvm::codeview::RegRelativeSym::RegRelativeSym(), llvm::codeview::ScopeEndSym::ScopeEndSym(), llvm::codeview::ScopeEndSym::ScopeEndSym(), llvm::codeview::SectionSym::SectionSym(), llvm::codeview::SectionSym::SectionSym(), SymbolRecord(), llvm::codeview::ThreadLocalDataSym::ThreadLocalDataSym(), llvm::codeview::Thunk32Sym::Thunk32Sym(), llvm::codeview::Thunk32Sym::Thunk32Sym(), llvm::codeview::TrampolineSym::TrampolineSym(), llvm::codeview::TrampolineSym::TrampolineSym(), llvm::codeview::UDTSym::UDTSym(), and llvm::codeview::UsingNamespaceSym::UsingNamespaceSym().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h