LLVM: llvm::CodeGenData Class Reference
llvm::CodeGenData Class Reference
#include "llvm/CGData/CodeGenData.h"
Public Member Functions
~CodeGenData ()=default
bool hasOutlinedHashTree ()
Returns true if we have a valid outlined hash tree.
bool hasStableFunctionMap ()
const OutlinedHashTree * getOutlinedHashTree ()
Returns the outlined hash tree.
const StableFunctionMap * getStableFunctionMap ()
bool emitCGData ()
Returns true if we should write codegen data.
void publishOutlinedHashTree (std::unique_ptr< OutlinedHashTree > HashTree)
Publish the (globally) merged or read outlined hash tree.
void publishStableFunctionMap (std::unique_ptr< StableFunctionMap > FunctionMap)
Static Public Member Functions
static LLVM_ABI CodeGenData & getInstance ()
Detailed Description
Definition at line 112 of file CodeGenData.h.
Constructor & Destructor Documentation
~CodeGenData()
llvm::CodeGenData::~CodeGenData () default
References LLVM_ABI.
Member Function Documentation
emitCGData()
bool llvm::CodeGenData::emitCGData () inline
Returns true if we should write codegen data.
Definition at line 154 of file CodeGenData.h.
Referenced by llvm::cgdata::emitCGData().
getInstance()
CodeGenData & llvm::CodeGenData::getInstance () static
Definition at line 147 of file CodeGenData.cpp.
References CodeGenDataGenerate, llvm::CodeGenDataThinLTOTwoRounds, CodeGenDataUsePath, llvm::CodeGenDataReader::create(), llvm::vfs::getRealFileSystem(), and llvm::cgdata::warn().
Referenced by llvm::cgdata::emitCGData(), llvm::cgdata::getOutlinedHashTree(), llvm::cgdata::getStableFunctionMap(), llvm::cgdata::hasOutlinedHashTree(), llvm::cgdata::hasStableFunctionMap(), llvm::cgdata::publishOutlinedHashTree(), and llvm::cgdata::publishStableFunctionMap().
getOutlinedHashTree()
const OutlinedHashTree * llvm::CodeGenData::getOutlinedHashTree () inline
Returns the outlined hash tree.
This can be globally used in a read-only manner.
Definition at line 146 of file CodeGenData.h.
Referenced by llvm::cgdata::getOutlinedHashTree().
getStableFunctionMap()
const StableFunctionMap * llvm::CodeGenData::getStableFunctionMap () inline
Definition at line 149 of file CodeGenData.h.
Referenced by llvm::cgdata::getStableFunctionMap().
hasOutlinedHashTree()
bool llvm::CodeGenData::hasOutlinedHashTree () inline
Returns true if we have a valid outlined hash tree.
Definition at line 137 of file CodeGenData.h.
Referenced by llvm::cgdata::hasOutlinedHashTree().
hasStableFunctionMap()
bool llvm::CodeGenData::hasStableFunctionMap () inline
Definition at line 140 of file CodeGenData.h.
Referenced by llvm::cgdata::hasStableFunctionMap().
publishOutlinedHashTree()
void llvm::CodeGenData::publishOutlinedHashTree (std::unique_ptr< OutlinedHashTree > HashTree) inline
Publish the (globally) merged or read outlined hash tree.
Definition at line 157 of file CodeGenData.h.
Referenced by llvm::cgdata::publishOutlinedHashTree().
publishStableFunctionMap()
void llvm::CodeGenData::publishStableFunctionMap (std::unique_ptr< StableFunctionMap > FunctionMap) inline
Definition at line 163 of file CodeGenData.h.
Referenced by llvm::cgdata::publishStableFunctionMap().
The documentation for this class was generated from the following files:
include/llvm/CGData/CodeGenData.h
lib/CGData/CodeGenData.cpp