LLVM: llvm::DIBasicType Class Reference
llvm::DIBasicType Class Reference
Basic type, like 'int' or 'float'.
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
enum class Signedness { Signed , Unsigned }
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, StringRef Name),(Tag, Name, 0, 0, 0, 0, 0, FlagZero)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, MDString *Name, uint64_t SizeInBits),(Tag, Name, SizeInBits, 0, 0, 0, 0, FlagZero)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, DIFlags Flags),(Tag, Name, SizeInBits, AlignInBits, Encoding, 0, 0, Flags)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, StringRef Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags),(Tag, Name, SizeInBits, AlignInBits, Encoding, NumExtraInhabitants, DataSizeInBits, Flags)) DEFINE_MDNODE_GET(DIBasicType
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags Flags DEFINE_MDNODE_GET (DIBasicType,(unsigned Tag, MDString *Name, Metadata *SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags),(Tag, Name, SizeInBits, AlignInBits, Encoding, NumExtraInhabitants, DataSizeInBits, Flags)) TempDIBasicType clone() const
unsigned getEncoding () const
uint32_t getDataSizeInBits () const
LLVM_ABI std::optional< Signedness > getSignedness () const
Return the signedness of this type, or std::nullopt if this type is neither signed nor unsigned.
Public Member Functions inherited from llvm::DIType
TempDIType clone () const
unsigned getLine () const
LLVM_ABI uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
uint32_t getNumExtraInhabitants () const
DIFlags getFlags () const
DIScope * getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
Metadata * getRawSizeInBits () const
uint64_t getSizeInBits () const
Metadata * getRawOffsetInBits () const
uint64_t getOffsetInBits () const
TempDIType cloneWithFlags (DIFlags NewFlags) const
Returns a new temporary DIType with updated Flags.
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isBitField () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isTypePassByValue () const
bool isTypePassByReference () const
bool isBigEndian () const
bool isLittleEndian () const
bool getExportSymbols () const
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
LLVM_ABI StringRef getName () const
LLVM_ABI DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
LLVM_ABI dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
LLVM_ABI TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
LLVM_ABI void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
bool hasGeneralizedMDString ()
Check if this is a valid generalized type metadata node.
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
LLVM_ABI void resolveCycles ()
Resolve cycles.
LLVM_ABI void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
LLVM_ABI bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
LLVM_ABI void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
LLVM_ABI void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
LLVM_ABI void dumpTree () const
User-friendly dump in tree shape.
LLVM_ABI void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIType
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static LLVM_ABI DIFlags getFlag (StringRef Flag)
static LLVM_ABI StringRef getFlagString (DIFlags Flag)
static LLVM_ABI DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static LLVM_ABI void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static LLVM_ABI MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static LLVM_ABI MDNode * intersect (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericNoaliasAddrspace (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
static LLVM_ABI MDNode * getMergedMemProfMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCallsiteMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCalleeTypeMetadata (const MDNode *A, const MDNode *B)
static LLVM_ABI CaptureComponents toCaptureComponents (const MDNode *MD)
Convert !captures metadata to CaptureComponents. MD may be nullptr.
static LLVM_ABI MDNode * fromCaptureComponents (LLVMContext &Ctx, CaptureComponents CC)
Convert CaptureComponents to !captures metadata.
Public Attributes
unsigned Tag
unsigned StringRef Name
unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t Tag
unsigned StringRef uint64_t Name
unsigned StringRef uint64_t FlagZero unsigned Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t NumExtraInhabitants
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags NumExtraInhabitants
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString * Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t NumExtraInhabitants
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DataSizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags Flags
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags Tag
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags Name
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags SizeInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags AlignInBits
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags Encoding
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags NumExtraInhabitants
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags DataSizeInBits
Protected Member Functions
DIBasicType (LLVMContext &C, StorageType Storage, unsigned Tag, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, ArrayRef< Metadata * > Ops)
DIBasicType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, ArrayRef< Metadata * > Ops)
~DIBasicType ()=default
TempDIBasicType cloneImpl () const
Protected Member Functions inherited from llvm::DIType
DIType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags, ArrayRef< Metadata * > Ops)
~DIType ()=default
void init (unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags)
void mutate (unsigned Tag, unsigned Line, uint32_t AlignInBits, uint32_t NumExtraInhabitants, DIFlags Flags)
Change fields in place.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~DINode ()=default
template<class Ty>
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
LLVM_ABI MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~MDNode ()=default
LLVM_ABI void * operator new (size_t Size, size_t NumOps, StorageType Storage)
LLVM_ABI void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
LLVM_ABI void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
LLVM_ABI void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
LLVM_ABI void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions
static DIBasicType * getImpl (LLVMContext &Context, unsigned Tag, StringRef Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, StorageType Storage, bool ShouldCreate=true)
static DIBasicType * getImpl (LLVMContext &Context, unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, StorageType Storage, bool ShouldCreate=true)
static LLVM_ABI DIBasicType * getImpl (LLVMContext &Context, unsigned Tag, MDString *Name, Metadata *SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, StorageType Storage, bool ShouldCreate=true)
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T, class StoreT>
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T>
static T * storeImpl (T *N, StorageType Storage)
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Static Protected Attributes inherited from llvm::DIType
static constexpr unsigned N_OPERANDS = 5
Detailed Description
Basic type, like 'int' or 'float'.
TODO: Split out DW_TAG_unspecified_type. TODO: Drop unused accessors.
Definition at line 889 of file DebugInfoMetadata.h.
Member Enumeration Documentation
Signedness
enum class llvm::DIBasicType::Signedness strong
Enumerator
Signed
Unsigned
Definition at line 1002 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DIBasicType() [1/2]
llvm::DIBasicType::DIBasicType (LLVMContext & C, StorageType Storage, unsigned Tag, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, ArrayRef< Metadata * > Ops) inline protected
Definition at line 900 of file DebugInfoMetadata.h.
References AbstractManglingParser< Derived, Alloc >::Ops, AlignInBits, llvm::CallingConv::C, llvm::DIType::DIType(), Flags, NumExtraInhabitants, llvm::Metadata::Storage, and Tag.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), getImpl(), getImpl(), getImpl(), and llvm::DIFixedPointType::MDNode.
DIBasicType() [2/2]
llvm::DIBasicType::DIBasicType (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, ArrayRef< Metadata * > Ops) inline protected
Definition at line 907 of file DebugInfoMetadata.h.
References AbstractManglingParser< Derived, Alloc >::Ops, AlignInBits, llvm::CallingConv::C, llvm::DIType::DIType(), Flags, NumExtraInhabitants, llvm::Metadata::Storage, and Tag.
~DIBasicType()
llvm::DIBasicType::~DIBasicType () protected default
Member Function Documentation
classof()
bool llvm::DIBasicType::classof (const Metadata * MD) inline static
Definition at line 1008 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
cloneImpl()
TempDIBasicType llvm::DIBasicType::cloneImpl () const inline protected
Definition at line 944 of file DebugInfoMetadata.h.
References llvm::DIType::getAlignInBits(), llvm::MDNode::getContext(), getDataSizeInBits(), getEncoding(), llvm::DIType::getFlags(), llvm::DIType::getNumExtraInhabitants(), llvm::DIType::getRawName(), llvm::DIType::getRawSizeInBits(), llvm::DINode::getTag(), and llvm::MDNode::getTemporary().
Referenced by DEFINE_MDNODE_GET(), and llvm::DIFixedPointType::DEFINE_MDNODE_GET().
DEFINE_MDNODE_GET() [1/5]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags Flags llvm::DIBasicType::DEFINE_MDNODE_GET (DIBasicType , (unsigned Tag, MDString *Name, Metadata *SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags) , (Tag, Name, SizeInBits, AlignInBits, Encoding, NumExtraInhabitants, DataSizeInBits, Flags)) const inline
Definition at line 988 of file DebugInfoMetadata.h.
References AlignInBits, llvm::DIType::clone(), cloneImpl(), DEFINE_MDNODE_GET(), DIBasicType(), Flags, Name, NumExtraInhabitants, SizeInBits, and Tag.
DEFINE_MDNODE_GET() [2/5]
unsigned StringRef uint64_t FlagZero llvm::DIBasicType::DEFINE_MDNODE_GET (DIBasicType , (unsigned Tag, MDString *Name, uint64_t SizeInBits) , (Tag, Name, SizeInBits, 0, 0, 0, 0, FlagZero))
References DEFINE_MDNODE_GET(), DIBasicType(), Name, SizeInBits, and Tag.
DEFINE_MDNODE_GET() [3/5]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags llvm::DIBasicType::DEFINE_MDNODE_GET (DIBasicType , (unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, DIFlags Flags) , (Tag, Name, SizeInBits, AlignInBits, Encoding, 0, 0, Flags))
References AlignInBits, DEFINE_MDNODE_GET(), DIBasicType(), Flags, Name, SizeInBits, and Tag.
DEFINE_MDNODE_GET() [4/5]
llvm::DIBasicType::DEFINE_MDNODE_GET (DIBasicType , (unsigned Tag, StringRef Name) , (Tag, Name, 0, 0, 0, 0, 0, FlagZero))
References DIBasicType(), Name, and Tag.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), and DEFINE_MDNODE_GET().
DEFINE_MDNODE_GET() [5/5]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags llvm::DIBasicType::DEFINE_MDNODE_GET (DIBasicType , (unsigned Tag, StringRef Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags) , (Tag, Name, SizeInBits, AlignInBits, Encoding, NumExtraInhabitants, DataSizeInBits, Flags))
References AlignInBits, DEFINE_MDNODE_GET(), DIBasicType(), Flags, Name, NumExtraInhabitants, SizeInBits, and Tag.
getDataSizeInBits()
uint32_t llvm::DIBasicType::getDataSizeInBits () const inline
Definition at line 1000 of file DebugInfoMetadata.h.
Referenced by cloneImpl().
getEncoding()
unsigned llvm::DIBasicType::getEncoding () const inline
Definition at line 998 of file DebugInfoMetadata.h.
Referenced by cloneImpl(), getSignedness(), and llvm::DIFixedPointType::isSigned().
getImpl() [1/3]
DIBasicType * DIBasicType::getImpl (LLVMContext & Context, unsigned Tag, MDString * Name, Metadata * SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, StorageType Storage, bool ShouldCreate = true) static protected
Definition at line 875 of file DebugInfoMetadata.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, AlignInBits, assert(), DEFINE_GETIMPL_LOOKUP, DEFINE_GETIMPL_STORE, DIBasicType(), Flags, isCanonical(), Name, NumExtraInhabitants, SizeInBits, llvm::Metadata::Storage, and Tag.
getImpl() [2/3]
DIBasicType * llvm::DIBasicType::getImpl (LLVMContext & Context, unsigned Tag, MDString * Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, StorageType Storage, bool ShouldCreate = true) inline static protected
Definition at line 926 of file DebugInfoMetadata.h.
References AlignInBits, DIBasicType(), Flags, llvm::ConstantAsMetadata::get(), getImpl(), llvm::Type::getInt64Ty(), Name, NumExtraInhabitants, SizeInBits, llvm::Metadata::Storage, and Tag.
getImpl() [3/3]
DIBasicType * llvm::DIBasicType::getImpl (LLVMContext & Context, unsigned Tag, StringRef Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, uint32_t NumExtraInhabitants, uint32_t DataSizeInBits, DIFlags Flags, StorageType Storage, bool ShouldCreate = true) inline static protected
Definition at line 916 of file DebugInfoMetadata.h.
References AlignInBits, DIBasicType(), Flags, llvm::DINode::getCanonicalMDString(), getImpl(), Name, NumExtraInhabitants, SizeInBits, llvm::Metadata::Storage, and Tag.
Referenced by getImpl(), and getImpl().
getSignedness()
std::optional< DIBasicType::Signedness > DIBasicType::getSignedness () const
Return the signedness of this type, or std::nullopt if this type is neither signed nor unsigned.
Definition at line 892 of file DebugInfoMetadata.cpp.
References getEncoding(), Signed, and Unsigned.
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 890 of file DebugInfoMetadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
MDNode
friend class MDNode friend
Definition at line 891 of file DebugInfoMetadata.h.
References MDNode.
Referenced by MDNode.
Member Data Documentation
AlignInBits [1/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::AlignInBits
Definition at line 986 of file DebugInfoMetadata.h.
AlignInBits [2/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t llvm::DIBasicType::AlignInBits
Definition at line 983 of file DebugInfoMetadata.h.
AlignInBits [3/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags llvm::DIBasicType::AlignInBits
Definition at line 972 of file DebugInfoMetadata.h.
AlignInBits [4/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t llvm::DIBasicType::AlignInBits
Definition at line 970 of file DebugInfoMetadata.h.
AlignInBits [5/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags llvm::DIBasicType::AlignInBits
Definition at line 963 of file DebugInfoMetadata.h.
AlignInBits [6/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t llvm::DIBasicType::AlignInBits
Definition at line 962 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DIBasicType(), DIBasicType(), getImpl(), getImpl(), and getImpl().
DataSizeInBits [1/2]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::DataSizeInBits
Definition at line 987 of file DebugInfoMetadata.h.
DataSizeInBits [2/2]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t llvm::DIBasicType::DataSizeInBits
Definition at line 984 of file DebugInfoMetadata.h.
Encoding [1/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::Encoding
Definition at line 986 of file DebugInfoMetadata.h.
Encoding [2/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned llvm::DIBasicType::Encoding
Definition at line 983 of file DebugInfoMetadata.h.
Encoding [3/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags llvm::DIBasicType::Encoding
Definition at line 972 of file DebugInfoMetadata.h.
Encoding [4/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned llvm::DIBasicType::Encoding
Definition at line 970 of file DebugInfoMetadata.h.
Encoding [5/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags llvm::DIBasicType::Encoding
Definition at line 963 of file DebugInfoMetadata.h.
Encoding [6/6]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned llvm::DIBasicType::Encoding
Definition at line 962 of file DebugInfoMetadata.h.
Flags [1/3]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::Flags
Definition at line 985 of file DebugInfoMetadata.h.
Flags [2/3]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags llvm::DIBasicType::Flags
Definition at line 971 of file DebugInfoMetadata.h.
Flags [3/3]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags llvm::DIBasicType::Flags
Definition at line 962 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DIBasicType(), DIBasicType(), getImpl(), getImpl(), and getImpl().
Name [1/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::Name
Definition at line 986 of file DebugInfoMetadata.h.
Name [2/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString* llvm::DIBasicType::Name
Definition at line 982 of file DebugInfoMetadata.h.
Name [3/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags llvm::DIBasicType::Name
Definition at line 972 of file DebugInfoMetadata.h.
Name [4/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef llvm::DIBasicType::Name
Definition at line 969 of file DebugInfoMetadata.h.
Name [5/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags llvm::DIBasicType::Name
Definition at line 963 of file DebugInfoMetadata.h.
Name [6/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef llvm::DIBasicType::Name
Definition at line 961 of file DebugInfoMetadata.h.
Name [7/8]
unsigned StringRef uint64_t llvm::DIBasicType::Name
Definition at line 956 of file DebugInfoMetadata.h.
Name [8/8]
unsigned StringRef llvm::DIBasicType::Name
Definition at line 955 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), getImpl(), getImpl(), and getImpl().
NumExtraInhabitants [1/4]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::NumExtraInhabitants
Definition at line 987 of file DebugInfoMetadata.h.
NumExtraInhabitants [2/4]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t llvm::DIBasicType::NumExtraInhabitants
Definition at line 984 of file DebugInfoMetadata.h.
NumExtraInhabitants [3/4]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags llvm::DIBasicType::NumExtraInhabitants
Definition at line 973 of file DebugInfoMetadata.h.
NumExtraInhabitants [4/4]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t llvm::DIBasicType::NumExtraInhabitants
Definition at line 971 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DIBasicType(), DIBasicType(), getImpl(), getImpl(), and getImpl().
SizeInBits [1/7]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::SizeInBits
Definition at line 986 of file DebugInfoMetadata.h.
SizeInBits [2/7]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t llvm::DIBasicType::SizeInBits
Definition at line 982 of file DebugInfoMetadata.h.
SizeInBits [3/7]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags llvm::DIBasicType::SizeInBits
Definition at line 972 of file DebugInfoMetadata.h.
SizeInBits [4/7]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t llvm::DIBasicType::SizeInBits
Definition at line 969 of file DebugInfoMetadata.h.
SizeInBits [5/7]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags llvm::DIBasicType::SizeInBits
Definition at line 963 of file DebugInfoMetadata.h.
SizeInBits [6/7]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t llvm::DIBasicType::SizeInBits
Definition at line 961 of file DebugInfoMetadata.h.
SizeInBits [7/7]
unsigned StringRef uint64_t llvm::DIBasicType::SizeInBits
Definition at line 955 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), getImpl(), getImpl(), and getImpl().
Tag [1/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned MDString uint64_t uint32_t unsigned uint32_t uint32_t DIFlags llvm::DIBasicType::Tag
Definition at line 986 of file DebugInfoMetadata.h.
Tag [2/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags Flags unsigned llvm::DIBasicType::Tag
Definition at line 982 of file DebugInfoMetadata.h.
Tag [3/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned StringRef uint64_t uint32_t unsigned uint32_t DIFlags llvm::DIBasicType::Tag
Definition at line 972 of file DebugInfoMetadata.h.
Tag [4/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags Flags unsigned llvm::DIBasicType::Tag
Definition at line 969 of file DebugInfoMetadata.h.
Tag [5/8]
unsigned StringRef uint64_t FlagZero unsigned StringRef uint64_t uint32_t unsigned DIFlags llvm::DIBasicType::Tag
Definition at line 963 of file DebugInfoMetadata.h.
Tag [6/8]
unsigned StringRef uint64_t FlagZero unsigned llvm::DIBasicType::Tag
Definition at line 961 of file DebugInfoMetadata.h.
Tag [7/8]
unsigned StringRef uint64_t llvm::DIBasicType::Tag
Definition at line 956 of file DebugInfoMetadata.h.
Tag [8/8]
unsigned llvm::DIBasicType::Tag
Definition at line 955 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DEFINE_MDNODE_GET(), DIBasicType(), DIBasicType(), getImpl(), getImpl(), and getImpl().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp