LLVM: llvm::NVPTXInstPrinter Class Reference
llvm::NVPTXInstPrinter Class Reference
#include "Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.h"
Public Member Functions
NVPTXInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, MCRegister Reg) override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS) override
Print the specified MCInst to the specified raw_ostream.
std::pair< const char *, uint64_t > getMnemonic (const MCInst &MI) const override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printCvtMode (const MCInst *MI, int OpNum, raw_ostream &O, StringRef Modifier={})
void printCmpMode (const MCInst *MI, int OpNum, raw_ostream &O, StringRef Modifier={})
void printAtomicCode (const MCInst *MI, int OpNum, raw_ostream &O, StringRef Modifier={})
void printMmaCode (const MCInst *MI, int OpNum, raw_ostream &O, StringRef Modifier={})
void printMemOperand (const MCInst *MI, int OpNum, raw_ostream &O, StringRef Modifier={})
void printUsedBytesMaskPragma (const MCInst *MI, int OpNum, raw_ostream &O)
void printRegisterOrSinkSymbol (const MCInst *MI, int OpNum, raw_ostream &O)
void printHexu32imm (const MCInst *MI, int OpNum, raw_ostream &O)
void printProtoIdent (const MCInst *MI, int OpNum, raw_ostream &O)
void printPrmtMode (const MCInst *MI, int OpNum, raw_ostream &O)
void printTmaReductionMode (const MCInst *MI, int OpNum, raw_ostream &O)
void printCTAGroup (const MCInst *MI, int OpNum, raw_ostream &O)
void printCallOperand (const MCInst *MI, int OpNum, raw_ostream &O, StringRef Modifier={})
void printFTZFlag (const MCInst *MI, int OpNum, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
bool getUseColor () const
void setUseColor (bool Value)
WithMarkup markup (raw_ostream &OS, Markup M)
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
Additional Inherited Members
Public Types inherited from llvm::MCInstPrinter
enum class Markup { Immediate , Register , Target , Memory }
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool UseColor = false
True if we are printing colored assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
SmallVector< raw_ostream::Colors, 4 > ColorStack {raw_ostream::Colors::RESET}
Detailed Description
Definition at line 22 of file NVPTXInstPrinter.h.
Constructor & Destructor Documentation
NVPTXInstPrinter()
NVPTXInstPrinter::NVPTXInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI)
Definition at line 33 of file NVPTXInstPrinter.cpp.
References llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MCInstPrinter(), llvm::MCInstPrinter::MII, and llvm::MCInstPrinter::MRI.
Member Function Documentation
getMnemonic()
std::pair< const char *, uint64_t > llvm::NVPTXInstPrinter::getMnemonic (const MCInst & MI) const override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
References MI.
getRegisterName()
const char * llvm::NVPTXInstPrinter::getRegisterName (MCRegister Reg) static
References MI, and Reg.
Referenced by llvm::NVPTXRegisterInfo::getDwarfRegNum(), and printRegName().
printAtomicCode()
void NVPTXInstPrinter::printAtomicCode (const MCInst * MI, int OpNum, raw_ostream & O, StringRef Modifier = {})
Definition at line 274 of file NVPTXInstPrinter.cpp.
References A(), llvm::NVPTX::Acquire, llvm::NVPTX::AcquireRelease, llvm::NVPTX::Block, llvm::c_str(), llvm::NVPTX::Cluster, llvm::NVPTX::Const, llvm::NVPTX::DefaultDevice, llvm::NVPTX::Device, llvm::NVPTX::PTXLdStInstCode::Float, llvm::formatv(), llvm::NVPTX::Generic, llvm::MCOperand::getImm(), llvm::NVPTX::Global, llvm_unreachable, llvm::NVPTX::Local, MI, llvm::NVPTX::NotAtomic, llvm::NVPTX::Param, llvm::NVPTX::Relaxed, llvm::NVPTX::RelaxedMMIO, llvm::NVPTX::Release, llvm::report_fatal_error(), llvm::NVPTX::SequentiallyConsistent, llvm::NVPTX::Shared, llvm::NVPTX::SharedCluster, llvm::NVPTX::PTXLdStInstCode::Signed, llvm::NVPTX::System, llvm::NVPTX::Thread, llvm::NVPTX::PTXLdStInstCode::Unsigned, llvm::NVPTX::PTXLdStInstCode::Untyped, and llvm::NVPTX::Volatile.
printCallOperand()
void NVPTXInstPrinter::printCallOperand (const MCInst * MI, int OpNum, raw_ostream & O, StringRef Modifier = {})
Definition at line 517 of file NVPTXInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), I, llvm::interleaveComma(), llvm::MCOperand::isImm(), llvm_unreachable, MI, and llvm::seq().
printCmpMode()
void NVPTXInstPrinter::printCmpMode (const MCInst * MI, int OpNum, raw_ostream & O, StringRef Modifier = {})
Definition at line 168 of file NVPTXInstPrinter.cpp.
References llvm::NVPTX::PTXCmpMode::EQ, llvm::NVPTX::PTXCmpMode::EQU, llvm::NVPTX::PTXCmpMode::GE, llvm::MCOperand::getImm(), llvm::NVPTX::PTXCmpMode::GEU, llvm::NVPTX::PTXCmpMode::GT, llvm::NVPTX::PTXCmpMode::GTU, llvm::NVPTX::PTXCmpMode::LE, llvm::NVPTX::PTXCmpMode::LEU, llvm_unreachable, llvm::NVPTX::PTXCmpMode::LT, llvm::NVPTX::PTXCmpMode::LTU, MI, llvm::NVPTX::PTXCmpMode::NE, llvm::NVPTX::PTXCmpMode::NEU, llvm::NVPTX::PTXCmpMode::NotANumber, and llvm::NVPTX::PTXCmpMode::NUM.
printCTAGroup()
void NVPTXInstPrinter::printCTAGroup (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 498 of file NVPTXInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm_unreachable, and MI.
printCvtMode()
void NVPTXInstPrinter::printCvtMode (const MCInst * MI, int OpNum, raw_ostream & O, StringRef Modifier = {})
Definition at line 98 of file NVPTXInstPrinter.cpp.
References llvm::NVPTX::PTXCvtMode::BASE_MASK, llvm::NVPTX::PTXCvtMode::FTZ_FLAG, llvm::MCOperand::getImm(), llvm_unreachable, MI, llvm::NVPTX::PTXCvtMode::NONE, llvm::NVPTX::PTXCvtMode::RELU_FLAG, llvm::NVPTX::PTXCvtMode::RM, llvm::NVPTX::PTXCvtMode::RMI, llvm::NVPTX::PTXCvtMode::RN, llvm::NVPTX::PTXCvtMode::RNA, llvm::NVPTX::PTXCvtMode::RNI, llvm::NVPTX::PTXCvtMode::RP, llvm::NVPTX::PTXCvtMode::RPI, llvm::NVPTX::PTXCvtMode::RS, llvm::NVPTX::PTXCvtMode::RZ, llvm::NVPTX::PTXCvtMode::RZI, and llvm::NVPTX::PTXCvtMode::SAT_FLAG.
printFTZFlag()
void NVPTXInstPrinter::printFTZFlag (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 160 of file NVPTXInstPrinter.cpp.
References llvm::MCOperand::getImm(), and MI.
printHexu32imm()
void NVPTXInstPrinter::printHexu32imm (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 417 of file NVPTXInstPrinter.cpp.
References llvm::MCInstPrinter::formatHex(), and MI.
printInst()
void NVPTXInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 75 of file NVPTXInstPrinter.cpp.
References MI, llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::NVPTXInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
References MI.
Referenced by printInst().
printMemOperand()
void NVPTXInstPrinter::printMemOperand (const MCInst * MI, int OpNum, raw_ostream & O, StringRef Modifier = {})
Definition at line 382 of file NVPTXInstPrinter.cpp.
References MI, and printOperand().
printMmaCode()
void NVPTXInstPrinter::printMmaCode (const MCInst * MI, int OpNum, raw_ostream & O, StringRef Modifier = {})
Definition at line 366 of file NVPTXInstPrinter.cpp.
References llvm::StringRef::empty(), llvm::MCOperand::getImm(), llvm_unreachable, and MI.
printOperand()
void NVPTXInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 84 of file NVPTXInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatImm(), llvm::MCInstPrinter::Immediate, llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::markup(), MI, and printRegName().
Referenced by printMemOperand(), and printRegisterOrSinkSymbol().
printPrmtMode()
void NVPTXInstPrinter::printPrmtMode (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 432 of file NVPTXInstPrinter.cpp.
References llvm::NVPTX::PTXPrmtMode::B4E, llvm::NVPTX::PTXPrmtMode::ECL, llvm::NVPTX::PTXPrmtMode::ECR, llvm::NVPTX::PTXPrmtMode::F4E, llvm::MCOperand::getImm(), MI, llvm::NVPTX::PTXPrmtMode::NONE, llvm::NVPTX::PTXPrmtMode::RC16, and llvm::NVPTX::PTXPrmtMode::RC8.
printProtoIdent()
void NVPTXInstPrinter::printProtoIdent (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 423 of file NVPTXInstPrinter.cpp.
References assert(), llvm::cast(), llvm::MCSymbol::getName(), and MI.
printRegisterOrSinkSymbol()
void NVPTXInstPrinter::printRegisterOrSinkSymbol (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 408 of file NVPTXInstPrinter.cpp.
References MI, llvm::MCRegister::NoRegister, and printOperand().
printRegName()
void NVPTXInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 37 of file NVPTXInstPrinter.cpp.
References getRegisterName(), and llvm::report_fatal_error().
Referenced by printOperand().
printTmaReductionMode()
void NVPTXInstPrinter::printTmaReductionMode (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 463 of file NVPTXInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm_unreachable, and MI.
printUsedBytesMaskPragma()
void NVPTXInstPrinter::printUsedBytesMaskPragma (const MCInst * MI, int OpNum, raw_ostream & O)
Definition at line 398 of file NVPTXInstPrinter.cpp.
References assert(), llvm::format_hex(), and MI.
The documentation for this class was generated from the following files:
lib/Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.h
lib/Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.cpp