LLVM: llvm::DbgSSABlockPredIterator Class Reference
llvm::DbgSSABlockPredIterator Class Reference
Thin wrapper around a block successor iterator.
#include "llvm/Transforms/Utils/DebugSSAUpdater.h"
Public Member Functions
DbgSSABlockPredIterator (pred_iterator PredIt, DebugSSAUpdater &Updater)
bool operator!= (const DbgSSABlockPredIterator &OtherIt) const
DbgSSABlockPredIterator & operator++ ()
DbgSSABlock * operator* ()
Public Attributes
pred_iterator PredIt
DebugSSAUpdater & Updater
Detailed Description
Thin wrapper around a block successor iterator.
Definition at line 146 of file DebugSSAUpdater.h.
Constructor & Destructor Documentation
DbgSSABlockPredIterator()
llvm::DbgSSABlockPredIterator::DbgSSABlockPredIterator (pred_iterator PredIt, DebugSSAUpdater & Updater) inline
Definition at line 151 of file DebugSSAUpdater.h.
References PredIt, and Updater.
Referenced by operator!=(), and operator++().
Member Function Documentation
operator!=()
bool llvm::DbgSSABlockPredIterator::operator!= (const DbgSSABlockPredIterator & OtherIt) const inline
Definition at line 154 of file DebugSSAUpdater.h.
References DbgSSABlockPredIterator(), and PredIt.
operator*()
DbgSSABlock * DbgSSABlockPredIterator::operator* ()
Definition at line 120 of file DebugSSAUpdater.cpp.
References PredIt, and Updater.
operator++()
DbgSSABlockPredIterator & llvm::DbgSSABlockPredIterator::operator++ () inline
Definition at line 158 of file DebugSSAUpdater.h.
References DbgSSABlockPredIterator(), and PredIt.
Member Data Documentation
PredIt
pred_iterator llvm::DbgSSABlockPredIterator::PredIt
Definition at line 148 of file DebugSSAUpdater.h.
Referenced by DbgSSABlockPredIterator(), operator!=(), operator*(), and operator++().
Updater
DebugSSAUpdater& llvm::DbgSSABlockPredIterator::Updater
Definition at line 149 of file DebugSSAUpdater.h.
Referenced by DbgSSABlockPredIterator(), and operator*().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/DebugSSAUpdater.h
lib/Transforms/Utils/DebugSSAUpdater.cpp