LLVM: llvm::lsp::JSONTransportInput Class Reference
llvm::lsp::JSONTransportInput Class Reference abstract
An abstract class used by the JSONTransport to read JSON message.
#include "llvm/Support/LSP/Transport.h"
Public Member Functions
JSONTransportInput (JSONStreamStyle Style=JSONStreamStyle::Standard)
virtual ~JSONTransportInput ()=default
virtual bool hasError () const =0
virtual bool isEndOfInput () const =0
LogicalResult readMessage (std::string &Json)
Read in a message from the input stream.
virtual LogicalResult readDelimitedMessage (std::string &Json)=0
virtual LogicalResult readStandardMessage (std::string &Json)=0
Detailed Description
An abstract class used by the JSONTransport to read JSON message.
Definition at line 53 of file Transport.h.
Constructor & Destructor Documentation
JSONTransportInput()
llvm::lsp::JSONTransportInput::JSONTransportInput (JSONStreamStyle Style = JSONStreamStyle::Standard) inline explicit
Definition at line 55 of file Transport.h.
References llvm::lsp::Standard.
Referenced by llvm::lsp::JSONTransportInputOverFile::JSONTransportInputOverFile().
~JSONTransportInput()
virtual llvm::lsp::JSONTransportInput::~JSONTransportInput () virtual default
Member Function Documentation
hasError()
virtual bool llvm::lsp::JSONTransportInput::hasError () const pure virtual
Implemented in llvm::lsp::JSONTransportInputOverFile.
isEndOfInput()
virtual bool llvm::lsp::JSONTransportInput::isEndOfInput () const pure virtual
Implemented in llvm::lsp::JSONTransportInputOverFile.
readDelimitedMessage()
virtual LogicalResult llvm::lsp::JSONTransportInput::readDelimitedMessage (std::string & Json) pure virtual
Implemented in llvm::lsp::JSONTransportInputOverFile.
Referenced by readMessage().
readMessage()
LogicalResult llvm::lsp::JSONTransportInput::readMessage (std::string & Json) inline
Read in a message from the input stream.
Definition at line 63 of file Transport.h.
References llvm::lsp::Delimited, readDelimitedMessage(), and readStandardMessage().
readStandardMessage()
virtual LogicalResult llvm::lsp::JSONTransportInput::readStandardMessage (std::string & Json) pure virtual
Implemented in llvm::lsp::JSONTransportInputOverFile.
Referenced by readMessage().
The documentation for this class was generated from the following file:
include/llvm/Support/LSP/Transport.h