LLVM: llvm::jitlink::systemz::GOTTableManager Class Reference
llvm::jitlink::systemz::GOTTableManager Class Reference
Global Offset Table Builder.
#include "llvm/ExecutionEngine/JITLink/systemz.h"
Public Member Functions
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< GOTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Detailed Description
Global Offset Table Builder.
Definition at line 827 of file systemz.h.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::systemz::GOTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 867 of file systemz.h.
References llvm::jitlink::systemz::createAnonymousPointer(), and G.
getSectionName()
StringRef llvm::jitlink::systemz::GOTTableManager::getSectionName () inline static
Definition at line 829 of file systemz.h.
visitEdge()
bool llvm::jitlink::systemz::GOTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 831 of file systemz.h.
References assert(), B(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::jitlink::systemz::Delta12FromGOT, llvm::jitlink::systemz::Delta16FromGOT, llvm::jitlink::systemz::Delta20FromGOT, llvm::jitlink::systemz::Delta32dbl, llvm::jitlink::systemz::Delta32FromGOT, llvm::jitlink::systemz::Delta64FromGOT, llvm::formatv(), G, llvm::jitlink::TableManager< GOTTableManager >::getEntryForTarget(), llvm::jitlink::systemz::RequestGOTAndTransformToDelta12FromGOT, llvm::jitlink::systemz::RequestGOTAndTransformToDelta16FromGOT, llvm::jitlink::systemz::RequestGOTAndTransformToDelta20FromGOT, llvm::jitlink::systemz::RequestGOTAndTransformToDelta32dbl, llvm::jitlink::systemz::RequestGOTAndTransformToDelta32FromGOT, and llvm::jitlink::systemz::RequestGOTAndTransformToDelta64FromGOT.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/systemz.h