LLVM: llvm::SDDbgOperand Class Reference
llvm::SDDbgOperand Class Reference
Holds the information for a single machine location through SDISel; either an SDNode, a constant, a stack location, or a virtual register.
#include "CodeGen/SelectionDAG/SDNodeDbgValue.h"
Public Types
enum Kind { SDNODE = 0 , CONST = 1 , FRAMEIX = 2 , VREG = 3 }
Public Member Functions
Kind getKind () const
SDNode * getSDNode () const
Returns the SDNode* for a register ref.
unsigned getResNo () const
Returns the ResNo for a register ref.
const Value * getConst () const
Returns the Value* for a constant.
unsigned getFrameIx () const
Returns the FrameIx for a stack object.
Register getVReg () const
Returns the Virtual Register for a VReg.
bool operator!= (const SDDbgOperand &Other) const
bool operator== (const SDDbgOperand &Other) const
Static Public Member Functions
static SDDbgOperand fromNode (SDNode *Node, unsigned ResNo)
static SDDbgOperand fromFrameIdx (unsigned FrameIdx)
static SDDbgOperand fromVReg (Register VReg)
static SDDbgOperand fromConst (const Value *Const)
Detailed Description
Holds the information for a single machine location through SDISel; either an SDNode, a constant, a stack location, or a virtual register.
Definition at line 32 of file SDNodeDbgValue.h.
Member Enumeration Documentation
Kind
enum llvm::SDDbgOperand::Kind
Enumerator
SDNODE
Value is the result of an expression.
CONST
Value is a constant.
FRAMEIX
Value is contents of a stack location.
VREG
Value is a virtual register.
Definition at line 34 of file SDNodeDbgValue.h.
Member Function Documentation
fromConst()
SDDbgOperand llvm::SDDbgOperand::fromConst (const Value * Const) inline static
Definition at line 81 of file SDNodeDbgValue.h.
References Const.
Referenced by llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::SelectionDAG::getConstantDbgValue(), handleDanglingVariadicDebugInfo(), and llvm::SelectionDAGBuilder::handleDebugValue().
fromFrameIdx()
SDDbgOperand llvm::SDDbgOperand::fromFrameIdx (unsigned FrameIdx) inline static
Definition at line 75 of file SDNodeDbgValue.h.
References FRAMEIX.
Referenced by llvm::SelectionDAG::getFrameIndexDbgValue(), llvm::SelectionDAGBuilder::handleDebugValue(), and llvm::SelectionDAG::salvageDebugInfo().
fromNode()
SDDbgOperand llvm::SDDbgOperand::fromNode (SDNode * Node, unsigned ResNo) inline static
Definition at line 72 of file SDNodeDbgValue.h.
References Node, and ResNo.
Referenced by llvm::SelectionDAG::getDbgValue(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAG::salvageDebugInfo(), and llvm::SelectionDAG::transferDbgValues().
fromVReg()
SDDbgOperand llvm::SDDbgOperand::fromVReg (Register VReg) inline static
Definition at line 78 of file SDNodeDbgValue.h.
References VREG, and VReg.
Referenced by llvm::SelectionDAG::getVRegDbgValue(), and llvm::SelectionDAGBuilder::handleDebugValue().
getConst()
const Value * llvm::SDDbgOperand::getConst () const inline
Returns the Value* for a constant.
Definition at line 55 of file SDNodeDbgValue.h.
References assert(), and CONST.
Referenced by operator==().
getFrameIx()
unsigned llvm::SDDbgOperand::getFrameIx () const inline
Returns the FrameIx for a stack object.
Definition at line 61 of file SDNodeDbgValue.h.
References assert(), and FRAMEIX.
Referenced by operator==().
getKind()
Kind llvm::SDDbgOperand::getKind () const inline
Definition at line 40 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgInstrRef().
getResNo()
unsigned llvm::SDDbgOperand::getResNo () const inline
Returns the ResNo for a register ref.
Definition at line 49 of file SDNodeDbgValue.h.
References assert(), and SDNODE.
Referenced by llvm::InstrEmitter::EmitDbgInstrRef(), and operator==().
getSDNode()
SDNode * llvm::SDDbgOperand::getSDNode () const inline
Returns the SDNode* for a register ref.
Definition at line 43 of file SDNodeDbgValue.h.
References assert(), and SDNODE.
Referenced by llvm::InstrEmitter::EmitDbgInstrRef(), and operator==().
getVReg()
Register llvm::SDDbgOperand::getVReg () const inline
Returns the Virtual Register for a VReg.
Definition at line 67 of file SDNodeDbgValue.h.
References assert(), and VREG.
Referenced by llvm::InstrEmitter::EmitDbgInstrRef(), and operator==().
operator!=()
bool llvm::SDDbgOperand::operator!= (const SDDbgOperand & Other) const inline
Definition at line 85 of file SDNodeDbgValue.h.
References llvm::Other.
operator==()
bool llvm::SDDbgOperand::operator== (const SDDbgOperand & Other) const inline
Definition at line 86 of file SDNodeDbgValue.h.
References CONST, FRAMEIX, getConst(), getFrameIx(), getResNo(), getSDNode(), getVReg(), llvm::Other, SDNODE, and VREG.
Member Data Documentation
Const
const Value* llvm::SDDbgOperand::Const
Valid for constants.
Definition at line 109 of file SDNodeDbgValue.h.
Referenced by fromConst().
FrameIx
unsigned llvm::SDDbgOperand::FrameIx
Valid for stack objects.
Definition at line 110 of file SDNodeDbgValue.h.
Node
SDNode* llvm::SDDbgOperand::Node
Valid for expressions.
Definition at line 106 of file SDNodeDbgValue.h.
Referenced by fromNode().
ResNo
unsigned llvm::SDDbgOperand::ResNo
Valid for expressions.
Definition at line 107 of file SDNodeDbgValue.h.
Referenced by fromNode().
[struct]
struct { ... } llvm::SDDbgOperand::s
VReg
unsigned llvm::SDDbgOperand::VReg
Valid for registers.
Definition at line 111 of file SDNodeDbgValue.h.
Referenced by fromVReg().
The documentation for this class was generated from the following file:
lib/CodeGen/SelectionDAG/SDNodeDbgValue.h