LLVM: llvm::AMDGPUMCInstLower Class Reference
llvm::AMDGPUMCInstLower Class Reference
#include "Target/AMDGPU/AMDGPUMCInstLower.h"
Public Member Functions
AMDGPUMCInstLower (MCContext &ctx, const TargetSubtargetInfo &ST, const AsmPrinter &AP)
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp) const
void lower (const MachineInstr *MI, MCInst &OutMI) const
Lower a MachineInstr to an MCInst.
void lowerT16D16Helper (const MachineInstr *MI, MCInst &OutMI) const
void lowerT16FmaMixFP16 (const MachineInstr *MI, MCInst &OutMI) const
Detailed Description
Definition at line 26 of file AMDGPUMCInstLower.h.
Constructor & Destructor Documentation
AMDGPUMCInstLower()
AMDGPUMCInstLower::AMDGPUMCInstLower (MCContext & ctx, const TargetSubtargetInfo & ST, const AsmPrinter & AP)
Definition at line 43 of file AMDGPUMCInstLower.cpp.
Member Function Documentation
lower()
void AMDGPUMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Lower a MachineInstr to an MCInst.
Definition at line 212 of file AMDGPUMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::CallingConv::C, llvm::MCOperand::createImm(), llvm::MCInst::getNumOperands(), lowerOperand(), lowerT16D16Helper(), lowerT16FmaMixFP16(), MI, llvm::MCInst::setOpcode(), and TII.
lowerOperand()
bool AMDGPUMCInstLower::lowerOperand (const MachineOperand & MO, MCOperand & MCOp) const
Definition at line 74 of file AMDGPUMCInstLower.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::AMDGPU::getMCReg(), llvm::MachineOperand::getMCSymbol(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getReg(), llvm::getSpecifier(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::MCSymbol::getVariableValue(), llvm_unreachable, llvm::MachineOperand::MO_ExternalSymbol, llvm::SIInstrInfo::MO_FAR_BRANCH_OFFSET, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_MCSymbol, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, and llvm::Offset.
Referenced by lower(), lowerT16D16Helper(), and lowerT16FmaMixFP16().
lowerT16D16Helper()
void AMDGPUMCInstLower::lowerT16D16Helper (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 126 of file AMDGPUMCInstLower.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), llvm::MachineOperand::getReg(), llvm::AMDGPU::hasNamedOperand(), I, llvm::AMDGPU::isHi16Reg(), llvm_unreachable, lowerOperand(), MI, llvm::MCInst::setOpcode(), TII, and TRI.
Referenced by lower().
lowerT16FmaMixFP16()
void AMDGPUMCInstLower::lowerT16FmaMixFP16 (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 178 of file AMDGPUMCInstLower.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), llvm::MachineOperand::getReg(), I, llvm::AMDGPU::isHi16Reg(), lowerOperand(), MI, llvm::MCInst::setOpcode(), TII, and TRI.
Referenced by lower().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUMCInstLower.h
lib/Target/AMDGPU/AMDGPUMCInstLower.cpp