LLVM: llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
#include "llvm/ADT/DenseMap.h"
Inherits llvm::DebugEpochBase.
Inherited by llvm::DenseMap< const BlockT *, const BlockT * >, llvm::DenseMap< unsigned, TreeTy * >, llvm::DenseMap< AssumeInst *, MinMax >, llvm::DenseMap< RetainedKnowledgeKey, Assume2KnowledgeMap >, llvm::DenseMap< const BasicBlock *, int >, llvm::DenseMap< const BasicBlock *, uint32_t >, llvm::DenseMap< GlobalValue::GUID, uint64_t >, llvm::DenseMap< const NodeType *, const PiBlockDDGNode * >, llvm::DenseMap< Instruction *, NodeType * >, llvm::DenseMap< Instruction *, size_t >, llvm::DenseMap< NodeType *, size_t >, llvm::DenseMap< BlockT *, DomSetType >, llvm::DenseMap< CallInst *, unsigned >, llvm::DenseMap< const Instruction *, Embedding >, llvm::DenseMap< const BasicBlock *, Embedding >, llvm::DenseMap< const Value *, WeakEvalType >, llvm::DenseMap< Instruction *, MemDepResult >, llvm::DenseMap< ValueIsLoadPair, NonLocalPointerInfo >, llvm::DenseMap< Instruction *, PerInstNLInfo >, llvm::DenseMap< LoadInst *, int32_t >, llvm::DenseMap< BlockT *, BlockT * >, llvm::DenseMap< BlockT *, RegionT * >, llvm::DenseMap< const SCEV *, bool >, llvm::DenseMap< const SCEV *, ValueSetVector >, llvm::DenseMap< SCEVCallbackVH, const SCEV *, DenseMapInfo< Value * > >, llvm::DenseMap< const Value *, Value * >, llvm::DenseMap< const Value *, const SCEV * >, llvm::DenseMap< const Loop *, const SCEV * >, llvm::DenseMap< const BasicBlock *, BlockLifetimeInfo >, llvm::DenseMap< unsigned, HashNode * >, llvm::DenseMap< const HashNode *, unsigned >, llvm::DenseMap< const MachineBasicBlock *, uint64_t >, llvm::DenseMap< Edge, uint64_t >, llvm::DenseMap< const Value *, StatepointRelocationRecord >, llvm::DenseMap< const Function *, GCFunctionInfo * >, llvm::const_iterator<, >, llvm::const_iterator<, >, llvm::DenseMap< LLT, LegacyLegalizeActions::LegacyLegalizeAction >, llvm::DenseMap< const TargetSubtargetInfo *, LibcallLoweringInfo >, llvm::DenseMap< const MachineInstr *, CallSiteInfo >, llvm::DenseMap< const MachineInstr *, CalledGlobalInfo >, llvm::DenseMap< SUnit *, OrderDep >, llvm::DenseMap< unsigned, unsigned >, llvm::DenseMap< MachineInstr *, MachineInstr * >, llvm::DenseMap< const MachineInstr *, Embedding >, llvm::DenseMap< const MachineBasicBlock *, Embedding >, llvm::DenseMap< Register, Register >, llvm::DenseMap< const MachineInstr *, SlotIndex >, llvm::DenseMap< const AllocaInst *, MachineFrameInfo::SSPLayoutKind >, llvm::DenseMap< uint64_t, RelocAddrEntry >, llvm::DenseMap< uint64_t, CompileUnit * >, llvm::DenseMap< T, uint64_t >, llvm::DenseMap< orc::SymbolStringPtr, orc::ExecutorSymbolDef >, llvm::DenseMap< orc::SymbolStringPtr, SymbolLookupFlags >, llvm::DenseMap< SymbolStringPtr, SymbolAliasMapEntry >, llvm::DenseMap< SymbolStringPtr, MaterializingInfo >, llvm::DenseMap< SymbolStringPtr, SymbolTableEntry >, llvm::DenseMap< SymbolStringPtr, JITDispatchHandlerFunction >, llvm::DenseMap< SymbolStringPtr, ExecutorSymbolDef >, llvm::DenseMap< SymbolStringPtr, JITSymbolFlags >, llvm::DenseMap< JITDylib *, SymbolNameSet >, llvm::DenseMap< ExecutorAddr, Allocation >, llvm::DenseMap< void *, Reservation >, llvm::DenseMap< SymbolStringPtr, ExtraSymbolInfo >, llvm::DenseMap< uint64_t, IncomingWFRHandler >, llvm::DenseMap< const BasicBlock *, WalkDirection >, llvm::DenseMap< Alias, AliaseeDetails >, llvm::DenseMap< SymbolStringPtr, SymbolNameSet >, llvm::DenseMap< TargetFAddr, SymbolNameSet >, llvm::DenseMap< uint64_t, std::promise< shared::WrapperFunctionBuffer > * >, llvm::DenseMap< ContainerId, ElementSet >, llvm::DenseMap< GlobalValue::GUID, GlobalValueSummary * >, llvm::DenseMap< IRUnitT *, AnalysisResultListT >, llvm::DenseMap< IndexPair, stable_hash >, llvm::DenseMap< ValueMapCVH, ValueT, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const Metadata *, TrackingMDRef >, llvm::DenseMap< uint64_t, uint64_t >, llvm::DenseMap< const void *, const PassInfo * >, llvm::DenseMap< unsigned, TVRowPair >, llvm::DenseMap< unsigned, LineColPair >, llvm::DenseMap< const llvm::Function *, FunctionSnapshot >, llvm::DenseMap< NodePtr, unsigned >, llvm::DenseMap< ObjectKey, Value, llvm::DenseMapInfo< StringRef > >, llvm::DenseMap< char, std::string >, llvm::DenseMap< SymbolsMapKey, Symbol * >, llvm::DenseMap< unsigned, InstructionVectorTy * >, llvm::const_iterator< StringRef, ImportMapTy >, llvm::DenseMap< Value *, Constant * >, llvm::DenseMap< ConstPtrUnionType, unsigned >, llvm::DenseMap< DbgSSABlock *, DbgValueDef >, llvm::DenseMap< const BasicBlockT *, uint64_t >, llvm::DenseMap< const BasicBlockT *, const BasicBlockT * >, llvm::DenseMap< const FunctionSamples *, BodySampleCoverageMap >, llvm::DenseMap< BlkT *, ValT >, llvm::DenseMap< BlkT *, BBInfo * >, llvm::DenseMap< EdgeIdentifier, EdgeAttribute >, llvm::DenseMap< VertexIdentifier, VertexAttribute >, llvm::DenseMap< VertexIdentifier, NeighborSetT >, llvm::DenseMap< Function *, Function * >, llvm::DenseMap< Type *, unsigned >, llvm::DenseMap< const Value *, unsigned >, llvm::DenseMap< const Metadata *, MDIndex >, llvm::DenseMap< IndexAndAttrSet, unsigned >, llvm::DenseMap< AttributeList, unsigned >, llvm::DenseMap< const Instruction *, unsigned >, llvm::DenseMap< MCSymbol *, PadRange >, llvm::DenseMap< unsigned, FragsInMemMap >, llvm::DenseMap< Value *, Value * >, llvm::DenseMap< const LexicalScope *, const DILocation * >, llvm::DenseMap< Register, MachineInstr * >, llvm::DenseMap< MachineBasicBlock *, MachineBasicBlock::iterator >, llvm::DenseMap< Register, UserValue * >, llvm::DenseMap< DebugVariable, UserValue * >, llvm::DenseMap< MachineInstr *, unsigned >, llvm::DenseMap< MachineBasicBlock *, Register >, llvm::DenseMap< const MachineInstr *, unsigned >, llvm::DenseMap< Register, const MachineInstr * >, llvm::DenseMap< BBVRegPair, unsigned >, llvm::DenseMap< MachineInstr *, Register, MachineInstrExpressionTrait >, llvm::DenseMap< IKey, PBQPRAGraph::MatrixPtr >, llvm::DenseMap< const MachineBasicBlock *, BlockLifetimeInfo >, llvm::DenseMap< const MachineBasicBlock *, BitVector >, llvm::DenseMap< unsigned, StringEntry * >, llvm::DenseMap< uint64_t, DwarfUnit * >, llvm::DenseMap< const StringEntry *, DwarfStringPoolEntryWithExtString * >, llvm::DenseMap< void *, unsigned int >, llvm::DenseMap< const void *, MethodAddressVector >, llvm::DenseMap< orc::ExecutorAddr, CIEInformation >, llvm::iterator<, unsigned >, llvm::iterator< AttributeSet, unsigned >, llvm::iterator< GUID, unsigned >, llvm::DenseMap< StructType *, StructLayout * >, llvm::DenseMap< Value *, ValueHandleBase * >, llvm::DenseMap< const MCSymbol *, unsigned >, llvm::DenseMap< MCSymbol const *, COFFSymbol * >, llvm::DenseMap< MCSection const *, COFFSection * >, llvm::DenseMap< StringRef, Option * >, llvm::DenseMap< Instruction *, Uses >, llvm::DenseMap< unsigned, LaneBitmask >, llvm::DenseMap< const MCExpr *, KnownBits >, llvm::DenseMap< MachineInstr *, MemAddress >, llvm::DenseMap< unsigned, const MCExpr * >, llvm::DenseMap< const Value *, Type * >, llvm::DenseMap< unsigned, ExtType >, llvm::DenseMap< unsigned, IFListType >, llvm::DenseMap< unsigned, DefUseInfo >, llvm::DenseMap< RegSubRegPair, RegSubRegPair >, llvm::DenseMap< MachineInstr *, bool >, llvm::DenseMap< unsigned, uint64_t >, llvm::DenseMap< Instruction *, Instruction * >, llvm::iterator< MCRegister, PredSet >, llvm::DenseMap< const TargetRegisterClass *, VRegMap >, llvm::DenseMap< int, int >, llvm::DenseMap< KeyT, size_t >, llvm::DenseMap< BasicBlock *, CloneList >, llvm::DenseMap< const BasicBlock *, const PHINode * >, llvm::DenseMap< const BasicBlock *, bool >, llvm::DenseMap< Instruction *, int >, llvm::DenseMap< const SCEV *, RegSortData >, llvm::DenseMap< LSRUse::SCEVUseKindPair, size_t >, llvm::DenseMap< const Expression *, CongruenceClass * >, llvm::DenseMap< const BasicBlock *, CandsTy >, llvm::DenseMap< BasicBlock *, Instruction * >, llvm::DenseMap< Instruction *, Value * >, llvm::DenseMap< const MDNode *, TrackingMDNodeRef >, llvm::DenseMap< BasicBlock *, Value * >, llvm::DenseMap< VPBasicBlock *, VPValue * >, llvm::DenseMap< InterleaveGroup< Instruction > *, InterleaveGroup< VPInstruction > * >, llvm::DenseMap< BasicBlock *, DomSetType >, llvm::DenseMap< const llvm::DILocation *, const llvm::sampleprof::FunctionSamples * >, llvm::DenseMap< const MachineBasicBlock *, MachineLoop * >, llvm::DenseMap< unsigned, llvm::jitlink::Block * >, llvm::DenseMap< unsigned, llvm::jitlink::Symbol * >, llvm::DenseMap< llvm::orc::SymbolStringPtr, llvm::jitlink::Symbol * >, llvm::DenseMap< llvm::StringRef, llvm::object::SectionRef >, llvm::DenseMap< llvm::GlobalVariable *, llvm::GlobalVariable * >, llvm::DenseMap< llvm::StringRef, FunctionImporter::ExportSetTy >, llvm::DenseMap< LiveDebugValues::ValueIDNum, LiveDebugValues::DbgOpID >, llvm::DenseMap< llvm::MachineOperand, LiveDebugValues::DbgOpID >, llvm::DenseMap< llvm::DebugVariable, unsigned >, llvm::DenseMap< const llvm::MachineBasicBlock *, unsigned int >, llvm::DenseMap< StackSlotPos, unsigned >, llvm::DenseMap< unsigned, StackSlotPos >, llvm::DenseMap< llvm::DILocalScope *, llvm::DISubprogram * >, llvm::DenseMap< llvm::Value *, llvm::BasicBlock * >, llvm::DenseMap< llvm::hash_code, unsigned >, llvm::DenseMap< constSCEV *, llvm::ScopedHashTableVal *, KInfo >, llvm::DenseMap< unsigned, TransferTracker::ResolvedDbgValue >, llvm::DenseMap< const llvm::Function *, llvm::AMDGPUFunctionArgInfo >, llvm::DenseMap< const llvm::MachineBasicBlock *, unsigned >, llvm::DenseMap< const llvm::MCSymbol *, AddressPoolEntry >, llvm::DenseMap< llvm::StringRef, unsigned >, llvm::DenseMap< llvm::Function *, llvm::FileLocRange >, llvm::DenseMap< llvm::BasicBlock *, llvm::FileLocRange >, llvm::DenseMap< llvm::Instruction *, llvm::FileLocRange >, llvm::DenseMap< llvm::MBBSectionID, unsigned >, llvm::DenseMap< const llvm::MCSymbol *, unsigned >, llvm::DenseMap< llvm::MBBSectionID, llvm::MCSymbol * >, llvm::DenseMap< llvm::StringRef, llvm::Attribute >, llvm::DenseMap< llvm::Value *, AttributeList >, llvm::DenseMap< AAMapKeyTy, llvm::AbstractAttribute * >, llvm::DenseMap< const llvm::MachineInstr *, unsigned >, llvm::DenseMap< const llvm::MachineBasicBlock *, int >, llvm::DenseMap< Edge, llvm::BranchProbability >, llvm::DenseMap< llvm::UniqueBBID, uint64_t >, llvm::DenseMap< llvm::CSKYTargetStreamer::SymbolIndex, const llvm::MCExpr * >, llvm::DenseMap< const llvm::Function *, uint64_t >, llvm::DenseMap< const llvm::Value *, const llvm::Value * >, llvm::DenseMap< const llvm::BasicBlock *, llvm::InstructionCost >, llvm::DenseMap< const llvm::DIGlobalVariable *, uint64_t >, llvm::DenseMap< const llvm::Function *, unsigned >, llvm::DenseMap< const llvm::DICompositeType *, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::CodeViewDebug::LocalVarDef, unsigned >, llvm::DenseMap< llvm::Instruction *, unsigned >, llvm::DenseMap< llvm::Value *, unsigned >, llvm::DenseMap< llvm::MDNode *, unsigned >, llvm::DenseMap< const llvm::DIE *, unsigned >, llvm::DenseMap< const llvm::BasicBlock *, bool >, llvm::DenseMap< uint64_t, const llvm::DWARFDebugNames::NameIndex * >, llvm::DenseMap< const char *, uint64_t, CStrDenseMapInfo >, llvm::DenseMap< llvm::TargetExtType *, llvm::dxil::ResourceTypeInfo >, llvm::DenseMap< llvm::DebugVariableAggregate, llvm::DbgValueDef >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MCSymbol * >, llvm::DenseMap< llvm::BasicBlock *, llvm::DbgSSABlock * >, llvm::DenseMap< llvm::Instruction *, llvm::APInt >, llvm::DenseMap< const llvm::DILocalScope *, llvm::DIE * >, llvm::DenseMap< const llvm::MDNode *, unsigned >, llvm::DenseMap< const llvm::DIE *, llvm::DwarfCompileUnit * >, llvm::DenseMap< const llvm::MCSymbol *, uint64_t >, llvm::DenseMap< const llvm::MDNode *, uint64_t >, llvm::DenseMap< const llvm::MCSection *, const llvm::MCSymbol * >, llvm::DenseMap< const llvm::DIStringType *, unsigned >, llvm::DenseMap< llvm::LexicalScope *, ScopeVars >, llvm::DenseMap< const llvm::MDNode *, llvm::DIE * >, llvm::DenseMap< llvm::DIE *, const llvm::DINode * >, llvm::DenseMap< const llvm::MCSymbolELF *, const llvm::MCSymbolELF * >, llvm::DenseMap< ElemTy, llvm::EquivalenceClasses::ECValue * >, llvm::DenseMap< llvm::GlobalVariable *, MutableValue >, llvm::DenseMap< const llvm::Value *, llvm::Register >, llvm::DenseMap< llvm::Instruction *, llvm::EquivalenceClasses::ECValue * >, llvm::DenseMap< const llvm::Value *, int >, llvm::DenseMap< const llvm::Comdat *, llvm::Comdat * >, llvm::DenseMap< llvm::StringRef, llvm::FunctionImporter::ImportMapTy >, llvm::DenseMap< llvm::Register, const llvm::Value * >, llvm::DenseMap< const llvm::AllocaInst *, int >, llvm::DenseMap< const Argument *, int >, llvm::DenseMap< llvm::Register, llvm::Register >, llvm::DenseMap< const llvm::Value *, ISD::NodeType >, llvm::DenseMap< llvm::Function *, llvm::CodeMetrics >, llvm::DenseMap< llvm::Function *, unsigned >, llvm::DenseMap< unsigned, llvm::Register >, llvm::DenseMap< const llvm::MachineInstr *, llvm::UniqueMachineInstr * >, llvm::DenseMap< llvm::MachineInstr *, unsigned >, llvm::DenseMap< const llvm::Value *, unsigned >, llvm::DenseMap< uint32_t, LeaderListNode >, llvm::DenseMap< llvm::Value *, uint32_t >, llvm::DenseMap< llvm::GVNPass::Expression, uint32_t >, llvm::DenseMap< uint32_t, llvm::PHINode * >, llvm::DenseMap< uint32_t, llvm::BasicBlock * >, llvm::DenseMap< const InstructionT *, const InstructionT * >, llvm::DenseMap< BlockT *, llvm::GenericCycle * >, llvm::DenseMap< BlockT *, DFSInfo >, llvm::DenseMap< const llvm::Value *, const llvm::GlobalValue * >, llvm::DenseMap< const llvm::Function *, GlobalsAAResult::FunctionInfo >, llvm::DenseMap< llvm::MCRegister, PredSet >, llvm::DenseMap< llvm::Value *, llvm::Value * >, llvm::DenseMap< llvm::IRSimilarity::IRInstructionData *, unsigned, llvm::IRSimilarity::IRInstructionDataTraits >, llvm::DenseMap< llvm::BasicBlock *, unsigned >, llvm::DenseMap< unsigned, llvm::Value * >, llvm::DenseMap< const llvm::Value *, llvm::SmallVector< Register, 1 > * >, llvm::DenseMap< const llvm::Type *, llvm::SmallVector< uint64_t, 1 > * >, llvm::DenseMap< const llvm::Function *, FunctionInfo * >, llvm::DenseMap< SymbolRemappingReader::Key, llvm::StringRef >, llvm::DenseMap< uint64_t, llvm::GlobalVariable * >, llvm::DenseMap< const llvm::BasicBlock *, const llvm::Instruction * >, llvm::DenseMap< int32_t, InstTy * >, llvm::DenseMap< llvm::Instruction *, llvm::InterleaveGroup< llvm::Instruction > * >, llvm::DenseMap< unsigned, llvm::GlobalValue * >, llvm::DenseMap< llvm::Module *, unsigned >, llvm::DenseMap< const llvm::Value *, llvm::StringMapEntry< Value * > * >, llvm::DenseMap< llvm::Value *, llvm::ValueAsMetadata * >, llvm::DenseMap< llvm::Metadata *, llvm::MetadataAsValue * >, llvm::DenseMap< const llvm::BasicBlock *, llvm::BlockAddress * >, llvm::DenseMap< const llvm::GlobalValue *, llvm::DSOLocalEquivalent * >, llvm::DenseMap< const llvm::GlobalValue *, llvm::NoCFIValue * >, llvm::DenseMap< unsigned, llvm::IntegerType * >, llvm::DenseMap< unsigned, llvm::PointerType * >, llvm::DenseMap< const llvm::Value *, llvm::MDAttachments >, llvm::DenseMap< const llvm::GlobalObject *, llvm::StringRef >, llvm::DenseMap< const llvm::GlobalValue *, llvm::StringRef >, llvm::DenseMap< const llvm::GlobalValue *, llvm::GlobalValue::SanitizerMetadata >, llvm::DenseMap< const llvm::Function *, std::string >, llvm::DenseMap< PassID, CompatibilityCheckFn >, llvm::DenseMap< const llvm::Function *, llvm::LazyCallGraph::Node * >, llvm::DenseMap< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * >, llvm::DenseMap< llvm::LazyCallGraph::RefSCC *, int >, llvm::DenseMap< llvm::LazyCallGraph::Node *, int >, llvm::DenseMap< const llvm::DISubprogram *, const llvm::Function * >, llvm::DenseMap< unsigned, llvm::BitVector >, llvm::DenseMap< llvm::MCSection *, const llvm::MCSymbolRefExpr * >, llvm::DenseMap< llvm::Value *, const llvm::SCEV * >, llvm::DenseMap< const BlockT *, LoopT * >, llvm::DenseMap< llvm::ElementCount, unsigned >, llvm::DenseMap< llvm::Instruction *, llvm::Instruction * >, llvm::DenseMap< const llvm::Value *, const llvm::RuntimeCheckingPtrGroup * >, llvm::DenseMap< const llvm::RuntimeCheckingPtrGroup *, llvm::MDNode * >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::BlockFrequency >, llvm::DenseMap< uint32_t, llvm::StringRef >, llvm::DenseMap< unsigned, llvm::MCCVFunctionInfo::LineInfo >, llvm::DenseMap< unsigned, llvm::MCLabel * >, llvm::DenseMap< llvm::MCRegister, int >, llvm::DenseMap< const llvm::MCSection *, unsigned >, llvm::DenseMap< const llvm::MCSection *, uint64_t >, llvm::DenseMap< const llvm::MachineBasicBlock *, uint64_t >, llvm::DenseMap< llvm::MachineBasicBlock *, DomSetType >, llvm::DenseMap< llvm::MCSymbol *, unsigned >, llvm::DenseMap< unsigned, llvm::MachineFunction::DebugPHIRegallocPos >, llvm::DenseMap< llvm::MCSymbol *, StubValueTy >, llvm::DenseMap< llvm::MCSymbol *, const llvm::MCExpr * >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MachineTraceMetrics::InstrCycles >, llvm::DenseMap< const llvm::GlobalValue *, unsigned >, llvm::DenseMap< const llvm::Init *, MappedValue >, llvm::DenseMap< KeyT, unsigned >, llvm::DenseMap< const llvm::Value *, llvm::MemoryAccess * >, llvm::DenseMap< const llvm::MemoryAccess *, unsigned long >, llvm::DenseMap< const llvm::MachineInstr *, InstType >, llvm::DenseMap< const BlockT *, unsigned >, llvm::DenseMap< uint64_t, unsigned >, llvm::DenseMap< llvm::MachineInstr *, int >, llvm::DenseMap< unsigned, T >, llvm::DenseMap< unsigned, llvm::Constant * >, llvm::DenseMap< llvm::Register, unsigned >, llvm::DenseMap< AnalysisID, llvm::Pass * >, llvm::DenseMap< llvm::Pass *, llvm::Pass * >, llvm::DenseMap< llvm::Pass *, llvm::AnalysisUsage * >, llvm::DenseMap< AnalysisID, const llvm::PassInfo * >, llvm::DenseMap< AnalysisID, llvm::IdentifyingPassPtr >, llvm::DenseMap< llvm::StringRef, std::string >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::BitVector >, llvm::DenseMap< llvm::MachineInstr *, llvm::MachineInstr * >, llvm::DenseMap< unsigned, llvm::MachineBasicBlock * >, llvm::DenseMap< llvm::Register, llvm::VRegInfo * >, llvm::DenseMap< unsigned, int >, llvm::DenseMap< unsigned, const llvm::Value * >, llvm::DenseMap< const llvm::PHINode *, unsigned int >, llvm::DenseMap< unsigned, llvm::GCNRegPressure >, llvm::DenseMap< const llvm::Value *, const llvm::PredicateBase * >, llvm::DenseMap< llvm::Value *, unsigned int >, llvm::DenseMap< const llvm::SCEV *, RewriteEntry >, llvm::DenseMap< ValueMapCVH, SCEVWrapPredicate::IncrementWrapFlags, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< T, ptrdiff_t >, llvm::DenseMap< int, uint64_t >, llvm::DenseMap< llvm::StringRef, uint64_t >, llvm::DenseMap< uint64_t, llvm::PseudoProbeDescriptor >, llvm::DenseMap< const llvm::MCSection *, ElfMappingSymbol >, llvm::DenseMap< const llvm::Init *, const llvm::Init * >, llvm::DenseMap< unsigned, llvm::MachineInstr * >, llvm::DenseMap< llvm::MCRegister, const llvm::TargetRegisterClass * >, llvm::DenseMap< SID, SID >, llvm::DenseMap< llvm::Value *, llvm::ValueLatticeElement >, llvm::DenseMap< llvm::GlobalVariable *, llvm::ValueLatticeElement >, llvm::DenseMap< const llvm::SCEV *, const llvm::Loop * >, llvm::DenseMap< int, llvm::SIMachineFunctionInfo::VGPRSpillToAGPR >, llvm::DenseMap< unsigned, llvm::MCRegister >, llvm::DenseMap< const llvm::Function *, llvm::MCRegister >, llvm::DenseMap< const llvm::Function *, llvm::SPIRV::FPFastMathDefaultInfoVector >, llvm::DenseMap< llvm::MachineInstr *, const llvm::Type * >, llvm::DenseMap< const llvm::Function *, const llvm::MachineOperand * >, llvm::DenseMap< const llvm::MachineInstr *, const llvm::Function * >, llvm::DenseMap< const llvm::MachineOperand *, const llvm::Function * >, llvm::DenseMap< llvm::Value *, llvm::Type * >, llvm::DenseMap< const llvm::Type *, llvm::MachineInstr * >, llvm::DenseMap< const llvm::MachineFunction *, llvm::MachineInstr * >, llvm::DenseMap< const llvm::Function *, llvm::TypedPointerType * >, llvm::DenseMap< llvm::Value *, llvm::CallInst * >, llvm::DenseMap< SPIRV::IRHandleMF, SPIRV::MIHandle >, llvm::DenseMap< const llvm::MachineInstr *, SPIRV::IRHandleMF >, llvm::DenseMap< uint64_t, std::string >, llvm::DenseMap< ValueMapCVH, uint64_t, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< uint64_t, llvm::StringRef >, llvm::DenseMap< llvm::ScalarEvolution::FoldID, const llvm::SCEV * >, llvm::DenseMap< const llvm::SCEV *, llvm::APInt >, llvm::DenseMap< const llvm::Loop *, BackedgeTakenInfo >, llvm::DenseMap< llvm::PHINode *, llvm::Constant * >, llvm::DenseMap< const llvm::Loop *, LoopProperties >, llvm::DenseMap< const llvm::SCEV *, llvm::ConstantRange >, llvm::DenseMap< const llvm::SCEV *, const llvm::SCEV * >, llvm::DenseMap< llvm::MachineInstr *, llvm::SUnit * >, llvm::DenseMap< K, llvm::ScopedHashTableVal *, KInfo >, llvm::DenseMap< K, llvm::ScopedHashTableVal *, DenseMapInfo< K > >, llvm::DenseMap< const llvm::SDNode *, NodeExtraInfo >, llvm::DenseMap< llvm::MCSymbol *, llvm::SDNode * >, llvm::DenseMap< const llvm::Value *, llvm::SDValue >, llvm::DenseMap< const llvm::Constant *, llvm::Register >, llvm::DenseMap< llvm::AttributeSet, unsigned >, llvm::DenseMap< LatticeKey, LatticeVal >, llvm::DenseMap< const llvm::AllocaInst *, unsigned >, llvm::DenseMap< llvm::SDValue, llvm::SDValue >, llvm::DenseMap< const llvm::Constant *, uint64_t >, llvm::DenseMap< llvm::CachedHashStringRef, uint8_t >, llvm::DenseMap< llvm::CachedHashStringRef, size_t >, llvm::DenseMap< unsigned, llvm::SuffixTreeNode * >, llvm::DenseMap< const llvm::MDNode *, TBAABaseNodeSummary >, llvm::DenseMap< const llvm::MDNode *, bool >, llvm::DenseMap< llvm::Register, AvailableValsTy >, llvm::DenseMap< unsigned, std::string >, llvm::DenseMap< unsigned int, unsigned int >, llvm::DenseMap< PartialReduceActionTypes, LegalizeAction >, llvm::DenseMap< llvm::Value *, SimplifiedAddress >, llvm::DenseMap< int32_t, llvm::Instruction * >, llvm::DenseMap< llvm::VPInstruction *, llvm::InterleaveGroup< llvm::VPInstruction > * >, llvm::DenseMap< llvm::VPBasicBlock *, llvm::VPValue * >, llvm::DenseMap< llvm::Instruction *, llvm::VPRecipeBase * >, llvm::DenseMap< const llvm::Instruction *, unsigned >, llvm::DenseMap< const llvm::VPValue *, std::string >, llvm::DenseMap< const llvm::VPValue *, llvm::Value * >, llvm::DenseMap< const llvm::VPValue *, llvm::Type * >, llvm::DenseMap< const llvm::BasicBlock *, unsigned >, llvm::DenseMap< llvm::Register, llvm::ShapeT >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::WebAssemblyException * >, llvm::DenseMap< const llvm::Instruction *, int >, llvm::DenseMap< const llvm::FuncletPadInst *, int >, llvm::DenseMap< const llvm::InvokeInst *, int >, llvm::DenseMap< const llvm::BasicBlock *, int >, llvm::DenseMap< int, unsigned >, llvm::DenseMap< const llvm::Value *, size_t >, llvm::DenseMap< llvm::StringRef, llvm::cl::Option * >, llvm::DenseMap< uint32_t, uint32_t >, llvm::DenseMap< llvm::codeview::GloballyHashedType, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::codeview::LocallyHashedType, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::coverage::CounterExpression, unsigned >, llvm::DenseMap< const llvm::StringMapEntry< EmptyStringSetTag > *, uint64_t >, llvm::DenseMap< const llvm::Function *, llvm::dxil::ComputedShaderFlags >, llvm::DenseMap< llvm::gsym::FileEntry, uint32_t >, llvm::DenseMap< uint64_t, llvm::CachedHashStringRef >, llvm::DenseMap< llvm::orc::SymbolStringPtr, llvm::orc::SymbolStringPtr >, llvm::DenseMap< llvm::jitlink::Section *, llvm::jitlink::SectionRange >, llvm::DenseMap< Edge::OffsetT, EdgeTarget >, llvm::DenseMap< llvm::orc::ExecutorAddr, llvm::jitlink::Symbol * >, llvm::DenseMap< unsigned, llvm::jitlink::MachOLinkGraphBuilder::NormalizedSection >, llvm::DenseMap< uint32_t, llvm::jitlink::MachOLinkGraphBuilder::NormalizedSymbol * >, llvm::DenseMap< uint16_t, SectionEntry >, llvm::DenseMap< uint32_t, llvm::jitlink::Block * >, llvm::DenseMap< uint32_t, llvm::jitlink::Symbol * >, llvm::DenseMap< llvm::StringRef, StubMapEntry >, llvm::DenseMap< uint64_t, uint32_t >, llvm::DenseMap< SymbolHandleRef, unsigned >, llvm::DenseMap< llvm::AllocaInst *, unsigned >, llvm::DenseMap< llvm::CallInst *, llvm::CallBase * >, llvm::DenseMap< llvm::StringRef, llvm::StringRef >, llvm::DenseMap< size_t, llvm::objcopy::coff::Symbol * >, llvm::DenseMap< ssize_t, llvm::objcopy::coff::Section * >, llvm::DenseMap< minidump::StreamType, std::size_t >, llvm::DenseMap< unsigned, OptRange >, llvm::DenseMap< llvm::orc::JITDylib *, llvm::orc::ExecutorAddr >, llvm::DenseMap< llvm::orc::ExecutorAddr, llvm::orc::JITDylib * >, llvm::DenseMap< llvm::orc::JITDylib *, llvm::orc::SymbolLookupSet >, llvm::DenseMap< llvm::orc::JITDylib *, uint64_t >, llvm::DenseMap< llvm::orc::ResourceTracker *, SymbolNameVector >, llvm::DenseMap< llvm::orc::ExecutorAddr, llvm::orc::LazyReexportsManager::CallThroughInfo >, llvm::DenseMap< llvm::orc::NonOwningSymbolStringPtr, llvm::orc::JITDylib * >, llvm::DenseMap< llvm::orc::JITDylib *, ObjCImageInfo >, llvm::DenseMap< llvm::orc::ExecutorAddr, uint64_t >, llvm::DenseMap< llvm::orc::SymbolStringPtr, size_t >, llvm::DenseMap< uint32_t, std::string >, llvm::DenseMap< llvm::codeview::TypeIndex, uint32_t >, llvm::DenseMap< uint32_t, llvm::MachineBasicBlock * >, llvm::DenseMap< uint32_t, RefMap >, llvm::DenseMap< const llvm::Value *, llvm::Align >, llvm::DenseMap< decltype(hash_value(llvm::sampleprof::FunctionId())), llvm::sampleprof::ProfiledCallGraphNode *, MapTArgs... >, llvm::DenseMap< llvm::hash_code, uint64_t >, llvm::DenseMap< llvm::sampleprof::FunctionId, unsigned >, llvm::DenseMap< llvm::sampleprof::SampleContext, unsigned >, llvm::DenseMap< llvm::sandboxir::Context::CallbackID, unsigned >, llvm::DenseMap< llvm::sandboxir::Value *, llvm::sandboxir::Action * >, llvm::DenseMap< llvm::sandboxir::Instruction *, llvm::sandboxir::SeedBundle * >, llvm::DenseMap< NodeRef, unsigned >, llvm::DenseMap< const llvm::object::ObjectFile *, std::string >, llvm::DenseMap< unsigned, TrieNode * >, llvm::DenseMap< BasicBlock *, unsigned >, llvm::SmallDenseMap< LocPair, CacheEntry, 8 >, llvm::SmallDenseMap< MemoryPhi *, MemoryAccess * >, llvm::SmallDenseMap< uint64_t, InstrProfRecord >, llvm::SmallDenseMap< NodePtr, DeletesInserts >, llvm::SmallDenseMap< const Loop *, Loop *, 4 >, llvm::SmallDenseMap< const GlobalValue *, ModRefInfo, 16 >, llvm::SmallDenseMap< PHINode *, size_t, 32 >, llvm::SmallDenseMap< LocIdx, ValueIDNum >, llvm::SmallDenseMap< const MachineBasicBlock *, DbgValue *, 16 >, llvm::SmallDenseMap< RegSubRegPair, ValueTrackerResult >, llvm::SmallDenseMap< SDValue, Register, 16 >, llvm::SmallDenseMap< const PHINode *, PhiInfo, 16 >, llvm::SmallDenseMap< Register, TiedPairList >, llvm::SmallDenseMap< uint64_t, uint64_t, 1 >, llvm::SmallDenseMap< Constant *, PromotedConstant, 16 >, llvm::SmallDenseMap< unsigned, unsigned >, llvm::SmallDenseMap< Value *, AllocaAndGEPs >, llvm::iterator<, RootSignatureDesc >, llvm::SmallDenseMap< Value *, Value *, 8 >, llvm::SmallDenseMap< const MDNode *, GlobalVariable *, 8 >, llvm::SmallDenseMap< const MDNode *, std::string, 8 >, llvm::SmallDenseMap< Function *, bool, 8 >, llvm::SmallDenseMap< BasicBlock *, Value *, 16 >, llvm::SmallDenseMap< ValueType, unsigned, N >, llvm::SmallDenseMap< const llvm::SCEV *, const llvm::SCEV * >, llvm::SmallDenseMap< KeyT, unsigned, N >, llvm::SmallDenseMap< T, ptrdiff_t >, llvm::SmallDenseMap< llvm::Instruction *, unsigned >, llvm::SmallDenseMap< llvm::Instruction *, uint64_t >, llvm::SmallDenseMap< unsigned, unsigned, N >, llvm::SmallDenseMap< unsigned, const llvm::DILocation *, 8 >, llvm::SmallDenseMap< llvm::Function *, llvm::DISubprogram *, 16 >, llvm::SmallDenseMap< unsigned, unsigned, 256 >, llvm::SmallDenseMap< unsigned, llvm::AMDGPU::SetOfRulesForOpcode, 128 >, llvm::SmallDenseMap< unsigned, unsigned, 128 >, llvm::SmallDenseMap< unsigned, llvm::AMDGPU::SetOfRulesForOpcode, 64 >, llvm::SmallDenseMap< int, llvm::KernArgPreloadDescriptor >, llvm::SmallDenseMap< const llvm::GlobalValue *, unsigned, 4 >, llvm::SmallDenseMap< llvm::AnalysisKey *, bool, 8 >, llvm::SmallDenseMap< llvm::Use *, unsigned, N >, llvm::SmallDenseMap< llvm::Value *, unsigned, N >, llvm::SmallDenseMap< const llvm::BasicBlock *, uint32_t >, llvm::SmallDenseMap< LoopData, uint32_t >, llvm::SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t >, llvm::SmallDenseMap< llvm::SDValue, unsigned, 8 >, llvm::SmallDenseMap< unsigned, llvm::SDValue, 8 >, llvm::SmallDenseMap< unsigned, unsigned, 8 >, llvm::SmallDenseMap< llvm::LLT, unsigned, 64 >, llvm::SmallDenseMap< llvm::SDNode *, int >, llvm::SmallDenseMap< const llvm::Value *, int >, llvm::SmallDenseMap< llvm::BasicBlock *, DeletesInserts >, llvm::SmallDenseMap< llvm::BasicBlock *, llvm::DbgMarker * >, llvm::SmallDenseMap< llvm::Loop *, ptrdiff_t >, llvm::SmallDenseMap< llvm::LazyCallGraph::SCC *, int, 4 >, llvm::SmallDenseMap< uint8_t, unsigned, N >, llvm::SmallDenseMap< llvm::Value *, llvm::Value * >, llvm::SmallDenseMap< llvm::Instruction *, llvm::OffsetSpan, 8 >, llvm::SmallDenseMap< const llvm::Value *, unsigned, N >, llvm::SmallDenseMap< AnalysisID, llvm::ImmutablePass *, 8 >, llvm::SmallDenseMap< llvm::MCRegister, SPIRV::InstructionSet::InstructionSet >, llvm::SmallDenseMap< const llvm::Value *, CaptureComponents, 8 >, llvm::SmallDenseMap< const llvm::VPBasicBlock *, llvm::BasicBlock * >, llvm::SmallDenseMap< const llvm::VPBlockBase *, unsigned >, llvm::SmallDenseMap< unsigned, MDRange, 1 >, llvm::SmallDenseMap< uint32_t, llvm::bfi_detail::IrreducibleGraph::IrrNode *, 4 >, llvm::SmallDenseMap< llvm::StructType *, LegacyStructLayout >, llvm::SmallDenseMap< const llvm::Function *, llvm::mcdxbc::RootSignatureDesc >, llvm::SmallDenseMap< ResourceRef, unsigned >, llvm::SmallDenseMap< TraitProperty, llvm::APInt >, llvm::SmallDenseMap< TreeEntry *, StridedPtrInfo >, llvm::SmallDenseMap< const TreeEntry *, InstructionCost >, llvm::SmallDenseMap< Value *, unsigned >, llvm::SmallDenseMap< const TreeEntry *, WeakTrackingVH >, llvm::SmallDenseMap< const Instruction *, Instruction * >, llvm::SmallDenseMap< AliasCacheKey, bool >, llvm::SmallDenseMap< Instruction *, ScheduleData * >, llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >.
Classes
struct ExactBucketCount
Public Types
using size_type = unsigned
using key_type = KeyT
using mapped_type = ValueT
using value_type = BucketT
using iterator = DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT>
using const_iterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
auto keys ()
auto values ()
auto keys () const
auto values () const
bool empty () const
unsigned size () const
void reserve (size_type NumEntries)
Grow the densemap so that it can contain at least NumEntries items before resizing again.
void clear ()
void shrink_and_clear ()
bool contains (const_arg_type_t< KeyT > Val) const
Return true if the specified key is in the map, false otherwise.
size_type count (const_arg_type_t< KeyT > Val) const
Return 1 if the specified key is in the map, 0 otherwise.
iterator find (const_arg_type_t< KeyT > Val)
const_iterator find (const_arg_type_t< KeyT > Val) const
template<class LookupKeyT>
iterator find_as (const LookupKeyT &Val)
Alternate version of find() which allows a different, and possibly less expensive, key type.
template<class LookupKeyT>
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const_arg_type_t< KeyT > Val) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
template<typename U = std::remove_cv_t<ValueT>>
ValueT lookup_or (const_arg_type_t< KeyT > Val, U &&Default) const
ValueT & at (const_arg_type_t< KeyT > Val)
at - Return the entry for the specified key, or abort if no such entry exists.
const ValueT & at (const_arg_type_t< KeyT > Val) const
at - Return the entry for the specified key, or abort if no such entry exists.
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
std::pair< iterator, bool > insert (std::pair< KeyT, ValueT > &&KV)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (KeyT &&Key, Ts &&...Args)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (const KeyT &Key, Ts &&...Args)
template<typename LookupKeyT>
std::pair< iterator, bool > insert_as (std::pair< KeyT, ValueT > &&KV, const LookupKeyT &Val)
Alternate version of insert() which allows a different, and possibly less expensive, key type.
template<typename InputIt>
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
template<typename Range>
void insert_range (Range &&R)
Inserts range of 'std::pair<KeyT, ValueT>' values into the map.
template<typename V>
std::pair< iterator, bool > insert_or_assign (const KeyT &Key, V &&Val)
template<typename V>
std::pair< iterator, bool > insert_or_assign (KeyT &&Key, V &&Val)
template<typename... Ts>
std::pair< iterator, bool > emplace_or_assign (const KeyT &Key, Ts &&...Args)
template<typename... Ts>
std::pair< iterator, bool > emplace_or_assign (KeyT &&Key, Ts &&...Args)
bool erase (const KeyT &Val)
void erase (iterator I)
ValueT & operator[] (const KeyT &Key)
ValueT & operator[] (KeyT &&Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
const void * getPointerIntoBucketsArray () const
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
void swap (DerivedT &RHS)
size_t getMemorySize () const
Return the approximate size (in bytes) of the actual map.
Public Member Functions inherited from llvm::DebugEpochBase
void incrementEpoch ()
Protected Member Functions
DenseMapBase ()=default
void initWithExactBucketCount (unsigned NewNumBuckets)
void destroyAll ()
void initEmpty ()
unsigned getMinBucketToReserveForEntries (unsigned NumEntries)
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
void moveFrom (DerivedT &Other)
void copyFrom (const DerivedT &other)
Detailed Description
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT>
class llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
Definition at line 64 of file DenseMap.h.
Member Typedef Documentation
const_iterator
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::const_iterator
Initial value:
DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT, true>
Definition at line 75 of file DenseMap.h.
iterator
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::iterator = DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT>
Definition at line 74 of file DenseMap.h.
key_type
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::key_type = KeyT
Definition at line 70 of file DenseMap.h.
mapped_type
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::mapped_type = ValueT
Definition at line 71 of file DenseMap.h.
size_type
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size_type = unsigned
Definition at line 69 of file DenseMap.h.
value_type
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::value_type = BucketT
Definition at line 72 of file DenseMap.h.
Constructor & Destructor Documentation
DenseMapBase()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::DenseMapBase () protected default
Member Function Documentation
at() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::at (const_arg_type_t< KeyT > Val) inline nodiscard
at - Return the entry for the specified key, or abort if no such entry exists.
Definition at line 224 of file DenseMap.h.
Referenced by slpvectorizer::BoUpSLP::calculateTreeCostAndTrimNonProfitable(), llvm::gatherImportedSummariesForModule(), slpvectorizer::BoUpSLP::getSpillCost(), rewriteGlobalVariablesInConstant(), and simplifySwitchLookup().
at() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::at (const_arg_type_t< KeyT > Val) const inline nodiscard
at - Return the entry for the specified key, or abort if no such entry exists.
Definition at line 232 of file DenseMap.h.
begin() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () inline nodiscard
Definition at line 78 of file DenseMap.h.
Referenced by checkNumberingAndReplaceCommutative(), llvm::DenseMap< const BlockT *, const BlockT * >::DenseMap(), findIrreducibleHeaders(), llvm::MachineModuleInfoImpl::getSortedExprStubs(), LowerShift(), matchScalarReduction(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::SmallDenseMap(), sortOpts(), SRAGlobal(), llvm::UnrollLoop(), and unswitchNontrivialInvariants().
begin() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () const inline nodiscard
Definition at line 84 of file DenseMap.h.
clear()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear () inline
Definition at line 121 of file DenseMap.h.
Referenced by llvm::SystemZTTIImpl::adjustInliningThreshold(), analyzeLoopUnrollCost(), llvm::SampleProfileInference< FT >::apply(), llvm::CloneAndPruneIntoFromInst(), llvm::TemporalProfTraceTy::createBPFunctionNodes(), llvm::LiveDebugVariables::LDVImpl::emitDebugValues(), findCandidateStructures(), forEachWorkListItem(), llvm::MachineModuleInfoImpl::getSortedExprStubs(), inferAlignment(), llvm::MachineSSAUpdater::Initialize(), llvm::SSAUpdater::Initialize(), llvm::Attributor::internalizeFunctions(), mergeConstants(), removeRedundantDbgLocsUsingBackwardScan(), llvm::SSPLayoutAnalysis::requiresStackProtector(), llvm::SSAUpdaterBulk::RewriteAllUses(), and llvm::writeMemProfCallStackArray().
contains()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains (const_arg_type_t< KeyT > Val) const inline nodiscard
Return true if the specified key is in the map, false otherwise.
Definition at line 169 of file DenseMap.h.
Referenced by cacheDIVar(), slpvectorizer::BoUpSLP::calculateTreeCostAndTrimNonProfitable(), checkDependencies(), collectRegionsConstants(), llvm::IRSimilarity::IRSimilarityCandidate::compareAssignmentMapping(), llvm::memprof::computeUndriftMap(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), createFunctionClones(), llvm::VPlan::duplicate(), slpvectorizer::BoUpSLP::getSpillCost(), llvm::Triple::getVulkanVersion(), relocationViaAlloca(), rewriteGEPAsOffset(), llvm::memprof::serializeV3(), llvm::memprof::serializeV4(), simplifyNeonTbl(), and llvm::UnrollLoop().
copyFrom()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom (const DerivedT & other) inline protected
Definition at line 461 of file DenseMap.h.
Referenced by llvm::DenseMap< const BlockT *, const BlockT * >::DenseMap(), llvm::DenseMap< const BlockT *, const BlockT * >::operator=(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::operator=(), and llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::SmallDenseMap().
count()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> size_type llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count (const_arg_type_t< KeyT > Val) const inline nodiscard
Return 1 if the specified key is in the map, 0 otherwise.
Definition at line 174 of file DenseMap.h.
Referenced by llvm::orc::addAliases(), llvm::InstrEmitter::AddDbgValueLocationOps(), analyzeLoopUnrollCost(), llvm::HexagonSubtarget::CallMutation::apply(), buildClonedLoops(), llvm::ComputeCrossModuleImport(), llvm::computeMinimumValueSizes(), llvm::ModuleSummaryIndex::exportToDot(), findIrreducibleHeaders(), fixI8UseChain(), llvm::getEHScopeMembership(), getUnwindDestToken(), getUnwindDestTokenHelper(), HandleInlinedEHPad(), HandlePrefixedOrGroupedOption(), llvm::MachineSSAUpdater::HasValueForBlock(), llvm::SSAUpdater::HasValueForBlock(), insertRelocationStores(), insertRematerializationStores(), llvm::orc::Platform::lookupInitSymbols(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerStatepointMetaArgs(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved(), ProcessSDDbgValues(), llvm::objcopy::macho::Object::removeSections(), slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::objcopy::elf::Object::replaceSections(), selectIncomingValueForBlock(), tryFoldHelper(), llvm::orc::StaticLibraryDefinitionGenerator::tryToGenerate(), and llvm::GenericConvergenceVerifier< ContextT >::verify().
destroyAll()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll () inline protected
Definition at line 391 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::DenseMap< const BlockT *, const BlockT * >::operator=(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::operator=(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear(), llvm::DenseMap< const BlockT *, const BlockT * >::~DenseMap(), and llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::~SmallDenseMap().
emplace_or_assign() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::emplace_or_assign (const KeyT & Key, Ts &&... Args) inline
Definition at line 315 of file DenseMap.h.
emplace_or_assign() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::emplace_or_assign (KeyT && Key, Ts &&... Args) inline
Definition at line 323 of file DenseMap.h.
empty()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty () const inline nodiscard
Definition at line 109 of file DenseMap.h.
Referenced by llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder::add(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::begin(), TransferTracker::checkInstForNewValues(), checkNumberingAndReplaceCommutative(), CompactSwizzlableVector(), llvm::objcarc::createCallInstWithColors(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::orc::CompileOnDemandLayer::emit(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::ModuleSummaryIndex::exportToDot(), findArgParts(), genNeg(), llvm::Attributor::getAttrsFromAssumes(), INITIALIZE_PASS(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), LowerShift(), matchScalarReduction(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved(), OptimizeNonTrivialIFuncs(), populateEHOperandBundle(), ProfitableToMerge(), promoteArguments(), RemoveFromReverseMap(), slpvectorizer::BoUpSLP::reorderTopToBottom(), ReorganizeVector(), llvm::SwingSchedulerDAG::schedule(), SRAGlobal(), llvm::lto::thinBackend(), llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::EPCDynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::ExecutorResolutionGenerator::tryToGenerate(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), and llvm::LoopInfoBase< BlockT, LoopT >::verify().
end() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () inline nodiscard
Definition at line 81 of file DenseMap.h.
Referenced by llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder::add(), addConstantsToTrack(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::SwingSchedulerDAG::applyInstrChange(), AreEquivalentPhiNodes(), assignSections(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::at(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::at(), buildBitSets(), buildClonedLoopBlocks(), slpvectorizer::BoUpSLP::buildExternalUses(), buildFrameDebugInfo(), llvm::calculateSEHStateForAsynchEH(), checkConstHashCompatible(), checkHoistValue(), TransferTracker::checkInstForNewValues(), checkNumberingAndReplaceCommutative(), llvm::CloneAndPruneIntoFromInst(), llvm::ComputeCrossModuleImport(), computeDomSubtreeCost(), llvm::computeEHOnlyBlocks(), computeShapeInfoForInst(), llvm::memprof::computeUndriftMap(), llvm::orc::StaticLibraryDefinitionGenerator::Create(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), createSwitchStatement(), decodeBBAddrMapImpl(), llvm::DenseMap< const BlockT *, const BlockT * >::DenseMap(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), findCandidateStructures(), findDuplicateOutputBlock(), findExtractedInputToOverallInputMapping(), findInsertLocation(), findIrreducibleHeaders(), findOrCreatePHIInBlock(), findOutputMapping(), llvm::SwingSchedulerDAG::fixupRegisterOverlaps(), forwardHandleAccesses(), llvm::gatherImportedSummariesForModule(), generateAssignInstrs(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::SwingSchedulerDAG::getInstrBaseReg(), llvm::WindowScheduler::getIssueOrder(), llvm::TargetLibraryInfoImpl::getLibFunc(), getMappedReg(), llvm::DILocation::getMergedLocation(), getOptionPred(), getOrCreateFPFastMathDefaultInfoVec(), llvm::object::ELFObjectFileBase::getPltEntries(), getPredState(), llvm::MachineModuleInfoImpl::getSortedExprStubs(), slpvectorizer::BoUpSLP::getSpillCost(), getSuccState(), slpvectorizer::BoUpSLP::getTreeCost(), getUnwindDestToken(), getUnwindDestTokenHelper(), getValueOnFirstIteration(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), getWorklist(), llvm::AsmPrinter::handleCallsiteForCallgraph(), llvm::cas::ObjectStore::importObject(), inferInitializes(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::insertDebugValuesForPHIs(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), isBigEndian(), llvm::isEqual(), IsValueFullyAvailableInBlock(), loadObj(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), mapInputsToGVNs(), llvm::CombinerHelper::matchLoadOrCombine(), matchScalarReduction(), mergeConstants(), migrateDebugInfo(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved(), OptimizeNonTrivialIFuncs(), llvm::PeelSingleBlockLoop(), processBlockAddr(), ProfitableToMerge(), llvm::PPCInstrInfo::promoteInstr32To64ForElimEXTSW(), llvm::orc::JITLinkRedirectableSymbolManager::redirect(), reduceDbgValsForwardScan(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), remapExtractedInputs(), RemoveFromReverseMap(), removeUndefDbgLocsFromEntryBlock(), slpvectorizer::BoUpSLP::reorderTopToBottom(), replaceArgumentUses(), replaceUndefValuesInPhi(), llvm::reportMismatch(), resolvePrevailingInIndex(), rewriteGEPAsOffset(), llvm::HipStdParAllocationInterpositionPass::run(), llvm::LoadAndStorePromoter::run(), llvm::lto::LTO::run(), llvm::SelectionDAGISel::runOnMachineFunction(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifyUsingControlFlow(), sinkCommonCodeFromPredecessors(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::SmallDenseMap(), sortOpts(), llvm::SplitModule(), llvm::thinLTOFinalizeInModule(), llvm::thinLTOInternalizeModule(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), undriftMemProfRecord(), llvm::UnrollLoop(), slpvectorizer::BoUpSLP::vectorizeTree(), llvm::GenericConvergenceVerifier< ContextT >::verify(), and llvm::BlockFrequencyInfoImpl< BT >::verifyMatch().
end() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () const inline nodiscard
Definition at line 87 of file DenseMap.h.
erase() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (const KeyT & Val) inline
Definition at line 330 of file DenseMap.h.
Referenced by llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder::add(), analyzeAndPruneOutputBlocks(), llvm::HexagonSubtarget::CallMutation::apply(), slpvectorizer::BoUpSLP::calculateTreeCostAndTrimNonProfitable(), checkNumberingAndReplaceCommutative(), forwardHandleAccesses(), OptimizeFunctions(), reduceDbgValsForwardScan(), RemoveFromReverseMap(), llvm::GlobalValue::removeSanitizerMetadata(), slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::GenericConvergenceVerifier< ContextT >::verify(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), and llvm::LoopInfoBase< MachineBasicBlock, MachineLoop >::verify().
erase() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (iterator I) inline
Definition at line 341 of file DenseMap.h.
find() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const_arg_type_t< KeyT > Val) inline nodiscard
Definition at line 178 of file DenseMap.h.
Referenced by llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder::add(), addConstantsToTrack(), alignOutputBlockWithAggFunc(), llvm::HexagonSubtarget::CallMutation::apply(), AreEquivalentPhiNodes(), assignSections(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::at(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::at(), buildBitSets(), buildClonedLoopBlocks(), slpvectorizer::BoUpSLP::buildExternalUses(), buildFrameDebugInfo(), llvm::calculateSEHStateForAsynchEH(), checkConstHashCompatible(), checkHoistValue(), TransferTracker::checkInstForNewValues(), CheckLargerCands(), checkNumberingAndReplaceCommutative(), llvm::CloneAndPruneIntoFromInst(), collectCallSiteParameters(), llvm::ComputeCrossModuleImport(), computeDomSubtreeCost(), llvm::computeEHOnlyBlocks(), computeShapeInfoForInst(), llvm::memprof::computeUndriftMap(), llvm::orc::StaticLibraryDefinitionGenerator::Create(), llvm::objcarc::createCallInstWithColors(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), createSwitchStatement(), decodeBBAddrMapImpl(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), findCandidateStructures(), findDuplicateOutputBlock(), findExtractedInputToOverallInputMapping(), findInsertLocation(), findOrCreatePHIInBlock(), findOutputMapping(), forwardHandleAccesses(), llvm::gatherImportedSummariesForModule(), generateAssignInstrs(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::WindowScheduler::getIssueOrder(), llvm::TargetLibraryInfoImpl::getLibFunc(), getMappedReg(), llvm::DILocation::getMergedLocation(), getOptionPred(), getOrCreateFPFastMathDefaultInfoVec(), llvm::object::ELFObjectFileBase::getPltEntries(), getPredState(), slpvectorizer::BoUpSLP::getSpillCost(), getSuccState(), slpvectorizer::BoUpSLP::getTreeCost(), getUnwindDestToken(), getUnwindDestTokenHelper(), getValueOnFirstIteration(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), getWorklist(), llvm::AsmPrinter::handleCallsiteForCallgraph(), HandlePrefixedOrGroupedOption(), llvm::cas::ObjectStore::importObject(), inferInitializes(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::insertDebugValuesForPHIs(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), isBigEndian(), llvm::isEqual(), IsValueFullyAvailableInBlock(), loadObj(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), mapInputsToGVNs(), llvm::CombinerHelper::matchLoadOrCombine(), matchScalarReduction(), mergeConstants(), migrateDebugInfo(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved(), OptimizeNonTrivialIFuncs(), llvm::PeelSingleBlockLoop(), populateEHOperandBundle(), processBlockAddr(), ProfitableToMerge(), llvm::PPCInstrInfo::promoteInstr32To64ForElimEXTSW(), llvm::orc::JITLinkRedirectableSymbolManager::redirect(), reduceDbgValsForwardScan(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), remapExtractedInputs(), removeUndefDbgLocsFromEntryBlock(), slpvectorizer::BoUpSLP::reorderTopToBottom(), replaceArgumentUses(), replaceUndefValuesInPhi(), llvm::reportMismatch(), resolvePrevailingInIndex(), rewriteGEPAsOffset(), llvm::HipStdParAllocationInterpositionPass::run(), llvm::LoadAndStorePromoter::run(), llvm::lto::LTO::run(), llvm::SelectionDAGISel::runOnMachineFunction(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifyUsingControlFlow(), sinkCommonCodeFromPredecessors(), sinkInstruction(), llvm::SplitModule(), llvm::thinLTOFinalizeInModule(), llvm::thinLTOInternalizeModule(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), undriftMemProfRecord(), llvm::UnrollLoop(), unswitchNontrivialInvariants(), slpvectorizer::BoUpSLP::vectorizeTree(), llvm::GenericConvergenceVerifier< ContextT >::verify(), and llvm::BlockFrequencyInfoImpl< BT >::verifyMatch().
find() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const_arg_type_t< KeyT > Val) const inline nodiscard
Definition at line 181 of file DenseMap.h.
find_as() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<class LookupKeyT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) inline nodiscard
Alternate version of find() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 191 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::find().
find_as() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<class LookupKeyT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) const inline nodiscard
Definition at line 197 of file DenseMap.h.
getMemorySize()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> size_t llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMemorySize () const inline nodiscard
Return the approximate size (in bytes) of the actual map.
This is just the raw memory used by DenseMap. If entries are pointers to objects, the size of the referenced objects are not included.
Definition at line 704 of file DenseMap.h.
getMinBucketToReserveForEntries()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMinBucketToReserveForEntries (unsigned NumEntries) inline protected
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
Definition at line 426 of file DenseMap.h.
Referenced by llvm::DenseMap< const BlockT *, const BlockT * >::DenseMap(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), and llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::SmallDenseMap().
getPointerIntoBucketsArray()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> const void * llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getPointerIntoBucketsArray () const inline nodiscard
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
In conjunction with the previous method, this can be used to determine whether an insertion caused the DenseMap to reallocate.
Definition at line 367 of file DenseMap.h.
initEmpty()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty () inline protected
Definition at line 411 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::initWithExactBucketCount(), and llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear().
initWithExactBucketCount()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initWithExactBucketCount (unsigned NewNumBuckets) inline protected
Definition at line 382 of file DenseMap.h.
Referenced by llvm::DenseMap< const BlockT *, const BlockT * >::operator=(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::operator=(), and llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear().
insert() [1/3]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (const std::pair< KeyT, ValueT > & KV) inline
Definition at line 241 of file DenseMap.h.
Referenced by AddAliasScopeMetadata(), llvm::addDiffRuntimeChecks(), analyzeLoopUnrollCost(), analyzeModule(), buildClonedLoops(), buildFrameDebugInfo(), cacheDIVar(), checkConstHashCompatible(), TransferTracker::checkInstForNewValues(), CheckLargerCands(), llvm::cloneNoAliasScopes(), collectEHScopeMembers(), computeDomSubtreeCost(), constantMatches(), createAndInsertBasicBlocks(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalMappingFor(), llvm::DenseMap< const BlockT *, const BlockT * >::DenseMap(), doPromotion(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), expandToSwitch(), findArgumentCopyElisionCandidates(), findCandidateStructures(), findExtractedInputToOverallInputMapping(), llvm::InstCombinerImpl::foldOpIntoPhi(), forEachWorkListItem(), gatherIncomingValuesToPhi(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), genAlternativeDpCodeSequence(), generateGatherLanePattern(), genNeg(), genShXAddAddShift(), genSubAdd2SubSub(), llvm::rdf::Liveness::getAllReachingDefs(), getLocalId(), llvm::object::ELFObjectFileBase::getPltEntries(), slpvectorizer::BoUpSLP::getTreeCost(), handleAllocSite(), llvm::MIRParserImpl::initializeConstantPool(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::MIRParserImpl::initializeJumpTableInfo(), initRegisterMaskIds(), initSlots2BasicBlocks(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::insert_range(), llvm::insertDebugValuesForPHIs(), insertFoldCacheEntry(), llvm::InternalizePass::internalizeModule(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), loadObj(), mapValueToSlot(), matchScalarReduction(), memoryIsNotModifiedBetween(), moveFunctionData(), llvm::orc::BlockFreqQuery::operator()(), llvm::orc::SequenceBBQuery::operator()(), OptimizeNonTrivialIFuncs(), promoteArguments(), pushDepHeight(), llvm::TargetInstrInfo::reassociateOps(), llvm::TargetInstrInfo::reduceAccumulatorTree(), removeUndefDbgLocsFromEntryBlock(), slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::SSPLayoutAnalysis::requiresStackProtector(), llvm::DevirtSCCRepeatedPass::run(), llvm::SelectionDAGISel::runOnMachineFunction(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), shouldConvert(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifySwitchLookup(), sinkCommonCodeFromPredecessors(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::SmallDenseMap(), solveDIType(), sortLocalVars(), SRAGlobal(), tryToElideArgumentCopy(), and llvm::writeMemProfFrameArray().
insert() [2/3]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename InputIt> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (InputIt I, InputIt E) inline
insert - Range insertion of pairs.
Definition at line 288 of file DenseMap.h.
insert() [3/3]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (std::pair< KeyT, ValueT > && KV) inline
Definition at line 248 of file DenseMap.h.
insert_as()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename LookupKeyT> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert_as (std::pair< KeyT, ValueT > && KV, const LookupKeyT & Val) inline
Alternate version of insert() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 274 of file DenseMap.h.
Referenced by hasHazard().
insert_or_assign() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename V> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert_or_assign (const KeyT & Key, V && Val) inline
Definition at line 299 of file DenseMap.h.
Referenced by handleNewDebugValue().
insert_or_assign() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename V> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert_or_assign (KeyT && Key, V && Val) inline
Definition at line 307 of file DenseMap.h.
insert_range()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename Range> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert_range (Range && R) inline
Inserts range of 'std::pair<KeyT, ValueT>' values into the map.
Definition at line 294 of file DenseMap.h.
Referenced by llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::lookup().
isPointerIntoBucketsArray()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::isPointerIntoBucketsArray (const void * Ptr) const inline nodiscard
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
either to a key or value in the DenseMap).
Definition at line 360 of file DenseMap.h.
keys() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> auto llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::keys () inline nodiscard
Definition at line 92 of file DenseMap.h.
keys() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> auto llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::keys () const inline nodiscard
Definition at line 101 of file DenseMap.h.
lookup()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup (const_arg_type_t< KeyT > Val) const inline nodiscard
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
Definition at line 205 of file DenseMap.h.
Referenced by llvm::adaptNoAliasScopes(), llvm::addClonedBlockToLoopInfo(), llvm::addDiffRuntimeChecks(), analyzeLoopUnrollCost(), llvm::CombinerHelper::applyCombineExtendingLoads(), buildClonedLoops(), checkDependencies(), checkForAllInstructionsImpl(), collectBlockUseDef(), llvm::ComputeCrossModuleImport(), llvm::MachObjectWriter::computeSymbolTable(), llvm::VPlanTransforms::createInLoopReductionRecipes(), llvm::VPlanTransforms::cse(), doPromotion(), dropDeadSymbols(), llvm::dumpMaxRegPressure(), EvaluateExpression(), EvaluateInDifferentTypeImpl(), llvm::sampleprof::FunctionSamples::findInlinedFunctions(), findIrreducibleHeaders(), llvm::SSAUpdater::FindValueForBlock(), llvm::InstCombinerImpl::foldOpIntoPhi(), llvm::gatherImportedSummariesForModule(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::Attributor::getAttrsFromAssumes(), getConstantEvolvingPHIOperands(), getIRBlockFromSlot(), getNewDefiningAccessForClone(), getNewSource(), slpvectorizer::BoUpSLP::getSpillCost(), llvm::Triple::getVulkanVersion(), llvm::Attributor::internalizeFunctions(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), legacyCSE(), optimizeLatchExitInductionUser(), preparePlanForEpilogueVectorLoop(), llvm::orc::JITLinkRedirectableSymbolManager::redirect(), remapOperands(), llvm::objcopy::elf::GroupSection::replaceSectionReferences(), llvm::objcopy::elf::RelocationSection::replaceSectionReferences(), llvm::objcopy::elf::SymbolTableSection::replaceSectionReferences(), llvm::replaceSymbolicStrideSCEV(), llvm::OpenMPOptPass::run(), llvm::GCNRegPressurePrinter::runOnMachineFunction(), solveDIType(), sortLocalVars(), speculatePHINodeLoads(), llvm::stripDebugInfo(), llvm::VPRecipeBuilder::updateBlockMaskCache(), llvm::MemorySSAUpdater::updateForClonedLoop(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), and llvm::LoopInfoBase< MachineBasicBlock, MachineLoop >::verify().
lookup_or()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename U = std::remove_cv_t<ValueT>> ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup_or (const_arg_type_t< KeyT > Val, U && Default) const inline nodiscard
Definition at line 215 of file DenseMap.h.
Referenced by expandToSwitch().
moveFrom()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFrom (DerivedT & Other) inline protected
Definition at line 437 of file DenseMap.h.
operator[]() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (const KeyT & Key) inline
Definition at line 349 of file DenseMap.h.
operator[]() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (KeyT && Key) inline
Definition at line 353 of file DenseMap.h.
reserve()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve (size_type NumEntries) inline
Grow the densemap so that it can contain at least NumEntries items before resizing again.
Definition at line 114 of file DenseMap.h.
Referenced by llvm::SampleProfileInference< FT >::apply(), buildIndexMap(), llvm::CloneAndPruneIntoFromInst(), findArgumentCopyElisionCandidates(), findBestInsertionSet(), llvm::cfg::LegalizeUpdates(), llvm::xray::mergeProfilesByStack(), llvm::SSAUpdaterBulk::RewriteAllUses(), and llvm::writeMemProfFrameArray().
shrink_and_clear()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::shrink_and_clear () inline
Definition at line 157 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::clear().
size()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size () const inline nodiscard
Definition at line 110 of file DenseMap.h.
Referenced by slpvectorizer::BoUpSLP::analyzeRtStrideCandidate(), checkNumberingAndReplaceCommutative(), llvm::CloneAndPruneIntoFromInst(), llvm::IRSimilarity::IRSimilarityCandidate::compareAssignmentMapping(), llvm::ComputeCrossModuleImport(), llvm::TemporalProfTraceTy::createBPFunctionNodes(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalMappingFor(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), dumpImportListForModule(), llvm::dwarf_linker::classic::DwarfStreamer::emitDebugNames(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::emitDebugNames(), llvm::DWARFYAML::emitDebugNames(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::ModuleSummaryIndex::exportToDot(), findArgParts(), findIrreducibleHeaders(), foldSelectToPhiImpl(), llvm::CSKYAsmBackend::getFixupKindInfo(), llvm::insertDebugValuesForPHIs(), isBigEndian(), llvm::isEqual(), IsEquivalentPHI(), llvm::TargetLoweringBase::isSuitableForBitTests(), llvm::cfg::LegalizeUpdates(), llvm::orc::Platform::lookupInitSymbols(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerBuildVectorViaDominantValues(), llvm::ARMTargetLowering::lowerInterleavedLoad(), LowerShift(), lowerStatepointMetaArgs(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved(), llvm::BasicBlockMatchingAndInference::runOnMachineFunction(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifyNeonTbl(), simplifySwitchLookup(), SRAGlobal(), tryToFindDuplicates(), llvm::UnrollLoop(), llvm::BlockFrequencyInfoImpl< BT >::verifyMatch(), writeFunctionHeapProfileRecords(), llvm::writeMemProfFrameArray(), and llvm::writeMemProfRadixTreeBased().
swap()
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::swap (DerivedT & RHS) inline
Definition at line 371 of file DenseMap.h.
Referenced by checkNumberingAndReplaceCommutative(), llvm::DenseMap< const BlockT *, const BlockT * >::DenseMap(), llvm::DenseMap< const BlockT *, const BlockT * >::operator=(), llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::operator=(), and llvm::SmallDenseMap< LocPair, CacheEntry, 8 >::SmallDenseMap().
try_emplace() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace (const KeyT & Key, Ts &&... Args) inline
Definition at line 264 of file DenseMap.h.
try_emplace() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace (KeyT && Key, Ts &&... Args) inline
Definition at line 256 of file DenseMap.h.
Referenced by addEdge(), allPathsGoThroughCold(), slpvectorizer::BoUpSLP::buildExternalUses(), llvm::calculateCXXStateForAsynchEH(), calculatePrevailingSummary(), slpvectorizer::BoUpSLP::calculateTreeCostAndTrimNonProfitable(), llvm::mca::ResourceManager::checkAvailability(), collectSRATypes(), llvm::memprof::computeUndriftMap(), llvm::TemporalProfTraceTy::createBPFunctionNodes(), CreateGCRelocates(), llvm::sandboxir::Region::createRegionsFromMD(), llvm::MCAssembler::dump(), eliminateDeadSwitchCases(), llvm::LoopVectorizationPlanner::emitInvalidCostRemarks(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::emplace_or_assign(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::emplace_or_assign(), llvm::ModuleSummaryIndex::exportToDot(), findArgParts(), findBasePointer(), findCandidateStructures(), llvm::DILocation::getMergedLocation(), getOrCreateRefVariable(), getRules(), slpvectorizer::BoUpSLP::getSpillCost(), HasAddressTaken(), hasChangeableCC(), hasPHICycle(), llvm::cas::ObjectStore::importObject(), inferAlignment(), INITIALIZE_PASS(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::insert_or_assign(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::insert_or_assign(), IsValueFullyAvailableInBlock(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerShift(), llvm::LegalizerHelper::lowerShuffleVector(), OptimizeNonTrivialIFuncs(), slpvectorizer::BoUpSLP::processBuildVector(), processHandle(), removeRedundantDbgInstrsUsingForwardScan(), removeRedundantDbgLocsUsingBackwardScan(), removeRedundantDbgLocsUsingForwardScan(), removeRedundantExpandSCEVRecipes(), slpvectorizer::BoUpSLP::reorderTopToBottom(), simplifyNeonTbl(), simplifySwitchLookup(), sinkThroughTriviallyReplaceablePHI(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), tryToFindDuplicates(), llvm::orc::DLLImportDefinitionGenerator::tryToGenerate(), updateIDTMetaData(), slpvectorizer::BoUpSLP::vectorizeTree(), llvm::GenericConvergenceVerifier< ContextT >::verify(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
values() [1/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> auto llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::values () inline nodiscard
Definition at line 97 of file DenseMap.h.
Referenced by llvm::VPlanTransforms::replaceSymbolicStrides().
values() [2/2]
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT> auto llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::values () const inline nodiscard
Definition at line 105 of file DenseMap.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseMap.h