LLVM: llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)> Class Template Reference
llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)> Class Template Reference
Specialization for functions of the form 'void (std::unique_ptr<ErrT>)'.
#include "llvm/Support/Error.h"
Static Public Member Functions
static bool appliesTo (const ErrorInfoBase &E)
template<typename HandlerT>
static Error apply (HandlerT &&H, std::unique_ptr< ErrorInfoBase > E)
Detailed Description
template<typename ErrT>
class llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>
Specialization for functions of the form 'void (std::unique_ptr<ErrT>)'.
Definition at line 899 of file Error.h.
Member Function Documentation
appliesTo()
template<typename ErrT> bool llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::appliesTo (const ErrorInfoBase & E) inline static
Definition at line 901 of file Error.h.
References E().
Referenced by apply().
apply()
template<typename ErrT> template<typename HandlerT> Error llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply (HandlerT && H, std::unique_ptr< ErrorInfoBase > E) inline static
Definition at line 906 of file Error.h.
References appliesTo(), assert(), E(), H, and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/Support/Error.h