LLVM: llvm::remarks::BitstreamMetaParserHelper Class Reference
llvm::remarks::BitstreamMetaParserHelper Class Reference
Helper to parse a META_BLOCK for a bitstream remark container.
#include "Remarks/BitstreamRemarkParser.h"
Classes
struct ContainerInfo
Public Member Functions
BitstreamMetaParserHelper (BitstreamCursor &Stream)
Public Member Functions inherited from llvm::remarks::BitstreamBlockParserHelper< BitstreamMetaParserHelper >
Error parseBlock ()
Enter, parse, and leave this bitstream block.
Public Member Functions inherited from llvm::remarks::BitstreamBlockParserHelperBase
BitstreamBlockParserHelperBase (BitstreamCursor &Stream, unsigned BlockID, StringRef BlockName)
template<typename... Ts>
Error error (char const *Fmt, const Ts &...Vals)
Error expectBlock ()
Public Attributes
std::optional< ContainerInfo > Container
The parsed content: depending on the container type, some fields might be empty.
std::optional< uint64_t > RemarkVersion
std::optional< StringRef > ExternalFilePath
std::optional< StringRef > StrTabBuf
Protected Member Functions
Error parseRecord (unsigned Code)
Protected Member Functions inherited from llvm::remarks::BitstreamBlockParserHelper< BitstreamMetaParserHelper >
BitstreamBlockParserHelperBase (BitstreamCursor &Stream, unsigned BlockID, StringRef BlockName)
BitstreamMetaParserHelper & derived ()
Error parseRecord (unsigned Code)=delete
Parse a record and fill in the fields in the parser.
Error parseSubBlock (unsigned Code)
Parse a subblock and fill in the fields in the parser.
Protected Member Functions inherited from llvm::remarks::BitstreamBlockParserHelperBase
Error enterBlock ()
Error unknownRecord (unsigned AbbrevID)
Error unexpectedRecord (StringRef RecordName)
Error malformedRecord (StringRef RecordName)
Error unexpectedBlock (unsigned Code)
Friends
class BitstreamBlockParserHelper< BitstreamMetaParserHelper >
Additional Inherited Members
Protected Attributes inherited from llvm::remarks::BitstreamBlockParserHelperBase
BitstreamCursor & Stream
StringRef BlockName
unsigned BlockID
Detailed Description
Helper to parse a META_BLOCK for a bitstream remark container.
Definition at line 113 of file BitstreamRemarkParser.h.
Constructor & Destructor Documentation
BitstreamMetaParserHelper()
llvm::remarks::BitstreamMetaParserHelper::BitstreamMetaParserHelper (BitstreamCursor & Stream) inline
Definition at line 130 of file BitstreamRemarkParser.h.
References llvm::remarks::META_BLOCK_ID, llvm::remarks::MetaBlockName(), and llvm::remarks::BitstreamBlockParserHelperBase::Stream.
Member Function Documentation
parseRecord()
Error BitstreamMetaParserHelper::parseRecord (unsigned Code) protected
Definition at line 83 of file BitstreamRemarkParser.cpp.
References Container, llvm::remarks::CurrentContainerVersion, llvm::remarks::CurrentRemarkVersion, ExternalFilePath, llvm::remarks::BitstreamBlockParserHelperBase::malformedRecord(), llvm::remarks::MetaContainerInfoName(), llvm::remarks::MetaExternalFileName(), llvm::remarks::MetaRemarkVersionName(), llvm::remarks::MetaStrTabName(), llvm::remarks::RECORD_META_CONTAINER_INFO, llvm::remarks::RECORD_META_EXTERNAL_FILE, llvm::remarks::RECORD_META_REMARK_VERSION, llvm::remarks::RECORD_META_STRTAB, RemarkVersion, llvm::remarks::BitstreamBlockParserHelperBase::Stream, StrTabBuf, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::remarks::BitstreamBlockParserHelperBase::unknownRecord().
Friends And Related Symbol Documentation
BitstreamBlockParserHelper< BitstreamMetaParserHelper >
friend class BitstreamBlockParserHelper< BitstreamMetaParserHelper > friend
Definition at line 83 of file BitstreamRemarkParser.h.
References llvm::remarks::BitstreamBlockParserHelper< Derived >::derived(), E(), llvm::BitstreamEntry::EndBlock, llvm::remarks::BitstreamBlockParserHelperBase::enterBlock(), llvm::BitstreamEntry::Error, error, llvm_unreachable, llvm::Next, llvm::remarks::BitstreamBlockParserHelper< Derived >::parseRecord(), llvm::remarks::BitstreamBlockParserHelper< Derived >::parseSubBlock(), llvm::BitstreamEntry::Record, llvm::remarks::BitstreamBlockParserHelperBase::Stream, llvm::BitstreamEntry::SubBlock, and llvm::Error::success().
Member Data Documentation
Container
std::optional<ContainerInfo> llvm::remarks::BitstreamMetaParserHelper::Container
The parsed content: depending on the container type, some fields might be empty.
Definition at line 125 of file BitstreamRemarkParser.h.
Referenced by parseRecord().
ExternalFilePath
std::optional<StringRef> llvm::remarks::BitstreamMetaParserHelper::ExternalFilePath
Definition at line 127 of file BitstreamRemarkParser.h.
Referenced by parseRecord().
RemarkVersion
std::optional<uint64_t> llvm::remarks::BitstreamMetaParserHelper::RemarkVersion
Definition at line 126 of file BitstreamRemarkParser.h.
Referenced by parseRecord().
StrTabBuf
std::optional<StringRef> llvm::remarks::BitstreamMetaParserHelper::StrTabBuf
Definition at line 128 of file BitstreamRemarkParser.h.
Referenced by parseRecord().
The documentation for this class was generated from the following files:
lib/Remarks/BitstreamRemarkParser.h
lib/Remarks/BitstreamRemarkParser.cpp