LLVM: llvm::ctx_profile::ContextNode Class Reference
llvm::ctx_profile::ContextNode Class Reference final
#include "llvm/ProfileData/CtxInstrContextNode.h"
Public Member Functions
ContextNode (GUID Guid, uint32_t NumCounters, uint32_t NumCallsites, ContextNode *Next=nullptr)
uint64_t * counters ()
uint32_t counters_size () const
uint32_t callsites_size () const
const uint64_t * counters () const
ContextNode ** subContexts ()
ContextNode *const * subContexts () const
GUID guid () const
ContextNode * next () const
size_t size () const
uint64_t entrycount () const
Static Public Member Functions
static size_t getAllocSize (uint32_t NumCounters, uint32_t NumCallsites)
Detailed Description
Definition at line 68 of file CtxInstrContextNode.h.
Constructor & Destructor Documentation
ContextNode()
llvm::ctx_profile::ContextNode::ContextNode (GUID Guid, uint32_t NumCounters, uint32_t NumCallsites, ContextNode * Next = nullptr) inline
Definition at line 75 of file CtxInstrContextNode.h.
References ContextNode().
Referenced by ContextNode(), counters(), counters(), getAllocSize(), next(), subContexts(), and subContexts().
Member Function Documentation
callsites_size()
uint32_t llvm::ctx_profile::ContextNode::callsites_size () const inline
Definition at line 93 of file CtxInstrContextNode.h.
counters() [1/2]
uint64_t * llvm::ctx_profile::ContextNode::counters () inline
Definition at line 87 of file CtxInstrContextNode.h.
References ContextNode().
Referenced by counters(), entrycount(), subContexts(), and llvm::PGOCtxProfileWriter::writeContextual().
counters() [2/2]
const uint64_t * llvm::ctx_profile::ContextNode::counters () const inline
Definition at line 95 of file CtxInstrContextNode.h.
References ContextNode(), and counters().
counters_size()
uint32_t llvm::ctx_profile::ContextNode::counters_size () const inline
Definition at line 92 of file CtxInstrContextNode.h.
Referenced by llvm::PGOCtxProfileWriter::writeContextual().
entrycount()
uint64_t llvm::ctx_profile::ContextNode::entrycount () const inline
Definition at line 113 of file CtxInstrContextNode.h.
References counters().
Referenced by llvm::PGOCtxProfileWriter::writeContextual().
getAllocSize()
size_t llvm::ctx_profile::ContextNode::getAllocSize (uint32_t NumCounters, uint32_t NumCallsites) inline static
Definition at line 80 of file CtxInstrContextNode.h.
References ContextNode().
Referenced by size().
guid()
GUID llvm::ctx_profile::ContextNode::guid () const inline
Definition at line 108 of file CtxInstrContextNode.h.
Referenced by llvm::PGOCtxProfileWriter::writeContextual().
next()
ContextNode * llvm::ctx_profile::ContextNode::next () const inline
Definition at line 109 of file CtxInstrContextNode.h.
References ContextNode().
size()
size_t llvm::ctx_profile::ContextNode::size () const inline
Definition at line 111 of file CtxInstrContextNode.h.
References getAllocSize().
subContexts() [1/2]
ContextNode ** llvm::ctx_profile::ContextNode::subContexts () inline
Definition at line 100 of file CtxInstrContextNode.h.
References ContextNode(), and counters().
Referenced by subContexts().
subContexts() [2/2]
ContextNode *const * llvm::ctx_profile::ContextNode::subContexts () const inline
Definition at line 104 of file CtxInstrContextNode.h.
References ContextNode(), and subContexts().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/CtxInstrContextNode.h