LLVM: llvm::vfs::ProxyFileSystem Class Reference
llvm::vfs::ProxyFileSystem Class Reference
By default, this delegates all calls to the underlying file system.
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
ProxyFileSystem (IntrusiveRefCntPtr< FileSystem > FS)
llvm::ErrorOr< Status > status (const Twine &Path) override
bool exists (const Twine &Path) override
llvm::ErrorOr< std::unique_ptr< File > > openFileForRead (const Twine &Path) override
directory_iterator dir_begin (const Twine &Dir, std::error_code &EC) override
llvm::ErrorOr< std::string > getCurrentWorkingDirectory () const override
std::error_code setCurrentWorkingDirectory (const Twine &Path) override
std::error_code getRealPath (const Twine &Path, SmallVectorImpl< char > &Output) override
std::error_code isLocal (const Twine &Path, bool &Result) override
Public Member Functions inherited from llvm::RTTIExtends< ProxyFileSystem, FileSystem >
const void * dynamicClassID () const override
bool isA () const
Check whether this instance is a subclass of QueryT.
Static Public Attributes
static const char ID = 0
Protected Member Functions
FileSystem & getUnderlyingFS () const
void visitChildFileSystems (VisitCallbackTy Callback) override
Additional Inherited Members
Static Public Member Functions inherited from llvm::RTTIExtends< ProxyFileSystem, FileSystem >
static const void * classID ()
static bool classof (const T *R)
Detailed Description
By default, this delegates all calls to the underlying file system.
This is useful when derived file systems want to override some calls and still proxy other calls.
Definition at line 456 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
ProxyFileSystem()
llvm::vfs::ProxyFileSystem::ProxyFileSystem (IntrusiveRefCntPtr< FileSystem > FS) inline explicit
Definition at line 460 of file VirtualFileSystem.h.
References llvm::move().
Member Function Documentation
dir_begin()
directory_iterator llvm::vfs::ProxyFileSystem::dir_begin (const Twine & Dir, std::error_code & EC) inline override
Definition at line 471 of file VirtualFileSystem.h.
Referenced by llvm::vfs::TracingFileSystem::dir_begin().
exists()
bool llvm::vfs::ProxyFileSystem::exists (const Twine & Path) inline override
Definition at line 466 of file VirtualFileSystem.h.
Referenced by llvm::vfs::TracingFileSystem::exists().
getCurrentWorkingDirectory()
llvm::ErrorOr< std::string > llvm::vfs::ProxyFileSystem::getCurrentWorkingDirectory () const inline override
Definition at line 474 of file VirtualFileSystem.h.
getRealPath()
std::error_code llvm::vfs::ProxyFileSystem::getRealPath (const Twine & Path, SmallVectorImpl< char > & Output) inline override
Definition at line 480 of file VirtualFileSystem.h.
Referenced by llvm::vfs::TracingFileSystem::getRealPath().
getUnderlyingFS()
FileSystem & llvm::vfs::ProxyFileSystem::getUnderlyingFS () const inline protected
Definition at line 489 of file VirtualFileSystem.h.
isLocal()
std::error_code llvm::vfs::ProxyFileSystem::isLocal (const Twine & Path, bool & Result) inline override
Definition at line 484 of file VirtualFileSystem.h.
Referenced by llvm::vfs::TracingFileSystem::isLocal().
openFileForRead()
llvm::ErrorOr< std::unique_ptr< File > > llvm::vfs::ProxyFileSystem::openFileForRead (const Twine & Path) inline override
Definition at line 468 of file VirtualFileSystem.h.
Referenced by llvm::vfs::TracingFileSystem::openFileForRead().
setCurrentWorkingDirectory()
std::error_code llvm::vfs::ProxyFileSystem::setCurrentWorkingDirectory (const Twine & Path) inline override
Definition at line 477 of file VirtualFileSystem.h.
status()
llvm::ErrorOr< Status > llvm::vfs::ProxyFileSystem::status (const Twine & Path) inline override
Definition at line 463 of file VirtualFileSystem.h.
Referenced by llvm::vfs::TracingFileSystem::status().
visitChildFileSystems()
void llvm::vfs::ProxyFileSystem::visitChildFileSystems (VisitCallbackTy Callback) inline override protected
Definition at line 490 of file VirtualFileSystem.h.
Member Data Documentation
ID
const char ProxyFileSystem::ID = 0 static
Definition at line 459 of file VirtualFileSystem.h.
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualFileSystem.h
lib/Support/VirtualFileSystem.cpp