LLVM: llvm::HexagonInstPrinter Class Reference
llvm::HexagonInstPrinter Class Reference
Prints bundles as a newline separated list of individual instructions Duplexes are separated by a vertical tab \v character A trailing line includes bundle properties such as endloop0/1.
#include "Target/Hexagon/MCTargetDesc/HexagonInstPrinter.h"
Public Member Functions
HexagonInstPrinter (MCAsmInfo const &MAI, MCInstrInfo const &MII, MCRegisterInfo const &MRI)
void printInst (MCInst const *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &O, MCRegister Reg) override
Print the assembler register name.
std::pair< const char *, uint64_t > getMnemonic (const MCInst &MI) const override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printOperand (MCInst const *MI, unsigned OpNo, raw_ostream &O) const
void printBrtarget (MCInst const *MI, unsigned OpNo, raw_ostream &O) const
MCAsmInfo const & getMAI () const
MCInstrInfo const & getMII () const
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
bool getUseColor () const
void setUseColor (bool Value)
WithMarkup markup (raw_ostream &OS, Markup M)
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static char const * getRegisterName (MCRegister Reg)
Additional Inherited Members
Public Types inherited from llvm::MCInstPrinter
enum class Markup { Immediate , Register , Target , Memory }
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool UseColor = false
True if we are printing colored assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
SmallVector< raw_ostream::Colors, 4 > ColorStack {raw_ostream::Colors::RESET}
Detailed Description
Prints bundles as a newline separated list of individual instructions Duplexes are separated by a vertical tab \v character A trailing line includes bundle properties such as endloop0/1.
r0 = add(r1, r2) r0 = #0 \v jump 0x0 :endloop0 :endloop1
Definition at line 25 of file HexagonInstPrinter.h.
Constructor & Destructor Documentation
HexagonInstPrinter()
llvm::HexagonInstPrinter::HexagonInstPrinter (MCAsmInfo const & MAI, MCInstrInfo const & MII, MCRegisterInfo const & MRI) inline explicit
Definition at line 27 of file HexagonInstPrinter.h.
References llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MCInstPrinter(), and llvm::MCInstPrinter::MRI.
Member Function Documentation
getMAI()
MCAsmInfo const & llvm::HexagonInstPrinter::getMAI () const inline
Definition at line 43 of file HexagonInstPrinter.h.
References llvm::MCInstPrinter::MAI.
getMII()
MCInstrInfo const & llvm::HexagonInstPrinter::getMII () const inline
Definition at line 44 of file HexagonInstPrinter.h.
getMnemonic()
std::pair< const char *, uint64_t > llvm::HexagonInstPrinter::getMnemonic (const MCInst & MI) const override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
References MI.
getRegisterName()
char const * llvm::HexagonInstPrinter::getRegisterName (MCRegister Reg) static
References Reg.
Referenced by llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::printOperand(), printOperand(), and printRegName().
printBrtarget()
void HexagonInstPrinter::printBrtarget (MCInst const * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 69 of file HexagonInstPrinter.cpp.
References assert(), llvm::format(), llvm::MCOperand::getExpr(), llvm::HexagonMCInstrInfo::getExtendableOp(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::MCOperand::isExpr(), llvm::MCInstPrinter::MAI, and MI.
printInst()
void HexagonInstPrinter::printInst (MCInst const * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 33 of file HexagonInstPrinter.cpp.
References llvm::HexagonII::INST_PARSE_MASK, llvm::HexagonII::INST_PARSE_PACKET_END, llvm::HexagonMCInstrInfo::isDuplex(), llvm::HexagonMCInstrInfo::isImmext(), MI, and printInstruction().
printInstruction()
void llvm::HexagonInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
References MI.
Referenced by printInst().
printOperand()
void HexagonInstPrinter::printOperand (MCInst const * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 50 of file HexagonInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getExpr(), llvm::HexagonMCInstrInfo::getExtendableOp(), llvm::MCOperand::getReg(), getRegisterName(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::MCOperand::isExpr(), llvm::MCOperand::isReg(), llvm_unreachable, llvm::MCInstPrinter::MAI, and MI.
printRegName()
void HexagonInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 29 of file HexagonInstPrinter.cpp.
References getRegisterName().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonInstPrinter.h
lib/Target/Hexagon/MCTargetDesc/HexagonInstPrinter.cpp