LLVM: llvm::CalleeSavedInfo Class Reference
llvm::CalleeSavedInfo Class Reference
The CalleeSavedInfo class tracks the information need to locate where a callee saved register is in the current frame.
#include "llvm/CodeGen/MachineFrameInfo.h"
Public Member Functions
CalleeSavedInfo (MCRegister R, int FI=0)
MCRegister getReg () const
int getFrameIdx () const
MCRegister getDstReg () const
void setReg (MCRegister R)
void setFrameIdx (int FI)
void setDstReg (MCRegister SpillReg)
bool isRestored () const
void setRestored (bool R)
bool isSpilledToReg () const
Detailed Description
The CalleeSavedInfo class tracks the information need to locate where a callee saved register is in the current frame.
Callee saved reg can also be saved to a different register rather than on the stack by setting DstReg instead of FrameIdx.
Definition at line 35 of file MachineFrameInfo.h.
Constructor & Destructor Documentation
CalleeSavedInfo()
llvm::CalleeSavedInfo::CalleeSavedInfo (MCRegister R, int FI = 0) inline explicit
Definition at line 59 of file MachineFrameInfo.h.
References FrameIdx.
Member Function Documentation
getDstReg()
MCRegister llvm::CalleeSavedInfo::getDstReg () const inline
Definition at line 64 of file MachineFrameInfo.h.
References DstReg.
Referenced by llvm::TargetFrameLowering::restoreCalleeSavedRegister(), and llvm::TargetFrameLowering::spillCalleeSavedRegister().
getFrameIdx()
int llvm::CalleeSavedInfo::getFrameIdx () const inline
Definition at line 63 of file MachineFrameInfo.h.
References FrameIdx.
Referenced by llvm::XCoreFrameLowering::emitPrologue(), llvm::TargetFrameLowering::restoreCalleeSavedRegister(), and llvm::TargetFrameLowering::spillCalleeSavedRegister().
getReg()
MCRegister llvm::CalleeSavedInfo::getReg () const inline
Definition at line 62 of file MachineFrameInfo.h.
Referenced by assignSlotsUsingVGPRBlocks(), llvm::XCoreFrameLowering::emitPrologue(), emitSCSEpilogue(), emitSCSPrologue(), llvm::TargetFrameLowering::restoreCalleeSavedRegister(), and llvm::TargetFrameLowering::spillCalleeSavedRegister().
isRestored()
bool llvm::CalleeSavedInfo::isRestored () const inline
Definition at line 74 of file MachineFrameInfo.h.
isSpilledToReg()
bool llvm::CalleeSavedInfo::isSpilledToReg () const inline
Definition at line 76 of file MachineFrameInfo.h.
Referenced by llvm::TargetFrameLowering::restoreCalleeSavedRegister(), and llvm::TargetFrameLowering::spillCalleeSavedRegister().
setDstReg()
void llvm::CalleeSavedInfo::setDstReg (MCRegister SpillReg) inline
Definition at line 70 of file MachineFrameInfo.h.
References DstReg, and llvm::MCRegister::id().
setFrameIdx()
void llvm::CalleeSavedInfo::setFrameIdx (int FI) inline
Definition at line 66 of file MachineFrameInfo.h.
References FrameIdx.
setReg()
void llvm::CalleeSavedInfo::setReg (MCRegister R) inline
Definition at line 65 of file MachineFrameInfo.h.
setRestored()
void llvm::CalleeSavedInfo::setRestored (bool R) inline
Definition at line 75 of file MachineFrameInfo.h.
Referenced by llvm::MIRParserImpl::parseCalleeSavedRegister().
Member Data Documentation
DstReg
unsigned llvm::CalleeSavedInfo::DstReg
Definition at line 39 of file MachineFrameInfo.h.
Referenced by getDstReg(), and setDstReg().
FrameIdx
int llvm::CalleeSavedInfo::FrameIdx
Definition at line 38 of file MachineFrameInfo.h.
Referenced by CalleeSavedInfo(), getFrameIdx(), and setFrameIdx().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineFrameInfo.h