LLVM: llvm::sandboxir::ReadyListContainer Class Reference
llvm::sandboxir::ReadyListContainer Class Reference
The list holding nodes that are ready to schedule. Used by the scheduler.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/Scheduler.h"
Public Member Functions
ReadyListContainer ()
void insert (DGNode *N)
DGNode * pop ()
bool empty () const
void clear ()
void remove (DGNode *N)
\Removes N if found in the ready list.
void dump (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
The list holding nodes that are ready to schedule. Used by the scheduler.
Definition at line 55 of file Scheduler.h.
Constructor & Destructor Documentation
ReadyListContainer()
llvm::sandboxir::ReadyListContainer::ReadyListContainer () inline
Definition at line 64 of file Scheduler.h.
Member Function Documentation
clear()
void llvm::sandboxir::ReadyListContainer::clear () inline
Definition at line 83 of file Scheduler.h.
dump() [1/2]
void llvm::sandboxir::ReadyListContainer::dump () const
Definition at line 63 of file Scheduler.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::ReadyListContainer::dump (raw_ostream & OS) const
Definition at line 55 of file Scheduler.cpp.
empty()
bool llvm::sandboxir::ReadyListContainer::empty () const inline
Definition at line 82 of file Scheduler.h.
insert()
void llvm::sandboxir::ReadyListContainer::insert (DGNode * N) inline
Definition at line 65 of file Scheduler.h.
References assert(), and N.
pop()
DGNode * llvm::sandboxir::ReadyListContainer::pop () inline
Definition at line 77 of file Scheduler.h.
remove()
void llvm::sandboxir::ReadyListContainer::remove (DGNode * N) inline
\Removes N if found in the ready list.
Definition at line 85 of file Scheduler.h.
References llvm::Keep, N, and llvm::SmallVectorImpl< T >::reserve().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/Scheduler.h
lib/Transforms/Vectorize/SandboxVectorizer/Scheduler.cpp