LLVM: llvm::ExpressionAST Class Reference
llvm::ExpressionAST Class Reference abstract
Base class representing the AST of a given expression.
#include "FileCheck/FileCheckImpl.h"
Public Member Functions
ExpressionAST (StringRef ExpressionStr)
virtual ~ExpressionAST ()=default
StringRef getExpressionStr () const
virtual Expected< APInt > eval () const =0
Evaluates and.
virtual Expected< ExpressionFormat > getImplicitFormat (const SourceMgr &SM) const
Detailed Description
Base class representing the AST of a given expression.
Definition at line 132 of file FileCheckImpl.h.
Constructor & Destructor Documentation
ExpressionAST()
llvm::ExpressionAST::ExpressionAST (StringRef ExpressionStr) inline
Definition at line 137 of file FileCheckImpl.h.
Referenced by llvm::BinaryOperation::BinaryOperation(), llvm::ExpressionLiteral::ExpressionLiteral(), and llvm::NumericVariableUse::NumericVariableUse().
~ExpressionAST()
virtual llvm::ExpressionAST::~ExpressionAST () virtual default
Member Function Documentation
eval()
virtual Expected< APInt > llvm::ExpressionAST::eval () const pure virtual
Evaluates and.
Returns
the value of the expression represented by this AST or an error if evaluation fails.
Implemented in llvm::BinaryOperation, llvm::ExpressionLiteral, and llvm::NumericVariableUse.
Referenced by llvm::FileCheckPatternContext::defineCmdlineVariables().
getExpressionStr()
StringRef llvm::ExpressionAST::getExpressionStr () const inline
Definition at line 141 of file FileCheckImpl.h.
Referenced by llvm::NumericVariableUse::eval(), and llvm::BinaryOperation::getImplicitFormat().
getImplicitFormat()
virtual Expected< ExpressionFormat > llvm::ExpressionAST::getImplicitFormat (const SourceMgr & SM) const inline virtual
Returns
either the implicit format of this AST, a diagnostic against SM if implicit formats of the AST's components conflict, or NoFormat if the AST has no implicit format (e.g. AST is made up of a single literal).
Reimplemented in llvm::BinaryOperation, and llvm::NumericVariableUse.
Definition at line 152 of file FileCheckImpl.h.
References SM().
The documentation for this class was generated from the following file:
lib/FileCheck/FileCheckImpl.h