LLVM: llvm::MachO::SymbolConverter Class Reference
llvm::MachO::SymbolConverter Class Reference
Specialized RecordVisitor for collecting exported symbols and undefined symbols if RecordSlice being visited represents a flat-namespaced library.
#include "llvm/TextAPI/RecordVisitor.h"
Public Member Functions
SymbolConverter (SymbolSet *Symbols, const Target &T, const bool RecordUndefs=false)
void visitGlobal (const GlobalRecord &) override
void visitObjCInterface (const ObjCInterfaceRecord &) override
void visitObjCCategory (const ObjCCategoryRecord &) override
Public Member Functions inherited from llvm::MachO::RecordVisitor
virtual ~RecordVisitor ()
Detailed Description
Specialized RecordVisitor for collecting exported symbols and undefined symbols if RecordSlice being visited represents a flat-namespaced library.
Definition at line 36 of file RecordVisitor.h.
Constructor & Destructor Documentation
SymbolConverter()
llvm::MachO::SymbolConverter::SymbolConverter (SymbolSet * Symbols, const Target & T, const bool RecordUndefs = false) inline
Definition at line 38 of file RecordVisitor.h.
References T.
Member Function Documentation
visitGlobal()
void SymbolConverter::visitGlobal (const GlobalRecord & GR) override virtual
Implements llvm::MachO::RecordVisitor.
Definition at line 30 of file RecordVisitor.cpp.
References llvm::MachO::Record::getFlags(), llvm::MachO::Record::getName(), llvm::MachO::GlobalSymbol, llvm::MachO::None, llvm::MachO::parseSymbol(), and shouldSkipRecord().
visitObjCCategory()
void SymbolConverter::visitObjCCategory (const ObjCCategoryRecord & Cat) override virtual
Reimplemented from llvm::MachO::RecordVisitor.
Definition at line 90 of file RecordVisitor.cpp.
References llvm::MachO::ObjCContainerRecord::getObjCIVars(), and llvm::MachO::ObjCCategoryRecord::getSuperClassName().
visitObjCInterface()
void SymbolConverter::visitObjCInterface (const ObjCInterfaceRecord & ObjCR) override virtual
Reimplemented from llvm::MachO::RecordVisitor.
Definition at line 59 of file RecordVisitor.cpp.
References llvm::MachO::Class, llvm::MachO::EHType, llvm::MachO::Record::getFlags(), llvm::MachO::Record::getName(), llvm::MachO::ObjCInterfaceRecord::getObjCCategories(), llvm::MachO::ObjCContainerRecord::getObjCIVars(), llvm::MachO::GlobalSymbol, llvm::MachO::ObjCInterfaceRecord::hasExceptionAttribute(), llvm::MachO::ObjCInterfaceRecord::isCompleteInterface(), llvm::MachO::ObjCInterfaceRecord::isExportedSymbol(), llvm::MachO::MetaClass, llvm::MachO::ObjC2ClassNamePrefix, llvm::MachO::ObjC2EHTypePrefix, llvm::MachO::ObjC2MetaClassNamePrefix, llvm::MachO::ObjectiveCClass, llvm::MachO::ObjectiveCClassEHType, and shouldSkipRecord().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/RecordVisitor.h
lib/TextAPI/RecordVisitor.cpp