LLVM: llvm::ARCFrameLowering Class Reference
llvm::ARCFrameLowering Class Reference
#include "Target/ARC/ARCFrameLowering.h"
Public Member Functions
ARCFrameLowering (const ARCSubtarget &st)
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
Insert Prologue into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
Insert Epilogue into the function.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
Add explicit callee save registers.
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
bool assignCalleeSavedSpillSlots (llvm::MachineFunction &, const llvm::TargetRegisterInfo *, std::vector< llvm::CalleeSavedInfo > &) const override
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
Align getStackAlign () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
virtual uint64_t getStackThreshold () const
getStackThreshold - Return the maximum stack size
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
Align getTransientStackAlign () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual bool isStackIdSafeForLocalArea (unsigned StackId) const
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool allocateScavengingFrameIndexesNearIncomingSP (const MachineFunction &MF) const
Control the placement of special register scavenging spill slots when allocating a stack frame.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void emitZeroCallUsedRegs (BitVector RegsToZero, MachineBasicBlock &MBB) const
emitZeroCallUsedRegs - Zeros out call used registers.
virtual void emitCalleeSavedFrameMovesFullCFA (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI) const
With basic block sections, emit callee saved frame moves for basic blocks that are in a different section.
virtual bool enableCFIFixup (const MachineFunction &MF) const
Returns true if we may need to fix the unwind information for the function.
virtual bool enableFullCFIFixup (const MachineFunction &MF) const
enableFullCFIFixup - Returns true if we may need to fix the unwind information such that it is accurate for every instruction in the function (e.g.
virtual void resetCFIToInitialState (MachineBasicBlock &MBB) const
Emit CFI instructions that recreate the state of the unwind information upon function entry.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual bool stackProbeFunctionModifiesSP () const
Does the stack probe function call return with a modified stack pointer?
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
void spillCalleeSavedRegister (MachineBasicBlock &SaveBlock, MachineBasicBlock::iterator MI, const CalleeSavedInfo &CS, const TargetInstrInfo *TII, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegister - Default implementation for spilling a single callee saved register.
void restoreCalleeSavedRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const CalleeSavedInfo &CS, const TargetInstrInfo *TII, const TargetRegisterInfo *TRI) const
bool hasFP (const MachineFunction &MF) const
hasFP - Return true if the specified function should have a dedicated frame pointer register.
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual StackOffset getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, Register &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual StackOffset getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual StackOffset getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI) const
getFrameIndexReferenceFromSP - This method returns the offset from the stack pointer to the slot of the specified index.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual Register getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
virtual DwarfFrameBase getDwarfFrameBase (const MachineFunction &MF) const
Return the frame base information to be encoded in the DWARF subprogram debug info.
virtual void spillFPBP (MachineFunction &MF) const
If frame pointer or base pointer is clobbered by an instruction, we should spill/restore it around that instruction.
virtual void emitRemarks (const MachineFunction &MF, MachineOptimizationRemarkEmitter *ORE) const
This method is called at the end of prolog/epilog code insertion, so targets can emit remarks based on the final frame layout.
Protected Member Functions
bool hasFPImpl (const MachineFunction &MF) const override
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 27 of file ARCFrameLowering.h.
Constructor & Destructor Documentation
ARCFrameLowering()
llvm::ARCFrameLowering::ARCFrameLowering (const ARCSubtarget & st) inline
Definition at line 29 of file ARCFrameLowering.h.
References llvm::TargetFrameLowering::StackGrowsDown, and llvm::TargetFrameLowering::TargetFrameLowering().
Member Function Documentation
assignCalleeSavedSpillSlots()
bool ARCFrameLowering::assignCalleeSavedSpillSlots (llvm::MachineFunction & MF, const llvm::TargetRegisterInfo * TRI, std::vector< llvm::CalleeSavedInfo > & CSI) const override virtual
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 344 of file ARCFrameLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedSpillStackObject(), llvm::dbgs(), determineLastCalleeSave(), llvm::MachineFunction::getFrameInfo(), getSavedReg(), llvm::MachineFrameInfo::hasCalls(), llvm::TargetFrameLowering::hasFP(), I, llvm::Last, LLVM_DEBUG, llvm::MachineFrameInfo::setObjectOffset(), TRI, and UseSaveRestoreFunclet.
determineCalleeSaves()
void ARCFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
Add explicit callee save registers.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 88 of file ARCFrameLowering.cpp.
References llvm::dbgs(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::MachineFunction::getName(), LLVM_DEBUG, and llvm::BitVector::set().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator ARCFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 466 of file ARCFrameLowering.cpp.
References assert(), llvm::dbgs(), emitRegUpdate(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getName(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), I, LLVM_DEBUG, MBB, and TII.
emitEpilogue()
void ARCFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Insert Epilogue into the function.
Insert epilog code into the function.
For ARC, this inserts a call to a function that restores callee saved registers onto the stack, when enough callee saved registers are required.
Implements llvm::TargetFrameLowering.
Definition at line 238 of file ARCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::dbgs(), llvm::dwarf_linker::DebugLoc, llvm::RegState::Define, determineLastCalleeSave(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getName(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasCalls(), llvm::TargetFrameLowering::hasFP(), llvm::RegState::Implicit, llvm::isInt(), llvm::isUInt(), llvm::Function::isVarArg(), llvm::RegState::Kill, llvm::Last, LLVM_DEBUG, load_funclet_name, MBB, MBBI, Opc, TII, and UseSaveRestoreFunclet.
emitPrologue()
void ARCFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Insert Prologue into the function.
Insert prolog code into the function.
For ARC, this inserts a call to a function that puts required callee saved registers onto the stack, when enough callee saved registers are required.
Implements llvm::TargetFrameLowering.
Definition at line 115 of file ARCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfaOffset(), llvm::MCCFIInstruction::createOffset(), llvm::dbgs(), llvm::RegState::Define, determineLastCalleeSave(), llvm::MachineInstr::FrameSetup, generateStackAdjustment(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getName(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasCalls(), llvm::TargetFrameLowering::hasFP(), llvm::RegState::Implicit, llvm::isInt(), llvm::isUInt(), llvm::Function::isVarArg(), llvm::RegState::Kill, llvm::Last, LLVM_DEBUG, MBB, MBBI, MRI, Opc, llvm::MachineInstrBuilder::setMIFlags(), llvm::MachineFrameInfo::setStackSize(), store_funclet_name, TII, and UseSaveRestoreFunclet.
hasFPImpl()
bool ARCFrameLowering::hasFPImpl (const MachineFunction & MF) const override protected virtual
Implements llvm::TargetFrameLowering.
Definition at line 490 of file ARCFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
processFunctionBeforeFrameFinalized()
void ARCFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 432 of file ARCFrameLowering.cpp.
References llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::dbgs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getName(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasStackObjects(), and LLVM_DEBUG.
restoreCalleeSavedRegisters()
bool ARCFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 417 of file ARCFrameLowering.cpp.
References llvm::dbgs(), determineLastCalleeSave(), llvm::Last, LLVM_DEBUG, MBB, MI, TRI, and UseSaveRestoreFunclet.
spillCalleeSavedRegisters()
bool ARCFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 400 of file ARCFrameLowering.cpp.
References llvm::dbgs(), determineLastCalleeSave(), llvm::Last, LLVM_DEBUG, MBB, MI, TRI, and UseSaveRestoreFunclet.
The documentation for this class was generated from the following files:
lib/Target/ARC/ARCFrameLowering.h
lib/Target/ARC/ARCFrameLowering.cpp