LLVM: llvm::orc::LibraryManager::FilteredView Class Reference
llvm::orc::LibraryManager::FilteredView Class Reference
A read-only view of libraries filtered by state and kind.
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h"
Classes
class FilterIterator
Public Types
using Map = StringMap<std::unique_ptr<LibraryInfo>>
using Iterator = Map::const_iterator
Public Member Functions
FilteredView (Iterator begin, Iterator end, LibState s, PathType k)
FilterIterator begin () const
FilterIterator end () const
Detailed Description
A read-only view of libraries filtered by state and kind.
Lets you loop over only the libraries in a map that match a given State and PathType.
Definition at line 161 of file LibraryResolver.h.
Member Typedef Documentation
Iterator
using llvm::orc::LibraryManager::FilteredView::Iterator = Map::const_iterator
Definition at line 164 of file LibraryResolver.h.
Map
using llvm::orc::LibraryManager::FilteredView::Map = StringMap<std::unique_ptr<LibraryInfo>>
Definition at line 163 of file LibraryResolver.h.
Constructor & Destructor Documentation
FilteredView()
llvm::orc::LibraryManager::FilteredView::FilteredView (Iterator begin, Iterator end, LibState s, PathType k) inline
Definition at line 195 of file LibraryResolver.h.
References begin(), and end().
Member Function Documentation
begin()
FilterIterator llvm::orc::LibraryManager::FilteredView::begin () const inline
Definition at line 198 of file LibraryResolver.h.
Referenced by FilteredView().
end()
FilterIterator llvm::orc::LibraryManager::FilteredView::end () const inline
Definition at line 202 of file LibraryResolver.h.
Referenced by FilteredView().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h