LLVM: llvm::FoldingSetBucketIterator< T > Class Template Reference
llvm::FoldingSetBucketIterator< T > Class Template Reference
#include "llvm/ADT/FoldingSet.h"
Public Member Functions
FoldingSetBucketIterator (void **Bucket)
FoldingSetBucketIterator (void **Bucket, bool)
T & operator* () const
T * operator-> () const
FoldingSetBucketIterator & operator++ ()
FoldingSetBucketIterator operator++ (int)
Public Member Functions inherited from llvm::FoldingSetBucketIteratorImpl
bool operator== (const FoldingSetBucketIteratorImpl &RHS) const
bool operator!= (const FoldingSetBucketIteratorImpl &RHS) const
Additional Inherited Members
Protected Member Functions inherited from llvm::FoldingSetBucketIteratorImpl
LLVM_ABI FoldingSetBucketIteratorImpl (void **Bucket)
FoldingSetBucketIteratorImpl (void **Bucket, bool)
void advance ()
Protected Attributes inherited from llvm::FoldingSetBucketIteratorImpl
void * Ptr
Detailed Description
template<class T>
class llvm::FoldingSetBucketIterator< T >
Definition at line 773 of file FoldingSet.h.
Constructor & Destructor Documentation
FoldingSetBucketIterator() [1/2]
template<class T> llvm::FoldingSetBucketIterator< T >::FoldingSetBucketIterator (void ** Bucket) inline explicit
Definition at line 775 of file FoldingSet.h.
References llvm::FoldingSetBucketIteratorImpl::FoldingSetBucketIteratorImpl().
Referenced by operator++(), and operator++().
FoldingSetBucketIterator() [2/2]
template<class T> llvm::FoldingSetBucketIterator< T >::FoldingSetBucketIterator (void ** Bucket, bool) inline
Definition at line 778 of file FoldingSet.h.
References llvm::FoldingSetBucketIteratorImpl::FoldingSetBucketIteratorImpl().
Member Function Documentation
operator*()
template<class T> T & llvm::FoldingSetBucketIterator< T >::operator* () const inline
Definition at line 781 of file FoldingSet.h.
References llvm::FoldingSetBucketIteratorImpl::Ptr, and T.
operator++() [1/2]
template<class T> FoldingSetBucketIterator & llvm::FoldingSetBucketIterator< T >::operator++ () inline
Definition at line 784 of file FoldingSet.h.
References llvm::FoldingSetBucketIteratorImpl::advance(), and FoldingSetBucketIterator().
operator++() [2/2]
template<class T> FoldingSetBucketIterator llvm::FoldingSetBucketIterator< T >::operator++ (int) inline
Definition at line 788 of file FoldingSet.h.
References FoldingSetBucketIterator().
operator->()
template<class T> T * llvm::FoldingSetBucketIterator< T >::operator-> () const inline
Definition at line 782 of file FoldingSet.h.
References llvm::FoldingSetBucketIteratorImpl::Ptr, and T.
The documentation for this class was generated from the following file:
include/llvm/ADT/FoldingSet.h