LLVM: llvm::objcopy::elf::Reader Class Reference
llvm::objcopy::elf::Reader Class Reference abstract
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~Reader ()
virtual Expected< std::unique_ptr< Object > > create (bool EnsureSymtab) const =0
Detailed Description
Definition at line 1040 of file ELFObject.h.
Constructor & Destructor Documentation
~Reader()
Reader::~Reader () virtual default
Member Function Documentation
create()
virtual Expected< std::unique_ptr< Object > > llvm::objcopy::elf::Reader::create (bool EnsureSymtab) const pure virtual
Implemented in llvm::objcopy::elf::BinaryReader, llvm::objcopy::elf::ELFReader, and llvm::objcopy::elf::IHexReader.
Referenced by llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), and llvm::objcopy::elf::executeObjcopyOnRawBinary().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp