LLVM: llvm::SSAUpdaterTraits< DebugSSAUpdater > Class Reference
llvm::SSAUpdaterTraits< DebugSSAUpdater > Class Reference
Classes
class PHI_iterator
Public Types
using BlkT = DbgSSABlock
using ValT = DbgValueDef
using PhiT = DbgSSAPhi
using BlkSucc_iterator = DbgSSABlockSuccIterator
Static Public Member Functions
static BlkSucc_iterator BlkSucc_begin (BlkT *BB)
static BlkSucc_iterator BlkSucc_end (BlkT *BB)
static PHI_iterator PHI_begin (PhiT *PHI)
static PHI_iterator PHI_end (PhiT *PHI)
static void FindPredecessorBlocks (DbgSSABlock *BB, SmallVectorImpl< DbgSSABlock * > *Preds)
FindPredecessorBlocks - Put the predecessors of BB into the Preds vector.
static DbgValueDef GetPoisonVal (DbgSSABlock *BB, DebugSSAUpdater *Updater)
GetPoisonVal - Get an undefined value of the same type as the value being handled.
static DbgSSAPhi * CreateEmptyPHI (DbgSSABlock *BB, unsigned NumPreds, DebugSSAUpdater *Updater)
CreateEmptyPHI - Create a new debug PHI entry for the specified block.
static void AddPHIOperand (DbgSSAPhi *PHI, DbgValueDef Val, DbgSSABlock *Pred)
AddPHIOperand - Add the specified value as an operand of the PHI for the specified predecessor block.
static DbgSSAPhi * ValueIsPHI (DbgValueDef Val, DebugSSAUpdater *Updater)
ValueIsPHI - Check if a value is a PHI.
static DbgSSAPhi * ValueIsNewPHI (DbgValueDef Val, DebugSSAUpdater *Updater)
ValueIsNewPHI - Like ValueIsPHI but also check if the PHI has no source operands, i.e., it was just added.
static DbgValueDef GetPHIValue (DbgSSAPhi *PHI)
GetPHIValue - For the specified PHI instruction, return the value that it defines.
Detailed Description
Definition at line 126 of file DebugSSAUpdater.cpp.
Member Typedef Documentation
BlkSucc_iterator
using llvm::SSAUpdaterTraits< DebugSSAUpdater >::BlkSucc_iterator = DbgSSABlockSuccIterator
Definition at line 131 of file DebugSSAUpdater.cpp.
BlkT
using llvm::SSAUpdaterTraits< DebugSSAUpdater >::BlkT = DbgSSABlock
Definition at line 128 of file DebugSSAUpdater.cpp.
PhiT
using llvm::SSAUpdaterTraits< DebugSSAUpdater >::PhiT = DbgSSAPhi
Definition at line 130 of file DebugSSAUpdater.cpp.
ValT
using llvm::SSAUpdaterTraits< DebugSSAUpdater >::ValT = DbgValueDef
Definition at line 129 of file DebugSSAUpdater.cpp.
Member Function Documentation
AddPHIOperand()
void llvm::SSAUpdaterTraits< DebugSSAUpdater >::AddPHIOperand (DbgSSAPhi * PHI, DbgValueDef Val, DbgSSABlock * Pred) inline static
AddPHIOperand - Add the specified value as an operand of the PHI for the specified predecessor block.
Definition at line 184 of file DebugSSAUpdater.cpp.
References PHI.
BlkSucc_begin()
BlkSucc_iterator llvm::SSAUpdaterTraits< DebugSSAUpdater >::BlkSucc_begin (BlkT * BB) inline static
Definition at line 133 of file DebugSSAUpdater.cpp.
References llvm::DbgSSABlock::succ_begin().
BlkSucc_end()
BlkSucc_iterator llvm::SSAUpdaterTraits< DebugSSAUpdater >::BlkSucc_end (BlkT * BB) inline static
Definition at line 134 of file DebugSSAUpdater.cpp.
References llvm::DbgSSABlock::succ_end().
CreateEmptyPHI()
DbgSSAPhi * llvm::SSAUpdaterTraits< DebugSSAUpdater >::CreateEmptyPHI (DbgSSABlock * BB, unsigned NumPreds, DebugSSAUpdater * Updater) inline static
CreateEmptyPHI - Create a new debug PHI entry for the specified block.
Definition at line 176 of file DebugSSAUpdater.cpp.
References llvm::DbgSSABlock::newPHI(), and PHI.
FindPredecessorBlocks()
void llvm::SSAUpdaterTraits< DebugSSAUpdater >::FindPredecessorBlocks (DbgSSABlock * BB, SmallVectorImpl< DbgSSABlock * > * Preds) inline static
FindPredecessorBlocks - Put the predecessors of BB into the Preds vector.
Definition at line 163 of file DebugSSAUpdater.cpp.
References llvm::DbgSSABlock::pred_begin(), llvm::DbgSSABlock::pred_end(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
GetPHIValue()
DbgValueDef llvm::SSAUpdaterTraits< DebugSSAUpdater >::GetPHIValue (DbgSSAPhi * PHI) inline static
GetPHIValue - For the specified PHI instruction, return the value that it defines.
Definition at line 205 of file DebugSSAUpdater.cpp.
References PHI.
GetPoisonVal()
DbgValueDef llvm::SSAUpdaterTraits< DebugSSAUpdater >::GetPoisonVal (DbgSSABlock * BB, DebugSSAUpdater * Updater) inline static
GetPoisonVal - Get an undefined value of the same type as the value being handled.
Definition at line 171 of file DebugSSAUpdater.cpp.
PHI_begin()
PHI_iterator llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_begin (PhiT * PHI) inline static
Definition at line 158 of file DebugSSAUpdater.cpp.
References PHI.
PHI_end()
PHI_iterator llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_end (PhiT * PHI) inline static
Definition at line 159 of file DebugSSAUpdater.cpp.
References PHI.
ValueIsNewPHI()
DbgSSAPhi * llvm::SSAUpdaterTraits< DebugSSAUpdater >::ValueIsNewPHI (DbgValueDef Val, DebugSSAUpdater * Updater) inline static
ValueIsNewPHI - Like ValueIsPHI but also check if the PHI has no source operands, i.e., it was just added.
Definition at line 196 of file DebugSSAUpdater.cpp.
References PHI, and ValueIsPHI().
ValueIsPHI()
DbgSSAPhi * llvm::SSAUpdaterTraits< DebugSSAUpdater >::ValueIsPHI (DbgValueDef Val, DebugSSAUpdater * Updater) inline static
ValueIsPHI - Check if a value is a PHI.
Definition at line 190 of file DebugSSAUpdater.cpp.
References llvm::DbgValueDef::Phi.
Referenced by ValueIsNewPHI().
The documentation for this class was generated from the following file:
lib/Transforms/Utils/DebugSSAUpdater.cpp