LLVM: llvm::sandboxir::PHIRemoveIncoming Class Reference
llvm::sandboxir::PHIRemoveIncoming Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
PHIRemoveIncoming (PHINode *PHI, unsigned RemovedIdx)
void revert (Tracker &Tracker) final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
virtual ~IRChangeBase ()=default
Detailed Description
Definition at line 154 of file Tracker.h.
Constructor & Destructor Documentation
PHIRemoveIncoming()
PHIRemoveIncoming::PHIRemoveIncoming (PHINode * PHI, unsigned RemovedIdx)
Definition at line 91 of file Tracker.cpp.
Member Function Documentation
accept()
void llvm::sandboxir::PHIRemoveIncoming::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 163 of file Tracker.h.
dump() [1/2]
void PHIRemoveIncoming::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 113 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::PHIRemoveIncoming::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 165 of file Tracker.h.
revert()
void PHIRemoveIncoming::revert (Tracker & Tracker) final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 97 of file Tracker.cpp.
References llvm::sandboxir::IRChangeBase::Tracker.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp