LLVM: llvm::LowerMatrixIntrinsicsPass Class Reference
llvm::LowerMatrixIntrinsicsPass Class Reference
#include "llvm/Transforms/Scalar/LowerMatrixIntrinsics.h"
Public Member Functions
LowerMatrixIntrinsicsPass (bool Minimal=false)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< LowerMatrixIntrinsicsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< LowerMatrixIntrinsicsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 19 of file LowerMatrixIntrinsics.h.
Constructor & Destructor Documentation
LowerMatrixIntrinsicsPass()
llvm::LowerMatrixIntrinsicsPass::LowerMatrixIntrinsicsPass (bool Minimal = false) inline
Definition at line 24 of file LowerMatrixIntrinsics.h.
Member Function Documentation
isRequired()
bool llvm::LowerMatrixIntrinsicsPass::isRequired () inline static
Definition at line 28 of file LowerMatrixIntrinsics.h.
printPipeline()
void LowerMatrixIntrinsicsPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 2900 of file LowerMatrixIntrinsics.cpp.
References printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses LowerMatrixIntrinsicsPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 2884 of file LowerMatrixIntrinsics.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::preserve().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LowerMatrixIntrinsics.h
lib/Transforms/Scalar/LowerMatrixIntrinsics.cpp