LLVM: llvm::yaml::IO Class Reference
llvm::yaml::IO Class Reference abstract
#include "llvm/Support/YAMLTraits.h"
Public Member Functions
IO (void *Ctxt=nullptr)
virtual ~IO ()
virtual bool outputting () const =0
virtual unsigned beginSequence ()=0
virtual bool preflightElement (unsigned, void *&)=0
virtual void postflightElement (void *)=0
virtual void endSequence ()=0
virtual bool canElideEmptySequence ()=0
virtual unsigned beginFlowSequence ()=0
virtual bool preflightFlowElement (unsigned, void *&)=0
virtual void postflightFlowElement (void *)=0
virtual void endFlowSequence ()=0
virtual bool mapTag (StringRef Tag, bool Default=false)=0
virtual void beginMapping ()=0
virtual void endMapping ()=0
virtual bool preflightKey (StringRef, bool, bool, bool &, void *&)=0
virtual void postflightKey (void *)=0
virtual std::vector< StringRef > keys ()=0
virtual void beginFlowMapping ()=0
virtual void endFlowMapping ()=0
virtual void beginEnumScalar ()=0
virtual bool matchEnumScalar (StringRef, bool)=0
virtual bool matchEnumFallback ()=0
virtual void endEnumScalar ()=0
virtual bool beginBitSetScalar (bool &)=0
virtual bool bitSetMatch (StringRef, bool)=0
virtual void endBitSetScalar ()=0
virtual void scalarString (StringRef &, QuotingType)=0
virtual void blockScalarString (StringRef &)=0
virtual void scalarTag (std::string &)=0
virtual NodeKind getNodeKind ()=0
virtual void setError (const Twine &)=0
virtual std::error_code error ()=0
virtual void setAllowUnknownKeys (bool Allow)
template<typename T>
void enumCase (T &Val, StringRef Str, const T ConstVal)
template<typename T>
void enumCase (T &Val, StringRef Str, const uint32_t ConstVal)
template<typename FBT, typename T>
void enumFallback (T &Val)
template<typename T>
void bitSetCase (T &Val, StringRef Str, const T ConstVal)
template<typename T>
void bitSetCase (T &Val, StringRef Str, const uint32_t ConstVal)
template<typename T>
void maskedBitSetCase (T &Val, StringRef Str, T ConstVal, T Mask)
template<typename T>
void maskedBitSetCase (T &Val, StringRef Str, uint32_t ConstVal, uint32_t Mask)
void * getContext () const
void setContext (void *)
template<typename T>
void mapRequired (StringRef Key, T &Val)
template<typename T, typename Context>
void mapRequired (StringRef Key, T &Val, Context &Ctx)
template<typename T>
void mapOptional (StringRef Key, T &Val)
template<typename T, typename DefaultT>
void mapOptional (StringRef Key, T &Val, const DefaultT &Default)
template<typename T, typename Context>
void mapOptionalWithContext (StringRef Key, T &Val, Context &Ctx)
template<typename T, typename Context>
void mapOptionalWithContext (StringRef Key, std::optional< T > &Val, Context &Ctx)
template<typename T, typename Context, typename DefaultT>
void mapOptionalWithContext (StringRef Key, T &Val, const DefaultT &Default, Context &Ctx)
Detailed Description
Definition at line 687 of file YAMLTraits.h.
Constructor & Destructor Documentation
IO()
IO::IO (void * Ctxt = nullptr)
Definition at line 37 of file YAMLTraits.cpp.
Referenced by llvm::yaml::Input::Input(), llvm::yaml::Input::Input(), and llvm::yaml::Output::Output().
~IO()
IO::~IO () virtual default
Member Function Documentation
beginBitSetScalar()
virtual bool llvm::yaml::IO::beginBitSetScalar (bool &) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
beginEnumScalar()
virtual void llvm::yaml::IO::beginEnumScalar () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize(), and llvm::yaml::yamlizeMappingEnumInput().
beginFlowMapping()
virtual void llvm::yaml::IO::beginFlowMapping () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
beginFlowSequence()
virtual unsigned llvm::yaml::IO::beginFlowSequence () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
beginMapping()
virtual void llvm::yaml::IO::beginMapping () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize(), and llvm::yaml::yamlize().
beginSequence()
virtual unsigned llvm::yaml::IO::beginSequence () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
bitSetCase() [1/2]
template<typename T> void llvm::yaml::IO::bitSetCase (T & Val, StringRef Str, const T ConstVal) inline
Definition at line 759 of file YAMLTraits.h.
References bitSetMatch(), outputting(), and T.
Referenced by llvm::yaml::ScalarBitSetTraits< TBDFlags >::bitset().
bitSetCase() [2/2]
template<typename T> void llvm::yaml::IO::bitSetCase (T & Val, StringRef Str, const uint32_t ConstVal) inline
Definition at line 767 of file YAMLTraits.h.
References bitSetMatch(), outputting(), and T.
bitSetMatch()
virtual bool llvm::yaml::IO::bitSetMatch (StringRef , bool) pure virtual
Implemented in llvm::yaml::Output.
Referenced by bitSetCase(), bitSetCase(), maskedBitSetCase(), and maskedBitSetCase().
blockScalarString()
virtual void llvm::yaml::IO::blockScalarString (StringRef &) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
canElideEmptySequence()
virtual bool llvm::yaml::IO::canElideEmptySequence () pure virtual
Implemented in llvm::yaml::Output.
Referenced by mapOptionalWithContext().
endBitSetScalar()
virtual void llvm::yaml::IO::endBitSetScalar () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
endEnumScalar()
virtual void llvm::yaml::IO::endEnumScalar () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize(), and llvm::yaml::yamlizeMappingEnumInput().
endFlowMapping()
virtual void llvm::yaml::IO::endFlowMapping () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
endFlowSequence()
virtual void llvm::yaml::IO::endFlowSequence () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
endMapping()
virtual void llvm::yaml::IO::endMapping () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize(), and llvm::yaml::yamlize().
endSequence()
virtual void llvm::yaml::IO::endSequence () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
enumCase() [1/2]
template<typename T> void llvm::yaml::IO::enumCase (T & Val, StringRef Str, const T ConstVal) inline
Definition at line 734 of file YAMLTraits.h.
References matchEnumScalar(), outputting(), and T.
Referenced by llvm::yaml::ScalarEnumerationTraits< AccessQualifier >::enumeration(), llvm::yaml::ScalarEnumerationTraits< AddressSpaceQualifier >::enumeration(), llvm::yaml::ScalarEnumerationTraits< AMXProgModelEnum >::enumeration(), llvm::yaml::ScalarEnumerationTraits< COFFYAML::COMDATType >::enumeration(), llvm::yaml::ScalarEnumerationTraits< COFFYAML::WeakExternalCharacteristics >::enumeration(), llvm::yaml::ScalarEnumerationTraits< FixedMachineStackObject::ObjectType >::enumeration(), llvm::yaml::ScalarEnumerationTraits< IFSSymbolType >::enumeration(), llvm::yaml::ScalarEnumerationTraits< MachineJumpTableInfo::JTEntryKind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< MachineStackObject::ObjectType >::enumeration(), llvm::yaml::ScalarEnumerationTraits< TargetStackID::Value >::enumeration(), llvm::yaml::ScalarEnumerationTraits< TypeTestResolution::Kind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< ValueKind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< ValueType >::enumeration(), llvm::yaml::ScalarEnumerationTraits< WholeProgramDevirtResolution::ByArg::Kind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< WholeProgramDevirtResolution::Kind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< xray::RecordTypes >::enumeration(), and llvm::yaml::ScalarEnumerationTraits< xray::SledEntry::FunctionKinds >::enumeration().
enumCase() [2/2]
template<typename T> void llvm::yaml::IO::enumCase (T & Val, StringRef Str, const uint32_t ConstVal) inline
Definition at line 742 of file YAMLTraits.h.
References matchEnumScalar(), outputting(), and T.
enumFallback()
template<typename FBT, typename T> void llvm::yaml::IO::enumFallback (T & Val) inline
Definition at line 748 of file YAMLTraits.h.
References matchEnumFallback(), T, and llvm::yaml::yamlize().
Referenced by llvm::yaml::ScalarEnumerationTraits< MachO::BindOpcode >::enumeration(), llvm::yaml::ScalarEnumerationTraits< MachO::LoadCommandType >::enumeration(), llvm::yaml::ScalarEnumerationTraits< MachO::RebaseOpcode >::enumeration(), llvm::yaml::ScalarEnumerationTraits< object::ImageKind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< object::OffloadKind >::enumeration(), llvm::yaml::ScalarEnumerationTraits< WasmYAML::RelocType >::enumeration(), llvm::yaml::ScalarEnumerationTraits< XCOFF::DwarfSectionSubtypeFlags >::enumeration(), and llvm::yaml::ScalarEnumerationTraits< XCOFF::SymbolType >::enumeration().
error()
virtual std::error_code llvm::yaml::IO::error () pure virtual
Implemented in Input, llvm::yaml::Input, and llvm::yaml::Output.
References setAllowUnknownKeys().
Referenced by llvm::yaml::MappingTraits< MachOYAML::Section >::validate().
getContext()
void * IO::getContext () const
Definition at line 41 of file YAMLTraits.cpp.
Referenced by llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::denormalize(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::denormalize(), llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< COFFYAML::SectionDataEntry >::mapping(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::ResourceBindInfo >::mapping(), llvm::yaml::MappingTraits< ExportSection >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Object >::mapping(), llvm::yaml::MappingTraits< MachOYAML::UniversalBinary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::Member >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::StringEntry >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping(), llvm::yaml::MappingTraits< UndefinedSection >::mapping(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), llvm::yaml::yamlize(), and llvm::yaml::yamlize().
getNodeKind()
virtual NodeKind llvm::yaml::IO::getNodeKind () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
keys()
virtual std::vector< StringRef > llvm::yaml::IO::keys () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::MappingTraits< SIArgument >::mapping(), and llvm::yaml::yamlize().
mapOptional() [1/2]
template<typename T> void llvm::yaml::IO::mapOptional (StringRef Key, T & Val) inline
Definition at line 799 of file YAMLTraits.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, mapOptionalWithContext(), and T.
Referenced by llvm::yaml::auxSymMapping(), llvm::yaml::auxSymMapping(), llvm::yaml::auxSymMapping(), llvm::yaml::auxSymMapping(), llvm::yaml::auxSymMapping(), llvm::yaml::auxSymMapping(), llvm::yaml::auxSymMapping(), llvm::yaml::commonSectionMapping(), llvm::yaml::commonSectionMapping(), llvm::yaml::fillMapping(), llvm::yaml::groupSectionMapping(), llvm::CodeViewYAML::detail::LeafRecordImpl< FieldListRecord >::map(), llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::map(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValues(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValuesV4(), llvm::yaml::mapLoadCommandData< MachO::build_version_command >(), llvm::yaml::mapLoadCommandData< MachO::dylib_command >(), llvm::yaml::mapLoadCommandData< MachO::dylinker_command >(), llvm::yaml::mapLoadCommandData< MachO::rpath_command >(), llvm::yaml::mapLoadCommandData< MachO::segment_command >(), llvm::yaml::mapLoadCommandData< MachO::segment_command_64 >(), llvm::yaml::mapLoadCommandData< MachO::sub_client_command >(), llvm::yaml::mapLoadCommandData< MachO::sub_framework_command >(), llvm::yaml::mapLoadCommandData< MachO::sub_library_command >(), llvm::yaml::mapLoadCommandData< MachO::sub_umbrella_command >(), llvm::yaml::mapLoadConfig(), llvm::yaml::mapLoadConfigMember(), mapOptional(), mapOptionalAs(), llvm::yaml::MappingTraits< AArch64FunctionInfo >::mapping(), llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::mapping(), llvm::yaml::MappingTraits< Argument >::mapping(), llvm::yaml::MappingTraits< ARMFunctionInfo >::mapping(), llvm::yaml::MappingTraits< CallSiteInfo >::mapping(), llvm::yaml::MappingTraits< CallSiteYAML >::mapping(), llvm::yaml::MappingTraits< COFF::AuxiliarySectionDefinition >::mapping(), llvm::yaml::MappingTraits< COFF::header >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Object >::mapping(), llvm::yaml::MappingTraits< COFFYAML::PEHeader >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Section >::mapping(), llvm::yaml::MappingTraits< COFFYAML::SectionDataEntry >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Symbol >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::DXILProgram >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::FileHeader >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::Part >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping(), llvm::yaml::MappingTraits< ExportSection >::mapping(), llvm::yaml::MappingTraits< FixedMachineStackObject >::mapping(), llvm::yaml::MappingTraits< FunctionSummary::ConstVCall >::mapping(), llvm::yaml::MappingTraits< FunctionSummary::VFuncId >::mapping(), llvm::yaml::MappingTraits< FunctionYAML >::mapping(), llvm::yaml::MappingTraits< GlobalValueSummaryYaml >::mapping(), llvm::yaml::MappingTraits< HSAMD::Metadata >::mapping(), llvm::yaml::MappingTraits< IFSStub >::mapping(), llvm::yaml::MappingTraits< IFSStubTriple >::mapping(), llvm::yaml::MappingTraits< IFSSymbol >::mapping(), llvm::yaml::MappingTraits< IFSTarget >::mapping(), llvm::yaml::MappingTraits< InstrProfCorrelator::Probe >::mapping(), llvm::yaml::MappingTraits< Kernel::Arg::Metadata >::mapping(), llvm::yaml::MappingTraits< Kernel::Attrs::Metadata >::mapping(), llvm::yaml::MappingTraits< Kernel::CodeProps::Metadata >::mapping(), llvm::yaml::MappingTraits< Kernel::DebugProps::Metadata >::mapping(), llvm::yaml::MappingTraits< Kernel::Metadata >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::DescriptorTableYaml >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping(), llvm::yaml::MappingTraits< MachineConstantPoolValue >::mapping(), llvm::yaml::MappingTraits< MachineFrameInfo >::mapping(), llvm::yaml::MappingTraits< MachineFunction >::mapping(), llvm::yaml::MappingTraits< MachineFunctionLiveIn >::mapping(), llvm::yaml::MappingTraits< MachineJumpTable >::mapping(), llvm::yaml::MappingTraits< MachineJumpTable::Entry >::mapping(), llvm::yaml::MappingTraits< MachineStackObject >::mapping(), llvm::yaml::MappingTraits< MachOYAML::BindOpcode >::mapping(), llvm::yaml::MappingTraits< MachOYAML::ExportEntry >::mapping(), llvm::yaml::MappingTraits< MachOYAML::FatArch >::mapping(), llvm::yaml::MappingTraits< MachOYAML::LinkEditData >::mapping(), llvm::yaml::MappingTraits< MachOYAML::LoadCommand >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Object >::mapping(), llvm::yaml::MappingTraits< MachOYAML::RebaseOpcode >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Section >::mapping(), llvm::yaml::MappingTraits< memprof::AllMemProfData >::mapping(), llvm::yaml::MappingTraits< memprof::CallSiteInfo >::mapping(), llvm::yaml::MappingTraits< memprof::DataAccessProfRecord >::mapping(), llvm::yaml::MappingTraits< memprof::GUIDMemProfRecordPair >::mapping(), llvm::yaml::MappingTraits< memprof::SourceLocation >::mapping(), llvm::yaml::MappingTraits< memprof::YamlDataAccessProfData >::mapping(), llvm::yaml::MappingTraits< ModuleSummaryIndex >::mapping(), llvm::yaml::MappingTraits< object::coff_load_config_code_integrity >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::Member >::mapping(), llvm::yaml::MappingTraits< RISCVMachineFunctionInfo >::mapping(), llvm::yaml::MappingTraits< SaveRestorePointEntry >::mapping(), llvm::yaml::MappingTraits< SerializableCtxRepresentation >::mapping(), llvm::yaml::MappingTraits< SerializableProfileRepresentation >::mapping(), llvm::yaml::MappingTraits< SerializableRootRepresentation >::mapping(), llvm::yaml::MappingTraits< SIArgument >::mapping(), llvm::yaml::MappingTraits< SIArgumentInfo >::mapping(), llvm::yaml::MappingTraits< SIMachineFunctionInfo >::mapping(), llvm::yaml::MappingTraits< SIMode >::mapping(), llvm::yaml::MappingTraits< SymbolSection >::mapping(), llvm::yaml::MappingTraits< TypeIdSummary >::mapping(), llvm::yaml::MappingTraits< TypeTestResolution >::mapping(), llvm::yaml::MappingTraits< UndefinedSection >::mapping(), llvm::yaml::MappingTraits< VirtualRegisterDefinition >::mapping(), llvm::yaml::MappingTraits< WasmYAML::DataSegment >::mapping(), llvm::yaml::MappingTraits< WasmYAML::ElemSegment >::mapping(), llvm::yaml::MappingTraits< WasmYAML::InitExpr >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Limits >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Object >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< WasmYAML::SymbolInfo >::mapping(), llvm::yaml::MappingTraits< WebAssemblyFunctionInfo >::mapping(), llvm::yaml::MappingTraits< WholeProgramDevirtResolution >::mapping(), llvm::yaml::MappingTraits< WholeProgramDevirtResolution::ByArg >::mapping(), llvm::yaml::MappingTraits< X86MachineFunctionInfo >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::AuxiliaryHeader >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::FileHeader >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::Object >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::Section >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::StringTable >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::Symbol >::mapping(), llvm::yaml::MappingTraits< xray::YAMLXRayRecord >::mapping(), llvm::yaml::MappingTraits< xray::YAMLXRaySledEntry >::mapping(), mapRemarkHeader(), llvm::yaml::sectionHeaderTableMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), streamMapping(), streamMapping(), and streamMapping().
mapOptional() [2/2]
template<typename T, typename DefaultT> void llvm::yaml::IO::mapOptional (StringRef Key, T & Val, const DefaultT & Default) inline
Definition at line 805 of file YAMLTraits.h.
References Default, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, mapOptionalWithContext(), and T.
mapOptionalWithContext() [1/3]
template<typename T, typename Context> void llvm::yaml::IO::mapOptionalWithContext (StringRef Key, std::optional< T > & Val, Context & Ctx) inline
Definition at line 821 of file YAMLTraits.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
mapOptionalWithContext() [2/3]
template<typename T, typename Context, typename DefaultT> void llvm::yaml::IO::mapOptionalWithContext (StringRef Key, T & Val, const DefaultT & Default, Context & Ctx) inline
Definition at line 828 of file YAMLTraits.h.
References Default, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and T.
mapOptionalWithContext() [3/3]
template<typename T, typename Context> void llvm::yaml::IO::mapOptionalWithContext (StringRef Key, T & Val, Context & Ctx) inline
Definition at line 811 of file YAMLTraits.h.
References canElideEmptySequence(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and T.
Referenced by llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValuesV4(), mapOptional(), and mapOptional().
mapRequired() [1/2]
template<typename T> void llvm::yaml::IO::mapRequired (StringRef Key, T & Val) inline
Definition at line 789 of file YAMLTraits.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and T.
Referenced by llvm::yaml::commonSectionMapping(), llvm::yaml::commonSectionMapping(), llvm::yaml::fillMapping(), llvm::yaml::getStringValue(), llvm::yaml::CustomMappingTraits< BBNumberMap >::inputOne(), llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::inputOne(), llvm::yaml::CustomMappingTraits< IdHashNodeStableMapTy >::inputOne(), llvm::yaml::CustomMappingTraits< MapDocNode >::inputOne(), llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >::inputOne(), llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >::inputOne(), llvm::yaml::CustomMappingTraits< TypeIdSummaryMapTy >::inputOne(), llvm::yaml::StdMapStringCustomMappingTraitsImpl< T >::inputOne(), llvm::CodeViewYAML::detail::LeafRecordImpl< FieldListRecord >::map(), llvm::CodeViewYAML::detail::LeafRecordImpl< FieldListRecord >::map(), llvm::CodeViewYAML::detail::MemberRecordImpl< T >::map(), llvm::CodeViewYAML::detail::SymbolRecordImpl< T >::map(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::map(), llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValues(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValuesV4(), mapLeafRecordImpl(), mapMemberRecordImpl(), llvm::yaml::MappingContextTraits< DXContainerYAML::RootParameterLocationYaml, DXContainerYAML::RootSignatureYamlDesc >::mapping(), llvm::yaml::MappingContextTraits< MetadataSection, MetadataSection::Option >::mapping(), llvm::yaml::MappingTraits< Argument >::mapping(), llvm::yaml::MappingTraits< CalledGlobal >::mapping(), llvm::yaml::MappingTraits< CallSiteInfo >::mapping(), llvm::yaml::MappingTraits< CallSiteInfo::ArgRegPair >::mapping(), llvm::yaml::MappingTraits< CallSiteYAML >::mapping(), llvm::yaml::MappingTraits< COFF::AuxiliarybfAndefSymbol >::mapping(), llvm::yaml::MappingTraits< COFF::AuxiliaryCLRToken >::mapping(), llvm::yaml::MappingTraits< COFF::AuxiliaryFunctionDefinition >::mapping(), llvm::yaml::MappingTraits< COFF::AuxiliarySectionDefinition >::mapping(), llvm::yaml::MappingTraits< COFF::AuxiliaryWeakExternal >::mapping(), llvm::yaml::MappingTraits< COFF::DataDirectory >::mapping(), llvm::yaml::MappingTraits< COFF::header >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Object >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Section >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Symbol >::mapping(), llvm::yaml::MappingTraits< DebugValueSubstitution >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::DXILProgram >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::FileHeader >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::Object >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::Part >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::ResourceBindInfo >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::ShaderHash >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::Signature >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::SignatureElement >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::SignatureParameter >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::VersionTuple >::mapping(), llvm::yaml::MappingTraits< EntryValueObject >::mapping(), llvm::yaml::MappingTraits< ExportSection >::mapping(), llvm::yaml::MappingTraits< FixedMachineStackObject >::mapping(), llvm::yaml::MappingTraits< FunctionsYAML >::mapping(), llvm::yaml::MappingTraits< FunctionYAML >::mapping(), llvm::yaml::MappingTraits< HashNodeStable >::mapping(), llvm::yaml::MappingTraits< HSAMD::Metadata >::mapping(), llvm::yaml::MappingTraits< IFSStub >::mapping(), llvm::yaml::MappingTraits< IFSStubTriple >::mapping(), llvm::yaml::MappingTraits< IFSSymbol >::mapping(), llvm::yaml::MappingTraits< IndexPairHash >::mapping(), llvm::yaml::MappingTraits< InstrProfCorrelator::CorrelationData >::mapping(), llvm::yaml::MappingTraits< InstrProfCorrelator::Probe >::mapping(), llvm::yaml::MappingTraits< Kernel::Arg::Metadata >::mapping(), llvm::yaml::MappingTraits< Kernel::CodeProps::Metadata >::mapping(), llvm::yaml::MappingTraits< Kernel::Metadata >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::DescriptorRangeYaml >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::DescriptorTableYaml >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::RootConstantsYaml >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::RootDescriptorYaml >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >::mapping(), llvm::yaml::MappingTraits< llvm::xray::YAMLXRayTrace >::mapping(), llvm::yaml::MappingTraits< LocalVariableAddrGap >::mapping(), llvm::yaml::MappingTraits< LocalVariableAddrRange >::mapping(), llvm::yaml::MappingTraits< MachineConstantPoolValue >::mapping(), llvm::yaml::MappingTraits< MachineFunction >::mapping(), llvm::yaml::MappingTraits< MachineFunctionLiveIn >::mapping(), llvm::yaml::MappingTraits< MachineJumpTable >::mapping(), llvm::yaml::MappingTraits< MachineJumpTable::Entry >::mapping(), llvm::yaml::MappingTraits< MachineStackObject >::mapping(), llvm::yaml::MappingTraits< MachO::build_tool_version >::mapping(), llvm::yaml::MappingTraits< MachO::dylib >::mapping(), llvm::yaml::MappingTraits< MachO::fvmlib >::mapping(), llvm::yaml::MappingTraits< MachO::section >::mapping(), llvm::yaml::MappingTraits< MachO::section_64 >::mapping(), llvm::yaml::MappingTraits< MachOYAML::BindOpcode >::mapping(), llvm::yaml::MappingTraits< MachOYAML::DataInCodeEntry >::mapping(), llvm::yaml::MappingTraits< MachOYAML::ExportEntry >::mapping(), llvm::yaml::MappingTraits< MachOYAML::FatArch >::mapping(), llvm::yaml::MappingTraits< MachOYAML::FatHeader >::mapping(), llvm::yaml::MappingTraits< MachOYAML::FileHeader >::mapping(), llvm::yaml::MappingTraits< MachOYAML::LoadCommand >::mapping(), llvm::yaml::MappingTraits< MachOYAML::NListEntry >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Object >::mapping(), llvm::yaml::MappingTraits< MachOYAML::RebaseOpcode >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Section >::mapping(), llvm::yaml::MappingTraits< MachOYAML::UniversalBinary >::mapping(), llvm::yaml::MappingTraits< memprof::AllocationInfo >::mapping(), llvm::yaml::MappingTraits< memprof::CallSiteInfo >::mapping(), llvm::yaml::MappingTraits< memprof::DataAccessProfRecord >::mapping(), llvm::yaml::MappingTraits< memprof::Frame >::mapping(), llvm::yaml::MappingTraits< memprof::GUIDMemProfRecordPair >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::StringEntry >::mapping(), llvm::yaml::MappingTraits< RemarkLocation >::mapping(), llvm::yaml::MappingTraits< SaveRestorePointEntry >::mapping(), llvm::yaml::MappingTraits< SerializableCtxRepresentation >::mapping(), llvm::yaml::MappingTraits< SerializableFlatProfileRepresentation >::mapping(), llvm::yaml::MappingTraits< SerializableRootRepresentation >::mapping(), llvm::yaml::MappingTraits< SIArgument >::mapping(), llvm::yaml::MappingTraits< StableFunction >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< WasmYAML::Section > >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping(), llvm::yaml::MappingTraits< SymbolSection >::mapping(), llvm::yaml::MappingTraits< UmbrellaSection >::mapping(), llvm::yaml::MappingTraits< UndefinedSection >::mapping(), llvm::yaml::MappingTraits< UUIDv4 >::mapping(), llvm::yaml::MappingTraits< VirtualRegisterDefinition >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Comdat >::mapping(), llvm::yaml::MappingTraits< WasmYAML::ComdatEntry >::mapping(), llvm::yaml::MappingTraits< WasmYAML::DataSegment >::mapping(), llvm::yaml::MappingTraits< WasmYAML::DylinkExportInfo >::mapping(), llvm::yaml::MappingTraits< WasmYAML::DylinkImportInfo >::mapping(), llvm::yaml::MappingTraits< WasmYAML::ElemSegment >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Export >::mapping(), llvm::yaml::MappingTraits< WasmYAML::FeatureEntry >::mapping(), llvm::yaml::MappingTraits< WasmYAML::FileHeader >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Function >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Global >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Import >::mapping(), llvm::yaml::MappingTraits< WasmYAML::InitExpr >::mapping(), llvm::yaml::MappingTraits< WasmYAML::InitFunction >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Limits >::mapping(), llvm::yaml::MappingTraits< WasmYAML::LocalDecl >::mapping(), llvm::yaml::MappingTraits< WasmYAML::NameEntry >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Object >::mapping(), llvm::yaml::MappingTraits< WasmYAML::ProducerEntry >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< WasmYAML::SegmentInfo >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Signature >::mapping(), llvm::yaml::MappingTraits< WasmYAML::SymbolInfo >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Table >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::Object >::mapping(), llvm::yaml::MappingTraits< xray::YAMLXRayFileHeader >::mapping(), llvm::yaml::MappingTraits< xray::YAMLXRayRecord >::mapping(), llvm::yaml::MappingTraits< xray::YAMLXRaySledEntry >::mapping(), mapRemarkHeader(), mapRequiredAs(), mapSymbolRecordImpl(), llvm::yaml::CustomMappingTraits< BBNumberMap >::output(), llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::output(), llvm::yaml::CustomMappingTraits< IdHashNodeStableMapTy >::output(), llvm::yaml::CustomMappingTraits< MapDocNode >::output(), llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >::output(), llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >::output(), llvm::yaml::CustomMappingTraits< TypeIdSummaryMapTy >::output(), llvm::yaml::StdMapStringCustomMappingTraitsImpl< T >::output(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::setStringValue(), streamMapping(), streamMapping(), streamMapping(), streamMapping(), and streamMapping().
mapRequired() [2/2]
template<typename T, typename Context> void llvm::yaml::IO::mapRequired (StringRef Key, T & Val, Context & Ctx) inline
Definition at line 795 of file YAMLTraits.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and T.
mapTag()
virtual bool llvm::yaml::IO::mapTag (StringRef Tag, bool Default = false) pure virtual
Implemented in llvm::yaml::Output.
References Default.
Referenced by llvm::yaml::MappingTraits< const InterfaceFile * >::mapKeysToValuesV4(), llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< COFFYAML::Object >::mapping(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::Object >::mapping(), llvm::yaml::MappingTraits< IFSStub >::mapping(), llvm::yaml::MappingTraits< IFSStubTriple >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Object >::mapping(), llvm::yaml::MappingTraits< MachOYAML::UniversalBinary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary >::mapping(), llvm::yaml::MappingTraits< remarks::Remark * >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Object >::mapping(), llvm::yaml::MappingTraits< XCOFFYAML::Object >::mapping(), and llvm::yaml::MappingTraits< const InterfaceFile * >::setFileTypeForInput().
maskedBitSetCase() [1/2]
template<typename T> void llvm::yaml::IO::maskedBitSetCase (T & Val, StringRef Str, T ConstVal, T Mask) inline
Definition at line 774 of file YAMLTraits.h.
References bitSetMatch(), outputting(), and T.
maskedBitSetCase() [2/2]
template<typename T> void llvm::yaml::IO::maskedBitSetCase (T & Val, StringRef Str, uint32_t ConstVal, uint32_t Mask) inline
Definition at line 780 of file YAMLTraits.h.
References bitSetMatch(), outputting(), and T.
matchEnumFallback()
virtual bool llvm::yaml::IO::matchEnumFallback () pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::ScalarEnumerationTraits< IFSSymbolType >::enumeration(), enumFallback(), and llvm::yaml::yamlizeMappingEnumInput().
matchEnumScalar()
virtual bool llvm::yaml::IO::matchEnumScalar (StringRef , bool) pure virtual
Implemented in llvm::yaml::Output.
Referenced by enumCase(), and enumCase().
outputting()
virtual bool llvm::yaml::IO::outputting () const pure virtual
Implemented in llvm::yaml::Output.
Referenced by bitSetCase(), bitSetCase(), llvm::yaml::commonSectionMapping(), llvm::yaml::SequenceTraits< ArrayRef< T > >::element(), enumCase(), enumCase(), llvm::yaml::ScalarEnumerationTraits< IFSSymbolType >::enumeration(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::map(), mapLeafRecordImpl(), mapMemberRecordImpl(), llvm::yaml::MappingTraits< Argument >::mapping(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapping(), llvm::yaml::MappingTraits< HSAMD::Metadata >::mapping(), llvm::yaml::MappingTraits< Kernel::Metadata >::mapping(), llvm::yaml::MappingTraits< llvm::DXContainerYAML::DescriptorRangeYaml >::mapping(), llvm::yaml::MappingTraits< MachineFunction >::mapping(), llvm::yaml::MappingTraits< MachOYAML::LinkEditData >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Object >::mapping(), llvm::yaml::MappingTraits< memprof::AllMemProfData >::mapping(), llvm::yaml::MappingTraits< memprof::DataAccessProfRecord >::mapping(), llvm::yaml::MappingTraits< ModuleSummaryIndex >::mapping(), llvm::yaml::MappingTraits< RemarkLocation >::mapping(), llvm::yaml::MappingTraits< remarks::Remark * >::mapping(), llvm::yaml::MappingTraits< SIArgument >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< WasmYAML::Section > >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping(), llvm::yaml::MappingTraits< WasmYAML::ElemSegment >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Limits >::mapping(), mapSymbolRecordImpl(), maskedBitSetCase(), maskedBitSetCase(), llvm::yaml::ResetAuxSym(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::yaml::yamlize(), llvm::yaml::yamlize(), llvm::yaml::yamlize(), llvm::yaml::yamlize(), and llvm::yaml::yamlizeMappingEnumInput().
postflightElement()
virtual void llvm::yaml::IO::postflightElement (void *) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
postflightFlowElement()
virtual void llvm::yaml::IO::postflightFlowElement (void *) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
postflightKey()
virtual void llvm::yaml::IO::postflightKey (void *) pure virtual
Implemented in llvm::yaml::Output.
preflightElement()
virtual bool llvm::yaml::IO::preflightElement (unsigned , void *&) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
preflightFlowElement()
virtual bool llvm::yaml::IO::preflightFlowElement (unsigned , void *&) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
preflightKey()
virtual bool llvm::yaml::IO::preflightKey (StringRef , bool , bool , bool & , void *&) pure virtual
Implemented in llvm::yaml::Output.
scalarString()
virtual void llvm::yaml::IO::scalarString (StringRef & , QuotingType) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
scalarTag()
virtual void llvm::yaml::IO::scalarTag (std::string &) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::yamlize().
setAllowUnknownKeys()
void IO::setAllowUnknownKeys (bool Allow) virtual
Reimplemented in Input, and llvm::yaml::Input.
Definition at line 49 of file YAMLTraits.cpp.
References llvm_unreachable.
Referenced by error().
setContext()
void IO::setContext (void * Context)
Definition at line 45 of file YAMLTraits.cpp.
Referenced by llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< COFF::header >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping(), llvm::yaml::MappingTraits< MachOYAML::Object >::mapping(), llvm::yaml::MappingTraits< MachOYAML::UniversalBinary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary >::mapping(), llvm::yaml::MappingTraits< WasmYAML::Object >::mapping(), and llvm::yaml::MappingTraits< XCOFFYAML::Object >::mapping().
setError()
virtual void llvm::yaml::IO::setError (const Twine &) pure virtual
Implemented in llvm::yaml::Output.
Referenced by llvm::yaml::IsResizableBase< T >::element(), llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::inputOne(), llvm::yaml::CustomMappingTraits< IdHashNodeStableMapTy >::inputOne(), llvm::yaml::CustomMappingTraits< memprof::PortableMemInfoBlock >::inputOne(), llvm::yaml::CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >::inputOne(), llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >::inputOne(), llvm::yaml::mapLoadConfig(), llvm::yaml::MappingTraits< COFFYAML::Section >::mapping(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapping(), llvm::yaml::MappingTraits< IFSStub >::mapping(), llvm::yaml::MappingTraits< IFSStubTriple >::mapping(), llvm::yaml::MappingTraits< SIArgument >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping(), llvm::yaml::sectionMapping(), llvm::yaml::yamlize(), llvm::yaml::yamlize(), and llvm::yaml::yamlize().
The documentation for this class was generated from the following files:
include/llvm/Support/YAMLTraits.h
lib/Support/YAMLTraits.cpp