LLVM: llvm::orc::CAPIDefinitionGenerator Class Reference
llvm::orc::CAPIDefinitionGenerator Class Reference final
Public Member Functions
CAPIDefinitionGenerator (LLVMOrcDisposeCAPIDefinitionGeneratorFunction Dispose, void *Ctx, LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction TryToGenerate)
~CAPIDefinitionGenerator () override
Error tryToGenerate (LookupState &LS, LookupKind K, JITDylib &JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet &LookupSet) override
DefinitionGenerators should override this method to insert new definitions into the parent JITDylib.
Public Member Functions inherited from llvm::orc::DefinitionGenerator
virtual ~DefinitionGenerator ()
Detailed Description
Definition at line 262 of file OrcV2CBindings.cpp.
Constructor & Destructor Documentation
CAPIDefinitionGenerator()
llvm::orc::CAPIDefinitionGenerator::CAPIDefinitionGenerator (LLVMOrcDisposeCAPIDefinitionGeneratorFunction Dispose, void * Ctx, LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction TryToGenerate) inline
Definition at line 264 of file OrcV2CBindings.cpp.
~CAPIDefinitionGenerator()
llvm::orc::CAPIDefinitionGenerator::~CAPIDefinitionGenerator () inline override
Definition at line 269 of file OrcV2CBindings.cpp.
Member Function Documentation
tryToGenerate()
Error llvm::orc::CAPIDefinitionGenerator::tryToGenerate (LookupState & LS, LookupKind K, JITDylib & JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet & LookupSet) inline override virtual
DefinitionGenerators should override this method to insert new definitions into the parent JITDylib.
K specifies the kind of this lookup. JD specifies the target JITDylib being searched, and JDLookupFlags specifies whether the search should match against hidden symbols. Finally, Symbols describes the set of unresolved symbols and their associated lookup flags.
Implements llvm::orc::DefinitionGenerator.
Definition at line 274 of file OrcV2CBindings.cpp.
References llvm::orc::OrcV2CAPIHelper::extractLookupState(), llvm::orc::SymbolStringPoolEntryUnsafe::from(), llvm::orc::OrcV2CAPIHelper::resetLookupState(), llvm::orc::SymbolLookupSet::size(), llvm::unwrap(), and llvm::wrap().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/OrcV2CBindings.cpp