LLVM: llvm::GenericCycleInfo< ContextT > Class Template Reference
llvm::GenericCycleInfo< ContextT > Class Template Reference
Cycle information for a function.
#include "llvm/ADT/GenericCycleInfo.h"
Classes
struct const_toplevel_iterator
Public Types
using BlockT = typename ContextT::BlockT
using CycleT = GenericCycle<ContextT>
using FunctionT = typename ContextT::FunctionT
using const_toplevel_iterator_base
Iteration over top-level cycles.
Public Member Functions
GenericCycleInfo ()=default
GenericCycleInfo (GenericCycleInfo &&)=default
GenericCycleInfo & operator= (GenericCycleInfo &&)=default
void clear ()
Reset the object to its initial state.
void compute (FunctionT &F)
Compute the cycle info for a function.
void splitCriticalEdge (BlockT *Pred, BlockT *Succ, BlockT *New)
const FunctionT * getFunction () const
const ContextT & getSSAContext () const
CycleT * getCycle (const BlockT *Block) const
Find the innermost cycle containing a given block.
CycleT * getSmallestCommonCycle (CycleT *A, CycleT *B) const
Find the innermost cycle containing both given cycles.
CycleT * getSmallestCommonCycle (BlockT *A, BlockT *B) const
Find the innermost cycle containing both given blocks.
unsigned getCycleDepth (const BlockT *Block) const
get the depth for the cycle which containing a given block.
CycleT * getTopLevelParentCycle (BlockT *Block)
void addBlockToCycle (BlockT *Block, CycleT *Cycle)
Assumes that Cycle is the innermost cycle containing Block.
void verifyCycleNest (bool VerifyFull=false) const
Methods for debug and self-test.
void verify () const
Verify that the entire cycle tree well-formed.
void print (raw_ostream &Out) const
Print the cycle info.
void dump () const
Printable print (const CycleT *Cycle)
const_toplevel_iterator toplevel_begin () const
const_toplevel_iterator toplevel_end () const
iterator_range< const_toplevel_iterator > toplevel_cycles () const
Friends
template<typename>
class GenericCycle
template<typename>
class GenericCycleInfoCompute
Detailed Description
template<typename ContextT>
class llvm::GenericCycleInfo< ContextT >
Cycle information for a function.
Definition at line 255 of file GenericCycleInfo.h.
Member Typedef Documentation
BlockT
template<typename ContextT> using llvm::GenericCycleInfo< ContextT >::BlockT = typename ContextT::BlockT
Definition at line 257 of file GenericCycleInfo.h.
const_toplevel_iterator_base
template<typename ContextT> using llvm::GenericCycleInfo< ContextT >::const_toplevel_iterator_base
Initial value:
typename std::vector<std::unique_ptr<CycleT>>::const_iterator
Iteration over top-level cycles.
Definition at line 319 of file GenericCycleInfo.h.
CycleT
template<typename ContextT> using llvm::GenericCycleInfo< ContextT >::CycleT = GenericCycle<ContextT>
Definition at line 258 of file GenericCycleInfo.h.
FunctionT
template<typename ContextT> using llvm::GenericCycleInfo< ContextT >::FunctionT = typename ContextT::FunctionT
Definition at line 259 of file GenericCycleInfo.h.
Constructor & Destructor Documentation
GenericCycleInfo() [1/2]
template<typename ContextT> llvm::GenericCycleInfo< ContextT >::GenericCycleInfo () default
GenericCycleInfo() [2/2]
template<typename ContextT> llvm::GenericCycleInfo< ContextT >::GenericCycleInfo (GenericCycleInfo< ContextT > &&) default
Member Function Documentation
addBlockToCycle()
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::addBlockToCycle (BlockT * Block, CycleT * Cycle)
Assumes that Cycle is the innermost cycle containing Block.
Block will be appended to Cycle and all of its parent cycles. Block will be added to BlockMap with Cycle and BlockMapTopLevel with Cycle's top level parent cycle.
Definition at line 312 of file GenericCycleImpl.h.
References llvm::Block.
Referenced by fixIrreducible(), and splitCriticalEdge().
clear()
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::clear ()
Reset the object to its initial state.
Definition at line 495 of file GenericCycleImpl.h.
compute()
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::compute (FunctionT & F)
Compute the cycle info for a function.
Definition at line 503 of file GenericCycleImpl.h.
References llvm::errs(), F, GenericCycleInfoCompute, LLVM_DEBUG, and llvm::GenericCycleInfoCompute< ContextT >::run().
Referenced by llvm::CycleAnalysis::run(), and llvm::MachineCycleAnalysis::run().
dump()
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::dump () const inline
Definition at line 313 of file GenericCycleInfo.h.
getCycle()
template<typename ContextT> auto llvm::GenericCycleInfo< ContextT >::getCycle (const BlockT * Block) const
Find the innermost cycle containing a given block.
Returns
the innermost cycle containing Block or nullptr if it is not contained in any cycle.
Definition at line 530 of file GenericCycleImpl.h.
References llvm::Block.
Referenced by getCycleDepth(), getSmallestCommonCycle(), llvm::SIInstrInfo::isSafeToSink(), mayBeInCycle(), and splitCriticalEdge().
getCycleDepth()
template<typename ContextT> unsigned llvm::GenericCycleInfo< ContextT >::getCycleDepth (const BlockT * Block) const
get the depth for the cycle which containing a given block.
Returns
the depth for the innermost cycle containing Block or 0 if it is not contained in any cycle.
Definition at line 580 of file GenericCycleImpl.h.
References llvm::Block, and getCycle().
getFunction()
template<typename ContextT> const FunctionT * llvm::GenericCycleInfo< ContextT >::getFunction () const inline
Definition at line 293 of file GenericCycleInfo.h.
getSmallestCommonCycle() [1/2]
template<typename ContextT> auto llvm::GenericCycleInfo< ContextT >::getSmallestCommonCycle (BlockT * A, BlockT * B) const
Find the innermost cycle containing both given blocks.
Returns
the innermost cycle containing both A and B or nullptr if there is no such cycle.
Definition at line 569 of file GenericCycleImpl.h.
References A(), B(), getCycle(), and getSmallestCommonCycle().
getSmallestCommonCycle() [2/2]
template<typename ContextT> auto llvm::GenericCycleInfo< ContextT >::getSmallestCommonCycle (CycleT * A, CycleT * B) const
Find the innermost cycle containing both given cycles.
Returns
the innermost cycle containing both A and B or nullptr if there is no such cycle.
Definition at line 540 of file GenericCycleImpl.h.
References A(), and B().
Referenced by getSmallestCommonCycle(), and splitCriticalEdge().
getSSAContext()
template<typename ContextT> const ContextT & llvm::GenericCycleInfo< ContextT >::getSSAContext () const inline
Definition at line 294 of file GenericCycleInfo.h.
getTopLevelParentCycle()
template<typename ContextT> auto llvm::GenericCycleInfo< ContextT >::getTopLevelParentCycle (BlockT * Block)
Definition at line 269 of file GenericCycleImpl.h.
References llvm::Block, and llvm::CallingConv::C.
operator=()
template<typename ContextT> GenericCycleInfo & llvm::GenericCycleInfo< ContextT >::operator= (GenericCycleInfo< ContextT > &&) default
print() [1/2]
template<typename ContextT> Printable llvm::GenericCycleInfo< ContextT >::print (const CycleT * Cycle) inline
Definition at line 314 of file GenericCycleInfo.h.
print() [2/2]
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::print (raw_ostream & Out) const
Print the cycle info.
Definition at line 622 of file GenericCycleImpl.h.
References llvm::depth_first(), I, and toplevel_cycles().
Referenced by llvm::GenericCycleInfo< MachineSSAContext >::dump(), and fixIrreducible().
splitCriticalEdge()
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::splitCriticalEdge (BlockT * Pred, BlockT * Succ, BlockT * New)
Definition at line 513 of file GenericCycleImpl.h.
References addBlockToCycle(), getCycle(), getSmallestCommonCycle(), and verifyCycleNest().
toplevel_begin()
template<typename ContextT> const_toplevel_iterator llvm::GenericCycleInfo< ContextT >::toplevel_begin () const inline
Definition at line 335 of file GenericCycleInfo.h.
toplevel_cycles()
template<typename ContextT> iterator_range< const_toplevel_iterator > llvm::GenericCycleInfo< ContextT >::toplevel_cycles () const inline
Definition at line 342 of file GenericCycleInfo.h.
Referenced by FixIrreducibleImpl(), print(), and verifyCycleNest().
toplevel_end()
template<typename ContextT> const_toplevel_iterator llvm::GenericCycleInfo< ContextT >::toplevel_end () const inline
Definition at line 338 of file GenericCycleInfo.h.
verify()
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::verify () const
Verify that the entire cycle tree well-formed.
Definition at line 616 of file GenericCycleImpl.h.
References verifyCycleNest().
Referenced by FixIrreducibleImpl(), and llvm::CycleInfoVerifierPass::run().
verifyCycleNest()
template<typename ContextT> void llvm::GenericCycleInfo< ContextT >::verifyCycleNest (bool VerifyFull = false) const
Methods for debug and self-test.
Verify the internal consistency of the cycle tree.
Note that this does not check that cycles are really cycles in the CFG, or that the right set of cycles in the CFG were found.
Definition at line 592 of file GenericCycleImpl.h.
References assert(), llvm::depth_first(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and toplevel_cycles().
Referenced by splitCriticalEdge(), and verify().
Friends And Related Symbol Documentation
GenericCycle
template<typename ContextT> template<typename> friend class GenericCycle friend
Definition at line 260 of file GenericCycleInfo.h.
GenericCycleInfoCompute
template<typename ContextT> template<typename> friend class GenericCycleInfoCompute friend
Definition at line 261 of file GenericCycleInfo.h.
Referenced by compute().
The documentation for this class was generated from the following files:
include/llvm/ADT/GenericCycleInfo.h
include/llvm/ADT/GenericCycleImpl.h