LLVM: llvm::GCStrategyMap Class Reference
llvm::GCStrategyMap Class Reference
#include "llvm/CodeGen/GCMetadata.h"
Public Types
using iterator = MapT::iterator
using const_iterator = MapT::const_iterator
using reverse_iterator = MapT::reverse_iterator
using const_reverse_iterator = MapT::const_reverse_iterator
Public Member Functions
GCStrategyMap ()=default
GCStrategyMap (GCStrategyMap &&)=default
LLVM_ABI bool invalidate (Module &M, const PreservedAnalyses &PA, ModuleAnalysisManager::Invalidator &Inv)
Handle invalidation explicitly.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
const GCStrategy & operator[] (StringRef GCName) const
std::pair< iterator, bool > try_emplace (StringRef GCName)
bool contains (StringRef GCName) const
Detailed Description
Definition at line 156 of file GCMetadata.h.
Member Typedef Documentation
const_iterator
using llvm::GCStrategyMap::const_iterator = MapT::const_iterator
Definition at line 170 of file GCMetadata.h.
const_reverse_iterator
using llvm::GCStrategyMap::const_reverse_iterator = MapT::const_reverse_iterator
Definition at line 172 of file GCMetadata.h.
iterator
using llvm::GCStrategyMap::iterator = MapT::iterator
Definition at line 169 of file GCMetadata.h.
reverse_iterator
using llvm::GCStrategyMap::reverse_iterator = MapT::reverse_iterator
Definition at line 171 of file GCMetadata.h.
Constructor & Destructor Documentation
GCStrategyMap() [1/2]
llvm::GCStrategyMap::GCStrategyMap () default
Referenced by GCStrategyMap().
GCStrategyMap() [2/2]
llvm::GCStrategyMap::GCStrategyMap (GCStrategyMap &&) default
References GCStrategyMap(), and LLVM_ABI.
Member Function Documentation
begin() [1/2]
iterator llvm::GCStrategyMap::begin () inline
Definition at line 174 of file GCMetadata.h.
begin() [2/2]
const_iterator llvm::GCStrategyMap::begin () const inline
Definition at line 175 of file GCMetadata.h.
contains()
bool llvm::GCStrategyMap::contains (StringRef GCName) const inline
Definition at line 196 of file GCMetadata.h.
Referenced by invalidate().
empty()
bool llvm::GCStrategyMap::empty () const inline
Definition at line 184 of file GCMetadata.h.
end() [1/2]
iterator llvm::GCStrategyMap::end () inline
Definition at line 176 of file GCMetadata.h.
end() [2/2]
const_iterator llvm::GCStrategyMap::end () const inline
Definition at line 177 of file GCMetadata.h.
invalidate()
bool GCStrategyMap::invalidate (Module & M, const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator & Inv)
Handle invalidation explicitly.
Definition at line 24 of file GCMetadata.cpp.
References contains(), and F.
operator[]()
const GCStrategy & llvm::GCStrategyMap::operator[] (StringRef GCName) const inline
Definition at line 186 of file GCMetadata.h.
References assert(), and I.
rbegin() [1/2]
reverse_iterator llvm::GCStrategyMap::rbegin () inline
Definition at line 179 of file GCMetadata.h.
rbegin() [2/2]
const_reverse_iterator llvm::GCStrategyMap::rbegin () const inline
Definition at line 180 of file GCMetadata.h.
rend() [1/2]
reverse_iterator llvm::GCStrategyMap::rend () inline
Definition at line 181 of file GCMetadata.h.
rend() [2/2]
const_reverse_iterator llvm::GCStrategyMap::rend () const inline
Definition at line 182 of file GCMetadata.h.
try_emplace()
std::pair< iterator, bool > llvm::GCStrategyMap::try_emplace (StringRef GCName) inline
Definition at line 192 of file GCMetadata.h.
Referenced by llvm::CollectorMetadataAnalysis::run().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GCMetadata.h
lib/CodeGen/GCMetadata.cpp