LLVM: llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids Class Reference
llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids Class Reference
#include "llvm/ProfileData/MemProfYAML.h"
Public Member Functions
CallSiteInfoWithHex64Guids (IO &)
CallSiteInfoWithHex64Guids (IO &, const memprof::CallSiteInfo &CS)
memprof::CallSiteInfo denormalize (IO &)
Public Attributes
decltype(memprof::CallSiteInfo::Frames) Frames
SmallVector< memprof::GUIDHex64 > CalleeGuids
Detailed Description
Definition at line 178 of file MemProfYAML.h.
Constructor & Destructor Documentation
CallSiteInfoWithHex64Guids() [1/2]
llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::CallSiteInfoWithHex64Guids (IO &) inline
Definition at line 180 of file MemProfYAML.h.
CallSiteInfoWithHex64Guids() [2/2]
llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::CallSiteInfoWithHex64Guids (IO & , const memprof::CallSiteInfo & CS) inline
Definition at line 181 of file MemProfYAML.h.
References llvm::memprof::CallSiteInfo::CalleeGuids, CalleeGuids, for(), Frames, and llvm::Guid.
Member Function Documentation
denormalize()
memprof::CallSiteInfo llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::denormalize (IO &) inline
Definition at line 189 of file MemProfYAML.h.
References llvm::memprof::CallSiteInfo::CalleeGuids, CalleeGuids, llvm::memprof::CallSiteInfo::Frames, and Frames.
Member Data Documentation
CalleeGuids
SmallVector<memprof::GUIDHex64> llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::CalleeGuids
Definition at line 203 of file MemProfYAML.h.
Referenced by CallSiteInfoWithHex64Guids(), and denormalize().
Frames
decltype(memprof::CallSiteInfo::Frames) llvm::yaml::MappingTraits< memprof::CallSiteInfo >::CallSiteInfoWithHex64Guids::Frames
Definition at line 201 of file MemProfYAML.h.
Referenced by CallSiteInfoWithHex64Guids(), and denormalize().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/MemProfYAML.h