LLVM: llvm::NVPTXAAResult Class Reference
llvm::NVPTXAAResult Class Reference
#include "Target/NVPTX/NVPTXAliasAnalysis.h"
Public Member Functions
NVPTXAAResult ()=default
NVPTXAAResult (NVPTXAAResult &&Arg)
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation events from the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI, const Instruction *CtxI=nullptr)
ModRefInfo getModRefInfoMask (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool IgnoreLocals)
MemoryEffects getMemoryEffects (const CallBase *Call, AAQueryInfo &AAQI)
MemoryEffects getMemoryEffects (const Function *F)
Public Member Functions inherited from llvm::AAResultBase
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI, const Instruction *I)
AliasResult aliasErrno (const MemoryLocation &Loc, const Module *M)
ModRefInfo getModRefInfoMask (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool IgnoreLocals)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
MemoryEffects getMemoryEffects (const CallBase *Call, AAQueryInfo &AAQI)
MemoryEffects getMemoryEffects (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)=default
AAResultBase (AAResultBase &&Arg)
Detailed Description
Definition at line 21 of file NVPTXAliasAnalysis.h.
Constructor & Destructor Documentation
NVPTXAAResult() [1/2]
llvm::NVPTXAAResult::NVPTXAAResult () default
Referenced by NVPTXAAResult().
NVPTXAAResult() [2/2]
llvm::NVPTXAAResult::NVPTXAAResult (NVPTXAAResult && Arg) inline
Definition at line 24 of file NVPTXAliasAnalysis.h.
References llvm::AAResultBase::AAResultBase(), llvm::move(), and NVPTXAAResult().
Member Function Documentation
alias()
AliasResult NVPTXAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI, const Instruction * CtxI = nullptr)
Definition at line 98 of file NVPTXAliasAnalysis.cpp.
References getAddressSpace(), getAliasResult(), llvm::MemoryLocation::Ptr, and TraverseAddressSpacesLimit.
getMemoryEffects() [1/2]
MemoryEffects NVPTXAAResult::getMemoryEffects (const CallBase * Call, AAQueryInfo & AAQI)
Definition at line 124 of file NVPTXAliasAnalysis.cpp.
References llvm::any_of(), llvm::dyn_cast(), llvm::InlineAsm::isClobber, llvm::MemoryEffectsBase< IRMemLocation >::none(), and llvm::MemoryEffectsBase< IRMemLocation >::unknown().
getMemoryEffects() [2/2]
MemoryEffects llvm::NVPTXAAResult::getMemoryEffects (const Function * F) inline
Definition at line 42 of file NVPTXAliasAnalysis.h.
References F, and llvm::MemoryEffectsBase< IRMemLocation >::unknown().
getModRefInfoMask()
ModRefInfo NVPTXAAResult::getModRefInfoMask (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool IgnoreLocals)
Definition at line 115 of file NVPTXAliasAnalysis.cpp.
References getAddressSpace(), isConstOrParam(), llvm::ModRef, llvm::NoModRef, and TraverseAddressSpacesLimit.
invalidate()
bool llvm::NVPTXAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator & Inv) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 29 of file NVPTXAliasAnalysis.h.
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXAliasAnalysis.h
lib/Target/NVPTX/NVPTXAliasAnalysis.cpp