LLVM: llvm::IRMover Class Reference
llvm::IRMover Class Reference
#include "llvm/Linker/IRMover.h"
Classes
class IdentifiedStructTypeSet
Public Types
typedef std::function< void(GlobalValue &)> ValueAdder
using LazyCallback
using NamedMDNodesT
Public Member Functions
LLVM_ABI IRMover (Module &M)
LLVM_ABI Error move (std::unique_ptr< Module > Src, ArrayRef< GlobalValue * > ValuesToLink, LazyCallback AddLazyFor, bool IsPerformingImport)
Move in the provide values in ValuesToLink from Src.
Module & getModule ()
Detailed Description
Definition at line 31 of file IRMover.h.
Member Typedef Documentation
LazyCallback
using llvm::IRMover::LazyCallback
Initial value:
llvm::unique_function<void(GlobalValue &GV, ValueAdder Add)>
Definition at line 71 of file IRMover.h.
NamedMDNodesT
using llvm::IRMover::NamedMDNodesT
Initial value:
DenseMap<const NamedMDNode *, SmallPtrSet<const MDNode *, 8>>
Definition at line 74 of file IRMover.h.
ValueAdder
typedef std::function<void(GlobalValue &)> llvm::IRMover::ValueAdder
Definition at line 70 of file IRMover.h.
Constructor & Destructor Documentation
IRMover()
IRMover::IRMover (Module & M)
Definition at line 1677 of file IRMover.cpp.
References llvm::copyModuleAttrToFunctions(), llvm::TypeFinder::getVisitedMetadata(), and llvm::TypeFinder::run().
Member Function Documentation
getModule()
Module & llvm::IRMover::getModule () inline
Definition at line 90 of file IRMover.h.
move()
Error IRMover::move (std::unique_ptr< Module > Src, ArrayRef< GlobalValue * > ValuesToLink, LazyCallback AddLazyFor, bool IsPerformingImport)
Move in the provide values in ValuesToLink from Src.
AddLazyFor is a call back that the IRMover will call when a global value is referenced by one of the ValuesToLink (transitively) but was not present in ValuesToLink. The GlobalValue and a ValueAdder callback are passed as an argument, and the callback is expected to be called if the GlobalValue needs to be added to the ValuesToLink and linked. Pass nullptr if there's no work to be done in such cases.
IsPerformingImport is true when this IR link is to perform ThinLTO function importing from Src.
Definition at line 1699 of file IRMover.cpp.
Referenced by llvm::FunctionImporter::importFunctions().
The documentation for this class was generated from the following files:
include/llvm/Linker/IRMover.h
lib/Linker/IRMover.cpp