LLVM: llvm::orc::SymbolStringPool Class Reference
llvm::orc::SymbolStringPool Class Reference
String pool for symbol names used by the JIT.
#include "llvm/ExecutionEngine/Orc/SymbolStringPool.h"
Public Member Functions
~SymbolStringPool ()
Destroy a SymbolStringPool.
SymbolStringPtr intern (StringRef S)
Create a symbol string pointer from the given string.
void clearDeadEntries ()
Remove from the pool any entries that are no longer referenced.
bool empty () const
Returns true if the pool is empty.
Friends
class SymbolStringPoolTest
class SymbolStringPtrBase
class SymbolStringPoolEntryUnsafe
LLVM_ABI friend raw_ostream & operator<< (raw_ostream &OS, const SymbolStringPool &SSP)
Dump a SymbolStringPool. Useful for debugging dangling-pointer crashes.
Detailed Description
String pool for symbol names used by the JIT.
Definition at line 34 of file SymbolStringPool.h.
Constructor & Destructor Documentation
~SymbolStringPool()
llvm::orc::SymbolStringPool::~SymbolStringPool () inline
Destroy a SymbolStringPool.
Definition at line 286 of file SymbolStringPool.h.
References assert(), and clearDeadEntries().
Member Function Documentation
clearDeadEntries()
void llvm::orc::SymbolStringPool::clearDeadEntries () inline
Remove from the pool any entries that are no longer referenced.
Definition at line 301 of file SymbolStringPool.h.
References E(), and I.
Referenced by ~SymbolStringPool().
empty()
bool llvm::orc::SymbolStringPool::empty () const inline
Returns true if the pool is empty.
Definition at line 310 of file SymbolStringPool.h.
intern()
SymbolStringPtr llvm::orc::SymbolStringPool::intern (StringRef S) inline
Create a symbol string pointer from the given string.
Definition at line 293 of file SymbolStringPool.h.
References I.
Friends And Related Symbol Documentation
operator<<
LLVM_ABI friend raw_ostream & operator<< (raw_ostream & OS, const SymbolStringPool & SSP) friend
Dump a SymbolStringPool. Useful for debugging dangling-pointer crashes.
Definition at line 294 of file DebugUtils.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), and llvm::sort().
SymbolStringPoolEntryUnsafe
friend class SymbolStringPoolEntryUnsafe friend
Definition at line 37 of file SymbolStringPool.h.
References LLVM_ABI, SymbolStringPoolEntryUnsafe, and SymbolStringPtrBase.
Referenced by SymbolStringPoolEntryUnsafe.
SymbolStringPoolTest
friend class SymbolStringPoolTest friend
Definition at line 35 of file SymbolStringPool.h.
References SymbolStringPoolTest.
Referenced by SymbolStringPoolTest.
SymbolStringPtrBase
friend class SymbolStringPtrBase friend
Definition at line 36 of file SymbolStringPool.h.
References SymbolStringPtrBase.
Referenced by SymbolStringPoolEntryUnsafe, and SymbolStringPtrBase.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/SymbolStringPool.h