LLVM: llvm::cas::BuiltinObjectHasher< HasherT > Class Template Reference
llvm::cas::BuiltinObjectHasher< HasherT > Class Template Reference
Hasher for stored objects in builtin CAS.
#include "llvm/CAS/BuiltinObjectHasher.h"
Public Types
using HashT = decltype(HasherT::hash(std::declval<ArrayRef<uint8_t> &>()))
Static Public Member Functions
static HashT hashObject (const ObjectStore &CAS, ArrayRef< ObjectRef > Refs, ArrayRef< char > Data)
static HashT hashObject (ArrayRef< ArrayRef< uint8_t > > Refs, ArrayRef< char > Data)
Detailed Description
template<class HasherT>
class llvm::cas::BuiltinObjectHasher< HasherT >
Hasher for stored objects in builtin CAS.
Definition at line 18 of file BuiltinObjectHasher.h.
Member Typedef Documentation
HashT
template<class HasherT> using llvm::cas::BuiltinObjectHasher< HasherT >::HashT = decltype(HasherT::hash(std::declval<ArrayRef<uint8_t> &>()))
Definition at line 20 of file BuiltinObjectHasher.h.
Member Function Documentation
hashObject() [1/2]
template<class HasherT> HashT llvm::cas::BuiltinObjectHasher< HasherT >::hashObject (ArrayRef< ArrayRef< uint8_t > > Refs, ArrayRef< char > Data) inline static
Definition at line 32 of file BuiltinObjectHasher.h.
References llvm::Data, H, and llvm::Ref.
hashObject() [2/2]
template<class HasherT> HashT llvm::cas::BuiltinObjectHasher< HasherT >::hashObject (const ObjectStore & CAS, ArrayRef< ObjectRef > Refs, ArrayRef< char > Data) inline static
Definition at line 22 of file BuiltinObjectHasher.h.
References llvm::Data, H, llvm::Ref, and llvm::ArrayRef< T >::size().
Referenced by llvm::cas::builtin::BuiltinCAS::store(), and llvm::cas::builtin::BuiltinCAS::validateObject().
The documentation for this class was generated from the following file:
include/llvm/CAS/BuiltinObjectHasher.h