LLVM: llvm::DbgEntity Class Reference
llvm::DbgEntity Class Reference
This class is defined as the common parent of DbgVariable and DbgLabel such that it could levarage polymorphism to extract common code for DbgVariable and DbgLabel.
#include "CodeGen/AsmPrinter/DwarfDebug.h"
Public Types
enum DbgEntityKind { DbgVariableKind , DbgLabelKind }
Public Member Functions
DbgEntity (const DINode *N, const DILocation *IA, DbgEntityKind ID)
virtual ~DbgEntity ()=default
void setDIE (DIE &D)
const DINode * getEntity () const
Accessors.
const DILocation * getInlinedAt () const
DIE * getDIE () const
DbgEntityKind getDbgEntityID () const
Static Public Member Functions
static bool classof (const DbgEntity *N)
Detailed Description
This class is defined as the common parent of DbgVariable and DbgLabel such that it could levarage polymorphism to extract common code for DbgVariable and DbgLabel.
Definition at line 65 of file DwarfDebug.h.
Member Enumeration Documentation
DbgEntityKind
enum llvm::DbgEntity::DbgEntityKind
Enumerator
DbgVariableKind
DbgLabelKind
Definition at line 67 of file DwarfDebug.h.
Constructor & Destructor Documentation
DbgEntity()
llvm::DbgEntity::DbgEntity (const DINode * N, const DILocation * IA, DbgEntityKind ID) inline
Definition at line 79 of file DwarfDebug.h.
References N.
Referenced by classof(), llvm::DbgLabel::classof(), llvm::DbgVariable::classof(), llvm::DbgLabel::DbgLabel(), and llvm::DbgVariable::DbgVariable().
~DbgEntity()
virtual llvm::DbgEntity::~DbgEntity () virtual default
Member Function Documentation
classof()
bool llvm::DbgEntity::classof (const DbgEntity * N) inline static
Definition at line 93 of file DwarfDebug.h.
References DbgEntity(), DbgLabelKind, DbgVariableKind, llvm_unreachable, and N.
getDbgEntityID()
DbgEntityKind llvm::DbgEntity::getDbgEntityID () const inline
Definition at line 88 of file DwarfDebug.h.
getDIE()
DIE * llvm::DbgEntity::getDIE () const inline
Definition at line 87 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::finishEntityDefinition().
getEntity()
const DINode * llvm::DbgEntity::getEntity () const inline
Accessors.
Definition at line 85 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::finishEntityDefinition(), llvm::DbgLabel::getLabel(), and llvm::DbgVariable::getVariable().
getInlinedAt()
const DILocation * llvm::DbgEntity::getInlinedAt () const inline
Definition at line 86 of file DwarfDebug.h.
setDIE()
void llvm::DbgEntity::setDIE (DIE & D) inline
Definition at line 91 of file DwarfDebug.h.
References D().
Referenced by llvm::DwarfCompileUnit::constructVariableDIE().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/DwarfDebug.h