LLVM: llvm::orc::LibraryScanHelper Class Reference
llvm::orc::LibraryScanHelper Class Reference
Scans and tracks libraries for symbol resolution.
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h"
Public Member Functions
LibraryScanHelper (const std::vector< std::string > &SPaths, std::shared_ptr< LibraryPathCache > LibPathCache, std::shared_ptr< PathResolver > LibPathResolver)
void addBasePath (const std::string &P, PathType Kind=PathType::Unknown)
void getNextBatch (PathType Kind, size_t batchSize, SmallVectorImpl< const LibrarySearchPath * > &Out)
bool leftToScan (PathType K) const
void resetToScan ()
bool isTrackedBasePath (StringRef P) const
bool hasSearchPath () const
SmallVector< StringRef > getSearchPaths () const
PathResolver & getPathResolver () const
LibraryPathCache & getCache () const
bool hasSeenOrMark (StringRef P) const
std::optional< std::string > resolve (StringRef P, std::error_code &ec) const
Detailed Description
Scans and tracks libraries for symbol resolution.
Maintains a list of library paths to scan, caches scanned units, and resolves paths canonically for consistent tracking.
Definition at line 409 of file LibraryScanner.h.
Constructor & Destructor Documentation
LibraryScanHelper()
llvm::orc::LibraryScanHelper::LibraryScanHelper (const std::vector< std::string > & SPaths, std::shared_ptr< LibraryPathCache > LibPathCache, std::shared_ptr< PathResolver > LibPathResolver) inline explicit
Definition at line 411 of file LibraryScanner.h.
References addBasePath(), llvm::dbgs(), DEBUG_WITH_TYPE, and llvm::move().
Member Function Documentation
addBasePath()
void llvm::orc::LibraryScanHelper::addBasePath (const std::string & P, PathType Kind = PathType::Unknown)
Definition at line 650 of file LibraryScanner.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Referenced by LibraryScanHelper().
getCache()
LibraryPathCache & llvm::orc::LibraryScanHelper::getCache () const inline
Definition at line 446 of file LibraryScanner.h.
getNextBatch()
void llvm::orc::LibraryScanHelper::getNextBatch (PathType Kind, size_t batchSize, SmallVectorImpl< const LibrarySearchPath * > & Out)
Definition at line 681 of file LibraryScanner.cpp.
References llvm::sampleprof::Base, llvm::orc::NotScanned, llvm::orc::Result, and llvm::orc::Scanning.
getPathResolver()
PathResolver & llvm::orc::LibraryScanHelper::getPathResolver () const inline
Definition at line 444 of file LibraryScanner.h.
getSearchPaths()
SmallVector< StringRef > llvm::orc::LibraryScanHelper::getSearchPaths () const inline
Definition at line 437 of file LibraryScanner.h.
References _, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
hasSearchPath()
bool llvm::orc::LibraryScanHelper::hasSearchPath () const inline
Definition at line 435 of file LibraryScanner.h.
hasSeenOrMark()
bool llvm::orc::LibraryScanHelper::hasSeenOrMark (StringRef P) const inline
Definition at line 448 of file LibraryScanner.h.
References P.
isTrackedBasePath()
bool llvm::orc::LibraryScanHelper::isTrackedBasePath (StringRef P) const
Definition at line 702 of file LibraryScanner.cpp.
leftToScan()
bool llvm::orc::LibraryScanHelper::leftToScan (PathType K) const
Definition at line 712 of file LibraryScanner.cpp.
References llvm::orc::NotScanned.
resetToScan()
void llvm::orc::LibraryScanHelper::resetToScan ()
Definition at line 722 of file LibraryScanner.cpp.
References _, llvm::SmallVectorImpl< T >::emplace_back(), llvm::orc::NotScanned, and llvm::orc::Scanned.
resolve()
std::optional< std::string > llvm::orc::LibraryScanHelper::resolve (StringRef P, std::error_code & ec) const inline
Definition at line 452 of file LibraryScanner.h.
References P.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryScanner.cpp