LLVM: llvm::codeview::DefRangeSubfieldSym Class Reference
llvm::codeview::DefRangeSubfieldSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
DefRangeSubfieldSym (SymbolRecordKind Kind)
DefRangeSubfieldSym (uint32_t RecordOffset)
uint32_t getRelocationOffset () const
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
uint32_t Program = 0
uint16_t OffsetInParent = 0
LocalVariableAddrRange Range
std::vector< LocalVariableAddrGap > Gaps
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 490 of file SymbolRecord.h.
Constructor & Destructor Documentation
DefRangeSubfieldSym() [1/2]
llvm::codeview::DefRangeSubfieldSym::DefRangeSubfieldSym (SymbolRecordKind Kind) inline explicit
Definition at line 494 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by DefRangeSubfieldSym().
DefRangeSubfieldSym() [2/2]
llvm::codeview::DefRangeSubfieldSym::DefRangeSubfieldSym (uint32_t RecordOffset) inline explicit
Definition at line 495 of file SymbolRecord.h.
References DefRangeSubfieldSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Function Documentation
getRelocationOffset()
uint32_t llvm::codeview::DefRangeSubfieldSym::getRelocationOffset () const inline
Definition at line 499 of file SymbolRecord.h.
References RecordOffset.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Member Data Documentation
Gaps
std::vector<LocalVariableAddrGap> llvm::codeview::DefRangeSubfieldSym::Gaps
Definition at line 506 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
OffsetInParent
uint16_t llvm::codeview::DefRangeSubfieldSym::OffsetInParent = 0
Definition at line 504 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Program
uint32_t llvm::codeview::DefRangeSubfieldSym::Program = 0
Definition at line 503 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Range
LocalVariableAddrRange llvm::codeview::DefRangeSubfieldSym::Range
Definition at line 505 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
RecordOffset
uint32_t llvm::codeview::DefRangeSubfieldSym::RecordOffset = 0
Definition at line 508 of file SymbolRecord.h.
Referenced by DefRangeSubfieldSym(), and getRelocationOffset().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h