LLVM: llvm::orc::rt_bootstrap::SimpleExecutorDylibManager Class Reference
llvm::orc::rt_bootstrap::SimpleExecutorDylibManager Class Reference
Simple page-based allocator.
#include "llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorDylibManager.h"
Public Member Functions
~SimpleExecutorDylibManager () override
Expected< tpctypes::DylibHandle > open (const std::string &Path, uint64_t Mode)
Error shutdown () override
void addBootstrapSymbols (StringMap< ExecutorAddr > &M) override
Public Member Functions inherited from llvm::orc::ExecutorBootstrapService
virtual ~ExecutorBootstrapService ()
Detailed Description
Simple page-based allocator.
Definition at line 38 of file SimpleExecutorDylibManager.h.
Constructor & Destructor Documentation
~SimpleExecutorDylibManager()
llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::~SimpleExecutorDylibManager () override
Definition at line 23 of file SimpleExecutorDylibManager.cpp.
References assert().
Member Function Documentation
addBootstrapSymbols()
void llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::addBootstrapSymbols (StringMap< ExecutorAddr > & M) override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 59 of file SimpleExecutorDylibManager.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::orc::rt::SimpleExecutorDylibManagerInstanceName, llvm::orc::rt::SimpleExecutorDylibManagerOpenWrapperName, and llvm::orc::rt::SimpleExecutorDylibManagerResolveWrapperName.
open()
Expected< tpctypes::DylibHandle > llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::open (const std::string & Path, uint64_t Mode)
Definition at line 28 of file SimpleExecutorDylibManager.cpp.
References DL, llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::DynamicLibrary::getPermanentLibrary(), H, llvm::inconvertibleErrorCode(), llvm::make_error(), Mode, and nullptr.
shutdown()
Error llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::shutdown () override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 47 of file SimpleExecutorDylibManager.cpp.
References llvm::Error::success(), and std::swap().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorDylibManager.h
lib/ExecutionEngine/Orc/TargetProcess/SimpleExecutorDylibManager.cpp