LLVM: llvm::DISourceLanguageName Class Reference
llvm::DISourceLanguageName Class Reference
Wrapper structure that holds a language name and its version.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
bool hasVersionedName () const
uint16_t getName () const
Returns a versioned or unversioned language name.
uint16_t getUnversionedName () const
Transitional API for cases where we do not yet support versioned source language names.
uint32_t getVersion () const
Returns language version. Only valid for versioned language names.
DISourceLanguageName (uint16_t Lang, uint32_t Version)
DISourceLanguageName (uint16_t Lang)
Detailed Description
Wrapper structure that holds a language name and its version.
Some debug-info formats, particularly DWARF, distniguish between language codes that include the version name and codes that don't. DISourceLanguageName may hold either of these.
Definition at line 75 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DISourceLanguageName() [1/2]
llvm::DISourceLanguageName::DISourceLanguageName (uint16_t Lang, uint32_t Version) inline
Definition at line 112 of file DebugInfoMetadata.h.
DISourceLanguageName() [2/2]
llvm::DISourceLanguageName::DISourceLanguageName (uint16_t Lang) inline
Definition at line 114 of file DebugInfoMetadata.h.
Member Function Documentation
getName()
uint16_t llvm::DISourceLanguageName::getName () const inline
Returns a versioned or unversioned language name.
Definition at line 94 of file DebugInfoMetadata.h.
Referenced by llvm::CodeViewDebug::beginModule(), printModuleDebugInfo(), and writeDICompileUnit().
getUnversionedName()
uint16_t llvm::DISourceLanguageName::getUnversionedName () const inline
Transitional API for cases where we do not yet support versioned source language names.
Use getName instead.
FIXME: remove once all callers of this API account for versioned names.
Definition at line 101 of file DebugInfoMetadata.h.
References assert(), and hasVersionedName().
getVersion()
uint32_t llvm::DISourceLanguageName::getVersion () const inline
Returns language version. Only valid for versioned language names.
Definition at line 107 of file DebugInfoMetadata.h.
References assert(), and hasVersionedName().
Referenced by writeDICompileUnit().
hasVersionedName()
bool llvm::DISourceLanguageName::hasVersionedName () const inline
Definition at line 91 of file DebugInfoMetadata.h.
Referenced by llvm::CodeViewDebug::beginModule(), getUnversionedName(), getVersion(), printModuleDebugInfo(), and writeDICompileUnit().
The documentation for this class was generated from the following file:
include/llvm/IR/DebugInfoMetadata.h