LLVM: llvm::AMDGPUPALMetadata Class Reference
llvm::AMDGPUPALMetadata Class Reference
#include "Target/AMDGPU/Utils/AMDGPUPALMetadata.h"
Public Types
using RegisterExprMap = DenseMap<unsigned, const MCExpr *>
Public Member Functions
void readFromIR (Module &M)
bool setFromBlob (unsigned Type, StringRef Blob)
void setRsrc1 (unsigned CC, unsigned Val)
void setRsrc1 (unsigned CC, const MCExpr *Val, MCContext &Ctx)
void setRsrc2 (unsigned CC, unsigned Val)
void setRsrc2 (unsigned CC, const MCExpr *Val, MCContext &Ctx)
void setSpiPsInputEna (unsigned Val)
void setSpiPsInputAddr (unsigned Val)
unsigned getRegister (unsigned Reg)
void setRegister (unsigned Reg, unsigned Val)
void setRegister (unsigned Reg, const MCExpr *Val, MCContext &Ctx)
void setEntryPoint (unsigned CC, StringRef Name)
void setNumUsedVgprs (unsigned CC, unsigned Val)
void setNumUsedVgprs (unsigned CC, const MCExpr *Val, MCContext &Ctx)
void setNumUsedAgprs (unsigned CC, unsigned Val)
void setNumUsedAgprs (unsigned CC, const MCExpr *Val)
void setNumUsedSgprs (unsigned CC, unsigned Val)
void setNumUsedSgprs (unsigned CC, const MCExpr *Val, MCContext &Ctx)
void setScratchSize (unsigned CC, unsigned Val)
void setScratchSize (unsigned CC, const MCExpr *Val, MCContext &Ctx)
void setFunctionScratchSize (StringRef FnName, unsigned Val)
void setFunctionLdsSize (StringRef FnName, unsigned Val)
void setFunctionNumUsedVgprs (StringRef FnName, unsigned Val)
void setFunctionNumUsedVgprs (StringRef FnName, const MCExpr *Val)
void setFunctionNumUsedSgprs (StringRef FnName, unsigned Val)
void setFunctionNumUsedSgprs (StringRef FnName, const MCExpr *Val)
void setWave32 (unsigned CC)
void toString (std::string &S)
bool setFromString (StringRef S)
const char * getVendor () const
unsigned getType () const
void toBlob (unsigned Type, std::string &S)
msgpack::Document * getMsgPackDoc ()
void setLegacy ()
unsigned getPALMajorVersion ()
unsigned getPALMinorVersion ()
VersionTuple getPALVersion ()
void updateHwStageMaximum (unsigned CC, StringRef field, unsigned Val)
void setHwStage (unsigned CC, StringRef field, unsigned Val)
void setHwStage (unsigned CC, StringRef field, bool Val)
void setHwStage (unsigned CC, StringRef field, msgpack::Type Type, const MCExpr *Val)
void setComputeRegisters (StringRef field, unsigned Val)
void setComputeRegisters (StringRef field, bool Val)
msgpack::DocNode * refComputeRegister (StringRef field)
bool checkComputeRegisters (StringRef field, unsigned Val)
bool checkComputeRegisters (StringRef field, bool Val)
void setGraphicsRegisters (StringRef field, unsigned Val)
void setGraphicsRegisters (StringRef field, bool Val)
void setGraphicsRegisters (StringRef field1, StringRef field2, unsigned Val)
void setGraphicsRegisters (StringRef field1, StringRef field2, bool Val)
void reset ()
bool resolvedAllMCExpr ()
Detailed Description
Definition at line 25 of file AMDGPUPALMetadata.h.
Member Typedef Documentation
RegisterExprMap
using llvm::AMDGPUPALMetadata::RegisterExprMap = DenseMap<unsigned, const MCExpr *>
Definition at line 27 of file AMDGPUPALMetadata.h.
Member Function Documentation
checkComputeRegisters() [1/2]
bool AMDGPUPALMetadata::checkComputeRegisters (StringRef field, bool Val)
Definition at line 1125 of file AMDGPUPALMetadata.cpp.
References N, and refComputeRegister().
checkComputeRegisters() [2/2]
bool AMDGPUPALMetadata::checkComputeRegisters (StringRef field, unsigned Val)
Definition at line 1119 of file AMDGPUPALMetadata.cpp.
References N, and refComputeRegister().
getMsgPackDoc()
msgpack::Document * llvm::AMDGPUPALMetadata::getMsgPackDoc () inline
Definition at line 150 of file AMDGPUPALMetadata.h.
getPALMajorVersion()
unsigned AMDGPUPALMetadata::getPALMajorVersion ()
Definition at line 1072 of file AMDGPUPALMetadata.cpp.
References getPALVersion().
getPALMinorVersion()
unsigned AMDGPUPALMetadata::getPALMinorVersion ()
Definition at line 1074 of file AMDGPUPALMetadata.cpp.
References getPALVersion().
getPALVersion()
VersionTuple AMDGPUPALMetadata::getPALVersion ()
Definition at line 1076 of file AMDGPUPALMetadata.cpp.
References getPALVersion().
Referenced by getPALMajorVersion(), getPALMinorVersion(), getPALVersion(), and setEntryPoint().
getRegister()
unsigned AMDGPUPALMetadata::getRegister (unsigned Reg)
Definition at line 194 of file AMDGPUPALMetadata.cpp.
References N, and llvm::msgpack::UInt.
getType()
unsigned AMDGPUPALMetadata::getType () const
Definition at line 1026 of file AMDGPUPALMetadata.cpp.
Referenced by llvm::AMDGPUTargetELFStreamer::finish().
getVendor()
const char * AMDGPUPALMetadata::getVendor () const
Definition at line 1018 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::ElfNote::NoteNameV2, and llvm::AMDGPU::ElfNote::NoteNameV3.
Referenced by llvm::AMDGPUTargetELFStreamer::finish().
readFromIR()
void AMDGPUPALMetadata::readFromIR (Module & M)
Definition at line 55 of file AMDGPUPALMetadata.cpp.
References llvm::dyn_cast(), llvm::mdconst::dyn_extract(), I, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::ELF::NT_AMD_PAL_METADATA, llvm::ELF::NT_AMDGPU_METADATA, and setRegister().
refComputeRegister()
msgpack::DocNode * AMDGPUPALMetadata::refComputeRegister (StringRef field)
Definition at line 1113 of file AMDGPUPALMetadata.cpp.
References I, and nullptr.
Referenced by checkComputeRegisters(), and checkComputeRegisters().
reset()
void AMDGPUPALMetadata::reset ()
Definition at line 1041 of file AMDGPUPALMetadata.cpp.
Referenced by llvm::AMDGPUTargetAsmStreamer::finish(), and llvm::AMDGPUTargetELFStreamer::finish().
resolvedAllMCExpr()
bool AMDGPUPALMetadata::resolvedAllMCExpr ()
Definition at line 1050 of file AMDGPUPALMetadata.cpp.
setComputeRegisters() [1/2]
void AMDGPUPALMetadata::setComputeRegisters (StringRef field, bool Val)
Definition at line 1109 of file AMDGPUPALMetadata.cpp.
setComputeRegisters() [2/2]
void AMDGPUPALMetadata::setComputeRegisters (StringRef field, unsigned Val)
Definition at line 1105 of file AMDGPUPALMetadata.cpp.
Referenced by EmitPALMetadataCommon().
setEntryPoint()
void AMDGPUPALMetadata::setEntryPoint (unsigned CC, StringRef Name)
Definition at line 255 of file AMDGPUPALMetadata.cpp.
References getPALVersion(), getStageName(), and llvm::raw_svector_ostream::str().
setFromBlob()
bool AMDGPUPALMetadata::setFromBlob (unsigned Type, StringRef Blob)
Definition at line 94 of file AMDGPUPALMetadata.cpp.
References llvm::ELF::NT_AMD_PAL_METADATA.
setFromString()
bool AMDGPUPALMetadata::setFromString (StringRef S)
Definition at line 895 of file AMDGPUPALMetadata.cpp.
References llvm::StringRef::consumeInteger(), llvm::errs(), I, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::ELF::NT_AMDGPU_METADATA, and llvm::msgpack::String.
setFunctionLdsSize()
void AMDGPUPALMetadata::setFunctionLdsSize (StringRef FnName, unsigned Val)
Definition at line 376 of file AMDGPUPALMetadata.cpp.
setFunctionNumUsedSgprs() [1/2]
void AMDGPUPALMetadata::setFunctionNumUsedSgprs (StringRef FnName, const MCExpr * Val)
Definition at line 401 of file AMDGPUPALMetadata.cpp.
References llvm::msgpack::UInt.
setFunctionNumUsedSgprs() [2/2]
void AMDGPUPALMetadata::setFunctionNumUsedSgprs (StringRef FnName, unsigned Val)
Definition at line 395 of file AMDGPUPALMetadata.cpp.
setFunctionNumUsedVgprs() [1/2]
void AMDGPUPALMetadata::setFunctionNumUsedVgprs (StringRef FnName, const MCExpr * Val)
Definition at line 388 of file AMDGPUPALMetadata.cpp.
References llvm::msgpack::UInt.
setFunctionNumUsedVgprs() [2/2]
void AMDGPUPALMetadata::setFunctionNumUsedVgprs (StringRef FnName, unsigned Val)
Definition at line 382 of file AMDGPUPALMetadata.cpp.
setFunctionScratchSize()
void AMDGPUPALMetadata::setFunctionScratchSize (StringRef FnName, unsigned Val)
Definition at line 369 of file AMDGPUPALMetadata.cpp.
setGraphicsRegisters() [1/4]
void AMDGPUPALMetadata::setGraphicsRegisters (StringRef field, bool Val)
Definition at line 1135 of file AMDGPUPALMetadata.cpp.
setGraphicsRegisters() [2/4]
void AMDGPUPALMetadata::setGraphicsRegisters (StringRef field, unsigned Val)
Definition at line 1131 of file AMDGPUPALMetadata.cpp.
setGraphicsRegisters() [3/4]
void AMDGPUPALMetadata::setGraphicsRegisters (StringRef field1, StringRef field2, bool Val)
Definition at line 1144 of file AMDGPUPALMetadata.cpp.
setGraphicsRegisters() [4/4]
void AMDGPUPALMetadata::setGraphicsRegisters (StringRef field1, StringRef field2, unsigned Val)
Definition at line 1139 of file AMDGPUPALMetadata.cpp.
setHwStage() [1/3]
void AMDGPUPALMetadata::setHwStage (unsigned CC, StringRef field, bool Val)
Definition at line 1096 of file AMDGPUPALMetadata.cpp.
setHwStage() [2/3]
void AMDGPUPALMetadata::setHwStage (unsigned CC, StringRef field, msgpack::Type Type, const MCExpr * Val)
Definition at line 1100 of file AMDGPUPALMetadata.cpp.
setHwStage() [3/3]
void AMDGPUPALMetadata::setHwStage (unsigned CC, StringRef field, unsigned Val)
Definition at line 1092 of file AMDGPUPALMetadata.cpp.
Referenced by EmitPALMetadataCommon(), setNumUsedAgprs(), setNumUsedSgprs(), setNumUsedVgprs(), and setScratchSize().
setLegacy()
void AMDGPUPALMetadata::setLegacy ()
Definition at line 1036 of file AMDGPUPALMetadata.cpp.
References llvm::ELF::NT_AMD_PAL_METADATA.
setNumUsedAgprs() [1/2]
void AMDGPUPALMetadata::setNumUsedAgprs (unsigned CC, const MCExpr * Val)
Definition at line 312 of file AMDGPUPALMetadata.cpp.
References setHwStage(), and llvm::msgpack::UInt.
setNumUsedAgprs() [2/2]
void AMDGPUPALMetadata::setNumUsedAgprs (unsigned CC, unsigned Val)
Definition at line 308 of file AMDGPUPALMetadata.cpp.
setNumUsedSgprs() [1/2]
void AMDGPUPALMetadata::setNumUsedSgprs (unsigned CC, const MCExpr * Val, MCContext & Ctx)
Definition at line 332 of file AMDGPUPALMetadata.cpp.
References getScratchSizeKey(), setHwStage(), setRegister(), llvm::msgpack::UInt, llvm::AMDGPU::PALMD::VS_NUM_USED_SGPRS, and llvm::AMDGPU::PALMD::VS_SCRATCH_SIZE.
setNumUsedSgprs() [2/2]
void AMDGPUPALMetadata::setNumUsedSgprs (unsigned CC, unsigned Val)
Definition at line 319 of file AMDGPUPALMetadata.cpp.
References getScratchSizeKey(), setRegister(), llvm::AMDGPU::PALMD::VS_NUM_USED_SGPRS, and llvm::AMDGPU::PALMD::VS_SCRATCH_SIZE.
setNumUsedVgprs() [1/2]
void AMDGPUPALMetadata::setNumUsedVgprs (unsigned CC, const MCExpr * Val, MCContext & Ctx)
Definition at line 293 of file AMDGPUPALMetadata.cpp.
References getScratchSizeKey(), setHwStage(), setRegister(), llvm::msgpack::UInt, llvm::AMDGPU::PALMD::VS_NUM_USED_VGPRS, and llvm::AMDGPU::PALMD::VS_SCRATCH_SIZE.
setNumUsedVgprs() [2/2]
void AMDGPUPALMetadata::setNumUsedVgprs (unsigned CC, unsigned Val)
Definition at line 280 of file AMDGPUPALMetadata.cpp.
References getScratchSizeKey(), setRegister(), llvm::AMDGPU::PALMD::VS_NUM_USED_VGPRS, and llvm::AMDGPU::PALMD::VS_SCRATCH_SIZE.
setRegister() [1/2]
void AMDGPUPALMetadata::setRegister (unsigned Reg, const MCExpr * Val, MCContext & Ctx)
Definition at line 222 of file AMDGPUPALMetadata.cpp.
References llvm::MCConstantExpr::create(), llvm::MCBinaryExpr::createOr(), N, and llvm::msgpack::UInt.
setRegister() [2/2]
void AMDGPUPALMetadata::setRegister (unsigned Reg, unsigned Val)
Definition at line 207 of file AMDGPUPALMetadata.cpp.
References N, and llvm::msgpack::UInt.
Referenced by readFromIR(), setNumUsedSgprs(), setNumUsedSgprs(), setNumUsedVgprs(), setNumUsedVgprs(), setRsrc1(), setRsrc1(), setRsrc2(), setRsrc2(), setScratchSize(), setScratchSize(), setSpiPsInputAddr(), setSpiPsInputEna(), and setWave32().
setRsrc1() [1/2]
void AMDGPUPALMetadata::setRsrc1 (unsigned CC, const MCExpr * Val, MCContext & Ctx)
Definition at line 165 of file AMDGPUPALMetadata.cpp.
References getRsrc1Reg(), and setRegister().
setRsrc1() [2/2]
void AMDGPUPALMetadata::setRsrc1 (unsigned CC, unsigned Val)
Definition at line 161 of file AMDGPUPALMetadata.cpp.
References getRsrc1Reg(), and setRegister().
setRsrc2() [1/2]
void AMDGPUPALMetadata::setRsrc2 (unsigned CC, const MCExpr * Val, MCContext & Ctx)
Definition at line 176 of file AMDGPUPALMetadata.cpp.
References getRsrc1Reg(), and setRegister().
setRsrc2() [2/2]
void AMDGPUPALMetadata::setRsrc2 (unsigned CC, unsigned Val)
Definition at line 172 of file AMDGPUPALMetadata.cpp.
References getRsrc1Reg(), and setRegister().
setScratchSize() [1/2]
void AMDGPUPALMetadata::setScratchSize (unsigned CC, const MCExpr * Val, MCContext & Ctx)
Definition at line 357 of file AMDGPUPALMetadata.cpp.
References getScratchSizeKey(), setHwStage(), setRegister(), and llvm::msgpack::UInt.
setScratchSize() [2/2]
void AMDGPUPALMetadata::setScratchSize (unsigned CC, unsigned Val)
Definition at line 347 of file AMDGPUPALMetadata.cpp.
References getScratchSizeKey(), and setRegister().
setSpiPsInputAddr()
void AMDGPUPALMetadata::setSpiPsInputAddr (unsigned Val)
Definition at line 189 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::PALMD::R_A1B4_SPI_PS_INPUT_ADDR, and setRegister().
setSpiPsInputEna()
void AMDGPUPALMetadata::setSpiPsInputEna (unsigned Val)
Definition at line 183 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::PALMD::R_A1B3_SPI_PS_INPUT_ENA, and setRegister().
setWave32()
void AMDGPUPALMetadata::setWave32 (unsigned CC)
Definition at line 409 of file AMDGPUPALMetadata.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, llvm::AMDGPU::PALMD::R_2E00_COMPUTE_DISPATCH_INITIATOR, llvm::AMDGPU::PALMD::R_A1B6_SPI_PS_IN_CONTROL, llvm::AMDGPU::PALMD::R_A2D5_VGT_SHADER_STAGES_EN, S_00B800_CS_W32_EN, S_0286D8_PS_W32_EN, S_028B54_GS_W32_EN, S_028B54_HS_W32_EN, S_028B54_VS_W32_EN, and setRegister().
toBlob()
void AMDGPUPALMetadata::toBlob (unsigned Type, std::string & S)
Definition at line 868 of file AMDGPUPALMetadata.cpp.
References llvm::ELF::NT_AMD_PAL_METADATA.
Referenced by llvm::AMDGPUTargetELFStreamer::finish().
toString()
void AMDGPUPALMetadata::toString (std::string & S)
Definition at line 815 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::PALMD::AssemblerDirective, llvm::AMDGPU::PALMD::AssemblerDirectiveBegin, llvm::AMDGPU::PALMD::AssemblerDirectiveEnd, getRegisterName(), I, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::msgpack::Nil, RegName, llvm::String, and llvm::Twine::utohexstr().
Referenced by llvm::AMDGPUTargetAsmStreamer::finish().
updateHwStageMaximum()
void AMDGPUPALMetadata::updateHwStageMaximum (unsigned CC, StringRef field, unsigned Val)
Definition at line 1081 of file AMDGPUPALMetadata.cpp.
Referenced by EmitPALMetadataCommon().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUPALMetadata.h
lib/Target/AMDGPU/Utils/AMDGPUPALMetadata.cpp