LLVM: llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT > Class Template Reference
llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT > Class Template Reference
Provides API functions, like getIterator() and getReverseIterator() to GlobalIFunc, Function, GlobalVariable and GlobalAlias.
#include "llvm/SandboxIR/Constant.h"
Public Types
using iterator
using reverse_iterator
Public Member Functions
GlobalWithNodeAPI (Value::ClassID ID, LLVMParentT *C, Context &Ctx)
Module * getParent () const
iterator getIterator () const
reverse_iterator getReverseIterator () const
Detailed Description
template<typename GlobalT, typename LLVMGlobalT, typename ParentT, typename LLVMParentT>
class llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT >
Provides API functions, like getIterator() and getReverseIterator() to GlobalIFunc, Function, GlobalVariable and GlobalAlias.
In LLVM IR these are provided by ilist_node.
Definition at line 1031 of file Constant.h.
Member Typedef Documentation
iterator
template<typename GlobalT, typename LLVMGlobalT, typename ParentT, typename LLVMParentT> using llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT >::iterator
Initial value:
mapped_iterator<
     decltype(static_cast<LLVMGlobalT *>(nullptr)->getIterator()), LLVMGVToGV>
Definition at line 1048 of file Constant.h.
reverse_iterator
template<typename GlobalT, typename LLVMGlobalT, typename ParentT, typename LLVMParentT> using llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT >::reverse_iterator
Initial value:
mapped_iterator<
     decltype(static_cast<LLVMGlobalT *>(nullptr)->getReverseIterator()),
     LLVMGVToGV>
Definition at line 1050 of file Constant.h.
Constructor & Destructor Documentation
GlobalWithNodeAPI()
template<typename GlobalT, typename LLVMGlobalT, typename ParentT, typename LLVMParentT> llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT >::GlobalWithNodeAPI (Value::ClassID ID, LLVMParentT * C, Context & Ctx) inline
Definition at line 1040 of file Constant.h.
References llvm::CallingConv::C.
Member Function Documentation
getIterator()
template<typename GlobalT, typename LLVMGlobalT, typename ParentT, typename LLVMParentT> iterator llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT >::getIterator () const inline
Definition at line 1053 of file Constant.h.
References llvm::cast(), and llvm::map_iterator().
getParent()
template<typename GlobalT, typename LLVMGlobalT, typename ParentT, typename LLVMParentT> Module * llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT >::getParent () const inline
Definition at line 1043 of file Constant.h.
References llvm::cast().
getReverseIterator()
template<typename GlobalT, typename LLVMGlobalT, typename ParentT, typename LLVMParentT> reverse_iterator llvm::sandboxir::GlobalWithNodeAPI< GlobalT, LLVMGlobalT, ParentT, LLVMParentT >::getReverseIterator () const inline
Definition at line 1058 of file Constant.h.
References llvm::cast(), and llvm::map_iterator().
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Constant.h