LLVM: llvm::InstCombinerImpl Class Reference
llvm::InstCombinerImpl Class Reference final
#include "Transforms/InstCombine/InstCombineInternal.h"
Public Member Functions
InstCombinerImpl (InstructionWorklist &Worklist, BuilderTy &Builder, Function &F, AAResults *AA, AssumptionCache &AC, TargetLibraryInfo &TLI, TargetTransformInfo &TTI, DominatorTree &DT, OptimizationRemarkEmitter &ORE, BlockFrequencyInfo *BFI, BranchProbabilityInfo *BPI, ProfileSummaryInfo *PSI, const DataLayout &DL, ReversePostOrderTraversal< BasicBlock * > &RPOT)
~InstCombinerImpl () override=default
bool prepareWorklist (Function &F)
Perform early cleanup and prepare the InstCombine worklist.
bool run ()
Run the combiner over the entire worklist until it is empty.
Instruction * visitFNeg (UnaryOperator &I)
Instruction * visitAdd (BinaryOperator &I)
Instruction * visitFAdd (BinaryOperator &I)
Value * OptimizePointerDifference (Value *LHS, Value *RHS, Type *Ty, bool isNUW)
Optimize pointer differences into the same array into a size.
Instruction * visitSub (BinaryOperator &I)
Instruction * visitFSub (BinaryOperator &I)
Instruction * visitMul (BinaryOperator &I)
Instruction * foldPowiReassoc (BinaryOperator &I)
Instruction * foldFMulReassoc (BinaryOperator &I)
Instruction * visitFMul (BinaryOperator &I)
Instruction * visitURem (BinaryOperator &I)
Instruction * visitSRem (BinaryOperator &I)
Instruction * visitFRem (BinaryOperator &I)
bool simplifyDivRemOfSelectWithZeroOp (BinaryOperator &I)
Fold a divide or remainder with a select instruction divisor when one of the select operands is zero.
Instruction * commonIDivRemTransforms (BinaryOperator &I)
Common integer divide/remainder transforms.
Instruction * commonIRemTransforms (BinaryOperator &I)
This function implements the transforms common to both integer remainder instructions (urem and srem).
Instruction * commonIDivTransforms (BinaryOperator &I)
This function implements the transforms common to both integer division instructions (udiv and sdiv).
Instruction * visitUDiv (BinaryOperator &I)
Instruction * visitSDiv (BinaryOperator &I)
Instruction * visitFDiv (BinaryOperator &I)
Value * simplifyRangeCheck (ICmpInst *Cmp0, ICmpInst *Cmp1, bool Inverted)
Try to fold a signed range checked with lower bound 0 to an unsigned icmp.
Instruction * visitAnd (BinaryOperator &I)
Instruction * visitOr (BinaryOperator &I)
bool sinkNotIntoLogicalOp (Instruction &I)
bool sinkNotIntoOtherHandOfLogicalOp (Instruction &I)
Instruction * visitXor (BinaryOperator &I)
Instruction * visitShl (BinaryOperator &I)
Value * reassociateShiftAmtsOfTwoSameDirectionShifts (BinaryOperator *Sh0, const SimplifyQuery &SQ, bool AnalyzeForSignBitExtraction=false)
Instruction * canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract (BinaryOperator &I)
Instruction * foldVariableSignZeroExtensionOfVariableHighBitExtract (BinaryOperator &OldAShr)
Instruction * visitAShr (BinaryOperator &I)
Instruction * visitLShr (BinaryOperator &I)
Instruction * commonShiftTransforms (BinaryOperator &I)
Instruction * visitFCmpInst (FCmpInst &I)
CmpInst * canonicalizeICmpPredicate (CmpInst &I)
If we have a comparison with a non-canonical predicate, if we can update all the users, invert the predicate and adjust all the users.
Instruction * visitICmpInst (ICmpInst &I)
Instruction * FoldShiftByConstant (Value *Op0, Constant *Op1, BinaryOperator &I)
Instruction * commonCastTransforms (CastInst &CI)
Implement the transforms common to all CastInst visitors.
Instruction * visitTrunc (TruncInst &CI)
Instruction * visitZExt (ZExtInst &Zext)
Instruction * visitSExt (SExtInst &Sext)
Instruction * visitFPTrunc (FPTruncInst &CI)
Instruction * visitFPExt (CastInst &CI)
Instruction * visitFPToUI (FPToUIInst &FI)
Instruction * visitFPToSI (FPToSIInst &FI)
Instruction * visitUIToFP (CastInst &CI)
Instruction * visitSIToFP (CastInst &CI)
Instruction * visitPtrToInt (PtrToIntInst &CI)
Instruction * visitPtrToAddr (PtrToAddrInst &CI)
Instruction * visitIntToPtr (IntToPtrInst &CI)
Instruction * visitBitCast (BitCastInst &CI)
Instruction * visitAddrSpaceCast (AddrSpaceCastInst &CI)
Instruction * foldItoFPtoI (CastInst &FI)
fpto{s/u}i({u/s}itofp(X)) --> X or zext(X) or sext(X) or trunc(X) This is safe if the intermediate type has enough bits in its mantissa to accurately represent all values of X.
Instruction * visitSelectInst (SelectInst &SI)
Instruction * foldShuffledIntrinsicOperands (IntrinsicInst *II)
If all arguments of the intrinsic are unary shuffles with the same mask, try to shuffle after the intrinsic.
Value * foldReversedIntrinsicOperands (IntrinsicInst *II)
If all arguments of the intrinsic are reverses, try to pull the reverse after the intrinsic.
Instruction * visitCallInst (CallInst &CI)
CallInst simplification.
Instruction * visitInvokeInst (InvokeInst &II)
Instruction * visitCallBrInst (CallBrInst &CBI)
Instruction * SliceUpIllegalIntegerPHI (PHINode &PN)
This is an integer PHI and we know that it has an illegal type: see if it is only used by trunc or trunc(lshr) operations.
Instruction * visitPHINode (PHINode &PN)
Instruction * visitGetElementPtrInst (GetElementPtrInst &GEP)
Instruction * visitGEPOfGEP (GetElementPtrInst &GEP, GEPOperator *Src)
Instruction * visitAllocaInst (AllocaInst &AI)
Instruction * visitAllocSite (Instruction &FI)
Instruction * visitFree (CallInst &FI, Value *FreedOp)
Instruction * visitLoadInst (LoadInst &LI)
Instruction * visitStoreInst (StoreInst &SI)
Instruction * visitAtomicRMWInst (AtomicRMWInst &SI)
Instruction * visitUnconditionalBranchInst (BranchInst &BI)
Instruction * visitBranchInst (BranchInst &BI)
Instruction * visitFenceInst (FenceInst &FI)
Instruction * visitSwitchInst (SwitchInst &SI)
Instruction * visitReturnInst (ReturnInst &RI)
Instruction * visitUnreachableInst (UnreachableInst &I)
Instruction * foldAggregateConstructionIntoAggregateReuse (InsertValueInst &OrigIVI)
Look for chain of insertvalue's that fully define an aggregate, and trace back the values inserted, see if they are all were extractvalue'd from the same source aggregate from the exact same element indexes.
Instruction * visitInsertValueInst (InsertValueInst &IV)
Try to find redundant insertvalue instructions, like the following ones: %0 = insertvalue { i8, i32 } undef, i8 x, 0 %1 = insertvalue { i8, i32 } %0, i8 y, 0 Here the second instruction inserts values at the same indices, as the first one, making the first one redundant.
Instruction * visitInsertElementInst (InsertElementInst &IE)
Instruction * visitExtractElementInst (ExtractElementInst &EI)
Instruction * simplifyBinOpSplats (ShuffleVectorInst &SVI)
Instruction * visitShuffleVectorInst (ShuffleVectorInst &SVI)
Instruction * visitExtractValueInst (ExtractValueInst &EV)
Instruction * visitLandingPadInst (LandingPadInst &LI)
Instruction * visitVAEndInst (VAEndInst &I)
Value * pushFreezeToPreventPoisonFromPropagating (FreezeInst &FI)
bool freezeOtherUses (FreezeInst &FI)
Instruction * foldFreezeIntoRecurrence (FreezeInst &I, PHINode *PN)
Instruction * visitFreeze (FreezeInst &I)
Instruction * visitInstruction (Instruction &I)
Specify what to return for unhandled instructions.
bool dominatesAllUses (const Instruction *DI, const Instruction *UI, const BasicBlock *DB) const
True when DB dominates all uses of DI except UI.
bool replacedSelectWithOperand (SelectInst *SI, const ICmpInst *Icmp, const unsigned SIOpd)
Try to replace select with select operand SIOpd in SI-ICmp sequence.
LoadInst * combineLoadToNewType (LoadInst &LI, Type *NewTy, const Twine &Suffix="")
Helper to combine a load to a new type.
KnownFPClass computeKnownFPClass (Value *Val, FastMathFlags FMF, FPClassTest Interested=fcAllFlags, const Instruction *CtxI=nullptr, unsigned Depth=0) const
KnownFPClass computeKnownFPClass (Value *Val, FPClassTest Interested=fcAllFlags, const Instruction *CtxI=nullptr, unsigned Depth=0) const
bool fmulByZeroIsZero (Value *MulVal, FastMathFlags FMF, const Instruction *CtxI) const
Check if fmul MulVal, +0.0 will yield +0.0 (or signed zero is ignorable).
std::optional< std::pair< Intrinsic::ID, SmallVector< Value *, 3 > > > convertOrOfShiftsToFunnelShift (Instruction &Or)
void CreateNonTerminatorUnreachable (Instruction *InsertAt)
Create and insert the idiom we use to indicate a block is unreachable without having to rewrite the CFG from within InstCombine.
Instruction * eraseInstFromFunction (Instruction &I) override
Combiner aware instruction erasure.
OverflowResult computeOverflow (Instruction::BinaryOps BinaryOp, bool IsSigned, Value *LHS, Value *RHS, Instruction *CxtI) const
bool SimplifyAssociativeOrCommutative (BinaryOperator &I)
Performs a few simplifications for operators which are associative or commutative.
Value * foldUsingDistributiveLaws (BinaryOperator &I)
Tries to simplify binary operations which some other binary operation distributes over.
Value * SimplifyAddWithRemainder (BinaryOperator &I)
Tries to simplify add operations using the definition of remainder.
Value * SimplifySelectsFeedingBinaryOp (BinaryOperator &I, Value *LHS, Value *RHS)
Instruction * tryFoldInstWithCtpopWithNot (Instruction *I)
Instruction * foldBinOpShiftWithShift (BinaryOperator &I)
Instruction * foldBinOpOfSelectAndCastOfSelectCondition (BinaryOperator &I)
Tries to simplify binops of select and cast of the select condition.
Value * tryFactorizationFolds (BinaryOperator &I)
This tries to simplify binary operations by factorizing out common terms (e.
bool matchThreeWayIntCompare (SelectInst *SI, Value *&LHS, Value *&RHS, ConstantInt *&Less, ConstantInt *&Equal, ConstantInt *&Greater)
Match a select chain which produces one of three values based on whether the LHS is less than, equal to, or greater than RHS respectively.
Value * SimplifyDemandedUseBits (Instruction *I, const APInt &DemandedMask, KnownBits &Known, const SimplifyQuery &Q, unsigned Depth=0)
Attempts to replace I with a simpler value based on the demanded bits.
bool SimplifyDemandedBits (Instruction *I, unsigned Op, const APInt &DemandedMask, KnownBits &Known, const SimplifyQuery &Q, unsigned Depth=0) override
This form of SimplifyDemandedBits simplifies the specified instruction operand if possible, updating it in place.
Value * SimplifyMultipleUseDemandedBits (Instruction *I, const APInt &DemandedMask, KnownBits &Known, const SimplifyQuery &Q, unsigned Depth=0)
Helper routine of SimplifyDemandedUseBits.
Value * simplifyShrShlDemandedBits (Instruction *Shr, const APInt &ShrOp1, Instruction *Shl, const APInt &ShlOp1, const APInt &DemandedMask, KnownBits &Known)
Helper routine of SimplifyDemandedUseBits.
bool SimplifyDemandedInstructionBits (Instruction &Inst)
Tries to simplify operands to an integer instruction based on its demanded bits.
bool SimplifyDemandedInstructionBits (Instruction &Inst, KnownBits &Known)
Inst is an integer instruction that SimplifyDemandedBits knows about.
Value * SimplifyDemandedVectorElts (Value *V, APInt DemandedElts, APInt &PoisonElts, unsigned Depth=0, bool AllowMultipleUsers=false) override
The specified value produces a vector with any number of elements.
Value * SimplifyDemandedUseFPClass (Instruction *I, FPClassTest DemandedMask, KnownFPClass &Known, Instruction *CxtI, unsigned Depth=0)
Attempts to replace V with a simpler value based on the demanded floating-point classes.
Value * SimplifyMultipleUseDemandedFPClass (Instruction *I, FPClassTest DemandedMask, KnownFPClass &Known, Instruction *CxtI, unsigned Depth)
Helper routine of SimplifyDemandedUseFPClass.
bool SimplifyDemandedFPClass (Instruction *I, unsigned Op, FPClassTest DemandedMask, KnownFPClass &Known, unsigned Depth=0)
Instruction * foldAddLikeCommutative (Value *LHS, Value *RHS, bool NSW, bool NUW)
Common transforms for add / disjoint or.
Instruction * foldVectorBinop (BinaryOperator &Inst)
Canonicalize the position of binops relative to shufflevector.
Instruction * foldVectorSelect (SelectInst &Sel)
Instruction * foldSelectShuffle (ShuffleVectorInst &Shuf)
Try to fold shuffles that are the equivalent of a vector select.
Constant * unshuffleConstant (ArrayRef< int > ShMask, Constant *C, VectorType *NewCTy)
Find a constant NewC that has property: shuffle(NewC, ShMask) = C Returns nullptr if such a constant does not exist e.g.
Instruction * foldOpIntoPhi (Instruction &I, PHINode *PN, bool AllowMultipleUses=false)
Given a binary operator, cast instruction, or select which has a PHI node as operand #0, see if we can fold the instruction into the PHI (which is only possible if all operands to the PHI are constants).
Instruction * foldBinopWithRecurrence (BinaryOperator &BO)
Try to fold binary operators whose operands are simple interleaved recurrences to a single recurrence.
Instruction * foldBinopWithPhiOperands (BinaryOperator &BO)
For a binary operator with 2 phi operands, try to hoist the binary operation before the phi.
Instruction * FoldOpIntoSelect (Instruction &Op, SelectInst *SI, bool FoldWithMultiUse=false, bool SimplifyBothArms=false)
Given an instruction with a select as one operand and a constant as the other operand, try to fold the binary operator into the select arguments.
Instruction * foldBinOpSelectBinOp (BinaryOperator &Op)
In some cases it is beneficial to fold a select into a binary operator.
Instruction * foldBinOpIntoSelectOrPhi (BinaryOperator &I)
This is a convenience wrapper function for the above two functions.
Instruction * foldAddWithConstant (BinaryOperator &Add)
Instruction * foldSquareSumInt (BinaryOperator &I)
Instruction * foldSquareSumFP (BinaryOperator &I)
Instruction * foldPHIArgOpIntoPHI (PHINode &PN)
Try to rotate an operation below a PHI node, using PHI nodes for its operands.
Instruction * foldPHIArgBinOpIntoPHI (PHINode &PN)
If we have something like phi [add (a,b), add(a,c)] and if a/b/c and the adds all have a single user, turn this into a phi and a single binop.
Instruction * foldPHIArgInsertValueInstructionIntoPHI (PHINode &PN)
If we have something like phi [insertvalue(a,b,0), insertvalue(c,d,0)], turn this into a phi[a,c] and phi[b,d] and a single insertvalue.
Instruction * foldPHIArgExtractValueInstructionIntoPHI (PHINode &PN)
If we have something like phi [extractvalue(a,0), extractvalue(b,0)], turn this into a phi[a,b] and a single extractvalue.
Instruction * foldPHIArgGEPIntoPHI (PHINode &PN)
Instruction * foldPHIArgLoadIntoPHI (PHINode &PN)
Instruction * foldPHIArgZextsIntoPHI (PHINode &PN)
TODO: This function could handle other cast types, but then it might require special-casing a cast from the 'i1' type.
Instruction * foldPHIArgIntToPtrToPHI (PHINode &PN)
bool foldDeadPhiWeb (PHINode &PN)
If the phi is within a phi web, which is formed by the def-use chain of phis and all the phis in the web are only used in the other phis.
bool foldIntegerTypedPHI (PHINode &PN)
If an integer typed PHI has only one use which is an IntToPtr operation, replace the PHI with an existing pointer typed PHI if it exists.
void PHIArgMergedDebugLoc (Instruction *Inst, PHINode &PN)
Helper function for FoldPHIArgXIntoPHI() to set debug location for the folded operation.
Value * foldPtrToIntOrAddrOfGEP (Type *IntTy, Value *Ptr)
Instruction * foldGEPICmp (GEPOperator *GEPLHS, Value *RHS, CmpPredicate Cond, Instruction &I)
Fold comparisons between a GEP instruction and something else.
Instruction * foldSelectICmp (CmpPredicate Pred, SelectInst *SI, Value *RHS, const ICmpInst &I)
bool foldAllocaCmp (AllocaInst *Alloca)
Instruction * foldCmpLoadFromIndexedGlobal (LoadInst *LI, GetElementPtrInst *GEP, CmpInst &ICI, ConstantInt *AndCst=nullptr)
This is called when we see this pattern: cmp pred (load (gep GV, ...)), cmpcst where GV is a global variable with a constant initializer.
Instruction * foldFCmpIntToFPConst (FCmpInst &I, Instruction *LHSI, Constant *RHSC)
Fold fcmp ([us]itofp x, cst) if possible.
Instruction * foldICmpAddOpConst (Value *X, const APInt &C, CmpPredicate Pred)
Fold "icmp pred (X+C), X".
Instruction * foldICmpWithCastOp (ICmpInst &ICmp)
Handle icmp (cast x), (cast or constant).
Instruction * foldICmpWithZextOrSext (ICmpInst &ICmp)
Instruction * foldICmpUsingKnownBits (ICmpInst &Cmp)
Try to fold the comparison based on range information we can get by checking whether bits are known to be zero or one in the inputs.
Instruction * foldICmpWithDominatingICmp (ICmpInst &Cmp)
Canonicalize icmp instructions based on dominating conditions.
Instruction * foldICmpWithConstant (ICmpInst &Cmp)
Fold icmp Pred X, C.
Instruction * foldIsMultipleOfAPowerOfTwo (ICmpInst &Cmp)
Fold icmp eq (num + mask) & ~mask, num to icmp eq (and num, mask), 0 Where mask is a low bit mask.
Instruction * foldICmpUsingBoolRange (ICmpInst &I)
If one operand of an icmp is effectively a bool (value range of {0,1}), then try to reduce patterns based on that limit.
Instruction * foldICmpInstWithConstant (ICmpInst &Cmp)
Try to fold integer comparisons with a constant operand: icmp Pred X, C where X is some kind of instruction.
Instruction * foldICmpInstWithConstantNotInt (ICmpInst &Cmp)
Handle icmp with constant (but not simple integer constant) RHS.
Instruction * foldICmpInstWithConstantAllowPoison (ICmpInst &Cmp, const APInt &C)
Try to fold integer comparisons with a constant operand: icmp Pred X, C where X is some kind of instruction and C is AllowPoison.
Instruction * foldICmpBinOp (ICmpInst &Cmp, const SimplifyQuery &SQ)
Try to fold icmp (binop), X or icmp X, (binop).
Instruction * foldICmpWithMinMax (Instruction &I, MinMaxIntrinsic *MinMax, Value *Z, CmpPredicate Pred)
Fold icmp Pred min|max(X, Y), Z.
Instruction * foldICmpWithClamp (ICmpInst &Cmp, Value *X, MinMaxIntrinsic *Min)
Match and fold patterns like: icmp eq/ne X, min(max(X, Lo), Hi) which represents a range check and can be repsented as a ConstantRange.
Instruction * foldICmpEquality (ICmpInst &Cmp)
Instruction * foldIRemByPowerOfTwoToBitTest (ICmpInst &I)
If we have: icmp eq/ne (urem/srem x, y), 0 iff y is a power-of-two, we can replace this with a bit test: icmp eq/ne (and x, (add y, -1)), 0.
Instruction * foldSignBitTest (ICmpInst &I)
Fold equality-comparison between zero and any (maybe truncated) right-shift by one-less-than-bitwidth into a sign test on the original value.
Instruction * foldICmpWithZero (ICmpInst &Cmp)
Value * foldMultiplicationOverflowCheck (ICmpInst &Cmp)
Fold (-1 u/ x) u< y ((x * y) ?
Instruction * foldICmpBinOpWithConstant (ICmpInst &Cmp, BinaryOperator *BO, const APInt &C)
Fold an icmp with BinaryOp and constant operand: icmp Pred BO, C.
Instruction * foldICmpSelectConstant (ICmpInst &Cmp, SelectInst *Select, ConstantInt *C)
Instruction * foldICmpTruncConstant (ICmpInst &Cmp, TruncInst *Trunc, const APInt &C)
Fold icmp (trunc X), C.
Instruction * foldICmpTruncWithTruncOrExt (ICmpInst &Cmp, const SimplifyQuery &Q)
Fold icmp (trunc nuw/nsw X), (trunc nuw/nsw Y).
Instruction * foldICmpAndConstant (ICmpInst &Cmp, BinaryOperator *And, const APInt &C)
Fold icmp (and X, Y), C.
Instruction * foldICmpXorConstant (ICmpInst &Cmp, BinaryOperator *Xor, const APInt &C)
Fold icmp (xor X, Y), C.
Instruction * foldICmpOrConstant (ICmpInst &Cmp, BinaryOperator *Or, const APInt &C)
Fold icmp (or X, Y), C.
Instruction * foldICmpMulConstant (ICmpInst &Cmp, BinaryOperator *Mul, const APInt &C)
Fold icmp (mul X, Y), C.
Instruction * foldICmpShlConstant (ICmpInst &Cmp, BinaryOperator *Shl, const APInt &C)
Fold icmp (shl X, Y), C.
Instruction * foldICmpShrConstant (ICmpInst &Cmp, BinaryOperator *Shr, const APInt &C)
Fold icmp ({al}shr X, Y), C.
Instruction * foldICmpSRemConstant (ICmpInst &Cmp, BinaryOperator *UDiv, const APInt &C)
Instruction * foldICmpUDivConstant (ICmpInst &Cmp, BinaryOperator *UDiv, const APInt &C)
Fold icmp (udiv X, Y), C.
Instruction * foldICmpDivConstant (ICmpInst &Cmp, BinaryOperator *Div, const APInt &C)
Fold icmp ({su}div X, Y), C.
Instruction * foldICmpSubConstant (ICmpInst &Cmp, BinaryOperator *Sub, const APInt &C)
Fold icmp (sub X, Y), C.
Instruction * foldICmpAddConstant (ICmpInst &Cmp, BinaryOperator *Add, const APInt &C)
Fold icmp (add X, Y), C.
Instruction * foldICmpAndConstConst (ICmpInst &Cmp, BinaryOperator *And, const APInt &C1)
Fold icmp (and X, C2), C1.
Instruction * foldICmpAndShift (ICmpInst &Cmp, BinaryOperator *And, const APInt &C1, const APInt &C2)
Fold icmp (and (sh X, Y), C2), C1.
Instruction * foldICmpXorShiftConst (ICmpInst &Cmp, BinaryOperator *Xor, const APInt &C)
For power-of-2 C: ((X s>> ShiftC) ^ X) u< C --> (X + C) u< (C << 1) ((X s>> ShiftC) ^ X) u> (C - 1) --> (X + C) u> ((C << 1) - 1).
Instruction * foldICmpShrConstConst (ICmpInst &I, Value *ShAmt, const APInt &C1, const APInt &C2)
Handle "(icmp eq/ne (ashr/lshr AP2, A), AP1)" -> (icmp eq/ne A, Log2(AP2/AP1)) -> (icmp eq/ne A, Log2(AP2) - Log2(AP1)).
Instruction * foldICmpShlConstConst (ICmpInst &I, Value *ShAmt, const APInt &C1, const APInt &C2)
Handle "(icmp eq/ne (shl AP2, A), AP1)" -> (icmp eq/ne A, TrailingZeros(AP1) - TrailingZeros(AP2)).
Instruction * foldICmpBinOpWithConstantViaTruthTable (ICmpInst &Cmp, BinaryOperator *BO, const APInt &C)
Instruction * foldICmpBinOpEqualityWithConstant (ICmpInst &Cmp, BinaryOperator *BO, const APInt &C)
Fold an icmp equality instruction with binary operator LHS and constant RHS: icmp eq/ne BO, C.
Instruction * foldICmpIntrinsicWithConstant (ICmpInst &ICI, IntrinsicInst *II, const APInt &C)
Fold an icmp with LLVM intrinsic and constant operand: icmp Pred II, C.
Instruction * foldICmpEqIntrinsicWithConstant (ICmpInst &ICI, IntrinsicInst *II, const APInt &C)
Fold an equality icmp with LLVM intrinsic and constant operand.
Instruction * foldICmpBitCast (ICmpInst &Cmp)
Instruction * foldICmpWithTrunc (ICmpInst &Cmp)
Instruction * foldICmpCommutative (CmpPredicate Pred, Value *Op0, Value *Op1, ICmpInst &CxtI)
Instruction * foldSelectOfBools (SelectInst &SI)
Instruction * foldSelectToCmp (SelectInst &SI)
Instruction * foldSelectExtConst (SelectInst &Sel)
Instruction * foldSelectEqualityTest (SelectInst &SI)
Instruction * foldSelectOpOp (SelectInst &SI, Instruction *TI, Instruction *FI)
We have (select c, TI, FI), and we know that TI and FI have the same opcode.
Instruction * foldSelectIntoOp (SelectInst &SI, Value *, Value *)
Try to fold the select into one of the operands to allow further optimization.
Instruction * foldSPFofSPF (Instruction *Inner, SelectPatternFlavor SPF1, Value *A, Value *B, Instruction &Outer, SelectPatternFlavor SPF2, Value *C)
We have an SPF (e.g.
Instruction * foldSelectInstWithICmp (SelectInst &SI, ICmpInst *ICI)
Visit a SelectInst that has an ICmpInst as its first operand.
Value * foldSelectWithConstOpToBinOp (ICmpInst *Cmp, Value *TrueVal, Value *FalseVal)
Fold X Pred C1 ?
Instruction * foldSelectValueEquivalence (SelectInst &SI, CmpInst &CI)
Fold the following code sequence:
bool replaceInInstruction (Value *V, Value *Old, Value *New, unsigned Depth=0)
Value * insertRangeTest (Value *V, const APInt &Lo, const APInt &Hi, bool isSigned, bool Inside)
Emit a computation of: (V >= Lo && V < Hi) if Inside is true, otherwise (V < Lo || V >= Hi).
bool mergeStoreIntoSuccessor (StoreInst &SI)
Try to transform: if () { *P = v1; } else { *P = v2 } or: *P = v1; if () { *P = v2; } into a phi node with a store in the successor.
Instruction * matchBSwapOrBitReverse (Instruction &I, bool MatchBSwaps, bool MatchBitReversals)
Given an initial instruction, check to see if it is the root of a bswap/bitreverse idiom.
Instruction * SimplifyAnyMemTransfer (AnyMemTransferInst *MI)
Instruction * SimplifyAnyMemSet (AnyMemSetInst *MI)
Value * EvaluateInDifferentType (Value *V, Type *Ty, bool isSigned)
Given an expression that CanEvaluateTruncated or CanEvaluateSExtd returns true for, actually insert the code to evaluate the expression.
bool tryToSinkInstruction (Instruction *I, BasicBlock *DestBlock)
Try to move the specified instruction from its current block into the beginning of DestBlock, which can only happen if it's safe to move the instruction past all of the instructions between it and the end of its block.
void tryToSinkInstructionDbgVariableRecords (Instruction *I, BasicBlock::iterator InsertPos, BasicBlock *SrcBlock, BasicBlock *DestBlock, SmallVectorImpl< DbgVariableRecord * > &DPUsers)
bool removeInstructionsBeforeUnreachable (Instruction &I)
void addDeadEdge (BasicBlock *From, BasicBlock *To, SmallVectorImpl< BasicBlock * > &Worklist)
void handleUnreachableFrom (Instruction *I, SmallVectorImpl< BasicBlock * > &Worklist)
void handlePotentiallyDeadBlocks (SmallVectorImpl< BasicBlock * > &Worklist)
void handlePotentiallyDeadSuccessors (BasicBlock *BB, BasicBlock *LiveSucc)
void freelyInvertAllUsersOf (Value *V, Value *IgnoredUser=nullptr)
Freely adapt every user of V as-if V was changed to !V.
Value * takeLog2 (Value *Op, unsigned Depth, bool AssumeNonZero, bool DoFold)
Take the exact integer log2 of the value.
Value * tryGetLog2 (Value *Op, bool AssumeNonZero)
bool SimplifyDemandedBits (Instruction *I, unsigned OpNo, const APInt &DemandedMask, KnownBits &Known)
Public Member Functions inherited from llvm::InstCombiner
InstCombiner (InstructionWorklist &Worklist, BuilderTy &Builder, Function &F, AAResults *AA, AssumptionCache &AC, TargetLibraryInfo &TLI, TargetTransformInfo &TTI, DominatorTree &DT, OptimizationRemarkEmitter &ORE, BlockFrequencyInfo *BFI, BranchProbabilityInfo *BPI, ProfileSummaryInfo *PSI, const DataLayout &DL, ReversePostOrderTraversal< BasicBlock * > &RPOT)
virtual ~InstCombiner ()=default
Value * getFreelyInvertedImpl (Value *V, bool WillInvertAllUses, BuilderTy *Builder, bool &DoesConsume, unsigned Depth)
Return nonnull value if V is free to invert under the condition of WillInvertAllUses.
Value * getFreelyInverted (Value *V, bool WillInvertAllUses, BuilderTy *Builder, bool &DoesConsume)
Value * getFreelyInverted (Value *V, bool WillInvertAllUses, BuilderTy *Builder)
bool isFreeToInvert (Value *V, bool WillInvertAllUses, bool &DoesConsume)
Return true if the specified value is free to invert (apply ~ to).
bool isFreeToInvert (Value *V, bool WillInvertAllUses)
bool canFreelyInvertAllUsersOf (Instruction *V, Value *IgnoredUser)
Given i1 V, can every user of V be freely adapted if V is changed to !V ?
void addToWorklist (Instruction *I)
AssumptionCache & getAssumptionCache () const
TargetLibraryInfo & getTargetLibraryInfo () const
DominatorTree & getDominatorTree () const
const DataLayout & getDataLayout () const
const SimplifyQuery & getSimplifyQuery () const
OptimizationRemarkEmitter & getOptimizationRemarkEmitter () const
BlockFrequencyInfo * getBlockFrequencyInfo () const
ProfileSummaryInfo * getProfileSummaryInfo () const
std::optional< Instruction * > targetInstCombineIntrinsic (IntrinsicInst &II)
std::optional< Value * > targetSimplifyDemandedUseBitsIntrinsic (IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed)
std::optional< Value * > targetSimplifyDemandedVectorEltsIntrinsic (IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp)
void computeBackEdges ()
bool isBackEdge (const BasicBlock *From, const BasicBlock *To)
Instruction * InsertNewInstBefore (Instruction *New, BasicBlock::iterator Old)
Inserts an instruction New before instruction Old.
Instruction * InsertNewInstWith (Instruction *New, BasicBlock::iterator Old)
Same as InsertNewInstBefore, but also sets the debug loc.
Instruction * replaceInstUsesWith (Instruction &I, Value *V)
A combiner-aware RAUW-like routine.
Instruction * replaceOperand (Instruction &I, unsigned OpNum, Value *V)
Replace operand of instruction and add old operand to the worklist.
void replaceUse (Use &U, Value *NewValue)
Replace use and add the previously used value to the worklist.
void computeKnownBits (const Value *V, KnownBits &Known, const Instruction *CxtI, unsigned Depth=0) const
KnownBits computeKnownBits (const Value *V, const Instruction *CxtI, unsigned Depth=0) const
bool isKnownToBeAPowerOfTwo (const Value *V, bool OrZero=false, const Instruction *CxtI=nullptr, unsigned Depth=0)
bool MaskedValueIsZero (const Value *V, const APInt &Mask, const Instruction *CxtI=nullptr, unsigned Depth=0) const
unsigned ComputeNumSignBits (const Value *Op, const Instruction *CxtI=nullptr, unsigned Depth=0) const
unsigned ComputeMaxSignificantBits (const Value *Op, const Instruction *CxtI=nullptr, unsigned Depth=0) const
OverflowResult computeOverflowForUnsignedMul (const Value *LHS, const Value *RHS, const Instruction *CxtI, bool IsNSW=false) const
OverflowResult computeOverflowForSignedMul (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForUnsignedAdd (const WithCache< const Value * > &LHS, const WithCache< const Value * > &RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForSignedAdd (const WithCache< const Value * > &LHS, const WithCache< const Value * > &RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForUnsignedSub (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
OverflowResult computeOverflowForSignedSub (const Value *LHS, const Value *RHS, const Instruction *CxtI) const
bool SimplifyDemandedBits (Instruction *I, unsigned OpNo, const APInt &DemandedMask, KnownBits &Known)
bool isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const
Public Member Functions inherited from llvm::InstVisitor< InstCombinerImpl, Instruction * >
void visit (Iterator Start, Iterator End)
void visitModule (Module &M)
void visitFunction (Function &F)
void visitBasicBlock (BasicBlock &BB)
Instruction * visitICmpInst (ICmpInst &I)
Instruction * visitFCmpInst (FCmpInst &I)
Instruction * visitAllocaInst (AllocaInst &I)
Instruction * visitLoadInst (LoadInst &I)
Instruction * visitStoreInst (StoreInst &I)
Instruction * visitAtomicCmpXchgInst (AtomicCmpXchgInst &I)
Instruction * visitAtomicRMWInst (AtomicRMWInst &I)
Instruction * visitFenceInst (FenceInst &I)
Instruction * visitGetElementPtrInst (GetElementPtrInst &I)
Instruction * visitPHINode (PHINode &I)
Instruction * visitTruncInst (TruncInst &I)
Instruction * visitZExtInst (ZExtInst &I)
Instruction * visitSExtInst (SExtInst &I)
Instruction * visitFPTruncInst (FPTruncInst &I)
Instruction * visitFPExtInst (FPExtInst &I)
Instruction * visitFPToUIInst (FPToUIInst &I)
Instruction * visitFPToSIInst (FPToSIInst &I)
Instruction * visitUIToFPInst (UIToFPInst &I)
Instruction * visitSIToFPInst (SIToFPInst &I)
Instruction * visitPtrToIntInst (PtrToIntInst &I)
Instruction * visitPtrToAddrInst (PtrToAddrInst &I)
Instruction * visitIntToPtrInst (IntToPtrInst &I)
Instruction * visitBitCastInst (BitCastInst &I)
Instruction * visitAddrSpaceCastInst (AddrSpaceCastInst &I)
Instruction * visitSelectInst (SelectInst &I)
Instruction * visitVAArgInst (VAArgInst &I)
Instruction * visitExtractElementInst (ExtractElementInst &I)
Instruction * visitInsertElementInst (InsertElementInst &I)
Instruction * visitShuffleVectorInst (ShuffleVectorInst &I)
Instruction * visitExtractValueInst (ExtractValueInst &I)
Instruction * visitInsertValueInst (InsertValueInst &I)
Instruction * visitLandingPadInst (LandingPadInst &I)
Instruction * visitFuncletPadInst (FuncletPadInst &I)
Instruction * visitCleanupPadInst (CleanupPadInst &I)
Instruction * visitCatchPadInst (CatchPadInst &I)
Instruction * visitFreezeInst (FreezeInst &I)
Instruction * visitMemSetInst (MemSetInst &I)
Instruction * visitMemSetPatternInst (MemSetPatternInst &I)
Instruction * visitMemCpyInst (MemCpyInst &I)
Instruction * visitMemMoveInst (MemMoveInst &I)
Instruction * visitMemTransferInst (MemTransferInst &I)
Instruction * visitMemIntrinsic (MemIntrinsic &I)
Instruction * visitVAStartInst (VAStartInst &I)
Instruction * visitVAEndInst (VAEndInst &I)
Instruction * visitVACopyInst (VACopyInst &I)
Instruction * visitIntrinsicInst (IntrinsicInst &I)
Instruction * visitCallInst (CallInst &I)
Instruction * visitInvokeInst (InvokeInst &I)
Instruction * visitCallBrInst (CallBrInst &I)
Instruction * visitReturnInst (ReturnInst &I)
Instruction * visitBranchInst (BranchInst &I)
Instruction * visitSwitchInst (SwitchInst &I)
Instruction * visitIndirectBrInst (IndirectBrInst &I)
Instruction * visitResumeInst (ResumeInst &I)
Instruction * visitUnreachableInst (UnreachableInst &I)
Instruction * visitCleanupReturnInst (CleanupReturnInst &I)
Instruction * visitCatchReturnInst (CatchReturnInst &I)
Instruction * visitCatchSwitchInst (CatchSwitchInst &I)
Instruction * visitTerminator (Instruction &I)
Instruction * visitCastInst (CastInst &I)
Instruction * visitUnaryOperator (UnaryOperator &I)
Instruction * visitBinaryOperator (BinaryOperator &I)
Instruction * visitCmpInst (CmpInst &I)
Instruction * visitUnaryInstruction (UnaryInstruction &I)
Instruction * visitCallBase (CallBase &I)
void visitInstruction (Instruction &I)
Additional Inherited Members
Public Types inherited from llvm::InstCombiner
using BuilderTy = IRBuilder<TargetFolder, IRBuilderCallbackInserter>
An IRBuilder that automatically inserts new instructions into the worklist.
Static Public Member Functions inherited from llvm::InstCombiner
static Value * peekThroughBitcast (Value *V, bool OneUseOnly=false)
Return the source operand of a potentially bitcasted value while optionally checking if it has one use.
static unsigned getComplexity (Value *V)
Assign a complexity or rank value to LLVM Values.
static bool isCanonicalPredicate (CmpPredicate Pred)
Predicate canonicalization reduces the number of patterns that need to be matched by other transforms.
static Constant * AddOne (Constant *C)
Add one to a Constant.
static Constant * SubOne (Constant *C)
Subtract one from a Constant.
static bool shouldAvoidAbsorbingNotIntoSelect (const SelectInst &SI)
static Constant * getSafeVectorConstantForBinop (BinaryOperator::BinaryOps Opcode, Constant *In, bool IsRHSConstant)
Some binary operators require special handling to avoid poison and undefined behavior.
Public Attributes inherited from llvm::InstCombiner
uint64_t MaxArraySizeForCombine = 0
Maximum size of array considered when transforming.
BuilderTy & Builder
Protected Attributes inherited from llvm::InstCombiner
InstructionWorklist & Worklist
A worklist of the instructions that need to be simplified.
Function & F
const bool MinimizeSize
AAResults * AA
AssumptionCache & AC
TargetLibraryInfo & TLI
DominatorTree & DT
const DataLayout & DL
SimplifyQuery SQ
OptimizationRemarkEmitter & ORE
BlockFrequencyInfo * BFI
BranchProbabilityInfo * BPI
ProfileSummaryInfo * PSI
DomConditionCache DC
ReversePostOrderTraversal< BasicBlock * > & RPOT
bool MadeIRChange = false
SmallDenseSet< std::pair< BasicBlock *, BasicBlock * >, 8 > DeadEdges
Edges that are known to never be taken.
SmallDenseMap< BasicBlock *, SmallVector< BasicBlock * >, 8 > PredOrder
Order of predecessors to canonicalize phi nodes towards.
SmallDenseSet< std::pair< const BasicBlock *, const BasicBlock * >, 8 > BackEdges
Backedges, used to avoid pushing instructions across backedges in cases where this may result in infinite combine loops.
bool ComputedBackEdges = false
Detailed Description
Definition at line 61 of file InstCombineInternal.h.
Constructor & Destructor Documentation
InstCombinerImpl()
llvm::InstCombinerImpl::InstCombinerImpl (InstructionWorklist & Worklist, BuilderTy & Builder, Function & F, AAResults * AA, AssumptionCache & AC, TargetLibraryInfo & TLI, TargetTransformInfo & TTI, DominatorTree & DT, OptimizationRemarkEmitter & ORE, BlockFrequencyInfo * BFI, BranchProbabilityInfo * BPI, ProfileSummaryInfo * PSI, const DataLayout & DL, ReversePostOrderTraversal< BasicBlock * > & RPOT) inline
Definition at line 65 of file InstCombineInternal.h.
References llvm::InstCombiner::AA, llvm::InstCombiner::AC, llvm::InstCombiner::BFI, llvm::InstCombiner::BPI, llvm::InstCombiner::Builder, llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::InstCombiner::F, llvm::InstCombiner::InstCombiner(), llvm::InstCombiner::ORE, llvm::InstCombiner::PSI, llvm::InstCombiner::RPOT, llvm::InstCombiner::TLI, and llvm::InstCombiner::Worklist.
Referenced by foldPowiReassoc().
~InstCombinerImpl()
llvm::InstCombinerImpl::~InstCombinerImpl () override default
References canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeICmpPredicate(), commonCastTransforms(), commonIDivRemTransforms(), commonIDivTransforms(), commonIRemTransforms(), commonShiftTransforms(), llvm::InstCombiner::F, foldAggregateConstructionIntoAggregateReuse(), foldFMulReassoc(), foldFreezeIntoRecurrence(), foldItoFPtoI(), foldPowiReassoc(), foldReversedIntrinsicOperands(), FoldShiftByConstant(), foldShuffledIntrinsicOperands(), foldVariableSignZeroExtensionOfVariableHighBitExtract(), freezeOtherUses(), GEP, I, II, IV, LHS, Op0, OptimizePointerDifference(), prepareWorklist(), pushFreezeToPreventPoisonFromPropagating(), reassociateShiftAmtsOfTwoSameDirectionShifts(), RHS, run(), simplifyBinOpSplats(), simplifyDivRemOfSelectWithZeroOp(), simplifyRangeCheck(), sinkNotIntoLogicalOp(), sinkNotIntoOtherHandOfLogicalOp(), SliceUpIllegalIntegerPHI(), llvm::InstCombiner::SQ, visitAdd(), visitAddrSpaceCast(), visitAllocaInst(), visitAllocSite(), visitAnd(), visitAShr(), visitAtomicRMWInst(), visitBitCast(), visitBranchInst(), visitCallBrInst(), visitCallInst(), visitExtractElementInst(), visitExtractValueInst(), visitFAdd(), visitFCmpInst(), visitFDiv(), visitFenceInst(), visitFMul(), visitFNeg(), visitFPExt(), visitFPToSI(), visitFPToUI(), visitFPTrunc(), visitFree(), visitFreeze(), visitFRem(), visitFSub(), visitGEPOfGEP(), visitGetElementPtrInst(), visitICmpInst(), visitInsertElementInst(), visitInsertValueInst(), visitIntToPtr(), visitInvokeInst(), visitLandingPadInst(), visitLoadInst(), visitLShr(), visitMul(), visitOr(), visitPHINode(), visitPtrToAddr(), visitPtrToInt(), visitReturnInst(), visitSDiv(), visitSelectInst(), visitSExt(), visitShl(), visitShuffleVectorInst(), visitSIToFP(), visitSRem(), visitStoreInst(), visitSub(), visitSwitchInst(), visitTrunc(), visitUDiv(), visitUIToFP(), visitUnconditionalBranchInst(), visitUnreachableInst(), visitURem(), visitVAEndInst(), visitXor(), and visitZExt().
Member Function Documentation
addDeadEdge()
void InstCombinerImpl::addDeadEdge (BasicBlock * From, BasicBlock * To, SmallVectorImpl< BasicBlock * > & Worklist)
Definition at line 4136 of file InstructionCombining.cpp.
References llvm::InstCombiner::addToWorklist(), llvm::InstCombiner::DeadEdges, llvm::PoisonValue::get(), llvm::isa(), llvm::InstCombiner::MadeIRChange, llvm::BasicBlock::phis(), llvm::InstCombiner::replaceUse(), and llvm::InstCombiner::Worklist.
Referenced by handlePotentiallyDeadSuccessors(), handleUnreachableFrom(), and replaceInInstruction().
canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract()
Instruction * InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract (BinaryOperator & I)
Definition at line 1351 of file InstCombineAddSub.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::CastInst::CreateTruncOrBitCast(), llvm::Value::getName(), llvm::Type::getScalarSizeInBits(), I, llvm::isSignBitCheck(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExtOrSelf(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::PatternMatch::match(), Select, std::swap(), and X.
Referenced by visitAdd(), visitOr(), visitSub(), and ~InstCombinerImpl().
canonicalizeICmpPredicate()
CmpInst * InstCombinerImpl::canonicalizeICmpPredicate (CmpInst & I)
If we have a comparison with a non-canonical predicate, if we can update all the users, invert the predicate and adjust all the users.
Definition at line 7223 of file InstCombineCompares.cpp.
References llvm::InstCombiner::canFreelyInvertAllUsersOf(), freelyInvertAllUsersOf(), llvm::CmpInst::getInversePredicate(), I, and llvm::InstCombiner::isCanonicalPredicate().
Referenced by visitICmpInst(), and ~InstCombinerImpl().
combineLoadToNewType()
LoadInst * InstCombinerImpl::combineLoadToNewType (LoadInst & LI, Type * NewTy, const Twine & Suffix = "")
Helper to combine a load to a new type.
This just does the work of combining a load to a new type. It handles metadata, etc., and returns the new instruction. The NewTy should be the loaded value type. This will convert it to a pointer, cast the operand to that pointer type, load it, etc.
Note that this will create all of the instructions with whatever insert point the InstCombinerImpl currently is using.
Definition at line 599 of file InstCombineLoadStoreAlloca.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::copyMetadataForLoad(), llvm::LoadInst::getAlign(), llvm::Value::getName(), llvm::LoadInst::getOrdering(), llvm::LoadInst::getPointerOperand(), llvm::LoadInst::getSyncScopeID(), llvm::Instruction::isAtomic(), isSupportedAtomicType(), llvm::LoadInst::isVolatile(), and llvm::LoadInst::setAtomic().
Referenced by combineLoadToOperationType(), and unpackLoadToAggregate().
commonCastTransforms()
Instruction * InstCombinerImpl::commonCastTransforms (CastInst & CI)
Implement the transforms common to all CastInst visitors.
Definition at line 190 of file InstCombineCasts.cpp.
References llvm::InstCombiner::Builder, llvm::CastInst::Create(), llvm::InstCombiner::DT, llvm::dyn_cast(), foldOpIntoPhi(), FoldOpIntoSelect(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::CastInst::getSrcTy(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::replaceAllDbgUsesWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::simplifyCastInst(), llvm::InstCombiner::SQ, and X.
Referenced by visitAddrSpaceCast(), visitBitCast(), visitFPExt(), visitFPToSI(), visitFPToUI(), visitFPTrunc(), visitIntToPtr(), visitPtrToAddr(), visitPtrToInt(), visitSExt(), visitSIToFP(), visitTrunc(), visitUIToFP(), visitZExt(), and ~InstCombinerImpl().
commonIDivRemTransforms()
Instruction * InstCombinerImpl::commonIDivRemTransforms (BinaryOperator & I)
Common integer divide/remainder transforms.
Definition at line 1277 of file InstCombineMulDivRem.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), foldBinopWithPhiOperands(), FoldOpIntoSelect(), llvm::PoisonValue::get(), llvm::Constant::getAggregateElement(), I, llvm::isa(), llvm::Constant::isNullValue(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), simplifyDivRemOfSelectWithZeroOp(), and simplifyValueKnownNonZero().
Referenced by commonIDivTransforms(), commonIRemTransforms(), and ~InstCombinerImpl().
commonIDivTransforms()
Instruction * InstCombinerImpl::commonIDivTransforms (BinaryOperator & I)
This function implements the transforms common to both integer division instructions (udiv and sdiv).
It is called by the visitors to those integer division instructions. Common integer divide transforms
Definition at line 1324 of file InstCombineMulDivRem.cpp.
References A(), assert(), B(), llvm::InstCombiner::Builder, llvm::cast(), commonIDivRemTransforms(), llvm::BinaryOperator::Create(), llvm::SelectInst::Create(), foldBinOpIntoSelectOrPhi(), foldIDivShl(), llvm::APInt::getBitWidth(), llvm::APInt::getOneBitSet(), llvm::APInt::getZExtValue(), hasNoUnsignedWrap(), I, llvm::APInt::isAllOnes(), llvm::isGuaranteedNotToBeUndef(), isMultiple(), llvm::APInt::isZero(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_NSWAddLike(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NUWAddLike(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Mul, multiplyOverflows(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::Instruction::setIsExact(), SimplifyDemandedInstructionBits(), llvm::APInt::udiv(), llvm::APInt::ule(), llvm::APInt::ult(), X, and Y.
Referenced by visitSDiv(), visitUDiv(), and ~InstCombinerImpl().
commonIRemTransforms()
Instruction * InstCombinerImpl::commonIRemTransforms (BinaryOperator & I)
This function implements the transforms common to both integer remainder instructions (urem and srem).
It is called by the visitors to those integer remainder instructions. Common integer remainder transforms
Definition at line 2378 of file InstCombineMulDivRem.cpp.
References commonIDivRemTransforms(), llvm::dyn_cast(), foldOpIntoPhi(), FoldOpIntoSelect(), I, llvm::isa(), llvm::APInt::isMinSignedValue(), llvm::APInt::isMinValue(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), Op0, SimplifyDemandedInstructionBits(), and simplifyIRemMulShl().
Referenced by visitSRem(), visitURem(), and ~InstCombinerImpl().
commonShiftTransforms()
Instruction * InstCombinerImpl::commonShiftTransforms (BinaryOperator & I)
Definition at line 406 of file InstCombineShifts.cpp.
References A(), llvm::InstCombiner::AC, assert(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::cast_or_null(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::dyn_cast(), foldBinopWithPhiOperands(), FoldOpIntoSelect(), FoldShiftByConstant(), foldShiftOfShiftedBinOp(), llvm::User::getOperand(), llvm::ConstantExpr::getSub(), I, llvm::isa(), llvm::APInt::isNegative(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_NUWAddLike(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombiner::replaceOperand(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::Instruction::setIsExact(), SimplifyDemandedInstructionBits(), llvm::InstCombiner::SQ, and Y.
Referenced by visitAShr(), visitLShr(), visitShl(), and ~InstCombinerImpl().
computeKnownFPClass() [1/2]
KnownFPClass llvm::InstCombinerImpl::computeKnownFPClass (Value * Val, FastMathFlags FMF, FPClassTest Interested = fcAllFlags, const Instruction * CtxI = nullptr, unsigned Depth = 0) const inline
Definition at line 205 of file InstCombineInternal.h.
References llvm::computeKnownFPClass(), llvm::Depth, llvm::fcAllFlags, and llvm::InstCombiner::getSimplifyQuery().
Referenced by fmulByZeroIsZero(), foldSelectIntoOp(), SimplifyDemandedFPClass(), SimplifyDemandedUseFPClass(), and SimplifyMultipleUseDemandedFPClass().
computeKnownFPClass() [2/2]
KnownFPClass llvm::InstCombinerImpl::computeKnownFPClass (Value * Val, FPClassTest Interested = fcAllFlags, const Instruction * CtxI = nullptr, unsigned Depth = 0) const inline
Definition at line 214 of file InstCombineInternal.h.
References llvm::computeKnownFPClass(), llvm::Depth, llvm::fcAllFlags, and llvm::InstCombiner::getSimplifyQuery().
computeOverflow()
OverflowResult InstCombinerImpl::computeOverflow (Instruction::BinaryOps BinaryOp, bool IsSigned, Value * LHS, Value * RHS, Instruction * CxtI) const
Definition at line 6524 of file InstCombineCompares.cpp.
References llvm::InstCombiner::computeOverflowForSignedAdd(), llvm::InstCombiner::computeOverflowForSignedMul(), llvm::InstCombiner::computeOverflowForSignedSub(), llvm::InstCombiner::computeOverflowForUnsignedAdd(), llvm::InstCombiner::computeOverflowForUnsignedMul(), llvm::InstCombiner::computeOverflowForUnsignedSub(), and llvm_unreachable.
Referenced by foldICmpBinOpEqualityWithConstant(), and visitCallInst().
convertOrOfShiftsToFunnelShift()
std::optional< std::pair< Intrinsic::ID, SmallVector< Value *, 3 > > > InstCombinerImpl::convertOrOfShiftsToFunnelShift (Instruction & Or)
Definition at line 2930 of file InstCombineAndOrXor.cpp.
References assert(), llvm::cast(), llvm::InstCombiner::computeKnownBits(), llvm::InstCombiner::DT, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::ConstantExpr::getAdd(), llvm::KnownBits::getMaxValue(), llvm::Instruction::getOpcode(), llvm::Value::getType(), High, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::isPowerOf2_32(), llvm::Low, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_LogicalShift(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::Constant::mergeUndefsWith(), std::swap(), llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ule(), llvm::APInt::ult(), llvm::Value::users(), X, and Y.
Referenced by matchFunnelShift(), and SimplifyDemandedUseBits().
CreateNonTerminatorUnreachable()
void llvm::InstCombinerImpl::CreateNonTerminatorUnreachable (Instruction * InsertAt) inline
Create and insert the idiom we use to indicate a block is unreachable without having to rewrite the CFG from within InstCombine.
Definition at line 489 of file InstCombineInternal.h.
References llvm::PoisonValue::get(), llvm::Value::getContext(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::ConstantInt::getTrue(), llvm::PointerType::getUnqual(), and llvm::InstCombiner::InsertNewInstWith().
Referenced by visitCallInst(), visitFree(), and visitLoadInst().
dominatesAllUses()
bool InstCombinerImpl::dominatesAllUses (const Instruction * DI, const Instruction * UI, const BasicBlock * DB) const
True when DB dominates all uses of DI except UI.
Check that one use is in the same block as the definition and all other uses are in blocks dominated by a given block.
UI must be in the same block as DI. The routine checks that the DI parent and DB are different.
Parameters
DI Definition
UI Use
DB Block that must dominate all uses of DI outside the parent block
Returns
true when UI is the only use of DI in the parent block and all other uses of DI are in blocks dominated by DB.
Definition at line 6797 of file InstCombineCompares.cpp.
References assert(), llvm::cast(), llvm::InstCombiner::DT, llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), and llvm::Value::users().
Referenced by replacedSelectWithOperand().
eraseInstFromFunction()
Instruction * llvm::InstCombinerImpl::eraseInstFromFunction (Instruction & I) inline override virtual
Combiner aware instruction erasure.
When dealing with an instruction that has side effects or produces a void value, we can't rely on DCE to delete the instruction. Instead, visit methods should return the value returned by this function.
Implements llvm::InstCombiner.
Definition at line 502 of file InstCombineInternal.h.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::dbgs(), llvm::InstCombiner::DC, I, LLVM_DEBUG, llvm::InstCombiner::MadeIRChange, llvm::salvageDebugInfo(), and llvm::InstCombiner::Worklist.
Referenced by combineLoadToOperationType(), convertFSqrtDivIntoFMul(), foldAllocaCmp(), foldBinopWithRecurrence(), foldDeadPhiWeb(), foldIntegerTypedPHI(), foldMultiplicationOverflowCheck(), foldOpIntoPhi(), handleUnreachableFrom(), mergeStoreIntoSuccessor(), processUGT_ADDCST_ADD(), removeInstructionsBeforeUnreachable(), removeTriviallyEmptyRange(), run(), visitAllocaInst(), visitAllocSite(), visitCallInst(), visitFenceInst(), visitFree(), visitICmpInst(), and visitStoreInst().
EvaluateInDifferentType()
Value * InstCombinerImpl::EvaluateInDifferentType (Value * V, Type * Ty, bool isSigned)
Given an expression that CanEvaluateTruncated or CanEvaluateSExtd returns true for, actually insert the code to evaluate the expression.
Definition at line 158 of file InstCombineCasts.cpp.
References EvaluateInDifferentTypeImpl().
Referenced by replaceInInstruction(), visitSExt(), visitTrunc(), and visitZExt().
fmulByZeroIsZero()
bool InstCombinerImpl::fmulByZeroIsZero (Value * MulVal, FastMathFlags FMF, const Instruction * CtxI) const
Check if fmul MulVal, +0.0 will yield +0.0 (or signed zero is ignorable).
Definition at line 4044 of file InstCombineSelect.cpp.
References computeKnownFPClass(), llvm::fcNegative, llvm::KnownFPClass::isKnownNeverInfinity(), llvm::KnownFPClass::isKnownNeverNaN(), llvm::FastMathFlags::noSignedZeros(), and llvm::KnownFPClass::signBitIsZeroOrNaN().
Referenced by matchFMulByZeroIfResultEqZero().
foldAddLikeCommutative()
Instruction * InstCombinerImpl::foldAddLikeCommutative (Value * LHS, Value * RHS, bool NSW, bool NUW)
Common transforms for add / disjoint or.
Definition at line 1321 of file InstCombineAddSub.cpp.
References A(), B(), llvm::CallingConv::C, llvm::APInt::getBitWidth(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_NUWSub(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by visitAdd(), and visitOr().
foldAddWithConstant()
Instruction * InstCombinerImpl::foldAddWithConstant (BinaryOperator & Add)
Definition at line 856 of file InstCombineAddSub.cpp.
References llvm::Add, llvm::InstCombiner::AddOne(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::computeKnownBits(), llvm::CastInst::Create(), foldBinOpIntoSelectOrPhi(), foldBinOpSelectBinOp(), llvm::ConstantExpr::getAdd(), llvm::APInt::getHighBitsSet(), llvm::ConstantExpr::getSub(), llvm::Value::getType(), llvm::isKnownNonZero(), llvm::APInt::isMask(), llvm::APInt::isMinSignedValue(), llvm::APInt::isPowerOf2(), llvm::APInt::isSignMask(), llvm::APInt::logBase2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_DisjointOr(), llvm::PatternMatch::m_ImmConstant(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_ZExt(), llvm::MaskedValueIsZero(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::APInt::sext(), llvm::InstCombiner::SQ, llvm::InstCombiner::SubOne(), X, Y, and llvm::KnownBits::Zero.
Referenced by visitAdd().
foldAggregateConstructionIntoAggregateReuse()
Instruction * InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse (InsertValueInst & OrigIVI)
Look for chain of insertvalue's that fully define an aggregate, and trace back the values inserted, see if they are all were extractvalue'd from the same source aggregate from the exact same element indexes.
If they were, just reuse the source aggregate. This potentially deals with PHI indirections.
When analyzing the value that was inserted into an aggregate, we did not manage to find defining extractvalue instruction to analyze.
When analyzing the value that was inserted into an aggregate, we did manage to find defining extractvalue instruction[s], and everything matched perfectly - aggregate type, element insertion/extraction index.
When analyzing the value that was inserted into an aggregate, we did manage to find defining extractvalue instruction, but there was a mismatch: either the source type from which the extraction was didn't match the aggregate type into which the insertion was, or the extraction/insertion channels mismatched, or different elements had different source aggregates.
Definition at line 906 of file InstCombineVectorOps.cpp.
References llvm::Type::ArrayTyID, assert(), llvm::InstCombiner::Builder, llvm::Depth, llvm::Value::DoPHITranslation(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::enumerate(), llvm::ArrayRef< T >::front(), llvm::PoisonValue::get(), llvm::Type::getArrayNumElements(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Type::getStructNumElements(), llvm::Value::getType(), llvm::Type::getTypeID(), I, llvm::is_contained(), llvm::isa(), IV, llvm_unreachable, PHI, llvm::pred_empty(), llvm::predecessors(), llvm::InstCombiner::replaceInstUsesWith(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Type::StructTyID, and llvm::MapVector< KeyT, ValueT, MapType, VectorType >::try_emplace().
Referenced by visitInsertValueInst(), and ~InstCombinerImpl().
foldAllocaCmp()
bool InstCombinerImpl::foldAllocaCmp (AllocaInst * Alloca)
The value of the map is a bit mask of which icmp operands the alloca is used in.
Definition at line 829 of file InstCombineCompares.cpp.
References llvm::Continue, llvm::dyn_cast(), eraseInstFromFunction(), llvm::getUnderlyingObject(), llvm::CmpInst::ICMP_NE, llvm_unreachable, llvm::PointerMayBeCaptured(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by visitICmpInst().
foldBinOpIntoSelectOrPhi()
Instruction * InstCombinerImpl::foldBinOpIntoSelectOrPhi (BinaryOperator & I)
This is a convenience wrapper function for the above two functions.
Definition at line 2310 of file InstructionCombining.cpp.
References llvm::dyn_cast(), foldOpIntoPhi(), FoldOpIntoSelect(), I, and llvm::isa().
Referenced by commonIDivTransforms(), foldAddWithConstant(), FoldShiftByConstant(), visitAnd(), visitFAdd(), visitFMul(), visitMul(), visitOr(), and visitXor().
foldBinOpOfSelectAndCastOfSelectCondition()
Instruction * InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition (BinaryOperator & I)
Tries to simplify binops of select and cast of the select condition.
(Binop (cast C), (select C, T, F)) -> (select C, C0, C1)
Definition at line 1101 of file InstructionCombining.cpp.
References A(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::SelectInst::Create(), llvm::Constant::getAllOnesValue(), llvm::Constant::getIntegerValue(), llvm::Constant::getNullValue(), I, llvm::isa(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), and Opc.
Referenced by visitAdd(), visitMul(), and visitSub().
foldBinOpSelectBinOp()
Instruction * InstCombinerImpl::foldBinOpSelectBinOp (BinaryOperator & Op)
In some cases it is beneficial to fold a select into a binary operator.
For example: %1 = or in, 4 %2 = select cond, %1, in %3 = or %2, 1 => %1 = select i1 cond, 5, 1 %2 = or %1, in
Definition at line 1887 of file InstructionCombining.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::ConstantFoldBinaryInstruction(), llvm::BinaryOperator::Create(), llvm::dyn_cast(), llvm::Value::hasOneUse(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Specific(), and llvm::PatternMatch::match().
Referenced by foldAddWithConstant(), visitMul(), visitOr(), and visitXor().
foldBinOpShiftWithShift()
Instruction * InstCombinerImpl::foldBinOpShiftWithShift (BinaryOperator & I)
Definition at line 955 of file InstructionCombining.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::ConstantFoldBinaryOpOperands(), llvm::BinaryOperator::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), I, llvm::Instruction::isBitwiseLogicOp(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_ImmConstant(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shift(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Opc, X, and Y.
Referenced by visitAdd(), visitAnd(), visitOr(), and visitXor().
foldBinopWithPhiOperands()
Instruction * InstCombinerImpl::foldBinopWithPhiOperands (BinaryOperator & BO)
For a binary operator with 2 phi operands, try to hoist the binary operation before the phi.
This can result in fewer instructions in patterns where at least one set of phi operands simplifies. Example: BB3: binop (phi [X, BB1], [C1, BB2]), (phi [Y, BB1], [C2, BB2]) --> BB1: BO = binop X, Y BB3: phi [BO, BB1], [(binop C1, C2), BB2]
Definition at line 2195 of file InstructionCombining.cpp.
References llvm::PHINode::addIncoming(), llvm::all_of(), assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::ConstantFoldBinaryOpOperands(), llvm::PHINode::Create(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), foldBinopWithRecurrence(), llvm::ConstantExpr::getBinOpIdentity(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), I, llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), T, and llvm::zip().
Referenced by commonIDivRemTransforms(), commonShiftTransforms(), visitAdd(), visitAnd(), visitFAdd(), visitFDiv(), visitFMul(), visitFRem(), visitFSub(), visitMul(), visitOr(), visitSub(), and visitXor().
foldBinopWithRecurrence()
Instruction * InstCombinerImpl::foldBinopWithRecurrence (BinaryOperator & BO)
Try to fold binary operators whose operands are simple interleaved recurrences to a single recurrence.
This is a common pattern in reduction operations. Example: phi1 = phi [init1, BB1], [op1, BB2] phi2 = phi [init2, BB1], [op2, BB2] op1 = binop phi1, constant1 op2 = binop phi2, constant2 rdx = binop op1, op2 --> phi_combined = phi [init_combined, BB1], [op_combined, BB2] rdx_combined = binop phi_combined, constant_combined
Definition at line 2092 of file InstructionCombining.cpp.
References llvm::OverflowTracking::AllKnownNonNegative, assert(), llvm::CallingConv::C, llvm::ConstantFoldBinaryInstruction(), llvm::BinaryOperator::Create(), llvm::PHINode::Create(), llvm::dbgs(), llvm::dyn_cast(), eraseInstFromFunction(), llvm::PoisonValue::get(), llvm::Instruction::getFastMathFlags(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::PHINode::getNumIncomingValues(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Value::getType(), llvm::Value::hasNUses(), llvm::Value::hasOneUse(), I, llvm::InstCombiner::InsertNewInstWith(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), LLVM_DEBUG, llvm_unreachable, llvm::matchSimpleRecurrence(), Opc, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by foldBinopWithPhiOperands().
foldCmpLoadFromIndexedGlobal()
Instruction * InstCombinerImpl::foldCmpLoadFromIndexedGlobal (LoadInst * LI, GetElementPtrInst * GEP, CmpInst & ICI, ConstantInt * AndCst = nullptr)
This is called when we see this pattern: cmp pred (load (gep GV, ...)), cmpcst where GV is a global variable with a constant initializer.
Try to simplify this into some simple computation that does not need the load. For example we can optimize "icmp eq (load (gep "foo", 0, i)), 0" into "icmp eq i, 3".
If AndCst is non-null, then the loaded value is masked with that constant before doing the comparison. This handles cases like "A[i]&4 == 0".
TrueRangeEnd/FalseRangeEnd - In conjunction with First*Element, these define a state machine that triggers for ranges of values that the index is true or false for. This triggers on things like "abbbbc"[i] == 'b'. This is -2 when undefined, -3 when overdefined, and otherwise the last index in the range (inclusive). We use -2 for undefined here because we use relative comparisons and don't want 0-1 to match -1.
Definition at line 113 of file InstCombineCompares.cpp.
References assert(), llvm::LinearExpression::BasePtr, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldLoadFromConst(), llvm::APInt::countr_zero(), llvm::decomposeLinearExpression(), llvm::divideCeil(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::LinearExpression::Flags, GEP, llvm::Constant::getAllOnesValue(), llvm::APInt::getBitWidth(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantInt::getSigned(), getType(), llvm::Value::getType(), llvm::getUnderlyingObject(), llvm::APInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::LinearExpression::Index, llvm::isa(), llvm::GEPNoWrapFlags::isInBounds(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::LoadInst::isVolatile(), llvm::InstCombiner::MaxArraySizeForCombine, llvm::LinearExpression::Offset, llvm::Offset, llvm::InstCombiner::replaceInstUsesWith(), llvm::LinearExpression::Scale, llvm::InstCombiner::TLI, llvm::APInt::uge(), and llvm::APInt::ult().
Referenced by foldICmpAndConstant(), foldICmpInstWithConstantNotInt(), and visitFCmpInst().
foldDeadPhiWeb()
bool InstCombinerImpl::foldDeadPhiWeb (PHINode & PN)
If the phi is within a phi web, which is formed by the def-use chain of phis and all the phis in the web are only used in the other phis.
In this case, these phis are dead and we will remove all of them.
Definition at line 59 of file InstCombinePHI.cpp.
References llvm::dyn_cast(), eraseInstFromFunction(), llvm::PoisonValue::get(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::SmallPtrSetImplBase::size().
Referenced by visitPHINode().
foldFCmpIntToFPConst()
Instruction * InstCombinerImpl::foldFCmpIntToFPConst (FCmpInst & I, Instruction * LHSI, Constant * RHSC)
Fold fcmp ([us]itofp x, cst) if possible.
Definition at line 8012 of file InstCombineCompares.cpp.
References assert(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::ConstantInt::getFalse(), llvm::Type::getFPMantissaWidth(), llvm::APFloat::getLargest(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APFloatBase::IEK_Inf, llvm::ilogb(), llvm::isa(), llvm_unreachable, llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::match(), P, llvm::InstCombiner::replaceInstUsesWith(), llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloatBase::rmTowardZero, llvm::APFloat::roundToIntegral(), llvm::SMax, llvm::SMin, llvm::UMax, and llvm::UMin.
Referenced by visitFCmpInst().
foldFMulReassoc()
Instruction * InstCombinerImpl::foldFMulReassoc (BinaryOperator & I)
Definition at line 783 of file InstCombineMulDivRem.cpp.
References llvm::FastMathFlags::allowReassoc(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldBinaryOpOperands(), llvm::BinaryOperator::CreateFAddFMF(), llvm::BinaryOperator::CreateFDivFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::BinaryOperator::CreateFSubFMF(), llvm::InstCombiner::DL, foldPowiReassoc(), llvm::Instruction::getFastMathFlags(), I, llvm::Constant::isNormalFP(), llvm::PatternMatch::m_AllowReassoc(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_FAdd(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_Sqrt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), X, and Y.
Referenced by visitFMul(), and ~InstCombinerImpl().
foldFreezeIntoRecurrence()
Instruction * InstCombinerImpl::foldFreezeIntoRecurrence (FreezeInst & I, PHINode * PN)
Definition at line 5126 of file InstructionCombining.cpp.
References llvm::append_range(), llvm::InstCombiner::Builder, llvm::canCreateUndefOrPoison(), llvm::cast(), llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::PHINode::getIncomingBlock(), llvm::Value::getName(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), I, llvm::PHINode::incoming_values(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isGuaranteedNotToBeUndefOrPoison(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceUse(), llvm::SmallPtrSetImplBase::size(), and llvm::InstCombiner::Worklist.
Referenced by visitFreeze(), and ~InstCombinerImpl().
foldGEPICmp()
Instruction * InstCombinerImpl::foldGEPICmp (GEPOperator * GEPLHS, Value * RHS, CmpPredicate Cond, Instruction & I)
Fold comparisons between a GEP instruction and something else.
At this point we know that the GEP is on the LHS of the comparison.
Definition at line 645 of file InstCombineCompares.cpp.
References assert(), llvm::sampleprof::Base, llvm::InstCombiner::Builder, llvm::cast(), llvm::CommonPointerBase::compute(), Cond, llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::GEPOperator::getNoWrapFlags(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::GEPOperator::getPointerOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::ICmpInst::getSignedPredicate(), llvm::GEPOperator::getSourceElementType(), llvm::Value::getType(), llvm::GEPOperator::hasAllConstantIndices(), llvm::GEPNoWrapFlags::hasNoUnsignedSignedWrap(), llvm::GEPNoWrapFlags::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::GEPOperator::isInBounds(), llvm::CmpInst::isSigned(), llvm::CmpInst::isTrueWhenEqual(), llvm::CmpInst::isUnsigned(), llvm::Type::isVectorTy(), llvm::CmpInst::makeCmpResultType(), llvm::GEPNoWrapFlags::none(), llvm::NullPointerIsDefined(), llvm::Offset, llvm::InstCombiner::replaceInstUsesWith(), llvm::Value::stripPointerCasts(), and transformToIndexedCompare().
Referenced by foldICmpCommutative().
foldICmpAddConstant()
Instruction * InstCombinerImpl::foldICmpAddConstant (ICmpInst & Cmp, BinaryOperator * Add, const APInt & C)
Fold icmp (add X, Y), C.
Definition at line 3127 of file InstCombineCompares.cpp.
References llvm::Add, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ICmpInst::compare(), llvm::computeConstantRange(), Cond, createLogicFromTable(), llvm::ConstantRange::getEquivalentICmp(), llvm::ConstantExpr::getNeg(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::ICmpInst::getSignedPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::APInt::isAllOnes(), llvm::Type::isIntOrIntVectorTy(), llvm::isKnownNonZero(), llvm::APInt::isPowerOf2(), llvm::CmpInst::isUnsigned(), llvm::APInt::isZero(), llvm::Lower, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::ConstantRange::makeExactICmpRegion(), llvm::PatternMatch::match(), llvm::TruncInst::NoUnsignedWrap, Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::SMax, llvm::SMin, llvm::InstCombiner::SQ, llvm::ConstantRange::subtract(), llvm::ConstantRange::truncate(), llvm::Upper, X, and Y.
Referenced by foldICmpBinOpWithConstant().
foldICmpAddOpConst()
Instruction * InstCombinerImpl::foldICmpAddOpConst (Value * X, const APInt & C, CmpPredicate Pred)
Fold "icmp pred (X+C), X".
Definition at line 907 of file InstCombineCompares.cpp.
References assert(), llvm::CallingConv::C, llvm::APInt::getMaxValue(), llvm::APInt::getSignedMaxValue(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::SMax, and X.
Referenced by foldICmpCommutative().
foldICmpAndConstant()
Instruction * InstCombinerImpl::foldICmpAndConstant (ICmpInst & Cmp, BinaryOperator * And, const APInt & C)
Fold icmp (and X, Y), C.
Definition at line 1927 of file InstCombineCompares.cpp.
References A(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::BinaryOperator::CreateNot(), llvm::dyn_cast(), foldCmpLoadFromIndexedGlobal(), foldICmpAndConstConst(), GEP, llvm::Constant::getNullValue(), llvm::APInt::getSignedMinValue(), llvm::Value::getType(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::isSignBitCheck(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LowBitMask(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::InstCombiner::SubOne(), X, and Y.
Referenced by foldICmpBinOpWithConstant().
foldICmpAndConstConst()
Instruction * InstCombinerImpl::foldICmpAndConstConst (ICmpInst & Cmp, BinaryOperator * And, const APInt & C1)
Fold icmp (and X, C2), C1.
Definition at line 1780 of file InstCombineCompares.cpp.
References A(), B(), llvm::APFloat::bitcastToAPInt(), llvm::InstCombiner::Builder, llvm::cast(), llvm::InstCombiner::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::fcAllFlags, llvm::fcInf, llvm::fcNan, llvm::fcSubnormal, llvm::fcZero, foldICmpAndShift(), llvm::APInt::getBitWidth(), llvm::APInt::getHighBitsSet(), llvm::APFloat::getInf(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::Type::getScalarSizeInBits(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, llvm::APInt::isNegatedPowerOf2(), llvm::APInt::isNegative(), llvm::APInt::isSignMask(), llvm::APInt::isZero(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), llvm::APInt::ule(), X, and llvm::APInt::zext().
Referenced by foldICmpAndConstant().
foldICmpAndShift()
Instruction * InstCombinerImpl::foldICmpAndShift (ICmpInst & Cmp, BinaryOperator * And, const APInt & C1, const APInt & C2)
Fold icmp (and (sh X, Y), C2), C1.
Definition at line 1693 of file InstCombineCompares.cpp.
References llvm::APInt::ashr(), assert(), llvm::InstCombiner::Builder, llvm::dyn_cast(), llvm::ConstantInt::getFalse(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantInt::getTrue(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::isa(), llvm::Instruction::isArithmeticShift(), llvm::APInt::isNegative(), llvm::APInt::isOne(), llvm::Instruction::isShift(), llvm::APInt::isZero(), llvm::APInt::lshr(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::APInt::shl().
Referenced by foldICmpAndConstConst().
foldICmpBinOp()
Instruction * InstCombinerImpl::foldICmpBinOp (ICmpInst & I, const SimplifyQuery & SQ)
Try to fold icmp (binop), X or icmp X, (binop).
TODO: A large part of this logic is duplicated in InstSimplify's simplifyICmpWithBinOp(). We should be able to share that and avoid the code duplication.
Definition at line 5133 of file InstCombineCompares.cpp.
References A(), llvm::APInt::abs(), assert(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::InstCombiner::computeKnownBits(), llvm::KnownBits::countMaxTrailingZeros(), D(), llvm::dyn_cast(), foldICmpAndXX(), foldICmpOrXX(), foldICmpWithTruncSignExtendedVal(), foldICmpXNegX(), foldICmpXorXX(), foldMultiplicationOverflowCheck(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::Constant::getAllOnesValue(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getFlippedStrictnessPredicate(), llvm::Constant::getIntegerValue(), llvm::APInt::getLowBitsSet(), llvm::ConstantExpr::getNeg(), llvm::ConstantExpr::getNot(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ICmpInst::getSignedPredicate(), llvm::ConstantExpr::getSub(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::APInt::isAllOnes(), llvm::ICmpInst::isEquality(), llvm::ICmpInst::isEquality(), llvm::Instruction::isExact(), llvm::ICmpInst::isGE(), llvm::ICmpInst::isGT(), llvm::isKnownNonEqual(), llvm::isKnownNonZero(), llvm::ICmpInst::isLE(), llvm::ICmpInst::isLT(), isMultipleOf(), llvm::APInt::isNegative(), llvm::KnownBits::isNegative(), llvm::APInt::isOne(), llvm::ICmpInst::isRelational(), llvm::CmpInst::isSigned(), llvm::KnownBits::isStrictlyPositive(), llvm::CmpInst::isUnsigned(), llvm::APInt::isZero(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AddLike(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_Mul(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_NegatedPower2OrZero(), llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::KnownBits::One, Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::simplifyICmpInst(), llvm::InstCombiner::SQ, llvm::APInt::uge(), llvm::APInt::ule(), X, and Y.
Referenced by visitICmpInst().
foldICmpBinOpEqualityWithConstant()
Instruction * InstCombinerImpl::foldICmpBinOpEqualityWithConstant (ICmpInst & Cmp, BinaryOperator * BO, const APInt & C)
Fold an icmp equality instruction with binary operator LHS and constant RHS: icmp eq/ne BO, C.
Definition at line 3601 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), computeOverflow(), Cond, llvm::BinaryOperator::Create(), llvm::dyn_cast(), llvm::Value::getName(), llvm::ConstantExpr::getNot(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getSub(), llvm::Value::getType(), llvm::ConstantExpr::getXor(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::Instruction::isExact(), llvm::isKnownNonZero(), llvm::APInt::isPowerOf2(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_NUWAdd(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::NeverOverflows, llvm::Other, llvm::APInt::sgt(), llvm::InstCombiner::SQ, and llvm::Value::takeName().
Referenced by foldICmpBinOpWithConstant().
foldICmpBinOpWithConstant()
Instruction * InstCombinerImpl::foldICmpBinOpWithConstant (ICmpInst & Cmp, BinaryOperator * BO, const APInt & C)
Fold an icmp with BinaryOp and constant operand: icmp Pred BO, C.
Definition at line 3983 of file InstCombineCompares.cpp.
References llvm::CallingConv::C, foldICmpAddConstant(), foldICmpAndConstant(), foldICmpBinOpEqualityWithConstant(), foldICmpBinOpWithConstantViaTruthTable(), foldICmpDivConstant(), foldICmpMulConstant(), foldICmpOrConstant(), foldICmpShlConstant(), foldICmpShrConstant(), foldICmpSRemConstant(), foldICmpSubConstant(), foldICmpUDivConstant(), foldICmpXorConstant(), llvm::BinaryOperator::getOpcode(), and I.
Referenced by foldICmpInstWithConstant().
foldICmpBinOpWithConstantViaTruthTable()
Instruction * InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable (ICmpInst & Cmp, BinaryOperator * BO, const APInt & C)
Definition at line 3088 of file InstCombineCompares.cpp.
References A(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::ICmpInst::compare(), Cond, llvm::ConstantFoldBinaryOpOperands(), createLogicFromTable(), llvm::InstCombiner::DL, llvm::dyn_cast_or_null(), llvm::First, llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by foldICmpBinOpWithConstant().
foldICmpBitCast()
Instruction * InstCombinerImpl::foldICmpBitCast (ICmpInst & Cmp)
Definition at line 3400 of file InstCombineCompares.cpp.
References llvm::all_equal(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::APFloat::classify(), llvm::dyn_cast(), llvm::fcInf, llvm::fcZero, llvm::VectorType::get(), llvm::Constant::getAllOnesValue(), llvm::InstCombiner::getFreelyInverted(), llvm::Constant::getNullValue(), llvm::Type::getScalarSizeInBits(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::Type::isPPC_FP128Ty(), llvm::isSignBitCheck(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_FPTrunc(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_SIToFP(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), and X.
Referenced by visitICmpInst().
foldICmpCommutative()
Instruction * InstCombinerImpl::foldICmpCommutative (CmpPredicate Pred, Value * Op0, Value * Op1, ICmpInst & CxtI)
Definition at line 7532 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::dyn_cast(), foldGEPICmp(), foldICmpAddOpConst(), foldICmpWithClamp(), foldICmpWithLowBitMaskedVal(), foldICmpWithMinMax(), foldSelectICmp(), GEP, llvm::Constant::getAllOnesValue(), llvm::ConstantInt::getFalse(), llvm::Constant::getNullValue(), llvm::APInt::getSignedMinValue(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::CmpInst::isUnsigned(), llvm_unreachable, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_CheckedInt(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::SMin, llvm::InstCombiner::SQ, and X.
Referenced by visitICmpInst().
foldICmpDivConstant()
Instruction * InstCombinerImpl::foldICmpDivConstant (ICmpInst & Cmp, BinaryOperator * Div, const APInt & C)
Fold icmp ({su}div X, Y), C.
Definition at line 2772 of file InstCombineCompares.cpp.
References addWithOverflow(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::BinaryOperator::Create(), llvm::APInt::getBitWidth(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, insertRangeTest(), llvm::APInt::isAllOnes(), llvm::Instruction::isExact(), llvm::APInt::isNegative(), llvm::APInt::isOne(), llvm::APInt::isStrictlyPositive(), llvm::APInt::isZero(), llvm_unreachable, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::APInt::negate(), llvm::InstCombiner::replaceInstUsesWith(), llvm::APInt::sdiv(), subWithOverflow(), llvm::APInt::udiv(), X, and Y.
Referenced by foldICmpBinOpWithConstant().
foldICmpEqIntrinsicWithConstant()
Instruction * InstCombinerImpl::foldICmpEqIntrinsicWithConstant (ICmpInst & ICI, IntrinsicInst * II, const APInt & C)
Fold an equality icmp with LLVM intrinsic and constant operand.
Definition at line 3794 of file InstCombineCompares.cpp.
References llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::Constant::getAllOnesValue(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, II, llvm::PatternMatch::m_APInt(), and llvm::PatternMatch::match().
Referenced by foldICmpIntrinsicWithConstant().
foldICmpEquality()
Instruction * InstCombinerImpl::foldICmpEquality (ICmpInst & Cmp)
Definition at line 6033 of file InstCombineCompares.cpp.
References A(), llvm::Add, B(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::APInt::countr_one(), D(), foldICmpEqualityWithOffset(), foldICmpIntrinsicWithIntrinsic(), llvm::APInt::getBitWidth(), llvm::ConstantInt::getBitWidth(), llvm::CmpInst::getInversePredicate(), llvm::APInt::getLimitedValue(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::ConstantExpr::getNot(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::InstCombiner::getSimplifyQuery(), llvm::Value::getType(), llvm::ConstantInt::getValue(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_LShr(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Unless(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), NC, Op0, X, llvm::Xor, Y, and llvm::APInt::zext().
Referenced by visitICmpInst().
foldICmpInstWithConstant()
Instruction * InstCombinerImpl::foldICmpInstWithConstant (ICmpInst & Cmp)
Try to fold integer comparisons with a constant operand: icmp Pred X, C where X is some kind of instruction.
Definition at line 3554 of file InstCombineCompares.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), foldICmpBinOpWithConstant(), foldICmpInstWithConstantAllowPoison(), foldICmpIntrinsicWithConstant(), foldICmpSelectConstant(), foldICmpTruncConstant(), llvm::Value::hasOneUse(), I, II, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_ExtractValue(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), X, and Y.
Referenced by visitICmpInst().
foldICmpInstWithConstantAllowPoison()
Instruction * InstCombinerImpl::foldICmpInstWithConstantAllowPoison (ICmpInst & Cmp, const APInt & C)
Try to fold integer comparisons with a constant operand: icmp Pred X, C where X is some kind of instruction and C is AllowPoison.
TODO: Move more folds which allow poison to this function.
Definition at line 3961 of file InstCombineCompares.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), and II.
Referenced by foldICmpInstWithConstant().
foldICmpInstWithConstantNotInt()
Instruction * InstCombinerImpl::foldICmpInstWithConstantNotInt (ICmpInst & Cmp)
Handle icmp with constant (but not simple integer constant) RHS.
Definition at line 4299 of file InstCombineCompares.cpp.
References llvm::cast(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldCmpLoadFromIndexedGlobal(), GEP, llvm::Constant::getNullValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), I, llvm::Constant::isNullValue(), and Op0.
Referenced by visitICmpInst().
foldICmpIntrinsicWithConstant()
Instruction * InstCombinerImpl::foldICmpIntrinsicWithConstant (ICmpInst & ICI, IntrinsicInst * II, const APInt & C)
Fold an icmp with LLVM intrinsic and constant operand: icmp Pred II, C.
Definition at line 4188 of file InstCombineCompares.cpp.
References llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::CmpInst::Create(), foldCtpopPow2Test(), foldICmpEqIntrinsicWithConstant(), foldICmpOfCmpIntrinsicWithConstant(), foldICmpUSubSatOrUAddSatWithConstant(), llvm::Constant::getAllOnesValue(), llvm::APInt::getLowBitsSet(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, II, llvm::CmpInst::isSigned(), llvm::InstCombiner::SQ, and X.
Referenced by foldICmpInstWithConstant(), and foldICmpWithTrunc().
foldICmpMulConstant()
Instruction * InstCombinerImpl::foldICmpMulConstant (ICmpInst & Cmp, BinaryOperator * Mul, const APInt & C)
Fold icmp (mul X, Y), C.
Definition at line 2182 of file InstCombineCompares.cpp.
References assert(), llvm::CallingConv::C, llvm::APInt::DOWN, llvm::Constant::getNullValue(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APInt::isAllOnes(), llvm::APInt::isNegative(), llvm::CmpInst::isSigned(), isSignTest(), llvm::CmpInst::isUnsigned(), llvm::APInt::isZero(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), Mul, llvm::APIntOps::RoundingSDiv(), llvm::APIntOps::RoundingUDiv(), llvm::APInt::UP, and X.
Referenced by foldICmpBinOpWithConstant().
foldICmpOrConstant()
Instruction * InstCombinerImpl::foldICmpOrConstant (ICmpInst & Cmp, BinaryOperator * Or, const APInt & C)
Fold icmp (or X, Y), C.
Definition at line 2081 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::BinaryOperator::Create(), foldICmpOrXorSubChain(), llvm::CmpInst::getFlippedStrictnessPredicate(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::isSignBitCheck(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_Signum(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, llvm::InstCombiner::replaceInstUsesWith(), llvm::APInt::sge(), llvm::APInt::sgt(), and X.
Referenced by foldICmpBinOpWithConstant().
foldICmpSelectConstant()
Instruction * InstCombinerImpl::foldICmpSelectConstant (ICmpInst & Cmp, SelectInst * Select, ConstantInt * C)
Definition at line 3352 of file InstCombineCompares.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::ICmpInst::compare(), Cond, llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, matchThreeWayIntCompare(), llvm::InstCombiner::replaceInstUsesWith(), and Select.
Referenced by foldICmpInstWithConstant().
foldICmpShlConstant()
Instruction * InstCombinerImpl::foldICmpShlConstant (ICmpInst & Cmp, BinaryOperator * Shl, const APInt & C)
Fold icmp (shl X, Y), C.
Definition at line 2323 of file InstCombineCompares.cpp.
References llvm::APInt::ashr(), assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::APInt::countr_zero(), foldICmpShlConstConst(), foldICmpShlLHSC(), llvm::Type::getContext(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getWithNewBitWidth(), llvm::APInt::getZExtValue(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::isSignBitCheck(), llvm::CmpInst::isStrictPredicate(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::APInt::trunc(), llvm::APInt::uge(), and X.
Referenced by foldICmpBinOpWithConstant().
foldICmpShlConstConst()
Instruction * InstCombinerImpl::foldICmpShlConstConst (ICmpInst & I, Value * ShAmt, const APInt & C1, const APInt & C2)
Handle "(icmp eq/ne (shl AP2, A), AP1)" -> (icmp eq/ne A, TrailingZeros(AP1) - TrailingZeros(AP2)).
Definition at line 1016 of file InstCombineCompares.cpp.
References A(), assert(), llvm::APInt::countr_zero(), llvm::APInt::getBitWidth(), llvm::CmpInst::getInversePredicate(), llvm::Constant::getNullValue(), I, llvm::APInt::isZero(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::APInt::shl().
Referenced by foldICmpShlConstant().
foldICmpShrConstant()
Instruction * InstCombinerImpl::foldICmpShrConstant (ICmpInst & Cmp, BinaryOperator * Shr, const APInt & C)
Fold icmp ({al}shr X, Y), C.
Definition at line 2503 of file InstCombineCompares.cpp.
References llvm::APInt::ashr(), assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::APInt::countl_zero(), llvm::countl_zero(), foldICmpShrConstConst(), llvm::Constant::getAllOnesValue(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLimitedValue(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::Instruction::isExact(), llvm::APInt::isNegative(), llvm::APInt::isPowerOf2(), llvm::isSignBitCheck(), llvm::APInt::lshr(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::APInt::uge(), and X.
Referenced by foldICmpBinOpWithConstant().
foldICmpShrConstConst()
Instruction * InstCombinerImpl::foldICmpShrConstConst (ICmpInst & I, Value * ShAmt, const APInt & C1, const APInt & C2)
Handle "(icmp eq/ne (ashr/lshr AP2, A), AP1)" -> (icmp eq/ne A, Log2(AP2/AP1)) -> (icmp eq/ne A, Log2(AP2) - Log2(AP1)).
Definition at line 957 of file InstCombineCompares.cpp.
References A(), llvm::APInt::ashr(), assert(), llvm::APInt::countl_one(), llvm::APInt::countl_zero(), llvm::CmpInst::getInversePredicate(), llvm::Constant::getNullValue(), I, llvm::isa(), llvm::APInt::isAllOnes(), llvm::APInt::isNegative(), llvm::APInt::isPowerOf2(), llvm::APInt::isZero(), llvm::APInt::logBase2(), llvm::APInt::lshr(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::APInt::sgt().
Referenced by foldICmpShrConstant().
foldICmpSRemConstant()
Instruction * InstCombinerImpl::foldICmpSRemConstant (ICmpInst & Cmp, BinaryOperator * UDiv, const APInt & C)
Definition at line 2657 of file InstCombineCompares.cpp.
References llvm::APInt::abs(), assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::APInt::flipAllBits(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::APInt::getSignMask(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::APInt::isZero(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::match(), and llvm::APInt::uge().
Referenced by foldICmpBinOpWithConstant().
foldICmpSubConstant()
Instruction * InstCombinerImpl::foldICmpSubConstant (ICmpInst & Cmp, BinaryOperator * Sub, const APInt & C)
Fold icmp (sub X, Y), C.
Definition at line 2954 of file InstCombineCompares.cpp.
References llvm::Add, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::ConstantExpr::getSub(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::match(), llvm::none_of(), llvm::Sub, subWithOverflow(), X, and Y.
Referenced by foldICmpBinOpWithConstant().
foldICmpTruncConstant()
Instruction * InstCombinerImpl::foldICmpTruncConstant (ICmpInst & Cmp, TruncInst * Trunc, const APInt & C)
Fold icmp (trunc X), C.
Definition at line 1442 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::InstCombiner::computeKnownBits(), llvm::Constant::getAllOnesValue(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::TruncInst::hasNoSignedWrap(), llvm::TruncInst::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::isSignBitCheck(), llvm::APInt::logBase2(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Signum(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::KnownBits::One, X, Y, and llvm::KnownBits::Zero.
Referenced by foldICmpInstWithConstant().
foldICmpTruncWithTruncOrExt()
Instruction * InstCombinerImpl::foldICmpTruncWithTruncOrExt (ICmpInst & Cmp, const SimplifyQuery & Q)
Fold icmp (trunc nuw/nsw X), (trunc nuw/nsw Y).
Fold icmp (trunc nuw/nsw X), (zext/sext Y).
Definition at line 1533 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), llvm::Type::getScalarSizeInBits(), llvm::isa(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_NSWTrunc(), llvm::PatternMatch::m_NUWTrunc(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), llvm::TruncInst::NoSignedWrap, llvm::TruncInst::NoUnsignedWrap, std::swap(), X, and Y.
Referenced by visitICmpInst().
foldICmpUDivConstant()
Instruction * InstCombinerImpl::foldICmpUDivConstant (ICmpInst & Cmp, BinaryOperator * UDiv, const APInt & C)
Fold icmp (udiv X, Y), C.
Definition at line 2739 of file InstCombineCompares.cpp.
References assert(), llvm::CallingConv::C, llvm::User::getOperand(), llvm::Value::getType(), llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::APInt::udiv(), X, and Y.
Referenced by foldICmpBinOpWithConstant().
foldICmpUsingBoolRange()
Instruction * InstCombinerImpl::foldICmpUsingBoolRange (ICmpInst & I)
If one operand of an icmp is effectively a bool (value range of {0,1}), then try to reduce patterns based on that limit.
Definition at line 7113 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::BinaryOperator::Create(), llvm::CmpInst::Create(), llvm::ConstantInt::getBool(), llvm::Constant::getNullValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::ConstantInt::getSigned(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Instruction(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), X, and Y.
Referenced by visitICmpInst().
foldICmpUsingKnownBits()
Instruction * InstCombinerImpl::foldICmpUsingKnownBits (ICmpInst & Cmp)
Try to fold the comparison based on range information we can get by checking whether bits are known to be zero or one in the inputs.
Definition at line 6900 of file InstCombineCompares.cpp.
References A(), B(), llvm::BitWidth, llvm::APInt::ceilLogBase2(), llvm::ICmpInst::compare(), llvm::KnownBits::countMinTrailingZeros(), llvm::APInt::countr_zero(), llvm::InstCombiner::DL, llvm::SelectPatternResult::Flavor, llvm::APInt::getActiveBits(), llvm::APInt::getAllOnes(), llvm::ConstantInt::getBool(), llvm::KnownBits::getConstant(), getDemandedBitsLHSMask(), llvm::Constant::getIntegerValue(), llvm::CmpInst::getInversePredicate(), llvm::KnownBits::getMaxValue(), llvm::KnownBits::getMinValue(), llvm::Constant::getNullValue(), llvm::KnownBits::getSignedMaxValue(), llvm::KnownBits::getSignedMinValue(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::KnownBits::isConstant(), llvm::SelectPatternResult::isMinOrMax(), llvm::APInt::isNegative(), llvm::APInt::isPowerOf2(), llvm::KnownBits::isZero(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_MaxOrMin(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), llvm::KnownBits::One, Op0, llvm::InstCombiner::replaceInstUsesWith(), SimplifyDemandedBits(), llvm::InstCombiner::SQ, X, and llvm::KnownBits::Zero.
Referenced by visitICmpInst().
foldICmpWithCastOp()
Instruction * InstCombinerImpl::foldICmpWithCastOp (ICmpInst & ICmp)
Handle icmp (cast x), (cast or constant).
Definition at line 6442 of file InstCombineCompares.cpp.
References llvm::cast(), llvm::ConstantFoldConstant(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldICmpWithTrunc(), foldICmpWithZextOrSext(), llvm::ConstantExpr::getIntToPtr(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantExpr::getPtrToInt(), llvm::Value::getType(), and llvm::isa().
Referenced by visitICmpInst().
foldICmpWithClamp()
Instruction * InstCombinerImpl::foldICmpWithClamp (ICmpInst & I, Value * X, MinMaxIntrinsic * Min)
Match and fold patterns like: icmp eq/ne X, min(max(X, Lo), Hi) which represents a range check and can be repsented as a ConstantRange.
For icmp eq, build ConstantRange [Lo, Hi + 1) and convert to: (X - Lo) u< (Hi + 1 - Lo) For icmp ne, build ConstantRange [Hi + 1, Lo) and convert to: (X - (Hi + 1)) u< (Lo - (Hi + 1))
Definition at line 5798 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::ConstantRange::getEquivalentICmp(), llvm::MinMaxIntrinsic::getLHS(), llvm::ConstantRange::getNonEmpty(), llvm::MinMaxIntrinsic::getRHS(), llvm::Value::hasOneUse(), llvm::Hi, I, llvm::CmpInst::ICMP_EQ, llvm::ConstantRange::inverse(), llvm::MinMaxIntrinsic::isMin(), llvm::MinMaxIntrinsic::isSigned(), llvm::Lo, llvm::PatternMatch::m_APInt(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::match(), llvm::Offset, llvm::InstCombiner::replaceInstUsesWith(), and X.
Referenced by foldICmpCommutative().
foldICmpWithConstant()
Instruction * InstCombinerImpl::foldICmpWithConstant (ICmpInst & Cmp)
Fold icmp Pred X, C.
TODO: This code structure does not make sense. The saturating add fold should be moved to some other helper and extended as noted below (it is also possible that code has been made unnecessary - do we canonicalize IR to overflow/saturating intrinsics or not?).
Definition at line 1316 of file InstCombineCompares.cpp.
References A(), AbstractManglingParser< Derived, Alloc >::Ops, llvm::PHINode::addIncoming(), llvm::all_of(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldCompareInstOperands(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::CmpInst::ICMP_UGT, llvm::IsaPred, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, processUGT_ADDCST_ADD(), llvm::InstCombiner::replaceInstUsesWith(), tryFoldInstWithCtpopWithNot(), and llvm::zip().
Referenced by visitICmpInst().
foldICmpWithDominatingICmp()
Instruction * InstCombinerImpl::foldICmpWithDominatingICmp (ICmpInst & Cmp)
Canonicalize icmp instructions based on dominating conditions.
Definition at line 1366 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::InstCombiner::DC, llvm::ConstantRange::difference(), llvm::InstCombiner::DT, llvm::CmpInst::getInversePredicate(), llvm::ConstantRange::getSingleElement(), hasBranchUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ConstantRange::intersectWith(), llvm::ConstantRange::isEmptySet(), llvm::isSignBitCheck(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_MaxOrMin(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::ConstantRange::makeExactICmpRegion(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), X, and Y.
Referenced by visitICmpInst().
foldICmpWithMinMax()
Instruction * InstCombinerImpl::foldICmpWithMinMax (Instruction & I, MinMaxIntrinsic * MinMax, Value * Z, CmpPredicate Pred)
Fold icmp Pred min|max(X, Y), Z.
Definition at line 5645 of file InstCombineCompares.cpp.
References llvm::CmpInst::Create(), llvm::ConstantInt::getBool(), llvm::ConstantInt::getFalse(), llvm::ICmpInst::getFlippedSignednessPredicate(), llvm::CmpInst::getInversePredicate(), llvm::CmpInst::getNonStrictPredicate(), llvm::CmpInst::getStrictPredicate(), llvm::ConstantInt::getTrue(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isKnownNonNegative(), llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), llvm::simplifyICmpInst(), llvm::InstCombiner::SQ, std::swap(), X, and Y.
Referenced by foldICmpCommutative().
foldICmpWithTrunc()
Instruction * InstCombinerImpl::foldICmpWithTrunc (ICmpInst & Cmp)
Definition at line 6286 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::decomposeBitTestICmp(), llvm::dyn_cast(), foldICmpIntrinsicWithConstant(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), I, II, llvm::Log2_32(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, and X.
Referenced by foldICmpWithCastOp().
foldICmpWithZero()
Instruction * InstCombinerImpl::foldICmpWithZero (ICmpInst & Cmp)
Definition at line 1197 of file InstCombineCompares.cpp.
References A(), B(), llvm::cast(), llvm::InstCombiner::computeKnownBits(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMaxTrailingZeros(), llvm::KnownBits::countMinPopulation(), foldIRemByPowerOfTwoToBitTest(), llvm::Constant::getNullValue(), llvm::CmpInst::ICMP_SGT, llvm::ICmpInst::isEquality(), llvm::isKnownNonZero(), llvm::isKnownPositive(), llvm::APInt::isZero(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::KnownBits::One, llvm::InstCombiner::SQ, llvm::stripNullTest(), X, and Y.
Referenced by visitICmpInst().
foldICmpWithZextOrSext()
Instruction * InstCombinerImpl::foldICmpWithZextOrSext (ICmpInst & ICmp)
Definition at line 6329 of file InstCombineCompares.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::Constant::getAllOnesValue(), llvm::getLosslessInvCast(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::ICmpInst::getUnsignedPredicate(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::CmpInst::isSigned(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), X, and Y.
Referenced by foldICmpWithCastOp().
foldICmpXorConstant()
Instruction * InstCombinerImpl::foldICmpXorConstant (ICmpInst & Cmp, BinaryOperator * Xor, const APInt & C)
Fold icmp (xor X, Y), C.
Definition at line 1592 of file InstCombineCompares.cpp.
References llvm::CallingConv::C, foldICmpXorShiftConst(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), I, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::APInt::isMaxSignedValue(), llvm::APInt::isNegative(), llvm::isSignBitCheck(), llvm::APInt::isSignMask(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceOperand(), X, llvm::Xor, and Y.
Referenced by foldICmpBinOpWithConstant().
foldICmpXorShiftConst()
Instruction * InstCombinerImpl::foldICmpXorShiftConst (ICmpInst & Cmp, BinaryOperator * Xor, const APInt & C)
For power-of-2 C: ((X s>> ShiftC) ^ X) u< C --> (X + C) u< (C << 1) ((X s>> ShiftC) ^ X) u> (C - 1) --> (X + C) u> ((C << 1) - 1).
Definition at line 1664 of file InstCombineCompares.cpp.
References llvm::Add, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::APInt::getLimitedValue(), llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::APInt::isMinSignedValue(), llvm::APInt::isPowerOf2(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Deferred(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), X, and llvm::Xor.
Referenced by foldICmpXorConstant().
foldIntegerTypedPHI()
bool InstCombinerImpl::foldIntegerTypedPHI (PHINode & PN)
If an integer typed PHI has only one use which is an IntToPtr operation, replace the PHI with an existing pointer typed PHI if it exists.
Otherwise insert a new pointer typed PHI and replace the original one.
Definition at line 135 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::all_of(), llvm::any_of(), assert(), llvm::PHINode::blocks(), llvm::cast(), llvm::PHINode::Create(), llvm::CastInst::CreateBitOrPointerCast(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::BasicBlock::end(), eraseInstFromFunction(), llvm::BasicBlock::getFirstInsertionPt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::BasicBlock::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::PHINode::incoming_values(), llvm::InstCombiner::InsertNewInstBefore(), llvm::isa(), llvm::Type::isIntegerTy(), MaxNumPhis, llvm::InstCombiner::replaceInstUsesWith(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Instruction::user_back(), llvm::Value::users(), and llvm::zip().
Referenced by visitPHINode().
foldIRemByPowerOfTwoToBitTest()
Instruction * InstCombinerImpl::foldIRemByPowerOfTwoToBitTest (ICmpInst & I)
If we have: icmp eq/ne (urem/srem x, y), 0 iff y is a power-of-two, we can replace this with a bit test: icmp eq/ne (and x, (add y, -1)), 0.
Definition at line 1147 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::CmpInst::Create(), llvm::Constant::getAllOnesValue(), I, llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_IRem(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::Masked, llvm::PatternMatch::match(), X, and Y.
Referenced by foldICmpWithZero().
foldIsMultipleOfAPowerOfTwo()
Instruction * InstCombinerImpl::foldIsMultipleOfAPowerOfTwo (ICmpInst & Cmp)
Fold icmp eq (num + mask) & ~mask, num to icmp eq (and num, mask), 0 Where mask is a low bit mask.
Definition at line 1286 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LowBitMask(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by visitICmpInst().
foldItoFPtoI()
Instruction * InstCombinerImpl::foldItoFPtoI (CastInst & FI)
fpto{s/u}i({u/s}itofp(X)) --> X or zext(X) or sext(X) or trunc(X) This is safe if the intermediate type has enough bits in its mantissa to accurately represent all values of X.
For example, this won't work with i64 -> float -> i64.
Definition at line 2253 of file InstCombineCasts.cpp.
References assert(), llvm::cast(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::isa(), isKnownExactCastIntToFP(), llvm::InstCombiner::replaceInstUsesWith(), and X.
Referenced by visitFPToSI(), visitFPToUI(), and ~InstCombinerImpl().
foldMultiplicationOverflowCheck()
Value * InstCombinerImpl::foldMultiplicationOverflowCheck (ICmpInst & I)
Fold (-1 u/ x) u< y ((x * y) ?
/ x) != y to @llvm.?mul.with.overflow(x, y) plus extraction of overflow bit Note that the comparison is commutative, while inverted (u>=, ==) predicate will mean that we are looking for the opposite answer.
Definition at line 4876 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, eraseInstFromFunction(), llvm::Instruction::getOpcode(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_IDiv(), llvm::PatternMatch::m_Instruction(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Mul, llvm::InstCombiner::replaceInstUsesWith(), X, and Y.
Referenced by foldICmpBinOp().
foldOpIntoPhi()
Instruction * InstCombinerImpl::foldOpIntoPhi (Instruction & I, PHINode * PN, bool AllowMultipleUses = false)
Given a binary operator, cast instruction, or select which has a PHI node as operand #0, see if we can fold the instruction into the PHI (which is only possible if all operands to the PHI are constants).
Definition at line 1923 of file InstructionCombining.cpp.
References llvm::PHINode::addIncoming(), llvm::cast(), llvm::PHINode::Create(), llvm::InstCombiner::DL, llvm::Instruction::dropUBImplyingAttrsAndMetadata(), llvm::InstCombiner::DT, llvm::dyn_cast(), eraseInstFromFunction(), llvm::Instruction::getDebugLoc(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::PHINode::getNumIncomingValues(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::hasOneUse(), llvm::Value::hasOneUser(), llvm::Value::hasUseList(), I, llvm::CmpInst::ICMP_EQ, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::InstCombiner::InsertNewInstBefore(), llvm::isa(), llvm::InstCombiner::isBackEdge(), llvm::BranchInst::isUnconditional(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::User::operands(), OpIndex, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::replaceAllDbgUsesWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setDebugLoc(), simplifyInstructionWithPHI(), llvm::InstCombiner::SQ, llvm::Value::takeName(), and llvm::Value::users().
Referenced by commonCastTransforms(), commonIRemTransforms(), foldBinOpIntoSelectOrPhi(), visitCallInst(), visitExtractValueInst(), visitFCmpInst(), visitFreeze(), visitICmpInst(), visitSelectInst(), visitShuffleVectorInst(), and visitSub().
FoldOpIntoSelect()
Instruction * InstCombinerImpl::FoldOpIntoSelect (Instruction & Op, SelectInst * SI, bool FoldWithMultiUse = false, bool SimplifyBothArms = false)
Given an instruction with a select as one operand and a constant as the other operand, try to fold the binary operator into the select arguments.
This also works for Cast instructions, which obviously do not have a second operand.
Definition at line 1782 of file InstructionCombining.cpp.
References llvm::SelectInst::Create(), llvm::dyn_cast(), foldOperationIntoSelectOperand(), llvm::isa(), Op0, and simplifyOperationIntoSelectOperand().
Referenced by commonCastTransforms(), commonIDivRemTransforms(), commonIRemTransforms(), commonShiftTransforms(), foldBinOpIntoSelectOrPhi(), visitCallInst(), visitExtractElementInst(), visitExtractValueInst(), visitFCmpInst(), visitFDiv(), visitFSub(), visitShuffleVectorInst(), and visitSub().
foldPHIArgBinOpIntoPHI()
Instruction * InstCombinerImpl::foldPHIArgBinOpIntoPHI (PHINode & PN)
If we have something like phi [add (a,b), add(a,c)] and if a/b/c and the adds all have a single user, turn this into a phi and a single binop.
Definition at line 440 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::Instruction::andIRFlags(), assert(), llvm::PHINode::blocks(), llvm::cast(), llvm::Instruction::copyIRFlags(), llvm::BinaryOperator::Create(), llvm::CmpInst::Create(), llvm::PHINode::Create(), llvm::drop_begin(), llvm::dyn_cast(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::BinaryOperator::getOpcode(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), I, llvm::PHINode::incoming_values(), llvm::InstCombiner::InsertNewInstBefore(), llvm::isa(), Opc, PHIArgMergedDebugLoc(), and llvm::zip().
Referenced by foldPHIArgOpIntoPHI().
foldPHIArgExtractValueInstructionIntoPHI()
Instruction * InstCombinerImpl::foldPHIArgExtractValueInstructionIntoPHI (PHINode & PN)
If we have something like phi [extractvalue(a,0), extractvalue(b,0)], turn this into a phi[a,b] and a single extractvalue.
Definition at line 404 of file InstCombinePHI.cpp.
References llvm::PHINode::blocks(), llvm::cast(), llvm::ExtractValueInst::Create(), llvm::PHINode::Create(), llvm::drop_begin(), llvm::dyn_cast(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), I, llvm::PHINode::incoming_values(), llvm::InstCombiner::InsertNewInstBefore(), PHIArgMergedDebugLoc(), and llvm::zip().
Referenced by foldPHIArgOpIntoPHI().
foldPHIArgGEPIntoPHI()
Instruction * InstCombinerImpl::foldPHIArgGEPIntoPHI (PHINode & PN)
Definition at line 535 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::sampleprof::Base, llvm::PHINode::blocks(), llvm::cast(), llvm::GetElementPtrInst::Create(), llvm::PHINode::Create(), llvm::drop_begin(), llvm::dyn_cast(), GEP, llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::GetElementPtrInst::getNoWrapFlags(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::GetElementPtrInst::getSourceElementType(), llvm::Value::getType(), I, llvm::PHINode::incoming_values(), llvm::InstCombiner::InsertNewInstBefore(), llvm::isa(), llvm::User::op_begin(), llvm::User::op_end(), PHIArgMergedDebugLoc(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::zip().
Referenced by foldPHIArgOpIntoPHI().
foldPHIArgInsertValueInstructionIntoPHI()
Instruction * InstCombinerImpl::foldPHIArgInsertValueInstructionIntoPHI (PHINode & PN)
If we have something like phi [insertvalue(a,b,0), insertvalue(c,d,0)], turn this into a phi[a,c] and phi[b,d] and a single insertvalue.
Definition at line 364 of file InstCombinePHI.cpp.
References llvm::PHINode::blocks(), llvm::cast(), llvm::InsertValueInst::Create(), llvm::PHINode::Create(), llvm::drop_begin(), llvm::dyn_cast(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), I, llvm::PHINode::incoming_values(), llvm::InstCombiner::InsertNewInstBefore(), OpIdx, PHIArgMergedDebugLoc(), and llvm::zip().
Referenced by foldPHIArgOpIntoPHI().
foldPHIArgIntToPtrToPHI()
Instruction * InstCombinerImpl::foldPHIArgIntToPtrToPHI (PHINode & PN)
Definition at line 340 of file InstCombinePHI.cpp.
References llvm::all_of(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::IsaPred, llvm::InstCombiner::replaceOperand(), and llvm::Value::users().
Referenced by visitPHINode().
foldPHIArgLoadIntoPHI()
Instruction * InstCombinerImpl::foldPHIArgLoadIntoPHI (PHINode & PN)
Definition at line 698 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::PHINode::blocks(), llvm::canReplaceOperandWithVariable(), llvm::cast(), llvm::combineMetadataForCSE(), llvm::Instruction::copyMetadata(), llvm::PHINode::Create(), llvm::drop_begin(), llvm::dyn_cast(), llvm::LoadInst::getAlign(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::LoadInst::getPointerAddressSpace(), llvm::Value::getType(), llvm::Value::hasOneUser(), llvm::PHINode::incoming_values(), llvm::InstCombiner::InsertNewInstBefore(), llvm::Instruction::isAtomic(), isSafeAndProfitableToSinkLoad(), llvm::LoadInst::isVolatile(), PHIArgMergedDebugLoc(), llvm::User::setOperand(), and llvm::zip().
Referenced by foldPHIArgOpIntoPHI().
foldPHIArgOpIntoPHI()
Instruction * InstCombinerImpl::foldPHIArgOpIntoPHI (PHINode & PN)
Try to rotate an operation below a PHI node, using PHI nodes for its operands.
If all operands to a PHI node are the same "unary" operator and they all are only used by the PHI, PHI together their inputs, and do the operation once, to the result of the PHI.
Definition at line 885 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::PHINode::blocks(), llvm::cast(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::CmpInst::Create(), llvm::PHINode::Create(), llvm::drop_begin(), llvm::dyn_cast(), foldPHIArgBinOpIntoPHI(), foldPHIArgExtractValueInstructionIntoPHI(), foldPHIArgGEPIntoPHI(), foldPHIArgInsertValueInstructionIntoPHI(), foldPHIArgLoadIntoPHI(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::CmpInst::getOpcode(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), I, llvm::PHINode::incoming_values(), llvm::InstCombiner::InsertNewInstBefore(), llvm::isa(), llvm::Type::isIntegerTy(), PHIArgMergedDebugLoc(), and llvm::zip().
Referenced by visitPHINode().
foldPHIArgZextsIntoPHI()
Instruction * InstCombinerImpl::foldPHIArgZextsIntoPHI (PHINode & Phi)
TODO: This function could handle other cast types, but then it might require special-casing a cast from the 'i1' type.
See the comment in FoldPHIArgOpIntoPHI() about pessimizing illegal integer types.
Definition at line 804 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::CallingConv::C, llvm::PHINode::Create(), llvm::CastInst::CreateZExtOrBitCast(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::DebugLoc::getDropped(), llvm::getLosslessUnsignedTrunc(), I, llvm::InstCombiner::InsertNewInstBefore(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by visitPHINode().
foldPowiReassoc()
Instruction * InstCombinerImpl::foldPowiReassoc (BinaryOperator & I)
Definition at line 624 of file InstCombineMulDivRem.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::BinaryOperator::CreateFDivFMF(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), I, InstCombinerImpl(), llvm::PatternMatch::m_AllowReassoc(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), X, and Y.
Referenced by foldFMulReassoc(), visitFDiv(), and ~InstCombinerImpl().
foldPtrToIntOrAddrOfGEP()
Value * InstCombinerImpl::foldPtrToIntOrAddrOfGEP (Type * IntTy, Value * Ptr)
Definition at line 2387 of file InstCombineCasts.cpp.
References llvm::InstCombiner::Builder, llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), GEP, llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::isa(), llvm::PatternMatch::m_IntToPtr(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::reverse().
Referenced by visitPtrToAddr(), and visitPtrToInt().
foldReversedIntrinsicOperands()
Value * InstCombinerImpl::foldReversedIntrinsicOperands (IntrinsicInst * II)
If all arguments of the intrinsic are reverses, try to pull the reverse after the intrinsic.
Definition at line 1545 of file InstCombineCalls.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, II, llvm::isa(), llvm::isSplatValue(), llvm::isTriviallyVectorizable(), llvm::isVectorIntrinsicWithScalarOpAtArg(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VecReverse(), llvm::PatternMatch::match(), llvm::none_of(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and X.
Referenced by visitCallInst(), and ~InstCombinerImpl().
foldSelectEqualityTest()
Instruction * llvm::InstCombinerImpl::foldSelectEqualityTest (SelectInst & SI)
References A(), B(), llvm::CallingConv::C, foldSelectInstWithICmp(), foldSelectIntoOp(), foldSelectOpOp(), foldSelectValueEquivalence(), foldSelectWithConstOpToBinOp(), and foldSPFofSPF().
Referenced by visitSelectInst().
foldSelectExtConst()
Instruction * InstCombinerImpl::foldSelectExtConst (SelectInst & Sel)
Definition at line 2503 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), Cond, llvm::CastInst::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::getLosslessInvCast(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::match(), std::swap(), and X.
Referenced by visitSelectInst().
foldSelectICmp()
Instruction * InstCombinerImpl::foldSelectICmp (CmpPredicate Pred, SelectInst * SI, Value * RHS, const ICmpInst & I)
Definition at line 4329 of file InstCombineCompares.cpp.
References llvm::InstCombiner::Builder, llvm::SelectInst::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), I, llvm::isa(), llvm::isImpliedCondition(), llvm::ConstantInt::isZero(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), replacedSelectWithOperand(), llvm::simplifyICmpInst(), and llvm::InstCombiner::SQ.
Referenced by foldICmpCommutative().
foldSelectInstWithICmp()
Instruction * InstCombinerImpl::foldSelectInstWithICmp (SelectInst & SI, ICmpInst * ICI)
Visit a SelectInst that has an ICmpInst as its first operand.
Definition at line 2207 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), foldAbsDiff(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), foldSelectICmpAndAnd(), foldSelectICmpAndZeroShl(), foldSelectICmpEq(), foldSelectICmpLshrAshr(), foldSelectICmpMinMax(), foldSelectWithConstOpToBinOp(), llvm::Value::getName(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_SGT, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), and llvm::InstCombiner::SQ.
Referenced by foldSelectEqualityTest(), and visitSelectInst().
foldSelectIntoOp()
Instruction * InstCombinerImpl::foldSelectIntoOp (SelectInst & SI, Value * TrueVal, Value * FalseVal)
Try to fold the select into one of the operands to allow further optimization.
Definition at line 503 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), computeKnownFPClass(), llvm::Instruction::copyIRFlags(), llvm::BinaryOperator::Create(), llvm::dyn_cast(), llvm::fcNan, llvm::ConstantExpr::getBinOpIdentity(), getSelectFoldableOperands(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoNaNs(), llvm::Instruction::hasNoSignedZeros(), llvm::isa(), llvm::isKnownNeverNaN(), isSelect01(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), llvm::Instruction::setHasNoInfs(), llvm::Instruction::setHasNoNaNs(), llvm::Instruction::setHasNoSignedZeros(), llvm::FastMathFlags::setNoInfs(), and llvm::Value::takeName().
Referenced by foldSelectEqualityTest(), and visitSelectInst().
foldSelectOfBools()
Instruction * InstCombinerImpl::foldSelectOfBools (SelectInst & SI)
Definition at line 3437 of file InstCombineSelect.cpp.
References A(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNot(), D(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::ConstantInt::getFalse(), llvm::InstCombiner::getFreelyInverted(), llvm::Value::getName(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::Value::hasOneUse(), impliesPoisonOrCond(), llvm::InstCombiner::InsertNewInstBefore(), llvm::isa(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::isImpliedCondition(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_LogicalAnd(), llvm::PatternMatch::m_c_LogicalOr(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_ConstantExpr(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), nullptr, llvm::ProfcheckDisableMetadataFixes, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::InstCombiner::replaceUse(), std::swap(), llvm::Instruction::swapProfMetadata(), and Y.
Referenced by visitSelectInst().
foldSelectOpOp()
Instruction * InstCombinerImpl::foldSelectOpOp (SelectInst & SI, Instruction * TI, Instruction * FI)
We have (select c, TI, FI), and we know that TI and FI have the same opcode.
Definition at line 252 of file InstCombineSelect.cpp.
References llvm::Instruction::andIRFlags(), assert(), llvm::InstCombiner::Builder, llvm::cast(), Cond, llvm::Instruction::copyIRFlags(), llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::GetElementPtrInst::Create(), llvm::dyn_cast(), llvm::FPMathOperator::getFastMathFlags(), llvm::Instruction::getFastMathFlags(), llvm::CmpPredicate::getMatching(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::ICmpInst::getSwappedCmpPredicate(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::isa(), llvm::Instruction::isCast(), llvm::Instruction::isCommutative(), llvm::ICmpInst::isEquality(), llvm::isGuaranteedNotToBePoison(), llvm::ICmpInst::isRelational(), llvm::Instruction::isSameOperationAs(), llvm::Type::isVectorTy(), llvm_unreachable, llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_MaxOrMin(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, P, llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setFastMathFlags(), TII, X, and Y.
Referenced by foldSelectEqualityTest(), and visitSelectInst().
foldSelectShuffle()
Instruction * InstCombinerImpl::foldSelectShuffle (ShuffleVectorInst & Shuf)
Try to fold shuffles that are the equivalent of a vector select.
Definition at line 2351 of file InstCombineVectorOps.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::cast(), llvm::ShuffleVectorInst::commute(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), getAlternateBinop(), llvm::ShuffleVectorInst::getMaskValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::InstCombiner::getSafeVectorConstantForBinop(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ConstantExpr::getShuffleVector(), llvm::InstCombiner::getSimplifyQuery(), llvm::ShuffleVectorInst::getType(), llvm::Value::hasOneUse(), I, llvm::is_contained(), llvm::isa(), llvm::Instruction::isIntDivRem(), llvm::ShuffleVectorInst::isSelect(), llvm::Instruction::isShift(), llvm::MIPatternMatch::m_BinOp(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Constant(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::PoisonMaskElem, llvm::InstCombiner::replaceInstUsesWith(), X, and Y.
Referenced by visitShuffleVectorInst().
foldSelectToCmp()
Instruction * InstCombinerImpl::foldSelectToCmp (SelectInst & SI)
Definition at line 3909 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::dyn_cast(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::ICmpInst::getInverseCmpPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::isa(), llvm::APInt::isAllOnes(), llvm::ICmpInst::isGT(), llvm::ICmpInst::isLT(), llvm::CmpInst::isNonStrictPredicate(), llvm::APInt::isOne(), llvm::CmpInst::isSigned(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), and std::swap().
Referenced by visitSelectInst().
foldSelectValueEquivalence()
Instruction * InstCombinerImpl::foldSelectValueEquivalence (SelectInst & Sel, CmpInst & Cmp)
Fold the following code sequence:
      int a = ctlz(x & -x);
//    x ? 31 - a : a;
//    // or
//    x ? 31 - a : 32;
    \code
    into:
      cttz(x) */
static Instruction *foldSelectCtlzToCttz(ICmpInst *ICI, Value *TrueVal,
                                         Value *FalseVal,
                                         InstCombiner::BuilderTy &Builder) {
  unsigned BitWidth = TrueVal->getType()->getScalarSizeInBits();
  if (!ICI->isEquality() || !match(ICI->getOperand(1), m_Zero()))
    return nullptr;
  if (ICI->getPredicate() == ICmpInst::ICMP_NE)
    std::swap(TrueVal, FalseVal);
  Value *Ctlz;
  if (!match(FalseVal,
             m_Xor(m_Value(Ctlz), m_SpecificInt(BitWidth - 1))))
    return nullptr;
  if (!match(Ctlz, m_Intrinsic<Intrinsic::ctlz>()))
    return nullptr;
  if (TrueVal != Ctlz && !match(TrueVal, m_SpecificInt(BitWidth)))
    return nullptr;
  Value *X = ICI->getOperand(0);
  auto *II = cast<IntrinsicInst>(Ctlz);
  if (!match(II->getOperand(0), m_c_And(m_Specific(X), m_Neg(m_Specific(X)))))
    return nullptr;
  Function *F = Intrinsic::getOrInsertDeclaration(
      II->getModule(), Intrinsic::cttz, II->getType());
  return CallInst::Create(F, {X, II->getArgOperand(1)});
}
/** Attempt to fold a cttz/ctlz followed by a icmp plus select into a single
    call to cttz/ctlz with flag 'is_zero_poison' cleared.
    For example, we can fold the following code sequence:
    \code
      %0 = tail call i32 @llvm.cttz.i32(i32 %x, i1 true)
      %1 = icmp ne i32 %x, 0
      %2 = select i1 %1, i32 %0, i32 32
    \code
    into:
      %0 = tail call i32 @llvm.cttz.i32(i32 %x, i1 false) */
static Value *foldSelectCttzCtlz(ICmpInst *ICI, Value *TrueVal, Value *FalseVal,
                                 InstCombinerImpl &IC) {
  ICmpInst::Predicate Pred = ICI->getPredicate();
  Value *CmpLHS = ICI->getOperand(0);
  Value *CmpRHS = ICI->getOperand(1);
Check if the select condition compares a value for equality.
  if (!ICI->isEquality())
    return nullptr;
  Value *SelectArg = FalseVal;
  Value *ValueOnZero = TrueVal;
  if (Pred == ICmpInst::ICMP_NE)
    std::swap(SelectArg, ValueOnZero);
Skip zero extend/truncate.
  Value *Count = nullptr;
  if (!match(SelectArg, m_ZExt(m_Value(Count))) &&
      !match(SelectArg, m_Trunc(m_Value(Count))))
    Count = SelectArg;
Check that 'Count' is a call to intrinsic cttz/ctlz. Also check that the
input to the cttz/ctlz is used as LHS for the compare instruction.
  Value *X;
  if (!match(Count, m_Intrinsic<Intrinsic::cttz>(m_Value(X))) &&
      !match(Count, m_Intrinsic<Intrinsic::ctlz>(m_Value(X))))
    return nullptr;
(X == 0) ? BitWidth : ctz(X)
(X == -1) ? BitWidth : ctz(~X)
(X == Y) ? BitWidth : ctz(X ^ Y)
  if ((X != CmpLHS || !match(CmpRHS, m_Zero())) &&
      (!match(X, m_Not(m_Specific(CmpLHS))) || !match(CmpRHS, m_AllOnes())) &&
      !match(X, m_c_Xor(m_Specific(CmpLHS), m_Specific(CmpRHS))))
    return nullptr;
  IntrinsicInst *II = cast<IntrinsicInst>(Count);
Check if the value propagated on zero is a constant number equal to the
sizeof in bits of 'Count'.
  unsigned SizeOfInBits = Count->getType()->getScalarSizeInBits();
  if (match(ValueOnZero, m_SpecificInt(SizeOfInBits))) {
Explicitly clear the 'is_zero_poison' flag. It's always valid to go from
true to false on this flag, so we can replace it for all users.
    II->setArgOperand(1, ConstantInt::getFalse(II->getContext()));
A range annotation on the intrinsic may no longer be valid.
    II->dropPoisonGeneratingAnnotations();
    IC.addToWorklist(II);
    return SelectArg;
  }
The ValueOnZero is not the bitwidth. But if the cttz/ctlz (and optional
zext/trunc) have one use (ending at the select), the cttz/ctlz result will
not be used if the input is zero. Relax to 'zero is poison' for that case.
  if (II->hasOneUse() && SelectArg->hasOneUse() &&
      !match(II->getArgOperand(1), m_One())) {
    II->setArgOperand(1, ConstantInt::getTrue(II->getContext()));
noundef attribute on the intrinsic may no longer be valid.
    II->dropUBImplyingAttrsAndMetadata();
    IC.addToWorklist(II);
  }
  return nullptr;
}
static Value *canonicalizeSPF(ICmpInst &Cmp, Value *TrueVal, Value *FalseVal,
                              InstCombinerImpl &IC) {
  Value *LHS, *RHS;
TODO: What to do with pointer min/max patterns?
  if (!TrueVal->getType()->isIntOrIntVectorTy())
    return nullptr;
  SelectPatternFlavor SPF =
      matchDecomposedSelectPattern(&Cmp, TrueVal, FalseVal, LHS, RHS).Flavor;
  if (SPF == SelectPatternFlavor::SPF_ABS ||
      SPF == SelectPatternFlavor::SPF_NABS) {
    if (!Cmp.hasOneUse() && !RHS->hasOneUse())
      return nullptr; // TODO: Relax this restriction.
Note that NSW flag can only be propagated for normal, non-negated abs!
    bool IntMinIsPoison = SPF == SelectPatternFlavor::SPF_ABS &&
                          match(RHS, m_NSWNeg(m_Specific(LHS)));
    Constant *IntMinIsPoisonC =
        ConstantInt::get(Type::getInt1Ty(Cmp.getContext()), IntMinIsPoison);
    Value *Abs =
        IC.Builder.CreateBinaryIntrinsic(Intrinsic::abs, LHS, IntMinIsPoisonC);
    if (SPF == SelectPatternFlavor::SPF_NABS)
      return IC.Builder.CreateNeg(Abs); // Always without NSW flag!
    return Abs;
  }
  if (SelectPatternResult::isMinOrMax(SPF)) {
    Intrinsic::ID IntrinsicID = getMinMaxIntrinsic(SPF);
    return IC.Builder.CreateBinaryIntrinsic(IntrinsicID, LHS, RHS);
  }
  return nullptr;
}
bool InstCombinerImpl::replaceInInstruction(Value *V, Value *Old, Value *New,
                                            unsigned Depth) {
Conservatively limit replacement to two instructions upwards.
  if (Depth == 2)
    return false;
  assert(!isa<Constant>(Old) && "Only replace non-constant values");
  auto *I = dyn_cast<Instruction>(V);
  if (!I || !I->hasOneUse() ||
      !isSafeToSpeculativelyExecuteWithVariableReplaced(I))
    return false;
Forbid potentially lane-crossing instructions.
  if (Old->getType()->isVectorTy() && !isNotCrossLaneOperation(I))
    return false;
  bool Changed = false;
  for (Use &U : I->operands()) {
    if (U == Old) {
      replaceUse(U, New);
      Worklist.add(I);
      Changed = true;
    } else {
      Changed |= replaceInInstruction(U, Old, New, Depth + 1);
    }
  }
  return Changed;
}
/** If we have a select with an equality comparison, then we know the value in
    one of the arms of the select. See if substituting this value into an arm
    and simplifying the result yields the same value as the other arm.
    To make this transform safe, we must drop poison-generating flags
    (nsw, etc) if we simplified to a binop because the select may be guarding
    that poison from propagating. If the existing binop already had no
    poison-generating flags, then this transform can be done by instsimplify.
    Consider:
      %cmp = icmp eq i32 %x, 2147483647
      %add = add nsw i32 %x, 1
      %sel = select i1 %cmp, i32 -2147483648, i32 %add
    We can't replace %sel with %add unless we strip away the flags.
    TODO: Wrapping flags could be preserved in some cases with better analysis.
Definition at line 1503 of file InstCombineSelect.cpp.
References llvm::canReplacePointersIfEqual(), llvm::cast(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::SelectInst::getFalseValue(), llvm::SelectInst::getTrueValue(), I, llvm::is_contained(), llvm::isa(), llvm::isGuaranteedNotToBeUndef(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::match(), replaceInInstruction(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::simplifyWithOpReplaced(), llvm::InstCombiner::SQ, std::swap(), and llvm::InstCombiner::Worklist.
Referenced by foldSelectEqualityTest(), and visitSelectInst().
foldSelectWithConstOpToBinOp()
Value * InstCombinerImpl::foldSelectWithConstOpToBinOp (ICmpInst * Cmp, Value * TrueVal, Value * FalseVal)
Fold X Pred C1 ?
X BOp C2 : C1 BOp C2 to min/max(X, C1) BOp C2. This allows for better canonicalization.
Definition at line 2058 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), llvm::ConstantFoldBinaryIntrinsic(), llvm::ConstantFoldBinaryOpOperands(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::SelectPatternResult::Flavor, llvm::getFlippedStrictnessPredicateAndConstant(), llvm::CmpInst::getInversePredicate(), llvm::getMinMaxIntrinsic(), llvm::getSelectPattern(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), II, llvm::Instruction::isIntDivRem(), llvm::ICmpInst::isRelational(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_MaxOrMin(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), std::swap(), and X.
Referenced by foldSelectEqualityTest(), and foldSelectInstWithICmp().
FoldShiftByConstant()
Instruction * InstCombinerImpl::FoldShiftByConstant (Value * Op0, Constant * Op1, BinaryOperator & I)
Definition at line 784 of file InstCombineShifts.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, canEvaluateShifted(), canShiftBinOpWithConstantRHS(), llvm::cast(), Cond, llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::SelectInst::Create(), llvm::dbgs(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldBinOpIntoSelectOrPhi(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), getShiftedValue(), llvm::APInt::getZExtValue(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), I, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::isa(), llvm::Instruction::isExact(), llvm::APInt::isMinSignedValue(), llvm::APInt::isNegative(), llvm::APInt::isZero(), LLVM_DEBUG, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_ImmConstant(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::Value::takeName(), llvm::APInt::uge(), and X.
Referenced by commonShiftTransforms(), and ~InstCombinerImpl().
foldShuffledIntrinsicOperands()
Instruction * InstCombinerImpl::foldShuffledIntrinsicOperands (IntrinsicInst * II)
If all arguments of the intrinsic are unary shuffles with the same mask, try to shuffle after the intrinsic.
Definition at line 1488 of file InstCombineCalls.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::find_if_not(), llvm::VectorType::get(), llvm::Use::getOperandNo(), II, llvm::isa(), llvm::isTriviallyVectorizable(), llvm::isVectorIntrinsicWithScalarOpAtArg(), llvm::PatternMatch::m_ImmConstant(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Poison(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::PatternMatch::match_fn(), llvm::none_of(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), unshuffleConstant(), and X.
Referenced by visitCallInst(), and ~InstCombinerImpl().
foldSignBitTest()
Instruction * InstCombinerImpl::foldSignBitTest (ICmpInst & I)
Fold equality-comparison between zero and any (maybe truncated) right-shift by one-less-than-bitwidth into a sign test on the original value.
Definition at line 1166 of file InstCombineCompares.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::CmpInst::Create(), llvm::Constant::getNullValue(), llvm::Type::getScalarSizeInBits(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLT, llvm::isa(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombiner::SQ, and X.
Referenced by visitICmpInst().
foldSPFofSPF()
Instruction * InstCombinerImpl::foldSPFofSPF (Instruction * Inner, SelectPatternFlavor SPF1, Value * A, Value * B, Instruction & Outer, SelectPatternFlavor SPF2, Value * C)
We have an SPF (e.g.
a min or max) of an SPF of the form: SPF2(SPF1(A, B), C)
Definition at line 2292 of file InstCombineSelect.cpp.
References A(), B(), llvm::CallingConv::C, llvm::Value::getType(), llvm::SelectPatternResult::isMinOrMax(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by foldSelectEqualityTest(), and visitSelectInst().
foldSquareSumFP()
Instruction * InstCombinerImpl::foldSquareSumFP (BinaryOperator & I)
Definition at line 1074 of file InstCombineAddSub.cpp.
References A(), assert(), B(), llvm::InstCombiner::Builder, llvm::BinaryOperator::CreateFMulFMF(), I, llvm::PatternMatch::m_SpecificFP(), and matchesSquareSum().
Referenced by visitFAdd().
foldSquareSumInt()
Instruction * InstCombinerImpl::foldSquareSumInt (BinaryOperator & I)
Definition at line 1063 of file InstCombineAddSub.cpp.
References A(), B(), llvm::InstCombiner::Builder, I, llvm::PatternMatch::m_SpecificInt(), and matchesSquareSum().
Referenced by visitAdd().
foldUsingDistributiveLaws()
Value * InstCombinerImpl::foldUsingDistributiveLaws (BinaryOperator & I)
Tries to simplify binary operations which some other binary operation distributes over.
This tries to simplify binary operations which some other binary operation distributes over either by factorizing out common terms (eg "(A*B)+(A*C)" -> "A*(B+C)") or expanding out if this results in simplifications (eg: "A & (B | C) -> (A&B) | (A&C)" if this is a win).
It does this by either by factorizing out common terms (eg "(A*B)+(A*C)" -> "A*(B+C)") or expanding out if this results in simplifications (eg: "A & (B | C) -> (A&B) | (A&C)" if this is a win). Returns the simplified value, or null if it didn't simplify.
Returns the simplified value, or null if it didn't simplify.
Definition at line 1203 of file InstructionCombining.cpp.
References A(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::dyn_cast(), llvm::ConstantExpr::getBinOpIdentity(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), I, leftDistributesOverRight(), Op0, rightDistributesOverLeft(), llvm::simplifyBinOp(), SimplifySelectsFeedingBinaryOp(), llvm::InstCombiner::SQ, and tryFactorizationFolds().
Referenced by visitAdd(), visitAnd(), visitMul(), visitOr(), visitSub(), and visitXor().
foldVariableSignZeroExtensionOfVariableHighBitExtract()
Instruction * InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract (BinaryOperator & OldAShr)
Definition at line 1644 of file InstCombineShifts.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::Instruction::copyIRFlags(), llvm::BinaryOperator::Create(), llvm::CastInst::CreateTruncOrBitCast(), llvm::BinaryOperator::getOpcode(), llvm::Instruction::getOpcode(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Instruction(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), and X.
Referenced by visitAShr(), and ~InstCombinerImpl().
foldVectorBinop()
Instruction * InstCombinerImpl::foldVectorBinop (BinaryOperator & Inst)
Canonicalize the position of binops relative to shufflevector.
Definition at line 2389 of file InstructionCombining.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), constantFoldBinOpWithSplat(), llvm::Instruction::copyIRFlags(), llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::InstCombiner::F, llvm::Instruction::getModule(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::InstCombiner::getSafeVectorConstantForBinop(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::is_contained(), llvm::isa(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), llvm::Instruction::isIntDivRem(), llvm::isSafeToSpeculativelyExecuteWithVariableReplaced(), llvm::isSplatValue(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantSplat(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Poison(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VecReverse(), llvm::PatternMatch::m_VectorInsert(), llvm::PatternMatch::match(), llvm::PoisonMaskElem, llvm::InstCombiner::replaceInstUsesWith(), llvm::ArrayRef< T >::size(), llvm::Splat, std::swap(), unshuffleConstant(), X, and Y.
Referenced by visitAdd(), visitAnd(), visitAShr(), visitFAdd(), visitFDiv(), visitFMul(), visitFRem(), visitFSub(), visitLShr(), visitMul(), visitOr(), visitSDiv(), visitShl(), visitSRem(), visitSub(), visitUDiv(), visitURem(), and visitXor().
foldVectorSelect()
Instruction * InstCombinerImpl::foldVectorSelect (SelectInst & Sel)
Definition at line 2842 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), Cond, llvm::CallInst::Create(), llvm::dyn_cast(), llvm::InstCombiner::F, llvm::APInt::getAllOnes(), llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::Instruction::getModule(), llvm::Value::getName(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::is_contained(), llvm::isa(), llvm::isSplatValue(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VecReverse(), llvm::PatternMatch::match(), llvm::PoisonMaskElem, llvm::InstCombiner::replaceInstUsesWith(), SimplifyDemandedVectorElts(), X, and Y.
Referenced by visitSelectInst().
freelyInvertAllUsersOf()
void InstCombinerImpl::freelyInvertAllUsersOf (Value * I, Value * IgnoredUser = nullptr)
Freely adapt every user of V as-if V was changed to !V.
WARNING: only if canFreelyInvertAllUsersOf() said this can be done.
Definition at line 1442 of file InstructionCombining.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::InstCombiner::addToWorklist(), llvm::DIExpression::appendOpsToArg(), assert(), llvm::InstCombiner::BPI, llvm::cast(), llvm::findDbgValues(), getOpcode(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), I, llvm::isa(), llvm_unreachable, llvm::make_early_inc_range(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::BranchInst::swapSuccessors().
Referenced by canonicalizeICmpPredicate(), freelyInvert(), replaceInInstruction(), sinkNotIntoLogicalOp(), and sinkNotIntoOtherHandOfLogicalOp().
freezeOtherUses()
bool InstCombinerImpl::freezeOtherUses (FreezeInst & FI)
Definition at line 5194 of file InstructionCombining.cpp.
References llvm::cast(), llvm::InstCombiner::DT, llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHIOrDbgOrAlloca(), llvm::Instruction::getFunction(), llvm::User::getOperand(), llvm::isa(), and llvm::Instruction::moveBefore().
Referenced by visitFreeze(), and ~InstCombinerImpl().
handlePotentiallyDeadBlocks()
void InstCombinerImpl::handlePotentiallyDeadBlocks (SmallVectorImpl< BasicBlock * > & Worklist)
Definition at line 4185 of file InstructionCombining.cpp.
References llvm::all_of(), llvm::InstCombiner::DeadEdges, llvm::InstCombiner::DT, llvm::BasicBlock::front(), handleUnreachableFrom(), llvm::predecessors(), and llvm::InstCombiner::Worklist.
Referenced by handlePotentiallyDeadSuccessors(), replaceInInstruction(), and visitStoreInst().
handlePotentiallyDeadSuccessors()
void InstCombinerImpl::handlePotentiallyDeadSuccessors (BasicBlock * BB, BasicBlock * LiveSucc)
Definition at line 4198 of file InstructionCombining.cpp.
References addDeadEdge(), handlePotentiallyDeadBlocks(), llvm::successors(), and llvm::InstCombiner::Worklist.
Referenced by replaceInInstruction(), visitBranchInst(), and visitSwitchInst().
handleUnreachableFrom()
void InstCombinerImpl::handleUnreachableFrom (Instruction * I, SmallVectorImpl< BasicBlock * > & Worklist)
Definition at line 4155 of file InstructionCombining.cpp.
References addDeadEdge(), llvm::InstCombiner::addToWorklist(), llvm::cast(), eraseInstFromFunction(), llvm::PoisonValue::get(), llvm::ilist_node_impl< OptionsT >::getReverseIterator(), llvm::BasicBlock::getTerminator(), llvm::handleUnreachableTerminator(), I, llvm::InstCombiner::MadeIRChange, llvm::make_early_inc_range(), llvm::make_range(), llvm::InstCombiner::replaceInstUsesWith(), llvm::successors(), and llvm::InstCombiner::Worklist.
Referenced by handlePotentiallyDeadBlocks(), replaceInInstruction(), and visitStoreInst().
insertRangeTest()
Value * InstCombinerImpl::insertRangeTest (Value * V, const APInt & Lo, const APInt & Hi, bool isSigned, bool Inside)
Emit a computation of: (V >= Lo && V < Hi) if Inside is true, otherwise (V < Lo || V >= Hi).
This method expects that Lo < Hi. IsSigned indicates whether to treat V, Lo, and Hi as signed or not.
Definition at line 60 of file InstCombineAndOrXor.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::ICmpInst::getSignedPredicate(), llvm::Hi, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, and llvm::Lo.
Referenced by foldICmpDivConstant(), and replaceInInstruction().
matchBSwapOrBitReverse()
Instruction * InstCombinerImpl::matchBSwapOrBitReverse (Instruction & I, bool MatchBSwaps, bool MatchBitReversals)
Given an initial instruction, check to see if it is the root of a bswap/bitreverse idiom.
If so, return the equivalent bswap/bitreverse intrinsic.
Definition at line 2912 of file InstCombineAndOrXor.cpp.
References I, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::Instruction::removeFromParent(), and llvm::InstCombiner::Worklist.
Referenced by replaceInInstruction(), visitCallInst(), and visitOr().
matchThreeWayIntCompare()
bool InstCombinerImpl::matchThreeWayIntCompare (SelectInst * SI, Value *& LHS, Value *& RHS, ConstantInt *& Less, ConstantInt *& Equal, ConstantInt *& Greater)
Match a select chain which produces one of three values based on whether the LHS is less than, equal to, or greater than RHS respectively.
Return true if we matched a three way compare idiom. The LHS, RHS, Less, Equal and Greater values are saved in the matching process and returned to the caller.
Definition at line 3299 of file InstCombineCompares.cpp.
References assert(), llvm::cast(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::Less, llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and std::swap().
Referenced by foldICmpSelectConstant().
mergeStoreIntoSuccessor()
bool InstCombinerImpl::mergeStoreIntoSuccessor (StoreInst & SI)
Try to transform: if () { *P = v1; } else { *P = v2 } or: *P = v1; if () { *P = v2; } into a phi node with a store in the successor.
Definition at line 1546 of file InstCombineLoadStoreAlloca.cpp.
References llvm::PHINode::addIncoming(), llvm::BasicBlock::begin(), llvm::InstCombiner::Builder, llvm::PHINode::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), eraseInstFromFunction(), llvm::Instruction::getAAMetadata(), llvm::Instruction::getDebugLoc(), llvm::BasicBlock::getFirstInsertionPt(), llvm::DebugLoc::getMergedLocation(), llvm::BranchInst::getSuccessor(), llvm::Instruction::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::StoreInst::getValueOperand(), llvm::BasicBlock::hasNPredecessors(), I, llvm::InstCombiner::InsertNewInstBefore(), llvm::CastInst::isBitOrNoopPointerCastable(), llvm::BranchInst::isUnconditional(), llvm::AAMDNodes::merge(), llvm::Instruction::mergeDIAssignID(), llvm::pred_begin(), llvm::Instruction::setAAMetadata(), and llvm::Instruction::setDebugLoc().
Referenced by replaceInInstruction(), and visitUnconditionalBranchInst().
OptimizePointerDifference()
Value * InstCombinerImpl::OptimizePointerDifference (Value * LHS, Value * RHS, Type * Ty, bool IsNUW)
Optimize pointer differences into the same array into a size.
Consider: &A[10] - &A[0]: we should compile this to "10". LHS/RHS are the pointer operands to the ptrtoint instructions for the LHS/RHS of the subtract.
Definition at line 2198 of file InstCombineAddSub.cpp.
References llvm::sampleprof::Base, llvm::InstCombiner::Builder, llvm::cast(), llvm::CommonPointerBase::compute(), llvm::InstCombiner::DL, llvm::dyn_cast(), I, llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_Zero(), and llvm::PatternMatch::match().
Referenced by visitSub(), and ~InstCombinerImpl().
PHIArgMergedDebugLoc()
void InstCombinerImpl::PHIArgMergedDebugLoc (Instruction * Inst, PHINode & PN)
Helper function for FoldPHIArgXIntoPHI() to set debug location for the folded operation.
The PHI arguments will be folded into a single operation with a PHI node as input.
The debug location of the single operation will be the merged locations of the original PHI node arguments.
Definition at line 43 of file InstCombinePHI.cpp.
References llvm::Instruction::applyMergedLocation(), assert(), llvm::cast(), llvm::drop_begin(), llvm::Instruction::getDebugLoc(), llvm::PHINode::getIncomingValue(), I, llvm::PHINode::incoming_values(), llvm::isa(), and llvm::Instruction::setDebugLoc().
Referenced by foldPHIArgBinOpIntoPHI(), foldPHIArgExtractValueInstructionIntoPHI(), foldPHIArgGEPIntoPHI(), foldPHIArgInsertValueInstructionIntoPHI(), foldPHIArgLoadIntoPHI(), and foldPHIArgOpIntoPHI().
prepareWorklist()
bool InstCombinerImpl::prepareWorklist (Function & F)
Perform early cleanup and prepare the InstCombine worklist.
Populate the IC worklist from a function, by walking it in reverse post-order and adding all reachable code to the worklist.
This has a couple of tricks to make the code faster and more powerful. In particular, we constant fold and DCE instructions as we go, to avoid adding them to the worklist (this significantly speeds up instcombine on code where many instructions are dead or constant). Additionally, if we find a branch whose condition is a known constant, we only visit the reachable successors.
Definition at line 5874 of file InstructionCombining.cpp.
References llvm::all_of(), AliasScopeTracker::analyse(), llvm::CallingConv::C, llvm::cast(), Cond, llvm::ConstantFoldConstant(), llvm::ConstantFoldInstruction(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::InstCombiner::DeadEdges, llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::InstCombiner::F, llvm::PoisonValue::get(), llvm::BasicBlock::getTerminator(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::BasicBlock::isEntryBlock(), llvm::isInstructionTriviallyDead(), AliasScopeTracker::isNoAliasScopeDeclDead(), LLVM_DEBUG, llvm::InstCombiner::MadeIRChange, llvm::make_early_inc_range(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::removeAllNonTerminatorAndEHPadInstructions(), llvm::reverse(), llvm::InstCombiner::RPOT, llvm::salvageDebugInfo(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::successors(), llvm::InstCombiner::TLI, and llvm::InstCombiner::Worklist.
Referenced by combineInstructionsOverFunction(), and ~InstCombinerImpl().
pushFreezeToPreventPoisonFromPropagating()
Value * InstCombinerImpl::pushFreezeToPreventPoisonFromPropagating (FreezeInst & FI)
Definition at line 5065 of file InstructionCombining.cpp.
References llvm::InstCombiner::Builder, llvm::canCreateUndefOrPoison(), llvm::cast(), llvm::dyn_cast(), llvm::Value::getName(), llvm::User::getOperand(), llvm::isa(), and llvm::isGuaranteedNotToBeUndefOrPoison().
Referenced by visitFreeze(), and ~InstCombinerImpl().
reassociateShiftAmtsOfTwoSameDirectionShifts()
Value * InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts (BinaryOperator * Sh0, const SimplifyQuery & SQ, bool AnalyzeForSignBitExtraction = false)
Definition at line 58 of file InstCombineShifts.cpp.
References assert(), llvm::InstCombiner::Builder, canTryToConstantAddTwoShiftAmounts(), llvm::ConstantFoldCastOperand(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::dyn_cast_or_null(), llvm::BinaryOperator::getOpcode(), llvm::Instruction::getOpcode(), llvm::Value::getType(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::Instruction::isExact(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Instruction(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shift(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::PatternMatch::match(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::Instruction::setIsExact(), llvm::simplifyAddInst(), llvm::InstCombiner::SQ, and X.
Referenced by commonShiftTransforms(), foldSignBitTest(), and ~InstCombinerImpl().
removeInstructionsBeforeUnreachable()
bool InstCombinerImpl::removeInstructionsBeforeUnreachable (Instruction & I)
Definition at line 4080 of file InstructionCombining.cpp.
References eraseInstFromFunction(), llvm::PoisonValue::get(), I, llvm::isGuaranteedToTransferExecutionToSuccessor(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by replaceInInstruction(), visitStoreInst(), and visitUnreachableInst().
replacedSelectWithOperand()
bool InstCombinerImpl::replacedSelectWithOperand (SelectInst * SI, const ICmpInst * Icmp, const unsigned SIOpd)
Try to replace select with select operand SIOpd in SI-ICmp sequence.
True when a select result is replaced by one of its operands in select-icmp sequence.
This will eventually result in the elimination of the select.
Parameters
SI Select instruction
Icmp Compare instruction
SIOpd Operand that replaces the select
Notes:
The replacement is global and requires dominator information
The caller is responsible for the actual replacement
Example:
entry: %4 = select i1 %3, C* %0, C* null %5 = icmp eq C* %4, null br i1 %5, label %9, label %7 ... ; <label>:7 ; preds = entry %8 = getelementptr inbounds C* %4, i64 0, i32 0 ...
can be transformed to
%5 = icmp eq C* %0, null %6 = select i1 %3, i1 %5, i1 true br i1 %6, label %9, label %7 ... ; <label>:7 ; preds = entry %8 = getelementptr inbounds C* %0, i64 0, i32 0 // replace by %0!
Similar when the first operand of the select is a constant or/and the compare is for not equal rather than equal.
NOTE: The function is only called when the select and compare constants are equal, the optimization can work only for EQ predicates. This is not a major restriction since a NE compare should be 'normalized' to an equal compare, which usually happens in the combiner and test case select-cmp-br.ll checks for it.
Definition at line 6872 of file InstCombineCompares.cpp.
References assert(), dominatesAllUses(), llvm::CmpInst::getPredicate(), llvm::BasicBlock::getSinglePredecessor(), llvm::CmpInst::ICMP_EQ, and isChainSelectCmpBranch().
Referenced by foldSelectICmp().
replaceInInstruction()
bool llvm::InstCombinerImpl::replaceInInstruction (Value * V, Value * Old, Value * New, unsigned Depth = 0)
References addDeadEdge(), llvm::Depth, EvaluateInDifferentType(), freelyInvertAllUsersOf(), handlePotentiallyDeadBlocks(), handlePotentiallyDeadSuccessors(), handleUnreachableFrom(), I, insertRangeTest(), matchBSwapOrBitReverse(), mergeStoreIntoSuccessor(), MI, removeInstructionsBeforeUnreachable(), SimplifyAnyMemSet(), SimplifyAnyMemTransfer(), takeLog2(), tryToSinkInstruction(), tryToSinkInstructionDbgVariableRecords(), and llvm::InstCombiner::Worklist.
Referenced by foldSelectValueEquivalence(), and visitSelectInst().
run()
bool InstCombinerImpl::run ()
Run the combiner over the entire worklist until it is empty.
Returns
true if the IR is changed.
Definition at line 5628 of file InstructionCombining.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::cast(), llvm::dbgs(), llvm::InstCombiner::DT, llvm::dyn_cast(), EnableCodeSinking, eraseInstFromFunction(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getFirstNonPHIIt(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), llvm::BasicBlock::getUniquePredecessor(), I, II, llvm::isa(), llvm::User::isDroppable(), llvm::isInstructionTriviallyDead(), LLVM_DEBUG, llvm::InstCombiner::MadeIRChange, MaxSinkNumUsers, llvm::DebugCounter::shouldExecute(), llvm::succ_empty(), llvm::InstCombiner::TLI, tryToSinkInstruction(), llvm::InstVisitor< InstCombinerImpl, Instruction * >::visit(), and llvm::InstCombiner::Worklist.
Referenced by combineInstructionsOverFunction(), and ~InstCombinerImpl().
SimplifyAddWithRemainder()
Value * InstCombinerImpl::SimplifyAddWithRemainder (BinaryOperator & I)
Tries to simplify add operations using the definition of remainder.
The definition of remainder is X % C = X - (X / C) * C. The add expression X % C0 + ((X / C0) % C1) * C0 can be simplified to X % (C0 * C1)
Definition at line 1161 of file InstCombineAddSub.cpp.
References llvm::InstCombiner::AC, llvm::InstCombiner::Builder, llvm::InstCombiner::DT, llvm::Value::hasOneUse(), I, llvm::isGuaranteedNotToBeUndef(), llvm::APInt::isOne(), llvm::APInt::isPowerOf2(), llvm::APInt::isZero(), llvm::PatternMatch::m_IRem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), MatchDiv(), MatchMul(), MatchRem(), MulWillOverflow(), std::swap(), and X.
Referenced by visitAdd(), and visitOr().
SimplifyAnyMemSet()
Instruction * InstCombinerImpl::SimplifyAnyMemSet (AnyMemSetInst * MI)
Definition at line 220 of file InstCombineCalls.cpp.
References llvm::InstCombiner::AA, llvm::InstCombiner::AC, assert(), llvm::InstCombiner::Builder, llvm::Instruction::copyMetadata(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::at::getDVRAssignmentMarkers(), llvm::getKnownAlignment(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getSplat(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::is_contained(), llvm::isa(), llvm::Type::isIntegerTy(), llvm::isModSet(), llvm::isPowerOf2_32(), MI, llvm::StoreInst::setAlignment(), llvm::StoreInst::setOrdering(), and llvm::Unordered.
Referenced by replaceInInstruction(), and visitCallInst().
SimplifyAnyMemTransfer()
Instruction * InstCombinerImpl::SimplifyAnyMemTransfer (AnyMemTransferInst * MI)
Definition at line 118 of file InstCombineCalls.cpp.
References llvm::InstCombiner::AA, llvm::InstCombiner::AC, assert(), llvm::InstCombiner::Builder, llvm::Instruction::copyMetadata(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::IntegerType::get(), llvm::getKnownAlignment(), llvm::ConstantInt::getLimitedValue(), hasUndefSource(), llvm::isModSet(), MI, llvm::Instruction::setAAMetadata(), llvm::StoreInst::setAlignment(), llvm::Instruction::setMetadata(), llvm::StoreInst::setOrdering(), llvm::StoreInst::setVolatile(), Size, and llvm::Unordered.
Referenced by replaceInInstruction(), and visitCallInst().
SimplifyAssociativeOrCommutative()
bool InstCombinerImpl::SimplifyAssociativeOrCommutative (BinaryOperator & I)
Performs a few simplifications for operators which are associative or commutative.
This performs a few simplifications for operators that are associative or commutative:
Commutative operators:
Order operands such that they are listed from right (least complex) to left (most complex). This puts constants before unary operators before binary operators.
Associative operators:
Transform: "(A op B) op C" ==> "A op (B op C)" if "B op C" simplifies.
Transform: "A op (B op C)" ==> "(A op B) op C" if "A op B" simplifies.
Associative and commutative operators:
Transform: "(A op B) op C" ==> "(C op A) op B" if "C op A" simplifies.
Transform: "A op (B op C)" ==> "B op (C op A)" if "C op A" simplifies.
Transform: "(A op C1) op (B op C2)" ==> "(A op B) op (C1 op C2)" if C1 and C2 are constants.
Definition at line 499 of file InstructionCombining.cpp.
References A(), B(), llvm::CallingConv::C, ClearSubclassDataAfterReassociation(), llvm::ConstantFoldBinaryOpOperands(), llvm::BinaryOperator::Create(), llvm::BinaryOperator::CreateNUW(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::InstCombiner::getComplexity(), llvm::Instruction::getFastMathFlags(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), hasNoSignedWrap(), hasNoUnsignedWrap(), I, llvm::InstCombiner::InsertNewInstWith(), llvm::isa(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_Constant(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), maintainNoSignedWrap(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceOperand(), llvm::Instruction::setFastMathFlags(), simplifyAssocCastAssoc(), llvm::simplifyBinOp(), llvm::InstCombiner::SQ, and llvm::Value::takeName().
Referenced by visitAdd(), visitAnd(), visitFAdd(), visitFMul(), visitMul(), visitOr(), and visitXor().
simplifyBinOpSplats()
Instruction * InstCombinerImpl::simplifyBinOpSplats (ShuffleVectorInst & SVI)
Definition at line 2869 of file InstCombineVectorOps.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), llvm::dyn_cast(), llvm::User::getOperand(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::Value::hasOneUse(), llvm::isSafeToSpeculativelyExecuteWithVariableReplaced(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_Poison(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, X, and Y.
Referenced by visitShuffleVectorInst(), and ~InstCombinerImpl().
SimplifyDemandedBits() [1/2]
bool InstCombinerImpl::SimplifyDemandedBits (Instruction * I, unsigned OpNo, const APInt & DemandedMask, KnownBits & Known, const SimplifyQuery & Q, unsigned Depth = 0) override virtual
This form of SimplifyDemandedBits simplifies the specified instruction operand if possible, updating it in place.
It returns true if it made any change and false otherwise.
Implements llvm::InstCombiner.
Definition at line 153 of file InstCombineSimplifyDemanded.cpp.
References llvm::computeKnownBits(), llvm::Depth, llvm::dyn_cast(), llvm::UndefValue::get(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::APInt::isZero(), llvm::MaxAnalysisRecursionDepth, llvm::InstCombiner::replaceUse(), llvm::KnownBits::resetAll(), llvm::salvageDebugInfo(), SimplifyDemandedUseBits(), and SimplifyMultipleUseDemandedBits().
Referenced by foldICmpUsingKnownBits(), SimplifyDemandedUseBits(), and visitCallInst().
SimplifyDemandedBits() [2/2]
bool llvm::InstCombiner::SimplifyDemandedBits (Instruction * I, unsigned OpNo, const APInt & DemandedMask, KnownBits & Known) inline
Definition at line 518 of file InstCombiner.h.
SimplifyDemandedFPClass()
bool InstCombinerImpl::SimplifyDemandedFPClass (Instruction * I, unsigned Op, FPClassTest DemandedMask, KnownFPClass & Known, unsigned Depth = 0)
Definition at line 2866 of file InstCombineSimplifyDemanded.cpp.
References computeKnownFPClass(), llvm::Depth, llvm::dyn_cast(), llvm::fcAllFlags, llvm::fcNone, llvm::PoisonValue::get(), getFPClassConstant(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::KnownFPClass::KnownFPClasses, llvm::MaxAnalysisRecursionDepth, llvm::InstCombiner::replaceUse(), llvm::salvageDebugInfo(), SimplifyDemandedUseFPClass(), and SimplifyMultipleUseDemandedFPClass().
Referenced by SimplifyDemandedUseFPClass(), and visitReturnInst().
SimplifyDemandedInstructionBits() [1/2]
bool InstCombinerImpl::SimplifyDemandedInstructionBits (Instruction & Inst)
Tries to simplify operands to an integer instruction based on its demanded bits.
Inst is an integer instruction that SimplifyDemandedBits knows about.
See if the instruction has any properties that allow us to simplify its operands.
Definition at line 145 of file InstCombineSimplifyDemanded.cpp.
References llvm::InstCombiner::DL, getBitWidth(), llvm::Value::getType(), and SimplifyDemandedInstructionBits().
Referenced by commonIDivTransforms(), commonIRemTransforms(), commonShiftTransforms(), SimplifyDemandedInstructionBits(), visitAnd(), visitCallInst(), visitOr(), visitTrunc(), and visitXor().
SimplifyDemandedInstructionBits() [2/2]
bool InstCombinerImpl::SimplifyDemandedInstructionBits (Instruction & Inst, KnownBits & Known)
Inst is an integer instruction that SimplifyDemandedBits knows about.
See if the instruction has any properties that allow us to simplify its operands.
Definition at line 132 of file InstCombineSimplifyDemanded.cpp.
References llvm::APInt::getAllOnes(), llvm::KnownBits::getBitWidth(), llvm::InstCombiner::replaceInstUsesWith(), SimplifyDemandedUseBits(), and llvm::InstCombiner::SQ.
SimplifyDemandedUseBits()
Value * InstCombinerImpl::SimplifyDemandedUseBits (Instruction * I, const APInt & DemandedMask, KnownBits & Known, const SimplifyQuery & Q, unsigned Depth = 0)
Attempts to replace I with a simpler value based on the demanded bits.
This function attempts to replace V with a simpler value based on the demanded bits.
When this function is called, it is known that only the bits set in DemandedMask of the result of V are ever used downstream. Consequently, depending on the mask and V, it may be possible to replace V with a constant or one of its operands. In such cases, this function does the replacement and returns true. In all other cases, it returns false after analyzing the expression and setting KnownOne and known to be one in the expression. Known.Zero contains all the bits that are known to be zero in the expression. These are provided to potentially allow the caller (which might recursively be SimplifyDemandedBits itself) to simplify the expression. Known.One and Known.Zero always follow the invariant that: Known.One & Known.Zero == 0. That is, a bit can't be both 1 and 0. The bits in Known.One and Known.Zero are accurate even for bits not in DemandedMask. Note also that the bitwidth of V, DemandedMask, Known.Zero and Known.One must all be the same.
This returns null if it did not change anything and it permits no simplification. This returns V itself if it did some simplification of V's operands based on the information about what bits are demanded. This returns some other non-null value if it found out that V is equal to another value in the context where the specified bits are demanded, but not for all users.
Definition at line 222 of file InstCombineSimplifyDemanded.cpp.
References llvm::KnownBits::add(), llvm::adjustKnownBitsForSelectArm(), llvm::alignDown(), llvm::analyzeKnownBitsFromAndXorOr(), llvm::KnownBits::anyextOrTrunc(), llvm::KnownBits::ashr(), assert(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::APInt::clearLowBits(), llvm::computeKnownBits(), llvm::InstCombiner::computeKnownBits(), llvm::InstCombiner::ComputeNumSignBits(), llvm::ConstantFoldBinaryOpOperands(), convertOrOfShiftsToFunnelShift(), llvm::APInt::countl_zero(), llvm::countr_one(), llvm::APInt::countr_zero(), llvm::CallInst::Create(), llvm::SimplifyQuery::CxtI, llvm::Depth, llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::errs(), GEP, llvm::APInt::getActiveBits(), llvm::Constant::getAllOnesValue(), llvm::APInt::getBitWidth(), llvm::KnownBits::getBitWidth(), llvm::APInt::getHighBitsSet(), llvm::Constant::getIntegerValue(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::Constant::getNullValue(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignMask(), llvm::ConstantInt::getValue(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), llvm::haveNoCommonBitsSet(), I, II, llvm::InstCombiner::InsertNewInstWith(), llvm::KnownBits::intersectWith(), llvm::isa(), llvm::APInt::isAllOnes(), llvm::Type::isIntOrIntVectorTy(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm::APInt::isOne(), llvm::APInt::isPowerOf2(), llvm::APInt::isSubsetOf(), llvm::Log2(), llvm::APInt::lshr(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_PtrAdd(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::KnownBits::makeConstant(), llvm::KnownBits::makeNonNegative(), llvm::PatternMatch::match(), llvm::MaxAnalysisRecursionDepth, Mul, llvm::KnownBits::One, llvm::InstCombiner::replaceOperand(), llvm::APInt::setBit(), llvm::APInt::setHighBits(), llvm::Instruction::setIsExact(), llvm::APInt::setLowBits(), llvm::APInt::setSignBit(), llvm::KnownBits::sext(), llvm::APInt::shl(), llvm::KnownBits::shl(), ShrinkDemandedConstant(), SimplifyDemandedBits(), simplifyShiftSelectingPackedElement(), simplifyShrShlDemandedBits(), llvm::KnownBits::srem(), llvm::KnownBits::sub(), llvm::Value::takeName(), llvm::InstCombiner::targetSimplifyDemandedUseBitsIntrinsic(), llvm::APInt::trunc(), llvm::KnownBits::udiv(), llvm::APInt::ult(), llvm::KnownBits::unionWith(), llvm::APInt::urem(), VerifyKnownBits, X, llvm::Xor, Y, llvm::KnownBits::Zero, llvm::APInt::zextOrTrunc(), and llvm::KnownBits::zextOrTrunc().
Referenced by SimplifyDemandedBits(), and SimplifyDemandedInstructionBits().
SimplifyDemandedUseFPClass()
Value * InstCombinerImpl::SimplifyDemandedUseFPClass (Instruction * I, FPClassTest DemandedMask, KnownFPClass & Known, Instruction * CxtI, unsigned Depth = 0)
Attempts to replace V with a simpler value based on the demanded floating-point classes.
Propagate nnan-ness to simplify edge case checks.
Propagate nnan-ness to simplify edge case checks.
Definition at line 2036 of file InstCombineSimplifyDemanded.cpp.
References llvm::adjustKnownFPClassForSelectArm(), assert(), llvm::InstCombiner::Builder, llvm::KnownFPClass::cannotBeOrderedGreaterEqZero(), llvm::KnownFPClass::canonicalize(), llvm::cast(), computeKnownFPClass(), llvm::KnownFPClass::copysign(), DEBUG_TYPE, llvm::Depth, llvm::Instruction::dropUBImplyingAttrsAndMetadata(), llvm::dyn_cast(), llvm::KnownFPClass::exp(), llvm::InstCombiner::F, llvm::KnownFPClass::fabs(), llvm::fcAllFlags, llvm::fcInf, llvm::CmpInst::FCMP_UEQ, llvm::fcNan, llvm::fcNegative, llvm::fcNegInf, llvm::fcNegNormal, llvm::fcNegSubnormal, llvm::fcNegZero, llvm::fcNone, llvm::fcNormal, llvm::fcPosInf, llvm::fcPositive, llvm::fcPosNormal, llvm::fcPosSubnormal, llvm::fcPosZero, llvm::fcQNan, llvm::fcSNan, llvm::fcSubnormal, llvm::fcZero, llvm::KnownFPClass::fmul(), llvm::fneg(), llvm::KnownFPClass::fneg(), llvm::KnownFPClass::fpext(), llvm::PoisonValue::get(), llvm::CallBase::getArgOperand(), llvm::Type::getFltSemantics(), getFPClassConstant(), llvm::DenormalMode::getIEEE(), llvm::ConstantFP::getInfinity(), llvm::CallBase::getIntrinsicID(), llvm::User::getOperand(), llvm::DenormalMode::getPreserveSign(), llvm::ConstantFP::getQNaN(), llvm::Type::getScalarType(), llvm::InstCombiner::getSimplifyQuery(), llvm::ConstantFP::getZero(), I, llvm::KnownFPClass::intersectWith(), llvm::inverse_fabs(), llvm::isGuaranteedNotToBeUndef(), llvm::Type::isIEEELikeFPTy(), llvm::KnownFPClass::isKnownAlways(), llvm::KnownFPClass::isKnownNever(), llvm::KnownFPClass::isKnownNeverInfOrNaN(), llvm::KnownFPClass::isKnownNeverLogicalZero(), llvm::KnownFPClass::isKnownNeverNaN(), llvm::KnownFPClass::isKnownNeverSubnormal(), llvm::Type::isMultiUnitFPType(), llvm::KnownFPClass::KnownFPClasses, llvm::KnownFPClass::knownNot(), llvm_unreachable, llvm::KnownFPClass::log(), llvm::MaxAnalysisRecursionDepth, llvm::KnownFPClass::maximum, llvm::KnownFPClass::maximumnum, llvm::KnownFPClass::minimum, llvm::KnownFPClass::minimumnum, llvm::KnownFPClass::minMaxLike(), llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), llvm::KnownFPClass::roundToIntegral(), llvm::Instruction::setHasNoNaNs(), llvm::User::setOperand(), llvm::KnownFPClass::SignBit, SimplifyDemandedFPClass(), llvm::InstCombiner::SQ, llvm::KnownFPClass::sqrt(), llvm::KnownFPClass::square(), llvm::Value::takeName(), llvm::unknown_sign(), X, and Y.
Referenced by SimplifyDemandedFPClass().
SimplifyDemandedVectorElts()
Value * InstCombinerImpl::SimplifyDemandedVectorElts (Value * V, APInt DemandedElts, APInt & PoisonElts, unsigned Depth = 0, bool AllowMultipleUsers = false) override virtual
The specified value produces a vector with any number of elements.
This method analyzes which elements of the operand are poison and returns that information in PoisonElts.
DemandedElts contains the set of elements that are actually used by the caller, and by default (AllowMultipleUsers equals false) the value is simplified only if it has a single caller. If AllowMultipleUsers is set to true, DemandedElts refers to the union of sets of elements that are used by all callers.
If the information about demanded elements can be used to simplify the operation, the operation is simplified, then the resultant value is returned. This returns null if no change was made.
Implements llvm::InstCombiner.
Definition at line 1457 of file InstCombineSimplifyDemanded.cpp.
References llvm::all_of(), assert(), llvm::CallingConv::C, llvm::cast(), llvm::APInt::clearAllBits(), llvm::APInt::clearBit(), llvm::InsertElementInst::Create(), llvm::Depth, llvm::InstCombiner::DT, llvm::dyn_cast(), GEP, llvm::gep_type_begin(), llvm::gep_type_end(), llvm::ConstantVector::get(), llvm::PoisonValue::get(), llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnes(), llvm::SelectInst::getCondition(), llvm::Type::getInt64Ty(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::Value::hasOneUse(), llvm::Value::hasUseList(), I, II, llvm::InstCombiner::InsertNewInstWith(), llvm::isa(), llvm::APInt::isAllOnes(), llvm::Instruction::isCommutative(), llvm::Instruction::isIntDivRem(), llvm::Constant::isNullValue(), llvm::Constant::isOneValue(), llvm::Instruction::isShift(), llvm::Type::isVectorTy(), llvm::APInt::isZero(), llvm_unreachable, llvm::APInt::lshr(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_ExtractElt(), llvm::PatternMatch::m_Poison(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Poison, llvm::PoisonMaskElem, llvm::APInt::popcount(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InstCombiner::replaceOperand(), llvm::APInt::setBit(), SimplifyDemandedVectorElts(), SimplifyDemandedVectorEltsDepthLimit, llvm::InstCombiner::targetSimplifyDemandedVectorEltsIntrinsic(), llvm::Value::users(), llvm::InstCombiner::Worklist, X, Y, and llvm::APInt::zextOrTrunc().
Referenced by foldVectorSelect(), SimplifyDemandedVectorElts(), visitCallInst(), visitExtractElementInst(), visitGetElementPtrInst(), visitInsertElementInst(), and visitShuffleVectorInst().
simplifyDivRemOfSelectWithZeroOp()
bool InstCombinerImpl::simplifyDivRemOfSelectWithZeroOp (BinaryOperator & I)
Fold a divide or remainder with a select instruction divisor when one of the select operands is zero.
In that case, we can use the other select operand because div/rem by zero is undefined.
Definition at line 1100 of file InstCombineMulDivRem.cpp.
References llvm::dyn_cast(), llvm::ConstantInt::getFalse(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceOperand(), llvm::InstCombiner::replaceUse(), and llvm::InstCombiner::Worklist.
Referenced by commonIDivRemTransforms(), and ~InstCombinerImpl().
SimplifyMultipleUseDemandedBits()
Value * InstCombinerImpl::SimplifyMultipleUseDemandedBits (Instruction * I, const APInt & DemandedMask, KnownBits & Known, const SimplifyQuery & Q, unsigned Depth = 0)
Helper routine of SimplifyDemandedUseBits.
It computes KnownZero/KnownOne bits. It also tries to handle simplifications that can be done based on DemandedMask, but without modifying the Instruction.
It computes Known bits. It also tries to handle simplifications that can be done based on DemandedMask, but without modifying the Instruction.
Definition at line 1206 of file InstCombineSimplifyDemanded.cpp.
References llvm::KnownBits::add(), llvm::analyzeKnownBitsFromAndXorOr(), llvm::BitWidth, llvm::cast(), llvm::computeKnownBits(), llvm::computeKnownBitsFromContext(), llvm::APInt::countl_zero(), llvm::Depth, llvm::APInt::getBitWidth(), llvm::Constant::getIntegerValue(), llvm::APInt::getLowBitsSet(), llvm::APInt::getZExtValue(), I, llvm::APInt::isSubsetOf(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::KnownBits::One, llvm::KnownBits::sub(), llvm::APInt::ult(), X, and llvm::KnownBits::Zero.
Referenced by SimplifyDemandedBits().
SimplifyMultipleUseDemandedFPClass()
Value * InstCombinerImpl::SimplifyMultipleUseDemandedFPClass (Instruction * I, FPClassTest DemandedMask, KnownFPClass & Known, Instruction * CxtI, unsigned Depth)
Helper routine of SimplifyDemandedUseFPClass.
It computes Known floating-point classes. It also tries to handle simplifications that can be done based on DemandedMask, but without modifying the Instruction.
Definition at line 2833 of file InstCombineSimplifyDemanded.cpp.
References llvm::adjustKnownFPClassForSelectArm(), computeKnownFPClass(), llvm::Depth, getFPClassConstant(), llvm::InstCombiner::getSimplifyQuery(), I, llvm::KnownFPClass::intersectWith(), llvm::KnownFPClass::isKnownNever(), llvm::KnownFPClass::KnownFPClasses, and llvm::InstCombiner::SQ.
Referenced by SimplifyDemandedFPClass().
simplifyRangeCheck()
Value * InstCombinerImpl::simplifyRangeCheck (ICmpInst * Cmp0, ICmpInst * Cmp1, bool Inverted)
Try to fold a signed range checked with lower bound 0 to an unsigned icmp.
Example: (icmp sge x, 0) & (icmp slt x, n) --> icmp ult x, n If Inverted is true then the check is for the inverted range, e.g. (icmp slt x, 0) | (icmp sgt x, n) --> icmp ugt x, n
Definition at line 724 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::Builder, llvm::InstCombiner::computeKnownBits(), llvm::dyn_cast(), llvm::CmpInst::getInversePredicate(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ConstantInt::isMinusOne(), llvm::KnownBits::isNonNegative(), llvm::ConstantInt::isZero(), llvm::PatternMatch::m_SExtOrSelf(), llvm::PatternMatch::m_Specific(), and llvm::PatternMatch::match().
Referenced by ~InstCombinerImpl().
SimplifySelectsFeedingBinaryOp()
Value * InstCombinerImpl::SimplifySelectsFeedingBinaryOp (BinaryOperator & I, Value * LHS, Value * RHS)
Definition at line 1359 of file InstructionCombining.cpp.
References A(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), Cond, D(), llvm::dyn_cast(), llvm::InstCombiner::F, I, llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), N, nullptr, llvm::ProfcheckDisableMetadataFixes, llvm::simplifyBinOp(), llvm::InstCombiner::SQ, llvm::Sub, and llvm::Value::takeName().
Referenced by foldUsingDistributiveLaws(), visitFAdd(), visitFMul(), and visitFSub().
simplifyShrShlDemandedBits()
Value * InstCombinerImpl::simplifyShrShlDemandedBits (Instruction * Shr, const APInt & ShrOp1, Instruction * Shl, const APInt & ShlOp1, const APInt & DemandedMask, KnownBits & Known)
Helper routine of SimplifyDemandedUseBits.
It tries to simplify demanded bit for "r1 = shr x, c1; r2 = shl r1, c2" instruction sequence.
It tries to simplify "E1 = (X lsr C1) << C2", where the C1 and C2 are constant, into "E2 = X << (C2 - C1)" or "E2 = X >> (C1 - C2)", depending on the sign of "C2-C1".
Suppose E1 and E2 are generally different in bits S={bm, bm+1, ..., bn}, without considering the specific value X is holding. This transformation is legal iff one of following conditions is hold: 1) All the bit in S are 0, in this case E1 == E2. 2) We don't care those bits in S, per the input DemandedMask. 3) Combination of 1) and 2). Some bits in S are 0, and we don't care the rest bits.
Currently we only test condition 2).
As with SimplifyDemandedUseBits, it returns NULL if the simplification was not successful.
Definition at line 1382 of file InstCombineSimplifyDemanded.cpp.
References llvm::APInt::ashr(), llvm::BitWidth, llvm::cast(), llvm::APInt::clearAllBits(), llvm::APInt::getAllOnes(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::APInt::getZExtValue(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), llvm::InstCombiner::InsertNewInstWith(), llvm::APInt::lshr(), llvm::KnownBits::One, llvm::APInt::setLowBits(), llvm::APInt::uge(), and llvm::KnownBits::Zero.
Referenced by SimplifyDemandedUseBits().
sinkNotIntoLogicalOp()
bool InstCombinerImpl::sinkNotIntoLogicalOp (Instruction & I)
Definition at line 4907 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::Builder, canFreelyInvert(), llvm::InstCombiner::canFreelyInvertAllUsersOf(), freelyInvert(), freelyInvertAllUsersOf(), I, llvm::isa(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOp(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by ~InstCombinerImpl().
sinkNotIntoOtherHandOfLogicalOp()
bool InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp (Instruction & I)
Definition at line 4959 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::Builder, canFreelyInvert(), llvm::InstCombiner::canFreelyInvertAllUsersOf(), freelyInvert(), freelyInvertAllUsersOf(), I, llvm::isa(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOp(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by visitAnd(), visitOr(), visitSelectInst(), and ~InstCombinerImpl().
SliceUpIllegalIntegerPHI()
Instruction * InstCombinerImpl::SliceUpIllegalIntegerPHI (PHINode & FirstPhi)
This is an integer PHI and we know that it has an illegal type: see if it is only used by trunc or trunc(lshr) operations.
If so, we split the PHI into the various pieces being extracted. This sort of thing is introduced when SROA promotes an aggregate to large integer values.
TODO: The user of the trunc may be an bitcast to float/double/vector or an inttoptr. We should produce new PHIs in the right type.
Definition at line 1095 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::array_pod_sort(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::PHINode::blocks(), llvm::InstCombiner::Builder, llvm::cast(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::PHINode::Create(), llvm::dbgs(), llvm::drop_begin(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::find(), llvm::PoisonValue::get(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, II, llvm::PHINode::incoming_values(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), LLVM_DEBUG, llvm::Offset, PHI, Poison, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InstCombiner::replaceInstUsesWith(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Instruction::user_back(), llvm::Value::users(), and llvm::zip().
Referenced by ~InstCombinerImpl().
takeLog2()
Value * InstCombinerImpl::takeLog2 (Value * Op, unsigned Depth, bool AssumeNonZero, bool DoFold)
Take the exact integer log2 of the value.
If DoFold is true, create the actual instructions, otherwise return a non-null dummy value. Return nullptr on failure. Note, if DoFold is true the caller must ensure that takeLog2 will succeed, otherwise it may create stray instructions.
Definition at line 1535 of file InstCombineMulDivRem.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::Depth, llvm::dyn_cast(), llvm::ConstantExpr::getExactLogBase2(), llvm_unreachable, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::MaxAnalysisRecursionDepth, takeLog2(), X, and Y.
Referenced by replaceInInstruction(), takeLog2(), and tryGetLog2().
tryFactorizationFolds()
Value * InstCombinerImpl::tryFactorizationFolds (BinaryOperator & I)
This tries to simplify binary operations by factorizing out common terms (e.
g. "(A*B)+(A*C)" -> "A*(B+C)").
Definition at line 1160 of file InstructionCombining.cpp.
References A(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, D(), llvm::dyn_cast(), getBinOpsForFactorization(), getIdentityValue(), I, Op0, llvm::InstCombiner::SQ, and tryFactorization().
Referenced by foldUsingDistributiveLaws().
tryFoldInstWithCtpopWithNot()
Instruction * InstCombinerImpl::tryFoldInstWithCtpopWithNot (Instruction * I)
Definition at line 850 of file InstructionCombining.cpp.
References assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldCompareInstOperands(), llvm::InstCombiner::DL, llvm::ConstantExpr::getAdd(), llvm::InstCombiner::getFreelyInverted(), llvm::ConstantExpr::getSub(), I, llvm::CmpInst::ICMP_UGT, llvm::InstCombiner::isFreeToInvert(), llvm_unreachable, llvm::PatternMatch::m_DisjointOr(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Opc, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by foldICmpWithConstant(), visitAdd(), visitOr(), and visitSub().
tryGetLog2()
Value * llvm::InstCombinerImpl::tryGetLog2 (Value * Op, bool AssumeNonZero) inline
Definition at line 854 of file InstCombineInternal.h.
References takeLog2().
Referenced by foldCttzCtlz(), visitMul(), and visitUDiv().
tryToSinkInstruction()
bool InstCombinerImpl::tryToSinkInstruction (Instruction * I, BasicBlock * DestBlock)
Try to move the specified instruction from its current block into the beginning of DestBlock, which can only happen if it's safe to move the instruction past all of the instructions between it and the end of its block.
FIXME: We could remove droppable uses that are not dominated by the new position.
Definition at line 5413 of file InstructionCombining.cpp.
References llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::findDbgUsers(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getTerminator(), llvm::BasicBlock::getUniquePredecessor(), I, llvm::isa(), SoleWriteToDeadLocal(), llvm::InstCombiner::TLI, tryToSinkInstructionDbgVariableRecords(), and llvm::InstCombiner::Worklist.
Referenced by replaceInInstruction(), and run().
tryToSinkInstructionDbgVariableRecords()
void InstCombinerImpl::tryToSinkInstructionDbgVariableRecords (Instruction * I, BasicBlock::iterator InsertPos, BasicBlock * SrcBlock, BasicBlock * DestBlock, SmallVectorImpl< DbgVariableRecord * > & DPUsers)
Definition at line 5500 of file InstructionCombining.cpp.
References A(), assert(), B(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::dbgs(), llvm::DbgVariableRecord::Declare, llvm::SmallVectorImpl< T >::emplace_back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::filterDbgVars(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallSet< T, N, C >::insert(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), llvm::salvageDebugInfoForDbgValues(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::stable_sort().
Referenced by replaceInInstruction(), and tryToSinkInstruction().
unshuffleConstant()
Constant * InstCombinerImpl::unshuffleConstant (ArrayRef< int > ShMask, Constant * C, VectorType * NewCTy)
Find a constant NewC that has property: shuffle(NewC, ShMask) = C Returns nullptr if such a constant does not exist e.g.
ShMask=<0,0> C=<1,2>
A 1-to-1 mapping is not required. Example: ShMask = <1,1,2,2> and C = <5,5,6,6> --> NewC = <poison,5,6,poison>
Definition at line 2340 of file InstructionCombining.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), llvm::ConstantVector::get(), llvm::PoisonValue::get(), llvm::VectorType::getElementCount(), getNumElements(), llvm::ConstantVector::getSplat(), I, llvm::isa(), and llvm::Splat.
Referenced by foldShuffledIntrinsicOperands(), and foldVectorBinop().
visitAdd()
Instruction * InstCombinerImpl::visitAdd (BinaryOperator & I)
Definition at line 1526 of file InstCombineAddSub.cpp.
References A(), llvm::Add, llvm::InstCombiner::AddOne(), llvm::AllOnes, assert(), B(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeLowbitMask(), llvm::cast(), checkForNegativeOperand(), combineAddSubWithShlAddSub(), llvm::InstCombiner::ComputeNumSignBits(), Cond, llvm::APInt::countl_zero(), llvm::APInt::countr_zero(), llvm::BinaryOperator::CreateNeg(), factorizeMathWithShlOps(), foldAddLikeCommutative(), foldAddToAshr(), foldAddWithConstant(), foldBinOpOfSelectAndCastOfSelectCondition(), foldBinOpShiftWithShift(), foldBinopWithPhiOperands(), foldBoxMultiply(), foldNoWrapAdd(), foldSquareSumInt(), foldToUnsignedSaturatedAdd(), foldUsingDistributiveLaws(), foldVectorBinop(), llvm::ConstantExpr::getAdd(), llvm::Constant::getAllOnesValue(), llvm::InstCombiner::getFreelyInverted(), llvm::Constant::getNullValue(), llvm::ConstantInt::getSigned(), llvm::Value::hasOneUse(), llvm::haveNoCommonBitsSet(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_UGT, llvm::isa(), llvm::InstCombiner::isFreeToInvert(), llvm::ICmpInst::isGT(), llvm::ICmpInst::isLT(), llvm::APInt::isPowerOf2(), llvm::CmpInst::isSigned(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_NegatedPower2(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NUWSub(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), llvm::matchSimpleRecurrence(), PHI, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::simplifyAddInst(), SimplifyAddWithRemainder(), SimplifyAssociativeOrCommutative(), llvm::InstCombiner::SQ, llvm::Sub, llvm::InstCombiner::SubOne(), std::swap(), tryFoldInstWithCtpopWithNot(), llvm::UMax, llvm::InstCombiner::Worklist, and X.
Referenced by ~InstCombinerImpl().
visitAddrSpaceCast()
Instruction * InstCombinerImpl::visitAddrSpaceCast (AddrSpaceCastInst & CI)
Definition at line 3233 of file InstCombineCasts.cpp.
References commonCastTransforms().
Referenced by ~InstCombinerImpl().
visitAllocaInst()
Instruction * InstCombinerImpl::visitAllocaInst (AllocaInst & AI)
Definition at line 498 of file InstCombineLoadStoreAlloca.cpp.
References llvm::InstCombiner::AA, llvm::InstCombiner::AC, llvm::dbgs(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), eraseInstFromFunction(), llvm::AllocaInst::getAddressSpace(), llvm::AllocaInst::getAlign(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getArraySize(), llvm::BasicBlock::getFirstNonPHIOrDbg(), llvm::getOrEnforceKnownAlignment(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), I, llvm::isa(), llvm::AllocaInst::isArrayAllocation(), isDereferenceableForAllocaSize(), isOnlyCopiedFromConstantMemory(), llvm::Type::isSized(), LLVM_DEBUG, llvm::Instruction::moveBefore(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::AllocaInst::setAlignment(), simplifyAllocaArraySize(), and visitAllocSite().
Referenced by ~InstCombinerImpl().
visitAllocSite()
Instruction * InstCombinerImpl::visitAllocSite (Instruction & FI)
Definition at line 3757 of file InstructionCombining.cpp.
References llvm::InstCombiner::AA, assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ConvertDebugDeclareToDebugValue(), llvm::InvokeInst::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), eraseInstFromFunction(), llvm::InstCombiner::F, llvm::findDbgUsers(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::getInitialValueOfAllocation(), llvm::Type::getInt1Ty(), llvm::Type::getInt8Ty(), llvm::Constant::getNullValue(), llvm::Intrinsic::getOrInsertDeclaration(), I, II, llvm::isa(), isAllocSiteRemovable(), llvm::isRefSet(), llvm::isRemovableAlloc(), llvm::lowerObjectSizeCall(), MI, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::TLI, Users, and llvm::InstCombiner::Worklist.
Referenced by visitAllocaInst(), and ~InstCombinerImpl().
visitAnd()
Instruction * InstCombinerImpl::visitAnd (BinaryOperator & I)
Definition at line 2416 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeLogicFirst(), llvm::cast(), llvm::InstCombiner::computeKnownBits(), llvm::ConstantFoldCompareInstOperands(), llvm::APInt::countr_zero(), llvm::BinaryOperator::Create(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::APInt::exactLogBase2(), foldAndToXor(), foldBinOpIntoSelectOrPhi(), foldBinOpShiftWithShift(), foldBinopWithPhiOperands(), foldBitwiseLogicWithIntrinsics(), foldComplexAndOrPatterns(), foldUsingDistributiveLaws(), foldVectorBinop(), llvm::ConstantExpr::getAdd(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getExactLogBase2(), llvm::Type::getFltSemantics(), llvm::InstCombiner::getFreelyInverted(), llvm::APInt::getLowBitsSet(), llvm::KnownBits::getMaxValue(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::ConstantExpr::getSub(), llvm::Value::getType(), llvm::APInt::getZExtValue(), llvm::Value::hasOneUse(), llvm::APFloatBase::hasSignBitInMSB(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::Type::isFloatingPointTy(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::APInt::isPowerOf2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_MaxSignedValue(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_SExtOrSelf(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), matchDeMorgansLaws(), llvm::matchSimpleRecurrence(), Op0, reassociateFCmps(), reassociateForUses(), llvm::InstCombiner::replaceInstUsesWith(), llvm::simplifyAndInst(), simplifyAndOrWithOpReplaced(), SimplifyAssociativeOrCommutative(), SimplifyDemandedInstructionBits(), sinkNotIntoOtherHandOfLogicalOp(), llvm::InstCombiner::SQ, llvm::APInt::trunc(), llvm::APInt::ult(), X, llvm::Xor, Y, and llvm::APInt::zext().
Referenced by ~InstCombinerImpl().
visitAShr()
Instruction * InstCombinerImpl::visitAShr (BinaryOperator & I)
Definition at line 1712 of file InstCombineShifts.cpp.
References llvm::BitWidth, llvm::InstCombiner::Builder, llvm::cast(), commonShiftTransforms(), llvm::BinaryOperator::Create(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNot(), foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVectorBinop(), llvm::APInt::getSignMask(), llvm::APInt::getZExtValue(), hasNoUnsignedWrap(), I, llvm::APInt::logBase2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NSWSub(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::Constant::mergeUndefsWith(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setIsExact(), setShiftFlags(), llvm::simplifyAShrInst(), llvm::InstCombiner::SQ, llvm::APInt::ult(), X, and Y.
Referenced by ~InstCombinerImpl().
visitAtomicRMWInst()
Instruction * InstCombinerImpl::visitAtomicRMWInst (AtomicRMWInst & SI)
Definition at line 101 of file InstCombineAtomicRMW.cpp.
References assert(), llvm::AtomicRMWInst::FAdd, llvm::ConstantFP::getNegativeZero(), llvm::AtomicRMWInst::getOperation(), llvm::AtomicRMWInst::getOrdering(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), isIdempotentRMW(), llvm::Type::isIntegerTy(), isSaturating(), llvm::AtomicRMWInst::isVolatile(), llvm::NotAtomic, llvm::AtomicRMWInst::Or, llvm::InstCombiner::replaceOperand(), llvm::AtomicRMWInst::setOperation(), llvm::Unordered, and llvm::AtomicRMWInst::Xchg.
Referenced by ~InstCombinerImpl().
visitBitCast()
Instruction * InstCombinerImpl::visitBitCast (BitCastInst & CI)
Definition at line 3086 of file InstCombineCasts.cpp.
References assert(), llvm::BitWidth, llvm::InstCombiner::Builder, canonicalizeBitCastExtElt(), llvm::cast(), commonCastTransforms(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldBitCastBitwiseLogic(), foldBitCastSelect(), foldCopySignIdioms(), llvm::Value::getContext(), llvm::APInt::getHighBitsSet(), llvm::Type::getInt32Ty(), llvm::Instruction::getModule(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), I, llvm::isa(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_InsertElt(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), optimizeIntegerToVectorInsertions(), optimizeVectorResizeWithIntegerBitCasts(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::SQ, X, and Y.
Referenced by ~InstCombinerImpl().
visitBranchInst()
Instruction * InstCombinerImpl::visitBranchInst (BranchInst & BI)
Definition at line 4212 of file InstructionCombining.cpp.
References llvm::InstCombiner::addToWorklist(), llvm::InstCombiner::BPI, llvm::InstCombiner::Builder, llvm::cast(), Cond, llvm::InstCombiner::DC, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::BranchInst::getCondition(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getInversePredicate(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BranchInst::getSuccessor(), llvm::ConstantInt::getTrue(), handlePotentiallyDeadSuccessors(), llvm::isa(), llvm::InstCombiner::isCanonicalPredicate(), llvm::BranchInst::isUnconditional(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_LogicalAnd(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::make_early_inc_range(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceOperand(), llvm::InstCombiner::replaceUse(), llvm::BranchInst::swapSuccessors(), visitUnconditionalBranchInst(), llvm::InstCombiner::Worklist, X, and Y.
Referenced by ~InstCombinerImpl().
visitCallBrInst()
Instruction * InstCombinerImpl::visitCallBrInst (CallBrInst & CBI)
Definition at line 4296 of file InstCombineCalls.cpp.
Referenced by ~InstCombinerImpl().
visitCallInst()
Instruction * InstCombinerImpl::visitCallInst (CallInst & CI)
CallInst simplification.
This mostly only handles folding of intrinsic instructions. For normal calls, it allows visitCallBase to do the heavy lifting.
This will remove the boolean Condition from the assume given as argument and remove the assume if it becomes useless. always returns nullptr for use as a return values.
Note: this doesn't preserve the offset information but merges offset and alignment. TODO: we can generate a GEP instead of merging the alignment with the offset.
Canonicalize Knowledge in operand bundles.
Definition at line 1866 of file InstCombineCalls.cpp.
References A(), llvm::InstCombiner::AA, llvm::InstCombiner::AC, llvm::CallBase::addRetAttr(), llvm::alignDown(), llvm::FastMathFlags::allowReassoc(), llvm::AlwaysOverflowsHigh, llvm::AlwaysOverflowsLow, llvm::CallBase::args(), llvm::RetainedKnowledge::ArgValue, assert(), llvm::RetainedKnowledge::AttrKind, B(), llvm::BitWidth, llvm::buildAssumeFromKnowledge(), llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeConstantArg0ToArg1(), llvm::cast(), llvm::APFloat::clearSign(), llvm::computeConstantRangeIncludingKnownBits(), llvm::InstCombiner::computeKnownBits(), llvm::computeKnownFPSignBit(), computeOverflow(), Cond, llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldCompareInstOperands(), llvm::Instruction::copyIRFlags(), llvm::KnownBits::countMinLeadingZeros(), llvm::KnownBits::countMinTrailingZeros(), llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateFAddFMF(), llvm::BinaryOperator::CreateFDivFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::UnaryOperator::CreateFNegFMF(), llvm::BinaryOperator::CreateFSubFMF(), llvm::CastInst::CreateIntegerCast(), llvm::BinaryOperator::CreateNeg(), CreateNonTerminatorUnreachable(), llvm::BinaryOperator::CreateNot(), llvm::BinaryOperator::CreateNSW(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUW(), llvm::UnaryOperator::CreateWithCopiedFlags(), llvm::Data, llvm::InstCombiner::DL, llvm::CallBase::doesNotThrow(), llvm::Function::doesNotThrow(), llvm::Value::dropDroppableUse(), llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::EnableKnowledgeRetention, eraseInstFromFunction(), factorizeMinMaxTree(), foldBitOrderCrossLogicOp(), foldClampRangeOfTwo(), foldCtpop(), foldCttzCtlz(), foldIdempotentBinaryIntrinsicRecurrence(), foldIntrinsicUsingDistributiveLaws(), foldMinimumOverTrailingOrLeadingZeroCount(), foldNeonShift(), foldOpIntoPhi(), FoldOpIntoSelect(), foldReversedIntrinsicOperands(), foldShuffledIntrinsicOperands(), llvm::ConstantAggregateZero::get(), llvm::ConstantPointerNull::get(), llvm::ConstantPtrAuth::get(), llvm::MDNode::get(), llvm::APInt::getAllOnes(), llvm::Constant::getAllOnesValue(), llvm::CallBase::getArgOperand(), llvm::InstCombiner::getAssumptionCache(), llvm::APInt::getBitWidth(), llvm::ConstantRange::getBitWidth(), llvm::KnownBits::getBitWidth(), llvm::ConstantInt::getBool(), getCalledFunction(), llvm::CallBase::getCalledOperand(), llvm::Value::getContext(), llvm::InstCombiner::getDominatorTree(), llvm::VectorType::getElementCount(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::getFreedOperand(), llvm::InstCombiner::getFreelyInverted(), llvm::Instruction::getFunction(), llvm::Type::getInt64Ty(), llvm::Constant::getIntegerValue(), llvm::CallBase::getIntrinsicID(), llvm::getInverseMinMaxIntrinsic(), llvm::getKnowledgeFromBundle(), llvm::getKnowledgeFromOperandInAssume(), llvm::getKnownAlignment(), getKnownSign(), getKnownSignOrZero(), llvm::getLosslessSignedTrunc(), llvm::getLosslessUnsignedTrunc(), llvm::APInt::getLowBitsSet(), llvm::APSInt::getMaxValue(), llvm::APSInt::getMinValue(), llvm::Instruction::getModule(), llvm::ConstantExpr::getNeg(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::CmpInst::getNonStrictPredicate(), llvm::Constant::getNullValue(), llvm::APFloat::getOne(), getOpcode(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::ConstantExpr::getPointerCast(), llvm::MinMaxIntrinsic::getPredicate(), llvm::CallBase::getRetAlign(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMinValue(), llvm::APInt::getSignMask(), llvm::InstCombiner::getSimplifyQuery(), llvm::getSplatValue(), llvm::ConstantExpr::getSub(), llvm::CmpInst::getSwappedPredicate(), llvm::OperandBundleUse::getTagID(), llvm::OperandBundleUse::getTagName(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::getUnderlyingObject(), llvm::getVScaleRange(), llvm::Attribute::getWithAlignment(), GuardWideningWindow, hasNoSignedWrap(), llvm::Value::hasOneUse(), llvm::CallBase::hasOperandBundles(), llvm::CallBase::hasRetAttr(), I, llvm::ConstantRange::icmp(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, II, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::OperandBundleUse::Inputs, llvm::FMFSource::intersect(), llvm::RetainedKnowledge::IRArgValue, llvm::isa(), llvm::KnownBits::isAllOnes(), llvm::isAssumeWithEmptyBundle(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isFixed(), llvm::InstCombiner::isFreeToInvert(), llvm::ConstantRange::isFullSet(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGT(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownLT(), llvm::isKnownNegation(), llvm::isKnownNonZero(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::APFloat::isNegative(), llvm::APInt::isNonNegative(), llvm::KnownBits::isNonZero(), llvm::isNotCrossLaneOperation(), llvm::isPowerOf2_32(), llvm::isPowerOf2_64(), llvm::isSafeToSpeculativelyExecute(), llvm::isSafeToSpeculativelyExecuteWithVariableReplaced(), llvm::MinMaxIntrinsic::isSigned(), llvm::isValidAssumeForContext(), llvm::APInt::isZero(), llvm_unreachable, llvm::Log2(), llvm::Log2_32_Ceil(), llvm::lowerObjectSizeCall(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_c_Select(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_CopySign(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ExtractValue(), llvm::PatternMatch::m_FAbs(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_FShl(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_LogicalShift(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_NegatedPower2(), llvm::PatternMatch::m_NegZeroFP(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NSWAddLike(), llvm::PatternMatch::m_NSWNeg(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_NUWAddLike(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_NUWSub(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_PtrToIntOrAddr(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_StrictlyPositive(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_UnOp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSExtOrSelf(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), matchBSwapOrBitReverse(), llvm::Value::MaxAlignmentExponent, llvm::maximum(), llvm::maxnum(), llvm::MayOverflow, MI, llvm::MinAlign(), llvm::minimum(), llvm::minnum(), Mod, moveAddAfterMinMax(), llvm::Instruction::moveBefore(), llvm::ConstantRange::multiply(), llvm::NeverOverflows, llvm::Next, llvm::None, llvm::Null, llvm::NullPointerIsDefined(), llvm::Offset, Op0, llvm::Other, llvm::PoisonMaskElem, llvm::SmallVectorTemplateBase< T, bool >::push_back(), reassociateMinMaxWithConstantInOperand(), reassociateMinMaxWithConstants(), llvm::CallBase::removeOperandBundle(), removeTriviallyEmptyRange(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::InstCombiner::replaceUse(), llvm::Reverse, llvm::APFloatBase::rmNearestTiesToEven, llvm::APInt::sadd_ov(), llvm::scalbn(), Scaled, Select, llvm::CallBase::setCalledFunction(), llvm::CallBase::setDoesNotThrow(), llvm::FastMathFlags::setNoSignedZeros(), llvm::APInt::sgt(), signBitMustBeTheSame(), SimplifyAnyMemSet(), SimplifyAnyMemTransfer(), llvm::simplifyCall(), llvm::simplifyConstrainedFPCall(), SimplifyDemandedBits(), SimplifyDemandedInstructionBits(), SimplifyDemandedVectorElts(), llvm::simplifyFMAFMul(), llvm::simplifyFMulInst(), simplifyInvariantGroupIntrinsic(), simplifyNeonTbl(), simplifyReductionOperand(), llvm::simplifyRetainedKnowledge(), llvm::Splat, llvm::InstCombiner::SQ, std::swap(), llvm::InstCombiner::targetInstCombineIntrinsic(), llvm::InstCombiner::TLI, llvm::APInt::uadd_ov(), llvm::APInt::uadd_sat(), llvm::APInt::ugt(), llvm::APInt::urem(), llvm::Value::use_empty(), llvm::MaybeAlign::valueOrOne(), visitFree(), llvm::RetainedKnowledge::WasOn, llvm::InstCombiner::Worklist, X, Y, and llvm::ConstantRange::zextOrTrunc().
Referenced by ~InstCombinerImpl().
visitExtractElementInst()
Instruction * InstCombinerImpl::visitExtractElementInst (ExtractElementInst & EI)
Definition at line 404 of file InstCombineVectorOps.cpp.
References llvm::BitWidth, llvm::InstCombiner::Builder, llvm::cast(), cheapToScalarize(), llvm::count_if(), llvm::CastInst::Create(), llvm::ExtractElementInst::Create(), llvm::GetElementPtrInst::Create(), llvm::BinaryOperator::CreateWithCopiedFlags(), llvm::CmpInst::CreateWithCopiedFlags(), llvm::UnaryOperator::CreateWithCopiedFlags(), llvm::dyn_cast(), findDemandedEltsByAllUsers(), FoldOpIntoSelect(), GEP, llvm::PoisonValue::get(), llvm::Value::getContext(), llvm::VectorType::getElementCount(), llvm::ExtractElementInst::getIndexOperand(), llvm::Type::getInt64Ty(), llvm::BinaryOperator::getOpcode(), llvm::CmpInst::getOpcode(), llvm::UnaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), getPreferredVectorIndex(), llvm::getSplatIndex(), llvm::Value::getType(), llvm::ExtractElementInst::getVectorOperand(), llvm::ExtractElementInst::getVectorOperandType(), llvm::Value::hasOneUse(), I, II, llvm::isa(), llvm::APInt::isAllOnes(), llvm::isSafeToSpeculativelyExecuteWithVariableReplaced(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_UnOp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::APInt::setBit(), llvm::GetElementPtrInst::setNoWrapFlags(), SimplifyDemandedVectorElts(), llvm::simplifyExtractElementInst(), llvm::InstCombiner::SQ, llvm::InstCombiner::Worklist, X, and Y.
Referenced by ~InstCombinerImpl().
visitExtractValueInst()
Instruction * InstCombinerImpl::visitExtractValueInst (ExtractValueInst & EV)
Definition at line 4589 of file InstructionCombining.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), Cond, llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::dyn_cast(), foldFrexpOfSelect(), foldOpIntoPhi(), FoldOpIntoSelect(), GEP, llvm::ExtractValueInst::getAggregateOperand(), llvm::ExtractValueInst::getIndices(), llvm::Value::getType(), llvm::ExtractValueInst::hasIndices(), llvm::ExtractValueInst::idx_begin(), llvm::ExtractValueInst::idx_end(), llvm::ExtractValueInst::indices(), IV, llvm::PatternMatch::m_ExtractValue(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setAAMetadata(), llvm::simplifyExtractValueInst(), and llvm::InstCombiner::SQ.
Referenced by ~InstCombinerImpl().
visitFAdd()
Instruction * InstCombinerImpl::visitFAdd (BinaryOperator & I)
Definition at line 1992 of file InstCombineAddSub.cpp.
References A(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::canIgnoreSignBitOfZero(), llvm::ConstantFoldBinaryOpOperands(), llvm::BinaryOperator::CreateFAddFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::BinaryOperator::CreateFSubFMF(), llvm::InstCombiner::DL, llvm::InstCombiner::F, factorizeFAddFSub(), foldBinOpIntoSelectOrPhi(), foldBinopWithPhiOperands(), foldSquareSumFP(), foldVectorBinop(), I, llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_c_FAdd(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_c_Intrinsic(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_FAdd(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), simplify, SimplifyAssociativeOrCommutative(), llvm::simplifyFAddInst(), SimplifySelectsFeedingBinaryOp(), llvm::InstCombiner::SQ, X, and Y.
Referenced by ~InstCombinerImpl().
visitFCmpInst()
Instruction * InstCombinerImpl::visitFCmpInst (FCmpInst & I)
Orders the operands of the compare so that they are listed from most complex to least complex. This puts constants before unary operators, before binary operators.
Definition at line 8716 of file InstCombineCompares.cpp.
References A(), assert(), B(), llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::APFloat::clearSign(), llvm::ConstantFoldUnaryOpOperand(), llvm::APFloat::convert(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::SelectPatternResult::Flavor, foldCmpLoadFromIndexedGlobal(), foldFabsWithFcmpZero(), foldFCmpFNegCommonOp(), foldFCmpFpTrunc(), foldFCmpFSubIntoFCmp(), foldFCmpIntToFPConst(), foldFCmpReciprocalAndZero(), foldFCmpWithFloorAndCeil(), foldOpIntoPhi(), FoldOpIntoSelect(), foldSqrtWithFcmpZero(), foldVectorCmp(), GEP, llvm::VectorType::get(), llvm::InstCombiner::getComplexity(), llvm::ConstantInt::getFalse(), llvm::Constant::getNullValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::InstCombiner::getSimplifyQuery(), llvm::APFloat::getSmallestNormalized(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), llvm::ConstantFP::getZero(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SLT, llvm::FCmpInst::isEquality(), llvm::isKnownNeverNaN(), isMinMaxCmpSelectEliminable(), llvm::APFloat::isZero(), llvm_unreachable, llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_c_Select(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_FAdd(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::APFloatBase::rmNearestTiesToEven, llvm::simplifyFCmpInst(), llvm::SPF_FMAXNUM, llvm::SPF_FMINNUM, llvm::SPF_UNKNOWN, llvm::InstCombiner::SQ, X, and Y.
Referenced by ~InstCombinerImpl().
visitFDiv()
Instruction * InstCombinerImpl::visitFDiv (BinaryOperator & I)
Definition at line 2119 of file InstCombineMulDivRem.cpp.
References B(), llvm::InstCombiner::Builder, llvm::cast(), convertFSqrtDivIntoFMul(), llvm::BinaryOperator::CreateFDivFMF(), llvm::BinaryOperator::CreateFMulFMF(), D(), llvm::dyn_cast(), llvm::emitUnaryFloatFnCall(), foldBinopWithPhiOperands(), foldFDivConstantDividend(), foldFDivPowDivisor(), foldFDivSqrtDivisor(), FoldOpIntoSelect(), foldPowiReassoc(), foldVectorBinop(), llvm::hasFloatFn(), I, llvm::isa(), isFSqrtDivToFMulLegal(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_FAbs(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Mul, Op0, R2, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::simplifyFDivInst(), llvm::InstCombiner::SQ, llvm::InstCombiner::TLI, X, and Y.
Referenced by ~InstCombinerImpl().
visitFenceInst()
Instruction * InstCombinerImpl::visitFenceInst (FenceInst & FI)
Definition at line 4263 of file InstCombineCalls.cpp.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), eraseInstFromFunction(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::FenceInst::getOrdering(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::FenceInst::getSyncScopeID(), llvm::isAtLeastOrStrongerThan(), llvm::Instruction::isIdenticalTo(), llvm::SyncScope::SingleThread, and llvm::SyncScope::System.
Referenced by ~InstCombinerImpl().
visitFMul()
Instruction * InstCombinerImpl::visitFMul (BinaryOperator & I)
Definition at line 960 of file InstCombineMulDivRem.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldUnaryOpOperand(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateFMulFMF(), llvm::UnaryOperator::CreateFNegFMF(), llvm::BinaryOperator::CreateFSubFMF(), llvm::InstCombiner::DL, foldBinOpIntoSelectOrPhi(), foldBinopWithPhiOperands(), foldFMulReassoc(), foldMulSelectToNegate(), foldVectorBinop(), I, llvm::isKnownNeverNaN(), llvm::APFloat::isNegative(), llvm::APFloat::isZero(), llvm::Log2(), llvm::PatternMatch::m_APFloatAllowPoison(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_c_Intrinsic(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::matchSimpleRecurrence(), Op0, llvm::InstCombiner::replaceInstUsesWith(), SimplifyAssociativeOrCommutative(), llvm::simplifyFMulInst(), SimplifySelectsFeedingBinaryOp(), llvm::InstCombiner::SQ, X, and Y.
Referenced by ~InstCombinerImpl().
visitFNeg()
Instruction * InstCombinerImpl::visitFNeg (UnaryOperator & I)
Definition at line 3048 of file InstCombineAddSub.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), Cond, llvm::Instruction::copyFastMathFlags(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateFSubFMF(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldFNegIntoConstant(), llvm::InstCombiner::getSimplifyQuery(), I, llvm::isGuaranteedNotToBeUndefOrPoison(), llvm::PatternMatch::m_CopySign(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_ImmConstant(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Poison(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VecReverse(), llvm::PatternMatch::match(), P, llvm::InstCombiner::replaceInstUsesWith(), llvm::Reverse, llvm::Instruction::setFastMathFlags(), llvm::Instruction::setHasNoSignedZeros(), llvm::simplifyFNegInst(), X, and Y.
Referenced by ~InstCombinerImpl().
visitFPExt()
Instruction * InstCombinerImpl::visitFPExt (CastInst & CI)
Definition at line 2235 of file InstCombineCasts.cpp.
References llvm::cast(), commonCastTransforms(), llvm::CastInst::Create(), llvm::User::getOperand(), llvm::Value::getType(), llvm::isa(), and isKnownExactCastIntToFP().
Referenced by ~InstCombinerImpl().
visitFPToSI()
Instruction * InstCombinerImpl::visitFPToSI (FPToSIInst & FI)
Definition at line 2315 of file InstCombineCasts.cpp.
References commonCastTransforms(), foldFPtoI(), foldItoFPtoI(), and I.
Referenced by ~InstCombinerImpl().
visitFPToUI()
Instruction * InstCombinerImpl::visitFPToUI (FPToUIInst & FI)
Definition at line 2305 of file InstCombineCasts.cpp.
References commonCastTransforms(), foldFPtoI(), foldItoFPtoI(), and I.
Referenced by ~InstCombinerImpl().
visitFPTrunc()
Instruction * InstCombinerImpl::visitFPTrunc (FPTruncInst & CI)
Definition at line 2047 of file InstCombineCasts.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), commonCastTransforms(), Cond, llvm::Instruction::copyFastMathFlags(), llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::CastInst::Create(), llvm::BinaryOperator::CreateFDivFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::CastInst::CreateFPCast(), llvm::dyn_cast(), llvm::Instruction::getFastMathFlags(), llvm::Type::getFPMantissaWidth(), getMinimumFPType(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::CastInst::getSrcTy(), llvm::Value::getType(), I, II, llvm::isa(), isKnownExactCastIntToFP(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), shrinkInsertElt(), X, and Y.
Referenced by ~InstCombinerImpl().
visitFree()
Instruction * InstCombinerImpl::visitFree (CallInst & FI, Value * FreedOp)
Definition at line 4007 of file InstructionCombining.cpp.
References CreateNonTerminatorUnreachable(), llvm::InstCombiner::DL, llvm::dyn_cast(), eraseInstFromFunction(), llvm::getReallocatedOperand(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::InstCombiner::MinimizeSize, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::TLI, and tryToMoveFreeBeforeNullTest().
Referenced by visitCallInst(), and ~InstCombinerImpl().
visitFreeze()
Instruction * InstCombinerImpl::visitFreeze (FreezeInst & I)
Definition at line 5245 of file InstructionCombining.cpp.
References llvm::InstCombiner::AC, assert(), llvm::CallingConv::C, llvm::InstCombiner::DT, llvm::dyn_cast(), foldFreezeIntoRecurrence(), foldOpIntoPhi(), freezeOtherUses(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::ConstantInt::getTrue(), I, llvm::isGuaranteedNotToBeUndefOrPoison(), isUsedWithinShuffleVector(), llvm::PatternMatch::m_c_Select(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Freeze(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, PHI, pushFreezeToPreventPoisonFromPropagating(), llvm::InstCombiner::replaceInstUsesWith(), llvm::Constant::replaceUndefsWith(), llvm::simplifyFreezeInst(), and llvm::InstCombiner::SQ.
Referenced by ~InstCombinerImpl().
visitFRem()
Instruction * InstCombinerImpl::visitFRem (BinaryOperator & I)
Definition at line 2557 of file InstCombineMulDivRem.cpp.
References foldBinopWithPhiOperands(), foldVectorBinop(), I, llvm::InstCombiner::replaceInstUsesWith(), llvm::simplifyFRemInst(), llvm::InstCombiner::SQ, and X.
Referenced by ~InstCombinerImpl().
visitFSub()
Instruction * InstCombinerImpl::visitFSub (BinaryOperator & I)
Definition at line 3140 of file InstCombineAddSub.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cannotBeNegativeZero(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldUnaryOpOperand(), llvm::BinaryOperator::CreateFAddFMF(), llvm::BinaryOperator::CreateFMulFMF(), llvm::UnaryOperator::CreateFNegFMF(), llvm::BinaryOperator::CreateFSubFMF(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::InstCombiner::F, factorizeFAddFSub(), llvm::FAdd, llvm::FMul, foldBinopWithPhiOperands(), foldFNegIntoConstant(), FoldOpIntoSelect(), foldVectorBinop(), llvm::InstCombiner::getSimplifyQuery(), llvm::Value::getType(), I, llvm::isa(), llvm::PatternMatch::m_c_FAdd(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_FPTrunc(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), simplify, llvm::simplifyFSubInst(), SimplifySelectsFeedingBinaryOp(), llvm::Sub, X, and Y.
Referenced by ~InstCombinerImpl().
visitGEPOfGEP()
Instruction * InstCombinerImpl::visitGEPOfGEP (GetElementPtrInst & GEP, GEPOperator * Src)
Definition at line 2833 of file InstructionCombining.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeGEPOfConstGEPI8(), llvm::cast(), combineConstantOffsets(), llvm::count_if(), llvm::dyn_cast(), GEP, llvm::gep_type_begin(), llvm::gep_type_end(), getMergedGEPNoWrapFlags(), llvm::Value::getType(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InstCombiner::replaceInstUsesWith(), shouldMergeGEPs(), llvm::simplifyAddInst(), and llvm::InstCombiner::SQ.
Referenced by visitGetElementPtrInst(), and ~InstCombinerImpl().
visitGetElementPtrInst()
Instruction * InstCombinerImpl::visitGetElementPtrInst (GetElementPtrInst & GEP)
Definition at line 3225 of file InstructionCombining.cpp.
References llvm::all_of(), llvm::any_of(), llvm::append_range(), llvm::ArrayRef(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::countr_zero(), llvm::GetElementPtrInst::Create(), llvm::GetElementPtrInst::CreateInBounds(), llvm::InstCombiner::DL, llvm::drop_begin(), llvm::drop_end(), llvm::dyn_cast(), llvm::enumerate(), foldGEPOfPhi(), foldSelectGEP(), llvm::SmallVectorTemplateCommon< T, typename >::front(), GEP, llvm::gep_type_begin(), llvm::VectorType::get(), llvm::APInt::getAllOnes(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::GetElementPtrInst::getIndexedType(), llvm::Constant::getNullValue(), llvm::Type::getPointerAddressSpace(), llvm::Value::getPointerDereferenceableBytes(), llvm::Type::getScalarSizeInBits(), llvm::getSplatValue(), llvm::Value::getType(), llvm::has_single_bit(), I, llvm::isa(), llvm::APInt::isAllOnes(), llvm::Type::isIntegerTy(), llvm::APInt::isNonNegative(), llvm::Type::isSized(), llvm::generic_gep_type_iterator< ItTy >::isStruct(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_AddLike(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_IDiv(), llvm::PatternMatch::m_NNegZExt(), llvm::PatternMatch::m_NSWAddLike(), llvm::PatternMatch::m_NUWAddLike(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_PtrToIntOrAddr(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_SExtLike(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::GEPNoWrapFlags::none(), llvm::GEPNoWrapFlags::noUnsignedWrap(), llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::APInt::sdivrem(), shouldCanonicalizeGEPToPtrAdd(), SimplifyDemandedVectorElts(), llvm::simplifyGEPInst(), llvm::InstCombiner::SQ, llvm::Value::stripAndAccumulateInBoundsConstantOffsets(), llvm::ArrayRef< T >::take_front(), llvm::APInt::udivrem(), llvm::APInt::ule(), visitGEPOfGEP(), X, and Y.
Referenced by ~InstCombinerImpl().
visitICmpInst()
Instruction * InstCombinerImpl::visitICmpInst (ICmpInst & I)
Orders the operands of the compare so that they are listed from most complex to least complex. This puts constants before unary operators, before binary operators.
Definition at line 7648 of file InstCombineCompares.cpp.
References A(), llvm::AllOnes, assert(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeCmpWithConstant(), canonicalizeICmpBool(), canonicalizeICmpPredicate(), llvm::cast(), Cond, llvm::CmpInst::Create(), llvm::ExtractValueInst::Create(), llvm::SelectInst::Create(), D(), llvm::InstCombiner::DL, llvm::dyn_cast(), eraseInstFromFunction(), llvm::SelectPatternResult::Flavor, foldAllocaCmp(), foldICmpBinOp(), foldICmpBitCast(), foldICmpCommutative(), foldICmpEquality(), foldICmpInstWithConstant(), foldICmpInstWithConstantNotInt(), foldICmpInvariantGroup(), foldICmpOfUAddOv(), foldICmpPow2Test(), foldICmpTruncWithTruncOrExt(), foldICmpUsingBoolRange(), foldICmpUsingKnownBits(), foldICmpWithCastOp(), foldICmpWithConstant(), foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), foldICmpWithZero(), foldIsMultipleOfAPowerOfTwo(), foldOpIntoPhi(), foldReductionIdiom(), foldSignBitTest(), foldVectorCmp(), llvm::APInt::getActiveBits(), llvm::Constant::getAllOnesValue(), llvm::APInt::getBitWidth(), llvm::InstCombiner::getComplexity(), llvm::InstCombiner::getFreelyInverted(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::Instruction::getOpcode(), llvm::Type::getScalarSizeInBits(), llvm::CmpPredicate::getSwapped(), llvm::getUnderlyingObject(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::InstCombiner::isFreeToInvert(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Instruction(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UAddWithOverflow(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), llvm::matchSelectPattern(), Op0, processUMulZExtIdiom(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::APInt::setBit(), llvm::simplifyICmpInst(), llvm::SPF_UNKNOWN, llvm::InstCombiner::SQ, std::swap(), llvm::APInt::trunc(), llvm::APInt::uge(), X, and Y.
Referenced by ~InstCombinerImpl().
visitInsertElementInst()
Instruction * InstCombinerImpl::visitInsertElementInst (InsertElementInst & IE)
Definition at line 1710 of file InstCombineVectorOps.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), collectShuffleElements(), llvm::InsertElementInst::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldConstantInsEltIntoShuffle(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), foldTruncInsEltPair(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::VectorType::get(), llvm::APInt::getAllOnes(), getPreferredVectorIndex(), llvm::Value::getType(), llvm::Value::hasOneUse(), hoistInsEltConst(), llvm::isa(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ExtractElt(), llvm::PatternMatch::m_InsertElt(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), narrowInsElt(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), SimplifyDemandedVectorElts(), llvm::simplifyInsertElementInst(), llvm::Splat, and llvm::InstCombiner::SQ.
Referenced by ~InstCombinerImpl().
visitInsertValueInst()
Instruction * InstCombinerImpl::visitInsertValueInst (InsertValueInst & I)
Try to find redundant insertvalue instructions, like the following ones: %0 = insertvalue { i8, i32 } undef, i8 x, 0 %1 = insertvalue { i8, i32 } %0, i8 y, 0 Here the second instruction inserts values at the same indices, as the first one, making the first one redundant.
It should be transformed to: %0 = insertvalue { i8, i32 } undef, i8 y, 0
Definition at line 1252 of file InstCombineVectorOps.cpp.
References llvm::Depth, llvm::dyn_cast(), foldAggregateConstructionIntoAggregateReuse(), I, llvm::InstCombiner::replaceInstUsesWith(), llvm::simplifyInsertValueInst(), llvm::InstCombiner::SQ, and llvm::Value::user_back().
Referenced by ~InstCombinerImpl().
visitInstruction()
Instruction * llvm::InstCombinerImpl::visitInstruction (Instruction & I) inline
Specify what to return for unhandled instructions.
Definition at line 190 of file InstCombineInternal.h.
References I.
visitIntToPtr()
Instruction * InstCombinerImpl::visitIntToPtr (IntToPtrInst & CI)
Definition at line 2347 of file InstCombineCasts.cpp.
References llvm::all_of(), llvm::sampleprof::Base, llvm::InstCombiner::Builder, commonCastTransforms(), llvm::GetElementPtrInst::Create(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::IntToPtrInst::getAddressSpace(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Type::getPointerAddressSpace(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getWithNewType(), I, llvm::isa(), llvm::PatternMatch::m_c_Add(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_PtrToIntSameSize(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::Offset, P, and llvm::Value::users().
Referenced by ~InstCombinerImpl().
visitInvokeInst()
Instruction * InstCombinerImpl::visitInvokeInst (InvokeInst & II)
Definition at line 4291 of file InstCombineCalls.cpp.
References II.
Referenced by ~InstCombinerImpl().
visitLandingPadInst()
Instruction * InstCombinerImpl::visitLandingPadInst (LandingPadInst & LI)
Definition at line 4755 of file InstructionCombining.cpp.
References llvm::LandingPadInst::addClause(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CallingConv::C, llvm::cast(), llvm::classifyEHPersonality(), llvm::LandingPadInst::Create(), llvm::dyn_cast(), llvm::SmallVectorImpl< T >::erase(), llvm::Filter, llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::LandingPadInst::getClause(), llvm::ArrayType::getElementType(), llvm::Constant::getNullValue(), llvm::LandingPadInst::getNumClauses(), llvm::ArrayType::getNumElements(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), getType(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::LandingPadInst::isCatch(), isCatchAll(), llvm::LandingPadInst::isCleanup(), llvm::LandingPadInst::isFilter(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::LandingPadInst::setCleanup(), shorter_filter(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Constant::stripPointerCasts(), and llvm::Value::stripPointerCasts().
Referenced by ~InstCombinerImpl().
visitLoadInst()
Instruction * InstCombinerImpl::visitLoadInst (LoadInst & LI)
Definition at line 1087 of file InstCombineLoadStoreAlloca.cpp.
References llvm::InstCombiner::AA, assert(), llvm::InstCombiner::Builder, canSimplifyNullLoadOrGEP(), llvm::cast(), combineLoadToOperationType(), llvm::combineMetadataForCSE(), llvm::Instruction::copyMetadata(), llvm::SelectInst::Create(), CreateNonTerminatorUnreachable(), llvm::InstCombiner::DL, llvm::dyn_cast(), llvm::FindAvailableLoadedValue(), llvm::PoisonValue::get(), llvm::LoadInst::getAlign(), llvm::Instruction::getFunction(), llvm::Value::getName(), llvm::User::getOperand(), llvm::LoadInst::getOrdering(), llvm::LoadInst::getPointerAddressSpace(), llvm::LoadInst::getSyncScopeID(), llvm::Value::getType(), llvm::isSafeToLoadUnconditionally(), llvm::LoadInst::isUnordered(), llvm::NullPointerIsDefined(), llvm::Metadata::PoisonGeneratingIDs, replaceGEPIdxWithZero(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::LoadInst::setAlignment(), llvm::LoadInst::setAtomic(), llvm::simplifyLoadInst(), llvm::InstCombiner::SQ, and unpackLoadToAggregate().
Referenced by ~InstCombinerImpl().
visitLShr()
Instruction * InstCombinerImpl::visitLShr (BinaryOperator & I)
Definition at line 1280 of file InstCombineShifts.cpp.
References llvm::AllOnes, assert(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), commonShiftTransforms(), llvm::InstCombiner::computeKnownBits(), llvm::BinaryOperator::Create(), llvm::SelectInst::Create(), llvm::dyn_cast(), llvm::APInt::eq(), foldVectorBinop(), llvm::APInt::getAllOnes(), llvm::Constant::getAllOnesValue(), llvm::APInt::getLowBitsSet(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), getScalarSizeInBits(), llvm::ConstantInt::getSigned(), getType(), llvm::Value::getType(), llvm::APInt::getZExtValue(), hasNoSignedWrap(), llvm::Instruction::hasNoSignedWrap(), hasNoUnsignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, II, llvm::Type::isIntOrIntVectorTy(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::isPowerOf2_32(), llvm::Log2_32(), llvm::APInt::logBase2(), llvm::APInt::lshr(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LShr(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_NUWSub(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), setShiftFlags(), llvm::APInt::shl(), llvm::simplifyLShrInst(), llvm::InstCombiner::SQ, llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ult(), X, and Y.
Referenced by ~InstCombinerImpl().
visitMul()
Instruction * InstCombinerImpl::visitMul (BinaryOperator & I)
Definition at line 193 of file InstCombineMulDivRem.cpp.
References assert(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldBinaryOpOperands(), llvm::APInt::countr_zero(), llvm::CastInst::Create(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateExact(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::InstCombiner::DL, llvm::dyn_cast(), foldBinOpIntoSelectOrPhi(), foldBinOpOfSelectAndCastOfSelectCondition(), foldBinOpSelectBinOp(), foldBinopWithPhiOperands(), foldMulSelectToNegate(), foldMulShl1(), foldUsingDistributiveLaws(), foldVectorBinop(), llvm::ConstantInt::getBool(), llvm::ConstantExpr::getExactLogBase2(), llvm::ConstantExpr::getNeg(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::APInt::getZExtValue(), hasNoSignedWrap(), llvm::Value::hasOneUse(), I, llvm::APInt::isAllOnes(), llvm::Instruction::isExact(), llvm::isGuaranteedNotToBeUndef(), llvm::Constant::isNotMinSignedValue(), llvm::APInt::isZero(), llvm::APInt::logBase2(), llvm::PatternMatch::m_AddLike(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_CheckedInt(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_NegatedPower2(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::CmpInst::makeCmpResultType(), llvm::PatternMatch::match(), Mul, N, llvm::Negator::Negate(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::APInt::sdivrem(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), SimplifyAssociativeOrCommutative(), llvm::simplifyMulInst(), llvm::InstCombiner::SQ, llvm::Value::takeName(), tryGetLog2(), X, and Y.
Referenced by ~InstCombinerImpl().
visitOr()
Instruction * InstCombinerImpl::visitOr (BinaryOperator & I)
Res, Overflow = xxx_with_overflow X, C1 Try to canonicalize the pattern "Overflow | icmp pred Res, C2" into "Overflow | icmp pred X, C2 +/- C1".
Definition at line 4029 of file InstCombineAndOrXor.cpp.
References A(), llvm::AllOnes, B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeLogicFirst(), llvm::cast(), llvm::InstCombiner::computeKnownBits(), Concat, llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNot(), D(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), foldAddLikeCommutative(), foldBinOpIntoSelectOrPhi(), foldBinOpSelectBinOp(), foldBinOpShiftWithShift(), foldBinopWithPhiOperands(), foldBitwiseLogicWithIntrinsics(), foldComplexAndOrPatterns(), foldIntegerPackFromVector(), foldOrOfInversions(), FoldOrOfSelectSmaxToAbs(), foldOrToXor(), foldOrUnsignedUMulOverflowICmp(), foldUsingDistributiveLaws(), foldVectorBinop(), llvm::Constant::getAllOnesValue(), llvm::BinaryOpIntrinsic::getBinaryOp(), llvm::Type::getFltSemantics(), llvm::BinaryOpIntrinsic::getLHS(), llvm::Constant::getNullValue(), llvm::BinaryOpIntrinsic::getRHS(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::APFloatBase::hasSignBitInMSB(), I, llvm::CmpInst::ICMP_NE, llvm::isa(), llvm::APInt::isAllOnes(), llvm::ICmpInst::isEquality(), llvm::Type::isFloatingPointTy(), llvm::BinaryOpIntrinsic::isSigned(), llvm::CmpInst::isSigned(), isZero(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_DisjointOr(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_ExtractValue(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_Mul(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_WithOverflowInst(), llvm::PatternMatch::m_Xor(), llvm::MIPatternMatch::m_ZeroInt(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), matchBSwapOrBitReverse(), matchDeMorgansLaws(), matchFunnelShift(), matchOrConcat(), llvm::matchSimpleRecurrence(), Mul, llvm::KnownBits::One, Op0, reassociateFCmps(), reassociateForUses(), llvm::InstCombiner::replaceInstUsesWith(), llvm::APInt::sadd_ov(), SimplifyAddWithRemainder(), simplifyAndOrWithOpReplaced(), SimplifyAssociativeOrCommutative(), SimplifyDemandedInstructionBits(), llvm::simplifyOrInst(), sinkNotIntoOtherHandOfLogicalOp(), llvm::InstCombiner::SQ, llvm::APInt::ssub_ov(), llvm::Sub, std::swap(), llvm::Value::takeName(), tryFoldInstWithCtpopWithNot(), llvm::APInt::uadd_ov(), llvm::APInt::usub_ov(), X, llvm::Xor, and Y.
Referenced by ~InstCombinerImpl().
visitPHINode()
Instruction * InstCombinerImpl::visitPHINode (PHINode & PN)
Definition at line 1433 of file InstCombinePHI.cpp.
References llvm::all_of(), llvm::cast(), llvm::CastInst::CreatePointerCast(), llvm::dyn_cast(), foldDeadPhiWeb(), foldIntegerTypedPHI(), foldPHIArgIntToPtrToPHI(), foldPHIArgOpIntoPHI(), foldPHIArgZextsIntoPHI(), llvm::PoisonValue::get(), getAnyNonZeroConstInt(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::InstCombiner::getSimplifyQuery(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Value::hasNUsesOrMore(), llvm::Value::hasOneUse(), I, if(), llvm::PHINode::incoming_values(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::CmpInst::isEquality(), llvm::isKnownNonZero(), llvm::Type::isPointerTy(), IV, llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::simplifyInstruction(), llvm::InstCombiner::SQ, llvm::Value::stripPointerCasts(), llvm::Instruction::user_back(), and llvm::Value::users().
Referenced by ~InstCombinerImpl().
visitPtrToAddr()
Instruction * InstCombinerImpl::visitPtrToAddr (PtrToAddrInst & CI)
Definition at line 2466 of file InstCombineCasts.cpp.
References llvm::InstCombiner::Builder, commonCastTransforms(), foldPtrToIntOrAddrOfGEP(), llvm::PtrToAddrInst::getPointerOperand(), llvm::Value::getType(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by ~InstCombinerImpl().
visitPtrToInt()
Instruction * InstCombinerImpl::visitPtrToInt (PtrToIntInst & CI)
Definition at line 2423 of file InstCombineCasts.cpp.
References assert(), llvm::InstCombiner::Builder, commonCastTransforms(), llvm::InsertElementInst::Create(), llvm::CastInst::CreateIntegerCast(), llvm::InstCombiner::DL, foldPtrToIntOrAddrOfGEP(), llvm::Value::getContext(), llvm::PtrToIntInst::getPointerAddressSpace(), llvm::PtrToIntInst::getPointerOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getWithNewType(), llvm::PatternMatch::m_InsertElt(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_IntToPtr(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by ~InstCombinerImpl().
visitReturnInst()
Instruction * InstCombinerImpl::visitReturnInst (ReturnInst & RI)
Definition at line 4047 of file InstructionCombining.cpp.
References llvm::InstCombiner::F, llvm::fcNone, llvm::Instruction::getFunction(), llvm::Type::getPointerAddressSpace(), llvm::ReturnInst::getReturnValue(), llvm::Value::getType(), llvm::AttributeFuncs::isNoFPClassCompatibleType(), llvm::Type::isPointerTy(), llvm::NullPointerIsDefined(), llvm::InstCombiner::replaceOperand(), and SimplifyDemandedFPClass().
Referenced by ~InstCombinerImpl().
visitSDiv()
Instruction * InstCombinerImpl::visitSDiv (BinaryOperator & I)
Definition at line 1759 of file InstCombineMulDivRem.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), commonIDivTransforms(), llvm::InstCombiner::computeKnownBits(), Cond, llvm::KnownBits::countMinTrailingZeros(), llvm::APInt::countr_zero(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNSWNeg(), foldVectorBinop(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getExactLogBase2(), llvm::ConstantExpr::getNeg(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMinValue(), llvm::APInt::getSignificantBits(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), I, llvm::isKnownNegation(), llvm::isKnownNonNegative(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::APInt::isMinSignedValue(), llvm::KnownBits::isNonNegative(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_NegatedPower2(), llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_NSWNeg(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setIsExact(), llvm::simplifySDivInst(), llvm::InstCombiner::SQ, X, and Y.
Referenced by ~InstCombinerImpl().
visitSelectInst()
Instruction * InstCombinerImpl::visitSelectInst (SelectInst & SI)
Definition at line 4221 of file InstCombineSelect.cpp.
References A(), llvm::InstCombiner::AC, llvm::Add, llvm::CondContext::AffectedValues, B(), llvm::sampleprof::Base, llvm::BitWidth, llvm::InstCombiner::Builder, llvm::canIgnoreSignBitOfZero(), canonicalizeScalarSelectOfVecs(), canonicalizeSelectToShuffle(), llvm::cast(), llvm::computeKnownBits(), llvm::InstCombiner::computeKnownBits(), llvm::CallInst::Create(), llvm::GetElementPtrInst::Create(), llvm::SelectInst::Create(), llvm::InstCombiner::DL, llvm::InstCombiner::DT, llvm::dyn_cast(), llvm::SmallPtrSetImplBase::empty(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UNE, llvm::findValuesAffectedByCondition(), llvm::SelectPatternResult::Flavor, foldAddSubSelect(), foldBitCeil(), foldNestedSelects(), foldOpIntoPhi(), foldOverflowingAddSubSelect(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBinOpIdentity(), foldSelectBitTest(), foldSelectCmpBitcasts(), foldSelectCmpXchg(), foldSelectEqualityTest(), foldSelectExtConst(), foldSelectFunnelShift(), foldSelectInstWithICmp(), foldSelectIntoAddConstant(), foldSelectIntoOp(), foldSelectOfBools(), foldSelectOfSymmetricSelect(), foldSelectOpOp(), foldSelectToCmp(), foldSelectToCopysign(), foldSelectToPhi(), foldSelectValueEquivalence(), foldSelectWithFCmpToFabs(), foldSelectWithSRem(), foldSelectZeroOrFixedOp(), foldSetClearBits(), foldSPFofSPF(), foldVectorSelect(), llvm::Constant::getAllOnesValue(), llvm::KnownBits::getConstant(), llvm::ConstantInt::getFalse(), llvm::getMinMaxPred(), llvm::Value::getName(), llvm::GetElementPtrInst::getNoWrapFlags(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::GetElementPtrInst::getPointerOperand(), llvm::GetElementPtrInst::getSourceElementType(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), hasAffectedValue(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::CondContext::Invert, llvm::isa(), llvm::KnownBits::isConstant(), llvm::Type::isFPOrFPVectorTy(), llvm::Instruction::isIntDivRem(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::CmpInst::isIntPredicate(), llvm::isKnownInversion(), llvm::SelectPatternResult::isMinOrMax(), llvm::APInt::isOne(), llvm::CmpInst::isUnordered(), llvm::Type::isVectorTy(), IV, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_MaskedGather(), llvm::PatternMatch::m_MaskedLoad(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NSWTrunc(), llvm::PatternMatch::m_NUWTrunc(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_OrdOrUnordFMax(), llvm::PatternMatch::m_OrdOrUnordFMin(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), matchFMulByZeroIfResultEqZero(), llvm::matchSelectPattern(), Mul, llvm::KnownBits::One, llvm::SelectPatternResult::Ordered, llvm::ProfcheckDisableMetadataFixes, replaceInInstruction(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), Select, llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::InstCombiner::shouldAvoidAbsorbingNotIntoSelect(), llvm::simplifyAndInst(), simplifyNestedSelectsUsingImpliedCond(), llvm::simplifySelectInst(), llvm::simplifyWithOpReplaced(), sinkNotIntoOtherHandOfLogicalOp(), llvm::InstCombiner::SQ, std::swap(), llvm::InstCombiner::TLI, llvm::InstCombiner::Worklist, X, Y, and llvm::KnownBits::Zero.
Referenced by ~InstCombinerImpl().
visitSExt()
Instruction * InstCombinerImpl::visitSExt (SExtInst & Sext)
Definition at line 1742 of file InstCombineCasts.cpp.
References A(), assert(), llvm::InstCombiner::Builder, llvm::cast(), commonCastTransforms(), llvm::InstCombiner::ComputeNumSignBits(), llvm::ConstantFoldCastOperand(), llvm::CastInst::Create(), llvm::CastInst::CreateIntegerCast(), llvm::dbgs(), llvm::InstCombiner::DL, llvm::dyn_cast(), EvaluateInDifferentType(), llvm::Function::getFnAttribute(), llvm::Instruction::getFunction(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getSub(), llvm::Value::getType(), llvm::Attribute::getVScaleRangeMax(), llvm::Function::hasFnAttribute(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::Constant::isElementWiseEqual(), llvm::isKnownNonNegative(), LLVM_DEBUG, llvm::Log2_32(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_LShr(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VScale(), llvm::PatternMatch::match(), llvm::Constant::mergeUndefsWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::SQ, llvm::Instruction::user_back(), X, and Y.
Referenced by ~InstCombinerImpl().
visitShl()
Instruction * InstCombinerImpl::visitShl (BinaryOperator & I)
Definition at line 1042 of file InstCombineShifts.cpp.
References llvm::AllOnes, B(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), commonShiftTransforms(), llvm::BinaryOperator::Create(), dropRedundantMaskingOfLeftShiftInput(), llvm::dyn_cast(), foldVectorBinop(), llvm::Constant::getAllOnesValue(), llvm::APInt::getHighBitsSet(), llvm::Value::getName(), llvm::Constant::getNullValue(), getOpcode(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::APInt::getSignMask(), llvm::APInt::getZExtValue(), I, llvm::Instruction::isCommutative(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), setShiftFlags(), llvm::APInt::shl(), llvm::simplifyShlInst(), llvm::InstCombiner::SQ, std::swap(), llvm::APInt::ult(), X, and Y.
Referenced by ~InstCombinerImpl().
visitShuffleVectorInst()
Instruction * InstCombinerImpl::visitShuffleVectorInst (ShuffleVectorInst & SVI)
Definition at line 2896 of file InstCombineVectorOps.cpp.
References assert(), llvm::InstCombiner::Builder, canEvaluateShuffled(), canonicalizeInsertSplat(), llvm::cast(), llvm::ShuffleVectorInst::commute(), llvm::CastInst::Create(), llvm::createUnaryMask(), llvm::InstCombiner::DL, llvm::dyn_cast(), evaluateInDifferentElementOrder(), foldCastShuffle(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldOpIntoPhi(), FoldOpIntoSelect(), foldSelectShuffle(), foldShuffleOfUnaryOps(), foldShuffleWithInsert(), foldTruncShuffle(), llvm::FixedVectorType::get(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::APInt::getAllOnes(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ShuffleVectorInst::getType(), llvm::Value::getType(), I, llvm::isa(), llvm::isGuaranteedNotToBePoison(), isShuffleExtractingFromLHS(), isSplat(), llvm::VectorType::isValidElementType(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Poison(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), narrowVectorSelect(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::scaleShuffleMaskElts(), simplifyBinOpSplats(), SimplifyDemandedVectorElts(), llvm::simplifyShuffleVectorInst(), llvm::InstCombiner::SQ, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace(), llvm::Value::users(), X, and Y.
Referenced by ~InstCombinerImpl().
visitSIToFP()
Instruction * InstCombinerImpl::visitSIToFP (CastInst & CI)
Definition at line 2335 of file InstCombineCasts.cpp.
References commonCastTransforms(), llvm::CastInst::Create(), llvm::User::getOperand(), llvm::Value::getType(), llvm::isKnownNonNegative(), and llvm::InstCombiner::SQ.
Referenced by ~InstCombinerImpl().
visitSRem()
Instruction * InstCombinerImpl::visitSRem (BinaryOperator & I)
Definition at line 2486 of file InstCombineMulDivRem.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), commonIRemTransforms(), llvm::BinaryOperator::CreateNSWNeg(), llvm::dyn_cast(), foldVectorBinop(), llvm::ConstantVector::get(), llvm::ConstantExpr::getNeg(), llvm::APInt::getSignMask(), I, llvm::isa(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_NSWNeg(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Value(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::simplifySRemInst(), llvm::InstCombiner::SQ, X, and Y.
Referenced by ~InstCombinerImpl().
visitStoreInst()
Instruction * InstCombinerImpl::visitStoreInst (StoreInst & SI)
Definition at line 1418 of file InstCombineLoadStoreAlloca.cpp.
References llvm::InstCombiner::AA, assert(), llvm::begin(), canSimplifyNullStoreOrGEP(), combineStoreToValueType(), llvm::dyn_cast(), equivalentAddressValues(), eraseInstFromFunction(), GEP, llvm::PoisonValue::get(), llvm::Value::getType(), handlePotentiallyDeadBlocks(), handleUnreachableFrom(), llvm::Value::hasOneUse(), llvm::isa(), llvm::isModSet(), llvm::NullPointerIsDefined(), removeInstructionsBeforeUnreachable(), replaceGEPIdxWithZero(), llvm::InstCombiner::replaceOperand(), unpackStoreToAggregate(), and llvm::InstCombiner::Worklist.
Referenced by ~InstCombinerImpl().
visitSub()
Instruction * InstCombinerImpl::visitSub (BinaryOperator & I)
Definition at line 2284 of file InstCombineAddSub.cpp.
References A(), llvm::Add, llvm::InstCombiner::AddOne(), assert(), B(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::cast(), llvm::computeKnownBits(), Cond, llvm::ConstantFoldBinaryInstruction(), llvm::Instruction::copyMetadata(), llvm::APInt::countr_zero(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNot(), llvm::InstCombiner::DL, llvm::dyn_cast(), factorizeMathWithShlOps(), foldBinOpOfSelectAndCastOfSelectCondition(), foldBinopWithPhiOperands(), foldOpIntoPhi(), FoldOpIntoSelect(), foldSubOfMinMax(), foldUsingDistributiveLaws(), foldVectorBinop(), GEP, llvm::Constant::getAllOnesValue(), llvm::InstCombiner::getFreelyInverted(), llvm::APInt::getHighBitsSet(), llvm::Constant::getNullValue(), getScalarSizeInBits(), llvm::ConstantExpr::getSub(), llvm::Value::getType(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::Constant::isElementWiseEqual(), llvm::InstCombiner::isFreeToInvert(), llvm::APInt::isMask(), llvm::APInt::isNegatedPowerOf2(), llvm::APInt::isSubsetOf(), isZero(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AddLike(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_MaxOrMin(), llvm::PatternMatch::m_c_NSWAdd(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Select(), llvm::PatternMatch::m_c_SMax(), llvm::PatternMatch::m_c_SMin(), llvm::PatternMatch::m_c_UMax(), llvm::PatternMatch::m_c_UMin(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Mul(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NSWAdd(), llvm::PatternMatch::m_NSWAddLike(), llvm::PatternMatch::m_NUWAddLike(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_PtrToAddr(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_PtrToIntOrAddr(), llvm::PatternMatch::m_PtrToIntSameSize(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_SExtLike(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::PatternMatch::match_fn(), Mul, llvm::Negator::Negate(), llvm::none_of(), llvm::Offset, Op0, OptimizePointerDifference(), llvm::InstCombiner::replaceInstUsesWith(), Select, llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::simplifySubInst(), llvm::InstCombiner::SQ, llvm::Sub, llvm::InstCombiner::SubOne(), tryFoldInstWithCtpopWithNot(), X, Y, and llvm::KnownBits::Zero.
Referenced by ~InstCombinerImpl().
visitSwitchInst()
Instruction * InstCombinerImpl::visitSwitchInst (SwitchInst & SI)
Definition at line 4326 of file InstructionCombining.cpp.
References llvm::all_of(), llvm::APInt::ashr(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::InstCombiner::computeKnownBits(), Cond, llvm::KnownBits::countMinLeadingOnes(), llvm::KnownBits::countMinLeadingZeros(), llvm::dyn_cast(), llvm::IntegerType::get(), llvm::KnownBits::getBitWidth(), llvm::APInt::getLowBitsSet(), getScalarSizeInBits(), getType(), handlePotentiallyDeadSuccessors(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), llvm::isa(), llvm::APInt::isMaxSignedValue(), llvm::APInt::isMinSignedValue(), llvm::APInt::lshr(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::replaceOperand(), Select, simplifySwitchOnSelectUsingRanges(), and llvm::APInt::trunc().
Referenced by ~InstCombinerImpl().
visitTrunc()
Instruction * InstCombinerImpl::visitTrunc (TruncInst & CI)
Definition at line 970 of file InstCombineCasts.cpp.
References A(), assert(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), commonCastTransforms(), llvm::InstCombiner::ComputeMaxSignificantBits(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldSelectInstruction(), llvm::APInt::countr_one(), llvm::APInt::countr_zero(), llvm::BinaryOperator::Create(), llvm::CastInst::CreateIntegerCast(), llvm::dbgs(), llvm::InstCombiner::DL, llvm::dyn_cast(), EvaluateInDifferentType(), llvm::APInt::exactLogBase2(), foldVecExtTruncToExtElt(), foldVecTruncToExtElt(), llvm::APInt::getBitsSetFrom(), llvm::Function::getFnAttribute(), llvm::Instruction::getFunction(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getSub(), llvm::ConstantInt::getTrue(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::Attribute::getVScaleRangeMax(), llvm::Function::hasFnAttribute(), llvm::TruncInst::hasNoSignedWrap(), llvm::TruncInst::hasNoUnsignedWrap(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::isKnownNonZero(), llvm::Type::isVectorTy(), LLVM_DEBUG, llvm::Log2_32(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_NegatedPower2(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VScale(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_ZExt(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::Constant::mergeUndefsWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::Right, llvm::TruncInst::setHasNoSignedWrap(), llvm::TruncInst::setHasNoUnsignedWrap(), shrinkInsertElt(), shrinkSplatShuffle(), SimplifyDemandedInstructionBits(), llvm::InstCombiner::SQ, X, and Y.
Referenced by ~InstCombinerImpl().
visitUDiv()
Instruction * InstCombinerImpl::visitUDiv (BinaryOperator & I)
Definition at line 1679 of file InstCombineMulDivRem.cpp.
References A(), B(), llvm::InstCombiner::Builder, llvm::cast(), commonIDivTransforms(), llvm::CastInst::CreateZExtOrBitCast(), foldVectorBinop(), llvm::Constant::getAllOnesValue(), I, llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::Log2(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), narrowUDivURem(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setIsExact(), llvm::simplifyUDivInst(), llvm::InstCombiner::SQ, tryGetLog2(), llvm::APInt::ushl_ov(), and X.
Referenced by ~InstCombinerImpl().
visitUIToFP()
Instruction * InstCombinerImpl::visitUIToFP (CastInst & CI)
Definition at line 2325 of file InstCombineCasts.cpp.
References commonCastTransforms(), llvm::User::getOperand(), llvm::Instruction::hasNonNeg(), llvm::isKnownNonNegative(), llvm::Instruction::setNonNeg(), and llvm::InstCombiner::SQ.
Referenced by ~InstCombinerImpl().
visitUnconditionalBranchInst()
Instruction * InstCombinerImpl::visitUnconditionalBranchInst (BranchInst & BI)
Definition at line 4112 of file InstructionCombining.cpp.
References assert(), llvm::dyn_cast(), llvm::BranchInst::isUnconditional(), and mergeStoreIntoSuccessor().
Referenced by visitBranchInst(), and ~InstCombinerImpl().
visitUnreachableInst()
Instruction * InstCombinerImpl::visitUnreachableInst (UnreachableInst & I)
Definition at line 4107 of file InstructionCombining.cpp.
References I, and removeInstructionsBeforeUnreachable().
Referenced by ~InstCombinerImpl().
visitURem()
Instruction * InstCombinerImpl::visitURem (BinaryOperator & I)
Definition at line 2414 of file InstCombineMulDivRem.cpp.
References llvm::Add, llvm::InstCombiner::Builder, commonIRemTransforms(), llvm::SelectInst::Create(), llvm::CastInst::CreateZExtOrBitCast(), foldVectorBinop(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), I, llvm::CmpInst::ICMP_ULT, llvm::isGuaranteedNotToBeUndef(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), narrowUDivURem(), Op0, llvm::InstCombiner::replaceInstUsesWith(), llvm::simplifyICmpInst(), llvm::simplifyURemInst(), llvm::InstCombiner::SQ, llvm::Sub, and X.
Referenced by ~InstCombinerImpl().
visitVAEndInst()
Instruction * InstCombinerImpl::visitVAEndInst (VAEndInst & I)
Definition at line 904 of file InstCombineCalls.cpp.
References I, II, and removeTriviallyEmptyRange().
Referenced by ~InstCombinerImpl().
visitXor()
Instruction * InstCombinerImpl::visitXor (BinaryOperator & I)
Definition at line 5194 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, canonicalizeAbs(), canonicalizeLogicFirst(), llvm::CallInst::Create(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNot(), D(), llvm::dyn_cast(), llvm::InstCombiner::F, foldBinOpIntoSelectOrPhi(), foldBinOpSelectBinOp(), foldBinOpShiftWithShift(), foldBinopWithPhiOperands(), foldBitwiseLogicWithIntrinsics(), foldUsingDistributiveLaws(), foldVectorBinop(), foldXorToXor(), llvm::APInt::getAllOnes(), llvm::Constant::getAllOnesValue(), llvm::Type::getFltSemantics(), llvm::ConstantExpr::getNot(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::ConstantExpr::getXor(), llvm::APFloatBase::hasSignBitInMSB(), I, II, llvm::isa(), llvm::Type::isFloatingPointTy(), llvm::isGuaranteedNotToBeUndef(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::APInt::isSignMask(), llvm::Constant::isZeroValue(), llvm::APInt::lshr(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantExpr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_DisjointOr(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_LShr(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_TruncOrSelf(), llvm::PatternMatch::m_Unless(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::Constant::mergeUndefsWith(), Op0, reassociateForUses(), llvm::InstCombiner::replaceInstUsesWith(), llvm::Constant::replaceUndefsWith(), SimplifyAssociativeOrCommutative(), SimplifyDemandedInstructionBits(), llvm::simplifyXorInst(), llvm::InstCombiner::SQ, std::swap(), visitMaskedMerge(), X, llvm::Xor, and Y.
Referenced by ~InstCombinerImpl().
visitZExt()
Instruction * InstCombinerImpl::visitZExt (ZExtInst & Zext)
Definition at line 1446 of file InstCombineCasts.cpp.
References A(), assert(), llvm::InstCombiner::Builder, llvm::CallingConv::C, commonCastTransforms(), llvm::dbgs(), llvm::InstCombiner::DT, llvm::dyn_cast(), EvaluateInDifferentType(), llvm::Function::getFnAttribute(), llvm::Instruction::getFunction(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getOperand(), getScalarSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Attribute::getVScaleRangeMax(), llvm::Function::hasFnAttribute(), llvm::Instruction::hasNonNeg(), llvm::Value::hasOneUse(), llvm::isa(), llvm::isKnownNonNegative(), LLVM_DEBUG, llvm::Log2_32(), llvm::Log2_64_Ceil(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Constant(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shift(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VScale(), llvm::PatternMatch::m_Xor(), llvm::InstCombiner::MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::replaceAllDbgUsesWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setNonNeg(), llvm::InstCombiner::SQ, llvm::Instruction::user_back(), and X.
Referenced by ~InstCombinerImpl().
The documentation for this class was generated from the following files:
lib/Transforms/InstCombine/InstCombineInternal.h
lib/Transforms/InstCombine/InstCombineAddSub.cpp
lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
lib/Transforms/InstCombine/InstCombineAtomicRMW.cpp
lib/Transforms/InstCombine/InstCombineCalls.cpp
lib/Transforms/InstCombine/InstCombineCasts.cpp
lib/Transforms/InstCombine/InstCombineCompares.cpp
lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp
lib/Transforms/InstCombine/InstCombineMulDivRem.cpp
lib/Transforms/InstCombine/InstCombinePHI.cpp
lib/Transforms/InstCombine/InstCombineSelect.cpp
lib/Transforms/InstCombine/InstCombineShifts.cpp
lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp
lib/Transforms/InstCombine/InstCombineVectorOps.cpp
lib/Transforms/InstCombine/InstructionCombining.cpp