LLVM: llvm::RABasic Class Reference
llvm::RABasic Class Reference
RABasic provides a minimal implementation of the basic register allocation algorithm.
#include "CodeGen/RegAllocBasic.h"
Public Member Functions
RABasic (const RegAllocFilterFunc F=nullptr)
StringRef getPassName () const override
Return the pass name.
void getAnalysisUsage (AnalysisUsage &AU) const override
RABasic analysis usage.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
Spiller & spiller () override
void enqueueImpl (const LiveInterval *LI) override
enqueue - Add VirtReg to the priority queue of unassigned registers.
const LiveInterval * dequeue () override
dequeue - Return the next unassigned register, or NULL.
MCRegister selectOrSplit (const LiveInterval &VirtReg, SmallVectorImpl< Register > &SplitVRegs) override
bool runOnMachineFunction (MachineFunction &mf) override
Perform register allocation.
MachineFunctionProperties getRequiredProperties () const override
MachineFunctionProperties getClearedProperties () const override
bool spillInterferences (const LiveInterval &VirtReg, MCRegister PhysReg, SmallVectorImpl< Register > &SplitVRegs)
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
StringRef getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Static Public Attributes inherited from llvm::RegAllocBase
static bool VerifyEnabled = false
VerifyEnabled - True when -verify-regalloc is given.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getSetProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Member Functions inherited from llvm::RegAllocBase
RegAllocBase (const RegAllocFilterFunc F=nullptr)
virtual ~RegAllocBase ()=default
void init (VirtRegMap &vrm, LiveIntervals &lis, LiveRegMatrix &mat)
bool shouldAllocateRegister (Register Reg)
Get whether a given register should be allocated.
void allocatePhysRegs ()
virtual void postOptimization ()
void cleanupFailedVReg (Register FailedVReg, MCRegister PhysReg, SmallVectorImpl< Register > &SplitRegs)
Perform cleanups on registers that failed to allocate.
void enqueue (const LiveInterval *LI)
enqueue - Add VirtReg to the priority queue of unassigned registers.
MCPhysReg getErrorAssignment (const TargetRegisterClass &RC, const MachineInstr *CtxMI=nullptr)
Query a physical register to use as a filler in contexts where the allocation has failed.
virtual void aboutToRemoveInterval (const LiveInterval &LI)
Method called when the allocator is about to remove a LiveInterval.
Protected Attributes inherited from llvm::RegAllocBase
const TargetRegisterInfo * TRI = nullptr
MachineRegisterInfo * MRI = nullptr
VirtRegMap * VRM = nullptr
LiveIntervals * LIS = nullptr
LiveRegMatrix * Matrix = nullptr
RegisterClassInfo RegClassInfo
SmallPtrSet< MachineInstr *, 32 > DeadRemats
Inst which is a def of an original reg and whose defs are already all dead after remat is saved in DeadRemats.
SmallSet< Register, 2 > FailedVRegs
Static Protected Attributes inherited from llvm::RegAllocBase
static const char TimerGroupName [] = "regalloc"
static const char TimerGroupDescription [] = "Register Allocation"
Detailed Description
RABasic provides a minimal implementation of the basic register allocation algorithm.
It prioritizes live virtual registers by spill weight and spills whenever a register is unavailable. This is not practical in production but provides a useful baseline both for measuring other allocators and comparing the speed of the basic algorithm against other styles of allocators.
Definition at line 37 of file RegAllocBasic.h.
Constructor & Destructor Documentation
RABasic()
RABasic::RABasic (const RegAllocFilterFunc F = nullptr)
Definition at line 87 of file RegAllocBasic.cpp.
References F, ID, llvm::MachineFunctionPass::MachineFunctionPass(), and llvm::RegAllocBase::RegAllocBase().
Member Function Documentation
dequeue()
const LiveInterval * llvm::RABasic::dequeue () inline override virtual
dequeue - Return the next unassigned register, or NULL.
Implements llvm::RegAllocBase.
Definition at line 71 of file RegAllocBasic.h.
enqueueImpl()
void llvm::RABasic::enqueueImpl (const LiveInterval * LI) inline override virtual
enqueue - Add VirtReg to the priority queue of unassigned registers.
Implements llvm::RegAllocBase.
Definition at line 69 of file RegAllocBasic.h.
getAnalysisUsage()
void RABasic::getAnalysisUsage (AnalysisUsage & AU) const override virtual
RABasic analysis usage.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 90 of file RegAllocBasic.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addPreservedID(), llvm::AnalysisUsage::addRequired(), llvm::AnalysisUsage::addRequiredID(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineDominatorsID, and llvm::AnalysisUsage::setPreservesCFG().
getClearedProperties()
MachineFunctionProperties llvm::RABasic::getClearedProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 90 of file RegAllocBasic.h.
References llvm::MachineFunctionProperties::IsSSA, and llvm::MachineFunctionProperties::set().
getPassName()
StringRef llvm::RABasic::getPassName () const inline override virtual
Return the pass name.
Reimplemented from llvm::Pass.
Definition at line 60 of file RegAllocBasic.h.
getRequiredProperties()
MachineFunctionProperties llvm::RABasic::getRequiredProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 85 of file RegAllocBasic.h.
References llvm::MachineFunctionProperties::NoPHIs, and llvm::MachineFunctionProperties::set().
releaseMemory()
void RABasic::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 116 of file RegAllocBasic.cpp.
Referenced by runOnMachineFunction().
runOnMachineFunction()
bool RABasic::runOnMachineFunction (MachineFunction & mf) override virtual
Perform register allocation.
Implements llvm::MachineFunctionPass.
Definition at line 223 of file RegAllocBasic.cpp.
References llvm::RegAllocBase::allocatePhysRegs(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), llvm::createInlineSpiller(), llvm::dbgs(), llvm::Pass::getAnalysis(), llvm::MachineFunction::getName(), llvm::RegAllocBase::init(), llvm::RegAllocBase::LIS, LLVM_DEBUG, llvm::RegAllocBase::postOptimization(), releaseMemory(), and llvm::RegAllocBase::VRM.
selectOrSplit()
MCRegister RABasic::selectOrSplit (const LiveInterval & VirtReg, SmallVectorImpl< Register > & SplitVRegs) override virtual
Implements llvm::RegAllocBase.
Definition at line 173 of file RegAllocBasic.cpp.
References assert(), llvm::AllocationOrder::create(), llvm::dbgs(), llvm::RegAllocBase::DeadRemats, llvm::LiveRegMatrix::IK_Free, llvm::LiveRegMatrix::IK_VirtReg, llvm::LiveInterval::isSpillable(), llvm::RegAllocBase::LIS, LLVM_DEBUG, llvm::RegAllocBase::Matrix, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveInterval::reg(), llvm::RegAllocBase::RegClassInfo, llvm::Spiller::spill(), spiller(), spillInterferences(), and llvm::RegAllocBase::VRM.
spiller()
Spiller & llvm::RABasic::spiller () inline override virtual
Implements llvm::RegAllocBase.
Definition at line 67 of file RegAllocBasic.h.
Referenced by selectOrSplit(), and spillInterferences().
spillInterferences()
bool RABasic::spillInterferences (const LiveInterval & VirtReg, MCRegister PhysReg, SmallVectorImpl< Register > & SplitVRegs)
Definition at line 124 of file RegAllocBasic.cpp.
References assert(), llvm::dbgs(), llvm::RegAllocBase::DeadRemats, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::LiveIntervalUnion::Query::interferingVRegs(), llvm::RegAllocBase::LIS, LLVM_DEBUG, llvm::RegAllocBase::Matrix, llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), llvm::Spiller::spill(), spiller(), llvm::RegAllocBase::TRI, llvm::RegAllocBase::VRM, and llvm::LiveInterval::weight().
Referenced by selectOrSplit().
Member Data Documentation
ID
char RABasic::ID = 0 static
Definition at line 101 of file RegAllocBasic.h.
Referenced by RABasic().
The documentation for this class was generated from the following files:
lib/CodeGen/RegAllocBasic.h
lib/CodeGen/RegAllocBasic.cpp