LLVM: llvm::DWARFDebugRnglist Class Reference
llvm::DWARFDebugRnglist Class Reference
A class representing a single rangelist.
#include "llvm/DebugInfo/DWARF/DWARFDebugRnglists.h"
Public Member Functions
LLVM_ABI DWARFAddressRangesVector getAbsoluteRanges (std::optional< object::SectionedAddress > BaseAddr, uint8_t AddressByteSize, function_ref< std::optional< object::SectionedAddress >(uint32_t)> LookupPooledAddress) const
Build a DWARFAddressRangesVector from a rangelist.
LLVM_ABI DWARFAddressRangesVector getAbsoluteRanges (std::optional< object::SectionedAddress > BaseAddr, DWARFUnit &U) const
Build a DWARFAddressRangesVector from a rangelist.
Public Member Functions inherited from llvm::DWARFListType< RangeListEntry >
const ListEntries & getEntries () const
bool empty () const
void clear ()
Error extract (DWARFDataExtractor Data, uint64_t HeaderOffset, uint64_t *OffsetPtr, StringRef SectionName, StringRef ListStringName)
Additional Inherited Members
Protected Attributes inherited from llvm::DWARFListType< RangeListEntry >
ListEntries Entries
Detailed Description
A class representing a single rangelist.
Definition at line 49 of file DWARFDebugRnglists.h.
Member Function Documentation
getAbsoluteRanges() [1/2]
DWARFAddressRangesVector DWARFDebugRnglist::getAbsoluteRanges (std::optional< object::SectionedAddress > BaseAddr, DWARFUnit & U) const
Build a DWARFAddressRangesVector from a rangelist.
Definition at line 88 of file DWARFDebugRnglists.cpp.
References getAbsoluteRanges().
getAbsoluteRanges() [2/2]
DWARFAddressRangesVector DWARFDebugRnglist::getAbsoluteRanges (std::optional< object::SectionedAddress > BaseAddr, uint8_t AddressByteSize, function_ref< std::optional< object::SectionedAddress >(uint32_t)> LookupPooledAddress) const
Build a DWARFAddressRangesVector from a rangelist.
Definition at line 95 of file DWARFDebugRnglists.cpp.
References llvm::dwarf::computeTombstoneAddress(), DenseMapInfo< LocallyHashedType >::Tombstone, llvm::DWARFListType< RangeListEntry >::Entries, llvm_unreachable, and llvm::DWARFAddressRange::SectionIndex.
Referenced by getAbsoluteRanges().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugRnglists.h
lib/DebugInfo/DWARF/DWARFDebugRnglists.cpp