LLVM: llvm::DWARFDebugNames::NameIterator Class Reference
llvm::DWARFDebugNames::NameIterator Class Reference
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Types
using size_type = size_t
using iterator_category = std::input_iterator_tag
using value_type = NameTableEntry
using difference_type = uint32_t
using pointer = NameTableEntry *
using reference = NameTableEntry
Public Member Functions
NameIterator (const NameIndex *CurrentIndex, uint32_t CurrentName)
Creates an iterator whose initial position is name CurrentName in CurrentIndex.
NameTableEntry operator* () const
NameIterator & operator++ ()
NameIterator operator++ (int)
reference operator[] (size_type idx)
Accesses entry at specific index (1-based internally, 0-based externally).
difference_type operator- (const NameIterator &other) const
Computes difference between iterators (used in parallelForEach).
Friends
bool operator== (const NameIterator &A, const NameIterator &B)
bool operator!= (const NameIterator &A, const NameIterator &B)
Detailed Description
Definition at line 773 of file DWARFAcceleratorTable.h.
Member Typedef Documentation
difference_type
using llvm::DWARFDebugNames::NameIterator::difference_type = uint32_t
Definition at line 790 of file DWARFAcceleratorTable.h.
iterator_category
using llvm::DWARFDebugNames::NameIterator::iterator_category = std::input_iterator_tag
Definition at line 788 of file DWARFAcceleratorTable.h.
pointer
using llvm::DWARFDebugNames::NameIterator::pointer = NameTableEntry *
Definition at line 791 of file DWARFAcceleratorTable.h.
reference
using llvm::DWARFDebugNames::NameIterator::reference = NameTableEntry
Definition at line 792 of file DWARFAcceleratorTable.h.
size_type
using llvm::DWARFDebugNames::NameIterator::size_type = size_t
Definition at line 787 of file DWARFAcceleratorTable.h.
value_type
using llvm::DWARFDebugNames::NameIterator::value_type = NameTableEntry
Definition at line 789 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
NameIterator()
llvm::DWARFDebugNames::NameIterator::NameIterator (const NameIndex * CurrentIndex, uint32_t CurrentName) inline
Creates an iterator whose initial position is name CurrentName in CurrentIndex.
Definition at line 796 of file DWARFAcceleratorTable.h.
Referenced by operator!=, operator++(), operator++(), operator-(), and operator==.
Member Function Documentation
operator*()
NameTableEntry llvm::DWARFDebugNames::NameIterator::operator* () const inline
Definition at line 799 of file DWARFAcceleratorTable.h.
operator++() [1/2]
NameIterator & llvm::DWARFDebugNames::NameIterator::operator++ () inline
Definition at line 802 of file DWARFAcceleratorTable.h.
References NameIterator().
operator++() [2/2]
NameIterator llvm::DWARFDebugNames::NameIterator::operator++ (int) inline
Definition at line 806 of file DWARFAcceleratorTable.h.
References I, and NameIterator().
operator-()
difference_type llvm::DWARFDebugNames::NameIterator::operator- (const NameIterator & other) const inline
Computes difference between iterators (used in parallelForEach).
Definition at line 817 of file DWARFAcceleratorTable.h.
References assert(), and NameIterator().
operator[]()
reference llvm::DWARFDebugNames::NameIterator::operator[] (size_type idx) inline
Accesses entry at specific index (1-based internally, 0-based externally).
For example how this is used in parallelForEach.
Definition at line 813 of file DWARFAcceleratorTable.h.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const NameIterator & A, const NameIterator & B) friend
Definition at line 825 of file DWARFAcceleratorTable.h.
References A(), B(), and NameIterator().
operator==
bool operator== (const NameIterator & A, const NameIterator & B) friend
Definition at line 822 of file DWARFAcceleratorTable.h.
References A(), B(), and NameIterator().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h