LLVM: llvm::orc::LibraryResolver::SymbolEnumerator Class Reference
llvm::orc::LibraryResolver::SymbolEnumerator Class Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h"
Public Types
enum class EnumerateResult { Continue , Stop , Error }
using OnEachSymbolFn = std::function<EnumerateResult(StringRef Sym)>
Static Public Member Functions
static bool enumerateSymbols (object::ObjectFile *Obj, OnEachSymbolFn OnEach, const SymbolEnumeratorOptions &Opts)
static bool enumerateSymbols (StringRef Path, OnEachSymbolFn OnEach, const SymbolEnumeratorOptions &Opts)
Detailed Description
Definition at line 383 of file LibraryResolver.h.
Member Typedef Documentation
OnEachSymbolFn
using llvm::orc::LibraryResolver::SymbolEnumerator::OnEachSymbolFn = std::function<EnumerateResult(StringRef Sym)>
Definition at line 387 of file LibraryResolver.h.
Member Enumeration Documentation
EnumerateResult
enum class llvm::orc::LibraryResolver::SymbolEnumerator::EnumerateResult strong
Enumerator
Continue
Stop
Error
Definition at line 385 of file LibraryResolver.h.
Member Function Documentation
enumerateSymbols() [1/2]
bool llvm::orc::SymbolEnumerator::enumerateSymbols (object::ObjectFile * Obj, OnEachSymbolFn OnEach, const SymbolEnumeratorOptions & Opts) static
Definition at line 106 of file LibraryResolver.cpp.
References llvm::cast(), llvm::consumeError(), E(), enumerateSymbols(), llvm::orc::SymbolEnumeratorOptions::FilterFlags, I, Range, and llvm::orc::shouldIgnoreSymbol().
Referenced by enumerateSymbols(), and enumerateSymbols().
enumerateSymbols() [2/2]
bool llvm::orc::SymbolEnumerator::enumerateSymbols (StringRef Path, OnEachSymbolFn OnEach, const SymbolEnumeratorOptions & Opts) static
Definition at line 165 of file LibraryResolver.cpp.
References llvm::dbgs(), enumerateSymbols(), llvm::orc::ObjectFileLoader::getObjectFile(), llvm::handleAllErrors(), and LLVM_DEBUG.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryResolver.cpp