LLVM: llvm::msf::MappedBlockStream Class Reference
llvm::msf::MappedBlockStream Class Reference
MappedBlockStream represents data stored in an MSF file into chunks of a particular size (called the Block Size), and whose chunks may not be necessarily contiguous.
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
Public Member Functions
llvm::endianness getEndian () const override
Error readBytes (uint64_t Offset, uint64_t Size, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Error readLongestContiguousChunk (uint64_t Offset, ArrayRef< uint8_t > &Buffer) override
Given an offset into the stream, read as much as possible without copying any data.
uint64_t getLength () override
Return the number of bytes of data in this stream.
BumpPtrAllocator & getAllocator ()
void invalidateCache ()
uint32_t getBlockSize () const
uint32_t getNumBlocks () const
uint32_t getStreamLength () const
Public Member Functions inherited from llvm::BinaryStream
virtual ~BinaryStream ()=default
virtual BinaryStreamFlags getFlags () const
Return the properties of this stream.
Static Public Member Functions
static std::unique_ptr< MappedBlockStream > createStream (uint32_t BlockSize, const MSFStreamLayout &Layout, BinaryStreamRef MsfData, BumpPtrAllocator &Allocator)
static std::unique_ptr< MappedBlockStream > createIndexedStream (const MSFLayout &Layout, BinaryStreamRef MsfData, uint32_t StreamIndex, BumpPtrAllocator &Allocator)
static std::unique_ptr< MappedBlockStream > createFpmStream (const MSFLayout &Layout, BinaryStreamRef MsfData, BumpPtrAllocator &Allocator)
static std::unique_ptr< MappedBlockStream > createDirectoryStream (const MSFLayout &Layout, BinaryStreamRef MsfData, BumpPtrAllocator &Allocator)
Protected Member Functions
MappedBlockStream (uint32_t BlockSize, const MSFStreamLayout &StreamLayout, BinaryStreamRef MsfData, BumpPtrAllocator &Allocator)
Protected Member Functions inherited from llvm::BinaryStream
Error checkOffsetForRead (uint64_t Offset, uint64_t DataSize)
Friends
class WritableMappedBlockStream
Detailed Description
MappedBlockStream represents data stored in an MSF file into chunks of a particular size (called the Block Size), and whose chunks may not be necessarily contiguous.
The arrangement of these chunks MSF the file is described by some other metadata contained within the MSF file. In the case of a standard MSF Stream, the layout of the stream's blocks is described by the MSF "directory", but in the case of the directory itself, the layout is described by an array at a fixed location within the MSF. MappedBlockStream provides methods for reading from and writing to one of these streams transparently, as if it were a contiguous sequence of bytes.
Definition at line 38 of file MappedBlockStream.h.
Constructor & Destructor Documentation
MappedBlockStream()
MappedBlockStream::MappedBlockStream (uint32_t BlockSize, const MSFStreamLayout & StreamLayout, BinaryStreamRef MsfData, BumpPtrAllocator & Allocator) protected
Definition at line 43 of file MappedBlockStream.cpp.
Member Function Documentation
createDirectoryStream()
std::unique_ptr< MappedBlockStream > MappedBlockStream::createDirectoryStream (const MSFLayout & Layout, BinaryStreamRef MsfData, BumpPtrAllocator & Allocator) static
Definition at line 69 of file MappedBlockStream.cpp.
References llvm::msf::MSFStreamLayout::Blocks, llvm::msf::SuperBlock::BlockSize, createStream(), llvm::msf::MSFLayout::DirectoryBlocks, llvm::msf::MSFStreamLayout::Length, llvm::msf::SuperBlock::NumDirectoryBytes, and llvm::msf::MSFLayout::SB.
Referenced by llvm::pdb::PDBFile::parseStreamData(), and WritableMappedBlockStream.
createFpmStream()
std::unique_ptr< MappedBlockStream > MappedBlockStream::createFpmStream (const MSFLayout & Layout, BinaryStreamRef MsfData, BumpPtrAllocator & Allocator) static
Definition at line 79 of file MappedBlockStream.cpp.
References llvm::msf::SuperBlock::BlockSize, createStream(), llvm::msf::getFpmStreamLayout(), and llvm::msf::MSFLayout::SB.
Referenced by llvm::pdb::PDBFile::parseFileHeaders(), and WritableMappedBlockStream.
createIndexedStream()
std::unique_ptr< MappedBlockStream > MappedBlockStream::createIndexedStream (const MSFLayout & Layout, BinaryStreamRef MsfData, uint32_t StreamIndex, BumpPtrAllocator & Allocator) static
Definition at line 57 of file MappedBlockStream.cpp.
References assert(), llvm::msf::MSFStreamLayout::Blocks, llvm::msf::SuperBlock::BlockSize, llvm::msf::MSFStreamLayout::Length, llvm::msf::MSFLayout::SB, llvm::msf::MSFLayout::StreamMap, and llvm::msf::MSFLayout::StreamSizes.
Referenced by llvm::pdb::PDBFile::createIndexedStream(), and WritableMappedBlockStream.
createStream()
std::unique_ptr< MappedBlockStream > MappedBlockStream::createStream (uint32_t BlockSize, const MSFStreamLayout & Layout, BinaryStreamRef MsfData, BumpPtrAllocator & Allocator) static
Definition at line 50 of file MappedBlockStream.cpp.
Referenced by createDirectoryStream(), createFpmStream(), and WritableMappedBlockStream.
getAllocator()
BumpPtrAllocator & llvm::msf::MappedBlockStream::getAllocator () inline
Definition at line 69 of file MappedBlockStream.h.
getBlockSize()
uint32_t llvm::msf::MappedBlockStream::getBlockSize () const inline
Definition at line 73 of file MappedBlockStream.h.
getEndian()
llvm::endianness llvm::msf::MappedBlockStream::getEndian () const inline override virtual
Implements llvm::BinaryStream.
Definition at line 58 of file MappedBlockStream.h.
References llvm::little.
getLength()
uint64_t MappedBlockStream::getLength () override virtual
Return the number of bytes of data in this stream.
Implements llvm::BinaryStream.
Definition at line 194 of file MappedBlockStream.cpp.
getNumBlocks()
uint32_t llvm::msf::MappedBlockStream::getNumBlocks () const inline
Definition at line 74 of file MappedBlockStream.h.
Referenced by readLongestContiguousChunk().
getStreamLength()
uint32_t llvm::msf::MappedBlockStream::getStreamLength () const inline
Definition at line 75 of file MappedBlockStream.h.
invalidateCache()
void MappedBlockStream::invalidateCache ()
Definition at line 270 of file MappedBlockStream.cpp.
readBytes()
Error MappedBlockStream::readBytes (uint64_t Offset, uint64_t Size, ArrayRef< uint8_t > & Buffer) override virtual
Given an offset into the stream and a number of bytes, attempt to read the bytes and set the output ArrayRef to point to data owned by the stream.
Implements llvm::BinaryStream.
Definition at line 86 of file MappedBlockStream.cpp.
References llvm::AbsoluteDifference(), llvm::BinaryStream::checkOffsetForRead(), intersect(), llvm::Offset, readBytes(), Size, llvm::ArrayRef< T >::slice(), and llvm::Error::success().
Referenced by readBytes().
readLongestContiguousChunk()
Error MappedBlockStream::readLongestContiguousChunk (uint64_t Offset, ArrayRef< uint8_t > & Buffer) override virtual
Given an offset into the stream, read as much as possible without copying any data.
Implements llvm::BinaryStream.
Definition at line 164 of file MappedBlockStream.cpp.
References llvm::msf::blockToOffset(), llvm::BinaryStream::checkOffsetForRead(), llvm::First, getNumBlocks(), llvm::Last, llvm::Offset, and llvm::Error::success().
Friends And Related Symbol Documentation
WritableMappedBlockStream
friend class WritableMappedBlockStream friend
Definition at line 39 of file MappedBlockStream.h.
References createDirectoryStream(), createFpmStream(), createIndexedStream(), createStream(), and WritableMappedBlockStream.
Referenced by WritableMappedBlockStream.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/MSF/MappedBlockStream.h
lib/DebugInfo/MSF/MappedBlockStream.cpp