LLVM: llvm::RISCV::RISCVVSETVLIInfoAnalysis Class Reference
llvm::RISCV::RISCVVSETVLIInfoAnalysis Class Reference
#include "Target/RISCV/RISCVVSETVLIInfoAnalysis.h"
Public Member Functions
RISCVVSETVLIInfoAnalysis ()=default
RISCVVSETVLIInfoAnalysis (const RISCVSubtarget *ST, LiveIntervals *LIS)
VSETVLIInfo getInfoForVSETVLI (const MachineInstr &MI) const
VSETVLIInfo computeInfoForInstr (const MachineInstr &MI) const
Detailed Description
Definition at line 571 of file RISCVVSETVLIInfoAnalysis.h.
Constructor & Destructor Documentation
RISCVVSETVLIInfoAnalysis() [1/2]
llvm::RISCV::RISCVVSETVLIInfoAnalysis::RISCVVSETVLIInfoAnalysis () default
RISCVVSETVLIInfoAnalysis() [2/2]
llvm::RISCV::RISCVVSETVLIInfoAnalysis::RISCVVSETVLIInfoAnalysis (const RISCVSubtarget * ST, LiveIntervals * LIS) inline
Definition at line 578 of file RISCVVSETVLIInfoAnalysis.h.
Member Function Documentation
computeInfoForInstr()
VSETVLIInfo llvm::RISCV::RISCVVSETVLIInfoAnalysis::computeInfoForInstr (const MachineInstr & MI) const
Definition at line 402 of file RISCVVSETVLIInfoAnalysis.cpp.
References llvm::RISCVII::AltFmt, assert(), llvm::RISCV::computeVLMAX(), llvm::RISCVII::getAltFmtType(), llvm::RISCV::getEEWForLoadStore(), llvm::MachineOperand::getImm(), llvm::RISCVII::getLMul(), llvm::MachineOperand::getReg(), llvm::RISCV::getSEWOpNum(), llvm::RISCVII::getTNOpNum(), llvm::RISCV::getVecPolicyOpNum(), llvm::RISCV::getVLOpNum(), llvm::RISCV::getVNInfoFromReg(), llvm::RISCVII::hasTWidenOp(), llvm::RISCV::hasUndefinedPassthru(), llvm::RISCVII::hasVecPolicyOp(), llvm::RISCVII::hasVLOp(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isUndef(), llvm::RISCVVType::isValidSEW(), llvm::Register::isVirtual(), llvm::RISCVVType::MASK_AGNOSTIC, MI, llvm::RISCVVType::TAIL_AGNOSTIC, llvm::RISCVII::usesMaskPolicy(), and llvm::RISCV::VLMaxSentinel.
getInfoForVSETVLI()
VSETVLIInfo llvm::RISCV::RISCVVSETVLIInfoAnalysis::getInfoForVSETVLI (const MachineInstr & MI) const
Definition at line 354 of file RISCVVSETVLIInfoAnalysis.cpp.
References assert(), llvm::RISCV::getVNInfoFromReg(), MI, llvm::RISCV::VSETVLIInfo::setAVLImm(), llvm::RISCV::VSETVLIInfo::setAVLRegDef(), llvm::RISCV::VSETVLIInfo::setAVLVLMAX(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
The documentation for this class was generated from the following files:
lib/Target/RISCV/RISCVVSETVLIInfoAnalysis.h
lib/Target/RISCV/RISCVVSETVLIInfoAnalysis.cpp