LLVM: llvm::dxil::ResourceInfo Class Reference
llvm::dxil::ResourceInfo Class Reference
#include "llvm/Analysis/DXILResource.h"
Classes
struct ResourceBinding
Public Member Functions
ResourceInfo (uint32_t RecordID, uint32_t Space, uint32_t LowerBound, uint32_t Size, TargetExtType *HandleTy, StringRef Name="", GlobalVariable *Symbol=nullptr)
void setBindingID (unsigned ID)
bool hasCounter () const
const ResourceBinding & getBinding () const
TargetExtType * getHandleTy () const
StringRef getName () const
bool hasSymbol () const
LLVM_ABI GlobalVariable * createSymbol (Module &M, StructType *Ty)
LLVM_ABI MDTuple * getAsMetadata (Module &M, dxil::ResourceTypeInfo &RTI) const
LLVM_ABI std::pair< uint32_t, uint32_t > getAnnotateProps (Module &M, dxil::ResourceTypeInfo &RTI) const
bool operator== (const ResourceInfo &RHS) const
bool operator!= (const ResourceInfo &RHS) const
bool operator< (const ResourceInfo &RHS) const
LLVM_ABI void print (raw_ostream &OS, dxil::ResourceTypeInfo &RTI, const DataLayout &DL) const
Public Attributes
bool GloballyCoherent = false
ResourceCounterDirection CounterDirection = ResourceCounterDirection::Unknown
Detailed Description
Definition at line 371 of file DXILResource.h.
Constructor & Destructor Documentation
ResourceInfo()
llvm::dxil::ResourceInfo::ResourceInfo (uint32_t RecordID, uint32_t Space, uint32_t LowerBound, uint32_t Size, TargetExtType * HandleTy, StringRef Name = "", GlobalVariable * Symbol = nullptr) inline
Definition at line 409 of file DXILResource.h.
Referenced by operator!=(), operator<(), and operator==().
Member Function Documentation
createSymbol()
GlobalVariable * ResourceInfo::createSymbol (Module & M, StructType * Ty)
Definition at line 658 of file DXILResource.cpp.
References assert(), llvm::GlobalValue::ExternalLinkage, llvm::ArrayType::get(), and Size.
getAnnotateProps()
std::pair< uint32_t, uint32_t > ResourceInfo::getAnnotateProps (Module & M, dxil::ResourceTypeInfo & RTI) const
Definition at line 742 of file DXILResource.cpp.
References llvm::dxil::ResourceTypeInfo::StructInfo::AlignLog2, llvm::dxil::Comparison, DL, llvm::dxil::ResourceTypeInfo::TypedInfo::ElementCount, llvm::dxil::ResourceTypeInfo::TypedInfo::ElementTy, llvm::dxil::ResourceTypeInfo::getCBufferSize(), llvm::dxil::ResourceTypeInfo::getFeedbackType(), llvm::dxil::ResourceTypeInfo::getMultiSampleCount(), llvm::dxil::ResourceTypeInfo::getResourceKind(), llvm::dxil::ResourceTypeInfo::getSamplerType(), llvm::dxil::ResourceTypeInfo::getStruct(), llvm::dxil::ResourceTypeInfo::getTyped(), llvm::dxil::ResourceTypeInfo::getUAV(), GloballyCoherent, hasCounter(), llvm::dxil::ResourceTypeInfo::isCBuffer(), llvm::dxil::ResourceTypeInfo::isFeedback(), llvm::dxil::ResourceTypeInfo::isMultiSample(), llvm::dxil::ResourceTypeInfo::UAVInfo::IsROV, llvm::dxil::ResourceTypeInfo::isSampler(), llvm::dxil::ResourceTypeInfo::isStruct(), llvm::dxil::ResourceTypeInfo::isTyped(), llvm::dxil::ResourceTypeInfo::isUAV(), llvm::dxil::ResourceTypeInfo::StructInfo::Stride, and llvm::to_underlying().
getAsMetadata()
MDTuple * ResourceInfo::getAsMetadata (Module & M, dxil::ResourceTypeInfo & RTI) const
Definition at line 671 of file DXILResource.cpp.
References assert(), DL, llvm::dxil::ResourceTypeInfo::TypedInfo::DXILStorageTy, llvm::dxil::ElementType, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::ValueAsMetadata::get(), llvm::dxil::ResourceTypeInfo::getCBufferSize(), llvm::dxil::ResourceTypeInfo::getFeedbackType(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Constant::getIntegerValue(), llvm::dxil::ResourceTypeInfo::getMultiSampleCount(), llvm::dxil::ResourceTypeInfo::getResourceKind(), llvm::dxil::ResourceTypeInfo::getSamplerType(), llvm::dxil::ResourceTypeInfo::getStruct(), llvm::dxil::ResourceTypeInfo::getTyped(), llvm::dxil::ResourceTypeInfo::getUAV(), GloballyCoherent, hasCounter(), llvm::dxil::ResourceTypeInfo::isCBuffer(), llvm::dxil::ResourceTypeInfo::isFeedback(), llvm::dxil::ResourceTypeInfo::isMultiSample(), llvm::dxil::ResourceTypeInfo::UAVInfo::IsROV, llvm::dxil::ResourceTypeInfo::isSampler(), llvm::dxil::ResourceTypeInfo::isStruct(), llvm::dxil::ResourceTypeInfo::isTyped(), llvm::dxil::ResourceTypeInfo::isUAV(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::dxil::SamplerFeedbackKind, llvm::dxil::ResourceTypeInfo::StructInfo::Stride, llvm::dxil::StructuredBufferStride, and llvm::to_underlying().
getBinding()
const ResourceBinding & llvm::dxil::ResourceInfo::getBinding () const inline
Definition at line 421 of file DXILResource.h.
Referenced by reportOverlappingBinding(), and reportOverlappingError().
getHandleTy()
TargetExtType * llvm::dxil::ResourceInfo::getHandleTy () const inline
Definition at line 422 of file DXILResource.h.
Referenced by llvm::DXILResourceMap::print().
getName()
StringRef llvm::dxil::ResourceInfo::getName () const inline
Definition at line 423 of file DXILResource.h.
Referenced by reportOverlappingError().
hasCounter()
bool llvm::dxil::ResourceInfo::hasCounter () const inline
Definition at line 417 of file DXILResource.h.
References CounterDirection, and llvm::dxil::Unknown.
Referenced by getAnnotateProps(), and getAsMetadata().
hasSymbol()
bool llvm::dxil::ResourceInfo::hasSymbol () const inline
Definition at line 425 of file DXILResource.h.
operator!=()
bool llvm::dxil::ResourceInfo::operator!= (const ResourceInfo & RHS) const inline
Definition at line 436 of file DXILResource.h.
References ResourceInfo(), and RHS.
operator<()
bool llvm::dxil::ResourceInfo::operator< (const ResourceInfo & RHS) const inline
Definition at line 437 of file DXILResource.h.
References ResourceInfo(), and RHS.
operator==()
bool llvm::dxil::ResourceInfo::operator== (const ResourceInfo & RHS) const inline
Definition at line 432 of file DXILResource.h.
References ResourceInfo(), and RHS.
print()
void ResourceInfo::print (raw_ostream & OS, dxil::ResourceTypeInfo & RTI, const DataLayout & DL) const
Definition at line 789 of file DXILResource.cpp.
References CounterDirection, llvm::dxil::Decrement, DL, GloballyCoherent, llvm::dxil::Increment, llvm::dxil::Invalid, llvm::dxil::ResourceTypeInfo::print(), and llvm::dxil::Unknown.
Referenced by llvm::DXILResourceMap::print().
setBindingID()
void llvm::dxil::ResourceInfo::setBindingID (unsigned ID) inline
Definition at line 415 of file DXILResource.h.
Member Data Documentation
CounterDirection
ResourceCounterDirection llvm::dxil::ResourceInfo::CounterDirection = ResourceCounterDirection::Unknown
Definition at line 407 of file DXILResource.h.
Referenced by hasCounter(), and print().
GloballyCoherent
bool llvm::dxil::ResourceInfo::GloballyCoherent = false
Definition at line 406 of file DXILResource.h.
Referenced by getAnnotateProps(), getAsMetadata(), and print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DXILResource.h
lib/Analysis/DXILResource.cpp