LLVM: llvm::codeview::LocalSym Class Reference
llvm::codeview::LocalSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
LocalSym (SymbolRecordKind Kind)
LocalSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
TypeIndex Type
LocalSymFlags Flags = LocalSymFlags::None
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 442 of file SymbolRecord.h.
Constructor & Destructor Documentation
LocalSym() [1/2]
llvm::codeview::LocalSym::LocalSym (SymbolRecordKind Kind) inline explicit
Definition at line 444 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by LocalSym().
LocalSym() [2/2]
llvm::codeview::LocalSym::LocalSym (uint32_t RecordOffset) inline explicit
Definition at line 445 of file SymbolRecord.h.
References LocalSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Data Documentation
Flags
LocalSymFlags llvm::codeview::LocalSym::Flags = LocalSymFlags::None
Definition at line 449 of file SymbolRecord.h.
Name
StringRef llvm::codeview::LocalSym::Name
Definition at line 450 of file SymbolRecord.h.
RecordOffset
uint32_t llvm::codeview::LocalSym::RecordOffset = 0
Definition at line 452 of file SymbolRecord.h.
Referenced by LocalSym().
Type
TypeIndex llvm::codeview::LocalSym::Type
Definition at line 448 of file SymbolRecord.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h