LLVM: llvm::MIMetadata Class Reference
llvm::MIMetadata Class Reference
Set of metadata that should be preserved when using BuildMI().
#include "llvm/CodeGen/MachineInstrBuilder.h"
Public Member Functions
MIMetadata ()=default
MIMetadata (DebugLoc DL, MDNode *PCSections=nullptr, MDNode *MMRA=nullptr, Value *DeactivationSymbol=nullptr)
MIMetadata (const DILocation *DI, MDNode *PCSections=nullptr, MDNode *MMRA=nullptr)
MIMetadata (const Instruction &From)
MIMetadata (const MachineInstr &From)
const DebugLoc & getDL () const
MDNode * getPCSections () const
MDNode * getMMRAMetadata () const
Value * getDeactivationSymbol () const
Detailed Description
Set of metadata that should be preserved when using BuildMI().
This provides a more convenient way of preserving certain data from the original instruction.
Definition at line 75 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
MIMetadata() [1/5]
llvm::MIMetadata::MIMetadata () default
MIMetadata() [2/5]
llvm::MIMetadata::MIMetadata (DebugLoc DL, MDNode * PCSections = nullptr, MDNode * MMRA = nullptr, Value * DeactivationSymbol = nullptr) inline
Definition at line 78 of file MachineInstrBuilder.h.
References llvm::move().
MIMetadata() [3/5]
llvm::MIMetadata::MIMetadata (const DILocation * DI, MDNode * PCSections = nullptr, MDNode * MMRA = nullptr) inline
Definition at line 82 of file MachineInstrBuilder.h.
MIMetadata() [4/5]
llvm::MIMetadata::MIMetadata (const Instruction & From) inline explicit
Definition at line 85 of file MachineInstrBuilder.h.
References getDeactivationSymbol(), and getDebugLoc().
MIMetadata() [5/5]
llvm::MIMetadata::MIMetadata (const MachineInstr & From) inline explicit
Definition at line 89 of file MachineInstrBuilder.h.
References getDeactivationSymbol(), getDebugLoc(), and getPCSections().
Member Function Documentation
getDeactivationSymbol()
Value * llvm::MIMetadata::getDeactivationSymbol () const inline
Definition at line 96 of file MachineInstrBuilder.h.
Referenced by llvm::MachineInstrBuilder::copyMIMetadata(), MIMetadata(), and MIMetadata().
getDL()
const DebugLoc & llvm::MIMetadata::getDL () const inline
Definition at line 93 of file MachineInstrBuilder.h.
Referenced by llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), and llvm::BuildMI().
getMMRAMetadata()
MDNode * llvm::MIMetadata::getMMRAMetadata () const inline
Definition at line 95 of file MachineInstrBuilder.h.
Referenced by llvm::MachineInstrBuilder::copyMIMetadata().
getPCSections()
MDNode * llvm::MIMetadata::getPCSections () const inline
Definition at line 94 of file MachineInstrBuilder.h.
Referenced by llvm::MachineInstrBuilder::copyMIMetadata(), and MIMetadata().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineInstrBuilder.h