LLVM: llvm::codeview::BPRelativeSym Class Reference
llvm::codeview::BPRelativeSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
BPRelativeSym (SymbolRecordKind Kind)
BPRelativeSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
int32_t Offset = 0
TypeIndex Type
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 922 of file SymbolRecord.h.
Constructor & Destructor Documentation
BPRelativeSym() [1/2]
llvm::codeview::BPRelativeSym::BPRelativeSym (SymbolRecordKind Kind) inline explicit
Definition at line 924 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by BPRelativeSym().
BPRelativeSym() [2/2]
llvm::codeview::BPRelativeSym::BPRelativeSym (uint32_t RecordOffset) inline explicit
Definition at line 925 of file SymbolRecord.h.
References BPRelativeSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Data Documentation
Name
StringRef llvm::codeview::BPRelativeSym::Name
Definition at line 931 of file SymbolRecord.h.
Offset
int32_t llvm::codeview::BPRelativeSym::Offset = 0
Definition at line 929 of file SymbolRecord.h.
RecordOffset
uint32_t llvm::codeview::BPRelativeSym::RecordOffset = 0
Definition at line 933 of file SymbolRecord.h.
Referenced by BPRelativeSym().
Type
TypeIndex llvm::codeview::BPRelativeSym::Type
Definition at line 930 of file SymbolRecord.h.
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h