LLVM: llvm::AMDGPUMachineFunction Class Reference
llvm::AMDGPUMachineFunction Class Reference
#include "Target/AMDGPU/AMDGPUMachineFunction.h"
Public Member Functions
AMDGPUMachineFunction (const Function &F, const AMDGPUSubtarget &ST)
uint64_t getExplicitKernArgSize () const
Align getMaxKernArgAlign () const
uint32_t getLDSSize () const
uint32_t getGDSSize () const
void recordNumNamedBarriers (uint32_t GVAddr, unsigned BarCnt)
uint32_t getNumNamedBarriers () const
bool isEntryFunction () const
bool isModuleEntryFunction () const
bool isChainFunction () const
bool isBottomOfStack () const
bool hasNoSignedZerosFPMath () const
bool isMemoryBound () const
bool needsWaveLimiter () const
bool hasInitWholeWave () const
void setInitWholeWave ()
unsigned allocateLDSGlobal (const DataLayout &DL, const GlobalVariable &GV)
unsigned allocateLDSGlobal (const DataLayout &DL, const GlobalVariable &GV, Align Trailing)
Align getDynLDSAlign () const
void setDynLDSAlign (const Function &F, const GlobalVariable &GV)
void setUsesDynamicLDS (bool DynLDS)
bool isDynamicLDSUsed () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Static Public Member Functions
static std::optional< uint32_t > getLDSKernelIdMetadata (const Function &F)
static std::optional< uint32_t > getLDSAbsoluteAddress (const GlobalValue &GV)
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy, typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Protected Attributes
uint64_t ExplicitKernArgSize = 0
Align MaxKernArgAlign
uint32_t LDSSize = 0
Number of bytes in the LDS that are being used.
uint32_t GDSSize = 0
uint32_t StaticLDSSize = 0
Number of bytes in the LDS allocated statically.
uint32_t StaticGDSSize = 0
Align DynLDSAlign
Align for dynamic shared memory if any.
bool UsesDynamicLDS = false
uint32_t NumNamedBarriers = 0
bool IsEntryFunction = false
bool IsModuleEntryFunction = false
bool IsChainFunction = false
bool NoSignedZerosFPMath = false
bool MemoryBound = false
bool WaveLimiter = false
bool HasInitWholeWave = false
Detailed Description
Definition at line 24 of file AMDGPUMachineFunction.h.
Constructor & Destructor Documentation
AMDGPUMachineFunction()
AMDGPUMachineFunction::AMDGPUMachineFunction (const Function & F, const AMDGPUSubtarget & ST)
Definition at line 42 of file AMDGPUMachineFunction.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, llvm::StringRef::consumeInteger(), llvm::StringRef::empty(), ExplicitKernArgSize, F, GDSSize, llvm::AMDGPU::getIntegerPairAttribute(), getKernelDynLDSGlobalFromFunction(), llvm::Attribute::getValueAsBool(), hasLDSKernelArgument(), if(), IsChainFunction, IsEntryFunction, IsModuleEntryFunction, LDSSize, MaxKernArgAlign, MemoryBound, NoSignedZerosFPMath, llvm::CallingConv::SPIR_KERNEL, StaticGDSSize, StaticLDSSize, UsesDynamicLDS, and WaveLimiter.
Referenced by llvm::R600MachineFunctionInfo::R600MachineFunctionInfo(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
Member Function Documentation
allocateLDSGlobal() [1/2]
unsigned llvm::AMDGPUMachineFunction::allocateLDSGlobal (const DataLayout & DL, const GlobalVariable & GV) inline
Definition at line 125 of file AMDGPUMachineFunction.h.
References allocateLDSGlobal(), DL, and DynLDSAlign.
Referenced by allocateLDSGlobal(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), and llvm::AMDGPUTargetLowering::LowerGlobalAddress().
allocateLDSGlobal() [2/2]
unsigned AMDGPUMachineFunction::allocateLDSGlobal (const DataLayout & DL, const GlobalVariable & GV, Align Trailing)
TODO: We should sort these to minimize wasted space due to alignment padding. Currently the padding is decided by the first encountered use during lowering.
Definition at line 93 of file AMDGPUMachineFunction.cpp.
References llvm::alignTo(), assert(), DL, GDSSize, llvm::GlobalValue::getAddressSpace(), llvm::GlobalVariable::getAlign(), getLDSAbsoluteAddress(), llvm::GlobalValue::getValueType(), isModuleEntryFunction(), llvm::AMDGPU::isNamedBarrier(), LDSSize, llvm_unreachable, llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::Offset, recordNumNamedBarriers(), llvm::AMDGPUAS::REGION_ADDRESS, llvm::report_fatal_error(), StaticGDSSize, and StaticLDSSize.
getDynLDSAlign()
Align llvm::AMDGPUMachineFunction::getDynLDSAlign () const inline
Definition at line 135 of file AMDGPUMachineFunction.h.
References DynLDSAlign.
getExplicitKernArgSize()
uint64_t llvm::AMDGPUMachineFunction::getExplicitKernArgSize () const inline
Definition at line 77 of file AMDGPUMachineFunction.h.
References ExplicitKernArgSize.
Referenced by llvm::AMDGPUTargetLowering::getImplicitParameterOffset().
getGDSSize()
uint32_t llvm::AMDGPUMachineFunction::getGDSSize () const inline
Definition at line 87 of file AMDGPUMachineFunction.h.
References GDSSize.
getLDSAbsoluteAddress()
std::optional< uint32_t > AMDGPUMachineFunction::getLDSAbsoluteAddress (const GlobalValue & GV) static
Definition at line 191 of file AMDGPUMachineFunction.cpp.
References llvm::GlobalValue::getAbsoluteSymbolRange(), llvm::GlobalValue::getAddressSpace(), and llvm::AMDGPUAS::LOCAL_ADDRESS.
Referenced by allocateLDSGlobal(), llvm::AMDGPUAsmPrinter::lowerConstant(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), and setDynLDSAlign().
getLDSKernelIdMetadata()
std::optional< uint32_t > AMDGPUMachineFunction::getLDSKernelIdMetadata (const Function & F) static
Definition at line 175 of file AMDGPUMachineFunction.cpp.
References llvm::mdconst::extract(), F, llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Referenced by llvm::AMDGPULegalizerInfo::getLDSKernelId(), llvm::AMDGPUCallLowering::passSpecialInputs(), and llvm::SITargetLowering::passSpecialInputs().
getLDSSize()
uint32_t llvm::AMDGPUMachineFunction::getLDSSize () const inline
Definition at line 83 of file AMDGPUMachineFunction.h.
References LDSSize.
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
getMaxKernArgAlign()
Align llvm::AMDGPUMachineFunction::getMaxKernArgAlign () const inline
Definition at line 81 of file AMDGPUMachineFunction.h.
References MaxKernArgAlign.
getNumNamedBarriers()
uint32_t llvm::AMDGPUMachineFunction::getNumNamedBarriers () const inline
Definition at line 95 of file AMDGPUMachineFunction.h.
References NumNamedBarriers.
Referenced by llvm::AMDGPUResourceUsageAnalysisImpl::analyzeResourceUsage().
hasInitWholeWave()
bool llvm::AMDGPUMachineFunction::hasInitWholeWave () const inline
Definition at line 122 of file AMDGPUMachineFunction.h.
References HasInitWholeWave.
Referenced by llvm::SIMachineFunctionInfo::allocateWWMSpill().
hasNoSignedZerosFPMath()
bool llvm::AMDGPUMachineFunction::hasNoSignedZerosFPMath () const inline
Definition at line 110 of file AMDGPUMachineFunction.h.
References NoSignedZerosFPMath.
isBottomOfStack()
bool llvm::AMDGPUMachineFunction::isBottomOfStack () const inline
Definition at line 106 of file AMDGPUMachineFunction.h.
References isChainFunction(), and isEntryFunction().
Referenced by llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIRegisterInfo::eliminateFrameIndex(), and llvm::SIRegisterInfo::getFrameRegister().
isChainFunction()
bool llvm::AMDGPUMachineFunction::isChainFunction () const inline
Definition at line 103 of file AMDGPUMachineFunction.h.
References IsChainFunction.
Referenced by llvm::SIMachineFunctionInfo::allocateWWMSpill(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), llvm::SIFrameLowering::hasFPImpl(), isBottomOfStack(), and llvm::SIFrameLowering::requiresStackPointerReference().
isDynamicLDSUsed()
bool AMDGPUMachineFunction::isDynamicLDSUsed () const
Definition at line 241 of file AMDGPUMachineFunction.cpp.
References UsesDynamicLDS.
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs().
isEntryFunction()
bool llvm::AMDGPUMachineFunction::isEntryFunction () const inline
Definition at line 97 of file AMDGPUMachineFunction.h.
References IsEntryFunction.
Referenced by llvm::SIMachineFunctionInfo::allocateWWMSpill(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIFrameLowering::emitEpilogue(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::SIFrameLowering::emitPrologue(), llvm::SIFrameLowering::hasFPImpl(), isBottomOfStack(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeLDSKernelId(), llvm::SIFrameLowering::requiresStackPointerReference(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), and llvm::SITargetLowering::supportSplitCSR().
isMemoryBound()
bool llvm::AMDGPUMachineFunction::isMemoryBound () const inline
Definition at line 114 of file AMDGPUMachineFunction.h.
References MemoryBound.
Referenced by llvm::SIMachineFunctionInfo::getMinAllowedOccupancy().
isModuleEntryFunction()
bool llvm::AMDGPUMachineFunction::isModuleEntryFunction () const inline
Definition at line 101 of file AMDGPUMachineFunction.h.
References IsModuleEntryFunction.
Referenced by allocateLDSGlobal(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
needsWaveLimiter()
bool llvm::AMDGPUMachineFunction::needsWaveLimiter () const inline
Definition at line 118 of file AMDGPUMachineFunction.h.
References WaveLimiter.
Referenced by llvm::SIMachineFunctionInfo::getMinAllowedOccupancy(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
recordNumNamedBarriers()
void llvm::AMDGPUMachineFunction::recordNumNamedBarriers (uint32_t GVAddr, unsigned BarCnt) inline
Definition at line 91 of file AMDGPUMachineFunction.h.
References NumNamedBarriers.
Referenced by allocateLDSGlobal(), and llvm::AMDGPUTargetLowering::LowerGlobalAddress().
setDynLDSAlign()
void AMDGPUMachineFunction::setDynLDSAlign (const Function & F, const GlobalVariable & GV)
Definition at line 209 of file AMDGPUMachineFunction.cpp.
References llvm::alignTo(), assert(), DL, DynLDSAlign, F, llvm::GlobalVariable::getAlign(), getKernelDynLDSGlobalFromFunction(), getLDSAbsoluteAddress(), llvm::GlobalValue::getValueType(), LDSSize, llvm::Offset, llvm::report_fatal_error(), and StaticLDSSize.
Referenced by llvm::AMDGPULegalizerInfo::legalizeGlobalValue().
setInitWholeWave()
void llvm::AMDGPUMachineFunction::setInitWholeWave () inline
Definition at line 123 of file AMDGPUMachineFunction.h.
References HasInitWholeWave.
Referenced by llvm::GCNTargetMachine::parseMachineFunctionInfo().
setUsesDynamicLDS()
void AMDGPUMachineFunction::setUsesDynamicLDS (bool DynLDS)
Definition at line 237 of file AMDGPUMachineFunction.cpp.
References UsesDynamicLDS.
Member Data Documentation
DynLDSAlign
Align llvm::AMDGPUMachineFunction::DynLDSAlign protected
Align for dynamic shared memory if any.
Dynamic shared memory is allocated directly after the static one, i.e., LDSSize. Need to pad LDSSize to ensure that dynamic one is aligned accordingly. The maximal alignment is updated during IR translation or lowering stages.
Definition at line 47 of file AMDGPUMachineFunction.h.
Referenced by allocateLDSGlobal(), getDynLDSAlign(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and setDynLDSAlign().
ExplicitKernArgSize
uint64_t llvm::AMDGPUMachineFunction::ExplicitKernArgSize = 0 protected
Definition at line 30 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), getExplicitKernArgSize(), and llvm::SIMachineFunctionInfo::initializeBaseYamlFields().
GDSSize
uint32_t llvm::AMDGPUMachineFunction::GDSSize = 0 protected
Definition at line 35 of file AMDGPUMachineFunction.h.
Referenced by allocateLDSGlobal(), AMDGPUMachineFunction(), getGDSSize(), and llvm::SIMachineFunctionInfo::initializeBaseYamlFields().
HasInitWholeWave
bool llvm::AMDGPUMachineFunction::HasInitWholeWave = false protected
Definition at line 72 of file AMDGPUMachineFunction.h.
Referenced by hasInitWholeWave(), and setInitWholeWave().
IsChainFunction
bool llvm::AMDGPUMachineFunction::IsChainFunction = false protected
Definition at line 62 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and isChainFunction().
IsEntryFunction
bool llvm::AMDGPUMachineFunction::IsEntryFunction = false protected
Definition at line 56 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and isEntryFunction().
IsModuleEntryFunction
bool llvm::AMDGPUMachineFunction::IsModuleEntryFunction = false protected
Definition at line 59 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), and isModuleEntryFunction().
LDSSize
uint32_t llvm::AMDGPUMachineFunction::LDSSize = 0 protected
Number of bytes in the LDS that are being used.
Definition at line 34 of file AMDGPUMachineFunction.h.
Referenced by allocateLDSGlobal(), AMDGPUMachineFunction(), getLDSSize(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and setDynLDSAlign().
MaxKernArgAlign
Align llvm::AMDGPUMachineFunction::MaxKernArgAlign protected
Definition at line 31 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), getMaxKernArgAlign(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
MemoryBound
bool llvm::AMDGPUMachineFunction::MemoryBound = false protected
Definition at line 67 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and isMemoryBound().
NoSignedZerosFPMath
bool llvm::AMDGPUMachineFunction::NoSignedZerosFPMath = false protected
Definition at line 64 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), hasNoSignedZerosFPMath(), and llvm::SIMachineFunctionInfo::initializeBaseYamlFields().
NumNamedBarriers
uint32_t llvm::AMDGPUMachineFunction::NumNamedBarriers = 0 protected
Definition at line 52 of file AMDGPUMachineFunction.h.
Referenced by getNumNamedBarriers(), and recordNumNamedBarriers().
StaticGDSSize
uint32_t llvm::AMDGPUMachineFunction::StaticGDSSize = 0 protected
Definition at line 40 of file AMDGPUMachineFunction.h.
Referenced by allocateLDSGlobal(), and AMDGPUMachineFunction().
StaticLDSSize
uint32_t llvm::AMDGPUMachineFunction::StaticLDSSize = 0 protected
Number of bytes in the LDS allocated statically.
This field is only used in the instruction selector and not part of the machine function info.
Definition at line 39 of file AMDGPUMachineFunction.h.
Referenced by allocateLDSGlobal(), AMDGPUMachineFunction(), and setDynLDSAlign().
UsesDynamicLDS
bool llvm::AMDGPUMachineFunction::UsesDynamicLDS = false protected
Definition at line 50 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), isDynamicLDSUsed(), and setUsesDynamicLDS().
WaveLimiter
bool llvm::AMDGPUMachineFunction::WaveLimiter = false protected
Definition at line 70 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and needsWaveLimiter().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUMachineFunction.h
lib/Target/AMDGPU/AMDGPUMachineFunction.cpp