LLVM: llvm::MCPseudoProbe Class Reference
llvm::MCPseudoProbe Class Reference
Instances of this class represent a pseudo probe instance for a pseudo probe table entry, which is created during a machine instruction is assembled and uses an address from a temporary label created at the current address in the current section.
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCPseudoProbe (MCSymbol *Label, uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attributes, uint32_t Discriminator)
uint64_t getGuid () const
MCSymbol * getLabel () const
LLVM_ABI void emit (MCObjectStreamer *MCOS, const MCPseudoProbe *LastProbe) const
Public Member Functions inherited from llvm::MCPseudoProbeBase
MCPseudoProbeBase (uint64_t I, uint64_t At, uint8_t T, uint32_t D)
bool isEntry () const
uint32_t getIndex () const
uint32_t getDiscriminator () const
uint8_t getAttributes () const
uint8_t getType () const
bool isBlock () const
bool isIndirectCall () const
bool isDirectCall () const
bool isCall () const
void setAttributes (uint8_t Attr)
Additional Inherited Members
Protected Attributes inherited from llvm::MCPseudoProbeBase
uint32_t Index
uint32_t Discriminator
uint8_t Attributes
uint8_t Type
Static Protected Attributes inherited from llvm::MCPseudoProbeBase
static const uint32_t PseudoProbeFirstId = 1
Detailed Description
Instances of this class represent a pseudo probe instance for a pseudo probe table entry, which is created during a machine instruction is assembled and uses an address from a temporary label created at the current address in the current section.
Definition at line 166 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCPseudoProbe()
llvm::MCPseudoProbe::MCPseudoProbe (MCSymbol * Label, uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attributes, uint32_t Discriminator) inline
Definition at line 171 of file MCPseudoProbe.h.
References assert(), llvm::MCPseudoProbeBase::Attributes, llvm::MCPseudoProbeBase::Discriminator, llvm::MCPseudoProbeBase::Index, llvm::MCPseudoProbeBase::MCPseudoProbeBase(), and llvm::MCPseudoProbeBase::Type.
Referenced by emit().
Member Function Documentation
emit()
void MCPseudoProbe::emit (MCObjectStreamer * MCOS, const MCPseudoProbe * LastProbe) const
Definition at line 51 of file MCPseudoProbe.cpp.
References llvm::AddressDelta, assert(), llvm::MCPseudoProbeBase::Attributes, buildSymbolDiff(), llvm::dbgs(), llvm::MCPseudoProbeTable::DdgPrintIndent, llvm::MCPseudoProbeBase::Discriminator, llvm::MCStreamer::emitInt64(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitSLEB128IntValue(), llvm::MCStreamer::emitULEB128IntValue(), F, llvm::MCObjectStreamer::getAssemblerPtr(), llvm::MCPseudoProbeBase::getAttributes(), llvm::MCStreamer::getCurrentFragment(), getLabel(), llvm::HasDiscriminator, llvm::raw_ostream::indent(), llvm::MCPseudoProbeBase::Index, llvm::isSentinelProbe(), LLVM_DEBUG, MCPseudoProbe(), llvm::MCObjectStreamer::newFragment(), and llvm::MCPseudoProbeBase::Type.
Referenced by llvm::MCPseudoProbeInlineTree::emit().
getGuid()
uint64_t llvm::MCPseudoProbe::getGuid () const inline
Definition at line 180 of file MCPseudoProbe.h.
Referenced by llvm::MCPseudoProbeInlineTree::addPseudoProbe(), and llvm::MCPseudoProbeInlineTree::emit().
getLabel()
MCSymbol * llvm::MCPseudoProbe::getLabel () const inline
Definition at line 181 of file MCPseudoProbe.h.
Referenced by emit().
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp