LLVM: ObjCARCContractLegacyPass Class Reference
ObjCARCContractLegacyPass Class Reference
Public Member Functions
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnFunction (Function &F) override
ObjCARCContractLegacyPass ()
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 116 of file ObjCARCContract.cpp.
Constructor & Destructor Documentation
ObjCARCContractLegacyPass()
ObjCARCContractLegacyPass::ObjCARCContractLegacyPass () inline
Definition at line 122 of file ObjCARCContract.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeObjCARCContractLegacyPassPass().
Referenced by getAnalysisUsage().
Member Function Documentation
getAnalysisUsage()
objc arc ObjC ARC false void ObjCARCContractLegacyPass::getAnalysisUsage (AnalysisUsage & AU) const override
Definition at line 757 of file ObjCARCContract.cpp.
References getAnalysisUsage(), and ObjCARCContractLegacyPass().
Referenced by getAnalysisUsage().
runOnFunction()
bool ObjCARCContractLegacyPass::runOnFunction (Function & F) override
Definition at line 769 of file ObjCARCContract.cpp.
References F, ObjCARCContract::init(), and ObjCARCContract::run().
Member Data Documentation
ID
char ObjCARCContractLegacyPass::ID = 0 static
Definition at line 121 of file ObjCARCContract.cpp.
Referenced by ObjCARCContractLegacyPass().
The documentation for this class was generated from the following file:
lib/Transforms/ObjCARC/ObjCARCContract.cpp