LLVM: llvm::X86TTIImpl Class Reference
llvm::X86TTIImpl Class Reference final
#include "Target/X86/X86TargetTransformInfo.h"
Public Member Functions
X86TTIImpl (const X86TargetMachine *TM, const Function &F)
Scalar TTI Implementations
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth) const override
Cache TTI Implementation
std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const override
std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const override
Public Member Functions inherited from llvm::BasicTTIImplBase< X86TTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const override
bool hasBranchDivergence (const Function *F=nullptr) const override
bool isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const override
bool addrspacesMayAlias (unsigned AS0, unsigned AS1) const override
unsigned getFlatAddressSpace () const override
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const override
bool isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const override
unsigned getAssumedAddrSpace (const Value *V) const override
bool isSingleThreaded () const override
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const override
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const override
bool isLegalAddImmediate (int64_t imm) const override
bool isLegalAddScalableImmediate (int64_t Imm) const override
bool isLegalICmpImmediate (int64_t imm) const override
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr, int64_t ScalableOffset=0) const override
int64_t getPreferredLargeGEPBaseOffset (int64_t MinOffset, int64_t MaxOffset)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty) const override
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty) const override
bool isNumRegsMajorCostOfLSR () const override
bool shouldDropLSRSolutionIfLessProfitable () const override
bool isProfitableLSRChainElement (Instruction *I) const override
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
bool isProfitableToHoist (Instruction *I) const override
bool useAA () const override
bool isTypeLegal (Type *Ty) const override
unsigned getRegUsageForType (Type *Ty) const override
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const override
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const override
bool shouldBuildLookupTables () const override
bool shouldBuildRelLookupTables () const override
bool haveFastSqrt (Type *Ty) const override
InstructionCost getFPOpCost (Type *Ty) const override
bool preferToKeepConstantsAttached (const Instruction &Inst, const Function &Fn) const override
unsigned getInliningThresholdMultiplier () const override
unsigned adjustInliningThreshold (const CallBase *CB) const override
unsigned getCallerAllocaCost (const CallBase *CB, const AllocaInst *AI) const override
int getInlinerVectorBonusPercent () const override
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP, OptimizationRemarkEmitter *ORE) const override
void getPeelingPreferences (Loop *L, ScalarEvolution &SE, TTI::PeelingPreferences &PP) const override
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const override
unsigned getEpilogueVectorizationMinVF () const override
bool preferPredicateOverEpilogue (TailFoldingInfo *TFI) const override
TailFoldingStyle getPreferredTailFoldingStyle (bool IVUpdateMayOverflow=true) const override
unsigned getCacheLineSize () const override
unsigned getPrefetchDistance () const override
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const override
unsigned getMaxPrefetchIterationsAhead () const override
bool enableWritePrefetching () const override
bool shouldPrefetchAddressSpace (unsigned AS) const override
std::optional< unsigned > getMaxVScale () const override
std::optional< unsigned > getVScaleForTuning () const override
bool isVScaleKnownToBeAPowerOfTwo () const override
bool isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const override
bool isTargetIntrinsicWithScalarOpAtArg (Intrinsic::ID ID, unsigned ScalarOpdIdx) const override
bool isTargetIntrinsicWithOverloadTypeAtArg (Intrinsic::ID ID, int OpdIdx) const override
bool isTargetIntrinsicWithStructReturnOverloadAtField (Intrinsic::ID ID, int RetIdx) const override
InstructionCost getScalarizationOverhead (VectorType *InTy, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
InstructionCost getOperandsScalarizationOverhead (ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const override
Estimate the overhead of scalarizing an instruction's operands.
InstructionCost getScalarizationOverhead (VectorType *RetTy, ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
Estimate the overhead of scalarizing the inputs and outputs of an instruction, with return type RetTy and arguments Args of type Tys.
std::pair< InstructionCost, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
TTI::ShuffleKind improveShuffleKindFromMask (TTI::ShuffleKind Kind, ArrayRef< int > Mask, VectorType *SrcTy, int &Index, VectorType *&SubTy) const
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index, TTI::TargetCostKind CostKind) const override
InstructionCost getIndexedVectorInstrCostFromEnd (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const override
InstructionCost getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
Get intrinsic cost based on argument types.
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const override
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp) const override
InstructionCost getTreeReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind) const
Try to calculate arithmetic and shuffle op costs for reduction intrinsics.
InstructionCost getOrderedReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind) const
Try to calculate the cost of performing strict (in-order) reductions, which involves doing a sequence of floating point additions in lane order, starting with an initial value.
InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override
InstructionCost getMulAccReductionCost (bool IsUnsigned, unsigned RedOpcode, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind) const override
InstructionCost getVectorSplitCost () const
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const override
InstructionCost getInstructionCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const override
bool supportsTailCallFor (const CallBase *CB) const override
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
virtual ~TargetTransformInfoImplBase ()
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)=default
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
virtual const DataLayout & getDataLayout () const
virtual unsigned getInliningCostBenefitAnalysisSavingsMultiplier () const
virtual unsigned getInliningCostBenefitAnalysisProfitableMultiplier () const
virtual int getInliningLastCallToStaticBonus () const
virtual InstructionCost getMemcpyCost (const Instruction *I) const
virtual BranchProbability getPredictableBranchThreshold () const
virtual InstructionUniformity getInstructionUniformity (const Value *V) const
virtual bool canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const
virtual bool isLoweredToCall (const Function *F) const
virtual bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
virtual TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
virtual bool isLegalStridedLoadStore (Type *DataType, Align Alignment) const
virtual bool isLegalInterleavedAccessType (VectorType *VTy, unsigned Factor, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalMaskedVectorHistogram (Type *AddrType, Type *DataType) const
virtual bool enableOrderedReductions () const
virtual bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
virtual bool LSRWithInstrQueries () const
virtual bool shouldBuildLookupTablesForConstant (Constant *C) const
virtual bool useColdCCForColdCall (Function &F) const
virtual bool supportsTailCalls () const
virtual bool enableAggressiveInterleaving (bool LoopHasReductions) const
virtual bool enableSelectOptimize () const
virtual bool shouldTreatInstructionLikeSelect (const Instruction *I) const
virtual bool enableMaskedInterleavedAccessVectorization () const
virtual bool isFPVectorizationPotentiallyUnsafe () const
virtual InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
virtual const char * getRegisterClassName (unsigned ClassID) const
virtual unsigned getMinVectorRegisterBitWidth () const
virtual bool shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const
virtual ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
virtual unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
virtual bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
virtual std::optional< unsigned > getMinPageSize () const
virtual InstructionCost getPartialReductionCost (unsigned Opcode, Type *InputTypeA, Type *InputTypeB, Type *AccumType, ElementCount VF, TTI::PartialReductionExtendKind OpAExtend, TTI::PartialReductionExtendKind OpBExtend, std::optional< unsigned > BinOp, TTI::TargetCostKind CostKind) const
virtual InstructionCost getInsertExtractValueCost (unsigned Opcode, TTI::TargetCostKind CostKind) const
virtual InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
virtual bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
virtual Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType, bool CanCreate=true) const
virtual Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicElementSize) const
virtual void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicCpySize) const
virtual unsigned getInlineCallPenalty (const Function *F, const CallBase &Call, unsigned DefaultCallPenalty) const
virtual bool isLegalToVectorizeLoad (LoadInst *LI) const
virtual bool isLegalToVectorizeStore (StoreInst *SI) const
virtual bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
virtual bool isElementTypeLegalForScalableVector (Type *Ty) const
virtual unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual bool preferFixedOverScalableIfEqualCost (bool IsEpilogue) const
virtual bool preferInLoopReduction (RecurKind Kind, Type *Ty) const
virtual bool preferPredicatedReductionSelect () const
virtual bool preferEpilogueVectorization () const
virtual bool shouldConsiderVectorizationRegPressure () const
virtual bool shouldExpandReduction (const IntrinsicInst *II) const
virtual TTI::ReductionShuffle getPreferredExpandedReductionShuffle (const IntrinsicInst *II) const
virtual unsigned getGISelRematGlobalCost () const
virtual unsigned getMinTripCountTailFoldingThreshold () const
virtual bool supportsScalableVectors () const
virtual bool enableScalableVectorization () const
virtual bool hasActiveVectorLength () const
virtual TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
virtual bool hasArmWideBranch (bool) const
virtual APInt getFeatureMask (const Function &F) const
virtual APInt getPriorityMask (const Function &F) const
virtual bool isMultiversionedFunction (const Function &F) const
virtual unsigned getMaxNumArgs () const
virtual unsigned getNumBytesToPadGlobalArray (unsigned Size, Type *ArrayType) const
virtual void collectKernelLaunchBounds (const Function &F, SmallVectorImpl< std::pair< StringRef, int64_t > > &LB) const
virtual bool allowVectorElementIndexingUsingGEP () const
Vector TTI Implementations
unsigned getNumberOfRegisters (unsigned ClassID) const override
unsigned getRegisterClassForType (bool Vector, Type *Ty) const override
bool hasConditionalLoadStoreForType (Type *Ty, bool IsStore) const override
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const override
unsigned getLoadStoreVecRegBitWidth (unsigned AS) const override
unsigned getMaxInterleaveFactor (ElementCount VF) const override
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info={TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const override
InstructionCost getAltInstrCost (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask, TTI::TargetCostKind CostKind) const override
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *DstTy, VectorType *SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const override
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr) const override
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, const Value *Op0, const Value *Op1) const override
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc=true, ArrayRef< Value * > VL={}) const override
Estimate the overhead of scalarizing an instruction.
InstructionCost getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind) const override
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr) const override
InstructionCost getMemIntrinsicInstrCost (const MemIntrinsicCostAttributes &MICA, TTI::TargetCostKind CostKind) const override
Get memory intrinsic cost based on arguments.
InstructionCost getMaskedMemoryOpCost (const MemIntrinsicCostAttributes &MICA, TTI::TargetCostKind CostKind) const
InstructionCost getGatherScatterOpCost (const MemIntrinsicCostAttributes &MICA, TTI::TargetCostKind CostKind) const
Calculate the cost of Gather / Scatter operation.
InstructionCost getPointersChainCost (ArrayRef< const Value * > Ptrs, const Value *Base, const TTI::PointersChainInfo &Info, Type *AccessTy, TTI::TargetCostKind CostKind) const override
InstructionCost getAddressComputationCost (Type *PtrTy, ScalarEvolution *SE, const SCEV *Ptr, TTI::TargetCostKind CostKind) const override
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const override
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const override
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const override
unsigned getAtomicMemIntrinsicMaxElementSize () const override
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const override
Get intrinsic cost based on arguments.
InstructionCost getArithmeticReductionCost (unsigned Opcode, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override
InstructionCost getMinMaxCost (Intrinsic::ID IID, Type *Ty, TTI::TargetCostKind CostKind, FastMathFlags FMF) const
InstructionCost getMinMaxReductionCost (Intrinsic::ID IID, VectorType *Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const override
Try to calculate op costs for min/max reduction operations.
InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false) const override
InstructionCost getInterleavedMemoryOpCostAVX512 (unsigned Opcode, FixedVectorType *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false) const
InstructionCost getIntImmCost (int64_t) const
Calculate the cost of materializing a 64-bit value.
InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const override
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const override
InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const override
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const override
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
bool isLSRCostLess (const TargetTransformInfo::LSRCost &C1, const TargetTransformInfo::LSRCost &C2) const override
bool canMacroFuseCmp () const override
bool isLegalMaskedLoad (Type *DataType, Align Alignment, unsigned AddressSpace, TTI::MaskKind MaskKind=TTI::MaskKind::VariableOrConstantMask) const override
bool isLegalMaskedStore (Type *DataType, Align Alignment, unsigned AddressSpace, TTI::MaskKind MaskKind=TTI::MaskKind::VariableOrConstantMask) const override
bool isLegalNTLoad (Type *DataType, Align Alignment) const override
bool isLegalNTStore (Type *DataType, Align Alignment) const override
bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const override
bool forceScalarizeMaskedGather (VectorType *VTy, Align Alignment) const override
bool forceScalarizeMaskedScatter (VectorType *VTy, Align Alignment) const override
bool isLegalMaskedGatherScatter (Type *DataType, Align Alignment) const
bool isLegalMaskedGather (Type *DataType, Align Alignment) const override
bool isLegalMaskedScatter (Type *DataType, Align Alignment) const override
bool isLegalMaskedExpandLoad (Type *DataType, Align Alignment) const override
bool isLegalMaskedCompressStore (Type *DataType, Align Alignment) const override
bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const override
bool hasDivRemOp (Type *DataType, bool IsSigned) const override
bool isExpensiveToSpeculativelyExecute (const Instruction *I) const override
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const override
bool areInlineCompatible (const Function *Caller, const Function *Callee) const override
bool areTypesABICompatible (const Function *Caller, const Function *Callee, ArrayRef< Type * > Type) const override
uint64_t getMaxMemIntrinsicInlineSizeThreshold () const override
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const override
bool preferAlternateOpcodeVectorization () const override
bool prefersVectorizedAddressing () const override
bool supportsEfficientVectorElementLoadStore () const override
bool enableInterleavedAccessVectorization () const override
InstructionCost getBranchMispredictPenalty () const override
bool isProfitableToSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const override
bool isVectorShiftByScalarCheap (Type *Ty) const override
unsigned getStoreMinimumVF (unsigned VF, Type *ScalarMemTy, Type *ScalarValTy) const override
bool useFastCCForInternalCall (Function &F) const override
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const override
InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const override
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< X86TTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
~BasicTTIImplBase () override=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes inherited from llvm::BasicTTIImplBase< X86TTIImpl >
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 28 of file X86TargetTransformInfo.h.
Constructor & Destructor Documentation
X86TTIImpl()
llvm::X86TTIImpl::X86TTIImpl (const X86TargetMachine * TM, const Function & F) inline explicit
Definition at line 113 of file X86TargetTransformInfo.h.
References F, and llvm::TargetTransformInfoImplBase::getDataLayout().
Member Function Documentation
areInlineCompatible()
bool X86TTIImpl::areInlineCompatible (const Function * Caller, const Function * Callee) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 6540 of file X86TargetTransformInfo.cpp.
References llvm::all_of(), areTypesABICompatible(), llvm::dyn_cast(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::TargetMachine::getSubtargetImpl(), I, instructions, llvm::Intrinsic::not_intrinsic, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
areTypesABICompatible()
bool X86TTIImpl::areTypesABICompatible (const Function * Caller, const Function * Callee, ArrayRef< Type * > Type) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6588 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::areTypesABICompatible(), llvm::TargetMachine::getSubtarget(), llvm::none_of(), T, and llvm::X86Subtarget::useAVX512Regs().
Referenced by areInlineCompatible().
canMacroFuseCmp()
bool X86TTIImpl::canMacroFuseCmp () const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6314 of file X86TargetTransformInfo.cpp.
enableInterleavedAccessVectorization()
bool X86TTIImpl::enableInterleavedAccessVectorization () const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6643 of file X86TargetTransformInfo.cpp.
enableMemCmpExpansion()
X86TTIImpl::TTI::MemCmpExpansionOptions X86TTIImpl::enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6611 of file X86TargetTransformInfo.cpp.
References Options.
forceScalarizeMaskedGather()
bool X86TTIImpl::forceScalarizeMaskedGather (VectorType * VTy, Align Alignment) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6449 of file X86TargetTransformInfo.cpp.
References llvm::cast().
Referenced by forceScalarizeMaskedScatter(), and getGatherScatterOpCost().
forceScalarizeMaskedScatter()
bool llvm::X86TTIImpl::forceScalarizeMaskedScatter (VectorType * VTy, Align Alignment) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 283 of file X86TargetTransformInfo.h.
References forceScalarizeMaskedGather().
Referenced by getGatherScatterOpCost().
getAddressComputationCost()
InstructionCost X86TTIImpl::getAddressComputationCost (Type * PtrTy, ScalarEvolution * SE, const SCEV * Ptr, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 5520 of file X86TargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::getAddressComputationCost(), llvm::TargetTransformInfoImplBase::getConstantStrideStep(), llvm::TargetTransformInfoImplBase::isStridedAccess(), and llvm::Type::isVectorTy().
getAltInstrCost()
InstructionCost X86TTIImpl::getAltInstrCost (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 1526 of file X86TargetTransformInfo.cpp.
References CostKind, llvm::InstructionCost::getInvalid(), isLegalAltInstr(), and llvm::TargetTransformInfo::TCC_Basic.
getArithmeticInstrCost()
InstructionCost X86TTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info = {TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info = {TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 253 of file X86TargetTransformInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::cast(), CostKind, llvm::CostTableLookup(), llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FSUB, llvm::BasicTTIImplBase< X86TTIImpl >::getArithmeticInstrCost(), getArithmeticInstrCost(), getCastInstrCost(), llvm::VectorType::getExtendedElementVectorType(), llvm::TargetTransformInfo::OperandValueInfo::getNoProps(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::MVT::getVectorVT(), llvm::isa(), llvm::TargetTransformInfo::OperandValueInfo::isConstant(), llvm::TargetTransformInfo::OperandValueInfo::isNegatedPowerOf2(), llvm::TargetTransformInfo::OperandValueInfo::isPowerOf2(), llvm::TargetTransformInfo::OperandValueInfo::isUniform(), llvm::TargetTransformInfoImplBase::minRequiredElementSize(), llvm::ISD::MUL, llvm::TargetTransformInfo::None, llvm::ISD::OR, llvm::X86ISD::PMULUDQ, llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SUB, llvm::TargetTransformInfo::TCK_CodeSize, llvm::TargetTransformInfo::TCK_RecipThroughput, llvm::ISD::UDIV, llvm::ISD::UREM, and llvm::ISD::XOR.
Referenced by getArithmeticInstrCost(), getArithmeticReductionCost(), getCmpSelInstrCost(), getInterleavedMemoryOpCostAVX512(), getIntrinsicInstrCost(), and getMinMaxReductionCost().
getArithmeticReductionCost()
InstructionCost X86TTIImpl::getArithmeticReductionCost (unsigned Opcode, VectorType * Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 5549 of file X86TargetTransformInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::cast(), CostKind, llvm::CostTableLookup(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::FADD, llvm::FixedVectorType::get(), llvm::IntegerType::get(), getArithmeticInstrCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getArithmeticReductionCost(), getArithmeticReductionCost(), getCastInstrCost(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getIntNTy(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), getShuffleCost(), llvm::EVT::getSimpleVT(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), getVectorInstrCost(), llvm::MVT::getVectorNumElements(), llvm::isPowerOf2_32(), llvm::EVT::isSimple(), llvm::MVT::isVector(), llvm::ISD::MUL, llvm::TargetTransformInfo::None, llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::TargetTransformInfo::OP_None, llvm::ISD::OR, llvm::TargetTransformInfo::requiresOrderedReduction(), Size, llvm::TargetTransformInfo::SK_ExtractSubvector, and llvm::TargetTransformInfo::SK_PermuteSingleSrc.
Referenced by getArithmeticReductionCost().
getAtomicMemIntrinsicMaxElementSize()
unsigned X86TTIImpl::getAtomicMemIntrinsicMaxElementSize () const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 3632 of file X86TargetTransformInfo.cpp.
getBranchMispredictPenalty()
InstructionCost X86TTIImpl::getBranchMispredictPenalty () const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 7162 of file X86TargetTransformInfo.cpp.
getCacheAssociativity()
std::optional< unsigned > X86TTIImpl::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 143 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
getCacheSize()
std::optional< unsigned > X86TTIImpl::getCacheSize (TargetTransformInfo::CacheLevel Level) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 113 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
getCastInstrCost()
InstructionCost X86TTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 2307 of file X86TargetTransformInfo.cpp.
References assert(), llvm::ConvertCostTableLookup(), CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::BasicTTIImplBase< X86TTIImpl >::getCastInstrCost(), getCastInstrCost(), llvm::EVT::getSimpleVT(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), I, InstructionCost, llvm::isa(), llvm::EVT::isSimple(), N, llvm::TargetTransformInfo::None, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::TargetTransformInfo::TCC_Free, llvm::TargetTransformInfo::TCK_RecipThroughput, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, and llvm::ISD::ZERO_EXTEND.
Referenced by getArithmeticInstrCost(), getArithmeticReductionCost(), getCastInstrCost(), getIntrinsicInstrCost(), and getReplicationShuffleCost().
getCFInstrCost()
InstructionCost X86TTIImpl::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 6174 of file X86TargetTransformInfo.cpp.
References CostKind, I, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by getMaskedMemoryOpCost().
getCmpSelInstrCost()
InstructionCost X86TTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info = {TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info = {TTI::OK_AnyValue, TTI::OP_None}, const Instruction * I = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 3333 of file X86TargetTransformInfo.cpp.
References assert(), llvm::CmpInst::BAD_FCMP_PREDICATE, llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::cast(), CostKind, llvm::CostTableLookup(), llvm::dyn_cast_or_null(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UNO, getArithmeticInstrCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getCmpSelInstrCost(), getCmpSelInstrCost(), llvm::MVT::getScalarSizeInBits(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), I, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::MVT::is128BitVector(), llvm::isa(), llvm::MVT::isVector(), llvm::ISD::SELECT, llvm::ISD::SETCC, and llvm::TargetTransformInfo::TCK_Latency.
Referenced by getCmpSelInstrCost(), getIntrinsicInstrCost(), and getMaskedMemoryOpCost().
getGatherScatterOpCost()
InstructionCost X86TTIImpl::getGatherScatterOpCost (const MemIntrinsicCostAttributes & MICA, TTI::TargetCostKind CostKind) const
Calculate the cost of Gather / Scatter operation.
Definition at line 6276 of file X86TargetTransformInfo.cpp.
References assert(), llvm::cast(), CostKind, llvm::dyn_cast(), forceScalarizeMaskedGather(), forceScalarizeMaskedScatter(), llvm::PointerType::getAddressSpace(), llvm::MemIntrinsicCostAttributes::getAlignment(), llvm::MemIntrinsicCostAttributes::getDataType(), llvm::MemIntrinsicCostAttributes::getID(), llvm::BasicTTIImplBase< X86TTIImpl >::getMemIntrinsicInstrCost(), llvm::MemIntrinsicCostAttributes::getPointer(), llvm::Value::getType(), isLegalMaskedGather(), isLegalMaskedScatter(), and llvm::Type::isVectorTy().
Referenced by getMemIntrinsicInstrCost().
getInterleavedMemoryOpCost()
InstructionCost X86TTIImpl::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond = false, bool UseMaskForGaps = false) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 6812 of file X86TargetTransformInfo.cpp.
References assert(), llvm::cast(), CostKind, llvm::CostTableLookup(), llvm::divideCeil(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), llvm::Type::getContext(), llvm::BasicTTIImplBase< X86TTIImpl >::getInterleavedMemoryOpCost(), getInterleavedMemoryOpCostAVX512(), llvm::Type::getIntNTy(), getMemoryOpCost(), llvm::EVT::getSimpleVT(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::Type::isBFloatTy(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::EVT::isSimple(), llvm::MVT::isVector(), and llvm::ArrayRef< T >::size().
getInterleavedMemoryOpCostAVX512()
InstructionCost X86TTIImpl::getInterleavedMemoryOpCostAVX512 (unsigned Opcode, FixedVectorType * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond = false, bool UseMaskForGaps = false) const
Definition at line 6654 of file X86TargetTransformInfo.cpp.
References assert(), CostKind, llvm::CostTableLookup(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), llvm::APInt::getAllOnes(), getArithmeticInstrCost(), llvm::Type::getContext(), llvm::VectorType::getElementType(), llvm::Type::getInt1Ty(), getMaskedMemoryOpCost(), getMemoryOpCost(), llvm::FixedVectorType::getNumElements(), getReplicationShuffleCost(), llvm::Type::getScalarType(), getShuffleCost(), llvm::MVT::getStoreSize(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::APInt::getZero(), llvm::APInt::setBit(), llvm::ArrayRef< T >::size(), llvm::TargetTransformInfo::SK_PermuteSingleSrc, and llvm::TargetTransformInfo::SK_PermuteTwoSrc.
Referenced by getInterleavedMemoryOpCost().
getIntImmCost() [1/2]
InstructionCost X86TTIImpl::getIntImmCost (const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 5990 of file X86TargetTransformInfo.cpp.
References llvm::alignTo(), llvm::APInt::ashr(), assert(), CostKind, getIntImmCost(), llvm::APInt::getSExtValue(), llvm::APInt::sextOrTrunc(), and llvm::TargetTransformInfo::TCC_Free.
getIntImmCost() [2/2]
InstructionCost X86TTIImpl::getIntImmCost (int64_t Val) const
Calculate the cost of materializing a 64-bit value.
This helper method might only calculate a fraction of a larger immediate. Therefore it is valid to return a cost of ZERO.
Definition at line 5980 of file X86TargetTransformInfo.cpp.
References llvm::isInt(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCost(), getIntImmCostInst(), and getIntImmCostIntrin().
getIntImmCostInst()
InstructionCost X86TTIImpl::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind, Instruction * Inst = nullptr) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6025 of file X86TargetTransformInfo.cpp.
References assert(), llvm::computeKnownBits(), CostKind, llvm::KnownBits::countMinTrailingZeros(), llvm::divideCeil(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::dyn_cast_or_null(), getIntImmCost(), llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
getIntImmCostIntrin()
InstructionCost X86TTIImpl::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6138 of file X86TargetTransformInfo.cpp.
References assert(), CostKind, getIntImmCost(), and llvm::TargetTransformInfo::TCC_Free.
getIntrinsicInstrCost()
InstructionCost X86TTIImpl::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) const override virtual
Get intrinsic cost based on arguments.
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 3635 of file X86TargetTransformInfo.cpp.
References llvm::ISD::ABS, llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, CostKind, llvm::CostTableLookup(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DELETED_NODE, llvm::dyn_cast(), llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FSHL, llvm::ISD::FSQRT, llvm::IntrinsicCostAttributes::getArgs(), llvm::IntrinsicCostAttributes::getArgTypes(), getArithmeticInstrCost(), getCastInstrCost(), getCmpSelInstrCost(), llvm::Type::getContainedType(), llvm::IntrinsicCostAttributes::getFlags(), llvm::IntrinsicCostAttributes::getID(), llvm::IntrinsicCostAttributes::getInst(), llvm::BasicTTIImplBase< X86TTIImpl >::getIntrinsicInstrCost(), llvm::IntrinsicCostAttributes::getReturnType(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::Type::getWithNewBitWidth(), llvm::CmpInst::ICMP_EQ, II, llvm::isa(), llvm::MVT::isScalarInteger(), llvm::IntrinsicCostAttributes::isTypeBasedOnly(), llvm::MVT::isVector(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::match(), llvm::TargetTransformInfo::None, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SADDSAT, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULO, llvm::ISD::SSUBSAT, llvm::TargetTransformInfo::TCC_Free, llvm::TargetTransformInfo::TCK_CodeSize, llvm::ISD::UADDO, llvm::ISD::UADDSAT, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULO, llvm::ISD::USUBSAT, and llvm::X86ISD::VROTLI.
Referenced by getMinMaxCost().
getLoadStoreVecRegBitWidth()
unsigned X86TTIImpl::getLoadStoreVecRegBitWidth (unsigned AS) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 230 of file X86TargetTransformInfo.cpp.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), getRegisterBitWidth(), and llvm::TargetTransformInfo::RGK_FixedWidthVector.
getMaskedMemoryOpCost()
InstructionCost X86TTIImpl::getMaskedMemoryOpCost (const MemIntrinsicCostAttributes & MICA, TTI::TargetCostKind CostKind) const
Definition at line 5428 of file X86TargetTransformInfo.cpp.
References llvm::CmpInst::BAD_ICMP_PREDICATE, CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::dyn_cast(), llvm::FixedVectorType::get(), llvm::MemIntrinsicCostAttributes::getAddressSpace(), llvm::MemIntrinsicCostAttributes::getAlignment(), llvm::APInt::getAllOnes(), getCFInstrCost(), getCmpSelInstrCost(), llvm::MemIntrinsicCostAttributes::getDataType(), llvm::MemIntrinsicCostAttributes::getID(), llvm::Type::getInt8Ty(), llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), getMemoryOpCost(), getScalarizationOverhead(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), isLegalMaskedLoad(), isLegalMaskedStore(), llvm::TargetTransformInfo::SK_InsertSubvector, and llvm::TargetTransformInfo::SK_PermuteTwoSrc.
Referenced by getInterleavedMemoryOpCostAVX512(), and getMemIntrinsicInstrCost().
getMaxInterleaveFactor()
unsigned X86TTIImpl::getMaxInterleaveFactor (ElementCount VF) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 235 of file X86TargetTransformInfo.cpp.
References llvm::ElementCount::isScalar().
getMaxMemIntrinsicInlineSizeThreshold()
uint64_t llvm::X86TTIImpl::getMaxMemIntrinsicInlineSizeThreshold () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 303 of file X86TargetTransformInfo.h.
getMemIntrinsicInstrCost()
InstructionCost X86TTIImpl::getMemIntrinsicInstrCost (const MemIntrinsicCostAttributes & MICA, TTI::TargetCostKind CostKind) const override virtual
Get memory intrinsic cost based on arguments.
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 5414 of file X86TargetTransformInfo.cpp.
References CostKind, getGatherScatterOpCost(), llvm::MemIntrinsicCostAttributes::getID(), getMaskedMemoryOpCost(), and llvm::BasicTTIImplBase< X86TTIImpl >::getMemIntrinsicInstrCost().
getMemoryOpCost()
InstructionCost X86TTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo = {TTI::OK_AnyValue, TTI::OP_None}, const Instruction * I = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 5243 of file X86TargetTransformInfo.cpp.
References llvm::all_of(), assert(), llvm::commonAlignment(), CostKind, llvm::divideCeil(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::dyn_cast(), llvm::dyn_cast_or_null(), GEP, llvm::FixedVectorType::get(), llvm::IntegerType::get(), llvm::APInt::getBitsSet(), llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), getMemoryOpCost(), getScalarizationOverhead(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), I, llvm::APInt::popcount(), llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by getInterleavedMemoryOpCost(), getInterleavedMemoryOpCostAVX512(), getMaskedMemoryOpCost(), getMemoryOpCost(), and getVectorInstrCost().
getMinMaxCost()
InstructionCost X86TTIImpl::getMinMaxCost (Intrinsic::ID IID, Type * Ty, TTI::TargetCostKind CostKind, FastMathFlags FMF) const
Definition at line 5798 of file X86TargetTransformInfo.cpp.
References CostKind, and getIntrinsicInstrCost().
Referenced by getMinMaxReductionCost().
getMinMaxReductionCost()
InstructionCost X86TTIImpl::getMinMaxReductionCost (Intrinsic::ID IID, VectorType * Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const override virtual
Try to calculate op costs for min/max reduction operations.
Parameters
CondTy Conditional type for the Select instruction.
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 5806 of file X86TargetTransformInfo.cpp.
References assert(), llvm::cast(), CostKind, llvm::CostTableLookup(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::FixedVectorType::get(), getArithmeticInstrCost(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getIntNTy(), getMinMaxCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getMinMaxReductionCost(), llvm::MVT::getScalarSizeInBits(), getShuffleCost(), llvm::EVT::getSimpleVT(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), getVectorInstrCost(), llvm::MVT::getVectorNumElements(), llvm::isPowerOf2_32(), llvm::EVT::isSimple(), llvm::MVT::isVector(), llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::TargetTransformInfo::OP_None, Size, llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_PermuteSingleSrc, llvm::ISD::SMIN, llvm::TargetTransformInfo::TCK_RecipThroughput, and llvm::ISD::UMIN.
getNumberOfRegisters()
unsigned X86TTIImpl::getNumberOfRegisters (unsigned ClassID) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 172 of file X86TargetTransformInfo.cpp.
References GPRClass, and VectorClass.
getPointersChainCost()
InstructionCost X86TTIImpl::getPointersChainCost (ArrayRef< const Value * > Ptrs, const Value * Base, const TTI::PointersChainInfo & Info, Type * AccessTy, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::TargetTransformInfoImplCRTPBase< T >.
Definition at line 5500 of file X86TargetTransformInfo.cpp.
References llvm::sampleprof::Base, CostKind, llvm::dyn_cast(), llvm::BasicTTIImplBase< X86TTIImpl >::getGEPCost(), llvm::TargetTransformInfoImplBase::getPointersChainCost(), and llvm::TargetTransformInfo::TCC_Free.
getPopcntSupport()
TargetTransformInfo::PopcntSupportKind X86TTIImpl::getPopcntSupport (unsigned TyWidth) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 105 of file X86TargetTransformInfo.cpp.
References assert(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
getRegisterBitWidth()
TypeSize X86TTIImpl::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 210 of file X86TargetTransformInfo.cpp.
References llvm::TypeSize::getFixed(), llvm::TypeSize::getScalable(), llvm_unreachable, llvm::TargetTransformInfo::RGK_FixedWidthVector, llvm::TargetTransformInfo::RGK_ScalableVector, and llvm::TargetTransformInfo::RGK_Scalar.
Referenced by getLoadStoreVecRegBitWidth().
getRegisterClassForType()
unsigned X86TTIImpl::getRegisterClassForType (bool Vector, Type * Ty) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 166 of file X86TargetTransformInfo.cpp.
References GPRClass, ScalarFPClass, llvm::Vector, and VectorClass.
getReplicationShuffleCost()
InstructionCost X86TTIImpl::getReplicationShuffleCost (Type * EltTy, int ReplicationFactor, int VF, const APInt & DemandedDstElts, TTI::TargetCostKind CostKind) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 5137 of file X86TargetTransformInfo.cpp.
References assert(), CostKind, llvm::divideCeil(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), getCastInstrCost(), llvm::Type::getContext(), llvm::Type::getIntNTy(), llvm::BasicTTIImplBase< X86TTIImpl >::getReplicationShuffleCost(), getReplicationShuffleCost(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::MVT::getVectorNumElements(), llvm::MVT::isVector(), llvm::TargetTransformInfo::None, llvm::APInt::popcount(), llvm::APIntOps::ScaleBitMask(), llvm::TargetTransformInfo::SK_PermuteSingleSrc, and llvm::APInt::zext().
Referenced by getInterleavedMemoryOpCostAVX512(), and getReplicationShuffleCost().
getScalarizationOverhead()
InstructionCost X86TTIImpl::getScalarizationOverhead (VectorType * InTy, const APInt & DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc = true, ArrayRef< Value * > VL = {}) const override virtual
Estimate the overhead of scalarizing an instruction.
Insert and Extract are set if the demanded result elements need to be inserted and/or extracted from vectors.
FIXME: a bitfield is not a reasonable abstraction for talking about which elements are needed from a scalable vector
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 4955 of file X86TargetTransformInfo.cpp.
References assert(), llvm::cast(), CostKind, llvm::ArrayRef< T >::empty(), llvm::APInt::extractBits(), llvm::FixedVectorType::get(), llvm::APInt::getBitWidth(), llvm::Constant::getNullValue(), getNumElements(), llvm::BasicTTIImplBase< X86TTIImpl >::getScalarizationOverhead(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), getVectorInstrCost(), I, llvm::APInt::isAllOnes(), llvm::MVT::isInteger(), llvm::APInt::isZero(), llvm::APInt::popcount(), llvm::PowerOf2Ceil(), llvm::APIntOps::ScaleBitMask(), llvm::seq(), llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, and llvm::APInt::zext().
Referenced by getMaskedMemoryOpCost(), and getMemoryOpCost().
getScalingFactorCost()
InstructionCost X86TTIImpl::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const override virtual
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
If the AM is supported, the return value must be >= 0. If the AM is not supported, it returns an invalid cost.
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 7127 of file X86TargetTransformInfo.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::StackOffset::getFixed(), llvm::InstructionCost::getInvalid(), llvm::StackOffset::getScalable(), llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::BasicTTIImplBase< X86TTIImpl >::isLegalAddressingMode(), llvm::TargetLoweringBase::AddrMode::ScalableOffset, and llvm::TargetLoweringBase::AddrMode::Scale.
getShuffleCost()
InstructionCost X86TTIImpl::getShuffleCost (TTI::ShuffleKind Kind, VectorType * DstTy, VectorType * SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType * SubTp, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 1534 of file X86TargetTransformInfo.cpp.
References llvm::alignDown(), llvm::all_of(), llvm::any_of(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), llvm::copy(), CostKind, llvm::CostTableLookup(), llvm::count_if(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ArrayRef< T >::empty(), llvm::enumerate(), llvm::FixedVectorType::get(), llvm::VectorType::getDoubleElementsVectorType(), llvm::VectorType::getElementCount(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarType(), llvm::BasicTTIImplBase< X86TTIImpl >::getShuffleCost(), getShuffleCost(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MVT::getStoreSize(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::InstructionCost::getValue(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), I, llvm::BasicTTIImplBase< X86TTIImpl >::improveShuffleKindFromMask(), llvm::isa(), llvm::ShuffleVectorInst::isIdentityMask(), isLegalBroadcastLoad(), llvm::Type::isScalableTy(), llvm::EVT::isSimple(), llvm::InstructionCost::isValid(), llvm::EVT::isVector(), llvm::MVT::isVector(), llvm::PatternMatch::m_Load(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, llvm::PoisonMaskElem, llvm::processShuffleMasks(), llvm::TargetTransformInfo::SK_Broadcast, llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::TargetTransformInfo::SK_PermuteSingleSrc, llvm::TargetTransformInfo::SK_PermuteTwoSrc, llvm::TargetTransformInfo::SK_Reverse, llvm::TargetTransformInfo::SK_Select, llvm::TargetTransformInfo::SK_Splice, llvm::TargetTransformInfo::SK_Transpose, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, X, and Y.
Referenced by getArithmeticReductionCost(), getInterleavedMemoryOpCostAVX512(), getMaskedMemoryOpCost(), getMemoryOpCost(), getMinMaxReductionCost(), getReplicationShuffleCost(), getScalarizationOverhead(), getShuffleCost(), and getVectorInstrCost().
getStoreMinimumVF()
unsigned X86TTIImpl::getStoreMinimumVF (unsigned VF, Type * ScalarMemTy, Type * ScalarValTy) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 7189 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::getStoreMinimumVF(), and llvm::Type::isHalfTy().
getVectorInstrCost() [1/3]
InstructionCost llvm::BasicTTIImplBase< X86TTIImpl >::getVectorInstrCost (const Instruction & I, Type * Val, TTI::TargetCostKind CostKind, unsigned Index) const inline override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 1451 of file BasicTTIImpl.h.
getVectorInstrCost() [2/3]
InstructionCost X86TTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, const Value * Op0, const Value * Op1) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 4806 of file X86TargetTransformInfo.cpp.
References assert(), llvm::cast(), CostKind, llvm::CostTableLookup(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::FixedVectorType::get(), getMemoryOpCost(), llvm::Type::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::Type::getScalarType(), getShuffleCost(), llvm::EVT::getSizeInBits(), llvm::Value::getType(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getVectorInstrCost(), llvm::isa(), llvm::isa_and_nonnull(), llvm::Type::isFloatingPointTy(), llvm::MVT::isInteger(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), Op0, llvm::TargetTransformInfo::SK_PermuteTwoSrc, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getArithmeticReductionCost(), getMinMaxReductionCost(), and getScalarizationOverhead().
getVectorInstrCost() [3/3]
InstructionCost llvm::BasicTTIImplBase< X86TTIImpl >::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, Value * Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const inline override virtual
Parameters
ScalarUserAndIdx encodes the information about extracts from a vector with 'Scalar' being the value being extracted,'User' being the user of the extract(nullptr if user is not known before vectorization) and 'Idx' being the extract lane.
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 1442 of file BasicTTIImpl.h.
hasConditionalLoadStoreForType()
bool X86TTIImpl::hasConditionalLoadStoreForType (Type * Ty, bool IsStore) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 186 of file X86TargetTransformInfo.cpp.
References llvm::cast(), llvm::dyn_cast(), and getBitWidth().
Referenced by isLegalMaskedLoad(), and isLegalMaskedStore().
hasDivRemOp()
bool X86TTIImpl::hasDivRemOp (Type * DataType, bool IsSigned) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6524 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::SDIVREM, and llvm::ISD::UDIVREM.
instCombineIntrinsic()
std::optional< Instruction * > X86TTIImpl::instCombineIntrinsic (InstCombiner & IC, IntrinsicInst & II) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 2194 of file X86InstCombineIntrinsic.cpp.
References llvm::any_of(), assert(), llvm::BitWidth, llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::cast(), llvm::SelectInst::Create(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateExtractElement(), llvm::IRBuilderBase::CreateFAdd(), llvm::IRBuilderBase::CreateFDiv(), llvm::IRBuilderBase::CreateFMul(), llvm::IRBuilderBase::CreateFSub(), llvm::IRBuilderBase::CreateICmpSGT(), llvm::IRBuilderBase::CreateInsertElement(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateSelect(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateShuffleVector(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ConstantAggregateZero::get(), llvm::FixedVectorType::get(), llvm::InstCombiner::getDataLayout(), llvm::IRBuilderBase::getInt1Ty(), llvm::APInt::getLowBitsSet(), getNegativeIsTrueBoolVec(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignMask(), llvm::APInt::getSplat(), llvm::Value::getType(), I, II, llvm::isa(), llvm::isPowerOf2_32(), llvm::APInt::isSubsetOf(), llvm::Type::isVectorTy(), llvm::Length, llvm_unreachable, llvm::APInt::lshr(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::Masked, llvm::maskTrailingOnes(), llvm::PatternMatch::match(), Op0, llvm::InstCombiner::peekThroughBitcast(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), llvm::scaleShuffleMaskElts(), llvm::InstCombiner::SimplifyDemandedBits(), llvm::InstCombiner::SimplifyDemandedVectorElts(), simplifyTernarylogic(), simplifyX86addcarry(), simplifyX86extrq(), simplifyX86FPMaxMin(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86insertq(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86movmsk(), simplifyX86pack(), simplifyX86pmadd(), simplifyX86pmulh(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86VPERMMask(), simplifyX86vpermv(), simplifyX86vpermv3(), and llvm::APInt::zextOrTrunc().
isExpensiveToSpeculativelyExecute()
bool X86TTIImpl::isExpensiveToSpeculativelyExecute (const Instruction * I) const override virtual
Reimplemented from llvm::TargetTransformInfoImplCRTPBase< T >.
Definition at line 6529 of file X86TargetTransformInfo.cpp.
References I, and llvm::TargetTransformInfoImplBase::isExpensiveToSpeculativelyExecute().
isFCmpOrdCheaperThanFCmpZero()
bool X86TTIImpl::isFCmpOrdCheaperThanFCmpZero (Type * Ty) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 6538 of file X86TargetTransformInfo.cpp.
isLegalAltInstr()
bool X86TTIImpl::isLegalAltInstr (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6484 of file X86TargetTransformInfo.cpp.
References assert(), llvm::cast(), llvm::isPowerOf2_32(), Opc, llvm::seq(), llvm::SmallBitVector::size(), and llvm::SmallBitVector::test().
Referenced by getAltInstrCost().
isLegalBroadcastLoad()
bool X86TTIImpl::isLegalBroadcastLoad (Type * ElementTy, ElementCount NumElements) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6405 of file X86TargetTransformInfo.cpp.
References llvm::Type::getContext(), llvm::Type::getDoubleTy(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
Referenced by getShuffleCost().
isLegalMaskedCompressStore()
bool X86TTIImpl::isLegalMaskedCompressStore (Type * DataType, Align Alignment) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6437 of file X86TargetTransformInfo.cpp.
References isLegalMaskedExpandLoad().
isLegalMaskedExpandLoad()
bool X86TTIImpl::isLegalMaskedExpandLoad (Type * DataType, Align Alignment) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6413 of file X86TargetTransformInfo.cpp.
References llvm::cast(), llvm::Type::getIntegerBitWidth(), getNumElements(), llvm::isa(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and llvm::Type::isIntegerTy().
Referenced by isLegalMaskedCompressStore().
isLegalMaskedGather()
bool X86TTIImpl::isLegalMaskedGather (Type * DataType, Align Alignment) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6478 of file X86TargetTransformInfo.cpp.
References isLegalMaskedGatherScatter().
Referenced by getGatherScatterOpCost().
isLegalMaskedGatherScatter()
bool X86TTIImpl::isLegalMaskedGatherScatter (Type * DataType, Align Alignment) const
Definition at line 6462 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::getScalarType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by isLegalMaskedGather(), and isLegalMaskedScatter().
isLegalMaskedLoad()
bool X86TTIImpl::isLegalMaskedLoad (Type * DataType, Align Alignment, unsigned AddressSpace, TTI::MaskKind MaskKind = TTI::MaskKind::VariableOrConstantMask) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6342 of file X86TargetTransformInfo.cpp.
References llvm::cast(), getNumElements(), llvm::Type::getScalarType(), hasConditionalLoadStoreForType(), llvm::isa(), and isLegalMaskedLoadStore().
Referenced by getMaskedMemoryOpCost().
isLegalMaskedScatter()
bool X86TTIImpl::isLegalMaskedScatter (Type * DataType, Align Alignment) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6517 of file X86TargetTransformInfo.cpp.
References isLegalMaskedGatherScatter().
Referenced by getGatherScatterOpCost().
isLegalMaskedStore()
bool X86TTIImpl::isLegalMaskedStore (Type * DataType, Align Alignment, unsigned AddressSpace, TTI::MaskKind MaskKind = TTI::MaskKind::VariableOrConstantMask) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6356 of file X86TargetTransformInfo.cpp.
References llvm::cast(), getNumElements(), llvm::Type::getScalarType(), hasConditionalLoadStoreForType(), llvm::isa(), and isLegalMaskedLoadStore().
Referenced by getMaskedMemoryOpCost().
isLegalNTLoad()
bool X86TTIImpl::isLegalNTLoad (Type * DataType, Align Alignment) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6370 of file X86TargetTransformInfo.cpp.
References llvm::DataSize, and llvm::BasicTTIImplBase< X86TTIImpl >::DL.
isLegalNTStore()
bool X86TTIImpl::isLegalNTStore (Type * DataType, Align Alignment) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6381 of file X86TargetTransformInfo.cpp.
References llvm::DataSize, llvm::BasicTTIImplBase< X86TTIImpl >::DL, and llvm::isPowerOf2_32().
isLSRCostLess()
bool X86TTIImpl::isLSRCostLess (const TargetTransformInfo::LSRCost & C1, const TargetTransformInfo::LSRCost & C2) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 6305 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::Insns, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
isProfitableToSinkOperands()
bool X86TTIImpl::isProfitableToSinkOperands (Instruction * I, SmallVectorImpl< Use * > & Ops) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 7197 of file X86TargetTransformInfo.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::any_of(), llvm::cast(), llvm::dyn_cast(), llvm::VectorType::getElementType(), llvm::getSplatIndex(), I, II, llvm::Type::isIntegerTy(), isVectorShiftByScalarCheap(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
isVectorShiftByScalarCheap()
bool X86TTIImpl::isVectorShiftByScalarCheap (Type * Ty) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 7167 of file X86TargetTransformInfo.cpp.
Referenced by isProfitableToSinkOperands().
preferAlternateOpcodeVectorization()
bool llvm::X86TTIImpl::preferAlternateOpcodeVectorization () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 309 of file X86TargetTransformInfo.h.
prefersVectorizedAddressing()
bool X86TTIImpl::prefersVectorizedAddressing () const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6635 of file X86TargetTransformInfo.cpp.
simplifyDemandedUseBitsIntrinsic()
std::optional< Value * > X86TTIImpl::simplifyDemandedUseBitsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedMask, KnownBits & Known, bool & KnownBitsComputed) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 3205 of file X86InstCombineIntrinsic.cpp.
References llvm::cast(), llvm::Constant::getNullValue(), II, llvm::APInt::isZero(), llvm::APInt::setBitsFrom(), llvm::KnownBits::Zero, and llvm::APInt::zextOrTrunc().
simplifyDemandedVectorEltsIntrinsic()
std::optional< Value * > X86TTIImpl::simplifyDemandedVectorEltsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, APInt & UndefElts, APInt & UndefElts2, APInt & UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 3245 of file X86InstCombineIntrinsic.cpp.
References llvm::InstCombiner::addToWorklist(), assert(), llvm::InstCombiner::Builder, llvm::cast(), llvm::APInt::clearBit(), llvm::IRBuilderBase::CreateBinOp(), llvm::ConstantAggregateZero::get(), llvm::APInt::getLoBits(), llvm::APInt::getSplat(), II, llvm::APInt::isSubsetOf(), llvm::APInt::lshr(), llvm::APIntOps::ScaleBitMask(), llvm::APInt::setBit(), llvm::APInt::setHighBits(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::APInt::zext().
supportsEfficientVectorElementLoadStore()
bool X86TTIImpl::supportsEfficientVectorElementLoadStore () const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 6639 of file X86TargetTransformInfo.cpp.
useFastCCForInternalCall()
bool X86TTIImpl::useFastCCForInternalCall (Function & F) const override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 7254 of file X86TargetTransformInfo.cpp.
References llvm::dyn_cast(), F, llvm::CallBase::getCalledOperand(), llvm::Instruction::getFunction(), and llvm::TargetMachine::getSubtarget().
The documentation for this class was generated from the following files:
lib/Target/X86/X86TargetTransformInfo.h
lib/Target/X86/X86InstCombineIntrinsic.cpp
lib/Target/X86/X86TargetTransformInfo.cpp