LLVM: llvm::object::BaseRelocRef Class Reference
llvm::object::BaseRelocRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
BaseRelocRef ()=default
BaseRelocRef (const coff_base_reloc_block_header *Header, const COFFObjectFile *Owner)
LLVM_ABI bool operator== (const BaseRelocRef &Other) const
LLVM_ABI void moveNext ()
LLVM_ABI Error getType (uint8_t &Type) const
LLVM_ABI Error getRVA (uint32_t &Result) const
Detailed Description
Definition at line 1339 of file COFF.h.
Constructor & Destructor Documentation
BaseRelocRef() [1/2]
llvm::object::BaseRelocRef::BaseRelocRef () default
Referenced by operator==().
BaseRelocRef() [2/2]
llvm::object::BaseRelocRef::BaseRelocRef (const coff_base_reloc_block_header * Header, const COFFObjectFile * Owner) inline
Definition at line 1342 of file COFF.h.
References Owner.
Member Function Documentation
getRVA()
Error BaseRelocRef::getRVA (uint32_t & Result) const
Definition at line 1928 of file COFFObjectFile.cpp.
References llvm::Error::success().
getType()
Error BaseRelocRef::getType (uint8_t & Type) const
Definition at line 1922 of file COFFObjectFile.cpp.
References llvm::Error::success().
moveNext()
void BaseRelocRef::moveNext ()
Definition at line 1904 of file COFFObjectFile.cpp.
References Size.
operator==()
bool BaseRelocRef::operator== (const BaseRelocRef & Other) const
Definition at line 1900 of file COFFObjectFile.cpp.
References BaseRelocRef(), and llvm::Other.
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp