LLVM: llvm::HexagonResource Class Reference
llvm::HexagonResource Class Reference
#include "Target/Hexagon/MCTargetDesc/HexagonShuffler.h"
Public Member Functions
HexagonResource (unsigned s)
void setUnits (unsigned s)
void setAllUnits ()
unsigned setWeight (unsigned s)
unsigned getUnits () const
unsigned getWeight () const
Static Public Member Functions
static bool lessUnits (const HexagonResource &A, const HexagonResource &B)
static bool lessWeight (const HexagonResource &A, const HexagonResource &B)
Detailed Description
Definition at line 37 of file HexagonShuffler.h.
Constructor & Destructor Documentation
HexagonResource()
llvm::HexagonResource::HexagonResource (unsigned s) inline
Definition at line 43 of file HexagonShuffler.h.
References setUnits().
Referenced by llvm::HexagonCVIResource::HexagonCVIResource(), lessUnits(), and lessWeight().
Member Function Documentation
getUnits()
unsigned llvm::HexagonResource::getUnits () const inline
Definition at line 55 of file HexagonShuffler.h.
Referenced by llvm::HexagonShuffler::restrictPreferSlot3(), and setWeight().
getWeight()
unsigned llvm::HexagonResource::getWeight () const inline
Definition at line 56 of file HexagonShuffler.h.
lessUnits()
bool llvm::HexagonResource::lessUnits (const HexagonResource & A, const HexagonResource & B) inline static
Definition at line 59 of file HexagonShuffler.h.
References A(), B(), HexagonResource(), and llvm::popcount().
Referenced by llvm::HexagonInstr::lessCore(), and llvm::HexagonInstr::lessCVI().
lessWeight()
bool llvm::HexagonResource::lessWeight (const HexagonResource & A, const HexagonResource & B) inline static
Definition at line 64 of file HexagonShuffler.h.
References A(), B(), and HexagonResource().
Referenced by llvm::HexagonInstr::operator<().
setAllUnits()
void llvm::HexagonResource::setAllUnits () inline
Definition at line 50 of file HexagonShuffler.h.
References HEXAGON_PACKET_SIZE, and setUnits().
setUnits()
void llvm::HexagonResource::setUnits (unsigned s) inline
Definition at line 45 of file HexagonShuffler.h.
References HEXAGON_PACKET_SIZE, and setWeight().
Referenced by llvm::HexagonCVIResource::HexagonCVIResource(), HexagonResource(), llvm::HexagonShuffler::restrictPreferSlot3(), and setAllUnits().
setWeight()
unsigned HexagonResource::setWeight (unsigned s)
Definition at line 90 of file HexagonShuffler.cpp.
References llvm::countr_zero(), getUnits(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::popcount().
Referenced by setUnits().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonShuffler.h
lib/Target/Hexagon/MCTargetDesc/HexagonShuffler.cpp