LLVM: llvm::IndexedMemProfReader Class Reference
llvm::IndexedMemProfReader Class Reference
#include "llvm/ProfileData/InstrProfReader.h"
Public Member Functions
IndexedMemProfReader ()=default
LLVM_ABI Error deserialize (const unsigned char *Start, uint64_t MemProfOffset)
LLVM_ABI Expected< memprof::MemProfRecord > getMemProfRecord (const uint64_t FuncNameHash) const
LLVM_ABI DenseMap< uint64_t, SmallVector< memprof::CallEdgeTy, 0 > > getMemProfCallerCalleePairs () const
LLVM_ABI memprof::DataAccessProfData * getDataAccessProfileData () const
LLVM_ABI memprof::AllMemProfData getAllMemProfData () const
memprof::MemProfSummary * getSummary () const
Detailed Description
Definition at line 691 of file InstrProfReader.h.
Constructor & Destructor Documentation
IndexedMemProfReader()
llvm::IndexedMemProfReader::IndexedMemProfReader () default
References LLVM_ABI.
Member Function Documentation
deserialize()
Error llvm::IndexedMemProfReader::deserialize (const unsigned char * Start, uint64_t MemProfOffset)
Definition at line 447 of file IndexedMemProfData.cpp.
References E(), llvm::formatv(), llvm::make_error(), llvm::memprof::MaximumSupportedVersion, llvm::memprof::MinimumSupportedVersion, llvm::support::endian::readNext(), llvm::Error::success(), llvm::unsupported_version, llvm::memprof::Version2, llvm::memprof::Version3, and llvm::memprof::Version4.
getAllMemProfData()
memprof::AllMemProfData IndexedMemProfReader::getAllMemProfData () const
Definition at line 1542 of file InstrProfReader.cpp.
References getMemProfRecord(), llvm::memprof::GUIDMemProfRecordPair::GUID, llvm::memprof::AllMemProfData::HeapProfileRecords, llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::memprof::YamlDataAccessProfData::KnownColdStrHashes, llvm::memprof::YamlDataAccessProfData::KnownColdSymbols, llvm::memprof::GUIDMemProfRecordPair::Record, llvm::memprof::YamlDataAccessProfData::Records, llvm::stable_sort(), and llvm::memprof::AllMemProfData::YamlifiedDataAccessProfiles.
getDataAccessProfileData()
LLVM_ABI memprof::DataAccessProfData * llvm::IndexedMemProfReader::getDataAccessProfileData () const inline
Definition at line 733 of file InstrProfReader.h.
References LLVM_ABI.
getMemProfCallerCalleePairs()
DenseMap< uint64_t, SmallVector< memprof::CallEdgeTy, 0 > > IndexedMemProfReader::getMemProfCallerCalleePairs () const
Definition at line 1504 of file InstrProfReader.cpp.
References assert(), llvm::memprof::IndexedAllocationInfo::CSId, llvm::BitVector::set(), llvm::BitVector::set_bits(), llvm::sort(), llvm::unique(), llvm::memprof::Version3, and llvm::memprof::Version4.
getMemProfRecord()
Expected< memprof::MemProfRecord > IndexedMemProfReader::getMemProfRecord (const uint64_t FuncNameHash) const
Definition at line 1461 of file InstrProfReader.cpp.
References assert(), llvm::formatv(), getMemProfRecordV2(), llvm::invalid_prof, llvm::make_error(), llvm::memprof::MaximumSupportedVersion, llvm::memprof::MinimumSupportedVersion, llvm::memprof::IndexedMemProfRecord::toMemProfRecord(), llvm::unknown_function, llvm::unsupported_version, llvm::memprof::Version2, llvm::memprof::Version3, and llvm::memprof::Version4.
Referenced by getAllMemProfData().
getSummary()
memprof::MemProfSummary * llvm::IndexedMemProfReader::getSummary () const inline
Definition at line 740 of file InstrProfReader.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/IndexedMemProfData.cpp
lib/ProfileData/InstrProfReader.cpp