LLVM: llvm::DOTFuncInfo Class Reference
llvm::DOTFuncInfo Class Reference
#include "llvm/Analysis/CFGPrinter.h"
Public Member Functions
DOTFuncInfo (const Function *F)
LLVM_ABI ~DOTFuncInfo ()
LLVM_ABI DOTFuncInfo (const Function *F, const BlockFrequencyInfo *BFI, const BranchProbabilityInfo *BPI, uint64_t MaxFreq, std::optional< NodeIdFormatterTy > NodeIdFormatter=std::nullopt)
const BlockFrequencyInfo * getBFI () const
const BranchProbabilityInfo * getBPI () const
const Function * getFunction () const
LLVM_ABI ModuleSlotTracker * getModuleSlotTracker ()
uint64_t getMaxFreq () const
uint64_t getFreq (const BasicBlock *BB) const
void setHeatColors (bool ShowHeat)
bool showHeatColors ()
void setRawEdgeWeights (bool RawWeights)
bool useRawEdgeWeights ()
void setEdgeWeights (bool EdgeWeights)
bool showEdgeWeights ()
std::optional< NodeIdFormatterTy > getNodeIdFormatter ()
Detailed Description
Definition at line 65 of file CFGPrinter.h.
Constructor & Destructor Documentation
DOTFuncInfo() [1/2]
llvm::DOTFuncInfo::DOTFuncInfo (const Function * F) inline
Definition at line 80 of file CFGPrinter.h.
References DOTFuncInfo(), and nullptr.
Referenced by DOTFuncInfo().
~DOTFuncInfo()
DOTFuncInfo::~DOTFuncInfo () default
References LLVM_ABI.
DOTFuncInfo() [2/2]
DOTFuncInfo::DOTFuncInfo (const Function * F, const BlockFrequencyInfo * BFI, const BranchProbabilityInfo * BPI, uint64_t MaxFreq, std::optional< NodeIdFormatterTy > NodeIdFormatter = std::nullopt)
Definition at line 94 of file CFGPrinter.cpp.
Member Function Documentation
getBFI()
const BlockFrequencyInfo * llvm::DOTFuncInfo::getBFI () const inline
Definition at line 88 of file CFGPrinter.h.
getBPI()
const BranchProbabilityInfo * llvm::DOTFuncInfo::getBPI () const inline
Definition at line 90 of file CFGPrinter.h.
Referenced by llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes().
getFreq()
uint64_t llvm::DOTFuncInfo::getFreq (const BasicBlock * BB) const inline
Definition at line 98 of file CFGPrinter.h.
Referenced by llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), and llvm::DOTGraphTraits< DOTFuncInfo * >::getNodeAttributes().
getFunction()
const Function * llvm::DOTFuncInfo::getFunction () const inline
Definition at line 92 of file CFGPrinter.h.
Referenced by llvm::GraphTraits< DOTFuncInfo * >::getEntryNode(), llvm::DOTGraphTraits< DOTFuncInfo * >::getGraphName(), llvm::GraphTraits< DOTFuncInfo * >::nodes_begin(), llvm::GraphTraits< DOTFuncInfo * >::nodes_end(), and llvm::GraphTraits< DOTFuncInfo * >::size().
getMaxFreq()
uint64_t llvm::DOTFuncInfo::getMaxFreq () const inline
Definition at line 96 of file CFGPrinter.h.
Referenced by llvm::DOTGraphTraits< DOTFuncInfo * >::getNodeAttributes().
getModuleSlotTracker()
ModuleSlotTracker * DOTFuncInfo::getModuleSlotTracker ()
Definition at line 106 of file CFGPrinter.cpp.
getNodeIdFormatter()
std::optional< NodeIdFormatterTy > llvm::DOTFuncInfo::getNodeIdFormatter () inline
Definition at line 114 of file CFGPrinter.h.
Referenced by llvm::DOTGraphTraits< DOTFuncInfo * >::getNodeAttributes().
setEdgeWeights()
void llvm::DOTFuncInfo::setEdgeWeights (bool EdgeWeights) inline
Definition at line 110 of file CFGPrinter.h.
Referenced by viewCFG(), and writeCFGToDotFile().
setHeatColors()
void llvm::DOTFuncInfo::setHeatColors (bool ShowHeat) inline
Definition at line 102 of file CFGPrinter.h.
Referenced by viewCFG(), and writeCFGToDotFile().
setRawEdgeWeights()
void llvm::DOTFuncInfo::setRawEdgeWeights (bool RawWeights) inline
Definition at line 106 of file CFGPrinter.h.
Referenced by viewCFG(), and writeCFGToDotFile().
showEdgeWeights()
bool llvm::DOTFuncInfo::showEdgeWeights () inline
Definition at line 112 of file CFGPrinter.h.
Referenced by llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes().
showHeatColors()
bool llvm::DOTFuncInfo::showHeatColors () inline
Definition at line 104 of file CFGPrinter.h.
Referenced by llvm::DOTGraphTraits< DOTFuncInfo * >::getNodeAttributes().
useRawEdgeWeights()
bool llvm::DOTFuncInfo::useRawEdgeWeights () inline
Definition at line 108 of file CFGPrinter.h.
Referenced by llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CFGPrinter.h
lib/Analysis/CFGPrinter.cpp