LLVM: llvm::ir2vec::Vocabulary Class Reference
llvm::ir2vec::Vocabulary Class Reference
Class for storing and accessing the IR2Vec vocabulary.
#include "llvm/Analysis/IR2Vec.h"
Public Types
enum class CanonicalTypeID : unsigned {
FloatTy , VoidTy , LabelTy , MetadataTy ,
VectorTy , TokenTy , IntegerTy , FunctionTy ,
PointerTy , StructTy , ArrayTy , UnknownTy ,
MaxCanonicalType
}
Canonical type IDs supported by IR2Vec Vocabulary.
enum class OperandKind : unsigned {
FunctionID , PointerID , ConstantID , VariableID ,
MaxOperandKind
}
Operand kinds supported by IR2Vec Vocabulary.
using const_iterator = VocabStorage::const_iterator
Const Iterator type aliases.
Public Member Functions
Vocabulary ()=default
LLVM_ABI Vocabulary (VocabStorage &&Storage)
Vocabulary (const Vocabulary &)=delete
Vocabulary & operator= (const Vocabulary &)=delete
Vocabulary (Vocabulary &&)=default
Vocabulary & operator= (Vocabulary &&Other)=delete
LLVM_ABI bool isValid () const
LLVM_ABI unsigned getDimension () const
LLVM_ABI const ir2vec::Embedding & operator[] (unsigned Opcode) const
Accessors to get the embedding for a given entity.
LLVM_ABI const ir2vec::Embedding & operator[] (Type::TypeID TypeID) const
LLVM_ABI const ir2vec::Embedding & operator[] (const Value &Arg) const
LLVM_ABI const ir2vec::Embedding & operator[] (CmpInst::Predicate P) const
const_iterator begin () const
const_iterator cbegin () const
const_iterator end () const
const_iterator cend () const
LLVM_ABI bool invalidate (Module &M, const PreservedAnalyses &PA, ModuleAnalysisManager::Invalidator &Inv) const
Static Public Member Functions
static constexpr size_t getCanonicalSize ()
Total number of entries (opcodes + canonicalized types + operand kinds + predicates).
static LLVM_ABI StringRef getVocabKeyForOpcode (unsigned Opcode)
Function to get vocabulary key for a given Opcode.
static LLVM_ABI StringRef getVocabKeyForTypeID (Type::TypeID TypeID)
Function to get vocabulary key for a given TypeID.
static LLVM_ABI StringRef getVocabKeyForOperandKind (OperandKind Kind)
Function to get vocabulary key for a given OperandKind.
static LLVM_ABI OperandKind getOperandKind (const Value *Op)
Function to classify an operand into OperandKind.
static LLVM_ABI StringRef getVocabKeyForPredicate (CmpInst::Predicate P)
Function to get vocabulary key for a given predicate.
static LLVM_ABI unsigned getIndex (unsigned Opcode)
Functions to return flat index.
static LLVM_ABI unsigned getIndex (Type::TypeID TypeID)
static LLVM_ABI unsigned getIndex (const Value &Op)
static LLVM_ABI unsigned getIndex (CmpInst::Predicate P)
static LLVM_ABI StringRef getStringKey (unsigned Pos)
Returns the string key for a given index position in the vocabulary.
static LLVM_ABI VocabStorage createDummyVocabForTest (unsigned Dim=1)
Create a dummy vocabulary for testing purposes.
Static Public Attributes
static constexpr unsigned MaxTypeIDs = Type::TypeID::TargetExtTyID + 1
static constexpr unsigned MaxCanonicalTypeIDs
static constexpr unsigned MaxOperandKinds
static constexpr unsigned MaxPredicateKinds
Friends
class llvm::IR2VecVocabAnalysis
Detailed Description
Class for storing and accessing the IR2Vec vocabulary.
The Vocabulary class manages seed embeddings for LLVM IR entities. The seed embeddings are the initial learned representations of the entities of LLVM IR. The IR2Vec representation for a given IR is derived from these seed embeddings.
The vocabulary contains the seed embeddings for three types of entities: instruction opcodes, types, and operands. Types are grouped/canonicalized for better learning (e.g., all float variants map to FloatTy). The vocabulary abstracts away the canonicalization effectively, the exposed APIs handle all the known LLVM IR opcodes, types and operands.
This class helps populate the seed embeddings in an internal vector-based ADT. It provides logic to map every IR entity to a specific slot index or position in this vector, enabling O(1) embedding lookup while avoiding unnecessary computations involving string based lookups while generating the embeddings.
Definition at line 242 of file IR2Vec.h.
Member Typedef Documentation
const_iterator
using llvm::ir2vec::Vocabulary::const_iterator = VocabStorage::const_iterator
Const Iterator type aliases.
Definition at line 409 of file IR2Vec.h.
Member Enumeration Documentation
CanonicalTypeID
enum class llvm::ir2vec::Vocabulary::CanonicalTypeID : unsigned strong
Canonical type IDs supported by IR2Vec Vocabulary.
Enumerator
FloatTy
VoidTy
LabelTy
MetadataTy
VectorTy
TokenTy
IntegerTy
FunctionTy
PointerTy
StructTy
ArrayTy
UnknownTy
MaxCanonicalType
Definition at line 281 of file IR2Vec.h.
OperandKind
enum class llvm::ir2vec::Vocabulary::OperandKind : unsigned strong
Operand kinds supported by IR2Vec Vocabulary.
Enumerator
FunctionID
PointerID
ConstantID
VariableID
MaxOperandKind
Definition at line 298 of file IR2Vec.h.
Constructor & Destructor Documentation
Vocabulary() [1/4]
llvm::ir2vec::Vocabulary::Vocabulary () default
Referenced by operator=(), operator=(), Vocabulary(), and Vocabulary().
Vocabulary() [2/4]
LLVM_ABI llvm::ir2vec::Vocabulary::Vocabulary (VocabStorage && Storage) inline
Definition at line 322 of file IR2Vec.h.
References LLVM_ABI, and llvm::move().
Vocabulary() [3/4]
llvm::ir2vec::Vocabulary::Vocabulary (const Vocabulary &) delete
References Vocabulary().
Vocabulary() [4/4]
llvm::ir2vec::Vocabulary::Vocabulary (Vocabulary &&) default
References Vocabulary().
Member Function Documentation
begin()
const_iterator llvm::ir2vec::Vocabulary::begin () const inline
Definition at line 411 of file IR2Vec.h.
References assert(), and isValid().
Referenced by cbegin().
cbegin()
const_iterator llvm::ir2vec::Vocabulary::cbegin () const inline
Definition at line 416 of file IR2Vec.h.
References begin().
cend()
const_iterator llvm::ir2vec::Vocabulary::cend () const inline
Definition at line 423 of file IR2Vec.h.
References end().
createDummyVocabForTest()
VocabStorage Vocabulary::createDummyVocabForTest (unsigned Dim = 1) static
Create a dummy vocabulary for testing purposes.
Definition at line 432 of file IR2Vec.cpp.
References I, MaxCanonicalTypeIDs, MaxOperandKinds, MaxPredicateKinds, and llvm::ir2vec::VocabStorage::VocabStorage().
end()
const_iterator llvm::ir2vec::Vocabulary::end () const inline
Definition at line 418 of file IR2Vec.h.
References assert(), and isValid().
Referenced by cend().
getCanonicalSize()
constexpr size_t llvm::ir2vec::Vocabulary::getCanonicalSize () inline static constexpr
Total number of entries (opcodes + canonicalized types + operand kinds + predicates).
Definition at line 341 of file IR2Vec.h.
getDimension()
LLVM_ABI unsigned llvm::ir2vec::Vocabulary::getDimension () const inline
Definition at line 334 of file IR2Vec.h.
References assert(), isValid(), and LLVM_ABI.
Referenced by llvm::FunctionPropertiesInfo::getFunctionPropertiesInfo().
getIndex() [1/4]
LLVM_ABI unsigned llvm::ir2vec::Vocabulary::getIndex (CmpInst::Predicate P) inline static
Definition at line 381 of file IR2Vec.h.
References LLVM_ABI, and P.
getIndex() [2/4]
LLVM_ABI unsigned llvm::ir2vec::Vocabulary::getIndex (const Value & Op) inline static
Definition at line 375 of file IR2Vec.h.
References assert(), getOperandKind(), LLVM_ABI, and MaxOperandKinds.
getIndex() [3/4]
LLVM_ABI unsigned llvm::ir2vec::Vocabulary::getIndex (Type::TypeID TypeID) inline static
Definition at line 370 of file IR2Vec.h.
References assert(), LLVM_ABI, and MaxTypeIDs.
getIndex() [4/4]
LLVM_ABI unsigned llvm::ir2vec::Vocabulary::getIndex (unsigned Opcode) inline static
Functions to return flat index.
Definition at line 365 of file IR2Vec.h.
References assert(), and LLVM_ABI.
getOperandKind()
Vocabulary::OperandKind Vocabulary::getOperandKind (const Value * Op) static
Function to classify an operand into OperandKind.
Definition at line 369 of file IR2Vec.cpp.
References ConstantID, FunctionID, llvm::isa(), PointerID, and VariableID.
Referenced by getIndex(), and operator[]().
getStringKey()
StringRef Vocabulary::getStringKey (unsigned Pos) static
Returns the string key for a given index position in the vocabulary.
This is useful for debugging or printing the vocabulary. Do not use this for embedding generation as string based lookups are inefficient.
Definition at line 408 of file IR2Vec.cpp.
References assert(), getVocabKeyForOpcode(), getVocabKeyForOperandKind(), and getVocabKeyForPredicate().
getVocabKeyForOpcode()
StringRef Vocabulary::getVocabKeyForOpcode (unsigned Opcode) static
Function to get vocabulary key for a given Opcode.
Definition at line 357 of file IR2Vec.cpp.
References assert().
Referenced by getStringKey().
getVocabKeyForOperandKind()
LLVM_ABI StringRef llvm::ir2vec::Vocabulary::getVocabKeyForOperandKind (OperandKind Kind) inline static
Function to get vocabulary key for a given OperandKind.
Definition at line 352 of file IR2Vec.h.
References assert(), LLVM_ABI, and MaxOperandKinds.
Referenced by getStringKey().
getVocabKeyForPredicate()
StringRef Vocabulary::getVocabKeyForPredicate (CmpInst::Predicate P) static
Function to get vocabulary key for a given predicate.
Definition at line 398 of file IR2Vec.cpp.
References llvm::CmpInst::FIRST_ICMP_PREDICATE, and llvm::CmpInst::getPredicateName().
Referenced by getStringKey().
getVocabKeyForTypeID()
LLVM_ABI StringRef llvm::ir2vec::Vocabulary::getVocabKeyForTypeID (Type::TypeID TypeID) inline static
Function to get vocabulary key for a given TypeID.
Definition at line 347 of file IR2Vec.h.
References LLVM_ABI.
invalidate()
bool Vocabulary::invalidate (Module & M, const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator & Inv) const
Definition at line 426 of file IR2Vec.cpp.
References llvm::PreservedAnalyses::getChecker(), and llvm::IR2VecVocabAnalysis.
isValid()
LLVM_ABI bool llvm::ir2vec::Vocabulary::isValid () const inline
Definition at line 330 of file IR2Vec.h.
References LLVM_ABI.
Referenced by begin(), end(), getDimension(), llvm::FunctionPropertiesInfo::getFunctionPropertiesInfo(), and llvm::IR2VecPrinterPass::run().
operator=() [1/2]
Vocabulary & llvm::ir2vec::Vocabulary::operator= (const Vocabulary &) delete
References Vocabulary().
operator=() [2/2]
Vocabulary & llvm::ir2vec::Vocabulary::operator= (Vocabulary && Other) delete
References Vocabulary().
operator[]() [1/4]
LLVM_ABI const ir2vec::Embedding & llvm::ir2vec::Vocabulary::operator[] (CmpInst::Predicate P) const inline
Definition at line 403 of file IR2Vec.h.
References LLVM_ABI, and P.
operator[]() [2/4]
LLVM_ABI const ir2vec::Embedding & llvm::ir2vec::Vocabulary::operator[] (const Value & Arg) const inline
Definition at line 397 of file IR2Vec.h.
References assert(), getOperandKind(), LLVM_ABI, and MaxOperandKinds.
operator[]() [3/4]
LLVM_ABI const ir2vec::Embedding & llvm::ir2vec::Vocabulary::operator[] (Type::TypeID TypeID) const inline
Definition at line 391 of file IR2Vec.h.
References assert(), LLVM_ABI, and MaxTypeIDs.
operator[]() [4/4]
LLVM_ABI const ir2vec::Embedding & llvm::ir2vec::Vocabulary::operator[] (unsigned Opcode) const inline
Accessors to get the embedding for a given entity.
Definition at line 386 of file IR2Vec.h.
References assert(), and LLVM_ABI.
Friends And Related Symbol Documentation
llvm::IR2VecVocabAnalysis
friend class llvm::IR2VecVocabAnalysis friend
Definition at line 243 of file IR2Vec.h.
Referenced by invalidate().
Member Data Documentation
MaxCanonicalTypeIDs
unsigned llvm::ir2vec::Vocabulary::MaxCanonicalTypeIDs static constexpr
Initial value:
                                          =
static_cast<unsigned>(CanonicalTypeID::MaxCanonicalType)
Definition at line 312 of file IR2Vec.h.
Referenced by createDummyVocabForTest().
MaxOperandKinds
unsigned llvm::ir2vec::Vocabulary::MaxOperandKinds static constexpr
Initial value:
                                      =
static_cast<unsigned>(OperandKind::MaxOperandKind)
Definition at line 314 of file IR2Vec.h.
Referenced by createDummyVocabForTest(), getIndex(), getVocabKeyForOperandKind(), and operator[]().
MaxPredicateKinds
unsigned llvm::ir2vec::Vocabulary::MaxPredicateKinds static constexpr
Initial value:
                                        =
NumICmpPredicates + NumFCmpPredicates
Definition at line 318 of file IR2Vec.h.
Referenced by createDummyVocabForTest().
MaxTypeIDs
unsigned llvm::ir2vec::Vocabulary::MaxTypeIDs = Type::TypeID::TargetExtTyID + 1 static constexpr
Definition at line 311 of file IR2Vec.h.
Referenced by getIndex(), and operator[]().
The documentation for this class was generated from the following files:
include/llvm/Analysis/IR2Vec.h
lib/Analysis/IR2Vec.cpp