LLVM: llvm::DICompileUnit Class Reference
llvm::DICompileUnit Class Reference
Compile unit.
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
enum DebugEmissionKind : unsigned {
NoDebug = 0 , FullDebug , LineTablesOnly , DebugDirectivesOnly ,
LastEmissionKind = DebugDirectivesOnly
}
enum class DebugNameTableKind : unsigned {
Default = 0 , GNU = 1 , None = 2 , Apple = 3 ,
LastDebugNameTableKind = Apple
}
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
DEFINE_MDNODE_GET_DISTINCT_TEMPORARY (DICompileUnit,(DISourceLanguageName SourceLanguage, DIFile *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, DebugEmissionKind EmissionKind, DICompositeTypeArray EnumTypes, DIScopeArray RetainedTypes, DIGlobalVariableExpressionArray GlobalVariables, DIImportedEntityArray ImportedEntities, DIMacroNodeArray Macros, uint64_t DWOId, bool SplitDebugInlining, bool DebugInfoForProfiling, DebugNameTableKind NameTableKind, bool RangesBaseAddress, StringRef SysRoot, StringRef SDK),(SourceLanguage, File, Producer, IsOptimized, Flags, RuntimeVersion, SplitDebugFilename, EmissionKind, EnumTypes, RetainedTypes, GlobalVariables, ImportedEntities, Macros, DWOId, SplitDebugInlining, DebugInfoForProfiling,(unsigned) NameTableKind, RangesBaseAddress, SysRoot, SDK)) DEFINE_MDNODE_GET_DISTINCT_TEMPORARY(DICompileUnit
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SDK TempDICompileUnit clone () const
DISourceLanguageName getSourceLanguage () const
bool isOptimized () const
unsigned getRuntimeVersion () const
DebugEmissionKind getEmissionKind () const
bool isDebugDirectivesOnly () const
bool getDebugInfoForProfiling () const
DebugNameTableKind getNameTableKind () const
bool getRangesBaseAddress () const
StringRef getProducer () const
StringRef getFlags () const
StringRef getSplitDebugFilename () const
DICompositeTypeArray getEnumTypes () const
DIScopeArray getRetainedTypes () const
DIGlobalVariableExpressionArray getGlobalVariables () const
DIImportedEntityArray getImportedEntities () const
DIMacroNodeArray getMacros () const
uint64_t getDWOId () const
void setDWOId (uint64_t DwoId)
bool getSplitDebugInlining () const
void setSplitDebugInlining (bool SplitDebugInlining)
StringRef getSysRoot () const
StringRef getSDK () const
MDString * getRawProducer () const
MDString * getRawFlags () const
MDString * getRawSplitDebugFilename () const
Metadata * getRawEnumTypes () const
Metadata * getRawRetainedTypes () const
Metadata * getRawGlobalVariables () const
Metadata * getRawImportedEntities () const
Metadata * getRawMacros () const
MDString * getRawSysRoot () const
MDString * getRawSDK () const
void replaceEnumTypes (DICompositeTypeArray N)
Replace arrays.
void replaceRetainedTypes (DITypeArray N)
void replaceGlobalVariables (DIGlobalVariableExpressionArray N)
void replaceImportedEntities (DIImportedEntityArray N)
void replaceMacros (DIMacroNodeArray N)
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
LLVM_ABI StringRef getName () const
LLVM_ABI DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
LLVM_ABI dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
LLVM_ABI TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
LLVM_ABI void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
bool hasGeneralizedMDString ()
Check if this is a valid generalized type metadata node.
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
LLVM_ABI void resolveCycles ()
Resolve cycles.
LLVM_ABI void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
LLVM_ABI bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
LLVM_ABI void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
LLVM_ABI void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
LLVM_ABI void dumpTree () const
User-friendly dump in tree shape.
LLVM_ABI void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
LLVM_ABI void dump () const
User-friendly dump.
LLVM_ABI void dump (const Module *M) const
LLVM_ABI void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
LLVM_ABI void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
LLVM_ABI void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static LLVM_ABI std::optional< DebugEmissionKind > getEmissionKind (StringRef Str)
static LLVM_ABI const char * emissionKindString (DebugEmissionKind EK)
static LLVM_ABI std::optional< DebugNameTableKind > getNameTableKind (StringRef Str)
static LLVM_ABI const char * nameTableKindString (DebugNameTableKind PK)
static void get ()=delete
static void getIfExists ()=delete
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static LLVM_ABI DIFlags getFlag (StringRef Flag)
static LLVM_ABI StringRef getFlagString (DIFlags Flag)
static LLVM_ABI DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static LLVM_ABI void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T>
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static LLVM_ABI MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static LLVM_ABI MDNode * intersect (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericNoaliasAddrspace (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
static LLVM_ABI MDNode * getMergedMemProfMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCallsiteMetadata (MDNode *A, MDNode *B)
static LLVM_ABI MDNode * getMergedCalleeTypeMetadata (const MDNode *A, const MDNode *B)
static LLVM_ABI CaptureComponents toCaptureComponents (const MDNode *MD)
Convert !captures metadata to CaptureComponents. MD may be nullptr.
static LLVM_ABI MDNode * fromCaptureComponents (LLVMContext &Ctx, CaptureComponents CC)
Convert CaptureComponents to !captures metadata.
Public Attributes
DISourceLanguageName Metadata * File
DISourceLanguageName Metadata MDString * Producer
DISourceLanguageName Metadata MDString bool IsOptimized
DISourceLanguageName Metadata MDString bool MDString * Flags
DISourceLanguageName Metadata MDString bool MDString unsigned RuntimeVersion
DISourceLanguageName Metadata MDString bool MDString unsigned MDString * SplitDebugFilename
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned EmissionKind
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata * EnumTypes
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata * RetainedTypes
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata * GlobalVariables
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata * ImportedEntities
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata * Macros
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t DWOId
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool SplitDebugInlining
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool DebugInfoForProfiling
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned NameTableKind
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool RangesBaseAddress
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString * SysRoot
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString * SDK
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SourceLanguage
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString File
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString Producer
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString IsOptimized
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString Flags
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString RuntimeVersion
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SplitDebugFilename
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString EmissionKind
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString EnumTypes
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString RetainedTypes
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString GlobalVariables
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString ImportedEntities
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString Macros
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString DWOId
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SplitDebugInlining
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString DebugInfoForProfiling
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString NameTableKind
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString RangesBaseAddress
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SysRoot
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Static Public Attributes inherited from llvm::Metadata
static constexpr const unsigned PoisonGeneratingIDs []
Metadata IDs that may generate poison.
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~DINode ()=default
template<class Ty>
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
LLVM_ABI MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2={})
~MDNode ()=default
LLVM_ABI void * operator new (size_t Size, size_t NumOps, StorageType Storage)
LLVM_ABI void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
LLVM_ABI void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
LLVM_ABI void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
LLVM_ABI void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T, class StoreT>
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T>
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Compile unit.
Definition at line 2046 of file DebugInfoMetadata.h.
Member Enumeration Documentation
DebugEmissionKind
enum llvm::DICompileUnit::DebugEmissionKind : unsigned
Enumerator
NoDebug
FullDebug
LineTablesOnly
DebugDirectivesOnly
LastEmissionKind
Definition at line 2051 of file DebugInfoMetadata.h.
DebugNameTableKind
enum class llvm::DICompileUnit::DebugNameTableKind : unsigned strong
Enumerator
Default
GNU
None
Apple
LastDebugNameTableKind
Definition at line 2059 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
bool llvm::DICompileUnit::classof (const Metadata * MD) inline static
Definition at line 2245 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SDK TempDICompileUnit llvm::DICompileUnit::clone () const inline
Definition at line 2170 of file DebugInfoMetadata.h.
References clone().
Referenced by clone().
DEFINE_MDNODE_GET_DISTINCT_TEMPORARY()
llvm::DICompileUnit::DEFINE_MDNODE_GET_DISTINCT_TEMPORARY (DICompileUnit , (DISourceLanguageName SourceLanguage, DIFile *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, DebugEmissionKind EmissionKind, DICompositeTypeArray EnumTypes, DIScopeArray RetainedTypes, DIGlobalVariableExpressionArray GlobalVariables, DIImportedEntityArray ImportedEntities, DIMacroNodeArray Macros, uint64_t DWOId, bool SplitDebugInlining, bool DebugInfoForProfiling, DebugNameTableKind NameTableKind, bool RangesBaseAddress, StringRef SysRoot, StringRef SDK) , (SourceLanguage, File, Producer, IsOptimized, Flags, RuntimeVersion, SplitDebugFilename, EmissionKind, EnumTypes, RetainedTypes, GlobalVariables, ImportedEntities, Macros, DWOId, SplitDebugInlining, DebugInfoForProfiling,(unsigned) NameTableKind, RangesBaseAddress, SysRoot, SDK))
References EnumTypes, File, Flags, GlobalVariables, ImportedEntities, Macros, Producer, RetainedTypes, SDK, SplitDebugFilename, and SysRoot.
emissionKindString()
const char * DICompileUnit::emissionKindString (DebugEmissionKind EK) static
Definition at line 1274 of file DebugInfoMetadata.cpp.
References DebugDirectivesOnly, FullDebug, LineTablesOnly, and NoDebug.
get()
void llvm::DICompileUnit::get () static delete
getDebugInfoForProfiling()
bool llvm::DICompileUnit::getDebugInfoForProfiling () const inline
Definition at line 2181 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfDebug::endFunctionImpl().
getDWOId()
uint64_t llvm::DICompileUnit::getDWOId () const inline
Definition at line 2204 of file DebugInfoMetadata.h.
getEmissionKind() [1/2]
DebugEmissionKind llvm::DICompileUnit::getEmissionKind () const inline
Definition at line 2175 of file DebugInfoMetadata.h.
Referenced by llvm::LLParser::parseMDField().
getEmissionKind() [2/2]
std::optional< DICompileUnit::DebugEmissionKind > DICompileUnit::getEmissionKind (StringRef Str) static
Definition at line 1255 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Case(), DebugDirectivesOnly, llvm::StringSwitch< T, R >::Default(), FullDebug, LineTablesOnly, and NoDebug.
Referenced by llvm::DwarfDebug::endFunctionImpl(), and llvm::DwarfCompileUnit::includeMinimalInlineScopes().
getEnumTypes()
DICompositeTypeArray llvm::DICompileUnit::getEnumTypes () const inline
Definition at line 2189 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawEnumTypes().
getFlags()
StringRef llvm::DICompileUnit::getFlags () const inline
Definition at line 2187 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getGlobalVariables()
DIGlobalVariableExpressionArray llvm::DICompileUnit::getGlobalVariables () const inline
Definition at line 2195 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawGlobalVariables().
getIfExists()
void llvm::DICompileUnit::getIfExists () static delete
getImportedEntities()
DIImportedEntityArray llvm::DICompileUnit::getImportedEntities () const inline
Definition at line 2198 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawImportedEntities().
getMacros()
DIMacroNodeArray llvm::DICompileUnit::getMacros () const inline
Definition at line 2201 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawMacros().
getNameTableKind() [1/2]
DebugNameTableKind llvm::DICompileUnit::getNameTableKind () const inline
Definition at line 2182 of file DebugInfoMetadata.h.
Referenced by llvm::LLParser::parseMDField().
getNameTableKind() [2/2]
std::optional< DICompileUnit::DebugNameTableKind > DICompileUnit::getNameTableKind (StringRef Str) static
Definition at line 1265 of file DebugInfoMetadata.cpp.
References Apple, llvm::StringSwitch< T, R >::Case(), Default, llvm::StringSwitch< T, R >::Default(), GNU, and None.
getProducer()
StringRef llvm::DICompileUnit::getProducer () const inline
Definition at line 2186 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getRangesBaseAddress()
bool llvm::DICompileUnit::getRangesBaseAddress () const inline
Definition at line 2185 of file DebugInfoMetadata.h.
getRawEnumTypes()
Metadata * llvm::DICompileUnit::getRawEnumTypes () const inline
Definition at line 2218 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getEnumTypes().
getRawFlags()
MDString * llvm::DICompileUnit::getRawFlags () const inline
Definition at line 2214 of file DebugInfoMetadata.h.
References llvm::DINode::getOperandAs().
getRawGlobalVariables()
Metadata * llvm::DICompileUnit::getRawGlobalVariables () const inline
Definition at line 2220 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getGlobalVariables().
getRawImportedEntities()
Metadata * llvm::DICompileUnit::getRawImportedEntities () const inline
Definition at line 2221 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getImportedEntities().
getRawMacros()
Metadata * llvm::DICompileUnit::getRawMacros () const inline
Definition at line 2222 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getMacros().
getRawProducer()
MDString * llvm::DICompileUnit::getRawProducer () const inline
Definition at line 2213 of file DebugInfoMetadata.h.
References llvm::DINode::getOperandAs().
getRawRetainedTypes()
Metadata * llvm::DICompileUnit::getRawRetainedTypes () const inline
Definition at line 2219 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getRetainedTypes().
getRawSDK()
MDString * llvm::DICompileUnit::getRawSDK () const inline
Definition at line 2224 of file DebugInfoMetadata.h.
References llvm::DINode::getOperandAs().
getRawSplitDebugFilename()
MDString * llvm::DICompileUnit::getRawSplitDebugFilename () const inline
Definition at line 2215 of file DebugInfoMetadata.h.
References llvm::DINode::getOperandAs().
getRawSysRoot()
MDString * llvm::DICompileUnit::getRawSysRoot () const inline
Definition at line 2223 of file DebugInfoMetadata.h.
References llvm::DINode::getOperandAs().
getRetainedTypes()
DIScopeArray llvm::DICompileUnit::getRetainedTypes () const inline
Definition at line 2192 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawRetainedTypes().
getRuntimeVersion()
unsigned llvm::DICompileUnit::getRuntimeVersion () const inline
Definition at line 2174 of file DebugInfoMetadata.h.
getSDK()
StringRef llvm::DICompileUnit::getSDK () const inline
Definition at line 2211 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getSourceLanguage()
DISourceLanguageName llvm::DICompileUnit::getSourceLanguage () const inline
Definition at line 2172 of file DebugInfoMetadata.h.
getSplitDebugFilename()
StringRef llvm::DICompileUnit::getSplitDebugFilename () const inline
Definition at line 2188 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getSplitDebugInlining()
bool llvm::DICompileUnit::getSplitDebugInlining () const inline
Definition at line 2206 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfDebug::endFunctionImpl().
getSysRoot()
StringRef llvm::DICompileUnit::getSysRoot () const inline
Definition at line 2210 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
isDebugDirectivesOnly()
bool llvm::DICompileUnit::isDebugDirectivesOnly () const inline
Definition at line 2178 of file DebugInfoMetadata.h.
References DebugDirectivesOnly.
Referenced by llvm::DwarfFile::emitUnit(), and llvm::DwarfDebug::endFunctionImpl().
isOptimized()
bool llvm::DICompileUnit::isOptimized () const inline
Definition at line 2173 of file DebugInfoMetadata.h.
nameTableKindString()
const char * DICompileUnit::nameTableKindString (DebugNameTableKind PK) static
Definition at line 1288 of file DebugInfoMetadata.cpp.
References Apple, Default, GNU, and None.
replaceEnumTypes()
void llvm::DICompileUnit::replaceEnumTypes (DICompositeTypeArray N) inline
Replace arrays.
If this isUniqued() and not isResolved(), it will be RAUW'ed and deleted on a uniquing collision. In practice, uniquing collisions on DICompileUnit should be fairly rare.
Definition at line 2232 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
replaceGlobalVariables()
void llvm::DICompileUnit::replaceGlobalVariables (DIGlobalVariableExpressionArray N) inline
Definition at line 2236 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
replaceImportedEntities()
void llvm::DICompileUnit::replaceImportedEntities (DIImportedEntityArray N) inline
Definition at line 2239 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
replaceMacros()
void llvm::DICompileUnit::replaceMacros (DIMacroNodeArray N) inline
Definition at line 2242 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
replaceRetainedTypes()
void llvm::DICompileUnit::replaceRetainedTypes (DITypeArray N) inline
Definition at line 2235 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
setDWOId()
void llvm::DICompileUnit::setDWOId (uint64_t DwoId) inline
Definition at line 2205 of file DebugInfoMetadata.h.
setSplitDebugInlining()
void llvm::DICompileUnit::setSplitDebugInlining (bool SplitDebugInlining) inline
Definition at line 2207 of file DebugInfoMetadata.h.
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 2047 of file DebugInfoMetadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
MDNode
friend class MDNode friend
Definition at line 2048 of file DebugInfoMetadata.h.
References MDNode.
Referenced by MDNode.
Member Data Documentation
DebugInfoForProfiling [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::DebugInfoForProfiling
Definition at line 2168 of file DebugInfoMetadata.h.
DebugInfoForProfiling [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool llvm::DICompileUnit::DebugInfoForProfiling
Definition at line 2162 of file DebugInfoMetadata.h.
DWOId [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::DWOId
Definition at line 2167 of file DebugInfoMetadata.h.
DWOId [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::DWOId
Definition at line 2161 of file DebugInfoMetadata.h.
EmissionKind [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::EmissionKind
Definition at line 2166 of file DebugInfoMetadata.h.
EmissionKind [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned llvm::DICompileUnit::EmissionKind
Definition at line 2159 of file DebugInfoMetadata.h.
EnumTypes [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::EnumTypes
Definition at line 2166 of file DebugInfoMetadata.h.
EnumTypes [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata* llvm::DICompileUnit::EnumTypes
Definition at line 2159 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
File [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::File
Definition at line 2165 of file DebugInfoMetadata.h.
File [2/2]
DISourceLanguageName Metadata* llvm::DICompileUnit::File
Definition at line 2157 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
Flags [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::Flags
Definition at line 2165 of file DebugInfoMetadata.h.
Flags [2/2]
DISourceLanguageName Metadata MDString bool MDString* llvm::DICompileUnit::Flags
Definition at line 2158 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
GlobalVariables [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::GlobalVariables
Definition at line 2167 of file DebugInfoMetadata.h.
GlobalVariables [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata* llvm::DICompileUnit::GlobalVariables
Definition at line 2160 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
ImportedEntities [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::ImportedEntities
Definition at line 2167 of file DebugInfoMetadata.h.
ImportedEntities [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata* llvm::DICompileUnit::ImportedEntities
Definition at line 2161 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
IsOptimized [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::IsOptimized
Definition at line 2165 of file DebugInfoMetadata.h.
IsOptimized [2/2]
DISourceLanguageName Metadata MDString bool llvm::DICompileUnit::IsOptimized
Definition at line 2158 of file DebugInfoMetadata.h.
Macros [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::Macros
Definition at line 2167 of file DebugInfoMetadata.h.
Macros [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata* llvm::DICompileUnit::Macros
Definition at line 2161 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
NameTableKind [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::NameTableKind
Definition at line 2168 of file DebugInfoMetadata.h.
NameTableKind [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned llvm::DICompileUnit::NameTableKind
Definition at line 2163 of file DebugInfoMetadata.h.
Producer [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::Producer
Definition at line 2165 of file DebugInfoMetadata.h.
Producer [2/2]
DISourceLanguageName Metadata MDString* llvm::DICompileUnit::Producer
Definition at line 2157 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
RangesBaseAddress [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::RangesBaseAddress
Definition at line 2168 of file DebugInfoMetadata.h.
RangesBaseAddress [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::RangesBaseAddress
Definition at line 2163 of file DebugInfoMetadata.h.
RetainedTypes [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::RetainedTypes
Definition at line 2166 of file DebugInfoMetadata.h.
RetainedTypes [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata* llvm::DICompileUnit::RetainedTypes
Definition at line 2160 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
RuntimeVersion [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::RuntimeVersion
Definition at line 2165 of file DebugInfoMetadata.h.
RuntimeVersion [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned llvm::DICompileUnit::RuntimeVersion
Definition at line 2158 of file DebugInfoMetadata.h.
SDK
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString* llvm::DICompileUnit::SDK
Definition at line 2164 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
SourceLanguage
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SourceLanguage
Definition at line 2165 of file DebugInfoMetadata.h.
SplitDebugFilename [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SplitDebugFilename
Definition at line 2166 of file DebugInfoMetadata.h.
SplitDebugFilename [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString* llvm::DICompileUnit::SplitDebugFilename
Definition at line 2159 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
SplitDebugInlining [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SplitDebugInlining
Definition at line 2167 of file DebugInfoMetadata.h.
SplitDebugInlining [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool llvm::DICompileUnit::SplitDebugInlining
Definition at line 2162 of file DebugInfoMetadata.h.
SysRoot [1/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SysRoot
Definition at line 2168 of file DebugInfoMetadata.h.
SysRoot [2/2]
DISourceLanguageName Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString* llvm::DICompileUnit::SysRoot
Definition at line 2163 of file DebugInfoMetadata.h.
Referenced by DEFINE_MDNODE_GET_DISTINCT_TEMPORARY().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp