LLVM: llvm::orc::DylibSymbolResolver Class Reference
llvm::orc::DylibSymbolResolver Class Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/ExecutorResolver.h"
Public Member Functions
DylibSymbolResolver (tpctypes::DylibHandle H)
void resolveAsync (const RemoteSymbolLookupSet &L, ExecutorResolver::YieldResolveResultFn &&OnResolve) override
Public Member Functions inherited from llvm::orc::ExecutorResolver
virtual ~ExecutorResolver ()=default
Additional Inherited Members
Public Types inherited from llvm::orc::ExecutorResolver
using ResolveResult = Expected<std::vector<std::optional<ExecutorSymbolDef>>>
using YieldResolveResultFn = unique_function<void(ResolveResult)>
Detailed Description
Definition at line 35 of file ExecutorResolver.h.
Constructor & Destructor Documentation
DylibSymbolResolver()
llvm::orc::DylibSymbolResolver::DylibSymbolResolver (tpctypes::DylibHandle H) inline
Definition at line 37 of file ExecutorResolver.h.
References H.
Member Function Documentation
resolveAsync()
void llvm::orc::DylibSymbolResolver::resolveAsync (const RemoteSymbolLookupSet & L, ExecutorResolver::YieldResolveResultFn && OnResolve) override virtual
Implements llvm::orc::ExecutorResolver.
Definition at line 9 of file ExecutorResolver.cpp.
References DL, E(), llvm::JITSymbolFlags::Exported, llvm::orc::ExecutorAddr::fromPtr(), llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::orc::Result.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/ExecutorResolver.h
lib/ExecutionEngine/Orc/TargetProcess/ExecutorResolver.cpp