LLVM: llvm::orc::LibraryResolutionDriver Class Reference
llvm::orc::LibraryResolutionDriver Class Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h"
Public Member Functions
void addScanPath (const std::string &Path, PathType Kind)
void markLibraryLoaded (StringRef Path)
void markLibraryUnLoaded (StringRef Path)
bool isLibraryLoaded (StringRef Path) const
void resetAll ()
void scanAll (size_t BatchSize=0)
void scan (PathType PK, size_t BatchSize=0)
void resolveSymbols (ArrayRef< StringRef > Symbols, LibraryResolver::OnSearchComplete OnCompletion, const SearchConfig &Config=SearchConfig())
~LibraryResolutionDriver ()=default
Static Public Member Functions
static std::unique_ptr< LibraryResolutionDriver > create (const LibraryResolver::Setup &S)
Detailed Description
Definition at line 559 of file LibraryResolver.h.
Constructor & Destructor Documentation
~LibraryResolutionDriver()
llvm::orc::LibraryResolutionDriver::~LibraryResolutionDriver () default
References llvm::move().
Member Function Documentation
addScanPath()
void llvm::orc::LibraryResolutionDriver::addScanPath (const std::string & Path, PathType Kind)
Definition at line 55 of file LibraryResolver.cpp.
References addScanPath().
Referenced by addScanPath().
create()
std::unique_ptr< LibraryResolutionDriver > llvm::orc::LibraryResolutionDriver::create (const LibraryResolver::Setup & S) static
Definition at line 49 of file LibraryResolver.cpp.
References create().
Referenced by create().
isLibraryLoaded()
bool llvm::orc::LibraryResolutionDriver::isLibraryLoaded (StringRef Path) const inline
Definition at line 567 of file LibraryResolver.h.
markLibraryLoaded()
void llvm::orc::LibraryResolutionDriver::markLibraryLoaded (StringRef Path)
Definition at line 59 of file LibraryResolver.cpp.
References markLibraryLoaded().
Referenced by markLibraryLoaded().
markLibraryUnLoaded()
void llvm::orc::LibraryResolutionDriver::markLibraryUnLoaded (StringRef Path)
Definition at line 63 of file LibraryResolver.cpp.
References markLibraryUnLoaded().
Referenced by markLibraryUnLoaded().
resetAll()
void llvm::orc::LibraryResolutionDriver::resetAll () inline
Definition at line 571 of file LibraryResolver.h.
resolveSymbols()
void llvm::orc::LibraryResolutionDriver::resolveSymbols (ArrayRef< StringRef > Symbols, LibraryResolver::OnSearchComplete OnCompletion, const SearchConfig & Config = SearchConfig())
Definition at line 67 of file LibraryResolver.cpp.
References resolveSymbols().
Referenced by resolveSymbols().
scan()
void llvm::orc::LibraryResolutionDriver::scan (PathType PK, size_t BatchSize = 0) inline
Definition at line 582 of file LibraryResolver.h.
scanAll()
void llvm::orc::LibraryResolutionDriver::scanAll (size_t BatchSize = 0) inline
Definition at line 577 of file LibraryResolver.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryResolver.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryResolver.cpp