LLVM: llvm::BasicTTIImplBase< T > Class Template Reference
llvm::BasicTTIImplBase< T > Class Template Reference
Base class which can be used to help build a TTI implementation.
#include "llvm/CodeGen/BasicTTIImpl.h"
Public Member Functions
Scalar TTI Implementations
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const override
bool areInlineCompatible (const Function *Caller, const Function *Callee) const override
bool hasBranchDivergence (const Function *F=nullptr) const override
bool isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const override
bool addrspacesMayAlias (unsigned AS0, unsigned AS1) const override
unsigned getFlatAddressSpace () const override
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const override
bool isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const override
unsigned getAssumedAddrSpace (const Value *V) const override
bool isSingleThreaded () const override
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const override
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const override
bool isLegalAddImmediate (int64_t imm) const override
bool isLegalAddScalableImmediate (int64_t Imm) const override
bool isLegalICmpImmediate (int64_t imm) const override
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr, int64_t ScalableOffset=0) const override
int64_t getPreferredLargeGEPBaseOffset (int64_t MinOffset, int64_t MaxOffset)
unsigned getStoreMinimumVF (unsigned VF, Type *ScalarMemTy, Type *ScalarValTy) const override
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty) const override
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty) const override
bool isLSRCostLess (const TTI::LSRCost &C1, const TTI::LSRCost &C2) const override
bool isNumRegsMajorCostOfLSR () const override
bool shouldDropLSRSolutionIfLessProfitable () const override
bool isProfitableLSRChainElement (Instruction *I) const override
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const override
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
bool isProfitableToHoist (Instruction *I) const override
bool useAA () const override
bool isTypeLegal (Type *Ty) const override
unsigned getRegUsageForType (Type *Ty) const override
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const override
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const override
bool shouldBuildLookupTables () const override
bool shouldBuildRelLookupTables () const override
bool haveFastSqrt (Type *Ty) const override
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const override
InstructionCost getFPOpCost (Type *Ty) const override
bool preferToKeepConstantsAttached (const Instruction &Inst, const Function &Fn) const override
unsigned getInliningThresholdMultiplier () const override
unsigned adjustInliningThreshold (const CallBase *CB) const override
unsigned getCallerAllocaCost (const CallBase *CB, const AllocaInst *AI) const override
int getInlinerVectorBonusPercent () const override
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP, OptimizationRemarkEmitter *ORE) const override
void getPeelingPreferences (Loop *L, ScalarEvolution &SE, TTI::PeelingPreferences &PP) const override
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const override
unsigned getEpilogueVectorizationMinVF () const override
bool preferPredicateOverEpilogue (TailFoldingInfo *TFI) const override
TailFoldingStyle getPreferredTailFoldingStyle (bool IVUpdateMayOverflow=true) const override
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const override
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const override
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const override
std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const override
std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const override
unsigned getCacheLineSize () const override
unsigned getPrefetchDistance () const override
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const override
unsigned getMaxPrefetchIterationsAhead () const override
bool enableWritePrefetching () const override
bool shouldPrefetchAddressSpace (unsigned AS) const override
Vector TTI Implementations
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const override
std::optional< unsigned > getMaxVScale () const override
std::optional< unsigned > getVScaleForTuning () const override
bool isVScaleKnownToBeAPowerOfTwo () const override
InstructionCost getScalarizationOverhead (VectorType *InTy, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc=true, ArrayRef< Value * > VL={}) const override
Estimate the overhead of scalarizing an instruction.
bool isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const override
bool isTargetIntrinsicWithScalarOpAtArg (Intrinsic::ID ID, unsigned ScalarOpdIdx) const override
bool isTargetIntrinsicWithOverloadTypeAtArg (Intrinsic::ID ID, int OpdIdx) const override
bool isTargetIntrinsicWithStructReturnOverloadAtField (Intrinsic::ID ID, int RetIdx) const override
InstructionCost getScalarizationOverhead (VectorType *InTy, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
InstructionCost getOperandsScalarizationOverhead (ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const override
Estimate the overhead of scalarizing an instruction's operands.
InstructionCost getScalarizationOverhead (VectorType *RetTy, ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
Estimate the overhead of scalarizing the inputs and outputs of an instruction, with return type RetTy and arguments Args of type Tys.
std::pair< InstructionCost, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
unsigned getMaxInterleaveFactor (ElementCount VF) const override
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Opd2Info={TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const override
TTI::ShuffleKind improveShuffleKindFromMask (TTI::ShuffleKind Kind, ArrayRef< int > Mask, VectorType *SrcTy, int &Index, VectorType *&SubTy) const
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *DstTy, VectorType *SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args={}, const Instruction *CxtI=nullptr) const override
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index, TTI::TargetCostKind CostKind) const override
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const override
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr) const override
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, const Value *Op0, const Value *Op1) const override
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const override
InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const override
InstructionCost getIndexedVectorInstrCostFromEnd (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const override
InstructionCost getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind) const override
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr) const override
InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false) const override
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const override
Get intrinsic cost based on arguments.
InstructionCost getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
Get intrinsic cost based on argument types.
InstructionCost getMemIntrinsicInstrCost (const MemIntrinsicCostAttributes &MICA, TTI::TargetCostKind CostKind) const override
Get memory intrinsic cost based on arguments.
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const override
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp) const override
InstructionCost getAddressComputationCost (Type *PtrTy, ScalarEvolution *, const SCEV *, TTI::TargetCostKind) const override
InstructionCost getTreeReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind) const
Try to calculate arithmetic and shuffle op costs for reduction intrinsics.
InstructionCost getOrderedReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind) const
Try to calculate the cost of performing strict (in-order) reductions, which involves doing a sequence of floating point additions in lane order, starting with an initial value.
InstructionCost getArithmeticReductionCost (unsigned Opcode, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override
InstructionCost getMinMaxReductionCost (Intrinsic::ID IID, VectorType *Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const override
Try to calculate op costs for min/max reduction operations.
InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const override
InstructionCost getMulAccReductionCost (bool IsUnsigned, unsigned RedOpcode, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind) const override
InstructionCost getVectorSplitCost () const
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, Type *AccessType, TTI::TargetCostKind CostKind) const override
InstructionCost getPointersChainCost (ArrayRef< const Value * > Ptrs, const Value *Base, const TTI::PointersChainInfo &Info, Type *AccessTy, TTI::TargetCostKind CostKind) const override
InstructionCost getInstructionCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const override
bool isExpensiveToSpeculativelyExecute (const Instruction *I) const override
bool supportsTailCallFor (const CallBase *CB) const override
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
virtual ~TargetTransformInfoImplBase ()
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)=default
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
virtual const DataLayout & getDataLayout () const
virtual unsigned getInliningCostBenefitAnalysisSavingsMultiplier () const
virtual unsigned getInliningCostBenefitAnalysisProfitableMultiplier () const
virtual int getInliningLastCallToStaticBonus () const
virtual InstructionCost getMemcpyCost (const Instruction *I) const
virtual uint64_t getMaxMemIntrinsicInlineSizeThreshold () const
virtual BranchProbability getPredictableBranchThreshold () const
virtual InstructionCost getBranchMispredictPenalty () const
virtual InstructionUniformity getInstructionUniformity (const Value *V) const
virtual bool canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const
virtual bool isLoweredToCall (const Function *F) const
virtual bool canMacroFuseCmp () const
virtual bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
virtual TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
virtual bool isLegalMaskedStore (Type *DataType, Align Alignment, unsigned AddressSpace, TTI::MaskKind MaskKind) const
virtual bool isLegalMaskedLoad (Type *DataType, Align Alignment, unsigned AddressSpace, TTI::MaskKind MaskKind) const
virtual bool isLegalNTStore (Type *DataType, Align Alignment) const
virtual bool isLegalNTLoad (Type *DataType, Align Alignment) const
virtual bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const
virtual bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
virtual bool isLegalMaskedGather (Type *DataType, Align Alignment) const
virtual bool forceScalarizeMaskedGather (VectorType *DataType, Align Alignment) const
virtual bool forceScalarizeMaskedScatter (VectorType *DataType, Align Alignment) const
virtual bool isLegalMaskedCompressStore (Type *DataType, Align Alignment) const
virtual bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const
virtual bool isLegalMaskedExpandLoad (Type *DataType, Align Alignment) const
virtual bool isLegalStridedLoadStore (Type *DataType, Align Alignment) const
virtual bool isLegalInterleavedAccessType (VectorType *VTy, unsigned Factor, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalMaskedVectorHistogram (Type *AddrType, Type *DataType) const
virtual bool enableOrderedReductions () const
virtual bool hasDivRemOp (Type *DataType, bool IsSigned) const
virtual bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
virtual bool prefersVectorizedAddressing () const
virtual bool LSRWithInstrQueries () const
virtual bool shouldBuildLookupTablesForConstant (Constant *C) const
virtual bool useColdCCForColdCall (Function &F) const
virtual bool useFastCCForInternalCall (Function &F) const
virtual bool supportsEfficientVectorElementLoadStore () const
virtual bool supportsTailCalls () const
virtual bool enableAggressiveInterleaving (bool LoopHasReductions) const
virtual TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
virtual bool enableSelectOptimize () const
virtual bool shouldTreatInstructionLikeSelect (const Instruction *I) const
virtual bool enableInterleavedAccessVectorization () const
virtual bool enableMaskedInterleavedAccessVectorization () const
virtual bool isFPVectorizationPotentiallyUnsafe () const
virtual TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
virtual InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
virtual InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
virtual InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const
virtual InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
virtual unsigned getNumberOfRegisters (unsigned ClassID) const
virtual bool hasConditionalLoadStoreForType (Type *Ty, bool IsStore) const
virtual unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
virtual const char * getRegisterClassName (unsigned ClassID) const
virtual unsigned getMinVectorRegisterBitWidth () const
virtual bool shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const
virtual ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
virtual unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
virtual bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
virtual std::optional< unsigned > getMinPageSize () const
virtual InstructionCost getPartialReductionCost (unsigned Opcode, Type *InputTypeA, Type *InputTypeB, Type *AccumType, ElementCount VF, TTI::PartialReductionExtendKind OpAExtend, TTI::PartialReductionExtendKind OpBExtend, std::optional< unsigned > BinOp, TTI::TargetCostKind CostKind) const
virtual InstructionCost getAltInstrCost (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask, TTI::TargetCostKind CostKind) const
virtual InstructionCost getInsertExtractValueCost (unsigned Opcode, TTI::TargetCostKind CostKind) const
virtual InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
virtual bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
virtual unsigned getAtomicMemIntrinsicMaxElementSize () const
virtual Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType, bool CanCreate=true) const
virtual Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicElementSize) const
virtual void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, Align SrcAlign, Align DestAlign, std::optional< uint32_t > AtomicCpySize) const
virtual unsigned getInlineCallPenalty (const Function *F, const CallBase &Call, unsigned DefaultCallPenalty) const
virtual bool areTypesABICompatible (const Function *Caller, const Function *Callee, ArrayRef< Type * > Types) const
virtual unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
virtual bool isLegalToVectorizeLoad (LoadInst *LI) const
virtual bool isLegalToVectorizeStore (StoreInst *SI) const
virtual bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
virtual bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
virtual bool isElementTypeLegalForScalableVector (Type *Ty) const
virtual unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
virtual bool preferFixedOverScalableIfEqualCost (bool IsEpilogue) const
virtual bool preferInLoopReduction (RecurKind Kind, Type *Ty) const
virtual bool preferAlternateOpcodeVectorization () const
virtual bool preferPredicatedReductionSelect () const
virtual bool preferEpilogueVectorization () const
virtual bool shouldConsiderVectorizationRegPressure () const
virtual bool shouldExpandReduction (const IntrinsicInst *II) const
virtual TTI::ReductionShuffle getPreferredExpandedReductionShuffle (const IntrinsicInst *II) const
virtual unsigned getGISelRematGlobalCost () const
virtual unsigned getMinTripCountTailFoldingThreshold () const
virtual bool supportsScalableVectors () const
virtual bool enableScalableVectorization () const
virtual bool hasActiveVectorLength () const
virtual bool isProfitableToSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
virtual bool hasArmWideBranch (bool) const
virtual APInt getFeatureMask (const Function &F) const
virtual APInt getPriorityMask (const Function &F) const
virtual bool isMultiversionedFunction (const Function &F) const
virtual unsigned getMaxNumArgs () const
virtual unsigned getNumBytesToPadGlobalArray (unsigned Size, Type *ArrayType) const
virtual void collectKernelLaunchBounds (const Function &F, SmallVectorImpl< std::pair< StringRef, int64_t > > &LB) const
virtual bool allowVectorElementIndexingUsingGEP () const
Protected Member Functions
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
~BasicTTIImplBase () override=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Detailed Description
template<typename T>
class llvm::BasicTTIImplBase< T >
Base class which can be used to help build a TTI implementation.
This class provides as much implementation of the TTI interface as is possible using the target independent parts of the code generator.
In order to subclass it, your class must implement a getST() method to return the subtarget, and a getTLI() method to return the target lowering. We need these methods implemented in the derived class so that this class doesn't have to duplicate storage for them.
Definition at line 82 of file BasicTTIImpl.h.
Constructor & Destructor Documentation
BasicTTIImplBase()
template<typename T> llvm::BasicTTIImplBase< T >::BasicTTIImplBase (const TargetMachine * TM, const DataLayout & DL) inline explicit protected
Definition at line 378 of file BasicTTIImpl.h.
~BasicTTIImplBase()
template<typename T> llvm::BasicTTIImplBase< T >::~BasicTTIImplBase () override protected default
Member Function Documentation
addrspacesMayAlias()
template<typename T> bool llvm::BasicTTIImplBase< T >::addrspacesMayAlias (unsigned AS0, unsigned AS1) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl.
Definition at line 417 of file BasicTTIImpl.h.
adjustInliningThreshold()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::adjustInliningThreshold (const CallBase * CB) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 700 of file BasicTTIImpl.h.
allowsMisalignedMemoryAccesses()
template<typename T> bool llvm::BasicTTIImplBase< T >::allowsMisalignedMemoryAccesses (LLVMContext & Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned * Fast) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 387 of file BasicTTIImpl.h.
areInlineCompatible()
template<typename T> bool llvm::BasicTTIImplBase< T >::areInlineCompatible (const Function * Caller, const Function * Callee) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, and llvm::X86TTIImpl.
Definition at line 395 of file BasicTTIImpl.h.
collectFlatAddressOperands()
template<typename T> bool llvm::BasicTTIImplBase< T >::collectFlatAddressOperands (SmallVectorImpl< int > & OpIndexes, Intrinsic::ID IID) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::SPIRVTTIImpl.
Definition at line 426 of file BasicTTIImpl.h.
enableWritePrefetching()
template<typename T> bool llvm::BasicTTIImplBase< T >::enableWritePrefetching () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::LoongArchTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 869 of file BasicTTIImpl.h.
getAddressComputationCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getAddressComputationCost (Type * PtrTy, ScalarEvolution * , const SCEV * , TTI::TargetCostKind) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::HexagonTTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 3148 of file BasicTTIImpl.h.
getArithmeticInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info = {TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Opd2Info = {TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::BPFTTIImpl, llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LanaiTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1041 of file BasicTTIImpl.h.
Referenced by llvm::WebAssemblyTTIImpl::getArithmeticInstrCost().
getArithmeticReductionCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getArithmeticReductionCost (unsigned Opcode, VectorType * Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 3268 of file BasicTTIImpl.h.
getAssumedAddrSpace()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getAssumedAddrSpace (const Value * V) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::NVPTXTTIImpl.
Definition at line 435 of file BasicTTIImpl.h.
getCacheAssociativity()
template<typename T> std::optional< unsigned > llvm::BasicTTIImplBase< T >::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 839 of file BasicTTIImpl.h.
getCacheLineSize()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getCacheLineSize () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 849 of file BasicTTIImpl.h.
getCacheSize()
template<typename T> std::optional< unsigned > llvm::BasicTTIImplBase< T >::getCacheSize (TargetTransformInfo::CacheLevel Level) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 833 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getCacheSize().
getCallerAllocaCost()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getCallerAllocaCost (const CallBase * CB, const AllocaInst * AI) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl.
Definition at line 703 of file BasicTTIImpl.h.
getCallInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline override virtual
Compute a cost of the given call instruction.
Compute the cost of calling function F with return type RetTy and argument types Tys. F might be nullptr, in this case the cost of an arbitrary call with the specified signature will be returned. This is used, for instance, when we estimate call of a vector counterpart of the given function.
Parameters
F Called function, might be nullptr.
RetTy Return value types.
Tys Argument types.
Returns
The cost of Call instruction.
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::HexagonTTIImpl.
Definition at line 3125 of file BasicTTIImpl.h.
getCastInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1204 of file BasicTTIImpl.h.
getCFInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 1374 of file BasicTTIImpl.h.
getCmpSelInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info = {TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info = {TTI::OK_AnyValue, TTI::OP_None}, const Instruction * I = nullptr) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::BPFTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 1379 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost().
getEpilogueVectorizationMinVF()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getEpilogueVectorizationMinVF () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 796 of file BasicTTIImpl.h.
getEstimatedNumberOfCaseClusters()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getEstimatedNumberOfCaseClusters (const SwitchInst & SI, unsigned & JumpTableSize, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI) const inline override virtual
Try to find the estimated number of clusters. Note that the number of clusters identified in this function could be different from the actual numbers found in lowering. This function ignore switches that are lowered with a mix of jump table / bit test / BTree. This function was initially intended to be used when estimating the cost of switch in inline cost heuristic, but it's a generic cost model to be used in other places (e.g., in loop unrolling).
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 571 of file BasicTTIImpl.h.
getExtendedReductionCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type * ResTy, VectorType * Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 3328 of file BasicTTIImpl.h.
getExtractWithExtendCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getExtractWithExtendCost (unsigned Opcode, Type * Dst, VectorType * VecTy, unsigned Index, TTI::TargetCostKind CostKind) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 1364 of file BasicTTIImpl.h.
getFlatAddressSpace()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getFlatAddressSpace () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::SPIRVTTIImpl.
Definition at line 421 of file BasicTTIImpl.h.
getFPOpCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getFPOpCost (Type * Ty) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 670 of file BasicTTIImpl.h.
getGEPCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getGEPCost (Type * PointeeType, const Value * Ptr, ArrayRef< const Value * > Operands, Type * AccessType, TTI::TargetCostKind CostKind) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 565 of file BasicTTIImpl.h.
getIndexedVectorInstrCostFromEnd()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getIndexedVectorInstrCostFromEnd (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 1465 of file BasicTTIImpl.h.
getInlinerVectorBonusPercent()
template<typename T> int llvm::BasicTTIImplBase< T >::getInlinerVectorBonusPercent () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl.
Definition at line 708 of file BasicTTIImpl.h.
getInliningThresholdMultiplier()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getInliningThresholdMultiplier () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 699 of file BasicTTIImpl.h.
getInterleavedMemoryOpCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond = false, bool UseMaskForGaps = false) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1556 of file BasicTTIImpl.h.
getIntrinsicInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) const inline override virtual
Get intrinsic cost based on arguments.
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 1704 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getMinMaxReductionCost().
getMaxInterleaveFactor()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getMaxInterleaveFactor (ElementCount VF) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 1039 of file BasicTTIImpl.h.
getMaxPrefetchIterationsAhead()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getMaxPrefetchIterationsAhead () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 865 of file BasicTTIImpl.h.
getMaxVScale()
template<typename T> std::optional< unsigned > llvm::BasicTTIImplBase< T >::getMaxVScale () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 887 of file BasicTTIImpl.h.
getMemIntrinsicInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getMemIntrinsicInstrCost (const MemIntrinsicCostAttributes & MICA, TTI::TargetCostKind CostKind) const inline override virtual
Get memory intrinsic cost based on arguments.
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl, and llvm::X86TTIImpl.
Definition at line 3053 of file BasicTTIImpl.h.
getMemoryOpCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo = {TTI::OK_AnyValue, TTI::OP_None}, const Instruction * I = nullptr) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1511 of file BasicTTIImpl.h.
getMinMaxReductionCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getMinMaxReductionCost (Intrinsic::ID IID, VectorType * Ty, FastMathFlags FMF, TTI::TargetCostKind CostKind) const inline override virtual
Try to calculate op costs for min/max reduction operations.
Parameters
CondTy Conditional type for the Select instruction.
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 3280 of file BasicTTIImpl.h.
getMinPrefetchStride()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::SystemZTTIImpl.
Definition at line 857 of file BasicTTIImpl.h.
getMulAccReductionCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getMulAccReductionCost (bool IsUnsigned, unsigned RedOpcode, Type * ResTy, VectorType * Ty, TTI::TargetCostKind CostKind) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 3357 of file BasicTTIImpl.h.
getNumberOfParts()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getNumberOfParts (Type * Tp) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl.
Definition at line 3130 of file BasicTTIImpl.h.
getOperandsScalarizationOverhead()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead (ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline override virtual
Estimate the overhead of scalarizing an instruction's operands.
The (potentially vector) types to use for each of argument are passes via Tys.
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 965 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), and llvm::BasicTTIImplBase< BasicTTIImpl >::getScalarizationOverhead().
getOrderedReductionCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getOrderedReductionCost (unsigned Opcode, VectorType * Ty, TTI::TargetCostKind CostKind) const inline
Try to calculate the cost of performing strict (in-order) reductions, which involves doing a sequence of floating point additions in lane order, starting with an initial value.
For example, consider a scalar initial value 'InitVal' of type float and a vector of type <4 x float>:
Vector = <float v0, float v1, float v2, float v3>
add1 = InitVal + v0 add2 = add1 + v1 add3 = add2 + v2 add4 = add3 + v3
As a simple estimate we can say the cost of such a reduction is 4 times the cost of a scalar FP addition. We can only estimate the costs for fixed-width vectors here because for scalable vectors we do not know the runtime number of operations.
Definition at line 3250 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getArithmeticReductionCost().
getPeelingPreferences()
template<typename T> void llvm::BasicTTIImplBase< T >::getPeelingPreferences (Loop * L, ScalarEvolution & SE, TTI::PeelingPreferences & PP) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 782 of file BasicTTIImpl.h.
getPredicatedAddrSpace()
template<typename T> std::pair< const Value *, unsigned > llvm::BasicTTIImplBase< T >::getPredicatedAddrSpace (const Value * V) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 445 of file BasicTTIImpl.h.
getPreferredLargeGEPBaseOffset()
template<typename T> int64_t llvm::BasicTTIImplBase< T >::getPreferredLargeGEPBaseOffset (int64_t MinOffset, int64_t MaxOffset) inline
Definition at line 479 of file BasicTTIImpl.h.
getPreferredTailFoldingStyle()
template<typename T> TailFoldingStyle llvm::BasicTTIImplBase< T >::getPreferredTailFoldingStyle (bool IVUpdateMayOverflow = true) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 805 of file BasicTTIImpl.h.
getPrefetchDistance()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getPrefetchDistance () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::PPCTTIImpl, and llvm::SystemZTTIImpl.
Definition at line 853 of file BasicTTIImpl.h.
getRegisterBitWidth()
template<typename T> TypeSize llvm::BasicTTIImplBase< T >::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::LoongArchTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::VETTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 883 of file BasicTTIImpl.h.
getRegUsageForType()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getRegUsageForType (Type * Ty) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 560 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getVectorInstrCost().
getReplicationShuffleCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getReplicationShuffleCost (Type * EltTy, int ReplicationFactor, int VF, const APInt & DemandedDstElts, TTI::TargetCostKind CostKind) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 1479 of file BasicTTIImpl.h.
getScalarizationOverhead() [1/3]
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getScalarizationOverhead (VectorType * InTy, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const inline
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
Definition at line 950 of file BasicTTIImpl.h.
getScalarizationOverhead() [2/3]
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getScalarizationOverhead (VectorType * InTy, const APInt & DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind, bool ForPoisonSrc = true, ArrayRef< Value * > VL = {}) const inline override virtual
Estimate the overhead of scalarizing an instruction.
Insert and Extract are set if the demanded result elements need to be inserted and/or extracted from vectors.
FIXME: a bitfield is not a reasonable abstraction for talking about which elements are needed from a scalable vector
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::NVPTXTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 896 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getCastInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getOperandsScalarizationOverhead(), llvm::BasicTTIImplBase< BasicTTIImpl >::getOrderedReductionCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getScalarizationOverhead(), and llvm::BasicTTIImplBase< BasicTTIImpl >::getTypeBasedIntrinsicInstrCost().
getScalarizationOverhead() [3/3]
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getScalarizationOverhead (VectorType * RetTy, ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline
Estimate the overhead of scalarizing the inputs and outputs of an instruction, with return type RetTy and arguments Args of type Tys.
If Args are unknown (empty), then the cost associated with one argument is added as a heuristic.
Definition at line 986 of file BasicTTIImpl.h.
getScalingFactorCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, StackOffset BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 530 of file BasicTTIImpl.h.
getShuffleCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getShuffleCost (TTI::ShuffleKind Kind, VectorType * DstTy, VectorType * SrcTy, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType * SubTp, ArrayRef< const Value * > Args = {}, const Instruction * CxtI = nullptr) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 1175 of file BasicTTIImpl.h.
getStoreMinimumVF()
template<typename T> unsigned llvm::BasicTTIImplBase< T >::getStoreMinimumVF (unsigned VF, Type * ScalarMemTy, Type * ScalarValTy) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 483 of file BasicTTIImpl.h.
getTreeReductionCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getTreeReductionCost (unsigned Opcode, VectorType * Ty, TTI::TargetCostKind CostKind) const inline
Try to calculate arithmetic and shuffle op costs for reduction intrinsics.
We're assuming that reduction operation are performing the following way:
val1 = shufflevector<n x t> val, <n x t> undef, <n x i32> <i32 n/2, i32 n/2 + 1, ..., i32 n, i32 undef, ..., i32 undef> -------------—v----------—/ -------—v---------—/ n/2 elements n/2 elements red1 = op <n x t> val, <n x t> val1 After this operation we have a vector red1 where only the first n/2 elements are meaningful, the second n/2 elements are undefined and can be dropped. All other operations are actually working with the vector of length n/2, not n, though the real vector length is still n. val2 = shufflevector<n x t> red1, <n x t> undef, <n x i32> <i32 n/4, i32 n/4 + 1, ..., i32 n/2, i32 undef, ..., i32 undef> -------------—v----------—/ -------—v---------—/ n/4 elements 3*n/4 elements red2 = op <n x t> red1, <n x t> val2 - working with the vector of length n/2, the resulting vector has length n/4 etc.
The cost model should take into account that the actual length of the vector is reduced on each iteration.
Definition at line 3174 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getArithmeticReductionCost().
getTypeBasedIntrinsicInstrCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) const inline
Get intrinsic cost based on argument types.
If ScalarizationCostPassed is std::numeric_limits<unsigned>::max(), the cost of scalarizing the arguments and the return value will be computed based on types.
Definition at line 2225 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost().
getTypeLegalizationCost()
template<typename T> std::pair< InstructionCost, MVT > llvm::BasicTTIImplBase< T >::getTypeLegalizationCost (Type * Ty) const inline
Estimate the cost of type-legalization and the legalized type.
Definition at line 1005 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getCastInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getNumberOfParts(), and llvm::BasicTTIImplBase< BasicTTIImpl >::getTypeBasedIntrinsicInstrCost().
getUnrollingPreferences()
template<typename T> void llvm::BasicTTIImplBase< T >::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP, OptimizationRemarkEmitter * ORE) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::WebAssemblyTTIImpl.
Definition at line 710 of file BasicTTIImpl.h.
Referenced by llvm::ARMTTIImpl::getUnrollingPreferences(), and llvm::RISCVTTIImpl::getUnrollingPreferences().
getVectorInstrCost() [1/3]
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getVectorInstrCost (const Instruction & I, Type * Val, TTI::TargetCostKind CostKind, unsigned Index) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1451 of file BasicTTIImpl.h.
getVectorInstrCost() [2/3]
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, const Value * Op0, const Value * Op1) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1431 of file BasicTTIImpl.h.
Referenced by llvm::WebAssemblyTTIImpl::getVectorInstrCost().
getVectorInstrCost() [3/3]
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, Value * Scalar, ArrayRef< std::tuple< Value *, User *, int > > ScalarUserAndIdx) const inline override virtual
Parameters
ScalarUserAndIdx encodes the information about extracts from a vector with 'Scalar' being the value being extracted,'User' being the user of the extract(nullptr if user is not known before vectorization) and 'Idx' being the extract lane.
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, llvm::PPCTTIImpl, llvm::R600TTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 1442 of file BasicTTIImpl.h.
getVectorSplitCost()
template<typename T> InstructionCost llvm::BasicTTIImplBase< T >::getVectorSplitCost () const inline
Definition at line 3378 of file BasicTTIImpl.h.
getVScaleForTuning()
template<typename T> std::optional< unsigned > llvm::BasicTTIImplBase< T >::getVScaleForTuning () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 888 of file BasicTTIImpl.h.
hasBranchDivergence()
template<typename T> bool llvm::BasicTTIImplBase< T >::hasBranchDivergence (const Function * F = nullptr) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::HexagonTTIImpl, and llvm::NVPTXTTIImpl.
Definition at line 409 of file BasicTTIImpl.h.
haveFastSqrt()
template<typename T> bool llvm::BasicTTIImplBase< T >::haveFastSqrt (Type * Ty) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 661 of file BasicTTIImpl.h.
improveShuffleKindFromMask()
template<typename T> TTI::ShuffleKind llvm::BasicTTIImplBase< T >::improveShuffleKindFromMask (TTI::ShuffleKind Kind, ArrayRef< int > Mask, VectorType * SrcTy, int & Index, VectorType *& SubTy) const inline
Definition at line 1119 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::improveShuffleKindFromMask().
instCombineIntrinsic()
template<typename T> std::optional< Instruction * > llvm::BasicTTIImplBase< T >::instCombineIntrinsic (InstCombiner & IC, IntrinsicInst & II) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, llvm::WebAssemblyTTIImpl, and llvm::X86TTIImpl.
Definition at line 810 of file BasicTTIImpl.h.
isFCmpOrdCheaperThanFCmpZero()
template<typename T> bool llvm::BasicTTIImplBase< T >::isFCmpOrdCheaperThanFCmpZero (Type * Ty) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 668 of file BasicTTIImpl.h.
isHardwareLoopProfitable()
template<typename T> bool llvm::BasicTTIImplBase< T >::isHardwareLoopProfitable (Loop * L, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * LibInfo, HardwareLoopInfo & HWLoopInfo) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::PPCTTIImpl.
Definition at line 790 of file BasicTTIImpl.h.
isIndexedLoadLegal()
template<typename T> bool llvm::BasicTTIImplBase< T >::isIndexedLoadLegal (TTI::MemIndexedMode M, Type * Ty) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 503 of file BasicTTIImpl.h.
isIndexedStoreLegal()
template<typename T> bool llvm::BasicTTIImplBase< T >::isIndexedStoreLegal (TTI::MemIndexedMode M, Type * Ty) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 508 of file BasicTTIImpl.h.
isLegalAddImmediate()
template<typename T> bool llvm::BasicTTIImplBase< T >::isLegalAddImmediate (int64_t imm) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 454 of file BasicTTIImpl.h.
isLegalAddressingMode()
template<typename T> bool llvm::BasicTTIImplBase< T >::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction * I = nullptr, int64_t ScalableOffset = 0) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 466 of file BasicTTIImpl.h.
Referenced by llvm::BasicTTIImplBase< BasicTTIImpl >::getScalingFactorCost().
isLegalAddScalableImmediate()
template<typename T> bool llvm::BasicTTIImplBase< T >::isLegalAddScalableImmediate (int64_t Imm) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 458 of file BasicTTIImpl.h.
isLegalICmpImmediate()
template<typename T> bool llvm::BasicTTIImplBase< T >::isLegalICmpImmediate (int64_t imm) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 462 of file BasicTTIImpl.h.
isLSRCostLess()
template<typename T> bool llvm::BasicTTIImplBase< T >::isLSRCostLess (const TTI::LSRCost & C1, const TTI::LSRCost & C2) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::MipsTTIImpl, llvm::PPCTTIImpl, llvm::RISCVTTIImpl, llvm::SystemZTTIImpl, and llvm::X86TTIImpl.
Definition at line 513 of file BasicTTIImpl.h.
isNoopAddrSpaceCast()
template<typename T> bool llvm::BasicTTIImplBase< T >::isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 431 of file BasicTTIImpl.h.
isNumRegsMajorCostOfLSR()
template<typename T> bool llvm::BasicTTIImplBase< T >::isNumRegsMajorCostOfLSR () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::PPCTTIImpl.
Definition at line 518 of file BasicTTIImpl.h.
isProfitableLSRChainElement()
template<typename T> bool llvm::BasicTTIImplBase< T >::isProfitableLSRChainElement (Instruction * I) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 526 of file BasicTTIImpl.h.
isProfitableToHoist()
template<typename T> bool llvm::BasicTTIImplBase< T >::isProfitableToHoist (Instruction * I) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 549 of file BasicTTIImpl.h.
isSingleThreaded()
template<typename T> bool llvm::BasicTTIImplBase< T >::isSingleThreaded () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 439 of file BasicTTIImpl.h.
isTargetIntrinsicTriviallyScalarizable()
template<typename T> bool llvm::BasicTTIImplBase< T >::isTargetIntrinsicTriviallyScalarizable (Intrinsic::ID ID) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::DirectXTTIImpl.
Definition at line 928 of file BasicTTIImpl.h.
isTargetIntrinsicWithOverloadTypeAtArg()
template<typename T> bool llvm::BasicTTIImplBase< T >::isTargetIntrinsicWithOverloadTypeAtArg (Intrinsic::ID ID, int OpdIdx) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::DirectXTTIImpl.
Definition at line 938 of file BasicTTIImpl.h.
isTargetIntrinsicWithScalarOpAtArg()
template<typename T> bool llvm::BasicTTIImplBase< T >::isTargetIntrinsicWithScalarOpAtArg (Intrinsic::ID ID, unsigned ScalarOpdIdx) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::DirectXTTIImpl.
Definition at line 933 of file BasicTTIImpl.h.
isTargetIntrinsicWithStructReturnOverloadAtField()
template<typename T> bool llvm::BasicTTIImplBase< T >::isTargetIntrinsicWithStructReturnOverloadAtField (Intrinsic::ID ID, int RetIdx) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 944 of file BasicTTIImpl.h.
isTruncateFree()
template<typename T> bool llvm::BasicTTIImplBase< T >::isTruncateFree (Type * Ty1, Type * Ty2) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 545 of file BasicTTIImpl.h.
isTypeLegal()
template<typename T> bool llvm::BasicTTIImplBase< T >::isTypeLegal (Type * Ty) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 555 of file BasicTTIImpl.h.
isValidAddrSpaceCast()
template<typename T> bool llvm::BasicTTIImplBase< T >::isValidAddrSpaceCast (unsigned FromAS, unsigned ToAS) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl.
Definition at line 413 of file BasicTTIImpl.h.
isVScaleKnownToBeAPowerOfTwo()
template<typename T> bool llvm::BasicTTIImplBase< T >::isVScaleKnownToBeAPowerOfTwo () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 891 of file BasicTTIImpl.h.
preferPredicateOverEpilogue()
template<typename T> bool llvm::BasicTTIImplBase< T >::preferPredicateOverEpilogue (TailFoldingInfo * TFI) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::RISCVTTIImpl.
Definition at line 800 of file BasicTTIImpl.h.
preferToKeepConstantsAttached()
template<typename T> bool llvm::BasicTTIImplBase< T >::preferToKeepConstantsAttached (const Instruction & Inst, const Function & Fn) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 680 of file BasicTTIImpl.h.
rewriteIntrinsicWithAddressSpace()
template<typename T> Value * llvm::BasicTTIImplBase< T >::rewriteIntrinsicWithAddressSpace (IntrinsicInst * II, Value * OldV, Value * NewV) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, llvm::NVPTXTTIImpl, and llvm::SPIRVTTIImpl.
Definition at line 449 of file BasicTTIImpl.h.
shouldBuildLookupTables()
template<typename T> bool llvm::BasicTTIImplBase< T >::shouldBuildLookupTables () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::HexagonTTIImpl, and llvm::LanaiTTIImpl.
Definition at line 630 of file BasicTTIImpl.h.
shouldBuildRelLookupTables()
template<typename T> bool llvm::BasicTTIImplBase< T >::shouldBuildRelLookupTables () const inline override virtual
Relative lookup table entries consist of 32-bit offsets. Do not generate relative lookup tables for large code models in 64-bit achitectures where 32-bit offsets might not be enough.
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::NVPTXTTIImpl, llvm::PPCTTIImpl, and llvm::VETTIImpl.
Definition at line 636 of file BasicTTIImpl.h.
shouldDropLSRSolutionIfLessProfitable()
template<typename T> bool llvm::BasicTTIImplBase< T >::shouldDropLSRSolutionIfLessProfitable () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 522 of file BasicTTIImpl.h.
shouldPrefetchAddressSpace()
template<typename T> bool llvm::BasicTTIImplBase< T >::shouldPrefetchAddressSpace (unsigned AS) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl.
Definition at line 873 of file BasicTTIImpl.h.
simplifyDemandedUseBitsIntrinsic()
template<typename T> std::optional< Value * > llvm::BasicTTIImplBase< T >::simplifyDemandedUseBitsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedMask, KnownBits & Known, bool & KnownBitsComputed) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::X86TTIImpl.
Definition at line 815 of file BasicTTIImpl.h.
simplifyDemandedVectorEltsIntrinsic()
template<typename T> std::optional< Value * > llvm::BasicTTIImplBase< T >::simplifyDemandedVectorEltsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, APInt & UndefElts, APInt & UndefElts2, APInt & UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Reimplemented in llvm::GCNTTIImpl, and llvm::X86TTIImpl.
Definition at line 822 of file BasicTTIImpl.h.
useAA()
template<typename T> bool llvm::BasicTTIImplBase< T >::useAA () const inline override virtual
Reimplemented from llvm::TargetTransformInfoImplBase.
Definition at line 553 of file BasicTTIImpl.h.
Member Data Documentation
DL
template<typename T> const DataLayout& llvm::TargetTransformInfoImplBase::DL protected
Definition at line 39 of file TargetTransformInfoImpl.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/BasicTTIImpl.h