LLVM: llvm::orc::EPCIndirectionUtils Class Reference
llvm::orc::EPCIndirectionUtils Class Reference
Provides ExecutorProcessControl based indirect stubs, trampoline pool and lazy call through manager.
#include "llvm/ExecutionEngine/Orc/EPCIndirectionUtils.h"
Classes
class ABISupport
ABI support base class.
Public Member Functions
ExecutorProcessControl & getExecutorProcessControl () const
Return a reference to the ExecutorProcessControl object.
ABISupport & getABISupport () const
Return a reference to the ABISupport object for this instance.
LLVM_ABI Error cleanup ()
Release memory for resources held by this instance.
LLVM_ABI Expected< ExecutorAddr > writeResolverBlock (ExecutorAddr ReentryFnAddr, ExecutorAddr ReentryCtxAddr)
Write resolver code to the executor process and return its address.
ExecutorAddr getResolverBlockAddress () const
Returns the address of the Resolver block.
LLVM_ABI std::unique_ptr< IndirectStubsManager > createIndirectStubsManager ()
Create an IndirectStubsManager for the executor process.
LLVM_ABI TrampolinePool & getTrampolinePool ()
Create a TrampolinePool for the executor process.
LLVM_ABI LazyCallThroughManager & createLazyCallThroughManager (ExecutionSession &ES, ExecutorAddr ErrorHandlerAddr)
Create a LazyCallThroughManager.
LazyCallThroughManager & getLazyCallThroughManager ()
Create a LazyCallThroughManager for the executor process.
Static Public Member Functions
template<typename ORCABI>
static std::unique_ptr< EPCIndirectionUtils > CreateWithABI (ExecutorProcessControl &EPC)
Create using the given ABI class.
static LLVM_ABI Expected< std::unique_ptr< EPCIndirectionUtils > > Create (ExecutorProcessControl &EPC)
Create based on the ExecutorProcessControl triple.
static Expected< std::unique_ptr< EPCIndirectionUtils > > Create (ExecutionSession &ES)
Create based on the ExecutorProcessControl triple.
Friends
class EPCIndirectionUtilsAccess
Detailed Description
Provides ExecutorProcessControl based indirect stubs, trampoline pool and lazy call through manager.
Definition at line 31 of file EPCIndirectionUtils.h.
Member Function Documentation
cleanup()
Error llvm::orc::EPCIndirectionUtils::cleanup ()
Release memory for resources held by this instance.
This must be called prior to destruction of the class.
Definition at line 273 of file EPCIndirectionUtils.cpp.
References llvm::joinErrors().
Create() [1/2]
Expected< std::unique_ptr< EPCIndirectionUtils > > llvm::orc::EPCIndirectionUtils::Create (ExecutionSession & ES) inline static
Create based on the ExecutorProcessControl triple.
Definition at line 90 of file EPCIndirectionUtils.h.
References Create(), and llvm::orc::ExecutionSession::getExecutorProcessControl().
Create() [2/2]
Expected< std::unique_ptr< EPCIndirectionUtils > > llvm::orc::EPCIndirectionUtils::Create (ExecutorProcessControl & EPC) static
Create based on the ExecutorProcessControl triple.
Definition at line 235 of file EPCIndirectionUtils.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, CreateWithABI(), llvm::inconvertibleErrorCode(), llvm::Triple::loongarch64, llvm::make_error(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::riscv64, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by Create().
createIndirectStubsManager()
std::unique_ptr< IndirectStubsManager > llvm::orc::EPCIndirectionUtils::createIndirectStubsManager ()
Create an IndirectStubsManager for the executor process.
Definition at line 320 of file EPCIndirectionUtils.cpp.
createLazyCallThroughManager()
LazyCallThroughManager & llvm::orc::EPCIndirectionUtils::createLazyCallThroughManager (ExecutionSession & ES, ExecutorAddr ErrorHandlerAddr)
Create a LazyCallThroughManager.
This function should only be called once.
Definition at line 330 of file EPCIndirectionUtils.cpp.
References assert(), and getTrampolinePool().
CreateWithABI()
template<typename ORCABI> std::unique_ptr< EPCIndirectionUtils > llvm::orc::EPCIndirectionUtils::CreateWithABI (ExecutorProcessControl & EPC) static
Create using the given ABI class.
Definition at line 217 of file EPCIndirectionUtils.h.
Referenced by Create().
getABISupport()
ABISupport & llvm::orc::EPCIndirectionUtils::getABISupport () const inline
Return a reference to the ABISupport object for this instance.
Definition at line 98 of file EPCIndirectionUtils.h.
getExecutorProcessControl()
ExecutorProcessControl & llvm::orc::EPCIndirectionUtils::getExecutorProcessControl () const inline
Return a reference to the ExecutorProcessControl object.
Definition at line 95 of file EPCIndirectionUtils.h.
getLazyCallThroughManager()
LazyCallThroughManager & llvm::orc::EPCIndirectionUtils::getLazyCallThroughManager () inline
Create a LazyCallThroughManager for the executor process.
Definition at line 127 of file EPCIndirectionUtils.h.
References assert().
Referenced by llvm::orc::setUpInProcessLCTMReentryViaEPCIU().
getResolverBlockAddress()
ExecutorAddr llvm::orc::EPCIndirectionUtils::getResolverBlockAddress () const inline
Returns the address of the Resolver block.
Returns zero if the writeResolverBlock method has not previously been called.
Definition at line 112 of file EPCIndirectionUtils.h.
getTrampolinePool()
TrampolinePool & llvm::orc::EPCIndirectionUtils::getTrampolinePool ()
Create a TrampolinePool for the executor process.
Definition at line 324 of file EPCIndirectionUtils.cpp.
Referenced by createLazyCallThroughManager().
writeResolverBlock()
Expected< ExecutorAddr > llvm::orc::EPCIndirectionUtils::writeResolverBlock (ExecutorAddr ReentryFnAddr, ExecutorAddr ReentryCtxAddr)
Write resolver code to the executor process and return its address.
This must be called before any call to createTrampolinePool or createLazyCallThroughManager.
Definition at line 290 of file EPCIndirectionUtils.cpp.
References assert().
Referenced by llvm::orc::setUpInProcessLCTMReentryViaEPCIU().
Friends And Related Symbol Documentation
EPCIndirectionUtilsAccess
friend class EPCIndirectionUtilsAccess friend
Definition at line 32 of file EPCIndirectionUtils.h.
References EPCIndirectionUtilsAccess.
Referenced by EPCIndirectionUtilsAccess.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/EPCIndirectionUtils.h
lib/ExecutionEngine/Orc/EPCIndirectionUtils.cpp