LLVM: llvm::VPlanSlp Class Reference
llvm::VPlanSlp Class Reference
Class that maps (parts of) an existing VPlan to trees of combined VPInstructions.
#include "Transforms/Vectorize/VPlanSLP.h"
Public Member Functions
VPlanSlp (VPInterleavedAccessInfo &IAI, VPBasicBlock &BB)
~VPlanSlp ()=default
LLVM_ABI_FOR_TEST VPInstruction * buildGraph (ArrayRef< VPValue * > Operands)
Tries to build an SLP tree rooted at Operands and returns a VPInstruction combining Operands, if they can be combined.
unsigned getWidestBundleBits () const
Return the width of the widest combined bundle in bits.
bool isCompletelySLP () const
Return true if all visited instruction can be combined.
Detailed Description
Class that maps (parts of) an existing VPlan to trees of combined VPInstructions.
Definition at line 74 of file VPlanSLP.h.
Constructor & Destructor Documentation
VPlanSlp()
llvm::VPlanSlp::VPlanSlp (VPInterleavedAccessInfo & IAI, VPBasicBlock & BB) inline
Definition at line 129 of file VPlanSLP.h.
~VPlanSlp()
llvm::VPlanSlp::~VPlanSlp () default
References LLVM_ABI_FOR_TEST.
Member Function Documentation
buildGraph()
VPInstruction * VPlanSlp::buildGraph (ArrayRef< VPValue * > Operands)
Tries to build an SLP tree rooted at Operands and returns a VPInstruction combining Operands, if they can be combined.
Definition at line 415 of file VPlanSLP.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, areCommutative(), assert(), llvm::VPInstruction::Broadcast, buildGraph(), llvm::cast(), llvm::dbgs(), llvm::ArrayRef< T >::empty(), getOpcode(), getOperands(), I, LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::VPInstruction::SLPLoad, llvm::VPInstruction::SLPStore, and llvm::to_vector().
Referenced by buildGraph().
getWidestBundleBits()
unsigned llvm::VPlanSlp::getWidestBundleBits () const inline
Return the width of the widest combined bundle in bits.
Definition at line 138 of file VPlanSLP.h.
isCompletelySLP()
bool llvm::VPlanSlp::isCompletelySLP () const inline
Return true if all visited instruction can be combined.
Definition at line 141 of file VPlanSLP.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanSLP.h
lib/Transforms/Vectorize/VPlanSLP.cpp