LLVM: llvm::xray::TraceExpander Class Reference
llvm::xray::TraceExpander Class Reference
#include "llvm/XRay/FDRTraceExpander.h"
Public Member Functions
TraceExpander (function_ref< void(const XRayRecord &)> F, uint16_t L)
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Error flush ()
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
Definition at line 22 of file FDRTraceExpander.h.
Constructor & Destructor Documentation
TraceExpander()
llvm::xray::TraceExpander::TraceExpander (function_ref< void(const XRayRecord &)> F, uint16_t L) inline explicit
Definition at line 37 of file FDRTraceExpander.h.
References F, and llvm::move().
Member Function Documentation
flush()
Error TraceExpander::flush ()
Definition at line 125 of file FDRTraceExpander.cpp.
References llvm::Error::success().
Referenced by loadFDRLog().
visit() [1/12]
Error TraceExpander::visit (BufferExtents &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 21 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [2/12]
Error TraceExpander::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 84 of file FDRTraceExpander.cpp.
References llvm::xray::ENTER_ARG, and llvm::Error::success().
visit() [3/12]
Error TraceExpander::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 39 of file FDRTraceExpander.cpp.
References llvm::xray::CUSTOM_EVENT, and llvm::Error::success().
visit() [4/12]
Error TraceExpander::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 53 of file FDRTraceExpander.cpp.
References llvm::xray::CUSTOM_EVENT, and llvm::Error::success().
visit() [5/12]
Error TraceExpander::visit (EndBufferRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 104 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [6/12]
Error TraceExpander::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 110 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [7/12]
Error TraceExpander::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 95 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [8/12]
Error TraceExpander::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 28 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [9/12]
Error TraceExpander::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 90 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [10/12]
Error TraceExpander::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 34 of file FDRTraceExpander.cpp.
References llvm::Error::success().
visit() [11/12]
Error TraceExpander::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 68 of file FDRTraceExpander.cpp.
References llvm::Error::success(), and llvm::xray::TYPED_EVENT.
visit() [12/12]
Error TraceExpander::visit (WallclockRecord &) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 26 of file FDRTraceExpander.cpp.
References llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRTraceExpander.h
lib/XRay/FDRTraceExpander.cpp