LLVM: llvm::orc::DylibPathValidator Class Reference
llvm::orc::DylibPathValidator Class Reference
Validates and normalizes dynamic library paths.
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h"
Public Member Functions
DylibPathValidator (PathResolver &PR, LibraryPathCache &LC, ObjFileCache *ObjCache=nullptr)
bool isSharedLibrary (StringRef Path) const
bool isSharedLibraryCached (StringRef Path) const
std::optional< std::string > normalize (StringRef Path) const
std::optional< std::string > validate (StringRef Path) const
Validate the given path as a shared library.
Detailed Description
Validates and normalizes dynamic library paths.
Uses a PathResolver to resolve paths to their canonical form and checks whether they point to valid shared libraries.
Definition at line 262 of file LibraryScanner.h.
Constructor & Destructor Documentation
DylibPathValidator()
llvm::orc::DylibPathValidator::DylibPathValidator (PathResolver & PR, LibraryPathCache & LC, ObjFileCache * ObjCache = nullptr) inline
Definition at line 264 of file LibraryScanner.h.
Member Function Documentation
isSharedLibrary()
bool llvm::orc::DylibPathValidator::isSharedLibrary (StringRef Path) const
Definition at line 213 of file LibraryScanner.cpp.
References llvm::file_magic::archive, llvm::consumeError(), llvm::dbgs(), llvm::file_magic::elf_shared_object, llvm::sys::fs::get_file_type(), llvm::orc::ObjectFileLoader::getObjectFile(), llvm::identify_magic(), llvm::orc::isSharedLibraryObject(), LLVM_DEBUG, llvm::file_magic::macho_dynamically_linked_shared_lib, llvm::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::file_magic::macho_universal_binary, llvm::file_magic::pecoff_executable, and llvm::sys::fs::regular_file.
Referenced by isSharedLibraryCached().
isSharedLibraryCached()
bool llvm::orc::DylibPathValidator::isSharedLibraryCached (StringRef Path) const inline
Definition at line 269 of file LibraryScanner.h.
References isSharedLibrary().
Referenced by validate().
normalize()
std::optional< std::string > llvm::orc::DylibPathValidator::normalize (StringRef Path) const inline
Definition at line 275 of file LibraryScanner.h.
Referenced by validate().
validate()
std::optional< std::string > llvm::orc::DylibPathValidator::validate (StringRef Path) const inline
Validate the given path as a shared library.
Definition at line 285 of file LibraryScanner.h.
References isSharedLibraryCached(), and normalize().
Referenced by llvm::orc::SearchPathResolver::resolve().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryScanner.cpp