LLVM: llvm::StringToOffsetTable Class Reference
llvm::StringToOffsetTable Class Reference
StringToOffsetTable - This class uniques a bunch of nul-terminated strings and keeps track of their offset in a massive contiguous string allocation.
#include "llvm/TableGen/StringToOffsetTable.h"
Public Member Functions
StringToOffsetTable (bool AppendZero=true, StringRef ClassPrefix="", bool UsePrefixForStorageMember=true)
bool empty () const
size_t size () const
unsigned GetOrAddStringOffset (StringRef Str)
std::optional< unsigned > GetStringOffset (StringRef Str) const
void EmitStringTableDef (raw_ostream &OS, const Twine &Name) const
void EmitString (raw_ostream &O) const
Detailed Description
StringToOffsetTable - This class uniques a bunch of nul-terminated strings and keeps track of their offset in a massive contiguous string allocation.
It can then output this string blob and use indexes into the string to reference each piece.
Definition at line 23 of file StringToOffsetTable.h.
Constructor & Destructor Documentation
StringToOffsetTable()
llvm::StringToOffsetTable::StringToOffsetTable (bool AppendZero = true, StringRef ClassPrefix = "", bool UsePrefixForStorageMember = true) inline
Definition at line 34 of file StringToOffsetTable.h.
References GetOrAddStringOffset().
Member Function Documentation
EmitString()
void StringToOffsetTable::EmitString (raw_ostream & O) const
Definition at line 82 of file StringToOffsetTable.cpp.
EmitStringTableDef()
void StringToOffsetTable::EmitStringTableDef (raw_ostream & OS, const Twine & Name) const
Definition at line 29 of file StringToOffsetTable.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::CallingConv::C, llvm::EmitLongStrLiterals, llvm::formatv(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::PrintFatalError(), and llvm::raw_ostream::write_escaped().
empty()
bool llvm::StringToOffsetTable::empty () const inline
Definition at line 43 of file StringToOffsetTable.h.
GetOrAddStringOffset()
unsigned StringToOffsetTable::GetOrAddStringOffset (StringRef Str)
Definition at line 17 of file StringToOffsetTable.cpp.
References II, and size().
Referenced by StringToOffsetTable().
GetStringOffset()
std::optional< unsigned > llvm::StringToOffsetTable::GetStringOffset (StringRef Str) const inline
Definition at line 50 of file StringToOffsetTable.h.
References II.
size()
size_t llvm::StringToOffsetTable::size () const inline
Definition at line 44 of file StringToOffsetTable.h.
Referenced by GetOrAddStringOffset().
The documentation for this class was generated from the following files:
include/llvm/TableGen/StringToOffsetTable.h
lib/TableGen/StringToOffsetTable.cpp