LLVM: llvm::sandboxir::CallBase Class Reference
llvm::sandboxir::CallBase Class Reference
#include "llvm/SandboxIR/Instruction.h"
Public Member Functions
LLVM_ABI FunctionType * getFunctionType () const
op_iterator data_operands_begin ()
const_op_iterator data_operands_begin () const
op_iterator data_operands_end ()
const_op_iterator data_operands_end () const
iterator_range< op_iterator > data_ops ()
iterator_range< const_op_iterator > data_ops () const
bool data_operands_empty () const
unsigned data_operands_size () const
bool isDataOperand (Use U) const
unsigned getDataOperandNo (Use U) const
unsigned getNumTotalBundleOperands () const
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
op_iterator arg_begin ()
const_op_iterator arg_begin () const
op_iterator arg_end ()
const_op_iterator arg_end () const
iterator_range< op_iterator > args ()
iterator_range< const_op_iterator > args () const
bool arg_empty () const
unsigned arg_size () const
Value * getArgOperand (unsigned OpIdx) const
void setArgOperand (unsigned OpIdx, Value *NewOp)
Use getArgOperandUse (unsigned Idx) const
Use getArgOperandUse (unsigned Idx)
bool isArgOperand (Use U) const
unsigned getArgOperandNo (Use U) const
bool hasArgument (const Value *V) const
LLVM_ABI Value * getCalledOperand () const
LLVM_ABI Use getCalledOperandUse () const
LLVM_ABI Function * getCalledFunction () const
bool isIndirectCall () const
bool isCallee (Use U) const
LLVM_ABI Function * getCaller ()
const Function * getCaller () const
bool isMustTailCall () const
bool isTailCall () const
Intrinsic::ID getIntrinsicID () const
void setCalledOperand (Value *V)
LLVM_ABI void setCalledFunction (Function *F)
CallingConv::ID getCallingConv () const
bool isInlineAsm () const
Public Member Functions inherited from llvm::sandboxir::SingleLLVMInstructionImpl< llvm::CallBase >
unsigned getUseOperandNo (const Use &Use) const final
\Returns the operand index of Use.
unsigned getNumOfIRInstrs () const final
This is used by BasicBlock::iterator.
void verify () const final
Should crash if there is something wrong with the instruction.
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Instruction
LLVM_ABI BBIterator getIterator () const
\Returns a BasicBlock::iterator for this Instruction.
LLVM_ABI Instruction * getNextNode () const
\Returns the next sandboxir::Instruction in the block, or nullptr if at the end of the block.
LLVM_ABI Instruction * getPrevNode () const
\Returns the previous sandboxir::Instruction in the block, or nullptr if at the beginning of the block.
Opcode getOpcode () const
\Returns this Instruction's opcode.
const char * getOpcodeName () const
const DataLayout & getDataLayout () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isSpecialTerminator () const
bool isOnlyUserOfAnyOperand () const
bool isLogicalShift () const
bool hasMetadata () const
Return true if the instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
LLVM_ABI void removeFromParent ()
Detach this from its parent BasicBlock without deleting it.
LLVM_ABI void eraseFromParent ()
Detach this Value from its parent and delete it.
LLVM_ABI void insertBefore (Instruction *BeforeI)
Insert this detached instruction before BeforeI.
LLVM_ABI void insertAfter (Instruction *AfterI)
Insert this detached instruction after AfterI.
LLVM_ABI void insertInto (BasicBlock *BB, const BBIterator &WhereIt)
Insert this detached instruction into BB at WhereIt.
LLVM_ABI void moveBefore (BasicBlock &BB, const BBIterator &WhereIt)
Move this instruction to WhereIt.
void moveBefore (Instruction *Before)
Move this instruction before Before.
void moveAfter (Instruction *After)
Move this instruction after After.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
LLVM_ABI BasicBlock * getParent () const
\Returns the BasicBlock containing this Instruction, or null if it is detached.
bool hasNoUnsignedWrap () const
Determine whether the no signed wrap flag is set.
LLVM_ABI void setHasNoUnsignedWrap (bool B=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
bool hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
LLVM_ABI void setHasNoSignedWrap (bool B=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
bool isFast () const
Determine whether all fast-math-flags are set.
LLVM_ABI void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
bool hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
LLVM_ABI void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
bool isExact () const
Determine whether the exact flag is set.
LLVM_ABI void setIsExact (bool B=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
LLVM_ABI void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
LLVM_ABI void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
LLVM_ABI void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
LLVM_ABI void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
bool hasAllowContract () const
Determine whether the allow-contract flag is set.
LLVM_ABI void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
bool hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
LLVM_ABI void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
LLVM_ABI void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool isAtomic () const
bool hasAtomicLoad () const
bool hasAtomicStore () const
bool isVolatile () const
LLVM_ABI Type * getAccessType () const
bool mayThrow (bool IncludePhaseOneUnwind=false) const
bool isFenceLike () const
bool mayHaveSideEffects () const
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dumpOS (raw_ostream &OS) const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
LLVM_ABI use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
LLVM_ABI user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
LLVM_ABI unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
LLVM_ABI Type * getType () const
Context & getContext () const
LLVM_ABI void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
LLVM_ABI void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Value *From)
Static Public Member Functions inherited from llvm::sandboxir::Instruction
static LLVM_ABI const char * getOpcodeName (Opcode Opc)
static LLVM_ABI bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Friends
class CallInst
class InvokeInst
class CallBrInst
Additional Inherited Members
Public Types inherited from llvm::sandboxir::Instruction
enum class Opcode
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Protected Member Functions inherited from llvm::sandboxir::Instruction
Instruction (ClassID ID, Opcode Opc, llvm::Instruction *I, sandboxir::Context &SBCtx)
LLVM_ABI llvm::Instruction * getTopmostLLVMInstruction () const
A SandboxIR Instruction may map to multiple LLVM IR Instruction.
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void swapOperandsInternal (unsigned OpIdxA, unsigned OpIdxB)
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
LLVM_ABI Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Value (const Value &)=delete
Disable copies.
Value & operator= (const Value &)=delete
Static Protected Member Functions inherited from llvm::sandboxir::Instruction
static IRBuilder & setInsertPos (InsertPosition Pos)
Helper function for create().
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Instruction
Opcode Opc
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 1297 of file Instruction.h.
Member Function Documentation
arg_begin() [1/2]
op_iterator llvm::sandboxir::CallBase::arg_begin () inline
Definition at line 1356 of file Instruction.h.
References llvm::sandboxir::User::op_begin().
Referenced by arg_empty(), arg_size(), args(), and args().
arg_begin() [2/2]
const_op_iterator llvm::sandboxir::CallBase::arg_begin () const inline
Definition at line 1357 of file Instruction.h.
References llvm::sandboxir::User::op_begin().
arg_empty()
bool llvm::sandboxir::CallBase::arg_empty () const inline
Definition at line 1370 of file Instruction.h.
References arg_begin(), and arg_end().
arg_end() [1/2]
op_iterator llvm::sandboxir::CallBase::arg_end () inline
Definition at line 1358 of file Instruction.h.
References data_operands_end(), and getNumTotalBundleOperands().
Referenced by arg_empty(), arg_end(), arg_size(), args(), and args().
arg_end() [2/2]
const_op_iterator llvm::sandboxir::CallBase::arg_end () const inline
Definition at line 1361 of file Instruction.h.
References arg_end().
arg_size()
unsigned llvm::sandboxir::CallBase::arg_size () const inline
Definition at line 1371 of file Instruction.h.
References arg_begin(), and arg_end().
Referenced by getArgOperand(), getArgOperandUse(), getArgOperandUse(), and setArgOperand().
args() [1/2]
iterator_range< op_iterator > llvm::sandboxir::CallBase::args () inline
Definition at line 1364 of file Instruction.h.
References arg_begin(), arg_end(), and llvm::make_range().
Referenced by hasArgument().
args() [2/2]
iterator_range< const_op_iterator > llvm::sandboxir::CallBase::args () const inline
Definition at line 1367 of file Instruction.h.
References arg_begin(), arg_end(), and llvm::make_range().
classof()
bool llvm::sandboxir::CallBase::classof (const Value * From) inline static
Definition at line 1305 of file Instruction.h.
References llvm::sandboxir::Value::getSubclassID(), and llvm::sandboxir::Instruction::Opc.
data_operands_begin() [1/2]
op_iterator llvm::sandboxir::CallBase::data_operands_begin () inline
Definition at line 1314 of file Instruction.h.
References llvm::sandboxir::User::op_begin().
Referenced by data_operands_begin(), data_operands_empty(), data_operands_size(), data_ops(), and data_ops().
data_operands_begin() [2/2]
const_op_iterator llvm::sandboxir::CallBase::data_operands_begin () const inline
Definition at line 1315 of file Instruction.h.
References data_operands_begin().
data_operands_empty()
bool llvm::sandboxir::CallBase::data_operands_empty () const inline
Definition at line 1334 of file Instruction.h.
References data_operands_begin(), and data_operands_end().
data_operands_end() [1/2]
op_iterator llvm::sandboxir::CallBase::data_operands_end () inline
Definition at line 1318 of file Instruction.h.
References llvm::cast(), llvm::sandboxir::User::op_begin(), and llvm::sandboxir::Value::Val.
Referenced by arg_end(), data_operands_empty(), data_operands_size(), data_ops(), and data_ops().
data_operands_end() [2/2]
const_op_iterator llvm::sandboxir::CallBase::data_operands_end () const inline
Definition at line 1323 of file Instruction.h.
References llvm::cast(), llvm::sandboxir::User::op_begin(), and llvm::sandboxir::Value::Val.
data_operands_size()
unsigned llvm::sandboxir::CallBase::data_operands_size () const inline
Definition at line 1337 of file Instruction.h.
References data_operands_begin(), and data_operands_end().
data_ops() [1/2]
iterator_range< op_iterator > llvm::sandboxir::CallBase::data_ops () inline
Definition at line 1328 of file Instruction.h.
References data_operands_begin(), data_operands_end(), and llvm::make_range().
data_ops() [2/2]
iterator_range< const_op_iterator > llvm::sandboxir::CallBase::data_ops () const inline
Definition at line 1331 of file Instruction.h.
References data_operands_begin(), data_operands_end(), and llvm::make_range().
getArgOperand()
Value * llvm::sandboxir::CallBase::getArgOperand (unsigned OpIdx) const inline
Definition at line 1373 of file Instruction.h.
References arg_size(), assert(), llvm::sandboxir::getOperand(), and OpIdx.
getArgOperandNo()
unsigned llvm::sandboxir::CallBase::getArgOperandNo (Use U) const inline
Definition at line 1394 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getArgOperandUse() [1/2]
Use llvm::sandboxir::CallBase::getArgOperandUse (unsigned Idx) inline
Definition at line 1386 of file Instruction.h.
References arg_size(), assert(), and llvm::sandboxir::User::getOperandUse().
getArgOperandUse() [2/2]
Use llvm::sandboxir::CallBase::getArgOperandUse (unsigned Idx) const inline
Definition at line 1382 of file Instruction.h.
References arg_size(), assert(), and llvm::sandboxir::User::getOperandUse().
getCalledFunction()
Function * llvm::sandboxir::CallBase::getCalledFunction () const
Definition at line 494 of file Instruction.cpp.
References llvm::cast(), llvm::cast_or_null(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
getCalledOperand()
Value * llvm::sandboxir::CallBase::getCalledOperand () const
Definition at line 485 of file Instruction.cpp.
getCalledOperandUse()
Use llvm::sandboxir::CallBase::getCalledOperandUse () const
Definition at line 489 of file Instruction.cpp.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by setCalledOperand().
getCaller() [1/2]
Function * llvm::sandboxir::CallBase::getCaller ()
Definition at line 498 of file Instruction.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
Referenced by getCaller().
getCaller() [2/2]
const Function * llvm::sandboxir::CallBase::getCaller () const inline
Definition at line 1410 of file Instruction.h.
References getCaller().
getCallingConv()
CallingConv::ID llvm::sandboxir::CallBase::getCallingConv () const inline
Definition at line 1422 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getDataOperandNo()
unsigned llvm::sandboxir::CallBase::getDataOperandNo (Use U) const inline
Definition at line 1345 of file Instruction.h.
References assert(), llvm::cast(), isDataOperand(), and llvm::sandboxir::Value::Val.
getFunctionType()
FunctionType * llvm::sandboxir::CallBase::getFunctionType () const
Definition at line 480 of file Instruction.cpp.
References llvm::cast(), llvm::sandboxir::Value::Ctx, and llvm::sandboxir::Value::Val.
getIntrinsicID()
Intrinsic::ID llvm::sandboxir::CallBase::getIntrinsicID () const inline
Definition at line 1417 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
getNumTotalBundleOperands()
unsigned llvm::sandboxir::CallBase::getNumTotalBundleOperands () const inline
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
Definition at line 1352 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by arg_end().
hasArgument()
bool llvm::sandboxir::CallBase::hasArgument (const Value * V) const inline
Definition at line 1397 of file Instruction.h.
References args(), and llvm::is_contained().
isArgOperand()
bool llvm::sandboxir::CallBase::isArgOperand (Use U) const inline
Definition at line 1391 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isCallee()
bool llvm::sandboxir::CallBase::isCallee (Use U) const inline
Definition at line 1406 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isDataOperand()
bool llvm::sandboxir::CallBase::isDataOperand (Use U) const inline
Definition at line 1340 of file Instruction.h.
References assert(), llvm::cast(), and llvm::sandboxir::Value::Val.
Referenced by getDataOperandNo().
isIndirectCall()
bool llvm::sandboxir::CallBase::isIndirectCall () const inline
Definition at line 1403 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isInlineAsm()
bool llvm::sandboxir::CallBase::isInlineAsm () const inline
Definition at line 1425 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isMustTailCall()
bool llvm::sandboxir::CallBase::isMustTailCall () const inline
Definition at line 1413 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
isTailCall()
bool llvm::sandboxir::CallBase::isTailCall () const inline
Definition at line 1416 of file Instruction.h.
References llvm::cast(), and llvm::sandboxir::Value::Val.
setArgOperand()
void llvm::sandboxir::CallBase::setArgOperand (unsigned OpIdx, Value * NewOp) inline
Definition at line 1377 of file Instruction.h.
References arg_size(), assert(), OpIdx, and llvm::sandboxir::User::setOperand().
setCalledFunction()
void llvm::sandboxir::CallBase::setCalledFunction (Function * F)
Definition at line 502 of file Instruction.cpp.
References llvm::cast(), F, setCalledOperand(), and llvm::sandboxir::Value::Val.
setCalledOperand()
void llvm::sandboxir::CallBase::setCalledOperand (Value * V) inline
Definition at line 1420 of file Instruction.h.
References getCalledOperandUse(), and llvm::sandboxir::Use::set().
Referenced by setCalledFunction().
Friends And Related Symbol Documentation
CallBrInst
friend class CallBrInst friend
Definition at line 1302 of file Instruction.h.
References CallBrInst.
Referenced by CallBrInst.
CallInst
friend class CallInst friend
Definition at line 1300 of file Instruction.h.
References CallInst.
Referenced by CallInst.
InvokeInst
friend class InvokeInst friend
Definition at line 1301 of file Instruction.h.
References InvokeInst.
Referenced by InvokeInst.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Instruction.h
lib/SandboxIR/Instruction.cpp