LLVM: llvm::cas::ondisk::object_refs_iterator Class Reference
llvm::cas::ondisk::object_refs_iterator Class Reference
Iterator for ObjectID.
#include "llvm/CAS/OnDiskGraphDB.h"
Public Member Functions
bool operator== (const object_refs_iterator &RHS) const
ObjectID operator* () const
bool operator< (const object_refs_iterator &RHS) const
ptrdiff_t operator- (const object_refs_iterator &RHS) const
object_refs_iterator & operator+= (ptrdiff_t N)
object_refs_iterator & operator-= (ptrdiff_t N)
ObjectID operator[] (ptrdiff_t N) const
object_refs_iterator ()=default
object_refs_iterator (InternalRefArrayRef::iterator I)
uint64_t getOpaqueData () const
Public Member Functions inherited from llvm::iterator_facade_base< object_refs_iterator, std::random_access_iterator_tag, ObjectID >
object_refs_iterator operator+ (std::ptrdiff_t n) const
object_refs_iterator operator- (std::ptrdiff_t n) const
object_refs_iterator & operator++ ()
object_refs_iterator & operator-- ()
bool operator!= (const object_refs_iterator &RHS) const
bool operator> (const object_refs_iterator &RHS) const
bool operator<= (const object_refs_iterator &RHS) const
bool operator>= (const object_refs_iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Static Public Member Functions
static object_refs_iterator fromOpaqueData (uint64_t Opaque)
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< object_refs_iterator, std::random_access_iterator_tag, ObjectID >
enum
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Iterator for ObjectID.
Definition at line 219 of file OnDiskGraphDB.h.
Constructor & Destructor Documentation
object_refs_iterator() [1/2]
llvm::cas::ondisk::object_refs_iterator::object_refs_iterator () default
Referenced by fromOpaqueData(), operator+=(), operator-(), operator-=(), operator<(), and operator==().
object_refs_iterator() [2/2]
llvm::cas::ondisk::object_refs_iterator::object_refs_iterator (InternalRefArrayRef::iterator I) inline
Definition at line 242 of file OnDiskGraphDB.h.
Member Function Documentation
fromOpaqueData()
object_refs_iterator llvm::cas::ondisk::object_refs_iterator::fromOpaqueData (uint64_t Opaque) inline static
Definition at line 246 of file OnDiskGraphDB.h.
References object_refs_iterator().
getOpaqueData()
uint64_t llvm::cas::ondisk::object_refs_iterator::getOpaqueData () const inline
Definition at line 244 of file OnDiskGraphDB.h.
operator*()
ObjectID llvm::cas::ondisk::object_refs_iterator::operator* () const inline
Definition at line 224 of file OnDiskGraphDB.h.
References llvm::cas::ondisk::ObjectID::fromOpaqueData().
operator+=()
object_refs_iterator & llvm::cas::ondisk::object_refs_iterator::operator+= (ptrdiff_t N) inline
Definition at line 231 of file OnDiskGraphDB.h.
References N, and object_refs_iterator().
operator-()
ptrdiff_t llvm::cas::ondisk::object_refs_iterator::operator- (const object_refs_iterator & RHS) const inline
Definition at line 228 of file OnDiskGraphDB.h.
References object_refs_iterator(), and RHS.
operator-=()
object_refs_iterator & llvm::cas::ondisk::object_refs_iterator::operator-= (ptrdiff_t N) inline
Definition at line 235 of file OnDiskGraphDB.h.
References N, and object_refs_iterator().
operator<()
bool llvm::cas::ondisk::object_refs_iterator::operator< (const object_refs_iterator & RHS) const inline
Definition at line 227 of file OnDiskGraphDB.h.
References object_refs_iterator(), and RHS.
operator==()
bool llvm::cas::ondisk::object_refs_iterator::operator== (const object_refs_iterator & RHS) const inline
Definition at line 223 of file OnDiskGraphDB.h.
References object_refs_iterator(), and RHS.
operator[]()
ObjectID llvm::cas::ondisk::object_refs_iterator::operator[] (ptrdiff_t N) const inline
Definition at line 239 of file OnDiskGraphDB.h.
References N, and llvm::iterator_facade_base< object_refs_iterator, std::random_access_iterator_tag, ObjectID >::operator+().
The documentation for this class was generated from the following file:
include/llvm/CAS/OnDiskGraphDB.h