LLVM: llvm::APFloatBase Class Reference
llvm::APFloatBase Class Reference
#include "llvm/ADT/APFloat.h"
Public Types
enum cmpResult { cmpLessThan , cmpEqual , cmpGreaterThan , cmpUnordered }
IEEE-754R 5.11: Floating Point Comparison Relations.
enum opStatus {
opOK = 0x00 , opInvalidOp = 0x01 , opDivByZero = 0x02 , opOverflow = 0x04 ,
opUnderflow = 0x08 , opInexact = 0x10
}
IEEE-754R 7: Default exception handling.
enum fltCategory { fcInfinity , fcNaN , fcNormal , fcZero }
Category of internally-represented number.
enum uninitializedTag { uninitialized }
Convenience enum used to construct an uninitialized APFloat.
enum IlogbErrorKinds { IEK_Zero = INT_MIN + 1 , IEK_NaN = INT_MIN , IEK_Inf = INT_MAX }
Enumeration of ilogb error results.
typedef APInt::WordType integerPart
using ExponentType = int32_t
A signed type to represent a floating point numbers unbiased exponent.
using roundingMode = llvm::RoundingMode
IEEE-754R 4.3: Rounding-direction attributes.
Static Public Member Functions
static LLVM_ABI unsigned int semanticsPrecision (const fltSemantics &)
static LLVM_ABI ExponentType semanticsMinExponent (const fltSemantics &)
static LLVM_ABI ExponentType semanticsMaxExponent (const fltSemantics &)
static LLVM_ABI unsigned int semanticsSizeInBits (const fltSemantics &)
static LLVM_ABI unsigned int semanticsIntSizeInBits (const fltSemantics &, bool)
static LLVM_ABI bool semanticsHasZero (const fltSemantics &)
static LLVM_ABI bool semanticsHasSignedRepr (const fltSemantics &)
static LLVM_ABI bool semanticsHasInf (const fltSemantics &)
static LLVM_ABI bool semanticsHasNaN (const fltSemantics &)
static LLVM_ABI bool isIEEELikeFP (const fltSemantics &)
static LLVM_ABI bool hasSignBitInMSB (const fltSemantics &)
static LLVM_ABI bool isRepresentableAsNormalIn (const fltSemantics &Src, const fltSemantics &Dst)
static LLVM_ABI unsigned getSizeInBits (const fltSemantics &Sem)
Returns the size of the floating point number (in bits) in the given semantics.
Static Public Attributes
static constexpr unsigned integerPartWidth = APInt::APINT_BITS_PER_WORD
static constexpr roundingMode rmNearestTiesToEven
static constexpr roundingMode rmTowardPositive = RoundingMode::TowardPositive
static constexpr roundingMode rmTowardNegative = RoundingMode::TowardNegative
static constexpr roundingMode rmTowardZero = RoundingMode::TowardZero
static constexpr roundingMode rmNearestTiesToAway
Floating Point Semantics.
enum Semantics {
S_IEEEhalf , S_BFloat , S_IEEEsingle , S_IEEEdouble ,
S_IEEEquad , S_PPCDoubleDouble , S_PPCDoubleDoubleLegacy , S_Float8E5M2 ,
S_Float8E5M2FNUZ , S_Float8E4M3 , S_Float8E4M3FN , S_Float8E4M3FNUZ ,
S_Float8E4M3B11FNUZ , S_Float8E3M4 , S_FloatTF32 , S_Float8E8M0FNU ,
S_Float6E3M2FN , S_Float6E2M3FN , S_Float4E2M1FN , S_x87DoubleExtended ,
S_MaxSemantics = S_x87DoubleExtended
}
class detail::IEEEFloat
class detail::DoubleAPFloat
class APFloat
static LLVM_ABI const llvm::fltSemantics & EnumToSemantics (Semantics S)
static LLVM_ABI Semantics SemanticsToEnum (const llvm::fltSemantics &Sem)
static const fltSemantics & IEEEhalf ()
static const fltSemantics & BFloat ()
static const fltSemantics & IEEEsingle ()
static const fltSemantics & IEEEdouble ()
static const fltSemantics & IEEEquad ()
static const fltSemantics & PPCDoubleDouble ()
static const fltSemantics & PPCDoubleDoubleLegacy ()
static const fltSemantics & Float8E5M2 ()
static const fltSemantics & Float8E5M2FNUZ ()
static const fltSemantics & Float8E4M3 ()
static const fltSemantics & Float8E4M3FN ()
static const fltSemantics & Float8E4M3FNUZ ()
static const fltSemantics & Float8E4M3B11FNUZ ()
static const fltSemantics & Float8E3M4 ()
static const fltSemantics & FloatTF32 ()
static const fltSemantics & Float8E8M0FNU ()
static const fltSemantics & Float6E3M2FN ()
static const fltSemantics & Float6E2M3FN ()
static const fltSemantics & Float4E2M1FN ()
static const fltSemantics & x87DoubleExtended ()
static const fltSemantics & Bogus ()
A Pseudo fltsemantic used to construct APFloats that cannot conflict with anything real.
static LLVM_ABI bool isRepresentableBy (const fltSemantics &A, const fltSemantics &B)
Detailed Description
Definition at line 149 of file APFloat.h.
Member Typedef Documentation
ExponentType
using llvm::APFloatBase::ExponentType = int32_t
A signed type to represent a floating point numbers unbiased exponent.
Definition at line 155 of file APFloat.h.
integerPart
typedef APInt::WordType llvm::APFloatBase::integerPart
Definition at line 151 of file APFloat.h.
roundingMode
using llvm::APFloatBase::roundingMode = llvm::RoundingMode
IEEE-754R 4.3: Rounding-direction attributes.
Definition at line 342 of file APFloat.h.
Member Enumeration Documentation
cmpResult
enum llvm::APFloatBase::cmpResult
IEEE-754R 5.11: Floating Point Comparison Relations.
Enumerator
cmpLessThan
cmpEqual
cmpGreaterThan
cmpUnordered
Definition at line 334 of file APFloat.h.
fltCategory
enum llvm::APFloatBase::fltCategory
Category of internally-represented number.
Enumerator
fcInfinity
fcNaN
fcNormal
fcZero
Definition at line 370 of file APFloat.h.
IlogbErrorKinds
enum llvm::APFloatBase::IlogbErrorKinds
Enumeration of ilogb error results.
Enumerator
IEK_Zero
IEK_NaN
IEK_Inf
Definition at line 383 of file APFloat.h.
opStatus
enum llvm::APFloatBase::opStatus
IEEE-754R 7: Default exception handling.
opUnderflow or opOverflow are always returned or-ed with opInexact.
APFloat models this behavior specified by IEEE-754: "For operations producing results in floating-point format, the default result of an operation that signals the invalid operation exception shall be a quiet NaN."
Enumerator
opOK
opInvalidOp
opDivByZero
opOverflow
opUnderflow
opInexact
Definition at line 360 of file APFloat.h.
Semantics
enum llvm::APFloatBase::Semantics
Enumerator
S_IEEEhalf
S_BFloat
S_IEEEsingle
S_IEEEdouble
S_IEEEquad
S_PPCDoubleDouble
S_PPCDoubleDoubleLegacy
S_Float8E5M2
S_Float8E5M2FNUZ
S_Float8E4M3
S_Float8E4M3FN
S_Float8E4M3FNUZ
S_Float8E4M3B11FNUZ
S_Float8E3M4
S_FloatTF32
S_Float8E8M0FNU
S_Float6E3M2FN
S_Float6E2M3FN
S_Float4E2M1FN
S_x87DoubleExtended
S_MaxSemantics
Definition at line 159 of file APFloat.h.
uninitializedTag
enum llvm::APFloatBase::uninitializedTag
Convenience enum used to construct an uninitialized APFloat.
Enumerator
uninitialized
Definition at line 378 of file APFloat.h.
Member Function Documentation
BFloat()
const fltSemantics & llvm::APFloatBase::BFloat () inline static
Definition at line 295 of file APFloat.h.
Referenced by EnumToSemantics(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::MVT::getFltSemantics(), getOpFltSemantics(), llvm::ConstantFP::isValueValidForType(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), shrinkFPConstant(), writeAPFloatInternal(), and llvm::X86TargetLowering::X86TargetLowering().
Bogus()
const fltSemantics & llvm::APFloatBase::Bogus () inline static
A Pseudo fltsemantic used to construct APFloats that cannot conflict with anything real.
Definition at line 323 of file APFloat.h.
Referenced by llvm::DenseMapInfo< APFloat >::getEmptyKey(), and llvm::DenseMapInfo< APFloat >::getTombstoneKey().
EnumToSemantics()
const llvm::fltSemantics & llvm::APFloatBase::EnumToSemantics (Semantics S) static
Definition at line 174 of file APFloat.cpp.
References BFloat(), Float4E2M1FN(), Float6E2M3FN(), Float6E3M2FN(), Float8E3M4(), Float8E4M3(), Float8E4M3B11FNUZ(), Float8E4M3FN(), Float8E4M3FNUZ(), Float8E5M2(), Float8E5M2FNUZ(), Float8E8M0FNU(), FloatTF32(), IEEEdouble(), IEEEhalf(), IEEEquad(), IEEEsingle(), llvm_unreachable, PPCDoubleDouble(), PPCDoubleDoubleLegacy(), S_BFloat, S_Float4E2M1FN, S_Float6E2M3FN, S_Float6E3M2FN, S_Float8E3M4, S_Float8E4M3, S_Float8E4M3B11FNUZ, S_Float8E4M3FN, S_Float8E4M3FNUZ, S_Float8E5M2, S_Float8E5M2FNUZ, S_Float8E8M0FNU, S_FloatTF32, S_IEEEdouble, S_IEEEhalf, S_IEEEquad, S_IEEEsingle, S_PPCDoubleDouble, S_PPCDoubleDoubleLegacy, S_x87DoubleExtended, and x87DoubleExtended().
Float4E2M1FN()
const fltSemantics & llvm::APFloatBase::Float4E2M1FN () inline static
Definition at line 316 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float6E2M3FN()
const fltSemantics & llvm::APFloatBase::Float6E2M3FN () inline static
Definition at line 315 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float6E3M2FN()
const fltSemantics & llvm::APFloatBase::Float6E3M2FN () inline static
Definition at line 314 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E3M4()
const fltSemantics & llvm::APFloatBase::Float8E3M4 () inline static
Definition at line 311 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E4M3()
const fltSemantics & llvm::APFloatBase::Float8E4M3 () inline static
Definition at line 305 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E4M3B11FNUZ()
const fltSemantics & llvm::APFloatBase::Float8E4M3B11FNUZ () inline static
Definition at line 308 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E4M3FN()
const fltSemantics & llvm::APFloatBase::Float8E4M3FN () inline static
Definition at line 306 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E4M3FNUZ()
const fltSemantics & llvm::APFloatBase::Float8E4M3FNUZ () inline static
Definition at line 307 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E5M2()
const fltSemantics & llvm::APFloatBase::Float8E5M2 () inline static
Definition at line 303 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E5M2FNUZ()
const fltSemantics & llvm::APFloatBase::Float8E5M2FNUZ () inline static
Definition at line 304 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E8M0FNU()
const fltSemantics & llvm::APFloatBase::Float8E8M0FNU () inline static
Definition at line 313 of file APFloat.h.
Referenced by EnumToSemantics(), llvm::APFloat::hasSignificand(), and SemanticsToEnum().
FloatTF32()
const fltSemantics & llvm::APFloatBase::FloatTF32 () inline static
Definition at line 312 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
getSizeInBits()
unsigned llvm::APFloatBase::getSizeInBits (const fltSemantics & Sem) static
Returns the size of the floating point number (in bits) in the given semantics.
Definition at line 354 of file APFloat.cpp.
References llvm::fltSemantics::sizeInBits.
Referenced by llvm::MachineIRBuilder::buildFConstant().
hasSignBitInMSB()
bool llvm::APFloatBase::hasSignBitInMSB (const fltSemantics & semantics) static
Definition at line 336 of file APFloat.cpp.
References llvm::fltSemantics::hasSignBitInMSB.
Referenced by llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitXor().
IEEEdouble()
const fltSemantics & llvm::APFloatBase::IEEEdouble () inline static
Definition at line 297 of file APFloat.h.
Referenced by llvm::APFloat::APFloat(), combineBitcast(), constantFoldFpUnary(), convertIntToDoubleImm(), emitDebugValueComment(), EnumToSemantics(), fixFuncEntryCount(), llvm::SelectionDAG::FoldConstantArithmetic(), getConstantVector(), getConstantVector(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::getFltSemanticForLLT(), getFltSemantics(), llvm::MVT::getFltSemantics(), llvm::RISCVLoadFPImm::getLoadFPImm(), getOneFP(), getOpFltSemantics(), getZeroFP(), isInv2Pi(), isInv2Pi(), llvm::ConstantFP::isValueValidForType(), llvm::AMDGPULegalizerInfo::legalizeFroundeven(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), LLVMConstRealGetDouble(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::ARMAsmPrinter::lowerOperand(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::SDNode::print_details(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), shrinkFPConstant(), and writeAPFloatInternal().
IEEEhalf()
const fltSemantics & llvm::APFloatBase::IEEEhalf () inline static
Definition at line 294 of file APFloat.h.
Referenced by canSafelyConvertTo16Bit(), convertNvvmIntrinsicToLlvm(), EnumToSemantics(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::getAPFloatFromSize(), getConstantVector(), getConstantVector(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::getFltSemanticForLLT(), getFltSemantics(), llvm::MVT::getFltSemantics(), llvm::RISCVLoadFPImm::getLoadFPImm(), getOneFP(), getOpFltSemantics(), getZeroFP(), llvm::GCNTTIImpl::instCombineIntrinsic(), isFPExtFromF16OrConst(), isInv2Pi(), isInv2Pi(), llvm::ConstantFP::isValueValidForType(), matchFPExtFromF16(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), shrinkFPConstant(), strictFPExtFromF16(), writeAPFloatInternal(), and llvm::X86TargetLowering::X86TargetLowering().
IEEEquad()
const fltSemantics & llvm::APFloatBase::IEEEquad () inline static
Definition at line 298 of file APFloat.h.
Referenced by EnumToSemantics(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::getFltSemanticForLLT(), llvm::MVT::getFltSemantics(), llvm::ConstantFP::isValueValidForType(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), llvm::SystemZVectorConstantInfo::SystemZVectorConstantInfo(), writeAPFloatInternal(), and llvm::X86TargetLowering::X86TargetLowering().
IEEEsingle()
const fltSemantics & llvm::APFloatBase::IEEEsingle () inline static
Definition at line 296 of file APFloat.h.
Referenced by llvm::APFloat::APFloat(), llvm::checkConvertToNonDenormSingle(), convertNvvmIntrinsicToLlvm(), llvm::convertToNonDenormSingle(), EnumToSemantics(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::generateReadImageInst(), getConstantVector(), getConstantVector(), llvm::ConstantDataSequential::getElementAsAPFloat(), getF32Constant(), llvm::getFltSemanticForLLT(), getFltSemantics(), llvm::MVT::getFltSemantics(), llvm::RISCVLoadFPImm::getLoadFPImm(), getOneFP(), getOpFltSemantics(), llvm::AMDGPULegalizerInfo::getScaledLogInput(), llvm::AMDGPUTargetLowering::getScaledLogInput(), getZeroFP(), llvm::Attributor::identifyDefaultAbstractAttributes(), isInv2Pi(), isInv2Pi(), llvm::ConstantFP::isValueValidForType(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFlogCommon(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::LegalizerHelper::lowerFPTOUI(), lowerUINT_TO_FP_vXi32(), llvm::AMDGPUTargetLowering::needsDenormHandlingF32(), needsDenormHandlingF32(), llvm::SDNode::print_details(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), shrinkFPConstant(), llvm::pdb::Variant::toAPFloat(), llvm::NVPTXTargetLowering::useF32FTZ(), valueHasFloatPrecision(), and writeAPFloatInternal().
isIEEELikeFP()
bool llvm::APFloatBase::isIEEELikeFP (const fltSemantics & semantics) static
Definition at line 331 of file APFloat.cpp.
References S_IEEEquad, and SemanticsToEnum().
Referenced by isRepresentableAsExactInteger().
isRepresentableAsNormalIn()
bool llvm::APFloatBase::isRepresentableAsNormalIn (const fltSemantics & Src, const fltSemantics & Dst) static
Definition at line 340 of file APFloat.cpp.
Referenced by llvm::KnownFPClass::fpext().
isRepresentableBy()
bool llvm::APFloatBase::isRepresentableBy (const fltSemantics & A, const fltSemantics & B) static
Definition at line 266 of file APFloat.cpp.
References A(), and B().
Referenced by llvm::APFloat::convertToDouble(), and llvm::APFloat::convertToFloat().
PPCDoubleDouble()
const fltSemantics & llvm::APFloatBase::PPCDoubleDouble () inline static
Definition at line 299 of file APFloat.h.
Referenced by EnumToSemantics(), llvm::detail::frexp(), llvm::MVT::getFltSemantics(), llvm::ConstantFP::isValueValidForType(), llvm::detail::scalbn(), SemanticsToEnum(), and writeAPFloatInternal().
PPCDoubleDoubleLegacy()
const fltSemantics & llvm::APFloatBase::PPCDoubleDoubleLegacy () inline static
Definition at line 300 of file APFloat.h.
Referenced by EnumToSemantics(), and SemanticsToEnum().
semanticsHasInf()
bool llvm::APFloatBase::semanticsHasInf (const fltSemantics & semantics) static
Definition at line 323 of file APFloat.cpp.
References llvm::IEEE754, and llvm::fltSemantics::nonFiniteBehavior.
semanticsHasNaN()
bool llvm::APFloatBase::semanticsHasNaN (const fltSemantics & semantics) static
Definition at line 327 of file APFloat.cpp.
References llvm::FiniteOnly, and llvm::fltSemantics::nonFiniteBehavior.
semanticsHasSignedRepr()
bool llvm::APFloatBase::semanticsHasSignedRepr (const fltSemantics & semantics) static
Definition at line 319 of file APFloat.cpp.
References llvm::fltSemantics::hasSignedRepr.
semanticsHasZero()
bool llvm::APFloatBase::semanticsHasZero (const fltSemantics & semantics) static
Definition at line 315 of file APFloat.cpp.
References llvm::fltSemantics::hasZero.
semanticsIntSizeInBits()
unsigned int llvm::APFloatBase::semanticsIntSizeInBits (const fltSemantics & semantics, bool isSigned) static
Definition at line 304 of file APFloat.cpp.
References semanticsMaxExponent().
Referenced by isSaturatingMinMax().
semanticsMaxExponent()
APFloatBase::ExponentType llvm::APFloatBase::semanticsMaxExponent (const fltSemantics & semantics) static
Definition at line 294 of file APFloat.cpp.
References llvm::fltSemantics::maxExponent.
Referenced by llvm::FunctionComparator::cmpAPFloats(), and semanticsIntSizeInBits().
semanticsMinExponent()
APFloatBase::ExponentType llvm::APFloatBase::semanticsMinExponent (const fltSemantics & semantics) static
Definition at line 298 of file APFloat.cpp.
References llvm::fltSemantics::minExponent.
Referenced by llvm::FunctionComparator::cmpAPFloats().
semanticsPrecision()
unsigned int llvm::APFloatBase::semanticsPrecision (const fltSemantics & semantics) static
Definition at line 290 of file APFloat.cpp.
References llvm::fltSemantics::precision.
Referenced by CastIntSETCCtoFP(), llvm::FunctionComparator::cmpAPFloats(), computeKnownFPClass(), FoldIntToFPToInt(), getEstimate(), isRepresentableAsExactInteger(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), and llvm::detail::IEEEFloat::roundToIntegral().
semanticsSizeInBits()
unsigned int llvm::APFloatBase::semanticsSizeInBits (const fltSemantics & semantics) static
Definition at line 301 of file APFloat.cpp.
References llvm::fltSemantics::sizeInBits.
Referenced by llvm::FunctionComparator::cmpAPFloats().
SemanticsToEnum()
APFloatBase::Semantics llvm::APFloatBase::SemanticsToEnum (const llvm::fltSemantics & Sem) static
Definition at line 221 of file APFloat.cpp.
References BFloat(), Float4E2M1FN(), Float6E2M3FN(), Float6E3M2FN(), Float8E3M4(), Float8E4M3(), Float8E4M3B11FNUZ(), Float8E4M3FN(), Float8E4M3FNUZ(), Float8E5M2(), Float8E5M2FNUZ(), Float8E8M0FNU(), FloatTF32(), IEEEdouble(), IEEEhalf(), IEEEquad(), IEEEsingle(), llvm_unreachable, PPCDoubleDouble(), PPCDoubleDoubleLegacy(), S_BFloat, S_Float4E2M1FN, S_Float6E2M3FN, S_Float6E3M2FN, S_Float8E3M4, S_Float8E4M3, S_Float8E4M3B11FNUZ, S_Float8E4M3FN, S_Float8E4M3FNUZ, S_Float8E5M2, S_Float8E5M2FNUZ, S_Float8E8M0FNU, S_FloatTF32, S_IEEEdouble, S_IEEEhalf, S_IEEEquad, S_IEEEsingle, S_PPCDoubleDouble, S_PPCDoubleDoubleLegacy, S_x87DoubleExtended, and x87DoubleExtended().
Referenced by isIEEELikeFP(), and llvm::SIInstrInfo::isInlineConstant().
x87DoubleExtended()
const fltSemantics & llvm::APFloatBase::x87DoubleExtended () inline static
Definition at line 317 of file APFloat.h.
Referenced by EnumToSemantics(), llvm::ExecutionEngine::getConstantValue(), llvm::MVT::getFltSemantics(), llvm::ConstantFP::isValueValidForType(), SemanticsToEnum(), toStringAPFloat(), writeAPFloatInternal(), and llvm::X86TargetLowering::X86TargetLowering().
Friends And Related Symbol Documentation
APFloat
friend class APFloat friend
Definition at line 291 of file APFloat.h.
References APFloat.
Referenced by APFloat, llvm::APFloat::convert(), and llvm::APFloat::getAllOnesValue().
detail::DoubleAPFloat
friend class detail::DoubleAPFloat friend
Definition at line 290 of file APFloat.h.
detail::IEEEFloat
friend class detail::IEEEFloat friend
Definition at line 289 of file APFloat.h.
Member Data Documentation
integerPartWidth
unsigned llvm::APFloatBase::integerPartWidth = APInt::APINT_BITS_PER_WORD static constexpr
Definition at line 152 of file APFloat.h.
Referenced by llvm::lostFractionThroughTruncation(), llvm::partAsHex(), llvm::partCountForBits(), and llvm::ulpsFromBoundary().
rmNearestTiesToAway
roundingMode llvm::APFloatBase::rmNearestTiesToAway static constexpr
Initial value:
    =
RoundingMode::NearestTiesToAway
Definition at line 349 of file APFloat.h.
Referenced by llvm::FixedPointSemantics::fitsInFloatSemantics().
rmNearestTiesToEven
roundingMode llvm::APFloatBase::rmNearestTiesToEven static constexpr
Initial value:
    =
RoundingMode::NearestTiesToEven
Definition at line 344 of file APFloat.h.
Referenced by llvm::APFloat::APFloat(), canLosslesslyConvertToFPType(), llvm::checkConvertToNonDenormSingle(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldFPBinOp(), constantFoldFpUnary(), llvm::ConstantFoldIntToFloat(), llvm::APFloat::convertToDouble(), llvm::APFixedPoint::convertToFloat(), llvm::APFloat::convertToFloat(), llvm::convertToNonDenormSingle(), emitDebugValueComment(), llvm::TargetLowering::expandFP_TO_UINT(), fitsInFPType(), fixFuncEntryCount(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::foldConstantFPMath(), foldFCmpFpTrunc(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), foldFPToIntToFP(), foldFrexpOfSelect(), llvm::ConstantFP::get(), llvm::getAPFloatFromSize(), llvm::StringRef::getAsDouble(), llvm::SelectionDAG::getConstantFP(), llvm::ExecutionEngine::getConstantValue(), llvm::nvvm::GetFAddRoundingMode(), llvm::nvvm::GetFDivRoundingMode(), llvm::nvvm::GetFMARoundingMode(), llvm::nvvm::GetFMulRoundingMode(), llvm::nvvm::GetFPToIntegerRoundingMode(), llvm::RISCVLoadFPImm::getLoadFPImm(), llvm::SelectionDAG::getNode(), llvm::nvvm::GetRCPRoundingMode(), llvm::harrisonUlp(), llvm::detail::IEEEFloat::ilogb, llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::APFloat::isExactlyValue(), llvm::ConstantFP::isExactlyValue(), isFPExtFromF16OrConst(), llvm::ConstantFP::isValueValidForType(), llvm::ConstantFPSDNode::isValueValidForType(), LLVMConstRealGetDouble(), llvm::LegalizerHelper::lowerFPTOUI(), LowerFROUND(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), llvm::CombinerHelper::matchConstantFoldFMA(), matchFPExtFromF16(), llvm::APFloat::operator*(), llvm::APFloat::operator+(), llvm::APFloat::operator-(), llvm::APFloat::operator/(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::NVPTXFloatMCExpr::printImpl(), strictFPExtFromF16(), toString(), valueHasFloatPrecision(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), writeAPFloatInternal(), and llvm::X86TargetLowering::X86TargetLowering().
rmTowardNegative
roundingMode llvm::APFloatBase::rmTowardNegative = RoundingMode::TowardNegative static constexpr
Definition at line 347 of file APFloat.h.
Referenced by llvm::SelectionDAG::FoldConstantArithmetic(), llvm::nvvm::GetFAddRoundingMode(), llvm::nvvm::GetFDivRoundingMode(), llvm::nvvm::GetFMARoundingMode(), llvm::nvvm::GetFMulRoundingMode(), llvm::nvvm::GetFPToIntegerRoundingMode(), and llvm::nvvm::GetRCPRoundingMode().
rmTowardPositive
roundingMode llvm::APFloatBase::rmTowardPositive = RoundingMode::TowardPositive static constexpr
Definition at line 346 of file APFloat.h.
Referenced by llvm::SelectionDAG::FoldConstantArithmetic(), llvm::nvvm::GetFAddRoundingMode(), llvm::nvvm::GetFDivRoundingMode(), llvm::nvvm::GetFMARoundingMode(), llvm::nvvm::GetFMulRoundingMode(), llvm::nvvm::GetFPToIntegerRoundingMode(), and llvm::nvvm::GetRCPRoundingMode().
rmTowardZero
roundingMode llvm::APFloatBase::rmTowardZero = RoundingMode::TowardZero static constexpr
Definition at line 348 of file APFloat.h.
Referenced by canSafelyConvertTo16Bit(), checkCVTFixedPointOperandWithFBits(), llvm::ConstantFoldCastInstruction(), llvm::APFixedPoint::convertToFloat(), ConvertToSInt(), llvm::TargetLowering::expandFP_TO_INT_SAT(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), foldFPToIntToFP(), llvm::BuildVectorSDNode::getConstantFPSplatPow2ToLog2Int(), llvm::ExecutionEngine::getConstantValue(), llvm::APFloat::getExactInverse(), llvm::nvvm::GetFAddRoundingMode(), llvm::nvvm::GetFDivRoundingMode(), llvm::nvvm::GetFMARoundingMode(), llvm::nvvm::GetFMulRoundingMode(), llvm::nvvm::GetFPToIntegerRoundingMode(), llvm::APFixedPoint::getFromFloatValue(), llvm::nvvm::GetRCPRoundingMode(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::PPCTargetLowering::isFPImmLegal(), isMinMaxCmpSelectEliminable(), llvm::LegalizerHelper::lowerFPTOINT_SAT(), llvm::ARMAsmPrinter::lowerOperand(), and PerformVMulVCTPCombine().
The documentation for this class was generated from the following files:
include/llvm/ADT/APFloat.h
lib/Support/APFloat.cpp