LLVM: llvm::TimePassesHandler Class Reference
llvm::TimePassesHandler Class Reference
This class implements -time-passes functionality for new pass manager.
#include "llvm/IR/PassTimingInfo.h"
Public Member Functions
LLVM_ABI TimePassesHandler ()
LLVM_ABI TimePassesHandler (bool Enabled, bool PerRun=false)
LLVM_ABI void print ()
Prints out timing information and then resets the timers.
TimePassesHandler (const TimePassesHandler &)=delete
void operator= (const TimePassesHandler &)=delete
LLVM_ABI void registerCallbacks (PassInstrumentationCallbacks &PIC)
LLVM_ABI void setOutStream (raw_ostream &OutStream)
Set a custom output stream for subsequent reporting.
Static Public Attributes
static constexpr StringRef PassGroupName = "pass"
static constexpr StringRef AnalysisGroupName = "analysis"
static constexpr StringRef PassGroupDesc = "Pass execution timing report"
static constexpr StringRef AnalysisGroupDesc
Detailed Description
This class implements -time-passes functionality for new pass manager.
It provides the pass-instrumentation callbacks that measure the pass execution time. They collect timing info into individual timers as passes are being run.
Definition at line 44 of file PassTimingInfo.h.
Constructor & Destructor Documentation
TimePassesHandler() [1/3]
TimePassesHandler::TimePassesHandler ()
Definition at line 188 of file PassTimingInfo.cpp.
References TimePassesHandler(), llvm::TimePassesIsEnabled, and llvm::TimePassesPerRun.
Referenced by operator=(), TimePassesHandler(), and TimePassesHandler().
TimePassesHandler() [2/3]
TimePassesHandler::TimePassesHandler (bool Enabled, bool PerRun = false)
Definition at line 185 of file PassTimingInfo.cpp.
TimePassesHandler() [3/3]
llvm::TimePassesHandler::TimePassesHandler (const TimePassesHandler &) delete
References TimePassesHandler().
Member Function Documentation
operator=()
void llvm::TimePassesHandler::operator= (const TimePassesHandler &) delete
References LLVM_ABI, LLVM_DUMP_METHOD, PIC, and TimePassesHandler().
print()
void TimePassesHandler::print ()
Prints out timing information and then resets the timers.
Definition at line 195 of file PassTimingInfo.cpp.
References llvm::CreateInfoOutputFile().
registerCallbacks()
void TimePassesHandler::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 299 of file PassTimingInfo.cpp.
References P, and PIC.
setOutStream()
void TimePassesHandler::setOutStream (raw_ostream & OutStream)
Set a custom output stream for subsequent reporting.
Definition at line 191 of file PassTimingInfo.cpp.
Member Data Documentation
AnalysisGroupDesc
StringRef llvm::TimePassesHandler::AnalysisGroupDesc static constexpr
Initial value:
                                         =
"Analysis execution timing report"
Definition at line 79 of file PassTimingInfo.h.
AnalysisGroupName
StringRef llvm::TimePassesHandler::AnalysisGroupName = "analysis" static constexpr
Definition at line 77 of file PassTimingInfo.h.
PassGroupDesc
StringRef llvm::TimePassesHandler::PassGroupDesc = "Pass execution timing report" static constexpr
Definition at line 78 of file PassTimingInfo.h.
PassGroupName
StringRef llvm::TimePassesHandler::PassGroupName = "pass" static constexpr
Definition at line 76 of file PassTimingInfo.h.
The documentation for this class was generated from the following files:
include/llvm/IR/PassTimingInfo.h
lib/IR/PassTimingInfo.cpp