LLVM: llvm::VETargetStreamer Class Reference
llvm::VETargetStreamer Class Reference
#include "Target/VE/MCTargetDesc/VETargetStreamer.h"
Public Member Functions
VETargetStreamer (MCStreamer &S)
virtual void emitVERegisterIgnore (unsigned reg)
Emit ".register <reg>, #ignore".
virtual void emitVERegisterScratch (unsigned reg)
Emit ".register <reg>, #scratch".
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 17 of file VETargetStreamer.h.
Constructor & Destructor Documentation
VETargetStreamer()
VETargetStreamer::VETargetStreamer (MCStreamer & S)
Definition at line 20 of file VETargetStreamer.cpp.
References llvm::MCTargetStreamer::MCTargetStreamer().
Referenced by llvm::VETargetAsmStreamer::VETargetAsmStreamer(), and llvm::VETargetELFStreamer::VETargetELFStreamer().
Member Function Documentation
emitVERegisterIgnore()
virtual void llvm::VETargetStreamer::emitVERegisterIgnore (unsigned reg) inline virtual
Emit ".register <reg>, #ignore".
Reimplemented in llvm::VETargetAsmStreamer, and llvm::VETargetELFStreamer.
Definition at line 23 of file VETargetStreamer.h.
emitVERegisterScratch()
virtual void llvm::VETargetStreamer::emitVERegisterScratch (unsigned reg) inline virtual
Emit ".register <reg>, #scratch".
Reimplemented in llvm::VETargetAsmStreamer, and llvm::VETargetELFStreamer.
Definition at line 25 of file VETargetStreamer.h.
The documentation for this class was generated from the following files:
lib/Target/VE/MCTargetDesc/VETargetStreamer.h
lib/Target/VE/MCTargetDesc/VETargetStreamer.cpp