LLVM: llvm::hlsl::BoundRegs Class Reference
llvm::hlsl::BoundRegs Class Reference
#include "llvm/Frontend/HLSL/HLSLBinding.h"
Public Member Functions
BoundRegs (SmallVector< Binding > &&Bindings)
const Binding * findBoundReg (dxil::ResourceClass RC, uint32_t Space, uint32_t LowerBound, uint32_t UpperBound) const
Detailed Description
Definition at line 130 of file HLSLBinding.h.
Constructor & Destructor Documentation
BoundRegs()
llvm::hlsl::BoundRegs::BoundRegs (SmallVector< Binding > && Bindings) inline
Definition at line 134 of file HLSLBinding.h.
References llvm::move().
Member Function Documentation
findBoundReg()
const Binding * llvm::hlsl::BoundRegs::findBoundReg (dxil::ResourceClass RC, uint32_t Space, uint32_t LowerBound, uint32_t UpperBound) const inline
Definition at line 136 of file HLSLBinding.h.
References llvm::hlsl::Binding::LowerBound, llvm::hlsl::Binding::RC, llvm::hlsl::Binding::Space, llvm::upper_bound(), and llvm::hlsl::Binding::UpperBound.
Referenced by validateRootSignature().
The documentation for this class was generated from the following file:
include/llvm/Frontend/HLSL/HLSLBinding.h