LLVM: llvm::sampleprof::SampleContext Class Reference
llvm::sampleprof::SampleContext Class Reference
#include "llvm/ProfileData/SampleProf.h"
Classes
struct Hash
Public Member Functions
SampleContext ()
SampleContext (StringRef Name)
SampleContext (FunctionId Func)
SampleContext (SampleContextFrames Context, ContextStateMask CState=RawContext)
SampleContext (StringRef ContextStr, std::list< SampleContextFrameVector > &CSNameTable, ContextStateMask CState=RawContext)
operator SampleContextFrames () const
bool hasAttribute (ContextAttributeMask A)
void setAttribute (ContextAttributeMask A)
uint32_t getAllAttributes ()
void setAllAttributes (uint32_t A)
bool hasState (ContextStateMask S)
void setState (ContextStateMask S)
void clearState (ContextStateMask S)
bool hasContext () const
bool isBaseContext () const
FunctionId getFunction () const
SampleContextFrames getContextFrames () const
std::string toString () const
uint64_t getHashCode () const
void setFunction (FunctionId NewFunctionID)
Set the name of the function and clear the current context.
void setContext (SampleContextFrames Context, ContextStateMask CState=RawContext)
bool operator== (const SampleContext &That) const
bool operator!= (const SampleContext &That) const
bool operator< (const SampleContext &That) const
bool isPrefixOf (const SampleContext &That) const
Static Public Member Functions
static void createCtxVectorFromStr (StringRef ContextStr, SampleContextFrameVector &Context)
Create a context vector from a given context string and save it in Context.
static void decodeContextString (StringRef ContextStr, FunctionId &Func, LineLocation &LineLoc)
static std::string getContextString (SampleContextFrames Context, bool IncludeLeafLineLocation=false)
Detailed Description
Definition at line 554 of file SampleProf.h.
Constructor & Destructor Documentation
SampleContext() [1/5]
llvm::sampleprof::SampleContext::SampleContext () inline
Definition at line 556 of file SampleProf.h.
References llvm::sampleprof::ContextNone, and llvm::sampleprof::UnknownContext.
Referenced by isPrefixOf(), operator!=(), llvm::sampleprof::SampleContext::Hash::operator()(), operator<(), and operator==().
SampleContext() [2/5]
llvm::sampleprof::SampleContext::SampleContext (StringRef Name) inline
Definition at line 558 of file SampleProf.h.
References assert(), llvm::sampleprof::ContextNone, and llvm::sampleprof::UnknownContext.
SampleContext() [3/5]
llvm::sampleprof::SampleContext::SampleContext (FunctionId Func) inline
Definition at line 563 of file SampleProf.h.
References llvm::sampleprof::ContextNone, and llvm::sampleprof::UnknownContext.
SampleContext() [4/5]
llvm::sampleprof::SampleContext::SampleContext (SampleContextFrames Context, ContextStateMask CState = RawContext) inline
Definition at line 566 of file SampleProf.h.
References assert(), llvm::sampleprof::ContextNone, llvm::sampleprof::RawContext, and setContext().
SampleContext() [5/5]
llvm::sampleprof::SampleContext::SampleContext (StringRef ContextStr, std::list< SampleContextFrameVector > & CSNameTable, ContextStateMask CState = RawContext) inline
Definition at line 576 of file SampleProf.h.
References assert(), llvm::sampleprof::ContextNone, createCtxVectorFromStr(), llvm::StringRef::empty(), llvm::sampleprof::RawContext, setContext(), llvm::StringRef::starts_with(), and llvm::sampleprof::UnknownContext.
Member Function Documentation
clearState()
void llvm::sampleprof::SampleContext::clearState (ContextStateMask S) inline
Definition at line 645 of file SampleProf.h.
createCtxVectorFromStr()
void llvm::sampleprof::SampleContext::createCtxVectorFromStr (StringRef ContextStr, SampleContextFrameVector & Context) inline static
Create a context vector from a given context string and save it in Context.
Definition at line 597 of file SampleProf.h.
References decodeContextString(), llvm::StringRef::empty(), llvm::StringRef::size(), llvm::StringRef::split(), and llvm::StringRef::substr().
Referenced by SampleContext().
decodeContextString()
void llvm::sampleprof::SampleContext::decodeContextString (StringRef ContextStr, FunctionId & Func, LineLocation & LineLoc) inline static
Definition at line 616 of file SampleProf.h.
References llvm::sampleprof::LineLocation::Discriminator, llvm::sampleprof::LineLocation::LineOffset, and llvm::StringRef::split().
Referenced by createCtxVectorFromStr().
getAllAttributes()
uint32_t llvm::sampleprof::SampleContext::getAllAttributes () inline
Definition at line 641 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeFuncMetadata(), and llvm::sampleprof::SampleProfileWriterText::writeSample().
getContextFrames()
SampleContextFrames llvm::sampleprof::SampleContext::getContextFrames () const inline
Definition at line 649 of file SampleProf.h.
Referenced by getHashCode().
getContextString()
std::string llvm::sampleprof::SampleContext::getContextString (SampleContextFrames Context, bool IncludeLeafLineLocation = false) inline static
Definition at line 651 of file SampleProf.h.
References I.
Referenced by llvm::SampleContextTracker::getContextString(), and toString().
getFunction()
FunctionId llvm::sampleprof::SampleContext::getFunction () const inline
Definition at line 648 of file SampleProf.h.
Referenced by getHashCode(), and llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles().
getHashCode()
uint64_t llvm::sampleprof::SampleContext::getHashCode () const inline
Definition at line 670 of file SampleProf.h.
References getContextFrames(), getFunction(), llvm::sampleprof::FunctionId::getHashCode(), hasContext(), and llvm::sampleprof::hash_value().
Referenced by llvm::DenseMapInfo< SampleContext >::getHashValue().
hasAttribute()
bool llvm::sampleprof::SampleContext::hasAttribute (ContextAttributeMask A) inline
Definition at line 639 of file SampleProf.h.
References A().
hasContext()
bool llvm::sampleprof::SampleContext::hasContext () const inline
Definition at line 646 of file SampleProf.h.
References llvm::sampleprof::UnknownContext.
Referenced by getHashCode(), operator<(), llvm::sampleprof::SampleProfileReaderText::readImpl(), and toString().
hasState()
bool llvm::sampleprof::SampleContext::hasState (ContextStateMask S) inline
Definition at line 643 of file SampleProf.h.
Referenced by llvm::SampleContextTracker::promoteMergeContextSamplesTree().
isBaseContext()
bool llvm::sampleprof::SampleContext::isBaseContext () const inline
Definition at line 647 of file SampleProf.h.
isPrefixOf()
bool llvm::sampleprof::SampleContext::isPrefixOf (const SampleContext & That) const inline
Definition at line 727 of file SampleProf.h.
References llvm::ArrayRef< T >::drop_back(), SampleContext(), and llvm::ArrayRef< T >::take_front().
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles().
operator SampleContextFrames()
llvm::sampleprof::SampleContext::operator SampleContextFrames () const inline
Definition at line 638 of file SampleProf.h.
operator!=()
bool llvm::sampleprof::SampleContext::operator!= (const SampleContext & That) const inline
Definition at line 696 of file SampleProf.h.
References SampleContext().
operator<()
bool llvm::sampleprof::SampleContext::operator< (const SampleContext & That) const inline
Definition at line 698 of file SampleProf.h.
References hasContext(), I, SampleContext(), and llvm::ArrayRef< T >::size().
operator==()
bool llvm::sampleprof::SampleContext::operator== (const SampleContext & That) const inline
Definition at line 691 of file SampleProf.h.
References SampleContext().
setAllAttributes()
void llvm::sampleprof::SampleContext::setAllAttributes (uint32_t A) inline
Definition at line 642 of file SampleProf.h.
References A().
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), and llvm::sampleprof::SampleProfileReaderText::readImpl().
setAttribute()
void llvm::sampleprof::SampleContext::setAttribute (ContextAttributeMask A) inline
Definition at line 640 of file SampleProf.h.
References A().
setContext()
void llvm::sampleprof::SampleContext::setContext (SampleContextFrames Context, ContextStateMask CState = RawContext) inline
Definition at line 683 of file SampleProf.h.
References assert(), llvm::sampleprof::RawContext, and llvm::sampleprof::UnknownContext.
Referenced by SampleContext(), and SampleContext().
setFunction()
void llvm::sampleprof::SampleContext::setFunction (FunctionId NewFunctionID) inline
Set the name of the function and clear the current context.
Definition at line 677 of file SampleProf.h.
References llvm::sampleprof::UnknownContext.
setState()
void llvm::sampleprof::SampleContext::setState (ContextStateMask S) inline
Definition at line 644 of file SampleProf.h.
Referenced by llvm::SampleContextTracker::getContextSamplesFor(), llvm::SampleContextTracker::markContextSamplesInlined(), and llvm::SampleContextTracker::populateFuncToCtxtMap().
toString()
std::string llvm::sampleprof::SampleContext::toString () const inline
Definition at line 664 of file SampleProf.h.
References getContextString(), and hasContext().
Referenced by llvm::sampleprof::SampleProfileWriterText::writeSample().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/SampleProf.h