LLVM: llvm::VPInterleaveBase Class Reference
llvm::VPInterleaveBase Class Reference abstract
A common base class for interleaved memory operations.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPInterleaveBase * clone () override=0
Clone the current recipe.
VPValue * getAddr () const
Return the address accessed by this recipe.
VPValue * getMask () const
Return the mask used by this recipe.
bool needsMaskForGaps () const
Return true if the access needs a mask because of the gaps.
const InterleaveGroup< Instruction > * getInterleaveGroup () const
Instruction * getInsertPos () const
void execute (VPTransformState &State) override
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Return the cost of this recipe.
bool usesFirstLaneOnly (const VPValue *Op) const override=0
Returns true if the recipe only uses the first lane of operand Op.
virtual unsigned getNumStoreOperands () const =0
Returns the number of stored operands of this interleave group.
ArrayRef< VPValue * > getStoredValues () const
Return the VPValues stored by this interleave group.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL=DebugLoc::getUnknown())
~VPRecipeBase () override=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
VPRegionBlock * getRegion ()
const VPRegionBlock * getRegion () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
bool isScalarCast () const
Return true if the recipe is a scalar cast.
void setDebugLoc (DebugLoc NewDL)
Set the recipe's debug location to NewDL.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override final
Print the recipe, delegating to printRecipe().
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPRecipeValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPRecipeValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
LLVM_ABI_FOR_TEST void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool usesFirstPartOnly (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Public Member Functions inherited from llvm::VPIRMetadata
VPIRMetadata ()=default
VPIRMetadata (Instruction &I)
Adds metatadata that can be preserved from the original instruction I.
VPIRMetadata (const VPIRMetadata &Other)=default
Copy constructor for cloning.
VPIRMetadata & operator= (const VPIRMetadata &Other)=default
void applyMetadata (Instruction &I) const
Add all metadata to I.
void setMetadata (unsigned Kind, MDNode *Node)
Set metadata with kind Kind to Node.
void intersect (const VPIRMetadata &MD)
Intersect this VPIRMetadata object with MD, keeping only metadata nodes that are common to both.
MDNode * getMetadata (unsigned Kind) const
Get metadata of kind Kind. Returns nullptr if not found.
void print (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print metadata with node IDs.
Static Public Member Functions
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Member Functions
VPInterleaveBase (const unsigned char SC, const InterleaveGroup< Instruction > *IG, ArrayRef< VPValue * > Operands, ArrayRef< VPValue * > StoredValues, VPValue *Mask, bool NeedsMaskForGaps, const VPIRMetadata &MD, DebugLoc DL)
Protected Member Functions inherited from llvm::VPRecipeBase
virtual void printRecipe (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const =0
Each concrete VPRecipe prints itself, without printing common information, like debug info or metadata.
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Detailed Description
A common base class for interleaved memory operations.
An Interleaved memory operation is a memory access method that combines multiple strided loads/stores into a single wide load/store with shuffles. The first operand is the start address. The optional operands are, in order, the stored values and the mask.
Definition at line 2573 of file VPlan.h.
Constructor & Destructor Documentation
VPInterleaveBase()
llvm::VPInterleaveBase::VPInterleaveBase (const unsigned char SC, const InterleaveGroup< Instruction > * IG, ArrayRef< VPValue * > Operands, ArrayRef< VPValue * > StoredValues, VPValue * Mask, bool NeedsMaskForGaps, const VPIRMetadata & MD, DebugLoc DL) inline protected
Definition at line 2586 of file VPlan.h.
References addOperand(), assert(), llvm::ArrayRef< T >::empty(), I, llvm::VPIRMetadata::VPIRMetadata(), and llvm::VPRecipeBase::VPRecipeBase().
Referenced by clone(), llvm::VPInterleaveEVLRecipe::VPInterleaveEVLRecipe(), and llvm::VPInterleaveRecipe::VPInterleaveRecipe().
Member Function Documentation
classof() [1/2]
bool llvm::VPInterleaveBase::classof (const VPRecipeBase * R) inline static
Definition at line 2615 of file VPlan.h.
References llvm::VPRecipeBase::VPRecipeBase().
Referenced by classof().
classof() [2/2]
bool llvm::VPInterleaveBase::classof (const VPUser * U) inline static
Definition at line 2620 of file VPlan.h.
References classof(), and llvm::dyn_cast().
clone()
VPInterleaveBase * llvm::VPInterleaveBase::clone () override pure virtual
Clone the current recipe.
Implements llvm::VPRecipeBase.
Implemented in llvm::VPInterleaveEVLRecipe, and llvm::VPInterleaveRecipe.
References VPInterleaveBase().
computeCost()
InstructionCost VPInterleaveBase::computeCost (ElementCount VF, VPCostContext & Ctx) const override virtual
Return the cost of this recipe.
Reimplemented from llvm::VPRecipeBase.
Definition at line 4238 of file VPlanRecipes.cpp.
References llvm::cast(), llvm::VectorType::get(), getAddr(), getInsertPos(), getMask(), llvm::VPDef::getNumDefinedValues(), llvm::Instruction::getOpcode(), getStoredValues(), llvm::VPDef::getVPValue(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::TargetTransformInfo::SK_Reverse, and llvm::toVectorTy().
execute()
void llvm::VPInterleaveBase::execute (VPTransformState & State) inline override virtual
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
Implements llvm::VPRecipeBase.
Reimplemented in llvm::VPInterleaveEVLRecipe, and llvm::VPInterleaveRecipe.
Definition at line 2644 of file VPlan.h.
References llvm_unreachable.
getAddr()
VPValue * llvm::VPInterleaveBase::getAddr () const inline
Return the address accessed by this recipe.
Definition at line 2626 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by llvm::VPInterleaveRecipe::clone(), computeCost(), llvm::VPInterleaveEVLRecipe::execute(), llvm::VPInterleaveRecipe::execute(), llvm::VPInterleaveEVLRecipe::printRecipe(), llvm::VPInterleaveRecipe::printRecipe(), llvm::VPInterleaveEVLRecipe::usesFirstLaneOnly(), and llvm::VPInterleaveRecipe::usesFirstLaneOnly().
getInsertPos()
Instruction * llvm::VPInterleaveBase::getInsertPos () const inline
Definition at line 2642 of file VPlan.h.
Referenced by computeCost().
getInterleaveGroup()
const InterleaveGroup< Instruction > * llvm::VPInterleaveBase::getInterleaveGroup () const inline
Definition at line 2640 of file VPlan.h.
Referenced by llvm::VPInterleaveRecipe::clone(), llvm::VPInterleaveEVLRecipe::execute(), llvm::VPInterleaveRecipe::execute(), isConsecutiveInterleaveGroup(), llvm::VPInterleaveEVLRecipe::printRecipe(), llvm::VPInterleaveRecipe::printRecipe(), and llvm::VPInterleaveEVLRecipe::VPInterleaveEVLRecipe().
getMask()
VPValue * llvm::VPInterleaveBase::getMask () const inline
Return the mask used by this recipe.
Note that a full mask is represented by a nullptr.
Definition at line 2632 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
Referenced by computeCost(), llvm::VPInterleaveEVLRecipe::execute(), llvm::VPInterleaveRecipe::execute(), isConsecutiveInterleaveGroup(), llvm::VPInterleaveEVLRecipe::printRecipe(), and llvm::VPInterleaveRecipe::printRecipe().
getNumStoreOperands()
virtual unsigned llvm::VPInterleaveBase::getNumStoreOperands () const pure virtual
Returns the number of stored operands of this interleave group.
Returns 0 for load interleave groups.
Implemented in llvm::VPInterleaveEVLRecipe, and llvm::VPInterleaveRecipe.
Referenced by getStoredValues().
getStoredValues()
ArrayRef< VPValue * > llvm::VPInterleaveBase::getStoredValues () const inline
Return the VPValues stored by this interleave group.
If it is a load interleave group, return an empty ArrayRef.
Definition at line 2661 of file VPlan.h.
References getNumStoreOperands(), and llvm::VPUser::op_end().
Referenced by llvm::VPInterleaveRecipe::clone(), computeCost(), llvm::VPInterleaveEVLRecipe::execute(), llvm::VPInterleaveRecipe::execute(), isConsecutiveInterleaveGroup(), llvm::VPInterleaveEVLRecipe::usesFirstLaneOnly(), and llvm::VPInterleaveRecipe::usesFirstLaneOnly().
needsMaskForGaps()
bool llvm::VPInterleaveBase::needsMaskForGaps () const inline
Return true if the access needs a mask because of the gaps.
Definition at line 2638 of file VPlan.h.
Referenced by llvm::VPInterleaveRecipe::clone(), llvm::VPInterleaveEVLRecipe::execute(), and llvm::VPInterleaveRecipe::execute().
usesFirstLaneOnly()
bool llvm::VPInterleaveBase::usesFirstLaneOnly (const VPValue * Op) const override pure virtual
Returns true if the recipe only uses the first lane of operand Op.
Reimplemented from llvm::VPUser.
Implemented in llvm::VPInterleaveEVLRecipe, and llvm::VPInterleaveRecipe.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp