LLVM: llvm::DiagnosticInfoSampleProfile Class Reference
llvm::DiagnosticInfoSampleProfile Class Reference
Diagnostic information for the sample profiler.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoSampleProfile (StringRef FileName, unsigned LineNum, const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity=DS_Error)
DiagnosticInfoSampleProfile (StringRef FileName, const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity=DS_Error)
DiagnosticInfoSampleProfile (const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity=DS_Error)
void print (DiagnosticPrinter &DP) const override
StringRef getFileName () const
unsigned getLineNum () const
const Twine & getMsg () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for the sample profiler.
Definition at line 263 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoSampleProfile() [1/3]
llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile (StringRef FileName, unsigned LineNum, const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity = DS_Error) inline
Definition at line 265 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_SampleProfile, llvm::DS_Error, and LLVM_LIFETIME_BOUND.
DiagnosticInfoSampleProfile() [2/3]
llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile (StringRef FileName, const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity = DS_Error) inline
Definition at line 270 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_SampleProfile, llvm::DS_Error, and LLVM_LIFETIME_BOUND.
DiagnosticInfoSampleProfile() [3/3]
llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile (const Twine &Msg LLVM_LIFETIME_BOUND, DiagnosticSeverity Severity = DS_Error) inline
Definition at line 275 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_SampleProfile, llvm::DS_Error, and LLVM_LIFETIME_BOUND.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoSampleProfile::classof (const DiagnosticInfo * DI) inline static
Definition at line 282 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_SampleProfile, and llvm::DiagnosticInfo::getKind().
getFileName()
StringRef llvm::DiagnosticInfoSampleProfile::getFileName () const inline
Definition at line 286 of file DiagnosticInfo.h.
Referenced by print().
getLineNum()
unsigned llvm::DiagnosticInfoSampleProfile::getLineNum () const inline
Definition at line 287 of file DiagnosticInfo.h.
Referenced by print().
getMsg()
const Twine & llvm::DiagnosticInfoSampleProfile::getMsg () const inline
Definition at line 288 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoSampleProfile::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 129 of file DiagnosticInfo.cpp.
References getFileName(), getLineNum(), and getMsg().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp