LLVM: llvm::orc::DumpedSymbolTable Class Reference
llvm::orc::DumpedSymbolTable Class Reference
A class for symbolicating backtraces using a previously dumped symbol table.
#include "llvm/ExecutionEngine/Orc/BacktraceTools.h"
Public Member Functions
LLVM_ABI std::string symbolicate (StringRef Backtrace)
Given a backtrace, try to symbolicate any unsymbolicated lines using the symbol addresses in the dumped symbol table.
Static Public Member Functions
static Expected< DumpedSymbolTable > Create (StringRef Path)
Create a DumpedSymbolTable from the given path.
Detailed Description
A class for symbolicating backtraces using a previously dumped symbol table.
Definition at line 74 of file BacktraceTools.h.
Member Function Documentation
Create()
Expected< DumpedSymbolTable > llvm::orc::DumpedSymbolTable::Create (StringRef Path) static
Create a DumpedSymbolTable from the given path.
Definition at line 62 of file BacktraceTools.cpp.
References llvm::createFileError(), and llvm::MemoryBuffer::getFile().
symbolicate()
std::string llvm::orc::DumpedSymbolTable::symbolicate (StringRef Backtrace)
Given a backtrace, try to symbolicate any unsymbolicated lines using the symbol addresses in the dumped symbol table.
Definition at line 110 of file BacktraceTools.cpp.
References llvm::formatv(), I, llvm::orc::Result, and llvm::StringRef::split().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/BacktraceTools.h
lib/ExecutionEngine/Orc/BacktraceTools.cpp