LLVM: llvm::DbgSSABlockSuccIterator Class Reference
llvm::DbgSSABlockSuccIterator Class Reference
Thin wrapper around a block successor iterator.
#include "llvm/Transforms/Utils/DebugSSAUpdater.h"
Public Member Functions
DbgSSABlockSuccIterator (succ_iterator SuccIt, DebugSSAUpdater &Updater)
bool operator!= (const DbgSSABlockSuccIterator &OtherIt) const
DbgSSABlockSuccIterator & operator++ ()
DbgSSABlock * operator* ()
Public Attributes
succ_iterator SuccIt
DebugSSAUpdater & Updater
Detailed Description
Thin wrapper around a block successor iterator.
Definition at line 125 of file DebugSSAUpdater.h.
Constructor & Destructor Documentation
DbgSSABlockSuccIterator()
llvm::DbgSSABlockSuccIterator::DbgSSABlockSuccIterator (succ_iterator SuccIt, DebugSSAUpdater & Updater) inline
Definition at line 130 of file DebugSSAUpdater.h.
References SuccIt, and Updater.
Referenced by operator!=(), and operator++().
Member Function Documentation
operator!=()
bool llvm::DbgSSABlockSuccIterator::operator!= (const DbgSSABlockSuccIterator & OtherIt) const inline
Definition at line 133 of file DebugSSAUpdater.h.
References DbgSSABlockSuccIterator(), and SuccIt.
operator*()
DbgSSABlock * DbgSSABlockSuccIterator::operator* ()
Definition at line 117 of file DebugSSAUpdater.cpp.
References SuccIt, and Updater.
operator++()
DbgSSABlockSuccIterator & llvm::DbgSSABlockSuccIterator::operator++ () inline
Definition at line 137 of file DebugSSAUpdater.h.
References DbgSSABlockSuccIterator(), and SuccIt.
Member Data Documentation
SuccIt
succ_iterator llvm::DbgSSABlockSuccIterator::SuccIt
Definition at line 127 of file DebugSSAUpdater.h.
Referenced by DbgSSABlockSuccIterator(), operator!=(), operator*(), and operator++().
Updater
DebugSSAUpdater& llvm::DbgSSABlockSuccIterator::Updater
Definition at line 128 of file DebugSSAUpdater.h.
Referenced by DbgSSABlockSuccIterator(), and operator*().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/DebugSSAUpdater.h
lib/Transforms/Utils/DebugSSAUpdater.cpp