LLVM: llvm::orc::LinkGraphMaterializationUnit Class Reference
llvm::orc::LinkGraphMaterializationUnit Class Reference
MaterializationUnit for wrapping LinkGraphs.
#include "llvm/ExecutionEngine/Orc/LinkGraphLayer.h"
Public Member Functions
LinkGraphMaterializationUnit (LinkGraphLayer &LGLayer, std::unique_ptr< jitlink::LinkGraph > G, Interface I)
LinkGraphMaterializationUnit (LinkGraphLayer &LGLayer, std::unique_ptr< jitlink::LinkGraph > G)
StringRef getName () const override
Return the name of this materialization unit.
void materialize (std::unique_ptr< MaterializationResponsibility > MR) override
Implementations of this method should materialize all symbols in the materialzation unit, except for those that have been previously discarded.
Public Member Functions inherited from llvm::orc::MaterializationUnit
MaterializationUnit (Interface I)
virtual ~MaterializationUnit ()=default
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
const SymbolStringPtr & getInitializerSymbol () const
Returns the initialization symbol for this MaterializationUnit (if any).
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Additional Inherited Members
Static Public Attributes inherited from llvm::orc::MaterializationUnit
static char ID
Protected Attributes inherited from llvm::orc::MaterializationUnit
SymbolFlagsMap SymbolFlags
SymbolStringPtr InitSymbol
Detailed Description
MaterializationUnit for wrapping LinkGraphs.
Definition at line 74 of file LinkGraphLayer.h.
Constructor & Destructor Documentation
LinkGraphMaterializationUnit() [1/2]
llvm::orc::LinkGraphMaterializationUnit::LinkGraphMaterializationUnit (LinkGraphLayer & LGLayer, std::unique_ptr< jitlink::LinkGraph > G, Interface I) inline
Definition at line 76 of file LinkGraphLayer.h.
References I, llvm::orc::MaterializationUnit::MaterializationUnit(), and llvm::move().
LinkGraphMaterializationUnit() [2/2]
llvm::orc::LinkGraphMaterializationUnit::LinkGraphMaterializationUnit (LinkGraphLayer & LGLayer, std::unique_ptr< jitlink::LinkGraph > G) inline
Definition at line 81 of file LinkGraphLayer.h.
References llvm::orc::MaterializationUnit::MaterializationUnit(), and llvm::move().
Member Function Documentation
getName()
StringRef llvm::orc::LinkGraphMaterializationUnit::getName () const override virtual
Return the name of this materialization unit.
Useful for debugging output.
Implements llvm::orc::MaterializationUnit.
Definition at line 92 of file LinkGraphLayer.cpp.
materialize()
void llvm::orc::LinkGraphMaterializationUnit::materialize (std::unique_ptr< MaterializationResponsibility > R) inline override virtual
Implementations of this method should materialize all symbols in the materialzation unit, except for those that have been previously discarded.
Implements llvm::orc::MaterializationUnit.
Definition at line 88 of file LinkGraphLayer.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LinkGraphLayer.h
lib/ExecutionEngine/Orc/LinkGraphLayer.cpp