LLVM: llvm::cas::ondisk::InternalRef Class Reference
llvm::cas::ondisk::InternalRef Class Reference
Standard 8 byte reference inside OnDiskGraphDB.
#include "llvm/CAS/OnDiskGraphDB.h"
Public Member Functions
FileOffset getFileOffset () const
uint64_t getRawData () const
Static Public Member Functions
static InternalRef getFromRawData (uint64_t Data)
static InternalRef getFromOffset (FileOffset Offset)
Friends
bool operator== (InternalRef LHS, InternalRef RHS)
Detailed Description
Standard 8 byte reference inside OnDiskGraphDB.
Definition at line 27 of file OnDiskGraphDB.h.
Member Function Documentation
getFileOffset()
FileOffset llvm::cas::ondisk::InternalRef::getFileOffset () const inline
Definition at line 29 of file OnDiskGraphDB.h.
getFromOffset()
InternalRef llvm::cas::ondisk::InternalRef::getFromOffset (FileOffset Offset) inline static
Definition at line 33 of file OnDiskGraphDB.h.
References llvm::Offset.
Referenced by llvm::cas::ondisk::InternalRef4B::operator InternalRef(), and llvm::cas::ondisk::OnDiskGraphDB::validate().
getFromRawData()
InternalRef llvm::cas::ondisk::InternalRef::getFromRawData (uint64_t Data) inline static
Definition at line 32 of file OnDiskGraphDB.h.
Referenced by llvm::cas::ondisk::InternalRefArrayRef::InternalRefArrayRef().
getRawData()
uint64_t llvm::cas::ondisk::InternalRef::getRawData () const inline
Definition at line 30 of file OnDiskGraphDB.h.
Friends And Related Symbol Documentation
operator==
bool operator== (InternalRef LHS, InternalRef RHS) friend
Definition at line 37 of file OnDiskGraphDB.h.
References LHS, and RHS.
The documentation for this class was generated from the following file:
include/llvm/CAS/OnDiskGraphDB.h