LLVM: llvm::symbolize::PlainPrinterBase Class Reference
llvm::symbolize::PlainPrinterBase Class Reference abstract
#include "llvm/DebugInfo/Symbolize/DIPrinter.h"
Public Member Functions
PlainPrinterBase (raw_ostream &OS, ErrorHandler EH, PrinterConfig &Config)
void print (const Request &Request, const DILineInfo &Info) override
void print (const Request &Request, const DIInliningInfo &Info) override
void print (const Request &Request, const DIGlobal &Global) override
void print (const Request &Request, const std::vector< DILocal > &Locals) override
void print (const Request &Request, const std::vector< DILineInfo > &Locations) override
bool printError (const Request &Request, const ErrorInfoBase &ErrorInfo) override
void listBegin () override
void listEnd () override
Public Member Functions inherited from llvm::symbolize::DIPrinter
DIPrinter ()=default
virtual ~DIPrinter ()=default
Protected Member Functions
void print (const DILineInfo &Info, bool Inlined)
void printFunctionName (StringRef FunctionName, bool Inlined)
virtual void printSimpleLocation (StringRef Filename, const DILineInfo &Info)=0
void printContext (SourceCode SourceCode)
void printVerbose (StringRef Filename, const DILineInfo &Info)
virtual void printStartAddress (const DILineInfo &Info)
virtual void printFooter ()
Protected Attributes
raw_ostream & OS
ErrorHandler ErrHandler
PrinterConfig Config
Detailed Description
Definition at line 71 of file DIPrinter.h.
Constructor & Destructor Documentation
PlainPrinterBase()
llvm::symbolize::PlainPrinterBase::PlainPrinterBase (raw_ostream & OS, ErrorHandler EH, PrinterConfig & Config) inline
Definition at line 90 of file DIPrinter.h.
References Config, ErrHandler, and OS.
Referenced by llvm::symbolize::GNUPrinter::GNUPrinter(), and llvm::symbolize::LLVMPrinter::LLVMPrinter().
Member Function Documentation
listBegin()
void llvm::symbolize::PlainPrinterBase::listBegin () inline override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 104 of file DIPrinter.h.
listEnd()
void llvm::symbolize::PlainPrinterBase::listEnd () inline override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 105 of file DIPrinter.h.
print() [1/6]
void llvm::symbolize::PlainPrinterBase::print (const DILineInfo & Info, bool Inlined) protected
Definition at line 180 of file DIPrinter.cpp.
References llvm::DILineInfo::Addr2LineBadString, llvm::DILineInfo::BadString, Config, Info, printFunctionName(), printSimpleLocation(), and printVerbose().
Referenced by print(), print(), and print().
print() [2/6]
void llvm::symbolize::PlainPrinterBase::print (const Request & Request, const DIGlobal & Global) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 209 of file DIPrinter.cpp.
References llvm::DILineInfo::Addr2LineBadString, llvm::symbolize::Request::Address, llvm::DILineInfo::BadString, llvm::Global, OS, and printFooter().
print() [3/6]
void llvm::symbolize::PlainPrinterBase::print (const Request & Request, const DIInliningInfo & Info) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 197 of file DIPrinter.cpp.
References llvm::symbolize::Request::Address, I, Info, print(), and printFooter().
print() [4/6]
void llvm::symbolize::PlainPrinterBase::print (const Request & Request, const DILineInfo & Info) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 191 of file DIPrinter.cpp.
References llvm::symbolize::Request::Address, Info, print(), and printFooter().
print() [5/6]
void llvm::symbolize::PlainPrinterBase::print (const Request & Request, const std::vector< DILineInfo > & Locations) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 270 of file DIPrinter.cpp.
References print(), and printFooter().
print() [6/6]
void llvm::symbolize::PlainPrinterBase::print (const Request & Request, const std::vector< DILocal > & Locals) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 223 of file DIPrinter.cpp.
References llvm::DILineInfo::Addr2LineBadString, llvm::symbolize::Request::Address, OS, and printFooter().
printContext()
void llvm::symbolize::PlainPrinterBase::printContext (SourceCode SourceCode) protected
Definition at line 118 of file DIPrinter.cpp.
References llvm::symbolize::SourceCode::format(), and OS.
Referenced by printSimpleLocation().
printError()
bool llvm::symbolize::PlainPrinterBase::printError (const Request & Request, const ErrorInfoBase & ErrorInfo) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 281 of file DIPrinter.cpp.
References ErrHandler, and llvm::symbolize::Request::ModuleName.
printFooter()
virtual void llvm::symbolize::PlainPrinterBase::printFooter () inline protected virtual
Definition at line 84 of file DIPrinter.h.
Referenced by print(), print(), print(), print(), and print().
printFunctionName()
void llvm::symbolize::PlainPrinterBase::printFunctionName (StringRef FunctionName, bool Inlined) protected
Definition at line 122 of file DIPrinter.cpp.
References llvm::DILineInfo::Addr2LineBadString, llvm::DILineInfo::BadString, Config, and OS.
Referenced by print().
printSimpleLocation()
virtual void llvm::symbolize::PlainPrinterBase::printSimpleLocation (StringRef Filename, const DILineInfo & Info) protected pure virtual
References Info, printContext(), and printVerbose().
Referenced by print().
printStartAddress()
virtual void llvm::symbolize::PlainPrinterBase::printStartAddress (const DILineInfo & Info) inline protected virtual
Definition at line 83 of file DIPrinter.h.
References Info.
Referenced by printVerbose().
printVerbose()
void llvm::symbolize::PlainPrinterBase::printVerbose (StringRef Filename, const DILineInfo & Info) protected
Definition at line 154 of file DIPrinter.cpp.
References Info, OS, and printStartAddress().
Referenced by print(), and printSimpleLocation().
Member Data Documentation
Config
PrinterConfig llvm::symbolize::PlainPrinterBase::Config protected
Definition at line 75 of file DIPrinter.h.
Referenced by llvm::symbolize::GNUPrinter::GNUPrinter(), llvm::symbolize::LLVMPrinter::LLVMPrinter(), PlainPrinterBase(), print(), and printFunctionName().
ErrHandler
ErrorHandler llvm::symbolize::PlainPrinterBase::ErrHandler protected
Definition at line 74 of file DIPrinter.h.
Referenced by PlainPrinterBase(), and printError().
OS
raw_ostream& llvm::symbolize::PlainPrinterBase::OS protected
Definition at line 73 of file DIPrinter.h.
Referenced by llvm::symbolize::GNUPrinter::GNUPrinter(), llvm::symbolize::LLVMPrinter::LLVMPrinter(), PlainPrinterBase(), print(), print(), printContext(), printFunctionName(), and printVerbose().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/DIPrinter.h
lib/DebugInfo/Symbolize/DIPrinter.cpp