LLVM: llvm::GVNExpression::op_inserter Class Reference
llvm::GVNExpression::op_inserter Class Reference
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Types
using iterator_category = std::output_iterator_tag
using value_type = void
using difference_type = void
using pointer = void
using reference = void
Public Member Functions
op_inserter (BasicExpression &E)
op_inserter (BasicExpression *E)
op_inserter & operator= (Value *val)
op_inserter & operator* ()
op_inserter & operator++ ()
op_inserter & operator++ (int)
Detailed Description
Definition at line 243 of file GVNExpression.h.
Member Typedef Documentation
difference_type
using llvm::GVNExpression::op_inserter::difference_type = void
Definition at line 252 of file GVNExpression.h.
iterator_category
using llvm::GVNExpression::op_inserter::iterator_category = std::output_iterator_tag
Definition at line 250 of file GVNExpression.h.
pointer
using llvm::GVNExpression::op_inserter::pointer = void
Definition at line 253 of file GVNExpression.h.
reference
using llvm::GVNExpression::op_inserter::reference = void
Definition at line 254 of file GVNExpression.h.
value_type
using llvm::GVNExpression::op_inserter::value_type = void
Definition at line 251 of file GVNExpression.h.
Constructor & Destructor Documentation
op_inserter() [1/2]
llvm::GVNExpression::op_inserter::op_inserter (BasicExpression & E) inline explicit
Definition at line 256 of file GVNExpression.h.
References E().
Referenced by operator*(), operator++(), operator++(), and operator=().
op_inserter() [2/2]
llvm::GVNExpression::op_inserter::op_inserter (BasicExpression * E) inline explicit
Definition at line 257 of file GVNExpression.h.
References E().
Member Function Documentation
operator*()
op_inserter & llvm::GVNExpression::op_inserter::operator* () inline
Definition at line 263 of file GVNExpression.h.
References op_inserter().
operator++() [1/2]
op_inserter & llvm::GVNExpression::op_inserter::operator++ () inline
Definition at line 264 of file GVNExpression.h.
References op_inserter().
operator++() [2/2]
op_inserter & llvm::GVNExpression::op_inserter::operator++ (int) inline
Definition at line 265 of file GVNExpression.h.
References op_inserter().
operator=()
op_inserter & llvm::GVNExpression::op_inserter::operator= (Value * val) inline
Definition at line 259 of file GVNExpression.h.
References op_inserter().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Scalar/GVNExpression.h