LLVM: llvm::sandboxir::MemDGNodeIntervalBuilder Class Reference
llvm::sandboxir::MemDGNodeIntervalBuilder Class Reference
Convenience builders for a MemDGNode interval.
#include "llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h"
Static Public Member Functions
static LLVM_ABI MemDGNode * getTopMemDGNode (const Interval< Instruction > &Intvl, const DependencyGraph &DAG)
Scans the instruction chain in Intvl top-down, returning the top-most MemDGNode, or nullptr.
static LLVM_ABI MemDGNode * getBotMemDGNode (const Interval< Instruction > &Intvl, const DependencyGraph &DAG)
Scans the instruction chain in Intvl bottom-up, returning the bottom-most MemDGNode, or nullptr.
static LLVM_ABI Interval< MemDGNode > make (const Interval< Instruction > &Instrs, DependencyGraph &DAG)
Given Instrs it finds their closest mem nodes in the interval and returns the corresponding mem range.
static Interval< MemDGNode > makeEmpty ()
Detailed Description
Convenience builders for a MemDGNode interval.
Definition at line 313 of file DependencyGraph.h.
Member Function Documentation
getBotMemDGNode()
MemDGNode * llvm::sandboxir::MemDGNodeIntervalBuilder::getBotMemDGNode (const Interval< Instruction > & Intvl, const DependencyGraph & DAG) static
Scans the instruction chain in Intvl bottom-up, returning the bottom-most MemDGNode, or nullptr.
Definition at line 116 of file DependencyGraph.cpp.
References llvm::sandboxir::Interval< T >::bottom(), llvm::cast(), llvm::sandboxir::DependencyGraph::getNode(), I, llvm::sandboxir::DGNode::isMemDepNodeCandidate(), and llvm::sandboxir::Interval< T >::top().
Referenced by make().
getTopMemDGNode()
MemDGNode * llvm::sandboxir::MemDGNodeIntervalBuilder::getTopMemDGNode (const Interval< Instruction > & Intvl, const DependencyGraph & DAG) static
Scans the instruction chain in Intvl top-down, returning the top-most MemDGNode, or nullptr.
Definition at line 103 of file DependencyGraph.cpp.
References llvm::sandboxir::Interval< T >::bottom(), llvm::cast(), llvm::sandboxir::DependencyGraph::getNode(), I, llvm::sandboxir::DGNode::isMemDepNodeCandidate(), and llvm::sandboxir::Interval< T >::top().
Referenced by make().
make()
Interval< MemDGNode > llvm::sandboxir::MemDGNodeIntervalBuilder::make (const Interval< Instruction > & Instrs, DependencyGraph & DAG) static
Given Instrs it finds their closest mem nodes in the interval and returns the corresponding mem range.
Note: BotN (or its neighboring mem node) is included in the range.
Definition at line 129 of file DependencyGraph.cpp.
References assert(), llvm::sandboxir::Interval< T >::empty(), getBotMemDGNode(), getTopMemDGNode(), and llvm::sandboxir::Interval< MemDGNode >.
Referenced by llvm::sandboxir::DependencyGraph::extend().
makeEmpty()
Interval< MemDGNode > llvm::sandboxir::MemDGNodeIntervalBuilder::makeEmpty () inline static
Definition at line 328 of file DependencyGraph.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h
lib/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.cpp