LLVM: llvm::CodeGenDataWriter Class Reference
llvm::CodeGenDataWriter Class Reference
#include "llvm/CGData/CodeGenDataWriter.h"
Public Member Functions
CodeGenDataWriter ()=default
~CodeGenDataWriter ()=default
LLVM_ABI void addRecord (OutlinedHashTreeRecord &Record)
Add the outlined hash tree record. The input hash tree is released.
LLVM_ABI void addRecord (StableFunctionMapRecord &Record)
Add the stable function map record. The input function map is released.
LLVM_ABI Error write (raw_fd_ostream &OS)
Write the codegen data to OS.
LLVM_ABI Error writeText (raw_fd_ostream &OS)
Write the codegen data in text format to OS.
CGDataKind getCGDataKind () const
Return the attributes of the current CGData.
bool hasOutlinedHashTree () const
Return true if the header indicates the data has an outlined hash tree.
bool hasStableFunctionMap () const
Return true if the header indicates the data has a stable function map.
Detailed Description
Definition at line 59 of file CodeGenDataWriter.h.
Constructor & Destructor Documentation
CodeGenDataWriter()
llvm::CodeGenDataWriter::CodeGenDataWriter () default
~CodeGenDataWriter()
llvm::CodeGenDataWriter::~CodeGenDataWriter () default
References LLVM_ABI.
Member Function Documentation
addRecord() [1/2]
void CodeGenDataWriter::addRecord (OutlinedHashTreeRecord & Record)
Add the outlined hash tree record. The input hash tree is released.
Definition at line 65 of file CodeGenDataWriter.cpp.
References assert(), and llvm::FunctionOutlinedHashTree.
addRecord() [2/2]
void CodeGenDataWriter::addRecord (StableFunctionMapRecord & Record)
Add the stable function map record. The input function map is released.
Definition at line 72 of file CodeGenDataWriter.cpp.
References assert(), and llvm::StableFunctionMergingMap.
getCGDataKind()
CGDataKind llvm::CodeGenDataWriter::getCGDataKind () const inline
Return the attributes of the current CGData.
Definition at line 86 of file CodeGenDataWriter.h.
hasOutlinedHashTree()
bool llvm::CodeGenDataWriter::hasOutlinedHashTree () const inline
Return true if the header indicates the data has an outlined hash tree.
Definition at line 89 of file CodeGenDataWriter.h.
References llvm::FunctionOutlinedHashTree.
Referenced by writeText().
hasStableFunctionMap()
bool llvm::CodeGenDataWriter::hasStableFunctionMap () const inline
Return true if the header indicates the data has a stable function map.
Definition at line 94 of file CodeGenDataWriter.h.
References llvm::StableFunctionMergingMap.
Referenced by writeText().
write()
Error CodeGenDataWriter::write (raw_fd_ostream & OS)
Write the codegen data to OS.
Definition at line 79 of file CodeGenDataWriter.cpp.
writeText()
Error CodeGenDataWriter::writeText (raw_fd_ostream & OS)
Write the codegen data in text format to OS.
Definition at line 157 of file CodeGenDataWriter.cpp.
References hasOutlinedHashTree(), hasStableFunctionMap(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/CGData/CodeGenDataWriter.h
lib/CGData/CodeGenDataWriter.cpp