LLVM: llvm::SMTSolverStatistics Class Reference
llvm::SMTSolverStatistics Class Reference abstract
#include "llvm/Support/SMTAPI.h"
Public Member Functions
SMTSolverStatistics ()=default
virtual ~SMTSolverStatistics ()=default
virtual double getDouble (llvm::StringRef) const =0
virtual unsigned getUnsigned (llvm::StringRef) const =0
virtual void print (raw_ostream &OS) const =0
LLVM_DUMP_METHOD void dump () const
Detailed Description
Definition at line 133 of file SMTAPI.h.
Constructor & Destructor Documentation
SMTSolverStatistics()
llvm::SMTSolverStatistics::SMTSolverStatistics () default
~SMTSolverStatistics()
virtual llvm::SMTSolverStatistics::~SMTSolverStatistics () virtual default
Member Function Documentation
dump()
LLVM_DUMP_METHOD void SMTSolverStatistics::dump () const
Definition at line 997 of file Z3Solver.cpp.
References llvm::errs(), LLVM_DUMP_METHOD, and print().
getDouble()
virtual double llvm::SMTSolverStatistics::getDouble (llvm::StringRef) const pure virtual
getUnsigned()
virtual unsigned llvm::SMTSolverStatistics::getUnsigned (llvm::StringRef) const pure virtual
print()
virtual void llvm::SMTSolverStatistics::print (raw_ostream & OS) const pure virtual
References LLVM_DUMP_METHOD.
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/Support/SMTAPI.h
lib/Support/Z3Solver.cpp