LLVM: llvm::PointerType Class Reference
llvm::PointerType Class Reference
Class to represent pointers.
#include "llvm/IR/DerivedTypes.h"
Public Member Functions
PointerType (const PointerType &)=delete
PointerType & operator= (const PointerType &)=delete
unsigned getAddressSpace () const
Return the address space of the Pointer type.
Public Member Functions inherited from llvm::Type
LLVM_ABI void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
LLVM_ABI void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isBFloatTy () const
Return true if this is 'bfloat', a 16-bit bfloat type.
bool is16bitFPTy () const
Return true if this is a 16-bit float type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isIEEELikeFPTy () const
Return true if this is a well-behaved IEEE-like type, which has a IEEE compatible layout, and does not have non-IEEE values, such as x86_fp80's unnormal values.
bool isFloatingPointTy () const
Return true if this is one of the floating-point types.
bool isMultiUnitFPType () const
Returns true if this is a floating-point type that is an unevaluated sum of multiple floating-point units.
LLVM_ABI const fltSemantics & getFltSemantics () const
bool isX86_AMXTy () const
Return true if this is X86 AMX.
bool isTargetExtTy () const
Return true if this is a target extension type.
LLVM_ABI bool isScalableTargetExtTy () const
Return true if this is a target extension type with a scalable layout.
LLVM_ABI bool isScalableTy (SmallPtrSetImpl< const Type * > &Visited) const
Return true if this is a type whose size is a known multiple of vscale.
LLVM_ABI bool isScalableTy () const
LLVM_ABI bool containsNonGlobalTargetExtType (SmallPtrSetImpl< const Type * > &Visited) const
Return true if this type is or contains a target extension type that disallows being used as a global.
LLVM_ABI bool containsNonGlobalTargetExtType () const
LLVM_ABI bool containsNonLocalTargetExtType (SmallPtrSetImpl< const Type * > &Visited) const
Return true if this type is or contains a target extension type that disallows being used as a local.
LLVM_ABI bool containsNonLocalTargetExtType () const
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isTokenLikeTy () const
Returns true if this is 'token' or a token-like target type.s.
bool isIntegerTy () const
True if this is an instance of IntegerType.
LLVM_ABI bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
LLVM_ABI bool isRISCVVectorTupleTy () const
LLVM_ABI bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
LLVM_ABI bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
LLVM_ABI bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
LLVM_ABI TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
LLVM_ABI unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
LLVM_ABI int getFPMantissaWidth () const
Return the width of the mantissa of this type.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
LLVM_ABI unsigned getIntegerBitWidth () const
LLVM_ABI Type * getFunctionParamType (unsigned i) const
LLVM_ABI unsigned getFunctionNumParams () const
LLVM_ABI bool isFunctionVarArg () const
LLVM_ABI StringRef getStructName () const
LLVM_ABI unsigned getStructNumElements () const
LLVM_ABI Type * getStructElementType (unsigned N) const
LLVM_ABI uint64_t getArrayNumElements () const
Type * getArrayElementType () const
LLVM_ABI StringRef getTargetExtName () const
LLVM_ABI Type * getWithNewType (Type *EltTy) const
Given vector type, change the element type, whilst keeping the old number of elements.
LLVM_ABI Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
LLVM_ABI Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
LLVM_ABI unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
LLVM_ABI LLVM_DEPRECATED ("Use PointerType::get instead", "PointerType::get") PointerType *getPointerTo(unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static LLVM_ABI PointerType * get (Type *ElementType, unsigned AddressSpace)
This constructs a pointer to an object of the specified type in a numbered address space.
static LLVM_ABI PointerType * get (LLVMContext &C, unsigned AddressSpace)
This constructs an opaque pointer to an object in a numbered address space.
static PointerType * getUnqual (Type *ElementType)
This constructs a pointer to an object of the specified type in the default address space (address space zero).
static PointerType * getUnqual (LLVMContext &C)
This constructs an opaque pointer to an object in the default address space (address space zero).
static LLVM_ABI bool isValidElementType (Type *ElemTy)
Return true if the specified type is valid as a element type.
static LLVM_ABI bool isLoadableOrStorableType (Type *ElemTy)
Return true if we can load or store from a pointer to this type.
static bool classof (const Type *T)
Implement support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static LLVM_ABI Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static LLVM_ABI Type * getVoidTy (LLVMContext &C)
static LLVM_ABI Type * getLabelTy (LLVMContext &C)
static LLVM_ABI Type * getHalfTy (LLVMContext &C)
static LLVM_ABI Type * getBFloatTy (LLVMContext &C)
static LLVM_ABI Type * getFloatTy (LLVMContext &C)
static LLVM_ABI Type * getDoubleTy (LLVMContext &C)
static LLVM_ABI Type * getMetadataTy (LLVMContext &C)
static LLVM_ABI Type * getX86_FP80Ty (LLVMContext &C)
static LLVM_ABI Type * getFP128Ty (LLVMContext &C)
static LLVM_ABI Type * getPPC_FP128Ty (LLVMContext &C)
static LLVM_ABI Type * getX86_AMXTy (LLVMContext &C)
static LLVM_ABI Type * getTokenTy (LLVMContext &C)
static LLVM_ABI IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static LLVM_ABI IntegerType * getInt1Ty (LLVMContext &C)
static LLVM_ABI IntegerType * getInt8Ty (LLVMContext &C)
static LLVM_ABI IntegerType * getInt16Ty (LLVMContext &C)
static LLVM_ABI IntegerType * getInt32Ty (LLVMContext &C)
static LLVM_ABI IntegerType * getInt64Ty (LLVMContext &C)
static LLVM_ABI IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy>
static Type * getScalarTy (LLVMContext &C)
static LLVM_ABI Type * getFloatingPointTy (LLVMContext &C, const fltSemantics &S)
static LLVM_ABI Type * getWasm_ExternrefTy (LLVMContext &C)
static LLVM_ABI Type * getWasm_FuncrefTy (LLVMContext &C)
Additional Inherited Members
Public Types inherited from llvm::Type
enum TypeID {
HalfTyID = 0 , BFloatTyID , FloatTyID , DoubleTyID ,
X86_FP80TyID , FP128TyID , PPC_FP128TyID , VoidTyID ,
LabelTyID , MetadataTyID , X86_AMXTyID , TokenTyID ,
IntegerTyID , FunctionTyID , PointerTyID , StructTyID ,
ArrayTyID , FixedVectorTyID , ScalableVectorTyID , TypedPointerTyID ,
TargetExtTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type * const *
using subtype_reverse_iterator = std::reverse_iterator<subtype_iterator>
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Detailed Description
Class to represent pointers.
Definition at line 702 of file DerivedTypes.h.
Constructor & Destructor Documentation
PointerType()
llvm::PointerType::PointerType (const PointerType &) delete
Member Function Documentation
classof()
bool llvm::PointerType::classof (const Type * T) inline static
Implement support type inquiry through isa, cast, and dyn_cast.
Definition at line 745 of file DerivedTypes.h.
References llvm::Type::PointerTyID, T, and llvm::Type::Type().
get() [1/2]
PointerType * PointerType::get (LLVMContext & C, unsigned AddressSpace) static
This constructs an opaque pointer to an object in a numbered address space.
Definition at line 854 of file Type.cpp.
get() [2/2]
LLVM_ABI PointerType * llvm::PointerType::get (Type * ElementType, unsigned AddressSpace) static
This constructs a pointer to an object of the specified type in a numbered address space.
References llvm::CallingConv::C, LLVM_ABI, and llvm::Type::Type().
Referenced by appendToGlobalArray(), buildTargetLegalPtr(), convertScratchAtomicToFlatAtomic(), convertToParamAS(), createAtomicLibcall(), CreateGCRelocates(), llvm::orc::createIRTypedAddress(), llvm::createMemLibcall(), llvm::OpenMPIRBuilder::createReductionsGPU(), llvm::createSanitizerCtorAndInitFunctions(), DecodeFixedType(), llvm::SITargetLowering::emitExpandAtomicAddrSpacePredicate(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), expandBounds(), expandProtectedFieldPtr(), findExtractedOutputToOverallOutputMapping(), llvm::sandboxir::PointerType::get(), llvm::DataLayout::getAllocaPtrType(), llvm::SelectionDAG::getEVTAlign(), llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy(), getIndirectionGlobal(), getIntrinsicParamType(), llvm::TargetLoweringBase::getIRStackGuard(), getOrCreateRefVariable(), llvm::getOrCreateSPIRVDeviceEventPointer(), getPtrOrVecOfPtrsWithNewAS(), llvm::IRBuilderBase::getPtrTy(), GetTLSADDR(), getUnqual(), hasLifetimeMarkers(), INITIALIZE_PASS(), llvm::CallLowering::insertSRetIncomingArgument(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetOutgoingArgument(), llvm::AMDGPU::instrumentAddressImpl(), llvm::coro::Shape::invalidateCoroutine(), isValidProtoForSizeReturningNew(), LLVMPointerType(), LLVMPointerTypeInContext(), llvm::TargetLowering::LowerCallTo(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), markPointerAsAS(), llvm::RandomIRBuilder::newSink(), llvm::coro::replaceCoroFree(), reportInvalidTensormapReplaceUsage(), llvm::SPIRVTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::WasmEHPreparePass::run(), llvm::ExecutionEngine::runFunctionAsMain(), runImpl(), setUsedInitializer(), simplifyX86MaskedStore(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getAddressSpace()
unsigned llvm::PointerType::getAddressSpace () const inline
Return the address space of the Pointer type.
Definition at line 742 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by llvm::MachineIRBuilder::buildGlobalValue(), llvm::CastInst::castIsValid(), llvm::orc::cloneGlobalVariableDecl(), llvm::FunctionComparator::cmpConstants(), llvm::FunctionComparator::cmpTypes(), llvm::convertToDeclaration(), llvm::LoongArchTargetLowering::emitExpandAtomicRMW(), llvm::AllocaInst::getAddressSpace(), llvm::GlobalAddressSDNode::getAddressSpace(), llvm::GlobalValue::getAddressSpace(), llvm::getAttributeBasedInliningDecision(), llvm::getCallsiteCost(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::isLegalToPromote(), llvm::DataLayout::isNonIntegralPointerType(), isUnmergeableGlobal(), processInternalGlobal(), TryToShrinkGlobalToBoolean(), and llvm::ObjectSizeOffsetVisitor::visitConstantPointerNull().
getUnqual() [1/2]
PointerType * llvm::PointerType::getUnqual (LLVMContext & C) inline static
This constructs an opaque pointer to an object in the default address space (address space zero).
Definition at line 731 of file DerivedTypes.h.
References llvm::CallingConv::C, and get().
getUnqual() [2/2]
PointerType * llvm::PointerType::getUnqual (Type * ElementType) inline static
This constructs a pointer to an object of the specified type in the default address space (address space zero).
Definition at line 722 of file DerivedTypes.h.
References assert(), getUnqual(), isValidElementType(), and llvm::Type::Type().
Referenced by addEmuTlsVar(), llvm::orc::ReOptimizeLayer::addOrcRTLiteSupport(), llvm::fuzzerop::anyPtrType(), appendToUsedList(), aspaceWrapValue(), buildFrameType(), llvm::CoroIdInst::clearPromise(), convertMetadataToAssumes(), llvm::coro::BaseCloner::create(), llvm::InlineAsmKeyType::create(), CreateFailBB(), llvm::IRBuilderBase::CreateFree(), llvm::IRBuilderBase::CreateMalloc(), llvm::InstCombinerImpl::CreateNonTerminatorUnreachable(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), llvm::OpenMPIRBuilder::createOffloadMapnames(), llvm::OpenMPIRBuilder::createOMPInteropDestroy(), llvm::OpenMPIRBuilder::createOMPInteropInit(), llvm::OpenMPIRBuilder::createOMPInteropUse(), createOutlinedFunction(), CreatePrologue(), llvm::coro::BaseCloner::deriveNewFramePointer(), llvm::AsmPrinter::doFinalization(), eliminateSwiftErrorArgument(), llvm::embedBitcodeInModule(), llvm::orc::IRSpeculationLayer::emit(), llvm::AtomicInfo::EmitAtomicLoadLibcall(), llvm::AtomicInfo::EmitAtomicStoreLibcall(), llvm::OpenMPIRBuilder::emitMapperCall(), llvm::OpenMPIRBuilder::emitOffloadingArrays(), llvm::OpenMPIRBuilder::emitOffloadingArraysArgument(), emitSMEStateSaveRestore(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), llvm::OpenMPIRBuilder::emitTargetTask(), llvm::TargetLowering::expandMultipleResultFPLibCall(), llvm::CodeExtractor::findAllocas(), llvm::SanitizerStatReport::finish(), llvm::InlineAsm::get(), getAddrPtrType(), llvm::ConstantExpr::getAlignOf(), llvm::ScalarEvolution::getElementSize(), llvm::offloading::getEntryTy(), getFreshReductionFunc(), getFuncAddrForProfData(), getHandleType(), getIntrinsicParamType(), llvm::SelectionDAG::getMemcmp(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::offloading::getOffloadingEntryInitializer(), llvm::coro::Shape::getResumeFunctionType(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), llvm::OpenMPIRBuilder::getSizeInBytes(), llvm::ConstantExpr::getSizeOf(), llvm::SelectionDAG::getStrcpy(), llvm::SelectionDAG::getStrlen(), getUnqual(), getVTableAddrForProfData(), insertCall(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::TargetLoweringBase::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), loadSharedDataFromTaskDescriptor(), lowerAwaitSuspend(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::needToDelay(), llvm::EscapeEnumerator::Next(), replaceAsyncResumeFunction(), runImpl(), llvm::SanitizerStatReport::SanitizerStatReport(), llvm::fuzzerop::sizedPtrType(), and llvm::coro::AsyncABI::splitCoroutine().
isLoadableOrStorableType()
bool PointerType::isLoadableOrStorableType (Type * ElemTy) static
Return true if we can load or store from a pointer to this type.
Definition at line 881 of file Type.cpp.
isValidElementType()
bool PointerType::isValidElementType (Type * ElemTy) static
Return true if the specified type is valid as a element type.
Definition at line 875 of file Type.cpp.
Referenced by getUnqual(), and llvm::GlobalVariable::GlobalVariable().
operator=()
PointerType & llvm::PointerType::operator= (const PointerType &) delete
The documentation for this class was generated from the following files:
include/llvm/IR/DerivedTypes.h
lib/SandboxIR/Type.cpp