LLVM: llvm::object::SFrameParser< E > Class Template Reference
llvm::object::SFrameParser< E > Class Template Reference
#include "llvm/Object/SFrameParser.h"
Classes
struct FrameRowEntry
class FallibleFREIterator
Public Types
using FDERange = ArrayRef<sframe::FuncDescEntry<E>>
using fre_iterator = fallible_iterator<FallibleFREIterator>
Public Member Functions
const sframe::Preamble< E > & getPreamble () const
const sframe::Header< E > & getHeader () const
Expected< ArrayRef< uint8_t > > getAuxHeader () const
bool usesFixedRAOffset () const
bool usesFixedFPOffset () const
Expected< FDERange > fdes () const
uint64_t getAbsoluteStartAddress (typename FDERange::iterator FDE) const
uint64_t offsetOf (typename FDERange::iterator FDE) const
iterator_range< fre_iterator > fres (const sframe::FuncDescEntry< E > &FDE, Error &Err) const
std::optional< int32_t > getCFAOffset (const FrameRowEntry &FRE) const
std::optional< int32_t > getRAOffset (const FrameRowEntry &FRE) const
std::optional< int32_t > getFPOffset (const FrameRowEntry &FRE) const
ArrayRef< int32_t > getExtraOffsets (const FrameRowEntry &FRE) const
Static Public Member Functions
static Expected< SFrameParser > create (ArrayRef< uint8_t > Contents, uint64_t SectionAddress)
Detailed Description
template<endianness E>
class llvm::object::SFrameParser< E >
Definition at line 22 of file SFrameParser.h.
Member Typedef Documentation
FDERange
template<endianness E> using llvm::object::SFrameParser< E >::FDERange = ArrayRef<sframe::FuncDescEntry<E>>
Definition at line 41 of file SFrameParser.h.
fre_iterator
template<endianness E> using llvm::object::SFrameParser< E >::fre_iterator = fallible_iterator<FallibleFREIterator>
Definition at line 58 of file SFrameParser.h.
Member Function Documentation
create()
template<endianness E> Expected< SFrameParser< E > > SFrameParser::create (ArrayRef< uint8_t > Contents, uint64_t SectionAddress) static
Definition at line 57 of file SFrameParser.cpp.
References llvm::object::createError(), llvm::formatv(), getDataSliceAs(), llvm::sframe::Magic, and llvm::Expected< T >::takeError().
fdes()
template<endianness E> Expected< ArrayRef< sframe::FuncDescEntry< E > > > SFrameParser::fdes () const
Definition at line 85 of file SFrameParser.cpp.
References llvm::ArrayRef(), and getDataSlice().
fres()
template<endianness E> iterator_range< typename SFrameParser< E >::fre_iterator > SFrameParser::fres (const sframe::FuncDescEntry< E > & FDE, Error & Err) const
Definition at line 176 of file SFrameParser.cpp.
References llvm::sframe::FuncDescEntry< E >::Info, llvm::make_fallible_end(), llvm::make_fallible_itr(), llvm::sframe::FuncDescEntry< E >::NumFREs, llvm::Offset, and llvm::sframe::FuncDescEntry< E >::StartFREOff.
getAbsoluteStartAddress()
template<endianness E> uint64_t SFrameParser::getAbsoluteStartAddress (typename FDERange::iterator FDE) const
Definition at line 96 of file SFrameParser.cpp.
References getPreamble(), and offsetOf().
getAuxHeader()
template<endianness E> Expected< ArrayRef< uint8_t > > SFrameParser::getAuxHeader () const
Definition at line 80 of file SFrameParser.cpp.
References getDataSlice().
getCFAOffset()
template<endianness E> std::optional< int32_t > SFrameParser::getCFAOffset (const FrameRowEntry & FRE) const
Definition at line 198 of file SFrameParser.cpp.
References llvm::getOffset(), and llvm::object::SFrameParser< E >::FrameRowEntry::Offsets.
getExtraOffsets()
template<endianness E> ArrayRef< int32_t > SFrameParser::getExtraOffsets (const FrameRowEntry & FRE) const
Definition at line 220 of file SFrameParser.cpp.
References llvm::ArrayRef(), llvm::object::SFrameParser< E >::FrameRowEntry::Offsets, llvm::SmallVectorTemplateCommon< T, typename >::size(), usesFixedFPOffset(), and usesFixedRAOffset().
getFPOffset()
template<endianness E> std::optional< int32_t > SFrameParser::getFPOffset (const FrameRowEntry & FRE) const
Definition at line 212 of file SFrameParser.cpp.
References llvm::getOffset(), llvm::object::SFrameParser< E >::FrameRowEntry::Offsets, usesFixedFPOffset(), and usesFixedRAOffset().
getHeader()
template<endianness E> const sframe::Header< E > & llvm::object::SFrameParser< E >::getHeader () const inline
Definition at line 30 of file SFrameParser.h.
Referenced by usesFixedRAOffset().
getPreamble()
template<endianness E> const sframe::Preamble< E > & llvm::object::SFrameParser< E >::getPreamble () const inline
Definition at line 29 of file SFrameParser.h.
Referenced by getAbsoluteStartAddress().
getRAOffset()
template<endianness E> std::optional< int32_t > SFrameParser::getRAOffset (const FrameRowEntry & FRE) const
Definition at line 204 of file SFrameParser.cpp.
References llvm::getOffset(), llvm::object::SFrameParser< E >::FrameRowEntry::Offsets, and usesFixedRAOffset().
offsetOf()
template<endianness E> uint64_t SFrameParser::offsetOf (typename FDERange::iterator FDE) const
Definition at line 108 of file SFrameParser.cpp.
References assert().
Referenced by getAbsoluteStartAddress().
usesFixedFPOffset()
template<endianness E> bool llvm::object::SFrameParser< E >::usesFixedFPOffset () const inline
Definition at line 37 of file SFrameParser.h.
Referenced by getExtraOffsets(), and getFPOffset().
usesFixedRAOffset()
template<endianness E> bool llvm::object::SFrameParser< E >::usesFixedRAOffset () const inline
Definition at line 34 of file SFrameParser.h.
References getHeader().
Referenced by getExtraOffsets(), getFPOffset(), and getRAOffset().
The documentation for this class was generated from the following files:
include/llvm/Object/SFrameParser.h
lib/Object/SFrameParser.cpp