LLVM: llvm::jitlink::systemz::PLTTableManager Class Reference
llvm::jitlink::systemz::PLTTableManager Class Reference
Procedure Linkage Table Builder.
#include "llvm/ExecutionEngine/JITLink/systemz.h"
Public Member Functions
PLTTableManager (GOTTableManager &GOT)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Section & getStubsSection (LinkGraph &G)
Public Member Functions inherited from llvm::jitlink::TableManager< PLTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Public Attributes
GOTTableManager & GOT
Section * StubsSection = nullptr
Detailed Description
Procedure Linkage Table Builder.
Definition at line 883 of file systemz.h.
Constructor & Destructor Documentation
PLTTableManager()
llvm::jitlink::systemz::PLTTableManager::PLTTableManager (GOTTableManager & GOT) inline
Definition at line 885 of file systemz.h.
References GOT.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::systemz::PLTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 916 of file systemz.h.
References llvm::jitlink::systemz::createAnonymousPointerJumpStub(), G, getStubsSection(), and GOT.
getSectionName()
StringRef llvm::jitlink::systemz::PLTTableManager::getSectionName () inline static
Definition at line 887 of file systemz.h.
Referenced by getStubsSection().
getStubsSection()
Section & llvm::jitlink::systemz::PLTTableManager::getStubsSection (LinkGraph & G) inline
Definition at line 922 of file systemz.h.
References llvm::orc::Exec, G, getSectionName(), llvm::orc::Read, and StubsSection.
Referenced by createEntry().
visitEdge()
bool llvm::jitlink::systemz::PLTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 889 of file systemz.h.
References B(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::jitlink::systemz::Delta16PLTFromGOT, llvm::jitlink::systemz::Delta32PLTFromGOT, llvm::jitlink::systemz::Delta64PLTFromGOT, llvm::jitlink::systemz::DeltaPLT12dbl, llvm::jitlink::systemz::DeltaPLT16dbl, llvm::jitlink::systemz::DeltaPLT24dbl, llvm::jitlink::systemz::DeltaPLT32, llvm::jitlink::systemz::DeltaPLT32dbl, llvm::jitlink::systemz::DeltaPLT64, llvm::formatv(), G, and llvm::jitlink::TableManager< PLTTableManager >::getEntryForTarget().
Member Data Documentation
GOT
GOTTableManager& llvm::jitlink::systemz::PLTTableManager::GOT
Definition at line 929 of file systemz.h.
Referenced by createEntry(), and PLTTableManager().
StubsSection
Section* llvm::jitlink::systemz::PLTTableManager::StubsSection = nullptr
Definition at line 930 of file systemz.h.
Referenced by getStubsSection().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/systemz.h