LLVM: llvm::gsym::CallSiteInfoLoader Class Reference
llvm::gsym::CallSiteInfoLoader Class Reference
#include "llvm/DebugInfo/GSYM/CallSiteInfo.h"
Public Member Functions
CallSiteInfoLoader (GsymCreator &GCreator, std::vector< FunctionInfo > &Funcs)
Constructor that initializes the CallSiteInfoLoader with necessary data structures.
LLVM_ABI llvm::Error loadYAML (StringRef YAMLFile)
This method reads the specified YAML file, parses its content, and updates the Funcs vector with call site information based on the YAML data.
Detailed Description
Definition at line 94 of file CallSiteInfo.h.
Constructor & Destructor Documentation
CallSiteInfoLoader()
llvm::gsym::CallSiteInfoLoader::CallSiteInfoLoader (GsymCreator & GCreator, std::vector< FunctionInfo > & Funcs) inline
Constructor that initializes the CallSiteInfoLoader with necessary data structures.
Parameters
GCreator A reference to the GsymCreator.
Definition at line 100 of file CallSiteInfo.h.
Referenced by loadYAML().
Member Function Documentation
loadYAML()
Error CallSiteInfoLoader::loadYAML (StringRef YAMLFile)
This method reads the specified YAML file, parses its content, and updates the Funcs vector with call site information based on the YAML data.
Parameters
Funcs A reference to a vector of FunctionInfo objects to be populated.
YAMLFile A StringRef representing the path to the YAML file to be loaded.
Returns
An llvm::Error indicating success or describing any issues encountered during the loading process.
Definition at line 150 of file CallSiteInfo.cpp.
References CallSiteInfoLoader(), llvm::createStringError(), llvm::yaml::Input::error(), llvm::errorCodeToError(), llvm::MemoryBuffer::getFile(), and loadYAML().
Referenced by llvm::gsym::GsymCreator::loadCallSitesFromYAML(), and loadYAML().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/GSYM/CallSiteInfo.h
lib/DebugInfo/GSYM/CallSiteInfo.cpp