LLVM: llvm::opt::GenericOptTable Class Reference
llvm::opt::GenericOptTable Class Reference
Specialization of OptTable.
#include "llvm/Option/OptTable.h"
Protected Member Functions
LLVM_ABI GenericOptTable (const StringTable &StrTable, ArrayRef< StringTable::Offset > PrefixesTable, ArrayRef< Info > OptionInfos, bool IgnoreCase=false, ArrayRef< SubCommand > SubCommands={}, ArrayRef< unsigned > SubCommandIDsTable={})
Protected Member Functions inherited from llvm::opt::OptTable
OptTable (const StringTable &StrTable, ArrayRef< StringTable::Offset > PrefixesTable, ArrayRef< Info > OptionInfos, bool IgnoreCase=false, ArrayRef< SubCommand > SubCommands={}, ArrayRef< unsigned > SubCommandIDsTable={})
Initialize OptTable using Tablegen'ed OptionInfos.
void buildPrefixChars ()
Build (or rebuild) the PrefixChars member.
Additional Inherited Members
Public Member Functions inherited from llvm::opt::OptTable
bool isValidForSubCommand (const Info *CandidateInfo, StringRef SubCommand) const
virtual ~OptTable ()
const StringTable & getStrTable () const
Return the string table used for option names.
ArrayRef< SubCommand > getSubCommands () const
ArrayRef< StringTable::Offset > getPrefixesTable () const
Return the prefixes table used for option names.
unsigned getNumOptions () const
Return the total number of option classes.
const Option getOption (OptSpecifier Opt) const
Get the given Opt's Option instance, lazily creating it if necessary.
StringRef getOptionName (OptSpecifier id) const
Lookup the name of the given option.
StringRef getOptionPrefix (OptSpecifier id) const
Lookup the prefix of the given option.
void appendOptionPrefixes (OptSpecifier id, SmallVectorImpl< StringRef > &Prefixes) const
StringRef getOptionPrefixedName (OptSpecifier id) const
Lookup the prefixed name of the given option.
unsigned getOptionKind (OptSpecifier id) const
Get the kind of the given option.
unsigned getOptionGroupID (OptSpecifier id) const
Get the group id for the given option.
const char * getOptionHelpText (OptSpecifier id) const
Get the help text to use to describe this option.
const char * getOptionHelpText (OptSpecifier id, Visibility VisibilityMask) const
const char * getOptionMetaVar (OptSpecifier id) const
Get the meta-variable name to use when describing this options values in the help text.
void setInitialOptionsFromEnvironment (const char *E)
Specify the environment variable where initial options should be read.
void setGroupedShortOptions (bool Value)
Support grouped short options. e.g. -ab represents -a -b.
void setDashDashParsing (bool Value)
Set whether "--" stops option parsing and treats all subsequent arguments as positional.
std::vector< std::string > suggestValueCompletions (StringRef Option, StringRef Arg) const
Find possible value for given flags.
std::vector< std::string > findByPrefix (StringRef Cur, Visibility VisibilityMask, unsigned int DisableFlags) const
Find flags from OptTable which starts with Cur.
unsigned findNearest (StringRef Option, std::string &NearestString, Visibility VisibilityMask=Visibility(), unsigned MinimumLength=4, unsigned MaximumDistance=UINT_MAX) const
Find the OptTable option that most closely matches the given string.
unsigned findNearest (StringRef Option, std::string &NearestString, unsigned FlagsToInclude, unsigned FlagsToExclude=0, unsigned MinimumLength=4, unsigned MaximumDistance=UINT_MAX) const
bool findExact (StringRef Option, std::string &ExactString, Visibility VisibilityMask=Visibility()) const
bool findExact (StringRef Option, std::string &ExactString, unsigned FlagsToInclude, unsigned FlagsToExclude=0) const
std::unique_ptr< Arg > ParseOneArg (const ArgList &Args, unsigned &Index, Visibility VisibilityMask=Visibility()) const
Parse a single argument; returning the new argument and updating Index.
std::unique_ptr< Arg > ParseOneArg (const ArgList &Args, unsigned &Index, unsigned FlagsToInclude, unsigned FlagsToExclude) const
InputArgList ParseArgs (ArrayRef< const char * > Args, unsigned &MissingArgIndex, unsigned &MissingArgCount, Visibility VisibilityMask=Visibility()) const
Parse an list of arguments into an InputArgList.
InputArgList ParseArgs (ArrayRef< const char * > Args, unsigned &MissingArgIndex, unsigned &MissingArgCount, unsigned FlagsToInclude, unsigned FlagsToExclude=0) const
InputArgList parseArgs (int Argc, char *const *Argv, OptSpecifier Unknown, StringSaver &Saver, std::function< void(StringRef)> ErrorFn) const
A convenience helper which handles optional initial options populated from an environment variable, expands response files recursively and parses options.
void printHelp (raw_ostream &OS, const char *Usage, const char *Title, bool ShowHidden=false, bool ShowAllAliases=false, Visibility VisibilityMask=Visibility(), StringRef SubCommand={}) const
Render the help text for an option table.
void printHelp (raw_ostream &OS, const char *Usage, const char *Title, unsigned FlagsToInclude, unsigned FlagsToExclude, bool ShowAllAliases) const
Protected Attributes inherited from llvm::opt::OptTable
unsigned FirstSearchableIndex = 0
The index of the first option which can be parsed (i.e., is not a special option like 'input' or 'unknown', and is not an option group).
SmallVector< StringRef > PrefixesUnion
The union of all option prefixes.
SmallString< 8 > PrefixChars
The union of the first element of all option prefixes.
Detailed Description
Specialization of OptTable.
Definition at line 478 of file OptTable.h.
Constructor & Destructor Documentation
GenericOptTable()
GenericOptTable::GenericOptTable (const StringTable & StrTable, ArrayRef< StringTable::Offset > PrefixesTable, ArrayRef< Info > OptionInfos, bool IgnoreCase = false, ArrayRef< SubCommand > SubCommands = {}, ArrayRef< unsigned > SubCommandIDsTable = {}) protected
Definition at line 842 of file OptTable.cpp.
References llvm::opt::OptTable::buildPrefixChars(), llvm::opt::OptTable::FirstSearchableIndex, for(), llvm::opt::OptTable::Info::getPrefixOffsets(), llvm::opt::OptTable::OptTable(), and llvm::opt::OptTable::PrefixesUnion.
The documentation for this class was generated from the following files:
include/llvm/Option/OptTable.h
lib/Option/OptTable.cpp