LLVM: llvm::Spelling Class Reference
llvm::Spelling Class Reference
#include "llvm/TableGen/DirectiveEmitter.h"
Public Types
using Value = directive::Spelling
Public Member Functions
Spelling (const Record *Def)
StringRef getText () const
llvm::directive::VersionRange getVersions () const
Value get () const
Public Member Functions inherited from llvm::Versioned
int getMinVersion (const Record *R) const
int getMaxVersion (const Record *R) const
Detailed Description
Definition at line 116 of file DirectiveEmitter.h.
Member Typedef Documentation
Value
using llvm::Spelling::Value = directive::Spelling
Definition at line 118 of file DirectiveEmitter.h.
Constructor & Destructor Documentation
Spelling()
llvm::Spelling::Spelling (const Record * Def) inline
Definition at line 120 of file DirectiveEmitter.h.
Member Function Documentation
get()
Value llvm::Spelling::get () const inline
Definition at line 128 of file DirectiveEmitter.h.
References getText(), and getVersions().
getText()
StringRef llvm::Spelling::getText () const inline
Definition at line 122 of file DirectiveEmitter.h.
Referenced by get().
getVersions()
llvm::directive::VersionRange llvm::Spelling::getVersions () const inline
Definition at line 123 of file DirectiveEmitter.h.
References llvm::Versioned::getMaxVersion(), and llvm::Versioned::getMinVersion().
Referenced by get().
The documentation for this class was generated from the following file:
include/llvm/TableGen/DirectiveEmitter.h