LLVM: llvm::object::OwningBinary< T > Class Template Reference
llvm::object::OwningBinary< T > Class Template Reference
#include "llvm/Object/Binary.h"
Public Member Functions
OwningBinary ()
OwningBinary (std::unique_ptr< T > Bin, std::unique_ptr< MemoryBuffer > Buf)
OwningBinary (OwningBinary< T > &&Other)
OwningBinary< T > & operator= (OwningBinary< T > &&Other)
std::pair< std::unique_ptr< T >, std::unique_ptr< MemoryBuffer > > takeBinary ()
T * getBinary ()
const T * getBinary () const
Detailed Description
template<typename T>
class llvm::object::OwningBinary< T >
Definition at line 200 of file Binary.h.
Constructor & Destructor Documentation
OwningBinary() [1/3]
template<typename T> llvm::object::OwningBinary< T >::OwningBinary () default
Referenced by operator=(), and OwningBinary().
OwningBinary() [2/3]
template<typename T> llvm::object::OwningBinary< T >::OwningBinary (std::unique_ptr< T > Bin, std::unique_ptr< MemoryBuffer > Buf)
Definition at line 217 of file Binary.h.
References llvm::move().
OwningBinary() [3/3]
template<typename T> llvm::object::OwningBinary< T >::OwningBinary (OwningBinary< T > && Other)
Definition at line 224 of file Binary.h.
References llvm::move(), and OwningBinary().
Member Function Documentation
getBinary() [1/2]
template<typename T> T * llvm::object::OwningBinary< T >::getBinary ()
Definition at line 240 of file Binary.h.
References T.
Referenced by loadObj().
getBinary() [2/2]
template<typename T> const T * llvm::object::OwningBinary< T >::getBinary () const
Definition at line 244 of file Binary.h.
References T.
operator=()
template<typename T> OwningBinary< T > & llvm::object::OwningBinary< T >::operator= (OwningBinary< T > && Other)
Definition at line 228 of file Binary.h.
References llvm::Other, and OwningBinary().
takeBinary()
template<typename T> std::pair< std::unique_ptr< T >, std::unique_ptr< MemoryBuffer > > llvm::object::OwningBinary< T >::takeBinary ()
Definition at line 236 of file Binary.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/RuntimeDyld.h
include/llvm/Object/Binary.h