LLVM: llvm::SpeculativeExecutionPass Class Reference
llvm::SpeculativeExecutionPass Class Reference
#include "llvm/Transforms/Scalar/SpeculativeExecution.h"
Public Member Functions
SpeculativeExecutionPass (bool OnlyIfDivergentTarget=false)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
bool runImpl (Function &F, TargetTransformInfo *TTI)
Public Member Functions inherited from llvm::PassInfoMixin< SpeculativeExecutionPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SpeculativeExecutionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 71 of file SpeculativeExecution.h.
Constructor & Destructor Documentation
SpeculativeExecutionPass()
SpeculativeExecutionPass::SpeculativeExecutionPass (bool OnlyIfDivergentTarget = false)
Definition at line 338 of file SpeculativeExecution.cpp.
References SpecExecOnlyIfDivergentTarget.
Member Function Documentation
printPipeline()
void SpeculativeExecutionPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 355 of file SpeculativeExecution.cpp.
References printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses SpeculativeExecutionPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 342 of file SpeculativeExecution.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool SpeculativeExecutionPass::runImpl (Function & F, TargetTransformInfo * TTI)
Definition at line 152 of file SpeculativeExecution.cpp.
References B(), llvm::dbgs(), F, LLVM_DEBUG, and runOnBasicBlock().
Referenced by run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/SpeculativeExecution.h
lib/Transforms/Scalar/SpeculativeExecution.cpp