LLVM: llvm::FoldingSetNodeIDRef Class Reference
llvm::FoldingSetNodeIDRef Class Reference
FoldingSetNodeIDRef - This class describes a reference to an interned FoldingSetNodeID, which can be a useful to store node id data rather than using plain FoldingSetNodeIDs, since the 32-element SmallVector is often much larger than necessary, and the possibility of heap allocation means it requires a non-trivial destructor call.
#include "llvm/ADT/FoldingSet.h"
Public Member Functions
FoldingSetNodeIDRef ()=default
FoldingSetNodeIDRef (const unsigned *D, size_t S)
unsigned ComputeHash () const
unsigned computeStableHash () const
LLVM_ABI bool operator== (FoldingSetNodeIDRef) const
bool operator!= (FoldingSetNodeIDRef RHS) const
LLVM_ABI bool operator< (FoldingSetNodeIDRef) const
Used to compare the "ordering" of two nodes as defined by the profiled bits and their ordering defined by memcmp().
const unsigned * getData () const
size_t getSize () const
Detailed Description
FoldingSetNodeIDRef - This class describes a reference to an interned FoldingSetNodeID, which can be a useful to store node id data rather than using plain FoldingSetNodeIDs, since the 32-element SmallVector is often much larger than necessary, and the possibility of heap allocation means it requires a non-trivial destructor call.
Definition at line 172 of file FoldingSet.h.
Constructor & Destructor Documentation
FoldingSetNodeIDRef() [1/2]
llvm::FoldingSetNodeIDRef::FoldingSetNodeIDRef () default
Referenced by operator!=(), operator<(), and operator==().
FoldingSetNodeIDRef() [2/2]
llvm::FoldingSetNodeIDRef::FoldingSetNodeIDRef (const unsigned * D, size_t S) inline
Definition at line 178 of file FoldingSet.h.
References D().
Member Function Documentation
ComputeHash()
unsigned llvm::FoldingSetNodeIDRef::ComputeHash () const inline
Definition at line 182 of file FoldingSet.h.
References llvm::hash_combine_range().
Referenced by llvm::FoldingSetNodeID::ComputeHash().
computeStableHash()
unsigned llvm::FoldingSetNodeIDRef::computeStableHash () const inline
Definition at line 188 of file FoldingSet.h.
References llvm::ArrayRef(), and llvm::xxh3_64bits().
Referenced by llvm::FoldingSetNodeID::computeStableHash().
getData()
const unsigned * llvm::FoldingSetNodeIDRef::getData () const inline
Definition at line 201 of file FoldingSet.h.
getSize()
size_t llvm::FoldingSetNodeIDRef::getSize () const inline
Definition at line 202 of file FoldingSet.h.
operator!=()
bool llvm::FoldingSetNodeIDRef::operator!= (FoldingSetNodeIDRef RHS) const inline
Definition at line 195 of file FoldingSet.h.
References FoldingSetNodeIDRef(), and RHS.
operator<()
bool FoldingSetNodeIDRef::operator< (FoldingSetNodeIDRef RHS) const
Used to compare the "ordering" of two nodes as defined by the profiled bits and their ordering defined by memcmp().
Definition at line 34 of file FoldingSet.cpp.
References FoldingSetNodeIDRef(), and memcmp.
operator==()
bool FoldingSetNodeIDRef::operator== (FoldingSetNodeIDRef RHS) const
Definition at line 27 of file FoldingSet.cpp.
References FoldingSetNodeIDRef(), and memcmp.
The documentation for this class was generated from the following files:
include/llvm/ADT/FoldingSet.h
lib/Support/FoldingSet.cpp