LLVM: llvm::AMDGPUTargetMachine Class Reference
llvm::AMDGPUTargetMachine Class Reference abstract
#include "Target/AMDGPU/AMDGPUTargetMachine.h"
Public Member Functions
AMDGPUTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOptLevel OL)
~AMDGPUTargetMachine () override
const TargetSubtargetInfo * getSubtargetImpl () const
const TargetSubtargetInfo * getSubtargetImpl (const Function &) const override=0
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
TargetLoweringObjectFile * getObjFileLowering () const override
void registerPassBuilderCallbacks (PassBuilder &PB) override
Allow the target to modify the pass pipeline.
void registerDefaultAliasAnalyses (AAManager &) override
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast between SrcAS and DestAS is a noop.
unsigned getAssumedAddrSpace (const Value *V) const override
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const override
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
unsigned getAddressSpaceForPseudoSourceKind (unsigned Kind) const override
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
bool splitModule (Module &M, unsigned NumParts, function_ref< void(std::unique_ptr< Module > MPart)> ModuleCallback) override
Entry point for module splitting.
ScheduleDAGInstrs * createMachineScheduler (MachineSchedContext *C) const override
Create an instance of ScheduleDAGInstrs to be run within the standard MachineScheduler pass for this function and target at the current optimization level.
Public Member Functions inherited from llvm::CodeGenTargetMachineImpl
TargetTransformInfo getTargetTransformInfo (const Function &F) const override
Get a TargetTransformInfo implementation for the target.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context) override
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
Expected< std::unique_ptr< MCStreamer > > createMCStreamer (raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Ctx) override
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
void setTargetFeatureString (StringRef FS)
virtual MachineFunctionInfo * createMachineFunctionInfo (BumpPtrAllocator &Allocator, const Function &F, const TargetSubtargetInfo *STI) const
Create the target's instance of MachineFunctionInfo.
virtual ScheduleDAGInstrs * createPostMachineScheduler (MachineSchedContext *C) const
Similar to createMachineScheduler but used when postRA machine scheduling is enabled.
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC>
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
ExceptionHandling getExceptionModel () const
Return the ExceptionHandling to use, considering TargetOptions and the Triple's default.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
uint64_t getMaxCodeSize () const
Returns the maximum code size possible under the code model.
void setCodeModel (CodeModel::Model CM)
Set the code model.
void setLargeDataThreshold (uint64_t LDT)
bool isLargeGlobalValue (const GlobalValue *GV) const
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
bool useTLSDESC () const
Returns true if this target uses TLS Descriptors.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOptLevel getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOptLevel Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
void setSupportsDebugEntryValues (bool Enable)
void setCFIFixup (bool Enable)
bool getAIXExtendedAltivecABI () const
bool getUniqueSectionNames () const
bool getUniqueBasicBlockSectionNames () const
Return true if unique basic block section names must be generated.
bool getSeparateNamedSections () const
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
bool getEnableStaticDataPartitioning () const
bool getIgnoreXCOFFVisibility () const
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
bool getXCOFFTracebackTable () const
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
llvm::BasicBlockSection getBBSectionsType () const
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
const MemoryBuffer * getBBSectionsFuncListBuf () const
Get the list of functions and basic block ids that need unique sections.
void setPGOOption (std::optional< PGOOptions > PGOOpt)
const std::optional< PGOOptions > & getPGOOption () const
TargetIRAnalysis getTargetIRAnalysis () const
Get a TargetIRAnalysis appropriate for the target.
virtual void registerEarlyDefaultAliasAnalyses (AAManager &)
Allow the target to register early alias analyses (AA before BasicAA) with the AAManager for use with the new pass manager.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
virtual unsigned getSjLjDataSize () const
virtual Error buildCodeGenPipeline (ModulePassManager &, raw_pwrite_stream &, raw_pwrite_stream *, CodeGenFileType, const CGPassBuilderOption &, PassInstrumentationCallbacks *)
virtual bool isMachineVerifierClean () const
Returns true if the target is expected to pass all machine verifier checks.
virtual bool usesPhysRegsForValues () const
True if the target uses physical regs (as nearly all targets do).
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
virtual int unqualifiedInlineAsmVariant () const
The default variant to use in unqualified asm instructions.
virtual void registerMachineRegisterInfoCallback (MachineFunction &MF) const
virtual size_t clearLinkerOptimizationHints (const SmallPtrSetImpl< MachineInstr * > &MIs) const
Remove all Linker Optimization Hints (LOH) associated with instructions in MIs and.
Static Public Member Functions
static int64_t getNullPointerValue (unsigned AddrSpace)
Get the integer value of a null pointer in the given address space.
Static Public Member Functions inherited from llvm::TargetMachine
static std::pair< int, int > parseBinutilsVersion (StringRef Version)
Static Public Attributes
static bool EnableFunctionCalls = false
static bool EnableLowerModuleLDS = true
Static Public Attributes inherited from llvm::TargetMachine
static constexpr unsigned DefaultSjLjDataSize = 32
The integer bit size to use for SjLj based exception handling.
Protected Member Functions
StringRef getGPUName (const Function &F) const
StringRef getFeatureString (const Function &F) const
Protected Member Functions inherited from llvm::CodeGenTargetMachineImpl
CodeGenTargetMachineImpl (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOptLevel OL)
void initAsmInfo ()
virtual void reset ()
Reset internal state.
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes
std::unique_ptr< TargetLoweringObjectFile > TLOF
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
uint64_t LargeDataThreshold = 0
CodeGenOptLevel OptLevel = CodeGenOptLevel::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
std::optional< PGOOptions > PGOOption
Additional Inherited Members
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Detailed Description
Definition at line 30 of file AMDGPUTargetMachine.h.
Constructor & Destructor Documentation
AMDGPUTargetMachine()
AMDGPUTargetMachine::AMDGPUTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOptLevel OL)
Definition at line 759 of file AMDGPUTargetMachine.cpp.
References llvm::CodeGenTargetMachineImpl::CodeGenTargetMachineImpl(), llvm::createGCNMCRegisterInfo(), createTLOF(), llvm::getEffectiveCodeModel(), llvm::getEffectiveRelocModel(), getGPUOrDefault(), llvm::TargetMachine::getMCSubtargetInfo(), llvm::TargetMachine::getTargetTriple(), llvm::CodeGenTargetMachineImpl::initAsmInfo(), llvm::TargetMachine::MRI, llvm::TargetMachine::Options, llvm::TargetMachine::OptLevel, llvm::TargetMachine::RM, T, TLOF, llvm::Wave32, and llvm::Wave64.
Referenced by llvm::GCNTargetMachine::GCNTargetMachine(), and llvm::R600TargetMachine::R600TargetMachine().
~AMDGPUTargetMachine()
AMDGPUTargetMachine::~AMDGPUTargetMachine () override default
Member Function Documentation
createMachineScheduler()
llvm::ScheduleDAGInstrs * AMDGPUTargetMachine::createMachineScheduler (MachineSchedContext * C) const override virtual
Create an instance of ScheduleDAGInstrs to be run within the standard MachineScheduler pass for this function and target at the current optimization level.
This can also be used to plug a new MachineSchedStrategy into an instance of the standard ScheduleDAGMI: return new ScheduleDAGMI(C, std::make_unique<MyStrategy>(C), /*RemoveKillFlags=*‍/false)
Return NULL to select the default (generic) machine scheduler.
Reimplemented from llvm::TargetMachine.
Reimplemented in llvm::GCNTargetMachine, and llvm::R600TargetMachine.
Definition at line 797 of file AMDGPUTargetMachine.cpp.
References llvm::CallingConv::C, llvm::createLoadClusterDAGMutation(), llvm::createSchedLive(), and llvm::createStoreClusterDAGMutation().
getAddressSpaceForPseudoSourceKind()
unsigned AMDGPUTargetMachine::getAddressSpaceForPseudoSourceKind (unsigned Kind) const override virtual
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
stack) the target returns the corresponding address space.
Reimplemented from llvm::TargetMachine.
Definition at line 1085 of file AMDGPUTargetMachine.cpp.
References llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::PseudoSourceValue::ConstantPool, llvm::PseudoSourceValue::ExternalSymbolCallEntry, llvm::PseudoSourceValue::FixedStack, llvm::AMDGPUAS::FLAT_ADDRESS, llvm::PseudoSourceValue::GlobalValueCallEntry, llvm::PseudoSourceValue::GOT, llvm::PseudoSourceValue::JumpTable, llvm::AMDGPUAS::PRIVATE_ADDRESS, and llvm::PseudoSourceValue::Stack.
getAssumedAddrSpace()
unsigned AMDGPUTargetMachine::getAssumedAddrSpace (const Value * V) const override virtual
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
Under offloading programming, the offloading target may be passed with values only prepared on the host side and could assume certain properties.
Reimplemented from llvm::TargetMachine.
Definition at line 1033 of file AMDGPUTargetMachine.cpp.
References assert(), llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::dyn_cast(), llvm::AMDGPUAS::FLAT_ADDRESS, llvm::AMDGPUAS::GLOBAL_ADDRESS, llvm::AMDGPU::isModuleEntryFunctionCC(), and llvm::AMDGPUAS::UNKNOWN_ADDRESS_SPACE.
getFeatureString()
StringRef AMDGPUTargetMachine::getFeatureString (const Function & F) const protected
Definition at line 789 of file AMDGPUTargetMachine.cpp.
References F, llvm::TargetMachine::getTargetFeatureString(), llvm::Attribute::getValueAsString(), and llvm::Attribute::isValid().
Referenced by llvm::GCNTargetMachine::getSubtargetImpl(), and llvm::R600TargetMachine::getSubtargetImpl().
getGPUName()
StringRef AMDGPUTargetMachine::getGPUName (const Function & F) const protected
Definition at line 784 of file AMDGPUTargetMachine.cpp.
References F, llvm::TargetMachine::getTargetCPU(), llvm::Attribute::getValueAsString(), and llvm::Attribute::isValid().
Referenced by llvm::GCNTargetMachine::getSubtargetImpl(), and llvm::R600TargetMachine::getSubtargetImpl().
getNullPointerValue()
int64_t AMDGPUTargetMachine::getNullPointerValue (unsigned AddrSpace) static
Get the integer value of a null pointer in the given address space.
Definition at line 1019 of file AMDGPUTargetMachine.cpp.
References llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::AMDGPUAS::PRIVATE_ADDRESS, and llvm::AMDGPUAS::REGION_ADDRESS.
Referenced by isKnownNonNull(), isKnownNonNull(), isPtrKnownNeverNull(), and llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast().
getObjFileLowering()
TargetLoweringObjectFile * llvm::AMDGPUTargetMachine::getObjFileLowering () const inline override virtual
Reimplemented from llvm::TargetMachine.
Definition at line 51 of file AMDGPUTargetMachine.h.
References TLOF.
Referenced by getEnqueuedBlockSymbolName().
getPredicatedAddrSpace()
std::pair< const Value *, unsigned > AMDGPUTargetMachine::getPredicatedAddrSpace (const Value * V) const override virtual
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
Such predicates could be specified in @llvm.assume intrinsics for the optimizer to assume that the given generic pointer always falls within the address space based on that predicate.
Reimplemented from llvm::TargetMachine.
Definition at line 1058 of file AMDGPUTargetMachine.cpp.
References llvm::dyn_cast(), llvm::AMDGPUAS::GLOBAL_ADDRESS, II, llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::AMDGPUAS::PRIVATE_ADDRESS.
getSubtargetImpl() [1/2]
const TargetSubtargetInfo * llvm::AMDGPUTargetMachine::getSubtargetImpl () const
getSubtargetImpl() [2/2]
const TargetSubtargetInfo * llvm::AMDGPUTargetMachine::getSubtargetImpl (const Function &) const override pure virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Implemented in llvm::GCNTargetMachine, and llvm::R600TargetMachine.
isNoopAddrSpaceCast()
bool AMDGPUTargetMachine::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented from llvm::TargetMachine.
Definition at line 1027 of file AMDGPUTargetMachine.cpp.
References llvm::AMDGPU::isFlatGlobalAddrSpace().
Referenced by llvm::SITargetLowering::isFreeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), and llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace().
registerDefaultAliasAnalyses()
void AMDGPUTargetMachine::registerDefaultAliasAnalyses (AAManager &) override virtual
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
Only affects the "default" AAManager.
Reimplemented from llvm::TargetMachine.
Definition at line 817 of file AMDGPUTargetMachine.cpp.
References llvm::AAManager::registerFunctionAnalysis().
registerPassBuilderCallbacks()
void AMDGPUTargetMachine::registerPassBuilderCallbacks (PassBuilder &) override virtual
Allow the target to modify the pass pipeline.
Reimplemented from llvm::TargetMachine.
Definition at line 854 of file AMDGPUTargetMachine.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::createCGSCCToFunctionPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), EarlyInlineAll, EnableAMDGPUAttributor, EnableFunctionCalls, EnableHipStdPar, EnableLibCallSimplify, EnableLowerExecSync, EnableLowerModuleLDS, EnablePromoteKernelArguments, EnableSwLowerLDS, EnableUniformIntrinsicCombine, llvm::FullLTOPostLink, llvm::TargetMachine::getTargetTriple(), HasClosedWorldAssumption, InternalizeSymbols, llvm::AMDGPUAttributorOptions::IsClosedWorld, isLTOPreLink(), mustPreserveGV(), llvm::NoKernelInfoEndLTO, llvm::OptimizationLevel::O0, llvm::OptimizationLevel::O1, PB(), and Phase.
splitModule()
bool AMDGPUTargetMachine::splitModule (Module & M, unsigned NumParts, function_ref< void(std::unique_ptr< Module > MPart)> ModuleCallback) override virtual
Entry point for module splitting.
Targets can implement custom module splitting logic, mainly used by LTO for –lto-partitions.
On success, this guarantees that between 1 and NumParts modules were created and passed to ModuleCallBack.
Returns
true if the module was split, false otherwise. When false is returned, it is assumed that ModuleCallback has never been called and M has not been modified.
Reimplemented from llvm::TargetMachine.
Definition at line 1100 of file AMDGPUTargetMachine.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), CGAM, FAM, LAM, MAM, PB(), and llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run().
Member Data Documentation
EnableFunctionCalls
bool AMDGPUTargetMachine::EnableFunctionCalls = false static
Definition at line 38 of file AMDGPUTargetMachine.h.
Referenced by alwaysInlineImpl(), llvm::R600TargetMachine::R600TargetMachine(), and registerPassBuilderCallbacks().
EnableLowerModuleLDS
bool AMDGPUTargetMachine::EnableLowerModuleLDS = true static
Definition at line 39 of file AMDGPUTargetMachine.h.
Referenced by alwaysInlineImpl(), and registerPassBuilderCallbacks().
TLOF
std::unique_ptr<TargetLoweringObjectFile> llvm::AMDGPUTargetMachine::TLOF protected
Definition at line 32 of file AMDGPUTargetMachine.h.
Referenced by AMDGPUTargetMachine(), and getObjFileLowering().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUTargetMachine.h
lib/Target/AMDGPU/AMDGPUTargetMachine.cpp