LLVM: llvm::VPUser Class Reference
llvm::VPUser Class Reference
This class augments VPValue with operands which provide the inverse def-use edges from VPValue's users to their defs.
#include "Transforms/Vectorize/VPlanValue.h"
Public Types
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Member Functions
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool usesFirstLaneOnly (const VPValue *Op) const
Returns true if the VPUser only uses the first lane of operand Op.
virtual bool usesFirstPartOnly (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Protected Member Functions
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Friends
class VPPhiAccessors
Grant access to removeOperand for VPPhiAccessors, the only supported user.
Detailed Description
This class augments VPValue with operands which provide the inverse def-use edges from VPValue's users to their defs.
Definition at line 229 of file VPlanValue.h.
Member Typedef Documentation
const_operand_iterator
typedef SmallVectorImpl<VPValue*>::const_iterator llvm::VPUser::const_operand_iterator
Definition at line 289 of file VPlanValue.h.
const_operand_range
typedef iterator_range<const_operand_iterator> llvm::VPUser::const_operand_range
Definition at line 291 of file VPlanValue.h.
operand_iterator
typedef SmallVectorImpl<VPValue*>::iterator llvm::VPUser::operand_iterator
Definition at line 288 of file VPlanValue.h.
operand_range
typedef iterator_range<operand_iterator> llvm::VPUser::operand_range
Definition at line 290 of file VPlanValue.h.
Constructor & Destructor Documentation
VPUser() [1/3]
llvm::VPUser::VPUser (ArrayRef< VPValue * > Operands) inline protected
Definition at line 248 of file VPlanValue.h.
References addOperand().
Referenced by llvm::VPRecipeBase::classof(), operator=(), llvm::VPRecipeBase::VPRecipeBase(), and VPUser().
VPUser() [2/3]
llvm::VPUser::VPUser () delete
VPUser() [3/3]
llvm::VPUser::VPUser (const VPUser &) delete
References VPUser().
~VPUser()
virtual llvm::VPUser::~VPUser () inline virtual
Definition at line 257 of file VPlanValue.h.
References operands().
Member Function Documentation
addOperand()
void llvm::VPUser::addOperand (VPValue * Operand) inline
Definition at line 262 of file VPlanValue.h.
References llvm::VPValue::addUser().
Referenced by llvm::VPlanTransforms::addExplicitVectorLength(), addInitialSkeleton(), addVPLaneMaskPhiAndUpdateExitBranch(), expandVPWidenPointerInduction(), llvm::VPlanTransforms::tryToConvertVPInstructionsToVPRecipes(), and VPUser().
getNumOperands()
unsigned llvm::VPUser::getNumOperands () const inline
Definition at line 267 of file VPlanValue.h.
Referenced by llvm::VPActiveLaneMaskPHIRecipe::clone(), llvm::VPReplicateRecipe::computeCost(), llvm::VPIRInstruction::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::VPWidenRecipe::execute(), llvm::VPIRInstruction::extractLastLaneOfLastPartOfFirstOperand(), llvm::VPWidenCallRecipe::getCalledScalarFunction(), llvm::VPReductionRecipe::getCondOp(), llvm::VPWidenIntOrFpInductionRecipe::getLastUnrolledPartOperand(), llvm::VPHistogramRecipe::getMask(), llvm::VPInterleaveBase::getMask(), llvm::VPReplicateRecipe::getMask(), llvm::VPWidenMemoryRecipe::getMask(), llvm::VPPhiAccessors::getNumIncoming(), llvm::VPBlendRecipe::getNumIncomingValues(), llvm::VPInterleaveEVLRecipe::getNumStoreOperands(), llvm::VPInterleaveRecipe::getNumStoreOperands(), llvm::VPVectorPointerRecipe::getOffset(), llvm::VPExpressionRecipe::getOperandOfResultType(), llvm::VPWidenIntOrFpInductionRecipe::getSplatVFValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPBlendRecipe::isNormalized(), llvm::VPExpressionRecipe::printRecipe(), llvm::VPIRPhi::printRecipe(), llvm::VPReplicateRecipe::printRecipe(), llvm::VPWidenGEPRecipe::printRecipe(), llvm::VPWidenPointerInductionRecipe::printRecipe(), replaceUsesOfWith(), llvm::VPInstruction::usesFirstLaneOnly(), llvm::VPVectorEndPointerRecipe::usesFirstPartOnly(), llvm::VPVectorPointerRecipe::usesFirstPartOnly(), and llvm::VPInstruction::VPInstruction().
getOperand()
VPValue * llvm::VPUser::getOperand (unsigned N) const inline
Definition at line 268 of file VPlanValue.h.
References assert(), and N.
Referenced by canNarrowLoad(), llvm::VPActiveLaneMaskPHIRecipe::clone(), llvm::VPBranchOnMaskRecipe::clone(), llvm::VPDerivedIVRecipe::clone(), llvm::VPFirstOrderRecurrencePHIRecipe::clone(), llvm::VPPredInstPHIRecipe::clone(), llvm::VPReductionPHIRecipe::clone(), llvm::VPScalarIVStepsRecipe::clone(), llvm::VPVectorEndPointerRecipe::clone(), llvm::VPVectorPointerRecipe::clone(), llvm::VPWidenCanonicalIVRecipe::clone(), llvm::VPWidenCastRecipe::clone(), llvm::VPWidenPHIRecipe::clone(), llvm::VPWidenPointerInductionRecipe::clone(), llvm::VPExpressionRecipe::computeCost(), llvm::VPHistogramRecipe::computeCost(), llvm::VPInstruction::computeCost(), llvm::VPReplicateRecipe::computeCost(), llvm::VPWidenMemoryRecipe::computeCost(), llvm::VPlanTransforms::createInLoopReductionRecipes(), createWidenInductionRecipe(), llvm::VPActiveLaneMaskPHIRecipe::execute(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPDerivedIVRecipe::execute(), llvm::VPHistogramRecipe::execute(), llvm::VPInstructionWithType::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::VPScalarIVStepsRecipe::execute(), llvm::VPVectorEndPointerRecipe::execute(), llvm::VPVectorPointerRecipe::execute(), llvm::VPWidenCanonicalIVRecipe::execute(), llvm::VPWidenCastRecipe::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::VPWidenPHIRecipe::execute(), llvm::VPWidenRecipe::execute(), llvm::VPIRInstruction::extractLastLaneOfLastPartOfFirstOperand(), fixReductionScalarResumeWhenVectorizingEpilog(), llvm::VPInterleaveBase::getAddr(), llvm::VPWidenMemoryRecipe::getAddr(), llvm::VPHeaderPHIRecipe::getBackedgeValue(), llvm::VPWidenCallRecipe::getCalledScalarFunction(), llvm::VPReductionRecipe::getChainOp(), llvm::VPReductionRecipe::getCondOp(), llvm::VPRecipeWithIRFlags::getCostForRecipeWithOpcode(), llvm::VPInterleaveEVLRecipe::getEVL(), llvm::VPReductionEVLRecipe::getEVL(), llvm::VPWidenLoadEVLRecipe::getEVL(), llvm::VPWidenStoreEVLRecipe::getEVL(), llvm::VPBlendRecipe::getIncomingValue(), llvm::VPPhiAccessors::getIncomingValue(), llvm::VPWidenIntOrFpInductionRecipe::getLastUnrolledPartOperand(), llvm::VPBlendRecipe::getMask(), llvm::VPHistogramRecipe::getMask(), llvm::VPInterleaveBase::getMask(), llvm::VPReplicateRecipe::getMask(), llvm::VPWidenMemoryRecipe::getMask(), llvm::VPVectorPointerRecipe::getOffset(), llvm::VPExpressionRecipe::getOperandOfResultType(), llvm::VPWidenIntOrFpInductionRecipe::getSplatVFValue(), llvm::VPCanonicalIVPHIRecipe::getStartValue(), llvm::VPDerivedIVRecipe::getStartValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPWidenInductionRecipe::getStartValue(), llvm::VPWidenIntOrFpInductionRecipe::getStartValue(), getStartValueFromReductionResult(), llvm::VPDerivedIVRecipe::getStepValue(), llvm::VPScalarIVStepsRecipe::getStepValue(), llvm::VPWidenInductionRecipe::getStepValue(), llvm::VPWidenInductionRecipe::getStepValue(), llvm::VPWidenStoreEVLRecipe::getStoredValue(), llvm::VPWidenStoreRecipe::getStoredValue(), llvm::VPUnrollPartAccessor< 1 >::getUnrollPart(), llvm::VPReductionRecipe::getVecOp(), llvm::VPVectorEndPointerRecipe::getVFValue(), llvm::VPVectorEndPointerRecipe::getVFValue(), llvm::VPWidenInductionRecipe::getVFValue(), llvm::VPWidenInductionRecipe::getVFValue(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::VPlanTransforms::handleUncountableEarlyExit(), preparePlanForEpilogueVectorLoop(), preparePlanForMainVectorLoop(), llvm::VPDerivedIVRecipe::printRecipe(), llvm::VPExpressionRecipe::printRecipe(), llvm::VPHistogramRecipe::printRecipe(), llvm::VPInterleaveEVLRecipe::printRecipe(), llvm::VPInterleaveRecipe::printRecipe(), llvm::VPWidenPointerInductionRecipe::printRecipe(), removeCommonBlendMask(), replaceUsesOfWith(), scalarizeVPWidenPointerInduction(), simplifyRecipe(), llvm::VPRecipeBuilder::tryToCreateWidenNonPhiRecipe(), tryToMatchAndCreateMulAccumulateReduction(), llvm::VPInstruction::usesFirstLaneOnly(), and llvm::VPWidenRecipe::usesFirstLaneOnly().
op_begin() [1/2]
operand_iterator llvm::VPUser::op_begin () inline
Definition at line 293 of file VPlanValue.h.
Referenced by operands(), operands(), and llvm::VPReplicateRecipe::printRecipe().
op_begin() [2/2]
const_operand_iterator llvm::VPUser::op_begin () const inline
Definition at line 294 of file VPlanValue.h.
op_end() [1/2]
operand_iterator llvm::VPUser::op_end () inline
Definition at line 295 of file VPlanValue.h.
Referenced by llvm::VPInterleaveBase::getStoredValues(), operands(), and operands().
op_end() [2/2]
const_operand_iterator llvm::VPUser::op_end () const inline
Definition at line 296 of file VPlanValue.h.
operands() [1/2]
operand_range llvm::VPUser::operands () inline
Definition at line 297 of file VPlanValue.h.
References op_begin(), and op_end().
Referenced by llvm::VPWidenCallRecipe::args(), llvm::VPWidenCallRecipe::args(), llvm::VPBlendRecipe::clone(), llvm::VPExpressionRecipe::clone(), llvm::VPHistogramRecipe::clone(), llvm::VPInstruction::clone(), llvm::VPInstructionWithType::clone(), llvm::VPIRInstruction::clone(), llvm::VPPhi::clone(), llvm::VPReplicateRecipe::clone(), llvm::VPWidenCallRecipe::clone(), llvm::VPWidenGEPRecipe::clone(), llvm::VPWidenIntrinsicRecipe::clone(), llvm::VPWidenPHIRecipe::clone(), llvm::VPWidenRecipe::clone(), cloneForLane(), llvm::collectEphemeralRecipesForVPlan(), llvm::VPReplicateRecipe::computeCost(), llvm::VPWidenIntrinsicRecipe::computeCost(), createReplicateRegion(), llvm::VPExpressionRecipe::decompose(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), llvm::VPIRPhi::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::VPWidenIntrinsicRecipe::execute(), llvm::VPWidenRecipe::execute(), llvm::VPRecipeBuilder::handleReplication(), hoistPreviousBeforeFORUsers(), llvm::vputils::isSingleScalar(), printOperands(), llvm::VPWidenIntrinsicRecipe::printRecipe(), scalarizeInstruction(), sinkScalarOperands(), llvm::VPBlendRecipe::usesFirstLaneOnly(), llvm::VPCanonicalIVPHIRecipe::usesFirstLaneOnly(), llvm::VPDerivedIVRecipe::usesFirstLaneOnly(), llvm::VPEVLBasedIVPHIRecipe::usesFirstLaneOnly(), llvm::VPFirstOrderRecurrencePHIRecipe::usesFirstLaneOnly(), llvm::VPInstruction::usesFirstLaneOnly(), llvm::VPInterleaveEVLRecipe::usesFirstLaneOnly(), llvm::VPInterleaveRecipe::usesFirstLaneOnly(), llvm::VPIRInstruction::usesFirstLaneOnly(), llvm::VPReductionEVLRecipe::usesFirstLaneOnly(), llvm::VPReductionPHIRecipe::usesFirstLaneOnly(), llvm::VPReplicateRecipe::usesFirstLaneOnly(), llvm::VPScalarIVStepsRecipe::usesFirstLaneOnly(), usesFirstLaneOnly(), llvm::VPVectorEndPointerRecipe::usesFirstLaneOnly(), llvm::VPVectorPointerRecipe::usesFirstLaneOnly(), llvm::VPWidenGEPRecipe::usesFirstLaneOnly(), llvm::VPWidenInductionRecipe::usesFirstLaneOnly(), llvm::VPWidenIntrinsicRecipe::usesFirstLaneOnly(), llvm::VPWidenLoadEVLRecipe::usesFirstLaneOnly(), llvm::VPWidenLoadRecipe::usesFirstLaneOnly(), llvm::VPWidenRecipe::usesFirstLaneOnly(), llvm::VPWidenStoreEVLRecipe::usesFirstLaneOnly(), llvm::VPWidenStoreRecipe::usesFirstLaneOnly(), llvm::VPCanonicalIVPHIRecipe::usesFirstPartOnly(), llvm::VPInstruction::usesFirstPartOnly(), llvm::VPIRInstruction::usesFirstPartOnly(), usesFirstPartOnly(), llvm::VPVectorEndPointerRecipe::usesFirstPartOnly(), llvm::VPVectorPointerRecipe::usesFirstPartOnly(), llvm::VPBranchOnMaskRecipe::usesScalars(), llvm::VPIRInstruction::usesScalars(), llvm::VPPredInstPHIRecipe::usesScalars(), llvm::VPReplicateRecipe::usesScalars(), usesScalars(), and ~VPUser().
operands() [2/2]
const_operand_range llvm::VPUser::operands () const inline
Definition at line 298 of file VPlanValue.h.
References op_begin(), and op_end().
operator=()
VPUser & llvm::VPUser::operator= (const VPUser &) delete
References VPUser().
printOperands()
void VPUser::printOperands (raw_ostream & O, VPSlotTracker & SlotTracker) const protected
Print the operands to O.
Definition at line 1428 of file VPlan.cpp.
References llvm::interleaveComma(), and operands().
Referenced by llvm::VPActiveLaneMaskPHIRecipe::printRecipe(), llvm::VPBranchOnMaskRecipe::printRecipe(), llvm::VPCanonicalIVPHIRecipe::printRecipe(), llvm::VPEVLBasedIVPHIRecipe::printRecipe(), llvm::VPFirstOrderRecurrencePHIRecipe::printRecipe(), llvm::VPInstruction::printRecipe(), llvm::VPInstructionWithType::printRecipe(), llvm::VPPredInstPHIRecipe::printRecipe(), llvm::VPReductionPHIRecipe::printRecipe(), llvm::VPReplicateRecipe::printRecipe(), llvm::VPScalarIVStepsRecipe::printRecipe(), llvm::VPVectorEndPointerRecipe::printRecipe(), llvm::VPVectorPointerRecipe::printRecipe(), llvm::VPWidenCanonicalIVRecipe::printRecipe(), llvm::VPWidenCastRecipe::printRecipe(), llvm::VPWidenGEPRecipe::printRecipe(), llvm::VPWidenIntOrFpInductionRecipe::printRecipe(), llvm::VPWidenLoadEVLRecipe::printRecipe(), llvm::VPWidenLoadRecipe::printRecipe(), llvm::VPWidenRecipe::printRecipe(), llvm::VPWidenStoreEVLRecipe::printRecipe(), and llvm::VPWidenStoreRecipe::printRecipe().
replaceUsesOfWith()
void VPUser::replaceUsesOfWith (VPValue * From, VPValue * To)
Replaces all uses of From in the VPUser with To.
Definition at line 1416 of file VPlan.cpp.
References getNumOperands(), getOperand(), and setOperand().
setOperand()
void llvm::VPUser::setOperand (unsigned I, VPValue * New) inline
Definition at line 273 of file VPlanValue.h.
References I.
Referenced by createReplicateRegion(), createWidenInductionRecipe(), llvm::VPIRInstruction::extractLastLaneOfLastPartOfFirstOperand(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::VPlanTransforms::handleUncountableEarlyExit(), llvm::VPlanTransforms::narrowInterleaveGroups(), preparePlanForEpilogueVectorLoop(), preparePlanForMainVectorLoop(), replaceUsesOfWith(), llvm::VPHeaderPHIRecipe::setBackedgeValue(), llvm::VPBlendRecipe::setMask(), llvm::VPHeaderPHIRecipe::setStartValue(), and llvm::VPWidenInductionRecipe::setStepValue().
swapOperands()
void llvm::VPUser::swapOperands () inline
Swap operands of the VPUser. It must have exactly 2 operands.
Definition at line 280 of file VPlanValue.h.
References assert(), and std::swap().
usesFirstLaneOnly()
virtual bool llvm::VPUser::usesFirstLaneOnly (const VPValue * Op) const inline virtual
Returns true if the VPUser only uses the first lane of operand Op.
Conservatively returns false.
Reimplemented in llvm::VPBlendRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPDerivedIVRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPInstruction, llvm::VPInterleaveBase, llvm::VPInterleaveEVLRecipe, llvm::VPInterleaveRecipe, llvm::VPIRInstruction, llvm::VPReductionEVLRecipe, llvm::VPReductionPHIRecipe, llvm::VPReplicateRecipe, llvm::VPScalarIVStepsRecipe, llvm::VPVectorEndPointerRecipe, llvm::VPVectorPointerRecipe, llvm::VPWidenGEPRecipe, llvm::VPWidenInductionRecipe, llvm::VPWidenIntrinsicRecipe, llvm::VPWidenLoadEVLRecipe, llvm::VPWidenLoadRecipe, llvm::VPWidenRecipe, llvm::VPWidenStoreEVLRecipe, and llvm::VPWidenStoreRecipe.
Definition at line 312 of file VPlanValue.h.
References assert(), llvm::is_contained(), and operands().
Referenced by llvm::VPWidenCallRecipe::execute(), and usesScalars().
usesFirstPartOnly()
virtual bool llvm::VPUser::usesFirstPartOnly (const VPValue * Op) const inline virtual
Returns true if the VPUser only uses the first part of operand Op.
Conservatively returns false.
Reimplemented in llvm::VPCanonicalIVPHIRecipe, llvm::VPInstruction, llvm::VPIRInstruction, llvm::VPVectorEndPointerRecipe, and llvm::VPVectorPointerRecipe.
Definition at line 320 of file VPlanValue.h.
References assert(), llvm::is_contained(), and operands().
usesScalars()
virtual bool llvm::VPUser::usesScalars (const VPValue * Op) const inline virtual
Returns true if the VPUser uses scalars of operand Op.
Conservatively returns if only first (scalar) lane is used, as default.
Reimplemented in llvm::VPBranchOnMaskRecipe, llvm::VPIRInstruction, llvm::VPPredInstPHIRecipe, and llvm::VPReplicateRecipe.
Definition at line 304 of file VPlanValue.h.
References assert(), llvm::is_contained(), operands(), and usesFirstLaneOnly().
Friends And Related Symbol Documentation
VPPhiAccessors
friend class VPPhiAccessors friend
Grant access to removeOperand for VPPhiAccessors, the only supported user.
Definition at line 231 of file VPlanValue.h.
References VPPhiAccessors.
Referenced by VPPhiAccessors.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanValue.h
lib/Transforms/Vectorize/VPlan.cpp