LLVM: llvm::remarks::BitstreamBlockParserHelperBase Class Reference
llvm::remarks::BitstreamBlockParserHelperBase Class Reference
#include "Remarks/BitstreamRemarkParser.h"
Public Member Functions
BitstreamBlockParserHelperBase (BitstreamCursor &Stream, unsigned BlockID, StringRef BlockName)
template<typename... Ts>
Error error (char const *Fmt, const Ts &...Vals)
Error expectBlock ()
Protected Member Functions
Error enterBlock ()
Error unknownRecord (unsigned AbbrevID)
Error unexpectedRecord (StringRef RecordName)
Error malformedRecord (StringRef RecordName)
Error unexpectedBlock (unsigned Code)
Protected Attributes
BitstreamCursor & Stream
StringRef BlockName
unsigned BlockID
Detailed Description
Definition at line 32 of file BitstreamRemarkParser.h.
Constructor & Destructor Documentation
BitstreamBlockParserHelperBase()
llvm::remarks::BitstreamBlockParserHelperBase::BitstreamBlockParserHelperBase (BitstreamCursor & Stream, unsigned BlockID, StringRef BlockName) inline
Definition at line 40 of file BitstreamRemarkParser.h.
References BlockID, BlockName, and Stream.
Member Function Documentation
enterBlock()
Error BitstreamBlockParserHelperBase::enterBlock () protected
Definition at line 77 of file BitstreamRemarkParser.cpp.
References BlockID, BlockName, error, Stream, and llvm::Error::success().
Referenced by llvm::remarks::BitstreamMetaParserHelper::BitstreamBlockParserHelper< BitstreamMetaParserHelper >.
error()
template<typename... Ts> Error llvm::remarks::BitstreamBlockParserHelperBase::error (char const * Fmt, const Ts &... Vals) inline
Definition at line 44 of file BitstreamRemarkParser.h.
References BlockName, llvm::formatv(), and llvm::make_error().
expectBlock()
Error BitstreamBlockParserHelperBase::expectBlock ()
Definition at line 67 of file BitstreamRemarkParser.cpp.
References BlockID, BlockName, error, expectSubBlock(), Stream, and llvm::Error::success().
malformedRecord()
Error BitstreamBlockParserHelperBase::malformedRecord (StringRef RecordName) protected
Definition at line 43 of file BitstreamRemarkParser.cpp.
References error.
Referenced by llvm::remarks::BitstreamRemarkParserHelper::handleRecord(), and llvm::remarks::BitstreamMetaParserHelper::parseRecord().
unexpectedBlock()
Error BitstreamBlockParserHelperBase::unexpectedBlock (unsigned Code) protected
Definition at line 47 of file BitstreamRemarkParser.cpp.
References error.
Referenced by llvm::remarks::BitstreamBlockParserHelper< Derived >::parseSubBlock().
unexpectedRecord()
Error BitstreamBlockParserHelperBase::unexpectedRecord (StringRef RecordName) protected
Definition at line 39 of file BitstreamRemarkParser.cpp.
References error.
unknownRecord()
Error BitstreamBlockParserHelperBase::unknownRecord (unsigned AbbrevID) protected
Definition at line 35 of file BitstreamRemarkParser.cpp.
References error.
Referenced by llvm::remarks::BitstreamRemarkParserHelper::handleRecord(), and llvm::remarks::BitstreamMetaParserHelper::parseRecord().
Member Data Documentation
BlockID
unsigned llvm::remarks::BitstreamBlockParserHelperBase::BlockID protected
Definition at line 37 of file BitstreamRemarkParser.h.
Referenced by BitstreamBlockParserHelperBase(), enterBlock(), and expectBlock().
BlockName
StringRef llvm::remarks::BitstreamBlockParserHelperBase::BlockName protected
Definition at line 36 of file BitstreamRemarkParser.h.
Referenced by BitstreamBlockParserHelperBase(), enterBlock(), error(), and expectBlock().
Stream
BitstreamCursor& llvm::remarks::BitstreamBlockParserHelperBase::Stream protected
Definition at line 34 of file BitstreamRemarkParser.h.
Referenced by llvm::remarks::BitstreamMetaParserHelper::BitstreamBlockParserHelper< BitstreamMetaParserHelper >, BitstreamBlockParserHelperBase(), llvm::remarks::BitstreamMetaParserHelper::BitstreamMetaParserHelper(), llvm::remarks::BitstreamRemarkParserHelper::BitstreamRemarkParserHelper(), enterBlock(), expectBlock(), llvm::remarks::BitstreamMetaParserHelper::parseRecord(), and llvm::remarks::BitstreamRemarkParserHelper::parseRecord().
The documentation for this class was generated from the following files:
lib/Remarks/BitstreamRemarkParser.h
lib/Remarks/BitstreamRemarkParser.cpp