LLVM: llvm::FoldingSetIteratorImpl Class Reference
llvm::FoldingSetIteratorImpl Class Reference
FoldingSetIteratorImpl - This is the common iterator support shared by all folding sets, which knows how to walk the folding set hash table.
#include "llvm/ADT/FoldingSet.h"
Public Member Functions
bool operator== (const FoldingSetIteratorImpl &RHS) const
bool operator!= (const FoldingSetIteratorImpl &RHS) const
Protected Member Functions
LLVM_ABI FoldingSetIteratorImpl (void **Bucket)
LLVM_ABI void advance ()
Protected Attributes
FoldingSetNode * NodePtr
Detailed Description
FoldingSetIteratorImpl - This is the common iterator support shared by all folding sets, which knows how to walk the folding set hash table.
Definition at line 707 of file FoldingSet.h.
Constructor & Destructor Documentation
FoldingSetIteratorImpl()
FoldingSetIteratorImpl::FoldingSetIteratorImpl (void ** Bucket) protected
Definition at line 390 of file FoldingSet.cpp.
References GetNextPtr(), and NodePtr.
Referenced by llvm::FoldingSetIterator< const T >::FoldingSetIterator(), operator!=(), and operator==().
Member Function Documentation
advance()
void FoldingSetIteratorImpl::advance () protected
Definition at line 399 of file FoldingSet.cpp.
References GetBucketPtr(), GetNextPtr(), and NodePtr.
Referenced by llvm::FoldingSetIterator< const T >::operator++().
operator!=()
bool llvm::FoldingSetIteratorImpl::operator!= (const FoldingSetIteratorImpl & RHS) const inline
Definition at line 719 of file FoldingSet.h.
References FoldingSetIteratorImpl(), NodePtr, and RHS.
operator==()
bool llvm::FoldingSetIteratorImpl::operator== (const FoldingSetIteratorImpl & RHS) const inline
Definition at line 716 of file FoldingSet.h.
References FoldingSetIteratorImpl(), NodePtr, and RHS.
Member Data Documentation
NodePtr
FoldingSetNode* llvm::FoldingSetIteratorImpl::NodePtr protected
Definition at line 709 of file FoldingSet.h.
Referenced by advance(), FoldingSetIteratorImpl(), operator!=(), llvm::FoldingSetIterator< const T >::operator*(), llvm::FoldingSetIterator< const T >::operator->(), and operator==().
The documentation for this class was generated from the following files:
include/llvm/ADT/FoldingSet.h
lib/Support/FoldingSet.cpp