LLVM: llvm::object::OffloadFile Class Reference
llvm::object::OffloadFile Class Reference
A class to contain the binary information for a single OffloadBinary that owns its memory.
#include "llvm/Object/OffloadBinary.h"
Public Types
using TargetID = std::pair<StringRef, StringRef>
Public Member Functions
OffloadFile (std::unique_ptr< OffloadBinary > Binary, std::unique_ptr< MemoryBuffer > Buffer)
OffloadFile copy () const
Make a deep copy of this offloading file.
operator TargetID () const
We use the Triple and Architecture pair to group linker inputs together.
Public Member Functions inherited from llvm::object::OwningBinary< OffloadBinary >
OwningBinary ()
OwningBinary (std::unique_ptr< OffloadBinary > Bin, std::unique_ptr< MemoryBuffer > Buf)
OwningBinary (OwningBinary< OffloadBinary > &&Other)
OwningBinary< OffloadBinary > & operator= (OwningBinary< OffloadBinary > &&Other)
std::pair< std::unique_ptr< OffloadBinary >, std::unique_ptr< MemoryBuffer > > takeBinary ()
OffloadBinary * getBinary ()
const OffloadBinary * getBinary () const
Detailed Description
A class to contain the binary information for a single OffloadBinary that owns its memory.
Definition at line 159 of file OffloadBinary.h.
Member Typedef Documentation
TargetID
using llvm::object::OffloadFile::TargetID = std::pair<StringRef, StringRef>
Definition at line 161 of file OffloadBinary.h.
Constructor & Destructor Documentation
OffloadFile()
llvm::object::OffloadFile::OffloadFile (std::unique_ptr< OffloadBinary > Binary, std::unique_ptr< MemoryBuffer > Buffer) inline
Definition at line 163 of file OffloadBinary.h.
References llvm::move(), and llvm::object::OwningBinary< OffloadBinary >::OwningBinary().
Referenced by copy().
Member Function Documentation
copy()
OffloadFile llvm::object::OffloadFile::copy () const inline
Make a deep copy of this offloading file.
Definition at line 168 of file OffloadBinary.h.
References assert(), llvm::consumeError(), llvm::object::OffloadBinary::create(), llvm::object::OwningBinary< OffloadBinary >::getBinary(), llvm::MemoryBuffer::getMemBufferCopy(), and OffloadFile().
operator TargetID()
llvm::object::OffloadFile::operator TargetID () const inline
We use the Triple and Architecture pair to group linker inputs together.
This conversion function lets us use these inputs in a hash-map.
Definition at line 183 of file OffloadBinary.h.
References llvm::object::OwningBinary< OffloadBinary >::getBinary().
The documentation for this class was generated from the following file:
include/llvm/Object/OffloadBinary.h