LLVM: llvm::SanitizerBinaryMetadataPass Class Reference
llvm::SanitizerBinaryMetadataPass Class Reference
Public interface to the SanitizerBinaryMetadata module pass for emitting metadata for binary analysis sanitizers.
#include "llvm/Transforms/Instrumentation/SanitizerBinaryMetadata.h"
Public Member Functions
LLVM_ABI SanitizerBinaryMetadataPass (SanitizerBinaryMetadataOptions Opts={}, IntrusiveRefCntPtr< vfs::FileSystem > VFS=nullptr, ArrayRef< std::string > IgnorelistFiles={})
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< SanitizerBinaryMetadataPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< SanitizerBinaryMetadataPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Public interface to the SanitizerBinaryMetadata module pass for emitting metadata for binary analysis sanitizers.
The pass should be inserted after optimizations.
Definition at line 55 of file SanitizerBinaryMetadata.h.
Constructor & Destructor Documentation
SanitizerBinaryMetadataPass()
SanitizerBinaryMetadataPass::SanitizerBinaryMetadataPass (SanitizerBinaryMetadataOptions Opts = {}, IntrusiveRefCntPtr< vfs::FileSystem > VFS = nullptr, ArrayRef< std::string > IgnorelistFiles = {}) explicit
Definition at line 483 of file SanitizerBinaryMetadata.cpp.
References llvm::move().
Member Function Documentation
isRequired()
bool llvm::SanitizerBinaryMetadataPass::isRequired () inline static
Definition at line 63 of file SanitizerBinaryMetadata.h.
run()
PreservedAnalyses SanitizerBinaryMetadataPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 492 of file SanitizerBinaryMetadata.cpp.
References llvm::PreservedAnalyses::all(), llvm::SpecialCaseList::createOrDie(), llvm::PreservedAnalyses::none(), and Pass.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/SanitizerBinaryMetadata.h
lib/Transforms/Instrumentation/SanitizerBinaryMetadata.cpp