LLVM: llvm::CGDataError Class Reference
llvm::CGDataError Class Reference
#include "llvm/CGData/CodeGenData.h"
Public Member Functions
CGDataError (cgdata_error Err, const Twine &ErrStr=Twine())
std::string message () const override
Return the error message as a string.
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
cgdata_error get () const
const std::string & getMessage () const
Public Member Functions inherited from llvm::ErrorInfo< CGDataError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
template<typename ErrorInfoT>
bool isA () const
Static Public Member Functions
static std::pair< cgdata_error, std::string > take (Error E)
Consume an Error and return the raw enum value contained within it, and the optional error message.
Static Public Member Functions inherited from llvm::ErrorInfo< CGDataError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 67 of file CodeGenData.h.
Constructor & Destructor Documentation
CGDataError()
llvm::CGDataError::CGDataError (cgdata_error Err, const Twine & ErrStr = Twine()) inline
Definition at line 69 of file CodeGenData.h.
References assert(), and llvm::success.
Referenced by take().
Member Function Documentation
convertToErrorCode()
std::error_code llvm::CGDataError::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 78 of file CodeGenData.h.
References llvm::make_error_code().
get()
cgdata_error llvm::CGDataError::get () const inline
Definition at line 82 of file CodeGenData.h.
Referenced by llvm::CodeGenDataReader::error(), and take().
getMessage()
const std::string & llvm::CGDataError::getMessage () const inline
Definition at line 83 of file CodeGenData.h.
Referenced by llvm::CodeGenDataReader::error(), and take().
log()
void llvm::CGDataError::log (raw_ostream & OS) const inline override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 76 of file CodeGenData.h.
References message().
message()
std::string CGDataError::message () const override virtual
Return the error message as a string.
Reimplemented from llvm::ErrorInfoBase.
Definition at line 99 of file CodeGenData.cpp.
References getCGDataErrString().
Referenced by log(), and llvm::cgdata::warn().
take()
std::pair< cgdata_error, std::string > llvm::CGDataError::take (Error E) inline static
Consume an Error and return the raw enum value contained within it, and the optional error message.
The Error must either be a success value, or contain a single CGDataError.
Definition at line 88 of file CodeGenData.h.
References assert(), CGDataError(), E(), get(), getMessage(), llvm::handleAllErrors(), and llvm::success.
Member Data Documentation
ID
char CGDataError::ID = 0 static
Definition at line 99 of file CodeGenData.h.
The documentation for this class was generated from the following files:
include/llvm/CGData/CodeGenData.h
lib/CGData/CodeGenData.cpp