LLVM: llvm::LiveRegSet Class Reference
llvm::LiveRegSet Class Reference
A set of live virtual registers and physical register units.
#include "llvm/CodeGen/RegisterPressure.h"
Public Member Functions
LLVM_ABI void clear ()
LLVM_ABI void init (const MachineRegisterInfo &MRI)
LaneBitmask contains (VirtRegOrUnit VRegOrUnit) const
LaneBitmask insert (VRegMaskOrUnit Pair)
Mark the Pair.LaneMask lanes of Pair.Reg as live.
LaneBitmask erase (VRegMaskOrUnit Pair)
Clears the Pair.LaneMask lanes of Pair.Reg (mark them as dead).
size_t size () const
void appendTo (SmallVectorImpl< VRegMaskOrUnit > &To) const
Detailed Description
A set of live virtual registers and physical register units.
This is a wrapper around a SparseSet which deals with mapping register unit and virtual register indexes to an index usable by the sparse set.
Definition at line 264 of file RegisterPressure.h.
Member Function Documentation
appendTo()
void llvm::LiveRegSet::appendTo (SmallVectorImpl< VRegMaskOrUnit > & To) const inline
Definition at line 336 of file RegisterPressure.h.
References llvm::SmallVectorImpl< T >::emplace_back(), and P.
clear()
void LiveRegSet::clear ()
Definition at line 231 of file RegisterPressure.cpp.
contains()
LaneBitmask llvm::LiveRegSet::contains (VirtRegOrUnit VRegOrUnit) const inline
Definition at line 299 of file RegisterPressure.h.
References llvm::LaneBitmask::getNone(), and I.
erase()
LaneBitmask llvm::LiveRegSet::erase (VRegMaskOrUnit Pair) inline
Clears the Pair.LaneMask lanes of Pair.Reg (mark them as dead).
Returns the previously live lanes of Pair.Reg.
Definition at line 322 of file RegisterPressure.h.
References llvm::LaneBitmask::getNone(), I, and llvm::VRegMaskOrUnit::VRegOrUnit.
init()
void LiveRegSet::init (const MachineRegisterInfo & MRI)
Definition at line 223 of file RegisterPressure.cpp.
References MRI, and TRI.
insert()
LaneBitmask llvm::LiveRegSet::insert (VRegMaskOrUnit Pair) inline
Mark the Pair.LaneMask lanes of Pair.Reg as live.
Returns the previously live lanes of Pair.Reg.
Definition at line 309 of file RegisterPressure.h.
References llvm::LaneBitmask::getNone(), llvm::VRegMaskOrUnit::LaneMask, and llvm::VRegMaskOrUnit::VRegOrUnit.
size()
size_t llvm::LiveRegSet::size () const inline
Definition at line 332 of file RegisterPressure.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterPressure.h
lib/CodeGen/RegisterPressure.cpp