LLVM: llvm::FeatureBitset Class Reference
llvm::FeatureBitset Class Reference
Container class for subtarget features.
#include "llvm/TargetParser/SubtargetFeature.h"
Public Member Functions
constexpr FeatureBitset ()=default
constexpr FeatureBitset (std::initializer_list< unsigned > Init)
FeatureBitset & set ()
constexpr FeatureBitset & set (unsigned I)
constexpr FeatureBitset & reset (unsigned I)
constexpr FeatureBitset & flip (unsigned I)
constexpr bool operator[] (unsigned I) const
constexpr bool test (unsigned I) const
constexpr size_t size () const
bool any () const
bool none () const
size_t count () const
constexpr FeatureBitset & operator^= (const FeatureBitset &RHS)
constexpr FeatureBitset operator^ (const FeatureBitset &RHS) const
constexpr FeatureBitset & operator&= (const FeatureBitset &RHS)
constexpr FeatureBitset operator& (const FeatureBitset &RHS) const
constexpr FeatureBitset & operator|= (const FeatureBitset &RHS)
constexpr FeatureBitset operator| (const FeatureBitset &RHS) const
constexpr FeatureBitset operator~ () const
bool operator== (const FeatureBitset &RHS) const
bool operator!= (const FeatureBitset &RHS) const
bool operator< (const FeatureBitset &Other) const
Protected Member Functions
constexpr FeatureBitset (const std::array< uint64_t, MAX_SUBTARGET_WORDS > &B)
Detailed Description
Container class for subtarget features.
This is a constexpr reimplementation of a subset of std::bitset. It would be nice to use std::bitset directly, but it doesn't support constant initialization.
Definition at line 42 of file SubtargetFeature.h.
Constructor & Destructor Documentation
FeatureBitset() [1/3]
llvm::FeatureBitset::FeatureBitset (const std::array< uint64_t, MAX_SUBTARGET_WORDS > & B) inline constexpr protected
Definition at line 48 of file SubtargetFeature.h.
References B().
Referenced by llvm::FeatureBitArray::FeatureBitArray(), flip(), llvm::FeatureBitArray::getAsBitset(), operator!=(), operator&(), operator&=(), operator<(), operator==(), operator^(), operator^=(), operator|(), operator|=(), operator~(), reset(), set(), and set().
FeatureBitset() [2/3]
llvm::FeatureBitset::FeatureBitset () constexpr default
FeatureBitset() [3/3]
llvm::FeatureBitset::FeatureBitset (std::initializer_list< unsigned > Init) inline constexpr
Definition at line 53 of file SubtargetFeature.h.
References I, and set().
Member Function Documentation
any()
bool llvm::FeatureBitset::any () const inline
Definition at line 87 of file SubtargetFeature.h.
References llvm::any_of(), and I.
Referenced by getImpliedEnabledFeatures(), and none().
count()
size_t llvm::FeatureBitset::count () const inline
Definition at line 91 of file SubtargetFeature.h.
References B(), llvm::Count, and llvm::popcount().
Referenced by llvm::ARMTTIImpl::areInlineCompatible().
flip()
FeatureBitset & llvm::FeatureBitset::flip (unsigned I) inline constexpr
Definition at line 73 of file SubtargetFeature.h.
References FeatureBitset(), and I.
Referenced by llvm::MCSubtargetInfo::ToggleFeature().
none()
bool llvm::FeatureBitset::none () const inline
Definition at line 90 of file SubtargetFeature.h.
References any().
Referenced by createAMDGPUMCSubtargetInfo().
operator!=()
bool llvm::FeatureBitset::operator!= (const FeatureBitset & RHS) const inline
Definition at line 144 of file SubtargetFeature.h.
References FeatureBitset(), and RHS.
operator&()
FeatureBitset llvm::FeatureBitset::operator& (const FeatureBitset & RHS) const inline constexpr
Definition at line 115 of file SubtargetFeature.h.
References FeatureBitset(), and RHS.
operator&=()
FeatureBitset & llvm::FeatureBitset::operator&= (const FeatureBitset & RHS) inline constexpr
Definition at line 110 of file SubtargetFeature.h.
References E(), FeatureBitset(), I, and RHS.
operator<()
bool llvm::FeatureBitset::operator< (const FeatureBitset & Other) const inline
Definition at line 146 of file SubtargetFeature.h.
References E(), FeatureBitset(), I, LHS, llvm::Other, RHS, size(), and test.
operator==()
bool llvm::FeatureBitset::operator== (const FeatureBitset & RHS) const inline
Definition at line 140 of file SubtargetFeature.h.
References FeatureBitset(), and RHS.
operator[]()
bool llvm::FeatureBitset::operator[] (unsigned I) const inline constexpr
Definition at line 78 of file SubtargetFeature.h.
References I.
operator^()
FeatureBitset llvm::FeatureBitset::operator^ (const FeatureBitset & RHS) const inline constexpr
Definition at line 104 of file SubtargetFeature.h.
References FeatureBitset(), and RHS.
operator^=()
FeatureBitset & llvm::FeatureBitset::operator^= (const FeatureBitset & RHS) inline constexpr
Definition at line 98 of file SubtargetFeature.h.
References E(), FeatureBitset(), I, and RHS.
operator|()
FeatureBitset llvm::FeatureBitset::operator| (const FeatureBitset & RHS) const inline constexpr
Definition at line 127 of file SubtargetFeature.h.
References FeatureBitset(), and RHS.
operator|=()
FeatureBitset & llvm::FeatureBitset::operator|= (const FeatureBitset & RHS) inline constexpr
Definition at line 121 of file SubtargetFeature.h.
References E(), FeatureBitset(), I, and RHS.
operator~()
FeatureBitset llvm::FeatureBitset::operator~ () const inline constexpr
Definition at line 133 of file SubtargetFeature.h.
References B(), and FeatureBitset().
reset()
FeatureBitset & llvm::FeatureBitset::reset (unsigned I) inline constexpr
Definition at line 68 of file SubtargetFeature.h.
References FeatureBitset(), and I.
Referenced by llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), and llvm::HexagonSubtarget::initializeSubtargetDependencies().
set() [1/2]
FeatureBitset & llvm::FeatureBitset::set () inline
Definition at line 58 of file SubtargetFeature.h.
References FeatureBitset(), and llvm::fill().
Referenced by llvm::Hexagon_MC::completeHVXFeatures(), llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), createRISCVMCSubtargetInfo(), createSparcMCSubtargetInfo(), FeatureBitset(), and llvm::SparcSubtarget::initializeSubtargetDependencies().
set() [2/2]
FeatureBitset & llvm::FeatureBitset::set (unsigned I) inline constexpr
Definition at line 63 of file SubtargetFeature.h.
References FeatureBitset(), and I.
size()
size_t llvm::FeatureBitset::size () const inline constexpr
Definition at line 85 of file SubtargetFeature.h.
References llvm::MAX_SUBTARGET_FEATURES.
Referenced by llvm::ARMTTIImpl::areInlineCompatible(), llvm::MCSubtargetInfo::ClearFeatureBitsTransitively(), and operator<().
test()
bool llvm::FeatureBitset::test (unsigned I) const inline constexpr
Definition at line 83 of file SubtargetFeature.h.
References I.
Referenced by llvm::ARMTTIImpl::areInlineCompatible(), llvm::Hexagon_MC::completeHVXFeatures(), llvm::AMDGPU::IsaInfo::getAddressableLocalMemorySize(), llvm::AMDGPU::IsaInfo::getAddressableNumArchVGPRs(), llvm::AMDGPU::IsaInfo::getAddressableNumSGPRs(), llvm::Hexagon_MC::getArchVersion(), llvm::AMDGPU::MCKernelDescriptor::getDefaultAmdhsaKernelDescriptor(), llvm::AMDGPU::IsaInfo::getEUsPerCU(), llvm::Hexagon_MC::getHVXVersion(), llvm::AMDGPU::IsaInfo::getLocalMemorySize(), llvm::AMDGPU::IsaInfo::getMaxNumSGPRs(), llvm::AMDGPU::IsaInfo::getMaxWorkGroupsPerCU(), llvm::AMDGPU::IsaInfo::getMinNumSGPRs(), llvm::AMDGPU::IsaInfo::getNumExtraSGPRs(), llvm::AMDGPU::IsaInfo::getNumExtraSGPRs(), llvm::AMDGPU::IsaInfo::getTotalNumVGPRs(), llvm::AMDGPU::IsaInfo::getVGPRAllocGranule(), llvm::AMDGPU::IsaInfo::getVGPREncodingGranule(), llvm::AMDGPU::IsaInfo::getWavefrontSize(), llvm::AMDGPU::initDefaultAMDKernelCodeT(), matchAliasCondition(), SetImpliedBits(), and setImpliedBits().
The documentation for this class was generated from the following file:
include/llvm/TargetParser/SubtargetFeature.h