LLVM: llvm::objcopy::dxbc::DXContainerReader Class Reference
llvm::objcopy::dxbc::DXContainerReader Class Reference
#include "ObjCopy/DXContainer/DXContainerReader.h"
Public Member Functions
DXContainerReader (const DXContainerObjectFile &Obj)
Expected< std::unique_ptr< Object > > create () const
Detailed Description
Definition at line 20 of file DXContainerReader.h.
Constructor & Destructor Documentation
DXContainerReader()
llvm::objcopy::dxbc::DXContainerReader::DXContainerReader (const DXContainerObjectFile & Obj) inline explicit
Definition at line 22 of file DXContainerReader.h.
Member Function Documentation
create()
Expected< std::unique_ptr< Object > > llvm::objcopy::dxbc::DXContainerReader::create () const
Definition at line 17 of file DXContainerReader.cpp.
References assert(), llvm::Data, and E().
Referenced by llvm::objcopy::dxbc::executeObjcopyOnBinary().
The documentation for this class was generated from the following files:
lib/ObjCopy/DXContainer/DXContainerReader.h
lib/ObjCopy/DXContainer/DXContainerReader.cpp