LLVM: llvm::xray::FDRTraceWriter Class Reference
llvm::xray::FDRTraceWriter Class Reference
The FDRTraceWriter allows us to hand-craft an XRay Flight Data Recorder (FDR) mode log file.
#include "llvm/XRay/FDRTraceWriter.h"
Public Member Functions
FDRTraceWriter (raw_ostream &O, const XRayFileHeader &H)
~FDRTraceWriter () override
Error visit (BufferExtents &) override
Error visit (WallclockRecord &) override
Error visit (NewCPUIDRecord &) override
Error visit (TSCWrapRecord &) override
Error visit (CustomEventRecord &) override
Error visit (CallArgRecord &) override
Error visit (PIDRecord &) override
Error visit (NewBufferRecord &) override
Error visit (EndBufferRecord &) override
Error visit (FunctionRecord &) override
Error visit (CustomEventRecordV5 &) override
Error visit (TypedEventRecord &) override
Public Member Functions inherited from llvm::xray::RecordVisitor
virtual ~RecordVisitor ()=default
Detailed Description
The FDRTraceWriter allows us to hand-craft an XRay Flight Data Recorder (FDR) mode log file.
This is used primarily for testing, generating sequences of FDR records that can be read/processed. It can also be used to generate various kinds of execution traces without using the XRay runtime. Note that this writer does not do any validation, but uses the types of records defined in the FDRRecords.h file.
Definition at line 29 of file FDRTraceWriter.h.
Constructor & Destructor Documentation
FDRTraceWriter()
FDRTraceWriter::FDRTraceWriter (raw_ostream & O, const XRayFileHeader & H) explicit
Definition at line 58 of file FDRTraceWriter.cpp.
References llvm::xray::XRayFileHeader::FreeFormData, and H.
~FDRTraceWriter()
FDRTraceWriter::~FDRTraceWriter () override default
Member Function Documentation
visit() [1/12]
Error FDRTraceWriter::visit (BufferExtents & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 78 of file FDRTraceWriter.cpp.
References writeMetadata().
visit() [2/12]
Error FDRTraceWriter::visit (CallArgRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 121 of file FDRTraceWriter.cpp.
References writeMetadata().
visit() [3/12]
Error FDRTraceWriter::visit (CustomEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 94 of file FDRTraceWriter.cpp.
References D(), llvm::Error::success(), and writeMetadata().
visit() [4/12]
Error FDRTraceWriter::visit (CustomEventRecordV5 & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 103 of file FDRTraceWriter.cpp.
References D(), llvm::Error::success(), and writeMetadata().
visit() [5/12]
Error FDRTraceWriter::visit (EndBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 133 of file FDRTraceWriter.cpp.
References writeMetadata().
visit() [6/12]
Error FDRTraceWriter::visit (FunctionRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 137 of file FDRTraceWriter.cpp.
References llvm::Error::success().
visit() [7/12]
Error FDRTraceWriter::visit (NewBufferRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 129 of file FDRTraceWriter.cpp.
References writeMetadata().
visit() [8/12]
Error FDRTraceWriter::visit (NewCPUIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 86 of file FDRTraceWriter.cpp.
References writeMetadata().
visit() [9/12]
Error FDRTraceWriter::visit (PIDRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 125 of file FDRTraceWriter.cpp.
References writeMetadata().
visit() [10/12]
Error FDRTraceWriter::visit (TSCWrapRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 90 of file FDRTraceWriter.cpp.
References writeMetadata().
visit() [11/12]
Error FDRTraceWriter::visit (TypedEventRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 112 of file FDRTraceWriter.cpp.
References D(), llvm::Error::success(), and writeMetadata().
visit() [12/12]
Error FDRTraceWriter::visit (WallclockRecord & R) override virtual
Implements llvm::xray::RecordVisitor.
Definition at line 82 of file FDRTraceWriter.cpp.
References writeMetadata().
The documentation for this class was generated from the following files:
include/llvm/XRay/FDRTraceWriter.h
lib/XRay/FDRTraceWriter.cpp