LLVM: llvm::FastMathFlags Class Reference
llvm::FastMathFlags Class Reference
Convenience struct for specifying and reasoning about fast-math flags.
#include "llvm/IR/FMF.h"
Public Types
enum {
AllowReassoc = (1 << 0) , NoNaNs = (1 << 1) , NoInfs = (1 << 2) , NoSignedZeros = (1 << 3) ,
AllowReciprocal = (1 << 4) , AllowContract = (1 << 5) , ApproxFunc = (1 << 6) , FlagEnd = (1 << 7)
}
Public Member Functions
FastMathFlags ()=default
bool any () const
bool none () const
bool all () const
void clear ()
void set ()
bool allowReassoc () const
Flag queries.
bool noNaNs () const
bool noInfs () const
bool noSignedZeros () const
bool allowReciprocal () const
bool allowContract () const
bool approxFunc () const
bool isFast () const
'Fast' means all bits are set.
void setAllowReassoc (bool B=true)
Flag setters.
void setNoNaNs (bool B=true)
void setNoInfs (bool B=true)
void setNoSignedZeros (bool B=true)
void setAllowReciprocal (bool B=true)
void setAllowContract (bool B=true)
void setApproxFunc (bool B=true)
void setFast (bool B=true)
void operator&= (const FastMathFlags &OtherFlags)
void operator|= (const FastMathFlags &OtherFlags)
bool operator!= (const FastMathFlags &OtherFlags) const
LLVM_ABI void print (raw_ostream &O) const
Print fast-math flags to O.
Static Public Member Functions
static FastMathFlags getFast ()
static FastMathFlags intersectRewrite (FastMathFlags LHS, FastMathFlags RHS)
Intersect rewrite-based flags.
static FastMathFlags unionValue (FastMathFlags LHS, FastMathFlags RHS)
Union value flags.
Static Public Attributes
static constexpr unsigned AllFlagsMask = FlagEnd - 1
Friends
class FPMathOperator
Detailed Description
Convenience struct for specifying and reasoning about fast-math flags.
Definition at line 22 of file FMF.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
AllowReassoc
NoNaNs
NoInfs
NoSignedZeros
AllowReciprocal
AllowContract
ApproxFunc
FlagEnd
Definition at line 35 of file FMF.h.
Constructor & Destructor Documentation
FastMathFlags()
llvm::FastMathFlags::FastMathFlags () default
Referenced by intersectRewrite(), and unionValue().
Member Function Documentation
all()
bool llvm::FastMathFlags::all () const inline
Definition at line 58 of file FMF.h.
References AllFlagsMask.
Referenced by isFast(), llvm::InstModificationIRStrategy::mutate(), and print().
allowContract()
bool llvm::FastMathFlags::allowContract () const inline
Definition at line 69 of file FMF.h.
References AllowContract.
Referenced by canConvertToFMA(), llvm::GCNTTIImpl::instCombineIntrinsic(), instCombineSVEVectorFuseMulAddSub(), mapToLLVMFastMathFlags(), and print().
allowReassoc()
bool llvm::FastMathFlags::allowReassoc () const inline
Flag queries.
Definition at line 64 of file FMF.h.
References AllowReassoc.
Referenced by llvm::InstCombinerImpl::foldFMulReassoc(), getISDForVPIntrinsic(), mapToLLVMFastMathFlags(), print(), simplifyFAddInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFSubInst(), and llvm::InstCombinerImpl::visitCallInst().
allowReciprocal()
bool llvm::FastMathFlags::allowReciprocal () const inline
Definition at line 68 of file FMF.h.
References AllowReciprocal.
Referenced by mapToLLVMFastMathFlags(), and print().
any()
bool llvm::FastMathFlags::any () const inline
Definition at line 56 of file FMF.h.
approxFunc()
bool llvm::FastMathFlags::approxFunc () const inline
Definition at line 70 of file FMF.h.
References ApproxFunc.
Referenced by expandFRem(), llvm::AMDGPULibCalls::fold(), mapToLLVMFastMathFlags(), and print().
clear()
void llvm::FastMathFlags::clear () inline
Definition at line 60 of file FMF.h.
Referenced by setFast().
getFast()
FastMathFlags llvm::FastMathFlags::getFast () inline static
Definition at line 50 of file FMF.h.
References setFast().
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), and llvm::VPlanTransforms::createInLoopReductionRecipes().
intersectRewrite()
FastMathFlags llvm::FastMathFlags::intersectRewrite (FastMathFlags LHS, FastMathFlags RHS) inline static
Intersect rewrite-based flags.
Definition at line 112 of file FMF.h.
References AllowContract, AllowReassoc, AllowReciprocal, ApproxFunc, FastMathFlags(), LHS, and RHS.
Referenced by convertFSqrtDivIntoFMul(), foldFNegIntoConstant(), foldSelectIntoAddConstant(), and tryFoldBinaryFMul().
isFast()
bool llvm::FastMathFlags::isFast () const inline
'Fast' means all bits are set.
Definition at line 72 of file FMF.h.
References all().
noInfs()
bool llvm::FastMathFlags::noInfs () const inline
Definition at line 66 of file FMF.h.
References NoInfs.
Referenced by llvm::computeKnownFPClass(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldSelectIntoOp(), foldSelectWithFCmpToFabs(), isKnownIntegral(), mapToLLVMFastMathFlags(), print(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), simplifyFDivInst(), and simplifyFPOp().
noNaNs()
bool llvm::FastMathFlags::noNaNs () const inline
Definition at line 65 of file FMF.h.
References NoNaNs.
Referenced by llvm::canIgnoreSNaN(), llvm::computeKnownFPClass(), llvm::InstCombinerImpl::foldSelectIntoOp(), foldSelectWithFCmpToFabs(), llvm::RISCVTTIImpl::getMinMaxReductionCost(), llvm::getRecurrenceIdentity(), isKnownIntegral(), isKnownNonNaN(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), mapToLLVMFastMathFlags(), print(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), simplifyFAddInst(), simplifyFCmpInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFPOp(), simplifyFRemInst(), and simplifyFSubInst().
none()
bool llvm::FastMathFlags::none () const inline
Definition at line 57 of file FMF.h.
Referenced by llvm::AMDGPULibCalls::fold(), and llvm::InstModificationIRStrategy::mutate().
noSignedZeros()
bool llvm::FastMathFlags::noSignedZeros () const inline
Definition at line 67 of file FMF.h.
References NoSignedZeros.
Referenced by llvm::InstCombinerImpl::fmulByZeroIsZero(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldSelectIntoOp(), llvm::getRecurrenceIdentity(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), mapToLLVMFastMathFlags(), matchSelectPattern(), print(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), simplifyFAddInst(), simplifyFDivInst(), simplifyFMAFMul(), and simplifyFSubInst().
operator!=()
bool llvm::FastMathFlags::operator!= (const FastMathFlags & OtherFlags) const inline
Definition at line 104 of file FMF.h.
operator&=()
void llvm::FastMathFlags::operator&= (const FastMathFlags & OtherFlags) inline
Definition at line 98 of file FMF.h.
operator|=()
void llvm::FastMathFlags::operator|= (const FastMathFlags & OtherFlags) inline
Definition at line 101 of file FMF.h.
print()
void FastMathFlags::print (raw_ostream & O) const
Print fast-math flags to O.
Definition at line 272 of file Operator.cpp.
References all(), allowContract(), allowReassoc(), allowReciprocal(), approxFunc(), noInfs(), noNaNs(), and noSignedZeros().
Referenced by llvm::operator<<(), and llvm::VPIRFlags::printFlags().
set()
void llvm::FastMathFlags::set () inline
Definition at line 61 of file FMF.h.
References AllFlagsMask.
Referenced by canConvertToFMA(), and setFast().
setAllowContract()
void llvm::FastMathFlags::setAllowContract (bool B = true) inline
Definition at line 90 of file FMF.h.
References AllowContract, and B().
Referenced by expandFRem(), getDecodedFastMathFlags(), llvm::VPIRFlags::getFastMathFlags(), and mapFromLLVMFastMathFlags().
setAllowReassoc()
void llvm::FastMathFlags::setAllowReassoc (bool B = true) inline
Flag setters.
Definition at line 75 of file FMF.h.
References AllowReassoc, and B().
Referenced by getDecodedFastMathFlags(), llvm::VPIRFlags::getFastMathFlags(), and mapFromLLVMFastMathFlags().
setAllowReciprocal()
void llvm::FastMathFlags::setAllowReciprocal (bool B = true) inline
Definition at line 87 of file FMF.h.
References AllowReciprocal, and B().
Referenced by expandFRem(), getDecodedFastMathFlags(), llvm::VPIRFlags::getFastMathFlags(), and mapFromLLVMFastMathFlags().
setApproxFunc()
void llvm::FastMathFlags::setApproxFunc (bool B = true) inline
Definition at line 93 of file FMF.h.
References ApproxFunc, and B().
Referenced by getDecodedFastMathFlags(), llvm::VPIRFlags::getFastMathFlags(), mapFromLLVMFastMathFlags(), and upgradeNVVMIntrinsicCall().
setFast()
void llvm::FastMathFlags::setFast (bool B = true) inline
Definition at line 96 of file FMF.h.
References B(), clear(), and set().
Referenced by getDecodedFastMathFlags(), and getFast().
setNoInfs()
void llvm::FastMathFlags::setNoInfs (bool B = true) inline
Definition at line 81 of file FMF.h.
References B(), and NoInfs.
Referenced by foldFNegIntoConstant(), llvm::InstCombinerImpl::foldSelectIntoOp(), getDecodedFastMathFlags(), llvm::VPIRFlags::getFastMathFlags(), mapFromLLVMFastMathFlags(), and llvm::InstCombinerImpl::visitSelectInst().
setNoNaNs()
void llvm::FastMathFlags::setNoNaNs (bool B = true) inline
Definition at line 78 of file FMF.h.
References B(), and NoNaNs.
Referenced by getDecodedFastMathFlags(), llvm::VPIRFlags::getFastMathFlags(), llvm::RecurrenceDescriptor::isReductionPHI(), mapFromLLVMFastMathFlags(), llvm::matchDecomposedSelectPattern(), and llvm::InstCombinerImpl::visitSelectInst().
setNoSignedZeros()
void llvm::FastMathFlags::setNoSignedZeros (bool B = true) inline
Definition at line 84 of file FMF.h.
References B(), and NoSignedZeros.
Referenced by getDecodedFastMathFlags(), llvm::VPIRFlags::getFastMathFlags(), mapFromLLVMFastMathFlags(), llvm::matchDecomposedSelectPattern(), matchFMulByZeroIfResultEqZero(), and llvm::InstCombinerImpl::visitCallInst().
unionValue()
FastMathFlags llvm::FastMathFlags::unionValue (FastMathFlags LHS, FastMathFlags RHS) inline static
Union value flags.
Definition at line 120 of file FMF.h.
References FastMathFlags(), LHS, NoInfs, NoNaNs, NoSignedZeros, and RHS.
Referenced by convertFSqrtDivIntoFMul(), foldFNegIntoConstant(), foldSelectIntoAddConstant(), and tryFoldBinaryFMul().
Friends And Related Symbol Documentation
FPMathOperator
friend class FPMathOperator friend
Definition at line 24 of file FMF.h.
References F, and FPMathOperator.
Referenced by FPMathOperator.
Member Data Documentation
AllFlagsMask
unsigned llvm::FastMathFlags::AllFlagsMask = FlagEnd - 1 static constexpr
Definition at line 46 of file FMF.h.
Referenced by all(), and set().
The documentation for this class was generated from the following files:
include/llvm/IR/FMF.h
lib/IR/Operator.cpp