LLVM: llvm::LiveIntervalUnion::Array Class Reference
llvm::LiveIntervalUnion::Array Class Reference
#include "llvm/CodeGen/LiveIntervalUnion.h"
Public Member Functions
Array ()=default
~Array ()
Array (Array &&Other)
Array (const Array &)=delete
void init (LiveIntervalUnion::Allocator &, unsigned Size)
unsigned size () const
void clear ()
LiveIntervalUnion & operator[] (MCRegUnit Unit)
const LiveIntervalUnion & operator[] (MCRegUnit Unit) const
Detailed Description
Definition at line 171 of file LiveIntervalUnion.h.
Constructor & Destructor Documentation
Array() [1/3]
llvm::LiveIntervalUnion::Array::Array () default
Referenced by Array(), and Array().
~Array()
llvm::LiveIntervalUnion::Array::~Array () inline
Definition at line 177 of file LiveIntervalUnion.h.
References clear().
Array() [2/3]
llvm::LiveIntervalUnion::Array::Array (Array && Other) inline
Definition at line 179 of file LiveIntervalUnion.h.
References Array(), and llvm::Other.
Array() [3/3]
llvm::LiveIntervalUnion::Array::Array (const Array &) delete
References Array().
Member Function Documentation
clear()
void LiveIntervalUnion::Array::clear ()
Definition at line 206 of file LiveIntervalUnion.cpp.
References llvm::LiveIntervalUnion::LiveIntervalUnion().
Referenced by ~Array().
init()
void LiveIntervalUnion::Array::init (LiveIntervalUnion::Allocator & Alloc, unsigned Size)
Definition at line 193 of file LiveIntervalUnion.cpp.
References llvm::LiveIntervalUnion::clear(), llvm::LiveIntervalUnion::LiveIntervalUnion(), and llvm::safe_malloc().
operator[]() [1/2]
LiveIntervalUnion & llvm::LiveIntervalUnion::Array::operator[] (MCRegUnit Unit) inline
Definition at line 194 of file LiveIntervalUnion.h.
References assert(), and llvm::LiveIntervalUnion::LiveIntervalUnion().
operator[]() [2/2]
const LiveIntervalUnion & llvm::LiveIntervalUnion::Array::operator[] (MCRegUnit Unit) const inline
Definition at line 199 of file LiveIntervalUnion.h.
References assert(), and llvm::LiveIntervalUnion::LiveIntervalUnion().
size()
unsigned llvm::LiveIntervalUnion::Array::size () const inline
Definition at line 190 of file LiveIntervalUnion.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveIntervalUnion.h
lib/CodeGen/LiveIntervalUnion.cpp