LLVM: llvm::VPUnrollPartAccessor< PartOpIdx > Class Template Reference
llvm::VPUnrollPartAccessor< PartOpIdx > Class Template Reference
Helper to access the operand that contains the unroll part for this recipe after unrolling.
#include "Transforms/Vectorize/VPlan.h"
Protected Member Functions
VPValue * getUnrollPartOperand (const VPUser &U) const
Return the VPValue operand containing the unroll part or null if there is no such operand.
unsigned getUnrollPart (const VPUser &U) const
Return the unroll part.
Detailed Description
template<unsigned PartOpIdx>
class llvm::VPUnrollPartAccessor< PartOpIdx >
Helper to access the operand that contains the unroll part for this recipe after unrolling.
Definition at line 968 of file VPlan.h.
Member Function Documentation
getUnrollPart()
template<unsigned PartOpIdx> unsigned VPUnrollPartAccessor::getUnrollPart (const VPUser & U) const protected
Return the unroll part.
Definition at line 394 of file VPlanRecipes.cpp.
References llvm::cast(), and getUnrollPartOperand().
getUnrollPartOperand()
template<unsigned PartOpIdx> VPValue * VPUnrollPartAccessor::getUnrollPartOperand (const VPUser & U) const protected
Return the VPValue operand containing the unroll part or null if there is no such operand.
Definition at line 387 of file VPlanRecipes.cpp.
Referenced by getUnrollPart().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp