LLVM: llvm::MachineInstrSpan Class Reference
llvm::MachineInstrSpan Class Reference
MachineInstrSpan provides an interface to get an iteration range containing the instruction it was initialized with, along with all those instructions inserted prior to or following that instruction at some point after the MachineInstrSpan is constructed.
#include "llvm/CodeGen/MachineBasicBlock.h"
Public Member Functions
MachineInstrSpan (MachineBasicBlock::iterator I, MachineBasicBlock *BB)
MachineBasicBlock::iterator begin ()
MachineBasicBlock::iterator end ()
bool empty ()
MachineBasicBlock::iterator getInitial ()
Detailed Description
MachineInstrSpan provides an interface to get an iteration range containing the instruction it was initialized with, along with all those instructions inserted prior to or following that instruction at some point after the MachineInstrSpan is constructed.
Definition at line 1468 of file MachineBasicBlock.h.
Constructor & Destructor Documentation
MachineInstrSpan()
llvm::MachineInstrSpan::MachineInstrSpan (MachineBasicBlock::iterator I, MachineBasicBlock * BB) inline
Definition at line 1473 of file MachineBasicBlock.h.
References assert(), begin(), llvm::MachineBasicBlock::end(), and end().
Member Function Documentation
begin()
MachineBasicBlock::iterator llvm::MachineInstrSpan::begin () inline
Definition at line 1479 of file MachineBasicBlock.h.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), empty(), insertCSRSaves(), and MachineInstrSpan().
empty()
bool llvm::MachineInstrSpan::empty () inline
Definition at line 1483 of file MachineBasicBlock.h.
References begin(), and end().
end()
MachineBasicBlock::iterator llvm::MachineInstrSpan::end () inline
Definition at line 1482 of file MachineBasicBlock.h.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), empty(), and MachineInstrSpan().
getInitial()
MachineBasicBlock::iterator llvm::MachineInstrSpan::getInitial () inline
Definition at line 1485 of file MachineBasicBlock.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineBasicBlock.h