LLVM: llvm::iterator_range< IteratorT > Class Template Reference
llvm::iterator_range< IteratorT > Class Template Reference
A range adaptor for a pair of iterators.
#include "llvm/ADT/iterator_range.h"
Public Member Functions
template<typename Container, std::void_t< explicitly_converted_t< llvm::detail::IterOfRange< Container >, IteratorT > > * = nullptr>
iterator_range (Container &&c)
iterator_range (IteratorT begin_iterator, IteratorT end_iterator)
IteratorT begin () const
IteratorT end () const
bool empty () const
Detailed Description
template<typename IteratorT>
class llvm::iterator_range< IteratorT >
A range adaptor for a pair of iterators.
This just wraps two iterators into a range-compatible interface. Nothing fancy at all.
Definition at line 32 of file iterator_range.h.
Constructor & Destructor Documentation
iterator_range() [1/2]
template<typename IteratorT> template<typename Container, std::void_t< explicitly_converted_t< llvm::detail::IterOfRange< Container >, IteratorT > > * = nullptr> llvm::iterator_range< IteratorT >::iterator_range (Container && c) inline
Definition at line 50 of file iterator_range.h.
iterator_range() [2/2]
template<typename IteratorT> llvm::iterator_range< IteratorT >::iterator_range (IteratorT begin_iterator, IteratorT end_iterator) inline
Definition at line 53 of file iterator_range.h.
Member Function Documentation
begin()
template<typename IteratorT> IteratorT llvm::iterator_range< IteratorT >::begin () const inline
Definition at line 57 of file iterator_range.h.
Referenced by llvm::orc::CtorDtorRunner::add(), llvm::RegisterBankInfo::applyDefaultMapping(), llvm::CodeViewDebug::beginModule(), eliminateMove(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), llvm::MachineInstr::getDebugOperand(), llvm::MachineInstr::getDebugOperand(), llvm::jitlink::getOrCreateLocalMachOHeader(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), isSafeToMove(), LLVMGetFirstTarget(), llvm::at::RAUW(), llvm::jitlink::SectionRange::SectionRange(), llvm::jitlink::splitCompactUnwindBlocks(), llvm::sandboxir::BranchInst::successors(), llvm::sandboxir::BranchInst::successors(), and llvm::jitlink::CompactUnwindManager< CURecTraits >::writeUnwindInfo().
empty()
template<typename IteratorT> bool llvm::iterator_range< IteratorT >::empty () const inline
Definition at line 59 of file iterator_range.h.
Referenced by llvm::orc::CtorDtorRunner::add(), llvm::RegisterBankInfo::applyDefaultMapping(), llvm::CodeViewDebug::beginModule(), llvm::DwarfFile::emitUnit(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), hasUAVsAtEveryStage(), and llvm::jitlink::SectionRange::SectionRange().
end()
template<typename IteratorT> IteratorT llvm::iterator_range< IteratorT >::end () const inline
Definition at line 58 of file iterator_range.h.
Referenced by findHeaderMask(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), LLVMGetTargetFromName(), preparePlanForMainVectorLoop(), llvm::at::RAUW(), llvm::jitlink::splitCompactUnwindBlocks(), llvm::sandboxir::BranchInst::successors(), and llvm::sandboxir::BranchInst::successors().
The documentation for this class was generated from the following file:
include/llvm/ADT/iterator_range.h