LLVM: llvm::VPHeaderPHIRecipe Class Reference
llvm::VPHeaderPHIRecipe Class Reference abstract
A pure virtual base class for all recipes modeling header phis, including phis for first order recurrences, pointer inductions and reductions.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
~VPHeaderPHIRecipe () override=default
void execute (VPTransformState &State) override=0
Generate the phi nodes.
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const override
Return the cost of this header phi recipe.
VPValue * getStartValue ()
Returns the start value of the phi, if one is set.
VPValue * getStartValue () const
void setStartValue (VPValue *V)
Update the start value of the recipe.
virtual VPValue * getBackedgeValue ()
Returns the incoming value from the loop backedge.
void setBackedgeValue (VPValue *V)
Update the incoming value from the loop backedge.
virtual VPRecipeBase & getBackedgeRecipe ()
Returns the backedge value as a recipe.
Public Member Functions inherited from llvm::VPSingleDefRecipe
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL=DebugLoc::getUnknown())
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, Value *UV, DebugLoc DL=DebugLoc::getUnknown())
VPSingleDefRecipe * clone () override=0
Clone the current recipe.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction.
const Instruction * getUnderlyingInstr () const
LLVM_ABI_FOR_TEST LLVM_DUMP_METHOD void dump () const
Print this VPSingleDefRecipe to dbgs() (for debugging).
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL=DebugLoc::getUnknown())
~VPRecipeBase () override=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
VPRegionBlock * getRegion ()
const VPRegionBlock * getRegion () const
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
bool isScalarCast () const
Return true if the recipe is a scalar cast.
void setDebugLoc (DebugLoc NewDL)
Set the recipe's debug location to NewDL.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override final
Print the recipe, delegating to printRecipe().
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPRecipeValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPRecipeValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
LLVM_ABI_FOR_TEST void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void swapOperands ()
Swap operands of the VPUser. It must have exactly 2 operands.
void replaceUsesOfWith (VPValue *From, VPValue *To)
Replaces all uses of From in the VPUser with To.
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool usesFirstLaneOnly (const VPValue *Op) const
Returns true if the VPUser only uses the first lane of operand Op.
virtual bool usesFirstPartOnly (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Public Member Functions inherited from llvm::VPRecipeValue
VPRecipeValue (VPDef *Def, Value *UV=nullptr)
virtual ~VPRecipeValue ()
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
Value * getLiveInIRValue () const
Return the underlying IR value for a VPIRValue.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser () const
Returns true if the value has more than one unique user.
bool hasOneUse () const
VPUser * getSingleUser ()
Return the single user of this value, or nullptr if there is not exactly one user.
const VPUser * getSingleUser () const
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop.
void setUnderlyingValue (Value *Val)
Public Member Functions inherited from llvm::VPPhiAccessors
virtual ~VPPhiAccessors ()=default
VPValue * getIncomingValue (unsigned Idx) const
Returns the incoming VPValue with index Idx.
const VPBasicBlock * getIncomingBlock (unsigned Idx) const
Returns the incoming block with index Idx.
virtual unsigned getNumIncoming () const
Returns the number of incoming values, also number of incoming blocks.
VPUser::const_operand_range incoming_values () const
Returns an interator range over the incoming values.
const_incoming_blocks_range incoming_blocks () const
Returns an iterator range over the incoming blocks.
detail::zippy< llvm::detail::zip_first, VPUser::const_operand_range, const_incoming_blocks_range > incoming_values_and_blocks () const
Returns an iterator range over pairs of incoming values and corresponding incoming blocks.
void removeIncomingValueFor (VPBlockBase *IncomingBlock) const
Removes the incoming value for IncomingBlock, which must be a predecessor.
void printPhiOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the recipe.
Static Public Member Functions
static bool classof (const VPRecipeBase *R)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPValue *V)
static bool classof (const VPSingleDefRecipe *R)
Static Public Member Functions inherited from llvm::VPSingleDefRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeValue
static bool classof (const VPValue *V)
Protected Member Functions
VPHeaderPHIRecipe (unsigned char VPDefID, Instruction *UnderlyingInstr, VPValue *Start, DebugLoc DL=DebugLoc::getUnknown())
const VPRecipeBase * getAsRecipe () const override
Return a VPRecipeBase* to the current object.
void printRecipe (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override=0
Print the recipe.
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands)
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPVIRValueSC , VPVSymbolicSC , VPVRecipeValueSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Public Types inherited from llvm::VPPhiAccessors
using const_incoming_blocks_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Detailed Description
A pure virtual base class for all recipes modeling header phis, including phis for first order recurrences, pointer inductions and reductions.
The start value is the first operand of the recipe and the incoming value from the backedge is the second operand.
Inductions are modeled using the following sub-classes:
VPCanonicalIVPHIRecipe: Canonical scalar induction of the vector loop, starting at a specified value (zero for the main vector loop, the resume value for the epilogue vector loop) and stepping by 1. The induction controls exiting of the vector loop by comparing against the vector trip count. Produces a single scalar PHI for the induction value per iteration.
VPWidenIntOrFpInductionRecipe: Generates vector values for integer and floating point inductions with arbitrary start and step values. Produces a vector PHI per-part.
VPDerivedIVRecipe: Converts the canonical IV value to the corresponding value of an IV with different start and step values. Produces a single scalar value per iteration
VPScalarIVStepsRecipe: Generates scalar values per-lane based on a canonical or derived induction.
VPWidenPointerInductionRecipe: Generate vector and scalar values for a pointer induction. Produces either a vector PHI per-part or scalar values per-lane based on the canonical induction.
Definition at line 2017 of file VPlan.h.
Constructor & Destructor Documentation
VPHeaderPHIRecipe()
llvm::VPHeaderPHIRecipe::VPHeaderPHIRecipe (unsigned char VPDefID, Instruction * UnderlyingInstr, VPValue * Start, DebugLoc DL = DebugLoc::getUnknown()) inline protected
Definition at line 2020 of file VPlan.h.
References llvm::DebugLoc::getUnknown(), and llvm::VPSingleDefRecipe::VPSingleDefRecipe().
Referenced by llvm::VPActiveLaneMaskPHIRecipe::VPActiveLaneMaskPHIRecipe(), llvm::VPCanonicalIVPHIRecipe::VPCanonicalIVPHIRecipe(), llvm::VPEVLBasedIVPHIRecipe::VPEVLBasedIVPHIRecipe(), llvm::VPFirstOrderRecurrencePHIRecipe::VPFirstOrderRecurrencePHIRecipe(), llvm::VPReductionPHIRecipe::VPReductionPHIRecipe(), and llvm::VPWidenInductionRecipe::VPWidenInductionRecipe().
~VPHeaderPHIRecipe()
llvm::VPHeaderPHIRecipe::~VPHeaderPHIRecipe () override default
Member Function Documentation
classof() [1/3]
bool llvm::VPHeaderPHIRecipe::classof (const VPRecipeBase * R) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 2031 of file VPlan.h.
classof() [2/3]
bool llvm::VPHeaderPHIRecipe::classof (const VPSingleDefRecipe * R) inline static
Definition at line 2038 of file VPlan.h.
References llvm::isa(), and llvm::VPSingleDefRecipe::VPSingleDefRecipe().
classof() [3/3]
bool llvm::VPHeaderPHIRecipe::classof (const VPValue * V) inline static
Definition at line 2035 of file VPlan.h.
References llvm::isa().
computeCost()
InstructionCost VPHeaderPHIRecipe::computeCost (ElementCount VF, VPCostContext & Ctx) const override virtual
Return the cost of this header phi recipe.
Reimplemented from llvm::VPRecipeBase.
Definition at line 2341 of file VPlanRecipes.cpp.
Referenced by execute().
execute()
void llvm::VPHeaderPHIRecipe::execute (VPTransformState & State) override pure virtual
Generate the phi nodes.
Implements llvm::VPRecipeBase.
Implemented in llvm::VPActiveLaneMaskPHIRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPReductionPHIRecipe, llvm::VPWidenInductionRecipe, llvm::VPWidenIntOrFpInductionRecipe, and llvm::VPWidenPointerInductionRecipe.
References computeCost().
getAsRecipe()
const VPRecipeBase * llvm::VPHeaderPHIRecipe::getAsRecipe () const inline override protected virtual
Return a VPRecipeBase* to the current object.
Implements llvm::VPPhiAccessors.
Definition at line 2025 of file VPlan.h.
getBackedgeRecipe()
virtual VPRecipeBase & llvm::VPHeaderPHIRecipe::getBackedgeRecipe () inline virtual
Returns the backedge value as a recipe.
The backedge value is guaranteed to be a recipe.
Reimplemented in llvm::VPWidenInductionRecipe.
Definition at line 2070 of file VPlan.h.
References getBackedgeValue().
getBackedgeValue()
virtual VPValue * llvm::VPHeaderPHIRecipe::getBackedgeValue () inline virtual
Returns the incoming value from the loop backedge.
Reimplemented in llvm::VPWidenInductionRecipe.
Definition at line 2061 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPCanonicalIVPHIRecipe::clone(), llvm::VPReductionPHIRecipe::clone(), and getBackedgeRecipe().
getStartValue() [1/2]
VPValue * llvm::VPHeaderPHIRecipe::getStartValue () inline
Returns the start value of the phi, if one is set.
Definition at line 2050 of file VPlan.h.
References llvm::VPUser::getNumOperands(), llvm::VPUser::getOperand(), and nullptr.
Referenced by llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPFirstOrderRecurrencePHIRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), preparePlanForEpilogueVectorLoop(), and llvm::VPFirstOrderRecurrencePHIRecipe::usesFirstLaneOnly().
getStartValue() [2/2]
VPValue * llvm::VPHeaderPHIRecipe::getStartValue () const inline
Definition at line 2053 of file VPlan.h.
References llvm::VPUser::getNumOperands(), llvm::VPUser::getOperand(), and nullptr.
printRecipe()
void llvm::VPHeaderPHIRecipe::printRecipe (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override protected pure virtual
Print the recipe.
Implements llvm::VPRecipeBase.
Implemented in llvm::VPActiveLaneMaskPHIRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPReductionPHIRecipe, llvm::VPWidenIntOrFpInductionRecipe, and llvm::VPWidenPointerInductionRecipe.
setBackedgeValue()
void llvm::VPHeaderPHIRecipe::setBackedgeValue (VPValue * V) inline
Update the incoming value from the loop backedge.
Definition at line 2066 of file VPlan.h.
References llvm::VPUser::setOperand().
setStartValue()
void llvm::VPHeaderPHIRecipe::setStartValue (VPValue * V) inline
Update the start value of the recipe.
Definition at line 2058 of file VPlan.h.
References llvm::VPUser::setOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp