LLVM: llvm::CallBase Class Reference
llvm::CallBase Class Reference
Base class for all callable instructions (InvokeInst and CallInst) Holds everything related to calling a function.
#include "llvm/IR/InstrTypes.h"
Classes
struct BundleOpInfo
Used to keep track of an operand bundle.
Public Member Functions
Value * getConvergenceControlToken () const
Return the convergence control token for this call, if it exists.
FunctionType * getFunctionType () const
void mutateFunctionType (FunctionType *FTy)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
User::op_iterator data_operands_begin ()
data_operands_begin/data_operands_end - Return iterators iterating over the call / invoke argument list and bundle operands.
User::const_op_iterator data_operands_begin () const
User::op_iterator data_operands_end ()
User::const_op_iterator data_operands_end () const
iterator_range< User::op_iterator > data_ops ()
iterator_range< User::const_op_iterator > data_ops () const
bool data_operands_empty () const
unsigned data_operands_size () const
bool isDataOperand (const Use *U) const
bool isDataOperand (Value::const_user_iterator UI) const
unsigned getDataOperandNo (Value::const_user_iterator UI) const
Given a value use iterator, return the data operand corresponding to it.
unsigned getDataOperandNo (const Use *U) const
Given a use for a data operand, get the data operand number that corresponds to it.
User::op_iterator arg_begin ()
Return the iterator pointing to the beginning of the argument list.
User::const_op_iterator arg_begin () const
User::op_iterator arg_end ()
Return the iterator pointing to the end of the argument list.
User::const_op_iterator arg_end () const
iterator_range< User::op_iterator > args ()
Iteration adapter for range-for loops.
iterator_range< User::const_op_iterator > args () const
bool arg_empty () const
unsigned arg_size () const
Value * getArgOperand (unsigned i) const
void setArgOperand (unsigned i, Value *v)
const Use & getArgOperandUse (unsigned i) const
Wrappers for getting the Use of a call argument.
Use & getArgOperandUse (unsigned i)
bool isArgOperand (const Use *U) const
bool isArgOperand (Value::const_user_iterator UI) const
unsigned getArgOperandNo (const Use *U) const
Given a use for a arg operand, get the arg operand number that corresponds to it.
unsigned getArgOperandNo (Value::const_user_iterator UI) const
Given a value use iterator, return the arg operand number corresponding to it.
bool hasArgument (const Value *V) const
Returns true if this CallSite passes the given Value* as an argument to the called function.
Value * getCalledOperand () const
const Use & getCalledOperandUse () const
Use & getCalledOperandUse ()
Function * getCalledFunction () const
Returns the function called, or null if this is an indirect function invocation or the function signature does not match the call signature, or the call target is an alias.
LLVM_ABI bool isIndirectCall () const
Return true if the callsite is an indirect call.
bool isCallee (Value::const_user_iterator UI) const
Determine whether the passed iterator points to the callee operand's Use.
bool isCallee (const Use *U) const
Determine whether this Use is the callee operand's Use.
LLVM_ABI Function * getCaller ()
Helper to get the caller (the parent function).
const Function * getCaller () const
LLVM_ABI bool isMustTailCall () const
Tests if this call site must be tail call optimized.
LLVM_ABI bool isTailCall () const
Tests if this call site is marked as a tail call.
LLVM_ABI Intrinsic::ID getIntrinsicID () const
Returns the intrinsic ID of the intrinsic called or Intrinsic::not_intrinsic if the called function is not an intrinsic, or if this is an indirect call.
void setCalledOperand (Value *V)
void setCalledFunction (Function *Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionCallee Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionType *FTy, Value *Fn)
Sets the function called, including updating to the specified function type.
CallingConv::ID getCallingConv () const
void setCallingConv (CallingConv::ID CC)
bool isInlineAsm () const
Check if this call is an inline asm statement.
Attribute API
These methods access and modify attributes on this call (including looking through to the attributes on the called function when necessary).
AttributeList getAttributes () const
Return the attributes for this call.
void setAttributes (AttributeList A)
Set the attributes for this call.
AttributeSet getRetAttributes () const
Return the return attributes for this call.
AttributeSet getParamAttributes (unsigned ArgNo) const
Return the param attributes for this call.
bool tryIntersectAttributes (const CallBase *Other)
Try to intersect the attributes from 'this' CallBase and the 'Other' CallBase.
bool hasFnAttr (Attribute::AttrKind Kind) const
Determine whether this call has the given attribute.
bool hasFnAttr (StringRef Kind) const
Determine whether this call has the given attribute.
void addAttributeAtIndex (unsigned i, Attribute::AttrKind Kind)
adds the attribute to the list of attributes.
void addAttributeAtIndex (unsigned i, Attribute Attr)
adds the attribute to the list of attributes.
void addFnAttr (Attribute::AttrKind Kind)
Adds the attribute to the function.
void addFnAttr (Attribute Attr)
Adds the attribute to the function.
void addRetAttr (Attribute::AttrKind Kind)
Adds the attribute to the return value.
void addRetAttr (Attribute Attr)
Adds the attribute to the return value.
void addRetAttrs (const AttrBuilder &B)
Adds attributes to the return value.
void addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Adds the attribute to the indicated argument.
void addParamAttr (unsigned ArgNo, Attribute Attr)
Adds the attribute to the indicated argument.
void addParamAttrs (unsigned ArgNo, const AttrBuilder &B)
Adds attributes to the indicated argument.
void removeAttributeAtIndex (unsigned i, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
void removeAttributeAtIndex (unsigned i, StringRef Kind)
removes the attribute from the list of attributes.
void removeFnAttrs (const AttributeMask &AttrsToRemove)
Removes the attributes from the function.
void removeFnAttr (Attribute::AttrKind Kind)
Removes the attribute from the function.
void removeFnAttr (StringRef Kind)
Removes the attribute from the function.
void removeRetAttr (Attribute::AttrKind Kind)
Removes the attribute from the return value.
void removeRetAttrs (const AttributeMask &AttrsToRemove)
Removes the attributes from the return value.
void removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Removes the attribute from the given argument.
void removeParamAttr (unsigned ArgNo, StringRef Kind)
Removes the attribute from the given argument.
void removeParamAttrs (unsigned ArgNo, const AttributeMask &AttrsToRemove)
Removes the attributes from the given argument.
void addDereferenceableParamAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
void addDereferenceableRetAttr (uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
void addRangeRetAttr (const ConstantRange &CR)
adds the range attribute to the list of attributes.
bool hasRetAttr (Attribute::AttrKind Kind) const
Determine whether the return value has the given attribute.
bool hasRetAttr (StringRef Kind) const
Determine whether the return value has the given attribute.
Attribute getRetAttr (Attribute::AttrKind Kind) const
Return the attribute for the given attribute kind for the return value.
LLVM_ABI bool paramHasAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Determine whether the argument or parameter has the given attribute.
LLVM_ABI bool paramHasNonNullAttr (unsigned ArgNo, bool AllowUndefOrPoison) const
Return true if this argument has the nonnull attribute on either the CallBase instruction or the called function.
Attribute getAttributeAtIndex (unsigned i, Attribute::AttrKind Kind) const
Get the attribute of a given kind at a position.
Attribute getAttributeAtIndex (unsigned i, StringRef Kind) const
Get the attribute of a given kind at a position.
Attribute getFnAttr (StringRef Kind) const
Get the attribute of a given kind for the function.
Attribute getFnAttr (Attribute::AttrKind Kind) const
Get the attribute of a given kind for the function.
Attribute getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Get the attribute of a given kind from a given arg.
Attribute getParamAttr (unsigned ArgNo, StringRef Kind) const
Get the attribute of a given kind from a given arg.
bool dataOperandHasImpliedAttr (unsigned i, Attribute::AttrKind Kind) const
Return true if the data operand at index i has the attribute A.
LLVM_ABI CaptureInfo getCaptureInfo (unsigned OpNo) const
Return which pointer components this operand may capture.
bool doesNotCapture (unsigned OpNo) const
Determine whether this data operand is not captured.
LLVM_ABI bool hasArgumentWithAdditionalReturnCaptureComponents () const
Returns whether the call has an argument that has an attribute like captures(ret: address, provenance), where the return capture components are not a subset of the other capture components.
bool isByValArgument (unsigned ArgNo) const
Determine whether this argument is passed by value.
bool isInAllocaArgument (unsigned ArgNo) const
Determine whether this argument is passed in an alloca.
bool isPassPointeeByValueArgument (unsigned ArgNo) const
Determine whether this argument is passed by value, in an alloca, or is preallocated.
bool isPassingUndefUB (unsigned ArgNo) const
Determine whether passing undef to this argument is undefined behavior.
bool hasInAllocaArgument () const
Determine if there are is an inalloca argument.
bool doesNotAccessMemory (unsigned OpNo) const
bool onlyReadsMemory (unsigned OpNo) const
bool onlyWritesMemory (unsigned OpNo) const
MaybeAlign getRetAlign () const
Extract the alignment of the return value.
MaybeAlign getParamAlign (unsigned ArgNo) const
Extract the alignment for a call or parameter (0=unknown).
MaybeAlign getParamStackAlign (unsigned ArgNo) const
Type * getParamByRefType (unsigned ArgNo) const
Extract the byref type for a call or parameter.
Type * getParamByValType (unsigned ArgNo) const
Extract the byval type for a call or parameter.
Type * getParamPreallocatedType (unsigned ArgNo) const
Extract the preallocated type for a call or parameter.
Type * getParamInAllocaType (unsigned ArgNo) const
Extract the inalloca type for a call or parameter.
Type * getParamStructRetType (unsigned ArgNo) const
Extract the sret type for a call or parameter.
Type * getParamElementType (unsigned ArgNo) const
Extract the elementtype type for a parameter.
uint64_t getRetDereferenceableBytes () const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getParamDereferenceableBytes (unsigned i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getRetDereferenceableOrNullBytes () const
Extract the number of dereferenceable_or_null bytes for a call (0=unknown).
uint64_t getParamDereferenceableOrNullBytes (unsigned i) const
Extract the number of dereferenceable_or_null bytes for a parameter (0=unknown).
LLVM_ABI FPClassTest getRetNoFPClass () const
Extract a test mask for disallowed floating-point value classes for the return value.
LLVM_ABI FPClassTest getParamNoFPClass (unsigned i) const
Extract a test mask for disallowed floating-point value classes for the parameter.
LLVM_ABI std::optional< ConstantRange > getRange () const
If this return value has a range attribute, return the value range of the argument.
LLVM_ABI bool isReturnNonNull () const
Return true if the return value is known to be not null.
bool returnDoesNotAlias () const
Determine if the return value is marked with NoAlias attribute.
Value * getReturnedArgOperand () const
If one of the arguments has the 'returned' attribute, returns its operand value.
LLVM_ABI Value * getArgOperandWithAttribute (Attribute::AttrKind Kind) const
If one of the arguments has the specified attribute, returns its operand value.
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isStrictFP () const
Determine if the call requires strict floating point semantics.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline ()
LLVM_ABI MemoryEffects getMemoryEffects () const
LLVM_ABI void setMemoryEffects (MemoryEffects ME)
LLVM_ABI bool doesNotAccessMemory () const
Determine if the call does not access memory.
LLVM_ABI void setDoesNotAccessMemory ()
LLVM_ABI bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
LLVM_ABI void setOnlyReadsMemory ()
LLVM_ABI bool onlyWritesMemory () const
Determine if the call does not access or only writes memory.
LLVM_ABI void setOnlyWritesMemory ()
LLVM_ABI bool onlyAccessesArgMemory () const
Determine if the call can access memmory only using pointers based on its arguments.
LLVM_ABI void setOnlyAccessesArgMemory ()
LLVM_ABI bool onlyAccessesInaccessibleMemory () const
Determine if the function may only access memory that is inaccessible from the IR.
LLVM_ABI void setOnlyAccessesInaccessibleMemory ()
LLVM_ABI bool onlyAccessesInaccessibleMemOrArgMem () const
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
LLVM_ABI void setOnlyAccessesInaccessibleMemOrArgMem ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNoCfCheck () const
Determine if the call should not perform indirect branch tracking.
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the invoke cannot be duplicated.
void setCannotDuplicate ()
bool cannotMerge () const
Determine if the call cannot be tail merged.
void setCannotMerge ()
bool isConvergent () const
Determine if the invoke is convergent.
void setConvergent ()
void setNotConvergent ()
bool hasStructRetAttr () const
Determine if the call returns a structure through first pointer argument.
bool hasByValArgument () const
Determine if any call argument is an aggregate passed by value.
Public Member Functions inherited from llvm::Instruction
LLVM_ABI iterator_range< simple_ilist< DbgRecord >::iterator > cloneDebugInfoFrom (const Instruction *From, std::optional< simple_ilist< DbgRecord >::iterator > FromHere=std::nullopt, bool InsertAtHead=false)
Clone any debug-info attached to From onto this instruction.
iterator_range< simple_ilist< DbgRecord >::iterator > getDbgRecordRange () const
Return a range over the DbgRecords attached to this instruction.
LLVM_ABI std::optional< simple_ilist< DbgRecord >::iterator > getDbgReinsertionPosition ()
Return an iterator to the position of the "Next" DbgRecord after this instruction, or std::nullopt.
LLVM_ABI bool hasDbgRecords () const
Returns true if any DbgRecords are attached to this instruction.
LLVM_ABI void adoptDbgRecords (BasicBlock *BB, InstListType::iterator It, bool InsertAtHead)
Transfer any DbgRecords on the position It onto this instruction, by simply adopting the sequence of DbgRecords (which is efficient) if possible, by merging two sequences otherwise.
LLVM_ABI void dropDbgRecords ()
Erase any DbgRecords attached to this instruction.
LLVM_ABI void dropOneDbgRecord (DbgRecord *I)
Erase a single DbgRecord I that is attached to this instruction.
LLVM_ABI void handleMarkerRemoval ()
Handle the debug-info implications of this instruction being removed.
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
LLVM_ABI const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
LLVM_ABI const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
LLVM_ABI const DataLayout & getDataLayout () const
Get the data layout of the module this instruction belongs to.
LLVM_ABI void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
LLVM_ABI InstListType::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void insertBefore(Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
LLVM_ABI void insertBefore (InstListType::iterator InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified position.
LLVM_ABI void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
LLVM_ABI void insertAfter (InstListType::iterator InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified position.
LLVM_ABI InstListType::iterator insertInto (BasicBlock *ParentBB, InstListType::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
LLVM_ABI void insertBefore (BasicBlock &BB, InstListType::iterator InsertPos)
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void moveBefore(Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
LLVM_ABI void moveBefore (InstListType::iterator InsertPos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
LLVM_ABI void moveBeforePreserving (InstListType::iterator MovePos)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI void moveBeforePreserving (BasicBlock &BB, InstListType::iterator I)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI LLVM_DEPRECATED ("Use iterators as instruction positions", "") void moveBeforePreserving(Instruction *MovePos)
Perform a moveBefore operation, while signalling that the caller intends to preserve the original ordering of instructions.
LLVM_ABI void moveBefore (BasicBlock &BB, InstListType::iterator I)
Unlink this instruction and insert into BB before I.
LLVM_ABI void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
LLVM_ABI void moveAfter (InstListType::iterator MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
LLVM_ABI void moveAfterPreserving (Instruction *MovePos)
See moveBeforePreserving .
LLVM_ABI bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
LLVM_ABI std::optional< InstListType::iterator > getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isFPDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isSpecialTerminator () const
LLVM_ABI bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
LLVM_ABI bool hasNonDebugLocLoopMetadata () const
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
LLVM_ABI void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
LLVM_ABI void setMetadata (StringRef Kind, MDNode *Node)
LLVM_ABI void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
LLVM_ABI void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata that matches the predicate.
LLVM_ABI void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
LLVM_ABI void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
LLVM_ABI void addAnnotationMetadata (SmallVector< StringRef > Annotations)
Adds an !annotation metadata node with an array of Annotations as a tuple to this instruction.
LLVM_ABI AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
LLVM_ABI void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
LLVM_ABI void setNoSanitizeMetadata ()
Sets the nosanitize metadata on this instruction.
LLVM_ABI bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
LLVM_ABI const DebugLoc & getStableDebugLoc () const
Fetch the debug location for this node, unless this is a debug intrinsic, in which case fetch the debug location of the next non-debug node.
LLVM_ABI void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setNonNeg (bool b=true)
Set or clear the nneg flag on this instruction, which must be a zext instruction.
LLVM_ABI bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
LLVM_ABI bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
LLVM_ABI bool hasNonNeg () const LLVM_READONLY
Determine whether the the nneg flag is set.
LLVM_ABI bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
LLVM_ABI void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
LLVM_ABI bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
LLVM_ABI void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
LLVM_ABI bool hasPoisonGeneratingReturnAttributes () const LLVM_READONLY
Return true if this instruction has poison-generating attribute.
LLVM_ABI void dropPoisonGeneratingReturnAttributes ()
Drops return attributes that may generate poison.
bool hasPoisonGeneratingAnnotations () const
Return true if this instruction has poison-generating flags, return attributes or metadata.
void dropPoisonGeneratingAnnotations ()
Drops flags, return attributes and metadata that may generate poison.
LLVM_ABI void dropUBImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
LLVM_ABI void dropUBImplyingAttrsAndMetadata (ArrayRef< unsigned > Keep={})
Drop any attributes or metadata that can cause immediate undefined behavior.
LLVM_ABI bool hasUBImplyingAttrs () const LLVM_READONLY
Return true if this instruction has UB-implying attributes that can cause immediate undefined behavior.
LLVM_ABI bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
LLVM_ABI void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
LLVM_ABI void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
LLVM_ABI bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
LLVM_ABI bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
LLVM_ABI bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
LLVM_ABI bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
LLVM_ABI bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
LLVM_ABI bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
LLVM_ABI bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
LLVM_ABI bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
LLVM_ABI FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
LLVM_ABI void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
LLVM_ABI void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
LLVM_ABI void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
LLVM_ABI void applyMergedLocation (DebugLoc LocA, DebugLoc LocB)
Merge 2 debug locations and apply it to the Instruction.
LLVM_ABI void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
LLVM_ABI void dropLocation ()
Drop the instruction's debug location.
LLVM_ABI void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
LLVM_ABI bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
LLVM_ABI bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
LLVM_ABI bool isCommutableOperand (unsigned Op) const LLVM_READONLY
Checks if the operand is commutative.
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
LLVM_ABI bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
LLVM_ABI bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
LLVM_ABI bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
LLVM_ABI bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
LLVM_ABI bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
LLVM_ABI bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
LLVM_ABI Type * getAccessType () const LLVM_READONLY
Return the type this instruction accesses in memory, if any.
LLVM_ABI bool mayThrow (bool IncludePhaseOneUnwind=false) const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
LLVM_ABI bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
LLVM_ABI bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
LLVM_ABI bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
LLVM_ABI bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
LLVM_ABI bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
LLVM_ABI bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
LLVM_ABI Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
LLVM_ABI bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
LLVM_ABI bool isIdenticalToWhenDefined (const Instruction *I, bool IntersectAttrs=false) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
LLVM_ABI bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
LLVM_ABI bool hasSameSpecialState (const Instruction *I2, bool IgnoreAlignment=false, bool IntersectAttrs=false) const LLVM_READONLY
This function determines if the speficied instruction has the same "special" characteristics as the current one.
LLVM_ABI bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
LLVM_ABI unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
LLVM_ABI BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
LLVM_ABI void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
LLVM_ABI void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
LLVM_ABI void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs={})
Drop all unknown metadata except for debug locations.
Public Member Functions inherited from llvm::User
User (const User &)=delete
LLVM_ABI void operator delete (void *Usr)
Free memory allocated for User and Use objects.
LLVM_ABI void operator delete (void *Usr, HungOffOperandsAllocMarker)
Placement delete - required by std, called if the ctor throws.
LLVM_ABI void operator delete (void *Usr, IntrusiveOperandsAndDescriptorAllocMarker)
Placement delete - required by std, called if the ctor throws.
LLVM_ABI void operator delete (void *Usr, IntrusiveOperandsAllocMarker Marker)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
LLVM_ABI ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
LLVM_ABI MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
LLVM_ABI bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
LLVM_ABI bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
LLVM_ABI void deleteValue ()
Delete a pointer to a generic Value.
LLVM_ABI void dump () const
Support for debugging, callable in GDB: V->dump().
Type * getType () const
All values are typed, get the type of this value.
LLVM_ABI LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
LLVM_ABI ValueName * getValueName () const
LLVM_ABI void setValueName (ValueName *VN)
LLVM_ABI StringRef getName () const
Return a constant reference to the value's name.
LLVM_ABI void setName (const Twine &Name)
Change the name of the value.
LLVM_ABI void takeName (Value *V)
Transfer the name from V to this value.
LLVM_ABI std::string getNameOrAsOperand () const
LLVM_ABI void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
LLVM_ABI void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
LLVM_ABI void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
LLVM_ABI void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
LLVM_ABI void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool hasUseList () const
Check if this Value has a use-list.
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
LLVM_ABI bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
LLVM_ABI bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI bool hasOneUser () const
Return true if there is exactly one user of this value.
LLVM_ABI Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
LLVM_ABI User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
LLVM_ABI bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
LLVM_ABI bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
LLVM_ABI void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
LLVM_ABI void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
LLVM_ABI bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
LLVM_ABI unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
LLVM_ABI bool isSwiftError () const
Return true if this value is a swifterror value.
LLVM_ABI const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
LLVM_ABI const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
LLVM_ABI const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
LLVM_ABI const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
LLVM_ABI const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
LLVM_ABI const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr, bool LookThroughIntToPtr=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
LLVM_ABI const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
LLVM_ABI std::optional< int64_t > getPointerOffsetFrom (const Value *Other, const DataLayout &DL) const
If this ptr is provably equal to Other plus a constant offset, return that offset in bytes.
LLVM_ABI bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
LLVM_ABI uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
LLVM_ABI Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
LLVM_ABI const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
LLVM_ABI void reverseUseList ()
Reverse the use-list.
LLVM_ABI void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
LLVM_ABI void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
LLVM_ABI void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock, ilist_iterator_bits< true >, ilist_parent< BasicBlock > >
Instruction * getPrevNode ()
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >, ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty *Parent)
Static Public Member Functions
static LLVM_ABI CallBase * Create (CallBase *CB, ArrayRef< OperandBundleDef > Bundles, InsertPosition InsertPt=nullptr)
Create a clone of CB with a different set of operand bundles and insert it before InsertPt.
static LLVM_ABI CallBase * Create (CallBase *CB, OperandBundleDef Bundle, InsertPosition InsertPt=nullptr)
Create a clone of CB with the operand bundle with the tag matching Bundle's tag replaced with Bundle, and insert it before InsertPt.
static LLVM_ABI CallBase * addOperandBundle (CallBase *CB, uint32_t ID, OperandBundleDef OB, InsertPosition InsertPt=nullptr)
Create a clone of CB with operand bundle OB added.
static LLVM_ABI CallBase * removeOperandBundle (CallBase *CB, uint32_t ID, InsertPosition InsertPt=nullptr)
Create a clone of CB with operand bundle ID removed.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static LLVM_ABI const char * getOpcodeName (unsigned Opcode)
static bool isTerminator (unsigned Opcode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isFPDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned Opcode)
Determine if the Opcode is one of the CastInst instructions.
static bool isFuncletPad (unsigned Opcode)
Determine if the Opcode is one of the FuncletPadInst instructions.
static bool isSpecialTerminator (unsigned Opcode)
Returns true if the Opcode is a "special" terminator that does more than branch to a successor (e.g.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static LLVM_ABI void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Types
using CallInstReservedField = Bitfield::Element<unsigned, 0, 2>
using CallingConvField
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions
template<class... ArgsTy>
CallBase (AttributeList const &A, FunctionType *FT, ArgsTy &&... Args)
bool hasDescriptor () const
unsigned getNumSubclassExtraOperands () const
LLVM_ABI unsigned getNumSubclassExtraOperandsDynamic () const
Get the number of extra operands for instructions that don't have a fixed number of extra operands.
Instruction (const Instruction &)=delete
LLVM_ABI Instruction (Type *Ty, unsigned iType, AllocInfo AllocInfo, InsertPosition InsertBefore=nullptr)
Protected Member Functions inherited from llvm::Instruction
LLVM_ABI ~Instruction ()
template<typename BitfieldElement>
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement>
void setSubclassData (typename BitfieldElement::Type Value)
LLVM_ABI Instruction (Type *Ty, unsigned iType, AllocInfo AllocInfo, InsertPosition InsertBefore=nullptr)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)=delete
LLVM_ABI void * operator new (size_t Size, HungOffOperandsAllocMarker)
Allocate a User with an operand pointer co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
LLVM_ABI void * operator new (size_t Size, IntrusiveOperandsAndDescriptorAllocMarker allocTrait)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, AllocInfo AllocInfo)
LLVM_ABI void allocHungoffUses (unsigned N, bool WithExtraValues=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
LLVM_ABI void growHungoffUses (unsigned N, bool WithExtraValues=false)
Grow the number of hung off uses.
~User ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
LLVM_ABI Value (Type *Ty, unsigned scid)
LLVM_ABI ~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
LLVM_ABI void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
LLVM_ABI bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
LLVM_ABI void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata attachments matching the given predicate.
LLVM_ABI void clearMetadata ()
Erase all metadata attached to this Value.
LLVM_ABI MDNode * getMetadataImpl (unsigned KindID) const
Get metadata for the given kind, if any.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
LLVM_ABI MDNode * getMetadata (StringRef Kind) const
LLVM_ABI void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
LLVM_ABI void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
LLVM_ABI void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
LLVM_ABI void setMetadata (StringRef Kind, MDNode *Node)
LLVM_ABI void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
LLVM_ABI void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock, ilist_iterator_bits< true >, ilist_parent< BasicBlock > >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
ilist_node_impl ()=default
Protected Attributes
AttributeList Attrs
parameter attributes for callable
FunctionType * FTy
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes
static constexpr int CalledOperandOpEndIdx = -1
The last operand is the called operand.
Operand Bundle API
This group of methods provides the API to access and manipulate operand bundles on this call.
using bundle_op_iterator = BundleOpInfo *
using const_bundle_op_iterator = const BundleOpInfo *
unsigned getNumOperandBundles () const
Return the number of operand bundles associated with this User.
bool hasOperandBundles () const
Return true if this User has any operand bundles.
unsigned getBundleOperandsStartIndex () const
Return the index of the first bundle operand in the Use array.
unsigned getBundleOperandsEndIndex () const
Return the index of the last bundle operand in the Use array.
bool isBundleOperand (unsigned Idx) const
Return true if the operand at index Idx is a bundle operand.
bool isOperandBundleOfType (uint32_t ID, unsigned Idx) const
Return true if the operand at index Idx is a bundle operand that has tag ID ID.
bool isBundleOperand (const Use *U) const
Returns true if the use is a bundle operand.
bool isBundleOperand (Value::const_user_iterator UI) const
unsigned getNumTotalBundleOperands () const
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
OperandBundleUse getOperandBundleAt (unsigned Index) const
Return the operand bundle at a specific index.
unsigned countOperandBundlesOfType (StringRef Name) const
Return the number of operand bundles with the tag Name attached to this instruction.
unsigned countOperandBundlesOfType (uint32_t ID) const
Return the number of operand bundles with the tag ID attached to this instruction.
std::optional< OperandBundleUse > getOperandBundle (StringRef Name) const
Return an operand bundle by name, if present.
std::optional< OperandBundleUse > getOperandBundle (uint32_t ID) const
Return an operand bundle by tag ID, if present.
LLVM_ABI void getOperandBundlesAsDefs (SmallVectorImpl< OperandBundleDef > &Defs) const
Return the list of operand bundles attached to this instruction as a vector of OperandBundleDefs.
OperandBundleUse getOperandBundleForOperand (unsigned OpIdx) const
Return the operand bundle for the operand at index OpIdx.
LLVM_ABI bool hasReadingOperandBundles () const
Return true if this operand bundle user has operand bundles that may read from the heap.
LLVM_ABI bool hasClobberingOperandBundles () const
Return true if this operand bundle user has operand bundles that may write to the heap.
bool bundleOperandHasAttr (unsigned OpIdx, Attribute::AttrKind A) const
Return true if the bundle operand at index OpIdx has the attribute A.
bool hasIdenticalOperandBundleSchema (const CallBase &Other) const
Return true if Other has the same sequence of operand bundle tags with the same number of operands on each one of them as this OperandBundleUser.
bool hasOperandBundlesOtherThan (ArrayRef< uint32_t > IDs) const
Return true if this operand bundle user contains operand bundles with tags other than those specified in IDs.
OperandBundleUse operandBundleFromBundleOpInfo (const BundleOpInfo &BOI) const
Simple helper function to map a BundleOpInfo to an OperandBundleUse.
bundle_op_iterator bundle_op_info_begin ()
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_begin () const
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
bundle_op_iterator bundle_op_info_end ()
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_end () const
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
iterator_range< bundle_op_iterator > bundle_op_infos ()
Return the range [bundle_op_info_begin, bundle_op_info_end).
iterator_range< const_bundle_op_iterator > bundle_op_infos () const
Return the range [bundle_op_info_begin, bundle_op_info_end).
LLVM_ABI op_iterator populateBundleOperandInfos (ArrayRef< OperandBundleDef > Bundles, const unsigned BeginIndex)
Populate the BundleOpInfo instances and the Use& vector from Bundles.
bool hasDeoptState () const
Return true if the call has deopt state bundle.
LLVM_ABI BundleOpInfo & getBundleOpInfoForOperand (unsigned OpIdx)
Return the BundleOpInfo for the operand at index OpIdx.
const BundleOpInfo & getBundleOpInfoForOperand (unsigned OpIdx) const
static unsigned CountBundleInputs (ArrayRef< OperandBundleDef > Bundles)
Return the total number of values used in Bundles.
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1 << 0 , CompareUsingScalarTypes = 1 << 1 , CompareUsingIntersectedAttrs = 1 << 2 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
using InstListType
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Public Attributes inherited from llvm::Instruction
DbgMarker * DebugMarker = nullptr
Optional marker recording the position for debugging information that takes effect immediately before this instruction.
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Detailed Description
Base class for all callable instructions (InvokeInst and CallInst) Holds everything related to calling a function.
All call-like instructions are required to use a common operand layout:
Zero or more arguments to the call,
Zero or more operand bundles with zero or more operand inputs each bundle,
Zero or more subclass controlled operands
The called function.
This allows this base class to easily access the called function and the start of the arguments without knowing how many other operands a particular subclass requires. Note that accessing the end of the argument list isn't as cheap as most other operations on the base class.
Definition at line 1114 of file InstrTypes.h.
Member Typedef Documentation
bundle_op_iterator
using llvm::CallBase::bundle_op_iterator = BundleOpInfo *
Definition at line 2194 of file InstrTypes.h.
CallingConvField
using llvm::CallBase::CallingConvField protected
Initial value:
Bitfield::Element<CallingConv::ID, CallInstReservedField::NextBit, 10,
                  CallingConv::MaxID>
Definition at line 1118 of file InstrTypes.h.
CallInstReservedField
using llvm::CallBase::CallInstReservedField = Bitfield::Element<unsigned, 0, 2> protected
Definition at line 1117 of file InstrTypes.h.
const_bundle_op_iterator
using llvm::CallBase::const_bundle_op_iterator = const BundleOpInfo *
Definition at line 2195 of file InstrTypes.h.
Constructor & Destructor Documentation
CallBase()
template<class... ArgsTy> llvm::CallBase::CallBase (AttributeList const & A, FunctionType * FT, ArgsTy &&... Args) inline protected
Definition at line 1132 of file InstrTypes.h.
References A(), Attrs, FTy, and Instruction().
Referenced by addOperandBundle(), arg_begin(), arg_end(), bundle_op_info_begin(), bundle_op_info_end(), llvm::CoroAwaitSuspendInst::classof(), llvm::GCStatepointInst::classof(), Create(), Create(), data_operands_begin(), data_operands_end(), getBundleOpInfoForOperand(), getCaller(), hasIdenticalOperandBundleSchema(), removeOperandBundle(), and tryIntersectAttributes().
Member Function Documentation
addAttributeAtIndex() [1/2]
void llvm::CallBase::addAttributeAtIndex (unsigned i, Attribute Attr) inline
adds the attribute to the list of attributes.
Definition at line 1474 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
addAttributeAtIndex() [2/2]
void llvm::CallBase::addAttributeAtIndex (unsigned i, Attribute::AttrKind Kind) inline
adds the attribute to the list of attributes.
Definition at line 1469 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
addDereferenceableParamAttr()
void llvm::CallBase::addDereferenceableParamAttr (unsigned i, uint64_t Bytes) inline
adds the dereferenceable attribute to the list of attributes.
Definition at line 1574 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
addDereferenceableRetAttr()
void llvm::CallBase::addDereferenceableRetAttr (uint64_t Bytes) inline
adds the dereferenceable attribute to the list of attributes.
Definition at line 1579 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
addFnAttr() [1/2]
void llvm::CallBase::addFnAttr (Attribute Attr) inline
Adds the attribute to the function.
Definition at line 1484 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
addFnAttr() [2/2]
void llvm::CallBase::addFnAttr (Attribute::AttrKind Kind) inline
Adds the attribute to the function.
Definition at line 1479 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
Referenced by llvm::memprof::addAmbiguousAttribute(), addBoundsChecking(), llvm::memprof::CallStackTrie::addSingleAllocTypeAttribute(), llvm::Attributor::createShallowWrapper(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), setCannotDuplicate(), setCannotMerge(), llvm::CallInst::setCanReturnTwice(), setConvergent(), setDoesNotReturn(), setDoesNotThrow(), llvm::setInlineRemark(), setIsNoInline(), setMemoryEffects(), and llvm::VFABI::setVectorVariantNames().
addOperandBundle()
CallBase * CallBase::addOperandBundle (CallBase * CB, uint32_t ID, OperandBundleDef OB, InsertPosition InsertPt = nullptr) static
Create a clone of CB with operand bundle OB added.
Definition at line 580 of file Instructions.cpp.
References CallBase(), Create(), getOperandBundle(), getOperandBundlesAsDefs(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by inlineRetainOrClaimRVCalls().
addParamAttr() [1/2]
void llvm::CallBase::addParamAttr (unsigned ArgNo, Attribute Attr) inline
Adds the attribute to the indicated argument.
Definition at line 1510 of file InstrTypes.h.
References arg_size(), assert(), Attrs, and llvm::Value::getContext().
addParamAttr() [2/2]
void llvm::CallBase::addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) inline
Adds the attribute to the indicated argument.
Definition at line 1504 of file InstrTypes.h.
References arg_size(), assert(), Attrs, and llvm::Value::getContext().
Referenced by addNonNullAttribute(), annotateDereferenceableBytes(), annotateNonNullNoUndefBasedOnAccess(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), CreateGCStatepointCallCommon(), llvm::IRBuilderBase::CreateMaskedCompressStore(), llvm::IRBuilderBase::CreateMaskedExpandLoad(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::IRBuilderBase::CreateThreadLocalAddress(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::VPInterleaveEVLRecipe::execute(), llvm::VPWidenLoadEVLRecipe::execute(), llvm::VPWidenStoreEVLRecipe::execute(), lowerObjCCall(), promoteArguments(), llvm::MemIntrinsicBase< Derived >::setDestAlignment(), and llvm::MemIntrinsicBase< Derived >::setDestAlignment().
addParamAttrs()
void llvm::CallBase::addParamAttrs (unsigned ArgNo, const AttrBuilder & B) inline
Adds attributes to the indicated argument.
Definition at line 1516 of file InstrTypes.h.
References arg_size(), assert(), Attrs, B(), and llvm::Value::getContext().
addRangeRetAttr()
void llvm::CallBase::addRangeRetAttr (const ConstantRange & CR) inline
adds the range attribute to the list of attributes.
Definition at line 1584 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
Referenced by hoistConditionalLoadsStores().
addRetAttr() [1/2]
void llvm::CallBase::addRetAttr (Attribute Attr) inline
Adds the attribute to the return value.
Definition at line 1494 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
addRetAttr() [2/2]
void llvm::CallBase::addRetAttr (Attribute::AttrKind Kind) inline
Adds the attribute to the return value.
Definition at line 1489 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
Referenced by createNVVMInternalAddrspaceWrap(), llvm::IRBuilderBase::CreateThreadLocalAddress(), lowerKernelArguments(), and llvm::InstCombinerImpl::visitCallInst().
addRetAttrs()
void llvm::CallBase::addRetAttrs (const AttrBuilder & B) inline
Adds attributes to the return value.
Definition at line 1499 of file InstrTypes.h.
References Attrs, B(), and llvm::Value::getContext().
arg_begin() [1/2]
User::op_iterator llvm::CallBase::arg_begin () inline
Return the iterator pointing to the beginning of the argument list.
Definition at line 1265 of file InstrTypes.h.
References llvm::User::op_begin().
Referenced by llvm::GCStatepointInst::actual_arg_begin(), arg_begin(), arg_empty(), arg_size(), args(), args(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), doPromotion(), llvm::MLInlineAdvisor::getAdviceImpl(), getArgOperandNo(), llvm::AAResults::getModRefInfo(), hasSameArgumentList(), hostParallelCallback(), llvm::InlineFunctionImpl(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), isArgOperand(), isCondRelevantToAnyCallArgument(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), optimizeModularFormat(), processCall(), ReplaceFPIntrinsicWithCall(), llvm::CoroEndResults::retval_begin(), llvm::CoroEndResults::retval_begin(), targetParallelCallback(), llvm::CoroSuspendRetconInst::value_begin(), and llvm::CoroSuspendRetconInst::value_begin().
arg_begin() [2/2]
User::const_op_iterator llvm::CallBase::arg_begin () const inline
Definition at line 1266 of file InstrTypes.h.
References arg_begin(), and CallBase().
arg_empty()
bool llvm::CallBase::arg_empty () const inline
Definition at line 1287 of file InstrTypes.h.
References arg_begin(), and arg_end().
Referenced by computeBytesPoppedByCalleeForSRet(), hasInAllocaArgument(), and hasStructRetAttr().
arg_end() [1/2]
User::op_iterator llvm::CallBase::arg_end () inline
Return the iterator pointing to the end of the argument list.
Definition at line 1271 of file InstrTypes.h.
References data_operands_end(), and getNumTotalBundleOperands().
Referenced by llvm::GCStatepointInst::actual_arg_end(), arg_empty(), arg_end(), arg_size(), args(), args(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::GCStatepointInst::deopt_begin(), llvm::GCStatepointInst::deopt_end(), doPromotion(), llvm::GCStatepointInst::gc_live_begin(), llvm::GCStatepointInst::gc_live_end(), llvm::GCStatepointInst::gc_transition_args_begin(), llvm::GCStatepointInst::gc_transition_args_end(), llvm::MLInlineAdvisor::getAdviceImpl(), llvm::AAResults::getModRefInfo(), hasSameArgumentList(), hostParallelCallback(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), isArgOperand(), isCondRelevantToAnyCallArgument(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), optimizeModularFormat(), processCall(), ReplaceFPIntrinsicWithCall(), llvm::CoroEndResults::retval_end(), llvm::CoroEndResults::retval_end(), llvm::CoroSuspendRetconInst::value_end(), and llvm::CoroSuspendRetconInst::value_end().
arg_end() [2/2]
User::const_op_iterator llvm::CallBase::arg_end () const inline
Definition at line 1276 of file InstrTypes.h.
References arg_end(), and CallBase().
arg_size()
unsigned llvm::CallBase::arg_size () const inline
Definition at line 1288 of file InstrTypes.h.
References arg_begin(), and arg_end().
Referenced by llvm::GCStatepointInst::actual_arg_begin(), AddParamAndFnBasicAttributes(), addParamAttr(), addParamAttr(), addParamAttrs(), llvm::CoroAsyncEndInst::checkWellFormed(), llvm::OpenMPIRBuilder::createTeams(), dataOperandHasImpliedAttr(), llvm::OpenMPIRBuilder::emitTargetTask(), emitTargetTaskProxyFunction(), getAllocationSize(), getArgOperand(), getArgOperandUse(), getArgOperandUse(), getBundleOpInfoForOperand(), getCaptureInfo(), llvm::ConstrainedFPIntrinsic::getExceptionBehavior(), llvm::MemoryLocation::getForDest(), llvm::CallBrInst::getIndirectDestLabel(), llvm::CallBrInst::getIndirectDestLabelUse(), llvm::CoroAsyncEndInst::getMustTailCallFunction(), llvm::ConstrainedFPIntrinsic::getNonMetadataArgCount(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), getParamAttr(), getParamAttr(), llvm::ConstrainedFPIntrinsic::getRoundingMode(), llvm::AArch64TTIImpl::getTgtMemIntrinsic(), llvm::RISCVTTIImpl::getTgtMemIntrinsic(), llvm::SITargetLowering::getTgtMemIntrinsic(), handleGuaranteedWellDefinedOps(), hasArgumentWithAdditionalReturnCaptureComponents(), hasInAllocaArgument(), hasSameArgumentList(), llvm::InlineFunctionImpl(), llvm::isLegalToPromote(), isReportingError(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::IntrinsicLowering::LowerToByteSwap(), mergeAttributesAndFlags(), onlyReadsMemory(), OptimizeAwayTrappingUsesOfValue(), paramHasAttr(), processCallSite(), removeParamAttr(), removeParamAttr(), removeTriviallyEmptyRange(), setArgOperand(), setInfoSVEStN(), llvm::Attributor::translateArgumentToCallSiteContent(), tryToSplitCallSite(), upgradeAbs(), upgradeAMDGCNIntrinsicCall(), llvm::UpgradeARCRuntime(), upgradeAVX512MaskToSelect(), upgradeDbgIntrinsicToDbgRecord(), llvm::UpgradeIntrinsicCall(), upgradeMaskedCompare(), upgradePMULDQ(), upgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), upgradeX86IntrinsicCall(), upgradeX86Rotate(), llvm::Interpreter::visitCallBase(), and workshareLoopTargetCallback().
args() [1/2]
iterator_range< User::op_iterator > llvm::CallBase::args () inline
Iteration adapter for range-for loops.
Definition at line 1281 of file InstrTypes.h.
References arg_begin(), arg_end(), and llvm::make_range().
Referenced by addNonNullAttribute(), adjustInliningThresholdUsingCallee(), buildIntrinsicArgTypes(), llvm::changeToInvokeAndSplitBasicBlock(), collectEscapedLocals(), doesInTreeUserNeedToExtract(), getCallArgsTotalAllocaSize(), llvm::objcarc::GetCallSiteClass(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), hasArgument(), llvm::InlineFunctionImpl(), isPredicatedOnPHI(), llvm::CallLowering::lowerCall(), llvm::makeGuardControlFlowExplicit(), markTails(), modifyIntrinsicCall(), processCallSite(), runIPSCCP(), setConstantInArgument(), llvm::LoopVectorizationCostModel::setVectorizedCallDecision(), splitCallSite(), upgradeAArch64IntrinsicCall(), upgradeAMDGCNIntrinsicCall(), upgradeARMIntrinsicCall(), upgradeAVX512MaskToSelect(), llvm::UpgradeIntrinsicCall(), upgradeX86IntrinsicCall(), llvm::Interpreter::visitCallBase(), and llvm::InstCombinerImpl::visitCallInst().
args() [2/2]
iterator_range< User::const_op_iterator > llvm::CallBase::args () const inline
Definition at line 1284 of file InstrTypes.h.
References arg_begin(), arg_end(), and llvm::make_range().
bundle_op_info_begin() [1/2]
bundle_op_iterator llvm::CallBase::bundle_op_info_begin () inline
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
OperandBundleUser uses the descriptor area co-allocated with the host User to store some meta information about which operands are "normal" operands, and which ones belong to some operand bundle.
The layout of an operand bundle user is
     +-----------uint32_t End-------------------------------------+
     |                                                            |
     |  +--------uint32_t Begin--------------------+              |
     |  |                                          |              |
     ^  ^                                          v              v
|---—|---—|-—|-—|-—|-—|-—|------—|-—|------—|-—|--— | BOI0 | BOI1 | .. | DU | U0 | U1 | .. | BOI0_U0 | .. | BOI1_U0 | .. | Un |---—|---—|-—|-—|-—|-—|-—|------—|-—|------—|-—|--— v v ^ ^ | | | | | +-----—uint32_t Begin---------—+ | | | +--------—uint32_t End--------------------------—+
BOI0, BOI1 ... are descriptions of operand bundles in this User's use list. These descriptions are installed and managed by this class, and they're all instances of OperandBundleUser<T>::BundleOpInfo.
DU is an additional descriptor installed by User's 'operator new' to keep track of the 'BOI0 ... BOIN' co-allocation. OperandBundleUser does not access or modify DU in any way, it's an implementation detail private to User.
The regular Use& vector for the User starts at U0. The operand bundle uses are part of the Use& vector, just like normal uses. In the diagram above, the operand bundle uses start at BOI0_U0. Each instance of BundleOpInfo has information about a contiguous set of uses constituting an operand bundle, and the total set of operand bundle uses themselves form a contiguous set of uses (i.e. there are no gaps between uses corresponding to individual operand bundles).
This class does not know the location of the set of operand bundle uses within the use list – that is decided by the User using this class via the BeginIdx argument in populateBundleOperandInfos.
Currently operand bundle users with hung-off operands are not supported.
Definition at line 2243 of file InstrTypes.h.
References llvm::User::getDescriptor(), and hasDescriptor().
Referenced by bundle_op_infos(), bundle_op_infos(), getBundleOperandsStartIndex(), getBundleOpInfoForOperand(), getNumOperandBundles(), getOperandBundleAt(), hasIdenticalOperandBundleSchema(), and processCall().
bundle_op_info_begin() [2/2]
const_bundle_op_iterator llvm::CallBase::bundle_op_info_begin () const inline
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
Definition at line 2253 of file InstrTypes.h.
References CallBase().
bundle_op_info_end() [1/2]
bundle_op_iterator llvm::CallBase::bundle_op_info_end () inline
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
Definition at line 2260 of file InstrTypes.h.
References llvm::User::getDescriptor(), and hasDescriptor().
Referenced by bundle_op_infos(), bundle_op_infos(), getBundleOperandsEndIndex(), getBundleOpInfoForOperand(), getNumOperandBundles(), hasIdenticalOperandBundleSchema(), and processCall().
bundle_op_info_end() [2/2]
const_bundle_op_iterator llvm::CallBase::bundle_op_info_end () const inline
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
Definition at line 2270 of file InstrTypes.h.
References CallBase().
bundle_op_infos() [1/2]
iterator_range< bundle_op_iterator > llvm::CallBase::bundle_op_infos () inline
Return the range [bundle_op_info_begin, bundle_op_info_end).
Definition at line 2276 of file InstrTypes.h.
References bundle_op_info_begin(), bundle_op_info_end(), and llvm::make_range().
Referenced by getBundleOpInfoForOperand(), populateBundleOperandInfos(), and llvm::objcarc::BundledRetainClaimRVs::~BundledRetainClaimRVs().
bundle_op_infos() [2/2]
iterator_range< const_bundle_op_iterator > llvm::CallBase::bundle_op_infos () const inline
Return the range [bundle_op_info_begin, bundle_op_info_end).
Definition at line 2281 of file InstrTypes.h.
References bundle_op_info_begin(), bundle_op_info_end(), and llvm::make_range().
bundleOperandHasAttr()
bool llvm::CallBase::bundleOperandHasAttr (unsigned OpIdx, Attribute::AttrKind A) const inline
Return true if the bundle operand at index OpIdx has the attribute A.
Definition at line 2137 of file InstrTypes.h.
References A(), getBundleOpInfoForOperand(), operandBundleFromBundleOpInfo(), and OpIdx.
Referenced by dataOperandHasImpliedAttr().
cannotDuplicate()
bool llvm::CallBase::cannotDuplicate () const inline
Determine if the invoke cannot be duplicated.
Definition at line 1957 of file InstrTypes.h.
References hasFnAttr().
Referenced by canSplitCallSite().
cannotMerge()
bool llvm::CallBase::cannotMerge () const inline
Determine if the call cannot be tail merged.
Definition at line 1961 of file InstrTypes.h.
References hasFnAttr().
classof() [1/2]
bool llvm::CallBase::classof (const Instruction * I) inline static
Definition at line 1194 of file InstrTypes.h.
References I, and Instruction().
Referenced by classof().
classof() [2/2]
bool llvm::CallBase::classof (const Value * V) inline static
Definition at line 1199 of file InstrTypes.h.
References llvm::cast(), classof(), and llvm::isa().
CountBundleInputs()
unsigned llvm::CallBase::CountBundleInputs (ArrayRef< OperandBundleDef > Bundles) inline static protected
Return the total number of values used in Bundles.
Definition at line 2311 of file InstrTypes.h.
References B(), and llvm::Total.
countOperandBundlesOfType() [1/2]
unsigned llvm::CallBase::countOperandBundlesOfType (StringRef Name) const inline
Return the number of operand bundles with the tag Name attached to this instruction.
Definition at line 2057 of file InstrTypes.h.
References llvm::Count, getNumOperandBundles(), and getOperandBundleAt().
Referenced by getOperandBundle(), getOperandBundle(), llvm::CallLowering::lowerCall(), and llvm::SelectionDAGBuilder::LowerCallTo().
countOperandBundlesOfType() [2/2]
unsigned llvm::CallBase::countOperandBundlesOfType (uint32_t ID) const inline
Return the number of operand bundles with the tag ID attached to this instruction.
Definition at line 2068 of file InstrTypes.h.
References llvm::Count, getNumOperandBundles(), and getOperandBundleAt().
Create() [1/2]
CallBase * CallBase::Create (CallBase * CB, ArrayRef< OperandBundleDef > Bundles, InsertPosition InsertPt = nullptr) static
Create a clone of CB with a different set of operand bundles and insert it before InsertPt.
The returned call instruction is identical CB in every way except that the operand bundles for the new instruction are set to the operand bundles in Bundles.
Definition at line 294 of file Instructions.cpp.
References CallBase(), llvm::cast(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::Instruction::getOpcode(), and llvm_unreachable.
Referenced by addOperandBundle(), Create(), llvm::InlineFunctionImpl(), PropagateOperandBundles(), removeOperandBundle(), RemovePreallocated(), and llvm::DropUnnecessaryAssumesPass::run().
Create() [2/2]
CallBase * CallBase::Create (CallBase * CB, OperandBundleDef Bundle, InsertPosition InsertPt = nullptr) static
Create a clone of CB with the operand bundle with the tag matching Bundle's tag replaced with Bundle, and insert it before InsertPt.
The returned call instruction is identical CI in every way except that the specified operand bundle has been replaced.
Definition at line 308 of file Instructions.cpp.
References CallBase(), Create(), llvm::SmallVectorImpl< T >::emplace_back(), getNumOperandBundles(), getOperandBundleAt(), and llvm::OperandBundleDefT< InputTy >::getTag().
data_operands_begin() [1/2]
User::op_iterator llvm::CallBase::data_operands_begin () inline
data_operands_begin/data_operands_end - Return iterators iterating over the call / invoke argument list and bundle operands.
For invokes, this is the set of instruction operands except the invoke target and the two successor blocks; and for calls this is the set of instruction operands except the call target.
Definition at line 1217 of file InstrTypes.h.
References llvm::User::op_begin().
Referenced by data_operands_begin(), data_operands_empty(), data_operands_size(), data_ops(), data_ops(), getDataOperandNo(), and isDataOperand().
data_operands_begin() [2/2]
User::const_op_iterator llvm::CallBase::data_operands_begin () const inline
Definition at line 1218 of file InstrTypes.h.
References CallBase(), and data_operands_begin().
data_operands_empty()
bool llvm::CallBase::data_operands_empty () const inline
Definition at line 1235 of file InstrTypes.h.
References data_operands_begin(), and data_operands_end().
data_operands_end() [1/2]
User::op_iterator llvm::CallBase::data_operands_end () inline
Definition at line 1221 of file InstrTypes.h.
References getNumSubclassExtraOperands(), and llvm::User::op_end().
Referenced by arg_end(), data_operands_empty(), data_operands_end(), data_operands_size(), data_ops(), data_ops(), and isDataOperand().
data_operands_end() [2/2]
User::const_op_iterator llvm::CallBase::data_operands_end () const inline
Definition at line 1226 of file InstrTypes.h.
References CallBase(), and data_operands_end().
data_operands_size()
unsigned llvm::CallBase::data_operands_size () const inline
Definition at line 1238 of file InstrTypes.h.
References data_operands_begin(), and data_operands_end().
data_ops() [1/2]
iterator_range< User::op_iterator > llvm::CallBase::data_ops () inline
Definition at line 1229 of file InstrTypes.h.
References data_operands_begin(), data_operands_end(), and llvm::make_range().
data_ops() [2/2]
iterator_range< User::const_op_iterator > llvm::CallBase::data_ops () const inline
Definition at line 1232 of file InstrTypes.h.
References data_operands_begin(), data_operands_end(), and llvm::make_range().
dataOperandHasImpliedAttr()
bool llvm::CallBase::dataOperandHasImpliedAttr (unsigned i, Attribute::AttrKind Kind) const inline
Return true if the data operand at index i has the attribute A.
Data operands include call arguments and values used in operand bundles, but does not include the callee operand.
The index i is interpreted as
i in [0, arg_size) -> argument number (i) i in [arg_size, data_operand_size) -> bundle operand at index (i) in the operand list.
Definition at line 1674 of file InstrTypes.h.
References arg_size(), assert(), bundleOperandHasAttr(), getBundleOperandsStartIndex(), getNumTotalBundleOperands(), hasOperandBundles(), and paramHasAttr().
Referenced by determinePointerAccessAttrs(), doesNotAccessMemory(), onlyReadsMemory(), and onlyWritesMemory().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::CallBase::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
doesNoCfCheck()
bool llvm::CallBase::doesNoCfCheck () const inline
Determine if the call should not perform indirect branch tracking.
Definition at line 1950 of file InstrTypes.h.
References hasFnAttr().
doesNotAccessMemory() [1/2]
bool CallBase::doesNotAccessMemory () const
Determine if the call does not access memory.
Determine if the function does not access memory.
Definition at line 653 of file Instructions.cpp.
References llvm::MemoryEffectsBase< LocationEnum >::doesNotAccessMemory(), and getMemoryEffects().
doesNotAccessMemory() [2/2]
bool llvm::CallBase::doesNotAccessMemory (unsigned OpNo) const inline
Definition at line 1743 of file InstrTypes.h.
References dataOperandHasImpliedAttr().
Referenced by determinePointerAccessAttrs(), isTrigLibCall(), and markTails().
doesNotCapture()
bool llvm::CallBase::doesNotCapture (unsigned OpNo) const inline
Determine whether this data operand is not captured.
Definition at line 1697 of file InstrTypes.h.
References llvm::capturesNothing(), and getCaptureInfo().
doesNotReturn()
bool llvm::CallBase::doesNotReturn () const inline
Determine if the call cannot return.
Definition at line 1946 of file InstrTypes.h.
References hasFnAttr().
doesNotThrow()
bool llvm::CallBase::doesNotThrow () const inline
Determine if the call cannot unwind.
Definition at line 1953 of file InstrTypes.h.
References hasFnAttr().
Referenced by HandleCallsInBlockInlinedThroughInvoke(), llvm::InlineFunctionImpl(), isRemovableWrite(), isTrigLibCall(), and llvm::InstCombinerImpl::visitCallInst().
getArgOperand()
Value * llvm::CallBase::getArgOperand (unsigned i) const inline
Definition at line 1290 of file InstrTypes.h.
References arg_size(), assert(), and llvm::User::getOperand().
Referenced by AddAlignmentAssumptions(), addArgumentAttrsFromCallsites(), addIntrinsicToSummary(), llvm::SystemZTTIImpl::adjustInliningThreshold(), annotateDereferenceableBytes(), annotateNonNullNoUndefBasedOnAccess(), aspaceMemCpy(), aspaceMemMove(), aspaceMemSet(), checkIfSupported(), llvm::AnyCoroIdRetconInst::checkWellFormed(), llvm::CoroIdAsyncInst::checkWellFormed(), llvm::CoroIdInst::clearPromise(), convertFSqrtDivIntoFMul(), convertStrToInt(), llvm::OpenMPIRBuilder::createTeams(), DoLowering(), llvm::OpenMPIRBuilder::emitTargetTask(), emitTargetTaskProxyFunction(), expandIsFPClass(), expandUsubSat(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::AMDGPULibCalls::fold(), foldCtpopPow2Test(), llvm::funcReturnsFirstArgOfCall(), llvm::GCStatepointInst::getActualCalledOperand(), llvm::CoroAllocaAllocInst::getAlignment(), llvm::CoroPromiseInst::getAlignment(), llvm::CoroAllocaFreeInst::getAlloc(), llvm::CoroAllocaGetInst::getAlloc(), llvm::AnyCoroIdRetconInst::getAllocFunction(), llvm::getAllocSize(), llvm::VAEndInst::getArgList(), llvm::VAStartInst::getArgList(), getArgOperandWithAttribute(), llvm::CoroAsyncContextDeallocInst::getAsyncContext(), llvm::CoroSuspendAsyncInst::getAsyncContextProjectionFunction(), llvm::CoroAsyncContextAllocInst::getAsyncFunctionPointer(), llvm::CoroIdAsyncInst::getAsyncFunctionPointer(), llvm::PseudoProbeInst::getAttributes(), llvm::CoroAwaitSuspendInst::getAwaiter(), llvm::GCRelocateInst::getBasePtrIndex(), llvm::InstrProfMCDCTVBitmapUpdate::getBitmapIndex(), getBranchWeight(), llvm::InstrProfCallsite::getCallee(), getCoopAtomicOperandsInfo(), llvm::CoroSuspendInst::getCoroSave(), llvm::CoroIdInst::getCoroutine(), llvm::CoroBeginInst::getCustomABI(), llvm::AnyCoroIdRetconInst::getDeallocFunction(), llvm::GCRelocateInst::getDerivedPtrIndex(), llvm::VACopyInst::getDest(), llvm::ConstrainedFPIntrinsic::getExceptionBehavior(), llvm::PseudoProbeInst::getFactor(), llvm::GCStatepointInst::getFlags(), llvm::MemoryLocation::getForDest(), llvm::MemoryLocation::getForSource(), llvm::CoroAwaitSuspendInst::getFrame(), llvm::CoroFreeInst::getFrame(), llvm::CoroSubFnInst::getFrame(), llvm::getFreedOperand(), llvm::PseudoProbeInst::getFuncGuid(), llvm::InstrProfInstBase::getHash(), llvm::GCStatepointInst::getID(), llvm::CoroBeginInst::getId(), llvm::InstrProfCntrInstBase::getIndex(), llvm::InstrProfValueProfileInst::getIndex(), llvm::PseudoProbeInst::getIndex(), getISDForVPIntrinsic(), KernelInfo::getKernelEnvironementGVFromKernelInitCB(), llvm::MemIntrinsicBase< Derived >::getLength(), llvm::BinaryOpIntrinsic::getLHS(), llvm::CmpIntrinsic::getLHS(), llvm::MinMaxIntrinsic::getLHS(), llvm::VPIntrinsic::getMaskParam(), llvm::InstrProfMCDCTVBitmapUpdate::getMCDCCondBitmapAddr(), llvm::CoroBeginInst::getMem(), llvm::VPIntrinsic::getMemoryDataParam(), llvm::VPIntrinsic::getMemoryPointerParam(), llvm::CoroAsyncEndInst::getMustTailCallFunction(), llvm::CoroSuspendAsyncInst::getMustTailCallFunction(), llvm::InstrProfInstBase::getNameValue(), llvm::InstrProfMCDCBitmapInstBase::getNumBitmapBits(), llvm::GCStatepointInst::getNumCallArgs(), llvm::InstrProfCntrInstBase::getNumCounters(), llvm::GCStatepointInst::getNumPatchBytes(), llvm::AArch64TTIImpl::getOrCreateResultFromMemIntrinsic(), llvm::ConstrainedFPCmpIntrinsic::getPredicate(), llvm::VPCmpIntrinsic::getPredicate(), llvm::CoroIdInst::getPromise(), llvm::AnyCoroIdRetconInst::getPrototype(), llvm::DbgAssignIntrinsic::getRawAddress(), llvm::DbgAssignIntrinsic::getRawAddressExpression(), llvm::DbgAssignIntrinsic::getRawAssignID(), llvm::MemIntrinsicBase< Derived >::getRawDest(), llvm::AnyMemIntrinsic::getRawElementSizeInBytes(), llvm::DbgVariableIntrinsic::getRawExpression(), llvm::CoroSubFnInst::getRawIndex(), llvm::CoroIdInst::getRawInfo(), llvm::DbgLabelInst::getRawLabel(), llvm::DbgVariableIntrinsic::getRawLocation(), llvm::DbgVariableIntrinsic::getRawVariable(), llvm::dxil::getResourceNameFromBindingCall(), llvm::AnyCoroEndInst::getResults(), llvm::CoroSuspendAsyncInst::getResumeFunction(), llvm::BinaryOpIntrinsic::getRHS(), llvm::CmpIntrinsic::getRHS(), llvm::MinMaxIntrinsic::getRHS(), llvm::ConstrainedFPIntrinsic::getRoundingMode(), llvm::CoroAllocaAllocInst::getSize(), llvm::VACopyInst::getSrc(), llvm::GCProjectionInst::getStatepoint(), llvm::InstrProfIncrementInst::getStep(), llvm::AnyCoroIdRetconInst::getStorage(), llvm::AnyCoroIdRetconInst::getStorageAlignment(), llvm::CoroIdAsyncInst::getStorageAlignment(), llvm::CoroIdAsyncInst::getStorageArgumentIndex(), llvm::CoroSuspendAsyncInst::getStorageArgumentIndex(), llvm::AnyCoroIdRetconInst::getStorageSize(), llvm::CoroIdAsyncInst::getStorageSize(), llvm::InstrProfValueProfileInst::getTargetValue(), llvm::AArch64TTIImpl::getTgtMemIntrinsic(), llvm::GCNTTIImpl::getTgtMemIntrinsic(), llvm::PPCTTIImpl::getTgtMemIntrinsic(), llvm::RISCVTTIImpl::getTgtMemIntrinsic(), llvm::SITargetLowering::getTgtMemIntrinsic(), llvm::InstrProfValueProfileInst::getValueKind(), llvm::VPIntrinsic::getVectorLengthParam(), llvm::MemIntrinsic::getVolatileCst(), llvm::MemSetPatternInst::getVolatileCst(), llvm::RISCVTTIImpl::getVPLegalizationStrategy(), llvm::CoroAwaitSuspendInst::getWrapperFunction(), handleBrSelExpect(), handleGuaranteedWellDefinedOps(), handlePhiDef(), handleSwitchExpect(), hasArgumentWithAdditionalReturnCaptureComponents(), llvm::AnyCoroEndInst::hasResults(), llvm::InlineFunctionImpl(), InsertStackProtectors(), instCombineSVEPTest(), llvm::CoroSuspendInst::isFinal(), llvm::CoroPromiseInst::isFromPromise(), isKnownNonZeroFromOperator(), llvm::isLegalToPromote(), llvm::GCNTTIImpl::isReadRegisterSourceOfDivergence(), isReportingError(), llvm::GCProjectionInst::isTiedToInvoke(), llvm::AnyCoroEndInst::isUnwind(), lowerConstrainedFPCmpIntrinsic(), lowerExpectIntrinsic(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::lowerObjectSizeCall(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::lowerUnaryVectorIntrinsicAsLoop(), llvm::makeGuardControlFlowExplicit(), memChrToCharCompare(), mergeAttributesAndFlags(), OptimizeAwayTrappingUsesOfValue(), optimizeCallInst(), optimizeDoubleFP(), OptimizeEmptyGlobalAtExitDtors(), optimizeNaN(), optimizeSymmetricCall(), paramHasNonNullAttr(), llvm::promoteCall(), RemovePreallocated(), ReplaceFPIntrinsicWithCall(), replacePrepare(), replaceUnaryCall(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), scalarizeMaskedVectorHistogram(), llvm::CoroIdInst::setCoroutineSelf(), setInfoSVEStN(), llvm::LoopVectorizationCostModel::setVectorizedCallDecision(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), stripDebugDeclareImpl(), llvm::JumpThreadingPass::threadGuard(), tryToMoveFreeBeforeNullTest(), turnGuardIntoBranch(), unwrapMAVMetadataOp(), unwrapMAVOp(), upgradeAbs(), upgradeAMDGCNIntrinsicCall(), llvm::UpgradeARCRuntime(), upgradeARMIntrinsicCall(), upgradeAVX512MaskToSelect(), upgradeDbgIntrinsicToDbgRecord(), llvm::UpgradeIntrinsicCall(), upgradeMaskedCompare(), upgradeMaskedMove(), upgradeMaskToInt(), upgradeNVVMIntrinsicCall(), upgradePMULDQ(), upgradeVectorSplice(), upgradeX86ConcatShift(), upgradeX86IntrinsicCall(), upgradeX86MaskedShift(), upgradeX86Rotate(), upgradeX86vpcom(), upgradeX86VPERMT2Intrinsics(), llvm::ObjectSizeOffsetEvaluator::visitCallBase(), llvm::InstCombinerImpl::visitCallInst(), and workshareLoopTargetCallback().
getArgOperandNo() [1/2]
unsigned llvm::CallBase::getArgOperandNo (const Use * U) const inline
Given a use for a arg operand, get the arg operand number that corresponds to it.
Definition at line 1321 of file InstrTypes.h.
References arg_begin(), assert(), and isArgOperand().
Referenced by adjustInliningThresholdUsingCallee(), getArgOperandNo(), and runIPSCCP().
getArgOperandNo() [2/2]
unsigned llvm::CallBase::getArgOperandNo (Value::const_user_iterator UI) const inline
Given a value use iterator, return the arg operand number corresponding to it.
Iterator must actually correspond to a data operand.
Definition at line 1328 of file InstrTypes.h.
References getArgOperandNo().
getArgOperandUse() [1/2]
Use & llvm::CallBase::getArgOperandUse (unsigned i) inline
Definition at line 1305 of file InstrTypes.h.
References arg_size(), assert(), and llvm::User::getOperandUse().
getArgOperandUse() [2/2]
const Use & llvm::CallBase::getArgOperandUse (unsigned i) const inline
Wrappers for getting the Use of a call argument.
Definition at line 1301 of file InstrTypes.h.
References arg_size(), assert(), and llvm::User::getOperandUse().
Referenced by llvm::IRPosition::callsite_argument(), llvm::MemIntrinsicBase< Derived >::getLengthUse(), llvm::MemIntrinsicBase< Derived >::getLengthUse(), llvm::MemIntrinsicBase< Derived >::getRawDestUse(), and llvm::MemIntrinsicBase< Derived >::getRawDestUse().
getArgOperandWithAttribute()
Value * CallBase::getArgOperandWithAttribute (Attribute::AttrKind Kind) const
If one of the arguments has the specified attribute, returns its operand value.
Otherwise, return nullptr.
Definition at line 397 of file Instructions.cpp.
References Attrs, F, getArgOperand(), and getCalledFunction().
Referenced by llvm::getFreedOperand(), llvm::getReallocatedOperand(), getReturnedArgOperand(), and hasInitializesAttr().
getAttributeAtIndex() [1/2]
Attribute llvm::CallBase::getAttributeAtIndex (unsigned i, Attribute::AttrKind Kind) const inline
Get the attribute of a given kind at a position.
Definition at line 1620 of file InstrTypes.h.
References getAttributes().
getAttributeAtIndex() [2/2]
Attribute llvm::CallBase::getAttributeAtIndex (unsigned i, StringRef Kind) const inline
Get the attribute of a given kind at a position.
Definition at line 1625 of file InstrTypes.h.
References getAttributes().
getAttributes()
AttributeList llvm::CallBase::getAttributes () const inline
Return the attributes for this call.
Definition at line 1422 of file InstrTypes.h.
References Attrs.
Referenced by llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), doPromotion(), expandAtan2Intrinsic(), expandExpIntrinsic(), expandLogIntrinsic(), expandPowIntrinsic(), getAttributeAtIndex(), getAttributeAtIndex(), getFnAttr(), getFnAttr(), getMemoryEffects(), getParamAttr(), getParamAttr(), getParamAttributes(), getRetAttributes(), llvm::InlineFunctionImpl(), llvm::isLegalToPromote(), lowerAwaitSuspend(), llvm::CallLowering::lowerCall(), makeStatepointExplicitImpl(), optimizeCallInst(), processCall(), processCallSite(), llvm::promoteCall(), RemoveAttribute(), tryIntersectAttributes(), tryToMoveFreeBeforeNullTest(), upgradeAMDGCNIntrinsicCall(), and llvm::UpgradeIntrinsicCall().
getBundleOperandsEndIndex()
unsigned llvm::CallBase::getBundleOperandsEndIndex () const inline
Return the index of the last bundle operand in the Use array.
Definition at line 2008 of file InstrTypes.h.
References assert(), bundle_op_info_end(), llvm::CallBase::BundleOpInfo::End, and hasOperandBundles().
Referenced by getNumTotalBundleOperands(), and isBundleOperand().
getBundleOperandsStartIndex()
unsigned llvm::CallBase::getBundleOperandsStartIndex () const inline
Return the index of the first bundle operand in the Use array.
Definition at line 2002 of file InstrTypes.h.
References assert(), llvm::CallBase::BundleOpInfo::Begin, bundle_op_info_begin(), and hasOperandBundles().
Referenced by dataOperandHasImpliedAttr(), getNumTotalBundleOperands(), getSameOpcode(), and isBundleOperand().
getBundleOpInfoForOperand() [1/2]
CallBase::BundleOpInfo & CallBase::getBundleOpInfoForOperand (unsigned OpIdx)
Return the BundleOpInfo for the operand at index OpIdx.
It is an error to call this with an OpIdx that does not correspond to an bundle operand.
When there isn't many bundles, we do a simple linear search. Else fallback to a binary-search that use the fact that bundles usually have similar number of argument to get faster convergence.
We need a decimal number below and to prevent using floating point numbers we use an intergal value multiplied by this constant.
Definition at line 533 of file Instructions.cpp.
References arg_size(), assert(), llvm::CallBase::BundleOpInfo::Begin, bundle_op_info_begin(), bundle_op_info_end(), bundle_op_infos(), llvm::CallBase::BundleOpInfo::End, llvm_unreachable, and OpIdx.
Referenced by bundleOperandHasAttr(), getBundleOpInfoForOperand(), getCaptureInfo(), and getOperandBundleForOperand().
getBundleOpInfoForOperand() [2/2]
const BundleOpInfo & llvm::CallBase::getBundleOpInfoForOperand (unsigned OpIdx) const inline
Definition at line 2305 of file InstrTypes.h.
References CallBase(), getBundleOpInfoForOperand(), and OpIdx.
getCalledFunction()
Function * llvm::CallBase::getCalledFunction () const inline
Returns the function called, or null if this is an indirect function invocation or the function signature does not match the call signature, or the call target is an alias.
Definition at line 1346 of file InstrTypes.h.
References llvm::dyn_cast_or_null(), F, getCalledOperand(), and getFunctionType().
Referenced by AddAliasScopeMetadata(), AddAlignmentAssumptions(), addArgumentAttrsFromCallsites(), addIntrinsicToSummary(), addMappingsFromTLI(), AddParamAndFnBasicAttributes(), AddReturnAttributes(), addSaturatedDecorationToIntrinsic(), addVariantDeclaration(), llvm::SystemZTTIImpl::adjustInliningThreshold(), llvm::CanInlineCallSite(), llvm::CoroAwaitSuspendInst::classof(), llvm::OpenMPIRBuilder::createParallel(), determinePointerAccessAttrs(), doCallSiteSplitting(), DoLowering(), doPromotion(), emitTargetTaskProxyFunction(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::AMDGPULibCalls::fold(), foldFrexpOfSelect(), llvm::InlineAdvisor::getAdvice(), llvm::MLInlineAdvisor::getAdviceImpl(), llvm::ReplayInlineAdvisor::getAdviceImpl(), llvm::objcarc::GetARCInstKind(), getArgOperandWithAttribute(), llvm::GCNTTIImpl::getCallerAllocaCost(), getDefaultInlineAdvice(), llvm::getIntrinsicForCallSite(), llvm::TargetLibraryInfo::getLibFunc(), llvm::InlineAdvisor::getMandatoryKind(), llvm::MDNode::getMergedProfMetadata(), getParamByRefType(), getParamByValType(), getParamInAllocaType(), getParamNoFPClass(), getParamPreallocatedType(), getParamStructRetType(), getRange(), llvm::dxil::getResourceNameFromBindingCall(), getRetAlign(), getRetAttr(), getRetDereferenceableBytes(), getRetDereferenceableOrNullBytes(), getRetNoFPClass(), getSameOpcode(), llvm::LoopVectorizationCostModel::getVectorCallCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), handleBrSelExpect(), HandleCallsInBlockInlinedThroughInvoke(), handlePhiDef(), handleSwitchExpect(), llvm::hasAssumption(), llvm::InlineFunction(), llvm::InlineFunctionImpl(), InstrBreaksNoFree(), InstrBreaksNonConvergent(), InstrBreaksNoSync(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), isFunctionMallocLike(), isIntrinsicOrLFToBeTailCalled(), llvm::isLegalToPromote(), isReturnNonNull(), isSMEABIRoutineCall(), llvm::isTLIScalarize(), lowerAwaitSuspend(), llvm::NVPTXTargetLowering::LowerCall(), lowerExpectIntrinsic(), llvm::IntrinsicLowering::LowerIntrinsicCall(), MayAutorelease(), llvm::maybeMarkSanitizerLibraryCallNoBuiltin(), mayHaveRecursiveCallee(), modifyIntrinsicCall(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), optimizeDoubleFP(), optimizeModularFormat(), optimizeSymmetricCall(), paramHasAttr(), llvm::SITargetLowering::passSpecialInputs(), llvm::promoteCall(), llvm::SCCPInstVisitor::resolvedUndef(), restoreMutatedType(), llvm::AMDGPULowerKernelAttributesPass::run(), llvm::InlineCostAnnotationPrinterPass::run(), llvm::InlinerPass::run(), llvm::ModuleInlinerPass::run(), runCGProfilePass(), llvm::IRSimilarity::IRInstructionData::setCalleeName(), llvm::LoopVectorizationCostModel::setVectorizedCallDecision(), shouldBeDeferred(), shouldCheckArgs(), llvm::shouldInline(), llvm::SMECallAttrs::SMECallAttrs(), llvm::PPCTargetLowering::supportsTailCallFor(), trackInlinedStores(), llvm::tryPromoteCall(), llvm::SCCPSolver::tryToReplaceWithConstant(), llvm::UpgradeARCRuntime(), llvm::UpgradeIntrinsicCall(), llvm::AMDGPULibCalls::useNative(), and llvm::IRSimilarity::IRInstructionMapper::InstructionClassification::visitCallInst().
getCalledOperand()
Value * llvm::CallBase::getCalledOperand () const inline
Definition at line 1338 of file InstrTypes.h.
Referenced by canParameterizeCallOperand(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::Attributor::checkForAllCallees(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::diagnoseDontCall(), getCalledFunction(), getCaptureInfo(), getIntrinsicID(), llvm::IntrinsicInst::getIntrinsicID(), llvm::getMaybeBitcastedCallee(), getMemoryEffects(), handleGuaranteedWellDefinedOps(), hasArgumentWithAdditionalReturnCaptureComponents(), llvm::InlineFunctionImpl(), isIndirectCall(), isInlineAsm(), isValidCandidateForColdCC(), llvm::CallLowering::lowerCall(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallSiteWithPtrAuthBundle(), OptimizeAwayTrappingUsesOfValue(), prepareDescriptorIndirectCall(), simplifySuspendPoint(), llvm::Attributor::translateArgumentToCallSiteContent(), llvm::PGOIndirectCallVisitor::tryGetVTableInstruction(), llvm::tryPromoteCall(), llvm::UpgradeIntrinsicCall(), llvm::X86TTIImpl::useFastCCForInternalCall(), llvm::versionCallSite(), llvm::Interpreter::visitCallBase(), and llvm::InstCombinerImpl::visitCallInst().
getCalledOperandUse() [1/2]
Use & llvm::CallBase::getCalledOperandUse () inline
Definition at line 1341 of file InstrTypes.h.
getCalledOperandUse() [2/2]
const Use & llvm::CallBase::getCalledOperandUse () const inline
Definition at line 1340 of file InstrTypes.h.
Referenced by isCallee(), and isCalleeOperand().
getCaller() [1/2]
Function * CallBase::getCaller ()
Helper to get the caller (the parent function).
Definition at line 320 of file Instructions.cpp.
References llvm::GlobalValue::getParent(), and llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >, ilist_detail::compute_node_options< Instruction, Options... >::type::parent_ty >::getParent().
Referenced by AddAlignmentAssumptions(), annotateDereferenceableBytes(), annotateNonNullNoUndefBasedOnAccess(), llvm::CtxProfAnalysis::collectIndirectCallPromotionList(), doPromotion(), llvm::InlineAdvisor::getAdvice(), llvm::MLInlineAdvisor::getAdviceImpl(), llvm::ReplayInlineAdvisor::getAdviceImpl(), getCaller(), llvm::InlineAdvisor::getCallerORE(), getDefaultInlineAdvice(), llvm::InlineFunction(), isColdCallSite(), llvm::ProfileSummaryInfo::isColdCallSite(), isReturnNonNull(), paramHasNonNullAttr(), llvm::InlineCostAnnotationPrinterPass::run(), llvm::InlinerPass::run(), llvm::ModuleInlinerPass::run(), llvm::shouldInline(), llvm::PPCTargetLowering::supportsTailCallFor(), and llvm::tryPromoteCall().
getCaller() [2/2]
const Function * llvm::CallBase::getCaller () const inline
Definition at line 1366 of file InstrTypes.h.
References CallBase(), and getCaller().
getCallingConv()
CallingConv::ID llvm::CallBase::getCallingConv () const inline
Definition at line 1404 of file InstrTypes.h.
References llvm::Instruction::getSubclassData().
Referenced by adjustInliningThresholdUsingCallee(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), doPromotion(), llvm::InlineFunctionImpl(), llvm::AMDGPU::isArgPassedInSGPR(), llvm::TargetLibraryInfoImpl::isCallingConvCCompatible(), llvm::CallLowering::lowerCall(), llvm::FastISel::lowerCallTo(), llvm::makeGuardControlFlowExplicit(), processCall(), llvm::PPCTargetLowering::supportsTailCallFor(), upgradeAMDGCNIntrinsicCall(), and llvm::IRSimilarity::IRInstructionMapper::InstructionClassification::visitCallInst().
getCaptureInfo()
CaptureInfo CallBase::getCaptureInfo (unsigned OpNo) const
Return which pointer components this operand may capture.
Definition at line 704 of file Instructions.cpp.
References llvm::CaptureInfo::all(), arg_size(), llvm::dyn_cast(), getBundleOpInfoForOperand(), getCalledOperand(), llvm::AttributeSet::getCaptureInfo(), getIntrinsicID(), getParamAttributes(), isByValArgument(), llvm::CaptureInfo::none(), and operandBundleFromBundleOpInfo().
Referenced by determinePointerAccessAttrs(), and doesNotCapture().
getConvergenceControlToken()
Value * llvm::CallBase::getConvergenceControlToken () const inline
Return the convergence control token for this call, if it exists.
Definition at line 1187 of file InstrTypes.h.
References getOperandBundle(), and llvm::LLVMContext::OB_convergencectrl.
getDataOperandNo() [1/2]
unsigned llvm::CallBase::getDataOperandNo (const Use * U) const inline
Given a use for a data operand, get the data operand number that corresponds to it.
Definition at line 1259 of file InstrTypes.h.
References assert(), data_operands_begin(), and isDataOperand().
getDataOperandNo() [2/2]
unsigned llvm::CallBase::getDataOperandNo (Value::const_user_iterator UI) const inline
Given a value use iterator, return the data operand corresponding to it.
Iterator must actually correspond to a data operand.
Definition at line 1253 of file InstrTypes.h.
References getDataOperandNo().
Referenced by determinePointerAccessAttrs(), and getDataOperandNo().
getFnAttr() [1/2]
Attribute llvm::CallBase::getFnAttr (Attribute::AttrKind Kind) const inline
Get the attribute of a given kind for the function.
Definition at line 1638 of file InstrTypes.h.
References A(), and getAttributes().
getFnAttr() [2/2]
Attribute llvm::CallBase::getFnAttr (StringRef Kind) const inline
Get the attribute of a given kind for the function.
Definition at line 1630 of file InstrTypes.h.
References getAttributes(), and llvm::Attribute::isValid().
Referenced by llvm::memprof::addAmbiguousAttribute(), getAllocationSize(), llvm::getAssumptions(), llvm::getStringFnAttrAsInt(), llvm::VFABI::getVectorVariantNames(), llvm::hasAssumption(), optimizeModularFormat(), and llvm::memprof::removeAnyExistingAmbiguousAttribute().
getFunctionType()
FunctionType * llvm::CallBase::getFunctionType () const inline
Definition at line 1203 of file InstrTypes.h.
References FTy.
Referenced by addVariantDeclaration(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), expandBufferStoreIntrinsic(), llvm::AMDGPULibCalls::fold(), getCalledFunction(), llvm::SPIRV::getOriginalFunctionType(), getVectorCallCosts(), llvm::VFABI::getVectorVariantNames(), llvm::objcarc::hasAttachedCallOpBundle(), llvm::InlineFunctionImpl(), llvm::TargetLibraryInfoImpl::isCallingConvCCompatible(), llvm::CallLowering::lowerCall(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::FastISel::lowerCallTo(), lowerFunnelShifts(), promoteArguments(), llvm::promoteCall(), llvm::VFABI::setVectorVariantNames(), shouldConvertToIndirectCall(), and llvm::UpgradeIntrinsicCall().
getIntrinsicID()
Intrinsic::ID CallBase::getIntrinsicID () const
Returns the intrinsic ID of the intrinsic called or Intrinsic::not_intrinsic if the called function is not an intrinsic, or if this is an indirect call.
Definition at line 349 of file Instructions.cpp.
References llvm::dyn_cast_or_null(), F, getCalledOperand(), and llvm::Intrinsic::not_intrinsic.
Referenced by llvm::InstrProfCallsite::canInstrumentCallsite(), llvm::objcarc::BundledRetainClaimRVs::eraseInst(), getCaptureInfo(), hasClobberingOperandBundles(), hasReadingOperandBundles(), llvm::AANoSync::isAlignedBarrier(), isKnownIntegral(), llvm::CallInst::isNonContinuableTrap(), llvm::lowerUnaryVectorIntrinsicAsLoop(), processCallSite(), reportInvalidDirection(), scalarizeMaskedVectorHistogram(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), upgradeARMIntrinsicCall(), and llvm::InstCombinerImpl::visitCallInst().
getMemoryEffects()
MemoryEffects CallBase::getMemoryEffects () const
Definition at line 629 of file Instructions.cpp.
References llvm::dyn_cast(), getAttributes(), getCalledOperand(), hasClobberingOperandBundles(), hasOperandBundles(), hasReadingOperandBundles(), llvm::MemoryEffectsBase< IRMemLocation >::inaccessibleMemOnly(), llvm::Instruction::isVolatile(), llvm::MemoryEffectsBase< IRMemLocation >::readOnly(), and llvm::MemoryEffectsBase< IRMemLocation >::writeOnly().
Referenced by determinePointerAccessAttrs(), doesNotAccessMemory(), llvm::MemoryLocation::getForDest(), onlyAccessesArgMemory(), onlyAccessesInaccessibleMemOrArgMem(), onlyAccessesInaccessibleMemory(), onlyReadsMemory(), onlyWritesMemory(), setOnlyAccessesArgMemory(), setOnlyAccessesInaccessibleMemOrArgMem(), setOnlyAccessesInaccessibleMemory(), setOnlyReadsMemory(), and setOnlyWritesMemory().
getNumOperandBundles()
unsigned llvm::CallBase::getNumOperandBundles () const inline
Return the number of operand bundles associated with this User.
Definition at line 1994 of file InstrTypes.h.
References bundle_op_info_begin(), and bundle_op_info_end().
Referenced by llvm::CanInlineCallSite(), llvm::CallBrInst::cloneImpl(), llvm::CallInst::cloneImpl(), llvm::InvokeInst::cloneImpl(), countOperandBundlesOfType(), countOperandBundlesOfType(), Create(), findAffectedValues(), getOperandBundle(), getOperandBundle(), getOperandBundleAt(), getOperandBundlesAsDefs(), hasIdenticalOperandBundleSchema(), hasOperandBundles(), hasOperandBundlesOtherThan(), llvm::InlineFunctionImpl(), and removeOperandBundle().
getNumSubclassExtraOperands()
unsigned llvm::CallBase::getNumSubclassExtraOperands () const inline protected
Definition at line 1139 of file InstrTypes.h.
References getNumSubclassExtraOperandsDynamic(), llvm::Instruction::getOpcode(), and llvm_unreachable.
Referenced by data_operands_end().
getNumSubclassExtraOperandsDynamic()
unsigned CallBase::getNumSubclassExtraOperandsDynamic () const protected
Get the number of extra operands for instructions that don't have a fixed number of extra operands.
Definition at line 322 of file Instructions.cpp.
References assert(), llvm::cast(), and llvm::Instruction::getOpcode().
Referenced by getNumSubclassExtraOperands().
getNumTotalBundleOperands()
unsigned llvm::CallBase::getNumTotalBundleOperands () const inline
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
Definition at line 2038 of file InstrTypes.h.
References assert(), getBundleOperandsEndIndex(), getBundleOperandsStartIndex(), and hasOperandBundles().
Referenced by arg_end(), dataOperandHasImpliedAttr(), llvm::CallBrInst::getIndirectDestLabel(), and llvm::CallBrInst::getIndirectDestLabelUse().
getOperandBundle() [1/2]
std::optional< OperandBundleUse > llvm::CallBase::getOperandBundle (StringRef Name) const inline
Return an operand bundle by name, if present.
It is an error to call this for operand bundle types that may have multiple instances of them on the same instruction.
Definition at line 2081 of file InstrTypes.h.
References assert(), countOperandBundlesOfType(), getNumOperandBundles(), and getOperandBundleAt().
Referenced by addOperandBundle(), llvm::CanInlineCallSite(), canParameterizeCallOperand(), llvm::GCStatepointInst::deopt_begin(), llvm::GCStatepointInst::deopt_end(), llvm::GCStatepointInst::gc_live_begin(), llvm::GCStatepointInst::gc_live_end(), llvm::GCStatepointInst::gc_transition_args_begin(), llvm::GCStatepointInst::gc_transition_args_end(), llvm::objcarc::getAttachedARCFunction(), getConvergenceControlToken(), HandleCallsInBlockInlinedThroughInvoke(), llvm::objcarc::hasAttachedCallOpBundle(), hasDeoptState(), llvm::InlineFunctionImpl(), llvm::CallLowering::lowerCall(), llvm::SelectionDAGBuilder::LowerCallSiteWithPtrAuthBundle(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::makeGuardControlFlowExplicit(), processCallSite(), replaceUnwindCoroEnd(), and llvm::SCCPSolver::tryToReplaceWithConstant().
getOperandBundle() [2/2]
std::optional< OperandBundleUse > llvm::CallBase::getOperandBundle (uint32_t ID) const inline
Return an operand bundle by tag ID, if present.
It is an error to call this for operand bundle types that may have multiple instances of them on the same instruction.
Definition at line 2097 of file InstrTypes.h.
References assert(), countOperandBundlesOfType(), getNumOperandBundles(), and getOperandBundleAt().
getOperandBundleAt()
OperandBundleUse llvm::CallBase::getOperandBundleAt (unsigned Index) const inline
Return the operand bundle at a specific index.
Definition at line 2050 of file InstrTypes.h.
References assert(), bundle_op_info_begin(), getNumOperandBundles(), and operandBundleFromBundleOpInfo().
Referenced by llvm::CanInlineCallSite(), countOperandBundlesOfType(), countOperandBundlesOfType(), Create(), findAffectedValues(), getOperandBundle(), getOperandBundle(), getOperandBundlesAsDefs(), hasOperandBundlesOtherThan(), llvm::InlineFunctionImpl(), and removeOperandBundle().
getOperandBundleForOperand()
OperandBundleUse llvm::CallBase::getOperandBundleForOperand (unsigned OpIdx) const inline
Return the operand bundle for the operand at index OpIdx.
It is an error to call this with an OpIdx that does not correspond to an bundle operand.
Definition at line 2123 of file InstrTypes.h.
References getBundleOpInfoForOperand(), operandBundleFromBundleOpInfo(), and OpIdx.
Referenced by isOperandBundleOfType().
getOperandBundlesAsDefs()
void CallBase::getOperandBundlesAsDefs (SmallVectorImpl< OperandBundleDef > & Defs) const
Return the list of operand bundles attached to this instruction as a vector of OperandBundleDefs.
This function copies the OperandBundeUse instances associated with this OperandBundleUser to a vector of OperandBundleDefs. Note: OperandBundeUses and OperandBundleDefs are non-trivially different representations of operand bundles (see documentation above).
Definition at line 501 of file Instructions.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), getNumOperandBundles(), and getOperandBundleAt().
Referenced by addOperandBundle(), llvm::changeToInvokeAndSplitBasicBlock(), doPromotion(), llvm::InlineFunctionImpl(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), RemovePreallocated(), rewriteCall(), and upgradeAMDGCNIntrinsicCall().
getParamAlign()
MaybeAlign llvm::CallBase::getParamAlign (unsigned ArgNo) const inline
Extract the alignment for a call or parameter (0=unknown).
Definition at line 1776 of file InstrTypes.h.
References Attrs.
Referenced by llvm::InlineFunctionImpl(), optimizeCallInst(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), and scalarizeMaskedStore().
getParamAttr() [1/2]
Attribute llvm::CallBase::getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const inline
Get the attribute of a given kind from a given arg.
Definition at line 1646 of file InstrTypes.h.
References A(), arg_size(), assert(), and getAttributes().
Referenced by AddParamAndFnBasicAttributes().
getParamAttr() [2/2]
Attribute llvm::CallBase::getParamAttr (unsigned ArgNo, StringRef Kind) const inline
Get the attribute of a given kind from a given arg.
Definition at line 1655 of file InstrTypes.h.
References A(), arg_size(), assert(), and getAttributes().
getParamAttributes()
AttributeSet llvm::CallBase::getParamAttributes (unsigned ArgNo) const inline
Return the param attributes for this call.
Definition at line 1433 of file InstrTypes.h.
References getAttributes().
Referenced by getCaptureInfo(), hasArgumentWithAdditionalReturnCaptureComponents(), and mergeAttributesAndFlags().
getParamByRefType()
Type * llvm::CallBase::getParamByRefType (unsigned ArgNo) const inline
Extract the byref type for a call or parameter.
Definition at line 1785 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
getParamByValType()
Type * llvm::CallBase::getParamByValType (unsigned ArgNo) const inline
Extract the byval type for a call or parameter.
Definition at line 1794 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
Referenced by llvm::InlineFunctionImpl().
getParamDereferenceableBytes()
uint64_t llvm::CallBase::getParamDereferenceableBytes (unsigned i) const inline
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
Definition at line 1847 of file InstrTypes.h.
References Attrs.
Referenced by annotateDereferenceableBytes().
getParamDereferenceableOrNullBytes()
uint64_t llvm::CallBase::getParamDereferenceableOrNullBytes (unsigned i) const inline
Extract the number of dereferenceable_or_null bytes for a parameter (0=unknown).
Definition at line 1865 of file InstrTypes.h.
References Attrs.
Referenced by annotateDereferenceableBytes().
getParamElementType()
Type * llvm::CallBase::getParamElementType (unsigned ArgNo) const inline
Extract the elementtype type for a parameter.
Note that elementtype() can only be applied to call arguments, not function declaration parameters.
Definition at line 1832 of file InstrTypes.h.
References Attrs.
Referenced by llvm::GCStatepointInst::getActualReturnType().
getParamInAllocaType()
Type * llvm::CallBase::getParamInAllocaType (unsigned ArgNo) const inline
Extract the inalloca type for a call or parameter.
Definition at line 1812 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
getParamNoFPClass()
FPClassTest CallBase::getParamNoFPClass (unsigned i) const
Extract a test mask for disallowed floating-point value classes for the parameter.
Definition at line 363 of file Instructions.cpp.
References Attrs, F, and getCalledFunction().
getParamPreallocatedType()
Type * llvm::CallBase::getParamPreallocatedType (unsigned ArgNo) const inline
Extract the preallocated type for a call or parameter.
Definition at line 1803 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
getParamStackAlign()
MaybeAlign llvm::CallBase::getParamStackAlign (unsigned ArgNo) const inline
Definition at line 1780 of file InstrTypes.h.
References Attrs.
getParamStructRetType()
Type * llvm::CallBase::getParamStructRetType (unsigned ArgNo) const inline
Extract the sret type for a call or parameter.
Definition at line 1821 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
getRange()
std::optional< ConstantRange > CallBase::getRange () const
If this return value has a range attribute, return the value range of the argument.
Otherwise, std::nullopt is returned.
Definition at line 371 of file Instructions.cpp.
References Attrs, F, FnAttr, getCalledFunction(), llvm::Attribute::getRange(), llvm::ConstantRange::intersectWith(), and llvm::Attribute::isValid().
Referenced by IdentifyValidPoisonGeneratingAttributes().
getRetAlign()
MaybeAlign llvm::CallBase::getRetAlign () const inline
Extract the alignment of the return value.
Definition at line 1767 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
Referenced by IdentifyValidPoisonGeneratingAttributes(), llvm::CallLowering::lowerCall(), and llvm::InstCombinerImpl::visitCallInst().
getRetAttr()
Attribute llvm::CallBase::getRetAttr (Attribute::AttrKind Kind) const inline
Return the attribute for the given attribute kind for the return value.
Definition at line 1596 of file InstrTypes.h.
References llvm::Attribute, Attrs, F, getCalledFunction(), and RetAttr.
getRetAttributes()
AttributeSet llvm::CallBase::getRetAttributes () const inline
Return the return attributes for this call.
Definition at line 1428 of file InstrTypes.h.
References getAttributes().
Referenced by llvm::InlineFunctionImpl(), and mergeAttributesAndFlags().
getRetDereferenceableBytes()
uint64_t llvm::CallBase::getRetDereferenceableBytes () const inline
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
Definition at line 1838 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
Referenced by IdentifyValidUBGeneratingAttributes(), and isReturnNonNull().
getRetDereferenceableOrNullBytes()
uint64_t llvm::CallBase::getRetDereferenceableOrNullBytes () const inline
Extract the number of dereferenceable_or_null bytes for a call (0=unknown).
Definition at line 1853 of file InstrTypes.h.
References Attrs, F, and getCalledFunction().
Referenced by IdentifyValidUBGeneratingAttributes().
getRetNoFPClass()
FPClassTest CallBase::getRetNoFPClass () const
Extract a test mask for disallowed floating-point value classes for the return value.
Definition at line 355 of file Instructions.cpp.
References Attrs, F, and getCalledFunction().
getReturnedArgOperand()
Value * llvm::CallBase::getReturnedArgOperand () const inline
If one of the arguments has the 'returned' attribute, returns its operand value.
Otherwise, return nullptr.
Definition at line 1893 of file InstrTypes.h.
References getArgOperandWithAttribute().
hasArgument()
bool llvm::CallBase::hasArgument (const Value * V) const inline
Returns true if this CallSite passes the given Value* as an argument to the called function.
Definition at line 1334 of file InstrTypes.h.
References args(), and llvm::is_contained().
hasArgumentWithAdditionalReturnCaptureComponents()
bool CallBase::hasArgumentWithAdditionalReturnCaptureComponents () const
Returns whether the call has an argument that has an attribute like captures(ret: address, provenance), where the return capture components are not a subset of the other capture components.
Definition at line 727 of file Instructions.cpp.
References arg_size(), llvm::capturesAnything(), llvm::dyn_cast(), getArgOperand(), getCalledOperand(), llvm::AttributeSet::getCaptureInfo(), llvm::CaptureInfo::getOtherComponents(), getParamAttributes(), llvm::CaptureInfo::getRetComponents(), llvm::Value::getType(), I, and llvm::isPointerTy().
hasByValArgument()
bool llvm::CallBase::hasByValArgument () const inline
Determine if any call argument is an aggregate passed by value.
Definition at line 1980 of file InstrTypes.h.
References Attrs.
hasClobberingOperandBundles()
bool CallBase::hasClobberingOperandBundles () const
Return true if this operand bundle user has operand bundles that may write to the heap.
Definition at line 620 of file Instructions.cpp.
References getIntrinsicID(), hasOperandBundlesOtherThan(), llvm::LLVMContext::OB_convergencectrl, llvm::LLVMContext::OB_deactivation_symbol, llvm::LLVMContext::OB_deopt, llvm::LLVMContext::OB_funclet, llvm::LLVMContext::OB_kcfi, and llvm::LLVMContext::OB_ptrauth.
Referenced by getMemoryEffects(), and paramHasAttr().
hasDeoptState()
bool llvm::CallBase::hasDeoptState () const inline
Return true if the call has deopt state bundle.
Definition at line 2295 of file InstrTypes.h.
References getOperandBundle(), and llvm::LLVMContext::OB_deopt.
hasDescriptor()
bool llvm::CallBase::hasDescriptor () const inline protected
Definition at line 1137 of file InstrTypes.h.
References llvm::Value::HasDescriptor.
Referenced by bundle_op_info_begin(), and bundle_op_info_end().
hasFnAttr() [1/2]
bool llvm::CallBase::hasFnAttr (Attribute::AttrKind Kind) const inline
Determine whether this call has the given attribute.
If it does not then determine if the called function has the attribute, but only if the attribute is allowed for the call.
Definition at line 1456 of file InstrTypes.h.
References assert().
Referenced by llvm::memprof::addAmbiguousAttribute(), allPathsGoThroughCold(), cannotDuplicate(), cannotMerge(), llvm::CallInst::canReturnTwice(), doesNoCfCheck(), doesNotReturn(), doesNotThrow(), InstrBreaksNoFree(), InstrBreaksNoSync(), isConvergent(), isNoInline(), llvm::CallInst::isNonContinuableTrap(), llvm::isSafeToMoveBefore(), isStrictFP(), optimizeModularFormat(), llvm::SITargetLowering::passSpecialInputs(), and llvm::memprof::removeAnyExistingAmbiguousAttribute().
hasFnAttr() [2/2]
bool llvm::CallBase::hasFnAttr (StringRef Kind) const inline
Determine whether this call has the given attribute.
If it does not then determine if the called function has the attribute, but only if the attribute is allowed for the call.
Definition at line 1465 of file InstrTypes.h.
hasIdenticalOperandBundleSchema()
bool llvm::CallBase::hasIdenticalOperandBundleSchema (const CallBase & Other) const inline
Return true if Other has the same sequence of operand bundle tags with the same number of operands on each one of them as this OperandBundleUser.
Definition at line 2146 of file InstrTypes.h.
References bundle_op_info_begin(), bundle_op_info_end(), CallBase(), getNumOperandBundles(), and llvm::Other.
hasInAllocaArgument()
bool llvm::CallBase::hasInAllocaArgument () const inline
Determine if there are is an inalloca argument.
Only the last argument can have the inalloca attribute.
Definition at line 1737 of file InstrTypes.h.
References arg_empty(), arg_size(), and paramHasAttr().
hasOperandBundles()
bool llvm::CallBase::hasOperandBundles () const inline
Return true if this User has any operand bundles.
Definition at line 1999 of file InstrTypes.h.
References getNumOperandBundles().
Referenced by llvm::CanInlineCallSite(), llvm::CallBrInst::cloneImpl(), llvm::CallInst::cloneImpl(), llvm::InvokeInst::cloneImpl(), dataOperandHasImpliedAttr(), getBundleOperandsEndIndex(), getBundleOperandsStartIndex(), llvm::MemoryLocation::getForDest(), getMemoryEffects(), getNumTotalBundleOperands(), getSameOpcode(), isBundleOperand(), isBundleOperand(), and llvm::InstCombinerImpl::visitCallInst().
hasOperandBundlesOtherThan()
bool llvm::CallBase::hasOperandBundlesOtherThan (ArrayRef< uint32_t > IDs) const inline
Return true if this operand bundle user contains operand bundles with tags other than those specified in IDs.
Definition at line 2156 of file InstrTypes.h.
References getNumOperandBundles(), getOperandBundleAt(), llvm::OperandBundleUse::getTagID(), and llvm::is_contained().
Referenced by hasClobberingOperandBundles(), hasReadingOperandBundles(), and markTails().
hasReadingOperandBundles()
bool CallBase::hasReadingOperandBundles () const
Return true if this operand bundle user has operand bundles that may read from the heap.
Definition at line 609 of file Instructions.cpp.
References getIntrinsicID(), hasOperandBundlesOtherThan(), llvm::LLVMContext::OB_convergencectrl, llvm::LLVMContext::OB_deactivation_symbol, llvm::LLVMContext::OB_kcfi, and llvm::LLVMContext::OB_ptrauth.
Referenced by getMemoryEffects(), and paramHasAttr().
hasRetAttr() [1/2]
bool llvm::CallBase::hasRetAttr (Attribute::AttrKind Kind) const inline
Determine whether the return value has the given attribute.
Definition at line 1589 of file InstrTypes.h.
Referenced by AddReturnAttributes(), IdentifyValidPoisonGeneratingAttributes(), IdentifyValidUBGeneratingAttributes(), isFunctionMallocLike(), isReturnNonNull(), and llvm::InstCombinerImpl::visitCallInst().
hasRetAttr() [2/2]
bool llvm::CallBase::hasRetAttr (StringRef Kind) const inline
Determine whether the return value has the given attribute.
Definition at line 1593 of file InstrTypes.h.
hasStructRetAttr()
bool llvm::CallBase::hasStructRetAttr () const inline
Determine if the call returns a structure through first pointer argument.
Definition at line 1971 of file InstrTypes.h.
References arg_empty(), and paramHasAttr().
Instruction() [1/2]
llvm::Instruction::Instruction (const Instruction &) protected delete
Referenced by CallBase(), and classof().
Instruction() [2/2]
Instruction::Instruction (Type * Ty, unsigned iType, AllocInfo AllocInfo, InsertPosition InsertBefore = nullptr) protected
Definition at line 1078 of file Instruction.cpp.
isArgOperand() [1/2]
bool llvm::CallBase::isArgOperand (const Use * U) const inline
Definition at line 1310 of file InstrTypes.h.
References arg_begin(), arg_end(), and assert().
Referenced by determinePointerAccessAttrs(), getArgOperandNo(), and isArgOperand().
isArgOperand() [2/2]
bool llvm::CallBase::isArgOperand (Value::const_user_iterator UI) const inline
Definition at line 1315 of file InstrTypes.h.
References isArgOperand().
isBundleOperand() [1/3]
bool llvm::CallBase::isBundleOperand (const Use * U) const inline
Returns true if the use is a bundle operand.
Definition at line 2027 of file InstrTypes.h.
References assert(), hasOperandBundles(), isBundleOperand(), and llvm::User::op_begin().
isBundleOperand() [2/3]
bool llvm::CallBase::isBundleOperand (unsigned Idx) const inline
Return true if the operand at index Idx is a bundle operand.
Definition at line 2014 of file InstrTypes.h.
References getBundleOperandsEndIndex(), getBundleOperandsStartIndex(), and hasOperandBundles().
Referenced by isBundleOperand(), isBundleOperand(), and isOperandBundleOfType().
isBundleOperand() [3/3]
bool llvm::CallBase::isBundleOperand (Value::const_user_iterator UI) const inline
Definition at line 2032 of file InstrTypes.h.
References isBundleOperand().
isByValArgument()
bool llvm::CallBase::isByValArgument (unsigned ArgNo) const inline
Determine whether this argument is passed by value.
Definition at line 1707 of file InstrTypes.h.
References paramHasAttr().
Referenced by getCaptureInfo(), llvm::InlineFunctionImpl(), and onlyReadsMemory().
isCallee() [1/2]
bool llvm::CallBase::isCallee (const Use * U) const inline
Determine whether this Use is the callee operand's Use.
Definition at line 1362 of file InstrTypes.h.
References getCalledOperandUse().
isCallee() [2/2]
bool llvm::CallBase::isCallee (Value::const_user_iterator UI) const inline
Determine whether the passed iterator points to the callee operand's Use.
Definition at line 1357 of file InstrTypes.h.
References isCallee().
Referenced by addNoRecurseAttrsTopDown(), determinePointerAccessAttrs(), isCallee(), mergeCompatibleInvokesImpl(), and promoteArguments().
isConvergent()
bool llvm::CallBase::isConvergent () const inline
Determine if the invoke is convergent.
Definition at line 1965 of file InstrTypes.h.
References hasFnAttr().
Referenced by llvm::CanInlineCallSite(), canSplitCallSite(), hashCallInst(), InstrBreaksNonConvergent(), llvm::CallLowering::lowerCall(), and llvm::SelectionDAGBuilder::LowerCallTo().
isDataOperand() [1/2]
bool llvm::CallBase::isDataOperand (const Use * U) const inline
Definition at line 1242 of file InstrTypes.h.
References assert(), data_operands_begin(), and data_operands_end().
Referenced by getDataOperandNo(), isDataOperand(), and mergeCompatibleInvokesImpl().
isDataOperand() [2/2]
bool llvm::CallBase::isDataOperand (Value::const_user_iterator UI) const inline
Definition at line 1247 of file InstrTypes.h.
References isDataOperand().
isInAllocaArgument()
bool llvm::CallBase::isInAllocaArgument (unsigned ArgNo) const inline
Determine whether this argument is passed in an alloca.
Definition at line 1712 of file InstrTypes.h.
References paramHasAttr().
isIndirectCall()
bool CallBase::isIndirectCall () const
Return true if the callsite is an indirect call.
Definition at line 327 of file Instructions.cpp.
References getCalledOperand(), llvm::isa(), and isInlineAsm().
Referenced by llvm::MachineFunction::CallSiteInfo::CallSiteInfo(), llvm::InstrProfCallsite::canInstrumentCallsite(), handleGuaranteedWellDefinedOps(), llvm::RISCVTargetLowering::LowerCall(), llvm::CallLowering::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::promoteCallWithIfThenElse(), restoreMutatedType(), runCGProfilePass(), llvm::IRSimilarity::IRInstructionData::setCalleeName(), llvm::PGOIndirectCallVisitor::tryGetVTableInstruction(), and llvm::IRSimilarity::IRInstructionMapper::InstructionClassification::visitCallInst().
isInlineAsm()
bool llvm::CallBase::isInlineAsm () const inline
Check if this call is an inline asm statement.
Definition at line 1413 of file InstrTypes.h.
References getCalledOperand(), and llvm::isa().
Referenced by llvm::InstrProfCallsite::canInstrumentCallsite(), canParameterizeCallOperand(), isIndirectCall(), restoreMutatedType(), and shouldConvertUse().
isMustTailCall()
bool CallBase::isMustTailCall () const
Tests if this call site must be tail call optimized.
Only a CallInst can be tail call optimized.
Definition at line 336 of file Instructions.cpp.
References llvm::dyn_cast().
Referenced by llvm::SelectionDAGBuilder::canTailCall(), doCallSiteSplitting(), hasMustTailCallers(), llvm::isLegalToPromote(), llvm::Attributor::isValidFunctionSignatureRewrite(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::CallLowering::lowerCall(), llvm::SelectionDAGBuilder::LowerCallSiteWithPtrAuthBundle(), promoteArguments(), RemovePreallocated(), splitCallSite(), llvm::SCCPSolver::tryToReplaceWithConstant(), and versionCallSiteWithCond().
isNoBuiltin()
bool llvm::CallBase::isNoBuiltin () const inline
Return true if the call should not be treated as a call to a builtin.
Definition at line 1903 of file InstrTypes.h.
Referenced by addMappingsFromTLI(), llvm::AMDGPULibCalls::fold(), llvm::TargetLibraryInfo::getLibFunc(), getVectorCallCosts(), llvm::LibCallSimplifier::optimizeCall(), llvm::LoopVectorizationCostModel::setVectorizedCallDecision(), and llvm::AMDGPULibCalls::useNative().
isNoInline()
bool llvm::CallBase::isNoInline () const inline
Return true if the call should not be inlined.
Definition at line 1912 of file InstrTypes.h.
References hasFnAttr().
isOperandBundleOfType()
bool llvm::CallBase::isOperandBundleOfType (uint32_t ID, unsigned Idx) const inline
Return true if the operand at index Idx is a bundle operand that has tag ID ID.
Definition at line 2021 of file InstrTypes.h.
References getOperandBundleForOperand(), llvm::OperandBundleUse::getTagID(), and isBundleOperand().
Referenced by canParameterizeCallOperand().
isPassingUndefUB()
bool llvm::CallBase::isPassingUndefUB (unsigned ArgNo) const inline
Determine whether passing undef to this argument is undefined behavior.
If passing undef to this argument is UB, passing poison is UB as well because poison is more undefined than undef.
Definition at line 1727 of file InstrTypes.h.
References paramHasAttr().
isPassPointeeByValueArgument()
bool llvm::CallBase::isPassPointeeByValueArgument (unsigned ArgNo) const inline
Determine whether this argument is passed by value, in an alloca, or is preallocated.
Definition at line 1718 of file InstrTypes.h.
References paramHasAttr().
isReturnNonNull()
bool CallBase::isReturnNonNull () const
Return true if the return value is known to be not null.
This may be because it has the nonnull attribute, or because at least one byte is dereferenceable and the pointer is in addrspace(0).
Definition at line 386 of file Instructions.cpp.
References getCaller(), llvm::getPointerAddressSpace(), getRetDereferenceableBytes(), llvm::Value::getType(), hasRetAttr(), and llvm::NullPointerIsDefined().
isStrictFP()
bool llvm::CallBase::isStrictFP () const inline
Determine if the call requires strict floating point semantics.
Definition at line 1909 of file InstrTypes.h.
References hasFnAttr().
Referenced by llvm::AMDGPULibCalls::fold().
isTailCall()
bool CallBase::isTailCall () const
Tests if this call site is marked as a tail call.
Definition at line 343 of file Instructions.cpp.
References llvm::dyn_cast().
Referenced by llvm::CallLowering::lowerCall(), and llvm::SelectionDAGBuilder::LowerCallSiteWithPtrAuthBundle().
mutateFunctionType()
void llvm::CallBase::mutateFunctionType (FunctionType * FTy) inline
Definition at line 1205 of file InstrTypes.h.
References FTy, and llvm::Value::mutateType().
Referenced by llvm::promoteCall().
onlyAccessesArgMemory()
bool CallBase::onlyAccessesArgMemory () const
Determine if the call can access memmory only using pointers based on its arguments.
Definition at line 678 of file Instructions.cpp.
References getMemoryEffects(), and llvm::MemoryEffectsBase< LocationEnum >::onlyAccessesArgPointees().
onlyAccessesInaccessibleMemOrArgMem()
bool CallBase::onlyAccessesInaccessibleMemOrArgMem () const
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
Definition at line 696 of file Instructions.cpp.
References getMemoryEffects(), and llvm::MemoryEffectsBase< LocationEnum >::onlyAccessesInaccessibleOrArgMem().
onlyAccessesInaccessibleMemory()
bool CallBase::onlyAccessesInaccessibleMemory () const
Determine if the function may only access memory that is inaccessible from the IR.
Definition at line 687 of file Instructions.cpp.
References getMemoryEffects(), and llvm::MemoryEffectsBase< LocationEnum >::onlyAccessesInaccessibleMem().
onlyReadsMemory() [1/2]
bool CallBase::onlyReadsMemory () const
Determine if the call does not access or only reads memory.
Determine if the function does not access or only reads memory.
Definition at line 661 of file Instructions.cpp.
References getMemoryEffects(), and llvm::MemoryEffectsBase< LocationEnum >::onlyReadsMemory().
onlyReadsMemory() [2/2]
bool llvm::CallBase::onlyReadsMemory (unsigned OpNo) const inline
Definition at line 1749 of file InstrTypes.h.
References arg_size(), dataOperandHasImpliedAttr(), and isByValArgument().
Referenced by determinePointerAccessAttrs(), llvm::objcarc::GetCallSiteClass(), llvm::MemoryLocation::getForDest(), llvm::getIntrinsicForCallSite(), and MayAutorelease().
onlyWritesMemory() [1/2]
bool CallBase::onlyWritesMemory () const
Determine if the call does not access or only writes memory.
Determine if the function does not access or only writes memory.
Definition at line 669 of file Instructions.cpp.
References getMemoryEffects(), and llvm::MemoryEffectsBase< LocationEnum >::onlyWritesMemory().
onlyWritesMemory() [2/2]
bool llvm::CallBase::onlyWritesMemory (unsigned OpNo) const inline
Definition at line 1761 of file InstrTypes.h.
References dataOperandHasImpliedAttr().
operandBundleFromBundleOpInfo()
OperandBundleUse llvm::CallBase::operandBundleFromBundleOpInfo (const BundleOpInfo & BOI) const inline
Simple helper function to map a BundleOpInfo to an OperandBundleUse.
Definition at line 2188 of file InstrTypes.h.
References llvm::CallBase::BundleOpInfo::Begin, llvm::begin(), llvm::CallBase::BundleOpInfo::End, llvm::User::op_begin(), and llvm::CallBase::BundleOpInfo::Tag.
Referenced by bundleOperandHasAttr(), getCaptureInfo(), getOperandBundleAt(), getOperandBundleForOperand(), and llvm::objcarc::BundledRetainClaimRVs::~BundledRetainClaimRVs().
paramHasAttr()
bool CallBase::paramHasAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Determine whether the argument or parameter has the given attribute.
Definition at line 410 of file Instructions.cpp.
References arg_size(), assert(), Attrs, F, getCalledFunction(), hasClobberingOperandBundles(), and hasReadingOperandBundles().
Referenced by AddAliasScopeMetadata(), AddParamAndFnBasicAttributes(), annotateDereferenceableBytes(), annotateNonNullNoUndefBasedOnAccess(), computeBytesPoppedByCalleeForSRet(), dataOperandHasImpliedAttr(), handleGuaranteedWellDefinedOps(), hasInAllocaArgument(), hasStructRetAttr(), llvm::AMDGPU::isArgPassedInSGPR(), isByValArgument(), isCondRelevantToAnyCallArgument(), isInAllocaArgument(), llvm::isLegalToPromote(), isPassingUndefUB(), isPassPointeeByValueArgument(), paramHasNonNullAttr(), and processCallSite().
paramHasNonNullAttr()
bool CallBase::paramHasNonNullAttr (unsigned ArgNo, bool AllowUndefOrPoison) const
Return true if this argument has the nonnull attribute on either the CallBase instruction or the called function.
Also returns true if at least one byte is known to be dereferenceable and the pointer is in addrspace(0). If AllowUndefOrPoison is true, respect the semantics of nonnull attribute and return true even if the argument can be undef or poison.
Definition at line 436 of file Instructions.cpp.
References assert(), getArgOperand(), getCaller(), llvm::getPointerAddressSpace(), llvm::Value::getType(), llvm::isPointerTy(), llvm::NullPointerIsDefined(), and paramHasAttr().
populateBundleOperandInfos()
CallBase::op_iterator CallBase::populateBundleOperandInfos (ArrayRef< OperandBundleDef > Bundles, const unsigned BeginIndex)
Populate the BundleOpInfo instances and the Use& vector from Bundles.
Return the op_iterator pointing to the Use& one past the last last bundle operand use.
Each OperandBundleDef instance is tracked by a OperandBundleInfo instance allocated in this User's descriptor.
Definition at line 508 of file Instructions.cpp.
References assert(), B(), llvm::ArrayRef< T >::begin(), bundle_op_infos(), llvm::ArrayRef< T >::end(), llvm::Value::getContext(), llvm::User::op_begin(), and llvm::LLVMContext::pImpl.
removeAttributeAtIndex() [1/2]
void llvm::CallBase::removeAttributeAtIndex (unsigned i, Attribute::AttrKind Kind) inline
removes the attribute from the list of attributes.
Definition at line 1522 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
removeAttributeAtIndex() [2/2]
void llvm::CallBase::removeAttributeAtIndex (unsigned i, StringRef Kind) inline
removes the attribute from the list of attributes.
Definition at line 1527 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
removeFnAttr() [1/2]
void llvm::CallBase::removeFnAttr (Attribute::AttrKind Kind) inline
Removes the attribute from the function.
Definition at line 1537 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
Referenced by processCall(), llvm::memprof::removeAnyExistingAmbiguousAttribute(), and setNotConvergent().
removeFnAttr() [2/2]
void llvm::CallBase::removeFnAttr (StringRef Kind) inline
Removes the attribute from the function.
Definition at line 1542 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
removeFnAttrs()
void llvm::CallBase::removeFnAttrs (const AttributeMask & AttrsToRemove) inline
Removes the attributes from the function.
Definition at line 1532 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
removeOperandBundle()
CallBase * CallBase::removeOperandBundle (CallBase * CB, uint32_t ID, InsertPosition InsertPt = nullptr) static
Create a clone of CB with operand bundle ID removed.
Definition at line 592 of file Instructions.cpp.
References CallBase(), Create(), llvm::SmallVectorImpl< T >::emplace_back(), getNumOperandBundles(), getOperandBundleAt(), and I.
Referenced by llvm::objcarc::BundledRetainClaimRVs::eraseInst(), llvm::KCFIPass::run(), and llvm::InstCombinerImpl::visitCallInst().
removeParamAttr() [1/2]
void llvm::CallBase::removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) inline
Removes the attribute from the given argument.
Definition at line 1557 of file InstrTypes.h.
References arg_size(), assert(), Attrs, and llvm::Value::getContext().
Referenced by annotateDereferenceableBytes(), promoteArguments(), runIPSCCP(), setConstantInArgument(), llvm::MemIntrinsicBase< Derived >::setDestAlignment(), and llvm::MemIntrinsicBase< Derived >::setDestAlignment().
removeParamAttr() [2/2]
void llvm::CallBase::removeParamAttr (unsigned ArgNo, StringRef Kind) inline
Removes the attribute from the given argument.
Definition at line 1563 of file InstrTypes.h.
References arg_size(), assert(), Attrs, and llvm::Value::getContext().
removeParamAttrs()
void llvm::CallBase::removeParamAttrs (unsigned ArgNo, const AttributeMask & AttrsToRemove) inline
Removes the attributes from the given argument.
Definition at line 1569 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
Referenced by mergeAttributesAndFlags().
removeRetAttr()
void llvm::CallBase::removeRetAttr (Attribute::AttrKind Kind) inline
Removes the attribute from the return value.
Definition at line 1547 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
removeRetAttrs()
void llvm::CallBase::removeRetAttrs (const AttributeMask & AttrsToRemove) inline
Removes the attributes from the return value.
Definition at line 1552 of file InstrTypes.h.
References Attrs, and llvm::Value::getContext().
Referenced by llvm::InlineFunctionImpl(), mergeAttributesAndFlags(), and runIPSCCP().
returnDoesNotAlias()
bool llvm::CallBase::returnDoesNotAlias () const inline
Determine if the return value is marked with NoAlias attribute.
Definition at line 1887 of file InstrTypes.h.
References Attrs.
setArgOperand()
void llvm::CallBase::setArgOperand (unsigned i, Value * v) inline
Definition at line 1295 of file InstrTypes.h.
References arg_size(), assert(), and llvm::User::setOperand().
Referenced by llvm::CoroIdInst::clearPromise(), createCoroSave(), despeculateCountZeros(), llvm::AMDGPULibCalls::fold(), OptimizeAwayTrappingUsesOfValue(), llvm::promoteCall(), llvm::DbgVariableIntrinsic::setArgOperand(), llvm::InstrProfCallsite::setCallee(), setConstantInArgument(), llvm::CoroIdInst::setCoroutineSelf(), llvm::MemIntrinsicBase< Derived >::setDest(), llvm::InstrProfCntrInstBase::setIndex(), llvm::CoroIdInst::setInfo(), llvm::DbgLabelInst::setLabel(), llvm::MemIntrinsicBase< Derived >::setLength(), llvm::VPIntrinsic::setMaskParam(), llvm::InstrProfInstBase::setNameValue(), llvm::VPIntrinsic::setVectorLengthParam(), llvm::MemIntrinsic::setVolatile(), llvm::MemSetPatternInst::setVolatile(), turnGuardIntoBranch(), and llvm::SPIRVGlobalRegistry::updateAssignType().
setAttributes()
void llvm::CallBase::setAttributes (AttributeList A) inline
Set the attributes for this call.
Definition at line 1425 of file InstrTypes.h.
References A(), and Attrs.
Referenced by llvm::createCallMatchingInvoke(), createThunk(), doPromotion(), emitBinaryFloatFnCallHelper(), emitUnaryFloatFnCallHelper(), expandAtan2Intrinsic(), llvm::InlineFunctionImpl(), makeStatepointExplicitImpl(), mergeAttributesAndFlags(), processCall(), processCallSite(), llvm::promoteCall(), RemoveAttribute(), tryIntersectAttributes(), tryToMoveFreeBeforeNullTest(), and llvm::UpgradeIntrinsicCall().
setCalledFunction() [1/3]
void llvm::CallBase::setCalledFunction (Function * Fn) inline
Sets the function called, including updating the function type.
Definition at line 1385 of file InstrTypes.h.
References llvm::Function::getFunctionType(), and setCalledFunction().
Referenced by llvm::AMDGPULibCalls::fold(), lowerFunnelShifts(), processCall(), setCalledFunction(), setCalledFunction(), llvm::UpgradeIntrinsicCall(), llvm::AMDGPULibCalls::useNative(), and llvm::InstCombinerImpl::visitCallInst().
setCalledFunction() [2/3]
void llvm::CallBase::setCalledFunction (FunctionCallee Fn) inline
Sets the function called, including updating the function type.
Definition at line 1390 of file InstrTypes.h.
References llvm::FunctionCallee::getCallee(), llvm::FunctionCallee::getFunctionType(), and setCalledFunction().
setCalledFunction() [3/3]
void llvm::CallBase::setCalledFunction (FunctionType * FTy, Value * Fn) inline
Sets the function called, including updating to the specified function type.
Definition at line 1396 of file InstrTypes.h.
References assert(), FTy, llvm::Value::getType(), and setCalledOperand().
setCalledOperand()
void llvm::CallBase::setCalledOperand (Value * V) inline
Definition at line 1382 of file InstrTypes.h.
Referenced by OptimizeAwayTrappingUsesOfValue(), OptimizeNonTrivialIFuncs(), llvm::promoteCall(), setCalledFunction(), and llvm::UpgradeIntrinsicCall().
setCallingConv()
void llvm::CallBase::setCallingConv (CallingConv::ID CC) inline
Definition at line 1408 of file InstrTypes.h.
References llvm::Instruction::setSubclassData().
Referenced by addBoundsChecking(), llvm::createCallMatchingInvoke(), llvm::IRBuilderBase::CreateMalloc(), createThunk(), doPromotion(), emitBinaryFloatFnCallHelper(), llvm::emitCalloc(), llvm::emitFPutC(), llvm::emitFPutS(), llvm::emitFWrite(), llvm::emitHotColdNew(), llvm::emitHotColdNewAligned(), llvm::emitHotColdNewAlignedNoThrow(), llvm::emitHotColdNewNoThrow(), llvm::emitHotColdSizeReturningNew(), llvm::emitHotColdSizeReturningNewAligned(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCpyChk(), llvm::emitPutChar(), llvm::emitPutS(), emitUnaryFloatFnCallHelper(), llvm::InlineFunctionImpl(), makeStatepointExplicitImpl(), and processCall().
setCannotDuplicate()
void llvm::CallBase::setCannotDuplicate () inline
Definition at line 1958 of file InstrTypes.h.
References addFnAttr().
Referenced by setCannotDuplicate(), and setDXILAttributes().
setCannotMerge()
void llvm::CallBase::setCannotMerge () inline
Definition at line 1962 of file InstrTypes.h.
References addFnAttr().
setConvergent()
void llvm::CallBase::setConvergent () inline
Definition at line 1966 of file InstrTypes.h.
References addFnAttr().
setDoesNotAccessMemory()
void CallBase::setDoesNotAccessMemory ()
Definition at line 656 of file Instructions.cpp.
References llvm::MemoryEffectsBase< IRMemLocation >::none(), and setMemoryEffects().
Referenced by setDXILAttributes().
setDoesNotReturn()
void llvm::CallBase::setDoesNotReturn () inline
Definition at line 1947 of file InstrTypes.h.
References addFnAttr().
Referenced by addBoundsChecking(), and setDXILAttributes().
setDoesNotThrow()
void llvm::CallBase::setDoesNotThrow () inline
Definition at line 1954 of file InstrTypes.h.
References addFnAttr().
Referenced by addBoundsChecking(), llvm::OpenMPIRBuilder::emitUserDefinedMapper(), llvm::InlineFunctionImpl(), and llvm::InstCombinerImpl::visitCallInst().
setIsNoInline()
void llvm::CallBase::setIsNoInline () inline
Definition at line 1913 of file InstrTypes.h.
References addFnAttr().
Referenced by llvm::InlinerPass::run().
setMemoryEffects()
void CallBase::setMemoryEffects (MemoryEffects ME)
Definition at line 648 of file Instructions.cpp.
References addFnAttr(), llvm::Value::getContext(), and llvm::Attribute::getWithMemoryEffects().
Referenced by setDoesNotAccessMemory(), setOnlyAccessesArgMemory(), setOnlyAccessesInaccessibleMemOrArgMem(), setOnlyAccessesInaccessibleMemory(), setOnlyReadsMemory(), and setOnlyWritesMemory().
setNotConvergent()
void llvm::CallBase::setNotConvergent () inline
Definition at line 1967 of file InstrTypes.h.
References removeFnAttr().
setOnlyAccessesArgMemory()
void CallBase::setOnlyAccessesArgMemory ()
Definition at line 681 of file Instructions.cpp.
References llvm::MemoryEffectsBase< IRMemLocation >::argMemOnly(), getMemoryEffects(), and setMemoryEffects().
setOnlyAccessesInaccessibleMemOrArgMem()
void CallBase::setOnlyAccessesInaccessibleMemOrArgMem ()
Definition at line 699 of file Instructions.cpp.
References getMemoryEffects(), llvm::MemoryEffectsBase< IRMemLocation >::inaccessibleOrArgMemOnly(), and setMemoryEffects().
setOnlyAccessesInaccessibleMemory()
void CallBase::setOnlyAccessesInaccessibleMemory ()
Definition at line 690 of file Instructions.cpp.
References getMemoryEffects(), llvm::MemoryEffectsBase< IRMemLocation >::inaccessibleMemOnly(), and setMemoryEffects().
setOnlyReadsMemory()
void CallBase::setOnlyReadsMemory ()
Definition at line 664 of file Instructions.cpp.
References getMemoryEffects(), llvm::MemoryEffectsBase< IRMemLocation >::readOnly(), and setMemoryEffects().
Referenced by setDXILAttributes().
setOnlyWritesMemory()
void CallBase::setOnlyWritesMemory ()
Definition at line 672 of file Instructions.cpp.
References getMemoryEffects(), setMemoryEffects(), and llvm::MemoryEffectsBase< IRMemLocation >::writeOnly().
tryIntersectAttributes()
bool llvm::CallBase::tryIntersectAttributes (const CallBase * Other) inline
Try to intersect the attributes from 'this' CallBase and the 'Other' CallBase.
Sets the intersected attributes to 'this' and return true if successful. Doesn't modify 'this' and returns false if unsuccessful.
Definition at line 1441 of file InstrTypes.h.
References CallBase(), getAttributes(), llvm::Value::getContext(), llvm::Other, and setAttributes().
Referenced by mergeCompatibleInvokesImpl().
Member Data Documentation
Attrs
AttributeList llvm::CallBase::Attrs protected
parameter attributes for callable
Definition at line 1128 of file InstrTypes.h.
Referenced by addAttributeAtIndex(), addAttributeAtIndex(), addDereferenceableParamAttr(), addDereferenceableRetAttr(), addFnAttr(), addFnAttr(), addParamAttr(), addParamAttr(), addParamAttrs(), addRangeRetAttr(), addRetAttr(), addRetAttr(), addRetAttrs(), CallBase(), getArgOperandWithAttribute(), getAttributes(), getParamAlign(), getParamByRefType(), getParamByValType(), getParamDereferenceableBytes(), getParamDereferenceableOrNullBytes(), getParamElementType(), getParamInAllocaType(), getParamNoFPClass(), getParamPreallocatedType(), getParamStackAlign(), getParamStructRetType(), getRange(), getRetAlign(), getRetAttr(), getRetDereferenceableBytes(), getRetDereferenceableOrNullBytes(), getRetNoFPClass(), hasByValArgument(), paramHasAttr(), removeAttributeAtIndex(), removeAttributeAtIndex(), removeFnAttr(), removeFnAttr(), removeFnAttrs(), removeParamAttr(), removeParamAttr(), removeParamAttrs(), removeRetAttr(), removeRetAttrs(), returnDoesNotAlias(), and setAttributes().
CalledOperandOpEndIdx
int llvm::CallBase::CalledOperandOpEndIdx = -1 static constexpr protected
The last operand is the called operand.
Definition at line 1126 of file InstrTypes.h.
FTy
FunctionType* llvm::CallBase::FTy protected
Definition at line 1129 of file InstrTypes.h.
Referenced by CallBase(), getFunctionType(), mutateFunctionType(), and setCalledFunction().
The documentation for this class was generated from the following files:
include/llvm/IR/InstrTypes.h
lib/IR/Instructions.cpp