LLVM: llvm::AMDGPU::VOPD::InstInfo Class Reference
llvm::AMDGPU::VOPD::InstInfo Class Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Types
using RegIndices = std::array<MCRegister, Component::MAX_OPR_NUM>
Public Member Functions
InstInfo (const MCInstrDesc &OpX, const MCInstrDesc &OpY)
InstInfo (const ComponentInfo &OprInfoX, const ComponentInfo &OprInfoY)
const ComponentInfo & operator[] (size_t ComponentIdx) const
bool hasInvalidOperand (std::function< MCRegister(unsigned, unsigned)> GetRegIdx, const MCRegisterInfo &MRI, bool SkipSrc=false, bool AllowSameVGPR=false, bool VOPD3=false) const
std::optional< unsigned > getInvalidCompOperandIndex (std::function< MCRegister(unsigned, unsigned)> GetRegIdx, const MCRegisterInfo &MRI, bool SkipSrc=false, bool AllowSameVGPR=false, bool VOPD3=false) const
Detailed Description
Definition at line 907 of file AMDGPUBaseInfo.h.
Member Typedef Documentation
RegIndices
using llvm::AMDGPU::VOPD::InstInfo::RegIndices = std::array<MCRegister, Component::MAX_OPR_NUM>
Definition at line 912 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
InstInfo() [1/2]
llvm::AMDGPU::VOPD::InstInfo::InstInfo (const MCInstrDesc & OpX, const MCInstrDesc & OpY) inline
Definition at line 914 of file AMDGPUBaseInfo.h.
InstInfo() [2/2]
llvm::AMDGPU::VOPD::InstInfo::InstInfo (const ComponentInfo & OprInfoX, const ComponentInfo & OprInfoY) inline
Definition at line 917 of file AMDGPUBaseInfo.h.
Member Function Documentation
getInvalidCompOperandIndex()
std::optional< unsigned > llvm::AMDGPU::VOPD::InstInfo::getInvalidCompOperandIndex (std::function< MCRegister(unsigned, unsigned)> GetRegIdx, const MCRegisterInfo & MRI, bool SkipSrc = false, bool AllowSameVGPR = false, bool VOPD3 = false) const
Definition at line 908 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::VOPD::DST_NUM, llvm::AMDGPU::getVGPREncodingMSBs(), llvm::MCRegister::id(), llvm::AMDGPU::VOPD::MAX_OPR_NUM, MRI, llvm::AMDGPU::VOPD::VOPD3_VGPR_BANK_MASKS, llvm::AMDGPU::VOPD::VOPD_VGPR_BANK_MASKS, llvm::AMDGPU::VOPD::X, and llvm::AMDGPU::VOPD::Y.
Referenced by hasInvalidOperand().
hasInvalidOperand()
bool llvm::AMDGPU::VOPD::InstInfo::hasInvalidOperand (std::function< MCRegister(unsigned, unsigned)> GetRegIdx, const MCRegisterInfo & MRI, bool SkipSrc = false, bool AllowSameVGPR = false, bool VOPD3 = false) const inline
Definition at line 936 of file AMDGPUBaseInfo.h.
References getInvalidCompOperandIndex(), and MRI.
operator[]()
const ComponentInfo & llvm::AMDGPU::VOPD::InstInfo::operator[] (size_t ComponentIdx) const inline
Definition at line 920 of file AMDGPUBaseInfo.h.
References assert(), and llvm::AMDGPU::VOPD::COMPONENTS_NUM.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp