LLVM: llvm::ListRecTy Class Reference
llvm::ListRecTy Class Reference
'list<Ty>' - Represent a list of element values, all of which must be of the specified type.
#include "llvm/TableGen/Record.h"
Public Member Functions
const RecTy * getElementType () const
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
Return true if all values of 'this' type can be converted to the specified type.
bool typeIsA (const RecTy *RHS) const override
Return true if 'this' type is equal to or a subtype of RHS.
Public Member Functions inherited from llvm::RecTy
RecTy (RecTyKind K, RecordKeeper &RK)
virtual ~RecTy ()=default
RecTyKind getRecTyKind () const
RecordKeeper & getRecordKeeper () const
Return the RecordKeeper that uniqued this Type.
void print (raw_ostream &OS) const
void dump () const
const ListRecTy * getListTy () const
Returns the type representing list<thistype>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static const ListRecTy * get (const RecTy *T)
Friends
const ListRecTy * RecTy::getListTy () const
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.).
Detailed Description
'list<Ty>' - Represent a list of element values, all of which must be of the specified type.
The type is stored in ElementTy.
Definition at line 189 of file Record.h.
Member Function Documentation
classof()
bool llvm::ListRecTy::classof (const RecTy * RT) inline static
Definition at line 198 of file Record.h.
References llvm::RecTy::getRecTyKind(), llvm::RecTy::ListRecTyKind, and llvm::RecTy::RecTy().
get()
const ListRecTy * llvm::ListRecTy::get (const RecTy * T) inline static
Definition at line 202 of file Record.h.
References llvm::RecTy::RecTy(), and T.
getAsString()
std::string ListRecTy::getAsString () const override virtual
Implements llvm::RecTy.
Definition at line 206 of file Record.cpp.
getElementType()
const RecTy * llvm::ListRecTy::getElementType () const inline
Definition at line 203 of file Record.h.
References llvm::RecTy::RecTy().
Referenced by typeIsA().
typeIsA()
bool ListRecTy::typeIsA (const RecTy * RHS) const override virtual
Return true if 'this' type is equal to or a subtype of RHS.
For example, a bit set is not an int, but they are convertible.
Reimplemented from llvm::RecTy.
Definition at line 216 of file Record.cpp.
References llvm::dyn_cast(), getElementType(), and llvm::RecTy::RecTy().
typeIsConvertibleTo()
bool ListRecTy::typeIsConvertibleTo (const RecTy * RHS) const override virtual
Return true if all values of 'this' type can be converted to the specified type.
Reimplemented from llvm::RecTy.
Definition at line 210 of file Record.cpp.
References llvm::dyn_cast(), and llvm::RecTy::RecTy().
Friends And Related Symbol Documentation
RecTy::getListTy
const ListRecTy * RecTy::getListTy () const friend
References llvm::RecTy::getRecordKeeper(), llvm::RecTy::ListRecTyKind, llvm::RecTy::RecTy(), and T.
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp