LLVM: llvm::PBQPRAConstraintList Class Reference
llvm::PBQPRAConstraintList Class Reference
PBQP register allocation constraint composer.
#include "llvm/CodeGen/PBQPRAConstraint.h"
Public Member Functions
PBQPRAConstraintList ()=default
PBQPRAConstraintList & operator= (const PBQPRAConstraintList &)=delete
PBQPRAConstraintList (const PBQPRAConstraintList &)=delete
void apply (PBQPRAGraph &G) override
void addConstraint (std::unique_ptr< PBQPRAConstraint > C)
Public Member Functions inherited from llvm::PBQPRAConstraint
virtual ~PBQPRAConstraint ()=0
Detailed Description
PBQP register allocation constraint composer.
Constraints added to this list will be applied, in the order that they are added, to the PBQP graph.
Definition at line 51 of file PBQPRAConstraint.h.
Constructor & Destructor Documentation
PBQPRAConstraintList() [1/2]
llvm::PBQPRAConstraintList::PBQPRAConstraintList () default
Referenced by operator=(), and PBQPRAConstraintList().
PBQPRAConstraintList() [2/2]
llvm::PBQPRAConstraintList::PBQPRAConstraintList (const PBQPRAConstraintList &) delete
References PBQPRAConstraintList().
Member Function Documentation
addConstraint()
void llvm::PBQPRAConstraintList::addConstraint (std::unique_ptr< PBQPRAConstraint > C) inline
Definition at line 63 of file PBQPRAConstraint.h.
References llvm::CallingConv::C.
apply()
void llvm::PBQPRAConstraintList::apply (PBQPRAGraph & G) inline override virtual
Implements llvm::PBQPRAConstraint.
Definition at line 58 of file PBQPRAConstraint.h.
References llvm::CallingConv::C, and G.
operator=()
PBQPRAConstraintList & llvm::PBQPRAConstraintList::operator= (const PBQPRAConstraintList &) delete
References PBQPRAConstraintList().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/PBQPRAConstraint.h
lib/CodeGen/RegAllocPBQP.cpp