LLVM: llvm::RegionInfoPrinterPass Class Reference
llvm::RegionInfoPrinterPass Class Reference
Printer pass for the RegionInfo.
#include "llvm/Analysis/RegionInfo.h"
Public Member Functions
RegionInfoPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< RegionInfoPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< RegionInfoPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the RegionInfo.
Definition at line 977 of file RegionInfo.h.
Constructor & Destructor Documentation
RegionInfoPrinterPass()
RegionInfoPrinterPass::RegionInfoPrinterPass (raw_ostream & OS) explicit
Definition at line 197 of file RegionInfo.cpp.
Member Function Documentation
isRequired()
bool llvm::RegionInfoPrinterPass::isRequired () inline static
Definition at line 985 of file RegionInfo.h.
run()
PreservedAnalyses RegionInfoPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 200 of file RegionInfo.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/RegionInfo.h
lib/Analysis/RegionInfo.cpp