LLVM: llvm::object::symbol_iterator Class Reference
llvm::object::symbol_iterator Class Reference
#include "llvm/Object/ObjectFile.h"
Public Member Functions
symbol_iterator (SymbolRef Sym)
symbol_iterator (const basic_symbol_iterator &B)
const SymbolRef * operator-> () const
const SymbolRef & operator* () const
Public Member Functions inherited from llvm::object::content_iterator< BasicSymbolRef >
content_iterator (BasicSymbolRef symb)
const BasicSymbolRef * operator-> () const
const BasicSymbolRef & operator* () const
bool operator== (const content_iterator &other) const
bool operator!= (const content_iterator &other) const
content_iterator & operator++ ()
Additional Inherited Members
Public Types inherited from llvm::object::content_iterator< BasicSymbolRef >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Definition at line 210 of file ObjectFile.h.
Constructor & Destructor Documentation
symbol_iterator() [1/2]
llvm::object::symbol_iterator::symbol_iterator (SymbolRef Sym) inline
Definition at line 212 of file ObjectFile.h.
Referenced by llvm::object::elf_symbol_iterator::elf_symbol_iterator(), llvm::object::xcoff_symbol_iterator::xcoff_symbol_iterator(), and llvm::object::xcoff_symbol_iterator::xcoff_symbol_iterator().
symbol_iterator() [2/2]
llvm::object::symbol_iterator::symbol_iterator (const basic_symbol_iterator & B) inline
Definition at line 213 of file ObjectFile.h.
References B(), llvm::cast(), and llvm::object::getObject().
Member Function Documentation
operator*()
const SymbolRef & llvm::object::symbol_iterator::operator* () const inline
Definition at line 222 of file ObjectFile.h.
References llvm::object::content_iterator< BasicSymbolRef >::operator*(), and P.
Referenced by llvm::object::elf_symbol_iterator::operator*(), and llvm::object::xcoff_symbol_iterator::operator*().
operator->()
const SymbolRef * llvm::object::symbol_iterator::operator-> () const inline
Definition at line 217 of file ObjectFile.h.
References llvm::object::content_iterator< BasicSymbolRef >::operator*(), and P.
Referenced by llvm::object::elf_symbol_iterator::operator->(), and llvm::object::xcoff_symbol_iterator::operator->().
The documentation for this class was generated from the following file:
include/llvm/Object/ObjectFile.h