LLVM: llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::pointer Class Reference
llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::pointer Class Reference
#include "llvm/ADT/TrieRawHashMap.h"
Public Member Functions
pointer ()=default
Friends
class ThreadSafeTrieRawHashMap
class const_pointer
Detailed Description
template<class T, size_t NumHashBytes>
class llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::pointer
Definition at line 255 of file TrieRawHashMap.h.
Constructor & Destructor Documentation
pointer()
template<class T, size_t NumHashBytes> llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::pointer::pointer () default
References pointer(), and llvm::ThreadSafeTrieRawHashMapBase::PointerBase::PointerBase().
Referenced by pointer().
Friends And Related Symbol Documentation
const_pointer
template<class T, size_t NumHashBytes> friend class const_pointer friend
Definition at line 257 of file TrieRawHashMap.h.
References const_pointer.
Referenced by const_pointer.
ThreadSafeTrieRawHashMap
template<class T, size_t NumHashBytes> friend class ThreadSafeTrieRawHashMap friend
Definition at line 256 of file TrieRawHashMap.h.
References ThreadSafeTrieRawHashMap.
Referenced by ThreadSafeTrieRawHashMap.
The documentation for this class was generated from the following file:
include/llvm/ADT/TrieRawHashMap.h