LLVM: llvm::jitlink::JITLinkDylib Class Reference
llvm::jitlink::JITLinkDylib Class Reference
#include "llvm/ExecutionEngine/JITLink/JITLinkDylib.h"
Public Member Functions
JITLinkDylib (std::string Name)
const std::string & getName () const
Get the name for this JITLinkDylib.
Detailed Description
Definition at line 21 of file JITLinkDylib.h.
Constructor & Destructor Documentation
JITLinkDylib()
llvm::jitlink::JITLinkDylib::JITLinkDylib (std::string Name) inline
Definition at line 23 of file JITLinkDylib.h.
References llvm::move().
Member Function Documentation
getName()
const std::string & llvm::jitlink::JITLinkDylib::getName () const inline
Get the name for this JITLinkDylib.
Definition at line 26 of file JITLinkDylib.h.
Referenced by llvm::orc::createHeaderBlock(), llvm::orc::JITDylib::define(), llvm::orc::JITDylib::define(), llvm::orc::LLJIT::deinitialize(), llvm::orc::LLJIT::initialize(), and llvm::orc::JITDylib::~JITDylib().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLinkDylib.h