LLVM: llvm::DWARFDebugAbbrev Class Reference
llvm::DWARFDebugAbbrev Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
Public Member Functions
LLVM_ABI DWARFDebugAbbrev (DataExtractor Data)
LLVM_ABI Expected< const DWARFAbbreviationDeclarationSet * > getAbbreviationDeclarationSet (uint64_t CUAbbrOffset) const
LLVM_ABI void dump (raw_ostream &OS) const
LLVM_ABI Error parse () const
DWARFAbbreviationDeclarationSetMap::const_iterator begin () const
DWARFAbbreviationDeclarationSetMap::const_iterator end () const
Detailed Description
Definition at line 59 of file DWARFDebugAbbrev.h.
Constructor & Destructor Documentation
DWARFDebugAbbrev()
DWARFDebugAbbrev::DWARFDebugAbbrev (DataExtractor Data)
Definition at line 104 of file DWARFDebugAbbrev.cpp.
References end().
Member Function Documentation
begin()
DWARFAbbreviationDeclarationSetMap::const_iterator llvm::DWARFDebugAbbrev::begin () const inline
Definition at line 76 of file DWARFDebugAbbrev.h.
References assert().
dump()
void DWARFDebugAbbrev::dump (raw_ostream & OS) const
Definition at line 127 of file DWARFDebugAbbrev.cpp.
References llvm::consumeError(), llvm::format(), I, and parse().
Referenced by llvm::DWARFContext::dump().
end()
DWARFAbbreviationDeclarationSetMap::const_iterator llvm::DWARFDebugAbbrev::end () const inline
Definition at line 81 of file DWARFDebugAbbrev.h.
Referenced by DWARFDebugAbbrev().
getAbbreviationDeclarationSet()
Expected< const DWARFAbbreviationDeclarationSet * > DWARFDebugAbbrev::getAbbreviationDeclarationSet (uint64_t CUAbbrOffset) const
Definition at line 144 of file DWARFDebugAbbrev.cpp.
References llvm::DWARFAbbreviationDeclarationSet::extract(), llvm::make_error(), and llvm::Offset.
parse()
Error DWARFDebugAbbrev::parse () const
Definition at line 107 of file DWARFDebugAbbrev.cpp.
References llvm::DWARFAbbreviationDeclarationSet::extract(), I, llvm::Offset, and llvm::Error::success().
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h
lib/DebugInfo/DWARF/DWARFDebugAbbrev.cpp