LLVM: llvm::SourceMgr Class Reference
llvm::SourceMgr Class Reference
This owns the files read by a parser, handles include stacks, and handles diagnostic wrangling.
#include "llvm/Support/SourceMgr.h"
Public Types
enum DiagKind { DK_Error , DK_Warning , DK_Remark , DK_Note }
using DiagHandlerTy = void (*)(const SMDiagnostic &, void *Context)
Clients that want to handle their own diagnostics in a custom way can register a function pointer+context as a diagnostic handler.
Public Member Functions
LLVM_ABI SourceMgr ()
Create new source manager without support for include files.
SourceMgr (IntrusiveRefCntPtr< vfs::FileSystem > FS)
Create new source manager with the capability of finding include files via the provided file system.
SourceMgr (const SourceMgr &)=delete
SourceMgr & operator= (const SourceMgr &)=delete
SourceMgr (SourceMgr &&)
SourceMgr & operator= (SourceMgr &&)
LLVM_ABI ~SourceMgr ()
IntrusiveRefCntPtr< vfs::FileSystem > getVirtualFileSystem () const
LLVM_ABI void setVirtualFileSystem (IntrusiveRefCntPtr< vfs::FileSystem > FS)
ArrayRef< std::string > getIncludeDirs () const
Return the include directories of this source manager.
void setIncludeDirs (const std::vector< std::string > &Dirs)
void setDiagHandler (DiagHandlerTy DH, void *Ctx=nullptr)
Specify a diagnostic handler to be invoked every time PrintMessage is called.
DiagHandlerTy getDiagHandler () const
void * getDiagContext () const
const SrcBuffer & getBufferInfo (unsigned i) const
const MemoryBuffer * getMemoryBuffer (unsigned i) const
unsigned getNumBuffers () const
unsigned getMainFileID () const
SMLoc getParentIncludeLoc (unsigned i) const
unsigned AddNewSourceBuffer (std::unique_ptr< MemoryBuffer > F, SMLoc IncludeLoc)
Add a new source buffer to this source manager.
void takeSourceBuffersFrom (SourceMgr &SrcMgr, SMLoc MainBufferIncludeLoc=SMLoc())
Takes the source buffers from the given source manager and append them to the current manager.
LLVM_ABI unsigned AddIncludeFile (const std::string &Filename, SMLoc IncludeLoc, std::string &IncludedFile)
Search for a file with the specified name in the current directory or in one of the IncludeDirs.
LLVM_ABI ErrorOr< std::unique_ptr< MemoryBuffer > > OpenIncludeFile (const std::string &Filename, std::string &IncludedFile)
Search for a file with the specified name in the current directory or in one of the IncludeDirs, and try to open it without adding to the SourceMgr.
LLVM_ABI unsigned FindBufferContainingLoc (SMLoc Loc) const
Return the ID of the buffer containing the specified location.
unsigned FindLineNumber (SMLoc Loc, unsigned BufferID=0) const
Find the line number for the specified location in the specified file.
LLVM_ABI std::pair< unsigned, unsigned > getLineAndColumn (SMLoc Loc, unsigned BufferID=0) const
Find the line and column number for the specified location in the specified file.
LLVM_ABI std::string getFormattedLocationNoOffset (SMLoc Loc, bool IncludePath=false) const
Get a string with the SMLoc filename and line number formatted in the standard style.
LLVM_ABI SMLoc FindLocForLineAndColumn (unsigned BufferID, unsigned LineNo, unsigned ColNo)
Given a line and column number in a mapped buffer, turn it into an SMLoc.
LLVM_ABI void PrintMessage (raw_ostream &OS, SMLoc Loc, DiagKind Kind, const Twine &Msg, ArrayRef< SMRange > Ranges={}, ArrayRef< SMFixIt > FixIts={}, bool ShowColors=true) const
Emit a message about the specified location with the specified string.
LLVM_ABI void PrintMessage (SMLoc Loc, DiagKind Kind, const Twine &Msg, ArrayRef< SMRange > Ranges={}, ArrayRef< SMFixIt > FixIts={}, bool ShowColors=true) const
Emits a diagnostic to llvm::errs().
LLVM_ABI void PrintMessage (raw_ostream &OS, const SMDiagnostic &Diagnostic, bool ShowColors=true) const
Emits a manually-constructed diagnostic to the given output stream.
LLVM_ABI SMDiagnostic GetMessage (SMLoc Loc, DiagKind Kind, const Twine &Msg, ArrayRef< SMRange > Ranges={}, ArrayRef< SMFixIt > FixIts={}) const
Return an SMDiagnostic at the specified location with the specified string.
LLVM_ABI void PrintIncludeStack (SMLoc IncludeLoc, raw_ostream &OS) const
Prints the names of included files and the line of the file they were included from.
Detailed Description
This owns the files read by a parser, handles include stacks, and handles diagnostic wrangling.
Definition at line 37 of file SourceMgr.h.
Member Typedef Documentation
DiagHandlerTy
using llvm::SourceMgr::DiagHandlerTy = void (*)(const SMDiagnostic &, void *Context)
Clients that want to handle their own diagnostics in a custom way can register a function pointer+context as a diagnostic handler.
It gets called each time PrintMessage is invoked.
Definition at line 49 of file SourceMgr.h.
Member Enumeration Documentation
DiagKind
enum llvm::SourceMgr::DiagKind
Enumerator
DK_Error
DK_Warning
DK_Remark
DK_Note
Definition at line 39 of file SourceMgr.h.
Constructor & Destructor Documentation
SourceMgr() [1/4]
SourceMgr::SourceMgr () default
Create new source manager without support for include files.
References LLVM_ABI.
Referenced by operator=(), operator=(), SourceMgr(), SourceMgr(), and takeSourceBuffersFrom().
SourceMgr() [2/4]
SourceMgr::SourceMgr (IntrusiveRefCntPtr< vfs::FileSystem > FS) explicit
Create new source manager with the capability of finding include files via the provided file system.
Definition at line 44 of file SourceMgr.cpp.
References llvm::move().
SourceMgr() [3/4]
llvm::SourceMgr::SourceMgr (const SourceMgr &) delete
References SourceMgr().
SourceMgr() [4/4]
SourceMgr::SourceMgr (SourceMgr &&) default
References SourceMgr().
~SourceMgr()
SourceMgr::~SourceMgr () default
References LLVM_ABI.
Member Function Documentation
AddIncludeFile()
unsigned SourceMgr::AddIncludeFile (const std::string & Filename, SMLoc IncludeLoc, std::string & IncludedFile)
Search for a file with the specified name in the current directory or in one of the IncludeDirs.
If no file is found, this returns 0, otherwise it returns the buffer ID of the stacked file. The full path to the included file can be found in IncludedFile.
Definition at line 58 of file SourceMgr.cpp.
References AddNewSourceBuffer(), and OpenIncludeFile().
AddNewSourceBuffer()
unsigned llvm::SourceMgr::AddNewSourceBuffer (std::unique_ptr< MemoryBuffer > F, SMLoc IncludeLoc) inline
Add a new source buffer to this source manager.
This takes ownership of the memory buffer.
Definition at line 160 of file SourceMgr.h.
References F.
Referenced by AddIncludeFile(), llvm::lsp::TextDocumentContentChangeEvent::applyTo(), and llvm::MIRParserImpl::initializeMachineFunction().
FindBufferContainingLoc()
unsigned SourceMgr::FindBufferContainingLoc (SMLoc Loc) const
Return the ID of the buffer containing the specified location.
0 is returned if the buffer is not found.
Definition at line 93 of file SourceMgr.cpp.
Referenced by getFormattedLocationNoOffset(), getLineAndColumn(), GetMessage(), PrintIncludeStack(), and PrintMessage().
FindLineNumber()
unsigned llvm::SourceMgr::FindLineNumber (SMLoc Loc, unsigned BufferID = 0) const inline
Find the line number for the specified location in the specified file.
This is not a fast method.
Definition at line 212 of file SourceMgr.h.
References getLineAndColumn().
Referenced by getFormattedLocationNoOffset(), and PrintIncludeStack().
FindLocForLineAndColumn()
SMLoc SourceMgr::FindLocForLineAndColumn (unsigned BufferID, unsigned LineNo, unsigned ColNo)
Given a line and column number in a mapped buffer, turn it into an SMLoc.
This will return a null SMLoc if the line/column location is invalid.
Definition at line 254 of file SourceMgr.cpp.
References getBufferInfo(), llvm::SMLoc::getFromPointer(), and llvm::StringRef::npos.
Referenced by llvm::lsp::Position::getAsSMLoc().
getBufferInfo()
const SrcBuffer & llvm::SourceMgr::getBufferInfo (unsigned i) const inline
Definition at line 136 of file SourceMgr.h.
References assert().
Referenced by FindLocForLineAndColumn(), getFormattedLocationNoOffset(), getLineAndColumn(), PrintIncludeStack(), and PrintMessage().
getDiagContext()
void * llvm::SourceMgr::getDiagContext () const inline
Definition at line 134 of file SourceMgr.h.
Referenced by llvm::TableGenParseFile().
getDiagHandler()
DiagHandlerTy llvm::SourceMgr::getDiagHandler () const inline
Definition at line 133 of file SourceMgr.h.
Referenced by llvm::TableGenParseFile().
getFormattedLocationNoOffset()
std::string SourceMgr::getFormattedLocationNoOffset (SMLoc Loc, bool IncludePath = false) const
Get a string with the SMLoc filename and line number formatted in the standard style.
Get a string with the source location formatted in the standard style, but without the line offset.
If IncludePath is true, the path is included. If false, only the file name and extension are included.
Definition at line 236 of file SourceMgr.cpp.
References assert(), FindBufferContainingLoc(), FindLineNumber(), getBufferInfo(), and I.
getIncludeDirs()
ArrayRef< std::string > llvm::SourceMgr::getIncludeDirs () const inline
Return the include directories of this source manager.
Definition at line 120 of file SourceMgr.h.
Referenced by llvm::TableGenParseFile().
getLineAndColumn()
std::pair< unsigned, unsigned > SourceMgr::getLineAndColumn (SMLoc Loc, unsigned BufferID = 0) const
Find the line and column number for the specified location in the specified file.
This is not a fast method.
Definition at line 212 of file SourceMgr.cpp.
References assert(), llvm::StringRef::find_last_of(), FindBufferContainingLoc(), getBufferInfo(), and llvm::StringRef::npos.
Referenced by FindLineNumber(), GetMessage(), and llvm::lsp::Position::Position().
getMainFileID()
unsigned llvm::SourceMgr::getMainFileID () const inline
Definition at line 148 of file SourceMgr.h.
References assert(), and getNumBuffers().
Referenced by llvm::lsp::Position::getAsSMLoc(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and llvm::GCNTargetMachine::parseMachineFunctionInfo().
getMemoryBuffer()
const MemoryBuffer * llvm::SourceMgr::getMemoryBuffer (unsigned i) const inline
Definition at line 141 of file SourceMgr.h.
References assert().
Referenced by GetMessage(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), and llvm::GCNTargetMachine::parseMachineFunctionInfo().
GetMessage()
SMDiagnostic SourceMgr::GetMessage (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine & Msg, ArrayRef< SMRange > Ranges = {}, ArrayRef< SMFixIt > FixIts = {}) const
Return an SMDiagnostic at the specified location with the specified string.
Parameters
Msg If non-null, the kind of message (e.g., "error") which is prefixed to the message.
Definition at line 294 of file SourceMgr.cpp.
References assert(), FindBufferContainingLoc(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferIdentifier(), llvm::MemoryBuffer::getBufferStart(), llvm::SMLoc::getFromPointer(), getLineAndColumn(), getMemoryBuffer(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Twine::str().
Referenced by PrintMessage(), llvm::MCContext::reportError(), and llvm::MCContext::reportWarning().
getNumBuffers()
unsigned llvm::SourceMgr::getNumBuffers () const inline
Definition at line 146 of file SourceMgr.h.
Referenced by getMainFileID(), and takeSourceBuffersFrom().
getParentIncludeLoc()
SMLoc llvm::SourceMgr::getParentIncludeLoc (unsigned i) const inline
Definition at line 153 of file SourceMgr.h.
References assert().
getVirtualFileSystem()
IntrusiveRefCntPtr< vfs::FileSystem > SourceMgr::getVirtualFileSystem () const
Definition at line 50 of file SourceMgr.cpp.
Referenced by llvm::TableGenParseFile().
OpenIncludeFile()
ErrorOr< std::unique_ptr< MemoryBuffer > > SourceMgr::OpenIncludeFile (const std::string & Filename, std::string & IncludedFile)
Search for a file with the specified name in the current directory or in one of the IncludeDirs, and try to open it without adding to the SourceMgr.
If the opened file is intended to be added to the source manager, prefer AddIncludeFile instead.
If no file is found, this returns an Error, otherwise it returns the buffer of the stacked file. The full path to the included file can be found in IncludedFile.
Definition at line 70 of file SourceMgr.cpp.
References llvm::sys::path::append(), and llvm::MemoryBuffer::getFile().
Referenced by AddIncludeFile().
operator=() [1/2]
SourceMgr & llvm::SourceMgr::operator= (const SourceMgr &) delete
References SourceMgr().
operator=() [2/2]
SourceMgr & SourceMgr::operator= (SourceMgr &&) default
References SourceMgr().
PrintIncludeStack()
void SourceMgr::PrintIncludeStack (SMLoc IncludeLoc, raw_ostream & OS) const
Prints the names of included files and the line of the file they were included from.
A diagnostic handler can use this before printing its custom formatted message.
Parameters
IncludeLoc The location of the include.
OS the raw_ostream to print on.
Definition at line 281 of file SourceMgr.cpp.
References assert(), FindBufferContainingLoc(), FindLineNumber(), getBufferInfo(), and PrintIncludeStack().
Referenced by PrintIncludeStack(), and PrintMessage().
PrintMessage() [1/3]
void SourceMgr::PrintMessage (raw_ostream & OS, const SMDiagnostic & Diagnostic, bool ShowColors = true) const
Emits a manually-constructed diagnostic to the given output stream.
Parameters
ShowColors Display colored messages if output is a terminal and the default error handler is used.
Definition at line 355 of file SourceMgr.cpp.
References assert(), FindBufferContainingLoc(), getBufferInfo(), llvm::SMDiagnostic::getLoc(), llvm::SMLoc::isValid(), llvm::SMDiagnostic::print(), and PrintIncludeStack().
PrintMessage() [2/3]
void SourceMgr::PrintMessage (raw_ostream & OS, SMLoc Loc, SourceMgr::DiagKind Kind, const Twine & Msg, ArrayRef< SMRange > Ranges = {}, ArrayRef< SMFixIt > FixIts = {}, bool ShowColors = true) const
Emit a message about the specified location with the specified string.
Parameters
ShowColors Display colored messages if output is a terminal and the default error handler is used.
Definition at line 372 of file SourceMgr.cpp.
References GetMessage(), and PrintMessage().
Referenced by llvm::MCObjectStreamer::emitFill(), PrintMessage(), and PrintMessage().
PrintMessage() [3/3]
void SourceMgr::PrintMessage (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine & Msg, ArrayRef< SMRange > Ranges = {}, ArrayRef< SMFixIt > FixIts = {}, bool ShowColors = true) const
Emits a diagnostic to llvm::errs().
Definition at line 379 of file SourceMgr.cpp.
References llvm::errs(), and PrintMessage().
setDiagHandler()
void llvm::SourceMgr::setDiagHandler (DiagHandlerTy DH, void * Ctx = nullptr) inline
Specify a diagnostic handler to be invoked every time PrintMessage is called.
Ctx is passed into the handler when it is invoked.
Definition at line 128 of file SourceMgr.h.
setIncludeDirs()
void llvm::SourceMgr::setIncludeDirs (const std::vector< std::string > & Dirs) inline
Definition at line 122 of file SourceMgr.h.
setVirtualFileSystem()
void SourceMgr::setVirtualFileSystem (IntrusiveRefCntPtr< vfs::FileSystem > FS)
Definition at line 54 of file SourceMgr.cpp.
takeSourceBuffersFrom()
void llvm::SourceMgr::takeSourceBuffersFrom (SourceMgr & SrcMgr, SMLoc MainBufferIncludeLoc = SMLoc()) inline
Takes the source buffers from the given source manager and append them to the current manager.
MainBufferIncludeLoc is an optional include location to attach to the main buffer of SrcMgr after it gets moved to the current manager.
Definition at line 173 of file SourceMgr.h.
References getNumBuffers(), SourceMgr(), and llvm::SrcMgr.
Referenced by llvm::TableGenParseFile().
The documentation for this class was generated from the following files:
include/llvm/Support/SourceMgr.h
lib/Support/SourceMgr.cpp