LLVM: llvm::VirtRegOrUnit Class Reference
llvm::VirtRegOrUnit Class Reference
Wrapper class representing a virtual register or register unit.
#include "llvm/CodeGen/Register.h"
Public Member Functions
constexpr VirtRegOrUnit (MCRegUnit Unit)
constexpr VirtRegOrUnit (Register Reg)
template<typename T>
VirtRegOrUnit (T)=delete
constexpr bool isVirtualReg () const
constexpr MCRegUnit asMCRegUnit () const
constexpr Register asVirtualReg () const
constexpr bool operator== (const VirtRegOrUnit &Other) const
constexpr bool operator< (const VirtRegOrUnit &Other) const
Detailed Description
Wrapper class representing a virtual register or register unit.
Definition at line 181 of file Register.h.
Constructor & Destructor Documentation
VirtRegOrUnit() [1/3]
llvm::VirtRegOrUnit::VirtRegOrUnit (MCRegUnit Unit) inline explicit constexpr
Definition at line 185 of file Register.h.
References assert(), and llvm::Register::isVirtualRegister().
Referenced by operator<(), and operator==().
VirtRegOrUnit() [2/3]
llvm::VirtRegOrUnit::VirtRegOrUnit (Register Reg) inline explicit constexpr
Definition at line 190 of file Register.h.
References assert(), and Reg.
VirtRegOrUnit() [3/3]
template<typename T> llvm::VirtRegOrUnit::VirtRegOrUnit (T) explicit delete
References T.
Member Function Documentation
asMCRegUnit()
MCRegUnit llvm::VirtRegOrUnit::asMCRegUnit () const inline constexpr
Definition at line 201 of file Register.h.
References assert(), and isVirtualReg().
Referenced by findUseBetween(), getLanesWithProperty(), getLiveRange(), llvm::printVRegOrUnit(), and llvm::PSetIterator::PSetIterator().
asVirtualReg()
Register llvm::VirtRegOrUnit::asVirtualReg () const inline constexpr
Definition at line 206 of file Register.h.
References assert(), isVirtualReg(), and Register.
Referenced by llvm::RegisterOperands::adjustLaneLiveness(), findUseBetween(), getLanesWithProperty(), getLiveRange(), llvm::RegPressureTracker::initLiveThru(), llvm::printVRegOrUnit(), llvm::PSetIterator::PSetIterator(), and llvm::RegPressureTracker::recede().
isVirtualReg()
bool llvm::VirtRegOrUnit::isVirtualReg () const inline constexpr
Definition at line 197 of file Register.h.
References llvm::Register::isVirtualRegister().
Referenced by llvm::RegisterOperands::adjustLaneLiveness(), asMCRegUnit(), asVirtualReg(), findUseBetween(), getLanesWithProperty(), getLiveRange(), llvm::RegPressureTracker::initLiveThru(), llvm::printVRegOrUnit(), llvm::PSetIterator::PSetIterator(), and llvm::RegPressureTracker::recede().
operator<()
bool llvm::VirtRegOrUnit::operator< (const VirtRegOrUnit & Other) const inline constexpr
Definition at line 215 of file Register.h.
References llvm::Other, and VirtRegOrUnit().
operator==()
bool llvm::VirtRegOrUnit::operator== (const VirtRegOrUnit & Other) const inline constexpr
Definition at line 211 of file Register.h.
References llvm::Other, and VirtRegOrUnit().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/Register.h