LLVM: llvm::Pass Class Reference
llvm::Pass Class Reference abstract
Pass interface - Implemented by all 'passes'.
#include "llvm/Pass.h"
Public Member Functions
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
StringRef getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const =0
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
virtual void assignPassManager (PMStack &, PassManagerType)
Each pass is responsible for assigning a pass manager to itself.
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType>
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Member Functions
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Pass interface - Implemented by all 'passes'.
Subclass this if you are an interprocedural optimization or you do not fit into any of the more constrained passes described below.
Definition at line 99 of file Pass.h.
Constructor & Destructor Documentation
Pass() [1/2]
llvm::Pass::Pass (PassKind K, char & pid) inline explicit
Definition at line 105 of file Pass.h.
Referenced by llvm::legacy::FunctionPassManagerImpl::add(), llvm::legacy::PassManagerImpl::add(), llvm::CallGraphSCCPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::CallGraphSCCPass(), llvm::CallGraphSCCPass::createPrinterPass(), llvm::legacy::FunctionPassManagerImpl::createPrinterPass(), llvm::legacy::PassManagerImpl::createPrinterPass(), llvm::LoopPass::createPrinterPass(), createPrinterPass(), llvm::RegionPass::createPrinterPass(), llvm::FunctionPass::FunctionPass(), llvm::legacy::FunctionPassManagerImpl::FunctionPassManagerImpl(), getAnalysisID(), getAnalysisID(), llvm::legacy::FunctionPassManagerImpl::getAsPass(), llvm::legacy::PassManagerImpl::getAsPass(), llvm::LoopPass::LoopPass(), llvm::ModulePass::ModulePass(), operator=(), Pass(), llvm::legacy::PassManagerImpl::PassManagerImpl(), llvm::RegionPass::RegionPass(), llvm::RegionPass::runOnRegion(), and llvm::ModulePass::~ModulePass().
Pass() [2/2]
llvm::Pass::Pass (const Pass &) delete
References Pass().
~Pass()
Pass::~Pass () virtual
Definition at line 43 of file Pass.cpp.
Member Function Documentation
assignPassManager()
virtual void llvm::Pass::assignPassManager (PMStack & , PassManagerType) inline virtual
Each pass is responsible for assigning a pass manager to itself.
PMS is the stack of available pass manager.
Reimplemented in llvm::CallGraphSCCPass, llvm::FunctionPass, llvm::LoopPass, llvm::ModulePass, and llvm::RegionPass.
Definition at line 151 of file Pass.h.
Referenced by llvm::FunctionPass::assignPassManager(), and llvm::PMTopLevelManager::schedulePass().
createPass()
Pass * Pass::createPass (AnalysisID ID) static
Definition at line 214 of file Pass.cpp.
Referenced by llvm::TargetPassConfig::addPass(), and INITIALIZE_PASS::InsertedPass::getInsertedPass().
createPrinterPass()
virtual Pass * llvm::Pass::createPrinterPass (raw_ostream & OS, const std::string & Banner) const pure virtual
createPrinterPass - Get a Pass appropriate to print the IR this pass operates on (Module, Function or MachineFunction).
Implemented in llvm::CallGraphSCCPass, llvm::FunctionPass, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LoopPass, llvm::ModulePass, and llvm::RegionPass.
References Pass().
doFinalization()
virtual bool llvm::Pass::doFinalization (Module &) inline virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented in llvm::AMDGPUAAWrapperPass, llvm::AMDGPUArgumentUsageInfoWrapperLegacy, llvm::AMDGPUAsmPrinter, llvm::AsmPrinter, llvm::AssumptionCacheTracker, llvm::BPFAsmPrinter, llvm::CallGraphSCCPass, llvm::FPPassManager, llvm::GlobalsAAWrapperPass, llvm::IRSimilarityIdentifierWrapperPass, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LoopPass, llvm::MachineModuleInfoWrapperPass, llvm::MIR2VecVocabPrinterLegacyPass, llvm::ModuleSummaryIndexWrapperPass, llvm::NVPTXAAWrapperPass, llvm::NVPTXAsmPrinter, llvm::PhysicalRegisterUsageInfoWrapperLegacy, llvm::ProfileSummaryInfoWrapperPass, llvm::RegionPass, llvm::ScopedNoAliasAAWrapperPass, llvm::StaticDataProfileInfoWrapperPass, and llvm::TypeBasedAAWrapperPass.
Definition at line 132 of file Pass.h.
Referenced by llvm::FPPassManager::doFinalization(), llvm::LoopPass::runOnLoop(), and llvm::RegionPass::runOnRegion().
doInitialization()
virtual bool llvm::Pass::doInitialization (Module &) inline virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented in AMDGPUAnnotateUniformValuesLegacy, llvm::AMDGPUAAWrapperPass, llvm::AMDGPUArgumentUsageInfoWrapperLegacy, llvm::AMDGPUAsmPrinter, llvm::AsmPrinter, llvm::BasicBlockSectionsProfileReaderWrapperPass, llvm::BPFAsmPrinter, llvm::CallGraphSCCPass, llvm::FPPassManager, llvm::IRSimilarityIdentifierWrapperPass, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LibcallLoweringInfoWrapper, llvm::LoopPass, llvm::MachineFunctionPass, llvm::MachineModuleInfoWrapperPass, llvm::NVPTXAAWrapperPass, llvm::NVPTXAsmPrinter, llvm::PhysicalRegisterUsageInfoWrapperLegacy, llvm::ProfileSummaryInfoWrapperPass, llvm::RegionPass, llvm::ScopedNoAliasAAWrapperPass, llvm::StaticDataProfileInfoWrapperPass, llvm::SystemZAsmPrinter, llvm::ThunkInserterPass< Inserters >, llvm::TypeBasedAAWrapperPass, and llvm::X86AsmPrinter.
Definition at line 128 of file Pass.h.
Referenced by llvm::FPPassManager::doInitialization(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::LoopPass::runOnLoop(), and llvm::RegionPass::runOnRegion().
dump()
void Pass::dump () const
Definition at line 146 of file Pass.cpp.
dumpPassStructure()
void Pass::dumpPassStructure (unsigned Offset = 0) virtual
Reimplemented in llvm::FPPassManager, llvm::legacy::FunctionPassManagerImpl, llvm::LPPassManager, and llvm::RGPassManager.
Definition at line 78 of file Pass.cpp.
Referenced by llvm::PMTopLevelManager::dumpPasses().
getAnalysis() [1/2]
template<typename AnalysisType> AnalysisType & llvm::Pass::getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
Definition at line 224 of file PassAnalysisSupport.h.
References assert(), and getAnalysisID().
Referenced by llvm::MIR2VecVocabPrinterLegacyPass::doFinalization(), llvm::LibcallLoweringInfoWrapper::doInitialization(), llvm::AsmPrinter::emitBBAddrMapSection(), llvm::X86AsmPrinter::emitInstruction(), llvm::MIR2VecVocabLegacyAnalysis::getMIR2VecVocabulary(), llvm::RegBankSelect::init(), llvm::SelectionDAGISel::initializeAnalysisResults(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SITargetLowering::passSpecialInputs(), llvm::DependenceAnalysisWrapperPass::print(), AMDGPUAnnotateUniformValuesLegacy::runOnFunction(), AMDGPULateCodeGenPrepareLegacy::runOnFunction(), llvm::AAResultsWrapperPass::runOnFunction(), llvm::BasicAAWrapperPass::runOnFunction(), llvm::BlockFrequencyInfoWrapperPass::runOnFunction(), llvm::BranchProbabilityInfoWrapperPass::runOnFunction(), llvm::DependenceAnalysisWrapperPass::runOnFunction(), llvm::DominanceFrontierWrapperPass::runOnFunction(), llvm::DOTGraphTraitsPrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::DOTGraphTraitsViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::gvn::GVNLegacyPass::runOnFunction(), llvm::InstructionCombiningPass::runOnFunction(), llvm::LazyBlockFrequencyInfoPass::runOnFunction(), llvm::LazyBranchProbabilityInfoPass::runOnFunction(), llvm::LazyValueInfoWrapperPass::runOnFunction(), llvm::LoopInfoWrapperPass::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::MemoryDependenceWrapperPass::runOnFunction(), llvm::MemorySSAWrapperPass::runOnFunction(), llvm::OptimizationRemarkEmitterWrapperPass::runOnFunction(), llvm::RegionInfoPass::runOnFunction(), llvm::ReplaceWithVeclibLegacy::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::ScalarEvolutionWrapperPass::runOnFunction(), llvm::SCEVAAWrapperPass::runOnFunction(), llvm::SPIRVConvergenceRegionAnalysisWrapperPass::runOnFunction(), llvm::StackProtector::runOnFunction(), llvm::StackSafetyInfoWrapperPass::runOnFunction(), llvm::UniformityInfoWrapperPass::runOnFunction(), SIAnnotateControlFlowLegacy::runOnFunction(), llvm::IVUsersWrapperPass::runOnLoop(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::AMDGPUDAGToDAGISelLegacy::runOnMachineFunction(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::GCNRegPressurePrinter::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::LiveDebugVariablesWrapperLegacy::runOnMachineFunction(), llvm::LiveIntervalsWrapperPass::runOnMachineFunction(), llvm::LiveRegMatrixWrapperLegacy::runOnMachineFunction(), llvm::MachineBlockFrequencyInfoWrapperPass::runOnMachineFunction(), llvm::MachineDominanceFrontier::runOnMachineFunction(), llvm::MachineLoopInfoWrapperPass::runOnMachineFunction(), llvm::MachineOptimizationRemarkEmitterPass::runOnMachineFunction(), llvm::MachinePipeliner::runOnMachineFunction(), llvm::MachineRegionInfoPass::runOnMachineFunction(), llvm::MachineTraceMetricsWrapperPass::runOnMachineFunction(), llvm::MachineUniformityAnalysisPass::runOnMachineFunction(), llvm::MIR2VecPrinterLegacyPass::runOnMachineFunction(), llvm::RABasic::runOnMachineFunction(), llvm::ThunkInserterPass< Inserters >::runOnMachineFunction(), llvm::WebAssemblyExceptionInfo::runOnMachineFunction(), SILowerI1CopiesLegacy::runOnMachineFunction(), StaticDataSplitter::runOnMachineFunction(), llvm::DOTGraphTraitsModulePrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnModule(), llvm::DOTGraphTraitsModuleViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnModule(), llvm::dxil::ShaderFlagsAnalysisWrapper::runOnModule(), llvm::DXILResourceBindingWrapperPass::runOnModule(), llvm::DXILResourceWrapperPass::runOnModule(), llvm::DXILTranslateMetadataLegacy::runOnModule(), llvm::GlobalsAAWrapperPass::runOnModule(), llvm::ModuleSummaryIndexWrapperPass::runOnModule(), llvm::SPIRVModuleAnalysis::runOnModule(), llvm::StackSafetyGlobalInfoWrapperPass::runOnModule(), StaticDataAnnotator::runOnModule(), llvm::AsmPrinter::SetupMachineFunction(), and llvm::LoopInfoWrapperPass::verifyAnalysis().
getAnalysis() [2/2]
template<typename AnalysisType> AnalysisType & llvm::Pass::getAnalysis (Function & F, bool * Changed = nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
If as part of the dependencies, an IR transformation is triggered (e.g. because the analysis requires BreakCriticalEdges), and Changed is non null, *Changed is updated.
Definition at line 249 of file PassAnalysisSupport.h.
References assert(), F, and getAnalysisID().
getAnalysisID() [1/2]
template<typename AnalysisType> AnalysisType & llvm::Pass::getAnalysisID (AnalysisID PI) const
Definition at line 230 of file PassAnalysisSupport.h.
References assert(), and Pass().
Referenced by getAnalysis(), and getAnalysis().
getAnalysisID() [2/2]
template<typename AnalysisType> AnalysisType & llvm::Pass::getAnalysisID (AnalysisID PI, Function & F, bool * Changed = nullptr)
Definition at line 256 of file PassAnalysisSupport.h.
References assert(), F, and Pass().
getAnalysisIfAvailable()
template<typename AnalysisType> AnalysisType * llvm::Pass::getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
This is different than getAnalysis in that it can fail (if the analysis results haven't been computed), so should only be used if you can handle the case when the analysis is not available. This method is often used by transformation APIs to update analysis results for a pass automatically as the transform is performed.
Definition at line 213 of file PassAnalysisSupport.h.
References assert().
Referenced by llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::doInitialization(), llvm::AsmPrinter::emitBBAddrMapSection(), llvm::AsmPrinter::emitFunctionBody(), llvm::AsmPrinter::emitStackMaps(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::SelectionDAGISel::initializeAnalysisResults(), llvm::AAResultsWrapperPass::runOnFunction(), llvm::gvn::GVNLegacyPass::runOnFunction(), llvm::InstructionCombiningPass::runOnFunction(), llvm::StackProtector::runOnFunction(), llvm::AMDGPUResourceUsageAnalysisWrapperPass::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and llvm::StackSafetyGlobalInfoWrapperPass::runOnModule().
getAnalysisUsage()
void Pass::getAnalysisUsage (AnalysisUsage &) const virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented in AMDGPUAnnotateUniformValuesLegacy, AMDGPULateCodeGenPrepareLegacy, llvm::AAResultsWrapperPass, llvm::AMDGPUAAWrapperPass, llvm::AMDGPUArgumentUsageInfoWrapperLegacy, llvm::AMDGPUAsmPrinter, llvm::AMDGPUDAGToDAGISelLegacy, llvm::AMDGPUResourceUsageAnalysisWrapperPass, llvm::ARMBlockPlacement, llvm::AsmPrinter, llvm::AssignmentTrackingAnalysis, llvm::BasicAAWrapperPass, llvm::BasicBlockMatchingAndInference, llvm::BlockFrequencyInfoWrapperPass, llvm::BranchProbabilityInfoWrapperPass, llvm::CallGraphSCCPass, llvm::CallGraphWrapperPass, llvm::CFIFixup, llvm::CycleInfoWrapperPass, llvm::DependenceAnalysisWrapperPass, llvm::DominanceFrontierWrapperPass, llvm::DominatorTreeWrapperPass, llvm::DOTGraphTraitsModulePrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsModuleViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsPrinterWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsViewerWrapperPass< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DummyCGSCCPass, llvm::dxil::RootSignatureAnalysisWrapper, llvm::dxil::ShaderFlagsAnalysisWrapper, llvm::DXILMetadataAnalysisWrapperPass, llvm::DXILResourceBindingWrapperPass, llvm::DXILResourceWrapperPass, llvm::DXILTranslateMetadataLegacy, llvm::ExecutionDomainFix, llvm::ExternalAAWrapperPass, llvm::FPPassManager, llvm::GCNRegPressurePrinter, llvm::GISelCSEAnalysisWrapperPass, llvm::GISelValueTrackingAnalysisLegacy, llvm::GlobalsAAWrapperPass, llvm::gvn::GVNLegacyPass, llvm::ImmutableModuleSummaryIndexWrapperPass, llvm::InstructionCombiningPass, llvm::InstructionSelect, llvm::IRSimilarityIdentifierWrapperPass, llvm::IRTranslator, llvm::IVUsersWrapperPass, llvm::LazyBlockFrequencyInfoPass, llvm::LazyBranchProbabilityInfoPass, llvm::LazyMachineBlockFrequencyInfoPass, llvm::LazyValueInfoWrapperPass, llvm::LCSSAVerificationPass, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::Legalizer, llvm::LibcallLoweringInfoWrapper, llvm::LiveDebugVariablesWrapperLegacy, llvm::LiveIntervalsWrapperPass, llvm::LiveRegMatrixWrapperLegacy, llvm::LiveStacksWrapperLegacy, llvm::LiveVariablesWrapperPass, llvm::LoadStoreOpt, llvm::Localizer, llvm::LoopInfoWrapperPass, llvm::LPPassManager, llvm::MachineBlockFrequencyInfoWrapperPass, llvm::MachineBlockHashInfo, llvm::MachineBranchProbabilityInfoWrapperPass, llvm::MachineCycleInfoWrapperPass, llvm::MachineDominanceFrontier, llvm::MachineDominatorTreeWrapperPass, llvm::MachineFunctionPass, llvm::MachineLoopInfoWrapperPass, llvm::MachineOptimizationRemarkEmitterPass, llvm::MachinePipeliner, llvm::MachinePostDominatorTreeWrapperPass, llvm::MachineRegionInfoPass, llvm::MachineTraceMetricsWrapperPass, llvm::MachineUniformityAnalysisPass, llvm::MemoryDependenceWrapperPass, llvm::MemorySSAWrapperPass, llvm::MipsDAGToDAGISelLegacy, llvm::MipsSEDAGToDAGISelLegacy, llvm::MIR2VecPrinterLegacyPass, llvm::MIR2VecVocabLegacyAnalysis, llvm::MIR2VecVocabPrinterLegacyPass, llvm::ModuleSummaryIndexWrapperPass, llvm::NVPTXAAWrapperPass, llvm::NVPTXAsmPrinter, llvm::OptimizationRemarkEmitterWrapperPass, llvm::PhiValuesWrapperPass, llvm::PostDominatorTreeWrapperPass, llvm::ProfileSummaryInfoWrapperPass, llvm::RABasic, llvm::ReachingDefInfoWrapperPass, llvm::RegAllocEvictionAdvisorAnalysisLegacy, llvm::RegAllocPriorityAdvisorAnalysisLegacy, llvm::RegBankSelect, llvm::RegionInfoPass, llvm::ReplaceWithVeclibLegacy, llvm::RGPassManager, llvm::RuntimeLibraryInfoWrapper, llvm::ScalarEvolutionWrapperPass, llvm::SCEVAAWrapperPass, llvm::ScopedNoAliasAAWrapperPass, llvm::SelectionDAGISelLegacy, llvm::SlotIndexesWrapperPass, llvm::SPIRVConvergenceRegionAnalysisWrapperPass, llvm::SPIRVModuleAnalysis, llvm::StackProtector, llvm::StackSafetyGlobalInfoWrapperPass, llvm::StackSafetyInfoWrapperPass, llvm::StaticDataProfileInfoWrapperPass, llvm::TypeBasedAAWrapperPass, llvm::UniformityInfoWrapperPass, llvm::VirtRegMapWrapperLegacy, llvm::WebAssemblyExceptionInfo, RemoveLoadsIntoFakeUsesLegacy, SIAnnotateControlFlowLegacy, SILowerI1CopiesLegacy, StaticDataAnnotator, and StaticDataSplitter.
Definition at line 112 of file Pass.cpp.
Referenced by llvm::MachineFunctionPass::getAnalysisUsage(), SIAnnotateControlFlowLegacy::getAnalysisUsage(), and StaticDataAnnotator::getAnalysisUsage().
getAsImmutablePass()
ImmutablePass * Pass::getAsImmutablePass () virtual
Reimplemented in llvm::ImmutablePass.
Definition at line 124 of file Pass.cpp.
getAsPMDataManager()
PMDataManager * Pass::getAsPMDataManager () virtual
Reimplemented in llvm::FPPassManager, llvm::legacy::FunctionPassManagerImpl, llvm::legacy::PassManagerImpl, llvm::LPPassManager, and llvm::RGPassManager.
Definition at line 128 of file Pass.cpp.
getPassArgument()
StringRef Pass::getPassArgument () const
Return a nice clean name for a pass corresponding to that used to enable the pass in opt.
getPassArgument - Return a nice clean name for a pass corresponding to that used to enable the pass in opt
Definition at line 95 of file Pass.cpp.
getPassID()
AnalysisID llvm::Pass::getPassID () const inline
getPassID - Return the PassID number that corresponds to this pass.
Definition at line 122 of file Pass.h.
Referenced by llvm::TargetPassConfig::insertPass().
getPassKind()
PassKind llvm::Pass::getPassKind () const inline
Definition at line 110 of file Pass.h.
getPassName()
StringRef Pass::getPassName () const virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented in AMDGPUAnnotateUniformValuesLegacy, AMDGPULateCodeGenPrepareLegacy, GCEmptyBasicBlocksLegacy, llvm::AMDGPUAsmPrinter, llvm::AMDGPUDAGToDAGISelLegacy, llvm::ARMAsmPrinter, llvm::AVRFrameAnalyzer, llvm::BasicBlockMatchingAndInference, llvm::BasicBlockSectionsProfileReaderWrapperPass, llvm::BPFAsmPrinter, llvm::CSKYAsmPrinter, llvm::DetectRoundChange, llvm::DXILTranslateMetadataLegacy, llvm::ErrataWorkaround, llvm::FixAllFDIVSQRT, llvm::FPPassManager, llvm::HexagonAsmPrinter, llvm::InsertNOPLoad, llvm::InstructionSelect, llvm::IRTranslator, llvm::Legalizer, llvm::LoadStoreOpt, llvm::Localizer, llvm::LoongArchAsmPrinter, llvm::LPPassManager, llvm::M68kAsmPrinter, llvm::MachineBlockHashInfo, llvm::MipsAsmPrinter, llvm::MIR2VecPrinterLegacyPass, llvm::MIR2VecVocabPrinterLegacyPass, llvm::MIRAddFSDiscriminators, llvm::MIRProfileLoaderPass, llvm::NVPTXAsmPrinter, llvm::NVPTXExternalAAWrapper, llvm::R600AsmPrinter, llvm::RABasic, llvm::RegBankSelect, llvm::RGPassManager, llvm::SystemZAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::X86AsmPrinter, llvm::XtensaAsmPrinter, RemoveLoadsIntoFakeUsesLegacy, SIAnnotateControlFlowLegacy, SILowerI1CopiesLegacy, StaticDataAnnotator, and StaticDataSplitter.
Definition at line 85 of file Pass.cpp.
Referenced by llvm::PMDataManager::addLowerLevelRequiredPass(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::PMTopLevelManager::schedulePass(), llvm::LoopPass::skipLoop(), and llvm::RegionPass::skipRegion().
getPotentialPassManagerType()
PassManagerType Pass::getPotentialPassManagerType () const virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented in llvm::CallGraphSCCPass, llvm::FunctionPass, llvm::LoopPass, llvm::ModulePass, and llvm::RegionPass.
Definition at line 107 of file Pass.cpp.
Referenced by llvm::PMTopLevelManager::schedulePass().
getResolver()
AnalysisResolver * llvm::Pass::getResolver () const inline
Definition at line 162 of file Pass.h.
Referenced by llvm::PMTopLevelManager::setLastUser().
lookupPassInfo() [1/2]
const PassInfo * Pass::lookupPassInfo (const void * TI) static
Definition at line 206 of file Pass.cpp.
lookupPassInfo() [2/2]
const PassInfo * Pass::lookupPassInfo (StringRef Arg) static
Definition at line 210 of file Pass.cpp.
mustPreserveAnalysisID()
bool Pass::mustPreserveAnalysisID (char & AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
This obviously cannot give you a properly typed instance of the class if you don't have the class name available (use getAnalysisIfAvailable if you do), but it can tell you if you need to preserve the pass at least.
Definition at line 73 of file Pass.cpp.
Referenced by llvm::LPPassManager::runOnFunction().
operator=()
Pass & llvm::Pass::operator= (const Pass &) delete
References Pass().
preparePassManager()
void Pass::preparePassManager (PMStack &) virtual
Check if available pass managers are suitable for this pass or not.
Reimplemented in llvm::LoopPass, and llvm::RegionPass.
Definition at line 103 of file Pass.cpp.
print()
void Pass::print (raw_ostream & OS, const Module * M) const virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented in llvm::AMDGPUArgumentUsageInfoWrapperLegacy, llvm::BlockFrequencyInfoWrapperPass, llvm::BranchProbabilityInfoWrapperPass, llvm::CallGraphWrapperPass, llvm::CycleInfoWrapperPass, llvm::DependenceAnalysisWrapperPass, llvm::DominanceFrontierWrapperPass, llvm::DominatorTreeWrapperPass, llvm::DXILMetadataAnalysisWrapperPass, llvm::DXILResourceWrapperPass, llvm::IVUsersWrapperPass, llvm::LazyBlockFrequencyInfoPass, llvm::LazyBranchProbabilityInfoPass, llvm::LiveIntervalsWrapperPass, llvm::LiveStacksWrapperLegacy, llvm::LoopInfoWrapperPass, llvm::MachineCycleInfoWrapperPass, llvm::MachineDominatorTreeWrapperPass, llvm::MachinePostDominatorTreeWrapperPass, llvm::MachineRegionInfoPass, llvm::MachineUniformityAnalysisPass, llvm::MemorySSAWrapperPass, llvm::PhysicalRegisterUsageInfoWrapperLegacy, llvm::PostDominatorTreeWrapperPass, llvm::RegionInfoPass, llvm::ScalarEvolutionWrapperPass, llvm::StackSafetyGlobalInfoWrapperPass, llvm::StackSafetyInfoWrapperPass, llvm::UniformityInfoWrapperPass, llvm::VirtRegMapWrapperLegacy, and llvm::WebAssemblyExceptionInfo.
Definition at line 140 of file Pass.cpp.
releaseMemory()
void Pass::releaseMemory () virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented in llvm::AssumptionCacheTracker, llvm::BlockFrequencyInfoWrapperPass, llvm::BranchProbabilityInfoWrapperPass, llvm::CallGraphWrapperPass, llvm::CycleInfoWrapperPass, llvm::DependenceAnalysisWrapperPass, llvm::DominanceFrontierWrapperPass, llvm::DominatorTreeWrapperPass, llvm::DXILMetadataAnalysisWrapperPass, llvm::DXILResourceBindingWrapperPass, llvm::DXILResourceWrapperPass, llvm::GISelCSEAnalysisWrapperPass, llvm::GISelValueTrackingAnalysisLegacy, llvm::IVUsersWrapperPass, llvm::LazyBlockFrequencyInfoPass, llvm::LazyBranchProbabilityInfoPass, llvm::LazyMachineBlockFrequencyInfoPass, llvm::LazyValueInfoWrapperPass, llvm::LibcallLoweringInfoWrapper, llvm::LiveDebugVariablesWrapperLegacy, llvm::LiveIntervalsWrapperPass, llvm::LiveRegMatrixWrapperLegacy, llvm::LiveStacksWrapperLegacy, llvm::LiveVariablesWrapperPass, llvm::LoopInfoWrapperPass, llvm::MachineBlockFrequencyInfoWrapperPass, llvm::MachineCycleInfoWrapperPass, llvm::MachineDominanceFrontier, llvm::MachineDominatorTreeWrapperPass, llvm::MachineLoopInfoWrapperPass, llvm::MachinePostDominatorTreeWrapperPass, llvm::MachineRegionInfoPass, llvm::MachineTraceMetricsWrapperPass, llvm::MemoryDependenceWrapperPass, llvm::MemorySSAWrapperPass, llvm::PhiValuesWrapperPass, llvm::PostDominatorTreeWrapperPass, llvm::RABasic, llvm::ReachingDefInfoWrapperPass, llvm::RegionInfoPass, llvm::ScalarEvolutionWrapperPass, llvm::SlotIndexesWrapperPass, llvm::UniformityInfoWrapperPass, and llvm::WebAssemblyExceptionInfo.
Definition at line 116 of file Pass.cpp.
Referenced by llvm::legacy::FunctionPassManagerImpl::releaseMemoryOnTheFly().
setResolver()
void Pass::setResolver (AnalysisResolver * AR)
Definition at line 132 of file Pass.cpp.
verifyAnalysis()
void Pass::verifyAnalysis () const virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented in llvm::AssumptionCacheTracker, llvm::DominatorTreeWrapperPass, llvm::LoopInfoWrapperPass, llvm::MachineDominatorTreeWrapperPass, llvm::MachinePostDominatorTreeWrapperPass, llvm::MachineRegionInfoPass, llvm::MachineTraceMetricsWrapperPass, llvm::MemorySSAWrapperPass, llvm::PostDominatorTreeWrapperPass, llvm::RegionInfoPass, and llvm::ScalarEvolutionWrapperPass.
Definition at line 120 of file Pass.cpp.
The documentation for this class was generated from the following files:
include/llvm/Pass.h
include/llvm/PassAnalysisSupport.h
lib/SandboxIR/Pass.cpp