LLVM: llvm::VPPhiAccessors Class Reference
llvm::VPPhiAccessors Class Reference abstract
Helper type to provide functions to access incoming values and blocks for phi-like recipes.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using const_incoming_blocks_range
Public Member Functions
virtual ~VPPhiAccessors ()=default
VPValue * getIncomingValue (unsigned Idx) const
Returns the incoming VPValue with index Idx.
const VPBasicBlock * getIncomingBlock (unsigned Idx) const
Returns the incoming block with index Idx.
virtual unsigned getNumIncoming () const
Returns the number of incoming values, also number of incoming blocks.
VPUser::const_operand_range incoming_values () const
Returns an interator range over the incoming values.
const_incoming_blocks_range incoming_blocks () const
Returns an iterator range over the incoming blocks.
detail::zippy< llvm::detail::zip_first, VPUser::const_operand_range, const_incoming_blocks_range > incoming_values_and_blocks () const
Returns an iterator range over pairs of incoming values and corresponding incoming blocks.
void removeIncomingValueFor (VPBlockBase *IncomingBlock) const
Removes the incoming value for IncomingBlock, which must be a predecessor.
void printPhiOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the recipe.
Protected Member Functions
virtual const VPRecipeBase * getAsRecipe () const =0
Return a VPRecipeBase* to the current object.
Detailed Description
Helper type to provide functions to access incoming values and blocks for phi-like recipes.
Definition at line 1328 of file VPlan.h.
Member Typedef Documentation
const_incoming_blocks_range
using llvm::VPPhiAccessors::const_incoming_blocks_range
Initial value:
iterator_range<mapped_iterator<
     detail::index_iterator, std::function<const VPBasicBlock *(size_t)>>>
Definition at line 1355 of file VPlan.h.
Constructor & Destructor Documentation
~VPPhiAccessors()
virtual llvm::VPPhiAccessors::~VPPhiAccessors () virtual default
Member Function Documentation
getAsRecipe()
virtual const VPRecipeBase * llvm::VPPhiAccessors::getAsRecipe () const protected pure virtual
Return a VPRecipeBase* to the current object.
Implemented in llvm::VPHeaderPHIRecipe, llvm::VPIRPhi, llvm::VPPhi, and llvm::VPWidenPHIRecipe.
Referenced by getIncomingBlock(), getIncomingValue(), getNumIncoming(), incoming_values(), printPhiOperands(), and removeIncomingValueFor().
getIncomingBlock()
const VPBasicBlock * llvm::VPPhiAccessors::getIncomingBlock (unsigned Idx) const inline
Returns the incoming block with index Idx.
Definition at line 4092 of file VPlan.h.
References getAsRecipe(), llvm::VPBasicBlock::getCFGPredecessor(), and llvm::VPRecipeBase::getParent().
Referenced by llvm::VPPhi::execute(), incoming_blocks(), and printPhiOperands().
getIncomingValue()
VPValue * llvm::VPPhiAccessors::getIncomingValue (unsigned Idx) const inline
Returns the incoming VPValue with index Idx.
Definition at line 1337 of file VPlan.h.
References getAsRecipe(), and llvm::VPUser::getOperand().
Referenced by llvm::VPPhi::execute().
getNumIncoming()
virtual unsigned llvm::VPPhiAccessors::getNumIncoming () const inline virtual
Returns the number of incoming values, also number of incoming blocks.
Reimplemented in llvm::VPReductionPHIRecipe, llvm::VPWidenInductionRecipe, and llvm::VPWidenIntOrFpInductionRecipe.
Definition at line 1345 of file VPlan.h.
References getAsRecipe(), and llvm::VPUser::getNumOperands().
Referenced by llvm::VPPhi::execute(), incoming_blocks(), and incoming_values().
incoming_blocks()
const_incoming_blocks_range llvm::VPPhiAccessors::incoming_blocks () const inline
Returns an iterator range over the incoming blocks.
Definition at line 1359 of file VPlan.h.
References getIncomingBlock(), getNumIncoming(), and llvm::map_range().
Referenced by incoming_values_and_blocks().
incoming_values()
VPUser::const_operand_range llvm::VPPhiAccessors::incoming_values () const inline
Returns an interator range over the incoming values.
Definition at line 1350 of file VPlan.h.
References getAsRecipe(), getNumIncoming(), and llvm::make_range().
Referenced by incoming_values_and_blocks().
incoming_values_and_blocks()
detail::zippy< llvm::detail::zip_first, VPUser::const_operand_range, const_incoming_blocks_range > llvm::VPPhiAccessors::incoming_values_and_blocks () const inline
Returns an iterator range over pairs of incoming values and corresponding incoming blocks.
Definition at line 1370 of file VPlan.h.
References incoming_blocks(), incoming_values(), and llvm::zip_equal().
Referenced by llvm::InnerLoopVectorizer::fixNonInductionPHIs(), and llvm::VPIRPhi::printRecipe().
printPhiOperands()
void VPPhiAccessors::printPhiOperands (raw_ostream & O, VPSlotTracker & SlotTracker) const
Print the recipe.
Definition at line 1694 of file VPlanRecipes.cpp.
References llvm::enumerate(), getAsRecipe(), getIncomingBlock(), llvm::interleaveComma(), and llvm::VPBlockBase::printAsOperand().
Referenced by llvm::VPPhi::printRecipe(), and llvm::VPWidenPHIRecipe::printRecipe().
removeIncomingValueFor()
void VPPhiAccessors::removeIncomingValueFor (VPBlockBase * IncomingBlock) const
Removes the incoming value for IncomingBlock, which must be a predecessor.
Definition at line 1685 of file VPlanRecipes.cpp.
References assert(), and getAsRecipe().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp