LLVM: llvm::hlsl::BindingInfo Class Reference
llvm::hlsl::BindingInfo Class Reference
BindingInfo represents the ranges of bindings and free space for each dxil::ResourceClass.
#include "llvm/Frontend/HLSL/HLSLBinding.h"
Classes
struct BindingRange
struct RegisterSpace
struct BindingSpaces
Public Member Functions
BindingSpaces & getBindingSpaces (dxil::ResourceClass RC)
const BindingSpaces & getBindingSpaces (dxil::ResourceClass RC) const
LLVM_ABI std::optional< uint32_t > findAvailableBinding (dxil::ResourceClass RC, uint32_t Space, int32_t Size)
Friends
class BindingInfoBuilder
Detailed Description
BindingInfo represents the ranges of bindings and free space for each dxil::ResourceClass.
This can represent HLSL-level bindings as well as bindings described in root signatures, and can be used for analysis of overlapping or missing bindings as well as for finding space for implicit bindings.
As an example, given these resource bindings:
RWBuffer<float> A[10] : register(u3); RWBuffer<float> B[] : register(u5, space2)
The binding info for UAV bindings should look like this:
UAVSpaces { ResClass = ResourceClass::UAV, Spaces = { { Space = 0u, FreeRanges = {{ 0u, 2u }, { 13u, ~0u }} }, { Space = 2u, FreeRanges = {{ 0u, 4u }} } } }
Definition at line 46 of file HLSLBinding.h.
Member Function Documentation
findAvailableBinding()
std::optional< uint32_t > BindingInfo::findAvailableBinding (dxil::ResourceClass RC, uint32_t Space, int32_t Size)
Definition at line 16 of file HLSLBinding.cpp.
References getBindingSpaces(), llvm::hlsl::BindingInfo::BindingSpaces::getOrInsertSpace(), and Size.
getBindingSpaces() [1/2]
BindingSpaces & llvm::hlsl::BindingInfo::getBindingSpaces (dxil::ResourceClass RC) inline
Definition at line 78 of file HLSLBinding.h.
References llvm::dxil::CBuffer, llvm_unreachable, llvm::dxil::Sampler, llvm::dxil::SRV, and llvm::dxil::UAV.
Referenced by findAvailableBinding(), and getBindingSpaces().
getBindingSpaces() [2/2]
const BindingSpaces & llvm::hlsl::BindingInfo::getBindingSpaces (dxil::ResourceClass RC) const inline
Definition at line 92 of file HLSLBinding.h.
References getBindingSpaces().
Friends And Related Symbol Documentation
BindingInfoBuilder
friend class BindingInfoBuilder friend
Definition at line 100 of file HLSLBinding.h.
References BindingInfoBuilder.
Referenced by BindingInfoBuilder.
The documentation for this class was generated from the following files:
include/llvm/Frontend/HLSL/HLSLBinding.h
lib/Frontend/HLSL/HLSLBinding.cpp