LLVM: llvm::object::elf_section_iterator Class Reference
llvm::object::elf_section_iterator Class Reference
#include "llvm/Object/ELFObjectFile.h"
Public Member Functions
elf_section_iterator (const section_iterator &B)
const ELFSectionRef * operator-> () const
const ELFSectionRef & operator* () const
Public Member Functions inherited from llvm::object::content_iterator< SectionRef >
content_iterator (SectionRef symb)
const SectionRef * operator-> () const
const SectionRef & operator* () const
bool operator== (const content_iterator &other) const
bool operator!= (const content_iterator &other) const
content_iterator & operator++ ()
Additional Inherited Members
Public Types inherited from llvm::object::content_iterator< SectionRef >
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Definition at line 156 of file ELFObjectFile.h.
Constructor & Destructor Documentation
elf_section_iterator()
llvm::object::elf_section_iterator::elf_section_iterator (const section_iterator & B) inline
Definition at line 158 of file ELFObjectFile.h.
References assert(), B(), and llvm::isa().
Member Function Documentation
operator*()
const ELFSectionRef & llvm::object::elf_section_iterator::operator* () const inline
Definition at line 166 of file ELFObjectFile.h.
References llvm::object::content_iterator< SectionRef >::operator*().
operator->()
const ELFSectionRef * llvm::object::elf_section_iterator::operator-> () const inline
Definition at line 162 of file ELFObjectFile.h.
References llvm::object::content_iterator< SectionRef >::operator->().
The documentation for this class was generated from the following file:
include/llvm/Object/ELFObjectFile.h