LLVM: llvm::cas::OnDiskDataAllocator::OnDiskPtr Class Reference
llvm::cas::OnDiskDataAllocator::OnDiskPtr Class Reference
A pointer to data stored on disk.
#include "llvm/CAS/OnDiskDataAllocator.h"
Public Member Functions
FileOffset getOffset () const
operator bool () const
const ValueProxy & operator* () const
const ValueProxy * operator-> () const
OnDiskPtr ()=default
Friends
class OnDiskDataAllocator
Detailed Description
A pointer to data stored on disk.
Definition at line 34 of file OnDiskDataAllocator.h.
Constructor & Destructor Documentation
OnDiskPtr()
llvm::cas::OnDiskDataAllocator::OnDiskPtr::OnDiskPtr () default
Member Function Documentation
getOffset()
FileOffset llvm::cas::OnDiskDataAllocator::OnDiskPtr::getOffset () const inline
Definition at line 36 of file OnDiskDataAllocator.h.
Referenced by operator bool().
operator bool()
llvm::cas::OnDiskDataAllocator::OnDiskPtr::operator bool () const inline explicit
Definition at line 37 of file OnDiskDataAllocator.h.
References getOffset().
operator*()
const ValueProxy & llvm::cas::OnDiskDataAllocator::OnDiskPtr::operator* () const inline
Definition at line 38 of file OnDiskDataAllocator.h.
References assert().
operator->()
const ValueProxy * llvm::cas::OnDiskDataAllocator::OnDiskPtr::operator-> () const inline
Definition at line 42 of file OnDiskDataAllocator.h.
References assert().
Friends And Related Symbol Documentation
OnDiskDataAllocator
friend class OnDiskDataAllocator friend
Definition at line 50 of file OnDiskDataAllocator.h.
References OnDiskDataAllocator.
Referenced by OnDiskDataAllocator.
The documentation for this class was generated from the following file:
include/llvm/CAS/OnDiskDataAllocator.h