LLVM: llvm::XtensaMCAsmInfo Class Reference
llvm::XtensaMCAsmInfo Class Reference
#include "Target/Xtensa/MCTargetDesc/XtensaMCAsmInfo.h"
Public Member Functions
XtensaMCAsmInfo (const Triple &TT)
void printSpecifierExpr (raw_ostream &OS, const MCSpecifierExpr &Expr) const override
Public Member Functions inherited from llvm::MCAsmInfo
MCAsmInfo ()
virtual ~MCAsmInfo ()
MCAsmInfo (MCAsmInfo const &)=delete
MCAsmInfo & operator= (MCAsmInfo const &)=delete
unsigned getCodePointerSize () const
Get the code pointer size in bytes.
unsigned getCalleeSaveStackSlotSize () const
Get the callee-saved register stack slot size in bytes.
bool isLittleEndian () const
True if the target is little endian.
bool isStackGrowthDirectionUp () const
True if target stack grow up.
bool hasSubsectionsViaSymbols () const
const char * getData8bitsDirective () const
const char * getData16bitsDirective () const
const char * getData32bitsDirective () const
const char * getData64bitsDirective () const
bool supportsSignedData () const
virtual const MCExpr * getExprForPersonalitySymbol (const MCSymbol *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCExpr * getExprForFDESymbol (const MCSymbol *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual bool isAcceptableChar (char C) const
Return true if C is an acceptable character inside a symbol name.
virtual bool isValidUnquotedName (StringRef Name) const
Return true if the identifier Name does not need quotes to be syntactically correct.
virtual bool shouldOmitSectionDirective (StringRef SectionName) const
Return true if the .section directive should be omitted when emitting SectionName.
bool usesSunStyleELFSectionSwitchSyntax () const
bool usesELFSectionDirectiveForBSS () const
bool needsDwarfSectionOffsetDirective () const
bool isAIX () const
bool isHLASM () const
bool isMachO () const
bool hasCOFFAssociativeComdats () const
bool hasCOFFComdatConstants () const
virtual unsigned getMaxInstLength (const MCSubtargetInfo *STI=nullptr) const
Returns the maximum possible encoded instruction size in bytes.
unsigned getMinInstAlignment () const
bool getDollarIsPC () const
const char * getSeparatorString () const
unsigned getCommentColumn () const
void setCommentColumn (unsigned Col)
StringRef getCommentString () const
bool shouldAllowAdditionalComments () const
const char * getLabelSuffix () const
bool usesSetToEquateSymbol () const
bool useAssignmentForEHBegin () const
bool needsLocalForSize () const
StringRef getPrivateGlobalPrefix () const
StringRef getPrivateLabelPrefix () const
bool hasLinkerPrivateGlobalPrefix () const
StringRef getLinkerPrivateGlobalPrefix () const
const char * getInlineAsmStart () const
const char * getInlineAsmEnd () const
unsigned getAssemblerDialect () const
bool doesAllowAtInName () const
void setAllowAtInName (bool V)
bool doesAllowQuestionAtStartOfIdentifier () const
bool doesAllowAtAtStartOfIdentifier () const
bool doesAllowDollarAtStartOfIdentifier () const
bool supportsNameQuoting () const
bool doesSupportDataRegionDirectives () const
bool hasLEB128Directives () const
bool useFullRegisterNames () const
void setFullRegisterNames (bool V)
const char * getZeroDirective () const
const char * getAsciiDirective () const
const char * getAscizDirective () const
AsmCharLiteralSyntax characterLiteralSyntax () const
bool getAlignmentIsInBytes () const
unsigned getTextAlignFillValue () const
const char * getGlobalDirective () const
bool doesSetDirectiveSuppressReloc () const
bool getCOMMDirectiveAlignmentIsInBytes () const
LCOMM::LCOMMType getLCOMMDirectiveAlignmentType () const
bool hasFunctionAlignment () const
bool hasDotTypeDotSizeDirective () const
bool hasSingleParameterDotFile () const
bool hasIdentDirective () const
bool hasNoDeadStrip () const
const char * getWeakDirective () const
const char * getWeakRefDirective () const
bool hasWeakDefCanBeHiddenDirective () const
bool avoidWeakIfComdat () const
MCSymbolAttr getHiddenVisibilityAttr () const
MCSymbolAttr getExportedVisibilityAttr () const
MCSymbolAttr getHiddenDeclarationVisibilityAttr () const
MCSymbolAttr getProtectedVisibilityAttr () const
bool doesSupportDebugInformation () const
ExceptionHandling getExceptionHandlingType () const
WinEH::EncodingType getWinEHEncodingType () const
void setExceptionsType (ExceptionHandling EH)
bool usesCFIWithoutEH () const
bool usesCFIForEH () const
Returns true if the exception handling method for the platform uses call frame information to unwind.
bool usesWindowsCFI () const
bool doesDwarfUseRelocationsAcrossSections () const
bool doDwarfFDESymbolsUseAbsDiff () const
bool useDwarfRegNumForCFI () const
bool useAtForSpecifier () const
bool useParensForSpecifier () const
bool supportsExtendedDwarfLocDirective () const
bool usesDwarfFileAndLocDirectives () const
bool enableDwarfFileDirectoryDefault () const
void addInitialFrameState (const MCCFIInstruction &Inst)
const std::vector< MCCFIInstruction > & getInitialFrameState () const
void setBinutilsVersion (std::pair< int, int > Value)
bool useIntegratedAssembler () const
Return true if assembly (inline or otherwise) should be parsed.
bool parseInlineAsmUsingAsmParser () const
Return true if target want to use AsmParser to parse inlineasm.
bool binutilsIsAtLeast (int Major, int Minor) const
virtual void setUseIntegratedAssembler (bool Value)
Set whether assembly (inline or otherwise) should be parsed.
virtual void setParseInlineAsmUsingAsmParser (bool Value)
Set whether target want to use AsmParser to parse inlineasm.
bool preserveAsmComments () const
Return true if assembly (inline or otherwise) should be parsed.
virtual void setPreserveAsmComments (bool Value)
Set whether assembly (inline or otherwise) should be parsed.
bool shouldUseLogicalShr () const
bool shouldUseMotorolaIntegers () const
StringRef getSpecifierName (uint32_t S) const
std::optional< uint32_t > getSpecifierForName (StringRef Name) const
void printExpr (raw_ostream &, const MCExpr &) const
virtual bool evaluateAsRelocatableImpl (const MCSpecifierExpr &, MCValue &Res, const MCAssembler *Asm) const
Additional Inherited Members
Public Types inherited from llvm::MCAsmInfo
enum AsmCharLiteralSyntax { ACLS_Unknown , ACLS_SingleQuotePrefix }
Assembly character literal syntax types.
Protected Member Functions inherited from llvm::MCAsmInfoELF
MCAsmInfoELF ()
Protected Member Functions inherited from llvm::MCAsmInfo
void initializeAtSpecifiers (ArrayRef< AtSpecifier >)
Protected Attributes inherited from llvm::MCAsmInfo
unsigned CodePointerSize = 4
Code pointer size in bytes. Default is 4.
unsigned CalleeSaveStackSlotSize = 4
Size of the stack slot reserved for callee-saved registers, in bytes.
bool IsLittleEndian = true
True if target is little endian. Default is true.
bool StackGrowsUp = false
True if target stack grow up. Default is false.
bool HasSubsectionsViaSymbols = false
True if this target has the MachO .subsections_via_symbols directive.
bool HasCOFFAssociativeComdats = false
True if this is a non-GNU COFF target.
bool HasCOFFComdatConstants = false
True if this is a non-GNU COFF target.
bool IsAIX = false
bool IsHLASM = false
unsigned MaxInstLength = 4
This is the maximum possible length of an instruction, which is needed to compute the size of an inline asm.
unsigned MinInstAlignment = 1
Every possible instruction length is a multiple of this value.
bool DollarIsPC = false
The '$' token, when not referencing an identifier or constant, refers to the current PC.
const char * SeparatorString
This string, if specified, is used to separate instructions from each other when on the same line.
StringRef CommentString
This indicates the comment string used by the assembler.
bool AllowAdditionalComments = true
This indicates whether to allow additional "comment strings" to be lexed as a comment.
const char * LabelSuffix
This is appended to emitted labels. Defaults to ":".
bool UsesSetToEquateSymbol = false
Use .set instead of = to equate a symbol to an expression.
bool UseAssignmentForEHBegin = false
bool NeedsLocalForSize = false
StringRef PrivateGlobalPrefix
This prefix is used for globals like constant pool entries that are completely private to the .s file and should not have names in the .o file.
StringRef PrivateLabelPrefix
This prefix is used for labels for basic blocks.
StringRef LinkerPrivateGlobalPrefix
This prefix is used for symbols that should be passed through the assembler but be removed by the linker.
const char * InlineAsmStart
If these are nonempty, they contain a directive to emit before and after an inline assembly statement.
const char * InlineAsmEnd
unsigned AssemblerDialect = 0
Which dialect of an assembler variant to use. Defaults to 0.
bool AllowAtInName = false
This is true if the assembler allows @ characters in symbol names.
bool AllowQuestionAtStartOfIdentifier = false
This is true if the assembler allows the "?" character at the start of of a string to be lexed as an AsmToken::Identifier.
bool AllowDollarAtStartOfIdentifier = false
This is true if the assembler allows the "$" character at the start of of a string to be lexed as an AsmToken::Identifier.
bool AllowAtAtStartOfIdentifier = false
This is true if the assembler allows the "@" character at the start of a string to be lexed as an AsmToken::Identifier.
bool SupportsQuotedNames = true
If this is true, symbol names with invalid characters will be printed in quotes.
bool UseDataRegionDirectives = false
This is true if data region markers should be printed as ".data_region/.end_data_region" directives.
bool HasLEB128Directives = true
True if the target supports LEB128 directives.
bool PPCUseFullRegisterNames = false
True if full register names are printed.
const char * ZeroDirective
This should be set to the directive used to get some number of zero (and non-zero if supported by the directive) bytes emitted to the current section.
const char * AsciiDirective
This directive allows emission of an ascii string with the standard C escape characters embedded into it.
const char * AscizDirective
If not null, this allows for special handling of zero terminated strings on this target.
AsmCharLiteralSyntax CharacterLiteralSyntax = ACLS_Unknown
Form used for character literals in the assembly syntax.
const char * Data8bitsDirective
These directives are used to output some unit of integer data to the current section.
const char * Data16bitsDirective
const char * Data32bitsDirective
const char * Data64bitsDirective
bool SupportsSignedData = true
True if data directives support signed values.
bool SunStyleELFSectionSwitchSyntax = false
This is true if this target uses "Sun Style" syntax for section switching ("#alloc,#write" etc) instead of the normal ELF syntax (,"a,w") in .section directives.
bool UsesELFSectionDirectiveForBSS = false
This is true if this target uses ELF '.section' directive before the '.bss' one.
bool NeedsDwarfSectionOffsetDirective = false
bool AlignmentIsInBytes = true
If this is true (the default) then the asmprinter emits ".align N" directives, where N is the number of bytes to align to.
unsigned TextAlignFillValue = 0
If non-zero, this is used to fill the executable space created as the result of a alignment directive.
const char * GlobalDirective
This is the directive used to declare a global entity.
bool SetDirectiveSuppressesReloc = false
True if the expression .long f - g uses a relocation but it can be suppressed by writing a = f - g .long a.
bool COMMDirectiveAlignmentIsInBytes = true
True is .comm's and .lcomms optional alignment is to be specified in bytes instead of log2(n).
LCOMM::LCOMMType LCOMMDirectiveAlignmentType = LCOMM::NoAlignment
Describes if the .lcomm directive for the target supports an alignment argument and how it is interpreted.
bool HasFunctionAlignment = true
bool HasDotTypeDotSizeDirective = true
True if the target has .type and .size directives, this is true for most ELF targets.
bool HasSingleParameterDotFile = true
True if the target has a single parameter .file directive, this is true for ELF targets.
bool HasIdentDirective = false
True if the target has a .ident directive, this is true for ELF targets.
bool HasNoDeadStrip = false
True if this target supports the MachO .no_dead_strip directive.
const char * WeakDirective
Used to declare a global as being a weak symbol. Defaults to ".weak".
const char * WeakRefDirective = nullptr
This directive, if non-null, is used to declare a global as being a weak undefined symbol.
bool HasWeakDefCanBeHiddenDirective = false
True if we have a directive to declare a global as being a weak defined symbol that can be hidden (unexported).
bool AvoidWeakIfComdat = false
True if we should mark symbols as global instead of weak, for weak*‍/linkonce*, if the symbol has a comdat.
MCSymbolAttr HiddenVisibilityAttr = MCSA_Hidden
This attribute, if not MCSA_Invalid, is used to declare a symbol as having hidden visibility.
MCSymbolAttr ExportedVisibilityAttr = MCSA_Exported
This attribute, if not MCSA_Invalid, is used to declare a symbol as having exported visibility.
MCSymbolAttr HiddenDeclarationVisibilityAttr = MCSA_Hidden
This attribute, if not MCSA_Invalid, is used to declare an undefined symbol as having hidden visibility.
MCSymbolAttr ProtectedVisibilityAttr = MCSA_Protected
This attribute, if not MCSA_Invalid, is used to declare a symbol as having protected visibility.
bool SupportsDebugInformation = false
True if target supports emission of debugging information.
ExceptionHandling ExceptionsType = ExceptionHandling::None
Exception handling format for the target. Defaults to None.
bool UsesCFIWithoutEH = false
True if target uses CFI unwind information for other purposes than EH (debugging / sanitizers) when ExceptionsType == ExceptionHandling::None.
WinEH::EncodingType WinEHEncodingType = WinEH::EncodingType::Invalid
Windows exception handling data (.pdata) encoding. Defaults to Invalid.
bool DwarfUsesRelocationsAcrossSections = true
True if Dwarf2 output generally uses relocations for references to other .debug_* sections.
bool DwarfFDESymbolsUseAbsDiff = false
True if DWARF FDE symbol reference relocations should be replaced by an absolute difference.
bool DwarfRegNumForCFI = false
True if DWARF `.file directory' directive syntax is used by default.
bool UseAtForSpecifier = true
True if target uses @ (expr@specifier) for relocation specifiers.
bool UseParensForSpecifier = false
(ARM-specific) Uses parens for relocation specifier in data directives, e.g.
bool SupportsExtendedDwarfLocDirective = true
True if the target supports flags in ".loc" directive, false if only location is allowed.
std::vector< MCCFIInstruction > InitialFrameState
std::pair< int, int > BinutilsVersion = {2, 26}
bool UseIntegratedAssembler
Should we use the integrated assembler?
bool ParseInlineAsmUsingAsmParser
Use AsmParser to parse inlineAsm when UseIntegratedAssembler is not set.
bool PreserveAsmComments
Preserve Comments in assembly.
unsigned CommentColumn = 40
The column (zero-based) at which asm comments should be printed.
bool UseLogicalShr = true
True if the integrated assembler should interpret 'a >> b' constant expressions as logical rather than arithmetic.
bool UseMotorolaIntegers = false
llvm::DenseMap< uint32_t, StringRef > AtSpecifierToName
llvm::StringMap< uint32_t > NameToAtSpecifier
Detailed Description
Definition at line 25 of file XtensaMCAsmInfo.h.
Constructor & Destructor Documentation
XtensaMCAsmInfo()
XtensaMCAsmInfo::XtensaMCAsmInfo (const Triple & TT) explicit
Definition at line 21 of file XtensaMCAsmInfo.cpp.
References llvm::MCAsmInfo::AlignmentIsInBytes, llvm::MCAsmInfo::CalleeSaveStackSlotSize, llvm::MCAsmInfo::CodePointerSize, llvm::MCAsmInfo::CommentString, llvm::MCAsmInfo::Data64bitsDirective, llvm::DwarfCFI, llvm::MCAsmInfo::ExceptionsType, llvm::MCAsmInfo::GlobalDirective, llvm::MCAsmInfo::PrivateGlobalPrefix, llvm::MCAsmInfo::SupportsDebugInformation, llvm::MCAsmInfo::UsesELFSectionDirectiveForBSS, and llvm::MCAsmInfo::ZeroDirective.
Member Function Documentation
printSpecifierExpr()
void XtensaMCAsmInfo::printSpecifierExpr (raw_ostream & OS, const MCSpecifierExpr & Expr) const override virtual
Reimplemented from llvm::MCAsmInfo.
Definition at line 35 of file XtensaMCAsmInfo.cpp.
References llvm::StringRef::empty(), llvm::MCSpecifierExpr::getSpecifier(), llvm::Xtensa::getSpecifierName(), llvm::MCSpecifierExpr::getSubExpr(), and llvm::MCAsmInfo::printExpr().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/MCTargetDesc/XtensaMCAsmInfo.h
lib/Target/Xtensa/MCTargetDesc/XtensaMCAsmInfo.cpp