LLVM: llvm::AttrBuilder Class Reference
llvm::AttrBuilder Class Reference
This class is used in conjunction with the Attribute::get method to create an Attribute object.
#include "llvm/IR/Attributes.h"
Public Member Functions
AttrBuilder (LLVMContext &Ctx)
AttrBuilder (const AttrBuilder &)=delete
AttrBuilder (AttrBuilder &&)=default
AttrBuilder (LLVMContext &Ctx, const Attribute &A)
LLVM_ABI AttrBuilder (LLVMContext &Ctx, AttributeSet AS)
LLVM_ABI void clear ()
LLVM_ABI AttrBuilder & addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
LLVM_ABI AttrBuilder & addAttribute (Attribute A)
Add the Attribute object to the builder.
LLVM_ABI AttrBuilder & addAttribute (StringRef A, StringRef V=StringRef())
Add the target-dependent attribute to the builder.
LLVM_ABI AttrBuilder & removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
LLVM_ABI AttrBuilder & removeAttribute (StringRef A)
Remove the target-dependent attribute from the builder.
AttrBuilder & removeAttribute (Attribute A)
Remove the target-dependent attribute from the builder.
LLVM_ABI AttrBuilder & merge (const AttrBuilder &B)
Add the attributes from the builder.
LLVM_ABI AttrBuilder & remove (const AttributeMask &AM)
Remove the attributes from the builder.
LLVM_ABI bool overlaps (const AttributeMask &AM) const
Return true if the builder has any attribute that's in the specified builder.
LLVM_ABI bool contains (Attribute::AttrKind A) const
Return true if the builder has the specified attribute.
LLVM_ABI bool contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
bool hasAttributes () const
Return true if the builder has IR-level attributes.
LLVM_ABI Attribute getAttribute (Attribute::AttrKind Kind) const
Return Attribute with the given Kind.
LLVM_ABI Attribute getAttribute (StringRef Kind) const
Return Attribute with the given Kind.
LLVM_ABI std::optional< ConstantRange > getRange () const
Retrieve the range if the attribute exists (std::nullopt is returned otherwise).
LLVM_ABI std::optional< uint64_t > getRawIntAttr (Attribute::AttrKind Kind) const
Return raw (possibly packed/encoded) value of integer attribute or std::nullopt if not set.
MaybeAlign getAlignment () const
Retrieve the alignment attribute, if it exists.
MaybeAlign getStackAlignment () const
Retrieve the stack alignment attribute, if it exists.
uint64_t getDereferenceableBytes () const
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
uint64_t getDereferenceableOrNullBytes () const
Retrieve the number of dereferenceable_or_null bytes, if the dereferenceable_or_null attribute exists (zero is returned otherwise).
FPClassTest getNoFPClass () const
Retrieve the bitmask for nofpclass, if the nofpclass attribute exists (fcNone is returned otherwise).
LLVM_ABI Type * getTypeAttr (Attribute::AttrKind Kind) const
Retrieve type for the given type attribute.
Type * getByValType () const
Retrieve the byval type.
Type * getStructRetType () const
Retrieve the sret type.
Type * getByRefType () const
Retrieve the byref type.
Type * getPreallocatedType () const
Retrieve the preallocated type.
Type * getInAllocaType () const
Retrieve the inalloca type.
LLVM_ABI std::optional< std::pair< unsigned, std::optional< unsigned > > > getAllocSizeArgs () const
Retrieve the allocsize args, or std::nullopt if the attribute does not exist.
LLVM_ABI AttrBuilder & addRawIntAttr (Attribute::AttrKind Kind, uint64_t Value)
Add integer attribute with raw value (packed/encoded if necessary).
LLVM_ABI AttrBuilder & addAlignmentAttr (MaybeAlign Align)
This turns an alignment into the form used internally in Attribute.
AttrBuilder & addAlignmentAttr (unsigned Align)
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addStackAlignmentAttr (MaybeAlign Align)
This turns a stack alignment into the form used internally in Attribute.
AttrBuilder & addStackAlignmentAttr (unsigned Align)
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addDereferenceableOrNullAttr (uint64_t Bytes)
This turns the number of dereferenceable_or_null bytes into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addAllocSizeAttr (unsigned ElemSizeArg, const std::optional< unsigned > &NumElemsArg)
This turns one (or two) ints into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addVScaleRangeAttr (unsigned MinValue, std::optional< unsigned > MaxValue)
This turns two ints into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addTypeAttr (Attribute::AttrKind Kind, Type *Ty)
Add a type attribute with the given type.
LLVM_ABI AttrBuilder & addByValAttr (Type *Ty)
This turns a byval type into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addStructRetAttr (Type *Ty)
This turns a sret type into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addByRefAttr (Type *Ty)
This turns a byref type into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addPreallocatedAttr (Type *Ty)
This turns a preallocated type into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addInAllocaAttr (Type *Ty)
This turns an inalloca type into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addAllocSizeAttrFromRawRepr (uint64_t RawAllocSizeRepr)
Add an allocsize attribute, using the representation returned by Attribute.getIntValue().
LLVM_ABI AttrBuilder & addVScaleRangeAttrFromRawRepr (uint64_t RawVScaleRangeRepr)
Add a vscale_range attribute, using the representation returned by Attribute.getIntValue().
LLVM_ABI AttrBuilder & addUWTableAttr (UWTableKind Kind)
This turns the unwind table kind into the form used internally in Attribute.
LLVM_ABI AttrBuilder & addAllocKindAttr (AllocFnKind Kind)
LLVM_ABI AttrBuilder & addMemoryAttr (MemoryEffects ME)
Add memory effect attribute.
LLVM_ABI AttrBuilder & addCapturesAttr (CaptureInfo CI)
Add captures attribute.
LLVM_ABI AttrBuilder & addNoFPClassAttr (FPClassTest NoFPClassMask)
LLVM_ABI AttrBuilder & addConstantRangeAttr (Attribute::AttrKind Kind, const ConstantRange &CR)
Add a ConstantRange attribute with the given range.
LLVM_ABI AttrBuilder & addRangeAttr (const ConstantRange &CR)
Add range attribute.
LLVM_ABI AttrBuilder & addConstantRangeListAttr (Attribute::AttrKind Kind, ArrayRef< ConstantRange > Val)
Add a ConstantRangeList attribute with the given ranges.
LLVM_ABI AttrBuilder & addInitializesAttr (const ConstantRangeList &CRL)
Add initializes attribute.
LLVM_ABI AttrBuilder & addFromEquivalentMetadata (const Instruction &I)
Add 0 or more parameter attributes which are equivalent to metadata attached to I.
ArrayRef< Attribute > attrs () const
LLVM_ABI bool operator== (const AttrBuilder &B) const
bool operator!= (const AttrBuilder &B) const
Detailed Description
This class is used in conjunction with the Attribute::get method to create an Attribute object.
The object itself is uniquified. The Builder's value, however, is not. So this can be used as a quick way to test for equality, presence of attributes, etc.
Definition at line 1082 of file Attributes.h.
Constructor & Destructor Documentation
AttrBuilder() [1/5]
llvm::AttrBuilder::AttrBuilder (LLVMContext & Ctx) inline
Definition at line 1087 of file Attributes.h.
Referenced by addAlignmentAttr(), addAlignmentAttr(), addAllocKindAttr(), addAllocSizeAttrFromRawRepr(), addAttribute(), addAttribute(), addAttribute(), addByRefAttr(), addByValAttr(), addCapturesAttr(), addConstantRangeAttr(), addDereferenceableAttr(), addDereferenceableOrNullAttr(), addFromEquivalentMetadata(), addInAllocaAttr(), addInitializesAttr(), addMemoryAttr(), addNoFPClassAttr(), addPreallocatedAttr(), addRangeAttr(), addRawIntAttr(), addStackAlignmentAttr(), addStackAlignmentAttr(), addStructRetAttr(), addTypeAttr(), addUWTableAttr(), addVScaleRangeAttr(), addVScaleRangeAttrFromRawRepr(), AttrBuilder(), AttrBuilder(), merge(), operator!=(), operator==(), remove(), removeAttribute(), removeAttribute(), and removeAttribute().
AttrBuilder() [2/5]
llvm::AttrBuilder::AttrBuilder (const AttrBuilder &) delete
References AttrBuilder().
AttrBuilder() [3/5]
llvm::AttrBuilder::AttrBuilder (AttrBuilder &&) default
References AttrBuilder().
AttrBuilder() [4/5]
llvm::AttrBuilder::AttrBuilder (LLVMContext & Ctx, const Attribute & A) inline
Definition at line 1091 of file Attributes.h.
References A(), and addAttribute().
AttrBuilder() [5/5]
AttrBuilder::AttrBuilder (LLVMContext & Ctx, AttributeSet AS)
Definition at line 2085 of file Attributes.cpp.
References llvm::append_range(), assert(), and llvm::is_sorted().
Member Function Documentation
addAlignmentAttr() [1/2]
AttrBuilder & AttrBuilder::addAlignmentAttr (MaybeAlign Align)
This turns an alignment into the form used internally in Attribute.
This call has no effect if Align is not set.
Definition at line 2185 of file Attributes.cpp.
References addRawIntAttr(), assert(), AttrBuilder(), llvm::Value::MaximumAlignment, and llvm::Align::value().
Referenced by addAlignmentAttr(), addFramePointerAttrs(), addFromEquivalentMetadata(), llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy(), and llvm::AttributeSet::intersectWith().
addAlignmentAttr() [2/2]
AttrBuilder & llvm::AttrBuilder::addAlignmentAttr (unsigned Align) inline
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
This call has no effect if Align is 0. Deprecated, use the version using a MaybeAlign.
Definition at line 1225 of file Attributes.h.
References addAlignmentAttr(), and AttrBuilder().
addAllocKindAttr()
AttrBuilder & AttrBuilder::addAllocKindAttr (AllocFnKind Kind)
Definition at line 2261 of file Attributes.cpp.
References addRawIntAttr(), and AttrBuilder().
Referenced by llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy().
addAllocSizeAttr()
AttrBuilder & AttrBuilder::addAllocSizeAttr (unsigned ElemSizeArg, const std::optional< unsigned > & NumElemsArg)
This turns one (or two) ints into the form used internally in Attribute.
Definition at line 2216 of file Attributes.cpp.
References addAllocSizeAttrFromRawRepr(), and packAllocSizeArgs().
Referenced by llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy().
addAllocSizeAttrFromRawRepr()
AttrBuilder & AttrBuilder::addAllocSizeAttrFromRawRepr (uint64_t RawAllocSizeRepr)
Add an allocsize attribute, using the representation returned by Attribute.getIntValue().
Definition at line 2221 of file Attributes.cpp.
References addRawIntAttr(), assert(), and AttrBuilder().
Referenced by addAllocSizeAttr().
addAttribute() [1/3]
AttrBuilder & AttrBuilder::addAttribute (Attribute A)
Add the Attribute object to the builder.
Definition at line 2130 of file Attributes.cpp.
References addAttributeImpl(), AttrBuilder(), llvm::Attribute::getKindAsEnum(), llvm::Attribute::getKindAsString(), and llvm::Attribute::isStringAttribute().
addAttribute() [2/3]
AttrBuilder & AttrBuilder::addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
Definition at line 2138 of file Attributes.cpp.
References addAttributeImpl(), AttrBuilder(), and llvm::Attribute::get().
Referenced by addAsyncContextAttrs(), addConstantRangeAttr(), addConstantRangeListAttr(), addFramePointerAttrs(), addFromEquivalentMetadata(), addRawIntAttr(), addSwiftSelfAttrs(), addTypeAttr(), AttrBuilder(), llvm::OpenMPIRBuilder::createReductionsGPU(), llvm::AtomicInfo::EmitAtomicLibcall(), llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy(), llvm::AttributeSet::intersectWith(), merge(), and llvm::codegen::setFunctionAttributes().
addAttribute() [3/3]
AttrBuilder & AttrBuilder::addAttribute (StringRef A, StringRef V = StringRef())
Add the target-dependent attribute to the builder.
Definition at line 2143 of file Attributes.cpp.
References A(), addAttributeImpl(), AttrBuilder(), and llvm::Attribute::get().
addByRefAttr()
AttrBuilder & AttrBuilder::addByRefAttr (Type * Ty)
This turns a byref type into the form used internally in Attribute.
Definition at line 2283 of file Attributes.cpp.
References addTypeAttr(), and AttrBuilder().
addByValAttr()
AttrBuilder & AttrBuilder::addByValAttr (Type * Ty)
This turns a byval type into the form used internally in Attribute.
Definition at line 2275 of file Attributes.cpp.
References addTypeAttr(), and AttrBuilder().
Referenced by llvm::promoteCall().
addCapturesAttr()
AttrBuilder & AttrBuilder::addCapturesAttr (CaptureInfo CI)
Add captures attribute.
Definition at line 2250 of file Attributes.cpp.
References addRawIntAttr(), AttrBuilder(), and llvm::CaptureInfo::toIntValue().
Referenced by llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy(), and llvm::AttributeSet::intersectWith().
addConstantRangeAttr()
AttrBuilder & AttrBuilder::addConstantRangeAttr (Attribute::AttrKind Kind, const ConstantRange & CR)
Add a ConstantRange attribute with the given range.
Definition at line 2295 of file Attributes.cpp.
References addAttribute(), AttrBuilder(), llvm::Attribute::get(), and llvm::ConstantRange::isFullSet().
Referenced by addRangeAttr().
addConstantRangeListAttr()
AttrBuilder & AttrBuilder::addConstantRangeListAttr (Attribute::AttrKind Kind, ArrayRef< ConstantRange > Val)
Add a ConstantRangeList attribute with the given ranges.
Definition at line 2308 of file Attributes.cpp.
References addAttribute(), and llvm::Attribute::get().
Referenced by addInitializesAttr().
addDereferenceableAttr()
AttrBuilder & AttrBuilder::addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
Definition at line 2202 of file Attributes.cpp.
References addRawIntAttr(), and AttrBuilder().
Referenced by addFramePointerAttrs(), and addFromEquivalentMetadata().
addDereferenceableOrNullAttr()
AttrBuilder & AttrBuilder::addDereferenceableOrNullAttr (uint64_t Bytes)
This turns the number of dereferenceable_or_null bytes into the form used internally in Attribute.
Definition at line 2208 of file Attributes.cpp.
References addRawIntAttr(), and AttrBuilder().
addFromEquivalentMetadata()
AttrBuilder & AttrBuilder::addFromEquivalentMetadata (const Instruction & I)
Add 0 or more parameter attributes which are equivalent to metadata attached to I.
e.g. !align -> align. This assumes the argument type is the same as the original instruction and the attribute is compatible.
Definition at line 2317 of file Attributes.cpp.
References addAlignmentAttr(), addAttribute(), addDereferenceableAttr(), addRangeAttr(), AttrBuilder(), llvm::mdconst::extract(), llvm::getConstantRangeFromMetadata(), llvm::ConstantInt::getZExtValue(), I, and Range.
addInAllocaAttr()
AttrBuilder & AttrBuilder::addInAllocaAttr (Type * Ty)
This turns an inalloca type into the form used internally in Attribute.
Definition at line 2291 of file Attributes.cpp.
References addTypeAttr(), and AttrBuilder().
Referenced by llvm::promoteCall().
addInitializesAttr()
AttrBuilder & AttrBuilder::addInitializesAttr (const ConstantRangeList & CRL)
Add initializes attribute.
Definition at line 2313 of file Attributes.cpp.
References addConstantRangeListAttr(), AttrBuilder(), and llvm::ConstantRangeList::rangesRef().
addMemoryAttr()
AttrBuilder & AttrBuilder::addMemoryAttr (MemoryEffects ME)
Add memory effect attribute.
Definition at line 2246 of file Attributes.cpp.
References addRawIntAttr(), AttrBuilder(), and llvm::MemoryEffectsBase< LocationEnum >::toIntValue().
Referenced by llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy(), and llvm::AttributeSet::intersectWith().
addNoFPClassAttr()
AttrBuilder & AttrBuilder::addNoFPClassAttr (FPClassTest NoFPClassMask)
Definition at line 2254 of file Attributes.cpp.
References addRawIntAttr(), AttrBuilder(), and llvm::fcNone.
Referenced by AddParamAndFnBasicAttributes(), and llvm::AttributeSet::intersectWith().
addPreallocatedAttr()
AttrBuilder & AttrBuilder::addPreallocatedAttr (Type * Ty)
This turns a preallocated type into the form used internally in Attribute.
Definition at line 2287 of file Attributes.cpp.
References addTypeAttr(), and AttrBuilder().
addRangeAttr()
AttrBuilder & AttrBuilder::addRangeAttr (const ConstantRange & CR)
Add range attribute.
Definition at line 2303 of file Attributes.cpp.
References addConstantRangeAttr(), and AttrBuilder().
Referenced by addFromEquivalentMetadata(), AddParamAndFnBasicAttributes(), AddReturnAttributes(), and llvm::AttributeSet::intersectWith().
addRawIntAttr()
AttrBuilder & AttrBuilder::addRawIntAttr (Attribute::AttrKind Kind, uint64_t Value)
Add integer attribute with raw value (packed/encoded if necessary).
Definition at line 2172 of file Attributes.cpp.
References addAttribute(), AttrBuilder(), and llvm::Attribute::get().
Referenced by addAlignmentAttr(), addAllocKindAttr(), addAllocSizeAttrFromRawRepr(), addCapturesAttr(), addDereferenceableAttr(), addDereferenceableOrNullAttr(), addMemoryAttr(), addNoFPClassAttr(), addStackAlignmentAttr(), addUWTableAttr(), addVScaleRangeAttrFromRawRepr(), and llvm::AttributeSet::intersectWith().
addStackAlignmentAttr() [1/2]
AttrBuilder & AttrBuilder::addStackAlignmentAttr (MaybeAlign Align)
This turns a stack alignment into the form used internally in Attribute.
This call has no effect if Align is not set.
Definition at line 2193 of file Attributes.cpp.
References addRawIntAttr(), assert(), AttrBuilder(), and llvm::Align::value().
Referenced by addStackAlignmentAttr().
addStackAlignmentAttr() [2/2]
AttrBuilder & llvm::AttrBuilder::addStackAlignmentAttr (unsigned Align) inline
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
This call has no effect if Align is 0. Deprecated, use the version using a MaybeAlign.
Definition at line 1237 of file Attributes.h.
References addStackAlignmentAttr(), and AttrBuilder().
addStructRetAttr()
AttrBuilder & AttrBuilder::addStructRetAttr (Type * Ty)
This turns a sret type into the form used internally in Attribute.
Definition at line 2279 of file Attributes.cpp.
References addTypeAttr(), and AttrBuilder().
Referenced by llvm::RTLIB::RuntimeLibcallsInfo::getFunctionTy().
addTypeAttr()
AttrBuilder & AttrBuilder::addTypeAttr (Attribute::AttrKind Kind, Type * Ty)
Add a type attribute with the given type.
Definition at line 2271 of file Attributes.cpp.
References addAttribute(), AttrBuilder(), and llvm::Attribute::get().
Referenced by addByRefAttr(), addByValAttr(), addInAllocaAttr(), addPreallocatedAttr(), and addStructRetAttr().
addUWTableAttr()
AttrBuilder & AttrBuilder::addUWTableAttr (UWTableKind Kind)
This turns the unwind table kind into the form used internally in Attribute.
Definition at line 2240 of file Attributes.cpp.
References addRawIntAttr(), AttrBuilder(), and llvm::None.
addVScaleRangeAttr()
AttrBuilder & AttrBuilder::addVScaleRangeAttr (unsigned MinValue, std::optional< unsigned > MaxValue)
This turns two ints into the form used internally in Attribute.
Definition at line 2227 of file Attributes.cpp.
References addVScaleRangeAttrFromRawRepr(), AttrBuilder(), and packVScaleRangeArgs().
addVScaleRangeAttrFromRawRepr()
AttrBuilder & AttrBuilder::addVScaleRangeAttrFromRawRepr (uint64_t RawVScaleRangeRepr)
Add a vscale_range attribute, using the representation returned by Attribute.getIntValue().
Definition at line 2232 of file Attributes.cpp.
References addRawIntAttr(), and AttrBuilder().
Referenced by addVScaleRangeAttr().
attrs()
ArrayRef< Attribute > llvm::AttrBuilder::attrs () const inline
Definition at line 1320 of file Attributes.h.
clear()
void AttrBuilder::clear ()
Definition at line 2090 of file Attributes.cpp.
contains() [1/2]
bool AttrBuilder::contains (Attribute::AttrKind A) const
Return true if the builder has the specified attribute.
Definition at line 2388 of file Attributes.cpp.
References A(), getAttribute(), and llvm::Attribute::isValid().
Referenced by llvm::attributesPermitTailCall(), and llvm::TargetLowering::isInTailCallPosition().
contains() [2/2]
bool AttrBuilder::contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
Definition at line 2392 of file Attributes.cpp.
References A(), getAttribute(), and llvm::Attribute::isValid().
getAlignment()
MaybeAlign llvm::AttrBuilder::getAlignment () const inline
Retrieve the alignment attribute, if it exists.
Definition at line 1161 of file Attributes.h.
References getRawIntAttr().
Referenced by AddParamAndFnBasicAttributes(), and AddReturnAttributes().
getAllocSizeArgs()
std::optional< std::pair< unsigned, std::optional< unsigned > > > AttrBuilder::getAllocSizeArgs () const
Retrieve the allocsize args, or std::nullopt if the attribute does not exist.
Definition at line 2178 of file Attributes.cpp.
References A(), and getAttribute().
getAttribute() [1/2]
Attribute AttrBuilder::getAttribute (Attribute::AttrKind Kind) const
Return Attribute with the given Kind.
The returned attribute will be invalid if the Kind is not present in the builder.
Definition at line 2366 of file Attributes.cpp.
References A(), assert(), llvm::Attribute::EndAttrKinds, and llvm::lower_bound().
Referenced by AddReturnAttributes(), contains(), contains(), getAllocSizeArgs(), getRange(), getRawIntAttr(), and getTypeAttr().
getAttribute() [2/2]
Attribute AttrBuilder::getAttribute (StringRef Kind) const
Return Attribute with the given Kind.
The returned attribute will be invalid if the Kind is not present in the builder.
Definition at line 2374 of file Attributes.cpp.
References A(), and llvm::lower_bound().
getByRefType()
Type * llvm::AttrBuilder::getByRefType () const inline
Retrieve the byref type.
Definition at line 1199 of file Attributes.h.
References getTypeAttr().
getByValType()
Type * llvm::AttrBuilder::getByValType () const inline
Retrieve the byval type.
Definition at line 1193 of file Attributes.h.
References getTypeAttr().
Referenced by llvm::promoteCall().
getDereferenceableBytes()
uint64_t llvm::AttrBuilder::getDereferenceableBytes () const inline
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
Definition at line 1172 of file Attributes.h.
References getRawIntAttr().
Referenced by AddParamAndFnBasicAttributes(), and AddReturnAttributes().
getDereferenceableOrNullBytes()
uint64_t llvm::AttrBuilder::getDereferenceableOrNullBytes () const inline
Retrieve the number of dereferenceable_or_null bytes, if the dereferenceable_or_null attribute exists (zero is returned otherwise).
Definition at line 1178 of file Attributes.h.
References getRawIntAttr().
Referenced by AddParamAndFnBasicAttributes(), and AddReturnAttributes().
getInAllocaType()
Type * llvm::AttrBuilder::getInAllocaType () const inline
Retrieve the inalloca type.
Definition at line 1207 of file Attributes.h.
References getTypeAttr().
Referenced by llvm::promoteCall().
getNoFPClass()
FPClassTest llvm::AttrBuilder::getNoFPClass () const inline
Retrieve the bitmask for nofpclass, if the nofpclass attribute exists (fcNone is returned otherwise).
Definition at line 1184 of file Attributes.h.
References getRawIntAttr().
Referenced by AddParamAndFnBasicAttributes().
getPreallocatedType()
Type * llvm::AttrBuilder::getPreallocatedType () const inline
Retrieve the preallocated type.
Definition at line 1202 of file Attributes.h.
References getTypeAttr().
getRange()
std::optional< ConstantRange > AttrBuilder::getRange () const
Retrieve the range if the attribute exists (std::nullopt is returned otherwise).
Definition at line 2381 of file Attributes.cpp.
References getAttribute(), llvm::Attribute::getRange(), and llvm::Attribute::isValid().
Referenced by AddParamAndFnBasicAttributes().
getRawIntAttr()
std::optional< uint64_t > AttrBuilder::getRawIntAttr (Attribute::AttrKind Kind) const
Return raw (possibly packed/encoded) value of integer attribute or std::nullopt if not set.
Definition at line 2164 of file Attributes.cpp.
References A(), assert(), getAttribute(), and llvm::Attribute::isIntAttrKind().
Referenced by getAlignment(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), getNoFPClass(), and getStackAlignment().
getStackAlignment()
MaybeAlign llvm::AttrBuilder::getStackAlignment () const inline
Retrieve the stack alignment attribute, if it exists.
Definition at line 1166 of file Attributes.h.
References getRawIntAttr().
getStructRetType()
Type * llvm::AttrBuilder::getStructRetType () const inline
Retrieve the sret type.
Definition at line 1196 of file Attributes.h.
References getTypeAttr().
getTypeAttr()
Type * AttrBuilder::getTypeAttr (Attribute::AttrKind Kind) const
Retrieve type for the given type attribute.
Definition at line 2265 of file Attributes.cpp.
References A(), assert(), getAttribute(), and llvm::Attribute::isTypeAttrKind().
Referenced by getByRefType(), getByValType(), getInAllocaType(), getPreallocatedType(), and getStructRetType().
hasAttributes()
bool llvm::AttrBuilder::hasAttributes () const inline
Return true if the builder has IR-level attributes.
Definition at line 1141 of file Attributes.h.
Referenced by AddReturnAttributes(), llvm::TargetLowering::isInTailCallPosition(), and isLibCallInTailPosition().
merge()
AttrBuilder & AttrBuilder::merge (const AttrBuilder & B)
Add the attributes from the builder.
Attributes in the passed builder overwrite attributes in this builder if they have the same key.
Definition at line 2349 of file Attributes.cpp.
References addAttribute(), AttrBuilder(), B(), and I.
Referenced by llvm::AttributeSet::addAttributes(), and mergeAttributes().
operator!=()
bool llvm::AttrBuilder::operator!= (const AttrBuilder & B) const inline
Definition at line 1323 of file Attributes.h.
References AttrBuilder(), and B().
operator==()
bool AttrBuilder::operator== (const AttrBuilder & B) const
Definition at line 2396 of file Attributes.cpp.
References AttrBuilder(), and B().
overlaps()
bool AttrBuilder::overlaps (const AttributeMask & AM) const
Return true if the builder has any attribute that's in the specified builder.
Definition at line 2362 of file Attributes.cpp.
References A(), llvm::any_of(), and llvm::AttributeMask::contains().
remove()
AttrBuilder & AttrBuilder::remove (const AttributeMask & AM)
Remove the attributes from the builder.
Definition at line 2357 of file Attributes.cpp.
References A(), AttrBuilder(), llvm::AttributeMask::contains(), and llvm::erase_if().
Referenced by llvm::promoteCall().
removeAttribute() [1/3]
AttrBuilder & llvm::AttrBuilder::removeAttribute (Attribute A) inline
Remove the target-dependent attribute from the builder.
Definition at line 1115 of file Attributes.h.
References A(), AttrBuilder(), and removeAttribute().
removeAttribute() [2/3]
AttrBuilder & AttrBuilder::removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
Definition at line 2148 of file Attributes.cpp.
References assert(), AttrBuilder(), llvm::Attribute::EndAttrKinds, and llvm::lower_bound().
Referenced by AddParamAndFnBasicAttributes(), AddReturnAttributes(), llvm::attributesPermitTailCall(), llvm::OpenMPIRBuilder::createReductionsGPU(), llvm::TargetLowering::isInTailCallPosition(), isLibCallInTailPosition(), legalizeCallAttributes(), and removeAttribute().
removeAttribute() [3/3]
AttrBuilder & AttrBuilder::removeAttribute (StringRef A)
Remove the target-dependent attribute from the builder.
Definition at line 2156 of file Attributes.cpp.
References A(), AttrBuilder(), and llvm::lower_bound().
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp