LLVM: llvm::sandboxir::RegionPassManager Class Reference
llvm::sandboxir::RegionPassManager Class Reference final
#include "llvm/SandboxIR/PassManager.h"
Public Member Functions
RegionPassManager (StringRef Name)
RegionPassManager (StringRef Name, StringRef Pipeline, CreatePassFunc CreatePass)
bool runOnRegion (Region &R, const Analyses &A) final
\Returns true if it modifies R.
Public Member Functions inherited from llvm::sandboxir::PassManager< RegionPass, RegionPass >
void addPass (std::unique_ptr< RegionPass > Pass)
Adds Pass to the pass pipeline.
void setPassPipeline (StringRef Pipeline, CreatePassFunc CreatePass)
Parses Pipeline as a comma-separated sequence of pass names and sets the pass pipeline, using CreatePass to instantiate passes by name.
void print (raw_ostream &OS) const override
LLVM_DUMP_METHOD void dump () const override
void printPipeline (raw_ostream &OS) const override
Similar to print() but prints one pass per line. Used for testing.
Public Member Functions inherited from llvm::sandboxir::RegionPass
RegionPass (StringRef Name)
Name can't contain any spaces or start with '-'.
Public Member Functions inherited from llvm::sandboxir::Pass
Pass (StringRef Name)
Name can't contain any spaces or start with '-'.
virtual ~Pass ()=default
StringRef getName () const
\Returns the name of the pass.
Additional Inherited Members
Public Types inherited from llvm::sandboxir::PassManager< RegionPass, RegionPass >
using CreatePassFunc
Static Public Attributes inherited from llvm::sandboxir::PassManager< RegionPass, RegionPass >
static constexpr char EndToken
static constexpr char BeginArgsToken
static constexpr char EndArgsToken
static constexpr char PassDelimToken
Protected Member Functions inherited from llvm::sandboxir::PassManager< RegionPass, RegionPass >
PassManager (StringRef Name)
~PassManager () override=default
PassManager & operator= (const PassManager &)=delete
Protected Attributes inherited from llvm::sandboxir::PassManager< RegionPass, RegionPass >
SmallVector< std::unique_ptr< RegionPass > > Passes
The list of passes that this pass manager will run.
Protected Attributes inherited from llvm::sandboxir::Pass
const std::string Name
The pass name.
Detailed Description
Definition at line 215 of file PassManager.h.
Constructor & Destructor Documentation
RegionPassManager() [1/2]
llvm::sandboxir::RegionPassManager::RegionPassManager (StringRef Name) inline
Definition at line 218 of file PassManager.h.
References llvm::sandboxir::Pass::Name, and llvm::sandboxir::PassManager< RegionPass, RegionPass >::PassManager().
RegionPassManager() [2/2]
llvm::sandboxir::RegionPassManager::RegionPassManager (StringRef Name, StringRef Pipeline, CreatePassFunc CreatePass) inline
Definition at line 219 of file PassManager.h.
References llvm::sandboxir::Pass::Name, and llvm::sandboxir::PassManager< RegionPass, RegionPass >::PassManager().
Member Function Documentation
runOnRegion()
bool llvm::sandboxir::RegionPassManager::runOnRegion (Region & R, const Analyses & A) final virtual
\Returns true if it modifies R.
Implements llvm::sandboxir::RegionPass.
Definition at line 23 of file PassManager.cpp.
References A().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/PassManager.h
lib/SandboxIR/PassManager.cpp