LLVM: llvm::abi::PointerLikeType Class Reference
llvm::abi::PointerLikeType Class Reference
#include "llvm/ABI/Types.h"
Public Member Functions
unsigned getAddrSpace () const
bool isMemberPointer () const
Public Member Functions inherited from llvm::abi::Type
TypeKind getKind () const
TypeSize getSizeInBits () const
Align getAlignment () const
TypeSize getTypeAllocSize () const
bool isVoid () const
bool isInteger () const
bool isFloat () const
bool isPointer () const
bool isArray () const
bool isVector () const
bool isRecord () const
bool isMemberPointer () const
bool isComplex () const
Static Public Member Functions
static bool classof (const Type *T)
Protected Member Functions
PointerLikeType (TypeKind K, TypeSize SizeInBits, Align ABIAlign, unsigned AS)
Protected Member Functions inherited from llvm::abi::Type
Type (TypeKind K, TypeSize SizeInBits, Align ABIAlign)
Protected Attributes
unsigned AddrSpace
Protected Attributes inherited from llvm::abi::Type
TypeKind Kind
TypeSize SizeInBits
Align ABIAlignment
Detailed Description
Definition at line 147 of file Types.h.
Constructor & Destructor Documentation
PointerLikeType()
llvm::abi::PointerLikeType::PointerLikeType (TypeKind K, TypeSize SizeInBits, Align ABIAlign, unsigned AS) inline protected
Definition at line 150 of file Types.h.
References AddrSpace, llvm::abi::Type::SizeInBits, and llvm::abi::Type::Type().
Referenced by llvm::abi::MemberPointerType::MemberPointerType(), and llvm::abi::PointerType::PointerType().
Member Function Documentation
classof()
bool llvm::abi::PointerLikeType::classof (const Type * T) inline static
Definition at line 157 of file Types.h.
References llvm::abi::MemberPointer, llvm::abi::Pointer, T, and llvm::abi::Type::Type().
getAddrSpace()
unsigned llvm::abi::PointerLikeType::getAddrSpace () const inline
Definition at line 154 of file Types.h.
References AddrSpace.
isMemberPointer()
bool llvm::abi::PointerLikeType::isMemberPointer () const inline
Definition at line 155 of file Types.h.
References llvm::abi::Type::getKind(), and llvm::abi::MemberPointer.
Member Data Documentation
AddrSpace
unsigned llvm::abi::PointerLikeType::AddrSpace protected
Definition at line 149 of file Types.h.
Referenced by getAddrSpace(), and PointerLikeType().
The documentation for this class was generated from the following file:
include/llvm/ABI/Types.h