LLVM: llvm::json::ObjectKey Class Reference
llvm::json::ObjectKey Class Reference
ObjectKey is a used to capture keys in Object.
#include "llvm/Support/JSON.h"
Public Member Functions
ObjectKey (const char *S)
ObjectKey (std::string S)
ObjectKey (llvm::StringRef S)
ObjectKey (const llvm::SmallVectorImpl< char > &V)
ObjectKey (const llvm::formatv_object_base &V)
ObjectKey (const ObjectKey &C)
ObjectKey (ObjectKey &&C)
ObjectKey & operator= (const ObjectKey &C)
ObjectKey & operator= (ObjectKey &&)=default
operator llvm::StringRef () const
std::string str () const
Detailed Description
ObjectKey is a used to capture keys in Object.
Like Value but:
only strings are allowed
it's optimized for the string literal case (Owned == nullptr) Like Value, strings must be UTF-8. See isUTF8 documentation for details.
Definition at line 587 of file JSON.h.
Constructor & Destructor Documentation
ObjectKey() [1/7]
llvm::json::ObjectKey::ObjectKey (const char * S) inline
Definition at line 589 of file JSON.h.
References ObjectKey(), and operator llvm::StringRef().
Referenced by ObjectKey(), ObjectKey(), ObjectKey(), ObjectKey(), ObjectKey(), ObjectKey(), operator=(), and operator=().
ObjectKey() [2/7]
llvm::json::ObjectKey::ObjectKey (std::string S) inline
Definition at line 590 of file JSON.h.
References assert(), llvm::json::fixUTF8(), llvm::json::isUTF8(), LLVM_UNLIKELY, and llvm::move().
ObjectKey() [3/7]
llvm::json::ObjectKey::ObjectKey (llvm::StringRef S) inline
Definition at line 597 of file JSON.h.
References assert(), llvm::json::fixUTF8(), llvm::json::isUTF8(), LLVM_UNLIKELY, and ObjectKey().
ObjectKey() [4/7]
llvm::json::ObjectKey::ObjectKey (const llvm::SmallVectorImpl< char > & V) inline
Definition at line 603 of file JSON.h.
References llvm::begin(), llvm::end(), and ObjectKey().
ObjectKey() [5/7]
llvm::json::ObjectKey::ObjectKey (const llvm::formatv_object_base & V) inline
Definition at line 605 of file JSON.h.
References ObjectKey(), and str().
ObjectKey() [6/7]
llvm::json::ObjectKey::ObjectKey (const ObjectKey & C) inline
Definition at line 607 of file JSON.h.
References llvm::CallingConv::C, and ObjectKey().
ObjectKey() [7/7]
llvm::json::ObjectKey::ObjectKey (ObjectKey && C) inline
Definition at line 608 of file JSON.h.
References llvm::CallingConv::C, const, and ObjectKey().
Member Function Documentation
operator llvm::StringRef()
llvm::json::ObjectKey::operator llvm::StringRef () const inline
Definition at line 620 of file JSON.h.
Referenced by ObjectKey().
operator=() [1/2]
ObjectKey & llvm::json::ObjectKey::operator= (const ObjectKey & C) inline
Definition at line 609 of file JSON.h.
References llvm::CallingConv::C, and ObjectKey().
operator=() [2/2]
ObjectKey & llvm::json::ObjectKey::operator= (ObjectKey &&) default
References ObjectKey().
str()
std::string llvm::json::ObjectKey::str () const inline
Definition at line 621 of file JSON.h.
Referenced by ObjectKey().
The documentation for this class was generated from the following file:
include/llvm/Support/JSON.h