LLVM: llvm::MemIntrinsicCostAttributes Class Reference
llvm::MemIntrinsicCostAttributes Class Reference
Information for memory intrinsic cost model.
#include "llvm/Analysis/TargetTransformInfo.h"
Public Member Functions
LLVM_ABI MemIntrinsicCostAttributes (Intrinsic::ID Id, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, const Instruction *I=nullptr)
LLVM_ABI MemIntrinsicCostAttributes (Intrinsic::ID Id, Type *DataTy, Align Alignment, unsigned AddressSpace=0)
LLVM_ABI MemIntrinsicCostAttributes (Intrinsic::ID Id, Type *DataTy, bool VariableMask, Align Alignment, const Instruction *I=nullptr)
Intrinsic::ID getID () const
const Instruction * getInst () const
const Value * getPointer () const
Type * getDataType () const
bool getVariableMask () const
unsigned getAddressSpace () const
Align getAlignment () const
Detailed Description
Information for memory intrinsic cost model.
Definition at line 128 of file TargetTransformInfo.h.
Constructor & Destructor Documentation
MemIntrinsicCostAttributes() [1/3]
LLVM_ABI llvm::MemIntrinsicCostAttributes::MemIntrinsicCostAttributes (Intrinsic::ID Id, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, const Instruction * I = nullptr) inline
Definition at line 153 of file TargetTransformInfo.h.
References LLVM_ABI.
MemIntrinsicCostAttributes() [2/3]
LLVM_ABI llvm::MemIntrinsicCostAttributes::MemIntrinsicCostAttributes (Intrinsic::ID Id, Type * DataTy, Align Alignment, unsigned AddressSpace = 0) inline
Definition at line 160 of file TargetTransformInfo.h.
References LLVM_ABI.
MemIntrinsicCostAttributes() [3/3]
LLVM_ABI llvm::MemIntrinsicCostAttributes::MemIntrinsicCostAttributes (Intrinsic::ID Id, Type * DataTy, bool VariableMask, Align Alignment, const Instruction * I = nullptr) inline
Definition at line 166 of file TargetTransformInfo.h.
References LLVM_ABI.
Member Function Documentation
getAddressSpace()
unsigned llvm::MemIntrinsicCostAttributes::getAddressSpace () const inline
Definition at line 177 of file TargetTransformInfo.h.
Referenced by llvm::ARMTTIImpl::getMaskedMemoryOpCost(), llvm::RISCVTTIImpl::getMaskedMemoryOpCost(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), and llvm::RISCVTTIImpl::getMemIntrinsicInstrCost().
getAlignment()
Align llvm::MemIntrinsicCostAttributes::getAlignment () const inline
Definition at line 178 of file TargetTransformInfo.h.
Referenced by llvm::RISCVTTIImpl::getExpandCompressMemoryOpCost(), llvm::AArch64TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::RISCVTTIImpl::getGatherScatterOpCost(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getMaskedMemoryOpCost(), llvm::RISCVTTIImpl::getMaskedMemoryOpCost(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getMemIntrinsicInstrCost(), llvm::RISCVTTIImpl::getMemIntrinsicInstrCost(), and llvm::RISCVTTIImpl::getStridedMemoryOpCost().
getDataType()
Type * llvm::MemIntrinsicCostAttributes::getDataType () const inline
Definition at line 175 of file TargetTransformInfo.h.
Referenced by llvm::RISCVTTIImpl::getExpandCompressMemoryOpCost(), llvm::AArch64TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::RISCVTTIImpl::getGatherScatterOpCost(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::AArch64TTIImpl::getMaskedMemoryOpCost(), llvm::ARMTTIImpl::getMaskedMemoryOpCost(), llvm::RISCVTTIImpl::getMaskedMemoryOpCost(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getMemIntrinsicInstrCost(), llvm::RISCVTTIImpl::getMemIntrinsicInstrCost(), and llvm::RISCVTTIImpl::getStridedMemoryOpCost().
getID()
Intrinsic::ID llvm::MemIntrinsicCostAttributes::getID () const inline
Definition at line 172 of file TargetTransformInfo.h.
Referenced by llvm::RISCVTTIImpl::getExpandCompressMemoryOpCost(), llvm::AArch64TTIImpl::getGatherScatterOpCost(), llvm::RISCVTTIImpl::getGatherScatterOpCost(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getMaskedMemoryOpCost(), llvm::RISCVTTIImpl::getMaskedMemoryOpCost(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::AArch64TTIImpl::getMemIntrinsicInstrCost(), llvm::ARMTTIImpl::getMemIntrinsicInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getMemIntrinsicInstrCost(), llvm::RISCVTTIImpl::getMemIntrinsicInstrCost(), llvm::TargetTransformInfoImplBase::getMemIntrinsicInstrCost(), llvm::X86TTIImpl::getMemIntrinsicInstrCost(), and llvm::RISCVTTIImpl::getStridedMemoryOpCost().
getInst()
const Instruction * llvm::MemIntrinsicCostAttributes::getInst () const inline
Definition at line 173 of file TargetTransformInfo.h.
Referenced by llvm::AArch64TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), and llvm::RISCVTTIImpl::getStridedMemoryOpCost().
getPointer()
const Value * llvm::MemIntrinsicCostAttributes::getPointer () const inline
Definition at line 174 of file TargetTransformInfo.h.
Referenced by llvm::ARMTTIImpl::getGatherScatterOpCost(), and llvm::X86TTIImpl::getGatherScatterOpCost().
getVariableMask()
bool llvm::MemIntrinsicCostAttributes::getVariableMask () const inline
Definition at line 176 of file TargetTransformInfo.h.
Referenced by llvm::RISCVTTIImpl::getExpandCompressMemoryOpCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), and llvm::BasicTTIImplBase< BasicTTIImpl >::getMemIntrinsicInstrCost().
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetTransformInfo.h