LLVM: llvm::GVNExpression::ConstantExpression Class Reference
llvm::GVNExpression::ConstantExpression Class Reference final
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Member Functions
ConstantExpression ()
ConstantExpression (Constant *constantValue)
ConstantExpression (const ConstantExpression &)=delete
ConstantExpression & operator= (const ConstantExpression &)=delete
Constant * getConstantValue () const
void setConstantValue (Constant *V)
bool equals (const Expression &Other) const override
hash_code getHashValue () const override
void printInternal (raw_ostream &OS, bool PrintEType) const override
Public Member Functions inherited from llvm::GVNExpression::Expression
Expression (ExpressionType ET=ET_Base, unsigned O=~2U)
Expression (const Expression &)=delete
Expression & operator= (const Expression &)=delete
virtual ~Expression ()
bool operator!= (const Expression &Other) const
bool operator== (const Expression &Other) const
hash_code getComputedHash () const
virtual bool exactlyEquals (const Expression &Other) const
unsigned getOpcode () const
void setOpcode (unsigned opcode)
ExpressionType getExpressionType () const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::Expression
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
Detailed Description
Definition at line 594 of file GVNExpression.h.
Constructor & Destructor Documentation
ConstantExpression() [1/3]
llvm::GVNExpression::ConstantExpression::ConstantExpression () inline
Definition at line 599 of file GVNExpression.h.
References llvm::GVNExpression::ET_Constant, and llvm::GVNExpression::Expression::Expression().
Referenced by ConstantExpression(), equals(), and operator=().
ConstantExpression() [2/3]
llvm::GVNExpression::ConstantExpression::ConstantExpression (Constant * constantValue) inline
Definition at line 600 of file GVNExpression.h.
References llvm::GVNExpression::ET_Constant, and llvm::GVNExpression::Expression::Expression().
ConstantExpression() [3/3]
llvm::GVNExpression::ConstantExpression::ConstantExpression (const ConstantExpression &) delete
References ConstantExpression().
Member Function Documentation
classof()
bool llvm::GVNExpression::ConstantExpression::classof (const Expression * EB) inline static
Definition at line 605 of file GVNExpression.h.
References llvm::GVNExpression::ET_Constant, llvm::GVNExpression::Expression::Expression(), and llvm::GVNExpression::Expression::getExpressionType().
equals()
bool llvm::GVNExpression::ConstantExpression::equals (const Expression & Other) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 612 of file GVNExpression.h.
References llvm::cast(), ConstantExpression(), llvm::GVNExpression::Expression::Expression(), and llvm::Other.
getConstantValue()
Constant * llvm::GVNExpression::ConstantExpression::getConstantValue () const inline
Definition at line 609 of file GVNExpression.h.
getHashValue()
hash_code llvm::GVNExpression::ConstantExpression::getHashValue () const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 617 of file GVNExpression.h.
References llvm::GVNExpression::Expression::getHashValue(), and llvm::hash_combine().
operator=()
ConstantExpression & llvm::GVNExpression::ConstantExpression::operator= (const ConstantExpression &) delete
References ConstantExpression().
printInternal()
void llvm::GVNExpression::ConstantExpression::printInternal (raw_ostream & OS, bool PrintEType) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 623 of file GVNExpression.h.
References llvm::GVNExpression::Expression::printInternal().
setConstantValue()
void llvm::GVNExpression::ConstantExpression::setConstantValue (Constant * V) inline
Definition at line 610 of file GVNExpression.h.
The documentation for this class was generated from the following file:
include/llvm/Transforms/Scalar/GVNExpression.h