LLVM: llvm::objcopy::elf::ELFSectionSizer< ELFT > Class Template Reference
llvm::objcopy::elf::ELFSectionSizer< ELFT > Class Template Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
Error visit (Section &Sec) override
Error visit (OwnedDataSection &Sec) override
Error visit (StringTableSection &Sec) override
Error visit (DynamicRelocationSection &Sec) override
Error visit (SymbolTableSection &Sec) override
Error visit (RelocationSection &Sec) override
Error visit (GnuDebugLinkSection &Sec) override
Error visit (GroupSection &Sec) override
Error visit (SectionIndexSection &Sec) override
Error visit (CompressedSection &Sec) override
Error visit (DecompressedSection &Sec) override
Public Member Functions inherited from llvm::objcopy::elf::MutableSectionVisitor
virtual ~MutableSectionVisitor ()=default
Detailed Description
template<class ELFT>
class llvm::objcopy::elf::ELFSectionSizer< ELFT >
Definition at line 149 of file ELFObject.h.
Member Function Documentation
visit() [1/11]
template<class ELFT> Error ELFSectionSizer::visit (CompressedSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 149 of file ELFObject.cpp.
References llvm::Error::success().
visit() [2/11]
template<class ELFT> Error ELFSectionSizer::visit (DecompressedSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 154 of file ELFObject.cpp.
References llvm::Error::success().
visit() [3/11]
template<class ELFT> Error ELFSectionSizer::visit (DynamicRelocationSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 95 of file ELFObject.cpp.
References llvm::Error::success().
visit() [4/11]
template<class ELFT> Error ELFSectionSizer::visit (GnuDebugLinkSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 135 of file ELFObject.cpp.
References llvm::Error::success().
visit() [5/11]
template<class ELFT> Error ELFSectionSizer::visit (GroupSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 139 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Size, and llvm::Error::success().
visit() [6/11]
template<class ELFT> Error ELFSectionSizer::visit (OwnedDataSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 86 of file ELFObject.cpp.
References llvm::Error::success().
visit() [7/11]
template<class ELFT> Error ELFSectionSizer::visit (RelocationSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 122 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Align, llvm::ELF::encodeCrel(), llvm::objcopy::elf::SectionBase::EntrySize, llvm::ELF::SHT_CREL, llvm::ELF::SHT_REL, llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), and llvm::objcopy::elf::SectionBase::Type.
visit() [8/11]
template<class ELFT> Error ELFSectionSizer::visit (Section & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 82 of file ELFObject.cpp.
References llvm::Error::success().
visit() [9/11]
template<class ELFT> Error ELFSectionSizer::visit (SectionIndexSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 145 of file ELFObject.cpp.
References llvm::Error::success().
visit() [10/11]
template<class ELFT> Error ELFSectionSizer::visit (StringTableSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 90 of file ELFObject.cpp.
References llvm::Error::success().
visit() [11/11]
template<class ELFT> Error ELFSectionSizer::visit (SymbolTableSection & Sec) override virtual
Implements llvm::objcopy::elf::MutableSectionVisitor.
Definition at line 100 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Align, llvm::objcopy::elf::SectionBase::EntrySize, llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), and llvm::objcopy::elf::SymbolTableSection::Symbols.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp