LLVM: llvm::ARCFunctionInfo Class Reference
llvm::ARCFunctionInfo Class Reference
ARCFunctionInfo - This class is derived from MachineFunction private ARC target-specific information for each MachineFunction.
#include "Target/ARC/ARCMachineFunctionInfo.h"
Public Member Functions
ARCFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
~ARCFunctionInfo ()
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
void setVarArgsFrameIndex (int off)
int getVarArgsFrameIndex () const
void setReturnStackOffset (unsigned value)
unsigned getReturnStackOffset () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Public Attributes
unsigned MaxCallStackReq
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy, typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
ARCFunctionInfo - This class is derived from MachineFunction private ARC target-specific information for each MachineFunction.
Definition at line 22 of file ARCMachineFunctionInfo.h.
Constructor & Destructor Documentation
ARCFunctionInfo()
llvm::ARCFunctionInfo::ARCFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline explicit
Definition at line 29 of file ARCMachineFunctionInfo.h.
References F, and MaxCallStackReq.
Referenced by clone().
~ARCFunctionInfo()
llvm::ARCFunctionInfo::~ARCFunctionInfo () inline
Definition at line 32 of file ARCMachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * ARCFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 16 of file ARCMachineFunctionInfo.cpp.
References ARCFunctionInfo(), and llvm::MachineFunction::cloneInfo().
getReturnStackOffset()
unsigned llvm::ARCFunctionInfo::getReturnStackOffset () const inline
Definition at line 48 of file ARCMachineFunctionInfo.h.
References assert().
getVarArgsFrameIndex()
int llvm::ARCFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 40 of file ARCMachineFunctionInfo.h.
setReturnStackOffset()
void llvm::ARCFunctionInfo::setReturnStackOffset (unsigned value) inline
Definition at line 42 of file ARCMachineFunctionInfo.h.
References assert().
setVarArgsFrameIndex()
void llvm::ARCFunctionInfo::setVarArgsFrameIndex (int off) inline
Definition at line 39 of file ARCMachineFunctionInfo.h.
Member Data Documentation
MaxCallStackReq
unsigned llvm::ARCFunctionInfo::MaxCallStackReq
Definition at line 53 of file ARCMachineFunctionInfo.h.
Referenced by ARCFunctionInfo().
The documentation for this class was generated from the following files:
lib/Target/ARC/ARCMachineFunctionInfo.h
lib/Target/ARC/ARCMachineFunctionInfo.cpp