LLVM: llvm::codeview::FileStaticSym Class Reference
llvm::codeview::FileStaticSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
FileStaticSym (SymbolRecordKind Kind)
FileStaticSym (uint32_t RecordOffset)
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
TypeIndex Index
uint32_t ModFilenameOffset = 0
LocalSymFlags Flags = LocalSymFlags::None
StringRef Name
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 719 of file SymbolRecord.h.
Constructor & Destructor Documentation
FileStaticSym() [1/2]
llvm::codeview::FileStaticSym::FileStaticSym (SymbolRecordKind Kind) inline explicit
Definition at line 721 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by FileStaticSym().
FileStaticSym() [2/2]
llvm::codeview::FileStaticSym::FileStaticSym (uint32_t RecordOffset) inline explicit
Definition at line 722 of file SymbolRecord.h.
References FileStaticSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Data Documentation
Flags
LocalSymFlags llvm::codeview::FileStaticSym::Flags = LocalSymFlags::None
Definition at line 728 of file SymbolRecord.h.
Index
TypeIndex llvm::codeview::FileStaticSym::Index
Definition at line 726 of file SymbolRecord.h.
ModFilenameOffset
uint32_t llvm::codeview::FileStaticSym::ModFilenameOffset = 0
Definition at line 727 of file SymbolRecord.h.
Name
StringRef llvm::codeview::FileStaticSym::Name
Definition at line 729 of file SymbolRecord.h.
RecordOffset
uint32_t llvm::codeview::FileStaticSym::RecordOffset = 0
Definition at line 731 of file SymbolRecord.h.
Referenced by FileStaticSym().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h