LLVM: llvm::mustache::ASTNode Class Reference
llvm::mustache::ASTNode Class Reference
Public Types
enum Type {
Root , Text , Partial , Variable ,
UnescapeVariable , Section , InvertSection
}
Public Member Functions
ASTNode (MustacheContext &Ctx)
ASTNode (MustacheContext &Ctx, StringRef Body, ASTNode *Parent)
ASTNode (MustacheContext &Ctx, Type Ty, ArrayRef< StringRef > Accessor, ASTNode *Parent)
void addChild (AstPtr Child)
void setRawBody (StringRef NewBody)
void setIndentation (size_t NewIndentation)
void render (const llvm::json::Value &Data, MustacheOutputStream &OS)
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< ASTNode, Options... >::type >
self_iterator getIterator ()
reverse_self_iterator getReverseIterator ()
std::enable_if_t< T::is_sentinel_tracking_explicit, bool > isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< ASTNode, Options... >::type >, ilist_detail::compute_node_options< ASTNode, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< ASTNode, Options... >::type::parent_ty * getParent () const
void setParent (ilist_detail::compute_node_options< ASTNode, Options... >::type::parent_ty *Parent)
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< ASTNode, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< ASTNode, Options... >::type >
ilist_node_impl ()=default
Detailed Description
Definition at line 183 of file Mustache.cpp.
Member Enumeration Documentation
Type
enum llvm::mustache::ASTNode::Type
Enumerator
Root
Text
Partial
Variable
UnescapeVariable
Section
InvertSection
Definition at line 185 of file Mustache.cpp.
Constructor & Destructor Documentation
ASTNode() [1/3]
llvm::mustache::ASTNode::ASTNode (MustacheContext & Ctx) inline
Definition at line 195 of file Mustache.cpp.
References nullptr, and Root.
Referenced by ASTNode(), and ASTNode().
ASTNode() [2/3]
llvm::mustache::ASTNode::ASTNode (MustacheContext & Ctx, StringRef Body, ASTNode * Parent) inline
Definition at line 198 of file Mustache.cpp.
References ASTNode(), nullptr, and Text.
ASTNode() [3/3]
llvm::mustache::ASTNode::ASTNode (MustacheContext & Ctx, Type Ty, ArrayRef< StringRef > Accessor, ASTNode * Parent) inline
Definition at line 203 of file Mustache.cpp.
References ASTNode(), and nullptr.
Member Function Documentation
addChild()
void llvm::mustache::ASTNode::addChild (AstPtr Child) inline
Definition at line 208 of file Mustache.cpp.
render()
void llvm::mustache::ASTNode::render (const llvm::json::Value & Data, MustacheOutputStream & OS)
Definition at line 773 of file Mustache.cpp.
References llvm::Data, InvertSection, llvm_unreachable, Partial, Root, Section, Text, UnescapeVariable, and Variable.
setIndentation()
void llvm::mustache::ASTNode::setIndentation (size_t NewIndentation) inline
Definition at line 212 of file Mustache.cpp.
setRawBody()
void llvm::mustache::ASTNode::setRawBody (StringRef NewBody) inline
Definition at line 210 of file Mustache.cpp.
The documentation for this class was generated from the following file:
lib/Support/Mustache.cpp