LLVM: llvm::CFIFunctionFrameReceiver Class Reference
llvm::CFIFunctionFrameReceiver Class Reference
This abstract base class is an interface for receiving DWARF function frames Call Frame Information.
#include "llvm/DWARFCFIChecker/DWARFCFIFunctionFrameReceiver.h"
Public Member Functions
CFIFunctionFrameReceiver (const CFIFunctionFrameReceiver &)=delete
CFIFunctionFrameReceiver & operator= (const CFIFunctionFrameReceiver &)=delete
virtual ~CFIFunctionFrameReceiver ()=default
CFIFunctionFrameReceiver (MCContext &Context)
MCContext & getContext () const
virtual void startFunctionFrame (bool IsEH, ArrayRef< MCCFIInstruction > Prologue)
virtual void emitInstructionAndDirectives (const MCInst &Inst, ArrayRef< MCCFIInstruction > Directives)
Instructions are processed in the program order.
virtual void finishFunctionFrame ()
Detailed Description
This abstract base class is an interface for receiving DWARF function frames Call Frame Information.
DWARFCFIFunctionFrameStreamer channels the function frames information gathered from an MCStreamer using a pointer to an instance of this class for the whole program.
Definition at line 29 of file DWARFCFIFunctionFrameReceiver.h.
Constructor & Destructor Documentation
CFIFunctionFrameReceiver() [1/2]
llvm::CFIFunctionFrameReceiver::CFIFunctionFrameReceiver (const CFIFunctionFrameReceiver &) delete
References CFIFunctionFrameReceiver().
Referenced by llvm::CFIFunctionFrameAnalyzer::CFIFunctionFrameAnalyzer(), CFIFunctionFrameReceiver(), and operator=().
~CFIFunctionFrameReceiver()
virtual llvm::CFIFunctionFrameReceiver::~CFIFunctionFrameReceiver () virtual default
CFIFunctionFrameReceiver() [2/2]
llvm::CFIFunctionFrameReceiver::CFIFunctionFrameReceiver (MCContext & Context) inline
Definition at line 36 of file DWARFCFIFunctionFrameReceiver.h.
Member Function Documentation
emitInstructionAndDirectives()
virtual void llvm::CFIFunctionFrameReceiver::emitInstructionAndDirectives (const MCInst & Inst, ArrayRef< MCCFIInstruction > Directives) inline virtual
Instructions are processed in the program order.
Reimplemented in llvm::CFIFunctionFrameAnalyzer.
Definition at line 44 of file DWARFCFIFunctionFrameReceiver.h.
finishFunctionFrame()
virtual void llvm::CFIFunctionFrameReceiver::finishFunctionFrame () inline virtual
Reimplemented in llvm::CFIFunctionFrameAnalyzer.
Definition at line 46 of file DWARFCFIFunctionFrameReceiver.h.
getContext()
MCContext & llvm::CFIFunctionFrameReceiver::getContext () const inline
Definition at line 38 of file DWARFCFIFunctionFrameReceiver.h.
Referenced by llvm::CFIFunctionFrameAnalyzer::startFunctionFrame().
operator=()
CFIFunctionFrameReceiver & llvm::CFIFunctionFrameReceiver::operator= (const CFIFunctionFrameReceiver &) delete
References CFIFunctionFrameReceiver().
startFunctionFrame()
virtual void llvm::CFIFunctionFrameReceiver::startFunctionFrame (bool IsEH, ArrayRef< MCCFIInstruction > Prologue) inline virtual
Reimplemented in llvm::CFIFunctionFrameAnalyzer.
Definition at line 40 of file DWARFCFIFunctionFrameReceiver.h.
The documentation for this class was generated from the following file:
include/llvm/DWARFCFIChecker/DWARFCFIFunctionFrameReceiver.h