LLVM: llvm::sandboxir::FixedVectorType Class Reference
llvm::sandboxir::FixedVectorType Class Reference
#include "llvm/SandboxIR/Type.h"
Public Member Functions
unsigned getNumElements () const
Public Member Functions inherited from llvm::sandboxir::VectorType
LLVM_ABI Type * getElementType () const
ElementCount getElementCount () const
Public Member Functions inherited from llvm::sandboxir::Type
void print (raw_ostream &OS, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
Context & getContext () const
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isBFloatTy () const
Return true if this is 'bfloat', a 16-bit bfloat type.
bool is16bitFPTy () const
Return true if this is a 16-bit float type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isIEEELikeFPTy () const
Return true if this is a well-behaved IEEE-like type, which has a IEEE compatible layout, and does not have non-IEEE values, such as x86_fp80's unnormal values.
bool isFloatingPointTy () const
Return true if this is one of the floating-point types.
bool isMultiUnitFPType () const
Returns true if this is a floating-point type that is an unevaluated sum of multiple floating-point units.
const fltSemantics & getFltSemantics () const
bool isX86_AMXTy () const
Return true if this is X86 AMX.
bool isTargetExtTy () const
Return true if this is a target extension type.
bool isScalableTargetExtTy () const
Return true if this is a target extension type with a scalable layout.
bool isScalableTy () const
Return true if this is a type whose size is a known multiple of vscale.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
LLVM_ABI Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
void dumpOS (raw_ostream &OS)
LLVM_DUMP_METHOD void dump ()
Static Public Member Functions
static LLVM_ABI FixedVectorType * get (Type *ElementType, unsigned NumElts)
static FixedVectorType * get (Type *ElementType, const FixedVectorType *FVTy)
static FixedVectorType * getInteger (FixedVectorType *VTy)
static FixedVectorType * getExtendedElementVectorType (FixedVectorType *VTy)
static FixedVectorType * getTruncatedElementVectorType (FixedVectorType *VTy)
static FixedVectorType * getSubdividedVectorType (FixedVectorType *VTy, int NumSubdivs)
static FixedVectorType * getHalfElementsVectorType (FixedVectorType *VTy)
static FixedVectorType * getDoubleElementsVectorType (FixedVectorType *VTy)
static bool classof (const Type *T)
Static Public Member Functions inherited from llvm::sandboxir::VectorType
static LLVM_ABI VectorType * get (Type *ElementType, ElementCount EC)
static VectorType * get (Type *ElementType, unsigned NumElements, bool Scalable)
static VectorType * get (Type *ElementType, const VectorType *Other)
static LLVM_ABI VectorType * getInteger (VectorType *VTy)
static LLVM_ABI VectorType * getExtendedElementVectorType (VectorType *VTy)
static LLVM_ABI VectorType * getTruncatedElementVectorType (VectorType *VTy)
static LLVM_ABI VectorType * getSubdividedVectorType (VectorType *VTy, int NumSubdivs)
static LLVM_ABI VectorType * getHalfElementsVectorType (VectorType *VTy)
static LLVM_ABI VectorType * getDoubleElementsVectorType (VectorType *VTy)
static LLVM_ABI bool isValidElementType (Type *ElemTy)
static bool classof (const Type *From)
Static Public Member Functions inherited from llvm::sandboxir::Type
static LLVM_ABI IntegerType * getInt64Ty (Context &Ctx)
static LLVM_ABI IntegerType * getInt32Ty (Context &Ctx)
static LLVM_ABI IntegerType * getInt16Ty (Context &Ctx)
static LLVM_ABI IntegerType * getInt8Ty (Context &Ctx)
static LLVM_ABI IntegerType * getInt1Ty (Context &Ctx)
static LLVM_ABI Type * getDoubleTy (Context &Ctx)
static LLVM_ABI Type * getFloatTy (Context &Ctx)
static LLVM_ABI Type * getHalfTy (Context &Ctx)
Additional Inherited Members
Protected Member Functions inherited from llvm::sandboxir::Type
Type (llvm::Type *LLVMTy, Context &Ctx)
~Type ()=default
Protected Attributes inherited from llvm::sandboxir::Type
llvm::Type * LLVMTy
Context & Ctx
Detailed Description
Definition at line 358 of file Type.h.
Member Function Documentation
classof()
bool llvm::sandboxir::FixedVectorType::classof (const Type * T) inline static
Definition at line 393 of file Type.h.
References llvm::isa(), and T.
get() [1/2]
FixedVectorType * llvm::sandboxir::FixedVectorType::get (Type * ElementType, const FixedVectorType * FVTy) inline static
Definition at line 362 of file Type.h.
References llvm::sandboxir::get(), and getNumElements().
get() [2/2]
LLVM_ABI FixedVectorType * llvm::sandboxir::FixedVectorType::get (Type * ElementType, unsigned NumElts) static
References LLVM_ABI.
Referenced by llvm::sandboxir::VecUtils::getWideType().
getDoubleElementsVectorType()
FixedVectorType * llvm::sandboxir::FixedVectorType::getDoubleElementsVectorType (FixedVectorType * VTy) inline static
Definition at line 389 of file Type.h.
References llvm::cast(), and llvm::sandboxir::VectorType::getDoubleElementsVectorType().
getExtendedElementVectorType()
FixedVectorType * llvm::sandboxir::FixedVectorType::getExtendedElementVectorType (FixedVectorType * VTy) inline static
Definition at line 370 of file Type.h.
References llvm::cast(), and llvm::sandboxir::VectorType::getExtendedElementVectorType().
getHalfElementsVectorType()
FixedVectorType * llvm::sandboxir::FixedVectorType::getHalfElementsVectorType (FixedVectorType * VTy) inline static
Definition at line 385 of file Type.h.
References llvm::cast(), and llvm::sandboxir::VectorType::getHalfElementsVectorType().
getInteger()
FixedVectorType * llvm::sandboxir::FixedVectorType::getInteger (FixedVectorType * VTy) inline static
Definition at line 366 of file Type.h.
References llvm::cast(), and llvm::sandboxir::VectorType::getInteger().
getNumElements()
unsigned llvm::sandboxir::FixedVectorType::getNumElements () const inline
Definition at line 397 of file Type.h.
References llvm::cast(), and llvm::sandboxir::Type::LLVMTy.
Referenced by get().
getSubdividedVectorType()
FixedVectorType * llvm::sandboxir::FixedVectorType::getSubdividedVectorType (FixedVectorType * VTy, int NumSubdivs) inline static
Definition at line 379 of file Type.h.
References llvm::cast(), and llvm::sandboxir::VectorType::getSubdividedVectorType().
getTruncatedElementVectorType()
FixedVectorType * llvm::sandboxir::FixedVectorType::getTruncatedElementVectorType (FixedVectorType * VTy) inline static
Definition at line 374 of file Type.h.
References llvm::cast(), and llvm::sandboxir::VectorType::getTruncatedElementVectorType().
The documentation for this class was generated from the following file:
include/llvm/SandboxIR/Type.h