LLVM: llvm::objcopy::coff::COFFReader Class Reference
llvm::objcopy::coff::COFFReader Class Reference
#include "ObjCopy/COFF/COFFReader.h"
Public Member Functions
COFFReader (const COFFObjectFile &O)
Expected< std::unique_ptr< Object > > create () const
Detailed Description
Definition at line 24 of file COFFReader.h.
Constructor & Destructor Documentation
COFFReader()
llvm::objcopy::coff::COFFReader::COFFReader (const COFFObjectFile & O) inline explicit
Definition at line 33 of file COFFReader.h.
Member Function Documentation
create()
Expected< std::unique_ptr< Object > > llvm::objcopy::coff::COFFReader::create () const
Definition at line 193 of file COFFReader.cpp.
References llvm::createStringError(), E(), llvm::object::coff_bigobj_file_header::Machine, and llvm::object::coff_bigobj_file_header::TimeDateStamp.
Referenced by llvm::objcopy::coff::executeObjcopyOnBinary().
The documentation for this class was generated from the following files:
lib/ObjCopy/COFF/COFFReader.h
lib/ObjCopy/COFF/COFFReader.cpp