LLVM: DarwinRISCVAsmBackend Class Reference
DarwinRISCVAsmBackend Class Reference
Public Member Functions
DarwinRISCVAsmBackend (const MCSubtargetInfo &STI, uint8_t OSABI, bool Is64Bit, bool IsLittleEndian, const MCTargetOptions &Options)
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
Public Member Functions inherited from llvm::RISCVAsmBackend
RISCVAsmBackend (const MCSubtargetInfo &STI, uint8_t OSABI, bool Is64Bit, bool IsLittleEndian, const MCTargetOptions &Options)
~RISCVAsmBackend () override=default
std::optional< bool > evaluateFixup (const MCFragment &, MCFixup &, MCValue &, uint64_t &) override
bool addReloc (const MCFragment &, const MCFixup &, const MCValue &, uint64_t &FixedValue, bool IsResolved)
void maybeAddVendorReloc (const MCFragment &, const MCFixup &)
void applyFixup (const MCFragment &, const MCFixup &, const MCValue &Target, uint8_t *Data, uint64_t Value, bool IsResolved) override
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
bool fixupNeedsRelaxationAdvanced (const MCFragment &, const MCFixup &, const MCValue &, uint64_t, bool) const override
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
std::optional< MCFixupKind > getFixupKind (StringRef Name) const override
Map a relocation name used in .reloc to a fixup kind.
MCFixupKindInfo getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
bool mayNeedRelaxation (unsigned Opcode, ArrayRef< MCOperand > Operands, const MCSubtargetInfo &STI) const override
Check whether the given instruction (encoded as Opcode+Operands) may need relaxation.
void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const override
Relax the instruction in the given fragment to the next wider instruction.
bool relaxAlign (MCFragment &F, unsigned &Size) override
bool relaxDwarfLineAddr (MCFragment &) const override
bool relaxDwarfCFA (MCFragment &) const override
std::pair< bool, bool > relaxLEB128 (MCFragment &LF, int64_t &Value) const override
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
const MCTargetOptions & getTargetOptions () const
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
void setAssembler (MCAssembler *A)
MCContext & getContext () const
bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool finishLayout () const
virtual uint64_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
void maybeAddReloc (const MCFragment &, const MCFixup &, const MCValue &, uint64_t &Value, bool IsResolved)
virtual bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value) const
Simple predicate for targets where !Resolved implies requiring relaxation.
virtual bool relaxSFrameCFA (MCFragment &) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::MCAsmBackend
static const MCSubtargetInfo * getSubtargetInfo (const MCFragment &F)
Public Attributes inherited from llvm::MCAsmBackend
const llvm::endianness Endian
Protected Member Functions inherited from llvm::RISCVAsmBackend
bool isPCRelFixupResolved (const MCSymbol *SymA, const MCFragment &F)
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (llvm::endianness Endian)
Protected Attributes inherited from llvm::RISCVAsmBackend
const MCSubtargetInfo & STI
uint8_t OSABI
bool Is64Bit
const MCTargetOptions & TargetOptions
MCSymbol * PCRelTemp = nullptr
StringMap< MCSymbol * > VendorSymbols
Protected Attributes inherited from llvm::MCAsmBackend
MCAssembler * Asm = nullptr
bool AllowAutoPadding = false
bool AllowEnhancedRelaxation = false
Detailed Description
Definition at line 960 of file RISCVAsmBackend.cpp.
Constructor & Destructor Documentation
DarwinRISCVAsmBackend()
DarwinRISCVAsmBackend::DarwinRISCVAsmBackend (const MCSubtargetInfo & STI, uint8_t OSABI, bool Is64Bit, bool IsLittleEndian, const MCTargetOptions & Options) inline
Definition at line 962 of file RISCVAsmBackend.cpp.
References llvm::RISCVAsmBackend::Is64Bit, Options, llvm::RISCVAsmBackend::OSABI, llvm::RISCVAsmBackend::RISCVAsmBackend(), and llvm::RISCVAsmBackend::STI.
Member Function Documentation
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > DarwinRISCVAsmBackend::createObjectTargetWriter () const inline override virtual
Implements llvm::MCAsmBackend.
Definition at line 967 of file RISCVAsmBackend.cpp.
References llvm::cantFail(), llvm::createRISCVMachObjectWriter(), llvm::MachO::getCPUSubType(), llvm::MachO::getCPUType(), and llvm::RISCVAsmBackend::STI.
The documentation for this class was generated from the following file:
lib/Target/RISCV/MCTargetDesc/RISCVAsmBackend.cpp