LLVM: llvm::AArch64PrologueEmitter Class Reference
llvm::AArch64PrologueEmitter Class Reference final
A helper class for emitting the prologue.
#include "Target/AArch64/AArch64PrologueEpilogue.h"
Public Member Functions
AArch64PrologueEmitter (MachineFunction &MF, MachineBasicBlock &MBB, const AArch64FrameLowering &AFL)
void emitPrologue ()
Emit the prologue.
~AArch64PrologueEmitter ()
Public Member Functions inherited from llvm::AArch64PrologueEpilogueCommon
AArch64PrologueEpilogueCommon (MachineFunction &MF, MachineBasicBlock &MBB, const AArch64FrameLowering &AFL)
Additional Inherited Members
Public Types inherited from llvm::AArch64PrologueEpilogueCommon
enum class SVEStackLayout { Default , Split , CalleeSavesAboveFrameRecord }
Protected Member Functions inherited from llvm::AArch64PrologueEpilogueCommon
bool requiresGetVGCall () const
bool isVGInstruction (MachineBasicBlock::iterator MBBI, const TargetLowering &TLI) const
MachineBasicBlock::iterator convertCalleeSaveRestoreToSPPrePostIncDec (MachineBasicBlock::iterator MBBI, const DebugLoc &DL, int CSStackSizeInc, bool EmitCFI, MachineInstr::MIFlag FrameFlag=MachineInstr::FrameSetup, int CFAOffset=0) const
void fixupCalleeSaveRestoreStackOffset (MachineInstr &MI, uint64_t LocalStackSize) const
bool shouldCombineCSRLocalStackBump (uint64_t StackBumpBytes) const
SVEFrameSizes getSVEStackFrameSizes () const
SVEStackAllocations getSVEStackAllocations (SVEFrameSizes const &)
Protected Attributes inherited from llvm::AArch64PrologueEpilogueCommon
MachineFunction & MF
MachineBasicBlock & MBB
const MachineFrameInfo & MFI
const AArch64Subtarget & Subtarget
const AArch64FrameLowering & AFL
const AArch64RegisterInfo & RegInfo
bool HasFP = false
bool EmitCFI = false
bool IsFunclet = false
bool NeedsWinCFI = false
bool HomPrologEpilog = false
SVEStackLayout SVELayout = SVEStackLayout::Default
bool HasWinCFI = false
const AArch64InstrInfo * TII = nullptr
AArch64FunctionInfo * AFI = nullptr
Detailed Description
A helper class for emitting the prologue.
Substantial new functionality should be factored into a new method. Where possible "emit*" methods should be const, and any flags that change how the prologue is emitted should be set in the constructor.
Definition at line 105 of file AArch64PrologueEpilogue.h.
Constructor & Destructor Documentation
AArch64PrologueEmitter()
llvm::AArch64PrologueEmitter::AArch64PrologueEmitter (MachineFunction & MF, MachineBasicBlock & MBB, const AArch64FrameLowering & AFL)
Definition at line 412 of file AArch64PrologueEpilogue.cpp.
References llvm::AArch64PrologueEpilogueCommon::AArch64PrologueEpilogueCommon(), llvm::AArch64PrologueEpilogueCommon::AFI, llvm::AArch64PrologueEpilogueCommon::AFL, llvm::AArch64PrologueEpilogueCommon::EmitCFI, getFunction(), llvm::AArch64PrologueEpilogueCommon::HomPrologEpilog, llvm::AArch64PrologueEpilogueCommon::IsFunclet, llvm::AArch64PrologueEpilogueCommon::MBB, and llvm::AArch64PrologueEpilogueCommon::MF.
~AArch64PrologueEmitter()
llvm::AArch64PrologueEmitter::~AArch64PrologueEmitter () inline
Definition at line 113 of file AArch64PrologueEpilogue.h.
References llvm::AArch64PrologueEpilogueCommon::HasWinCFI, and llvm::AArch64PrologueEpilogueCommon::MF.
Member Function Documentation
emitPrologue()
void llvm::AArch64PrologueEmitter::emitPrologue ()
Emit the prologue.
Definition at line 618 of file AArch64PrologueEpilogue.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::AArch64PrologueEpilogueCommon::AFI, llvm::AArch64PrologueEpilogueCommon::AFL, llvm::SVEStackAllocations::AfterPPRs, llvm::SVEStackAllocations::AfterZPRs, assert(), llvm::SVEStackAllocations::BeforePPRs, llvm::BuildMI(), llvm::AArch64PrologueEpilogueCommon::CalleeSavesAboveFrameRecord, llvm::classifyEHPersonality(), llvm::AArch64PrologueEpilogueCommon::convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::createDefCFA(), DL, llvm::AArch64PrologueEpilogueCommon::EmitCFI, llvm::emitFrameOffset(), llvm::AArch64PrologueEpilogueCommon::fixupCalleeSaveRestoreStackOffset(), llvm::MachineInstr::FrameSetup, llvm::StackOffset::getFixed(), llvm::StackOffset::getFixed(), llvm::AArch64PrologueEpilogueCommon::getSVEStackAllocations(), llvm::AArch64PrologueEpilogueCommon::getSVEStackFrameSizes(), llvm::CallingConv::GHC, llvm::AArch64PrologueEpilogueCommon::HasFP, llvm::AArch64PrologueEpilogueCommon::HasWinCFI, llvm::AArch64PrologueEpilogueCommon::HomPrologEpilog, llvm::CFIInstBuilder::insertCFIInst(), llvm::isAsynchronousEHPersonality(), llvm::AArch64PrologueEpilogueCommon::IsFunclet, llvm::isPartOfSVECalleeSaves(), llvm::AArch64PrologueEpilogueCommon::isVGInstruction(), llvm::AArch64PrologueEpilogueCommon::MBB, MBBI, llvm::AArch64PrologueEpilogueCommon::MF, llvm::AArch64PrologueEpilogueCommon::MFI, llvm::AArch64PrologueEpilogueCommon::NeedsWinCFI, llvm::partitionSVECS(), llvm::AArch64PrologueEpilogueCommon::RegInfo, llvm::MachineInstrBuilder::setMIFlag(), llvm::AArch64PrologueEpilogueCommon::Subtarget, llvm::AArch64PrologueEpilogueCommon::SVELayout, and llvm::AArch64PrologueEpilogueCommon::TII.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64PrologueEpilogue.h
lib/Target/AArch64/AArch64PrologueEpilogue.cpp