LLVM: llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT > Class Template Reference
llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT > Class Template Reference
CRTP base class for adapting an iterator to a different type.
#include "llvm/ADT/iterator.h"
Inherits llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >.
Inherited by , , , , llvm::ImutAVLValueIterator< ImmutableSet >, llvm::ImutAVLValueIterator< ImmutableSetRef >, llvm::mapped_iterator< CallGraphNode::iterator, decltype(&CGNGetValue)>, llvm::mapped_iterator< CallGraphNode::const_iterator, decltype(&CGNGetValue)>, llvm::mapped_iterator< CallGraph::iterator, decltype(&CGGetValuePtr)>, llvm::mapped_iterator< CallGraph::const_iterator, decltype(&CGGetValuePtr)>, llvm::mapped_iterator< DDGNode::iterator, decltype(&DDGGetTargetNode)>, llvm::mapped_iterator< DDGNode::const_iterator, decltype(&DDGGetTargetNode)>, llvm::mapped_iterator< ExternalSymbolMap::iterator, GetExternalSymbolMapEntryValue >, llvm::mapped_iterator< SectionMap::iterator, GetSectionMapEntryValue >, llvm::mapped_iterator< SectionMap::const_iterator, GetSectionMapEntryConstValue >, llvm::mapped_iterator< op_iterator, DerefFnTy >, llvm::mapped_iterator< const_op_iterator, ConstDerefFnTy >, llvm::mapped_iterator< SmallVector< FunctionSummary::EdgeTy, 0 >::iterator, decltype(&valueInfoFromEdge)>, llvm::mapped_iterator< llvm::Function::iterator, LLVMBBToBB >, llvm::mapped_iterator< llvm::BranchInst::succ_op_iterator, LLVMBBToSBBB >, llvm::mapped_iterator< llvm::BranchInst::const_succ_op_iterator, ConstLLVMBBToSBBB >, llvm::mapped_iterator< llvm::PHINode::const_block_iterator, LLVMBBToBB >, llvm::mapped_iterator< sandboxir::UserUseIterator, UseToUser >, llvm::mapped_iterator< DepSetTy::iterator, decltype(&DepGetVal)>, llvm::mapped_iterator< DepSetTy::iterator, decltype(&DepGetValAA)>, llvm::mapped_iterator< AADepGraphNode::DepSetTy::iterator, decltype(&DepGetVal)>, llvm::mapped_iterator< CallGraphNode::const_iterator, decltype(&CGGetValuePtr)>, llvm::mapped_iterator< typename GraphT::Edge const *, decltype(&edge_dest)>, llvm::mapped_iterator< typename GraphT::Node const *, decltype(&getNode)>, llvm::mapped_iterator< typename std::vector< NodePtrTy >::const_iterator, decltype(&getNode)>, llvm::mapped_iterator< typename std::vector< std::shared_ptr< ContextEdge< DerivedCCG, FuncTy, CallTy > > >::const_iterator, decltype(&GetCallee)>, llvm::pointee_iterator< typename VectorT::iterator >, llvm::pointee_iterator< typename VectorT::const_iterator >, llvm::pointee_iterator< SmallVectorImpl< Node * >::const_iterator >, llvm::pointee_iterator< SmallVectorImpl< SCC * >::const_iterator >, llvm::pointee_iterator< SmallPtrSetImpl< RefSCC * >::const_iterator >, llvm::pointee_iterator< decltype(Entries)::const_iterator >, llvm::pointee_iterator< SectionListType::const_iterator >, llvm::pointee_iterator< std::vector< std::unique_ptr< Module > >::const_iterator, const Module >, llvm::pointee_iterator< SmallVectorImpl< std::unique_ptr< GCOVFunction > >::const_iterator >, llvm::pointee_iterator< SmallVectorImpl< std::unique_ptr< GCOVBlock > >::const_iterator >, llvm::pointee_iterator< decltype(Remarks)::const_iterator >, llvm::pointee_iterator< const std::unique_ptr< SectionBase > * >, llvm::pointee_iterator< std::vector< std::unique_ptr< SymbolEntry > >::const_iterator >, llvm::pointer_iterator< pointee_iterator< WrappedIteratorT, T1 >, T2 >, llvm::pointer_iterator< Function::const_iterator >, llvm::pointer_iterator< MachineFunction::const_iterator >, llvm::pointer_iterator< MachineFunction::iterator >, llvm::pointer_iterator< std::vector< SUnit >::iterator >, and llvm::pointer_iterator< SelectionDAG::allnodes_iterator >.
Public Types
using difference_type = DifferenceTypeT
Public Types inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
enum { IsRandomAccess , IsBidirectional }
using iterator_category = IteratorCategoryT
using value_type = T
using difference_type = DifferenceTypeT
using pointer = PointerT
using reference = ReferenceT
Public Member Functions
DerivedT & operator+= (difference_type n)
DerivedT & operator-= (difference_type n)
template<bool Enabled = BaseT::IsRandomAccess, typename = std::enable_if_t<Enabled>>
difference_type operator- (const DerivedT &RHS) const
DerivedT & operator++ ()
DerivedT & operator-- ()
ReferenceT operator* () const
Public Member Functions inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
DerivedT operator+ (DifferenceTypeT n) const
DerivedT operator- (DifferenceTypeT n) const
DerivedT & operator++ ()
DerivedT operator++ (int)
DerivedT & operator-- ()
DerivedT operator-- (int)
bool operator!= (const DerivedT &RHS) const
bool operator> (const DerivedT &RHS) const
bool operator<= (const DerivedT &RHS) const
bool operator>= (const DerivedT &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (DifferenceTypeT n) const
Protected Member Functions
iterator_adaptor_base ()=default
iterator_adaptor_base (WrappedIteratorT u)
const WrappedIteratorT & wrapped () const
Protected Attributes
WrappedIteratorT I
Friends
bool operator== (const iterator_adaptor_base &LHS, const iterator_adaptor_base &RHS)
bool operator< (const iterator_adaptor_base &LHS, const iterator_adaptor_base &RHS)
Detailed Description
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>>
class llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
CRTP base class for adapting an iterator to a different type.
This class can be used through CRTP to adapt one iterator into another. Typically this is done through providing in the derived class a custom operator* implementation. Other methods can be overridden as well.
Definition at line 238 of file iterator.h.
Member Typedef Documentation
difference_type
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> using llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::difference_type = DifferenceTypeT
Definition at line 256 of file iterator.h.
Constructor & Destructor Documentation
iterator_adaptor_base() [1/2]
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::iterator_adaptor_base () protected default
Referenced by llvm::ImutAVLValueIterator< ImmutableSet >::ImutAVLValueIterator(), llvm::mapped_iterator< CallGraphNode::iterator, decltype(&CGNGetValue)>::mapped_iterator(), llvm::pointee_iterator< typename VectorT::iterator >::pointee_iterator(), and llvm::pointer_iterator< pointee_iterator< WrappedIteratorT, T1 >, T2 >::pointer_iterator().
iterator_adaptor_base() [2/2]
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::iterator_adaptor_base (WrappedIteratorT u) inline explicit protected
Definition at line 248 of file iterator.h.
Member Function Documentation
operator*()
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> ReferenceT llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator* () const inline
Definition at line 310 of file iterator.h.
operator++()
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> DerivedT & llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator++ () inline
Definition at line 285 of file iterator.h.
operator+=()
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> DerivedT & llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator+= (difference_type n) inline
Definition at line 258 of file iterator.h.
operator-()
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> template<bool Enabled = BaseT::IsRandomAccess, typename = std::enable_if_t<Enabled>> difference_type llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator- (const DerivedT & RHS) const inline
Definition at line 275 of file iterator.h.
operator--()
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> DerivedT & llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator-- () inline
Definition at line 290 of file iterator.h.
operator-=()
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> DerivedT & llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::operator-= (difference_type n) inline
Definition at line 265 of file iterator.h.
wrapped()
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> const WrappedIteratorT & llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::wrapped () const inline protected
Definition at line 253 of file iterator.h.
Friends And Related Symbol Documentation
operator<
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> bool operator< (const iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT > & LHS, const iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT > & RHS) friend
Definition at line 302 of file iterator.h.
operator==
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> bool operator== (const iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT > & LHS, const iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT > & RHS) friend
Definition at line 298 of file iterator.h.
Member Data Documentation
I
template<typename DerivedT, typename WrappedIteratorT, typename IteratorCategoryT = typename std::iterator_traits<WrappedIteratorT>::iterator_category, typename T = typename std::iterator_traits<WrappedIteratorT>::value_type, typename DifferenceTypeT = typename std::iterator_traits<WrappedIteratorT>::difference_type, typename PointerT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::pointer, T *>, typename ReferenceT = std::conditional_t< std::is_same<T, typename std::iterator_traits< WrappedIteratorT>::value_type>::value, typename std::iterator_traits<WrappedIteratorT>::reference, T &>> WrappedIteratorT llvm::iterator_adaptor_base< DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >::I protected
Definition at line 244 of file iterator.h.
Referenced by llvm::ImutAVLValueIterator< ImmutableSet >::operator*(), llvm::pointee_iterator< typename VectorT::iterator >::operator*(), and llvm::pointer_iterator< pointee_iterator< WrappedIteratorT, T1 >, T2 >::operator*().
The documentation for this class was generated from the following file:
include/llvm/ADT/iterator.h