LLVM: llvm::WebAssemblyTargetWasmStreamer Class Reference
llvm::WebAssemblyTargetWasmStreamer Class Reference final
This part is for Wasm object output.
#include "Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.h"
Public Member Functions
WebAssemblyTargetWasmStreamer (MCStreamer &S)
void emitLocal (ArrayRef< wasm::ValType > Types) override
.local
void emitFunctionType (const MCSymbolWasm *Sym) override
.functype
void emitIndIdx (const MCExpr *Value) override
.indidx
void emitGlobalType (const MCSymbolWasm *Sym) override
.globaltype
void emitTableType (const MCSymbolWasm *Sym) override
.tabletype
void emitTagType (const MCSymbolWasm *Sym) override
.tagtype
void emitImportModule (const MCSymbolWasm *Sym, StringRef ImportModule) override
.import_module
void emitImportName (const MCSymbolWasm *Sym, StringRef ImportName) override
.import_name
void emitExportName (const MCSymbolWasm *Sym, StringRef ExportName) override
.export_name
Public Member Functions inherited from llvm::WebAssemblyTargetStreamer
WebAssemblyTargetStreamer (MCStreamer &S)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Member Functions inherited from llvm::WebAssemblyTargetStreamer
void emitValueType (wasm::ValType Type)
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
This part is for Wasm object output.
Definition at line 78 of file WebAssemblyTargetStreamer.h.
Constructor & Destructor Documentation
WebAssemblyTargetWasmStreamer()
WebAssemblyTargetWasmStreamer::WebAssemblyTargetWasmStreamer (MCStreamer & S) explicit
Definition at line 36 of file WebAssemblyTargetStreamer.cpp.
References llvm::WebAssemblyTargetStreamer::WebAssemblyTargetStreamer().
Member Function Documentation
emitExportName()
void llvm::WebAssemblyTargetWasmStreamer::emitExportName (const MCSymbolWasm * Sym, StringRef ExportName) inline override virtual
.export_name
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 92 of file WebAssemblyTargetStreamer.h.
emitFunctionType()
void llvm::WebAssemblyTargetWasmStreamer::emitFunctionType (const MCSymbolWasm * Sym) inline override virtual
.functype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 83 of file WebAssemblyTargetStreamer.h.
emitGlobalType()
void llvm::WebAssemblyTargetWasmStreamer::emitGlobalType (const MCSymbolWasm * Sym) inline override virtual
.globaltype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 85 of file WebAssemblyTargetStreamer.h.
emitImportModule()
void llvm::WebAssemblyTargetWasmStreamer::emitImportModule (const MCSymbolWasm * Sym, StringRef ImportModule) inline override virtual
.import_module
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 88 of file WebAssemblyTargetStreamer.h.
emitImportName()
void llvm::WebAssemblyTargetWasmStreamer::emitImportName (const MCSymbolWasm * Sym, StringRef ImportName) inline override virtual
.import_name
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 90 of file WebAssemblyTargetStreamer.h.
emitIndIdx()
void WebAssemblyTargetWasmStreamer::emitIndIdx (const MCExpr * Value) override virtual
.indidx
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 137 of file WebAssemblyTargetStreamer.cpp.
References llvm_unreachable.
emitLocal()
void WebAssemblyTargetWasmStreamer::emitLocal (ArrayRef< wasm::ValType > Types) override virtual
.local
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 121 of file WebAssemblyTargetStreamer.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::WebAssemblyTargetStreamer::emitValueType(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::MCTargetStreamer::Streamer.
emitTableType()
void llvm::WebAssemblyTargetWasmStreamer::emitTableType (const MCSymbolWasm * Sym) inline override virtual
.tabletype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 86 of file WebAssemblyTargetStreamer.h.
emitTagType()
void llvm::WebAssemblyTargetWasmStreamer::emitTagType (const MCSymbolWasm * Sym) inline override virtual
.tagtype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 87 of file WebAssemblyTargetStreamer.h.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.h
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.cpp