LLVM: llvm::orc::DebugObject Class Reference
llvm::orc::DebugObject Class Reference
Public Types
using FinalizedAlloc = JITLinkMemoryManager::FinalizedAlloc
using GetLoadAddressFn = llvm::unique_function<ExecutorAddr(StringRef)>
Public Member Functions
DebugObject (StringRef Name, SimpleSegmentAlloc Alloc, JITLinkContext &Ctx, ExecutionSession &ES)
~DebugObject ()
MutableArrayRef< char > getBuffer ()
SimpleSegmentAlloc collectTargetAlloc ()
void trackFinalizedAlloc (FinalizedAlloc FA)
bool hasPendingTargetMem () const
Expected< ExecutorAddrRange > awaitTargetMem ()
void reportTargetMem (ExecutorAddrRange TargetMem)
void failMaterialization (Error Err)
void releasePendingResources ()
Error visitSections (GetLoadAddressFn Callback)
template<typename ELFT>
Error visitSectionLoadAddresses (GetLoadAddressFn Callback)
Detailed Description
Definition at line 47 of file ELFDebugObjectPlugin.cpp.
Member Typedef Documentation
FinalizedAlloc
using llvm::orc::DebugObject::FinalizedAlloc = JITLinkMemoryManager::FinalizedAlloc
Definition at line 49 of file ELFDebugObjectPlugin.cpp.
GetLoadAddressFn
using llvm::orc::DebugObject::GetLoadAddressFn = llvm::unique_function<ExecutorAddr(StringRef)>
Definition at line 108 of file ELFDebugObjectPlugin.cpp.
Constructor & Destructor Documentation
DebugObject()
llvm::orc::DebugObject::DebugObject (StringRef Name, SimpleSegmentAlloc Alloc, JITLinkContext & Ctx, ExecutionSession & ES) inline
Definition at line 51 of file ELFDebugObjectPlugin.cpp.
References llvm::move().
~DebugObject()
llvm::orc::DebugObject::~DebugObject () inline
Definition at line 56 of file ELFDebugObjectPlugin.cpp.
References assert().
Member Function Documentation
awaitTargetMem()
Expected< ExecutorAddrRange > llvm::orc::DebugObject::awaitTargetMem () inline
Definition at line 80 of file ELFDebugObjectPlugin.cpp.
References assert().
Referenced by llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
collectTargetAlloc()
SimpleSegmentAlloc llvm::orc::DebugObject::collectTargetAlloc () inline
Definition at line 71 of file ELFDebugObjectPlugin.cpp.
Referenced by llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
failMaterialization()
void llvm::orc::DebugObject::failMaterialization (Error Err) inline
Definition at line 91 of file ELFDebugObjectPlugin.cpp.
Referenced by llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
getBuffer()
MutableArrayRef< char > llvm::orc::DebugObject::getBuffer () inline
Definition at line 66 of file ELFDebugObjectPlugin.cpp.
References llvm::orc::Read.
Referenced by visitSectionLoadAddresses(), and visitSections().
hasPendingTargetMem()
bool llvm::orc::DebugObject::hasPendingTargetMem () const inline
Definition at line 78 of file ELFDebugObjectPlugin.cpp.
Referenced by llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
releasePendingResources()
void llvm::orc::DebugObject::releasePendingResources () inline
Definition at line 95 of file ELFDebugObjectPlugin.cpp.
References llvm::Expected< T >::get(), and llvm::Expected< T >::takeError().
reportTargetMem()
void llvm::orc::DebugObject::reportTargetMem (ExecutorAddrRange TargetMem) inline
Definition at line 87 of file ELFDebugObjectPlugin.cpp.
Referenced by llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
trackFinalizedAlloc()
void llvm::orc::DebugObject::trackFinalizedAlloc (FinalizedAlloc FA) inline
Definition at line 76 of file ELFDebugObjectPlugin.cpp.
Referenced by llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
visitSectionLoadAddresses()
template<typename ELFT> Error llvm::orc::DebugObject::visitSectionLoadAddresses (GetLoadAddressFn Callback)
Definition at line 127 of file ELFDebugObjectPlugin.cpp.
References llvm::cantFail(), llvm::object::ELFFile< ELFT >::create(), llvm::MutableArrayRef< T >::data(), llvm::dbgs(), llvm::formatv(), getBuffer(), llvm::orc::ExecutorAddr::getValue(), LLVM_DEBUG, llvm::ArrayRef< T >::size(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by visitSections().
visitSections()
Error llvm::orc::DebugObject::visitSections (GetLoadAddressFn Callback)
Definition at line 168 of file ELFDebugObjectPlugin.cpp.
References llvm::MutableArrayRef< T >::data(), llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::ELFDATA2MSB, getBuffer(), llvm::object::getElfArchType(), llvm_unreachable, llvm::ArrayRef< T >::size(), and visitSectionLoadAddresses().
Referenced by llvm::orc::ELFDebugObjectPlugin::modifyPassConfig().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/Debugging/ELFDebugObjectPlugin.cpp