LLVM: llvm::orc::StaticInitGVIterator Class Reference
llvm::orc::StaticInitGVIterator Class Reference
This iterator provides a convenient way to iterate over GlobalValues that have initialization effects.
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
Public Member Functions
StaticInitGVIterator ()=default
StaticInitGVIterator (Module &M)
bool operator== (const StaticInitGVIterator &O) const
bool operator!= (const StaticInitGVIterator &O) const
StaticInitGVIterator & operator++ ()
GlobalValue & operator* ()
Detailed Description
This iterator provides a convenient way to iterate over GlobalValues that have initialization effects.
Definition at line 102 of file ExecutionUtils.h.
Constructor & Destructor Documentation
StaticInitGVIterator() [1/2]
llvm::orc::StaticInitGVIterator::StaticInitGVIterator () default
Referenced by operator!=(), operator++(), and operator==().
StaticInitGVIterator() [2/2]
llvm::orc::StaticInitGVIterator::StaticInitGVIterator (Module & M) inline
Definition at line 106 of file ExecutionUtils.h.
References llvm::begin(), and llvm::end().
Member Function Documentation
operator!=()
bool llvm::orc::StaticInitGVIterator::operator!= (const StaticInitGVIterator & O) const inline
Definition at line 117 of file ExecutionUtils.h.
References StaticInitGVIterator().
operator*()
GlobalValue & llvm::orc::StaticInitGVIterator::operator* () inline
Definition at line 125 of file ExecutionUtils.h.
operator++()
StaticInitGVIterator & llvm::orc::StaticInitGVIterator::operator++ () inline
Definition at line 119 of file ExecutionUtils.h.
References assert(), and StaticInitGVIterator().
operator==()
bool llvm::orc::StaticInitGVIterator::operator== (const StaticInitGVIterator & O) const inline
Definition at line 116 of file ExecutionUtils.h.
References StaticInitGVIterator().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutionUtils.h
lib/ExecutionEngine/Orc/ExecutionUtils.cpp