LLVM: llvm::GCNRewritePartialRegUsesPass Class Reference
llvm::GCNRewritePartialRegUsesPass Class Reference
#include "Target/AMDGPU/GCNRewritePartialRegUses.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< GCNRewritePartialRegUsesPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< GCNRewritePartialRegUsesPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 15 of file GCNRewritePartialRegUses.h.
Member Function Documentation
run()
PreservedAnalyses GCNRewritePartialRegUsesPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 455 of file GCNRewritePartialRegUses.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::getMachineFunctionPassPreservedAnalyses(), and run().
Referenced by run().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNRewritePartialRegUses.h
lib/Target/AMDGPU/GCNRewritePartialRegUses.cpp