LLVM: llvm::VPBasicBlock Class Reference
llvm::VPBasicBlock Class Reference
VPBasicBlock serves as the leaf of the Hierarchical Control-Flow Graph.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using RecipeListTy = iplist<VPRecipeBase>
using iterator = RecipeListTy::iterator
Instruction iterators...
using const_iterator = RecipeListTy::const_iterator
using reverse_iterator = RecipeListTy::reverse_iterator
using const_reverse_iterator = RecipeListTy::const_reverse_iterator
Public Types inherited from llvm::VPBlockBase
using VPBlockTy = enum { VPRegionBlockSC, VPBasicBlockSC, VPIRBasicBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
using VPBlocksTy = SmallVectorImpl<VPBlockBase *>
Public Member Functions
~VPBasicBlock () override
iterator begin ()
Recipe iterator methods.
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
const VPRecipeBase & front () const
VPRecipeBase & front ()
const VPRecipeBase & back () const
VPRecipeBase & back ()
RecipeListTy & getRecipeList ()
Returns a reference to the list of recipes.
void insert (VPRecipeBase *Recipe, iterator InsertPt)
void appendRecipe (VPRecipeBase *Recipe)
Augment the existing recipes of a VPBasicBlock with an additional Recipe as the last recipe.
void execute (VPTransformState *State) override
The method which generates the output IR instructions that correspond to this VPBasicBlock, thereby "executing" the VPlan.
InstructionCost cost (ElementCount VF, VPCostContext &Ctx) override
Return the cost of this VPBasicBlock.
iterator getFirstNonPhi ()
Return the position of the first non-phi node recipe in the block.
iterator_range< iterator > phis ()
Returns an iterator range over the PHI-like recipes in the block.
VPBasicBlock * splitAt (iterator SplitAt)
Split current block at SplitAt by inserting a new block between the current block and its successors and moving all recipes starting at SplitAt to the new block.
VPRegionBlock * getEnclosingLoopRegion ()
const VPRegionBlock * getEnclosingLoopRegion () const
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print this VPBsicBlock to O, prefixing all lines with Indent.
VPRecipeBase * getTerminator ()
If the block has multiple successors, return the branch recipe terminating the block.
const VPRecipeBase * getTerminator () const
bool isExiting () const
Returns true if the block is exiting it's parent region.
VPBasicBlock * clone () override
Clone the current block and it's recipes, without updating the operands of the cloned recipes.
const VPBasicBlock * getCFGPredecessor (unsigned Idx) const
Returns the predecessor block at index Idx with the predecessors as per the corresponding plain CFG.
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
Public Member Functions inherited from llvm::VPBlockBase
virtual ~VPBlockBase ()=default
const std::string & getName () const
void setName (const Twine &newName)
unsigned getVPBlockID () const
VPRegionBlock * getParent ()
const VPRegionBlock * getParent () const
VPlan * getPlan ()
const VPlan * getPlan () const
void setPlan (VPlan *ParentPlan)
Sets the pointer of the plan containing the block.
void setParent (VPRegionBlock *P)
const VPBasicBlock * getEntryBasicBlock () const
VPBasicBlock * getEntryBasicBlock ()
const VPBasicBlock * getExitingBasicBlock () const
VPBasicBlock * getExitingBasicBlock ()
const VPBlocksTy & getSuccessors () const
VPBlocksTy & getSuccessors ()
iterator_range< VPBlockBase ** > successors ()
iterator_range< VPBlockBase ** > predecessors ()
const VPBlocksTy & getPredecessors () const
VPBlocksTy & getPredecessors ()
VPBlockBase * getSingleSuccessor () const
VPBlockBase * getSinglePredecessor () const
size_t getNumSuccessors () const
size_t getNumPredecessors () const
bool hasPredecessors () const
Returns true if this block has any predecessors.
VPBlockBase * getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
VPBlockBase * getEnclosingBlockWithPredecessors ()
const VPBlocksTy & getHierarchicalSuccessors ()
VPBlockBase * getSingleHierarchicalSuccessor ()
const VPBlocksTy & getHierarchicalPredecessors ()
VPBlockBase * getSingleHierarchicalPredecessor ()
void setOneSuccessor (VPBlockBase *Successor)
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
void setTwoSuccessors (VPBlockBase *IfTrue, VPBlockBase *IfFalse)
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
void setPredecessors (ArrayRef< VPBlockBase * > NewPreds)
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
void setSuccessors (ArrayRef< VPBlockBase * > NewSuccs)
Set each VPBasicBlock in NewSuccss as successor of this VPBlockBase.
void clearPredecessors ()
Remove all the predecessor of this block.
void clearSuccessors ()
Remove all the successors of this block.
void swapPredecessors ()
Swap predecessors of the block.
void swapSuccessors ()
Swap successors of the block. The block must have exactly 2 successors.
unsigned getIndexForPredecessor (const VPBlockBase *Pred) const
Returns the index for Pred in the blocks predecessors list.
unsigned getIndexForSuccessor (const VPBlockBase *Succ) const
Returns the index for Succ in the blocks successor list.
void printAsOperand (raw_ostream &OS, bool PrintType=false) const
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
void printSuccessors (raw_ostream &O, const Twine &Indent) const
Print the successors of this block to O, prefixing all lines with Indent.
LLVM_DUMP_METHOD void dump () const
Dump this VPBlockBase to dbgs().
Static Public Member Functions
static RecipeListTy VPBasicBlock::* getSublistAccess (VPRecipeBase *)
Returns a pointer to a member of the recipe list.
static bool classof (const VPBlockBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Protected Member Functions
VPBasicBlock (const unsigned char BlockSC, const Twine &Name="")
void executeRecipes (VPTransformState *State, BasicBlock *BB)
Execute the recipes in the IR basic block BB.
void connectToPredecessors (VPTransformState &State)
Connect the VPBBs predecessors' in the VPlan CFG to the IR basic block generated for this VPBB.
Protected Member Functions inherited from llvm::VPBlockBase
VPBlockBase (const unsigned char SC, const std::string &N)
Protected Attributes
RecipeListTy Recipes
The VPRecipes held in the order of output instructions to generate.
Friends
class VPlan
Detailed Description
VPBasicBlock serves as the leaf of the Hierarchical Control-Flow Graph.
It holds a sequence of zero or more VPRecipe's each representing a sequence of output IR instructions. All PHI-like recipes must come before any non-PHI recipes.
Definition at line 3948 of file VPlan.h.
Member Typedef Documentation
const_iterator
using llvm::VPBasicBlock::const_iterator = RecipeListTy::const_iterator
Definition at line 3976 of file VPlan.h.
const_reverse_iterator
using llvm::VPBasicBlock::const_reverse_iterator = RecipeListTy::const_reverse_iterator
Definition at line 3978 of file VPlan.h.
iterator
using llvm::VPBasicBlock::iterator = RecipeListTy::iterator
Instruction iterators...
Definition at line 3975 of file VPlan.h.
RecipeListTy
using llvm::VPBasicBlock::RecipeListTy = iplist<VPRecipeBase>
Definition at line 3959 of file VPlan.h.
reverse_iterator
using llvm::VPBasicBlock::reverse_iterator = RecipeListTy::reverse_iterator
Definition at line 3977 of file VPlan.h.
Constructor & Destructor Documentation
VPBasicBlock()
llvm::VPBasicBlock::VPBasicBlock (const unsigned char BlockSC, const Twine & Name = "") inline protected
Definition at line 3965 of file VPlan.h.
References llvm::VPBlockBase::VPBlockBase().
~VPBasicBlock()
llvm::VPBasicBlock::~VPBasicBlock () inline override
Definition at line 3969 of file VPlan.h.
References Recipes.
Member Function Documentation
appendRecipe()
void llvm::VPBasicBlock::appendRecipe (VPRecipeBase * Recipe) inline
Augment the existing recipes of a VPBasicBlock with an additional Recipe as the last recipe.
Definition at line 4023 of file VPlan.h.
References end(), and insert().
Referenced by clone(), llvm::VPIRBasicBlock::clone(), llvm::VPlanTransforms::createInLoopReductionRecipes(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), optimizeVectorInductionWidthForTCAndVFUF(), simplifyBranchConditionForVFAndUF(), and VPlan.
back() [1/2]
VPRecipeBase & llvm::VPBasicBlock::back () inline
Definition at line 3998 of file VPlan.h.
References Recipes.
back() [2/2]
const VPRecipeBase & llvm::VPBasicBlock::back () const inline
Definition at line 3997 of file VPlan.h.
References Recipes.
Referenced by addCanonicalIVRecipes(), getTerminator(), getTerminator(), hasConditionalTerminator(), llvm::VPlanTransforms::hoistPredicatedLoads(), simplifyBranchConditionForVFAndUF(), and tryToReplaceALMWithWideALM().
begin() [1/2]
iterator llvm::VPBasicBlock::begin () inline
Recipe iterator methods.
Definition at line 3983 of file VPlan.h.
References Recipes.
Referenced by addCanonicalIVRecipes(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPRegionBlock::getCanonicalIV(), getFirstNonPhi(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::materializeBackedgeTakenCount(), llvm::VPlanTransforms::materializeBroadcasts(), llvm::VPlanTransforms::materializeVectorTripCount(), llvm::VPlanTransforms::materializeVFAndVFxUF(), phis(), preparePlanForMainVectorLoop(), and replaceVPBBWithIRVPBB().
begin() [2/2]
const_iterator llvm::VPBasicBlock::begin () const inline
Definition at line 3984 of file VPlan.h.
References Recipes.
classof()
bool llvm::VPBasicBlock::classof (const VPBlockBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 4009 of file VPlan.h.
References llvm::VPBlockBase::VPBlockBase().
clone()
VPBasicBlock * VPBasicBlock::clone () override virtual
Clone the current block and it's recipes, without updating the operands of the cloned recipes.
Implements llvm::VPBlockBase.
Reimplemented in llvm::VPIRBasicBlock.
Definition at line 540 of file VPlan.cpp.
References appendRecipe(), llvm::VPlan::createVPBasicBlock(), llvm::VPBlockBase::getName(), and llvm::VPBlockBase::getPlan().
connectToPredecessors()
void VPBasicBlock::connectToPredecessors (VPTransformState & State) protected
Connect the VPBBs predecessors' in the VPlan CFG to the IR basic block generated for this VPBB.
Definition at line 389 of file VPlan.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), assert(), llvm::cast(), CFG, llvm::BranchInst::Create(), llvm::dbgs(), DL, llvm::dyn_cast(), llvm::VPBlockBase::getHierarchicalSuccessors(), llvm::Value::getName(), llvm::VPBlockBase::getPlan(), llvm::VPBlockBase::getPredecessors(), llvm::VPBlockBase::getSingleSuccessor(), llvm::BasicBlock::getTerminator(), llvm::DominatorTreeBase< BasicBlock, false >::Insert, llvm::isa(), llvm::VPBlockUtils::isHeader(), LLVM_DEBUG, llvm::to_vector(), and llvm::VPBlockBase::VPBlockBase().
Referenced by execute(), and llvm::VPIRBasicBlock::execute().
cost()
InstructionCost VPBasicBlock::cost (ElementCount VF, VPCostContext & Ctx) override virtual
Return the cost of this VPBasicBlock.
Implements llvm::VPBlockBase.
Definition at line 775 of file VPlan.cpp.
References Recipes.
Referenced by llvm::VPlan::cost(), and isOutsideLoopWorkProfitable().
empty()
bool llvm::VPBasicBlock::empty () const inline
Definition at line 3994 of file VPlan.h.
References Recipes.
Referenced by addCanonicalIVRecipes(), llvm::VPRegionBlock::getCanonicalIV(), and hasConditionalTerminator().
end() [1/2]
iterator llvm::VPBasicBlock::end () inline
Definition at line 3985 of file VPlan.h.
References Recipes.
Referenced by appendRecipe(), llvm::VPlanTransforms::createInLoopReductionRecipes(), llvm::EpilogueVectorizerEpilogueLoop::createVectorizedLoopSkeleton(), getFirstNonPhi(), llvm::VPRecipeBase::insertBefore(), licm(), mergeBlocksIntoPredecessors(), preparePlanForMainVectorLoop(), replaceVPBBWithIRVPBB(), llvm::VPBuilder::setInsertPoint(), and splitAt().
end() [2/2]
const_iterator llvm::VPBasicBlock::end () const inline
Definition at line 3986 of file VPlan.h.
References Recipes.
execute()
void VPBasicBlock::execute (VPTransformState * State) override virtual
The method which generates the output IR instructions that correspond to this VPBasicBlock, thereby "executing" the VPlan.
Implements llvm::VPBlockBase.
Reimplemented in llvm::VPIRBasicBlock.
Definition at line 489 of file VPlan.cpp.
References llvm::LoopBase< BlockT, LoopT >::addChildLoop(), assert(), connectToPredecessors(), llvm::dyn_cast_or_null(), executeRecipes(), llvm::VPBlockBase::getParent(), llvm::VPBlockBase::getSingleHierarchicalPredecessor(), llvm::VPBlockUtils::isHeader(), llvm::VPBlockUtils::isLatch(), and llvm::VPBlockBase::VPBlockBase().
executeRecipes()
void VPBasicBlock::executeRecipes (VPTransformState * State, BasicBlock * BB) protected
Execute the recipes in the IR basic block BB.
Definition at line 547 of file VPlan.cpp.
References llvm::dbgs(), llvm::Value::getName(), llvm::VPBlockBase::getName(), LLVM_DEBUG, and Recipes.
Referenced by execute(), and llvm::VPIRBasicBlock::execute().
front() [1/2]
VPRecipeBase & llvm::VPBasicBlock::front () inline
Definition at line 3996 of file VPlan.h.
References Recipes.
front() [2/2]
const VPRecipeBase & llvm::VPBasicBlock::front () const inline
Definition at line 3995 of file VPlan.h.
References Recipes.
getCFGPredecessor()
const VPBasicBlock * VPBasicBlock::getCFGPredecessor (unsigned Idx) const
Returns the predecessor block at index Idx with the predecessors as per the corresponding plain CFG.
If the block is an entry block to a region, the first predecessor is the single predecessor of a region, and the second predecessor is the exiting block of the region.
Definition at line 782 of file VPlan.cpp.
References assert(), llvm::RegionBase< Tr >::getEntry(), llvm::VPBlockBase::getNumPredecessors(), llvm::VPBlockBase::getParent(), llvm::VPBlockBase::getPredecessors(), llvm::VPBlockBase::hasPredecessors(), and llvm::VPBlockBase::VPBlockBase().
Referenced by llvm::VPPhiAccessors::getIncomingBlock().
getEnclosingLoopRegion() [1/2]
VPRegionBlock * VPBasicBlock::getEnclosingLoopRegion ()
Definition at line 589 of file VPlan.cpp.
References getEnclosingLoopRegionForRegion(), and llvm::VPBlockBase::getParent().
Referenced by hoistPreviousBeforeFORUsers(), and isDefinedInsideLoopRegions().
getEnclosingLoopRegion() [2/2]
const VPRegionBlock * VPBasicBlock::getEnclosingLoopRegion () const
Definition at line 593 of file VPlan.cpp.
References getEnclosingLoopRegionForRegion(), and llvm::VPBlockBase::getParent().
getFirstNonPhi()
VPBasicBlock::iterator VPBasicBlock::getFirstNonPhi ()
Return the position of the first non-phi node recipe in the block.
Definition at line 228 of file VPlan.cpp.
References begin(), and end().
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences(), createExtractsForLiveOuts(), llvm::VPlanTransforms::hoistInvariantLoads(), legalizeAndOptimizeInductions(), mergeReplicateRegionsIntoSuccessors(), phis(), replaceVPBBWithIRVPBB(), and sinkScalarOperands().
getRecipeList()
RecipeListTy & llvm::VPBasicBlock::getRecipeList () inline
Returns a reference to the list of recipes.
Definition at line 4001 of file VPlan.h.
References Recipes.
Referenced by llvm::VPRecipeBase::eraseFromParent(), and llvm::VPRecipeBase::removeFromParent().
getSublistAccess()
RecipeListTy VPBasicBlock::* llvm::VPBasicBlock::getSublistAccess (VPRecipeBase *) inline static
Returns a pointer to a member of the recipe list.
Definition at line 4004 of file VPlan.h.
References Recipes.
getTerminator() [1/2]
VPRecipeBase * VPBasicBlock::getTerminator ()
If the block has multiple successors, return the branch recipe terminating the block.
If there are no or only a single successor, return nullptr;
Definition at line 635 of file VPlan.cpp.
References back(), and hasConditionalTerminator().
Referenced by llvm::VPlanTransforms::addBranchWeightToMiddleTerminator(), addCanonicalIVRecipes(), addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlanTransforms::canonicalizeEVLLoops(), expandVPWidenIntOrFpInduction(), expandVPWidenPointerInduction(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleUncountableEarlyExit(), and llvm::VPlanTransforms::introduceMasksAndLinearize().
getTerminator() [2/2]
const VPRecipeBase * VPBasicBlock::getTerminator () const
Definition at line 641 of file VPlan.cpp.
References back(), and hasConditionalTerminator().
insert()
void llvm::VPBasicBlock::insert (VPRecipeBase * Recipe, iterator InsertPt) inline
Definition at line 4014 of file VPlan.h.
References assert(), and Recipes.
Referenced by addCanonicalIVRecipes(), appendRecipe(), llvm::VPlanTransforms::createInLoopReductionRecipes(), llvm::VPRecipeBase::insertAfter(), llvm::VPRecipeBase::insertBefore(), and llvm::VPRecipeBase::insertBefore().
isExiting()
bool VPBasicBlock::isExiting () const
Returns true if the block is exiting it's parent region.
Definition at line 647 of file VPlan.cpp.
References llvm::VPBlockBase::getExitingBasicBlock(), and llvm::VPBlockBase::getParent().
Referenced by hasConditionalTerminator().
phis()
iterator_range< iterator > llvm::VPBasicBlock::phis () inline
Returns an iterator range over the PHI-like recipes in the block.
Definition at line 4036 of file VPlan.h.
References begin(), getFirstNonPhi(), and llvm::make_range().
Referenced by llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), addInitialSkeleton(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::calculateRegisterUsageForPlan(), llvm::VPlanTransforms::clearReductionWrapFlags(), llvm::VPlanTransforms::createHeaderPhiRecipes(), findHeaderMask(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::VPlanTransforms::handleUncountableEarlyExit(), legalizeAndOptimizeInductions(), optimizeVectorInductionWidthForTCAndVFUF(), preparePlanForMainVectorLoop(), llvm::VPlanTransforms::removeBranchOnConst(), removeRedundantCanonicalIVs(), removeRedundantInductionCasts(), replaceVPBBWithIRVPBB(), llvm::LoopVectorizationPlanner::selectInterleaveCount(), llvm::VPlanTransforms::unrollByUF(), and llvm::VPlanTransforms::updateScalarResumePhis().
print() [1/2]
void VPBlockBase::print (raw_ostream & O) const
Print plain-text dump of this VPlan to O.
Definition at line 363 of file VPlan.cpp.
References I.
print() [2/2]
void VPBasicBlock::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print this VPBsicBlock to O, prefixing all lines with Indent.
SlotTracker is used to print unnamed VPValue's using consequtive numbers.
Note that the numbering is applied to the whole VPlan, so printing individual blocks is consistent with the whole VPlan printing.
Implements llvm::VPBlockBase.
Definition at line 669 of file VPlan.cpp.
References llvm::VPBlockBase::getName(), llvm::VPRecipeBase::print(), and llvm::VPBlockBase::printSuccessors().
rbegin() [1/2]
reverse_iterator llvm::VPBasicBlock::rbegin () inline
Definition at line 3988 of file VPlan.h.
References Recipes.
rbegin() [2/2]
const_reverse_iterator llvm::VPBasicBlock::rbegin () const inline
Definition at line 3989 of file VPlan.h.
References Recipes.
rend() [1/2]
reverse_iterator llvm::VPBasicBlock::rend () inline
Definition at line 3990 of file VPlan.h.
References Recipes.
rend() [2/2]
const_reverse_iterator llvm::VPBasicBlock::rend () const inline
Definition at line 3991 of file VPlan.h.
References Recipes.
size()
size_t llvm::VPBasicBlock::size () const inline
Definition at line 3993 of file VPlan.h.
References Recipes.
Referenced by llvm::VPIRBasicBlock::execute().
splitAt()
VPBasicBlock * VPBasicBlock::splitAt (iterator SplitAt)
Split current block at SplitAt by inserting a new block between the current block and its successors and moving all recipes starting at SplitAt to the new block.
Returns the new block.
Definition at line 561 of file VPlan.cpp.
References assert(), llvm::VPlan::createVPBasicBlock(), end(), llvm::VPBlockBase::getName(), llvm::VPBlockBase::getPlan(), llvm::VPBlockUtils::insertBlockAfter(), llvm::make_early_inc_range(), llvm::make_range(), and llvm::SplitBlock().
Referenced by addReplicateRegions().
Friends And Related Symbol Documentation
VPlan
friend class VPlan friend
Definition at line 3949 of file VPlan.h.
References appendRecipe(), llvm::VPBlockBase::VPBlockBase(), and VPlan.
Referenced by VPlan.
Member Data Documentation
Recipes
RecipeListTy llvm::VPBasicBlock::Recipes protected
The VPRecipes held in the order of output instructions to generate.
Definition at line 3963 of file VPlan.h.
Referenced by back(), back(), begin(), begin(), llvm::VPIRBasicBlock::clone(), cost(), empty(), end(), end(), executeRecipes(), front(), front(), getRecipeList(), getSublistAccess(), insert(), rbegin(), rbegin(), rend(), rend(), size(), and ~VPBasicBlock().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp