LLVM: llvm::GlobPattern Class Reference
llvm::GlobPattern Class Reference
This class implements a glob pattern matcher similar to the one found in bash, but with some key differences.
#include "llvm/Support/GlobPattern.h"
Public Member Functions
LLVM_ABI bool match (StringRef S) const
bool isTrivialMatchAll () const
StringRef prefix () const
StringRef suffix () const
LLVM_ABI_FOR_TEST StringRef longest_substr () const
Static Public Member Functions
static LLVM_ABI Expected< GlobPattern > create (StringRef Pat, std::optional< size_t > MaxSubPatterns={})
Detailed Description
This class implements a glob pattern matcher similar to the one found in bash, but with some key differences.
Namely, that * matches all characters and does not exclude path separators.
? matches a single character.
* matches zero or more characters.
[<chars>] matches one character in the bracket. Character ranges, e.g., [a-z], and negative sets via [^ab] or [!ab] are also supported.
{<glob>,...} matches one of the globs in the list. Nested brace expansions are not supported. If MaxSubPatterns is empty then brace expansions are not supported and characters {,} are treated as literals.
\\endiskip escapes the next character so it is treated as a literal.
Some known edge cases are:
The literal ] is allowed as the first character in a character class, i.e., []] is valid and matches the literal ].
The empty character class, i.e., [], is invalid.
Empty or singleton brace expansions, e.g., {}, {a}, are invalid.
The literals } and , that are not inside a brace expansion are taken as literals, e.g., ,} is valid but { is not.
Examples:
*[/\\]foo.{c,cpp} will match (unix or windows) paths to files named foo.c or foo.cpp.
_Z{N,NK,}S[tabsoid]* will match mangled C++ standard library functions.
Definition at line 52 of file GlobPattern.h.
Member Function Documentation
create()
Expected< GlobPattern > GlobPattern::create (StringRef Pat, std::optional< size_t > MaxSubPatterns = {}) static
Parameters
Pat the pattern to match against
MaxSubPatterns if provided limit the number of allowed subpatterns created from expanding braces otherwise disable brace expansion
Definition at line 179 of file GlobPattern.cpp.
References assert(), llvm::StringRef::find_first_of(), llvm::StringRef::find_last_of(), parseBraceExpansions(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::StringRef::size(), llvm::StringRef::substr(), and SuffixStart.
Referenced by llvm::objcopy::NameOrPattern::create(), and llvm::ifs::filterIFSSyms().
isTrivialMatchAll()
bool llvm::GlobPattern::isTrivialMatchAll () const inline
Definition at line 65 of file GlobPattern.h.
longest_substr()
StringRef GlobPattern::longest_substr () const
Definition at line 248 of file GlobPattern.cpp.
References maxPlainSubstring().
match()
bool GlobPattern::match (StringRef S) const
Returns
true if S matches this glob pattern
Definition at line 253 of file GlobPattern.cpp.
References llvm::StringRef::consume_back(), llvm::StringRef::consume_front(), llvm::StringRef::empty(), prefix(), and suffix().
prefix()
StringRef llvm::GlobPattern::prefix () const inline
Definition at line 79 of file GlobPattern.h.
References llvm::StringRef::take_front().
Referenced by match().
suffix()
StringRef llvm::GlobPattern::suffix () const inline
Definition at line 81 of file GlobPattern.h.
References llvm::StringRef::take_back().
Referenced by match().
The documentation for this class was generated from the following files:
include/llvm/Support/GlobPattern.h
lib/Support/GlobPattern.cpp