LLVM: llvm::VPlan Class Reference
llvm::VPlan Class Reference
VPlan models a candidate for vectorization, encoding various decisions take to produce efficient output IR, including which branches, basic-blocks and output IR instructions to generate, and their cost.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPlan (Loop *L)
Construct a VPlan for L.
VPlan (BasicBlock *ScalarHeaderBB)
Construct a VPlan with a new VPBasicBlock as entry, a VPIRBasicBlock wrapping ScalarHeaderBB and a trip count of TC.
LLVM_ABI_FOR_TEST ~VPlan ()
void setEntry (VPBasicBlock *VPBB)
void execute (VPTransformState *State)
Generate the IR code for this VPlan.
InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this plan.
VPBasicBlock * getEntry ()
const VPBasicBlock * getEntry () const
VPBasicBlock * getVectorPreheader ()
Returns the preheader of the vector loop region, if one exists, or null otherwise.
LLVM_ABI_FOR_TEST VPRegionBlock * getVectorLoopRegion ()
Returns the VPRegionBlock of the vector loop.
LLVM_ABI_FOR_TEST const VPRegionBlock * getVectorLoopRegion () const
VPBasicBlock * getMiddleBlock ()
Returns the 'middle' block of the plan, that is the block that selects whether to execute the scalar tail loop or the exit block from the loop latch.
const VPBasicBlock * getMiddleBlock () const
VPBasicBlock * getScalarPreheader () const
Return the VPBasicBlock for the preheader of the scalar loop.
VPIRBasicBlock * getScalarHeader () const
Return the VPIRBasicBlock wrapping the header of the scalar loop.
ArrayRef< VPIRBasicBlock * > getExitBlocks () const
Return an ArrayRef containing VPIRBasicBlocks wrapping the exit blocks of the original scalar loop.
VPIRBasicBlock * getExitBlock (BasicBlock *IRBB) const
Return the VPIRBasicBlock corresponding to IRBB.
bool isExitBlock (VPBlockBase *VPBB)
Returns true if VPBB is an exit block.
VPValue * getTripCount () const
The trip count of the original loop.
void setTripCount (VPValue *NewTripCount)
Set the trip count assuming it is currently null; if it is not - use resetTripCount().
void resetTripCount (VPValue *NewTripCount)
Resets the trip count for the VPlan.
VPValue * getOrCreateBackedgeTakenCount ()
The backedge taken count of the original loop.
VPValue * getBackedgeTakenCount () const
VPSymbolicValue & getVectorTripCount ()
The vector trip count.
VPValue & getVF ()
Returns the VF of the vector loop region.
const VPValue & getVF () const
VPValue & getVFxUF ()
Returns VF * UF of the vector loop region.
LLVMContext & getContext () const
void addVF (ElementCount VF)
void setVF (ElementCount VF)
bool hasVF (ElementCount VF) const
bool hasScalableVF () const
iterator_range< SmallSetVector< ElementCount, 2 >::iterator > vectorFactors () const
Returns an iterator range over all VFs of the plan.
bool hasScalarVFOnly () const
bool hasUF (unsigned UF) const
unsigned getUF () const
void setUF (unsigned UF)
bool isUnrolled () const
Returns true if the VPlan already has been unrolled, i.e.
std::string getName () const
Return a string with the name of the plan and the applicable VFs and UFs.
void setName (const Twine &newName)
VPIRValue * getOrAddLiveIn (Value *V)
Gets the live-in VPIRValue for V or adds a new live-in (if none exists yet) for V.
VPIRValue * getOrAddLiveIn (VPIRValue *V)
VPIRValue * getTrue ()
Return a VPIRValue wrapping i1 true.
VPIRValue * getFalse ()
Return a VPIRValue wrapping i1 false.
VPIRValue * getConstantInt (Type *Ty, uint64_t Val, bool IsSigned=false)
Return a VPIRValue wrapping a ConstantInt with the given type and value.
VPIRValue * getConstantInt (unsigned BitWidth, uint64_t Val, bool IsSigned=false)
Return a VPIRValue wrapping a ConstantInt with the given bitwidth and value.
VPIRValue * getConstantInt (const APInt &Val)
Return a VPIRValue wrapping a ConstantInt with the given APInt value.
VPIRValue * getLiveIn (Value *V) const
Return the live-in VPIRValue for V, if there is one or nullptr otherwise.
auto getLiveIns () const
Return the list of live-in VPValues available in the VPlan.
void printLiveIns (raw_ostream &O) const
Print the live-ins of this VPlan to O.
LLVM_ABI_FOR_TEST void print (raw_ostream &O) const
Print this VPlan to O.
LLVM_ABI_FOR_TEST void printDOT (raw_ostream &O) const
Print this VPlan in DOT format to O.
LLVM_DUMP_METHOD void dump () const
Dump the plan to stderr (for debugging).
LLVM_ABI_FOR_TEST VPlan * duplicate ()
Clone the current VPlan, update all VPValues of the new VPlan and cloned recipes to refer to the clones, and return it.
VPBasicBlock * createVPBasicBlock (const Twine &Name, VPRecipeBase *Recipe=nullptr)
Create a new VPBasicBlock with Name and containing Recipe if present.
VPRegionBlock * createLoopRegion (const std::string &Name="", VPBlockBase *Entry=nullptr, VPBlockBase *Exiting=nullptr)
Create a new loop region with Name and entry and exiting blocks set to Entry and Exiting respectively, if set.
VPRegionBlock * createReplicateRegion (VPBlockBase *Entry, VPBlockBase *Exiting, const std::string &Name="")
Create a new replicate region with Entry, Exiting and Name.
VPIRBasicBlock * createEmptyVPIRBasicBlock (BasicBlock *IRBB)
Create a VPIRBasicBlock wrapping IRBB, but do not create VPIRInstructions wrapping the instructions in tIRBB.
LLVM_ABI_FOR_TEST VPIRBasicBlock * createVPIRBasicBlock (BasicBlock *IRBB)
Create a VPIRBasicBlock from IRBB containing VPIRInstructions for all instructions in IRBB, except its terminator which is managed by the successors of the block in VPlan.
bool hasEarlyExit () const
Returns true if the VPlan is based on a loop with an early exit.
bool hasScalarTail () const
Returns true if the scalar tail may execute after the vector loop.
Friends
class VPlanPrinter
class VPSlotTracker
Detailed Description
VPlan models a candidate for vectorization, encoding various decisions take to produce efficient output IR, including which branches, basic-blocks and output IR instructions to generate, and their cost.
VPlan holds a Hierarchical-CFG of VPBasicBlocks and VPRegionBlocks rooted at an Entry VPBasicBlock.
Definition at line 4266 of file VPlan.h.
Constructor & Destructor Documentation
VPlan() [1/2]
VPlan::VPlan (Loop * L)
Construct a VPlan for L.
This will create VPIRBasicBlocks wrapping the original preheader and scalar header of L, to be used as entry and scalar header blocks of the new VPlan.
Definition at line 869 of file VPlan.cpp.
References createVPIRBasicBlock(), and setEntry().
VPlan() [2/2]
llvm::VPlan::VPlan (BasicBlock * ScalarHeaderBB) inline
Construct a VPlan with a new VPBasicBlock as entry, a VPIRBasicBlock wrapping ScalarHeaderBB and a trip count of TC.
Definition at line 4337 of file VPlan.h.
References createVPBasicBlock(), createVPIRBasicBlock(), and setEntry().
~VPlan()
VPlan::~VPlan ()
Definition at line 879 of file VPlan.cpp.
References llvm::dyn_cast(), getLiveIns(), and I.
Member Function Documentation
addVF()
void llvm::VPlan::addVF (ElementCount VF) inline
Definition at line 4455 of file VPlan.h.
cost()
InstructionCost VPlan::cost (ElementCount VF, VPCostContext & Ctx)
Return the cost of this plan.
Definition at line 1004 of file VPlan.cpp.
References llvm::any_of(), llvm::VPBlockUtils::blocksOnly(), llvm::VPBasicBlock::cost(), llvm::VPRegionBlock::cost(), getEntry(), llvm::InstructionCost::getInvalid(), getVectorLoopRegion(), llvm::InstructionCost::isValid(), and llvm::vp_depth_first_shallow().
createEmptyVPIRBasicBlock()
VPIRBasicBlock * VPlan::createEmptyVPIRBasicBlock (BasicBlock * IRBB)
Create a VPIRBasicBlock wrapping IRBB, but do not create VPIRInstructions wrapping the instructions in tIRBB.
The returned block is owned by the VPlan and deleted once the VPlan is destroyed.
Definition at line 1228 of file VPlan.cpp.
Referenced by llvm::VPIRBasicBlock::clone(), and createVPIRBasicBlock().
createLoopRegion()
VPRegionBlock * llvm::VPlan::createLoopRegion (const std::string & Name = "", VPBlockBase * Entry = nullptr, VPBlockBase * Exiting = nullptr) inline
Create a new loop region with Name and entry and exiting blocks set to Entry and Exiting respectively, if set.
The returned block is owned by the VPlan and deleted once the VPlan is destroyed.
Definition at line 4581 of file VPlan.h.
Referenced by createLoopRegion().
createReplicateRegion()
VPRegionBlock * llvm::VPlan::createReplicateRegion (VPBlockBase * Entry, VPBlockBase * Exiting, const std::string & Name = "") inline
Create a new replicate region with Entry, Exiting and Name.
The returned block is owned by the VPlan and deleted once the VPlan is destroyed.
Definition at line 4593 of file VPlan.h.
Referenced by createReplicateRegion().
createVPBasicBlock()
VPBasicBlock * llvm::VPlan::createVPBasicBlock (const Twine & Name, VPRecipeBase * Recipe = nullptr) inline
Create a new VPBasicBlock with Name and containing Recipe if present.
The returned block is owned by the VPlan and deleted once the VPlan is destroyed.
Definition at line 4571 of file VPlan.h.
Referenced by addInitialSkeleton(), llvm::VPBasicBlock::clone(), createReplicateRegion(), llvm::VPlanTransforms::expandBranchOnTwoConds(), llvm::VPlanTransforms::handleUncountableEarlyExit(), llvm::VPBasicBlock::splitAt(), and VPlan().
createVPIRBasicBlock()
VPIRBasicBlock * VPlan::createVPIRBasicBlock (BasicBlock * IRBB)
Create a VPIRBasicBlock from IRBB containing VPIRInstructions for all instructions in IRBB, except its terminator which is managed by the successors of the block in VPlan.
The returned block is owned by the VPlan and deleted once the VPlan is destroyed.
Definition at line 1234 of file VPlan.cpp.
References llvm::BasicBlock::begin(), llvm::VPIRInstruction::create(), createEmptyVPIRBasicBlock(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::BasicBlock::getTerminator(), I, and llvm::make_range().
Referenced by llvm::VPlanTransforms::attachCheckBlock(), duplicate(), VPlan(), and VPlan().
dump()
LLVM_DUMP_METHOD void VPlan::dump () const
Dump the plan to stderr (for debugging).
Definition at line 1123 of file VPlan.cpp.
References llvm::dbgs(), and print().
Referenced by execute().
duplicate()
VPlan * VPlan::duplicate ()
Clone the current VPlan, update all VPValues of the new VPlan and cloned recipes to refer to the clones, and return it.
Definition at line 1164 of file VPlan.cpp.
References assert(), llvm::cast(), cloneFrom(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), createVPIRBasicBlock(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::find_if(), llvm::VPIRBasicBlock::getIRBasicBlock(), getLiveIns(), llvm::VPBlockBase::getNumSuccessors(), getScalarHeader(), I, llvm::isa(), remapOperands(), llvm::seq(), and llvm::vp_depth_first_shallow().
Referenced by llvm::LoopVectorizePass::processLoop().
execute()
void VPlan::execute (VPTransformState * State)
Generate the IR code for this VPlan.
Generate the code inside the preheader and body of the vectorized loop.
Assumes a single pre-header basic-block was created for this. Introduce additional basic-blocks as needed, and fill them all.
Definition at line 916 of file VPlan.cpp.
References llvm::Block, llvm::cast(), llvm::dbgs(), llvm::DominatorTreeBase< BasicBlock, false >::Delete, llvm::DeleteDeadBlocks(), dump(), llvm::LoopBase< BlockT, LoopT >::getBlocksVector(), getExitBlocks(), llvm::vputils::getFirstLoopHeader(), getScalarHeader(), getScalarPreheader(), llvm::BasicBlock::getSingleSuccessor(), llvm::BasicBlock::getTerminator(), getUF(), llvm::VPBlockBase::hasPredecessors(), llvm::isa(), LLVM_DEBUG, llvm::make_early_inc_range(), and setName().
Referenced by llvm::LoopVectorizationPlanner::executePlan().
getBackedgeTakenCount()
VPValue * llvm::VPlan::getBackedgeTakenCount () const inline
Definition at line 4439 of file VPlan.h.
Referenced by llvm::vputils::isHeaderMask().
getConstantInt() [1/3]
VPIRValue * llvm::VPlan::getConstantInt (const APInt & Val) inline
Return a VPIRValue wrapping a ConstantInt with the given APInt value.
Definition at line 4539 of file VPlan.h.
References getContext(), and getOrAddLiveIn().
getConstantInt() [2/3]
VPIRValue * llvm::VPlan::getConstantInt (Type * Ty, uint64_t Val, bool IsSigned = false) inline
Return a VPIRValue wrapping a ConstantInt with the given type and value.
Definition at line 4527 of file VPlan.h.
References getOrAddLiveIn().
Referenced by llvm::VPlanTransforms::addExplicitVectorLength(), llvm::VPlanTransforms::addMinimumIterationCheck(), addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlanTransforms::canonicalizeEVLLoops(), cloneForLane(), llvm::VPBuilder::createElementCount(), llvm::VPlanTransforms::createInLoopReductionRecipes(), llvm::VPlanTransforms::createInterleaveGroups(), getConstantInt(), getFalse(), getTrue(), llvm::VPlanTransforms::materializeBackedgeTakenCount(), llvm::VPlanTransforms::materializeVectorTripCount(), llvm::VPlanTransforms::materializeVFAndVFxUF(), llvm::VPlanTransforms::narrowInterleaveGroups(), optimizeEarlyExitInductionUser(), optimizeLatchExitInductionUser(), optimizeMaskToEVL(), optimizeVectorInductionWidthForTCAndVFUF(), llvm::VPlanTransforms::replaceSymbolicStrides(), scalarizeVPWidenPointerInduction(), and tryToReplaceALMWithWideALM().
getConstantInt() [3/3]
VPIRValue * llvm::VPlan::getConstantInt (unsigned BitWidth, uint64_t Val, bool IsSigned = false) inline
Return a VPIRValue wrapping a ConstantInt with the given bitwidth and value.
Definition at line 4533 of file VPlan.h.
References llvm::BitWidth, and getConstantInt().
getContext()
LLVMContext & llvm::VPlan::getContext () const inline
Definition at line 4451 of file VPlan.h.
References llvm::BasicBlock::getContext(), llvm::VPIRBasicBlock::getIRBasicBlock(), and getScalarHeader().
Referenced by llvm::VPlanTransforms::addBranchWeightToMiddleTerminator(), llvm::VPlanTransforms::addExplicitVectorLength(), llvm::VPlanTransforms::addMinimumIterationCheck(), llvm::VPlanTransforms::addMinimumVectorEpilogueIterationCheck(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::attachCheckBlock(), llvm::VPlanTransforms::convertToConcreteRecipes(), expandVPWidenIntOrFpInduction(), getConstantInt(), optimizeVectorInductionWidthForTCAndVFUF(), simplifyKnownEVL(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), and tryToReplaceALMWithWideALM().
getEntry() [1/2]
VPBasicBlock * llvm::VPlan::getEntry () inline
Definition at line 4355 of file VPlan.h.
Referenced by addInitialSkeleton(), llvm::VPlanTransforms::addMinimumIterationCheck(), llvm::VPlanTransforms::addMinimumVectorEpilogueIterationCheck(), addReplicateRegions(), llvm::VPlanTransforms::canonicalizeEVLLoops(), connectEpilogueVectorLoop(), llvm::VPlanTransforms::convertToConcreteRecipes(), cost(), llvm::VPlanTransforms::createHeaderPhiRecipes(), llvm::VPlanTransforms::createLoopRegions(), llvm::VPlanTransforms::cse(), llvm::VPlanTransforms::dissolveLoopRegions(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), llvm::LoopVectorizationPlanner::executePlan(), llvm::VPlanTransforms::expandBranchOnTwoConds(), llvm::VPlanTransforms::expandSCEVs(), llvm::DomTreeNodeTraits< VPBlockBase >::getEntryNode(), llvm::vputils::getFirstLoopHeader(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), getVectorLoopRegion(), getVectorLoopRegion(), hasScalarTail(), llvm::VPlanTransforms::materializeBroadcasts(), llvm::VPlanTransforms::materializePacksAndUnpacks(), mergeBlocksIntoPredecessors(), mergeReplicateRegionsIntoSuccessors(), preparePlanForEpilogueVectorLoop(), preparePlanForMainVectorLoop(), print(), llvm::VPlanTransforms::removeBranchOnConst(), llvm::VPlanTransforms::removeDeadRecipes(), removeRedundantExpandSCEVRecipes(), llvm::VPlanTransforms::replaceSymbolicStrides(), llvm::VPlanTransforms::replicateByVF(), llvm::VPBlockBase::setPlan(), simplifyKnownEVL(), llvm::VPlanTransforms::simplifyRecipes(), sinkScalarOperands(), and llvm::VPlanTransforms::unrollByUF().
getEntry() [2/2]
const VPBasicBlock * llvm::VPlan::getEntry () const inline
Definition at line 4356 of file VPlan.h.
getExitBlock()
VPIRBasicBlock * VPlan::getExitBlock (BasicBlock * IRBB) const
Return the VPIRBasicBlock corresponding to IRBB.
IRBB must be an exit block.
Definition at line 901 of file VPlan.cpp.
References assert(), llvm::end(), llvm::find_if(), getExitBlocks(), and llvm::VPIRBasicBlock::getIRBasicBlock().
getExitBlocks()
ArrayRef< VPIRBasicBlock * > llvm::VPlan::getExitBlocks () const inline
Return an ArrayRef containing VPIRBasicBlocks wrapping the exit blocks of the original scalar loop.
Definition at line 4403 of file VPlan.h.
Referenced by calculateEarlyExitCost(), createExtractsForLiveOuts(), execute(), llvm::LoopVectorizationPlanner::executePlan(), getExitBlock(), llvm::VPlanTransforms::handleEarlyExits(), llvm::VPlanTransforms::introduceMasksAndLinearize(), and llvm::VPlanTransforms::optimizeInductionExitUsers().
getFalse()
VPIRValue * llvm::VPlan::getFalse () inline
Return a VPIRValue wrapping i1 false.
Definition at line 4524 of file VPlan.h.
References getConstantInt().
Referenced by llvm::VPlanTransforms::addMiddleCheck(), llvm::VPlanTransforms::addMinimumIterationCheck(), and simplifyRecipe().
getLiveIn()
VPIRValue * llvm::VPlan::getLiveIn (Value * V) const inline
Return the live-in VPIRValue for V, if there is one or nullptr otherwise.
Definition at line 4545 of file VPlan.h.
Referenced by createWidenInductionRecipe(), and llvm::VPlanTransforms::replaceSymbolicStrides().
getLiveIns()
auto llvm::VPlan::getLiveIns () const inline
Return the list of live-in VPValues available in the VPlan.
Definition at line 4548 of file VPlan.h.
Referenced by duplicate(), llvm::VPlanTransforms::materializeBroadcasts(), simplifyLiveInsWithSCEV(), and ~VPlan().
getMiddleBlock() [1/2]
VPBasicBlock * llvm::VPlan::getMiddleBlock () inline
Returns the 'middle' block of the plan, that is the block that selects whether to execute the scalar tail loop or the exit block from the loop latch.
If there is an early exit from the vector loop, the middle block conceptully has the early exit block as third successor, split accross 2 VPBBs. In that case, the second VPBB selects whether to execute the scalar tail loop or the exit block. If the scalar tail loop or exit block are known to always execute, the middle block may branch directly to that block. This function cannot be called once the vector loop region has been removed.
Definition at line 4380 of file VPlan.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::cast(), llvm::VPBlockBase::getSuccessors(), and getVectorLoopRegion().
Referenced by llvm::VPlanTransforms::addBranchWeightToMiddleTerminator(), llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), calculateEarlyExitCost(), llvm::VPlanTransforms::createInLoopReductionRecipes(), getMiddleBlock(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::introduceMasksAndLinearize(), isOutsideLoopWorkProfitable(), llvm::VPlanTransforms::materializeConstantVectorTripCount(), llvm::VPlanTransforms::optimizeInductionExitUsers(), preparePlanForMainVectorLoop(), llvm::LoopVectorizePass::processLoop(), and llvm::VPlanTransforms::updateScalarResumePhis().
getMiddleBlock() [2/2]
const VPBasicBlock * llvm::VPlan::getMiddleBlock () const inline
Definition at line 4389 of file VPlan.h.
References getMiddleBlock().
getName()
std::string VPlan::getName () const
Return a string with the name of the plan and the applicable VFs and UFs.
Definition at line 1093 of file VPlan.cpp.
References llvm::drop_begin().
Referenced by print().
getOrAddLiveIn() [1/2]
VPIRValue * llvm::VPlan::getOrAddLiveIn (Value * V) inline
Gets the live-in VPIRValue for V or adds a new live-in (if none exists yet) for V.
Definition at line 4505 of file VPlan.h.
References assert(), and llvm::isa().
Referenced by llvm::VPlanTransforms::addActiveLaneMask(), addCanonicalIVRecipes(), llvm::VPlanTransforms::addMinimumVectorEpilogueIterationCheck(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::attachCheckBlock(), llvm::VPlanTransforms::convertToConcreteRecipes(), llvm::VPlanTransforms::expandSCEVs(), getConstantInt(), getConstantInt(), getOrAddLiveIn(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), llvm::VPlanTransforms::narrowInterleaveGroups(), preparePlanForEpilogueVectorLoop(), simplifyLiveInsWithSCEV(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::tryToConvertVPInstructionsToVPRecipes(), and tryToReplaceALMWithWideALM().
getOrAddLiveIn() [2/2]
VPIRValue * llvm::VPlan::getOrAddLiveIn (VPIRValue * V) inline
Definition at line 4515 of file VPlan.h.
References assert(), and getOrAddLiveIn().
getOrCreateBackedgeTakenCount()
VPValue * llvm::VPlan::getOrCreateBackedgeTakenCount () inline
The backedge taken count of the original loop.
Definition at line 4434 of file VPlan.h.
Referenced by llvm::VPlanTransforms::materializeBackedgeTakenCount(), llvm::VPlanTransforms::materializeBroadcasts(), and optimizeVectorInductionWidthForTCAndVFUF().
getScalarHeader()
VPIRBasicBlock * llvm::VPlan::getScalarHeader () const inline
Return the VPIRBasicBlock wrapping the header of the scalar loop.
Definition at line 4399 of file VPlan.h.
Referenced by addInitialSkeleton(), llvm::VPlanTransforms::addMiddleCheck(), duplicate(), execute(), getContext(), getScalarPreheader(), llvm::VPlanTransforms::handleEarlyExits(), preparePlanForMainVectorLoop(), llvm::VPlanTransforms::replicateByVF(), simplifyRecipe(), and llvm::VPSlotTracker::VPSlotTracker().
getScalarPreheader()
VPBasicBlock * llvm::VPlan::getScalarPreheader () const inline
Return the VPBasicBlock for the preheader of the scalar loop.
Definition at line 4394 of file VPlan.h.
References llvm::cast(), and getScalarHeader().
Referenced by llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), llvm::VPlanTransforms::addMiddleCheck(), llvm::VPlanTransforms::attachCheckBlock(), connectEpilogueVectorLoop(), llvm::VPlanTransforms::createInLoopReductionRecipes(), execute(), llvm::LoopVectorizationPlanner::executePlan(), fixScalarResumeValuesFromBypass(), llvm::VPlanTransforms::handleMaxMinNumReductions(), hasScalarTail(), llvm::VPlanTransforms::materializeConstantVectorTripCount(), preparePlanForMainVectorLoop(), llvm::LoopVectorizationPlanner::updateLoopMetadataAndProfileInfo(), and llvm::VPlanTransforms::updateScalarResumePhis().
getTripCount()
VPValue * llvm::VPlan::getTripCount () const inline
The trip count of the original loop.
Definition at line 4413 of file VPlan.h.
References assert().
Referenced by llvm::VPlanTransforms::addActiveLaneMask(), llvm::VPlanTransforms::addExplicitVectorLength(), llvm::VPlanTransforms::addMiddleCheck(), llvm::VPlanTransforms::addMinimumIterationCheck(), addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::LoopVectorizationPlanner::executePlan(), llvm::VPlanTransforms::expandSCEVs(), isConditionTrueViaVFAndUF(), llvm::vputils::isHeaderMask(), llvm::VPlanTransforms::materializeBackedgeTakenCount(), llvm::VPlanTransforms::materializeConstantVectorTripCount(), llvm::VPlanTransforms::materializeVectorTripCount(), llvm::VPlanTransforms::materializeVFAndVFxUF(), optimizeVectorInductionWidthForTCAndVFUF(), preparePlanForEpilogueVectorLoop(), llvm::VPlanTransforms::replaceSymbolicStrides(), and simplifyBranchConditionForVFAndUF().
getTrue()
VPIRValue * llvm::VPlan::getTrue () inline
Return a VPIRValue wrapping i1 true.
Definition at line 4521 of file VPlan.h.
References getConstantInt().
Referenced by llvm::VPlanTransforms::addMiddleCheck(), llvm::VPlanTransforms::addMinimumIterationCheck(), optimizeMaskToEVL(), simplifyBranchConditionForVFAndUF(), and transformRecipestoEVLRecipes().
getUF()
unsigned llvm::VPlan::getUF () const inline
Definition at line 4483 of file VPlan.h.
References assert().
Referenced by llvm::VPlanTransforms::addBranchWeightToMiddleTerminator(), execute(), llvm::VPlanTransforms::materializeVFAndVFxUF(), llvm::VPlanTransforms::narrowInterleaveGroups(), llvm::VPlanTransforms::optimizeForVFAndUF(), and simplifyRecipe().
getVectorLoopRegion() [1/2]
VPRegionBlock * VPlan::getVectorLoopRegion ()
Returns the VPRegionBlock of the vector loop.
Definition at line 1022 of file VPlan.cpp.
References B(), llvm::dyn_cast(), getEntry(), nullptr, and llvm::vp_depth_first_shallow().
Referenced by llvm::VPlanTransforms::addActiveLaneMask(), llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), llvm::VPlanTransforms::addExplicitVectorLength(), addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::attachCheckBlock(), llvm::LoopVectorizationPlanner::buildVPlans(), llvm::calculateRegisterUsageForPlan(), llvm::VPlanTransforms::clearReductionWrapFlags(), collectComplementaryPredicatedMemOps(), llvm::collectEphemeralRecipesForVPlan(), llvm::LoopVectorizationPlanner::computeBestVF(), llvm::VPlanTransforms::convertToAbstractRecipes(), cost(), llvm::VPlanTransforms::createInLoopReductionRecipes(), llvm::VPlanTransforms::createLoopRegions(), createScalarIVSteps(), expandVPWidenIntOrFpInduction(), expandVPWidenPointerInduction(), findHeaderMask(), getMiddleBlock(), llvm::vputils::getRecipesForUncountableExit(), getVectorPreheader(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleMultiUseReductions(), hasReplicatorRegion(), llvm::VPlanTransforms::hoistInvariantLoads(), llvm::VPlanTransforms::introduceMasksAndLinearize(), isConditionTrueViaVFAndUF(), llvm::vputils::isHeaderMask(), legalizeAndOptimizeInductions(), licm(), llvm::VPlanTransforms::materializePacksAndUnpacks(), llvm::VPlanTransforms::narrowInterleaveGroups(), narrowToSingleScalarRecipes(), optimizeEarlyExitInductionUser(), optimizeVectorInductionWidthForTCAndVFUF(), planContainsAdditionalSimplifications(), preparePlanForEpilogueVectorLoop(), preparePlanForMainVectorLoop(), removeRedundantCanonicalIVs(), removeRedundantInductionCasts(), llvm::VPlanTransforms::replaceSymbolicStrides(), llvm::VPlanTransforms::replicateByVF(), scalarizeInstruction(), llvm::LoopVectorizationPlanner::selectInterleaveCount(), simplifyBlends(), simplifyBranchConditionForVFAndUF(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), llvm::VPlanTransforms::tryToConvertVPInstructionsToVPRecipes(), tryToReplaceALMWithWideALM(), llvm::VPlanTransforms::unrollByUF(), llvm::VPlanTransforms::updateScalarResumePhis(), llvm::VPInterleavedAccessInfo::VPInterleavedAccessInfo(), llvm::VPTypeAnalysis::VPTypeAnalysis(), and willGenerateVectors().
getVectorLoopRegion() [2/2]
const VPRegionBlock * VPlan::getVectorLoopRegion () const
Definition at line 1030 of file VPlan.cpp.
References B(), llvm::dyn_cast(), getEntry(), nullptr, and llvm::vp_depth_first_shallow().
getVectorPreheader()
VPBasicBlock * llvm::VPlan::getVectorPreheader () inline
Returns the preheader of the vector loop region, if one exists, or null otherwise.
Definition at line 4360 of file VPlan.h.
References llvm::cast(), llvm::VPBlockBase::getSinglePredecessor(), and getVectorLoopRegion().
Referenced by addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlanTransforms::attachCheckBlock(), llvm::LoopVectorizationPlanner::executePlan(), expandVPWidenIntOrFpInduction(), llvm::VPlanTransforms::hoistInvariantLoads(), licm(), llvm::VPlanTransforms::materializeBroadcasts(), llvm::VPlanTransforms::narrowInterleaveGroups(), optimizeVectorInductionWidthForTCAndVFUF(), planContainsAdditionalSimplifications(), llvm::LoopVectorizePass::processLoop(), simplifyBranchConditionForVFAndUF(), and llvm::VPlanTransforms::truncateToMinimalBitwidths().
getVectorTripCount()
VPSymbolicValue & llvm::VPlan::getVectorTripCount () inline
The vector trip count.
Definition at line 4442 of file VPlan.h.
Referenced by addCanonicalIVRecipes(), llvm::VPlanTransforms::addMiddleCheck(), llvm::calculateRegisterUsageForPlan(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::VPlanTransforms::handleMaxMinNumReductions(), isConditionTrueViaVFAndUF(), llvm::VPlanTransforms::materializeConstantVectorTripCount(), llvm::VPlanTransforms::materializeVectorTripCount(), preparePlanForMainVectorLoop(), simplifyBranchConditionForVFAndUF(), and llvm::VPlanTransforms::updateScalarResumePhis().
getVF() [1/2]
VPValue & llvm::VPlan::getVF () inline
Returns the VF of the vector loop region.
Definition at line 4445 of file VPlan.h.
Referenced by llvm::VPlanTransforms::createInterleaveGroups(), createScalarIVSteps(), createWidenInductionRecipe(), llvm::vputils::isHeaderMask(), llvm::VPlanTransforms::materializeVFAndVFxUF(), llvm::VPlanTransforms::narrowInterleaveGroups(), optimizeMaskToEVL(), transformRecipestoEVLRecipes(), and llvm::VPlanTransforms::tryToConvertVPInstructionsToVPRecipes().
getVF() [2/2]
const VPValue & llvm::VPlan::getVF () const inline
Definition at line 4446 of file VPlan.h.
getVFxUF()
VPValue & llvm::VPlan::getVFxUF () inline
Returns VF * UF of the vector loop region.
Definition at line 4449 of file VPlan.h.
Referenced by addCanonicalIVRecipes(), llvm::VPlanTransforms::canonicalizeEVLLoops(), createWidenInductionRecipe(), llvm::VPlanTransforms::materializeVectorTripCount(), llvm::VPlanTransforms::materializeVFAndVFxUF(), and transformRecipestoEVLRecipes().
hasEarlyExit()
bool llvm::VPlan::hasEarlyExit () const inline
Returns true if the VPlan is based on a loop with an early exit.
That is the case if the VPlan has either more than one exit block or a single exit block with multiple predecessors (one for the exit via the latch and one via the other early exit).
Definition at line 4615 of file VPlan.h.
References llvm::count_if(), and llvm::VPBlockBase::hasPredecessors().
Referenced by llvm::LoopVectorizationPlanner::executePlan(), and llvm::LoopVectorizationPlanner::selectInterleaveCount().
hasScalableVF()
bool llvm::VPlan::hasScalableVF () const inline
Definition at line 4464 of file VPlan.h.
References llvm::any_of().
Referenced by llvm::VPlanTransforms::convertToConcreteRecipes(), expandVPWidenPointerInduction(), and legalizeAndOptimizeInductions().
hasScalarTail()
bool llvm::VPlan::hasScalarTail () const inline
Returns true if the scalar tail may execute after the vector loop.
Note that this relies on unneeded branches to the scalar tail loop being removed.
Definition at line 4625 of file VPlan.h.
References getEntry(), getScalarPreheader(), llvm::VPBlockBase::getSinglePredecessor(), and llvm::VPBlockBase::hasPredecessors().
Referenced by llvm::VPlanTransforms::handleMaxMinNumReductions(), and llvm::VPlanTransforms::materializeConstantVectorTripCount().
hasScalarVFOnly()
bool llvm::VPlan::hasScalarVFOnly () const inline
Definition at line 4474 of file VPlan.h.
References assert(), llvm::ElementCount::getFixed(), and hasVF().
Referenced by llvm::VPlanTransforms::addExplicitVectorLength(), llvm::vputils::isHeaderMask(), legalizeAndOptimizeInductions(), llvm::VPlanTransforms::materializeBroadcasts(), llvm::VPlanTransforms::materializePacksAndUnpacks(), narrowToSingleScalarRecipes(), simplifyRecipe(), sinkScalarOperands(), and llvm::VPlanTransforms::truncateToMinimalBitwidths().
hasUF()
bool llvm::VPlan::hasUF (unsigned UF) const inline
Definition at line 4481 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::executePlan(), llvm::VPlanTransforms::materializeConstantVectorTripCount(), llvm::VPlanTransforms::optimizeForVFAndUF(), and setUF().
hasVF()
bool llvm::VPlan::hasVF (ElementCount VF) const inline
Definition at line 4463 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::executePlan(), hasScalarVFOnly(), llvm::VPlanTransforms::materializeConstantVectorTripCount(), llvm::VPlanTransforms::optimizeForVFAndUF(), and setVF().
isExitBlock()
bool VPlan::isExitBlock (VPBlockBase * VPBB)
Returns true if VPBB is an exit block.
Definition at line 909 of file VPlan.cpp.
References llvm::is_contained().
isUnrolled()
bool llvm::VPlan::isUnrolled () const inline
Returns true if the VPlan already has been unrolled, i.e.
it has a single concrete UF.
Definition at line 4496 of file VPlan.h.
Referenced by simplifyRecipe().
print()
LLVM_DUMP_METHOD void VPlan::print (raw_ostream & O) const
Print this VPlan to O.
Definition at line 1076 of file VPlan.cpp.
References llvm::Block, getEntry(), getName(), printLiveIns(), and VPSlotTracker.
Referenced by dump(), llvm::operator<<(), and llvm::LoopVectorizationPlanner::printPlans().
printDOT()
LLVM_DUMP_METHOD void VPlan::printDOT (raw_ostream & O) const
Print this VPlan in DOT format to O.
Definition at line 1117 of file VPlan.cpp.
References Printer, and VPlanPrinter.
Referenced by llvm::LoopVectorizationPlanner::printPlans().
printLiveIns()
void VPlan::printLiveIns (raw_ostream & O) const
Print the live-ins of this VPlan to O.
Definition at line 1038 of file VPlan.cpp.
References llvm::isa(), and VPSlotTracker.
Referenced by print().
resetTripCount()
void llvm::VPlan::resetTripCount (VPValue * NewTripCount) inline
Resets the trip count for the VPlan.
The caller must make sure all uses of the original trip count have been replaced.
Definition at line 4427 of file VPlan.h.
References assert(), and llvm::VPValue::getNumUsers().
Referenced by llvm::VPlanTransforms::expandSCEVs(), preparePlanForEpilogueVectorLoop(), and llvm::VPlanTransforms::replaceSymbolicStrides().
setEntry()
void llvm::VPlan::setEntry (VPBasicBlock * VPBB) inline
Definition at line 4344 of file VPlan.h.
References llvm::VPBlockBase::setPlan().
Referenced by VPlan(), and VPlan().
setName()
void llvm::VPlan::setName (const Twine & newName) inline
Definition at line 4501 of file VPlan.h.
References llvm::Twine::str().
Referenced by execute().
setTripCount()
void llvm::VPlan::setTripCount (VPValue * NewTripCount) inline
Set the trip count assuming it is currently null; if it is not - use resetTripCount().
Definition at line 4420 of file VPlan.h.
References assert().
Referenced by addInitialSkeleton().
setUF()
void llvm::VPlan::setUF (unsigned UF) inline
Definition at line 4488 of file VPlan.h.
References assert(), and hasUF().
Referenced by llvm::VPlanTransforms::addExplicitVectorLength(), and llvm::VPlanTransforms::unrollByUF().
setVF()
void llvm::VPlan::setVF (ElementCount VF) inline
Definition at line 4457 of file VPlan.h.
References assert(), and hasVF().
Referenced by llvm::VPlanTransforms::optimizeForVFAndUF().
vectorFactors()
iterator_range< SmallSetVector< ElementCount, 2 >::iterator > llvm::VPlan::vectorFactors () const inline
Returns an iterator range over all VFs of the plan.
Definition at line 4470 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::computeBestVF().
Friends And Related Symbol Documentation
VPlanPrinter
friend class VPlanPrinter friend
Definition at line 4267 of file VPlan.h.
References VPlanPrinter.
Referenced by printDOT(), and VPlanPrinter.
VPSlotTracker
friend class VPSlotTracker friend
Definition at line 4268 of file VPlan.h.
References VPSlotTracker.
Referenced by print(), printLiveIns(), and VPSlotTracker.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp