LLVM: llvm::object::Archive::symbol_iterator Class Reference
llvm::object::Archive::symbol_iterator Class Reference
#include "llvm/Object/Archive.h"
Public Member Functions
symbol_iterator (const Symbol &s)
const Symbol * operator-> () const
const Symbol & operator* () const
bool operator== (const symbol_iterator &other) const
bool operator!= (const symbol_iterator &other) const
symbol_iterator & operator++ ()
Detailed Description
Definition at line 311 of file Archive.h.
Constructor & Destructor Documentation
symbol_iterator()
llvm::object::Archive::symbol_iterator::symbol_iterator (const Symbol & s) inline
Definition at line 315 of file Archive.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
bool llvm::object::Archive::symbol_iterator::operator!= (const symbol_iterator & other) const inline
Definition at line 324 of file Archive.h.
References symbol_iterator().
operator*()
const Symbol & llvm::object::Archive::symbol_iterator::operator* () const inline
Definition at line 318 of file Archive.h.
operator++()
symbol_iterator & llvm::object::Archive::symbol_iterator::operator++ () inline
Definition at line 328 of file Archive.h.
References symbol_iterator().
operator->()
const Symbol * llvm::object::Archive::symbol_iterator::operator-> () const inline
Definition at line 317 of file Archive.h.
operator==()
bool llvm::object::Archive::symbol_iterator::operator== (const symbol_iterator & other) const inline
Definition at line 320 of file Archive.h.
References symbol_iterator().
The documentation for this class was generated from the following file:
include/llvm/Object/Archive.h