LLVM: RegBankSelectHelper Class Reference
RegBankSelectHelper Class Reference
Public Member Functions
RegBankSelectHelper (MachineIRBuilder &B, AMDGPU::IntrinsicLaneMaskAnalyzer &ILMA, const MachineUniformityInfo &MUI, const SIRegisterInfo &TRI, const RegisterBankInfo &RBI)
bool isTemporalDivergenceCopy (Register Reg)
const RegisterBank * getRegBankToAssign (Register Reg)
void reAssignRegBankOnDef (MachineInstr &MI, MachineOperand &DefOP, const RegisterBank *RB)
void constrainRegBankUse (MachineInstr &MI, MachineOperand &UseOP, const RegisterBank *RB)
Detailed Description
Definition at line 78 of file AMDGPURegBankSelect.cpp.
Constructor & Destructor Documentation
RegBankSelectHelper()
RegBankSelectHelper::RegBankSelectHelper (MachineIRBuilder & B, AMDGPU::IntrinsicLaneMaskAnalyzer & ILMA, const MachineUniformityInfo & MUI, const SIRegisterInfo & TRI, const RegisterBankInfo & RBI) inline
Definition at line 89 of file AMDGPURegBankSelect.cpp.
Member Function Documentation
constrainRegBankUse()
void RegBankSelectHelper::constrainRegBankUse (MachineInstr & MI, MachineOperand & UseOP, const RegisterBank * RB) inline
Definition at line 168 of file AMDGPURegBankSelect.cpp.
References DefMI, llvm::MachineOperand::getReg(), MI, llvm::MachineOperand::setReg(), and llvm::MachineBasicBlock::SkipPHIsAndLabels().
getRegBankToAssign()
const RegisterBank * RegBankSelectHelper::getRegBankToAssign (Register Reg) inline
Definition at line 112 of file AMDGPURegBankSelect.cpp.
References isTemporalDivergenceCopy(), and llvm::LLT::scalar().
isTemporalDivergenceCopy()
bool RegBankSelectHelper::isTemporalDivergenceCopy (Register Reg) inline
Definition at line 104 of file AMDGPURegBankSelect.cpp.
References MI.
Referenced by getRegBankToAssign().
reAssignRegBankOnDef()
void RegBankSelectHelper::reAssignRegBankOnDef (MachineInstr & MI, MachineOperand & DefOP, const RegisterBank * RB) inline
Definition at line 129 of file AMDGPURegBankSelect.cpp.
References llvm::MachineOperand::getReg(), llvm::make_early_inc_range(), MBB, MI, llvm::MachineOperand::setReg(), and UseMI.
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPURegBankSelect.cpp