LLVM: llvm::orc::COFFImportFileScanner Class Reference
llvm::orc::COFFImportFileScanner Class Reference
#include "llvm/ExecutionEngine/Orc/COFF.h"
Public Member Functions
COFFImportFileScanner (std::set< std::string > &ImportedDynamicLibraries)
LLVM_ABI Expected< bool > operator() (object::Archive &A, MemoryBufferRef MemberBuf, size_t Index) const
Detailed Description
Definition at line 31 of file COFF.h.
Constructor & Destructor Documentation
COFFImportFileScanner()
llvm::orc::COFFImportFileScanner::COFFImportFileScanner (std::set< std::string > & ImportedDynamicLibraries) inline
Definition at line 33 of file COFF.h.
Member Function Documentation
operator()()
Expected< bool > llvm::orc::COFFImportFileScanner::operator() (object::Archive & A, MemoryBufferRef MemberBuf, size_t Index) const
Definition at line 16 of file COFF.cpp.
References A(), llvm::Bin, llvm::consumeError(), and llvm::object::createBinary().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/COFF.h
lib/ExecutionEngine/Orc/COFF.cpp