LLVM: llvm::MCPseudoProbeTable Class Reference
llvm::MCPseudoProbeTable Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCPseudoProbeSections & getProbeSections ()
Static Public Member Functions
static LLVM_ABI void emit (MCObjectStreamer *MCOS)
Static Public Attributes
static int DdgPrintIndent = 0
Detailed Description
Definition at line 369 of file MCPseudoProbe.h.
Member Function Documentation
emit()
void MCPseudoProbeTable::emit (MCObjectStreamer * MCOS) static
Definition at line 254 of file MCPseudoProbe.cpp.
References DdgPrintIndent, llvm::MCStreamer::getContext(), llvm::MCContext::getMCPseudoProbeTable(), getProbeSections(), and LLVM_DEBUG.
Referenced by llvm::MCObjectStreamer::finishImpl().
getProbeSections()
MCPseudoProbeSections & llvm::MCPseudoProbeTable::getProbeSections () inline
Definition at line 381 of file MCPseudoProbe.h.
Referenced by emit().
Member Data Documentation
DdgPrintIndent
int MCPseudoProbeTable::DdgPrintIndent = 0 static
Definition at line 384 of file MCPseudoProbe.h.
Referenced by llvm::MCPseudoProbe::emit(), llvm::MCPseudoProbeInlineTree::emit(), and emit().
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp