LLVM: llvm::orc::DylibResolverImpl Class Reference
llvm::orc::DylibResolverImpl Class Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h"
Public Member Functions
DylibResolverImpl (DylibSubstitutor Substitutor, DylibPathValidator &Validator, std::vector< SearchPathResolver > Resolvers)
std::optional< std::string > resolve (StringRef Stem, bool VariateLibStem=false) const
Detailed Description
Definition at line 336 of file LibraryScanner.h.
Constructor & Destructor Documentation
DylibResolverImpl()
llvm::orc::DylibResolverImpl::DylibResolverImpl (DylibSubstitutor Substitutor, DylibPathValidator & Validator, std::vector< SearchPathResolver > Resolvers) inline
Definition at line 338 of file LibraryScanner.h.
References llvm::move().
Member Function Documentation
resolve()
std::optional< std::string > llvm::orc::DylibResolverImpl::resolve (StringRef Stem, bool VariateLibStem = false) const
Definition at line 376 of file LibraryScanner.cpp.
References llvm::dbgs(), llvm::sys::path::is_absolute(), LLVM_DEBUG, llvm::orc::Result, and llvm::StringRef::starts_with_insensitive().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h
lib/ExecutionEngine/Orc/TargetProcess/LibraryScanner.cpp