LLVM: llvm::TypeBasedAAResult Class Reference
llvm::TypeBasedAAResult Class Reference
A simple AA result that uses TBAA metadata to answer queries.
#include "llvm/Analysis/TypeBasedAliasAnalysis.h"
Public Member Functions
TypeBasedAAResult (bool UsingTypeSanitizer)
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Handle invalidation events from the new pass manager.
LLVM_ABI AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI, const Instruction *CtxI)
LLVM_ABI AliasResult aliasErrno (const MemoryLocation &Loc, const Module *M)
LLVM_ABI ModRefInfo getModRefInfoMask (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool IgnoreLocals)
LLVM_ABI MemoryEffects getMemoryEffects (const CallBase *Call, AAQueryInfo &AAQI)
LLVM_ABI MemoryEffects getMemoryEffects (const Function *F)
LLVM_ABI ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
LLVM_ABI ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Public Member Functions inherited from llvm::AAResultBase
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI, const Instruction *I)
AliasResult aliasErrno (const MemoryLocation &Loc, const Module *M)
ModRefInfo getModRefInfoMask (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool IgnoreLocals)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
MemoryEffects getMemoryEffects (const CallBase *Call, AAQueryInfo &AAQI)
MemoryEffects getMemoryEffects (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)=default
AAResultBase (AAResultBase &&Arg)
Detailed Description
A simple AA result that uses TBAA metadata to answer queries.
Definition at line 32 of file TypeBasedAliasAnalysis.h.
Constructor & Destructor Documentation
TypeBasedAAResult()
llvm::TypeBasedAAResult::TypeBasedAAResult (bool UsingTypeSanitizer) inline
Definition at line 39 of file TypeBasedAliasAnalysis.h.
Member Function Documentation
alias()
AliasResult TypeBasedAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI, const Instruction * CtxI)
Definition at line 376 of file TypeBasedAliasAnalysis.cpp.
References llvm::MemoryLocation::AATags, llvm::AliasResult::MayAlias, llvm::AliasResult::NoAlias, and llvm::AAMDNodes::TBAA.
aliasErrno()
AliasResult TypeBasedAAResult::aliasErrno (const MemoryLocation & Loc, const Module * M)
Definition at line 389 of file TypeBasedAliasAnalysis.cpp.
References llvm::any_of(), llvm::AliasResult::MayAlias, N, and llvm::AliasResult::NoAlias.
getMemoryEffects() [1/2]
MemoryEffects TypeBasedAAResult::getMemoryEffects (const CallBase * Call, AAQueryInfo & AAQI)
Definition at line 427 of file TypeBasedAliasAnalysis.cpp.
References isStructPathTBAA(), llvm::MemoryEffectsBase< IRMemLocation >::none(), and llvm::MemoryEffectsBase< IRMemLocation >::unknown().
getMemoryEffects() [2/2]
MemoryEffects TypeBasedAAResult::getMemoryEffects (const Function * F)
Definition at line 441 of file TypeBasedAliasAnalysis.cpp.
References F, and llvm::MemoryEffectsBase< IRMemLocation >::unknown().
getModRefInfo() [1/2]
ModRefInfo TypeBasedAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Definition at line 446 of file TypeBasedAliasAnalysis.cpp.
References llvm::ModRef, and llvm::NoModRef.
getModRefInfo() [2/2]
ModRefInfo TypeBasedAAResult::getModRefInfo (const CallBase * Call1, const CallBase * Call2, AAQueryInfo & AAQI)
Definition at line 460 of file TypeBasedAliasAnalysis.cpp.
References llvm::Instruction::getMetadata(), llvm::M1(), llvm::ModRef, and llvm::NoModRef.
getModRefInfoMask()
ModRefInfo TypeBasedAAResult::getModRefInfoMask (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool IgnoreLocals)
Definition at line 408 of file TypeBasedAliasAnalysis.cpp.
References isStructPathTBAA(), llvm::ModRef, and llvm::NoModRef.
invalidate()
bool llvm::TypeBasedAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 45 of file TypeBasedAliasAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/TypeBasedAliasAnalysis.h
lib/Analysis/TypeBasedAliasAnalysis.cpp