LLVM: llvm::XtensaRegisterInfo Class Reference
llvm::XtensaRegisterInfo Class Reference
#include "Target/Xtensa/XtensaRegisterInfo.h"
Public Member Functions
XtensaRegisterInfo (const XtensaSubtarget &STI)
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &) const override
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const override
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
Public Attributes
const XtensaSubtarget & Subtarget
Detailed Description
Definition at line 27 of file XtensaRegisterInfo.h.
Constructor & Destructor Documentation
XtensaRegisterInfo()
XtensaRegisterInfo::XtensaRegisterInfo (const XtensaSubtarget & STI)
Definition at line 32 of file XtensaRegisterInfo.cpp.
References Subtarget.
Member Function Documentation
eliminateFrameIndex()
bool XtensaRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 65 of file XtensaRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getStackSize(), II, llvm::Xtensa::isValidAddrOffsetForOpcode(), llvm::RegState::Kill, MBB, MI, llvm::Offset, and TII.
getCalleeSavedRegs()
const uint16_t * XtensaRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = 0) const override
Definition at line 36 of file XtensaRegisterInfo.cpp.
References Subtarget.
getCallPreservedMask()
const uint32_t * XtensaRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const override
Definition at line 42 of file XtensaRegisterInfo.cpp.
References Subtarget.
getFrameRegister()
Register XtensaRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 134 of file XtensaRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), and Subtarget.
Referenced by eliminateFrameIndex(), and getReservedRegs().
getReservedRegs()
BitVector XtensaRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 47 of file XtensaRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), getFrameRegister(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::Reserved, and Subtarget.
requiresFrameIndexScavenging()
bool llvm::XtensaRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Definition at line 37 of file XtensaRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::XtensaRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Definition at line 33 of file XtensaRegisterInfo.h.
trackLivenessAfterRegAlloc()
bool llvm::XtensaRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction &) const inline override
Definition at line 41 of file XtensaRegisterInfo.h.
Member Data Documentation
Subtarget
const XtensaSubtarget& llvm::XtensaRegisterInfo::Subtarget
Definition at line 29 of file XtensaRegisterInfo.h.
Referenced by getCalleeSavedRegs(), getCallPreservedMask(), getFrameRegister(), getReservedRegs(), and XtensaRegisterInfo().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaRegisterInfo.h
lib/Target/Xtensa/XtensaRegisterInfo.cpp