LLVM: llvm::cas::ondisk::InternalRefArrayRef::iterator Class Reference
llvm::cas::ondisk::InternalRefArrayRef::iterator Class Reference
#include "llvm/CAS/OnDiskGraphDB.h"
Public Member Functions
bool operator== (const iterator &RHS) const
InternalRef operator* () const
bool operator< (const iterator &RHS) const
ptrdiff_t operator- (const iterator &RHS) const
iterator & operator+= (ptrdiff_t N)
iterator & operator-= (ptrdiff_t N)
InternalRef operator[] (ptrdiff_t N) const
iterator ()=default
uint64_t getOpaqueData () const
Public Member Functions inherited from llvm::iterator_facade_base< iterator, std::random_access_iterator_tag, const InternalRef >
iterator operator+ (std::ptrdiff_t n) const
iterator operator- (std::ptrdiff_t n) const
iterator & operator++ ()
iterator & operator-- ()
bool operator!= (const iterator &RHS) const
bool operator> (const iterator &RHS) const
bool operator<= (const iterator &RHS) const
bool operator>= (const iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Static Public Member Functions
static iterator fromOpaqueData (uint64_t Opaque)
Friends
class InternalRefArrayRef
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< iterator, std::random_access_iterator_tag, const InternalRef >
enum
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Definition at line 77 of file OnDiskGraphDB.h.
Constructor & Destructor Documentation
iterator()
llvm::cas::ondisk::InternalRefArrayRef::iterator::iterator () default
Referenced by fromOpaqueData(), operator+=(), operator-(), operator-=(), operator<(), and operator==().
Member Function Documentation
fromOpaqueData()
iterator llvm::cas::ondisk::InternalRefArrayRef::iterator::fromOpaqueData (uint64_t Opaque) inline static
Definition at line 121 of file OnDiskGraphDB.h.
References iterator().
getOpaqueData()
uint64_t llvm::cas::ondisk::InternalRefArrayRef::iterator::getOpaqueData () const inline
Definition at line 119 of file OnDiskGraphDB.h.
operator*()
InternalRef llvm::cas::ondisk::InternalRefArrayRef::iterator::operator* () const inline
Definition at line 82 of file OnDiskGraphDB.h.
References llvm::cast(), llvm::dyn_cast(), and llvm::Ref.
operator+=()
iterator & llvm::cas::ondisk::InternalRefArrayRef::iterator::operator+= (ptrdiff_t N) inline
Definition at line 101 of file OnDiskGraphDB.h.
References llvm::cast(), llvm::dyn_cast(), iterator(), N, and llvm::Ref.
operator-()
ptrdiff_t llvm::cas::ondisk::InternalRefArrayRef::iterator::operator- (const iterator & RHS) const inline
Definition at line 94 of file OnDiskGraphDB.h.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::isa(), iterator(), llvm::Ref, and RHS.
operator-=()
iterator & llvm::cas::ondisk::InternalRefArrayRef::iterator::operator-= (ptrdiff_t N) inline
Definition at line 108 of file OnDiskGraphDB.h.
References llvm::cast(), llvm::dyn_cast(), iterator(), N, and llvm::Ref.
operator<()
bool llvm::cas::ondisk::InternalRefArrayRef::iterator::operator< (const iterator & RHS) const inline
Definition at line 87 of file OnDiskGraphDB.h.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::isa(), iterator(), llvm::Ref, and RHS.
operator==()
bool llvm::cas::ondisk::InternalRefArrayRef::iterator::operator== (const iterator & RHS) const inline
Definition at line 81 of file OnDiskGraphDB.h.
References iterator(), and RHS.
operator[]()
InternalRef llvm::cas::ondisk::InternalRefArrayRef::iterator::operator[] (ptrdiff_t N) const inline
Definition at line 115 of file OnDiskGraphDB.h.
References N, and llvm::iterator_facade_base< iterator, std::random_access_iterator_tag, const InternalRef >::operator+().
Friends And Related Symbol Documentation
InternalRefArrayRef
friend class InternalRefArrayRef friend
Definition at line 129 of file OnDiskGraphDB.h.
References InternalRefArrayRef.
Referenced by InternalRefArrayRef.
The documentation for this class was generated from the following file:
include/llvm/CAS/OnDiskGraphDB.h