LLVM: llvm::SROAPass Class Reference
llvm::SROAPass Class Reference
#include "llvm/Transforms/Scalar/SROA.h"
Public Member Functions
SROAPass (SROAOptions PreserveCFG)
If PreserveCFG is set, then the pass is not allowed to modify CFG in any way, even if it would update CFG analyses.
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Run the pass over the function.
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< SROAPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SROAPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 26 of file SROA.h.
Constructor & Destructor Documentation
SROAPass()
SROAPass::SROAPass (SROAOptions PreserveCFG)
If PreserveCFG is set, then the pass is not allowed to modify CFG in any way, even if it would update CFG analyses.
Definition at line 6190 of file SROA.cpp.
Member Function Documentation
printPipeline()
void SROAPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 6182 of file SROA.cpp.
References llvm::PreserveCFG, and printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses SROAPass::run (Function & F, FunctionAnalysisManager & AM)
Run the pass over the function.
Definition at line 6167 of file SROA.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/SROA.h
lib/Transforms/Scalar/SROA.cpp