LLVM: llvm::MergedLoadStoreMotionPass Class Reference
llvm::MergedLoadStoreMotionPass Class Reference
#include "llvm/Transforms/Scalar/MergedLoadStoreMotion.h"
Public Member Functions
MergedLoadStoreMotionPass ()
MergedLoadStoreMotionPass (const MergedLoadStoreMotionOptions &PassOptions)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< MergedLoadStoreMotionPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MergedLoadStoreMotionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 42 of file MergedLoadStoreMotion.h.
Constructor & Destructor Documentation
MergedLoadStoreMotionPass() [1/2]
llvm::MergedLoadStoreMotionPass::MergedLoadStoreMotionPass () inline
Definition at line 47 of file MergedLoadStoreMotion.h.
References MergedLoadStoreMotionPass().
Referenced by MergedLoadStoreMotionPass().
MergedLoadStoreMotionPass() [2/2]
llvm::MergedLoadStoreMotionPass::MergedLoadStoreMotionPass (const MergedLoadStoreMotionOptions & PassOptions) inline
Definition at line 49 of file MergedLoadStoreMotion.h.
Member Function Documentation
printPipeline()
void MergedLoadStoreMotionPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 395 of file MergedLoadStoreMotion.cpp.
References printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses MergedLoadStoreMotionPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 383 of file MergedLoadStoreMotion.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/MergedLoadStoreMotion.h
lib/Transforms/Scalar/MergedLoadStoreMotion.cpp