LLVM: llvm::codeview::DefRangeRegisterRelSym Class Reference
llvm::codeview::DefRangeRegisterRelSym Class Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Types
enum : uint16_t { IsSubfieldFlag = 1 , OffsetInParentShift = 4 }
Public Member Functions
DefRangeRegisterRelSym (SymbolRecordKind Kind)
DefRangeRegisterRelSym (uint32_t RecordOffset)
bool hasSpilledUDTMember () const
uint16_t offsetInParent () const
uint32_t getRelocationOffset () const
Public Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecordKind getKind () const
Public Attributes
DefRangeRegisterRelHeader Hdr
LocalVariableAddrRange Range
std::vector< LocalVariableAddrGap > Gaps
uint32_t RecordOffset = 0
Public Attributes inherited from llvm::codeview::SymbolRecord
SymbolRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::SymbolRecord
SymbolRecord (SymbolRecordKind Kind)
Detailed Description
Definition at line 590 of file SymbolRecord.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint16_t
Enumerator
IsSubfieldFlag
OffsetInParentShift
Definition at line 601 of file SymbolRecord.h.
Constructor & Destructor Documentation
DefRangeRegisterRelSym() [1/2]
llvm::codeview::DefRangeRegisterRelSym::DefRangeRegisterRelSym (SymbolRecordKind Kind) inline explicit
Definition at line 592 of file SymbolRecord.h.
References llvm::codeview::SymbolRecord::Kind, and llvm::codeview::SymbolRecord::SymbolRecord().
Referenced by DefRangeRegisterRelSym().
DefRangeRegisterRelSym() [2/2]
llvm::codeview::DefRangeRegisterRelSym::DefRangeRegisterRelSym (uint32_t RecordOffset) inline explicit
Definition at line 593 of file SymbolRecord.h.
References DefRangeRegisterRelSym(), RecordOffset, and llvm::codeview::SymbolRecord::SymbolRecord().
Member Function Documentation
getRelocationOffset()
uint32_t llvm::codeview::DefRangeRegisterRelSym::getRelocationOffset () const inline
Definition at line 609 of file SymbolRecord.h.
References RecordOffset.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
hasSpilledUDTMember()
bool llvm::codeview::DefRangeRegisterRelSym::hasSpilledUDTMember () const inline
Definition at line 606 of file SymbolRecord.h.
References Hdr, and IsSubfieldFlag.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
offsetInParent()
uint16_t llvm::codeview::DefRangeRegisterRelSym::offsetInParent () const inline
Definition at line 607 of file SymbolRecord.h.
References Hdr, and OffsetInParentShift.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Member Data Documentation
Gaps
std::vector<LocalVariableAddrGap> llvm::codeview::DefRangeRegisterRelSym::Gaps
Definition at line 613 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Hdr
DefRangeRegisterRelHeader llvm::codeview::DefRangeRegisterRelSym::Hdr
Definition at line 611 of file SymbolRecord.h.
Referenced by hasSpilledUDTMember(), offsetInParent(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
Range
LocalVariableAddrRange llvm::codeview::DefRangeRegisterRelSym::Range
Definition at line 612 of file SymbolRecord.h.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
RecordOffset
uint32_t llvm::codeview::DefRangeRegisterRelSym::RecordOffset = 0
Definition at line 615 of file SymbolRecord.h.
Referenced by DefRangeRegisterRelSym(), and getRelocationOffset().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h