LLVM: llvm::RuntimeDyldChecker::MemoryRegionInfo Class Reference
llvm::RuntimeDyldChecker::MemoryRegionInfo Class Reference
#include "llvm/ExecutionEngine/RuntimeDyldChecker.h"
Public Member Functions
MemoryRegionInfo ()
MemoryRegionInfo (ArrayRef< char > Content, JITTargetAddress TargetAddress, TargetFlagsType TargetFlags)
Constructor for symbols/sections with content and TargetFlag.
MemoryRegionInfo (uint64_t Size, JITTargetAddress TargetAddress)
Constructor for zero-fill symbols/sections.
bool isZeroFill () const
Returns true if this is a zero-fill symbol/section.
void setContent (ArrayRef< char > Content)
Set the content for this memory region.
void setZeroFill (uint64_t Size)
Set a zero-fill length for this memory region.
ArrayRef< char > getContent () const
Returns the content for this section if there is any.
uint64_t getZeroFillLength () const
Returns the zero-fill length for this section.
void setTargetAddress (JITTargetAddress TargetAddress)
Set the target address for this region.
JITTargetAddress getTargetAddress () const
Return the target address for this region.
TargetFlagsType getTargetFlags () const
Get the target flags for this Symbol.
void setTargetFlags (TargetFlagsType Flags)
Set the target flags for this Symbol.
Detailed Description
Definition at line 83 of file RuntimeDyldChecker.h.
Constructor & Destructor Documentation
MemoryRegionInfo() [1/3]
llvm::RuntimeDyldChecker::MemoryRegionInfo::MemoryRegionInfo () inline
Definition at line 85 of file RuntimeDyldChecker.h.
MemoryRegionInfo() [2/3]
llvm::RuntimeDyldChecker::MemoryRegionInfo::MemoryRegionInfo (ArrayRef< char > Content, JITTargetAddress TargetAddress, TargetFlagsType TargetFlags) inline
Constructor for symbols/sections with content and TargetFlag.
Definition at line 88 of file RuntimeDyldChecker.h.
References data, and llvm::size().
MemoryRegionInfo() [3/3]
llvm::RuntimeDyldChecker::MemoryRegionInfo::MemoryRegionInfo (uint64_t Size, JITTargetAddress TargetAddress) inline
Constructor for zero-fill symbols/sections.
Definition at line 96 of file RuntimeDyldChecker.h.
Member Function Documentation
getContent()
ArrayRef< char > llvm::RuntimeDyldChecker::MemoryRegionInfo::getContent () const inline
Returns the content for this section if there is any.
Definition at line 123 of file RuntimeDyldChecker.h.
References assert(), and isZeroFill().
getTargetAddress()
JITTargetAddress llvm::RuntimeDyldChecker::MemoryRegionInfo::getTargetAddress () const inline
Return the target address for this region.
Definition at line 141 of file RuntimeDyldChecker.h.
getTargetFlags()
TargetFlagsType llvm::RuntimeDyldChecker::MemoryRegionInfo::getTargetFlags () const inline
Get the target flags for this Symbol.
Definition at line 144 of file RuntimeDyldChecker.h.
getZeroFillLength()
uint64_t llvm::RuntimeDyldChecker::MemoryRegionInfo::getZeroFillLength () const inline
Returns the zero-fill length for this section.
Definition at line 129 of file RuntimeDyldChecker.h.
References assert(), and isZeroFill().
isZeroFill()
bool llvm::RuntimeDyldChecker::MemoryRegionInfo::isZeroFill () const inline
Returns true if this is a zero-fill symbol/section.
Definition at line 102 of file RuntimeDyldChecker.h.
References assert().
Referenced by getContent(), and getZeroFillLength().
setContent()
void llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent (ArrayRef< char > Content) inline
Set the content for this memory region.
Definition at line 108 of file RuntimeDyldChecker.h.
References assert(), llvm::ArrayRef< T >::data(), and llvm::ArrayRef< T >::size().
setTargetAddress()
void llvm::RuntimeDyldChecker::MemoryRegionInfo::setTargetAddress (JITTargetAddress TargetAddress) inline
Set the target address for this region.
Definition at line 135 of file RuntimeDyldChecker.h.
References assert().
setTargetFlags()
void llvm::RuntimeDyldChecker::MemoryRegionInfo::setTargetFlags (TargetFlagsType Flags) inline
Set the target flags for this Symbol.
Definition at line 147 of file RuntimeDyldChecker.h.
References assert().
setZeroFill()
void llvm::RuntimeDyldChecker::MemoryRegionInfo::setZeroFill (uint64_t Size) inline
Set a zero-fill length for this memory region.
Definition at line 116 of file RuntimeDyldChecker.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/RuntimeDyldChecker.h