LLVM: llvm::MipsTargetELFStreamer Class Reference
llvm::MipsTargetELFStreamer Class Reference
#include "Target/Mips/MCTargetDesc/MipsTargetStreamer.h"
Public Member Functions
bool isMicroMipsEnabled () const
MCELFStreamer & getStreamer ()
MipsTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
void setPic (bool Value) override
void emitLabel (MCSymbol *Symbol) override
void emitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
void finish () override
void emitGPRel32Value (const MCExpr *) override
void emitGPRel64Value (const MCExpr *) override
void emitDTPRel32Value (const MCExpr *) override
void emitDTPRel64Value (const MCExpr *) override
void emitTPRel32Value (const MCExpr *) override
void emitTPRel64Value (const MCExpr *) override
void emitDirectiveSetMicroMips () override
void emitDirectiveSetNoMicroMips () override
void setUsesMicroMips () override
void emitDirectiveSetMips16 () override
void emitDirectiveSetNoReorder () override
void emitDirectiveEnd (StringRef Name) override
void emitDirectiveEnt (const MCSymbol &Symbol) override
void emitDirectiveAbiCalls () override
void emitDirectiveNaN2008 () override
void emitDirectiveNaNLegacy () override
void emitDirectiveOptionPic0 () override
void emitDirectiveOptionPic2 () override
void emitDirectiveInsn () override
void emitFrame (MCRegister StackReg, unsigned StackSize, MCRegister ReturnReg) override
void emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override
void emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override
void emitDirectiveCpAdd (MCRegister Reg) override
void emitDirectiveCpLoad (MCRegister Reg) override
void emitDirectiveCpLocal (MCRegister Reg) override
bool emitDirectiveCpRestore (int Offset, function_ref< MCRegister()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI) override
void emitDirectiveCpsetup (MCRegister Reg, int RegOrOffset, const MCSymbol &Sym, bool IsReg) override
void emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister) override
void emitMipsAbiFlags ()
Public Member Functions inherited from llvm::MipsTargetStreamer
MipsTargetStreamer (MCStreamer &S)
virtual void emitDirectiveSetNoMips16 ()
virtual void emitDirectiveSetReorder ()
virtual void emitDirectiveSetMacro ()
virtual void emitDirectiveSetNoMacro ()
virtual void emitDirectiveSetMsa ()
virtual void emitDirectiveSetNoMsa ()
virtual void emitDirectiveSetMt ()
virtual void emitDirectiveSetNoMt ()
virtual void emitDirectiveSetCRC ()
virtual void emitDirectiveSetNoCRC ()
virtual void emitDirectiveSetVirt ()
virtual void emitDirectiveSetNoVirt ()
virtual void emitDirectiveSetGINV ()
virtual void emitDirectiveSetNoGINV ()
virtual void emitDirectiveSetAt ()
virtual void emitDirectiveSetAtWithArg (unsigned RegNo)
virtual void emitDirectiveSetNoAt ()
virtual void emitDirectiveSetArch (StringRef Arch)
virtual void emitDirectiveSetMips0 ()
virtual void emitDirectiveSetMips1 ()
virtual void emitDirectiveSetMips2 ()
virtual void emitDirectiveSetMips3 ()
virtual void emitDirectiveSetMips4 ()
virtual void emitDirectiveSetMips5 ()
virtual void emitDirectiveSetMips32 ()
virtual void emitDirectiveSetMips32R2 ()
virtual void emitDirectiveSetMips32R3 ()
virtual void emitDirectiveSetMips32R5 ()
virtual void emitDirectiveSetMips32R6 ()
virtual void emitDirectiveSetMips64 ()
virtual void emitDirectiveSetMips64R2 ()
virtual void emitDirectiveSetMips64R3 ()
virtual void emitDirectiveSetMips64R5 ()
virtual void emitDirectiveSetMips64R6 ()
virtual void emitDirectiveSetDsp ()
virtual void emitDirectiveSetDspr2 ()
virtual void emitDirectiveSetNoDsp ()
virtual void emitDirectiveSetMips3D ()
virtual void emitDirectiveSetNoMips3D ()
virtual void emitDirectiveSetPop ()
virtual void emitDirectiveSetPush ()
virtual void emitDirectiveSetSoftFloat ()
virtual void emitDirectiveSetHardFloat ()
virtual void emitDirectiveModuleFP ()
virtual void emitDirectiveModuleOddSPReg ()
virtual void emitDirectiveModuleSoftFloat ()
virtual void emitDirectiveModuleHardFloat ()
virtual void emitDirectiveModuleMT ()
virtual void emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value)
virtual void emitDirectiveSetOddSPReg ()
virtual void emitDirectiveSetNoOddSPReg ()
virtual void emitDirectiveModuleCRC ()
virtual void emitDirectiveModuleNoCRC ()
virtual void emitDirectiveModuleVirt ()
virtual void emitDirectiveModuleNoVirt ()
virtual void emitDirectiveModuleGINV ()
virtual void emitDirectiveModuleNoGINV ()
void emitR (unsigned Opcode, MCRegister Reg0, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitII (unsigned Opcode, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRX (unsigned Opcode, MCRegister Reg0, MCOperand Op1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRI (unsigned Opcode, MCRegister Reg0, int32_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRR (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRX (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, MCOperand Op2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRR (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, MCRegister Reg2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRRX (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, MCRegister Reg2, MCOperand Op3, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRI (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, int16_t Imm, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitRRIII (unsigned Opcode, MCRegister Reg0, MCRegister Reg1, int16_t Imm0, int16_t Imm1, int16_t Imm2, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitAddu (MCRegister DstReg, MCRegister SrcReg, MCRegister TrgReg, bool Is64Bit, const MCSubtargetInfo *STI)
void emitDSLL (MCRegister DstReg, MCRegister SrcReg, int16_t ShiftAmount, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitEmptyDelaySlot (bool hasShortDelaySlot, SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitNop (SMLoc IDLoc, const MCSubtargetInfo *STI)
void emitStoreWithImmOffset (unsigned Opcode, MCRegister SrcReg, MCRegister BaseReg, int64_t Offset, function_ref< MCRegister()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a store instruction with an offset.
void emitLoadWithImmOffset (unsigned Opcode, MCRegister DstReg, MCRegister BaseReg, int64_t Offset, MCRegister TmpReg, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit a load instruction with an immediate offset.
void emitGPRestore (int Offset, SMLoc IDLoc, const MCSubtargetInfo *STI)
Emit the $gp restore operation for .cprestore.
void forbidModuleDirective ()
void reallowModuleDirective ()
bool isModuleDirectiveAllowed ()
template<class PredicateLibrary>
void updateABIInfo (const PredicateLibrary &P)
MipsABIFlagsSection & getABIFlagsSection ()
const MipsABIInfo & getABI () const
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
Additional Inherited Members
Protected Attributes inherited from llvm::MipsTargetStreamer
std::optional< MipsABIInfo > ABI
MipsABIFlagsSection ABIFlagsSection
bool GPRInfoSet
unsigned GPRBitMask
int GPROffset
bool FPRInfoSet
unsigned FPRBitMask
int FPROffset
bool FrameInfoSet
int FrameOffset
unsigned FrameReg
MCRegister GPReg
unsigned ReturnReg
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 329 of file MipsTargetStreamer.h.
Constructor & Destructor Documentation
MipsTargetELFStreamer()
MipsTargetELFStreamer::MipsTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 852 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABI, llvm::ELF::EF_MIPS_ARCH_1, llvm::ELF::EF_MIPS_ARCH_2, llvm::ELF::EF_MIPS_ARCH_3, llvm::ELF::EF_MIPS_ARCH_32, llvm::ELF::EF_MIPS_ARCH_32R2, llvm::ELF::EF_MIPS_ARCH_32R6, llvm::ELF::EF_MIPS_ARCH_4, llvm::ELF::EF_MIPS_ARCH_5, llvm::ELF::EF_MIPS_ARCH_64, llvm::ELF::EF_MIPS_ARCH_64R2, llvm::ELF::EF_MIPS_ARCH_64R6, llvm::ELF::EF_MIPS_MACH_OCTEON, llvm::ELF::EF_MIPS_NAN2008, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getObjectFileInfo(), getStreamer(), llvm::MCELFStreamer::getWriter(), llvm::MCObjectFileInfo::isPositionIndependent(), llvm::Triple::mips, llvm::Triple::mipsel, llvm::MipsTargetStreamer::MipsTargetStreamer(), llvm::MipsABIInfo::N64(), and llvm::MipsABIInfo::O32().
Member Function Documentation
emitAssignment()
void MipsTargetELFStreamer::emitAssignment (MCSymbol * Symbol, const MCExpr * Value) override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 1016 of file MipsTargetStreamer.cpp.
References llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbolELF::setOther(), llvm::ELF::STO_MIPS_MICROMIPS, and llvm::MCExpr::SymbolRef.
emitDirectiveAbiCalls()
void MipsTargetELFStreamer::emitDirectiveAbiCalls () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1159 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, getStreamer(), and llvm::MCELFStreamer::getWriter().
emitDirectiveCpAdd()
void MipsTargetELFStreamer::emitDirectiveCpAdd (MCRegister Reg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1232 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitAddu(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsTargetStreamer::getABI(), and llvm::MipsTargetStreamer::GPReg.
emitDirectiveCpLoad()
void MipsTargetELFStreamer::emitDirectiveCpLoad (MCRegister Reg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1243 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::clear(), llvm::MCSpecifierExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createReg(), llvm::MCObjectStreamer::emitInstruction(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsTargetStreamer::getABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getOrCreateSymbol(), getStreamer(), llvm::MipsTargetStreamer::GPReg, llvm::MCAssembler::registerSymbol(), llvm::Mips::S_HI, llvm::Mips::S_LO, and llvm::MCInst::setOpcode().
emitDirectiveCpLocal()
void MipsTargetELFStreamer::emitDirectiveCpLocal (MCRegister Reg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1292 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveCpLocal().
emitDirectiveCpRestore()
bool MipsTargetELFStreamer::emitDirectiveCpRestore (int Offset, function_ref< MCRegister()> GetATReg, SMLoc IDLoc, const MCSubtargetInfo * STI) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1297 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveCpRestore(), llvm::MipsTargetStreamer::emitStoreWithImmOffset(), llvm::MipsTargetStreamer::getABI(), llvm::MipsTargetStreamer::GPReg, and llvm::Offset.
emitDirectiveCpreturn()
void MipsTargetELFStreamer::emitDirectiveCpreturn (unsigned SaveLocation, bool SaveLocationIsRegister) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1361 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCObjectStreamer::emitInstruction(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsTargetStreamer::getABI(), getStreamer(), llvm::MipsTargetStreamer::GPReg, and llvm::MCInst::setOpcode().
emitDirectiveCpsetup()
void MipsTargetELFStreamer::emitDirectiveCpsetup (MCRegister Reg, int RegOrOffset, const MCSymbol & Sym, bool IsReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1318 of file MipsTargetStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::Mips::createGpOff(), llvm::MipsTargetStreamer::emitRRI(), llvm::MipsTargetStreamer::emitRRR(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsTargetStreamer::getABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), getStreamer(), llvm::MipsTargetStreamer::GPReg, llvm::Mips::S_HI, and llvm::Mips::S_LO.
emitDirectiveEnd()
void MipsTargetELFStreamer::emitDirectiveEnd (StringRef Name) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1110 of file MipsTargetStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitValueImpl(), llvm::MipsTargetStreamer::FPRBitMask, llvm::MipsTargetStreamer::FPRInfoSet, llvm::MipsTargetStreamer::FPROffset, llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::FrameOffset, llvm::MipsTargetStreamer::FrameReg, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), getStreamer(), llvm::MipsTargetStreamer::GPRBitMask, llvm::MipsTargetStreamer::GPRInfoSet, llvm::MipsTargetStreamer::GPROffset, llvm::MCStreamer::popSection(), llvm::MCStreamer::pushSection(), llvm::MipsTargetStreamer::ReturnReg, llvm::MCSection::setAlignment(), llvm::ELF::SHT_PROGBITS, Size, and llvm::MCStreamer::switchSection().
emitDirectiveEnt()
void MipsTargetELFStreamer::emitDirectiveEnt (const MCSymbol & Symbol) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1152 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FPRInfoSet, llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::GPRInfoSet, and llvm::ELF::STT_FUNC.
emitDirectiveInsn()
void MipsTargetELFStreamer::emitDirectiveInsn () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1201 of file MipsTargetStreamer.cpp.
References llvm::MipsELFStreamer::createPendingLabelRelocs(), llvm::MipsTargetStreamer::emitDirectiveInsn(), and llvm::MCTargetStreamer::Streamer.
emitDirectiveNaN2008()
void MipsTargetELFStreamer::emitDirectiveNaN2008 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1166 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_NAN2008, getStreamer(), and llvm::MCELFStreamer::getWriter().
emitDirectiveNaNLegacy()
void MipsTargetELFStreamer::emitDirectiveNaNLegacy () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1173 of file MipsTargetStreamer.cpp.
References getStreamer(), and llvm::MCELFStreamer::getWriter().
emitDirectiveOptionPic0()
void MipsTargetELFStreamer::emitDirectiveOptionPic0 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1180 of file MipsTargetStreamer.cpp.
References getStreamer(), and llvm::MCELFStreamer::getWriter().
emitDirectiveOptionPic2()
void MipsTargetELFStreamer::emitDirectiveOptionPic2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1189 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, getStreamer(), and llvm::MCELFStreamer::getWriter().
emitDirectiveSetMicroMips()
void MipsTargetELFStreamer::emitDirectiveSetMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1077 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetMips16()
void MipsTargetELFStreamer::emitDirectiveSetMips16 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1094 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_ARCH_ASE_M16, llvm::MipsTargetStreamer::forbidModuleDirective(), getStreamer(), and llvm::MCELFStreamer::getWriter().
emitDirectiveSetNoMicroMips()
void MipsTargetELFStreamer::emitDirectiveSetNoMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1082 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetNoReorder()
void MipsTargetELFStreamer::emitDirectiveSetNoReorder () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1102 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_NOREORDER, llvm::MipsTargetStreamer::forbidModuleDirective(), getStreamer(), and llvm::MCELFStreamer::getWriter().
emitDTPRel32Value()
void MipsTargetELFStreamer::emitDTPRel32Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1049 of file MipsTargetStreamer.cpp.
References llvm::Mips::fixup_Mips_DTPREL32, and getStreamer().
emitDTPRel64Value()
void MipsTargetELFStreamer::emitDTPRel64Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1056 of file MipsTargetStreamer.cpp.
References llvm::Mips::fixup_Mips_DTPREL64, and getStreamer().
emitFMask()
void MipsTargetELFStreamer::emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1225 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FPRBitMask, llvm::MipsTargetStreamer::FPRInfoSet, and llvm::MipsTargetStreamer::FPROffset.
emitFrame()
void MipsTargetELFStreamer::emitFrame (MCRegister StackReg, unsigned StackSize, MCRegister ReturnReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1207 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::FrameOffset, llvm::MipsTargetStreamer::FrameReg, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), getStreamer(), and llvm::MipsTargetStreamer::ReturnReg.
emitGPRel32Value()
void MipsTargetELFStreamer::emitGPRel32Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1034 of file MipsTargetStreamer.cpp.
References llvm::Mips::fixup_Mips_GPREL32, and getStreamer().
emitGPRel64Value()
void MipsTargetELFStreamer::emitGPRel64Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1041 of file MipsTargetStreamer.cpp.
References llvm::Mips::fixup_Mips_GPREL32, and getStreamer().
emitLabel()
void MipsTargetELFStreamer::emitLabel (MCSymbol * Symbol) override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 932 of file MipsTargetStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), getStreamer(), isMicroMipsEnabled(), llvm::MCAssembler::registerSymbol(), llvm::ELF::STO_MIPS_MICROMIPS, and llvm::ELF::STT_FUNC.
emitMask()
void MipsTargetELFStreamer::emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1218 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::GPRBitMask, llvm::MipsTargetStreamer::GPRInfoSet, and llvm::MipsTargetStreamer::GPROffset.
emitMipsAbiFlags()
void MipsTargetELFStreamer::emitMipsAbiFlags ()
Definition at line 1385 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), getStreamer(), llvm::MCSection::setAlignment(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_MIPS_ABIFLAGS, and llvm::MCStreamer::switchSection().
Referenced by finish().
emitTPRel32Value()
void MipsTargetELFStreamer::emitTPRel32Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1063 of file MipsTargetStreamer.cpp.
References llvm::Mips::fixup_Mips_TPREL32, and getStreamer().
emitTPRel64Value()
void MipsTargetELFStreamer::emitTPRel64Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1070 of file MipsTargetStreamer.cpp.
References llvm::Mips::fixup_Mips_TPREL64, and getStreamer().
finish()
void MipsTargetELFStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 943 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_32BITMODE, llvm::ELF::EF_MIPS_ABI2, llvm::ELF::EF_MIPS_ABI_O32, llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, llvm::MCObjectStreamer::emitCodeAlignment(), emitMipsAbiFlags(), llvm::MipsELFStreamer::EmitMipsOptionRecords(), llvm::MCObjectStreamer::emitValueToAlignment(), llvm::MCSection::ensureMinAlignment(), llvm::MipsTargetStreamer::getABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCObjectFileInfo::getBSSSection(), llvm::MCAssembler::getContext(), llvm::MCTargetStreamer::getContext(), llvm::MCObjectFileInfo::getDataSection(), llvm::MCContext::getObjectFileInfo(), getStreamer(), llvm::MCObjectFileInfo::getTextSection(), llvm::MCELFStreamer::getWriter(), llvm::MCTargetStreamer::Streamer, llvm::MCStreamer::switchSection(), and llvm::Align::value().
getStreamer()
MCELFStreamer & MipsTargetELFStreamer::getStreamer ()
Definition at line 1030 of file MipsTargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by emitDirectiveAbiCalls(), emitDirectiveCpLoad(), emitDirectiveCpreturn(), emitDirectiveCpsetup(), emitDirectiveEnd(), emitDirectiveNaN2008(), emitDirectiveNaNLegacy(), emitDirectiveOptionPic0(), emitDirectiveOptionPic2(), emitDirectiveSetMips16(), emitDirectiveSetNoReorder(), emitDTPRel32Value(), emitDTPRel64Value(), emitFrame(), emitGPRel32Value(), emitGPRel64Value(), emitLabel(), emitMipsAbiFlags(), emitTPRel32Value(), emitTPRel64Value(), finish(), MipsTargetELFStreamer(), and setUsesMicroMips().
isMicroMipsEnabled()
bool llvm::MipsTargetELFStreamer::isMicroMipsEnabled () const inline
Definition at line 335 of file MipsTargetStreamer.h.
Referenced by llvm::MipsELFStreamer::createPendingLabelRelocs(), and emitLabel().
setPic()
void llvm::MipsTargetELFStreamer::setPic (bool Value) inline override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 339 of file MipsTargetStreamer.h.
setUsesMicroMips()
void MipsTargetELFStreamer::setUsesMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 1087 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_MICROMIPS, getStreamer(), and llvm::MCELFStreamer::getWriter().
The documentation for this class was generated from the following files:
lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.h
lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp