LLVM: llvm::BPFMCInstLower Class Reference
llvm::BPFMCInstLower Class Reference
#include "Target/BPF/BPFMCInstLower.h"
Public Member Functions
BPFMCInstLower (MCContext &ctx, BPFAsmPrinter &printer)
void Lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand LowerSymbolOperand (const MachineOperand &MO, MCSymbol *Sym) const
MCSymbol * GetGlobalAddressSymbol (const MachineOperand &MO) const
MCSymbol * GetExternalSymbolSymbol (const MachineOperand &MO) const
Detailed Description
Definition at line 24 of file BPFMCInstLower.h.
Constructor & Destructor Documentation
BPFMCInstLower()
llvm::BPFMCInstLower::BPFMCInstLower (MCContext & ctx, BPFAsmPrinter & printer) inline
Definition at line 30 of file BPFMCInstLower.h.
References printer.
Member Function Documentation
GetExternalSymbolSymbol()
MCSymbol * BPFMCInstLower::GetExternalSymbolSymbol (const MachineOperand & MO) const
Definition at line 35 of file BPFMCInstLower.cpp.
References llvm::MachineOperand::getSymbolName().
Referenced by Lower().
GetGlobalAddressSymbol()
MCSymbol * BPFMCInstLower::GetGlobalAddressSymbol (const MachineOperand & MO) const
Definition at line 30 of file BPFMCInstLower.cpp.
References llvm::MachineOperand::getGlobal().
Referenced by Lower().
Lower()
void BPFMCInstLower::Lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 50 of file BPFMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::errs(), GetExternalSymbolSymbol(), GetGlobalAddressSymbol(), llvm_unreachable, LowerSymbolOperand(), MI, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, and llvm::MCInst::setOpcode().
Referenced by llvm::BPFAsmPrinter::emitInstruction().
LowerSymbolOperand()
MCOperand BPFMCInstLower::LowerSymbolOperand (const MachineOperand & MO, MCSymbol * Sym) const
Definition at line 39 of file BPFMCInstLower.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::isJTI(), and llvm_unreachable.
Referenced by Lower().
The documentation for this class was generated from the following files:
lib/Target/BPF/BPFMCInstLower.h
lib/Target/BPF/BPFMCInstLower.cpp