LLVM: llvm::sys::fs::directory_entry Class Reference
llvm::sys::fs::directory_entry Class Reference
directory_entry - A single entry in a directory.
#include "llvm/Support/FileSystem.h"
Public Member Functions
directory_entry (const Twine &Path, bool FollowSymlinks=true, file_type Type=file_type::type_unknown, basic_file_status Status=basic_file_status())
directory_entry ()=default
LLVM_ABI void replace_filename (const Twine &Filename, file_type Type, basic_file_status Status=basic_file_status())
const std::string & path () const
LLVM_ABI ErrorOr< basic_file_status > status () const
file_type type () const
bool operator== (const directory_entry &RHS) const
bool operator!= (const directory_entry &RHS) const
LLVM_ABI bool operator< (const directory_entry &RHS) const
LLVM_ABI bool operator<= (const directory_entry &RHS) const
LLVM_ABI bool operator> (const directory_entry &RHS) const
LLVM_ABI bool operator>= (const directory_entry &RHS) const
Detailed Description
directory_entry - A single entry in a directory.
Definition at line 1373 of file FileSystem.h.
Constructor & Destructor Documentation
directory_entry() [1/2]
llvm::sys::fs::directory_entry::directory_entry (const Twine & Path, bool FollowSymlinks = true, file_type Type = file_type::type_unknown, basic_file_status Status = basic_file_status()) inline explicit
Definition at line 1385 of file FileSystem.h.
References llvm::sys::fs::type_unknown.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
directory_entry() [2/2]
llvm::sys::fs::directory_entry::directory_entry () default
References LLVM_ABI.
Member Function Documentation
operator!=()
bool llvm::sys::fs::directory_entry::operator!= (const directory_entry & RHS) const inline
Definition at line 1413 of file FileSystem.h.
References directory_entry(), and RHS.
operator<()
LLVM_ABI bool llvm::sys::fs::directory_entry::operator< (const directory_entry & RHS) const
References directory_entry(), LLVM_ABI, and RHS.
operator<=()
LLVM_ABI bool llvm::sys::fs::directory_entry::operator<= (const directory_entry & RHS) const
References directory_entry(), LLVM_ABI, and RHS.
operator==()
bool llvm::sys::fs::directory_entry::operator== (const directory_entry & RHS) const inline
Definition at line 1412 of file FileSystem.h.
References directory_entry(), and RHS.
operator>()
LLVM_ABI bool llvm::sys::fs::directory_entry::operator> (const directory_entry & RHS) const
References directory_entry(), LLVM_ABI, and RHS.
operator>=()
LLVM_ABI bool llvm::sys::fs::directory_entry::operator>= (const directory_entry & RHS) const
References directory_entry(), LLVM_ABI, and RHS.
path()
const std::string & llvm::sys::fs::directory_entry::path () const inline
Definition at line 1397 of file FileSystem.h.
Referenced by llvm::sys::fs::directory_iterator::directory_iterator().
replace_filename()
void llvm::sys::fs::directory_entry::replace_filename (const Twine & Filename, file_type Type, basic_file_status Status = basic_file_status())
Definition at line 1163 of file Path.cpp.
References llvm::sys::path::append(), and llvm::sys::path::parent_path().
status()
LLVM_ABI ErrorOr< basic_file_status > llvm::sys::fs::directory_entry::status () const
References LLVM_ABI.
Referenced by type().
type()
file_type llvm::sys::fs::directory_entry::type () const inline
Definition at line 1405 of file FileSystem.h.
References status(), and llvm::sys::fs::type_unknown.
The documentation for this class was generated from the following files:
include/llvm/Support/FileSystem.h
lib/Support/Path.cpp