LLVM: llvm::PredicateSwitch Class Reference
llvm::PredicateSwitch Class Reference
#include "llvm/Transforms/Utils/PredicateInfo.h"
Public Member Functions
PredicateSwitch (Value *Op, BasicBlock *SwitchBB, BasicBlock *TargetBB, Value *CaseValue, SwitchInst *SI)
PredicateSwitch ()=delete
Public Member Functions inherited from llvm::PredicateWithEdge
PredicateWithEdge ()=delete
Public Member Functions inherited from llvm::PredicateBase
PredicateBase (const PredicateBase &)=delete
PredicateBase & operator= (const PredicateBase &)=delete
PredicateBase ()=delete
LLVM_ABI std::optional< PredicateConstraint > getConstraint () const
Fetch condition in the form of PredicateConstraint, if possible.
Static Public Member Functions
static bool classof (const PredicateBase *PB)
Static Public Member Functions inherited from llvm::PredicateWithEdge
static bool classof (const PredicateBase *PB)
Static Public Member Functions inherited from llvm::PredicateBase
static bool classof (const PredicateBase *PB)
Public Attributes
Value * CaseValue
SwitchInst * Switch
Public Attributes inherited from llvm::PredicateWithEdge
BasicBlock * From
BasicBlock * To
Public Attributes inherited from llvm::PredicateBase
PredicateType Type
Value * OriginalOp
Value * RenamedOp
Value * Condition
Additional Inherited Members
Protected Member Functions inherited from llvm::PredicateWithEdge
PredicateWithEdge (PredicateType PType, Value *Op, BasicBlock *From, BasicBlock *To, Value *Cond)
Protected Member Functions inherited from llvm::PredicateBase
PredicateBase (PredicateType PT, Value *Op, Value *Condition)
Detailed Description
Definition at line 158 of file PredicateInfo.h.
Constructor & Destructor Documentation
PredicateSwitch() [1/2]
llvm::PredicateSwitch::PredicateSwitch (Value * Op, BasicBlock * SwitchBB, BasicBlock * TargetBB, Value * CaseValue, SwitchInst * SI) inline
Definition at line 163 of file PredicateInfo.h.
References CaseValue, getCondition(), llvm::PredicateWithEdge::PredicateWithEdge(), llvm::PT_Switch, and Switch.
PredicateSwitch() [2/2]
llvm::PredicateSwitch::PredicateSwitch () delete
Member Function Documentation
classof()
bool llvm::PredicateSwitch::classof (const PredicateBase * PB) inline static
Definition at line 169 of file PredicateInfo.h.
References PB(), and llvm::PT_Switch.
Member Data Documentation
CaseValue
Value* llvm::PredicateSwitch::CaseValue
Definition at line 160 of file PredicateInfo.h.
Referenced by PredicateSwitch().
Switch
SwitchInst* llvm::PredicateSwitch::Switch
Definition at line 162 of file PredicateInfo.h.
Referenced by PredicateSwitch().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Utils/PredicateInfo.h