LLVM: llvm::objcopy::elf::ELFReader Class Reference
llvm::objcopy::elf::ELFReader Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
Expected< std::unique_ptr< Object > > create (bool EnsureSymtab) const override
ELFReader (Binary *B, std::optional< StringRef > ExtractPartition)
Public Member Functions inherited from llvm::objcopy::elf::Reader
virtual ~Reader ()
Detailed Description
Definition at line 1148 of file ELFObject.h.
Constructor & Destructor Documentation
ELFReader()
llvm::objcopy::elf::ELFReader::ELFReader (Binary * B, std::optional< StringRef > ExtractPartition) inline explicit
Definition at line 1154 of file ELFObject.h.
References B().
Member Function Documentation
create()
Expected< std::unique_ptr< Object > > ELFReader::create (bool EnsureSymtab) const override virtual
Implements llvm::objcopy::elf::Reader.
Definition at line 1996 of file ELFObject.cpp.
References llvm::createStringError(), llvm::dyn_cast(), and llvm::invalid_argument.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp