LLVM: llvm::NVPTXTargetStreamer Class Reference
llvm::NVPTXTargetStreamer Class Reference
Implments NVPTX-specific streamer.
#include "Target/NVPTX/MCTargetDesc/NVPTXTargetStreamer.h"
Public Member Functions
NVPTXTargetStreamer (MCStreamer &S)
~NVPTXTargetStreamer () override
void outputDwarfFileDirectives ()
Outputs the list of the DWARF '.file' directives to the streamer.
void closeLastSection ()
Close last section.
void emitDwarfFileDirective (StringRef Directive) override
Record DWARF file directives for later output.
void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS) override
Update streamer for a new active section.
void emitRawBytes (StringRef Data) override
Emit the bytes in Data into the output.
void emitValue (const MCExpr *Value) override
Makes sure that labels are mangled the same way as the actual symbols.
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
MCContext & getContext ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Implments NVPTX-specific streamer.
Definition at line 18 of file NVPTXTargetStreamer.h.
Constructor & Destructor Documentation
NVPTXTargetStreamer()
NVPTXTargetStreamer::NVPTXTargetStreamer (MCStreamer & S)
Definition at line 27 of file NVPTXTargetStreamer.cpp.
References llvm::MCTargetStreamer::MCTargetStreamer().
Referenced by llvm::NVPTXAsmTargetStreamer::NVPTXAsmTargetStreamer().
~NVPTXTargetStreamer()
NVPTXTargetStreamer::~NVPTXTargetStreamer () override default
References llvm::Data.
Member Function Documentation
changeSection()
void NVPTXTargetStreamer::changeSection (const MCSection * CurSection, MCSection * Section, uint32_t SubSection, raw_ostream & OS) override virtual
Update streamer for a new active section.
This is called by popSection and switchSection, if the current section changes.
Reimplemented from llvm::MCTargetStreamer.
Definition at line 89 of file NVPTXTargetStreamer.cpp.
References assert(), llvm::MCStreamer::getContext(), llvm::MCContext::getObjectFileInfo(), llvm::MCTargetStreamer::getStreamer(), isDwarfSection(), and outputDwarfFileDirectives().
closeLastSection()
void NVPTXTargetStreamer::closeLastSection ()
Close last section.
Definition at line 40 of file NVPTXTargetStreamer.cpp.
References llvm::MCStreamer::emitRawText(), and llvm::MCTargetStreamer::getStreamer().
emitDwarfFileDirective()
void NVPTXTargetStreamer::emitDwarfFileDirective (StringRef Directive) override virtual
Record DWARF file directives for later output.
According to PTX ISA, CUDA Toolkit documentation, 11.5.3. Debugging Directives: .file (http://docs.nvidia.com/cuda/parallel-thread-execution/index.html#debugging-directives-file), The .file directive is allowed only in the outermost scope, i.e., at the same level as kernel and device function declarations. Also, the order of the .loc and .file directive does not matter, .file directives may follow the .loc directives where the file is referenced. LLVM emits .file directives immediately the location debug info is emitted, i.e. they may be emitted inside functions. We gather all these directives and emit them outside of the sections and, thus, outside of the functions.
Reimplemented from llvm::MCTargetStreamer.
Definition at line 45 of file NVPTXTargetStreamer.cpp.
emitRawBytes()
void NVPTXTargetStreamer::emitRawBytes (StringRef Data) override virtual
Emit the bytes in Data into the output.
This is used to emit bytes in Data as sequence of .byte directives.
Reimplemented from llvm::MCTargetStreamer.
Definition at line 107 of file NVPTXTargetStreamer.cpp.
References llvm::Data, llvm::MCTargetStreamer::emitRawBytes(), llvm::MCAsmInfo::getData8bitsDirective(), I, llvm::raw_svector_ostream::str(), and llvm::MCTargetStreamer::Streamer.
emitValue()
void NVPTXTargetStreamer::emitValue (const MCExpr * Value) override virtual
Makes sure that labels are mangled the same way as the actual symbols.
Reimplemented from llvm::MCTargetStreamer.
Definition at line 139 of file NVPTXTargetStreamer.cpp.
References llvm::cast(), llvm::MCTargetStreamer::emitValue(), llvm::MCSymbol::getName(), llvm::MCSymbolRefExpr::getSymbol(), llvm::NVPTX::getValidPTXIdentifier(), llvm::StringRef::starts_with(), llvm::MCTargetStreamer::Streamer, and llvm::MCExpr::SymbolRef.
outputDwarfFileDirectives()
void NVPTXTargetStreamer::outputDwarfFileDirectives ()
Outputs the list of the DWARF '.file' directives to the streamer.
Definition at line 34 of file NVPTXTargetStreamer.cpp.
References llvm::MCStreamer::emitRawText(), and llvm::MCTargetStreamer::getStreamer().
Referenced by changeSection(), and llvm::NVPTXAsmPrinter::doFinalization().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/MCTargetDesc/NVPTXTargetStreamer.h
lib/Target/NVPTX/MCTargetDesc/NVPTXTargetStreamer.cpp