LLVM: lib/CodeGen/CodeGenCommonISel.cpp File Reference
CodeGenCommonISel.cpp File Reference
#include "llvm/CodeGen/CodeGenCommonISel.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/IR/DebugInfoMetadata.h"
Macros
#define DEBUG_TYPE "codegen-common"
Functions
static bool MIIsInTerminatorSequence (const MachineInstr &MI)
Given that the input MI is before a partial terminator sequence TSeq, return true if M + TSeq also a partial terminator sequence.
assert (UseMOIdx !=-1 &&DbgMI->hasDebugOperandForReg(DefMO->getReg()) &&"Must use salvaged instruction as its location")
if (DbgMI->getOpcode() !=TargetOpcode::DBG_VALUE)
if (!Op0) continue
if (IsValidSalvageExpr)
Variables
nullptr
Find the split point at which to splice the end of BB into its success stack protector check machine basic block.
const DIExpression * SalvagedExpr = DbgMI->getDebugExpression()
SmallVector< uint64_t, 16 > Ops
auto Op0 = salvageDebugInfoImpl(MRI, MI, Ops)
bool IsValidSalvageExpr
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "codegen-common"
Definition at line 22 of file CodeGenCommonISel.cpp.
Function Documentation
assert()
assert (UseMOIdx ! = -1 &&DbgMI->hasDebugOperandForReg(DefMO->getReg()) &&"Must use salvaged instruction as its location")
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo(), llvm::AArch64RegisterBankInfo::AArch64RegisterBankInfo(), absoluteSymbolDiff(), llvm::AbstractCallSite::AbstractCallSite(), llvm::sandboxir::Tracker::accept(), accessedBetween(), llvm::GEPOperator::accumulateConstantOffset(), llvm::LiveRegUnits::accumulateUsedDefed(), llvm::GCStatepointInst::actual_arg_begin(), llvm::GCStatepointInst::actual_arg_end(), false::Chain::add(), llvm::AliasSetTracker::add(), llvm::APFloat::add(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::add(), llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::add(), llvm::LiveRangeUpdater::add(), llvm::lto::LTO::add(), llvm::NumberedValues< T >::add(), llvm::orc::BloomFilter::add(), llvm::orc::CtorDtorRunner::add(), llvm::orc::detail::WaitingOnGraph< ContainerIdT, ElementIdT >::SuperNodeBuilder::add(), llvm::orc::IRLayer::add(), llvm::orc::IRSymbolMapper::add(), llvm::orc::ObjectLayer::add(), llvm::PMDataManager::add(), llvm::ResourceSegments::add(), llvm::SDDbgInfo::add(), llvm::SPIRVIRMapping::add(), llvm::StringTableBuilder::add(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), llvm::ImutAVLFactory< ImutInfo >::add_internal(), llvm::X86Operand::addAbsMemOperands(), llvm::jitlink::LinkGraph::addAbsoluteSymbol(), llvm::dwarf_linker::classic::DWARFLinker::addAccelTableKind(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::addAccelTableKind(), llvm::AA::PointerInfo::State::addAccess(), addAccessAttr(), llvm::VPlanTransforms::addActiveLaneMask(), llvm::orc::addAliases(), llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAllocSizeAttrFromRawRepr(), llvm::memprof::addAmbiguousAttribute(), llvm::DwarfUnit::addAnnotation(), llvm::Hexagon_MC::addArchSubtarget(), llvm::AttributeMask::addAttribute(), llvm::OpenMPIRBuilder::addAttributes(), llvm::SSAUpdater::AddAvailableValue(), llvm::SSAUpdaterBulk::AddAvailableValue(), llvm::X86Operand::addAVX512RCOperands(), llvm::ScheduleDAGInstrs::addBarrierChain(), llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::dwarf_linker::parallel::DIEGenerator::addBlockAttribute(), llvm::LoopBase< BlockT, LoopT >::addBlockEntry(), llvm::DwarfExpression::addBooleanConstant(), llvm::ControlFlowHub::addBranch(), llvm::VPlanTransforms::addBranchWeightToMiddleTerminator(), llvm::DwarfExpression::addBReg(), llvm::MachineFunction::addCalledGlobal(), llvm::MachineFunction::addCallSiteInfo(), addCallStack(), llvm::memprof::CallStackTrie::addCallStack(), llvm::memprof::CallStackTrie::addCallStack(), llvm::SwitchInst::addCase(), llvm::SwitchInstProfUpdateWrapper::addCase(), llvm::cl::Option::addCategory(), llvm::codeview::DebugChecksumsSubsection::addChecksum(), llvm::DIE::addChild(), llvm::dwarf_linker::parallel::DIEGenerator::addChild(), llvm::DIE::addChildFront(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LPMUpdater::addChildLoops(), llvm::RecordKeeper::addClass(), llvm::PassInstrumentationCallbacks::addClassToPassName(), llvm::LandingPadInst::addClause(), llvm::addClonedBlockToLoopInfo(), AddCombineTo64bitMLAL(), addConditions(), addConstantComments(), llvm::DwarfExpression::addConstantFP(), addConstantsToTrack(), llvm::HexagonMCInstrInfo::addConstExtender(), llvm::jitlink::MachOLinkGraphBuilder::addCustomSectionParser(), llvm::SelectionDAGBuilder::addDanglingDebugInfo(), addData(), llvm::pdb::DbiStreamBuilder::addDbgStream(), llvm::SelectionDAG::AddDbgValue(), llvm::RecordKeeper::addDef(), llvm::jitlink::LinkGraph::addDefinedSymbol(), llvm::MachineRegisterInfo::addDelegate(), llvm::DeltaTree::AddDelta(), llvm::IndirectBrInst::addDestination(), llvm::DwarfUnit::addDIEEntry(), llvm::FileCollectorBase::addDirectory(), llvm::Record::addDirectSuperClass(), llvm::MachineInstrBuilder::addDisp(), llvm::MachO::InterfaceFile::addDocument(), llvm::DomainValue::addDomain(), llvm::X86Operand::addDstIdxOperands(), llvm::jitlink::Block::addEdge(), llvm::PBQP::Graph< RegAllocSolverImpl >::addEdge(), llvm::PBQP::Graph< RegAllocSolverImpl >::addEdgeBypassingCostAllocator(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScope::addElement(), addEmuTlsVar(), llvm::logicalview::LVRange::addEntry(), llvm::InstrProfSummaryBuilder::addEntryCount(), llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), llvm::Loc::EntryValue::addExpr(), XtensaOperand::addExpr(), llvm::DwarfExpression::addExpression(), llvm::jitlink::LinkGraph::addExternalSymbol(), llvm::RecordKeeper::addExtraGlobal(), llvm::AMDGPU::SetOfRulesForOpcode::addFastRuleDivergent(), llvm::AMDGPU::SetOfRulesForOpcode::addFastRuleUniform(), llvm::CodeViewContext::addFile(), llvm::DwarfExpression::addFragmentOffset(), llvm::Loc::MMI::addFrameIndexExpr(), llvm::addFullAddress(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::orc::JITDylib::addGenerator(), llvm::ExecutionEngine::addGlobalMapping(), llvm::X86Operand::addGR16orGR32orGR64Operands(), llvm::X86Operand::addGR32orGR64Operands(), llvm::CatchSwitchInst::addHandler(), llvm::X86Operand::addImmOperands(), XtensaOperand::addImmOperands(), addIncomingValuesToPHIs(), llvm::objcopy::elf::SectionIndexSection::addIndex(), llvm::dwarf_linker::parallel::DIEGenerator::addIndexedStringAttribute(), addInitialSkeleton(), llvm::orc::addInitSymbol(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::DbgLabelInstrMap::addInstr(), llvm::mca::LSUnit::MemoryGroup::addInstruction(), llvm::PressureDiffs::addInstruction(), addInstToMergeableList(), llvm::InstrProfSummaryBuilder::addInternalCount(), llvm::WinEHFuncInfo::addIPToStateRange(), llvm::orc::LLJIT::addIRModule(), llvm::LiveIntervals::addKillFlags(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::MachineFunction::addLandingPad(), llvm::orc::LLLazyJIT::addLazyIRModule(), llvm::sys::DynamicLibrary::HandleSet::AddLibrary(), llvm::codeview::DebugLinesSubsection::addLineAndColumnInfo(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::addLiveIn(), addLiveInRegs(), llvm::addLiveIns(), llvm::DwarfCompileUnit::addLocationAttribute(), addLoopMetadata(), llvm::DwarfExpression::addMachineRegExpression(), addMask(), llvm::X86Operand::addMaskPairOperands(), llvm::X86Operand::addMemOffsOperands(), llvm::X86Operand::addMemOperands(), llvm::SITargetLowering::AddMemOpInit(), llvm::DwarfCompileUnit::addMemoryLocation(), llvm::sandboxir::MemDGNode::addMemPred(), llvm::InstrProfWriter::addMemProfData(), llvm::MachineInstrBuilder::addMetadata(), llvm::Value::addMetadata(), llvm::VPlanTransforms::addMiddleCheck(), llvm::LTOCodeGenerator::addModule(), llvm::ModuleSymbolTable::addModule(), llvm::CodeGenPassBuilder< AMDGPUCodeGenPassBuilder, GCNTargetMachine >::addModulePass(), llvm::AccelTable< DataT >::addName(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::DominatorTreeBase< BlockT, false >::addNewBlock(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::addNewSection(), llvm::objcopy::elf::Object::addNewSymbolTable(), llvm::DataDependenceGraph::addNode(), llvm::GISelInstProfileBuilder::addNodeIDMachineOperand(), llvm::SymbolTableListTraits< ValueSubClass, Args >::addNodeToList(), addNonConstUser(), llvm::IRMover::IdentifiedStructTypeSet::addNonOpaque(), addNoRecurseAttrsTopDown(), llvm::logicalview::LVScope::addObject(), llvm::orc::LLJIT::addObjectFile(), llvm::IRMover::IdentifiedStructTypeSet::addOpaque(), llvm::MachineInstr::addOperand(), llvm::MachineInstr::addOperand(), addOperands(), addOpsFromMDNode(), llvm::CallBase::addParamAttr(), llvm::CallBase::addParamAttr(), llvm::addParamAttribute(), llvm::CallBase::addParamAttrs(), llvm::TargetPassConfig::addPass(), llvm::CodeGenTargetMachineImpl::addPassesToEmitMC(), llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::addPassesToHandleExceptions(), llvm::TargetPassConfig::addPassesToHandleExceptions(), addPermMasks(), llvm::PassBuilder::addPGOInstrPassesForO0(), llvm::rdf::BlockNode::addPhi(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::RuntimeCheckingPtrGroup::addPointer(), llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::SIScheduleBlock::addPred(), llvm::SUnit::addPred(), llvm::SIMachineFunctionInfo::addPreloadedKernArg(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), llvm::pdb::GSIStreamBuilder::addPublicSymbols(), llvm::CodeGenDataWriter::addRecord(), llvm::CodeGenDataWriter::addRecord(), llvm::DwarfExpression::addReg(), llvm::LivePhysRegs::addReg(), llvm::MachineInstrBuilder::addReg(), llvm::MachineRegisterInfo::addRegAllocationHint(), addRegDescribedVar(), llvm::TargetLoweringBase::addRegisterClass(), llvm::mca::RegisterFile::addRegisterRead(), llvm::mca::addRegisterReadWrite(), llvm::mca::RegisterFile::addRegisterWrite(), addRegLanes(), llvm::X86Operand::addRegOperands(), XtensaOperand::addRegOperands(), llvm::MachineRegisterInfo::addRegOperandToUseList(), llvm::LoongArchAsmBackend::addReloc(), llvm::RISCVAsmBackend::addReloc(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), AddRequiredExtensionForVMULL(), llvm::jitlink::Addressable::Addressable(), addresses16Bits(), llvm::AddressRange::AddressRange(), llvm::DwarfUnit::addRnglistsBase(), llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::addRuntimeChecks(), llvm::DwarfFile::addScopeVariable(), llvm::RISCVConstantPoolValue::addSelectionDAGCSEId(), llvm::M68kInstrInfo::AddSExt(), llvm::LPMUpdater::addSiblingLoops(), llvm::DwarfExpression::addSignedConstant(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addSourceLine(), llvm::LazyCallGraph::addSplitFunction(), llvm::LazyCallGraph::addSplitRefRecursiveFunctions(), llvm::X86Operand::addSrcIdxOperands(), llvm::AttrBuilder::addStackAlignmentAttr(), llvm::dwarf_linker::parallel::DIEGenerator::addStringPlaceholderAttribute(), llvm::DwarfDebug::addStringTypeLoc(), llvm::RegionBase< Tr >::addSubRegion(), llvm::RegionBase< RegionTraits< MachineFunction > >::addSubRegion(), llvm::SIScheduleBlock::addSucc(), llvm::mca::LSUnit::MemoryGroup::addSuccessor(), llvm::ScheduleDAGTopologicalSort::AddSUnitWithoutPredecessors(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::cas::ondisk::DatabaseFile::addTable(), llvm::MachineOperand::addTargetFlag(), llvm::Record::addTemplateArg(), addToAccessGroupList(), llvm::AAPointerInfo::RangeList::addToAllOffsets(), llvm::BlockFrequencyInfoImplBase::addToDist(), addToFwdRegWorklist(), llvm::HexagonPacketizerList::addToPacket(), llvm::WebAssemblyExceptionInfo::addTopLevelException(), llvm::LoopInfoBase< BasicBlock, Loop >::addTopLevelLoop(), llvm::SIMachineFunctionInfo::addToPrologEpilogSGPRSpills(), addTryBlockMapEntry(), llvm::DwarfUnit::addType(), llvm::pdb::TpiStreamBuilder::addTypeRecord(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), llvm::DwarfUnit::addUInt(), llvm::pdb::DbiModuleDescriptorBuilder::addUnmergedSymbols(), llvm::DwarfExpression::addUnsignedConstant(), llvm::DwarfExpression::addUnsignedConstant(), llvm::SSAUpdaterBulk::AddUse(), llvm::MachineInstrBuilder::addUse(), llvm::mca::WriteState::addUser(), llvm::cl::bits_storage< DataType, StorageClass >::addValue(), llvm::cl::list_storage< DataType, StorageClass >::addValue(), llvm::Record::addValue(), llvm::SSAValueNameMap::addValue(), addValueAffectedByCondition(), llvm::InstrProfRecord::addValueData(), llvm::DebugLocEntry::addValues(), llvm::TGVarScope::addVar(), llvm::DbgValueRangeTable::addVariable(), llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::DbgVariableRecord::addVariableLocationOps(), llvm::ConstraintSystem::addVariableRow(), addVariantDeclaration(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), addVPMetadata(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), llvm::DwarfExpression::addWasmLocation(), AdjustBaseAndOffset(), llvm::ARMBasicBlockUtils::adjustBBOffsetsAfter(), AdjustBlendMask(), adjustByValArgAlignment(), adjustCostForPairing(), adjustDown(), slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::adjustExtracts(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), adjustFixupValue(), adjustFixupValue(), llvm::ARMAsmBackend::adjustFixupValue(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::SparcTargetLowering::AdjustInstrPostInstrSelection(), llvm::TargetLowering::AdjustInstrPostInstrSelection(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::adjustPqBits(), llvm::RISCVRegisterInfo::adjustReg(), adjust::adjustRelativeBranch(), llvm::IntervalMapImpl::adjustSiblingSizes(), llvm::X86RegisterInfo::adjustStackMapLiveOutMask(), adjustUp(), llvm::RegPressureTracker::advance(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::PPCHazardRecognizer970::AdvanceCycle(), llvm::PredIterator< BasicBlock, Value::user_iterator >::advancePastNonTerminators(), llvm::GCNSchedStrategy::advanceStage(), llvm::SectionEntry::advanceStubOffset(), llvm::LiveRange::advanceTo(), llvm::LiveRange::advanceTo(), llvm::AAResults::alias(), llvm::BasicAAResult::alias(), llvm::LegalizerInfo::aliasActionDefinitions(), llvm::LegalizeRuleSet::aliasTo(), llvm::Align::Align(), llvm::alignAddr(), llvm::alignDown(), llvm::alignTo(), llvm::alignTo(), llvm::alignTo(), llvm::alignTo(), llvm::alignToPowerOf2(), llvm::alignToPowerOf2(), llvm::LoopSafetyInfo::allLoopPathsLeadToBlock(), llvm::ms_demangle::ArenaAllocator::alloc(), llvm::AllocaInst::AllocaInst(), llvm::ms_demangle::ArenaAllocator::allocArray(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::Allocate(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::Allocate(), llvm::parallel::PerThreadAllocator< BumpPtrAllocator >::Allocate(), allocateFixedSGPRInputImpl(), llvm::GVNExpression::AggregateValueExpression::allocateIntOperands(), llvm::AMDGPUMachineFunction::allocateLDSGlobal(), llvm::PGOContextualProfile::allocateNextCallsiteIndex(), llvm::PGOContextualProfile::allocateNextCounterIndex(), llvm::cas::MappedFileRegionArena::allocateOffset(), llvm::GVNExpression::BasicExpression::allocateOperands(), llvm::RegAllocBase::allocatePhysRegs(), llvm::SITargetLowering::allocatePreloadKernArgSGPRs(), allocateSGPR32InputImpl(), llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPRLane(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::AllocateSlow(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::SITargetLowering::allocateSystemSGPRs(), allocateVGPR32Input(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::StringMapEntryBase::allocateWithKey(), llvm::GCNUserSGPRUsageInfo::allocKernargPreloadSGPRs(), allocset(), llvm::ms_demangle::ArenaAllocator::allocUnalignedBuffer(), allowPGOOutlining(), allowsPreservingNUW(), llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::AMDGPUTargetLowering::allUsesHaveSourceMods(), allUsesOfLoadAndStores(), AllUsesOfValueWillTrapIfNull(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::AMDGPULibFunc::AMDGPULibFunc(), llvm::AMDGPURegisterBankInfo::AMDGPURegisterBankInfo(), llvm::coro::Shape::analyze(), llvm::ForwardDominanceFrontierBase< BlockT >::analyze(), Analyze_CC_Sparc64_Full(), Analyze_CC_Sparc64_Half(), analyzeArgSplit(), AnalyzeArguments(), llvm::analyzeArguments(), llvm::CodeMetrics::analyzeBasicBlock(), llvm::AArch64InstrInfo::analyzeBranch(), llvm::ARCInstrInfo::analyzeBranch(), llvm::ARMBaseInstrInfo::analyzeBranch(), llvm::AVRInstrInfo::analyzeBranch(), llvm::MSP430InstrInfo::analyzeBranch(), llvm::SystemZInstrInfo::analyzeBranch(), llvm::XtensaInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::AnalyzeBranchImpl(), llvm::AArch64InstrInfo::analyzeBranchPredicate(), llvm::X86InstrInfo::analyzeBranchPredicate(), analyzeCallOperands(), analyzeCandidate(), llvm::AArch64InstrInfo::analyzeCompare(), llvm::SystemZInstrInfo::analyzeCompare(), analyzeCompressibleUses(), slpvectorizer::BoUpSLP::analyzeConstantStrideCandidate(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), analyzeGlobalAux(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::BlockFrequencyInfoImplBase::analyzeIrreducible(), llvm::AArch64InstrInfo::analyzeLoopForPipelining(), llvm::RISCVInstrInfo::analyzeLoopForPipelining(), analyzeLoopUnrollCost(), analyzeModule(), llvm::AnalyzePhysRegInBundle(), llvm::AMDGPUResourceUsageAnalysisImpl::analyzeResourceUsage(), llvm::analyzeReturnValues(), llvm::ARMBaseInstrInfo::analyzeSelect(), llvm::LanaiInstrInfo::analyzeSelect(), llvm::RISCVInstrInfo::analyzeSelect(), llvm::TargetInstrInfo::analyzeSelect(), llvm::Any::any_cast, llvm::Any::any_cast, llvm::Any::any_cast, llvm::APFixedPoint::APFixedPoint(), llvm::APFloat::APFloat(), llvm::APInt::APInt(), APIntToHexString(), llvm::DIExpression::append(), llvm::LiveRange::append(), llvm::SmallString< 0 >::append(), llvm::MCObjectStreamer::appendContents(), appendDigit(), llvm::objcopy::elf::OwnedDataSection::appendHexData(), llvm::DIExpression::appendOpsToArg(), llvm::appendReversedLoopsToWorklist(), llvm::mca::Pipeline::appendStage(), llvm::DWARFTypePrinter< DieType >::appendTemplateParameters(), llvm::DIExpression::appendToStack(), llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameBefore(), llvm::BitVector::apply(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::apply(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::jitlink::BasicLayout::apply(), llvm::LegalizeRuleSet::apply(), llvm::SampleProfileInference< FT >::apply(), llvm::CombinerHelper::applyAshShlToSextInreg(), llvm::CombinerHelper::applyBuildInstructionSteps(), llvm::CombinerHelper::applyCombineBuildUnmerge(), llvm::CombinerHelper::applyCombineDivRem(), llvm::CombinerHelper::applyCombineI2PToP2I(), llvm::CombinerHelper::applyCombineMulToShl(), llvm::CombinerHelper::applyCombineP2IToI2P(), llvm::CombinerHelper::applyCombineShiftToUnmerge(), llvm::CombinerHelper::applyCombineShuffleConcat(), llvm::CombinerHelper::applyCombineShuffleToBuildVector(), llvm::CombinerHelper::applyCombineUnmergeConstant(), llvm::CombinerHelper::applyCombineUnmergeMergeToPlainValues(), llvm::CombinerHelper::applyCombineUnmergeZExtToZExt(), applyDebugify(), applyDebugify(), llvm::RegisterBankInfo::applyDefaultMapping(), applyDivisibilityOnMinMaxExpr(), llvm::RuntimeDyldImpl::applyExternalSymbolRelocations(), llvm::CombinerHelper::applyExtractAllEltsFromBuildVector(), llvm::CombinerHelper::applyExtractVecEltBuildVec(), ApplyFeatureFlag(), llvm::ARMAsmBackend::applyFixup(), llvm::AVRAsmBackend::applyFixup(), llvm::CSKYAsmBackend::applyFixup(), llvm::jitlink::aarch32::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::ppc64::applyFixup(), llvm::jitlink::systemz::applyFixup(), llvm::jitlink::x86::applyFixup(), llvm::jitlink::x86_64::applyFixup(), llvm::LoongArchAsmBackend::applyFixup(), llvm::RISCVAsmBackend::applyFixup(), llvm::jitlink::aarch32::applyFixupThumb(), llvm::CombinerHelper::applyFunnelShiftConstantModulo(), llvm::CombinerHelper::applyFunnelShiftToRotate(), llvm::DWARFUnitHeader::applyIndexEntry(), llvm::dwarf_linker::parallel::SectionDescriptor::applyIntVal(), llvm::CombinerHelper::applyLshrOfTruncOfLshr(), llvm::RegBankSelect::applyMapping(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingSMULU64(), llvm::AMDGPU::RegBankLegalizeHelper::applyMappingTrivial(), llvm::jitlink::applyPACSigningToModInitPointers(), llvm::dwarf_linker::parallel::OutputSections::applyPatches(), llvm::CombinerHelper::applyPtrAddImmedChain(), llvm::PBQP::applyR1(), llvm::PBQP::applyR2(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::applyRemapping(), llvm::CombinerHelper::applyRotateOutOfRange(), llvm::CombinerHelper::applySDivByPow2(), llvm::CombinerHelper::applySextInRegOfLoad(), llvm::CombinerHelper::applySextTruncSextLoad(), llvm::CombinerHelper::applyShiftImmedChain(), llvm::CombinerHelper::applyShiftOfShiftedLogic(), llvm::dwarf_linker::parallel::SectionDescriptor::applySLEB128(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfUnit::applySubprogramDefinitionAttributes(), llvm::CombinerHelper::applyUDivByPow2(), llvm::dwarf_linker::parallel::SectionDescriptor::applyULEB128(), llvm::OpenMPIRBuilder::applyWorkshareLoop(), llvm::ir2vec::Embedding::approximatelyEquals(), llvm::APSInt::APSInt(), areCandidatesToMergeOrPair(), areCFlagsAccessedBetweenInstrs(), llvm::sandboxir::VecUtils::areConsecutive(), llvm::MemoryDepChecker::areDepsSafe(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::AArch64InstrInfo::areMemAccessesTriviallyDisjoint(), llvm::LanaiInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::PPCInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::RISCVInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::SIInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::TargetInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::RISCVDAGToDAGISel::areOffsetsWithinAlignment(), areSlicesNextToEachOther(), areStridedAccessesIndependent(), llvm::CallLowering::ArgInfo::ArgInfo(), llvm::MachineFunction::ArgRegPair::ArgRegPair(), ARM64EmitUnwindCode(), ARM64EmitUnwindInfoForSegment(), ARM64FindSegmentsInFunction(), ARM64ProcessEpilogs(), llvm::object::DynamicRelocRef::arm64x_reloc_begin(), llvm::object::DynamicRelocRef::arm64x_reloc_end(), ARMEmitUnwindCode(), ARMEmitUnwindInfo(), llvm::ARMRegisterBankInfo::ARMRegisterBankInfo(), llvm::msgpack::ArrayDocNode::ArrayDocNode(), llvm::json::OStream::arrayEnd(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::ArrayRef(), llvm::ValueLatticeElement::asConstantRange(), llvm::APInt::ashrInPlace(), llvm::rdf::RegisterRef::asMaskIdx(), llvm::rdf::RegisterRef::asMCReg(), llvm::Register::asMCReg(), llvm::rdf::RegisterRef::asMCRegUnit(), llvm::VirtRegOrUnit::asMCRegUnit(), assertBranchOrSelectConditionHoisted(), assertCHRRegionsHaveBiasedBranchOrSelect(), llvm::CanonicalLoopInfo::assertOK(), llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterResize(), AssertSorted(), llvm::BCChar6::assertValid(), llvm::BCFixed< Width >::assertValid(), llvm::BCFixed< Width >::assertValid(), llvm::BCLiteral< Value >::assertValid(), llvm::BCVBR< Width >::assertValid(), llvm::LiveRange::assign(), llvm::LiveRegMatrix::assign(), llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), llvm::ARMFrameLowering::assignCalleeSavedSpillSlots(), llvm::RISCVFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::RegBankSelect::assignInstr(), llvm::RegBankSelect::assignmentMatch(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::assignName(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::assignOffsetsToStrings(), llvm::CallGraphSCCPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::RegScavenger::assignRegToScavengingIndex(), assignSections(), assignSlotsUsingVGPRBlocks(), llvm::SelectionDAG::AssignTopologicalOrder(), llvm::BitcodeReaderValueList::assignValue(), llvm::VirtRegMap::assignVirt2Phys(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::VirtRegOrUnit::asVirtualReg(), llvm::orc::AsynchronousSymbolQuery::AsynchronousSymbolQuery(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::at(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::at(), llvm::MapVector< StringRef, HashData >::at(), llvm::MapVector< StringRef, HashData >::at(), llvm::StableFunctionMap::at(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::at(), llvm::AtomicSDNode::AtomicSDNode(), llvm::VPlanTransforms::attachCheckBlock(), llvm::DwarfCompileUnit::attachLowHighPC(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::AttrBuilder::AttrBuilder(), llvm::DWARFDie::attribute_iterator::attribute_iterator(), llvm::json::OStream::attributeBegin(), llvm::json::OStream::attributeEnd(), llvm::AttributeListImpl::AttributeListImpl(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::AttributeSpec(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::AttributeSpec(), llvm::object::XCOFFObjectFile::auxiliaryHeader32(), llvm::object::XCOFFObjectFile::auxiliaryHeader64(), llvm::objcopy::coff::AuxSymbol::AuxSymbol(), llvm::orc::DebugObject::awaitTargetMem(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::back(), llvm::BitVector::back(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::back(), llvm::memprof::CallStack< NodeT, IteratorT >::back(), llvm::MutableArrayRef< char >::back(), llvm::PriorityWorklist< T, VectorT, MapT >::back(), llvm::sandboxir::BasicBlock::back(), llvm::SetVector< EdgeType * >::back(), llvm::SmallBitVector::back(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::StringRef::back(), llvm::TinyPtrVector< ReachingDef >::back(), llvm::BitstreamWriter::BackpatchByte(), llvm::PBQP::backpropagate(), llvm::ImutAVLFactory< ImutInfo >::balanceTree(), llvm::coro::BaseCloner::BaseCloner(), llvm::codeview::ContinuationRecordBuilder::begin(), llvm::DWARFDebugAbbrev::begin(), llvm::GFConstant::begin(), llvm::ir2vec::Vocabulary::begin(), llvm::LoopBlocksTraversal::begin(), llvm::sandboxir::BasicBlock::begin(), llvm::TimeTraceProfiler::begin(), llvm::TimeTraceProfiler::begin(), llvm::yaml::begin(), llvm::memprof::CallStack< NodeT, IteratorT >::beginAfterSharedPrefix(), llvm::DwarfCFIException::beginBasicBlockSection(), llvm::DwarfExpression::beginEntryValueExpression(), llvm::ARMException::beginFunction(), llvm::DebugHandlerBase::beginFunction(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfDebug::beginFunctionImpl(), llvm::LiveRange::beginIndex(), llvm::DebugHandlerBase::beginInstruction(), llvm::DwarfDebug::beginInstruction(), llvm::DwarfDebug::beginModule(), llvm::LoopBlocksDFS::beginPostorder(), llvm::LoopBlocksDFS::beginRPO(), bigEndianByteAt(), llvm::ConstantRange::binaryOp(), llvm::BitCastInst::BitCastInst(), llvm::detail::DoubleAPFloat::bitcastToAPInt(), llvm::detail::IEEEFloat::bitcastToAPInt(), bitcastToVectorElement32(), llvm::EVT::bitsGE(), llvm::MVT::bitsGE(), llvm::EVT::bitsGT(), llvm::MVT::bitsGT(), llvm::EVT::bitsLE(), llvm::MVT::bitsLE(), llvm::EVT::bitsLT(), llvm::MVT::bitsLT(), llvm::BlockCoverageInference::BlockCoverageInference(), llvm::LoopAccessInfo::blockNeedsPredication(), llvm::LoopVectorizationLegality::blockNeedsPredication(), llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::BlockToIndexMapping::blockToIndex(), bothcases(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::branched(), llvm::coverage::mcdc::BranchParameters::BranchParameters(), llvm::BranchProbability::BranchProbability(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), breakBackedgeIfNotTaken(), llvm::breakLoopBackedge(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), BrPHIToSelect(), llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::build(), llvm::orc::BloomFilterBuilder::build(), llvm::rdf::DataFlowGraph::build(), llvm::AMDGPULegalizerInfo::buildAbsGlobalAddress(), llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap(), llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicFlagInst(), llvm::buildAtomicFloatingRMWInst(), llvm::buildAtomicInitInst(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::buildAtomicRMWInst(), llvm::buildBarrierInst(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildBrCond(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), buildCallOperands(), llvm::MachineIRBuilder::buildCast(), llvm::AArch64InstrInfo::buildClearRegister(), buildClonedLoopBlocks(), buildClonedLoops(), llvm::MachineIRBuilder::buildConstant(), BuildConstantFromSCEV(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::MachineIRBuilder::buildConstantPool(), llvm::LegalizerHelper::buildConstantShiftPart(), llvm::MachineIRBuilder::buildConstDbgValue(), buildCopyFromRegs(), buildCopyToRegs(), llvm::MachineIRBuilder::buildDbgLabel(), llvm::buildDbgValueForSpill(), buildDefaultVLOps(), llvm::MachineIRBuilder::buildDeleteTrailingVectorElements(), llvm::MachineIRBuilder::buildDirectDbgValue(), llvm::MachineIRBuilder::buildDynStackAlloc(), llvm::buildEnqueueKernel(), BuildExactSDIV(), BuildExactUDIV(), slpvectorizer::BoUpSLP::buildExternalUses(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::MachineIRBuilder::buildExtract(), buildExtractionBlockSet(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFIDbgValue(), buildFixItLine(), buildFrameDebugInfo(), llvm::MachineIRBuilder::buildFrameIndex(), buildFrameType(), llvm::PassBuilder::buildFunctionSimplificationPipeline(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::VPlanSlp::buildGraph(), llvm::MCPseudoProbeDecoder::buildGUID2FuncDescMap(), llvm::MachineIRBuilder::buildIndirectDbgValue(), llvm::MachineIRBuilder::buildInsert(), llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstr(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), llvm::MachineIRBuilder::buildLoad(), llvm::AMDGPULegalizerInfo::buildLoadInputValue(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), llvm::BuildMI(), llvm::BuildMI(), llvm::PassBuilder::buildModuleSimplificationPipeline(), llvm::buildModuleSummaryIndex(), llvm::AMDGPULegalizerInfo::buildMultiply(), llvm::buildNDRange(), buildNew(), llvm::PassBuilder::buildO0DefaultPipeline(), llvm::DICompositeType::buildODRType(), buildOpBitcast(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::ARMBaseInstrInfo::buildOutlinedFrame(), buildOverlapMapAndRecordDeclares(), BuildPACM(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), buildPCRelGlobalAddress(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), llvm::PassBuilder::buildPerModuleDefaultPipeline(), llvm::opt::OptTable::buildPrefixChars(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), llvm::LazyCallGraph::buildRefSCCs(), buildRegSequence16(), llvm::hlsl::rootsig::MetadataBuilder::BuildRootSignature(), llvm::ScheduleDAGInstrs::buildSchedGraph(), buildScratchExecCopy(), llvm::TargetLowering::BuildSDIV(), llvm::CombinerHelper::buildSDivOrSRemUsingMul(), llvm::MachineIRBuilder::buildShuffleSplat(), llvm::MachineIRBuilder::buildShuffleVector(), llvm::orc::buildSimpleReexportsAliasMap(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), llvm::SIRegisterInfo::buildSpillLoadStore(), buildSplatSplitS64WithVL(), llvm::MachineIRBuilder::buildSplatVector(), llvm::MachineIRBuilder::buildStore(), llvm::MachineIRBuilder::buildStore(), slpvectorizer::BoUpSLP::buildTree(), slpvectorizer::BoUpSLP::buildTree(), buildTreeReduction(), llvm::TargetLowering::BuildUDIV(), llvm::CombinerHelper::buildUDivOrURemUsingMul(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineIRBuilder::buildUnmerge(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::bumpCycle(), llvm::SchedBoundary::bumpCycle(), llvm::GCNDownwardRPTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::SchedBoundary::bumpNode(), llvm::RegPressureTracker::bumpUpwardPressure(), llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::MachineInstr::bundleWithPred(), llvm::MachineInstr::bundleWithSucc(), BURRSort(), llvm::APInt::byteSwap(), llvm::ARM::WinEH::RuntimeFunction::C(), llvm::cacheAnnotationFromMD(), llvm::CacheCost::CacheCost(), llvm::CachedHashStringRef::CachedHashStringRef(), CalcNodeSethiUllmanNumber(), calcPredicateUsingBooleans(), llvm::BranchProbabilityInfo::calculate(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::LiveIntervalCalc::calculate(), llvm::hlsl::BindingInfoBuilder::calculateBindingInfo(), calculateByteProvider(), llvm::OpenMPIRBuilder::calculateCanonicalLoopTripCount(), llvm::calculateClrEHStateNumbers(), calculateCXXStateNumbers(), llvm::calculateDbgEntityHistory(), llvm::SelectionDAG::calculateDivergence(), llvm::MDNodeOpsKey::calculateHash(), llvm::R600InstrInfo::calculateIndirectAddress(), calculateMMLEIndex(), calculatePrevailingSummary(), calculateRtStride(), calculateSEHStateNumbers(), llvm::codeview::DebugInlineeLinesSubsection::calculateSerializedSize(), calculateShufflevectorMask(), calculateStateNumbersForInvokes(), slpvectorizer::BoUpSLP::calculateTreeCostAndTrimNonProfitable(), llvm::LiveRangeCalc::calculateValues(), calculateVectorIndex(), llvm::dwarf::CallFrameString(), llvm::Interpreter::callFunction(), callHasRegMask(), llvm::PGOCtxProfContext::callsite(), llvm::PGOCtxProfContext::callsite(), llvm::sampleprofutil::callsiteIsHot(), callsShareTOCBase(), llvm::orc::SimpleRemoteEPC::callWrapperAsync(), canBeFeederToNewValueJump(), llvm::DwarfExpression::cancelEntryValue(), canClobberPhysRegDefs(), canCmpInstrBeRemoved(), canCombine(), canCombineOpSel(), canCombineOpSel(), llvm::ARMTargetLowering::canCombineStoreAndExtract(), canConvertSETCCToXori(), canConvertToFMA(), canConvertValue(), canCreateAliasFor(), llvm::RISCVTargetLowering::canCreateUndefOrPoisonForTargetNode(), llvm::TargetLowering::canCreateUndefOrPoisonForTargetNode(), canEmitConjunction(), canEmitConjunction(), canEvaluateShiftedShift(), canExpandVectorCTPOP(), canFoldCopy(), canFoldIntoCSel(), llvm::InstCombiner::canFreelyInvertAllUsersOf(), llvm::SelectionDAG::canIgnoreSignBitOfZero(), llvm::CanInlineCallSite(), canInstrSubstituteCmpInstr(), llvm::AAResults::canInstructionRangeModRef(), canLowerByDroppingElements(), canLowerSRLToRoundingShiftForVT(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::RegBankSelect::EdgeInsertPoint::canMaterialize(), canonicalHeaderAndLatch(), canonicalizeAbs(), canonicalizeBitSelect(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeConstantArg0ToArg1(), llvm::VPlanTransforms::canonicalizeEVLLoops(), canonicalizeICmpBool(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeSaturatedSubtract(), canonicalizeShuffleMaskWithCommute(), canonicalizeShuffleMaskWithHorizOp(), llvm::TargetLoweringBase::canOpTrap(), llvm::TargetInstrInfo::canPredicatePredicatedInstr(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), CanPropagatePredecessorsForPHIs(), canProveExitOnFirstIteration(), CanProveNotTakenFirstIteration(), canReduceVMulWidth(), llvm::LiveRangeEdit::canRematerializeAt(), canRenameComdat(), llvm::canRenameComdatFunc(), llvm::canReplacePointersIfEqual(), llvm::canReplacePointersInUseIfEqual(), canSinkInstructions(), llvm::canSinkOrHoistInst(), canTransformAccumulatorRecursion(), llvm::X86FrameLowering::canUseAsEpilogue(), llvm::X86FrameLowering::canUseAsPrologue(), canVectorize(), llvm::LoopVectorizationLegality::canVectorize(), slpvectorizer::BoUpSLP::canVectorizeLoads(), CanWidenIV(), canWidenShuffleElements(), canWidenShuffleElements(), carryFlagToValue(), llvm::cas::ondisk::TableHandle::cast(), llvm::cast(), llvm::cast(), llvm::cast(), llvm::cast(), llvm::PointerSumType< TagT, MemberTs... >::cast(), llvm::cast_if_present(), llvm::cast_if_present(), llvm::cast_if_present(), CastIntSETCCtoFP(), CC_AArch64_Custom_Block(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), CC_LoongArch(), CC_MipsO32(), CC_PPC32_SPE_CustomSplitFP64(), llvm::CC_RISCV(), CC_Sparc_Assign_SRet(), CC_X86_32_I128_FP128(), CC_X86_32_MCUInReg(), CC_X86_32_RegCall_Assign2Regs(), CC_X86_64_I128(), CC_X86_VectorCallAssignRegister(), llvm::CFGMST< Edge, BBInfo >::CFGMST(), llvm::CFIFunctionFrameStreamer::CFIFunctionFrameStreamer(), llvm::CGDataError::CGDataError(), chainLoadsAndStoresForMemcpy(), chainToBasePointerCost(), llvm::Attributor::changeAfterManifest(), llvm::LLT::changeElementSize(), changeFPCCToANDAArch64CC(), changeFPCCToANDAArch64CC(), llvm::DominatorTreeBase< BlockT, false >::changeImmediateDominator(), llvm::SPIRVGlobalRegistry::changePointerStorageClass(), llvm::MCObjectStreamer::changeSection(), llvm::NVPTXTargetStreamer::changeSection(), ChangesStreamingMode(), llvm::AArch64TargetLowering::changeStreamingMode(), llvm::MachineOperand::ChangeToBA(), llvm::MachineOperand::ChangeToCPI(), llvm::MachineOperand::ChangeToDbgInstrRef(), llvm::MachineOperand::ChangeToES(), llvm::MachineOperand::ChangeToFPImmediate(), llvm::MachineOperand::ChangeToFrameIndex(), llvm::MachineOperand::ChangeToGA(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToMCSymbol(), llvm::LoopInfoBase< BasicBlock, Loop >::changeTopLevelLoop(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineOperand::ChangeToTargetIndex(), llvm::Attributor::changeUseAfterManifest(), llvm::LLT::changeVectorElementCount(), llvm::MVT::changeVectorElementType(), llvm::MVT::changeVectorElementTypeToInteger(), llvm::FileCheckString::Check(), checkAllocContextIds(), CheckAndCreateOffsetAdd(), checkBasicSSA(), checkBiasedBranch(), checkBoolTestSetCCCombine(), checkChars(), checkClobberSanity(), checkConstLocationCompatible(), llvm::FileCheckString::CheckDag(), checkDependency(), checkDot4MulSignedness(), checkEdge(), checkedGetHex(), llvm::Attributor::checkForAllCallSites(), llvm::checkForCycles(), llvm::checkGEPType(), checkGlobalVariableScope(), checkHoistValue(), checkIfSafeAddSequence(), checkIfStatusIsExtracted(), checkIfSupported(), checkImmOpForPKF32InstrReplicatesLower32BitsOfScalarOperand(), TransferTracker::checkInstForNewValues(), checkNode(), llvm::FileCheckString::CheckNot(), llvm::jitlink::aarch32::checkOpcode(), llvm::jitlink::aarch32::checkOpcode(), llvm::ARM::checkPartialMappings(), checkPHIs(), llvm::mca::RegisterFile::checkRAWHazards(), checkReductionInfos(), llvm::LiveIntervals::checkRegMaskInterference(), CheckSame(), checkValidLayout(), llvm::bitfields_details::Impl< Bitfield, StorageType >::checkValue(), llvm::ARM::checkValueMappings(), checkVectorTypesForPromotion(), CheckVGPROverflow(), llvm::checkVOPDRegConstraints(), llvm::object::Archive::Child::Child(), llvm::IDFCalculatorDetail::ChildrenGetterTy< BasicBlock, IsPostDom >::ChildrenGetterTy(), chopOneUTF32(), clampDynamicVectorIndex(), llvm::LegalizeRuleSet::clampNumElements(), clampReturnedValueStates(), llvm::LegalizeRuleSet::clampScalar(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::APFloat::classify(), llvm::ConstantFPRange::classify(), classifyConstantWithOpaquePtr(), llvm::X86InstrInfo::classifyLEAReg(), llvm::X86Subtarget::classifyLocalReference(), llvm::DroppedVariableStats::cleanup(), llvm::FPPassManager::cleanup(), llvm::SCEVExpanderCleaner::cleanup(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::LiveDebugVariables::LDVImpl::clear(), llvm::orc::JITDylib::clear(), llvm::OutlinedHashTree::clear(), llvm::sandboxir::Scheduler::clear(), llvm::StatepointLoweringState::clear(), llvm::rdf::DataFlowGraph::DefStack::clear_block(), llvm::AnalysisManager< LazyCallGraph::SCC, LazyCallGraph & >::clearAnalysis(), llvm::MachineInstr::clearAsmPrinterFlag(), clearAssumptionsOfUsers(), llvm::APInt::clearBit(), llvm::APInt::clearBits(), llvm::GlobalVariable::clearCodeModel(), llvm::MachineInstr::clearFlag(), llvm::MachineInstr::clearFlags(), llvm::SCEVWrapPredicate::clearFlags(), llvm::APInt::clearHighBits(), llvm::ScheduleDAGInstrs::Value2SUsMap::clearList(), llvm::MachineBasicBlock::clearLiveIns(), llvm::APInt::clearLowBits(), llvm::InlineAsm::Flag::clearMemConstraint(), llvm::Value::clearMetadata(), llvm::RegionBase< RegionTraits< MachineFunction > >::clearNodeCache(), llvm::MachineFrameInfo::clearObjectAllocation(), llvm::CoroIdInst::clearPromise(), llvm::MachineRegisterInfo::clearSimpleHint(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::VirtRegMap::clearVirt(), llvm::APIntOps::clmul(), llvm::APIntOps::clmulh(), llvm::APIntOps::clmulr(), TransferTracker::clobberMloc(), clobberRegEntries(), llvm::MachineOperand::clobbersPhysReg(), llvm::VPExpressionRecipe::clone(), llvm::cloneAndAdaptNoAliasScopes(), llvm::CloneAndPruneIntoFromInst(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::DILocation::cloneByMultiplyingDuplicationFactor(), cloneConstantExprWithNewAddressSpace(), llvm::dwarf_linker::parallel::CompileUnit::cloneDIE(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneDieRefAttr(), cloneForLane(), cloneFrom(), llvm::CloneFunctionInto(), llvm::orc::cloneGlobalAliasDecl(), llvm::MachineFunction::cloneInfo(), llvm::MachineFunction::cloneInfoFrom(), llvm::MachineInstr::cloneInstrSymbols(), cloneInstructionInExitBlock(), cloneInstructionsIntoPredecessorBlockAndUpdateSSAUses(), CloneLoopBlocks(), cloneLoopBlocks(), cloneLoopNest(), llvm::cloneLoopWithPreheader(), llvm::MachineInstr::cloneMemRefs(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::CloneModule(), llvm::orc::cloneToContext(), llvm::orc::cloneToNewContext(), llvm::cas::ondisk::UnifiedOnDiskCache::close(), llvm::raw_fd_ostream::close(), llvm::RegPressureTracker::closeBottom(), llvm::LexicalScope::closeInsnRange(), llvm::RegPressureTracker::closeRegion(), llvm::RegPressureTracker::closeTop(), clusterSortPtrAccesses(), llvm::AttributeImpl::cmp(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::FunctionComparator::cmpConstants(), llvm::CmpPredicate::CmpPredicate(), llvm::FunctionComparator::cmpTypes(), coalescable(), coerceArguments(), llvm::VNCoercion::coerceAvailableValueToLoadType(), llvm::LegalizerHelper::coerceToScalar(), llvm::object::coffnamecpy(), llvm::OpenMPIRBuilder::collapseLoops(), collectCallSiteParameters(), collectComplementaryPredicatedMemOps(), collectConcatOps(), collectEHScopeMembers(), llvm::LoopVectorizationCostModel::collectElementTypesForWidening(), llvm::CodeMetrics::collectEphemeralValues(), collectEscapedLocals(), llvm::collectGlobalObjectNameStrings(), collectHomogenousInstGraphLoopInvariants(), collectHWRegs(), collectInsertionElements(), llvm::DDGNode::collectInstructions(), collectInstructionsInBetween(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), collectMetadataInfo(), collectMultiplyFactors(), llvm::GEPOperator::collectOffset(), collectRegionsConstants(), llvm::ScopedNoAliasAAResult::collectScopedDomains(), collectShuffleElements(), collectSingleShuffleElements(), collectTransitivePredecessors(), collectUnswitchCandidates(), collectUnswitchCandidatesWithInjections(), llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), llvm::mca::RegisterFile::collectWrites(), llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::CombinationGenerator(), combineAdd(), combineADDRSPACECAST(), combineAnd(), combineAndNotIntoANDNP(), combineAndNotIntoVANDN(), combineAndShuffleNot(), combineArithReduction(), combineBallotPattern(), combineBinOpOfExtractToReduceTree(), combineBitOpWithMOVMSK(), combineBitOpWithPACK(), combineBitOpWithShift(), combineBlendOfPermutes(), combineBMILogicOp(), combineBROADCAST_LOAD(), combineBVOfConsecutiveLoads(), combineCastedMaskArithmetic(), combineCMov(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineExtractFromVectorLoad(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFMA(), combineFMinFMax(), combineFOr(), combineFP_EXTEND(), combineFP_ROUND(), combineGatherScatter(), combineHorizOpWithShuffle(), combinei64TruncSrlConstant(), combineI8TruncStore(), combineINSERT_SUBVECTOR(), combineIRFlags(), llvm::InstCombinerImpl::combineLoadToNewType(), combineLoadToOperationType(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), llvm::Combiner::combineMachineInstrs(), combineMaskedLoadConstantMask(), combineMinMaxReduction(), combineMOVMSK(), combineMul(), combineOp_VLToVWOp_VL(), combineOr(), combineOrders(), combineOrOfCZERO(), combineOrXorWithSETCC(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineRestoreSETHIi(), llvm::CombinerInfo::CombinerInfo(), llvm::PPCInstrInfo::combineRLWINM(), combineScalarAndWithMaskSetcc(), combineSelect(), llvm::VETargetLowering::combineSelect(), llvm::VETargetLowering::combineSelectCC(), combineSetCC(), combineSetCCMOVMSK(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineShiftToAVG(), combineShiftToMULH(), combineShiftToPMULH(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), combineSignExtendInReg(), combineSIntToFP(), combineStoreToNewValue(), combineStoreToValueType(), combineSub(), combineSubABS(), combineTargetShuffle(), combineToConsecutiveLoads(), combineToExtendBoolVectorInReg(), combineToVCPOP(), combineToVWMACC(), llvm::VETargetLowering::combineTRUNCATE(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineTruncToVnclip(), combineV3I8LoadExt(), combineVectorCompare(), combineVectorHADDSUB(), combineVectorInsert(), combineVectorPack(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSizedSetCCEquality(), combineVectorSizedSetCCEquality(), combineVPMADD(), combineVqdotAccum(), combineVSelectWithAllOnesOrZeros(), combineVWADDSUBWSelect(), combinevXi1ConstantToInteger(), combineWeight(), combineX86AddSub(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), combineXorSubCTLZ(), llvm::sandboxir::Interval< T >::comesBefore(), llvm::json::OStream::comment(), llvm::codeview::DebugLinesSubsection::commit(), llvm::codeview::DebugStringTableSubsection::commit(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::mca::WriteRef::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::pdb::InfoStreamBuilder::commit(), llvm::pdb::PDBFileBuilder::commit(), llvm::pdb::TpiStreamBuilder::commit(), commitFpm(), llvm::pdb::DbiModuleDescriptorBuilder::commitSymbolStream(), llvm::InstCombinerImpl::commonIDivRemTransforms(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::yaml::commonSectionMapping(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::ShuffleVectorInst::commute(), llvm::TargetInstrInfo::commuteInstruction(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::RISCVInstrInfo::commuteInstructionImpl(), llvm::SIInstrInfo::commuteInstructionImpl(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::ShuffleVectorInst::commuteShuffleMask(), commuteVPTERNLOG(), CompactSwizzlableVector(), llvm::APFloat::compare(), llvm::detail::IEEEFloat::compare(), llvm::FunctionComparator::compare(), llvm::ICmpInst::compare(), llvm::IRComparer< T >::compare(), llvm::detail::IEEEFloat::compareAbsoluteValue(), compareCmp(), llvm::ScaledNumbers::compareImpl(), llvm::MDNodeOpsKey::compareOps(), llvm::ValueDFS_Compare::comparePHIRelated(), CompareSCEVComplexity(), llvm::FunctionComparator::compareSignature(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::APSInt::compareValues(), llvm::LTOCodeGenerator::compileOptimized(), completeEphemeralValues(), llvm::HvxSelector::completeToPerfect(), llvm::BTFTypeDerived::completeType(), llvm::AMDGPU::VOPD::ComponentLayout::ComponentLayout(), llvm::AMDGPU::VOPD::ComponentProps::ComponentProps(), llvm::HexagonEvaluator::composeWithSubRegIndex(), compress_chunks_parallel(), compress_parents_parallel(), compress_subtree_to_parent_node(), CompressEVEXImpl(), llvm::GenericUniformityAnalysisImpl< ContextT >::compute(), llvm::EHStreamer::computeActionsTable(), computeAliasSummary(), computeAllocaDefaultAlign(), llvm::ComputeASanStackFrameLayout(), llvm::LoopVectorizationPlanner::computeBestVF(), computeBlockRuns(), computeBucketCount(), llvm::codelayout::computeCacheDirectedLayout(), computeCalleeSaveRegisterPairs(), llvm::ScalarEvolution::computeConstantDifference(), llvm::computeConstantRange(), llvm::TargetLowering::ComputeConstraintToUse(), computeConstraintToUse(), llvm::VPExpressionRecipe::computeCost(), llvm::VPHistogramRecipe::computeCost(), llvm::VPInstruction::computeCost(), llvm::VPReductionRecipe::computeCost(), llvm::VPReplicateRecipe::computeCost(), llvm::VPWidenMemoryRecipe::computeCost(), llvm::sampleprofutil::SampleCoverageTracker::computeCoverage(), llvm::ComputeCrossModuleImport(), ComputeCrossModuleImportForModuleFromIndexForTest(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), llvm::ProfileSummaryBuilder::computeDetailedSummary(), computeDomSubtreeCost(), computeExprForSpill(), computeExprForSpill(), llvm::codelayout::computeExtTspLayout(), llvm::KnownBits::computeForAddCarry(), computeForSatAddSub(), llvm::KnownBits::computeForSubBorrow(), llvm::MCAssembler::computeFragmentSize(), computeFunctionSummary(), computeGEPToVectorIndex(), ComputeHash(), ReachabilityQueryInfo< ToTy >::computeHashValue(), computeHeuristicUnrollFactor(), ModuleImportsManager::computeImportForModule(), computeIndirectRegIndex(), llvm::RISCV::RISCVVSETVLIInfoAnalysis::computeInfoForInstr(), llvm::MCSchedModel::computeInstrLatency(), llvm::TargetSchedModel::computeInstrLatency(), llvm::DivergencePropagator< ContextT >::computeJoinPoints(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsForLoadV(), computeKnownBitsForPRMT(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::computeKnownBitsFromContext(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), llvm::GISelValueTracking::computeKnownBitsImpl(), computeKnownFPClass(), computeKnownFPClassFromContext(), computeLabelDiff(), llvm::ComputeLinearIndex(), computeLiveInValues(), computeLiveInValues(), computeLiveOutSeed(), computeLoadStoreDefaultAlign(), computeLoongArchDataLayout(), llvm::ICFLoopSafetyInfo::computeLoopSafetyInfo(), llvm::SimpleLoopSafetyInfo::computeLoopSafetyInfo(), llvm::computeMachineUniformityInfo(), llvm::RegBankSelect::computeMapping(), llvm::MachineFrameInfo::computeMaxCallFrameSize(), llvm::LoopVectorizationCostModel::computeMaxVF(), computeMergedBranchWeights(), slpvectorizer::BoUpSLP::computeMinimumValueSizes(), ComputeNumSignBits(), llvm::SelectionDAG::ComputeNumSignBits(), computeNumSignBitsBinOp(), llvm::RISCVTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), ComputeNumSignBitsImpl(), llvm::DIE::computeOffsetsAndAbbrevs(), computeOpenMPScheduleType(), llvm::computePeelCount(), llvm::rdf::Liveness::computePhiInfo(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computePointerICmp(), computePRMT(), llvm::mca::computeProcResourceMasks(), llvm::RegisterClassInfo::computePSetLimit(), ComputePTXValueVTs(), llvm::hlsl::rootsig::computeRangeBound(), llvm::IndexedReference::computeRefCost(), llvm::MachineBasicBlock::computeRegisterLiveness(), llvm::TargetLoweringBase::computeRegisterProperties(), computeRISCVDataLayout(), llvm::SwitchCG::SwitchLowering::computeSplitWorkItemInfo(), llvm::LiveInterval::computeSubRangeUndefs(), llvm::SampleProfileSummaryBuilder::computeSummaryForProfiles(), llvm::MachObjectWriter::computeSymbolTable(), computeSymbolTableSize(), llvm::LegacyLegalizerInfo::computeTables(), computeTargetABI(), llvm::MipsABIInfo::computeTargetABI(), llvm::memprof::computeUndriftMap(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators(), llvm::computeUnrollCount(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ComputeValueTypes(), computeVectorAddr(), llvm::SelectionDAG::computeVectorKnownZeroElements(), llvm::RISCVTargetLowering::computeVLMax(), llvm::RISCVTargetLowering::computeVLMAXBounds(), computeVTableFuncs(), computeZeroableShuffleElements(), computeZeroableShuffleElements(), concatenateTwoVectors(), llvm::concatenateVectors(), concatSubVectors(), llvm::ConcurrentHashTableByPtr< KeyTy, KeyDataTy, AllocatorTy, Info >::ConcurrentHashTableByPtr(), llvm::DirectedGraph< DDGNode, DDGEdge >::connect(), llvm::VPBlockUtils::connectBlocks(), ConnectEpilog(), connectEpilogueVectorLoop(), ConnectProlog(), llvm::VPBasicBlock::connectToPredecessors(), llvm::sys::fs::mapped_file_region::const_data(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantAggrKeyType< ConstantArray >::ConstantAggrKeyType(), ConstantBuildVector(), llvm::ConstantExprKeyType::ConstantExprKeyType(), llvm::DIExpression::constantFold(), constantFoldAndGroupOps(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldICmp(), llvm::ConstantFoldIntToFloat(), llvm::ConstantFoldTerminator(), llvm::ConstantFoldUnaryInstruction(), llvm::ConstantFoldUnaryOpOperand(), constantFoldUser(), llvm::ConstantFPRange::ConstantFPRange(), llvm::ConstantPtrAuthKeyType::ConstantPtrAuthKeyType(), llvm::ConstantRange::ConstantRange(), llvm::ConstantRangeList::ConstantRangeList(), llvm::ConstantRangeListAttributeImpl::ConstantRangeListAttributeImpl(), llvm::constrainOperandRegClass(), llvm::constrainOperandRegClass(), llvm::constrainSelectedInstRegOperands(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::LiveIntervalCalc::constructMainRangeFromSubranges(), llvm::LiveIntervals::constructMainRangeFromSubranges(), constructOverloadTypeName(), llvm::DwarfCompileUnit::constructScopeDIE(), constructSegment(), ConstructSSAForLoadSet(), llvm::DwarfUnit::constructSubprogramArguments(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), constructSymbolEntry(), llvm::omp::DirectiveNameParser::consume(), llvm::StringRef::consumeInteger(), llvm::orc::ThreadSafeModule::consumingModuleDo(), llvm::AttributeMask::contains(), llvm::ConstantFPRange::contains(), llvm::ConstantFPRange::contains(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LiveRange::Segment::containsInterval(), containsUnconditionalCallSafepoint(), llvm::ContextAndReplaceableUses::ContextAndReplaceableUses(), llvm::orc::LookupState::continueLookup(), llvm::SPIRV::ConvergenceRegion::ConvergenceRegion(), llvm::APFloat::convert(), convertArgumentInfo(), llvm::AArch64PrologueEpilogueCommon::convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), llvm::AMDGPUDisassembler::convertFMAanyK(), convertFPR32ToFPR64(), convertFPR32ToFPR64(), convertFPR64ToFPR128(), convertFPR64ToFPR16(), convertFPR64ToFPR32(), convertFPToInt(), convertFromF16(), convertFromScalableVector(), convertFromScalableVector(), llvm::detail::DoubleAPFloat::convertFromString(), convertImageAddrToPacked(), convertImplicitDefToConstZero(), convertIntLogicToFPLogic(), convertLocVTToValVT(), llvm::AMDGPUDisassembler::convertMacDPPInst(), convertMergedOpToPredOp(), llvm::AMDGPUDisassembler::convertMIMGInst(), convertMLOADToLoadWithUsedBytesMask(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), convertScratchAtomicToFlatAtomic(), ConvertSelectToConcatVector(), ConvertSETCCToXori(), ConvertShiftToMul(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::AMDGPU::convertSMRDOffsetUnits(), convertStackObjects(), llvm::VPlanTransforms::convertToConcreteRecipes(), llvm::APFloat::convertToDouble(), llvm::detail::IEEEFloat::convertToDouble(), llvm::ConverterEBCDIC::convertToEBCDIC(), convertToF16(), llvm::APFloat::convertToFloat(), llvm::detail::IEEEFloat::convertToFloat(), llvm::detail::DoubleAPFloat::convertToHexString(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::detail::DoubleAPFloat::convertToInteger(), llvm::detail::IEEEFloat::convertToInteger(), convertToLocalCopy(), convertToLocalCopy(), convertToParamAS(), convertToScalableVector(), convertToScalableVector(), llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ConverterEBCDIC::convertToUTF8(), convertTwoLoadsAndCmpToVCMPEQUB(), llvm::convertUsersOfConstantsToInstructions(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), convertValue(), convertValVTToLocVT(), llvm::IntervalMapImpl::NodeBase< std::pair< KeyT, KeyT >, ValT, LeafSize >::copy(), llvm::object::OffloadFile::copy(), llvm::MachineFunction::copyAdditionalCallInfo(), llvm::BranchProbabilityInfo::copyEdgeProbabilities(), llvm::SelectionDAG::copyExtraInfo(), copyFlags(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::SmallPtrSetImplBase::copyFrom(), llvm::AArch64InstrInfo::copyGPRRegTuple(), copyMustTailReturn(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARCInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::CSKYInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::SPIRVInstrInfo::copyPhysReg(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), llvm::RISCVInstrInfo::copyPhysRegVector(), copyPhysSubRegs(), copyRegOperand(), copySubReg(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), CopyToFromAsymmetricReg(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), correctParamType(), llvm::InstrProfCorrelatorImpl< IntPtrT >::correlateProfileData(), llvm::VPRegionBlock::cost(), costAndCollectOperands(), costShuffleViaSplitting(), costShuffleViaVRegSplitting(), llvm::SchedBoundary::countResource(), countToEliminateCompares(), llvm::coverage::CoverageFilenamesSectionWriter::CoverageFilenamesSectionWriter(), llvm::coverage::CoverageMapError::CoverageMapError(), llvm::MachO::CPU_SUBTYPE_ARM64E_WITH_PTRAUTH_VERSION(), llvm::ARM::WinEH::RuntimeFunctionARM64::CR(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::CatchReturnInst::Create(), llvm::CleanupReturnInst::Create(), llvm::GetElementPtrInst::Create(), llvm::jitlink::SimpleSegmentAlloc::Create(), llvm::OnDiskChainedHashTable< Info >::Create(), llvm::OnDiskIterableChainedHashTable< InstrProfLookupTrait >::Create(), llvm::AllocationOrder::create(), llvm::cas::MappedFileRegionArena::create(), llvm::coro::BaseCloner::create(), llvm::GlobPattern::create(), llvm::InlineAsmKeyType::create(), llvm::IntervalTree< LVAddress, LVScope * >::create(), llvm::objcopy::dxbc::DXContainerReader::create(), llvm::orc::LocalIndirectStubsInfo< ORCABI >::create(), llvm::sandboxir::CastInst::create(), llvm::sandboxir::ExtractElementInst::create(), llvm::sandboxir::ExtractValueInst::create(), llvm::sandboxir::GetElementPtrInst::create(), llvm::sandboxir::InsertElementInst::create(), llvm::sandboxir::InsertValueInst::create(), llvm::sandboxir::SelectInst::create(), llvm::sandboxir::ShuffleVectorInst::create(), llvm::sandboxir::ShuffleVectorInst::create(), llvm::StructType::create(), llvm::symbolize::SymbolizableObjectFile::create(), llvm::ThinLTOCodeGeneratorImpl::TargetMachineBuilder::create(), llvm::vfs::RedirectingFileSystem::create(), llvm::vfs::RedirectingFileSystem::create(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), llvm::DwarfCompileUnit::createAbstractEntity(), llvm::MatrixBuilder::CreateAdd(), llvm::ScalarEvolution::createAddRecFromPHIWithCasts(), llvm::IRBuilderBase::CreateAggregateCast(), llvm::IRBuilderBase::CreateAlignmentAssumption(), llvm::IRBuilderBase::CreateAlignmentAssumption(), createAMDGPUMCSubtargetInfo(), llvm::IRBuilderBase::CreateAnd(), createAndCheckVectorTypesForPromotion(), llvm::jitlink::ppc64::createAnonymousPointer(), llvm::createAnyOfReduction(), createARMAsmBackend(), llvm::IRBuilderBase::CreateAssumption(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::DIBuilder::createAutoVariable(), llvm::orc::ExecutionSession::createBareJITDylib(), llvm::sandboxir::Context::createBasicBlock(), llvm::DIBuilder::createBasicType(), llvm::createBitMaskForGaps(), createBitOrPointerCast(), llvm::MDBuilder::createBranchWeights(), createCall(), llvm::objcarc::createCallInstWithColors(), createCallWithOps(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalMappingFor(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::OpenMPIRBuilder::createCanonicalScanLoops(), createCBufferLoad(), llvm::createCFAOffset(), createCheckDebugifyFunctionPass(), createCheckDebugifyModulePass(), llvm::DIBuilder::createClassType(), llvm::coro::BaseCloner::createClone(), llvm::coro::SwitchCloner::createClone(), createCmpXchgInstFun(), llvm::DIBuilder::createCompileUnit(), llvm::AArch64TargetLowering::createComplexDeinterleavingIR(), llvm::ARMTargetLowering::createComplexDeinterleavingIR(), createCoroSave(), llvm::LiveIntervalCalc::createDeadDefs(), createDebugifyFunctionPass(), createDebugifyModulePass(), llvm::DbgVariableRecord::createDebugIntrinsic(), llvm::createDefaultScheduler(), createDefCFAExpression(), createDefCFAExpression(), createDefCFAOffset(), llvm::MemorySSA::createDefinedAccess(), llvm::DDGBuilder::createDefUseEdge(), llvm::IRBuilderBase::CreateDereferenceableAssumption(), llvm::OpenMPIRBuilder::createDispatchFiniFunction(), llvm::OpenMPIRBuilder::createDispatchInitFunction(), llvm::OpenMPIRBuilder::createDispatchNextFunction(), llvm::mir2vec::MIRVocabulary::createDummyVocabForTest(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::LiveIntervals::createEmptyInterval(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createEnumerator(), createExtractsForLiveOuts(), llvm::VPBuilder::createFCmp(), llvm::vfs::OutputBackend::createFile(), llvm::DDGBuilder::createFineGrainedNode(), llvm::AbstractDependenceGraphBuilder< GraphType >::createFineGrainedNodes(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::OpenMPIRBuilder::createForStaticInitFunction(), llvm::CastInst::CreateFPCast(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), createFrameHelperMachineFunction(), llvm::IRBuilderBase::CreateFree(), llvm::DIBuilder::createFriend(), llvm::RISCVISAInfo::createFromExtMap(), createFunctionClones(), CreateGCRelocates(), llvm::VPlanTransforms::createHeaderPhiRecipes(), llvm::VPBuilder::createICmp(), createImportedModule(), llvm::MatrixBuilder::CreateIndexAssumption(), llvm::msf::MappedBlockStream::createIndexedStream(), llvm::msf::WritableMappedBlockStream::createIndexedStream(), createIndexMap(), llvm::DIBuilder::createInheritance(), llvm::VPlanTransforms::createInLoopReductionRecipes(), llvm::mca::InstrBuilder::createInstruction(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::CastInst::CreateIntegerCast(), llvm::VPlanTransforms::createInterleaveGroups(), createInvariantCond(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::MachineJumpTableInfo::createJumpTableIndex(), llvm::IRBuilderBase::CreateLaunderInvariantGroup(), llvm::orc::EPCIndirectionUtils::createLazyCallThroughManager(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::createLibcall(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::FileCheckPatternContext::createLineVariable(), llvm::DbgVariableRecord::createLinkedDVRAssign(), llvm::jitlink::createLinkGraphFromELFObject_aarch64(), llvm::jitlink::createLinkGraphFromELFObject_loongarch(), llvm::jitlink::createLinkGraphFromELFObject_riscv(), llvm::jitlink::createLinkGraphFromELFObject_systemz(), llvm::jitlink::createLinkGraphFromELFObject_x86(), llvm::jitlink::createLinkGraphFromXCOFFObject_ppc64(), llvm::AMDGPUMCExpr::createLit(), llvm::IRBuilderBase::CreateLogicalAnd(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::DIBuilder::createMacro(), llvm::IRBuilderBase::CreateMalloc(), llvm::IRBuilderBase::CreateMaskedCompressStore(), llvm::IRBuilderBase::CreateMaskedExpandLoad(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedStore(), createMaskInstrs(), createMCInstPrinter(), llvm::Target::createMCObjectStreamer(), llvm::createMCSymbolizer(), llvm::X86Operand::CreateMem(), llvm::createMemCpyLoopKnownSize(), llvm::createMemLibcall(), llvm::MemorySSAUpdater::createMemoryAccessAfter(), llvm::MemorySSAUpdater::createMemoryAccessBefore(), llvm::DDGBuilder::createMemoryEdge(), llvm::IRBuilderBase::CreateMemTransferInst(), createMergedFunction(), llvm::DIBuilder::createMethod(), createMIBNode(), llvm::RISCVInstrInfo::createMIROperandComment(), llvm::TargetInstrInfo::createMIROperandComment(), llvm::IRBuilderBase::CreateNAryOp(), llvm::ImutAVLFactory< ImutInfo >::createNode(), createNodeForSelectViaUMinSeq(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), llvm::IRBuilderBase::CreateOr(), llvm::OpenMPIRBuilder::createOrderedDepend(), llvm::createOrderedReduction(), llvm::createOrderedReduction(), createOrReplaceFragment(), createPackShuffleMask(), llvm::OpenMPIRBuilder::createParallel(), llvm::DIBuilder::createParameterVariable(), llvm::PassInfo::createPass(), llvm::createPHIsForSplitLoopExit(), llvm::DDGBuilder::createPiBlock(), createPlaceholderForShuffleVector(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::IRBuilderBase::CreatePreserveUnionAccessIndex(), createProfileFileNameVar(), llvm::IRBuilderBase::CreatePtrDiff(), llvm::MDBuilder::createRange(), createRawLoad(), createRawStore(), llvm::OpenMPIRBuilder::createReductions(), llvm::DIBuilder::createReferenceType(), llvm::MachineOperand::CreateReg(), llvm::sandboxir::Region::createRegionsFromMD(), llvm::MachineOperand::CreateRegLiveOut(), llvm::MachineOperand::CreateRegMask(), createReplicateRegion(), llvm::orc::JITDylib::createResourceTracker(), llvm::DDGBuilder::createRootedEdge(), llvm::DDGBuilder::createRootNode(), llvm::createSanitizerCtorAndInitFunctions(), llvm::MatrixBuilder::CreateScalarDiv(), createScalarIVSteps(), llvm::InnerLoopVectorizer::createScalarPreheader(), createScratchRegisterForInstruction(), llvm::jitlink::LinkGraph::createSection(), llvm::OpenMPIRBuilder::createSections(), llvm::TargetLowering::createSelectForFMINNUM_FMAXNUM(), llvm::IRBuilderBase::CreateSExtOrTrunc(), llvm::Attributor::createShallowWrapper(), llvm::createSimpleReduction(), createSPIRVMCInstPrinter(), llvm::createSplat2ShuffleMask(), llvm::MachineFrameInfo::CreateStackObject(), llvm::SelectionDAG::CreateStackTemporary(), llvm::createStepForVF(), llvm::DIBuilder::createStringType(), llvm::DIBuilder::createStringType(), llvm::DIBuilder::createStringType(), llvm::IRBuilderBase::CreateStripInvariantGroup(), llvm::jitlink::aarch32::createStubArmv7(), llvm::jitlink::aarch32::createStubThumbv7(), llvm::MatrixBuilder::CreateSub(), createSwitchStatement(), llvm::dxil::ResourceInfo::createSymbol(), llvm::OpenMPIRBuilder::createTargetData(), llvm::OpenMPIRBuilder::createTargetDeinit(), llvm::OpenMPIRBuilder::createTargetInit(), createTargetMachine(), llvm::PPCInstrInfo::CreateTargetPostRAHazardRecognizer(), createTaskWithPrivatesTy(), createTblForTrunc(), createTblShuffleMask(), llvm::OpenMPIRBuilder::createTeams(), createTempFile(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::sys::fs::createTemporaryFile(), llvm::IRBuilderBase::CreateThreadLocalAddress(), createThunk(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), createTileStore(), createTuple(), createTypedBufferStore(), llvm::createUnaryMask(), llvm::createUnpackShuffleMask(), llvm::DIBuilder::createUnspecifiedType(), createVariablePermute(), llvm::DIBuilder::createVariantMemberType(), llvm::IRBuilderBase::CreateVectorInterleave(), llvm::IRBuilderBase::CreateVectorSplat(), llvm::IRBuilderBase::CreateVectorSplice(), llvm::MachineRegisterInfo::createVirtualRegister(), CreateVPTBlock(), llvm::RegisterBankInfo::OperandsMapper::createVRegs(), createWidenInductionRecipe(), llvm::SystemZTargetGOFFStreamer::createWordDiffExpr(), llvm::SystemZTargetHLASMStreamer::createWordDiffExpr(), llvm::createX86_64AsmBackend(), llvm::X86_MC::createX86MCSubtargetInfo(), llvm::IRBuilderBase::CreateZExtOrTrunc(), cvtVOP3DstOpSelOnly(), llvm::mca::Instruction::cycleEvent(), llvm::mca::EntryStage::cycleResume(), llvm::SMSchedule::cycleScheduled(), llvm::mca::DispatchStage::cycleStart(), llvm::mca::InOrderIssueStage::cycleStart(), llvm::orc::shared::WrapperFunctionBuffer::data(), llvm::orc::shared::WrapperFunctionBuffer::data(), llvm::sys::fs::mapped_file_region::data(), llvm::CallBase::dataOperandHasImpliedAttr(), llvm::DbgCallSiteParam::DbgCallSiteParam(), llvm::DbgLabelRecord::DbgLabelRecord(), DbgRewriteSalvageableDVIs(), LiveDebugValues::DbgValue::DbgValue(), LiveDebugValues::DbgValue::DbgValue(), LiveDebugValues::DbgValue::DbgValue(), llvm::DbgValueDef::DbgValueDef(), llvm::DbgValueLoc::DbgValueLoc(), llvm::DbgValueLoc::DbgValueLoc(), LiveDebugValues::DbgValueProperties::DbgValueProperties(), llvm::DCData::DCData(), llvm::parallel::PerThreadAllocator< BumpPtrAllocator >::Deallocate(), llvm::CCState::DeallocateReg(), llvm::MachineInstr::debug_operands(), llvm::MachineInstr::debug_operands(), llvm::coverage::mcdc::DecisionParameters::DecisionParameters(), llvm::MCSymbol::declareCommon(), llvm::declareSanitizerInitFunction(), llvm::coro::declaresIntrinsics(), llvm::RuntimeDyldMachOAArch64::decodeAddend(), DecodeANDI16Imm(), decodeB4constOperand(), decodeB4constuOperand(), decodeBase64StringEntry(), decodeBBAddrMapImpl(), decodeBranchOperand(), decodeCallOperand(), llvm::BitCodeAbbrevOp::DecodeChar6(), decodeCLUIImmOperand(), llvm::AMDGPUDisassembler::decodeCOMPUTE_PGM_RSRC1(), DecodeDREGSRegisterClass(), decodeEntry_Imm12OpValue(), DecodeFixedType(), llvm::codeview::decodeFramePtrReg(), decodeFRMArg(), decodeImm12Operand(), decodeImm1_16Operand(), decodeImm1n_15Operand(), decodeImm32n_95Operand(), decodeImm64n_4nOperand(), decodeImm7_22Operand(), decodeImm8_sh8Operand(), decodeImm8n_7Operand(), decodeImm8Operand(), llvm::jitlink::aarch32::decodeImmMovtT1MovwT3(), decodeImmZibiOperand(), llvm::DecodeInsertElementMask(), DecodeINSVE_DF(), llvm::AMDGPUDisassembler::decodeIntImmed(), DecodeIWREGSRegisterClass(), decodeJMPIXImmOperand(), decodeJumpOperand(), llvm::AMDGPUDisassembler::decodeKernelDescriptorDirective(), decodeL32ROperand(), DecodeLD8loRegisterClass(), DecodeLD8RegisterClass(), llvm::AMDGPUDisassembler::decodeLiteral64Constant(), decodeLLVMAttributesForBitcode(), llvm::AArch64_AM::decodeLogicalImmediate(), decodeLoopOperand(), decodeLRW16Imm8(), llvm::AMDGPUDisassembler::decodeMandatoryLiteralConstant(), decodeMem16Operand(), decodeMem32nOperand(), decodeMem32Operand(), decodeMem8Operand(), DecodeMSA128Mem(), decodeMultiByteChar(), llvm::AMDGPUDisassembler::decodeNonVGPRSrcOp(), decodeOImmOperand(), decodeOperand_VGPR_16(), decodeOperand_VSrc_f64(), decodeOperand_VSrcT16(), decodeOperand_VSrcT16_Lo128(), llvm::decodePackedBCD(), decodePCDBLOperand(), llvm::DecodePSHUFBMask(), decodeRegisterClass(), DecodeRegSeqOperand(), DecodeRegSeqOperandD1(), DecodeRegSeqOperandD2(), DecodeRegSeqOperandF1(), DecodeRegSeqOperandF2(), decodeRTZArg(), llvm::AMDGPUDisassembler::decodeSDWAVopcDst(), decodeShimm1_31Operand(), DecodeSIMM13(), DecodeSIMM5(), decodeSImmOperand(), decodeSImmOperand(), decodeSImmOperand(), decodeSImmOperandAndLslN(), DecodeSPRegisterClass(), decodeSrcOp(), llvm::AMDGPUDisassembler::decodeSrcOp(), DecodeT2Adr(), llvm::RISCVVType::decodeTWiden(), decodeUimm4Operand(), decodeUimm5Operand(), decodeUImmLog2XLenOperand(), decodeUImmOperand(), decodeUImmOperand(), decodeUImmOperand(), decodeUImmOperandGE(), decodeUImmPlus1Operand(), decodeUImmPlus1OperandGE(), decodeUImmSlistOperand(), llvm::DecodeVALIGNMask(), DecodeVGPR_16_Lo128RegisterClass(), DecodeVGPR_16RegisterClass(), llvm::AMDGPUDisassembler::decodeVOPDDstYOp(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPPERMMask(), llvm::DecodeVPPERMMask(), DecodeVpredROperand(), llvm::RISCVVType::decodeVSEW(), llvm::DecodeZeroExtendMask(), decompose(), llvm::decomposeBitTestICmp(), decomposeGEP(), llvm::decomposeLinearExpression(), llvm::AArch64InstrInfo::decomposeStackOffsetForDwarfOffsets(), llvm::AArch64InstrInfo::decomposeStackOffsetForFrameOffsets(), llvm::RISCVTargetLowering::decomposeSubvectorInsertExtractToSubRegs(), decreaseSetPressure(), llvm::sandboxir::DGNode::decrUnscheduledSuccs(), deduceAndAssignTypeForGUnmerge(), llvm::ShapeT::deduceImm(), deducePointerTypeFromResultRegister(), deduceTypeFromOperandRange(), deduceTypeFromPointerOperand(), llvm::def_chain(), llvm::orc::JITDylib::define(), llvm::orc::JITDylib::define(), llvm::FileCheckPatternContext::defineCmdlineVariables(), definesFullReg(), LiveDebugValues::VLocTracker::defVar(), llvm::orc::LLJIT::deinitialize(), llvm::DeleteDeadBlocks(), llvm::deleteDeadLoop(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::DominatorTreeBase< BlockT, false >::deleteEdge(), deleteLoopIfDead(), llvm::MachineFunction::deleteMachineInstr(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::MDNode::deleteTemporary(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DeltaTree::DeltaTree(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::denormalize(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::denormalize(), llvm::DependenceInfo::depends(), llvm::SmallPtrSetIteratorImpl::dereference(), llvm::orc::ExecutionSession::deregisterResourceManager(), llvm::HexagonMCInstrInfo::deriveDuplex(), llvm::HexagonMCInstrInfo::deriveExtender(), llvm::coro::BaseCloner::deriveNewFramePointer(), llvm::HexagonMCInstrInfo::deriveSubInst(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), llvm::DISubprogram::describes(), llvm::PPCSubtarget::descriptorEnvironmentPointerOffset(), llvm::PPCSubtarget::descriptorTOCAnchorOffset(), llvm::memprof::MemProfSummary::deserialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::deserialize(), llvm::StableFunctionMapRecord::deserializeEntry(), llvm::orc::deserializeModule(), llvm::deserializeSectionKind(), llvm::ManagedStaticBase::destroy(), llvm::SpecificBumpPtrAllocator< T >::DestroyAll(), llvm::Constant::destroyConstant(), llvm::sandboxir::Context::detach(), detectPMADDUBSW(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), detectSSatPattern(), detectSSatSPattern(), detectSSatUPattern(), detectUSatPattern(), detectUSatUPattern(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSaves(), determineLastCalleeSave(), determineLiveOperandBitsAddCarry(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::DWARFUnit::determineStringOffsetsTableContribution(), llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), determineSVEStackSizes(), llvm::DetermineUseCaptureKind(), llvm::sandboxir::DGNode::DGNode(), llvm::MCContext::diagnose(), llvm::LTOCodeGenerator::DiagnosticHandler(), llvm::DIEUnit::DIEUnit(), llvm::DIExpressionCursor::DIExpressionCursor(), llvm::vfs::directory_iterator::directory_iterator(), llvm::MachineRegisterInfo::disableCalleeSavedRegister(), llvm::VPBlockUtils::disconnectBlocks(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::ModuleSummaryIndex::discoverNodes(), llvm::mca::Instruction::dispatch(), llvm::mca::LSUnit::dispatch(), llvm::mca::RetireControlUnit::dispatch(), llvm::mca::Scheduler::dispatch(), llvm::telemetry::Manager::dispatch(), llvm::orc::ExecutionSession::dispatchTask(), llvm::VPRegionBlock::dissolveToCFGLoop(), llvm::BlendedBlockHash::distance(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::IntervalMapImpl::distribute(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::DistributeRange(), llvm::ConstantFPRange::div(), llvm::DynamicAPInt::divByPositive(), llvm::DynamicAPInt::divByPositiveInPlace(), llvm::APFloat::divide(), llvm::detail::DoubleAPFloat::divide(), llvm::LLT::divide(), llvm::SCEVDivision::divide(), llvm::ScaledNumbers::divide32(), llvm::ScaledNumbers::divide64(), llvm::divideCeil(), llvm::divideCeil(), llvm::divideCeilSigned(), llvm::divideFloorSigned(), llvm::divideNearest(), llvm::CastInfo< To, PointerUnion< PTs... > >::doCast(), doemit(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::AsmPrinter::doFinalization(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), dofwd(), llvm::AsmPrinter::doInitialization(), llvm::BasicBlockSectionsProfileReaderWrapperPass::doInitialization(), doinsert(), llvm::isa_impl_cl< To, const From * >::doit(), llvm::isa_impl_cl< To, const From *const >::doit(), llvm::isa_impl_cl< To, const std::unique_ptr< From > >::doit(), llvm::isa_impl_cl< To, From * >::doit(), llvm::isa_impl_cl< To, From *const >::doit(), dominates(), llvm::CombinerHelper::dominates(), llvm::DominatorTree::dominates(), llvm::DominatorTree::dominates(), llvm::DominatorTreeBase< BlockT, false >::dominates(), llvm::LexicalScopes::dominates(), llvm::PostDominatorTree::dominates(), llvm::Trace::dominates(), llvm::InstCombinerImpl::dominatesAllUses(), dominatesAllUsesOf(), doPromotion(), doSplitCoroutine(), llvm::detail::DoubleAPFloat::DoubleAPFloat(), llvm::downscaleWeights(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::drop_back(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_back(), llvm::MutableArrayRef< char >::drop_back(), llvm::StringRef::drop_back(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::drop_front(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front(), llvm::MutableArrayRef< char >::drop_front(), llvm::StringRef::drop_front(), dropIntrinsicWithUnknownMetadataArgument(), llvm::DbgMarker::dropOneDbgRecord(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::dropOutOfDateUpdates(), llvm::GenericMachineInstr::dropPoisonGeneratingFlags(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), dropRedundantMaskingOfLeftShiftInput(), dropRegDescribedVar(), dropTypeTests(), llvm::lto::DTLTO::DTLTO(), llvm::DWARFDebugNames::Entry::dump(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::dump(), llvm::gsym::GsymReader::dump(), llvm::ImportedFunctionsInliningStatistics::dump(), llvm::orc::JITDylib::dump(), llvm::PBQP::RegAlloc::PBQPRAGraph::dump(), llvm::RangeListEntry::dump(), dumpApplePropertyAttribute(), llvm::PMTopLevelManager::dumpArguments(), dumpExampleDependence(), dumpLocationExpr(), dumpLocationList(), llvm::dumpMaxRegPressure(), llvm::DWARFDebugLoclists::dumpRawEntry(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::dumpSectionInfo(), dupl(), llvm::TargetInstrInfo::duplicate(), llvm::VPlan::duplicate(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), duplicateCPV(), llvm::DuplicateInstructionsInSplitBetween(), llvm::DWARFCFIAnalysis::DWARFCFIAnalysis(), llvm::DWARFExpression::DWARFExpression(), llvm::dyn_cast(), llvm::dyn_cast(), llvm::dyn_cast(), llvm::dyn_cast(), llvm::BitTracker::MachineEvaluator::eADD(), llvm::BitTracker::MachineEvaluator::eAND(), earlyExpandDIVFIX(), llvm::BitTracker::MachineEvaluator::eASL(), llvm::BitTracker::MachineEvaluator::eASR(), eat12Bytes(), eat16Bytes(), eatBytes(), llvm::BitTracker::MachineEvaluator::eCLR(), llvm::EquivalenceClasses< ElemTy >::ECValue::ECValue(), llvm::ehAwareSplitEdge(), llvm::BitTracker::MachineEvaluator::eIMM(), llvm::BitTracker::MachineEvaluator::eINS(), llvm::yaml::SequenceTraits< ArrayRef< T > >::element(), elementPairIsContiguous(), elementPairIsOddToEven(), llvm::object::elf_section_iterator::elf_section_iterator(), llvm::object::ELFRelocationRef::ELFRelocationRef(), llvm::object::ELFSectionRef::ELFSectionRef(), llvm::object::ELFSymbolRef::ELFSymbolRef(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonFrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::WebAssemblyFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), eliminateDeadSwitchCases(), EliminateDuplicatePHINodesSetBasedImpl(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::VERegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), eliminateMemIntrinsics(), eliminateMove(), llvm::EliminateNewDuplicatePHINodes(), eliminateSwiftErrorAlloca(), llvm::BitTracker::MachineEvaluator::eLSR(), EltsFromConsecutiveLoads(), llvm::embedBitcodeInModule(), llvm::BitstreamWriter::Emit(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::AppleAccelTableOffsetData::emit(), llvm::AppleAccelTableTypeData::emit(), llvm::AsmPrinter::XRayFunctionEntry::emit(), llvm::dwarf_linker::parallel::DebugLineSectionEmitter::emit(), llvm::DwarfStringPool::emit(), llvm::MCPseudoProbe::emit(), llvm::MCPseudoProbeInlineTree::emit(), llvm::orc::CompileOnDemandLayer::emit(), llvm::orc::IRCompileLayer::emit(), llvm::orc::IRPartitionLayer::emit(), llvm::orc::IRSpeculationLayer::emit(), llvm::orc::IRTransformLayer::emit(), llvm::orc::ObjectLinkingLayer::emit(), llvm::orc::ObjectTransformLayer::emit(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::remarks::BitstreamMetaSerializer::emit(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::AArch64TargetLowering::EmitAllocateSMESaveBuffer(), llvm::AArch64TargetLowering::EmitAllocateZABuffer(), llvm::emitAMDGPUPrintfCall(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFIAddFP(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFReg(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveReg(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::AArch64TargetStreamer::emitAttribute(), EmitAVX512Test(), emitBasicBlockLoopComments(), llvm::AsmPrinter::emitBasicBlockStart(), llvm::AsmPrinter::emitBBAddrMapSection(), llvm::emitBinaryFloatFnCall(), emitBinaryFloatFnCallHelper(), llvm::BitstreamWriter::emitBlob(), emitBuildPairF64Pseudo(), emitBuildPairF64Pseudo(), llvm::SystemZHLASMAsmStreamer::emitBytes(), llvm::AsmPrinter::emitCallGraphSection(), llvm::OpenMPIRBuilder::emitCancelationCheckImpl(), llvm::CFIFunctionFrameStreamer::emitCFIEndProcImpl(), EmitCMP(), EmitCmp(), llvm::AsmPrinter::emitCOFFFeatureSymbol(), llvm::AsmPrinter::emitCOFFReplaceableFunctionData(), llvm::SystemZHLASMAsmStreamer::EmitComment(), emitComparison(), emitConditionalComparison(), emitConjunctionRec(), llvm::WebAssemblyAsmPrinter::emitConstantPool(), emitConstantSizeRepmov(), emitDarwinBCHeaderAndTrailer(), llvm::memprof::RecordWriterTrait::EmitData(), emitDbgAssign(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::InstrEmitter::EmitDbgLabel(), llvm::InstrEmitter::EmitDbgValue(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::DWARFYAML::emitDebugAranges(), llvm::DWARFYAML::emitDebugGNUPubnames(), llvm::DWARFYAML::emitDebugGNUPubtypes(), llvm::DwarfDebug::emitDebugLocEntry(), llvm::DWARFYAML::emitDebugLoclists(), llvm::DwarfDebug::emitDebugLocValue(), llvm::DWARFYAML::emitDebugNames(), llvm::DWARFYAML::emitDebugPubnames(), llvm::DWARFYAML::emitDebugPubtypes(), llvm::DWARFYAML::emitDebugRnglists(), llvm::DWARFYAML::emitDebugStrOffsets(), llvm::LiveDebugVariables::LDVImpl::emitDebugValues(), llvm::APByteStreamer::emitDIERef(), llvm::BufferByteStreamer::emitDIERef(), llvm::emitDWARF5AccelTable(), llvm::AsmPrinter::emitDwarfDIE(), llvm::AsmPrinter::emitDwarfLengthOrOffset(), llvm::AsmPrinter::emitDwarfStringOffset(), llvm::AsmPrinter::emitDwarfSymbolReference(), llvm::MCStreamer::emitDwarfUnitLength(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::SystemZTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SystemZTargetLowering::emitEHSjLjSetJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::AMDGPUAsmPrinter::emitEndOfAsmFile(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AArch64EpilogueEmitter::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::XtensaFrameLowering::emitEpilogue(), llvm::LLVMContext::emitError(), llvm::LoongArchTargetLowering::emitExpandAtomicRMW(), emitExternalFile(), llvm::MCObjectStreamer::emitFill(), llvm::MCObjectStreamer::emitFill(), emitFloatCompareMask(), llvm::emitFrameOffset(), emitFrameOffsetAdj(), emitFROUND(), llvm::AsmPrinter::emitFunctionBody(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::WebAssemblyTargetAsmStreamer::emitFunctionType(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), llvm::AsmPrinter::emitGlobalAlias(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), llvm::ExecutionEngine::emitGlobals(), llvm::WebAssemblyTargetAsmStreamer::emitGlobalType(), llvm::AsmPrinter::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), emitIndirectDst(), llvm::AsmPrinter::emitInitialRawDwarfLocDirective(), llvm::MachineInstr::emitInlineAsmError(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::SystemZHazardRecognizer::EmitInstruction(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::HexagonMCELFStreamer::emitInstruction(), llvm::SystemZHazardRecognizer::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::CFIFunctionFrameAnalyzer::emitInstructionAndDirectives(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::RISCVTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), llvm::MCStreamer::emitIntValue(), llvm::LoopVectorizationPlanner::emitInvalidCostRemarks(), llvm::EpilogueVectorizerMainLoop::emitIterationCountCheck(), llvm::AsmPrinter::emitJumpTableEntry(), llvm::BPFAsmPrinter::emitJumpTableInfo(), llvm::LoongArchAsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), llvm::AArch64TargetLowering::EmitKCFICheck(), llvm::ARMTargetLowering::EmitKCFICheck(), llvm::RISCVTargetLowering::EmitKCFICheck(), llvm::X86TargetLowering::EmitKCFICheck(), llvm::X86AsmPrinter::emitKCFITypeId(), llvm::OpenMPIRBuilder::emitKernelLaunch(), emitKill(), llvm::MCStreamer::emitLabel(), llvm::MCObjectStreamer::emitLabelAtPos(), llvm::AArch64InstrInfo::emitLdStWithAddr(), llvm::LoongArchInstrInfo::emitLdStWithAddr(), llvm::RISCVInstrInfo::emitLdStWithAddr(), llvm::TargetLoweringObjectFileCOFF::emitLinkerDirectives(), emitLoad(), llvm::ThumbRegisterInfo::emitLoadConstPool(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::PPCTargetLowering::emitLoadLinked(), emitLoadScalarOpsFromVGPRLoop(), LiveDebugValues::MLocTracker::emitLoc(), llvm::AArch64TargetLowering::EmitLoweredCatchRet(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::XtensaAsmPrinter::emitMachineConstantPoolValue(), llvm::dwarf_linker::classic::DwarfStreamer::emitMacroTables(), llvm::PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::PPCTargetLowering::emitMaskedAtomicRMWIntrinsic(), emitMemMemImm(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaBlock(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), emitNop(), llvm::MCObjectStreamer::emitNops(), llvm::RISCVTargetELFStreamer::emitNoteGnuPropertySection(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::MCJIT::emitObject(), llvm::OpenMPIRBuilder::emitOffloadingArraysArgument(), emitOneV5FileEntry(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::AsmPrinter::emitPCSections(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::AArch64PrologueEmitter::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::XtensaFrameLowering::emitPrologue(), emitPseudoCTPOP(), llvm::PseudoProbeHandler::emitPseudoProbe(), emitRangeList(), emitReadCounterWidePseudo(), llvm::orc::IndirectStubsManager::emitRedirectableSymbols(), llvm::AsmPrinter::emitRemarksSection(), llvm::ScheduleDAGSDNodes::EmitSchedule(), emitSCSPrologue(), llvm::MCObjectStreamer::emitSFrameCalculateFuncOffset(), emitSiFiveCLICStackSwap(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::emitSourceFileHeader(), llvm::AsmPrinter::emitSpecialLLVMGlobal(), emitSplitF64Pseudo(), emitSplitPairF64Pseudo(), llvm::X86FrameLowering::emitSPUpdate(), llvm::AsmPrinter::emitStackMaps(), emitStackProbeInline(), llvm::X86AsmPrinter::emitStartOfAsmFile(), emitStore(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::PPCTargetLowering::emitStoreConditional(), emitStrictFPComparison(), llvm::dwarf_linker::parallel::SectionDescriptor::emitString(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitStringSections(), llvm::StringToOffsetTable::EmitStringTableDef(), llvm::MCWasmStreamer::emitSymbolAttribute(), llvm::MCStreamer::emitSymbolValue(), llvm::emitT2RegPlusImmediate(), llvm::WebAssemblyTargetAsmStreamer::emitTableType(), llvm::WebAssemblyTargetAsmStreamer::emitTagType(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), llvm::OpenMPIRBuilder::emitTargetTask(), emitTargetTaskProxyFunction(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), emitTransformedIndex(), emitUnaryFloatFnCallHelper(), EmitUnwindInfo(), llvm::DIEBaseTypeRef::emitValue(), llvm::SystemZHLASMAsmStreamer::emitValueImpl(), llvm::BitstreamWriter::EmitVBR(), llvm::BitstreamWriter::EmitVBR64(), emitVectorComparison(), llvm::MCStreamer::emitVersionForTarget(), emitVFROUND_NOEXCEPT_MASK(), llvm::emitWcsLen(), emitX86Nops(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::SystemZAsmPrinter::emitXXStructorList(), llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::emplace(), llvm::AnalysisManager< LazyCallGraph::SCC, LazyCallGraph & >::empty(), llvm::BlotMapVector< KeyT, ValueT >::empty(), llvm::jitlink::SectionRange::empty(), llvm::sandboxir::DependencyGraph::empty(), llvm::sandboxir::Interval< T >::empty(), emptyAndDetachBlock(), llvm::PPCTargetLowering::enableAggressiveFMAFusion(), enableAllocFrameElim(), llvm::ARMFrameLowering::enableCalleeSaveSkip(), llvm::HexagonFrameLowering::enableCalleeSaveSkip(), llvm::TargetFrameLowering::enableCalleeSaveSkip(), llvm::Automaton< ActionT >::enableTranscription(), llvm::gsym::GsymCreator::encode(), llvm::gsym::LineTable::encode(), llvm::MCDwarfLineAddr::encode(), llvm::RuntimeDyldMachOAArch64::encodeAddend(), llvm::MCDwarfFrameEmitter::encodeAdvanceLoc(), encodeBase64StringEntry(), encodeCounter(), llvm::CodeViewContext::encodeDefRange(), llvm::MCSFrameEmitter::encodeFuncOffset(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::HexagonMCCodeEmitter::encodeInstruction(), llvm::RISCVVType::encodeLMUL(), llvm::AArch64_AM::encodeLogicalImmediate(), llvm::ARM_AM::encodeNEONi16splat(), llvm::ARM_AM::encodeNEONi32splat(), llvm::gsym::encodeRange(), llvm::RISCVZC::encodeRegList(), llvm::RISCVZC::encodeRegListNumRegs(), llvm::COFF::encodeSectionName(), llvm::RISCVVType::encodeSEW(), llvm::HexagonMCCodeEmitter::encodeSingleInstruction(), llvm::RISCV::VSETVLIInfo::encodeVTYPE(), llvm::RISCVVType::encodeVTYPE(), llvm::RISCVVType::encodeXSfmmVType(), llvm::GFConstant::end(), llvm::ir2vec::Vocabulary::end(), llvm::TimeTraceProfiler::end(), llvm::TimeTraceProfiler::end(), llvm::VFRange::end(), llvm::DbgValueHistoryMap::Entry::endEntry(), llvm::AIXException::endFunction(), llvm::WasmException::endFunction(), llvm::CodeViewDebug::endFunctionImpl(), llvm::DwarfDebug::endFunctionImpl(), llvm::LiveRange::endIndex(), llvm::DebugHandlerBase::endInstruction(), llvm::DwarfDebug::endModule(), llvm::WebAssemblyAsmTypeCheck::endOfFunction(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::RegAllocBase::enqueue(), ensureAssignTypeForTypeFolding(), llvm::MachineFrameInfo::ensureMaxAlignment(), ensurePromotedGV(), ensureValueAvailableInSuccessor(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvAtEnd(), llvm::SplitEditor::enterIntvBefore(), llvm::SystemZPostRASchedStrategy::enterMBB(), llvm::ScheduleDAGInstrs::enterRegion(), llvm::ScheduleDAGMILive::enterRegion(), llvm::EnumAttributeImpl::EnumAttributeImpl(), llvm::enumerate(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray(), llvm::BitTracker::MachineEvaluator::eORL(), llvm::EpilogueLoopVectorizationInfo::EpilogueLoopVectorizationInfo(), llvm::ARM::WinEH::ExceptionDataRecord::EpilogueScopes(), llvm::vfs::Status::equivalent(), llvm::sampleprof::DefaultFunctionPruningStrategy::Erase(), llvm::const_iterator< MemoryLocation >::erase(), llvm::const_iterator< MemoryLocation >::erase(), llvm::EquivalenceClasses< BasicBlock * >::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::LoopInfo::erase(), llvm::MapVector< StringRef, HashData >::erase(), llvm::PriorityWorklist< T, VectorT, MapT >::erase(), llvm::RewriteRope::erase(), llvm::sandboxir::SeedContainer::erase(), llvm::SetVector< EdgeType * >::erase(), llvm::simple_ilist< Node >::erase(), llvm::SparseMultiSet< PhysRegSUOper, MCRegUnit, MCRegUnitToIndex, uint16_t >::erase(), llvm::SparseSet< MCPhysReg, MCPhysReg >::erase(), llvm::TinyPtrVector< ReachingDef >::erase(), llvm::TinyPtrVector< ReachingDef >::erase(), llvm::MachineFunction::eraseAdditionalCallInfo(), llvm::BranchProbabilityInfo::eraseBlock(), llvm::MachineInstr::eraseFromBundle(), llvm::sandboxir::EraseFromParent::EraseFromParent(), llvm::MachineBasicBlock::eraseFromParent(), llvm::MachineInstr::eraseFromParent(), llvm::sandboxir::Instruction::eraseFromParent(), llvm::VPRecipeBase::eraseFromParent(), llvm::InstCombinerImpl::eraseInstFromFunction(), llvm::objcarc::EraseInstruction(), llvm::Value::eraseMetadataIf(), llvm::DominatorTreeBase< BlockT, false >::eraseNode(), error(), llvm::MIRParserImpl::error(), llvm::errs(), llvm::BitTracker::MachineEvaluator::eSET(), estimateElementCount(), llvm::BitTracker::MachineEvaluator::eSUB(), llvm::BitTracker::MachineEvaluator::eSXT(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::eval(), llvm::BitTracker::MachineEvaluator::evaluate(), llvm::HexagonEvaluator::evaluate(), llvm::AVRMCAsmInfo::evaluateAsRelocatableImpl(), MCCOFFSectionNumberTargetExpr::evaluateAsRelocatableImpl(), llvm::SCEVAddRecExpr::evaluateAtIteration(), EvaluateConstantChrecAtConstant(), llvm::Evaluator::EvaluateFunction(), evaluateICmpRelation(), evaluateInDifferentElementOrder(), evaluateMemOpAddrForAddrModeT2_i8s4(), evaluatePtrAddRecAtMaxBTCWillNotWrap(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerParameter(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerRVA(), llvm::ARM::WinEH::RuntimeFunction::ExceptionInformationRVA(), llvm::ARM::WinEH::RuntimeFunctionARM64::ExceptionInformationRVA(), llvm::execMayBeModifiedBeforeAnyUse(), llvm::execMayBeModifiedBeforeUse(), llvm::mca::DispatchStage::execute(), llvm::mca::EntryStage::execute(), llvm::mca::ExecuteStage::execute(), llvm::mca::Instruction::execute(), llvm::mca::RetireStage::execute(), llvm::VPBasicBlock::execute(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPDerivedIVRecipe::execute(), llvm::VPHistogramRecipe::execute(), llvm::VPInstruction::execute(), llvm::VPInterleaveEVLRecipe::execute(), llvm::VPInterleaveRecipe::execute(), llvm::VPIRBasicBlock::execute(), llvm::VPIRInstruction::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::VPReductionEVLRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), llvm::VPReductionRecipe::execute(), llvm::VPRegionBlock::execute(), llvm::VPReplicateRecipe::execute(), llvm::VPScalarIVStepsRecipe::execute(), llvm::VPVectorPointerRecipe::execute(), llvm::VPWidenCallRecipe::execute(), llvm::VPWidenCastRecipe::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::VPWidenIntrinsicRecipe::execute(), llvm::VPWidenRecipe::execute(), llvm::sys::ExecuteAndWait(), executeFCMP_BOOL(), executeFCMP_ORD(), executeFCMP_UNO(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::GIMatchTableExecutor::executeMatchTable(), llvm::sys::ExecuteNoWait(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::objcopy::dxbc::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), llvm::LoopVectorizationPlanner::executePlan(), llvm::ELFObjectWriter::executePostLayoutBinding(), executeSelectInst(), llvm::vfs::RedirectingFileSystem::exists(), llvm::BitstreamWriter::ExitBlock(), llvm::ScalarEvolution::ExitLimit::ExitLimit(), llvm::BitTracker::MachineEvaluator::eXOR(), llvm::PeelingModuloScheduleExpander::expand(), Expand2AddrKreg(), Expand2AddrUndef(), Expand2AddrUndef(), Expand64BitShift(), llvm::TargetLowering::expandAddSubSat(), expandAnyOrAllIntrinsic(), llvm::expandAtomicMemCpyAsLoop(), llvm::TargetLowering::expandAVG(), ExpandBasePaths(), expandBitCastF128ToI128(), expandBitCastI128ToF128(), llvm::VPlanTransforms::expandBranchOnTwoConds(), expandBufferLoadIntrinsic(), expandBufferStoreIntrinsic(), ExpandBVWithShuffles(), llvm::SCEVExpander::expandCodeFor(), llvm::SCEVExpander::expandCodeForPredicate(), llvm::TargetLowering::expandCTPOP(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandFixedPointMul(), expandFloatDotIntrinsic(), llvm::TargetLowering::expandFP_ROUND(), llvm::TargetLowering::expandFP_TO_INT_SAT(), expandFP_TO_UINT_SSE(), expandFRem(), expandFSH64(), expandFunnelShiftIntrinsic(), ExpandHorizontalBinOp(), expandIntegerDotIntrinsic(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandIS_FPCLASS(), expandIToFP(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), expandMemCpy(), expandMemSet(), llvm::SIInstrInfo::expandMovDPP64(), llvm::M68kInstrInfo::ExpandMOVI(), llvm::AArch64_IMM::expandMOVImm(), ExpandMOVImmSExti8(), llvm::M68kInstrInfo::ExpandMOVSZX_RM(), llvm::M68kInstrInfo::ExpandMOVSZX_RR(), llvm::M68kInstrInfo::ExpandMOVX_RR(), llvm::TargetLowering::expandMUL(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandMULO(), expandMulToShlAddShlAdd(), llvm::TargetLowering::expandPartialReduceMLA(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::expandPredBlockMask(), ExpandREAD_REGISTER(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::VPlanTransforms::expandSCEVs(), expandSGPRCopy(), llvm::TargetLowering::expandShiftParts(), llvm::TargetLowering::expandShlSat(), expandSignIntrinsic(), llvm::HexagonBlockRanges::expandToSubRegs(), expandToSwitch(), expandUDivOrURem(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandVecReduceAdd(), llvm::TargetLowering::expandVectorSplice(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPCTPOP(), expandVPWidenIntOrFpInduction(), expandVPWidenPointerInduction(), llvm::Expected< std::unique_ptr< InFlightAlloc > >::Expected(), llvm::ModuleSummaryIndex::exportToDot(), llvm::LiveRangeCalc::extend(), llvm::HexagonMCInstrInfo::extenderForIndex(), llvm::LexicalScope::extendInsnRange(), extendLow32IntoHigh32(), llvm::LiveIntervals::extendToIndices(), ExtendToType(), llvm::BitTracker::MachineEvaluator::eXTR(), llvm::BitTracker::RegisterCell::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::DWARFListTableHeader::extract(), llvm::DWARFUnitHeader::extract(), llvm::LiveIntervalUnion::extract(), llvm::RangeListEntry::extract(), extract128BitVector(), extract256BitVector(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), llvm::mir2vec::MIRVocabulary::extractBaseOpcodeName(), ExtractBitFromMaskVector(), llvm::APInt::extractBits(), llvm::APInt::extractBitsAsZExtValue(), extractBranchProbabilities(), llvm::extractBranchWeights(), llvm::memprof::extractCallsFromIR(), llvm::CodeExtractor::extractCodeRegion(), extractConstantBits(), llvm::extractConstantMask(), llvm::DWARFDebugInfoEntry::extractFast(), extractFromBranchWeightMD(), llvm::SPIRV::extractFunctionTypeFromMetadata(), extractInteger(), llvm::VPIRInstruction::extractLastLaneOfLastPartOfFirstOperand(), extractMaskedValue(), extractMDNode(), llvm::extractParts(), extractPhiReg(), llvm::DWARFDebugAddrTable::extractPreStandard(), extractProbeFromDiscriminator(), llvm::Instruction::extractProfTotalWeight(), llvm::DWARFUnit::extractRangeList(), extractSections(), extractShiftForRotate(), extractSubModule(), extractSubVector(), extractSubVector(), llvm::ExtractTypeInfo(), extractVector(), llvm::extractVectorParts(), llvm::BitTracker::MachineEvaluator::eZXT(), llvm::ARM::WinEH::ExceptionDataRecord::F(), f64AssignAAPCS(), factorizeFAddFSub(), factorizeMathWithShlOps(), factorizeMinMaxTree(), llvm::orc::detail::WaitingOnGraph< JITDylib *, NonOwningSymbolStringPtr >::fail(), llvm::orc::FailedToMaterialize::FailedToMaterialize(), llvm::FailureOr< T >::FailureOr(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::mca::ResourceManager::fastIssueInstruction(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), llvm::LegalizerHelper::fewerElementsBitcast(), llvm::LegalizerHelper::fewerElementsVector(), llvm::LegalizerHelper::fewerElementsVectorExtractInsertVectorElt(), llvm::LegalizerHelper::fewerElementsVectorMerge(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::LegalizerHelper::fewerElementsVectorSeqReductions(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), llvm::MCD::fieldFromInstruction(), llvm::FileCollector::FileCollector(), llvm::object::XCOFFObjectFile::fileHeader32(), llvm::object::XCOFFObjectFile::fileHeader64(), llvm::FileLocRange::FileLocRange(), llvm::BitTracker::RegisterCell::fill(), fillSubVectorFromBuildVector(), fillVector(), llvm::PeelingModuloScheduleExpander::filterInstructions(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::CallGraphUpdater::finalize(), llvm::ControlFlowHub::finalize(), llvm::DebugLocEntry::finalize(), llvm::DIBuilder::finalize(), llvm::DwarfExpression::finalize(), llvm::GISelWorkList< 512 >::finalize(), llvm::MCResourceInfo::finalize(), llvm::OpenMPIRBuilder::finalize(), llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::finalize(), llvm::SchedDFSImpl::finalize(), llvm::StableFunctionMap::finalize(), llvm::StringTableBuilder::finalize(), llvm::RuntimeDyldImpl::finalizeAsync(), llvm::jitlink::finalizeBlockRelax(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::finalizeBundle(), llvm::finalizeBundles(), llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::FinalizedAlloc(), llvm::MachineFunction::finalizeDebugInstrRefs(), llvm::DwarfExpression::finalizeEntryValue(), llvm::UnclusteredHighRPStage::finalizeGCNSchedStage(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::RISCVInstrInfo::finalizeInsInstrs(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::SITargetLowering::finalizeLowering(), llvm::SPIRVTargetLowering::finalizeLowering(), llvm::MCJIT::finalizeModule(), llvm::dwarf_linker::parallel::CompileUnit::find(), llvm::rdf::IndexedSet< T, N >::find(), llvm::ThreadSafeTrieRawHashMap< DataT, sizeof(HashType)>::find(), llvm::ThreadSafeTrieRawHashMap< DataT, sizeof(HashType)>::find(), llvm::ThreadSafeTrieRawHashMapBase::find(), llvm::pdb::const_iterator< SrcHeaderBlockEntry >::find_as(), llvm::BitVector::find_first_in(), llvm::BitVector::find_last_in(), llvm::BitVector::find_last_unset_in(), llvm::SparseBitVectorElement< ElementSize >::find_next(), llvm::find_singleton_nested(), llvm::findAllocaForValue(), llvm::CodeExtractor::findAllocas(), llvm::PMTopLevelManager::findAnalysisPassInfo(), llvm::PMTopLevelManager::findAnalysisUsage(), llvm::hlsl::BindingInfo::RegisterSpace::findAvailableBinding(), findBaseDefiningValue(), findBaseDefiningValueCached(), findBaseDefiningValueOfVector(), findBasePointer(), findBasePointers(), findBestInsertionSet(), llvm::RegBankSelect::findBestMapping(), findBestNonTrivialUnswitchCandidate(), llvm::SwitchCG::SwitchLowering::findBitTestClusters(), findBuildAggregate(), llvm::orc::SpeculateQuery::findCalles(), FindCallSeqStart(), findCanonNumsForPHI(), llvm::WebAssembly::findCatch(), findCommonDominator(), llvm::MipsInstrInfo::findCommutedOpIndices(), llvm::RISCVInstrInfo::findCommutedOpIndices(), llvm::TargetInstrInfo::findCommutedOpIndices(), findCondCodeUseOperandIdxForBranchOrSelect(), findContiguousCases(), llvm::OutlinableRegion::findCorrespondingBlockIn(), llvm::OutlinableRegion::findCorrespondingValueIn(), findDemandedEltsBySingleUser(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::FindEarliestCapture(), llvm::DGNode< DDGNode, DDGEdge >::findEdgesTo(), llvm::logicalview::LVScope::findEqualScope(), llvm::logicalview::LVScopeAggregate::findEqualScope(), llvm::logicalview::LVScopeFunction::findEqualScope(), llvm::logicalview::LVScopeNamespace::findEqualScope(), findExtractedInputToOverallInputMapping(), FindFirstMatchingPrefix(), FindFirstNonCommonLetter(), llvm::findFixedSizeArrayDimensions(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, Sizer::BranchSize, Traits >::findFrom(), llvm::IntervalMapImpl::LeafNode< KeyT, ValT, Sizer::LeafSize, Traits >::findFrom(), findFuncPointers(), llvm::sampleprof::FunctionSamples::findFunctionSamples(), findGISelOptimalMemOpLowering(), findHeaderMask(), llvm::DirectedGraph< DDGNode, DDGEdge >::findIncomingEdgesToNode(), llvm::coverage::MCDCRecord::findIndependencePairs(), llvm::SparseMultiSet< PhysRegSUOper, MCRegUnit, MCRegUnitToIndex, uint16_t >::findIndex(), llvm::SparseSet< MCPhysReg, MCPhysReg >::findIndex(), llvm::LiveRange::findIndexesLiveAt(), llvm::sys::Process::FindInEnvPath(), llvm::MachineInstr::findInlineAsmFlagIdx(), findInnerReductionPhi(), llvm::FindInsertedValue(), llvm::SCEVExpander::findInsertPointAfter(), findInstructionWithOpcode(), findIrreducibleHeaders(), llvm::SwitchCG::SwitchLowering::findJumpTables(), llvm::StringMapImpl::FindKey(), findLastNonVersionCharacter(), llvm::IntEqClasses::findLeader(), findLiveSetAtInst(), findLocationForEntrySafepoint(), LiveDebugValues::InstrRefBasedLDV::findLocationForMemOperand(), FindLoopCounter(), FindMatchingEpilog(), findMatchingInlineAsmOperand(), llvm::findMaximalSubpartOfIllFormedUTF8Sequence(), findMayClobberedPtrAccess(), findMemSDNode(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::SPIRVIRMapping::findMI(), findMostPopularDest(), findmust(), llvm::directive::FindName(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::TargetLowering::findOptimalMemOpLowering(), llvm::findOptionMDForLoopID(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), findOrCreatePHIBlock(), findOrCreatePHIInBlock(), findOutputValueInRegion(), slpvectorizer::BoUpSLP::findPartiallyOrderedLoads(), findPHIForConditionForwarding(), llvm::orc::LocalIndirectStubsManager< TargetT >::findPointer(), FindPreallocatedCall(), findPreviousSpillSlot(), findPrologueEndLoc(), llvm::SIRegisterInfo::findReachingDef(), llvm::pdb::GlobalsStream::findRecordsByName(), findRedundantFlagInstr(), findReturnsToZap(), slpvectorizer::BoUpSLP::findReusedOrderedScalars(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::ScheduleDAGMI::findRootsAndBiasEdges(), llvm::findScalarElement(), findSection(), llvm::SSAUpdaterImpl< UpdaterT >::FindSingularVal(), findStartOfTree(), findStrip(), llvm::orc::LocalIndirectStubsManager< TargetT >::findStub(), findSurvivorBackwards(), llvm::sys::unicode::findSyllable(), llvm::MachO::SymbolSet::findSymbol(), llvm::jitlink::MachOLinkGraphBuilder::findSymbolByIndex(), llvm::pdb::SymbolCache::findSymbolByTypeIndex(), findTargetSubtable(), llvm::MachineInstr::findTiedOperandIdx(), findValueInfoForFunc(), llvm::AssumptionCache::findValuesAffectedByOperandBundle(), findVSplat(), llvm::MCAssembler::Finish(), llvm::CodeViewContext::finish(), llvm::FunctionPropertiesUpdater::finish(), llvm::SpillPlacement::finish(), llvm::SplitEditor::finish(), finishCallSiteParams(), llvm::ItaniumPartialDemangler::finishDemangle(), llvm::ItaniumPartialDemangler::finishDemangle(), llvm::CFIFunctionFrameAnalyzer::finishFunctionFrame(), llvm::LoopBlocksTraversal::finishPostorder(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), firstch(), llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::FixedPointSemantics::FixedPointSemantics(), llvm::FixedScalableVFPair::FixedScalableVFPair(), llvm::FixedStreamArray< CrossModuleExport >::FixedStreamArray(), fixFuncEntryCount(), fixI8UseChain(), fixIrreducible(), fixReductionScalarResumeWhenVectorizingEpilog(), llvm::fixStackStores(), fixupBlock(), llvm::AArch64PrologueEpilogueCommon::fixupCalleeSaveRestoreStackOffset(), FixupDebugInfoForOutlinedFunction(), fixupDebugInfoPostExtraction(), llvm::dwarf_linker::classic::CompileUnit::fixupForwardReferences(), fixupLineNumbers(), fixupOrderingIndices(), fixupPHIOpBanks(), llvm::AArch64TargetLowering::fixupPtrauthDiscriminator(), fixupSetCC(), fixupVariableFloatArgs(), llvm::PGOContextualProfile::flatten(), FlattenLoopPair(), llvm::APInt::flipBit(), llvm::LiveRangeUpdater::flush(), llvm::ConstantFPRange::flushDenormals(), llvm::LiveRange::flushSegmentSet(), fmed3AMDGCN(), llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), llvm::UnOpInit::Fold(), foldADDIForFasterLocalAccesses(), foldAddSubBoolOfMaskedVal(), foldAddSubOfSignBit(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), foldAndOrOfSETCC(), foldAndToXor(), llvm::InstCombinerImpl::foldBinOpSelectBinOp(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), llvm::InstCombinerImpl::foldBinopWithRecurrence(), foldBitwiseLogicWithIntrinsics(), foldBoolSelectToLogic(), FoldBUILD_VECTOR(), foldCastShuffle(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldComplexAndOrPatterns(), foldCONCAT_VECTORS(), foldConcatVector(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::FoldConstantBuildVector(), foldConstantCastPair(), llvm::DIExpression::foldConstantMath(), foldCSELofCTTZ(), foldCtpop(), foldCtpopPow2Test(), foldCttzCtlz(), foldDependentIVs(), foldExtendedSignBitTest(), foldExtendVectorInregToExtendOfSubvector(), foldExtractSubvectorFromShuffleVector(), foldFabsWithFcmpZero(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), foldFPToIntToFP(), llvm::PPCInstrInfo::foldFrameOffset(), llvm::InstCombinerImpl::foldGEPICmp(), foldGEPOfPhi(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAddOpConst(), llvm::InstCombinerImpl::foldICmpAndShift(), llvm::InstCombinerImpl::foldICmpBinOp(), foldICmpEqualityWithOffset(), foldICmpIntrinsicWithIntrinsic(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpSelectConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShlConstConst(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpShrConstConst(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpUDivConstant(), foldICmpWithDominatingICmp(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), llvm::ScalarEvolution::FoldID::FoldID(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIDivShl(), llvm::SIInstrInfo::foldImmediate(), llvm::SystemZInstrInfo::foldImmediate(), llvm::VEInstrInfo::foldImmediate(), llvm::FoldingSetBase::FoldingSetBase(), foldInlineAsmMemOperand(), foldInlineAsmMemOperand(), foldInsEltIntoIdentityShuffle(), foldIntegerPackFromVector(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::InstCombinerImpl::foldItoFPtoI(), foldLogicOfShifts(), foldLogicTreeOfShifts(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldMaskAndShiftToScale(), foldMaskedMerge(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldMinimumMaximumSharedOp(), foldNegativePower2AndShiftedMask(), foldOrOfInversions(), foldOrToXor(), foldPatchpoint(), llvm::InstCombinerImpl::foldPHIArgBinOpIntoPHI(), llvm::InstCombinerImpl::foldPowiReassoc(), foldRemainderIdiom(), foldSelectBitTest(), foldSelectFunnelShift(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), foldSelectToCopysign(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), foldShuffleWithInsert(), foldSignedTruncationCheck(), llvm::InstCombinerImpl::foldSquareSumFP(), foldSwitchToSelect(), foldToUnsignedSaturatedAdd(), foldTruncShuffle(), foldTruncStoreOfExt(), foldTwoEntryPHINode(), foldURemOfLoopIncrement(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVecExtTruncToExtElt(), llvm::InstCombinerImpl::foldVectorBinop(), foldVGPRCopyIntoRegSequence(), foldXorToXor(), FollowCopyChain(), llvm::mca::Instruction::forceExecuted(), forceExpAbs(), llvm::TargetLowering::forceExpandMultiply(), llvm::TargetLowering::forceExpandWideMUL(), forceRenaming(), llvm::dwarf_linker::parallel::OutputSections::forEach(), llvm::dwarf_linker::parallel::TypeUnit::forEachAcceleratorRecord(), llvm::forEachCallbackCallSite(), forEachJumpTableBranch(), llvm::codeview::detail::GuidAdapter::format(), llvm::format_provider< llvm::lsp::Position >::format(), llvm::format_provider< T, std::enable_if_t< support::detail::use_integral_formatter< T >::value > >::format(), llvm::format_provider< T, std::enable_if_t< support::detail::use_string_formatter< T >::value > >::format(), llvm::format_hex(), llvm::format_hex_no_prefix(), llvm::pdb::LinePrinter::formatMsfStreamBlocks(), llvm::pdb::LinePrinter::formatMsfStreamData(), formatTypeName(), llvm::formDedicatedExitBlocks(), formLCSSAForInstructionsImpl(), formLCSSAImpl(), formSplatFromShuffles(), llvm::FPExtInst::FPExtInst(), llvm::FPStateAccessSDNode::FPStateAccessSDNode(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::ARM::WinEH::RuntimeFunctionARM64::FrameSize(), llvm::InstCombinerImpl::freelyInvertAllUsersOf(), llvm::MachineRegisterInfo::freezeReservedRegs(), llvm::detail::frexp(), llvm::MCRegister::from(), llvm::MDNode::fromCaptureComponents(), llvm::CodeViewYAML::fromDebugH(), llvm::CodeViewYAML::fromDebugS(), llvm::CodeViewYAML::fromDebugT(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), llvm::cas::ondisk::ObjectHandle::fromFileOffset(), llvm::JITSymbolFlags::fromGlobalValue(), llvm::IRSimilarity::IRSimilarityCandidate::fromGVN(), llvm::cas::ondisk::ObjectHandle::fromMemory(), llvm::msgpack::DocNode::fromString(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::fromSuccessorIndex(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::front(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::front(), llvm::MutableArrayRef< char >::front(), llvm::sandboxir::BasicBlock::front(), llvm::SetVector< EdgeType * >::front(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::StringRef::front(), llvm::TinyPtrVector< ReachingDef >::front(), llvm::APIntOps::fshl(), llvm::APIntOps::fshr(), llvm::IRPosition::function_scope(), llvm::FunctionCallee::FunctionCallee(), llvm::sampleprof::FunctionId::FunctionId(), llvm::ARM::WinEH::RuntimeFunction::FunctionLength(), llvm::ARM::WinEH::RuntimeFunctionARM64::FunctionLength(), llvm::FunctionPropertiesUpdater::FunctionPropertiesUpdater(), llvm::APFloat::fusedMultiplyAdd(), llvm::detail::DoubleAPFloat::fusedMultiplyAdd(), fuseInst(), llvm::fuseInstructionPair(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), llvm::gatherImportedSummariesForModule(), gatherPossiblyVectorizableLoads(), llvm::detail::gcd(), llvm::DynamicAPInt::gcd, llvm::TargetInstrInfo::genAlternativeCodeSequence(), genAlternativeDpCodeSequence(), generateAssignInstrs(), llvm::RuntimePointerChecking::generateChecks(), llvm::MCJIT::generateCodeForModule(), llvm::generateConvertInst(), generateEquivalentSub(), GenerateFixedLengthSVETBL(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqImpl(), generateInstSeqLeadingZeros(), llvm::LLVMContext::generateMachineFunctionNum(), generateModuleMap(), generateNewInstTree(), llvm::SCEVExpander::generateOverflowCheck(), llvm::generateParamAccessSummary(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), generateReproducer(), llvm::generateSpecConstantInst(), generateStackAdjustment(), llvm::WindowScheduler::generateTripleMBB(), llvm::RISCVMatInt::generateTwoRegInstSeq(), llvm::generateWaveInst(), llvm::orc::GenericNamedTaskImpl< FnT >::GenericNamedTaskImpl(), llvm::AArch64SysReg::genericRegisterString(), genFusedMultiply(), genFusedMultiplyAccNeg(), genFusedMultiplyIdxNeg(), genIndexedMultiply(), genLoopLimit(), genMaddR(), genNeg(), genShuffleBland(), genShXAddAddShift(), genSubAdd2SubSub(), llvm::AMDGPU::LaneMaskConstants::get(), llvm::Attribute::get(), llvm::Attribute::get(), llvm::Attribute::get(), llvm::Attribute::get(), llvm::BlockAddress::get(), llvm::BlockAddress::get(), llvm::cas::ondisk::OnDiskKeyValueDB::get(), llvm::CondOpInit::get(), llvm::ConstantAggregateZero::get(), llvm::ConstantExpr::get(), llvm::ConstantFP::get(), llvm::ConstantInt::get(), llvm::ConstantInt::get(), llvm::ConstantStruct::get(), llvm::ConstantTargetNone::get(), llvm::DagInit::get(), llvm::DbgVariable::get(), llvm::DbgVariable::get(), llvm::DSOLocalEquivalent::get(), llvm::dwarf_linker::classic::PatchLocation::get(), llvm::gsym::LineTable::get(), llvm::gsym::LineTable::get(), llvm::hlsl::CBufferMetadata::get(), llvm::ImmutableGraphBuilder< MachineGadgetGraph >::get(), llvm::InlineCost::get(), llvm::ListInit::get(), llvm::MCInstrInfo::get(), llvm::NoCFIValue::get(), llvm::objcarc::ARCRuntimeEntryPoints::get(), llvm::object::Record::get(), llvm::pdb::const_iterator< SrcHeaderBlockEntry >::get(), llvm::PointerUnion< TrivialCallback *, NonTrivialCallbacks * >::get(), llvm::rdf::IndexedSet< T, N >::get(), llvm::RecordRecTy::get(), llvm::RecordRecTy::get(), llvm::sandboxir::ConstantVector::get(), llvm::SignedDivisionByConstantInfo::get(), llvm::StructType::get(), llvm::TypedPointerType::get(), llvm::UnsignedDivisionByConstantInfo::get(), llvm::ValueAsMetadata::get(), llvm::VPTransformState::get(), llvm::VPTransformState::get(), llvm::SIRegisterInfo::get32BitRegister(), get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), llvm::PPC::get_VSPLTI_elt(), getAArch64Cmp(), getAArch64XALUOOp(), llvm::DWARFDie::getAbbreviationDeclarationPtr(), llvm::DWARFYAML::Data::getAbbrevTableContentByIndex(), llvm::MipsTargetStreamer::getABI(), llvm::ARMTargetLowering::getABIAlignmentForCallingConv(), getAbsSetOperand(), llvm::MemoryDepChecker::getAC(), llvm::ValueInfo::getAccessSpecifier(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LegalizerInfo::getActionDefinitionsIdx(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::DbgAssignIntrinsic::getAddress(), llvm::DbgDeclareInst::getAddress(), llvm::DbgVariableRecord::getAddress(), llvm::JITSymbol::getAddress(), llvm::jitlink::Symbol::getAddressable(), llvm::jitlink::Symbol::getAddressable(), llvm::TargetTransformInfo::getAddressComputationCost(), llvm::AVR::getAddressSpace(), llvm::dwarf::UnwindLocation::getAddressSpace(), llvm::LLT::getAddressSpace(), llvm::MCCFIInstruction::getAddressSpace(), llvm::SectionEntry::getAddressWithOffset(), llvm::AddrLabelMap::getAddrLabelSymbolToEmit(), getAddrOffset(), llvm::PointerIntPair< PointerTy, IntBits, IntType >::getAddrOfPointer(), llvm::PointerUnion< TrivialCallback *, NonTrivialCallbacks * >::getAddrOfPtr1(), llvm::PointerSumType< TagT, MemberTs... >::getAddrOfZeroTagPointer(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::AMDGPULibFuncBase::getAddrSpaceFromEPtrKind(), llvm::ReplayInlineAdvisor::getAdviceImpl(), GetAEABIUnwindPersonalityName(), llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getAfterIP(), llvm::Constant::getAggregateElement(), llvm::Constant::getAggregateElement(), getAggregateNumElements(), getAISize(), llvm::opt::Option::getAlias(), llvm::opt::Option::getAliasArgs(), llvm::AliasSummary::getAliasee(), llvm::AliasSummary::getAliaseeGUID(), llvm::AliasSummary::getAliaseeVI(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::AliasSetTracker::getAliasSetFor(), llvm::MCFragment::getAlignFill(), llvm::MCFragment::getAlignFillLen(), llvm::MCFragment::getAlignMaxBytesToEmit(), llvm::Attribute::getAlignment(), llvm::MCFragment::getAlignment(), llvm::RecordKeeper::getAllDerivedDefinitions(), llvm::Value::getAllMetadata(), getAllocatableSetForRC(), llvm::AllocaInst::getAllocationSize(), llvm::Attribute::getAllocKind(), llvm::Attribute::getAllocSizeArgs(), llvm::getAllocToken(), llvm::memprof::getAllocTypeAttributeString(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::jitlink::Block::getAlreadyMutableContent(), getAlternateBinop(), llvm::RISCV::VSETVLIInfo::getAltFmt(), llvm::TargetTransformInfo::getAltInstrCost(), llvm::ARM_AM::getAM2Opc(), llvm::Pass::getAnalysis(), llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisID(), llvm::Pass::getAnalysisID(), llvm::Pass::getAnalysisIfAvailable(), llvm::WindowScheduler::getAntiRegister(), getAnyExtendConsideringPostIncUses(), llvm::ScalarEvolution::getAnyExtendExpr(), getAnyNonZeroConstInt(), llvm::AsmToken::getAPIntVal(), llvm::AArch64::getArchExtFeature(), llvm::Function::getArg(), llvm::IRPosition::getArg(), llvm::getArgNo(), llvm::CallBase::getArgOperand(), llvm::sandboxir::CallBase::getArgOperand(), llvm::CallBase::getArgOperandNo(), llvm::CallBase::getArgOperandUse(), llvm::CallBase::getArgOperandUse(), llvm::sandboxir::CallBase::getArgOperandUse(), llvm::sandboxir::CallBase::getArgOperandUse(), getArgSPIRVType(), llvm::getArgumentAliasingToReturnedPointer(), llvm::Intrinsic::IITDescriptor::getArgumentKind(), llvm::Intrinsic::IITDescriptor::getArgumentNumber(), llvm::AArch64_AM::getArithExtendImm(), llvm::PPCTTIImpl::getArithmeticInstrCost(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticReductionCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getArithmeticReductionCost(), llvm::RISCVTTIImpl::getArithmeticReductionCost(), llvm::TargetTransformInfo::getArithmeticReductionCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::AArch64TTIImpl::getArithmeticReductionCostSVE(), llvm::getArm64ECMangledFunctionName(), getARM64SubType(), getARMIndexedAddressParts(), getARMLoadDeprecationInfo(), getARMStoreDeprecationInfo(), getARMSubType(), llvm::msgpack::DocNode::getArray(), llvm::Type::getArrayElementType(), llvm::BTFDebug::getArrayIndexTypeId(), llvm::ConstantDataSequential::getAsCString(), llvm::ConstantExpr::getAsInstruction(), llvm::dxil::ResourceInfo::getAsMetadata(), llvm::MachineInstr::getAsmPrinterFlag(), llvm::object::TapiUniversal::ObjectForArch::getAsObjectFile(), llvm::SelectionDAG::getAssertAlign(), llvm::at::getAssignmentInsts(), llvm::at::getAssignmentInsts(), llvm::IRPosition::getAssociatedArgument(), llvm::IRPosition::getAssociatedValue(), llvm::Attribute::getAsString(), llvm::ConstantDataSequential::getAsString(), llvm::AMDGPUTargetMachine::getAssumedAddrSpace(), llvm::Attributor::getAssumedInitializerFromCallBack(), llvm::PotentialValuesState< APInt >::getAssumedSet(), llvm::PotentialValuesState< APInt >::getAssumedSet(), llvm::AssumptionCacheTracker::getAssumptionCache(), getAssumptions(), llvm::FunctionPointerLikeTypeTraits< Alignment, FunctionPointerT >::getAsVoidPointer(), llvm::coro::Shape::getAsyncCoroId(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getAtomicCmpSwap(), getAtomicLoad128Opcode(), llvm::TargetLoweringBase::getAtomicLoadExtAction(), llvm::objcarc::getAttachedARCFunctionKind(), llvm::DWARFAbbreviationDeclaration::getAttrByIndex(), llvm::AttrBuilder::getAttribute(), llvm::dxil::ValueEnumerator::getAttributeGroupID(), llvm::ValueEnumerator::getAttributeGroupID(), llvm::dxil::ValueEnumerator::getAttributeListID(), llvm::ValueEnumerator::getAttributeListID(), getAttributeProperties(), llvm::ELFCompactAttrParser::getAttributeString(), llvm::ELFExtendedAttrParser::getAttributeString(), llvm::ELFCompactAttrParser::getAttributeValue(), llvm::ELFExtendedAttrParser::getAttributeValue(), llvm::DWARFAbbreviationDeclaration::getAttributeValueFromOffset(), llvm::DWARFAbbreviationDeclaration::getAttrImplicitConstValueByIndex(), llvm::DWARFAbbreviationDeclaration::getAttrIsImplicitConstByIndex(), llvm::Attributor::getAttrsFromAssumes(), llvm::MachineModuleInfoELF::getAuthPtrStubEntry(), llvm::MachineModuleInfoMachO::getAuthPtrStubEntry(), llvm::object::XCOFFCsectAuxRef::getAuxType64(), llvm::RISCV::VSETVLIInfo::getAVLDefMI(), llvm::RISCV::VSETVLIInfo::getAVLImm(), llvm::RISCV::VSETVLIInfo::getAVLReg(), llvm::RISCV::VSETVLIInfo::getAVLVNInfo(), getAVX512Node(), llvm::Intrinsic::getBaseName(), llvm::getBaseObjectSize(), llvm::WebAssemblyFunctionInfo::getBasePointerVreg(), llvm::SampleContextTracker::getBaseSamplesFor(), llvm::MCAssembler::getBaseSymbol(), llvm::DebugHandlerBase::getBaseTypeSize(), llvm::AMDGPU::getBaseWithConstantOffset(), llvm::CFGMST< Edge, BBInfo >::getBBInfo(), llvm::RegionBase< Tr >::getBBNode(), llvm::msgpack::DocNode::getBinary(), llvm::ConstantExpr::getBinOpIdentity(), getBinOpsForFactorization(), llvm::BitInit::getBit(), llvm::VarBitInit::getBit(), llvm::ConstantExpr::getBitCast(), llvm::SelectionDAG::getBitcastedAnyExtOrTrunc(), llvm::SelectionDAG::getBitcastedSExtOrTrunc(), llvm::SelectionDAG::getBitcastedZExtOrTrunc(), llvm::object::Record::getBits(), llvm::APInt::getBitsNeeded(), llvm::SMTSort::getBitvectorSortSize(), llvm::KnownBits::getBitWidth(), llvm::pdb::Variant::getBitWidth(), getBLENDIBlendMask(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Symbol::getBlock(), llvm::CSKYConstantPoolConstant::getBlockAddress(), llvm::MachineOperand::getBlockAddress(), llvm::MachineBlockFrequencyInfo::getBlockFreqRelativeToEntryBlock(), llvm::bfi_detail::getBlockName(), llvm::bfi_detail::getBlockName(), llvm::MachineFunction::getBlockNumbered(), llvm::IRSimilarity::IRInstructionData::getBlockOperVals(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::LoopBase< BlockT, LoopT >::getBlocksSet(), llvm::LoopBase< BlockT, LoopT >::getBlocksSet(), llvm::getBlockStructInstr(), llvm::getBlockStructType(), llvm::LoopBase< BlockT, LoopT >::getBlocksVector(), llvm::CanonicalLoopInfo::getBody(), llvm::CanonicalLoopInfo::getBodyIP(), llvm::msgpack::DocNode::getBool(), llvm::msgpack::DocNode::getBool(), llvm::CSKYInstrInfo::getBranchDestBlock(), llvm::LoongArchInstrInfo::getBranchDestBlock(), llvm::RISCVInstrInfo::getBranchDestBlock(), getBranchHint(), getBranchInsertPoint(), llvm::getBranchOpcodeForKey(), llvm::BranchProbability::getBranchProbability(), llvm::BranchProbability::getBranchProbability(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget7OpValueMM(), getBranchTargetOpValue(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue1SImm16(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueLsl2MMR6(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMM(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMPC10(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMR6(), getBranchWeight(), getBranchWeights(), getBRccForPseudo(), llvm::AMDGPURegisterBankInfo::getBreakDownCost(), llvm::VECustomDAG::getBroadcast(), getBROADCAST_LOAD(), getBroadcastOpcode(), llvm::getBTIHintNum(), llvm::DWARFDebugNames::NameIndex::getBucketArrayEntry(), GetBucketPtr(), getBufferFormatWithCompCount(), llvm::SourceMgr::getBufferInfo(), getBuildDwordsVector(), getBundledDefMI(), getBundledUseMI(), llvm::HexagonInstrInfo::getBundleNoShuf(), llvm::CallBase::getBundleOperandsEndIndex(), llvm::CallBase::getBundleOperandsStartIndex(), llvm::CallBase::getBundleOpInfoForOperand(), llvm::ISD::ArgFlagsTy::getByRefSize(), getBytePosition(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::AnalysisManager< LazyCallGraph::SCC, LazyCallGraph & >::getCachedResult(), llvm::LazyBlockFrequencyInfo< FunctionT, BranchProbabilityInfoPassT, LoopInfoT, BlockFrequencyInfoT >::getCalculated(), llvm::AbstractCallSite::getCallArgOperandNoForCallee(), llvm::IRSimilarity::IRInstructionData::getCalleeName(), llvm::TargetInstrInfo::getCalleeOperand(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::X86RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::AbstractCallSite::getCalleeUseForCallback(), llvm::TargetTransformInfo::getCallInstrCost(), getCallOpcode(), getCallOpcode(), getCallOpcode(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::MachineFunction::getCallSiteBeginLabel(), llvm::CtxProfAnalysis::getCallsiteInstrumentation(), llvm::MachineFunction::getCallSiteLandingPad(), llvm::orc::LazyCallThroughManager::getCallThroughTrampoline(), llvm::LoopVectorizationCostModel::getCallWideningDecision(), llvm::AMDGPU::getCanonicalArchName(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), llvm::mir2vec::MIRVocabulary::getCanonicalIndexForBaseName(), llvm::mir2vec::MIRVocabulary::getCanonicalIndexForOperandName(), llvm::mir2vec::MIRVocabulary::getCanonicalIndexForRegisterClass(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::Attribute::getCaptureInfo(), llvm::SwitchInst::CaseHandleImpl< const SwitchInst, const ConstantInt, const BasicBlock >::getCaseSuccessor(), llvm::SwitchInst::CaseHandleImpl< const SwitchInst, const ConstantInt, const BasicBlock >::getCaseValue(), llvm::ConstantExpr::getCast(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getCastInstrCost(), llvm::PPCTTIImpl::getCastInstrCost(), llvm::RISCVTTIImpl::getCastInstrCost(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::TargetTransformInfoImplBase::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::CastInst::getCastOpcode(), getCastsForInductionPHI(), llvm::TypedInit::getCastTo(), llvm::FunctionLoweringInfo::getCatchPadExceptionPointerVReg(), llvm::dxil::ResourceTypeInfo::getCBufferSize(), llvm::BitTracker::MachineEvaluator::getCell(), llvm::VPBasicBlock::getCFGPredecessor(), llvm::MachineOperand::getCFIIndex(), llvm::MCCFIInstruction::getCfiLabel(), llvm::AArch64TTIImpl::getCFInstrCost(), llvm::GCNTTIImpl::getCFInstrCost(), llvm::TargetTransformInfo::getCFInstrCost(), llvm::objcopy::elf::IHexRecord::getChecksum(), llvm::dwarf_linker::classic::DeclContextTree::getChildDeclContext(), llvm::dwarf_linker::parallel::OrderedChildrenIndexAssigner::getChildIndex(), getChunk(), llvm::MachineOperand::getCImm(), llvm::pdb::NativeTypePointer::getClassParentId(), llvm::DIDerivedType::getClassType(), llvm::ReachingDefInfo::getClearance(), llvm::MemDepResult::getClobber(), llvm::MemorySSAWalker::getClobberingMemoryAccess(), getCmp(), getCmpForPseudo(), getCmpOpsType(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::TargetTransformInfo::getCmpSelInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::pdb::DIAInjectedSource::getCode(), getCodeExtractorArguments(), getCodeModel(), llvm::PPCSubtarget::getCodeModel(), llvm::gvn::AvailableValue::getCoercedLoadValue(), llvm::MCContext::getCOFFSection(), llvm::irsymtab::Symbol::getCOFFWeakExternalFallback(), llvm::DebugLoc::getCol(), llvm::PBQP::Matrix::getColAsVector(), llvm::TrieHashIndexGenerator::getCollidingBits(), llvm::PBQP::Matrix::getCols(), getComdatGVForCOFF(), llvm::ValueEnumerator::getComdatID(), llvm::MCCFIInstruction::getComment(), llvm::irsymtab::Symbol::getCommonAlignment(), llvm::MCSymbol::getCommonAlignment(), getCommonMinimalPhysRegClass(), llvm::RegionInfoBase< RegionTraits< MachineFunction > >::getCommonRegion(), llvm::sandboxir::VecUtils::getCommonScalarType(), llvm::irsymtab::Symbol::getCommonSize(), llvm::MCSymbol::getCommonSize(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), llvm::object::ObjectFile::getCommonSymbolSize(), llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), llvm::ScalarEvolution::getComparePredicate(), getComparePreds(), getCompareSourceReg(), getCompoundInsn(), getCompoundOp(), llvm::HexagonInstrInfo::getCompoundOpcode(), getConcreteOpcode(), llvm::CanonicalLoopInfo::getCond(), GetCondCode(), llvm::TargetLoweringBase::getCondCodeAction(), getCondition(), llvm::BranchInst::getCondition(), llvm::sandboxir::BranchInst::getCondition(), llvm::coverage::MCDCRecord::getConditionCoverageString(), llvm::coverage::MCDCRecord::getConditionIndependencePair(), llvm::SDDbgOperand::getConst(), getConstant(), llvm::DIDerivedType::getConstant(), llvm::KnownBits::getConstant(), llvm::SCCPInstVisitor::getConstant(), llvm::SelectionDAG::getConstant(), llvm::ValueLatticeElement::getConstant(), llvm::getConstantDataArrayInfo(), llvm::SelectionDAG::getConstantDbgValue(), llvm::SelectionDAG::getConstantFP(), llvm::PPCInstrInfo::getConstantFromConstantPool(), llvm::X86::getConstantFromPool(), llvm::StackMapParser< Endianness >::LocationAccessor::getConstantIndex(), llvm::ScalarEvolution::getConstantMultiple(), llvm::SCCPInstVisitor::getConstantOrNull(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::ValueLatticeElement::getConstantRange(), llvm::getConstantRangeFromMetadata(), llvm::BuildVectorSDNode::getConstantRawBits(), llvm::ExecutionEngine::getConstantValue(), llvm::VNCoercion::getConstantValueForLoad(), getConstantVector(), getConstantVector(), llvm::getConstFromIntrinsic(), getConstMetaVal(), llvm::ConstantPoolSDNode::getConstVal(), getConstVector(), llvm::legacy::FunctionPassManagerImpl::getContainedManager(), llvm::legacy::PassManagerImpl::getContainedManager(), llvm::FPPassManager::getContainedPass(), llvm::LPPassManager::getContainedPass(), llvm::RGPassManager::getContainedPass(), llvm::Type::getContainedType(), getContainerForFixedLengthVector(), getContainerForFixedLengthVector(), llvm::IntervalTree< LVAddress, LVScope * >::getContaining(), llvm::jitlink::Block::getContent(), llvm::RuntimeDyldChecker::MemoryRegionInfo::getContent(), getContentFromHandle(), llvm::cas::CASID::getContext(), llvm::SampleContextTracker::getContextSamplesFor(), llvm::object::Record::getContinuousData(), getContributionIndex(), true::getConvergenceTokenInternal(), llvm::getCoopMatrType(), getCopyFromParts(), getCopyFromPartsVector(), llvm::RegsForValue::getCopyFromRegs(), llvm::WebAssembly::getCopyOpcodeForRegClass(), getCopyToParts(), getCopyToPartsVector(), llvm::CoroSuspendInst::getCoroSave(), getCorrespondingDRegAndLane(), llvm::InlineCost::getCost(), GetCostForDef(), getCostValue(), llvm::DIGenericSubrange::getCount(), llvm::DISubrange::getCount(), llvm::coverage::CoverageMapping::getCoverageForExpansion(), llvm::coverage::CoverageMapping::getCoverageForFile(), llvm::coverage::CoverageMapping::getCoverageForFunction(), llvm::getCPUDefaultTargetFeatures(), llvm::X86::getCPUDispatchMangling(), llvm::Xtensa::getCPUFeatures(), llvm::X86::getCpuSupportsMask(), llvm::object::XCOFFSymbolRef::getCPUTypeIddForCFile(), getCRBitValue(), llvm::object::ELFObjectFile< ELFT >::getCrel(), llvm::getCRFromCRBit(), llvm::MCSectionXCOFF::getCSectType(), llvm::RegOrConstant::getCst(), llvm::StringTable::getCString(), llvm::DWARFDebugNames::NameIndex::getCUOffset(), llvm::TGLexer::getCurBinaryIntVal(), llvm::TGLexer::getCurIntVal(), llvm::MCStreamer::getCurrentFragment(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::GCNSchedStrategy::getCurrentStage(), llvm::mca::RetireControlUnit::getCurrentToken(), llvm::TGLexer::getCurStrVal(), llvm::GenericCycle< ContextT >::getCyclePreheader(), llvm::GCOVBlock::getCyclesCount(), getDagArgNoByKey(), llvm::AArch64RegisterInfo::getDarwinCallPreservedMask(), getDataClassTest(), llvm::object::COFFObjectFile::getDataDirectory(), llvm::AsmPrinter::getDataLayout(), llvm::CallBase::getDataOperandNo(), llvm::sandboxir::CallBase::getDataOperandNo(), getDbgIntrinsicValueImpl(), llvm::SelectionDAG::getDbgLabel(), LiveDebugValues::DbgValue::getDbgOpID(), llvm::SelectionDAG::getDbgValue(), llvm::SelectionDAG::getDbgValueList(), llvm::dwarf_linker::parallel::OutputSections::getDebugAddrHeaderSize(), llvm::MachineInstr::getDebugExpressionOp(), llvm::MachineInstr::getDebugExpressionOp(), llvm::dwarf_linker::parallel::CompileUnit::getDebugInfoEntry(), llvm::DWARFUnit::getDebugInfoEntry(), llvm::MachineInstr::getDebugLabel(), getDebugLocValue(), llvm::MachineInstr::getDebugOffset(), llvm::MachineInstr::getDebugOffset(), llvm::MachineInstr::getDebugOperand(), llvm::MachineInstr::getDebugOperand(), llvm::MachineInstr::getDebugOperandIndex(), llvm::DIE::getDebugSectionOffset(), llvm::dwarf_linker::parallel::OutputSections::getDebugStrOffsetsHeaderSize(), llvm::MachineInstr::getDebugVariableOp(), llvm::MachineInstr::getDebugVariableOp(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), getDecoderTable(), llvm::MemDepResult::getDef(), llvm::orc::JITDylib::getDefaultResourceTracker(), getDefaultScalableVLOps(), getDefaultVLOps(), getDefaultVLOps(), llvm::PPCInstrInfo::getDefMIPostRA(), llvm::ValueDFS_Compare::getDefOrUser(), getDefRegMask(), llvm::getDeinterleavedVectorType(), llvm::Intrinsic::getDeinterleaveIntrinsicID(), llvm::RISCV::getDemanded(), getDemandedSrcElements(), llvm::DIFixedPointType::getDenominator(), GetDeoptBundleOperands(), getDeoptLowering(), llvm::BlockCoverageInference::getDependencies(), llvm::DependenceGraphInfo< NodeType >::getDependencies(), llvm::SelectionDAG::GetDependentSplitDestVTs(), llvm::Attribute::getDereferenceableBytes(), llvm::Attribute::getDereferenceableOrNullBytes(), llvm::SDNodeInfo::getDesc(), llvm::RISCV::getDestLog2EEW(), llvm::AMDGPU::MTBUFFormat::getDfmtName(), llvm::mca::MCAOperand::getDFPImm(), llvm::MCOperand::getDFPImm(), llvm::dwarf_linker::parallel::CompileUnit::getDIE(), llvm::dwarf_linker::parallel::CompileUnit::getDIEAtIndex(), llvm::dwarf_linker::parallel::CompileUnit::getDIEIndex(), llvm::dwarf_linker::parallel::CompileUnit::getDIEIndex(), llvm::DWARFUnit::getDIEIndex(), llvm::DWARF5AccelTableData::getDieOffset(), llvm::ir2vec::Vocabulary::getDimension(), llvm::AMDGPU::ClusterDimsAttr::getDims(), llvm::DIDerivedType::getDiscriminantValue(), llvm::sampleprof::SampleProfileReader::getDiscriminatorMask(), llvm::getDisjunctionWeights(), llvm::PPCMCCodeEmitter::getDispRI34PCRelEncoding(), llvm::PPCMCCodeEmitter::getDispRIHashEncoding(), llvm::PPCMCCodeEmitter::getDispRIX16Encoding(), llvm::PPCMCCodeEmitter::getDispSPE2Encoding(), llvm::PPCMCCodeEmitter::getDispSPE4Encoding(), llvm::PPCMCCodeEmitter::getDispSPE8Encoding(), getDivRemArgList(), getDivRemLibcall(), llvm::LoopVectorizationCostModel::getDivRemSpeculationCost(), llvm::RuntimeDyldCOFF::getDLLImportOffset(), getDomPredecessorCondition(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::getDomTree(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), llvm::HexagonInstrInfo::getDotOldOp(), llvm::VectorType::getDoubleElementsVectorType(), llvm::MemOp::getDstAlign(), GetDSubRegs(), llvm::MemoryDepChecker::getDT(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), llvm::FullDependence::getDVEntry(), LiveDebugValues::DebugVariableMap::getDVID(), llvm::MCFragment::getDwarfAddrDelta(), llvm::MCFragment::getDwarfLineDelta(), getDwarfRegNum(), llvm::NVPTXRegisterInfo::getDwarfRegNumForVirtReg(), llvm::DwarfDebug::getDwarfSectionOffsetForm(), llvm::DWARFUnit::getDwarfStringOffsetsByteSize(), llvm::getDWARFUnitIndex(), getDWordFromOffset(), llvm::orc::ExecutorProcessControl::getDylibMgr(), getDynAllocaAmount(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getEarliestInsertPos(), llvm::MCSectionGOFF::getEDAttributes(), DOTGraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::getEdgeAttributes(), getEdgeKind(), llvm::BranchProbabilityInfo::getEdgeProbability(), getEffectiveImm(), getEffectivePPCCodeModel(), getEffectiveRelocModel(), llvm::ScalarEvolution::getEffectiveSCEVType(), getEHPadFromPredecessor(), GetEHSpillList(), llvm::XCoreFunctionInfo::getEHSpillSlot(), llvm::mca::RegisterFile::getElapsedCyclesFromWriteBack(), llvm::DIExpression::getElement(), llvm::ConstantDataSequential::getElementAsAPInt(), llvm::ConstantDataSequential::getElementAsDouble(), llvm::ConstantDataSequential::getElementAsFloat(), llvm::ConstantDataSequential::getElementAsInteger(), llvm::StructLayout::getElementContainingOffset(), llvm::LLT::getElementCount(), getElementCountForTy(), getElementIndex(), llvm::StructLayout::getElementOffset(), llvm::AnyMemIntrinsic::getElementSizeInBytes(), llvm::LLT::getElementType(), llvm::StructType::getElementType(), llvm::RISCVSubtarget::getELen(), llvm::AVRSubtarget::getELFArch(), llvm::MCContext::getELFSection(), getELFSectionNameForGlobal(), getEmscriptenInvokeSymbolName(), getEnableSplitLTOUnitAndUnifiedFlag(), llvm::VPBlockBase::getEnclosingBlockWithPredecessors(), llvm::VPBlockBase::getEnclosingBlockWithSuccessors(), getEnclosingLoopRegionForRegion(), getEncodedIntegerLength(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::MCRegisterInfo::getEncodingValue(), llvm::SuffixTreeLeafNode::getEndIdx(), llvm::OptimizedStructLayoutField::getEndOffset(), llvm::MachineTraceMetrics::getEnsemble(), llvm::RegionBase< Tr >::getEnteringBlock(), llvm::PGOCtxProfContext::getEntrycount(), llvm::object::ResourceSectionRef::getEntryData(), llvm::jitlink::TableManager< TableManagerImplT >::getEntryForTarget(), llvm::BlockFrequencyInfoImplBase::getEntryFreq(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GetEntryNode(), getEntrySizeForKind(), llvm::object::ResourceSectionRef::getEntrySubDir(), llvm::PPCSubtarget::getEnvironmentPointerRegister(), llvm::Win64EH::UnwindCode::getEpilogOffset(), llvm::AMDGPULibFuncBase::getEPtrKindFromAddrSpace(), llvm::SIRegisterInfo::getEquivalentAGPRClass(), llvm::SIRegisterInfo::getEquivalentAVClass(), llvm::ConstantRange::getEquivalentICmp(), llvm::SCEVSequentialMinMaxExpr::getEquivalentNonSequentialSCEVType(), llvm::ConstantRange::getEquivalentPredWithFlippedSignedness(), llvm::SIRegisterInfo::getEquivalentSGPRClass(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::RegAllocBase::getErrorAssignment(), llvm::AMDGPU::IsaInfo::getEUsPerCU(), llvm::APFloat::getExactInverse(), llvm::object::XCOFFObjectFile::getExceptionEntries(), getExecutionModel(), llvm::orc::ExecutorProcessControl::getExecutionSession(), llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::getExistingEntry(), llvm::ScalarEvolution::getExistingSCEV(), llvm::CanonicalLoopInfo::getExit(), llvm::VPlan::getExitBlock(), llvm::getExitBlockHelper(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), getExitFor(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::RegionBase< Tr >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), getExpandedStep(), getExpectedExitLoopLatchBranch(), llvm::AMDGPUSubtarget::getExplicitKernArgSize(), llvm::JobSlot::getExplicitValue(), llvm::HexagonMCInstrInfo::getExpr(), llvm::MCOperand::getExpr(), llvm::RISCVMCAsmInfo::getExprForFDESymbol(), llvm::getExtDivCycle(), getEXTEND_VECTOR_INREG(), llvm::HexagonMCInstrInfo::getExtendableOperand(), llvm::VectorType::getExtendedElementVectorType(), llvm::object::getExtendedSymbolTableIndex(), llvm::Type::getExtendedType(), llvm::RISCVTargetLowering::getExtendForAtomicRMWArg(), GetExtendHigh(), llvm::AArch64_AM::getExtendType(), getExtendTypeForNode(), getExtensionRank(), getExtensionTo64Bits(), llvm::AtomicSDNode::getExtensionType(), llvm::ConstantExpr::getExtractElement(), getExtractIndex(), llvm::TargetInstrInfo::getExtractSubregInputs(), llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs(), getExtractVectorizedValue(), getExtractWithExtendCost(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), llvm::TargetTransformInfo::getExtractWithExtendCost(), llvm::MCSchedModel::getExtraProcessorInfo(), llvm::APSInt::getExtValue(), llvm::DIFixedPointType::getFactor(), llvm::AtomicSDNode::getFailureOrdering(), llvm::InlineResult::getFailureReason(), llvm::ConstantInt::getFalse(), llvm::VPIRFlags::getFastMathFlags(), llvm::FaultMapParser::getFaultMapVersion(), getFauxShuffleMask(), llvm::getFCmpCode(), getFCmpOpcode(), getFD(), llvm::X86::getFeaturePriority(), getFeatures(), llvm::NearMissInfo::getFeatures(), llvm::X86::getFeaturesForCPU(), llvm::dxil::ResourceTypeInfo::getFeedbackType(), llvm::NewArchiveMember::getFile(), llvm::DWARFDebugLine::Prologue::getFileNameByIndex(), llvm::DWARFDebugLine::Prologue::getFileNameEntry(), llvm::pdb::InputFile::getFilePath(), llvm::dwarf_linker::parallel::TypeEntryBody::getFinalDie(), getFinalPlacementForEntry(), llvm::X86::getFirstAddrOperandIdx(), llvm::jitlink::SectionRange::getFirstBlock(), llvm::dwarf_linker::parallel::CompileUnit::getFirstChildEntry(), llvm::DWARFUnit::getFirstChildEntry(), llvm::StatepointOpers::getFirstGCPtrIdx(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::SystemZMC::getFirstReg(), llvm::IndexedReference::getFirstSubscript(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::ARMAsmBackend::getFixupKindInfo(), llvm::AVRAsmBackend::getFixupKindInfo(), llvm::CSKYAsmBackend::getFixupKindInfo(), llvm::LoongArchAsmBackend::getFixupKindInfo(), llvm::MCAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), llvm::RISCVAsmBackend::getFixupKindInfo(), llvm::MachineInstr::getFlag(), llvm::R600InstrInfo::getFlagOp(), llvm::vputils::getFlagsFromIndDesc(), llvm::CmpInst::getFlippedStrictnessPredicate(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::msgpack::DocNode::getFloat(), llvm::msgpack::DocNode::getFloat(), llvm::getFloatFn(), llvm::SMTSort::getFloatSortSize(), llvm::getFltSemanticForLLT(), llvm::getFMA3Group(), llvm::X86InstrInfo::getFMA3OpcodeToCommuteOperands(), getFMAPatterns(), llvm::PPCInstrInfo::getFMAPatterns(), getFoldedCast(), llvm::MemoryLocation::getForArgument(), llvm::MemoryLocation::getForDest(), llvm::DWARFDebugNames::NameIndex::getForeignTUSignature(), llvm::SourceMgr::getFormattedLocationNoOffset(), llvm::DWARFAbbreviationDeclaration::getFormByIndex(), llvm::MemoryLocation::getForSource(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), getFPBinOp(), getFPFastMathDefaultInfo(), llvm::MachineOperand::getFPImm(), llvm::RISCVLoadFPImm::getFPImm(), llvm::TargetTransformInfo::getFPOpCost(), llvm::SelectionDAGBuilder::getFPOperationRoot(), getFPReg(), getFPSequenceIfElementsMatch(), llvm::XCoreFunctionInfo::getFPSpillSlot(), getFPSubregForVT(), getFPTernOp(), llvm::DIInliningInfo::getFrame(), llvm::X86InstrInfo::getFrameAdjustment(), llvm::WebAssemblyFunctionInfo::getFrameBaseLocal(), llvm::WebAssemblyFunctionInfo::getFrameBaseVreg(), llvm::SelectionDAG::getFrameIndexDbgValue(), llvm::SelectionDAG::getFrameIndexDbgValue(), llvm::RISCVRegisterInfo::getFrameIndexInstrOffset(), llvm::SIRegisterInfo::getFrameIndexInstrOffset(), getFrameIndexOperandNum(), llvm::CSKYFrameLowering::getFrameIndexReference(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::M68kFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::AArch64FrameLowering::getFrameIndexReferenceFromSP(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), llvm::SDDbgOperand::getFrameIx(), llvm::MSP430InstrInfo::getFramePoppedByCallee(), llvm::ARMBaseInstrInfo::getFramePred(), llvm::TargetInstrInfo::getFrameSize(), llvm::TargetInstrInfo::getFrameTotalSize(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::NVPTXDAGToDAGISel::getFromTypeWidthForLoad(), llvm::getFSPassBitBegin(), llvm::getFSPassBitEnd(), llvm::X86AddressMode::getFullAddress(), llvm::object::Archive::Child::getFullName(), llvm::MCPseudoProbeDecoder::getFuncDescForGUID(), llvm::sampleprof::FunctionSamples::getFuncName(), llvm::SampleContextTracker::getFuncNameFor(), llvm::SPIRV::ModuleAnalysisInfo::getFuncReg(), llvm::CanonicalLoopInfo::getFunction(), llvm::coro::BaseCloner::getFunction(), llvm::LazyCallGraph::Edge::getFunction(), llvm::object::BBAddrMap::getFunctionAddress(), llvm::IndexedInstrProfReader::getFunctionBitmap(), llvm::TargetLoweringObjectFileXCOFF::getFunctionEntryPointSymbol(), llvm::FaultMapParser::FunctionInfoAccessor::getFunctionFaultInfoAt(), llvm::dxil::ModuleShaderFlags::getFunctionFlags(), llvm::GCModuleInfo::getFunctionInfo(), llvm::gsym::GsymReader::getFunctionInfoDataAtIndex(), llvm::getFunctionLiveInPhysReg(), llvm::NVPTXTargetLowering::getFunctionParamOptimizedAlign(), getGapMask(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::SelectionDAG::getGatherVP(), llvm::getGCDType(), llvm::MCOperandInfo::getGenericImmIndex(), llvm::MCOperandInfo::getGenericTypeIndex(), llvm::TargetTransformInfoImplCRTPBase< T >::getGEPCost(), llvm::ScalarEvolution::getGEPExpr(), llvm::DataLayout::getGEPIndicesForOffset(), llvm::ConstantExpr::getGetElementPtr(), llvm::SelectionDAG::getGetFPEnv(), getGFNICtrlImm(), getGFNICtrlMask(), llvm::MachineOperand::getGlobal(), llvm::SelectionDAG::getGlobalAddress(), llvm::MCSymbolWasm::getGlobalType(), llvm::ModuleSummaryIndex::getGlobalValueSummary(), llvm::ModuleSummaryIndex::getGlobalValueSummary(), llvm::AArch64MCInstLower::GetGlobalValueSymbol(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getGOTEntry(), SVEIntrinsicInfo::getGoverningPredicateOperandIdx(), llvm::DOTGraphTraits< const DataDependenceGraph * >::getGraphName(), llvm::OpenMPIRBuilderConfig::getGridValue(), llvm::opt::Option::getGroup(), llvm::AssignGUIDPass::getGUID(), llvm::CSKYConstantPoolConstant::getGV(), llvm::AsmPrinter::getGVAlignment(), llvm::IRSimilarity::IRSimilarityCandidate::getGVN(), getGVNForPHINode(), llvm::MachineModuleInfoCOFF::getGVStubEntry(), llvm::MachineModuleInfoELF::getGVStubEntry(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::VectorType::getHalfElementsVectorType(), llvm::EVT::getHalfNumVectorElementsVT(), llvm::MVT::getHalfNumVectorElementsVT(), getHalfShuffleMask(), llvm::EVT::getHalfSizedIntegerVT(), getHalfSizedType(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), llvm::DenseMapInfo< ArrayRef< T >, void >::getHashValue(), llvm::DenseMapInfo< CachedHashString >::getHashValue(), llvm::DenseMapInfo< CachedHashStringRef >::getHashValue(), llvm::DenseMapInfo< const SwitchSuccWrapper * >::getHashValue(), llvm::DenseMapInfo< MemOpKey >::getHashValue(), llvm::IRSimilarity::IRInstructionDataTraits::getHashValue(), getHashValueImpl(), llvm::ARMHazardRecognizerFPMLx::getHazardType(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::ImmutableList< T >::getHead(), llvm::CanonicalLoopInfo::getHeader(), llvm::gsym::GsymReader::getHeader(), llvm::object::MachOObjectFile::getHeader64(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), llvm::opt::Option::getHelpText(), getHexagonRegisterPair(), llvm::HexagonRegisterInfo::getHexagonSubRegIndex(), getHexDigit(), getHexUint(), llvm::COFF::ImportLookupTableEntry32::getHintNameRVA(), llvm::object::import_lookup_table_entry< support::little32_t >::getHintNameRVA(), llvm::getHorizDemandedEltsForFirstOperand(), llvm::getIConstantFromReg(), llvm::getIConstantVRegVal(), llvm::getIConstVal(), llvm::getIConstValSext(), llvm::IdentifyingPassPtr::getID(), llvm::MemoryAccess::getID(), llvm::opt::Option::getID(), llvm::codeview::DebugStringTableSubsection::getIdForString(), getIDFromMarker(), llvm::SPIRV::getIDFromRegister(), llvm::StableFunctionMap::getIdOrCreateForName(), llvm::GetIfCondition(), llvm::ValueAsMetadata::getIfExists(), llvm::SPIRVGlobalRegistry::getImageType(), llvm::MachineOperand::getImm(), llvm::mca::MCAOperand::getImm(), llvm::MCOperand::getImm(), llvm::X86Operand::getImm(), XtensaOperand::getImm(), llvm::PPCMCCodeEmitter::getImmEncoding(), llvm::MipsMCCodeEmitter::getImmOpValue(), llvm::ConstantDataSequential::getImpl(), llvm::DIBasicType::getImpl(), llvm::AMDGPUSubtarget::getImplicitArgNumBytes(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::getImplicitConstValue(), llvm::Loop::getIncomingAndBackEdge(), llvm::MemoryPhi::getIncomingBlock(), llvm::PHINode::getIncomingBlock(), llvm::MemoryPhi::getIncomingValueForBlock(), llvm::PHINode::getIncomingValueForBlock(), llvm::ArgumentInit::getIndex(), llvm::CoroSubFnInst::getIndex(), llvm::ir2vec::Vocabulary::getIndex(), llvm::ir2vec::Vocabulary::getIndex(), llvm::ir2vec::Vocabulary::getIndex(), llvm::MachineOperand::getIndex(), llvm::ModifiedPostOrder< ContextT >::getIndex(), llvm::TrieHashIndexGenerator::getIndex(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedLoadVP(), llvm::SelectionDAG::getIndexedMaskedLoad(), llvm::SelectionDAG::getIndexedMaskedStore(), llvm::DataLayout::getIndexedOffsetInType(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getIndexedStoreVP(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIndexedVectorInstrCostFromEnd(), llvm::RISCVTTIImpl::getIndexedVectorInstrCostFromEnd(), llvm::TargetTransformInfo::getIndexedVectorInstrCostFromEnd(), llvm::getIndexExpressionsFromGEP(), llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::VPBlockBase::getIndexForPredecessor(), llvm::VPBlockBase::getIndexForSuccessor(), llvm::AMDGPU::VOPD::ComponentInfo::getIndexInParsedOperands(), llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfSrcInMCOperands(), llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfSrcInParsedOperands(), llvm::coro::Shape::getIndexType(), llvm::DataLayout::getIndexType(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::CallBrInst::getIndirectDestLabel(), llvm::CallBrInst::getIndirectDestLabelUse(), llvm::InformationCache::getIndirectlyCallableFunctions(), llvm::SIInstrInfo::getIndirectRegWriteMovRelPseudo(), llvm::orc::getIndirectStubsBlockSizes(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), getIndirectThunkSymbol(), llvm::getInductionIntegerTy(), llvm::Loop::getInductionVariable(), llvm::CanonicalLoopInfo::getIndVar(), llvm::CanonicalLoopInfo::getIndVarType(), llvm::CoroIdInst::getInfo(), llvm::RISCV::RISCVVSETVLIInfoAnalysis::getInfoForVSETVLI(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::getInitializer(), llvm::Attribute::getInitializes(), llvm::AA::getInitialValueForObj(), llvm::MCPseudoProbeDecoder::getInjectedProbes(), llvm::MachineInstr::getInlineAsmDialect(), llvm::DebugLoc::getInlinedAt(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::getInlineSpirvType(), llvm::pdb::PDBContext::getInliningInfoForAddress(), getInnerMostLoop(), llvm::object::DirectX::PSVRuntimeInfo::getInputOutputMap(), getInputSegmentList(), llvm::CCState::getInRegsParamInfo(), INITIALIZE_PASS::InsertedPass::getInsertedPass(), llvm::ConstantExpr::getInsertElement(), llvm::TargetTransformInfo::getInsertExtractValueCost(), llvm::RegBankSelect::InsertPoint::getInsertMBB(), getInsertPointForUses(), llvm::TargetInstrInfo::getInsertSubregInputs(), llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs(), llvm::MCFragment::getInst(), llvm::MCOperand::getInst(), llvm::IdentifyingPassPtr::getInstance(), llvm::SIInstrInfo::getInstBundleSize(), getInstCondition(), llvm::SUnit::getInstr(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), getInstReadLaneMask(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::RISCVRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::RegisterBankInfo::getInstrMappingImpl(), getInstrName(), llvm::RegisterBankInfo::getInstrPossibleMappings(), llvm::MachineOperand::getInstrRefInstrIndex(), llvm::MachineOperand::getInstrRefOpIndex(), llvm::MachineTraceMetrics::Trace::getInstrSlack(), getInstrStrFromOpNo(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::TargetTransformInfo::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::SimpleDDGNode::getInstructions(), getInstSizeInBytes(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::LoongArchInstrInfo::getInstSizeInBytes(), llvm::msgpack::DocNode::getInt(), llvm::msgpack::DocNode::getInt(), llvm::getIntDivCycle(), llvm::VectorType::getInteger(), llvm::AMDGPU::getIntegerVecAttribute(), llvm::orc::LinkGraphLayer::getInterface(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getInterleavedMemoryOpCost(), llvm::PPCTTIImpl::getInterleavedMemoryOpCost(), llvm::RISCVTTIImpl::getInterleavedMemoryOpCost(), llvm::SystemZTTIImpl::getInterleavedMemoryOpCost(), llvm::TargetTransformInfo::getInterleavedMemoryOpCost(), llvm::WebAssemblyTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::Intrinsic::getInterleaveIntrinsicID(), llvm::cas::ReferenceBase::getInternalRef(), llvm::RISCVMachineFunctionInfo::getInterruptStackKind(), llvm::LiveStacks::getInterval(), llvm::LiveStacks::getInterval(), llvm::LiveStacks::getIntervalRegClass(), llvm::TargetTransformInfo::getIntImmCodeSizeCost(), llvm::AArch64TTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCost(), llvm::LanaiTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCost(), llvm::SystemZTTIImpl::getIntImmCost(), llvm::TargetTransformInfo::getIntImmCost(), llvm::X86TTIImpl::getIntImmCost(), getIntImmCostImpl(), llvm::AArch64TTIImpl::getIntImmCostInst(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::RISCVTTIImpl::getIntImmCostInst(), llvm::SystemZTTIImpl::getIntImmCostInst(), llvm::TargetTransformInfo::getIntImmCostInst(), llvm::X86TTIImpl::getIntImmCostInst(), llvm::AArch64TTIImpl::getIntImmCostIntrin(), llvm::PPCTTIImpl::getIntImmCostIntrin(), llvm::SystemZTTIImpl::getIntImmCostIntrin(), llvm::TargetTransformInfo::getIntImmCostIntrin(), llvm::X86TTIImpl::getIntImmCostIntrin(), getIntOperandFromRegisterString(), getIntOperandsFromRegisterString(), llvm::DataLayout::getIntPtrType(), llvm::MachineOperand::getIntrinsicID(), llvm::BasicTTIImplBase< BasicTTIImpl >::getIntrinsicInstrCost(), llvm::TargetTransformInfo::getIntrinsicInstrCost(), getIntrinsicNameImpl(), getIntSequenceIfElementsMatch(), llvm::ConstantExpr::getIntToPtr(), llvm::AsmToken::getIntVal(), llvm::dwarf_linker::parallel::SectionDescriptor::getIntVal(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getInvertedVectorForFMA(), llvm::GenericSyncDependenceAnalysis< ContextT >::getJoinBlocks(), llvm::MachineFunction::getJTISymbol(), llvm::MipsMCCodeEmitter::getJumpOffset16OpValue(), llvm::SelectionDAG::getJumpTable(), getJumpTableIndexFromAddr(), llvm::SwitchCG::getJumpTableNumCases(), llvm::SwitchCG::getJumpTableRange(), llvm::MipsMCCodeEmitter::getJumpTargetOpValue(), llvm::MipsMCCodeEmitter::getJumpTargetOpValueMM(), getJumpThreadDuplicationCost(), llvm::OpenMPIRBuilder::getKernelArgsVector(), llvm::X86::getKeyFeature(), llvm::LazyCallGraph::Edge::getKind(), llvm::opt::Option::getKind(), llvm::Attribute::getKindAsEnum(), llvm::AttributeImpl::getKindAsEnum(), llvm::Attribute::getKindAsString(), llvm::AttributeImpl::getKindAsString(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::GISelValueTracking::getKnownBits(), llvm::VPLane::getKnownLane(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownScalarFactor(), getKnownUndefForVectorBinop(), llvm::DebugHandlerBase::getLabelBeforeInsn(), llvm::DwarfUnit::getLabelBegin(), llvm::VPLane::getLaneFromEnd(), llvm::MachineOperand::getLaneMask(), getLanesWithProperty(), llvm::object::XCOFFSymbolRef::getLanguageIdForCFile(), llvm::jitlink::SectionRange::getLastBlock(), llvm::DWARFUnit::getLastChildEntry(), llvm::ConstraintSystem::getLastConstraint(), getLastMIForRegion(), llvm::IndexedReference::getLastSubscript(), llvm::RegPressureTracker::getLastUsedLanes(), llvm::DWARFDebugLine::Prologue::getLastValidFileIndex(), llvm::CanonicalLoopInfo::getLatch(), llvm::LatencyPriorityQueue::getLatency(), llvm::ResourcePriorityQueue::getLatency(), getLatestInsertPos(), llvm::SCCPInstVisitor::getLatticeValueFor(), llvm::orc::EPCIndirectionUtils::getLazyCallThroughManager(), llvm::getLCMType(), llvm::AArch64InstrInfo::getLdStBaseOp(), llvm::AArch64InstrInfo::getLdStOffsetOp(), getLdStRegOp(), llvm::EquivalenceClasses< BasicBlock * >::getLeaderValue(), llvm::omp::getLeafConstructsOrSelf(), llvm::omp::getLeafOrCompositeConstructs(), getLEB128(), llvm::MCFragment::getLEBValue(), getLeftShift(), llvm::VECustomDAG::getLegalReductionOpVVP(), llvm::RISCVTargetLowering::getLegalZfaFPImm(), llvm::PBQP::Vector::getLength(), llvm::pdb::NativeTypePointer::getLength(), llvm::DwarfCompileUnit::getLexicalBlockDIE(), llvm::ScaledNumbers::getLgImpl(), llvm::WebAssembly::getLibcallSignature(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::sys::DynamicLibrary::getLibrary(), llvm::DebugLoc::getLine(), llvm::objcopy::elf::IHexRecord::getLine(), llvm::SourceMgr::getLineAndColumn(), llvm::pdb::PDBContext::getLineInfoForAddress(), llvm::MachO::ObjCInterfaceRecord::getLinkageForSymbol(), llvm::BinOpInit::getListConcat(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::AMDGPU::getLitValue(), llvm::getLiveLaneMask(), llvm::RegPressureTracker::getLiveLanesAt(), llvm::StackLifetime::getLiveRange(), llvm::SIInstrInfo::getLiveRangeSplitOpcode(), llvm::RegionPressureMap::getLiveRegsForRegionIdx(), llvm::RegPressureTracker::getLiveThroughAt(), llvm::getLLTForType(), getLlvmUserOperationEncoding(), llvm::mca::RISCVLMULInstrument::getLMUL(), llvm::RISCVTargetLowering::getLMUL(), getLMUL1Ty(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoad(), llvm::SectionEntry::getLoadAddressWithOffset(), getLoadCommandInfo(), llvm::object::COFFObjectFile::getLoadConfig32(), llvm::object::COFFObjectFile::getLoadConfig64(), llvm::TargetLoweringBase::getLoadExtAction(), llvm::RISCVLoadFPImm::getLoadFPImm(), llvm::getLoadStoreAddressSpace(), llvm::getLoadStoreAlignment(), getLoadStoreRegOpcode(), llvm::getLoadStoreType(), llvm::SelectionDAG::getLoadVP(), llvm::SelectionDAG::getLoadVP(), llvm::MachineFrameInfo::getLocalFrameObjectMap(), getLocalFunctionMetadata(), getLocalScopeLocationOr(), llvm::ModuleSlotTracker::getLocalSlot(), llvm::SlotTracker::getLocalSlot(), llvm::DWARFDebugNames::NameIndex::getLocalTUOffset(), LiveDebugValues::MLocTracker::getLocID(), llvm::LoopNest::getLoop(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::Loop::getLoopGuardBranch(), llvm::ScalarEvolution::getLoopInvariantPredicate(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopNest::getLoopsAtDepth(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), llvm::ScalarEvolution::getLosslessPtrToIntExpr(), llvm::DIGenericSubrange::getLowerBound(), llvm::DISubrange::getLowerBound(), llvm::XCoreFunctionInfo::getLRSpillSlot(), llvm::jitlink::EHFrameCFIBlockInspector::getLSDAEdge(), llvm::RISCVTargetLowering::getM1VT(), llvm::LexicalScopes::getMachineBasicBlocks(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::VirtRegMap::getMachineFunction(), llvm::getMachineInstrType(), llvm::SDNode::getMachineOpcode(), llvm::HexagonMCCodeEmitter::getMachineOpValue(), llvm::MipsMCCodeEmitter::getMachineOpValue(), llvm::PPCMCCodeEmitter::getMachineOpValue(), getMachoBuildVersionPlatformType(), getMachoBuildVersionSupportedOS(), llvm::MCContext::getMachOSection(), getMachoVersionMinLoadCommandType(), getMaddPatterns(), getMainAltOpsNoStateVL(), llvm::SourceMgr::getMainFileID(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::getManager(), llvm::AMDGPU::VOPD::ComponentProps::getMandatoryLiteralCompOperandIndex(), llvm::ExecutionEngine::getMangledName(), llvm::msgpack::DocNode::getMap(), llvm::MCSectionXCOFF::getMappingClass(), llvm::BitstreamWriter::getMarkedBufferAndResumeFlushing(), llvm::ArgDescriptor::getMask(), llvm::VPBlendRecipe::getMask(), llvm::VPReplicateRecipe::getMask(), llvm::RISCV::VSETVLIInfo::getMaskAgnostic(), llvm::VECustomDAG::getMaskBroadcast(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedHistogram(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::ShuffleVectorSDNode::getMaskElt(), getMaskNode(), getMaskTypeFor(), getMaskTypeFor(), getMatchedEntries(), llvm::TargetLowering::AsmOperandInfo::getMatchedOperand(), SVEIntrinsicInfo::getMatchingIROpode(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), SVEIntrinsicInfo::getMatchingUndefIntrinsic(), llvm::RegPressureTracker::getMaxDownwardPressureDelta(), getMaxForClamp(), llvm::M68kRegisterInfo::getMaximalPhysRegClass(), llvm::IndexedInstrProfReader::getMaximumFunctionCount(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::RISCVSubtarget::getMaxLMULForFixedLengthVectors(), llvm::AMDGPU::IsaInfo::getMaxNumSGPRs(), llvm::GCNSubtarget::getMaxNumVectorRegs(), llvm::AMDGPU::IsaInfo::getMaxNumVGPRs(), llvm::GEPOperator::getMaxPreservedAlignment(), llvm::RegPressureTracker::getMaxPressureDelta(), llvm::RISCVSubtarget::getMaxRVVVectorSizeInBits(), llvm::AArch64Subtarget::getMaxSVEVectorSizeInBits(), llvm::RegPressureTracker::getMaxUpwardPressureDelta(), llvm::HexagonMCInstrInfo::getMaxValue(), llvm::Versioned::getMaxVersion(), llvm::AMDGPU::IsaInfo::getMaxWorkGroupsPerCU(), llvm::FunctionLoweringInfo::getMBB(), llvm::MachineIRBuilder::getMBB(), llvm::MachineOperand::getMBB(), llvm::SlotIndexes::getMBBFromIndex(), llvm::MCContext::getMCDwarfLineTable(), llvm::MachineOperand::getMCSymbol(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), getMCSymbolForMBB(), llvm::DwarfDebug::getMD5AsBytes(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::X86Operand::getMemBaseReg(), getMemberOffsets(), llvm::SelectionDAG::getMemcpy(), llvm::TargetTransformInfo::getMemcpyCost(), getMemcpyLoadsAndStores(), llvm::X86Operand::getMemDefaultBaseReg(), llvm::X86Operand::getMemDisp(), llvm::MipsMCCodeEmitter::getMemEncoding(), llvm::MipsMCCodeEmitter::getMemEncodingMMGPImm7Lsl2(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm11(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm12(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm16(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4Lsl1(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4Lsl2(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4sp(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm9(), llvm::MipsMCCodeEmitter::getMemEncodingMMSPImm5Lsl2(), llvm::X86Operand::getMemFrontendSize(), llvm::X86Operand::getMemIndexReg(), llvm::TargetTransformInfo::getMemIntrinsicInstrCost(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::gvn::AvailableValue::getMemIntrinValue(), llvm::orc::ExecutorProcessControl::getMemMgr(), llvm::X86Operand::getMemModeSize(), getMemmoveLoadsAndStores(), llvm::AArch64InstrInfo::getMemOpBaseRegImmOfsOffsetOperand(), getMemOperands(), llvm::SIInstrInfo::getMemOperandsWithOffsetWidth(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), getMemOpKey(), llvm::orc::ExecutorProcessControl::getMemoryAccess(), llvm::SourceMgr::getMemoryBuffer(), llvm::InlineAsm::Flag::getMemoryConstraintID(), llvm::Attribute::getMemoryEffects(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::SystemZTTIImpl::getMemoryOpCost(), llvm::TargetTransformInfo::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::X86_MC::X86MCInstrAnalysis::getMemoryOperandRelocationOffset(), llvm::IndexedMemProfReader::getMemProfCallerCalleePairs(), getMemProfCloneNum(), llvm::IndexedMemProfReader::getMemProfRecord(), llvm::X86Operand::getMemScale(), llvm::X86Operand::getMemSegReg(), llvm::SelectionDAG::getMemset(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getMemTarget(), llvm::DILocation::getMergedLocation(), llvm::MDNode::getMergedProfMetadata(), llvm::SourceMgr::GetMessage(), llvm::MachineOperand::getMetadata(), llvm::dxil::ValueEnumerator::getMetadataID(), llvm::ValueEnumerator::getMetadataID(), llvm::opt::Option::getMetaVar(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMF(), llvm::memprof::getMIBAllocType(), llvm::memprof::getMIBStackNode(), llvm::VPlan::getMiddleBlock(), getMIMnemonic(), getMinAnalyzeableBackedgeTakenCount(), getMinClassForRegBank(), getMinForClamp(), getMinimalPhysRegClass(), llvm::Triple::getMinimumSupportedOSVersion(), llvm::HexagonTTIImpl::getMinimumVF(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::TargetTransformInfo::getMinMaxReductionCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::AMDGPU::IsaInfo::getMinNumSGPRs(), llvm::AMDGPU::IsaInfo::getMinNumVGPRs(), llvm::RISCVSubtarget::getMinRVVVectorSizeInBits(), llvm::AArch64Subtarget::getMinSVEVectorSizeInBits(), getMinUselessShift(), llvm::HexagonMCInstrInfo::getMinValue(), llvm::Versioned::getMinVersion(), llvm::ReachingDefInfo::getMIOperand(), llvm::ReachingDefInfo::getMIOperand(), getMipsABI(), getMnemonic(), llvm::codeview::getModifiedType(), getModifier(), llvm::AAResults::getModRefInfo(), llvm::BasicAAResult::getModRefInfo(), llvm::BasicAAResult::getModRefInfoMask(), llvm::ModuleSummaryIndex::getModule(), llvm::ModuleSummaryIndex::getModule(), llvm::pdb::NativeSession::getModuleDebugStream(), llvm::pdb::DbiModuleList::getModuleDescriptor(), llvm::ModuleSummaryIndex::getModuleHash(), llvm::ScalarEvolution::getMonotonicPredicateType(), llvm::APIntOps::GetMostSignificantDifferentBit(), llvm::MipsMCCodeEmitter::getMovePRegSingleOpValue(), getMSAMapping(), llvm::AMDGPU::SendMsg::getMsgOpName(), llvm::BasicTTIImplBase< BasicTTIImpl >::getMulAccReductionCost(), llvm::ScalarEvolution::getMulExpr(), llvm::dxil::ResourceTypeInfo::getMultiSampleCount(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), llvm::DIInliningInfo::getMutableFrame(), getMVEIndexedAddressParts(), llvm::getN1Bits(), llvm::ArgumentInit::getName(), llvm::coverage::InstantiationGroup::getName(), llvm::DIScope::getName(), llvm::GCNRegPressure::getName(), llvm::Intrinsic::getName(), llvm::Intrinsic::getName(), llvm::jitlink::Symbol::getName(), llvm::MCInstrInfo::getName(), llvm::object::DirectX::Signature::getName(), llvm::opt::Option::getName(), llvm::TargetLibraryInfo::getName(), llvm::DWARFDebugNames::NameIndex::getNameTableEntry(), llvm::Mangler::getNameWithPrefix(), getNameWithPrefixImpl(), getNarrowMaskForInterleavedOps(), getNarrowTypeBreakDown(), llvm::ConstantExpr::getNeg(), getNegativeIsTrueBoolVec(), getNegOperand(), llvm::LoopNest::getNestDepth(), getNewAlignment(), getNewDefiningAccessForClone(), llvm::HexagonMCInstrInfo::getNewValueOperand(), llvm::HexagonMCInstrInfo::getNewValueOperand2(), llvm::codeview::TypeTableCollection::getNext(), getNextDBDirName(), llvm::FaultMapParser::FunctionInfoAccessor::getNextFunctionInfo(), llvm::HexagonBlockRanges::InstrIndexMap::getNextIndex(), llvm::StackMaps::getNextMetaArgIdx(), llvm::sandboxir::Instruction::getNextNode(), llvm::rdf::RefNode::getNextRef(), llvm::rdf::DataFlowGraph::getNextRelated(), llvm::SchedBoundary::getNextResourceCycle(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::GCNSchedStrategy::getNextStage(), llvm::ThreadSafeTrieRawHashMapBase::getNextTrie(), llvm::Automaton< ActionT >::getNfaPaths(), llvm::AMDGPU::MTBUFFormat::getNfmtName(), llvm::X86::getNFVariant(), llvm::DominatorTreeBase< BlockT, false >::getNode(), llvm::LazyCallGraph::Edge::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SUnit::getNode(), llvm::VPMatchContext::getNode(), llvm::VPMatchContext::getNode(), llvm::VPMatchContext::getNode(), llvm::VPMatchContext::getNode(), llvm::VPMatchContext::getNode(), llvm::VPMatchContext::getNode(), llvm::RegionNodeBase< RegionTraits< MachineFunction > >::getNodeAs(), DOTGraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::getNodeAttributes(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock(), DOTGraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::getNodeLabel(), llvm::PartialOrderingVisitor::GetNodeRank(), llvm::PiBlockDDGNode::getNodes(), llvm::DDGBuilder::getNodesInPiBlock(), llvm::Attribute::getNoFPClass(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::X86::getNonNDVariant(), llvm::ISD::ArgFlagsTy::getNonZeroByValAlign(), llvm::ScalarEvolution::getNoopOrAnyExtend(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::ConstantExpr::getNot(), llvm::ValueLatticeElement::getNot(), llvm::ValueLatticeElement::getNotConstant(), llvm::ScalarEvolution::getNotSCEV(), getNumAllocatableRegsForConstraints(), llvm::IRPosition::getNumArgs(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::BasicBlock::getNumber(), llvm::GraphTraits< const MachineBasicBlock * >::getNumber(), llvm::GraphTraits< Inverse< const MachineBasicBlock * > >::getNumber(), llvm::GraphTraits< Inverse< MachineBasicBlock * > >::getNumber(), llvm::GraphTraits< MachineBasicBlock * >::getNumber(), llvm::object::COFFSymbolRef::getNumberOfAuxSymbols(), llvm::PPCTTIImpl::getNumberOfRegisters(), llvm::ThreadSafeTrieRawHashMapBase::getNumBits(), llvm::TrieHashIndexGenerator::getNumBits(), llvm::LoopBase< BlockT, LoopT >::getNumBlocks(), llvm::PGOContextualProfile::getNumCallsites(), llvm::PGOContextualProfile::getNumCounters(), getNumElements(), llvm::sandboxir::VecUtils::getNumElements(), llvm::DIFixedPointType::getNumerator(), llvm::msf::getNumFpmIntervals(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::sandboxir::VecUtils::getNumLanes(), llvm::DIExpression::getNumLocationOperands(), getNumMicroOpsSwiftLdSt(), llvm::GCStatepointInst::getNumPatchBytes(), getNumPushPopRegs(), llvm::TargetLoweringBase::getNumRegisters(), llvm::GCNRegPressure::getNumRegs(), llvm::SPIRVGlobalRegistry::getNumScalarOrVectorTotalBitWidth(), llvm::getNumSizeComponents(), llvm::ThreadSafeTrieRawHashMapBase::getNumSlotUsed(), llvm::LatencyPriorityQueue::getNumSolelyBlockNodes(), llvm::ResourcePriorityQueue::getNumSolelyBlockNodes(), llvm::CallBase::getNumSubclassExtraOperandsDynamic(), llvm::MDNode::getNumTemporaryUses(), llvm::CallBase::getNumTotalBundleOperands(), getNumVectorRegs(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectAllocation(), llvm::cas::ondisk::OnDiskGraphDB::getObjectData(), llvm::cas::ondisk::UnifiedOnDiskCache::getObjectIDFromValue(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getObjectSSPLayout(), llvm::outliner::GlobalOutlinedFunction::getOccurrenceCount(), llvm::getOCLKernelArgAccessQual(), getOCLKernelArgAttribute(), llvm::getOCLKernelArgTypeQual(), llvm::getOclOrSpirvBuiltinDemangledName(), llvm::DICompositeType::getODRTypeIfExists(), llvm::AliasResult::getOffset(), llvm::DIE::getOffset(), llvm::DWARFDie::getOffset(), llvm::DWPStringPool::getOffset(), llvm::MachineOperand::getOffset(), llvm::MCCFIInstruction::getOffset(), llvm::MCSymbol::getOffset(), llvm::StackMapParser< Endianness >::LocationAccessor::getOffset(), llvm::StringTableBuilder::getOffset(), llvm::ARMBasicBlockUtils::getOffsetOf(), llvm::ScalarEvolution::getOffsetOfExpr(), llvm::codeview::LazyRandomTypeCollection::getOffsetOfType(), llvm::AArch64RegisterInfo::getOffsetOpcodes(), llvm::RISCVRegisterInfo::getOffsetOpcodes(), llvm::TargetRegisterInfo::getOffsetOpcodes(), llvm::VectorType::getOneNthElementsVectorType(), getOnesVector(), llvm::rdf::RefNode::getOp(), llvm::MCFragment::getOpcode(), llvm::NearMissInfo::getOpcode(), llvm::LegacyLegalizerInfo::getOpcodeIdxForOpcode(), llvm::LegalizerInfo::getOpcodeIdxForOpcode(), getOpcodeName(), getOpcodeWithCC(), llvm::MemoryBuffer::getOpenFileSlice(), getOpenMPMonotonicityScheduleType(), getOpenMPOrderingScheduleType(), llvm::GVNExpression::BasicExpression::getOperand(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::SCEVCastExpr::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVUDivExpr::getOperand(), llvm::SDNode::getOperand(), llvm::User::getOperand(), llvm::VPUser::getOperand(), llvm::CallBase::getOperandBundle(), llvm::CallBase::getOperandBundle(), llvm::CallBase::getOperandBundleAt(), llvm::LLVMContextImpl::getOperandBundleTagID(), llvm::NearMissInfo::getOperandClass(), llvm::NearMissInfo::getOperandError(), SVEIntrinsicInfo::getOperandIdxInactiveLanesTakenFrom(), SVEIntrinsicInfo::getOperandIdxWithNoActiveLanes(), llvm::NearMissInfo::getOperandIndex(), getOperandInfo(), getOperandLog2EEW(), llvm::MachineOperand::getOperandNo(), llvm::MachineRegisterInfo::defusechain_iterator< true, true, false, true, false >::getOperandNo(), llvm::MCFragment::getOperands(), llvm::User::getOperandUse(), llvm::User::getOperandUse(), llvm::sandboxir::User::getOperandUseDefault(), llvm::MipsTargetLowering::getOpndList(), getOpRefinementSteps(), llvm::SIInstrInfo::getOpSize(), getOptimalRepType(), llvm::opt::OptTable::getOption(), llvm::VPlan::getOrAddLiveIn(), llvm::VPlan::getOrAddLiveIn(), llvm::ConstantUniqueMap< ConstantArray >::getOrCreate(), llvm::LexicalScopes::getOrCreateAbstractScope(), llvm::ContextTrieNode::getOrCreateChildContext(), llvm::sampleprof::ProfileConverter::FrameNode::getOrCreateChildFrame(), llvm::SPIRVGlobalRegistry::getOrCreateConsIntVector(), llvm::SPIRVGlobalRegistry::getOrCreateConstIntArray(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), llvm::SPIRVGlobalRegistry::getOrCreateConstVector(), llvm::SPIRVGlobalRegistry::getOrCreateConstVector(), llvm::SampleContextTracker::getOrCreateContextPath(), getOrCreateDebugLoc(), getOrCreateFixedStackObject(), getOrCreateFrameHelper(), llvm::getOrCreateFunctionComdat(), llvm::pdb::SymbolCache::getOrCreateGlobalSymbolByOffset(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfCompileUnit::getOrCreateImportedEntityDIE(), llvm::OpenMPIRBuilder::getOrCreateInternalVariable(), llvm::LiveStacks::getOrCreateInterval(), llvm::SPIRVGlobalRegistry::getOrCreateLayoutType(), llvm::jitlink::getOrCreateLocalMachOHeader(), getOrCreateLogFile(), llvm::VPSlotTracker::getOrCreateName(), GetOrCreateOffsetCache(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunctionPtr(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::MCContext::getOrCreateSymbol(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::InformationCache::getOrCreateUniqueBlockExecutionSet(), llvm::sandboxir::Context::getOrCreateValueInternal(), getOrderedBlocks(), llvm::getOrderedReduction(), llvm::AllocationOrder::getOrderLimitEnd(), llvm::AbstractDependenceGraphBuilder< GraphType >::getOrdinal(), llvm::AbstractDependenceGraphBuilder< GraphType >::getOrdinal(), llvm::COFF::ImportLookupTableEntry32::getOrdinal(), llvm::object::import_lookup_table_entry< support::little32_t >::getOrdinal(), llvm::MachineOptimizationRemarkEmitterPass::getORE(), llvm::OptimizationRemarkEmitterWrapperPass::getORE(), llvm::getOrEnforceKnownAlignment(), llvm::WindowScheduler::getOriCycle(), llvm::ISD::InputArg::getOrigArgIndex(), llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit(), llvm::WindowScheduler::getOriMI(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::VPIntrinsic::getOrInsertDeclarationForParams(), llvm::AMDGPULibFunc::getOrInsertFunction(), llvm::CallGraph::getOrInsertFunction(), llvm::EquivalenceClasses< BasicBlock * >::getOrInsertLeaderValue(), llvm::getOrInsertLibFunc(), llvm::LLVMContextImpl::getOrInsertSyncScopeID(), llvm::ModuleSummaryIndex::getOrInsertValueInfo(), llvm::ModuleSummaryIndex::getOrInsertValueInfo(), getOrInsertValueProfilingCall(), llvm::WindowScheduler::getOriStage(), llvm::vfs::OutputFile::getOS(), getOuterLoopLatchCmp(), llvm::AArch64InstrInfo::getOutlinableRanges(), llvm::outliner::GlobalOutlinedFunction::getOutliningCost(), llvm::TargetInstrInfo::getOutliningType(), llvm::AArch64InstrInfo::getOutliningTypeImpl(), getOutputChainFromCallSeq(), getOutputSegmentMap(), llvm::object::DirectX::PSVRuntimeInfo::getOutputVectorMasks(), llvm::Intrinsic::IITDescriptor::getOverloadArgNumber(), llvm::rdf::InstrNode::getOwner(), getPack(), llvm::VECustomDAG::getPack(), getPackedVectorTypeFromPredicateType(), llvm::HexagonShuffler::GetPacketSummary(), getPACKOpcode(), llvm::HvxSelector::getPairVT(), llvm::CallBase::getParamAttr(), llvm::CallBase::getParamAttr(), llvm::coverage::mcdc::getParams(), llvm::FunctionType::getParamType(), llvm::dwarf_linker::parallel::CompileUnit::getParent(), llvm::LiveRangeEdit::getParent(), llvm::logicalview::LVObject::getParent(), llvm::DWARFDebugNames::Entry::getParentDIEEntry(), llvm::DWARF5AccelTableData::getParentDieOffsetAndUnitID(), llvm::DWARFUnit::getParentEntry(), llvm::MCCVFunctionInfo::getParentFuncId(), llvm::SourceMgr::getParentIncludeLoc(), llvm::logicalview::LVObject::getParentScope(), llvm::logicalview::LVObject::getParentSymbol(), llvm::TargetLoweringBase::getPartialReduceMLAAction(), llvm::AArch64TTIImpl::getPartialReductionCost(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::MCSectionWasm::getPassive(), llvm::PMDataManager::getPassManagerType(), getPayloadString(), llvm::pdb::SymbolGroup::getPdbModuleStream(), llvm::getPerfectShuffleCost(), getPermuteMask(), llvm::jitlink::EHFrameCFIBlockInspector::getPersonalityEdge(), llvm::MCSymbolXCOFF::getPerSymbolCodeModel(), llvm::memoryaccess_def_iterator_base< MemoryAccess >::getPhiArgBlock(), llvm::PeelingModuloScheduleExpander::getPhiCanonicalReg(), getPHIDeps(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), getPhiRegs(), getPhiRegs(), llvm::VirtRegMap::getPhys(), getPhysicalRegisterVT(), getPhysicalRegisterVT(), llvm::DataDependenceGraph::getPiBlock(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::getPipeType(), llvm::LoopVectorizationPlanner::getPlanFor(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getPLTStub(), llvm::PluginLoader::getPlugin(), llvm::RegBankSelect::InsertPoint::getPoint(), getPointeeType(), getPointer(), llvm::VPIntrinsic::getPointerAlignment(), llvm::ScalarEvolution::getPointerBase(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), getPointerOperands(), llvm::MipsRegisterInfo::getPointerRegClass(), llvm::SparcRegisterInfo::getPointerRegClass(), llvm::WebAssemblyRegisterInfo::getPointerRegClass(), llvm::X86RegisterInfo::getPointerRegClass(), llvm::TargetTransformInfo::getPointersChainCost(), llvm::getPointersDiff(), llvm::SPIRVGlobalRegistry::getPointerStorageClass(), llvm::SimpleBitstreamCursor::getPointerToBit(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::AArch64TTIImpl::getPopcntSupport(), llvm::GCNTTIImpl::getPopcntSupport(), llvm::LoongArchTTIImpl::getPopcntSupport(), llvm::PPCTTIImpl::getPopcntSupport(), llvm::RISCVTTIImpl::getPopcntSupport(), llvm::SystemZTTIImpl::getPopcntSupport(), llvm::WebAssemblyTTIImpl::getPopcntSupport(), llvm::X86TTIImpl::getPopcntSupport(), getPopRetOpcode(), llvm::cl::bits< DataType, Storage, ParserClass >::getPosition(), llvm::cl::list< std::string, DebugCounter >::getPosition(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::getPostDomTree(), llvm::SCEVAddRecExpr::getPostIncExpr(), getPostIncrementOperand(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::LoopBlocksDFS::getPostorder(), getPotentialCopiesOfMemoryValue(), llvm::ScalarEvolution::getPowerOfTwo(), llvm::AArch64FunctionInfo::getPPRCalleeSavedStackSize(), llvm::MCSectionGOFF::getPRAttributes(), llvm::X86MachineFunctionInfo::getPreallocatedArgOffsets(), llvm::X86MachineFunctionInfo::getPreallocatedStackSize(), llvm::LoopVectorizationCostModel::getPredBlockCostDivisor(), llvm::rdf::PhiUseNode::getPredecessor(), llvm::getPredForFCmpCode(), llvm::IRSimilarity::IRInstructionData::getPredicate(), llvm::MachineOperand::getPredicate(), llvm::VPCmpIntrinsic::getPredicate(), llvm::VPIRFlags::getPredicate(), getPredicatedRegister(), llvm::NearMissInfo::getPredicateError(), getPredicateForFixedLengthVector(), getPredicateForScalableVector(), llvm::HexagonInstrInfo::getPredReg(), getPredState(), llvm::opt::Option::getPrefix(), llvm::X86Operand::getPrefix(), llvm::opt::Option::getPrefixedName(), llvm::CanonicalLoopInfo::getPreheader(), llvm::CanonicalLoopInfo::getPreheaderIP(), llvm::VPRegionBlock::getPreheaderVPBB(), llvm::RegPressureTracker::getPressureAfterInst(), llvm::HexagonBlockRanges::InstrIndexMap::getPrevIndex(), llvm::DWARFUnit::getPreviousSiblingEntry(), llvm::sandboxir::Instruction::getPrevNode(), getPRMT(), getPRMTSelector(), getProbeFNameForGUID(), llvm::SampleProfileLoaderBaseImpl< FT >::getProbeWeight(), llvm::MachineTraceMetrics::getProcReleaseAtCycles(), llvm::MCSchedModel::getProcResource(), llvm::MachineTraceMetrics::Ensemble::getProcResourceDepths(), llvm::MachineTraceMetrics::Ensemble::getProcResourceHeights(), llvm::ProfileSummaryInfo::getProfileCount(), llvm::memprof::DataAccessProfData::getProfileRecord(), llvm::AVR::getProgramMemoryBank(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSaveRestoreInfo(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSpills(), getPromotedVectorElementType(), getPromotedVTForPredicate(), llvm::NVPTXTargetLowering::getPrototype(), llvm::MIR2VecVocabLegacyAnalysis::getProvider(), llvm::raw_ostream_proxy_adaptor< RawPwriteStreamT >::getProxiedOS(), llvm::PressureChange::getPSet(), getPSHUFShuffleMask(), getPTest(), getPtr(), getPtrOrVecOfPtrsWithNewAS(), llvm::getPtrStride(), llvm::ConstantExpr::getPtrToAddr(), llvm::ConstantExpr::getPtrToInt(), llvm::ScalarEvolution::getPtrToIntExpr(), getQDOTXResultType(), GetQuadraticEquation(), llvm::Attribute::getRange(), getRangeForAffineARHelper(), getRangeViaSLT(), llvm::AnyMemIntrinsic::getRawElementSizeInBytes(), llvm::AttrBuilder::getRawIntAttr(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness >::getRawOffset(), getRC32(), llvm::ReachingDefInfo::getReachingDef(), llvm::InlineCost::getReason(), llvm::TargetInstrInfo::getReassociationOpcodes(), llvm::VPRecipeBuilder::getRecipe(), getReciprocalOpName(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::LoopVectorizationLegality::getRecurrenceDescriptor(), llvm::getRecurrenceIdentity(), getReducedType(), llvm::getReductionStyle(), llvm::AMDGPU::getRedzoneSizeForGlobal(), llvm::Intrinsic::IITDescriptor::getRefArgNumber(), llvm::cas::ObjectProxy::getReferenceID(), llvm::DstOp::getReg(), llvm::MachineOperand::getReg(), llvm::mca::MCAOperand::getReg(), llvm::MCOperand::getReg(), llvm::RegOrConstant::getReg(), llvm::SDep::getReg(), llvm::X86Operand::getReg(), XtensaOperand::getReg(), llvm::MachineRegisterInfo::getRegAllocationHint(), llvm::AArch64RegisterInfo::getRegAllocationHints(), llvm::MachineRegisterInfo::getRegAllocationHints(), llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::SIRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::RegisterBankInfo::getRegBank(), llvm::RegisterBankInfo::getRegBankFromConstraints(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::DstOp::getRegClass(), llvm::MachineRegisterInfo::getRegClass(), llvm::MCRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClass(), llvm::MCInstrInfo::getRegClassByHwModeTable(), llvm::MachineInstr::getRegClassConstraint(), llvm::MachineInstr::getRegClassConstraintEffect(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SIRegisterInfo::getRegClassForSizeOnBank(), getRegClassForSVT(), getRegClassFromGRPhysReg(), llvm::RISCVTargetLowering::getRegClassIDForVecVT(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::SparcTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::object::Elf_Mips_Options< ELFT >::getRegInfo(), llvm::GCNIterativeScheduler::getRegionPressure(), llvm::MCCFIInstruction::getRegister(), llvm::MCRegisterClass::getRegister(), llvm::MCCFIInstruction::getRegister2(), getRegisterByIndex(), llvm::X86TargetLowering::getRegisterByName(), llvm::TargetRegisterInfo::getRegisterCosts(), llvm::cl::getRegisteredOptions(), getRegisterName(), getRegistersForValue(), getRegistersForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::MachineOperand::getRegLiveOut(), llvm::MachineOperand::getRegMask(), llvm::InlineAsm::Flag::getRegMayBeFolded(), LiveDebugValues::MLocTracker::getRegMLoc(), getRegOrUndef(), llvm::rdf::RefNode::getRegRef(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::getRegSequenceSubReg(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::SIRegisterInfo::getRegSplitParts(), llvm::getRegState(), llvm::getRegSubRegPair(), getRegTy(), getReinterpretiveCast_i16_to_i32(), getReinterpretiveCast_i8_to_i32(), llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::rdf::DataFlowGraph::getRelatedRefs(), llvm::DWARFDataExtractorSimple::getRelocatedValueImpl(), llvm::jitlink::Edge::getRelocation(), llvm::object::MachOObjectFile::getRelocationOffset(), llvm::object::getRelocationResolver(), llvm::CCState::getRemainingRegParmsForType(), slpvectorizer::BoUpSLP::getReorderingData(), llvm::RegBankSelect::getRepairCost(), llvm::BuildVectorSDNode::getRepeatedSequence(), llvm::BasicTTIImplBase< BasicTTIImpl >::getReplicationShuffleCost(), llvm::TargetTransformInfo::getReplicationShuffleCost(), llvm::X86TTIImpl::getReplicationShuffleCost(), llvm::MCSymbolXCOFF::getRepresentedCsect(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::CSKYRegisterInfo::getReservedRegs(), llvm::LoongArchRegisterInfo::getReservedRegs(), llvm::MachineRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::RISCVRegisterInfo::getReservedRegs(), llvm::SIRegisterInfo::getReservedRegs(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::SDDbgOperand::getResNo(), llvm::dxil::getResourceNameFromBindingCall(), llvm::MachineTraceMetrics::getResources(), llvm::mca::getResourceStateIndex(), llvm::AnalysisManager< LazyCallGraph::SCC, LazyCallGraph & >::getResult(), llvm::NumericSubstitution::getResultRegex(), llvm::AnyCoroEndInst::getResults(), getRetComponentType(), llvm::coro::Shape::getRetconCoroId(), llvm::coro::Shape::getRetconResultTypes(), llvm::coro::Shape::getRetconResumeTypes(), llvm::ARCFunctionInfo::getReturnStackOffset(), llvm::XCoreFunctionInfo::getReturnStackOffset(), llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::getRInfo(), llvm::MVT::getRISCVVectorTupleNumFields(), llvm::DependenceGraphInfo< DDGNode >::getRoot(), llvm::DominatorTreeBase< BlockT, false >::getRoot(), llvm::DomSetType< BasicBlock, false >::getRoot(), llvm::VPMatchContext::getRootBaseOpcode(), slpvectorizer::BoUpSLP::getRootNodeScalars(), llvm::EVT::getRoundIntegerType(), llvm::PBQP::Matrix::getRowAsVector(), llvm::PBQP::Matrix::getRows(), getSafeDivisor(), llvm::InstCombiner::getSafeVectorConstantForBinop(), getSalvageOpsForGEP(), getSameOpcode(), llvm::getSamplerName(), llvm::dxil::ResourceTypeInfo::getSamplerType(), llvm::GlobalValue::getSanitizerMetadata(), llvm::RISCVTTIImpl::getScalarizationOverhead(), llvm::SystemZTTIImpl::getScalarizationOverhead(), llvm::VPCostContext::getScalarizationOverhead(), llvm::X86TTIImpl::getScalarizationOverhead(), getScalarMaskingNode(), llvm::SPIRVGlobalRegistry::getScalarOrVectorBitWidth(), llvm::SPIRVGlobalRegistry::getScalarOrVectorComponentType(), llvm::getScalarReductionOpcode(), getScalarSizeInBits(), llvm::GFConstant::getScalarValue(), llvm::GIConstant::getScalarValue(), llvm::FixedPointSemantics::getScale(), getScaledOffsetForBitWidth(), getScalingFactorCost(), llvm::TargetTransformInfo::getScalingFactorCost(), llvm::SelectionDAG::getScatterVP(), llvm::ScalarEvolution::getSCEV(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSubtargetInfo::getSchedModelForCPU(), llvm::DebugLoc::getScope(), llvm::DIScope::getScope(), llvm::codeview::getScopeEndOffset(), llvm::codeview::getScopeParentOffset(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getScoreAtLevelRec(), llvm::SIRegisterInfo::getScratchInstrOffset(), llvm::MCSectionGOFF::getSDAttributes(), llvm::SDDbgOperand::getSDNode(), llvm::WindowScheduler::getSearchIndexes(), llvm::MCSymbol::getSection(), llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), llvm::MCAssembler::getSectionAddressSize(), llvm::jitlink::MachOLinkGraphBuilder::getSectionByIndex(), llvm::RuntimeDyld::getSectionContent(), llvm::dwarf_linker::parallel::OutputSections::getSectionDescriptor(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileXCOFF::getSectionForConstant(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileXCOFF::getSectionForExternalReference(), llvm::TargetLoweringObjectFileXCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock(), llvm::StaticDataProfileInfo::getSectionHotnessUsingDataAccessProfile(), llvm::object::COFFObjectFile::getSectionID(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSectionId(), llvm::RuntimeDyld::getSectionLoadAddress(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::XCOFFCsectAuxRef::getSectionOrLength32(), llvm::object::XCOFFCsectAuxRef::getSectionOrLength64(), llvm::GlobalObject::getSectionPrefix(), llvm::logicalview::LVReader::getSectionRanges(), llvm::object::MachOObjectFile::getSectionRawFinalSegmentName(), llvm::object::MachOObjectFile::getSectionRawName(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::SelectionDAG::getSelect(), llvm::ProfileAnnotator::getSelectInstrProfile(), llvm::PBQP::Solution::getSelection(), llvm::ReservoirSampler< T, GenT >::getSelection(), llvm::gvn::AvailableValue::getSelectValue(), llvm::generic_gep_type_iterator< ItTy >::getSequentialElementStride(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::SelectionDAG::getSetCC(), llvm::AVRTargetLowering::getSetCCResultType(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SelectionDAG::getSetCCVP(), llvm::SelectionDAG::getSetFPEnv(), llvm::mca::RISCVSEWInstrument::getSEW(), llvm::RISCV::VSETVLIInfo::getSEW(), llvm::RISCV::VSETVLIInfo::getSEWLMULRatio(), llvm::RISCVVType::getSEWLMULRatio(), llvm::RISCVII::getSEWOpNum(), llvm::APInt::getSExtValue(), llvm::mca::MCAOperand::getSFPImm(), llvm::MCOperand::getSFPImm(), llvm::MCFragment::getSFrameAddrDelta(), llvm::MCFragment::getSFrameFDE(), llvm::dxbc::getShaderStage(), llvm::GetShadowBytes(), llvm::GetShadowBytesAfterScope(), getShape(), getShape(), llvm::VirtRegMap::getShape(), getShapedOperandsForInst(), llvm::SelectionDAG::getShiftAmountConstant(), llvm::SelectionDAG::getShiftAmountConstant(), llvm::TargetLoweringBase::getShiftAmountTy(), getShiftedValue(), llvm::AArch64_AM::getShifterImm(), llvm::objcopy::elf::Symbol::getShndx(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getShuffleCost(), llvm::GCNTTIImpl::getShuffleCost(), llvm::RISCVTTIImpl::getShuffleCost(), llvm::TargetTransformInfo::getShuffleCost(), llvm::X86TTIImpl::getShuffleCost(), getShuffleDemandedElts(), llvm::getShuffleDemandedElts(), getShuffleHalfVectors(), llvm::MachineOperand::getShuffleMask(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::getShuffleReduction(), getShuffleScalarElt(), llvm::ConstantExpr::getShuffleVector(), getShufflevectorNumGroups(), getSHUFPDImm(), llvm::dwarf_linker::parallel::CompileUnit::getSiblingEntry(), llvm::DWARFUnit::getSiblingEntry(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getSignExtendExprImpl(), GetSignReturnAddress(), llvm::MipsMCCodeEmitter::getSimm18Lsl3Encoding(), llvm::MipsMCCodeEmitter::getSimm19Lsl2Encoding(), llvm::MipsMCCodeEmitter::getSimm23Lsl2Encoding(), llvm::MachineRegisterInfo::getSimpleHint(), llvm::codeview::TypeIndex::getSimpleKind(), llvm::codeview::TypeIndex::getSimpleMode(), llvm::gvn::AvailableValue::getSimpleValue(), llvm::EVT::getSimpleVT(), llvm::lto::InputFile::getSingleBitcodeModule(), llvm::sandboxir::Interval< T >::getSingleDiff(), llvm::getSingleElement(), getSingleSchedPred(), llvm::Twine::getSingleStringRef(), llvm::HvxSelector::getSingleVT(), llvm::DIE::getSize(), llvm::HexagonInstrInfo::getSize(), llvm::MVT::getSizeInBits(), llvm::RegisterBankInfo::getSizeInBits(), llvm::codeview::getSizeInBytesForTypeIndex(), llvm::MipsMCCodeEmitter::getSizeInsEncoding(), llvm::sandboxir::SeedBundle::getSlice(), llvm::StackMapParser< Endianness >::LocationAccessor::getSmallConstant(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), getSmallestVTForIndex(), llvm::AMDGPU::getSMRDEncodedOffset(), llvm::ARM_AM::getSOImmTwoPartSecond(), getSortedConstantKeys(), llvm::SuccIterator< Instruction, BasicBlock >::getSource(), llvm::pdb::SymbolCache::getSourceFileById(), getSPDenormModeValue(), llvm::SystemZSubtarget::getSpecialRegisters(), llvm::MCAsmInfo::getSpecifierName(), slpvectorizer::BoUpSLP::getSpillCost(), getSpillFunctionFor(), llvm::coro::getSpillInsertionPt(), LiveDebugValues::MLocTracker::getSpillMLoc(), llvm::M68kRegisterInfo::getSpillRegisterOrder(), llvm::getSPIRVStringOperand(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), llvm::APInt::getSplat(), llvm::ConstantDataVector::getSplat(), llvm::SelectionDAG::getSplat(), getSplatableConstant(), llvm::SelectionDAG::getSplatBuildVector(), llvm::PPC::getSplatIdxForPPCMnemonics(), llvm::getSplatIndex(), llvm::getSplatIndex(), llvm::ShuffleVectorSDNode::getSplatMaskIndex(), llvm::SelectionDAG::getSplatSourceVector(), llvm::BuildVectorSDNode::getSplatValue(), llvm::Constant::getSplatValue(), llvm::SelectionDAG::getSplatVector(), llvm::AArch64TTIImpl::getSpliceCost(), llvm::MemOp::getSrcAlign(), llvm::R600InstrInfo::getSrcs(), llvm::object::XCOFFCsectAuxRef::getStabInfoIndex32(), llvm::object::XCOFFCsectAuxRef::getStabSectNum32(), llvm::RISCVZC::getStackAdjBase(), llvm::Attribute::getStackAlignment(), llvm::ModuleSummaryIndex::getStackIdAtIndex(), llvm::PPCTargetLowering::getStackProbeSize(), llvm::SystemZTargetLowering::getStackProbeSize(), llvm::AArch64FunctionInfo::getStackSizePPR(), llvm::AArch64FunctionInfo::getStackSizeZPR(), llvm::VirtRegMap::getStackSlot(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::getStartAndEndForAccess(), llvm::ThreadSafeTrieRawHashMapBase::getStartBit(), llvm::ConcurrentHashTableByPtr< KeyTy, KeyDataTy, AllocatorTy, Info >::getStartIdx(), getStartOrEndSlot(), getStartValueFromReductionResult(), llvm::TargetLibraryInfo::getState(), llvm::GCProjectionInst::getStatepoint(), llvm::InlineCost::getStaticBonusApplied(), llvm::VPIntrinsic::getStaticVectorLength(), llvm::SelectionDAG::getStepVector(), llvm::MCSymbolXCOFF::getStorageClass(), llvm::object::COFFSymbolRef::getStorageClass(), llvm::TargetLoweringObjectFileXCOFF::getStorageClassForGlobal(), llvm::DIDerivedType::getStorageOffsetInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getStore(), llvm::RISCVTTIImpl::getStoreImmCost(), llvm::MemoryDepChecker::getStoreLoadForwardSafeDistanceInBits(), llvm::VNCoercion::getStoreValueForLoadHelper(), llvm::SelectionDAG::getStoreVP(), getSToVPermuted(), llvm::SelectionDAG::getStrictFPExtendOrRound(), llvm::AArch64RegisterInfo::getStrictlyReservedRegs(), llvm::DIGenericSubrange::getStride(), llvm::DISubrange::getStride(), llvm::SelectionDAG::getStridedLoadVP(), llvm::SelectionDAG::getStridedStoreVP(), llvm::gsym::GsymCreator::getString(), llvm::msgpack::DocNode::getString(), llvm::pdb::NamedStreamMap::getString(), llvm::AsmToken::getStringContents(), llvm::codeview::DebugStringTableSubsection::getStringForId(), llvm::ir2vec::Vocabulary::getStringKey(), llvm::mir2vec::MIRVocabulary::getStringKey(), llvm::DWARFUnit::getStringOffsetsBase(), llvm::pdb::PDBFile::getStringTable(), llvm::object::COFFSymbolRef::getStringTableOffset(), llvm::getStringValueFromReg(), llvm::dxil::ResourceTypeInfo::getStruct(), llvm::SCCPInstVisitor::getStructLatticeValueFor(), llvm::getStructTM(), llvm::getStructTMUtc(), getStructuredLoadFunction(), getStructuredStoreFunction(), llvm::TargetRegisterInfo::getSubClassWithSubReg(), llvm::AMDGPUMCExpr::getSubExpr(), llvm::ScheduleDAGTopologicalSort::GetSubGraph(), llvm::LoopBase< BlockT, LoopT >::getSubLoops(), llvm::LoopBase< BlockT, LoopT >::getSubLoopsVector(), llvm::getSubOpDesc(), llvm::dwarf::getSubOperationEncoding(), getSubprogram(), llvm::MachineOperand::getSubReg(), llvm::MCRegisterInfo::getSubReg(), llvm::R600RegisterInfo::getSubRegFromChannel(), llvm::SIRegisterInfo::getSubRegFromChannel(), llvm::TargetRegisterInfo::getSubRegIdxOffset(), llvm::TargetRegisterInfo::getSubRegIdxSize(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::TargetRegisterInfo::getSubRegIndexName(), llvm::RegionBase< Tr >::getSubRegionNode(), llvm::IndexedReference::getSubscript(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::AsmPrinter::getSubtargetInfo(), llvm::MCAsmBackend::getSubtargetInfo(), llvm::SchedDFSResult::getSubtreeID(), llvm::BranchInst::getSuccessor(), llvm::CallBrInst::getSuccessor(), llvm::CatchSwitchInst::getSuccessor(), llvm::InvokeInst::getSuccessor(), llvm::sandboxir::BranchInst::getSuccessor(), llvm::sandboxir::CatchSwitchInst::getSuccessor(), llvm::SwitchInst::getSuccessor(), llvm::SwitchInst::CaseHandleImpl< const SwitchInst, const ConstantInt, const BasicBlock >::getSuccessorIndex(), llvm::DCData::getSuccessorLabel(), llvm::GetSuccessorNumber(), getSuccState(), llvm::APInt::getSufficientBitsNeeded(), llvm::ScaledNumbers::getSum(), llvm::IndexedInstrProfReader::getSummary(), llvm::getSurfaceName(), llvm::AArch64FunctionInfo::getSVECalleeSavedStackSize(), getSVECalleeSaveSlotRange(), getSVEContainerType(), getSVEGatherScatterOverhead(), getSVEPredicateBitCast(), llvm::AArch64Subtarget::getSVEVectorSizeInBits(), llvm::coro::Shape::getSwitchCoroId(), llvm::coro::Shape::getSwitchIndexField(), llvm::coro::Shape::getSwitchResumePointerType(), llvm::object::COFFObjectFile::getSymbolAuxData(), llvm::object::XCOFFObjectFile::getSymbolAuxType(), llvm::pdb::SymbolCache::getSymbolById(), llvm::objcopy::macho::SymbolTable::getSymbolByIndex(), llvm::object::TapiFile::getSymbolFlags(), GetSymbolFromOperand(), llvm::M68kMCInstLower::GetSymbolFromOperand(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), llvm::object::COFFObjectFile::getSymbolIndex(), llvm::object::ExceptionSectionEntry< support::ubig32_t >::getSymbolIndex(), llvm::MachineOperand::getSymbolName(), llvm::memprof::Frame::getSymbolName(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSymbolNum(), GetSymbolRef(), llvm::RuntimeDyld::getSymbolSectionID(), llvm::object::TapiFile::getSymbolType(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::RawInstrProfReader< uint32_t >::getSymtab(), llvm::TextInstrProfReader::getSymtab(), getT2IndexedAddressParts(), llvm::ARM_AM::getT2SOImmTwoPartFirst(), llvm::ARM_AM::getT2SOImmTwoPartSecond(), llvm::MCSymbolWasm::getTableType(), getTagSymNode(), llvm::RISCV::VSETVLIInfo::getTailAgnostic(), getTargetConstantBitsFromNode(), llvm::RISCVTargetLowering::getTargetConstantFromLoad(), llvm::X86TargetLowering::getTargetConstantFromLoad(), getTargetIndexName(), llvm::RISCVTargetLowering::getTargetMMOFlags(), llvm::SelectionDAGGenTargetInfo::getTargetNodeName(), getTargetShuffleAndZeroables(), getTargetShuffleMask(), getTargetVShiftByConstNode(), getTargetVShiftNode(), llvm::RawInstrProfReader< IntPtrT >::getTemporalProfTraces(), getTestBitReg(), getTestUnderMaskCond(), llvm::coverage::MCDCRecord::getTestVectorString(), llvm::MCSectionGOFF::getTextStyle(), llvm::getTextureName(), llvm::AArch64RegisterInfo::getThisReturnPreservedMask(), llvm::parallel::PerThreadAllocator< BumpPtrAllocator >::getThreadLocalAllocator(), llvm::MachineModuleInfoMachO::getThreadLocalGVStubEntry(), llvm::PPCSubtarget::getThreadPointerRegister(), llvm::InlineCost::getThreshold(), llvm::MachineIRBuilder::getTII(), getTileReg(), llvm::RISCVII::getTKOpNum(), GetTLSADDR(), llvm::AArch64RegisterInfo::getTLSCallPreservedMask(), llvm::ARMBaseRegisterInfo::getTLSCallPreservedMask(), llvm::RISCVII::getTMOpNum(), llvm::RISCVII::getTNOpNum(), llvm::PPCSubtarget::getTOCPointerRegister(), llvm::X86Operand::getToken(), XtensaOperand::getToken(), llvm::logicalview::LVDWARFReader::getTombstoneAddress(), llvm::SelectionDAG::getTopologicallyOrderedNodes(), llvm::orc::TrampolinePool::getTrampoline(), llvm::AMDGPU::getTransitiveUsesOfLDS(), getTransSwizzle(), llvm::object::ExceptionSectionEntry< support::ubig32_t >::getTrapInstAddr(), slpvectorizer::BoUpSLP::getTreeCost(), llvm::ThreadSafeTrieRawHashMapBase::getTriePrefixAsString(), llvm::CanonicalLoopInfo::getTripCount(), llvm::VPlan::getTripCount(), llvm::ScalarEvolution::getTripCountFromExitCount(), llvm::ConstantInt::getTrue(), getTrueOrFalseValue(), getTrueOrFalseValue(), llvm::ConstantExpr::getTrunc(), llvm::VectorType::getTruncatedElementVectorType(), getTruncatedUSUBSAT(), llvm::ScalarEvolution::getTruncateExpr(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::ScalarEvolution::getTruncateOrSignExtend(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStridedStoreVP(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::RISCV::VSETVLIInfo::getTWiden(), getTwoPredecessors(), llvm::codeview::LazyRandomTypeCollection::getType(), llvm::codeview::TypeTableCollection::getType(), llvm::object::COFFSymbolRef::getType(), llvm::pdb::TpiStream::getType(), llvm::AttrBuilder::getTypeAttr(), llvm::BasicTTIImplBase< BasicTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::TargetLoweringBase::getTypeConversion(), llvm::dxil::ResourceTypeInfo::getTyped(), llvm::ConstantStruct::getTypeForElements(), llvm::sandboxir::ConstantStruct::getTypeForElements(), llvm::EVT::getTypeForEVT(), llvm::AMDGPUTargetLowering::getTypeForExtReturn(), llvm::SPIRVGlobalRegistry::getTypeForSPIRVType(), getTypeFromTypeIdx(), llvm::BitcodeReaderValueList::getTypeID(), llvm::dxil::ValueEnumerator::getTypeID(), llvm::ValueEnumerator::getTypeID(), llvm::BTFDebug::getTypeId(), llvm::getTypeName(), llvm::getTypePacking(), getTypePartition(), llvm::DataLayout::getTypeSizeInBits(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::TargetLoweringBase::getTypeToExpandTo(), llvm::TargetLoweringBase::getTypeToPromoteTo(), llvm::dxil::ResourceTypeInfo::getUAV(), llvm::ScalarEvolution::getUDivExpr(), llvm::VPlan::getUF(), llvm::MipsMCCodeEmitter::getUImm3Mod8Encoding(), llvm::MipsMCCodeEmitter::getUImm4AndValue(), llvm::MipsMCCodeEmitter::getUImm5Lsl2Encoding(), llvm::MipsMCCodeEmitter::getUImmWithOffsetEncoding(), llvm::msgpack::DocNode::getUInt(), llvm::msgpack::DocNode::getUInt(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), getUnderlyingExtractedFromVec(), llvm::getUnderlyingObject(), getUnderlyingObjectFromInt(), getUnderlyingObjectsForInstr(), llvm::logicalview::LVTypeDefinition::getUnderlyingType(), getUniformBase(), llvm::AAPointerInfo::RangeList::getUnique(), llvm::LoopBase< BasicBlock, Loop >::getUniqueExitBlocks(), llvm::getUniqueExitBlocksHelper(), llvm::Constant::getUniqueInteger(), llvm::LoopBase< BlockT, LoopT >::getUniqueLatchExitBlock(), llvm::LoopBase< BlockT, LoopT >::getUniqueNonLatchExitBlocks(), llvm::dwarf_linker::parallel::CompileUnit::getUnitDIE(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::ScalarEvolution::getUnknown(), getUnmergeResults(), llvm::VECustomDAG::getUnpack(), llvm::PointerType::getUnqual(), llvm::MCSymbolXCOFF::getUnqualifiedName(), getUnrollAndJammedLoopSize(), llvm::UnrollCostEstimator::getUnrolledLoopSize(), llvm::GetUnrollMetadata(), getUnsignedCountTrailingZerosRange(), getUnsignedMonotonicValues(), getUnsignedPopCountRange(), llvm::DISourceLanguageName::getUnversionedName(), llvm::WasmEHFuncInfo::getUnwindDest(), llvm::WasmEHFuncInfo::getUnwindDest(), getUnwindDestToken(), getUnwindDestTokenHelper(), getUnwindRuleRegSet(), llvm::WasmEHFuncInfo::getUnwindSrcs(), llvm::WasmEHFuncInfo::getUnwindSrcs(), llvm::DIGenericSubrange::getUpperBound(), llvm::DISubrange::getUpperBound(), llvm::RegPressureTracker::getUpwardPressureDelta(), llvm::ScalarEvolution::getURemExpr(), getUsedNZCV(), llvm::DFAPacketizer::getUsedResources(), llvm::Attribute::getUWTableKind(), getV4X86ShuffleImm(), getv64i1Argument(), llvm::SelectionDAG::getValidMaximumShiftAmount(), llvm::SelectionDAG::getValidMinimumShiftAmount(), llvm::SelectionDAG::getValidShiftAmount(), llvm::GISelValueTracking::getValidShiftAmountRange(), llvm::SelectionDAG::getValidShiftAmountRange(), llvm::TrackingVH< ValueTy >::getValPtr(), llvm::ScheduleDAGSDNodes::RegDefIter::GetValue(), llvm::cl::OptionValueCopy< DataType >::getValue(), llvm::InstructionCost::getValue(), llvm::LocationSize::getValue(), llvm::object::COFFSymbolRef::getValue(), llvm::pdb::NativeSymbolEnumerator::getValue(), llvm::ValueInfo::getValue(), llvm::Attribute::getValueAsBool(), llvm::AttributeImpl::getValueAsBool(), llvm::Attribute::getValueAsConstantRange(), llvm::AttributeImpl::getValueAsConstantRange(), llvm::Attribute::getValueAsConstantRangeList(), llvm::AttributeImpl::getValueAsConstantRangeList(), llvm::Attribute::getValueAsInt(), llvm::AttributeImpl::getValueAsInt(), llvm::Attribute::getValueAsString(), llvm::AttributeImpl::getValueAsString(), llvm::Attribute::getValueAsType(), llvm::AttributeImpl::getValueAsType(), llvm::VNCoercion::getValueForLoad(), getValueFromBundleOpInfo(), llvm::ValueEnumerator::getValueID(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::LazyValueInfoImpl::getValueInBlock(), llvm::MCCFIInstruction::getValues(), llvm::PhiValues::getValuesForPhi(), llvm::SDNode::getValueType(), llvm::object::COFFObjectFile::getVaPtr(), llvm::TGVarScope::getVar(), llvm::WebAssemblyFunctionInfo::getVarargBufferVreg(), llvm::DbgVariableRecord::getVariableLocationOp(), llvm::RawLocationWrapper::getVariableLocationOp(), llvm::dwarf_linker::AddressesMap::getVariableRelocAdjustment(), llvm::MCSymbol::getVariableValue(), getVariantMatchScore(), llvm::LiveVariables::getVarInfo(), llvm::DIDerivedType::getVBPtrOffset(), GetVBR(), llvm::GlobalObject::getVCallVisibility(), llvm::RISCVII::getVecPolicyOpNum(), llvm::HexagonMCInstrInfo::GetVecRegPairIndices(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), getVectorBitwiseReduce(), llvm::Intrinsic::IITDescriptor::getVectorDivisor(), llvm::EVT::getVectorElementCount(), llvm::LegalizerHelper::getVectorElementPointer(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::VecDesc::getVectorFunctionABIVariantString(), getVectorInstrCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::getVectorizedTypeVF(), llvm::HexagonSubtarget::getVectorLength(), llvm::MVT::getVectorMinNumElements(), llvm::EVT::getVectorNumElements(), llvm::SIInstrInfo::getVectorRegSpillRestoreOpcode(), getVectorShiftImm(), llvm::SelectionDAG::getVectorShuffle(), getVectorShuffleOpcode(), llvm::TargetLowering::getVectorSubVecPointer(), llvm::SystemZTTIImpl::getVectorTruncCost(), llvm::AArch64TargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::AArch64BuildAttributes::getVendorName(), llvm::DISourceLanguageName::getVersion(), llvm::vputils::getVFScaleFactor(), getVFSEntries(), llvm::AMDGPU::getVGPRLoweringOperandTables(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), slpvectorizer::BoUpSLP::VLOperands::getVL(), getVLDSTRegisterUpdateOpcode(), llvm::RISCV::VSETVLIInfo::getVLMUL(), getVLOperand(), llvm::RISCVII::getVLOpNum(), llvm::RISCV::getVNInfoFromReg(), llvm::ir2vec::Vocabulary::getVocabKeyForOpcode(), llvm::ir2vec::Vocabulary::getVocabKeyForOperandKind(), llvm::AMDGPU::getVOPDComponents(), llvm::VPDef::getVPSingleValue(), llvm::VPDef::getVPSingleValue(), llvm::VPDef::getVPValue(), llvm::VPDef::getVPValue(), llvm::SelectionDAG::getVPZeroExtendInReg(), llvm::SDDbgOperand::getVReg(), llvm::DstOp::getVRegAttrs(), llvm::SelectionDAG::getVRegDbgValue(), llvm::MachineRegisterInfo::getVRegDef(), llvm::PerFunctionMIParsingState::getVRegInfoNamed(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), llvm::getVRegSubRegDef(), getVRGatherIndexType(), llvm::SelectionDAG::getVScale(), llvm::Attribute::getVScaleRangeMax(), llvm::Attribute::getVScaleRangeMin(), getVShift(), llvm::PPCMCCodeEmitter::getVSRpEvenEncoding(), llvm::MVT::getVT(), llvm::getVulkanBufferType(), llvm::getVulkanPushConstantType(), llvm::WebAssemblyFunctionInfo::getWAReg(), llvm::WebAssembly::getWARegStackId(), llvm::MachineFunction::getWasmLandingPadIndex(), getWFCountLimitedByGPR(), llvm::getWhileLoopStartTargetBB(), llvm::SIInstrInfo::getWholeWaveFunctionSetup(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::LoopVectorizationCostModel::getWideningDecision(), getWideningInterleave(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithAllocSizeArgs(), llvm::Attribute::getWithDereferenceableBytes(), llvm::Attribute::getWithDereferenceableOrNullBytes(), llvm::Type::getWithNewBitWidth(), llvm::Attribute::getWithNewType(), llvm::ConstantExpr::getWithOperands(), llvm::Attribute::getWithStackAlignment(), llvm::mca::WriteRef::getWriteBackCycle(), llvm::MCSubtargetInfo::getWriteLatencyEntry(), llvm::AAPointerInfo::Access::getWrittenValue(), getX86MaskVec(), getX86SubType(), getX86XALUOOp(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), llvm::MCContext::getXCOFFSection(), llvm::RISCVVType::getXSfmmWiden(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::RuntimeDyldChecker::MemoryRegionInfo::getZeroFillLength(), llvm::SlotIndexes::getZeroIndex(), getZeroPaddedAdd(), getZeroVector(), getZeroVector(), llvm::APInt::getZExtValue(), llvm::AArch64FunctionInfo::getZPRCalleeSavedStackSize(), llvm::AArch64FunctionInfo::getZT0SpillSlotIndex(), llvm::CodeViewYAML::GlobalHash::GlobalHash(), llvm::CodeViewYAML::GlobalHash::GlobalHash(), llvm::globalHasNVVMAnnotation(), llvm::codeview::GloballyHashedType::GloballyHashedType(), llvm::GlobalsAAResult::GlobalsAAResult(), llvm::GlobalValueSummary::GlobalValueSummary(), llvm::GlobalVariable::GlobalVariable(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::glueCompileUnitsAndWriteToTheOutput(), llvm::object::GOFFSymbolRef::GOFFSymbolRef(), llvm::FunctionSummary::GraphTraits< ValueInfo >, llvm::IntEqClasses::grow(), growShuffleMask(), guessCharByteSize(), llvm::ARM::WinEH::RuntimeFunction::H(), llvm::ARM::WinEH::RuntimeFunctionARM64::H(), llvm::CoalescingBitVector< IndexT >::half_open_range(), llvm::jitlink::aarch32::HalfWords::HalfWords(), llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleAddNode(), llvm::DotCfgChangeReporter::handleAfter(), handleAllocSite(), llvm::CallLowering::handleAssignments(), llvm::MipsTargetLowering::HandleByVal(), handleByValParam(), HandleCallsInBlockInlinedThroughInvoke(), handleCallSite(), llvm::AsmPrinter::handleCallsiteForCallgraph(), llvm::DIArgList::handleChangedOperand(), handleCMSEValue(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::FastISel::handleDbgInfo(), llvm::SelectionDAGBuilder::handleDebugDeclare(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::ValueAsMetadata::handleDeletion(), handleDiagnostic(), llvm::VPlanTransforms::handleEarlyExits(), llvm::CrashRecoveryContext::HandleExit(), llvm::DotCfgChangeReporter::handleFiltered(), llvm::coro::BaseCloner::handleFinalSuspend(), llvm::DotCfgChangeReporter::handleFunctionCompare(), llvm::DotCfgChangeReporter::handleIgnored(), llvm::DotCfgChangeReporter::handleInitialIR(), llvm::TextChangeReporter< IRUnitT >::handleInitialIR(), HandleInlinedEHPad(), llvm::DotCfgChangeReporter::handleInvalidated(), llvm::ChangeReporter< IRUnitT >::handleInvalidatedPass(), llvm::ChangeReporter< IRUnitT >::handleIRAfterPass(), llvm::HexagonTargetLowering::handleMaskRegisterForCallingConv(), llvm::VPlanTransforms::handleMaxMinNumReductions(), handleMemIntrinsicPtrUse(), llvm::orc::SimpleRemoteEPC::handleMessage(), llvm::orc::SimpleRemoteEPCServer::handleMessage(), handleMiddleInst(), llvm::LiveIntervals::handleMove(), llvm::LiveIntervals::handleMoveIntoNewBundle(), llvm::VPlanTransforms::handleMultiUseReductions(), handleMustTailForwardedRegisters(), handleNewDebugValue(), llvm::Constant::handleOperandChange(), llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), HandlePrefixedOrGroupedOption(), llvm::ValueAsMetadata::handleRAUW(), llvm::GISelCSEInfo::handleRecordedInst(), llvm::orc::LazyReexportsManager::handleRemoveResources(), llvm::VPRecipeBuilder::handleReplication(), llvm::VPlanTransforms::handleUncountableEarlyExit(), HandleUnsupportedAnnotationKinds(), llvm::LiveVariables::HandleVirtRegUse(), llvm::X86FrameLowering::has128ByteRedZone(), llvm::mdconst::hasa(), llvm::AliasSummary::hasAliasee(), llvm::MCFragment::hasAlignEmitNops(), llvm::RISCVDAGToDAGISel::hasAllNBitUsers(), hasAnyUnrollPragma(), llvm::SDNode::hasAnyUseOfValue(), hasAssumption(), llvm::hasAttributeInAssume(), llvm::hasBranchWeightOrigin(), llvm::DWARFDie::hasChildren(), hasConditionalTerminator(), llvm::scc_iterator< GraphT, GT >::hasCycle(), hasDebugInfo(), llvm::SDNodeInfo::hasDesc(), llvm::DomainValue::hasDomain(), llvm::DWARFDebugLine::Prologue::hasFileAtIndex(), llvm::SubtargetFeatures::hasFlag(), llvm::CallBase::hasFnAttr(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), hasFPAssociativeFlags(), llvm::ItaniumPartialDemangler::hasFunctionQualifiers(), llvm::hashing::detail::hash_combine_range_impl(), llvm::hash_value(), llvm::pdb::hashTagRecord(), hasIdenticalHalvesShuffleMask(), hasIntersectProperty(), llvm::AArch64TTIImpl::hasKnownLowerThroughputFromSchedulingModel(), hasLoopCarriedMemDep(), llvm::RawInstrProfReader< uint32_t >::hasMemoryProfile(), llvm::GCNSchedStrategy::hasNextStage(), llvm::DbgValueHistoryMap::hasNonEmptyLocation(), llvm::SDNode::hasNUsesOfValue(), llvm::Attribute::hasParentContext(), llvm::AttributeSet::hasParentContext(), llvm::hasPartialIVCondition(), llvm::pdb::PDBFile::hasPDBInjectedSourceStream(), llvm::pdb::PDBFile::hasPDBStringTable(), llvm::MachineInstr::hasProperty(), llvm::X86InstrInfo::hasReassociableOperands(), llvm::HexagonPacketizerList::hasRegMaskDependence(), llvm::AMDGPU::VOPD::ComponentProps::hasRegSrcOperand(), llvm::RISCV::VSETVLIInfo::hasSameAVL(), llvm::RISCV::VSETVLIInfo::hasSameAVLLatticeValue(), hasSameExtUse(), llvm::cas::ReferenceBase::hasSameInternalRef(), llvm::RISCV::VSETVLIInfo::hasSameVLMAX(), llvm::RISCV::VSETVLIInfo::hasSameVTYPE(), llvm::VPlan::hasScalarVFOnly(), llvm::memprof::hasSingleAllocType(), hasSingleUse(), llvm::IndexedReference::hasSpacialReuse(), llvm::TargetLoweringBase::hasTargetDAGCombine(), llvm::IndexedReference::hasTemporalReuse(), hasUseOtherThanLLVMUsed(), llvm::VFShape::hasValidParameterList(), llvm::AMDGPU::hasValueInRangeLikeMetadata(), hasVectorBeenPadded(), haveCommonPrefix(), llvm::haveNoCommonBitsSet(), llvm::SelectionDAG::haveNoCommonBitsSet(), haveSameOperands(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::HexagonSubtarget::HexagonSubtarget(), llvm::TrieHashIndexGenerator::hint(), hoistAdd(), hoistAndMergeSGPRInits(), hoistBOAssociation(), hoistConditionalLoadsStores(), llvm::GCNTTIImpl::hoistLaneIntrinsicThroughOperand(), hoistLoopToNewParent(), hoistMinMax(), hoistMulAddAssociation(), hoistPreviousBeforeFORUsers(), llvm::hoistRegion(), hoistSub(), hoistValue(), hostParallelCallback(), llvm::HUerrBound(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::identifyKnownAlignedObject(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::identifyKnownObject(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::IDFCalculator< false >::IDFCalculator(), llvm::memprof::MemProfReader::idToFrame(), if(), IfNeededExtSP(), IfNeededLDAWSP(), llvm::HexagonInstrInfo::immediateExtend(), llvm::LegalizeRuleSet::immIdx(), llvm::AArch64::ArchInfo::implies(), llvm::FunctionImporter::importFunctions(), llvm::cas::ObjectStore::importObject(), llvm::GCNRegPressure::inc(), llvm::includes(), llvm::includes(), incomingValuesAreCompatible(), llvm::ValueEnumerator::incorporateFunction(), incorporateNewSCCRange(), increaseSetPressure(), llvm::SmallPtrSetIteratorImpl::increment(), llvm::vfs::directory_iterator::increment(), llvm::vfs::recursive_directory_iterator::increment(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::memtag::incrementThreadLong(), llvm::Register::index2StackSlot(), llvm::Register::index2VirtReg(), llvm::IndexedReference::IndexedReference(), indirectCopyToAGPR(), inferDomainOfAffine(), inferInitializes(), llvm::VPTypeAnalysis::inferScalarType(), llvm::PGOCtxProfContext::ingestAllContexts(), llvm::coro::AnyRetconABI::init(), llvm::coro::AsyncABI::init(), llvm::coro::SwitchABI::init(), llvm::FunctionVarLocs::init(), llvm::MemoryBuffer::init(), llvm::RegBankSelect::init(), llvm::RegPressureTracker::init(), llvm::SchedRemainder::init(), llvm::StringMapImpl::init(), llvm::Timer::init(), StaleMatcher::init(), llvm::CodeGenTargetMachineImpl::initAsmInfo(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), llvm::PreRARematStage::initGCNSchedStage(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::codeview::DebugInlineeLinesSubsectionRef::initialize(), llvm::dxil::ModuleShaderFlags::initialize(), llvm::GenericScheduler::initialize(), llvm::orc::LLJIT::initialize(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::initialize(), llvm::orc::SharedMemoryMapper::initialize(), llvm::R600SchedStrategy::initialize(), llvm::StackProtectorDescriptor::initialize(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::MCAsmInfo::initializeAtSpecifiers(), llvm::pdb::UDTLayoutBase::initializeChildren(), llvm::MIRParserImpl::initializeMachineFunction(), initializeRecordStreamer(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::GCNSubtarget::initializeSubtargetDependencies(), llvm::MipsSubtarget::initializeSubtargetDependencies(), llvm::AMDGPUTargetStreamer::initializeTargetID(), llvm::AMDGPUTargetStreamer::initializeTargetID(), llvm::mca::initializeUsedResources(), llvm::MipsSubtarget::initLibcallLoweringInfo(), llvm::RegPressureTracker::initLiveThru(), llvm::InitLLVM::InitLLVM(), llvm::TailDuplicator::initMF(), llvm::ScheduleDAGSDNodes::InitNumRegDefsLeft(), llvm::ResourceManager::initProcResourceVectors(), llvm::ScheduleDAGMILive::initQueues(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::jitlink::initRelaxAux(), llvm::MachineFunction::initTargetMachineFunctionInfo(), llvm::WebAssemblyFunctionInfo::initWARegs(), injectPendingInvariantConditions(), llvm::InlineFunction(), llvm::InlineFunctionImpl(), inlineGetBaseAndOffset(), inlineHistoryIncludes(), inlineHistoryIncludes(), inlineRetainOrClaimRVCalls(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::jitlink::InProcessMemoryManager::InProcessMemoryManager(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), llvm::FullDependence::inSameSDLoops(), llvm::IRBuilderBase::Insert(), llvm::BitTracker::RegisterCell::insert(), llvm::const_iterator< MemoryLocation >::insert(), llvm::const_iterator< MemoryLocation >::insert(), llvm::ConstantRangeList::insert(), llvm::GISelWorkList< 512 >::insert(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, Sizer::BranchSize, Traits >::insert(), llvm::IntervalTree< LVAddress, LVScope * >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineInstr::insert(), llvm::PriorityWorklist< T, VectorT, MapT >::insert(), llvm::RewriteRope::insert(), llvm::RuntimePointerChecking::insert(), llvm::sandboxir::MemSeedBundle< sandboxir::StoreInst >::insert(), llvm::sandboxir::ReadyListContainer::insert(), llvm::StableFunctionMap::insert(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::insert(), llvm::ThreadSafeTrieRawHashMapBase::insert(), llvm::TinyPtrVector< ReachingDef >::insert(), llvm::TinyPtrVector< ReachingDef >::insert(), llvm::VPBasicBlock::insert(), insert128BitVector(), insert1BitVector(), llvm::DbgRecord::insertAfter(), llvm::DbgRecord::insertAfter(), llvm::MachineBasicBlock::insertAfter(), llvm::VPRecipeBase::insertAfter(), llvm::MachineBasicBlock::insertAfterBundle(), llvm::objcarc::BundledRetainClaimRVs::insertAfterInvokes(), llvm::ScheduleDAGInstrs::insertBarrierChain(), llvm::DbgRecord::insertBefore(), llvm::DbgRecord::insertBefore(), llvm::VPRecipeBase::insertBefore(), llvm::VPRecipeBase::insertBefore(), insertBitcasts(), llvm::APInt::insertBits(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertBlockBefore(), llvm::AArch64InstrInfo::insertBranch(), llvm::ARCInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::AVRInstrInfo::insertBranch(), llvm::BPFInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::M68kInstrInfo::insertBranch(), llvm::MipsInstrInfo::insertBranch(), llvm::MSP430InstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::XCoreInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranchAtInst(), insertCandidatesWithPendingInjections(), llvm::XtensaInstrInfo::insertConstBranchAtInst(), llvm::AArch64TargetLowering::insertCopiesSplitCSR(), insertCSRSaves(), llvm::DIBuilder::insertDbgAssign(), llvm::DbgMarker::insertDbgRecord(), llvm::DbgMarker::insertDbgRecordAfter(), llvm::InsertDebugValueAtStoreLoc(), llvm::insertDebugValuesForPHIs(), llvm::DIBuilder::insertDeclare(), llvm::DIBuilder::insertDeclareValue(), llvm::MemorySSAUpdater::insertDef(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), llvm::DominatorTreeBase< BlockT, false >::insertEdge(), llvm::LazyCallGraph::insertEdge(), insertFoldCacheEntry(), InsertFPConstInst(), llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::insertFrom(), llvm::MachineModuleInfo::insertFunction(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::AArch64InstrInfo::insertIndirectBranch(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::XtensaInstrInfo::insertIndirectBranch(), insertInlineAsmProcess(), insertInteger(), llvm::LazyCallGraph::RefSCC::insertInternalRefEdge(), llvm::ScopedHashTable< MachineInstr *, unsigned, MachineInstrExpressionTrait, AllocatorTy >::insertIntoScope(), llvm::DIBuilder::insertLabel(), insertLifetimeMarkersSurroundingCall(), llvm::SPIRVTargetLowering::insertLogicalCopyOnResult(), insertLoopExpansion(), llvm::SlotIndexes::insertMachineInstrInMaps(), insertMaskedValue(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), llvm::insertMultibyteShift(), llvm::InstCombiner::InsertNewInstBefore(), InsertNewValueIntoMap(), llvm::FoldingSetBase::InsertNode(), llvm::FoldingSetImpl< FoldingSet, T >::InsertNode(), llvm::MipsInstrInfo::insertNop(), insertNopBeforeInstruction(), llvm::LazyCallGraph::RefSCC::insertOutgoingEdge(), llvm::AArch64InstrInfo::insertOutlinedCall(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), insertParsePoints(), llvm::TargetPassConfig::insertPass(), insertPHI(), llvm::sandboxir::InsertPosition::InsertPosition(), llvm::InstCombinerImpl::insertRangeTest(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::codeview::AppendingTypeTableBuilder::insertRecord(), llvm::codeview::GlobalTypeTableBuilder::insertRecord(), llvm::codeview::MergingTypeTableBuilder::insertRecord(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), llvm::codeview::MergingTypeTableBuilder::insertRecordAs(), insertRelocationStores(), insertRematerializationStores(), llvm::SIInstrInfo::insertReturn(), llvm::objcarc::BundledRetainClaimRVs::insertRVCallWithColors(), InsertSafepointPoll(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), insertSinCosCall(), InsertSPConstInst(), insertSpeculationBarrier(), insertSpills(), llvm::CallLowering::insertSRetIncomingArgument(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), InsertStackProtectors(), insertSubVector(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), llvm::VPBlockUtils::insertTwoBlocksAfter(), insertUniqueBackedgeBlock(), llvm::MemorySSAUpdater::insertUse(), insertValues(), insertVector(), llvm::SIInstrInfo::insertVectorSelect(), llvm::MachineRegisterInfo::insertVRegByName(), llvm::RISCVMatInt::Inst::Inst(), llvm::install_bad_alloc_error_handler(), llvm::install_fatal_error_handler(), llvm::install_out_of_memory_new_handler(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::PPCTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::HexagonBlockRanges::InstrIndexMap::InstrIndexMap(), llvm::RegBankSelect::InstrInsertPoint::InstrInsertPoint(), llvm::InstrProfError::InstrProfError(), llvm::HexagonMCInstrInfo::instruction(), llvm::mca::Scheduler::instructionCheck(), instructionClobbersQuery(), llvm::SampleProfileProber::instrumentOneFunc(), inSubLoop(), llvm::GVNExpression::AggregateValueExpression::int_op_push_back(), llvm::IntAttributeImpl::IntAttributeImpl(), llvm::IntegerInclusiveInterval::IntegerInclusiveInterval(), llvm::orc::MaterializationUnit::Interface::Interface(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::InterleaveGroup< InstTy >::InterleaveGroup(), interleaveVectors(), llvm::xray::Profile::internPath(), llvm::rdf::CopyPropagation::interpretAsCopy(), llvm::intersectAccessGroups(), llvm::VPIRFlags::intersectFlags(), llvm::APInt::intersects(), llvm::DWARFAddressRange::intersects(), llvm::ResourceSegments::intersects(), IntersectSignedRange(), IntersectUnsignedRange(), llvm::AttributeSet::intersectWith(), llvm::ConstantFPRange::intersectWith(), llvm::ConstantRange::intersectWith(), llvm::ConstantRangeList::intersectWith(), llvm::rdf::RegisterAggr::intersectWith(), llvm::CoalescingBitVector< IndexT >::intersectWithComplement(), llvm::sandboxir::Interval< T >::Interval(), llvm::sandboxir::Interval< T >::Interval(), llvm::IntervalData< PointT, ValueT >::IntervalData(), llvm::LiveIntervals::intervalIsInOneMBB(), llvm::IntervalMap< IndexT, char >::IntervalMap(), llvm::IntervalMap< IndexT, char >::IntervalMap(), inThisOrder(), llvm::Mips16RegisterInfo::intRegClass(), llvm::MipsSERegisterInfo::intRegClass(), llvm::ConstantRange::intrinsic(), llvm::EpilogueVectorizerMainLoop::introduceCheckBlockInVPlan(), llvm::VPlanTransforms::introduceMasksAndLinearize(), llvm::IntToPtrInst::IntToPtrInst(), llvm::BitVector::invalid(), llvm::SmallBitVector::invalid(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::MachineTraceMetrics::Ensemble::invalidate(), llvm::AnalysisGetter::invalidateAnalyses(), llvm::coro::Shape::invalidateCoroutine(), llvm::InterleavedAccessInfo::invalidateGroups(), llvm::InterleavedAccessInfo::invalidateGroupsRequiringScalarEpilogue(), llvm::SPIRVGlobalRegistry::invalidateMachineInstr(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), llvm::invertCondition(), invertFPCondCodeUser(), invokeFunctionPass(), llvm::iota_range< T >::iota_range(), llvm::SPIRV::irhandle_sampled_image(), llvm::orc::IRMaterializationUnit::IRMaterializationUnit(), llvm::IRSimilarity::IRSimilarityCandidate::IRSimilarityCandidate(), llvm::BitTracker::BitValue::is(), llvm::X86_MC::is32BitMemOperand(), llvm::ARMBaseTargetMachine::isAAPCS16_ABI(), llvm::ARMBaseTargetMachine::isAAPCS_ABI(), llvm::Triple::isAArch64(), llvm::isAArch64FrameOffsetLegal(), llvm::HexagonMCInstrInfo::IsABranchingInst(), llvm::jitlink::Symbol::isAbsolute(), IsAcceptableTarget(), isAddConstantOp(), llvm::AArch64InstrInfo::isAddImmediate(), isAddressExpression(), isAddSubOrSubAdd(), isAGPRCopy(), llvm::MachineFrameInfo::isAliasedObjectIndex(), llvm::StackLifetime::isAliveAfter(), isAllocSiteRemovable(), llvm::isAlmostDeadIV(), isAlternateInstruction(), isAlternating(), isAMCompletelyFolded(), llvm::Triple::isAndroidVersionLT(), isAngleBracketString(), isAngleBracketString(), llvm::Loop::isAnnotatedParallel(), llvm::ARMBaseTargetMachine::isAPCS_ABI(), llvm::CallBase::isArgOperand(), llvm::scc_iterator< GraphT, GT >::isAtEnd(), llvm::MCOperand::isBareSymbolRef(), llvm::DWARFDebugRangeList::RangeListEntry::isBaseAddressSelectionEntry(), llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond(), llvm::InstructionOrdering::isBefore(), IsBetterFallthrough(), isBigEndian(), isBigEndian(), isBitfieldDstMask(), isBitfieldExtractOpFromAnd(), isBitfieldExtractOpFromSExtInReg(), isBitfieldExtractOpFromShr(), isBitfieldPositioningOp(), isBitfieldPositioningOpFromAnd(), isBitfieldPositioningOpFromShl(), llvm::XtensaInstrInfo::isBranch(), llvm::AArch64InstrInfo::isBranchOffsetInRange(), llvm::SIInstrInfo::isBranchOffsetInRange(), llvm::SparcInstrInfo::isBranchOffsetInRange(), IsBranchOnlyBlock(), llvm::HexagonMCInstrInfo::isBundle(), llvm::CallBase::isBundleOperand(), llvm::isBytewiseValue(), llvm::LazyCallGraph::Edge::isCall(), llvm::AbstractCallSite::isCallee(), llvm::MachineFrameInfo::isCalleeSavedObjectIndex(), llvm::TargetRegisterInfo::isCalleeSavedPhysReg(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), isCallToCFGuardFunction(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), isCheapCopy(), isCheapImmediate(), llvm::rdf::TargetOperandInfo::isClobbering(), isCmpSameOrSwapped(), llvm::CoalescerPair::isCoalescable(), isCommutableOperand(), llvm::RISCV::VSETVLIInfo::isCompatible(), llvm::MapResolver::isComplete(), llvm::coverage::MCDCRecord::isConditionIndependencePairCovered(), isConditionTrueViaVFAndUF(), isCondRelevantToAnyCallArgument(), isConstantOne(), llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::MachineInstr::isConstantValuePHI(), llvm::HexagonInstrInfo::isConstExtended(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::isConstOrConstSplat(), isContractableFMUL(), isConvertibleToVMV_V_V(), isCopyFeedingInvariantStore(), isCopyFromRegOfInlineAsm(), isCopyOfBundle(), llvm::isCriticalEdge(), llvm::isCriticalEdge(), isCrossCopy(), llvm::isCycleInvariant(), llvm::MCAsmBackend::isDarwinCanonicalPersonality(), llvm::CallBase::isDataOperand(), llvm::sandboxir::CallBase::isDataOperand(), llvm::LazyCallGraph::Node::isDead(), llvm::MachineOperand::isDead(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineOperand::isDebug(), llvm::GlobalValue::isDeclaration(), llvm::MachineOperand::isDef(), llvm::rdf::RefNode::isDef(), llvm::jitlink::Symbol::isDefined(), llvm::SuspendCrossingInfo::isDefinitionAcrossSuspend(), llvm::SuspendCrossingInfo::isDefinitionAcrossSuspend(), isDereferenceableAndAlignedPointer(), llvm::AArch64TargetLowering::isDesirableToCommuteWithShift(), llvm::AMDGPUTargetLowering::isDesirableToCommuteWithShift(), llvm::ARMTargetLowering::isDesirableToCommuteWithShift(), llvm::RISCVTargetLowering::isDesirableToCommuteWithShift(), llvm::AArch64TargetLowering::isDesirableToCommuteXorWithShift(), llvm::ARMTargetLowering::isDesirableToCommuteXorWithShift(), llvm::VPIRFlags::isDisjoint(), isDispOrCDisp8(), llvm::MachineOperand::isEarlyClobber(), IsElementEquivalent(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::CastInst::isEliminableCastPair(), llvm::SubtargetFeatures::isEnabled(), isEpilogProfitable(), llvm::DenseMapInfo< const SwitchSuccWrapper * >::isEqual(), llvm::DenseMapInfo< ValueInfo >::isEqual(), llvm::IRSimilarity::IRInstructionDataTraits::isEqual(), isEqualImpl(), isEvenReg(), isExplicitVecOuterLoop(), llvm::AArch64InstrInfo::isExtendLikelyToBeFolded(), llvm::jitlink::Symbol::isExternal(), llvm::TargetLoweringBase::isExtLoad(), isExtractHiElt(), llvm::HexagonTargetLowering::isExtractSubvectorCheap(), llvm::RISCVTargetLowering::isExtractSubvectorCheap(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::AMDGPUTargetLowering::isFAbsFree(), llvm::TargetLoweringBase::isFAbsFree(), llvm::RecurrenceDescriptor::isFindIVPattern(), isFIPlusImmOrVGPR(), isFloatDIType(), llvm::TargetLoweringBase::isFMADLegal(), llvm::TargetLoweringBase::isFMADLegal(), llvm::AMDGPUTargetLowering::isFNegFree(), llvm::TargetLoweringBase::isFNegFree(), llvm::TargetLoweringBase::isFPExtFoldable(), llvm::PPCTargetLowering::isFPExtFree(), llvm::TargetLoweringBase::isFPExtFree(), llvm::AArch64TargetLowering::isFPImmLegal(), llvm::InductionDescriptor::isFPInductionPHI(), llvm::AArch64InstrInfo::isFpOrNEON(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::AArch64RegisterInfo::isFrameOffsetLegal(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), llvm::PPCRegisterInfo::isFrameOffsetLegal(), llvm::RISCVRegisterInfo::isFrameOffsetLegal(), llvm::ItaniumPartialDemangler::isFunction(), llvm::ProfileSummaryInfo::isFunctionHotnessUnknown(), isGCPointerType(), isGEPKnownNonNull(), llvm::AArch64InstrInfo::isGPRCopy(), isGPRShadowAligned(), llvm::AArch64InstrInfo::isGPRZero(), llvm::OpenMPIRBuilderConfig::isGPU(), llvm::TargetLowering::isGuaranteedNotToBeUndefOrPoisonForTargetNode(), llvm::X86TargetLowering::isGuaranteedNotToBeUndefOrPoisonForTargetNode(), llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::vputils::isHeaderMask(), llvm::SCEVExpander::isHighCostExpansion(), llvm::SystemZ::isHighReg(), llvm::AllocationOrder::isHint(), isHorizontalBinOp(), isHorizontalBinOpPart(), isI32InsnAllUses(), llvm::MachineInstr::isIdenticalTo(), llvm::ShuffleVectorInst::isIdentityMask(), slpvectorizer::BoUpSLP::isIdentityOrder(), isIdentityValue(), llvm::PPCInstrInfo::isImmInstrEligibleForFolding(), llvm::SIInstrInfo::isImmOperandLegal(), llvm::MachineFrameInfo::isImmutableObjectIndex(), llvm::MachineOperand::isImplicit(), llvm::isImpliedByDomCondition(), llvm::AAMustProgress::isImpliedByIR(), llvm::AANoAlias::isImpliedByIR(), llvm::AANoCapture::isImpliedByIR(), llvm::AANoFree::isImpliedByIR(), llvm::AANoSync::isImpliedByIR(), llvm::AANoUndef::isImpliedByIR(), llvm::AAWillReturn::isImpliedByIR(), isImpliedCondAndOr(), llvm::isImpliedCondition(), isIndirectBranchOpcode(), llvm::isIndirectCall(), llvm::InductionDescriptor::isInductionPHI(), isInlineableLiteralOp16(), llvm::ARMBaseRegisterInfo::isInlineAsmReadOnlyReg(), llvm::SIInstrInfo::isInlineConstant(), llvm::SIInstrInfo::isInlineConstant(), llvm::HexagonMCInstrInfo::isInnerLoop(), isInRage(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), llvm::detail::DoubleAPFloat::isInteger(), isInterleaveShuffle(), llvm::MachineOperand::isInternalRead(), isIntExtFree(), isIntrinsicOrLFToBeTailCalled(), isInvalidVOPDY(), llvm::BlockFrequencyInfo::isIrrLoopHeader(), llvm::MachineBlockFrequencyInfo::isIrrLoopHeader(), llvm::MachineOperand::isKill(), llvm::AMDGPU::isKImmOperand(), isKnownBase(), isKnownExactCastIntToFP(), llvm::isKnownNegation(), llvm::SelectionDAG::isKnownNeverNaN(), llvm::TargetLowering::isKnownNeverNaNForTargetNode(), llvm::SelectionDAG::isKnownNeverZero(), llvm::SelectionDAG::isKnownNeverZeroFloat(), isKnownNonEqualFromContext(), isKnownNonNullFromDominatingCondition(), isKnownNonZero(), isKnownNonZeroFromAssume(), llvm::isKnownToBeAPowerOfTwo(), llvm::ScalarEvolution::isKnownViaInduction(), isLaneCrossingShuffleMask(), isLdOffsetInRangeOfSt(), isLdStSafeToCluster(), llvm::RISCVInstrInfo::isLdStSafeToPair(), llvm::MCFragment::isLEBSigned(), llvm::CombinerHelper::isLegal(), llvm::X86TTIImpl::isLegalAltInstr(), llvm::SIInstrInfo::isLegalGFX12PlusPackedMathFP32Operand(), IsLegalOffset(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::isLegalToPromote(), llvm::HexagonPacketizerList::isLegalToPruneDependencies(), llvm::SIInstrInfo::isLegalVSrcOperand(), llvm::PPCTargetMachine::isLittleEndian(), llvm::jitlink::Symbol::isLive(), llvm::MachineBasicBlock::isLiveIn(), llvm::AAIsDead::isLiveInstSet(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), llvm::SystemZInstrInfo::isLoadFromStackSlotPostFE(), isLoadStoreSizeLegal(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::SMSchedule::isLoopCarried(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isLoopCounter(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), llvm::MachineLoop::isLoopInvariant(), llvm::LoopBase< BlockT, LoopT >::isLoopLatch(), isLoopNeverExecuted(), llvm::TargetTransformInfoImplBase::isLoweredToCall(), isLowHalfOnly(), llvm::AMDGPUDisassembler::isMacDPP(), llvm::orc::isMachOInitializerSection(), llvm::Triple::isMacOSXVersionLT(), llvm::APInt::isMask(), isMaskedLoadCompress(), isMaskedSlidePair(), llvm::isMaskedSlidePair(), llvm::TargetLowering::AsmOperandInfo::isMatchingInputConstraint(), isMatchingOrAlias(), llvm::APInt::isMaxSignedValue(), llvm::AAPointerInfo::Access::isMayAccess(), llvm::X86Operand::isMaybeDirectBranchDest(), llvm::ARMBaseInstrInfo::isMBBSafeToOutlineFrom(), llvm::MemOp::isMemcpyStrSrc(), llvm::X86Operand::isMemIndexReg(), llvm::HexagonMCInstrInfo::isMemReorderDisabled(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), llvm::APInt::isMinSignedValue(), isMultiLaneShuffleMask(), isMultiple(), isMultipleOfN(), llvm::AAPointerInfo::Access::isMustAccess(), isNByteElemShuffleMask(), llvm::APInt::isNegatedPowerOf2(), llvm::ARM_AM::isNEONBytesplat(), AliasScopeTracker::isNoAliasScopeDeclDead(), llvm::DOTGraphTraits< const DataDependenceGraph * >::isNodeHidden(), llvm::VPIRFlags::isNonNeg(), isNonZeroElementsInOrder(), llvm::X86TargetMachine::isNoopAddrSpaceCast(), llvm::CastInst::isNoopCast(), isNoopPtrIntCastPair(), isNoopShuffleMask(), IsNullTerminatedString(), llvm::yaml::isNumeric(), llvm::MachineFrameInfo::isObjectPreAllocated(), llvm::MachineFrameInfo::isObjectSExt(), llvm::MachineFrameInfo::isObjectZExt(), isOneDimensionalArray(), isOnlyCopiedFromConstantMemory(), isOnlyReachableViaThisEdge(), llvm::SIInstrInfo::isOperandLegal(), llvm::MachineInstr::isOperandSubregIdx(), llvm::sandboxir::isOrdered(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::SplitAnalysis::isOriginalEndpoint(), llvm::HexagonMCInstrInfo::isOuterLoop(), llvm::isOverflowIntrinsicNoWrap(), isPackedVectorType(), llvm::isParamGridConstant(), isPartialOverwrite(), llvm::M68kInstrInfo::isPCRelRegisterOperandLegal(), llvm::R600RegisterInfo::isPhysRegLiveAcrossClauses(), llvm::isPhysRegUsedAfter(), isPointerValueDeadOnEntryToFunction(), llvm::CastIsPossible< To, std::optional< From > >::isPossible(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachable(), llvm::APInt::isPowerOf2(), llvm::CombinerHelper::isPredecessor(), llvm::LoopVectorizationCostModel::isPredicatedInst(), llvm::HexagonInstrInfo::isPredicatedNew(), llvm::HexagonInstrInfo::isPredicatedNew(), isPredicatedOnPHI(), llvm::HexagonInstrInfo::isPredicatedTrue(), llvm::HexagonInstrInfo::isPredictedTaken(), llvm::isPresplitCoroSuspendExitEdge(), isProcessableCondBI(), isProfitableChain(), llvm::PPCTargetLowering::isProfitableToHoist(), llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::AVR::isProgramMemoryAddress(), llvm::SIRegisterInfo::isProperlyAlignedRC(), isPtrKnownNeverNull(), llvm::isRangeRelaxable(), llvm::ScheduleDAGTopologicalSort::IsReachable(), isReachableAmongDominated(), llvm::DominatorTreeBase< BlockT, false >::isReachableFromEntry(), llvm::ValueInfo::isReadOnly(), llvm::isReadOnlyData(), llvm::SchedulingPriorityQueue::isReady(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), isReg(), llvm::SIRegisterInfo::isRegClassAligned(), llvm::opt::Option::isRegisteredSC(), llvm::M68kSubtarget::isRegisterReservedByUser(), llvm::RISCVSubtarget::isRegisterReservedByUser(), llvm::VirtRegAuxInfo::isRematerializable(), llvm::MachineOperand::isRenamable(), isRepeatedByteSequence(), isRepeatedByteSequence(), isRepeatedShuffleMask(), isRepeatedShuffleMask(), isRepeatedTargetShuffleMask(), llvm::ShuffleVectorInst::isReplicationMask(), isReplicationMaskWithParams(), llvm::isRequiredForExecution(), isReturnNonNull(), llvm::ShuffleVectorInst::isReverseMask(), isReverseOrder(), llvm::isREVMask(), llvm::Loop::isRotatedForm(), llvm::SystemZInstrInfo::isRxSBGMask(), isSafeDecreasingBound(), isSafeForNoNTrivialUnswitching(), isSafeIncreasingBound(), isSafeLoadOfSelectToSpeculate(), isSafeToMove(), isSafeToMove(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), isSafeToTruncateWideIVType(), llvm::LLT::isScalable(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::SPIRVGlobalRegistry::isScalarOfType(), llvm::SPIRVGlobalRegistry::isScalarOrVectorOfType(), isScaledConstantInRange(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), llvm::ShuffleVectorInst::isSelectMask(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::isSequenceFromUnmerge(), isSeveralBitsPositioningOpFromShl(), llvm::SIInstrInfo::isSGPRStackAccess(), isShiftedMask(), isShuffleEquivalent(), isShuffleMaskInputBroadcastable(), isShuffleMaskInputInPlace(), isSignedMinMaxClamp(), isSignedMinMaxIntrinsicClamp(), isSignExtendedW(), isSignExtendedW(), isSignExtendingOpW(), isSimilarDispOp(), isSimpleVIDSequence(), llvm::BasicBlockEdge::isSingleEdge(), isSingleSHUFPSMask(), llvm::ShuffleVectorInst::isSingleSourceMask(), isSingleSourceMaskImpl(), llvm::AMDGPU::isSISrcFPOperand(), llvm::AMDGPU::isSISrcInlinableOperand(), llvm::ConstantRange::isSizeStrictlySmallerThan(), llvm::ItaniumPartialDemangler::isSpecialName(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::APInt::isSplat(), llvm::PPC::isSplatShuffleMask(), llvm::isSplatValue(), llvm::SelectionDAG::isSplatValue(), llvm::SelectionDAG::isSplatValue(), llvm::TargetLowering::isSplatValueForTargetNode(), llvm::ShuffleVectorInst::isSpliceMask(), llvm::SIInstrInfo::isStackAccess(), llvm::StatepointLoweringState::isStackSlotAllocated(), llvm::MachineFrameInfo::isStatepointSpillSlotObjectIndex(), llvm::SystemZInstrInfo::isStoreToStackSlotPostFE(), llvm::SCCPInstVisitor::isStructLatticeConstant(), isSubset(), llvm::APInt::isSubsetOf(), llvm::mca::ResourceManager::issueInstructionImpl(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), llvm::ELFObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::AArch64InstrInfo::isTailCallReturnInst(), llvm::OpenMPIRBuilderConfig::isTargetDevice(), isTargetShuffleEquivalent(), isTerminalReg(), isThreadPointerAcquisitionNode(), llvm::MachineOperand::isTied(), isTileDef(), llvm::isTLIScalarize(), llvm::ShuffleVectorInst::isTransposeMask(), slpvectorizer::BoUpSLP::isTreeTinyAndNotFullyVectorizable(), isTupleInsertInstr(), llvm::TargetLoweringBase::isTypeLegal(), isUnalignedMemmoryAccess(), llvm::AA::RangeTy::isUnassigned(), isUncondBranchOpcode(), llvm::MachineOperand::isUndef(), llvm::SelectionDAG::isUndef(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::isUniformLoop(), llvm::AAPointerInfo::RangeList::isUnknown(), llvm::DebugHandlerBase::isUnsignedDIType(), isUpperSubvectorUndef(), llvm::MachineOperand::isUse(), llvm::rdf::RefNode::isUse(), isValidClauseInst(), isValidDisp(), llvm::opt::OptTable::isValidForSubCommand(), llvm::AbstractAttribute::isValidIRPositionForUpdate(), llvm::AMDGPU::SendMsg::isValidMsgOp(), llvm::AMDGPU::SendMsg::isValidMsgStream(), isValidMtVsrBmi(), llvm::HexagonInstrInfo::isValidOffset(), llvm::SMSchedule::isValidSchedule(), llvm::PPCInstrInfo::isValidToBeChangedReg(), IsValueFullyAvailableInBlock(), llvm::ConstantFPSDNode::isValueValidForType(), llvm::MachineFrameInfo::isVariableSizedObjectIndex(), isVariantApplicableInContextHelper(), isVECTOR_SHUFFLE_SPLATI(), llvm::isVectorIntrinsicWithOverloadTypeAtArg(), slpvectorizer::BoUpSLP::isVectorized(), isVectorLikeInstWithConstOps(), isVectorPromotionViableForSlice(), llvm::ISD::isVectorShrinkable(), llvm::SIInstrInfo::isVGPRCopy(), llvm::RISCV::isVLKnownLE(), isVMerge(), isVMOVModifiedImm(), IsVPNOTEquivalent(), llvm::isVREVMask(), llvm::RISCVTargetLowering::isVScaleKnownToBeAPowerOfTwo(), isVShiftLImm(), isVShiftLImm(), isVShiftRImm(), isVShiftRImm(), llvm::jitlink::Symbol::isWeaklyReferenced(), isWideDUPMask(), IsWMMAHazardInstInCategory(), isWorthFoldingIntoOrrWithShift(), isWorthFoldingIntoRegRegScale(), isWorthFoldingSHL(), llvm::ValueInfo::isWriteOnly(), llvm::mca::WriteRef::isWriteZero(), isXXBRShuffleMaskHelper(), llvm::PPC::isXXPERMDIShuffleMask(), llvm::PPC::isXXSLDWIShuffleMask(), llvm::ShuffleVectorInst::isZeroEltSplatMask(), llvm::RuntimeDyldChecker::MemoryRegionInfo::isZeroFill(), llvm::itaniumDemangle(), iterativelySimplifyCFG(), llvm::jitlink::JITLinkerBase::JITLinkerBase(), llvm::jitTargetAddressToPointer(), llvm::IntEqClasses::join(), llvm::LiveRange::join(), llvm::SchedDFSImpl::joinPredSubtree(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), jumpTableHasOtherUses(), llvm::SimpleBitstreamCursor::JumpToBit(), llvm::sys::fs::TempFile::keep(), llvm::sys::fs::TempFile::keep(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_back(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front(), KnuthDiv(), llvm::ARM::WinEH::RuntimeFunction::L(), llvm::MCAssembler::layout(), layoutCOFF(), layoutSegments(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvAtTop(), llvm::SplitEditor::leaveIntvBefore(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), legalizeAndOptimizeInductions(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBuildVector(), llvm::AMDGPULegalizerInfo::legalizeBVHDualOrBVH8IntersectRayIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeBVHIntersectRayIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeCTLZ_ZERO_UNDEF(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::SPIRVLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFceil(), legalizeFCmpPredicate(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFExp2(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFlog2(), llvm::AMDGPULegalizerInfo::legalizeFlogCommon(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFPTOI(), llvm::AMDGPULegalizerInfo::legalizeFroundeven(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF16(), llvm::AMDGPULegalizerInfo::legalizeFSQRTF64(), legalizeGetHighLowi64Bytes(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeKernargMemParameter(), llvm::Legalizer::legalizeMachineFunction(), llvm::AMDGPULegalizerInfo::legalizeMul(), llvm::SIInstrInfo::legalizeOperands(), llvm::VETargetLowering::legalizePackedAVL(), llvm::AMDGPULegalizerInfo::legalizeSBufferLoad(), legalizeScalarLoadStoreOnArrays(), llvm::TargetLowering::LegalizeSetCCCondCode(), legalizeStore(), llvm::cfg::LegalizeUpdates(), llvm::vfs::recursive_directory_iterator::level(), llvm::AsmLexer::Lex(), llvm::LexicalScope::LexicalScope(), lexMacroName(), lexStringConstant(), licm(), llvm::codeview::limitSymbolArrayToScope(), LinearizeExprTree(), llvm::LineEditor::LineEditor(), llvm::dwarf_linker::classic::DWARFLinker::link(), llvm::remarks::RemarkLinker::link(), llvm::jitlink::LinkGraph::LinkGraph(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::linkSingleCompileUnit(), llvm::lintFunction(), llvm::symbolize::JSONPrinter::listBegin(), llvm::symbolize::JSONPrinter::listEnd(), littleEndianByteAt(), llvm::MachineBasicBlock::livein_begin(), llvm::LiveRange::LiveRange(), lle_X_atexit(), lle_X_fprintf(), lle_X_scanf(), lle_X_sscanf(), llvm::orc::LLJIT::LLJIT(), llvm_map_to_intrinsic_id(), llvm_regerror(), llvm_regexec(), llvm::LLVMContext::LLVMContext(), LLVMDbgRecordGetKind(), LLVMDIBuilderInsertDbgValueRecordAtEnd(), LLVMDIBuilderInsertDbgValueRecordBefore(), LLVMDIBuilderInsertDeclareRecordAtEnd(), LLVMDIBuilderInsertDeclareRecordBefore(), LLVMDIBuilderInsertLabelAtEnd(), LLVMDIBuilderInsertLabelBefore(), LLVMDisasmInstruction(), LLVMExecutionEngineGetErrMsg(), LLVMGetAtomicSyncScopeID(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), LLVMGetMetadata(), LLVMGetOperand(), LLVMGetSwitchCaseValue(), LLVMInsertExistingBasicBlockAfterInsertBlock(), LLVMMDNodeInContext(), LLVMOrcCreateDumpObjects(), LLVMOrcCreateDynamicLibrarySearchGeneratorForPath(), LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess(), LLVMOrcCreateLLJIT(), LLVMOrcCreateObjectLinkingLayerWithInProcessMemoryManager(), LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks(), LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager(), LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManagerReserveAlloc(), LLVMOrcCreateStaticLibrarySearchGeneratorForPath(), LLVMOrcExecutionSessionLookup(), LLVMOrcIRTransformLayerSetTransform(), LLVMOrcJITTargetMachineBuilderDetectHost(), LLVMOrcLLJITLookup(), LLVMOrcObjectTransformLayerSetTransform(), LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener(), LLVMSetAtomicSyncScopeID(), LLVMSetSwitchCaseValue(), loadBinaryFormat(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::AMDGPUTargetLowering::loadInputValue(), llvm::LoadIntFromMemory(), llvm::orc::loadMachORelocatableObject(), llvm::LazyAtomicPointer< TrieNode >::loadOrGenerate(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::M68kInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadRegFromStackSlot(), TransferTracker::loadVarInloc(), llvm::MemorySSA::locallyDominates(), locateGepFromIntrinsic(), llvm::DbgVariableRecord::location_ops(), llvm::RawLocationWrapper::location_ops(), LiveDebugValues::MLocTracker::locIDToSpill(), LiveDebugValues::MLocTracker::locIDToSpillIdx(), LiveDebugValues::LocIdx::LocIdx(), llvm::sys::SmartRWMutex< false >::lock(), llvm::FileError::log(), lookForCompound(), lookThroughCast(), llvm::TargetRegisterInfo::lookThruCopyLike(), llvm::TargetRegisterInfo::lookThruSingleUseCopyChain(), llvm::sys::DynamicLibrary::HandleSet::Lookup(), llvm::BitTracker::lookup(), llvm::BlockAddress::lookup(), llvm::DWARFDebugNames::Entry::lookup(), llvm::GVNPass::ValueTable::lookup(), llvm::orc::ExecutionSession::lookup(), llvm::orc::SymbolInstance::lookupAsync(), llvm::StringMapImpl::LookupBucketFor(), llvm::orc::Platform::lookupInitSymbols(), llvm::Intrinsic::lookupIntrinsicID(), lookupLLVMIntrinsicByName(), lookupMaskedIntrinsic(), LookupNEONLdSt(), llvm::vfs::RedirectingFileSystem::LookupResult::LookupResult(), lowBitMask(), llvm::M68kMCInstLower::Lower(), llvm::LegalizerHelper::lower(), llvm::WebAssemblyMCInstLower::lower(), lower128BitShuffle(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), lower256BitShuffle(), lower512BitShuffle(), LowerABS(), llvm::LegalizerHelper::lowerAbsDiffToMinMax(), llvm::LegalizerHelper::lowerAbsDiffToSelect(), llvm::PPCRegisterInfo::lowerACCRestore(), LowerADDRSPACECAST(), LowerADDRSPACECAST(), lowerAddrSpaceCast(), LowerADDSAT_SUBSAT(), lowerAddSub(), lowerAddSubToHorizontalOp(), LowerAndToBT(), LowerANY_EXTEND(), llvm::FastISel::lowerArguments(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::InlineAsmLowering::lowerAsmOperandForConstraint(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerATOMIC_FENCE(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), lowerBitcasts(), llvm::LegalizerHelper::lowerBitCount(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBitreverseShuffle(), LowerBR_CC(), LowerBSWAP(), lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), lowerBUILD_VECTORAsBroadCastLoad(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), lowerBuildVectorOfConstants(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), lowerBuildVectorViaDominantValues(), lowerBuildVectorViaPacking(), lowerBuildVectorViaVID(), llvm::SPIRV::lowerBuiltin(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::XtensaTargetLowering::LowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::CallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallFromStatepointLoweringInfo(), LowerCallResult(), lowerCallResult(), LowerCallResults(), llvm::SelectionDAGBuilder::LowerCallSiteWithPtrAuthBundle(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::FastISel::lowerCallTo(), llvm::FastISel::lowerCallTo(), llvm::AMDGPUCallLowering::lowerChainCall(), LowerCMP_SWAP(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), lowerConstant(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), lowerCTLZCTPOP(), llvm::AMDGPUTargetLowering::lowerCTLZResults(), LowerCTPOP(), LowerCTPOP(), LowerCTPOP(), LowerCTTZ(), llvm::RISCVTargetLowering::LowerCustomJumpTableEntry(), llvm::VETargetLowering::LowerCustomJumpTableEntry(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), llvm::FastISel::lowerDbgDeclare(), llvm::FastISel::lowerDbgValue(), llvm::AArch64TargetLowering::lowerDeinterleaveIntrinsicToLoad(), lowerDSPIntr(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), LowerEXTEND_VECTOR_INREG(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerF128Load(), llvm::SparcTargetLowering::LowerF128Op(), LowerF128Store(), LowerF64Op(), llvm::AMDGPUTargetLowering::LowerF64ToF16Safe(), LowerFABSorFNEG(), lowerFABSorFNEG(), LowerFCOPYSIGN(), lowerFCOPYSIGN(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::lowerFEXP2(), LowerFGETSIGN(), lowerFixedVectorSegLoadIntrinsics(), lowerFixedVectorSegStoreIntrinsics(), llvm::AMDGPUTargetLowering::LowerFLOG2(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), LowerFMINIMUM_FMAXIMUM(), LowerFNEGorFABS(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), LowerFP16_TO_FP(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), lowerFP_TO_INT_SAT(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), llvm::SITargetLowering::lowerGET_ROUNDING(), lowerGetVectorLength(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerHorizontalByteSum(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerImmediateIfPossible(), lowerIncomingStatepointValue(), llvm::InlineAsmLowering::lowerInlineAsm(), LowerINSERT_SUBVECTOR(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), lowerINT_TO_FP_vXi64(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::RISCVTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::RISCVTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), llvm::AArch64TargetLowering::lowerInterleaveIntrinsicToStore(), lowerIntNeonIntrinsic(), LowerINTRINSIC_W_CHAIN(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerIntrinsicToFunction(), LowerIntVSETCC_AVX512(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::ARMAsmPrinter::LowerKCFI_CHECK(), lowerLaneOp(), LowerLargeShift(), LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), llvm::LegalizerHelper::lowerLoad(), lowerLoadF128(), lowerLOADi1(), lowerLoadI1(), llvm::LegalizerHelper::lowerMemCpyFamily(), llvm::LegalizerHelper::lowerMemcpyInline(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), lowerMSTORE(), LowerMUL(), LowerMUL(), LowerMULH(), LowerNegateToMultiply(), lowerObjCCall(), llvm::lowerObjectSizeCall(), llvm::PPCRegisterInfo::lowerOctWordSpilling(), llvm::ARMAsmPrinter::lowerOperand(), llvm::AArch64TargetLowering::LowerOperation(), llvm::ARCTargetLowering::LowerOperation(), llvm::ARMTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::TargetLowering::LowerOperationWrapper(), llvm::jitlink::aarch64::lowerPointer64AuthEdgesToSigningFunction(), llvm::LowerPPCMachineOperandToMCOperand(), LowerPredicateLoad(), LowerPredicateStore(), LowerPREFETCH(), llvm::PPCRegisterInfo::lowerPrepareProbedAlloca(), LowerPtrAuthGlobalAddressStatically(), llvm::PPCRegisterInfo::lowerQuadwordRestore(), lowerRegToMasks(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::XtensaTargetLowering::LowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::CallLowering::lowerReturn(), llvm::RISCVCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerReverse_VECTOR_SHUFFLE(), lowerRISCVVMachineInstrToMCInst(), LowerRotate(), llvm::SITargetLowering::lowerROTR(), LowerSCALAR_TO_VECTOR(), lowerScalarInsert(), lowerScalarSplat(), LowerSDIV(), llvm::RISCVRegisterInfo::lowerSegmentSpillReload(), lowerSELECT(), LowerSELECT_CC(), llvm::SITargetLowering::lowerSET_ROUNDING(), llvm::HexagonTargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShift(), LowerShiftByScalarImmediate(), llvm::MSP430TargetLowering::LowerShifts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LegalizerHelper::lowerShlSat(), lowerShuffleAsBitBlend(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsSpecificExtension(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShufflePairAsUNPCKAndPermute(), llvm::LegalizerHelper::lowerShuffleVector(), lowerShuffleViaVRegSplitting(), lowerShuffleWithEXPAND(), lowerShuffleWithPACK(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithUndefHalf(), lowerShuffleWithVPMOV(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), LowerSINT_TO_FP(), llvm::LoongArchAsmPrinter::LowerSTATEPOINT(), llvm::SelectionDAGBuilder::LowerStatepoint(), lowerStatepointMetaArgs(), LowerSTORE(), LowerStore(), llvm::VETargetLowering::lowerSTORE(), lowerStoreF128(), lowerStoreI1(), lowerSTOREVector(), LowerSVEIntrinsicEXT(), llvm::AArch64MCInstLower::LowerSymbolOperand(), llvm::XtensaAsmPrinter::LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), llvm::AMDGPUMCInstLower::lowerT16D16Helper(), llvm::AMDGPUMCInstLower::lowerT16FmaMixFP16(), llvm::AMDGPUCallLowering::lowerTailCall(), lowerTileCopy(), LowerToHorizontalOp(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::VETargetLowering::lowerToVVP(), llvm::LegalizerHelper::lowerTRUNC(), LowerTruncatei1(), LowerTruncateToBTST(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::LegalizerHelper::lowerU64ToF32WithSITOFP(), llvm::LegalizerHelper::lowerU64ToF64BitFloatOps(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerUnalignedIntStore(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV4X128Shuffle(), lowerV64I8Shuffle(), lowerV8F16Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::HexagonTargetLowering::LowerVACOPY(), LowerVACOPY(), LowerVecReduce(), LowerVecReduceMinMax(), lowerVECTOR_COMPRESS(), llvm::HexagonTargetLowering::LowerVECTOR_SHIFT(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_VREPLVEI(), lowerVECTOR_SHUFFLE_VSHF(), lowerVECTOR_SHUFFLE_XVINSVE0(), lowerVECTOR_SHUFFLE_XVREPLVEI(), lowerVECTOR_SHUFFLE_XVSHUF(), lowerVECTOR_SHUFFLEAsLanePermuteAndShuffle(), lowerVECTOR_SHUFFLEAsShift(), lowerVECTOR_SHUFFLEAsVRGatherVX(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVectorAllEqual(), LowerVectorCTLZ(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZ_GFNI(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), LowerVectorINT_TO_FP(), lowerVectorIntrinsicScalars(), LowerVectorMatch(), lowerVectorStrictFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorXRINT_XROUND(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerVSETCC(), LowerVSETCC(), llvm::VETargetLowering::lowerVVP_LOAD_STORE(), lowerVZIP(), lowerWaveShuffle(), LowerWRITE_REGISTER(), LowerXALUO(), LowerZERO_EXTEND(), LowerZERO_EXTEND_Mask(), llvm::LSBaseSDNode::LSBaseSDNode(), llvm::APInt::lshrInPlace(), llvm::SDPatternMatch::m_Specific(), llvm::MachineInstrBundleIterator< MachineInstr >::MachineInstrBundleIterator(), llvm::MachineInstrBundleIterator< MachineInstr >::MachineInstrBundleIterator(), llvm::MachineInstrBundleIterator< MachineInstr >::MachineInstrBundleIterator(), llvm::MachineInstrSpan::MachineInstrSpan(), llvm::MachineMemOperand::MachineMemOperand(), llvm::msf::MSFLayout::mainFpmBlock(), llvm::sandboxir::MemDGNodeIntervalBuilder::make(), llvm::jitlink::LinkGraph::makeAbsolute(), llvm::MachineFunction::makeDebugValueSubstitution(), llvm::jitlink::LinkGraph::makeDefined(), makeDstOps(), llvm::SelectionDAG::makeEquivalentMemoryOrdering(), llvm::SelectionDAG::makeEquivalentMemoryOrdering(), llvm::jitlink::LinkGraph::makeExternal(), llvm::vfs::makeFilteringOutputBackend(), llvm::makeFollowupLoopID(), llvm::ConstantRange::makeGuaranteedNoWrapRegion(), llvm::makeGuardControlFlowExplicit(), llvm::opt::InputArgList::MakeIndex(), llvm::detail::DoubleAPFloat::makeLargest(), llvm::MCFragment::makeLEB(), makeMergeable(), llvm::vfs::makeMirroringOutputBackend(), llvm::LPAC::makePostOp(), llvm::LPAC::makePreOp(), llvm::detail::IEEEFloat::makeQuiet(), llvm::rdf::DataFlowGraph::makeRegRef(), llvm::rdf::DataFlowGraph::makeRegRef(), llvm::ContextAndReplaceableUses::makeReplaceable(), llvm::detail::DoubleAPFloat::makeSmallest(), llvm::detail::DoubleAPFloat::makeSmallestNormalized(), llvm::SelectionDAG::makeStateFunctionCall(), makeStatepointExplicit(), makeStatepointExplicitImpl(), llvm::orc::makeStub(), llvm::coro::LowererBase::makeSubFnCall(), makeVisible(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::map(), mapArgRegToOffsetAIX(), llvm::mapAtomInstance(), llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), llvm::msgpack::MapDocNode::MapDocNode(), mapInputsToGVNs(), mapNameAndUniqueName(), llvm::json::ObjectMapper::mapOptional(), mapOptOrNull(), llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::mapping(), llvm::yaml::MappingTraits< Argument >::mapping(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapping(), llvm::yaml::MappingTraits< ExportSection >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::Member >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::StringEntry >::mapping(), llvm::yaml::MappingTraits< RemarkLocation >::mapping(), llvm::yaml::MappingTraits< remarks::Remark * >::mapping(), llvm::yaml::MappingTraits< UndefinedSection >::mapping(), llvm::VPLane::mapToCacheIndex(), llvm::IRSimilarity::IRInstructionMapper::mapToIllegalUnsigned(), llvm::IRSimilarity::IRInstructionMapper::mapToLegalUnsigned(), llvm::LiveDebugVariables::LDVImpl::mapVirtReg(), mapWasmLandingPadIndex(), llvm::BitstreamWriter::markAndBlockFlushing(), llvm::MachineFrameInfo::markAsStatepointSpillSlotObjectIndex(), llvm::ValueLatticeElement::markConstant(), llvm::ValueLatticeElement::markConstantRange(), llvm::SampleContextTracker::markContextSamplesInlined(), markCoroutineAsDone(), llvm::LazyCallGraph::markDeadFunction(), llvm::GenericUniformityAnalysisImpl< ContextT >::markDefsDivergent(), llvm::dwarf_linker::parallel::DependencyTracker::markDIEEntryAsKeptRec(), llvm::Attributor::markLiveInternalFunction(), llvm::LPMUpdater::markLoopAsDeleted(), llvm::LPPassManager::markLoopAsDeleted(), llvm::ValueLatticeElement::markNotConstant(), markPointerAsAS(), llvm::markRegisterParameterAttributes(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::markSectionStart(), llvm::mca::ResourceState::markSubResourceAsUsed(), llvm::ValueLatticeElement::markUndef(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::BitTracker::MachineEvaluator::mask(), llvm::maskContainsAllOneOrUndef(), llvm::MaskedGatherScatterSDNode::MaskedGatherScatterSDNode(), llvm::MaskedLoadStoreSDNode::MaskedLoadStoreSDNode(), llvm::SCEVWrapPredicate::maskFlags(), llvm::maskIsAllOneOrUndef(), llvm::maskIsAllZeroOrUndef(), llvm::DwarfExpression::maskSubRegister(), llvm::maskTrailingOnes(), llvm::Pattern::match(), llvm::PatternMatch::DisjointOr_match< LHS, RHS, Commutable >::match(), llvm::PatternMatch::LogicalOp_match< LHS, RHS, Opcode, Commutable >::match(), llvm::Regex::match(), llvm::SCEVPatternMatch::bind_cst_ty::match(), llvm::SCEVPatternMatch::cst_pred_ty< Predicate >::match(), llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::TLI_pred_match< Pattern, PredFuncT >::match(), llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::match(), llvm::VPlanPatternMatch::bind_apint::match(), llvm::VPlanPatternMatch::int_pred_ty< is_specific_int, Bitwidth >::match(), llvm::VPlanPatternMatch::Recipe_match< std::tuple< OpTys... >, Opcode, false, VPWidenRecipe, VPReplicateRecipe, VPWidenCastRecipe, VPInstruction >::match(), PrefixMatcher::match(), llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantInt, AllowPoison >::match_impl(), matchAccessTags(), llvm::CombinerHelper::matchAddEToAddO(), llvm::CombinerHelper::matchAddSubSameReg(), llvm::MCInstPrinter::matchAliasPatterns(), llvm::CombinerHelper::matchAndOrDisjointMask(), llvm::CombinerHelper::matchAshrShlToSextInreg(), matchBinaryPermuteShuffle(), llvm::CombinerHelper::matchBitfieldExtractFromSExtInReg(), llvm::CombinerHelper::matchBitfieldExtractFromShr(), llvm::CombinerHelper::matchBitfieldExtractFromShrAnd(), matchBitmaskMul(), matchBSwapHWordOrAndAnd(), llvm::CombinerHelper::matchCanonicalizeFCmp(), llvm::CombinerHelper::matchCanonicalizeICmp(), llvm::CombinerHelper::matchCombineAddP2IToPtrAdd(), llvm::CombinerHelper::matchCombineAnyExtTrunc(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineExtractedVectorLoad(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::AMDGPUCombinerHelper::matchCombineFmulWithSelectToFldexp(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineI2PToP2I(), llvm::CombinerHelper::matchCombineInsertVecElts(), llvm::CombinerHelper::matchCombineLoadWithAndMask(), llvm::CombinerHelper::matchCombineMulToShl(), llvm::CombinerHelper::matchCombineShiftToUnmerge(), llvm::CombinerHelper::matchCombineShlOfExtend(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::CombinerHelper::matchCombineTruncOfShift(), llvm::CombinerHelper::matchCombineUnmergeMergeToPlainValues(), llvm::CombinerHelper::matchCombineUnmergeWithDeadLanesToTrunc(), llvm::CombinerHelper::matchCombineUnmergeZExtToZExt(), llvm::CombinerHelper::matchCombineZextTrunc(), llvm::CombinerHelper::matchCommuteShift(), llvm::CombinerHelper::matchConstantFoldFMA(), matchDeMorgansLaws(), llvm::CombinerHelper::matchDivByPow2(), llvm::AMDGPUCombinerHelper::matchExpandPromotedF16FMed3(), llvm::CombinerHelper::matchExtractAllEltsFromBuildVector(), llvm::CombinerHelper::matchExtractVecEltBuildVec(), llvm::CombinerHelper::matchExtractVectorElementWithShuffleVector(), llvm::fuzzerop::matchFirstLengthWAnyType(), llvm::fuzzerop::matchFirstType(), llvm::CombinerHelper::matchFsubToFneg(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), llvm::CombinerHelper::matchICmpToLHSKnownBits(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), matchIndexAsShuffle(), MatchingStackOffset(), MatchingStackOffset(), llvm::CombinerHelper::matchInsertExtractVecEltOutOfBounds(), matchIntrinsicType(), matchLoadAndBytePosition(), llvm::AMDGPUDAGToDAGISel::matchLoadD16FromBuildVector(), llvm::CombinerHelper::matchLoadOrCombine(), llvm::CombinerHelper::matchLshrOfTruncOfLshr(), llvm::CombinerHelper::matchMergeXAndUndef(), matchMinMaxOfMinMax(), llvm::CombinerHelper::matchMulOBy0(), llvm::CombinerHelper::matchMulOBy2(), llvm::CombinerHelper::matchNarrowBinopFeedingAnd(), llvm::CombinerHelper::matchNotCmp(), llvm::CombinerHelper::matchOptBrCondByInvertingCond(), matchOrConcat(), llvm::CombinerHelper::matchOrShiftToFunnelShift(), llvm::CombinerHelper::matchOverlappingAnd(), llvm::sandboxir::VecUtils::matchPack(), matchPERM(), matchPMADDWD(), matchPMADDWD_2(), llvm::CombinerHelper::matchPtrAddZero(), llvm::CombinerHelper::matchRedundantAnd(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchRedundantOr(), llvm::CombinerHelper::matchRedundantSextInReg(), matchRegisterNameHelper(), llvm::CombinerHelper::matchRepeatedFPDivisor(), llvm::CombinerHelper::matchRotateOutOfRange(), llvm::fuzzerop::matchScalarOfFirstType(), matchScalarReduction(), llvm::ScaledNumbers::matchScales(), llvm::CombinerHelper::matchSDivOrSRemByConst(), llvm::fuzzerop::matchSecondType(), llvm::CombinerHelper::matchSelectSameVal(), matchSetCC(), matchSetCC(), llvm::CombinerHelper::matchSextInRegOfLoad(), llvm::CombinerHelper::matchSextTruncSextLoad(), llvm::CombinerHelper::matchShiftImmedChain(), llvm::CombinerHelper::matchShiftOfShiftedLogic(), matchShuffleAsBitRotate(), matchShuffleAsBitRotate(), matchShuffleAsBlend(), matchShuffleAsByteRotate(), matchShuffleAsElementRotate(), matchShuffleAsEXTRQ(), matchShuffleAsInsertPS(), matchShuffleAsINSERTQ(), matchShuffleWithPACK(), matchShuffleWithSHUFPD(), matchShuffleWithUNPCK(), llvm::CombinerHelper::matchSimplifyNegMinMax(), llvm::CombinerHelper::matchSimplifySelectToMinMax(), llvm::CombinerHelper::matchSubAddSameReg(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), matchTruncateWithPACK(), llvm::CombinerHelper::matchTruncSSatS(), llvm::CombinerHelper::matchTruncSSatU(), llvm::CombinerHelper::matchTruncUSatU(), llvm::CombinerHelper::matchUDivOrURemByConst(), llvm::CombinerHelper::matchUMulHToLShr(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::CombinerHelper::matchUndefSelectCmp(), llvm::CombinerHelper::matchUndefShuffleVectorMask(), llvm::CombinerHelper::matchUndefStore(), MatchVectorAllEqualTest(), matchVPMADD52(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), llvm::VPlanTransforms::materializeBroadcasts(), llvm::VPlanTransforms::materializeConstantVectorTripCount(), llvm::Value::materialized_use_begin(), llvm::Value::materialized_use_begin(), llvm::Value::materialized_user_begin(), llvm::Value::materialized_user_begin(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::MachineIRBuilder::materializePtrAdd(), llvm::VPlanTransforms::materializeVectorTripCount(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), llvm::maxIntN(), maxPlainSubstring(), llvm::maxUIntN(), llvm::SIInstrInfo::mayAccessLDSThroughFlat(), llvm::SIInstrInfo::mayAccessVMEMThroughFlat(), mayBeAccessToSubobjectOf(), llvm::dwarf_linker::parallel::DependencyTracker::maybeAddReferencedRoots(), llvm::MaybeAlign::MaybeAlign(), maybeFloatingPointRecurrence(), maybeFreeRetconStorage(), maybeLexRegister(), maybeMoveCFI(), maybeRewriteToFallthrough(), llvm::codegen::MaybeSaveStatistics(), maybeUpdateTerminator(), mayBeVisibleThroughUnwinding(), llvm::orc::LibraryInfo::mayContain(), MayContainThrowingOrExitingCallAfterCB(), llvm::orc::MayExistInElfObjectFile(), llvm::MachineInstr::mayFoldInlineAsmRegOp(), llvm::X86::mayFoldLoadIntoBroadcastFromMem(), llvm::VPExpressionRecipe::mayHaveSideEffects(), llvm::VPRecipeBase::mayHaveSideEffects(), mayLoadFromGOTOrConstantPool(), mayLoadFromGOTOrConstantPool(), llvm::VPRecipeBase::mayReadFromMemory(), llvm::WebAssembly::mayThrow(), mayUseP9Setb(), llvm::VPRecipeBase::mayWriteToMemory(), llvm::RegBankSelect::MBBInsertPoint::MBBInsertPoint(), mccase(), llvm::MCDwarfLineStr::MCDwarfLineStr(), llvm::MCExpr::MCExpr(), mcinvert(), llvm::MCLOHDirective::MCLOHDirective(), llvm::MCObjectStreamer::MCObjectStreamer(), llvm::MCPseudoProbe::MCPseudoProbe(), llvm::MCRegAliasIterator::MCRegAliasIterator(), llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::MCRegUnitRootIterator::MCRegUnitRootIterator(), llvm::MCSubRegIterator::MCSubRegIterator(), llvm::MCSuperRegIterator::MCSuperRegIterator(), llvm::BitTracker::RegisterCell::meet(), llvm::sandboxir::MemDGNode::MemDGNode(), MemOperandsHaveAlias(), llvm::object::MinidumpFile::MemoryInfoIterator::MemoryInfoIterator(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), memoryIsNotModifiedBetween(), llvm::MemorySSA::MemorySSA(), llvm::MemorySSA::MemorySSA(), llvm::MemProfContextDisambiguation::MemProfContextDisambiguation(), llvm::MemSDNode::MemSDNode(), llvm::sandboxir::MemSeedBundle< sandboxir::StoreInst >::MemSeedBundle(), llvm::sandboxir::MemSeedBundle< sandboxir::StoreInst >::MemSeedBundle(), memVTFromLoadIntrData(), memVTFromLoadIntrReturn(), llvm::GlobalMergeFunc::merge(), llvm::HexagonBlockRanges::IndexRange::merge(), llvm::StableFunctionMap::merge(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::MergeBlockSuccessorsIntoGivenBlocks(), llvm::MDBuilder::mergeCallbackEncodings(), mergeComparisons(), mergeCompatibleInvokesImpl(), mergeConditionalStoreToAddress(), llvm::Instruction::mergeDIAssignID(), mergeEltWithShuffle(), llvm::OverflowTracking::mergeFlags(), mergeHighParts(), llvm::ValueLatticeElement::mergeIn(), llvm::DDGBuilder::mergeNodes(), mergeOperations(), mergeReplicateRegionsIntoSuccessors(), llvm::AliasSet::mergeSetIn(), llvm::M68kFrameLowering::mergeSPUpdates(), llvm::Constant::mergeUndefsWith(), llvm::LiveRange::MergeValueNumberInto(), mergeVectorRegsToResultRegs(), llvm::MIBundleBuilder::MIBundleBuilder(), migrateDebugInfo(), MIIsInTerminatorSequence(), llvm::AArch64FunctionInfo::MILOHDirective::MILOHDirective(), llvm::PBQP::Vector::minIndex(), llvm::minIntN(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsSubtarget::MipsSubtarget(), llvm::MIRAddFSDiscriminators::MIRAddFSDiscriminators(), llvm::MIRProfileLoaderPass::MIRProfileLoaderPass(), llvm::MLModelRunner::MLModelRunner(), LiveDebugValues::MLocTracker::MLocTracker(), llvm::MLPriorityAdvisor::MLPriorityAdvisor(), llvm::MMRAMetadata::MMRAMetadata(), llvm::APFloat::mod(), llvm::detail::DoubleAPFloat::mod(), llvm::detail::IEEEFloat::mod(), llvm::detail::mod(), llvm::mod(), llvm::MCSymbol::modifyFlags(), llvm::orc::ELFDebugObjectPlugin::modifyPassConfig(), modRMByte(), llvm::objcarc::ModuleHasARC(), moreElementsToNextExistingRegClass(), llvm::LegalizerHelper::moreElementsVectorPhi(), moreEltsToNext32Bit(), llvm::ConstantDataArraySlice::move(), moveAddAfterMinMax(), llvm::MachineFunction::moveAdditionalCallInfo(), llvm::DbgRecord::moveAfter(), llvm::DbgRecord::moveAfter(), llvm::MemorySSAUpdater::moveAllAfterMergeBlocks(), llvm::MemorySSAUpdater::moveAllAfterSpliceBlocks(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::DbgRecord::moveBefore(), llvm::DbgRecord::moveBefore(), moveBelowOrigChain(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT, BucketT >::moveFrom(), moveInstrOut(), moveLCSSAPhis(), llvm::IntervalMapImpl::NodeBase< std::pair< KeyT, KeyT >, ValT, LeafSize >::moveLeft(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::LoopInfo::movementPreservesLCSSAForm(), llvm::object::ExportEntry::moveNext(), llvm::object::MachOChainedFixupEntry::moveNext(), llvm::MachineRegisterInfo::moveOperands(), moveOperands(), llvm::IntervalMapImpl::NodeBase< std::pair< KeyT, KeyT >, ValT, LeafSize >::moveRight(), llvm::IntervalMapImpl::Path::moveRight(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::MemorySSA::moveTo(), llvm::LoopBase< BlockT, LoopT >::moveToHeader(), llvm::mca::Stage::moveToTheNextStage(), llvm::SIInstrInfo::moveToVALU(), llvm::SIInstrInfo::moveToVALUImpl(), MoveVPNOTBeforeFirstUser(), llvm::LoongArchInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), llvm::APFixedPoint::mul(), llvm::KnownBits::mul(), llvm::APIntOps::mulhs(), llvm::KnownBits::mulhs(), llvm::APIntOps::mulhu(), llvm::KnownBits::mulhu(), llvm::RISCVInstrInfo::mulImm(), llvm::APIntOps::mulsExtended(), llvm::APInt::multiplicativeInverse(), llvm::APFloat::multiply(), llvm::detail::DoubleAPFloat::multiply(), llvm::APIntOps::muluExtended(), mustBeUnreachableFunction(), llvm::FunctionSummary::mutableCallsites(), llvm::DIType::mutate(), llvm::InsertCFGStrategy::mutate(), llvm::InstDeleterIRStrategy::mutate(), llvm::SelectionDAG::mutateStrictFPToFP(), llvm::ValueInfo::name(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowExtractedVectorSelect(), narrowInterleaveGroupOp(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarShiftByConstantMultiway(), llvm::LegalizerHelper::narrowScalarShiftMultiway(), narrowSDivOrSRem(), llvm::narrowShuffleMaskElts(), narrowToSingleScalarRecipes(), narrowUDivOrURem(), llvm::sys::path::native(), llvm::pdb::NativeTypePointer::NativeTypePointer(), llvm::sys::unicode::nearestMatchesForCodepointName(), needCarryOrOverflowFlag(), llvm::X86_MC::needsAddressSizeOverride(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::RISCVRegisterInfo::needsFrameBaseReg(), needsLFTR(), llvm::remarks::RemarkStreamer::needsSection(), needStackSlotPassParameters(), negateICmpIfUsedByBranchOrSelectOnly(), llvm::DbgSSABlock::newPHI(), llvm::RandomIRBuilder::newSource(), llvm::ScheduleDAGInstrs::newSUnit(), llvm::ScheduleDAGSDNodes::newSUnit(), llvm::detail::DoubleAPFloat::next(), llvm::detail::IEEEFloat::next(), llvm::TrieHashIndexGenerator::next(), llvm::symbolize::MarkupParser::nextNode(), NextPossibleSolution(), nextRealType(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::nlist(), noConflictingReadWrites(), llvm::rdf::NodeAllocator::NodeAllocator(), llvm::IntervalMapImpl::NodeRef::NodeRef(), llvm::HexagonInstrInfo::nonDbgBundleSize(), nonnewline(), llvm::BlockFrequencyInfoImplBase::Distribution::normalize(), llvm::Triple::normalize(), NormalizeBuildVector(), llvm::DWARF5AccelTableData::normalizeDIEToOffset(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), normalizeForInvokeSafepoint(), llvm::DAGTypeLegalizer::NoteDeletion(), llvm::object::ELFFile< ELF32LE >::notes_begin(), llvm::object::ELFFile< ELF32LE >::notes_begin(), llvm::mca::WriteRef::notifyExecuted(), llvm::mca::ExecuteStage::notifyInstructionIssued(), llvm::sandboxir::Interval< T >::notifyMoveInstr(), llvm::orc::LinkGraphLinkingLayer::JITLinkCtx::notifyResolved(), llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState(), llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::numCombinations(), numElementsInSubstring(), llvm::pdb::InputFile::obj(), llvm::pdb::InputFile::obj(), llvm::json::OStream::objectEnd(), llvm::json::ObjectKey::ObjectKey(), llvm::json::ObjectKey::ObjectKey(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::CriticalAntiDepBreaker::Observe(), llvm::object::SFrameParser< E >::offsetOf(), llvm::DotCfgChangeReporter::omitAfter(), llvm::OnDiskChainedHashTable< Info >::OnDiskChainedHashTable(), llvm::MachineBlockFrequencyInfo::onEdgeSplit(), oneUseDominatesOtherUses(), llvm::mca::LSUnit::MemoryGroup::onGroupExecuted(), llvm::mca::LSUnit::MemoryGroup::onGroupIssued(), llvm::mca::LSUnit::MemoryGroup::onInstructionExecuted(), llvm::mca::LSUnit::onInstructionExecuted(), llvm::mca::RegisterFile::onInstructionExecuted(), llvm::mca::RetireControlUnit::onInstructionExecuted(), llvm::mca::LSUnit::MemoryGroup::onInstructionIssued(), llvm::mca::WriteState::onInstructionIssued(), llvm::mca::LSUnit::onInstructionRetired(), llvm::PPCInstrInfo::onlyFoldImmediate(), onlyZeroFlagUsed(), llvm::MLInlineAdvisor::onPassEntry(), llvm::MLInlineAdvisor::onPassExit(), llvm::MLInlineAdvisor::onSuccessfulInlining(), llvm::sandboxir::User::op_begin(), llvm::sandboxir::User::op_end(), llvm::GVNExpression::BasicExpression::op_push_back(), llvm::cas::ondisk::UnifiedOnDiskCache::open(), llvm::logicalview::LVSplitContext::open(), llvm::OpenMPIRBuilderConfig::openMPOffloadMandatory(), llvm::RegisterBankInfo::OperandsMapper::OperandsMapper(), llvm::BitTracker::BitValue::operator bool(), llvm::mca::ReleaseAtCycles::operator double(), llvm::yaml::basic_collection_iterator< MappingNode, KeyValueNode >::operator KeyValueNode *(), operator new(), llvm::HexagonBlockRanges::IndexType::operator unsigned(), llvm::const_set_bits_iterator_impl< BitVector >::operator!=(), llvm::operator!=(), llvm::APSInt::operator%(), llvm::APSInt::operator%=(), llvm::APSInt::operator&(), llvm::AAPointerInfo::Access::operator&=(), llvm::APInt::operator&=(), llvm::APSInt::operator&=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator&=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator&=(), llvm::deref< T >::operator()(), llvm::FileCache::operator()(), llvm::LessRecordRegister::operator()(), llvm::lto::ThinBackend::operator()(), llvm::memprof::CallerCalleePairExtractor::operator()(), llvm::memprof::LinearCallStackIdConverter::operator()(), llvm::orc::BlockFreqQuery::operator()(), llvm::SystemZTargetStreamer::CmpMCInst::operator()(), llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::operator()(), llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::operator()(), llvm::ValueDFS_Compare::operator()(), llvm::VGPRBlock2IndexFunctor::operator()(), llvm::AllocationOrder::Iterator::operator*(), llvm::APInt::operator*(), llvm::AppleAcceleratorTable::Iterator::operator*(), llvm::APSInt::operator*(), llvm::cas::OnDiskDataAllocator::OnDiskPtr::operator*(), llvm::cas::OnDiskTrieRawHashMap::PointerImpl< ProxyT >::operator*(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator*(), llvm::early_inc_iterator_impl< WrappedIteratorT >::operator*(), llvm::EquivalenceClasses< ElemTy >::member_iterator::operator*(), llvm::filter_iterator_base< WrappedIteratorT, PredicateT, IterTag >::operator*(), llvm::ilist_iterator< OptionsT, false, IsConst >::operator*(), llvm::ilist_iterator_w_bits< OptionsT, false, IsConst >::operator*(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator*(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::ir2vec::VocabStorage::const_iterator::operator*(), llvm::jitlink::LinkGraph::nested_collection_iterator< section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols >::operator*(), llvm::LazyAtomicPointer< TrieNode >::operator*(), llvm::MachineRegisterInfo::defusechain_instr_iterator< true, true, false, true >::operator*(), llvm::MachineRegisterInfo::defusechain_iterator< true, true, false, true, false >::operator*(), llvm::memoryaccess_def_iterator_base< MemoryAccess >::operator*(), llvm::memprof::CallStack< NodeT, IteratorT >::CallStackIterator::operator*(), llvm::object::Elf_Note_Iterator_Impl< ELFType< E, Is64 > >::operator*(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::orc::CtorDtorIterator::operator*(), llvm::PagedVector< T, PageSize >::MaterializedIterator::operator*(), llvm::pdb::HashTableIterator< ValueT >::operator*(), llvm::pdb::SymbolGroupIterator::operator*(), llvm::pdb::SymbolGroupIterator::operator*(), llvm::PredIterator< BasicBlock, Value::user_iterator >::operator*(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator*(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::operator*(), llvm::SampleContextTracker::Iterator::operator*(), llvm::sandboxir::PredIterator::operator*(), llvm::sandboxir::SeedContainer::iterator::operator*(), llvm::scc_iterator< GraphT, GT >::operator*(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator*(), llvm::SDNode::use_iterator::operator*(), llvm::SparseMultiSet< ValueT, KeyT, KeyFunctorT, SparseT >::iterator_base< SparseMultiSet * >::operator*(), llvm::TargetRegistry::iterator::operator*(), llvm::upward_defs_iterator::operator*(), llvm::ValueHandleBase::operator*(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator*(), llvm::yaml::basic_collection_iterator< MappingNode, KeyValueNode >::operator*(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator*(), llvm::APSInt::operator*=(), llvm::BranchProbability::operator*=(), llvm::BranchProbability::operator*=(), llvm::APSInt::operator+(), llvm::PBQP::Matrix::operator+(), llvm::BasicBlock::phi_iterator_impl< const PHINode, BasicBlock::const_iterator >::operator++(), llvm::BitMaskClassIterator::operator++(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator++(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator++(), llvm::early_inc_iterator_impl< WrappedIteratorT >::operator++(), llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++(), llvm::fallible_iterator< ChildFallibleIterator >::operator++(), llvm::GVNPass::LeaderMap::leader_iterator::operator++(), llvm::HexagonBlockRanges::IndexType::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++(), llvm::ir2vec::VocabStorage::const_iterator::operator++(), llvm::MachineRegisterInfo::defusechain_instr_iterator< true, true, false, true >::operator++(), llvm::MachineRegisterInfo::defusechain_iterator< true, true, false, true, false >::operator++(), llvm::MCRegAliasIterator::operator++(), llvm::MCRegUnitRootIterator::operator++(), llvm::memoryaccess_def_iterator_base< MemoryAccess >::operator++(), llvm::MIBundleOperandIteratorBase< ValueT >::operator++(), llvm::object::Elf_Note_Iterator_Impl< ELFType< E, Is64 > >::operator++(), llvm::orc::StaticInitGVIterator::operator++(), llvm::pdb::SymbolGroupIterator::operator++(), llvm::PredIterator< BasicBlock, Value::user_iterator >::operator++(), llvm::PSetIterator::operator++(), llvm::Register::operator++(), llvm::SampleContextTracker::Iterator::operator++(), llvm::sandboxir::IntervalIterator< T, Interval >::operator++(), llvm::sandboxir::OperandUseIterator::operator++(), llvm::sandboxir::PredIterator::operator++(), llvm::sandboxir::SeedContainer::iterator::operator++(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator++(), llvm::SDNode::use_iterator::operator++(), llvm::SparseMultiSet< ValueT, KeyT, KeyFunctorT, SparseT >::iterator_base< SparseMultiSet * >::operator++(), llvm::SuperRegClassIterator::operator++(), llvm::sys::path::const_iterator::operator++(), llvm::TargetRegistry::iterator::operator++(), llvm::upward_defs_iterator::operator++(), llvm::yaml::basic_collection_iterator< MappingNode, KeyValueNode >::operator++(), llvm::yaml::document_iterator::operator++(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::APInt::operator+=(), llvm::APSInt::operator+=(), llvm::BranchProbability::operator+=(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator+=, llvm::ir2vec::Embedding::operator+=(), llvm::PBQP::Matrix::operator+=(), llvm::PBQP::Vector::operator+=(), llvm::pdb::DbiModuleSourceFilesIterator::operator+=(), llvm::Register::operator+=(), llvm::SuccIterator< Instruction, BasicBlock >::operator+=(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::operator+=(), llvm::APSInt::operator-(), llvm::cas::ondisk::InternalRefArrayRef::iterator::operator-(), llvm::codeview::TypeIndex::operator-, llvm::codeview::TypeIndex::operator-, llvm::DWARFDebugNames::NameIterator::operator-(), llvm::FixedStreamArrayIterator< T >::operator-(), llvm::indent::operator-(), llvm::indexed_accessor_iterator< DerivedT, BaseT, T, PointerT, ReferenceT >::operator-(), llvm::pdb::DbiModuleSourceFilesIterator::operator-(), llvm::sandboxir::OperandUseIterator::operator-(), llvm::SDNodeIterator::operator-(), llvm::SuccIterator< Instruction, BasicBlock >::operator-(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::operator-(), llvm::ARM::operator--(), llvm::fallible_iterator< ChildFallibleIterator >::operator--(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::indent::operator--(), llvm::indent::operator--(), llvm::SparseMultiSet< ValueT, KeyT, KeyFunctorT, SparseT >::iterator_base< SparseMultiSet * >::operator--(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator--(), llvm::APInt::operator-=(), llvm::APSInt::operator-=(), llvm::BranchProbability::operator-=(), llvm::codeview::TypeIndex::operator-=(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::operator-=, llvm::FixedStreamArrayIterator< T >::operator-=(), llvm::indent::operator-=(), llvm::ir2vec::Embedding::operator-=(), llvm::pdb::DbiModuleSourceFilesIterator::operator-=(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::operator-=(), llvm::cas::OnDiskDataAllocator::OnDiskPtr::operator->(), llvm::cas::OnDiskTrieRawHashMap::PointerImpl< ProxyT >::operator->(), llvm::filter_iterator_base< WrappedIteratorT, PredicateT, IterTag >::operator->(), llvm::MachineRegisterInfo::defusechain_iterator< true, true, false, true, false >::operator->(), llvm::yaml::basic_collection_iterator< MappingNode, KeyValueNode >::operator->(), llvm::APSInt::operator/(), llvm::APSInt::operator/=(), llvm::BranchProbability::operator/=(), llvm::BranchProbability::operator/=(), llvm::APSInt::operator<(), llvm::BranchProbability::operator<(), llvm::cas::ondisk::InternalRefArrayRef::iterator::operator<(), llvm::FixedStreamArrayIterator< T >::operator<(), llvm::indexed_accessor_iterator< DerivedT, BaseT, T, PointerT, ReferenceT >::operator<(), llvm::object::SectionRef::operator<(), llvm::operator<(), llvm::pdb::DbiModuleSourceFilesIterator::operator<(), llvm::RetainedKnowledge::operator<(), llvm::SuccIterator< Instruction, BasicBlock >::operator<(), llvm::SwitchInst::CaseIteratorImpl< CaseHandle >::operator<(), llvm::SymbolInfoTy::operator<, llvm::ValID::operator<(), llvm::operator<<(), llvm::operator<<(), llvm::orc::operator<<(), llvm::PBQP::operator<<(), llvm::PBQP::operator<<(), llvm::raw_ostream::operator<<(), llvm::raw_ostream::operator<<(), llvm::sys::operator<<(), llvm::APInt::operator<<=(), llvm::BitVector::operator<<=(), llvm::APSInt::operator<=(), llvm::BranchProbability::operator<=(), llvm::APInt::operator=(), llvm::GlobalVariable::operator=(), llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::operator=(), llvm::PointerEmbeddedInt< IntT, Bits >::operator=(), llvm::Timer::operator=(), AllocaSlices::partition_iterator::operator==(), LiveDebugValues::MLocTracker::MLocIterator::operator==(), llvm::AllocationOrder::Iterator::operator==(), llvm::APInt::operator==(), llvm::APSInt::operator==(), llvm::const_set_bits_iterator_impl< BitVector >::operator==(), llvm::ConstantFPRange::operator==(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >::operator==, llvm::early_inc_iterator_impl< WrappedIteratorT >::operator==, llvm::fallible_iterator< ChildFallibleIterator >::operator==, llvm::FixedStreamArrayIterator< T >::operator==(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator==(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator==(), llvm::indexed_accessor_iterator< DerivedT, BaseT, T, PointerT, ReferenceT >::operator==(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator==(), llvm::IntervalMapImpl::NodeRef::operator==(), llvm::object::Archive::Child::operator==(), llvm::object::MachOBindEntry::operator==(), llvm::object::MachORebaseEntry::operator==(), llvm::object::SFrameParser< E >::FallibleFREIterator::operator==, llvm::operator==(), llvm::orc::CtorDtorIterator::operator==(), llvm::PBQP::Matrix::operator==(), llvm::PBQP::Vector::operator==(), llvm::pdb::DbiModuleSourceFilesIterator::operator==(), llvm::rdf::NodeAddr< NodeBase * >::operator==(), llvm::rdf::RegisterAggr::ref_iterator::operator==(), llvm::RegisterBank::operator==(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator==(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::operator==(), llvm::sandboxir::IntervalIterator< T, Interval >::operator==(), llvm::sandboxir::PredIterator::operator==(), llvm::sandboxir::SeedContainer::iterator::operator==(), llvm::sandboxir::Use::operator==(), llvm::SparseMultiSet< ValueT, KeyT, KeyFunctorT, SparseT >::iterator_base< SparseMultiSet * >::operator==(), llvm::StringTable::Iterator::operator==(), llvm::SwitchInst::CaseHandleImpl< const SwitchInst, const ConstantInt, const BasicBlock >::operator==(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator==(), llvm::yaml::basic_collection_iterator< MappingNode, KeyValueNode >::operator==(), llvm::APSInt::operator>(), llvm::BranchProbability::operator>(), llvm::APSInt::operator>=(), llvm::BranchProbability::operator>=(), llvm::BitVector::operator>>=(), llvm::BlockFrequency::operator>>=(), LiveDebugValues::FuncValueTable::operator[](), llvm::AddressRangesBase< T >::operator[](), llvm::AMDGPU::VOPD::InstInfo::operator[](), llvm::APInt::operator[](), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::operator[](), llvm::BitcodeReaderValueList::operator[](), llvm::BitTracker::RegisterCell::operator[](), llvm::BitTracker::RegisterCell::operator[](), llvm::BitVector::operator[](), llvm::BitVector::operator[](), llvm::CallGraph::operator[](), llvm::CallGraph::operator[](), llvm::CallGraphNode::operator[](), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator[](), llvm::dwarf::UnwindTable::operator[](), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::operator[](), llvm::FixedStreamArray< CrossModuleExport >::operator[](), llvm::GCStrategyMap::operator[](), llvm::IndexedMap< LiveOutPair, MBB2NumberFunctor >::operator[](), llvm::IndexedMap< LiveOutPair, MBB2NumberFunctor >::operator[](), llvm::IntEqClasses::operator[](), llvm::ir2vec::Embedding::operator[](), llvm::ir2vec::Embedding::operator[](), llvm::ir2vec::VocabStorage::operator[](), llvm::ir2vec::Vocabulary::operator[](), llvm::ir2vec::Vocabulary::operator[](), llvm::ir2vec::Vocabulary::operator[](), llvm::LazyCallGraph::EdgeSequence::operator[](), llvm::LiveIntervalUnion::Array::operator[](), llvm::LiveIntervalUnion::Array::operator[](), llvm::MCRegisterInfo::operator[](), llvm::msgpack::MapDocNode::operator[](), llvm::MutableArrayRef< char >::operator[](), llvm::NVPTXScopes::operator[](), llvm::object::DataRegion< T >::operator[](), llvm::PagedVector< T, PageSize >::operator[](), llvm::PBQP::Matrix::operator[](), llvm::PBQP::Matrix::operator[](), llvm::PBQP::Vector::operator[](), llvm::PBQP::Vector::operator[](), llvm::PressureDiffs::operator[](), llvm::SetVector< EdgeType * >::operator[](), llvm::SmallBitVector::operator[](), llvm::SmallBitVector::operator[](), llvm::SmallVectorTemplateCommon< T, typename >::operator[](), llvm::SmallVectorTemplateCommon< T, typename >::operator[](), llvm::StringRef::operator[](), llvm::TinyPtrVector< ReachingDef >::operator[](), llvm::UniqueVector< const Comdat * >::operator[](), llvm::APSInt::operator^(), llvm::APInt::operator^=(), llvm::APSInt::operator^=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator^=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator^=(), llvm::APSInt::operator|(), llvm::APInt::operator|=(), llvm::APSInt::operator|=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator|=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator|=(), llvm::cl::applicator< MiscFlags >::opt(), OptimizeAndOrXor(), OptimizeAwayTrappingUsesOfLoads(), llvm::LibCallSimplifier::optimizeCall(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::RISCVInstrInfo::optimizeCondBranch(), OptimizeConstMinMax(), optimizeDivRem(), llvm::OptimizedStructLayoutField::OptimizedStructLayoutField(), llvm::AArch64TargetLowering::optimizeExtendOrTruncateConversion(), OptimizeExtractBits(), llvm::VPlanTransforms::optimizeForVFAndUF(), slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::jitlink::systemz::optimizeGOTAndStubAccesses(), llvm::jitlink::x86::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), optimizeLatchExitInductionUser(), llvm::TargetInstrInfo::optimizeLoadInstr(), optimizeLogicalImm(), optimizeLoopExitWithUnknownExitCount(), optimizeModularFormat(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::RISCVInstrInfo::optimizeSelect(), optimizeVectorResizeWithIntegerBitCasts(), llvm::opt::Option::Option(), llvm::opt::OptTable::OptTable(), llvm::dwarf_linker::parallel::OrderedChildrenIndexAssigner::OrderedChildrenIndexAssigner(), llvm::RISCVDAGToDAGISel::orDisjoint(), othercase(), llvm::RegionBase< Tr >::outermostLoopInRegion(), llvm::vfs::OutputError::OutputError(), llvm::vfs::OutputError::OutputError(), llvm::vfs::OutputFile::OutputFile(), outputHex(), llvm::ms_demangle::ArrayTypeNode::outputOneDimension(), llvm::ms_demangle::PointerTypeNode::outputPre(), llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::OutputUnitVariantPtr(), llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::OutputUnitVariantPtr(), llvm::outs(), overflowFlagToValue(), llvm::ConstantRange::overflowingBinaryOp(), llvm::InstrProfRecord::overlap(), llvm::SplitEditor::overlapIntv(), llvm::IntervalMap< IndexT, char >::overlaps(), llvm::LiveRange::overlaps(), llvm::LiveRange::overlaps(), llvm::LiveRange::overlapsFrom(), llvm::InstrProfRecord::overlapValueProfData(), p_bracket(), p_ere(), p_ere_exp(), p_simp_re(), packAllocSizeArgs(), packCmovGroup(), llvm::ARM::WinEH::RuntimeFunction::PackedUnwindData(), llvm::ARM::WinEH::RuntimeFunctionARM64::PackedUnwindData(), llvm::VLIWPacketizerList::PacketizeMIs(), packImage16bitOpsToDwords(), llvm::PseudoProbeDwarfDiscriminator::packProbeData(), packSegmentMask(), llvm::HexagonMCInstrInfo::padEndloop(), llvm::PagedVector< T, PageSize >::PagedVector(), llvm::CallBase::paramHasAttr(), llvm::CallBase::paramHasNonNullAttr(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::DWARFDebugLine::LineTable::parse(), llvm::DWARFDebugLine::Prologue::parse(), llvm::objcopy::elf::IHexRecord::parse(), llvm::RISCVISAInfo::parseArchString(), ParseBFI(), llvm::SPIRV::parseBuiltinCallArgumentType(), llvm::SPIRV::parseBuiltinTypeNameToTargetExtType(), parseCond(), parseCond(), parseCondBranch(), parseCondBranch(), parseCondBranch(), llvm::TargetLowering::ParseConstraints(), llvm::RISCVISAInfo::parseFeatures(), llvm::formatv_object_base::parseFormatString(), llvm::cas::builtin::BuiltinCASContext::parseID(), parseInt(), llvm::LoopStructure::parseLoopStructure(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::LLParser::parseMDField(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadata(), llvm::MetadataLoader::MetadataLoaderImpl::parseMetadataAttachment(), llvm::DWARFDebugLine::SectionParser::parseNext(), llvm::support::detail::HelperFunctions::parseNumericPrecision(), llvm::XCOFF::parseParmsTypeWithVecInfo(), llvm::MIRParserImpl::parseRegisterInfo(), parseRegisterNumber(), parseReplacementItem(), parseScalarValue(), llvm::pdb::PDBFile::parseStreamData(), parseThunkName(), llvm::parseWidenableGuard(), llvm::partAsHex(), llvm::PartialOrderingVisitor::partialOrderVisit(), partitionShuffleOfConcats(), llvm::partitionSVECS(), llvm::sandboxir::Pass::Pass(), passingValueIsAlwaysUndefined(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::SITargetLowering::passSpecialInputs(), Passv64i1ArgInRegs(), llvm::PatchPointOpers::PatchPointOpers(), llvm::patchReplacementInstruction(), llvm::pdb::InputFile::pdb(), llvm::pdb::InputFile::pdb(), llvm::BinaryStreamReader::peek(), llvm::mca::CircularSourceMgr::peekNext(), llvm::mca::IncrementalSourceMgr::peekNext(), llvm::yaml::Scanner::peekNext(), llvm::AsmLexer::peekTok(), llvm::peelLoop(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), llvm::PeelSingleBlockLoop(), performActiveLaneMaskCombine(), performAddCSelIntoCSinc(), performAnyAllCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), performBITREVERSECombine(), performBlockTailMerging(), performBranchToCommonDestFolding(), performBRCONDCombine(), PerformBUILD_VECTORCombine(), performBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCustomAdjustments(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtractLastActiveCombine(), performExtractsShuffleAction(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFirstTrueTestVectorCombine(), performGatherLoadCombine(), PerformHWLoopCombine(), performLastTrueTestVectorCombine(), performMOVFR2GR_SCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), performMulCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::performOptimizedStructLayout(), performORCombine(), performORCombine(), PerformREMCombine(), performScatterStoreCombine(), performSelectCombine(), performSetccAddFolding(), performSETCCCombine(), performSetccMergeZeroCombine(), performSignExtendInRegCombine(), performSignExtendSetCCCombine(), performSpliceCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSRACombine(), performSubsToAndsCombine(), performTBZCombine(), performTruncateCombine(), PerformTruncatingStoreCombine(), performUADDVAddCombine(), performUADDVCombine(), performUADDVZextCombine(), performUnpackCombine(), PerformVECREDUCE_ADDCombine(), performVECTOR_SHUFFLECombine(), performVectorExtendCombine(), performVectorExtendToFPCombine(), performVectorShiftCombine(), PerformVQDMULHCombine(), performVWADDSUBW_VLCombine(), llvm::PGOOptions::PGOOptions(), llvm::InstCombinerImpl::PHIArgMergedDebugLoc(), PhiHasDebugValue(), phiNodeOperandWithNewAddressSpace(), llvm::PiBlockDDGNode::PiBlockDDGNode(), llvm::PiBlockDDGNode::PiBlockDDGNode(), llvm::PiBlockDDGNode::PiBlockDDGNode(), llvm::ConvergingVLIWScheduler::pickNode(), llvm::GCNSchedStrategy::pickNode(), llvm::GenericScheduler::pickNode(), llvm::PostGenericScheduler::pickNode(), llvm::SystemZPostRASchedStrategy::pickNode(), llvm::GCNSchedStrategy::pickNodeBidirectional(), llvm::GenericScheduler::pickNodeBidirectional(), llvm::PostGenericScheduler::pickNodeBidirectional(), llvm::ConvergingVLIWScheduler::pickNodeBidrectional(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::pickOnlyChoice(), placeSources(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::PluginInlineAdvisorAnalysis::PluginInlineAdvisorAnalysis(), llvm::PluginInlineOrderAnalysis::PluginInlineOrderAnalysis(), llvm::LLT::pointer(), llvm::cas::OnDiskTrieRawHashMap::PointerImpl< ProxyT >::PointerImpl(), llvm::PointerMayBeCaptured(), llvm::PointerMayBeCaptured(), llvm::PointerMayBeCapturedBefore(), llvm::rdf::DataFlowGraph::DefStack::pop(), llvm::sys::fs::recursive_directory_iterator::pop(), llvm::BitVector::pop_back(), llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_back(), llvm::PriorityWorklist< T, VectorT, MapT >::pop_back(), llvm::SetVector< EdgeType * >::pop_back(), llvm::SmallBitVector::pop_back(), llvm::const_iterator< MemoryLocation >::pop_back_n(), llvm::GISelWorkList< 512 >::pop_back_val(), llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_front(), llvm::ConstraintSystem::popLastNVariables(), popRegsFromStack(), llvm::TGParser::PopScope(), llvm::CallBase::populateBundleOperandInfos(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), populateDependencyMatrix(), populateEHOperandBundle(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), populateWorklist(), llvm::GraphDiff< MachineBasicBlock *, false >::popUpdateForIncrementalUpdates(), llvm::possiblyDemandedEltsInMask(), llvm::SITargetLowering::PostISelFolding(), llvm::LazyCallGraph::postorder_ref_scc_begin(), llvm::LazyCallGraph::postorder_ref_scc_end(), llvm::APIntOps::pow(), llvm::powerOf5(), llvm::cas::ondisk::preallocateFileTail(), llvm::SwiftErrorValueTracking::preassignVRegs(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::TargetInstrInfo::PredicateInstruction(), predictValueUseListOrder(), predictValueUseListOrder(), predictValueUseListOrderImpl(), predictValueUseListOrderImpl(), llvm::sandboxir::MemDGNode::PredIterator, llvm::X86TargetLowering::preferedOpcodeForCmpEqPiecesOfOperand(), llvm::ARMTTIImpl::preferPredicateOverEpilogue(), llvm::orc::SharedMemoryMapper::prepare(), llvm::SGPRSpillBuilder::prepare(), llvm::SystemZInstrInfo::prepareCompareSwapOperands(), prepareDescriptorIndirectCall(), preparePlanForEpilogueVectorLoop(), llvm::prepareTempFiles(), llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), llvm::PrepareToSplitEntryBlock(), llvm::TargetRegisterInfo::prependOffsetExpression(), llvm::DIExpression::prependOpcodes(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::X86InstrInfo::preservesZeroValueInReg(), llvm::PressureChange::PressureChange(), llvm::prettyPrintBaseTypeRef(), llvm::Align::previous(), llvm::BranchProbabilityInfo::print(), llvm::cas::ondisk::OnDiskGraphDB::print(), llvm::cas::ReferenceBase::print(), llvm::cas::ReferenceBase::print(), llvm::format_object_base::print(), llvm::LiveRange::print(), llvm::LiveRangeUpdater::print(), llvm::LLT::print(), llvm::MachineInstr::print(), llvm::MachineMemOperand::print(), llvm::MachineOperand::print(), llvm::RegisterBank::print(), llvm::RISCVConstantPoolValue::print(), llvm::VPIRMetadata::print(), llvm::ARMInstPrinter::printAddrMode2Operand(), llvm::ARMInstPrinter::printAddrMode3Operand(), llvm::AArch64InstPrinter::printAddSubImm(), llvm::AArch64InstPrinter::printAMIndexedWB(), llvm::ARMAsmPrinter::PrintAsmMemoryOperand(), llvm::BPFAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::XtensaAsmPrinter::PrintAsmMemoryOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::LoongArchInstPrinter::printAtomicMemOp(), llvm::ARMInstPrinter::printBankedRegOperand(), llvm::AArch64InstPrinter::printBarriernXSOption(), llvm::ARMInstPrinter::printBitfieldInvMaskImmOperand(), llvm::HexagonInstPrinter::printBrtarget(), PrintByteList(), llvm::NVPTXInstPrinter::printCallOperand(), llvm::printCompactDWARFExpr(), llvm::SystemZInstPrinterCommon::printCond4Operand(), llvm::X86InstPrinterCommon::printCondFlags(), llvm::CSKYInstPrinter::printConstpool(), printCustomRegMask(), llvm::PreservedCFGCheckerInstrumentation::CFG::printDiff(), llvm::cl::Option::printEnumValHelpStr(), printExpr(), printExpr(), printExpr(), llvm::RISCVInstPrinter::printFenceArg(), printFormattedRegName(), llvm::CSKYInstPrinter::printFPR(), PrintHelpOptionList(), llvm::cl::Option::printHelpStr(), llvm::LanaiInstPrinter::printHi16AndImmOperand(), llvm::LanaiInstPrinter::printHi16ImmOperand(), llvm::AMDGPUInstPrinter::printIfSet(), llvm::AMDGPUInstPrinter::printIfSet(), llvm::AMDGPUMIRFormatter::printImm(), llvm::AArch64InstPrinter::printImm8OptLsl(), llvm::PPCInstPrinter::printImmZeroOperand(), printImplicitRegisterFlag(), llvm::SourceMgr::PrintIncludeStack(), llvm::AArch64AppleInstPrinter::printInst(), llvm::ARMInstPrinter::printInst(), llvm::PPCInstPrinter::printInst(), llvm::SPIRVInstPrinter::printInst(), llvm::WebAssemblyInstPrinter::printInst(), printLine(), llvm::R600InstPrinter::printLiteral(), llvm::printLLVMNameWithoutPrefix(), llvm::LanaiInstPrinter::printLo16AndImmOperand(), PrintLoopInfo(), printMatch(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), llvm::AArch64InstPrinter::printMatrix(), llvm::AArch64InstPrinter::printMatrixTile(), llvm::AArch64InstPrinter::printMatrixTileVector(), printMBB(), llvm::LanaiInstPrinter::printMemImmOperand(), llvm::X86ATTInstPrinter::printMemOffset(), llvm::X86IntelInstPrinter::printMemOffset(), llvm::BPFInstPrinter::printMemOperand(), printMemoryBaseRegister(), printMemoryImmediateOffset(), llvm::X86ATTInstPrinter::printMemReference(), llvm::X86IntelInstPrinter::printMemReference(), llvm::LanaiInstPrinter::printMemRrOperand(), llvm::SourceMgr::PrintMessage(), printMI(), llvm::ARMInstPrinter::printMveSaturateOp(), printNoMatch(), llvm::printOp(), llvm::SPIRVInstPrinter::printOpConstantVarOps(), llvm::AArch64InstPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::ARMInstPrinter::printOperand(), llvm::BPFInstPrinter::printOperand(), llvm::CSKYInstPrinter::printOperand(), llvm::LanaiInstPrinter::printOperand(), llvm::NVPTXInstPrinter::printOperand(), llvm::PPCInstPrinter::printOperand(), llvm::RISCVInstPrinter::printOperand(), llvm::SparcInstPrinter::printOperand(), llvm::VEInstPrinter::printOperand(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::X86ATTInstPrinter::printOperand(), llvm::X86IntelInstPrinter::printOperand(), printOperand(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::X86InstPrinterCommon::printPCRelImm(), llvm::ARMInstPrinter::printPKHASRShiftImm(), llvm::ARMInstPrinter::printPKHLSLShiftImm(), llvm::PPCInstPrinter::printPredicateOperand(), llvm::NVPTXInstPrinter::printProtoIdent(), llvm::AArch64InstPrinter::printRangePrefetchAlias(), llvm::VPHistogramRecipe::printRecipe(), llvm::VPInstructionWithType::printRecipe(), llvm::VPWidenPointerInductionRecipe::printRecipe(), llvm::printRegClassOrBank(), printRegImmShift(), llvm::ARMInstPrinter::printRegisterList(), llvm::RISCVInstPrinter::printRegList(), llvm::RISCVZC::printRegList(), llvm::WebAssemblyInstPrinter::printRegName(), llvm::RISCVInstPrinter::printRegReg(), llvm::printRegUnit(), llvm::AArch64InstPrinter::printRegWithShiftExtend(), llvm::ARMInstPrinter::printRotImmOperand(), llvm::PPCInstPrinter::printS32ImmOperand(), llvm::PPCInstPrinter::printS34ImmOperand(), llvm::ARMInstPrinter::printSBitModifierOperand(), llvm::SystemZInstPrinterCommon::printSImmOperand(), llvm::ARMInstPrinter::printSORegRegOperand(), llvm::AVRMCAsmInfo::printSpecifierExpr(), llvm::RISCVInstPrinter::printStackAdj(), printStackObjectReference(), llvm::PrintStatisticsJSON(), llvm::AArch64InstPrinter::printSVCROp(), llvm::MCAsmInfoDarwin::printSwitchToSection(), llvm::MCAsmInfoXCOFF::printSwitchToSection(), llvm::object::TapiFile::printSymbolName(), llvm::ARMAsmPrinter::PrintSymbolOperand(), llvm::AsmPrinter::PrintSymbolOperand(), llvm::AArch64InstPrinter::printSysAlias(), llvm::AArch64InstPrinter::printSysCROperand(), llvm::AArch64InstPrinter::printSyslAlias(), llvm::AArch64InstPrinter::printSyspAlias(), llvm::AArch64InstPrinter::printSyspXzrPair(), llvm::ARMInstPrinter::printT2AddrModeImm8s4OffsetOperand(), llvm::ARMInstPrinter::printT2AddrModeImm8s4Operand(), llvm::ARMInstPrinter::printT2AddrModeSoRegOperand(), llvm::ARMInstPrinter::printT2SOOperand(), llvm::MachineOperand::printTargetFlags(), llvm::ARMInstPrinter::printThumbITMask(), llvm::PPCInstPrinter::printU10ImmOperand(), llvm::PPCInstPrinter::printU12ImmOperand(), llvm::PPCInstPrinter::printU1ImmOperand(), llvm::PPCInstPrinter::printU2ImmOperand(), llvm::PPCInstPrinter::printU3ImmOperand(), llvm::PPCInstPrinter::printU4ImmOperand(), llvm::PPCInstPrinter::printU5ImmOperand(), llvm::PPCInstPrinter::printU6ImmOperand(), llvm::PPCInstPrinter::printU7ImmOperand(), llvm::AArch64InstPrinter::printUImm12Offset(), llvm::SystemZInstPrinterCommon::printUImmOperand(), llvm::SPIRVInstPrinter::printUnknownType(), llvm::NVPTXInstPrinter::printUsedBytesMaskPragma(), llvm::Pattern::printVariableDefs(), llvm::X86ATTInstPrinter::printVecCompareInstr(), llvm::X86IntelInstPrinter::printVecCompareInstr(), llvm::RISCVInstPrinter::printVMaskReg(), llvm::ARMInstPrinter::printVPTMask(), llvm::AArch64InstPrinter::printVRegOperand(), printWithSpacePadding(), llvm::RISCVInstPrinter::printXSfmmVType(), printZeroExtend(), llvm::RISCVInstPrinter::printZeroOffsetMemOp(), priorNonDebug(), llvm::AArch64InstrInfo::probedStackAlloc(), processBlockAddr(), llvm::JumpThreadingPass::processBranchOnXOR(), slpvectorizer::BoUpSLP::processBuildVector(), processCallSite(), processDbgDeclare(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::processInstr(), processInternalGlobal(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVBinaryReader::processLines(), llvm::AArch64_AM::processLogicalImmediate(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), processPhiNode(), processPSInputArgs(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldMachO::processScatteredVANILLA(), processSDiv(), processSDivOrSRem(), llvm::processShuffleMasks(), processSingleLocVars(), processSRem(), processSwitchesConstants(), llvm::JumpThreadingPass::processThreadableEdges(), processUDivOrURem(), processUMulZExtIdiom(), llvm::xray::FileBasedRecordProducer::produce(), llvm::AttributeImpl::Profile(), llvm::AttributeImpl::Profile(), llvm::ProfileAnnotatorImpl::ProfileAnnotatorImpl(), ProfileCondOpInit(), llvm::sampleprof::ProfileConverter::ProfileConverter(), llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph(), ProfitableToMerge(), profitableToRotateLoopExitingLatch(), llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder(), promoteAllocaUserToVector(), llvm::promoteCall(), llvm::promoteCallWithIfThenElse(), llvm::promoteCallWithVTableCmp(), llvm::PPCInstrInfo::promoteInstr32To64ForElimEXTSW(), llvm::promoteLoopAccessesToScalars(), PromoteMaskArithmetic(), llvm::HexagonPacketizerList::promoteToDotCur(), llvm::HexagonPacketizerList::promoteToDotNew(), promoteVCIXScalar(), llvm::ModuleSummaryIndex::propagateAttributes(), propagateAttributesToRefs(), propagateMemProfHelper(), propagateNaN(), propagateSPIRVType(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::VPDominatorTree::properlyDominates(), ProvideOption(), llvm::vfs::ProxyOutputBackend::ProxyOutputBackend(), llvm::SIInstrInfo::pseudoToMCOpcode(), llvm::DXContainerYAML::PSVInfo::PSVInfo(), llvm::DIDerivedType::PtrAuthData::PtrAuthData(), llvm::PtrToAddrInst::PtrToAddrInst(), llvm::PtrToIntInst::PtrToIntInst(), llvm::InstructionWorklist::push(), llvm::PMStack::push(), llvm::AAPointerInfo::RangeList::push_back(), llvm::coverage::MCDCRecord::TestVector::push_back(), llvm::IntrusiveBackListBase::push_back(), llvm::msgpack::ArrayDocNode::push_back(), llvm::TinyPtrVector< ReachingDef >::push_back(), llvm::IntrusiveBackListBase::push_front(), PushArgMD(), llvm::cas::ActionCache::put(), llvm::cas::ondisk::OnDiskKeyValueDB::put(), llvm::BitTracker::MachineEvaluator::putCell(), llvm::raw_pwrite_stream::pwrite(), query(), llvm::ARM::WinEH::RuntimeFunction::R(), llvm::AAPointerInfo::RangeList::RangeList(), rangeMetadataExcludesValue(), llvm::RawLocationWrapper::RawLocationWrapper(), llvm::json::OStream::rawValueEnd(), llvm::BitTracker::reached(), llvm::SimpleBitstreamCursor::Read(), llvm::coverage::RawCoverageMappingReader::read(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), llvm::raw_fd_stream::read(), readAbbreviatedField(), llvm::jitlink::aarch32::readAddend(), llvm::BinaryStreamReader::readArray(), llvm::support::endian::readAtBitAlignment(), readBBAddrMapImpl(), llvm::sampleprof::SampleProfileReaderBinary::readCallsiteVTableProf(), llvm::FileCheck::readCheckFile(), llvm::BinaryStreamReader::readCString(), llvm::memprof::CallStackLookupTrait::ReadData(), llvm::cas::ObjectStore::readData(), llvm::jitlink::CompactUnwindTraits< CRTPImpl, PtrSize >::readEncoding(), llvm::MachO::DylibReader::readFile(), llvm::msgpack::Document::readFromBlob(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), llvm::GCOVFile::readGCDA(), readImmediate(), llvm::sampleprof::SampleProfileReaderGCC::readImpl(), llvm::sampleprof::SampleProfileReaderText::readImpl(), readMemprof(), LiveDebugValues::MLocTracker::readMLoc(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), llvm::memprof::RawMemProfReader::readNextRecord(), llvm::OnDiskChainedHashTable< Info >::readNumBucketsAndEntries(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readOneSection(), llvm::jitlink::CompactUnwindTraits< CRTPImpl, PtrSize >::readPCRangeSize(), llvm::offloading::readPropertiesFromJSON(), llvm::BitstreamCursor::readRecord(), llvm::sampleprof::SampleProfileReaderBinary::readSampleContextFromTable(), llvm::MachineOperand::readsReg(), readsWritesFloatRegister(), llvm::pdb::ModuleDebugStreamRef::readSymbolAtOffset(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), reassociateFCmps(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::OutlinableRegion::reattachCandidate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), rebasedHexDigitToNumber(), rebuildConstant(), rebuildExtCst(), rebuildLoopAfterUnswitch(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::BuildVectorSDNode::recastRawBits(), llvm::GCNUpwardRPTracker::recede(), llvm::RegPressureTracker::recede(), llvm::RegPressureTracker::recede(), llvm::GCNHazardRecognizer::RecedeCycle(), llvm::RegPressureTracker::recedeSkipDebugValues(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::HashRecognize::recognizeCRC(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), llvm::recomputeLivenessFlags(), recomputeLoopBlockSet(), llvm::recomputeVPTBlockMask(), reconnectPhis(), llvm::AArch64::ExtensionSet::reconstructFromParsedFeatures(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReconstructShuffleWithRuntimeMask(), ReconstructTruncateFromBuildVector(), llvm::ImportedFunctionsInliningStatistics::recordInline(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), llvm::StackMaps::recordPatchPoint(), llvm::ELFObjectWriter::recordRelocation(), llvm::GOFFObjectWriter::recordRelocation(), llvm::WinCOFFObjectWriter::recordRelocation(), llvm::WinCOFFWriter::recordRelocation(), llvm::StackMaps::recordStackMap(), llvm::StackMaps::recordStatepoint(), llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::recordTrampolineAddrs(), llvm::MLInlineAdvice::recordUnattemptedInliningImpl(), llvm::RecordVal::RecordVal(), llvm::RecordVal::RecordVal(), llvm::RecurrenceDescriptor::RecurrenceDescriptor(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::orc::JITLinkRedirectableSymbolManager::redirect(), redirectTo(), redirectToHub(), redirectValuesFromPredecessorsToPhi(), reduceBuildVecToShuffleWithZero(), llvm::ScheduleDAGInstrs::reduceHugeMemNodeMaps(), reduceMaskedLoadToScalarLoad(), reduceSwitchRange(), llvm::cas::ReferenceBase::ReferenceBase(), llvm::MachineMemOperand::refineAlignment(), llvm::ARM::WinEH::RuntimeFunction::Reg(), llvm::ARM::WinEH::RuntimeFunctionARM64::RegF(), llvm::ARM::WinEH::RuntimeFunctionARM64::RegI(), regIsPICBase(), llvm::Attributor::registerAA(), llvm::AssumptionCache::registerAssumption(), llvm::RegisterBankInfo::RegisterBankInfo(), llvm::DomConditionCache::registerBranch(), llvm::DotCfgChangeReporter::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::sandboxir::Context::registerCreateInstrCallback(), llvm::OffloadEntriesInfoManager::registerDeviceGlobalVarEntryInfo(), llvm::sandboxir::Context::registerEraseInstrCallback(), llvm::jitlink::aarch64::PLTTableManager::registerExistingEntries(), llvm::jitlink::x86_64::PLTTableManager::registerExistingEntries(), llvm::Attributor::registerForUpdate(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::orc::JITLinkReentryTrampolines::TrampolineAddrScraperPlugin::registerGraph(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), llvm::orc::RTDyldObjectLinkingLayer::registerJITEventListener(), llvm::ManagedStaticBase::RegisterManagedStatic(), llvm::MachineBasicBlock::RegisterMaskPair::RegisterMaskPair(), llvm::sandboxir::Context::registerMoveInstrCallback(), llvm::PassRegistry::registerPass(), llvm::jitlink::TableManager< TableManagerImplT >::registerPreExistingEntry(), llvm::sandboxir::Context::registerSetUseCallback(), llvm::TargetRegistry::RegisterTarget(), llvm::OffloadEntriesInfoManager::registerTargetRegionEntryInfo(), llvm::sandboxir::Context::registerValue(), llvm::sandboxir::InstrMaps::registerVector(), llvm::WebAssemblyAsmPrinter::regToString(), llvm::ConcurrentHashTableByPtr< KeyTy, KeyDataTy, AllocatorTy, Info >::RehashBucket(), llvm::jitlink::relaxAlign(), llvm::LoongArchAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::LoongArchAsmBackend::relaxDwarfLineAddr(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::ARMAsmBackend::relaxInstruction(), llvm::RISCVAsmBackend::relaxInstruction(), llvm::RefCountedBase< Derived >::Release(), llvm::RopeRefCountString::Release(), llvm::ThreadSafeRefCountedBase< Derived >::Release(), llvm::ImutAVLTree< ValInfo >::release(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::mca::ResourceState::releaseBuffer(), llvm::SchedBoundary::releaseNode(), llvm::mca::ResourceState::releaseSubResource(), llvm::ModuleSummaryIndex::releaseTemporaryMemory(), llvm::pdb::InjectedSourceStream::reload(), llvm::pdb::PDBStringTable::reload(), llvm::orc::MachOBuilder< MachOTraits >::Reloc::Reloc(), relocationViaAlloca(), llvm::StatepointLoweringState::relocCallVisited(), llvm::APFloat::remainder(), llvm::detail::DoubleAPFloat::remainder(), llvm::detail::IEEEFloat::remainder(), llvm::Intrinsic::remangleIntrinsicFunction(), remapIndices(), remapOperands(), llvm::SIInstrInfo::reMaterialize(), llvm::LiveRangeEdit::rematerializeAt(), rematerializeChain(), rematerializeCheapDef(), rematerializeLiveValues(), rematerializeLiveValuesAtUses(), llvm::orc::tpctypes::RemoteAllocGroup::RemoteAllocGroup(), llvm::ConstantUniqueMap< ConstantArray >::remove(), llvm::GISelWorkList< 512 >::remove(), llvm::LatencyPriorityQueue::remove(), llvm::MachineBasicBlock::remove(), llvm::orc::JITDylib::remove(), llvm::ResourcePriorityQueue::remove(), llvm::SetVector< EdgeType * >::remove(), llvm::ImutAVLFactory< ImutInfo >::remove_internal(), llvm::jitlink::LinkGraph::removeAbsoluteSymbol(), llvm::memprof::removeAnyExistingAmbiguousAttribute(), llvm::AttrBuilder::removeAttribute(), llvm::jitlink::LinkGraph::removeBlock(), llvm::LoopBase< BlockT, LoopT >::removeBlockFromLoop(), removeBlockFromLoops(), llvm::MemorySSAUpdater::removeBlocks(), llvm::ARCInstrInfo::removeBranch(), llvm::ARMBaseInstrInfo::removeBranch(), llvm::BPFInstrInfo::removeBranch(), llvm::HexagonInstrInfo::removeBranch(), llvm::LanaiInstrInfo::removeBranch(), llvm::M68kInstrInfo::removeBranch(), llvm::MipsInstrInfo::removeBranch(), llvm::MSP430InstrInfo::removeBranch(), llvm::NVPTXInstrInfo::removeBranch(), llvm::PPCInstrInfo::removeBranch(), llvm::R600InstrInfo::removeBranch(), llvm::SystemZInstrInfo::removeBranch(), llvm::VEInstrInfo::removeBranch(), llvm::WebAssemblyInstrInfo::removeBranch(), llvm::X86InstrInfo::removeBranch(), llvm::XCoreInstrInfo::removeBranch(), llvm::VPlanTransforms::removeBranchOnConst(), llvm::SwitchInst::removeCase(), llvm::SwitchInstProfUpdateWrapper::removeCase(), llvm::LoopBase< BlockT, LoopT >::removeChildLoop(), llvm::FastISel::removeDeadCode(), RemoveDeadConstant(), llvm::LazyCallGraph::removeDeadFunctions(), llvm::jitlink::LinkGraph::removeDefinedSymbol(), llvm::IndirectBrInst::removeDestination(), llvm::LazyCallGraph::removeEdge(), removeEmptyCleanup(), llvm::jitlink::LinkGraph::removeExternalSymbol(), llvm::AMDGPU::removeFnAttrFromReachable(), llvm::MachineInstr::removeFromBundle(), llvm::orc::JITDylib::removeFromLinkOrder(), llvm::MemorySSA::removeFromLookups(), llvm::MachineFunction::removeFromMBBNumbering(), llvm::MachineBasicBlock::removeFromParent(), llvm::MachineInstr::removeFromParent(), llvm::VPRecipeBase::removeFromParent(), RemoveFromReverseMap(), llvm::CallGraph::removeFunctionFromModule(), llvm::orc::JITDylib::removeGenerator(), removeImplicitFallthroughs(), llvm::PHINode::removeIncomingValue(), llvm::VPPhiAccessors::removeIncomingValueFor(), removeInf(), RemoveInstInputs(), llvm::InstructionPrecedenceTracking::removeInstruction(), llvm::MemoryDependenceResults::removeInstruction(), slpvectorizer::BoUpSLP::removeInstructionsAndOperands(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdges(), llvm::orc::ExecutionSession::removeJITDylibs(), llvm::StringMapImpl::RemoveKey(), llvm::StringMapImpl::RemoveKey(), llvm::cl::parser< DataType >::removeLiteralOption(), llvm::MachineBasicBlock::removeLiveIn(), llvm::LoopInfoBase< BasicBlock, Loop >::removeLoop(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::rdf::CodeNode::removeMember(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::ImutAVLFactory< ImutInfo >::removeMinBinding(), llvm::SCCPSolver::removeNonFeasibleEdges(), llvm::CallGraphNode::removeOneAbstractEdgeTo(), llvm::MachineInstr::removeOperand(), llvm::LazyCallGraph::RefSCC::removeOutgoingEdge(), llvm::CallBase::removeParamAttr(), llvm::CallBase::removeParamAttr(), llvm::MachineInstr::removePHIIncomingValueFor(), llvm::orc::LinkGraphLinkingLayer::removePlugin(), llvm::ScalarEvolution::removePointerBase(), RemovePreallocated(), llvm::SUnit::removePred(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::removeReady(), llvm::SchedBoundary::removeReady(), removeRedundantInsertVectorElt(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), llvm::LivePhysRegs::removeReg(), removeRegisterOperands(), llvm::mca::RegisterFile::removeRegisterWrite(), removeRegLanes(), llvm::MachineRegisterInfo::removeRegOperandFromUseList(), llvm::jitlink::LinkGraph::removeSection(), llvm::objcopy::elf::DynamicRelocationSection::removeSectionReferences(), llvm::LiveRange::removeSegment(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), llvm::RegionBase< Tr >::removeSubRegion(), llvm::MachineBasicBlock::removeSuccessor(), llvm::RewriteBuffer::RemoveText(), removeUndefDbgAssignsFromEntryBlock(), removeUndefDbgLocsFromEntryBlock(), llvm::removeUnreachableBlocks(), RemoveUnusedGlue(), llvm::LiveVariables::removeVirtualRegisterDead(), llvm::LiveVariables::removeVirtualRegisterKilled(), llvm::LiveVariables::removeVirtualRegistersKilled(), llvm::LiveIntervals::removeVRegDefAt(), llvm::MachineFunction::RenumberBlocks(), llvm::LiveRange::RenumberValues(), slpvectorizer::BoUpSLP::VLOperands::reorder(), slpvectorizer::BoUpSLP::reorderBottomToTop(), reorderOrder(), reorderReuses(), reorderScalars(), slpvectorizer::BoUpSLP::reorderTopToBottom(), ReorganizeVector(), llvm::SlotIndexes::repairIndexesInRange(), llvm::RegBankSelect::RepairingPlacement::RepairingPlacement(), llvm::RegBankSelect::repairReg(), repeat(), replace(), replaceAccess(), ReplaceAddWithADDP(), llvm::replaceAllDbgUsesWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::MDNode::replaceAllUsesWith(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::sandboxir::Value::replaceAllUsesWith(), llvm::replaceAndRecursivelySimplify(), llvm::DIExpression::replaceArg(), replaceArgumentUses(), ReplaceATOMIC_LOAD_128Results(), replaceAtomicSwap128(), replaceBoolVectorBitcast(), replaceBranchTargets(), llvm::X86InstrInfo::replaceBranchWithTailCall(), replaceCalledFunction(), llvm::CallGraphNode::replaceCallEdge(), llvm::LoopBase< BlockT, LoopT >::replaceChildLoopWith(), llvm::LoopBase< BasicBlock, Loop >::replaceChildLoopWith(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceCMP_XCHG_128Results(), replaceConstants(), ReplaceCopyFromReg_128(), replaceCoroEndAsync(), llvm::replaceCreatedSSACopys(), llvm::replaceDbgDeclare(), replaceDominatedUsesWith(), llvm::InstCombinerImpl::replacedSelectWithOperand(), llvm::HexagonMCInstrInfo::replaceDuplex(), llvm::DICompositeType::replaceElements(), llvm::DIMacroFile::replaceElements(), llvm::coro::BaseCloner::replaceEntryBlock(), llvm::RegionBase< Tr >::replaceExit(), replaceFallthroughCoroEnd(), replaceFoldableUses(), replaceFrameIndex(), llvm::MBBReachingDefsInfo::replaceFront(), llvm::PHINode::replaceIncomingBlockWith(), llvm::sandboxir::PHINode::replaceIncomingBlockWith(), llvm::GlobalVariable::replaceInitializer(), llvm::orc::JITDylib::replaceInLinkOrder(), llvm::PPCInstrInfo::replaceInstrOperandWithImm(), llvm::CombinerHelper::replaceInstWithConstant(), llvm::CombinerHelper::replaceInstWithConstant(), llvm::CombinerHelper::replaceInstWithFConstant(), llvm::CombinerHelper::replaceInstWithFConstant(), llvm::ReplaceInstWithInst(), llvm::CombinerHelper::replaceInstWithUndef(), ReplaceINTRINSIC_W_CHAIN(), replaceLoadVector(), replaceLoopInvariantUses(), replaceLoopPHINodesWithPreheaderValues(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::MachineJumpTableInfo::ReplaceMBBInJumpTable(), llvm::MachineJumpTableInfo::ReplaceMBBInJumpTables(), llvm::CallGraphSCC::ReplaceNode(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::LazyCallGraph::RefSCC::replaceNodeFunction(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::replaceNonLocalUsesWith(), llvm::ConstantUniqueMap< ConstantArray >::replaceOperandsInPlace(), llvm::CombinerHelper::replaceRegOpWith(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::coro::BaseCloner::replaceRetconOrAsyncSuspendUses(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::DILexicalBlockBase::replaceScope(), llvm::objcopy::elf::Object::replaceSections(), llvm::replaceSignedInst(), llvm::CombinerHelper::replaceSingleDefInstWithOperand(), llvm::CombinerHelper::replaceSingleDefInstWithReg(), llvm::MachineBasicBlock::replaceSuccessor(), replaceSwiftErrorOps(), llvm::replaceSymbolicStrideSCEV(), replaceTargetsFromPHINode(), llvm::codeview::AppendingTypeTableBuilder::replaceType(), llvm::codeview::GlobalTypeTableBuilder::replaceType(), llvm::codeview::MergingTypeTableBuilder::replaceType(), llvm::Constant::replaceUndefsWith(), replaceUsersOfGlobal(), llvm::MachineBasicBlock::ReplaceUsesOfBlockWith(), llvm::sandboxir::Value::replaceUsesWithIf(), llvm::DistinctMDOperandPlaceholder::replaceUseWith(), llvm::BitcodeReaderValueList::replaceValueWithoutRAUW(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::DbgVariableRecord::replaceVariableLocationOp(), llvm::DbgVariableRecord::replaceVariableLocationOp(), replaceWithCallToVeclib(), replaceWithIndirectUse(), replaceWithTileLoad(), llvm::VPlanTransforms::replicateByVF(), replicateMask(), reportErrors(), reportOverlappingBinding(), llvm::CodeGenPassBuilder< AMDGPUCodeGenPassBuilder, GCNTargetMachine >::requireCGSCCOrder(), llvm::InterleaveGroup< InstTy >::requiresScalarEpilogue(), llvm::SIFrameLowering::requiresStackPointerReference(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::reserve(), llvm::SectionMemoryManager::reserveAllocationSpace(), llvm::LoopBase< BlockT, LoopT >::reserveBlocks(), llvm::mca::ResourceState::reserveBuffer(), llvm::mca::ResourceManager::reserveBuffers(), reservePreviousStackSlotForValue(), reservePrivateMemoryRegs(), llvm::MachineRegisterInfo::reserveReg(), llvm::mca::ResourceManager::reserveResource(), llvm::StatepointLoweringState::reserveStackSlot(), llvm::BitVector::reset(), llvm::CoalescingBitVector< IndexT >::reset(), llvm::SchedBoundary::reset(), llvm::SmallBitVector::reset(), llvm::VPTransformState::reset(), llvm::VPTransformState::reset(), llvm::AllocatorList< T, BumpPtrAllocator >< Addend >::resetAlloc(), llvm::DebugValueUser::resetDebugValue(), llvm::MachineFunction::resetDelegate(), llvm::MachineRegisterInfo::resetDelegate(), llvm::SCCPInstVisitor::resetLatticeValueFor(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::resetSecLayout(), llvm::VPlan::resetTripCount(), resetVRegCycle(), llvm::MDNode::resize(), llvm::MDNode::resolve(), llvm::object::resolveAmdgpu(), llvm::object::resolveARM(), llvm::MDNode::resolveCycles(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::RISCVRegisterInfo::resolveFrameIndex(), llvm::SIRegisterInfo::resolveFrameIndex(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::logicalview::LVElement::resolveFullname(), resolveFwdRef(), llvm::BitsInit::resolveReferences(), llvm::RuntimeDyldCOFFAArch64::resolveRelocation(), llvm::RuntimeDyldCOFFI386::resolveRelocation(), llvm::RuntimeDyldCOFFThumb::resolveRelocation(), llvm::RuntimeDyldCOFFX86_64::resolveRelocation(), llvm::RuntimeDyldMachOAArch64::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), llvm::RuntimeDyldMachOX86_64::resolveRelocation(), llvm::TargetSchedModel::resolveSchedClass(), resolveSources(), resolveTargetShuffleFromZeroables(), llvm::orc::LazyCallThroughManager::resolveTrampolineLandingAddress(), llvm::resolveTypes(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::TargetFrameLowering::restoreCalleeSavedRegister(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::AVRFrameLowering::restoreCalleeSavedRegisters(), llvm::CSKYFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::GCNIterativeScheduler::OverrideLegacyStrategy::restoreOrder(), restorePreTransformState(), RestoreSpillList(), llvm::objcopy::elf::Section::restoreSymTabLink(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::CCState::resultsCompatible(), llvm::ARM::WinEH::RuntimeFunction::Ret(), llvm::DIBuilder::retainType(), llvm::mca::Instruction::retire(), llvm::mca::RetireControlUnit::RetireControlUnit(), llvm::MetadataTracking::retrack(), returnEdge(), llvm::LoopBase< BlockT, LoopT >::reverseBlock(), llvm::ARCInstrInfo::reverseBranchCondition(), llvm::AVRInstrInfo::reverseBranchCondition(), llvm::CSKYInstrInfo::reverseBranchCondition(), llvm::HexagonInstrInfo::reverseBranchCondition(), llvm::LanaiInstrInfo::reverseBranchCondition(), llvm::LoongArchInstrInfo::reverseBranchCondition(), llvm::MipsInstrInfo::reverseBranchCondition(), llvm::MSP430InstrInfo::reverseBranchCondition(), llvm::PPCInstrInfo::reverseBranchCondition(), llvm::RISCVInstrInfo::reverseBranchCondition(), llvm::SparcInstrInfo::reverseBranchCondition(), llvm::SystemZInstrInfo::reverseBranchCondition(), llvm::WebAssemblyInstrInfo::reverseBranchCondition(), llvm::X86InstrInfo::reverseBranchCondition(), llvm::XCoreInstrInfo::reverseBranchCondition(), llvm::XtensaInstrInfo::reverseBranchCondition(), llvm::HexagonInstrInfo::reversePrediction(), llvm::sandboxir::Tracker::revert(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::SSAUpdaterBulk::RewriteAllUses(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteLoopExitValues(), rewriteMaterializableInstructions(), rewriteMemOpOfSelect(), rewriteP2Align(), rewritePHINodesForExitAndUnswitchedBlocks(), rewritePHINodesForUnswitchedExitBlock(), rewritePHIs(), rewriteSelectInstMemOps(), llvm::rewriteT2FrameIndex(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), llvm::RISCVMachineFunctionInfo::RISCVMachineFunctionInfo(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::RNSuccIterator(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::RNSuccIterator(), llvm::RopePieceBTree::RopePieceBTree(), llvm::APInt::roundToDouble(), llvm::detail::DoubleAPFloat::roundToIntegral(), llvm::detail::IEEEFloat::roundToIntegral(), llvm::AMDGPUISelDAGToDAGPass::run(), llvm::BitTracker::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::CtxProfAnalysis::run(), llvm::DAGTypeLegalizer::run(), llvm::DevirtSCCRepeatedPass::run(), llvm::DominatorTreeVerifierPass::run(), llvm::DXILResourceAccess::run(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::FunctionSpecializer::run(), llvm::FunctionToLoopPassAdaptor::run(), llvm::GCFunctionAnalysis::run(), llvm::GenericCycleInfoCompute< ContextT >::run(), llvm::GVNPass::run(), llvm::InlinerPass::run(), llvm::InstCombinerImpl::run(), llvm::IR2VecPrinterPass::run(), llvm::IR2VecVocabPrinterPass::run(), llvm::JumpTableToSwitchPass::run(), llvm::JumpThreadingPass::run(), llvm::KCFIPass::run(), llvm::LoadAndStorePromoter::run(), llvm::LoopBoundSplitPass::run(), llvm::LoopConstrainer::run(), llvm::mca::Pipeline::run(), llvm::MemProfContextDisambiguation::run(), llvm::MemProfilerPass::run(), llvm::MemProfRemoveInfo::run(), llvm::ModuleInlinerPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::orc::CtorDtorRunner::run(), llvm::orc::MaterializationTask::run(), llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run(), llvm::PGOCtxProfFlatteningPass::run(), llvm::rdf::CopyPropagation::run(), llvm::ReassociatePass::run(), llvm::RegUsageInfoCollectorPass::run(), llvm::RegUsageInfoPropagationPass::run(), llvm::SIMemoryLegalizerPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::StackProtectorPass::run(), llvm::TargetIRAnalysis::run(), llvm::ThinLTOCodeGenerator::run(), llvm::WholeProgramDevirtPass::run(), ObjCARCContract::run(), runAttributorOnFunctions(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::JumpThreadingPass::runImpl(), llvm::PlaceSafepointsPass::runImpl(), runImpl(), runImpl(), runImpl(), runIPSCCP(), llvm::LPPassManager::runOnFunction(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::sandboxir::SeedCollection::runOnFunction(), llvm::StackProtector::runOnFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::AMDGPUDAGToDAGISelLegacy::runOnMachineFunction(), llvm::CFIFixup::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::MIR2VecPrinterLegacyPass::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), runOnMF(), llvm::sandboxir::BottomUpVec::runOnRegion(), runOpWithExpandOnOverflow(), runPass(), llvm::CrashRecoveryContext::RunSafely(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA(), RunTermFold(), llvm::RuntimeDyldCOFF::RuntimeDyldCOFF(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithLoopNestPasses(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, Sizer::BranchSize, Traits >::safeFind(), llvm::IntervalMapImpl::LeafNode< KeyT, ValT, Sizer::LeafSize, Traits >::safeFind(), llvm::MachineFunction::salvageCopySSA(), llvm::MachineFunction::salvageCopySSAImpl(), salvageDbgAssignAddress(), llvm::salvageDebugInfo(), llvm::SelectionDAG::salvageDebugInfo(), llvm::salvageDebugInfoForDbgValues(), salvageDebugInfoFromEmptyBlock(), SalvageDVI(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), SameSignRange::SameSignRange(), llvm::sampleprof::SampleContext::SampleContext(), llvm::sampleprof::SampleContext::SampleContext(), llvm::sampleprof::SampleContext::SampleContext(), llvm::SampleContextTracker::SampleContextTracker(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::SampleProfileReaderItaniumRemapper(), llvm::ThreadSafeTrieRawHashMapBase::ImplType::save(), saveFilteredNewMIBNodes(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveNamespaceRecord(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveTypeRecord(), scalarizeExtEltFP(), llvm::TargetLowering::scalarizeExtractedVectorLoad(), scalarizeInstruction(), scalarizeMaskedScatter(), scalarizeMaskedVectorHistogram(), llvm::LegalizerHelper::scalarizeVectorBooleanStore(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::LLT::scalarOrVector(), llvm::detail::scalbn(), llvm::InstrProfRecord::scale(), scale(), llvm::ir2vec::Embedding::scaleAndAdd(), llvm::APIntOps::ScaleBitMask(), llvm::scaleBranchCount(), llvm::scaleProfData(), scaleShuffleElements(), llvm::scaleShuffleMaskElts(), scanOneBB(), scavengeFrameVirtualRegsInBlock(), llvm::RegScavenger::scavengeRegisterBackwards(), scavengeVReg(), llvm::scc_member_iterator< GraphT, GT >::scc_member_iterator(), llvm::SCEVComparePredicate::SCEVComparePredicate(), llvm::SCEVMinMaxExpr::SCEVMinMaxExpr(), llvm::SCEVSequentialMinMaxExpr::SCEVSequentialMinMaxExpr(), llvm::GCNIterativeScheduler::OverrideLegacyStrategy::schedule(), llvm::ScheduleDAGMI::schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::SIScheduleBlock::schedule(), llvm::SIScheduleDAGMI::schedule(), llvm::SwingSchedulerDAG::schedule(), llvm::VLIWMachineScheduler::schedule(), llvm::GCNIterativeScheduler::scheduleBest(), llvm::GCNIterativeScheduler::scheduleLegacyMaxOccupancy(), llvm::ScheduleDAGMILive::scheduleMI(), llvm::PMTopLevelManager::schedulePass(), llvm::GCNIterativeScheduler::scheduleRegion(), llvm::SDDbgValue::SDDbgValue(), llvm::SDep::SDep(), llvm::SDLoc::SDLoc(), llvm::SDNode::SDNode(), llvm::SDValue::SDValue(), SDValueToConstBool(), llvm::orc::MachOBuilder< MachOTraits >::Section::Section(), llvm::yaml::sectionMapping(), llvm::yaml::sectionMapping(), llvm::object::XCOFFObjectFile::sections32(), llvm::object::XCOFFObjectFile::sections64(), llvm::raw_fd_ostream::seek(), llvm::LiveRange::Segment::Segment(), llvm::orc::MachOBuilder< MachOTraits >::Segment::Segment(), llvm::AMDGPUDAGToDAGISel::Select(), llvm::RISCVDAGToDAGISel::Select(), llvm::AMDGPUInstructionSelector::select(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::RISCVDAGToDAGISel::SelectAddrRegImmLsb00000(), llvm::AMDGPUDAGToDAGISel::SelectBuildVector(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), selectConstantAddr(), selectCopy(), selectELFSectionForGlobal(), llvm::LoopVectorizationPlanner::selectEpilogueVectorizationFactor(), selectExplicitSectionGlobal(), llvm::HexagonDAGToDAGISel::SelectExtractSubvector(), llvm::HvxSelector::selectExtractSubvector(), selectI64ImmDirect(), selectIncomingValueForBlock(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::RISCVDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands(), llvm::InstructionSelect::selectInstr(), llvm::LoopVectorizationPlanner::selectInterleaveCount(), llvm::SplitEditor::selectIntv(), llvm::InstructionSelect::selectMachineFunction(), selectMergeValues(), SelectMSA3OpIntrinsic(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::RABasic::selectOrSplit(), llvm::FastISel::selectPatchpoint(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::RISCVDAGToDAGISel::selectScalarFPAsInt(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::RISCVDAGToDAGISel::selectSETCC(), llvm::RISCVDAGToDAGISel::selectSF_VC_X_SE(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::RISCVDAGToDAGISel::selectShiftMask(), llvm::HvxSelector::selectShuffle(), llvm::FastISel::selectStackmap(), llvm::EngineBuilder::selectTarget(), selectUnmergeValues(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::AMDGPUDAGToDAGISel::SelectVectorShuffle(), llvm::RISCVDAGToDAGISel::selectVLXSEG(), llvm::RISCVDAGToDAGISel::selectVSETVLI(), selectVSplatImmHelper(), llvm::RISCVDAGToDAGISel::selectVSXSEG(), selectWMMAModsNegAbs(), selectWMMAModsNegAbs(), llvm::RISCVDAGToDAGISel::selectXSfmmVSET(), separateNestedLoop(), llvm::orc::shared::SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableError >::serialize(), serializePublic(), llvm::serializeSectionKind(), llvm::StackMaps::serializeToStackMapSection(), llvm::memprof::serializeV3(), llvm::memprof::serializeV4(), llvm::BitVector::set(), llvm::BitVector::set(), llvm::CoalescingBitVector< IndexT >::set(), llvm::dwarf_linker::classic::PatchLocation::set(), llvm::FunctionLoweringInfo::set(), llvm::PointerSumType< TagT, MemberTs... >::set(), llvm::SmallBitVector::set(), llvm::SmallBitVector::set(), llvm::VPTransformState::set(), llvm::VPTransformState::set(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_allocation_range(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::detail::PtrUseVisitorBase::PtrInfo::setAborted(), llvm::LegacyLegalizerInfo::setAction(), llvm::OffloadEntriesInfoManager::OffloadEntryInfo::setAddress(), llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBit(), llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes(), llvm::GlobalAlias::setAliasee(), llvm::GlobalObject::setAlignment(), llvm::GlobalObject::setAlignment(), llvm::jitlink::Block::setAlignment(), llvm::object::coff_tls_directory< support::little32_t >::setAlignment(), llvm::jitlink::Block::setAlignmentOffset(), llvm::X86MachineFunctionInfo::setAMXProgModel(), llvm::CallLowering::setArgFlags(), llvm::CallBase::setArgOperand(), llvm::sandboxir::CallBase::setArgOperand(), llvm::cl::Option::setArgStr(), llvm::MachineInstr::setAsmPrinterFlag(), llvm::TargetLoweringBase::setAtomicLoadExtAction(), llvm::setAtomicSyncScopeID(), llvm::TargetLoweringBase::ArgListEntry::setAttributes(), llvm::sandboxir::Region::setAux(), llvm::TargetLibraryInfoImpl::setAvailableWithName(), llvm::RISCV::VSETVLIInfo::setAVL(), llvm::RISCV::VSETVLIInfo::setAVLRegDef(), llvm::MachineBasicBlock::setBBID(), llvm::wholeprogramdevirt::AccumBitVector::setBE(), llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBit(), llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBytes(), llvm::IntegerInclusiveInterval::setBegin(), llvm::MCSection::setBeginSymbol(), llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::APInt::setBit(), llvm::wholeprogramdevirt::AccumBitVector::setBit(), llvm::APInt::setBits(), llvm::APInt::setBitsWithWrap(), llvm::BlockFrequencyInfo::setBlockFreq(), llvm::BlockFrequencyInfoImplBase::setBlockFreq(), llvm::BlockFrequencyInfo::setBlockFreqAndScale(), llvm::orc::SimpleRemoteEPCServer::Setup::setBootstrapMapValue(), llvm::MIRProfileLoader::setBranchProbs(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::pdb::BulkPublic::setBucketIdx(), llvm::AsmLexer::setBuffer(), llvm::HexagonInstrInfo::setBundleNoShuf(), llvm::ISD::ArgFlagsTy::setByRefSize(), llvm::ISD::ArgFlagsTy::setByValSize(), llvm::CallBase::setCalledFunction(), llvm::InstrProfCallsite::setCallee(), llvm::IRSimilarity::IRInstructionData::setCalleeName(), llvm::Function::setCallingConv(), llvm::LoopVectorizationCostModel::setCallWideningDecision(), llvm::CatchReturnInst::setCatchPad(), llvm::CatchPadInst::setCatchSwitch(), llvm::MachineOperand::setCImm(), llvm::CleanupReturnInst::setCleanupPad(), llvm::GlobalVariable::setCodeModel(), llvm::MCCVLoc::setColumn(), llvm::MCDwarfLoc::setColumn(), llvm::MCSymbol::setCommon(), llvm::logicalview::LVReader::setCompileUnit(), llvm::TargetLoweringBase::setCondCodeAction(), llvm::BranchInst::setCondition(), setCondition(), llvm::IRBuilderBase::setConstrainedFPFunctionAttr(), llvm::jitlink::Block::setContent(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent(), llvm::sampleprof::SampleContext::setContext(), llvm::CoroIdInst::setCoroutineSelf(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::Check::FileCheckType::setCount(), llvm::vfs::InMemoryFileSystem::setCurrentWorkingDirectory(), llvm::mca::ResourceManager::setCustomStrategy(), LiveDebugValues::DbgValue::setDbgOpIDs(), llvm::MachineInstr::setDebugLoc(), llvm::MachineInstr::setDebugValueUndef(), llvm::MachinePassRegistry< PassCtorTy >::setDefault(), llvm::IRBuilderBase::setDefaultConstrainedExcept(), llvm::IRBuilderBase::setDefaultConstrainedRounding(), llvm::hlsl::rootsig::DescriptorTableClause::setDefaultFlags(), llvm::hlsl::rootsig::RootDescriptor::setDefaultFlags(), llvm::MachineFunction::setDelegate(), llvm::MCSymbolMachO::setDesc(), llvm::MemIntrinsicBase< Derived >::setDest(), llvm::MCOperand::setDFPImm(), llvm::GlobalValue::setDLLStorageClass(), llvm::MCFragment::setDwarfAddrDelta(), llvm::MCFragment::setDwarfLineDelta(), llvm::DWARFUnitHeader::setDWOId(), llvm::AMDGPUMachineFunction::setDynLDSAlign(), llvm::BranchProbabilityInfo::setEdgeProbability(), llvm::mca::WriteState::setEliminated(), llvm::IntegerInclusiveInterval::setEnd(), llvm::MCDwarfLineEntry::setEndLabel(), llvm::VPRegionBlock::setEntry(), llvm::InlineAsmIdentifierInfo::setEnum(), llvm::detail::PtrUseVisitorBase::PtrInfo::setEscaped(), llvm::detail::PtrUseVisitorBase::PtrInfo::setEscapedReadOnly(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setExecutionSession(), llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setExecutorProcessControl(), llvm::VPRegionBlock::setExiting(), llvm::setExplicitlyUnknownBranchWeightsIfProfiled(), llvm::MCOperand::setExpr(), llvm::AtomicCmpXchgInst::setFailureOrdering(), llvm::orc::BloomFilterBuilder::setFalsePositiveRate(), llvm::MachineInstr::setFlag(), llvm::SIMachineFunctionInfo::setFlag(), llvm::MachineInstr::setFlags(), llvm::MCDwarfLoc::setFlags(), llvm::MCSymbol::setFlags(), llvm::ModuleSummaryIndex::setFlags(), llvm::pdb::BulkPublic::setFlags(), llvm::SCEVWrapPredicate::setFlags(), llvm::MachineOperand::setFPImm(), llvm::MCOperand::setFPImm(), llvm::MCSymbol::setFragment(), llvm::X86InstrInfo::setFrameAdjustment(), llvm::SIMachineFunctionInfo::setFrameOffsetReg(), llvm::MIRProfileLoader::setFSPass(), llvm::SwiftErrorValueTracking::setFunction(), llvm::MCContext::setGenDwarfRootFile(), llvm::GlobalObject::setGlobalObjectSubClassData(), llvm::GlobalValue::setGlobalValueSubClassData(), SVEIntrinsicInfo::setGoverningPredicateOperandIdx(), llvm::jitlink::COFFLinkGraphBuilder::setGraphBlock(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::setGraphBlock(), llvm::jitlink::COFFLinkGraphBuilder::setGraphSymbol(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::setGraphSymbol(), llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::setID(), llvm::DomTreeNodeBase< BlockT >::setIDom(), llvm::MachineOperand::setImm(), llvm::MCOperand::setImm(), llvm::R600InstrInfo::setImmOperand(), llvm::MachineOperand::setImplicit(), SVEIntrinsicInfo::setInactiveLanesAreNotDefined(), SVEIntrinsicInfo::setInactiveLanesAreUnused(), llvm::MemoryPhi::setIncomingBlock(), llvm::MemoryPhi::setIncomingValue(), llvm::PHINode::setIncomingValue(), llvm::PHINode::setIncomingValueForBlock(), llvm::InstrProfCntrInstBase::setIndex(), llvm::MachineOperand::setIndex(), setInfoSVEStN(), llvm::GlobalVariable::setInitializer(), llvm::cl::list< std::string, DebugCounter >::setInitialValues(), llvm::HexagonMCInstrInfo::setInnerLoop(), setInsertionPoint(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SCEVExpander::setInsertPoint(), llvm::VPBuilder::setInsertPoint(), llvm::MachineIRBuilder::setInsertPt(), llvm::MCFragment::setInst(), llvm::MCOperand::setInst(), llvm::MachineIRBuilder::setInstr(), llvm::SUnit::setInstr(), llvm::MachineOperand::setInstrRefInstrIndex(), llvm::MachineOperand::setInstrRefOpIndex(), llvm::MachineOperand::setIntrinsicID(), llvm::sampleprof::FunctionSamples::setIRToProfileLocationMap(), llvm::MCDwarfLoc::setIsa(), llvm::MachineFrameInfo::setIsAliasedObjectIndex(), llvm::MachineFrameInfo::setIsCalleeSavedObjectIndex(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsDebug(), llvm::MachineOperand::setIsDef(), llvm::MachineOperand::setIsEarlyClobber(), llvm::MachineFrameInfo::setIsImmutableObjectIndex(), llvm::MachineOperand::setIsInternalRead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsRenamable(), llvm::MachineOperand::setIsUndef(), llvm::SCEVExpander::setIVIncInsertPos(), false::Chain::setKill(), setKnownBase(), llvm::InlineAsmIdentifierInfo::setLabel(), llvm::MCBoundaryAlignFragment::setLastFragment(), llvm::PMTopLevelManager::setLastUser(), llvm::SCCPInstVisitor::setLatticeValueForSpecializationArguments(), llvm::wholeprogramdevirt::AccumBitVector::setLE(), llvm::MCFragment::setLEBValue(), llvm::MemIntrinsicBase< Derived >::setLength(), setLimitsForBinOp(), llvm::SuffixTreeInternalNode::setLink(), llvm::jitlink::Symbol::setLinkage(), llvm::orc::JITDylib::setLinkOrder(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::setLoadStoreAlignment(), llvm::StatepointLoweringState::setLocation(), llvm::Loop::setLoopID(), setM0ToIndexFromSGPR(), llvm::VPBlendRecipe::setMask(), llvm::VPWidenMemoryRecipe::setMask(), SVEIntrinsicInfo::setMatchingIROpcode(), llvm::InlineAsm::Flag::setMatchingOp(), SVEIntrinsicInfo::setMatchingUndefIntrinsic(), llvm::MachineIRBuilder::setMBB(), llvm::MachineOperand::setMBB(), llvm::ISD::ArgFlagsTy::setMemAlign(), llvm::InlineAsm::Flag::setMemConstraint(), llvm::DwarfExpression::setMemoryLocationKind(), setMemoryPhiValueForBlock(), llvm::HexagonMCInstrInfo::setMemReorderDisabled(), llvm::Instruction::setMetadata(), llvm::MachineOperand::setMetadata(), llvm::Value::setMetadata(), llvm::SGPRSpillBuilder::setMI(), LiveDebugValues::MLocTracker::setMLoc(), llvm::LTOCodeGenerator::setModule(), llvm::HexagonMCExpr::setMustExtend(), llvm::HexagonMCExpr::setMustNotExtend(), llvm::jitlink::Block::setMutableContent(), llvm::DominatorTreeBase< BlockT, false >::setNewRoot(), llvm::mca::Stage::setNextInSequence(), llvm::SUnit::setNode(), llvm::sandboxir::InvokeInst::setNormalDest(), llvm::User::setNumHungOffUseOperands(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::MachineFrameInfo::setObjectOffset(), llvm::MachineFrameInfo::setObjectSExt(), llvm::MachineFrameInfo::setObjectSize(), llvm::MachineFrameInfo::setObjectSSPLayout(), llvm::MachineFrameInfo::setObjectZExt(), llvm::jitlink::Symbol::setOffset(), llvm::MachineOperand::setOffset(), llvm::MCSymbol::setOffset(), llvm::VPBlockBase::setOneSuccessor(), llvm::GVNExpression::BasicExpression::setOperand(), llvm::MDNode::setOperand(), llvm::NamedMDNode::setOperand(), llvm::sandboxir::User::setOperand(), llvm::User::setOperand(), SVEIntrinsicInfo::setOperandIdxInactiveLanesTakenFrom(), SVEIntrinsicInfo::setOperandIdxWithNoActiveLanes(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetPassConfig::setOpt(), llvm::LTOCodeGenerator::setOptLevel(), llvm::AtomicRMWInst::setOrdering(), llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::MCSymbolELF::setOther(), llvm::HexagonMCInstrInfo::setOuterLoop(), llvm::LoopBase< BlockT, LoopT >::setParentLoop(), llvm::FuncletPadInst::setParentPad(), llvm::ProfileSummary::setPartialProfileRatio(), llvm::TargetLoweringBase::setPartialReduceMLAAction(), llvm::MCSectionWasm::setPassive(), llvm::sandboxir::PassManager< ParentPass, ContainedPass >::setPassPipeline(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::objcopy::macho::RelocationInfo::setPlainRelocationSymbolNum(), llvm::VPBlockBase::setPlan(), llvm::SCEVExpander::setPostInc(), llvm::rdf::PhiUseNode::setPredecessor(), llvm::VPBlockBase::setPredecessors(), llvm::MachineOperand::setPredicate(), llvm::VPIRFlags::setPredicate(), llvm::setProbeDistributionFactor(), llvm::RuntimeDyld::setProcessAllSections(), llvm::DbgVariableRecord::setRawLocation(), llvm::ValueInfo::setReadOnly(), llvm::StableFunctionMapRecord::setReadStableFunctionMapNames(), llvm::VPRecipeBuilder::setRecipe(), llvm::PBQP::RegAlloc::NodeMetadata::setReductionState(), llvm::logicalview::LVSymbol::setReference(), llvm::MCOperand::setReg(), llvm::SDep::setReg(), llvm::MachineRegisterInfo::setRegAllocationHint(), llvm::MipsRegisterBankInfo::setRegBank(), llvm::InlineAsm::Flag::setRegClass(), llvm::MachineRegisterInfo::setRegClass(), llvm::CoalescerPair::setRegisters(), llvm::MachineOperand::setRegMask(), llvm::InlineAsm::Flag::setRegMayBeFolded(), llvm::rdf::RefNode::setRegRef(), llvm::rdf::RefNode::setRegRef(), setRegsToType(), llvm::MCSymbolXCOFF::setRepresentedCsect(), llvm::ARCFunctionInfo::setReturnStackOffset(), llvm::XCoreFunctionInfo::setReturnStackOffset(), llvm::object::Elf_Rel_Impl< ELFType< Endianness, false >, false >::setRInfo(), llvm::SelectionDAG::setRoot(), llvm::jitlink::Symbol::setScope(), llvm::SIMachineFunctionInfo::setScratchRSrcReg(), llvm::DIEUnit::setSection(), llvm::MCSectionCOFF::setSelection(), llvm::MCOperand::setSFPImm(), llvm::MCFragment::setSFrameAddrDelta(), llvm::MCFragment::setSFrameFDE(), setShiftFlags(), llvm::DomainValue::setSingleDomain(), llvm::GenericCycle< ContextT >::setSingleEntry(), llvm::jitlink::Symbol::setSize(), llvm::PBQP::Graph< RegAllocSolverImpl >::setSolver(), llvm::MemTransferBase< BaseCL >::setSource(), llvm::X86InstrInfo::setSpecialOperandAttr(), setSpecialRefs(), llvm::AArch64FunctionInfo::setStackHazardCSRSlotIndex(), llvm::AArch64FunctionInfo::setStackHazardSlotIndex(), llvm::MachineFrameInfo::setStackID(), llvm::SIMachineFunctionInfo::setStackPtrOffsetReg(), llvm::AArch64FunctionInfo::setStackSizeSVE(), llvm::ModuloSchedule::setStage(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStop(), llvm::Type::setSubclassData(), llvm::MachineOperand::setSubReg(), llvm::DwarfExpression::setSubRegisterPiece(), llvm::BranchInst::setSuccessor(), llvm::CallBrInst::setSuccessor(), llvm::CatchReturnInst::setSuccessor(), llvm::CatchSwitchInst::setSuccessor(), llvm::InvokeInst::setSuccessor(), llvm::sandboxir::BranchInst::setSuccessor(), llvm::sandboxir::CatchSwitchInst::setSuccessor(), llvm::sandboxir::InvokeInst::setSuccessor(), llvm::SwitchInst::setSuccessor(), llvm::AtomicCmpXchgInst::setSuccessOrdering(), llvm::VPBlockBase::setSuccessors(), llvm::MachineBasicBlock::setSuccProbability(), llvm::AArch64FunctionInfo::setSVECalleeSavedStackSize(), llvm::LoopVectorizationCostModel::setTailFoldingStyles(), llvm::LoongArchTargetStreamer::setTargetABI(), llvm::RISCVTargetStreamer::setTargetABI(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setTargetAddress(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::jitlink::Symbol::setTargetFlags(), llvm::MachineOperand::setTargetFlags(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setTargetFlags(), llvm::MCAsmParser::setTargetParser(), llvm::GlobalValue::setThreadLocalMode(), llvm::X86Operand::setTokenValue(), llvm::LLVMContextImpl::setTrailingDbgRecords(), llvm::VPlan::setTripCount(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::VPBlockBase::setTwoSuccessors(), llvm::VPlan::setUF(), llvm::TargetLibraryInfo::setUnavailable(), llvm::VPValue::setUnderlyingValue(), llvm::SparseMultiSet< PhysRegSUOper, MCRegUnit, MCRegUnitToIndex, uint16_t >::setUniverse(), llvm::SparseSet< MCPhysReg, MCPhysReg >::setUniverse(), llvm::SelectionDAGBuilder::setUnusedArgValue(), llvm::CatchSwitchInst::setUnwindDest(), llvm::CleanupReturnInst::setUnwindDest(), llvm::sandboxir::InvokeInst::setUnwindDest(), setupBranchForGuard(), llvm::AsmPrinter::SetupMachineFunction(), llvm::sandboxir::SeedBundle::setUsed(), llvm::sandboxir::SeedBundle::setUsed(), llvm::MemSetBase< BaseCL >::setValue(), llvm::RecordVal::setValue(), llvm::SelectionDAGBuilder::setValue(), llvm::SwitchInst::CaseHandle::setValue(), llvm::InlineAsmIdentifierInfo::setVar(), llvm::MCFragment::setVarFixups(), llvm::MCSymbol::setVariableValue(), llvm::LoopVectorizationCostModel::setVectorizedCallDecision(), llvm::VFABI::setVectorVariantNames(), llvm::VPlan::setVF(), llvm::VPReductionPHIRecipe::setVFScaleFactor(), llvm::GlobalValue::setVisibility(), llvm::MCSymbolELF::setVisibility(), llvm::object::Elf_Sym_Impl< ELFType< E, Is64 > >::setVisibility(), llvm::RegisterBankInfo::OperandsMapper::setVRegs(), llvm::GlobalVarSummary::setVTableFuncs(), llvm::RISCV::VSETVLIInfo::setVTYPE(), llvm::RISCV::VSETVLIInfo::setVTYPE(), llvm::WebAssemblyFunctionInfo::setWAReg(), llvm::jitlink::Symbol::setWeaklyReferenced(), llvm::setWidenableBranchCond(), llvm::LoopVectorizationCostModel::setWideningDecision(), llvm::LoopVectorizationCostModel::setWideningDecision(), llvm::ValueInfo::setWriteOnly(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setZeroFill(), llvm::APInt::sext(), llvm::KnownBits::sextInReg(), llvm::SExtInst::SExtInst(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), shiftRightAndRound(), llvm::TargetMachine::shouldAssumeDSOLocal(), shouldClusterFI(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), llvm::SystemZRegisterInfo::shouldCoalesce(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::ARMTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::HexagonTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::PPCTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::X86TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::GISelCSEInfo::shouldCSE(), llvm::TargetLoweringObjectFileXCOFF::ShouldEmitEHBlock(), llvm::shouldEmitPTXNoReturn(), llvm::AArch64TargetLowering::shouldExpandAtomicRMWInIR(), llvm::NVPTXTargetLowering::shouldExpandAtomicRMWInIR(), shouldFoldCondBranchesToCommonDestination(), llvm::AArch64TargetLowering::shouldFoldConstantShiftPairToMask(), llvm::ARMTargetLowering::shouldFoldConstantShiftPairToMask(), llvm::MipsTargetLowering::shouldFoldConstantShiftPairToMask(), llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask(), shouldFullUnroll(), llvm::shouldFuncOptimizeForSizeImpl(), shouldInsertFreeze(), llvm::BlockCoverageInference::shouldInstrumentBlock(), llvm::AArch64TTIImpl::shouldMaximizeVectorBandwidth(), llvm::shouldOptimizeForSize(), llvm::shouldOptimizeForSize(), llvm::shouldOptimizeForSize(), llvm::AArch64TargetLowering::shouldReduceLoadWidth(), llvm::X86TargetLowering::shouldReduceLoadWidth(), llvm::PPCInstrInfo::shouldReduceRegisterPressure(), shouldRewriteStatepointsIn(), llvm::OptPassGateInstrumentation::shouldRun(), llvm::OptBisect::shouldRunPass(), llvm::OptDisable::shouldRunPass(), llvm::ARMBaseInstrInfo::shouldScheduleLoadsNear(), llvm::SIInstrInfo::shouldScheduleLoadsNear(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), ShouldSignWithBKey(), shouldSplit(), shouldSplitOnPredicatedArgument(), llvm::MachineRegisterInfo::shouldTrackSubRegLiveness(), shouldTryInjectBasingOnMetadata(), shouldUseFrameHelper(), shouldUseMmap(), ShrinkDemandedConstant(), llvm::TargetLowering::ShrinkDemandedOp(), shrinkInsertElt(), llvm::BitcodeReaderValueList::shrinkTo(), llvm::LiveIntervals::shrinkToUses(), llvm::LiveIntervals::shrinkToUses(), llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ConstantRange::signExtend(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), llvm::SimpleDDGNode::SimpleDDGNode(), llvm::SimpleDDGNode::SimpleDDGNode(), llvm::SimpleDDGNode::SimpleDDGNode(), llvm::codeview::TypeIndex::simpleTypeName(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifyAMDGCNImageIntrinsic(), simplifyAndOrWithICmpEq(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), llvm::InstCombinerImpl::SimplifyAnyMemTransfer(), simplifyAssociativeBinOp(), llvm::simplifyBinaryIntrinsic(), simplifyBranchConditionForVFAndUF(), llvm::simplifyCall(), SimplifyCondBranchToCondBranch(), llvm::simplifyConstrainedFPCall(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyDemandedBitsForPRMT(), llvm::TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TTIImpl::simplifyDemandedVectorEltsIntrinsic(), simplifyExtractValueInst(), simplifyFCmpInst(), simplifyFunctionCFG(), simplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyInstructionWithOperands(), simplifyInstructionWithOperands(), simplifyIntrinsic(), simplifyLCSSAPhis(), simplifyLogicOfAddSub(), llvm::simplifyLoop(), simplifyLoopInst(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyNestedSelectsUsingImpliedCond(), simplifyOneLoop(), simplifyOp_VL(), simplifyOrLogic(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), simplifyRecipe(), simplifyRelocatesOffABase(), simplifySelectInst(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), simplifyShift(), simplifyShiftSelectingPackedElement(), simplifyShuffleOfShuffle(), simplifyShuffleVectorInst(), simplifySuspendPoints(), simplifySVEIntReduction(), simplifySVEIntrinsicBinOp(), simplifySwitchLookup(), simplifySwitchOfCmpIntrinsic(), simplifyTernarylogic(), simplifyWasmSwizzle(), simplifyWithOpsReplaced(), simplifyX86addcarry(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86pack(), simplifyX86pmadd(), simplifyX86pmulh(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86VPERMMask(), simplifyX86vpermv(), simplifyX86vpermv3(), singleLetterExtensionRank(), sink(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), sinkCommonCodeFromPredecessors(), SinkInstruction(), sinkInstruction(), sinkLastInstruction(), sinkLifetimeStartMarkers(), sinkLoopInvariantInstructions(), sinkMinMaxInBB(), sinkRecurrenceUsersAfterPrevious(), llvm::sinkRegion(), SinkShiftAndTruncate(), sinkThroughTriviallyReplaceablePHI(), llvm::SIRegisterInfo::SIRegisterInfo(), llvm::SIToFPInst::SIToFPInst(), llvm::GFConstant::size(), llvm::orc::shared::SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableError >::size(), llvm::orc::shared::WrapperFunctionBuffer::size(), llvm::SparseMultiSet< PhysRegSUOper, MCRegUnit, MCRegUnitToIndex, uint16_t >::size(), llvm::sys::fs::mapped_file_region::size(), llvm::DIELocList::sizeOf(), llvm::DWARFDebugLine::SectionParser::skip(), llvm::yaml::skip(), skipAlignedDPRCS2Spills(), llvm::LoopNest::skipEmptyBlockUntil(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::codeview::CodeViewRecordIO::skipPadding(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::MachineBasicBlock::SkipPHIsLabelsAndDebug(), llvm::BitstreamCursor::skipRecord(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::slice(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::slice(), llvm::MutableArrayRef< char >::slice(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), slotForIndex(), llvm::SlotIndex::SlotIndex(), smallData(), llvm::SmallPtrSetImplBase::SmallPtrSetImplBase(), llvm::SMECallAttrs::SMECallAttrs(), llvm::SMFixIt::SMFixIt(), llvm::SMRange::SMRange(), llvm::TargetLowering::softenSetCCOperands(), solveDIType(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), llvm::SwitchCG::sortAndRangeify(), llvm::sortBasicBlocksAndUpdateBranches(), llvm::sortBlocks(), sortBlocks(), sortLocalVars(), llvm::AbstractDependenceGraphBuilder< GraphType >::sortNodesTopologically(), llvm::sortPtrAccesses(), llvm::Value::sortUseList(), speculateSelectInstLoads(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillEmergencySGPR(), spillIncomingStatepointValue(), llvm::RABasic::spillInterferences(), llvm::SIRegisterInfo::spillSGPR(), splatSplitI64WithVL(), llvm::spliceBB(), llvm::DominatorTreeBase< BlockT, false >::Split(), llvm::BinaryStreamReader::split(), llvm::BinaryStreamWriter::split(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), SplitAndExtendv16i1(), splitAndLowerShuffle(), llvm::VPBasicBlock::splitAt(), llvm::SITargetLowering::splitBinaryVectorOp(), llvm::jitlink::LinkGraph::splitBlock(), splitBlock(), llvm::SplitBlockAndInsertIfThenElse(), SplitBlockImpl(), SplitBlockPredecessorsImpl(), llvm::SplitCallBrEdge(), splitCallSite(), llvm::OutlinableRegion::splitCandidate(), llvm::coro::AnyRetconABI::splitCoroutine(), llvm::coro::AsyncABI::splitCoroutine(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SplitCriticalEdge(), llvm::SplitEdge(), splitEdge(), llvm::SelectionDAG::SplitEVL(), llvm::SIInstrInfo::splitFlatOffset(), splitGlobal(), llvm::SplitIndirectBrCriticalEdges(), llvm::ScalarEvolution::SplitIntoInitAndPostInc(), llvm::SplitKnownCriticalEdge(), SplitLandingPadPredecessorsImpl(), splitLiteralAndReplacement(), llvm::SplitEditor::splitLiveThroughBlock(), splitLoweredFatBufferConst(), splitMask(), splitMBB(), SplitOpsAndApply(), llvm::VETargetLowering::splitPackedLoadStore(), llvm::LiveDebugVariables::LDVImpl::splitPHIRegister(), splitPosNeg(), splitPredecessorsOfLoopExit(), llvm::AVRRegisterInfo::splitReg(), llvm::SplitEditor::splitRegInBlock(), llvm::SplitEditor::splitRegOutBlock(), llvm::SelectionDAG::SplitScalar(), splitStoreSplat(), SplitStrictFPVectorOp(), llvm::MachineBasicBlock::splitSuccessor(), llvm::SITargetLowering::splitTernaryVectorOp(), llvm::CallLowering::splitToValueTypes(), llvm::SITargetLowering::splitUnaryVectorOp(), splitUnequalType(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::SelectionDAG::SplitVector(), llvm::AMDGPUTargetLowering::splitVector(), splitVector(), splitVectorIntBinary(), splitVectorIntUnary(), llvm::VETargetLowering::splitVectorOp(), splitVectorStore(), SplitVPOp(), splitVSETCC(), llvm::APInt::sqrt(), SRAGlobal(), llvm::stableHashValue(), llvm::ARM::WinEH::RuntimeFunction::StackAdjust(), llvm::WebAssemblyFunctionInfo::stackifyVReg(), StackMallocSizeClass(), llvm::StackMapOpers::StackMapOpers(), llvm::StackMapParser< Endianness >::StackMapParser(), llvm::Register::stackSlotIndex(), llvm::IntervalMap< IndexT, char >::start(), llvm::rdf::DataFlowGraph::DefStack::start_block(), llvm::AggressiveAntiDepBreaker::StartBlock(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::FastISel::startNewBlock(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::Timer::startTimer(), llvm::CallGraphNode::stealCalledFunctionsFrom(), llvm::LivePhysRegs::stepForward(), StepOverPredicatedInstrs(), llvm::IntervalMap< IndexT, char >::stop(), llvm::CodeGenPassBuilder< AMDGPUCodeGenPassBuilder, GCNTargetMachine >::stopAddingInCGSCCOrder(), llvm::TGTimer::stopTimer(), llvm::Timer::stopTimer(), llvm::cas::ondisk::OnDiskGraphDB::store(), llvm::MDNode::storeDistinctInContext(), llvm::StoreIntToMemory(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::M68kInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), StrengthenNoWrapFlags(), strictCompare(), llvm::sampleprof::FunctionId::stringRef(), llvm::StringTable::StringTable(), stripAndComputeConstantOffsets(), stripDebugDeclareImpl(), llvm::stripDebugifyMetadata(), stripDebugLocFromLoopID(), stripLoopMDLoc(), stripNonValidData(), stripTrailingZeros(), stripValuesNotDefiningMask(), stripVRegCopies(), llvm::dwarf::SubOperationEncodingString(), llvm::BitTracker::subst(), llvm::MachineFunction::substituteDebugValuesForInst(), substituteSimpleCopyRegs(), llvm::MachineOperand::substPhysReg(), llvm::VarStreamArray< CVSymbol >::substream(), llvm::MachineOperand::substVirtReg(), llvm::PPCInstrInfo::SubsumesPredicate(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), llvm::APFloat::subtract(), llvm::ConstantRange::subtract(), llvm::ConstantRangeList::subtract(), llvm::mca::CycleSegment::subtract(), llvm::SuffixTree::SuffixTree(), supportedVectorShiftWithImm(), supportedVectorVarShift(), suppressEGPRRegClass(), llvm::SuspendCrossingInfo::SuspendCrossingInfo(), llvm::iplist_impl< IntrusiveListT, TraitsT >::swap(), llvm::SmallPtrSetImplBase::swap(), swapMIOperands(), llvm::VPUser::swapOperands(), llvm::sandboxir::User::swapOperandsInternal(), llvm::VPBlockBase::swapPredecessors(), llvm::SIInstrInfo::swapSourceModifiers(), llvm::BranchProbabilityInfo::swapSuccEdgesProbabilities(), llvm::BranchInst::swapSuccessors(), llvm::VPBlockBase::swapSuccessors(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToRef(), llvm::MCStreamer::switchSection(), llvm::RegBankSelect::RepairingPlacement::switchTo(), llvm::IRMover::IdentifiedStructTypeSet::switchToNonOpaque(), llvm::LazyCallGraph::RefSCC::switchTrivialInternalEdgeToRef(), llvm::object::SymbolRef::SymbolRef(), llvm::orc::SymbolsCouldNotBeRemoved::SymbolsCouldNotBeRemoved(), llvm::orc::SymbolsNotFound::SymbolsNotFound(), llvm::orc::SymbolsNotFound::SymbolsNotFound(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), llvm::SystemZHLASMAsmStreamer::SystemZHLASMAsmStreamer(), llvm::SystemZVectorConstantInfo::SystemZVectorConstantInfo(), llvm::SystemZVectorConstantInfo::SystemZVectorConstantInfo(), llvm::CGDataError::take(), llvm::InstrProfError::take(), llvm::hlsl::BindingInfoBuilder::takeBoundRegs(), llvm::vfs::OutputFile::takeImpl(), takeInexpensiveLog2(), llvm::ContextAndReplaceableUses::takeReplaceableUses(), targetParallelCallback(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::APInt::tcAdd(), llvm::APInt::tcDivide(), llvm::APInt::tcExtract(), llvm::APInt::tcFullMultiply(), llvm::APInt::tcMultiply(), llvm::APInt::tcMultiplyPart(), llvm::APInt::tcSet(), llvm::APInt::tcSubtract(), llvm::orc::COFFPlatform::teardownJITDylib(), llvm::orc::ELFNixPlatform::teardownJITDylib(), llvm::orc::MachOPlatform::teardownJITDylib(), llvm::CoalescingBitVector< IndexT >::test(), llvm::lto::thinBackend(), llvm::thinLTOFinalizeInModule(), llvm::thinLTOInternalizeAndPromoteInIndex(), llvm::thinLTOInternalizeModule(), threadBinOpOverPHI(), threadBinOpOverSelect(), threadCmpOverPHI(), threadCmpOverSelect(), llvm::JumpThreadingPass::threadEdge(), llvm::JumpThreadingPass::threadGuard(), llvm::orc::ThreadSafeContext::ThreadSafeContext(), llvm::ThreadSafeTrieRawHashMapBase::ThreadSafeTrieRawHashMapBase(), llvm::JumpThreadingPass::threadThroughTwoBasicBlocks(), llvm::MachineInstr::tieOperands(), tileConfig(), llvm::OpenMPIRBuilder::tileLoops(), llvm::Timer::Timer(), llvm::TimerGroup::TimerGroup(), llvm::timeTraceProfilerInitialize(), llvm::timeTraceProfilerWrite(), llvm::timeTraceProfilerWrite(), llvm::pdb::Variant::toAPFloat(), llvm::pdb::Variant::toAPSInt(), llvm::codeview::TypeIndex::toArrayIndex(), tocDataChecks(), llvm::CodeViewYAML::toCodeViewSubsectionList(), llvm::CodeViewYAML::toDebugH(), llvm::CodeViewYAML::toDebugT(), llvm::object::ELFObjectFile< ELF32LE >::toDRI(), toHexStr(), llvm::BitTracker::MachineEvaluator::toInt(), llvm::ScaledNumber< DigitsT >::toInt(), llvm::lsp::toJSON(), llvm::lsp::toJSON(), llvm::lsp::toJSON(), llvm::lsp::toJSON(), tokenizeWindowsCommandLineImpl(), llvm::orc::ExecutorAddr::toPtr(), llvm::toScalarizedStructTy(), llvm::APInt::toString(), llvm::detail::DoubleAPFloat::toString(), llvm::objcopy::elf::SRecord::toString(), toString(), toStringAPFloat(), llvm::objcopy::macho::MachOWriter::totalSize(), toUTF8(), llvm::toVectorizedStructTy(), llvm::sandboxir::Tracker::track(), llvm::at::trackAssignments(), llvm::vfs::OutputFile::TrackedProxy::TrackedProxy(), llvm::orc::ImplSymbolMap::trackImpls(), LiveDebugValues::MLocTracker::trackRegister(), llvm::ilist_base< enable_sentinel_tracking, parent_ty >::transferBeforeImpl(), llvm::SelectionDAG::transferDbgValues(), llvm::DeadLaneDetector::transferDefinedLanes(), TransferTracker::transferMlocs(), llvm::ilist_callback_traits< MachineBasicBlock >::transferNodesFromList(), llvm::DeadLaneDetector::transferUsedLanes(), transformCallee(), transformInitializer(), transformInitializer(), transformRecipestoEVLRecipes(), translateBranchMetadata(), translateDstIndex(), translateExtract(), translateShiftImm(), translateSrcIndex(), llvm::PHITransAddr::translateValue(), llvm::PBQP::Matrix::transpose(), llvm::LoopTraversal::traverse(), llvm::ReachingDefInfo::traverse(), traverseGEPOffsets(), llvm::ImmutableGraphBuilder< MachineGadgetGraph >::trim(), llvm::trimBlockToPageSize(), llvm::APInt::trunc(), llvm::const_iterator< MemoryLocation >::truncate(), llvm::ConstantRange::truncate(), truncateScalarIntegerArg(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), truncateToSize(), truncateVectorWithNARROW(), truncateVectorWithPACK(), llvm::TruncInst::TruncInst(), llvm::APInt::truncSSat(), llvm::APInt::truncUSat(), llvm::sampleprof::HashKeyMap< MapT, KeyT, ValueT, MapTArgs >::try_emplace(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::try_emplace_with_hash(), llvm::MCDisassembler::tryAddingPcLoadReferenceComment(), llvm::MCDisassembler::tryAddingSymbolicOperand(), tryARM64PackedUnwind(), tryARMPackedUnwind(), llvm::RegBankSelect::tryAvoidingSplit(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), llvm::GCNMaxMemoryClauseSchedStrategy::tryCandidate(), llvm::LegalizationArtifactCombiner::tryCombineAnyExt(), TryCombineBaseUpdate(), AMDGPURegBankLegalizeCombiner::tryCombineCopy(), tryCombineExtendRShTrunc(), llvm::LegalizationArtifactCombiner::tryCombineExtract(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), tryCombineLongOpWithDup(), llvm::LegalizationArtifactCombiner::tryCombineSExt(), llvm::LegalizationArtifactCombiner::tryCombineTrunc(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), llvm::HexagonMCInstrInfo::tryCompound(), tryCopyWithNegation(), llvm::AMDGPUDisassembler::tryDecodeInst(), llvm::VFABI::tryDemangleForVFABI(), llvm::AArch64GISelUtils::tryEmitBZero(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), tryFactorization(), llvm::LegalizationArtifactCombiner::tryFoldImplicitDef(), llvm::InstCombinerImpl::tryFoldInstWithCtpopWithNot(), tryFoldSelectIntoOp(), llvm::tryFoldSPUpdateIntoPushPop(), llvm::LegalizationArtifactCombiner::tryFoldUnmergeCast(), llvm::MCDwarfLineTableHeader::tryGetFile(), tryGetOriginalBoolVectorType(), tryGetSecondaryReductionRoot(), llvm::PGOIndirectCallVisitor::tryGetVTableInstruction(), llvm::RISCVDAGToDAGISel::tryIndexedLoad(), tryInterleave(), llvm::LockFileManager::tryLock(), tryLowerToBSL(), tryLowerToSLI(), tryOrrWithShift(), llvm::object::CompressedOffloadBundle::CompressedBundleHeader::tryParse(), llvm::tryPromoteCall(), llvm::sandboxir::Scheduler::trySchedule(), trySequenceOfOnes(), llvm::RISCVDAGToDAGISel::tryShrinkShlLogicImm(), trySwitchToSelect(), llvm::VPlanTransforms::tryToConvertVPInstructionsToVPRecipes(), llvm::VPRecipeBuilder::tryToCreatePartialReduction(), llvm::VPRecipeBuilder::tryToCreateWidenNonPhiRecipe(), tryToElideArgumentCopy(), tryToFoldExtendOfConstant(), tryToFoldExtendSelectLoad(), tryToFoldExtOfAtomicLoad(), tryToFoldExtOfLoad(), tryToFoldLiveIns(), llvm::FastISel::tryToFoldLoad(), llvm::orc::EPCDynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::ExecutorResolutionGenerator::tryToGenerate(), llvm::orc::ReexportsGenerator::tryToGenerate(), tryToMergeLandingPad(), tryToMergePartialOverlappingStores(), tryToMoveFreeBeforeNullTest(), tryToReplaceALMWithWideALM(), tryToShorten(), tryToShortenBegin(), tryToShortenEnd(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::InstCombinerImpl::tryToSinkInstructionDbgVariableRecords(), tryToUnrollLoop(), TryWideExtMulCombine(), turnToExplicitForm(), llvm::coverage::mcdc::TVIdxBuilder::TVIdxBuilder(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::Twine::Twine(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), llvm::RecTy::typeIsConvertibleTo(), llvm::codeview::TypeServer2Record::TypeServer2Record(), TypeSizeToSizeIndex(), TypeStoreSizeToSizeIndex(), llvm::APInt::udiv(), llvm::APInt::udiv(), llvm::APInt::udivrem(), llvm::APInt::udivrem(), llvm::UIToFPInst::UIToFPInst(), llvm::ulpsFromBoundary(), llvm::MachineInstr::unbundleFromPred(), llvm::MachineInstr::unbundleFromSucc(), undefInvalidDbgValues(), llvm::PotentialValuesState< APInt >::undefIsContained(), llvm::BitmaskEnumDetail::Underlying(), unescapeQuotedString(), llvm::sys::UnicodeCharSet::UnicodeCharSet(), unifyLoopExits(), llvm::AggressiveAntiDepState::UnionGroups(), llvm::EquivalenceClasses< BasicBlock * >::unionSets(), llvm::ConstantFPRange::unionWith(), llvm::ConstantRange::unionWith(), llvm::ConstantRangeList::unionWith(), llvm::pdb::InputFile::unknown(), llvm::pdb::InputFile::unknown(), llvm::sys::SmartMutex< false >::unlock(), llvm::sys::SmartRWMutex< false >::unlock(), llvm::sys::SmartRWMutex< false >::unlock_shared(), llvm::MemoryPhi::unorderedDeleteIncoming(), llvm::MemoryPhi::unorderedDeleteIncomingIf(), unpack64(), unpackF64OnLA32DSoftABI(), unpackF64OnRV32DSoftABI(), unpackV2S16ToS32(), llvm::AssumptionCache::unregisterAssumption(), llvm::sandboxir::Context::unregisterCreateInstrCallback(), llvm::sandboxir::Context::unregisterEraseInstrCallback(), llvm::orc::RTDyldObjectLinkingLayer::unregisterJITEventListener(), llvm::sandboxir::Context::unregisterMoveInstrCallback(), llvm::sandboxir::Context::unregisterSetUseCallback(), unrollAndJamCountPragmaValue(), llvm::UnrollAndJamLoop(), llvm::VPlanTransforms::unrollByUF(), unrollCountPragmaValue(), llvm::UnrollLoop(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::UnrollRuntimeLoopRemainder(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UnrollVectorOverflowOp(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue(), llvm::PBQP::Graph< RegAllocSolverImpl >::unsetSolver(), llvm::InstCombinerImpl::unshuffleConstant(), unsignedImmDecoder(), unswitchBestCondition(), unswitchLoop(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), llvm::MetadataTracking::untrack(), unwrapExprVar(), llvm::DWARFCFIAnalysis::update(), llvm::PGOContextualProfile::update(), llvm::SHA1::update(), llvm::SHA256::update(), UpdateAnalysisInformation(), updateAsyncFuncPointerContextSize(), updateBranchWeights(), llvm::PPCFrameLowering::updateCalleeSaves(), updateCGAndAnalysisManagerForPass(), llvm::Record::updateClassLoc(), UpdateCPSRUse(), llvm::MachineRegisterInfo::updateDbgUsersToReg(), UpdateDbgValue(), llvm::dwarf_linker::parallel::CompileUnit::updateDependenciesCompleteness(), llvm::dwarf_linker::parallel::DependencyTracker::updateDependenciesCompleteness(), llvm::MachineTraceMetrics::Ensemble::updateDepth(), llvm::DominatorTreeBase< BlockT, false >::updateDFSNumbers(), llvm::mca::Instruction::updateDispatched(), UpdatedOnX86AvoidTrailingCallPass(), updateDVIWithLocation(), updateDVIWithLocations(), llvm::MemorySSAUpdater::updateForClonedLoop(), llvm::AddrLabelMap::UpdateForDeletedBlock(), llvm::AddrLabelMap::UpdateForRAUWBlock(), updateGetPCBundle(), llvm::ExecutionEngine::updateGlobalMapping(), updateIDTMetaData(), llvm::updateIndexWPDForExports(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), llvm::PointerIntPairInfo< PointerT, IntBits, PtrTraits >::updateInt(), llvm::MachineJumpTableInfo::updateJumpTableEntryHotness(), updateLiveness(), updateLoadCommandPayloadString(), updateLoopMetadataDebugLocationsImpl(), updateLoopMetadataDebugLocationsRecursive(), updateMemprofMetadata(), llvm::SelectionDAG::UpdateNodeOperands(), llvm::SelectionDAG::UpdateNodeOperands(), llvm::SelectionDAG::UpdateNodeOperands(), llvm::HexagonPacketizerList::updateOffset(), updateOneDbgValueForAlloca(), updateOperandIfDifferent(), UpdateOperandRegClass(), updateOperands(), llvm::VFShape::updateParam(), llvm::mca::Instruction::updatePending(), llvm::updatePhiNodes(), llvm::orc::LocalIndirectStubsManager< TargetT >::updatePointer(), llvm::PointerIntPairInfo< PointerT, IntBits, PtrTraits >::updatePointer(), updatePostorderSequenceForEdgeInsertion(), llvm::ScheduleDAGMILive::updatePressureDiffs(), llvm::updateRegType(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), llvm::VPlanTransforms::updateScalarResumePhis(), llvm::WindowScheduler::updateScheduleResult(), llvm::objcopy::elf::Object::updateSectionData(), llvm::MachineFunction::VariableDbgInfo::updateStackSlot(), updateSubprogramLinkageName(), llvm::DwarfCompileUnit::updateSubprogramScopeDIE(), updateSuccessor(), llvm::MachineBasicBlock::updateTerminator(), upgradeAMDGCNIntrinsicCall(), upgradeArmOrAarch64IntrinsicFunction(), llvm::UpgradeCallsToIntrinsic(), upgradeDbgIntrinsicToDbgRecord(), llvm::UpgradeIntrinsicCall(), upgradeIntrinsicFunction1(), upgradeLoopTag(), llvm::UpgradeModuleFlags(), llvm::UpgradeNVVMAnnotations(), upgradeNVVMFnVectorAttr(), upgradeX86ALIGNIntrinsics(), upgradeX86IntrinsicCall(), llvm::APInt::urem(), llvm::APInt::urem(), llvm::AArch64RegisterInfo::useFPForScavengingIndex(), llvm::SplitEditor::useIntv(), llvm::SystemZTargetLowering::useLibCall(), llvm::User::User(), llvm::GCStrategy::useRS4GC(), useRVVForFixedLengthVectorVT(), usesExtendedRegister(), llvm::VPBlendRecipe::usesFirstLaneOnly(), llvm::VPCanonicalIVPHIRecipe::usesFirstLaneOnly(), llvm::VPDerivedIVRecipe::usesFirstLaneOnly(), llvm::VPEVLBasedIVPHIRecipe::usesFirstLaneOnly(), llvm::VPFirstOrderRecurrencePHIRecipe::usesFirstLaneOnly(), llvm::VPInstruction::usesFirstLaneOnly(), llvm::VPInterleaveEVLRecipe::usesFirstLaneOnly(), llvm::VPInterleaveRecipe::usesFirstLaneOnly(), llvm::VPIRInstruction::usesFirstLaneOnly(), llvm::VPReductionEVLRecipe::usesFirstLaneOnly(), llvm::VPReductionPHIRecipe::usesFirstLaneOnly(), llvm::VPReplicateRecipe::usesFirstLaneOnly(), llvm::VPScalarIVStepsRecipe::usesFirstLaneOnly(), llvm::VPUser::usesFirstLaneOnly(), llvm::VPVectorEndPointerRecipe::usesFirstLaneOnly(), llvm::VPVectorPointerRecipe::usesFirstLaneOnly(), llvm::VPWidenGEPRecipe::usesFirstLaneOnly(), llvm::VPWidenInductionRecipe::usesFirstLaneOnly(), llvm::VPWidenIntrinsicRecipe::usesFirstLaneOnly(), llvm::VPWidenLoadEVLRecipe::usesFirstLaneOnly(), llvm::VPWidenLoadRecipe::usesFirstLaneOnly(), llvm::VPWidenRecipe::usesFirstLaneOnly(), llvm::VPWidenStoreEVLRecipe::usesFirstLaneOnly(), llvm::VPWidenStoreRecipe::usesFirstLaneOnly(), llvm::VPCanonicalIVPHIRecipe::usesFirstPartOnly(), llvm::VPInstruction::usesFirstPartOnly(), llvm::VPIRInstruction::usesFirstPartOnly(), llvm::VPUser::usesFirstPartOnly(), llvm::VPVectorEndPointerRecipe::usesFirstPartOnly(), llvm::VPVectorPointerRecipe::usesFirstPartOnly(), llvm::VPBranchOnMaskRecipe::usesScalars(), llvm::VPIRInstruction::usesScalars(), llvm::VPPredInstPHIRecipe::usesScalars(), llvm::VPReplicateRecipe::usesScalars(), llvm::VPUser::usesScalars(), llvm::sandboxir::UseSwap::UseSwap(), llvm::ValID::ValID(), llvm::orc::detail::WaitingOnGraph< JITDylib *, NonOwningSymbolStringPtr >::validate(), llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander(), llvm::MachineIRBuilder::validateBinaryOp(), llvm::cas::ondisk::UnifiedOnDiskCache::validateIfNeeded(), llvm::MachineIRBuilder::validateSelectOp(), llvm::MachineIRBuilder::validateShiftOp(), llvm::MachineBasicBlock::validateSuccProbs(), llvm::ImutAVLTree< ValInfo >::validateTree(), llvm::MachineIRBuilder::validateTruncExt(), llvm::MachineIRBuilder::validateUnaryOp(), validThroughout(), llvm::json::Value::Value(), llvm::json::Value::Value(), llvm::ValueAsMetadata::ValueAsMetadata(), valueCoversEntireFragment(), llvm::ValueEnumerator::ValueEnumerator(), llvm::ExpressionFormat::valueFromStringRepr(), llvm::object::Elf_GnuHash_Impl< ELFType< E, Is64 > >::values(), llvm::LLT::vector(), llvm::LLT::vector(), VectorizePTXValueVTs(), slpvectorizer::BoUpSLP::vectorizeTree(), vectorPseudoHasAllNBitUsers(), vectorPseudoHasAllNBitUsers(), vectorToScalarBitmask(), llvm::AAPointerInfo::Access::verify(), llvm::GenericConvergenceVerifier< ContextT >::verify(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::LoopInfoBase< MachineBasicBlock, MachineLoop >::verify(), llvm::MachineTraceMetrics::Ensemble::verify(), llvm::RegisterBank::verify(), llvm::RegisterBankInfo::InstructionMapping::verify(), llvm::RegisterBankInfo::PartialMapping::verify(), llvm::RegisterBankInfo::ValueMapping::verify(), llvm::RegisterBankInfo::verify(), llvm::sandboxir::Argument::verify(), llvm::sandboxir::BasicBlock::verify(), llvm::sandboxir::Constant::verify(), llvm::sandboxir::ConstantAggregateZero::verify(), llvm::sandboxir::ConstantFP::verify(), llvm::sandboxir::ConstantInt::verify(), llvm::sandboxir::ConstantPointerNull::verify(), llvm::sandboxir::ConstantTokenNone::verify(), llvm::sandboxir::DSOLocalEquivalent::verify(), llvm::sandboxir::Function::verify(), llvm::sandboxir::GlobalIFunc::verify(), llvm::sandboxir::GlobalVariable::verify(), llvm::sandboxir::NoCFIValue::verify(), llvm::sandboxir::OpaqueValue::verify(), llvm::sandboxir::PoisonValue::verify(), llvm::sandboxir::SingleLLVMInstructionImpl< LLVMT >::verify(), llvm::sandboxir::UndefValue::verify(), llvm::sandboxir::User::verify(), llvm::ScalarEvolution::verify(), llvm::DominatorTreeWrapperPass::verifyAnalysis(), llvm::MachineTraceMetrics::verifyAnalysis(), llvm::PostDominatorTreeWrapperPass::verifyAnalysis(), llvm::GenericCycle< ContextT >::verifyCycle(), llvm::GenericCycle< ContextT >::verifyCycleNest(), llvm::GenericCycleInfo< ContextT >::verifyCycleNest(), llvm::dwarf_linker::parallel::CompileUnit::verifyDependencies(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::MemorySSA::verifyDominationNumbers(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::verifyInput(), llvm::RISCVInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), llvm::X86InstrInfo::verifyInstruction(), llvm::mca::verifyInstructionEliminated(), llvm::verifyIntrinsicTables(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), llvm::GlobalValueSummaryInfo::verifyLocal(), llvm::LoopBase< BlockT, LoopT >::verifyLoopNest(), llvm::BlockFrequencyInfoImpl< BT >::verifyMatch(), llvm::MemorySSA::verifyMemorySSA(), llvm::misexpect::verifyMisExpect(), llvm::AnalysisManager< LazyCallGraph::SCC, LazyCallGraph & >::verifyNotInvalidated(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::MemorySSA::verifyPrevDefInPhis(), llvm::GVNPass::ValueTable::verifyRemoved(), verifySameBranchInstructions(), llvm::ScheduleDAG::VerifyScheduledDAG(), llvm::ScheduleDAGSDNodes::VerifyScheduledSequence(), verifyTables(), verifyTables(), llvm::AArch64SelectionDAGInfo::verifyTargetNode(), llvm::RISCVSelectionDAGInfo::verifyTargetNode(), llvm::MachineRegisterInfo::verifyUseList(), versionCallSiteWithCond(), llvm::LoopVersioning::versionLoop(), llvm::VFRange::VFRange(), viewRegionInfo(), violatesLegacyMultiExitLoopCheck(), llvm::Register::virtRegIndex(), llvm::VirtRegOrUnit::VirtRegOrUnit(), llvm::VirtRegOrUnit::VirtRegOrUnit(), llvm::BitTracker::visit(), llvm::objcopy::elf::IHexSectionWriter::visit(), llvm::objcopy::elf::IHexSectionWriterBase::visit(), llvm::objcopy::elf::SRECSectionWriter::visit(), llvm::objcopy::elf::SRECSectionWriterBase::visit(), llvm::PGOContextualProfile::visit(), llvm::SCEVRewriteVisitor< SCEVCastSinkingRewriter >::visit(), llvm::SelectionDAGBuilder::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::xray::RecordInitializer::visit(), llvm::InstCombinerImpl::visitAdd(), llvm::Interpreter::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitAnd(), llvm::Interpreter::visitAShr(), llvm::InstCombinerImpl::visitAtomicRMWInst(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), visitCmpBlock(), llvm::SelectionDAGBuilder::visitDbgInfo(), visitDomSubTree(), llvm::jitlink::aarch32::StubsManager_prev7::visitEdge(), llvm::jitlink::aarch32::StubsManager_v7::visitEdge(), llvm::jitlink::aarch64::GOTTableManager::visitEdge(), llvm::jitlink::loongarch::GOTTableManager::visitEdge(), llvm::jitlink::systemz::GOTTableManager::visitEdge(), llvm::jitlink::x86::GOTTableManager::visitEdge(), llvm::jitlink::x86_64::GOTTableManager::visitEdge(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFreeze(), DataScalarizerVisitor::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::InstCombinerImpl::visitLoadInst(), llvm::InstCombinerImpl::visitLShr(), llvm::Interpreter::visitLShr(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::InstCombinerImpl::visitMul(), llvm::PtrUseVisitor< ArgUseChecker >::visitPtr(), llvm::InstCombinerImpl::visitPtrToInt(), llvm::pdb::DbiStream::visitSectionContributions(), llvm::InstCombinerImpl::visitSExt(), llvm::Interpreter::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::InstCombinerImpl::visitStoreInst(), llvm::InstCombinerImpl::visitSub(), llvm::SelectionDAGBuilder::visitSwitchCase(), llvm::codeview::SymbolDeserializer::visitSymbolBegin(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::logicalview::LVSymbolVisitor::visitSymbolBegin(), llvm::codeview::SymbolDeserializer::visitSymbolEnd(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), llvm::InstCombinerImpl::visitTrunc(), llvm::codeview::TypeDeserializer::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeDeserializer::visitTypeEnd(), llvm::codeview::TypeRecordMapping::visitTypeEnd(), llvm::InstCombinerImpl::visitUnconditionalBranchInst(), SCEVCastSinkingRewriter::visitUnknown(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), llvm::VLIWResourceModel::VLIWResourceModel(), llvm::ir2vec::VocabStorage::VocabStorage(), llvm::VPBaseLoadStoreSDNode::VPBaseLoadStoreSDNode(), llvm::VPBlendRecipe::VPBlendRecipe(), llvm::VPGatherScatterSDNode::VPGatherScatterSDNode(), llvm::VPInstruction::VPInstruction(), llvm::VPInterleaveBase::VPInterleaveBase(), llvm::VPIRValue::VPIRValue(), llvm::VPMatchContext::VPMatchContext(), llvm::VPRecipeValue::VPRecipeValue(), llvm::VPWidenIntOrFpInductionRecipe::VPWidenIntOrFpInductionRecipe(), llvm::VPWidenMemoryRecipe::VPWidenMemoryRecipe(), llvm::LockFileManager::waitForUnlockFor(), wasEscaped(), llvm::object::WasmSymbol::WasmSymbol(), llvm::WebAssembly::wasmSymbolSetType(), llvm::VirtRegAuxInfo::weightCalcHelper(), llvm::WholeProgramDevirtPass::WholeProgramDevirtPass(), widen96To128(), widenAbs(), widenBuildVec(), widenBuildVector(), widenCtPop(), widenMaskVectorType(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), llvm::LegalizerHelper::widenScalar(), llvm::widenShuffleMaskElts(), llvm::widenShuffleMaskElts(), widenSubVector(), widenSubVector(), llvm::LegacyLegalizerInfo::widenToLargerTypesAndNarrowToLargest(), widenVec(), widenVectorOpsToi8(), widenVectorToPartType(), llvm::widenWidenableBranch(), willGenerateVectors(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::orc::JITDylib::withLinkOrderDo(), llvm::orc::ThreadSafeModule::withModuleDo(), llvm::orc::ThreadSafeModule::withModuleDo(), llvm::SparseBitVectorElement< ElementSize >::word(), workshareLoopTargetCallback(), llvm::coverage::CoverageMappingWriter::write(), llvm::mcdxbc::PSVRuntimeInfo::write(), llvm::mcdxbc::RootSignatureDesc::write(), llvm::memprof::MemProfSummary::write(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::write(), llvm::objcopy::elf::BinaryWriter::write(), llvm::objcopy::elf::IHexWriter::write(), llvm::objcopy::elf::SRECWriter::write(), llvm::object::OffloadBinary::write(), llvm::orc::shared::SPSOutputBuffer::write(), llvm::raw_ostream::write(), llvm::StringTableBuilder::write(), llvm::StringTableBuilder::write(), llvm::TimeTraceProfiler::write(), llvm::write32AArch64Ldr(), writeAPFloatInternal(), llvm::writeArchiveToStream(), writeAsOperandInternal(), writeAsOperandInternal(), llvm::support::endian::writeAtBitAlignment(), llvm::ifs::writeBinaryStub(), llvm::sampleprof::SampleProfileWriterBinary::writeCallsiteVTableProf(), writeCOFF(), llvm::sampleprof::SampleProfileWriterBinary::writeContextIdx(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCSNameTableSection(), writeDIArgList(), writeDIExpression(), llvm::MachObjectWriter::writeDysymtabLoadCommand(), llvm::msgpack::Writer::writeExt(), writeFragment(), writeFunctionHeapProfileRecords(), writeFunctionTypeMetadataRecords(), llvm::MachObjectWriter::writeHeader(), writeHexDigit(), llvm::jitlink::aarch32::writeImmediate(), llvm::jitlink::aarch32::writeImmediate(), llvm::writeIndex(), llvm::orc::OrcAArch64::writeIndirectStubsBlock(), llvm::orc::OrcI386::writeIndirectStubsBlock(), llvm::orc::OrcLoongArch64::writeIndirectStubsBlock(), llvm::orc::OrcMips32_Base::writeIndirectStubsBlock(), llvm::orc::OrcMips64::writeIndirectStubsBlock(), llvm::orc::OrcRiscv64::writeIndirectStubsBlock(), llvm::orc::OrcX86_64_Base::writeIndirectStubsBlock(), writeIRFileDisplayName(), llvm::MachObjectWriter::writeLinkeditLoadCommand(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::orc::writeMachOStruct(), llvm::codeview::ContinuationRecordBuilder::writeMemberType(), writeMemoryProfileRadixTree(), llvm::writeMemProfFrameArray(), llvm::writeMemProfRadixTreeBased(), writeMetadata(), llvm::BitcodeWriter::writeModule(), llvm::dxil::BitcodeWriter::writeModule(), llvm::jitlink::aarch64::writeMovRegImm64Seq(), llvm::jitlink::aarch64::writeMovRegRegSeq(), llvm::AVRAsmBackend::writeNopData(), llvm::DXContainerObjectWriter::writeObject(), llvm::MachObjectWriter::writeObject(), llvm::WinCOFFWriter::writeObject(), llvm::jitlink::aarch64::writePACSignSeq(), llvm::jitlink::aarch32::writeRegister(), llvm::jitlink::aarch32::writeRegister(), llvm::orc::EPCIndirectionUtils::writeResolverBlock(), llvm::orc::OrcI386::writeResolverCode(), llvm::MachObjectWriter::writeSection(), llvm::objcopy::elf::IHexSectionWriterBase::writeSection(), llvm::MCAssembler::writeSectionData(), llvm::MachObjectWriter::writeSegmentLoadCommand(), llvm::gsym::FileWriter::writeSLEB(), llvm::mca::ReadState::writeStartEvent(), llvm::jitlink::aarch64::writeStoreRegSeq(), llvm::writeStringsAndOffsets(), llvm::BitcodeWriter::writeStrtab(), llvm::BitcodeWriter::writeSymtab(), llvm::MachObjectWriter::writeSymtabLoadCommand(), llvm::BitcodeWriter::writeThinLinkBitcode(), writeToResolutionFile(), llvm::orc::OrcI386::writeTrampolines(), llvm::orc::OrcMips32_Base::writeTrampolines(), llvm::gsym::FileWriter::writeULEB(), writeUniversalArchsToStream(), writeWithCommas(), llvm::X86FrameLowering::X86FrameLowering(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), llvm::X86RegisterBankInfo::X86RegisterBankInfo(), X86SelectAddress(), llvm::X86TargetLowering::X86TargetLowering(), llvm::object::XCOFFSymbolRef::XCOFFSymbolRef(), llvm::reassociate::XorOpnd::XorOpnd(), XXH3_hashLong_128b(), XXH3_hashLong_64b(), llvm::yaml::yamlize(), llvm::InstructionWorklist::zap(), llvm::ConstantRange::zeroExtend(), llvm::APInt::zext(), llvm::ZExtInst::ZExtInst(), llvm::zip_equal(), llvm::zip_first(), llvm::AddrLabelMap::~AddrLabelMap(), llvm::ms_demangle::ArenaAllocator::~ArenaAllocator(), llvm::ArrayRecycler< MachineOperand >::Capacity< MachineOperand >::~ArrayRecycler(), llvm::AsmPrinter::~AsmPrinter(), llvm::BitcodeWriter::~BitcodeWriter(), llvm::BitstreamWriter::~BitstreamWriter(), slpvectorizer::BoUpSLP::~BoUpSLP(), llvm::CallGraphNode::~CallGraphNode(), llvm::CFIFunctionFrameAnalyzer::~CFIFunctionFrameAnalyzer(), llvm::ChangeReporter< IRUnitT >::~ChangeReporter(), llvm::SelectionDAG::DAGUpdateListener::~DAGUpdateListener(), llvm::orc::DebugObject::~DebugObject(), llvm::orc::ExecutionSession::~ExecutionSession(), llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::~FinalizedAlloc(), llvm::TrailingObjects< BaseTy, TrailingTys >::FixedSizeStorageOwner::~FixedSizeStorageOwner(), llvm::GenericDomTreeUpdater< DomTreeUpdater, DominatorTree, PostDominatorTree >::~GenericDomTreeUpdater(), llvm::InlineAdvice::~InlineAdvice(), llvm::InlineAdvisor::~InlineAdvisor(), llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc::~IPInFlightAlloc(), llvm::parallel::detail::Latch::~Latch(), llvm::ThreadSafeTrieRawHashMap< T, NumHashBytes >::LazyValueConstructor::~LazyValueConstructor(), llvm::LazyValueInfoWrapperPass::~LazyValueInfoWrapperPass(), llvm::orc::LinkGraphLinkingLayer::~LinkGraphLinkingLayer(), llvm::LLVMContextImpl::~LLVMContextImpl(), llvm::OpenMPIRBuilder::~OpenMPIRBuilder(), llvm::json::OStream::~OStream(), llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry(), llvm::PrintCrashIRInstrumentation::~PrintCrashIRInstrumentation(), llvm::PrintIRInstrumentation::~PrintIRInstrumentation(), llvm::raw_ostream::~raw_ostream(), llvm::Recycler< T, Size, Align >::~Recycler(), llvm::RefCountedBase< Derived >::~RefCountedBase(), llvm::remarks::RemarkStreamer::~RemarkStreamer(), llvm::ReplaceableMetadataImpl::~ReplaceableMetadataImpl(), llvm::orc::RTDyldObjectLinkingLayer::~RTDyldObjectLinkingLayer(), llvm::ScalarEvolution::~ScalarEvolution(), llvm::SCEVExpander::~SCEVExpander(), llvm::ScopedHashTable< MachineInstr *, unsigned, MachineInstrExpressionTrait, AllocatorTy >::~ScopedHashTable(), llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope(), llvm::SelectionDAG::~SelectionDAG(), slpvectorizer::BoUpSLP::ShuffleCostEstimator::~ShuffleCostEstimator(), slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::~ShuffleInstructionBuilder(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::~SimpleExecutorDylibManager(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::~SimpleExecutorMemoryManager(), llvm::orc::SimpleRemoteEPC::~SimpleRemoteEPC(), llvm::orc::SymbolStringPool::~SymbolStringPool(), llvm::sys::fs::TempFile::~TempFile(), llvm::ThreadSafeRefCountedBase< Derived >::~ThreadSafeRefCountedBase(), llvm::ThreadSafeTrieRawHashMapBase::~ThreadSafeTrieRawHashMapBase(), llvm::sandboxir::Tracker::~Tracker(), llvm::ValueSymbolTable::~ValueSymbolTable(), llvm::VPDef::~VPDef(), llvm::VPRecipeValue::~VPRecipeValue(), and llvm::VPValue::~VPValue().
if() [1/3]
if (! Op0)
References AbstractManglingParser< Derived, Alloc >::Ops, Op0, and SalvagedExpr.
if() [2/3]
if (DbgMI->getOpcode() ! = TargetOpcode::DBG_VALUE)
Definition at line 277 of file CodeGenCommonISel.cpp.
References assert(), and llvm::MachineInstr::getOpcode().
Referenced by llvm::AArch64PrologueEpilogueCommon::AArch64PrologueEpilogueCommon(), llvm::AbstractCallSite::AbstractCallSite(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::AMDGPU::IsaInfo::AMDGPUTargetID::AMDGPUTargetID(), llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::jitlink::BasicLayout::BasicLayout(), llvm::CallGraphDOTInfo::CallGraphDOTInfo(), canBeFeederToNewValueJump(), llvm::GenericScheduler::checkAcyclicLatency(), llvm::CodeGenPassBuilder< AMDGPUCodeGenPassBuilder, GCNTargetMachine >::CodeGenPassBuilder(), llvm::CodeGenTargetMachineImpl::CodeGenTargetMachineImpl(), llvm::dwarf_linker::classic::CompileUnit::CompileUnit(), llvm::DebuginfodServer::DebuginfodServer(), llvm::DwarfDebug::DwarfDebug(), llvm::DWARFVerifier::DWARFVerifier(), eliminateConstraints(), llvm::SystemZPostRASchedStrategy::enterMBB(), llvm::Expected< std::unique_ptr< InFlightAlloc > >::Expected(), llvm::Expected< std::unique_ptr< InFlightAlloc > >::Expected(), FindDominatedInstruction(), findReturnsToZap(), findVCMPToFoldIntoVPST(), llvm::FunctionSummary::FunctionSummary(), llvm::GCNUserSGPRUsageInfo::GCNUserSGPRUsageInfo(), getLocCookie(), getRegOpRC(), llvm::BaseRecord::getUpperCamelName(), handleUse(), if(), llvm::GCNSchedStage::initGCNRegion(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), isCVTAToLocalCombinationCandidate(), isMoveInstr(), llvm::mca::LatencyInstrument::LatencyInstrument(), llvm::coverage::LineCoverageStats::LineCoverageStats(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), lowerV4I32Shuffle(), llvm::mca::LSUnitBase::LSUnitBase(), llvm::object::MachOAbstractFixupEntry::MachOAbstractFixupEntry(), llvm::yaml::MappingNormalizationHeap< TNorm, TFinal >::MappingNormalizationHeap(), llvm::MCAssembler::MCAssembler(), llvm::MemProfContextDisambiguation::MemProfContextDisambiguation(), llvm::PBQP::RegAlloc::NodeMetadata::NodeMetadata(), llvm::NVPTXTargetMachine::NVPTXTargetMachine(), ParameterPack::ParameterPack(), llvm::PassBuilder::PassBuilder(), llvm::PGOInstrumentationUse::PGOInstrumentationUse(), slpvectorizer::BoUpSLP::processBuildVector(), ReachabilityQueryInfo< ToTy >::ReachabilityQueryInfo(), reportTranslationError(), llvm::SanitizerCoveragePass::SanitizerCoveragePass(), llvm::SystemZPostRASchedStrategy::schedNode(), llvm::impl_detail::MachineSchedulerBase::scheduleRegions(), llvm::GenericSchedulerBase::setPolicy(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), llvm::yaml::SIMachineFunctionInfo::SIMachineFunctionInfo(), simplifyAMDGCNImageIntrinsic(), llvm::SinkAndHoistLICMFlags::SinkAndHoistLICMFlags(), llvm::SPIRVSubtarget::SPIRVSubtarget(), llvm::cgdata::StreamCacheData::StreamCacheData(), llvm::ThreadSafeTrieRawHashMapBase::ImplType::TrailingObjects, llvm::InstCombinerImpl::visitPHINode(), llvm::WebAssemblyDebugValueManager::WebAssemblyDebugValueManager(), and WorkloadImportsManager::WorkloadImportsManager().
if() [3/3]
if (IsValidSalvageExpr)
Definition at line 293 of file CodeGenCommonISel.cpp.
References llvm::dbgs(), llvm::MachineInstr::getDebugExpressionOp(), llvm::MachineInstr::getOperand(), IsValidSalvageExpr, LLVM_DEBUG, Op0, SalvagedExpr, llvm::MachineOperand::setMetadata(), and llvm::MachineOperand::setReg().
MIIsInTerminatorSequence()
bool MIIsInTerminatorSequence (const MachineInstr & MI) static
Given that the input MI is before a partial terminator sequence TSeq, return true if M + TSeq also a partial terminator sequence.
A Terminator sequence is a sequence of MachineInstrs which at this point in lowering copy vregs into physical registers, which are then passed into terminator instructors so we can satisfy ABI constraints. A partial terminator sequence is an improper subset of a terminator sequence (i.e. it may be the whole terminator sequence).
Definition at line 53 of file CodeGenCommonISel.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::Register::isPhysical(), llvm::MachineOperand::isReg(), and MI.
Variable Documentation
IsValidSalvageExpr
bool IsValidSalvageExpr
Initial value:
                    =
SalvagedExpr->getNumElements() <= MaxExpressionSize
Definition at line 291 of file CodeGenCommonISel.cpp.
Referenced by if(), and llvm::salvageDebugInfoForDbgValues().
nullptr
nullptr
Find the split point at which to splice the end of BB into its success stack protector check machine basic block.
On many platforms, due to ABI constraints, terminators, even before register allocation, use physical registers. This creates an issue for us since physical registers at this point can not travel across basic blocks. Luckily, selectiondag always moves physical registers into vregs when they enter functions and moves them through a sequence of copies back into the physical registers right before the terminator creating a ``Terminator Sequence''. This function is searching for the beginning of the terminator sequence so that we can ensure that we splice off not just the terminator, but additionally the copies that move the vregs into the physical registers. */ MachineBasicBlock::iterator llvm::findSplitPointForStackProtector(MachineBasicBlock *BB, const TargetInstrInfo &TII) { MachineBasicBlock::iterator SplitPoint = BB->getFirstTerminator(); if (SplitPoint == BB->begin()) return SplitPoint;
MachineBasicBlock::iterator Start = BB->begin(); MachineBasicBlock::iterator Previous = SplitPoint; do { –Previous; } while (Previous != Start && Previous->isDebugInstr());
if (TII.isTailCall(*SplitPoint) && Previous->getOpcode() == TII.getCallFrameDestroyOpcode()) { Call frames cannot be nested, so if this frame is describing the tail call itself, then we must insert before the sequence even starts. For example: <split point> ADJCALLSTACKDOWN ... <Moves> ADJCALLSTACKUP ... TAILJMP somewhere On the other hand, it could be an unrelated call in which case this tail call has no register moves of its own and should be the split point. For example: ADJCALLSTACKDOWN CALL something_else ADJCALLSTACKUP <split point> TAILJMP somewhere do { –Previous; if (Previous->isCall()) return SplitPoint; } while(Previous->getOpcode() != TII.getCallFrameSetupOpcode());
return Previous; }
while (MIIsInTerminatorSequence(*Previous)) { SplitPoint = Previous; if (Previous == Start) break; –Previous; }
return SplitPoint; }
FPClassTest llvm::invertFPClassTestIfSimpler(FPClassTest Test, bool UseFCmp) { FPClassTest InvertedTest = ~Test;
Pick the direction with fewer tests TODO: Handle more combinations of cases that can be handled together switch (static_cast<unsigned>(InvertedTest)) { case fcNan: case fcSNan: case fcQNan: case fcInf: case fcPosInf: case fcNegInf: case fcNormal: case fcPosNormal: case fcNegNormal: case fcSubnormal: case fcPosSubnormal: case fcNegSubnormal: case fcZero: case fcPosZero: case fcNegZero: case fcFinite: case fcPosFinite: case fcNegFinite: case fcZero | fcNan: case fcSubnormal | fcZero: case fcSubnormal | fcZero | fcNan: return InvertedTest; case fcInf | fcNan: case fcPosInf | fcNan: case fcNegInf | fcNan: If we're trying to use fcmp, we can take advantage of the nan check behavior of the compare (but this is more instructions in the integer expansion). return UseFCmp ? InvertedTest : fcNone; default: return fcNone; }
llvm_unreachable("covered FPClassTest"); }
static MachineOperand *getSalvageOpsForCopy(const MachineRegisterInfo &MRI, MachineInstr &Copy) { assert(Copy.getOpcode() == TargetOpcode::COPY && "Must be a COPY");
return &Copy.getOperand(1); }
static MachineOperand *getSalvageOpsForTrunc(const MachineRegisterInfo &MRI, MachineInstr &Trunc, SmallVectorImpl<uint64_t> &Ops) { assert(Trunc.getOpcode() == TargetOpcode::G_TRUNC && "Must be a G_TRUNC");
const auto FromLLT = MRI.getType(Trunc.getOperand(1).getReg()); const auto ToLLT = MRI.getType(Trunc.defs().begin()->getReg());
TODO: Support non-scalar types. if (!FromLLT.isScalar()) { return nullptr; }
auto ExtOps = DIExpression::getExtOps(FromLLT.getSizeInBits(), ToLLT.getSizeInBits(), false); Ops.append(ExtOps.begin(), ExtOps.end()); return &Trunc.getOperand(1); }
static MachineOperand *salvageDebugInfoImpl(const MachineRegisterInfo &MRI, MachineInstr &MI, SmallVectorImpl<uint64_t> &Ops) { switch (MI.getOpcode()) { case TargetOpcode::G_TRUNC: return getSalvageOpsForTrunc(MRI, MI, Ops); case TargetOpcode::COPY: return getSalvageOpsForCopy(MRI, MI); default: return nullptr; } }
void llvm::salvageDebugInfoForDbgValue(const MachineRegisterInfo &MRI, MachineInstr &MI, ArrayRef<MachineOperand *> DbgUsers) { These are arbitrary chosen limits on the maximum number of values and the maximum size of a debug expression we can salvage up to, used for performance reasons. const unsigned MaxExpressionSize = 128;
for (auto *DefMO : DbgUsers) { MachineInstr *DbgMI = DefMO->getParent(); if (DbgMI->isIndirectDebugValue()) { continue; }
int UseMOIdx = DbgMI->findRegisterUseOperandIdx(DefMO->getReg(), /*TRI=
Definition at line 272 of file CodeGenCommonISel.cpp.
Referenced by llvm::AArch64AttributeParser::AArch64AttributeParser(), llvm::cl::alias::alias(), llvm::AllocaInst::AllocaInst(), llvm::analyzeContextInfo(), llvm::Any::Any(), llvm::TargetLoweringBase::ArgListEntry::ArgListEntry(), llvm::ARMAsmPrinter::ARMAsmPrinter(), llvm::ArrayRef< llvm::cfg::Update< MachineBasicBlock * > >::ArrayRef(), llvm::AssertingVH< const BasicBlock >::AssertingVH(), llvm::mustache::ASTNode::ASTNode(), llvm::mustache::ASTNode::ASTNode(), llvm::mustache::ASTNode::ASTNode(), llvm::CallLowering::BaseArgInfo::BaseArgInfo(), llvm::SDPatternMatch::BasicMatchContext::BasicMatchContext(), llvm::SDPatternMatch::BasicMatchContext::BasicMatchContext(), llvm::BitstreamWriter::BitstreamWriter(), llvm::BitstreamWriter::BitstreamWriter(), llvm::RegionBase< Tr >::block_iterator_wrapper< false >::block_iterator_wrapper(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BlockNamePrinter::BlockNamePrinter(), llvm::BPFAsmPrinter::BPFAsmPrinter(), llvm::BTFTypeDerived::BTFTypeDerived(), llvm::BTFTypeTypeTag::BTFTypeTypeTag(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::CallGraph::CallGraph(), llvm::dxil::CBufferDataLayout::CBufferDataLayout(), false::Chain::Chain(), llvm::object::Archive::ChildFallibleIterator::ChildFallibleIterator(), llvm::pdb::ClassLayout::ClassLayout(), llvm::PatternMatch::CmpClass_match< LHS_t, RHS_t, Class, Commutable >::CmpClass_match(), llvm::SPIRV::ConvergenceRegion::ConvergenceRegion(), llvm::SPIRV::ConvergenceRegionInfo::ConvergenceRegionInfo(), llvm::coverage::CoverageMappingIterator::CoverageMappingIterator(), llvm::createCallMatchingInvoke(), createDummyReturnBlock(), llvm::CriticalAntiDepBreaker::CriticalAntiDepBreaker(), llvm::orc::CtorDtorIterator::CtorDtorIterator(), llvm::DbgValueDef::DbgValueDef(), llvm::DbgValueDef::DbgValueDef(), llvm::DbgValueDef::DbgValueDef(), llvm::DbgValueDef::DbgValueDef(), llvm::DbgValueDef::DbgValueDef(), llvm::pdb::DbiStream::DbiStream(), llvm::pdb::DbiStreamBuilder::DbiStreamBuilder(), llvm::def_chain_iterator< T, UseOptimizedChain >::def_chain_iterator(), llvm::DelimitedScope::DelimitedScope(), llvm::DependenceGraphInfo< DDGNode >::DependenceGraphInfo(), llvm::DiagnosticInfoOptimizationFailure::DiagnosticInfoOptimizationFailure(), llvm::msgpack::DocNode::DocNode(), llvm::yaml::Document::Document(), llvm::DOTFuncInfo::DOTFuncInfo(), llvm::dwarf_linker::parallel::DwarfUnit::DwarfUnit(), llvm::ELFCompactAttrParser::ELFCompactAttrParser(), llvm::ELFExtendedAttrParser::ELFExtendedAttrParser(), emitResourceMetadata(), llvm::EngineBuilder::EngineBuilder(), llvm::EngineBuilder::EngineBuilder(), llvm::ExecutionContext::ExecutionContext(), llvm::ExecutionEngine::ExecutionEngine(), llvm::ExecutionEngine::ExecutionEngine(), expandToSwitch(), llvm::AArch64::ExtensionSet::ExtensionSet(), llvm::FCmpInst::FCmpInst(), llvm::SPIRVGlobalRegistry::findAssignPtrTypeInstr(), llvm::SPIRVGlobalRegistry::findDeducedCompositeType(), llvm::SPIRVGlobalRegistry::findDeducedElementType(), llvm::SPIRVGlobalRegistry::findMutated(), llvm::IRMover::IdentifiedStructTypeSet::findNonOpaque(), llvm::MachineInstr::findRegisterDefOperand(), llvm::MachineInstr::findRegisterUseOperand(), llvm::SPIRVGlobalRegistry::findReturnType(), llvm::objcopy::elf::Object::findSection(), findUserOf(), fixIrreducible(), foldAndOrOfICmpsWithConstEq(), foldLogOpOfMaskedICmps(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::formatted_raw_ostream::formatted_raw_ostream(), llvm::formatted_raw_ostream::formatted_raw_ostream(), llvm::FunctionCallee::FunctionCallee(), llvm::GlobalsAAResult::FunctionInfo::FunctionInfo(), llvm::GCNHazardRecognizer::GCNHazardRecognizer(), llvm::GCNSchedStrategy::GCNSchedStrategy(), llvm::generateAsyncCopy(), false::GepNode::GepNode(), llvm::RecordKeeper::getClass(), llvm::InstrProfCorrelatorImpl< IntPtrT >::getDataPointer(), llvm::RecordKeeper::getDef(), llvm::PseudoProbeManager::getDesc(), getFirstFunctionBlock(), llvm::vputils::getFirstLoopHeader(), llvm::SPIRVGlobalRegistry::getForwardCalls(), llvm::SPIRVGlobalRegistry::getFunctionByDefinition(), llvm::SPIRVGlobalRegistry::getFunctionDefinition(), llvm::SPIRVGlobalRegistry::getFunctionDefinitionByUse(), llvm::RecordKeeper::getGlobal(), llvm::SPIRVGlobalRegistry::getGlobalObject(), llvm::LoopNest::getInnermostLoop(), getInstrBB(), getInvariantGroupClobberingInstruction(), llvm::DataLayout::getLargestLegalIntType(), getLoadInfo(), llvm::ReachingDefInfo::getLocalLiveOutMIDef(), getMatchedEntries(), llvm::MDNode::getMostGenericAliasScope(), llvm::IntrusiveBackListNode::getNext(), llvm::SIInstrInfo::getOpRegClass(), getOptimizableIVOf(), llvm::CoroIdInst::getPromise(), llvm::logicalview::LVCodeViewReader::getScopeForModule(), llvm::LiveRange::getSegmentContaining(), llvm::LiveRange::getSegmentContaining(), getSingleSchedPred(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPHeaderPHIRecipe::getStartValue(), getTargetSection(), llvm::getUniqued(), llvm::VPlan::getVectorLoopRegion(), llvm::VPlan::getVectorLoopRegion(), llvm::LiveRange::getVNInfoAt(), llvm::LiveRange::getVNInfoBefore(), llvm::MemorySSA::getWritableBlockAccesses(), llvm::MemorySSA::getWritableBlockDefs(), llvm::HasReferenceResolver::HasReferenceResolver(), llvm::HexagonDAGToDAGISel::HexagonDAGToDAGISel(), llvm::IdentifyingPassPtr::IdentifyingPassPtr(), llvm::object::ImportedSymbolRef::ImportedSymbolRef(), llvm::object::ImportedSymbolRef::ImportedSymbolRef(), llvm::pdb::InfoStream::InfoStream(), llvm::InstCombiner::InstCombiner(), llvm::mca::InstRef::InstRef(), llvm::InstrProfRecord::InstrProfRecord(), llvm::InterleaveGroup< InstTy >::InterleaveGroup(), llvm::sandboxir::Interval< T >::Interval(), llvm::IRPosition::IRPosition(), llvm::ItaniumPartialDemangler::ItaniumPartialDemangler(), llvm::OnDiskChainedHashTable< Info >::iterator::iterator(), llvm::LegalizerHelper::LegalizerHelper(), llvm::line_iterator::line_iterator(), llvm::coverage::LineCoverageIterator::LineCoverageIterator(), llvm::LiveRange::LiveRange(), llvm::LLParser::LLParser(), llvm::LLVMRemarkFileHandle::LLVMRemarkFileHandle(), llvm::LazyAtomicPointer< TrieNode >::load(), llvm::MCContext::lookupMacro(), llvm::LoopAccessInfo::LoopAccessInfo(), llvm::LoopBase< BlockT, LoopT >::LoopBase(), llvm::LoopBase< BlockT, LoopT >::LoopBase(), llvm::MachineInstrBundleIterator< MachineInstr >::MachineInstrBundleIterator(), llvm::MachineModuleInfo::MachineModuleInfo(), llvm::MachineModuleInfo::MachineModuleInfo(), llvm::MachineModuleInfo::MachineModuleInfo(), llvm::MachinePointerInfo::MachinePointerInfo(), llvm::yaml::MappingNormalization< TNorm, TFinal >::MappingNormalization(), llvm::MCContext::MCContext(), llvm::MCSectionSPIRV::MCContext, llvm::MCStreamer::MCStreamer(), llvm::MCSectionGOFF::MCSymbolGOFF, llvm::MCWinCOFFStreamer::MCWinCOFFStreamer(), llvm::sys::MemoryBlock::MemoryBlock(), llvm::MemoryLocation::MemoryLocation(), llvm::MemorySSA::MemorySSA(), llvm::MemorySSA::MemorySSA(), llvm::M68kFrameLowering::mergeSPUpdates(), MinMaxSinkInfo::MinMaxSinkInfo(), llvm::MipsDAGToDAGISel::MipsDAGToDAGISel(), llvm::MipsTargetMachine::MipsTargetMachine(), llvm::MIRParserImpl::MIRParserImpl(), llvm::MLInlineAdvisor::MLInlineAdvisor(), llvm::InsertFunctionStrategy::mutate(), llvm::NamedRegionTimer::NamedRegionTimer(), llvm::ScheduleDAGInstrs::newSUnit(), llvm::Registry< T >::node::node(), NodeArray::NodeArray(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::open(), llvm::OptimizationRemarkEmitter::OptimizationRemarkEmitter(), llvm::PassManagerPrettyStackEntry::PassManagerPrettyStackEntry(), llvm::PassManagerPrettyStackEntry::PassManagerPrettyStackEntry(), llvm::PassManagerPrettyStackEntry::PassManagerPrettyStackEntry(), llvm::json::Path::Path(), llvm::PPCELFStreamer::PPCELFStreamer(), llvm::Recycler< T, Size, Align >::Recycler(), llvm::OpenMPIRBuilder::ReductionInfo::ReductionInfo(), llvm::AMDGPUPALMetadata::refComputeRegister(), llvm::AMDGPU::RegBankLegalizeHelper::RegBankLegalizeHelper(), llvm::Regex::Regex(), removeUnneededSections(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result(), llvm::SCEVExpander::SCEVExpander(), llvm::SCEVUnionPredicate::SCEVUnionPredicate(), llvm::mca::Scheduler::Scheduler(), llvm::SDep::SDep(), llvm::SectionMemoryManager::SectionMemoryManager(), llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::SegInfo::SegInfo(), llvm::ShapeT::ShapeT(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), llvm::SizeOffsetValue::SizeOffsetValue(), llvm::SizeOffsetWeakTrackingVH::SizeOffsetWeakTrackingVH(), llvm::SlotTracker::SlotTracker(), llvm::SlotTracker::SlotTracker(), llvm::SPIRVGlobalRegistry::SPIRVGlobalRegistry(), llvm::SPIRVModuleAnalysis::SPIRVModuleAnalysis(), llvm::SUnit::SUnit(), llvm::pdb::SymbolGroupIterator::SymbolGroupIterator(), llvm::SymbolTableListTraits< ValueSubClass, Args >::SymbolTableListTraits(), llvm::SystemZAsmPrinter::SystemZAsmPrinter(), llvm::SystemZHLASMAsmStreamer::SystemZHLASMAsmStreamer(), llvm::SystemZPostRASchedStrategy::SystemZPostRASchedStrategy(), llvm::TargetMachine::TargetMachine(), llvm::TGParser::TGParser(), llvm::ThreadSafeTrieRawHashMapBase::ThreadSafeTrieRawHashMapBase(), llvm::pdb::TpiStreamBuilder::TpiStreamBuilder(), llvm::TrackUnresolvedResolver::TrackUnresolvedResolver(), unifyLoopExits(), unswitchNontrivialInvariants(), updateLiveness(), llvm::sandboxir::Value::user_begin(), llvm::LiveQueryResult::valueDefined(), llvm::ValueHandleBase::ValueHandleBase(), llvm::ValueHandleBase::ValueHandleBase(), llvm::ValueHandleBase::ValueHandleBase(), llvm::RegisterBankInfo::ValueMapping::ValueMapping(), llvm::LiveQueryResult::valueOut(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::wholeprogramdevirt::VirtualCallTarget::VirtualCallTarget(), llvm::VPActiveLaneMaskPHIRecipe::VPActiveLaneMaskPHIRecipe(), llvm::VPCanonicalIVPHIRecipe::VPCanonicalIVPHIRecipe(), llvm::VPEVLBasedIVPHIRecipe::VPEVLBasedIVPHIRecipe(), llvm::VPReductionRecipe::VPReductionRecipe(), llvm::VPSymbolicValue::VPSymbolicValue(), llvm::VPWidenIntOrFpInductionRecipe::VPWidenIntOrFpInductionRecipe(), llvm::WebAssemblyAsmPrinter::WebAssemblyAsmPrinter(), llvm::WholeProgramDevirtPass::WholeProgramDevirtPass(), llvm::mca::WriteState::WriteState(), and llvm::X86Operand::X86Operand().
Op0
auto Op0 = salvageDebugInfoImpl(MRI, MI, Ops)
Definition at line 286 of file CodeGenCommonISel.cpp.
Referenced by AddCombineTo64BitSMLAL16(), adjustBitcastSrcVectorSSE1(), analyzeCostOfVecReduction(), areBitwiseNotOfEachother(), areCompatibleCmpOps(), llvm::SelectInst::areInvalidOperands(), areLoadedOffsetButOtherwiseSame(), llvm::SCEVPatternMatch::bind_cst_ty::bind_cst_ty(), llvm::CSEMIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildDeleteTrailingVectorElements(), BuildExactSDIV(), llvm::MachineIRBuilder::buildFCmp(), llvm::MachineIRBuilder::buildICmp(), BuildIntrinsicOp(), llvm::MachineIRBuilder::buildMaskLowPtrBits(), buildMergeScalars(), llvm::MachineIRBuilder::buildObjectPtrOffset(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::MachineIRBuilder::buildPtrMask(), llvm::MachineIRBuilder::buildSAdde(), llvm::MachineIRBuilder::buildSAddo(), llvm::MachineIRBuilder::buildSCmp(), llvm::MachineIRBuilder::buildSelect(), llvm::MachineIRBuilder::buildSSube(), llvm::MachineIRBuilder::buildSSubo(), llvm::MachineIRBuilder::buildUAdde(), llvm::MachineIRBuilder::buildUAddo(), llvm::MachineIRBuilder::buildUCmp(), llvm::MachineIRBuilder::buildUSube(), llvm::MachineIRBuilder::buildUSubo(), canonicalizeAbs(), canonicalizeCmpWithConstant(), canonicalizeInsertSplat(), canonicalizeLogicFirst(), llvm::GCNTTIImpl::canSimplifyLegacyMulToMul(), checkOrderedReduction(), llvm::collectCmpOps(), CollectSubexprs(), combineAdd(), combineAndMaskToShift(), combineAVX512SetCCToKMOV(), combineCCMask(), combineCMP(), combineConcatVectorOfSplats(), combineConcatVectorOps(), combineFaddCFmul(), combineFMinNumFMaxNum(), combineFP_ROUND(), combineFunnelShift(), combineMulToPMADD52(), combinePTESTCC(), combineSelect(), combineSetCC(), combineShuffleOfBitcast(), combineShuffleOfScalars(), combineShuffleToFMAddSub(), combineSIntToFP(), combineSub(), combineSubSetcc(), combineTargetShuffle(), combineTruncatedArithmetic(), combineUIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVPMADD52LH(), llvm::InstCombinerImpl::commonIDivRemTransforms(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonIRemTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), compareMachineOp(), llvm::BaseIndexOffset::computeAliasing(), computeKnownBitsAddSub(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromLerpPattern(), computeKnownBitsMul(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCastOp(), constantFoldCmp(), llvm::ConstantFoldFPInstOperands(), createLogicFromTable(), decompose(), detectExtMul(), EmitAVX512Test(), EmitCmp(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelLanguage(), emitOrXorXorTree(), llvm::AArch64SelectionDAGInfo::EmitStreamingCompatibleMemLibCall(), emitX86ScalarSelect(), emitX86Select(), EvaluateInDifferentTypeImpl(), llvm::VPWidenPHIRecipe::execute(), llvm::VPWidenRecipe::execute(), expandDisp(), llvm::TargetLowering::expandIntMINMAX(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::TargetLowering::expandROT(), factorizeFAddFSub(), factorizeMathWithShlOps(), llvm::FastISel::fastEmit_ri_(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrr(), llvm::FastISel::fastEmitZExtFromI1(), llvm::FastISel::fastSelectInstruction(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), fillVector(), findFinalIVValue(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndToXor(), foldBitmaskMul(), foldComplexAndOrPatterns(), foldCtpop(), foldCttzCtlz(), foldFCmpFNegCommonOp(), foldFDivPowDivisor(), foldFDivSqrtDivisor(), llvm::InstCombinerImpl::foldFMulReassoc(), llvm::InstCombinerImpl::foldICmpAddConstant(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpEqualityWithOffset(), llvm::InstCombinerImpl::foldICmpInstWithConstantNotInt(), foldICmpIntrinsicWithIntrinsic(), foldICmpOfUAddOv(), foldICmpOrChain(), foldICmpOrXX(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpUSubSatOrUAddSatWithConstant(), llvm::InstCombinerImpl::foldICmpWithConstant(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpXorXX(), foldIdentityExtractShuffle(), foldIdentityShuffles(), foldIDivShl(), foldInsEltIntoSplat(), foldIntrinsicUsingDistributiveLaws(), foldMinimumMaximumSharedOp(), foldMinMaxSharedOp(), foldNoWrapAdd(), llvm::InstCombinerImpl::FoldOpIntoSelect(), foldOrCommuteConstant(), foldOrToXor(), llvm::InstCombinerImpl::foldPowiReassoc(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldSubOfMinMax(), llvm::InstCombinerImpl::foldUsingDistributiveLaws(), foldXorToXor(), genConstMult(), generateEquivalentSub(), llvm::AArch64SysReg::genericRegisterString(), llvm::gep_type_begin(), llvm::ScalarEvolution::getAddExpr(), llvm::getAddressFromInstr(), llvm::ARMTTIImpl::getArithmeticInstrCost(), getCastsForInductionPHI(), llvm::SelectionDAG::getCommutedVectorShuffle(), getConstantAt(), llvm::ExecutionEngine::getConstantValue(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), getKnownTypeFromMaskedOp(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getMulExpr(), getNonPhiOperand(), getPermuteNode(), getPostIncrementOperand(), llvm::LoopVectorizationCostModel::getReductionPatternCost(), getSameOpcode(), getShuffleHalfVectors(), getSummaryFromMD(), slpvectorizer::BoUpSLP::getTreeCost(), llvm::AArch64TTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getVectorInstrCost(), llvm::BasicTTIImplBase< BasicTTIImpl >::getVectorInstrCost(), llvm::GCNTTIImpl::getVectorInstrCost(), llvm::HexagonTTIImpl::getVectorInstrCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::R600TTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::SystemZTTIImpl::getVectorInstrCost(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::TargetTransformInfoImplBase::getVectorInstrCost(), llvm::WebAssemblyTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), handleSpaceCheckIntrinsics(), haveEfficientBuildVectorPattern(), hoistConditionalLoadsStores(), if(), if(), INITIALIZE_PASS(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::PPCTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::AArch64InstrInfo::isAddImmediate(), llvm::ARMBaseInstrInfo::isAddImmediate(), llvm::MipsInstrInfo::isAddImmediate(), llvm::RISCVInstrInfo::isAddImmediate(), isAddSubOrSubAdd(), isBitfieldExtractOpFromAnd(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::isCheckForZeroAndMulWithOverflow(), isCmpSameOrSwapped(), isCondRelevantToAnyCallArgument(), isConstantSplatVectorMaskForType(), isFNEG(), isHalvingTruncateAndConcatOfLegalIntScalableType(), isHighCostExpansion(), isHopBuildVector(), isHorizontalBinOpPart(), isI128MovedFromParts(), llvm::SelectionDAG::isKnownNeverZero(), llvm::isMathLibCallNoop(), IsNOT(), isNOT(), isRepeatedByteSequence(), isSeveralBitsPositioningOpFromShl(), joinDwords(), llvm::SPIRVLegalizerInfo::legalizeCustom(), lower1BitShuffle(), LowerAndToBT(), LowerAndToBTST(), lowerBALLOTIntrinsic(), LowerBUILD_VECTORToVIDUP(), lowerBuildVectorAsBlend(), lowerBuildVectorAsBroadcast(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), LowerCONCAT_VECTORS(), lowerCttzElts(), LowerFABSorFNEG(), LowerFunnelShift(), lowerGR128Binary(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerIntVSETCC_AVX512(), LowerMUL(), lowerMUL_LOHI32(), llvm::RISCVTargetLowering::LowerOperation(), LowerSVEIntrinsicEXT(), LowerVecReduce(), LowerVecReduceMinMax(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVSETCC(), LowerVSETCC(), LowerVSETCCWithSUBUS(), lowerVZIP(), lowerX86FPLogicOp(), llvm::VPlanPatternMatch::m_ActiveLaneMask(), llvm::VPlanPatternMatch::m_Add(), llvm::VPlanPatternMatch::m_AnyOf(), llvm::VPlanPatternMatch::m_Binary(), llvm::VPlanPatternMatch::m_BinaryOr(), llvm::PatternMatch::m_BitReverse(), llvm::VPlanPatternMatch::m_BranchOnCond(), llvm::VPlanPatternMatch::m_BranchOnCount(), llvm::VPlanPatternMatch::m_BranchOnTwoConds(), llvm::VPlanPatternMatch::m_Broadcast(), llvm::PatternMatch::m_BSwap(), llvm::VPlanPatternMatch::m_c_Add(), llvm::VPlanPatternMatch::m_c_Binary(), llvm::VPlanPatternMatch::m_c_BinaryAnd(), llvm::VPlanPatternMatch::m_c_BinaryOr(), llvm::PatternMatch::m_c_Intrinsic(), llvm::VPlanPatternMatch::m_c_Mul(), llvm::SDPatternMatch::m_c_TernaryOp(), llvm::VPlanPatternMatch::m_Cmp(), llvm::VPlanPatternMatch::m_Cmp(), llvm::PatternMatch::m_CopySign(), llvm::VPlanPatternMatch::m_DerivedIV(), llvm::VPlanPatternMatch::m_EVL(), llvm::VPlanPatternMatch::m_ExtractElement(), llvm::VPlanPatternMatch::m_ExtractLane(), llvm::VPlanPatternMatch::m_ExtractLastLane(), llvm::VPlanPatternMatch::m_ExtractLastLaneOfLastPart(), llvm::VPlanPatternMatch::m_ExtractLastPart(), llvm::VPlanPatternMatch::m_ExtractPenultimateElement(), llvm::PatternMatch::m_FAbs(), llvm::PatternMatch::m_FCanonicalize(), llvm::VPlanPatternMatch::m_FirstActiveLane(), llvm::PatternMatch::m_FMaximum(), llvm::PatternMatch::m_FMaximumNum(), llvm::PatternMatch::m_FMaxNum(), llvm::PatternMatch::m_FMinimum(), llvm::PatternMatch::m_FMinimumNum(), llvm::PatternMatch::m_FMinNum(), llvm::VPlanPatternMatch::m_Freeze(), llvm::PatternMatch::m_FShl(), llvm::PatternMatch::m_FShr(), llvm::VPlanPatternMatch::m_GetElementPtr(), llvm::VPlanPatternMatch::m_ICmp(), llvm::VPlanPatternMatch::m_ICmp(), llvm::PatternMatch::m_Interleave2(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Intrinsic(), llvm::VPlanPatternMatch::m_Intrinsic(), llvm::VPlanPatternMatch::m_Intrinsic(), llvm::VPlanPatternMatch::m_Intrinsic(), llvm::VPlanPatternMatch::m_Intrinsic(), llvm::VPlanPatternMatch::m_LastActiveLane(), llvm::VPlanPatternMatch::m_LogicalAnd(), llvm::VPlanPatternMatch::m_LogicalOr(), llvm::PatternMatch::m_MaskedGather(), llvm::PatternMatch::m_MaskedLoad(), llvm::PatternMatch::m_MaskedStore(), llvm::VPlanPatternMatch::m_Mul(), llvm::VPlanPatternMatch::m_Not(), llvm::VPlanPatternMatch::m_Reverse(), llvm::VPlanPatternMatch::m_ScalarIVSteps(), llvm::SCEVPatternMatch::m_scev_Add(), llvm::SCEVPatternMatch::m_scev_AffineAddRec(), llvm::SCEVPatternMatch::m_scev_AffineAddRec(), llvm::SCEVPatternMatch::m_scev_Binary(), llvm::SCEVPatternMatch::m_scev_c_Mul(), llvm::SCEVPatternMatch::m_scev_c_NUWMul(), llvm::SCEVPatternMatch::m_scev_MinMax(), llvm::SCEVPatternMatch::m_scev_Mul(), llvm::SCEVPatternMatch::m_scev_PtrToInt(), llvm::SCEVPatternMatch::m_scev_SExt(), llvm::SCEVPatternMatch::m_scev_SMax(), llvm::SCEVPatternMatch::m_scev_Trunc(), llvm::SCEVPatternMatch::m_scev_UDiv(), llvm::SCEVPatternMatch::m_scev_Unary(), llvm::SCEVPatternMatch::m_scev_ZExt(), llvm::VPlanPatternMatch::m_Select(), llvm::VPlanPatternMatch::m_SExt(), llvm::VPlanPatternMatch::m_SpecificCmp(), llvm::VPlanPatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_Sqrt(), llvm::VPlanPatternMatch::m_Sub(), llvm::SDPatternMatch::m_TernaryOp(), llvm::VPlanPatternMatch::m_Trunc(), llvm::VPlanPatternMatch::m_TruncOrSelf(), llvm::VPlanPatternMatch::m_UDiv(), llvm::VPlanPatternMatch::m_Unary(), llvm::VPlanPatternMatch::m_VecEndPtr(), llvm::PatternMatch::m_VecReverse(), llvm::PatternMatch::m_VectorInsert(), llvm::VPlanPatternMatch::m_ZExt(), llvm::VPlanPatternMatch::m_ZExtOrSelf(), llvm::VPlanPatternMatch::m_ZExtOrSExt(), llvm::PatternMatch::LogicalOp_match< LHS, RHS, Opcode, Commutable >::match(), matchAndOrChain(), MatchBinarySub(), llvm::SelectionDAG::matchBinOpReduction(), matchDeMorgansLaws(), matchOpWithOpEqZero(), matchOrConcat(), matchPMADDWD(), llvm::MachineIRBuilder::materializeObjectPtrOffset(), llvm::MachineIRBuilder::materializePtrAdd(), mergeHighParts(), moveAddAfterMinMax(), llvm::InstModificationIRStrategy::mutate(), optimizeIncrementingWhile(), optimizeShiftInOrChain(), optimizeUniformIntrinsic(), llvm::AArch64SysReg::parseGenericRegister(), performAddSubIntoVectorOp(), performANDCombine(), performANDCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtBinopLoadFold(), PerformExtractEltCombine(), PerformExtractEltToVMOVRRD(), PerformFAddVSelectCombine(), PerformFMinMaxCombine(), PerformLongShiftCombine(), PerformMinMaxToSatCombine(), performMOVFR2GR_SCombine(), performMOVGR2FR_WCombine(), performMulVectorExtendCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), PerformMVEVMULLCombine(), performORCombine(), performSHLCombine(), performSPLIT_PAIR_F64Combine(), performSRACombine(), performSVEMulAddSubCombine(), performTRUNCATECombine(), performUADDVAddCombine(), performUADDVZextCombine(), performUzpCombine(), PerformVCMPCombine(), performVecReduceAddCombine(), PerformVECTOR_SHUFFLECombine(), performVectorDeinterleaveCombine(), performVectorNonNegToFPCombine(), PerformVMOVDRRCombine(), PerformVMOVhrCombine(), PerformVMOVNCombine(), PerformVMOVRRDCombine(), PerformVQMOVNCombine(), PerformVSetCCToVCTPCombine(), performXORCombine(), performXORCombine(), llvm::AArch64InstPrinter::printInst(), reassociateFCmps(), slpvectorizer::BoUpSLP::VLOperands::reorder(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::replaceSignedInst(), llvm::salvageDebugInfoForDbgValues(), scalarizeExtractedBinOp(), llvm::SCEVPatternMatch::SCEVAffineAddRec_match< Op0_t, Op1_t, Loop_t >::SCEVAffineAddRec_match(), llvm::FastISel::selectBinaryOp(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectExtractValue(), llvm::RISCVDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), signBitMustBeTheSame(), llvm::simplifyAddInst(), simplifyAddInst(), simplifyAndCommutative(), llvm::simplifyAndInst(), simplifyAndInst(), simplifyAndOfICmps(), simplifyAndOfICmpsWithAdd(), simplifyAndOrOfCmps(), simplifyAndOrWithICmpEq(), llvm::simplifyAShrInst(), simplifyAShrInst(), simplifyAssociativeBinOp(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyAssumingCCVal(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::simplifyBinOpSplats(), simplifyByDomEq(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyDemandedBitsForPRMT(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyDiv(), simplifyDivRem(), llvm::simplifyFAddInst(), simplifyFAddInst(), llvm::simplifyFDivInst(), simplifyFDivInst(), llvm::simplifyFMAFMul(), simplifyFMAFMul(), llvm::simplifyFMulInst(), simplifyFMulInst(), llvm::simplifyFreezeInst(), simplifyFreezeInst(), llvm::simplifyFRemInst(), simplifyFRemInst(), llvm::simplifyFSubInst(), simplifyFSubInst(), simplifyIntrinsic(), simplifyIRemMulShl(), simplifyLdexp(), simplifyLogicOfAddSub(), llvm::simplifyLShrInst(), simplifyLShrInst(), llvm::simplifyMulInst(), simplifyMulInst(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), llvm::simplifyOrInst(), simplifyOrInst(), simplifyOrOfICmps(), simplifyOrOfICmpsWithAdd(), simplifyRem(), simplifyRightShift(), llvm::simplifySDivInst(), simplifySDivInst(), llvm::TargetLowering::SimplifySetCC(), simplifyShift(), llvm::simplifyShlInst(), simplifyShlInst(), llvm::simplifyShuffleVectorInst(), simplifyShuffleVectorInst(), llvm::simplifySRemInst(), simplifySRemInst(), llvm::simplifySubInst(), simplifySubInst(), simplifySVEIntReduction(), llvm::simplifyUDivInst(), simplifyUDivInst(), simplifyUnaryIntrinsic(), llvm::simplifyURemInst(), simplifyURemInst(), simplifyX86extrq(), simplifyX86insertq(), llvm::simplifyXorInst(), simplifyXorInst(), llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp(), llvm::SITargetLowering::splitTernaryVectorOp(), swapICmpOperandsToExposeCSEOpportunities(), translateX86FSETCC(), tryCombineExtendRShTrunc(), llvm::InstCombinerImpl::tryFactorizationFolds(), tryFoldBinaryFMul(), tryToRecognizePopCount(), upgradeAbs(), upgradeMaskedCompare(), upgradeX86ALIGNIntrinsics(), upgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), upgradeX86IntrinsicCall(), useSinCos(), llvm::MachineIRBuilder::validateBinaryOp(), llvm::MachineIRBuilder::validateShiftOp(), llvm::MachineIRBuilder::validateUnaryOp(), valueToCarryFlag(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitXor(), widenBuildVector(), and llvm::InstCombinerImpl::~InstCombinerImpl().
Ops
SmallVector<uint64_t, 16> Ops
Definition at line 285 of file CodeGenCommonISel.cpp.
SalvagedExpr
SalvagedExpr = DbgMI->getDebugExpression()
Definition at line 283 of file CodeGenCommonISel.cpp.
Referenced by if(), if(), salvageDbgAssignAddress(), and llvm::salvageDebugInfoForDbgValues().