LLVM: lib/CodeGen/ComplexDeinterleavingPass.cpp File Reference
ComplexDeinterleavingPass.cpp File Reference
#include "llvm/CodeGen/ComplexDeinterleavingPass.h"
#include "llvm/ADT/AllocatorList.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
Classes
struct llvm::DenseMapInfo< ComplexValue >
Macros
#define DEBUG_TYPE "complex-deinterleaving"
Typedefs
typedef SmallVector< struct ComplexValue, 2 > ComplexValues
Functions
STATISTIC (NumComplexTransformations, "Amount of complex patterns transformed")
static bool isInterleavingMask (ArrayRef< int > Mask)
Checks the given mask, and determines whether said mask is interleaving.
static bool isDeinterleavingMask (ArrayRef< int > Mask)
Checks the given mask, and determines whether said mask is deinterleaving.
static bool isNeg (Value *V)
Returns true if the operation is a negation of V, and it works for both integers and floats.
static Value * getNegOperand (Value *V)
Returns the operand for negation operation.
INITIALIZE_PASS_BEGIN (ComplexDeinterleavingLegacyPass, DEBUG_TYPE, "Complex Deinterleaving", false, false) INITIALIZE_PASS_END(ComplexDeinterleavingLegacyPass
static bool isInstructionPairAdd (Instruction *A, Instruction *B)
static bool isInstructionPairMul (Instruction *A, Instruction *B)
static bool isInstructionPotentiallySymmetric (Instruction *I)
static Value * replaceSymmetricNode (IRBuilderBase &B, unsigned Opcode, std::optional< FastMathFlags > Flags, Value *InputA, Value *InputB)
Variables
static cl::opt< bool > ComplexDeinterleavingEnabled ("enable-complex-deinterleaving", cl::desc("Enable generation of complex instructions"), cl::init(true), cl::Hidden)
DEBUG_TYPE
Complex Deinterleaving
Complex false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "complex-deinterleaving"
Definition at line 82 of file ComplexDeinterleavingPass.cpp.
Typedef Documentation
ComplexValues
typedef SmallVector<struct ComplexValue, 2> ComplexValues
Definition at line 127 of file ComplexDeinterleavingPass.cpp.
Function Documentation
getNegOperand()
Value * getNegOperand (Value * V) static
Returns the operand for negation operation.
Definition at line 616 of file ComplexDeinterleavingPass.cpp.
References assert(), llvm::cast(), I, and isNeg().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ComplexDeinterleavingLegacyPass , DEBUG_TYPE , "Complex Deinterleaving" , false , false)
References DEBUG_TYPE.
isDeinterleavingMask()
bool isDeinterleavingMask (ArrayRef< int > Mask) static
Checks the given mask, and determines whether said mask is deinterleaving.
To be deinterleaving, a mask must increment in steps of 2, and either start with 0 or 1. (e.g. an 8x vector deinterleaving mask would be either <0, 2, 4, 6> or <1, 3, 5, 7>).
Definition at line 600 of file ComplexDeinterleavingPass.cpp.
References llvm::Offset.
isInstructionPairAdd()
bool isInstructionPairAdd (Instruction * A, Instruction * B) static
Definition at line 916 of file ComplexDeinterleavingPass.cpp.
References A(), and B().
isInstructionPairMul()
bool isInstructionPairMul (Instruction * A, Instruction * B) static
Definition at line 926 of file ComplexDeinterleavingPass.cpp.
References A(), B(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
isInstructionPotentiallySymmetric()
bool isInstructionPotentiallySymmetric (Instruction * I) static
Definition at line 933 of file ComplexDeinterleavingPass.cpp.
References I.
isInterleavingMask()
bool isInterleavingMask (ArrayRef< int > Mask) static
Checks the given mask, and determines whether said mask is interleaving.
To be interleaving, a mask must alternate between i and i + (Length / 2), and must contain all numbers within the range of [0..Length) (e.g. a 4x vector interleaving mask would be <0, 2, 1, 3>).
Definition at line 585 of file ComplexDeinterleavingPass.cpp.
isNeg()
bool isNeg (Value * V) static
Returns true if the operation is a negation of V, and it works for both integers and floats.
Definition at line 612 of file ComplexDeinterleavingPass.cpp.
References llvm::PatternMatch::m_FNeg(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by DecodeBFLabelOperand(), expandMOVImmSimple(), getNegOperand(), KnuthDiv(), llvm::APIntOps::RoundDoubleToAPInt(), and llvm::APInt::roundToDouble().
replaceSymmetricNode()
Value * replaceSymmetricNode (IRBuilderBase & B, unsigned Opcode, std::optional< FastMathFlags > Flags, Value * InputA, Value * InputB) static
Definition at line 2281 of file ComplexDeinterleavingPass.cpp.
References B(), llvm::cast(), I, and llvm_unreachable.
STATISTIC()
STATISTIC (NumComplexTransformations , "Amount of complex patterns transformed")
Variable Documentation
ComplexDeinterleavingEnabled
cl::opt< bool > ComplexDeinterleavingEnabled("enable-complex-deinterleaving", cl::desc("Enable generation of complex instructions"), cl::init(true), cl::Hidden) ("enable-complex-deinterleaving" , cl::desc("Enable generation of complex instructions") , cl::init(true) , cl::Hidden) static
DEBUG_TYPE
DEBUG_TYPE
Definition at line 531 of file ComplexDeinterleavingPass.cpp.
Deinterleaving
Complex Deinterleaving
Definition at line 532 of file ComplexDeinterleavingPass.cpp.
false
Complex false
Definition at line 532 of file ComplexDeinterleavingPass.cpp.