LLVM: lib/Transforms/Coroutines/CoroAnnotationElide.cpp File Reference
CoroAnnotationElide.cpp File Reference
#include "llvm/Transforms/Coroutines/CoroAnnotationElide.h"
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Analysis.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Transforms/Utils/CallGraphUpdater.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include <cassert>
Macros
#define DEBUG_TYPE "coro-annotation-elide"
Functions
static Instruction * getFirstNonAllocaInTheEntryBlock (Function *F)
static Value * allocateFrameInCaller (Function *Caller, uint64_t FrameSize, Align FrameAlign)
static void processCall (CallBase *CB, Function *Caller, Function *NewCallee, uint64_t FrameSize, Align FrameAlign)
Variables
static cl::opt< float > CoroElideBranchRatio ("coro-elide-branch-ratio", cl::init(0.55), cl::Hidden, cl::desc("Minimum BranchProbability to consider a elide a coroutine."))
cl::opt< unsigned > MinBlockCounterExecution
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-annotation-elide"
Definition at line 37 of file CoroAnnotationElide.cpp.
Function Documentation
allocateFrameInCaller()
Value * allocateFrameInCaller (Function * Caller, uint64_t FrameSize, Align FrameAlign) static
Definition at line 53 of file CoroAnnotationElide.cpp.
References llvm::CallingConv::C, DL, llvm::ArrayType::get(), getFirstNonAllocaInTheEntryBlock(), llvm::Type::getInt8Ty(), and llvm::ilist_node_impl< OptionsT >::getIterator().
Referenced by processCall().
getFirstNonAllocaInTheEntryBlock()
Instruction * getFirstNonAllocaInTheEntryBlock (Function * F) static
Definition at line 44 of file CoroAnnotationElide.cpp.
References F, I, llvm::isa(), and llvm_unreachable.
Referenced by allocateFrameInCaller().
processCall()
void processCall (CallBase * CB, Function * Caller, Function * NewCallee, uint64_t FrameSize, Align FrameAlign) static
Definition at line 70 of file CoroAnnotationElide.cpp.
References allocateFrameInCaller(), llvm::SmallVectorImpl< T >::append(), llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), llvm::CallBase::bundle_op_info_begin(), llvm::CallBase::bundle_op_info_end(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), FramePtr, llvm::CallBase::getAttributes(), llvm::CallBase::getCallingConv(), llvm::Instruction::getDebugLoc(), llvm::Function::getFunctionType(), llvm::ilist_node_impl< OptionsT >::getIterator(), II, llvm::InlineFunction(), IR, llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::CallBase::removeFnAttr(), llvm::Value::replaceAllUsesWith(), llvm::CallBase::setAttributes(), llvm::CallBase::setCalledFunction(), llvm::CallBase::setCallingConv(), and llvm::Instruction::setDebugLoc().
Referenced by llvm::CoroAnnotationElidePass::run().
Variable Documentation
CoroElideBranchRatio
cl::opt< float > CoroElideBranchRatio("coro-elide-branch-ratio", cl::init(0.55), cl::Hidden, cl::desc("Minimum BranchProbability to consider a elide a coroutine.")) ("coro-elide-branch-ratio" , cl::init(0.55) , cl::Hidden , cl::desc("Minimum BranchProbability to consider a elide a coroutine.")) static
Referenced by llvm::CoroAnnotationElidePass::run().
MinBlockCounterExecution
cl::opt<unsigned> MinBlockCounterExecution extern