LLVM: lib/ProfileData/Coverage/CoverageMapping.cpp File Reference
CoverageMapping.cpp File Reference
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Object/BuildID.h"
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdint>
#include <iterator>
#include <map>
#include <memory>
#include <optional>
#include <stack>
#include <string>
#include <system_error>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "coverage-mapping"
Functions
static unsigned getMaxCounterID (const CounterMappingContext &Ctx, const CoverageMappingRecord &Record)
static unsigned getMaxBitmapSize (const CoverageMappingRecord &Record, bool IsVersion11)
Returns the bit count.
static Error handleMaybeNoDataFoundError (Error E)
static SmallBitVector gatherFileIDs (StringRef SourceFile, const FunctionRecord &Function)
static std::optional< unsigned > findMainViewFileID (const FunctionRecord &Function)
Return the ID of the file where the definition of the function is located.
static std::optional< unsigned > findMainViewFileID (StringRef SourceFile, const FunctionRecord &Function)
Check if SourceFile is the file that contains the definition of the Function.
static bool isExpansion (const CountedRegion &R, unsigned FileID)
static std::string getCoverageMapErrString (coveragemap_error Err, const std::string &ErrMsg="")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coverage-mapping"
Definition at line 49 of file CoverageMapping.cpp.
Function Documentation
findMainViewFileID() [1/2]
std::optional< unsigned > findMainViewFileID (const FunctionRecord & Function) static
Return the ID of the file where the definition of the function is located.
Definition at line 1468 of file CoverageMapping.cpp.
References llvm::coverage::CounterMappingRegion::ExpandedFileID, llvm::coverage::CounterMappingRegion::ExpansionRegion, llvm::SmallBitVector::find_first(), I, llvm::coverage::CounterMappingRegion::Kind, and llvm::Function::size().
Referenced by findMainViewFileID(), llvm::coverage::CoverageMapping::getCoverageForFile(), llvm::coverage::CoverageMapping::getCoverageForFunction(), and llvm::coverage::CoverageMapping::getInstantiationGroups().
findMainViewFileID() [2/2]
std::optional< unsigned > findMainViewFileID (StringRef SourceFile, const FunctionRecord & Function) static
Check if SourceFile is the file that contains the definition of the Function.
Return the ID of the file in that case or std::nullopt otherwise.
Definition at line 1483 of file CoverageMapping.cpp.
References findMainViewFileID(), and I.
gatherFileIDs()
SmallBitVector gatherFileIDs (StringRef SourceFile, const FunctionRecord & Function) static
Definition at line 1457 of file CoverageMapping.cpp.
References E(), I, and llvm::Function::size().
Referenced by llvm::coverage::CoverageMapping::getCoverageForFile().
getCoverageMapErrString()
std::string getCoverageMapErrString (coveragemap_error Err, const std::string & ErrMsg = "") static
Definition at line 1644 of file CoverageMapping.cpp.
References llvm::coverage::decompression_failed, llvm::coverage::eof, llvm::coverage::invalid_or_missing_arch_specifier, llvm::coverage::malformed, llvm::coverage::no_data_found, llvm::coverage::success, llvm::coverage::truncated, and llvm::coverage::unsupported_version.
Referenced by llvm::coverage::CoverageMapError::message().
getMaxBitmapSize()
unsigned getMaxBitmapSize (const CoverageMappingRecord & Record, bool IsVersion11) static
Returns the bit count.
Definition at line 662 of file CoverageMapping.cpp.
References llvm::alignTo(), llvm::coverage::mcdc::DecisionParameters::BitmapIdx, llvm::coverage::CounterMappingRegion::MCDCDecisionRegion, llvm::coverage::mcdc::DecisionParameters::NumConditions, and llvm::reverse().
getMaxCounterID()
unsigned getMaxCounterID (const CounterMappingContext & Ctx, const CoverageMappingRecord & Record) static
Definition at line 649 of file CoverageMapping.cpp.
handleMaybeNoDataFoundError()
Error handleMaybeNoDataFoundError (Error E) static
Definition at line 1020 of file CoverageMapping.cpp.
References E(), llvm::coverage::CoverageMapError::get(), llvm::coverage::CoverageMapError::getMessage(), llvm::handleErrors(), llvm::make_error(), llvm::coverage::no_data_found, and llvm::Error::success().
isExpansion()
bool isExpansion (const CountedRegion & R, unsigned FileID) static
Definition at line 1490 of file CoverageMapping.cpp.
References llvm::coverage::CounterMappingRegion::ExpansionRegion.
Referenced by llvm::coverage::CoverageMapping::getCoverageForExpansion(), llvm::coverage::CoverageMapping::getCoverageForFile(), and llvm::coverage::CoverageMapping::getCoverageForFunction().