LLVM: lib/Transforms/Utils/DebugSSAUpdater.cpp File Reference
DebugSSAUpdater.cpp File Reference
#include "llvm/Transforms/Utils/DebugSSAUpdater.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/Transforms/Utils/SSAUpdaterImpl.h"
Classes
class llvm::SSAUpdaterTraits< DebugSSAUpdater >
class llvm::SSAUpdaterTraits< DebugSSAUpdater >::PHI_iterator
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "debug-ssa-updater"
Typedefs
using AvailableValsTy = DenseMap<DbgSSABlock *, DbgValueDef>
Functions
bool isContained (DIScope *Inner, DIScope *Outer)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "debug-ssa-updater"
Definition at line 21 of file DebugSSAUpdater.cpp.
Typedef Documentation
AvailableValsTy
using AvailableValsTy = DenseMap<DbgSSABlock *, DbgValueDef>
Definition at line 43 of file DebugSSAUpdater.cpp.
Function Documentation
isContained()
bool isContained (DIScope * Inner, DIScope * Outer)
Definition at line 221 of file DebugSSAUpdater.cpp.
References llvm::DIScope::getScope(), and isContained().
Referenced by llvm::DbgValueRangeTable::addVariable(), llvm::RegionBase< Tr >::getExitingBlock(), and isContained().