LLVM: lib/Transforms/Utils/DeclareRuntimeLibcalls.cpp File Reference
DeclareRuntimeLibcalls.cpp File Reference
#include "llvm/Transforms/Utils/DeclareRuntimeLibcalls.h"
#include "llvm/Analysis/RuntimeLibcallInfo.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/RuntimeLibcalls.h"
Functions
static void mergeAttributes (LLVMContext &Ctx, const Module &M, const DataLayout &DL, const Triple &TT, Function *Func, FunctionType *FuncTy, AttributeList FuncAttrs)
Function Documentation
mergeAttributes()
void mergeAttributes (LLVMContext & Ctx, const Module & M, const DataLayout & DL, const Triple & TT, Function * Func, FunctionType * FuncTy, AttributeList FuncAttrs) static
Definition at line 20 of file DeclareRuntimeLibcalls.cpp.
References DL, E(), I, and llvm::AttrBuilder::merge().
Referenced by llvm::DeclareRuntimeLibcallsPass::run().