LLVM: lib/IR/DIBuilder.cpp File Reference
DIBuilder.cpp File Reference
#include "llvm/IR/DIBuilder.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include <optional>
Functions
static DIScope * getNonCompileUnitScope (DIScope *N)
If N is compile unit return NULL otherwise return N.
static DIImportedEntity * createImportedModule (LLVMContext &C, dwarf::Tag Tag, DIScope *Context, Metadata *NS, DIFile *File, unsigned Line, StringRef Name, DINodeArray Elements, SmallVectorImpl< TrackingMDNodeRef > &ImportedModules)
static ConstantAsMetadata * getConstantOrNull (Constant *C)
static DITemplateValueParameter * createTemplateValueParameterHelper (LLVMContext &VMContext, unsigned Tag, DIScope *Context, StringRef Name, DIType *Ty, bool IsDefault, Metadata *MD)
static DIType * createTypeWithFlags (const DIType *Ty, DINode::DIFlags FlagsToSet)
static void checkGlobalVariableScope (DIScope *Context)
static DILocalVariable * createLocalVariable (LLVMContext &VMContext, SmallVectorImpl< TrackingMDNodeRef > &PreservedNodes, DIScope *Context, StringRef Name, unsigned ArgNo, DIFile *File, unsigned LineNo, DIType *Ty, bool AlwaysPreserve, DINode::DIFlags Flags, uint32_t AlignInBits, DINodeArray Annotations=nullptr)
template<class... Ts>
static DISubprogram * getSubprogram (bool IsDistinct, Ts &&...Args)
static void initIRBuilder (IRBuilder<> &Builder, const DILocation *DL, InsertPosition InsertPt)
Initialize IRBuilder for inserting dbg.declare and dbg.value intrinsics.
static Value * getDbgIntrinsicValueImpl (LLVMContext &VMContext, Value *V)
Function Documentation
checkGlobalVariableScope()
void checkGlobalVariableScope (DIScope * Context) static
Definition at line 869 of file DIBuilder.cpp.
References assert(), llvm::dyn_cast_or_null(), and getNonCompileUnitScope().
Referenced by llvm::DIBuilder::createGlobalVariableExpression(), and llvm::DIBuilder::createTempGlobalVariableFwdDecl().
createImportedModule()
DIImportedEntity * createImportedModule (LLVMContext & C, dwarf::Tag Tag, DIScope * Context, Metadata * NS, DIFile * File, unsigned Line, StringRef Name, DINodeArray Elements, SmallVectorImpl< TrackingMDNodeRef > & ImportedModules) static
Definition at line 156 of file DIBuilder.cpp.
References assert(), llvm::CallingConv::C, llvm::cast_or_null(), llvm::SmallVectorImpl< T >::emplace_back(), and llvm::MDNode::get().
Referenced by LLVMDIBuilderCreateImportedModuleFromAlias(), LLVMDIBuilderCreateImportedModuleFromModule(), and LLVMDIBuilderCreateImportedModuleFromNamespace().
createLocalVariable()
DILocalVariable * createLocalVariable (LLVMContext & VMContext, SmallVectorImpl< TrackingMDNodeRef > & PreservedNodes, DIScope * Context, StringRef Name, unsigned ArgNo, DIFile * File, unsigned LineNo, DIType * Ty, bool AlwaysPreserve, DINode::DIFlags Flags, uint32_t AlignInBits, DINodeArray Annotations = nullptr) static
Definition at line 911 of file DIBuilder.cpp.
References llvm::cast(), llvm::SmallVectorImpl< T >::emplace_back(), and llvm::MDNode::get().
Referenced by llvm::DIBuilder::createAutoVariable(), and llvm::DIBuilder::createParameterVariable().
createTemplateValueParameterHelper()
DITemplateValueParameter * createTemplateValueParameterHelper (LLVMContext & VMContext, unsigned Tag, DIScope * Context, StringRef Name, DIType * Ty, bool IsDefault, Metadata * MD) static
Definition at line 539 of file DIBuilder.cpp.
References assert(), llvm::MDNode::get(), and llvm::isa().
Referenced by llvm::DIBuilder::createTemplateParameterPack(), llvm::DIBuilder::createTemplateTemplateParameter(), and llvm::DIBuilder::createTemplateValueParameter().
createTypeWithFlags()
DIType * createTypeWithFlags (const DIType * Ty, DINode::DIFlags FlagsToSet) static
Definition at line 743 of file DIBuilder.cpp.
References llvm::DIType::cloneWithFlags(), and llvm::MDNode::replaceWithUniqued().
Referenced by llvm::DIBuilder::createArtificialType(), and llvm::DIBuilder::createObjectPointerType().
getConstantOrNull()
ConstantAsMetadata * getConstantOrNull (Constant * C) static
Definition at line 439 of file DIBuilder.cpp.
References llvm::CallingConv::C, and llvm::ConstantAsMetadata::get().
Referenced by llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createTemplateValueParameter(), and llvm::DIBuilder::createVariantMemberType().
getDbgIntrinsicValueImpl()
Value * getDbgIntrinsicValueImpl (LLVMContext & VMContext, Value * V) static
Definition at line 1119 of file DIBuilder.cpp.
References assert(), llvm::MetadataAsValue::get(), and llvm::ValueAsMetadata::get().
getNonCompileUnitScope()
DIScope * getNonCompileUnitScope (DIScope * N) static
If N is compile unit return NULL otherwise return N.
Definition at line 127 of file DIBuilder.cpp.
References llvm::cast(), llvm::isa(), and N.
Referenced by checkGlobalVariableScope(), llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createBitFieldMemberType(), llvm::DIBuilder::createBitFieldMemberType(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createLexicalBlock(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createReplaceableCompositeType(), llvm::DIBuilder::createSetType(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTemplateAlias(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createVariantMemberType(), llvm::DIBuilder::createVariantMemberType(), and llvm::DIBuilder::createVariantPart().
getSubprogram()
template<class... Ts> DISubprogram * getSubprogram (bool IsDistinct, Ts &&... Args) static
Definition at line 978 of file DIBuilder.cpp.
References llvm::MDNode::get(), and llvm::MDNode::getDistinct().
Referenced by llvm::DIBuilder::createFunction(), llvm::DIBuilder::createMethod(), llvm::DiagnosticInfoRegAllocFailure::DiagnosticInfoRegAllocFailure(), llvm::DiagnosticInfoRegAllocFailure::DiagnosticInfoRegAllocFailure(), llvm::DiagnosticInfoResourceLimit::DiagnosticInfoResourceLimit(), getSubprogram(), LLVMGetSubprogram(), llvm::OptimizationRemark::OptimizationRemark(), llvm::OptimizationRemarkAnalysis::OptimizationRemarkAnalysis(), and llvm::OptimizationRemarkMissed::OptimizationRemarkMissed().
initIRBuilder()
void initIRBuilder (IRBuilder<> & Builder, const DILocation * DL, InsertPosition InsertPt) static
Initialize IRBuilder for inserting dbg.declare and dbg.value intrinsics.
This abstracts over the various ways to specify an insert position.
Definition at line 1113 of file DIBuilder.cpp.
References DL, and llvm::InsertPosition::getBasicBlock().