LLVM: lib/DebugInfo/DWARF/DWARFDie.cpp File Reference
DWARFDie.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
#include "llvm/DebugInfo/DWARF/DWARFExpressionPrinter.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFTypePrinter.h"
#include "llvm/DebugInfo/DWARF/DWARFTypeUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFExpression.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <string>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static void dumpApplePropertyAttribute (raw_ostream &OS, uint64_t Val)
static void dumpRanges (const DWARFObject &Obj, raw_ostream &OS, const DWARFAddressRangesVector &Ranges, unsigned AddressSize, unsigned Indent, const DIDumpOptions &DumpOpts)
static void dumpLocationList (raw_ostream &OS, const DWARFFormValue &FormValue, DWARFUnit *U, unsigned Indent, DIDumpOptions DumpOpts)
static void dumpLocationExpr (raw_ostream &OS, const DWARFFormValue &FormValue, DWARFUnit *U, unsigned Indent, DIDumpOptions DumpOpts)
static DWARFDie resolveReferencedType (DWARFDie D, DWARFFormValue F)
static llvm::StringRef prettyLanguageVersionString (const DWARFAttribute &AttrValue, const DWARFDie &Die)
static llvm::Expected< llvm::StringRef > getApplePropertyName (const DWARFDie &PropDIE)
static void dumpAttribute (raw_ostream &OS, const DWARFDie &Die, const DWARFAttribute &AttrValue, unsigned Indent, DIDumpOptions DumpOpts)
static std::optional< uint64_t > getTypeSizeImpl (DWARFDie Die, uint64_t PointerSize, SmallPtrSetImpl< const DWARFDebugInfoEntry * > &Visited)
static unsigned dumpParentChain (DWARFDie Die, raw_ostream &OS, unsigned Indent, DIDumpOptions DumpOpts, unsigned Depth=0)
Helper to dump a DIE with all of its parents, but no siblings.
LLVM_ABI void llvm::dumpTypeQualifiedName (const DWARFDie &DIE, raw_ostream &OS)
LLVM_ABI void llvm::dumpTypeUnqualifiedName (const DWARFDie &DIE, raw_ostream &OS, std::string *OriginalFullName=nullptr)
Function Documentation
dumpApplePropertyAttribute()
void dumpApplePropertyAttribute (raw_ostream & OS, uint64_t Val) static
Definition at line 39 of file DWARFDie.cpp.
References llvm::dwarf::ApplePropertyString(), assert(), llvm::countr_zero(), and llvm::format().
Referenced by dumpAttribute().
dumpAttribute()
void dumpAttribute (raw_ostream & OS, const DWARFDie & Die, const DWARFAttribute & AttrValue, unsigned Indent, DIDumpOptions DumpOpts) static
Definition at line 150 of file DWARFDie.cpp.
References llvm::DILineInfoSpecifier::AbsoluteFilePath, llvm::DWARFAttribute::Attr, llvm::Attribute, llvm::dwarf::AttributeValueString(), llvm::dwarf::computeTombstoneAddress(), llvm::DWARFFormValue::createFromUValue(), llvm::createStringError(), D(), llvm::DWARFFormValue::dump(), llvm::DWARFFormValue::dumpAddress(), dumpApplePropertyAttribute(), dumpLocationExpr(), dumpLocationList(), dumpRanges(), llvm::dumpTypeQualifiedName(), llvm::StringRef::empty(), llvm::Enumerator, llvm::DWARFFormValue::FC_Block, llvm::DWARFFormValue::FC_Exprloc, llvm::DWARFFormValue::FC_SectionOffset, llvm::formatv(), llvm::DWARFDie::getAddressRanges(), getApplePropertyName(), llvm::DWARFFormValue::getAsAddress(), llvm::DWARFFormValue::getAsSectionOffset(), llvm::DWARFFormValue::getAsUnsignedConstant(), llvm::DWARFDie::getAttributeValueAsReferencedDie(), llvm::DWARFUnit::getContext(), llvm::DWARFContext::getDWARFObj(), llvm::DWARFDie::getDwarfUnit(), llvm::DWARFFormValue::getForm(), llvm::DWARFDie::getLowAndHighPC(), llvm::DWARFDie::getName(), llvm::raw_ostream::indent(), llvm::invalid_argument, llvm::DWARFFormValue::isFormClass(), llvm::DWARFDie::isValid(), llvm::LinkageName, llvm::DWARFAttribute::mayHaveLocationExpr(), llvm::DWARFAttribute::mayHaveLocationList(), prettyLanguageVersionString(), llvm::DIDumpOptions::RecoverableErrorHandler, resolveReferencedType(), llvm::DIDumpOptions::ShowAddresses, llvm::DIDumpOptions::ShowForm, llvm::String, llvm::dwarf::toString(), llvm::DWARFAttribute::Value, and llvm::DIDumpOptions::Verbose.
Referenced by llvm::DWARFDie::dump().
dumpLocationExpr()
void dumpLocationExpr (raw_ostream & OS, const DWARFFormValue & FormValue, DWARFUnit * U, unsigned Indent, DIDumpOptions DumpOpts) static
Definition at line 91 of file DWARFDie.cpp.
References assert(), llvm::Data, llvm::ArrayRef< T >::data(), llvm::DWARFFormValue::FC_Block, llvm::DWARFFormValue::FC_Exprloc, llvm::DWARFFormValue::getAsBlock(), llvm::DWARFFormValue::isFormClass(), llvm::printDwarfExpression(), and llvm::ArrayRef< T >::size().
Referenced by dumpAttribute().
dumpLocationList()
void dumpLocationList (raw_ostream & OS, const DWARFFormValue & FormValue, DWARFUnit * U, unsigned Indent, DIDumpOptions DumpOpts) static
Definition at line 71 of file DWARFDie.cpp.
References assert(), llvm::DWARFFormValue::dump(), llvm::DWARFFormValue::FC_SectionOffset, llvm::DWARFFormValue::getAsSectionOffset(), llvm::DWARFFormValue::getForm(), llvm::DWARFFormValue::isFormClass(), and llvm::Offset.
Referenced by llvm::DWARFDebugLoc::dump(), dumpAttribute(), and llvm::DWARFDebugLoclists::dumpRange().
dumpParentChain()
unsigned dumpParentChain (DWARFDie Die, raw_ostream & OS, unsigned Indent, DIDumpOptions DumpOpts, unsigned Depth = 0) static
Helper to dump a DIE with all of its parents, but no siblings.
Definition at line 651 of file DWARFDie.cpp.
References llvm::Depth, llvm::DWARFDie::dump(), dumpParentChain(), llvm::DWARFDie::getParent(), and llvm::DIDumpOptions::ParentRecurseDepth.
Referenced by llvm::DWARFDie::dump(), and dumpParentChain().
dumpRanges()
void dumpRanges (const DWARFObject & Obj, raw_ostream & OS, const DWARFAddressRangesVector & Ranges, unsigned AddressSize, unsigned Indent, const DIDumpOptions & DumpOpts) static
Definition at line 57 of file DWARFDie.cpp.
References llvm::raw_ostream::indent(), and llvm::DIDumpOptions::ShowAddresses.
Referenced by dumpAttribute().
getApplePropertyName()
llvm::Expected< llvm::StringRef > getApplePropertyName (const DWARFDie & PropDIE) static
Definition at line 132 of file DWARFDie.cpp.
References llvm::createStringError(), llvm::DWARFDie::find(), and llvm::DWARFDie::getTag().
Referenced by dumpAttribute().
getTypeSizeImpl()
std::optional< uint64_t > getTypeSizeImpl (DWARFDie Die, uint64_t PointerSize, SmallPtrSetImpl< const DWARFDebugInfoEntry * > & Visited) static
Definition at line 579 of file DWARFDie.cpp.
References llvm::DWARFDie::find(), llvm::DWARFDie::getAttributeValueAsReferencedDie(), llvm::DWARFDie::getDebugInfoEntry(), llvm::DWARFDie::getTag(), getTypeSizeImpl(), llvm::SmallPtrSetImpl< PtrType >::insert(), and Size.
Referenced by llvm::DWARFDie::getTypeSize(), and getTypeSizeImpl().
prettyLanguageVersionString()
llvm::StringRef prettyLanguageVersionString (const DWARFAttribute & AttrValue, const DWARFDie & Die) static
Definition at line 110 of file DWARFDie.cpp.
References llvm::DWARFAttribute::Attr, llvm::DWARFDie::find(), llvm::DWARFFormValue::getAsUnsignedConstant(), llvm::dwarf::LanguageDescription(), and llvm::DWARFAttribute::Value.
Referenced by dumpAttribute().
resolveReferencedType()
DWARFDie resolveReferencedType (DWARFDie D, DWARFFormValue F) static
Definition at line 105 of file DWARFDie.cpp.
References D(), and F.
Referenced by dumpAttribute().