LLVM: lib/DWARFCFIChecker/DWARFCFIAnalysis.cpp File Reference
DWARFCFIAnalysis.cpp File Reference
#include "llvm/DWARFCFIChecker/DWARFCFIAnalysis.h"
#include "Registers.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/DWARFCFIChecker/DWARFCFIState.h"
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFUnwindTable.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegister.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include <optional>
Classes
struct CFARegOffsetInfo
Functions
static std::optional< CFARegOffsetInfo > getCFARegOffsetInfo (const dwarf::UnwindRow &UnwindRow)
static SmallSet< DWARFRegNum, 4 > getUnwindRuleRegSet (const dwarf::UnwindRow &UnwindRow, DWARFRegNum Reg)
Function Documentation
getCFARegOffsetInfo()
std::optional< CFARegOffsetInfo > getCFARegOffsetInfo (const dwarf::UnwindRow & UnwindRow) static
Definition at line 47 of file DWARFCFIAnalysis.cpp.
References llvm::dwarf::UnwindRow::getCFAValue(), and llvm::dwarf::UnwindLocation::RegPlusOffset.
Referenced by llvm::DWARFCFIAnalysis::DWARFCFIAnalysis().
getUnwindRuleRegSet()
SmallSet< DWARFRegNum, 4 > getUnwindRuleRegSet (const dwarf::UnwindRow & UnwindRow, DWARFRegNum Reg) static
Definition at line 57 of file DWARFCFIAnalysis.cpp.
References assert(), llvm::dwarf::UnwindLocation::CFAPlusOffset, llvm::dwarf::UnwindLocation::Constant, llvm::dwarf::UnwindLocation::DWARFExpr, llvm::dwarf::RegisterLocations::getRegisterLocation(), llvm::dwarf::UnwindRow::getRegisterLocations(), llvm_unreachable, Reg, llvm::dwarf::UnwindLocation::RegPlusOffset, llvm::dwarf::UnwindLocation::Same, llvm::dwarf::UnwindLocation::Undefined, and llvm::dwarf::UnwindLocation::Unspecified.