LLVM: lib/Target/DirectX/DXILIntrinsicExpansion.cpp File Reference
DXILIntrinsicExpansion.cpp File Reference
#include "DXILIntrinsicExpansion.h"
#include "DirectX.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
Classes
class DXILIntrinsicExpansionLegacy
Macros
#define DEBUG_TYPE "dxil-intrinsic-expansion"
Functions
static bool resourceAccessNeeds64BitExpansion (Module *M, Type *OverloadTy, bool IsRaw)
static Value * expand16BitIsInf (CallInst *Orig)
static Value * expand16BitIsNaN (CallInst *Orig)
static Value * expand16BitIsFinite (CallInst *Orig)
static Value * expand16BitIsNormal (CallInst *Orig)
static bool isIntrinsicExpansion (Function &F)
static Value * expandUsubSat (CallInst *Orig)
static Value * expandVecReduceAdd (CallInst *Orig, Intrinsic::ID IntrinsicId)
static Value * expandAbs (CallInst *Orig)
static Value * expandCrossIntrinsic (CallInst *Orig)
static Value * expandFloatDotIntrinsic (CallInst *Orig, Value *A, Value *B)
static Value * expandFloatDotIntrinsic (CallInst *Orig)
static Value * expandIntegerDotIntrinsic (CallInst *Orig, Intrinsic::ID DotIntrinsic)
static Value * expandExpIntrinsic (CallInst *Orig)
static Value * expandIsFPClass (CallInst *Orig)
static Value * expandAnyOrAllIntrinsic (CallInst *Orig, Intrinsic::ID IntrinsicId)
static Value * expandLerpIntrinsic (CallInst *Orig)
static Value * expandLogIntrinsic (CallInst *Orig, float LogConstVal=numbers::ln2f)
static Value * expandLog10Intrinsic (CallInst *Orig)
static Value * expandNormalizeIntrinsic (CallInst *Orig)
static Value * expandAtan2Intrinsic (CallInst *Orig)
template<bool LeftFunnel>
static Value * expandFunnelShiftIntrinsic (CallInst *Orig)
static Value * expandPowIntrinsic (CallInst *Orig, Intrinsic::ID IntrinsicId)
static Value * expandStepIntrinsic (CallInst *Orig)
static Value * expandRadiansIntrinsic (CallInst *Orig)
static bool expandBufferLoadIntrinsic (CallInst *Orig, bool IsRaw)
static bool expandBufferStoreIntrinsic (CallInst *Orig, bool IsRaw)
static Intrinsic::ID getMaxForClamp (Intrinsic::ID ClampIntrinsic)
static Intrinsic::ID getMinForClamp (Intrinsic::ID ClampIntrinsic)
static Value * expandClampIntrinsic (CallInst *Orig, Intrinsic::ID ClampIntrinsic)
static Value * expandDegreesIntrinsic (CallInst *Orig)
static Value * expandSignIntrinsic (CallInst *Orig)
static bool expandIntrinsic (Function &F, CallInst *Orig)
static bool expansionIntrinsics (Module &M)
INITIALIZE_PASS_BEGIN (DXILIntrinsicExpansionLegacy, DEBUG_TYPE, "DXIL Intrinsic Expansion", false, false) INITIALIZE_PASS_END(DXILIntrinsicExpansionLegacy
Variables
DEBUG_TYPE
DXIL Intrinsic Expansion
DXIL Intrinsic false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-intrinsic-expansion"
Definition at line 33 of file DXILIntrinsicExpansion.cpp.
Function Documentation
expand16BitIsFinite()
Value * expand16BitIsFinite (CallInst * Orig) static
Definition at line 136 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::ElementCount::getFixed(), llvm::Type::getInt16Ty(), llvm::Instruction::getModule(), getNumElements(), llvm::User::getOperand(), llvm::ConstantVector::getSplat(), and llvm::Value::getType().
Referenced by expandIsFPClass().
expand16BitIsInf()
Value * expand16BitIsInf (CallInst * Orig) static
Definition at line 55 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::ElementCount::getFixed(), llvm::Type::getInt16Ty(), llvm::Instruction::getModule(), getNumElements(), llvm::User::getOperand(), llvm::ConstantVector::getSplat(), and llvm::Value::getType().
Referenced by expandIntrinsic(), and expandIsFPClass().
expand16BitIsNaN()
Value * expand16BitIsNaN (CallInst * Orig) static
Definition at line 90 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::ElementCount::getFixed(), llvm::Type::getInt16Ty(), llvm::Instruction::getModule(), getNumElements(), llvm::User::getOperand(), llvm::ConstantVector::getSplat(), and llvm::Value::getType().
Referenced by expandIntrinsic(), and expandIsFPClass().
expand16BitIsNormal()
Value * expand16BitIsNormal (CallInst * Orig) static
Definition at line 163 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::ElementCount::getFixed(), llvm::Type::getInt16Ty(), llvm::Instruction::getModule(), getNumElements(), llvm::User::getOperand(), llvm::ConstantVector::getSplat(), and llvm::Value::getType().
Referenced by expandIsFPClass().
expandAbs()
Value * expandAbs (CallInst * Orig) static
Definition at line 296 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::ElementCount::getFixed(), getNumElements(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and X.
Referenced by expandIntrinsic().
expandAnyOrAllIntrinsic()
Value * expandAnyOrAllIntrinsic (CallInst * Orig, Intrinsic::ID IntrinsicId) static
Definition at line 505 of file DXILIntrinsicExpansion.cpp.
References assert(), Cond, llvm::dyn_cast(), llvm::ElementCount::getFixed(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), I, llvm::Type::isFloatingPointTy(), and X.
Referenced by expandIntrinsic().
expandAtan2Intrinsic()
Value * expandAtan2Intrinsic (CallInst * Orig) static
Definition at line 615 of file DXILIntrinsicExpansion.cpp.
References llvm::CallBase::getAttributes(), llvm::Instruction::getFastMathFlags(), llvm::User::getOperand(), llvm::CallInst::isTailCall(), llvm::numbers::pi, llvm::CallBase::setAttributes(), llvm::CallInst::setTailCall(), X, and Y.
Referenced by expandIntrinsic().
expandBufferLoadIntrinsic()
bool expandBufferLoadIntrinsic (CallInst * Orig, bool IsRaw) static
Definition at line 770 of file DXILIntrinsicExpansion.cpp.
References assert(), llvm::sampleprof::Base, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::PoisonValue::get(), llvm::StructType::get(), llvm::VectorType::get(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Type::getStructElementType(), llvm::Value::getType(), llvm::Hi, I, llvm::Type::isDoubleTy(), llvm::Type::isIntegerTy(), llvm_unreachable, llvm::Lo, llvm::make_early_inc_range(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ArrayRef< T >::size(), and llvm::Value::users().
Referenced by expandIntrinsic().
expandBufferStoreIntrinsic()
bool expandBufferStoreIntrinsic (CallInst * Orig, bool IsRaw) static
Definition at line 881 of file DXILIntrinsicExpansion.cpp.
References assert(), llvm::sampleprof::Base, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::PoisonValue::get(), llvm::StructType::get(), llvm::VectorType::get(), llvm::ElementCount::getFixed(), llvm::CallBase::getFunctionType(), llvm::User::getOperand(), llvm::FunctionType::getParamType(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), I, llvm::Int32Ty, llvm::Type::isDoubleTy(), and llvm::Type::isIntegerTy().
Referenced by expandIntrinsic().
expandClampIntrinsic()
Value * expandClampIntrinsic (CallInst * Orig, Intrinsic::ID ClampIntrinsic) static
Definition at line 999 of file DXILIntrinsicExpansion.cpp.
References getMaxForClamp(), getMinForClamp(), llvm::User::getOperand(), and X.
Referenced by expandIntrinsic().
expandCrossIntrinsic()
Value * expandCrossIntrinsic (CallInst * Orig) static
Definition at line 312 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::PoisonValue::get(), llvm::Value::getName(), getNumElements(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::reportFatalUsageError().
Referenced by expandIntrinsic().
expandDegreesIntrinsic()
Value * expandDegreesIntrinsic (CallInst * Orig) static
Definition at line 1012 of file DXILIntrinsicExpansion.cpp.
References llvm::User::getOperand(), llvm::numbers::inv_pi, and X.
Referenced by expandIntrinsic().
expandExpIntrinsic()
Value * expandExpIntrinsic (CallInst * Orig) static
Definition at line 430 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::CallBase::getAttributes(), llvm::ElementCount::getFixed(), getNumElements(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::CallInst::isTailCall(), llvm::numbers::log2ef, and X.
Referenced by expandIntrinsic().
expandFloatDotIntrinsic() [1/2]
Value * expandFloatDotIntrinsic (CallInst * Orig) static
Definition at line 391 of file DXILIntrinsicExpansion.cpp.
References expandFloatDotIntrinsic(), and llvm::User::getOperand().
expandFloatDotIntrinsic() [2/2]
Value * expandFloatDotIntrinsic (CallInst * Orig, Value * A, Value * B) static
Definition at line 350 of file DXILIntrinsicExpansion.cpp.
References A(), assert(), B(), llvm::dyn_cast(), llvm::Type::getScalarType(), I, llvm::Type::isFloatingPointTy(), llvm::Type::isVectorTy(), and llvm::reportFatalUsageError().
Referenced by expandFloatDotIntrinsic(), expandIntrinsic(), and expandNormalizeIntrinsic().
expandFunnelShiftIntrinsic()
template<bool LeftFunnel> Value * expandFunnelShiftIntrinsic (CallInst * Orig) static
Definition at line 664 of file DXILIntrinsicExpansion.cpp.
References A(), assert(), B(), llvm::BitWidth, llvm::User::getOperand(), llvm::Value::getType(), and llvm::isPowerOf2_32().
Referenced by expandIntrinsic().
expandIntegerDotIntrinsic()
Value * expandIntegerDotIntrinsic (CallInst * Orig, Intrinsic::ID DotIntrinsic) static
Definition at line 397 of file DXILIntrinsicExpansion.cpp.
References A(), assert(), B(), llvm::dyn_cast(), llvm::User::getOperand(), llvm::Type::getScalarType(), I, llvm::Type::isIntegerTy(), and llvm::Type::isVectorTy().
Referenced by expandIntrinsic().
expandIntrinsic()
bool expandIntrinsic (Function & F, CallInst * Orig) static
Definition at line 1046 of file DXILIntrinsicExpansion.cpp.
References llvm::Instruction::eraseFromParent(), expand16BitIsInf(), expand16BitIsNaN(), expandAbs(), expandAnyOrAllIntrinsic(), expandAtan2Intrinsic(), expandBufferLoadIntrinsic(), expandBufferStoreIntrinsic(), expandClampIntrinsic(), expandCrossIntrinsic(), expandDegreesIntrinsic(), expandExpIntrinsic(), expandFloatDotIntrinsic(), expandFunnelShiftIntrinsic(), expandIntegerDotIntrinsic(), expandIsFPClass(), expandLerpIntrinsic(), expandLog10Intrinsic(), expandLogIntrinsic(), expandNormalizeIntrinsic(), expandPowIntrinsic(), expandRadiansIntrinsic(), expandSignIntrinsic(), expandStepIntrinsic(), expandUsubSat(), expandVecReduceAdd(), F, and llvm::Value::replaceAllUsesWith().
Referenced by expansionIntrinsics().
expandIsFPClass()
Value * expandIsFPClass (CallInst * Orig) static
Definition at line 449 of file DXILIntrinsicExpansion.cpp.
References llvm::BitWidth, llvm::dyn_cast(), expand16BitIsFinite(), expand16BitIsInf(), expand16BitIsNaN(), expand16BitIsNormal(), F, llvm::fcFinite, llvm::fcInf, llvm::fcNan, llvm::fcNegZero, llvm::fcNormal, llvm::FixedVectorType::get(), llvm::CallBase::getArgOperand(), llvm::Type::getIntNTy(), llvm::Type::getPrimitiveSizeInBits(), llvm::reportFatalUsageError(), and T.
Referenced by expandIntrinsic().
expandLerpIntrinsic()
Value * expandLerpIntrinsic (CallInst * Orig) static
Definition at line 546 of file DXILIntrinsicExpansion.cpp.
References llvm::User::getOperand(), X, and Y.
Referenced by expandIntrinsic().
expandLog10Intrinsic()
Value * expandLog10Intrinsic (CallInst * Orig) static
Definition at line 574 of file DXILIntrinsicExpansion.cpp.
References expandLogIntrinsic(), llvm::numbers::ln10f, and llvm::numbers::ln2f.
Referenced by expandIntrinsic().
expandLogIntrinsic()
Value * expandLogIntrinsic (CallInst * Orig, float LogConstVal = numbers::ln2f) static
Definition at line 556 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::CallBase::getAttributes(), llvm::ElementCount::getFixed(), getNumElements(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::CallInst::isTailCall(), llvm::numbers::ln2f, and X.
Referenced by expandIntrinsic(), and expandLog10Intrinsic().
expandNormalizeIntrinsic()
Value * expandNormalizeIntrinsic (CallInst * Orig) static
Definition at line 580 of file DXILIntrinsicExpansion.cpp.
References llvm::dyn_cast(), expandFloatDotIntrinsic(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::APFloat::isZero(), llvm::reportFatalUsageError(), and X.
Referenced by expandIntrinsic().
expandPowIntrinsic()
Value * expandPowIntrinsic (CallInst * Orig, Intrinsic::ID IntrinsicId) static
Definition at line 720 of file DXILIntrinsicExpansion.cpp.
References llvm::CallBase::getAttributes(), llvm::User::getOperand(), llvm::CallInst::isTailCall(), Mul, X, and Y.
Referenced by expandIntrinsic().
expandRadiansIntrinsic()
Value * expandRadiansIntrinsic (CallInst * Orig) static
Definition at line 762 of file DXILIntrinsicExpansion.cpp.
References llvm::User::getOperand(), llvm::numbers::pi, and X.
Referenced by expandIntrinsic().
expandSignIntrinsic()
Value * expandSignIntrinsic (CallInst * Orig) static
Definition at line 1020 of file DXILIntrinsicExpansion.cpp.
References assert(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), and X.
Referenced by expandIntrinsic().
expandStepIntrinsic()
Value * expandStepIntrinsic (CallInst * Orig) static
Definition at line 740 of file DXILIntrinsicExpansion.cpp.
References Cond, llvm::dyn_cast(), llvm::ElementCount::getFixed(), llvm::User::getOperand(), llvm::ConstantVector::getSplat(), X, and Y.
Referenced by expandIntrinsic().
expandUsubSat()
Value * expandUsubSat (CallInst * Orig) static
Definition at line 251 of file DXILIntrinsicExpansion.cpp.
References A(), B(), llvm::CallBase::getArgOperand(), and llvm::Sub.
Referenced by expandIntrinsic().
expandVecReduceAdd()
Value * expandVecReduceAdd (CallInst * Orig, Intrinsic::ID IntrinsicId) static
Definition at line 264 of file DXILIntrinsicExpansion.cpp.
References assert(), llvm::dyn_cast(), llvm::User::getOperand(), I, llvm::Constant::isZeroValue(), and X.
Referenced by expandIntrinsic().
expansionIntrinsics()
bool expansionIntrinsics (Module & M) static
Definition at line 1156 of file DXILIntrinsicExpansion.cpp.
References llvm::dyn_cast(), expandIntrinsic(), F, isIntrinsicExpansion(), and llvm::make_early_inc_range().
Referenced by llvm::DXILIntrinsicExpansion::run(), and DXILIntrinsicExpansionLegacy::runOnModule().
getMaxForClamp()
Intrinsic::ID getMaxForClamp (Intrinsic::ID ClampIntrinsic) static
Definition at line 981 of file DXILIntrinsicExpansion.cpp.
References assert().
Referenced by expandClampIntrinsic().
getMinForClamp()
Intrinsic::ID getMinForClamp (Intrinsic::ID ClampIntrinsic) static
Definition at line 990 of file DXILIntrinsicExpansion.cpp.
References assert().
Referenced by expandClampIntrinsic().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILIntrinsicExpansionLegacy , DEBUG_TYPE , "DXIL Intrinsic Expansion" , false , false)
References DEBUG_TYPE.
isIntrinsicExpansion()
bool isIntrinsicExpansion (Function & F) static
Definition at line 199 of file DXILIntrinsicExpansion.cpp.
References F, and resourceAccessNeeds64BitExpansion().
Referenced by expansionIntrinsics().
resourceAccessNeeds64BitExpansion()
bool resourceAccessNeeds64BitExpansion (Module * M, Type * OverloadTy, bool IsRaw) static
Definition at line 46 of file DXILIntrinsicExpansion.cpp.
References llvm::Type::getScalarType(), llvm::Type::isDoubleTy(), and llvm::Type::isIntegerTy().
Referenced by isIntrinsicExpansion().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 1188 of file DXILIntrinsicExpansion.cpp.
Expansion
DXIL Intrinsic Expansion
Definition at line 1189 of file DXILIntrinsicExpansion.cpp.
Referenced by llvm::coverage::CoverageMapping::getCoverageForExpansion().
false
DXIL Intrinsic false
Definition at line 1189 of file DXILIntrinsicExpansion.cpp.