LLVM: lib/Target/DirectX/DXILTranslateMetadata.cpp File Reference
DXILTranslateMetadata.cpp File Reference
#include "DXILTranslateMetadata.h"
#include "DXILRootSignature.h"
#include "DXILShaderFlags.h"
#include "DirectX.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/DXILMetadataAnalysis.h"
#include "llvm/Analysis/DXILResource.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/VersionTuple.h"
#include "llvm/TargetParser/Triple.h"
#include <cstdint>
Typedefs
using InstructionMDList = std::array<unsigned, 7>
using GlobalMDList = std::array<StringLiteral, 7>
Functions
static NamedMDNode * emitResourceMetadata (Module &M, DXILResourceMap &DRM, DXILResourceTypeMap &DRTM)
static StringRef getShortShaderStage (Triple::EnvironmentType Env)
static uint32_t getShaderStage (Triple::EnvironmentType Env)
static SmallVector< Metadata * > getTagValueAsMetadata (EntryPropsTag Tag, uint64_t Value, LLVMContext &Ctx)
static MDTuple * getEntryPropAsMetadata (Module &M, const EntryProperties &EP, uint64_t EntryShaderFlags, const ModuleMetadataInfo &MMDI)
static MDTuple * constructEntryMetadata (const Function *EntryFn, MDTuple *Signatures, MDNode *Resources, MDTuple *Properties, LLVMContext &Ctx)
static MDTuple * emitEntryMD (Module &M, const EntryProperties &EP, MDTuple *Signatures, MDNode *MDResources, const uint64_t EntryShaderFlags, const ModuleMetadataInfo &MMDI)
static void emitValidatorVersionMD (Module &M, const ModuleMetadataInfo &MMDI)
static void emitShaderModelVersionMD (Module &M, const ModuleMetadataInfo &MMDI)
static void emitDXILVersionTupleMD (Module &M, const ModuleMetadataInfo &MMDI)
static MDTuple * emitTopLevelLibraryNode (Module &M, MDNode *RMD, uint64_t ShaderFlags)
static void translateBranchMetadata (Module &M, Instruction *BBTerminatorInst)
static bool isLoopMDCompatible (Module &M, Metadata *MD)
static void translateLoopMetadata (Module &M, Instruction *I, MDNode *BaseMD)
static InstructionMDList getCompatibleInstructionMDs (llvm::Module &M)
static void translateInstructionMetadata (Module &M)
static void cleanModuleFlags (Module &M)
static void translateGlobalMetadata (Module &M, DXILResourceMap &DRM, DXILResourceTypeMap &DRTM, const ModuleShaderFlags &ShaderFlags, const ModuleMetadataInfo &MMDI)
INITIALIZE_PASS_BEGIN (DXILTranslateMetadataLegacy, "dxil-translate-metadata", "DXIL Translate Metadata", false, false) INITIALIZE_PASS_END(DXILTranslateMetadataLegacy
Variables
static GlobalMDList CompatibleNamedModuleMDs
dxil translate metadata
dxil translate DXIL Translate Metadata
dxil translate DXIL Translate false
Typedef Documentation
GlobalMDList
using GlobalMDList = std::array<StringLiteral, 7>
Definition at line 517 of file DXILTranslateMetadata.cpp.
InstructionMDList
using InstructionMDList = std::array<unsigned, 7>
Definition at line 460 of file DXILTranslateMetadata.cpp.
Function Documentation
cleanModuleFlags()
void cleanModuleFlags (Module & M) static
Definition at line 492 of file DXILTranslateMetadata.cpp.
References llvm::Module::AppendUnique, llvm::NamedMDNode::eraseFromParent(), and llvm::Module::Warning.
Referenced by translateGlobalMetadata().
constructEntryMetadata()
MDTuple * constructEntryMetadata (const Function * EntryFn, MDTuple * Signatures, MDNode * Resources, MDTuple * Properties, LLVMContext & Ctx) static
Definition at line 263 of file DXILTranslateMetadata.cpp.
References llvm::MDNode::get(), llvm::MDString::get(), llvm::ValueAsMetadata::get(), and llvm::Value::getName().
Referenced by emitEntryMD(), and emitTopLevelLibraryNode().
emitDXILVersionTupleMD()
void emitDXILVersionTupleMD (Module & M, const ModuleMetadataInfo & MMDI) static
Definition at line 321 of file DXILTranslateMetadata.cpp.
References llvm::NamedMDNode::addOperand(), llvm::dxil::ModuleMetadataInfo::DXILVersion, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::IRBuilderBase::getInt32(), llvm::VersionTuple::getMajor(), and llvm::VersionTuple::getMinor().
Referenced by translateGlobalMetadata().
emitEntryMD()
MDTuple * emitEntryMD (Module & M, const EntryProperties & EP, MDTuple * Signatures, MDNode * MDResources, const uint64_t EntryShaderFlags, const ModuleMetadataInfo & MMDI) static
Definition at line 282 of file DXILTranslateMetadata.cpp.
References constructEntryMetadata(), llvm::dxil::EntryProperties::Entry, llvm::Function::getContext(), and getEntryPropAsMetadata().
Referenced by translateGlobalMetadata().
emitResourceMetadata()
NamedMDNode * emitResourceMetadata (Module & M, DXILResourceMap & DRM, DXILResourceTypeMap & DRTM) static
Definition at line 90 of file DXILTranslateMetadata.cpp.
References llvm::NamedMDNode::addOperand(), llvm::DXILResourceMap::cbuffers(), llvm::DXILResourceMap::empty(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::MDNode::get(), nullptr, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::DXILResourceMap::samplers(), llvm::DXILResourceMap::srvs(), and llvm::DXILResourceMap::uavs().
Referenced by translateGlobalMetadata().
emitShaderModelVersionMD()
void emitShaderModelVersionMD (Module & M, const ModuleMetadataInfo & MMDI) static
Definition at line 308 of file DXILTranslateMetadata.cpp.
References llvm::NamedMDNode::addOperand(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::IRBuilderBase::getInt32(), getShortShaderStage(), llvm::dxil::ModuleMetadataInfo::ShaderModelVersion, llvm::dxil::ModuleMetadataInfo::ShaderProfile, and SM().
Referenced by translateGlobalMetadata().
emitTopLevelLibraryNode()
MDTuple * emitTopLevelLibraryNode (Module & M, MDNode * RMD, uint64_t ShaderFlags) static
Definition at line 333 of file DXILTranslateMetadata.cpp.
References llvm::SmallVectorImpl< T >::append(), constructEntryMetadata(), llvm::MDNode::get(), and getTagValueAsMetadata().
Referenced by translateGlobalMetadata().
emitValidatorVersionMD()
void emitValidatorVersionMD (Module & M, const ModuleMetadataInfo & MMDI) static
Definition at line 291 of file DXILTranslateMetadata.cpp.
References llvm::NamedMDNode::addOperand(), llvm::NamedMDNode::clearOperands(), llvm::VersionTuple::empty(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::IRBuilderBase::getInt32(), llvm::VersionTuple::getMajor(), llvm::VersionTuple::getMinor(), and llvm::dxil::ModuleMetadataInfo::ValidatorVersion.
Referenced by translateGlobalMetadata().
getCompatibleInstructionMDs()
InstructionMDList getCompatibleInstructionMDs (llvm::Module & M) static
Definition at line 462 of file DXILTranslateMetadata.cpp.
Referenced by translateInstructionMetadata().
getEntryPropAsMetadata()
MDTuple * getEntryPropAsMetadata (Module & M, const EntryProperties & EP, uint64_t EntryShaderFlags, const ModuleMetadataInfo & MMDI) static
Definition at line 187 of file DXILTranslateMetadata.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::Triple::Compute, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::dxil::EntryProperties::Entry, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::Function::getContext(), llvm::Type::getInt32Ty(), getShaderStage(), getTagValueAsMetadata(), llvm::Triple::Library, llvm::dxil::EntryProperties::NumThreadsX, llvm::dxil::EntryProperties::NumThreadsY, llvm::dxil::EntryProperties::NumThreadsZ, llvm::SmallVectorTemplateBase< T, bool >::push_back(), reportError(), llvm::dxil::ModuleMetadataInfo::ShaderModelVersion, llvm::dxil::ModuleMetadataInfo::ShaderProfile, llvm::dxil::EntryProperties::ShaderStage, llvm::dxil::EntryProperties::WaveSizeMax, llvm::dxil::EntryProperties::WaveSizeMin, and llvm::dxil::EntryProperties::WaveSizePref.
Referenced by emitEntryMD().
getShaderStage()
uint32_t getShaderStage (Triple::EnvironmentType Env) static
Definition at line 152 of file DXILTranslateMetadata.cpp.
References llvm::Triple::Pixel.
Referenced by getEntryPropAsMetadata().
getShortShaderStage()
StringRef getShortShaderStage (Triple::EnvironmentType Env) static
Definition at line 124 of file DXILTranslateMetadata.cpp.
References llvm::Triple::Amplification, llvm::Triple::Compute, llvm::Triple::Domain, llvm::Triple::Geometry, llvm::Triple::Hull, llvm::Triple::Library, llvm_unreachable, llvm::Triple::Mesh, llvm::Triple::Pixel, llvm::Triple::RootSignature, and llvm::Triple::Vertex.
Referenced by emitShaderModelVersionMD(), and translateGlobalMetadata().
getTagValueAsMetadata()
SmallVector< Metadata * > getTagValueAsMetadata (EntryPropsTag Tag, uint64_t Value, LLVMContext & Ctx) static
Definition at line 157 of file DXILTranslateMetadata.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::ConstantAsMetadata::get(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), and llvm_unreachable.
Referenced by emitTopLevelLibraryNode(), and getEntryPropAsMetadata().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILTranslateMetadataLegacy , "dxil-translate-metadata" , "DXIL Translate Metadata" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
isLoopMDCompatible()
bool isLoopMDCompatible (Module & M, Metadata * MD) static
Definition at line 374 of file DXILTranslateMetadata.cpp.
References llvm::Count, llvm::dyn_cast(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::is_contained(), and llvm::isa().
Referenced by translateLoopMetadata().
translateBranchMetadata()
void translateBranchMetadata (Module & M, Instruction * BBTerminatorInst) static
Definition at line 348 of file DXILTranslateMetadata.cpp.
References assert(), llvm::MDBuilder::createConstant(), llvm::MDBuilder::createString(), llvm::mdconst::extract(), llvm::MDNode::get(), llvm::Instruction::getMetadata(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and llvm::Instruction::setMetadata().
Referenced by translateInstructionMetadata().
translateGlobalMetadata()
void translateGlobalMetadata (Module & M, DXILResourceMap & DRM, DXILResourceTypeMap & DRTM, const ModuleShaderFlags & ShaderFlags, const ModuleMetadataInfo & MMDI) static
Definition at line 527 of file DXILTranslateMetadata.cpp.
References llvm::NamedMDNode::addOperand(), cleanModuleFlags(), CompatibleNamedModuleMDs, emitDXILVersionTupleMD(), emitEntryMD(), emitResourceMetadata(), emitShaderModelVersionMD(), emitTopLevelLibraryNode(), emitValidatorVersionMD(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::dxil::EntryProperties::Entry, llvm::dxil::ModuleMetadataInfo::EntryPropertyVec, llvm::Triple::getEnvironmentTypeName(), llvm::Value::getName(), llvm::NamedMDNode::getOperand(), getShortShaderStage(), llvm::is_contained(), llvm::Triple::Library, llvm::SmallVectorTemplateBase< T, bool >::push_back(), reportError(), llvm::dxil::ModuleMetadataInfo::ShaderProfile, and llvm::dxil::EntryProperties::ShaderStage.
Referenced by llvm::DXILTranslateMetadata::run(), and llvm::DXILTranslateMetadataLegacy::runOnModule().
translateInstructionMetadata()
void translateInstructionMetadata (Module & M) static
Definition at line 470 of file DXILTranslateMetadata.cpp.
References F, getCompatibleInstructionMDs(), I, llvm::isa(), llvm::make_early_inc_range(), translateBranchMetadata(), and translateLoopMetadata().
Referenced by llvm::DXILTranslateMetadata::run(), and llvm::DXILTranslateMetadataLegacy::runOnModule().
translateLoopMetadata()
void translateLoopMetadata (Module & M, Instruction * I, MDNode * BaseMD) static
Definition at line 415 of file DXILTranslateMetadata.cpp.
References llvm::ArrayRef< T >::drop_front(), llvm::dyn_cast(), llvm::MDNode::get(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDNode::getTemporary(), I, isLoopMDCompatible(), llvm::MDNode::operands(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by translateInstructionMetadata().
Variable Documentation
CompatibleNamedModuleMDs
GlobalMDList CompatibleNamedModuleMDs static
Initial value:
                                             = {
    "llvm.ident",     "llvm.module.flags", "dx.resources",   "dx.valver",
    "dx.shaderModel", "dx.version",        "dx.entryPoints",
}
Definition at line 522 of file DXILTranslateMetadata.cpp.
Referenced by translateGlobalMetadata().
false
dxil translate DXIL Translate false
Definition at line 647 of file DXILTranslateMetadata.cpp.
Metadata
dxil translate DXIL Translate Metadata
Definition at line 647 of file DXILTranslateMetadata.cpp.
Referenced by llvm::TimeTraceProfiler::begin().
metadata
dxil translate metadata
Definition at line 646 of file DXILTranslateMetadata.cpp.