LLVM: lib/Target/DirectX/DXILPostOptimizationValidation.cpp File Reference
DXILPostOptimizationValidation.cpp File Reference
#include "DXILPostOptimizationValidation.h"
#include "DXILRootSignature.h"
#include "DXILShaderFlags.h"
#include "DirectX.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Analysis/DXILMetadataAnalysis.h"
#include "llvm/Analysis/DXILResource.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/DXILABI.h"
Macros
#define DEBUG_TYPE "dxil-post-optimization-validation"
Functions
static ResourceClass toResourceClass (dxbc::RootParameterType Type)
static void reportInvalidDirection (Module &M, DXILResourceMap &DRM)
static void reportOverlappingError (Module &M, ResourceInfo R1, ResourceInfo R2)
static void reportOverlappingBinding (Module &M, DXILResourceMap &DRM)
static void reportInvalidHandleTyError (Module &M, ResourceClass RC, ResourceInfo::ResourceBinding Binding)
static void reportOverlappingRegisters (Module &M, const llvm::hlsl::Binding &R1, const llvm::hlsl::Binding &R2)
static void reportRegNotBound (Module &M, ResourceClass Class, const llvm::dxil::ResourceInfo::ResourceBinding &Unbound)
static dxbc::ShaderVisibility tripleToVisibility (llvm::Triple::EnvironmentType ET)
static void reportIfDeniedShaderStageAccess (Module &M, const dxbc::RootFlags &Flags, const dxbc::RootFlags &Mask)
static std::optional< dxbc::RootFlags > getEnvironmentDenyFlagMask (Triple::EnvironmentType ShaderProfile)
static void validateRootSignature (Module &M, const mcdxbc::RootSignatureDesc &RSD, dxil::ModuleMetadataInfo &MMI, DXILResourceMap &DRM, DXILResourceTypeMap &DRTM)
static mcdxbc::RootSignatureDesc * getRootSignature (RootSignatureBindingInfo &RSBI, dxil::ModuleMetadataInfo &MMI)
static void reportErrors (Module &M, DXILResourceMap &DRM, DXILResourceBindingInfo &DRBI, RootSignatureBindingInfo &RSBI, dxil::ModuleMetadataInfo &MMI, DXILResourceTypeMap &DRTM)
INITIALIZE_PASS_BEGIN (DXILPostOptimizationValidationLegacy, DEBUG_TYPE, "DXIL Post Optimization Validation", false, false) INITIALIZE_PASS_END(DXILPostOptimizationValidationLegacy
Variables
DEBUG_TYPE
DXIL Post Optimization Validation
DXIL Post Optimization false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-post-optimization-validation"
Definition at line 23 of file DXILPostOptimizationValidation.cpp.
Function Documentation
getEnvironmentDenyFlagMask()
std::optional< dxbc::RootFlags > getEnvironmentDenyFlagMask (Triple::EnvironmentType ShaderProfile) static
Definition at line 177 of file DXILPostOptimizationValidation.cpp.
References llvm::Triple::Amplification, llvm::Triple::Domain, llvm::Triple::Geometry, llvm::Triple::Hull, llvm::Triple::Mesh, llvm::Triple::Pixel, and llvm::Triple::Vertex.
Referenced by validateRootSignature().
getRootSignature()
mcdxbc::RootSignatureDesc * getRootSignature (RootSignatureBindingInfo & RSBI, dxil::ModuleMetadataInfo & MMI) static
Definition at line 306 of file DXILPostOptimizationValidation.cpp.
References llvm::dxil::ModuleMetadataInfo::EntryPropertyVec, and llvm::dxil::RootSignatureBindingInfo::getDescForFunction().
Referenced by reportErrors().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILPostOptimizationValidationLegacy , DEBUG_TYPE , "DXIL Post Optimization Validation" , false , false)
References DEBUG_TYPE, and INITIALIZE_PASS_DEPENDENCY.
reportErrors()
void reportErrors (Module & M, DXILResourceMap & DRM, DXILResourceBindingInfo & DRBI, RootSignatureBindingInfo & RSBI, dxil::ModuleMetadataInfo & MMI, DXILResourceTypeMap & DRTM) static
Definition at line 313 of file DXILPostOptimizationValidation.cpp.
References assert(), getRootSignature(), llvm::DXILResourceBindingInfo::hasImplicitBinding(), llvm::DXILResourceMap::hasInvalidCounterDirection(), llvm::DXILResourceBindingInfo::hasOverlappingBinding(), reportInvalidDirection(), reportOverlappingBinding(), and validateRootSignature().
Referenced by llvm::DXILPostOptimizationValidation::run().
reportIfDeniedShaderStageAccess()
void reportIfDeniedShaderStageAccess (Module & M, const dxbc::RootFlags & Flags, const dxbc::RootFlags & Mask) static
Definition at line 163 of file DXILPostOptimizationValidation.cpp.
Referenced by validateRootSignature().
reportInvalidDirection()
void reportInvalidDirection (Module & M, DXILResourceMap & DRM) static
Definition at line 45 of file DXILPostOptimizationValidation.cpp.
References llvm::DXILResourceMap::calls(), llvm::dyn_cast(), llvm::DXILResourceMap::find(), llvm::Instruction::getDebugLoc(), llvm::Instruction::getFunction(), llvm::CallBase::getIntrinsicID(), llvm::dxil::Invalid, llvm::dxil::UAV, llvm::DXILResourceMap::uavs(), and llvm::Value::users().
Referenced by reportErrors().
reportInvalidHandleTyError()
void reportInvalidHandleTyError (Module & M, ResourceClass RC, ResourceInfo::ResourceBinding Binding) static
Definition at line 106 of file DXILPostOptimizationValidation.cpp.
References Binding, and llvm::dxil::getResourceClassName().
Referenced by validateRootSignature().
reportOverlappingBinding()
void reportOverlappingBinding (Module & M, DXILResourceMap & DRM) static
Definition at line 82 of file DXILPostOptimizationValidation.cpp.
References assert(), llvm::DXILResourceMap::cbuffers(), llvm::dxil::ResourceInfo::getBinding(), I, llvm::dxil::ResourceInfo::ResourceBinding::overlapsWith(), reportOverlappingError(), llvm::DXILResourceMap::samplers(), llvm::DXILResourceMap::srvs(), and llvm::DXILResourceMap::uavs().
Referenced by reportErrors().
reportOverlappingError()
void reportOverlappingError (Module & M, ResourceInfo R1, ResourceInfo R2) static
Definition at line 71 of file DXILPostOptimizationValidation.cpp.
References llvm::dxil::ResourceInfo::getBinding(), llvm::dxil::ResourceInfo::getName(), llvm::dxil::ResourceInfo::ResourceBinding::LowerBound, and R2.
Referenced by reportOverlappingBinding().
reportOverlappingRegisters()
void reportOverlappingRegisters (Module & M, const llvm::hlsl::Binding & R1, const llvm::hlsl::Binding & R2) static
Definition at line 117 of file DXILPostOptimizationValidation.cpp.
References llvm::dxil::getResourceClassName(), llvm::hlsl::Binding::LowerBound, R2, llvm::hlsl::Binding::RC, llvm::hlsl::Binding::Space, and llvm::hlsl::Binding::UpperBound.
Referenced by validateRootSignature().
reportRegNotBound()
void reportRegNotBound (Module & M, ResourceClass Class, const llvm::dxil::ResourceInfo::ResourceBinding & Unbound) static
Definition at line 131 of file DXILPostOptimizationValidation.cpp.
References llvm::dxil::getResourceClassName(), llvm::dxil::ResourceInfo::ResourceBinding::LowerBound, and llvm::dxil::ResourceInfo::ResourceBinding::Space.
Referenced by validateRootSignature().
toResourceClass()
ResourceClass toResourceClass (dxbc::RootParameterType Type) static
Definition at line 28 of file DXILPostOptimizationValidation.cpp.
References llvm::dxil::CBuffer, llvm_unreachable, llvm::dxil::SRV, and llvm::dxil::UAV.
Referenced by validateRootSignature().
tripleToVisibility()
dxbc::ShaderVisibility tripleToVisibility (llvm::Triple::EnvironmentType ET) static
Definition at line 142 of file DXILPostOptimizationValidation.cpp.
References llvm::Triple::Compute, llvm::Triple::Domain, llvm::Triple::Geometry, llvm::Triple::Hull, llvm_unreachable, llvm::Triple::Mesh, llvm::Triple::Pixel, and llvm::Triple::Vertex.
Referenced by validateRootSignature().
validateRootSignature()
void validateRootSignature (Module & M, const mcdxbc::RootSignatureDesc & RSD, dxil::ModuleMetadataInfo & MMI, DXILResourceMap & DRM, DXILResourceTypeMap & DRTM) static
Definition at line 198 of file DXILPostOptimizationValidation.cpp.
References Binding, llvm::dxil::CBuffer, llvm::hlsl::BoundRegs::findBoundReg(), llvm::mcdxbc::RootSignatureDesc::Flags, llvm::mcdxbc::RootParametersContainer::getConstant(), llvm::mcdxbc::RootParametersContainer::getDescriptorTable(), getEnvironmentDenyFlagMask(), llvm::dxil::ResourceTypeInfo::getResourceClass(), llvm::dxil::ResourceTypeInfo::getResourceKind(), llvm::mcdxbc::RootParametersContainer::getRootDescriptor(), llvm::mcdxbc::RootParameterInfo::Location, llvm::mcdxbc::RootSignatureDesc::ParametersContainer, Range, llvm::mcdxbc::DescriptorTable::Ranges, llvm::dxil::RawBuffer, Reg, llvm::mcdxbc::StaticSampler::RegisterSpace, reportIfDeniedShaderStageAccess(), reportInvalidHandleTyError(), reportOverlappingRegisters(), reportRegNotBound(), llvm::dxil::Sampler, llvm::dxil::ModuleMetadataInfo::ShaderProfile, llvm::mcdxbc::StaticSampler::ShaderRegister, llvm::dxil::SRV, llvm::mcdxbc::RootSignatureDesc::StaticSamplers, llvm::dxil::StructuredBuffer, toResourceClass(), tripleToVisibility(), llvm::mcdxbc::RootParameterInfo::Type, llvm::dxil::UAV, and llvm::mcdxbc::RootParameterInfo::Visibility.
Referenced by reportErrors().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 391 of file DXILPostOptimizationValidation.cpp.
false
DXIL Post Optimization false
Definition at line 392 of file DXILPostOptimizationValidation.cpp.
Validation
DXIL Post Optimization Validation
Definition at line 392 of file DXILPostOptimizationValidation.cpp.