LLVM: lib/Target/DirectX/DXILResourceAccess.cpp File Reference
DXILResourceAccess.cpp File Reference
#include "DXILResourceAccess.h"
#include "DirectX.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Analysis/DXILResource.h"
#include "llvm/Frontend/HLSL/HLSLResource.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/User.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
Macros
#define DEBUG_TYPE "dxil-resource-access"
Functions
static Value * traverseGEPOffsets (const DataLayout &DL, IRBuilder<> &Builder, Value *Ptr, uint64_t AccessSize)
static void createTypedBufferStore (IntrinsicInst *II, StoreInst *SI, dxil::ResourceTypeInfo &RTI)
static void createRawStore (IntrinsicInst *II, StoreInst *SI, dxil::ResourceTypeInfo &RTI)
static void createStoreIntrinsic (IntrinsicInst *II, StoreInst *SI, dxil::ResourceTypeInfo &RTI)
static void createTypedBufferLoad (IntrinsicInst *II, LoadInst *LI, dxil::ResourceTypeInfo &RTI)
static void createRawLoad (IntrinsicInst *II, LoadInst *LI, dxil::ResourceTypeInfo &RTI)
static void createCBufferLoad (IntrinsicInst *II, LoadInst *LI, dxil::ResourceTypeInfo &RTI)
static void createLoadIntrinsic (IntrinsicInst *II, LoadInst *LI, dxil::ResourceTypeInfo &RTI)
static SmallVector< Instruction * > collectBlockUseDef (Instruction *Start)
static void phiNodeRemapHelper (PHINode *Phi, BasicBlock *BB, IRBuilder<> &Builder, SmallVector< Instruction * > &UsesInBlock)
static void phiNodeReplacement (IntrinsicInst *II, SmallVectorImpl< Instruction * > &PrevBBDeadInsts, SetVector< BasicBlock * > &DeadBB)
static void replaceAccess (IntrinsicInst *II, dxil::ResourceTypeInfo &RTI)
static bool transformResourcePointers (Function &F, DXILResourceTypeMap &DRTM)
INITIALIZE_PASS_BEGIN (DXILResourceAccessLegacy, DEBUG_TYPE, "DXIL Resource Access", false, false) INITIALIZE_PASS_END(DXILResourceAccessLegacy
Variables
DEBUG_TYPE
DXIL Resource Access
DXIL Resource false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-resource-access"
Definition at line 27 of file DXILResourceAccess.cpp.
Function Documentation
collectBlockUseDef()
SmallVector< Instruction * > collectBlockUseDef (Instruction * Start) static
Definition at line 422 of file DXILResourceAccess.cpp.
References A(), B(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sort().
Referenced by phiNodeReplacement().
createCBufferLoad()
void createCBufferLoad (IntrinsicInst * II, LoadInst * LI, dxil::ResourceTypeInfo & RTI) static
Definition at line 284 of file DXILResourceAccess.cpp.
References assert(), llvm::cast(), llvm::hlsl::CBufferRowSizeInBytes, DL, llvm::dyn_cast(), E(), llvm::formatv(), llvm::PoisonValue::get(), llvm::Instruction::getDataLayout(), llvm::Value::getName(), llvm::LoadInst::getPointerOperand(), llvm::Value::getType(), llvm::APInt::getZExtValue(), llvm::ConstantInt::getZExtValue(), I, II, llvm::isa(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::SmallVectorTemplateCommon< T, typename >::size(), traverseGEPOffsets(), llvm::APInt::udiv(), and llvm::APInt::udivrem().
Referenced by createLoadIntrinsic().
createLoadIntrinsic()
void createLoadIntrinsic (IntrinsicInst * II, LoadInst * LI, dxil::ResourceTypeInfo & RTI) static
Definition at line 389 of file DXILResourceAccess.cpp.
References llvm::dxil::CBuffer, createCBufferLoad(), createRawLoad(), createTypedBufferLoad(), llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::ResourceTypeInfo::getResourceKind(), II, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::reportFatalUsageError(), llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by llvm::ARMTargetLowering::lowerInterleavedLoad(), and replaceAccess().
createRawLoad()
void createRawLoad (IntrinsicInst * II, LoadInst * LI, dxil::ResourceTypeInfo & RTI) static
Definition at line 215 of file DXILResourceAccess.cpp.
References assert(), DL, llvm::dyn_cast(), llvm::PoisonValue::get(), llvm::StructType::get(), llvm::Instruction::getDataLayout(), llvm::Type::getInt1Ty(), llvm::LoadInst::getPointerOperand(), llvm::Value::getType(), II, llvm::Type::isAggregateType(), llvm::dxil::ResourceTypeInfo::isStruct(), llvm::Offset, llvm::Value::replaceAllUsesWith(), and traverseGEPOffsets().
Referenced by createLoadIntrinsic().
createRawStore()
void createRawStore (IntrinsicInst * II, StoreInst * SI, dxil::ResourceTypeInfo & RTI) static
Definition at line 123 of file DXILResourceAccess.cpp.
References assert(), DL, llvm::dyn_cast(), llvm::PoisonValue::get(), II, llvm::dxil::ResourceTypeInfo::isStruct(), llvm::Offset, and traverseGEPOffsets().
Referenced by createStoreIntrinsic().
createStoreIntrinsic()
void createStoreIntrinsic (IntrinsicInst * II, StoreInst * SI, dxil::ResourceTypeInfo & RTI) static
Definition at line 153 of file DXILResourceAccess.cpp.
References llvm::dxil::CBuffer, createRawStore(), createTypedBufferStore(), llvm::dxil::FeedbackTexture2D, llvm::dxil::FeedbackTexture2DArray, llvm::dxil::ResourceTypeInfo::getResourceKind(), II, llvm::dxil::Invalid, llvm_unreachable, llvm::dxil::NumEntries, llvm::dxil::RawBuffer, llvm::reportFatalUsageError(), llvm::dxil::RTAccelerationStructure, llvm::dxil::Sampler, llvm::dxil::StructuredBuffer, llvm::dxil::TBuffer, llvm::dxil::Texture1D, llvm::dxil::Texture1DArray, llvm::dxil::Texture2D, llvm::dxil::Texture2DArray, llvm::dxil::Texture2DMS, llvm::dxil::Texture2DMSArray, llvm::dxil::Texture3D, llvm::dxil::TextureCube, llvm::dxil::TextureCubeArray, and llvm::dxil::TypedBuffer.
Referenced by llvm::ARMTargetLowering::lowerInterleavedStore(), and replaceAccess().
createTypedBufferLoad()
void createTypedBufferLoad (IntrinsicInst * II, LoadInst * LI, dxil::ResourceTypeInfo & RTI) static
Definition at line 185 of file DXILResourceAccess.cpp.
References DL, llvm::dyn_cast(), llvm::PoisonValue::get(), llvm::StructType::get(), llvm::Instruction::getDataLayout(), llvm::dxil::ResourceTypeInfo::getHandleTy(), llvm::Type::getInt1Ty(), llvm::LoadInst::getPointerOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::TargetExtType::getTypeParameter(), II, llvm::isa(), llvm::Offset, llvm::Value::replaceAllUsesWith(), and traverseGEPOffsets().
Referenced by createLoadIntrinsic().
createTypedBufferStore()
void createTypedBufferStore (IntrinsicInst * II, StoreInst * SI, dxil::ResourceTypeInfo & RTI) static
Definition at line 88 of file DXILResourceAccess.cpp.
References assert(), DL, llvm::StructType::get(), llvm::dxil::ResourceTypeInfo::getHandleTy(), llvm::Type::getInt1Ty(), llvm::Type::getScalarType(), llvm::TargetExtType::getTypeParameter(), II, llvm_unreachable, llvm::Offset, and traverseGEPOffsets().
Referenced by createStoreIntrinsic().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILResourceAccessLegacy , DEBUG_TYPE , "DXIL Resource Access" , false , false)
References DEBUG_TYPE, and INITIALIZE_PASS_DEPENDENCY.
phiNodeRemapHelper()
void phiNodeRemapHelper (PHINode * Phi, BasicBlock * BB, IRBuilder<> & Builder, SmallVector< Instruction * > & UsesInBlock) static
Definition at line 470 of file DXILResourceAccess.cpp.
References llvm::BasicBlock::back(), llvm::dyn_cast(), I, llvm::RemapInstruction(), llvm::RF_IgnoreMissingLocals, and llvm::RF_NoModuleLevelChanges.
Referenced by phiNodeReplacement().
phiNodeReplacement()
void phiNodeReplacement (IntrinsicInst * II, SmallVectorImpl< Instruction * > & PrevBBDeadInsts, SetVector< BasicBlock * > & DeadBB) static
Definition at line 492 of file DXILResourceAccess.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorImpl< T >::clear(), collectBlockUseDef(), llvm::dyn_cast(), E(), I, II, llvm::SetVector< T, Vector, Set, N >::insert(), llvm::isa(), phiNodeRemapHelper(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::reverse().
Referenced by transformResourcePointers().
replaceAccess()
void replaceAccess (IntrinsicInst * II, dxil::ResourceTypeInfo & RTI) static
Definition at line 528 of file DXILResourceAccess.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), createLoadIntrinsic(), createStoreIntrinsic(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), GEP, II, llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::reverse().
Referenced by transformResourcePointers().
transformResourcePointers()
bool transformResourcePointers (Function & F, DXILResourceTypeMap & DRTM) static
Definition at line 561 of file DXILResourceAccess.cpp.
References llvm::cast(), llvm::SetVector< T, Vector, Set, N >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::dyn_cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), F, I, II, llvm::make_early_inc_range(), phiNodeReplacement(), and replaceAccess().
Referenced by llvm::DXILResourceAccess::run().
traverseGEPOffsets()
Value * traverseGEPOffsets (const DataLayout & DL, IRBuilder<> & Builder, Value * Ptr, uint64_t AccessSize) static
Definition at line 31 of file DXILResourceAccess.cpp.
References assert(), llvm::cast(), DL, llvm::dyn_cast(), GEP, II, llvm_unreachable, and llvm::Offset.
Referenced by createCBufferLoad(), createRawLoad(), createRawStore(), createTypedBufferLoad(), and createTypedBufferStore().
Variable Documentation
Access
DXIL Resource Access
Definition at line 632 of file DXILResourceAccess.cpp.
Referenced by llvm::dwarf::AccessibilityString(), llvm::logicalview::LVElement::accessibilityString(), llvm::codeview::BaseClassRecord::BaseClassRecord(), llvm::codeview::DataMemberRecord::DataMemberRecord(), llvm::codeview::EnumeratorRecord::EnumeratorRecord(), llvm::AA::PointerInfo::State::forallInterferingAccesses(), foreachMemoryAccess(), llvm::logicalview::LVElement::getAccessibilityCode(), getFD(), llvm::MemoryDepChecker::getInstructionsForAccess(), isAllocSiteRemovable(), mayLoopAccessLocation(), mayLoopAccessLocation(), llvm::codeview::MemberAttributes::MemberAttributes(), llvm::codeview::MemberAttributes::MemberAttributes(), llvm::codeview::OneMethodRecord::OneMethodRecord(), llvm::sys::fs::openFile(), llvm::sys::fs::openNativeFile(), llvm::pdb::operator<<(), llvm::logicalview::LVLogicalVisitor::printMemberAttributes(), llvm::raw_fd_ostream::raw_fd_ostream(), llvm::raw_fd_ostream::raw_fd_ostream(), llvm::logicalview::LVElement::setAccessibilityCode(), llvm::logicalview::LVElement::setAccessibilityCode(), llvm::codeview::StaticDataMemberRecord::StaticDataMemberRecord(), and llvm::codeview::VirtualBaseClassRecord::VirtualBaseClassRecord().
DEBUG_TYPE
DEBUG_TYPE
Definition at line 631 of file DXILResourceAccess.cpp.
false
DXIL Resource false
Definition at line 632 of file DXILResourceAccess.cpp.