LLVM: lib/XRay/FDRRecordProducer.cpp File Reference
FDRRecordProducer.cpp File Reference
#include "llvm/XRay/FDRRecordProducer.h"
#include "llvm/Support/DataExtractor.h"
#include <cstdint>
Functions
static Expected< std::unique_ptr< Record > > metadataRecordType (const XRayFileHeader &Header, uint8_t T)
static constexpr bool isMetadataIntroducer (uint8_t FirstByte)
Function Documentation
isMetadataIntroducer()
constexpr bool isMetadataIntroducer (uint8_t FirstByte) static constexpr
Definition at line 76 of file FDRRecordProducer.cpp.
Referenced by llvm::xray::FileBasedRecordProducer::produce().
metadataRecordType()
Expected< std::unique_ptr< Record > > metadataRecordType (const XRayFileHeader & Header, uint8_t T) static
Definition at line 37 of file FDRRecordProducer.cpp.
References llvm::createStringError(), llvm_unreachable, and T.
Referenced by llvm::xray::FileBasedRecordProducer::produce().