LLVM: lib/XRay/FDRTraceWriter.cpp File Reference
FDRTraceWriter.cpp File Reference
#include "llvm/XRay/FDRTraceWriter.h"
#include <tuple>
Functions
template<uint8_t Kind, class... Values>
static Error writeMetadata (support::endian::Writer &OS, Values &&...Ds)
Function Documentation
writeMetadata()
template<uint8_t Kind, class... Values> Error writeMetadata (support::endian::Writer & OS, Values &&... Ds) static
Definition at line 43 of file FDRTraceWriter.cpp.
References assert(), llvm::Error::success(), T, and llvm::support::endian::Writer::write().
Referenced by llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), and llvm::xray::FDRTraceWriter::visit().