LLVM: lib/Transforms/IPO/FunctionAttrs.cpp File Reference
FunctionAttrs.cpp File Reference
This file implements interprocedural passes which walk the call-graph deducing and/or propagating function attributes.
#include "llvm/Transforms/IPO/FunctionAttrs.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/CGSCCPassManager.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRangeList.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/Local.h"
#include <cassert>
#include <iterator>
#include <map>
#include <optional>
#include <vector>
Classes
struct llvm::GraphTraits< ArgumentGraphNode * >
struct llvm::GraphTraits< ArgumentGraph * >
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "function-attrs"
Functions
STATISTIC (NumMemoryAttr, "Number of functions with improved memory attribute")
STATISTIC (NumCapturesNone, "Number of arguments marked captures(none)")
STATISTIC (NumCapturesPartial, "Number of arguments marked with captures " "attribute other than captures(none)")
STATISTIC (NumReturned, "Number of arguments marked returned")
STATISTIC (NumReadNoneArg, "Number of arguments marked readnone")
STATISTIC (NumReadOnlyArg, "Number of arguments marked readonly")
STATISTIC (NumWriteOnlyArg, "Number of arguments marked writeonly")
STATISTIC (NumNoAlias, "Number of function returns marked noalias")
STATISTIC (NumNonNullReturn, "Number of function returns marked nonnull")
STATISTIC (NumNoUndefReturn, "Number of function returns marked noundef")
STATISTIC (NumNoRecurse, "Number of functions marked as norecurse")
STATISTIC (NumNoUnwind, "Number of functions marked as nounwind")
STATISTIC (NumNoFree, "Number of functions marked as nofree")
STATISTIC (NumWillReturn, "Number of functions marked as willreturn")
STATISTIC (NumNoSync, "Number of functions marked as nosync")
STATISTIC (NumCold, "Number of functions marked as cold")
STATISTIC (NumThinLinkNoRecurse, "Number of functions marked as norecurse during thinlink")
STATISTIC (NumThinLinkNoUnwind, "Number of functions marked as nounwind during thinlink")
static void addCapturesStat (CaptureInfo CI)
static void addLocAccess (MemoryEffects &ME, const MemoryLocation &Loc, ModRefInfo MR, AAResults &AAR)
static void addArgLocs (MemoryEffects &ME, const CallBase *Call, ModRefInfo ArgMR, AAResults &AAR)
static std::pair< MemoryEffects, MemoryEffects > checkFunctionMemoryAccess (Function &F, bool ThisBody, AAResults &AAR, const SCCNodeSet &SCCNodes)
Returns the memory access attribute for function F using AAR for AA results, where SCCNodes is the current SCC.
template<typename AARGetterT>
static void addMemoryAttrs (const SCCNodeSet &SCCNodes, AARGetterT &&AARGetter, SmallPtrSet< Function *, 8 > &Changed)
Deduce readonly/readnone/writeonly attributes for the SCC.
static FunctionSummary * calculatePrevailingSummary (ValueInfo VI, DenseMap< ValueInfo, FunctionSummary * > &CachedPrevailingSummary, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing)
static Attribute::AttrKind determinePointerAccessAttrs (Argument *A, const SmallPtrSet< Argument *, 8 > &SCCNodes)
Returns Attribute::None, Attribute::ReadOnly or Attribute::ReadNone.
static void addArgumentReturnedAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
Deduce returned attributes for the SCC.
static bool addArgumentAttrsFromCallsites (Function &F)
If a callsite has arguments that are also arguments to the parent function, try to propagate attributes from the callsite's arguments to the parent's arguments.
static bool addAccessAttr (Argument *A, Attribute::AttrKind R)
static bool inferInitializes (Argument &A, Function &F)
static void addArgumentAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed, bool SkipInitializes)
Deduce nocapture attributes for the SCC.
static bool isFunctionMallocLike (Function *F, const SCCNodeSet &SCCNodes)
Tests whether a function is "malloc-like".
static void addNoAliasAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
Deduce noalias attributes for the SCC.
static bool isReturnNonNull (Function *F, const SCCNodeSet &SCCNodes, bool &Speculative)
Tests whether this function is known to not return null.
static void addNonNullAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
Deduce nonnull attributes for the SCC.
static void addNoUndefAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
Deduce noundef attributes for the SCC.
static bool InstrBreaksNonConvergent (Instruction &I, const SCCNodeSet &SCCNodes)
Helper for non-Convergent inference predicate InstrBreaksAttribute.
static bool InstrBreaksNonThrowing (Instruction &I, const SCCNodeSet &SCCNodes)
Helper for NoUnwind inference predicate InstrBreaksAttribute.
static bool InstrBreaksNoFree (Instruction &I, const SCCNodeSet &SCCNodes)
Helper for NoFree inference predicate InstrBreaksAttribute.
static bool isOrderedAtomic (Instruction *I)
static bool InstrBreaksNoSync (Instruction &I, const SCCNodeSet &SCCNodes)
static void inferConvergent (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
Attempt to remove convergent function attribute when possible.
static void inferAttrsFromFunctionBodies (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
Infer attributes from all functions in the SCC by scanning every instruction for compliance to the attribute assumptions.
static bool mayHaveRecursiveCallee (Function &F, bool AnyFunctionsAddressIsTaken=true)
static void addNoRecurseAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
static void addNoReturnAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
static bool allPathsGoThroughCold (Function &F)
static void addColdAttrs (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
static bool functionWillReturn (const Function &F)
static void addWillReturn (const SCCNodeSet &SCCNodes, SmallPtrSet< Function *, 8 > &Changed)
static SCCNodesResult createSCCNodeSet (ArrayRef< Function * > Functions)
template<typename AARGetterT>
static SmallPtrSet< Function *, 8 > deriveAttrsInPostOrder (ArrayRef< Function * > Functions, AARGetterT &&AARGetter, bool ArgAttrsOnly)
template<typename AARGetterT>
static bool runImpl (CallGraphSCC &SCC, AARGetterT AARGetter)
static bool addNoRecurseAttrsTopDown (Function &F)
static bool deduceFunctionAttributeInRPO (Module &M, LazyCallGraph &CG)
Variables
static cl::opt< bool > EnableNonnullArgPropagation ("enable-nonnull-arg-prop", cl::init(true), cl::Hidden, cl::desc("Try to propagate nonnull argument attributes from callsites to " "caller functions."))
static cl::opt< bool > DisableNoUnwindInference ("disable-nounwind-inference", cl::Hidden, cl::desc("Stop inferring nounwind attribute during function-attrs pass"))
static cl::opt< bool > DisableNoFreeInference ("disable-nofree-inference", cl::Hidden, cl::desc("Stop inferring nofree attribute during function-attrs pass"))
static cl::opt< bool > DisableThinLTOPropagation ("disable-thinlto-funcattrs", cl::init(true), cl::Hidden, cl::desc("Don't propagate function-attrs in thinLTO"))
Detailed Description
This file implements interprocedural passes which walk the call-graph deducing and/or propagating function attributes.
Definition in file FunctionAttrs.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "function-attrs"
Definition at line 70 of file FunctionAttrs.cpp.
Function Documentation
addAccessAttr()
bool addAccessAttr (Argument * A, Attribute::AttrKind R) static
Definition at line 1091 of file FunctionAttrs.cpp.
References A(), and assert().
Referenced by addArgumentAttrs().
addArgLocs()
void addArgLocs (MemoryEffects & ME, const CallBase * Call, ModRefInfo ArgMR, AAResults & AAR) static
Definition at line 147 of file FunctionAttrs.cpp.
References addLocAccess(), and llvm::MemoryLocation::getBeforeOrAfter().
Referenced by checkFunctionMemoryAccess().
addArgumentAttrs()
void addArgumentAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed, bool SkipInitializes) static
Deduce nocapture attributes for the SCC.
Definition at line 1239 of file FunctionAttrs.cpp.
References A(), addAccessAttr(), addArgumentAttrsFromCallsites(), addCapturesStat(), B(), llvm::capturesAll(), llvm::capturesAnyProvenance(), llvm::capturesNothing(), llvm::SmallPtrSetImpl< PtrType >::count(), determinePointerAccessAttrs(), F, llvm::Attribute::getWithCaptureInfo(), I, inferInitializes(), llvm::SmallPtrSetImpl< PtrType >::insert(), N, llvm::Attribute::None, llvm::None, llvm::CaptureInfo::none(), llvm::PointerMayBeCaptured(), llvm::scc_begin(), and Uses.
Referenced by deriveAttrsInPostOrder().
addArgumentAttrsFromCallsites()
bool addArgumentAttrsFromCallsites (Function & F) static
If a callsite has arguments that are also arguments to the parent function, try to propagate attributes from the callsite's arguments to the parent's arguments.
This may be important because inlining can cause information loss when attribute knowledge disappears with the inlined call.
Definition at line 1052 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), EnableNonnullArgPropagation, F, llvm::CallBase::getArgOperand(), llvm::CallBase::getCalledFunction(), I, and llvm::isGuaranteedToTransferExecutionToSuccessor().
Referenced by addArgumentAttrs().
addArgumentReturnedAttrs()
void addArgumentReturnedAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Deduce returned attributes for the SCC.
Definition at line 1003 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), F, and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by deriveAttrsInPostOrder().
addCapturesStat()
void addCapturesStat (CaptureInfo CI) static
Definition at line 112 of file FunctionAttrs.cpp.
References llvm::capturesNothing().
Referenced by addArgumentAttrs().
addColdAttrs()
void addColdAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Definition at line 2183 of file FunctionAttrs.cpp.
References allPathsGoThroughCold(), F, and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by deriveAttrsInPostOrder().
addLocAccess()
void addLocAccess (MemoryEffects & ME, const MemoryLocation & Loc, ModRefInfo MR, AAResults & AAR) static
Definition at line 125 of file FunctionAttrs.cpp.
References llvm::MemoryEffectsBase< IRMemLocation >::argMemOnly(), llvm::ErrnoMem, llvm::AAResults::getModRefInfoMask(), llvm::getUnderlyingObjectAggressive(), llvm::isa(), llvm::isIdentifiedObject(), llvm::isNoModRef(), and llvm::Other.
Referenced by addArgLocs(), and checkFunctionMemoryAccess().
addMemoryAttrs()
template<typename AARGetterT> void addMemoryAttrs (const SCCNodeSet & SCCNodes, AARGetterT && AARGetter, SmallPtrSet< Function *, 8 > & Changed) static
Deduce readonly/readnone/writeonly attributes for the SCC.
Definition at line 274 of file FunctionAttrs.cpp.
References A(), llvm::ArgMem, checkFunctionMemoryAccess(), F, llvm::MemoryEffectsBase< LocationEnum >::getModRef(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isModSet(), llvm::NoModRef, llvm::MemoryEffectsBase< IRMemLocation >::none(), and llvm::MemoryEffectsBase< IRMemLocation >::unknown().
Referenced by deriveAttrsInPostOrder().
addNoAliasAttrs()
void addNoAliasAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Deduce noalias attributes for the SCC.
Definition at line 1511 of file FunctionAttrs.cpp.
References F, llvm::SmallPtrSetImpl< PtrType >::insert(), and isFunctionMallocLike().
Referenced by deriveAttrsInPostOrder().
addNonNullAttrs()
void addNonNullAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Deduce nonnull attributes for the SCC.
Definition at line 1624 of file FunctionAttrs.cpp.
References llvm::dbgs(), F, llvm::SmallPtrSetImpl< PtrType >::insert(), isReturnNonNull(), and LLVM_DEBUG.
Referenced by deriveAttrsInPostOrder().
addNoRecurseAttrs()
void addNoRecurseAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Definition at line 2100 of file FunctionAttrs.cpp.
References F, llvm::SmallPtrSetImpl< PtrType >::insert(), and mayHaveRecursiveCallee().
Referenced by deriveAttrsInPostOrder().
addNoRecurseAttrsTopDown()
bool addNoRecurseAttrsTopDown (Function & F) static
Definition at line 2378 of file FunctionAttrs.cpp.
References assert(), llvm::dyn_cast(), F, llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), I, and llvm::CallBase::isCallee().
Referenced by deduceFunctionAttributeInRPO().
addNoReturnAttrs()
void addNoReturnAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Definition at line 2122 of file FunctionAttrs.cpp.
References llvm::canReturn(), F, and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by deriveAttrsInPostOrder().
addNoUndefAttrs()
void addNoUndefAttrs (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Deduce noundef attributes for the SCC.
Definition at line 1681 of file FunctionAttrs.cpp.
References llvm::all_of(), llvm::computeConstantRange(), llvm::ConstantRange::contains(), DL, llvm::dyn_cast(), F, llvm::Value::getPointerAlignment(), llvm::Attribute::getRange(), llvm::BasicBlock::getTerminator(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isGuaranteedNotToBeUndefOrPoison(), llvm::isKnownNonZero(), and llvm::Attribute::isValid().
Referenced by deriveAttrsInPostOrder().
addWillReturn()
void addWillReturn (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Definition at line 2230 of file FunctionAttrs.cpp.
References F, functionWillReturn(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by deriveAttrsInPostOrder().
allPathsGoThroughCold()
bool allPathsGoThroughCold (Function & F) static
Definition at line 2136 of file FunctionAttrs.cpp.
References llvm::any_of(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), F, llvm::CallBase::hasFnAttr(), I, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::successors(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by addColdAttrs().
calculatePrevailingSummary()
FunctionSummary * calculatePrevailingSummary (ValueInfo VI, DenseMap< ValueInfo, FunctionSummary * > & CachedPrevailingSummary, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing) static
At this point, prevailing symbols have been resolved. The following leads to returning a conservative result:
Multiple instances with local linkage. Normally local linkage would be unique per module as the GUID includes the module path. We could have a guid alias if there wasn't any distinguishing path when each file was compiled, but that should be rare so we'll punt on those.
These next 2 cases should not happen and will assert:
Multiple instances with external linkage. This should be caught in symbol resolution
Non-existent FunctionSummary for Aliasee. This presents a hole in our knowledge meaning we have to go conservative.
Otherwise, we calculate attributes for a function as:
If we have a local linkage, take its attributes. If there's somehow multiple, bail and go conservative.
If we have an external/WeakODR/LinkOnceODR linkage check that it is prevailing, take its attributes.
If we have a Weak/LinkOnce linkage the copies can have semantic differences. However, if the prevailing copy is known it will be used so take its attributes. If the prevailing copy is in a native file all IR copies will be dead and propagation will go conservative.
AvailableExternally summaries without a prevailing copy are known to occur in a couple of circumstances: a. An internal function gets imported due to its caller getting imported, it becomes AvailableExternally but no prevailing definition exists. Because it has to get imported along with its caller the attributes will be captured by propagating on its caller. b. C++11 [temp.explicit]p10 can generate AvailableExternally definitions of explicitly instanced template declarations for inlining which are ultimately dropped from the TU. Since this is localized to the TU the attributes will have already made it to the callers. These are edge cases and already captured by their callers so we ignore these for now. If they become relevant to optimize in the future this can be revisited.
Otherwise, go conservative.
Definition at line 315 of file FunctionAttrs.cpp.
References assert(), llvm::dbgs(), llvm::dyn_cast(), llvm::GlobalValue::isAvailableExternallyLinkage(), llvm::GlobalValue::isExternalLinkage(), llvm::GlobalValue::isLinkOnceAnyLinkage(), llvm::GlobalValue::isLinkOnceODRLinkage(), llvm::GlobalValue::isLocalLinkage(), llvm::GlobalValue::isWeakAnyLinkage(), llvm::GlobalValue::isWeakODRLinkage(), Linkage, LLVM_DEBUG, Local, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by llvm::thinLTOPropagateFunctionAttrs().
checkFunctionMemoryAccess()
std::pair< MemoryEffects, MemoryEffects > checkFunctionMemoryAccess (Function & F, bool ThisBody, AAResults & AAR, const SCCNodeSet & SCCNodes) static
Returns the memory access attribute for function F using AAR for AA results, where SCCNodes is the current SCC.
If ThisBody is true, this function may examine the function body and will return a result pertaining to this copy of the function. If it is false, the result will be based only on AA results for the function declaration; it will be assumed that some other (perhaps less optimized) version of the function may be selected at link time.
The return value is split into two parts: Memory effects that always apply, and additional memory effects that apply if any of the functions in the SCC can access argmem.
Definition at line 172 of file FunctionAttrs.cpp.
References addArgLocs(), addLocAccess(), llvm::ArgMem, llvm::MemoryEffectsBase< IRMemLocation >::argMemOnly(), llvm::MemoryEffectsBase< LocationEnum >::doesNotAccessMemory(), llvm::dyn_cast(), F, llvm::AAResults::getMemoryEffects(), llvm::MemoryEffectsBase< LocationEnum >::getModRef(), llvm::MemoryLocation::getOrNone(), llvm::MemoryEffectsBase< LocationEnum >::getWithoutLoc(), I, llvm::MemoryEffectsBase< IRMemLocation >::inaccessibleMemOnly(), instructions, llvm::isa(), llvm::Mod, llvm::ModRef, llvm::NoModRef, llvm::MemoryEffectsBase< IRMemLocation >::none(), llvm::Other, and llvm::Ref.
Referenced by addMemoryAttrs(), and llvm::computeFunctionBodyMemoryAccess().
createSCCNodeSet()
SCCNodesResult createSCCNodeSet (ArrayRef< Function * > Functions) static
Definition at line 2242 of file FunctionAttrs.cpp.
References F.
Referenced by deriveAttrsInPostOrder().
deduceFunctionAttributeInRPO()
bool deduceFunctionAttributeInRPO (Module & M, LazyCallGraph & CG) static
Definition at line 2410 of file FunctionAttrs.cpp.
References addNoRecurseAttrsTopDown(), llvm::LazyCallGraph::buildRefSCCs(), F, llvm::LazyCallGraph::postorder_ref_sccs(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::reverse().
Referenced by llvm::ReversePostOrderFunctionAttrsPass::run().
deriveAttrsInPostOrder()
template<typename AARGetterT> SmallPtrSet< Function *, 8 > deriveAttrsInPostOrder (ArrayRef< Function * > Functions, AARGetterT && AARGetter, bool ArgAttrsOnly) static
Definition at line 2258 of file FunctionAttrs.cpp.
References addArgumentAttrs(), addArgumentReturnedAttrs(), addColdAttrs(), addMemoryAttrs(), addNoAliasAttrs(), addNonNullAttrs(), addNoRecurseAttrs(), addNoReturnAttrs(), addNoUndefAttrs(), addWillReturn(), createSCCNodeSet(), F, llvm::inferAttributesFromOthers(), inferAttrsFromFunctionBodies(), inferConvergent(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by llvm::PostOrderFunctionAttrsPass::run(), and runImpl().
determinePointerAccessAttrs()
Attribute::AttrKind determinePointerAccessAttrs (Argument * A, const SmallPtrSet< Argument *, 8 > & SCCNodes) static
Returns Attribute::None, Attribute::ReadOnly or Attribute::ReadNone.
Definition at line 861 of file FunctionAttrs.cpp.
References A(), llvm::ArgMem, llvm::capturesAnyProvenance(), llvm::cast(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::CallBase::dataOperandHasImpliedAttr(), llvm::CallBase::doesNotAccessMemory(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), F, llvm::CallBase::getCalledFunction(), llvm::CallBase::getCaptureInfo(), llvm::CallBase::getDataOperandNo(), llvm::CallBase::getMemoryEffects(), llvm::MemoryEffectsBase< LocationEnum >::getModRef(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::CallBase::isArgOperand(), llvm::CallBase::isCallee(), llvm::isIntrinsicReturningPointerAliasingArgumentWithoutCapturing(), llvm::isModSet(), llvm::isNoModRef(), llvm::isRefSet(), llvm::Attribute::None, llvm::CallBase::onlyReadsMemory(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::uses().
Referenced by addArgumentAttrs().
functionWillReturn()
bool functionWillReturn (const Function & F) static
Definition at line 2200 of file FunctionAttrs.cpp.
References llvm::all_of(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), F, llvm::FindFunctionBackedges(), I, and instructions.
Referenced by addWillReturn().
inferAttrsFromFunctionBodies()
void inferAttrsFromFunctionBodies (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Infer attributes from all functions in the SCC by scanning every instruction for compliance to the attribute assumptions.
Returns true if any changes to function attributes were made.
Definition at line 2001 of file FunctionAttrs.cpp.
References llvm::dbgs(), DisableNoFreeInference, DisableNoUnwindInference, F, I, InstrBreaksNoFree(), InstrBreaksNonThrowing(), InstrBreaksNoSync(), and LLVM_DEBUG.
Referenced by deriveAttrsInPostOrder().
inferConvergent()
void inferConvergent (const SCCNodeSet & SCCNodes, SmallPtrSet< Function *, 8 > & Changed) static
Attempt to remove convergent function attribute when possible.
Returns true if any changes to function attributes were made.
Definition at line 1970 of file FunctionAttrs.cpp.
References llvm::dbgs(), F, I, InstrBreaksNonConvergent(), and LLVM_DEBUG.
Referenced by deriveAttrsInPostOrder().
inferInitializes()
bool inferInitializes (Argument & A, Function & F) static
Definition at line 1119 of file FunctionAttrs.cpp.
References _, A(), llvm::append_range(), assert(), llvm::ConstantRangeList::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Attribute::get(), Info, llvm::ConstantRangeList::intersectWith(), LHS, llvm::post_order(), llvm::ConstantRangeList::rangesRef(), llvm::reverse(), RHS, llvm::sort(), llvm::ConstantRangeList::subtract(), llvm::successors(), and llvm::ConstantRangeList::unionWith().
Referenced by addArgumentAttrs().
InstrBreaksNoFree()
bool InstrBreaksNoFree (Instruction & I, const SCCNodeSet & SCCNodes) static
Helper for NoFree inference predicate InstrBreaksAttribute.
Definition at line 1896 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), llvm::CallBase::getCalledFunction(), llvm::CallBase::hasFnAttr(), and I.
Referenced by inferAttrsFromFunctionBodies().
InstrBreaksNonConvergent()
bool InstrBreaksNonConvergent (Instruction & I, const SCCNodeSet & SCCNodes) static
Helper for non-Convergent inference predicate InstrBreaksAttribute.
Definition at line 1870 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), llvm::CallBase::getCalledFunction(), I, and llvm::CallBase::isConvergent().
Referenced by inferConvergent().
InstrBreaksNonThrowing()
bool InstrBreaksNonThrowing (Instruction & I, const SCCNodeSet & SCCNodes) static
Helper for NoUnwind inference predicate InstrBreaksAttribute.
Definition at line 1880 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), and I.
Referenced by inferAttrsFromFunctionBodies().
InstrBreaksNoSync()
bool InstrBreaksNoSync (Instruction & I, const SCCNodeSet & SCCNodes) static
Definition at line 1935 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), llvm::CallBase::getCalledFunction(), llvm::CallBase::hasFnAttr(), I, isOrderedAtomic(), and MI.
Referenced by inferAttrsFromFunctionBodies().
isFunctionMallocLike()
bool isFunctionMallocLike (Function * F, const SCCNodeSet & SCCNodes) static
Tests whether a function is "malloc-like".
A function is "malloc-like" if it returns either null or a pointer that doesn't alias any other pointer visible to the caller.
Definition at line 1448 of file FunctionAttrs.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), F, llvm::CallBase::getCalledFunction(), llvm::CallBase::hasRetAttr(), llvm::PHINode::incoming_values(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::SetVector< T, Vector, Set, N >::insert_range(), llvm::isa(), llvm::PointerMayBeCaptured(), and llvm::SetVector< T, Vector, Set, N >::size().
Referenced by addNoAliasAttrs().
isOrderedAtomic()
bool isOrderedAtomic (Instruction * I) static
Definition at line 1917 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), I, llvm::isa(), llvm_unreachable, and llvm::SyncScope::SingleThread.
Referenced by InstrBreaksNoSync().
isReturnNonNull()
bool isReturnNonNull (Function * F, const SCCNodeSet & SCCNodes, bool & Speculative) static
Tests whether this function is known to not return null.
Requires that the function returns a pointer.
Returns true if it believes the function will not return a null, and sets Speculative based on whether the returned conclusion is a speculative conclusion due to SCC calls.
Definition at line 1553 of file FunctionAttrs.cpp.
References assert(), llvm::cast(), DL, llvm::dyn_cast(), F, llvm::CallBase::getCalledFunction(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::isKnownNonZero(), llvm_unreachable, and llvm::SetVector< T, Vector, Set, N >::size().
Referenced by addNonNullAttrs().
mayHaveRecursiveCallee()
bool mayHaveRecursiveCallee (Function & F, bool AnyFunctionsAddressIsTaken = true) static
Definition at line 2077 of file FunctionAttrs.cpp.
References llvm::dyn_cast(), F, llvm::CallBase::getCalledFunction(), and I.
Referenced by addNoRecurseAttrs(), and llvm::NoRecurseLTOInferencePass::run().
runImpl()
template<typename AARGetterT> bool runImpl (CallGraphSCC & SCC, AARGetterT AARGetter) static
Definition at line 2369 of file FunctionAttrs.cpp.
References deriveAttrsInPostOrder(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), and I.
STATISTIC() [1/18]
STATISTIC (NumCapturesNone , "Number of arguments marked captures(none)")
STATISTIC() [2/18]
STATISTIC (NumCapturesPartial , "Number of arguments marked with captures " "attribute other than captures(none)")
STATISTIC() [3/18]
STATISTIC (NumCold , "Number of functions marked as cold")
STATISTIC() [4/18]
STATISTIC (NumMemoryAttr , "Number of functions with improved memory attribute")
STATISTIC() [5/18]
STATISTIC (NumNoAlias , "Number of function returns marked noalias")
STATISTIC() [6/18]
STATISTIC (NumNoFree , "Number of functions marked as nofree")
STATISTIC() [7/18]
STATISTIC (NumNonNullReturn , "Number of function returns marked nonnull")
STATISTIC() [8/18]
STATISTIC (NumNoRecurse , "Number of functions marked as norecurse")
STATISTIC() [9/18]
STATISTIC (NumNoSync , "Number of functions marked as nosync")
STATISTIC() [10/18]
STATISTIC (NumNoUndefReturn , "Number of function returns marked noundef")
STATISTIC() [11/18]
STATISTIC (NumNoUnwind , "Number of functions marked as nounwind")
STATISTIC() [12/18]
STATISTIC (NumReadNoneArg , "Number of arguments marked readnone")
STATISTIC() [13/18]
STATISTIC (NumReadOnlyArg , "Number of arguments marked readonly")
STATISTIC() [14/18]
STATISTIC (NumReturned , "Number of arguments marked returned")
STATISTIC() [15/18]
STATISTIC (NumThinLinkNoRecurse , "Number of functions marked as norecurse during thinlink")
STATISTIC() [16/18]
STATISTIC (NumThinLinkNoUnwind , "Number of functions marked as nounwind during thinlink")
STATISTIC() [17/18]
STATISTIC (NumWillReturn , "Number of functions marked as willreturn")
STATISTIC() [18/18]
STATISTIC (NumWriteOnlyArg , "Number of arguments marked writeonly")
Variable Documentation
DisableNoFreeInference
cl::opt< bool > DisableNoFreeInference("disable-nofree-inference", cl::Hidden, cl::desc("Stop inferring nofree attribute during function-attrs pass")) ("disable-nofree-inference" , cl::Hidden , cl::desc("Stop inferring nofree attribute during function-attrs pass")) static
Referenced by inferAttrsFromFunctionBodies().
DisableNoUnwindInference
cl::opt< bool > DisableNoUnwindInference("disable-nounwind-inference", cl::Hidden, cl::desc("Stop inferring nounwind attribute during function-attrs pass")) ("disable-nounwind-inference" , cl::Hidden , cl::desc("Stop inferring nounwind attribute during function-attrs pass")) static
Referenced by inferAttrsFromFunctionBodies().
DisableThinLTOPropagation
cl::opt< bool > DisableThinLTOPropagation("disable-thinlto-funcattrs", cl::init(true), cl::Hidden, cl::desc("Don't propagate function-attrs in thinLTO")) ("disable-thinlto-funcattrs" , cl::init(true) , cl::Hidden , cl::desc("Don't propagate function-attrs in thinLTO")) static
Referenced by llvm::thinLTOPropagateFunctionAttrs().
EnableNonnullArgPropagation
cl::opt< bool > EnableNonnullArgPropagation("enable-nonnull-arg-prop", cl::init(true), cl::Hidden, cl::desc("Try to propagate nonnull argument attributes from callsites to " "caller functions.")) ("enable-nonnull-arg-prop" , cl::init(true) , cl::Hidden , cl::desc("Try to propagate nonnull argument attributes from callsites to " "caller functions.")) static
Referenced by addArgumentAttrsFromCallsites().