LLVM: lib/Target/AMDGPU/GCNSchedStrategy.cpp File Reference
GCNSchedStrategy.cpp File Reference
This contains a MachineSchedStrategy implementation for maximizing wave occupancy on GCN hardware.
#include "GCNSchedStrategy.h"
#include "AMDGPUIGroupLP.h"
#include "GCNRegPressure.h"
#include "SIMachineFunctionInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/CalcSpillWeights.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/Support/ErrorHandling.h"
Classes
struct EarlierIssuingCycle
Macros
#define DEBUG_TYPE "machine-scheduler"
Generally, the reason for having multiple scheduling stages is to account for the kernel-wide effect of register usage on occupancy.
#define DUMP_MAX_REG_PRESSURE
#define REMAT_PREFIX "[PreRARemat] "
Allows to easily filter for this stage's debug output.
#define REMAT_DEBUG(X)
Functions
static bool canUsePressureDiffs (const SUnit &SU)
Checks whether SU can use the cached DAG pressure diffs to compute the current register pressure.
static void getRegisterPressures (bool AtTop, const RegPressureTracker &RPTracker, SUnit *SU, std::vector< unsigned > &Pressure, std::vector< unsigned > &MaxPressure, GCNDownwardRPTracker &DownwardTracker, GCNUpwardRPTracker &UpwardTracker, ScheduleDAGMI *DAG, const SIRegisterInfo *SRI)
static bool shouldCheckPending (SchedBoundary &Zone, const TargetSchedModel *SchedModel)
static SUnit * pickOnlyChoice (SchedBoundary &Zone, const TargetSchedModel *SchedModel)
static MachineInstr * getLastMIForRegion (MachineBasicBlock::iterator RegionBegin, MachineBasicBlock::iterator RegionEnd)
static void printScheduleModel (std::set< std::pair< MachineInstr *, unsigned >, EarlierIssuingCycle > &ReadyCycles)
static bool hasIGLPInstrs (ScheduleDAGInstrs *DAG)
Variables
static cl::opt< bool > DisableUnclusterHighRP ("amdgpu-disable-unclustered-high-rp-reschedule", cl::Hidden, cl::desc("Disable unclustered high register pressure " "reduction scheduling stage."), cl::init(false))
static cl::opt< bool > DisableClusteredLowOccupancy ("amdgpu-disable-clustered-low-occupancy-reschedule", cl::Hidden, cl::desc("Disable clustered low occupancy " "rescheduling for ILP scheduling stage."), cl::init(false))
static cl::opt< unsigned > ScheduleMetricBias ("amdgpu-schedule-metric-bias", cl::Hidden, cl::desc("Sets the bias which adds weight to occupancy vs latency. Set it to " "100 to chase the occupancy only."), cl::init(10))
static cl::opt< bool > RelaxedOcc ("amdgpu-schedule-relaxed-occupancy", cl::Hidden, cl::desc("Relax occupancy targets for kernels which are memory " "bound (amdgpu-membound-threshold), or " "Wave Limited (amdgpu-limit-wave-threshold)."), cl::init(false))
static cl::opt< bool > GCNTrackers ("amdgpu-use-amdgpu-trackers", cl::Hidden, cl::desc("Use the AMDGPU specific RPTrackers during scheduling"), cl::init(false))
static cl::opt< unsigned > PendingQueueLimit ("amdgpu-scheduler-pending-queue-limit", cl::Hidden, cl::desc("Max (Available+Pending) size to inspect pending queue (0 disables)"), cl::init(256))
static cl::opt< bool > PrintMaxRPRegUsageBeforeScheduler ("amdgpu-print-max-reg-pressure-regusage-before-scheduler", cl::Hidden, cl::desc("Print a list of live registers along with their def/uses at the " "point of maximum register pressure before scheduling."), cl::init(false))
static cl::opt< bool > PrintMaxRPRegUsageAfterScheduler ("amdgpu-print-max-reg-pressure-regusage-after-scheduler", cl::Hidden, cl::desc("Print a list of live registers along with their def/uses at the " "point of maximum register pressure after scheduling."), cl::init(false))
Detailed Description
This contains a MachineSchedStrategy implementation for maximizing wave occupancy on GCN hardware.
This pass will apply multiple scheduling stages to the same function. Regions are first recorded in GCNScheduleDAGMILive::schedule. The actual entry point for the scheduling of those regions is GCNScheduleDAGMILive::runSchedStages.
Definition in file GCNSchedStrategy.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Generally, the reason for having multiple scheduling stages is to account for the kernel-wide effect of register usage on occupancy.
Usually, only a few scheduling regions will have register pressure high enough to limit occupancy for the kernel, so constraints can be relaxed to improve ILP in other regions.
Definition at line 37 of file GCNSchedStrategy.cpp.
DUMP_MAX_REG_PRESSURE
#define DUMP_MAX_REG_PRESSURE
Definition at line 79 of file GCNSchedStrategy.cpp.
REMAT_DEBUG
#define REMAT_DEBUG (X)
Value:
LLVM_DEBUG(dbgs() << REMAT_PREFIX; X;)
Definition at line 1273 of file GCNSchedStrategy.cpp.
Referenced by llvm::PreRARematStage::initGCNSchedStage().
REMAT_PREFIX
#define REMAT_PREFIX "[PreRARemat] "
Allows to easily filter for this stage's debug output.
Definition at line 1272 of file GCNSchedStrategy.cpp.
Function Documentation
canUsePressureDiffs()
bool canUsePressureDiffs (const SUnit & SU) static
Checks whether SU can use the cached DAG pressure diffs to compute the current register pressure.
This works for the common case, but it has a few exceptions that have been observed through trial and error:
Explicit physical register operands
Subregister definitions
In both of those cases, PressureDiff doesn't represent the actual pressure, and querying LiveIntervals through the RegPressureTracker is needed to get an accurate value.
We should eventually only use PressureDiff for maximum performance, but this already allows 80% of SUs to take the fast path without changing scheduling at all. Further changes would either change scheduling, or require a lot more logic to recover an accurate pressure estimate from the PressureDiffs.
Definition at line 171 of file GCNSchedStrategy.cpp.
References llvm::SUnit::getInstr(), llvm::SUnit::isInstr(), and llvm::MachineInstr::operands().
Referenced by llvm::GCNSchedStrategy::initCandidate().
getLastMIForRegion()
MachineInstr * getLastMIForRegion (MachineBasicBlock::iterator RegionBegin, MachineBasicBlock::iterator RegionEnd) static
Definition at line 979 of file GCNSchedStrategy.cpp.
References assert(), and llvm::skipDebugInstructionsBackward().
Referenced by llvm::RegionPressureMap::buildLiveRegMap().
getRegisterPressures()
void getRegisterPressures (bool AtTop, const RegPressureTracker & RPTracker, SUnit * SU, std::vector< unsigned > & Pressure, std::vector< unsigned > & MaxPressure, GCNDownwardRPTracker & DownwardTracker, GCNUpwardRPTracker & UpwardTracker, ScheduleDAGMI * DAG, const SIRegisterInfo * SRI) static
Definition at line 187 of file GCNSchedStrategy.cpp.
References llvm::GCNDownwardRPTracker::bumpDownwardPressure(), GCNTrackers, llvm::GCNRegPressure::getAGPRNum(), llvm::GCNRegPressure::getArchVGPRNum(), llvm::RegPressureTracker::getDownwardPressure(), llvm::SUnit::getInstr(), llvm::GCNRPTracker::getPressure(), llvm::GCNRegPressure::getSGPRNum(), llvm::RegPressureTracker::getUpwardPressure(), MI, and llvm::GCNUpwardRPTracker::recede().
Referenced by llvm::GCNSchedStrategy::initCandidate().
hasIGLPInstrs()
bool hasIGLPInstrs (ScheduleDAGInstrs * DAG) static
Definition at line 2245 of file GCNSchedStrategy.cpp.
References llvm::any_of(), llvm::SIInstrInfo::isIGLPMutationOnly(), MI, and llvm::ScheduleDAG::TII.
Referenced by llvm::GCNPostScheduleDAGMILive::schedule().
pickOnlyChoice()
SUnit * pickOnlyChoice (SchedBoundary & Zone, const TargetSchedModel * SchedModel) static
Definition at line 352 of file GCNSchedStrategy.cpp.
References llvm::ReadyQueue::empty(), llvm::SchedBoundary::Pending, llvm::SchedBoundary::pickOnlyChoice(), and shouldCheckPending().
Referenced by llvm::GCNSchedStrategy::pickNode(), and llvm::GCNSchedStrategy::pickNodeBidirectional().
printScheduleModel()
void printScheduleModel (std::set< std::pair< MachineInstr *, unsigned >, EarlierIssuingCycle > & ReadyCycles) static
Definition at line 1578 of file GCNSchedStrategy.cpp.
References llvm::dbgs(), and I.
Referenced by llvm::GCNSchedStage::getScheduleMetrics(), and llvm::GCNSchedStage::getScheduleMetrics().
shouldCheckPending()
bool shouldCheckPending (SchedBoundary & Zone, const TargetSchedModel * SchedModel) static
Definition at line 344 of file GCNSchedStrategy.cpp.
References llvm::SchedBoundary::Available, llvm::TargetSchedModel::getMicroOpBufferSize(), llvm::TargetSchedModel::hasInstrSchedModel(), llvm::SchedBoundary::Pending, PendingQueueLimit, and llvm::ReadyQueue::size().
Referenced by llvm::GCNSchedStrategy::pickNodeFromQueue(), and pickOnlyChoice().
Variable Documentation
DisableClusteredLowOccupancy
cl::opt< bool > DisableClusteredLowOccupancy("amdgpu-disable-clustered-low-occupancy-reschedule", cl::Hidden, cl::desc("Disable clustered low occupancy " "rescheduling for ILP scheduling stage."), cl::init(false)) ("amdgpu-disable-clustered-low-occupancy-reschedule" , cl::Hidden , cl::desc("Disable clustered low occupancy " "rescheduling for ILP scheduling stage.") , cl::init(false)) static
Referenced by llvm::ClusteredLowOccStage::initGCNSchedStage().
DisableUnclusterHighRP
cl::opt< bool > DisableUnclusterHighRP("amdgpu-disable-unclustered-high-rp-reschedule", cl::Hidden, cl::desc("Disable unclustered high register pressure " "reduction scheduling stage."), cl::init(false)) ("amdgpu-disable-unclustered-high-rp-reschedule" , cl::Hidden , cl::desc("Disable unclustered high register pressure " "reduction scheduling stage.") , cl::init(false)) static
Referenced by llvm::UnclusteredHighRPStage::initGCNSchedStage().
GCNTrackers
cl::opt< bool > GCNTrackers("amdgpu-use-amdgpu-trackers", cl::Hidden, cl::desc("Use the AMDGPU specific RPTrackers during scheduling"), cl::init(false)) ("amdgpu-use-amdgpu-trackers" , cl::Hidden , cl::desc("Use the AMDGPU specific RPTrackers during scheduling") , cl::init(false)) static
Referenced by llvm::GCNMaxOccupancySchedStrategy::GCNMaxOccupancySchedStrategy(), getRegisterPressures(), llvm::GCNSchedStrategy::initCandidate(), llvm::PreRARematStage::initGCNSchedStage(), llvm::GCNSchedStrategy::pickNodeFromQueue(), and llvm::GCNSchedStrategy::schedNode().
PendingQueueLimit
cl::opt< unsigned > PendingQueueLimit("amdgpu-scheduler-pending-queue-limit", cl::Hidden, cl::desc("Max (Available+Pending) size to inspect pending queue (0 disables)"), cl::init(256)) ("amdgpu-scheduler-pending-queue-limit" , cl::Hidden , cl::desc("Max (Available+Pending) size to inspect pending queue (0 disables)") , cl::init(256)) static
Referenced by shouldCheckPending().
PrintMaxRPRegUsageAfterScheduler
cl::opt< bool > PrintMaxRPRegUsageAfterScheduler("amdgpu-print-max-reg-pressure-regusage-after-scheduler", cl::Hidden, cl::desc("Print a list of live registers along with their def/uses at the " "point of maximum register pressure after scheduling."), cl::init(false)) ("amdgpu-print-max-reg-pressure-regusage-after-scheduler" , cl::Hidden , cl::desc("Print a list of live registers along with their def/uses at the " "point of maximum register pressure after scheduling.") , cl::init(false)) static
PrintMaxRPRegUsageBeforeScheduler
cl::opt< bool > PrintMaxRPRegUsageBeforeScheduler("amdgpu-print-max-reg-pressure-regusage-before-scheduler", cl::Hidden, cl::desc("Print a list of live registers along with their def/uses at the " "point of maximum register pressure before scheduling."), cl::init(false)) ("amdgpu-print-max-reg-pressure-regusage-before-scheduler" , cl::Hidden , cl::desc("Print a list of live registers along with their def/uses at the " "point of maximum register pressure before scheduling.") , cl::init(false)) static
RelaxedOcc
cl::opt< bool > RelaxedOcc("amdgpu-schedule-relaxed-occupancy", cl::Hidden, cl::desc("Relax occupancy targets for kernels which are memory " "bound (amdgpu-membound-threshold), or " "Wave Limited (amdgpu-limit-wave-threshold)."), cl::init(false)) ("amdgpu-schedule-relaxed-occupancy" , cl::Hidden , cl::desc("Relax occupancy targets for kernels which are memory " "bound (amdgpu-membound-threshold), or " "Wave Limited (amdgpu-limit-wave-threshold).") , cl::init(false)) static
Referenced by llvm::GCNScheduleDAGMILive::GCNScheduleDAGMILive(), and llvm::GCNSchedStrategy::initialize().
ScheduleMetricBias
cl::opt< unsigned > ScheduleMetricBias("amdgpu-schedule-metric-bias", cl::Hidden, cl::desc("Sets the bias which adds weight to occupancy vs latency. Set it to " "100 to chase the occupancy only."), cl::init(10)) ("amdgpu-schedule-metric-bias" , cl::Hidden , cl::desc("Sets the bias which adds weight to occupancy vs latency. Set it to " "100 to chase the occupancy only.") , cl::init(10)) static
Referenced by llvm::UnclusteredHighRPStage::shouldRevertScheduling().