LLVM: lib/Support/GlobPattern.cpp File Reference
GlobPattern.cpp File Reference
#include "llvm/Support/GlobPattern.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
Functions
static Expected< BitVector > expand (StringRef S, StringRef Original)
static Expected< SmallVector< std::string, 1 > > parseBraceExpansions (StringRef S, std::optional< size_t > MaxSubPatterns)
static StringRef maxPlainSubstring (StringRef S)
Function Documentation
expand()
Expected< BitVector > expand (StringRef S, StringRef Original) static
Definition at line 21 of file GlobPattern.cpp.
References llvm::CallingConv::C, llvm::invalid_argument, llvm::make_error(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by llvm::MipsSEFrameLowering::determineCalleeSaves().
maxPlainSubstring()
StringRef maxPlainSubstring (StringRef S) static
Definition at line 135 of file GlobPattern.cpp.
References assert(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::find_first_of(), llvm::StringRef::front(), llvm::StringRef::size(), and llvm::StringRef::take_front().
Referenced by llvm::GlobPattern::longest_substr().
parseBraceExpansions()
Expected< SmallVector< std::string, 1 > > parseBraceExpansions (StringRef S, std::optional< size_t > MaxSubPatterns) static
Definition at line 59 of file GlobPattern.cpp.
References llvm::StringRef::contains(), E(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::StringRef::find(), I, llvm::invalid_argument, llvm::Length, llvm::make_error(), llvm::reverse(), llvm::StringRef::size(), llvm::StringRef::str(), llvm::StringRef::substr(), and std::swap().
Referenced by llvm::GlobPattern::create().