LLVM: Analysis
Analysis
LLVM-C: C interface to LLVM
Enumerations
enum LLVMVerifierFailureAction { LLVMAbortProcessAction , LLVMPrintMessageAction , LLVMReturnStatusAction }
Functions
LLVM_C_ABI LLVMBool LLVMVerifyModule (LLVMModuleRef M, LLVMVerifierFailureAction Action, char **OutMessage)
LLVM_C_ABI LLVMBool LLVMVerifyFunction (LLVMValueRef Fn, LLVMVerifierFailureAction Action)
LLVM_C_ABI void LLVMViewFunctionCFG (LLVMValueRef Fn)
LLVM_C_ABI void LLVMViewFunctionCFGOnly (LLVMValueRef Fn)
Detailed Description
Enumeration Type Documentation
LLVMVerifierFailureAction
enum LLVMVerifierFailureAction
Enumerator
LLVMAbortProcessAction
LLVMPrintMessageAction
LLVMReturnStatusAction
Definition at line 35 of file Analysis.h.
Function Documentation
LLVMVerifyFunction()
LLVM_C_ABI LLVMBool LLVMVerifyFunction (LLVMValueRef Fn, LLVMVerifierFailureAction Action)
Definition at line 102 of file Analysis.cpp.
References llvm::errs(), LLVMAbortProcessAction, LLVMReturnStatusAction, llvm::report_fatal_error(), llvm::unwrap(), and llvm::verifyFunction().
LLVMVerifyModule()
LLVM_C_ABI LLVMBool LLVMVerifyModule (LLVMModuleRef M, LLVMVerifierFailureAction Action, char ** OutMessage)
Definition at line 81 of file Analysis.cpp.
References llvm::errs(), LLVMAbortProcessAction, LLVMReturnStatusAction, llvm::report_fatal_error(), llvm::raw_string_ostream::str(), llvm::unwrap(), and llvm::verifyModule().
LLVMViewFunctionCFG()
LLVM_C_ABI void LLVMViewFunctionCFG (LLVMValueRef Fn)
Definition at line 113 of file Analysis.cpp.
References F, and llvm::unwrap().
LLVMViewFunctionCFGOnly()
LLVM_C_ABI void LLVMViewFunctionCFGOnly (LLVMValueRef Fn)
Definition at line 118 of file Analysis.cpp.
References F, and llvm::unwrap().