LLVM: Global Variables
Global Variables
LLVM-C: C interface to LLVM » Core » Values » Constants
This group contains functions that operate on global variable values.
Functions
LLVM_C_ABI LLVMValueRef LLVMAddGlobal (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMAddGlobalInAddressSpace (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name, unsigned AddressSpace)
LLVM_C_ABI LLVMValueRef LLVMGetNamedGlobal (LLVMModuleRef M, const char *Name)
LLVM_C_ABI LLVMValueRef LLVMGetNamedGlobalWithLength (LLVMModuleRef M, const char *Name, size_t Length)
LLVM_C_ABI LLVMValueRef LLVMGetFirstGlobal (LLVMModuleRef M)
LLVM_C_ABI LLVMValueRef LLVMGetLastGlobal (LLVMModuleRef M)
LLVM_C_ABI LLVMValueRef LLVMGetNextGlobal (LLVMValueRef GlobalVar)
LLVM_C_ABI LLVMValueRef LLVMGetPreviousGlobal (LLVMValueRef GlobalVar)
LLVM_C_ABI void LLVMDeleteGlobal (LLVMValueRef GlobalVar)
LLVM_C_ABI LLVMValueRef LLVMGetInitializer (LLVMValueRef GlobalVar)
LLVM_C_ABI void LLVMSetInitializer (LLVMValueRef GlobalVar, LLVMValueRef ConstantVal)
LLVM_C_ABI LLVMBool LLVMIsThreadLocal (LLVMValueRef GlobalVar)
LLVM_C_ABI void LLVMSetThreadLocal (LLVMValueRef GlobalVar, LLVMBool IsThreadLocal)
LLVM_C_ABI LLVMBool LLVMIsGlobalConstant (LLVMValueRef GlobalVar)
LLVM_C_ABI void LLVMSetGlobalConstant (LLVMValueRef GlobalVar, LLVMBool IsConstant)
LLVM_C_ABI LLVMThreadLocalMode LLVMGetThreadLocalMode (LLVMValueRef GlobalVar)
LLVM_C_ABI void LLVMSetThreadLocalMode (LLVMValueRef GlobalVar, LLVMThreadLocalMode Mode)
LLVM_C_ABI LLVMBool LLVMIsExternallyInitialized (LLVMValueRef GlobalVar)
LLVM_C_ABI void LLVMSetExternallyInitialized (LLVMValueRef GlobalVar, LLVMBool IsExtInit)
Detailed Description
This group contains functions that operate on global variable values.
See also
llvm::GlobalVariable
Function Documentation
LLVMAddGlobal()
LLVM_C_ABI LLVMValueRef LLVMAddGlobal (LLVMModuleRef M, LLVMTypeRef Ty, const char * Name)
Definition at line 2223 of file Core.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAddGlobalInAddressSpace()
LLVM_C_ABI LLVMValueRef LLVMAddGlobalInAddressSpace (LLVMModuleRef M, LLVMTypeRef Ty, const char * Name, unsigned AddressSpace)
Definition at line 2228 of file Core.cpp.
References llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::NotThreadLocal, llvm::unwrap(), and llvm::wrap().
LLVMDeleteGlobal()
LLVM_C_ABI void LLVMDeleteGlobal (LLVMValueRef GlobalVar)
Definition at line 2278 of file Core.cpp.
References llvm::unwrap().
LLVMGetFirstGlobal()
LLVM_C_ABI LLVMValueRef LLVMGetFirstGlobal (LLVMModuleRef M)
Definition at line 2246 of file Core.cpp.
References I, Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetInitializer()
LLVM_C_ABI LLVMValueRef LLVMGetInitializer (LLVMValueRef GlobalVar)
Definition at line 2282 of file Core.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::hasInitializer(), llvm::unwrap(), and llvm::wrap().
LLVMGetLastGlobal()
LLVM_C_ABI LLVMValueRef LLVMGetLastGlobal (LLVMModuleRef M)
Definition at line 2254 of file Core.cpp.
References I, Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobal()
LLVM_C_ABI LLVMValueRef LLVMGetNamedGlobal (LLVMModuleRef M, const char * Name)
Definition at line 2237 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobalWithLength()
LLVM_C_ABI LLVMValueRef LLVMGetNamedGlobalWithLength (LLVMModuleRef M, const char * Name, size_t Length)
Definition at line 2241 of file Core.cpp.
References llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMGetNextGlobal()
LLVM_C_ABI LLVMValueRef LLVMGetNextGlobal (LLVMValueRef GlobalVar)
Definition at line 2262 of file Core.cpp.
References llvm::GlobalValue::getParent(), llvm::Module::global_end(), I, llvm::unwrap(), and llvm::wrap().
LLVMGetPreviousGlobal()
LLVM_C_ABI LLVMValueRef LLVMGetPreviousGlobal (LLVMValueRef GlobalVar)
Definition at line 2270 of file Core.cpp.
References llvm::GlobalValue::getParent(), llvm::Module::global_begin(), I, llvm::unwrap(), and llvm::wrap().
LLVMGetThreadLocalMode()
LLVM_C_ABI LLVMThreadLocalMode LLVMGetThreadLocalMode (LLVMValueRef GlobalVar)
Definition at line 2310 of file Core.cpp.
References llvm::GlobalValue::GeneralDynamicTLSModel, llvm::GlobalValue::InitialExecTLSModel, llvm_unreachable, LLVMGeneralDynamicTLSModel, LLVMInitialExecTLSModel, LLVMLocalDynamicTLSModel, LLVMLocalExecTLSModel, LLVMNotThreadLocal, llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, llvm::GlobalValue::NotThreadLocal, and llvm::unwrap().
LLVMIsExternallyInitialized()
LLVM_C_ABI LLVMBool LLVMIsExternallyInitialized (LLVMValueRef GlobalVar)
Definition at line 2349 of file Core.cpp.
References llvm::unwrap().
LLVMIsGlobalConstant()
LLVM_C_ABI LLVMBool LLVMIsGlobalConstant (LLVMValueRef GlobalVar)
Definition at line 2302 of file Core.cpp.
References llvm::unwrap().
LLVMIsThreadLocal()
LLVM_C_ABI LLVMBool LLVMIsThreadLocal (LLVMValueRef GlobalVar)
Definition at line 2294 of file Core.cpp.
References llvm::unwrap().
LLVMSetExternallyInitialized()
LLVM_C_ABI void LLVMSetExternallyInitialized (LLVMValueRef GlobalVar, LLVMBool IsExtInit)
Definition at line 2353 of file Core.cpp.
References llvm::unwrap().
LLVMSetGlobalConstant()
LLVM_C_ABI void LLVMSetGlobalConstant (LLVMValueRef GlobalVar, LLVMBool IsConstant)
Definition at line 2306 of file Core.cpp.
References llvm::unwrap().
LLVMSetInitializer()
LLVM_C_ABI void LLVMSetInitializer (LLVMValueRef GlobalVar, LLVMValueRef ConstantVal)
Definition at line 2289 of file Core.cpp.
References llvm::unwrap().
LLVMSetThreadLocal()
LLVM_C_ABI void LLVMSetThreadLocal (LLVMValueRef GlobalVar, LLVMBool IsThreadLocal)
Definition at line 2298 of file Core.cpp.
References llvm::unwrap().
LLVMSetThreadLocalMode()
LLVM_C_ABI void LLVMSetThreadLocalMode (LLVMValueRef GlobalVar, LLVMThreadLocalMode Mode)
Definition at line 2327 of file Core.cpp.
References llvm::GlobalValue::GeneralDynamicTLSModel, llvm::GlobalValue::InitialExecTLSModel, LLVMGeneralDynamicTLSModel, LLVMInitialExecTLSModel, LLVMLocalDynamicTLSModel, LLVMLocalExecTLSModel, LLVMNotThreadLocal, llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, Mode, llvm::GlobalValue::NotThreadLocal, llvm::GlobalValue::setThreadLocalMode(), and llvm::unwrap().