LLVM: Threading
Threading
LLVM-C: C interface to LLVM
Handle the structures needed to make LLVM safe for multithreading.
Functions
LLVM_C_ABI LLVMBool LLVMStartMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
LLVM_C_ABI void LLVMStopMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
LLVM_C_ABI LLVMBool LLVMIsMultithreaded (void)
Check whether LLVM is executing in thread-safe mode or not.
Detailed Description
Handle the structures needed to make LLVM safe for multithreading.
Function Documentation
LLVMIsMultithreaded()
LLVM_C_ABI LLVMBool LLVMIsMultithreaded (void)
Check whether LLVM is executing in thread-safe mode or not.
See also
llvm::llvm_is_multithreaded
Definition at line 4685 of file Core.cpp.
References llvm::llvm_is_multithreaded().
Referenced by LLVMStartMultithreaded().
LLVMStartMultithreaded()
LLVM_C_ABI LLVMBool LLVMStartMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
This function always returns LLVMIsMultithreaded().
Definition at line 4678 of file Core.cpp.
References LLVMIsMultithreaded().
LLVMStopMultithreaded()
LLVM_C_ABI void LLVMStopMultithreaded (void)
Deprecated: Multi-threading can only be enabled/disabled with the compile time define LLVM_ENABLE_THREADS.
Definition at line 4682 of file Core.cpp.