LLVM: PHI Nodes
PHI Nodes
LLVM-C: C interface to LLVM » Core » Instructions
Functions in this group only apply to instructions that map to llvm::PHINode instances.
Functions
LLVM_C_ABI void LLVMAddIncoming (LLVMValueRef PhiNode, LLVMValueRef *IncomingValues, LLVMBasicBlockRef *IncomingBlocks, unsigned Count)
Add an incoming value to the end of a PHI list.
LLVM_C_ABI unsigned LLVMCountIncoming (LLVMValueRef PhiNode)
Obtain the number of incoming basic blocks to a PHI node.
LLVM_C_ABI LLVMValueRef LLVMGetIncomingValue (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMValueRef.
LLVM_C_ABI LLVMBasicBlockRef LLVMGetIncomingBlock (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMBasicBlockRef.
Detailed Description
Functions in this group only apply to instructions that map to llvm::PHINode instances.
Function Documentation
LLVMAddIncoming()
LLVM_C_ABI void LLVMAddIncoming (LLVMValueRef PhiNode, LLVMValueRef * IncomingValues, LLVMBasicBlockRef * IncomingBlocks, unsigned Count)
Add an incoming value to the end of a PHI list.
Definition at line 3309 of file Core.cpp.
References llvm::PHINode::addIncoming(), llvm::Count, I, and llvm::unwrap().
LLVMCountIncoming()
LLVM_C_ABI unsigned LLVMCountIncoming (LLVMValueRef PhiNode)
Obtain the number of incoming basic blocks to a PHI node.
Definition at line 3316 of file Core.cpp.
References llvm::unwrap().
LLVMGetIncomingBlock()
LLVM_C_ABI LLVMBasicBlockRef LLVMGetIncomingBlock (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMBasicBlockRef.
Definition at line 3324 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetIncomingValue()
LLVM_C_ABI LLVMValueRef LLVMGetIncomingValue (LLVMValueRef PhiNode, unsigned Index)
Obtain an incoming value to a PHI node as an LLVMValueRef.
Definition at line 3320 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().