LLVM: Constants
Constants
LLVM-C: C interface to LLVM » Core » Values
This section contains APIs for interacting with LLVMValueRef that correspond to llvm::Constant instances.
Topics
Scalar constants
Functions in this group model LLVMValueRef instances that correspond to constants referring to scalar types.
Composite Constants
Functions in this group operate on composite constants.
Constant Expressions
Functions in this group correspond to APIs on llvm::ConstantExpr.
Global Values
This group contains functions that operate on global values.
Global Variables
This group contains functions that operate on global variable values.
Global Aliases
This group contains function that operate on global alias values.
Function values
Functions in this group operate on LLVMValueRef instances that correspond to llvm::Function instances.
Functions
LLVM_C_ABI LLVMValueRef LLVMConstNull (LLVMTypeRef Ty)
Obtain a constant value referring to the null instance of a type.
LLVM_C_ABI LLVMValueRef LLVMConstAllOnes (LLVMTypeRef Ty)
Obtain a constant value referring to the instance of a type consisting of all ones.
LLVM_C_ABI LLVMValueRef LLVMGetUndef (LLVMTypeRef Ty)
Obtain a constant value referring to an undefined value of a type.
LLVM_C_ABI LLVMValueRef LLVMGetPoison (LLVMTypeRef Ty)
Obtain a constant value referring to a poison value of a type.
LLVM_C_ABI LLVMBool LLVMIsNull (LLVMValueRef Val)
Determine whether a value instance is null.
LLVM_C_ABI LLVMValueRef LLVMConstPointerNull (LLVMTypeRef Ty)
Obtain a constant that is a constant pointer pointing to NULL for a specified type.
Detailed Description
This section contains APIs for interacting with LLVMValueRef that correspond to llvm::Constant instances.
These functions will work for any LLVMValueRef in the llvm::Constant class hierarchy.
Function Documentation
LLVMConstAllOnes()
LLVM_C_ABI LLVMValueRef LLVMConstAllOnes (LLVMTypeRef Ty)
Obtain a constant value referring to the instance of a type consisting of all ones.
This is only valid for integer types.
See also
llvm::Constant::getAllOnesValue()
Definition at line 1249 of file Core.cpp.
References llvm::Constant::getAllOnesValue(), llvm::unwrap(), and llvm::wrap().
LLVMConstNull()
LLVM_C_ABI LLVMValueRef LLVMConstNull (LLVMTypeRef Ty)
Obtain a constant value referring to the null instance of a type.
See also
llvm::Constant::getNullValue()
Definition at line 1245 of file Core.cpp.
References llvm::Constant::getNullValue(), llvm::unwrap(), and llvm::wrap().
LLVMConstPointerNull()
LLVM_C_ABI LLVMValueRef LLVMConstPointerNull (LLVMTypeRef Ty)
Obtain a constant that is a constant pointer pointing to NULL for a specified type.
Definition at line 1279 of file Core.cpp.
References llvm::ConstantPointerNull::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetPoison()
LLVM_C_ABI LLVMValueRef LLVMGetPoison (LLVMTypeRef Ty)
Obtain a constant value referring to a poison value of a type.
See also
llvm::PoisonValue::get()
Definition at line 1257 of file Core.cpp.
References llvm::PoisonValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetUndef()
LLVM_C_ABI LLVMValueRef LLVMGetUndef (LLVMTypeRef Ty)
Obtain a constant value referring to an undefined value of a type.
See also
llvm::UndefValue::get()
Definition at line 1253 of file Core.cpp.
References llvm::UndefValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMIsNull()
LLVM_C_ABI LLVMBool LLVMIsNull (LLVMValueRef Val)
Determine whether a value instance is null.
See also
llvm::Constant::isNullValue()
Definition at line 1265 of file Core.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), and llvm::unwrap().