LLVM: Debug Information
Debug Information
LLVM-C: C interface to LLVM » Core
This file declares the C API endpoints for generating DWARF Debug Info.
Typedefs
typedef unsigned LLVMMetadataKind
typedef unsigned LLVMDWARFTypeEncoding
An LLVM DWARF type encoding.
Enumerations
enum LLVMDIFlags {
LLVMDIFlagZero = 0 , LLVMDIFlagPrivate = 1 , LLVMDIFlagProtected = 2 , LLVMDIFlagPublic = 3 ,
LLVMDIFlagFwdDecl = 1 << 2 , LLVMDIFlagAppleBlock = 1 << 3 , LLVMDIFlagReservedBit4 = 1 << 4 , LLVMDIFlagVirtual = 1 << 5 ,
LLVMDIFlagArtificial = 1 << 6 , LLVMDIFlagExplicit = 1 << 7 , LLVMDIFlagPrototyped = 1 << 8 , LLVMDIFlagObjcClassComplete = 1 << 9 ,
LLVMDIFlagObjectPointer = 1 << 10 , LLVMDIFlagVector = 1 << 11 , LLVMDIFlagStaticMember = 1 << 12 , LLVMDIFlagLValueReference = 1 << 13 ,
LLVMDIFlagRValueReference = 1 << 14 , LLVMDIFlagReserved = 1 << 15 , LLVMDIFlagSingleInheritance = 1 << 16 , LLVMDIFlagMultipleInheritance = 2 << 16 ,
LLVMDIFlagVirtualInheritance = 3 << 16 , LLVMDIFlagIntroducedVirtual = 1 << 18 , LLVMDIFlagBitField = 1 << 19 , LLVMDIFlagNoReturn = 1 << 20 ,
LLVMDIFlagTypePassByValue = 1 << 22 , LLVMDIFlagTypePassByReference = 1 << 23 , LLVMDIFlagEnumClass = 1 << 24 , LLVMDIFlagFixedEnum = LLVMDIFlagEnumClass ,
LLVMDIFlagThunk = 1 << 25 , LLVMDIFlagNonTrivial = 1 << 26 , LLVMDIFlagBigEndian = 1 << 27 , LLVMDIFlagLittleEndian = 1 << 28 ,
LLVMDIFlagIndirectVirtualBase = (1 << 2) | (1 << 5) , LLVMDIFlagAccessibility , LLVMDIFlagPtrToMemberRep
}
Debug info flags.
enum LLVMDWARFSourceLanguage {
LLVMDWARFSourceLanguageC89 , LLVMDWARFSourceLanguageC , LLVMDWARFSourceLanguageAda83 , LLVMDWARFSourceLanguageC_plus_plus ,
LLVMDWARFSourceLanguageCobol74 , LLVMDWARFSourceLanguageCobol85 , LLVMDWARFSourceLanguageFortran77 , LLVMDWARFSourceLanguageFortran90 ,
LLVMDWARFSourceLanguagePascal83 , LLVMDWARFSourceLanguageModula2 , LLVMDWARFSourceLanguageJava , LLVMDWARFSourceLanguageC99 ,
LLVMDWARFSourceLanguageAda95 , LLVMDWARFSourceLanguageFortran95 , LLVMDWARFSourceLanguagePLI , LLVMDWARFSourceLanguageObjC ,
LLVMDWARFSourceLanguageObjC_plus_plus , LLVMDWARFSourceLanguageUPC , LLVMDWARFSourceLanguageD , LLVMDWARFSourceLanguagePython ,
LLVMDWARFSourceLanguageOpenCL , LLVMDWARFSourceLanguageGo , LLVMDWARFSourceLanguageModula3 , LLVMDWARFSourceLanguageHaskell ,
LLVMDWARFSourceLanguageC_plus_plus_03 , LLVMDWARFSourceLanguageC_plus_plus_11 , LLVMDWARFSourceLanguageOCaml , LLVMDWARFSourceLanguageRust ,
LLVMDWARFSourceLanguageC11 , LLVMDWARFSourceLanguageSwift , LLVMDWARFSourceLanguageJulia , LLVMDWARFSourceLanguageDylan ,
LLVMDWARFSourceLanguageC_plus_plus_14 , LLVMDWARFSourceLanguageFortran03 , LLVMDWARFSourceLanguageFortran08 , LLVMDWARFSourceLanguageRenderScript ,
LLVMDWARFSourceLanguageBLISS , LLVMDWARFSourceLanguageKotlin , LLVMDWARFSourceLanguageZig , LLVMDWARFSourceLanguageCrystal ,
LLVMDWARFSourceLanguageC_plus_plus_17 , LLVMDWARFSourceLanguageC_plus_plus_20 , LLVMDWARFSourceLanguageC17 , LLVMDWARFSourceLanguageFortran18 ,
LLVMDWARFSourceLanguageAda2005 , LLVMDWARFSourceLanguageAda2012 , LLVMDWARFSourceLanguageHIP , LLVMDWARFSourceLanguageAssembly ,
LLVMDWARFSourceLanguageC_sharp , LLVMDWARFSourceLanguageMojo , LLVMDWARFSourceLanguageGLSL , LLVMDWARFSourceLanguageGLSL_ES ,
LLVMDWARFSourceLanguageHLSL , LLVMDWARFSourceLanguageOpenCL_CPP , LLVMDWARFSourceLanguageCPP_for_OpenCL , LLVMDWARFSourceLanguageSYCL ,
LLVMDWARFSourceLanguageRuby , LLVMDWARFSourceLanguageMove , LLVMDWARFSourceLanguageHylo , LLVMDWARFSourceLanguageMetal ,
LLVMDWARFSourceLanguageMips_Assembler , LLVMDWARFSourceLanguageGOOGLE_RenderScript , LLVMDWARFSourceLanguageBORLAND_Delphi
}
Source languages known by DWARF.
enum LLVMDWARFEmissionKind { LLVMDWARFEmissionNone = 0 , LLVMDWARFEmissionFull , LLVMDWARFEmissionLineTablesOnly }
The amount of debug information to emit.
enum {
LLVMMDStringMetadataKind , LLVMConstantAsMetadataMetadataKind , LLVMLocalAsMetadataMetadataKind , LLVMDistinctMDOperandPlaceholderMetadataKind ,
LLVMMDTupleMetadataKind , LLVMDILocationMetadataKind , LLVMDIExpressionMetadataKind , LLVMDIGlobalVariableExpressionMetadataKind ,
LLVMGenericDINodeMetadataKind , LLVMDISubrangeMetadataKind , LLVMDIEnumeratorMetadataKind , LLVMDIBasicTypeMetadataKind ,
LLVMDIDerivedTypeMetadataKind , LLVMDICompositeTypeMetadataKind , LLVMDISubroutineTypeMetadataKind , LLVMDIFileMetadataKind ,
LLVMDICompileUnitMetadataKind , LLVMDISubprogramMetadataKind , LLVMDILexicalBlockMetadataKind , LLVMDILexicalBlockFileMetadataKind ,
LLVMDINamespaceMetadataKind , LLVMDIModuleMetadataKind , LLVMDITemplateTypeParameterMetadataKind , LLVMDITemplateValueParameterMetadataKind ,
LLVMDIGlobalVariableMetadataKind , LLVMDILocalVariableMetadataKind , LLVMDILabelMetadataKind , LLVMDIObjCPropertyMetadataKind ,
LLVMDIImportedEntityMetadataKind , LLVMDIMacroMetadataKind , LLVMDIMacroFileMetadataKind , LLVMDICommonBlockMetadataKind ,
LLVMDIStringTypeMetadataKind , LLVMDIGenericSubrangeMetadataKind , LLVMDIArgListMetadataKind , LLVMDIAssignIDMetadataKind ,
LLVMDISubrangeTypeMetadataKind , LLVMDIFixedPointTypeMetadataKind
}
The kind of metadata nodes.
enum LLVMChecksumKind { CSK_MD5 , CSK_SHA1 , CSK_SHA256 }
The kind of checksum to emit.
enum LLVMDWARFMacinfoRecordType {
LLVMDWARFMacinfoRecordTypeDefine = 0x01 , LLVMDWARFMacinfoRecordTypeMacro = 0x02 , LLVMDWARFMacinfoRecordTypeStartFile = 0x03 , LLVMDWARFMacinfoRecordTypeEndFile = 0x04 ,
LLVMDWARFMacinfoRecordTypeVendorExt = 0xff
}
Describes the kind of macro declaration used for LLVMDIBuilderCreateMacro.
Functions
LLVM_C_ABI unsigned LLVMDebugMetadataVersion (void)
The current debug metadata version number.
LLVM_C_ABI unsigned LLVMGetModuleDebugMetadataVersion (LLVMModuleRef Module)
The version of debug metadata that's present in the provided Module.
LLVM_C_ABI LLVMBool LLVMStripModuleDebugInfo (LLVMModuleRef Module)
Strip debug info in the module if it exists.
LLVM_C_ABI LLVMDIBuilderRef LLVMCreateDIBuilderDisallowUnresolved (LLVMModuleRef M)
Construct a builder for a module, and do not allow for unresolved nodes attached to the module.
LLVM_C_ABI LLVMDIBuilderRef LLVMCreateDIBuilder (LLVMModuleRef M)
Construct a builder for a module and collect unresolved nodes attached to the module in order to resolve cycles during a call to LLVMDIBuilderFinalize.
LLVM_C_ABI void LLVMDisposeDIBuilder (LLVMDIBuilderRef Builder)
Deallocates the DIBuilder and everything it owns.
LLVM_C_ABI void LLVMDIBuilderFinalize (LLVMDIBuilderRef Builder)
Construct any deferred debug info descriptors.
LLVM_C_ABI void LLVMDIBuilderFinalizeSubprogram (LLVMDIBuilderRef Builder, LLVMMetadataRef Subprogram)
Finalize a specific subprogram.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateCompileUnit (LLVMDIBuilderRef Builder, LLVMDWARFSourceLanguage Lang, LLVMMetadataRef FileRef, const char *Producer, size_t ProducerLen, LLVMBool isOptimized, const char *Flags, size_t FlagsLen, unsigned RuntimeVer, const char *SplitName, size_t SplitNameLen, LLVMDWARFEmissionKind Kind, unsigned DWOId, LLVMBool SplitDebugInlining, LLVMBool DebugInfoForProfiling, const char *SysRoot, size_t SysRootLen, const char *SDK, size_t SDKLen)
A CompileUnit provides an anchor for all debugging information generated during this instance of compilation.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateFile (LLVMDIBuilderRef Builder, const char *Filename, size_t FilenameLen, const char *Directory, size_t DirectoryLen)
Create a file descriptor to hold debugging information for a file.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateFileWithChecksum (LLVMDIBuilderRef Builder, const char *Filename, size_t FilenameLen, const char *Directory, size_t DirectoryLen, LLVMChecksumKind ChecksumKind, const char *Checksum, size_t ChecksumLen, const char *Source, size_t SourceLen)
Create a file descriptor to hold debugging information for a file.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateModule (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char *Name, size_t NameLen, const char *ConfigMacros, size_t ConfigMacrosLen, const char *IncludePath, size_t IncludePathLen, const char *APINotesFile, size_t APINotesFileLen)
Creates a new descriptor for a module with the specified parent scope.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateNameSpace (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char *Name, size_t NameLen, LLVMBool ExportSymbols)
Creates a new descriptor for a namespace with the specified parent scope.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateFunction (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, const char *LinkageName, size_t LinkageNameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool IsLocalToUnit, LLVMBool IsDefinition, unsigned ScopeLine, LLVMDIFlags Flags, LLVMBool IsOptimized)
Create a new descriptor for the specified subprogram.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateLexicalBlock (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned Column)
Create a descriptor for a lexical block with the specified parent context.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateLexicalBlockFile (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Discriminator)
Create a descriptor for a lexical block with a new file attached.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromNamespace (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef NS, LLVMMetadataRef File, unsigned Line)
Create a descriptor for an imported namespace.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromAlias (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef ImportedEntity, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef *Elements, unsigned NumElements)
Create a descriptor for an imported module that aliases another imported entity descriptor.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromModule (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef M, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef *Elements, unsigned NumElements)
Create a descriptor for an imported module.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedDeclaration (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef Decl, LLVMMetadataRef File, unsigned Line, const char *Name, size_t NameLen, LLVMMetadataRef *Elements, unsigned NumElements)
Create a descriptor for an imported function, type, or variable.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateDebugLocation (LLVMContextRef Ctx, unsigned Line, unsigned Column, LLVMMetadataRef Scope, LLVMMetadataRef InlinedAt)
Creates a new DebugLocation that describes a source location.
LLVM_C_ABI unsigned LLVMDILocationGetLine (LLVMMetadataRef Location)
Get the line number of this debug location.
LLVM_C_ABI unsigned LLVMDILocationGetColumn (LLVMMetadataRef Location)
Get the column number of this debug location.
LLVM_C_ABI LLVMMetadataRef LLVMDILocationGetScope (LLVMMetadataRef Location)
Get the local scope associated with this debug location.
LLVM_C_ABI LLVMMetadataRef LLVMDILocationGetInlinedAt (LLVMMetadataRef Location)
Get the "inline at" location associated with this debug location.
LLVM_C_ABI LLVMMetadataRef LLVMDIScopeGetFile (LLVMMetadataRef Scope)
Get the metadata of the file associated with a given scope.
LLVM_C_ABI const char * LLVMDIFileGetDirectory (LLVMMetadataRef File, unsigned *Len)
Get the directory of a given file.
LLVM_C_ABI const char * LLVMDIFileGetFilename (LLVMMetadataRef File, unsigned *Len)
Get the name of a given file.
LLVM_C_ABI const char * LLVMDIFileGetSource (LLVMMetadataRef File, unsigned *Len)
Get the source of a given file.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderGetOrCreateTypeArray (LLVMDIBuilderRef Builder, LLVMMetadataRef *Data, size_t NumElements)
Create a type array.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateSubroutineType (LLVMDIBuilderRef Builder, LLVMMetadataRef File, LLVMMetadataRef *ParameterTypes, unsigned NumParameterTypes, LLVMDIFlags Flags)
Create subroutine type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateMacro (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMDWARFMacinfoRecordType RecordType, const char *Name, size_t NameLen, const char *Value, size_t ValueLen)
Create debugging information entry for a macro.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateTempMacroFile (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMMetadataRef File)
Create debugging information temporary entry for a macro file.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateEnumerator (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, int64_t Value, LLVMBool IsUnsigned)
Create debugging information entry for an enumerator.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateEnumeratorOfArbitraryPrecision (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, uint64_t SizeInBits, const uint64_t Words[], LLVMBool IsUnsigned)
Create debugging information entry for an enumerator of arbitrary precision.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateEnumerationType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMMetadataRef *Elements, unsigned NumElements, LLVMMetadataRef ClassTy)
Create debugging information entry for an enumeration.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateUnionType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef *Elements, unsigned NumElements, unsigned RunTimeLang, const char *UniqueId, size_t UniqueIdLen)
Create debugging information entry for a union.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateArrayType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef *Subscripts, unsigned NumSubscripts)
Create debugging information entry for an array.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateSetType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMMetadataRef BaseTy)
Create debugging information entry for a set.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateSubrangeType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, unsigned LineNo, LLVMMetadataRef File, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef BaseTy, LLVMMetadataRef LowerBound, LLVMMetadataRef UpperBound, LLVMMetadataRef Stride, LLVMMetadataRef Bias)
Create a descriptor for a subrange with dynamic bounds.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateDynamicArrayType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, unsigned LineNo, LLVMMetadataRef File, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef *Subscripts, unsigned NumSubscripts, LLVMMetadataRef DataLocation, LLVMMetadataRef Associated, LLVMMetadataRef Allocated, LLVMMetadataRef Rank, LLVMMetadataRef BitStride)
Create debugging information entry for a dynamic array.
LLVM_C_ABI void LLVMReplaceArrays (LLVMDIBuilderRef Builder, LLVMMetadataRef *T, LLVMMetadataRef *Elements, unsigned NumElements)
Replace arrays.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateVectorType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef *Subscripts, unsigned NumSubscripts)
Create debugging information entry for a vector type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateUnspecifiedType (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen)
Create a DWARF unspecified type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateBasicType (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, uint64_t SizeInBits, LLVMDWARFTypeEncoding Encoding, LLVMDIFlags Flags)
Create debugging information entry for a basic type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreatePointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeTy, uint64_t SizeInBits, uint32_t AlignInBits, unsigned AddressSpace, const char *Name, size_t NameLen)
Create debugging information entry for a pointer.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateStructType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef *Elements, unsigned NumElements, unsigned RunTimeLang, LLVMMetadataRef VTableHolder, const char *UniqueId, size_t UniqueIdLen)
Create debugging information entry for a struct.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty)
Create debugging information entry for a member.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateStaticMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, LLVMMetadataRef Type, LLVMDIFlags Flags, LLVMValueRef ConstantVal, uint32_t AlignInBits)
Create debugging information entry for a C++ static data member.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateMemberPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeType, LLVMMetadataRef ClassType, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags)
Create debugging information entry for a pointer to member.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateObjCIVar (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty, LLVMMetadataRef PropertyNode)
Create debugging information entry for Objective-C instance variable.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateObjCProperty (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, const char *GetterName, size_t GetterNameLen, const char *SetterName, size_t SetterNameLen, unsigned PropertyAttributes, LLVMMetadataRef Ty)
Create debugging information entry for Objective-C property.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateObjectPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type, LLVMBool Implicit)
Create a uniqued DIType* clone with FlagObjectPointer.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateQualifiedType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a qualified type, e.g.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateReferenceType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a c++ style reference or rvalue reference type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateNullPtrType (LLVMDIBuilderRef Builder)
Create C++11 nullptr type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateTypedef (LLVMDIBuilderRef Builder, LLVMMetadataRef Type, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Scope, uint32_t AlignInBits)
Create debugging information entry for a typedef.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateInheritance (LLVMDIBuilderRef Builder, LLVMMetadataRef Ty, LLVMMetadataRef BaseTy, uint64_t BaseOffset, uint32_t VBPtrOffset, LLVMDIFlags Flags)
Create debugging information entry to establish inheritance relationship between two types.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateForwardDecl (LLVMDIBuilderRef Builder, unsigned Tag, const char *Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, const char *UniqueIdentifier, size_t UniqueIdentifierLen)
Create a permanent forward-declared type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateReplaceableCompositeType (LLVMDIBuilderRef Builder, unsigned Tag, const char *Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, const char *UniqueIdentifier, size_t UniqueIdentifierLen)
Create a temporary forward-declared type.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateBitFieldMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint64_t OffsetInBits, uint64_t StorageOffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Type)
Create debugging information entry for a bit field member.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateClassType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef *Elements, unsigned NumElements, LLVMMetadataRef VTableHolder, LLVMMetadataRef TemplateParamsNode, const char *UniqueIdentifier, size_t UniqueIdentifierLen)
Create debugging information entry for a class.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateArtificialType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type)
Create a uniqued DIType* clone with FlagArtificial set.
LLVM_C_ABI const char * LLVMDITypeGetName (LLVMMetadataRef DType, size_t *Length)
Get the name of this DIType.
LLVM_C_ABI uint64_t LLVMDITypeGetSizeInBits (LLVMMetadataRef DType)
Get the size of this DIType in bits.
LLVM_C_ABI uint64_t LLVMDITypeGetOffsetInBits (LLVMMetadataRef DType)
Get the offset of this DIType in bits.
LLVM_C_ABI uint32_t LLVMDITypeGetAlignInBits (LLVMMetadataRef DType)
Get the alignment of this DIType in bits.
LLVM_C_ABI unsigned LLVMDITypeGetLine (LLVMMetadataRef DType)
Get the source line where this DIType is declared.
LLVM_C_ABI LLVMDIFlags LLVMDITypeGetFlags (LLVMMetadataRef DType)
Get the flags associated with this DIType.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderGetOrCreateSubrange (LLVMDIBuilderRef Builder, int64_t LowerBound, int64_t Count)
Create a descriptor for a value range.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderGetOrCreateArray (LLVMDIBuilderRef Builder, LLVMMetadataRef *Data, size_t NumElements)
Create an array of DI Nodes.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateExpression (LLVMDIBuilderRef Builder, uint64_t *Addr, size_t Length)
Create a new descriptor for the specified variable which has a complex address expression for its address.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateConstantValueExpression (LLVMDIBuilderRef Builder, uint64_t Value)
Create a new descriptor for the specified variable that does not have an address, but does have a constant value.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateGlobalVariableExpression (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, const char *Linkage, size_t LinkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Expr, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified variable.
LLVM_C_ABI uint16_t LLVMGetDINodeTag (LLVMMetadataRef MD)
Get the dwarf::Tag of a DINode.
LLVM_C_ABI LLVMMetadataRef LLVMDIGlobalVariableExpressionGetVariable (LLVMMetadataRef GVE)
Retrieves the DIVariable associated with this global variable expression.
LLVM_C_ABI LLVMMetadataRef LLVMDIGlobalVariableExpressionGetExpression (LLVMMetadataRef GVE)
Retrieves the DIExpression associated with this global variable expression.
LLVM_C_ABI LLVMMetadataRef LLVMDIVariableGetFile (LLVMMetadataRef Var)
Get the metadata of the file associated with a given variable.
LLVM_C_ABI LLVMMetadataRef LLVMDIVariableGetScope (LLVMMetadataRef Var)
Get the metadata of the scope associated with a given variable.
LLVM_C_ABI unsigned LLVMDIVariableGetLine (LLVMMetadataRef Var)
Get the source line where this DIVariable is declared.
LLVM_C_ABI LLVMMetadataRef LLVMTemporaryMDNode (LLVMContextRef Ctx, LLVMMetadataRef *Data, size_t NumElements)
Create a new temporary MDNode.
LLVM_C_ABI void LLVMDisposeTemporaryMDNode (LLVMMetadataRef TempNode)
Deallocate a temporary node.
LLVM_C_ABI void LLVMMetadataReplaceAllUsesWith (LLVMMetadataRef TempTargetMetadata, LLVMMetadataRef Replacement)
Replace all uses of temporary metadata.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateTempGlobalVariableFwdDecl (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, const char *Linkage, size_t LnkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified global variable that is temporary and meant to be RAUWed.
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDeclareRecordBefore (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDeclareRecordAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDbgValueRecordBefore (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDbgValueRecordAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateAutoVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags, uint32_t AlignInBits)
Create a new descriptor for a local auto variable.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateParameterVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, unsigned ArgNo, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags)
Create a new descriptor for a function parameter variable.
LLVM_C_ABI LLVMMetadataRef LLVMGetSubprogram (LLVMValueRef Func)
Get the metadata of the subprogram attached to a function.
LLVM_C_ABI void LLVMSetSubprogram (LLVMValueRef Func, LLVMMetadataRef SP)
Set the subprogram attached to a function.
LLVM_C_ABI unsigned LLVMDISubprogramGetLine (LLVMMetadataRef Subprogram)
Get the line associated with a given subprogram.
LLVM_C_ABI void LLVMDISubprogramReplaceType (LLVMMetadataRef Subprogram, LLVMMetadataRef SubroutineType)
Replace the subprogram subroutine type.
LLVM_C_ABI LLVMMetadataRef LLVMInstructionGetDebugLoc (LLVMValueRef Inst)
Get the debug location for the given instruction.
LLVM_C_ABI void LLVMInstructionSetDebugLoc (LLVMValueRef Inst, LLVMMetadataRef Loc)
Set the debug location for the given instruction.
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateLabel (LLVMDIBuilderRef Builder, LLVMMetadataRef Context, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMBool AlwaysPreserve)
Create a new descriptor for a label.
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertLabelBefore (LLVMDIBuilderRef Builder, LLVMMetadataRef LabelInfo, LLVMMetadataRef Location, LLVMValueRef InsertBefore)
Insert a new llvm.dbg.label intrinsic call.
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertLabelAtEnd (LLVMDIBuilderRef Builder, LLVMMetadataRef LabelInfo, LLVMMetadataRef Location, LLVMBasicBlockRef InsertAtEnd)
Insert a new llvm.dbg.label intrinsic call.
LLVM_C_ABI LLVMMetadataKind LLVMGetMetadataKind (LLVMMetadataRef Metadata)
Obtain the enumerated type of a Metadata instance.
Detailed Description
This file declares the C API endpoints for generating DWARF Debug Info.
Note: This interface is experimental. It is NOT stable, and may be changed without warning.
Typedef Documentation
LLVMDWARFTypeEncoding
typedef unsigned LLVMDWARFTypeEncoding
An LLVM DWARF type encoding.
Definition at line 214 of file DebugInfo.h.
LLVMMetadataKind
typedef unsigned LLVMMetadataKind
Definition at line 204 of file DebugInfo.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
The kind of metadata nodes.
Enumerator
LLVMMDStringMetadataKind
LLVMConstantAsMetadataMetadataKind
LLVMLocalAsMetadataMetadataKind
LLVMDistinctMDOperandPlaceholderMetadataKind
LLVMMDTupleMetadataKind
LLVMDILocationMetadataKind
LLVMDIExpressionMetadataKind
LLVMDIGlobalVariableExpressionMetadataKind
LLVMGenericDINodeMetadataKind
LLVMDISubrangeMetadataKind
LLVMDIEnumeratorMetadataKind
LLVMDIBasicTypeMetadataKind
LLVMDIDerivedTypeMetadataKind
LLVMDICompositeTypeMetadataKind
LLVMDISubroutineTypeMetadataKind
LLVMDIFileMetadataKind
LLVMDICompileUnitMetadataKind
LLVMDISubprogramMetadataKind
LLVMDILexicalBlockMetadataKind
LLVMDILexicalBlockFileMetadataKind
LLVMDINamespaceMetadataKind
LLVMDIModuleMetadataKind
LLVMDITemplateTypeParameterMetadataKind
LLVMDITemplateValueParameterMetadataKind
LLVMDIGlobalVariableMetadataKind
LLVMDILocalVariableMetadataKind
LLVMDILabelMetadataKind
LLVMDIObjCPropertyMetadataKind
LLVMDIImportedEntityMetadataKind
LLVMDIMacroMetadataKind
LLVMDIMacroFileMetadataKind
LLVMDICommonBlockMetadataKind
LLVMDIStringTypeMetadataKind
LLVMDIGenericSubrangeMetadataKind
LLVMDIArgListMetadataKind
LLVMDIAssignIDMetadataKind
LLVMDISubrangeTypeMetadataKind
LLVMDIFixedPointTypeMetadataKind
Definition at line 164 of file DebugInfo.h.
LLVMChecksumKind
enum LLVMChecksumKind
The kind of checksum to emit.
Enumerator
CSK_MD5
CSK_SHA1
CSK_SHA256
Definition at line 209 of file DebugInfo.h.
LLVMDIFlags
enum LLVMDIFlags
Debug info flags.
Enumerator
LLVMDIFlagZero
LLVMDIFlagPrivate
LLVMDIFlagProtected
LLVMDIFlagPublic
LLVMDIFlagFwdDecl
LLVMDIFlagAppleBlock
LLVMDIFlagReservedBit4
LLVMDIFlagVirtual
LLVMDIFlagArtificial
LLVMDIFlagExplicit
LLVMDIFlagPrototyped
LLVMDIFlagObjcClassComplete
LLVMDIFlagObjectPointer
LLVMDIFlagVector
LLVMDIFlagStaticMember
LLVMDIFlagLValueReference
LLVMDIFlagRValueReference
LLVMDIFlagReserved
LLVMDIFlagSingleInheritance
LLVMDIFlagMultipleInheritance
LLVMDIFlagVirtualInheritance
LLVMDIFlagIntroducedVirtual
LLVMDIFlagBitField
LLVMDIFlagNoReturn
LLVMDIFlagTypePassByValue
LLVMDIFlagTypePassByReference
LLVMDIFlagEnumClass
LLVMDIFlagFixedEnum
LLVMDIFlagThunk
LLVMDIFlagNonTrivial
LLVMDIFlagBigEndian
LLVMDIFlagLittleEndian
LLVMDIFlagIndirectVirtualBase
LLVMDIFlagAccessibility
LLVMDIFlagPtrToMemberRep
Definition at line 35 of file DebugInfo.h.
LLVMDWARFEmissionKind
enum LLVMDWARFEmissionKind
The amount of debug information to emit.
Enumerator
LLVMDWARFEmissionNone
LLVMDWARFEmissionFull
LLVMDWARFEmissionLineTablesOnly
Definition at line 153 of file DebugInfo.h.
LLVMDWARFMacinfoRecordType
enum LLVMDWARFMacinfoRecordType
Describes the kind of macro declaration used for LLVMDIBuilderCreateMacro.
See also
llvm::dwarf::MacinfoRecordType
Note
Values are from DW_MACINFO_* constants in the DWARF specification.
Enumerator
LLVMDWARFMacinfoRecordTypeDefine
LLVMDWARFMacinfoRecordTypeMacro
LLVMDWARFMacinfoRecordTypeStartFile
LLVMDWARFMacinfoRecordTypeEndFile
LLVMDWARFMacinfoRecordTypeVendorExt
Definition at line 221 of file DebugInfo.h.
LLVMDWARFSourceLanguage
enum LLVMDWARFSourceLanguage
Source languages known by DWARF.
Enumerator
LLVMDWARFSourceLanguageC89
LLVMDWARFSourceLanguageC
LLVMDWARFSourceLanguageAda83
LLVMDWARFSourceLanguageC_plus_plus
LLVMDWARFSourceLanguageCobol74
LLVMDWARFSourceLanguageCobol85
LLVMDWARFSourceLanguageFortran77
LLVMDWARFSourceLanguageFortran90
LLVMDWARFSourceLanguagePascal83
LLVMDWARFSourceLanguageModula2
LLVMDWARFSourceLanguageJava
LLVMDWARFSourceLanguageC99
LLVMDWARFSourceLanguageAda95
LLVMDWARFSourceLanguageFortran95
LLVMDWARFSourceLanguagePLI
LLVMDWARFSourceLanguageObjC
LLVMDWARFSourceLanguageObjC_plus_plus
LLVMDWARFSourceLanguageUPC
LLVMDWARFSourceLanguageD
LLVMDWARFSourceLanguagePython
LLVMDWARFSourceLanguageOpenCL
LLVMDWARFSourceLanguageGo
LLVMDWARFSourceLanguageModula3
LLVMDWARFSourceLanguageHaskell
LLVMDWARFSourceLanguageC_plus_plus_03
LLVMDWARFSourceLanguageC_plus_plus_11
LLVMDWARFSourceLanguageOCaml
LLVMDWARFSourceLanguageRust
LLVMDWARFSourceLanguageC11
LLVMDWARFSourceLanguageSwift
LLVMDWARFSourceLanguageJulia
LLVMDWARFSourceLanguageDylan
LLVMDWARFSourceLanguageC_plus_plus_14
LLVMDWARFSourceLanguageFortran03
LLVMDWARFSourceLanguageFortran08
LLVMDWARFSourceLanguageRenderScript
LLVMDWARFSourceLanguageBLISS
LLVMDWARFSourceLanguageKotlin
LLVMDWARFSourceLanguageZig
LLVMDWARFSourceLanguageCrystal
LLVMDWARFSourceLanguageC_plus_plus_17
LLVMDWARFSourceLanguageC_plus_plus_20
LLVMDWARFSourceLanguageC17
LLVMDWARFSourceLanguageFortran18
LLVMDWARFSourceLanguageAda2005
LLVMDWARFSourceLanguageAda2012
LLVMDWARFSourceLanguageHIP
LLVMDWARFSourceLanguageAssembly
LLVMDWARFSourceLanguageC_sharp
LLVMDWARFSourceLanguageMojo
LLVMDWARFSourceLanguageGLSL
LLVMDWARFSourceLanguageGLSL_ES
LLVMDWARFSourceLanguageHLSL
LLVMDWARFSourceLanguageOpenCL_CPP
LLVMDWARFSourceLanguageCPP_for_OpenCL
LLVMDWARFSourceLanguageSYCL
LLVMDWARFSourceLanguageRuby
LLVMDWARFSourceLanguageMove
LLVMDWARFSourceLanguageHylo
LLVMDWARFSourceLanguageMetal
LLVMDWARFSourceLanguageMips_Assembler
LLVMDWARFSourceLanguageGOOGLE_RenderScript
LLVMDWARFSourceLanguageBORLAND_Delphi
Definition at line 79 of file DebugInfo.h.
Function Documentation
LLVMCreateDIBuilder()
LLVM_C_ABI LLVMDIBuilderRef LLVMCreateDIBuilder (LLVMModuleRef M)
Construct a builder for a module and collect unresolved nodes attached to the module in order to resolve cycles during a call to LLVMDIBuilderFinalize.
Definition at line 1059 of file DebugInfo.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMCreateDIBuilderDisallowUnresolved()
LLVM_C_ABI LLVMDIBuilderRef LLVMCreateDIBuilderDisallowUnresolved (LLVMModuleRef M)
Construct a builder for a module, and do not allow for unresolved nodes attached to the module.
Definition at line 1055 of file DebugInfo.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMDebugMetadataVersion()
LLVM_C_ABI unsigned LLVMDebugMetadataVersion (void)
The current debug metadata version number.
Definition at line 1051 of file DebugInfo.cpp.
References llvm::DEBUG_METADATA_VERSION.
LLVMDIBuilderCreateArrayType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateArrayType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef * Subscripts, unsigned NumSubscripts)
Create debugging information entry for an array.
Parameters
Builder The DIBuilder.
Size Array size.
AlignInBits Alignment.
Ty Element type.
Subscripts Subscripts.
NumSubscripts Number of subscripts.
Definition at line 1417 of file DebugInfo.cpp.
References Size, llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateArtificialType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateArtificialType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type)
Create a uniqued DIType* clone with FlagArtificial set.
Parameters
Builder The DIBuilder.
Type The underlying type.
Definition at line 1649 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateAutoVariable()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateAutoVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags, uint32_t AlignInBits)
Create a new descriptor for a local auto variable.
Parameters
Builder The DIBuilder.
Scope The local scope the variable is declared in.
Name Variable name.
NameLen Length of variable name.
File File where this variable is defined.
LineNo Line number.
Ty Metadata describing the type of the variable.
AlwaysPreserve If true, this descriptor will survive optimizations.
Flags Flags.
AlignInBits Variable alignment.
Definition at line 1845 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateBasicType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateBasicType (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, uint64_t SizeInBits, LLVMDWARFTypeEncoding Encoding, LLVMDIFlags Flags)
Create debugging information entry for a basic type.
Parameters
Builder The DIBuilder.
Name Type name.
NameLen Length of type name.
SizeInBits Size of the type.
Encoding DWARF encoding code, e.g. LLVMDWARFTypeEncoding_float.
Flags Flags to encode optional attribute like endianity
Definition at line 1439 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateBitFieldMemberType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateBitFieldMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint64_t OffsetInBits, uint64_t StorageOffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Type)
Create debugging information entry for a bit field member.
Parameters
Builder The DIBuilder.
Scope Member scope.
Name Member name.
NameLen Length of member name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
OffsetInBits Member offset.
StorageOffsetInBits Member storage offset.
Flags Flags to encode member attribute.
Type Parent type.
Definition at line 1614 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateClassType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateClassType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef * Elements, unsigned NumElements, LLVMMetadataRef VTableHolder, LLVMMetadataRef TemplateParamsNode, const char * UniqueIdentifier, size_t UniqueIdentifierLen)
Create debugging information entry for a class.
Parameters
Scope Scope in which this class is defined.
Name Class name.
NameLen The length of the C string passed to Name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private.
DerivedFrom Debug info of the base class of this type.
Elements Class members.
NumElements Number of class elements.
VTableHolder Debug info of the base class that contains vtable for this type. This is used in DW_AT_containing_type. See DWARF documentation for more info.
TemplateParamsNode Template type parameters.
UniqueIdentifier A unique identifier for the type.
UniqueIdentifierLen Length of the unique identifier.
Definition at line 1629 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateCompileUnit()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateCompileUnit (LLVMDIBuilderRef Builder, LLVMDWARFSourceLanguage Lang, LLVMMetadataRef FileRef, const char * Producer, size_t ProducerLen, LLVMBool isOptimized, const char * Flags, size_t FlagsLen, unsigned RuntimeVer, const char * SplitName, size_t SplitNameLen, LLVMDWARFEmissionKind Kind, unsigned DWOId, LLVMBool SplitDebugInlining, LLVMBool DebugInfoForProfiling, const char * SysRoot, size_t SysRootLen, const char * SDK, size_t SDKLen)
A CompileUnit provides an anchor for all debugging information generated during this instance of compilation.
Parameters
Lang Source programming language, eg. LLVMDWARFSourceLanguageC99
FileRef File info.
Producer Identify the producer of debugging information and code. Usually this is a compiler version string.
ProducerLen The length of the C string passed to Producer.
isOptimized A boolean flag which indicates whether optimization is enabled or not.
Flags This string lists command line options. This string is directly embedded in debug info output which may be used by a tool analyzing generated debugging information.
FlagsLen The length of the C string passed to Flags.
RuntimeVer This indicates runtime version for languages like Objective-C.
SplitName The name of the file that we'll split debug info out into.
SplitNameLen The length of the C string passed to SplitName.
Kind The kind of debug information to generate.
DWOId The DWOId if this is a split skeleton compile unit.
SplitDebugInlining Whether to emit inline debug info.
DebugInfoForProfiling Whether to emit extra debug info for profile collection.
SysRoot The Clang system root (value of -isysroot).
SysRootLen The length of the C string passed to SysRoot.
SDK The SDK. On Darwin, the last component of the sysroot.
SDKLen The length of the C string passed to SDK.
Definition at line 1084 of file DebugInfo.cpp.
References llvm::DICompileUnit::Default, map_from_llvmDWARFsourcelanguage(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateConstantValueExpression()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateConstantValueExpression (LLVMDIBuilderRef Builder, uint64_t Value)
Create a new descriptor for the specified variable that does not have an address, but does have a constant value.
Parameters
Builder The DIBuilder.
Value The constant value.
Definition at line 1710 of file DebugInfo.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateDebugLocation()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateDebugLocation (LLVMContextRef Ctx, unsigned Line, unsigned Column, LLVMMetadataRef Scope, LLVMMetadataRef InlinedAt)
Creates a new DebugLocation that describes a source location.
Parameters
table emission The line in the source file.
Column The column in the source file.
Scope The scope in which the location resides.
InlinedAt The scope where this location was inlined, if at all. (optional).
Note
If the item to which this location is attached cannot be attributed to a source line, pass 0 for the line and column.
Definition at line 1247 of file DebugInfo.cpp.
References llvm::MDNode::get(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateDynamicArrayType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateDynamicArrayType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, unsigned LineNo, LLVMMetadataRef File, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef * Subscripts, unsigned NumSubscripts, LLVMMetadataRef DataLocation, LLVMMetadataRef Associated, LLVMMetadataRef Allocated, LLVMMetadataRef Rank, LLVMMetadataRef BitStride)
Create debugging information entry for a dynamic array.
Parameters
Builder The DIBuilder.
Size Array size.
AlignInBits Alignment.
Ty Element type.
Subscripts Subscripts.
NumSubscripts Number of subscripts.
DataLocation DataLocation. (DIVariable, DIExpression or NULL)
Associated Associated. (DIVariable, DIExpression or NULL)
Allocated Allocated. (DIVariable, DIExpression or NULL)
Rank Rank. (DIVariable, DIExpression or NULL)
BitStride BitStride.
Definition at line 1377 of file DebugInfo.cpp.
References Size, llvm::unwrap(), unwrapDI(), unwrapExprVar(), and llvm::wrap().
LLVMDIBuilderCreateEnumerationType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateEnumerationType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMMetadataRef * Elements, unsigned NumElements, LLVMMetadataRef ClassTy)
Create debugging information entry for an enumeration.
Parameters
Builder The DIBuilder.
Scope Scope in which this enumeration is defined.
Name Enumeration name.
NameLen Length of enumeration name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Elements Enumeration elements.
NumElements Number of enumeration elements.
ClassTy Underlying type of a C++11/ObjC fixed enum.
Definition at line 1332 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateEnumerator()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateEnumerator (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, int64_t Value, LLVMBool IsUnsigned)
Create debugging information entry for an enumerator.
Parameters
Builder The DIBuilder.
Name Enumerator name.
NameLen Length of enumerator name.
Value Enumerator value.
IsUnsigned True if the value is unsigned.
Definition at line 1315 of file DebugInfo.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateEnumeratorOfArbitraryPrecision()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateEnumeratorOfArbitraryPrecision (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, uint64_t SizeInBits, const uint64_t Words[], LLVMBool IsUnsigned)
Create debugging information entry for an enumerator of arbitrary precision.
Parameters
Builder The DIBuilder.
Name Enumerator name.
NameLen Length of enumerator name.
SizeInBits Number of bits of the value.
Words The words that make up the value.
IsUnsigned True if the value is unsigned.
Definition at line 1323 of file DebugInfo.cpp.
References llvm::ArrayRef(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateExpression()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateExpression (LLVMDIBuilderRef Builder, uint64_t * Addr, size_t Length)
Create a new descriptor for the specified variable which has a complex address expression for its address.
Parameters
Builder The DIBuilder.
Addr An array of complex address operations.
Length Length of the address operation array.
Definition at line 1703 of file DebugInfo.cpp.
References llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateFile()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateFile (LLVMDIBuilderRef Builder, const char * Filename, size_t FilenameLen, const char * Directory, size_t DirectoryLen)
Create a file descriptor to hold debugging information for a file.
Parameters
Builder The DIBuilder.
Filename File name.
FilenameLen The length of the C string passed to Filename.
Directory Directory.
DirectoryLen The length of the C string passed to Directory.
Definition at line 1105 of file DebugInfo.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateFileWithChecksum()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateFileWithChecksum (LLVMDIBuilderRef Builder, const char * Filename, size_t FilenameLen, const char * Directory, size_t DirectoryLen, LLVMChecksumKind ChecksumKind, const char * Checksum, size_t ChecksumLen, const char * Source, size_t SourceLen)
Create a file descriptor to hold debugging information for a file.
Parameters
Builder The DIBuilder.
Filename File name.
FilenameLen The length of the C string passed to Filename.
Directory Directory.
DirectoryLen The length of the C string passed to Directory.
ChecksumKind The kind of checksum. eg MD5, SHA256
Checksum The checksum.
ChecksumLen The length of the checksum.
Souce The embedded source.
SourceLen The length of the source.
Definition at line 1125 of file DebugInfo.cpp.
References map_from_llvmChecksumKind(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateForwardDecl()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateForwardDecl (LLVMDIBuilderRef Builder, unsigned Tag, const char * Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, const char * UniqueIdentifier, size_t UniqueIdentifierLen)
Create a permanent forward-declared type.
Parameters
Builder The DIBuilder.
Tag A unique tag for this type.
Name Type name.
NameLen Length of type name.
Scope Type scope.
File File where this type is defined.
table emission Line number where this type is defined.
RuntimeLang Indicates runtime version for languages like Objective-C.
SizeInBits Member size.
AlignInBits Member alignment.
UniqueIdentifier A unique identifier for the type.
UniqueIdentifierLen Length of the unique identifier.
Definition at line 1556 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateFunction()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateFunction (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, const char * LinkageName, size_t LinkageNameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool IsLocalToUnit, LLVMBool IsDefinition, unsigned ScopeLine, LLVMDIFlags Flags, LLVMBool IsOptimized)
Create a new descriptor for the specified subprogram.
Parameters
Builder The DIBuilder.
Scope Function scope.
Name Function name.
NameLen Length of enumeration name.
LinkageName Mangled function name.
LinkageNameLen Length of linkage name.
File File where this variable is defined.
LineNo Line number.
Ty Function type.
IsLocalToUnit True if this function is not externally visible.
IsDefinition True if this is a function definition.
ScopeLine Set to the beginning of the scope this starts
Flags E.g.: LLVMDIFlagLValueReference. These flags are used to emit dwarf attributes.
IsOptimized True if optimization is ON.
Definition at line 1162 of file DebugInfo.cpp.
References llvm::LinkageName, map_from_llvmDIFlags(), pack_into_DISPFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateGlobalVariableExpression()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateGlobalVariableExpression (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, const char * Linkage, size_t LinkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Expr, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified variable.
Parameters
Scope Variable scope.
Name Name of the variable.
NameLen The length of the C string passed to Name.
Linkage Mangled name of the variable.
LinkLen The length of the C string passed to Linkage.
File File where this variable is defined.
LineNo Line number.
Ty Variable Type.
LocalToUnit Boolean flag indicate whether this variable is externally visible or not.
Expr The location of the global relative to the attached GlobalVariable.
Decl Reference to the corresponding declaration. variables.
AlignInBits Variable alignment(or 0 if no alignment attr was specified)
Definition at line 1715 of file DebugInfo.cpp.
References Linkage, llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateImportedDeclaration()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedDeclaration (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef Decl, LLVMMetadataRef File, unsigned Line, const char * Name, size_t NameLen, LLVMMetadataRef * Elements, unsigned NumElements)
Create a descriptor for an imported function, type, or variable.
Suitable for e.g. FORTRAN-style USE declarations.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into.
Decl The declaration (or definition) of a function, type, or variable.
File File where the declaration is located.
table emission Line number of the declaration.
Name A name that uniquely identifies this imported declaration.
NameLen The length of the C string passed to Name.
Elements Renamed elements.
NumElements Number of renamed elements.
Definition at line 1233 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateImportedModuleFromAlias()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromAlias (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef ImportedEntity, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef * Elements, unsigned NumElements)
Create a descriptor for an imported module that aliases another imported entity descriptor.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into
ImportedEntity Previous imported entity to alias.
File File where the declaration is located.
table emission Line number of the declaration.
Elements Renamed elements.
NumElements Number of renamed elements.
Definition at line 1207 of file DebugInfo.cpp.
References createImportedModule(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateImportedModuleFromModule()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromModule (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef M, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef * Elements, unsigned NumElements)
Create a descriptor for an imported module.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into
M The module being imported here
File File where the declaration is located.
table emission Line number of the declaration.
Elements Renamed elements.
NumElements Number of renamed elements.
Definition at line 1220 of file DebugInfo.cpp.
References createImportedModule(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateImportedModuleFromNamespace()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromNamespace (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef NS, LLVMMetadataRef File, unsigned Line)
Create a descriptor for an imported namespace.
Suitable for e.g. C++ using declarations.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into
File File where the declaration is located.
table emission Line number of the declaration.
Definition at line 1196 of file DebugInfo.cpp.
References createImportedModule(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateInheritance()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateInheritance (LLVMDIBuilderRef Builder, LLVMMetadataRef Ty, LLVMMetadataRef BaseTy, uint64_t BaseOffset, uint32_t VBPtrOffset, LLVMDIFlags Flags)
Create debugging information entry to establish inheritance relationship between two types.
Parameters
Builder The DIBuilder.
Ty Original type.
BaseTy Base type. Ty is inherits from base.
BaseOffset Base offset.
VBPtrOffset Virtual base pointer offset.
Flags Flags to describe inheritance attribute, e.g. private
Definition at line 1546 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateLabel()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateLabel (LLVMDIBuilderRef Builder, LLVMMetadataRef Context, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMBool AlwaysPreserve)
Create a new descriptor for a label.
Parameters
Builder The DIBuilder.
Scope The scope to create the label in.
Name Variable name.
NameLen Length of variable name.
File The file to create the label in.
LineNo Line Number.
AlwaysPreserve Preserve the label regardless of optimization.
See also
llvm::DIBuilder::createLabel()
Definition at line 1906 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateLexicalBlock()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateLexicalBlock (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned Column)
Create a descriptor for a lexical block with the specified parent context.
Parameters
Builder The DIBuilder.
Scope Parent lexical block.
File Source file.
table emission The line in the source file.
Column The column in the source file.
Definition at line 1177 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateLexicalBlockFile()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateLexicalBlockFile (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Discriminator)
Create a descriptor for a lexical block with a new file attached.
Parameters
Builder The DIBuilder.
Scope Lexical block.
File Source file.
Discriminator DWARF path discriminator value.
Definition at line 1186 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateMacro()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateMacro (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMDWARFMacinfoRecordType RecordType, const char * Name, size_t NameLen, const char * Value, size_t ValueLen)
Create debugging information entry for a macro.
Parameters
Builder The DIBuilder.
ParentMacroFile Macro parent (could be NULL).
table emission Source line number where the macro is defined.
RecordType DW_MACINFO_define or DW_MACINFO_undef.
Name Macro name.
NameLen Macro name length.
Value Macro value.
ValueLen Macro value length.
Definition at line 1295 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateMemberPointerType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateMemberPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeType, LLVMMetadataRef ClassType, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags)
Create debugging information entry for a pointer to member.
Parameters
Builder The DIBuilder.
PointeeType Type pointed to by this pointer.
ClassType Type for which this pointer points to members of.
SizeInBits Size.
AlignInBits Alignment.
Flags Flags.
Definition at line 1601 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateMemberType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty)
Create debugging information entry for a member.
Parameters
Builder The DIBuilder.
Scope Member scope.
Name Member name.
NameLen Length of member name.
File File where this member is defined.
LineNo Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private
Ty Parent type.
Definition at line 1473 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateModule()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateModule (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char * Name, size_t NameLen, const char * ConfigMacros, size_t ConfigMacrosLen, const char * IncludePath, size_t IncludePathLen, const char * APINotesFile, size_t APINotesFileLen)
Creates a new descriptor for a module with the specified parent scope.
Parameters
Builder The DIBuilder.
ParentScope The parent scope containing this module declaration.
Name Module name.
NameLen The length of the C string passed to Name.
ConfigMacros A space-separated shell-quoted list of -D macro definitions as they would appear on a command line.
ConfigMacrosLen The length of the C string passed to ConfigMacros.
IncludePath The path to the module map file.
IncludePathLen The length of the C string passed to IncludePath.
APINotesFile The path to an API notes file for the module.
APINotesFileLen The length of the C string passed to APINotestFile.
Definition at line 1142 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateNameSpace()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateNameSpace (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char * Name, size_t NameLen, LLVMBool ExportSymbols)
Creates a new descriptor for a namespace with the specified parent scope.
Parameters
Builder The DIBuilder.
ParentScope The parent scope containing this module declaration.
Name NameSpace name.
NameLen The length of the C string passed to Name.
ExportSymbols Whether or not the namespace exports symbols, e.g. this is true of C++ inline namespaces.
Definition at line 1154 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateNullPtrType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateNullPtrType (LLVMDIBuilderRef Builder)
Create C++11 nullptr type.
Parameters
Builder The DIBuilder.
Definition at line 1596 of file DebugInfo.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateObjCIVar()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateObjCIVar (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty, LLVMMetadataRef PropertyNode)
Create debugging information entry for Objective-C instance variable.
Parameters
Builder The DIBuilder.
Name Member name.
NameLen The length of the C string passed to Name.
File File where this member is defined.
LineNo Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private
Ty Parent type.
PropertyNode Property associated with this ivar.
Definition at line 1501 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateObjCProperty()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateObjCProperty (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, const char * GetterName, size_t GetterNameLen, const char * SetterName, size_t SetterNameLen, unsigned PropertyAttributes, LLVMMetadataRef Ty)
Create debugging information entry for Objective-C property.
Parameters
Builder The DIBuilder.
Name Property name.
NameLen The length of the C string passed to Name.
File File where this property is defined.
LineNo Line number.
GetterName Name of the Objective C property getter selector.
GetterNameLen The length of the C string passed to GetterName.
SetterName Name of the Objective C property setter selector.
SetterNameLen The length of the C string passed to SetterName.
PropertyAttributes Objective C property attributes.
Ty Type.
Definition at line 1515 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateObjectPointerType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateObjectPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type, LLVMBool Implicit)
Create a uniqued DIType* clone with FlagObjectPointer.
If Implicit is true, then also set FlagArtificial.
Parameters
Builder The DIBuilder.
Type The underlying type to which this pointer points.
Implicit Indicates whether this pointer was implicitly generated (i.e., not spelled out in source).
Definition at line 1528 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateParameterVariable()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateParameterVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, unsigned ArgNo, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags)
Create a new descriptor for a function parameter variable.
Parameters
Builder The DIBuilder.
Scope The local scope the variable is declared in.
Name Variable name.
NameLen Length of variable name.
ArgNo Unique argument number for this variable; starts at 1.
File File where this variable is defined.
LineNo Line number.
Ty Metadata describing the type of the variable.
AlwaysPreserve If true, this descriptor will survive optimizations.
Flags Flags.
Definition at line 1855 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreatePointerType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreatePointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeTy, uint64_t SizeInBits, uint32_t AlignInBits, unsigned AddressSpace, const char * Name, size_t NameLen)
Create debugging information entry for a pointer.
Parameters
Builder The DIBuilder.
PointeeTy Type pointed by this pointer.
SizeInBits Size.
AlignInBits Alignment. (optional, pass 0 to ignore)
AddressSpace DWARF address space. (optional, pass 0 to ignore)
Name Pointer type name. (optional)
NameLen Length of pointer type name. (optional)
Definition at line 1448 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateQualifiedType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateQualifiedType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a qualified type, e.g.
'const int'.
Parameters
Builder The DIBuilder.
Tag Tag identifying type, e.g. LLVMDWARFTypeQualifier_volatile_type
Type Base Type.
Definition at line 1582 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateReferenceType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateReferenceType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a c++ style reference or rvalue reference type.
Parameters
Builder The DIBuilder.
Tag Tag identifying type,
Type Base Type.
Definition at line 1589 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateReplaceableCompositeType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateReplaceableCompositeType (LLVMDIBuilderRef Builder, unsigned Tag, const char * Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, const char * UniqueIdentifier, size_t UniqueIdentifierLen)
Create a temporary forward-declared type.
Parameters
Builder The DIBuilder.
Tag A unique tag for this type.
Name Type name.
NameLen Length of type name.
Scope Type scope.
File File where this type is defined.
table emission Line number where this type is defined.
RuntimeLang Indicates runtime version for languages like Objective-C.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags.
UniqueIdentifier A unique identifier for the type.
UniqueIdentifierLen Length of the unique identifier.
Definition at line 1568 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateSetType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateSetType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMMetadataRef BaseTy)
Create debugging information entry for a set.
Parameters
Builder The DIBuilder.
Scope The scope in which the set is defined.
Name A name that uniquely identifies this set.
NameLen The length of the C string passed to Name.
File File where the set is located.
table emission Line number of the declaration.
SizeInBits Set size.
AlignInBits Set alignment.
BaseTy The base type of the set.
Definition at line 1344 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateStaticMemberType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateStaticMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, LLVMMetadataRef Type, LLVMDIFlags Flags, LLVMValueRef ConstantVal, uint32_t AlignInBits)
Create debugging information entry for a C++ static data member.
Parameters
Builder The DIBuilder.
Scope Member scope.
Name Member name.
NameLen Length of member name.
File File where this member is declared.
LineNumber Line number.
Type Type of the static member.
Flags Flags to encode member attribute, e.g. private.
ConstantVal Const initializer of the member.
AlignInBits Member alignment.
Definition at line 1489 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateStructType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateStructType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef * Elements, unsigned NumElements, unsigned RunTimeLang, LLVMMetadataRef VTableHolder, const char * UniqueId, size_t UniqueIdLen)
Create debugging information entry for a struct.
Parameters
Builder The DIBuilder.
Scope Scope in which this struct is defined.
Name Struct name.
NameLen Struct name length.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags to encode member attribute, e.g. private
Elements Struct elements.
NumElements Number of struct elements.
RunTimeLang Optional parameter, Objective-C runtime version.
VTableHolder The object containing the vtable for the struct.
UniqueId A unique identifier for the struct.
UniqueIdLen Length of the unique identifier for the struct.
Definition at line 1457 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateSubrangeType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateSubrangeType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, unsigned LineNo, LLVMMetadataRef File, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef BaseTy, LLVMMetadataRef LowerBound, LLVMMetadataRef UpperBound, LLVMMetadataRef Stride, LLVMMetadataRef Bias)
Create a descriptor for a subrange with dynamic bounds.
Parameters
Builder The DIBuilder.
Scope The scope in which the subrange is defined.
Name A name that uniquely identifies this subrange.
NameLen The length of the C string passed to Name.
LineNo Line number.
File File where the subrange is located.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags.
BaseTy The base type of the subrange. eg integer or enumeration
LowerBound Lower bound of the subrange.
UpperBound Upper bound of the subrange.
Stride Stride of the subrange.
Bias Bias of the subrange.
Definition at line 1353 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateSubroutineType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateSubroutineType (LLVMDIBuilderRef Builder, LLVMMetadataRef File, LLVMMetadataRef * ParameterTypes, unsigned NumParameterTypes, LLVMDIFlags Flags)
Create subroutine type.
Parameters
Builder The DIBuilder.
File The file in which the subroutine resides.
ParameterTypes An array of subroutine parameter types. This includes return type at 0th index.
NumParameterTypes The number of parameter types in ParameterTypes
Flags E.g.: LLVMDIFlagLValueReference. These flags are used to emit dwarf attributes.
Definition at line 1692 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateTempGlobalVariableFwdDecl()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateTempGlobalVariableFwdDecl (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, const char * Linkage, size_t LnkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified global variable that is temporary and meant to be RAUWed.
Parameters
Scope Variable scope.
Name Name of the variable.
NameLen The length of the C string passed to Name.
Linkage Mangled name of the variable.
LnkLen The length of the C string passed to Linkage.
File File where this variable is defined.
LineNo Line number.
Ty Variable Type.
LocalToUnit Boolean flag indicate whether this variable is externally visible or not.
Decl Reference to the corresponding declaration.
AlignInBits Variable alignment(or 0 if no alignment attr was specified)
Definition at line 1765 of file DebugInfo.cpp.
References Linkage, llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateTempMacroFile()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateTempMacroFile (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMMetadataRef File)
Create debugging information temporary entry for a macro file.
List of macro node direct children will be calculated by DIBuilder, using the ParentMacroFile relationship.
Parameters
Builder The DIBuilder.
ParentMacroFile Macro parent (could be NULL).
table emission Source line number where the macro file is included.
File File descriptor containing the name of the macro file.
Definition at line 1308 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateTypedef()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateTypedef (LLVMDIBuilderRef Builder, LLVMMetadataRef Type, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Scope, uint32_t AlignInBits)
Create debugging information entry for a typedef.
Parameters
Builder The DIBuilder.
Type Original type.
Name Typedef name.
File File where this type is defined.
LineNo Line number.
Scope The surrounding context for the typedef.
Definition at line 1536 of file DebugInfo.cpp.
References llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateUnionType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateUnionType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef * Elements, unsigned NumElements, unsigned RunTimeLang, const char * UniqueId, size_t UniqueIdLen)
Create debugging information entry for a union.
Parameters
Builder The DIBuilder.
Scope Scope in which this union is defined.
Name Union name.
NameLen Length of union name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags to encode member attribute, e.g. private
Elements Union elements.
NumElements Number of union elements.
RunTimeLang Optional parameter, Objective-C runtime version.
UniqueId A unique identifier for the union.
UniqueIdLen Length of unique identifier.
Definition at line 1401 of file DebugInfo.cpp.
References map_from_llvmDIFlags(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderCreateUnspecifiedType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateUnspecifiedType (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen)
Create a DWARF unspecified type.
Parameters
Builder The DIBuilder.
Name The unspecified type's name.
NameLen Length of type name.
Definition at line 1484 of file DebugInfo.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateVectorType()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderCreateVectorType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef * Subscripts, unsigned NumSubscripts)
Create debugging information entry for a vector type.
Parameters
Builder The DIBuilder.
Size Vector size.
AlignInBits Alignment.
Ty Element type.
Subscripts Subscripts.
NumSubscripts Number of subscripts.
Definition at line 1428 of file DebugInfo.cpp.
References Size, llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderFinalize()
LLVM_C_ABI void LLVMDIBuilderFinalize (LLVMDIBuilderRef Builder)
Construct any deferred debug info descriptors.
Definition at line 1075 of file DebugInfo.cpp.
References llvm::unwrap().
LLVMDIBuilderFinalizeSubprogram()
LLVM_C_ABI void LLVMDIBuilderFinalizeSubprogram (LLVMDIBuilderRef Builder, LLVMMetadataRef Subprogram)
Finalize a specific subprogram.
No new variables may be added to this subprogram afterwards.
Definition at line 1079 of file DebugInfo.cpp.
References llvm::unwrap(), and unwrapDI().
LLVMDIBuilderGetOrCreateArray()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderGetOrCreateArray (LLVMDIBuilderRef Builder, LLVMMetadataRef * Data, size_t NumElements)
Create an array of DI Nodes.
Parameters
Builder The DIBuilder.
Members accessed asinchronously. The DI Node elements.
NumElements Number of DI Node elements.
Definition at line 1870 of file DebugInfo.cpp.
References llvm::Data, llvm::Attribute::get(), llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderGetOrCreateSubrange()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderGetOrCreateSubrange (LLVMDIBuilderRef Builder, int64_t LowerBound, int64_t Count)
Create a descriptor for a value range.
Parameters
Builder The DIBuilder.
LowerBound Lower bound of the subrange, e.g. 0 for C, 1 for Fortran.
Count Count of elements in the subrange.
Definition at line 1865 of file DebugInfo.cpp.
References llvm::Count, llvm::Lo, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderGetOrCreateTypeArray()
LLVM_C_ABI LLVMMetadataRef LLVMDIBuilderGetOrCreateTypeArray (LLVMDIBuilderRef Builder, LLVMMetadataRef * Data, size_t NumElements)
Create a type array.
Parameters
Builder The DIBuilder.
Members accessed asinchronously. The type elements.
NumElements Number of type elements.
Definition at line 1684 of file DebugInfo.cpp.
References llvm::Attribute::get(), llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDbgValueRecordAtEnd()
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDbgValueRecordAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
The debug format can be switched later after inserting the records using LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
Insert a new debug record at the end of the given basic block. If the basic block has a terminator instruction, the record is inserted before that terminator instruction.
Parameters
Builder The DIBuilder.
Val The value of the variable.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Block Basic block acting as a location for the new record.
Definition at line 1828 of file DebugInfo.cpp.
References assert(), llvm::Block, llvm::cast(), llvm::end(), llvm::isa(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDbgValueRecordBefore()
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDbgValueRecordBefore (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
The debug format can be switched later after inserting the records using LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
Insert a new debug record before the given instruction.
Parameters
Builder The DIBuilder.
Val The value of the variable.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Instr Instruction acting as a location for the new record.
Definition at line 1810 of file DebugInfo.cpp.
References assert(), llvm::cast(), llvm::isa(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDeclareRecordAtEnd()
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDeclareRecordAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
The debug format can be switched later after inserting the records using LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
Insert a Declare DbgRecord at the end of the given basic block. If the basic block has a terminator instruction, the record is inserted before that terminator instruction.
Parameters
Builder The DIBuilder.
Storage The storage of the variable to declare.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Block Basic block acting as a location for the new record.
Definition at line 1794 of file DebugInfo.cpp.
References assert(), llvm::Block, llvm::cast(), DL, llvm::isa(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDeclareRecordBefore()
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertDeclareRecordBefore (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
The debug format can be switched later after inserting the records using LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
Insert a Declare DbgRecord before the given instruction.
Parameters
Builder The DIBuilder.
Storage The storage of the variable to declare.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Instr Instruction acting as a location for the new record.
Definition at line 1776 of file DebugInfo.cpp.
References assert(), llvm::cast(), DL, llvm::isa(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertLabelAtEnd()
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertLabelAtEnd (LLVMDIBuilderRef Builder, LLVMMetadataRef LabelInfo, LLVMMetadataRef Location, LLVMBasicBlockRef InsertAtEnd)
Insert a new llvm.dbg.label intrinsic call.
Parameters
Builder The DIBuilder.
LabelInfo The Label's debug info descriptor
Location The debug info location
InsertAtEnd Location for the new intrinsic.
See also
llvm::DIBuilder::insertLabel()
Definition at line 1936 of file DebugInfo.cpp.
References assert(), llvm::cast(), llvm::end(), llvm::isa(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIBuilderInsertLabelBefore()
LLVM_C_ABI LLVMDbgRecordRef LLVMDIBuilderInsertLabelBefore (LLVMDIBuilderRef Builder, LLVMMetadataRef LabelInfo, LLVMMetadataRef Location, LLVMValueRef InsertBefore)
Insert a new llvm.dbg.label intrinsic call.
Parameters
Builder The DIBuilder.
LabelInfo The Label's debug info descriptor
Location The debug info location
InsertBefore Location for the new intrinsic.
See also
llvm::DIBuilder::insertLabel()
Definition at line 1917 of file DebugInfo.cpp.
References assert(), llvm::cast(), llvm::isa(), llvm::unwrap(), unwrapDI(), and llvm::wrap().
LLVMDIFileGetDirectory()
LLVM_C_ABI const char * LLVMDIFileGetDirectory (LLVMMetadataRef File, unsigned * Len)
Get the directory of a given file.
Parameters
File The file object.
Len The length of the returned string.
See also
DIFile::getDirectory()
Definition at line 1274 of file DebugInfo.cpp.
References unwrapDI().
LLVMDIFileGetFilename()
LLVM_C_ABI const char * LLVMDIFileGetFilename (LLVMMetadataRef File, unsigned * Len)
Get the name of a given file.
Parameters
File The file object.
Len The length of the returned string.
See also
DIFile::getFilename()
Definition at line 1280 of file DebugInfo.cpp.
References unwrapDI().
LLVMDIFileGetSource()
LLVM_C_ABI const char * LLVMDIFileGetSource (LLVMMetadataRef File, unsigned * Len)
Get the source of a given file.
Parameters
File The file object.
Len The length of the returned string.
See also
DIFile::getSource()
Definition at line 1286 of file DebugInfo.cpp.
References unwrapDI().
LLVMDIGlobalVariableExpressionGetExpression()
LLVM_C_ABI LLVMMetadataRef LLVMDIGlobalVariableExpressionGetExpression (LLVMMetadataRef GVE)
Retrieves the DIExpression associated with this global variable expression.
Parameters
GVE The global variable expression.
See also
llvm::DIGlobalVariableExpression::getExpression()
Definition at line 1731 of file DebugInfo.cpp.
References unwrapDI(), and llvm::wrap().
LLVMDIGlobalVariableExpressionGetVariable()
LLVM_C_ABI LLVMMetadataRef LLVMDIGlobalVariableExpressionGetVariable (LLVMMetadataRef GVE)
Retrieves the DIVariable associated with this global variable expression.
Parameters
GVE The global variable expression.
See also
llvm::DIGlobalVariableExpression::getVariable()
Definition at line 1727 of file DebugInfo.cpp.
References unwrapDI(), and llvm::wrap().
LLVMDILocationGetColumn()
LLVM_C_ABI unsigned LLVMDILocationGetColumn (LLVMMetadataRef Location)
Get the column number of this debug location.
Parameters
Location The debug location.
See also
DILocation::getColumn()
Definition at line 1258 of file DebugInfo.cpp.
References unwrapDI().
LLVMDILocationGetInlinedAt()
LLVM_C_ABI LLVMMetadataRef LLVMDILocationGetInlinedAt (LLVMMetadataRef Location)
Get the "inline at" location associated with this debug location.
Parameters
Location The debug location.
See also
DILocation::getInlinedAt()
Definition at line 1266 of file DebugInfo.cpp.
References unwrapDI(), and llvm::wrap().
LLVMDILocationGetLine()
LLVM_C_ABI unsigned LLVMDILocationGetLine (LLVMMetadataRef Location)
Get the line number of this debug location.
Parameters
Location The debug location.
See also
DILocation::getLine()
Definition at line 1254 of file DebugInfo.cpp.
References unwrapDI().
LLVMDILocationGetScope()
LLVM_C_ABI LLVMMetadataRef LLVMDILocationGetScope (LLVMMetadataRef Location)
Get the local scope associated with this debug location.
Parameters
Location The debug location.
See also
DILocation::getScope()
Definition at line 1262 of file DebugInfo.cpp.
References unwrapDI(), and llvm::wrap().
LLVMDIScopeGetFile()
LLVM_C_ABI LLVMMetadataRef LLVMDIScopeGetFile (LLVMMetadataRef Scope)
Get the metadata of the file associated with a given scope.
Parameters
Scope The scope object.
See also
DIScope::getFile()
Definition at line 1270 of file DebugInfo.cpp.
References unwrapDI(), and llvm::wrap().
LLVMDisposeDIBuilder()
LLVM_C_ABI void LLVMDisposeDIBuilder (LLVMDIBuilderRef Builder)
Deallocates the DIBuilder and everything it owns.
Note
You must call LLVMDIBuilderFinalize before this
Definition at line 1071 of file DebugInfo.cpp.
References llvm::unwrap().
LLVMDisposeTemporaryMDNode()
LLVM_C_ABI void LLVMDisposeTemporaryMDNode (LLVMMetadataRef TempNode)
Deallocate a temporary node.
Calls replaceAllUsesWith(nullptr) before deleting, so any remaining references will be reset.
Parameters
TempNode The temporary metadata node.
Definition at line 1754 of file DebugInfo.cpp.
References llvm::MDNode::deleteTemporary(), and unwrapDI().
LLVMDISubprogramGetLine()
LLVM_C_ABI unsigned LLVMDISubprogramGetLine (LLVMMetadataRef Subprogram)
Get the line associated with a given subprogram.
Parameters
Subprogram The subprogram object.
See also
DISubprogram::getLine()
Definition at line 1885 of file DebugInfo.cpp.
References unwrapDI().
LLVMDISubprogramReplaceType()
LLVM_C_ABI void LLVMDISubprogramReplaceType (LLVMMetadataRef Subprogram, LLVMMetadataRef SubroutineType)
Replace the subprogram subroutine type.
Parameters
Subprogram The subprogram object.
SubroutineType The new subroutine type.
See also
DISubprogram::replaceType()
Definition at line 1889 of file DebugInfo.cpp.
References unwrapDI().
LLVMDITypeGetAlignInBits()
LLVM_C_ABI uint32_t LLVMDITypeGetAlignInBits (LLVMMetadataRef DType)
Get the alignment of this DIType in bits.
Parameters
DType The DIType.
See also
DIType::getAlignInBits()
Definition at line 1672 of file DebugInfo.cpp.
References unwrapDI().
LLVMDITypeGetFlags()
LLVM_C_ABI LLVMDIFlags LLVMDITypeGetFlags (LLVMMetadataRef DType)
Get the flags associated with this DIType.
Parameters
DType The DIType.
See also
DIType::getFlags()
Definition at line 1680 of file DebugInfo.cpp.
References getFlags(), map_to_llvmDIFlags(), and unwrapDI().
LLVMDITypeGetLine()
LLVM_C_ABI unsigned LLVMDITypeGetLine (LLVMMetadataRef DType)
Get the source line where this DIType is declared.
Parameters
DType The DIType.
See also
DIType::getLine()
Definition at line 1676 of file DebugInfo.cpp.
References unwrapDI().
LLVMDITypeGetName()
LLVM_C_ABI const char * LLVMDITypeGetName (LLVMMetadataRef DType, size_t * Length)
Get the name of this DIType.
Parameters
DType The DIType.
Length The length of the returned string.
See also
DIType::getName()
Definition at line 1658 of file DebugInfo.cpp.
References llvm::Length, and unwrapDI().
LLVMDITypeGetOffsetInBits()
LLVM_C_ABI uint64_t LLVMDITypeGetOffsetInBits (LLVMMetadataRef DType)
Get the offset of this DIType in bits.
Parameters
DType The DIType.
See also
DIType::getOffsetInBits()
Definition at line 1668 of file DebugInfo.cpp.
References unwrapDI().
LLVMDITypeGetSizeInBits()
LLVM_C_ABI uint64_t LLVMDITypeGetSizeInBits (LLVMMetadataRef DType)
Get the size of this DIType in bits.
Parameters
DType The DIType.
See also
DIType::getSizeInBits()
Definition at line 1664 of file DebugInfo.cpp.
References unwrapDI().
LLVMDIVariableGetFile()
LLVM_C_ABI LLVMMetadataRef LLVMDIVariableGetFile (LLVMMetadataRef Var)
Get the metadata of the file associated with a given variable.
Parameters
Var The variable object.
See also
DIVariable::getFile()
Definition at line 1736 of file DebugInfo.cpp.
References unwrapDI(), and llvm::wrap().
LLVMDIVariableGetLine()
LLVM_C_ABI unsigned LLVMDIVariableGetLine (LLVMMetadataRef Var)
Get the source line where this DIVariable is declared.
Parameters
Var The DIVariable.
See also
DIVariable::getLine()
Definition at line 1744 of file DebugInfo.cpp.
References unwrapDI().
LLVMDIVariableGetScope()
LLVM_C_ABI LLVMMetadataRef LLVMDIVariableGetScope (LLVMMetadataRef Var)
Get the metadata of the scope associated with a given variable.
Parameters
Var The variable object.
See also
DIVariable::getScope()
Definition at line 1740 of file DebugInfo.cpp.
References unwrapDI(), and llvm::wrap().
LLVMGetDINodeTag()
LLVM_C_ABI uint16_t LLVMGetDINodeTag (LLVMMetadataRef MD)
Get the dwarf::Tag of a DINode.
Definition at line 1654 of file DebugInfo.cpp.
References unwrapDI().
LLVMGetMetadataKind()
LLVM_C_ABI LLVMMetadataKind LLVMGetMetadataKind (LLVMMetadataRef Metadata)
Obtain the enumerated type of a Metadata instance.
See also
llvm::Metadata::getMetadataID()
Definition at line 1953 of file DebugInfo.cpp.
References LLVMGenericDINodeMetadataKind, and llvm::unwrap().
LLVMGetModuleDebugMetadataVersion()
LLVM_C_ABI unsigned LLVMGetModuleDebugMetadataVersion (LLVMModuleRef Module)
The version of debug metadata that's present in the provided Module.
Definition at line 1063 of file DebugInfo.cpp.
References llvm::getDebugMetadataVersionFromModule(), and llvm::unwrap().
LLVMGetSubprogram()
LLVM_C_ABI LLVMMetadataRef LLVMGetSubprogram (LLVMValueRef Func)
Get the metadata of the subprogram attached to a function.
See also
llvm::Function::getSubprogram()
Definition at line 1877 of file DebugInfo.cpp.
References getSubprogram(), llvm::unwrap(), and llvm::wrap().
LLVMInstructionGetDebugLoc()
LLVM_C_ABI LLVMMetadataRef LLVMInstructionGetDebugLoc (LLVMValueRef Inst)
Get the debug location for the given instruction.
See also
llvm::Instruction::getDebugLoc()
Definition at line 1895 of file DebugInfo.cpp.
References getDebugLoc(), llvm::unwrap(), and llvm::wrap().
LLVMInstructionSetDebugLoc()
LLVM_C_ABI void LLVMInstructionSetDebugLoc (LLVMValueRef Inst, LLVMMetadataRef Loc)
Set the debug location for the given instruction.
To clear the location metadata of the given instruction, pass NULL to Loc.
See also
llvm::Instruction::setDebugLoc()
Definition at line 1899 of file DebugInfo.cpp.
References llvm::dwarf_linker::DebugLoc, and llvm::unwrap().
LLVMMetadataReplaceAllUsesWith()
LLVM_C_ABI void LLVMMetadataReplaceAllUsesWith (LLVMMetadataRef TempTargetMetadata, LLVMMetadataRef Replacement)
Replace all uses of temporary metadata.
Parameters
TempTargetMetadata The temporary metadata node.
Replacement The replacement metadata node.
Definition at line 1758 of file DebugInfo.cpp.
References llvm::MDNode::deleteTemporary(), llvm::unwrap(), and unwrapDI().
LLVMReplaceArrays()
LLVM_C_ABI void LLVMReplaceArrays (LLVMDIBuilderRef Builder, LLVMMetadataRef * T, LLVMMetadataRef * Elements, unsigned NumElements)
Replace arrays.
See also
DIBuilder::replaceArrays()
Definition at line 1393 of file DebugInfo.cpp.
References T, and llvm::unwrap().
LLVMSetSubprogram()
LLVM_C_ABI void LLVMSetSubprogram (LLVMValueRef Func, LLVMMetadataRef SP)
Set the subprogram attached to a function.
See also
llvm::Function::setSubprogram()
Definition at line 1881 of file DebugInfo.cpp.
References llvm::unwrap().
LLVMStripModuleDebugInfo()
LLVM_C_ABI LLVMBool LLVMStripModuleDebugInfo (LLVMModuleRef Module)
Strip debug info in the module if it exists.
To do this, we remove all calls to the debugger intrinsics and any named metadata for debugging. We also remove debug locations for instructions. Return true if module is modified.
Definition at line 1067 of file DebugInfo.cpp.
References llvm::StripDebugInfo(), and llvm::unwrap().
LLVMTemporaryMDNode()
LLVM_C_ABI LLVMMetadataRef LLVMTemporaryMDNode (LLVMContextRef Ctx, LLVMMetadataRef * Data, size_t NumElements)
Create a new temporary MDNode.
Suitable for use in constructing cyclic MDNode structures. A temporary MDNode is not uniqued, may be RAUW'd, and must be manually deleted with LLVMDisposeTemporaryMDNode.
Parameters
Ctx The context in which to construct the temporary node.
Members accessed asinchronously. The metadata elements.
NumElements Number of metadata elements.
Definition at line 1748 of file DebugInfo.cpp.
References llvm::Count, llvm::Data, llvm::MDTuple::getTemporary(), llvm::unwrap(), and llvm::wrap().