LLVM: Global Aliases
Global Aliases
LLVM-C: C interface to LLVM » Core » Values » Constants
This group contains function that operate on global alias values.
Functions
LLVM_C_ABI LLVMValueRef LLVMAddAlias2 (LLVMModuleRef M, LLVMTypeRef ValueTy, unsigned AddrSpace, LLVMValueRef Aliasee, const char *Name)
Add a GlobalAlias with the given value type, address space and aliasee.
LLVM_C_ABI LLVMValueRef LLVMGetNamedGlobalAlias (LLVMModuleRef M, const char *Name, size_t NameLen)
Obtain a GlobalAlias value from a Module by its name.
LLVM_C_ABI LLVMValueRef LLVMGetFirstGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the first GlobalAlias in a Module.
LLVM_C_ABI LLVMValueRef LLVMGetLastGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the last GlobalAlias in a Module.
LLVM_C_ABI LLVMValueRef LLVMGetNextGlobalAlias (LLVMValueRef GA)
Advance a GlobalAlias iterator to the next GlobalAlias.
LLVM_C_ABI LLVMValueRef LLVMGetPreviousGlobalAlias (LLVMValueRef GA)
Decrement a GlobalAlias iterator to the previous GlobalAlias.
LLVM_C_ABI LLVMValueRef LLVMAliasGetAliasee (LLVMValueRef Alias)
Retrieve the target value of an alias.
LLVM_C_ABI void LLVMAliasSetAliasee (LLVMValueRef Alias, LLVMValueRef Aliasee)
Set the target value of an alias.
Detailed Description
This group contains function that operate on global alias values.
See also
llvm::GlobalAlias
Function Documentation
LLVMAddAlias2()
LLVM_C_ABI LLVMValueRef LLVMAddAlias2 (LLVMModuleRef M, LLVMTypeRef ValueTy, unsigned AddrSpace, LLVMValueRef Aliasee, const char * Name)
Add a GlobalAlias with the given value type, address space and aliasee.
See also
llvm::GlobalAlias::create()
Definition at line 2359 of file Core.cpp.
References llvm::GlobalAlias::create(), llvm::GlobalValue::ExternalLinkage, llvm::unwrap(), and llvm::wrap().
LLVMAliasGetAliasee()
LLVM_C_ABI LLVMValueRef LLVMAliasGetAliasee (LLVMValueRef Alias)
Retrieve the target value of an alias.
Definition at line 2404 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMAliasSetAliasee()
LLVM_C_ABI void LLVMAliasSetAliasee (LLVMValueRef Alias, LLVMValueRef Aliasee)
Set the target value of an alias.
Definition at line 2408 of file Core.cpp.
References llvm::unwrap().
LLVMGetFirstGlobalAlias()
LLVM_C_ABI LLVMValueRef LLVMGetFirstGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the first GlobalAlias in a Module.
See also
llvm::Module::alias_begin()
Definition at line 2372 of file Core.cpp.
References I, Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastGlobalAlias()
LLVM_C_ABI LLVMValueRef LLVMGetLastGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the last GlobalAlias in a Module.
See also
llvm::Module::alias_end()
Definition at line 2380 of file Core.cpp.
References I, Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobalAlias()
LLVM_C_ABI LLVMValueRef LLVMGetNamedGlobalAlias (LLVMModuleRef M, const char * Name, size_t NameLen)
Obtain a GlobalAlias value from a Module by its name.
The returned value corresponds to a llvm::GlobalAlias value.
See also
llvm::Module::getNamedAlias()
Definition at line 2367 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetNextGlobalAlias()
LLVM_C_ABI LLVMValueRef LLVMGetNextGlobalAlias (LLVMValueRef GA)
Advance a GlobalAlias iterator to the next GlobalAlias.
Returns NULL if the iterator was already at the end and there are no more global aliases.
Definition at line 2388 of file Core.cpp.
References llvm::Module::alias_end(), llvm::GlobalValue::getParent(), I, llvm::unwrap(), and llvm::wrap().
LLVMGetPreviousGlobalAlias()
LLVM_C_ABI LLVMValueRef LLVMGetPreviousGlobalAlias (LLVMValueRef GA)
Decrement a GlobalAlias iterator to the previous GlobalAlias.
Returns NULL if the iterator was already at the beginning and there are no previous global aliases.
Definition at line 2396 of file Core.cpp.
References llvm::Module::alias_begin(), llvm::GlobalValue::getParent(), I, llvm::unwrap(), and llvm::wrap().