LLVM: User value
User value
LLVM-C: C interface to LLVM » Core » Values
Function in this group pertain to LLVMValueRef instances that descent from llvm::User.
Functions
LLVM_C_ABI LLVMValueRef LLVMGetOperand (LLVMValueRef Val, unsigned Index)
Obtain an operand at a specific index in a llvm::User value.
LLVM_C_ABI LLVMUseRef LLVMGetOperandUse (LLVMValueRef Val, unsigned Index)
Obtain the use of an operand at a specific index in a llvm::User value.
LLVM_C_ABI void LLVMSetOperand (LLVMValueRef User, unsigned Index, LLVMValueRef Val)
Set an operand at a specific index in a llvm::User value.
LLVM_C_ABI int LLVMGetNumOperands (LLVMValueRef Val)
Obtain the number of operands in a llvm::User value.
Detailed Description
Function in this group pertain to LLVMValueRef instances that descent from llvm::User.
This includes constants, instructions, and operators.
Function Documentation
LLVMGetNumOperands()
LLVM_C_ABI int LLVMGetNumOperands (LLVMValueRef Val)
Obtain the number of operands in a llvm::User value.
See also
llvm::User::getNumOperands()
Definition at line 1235 of file Core.cpp.
References llvm::cast(), llvm::isa(), LLVMGetMDNodeNumOperands(), and llvm::unwrap().
LLVMGetOperand()
LLVM_C_ABI LLVMValueRef LLVMGetOperand (LLVMValueRef Val, unsigned Index)
Obtain an operand at a specific index in a llvm::User value.
See also
llvm::User::getOperand()
Definition at line 1212 of file Core.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), getMDNodeOperandImpl(), llvm::unwrap(), and llvm::wrap().
LLVMGetOperandUse()
LLVM_C_ABI LLVMUseRef LLVMGetOperandUse (LLVMValueRef Val, unsigned Index)
Obtain the use of an operand at a specific index in a llvm::User value.
See also
llvm::User::getOperandUse()
Definition at line 1226 of file Core.cpp.
References llvm::cast(), llvm::unwrap(), and llvm::wrap().
LLVMSetOperand()
LLVM_C_ABI void LLVMSetOperand (LLVMValueRef User, unsigned Index, LLVMValueRef Val)
Set an operand at a specific index in a llvm::User value.
See also
llvm::User::setOperand()
Definition at line 1231 of file Core.cpp.
References llvm::unwrap().