LLVM: Floating Point Types
Floating Point Types
LLVM-C: C interface to LLVM » Core » Types
Functions
LLVM_C_ABI LLVMTypeRef LLVMHalfTypeInContext (LLVMContextRef C)
Obtain a 16-bit floating point type from a context.
LLVM_C_ABI LLVMTypeRef LLVMBFloatTypeInContext (LLVMContextRef C)
Obtain a 16-bit brain floating point type from a context.
LLVM_C_ABI LLVMTypeRef LLVMFloatTypeInContext (LLVMContextRef C)
Obtain a 32-bit floating point type from a context.
LLVM_C_ABI LLVMTypeRef LLVMDoubleTypeInContext (LLVMContextRef C)
Obtain a 64-bit floating point type from a context.
LLVM_C_ABI LLVMTypeRef LLVMX86FP80TypeInContext (LLVMContextRef C)
Obtain a 80-bit floating point type (X87) from a context.
LLVM_C_ABI LLVMTypeRef LLVMFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (112-bit mantissa) from a context.
LLVM_C_ABI LLVMTypeRef LLVMPPCFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (two 64-bits) from a context.
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMHalfType(void), "Use of the global context is deprecated, use " "LLVMHalfTypeInContext instead")
Obtain a floating point type from the global context.
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMBFloatType(void), "Use of the global context is deprecated, use " "LLVMBFloatTypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMFloatType(void), "Use of the global context is deprecated, use " "LLVMFloatTypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMDoubleType(void), "Use of the global context is deprecated, use " "LLVMDoubleTypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMX86FP80Type(void), "Use of the global context is deprecated, use " "LLVMX86FP80TypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMFP128Type(void), "Use of the global context is deprecated, use " "LLVMFP128TypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMPPCFP128Type(void), "Use of the global context is deprecated, use " "LLVMPPCFP128TypeInContext instead")
Detailed Description
Function Documentation
LLVM_ATTRIBUTE_C_DEPRECATED() [1/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMBFloatTypevoid, "Use of the global context is deprecated, use " "LLVMBFloatTypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [2/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMDoubleTypevoid, "Use of the global context is deprecated, use " "LLVMDoubleTypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [3/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMFloatTypevoid, "Use of the global context is deprecated, use " "LLVMFloatTypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [4/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMFP128Typevoid, "Use of the global context is deprecated, use " "LLVMFP128TypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [5/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMHalfTypevoid, "Use of the global context is deprecated, use " "LLVMHalfTypeInContext instead")
Obtain a floating point type from the global context.
These map to the functions in this group of the same name.
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [6/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMPPCFP128Typevoid, "Use of the global context is deprecated, use " "LLVMPPCFP128TypeInContext instead")
References C(), and LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [7/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMX86FP80Typevoid, "Use of the global context is deprecated, use " "LLVMX86FP80TypeInContext instead")
References LLVM_C_ABI.
LLVMBFloatTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMBFloatTypeInContext (LLVMContextRef C)
Obtain a 16-bit brain floating point type from a context.
Definition at line 718 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getBFloatTy(), and llvm::unwrap().
Referenced by LLVMBFloatType().
LLVMDoubleTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMDoubleTypeInContext (LLVMContextRef C)
Obtain a 64-bit floating point type from a context.
Definition at line 724 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getDoubleTy(), and llvm::unwrap().
Referenced by LLVMDoubleType().
LLVMFloatTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMFloatTypeInContext (LLVMContextRef C)
Obtain a 32-bit floating point type from a context.
Definition at line 721 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getFloatTy(), and llvm::unwrap().
Referenced by LLVMFloatType().
LLVMFP128TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (112-bit mantissa) from a context.
Definition at line 730 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getFP128Ty(), and llvm::unwrap().
Referenced by LLVMFP128Type().
LLVMHalfTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMHalfTypeInContext (LLVMContextRef C)
Obtain a 16-bit floating point type from a context.
Definition at line 715 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getHalfTy(), and llvm::unwrap().
Referenced by LLVMHalfType().
LLVMPPCFP128TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMPPCFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (two 64-bits) from a context.
Definition at line 733 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getPPC_FP128Ty(), and llvm::unwrap().
Referenced by LLVMPPCFP128Type().
LLVMX86FP80TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMX86FP80TypeInContext (LLVMContextRef C)
Obtain a 80-bit floating point type (X87) from a context.
Definition at line 727 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getX86_FP80Ty(), and llvm::unwrap().
Referenced by LLVMX86FP80Type().