LLVM: ExecutionEngine-based ORC Utils
ExecutionEngine-based ORC Utils
LLVM-C: C interface to LLVM » Execution Engine
Functions
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateObjectLinkingLayerWithInProcessMemoryManager (LLVMOrcObjectLayerRef *Result, LLVMOrcExecutionSessionRef ES)
Create a ObjectLinkingLayer instance using the standard JITLink InProcessMemoryManager for memory management.
LLVM_C_ABI LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager (LLVMOrcExecutionSessionRef ES)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
LLVM_C_ABI LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManagerReserveAlloc (LLVMOrcExecutionSessionRef ES, LLVMBool ReserveAlloc)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
LLVM_C_ABI LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks (LLVMOrcExecutionSessionRef ES, void *CreateContextCtx, LLVMMemoryManagerCreateContextCallback CreateContext, LLVMMemoryManagerNotifyTerminatingCallback NotifyTerminating, LLVMMemoryManagerAllocateCodeSectionCallback AllocateCodeSection, LLVMMemoryManagerAllocateDataSectionCallback AllocateDataSection, LLVMMemoryManagerFinalizeMemoryCallback FinalizeMemory, LLVMMemoryManagerDestroyCallback Destroy)
Create a RTDyldObjectLinkingLayer instance using MCJIT-memory-manager-like callbacks.
LLVM_C_ABI void LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener (LLVMOrcObjectLayerRef RTDyldObjLinkingLayer, LLVMJITEventListenerRef Listener)
Add the given listener to the given RTDyldObjectLinkingLayer.
Detailed Description
Function Documentation
LLVMOrcCreateObjectLinkingLayerWithInProcessMemoryManager()
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateObjectLinkingLayerWithInProcessMemoryManager (LLVMOrcObjectLayerRef * Result, LLVMOrcExecutionSessionRef ES)
Create a ObjectLinkingLayer instance using the standard JITLink InProcessMemoryManager for memory management.
Definition at line 1022 of file OrcV2CBindings.cpp.
References assert(), llvm::jitlink::InProcessMemoryManager::Create(), LLVMErrorSuccess, llvm::orc::Result, llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks()
LLVM_C_ABI LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks (LLVMOrcExecutionSessionRef ES, void * CreateContextCtx, LLVMMemoryManagerCreateContextCallback CreateContext, LLVMMemoryManagerNotifyTerminatingCallback NotifyTerminating, LLVMMemoryManagerAllocateCodeSectionCallback AllocateCodeSection, LLVMMemoryManagerAllocateDataSectionCallback AllocateDataSection, LLVMMemoryManagerFinalizeMemoryCallback FinalizeMemory, LLVMMemoryManagerDestroyCallback Destroy)
Create a RTDyldObjectLinkingLayer instance using MCJIT-memory-manager-like callbacks.
This is intended to simplify transitions for existing MCJIT clients. The callbacks used are similar (but not identical) to the callbacks for LLVMCreateSimpleMCJITMemoryManager: Unlike MCJIT, RTDyldObjectLinkingLayer will create a new memory manager for each object linked by calling the given CreateContext callback. This allows for code removal by destroying each allocator individually. Every allocator will be destroyed (if it has not been already) at RTDyldObjectLinkingLayer destruction time, and the NotifyTerminating callback will be called to indicate that no further allocation contexts will be created.
To implement MCJIT-like behavior clients can implement CreateContext, NotifyTerminating, and Destroy as:
void *CreateContext(void *CtxCtx) { return CtxCtx; } void NotifyTerminating(void *CtxCtx) { MyOriginalDestroy(CtxCtx); } void Destroy(void *Ctx) { }
This scheme simply reuses the CreateContextCtx pointer as the one-and-only allocation context.
Definition at line 1054 of file OrcV2CBindings.cpp.
References llvm::RuntimeDyld::MemoryManager::allocateCodeSection(), llvm::RuntimeDyld::MemoryManager::allocateDataSection(), assert(), llvm::RuntimeDyld::MemoryManager::finalizeMemory(), LLVMMemoryManagerCreateContextCallback, llvm::Other, llvm::orc::Result, Size, std::swap(), llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager()
LLVM_C_ABI LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager (LLVMOrcExecutionSessionRef ES)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
Definition at line 1034 of file OrcV2CBindings.cpp.
References assert(), llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManagerReserveAlloc()
LLVM_C_ABI LLVMOrcObjectLayerRef LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManagerReserveAlloc (LLVMOrcExecutionSessionRef ES, LLVMBool ReserveAlloc)
Create a RTDyldObjectLinkingLayer instance using the standard SectionMemoryManager for memory management.
If ReserveAlloc is true then a contiguous range of memory will be reserved for each object file.
Definition at line 1044 of file OrcV2CBindings.cpp.
References assert(), llvm::unwrap(), and llvm::wrap().
LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener()
LLVM_C_ABI void LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener (LLVMOrcObjectLayerRef RTDyldObjLinkingLayer, LLVMJITEventListenerRef Listener)
Add the given listener to the given RTDyldObjectLinkingLayer.
Note: Layer must be an RTDyldObjectLinkingLayer instance or behavior is undefined.
Definition at line 1164 of file OrcV2CBindings.cpp.
References assert(), and llvm::unwrap().