LLVM: Bit Reader
Bit Reader
LLVM-C: C interface to LLVM
Functions
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMParseBitcode(LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage), "Use of the global context is deprecated, use LLVMParseBitcodeInContext2 " "instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMParseBitcode2(LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule), "Use of the global context is deprecated, use LLVMParseBitcodeInContext2 " "instead")
LLVM_C_ABI LLVMBool LLVMParseBitcodeInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage)
LLVM_C_ABI LLVMBool LLVMParseBitcodeInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule)
LLVM_C_ABI LLVMBool LLVMGetBitcodeModuleInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
LLVM_C_ABI LLVMBool LLVMGetBitcodeModuleInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM)
Reads a module from the given memory buffer, returning via the OutMP parameter a module provider which performs lazy deserialization.
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMGetBitcodeModule(LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage), "Use of the global context is deprecated, use " "LLVMGetBitcodeModuleInContext2 instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMGetBitcodeModule2(LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM), "Use of the global context is deprecated, use " "LLVMGetBitcodeModuleInContext2 instead")
Detailed Description
Function Documentation
LLVM_ATTRIBUTE_C_DEPRECATED() [1/4]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMGetBitcodeModuleLLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage, "Use of the global context is deprecated, use " "LLVMGetBitcodeModuleInContext2 instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [2/4]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMGetBitcodeModule2LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, "Use of the global context is deprecated, use " "LLVMGetBitcodeModuleInContext2 instead")
References LLVM_C_ABI, and LLVM_C_EXTERN_C_END.
LLVM_ATTRIBUTE_C_DEPRECATED() [3/4]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMParseBitcodeLLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, char **OutMessage, "Use of the global context is deprecated, use LLVMParseBitcodeInContext2 " "instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [4/4]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMBool LLVMParseBitcode2LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutModule, "Use of the global context is deprecated, use LLVMParseBitcodeInContext2 " "instead")
References LLVM_C_ABI.
LLVMGetBitcodeModuleInContext()
LLVM_C_ABI LLVMBool LLVMGetBitcodeModuleInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Reads a module from the specified path, returning via the OutMP parameter a module provider which performs lazy deserialization.
Returns 0 on success. Optionally returns a human-readable error message via OutMessage. This is deprecated. Use LLVMGetBitcodeModuleInContext2.
Definition at line 78 of file BitReader.cpp.
References llvm::Expected< T >::get(), llvm::getOwningLazyBitcodeModule(), llvm::handleAllErrors(), llvm::ErrorInfoBase::message(), Owner, llvm::Expected< T >::takeError(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMGetBitcodeModule().
LLVMGetBitcodeModuleInContext2()
LLVM_C_ABI LLVMBool LLVMGetBitcodeModuleInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM)
Reads a module from the given memory buffer, returning via the OutMP parameter a module provider which performs lazy deserialization.
Returns 0 on success.
Takes ownership of MemBuf if (and only if) the module was read successfully.
Definition at line 105 of file BitReader.cpp.
References llvm::expectedToErrorOrAndEmitErrors(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::getOwningLazyBitcodeModule(), Owner, llvm::unwrap(), and llvm::wrap().
Referenced by LLVMGetBitcodeModule2().
LLVMParseBitcodeInContext()
LLVM_C_ABI LLVMBool LLVMParseBitcodeInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule, char ** OutMessage)
Definition at line 35 of file BitReader.cpp.
References llvm::Expected< T >::get(), llvm::handleAllErrors(), llvm::ErrorInfoBase::message(), llvm::parseBitcodeFile(), llvm::Expected< T >::takeError(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMParseBitcode().
LLVMParseBitcodeInContext2()
LLVM_C_ABI LLVMBool LLVMParseBitcodeInContext2 (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutModule)
Definition at line 58 of file BitReader.cpp.
References llvm::expectedToErrorOrAndEmitErrors(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::parseBitcodeFile(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMParseBitcode2().