LLVM: Utility declarations/definitions specific to ARC.
Utility declarations/definitions specific to ARC.
Functions
static const Value * FindSingleUseIdentifiedObject (const Value *Arg)
This is similar to GetRCIdentityRoot but it stops as soon as it finds a value with multiple uses.
Detailed Description
Function Documentation
FindSingleUseIdentifiedObject()
const Value * FindSingleUseIdentifiedObject (const Value * Arg) static
This is similar to GetRCIdentityRoot but it stops as soon as it finds a value with multiple uses.
Definition at line 86 of file ObjCARCOpts.cpp.
References llvm::cast(), llvm::dyn_cast(), FindSingleUseIdentifiedObject(), GEP, llvm::objcarc::GetBasicARCInstKind(), llvm::objcarc::GetRCIdentityRoot(), llvm::Value::hasOneUse(), llvm::isa(), llvm::objcarc::IsForwarding(), llvm::objcarc::IsObjCIdentifiedObject(), and llvm::Value::users().
Referenced by FindSingleUseIdentifiedObject().