LLVM: Types
Types
LLVM-C: C interface to LLVM » Core
Types represent the type of a value.
Topics
Integer Types
Functions in this section operate on integer types.
Floating Point Types
Function Types
Structure Types
These functions relate to LLVMTypeRef instances.
Sequential Types
Sequential types represents "arrays" of types.
Other Types
Functions
LLVM_C_ABI LLVMTypeKind LLVMGetTypeKind (LLVMTypeRef Ty)
Obtain the enumerated type of a Type instance.
LLVM_C_ABI LLVMBool LLVMTypeIsSized (LLVMTypeRef Ty)
Whether the type has a known size.
LLVM_C_ABI LLVMContextRef LLVMGetTypeContext (LLVMTypeRef Ty)
Obtain the context to which this type instance is associated.
LLVM_C_ABI void LLVMDumpType (LLVMTypeRef Val)
Dump a representation of a type to stderr.
LLVM_C_ABI char * LLVMPrintTypeToString (LLVMTypeRef Val)
Return a string representation of the type.
Detailed Description
Types represent the type of a value.
Types are associated with a context instance. The context internally deduplicates types so there is only 1 instance of a specific type alive at a time. In other words, a unique type is shared among all consumers within a context.
A Type in the C API corresponds to llvm::Type.
Types have the following hierarchy:
types: integer type real type function type sequence types: array type pointer type vector type void type label type opaque type
Function Documentation
LLVMDumpType()
LLVM_C_ABI void LLVMDumpType (LLVMTypeRef Val)
Dump a representation of a type to stderr.
See also
llvm::Type::dump()
Definition at line 645 of file Core.cpp.
References llvm::errs(), and llvm::unwrap().
LLVMGetTypeContext()
LLVM_C_ABI LLVMContextRef LLVMGetTypeContext (LLVMTypeRef Ty)
Obtain the context to which this type instance is associated.
See also
llvm::Type::getContext()
Definition at line 641 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetTypeKind()
LLVM_C_ABI LLVMTypeKind LLVMGetTypeKind (LLVMTypeRef Ty)
Obtain the enumerated type of a Type instance.
See also
llvm::Type:getTypeID()
Definition at line 588 of file Core.cpp.
References llvm::Type::ArrayTyID, llvm::Type::BFloatTyID, llvm::Type::DoubleTyID, llvm::Type::FixedVectorTyID, llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::Type::FunctionTyID, getTypeID(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, llvm::Type::LabelTyID, llvm_unreachable, LLVMArrayTypeKind, LLVMBFloatTypeKind, LLVMDoubleTypeKind, LLVMFloatTypeKind, LLVMFP128TypeKind, LLVMFunctionTypeKind, LLVMHalfTypeKind, LLVMIntegerTypeKind, LLVMLabelTypeKind, LLVMMetadataTypeKind, LLVMPointerTypeKind, LLVMPPC_FP128TypeKind, LLVMScalableVectorTypeKind, LLVMStructTypeKind, LLVMTargetExtTypeKind, LLVMTokenTypeKind, LLVMVectorTypeKind, LLVMVoidTypeKind, LLVMX86_AMXTypeKind, LLVMX86_FP80TypeKind, llvm::Type::MetadataTyID, llvm::Type::PointerTyID, llvm::Type::PPC_FP128TyID, llvm::Type::ScalableVectorTyID, llvm::Type::StructTyID, llvm::Type::TargetExtTyID, llvm::Type::TokenTyID, llvm::Type::TypedPointerTyID, llvm::unwrap(), llvm::Type::VoidTyID, llvm::Type::X86_AMXTyID, and llvm::Type::X86_FP80TyID.
LLVMPrintTypeToString()
LLVM_C_ABI char * LLVMPrintTypeToString (LLVMTypeRef Val)
Return a string representation of the type.
Use LLVMDisposeMessage to free the string.
See also
llvm::Type::print()
Definition at line 649 of file Core.cpp.
References llvm::raw_ostream::flush(), and llvm::unwrap().
LLVMTypeIsSized()
LLVM_C_ABI LLVMBool LLVMTypeIsSized (LLVMTypeRef Ty)
Whether the type has a known size.
Things that don't have a size are abstract types, labels, and void.a
See also
llvm::Type::isSized()
Definition at line 636 of file Core.cpp.
References llvm::unwrap().