LLVM: Integer Types
Integer Types
LLVM-C: C interface to LLVM » Core » Types
Functions in this section operate on integer types.
Functions
LLVM_C_ABI LLVMTypeRef LLVMInt1TypeInContext (LLVMContextRef C)
Obtain an integer type from a context with specified bit width.
LLVM_C_ABI LLVMTypeRef LLVMInt8TypeInContext (LLVMContextRef C)
LLVM_C_ABI LLVMTypeRef LLVMInt16TypeInContext (LLVMContextRef C)
LLVM_C_ABI LLVMTypeRef LLVMInt32TypeInContext (LLVMContextRef C)
LLVM_C_ABI LLVMTypeRef LLVMInt64TypeInContext (LLVMContextRef C)
LLVM_C_ABI LLVMTypeRef LLVMInt128TypeInContext (LLVMContextRef C)
LLVM_C_ABI LLVMTypeRef LLVMIntTypeInContext (LLVMContextRef C, unsigned NumBits)
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt1Type(void), "Use of the global context is deprecated, use " "LLVMInt1TypeInContext instead")
Obtain an integer type from the global context with a specified bit width.
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt8Type(void), "Use of the global context is deprecated, use " "LLVMInt8TypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt16Type(void), "Use of the global context is deprecated, use " "LLVMInt16TypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt32Type(void), "Use of the global context is deprecated, use " "LLVMInt32TypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt64Type(void), "Use of the global context is deprecated, use " "LLVMInt64TypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt128Type(void), "Use of the global context is deprecated, use " "LLVMInt128TypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMIntType(unsigned NumBits), "Use of the global context is deprecated, use " "LLVMIntTypeInContext instead")
LLVM_C_ABI unsigned LLVMGetIntTypeWidth (LLVMTypeRef IntegerTy)
Detailed Description
Functions in this section operate on integer types.
Function Documentation
LLVM_ATTRIBUTE_C_DEPRECATED() [1/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt128Typevoid, "Use of the global context is deprecated, use " "LLVMInt128TypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [2/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt16Typevoid, "Use of the global context is deprecated, use " "LLVMInt16TypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [3/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt1Typevoid, "Use of the global context is deprecated, use " "LLVMInt1TypeInContext instead")
Obtain an integer type from the global context with a specified bit width.
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [4/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt32Typevoid, "Use of the global context is deprecated, use " "LLVMInt32TypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [5/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt64Typevoid, "Use of the global context is deprecated, use " "LLVMInt64TypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [6/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMInt8Typevoid, "Use of the global context is deprecated, use " "LLVMInt8TypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [7/7]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMIntTypeunsigned NumBits, "Use of the global context is deprecated, use " "LLVMIntTypeInContext instead")
References C(), and LLVM_C_ABI.
LLVMGetIntTypeWidth()
LLVM_C_ABI unsigned LLVMGetIntTypeWidth (LLVMTypeRef IntegerTy)
Definition at line 709 of file Core.cpp.
References llvm::unwrap().
LLVMInt128TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMInt128TypeInContext (LLVMContextRef C)
Definition at line 680 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getInt128Ty(), and llvm::unwrap().
Referenced by LLVMInt128Type().
LLVMInt16TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMInt16TypeInContext (LLVMContextRef C)
Definition at line 671 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getInt16Ty(), and llvm::unwrap().
Referenced by LLVMInt16Type().
LLVMInt1TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMInt1TypeInContext (LLVMContextRef C)
Obtain an integer type from a context with specified bit width.
Definition at line 665 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getInt1Ty(), and llvm::unwrap().
Referenced by LLVMInt1Type().
LLVMInt32TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMInt32TypeInContext (LLVMContextRef C)
Definition at line 674 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getInt32Ty(), and llvm::unwrap().
Referenced by LLVMInt32Type().
LLVMInt64TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMInt64TypeInContext (LLVMContextRef C)
Definition at line 677 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getInt64Ty(), and llvm::unwrap().
Referenced by LLVMInt64Type().
LLVMInt8TypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMInt8TypeInContext (LLVMContextRef C)
Definition at line 668 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getInt8Ty(), and llvm::unwrap().
Referenced by LLVMInt8Type().
LLVMIntTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMIntTypeInContext (LLVMContextRef C, unsigned NumBits)
Definition at line 683 of file Core.cpp.
References llvm::CallingConv::C, llvm::IntegerType::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMIntType().