LLVM: GEPs
GEPs
LLVM-C: C interface to LLVM » Core » Instructions
Functions in this group only apply to instructions that map to llvm::GetElementPtrInst instances.
Functions
LLVM_C_ABI LLVMBool LLVMIsInBounds (LLVMValueRef GEP)
Check whether the given GEP operator is inbounds.
LLVM_C_ABI void LLVMSetIsInBounds (LLVMValueRef GEP, LLVMBool InBounds)
Set the given GEP instruction to be inbounds or not.
LLVM_C_ABI LLVMTypeRef LLVMGetGEPSourceElementType (LLVMValueRef GEP)
Get the source element type of the given GEP operator.
LLVM_C_ABI LLVMGEPNoWrapFlags LLVMGEPGetNoWrapFlags (LLVMValueRef GEP)
Get the no-wrap related flags for the given GEP instruction.
LLVM_C_ABI void LLVMGEPSetNoWrapFlags (LLVMValueRef GEP, LLVMGEPNoWrapFlags NoWrapFlags)
Set the no-wrap related flags for the given GEP instruction.
Detailed Description
Functions in this group only apply to instructions that map to llvm::GetElementPtrInst instances.
Function Documentation
LLVMGEPGetNoWrapFlags()
LLVM_C_ABI LLVMGEPNoWrapFlags LLVMGEPGetNoWrapFlags (LLVMValueRef GEP)
Get the no-wrap related flags for the given GEP instruction.
See also
llvm::GetElementPtrInst::getNoWrapFlags
Definition at line 3297 of file Core.cpp.
References GEP, llvm::GEPOperator::getNoWrapFlags(), mapToLLVMGEPNoWrapFlags(), and llvm::unwrap().
LLVMGEPSetNoWrapFlags()
LLVM_C_ABI void LLVMGEPSetNoWrapFlags (LLVMValueRef GEP, LLVMGEPNoWrapFlags NoWrapFlags)
Set the no-wrap related flags for the given GEP instruction.
See also
llvm::GetElementPtrInst::setNoWrapFlags
Definition at line 3302 of file Core.cpp.
References GEP, mapFromLLVMGEPNoWrapFlags(), llvm::GetElementPtrInst::setNoWrapFlags(), and llvm::unwrap().
LLVMGetGEPSourceElementType()
LLVM_C_ABI LLVMTypeRef LLVMGetGEPSourceElementType (LLVMValueRef GEP)
Get the source element type of the given GEP operator.
Definition at line 3293 of file Core.cpp.
References GEP, llvm::unwrap(), and llvm::wrap().
LLVMIsInBounds()
LLVM_C_ABI LLVMBool LLVMIsInBounds (LLVMValueRef GEP)
Check whether the given GEP operator is inbounds.
Definition at line 3285 of file Core.cpp.
References GEP, and llvm::unwrap().
LLVMSetIsInBounds()
LLVM_C_ABI void LLVMSetIsInBounds (LLVMValueRef GEP, LLVMBool InBounds)
Set the given GEP instruction to be inbounds or not.
Definition at line 3289 of file Core.cpp.
References GEP, and llvm::unwrap().