LLVM: Usage
Usage
LLVM-C: C interface to LLVM » Core » Values
This module defines functions that allow you to inspect the uses of a LLVMValueRef.
Functions
LLVM_C_ABI LLVMUseRef LLVMGetFirstUse (LLVMValueRef Val)
Obtain the first use of a value.
LLVM_C_ABI LLVMUseRef LLVMGetNextUse (LLVMUseRef U)
Obtain the next use of a value.
LLVM_C_ABI LLVMValueRef LLVMGetUser (LLVMUseRef U)
Obtain the user value for a user.
LLVM_C_ABI LLVMValueRef LLVMGetUsedValue (LLVMUseRef U)
Obtain the value this use corresponds to.
Detailed Description
This module defines functions that allow you to inspect the uses of a LLVMValueRef.
It is possible to obtain an LLVMUseRef for any LLVMValueRef instance. Each LLVMUseRef (which corresponds to a llvm::Use instance) holds a llvm::User and llvm::Value.
Function Documentation
LLVMGetFirstUse()
LLVM_C_ABI LLVMUseRef LLVMGetFirstUse (LLVMValueRef Val)
Obtain the first use of a value.
Uses are obtained in an iterator fashion. First, call this function to obtain a reference to the first use. Then, call LLVMGetNextUse() on that instance and all subsequently obtained instances until LLVMGetNextUse() returns NULL.
See also
llvm::Value::use_begin()
Definition at line 1177 of file Core.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMGetNextUse()
LLVM_C_ABI LLVMUseRef LLVMGetNextUse (LLVMUseRef U)
Obtain the next use of a value.
This effectively advances the iterator. It returns NULL if you are on the final use and no more are available.
Definition at line 1185 of file Core.cpp.
References llvm::Next, llvm::unwrap(), and llvm::wrap().
LLVMGetUsedValue()
LLVM_C_ABI LLVMValueRef LLVMGetUsedValue (LLVMUseRef U)
Obtain the value this use corresponds to.
See also
llvm::Use::get().
Definition at line 1196 of file Core.cpp.
References llvm::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetUser()
LLVM_C_ABI LLVMValueRef LLVMGetUser (LLVMUseRef U)
Obtain the user value for a user.
The returned value corresponds to a llvm::User type.
See also
llvm::Use::getUser()
Definition at line 1192 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().