LLVM: On-Request-Compilation
On-Request-Compilation
LLVM-C: C interface to LLVM » Execution Engine
Classes
struct LLVMJITSymbolFlags
Represents the linkage flags for a symbol definition.
struct LLVMJITEvaluatedSymbol
Represents an evaluated symbol address and flags.
struct LLVMOrcCSymbolFlagsMapPair
Represents a pair of a symbol name and LLVMJITSymbolFlags.
struct LLVMOrcCSymbolMapPair
Represents a pair of a symbol name and an evaluated symbol.
struct LLVMOrcCSymbolAliasMapEntry
Represents a SymbolAliasMapEntry.
struct LLVMOrcCSymbolAliasMapPair
Represents a pair of a symbol name and SymbolAliasMapEntry.
struct LLVMOrcCSymbolsList
Represents a list of LLVMOrcSymbolStringPoolEntryRef and the associated length.
struct LLVMOrcCDependenceMapPair
Represents a pair of a JITDylib and LLVMOrcCSymbolsList.
struct LLVMOrcCSymbolDependenceGroup
A set of symbols that share dependencies.
struct LLVMOrcCJITDylibSearchOrderElement
An element type for a JITDylib search order.
struct LLVMOrcCLookupSetElement
An element type for a symbol lookup set.
Typedefs
typedef uint64_t LLVMOrcJITTargetAddress
Represents an address in the executor process.
typedef uint64_t LLVMOrcExecutorAddress
Represents an address in the executor process.
typedef uint8_t LLVMJITSymbolTargetFlags
Represents target specific flags for a symbol definition.
typedef struct LLVMOrcOpaqueExecutionSession * LLVMOrcExecutionSessionRef
A reference to an orc::ExecutionSession instance.
typedef void(* LLVMOrcErrorReporterFunction) (void *Ctx, LLVMErrorRef Err)
Error reporter function.
typedef struct LLVMOrcOpaqueSymbolStringPool * LLVMOrcSymbolStringPoolRef
A reference to an orc::SymbolStringPool.
typedef struct LLVMOrcOpaqueSymbolStringPoolEntry * LLVMOrcSymbolStringPoolEntryRef
A reference to an orc::SymbolStringPool table entry.
typedef LLVMOrcCSymbolFlagsMapPair * LLVMOrcCSymbolFlagsMapPairs
Represents a list of (SymbolStringPtr, JITSymbolFlags) pairs that can be used to construct a SymbolFlagsMap.
typedef LLVMOrcCSymbolMapPair * LLVMOrcCSymbolMapPairs
Represents a list of (SymbolStringPtr, JITEvaluatedSymbol) pairs that can be used to construct a SymbolMap.
typedef LLVMOrcCSymbolAliasMapPair * LLVMOrcCSymbolAliasMapPairs
Represents a list of (SymbolStringPtr, (SymbolStringPtr, JITSymbolFlags)) pairs that can be used to construct a SymbolFlagsMap.
typedef struct LLVMOrcOpaqueJITDylib * LLVMOrcJITDylibRef
A reference to an orc::JITDylib instance.
typedef LLVMOrcCDependenceMapPair * LLVMOrcCDependenceMapPairs
Represents a list of (JITDylibRef, (LLVMOrcSymbolStringPoolEntryRef*, size_t)) pairs that can be used to construct a SymbolDependenceMap.
typedef LLVMOrcCJITDylibSearchOrderElement * LLVMOrcCJITDylibSearchOrder
A JITDylib search order.
typedef LLVMOrcCLookupSetElement * LLVMOrcCLookupSet
A set of symbols to look up / generate.
typedef struct LLVMOrcOpaqueMaterializationUnit * LLVMOrcMaterializationUnitRef
A reference to a uniquely owned orc::MaterializationUnit instance.
typedef struct LLVMOrcOpaqueMaterializationResponsibility * LLVMOrcMaterializationResponsibilityRef
A reference to a uniquely owned orc::MaterializationResponsibility instance.
typedef void(* LLVMOrcMaterializationUnitMaterializeFunction) (void *Ctx, LLVMOrcMaterializationResponsibilityRef MR)
A MaterializationUnit materialize callback.
typedef void(* LLVMOrcMaterializationUnitDiscardFunction) (void *Ctx, LLVMOrcJITDylibRef JD, LLVMOrcSymbolStringPoolEntryRef Symbol)
A MaterializationUnit discard callback.
typedef void(* LLVMOrcMaterializationUnitDestroyFunction) (void *Ctx)
A MaterializationUnit destruction callback.
typedef struct LLVMOrcOpaqueResourceTracker * LLVMOrcResourceTrackerRef
A reference to an orc::ResourceTracker instance.
typedef struct LLVMOrcOpaqueDefinitionGenerator * LLVMOrcDefinitionGeneratorRef
A reference to an orc::DefinitionGenerator.
typedef struct LLVMOrcOpaqueLookupState * LLVMOrcLookupStateRef
An opaque lookup state object.
typedef LLVMErrorRef(* LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction) (LLVMOrcDefinitionGeneratorRef GeneratorObj, void *Ctx, LLVMOrcLookupStateRef *LookupState, LLVMOrcLookupKind Kind, LLVMOrcJITDylibRef JD, LLVMOrcJITDylibLookupFlags JDLookupFlags, LLVMOrcCLookupSet LookupSet, size_t LookupSetSize)
A custom generator function.
typedef void(* LLVMOrcDisposeCAPIDefinitionGeneratorFunction) (void *Ctx)
Disposer for a custom generator.
typedef int(* LLVMOrcSymbolPredicate) (void *Ctx, LLVMOrcSymbolStringPoolEntryRef Sym)
Predicate function for SymbolStringPoolEntries.
typedef struct LLVMOrcOpaqueThreadSafeContext * LLVMOrcThreadSafeContextRef
A reference to an orc::ThreadSafeContext instance.
typedef struct LLVMOrcOpaqueThreadSafeModule * LLVMOrcThreadSafeModuleRef
A reference to an orc::ThreadSafeModule instance.
typedef LLVMErrorRef(* LLVMOrcGenericIRModuleOperationFunction) (void *Ctx, LLVMModuleRef M)
A function for inspecting/mutating IR modules, suitable for use with LLVMOrcThreadSafeModuleWithModuleDo.
typedef struct LLVMOrcOpaqueJITTargetMachineBuilder * LLVMOrcJITTargetMachineBuilderRef
A reference to an orc::JITTargetMachineBuilder instance.
typedef struct LLVMOrcOpaqueObjectLayer * LLVMOrcObjectLayerRef
A reference to an orc::ObjectLayer instance.
typedef struct LLVMOrcOpaqueObjectLinkingLayer * LLVMOrcObjectLinkingLayerRef
A reference to an orc::ObjectLinkingLayer instance.
typedef struct LLVMOrcOpaqueIRTransformLayer * LLVMOrcIRTransformLayerRef
A reference to an orc::IRTransformLayer instance.
typedef LLVMErrorRef(* LLVMOrcIRTransformLayerTransformFunction) (void *Ctx, LLVMOrcThreadSafeModuleRef *ModInOut, LLVMOrcMaterializationResponsibilityRef MR)
A function for applying transformations as part of an transform layer.
typedef struct LLVMOrcOpaqueObjectTransformLayer * LLVMOrcObjectTransformLayerRef
A reference to an orc::ObjectTransformLayer instance.
typedef LLVMErrorRef(* LLVMOrcObjectTransformLayerTransformFunction) (void *Ctx, LLVMMemoryBufferRef *ObjInOut)
A function for applying transformations to an object file buffer.
typedef struct LLVMOrcOpaqueIndirectStubsManager * LLVMOrcIndirectStubsManagerRef
A reference to an orc::IndirectStubsManager instance.
typedef struct LLVMOrcOpaqueLazyCallThroughManager * LLVMOrcLazyCallThroughManagerRef
A reference to an orc::LazyCallThroughManager instance.
typedef struct LLVMOrcOpaqueDumpObjects * LLVMOrcDumpObjectsRef
A reference to an orc::DumpObjects object.
typedef void(* LLVMOrcExecutionSessionLookupHandleResultFunction) (LLVMErrorRef Err, LLVMOrcCSymbolMapPairs Result, size_t NumPairs, void *Ctx)
Callback type for ExecutionSession lookups.
Enumerations
enum LLVMJITSymbolGenericFlags {
LLVMJITSymbolGenericFlagsNone = 0 , LLVMJITSymbolGenericFlagsExported = 1U << 0 , LLVMJITSymbolGenericFlagsWeak = 1U << 1 , LLVMJITSymbolGenericFlagsCallable = 1U << 2 ,
LLVMJITSymbolGenericFlagsMaterializationSideEffectsOnly = 1U << 3
}
Represents generic linkage flags for a symbol definition.
enum LLVMOrcLookupKind { LLVMOrcLookupKindStatic , LLVMOrcLookupKindDLSym }
Lookup kind.
enum LLVMOrcJITDylibLookupFlags { LLVMOrcJITDylibLookupFlagsMatchExportedSymbolsOnly , LLVMOrcJITDylibLookupFlagsMatchAllSymbols }
JITDylib lookup flags.
enum LLVMOrcSymbolLookupFlags { LLVMOrcSymbolLookupFlagsRequiredSymbol , LLVMOrcSymbolLookupFlagsWeaklyReferencedSymbol }
Symbol lookup flags for lookup sets.
Functions
LLVM_C_ABI void LLVMOrcExecutionSessionSetErrorReporter (LLVMOrcExecutionSessionRef ES, LLVMOrcErrorReporterFunction ReportError, void *Ctx)
Attach a custom error reporter function to the ExecutionSession.
LLVM_C_ABI LLVMOrcSymbolStringPoolRef LLVMOrcExecutionSessionGetSymbolStringPool (LLVMOrcExecutionSessionRef ES)
Return a reference to the SymbolStringPool for an ExecutionSession.
LLVM_C_ABI void LLVMOrcSymbolStringPoolClearDeadEntries (LLVMOrcSymbolStringPoolRef SSP)
Clear all unreferenced symbol string pool entries.
LLVM_C_ABI LLVMOrcSymbolStringPoolEntryRef LLVMOrcExecutionSessionIntern (LLVMOrcExecutionSessionRef ES, const char *Name)
Intern a string in the ExecutionSession's SymbolStringPool and return a reference to it.
LLVM_C_ABI void LLVMOrcExecutionSessionLookup (LLVMOrcExecutionSessionRef ES, LLVMOrcLookupKind K, LLVMOrcCJITDylibSearchOrder SearchOrder, size_t SearchOrderSize, LLVMOrcCLookupSet Symbols, size_t SymbolsSize, LLVMOrcExecutionSessionLookupHandleResultFunction HandleResult, void *Ctx)
Look up symbols in an execution session.
LLVM_C_ABI void LLVMOrcRetainSymbolStringPoolEntry (LLVMOrcSymbolStringPoolEntryRef S)
Increments the ref-count for a SymbolStringPool entry.
LLVM_C_ABI void LLVMOrcReleaseSymbolStringPoolEntry (LLVMOrcSymbolStringPoolEntryRef S)
Reduces the ref-count for of a SymbolStringPool entry.
LLVM_C_ABI const char * LLVMOrcSymbolStringPoolEntryStr (LLVMOrcSymbolStringPoolEntryRef S)
Return the c-string for the given symbol.
LLVM_C_ABI void LLVMOrcReleaseResourceTracker (LLVMOrcResourceTrackerRef RT)
Reduces the ref-count of a ResourceTracker.
LLVM_C_ABI void LLVMOrcResourceTrackerTransferTo (LLVMOrcResourceTrackerRef SrcRT, LLVMOrcResourceTrackerRef DstRT)
Transfers tracking of all resources associated with resource tracker SrcRT to resource tracker DstRT.
LLVM_C_ABI LLVMErrorRef LLVMOrcResourceTrackerRemove (LLVMOrcResourceTrackerRef RT)
Remove all resources associated with the given tracker.
LLVM_C_ABI void LLVMOrcDisposeDefinitionGenerator (LLVMOrcDefinitionGeneratorRef DG)
Dispose of a JITDylib::DefinitionGenerator.
LLVM_C_ABI void LLVMOrcDisposeMaterializationUnit (LLVMOrcMaterializationUnitRef MU)
Dispose of a MaterializationUnit.
LLVM_C_ABI LLVMOrcMaterializationUnitRef LLVMOrcCreateCustomMaterializationUnit (const char *Name, void *Ctx, LLVMOrcCSymbolFlagsMapPairs Syms, size_t NumSyms, LLVMOrcSymbolStringPoolEntryRef InitSym, LLVMOrcMaterializationUnitMaterializeFunction Materialize, LLVMOrcMaterializationUnitDiscardFunction Discard, LLVMOrcMaterializationUnitDestroyFunction Destroy)
Create a custom MaterializationUnit.
LLVM_C_ABI LLVMOrcMaterializationUnitRef LLVMOrcAbsoluteSymbols (LLVMOrcCSymbolMapPairs Syms, size_t NumPairs)
Create a MaterializationUnit to define the given symbols as pointing to the corresponding raw addresses.
LLVM_C_ABI LLVMOrcMaterializationUnitRef LLVMOrcLazyReexports (LLVMOrcLazyCallThroughManagerRef LCTM, LLVMOrcIndirectStubsManagerRef ISM, LLVMOrcJITDylibRef SourceRef, LLVMOrcCSymbolAliasMapPairs CallableAliases, size_t NumPairs)
Create a MaterializationUnit to define lazy re-expots.
LLVM_C_ABI void LLVMOrcDisposeMaterializationResponsibility (LLVMOrcMaterializationResponsibilityRef MR)
Disposes of the passed MaterializationResponsibility object.
LLVM_C_ABI LLVMOrcJITDylibRef LLVMOrcMaterializationResponsibilityGetTargetDylib (LLVMOrcMaterializationResponsibilityRef MR)
Returns the target JITDylib that these symbols are being materialized into.
LLVM_C_ABI LLVMOrcExecutionSessionRef LLVMOrcMaterializationResponsibilityGetExecutionSession (LLVMOrcMaterializationResponsibilityRef MR)
Returns the ExecutionSession for this MaterializationResponsibility.
LLVM_C_ABI LLVMOrcCSymbolFlagsMapPairs LLVMOrcMaterializationResponsibilityGetSymbols (LLVMOrcMaterializationResponsibilityRef MR, size_t *NumPairs)
Returns the symbol flags map for this responsibility instance.
LLVM_C_ABI void LLVMOrcDisposeCSymbolFlagsMap (LLVMOrcCSymbolFlagsMapPairs Pairs)
Disposes of the passed LLVMOrcCSymbolFlagsMap.
LLVM_C_ABI LLVMOrcSymbolStringPoolEntryRef LLVMOrcMaterializationResponsibilityGetInitializerSymbol (LLVMOrcMaterializationResponsibilityRef MR)
Returns the initialization pseudo-symbol, if any.
LLVM_C_ABI LLVMOrcSymbolStringPoolEntryRef * LLVMOrcMaterializationResponsibilityGetRequestedSymbols (LLVMOrcMaterializationResponsibilityRef MR, size_t *NumSymbols)
Returns the names of any symbols covered by this MaterializationResponsibility object that have queries pending.
LLVM_C_ABI void LLVMOrcDisposeSymbols (LLVMOrcSymbolStringPoolEntryRef *Symbols)
Disposes of the passed LLVMOrcSymbolStringPoolEntryRef* .
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityNotifyResolved (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcCSymbolMapPairs Symbols, size_t NumPairs)
Notifies the target JITDylib that the given symbols have been resolved.
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityNotifyEmitted (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcCSymbolDependenceGroup *SymbolDepGroups, size_t NumSymbolDepGroups)
Notifies the target JITDylib (and any pending queries on that JITDylib) that all symbols covered by this MaterializationResponsibility instance have been emitted.
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityDefineMaterializing (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcCSymbolFlagsMapPairs Pairs, size_t NumPairs)
Attempt to claim responsibility for new definitions.
LLVM_C_ABI void LLVMOrcMaterializationResponsibilityFailMaterialization (LLVMOrcMaterializationResponsibilityRef MR)
Notify all not-yet-emitted covered by this MaterializationResponsibility instance that an error has occurred.
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityReplace (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcMaterializationUnitRef MU)
Transfers responsibility to the given MaterializationUnit for all symbols defined by that MaterializationUnit.
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityDelegate (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcSymbolStringPoolEntryRef *Symbols, size_t NumSymbols, LLVMOrcMaterializationResponsibilityRef *Result)
Delegates responsibility for the given symbols to the returned materialization responsibility.
LLVM_C_ABI LLVMOrcJITDylibRef LLVMOrcExecutionSessionCreateBareJITDylib (LLVMOrcExecutionSessionRef ES, const char *Name)
Create a "bare" JITDylib.
LLVM_C_ABI LLVMErrorRef LLVMOrcExecutionSessionCreateJITDylib (LLVMOrcExecutionSessionRef ES, LLVMOrcJITDylibRef *Result, const char *Name)
Create a JITDylib.
LLVM_C_ABI LLVMOrcJITDylibRef LLVMOrcExecutionSessionGetJITDylibByName (LLVMOrcExecutionSessionRef ES, const char *Name)
Returns the JITDylib with the given name, or NULL if no such JITDylib exists.
LLVM_C_ABI LLVMOrcResourceTrackerRef LLVMOrcJITDylibCreateResourceTracker (LLVMOrcJITDylibRef JD)
Return a reference to a newly created resource tracker associated with JD.
LLVM_C_ABI LLVMOrcResourceTrackerRef LLVMOrcJITDylibGetDefaultResourceTracker (LLVMOrcJITDylibRef JD)
Return a reference to the default resource tracker for the given JITDylib.
LLVM_C_ABI LLVMErrorRef LLVMOrcJITDylibDefine (LLVMOrcJITDylibRef JD, LLVMOrcMaterializationUnitRef MU)
Add the given MaterializationUnit to the given JITDylib.
LLVM_C_ABI LLVMErrorRef LLVMOrcJITDylibClear (LLVMOrcJITDylibRef JD)
Calls remove on all trackers associated with this JITDylib, see JITDylib::clear().
LLVM_C_ABI void LLVMOrcJITDylibAddGenerator (LLVMOrcJITDylibRef JD, LLVMOrcDefinitionGeneratorRef DG)
Add a DefinitionGenerator to the given JITDylib.
LLVM_C_ABI LLVMOrcDefinitionGeneratorRef LLVMOrcCreateCustomCAPIDefinitionGenerator (LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction F, void *Ctx, LLVMOrcDisposeCAPIDefinitionGeneratorFunction Dispose)
Create a custom generator.
LLVM_C_ABI void LLVMOrcLookupStateContinueLookup (LLVMOrcLookupStateRef S, LLVMErrorRef Err)
Continue a lookup that was suspended in a generator (see LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction).
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess (LLVMOrcDefinitionGeneratorRef *Result, char GlobalPrefx, LLVMOrcSymbolPredicate Filter, void *FilterCtx)
Get a DynamicLibrarySearchGenerator that will reflect process symbols into the JITDylib.
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateDynamicLibrarySearchGeneratorForPath (LLVMOrcDefinitionGeneratorRef *Result, const char *FileName, char GlobalPrefix, LLVMOrcSymbolPredicate Filter, void *FilterCtx)
Get a LLVMOrcCreateDynamicLibararySearchGeneratorForPath that will reflect library symbols into the JITDylib.
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateStaticLibrarySearchGeneratorForPath (LLVMOrcDefinitionGeneratorRef *Result, LLVMOrcObjectLayerRef ObjLayer, const char *FileName)
Get a LLVMOrcCreateStaticLibrarySearchGeneratorForPath that will reflect static library symbols into the JITDylib.
LLVM_C_ABI LLVMOrcThreadSafeContextRef LLVMOrcCreateNewThreadSafeContext (void)
Create a ThreadSafeContextRef containing a new LLVMContext.
LLVM_C_ABI LLVMOrcThreadSafeContextRef LLVMOrcCreateNewThreadSafeContextFromLLVMContext (LLVMContextRef Ctx)
Create a ThreadSafeContextRef from a given LLVMContext, which must not be associated with any existing ThreadSafeContext.
LLVM_C_ABI void LLVMOrcDisposeThreadSafeContext (LLVMOrcThreadSafeContextRef TSCtx)
Dispose of a ThreadSafeContext.
LLVM_C_ABI LLVMOrcThreadSafeModuleRef LLVMOrcCreateNewThreadSafeModule (LLVMModuleRef M, LLVMOrcThreadSafeContextRef TSCtx)
Create a ThreadSafeModule wrapper around the given LLVM module.
LLVM_C_ABI void LLVMOrcDisposeThreadSafeModule (LLVMOrcThreadSafeModuleRef TSM)
Dispose of a ThreadSafeModule.
LLVM_C_ABI LLVMErrorRef LLVMOrcThreadSafeModuleWithModuleDo (LLVMOrcThreadSafeModuleRef TSM, LLVMOrcGenericIRModuleOperationFunction F, void *Ctx)
Apply the given function to the module contained in this ThreadSafeModule.
LLVM_C_ABI LLVMErrorRef LLVMOrcJITTargetMachineBuilderDetectHost (LLVMOrcJITTargetMachineBuilderRef *Result)
Create a JITTargetMachineBuilder by detecting the host.
LLVM_C_ABI LLVMOrcJITTargetMachineBuilderRef LLVMOrcJITTargetMachineBuilderCreateFromTargetMachine (LLVMTargetMachineRef TM)
Create a JITTargetMachineBuilder from the given TargetMachine template.
LLVM_C_ABI void LLVMOrcDisposeJITTargetMachineBuilder (LLVMOrcJITTargetMachineBuilderRef JTMB)
Dispose of a JITTargetMachineBuilder.
LLVM_C_ABI char * LLVMOrcJITTargetMachineBuilderGetTargetTriple (LLVMOrcJITTargetMachineBuilderRef JTMB)
Returns the target triple for the given JITTargetMachineBuilder as a string.
LLVM_C_ABI void LLVMOrcJITTargetMachineBuilderSetTargetTriple (LLVMOrcJITTargetMachineBuilderRef JTMB, const char *TargetTriple)
Sets the target triple for the given JITTargetMachineBuilder to the given string.
LLVM_C_ABI LLVMErrorRef LLVMOrcObjectLayerAddObjectFile (LLVMOrcObjectLayerRef ObjLayer, LLVMOrcJITDylibRef JD, LLVMMemoryBufferRef ObjBuffer)
Add an object to an ObjectLayer to the given JITDylib.
LLVM_C_ABI LLVMErrorRef LLVMOrcObjectLayerAddObjectFileWithRT (LLVMOrcObjectLayerRef ObjLayer, LLVMOrcResourceTrackerRef RT, LLVMMemoryBufferRef ObjBuffer)
Add an object to an ObjectLayer using the given ResourceTracker.
LLVM_C_ABI void LLVMOrcObjectLayerEmit (LLVMOrcObjectLayerRef ObjLayer, LLVMOrcMaterializationResponsibilityRef R, LLVMMemoryBufferRef ObjBuffer)
Emit an object buffer to an ObjectLayer.
LLVM_C_ABI void LLVMOrcDisposeObjectLayer (LLVMOrcObjectLayerRef ObjLayer)
Dispose of an ObjectLayer.
LLVM_C_ABI void LLVMOrcIRTransformLayerEmit (LLVMOrcIRTransformLayerRef IRTransformLayer, LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcThreadSafeModuleRef TSM)
LLVM_C_ABI void LLVMOrcIRTransformLayerSetTransform (LLVMOrcIRTransformLayerRef IRTransformLayer, LLVMOrcIRTransformLayerTransformFunction TransformFunction, void *Ctx)
Set the transform function of the provided transform layer, passing through a pointer to user provided context.
LLVM_C_ABI void LLVMOrcObjectTransformLayerSetTransform (LLVMOrcObjectTransformLayerRef ObjTransformLayer, LLVMOrcObjectTransformLayerTransformFunction TransformFunction, void *Ctx)
Set the transform function on an LLVMOrcObjectTransformLayer.
LLVM_C_ABI LLVMOrcIndirectStubsManagerRef LLVMOrcCreateLocalIndirectStubsManager (const char *TargetTriple)
Create a LocalIndirectStubsManager from the given target triple.
LLVM_C_ABI void LLVMOrcDisposeIndirectStubsManager (LLVMOrcIndirectStubsManagerRef ISM)
Dispose of an IndirectStubsManager.
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateLocalLazyCallThroughManager (const char *TargetTriple, LLVMOrcExecutionSessionRef ES, LLVMOrcJITTargetAddress ErrorHandlerAddr, LLVMOrcLazyCallThroughManagerRef *LCTM)
LLVM_C_ABI void LLVMOrcDisposeLazyCallThroughManager (LLVMOrcLazyCallThroughManagerRef LCTM)
Dispose of an LazyCallThroughManager.
LLVM_C_ABI LLVMOrcDumpObjectsRef LLVMOrcCreateDumpObjects (const char *DumpDir, const char *IdentifierOverride)
Create a DumpObjects instance.
LLVM_C_ABI void LLVMOrcDisposeDumpObjects (LLVMOrcDumpObjectsRef DumpObjects)
Dispose of a DumpObjects instance.
LLVM_C_ABI LLVMErrorRef LLVMOrcDumpObjects_CallOperator (LLVMOrcDumpObjectsRef DumpObjects, LLVMMemoryBufferRef *ObjBuffer)
Dump the contents of the given MemoryBuffer.
Detailed Description
Typedef Documentation
LLVMJITSymbolTargetFlags
typedef uint8_t LLVMJITSymbolTargetFlags
Represents target specific flags for a symbol definition.
Definition at line 68 of file Orc.h.
LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction
typedef LLVMErrorRef(* LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction) (LLVMOrcDefinitionGeneratorRef GeneratorObj, void *Ctx, LLVMOrcLookupStateRef *LookupState, LLVMOrcLookupKind Kind, LLVMOrcJITDylibRef JD, LLVMOrcJITDylibLookupFlags JDLookupFlags, LLVMOrcCLookupSet LookupSet, size_t LookupSetSize)
A custom generator function.
This can be used to create a custom generator object using LLVMOrcCreateCustomCAPIDefinitionGenerator. The resulting object can be attached to a JITDylib, via LLVMOrcJITDylibAddGenerator, to receive callbacks when lookups fail to match existing definitions.
GeneratorObj will contain the address of the custom generator object.
Ctx will contain the context object passed to LLVMOrcCreateCustomCAPIDefinitionGenerator.
LookupState will contain a pointer to an LLVMOrcLookupStateRef object. This can optionally be modified to make the definition generation process asynchronous: If the LookupStateRef value is copied, and the original LLVMOrcLookupStateRef set to null, the lookup will be suspended. Once the asynchronous definition process has been completed clients must call LLVMOrcLookupStateContinueLookup to continue the lookup (this should be done unconditionally, even if errors have occurred in the mean time, to free the lookup state memory and notify the query object of the failures). If LookupState is captured this function must return LLVMErrorSuccess.
The Kind argument can be inspected to determine the lookup kind (e.g. as-if-during-static-link, or as-if-during-dlsym).
The JD argument specifies which JITDylib the definitions should be generated into.
The JDLookupFlags argument can be inspected to determine whether the original lookup included non-exported symbols.
Finally, the LookupSet argument contains the set of symbols that could not be found in JD already (the set of generation candidates).
Definition at line 364 of file Orc.h.
LLVMOrcCDependenceMapPairs
typedef LLVMOrcCDependenceMapPair* LLVMOrcCDependenceMapPairs
Represents a list of (JITDylibRef, (LLVMOrcSymbolStringPoolEntryRef*, size_t)) pairs that can be used to construct a SymbolDependenceMap.
Definition at line 183 of file Orc.h.
LLVMOrcCJITDylibSearchOrder
typedef LLVMOrcCJITDylibSearchOrderElement* LLVMOrcCJITDylibSearchOrder
A JITDylib search order.
The list is terminated with an element containing a null pointer for the JD field.
Definition at line 230 of file Orc.h.
LLVMOrcCLookupSet
typedef LLVMOrcCLookupSetElement* LLVMOrcCLookupSet
A set of symbols to look up / generate.
The list is terminated with an element containing a null pointer for the Name field.
If a client creates an instance of this type then they are responsible for freeing it, and for ensuring that all strings have been retained over the course of its life. Clients receiving a copy from a callback are not responsible for managing lifetime or retain counts.
Definition at line 260 of file Orc.h.
LLVMOrcCSymbolAliasMapPairs
typedef LLVMOrcCSymbolAliasMapPair* LLVMOrcCSymbolAliasMapPairs
Represents a list of (SymbolStringPtr, (SymbolStringPtr, JITSymbolFlags)) pairs that can be used to construct a SymbolFlagsMap.
Definition at line 155 of file Orc.h.
LLVMOrcCSymbolFlagsMapPairs
typedef LLVMOrcCSymbolFlagsMapPair* LLVMOrcCSymbolFlagsMapPairs
Represents a list of (SymbolStringPtr, JITSymbolFlags) pairs that can be used to construct a SymbolFlagsMap.
Definition at line 119 of file Orc.h.
LLVMOrcCSymbolMapPairs
typedef LLVMOrcCSymbolMapPair* LLVMOrcCSymbolMapPairs
Represents a list of (SymbolStringPtr, JITEvaluatedSymbol) pairs that can be used to construct a SymbolMap.
Definition at line 133 of file Orc.h.
LLVMOrcDefinitionGeneratorRef
typedef struct LLVMOrcOpaqueDefinitionGenerator* LLVMOrcDefinitionGeneratorRef
A reference to an orc::DefinitionGenerator.
Definition at line 315 of file Orc.h.
LLVMOrcDisposeCAPIDefinitionGeneratorFunction
typedef void(* LLVMOrcDisposeCAPIDefinitionGeneratorFunction) (void *Ctx)
Disposer for a custom generator.
Will be called by ORC when the JITDylib that the generator is attached to is destroyed.
Definition at line 376 of file Orc.h.
LLVMOrcDumpObjectsRef
typedef struct LLVMOrcOpaqueDumpObjects* LLVMOrcDumpObjectsRef
A reference to an orc::DumpObjects object.
Can be used to dump object files to disk with unique names. Useful as an ObjectTransformLayer transform.
Definition at line 481 of file Orc.h.
LLVMOrcErrorReporterFunction
typedef void(* LLVMOrcErrorReporterFunction) (void *Ctx, LLVMErrorRef Err)
Error reporter function.
Definition at line 94 of file Orc.h.
LLVMOrcExecutionSessionLookupHandleResultFunction
typedef void(* LLVMOrcExecutionSessionLookupHandleResultFunction) (LLVMErrorRef Err, LLVMOrcCSymbolMapPairs Result, size_t NumPairs, void *Ctx)
Callback type for ExecutionSession lookups.
If Err is LLVMErrorSuccess then Result will contain a pointer to a list of (SymbolStringPtr, JITEvaluatedSymbol) pairs of length NumPairs.
If Err is a failure value then Result and Ctx are undefined and should not be accessed. The Callback is responsible for handling the error value (e.g. by calling LLVMGetErrorMessage + LLVMDisposeErrorMessage).
The caller retains ownership of the Result array and will release all contained symbol names. Clients are responsible for retaining any symbol names that they wish to hold after the function returns.
Definition at line 547 of file Orc.h.
LLVMOrcExecutionSessionRef
typedef struct LLVMOrcOpaqueExecutionSession* LLVMOrcExecutionSessionRef
A reference to an orc::ExecutionSession instance.
Definition at line 89 of file Orc.h.
LLVMOrcExecutorAddress
typedef uint64_t LLVMOrcExecutorAddress
Represents an address in the executor process.
Definition at line 52 of file Orc.h.
LLVMOrcGenericIRModuleOperationFunction
typedef LLVMErrorRef(* LLVMOrcGenericIRModuleOperationFunction) (void *Ctx, LLVMModuleRef M)
A function for inspecting/mutating IR modules, suitable for use with LLVMOrcThreadSafeModuleWithModuleDo.
Definition at line 398 of file Orc.h.
LLVMOrcIndirectStubsManagerRef
typedef struct LLVMOrcOpaqueIndirectStubsManager* LLVMOrcIndirectStubsManagerRef
A reference to an orc::IndirectStubsManager instance.
Definition at line 467 of file Orc.h.
LLVMOrcIRTransformLayerRef
typedef struct LLVMOrcOpaqueIRTransformLayer* LLVMOrcIRTransformLayerRef
A reference to an orc::IRTransformLayer instance.
Definition at line 420 of file Orc.h.
LLVMOrcIRTransformLayerTransformFunction
typedef LLVMErrorRef(* LLVMOrcIRTransformLayerTransformFunction) (void *Ctx, LLVMOrcThreadSafeModuleRef *ModInOut, LLVMOrcMaterializationResponsibilityRef MR)
A function for applying transformations as part of an transform layer.
Implementations of this type are responsible for managing the lifetime of the Module pointed to by ModInOut: If the LLVMModuleRef value is overwritten then the function is responsible for disposing of the incoming module. If the module is simply accessed/mutated in-place then ownership returns to the caller and the function does not need to do any lifetime management.
Clients can call LLVMOrcLLJITGetIRTransformLayer to obtain the transform layer of a LLJIT instance, and use LLVMOrcIRTransformLayerSetTransform to set the function. This can be used to override the default transform layer.
Definition at line 437 of file Orc.h.
LLVMOrcJITDylibRef
typedef struct LLVMOrcOpaqueJITDylib* LLVMOrcJITDylibRef
A reference to an orc::JITDylib instance.
Definition at line 160 of file Orc.h.
LLVMOrcJITTargetAddress
typedef uint64_t LLVMOrcJITTargetAddress
Represents an address in the executor process.
Definition at line 47 of file Orc.h.
LLVMOrcJITTargetMachineBuilderRef
typedef struct LLVMOrcOpaqueJITTargetMachineBuilder* LLVMOrcJITTargetMachineBuilderRef
A reference to an orc::JITTargetMachineBuilder instance.
Definition at line 405 of file Orc.h.
LLVMOrcLazyCallThroughManagerRef
typedef struct LLVMOrcOpaqueLazyCallThroughManager* LLVMOrcLazyCallThroughManagerRef
A reference to an orc::LazyCallThroughManager instance.
Definition at line 473 of file Orc.h.
LLVMOrcLookupStateRef
typedef struct LLVMOrcOpaqueLookupState* LLVMOrcLookupStateRef
An opaque lookup state object.
Instances of this type can be captured to suspend a lookup while a custom generator function attempts to produce a definition.
If a client captures a lookup state object then they must eventually call LLVMOrcLookupStateContinueLookup to restart the lookup. This is required in order to release memory allocated for the lookup state, even if errors have occurred while the lookup was suspended (if these errors have made the lookup impossible to complete then it will issue its own error before destruction).
Definition at line 329 of file Orc.h.
LLVMOrcMaterializationResponsibilityRef
typedef struct LLVMOrcOpaqueMaterializationResponsibility* LLVMOrcMaterializationResponsibilityRef
A reference to a uniquely owned orc::MaterializationResponsibility instance.
Ownership must be passed to a lower-level layer in a JIT stack.
Definition at line 273 of file Orc.h.
LLVMOrcMaterializationUnitDestroyFunction
typedef void(* LLVMOrcMaterializationUnitDestroyFunction) (void *Ctx)
A MaterializationUnit destruction callback.
If a custom MaterializationUnit is destroyed before its Materialize function is called then this function will be called to provide an opportunity for the underlying program representation to be destroyed.
Definition at line 304 of file Orc.h.
LLVMOrcMaterializationUnitDiscardFunction
typedef void(* LLVMOrcMaterializationUnitDiscardFunction) (void *Ctx, LLVMOrcJITDylibRef JD, LLVMOrcSymbolStringPoolEntryRef Symbol)
A MaterializationUnit discard callback.
Ownership of JD and Symbol remain with the caller: These arguments should not be disposed of or released.
Definition at line 294 of file Orc.h.
LLVMOrcMaterializationUnitMaterializeFunction
typedef void(* LLVMOrcMaterializationUnitMaterializeFunction) (void *Ctx, LLVMOrcMaterializationResponsibilityRef MR)
A MaterializationUnit materialize callback.
Ownership of the Ctx and MR arguments passes to the callback which must adhere to the LLVMOrcMaterializationResponsibilityRef contract (see comment for that type).
If this callback is called then the LLVMOrcMaterializationUnitDestroy callback will NOT be called.
Definition at line 285 of file Orc.h.
LLVMOrcMaterializationUnitRef
typedef struct LLVMOrcOpaqueMaterializationUnit* LLVMOrcMaterializationUnitRef
A reference to a uniquely owned orc::MaterializationUnit instance.
Definition at line 265 of file Orc.h.
LLVMOrcObjectLayerRef
typedef struct LLVMOrcOpaqueObjectLayer* LLVMOrcObjectLayerRef
A reference to an orc::ObjectLayer instance.
Definition at line 410 of file Orc.h.
LLVMOrcObjectLinkingLayerRef
typedef struct LLVMOrcOpaqueObjectLinkingLayer* LLVMOrcObjectLinkingLayerRef
A reference to an orc::ObjectLinkingLayer instance.
Definition at line 415 of file Orc.h.
LLVMOrcObjectTransformLayerRef
typedef struct LLVMOrcOpaqueObjectTransformLayer* LLVMOrcObjectTransformLayerRef
A reference to an orc::ObjectTransformLayer instance.
Definition at line 445 of file Orc.h.
LLVMOrcObjectTransformLayerTransformFunction
typedef LLVMErrorRef(* LLVMOrcObjectTransformLayerTransformFunction) (void *Ctx, LLVMMemoryBufferRef *ObjInOut)
A function for applying transformations to an object file buffer.
Implementations of this type are responsible for managing the lifetime of the memory buffer pointed to by ObjInOut: If the LLVMMemoryBufferRef value is overwritten then the function is responsible for disposing of the incoming buffer. If the buffer is simply accessed/mutated in-place then ownership returns to the caller and the function does not need to do any lifetime management.
The transform is allowed to return an error, in which case the ObjInOut buffer should be disposed of and set to null.
Definition at line 460 of file Orc.h.
LLVMOrcResourceTrackerRef
typedef struct LLVMOrcOpaqueResourceTracker* LLVMOrcResourceTrackerRef
A reference to an orc::ResourceTracker instance.
Definition at line 309 of file Orc.h.
LLVMOrcSymbolPredicate
typedef int(* LLVMOrcSymbolPredicate) (void *Ctx, LLVMOrcSymbolStringPoolEntryRef Sym)
Predicate function for SymbolStringPoolEntries.
Definition at line 381 of file Orc.h.
LLVMOrcSymbolStringPoolEntryRef
typedef struct LLVMOrcOpaqueSymbolStringPoolEntry* LLVMOrcSymbolStringPoolEntryRef
A reference to an orc::SymbolStringPool table entry.
Definition at line 105 of file Orc.h.
LLVMOrcSymbolStringPoolRef
typedef struct LLVMOrcOpaqueSymbolStringPool* LLVMOrcSymbolStringPoolRef
A reference to an orc::SymbolStringPool.
Definition at line 99 of file Orc.h.
LLVMOrcThreadSafeContextRef
typedef struct LLVMOrcOpaqueThreadSafeContext* LLVMOrcThreadSafeContextRef
A reference to an orc::ThreadSafeContext instance.
Definition at line 387 of file Orc.h.
LLVMOrcThreadSafeModuleRef
typedef struct LLVMOrcOpaqueThreadSafeModule* LLVMOrcThreadSafeModuleRef
A reference to an orc::ThreadSafeModule instance.
Definition at line 392 of file Orc.h.
Enumeration Type Documentation
LLVMJITSymbolGenericFlags
enum LLVMJITSymbolGenericFlags
Represents generic linkage flags for a symbol definition.
Enumerator
LLVMJITSymbolGenericFlagsNone
LLVMJITSymbolGenericFlagsExported
LLVMJITSymbolGenericFlagsWeak
LLVMJITSymbolGenericFlagsCallable
LLVMJITSymbolGenericFlagsMaterializationSideEffectsOnly
Definition at line 57 of file Orc.h.
LLVMOrcJITDylibLookupFlags
enum LLVMOrcJITDylibLookupFlags
JITDylib lookup flags.
This can be used by definition generators when deciding whether to produce a definition for a requested symbol.
This enum should be kept in sync with llvm::orc::JITDylibLookupFlags.
Enumerator
LLVMOrcJITDylibLookupFlagsMatchExportedSymbolsOnly
LLVMOrcJITDylibLookupFlagsMatchAllSymbols
Definition at line 211 of file Orc.h.
LLVMOrcLookupKind
enum LLVMOrcLookupKind
Lookup kind.
This can be used by definition generators when deciding whether to produce a definition for a requested symbol.
This enum should be kept in sync with llvm::orc::LookupKind.
Enumerator
LLVMOrcLookupKindStatic
LLVMOrcLookupKindDLSym
Definition at line 200 of file Orc.h.
LLVMOrcSymbolLookupFlags
enum LLVMOrcSymbolLookupFlags
Symbol lookup flags for lookup sets.
This should be kept in sync with llvm::orc::SymbolLookupFlags.
Enumerator
LLVMOrcSymbolLookupFlagsRequiredSymbol
LLVMOrcSymbolLookupFlagsWeaklyReferencedSymbol
Definition at line 236 of file Orc.h.
Function Documentation
LLVMOrcAbsoluteSymbols()
LLVM_C_ABI LLVMOrcMaterializationUnitRef LLVMOrcAbsoluteSymbols (LLVMOrcCSymbolMapPairs Syms, size_t NumPairs)
Create a MaterializationUnit to define the given symbols as pointing to the corresponding raw addresses.
This function takes ownership of the elements of the Syms array. The Name fields of the array elements are taken to have been retained for this function. This allows the following pattern...
size_t NumPairs; LLVMOrcCSymbolMapPairs Sym; – Build Syms array – LLVMOrcMaterializationUnitRef MU = LLVMOrcAbsoluteSymbols(Syms, NumPairs);
... without requiring cleanup of the elements of the Sym array afterwards.
The client is still responsible for deleting the Sym array itself.
If a client wishes to reuse elements of the Sym array after this call they must explicitly retain each of the elements for themselves.
Definition at line 445 of file OrcV2CBindings.cpp.
References llvm::orc::absoluteSymbols(), llvm::release, SM(), and llvm::wrap().
LLVMOrcCreateCustomCAPIDefinitionGenerator()
LLVM_C_ABI LLVMOrcDefinitionGeneratorRef LLVMOrcCreateCustomCAPIDefinitionGenerator (LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction F, void * Ctx, LLVMOrcDisposeCAPIDefinitionGeneratorFunction Dispose)
Create a custom generator.
The F argument will be used to implement the DefinitionGenerator's tryToGenerate method (see LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction).
Ctx is a context object that will be passed to F. This argument is permitted to be null.
Dispose is the disposal function for Ctx. This argument is permitted to be null (in which case the client is responsible for the lifetime of Ctx).
Definition at line 648 of file OrcV2CBindings.cpp.
References F, and llvm::wrap().
LLVMOrcCreateCustomMaterializationUnit()
LLVM_C_ABI LLVMOrcMaterializationUnitRef LLVMOrcCreateCustomMaterializationUnit (const char * Name, void * Ctx, LLVMOrcCSymbolFlagsMapPairs Syms, size_t NumSyms, LLVMOrcSymbolStringPoolEntryRef InitSym, LLVMOrcMaterializationUnitMaterializeFunction Materialize, LLVMOrcMaterializationUnitDiscardFunction Discard, LLVMOrcMaterializationUnitDestroyFunction Destroy)
Create a custom MaterializationUnit.
Name is a name for this MaterializationUnit to be used for identification and logging purposes (e.g. if this MaterializationUnit produces an object buffer then the name of that buffer will be derived from this name).
The Syms list contains the names and linkages of the symbols provided by this unit. This function takes ownership of the elements of the Syms array. The Name fields of the array elements are taken to have been retained for this function. The client should not release the elements of the array, but is still responsible for destroying the array itself.
The InitSym argument indicates whether or not this MaterializationUnit contains static initializers. If three are no static initializers (the common case) then this argument should be null. If there are static initializers then InitSym should be set to a unique name that also appears in the Syms list with the LLVMJITSymbolGenericFlagsMaterializationSideEffectsOnly flag set. This function takes ownership of the InitSym, which should have been retained twice on behalf of this function: once for the Syms entry and once for InitSym. If clients wish to use the InitSym value after this function returns they must retain it once more for themselves.
If any of the symbols in the Syms list is looked up then the Materialize function will be called.
If any of the symbols in the Syms list is overridden then the Discard function will be called.
The caller owns the underling MaterializationUnit and is responsible for either passing it to a JITDylib (via LLVMOrcJITDylibDefine) or disposing of it by calling LLVMOrcDisposeMaterializationUnit.
Definition at line 427 of file OrcV2CBindings.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateDumpObjects()
LLVM_C_ABI LLVMOrcDumpObjectsRef LLVMOrcCreateDumpObjects (const char * DumpDir, const char * IdentifierOverride)
Create a DumpObjects instance.
DumpDir specifies the path to write dumped objects to. DumpDir may be empty in which case files will be dumped to the working directory.
IdentifierOverride specifies a file name stem to use when dumping objects. If empty then each MemoryBuffer's identifier will be used (with a .o suffix added if not already present). If an identifier override is supplied it will be used instead, along with an incrementing counter (since all buffers will use the same identifier, the resulting files will be named <ident>.o, <ident>.2.o, <ident>.3.o, and so on). IdentifierOverride should not contain an extension, as a .o suffix will be added by DumpObjects.
Definition at line 876 of file OrcV2CBindings.cpp.
References assert(), and llvm::wrap().
LLVMOrcCreateDynamicLibrarySearchGeneratorForPath()
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateDynamicLibrarySearchGeneratorForPath (LLVMOrcDefinitionGeneratorRef * Result, const char * FileName, char GlobalPrefix, LLVMOrcSymbolPredicate Filter, void * FilterCtx)
Get a LLVMOrcCreateDynamicLibararySearchGeneratorForPath that will reflect library symbols into the JITDylib.
On success the resulting generator is owned by the client. Ownership is typically transferred by adding the instance to a JITDylib using LLVMOrcJITDylibAddGenerator,
The GlobalPrefix argument specifies the character that appears on the front of linker-mangled symbols for the target platform (e.g. '_' on MachO). If non-null, this character will be stripped from the start of all symbol strings before passing the remaining substring to dlsym.
The optional Filter and Ctx arguments can be used to supply a symbol name filter: Only symbols for which the filter returns true will be visible to JIT'd code. If the Filter argument is null then all library symbols will be visible to JIT'd code. Note that the symbol name passed to the Filter function is the full mangled symbol: The client is responsible for stripping the global prefix if present.
THIS API IS EXPERIMENTAL AND LIKELY TO CHANGE IN THE NEAR FUTURE!
Definition at line 687 of file OrcV2CBindings.cpp.
References assert(), llvm::Filter, llvm::orc::SymbolStringPoolEntryUnsafe::from(), GlobalPrefix, LLVMErrorSuccess, llvm::orc::DynamicLibrarySearchGenerator::Load(), llvm::orc::Result, and llvm::wrap().
LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess()
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess (LLVMOrcDefinitionGeneratorRef * Result, char GlobalPrefx, LLVMOrcSymbolPredicate Filter, void * FilterCtx)
Get a DynamicLibrarySearchGenerator that will reflect process symbols into the JITDylib.
On success the resulting generator is owned by the client. Ownership is typically transferred by adding the instance to a JITDylib using LLVMOrcJITDylibAddGenerator,
The GlobalPrefix argument specifies the character that appears on the front of linker-mangled symbols for the target platform (e.g. '_' on MachO). If non-null, this character will be stripped from the start of all symbol strings before passing the remaining substring to dlsym.
The optional Filter and Ctx arguments can be used to supply a symbol name filter: Only symbols for which the filter returns true will be visible to JIT'd code. If the Filter argument is null then all process symbols will be visible to JIT'd code. Note that the symbol name passed to the Filter function is the full mangled symbol: The client is responsible for stripping the global prefix if present.
Definition at line 662 of file OrcV2CBindings.cpp.
References assert(), llvm::Filter, llvm::orc::SymbolStringPoolEntryUnsafe::from(), llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(), GlobalPrefix, LLVMErrorSuccess, llvm::orc::Result, and llvm::wrap().
LLVMOrcCreateLocalIndirectStubsManager()
LLVM_C_ABI LLVMOrcIndirectStubsManagerRef LLVMOrcCreateLocalIndirectStubsManager (const char * TargetTriple)
Create a LocalIndirectStubsManager from the given target triple.
The resulting IndirectStubsManager is owned by the client and must be disposed of by calling LLVMOrcDisposeDisposeIndirectStubsManager.
Definition at line 1182 of file OrcV2CBindings.cpp.
References llvm::orc::createLocalIndirectStubsManagerBuilder(), llvm::release, and llvm::wrap().
LLVMOrcCreateLocalLazyCallThroughManager()
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateLocalLazyCallThroughManager (const char * TargetTriple, LLVMOrcExecutionSessionRef ES, LLVMOrcJITTargetAddress ErrorHandlerAddr, LLVMOrcLazyCallThroughManagerRef * LCTM)
Definition at line 1191 of file OrcV2CBindings.cpp.
References llvm::orc::createLocalLazyCallThroughManager(), LLVMErrorSuccess, llvm::orc::Result, llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateNewThreadSafeContext()
LLVM_C_ABI LLVMOrcThreadSafeContextRef LLVMOrcCreateNewThreadSafeContext (void)
Create a ThreadSafeContextRef containing a new LLVMContext.
Ownership of the underlying ThreadSafeContext data is shared: Clients can and should dispose of their ThreadSafeContextRef as soon as they no longer need to refer to it directly. Other references (e.g. from ThreadSafeModules) will keep the underlying data alive as long as it is needed.
Definition at line 730 of file OrcV2CBindings.cpp.
References llvm::wrap().
LLVMOrcCreateNewThreadSafeContextFromLLVMContext()
LLVM_C_ABI LLVMOrcThreadSafeContextRef LLVMOrcCreateNewThreadSafeContextFromLLVMContext (LLVMContextRef Ctx)
Create a ThreadSafeContextRef from a given LLVMContext, which must not be associated with any existing ThreadSafeContext.
The underlying ThreadSafeContext will take ownership of the LLVMContext object, so clients should not free the LLVMContext passed to this function.
Ownership of the underlying ThreadSafeContext data is shared: Clients can and should dispose of their ThreadSafeContextRef as soon as they no longer need to refer to it directly. Other references (e.g. from ThreadSafeModules) will keep the underlying data alive as long as it is needed.
Definition at line 735 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateNewThreadSafeModule()
LLVM_C_ABI LLVMOrcThreadSafeModuleRef LLVMOrcCreateNewThreadSafeModule (LLVMModuleRef M, LLVMOrcThreadSafeContextRef TSCtx)
Create a ThreadSafeModule wrapper around the given LLVM module.
This takes ownership of the M argument which should not be disposed of or referenced after this function returns.
Ownership of the ThreadSafeModule is unique: If it is transferred to the JIT (e.g. by LLVMOrcLLJITAddLLVMIRModule) then the client is no longer responsible for it. If it is not transferred to the JIT then the client should call LLVMOrcDisposeThreadSafeModule to dispose of it.
Definition at line 752 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateStaticLibrarySearchGeneratorForPath()
LLVM_C_ABI LLVMErrorRef LLVMOrcCreateStaticLibrarySearchGeneratorForPath (LLVMOrcDefinitionGeneratorRef * Result, LLVMOrcObjectLayerRef ObjLayer, const char * FileName)
Get a LLVMOrcCreateStaticLibrarySearchGeneratorForPath that will reflect static library symbols into the JITDylib.
On success the resulting generator is owned by the client. Ownership is typically transferred by adding the instance to a JITDylib using LLVMOrcJITDylibAddGenerator,
Call with the optional TargetTriple argument will succeed if the file at the given path is a static library or a MachO universal binary containing a static library that is compatible with the given triple. Otherwise it will return an error.
THIS API IS EXPERIMENTAL AND LIKELY TO CHANGE IN THE NEAR FUTURE!
Definition at line 713 of file OrcV2CBindings.cpp.
References assert(), LLVMErrorSuccess, llvm::orc::StaticLibraryDefinitionGenerator::Load(), llvm::orc::Result, llvm::unwrap(), and llvm::wrap().
LLVMOrcDisposeCSymbolFlagsMap()
LLVM_C_ABI void LLVMOrcDisposeCSymbolFlagsMap (LLVMOrcCSymbolFlagsMapPairs Pairs)
Disposes of the passed LLVMOrcCSymbolFlagsMap.
Does not release the entries themselves.
Definition at line 502 of file OrcV2CBindings.cpp.
LLVMOrcDisposeDefinitionGenerator()
LLVM_C_ABI void LLVMOrcDisposeDefinitionGenerator (LLVMOrcDefinitionGeneratorRef DG)
Dispose of a JITDylib::DefinitionGenerator.
This should only be called if ownership has not been passed to a JITDylib (e.g. because some error prevented the client from calling LLVMOrcJITDylibAddGenerator).
Definition at line 419 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeDumpObjects()
LLVM_C_ABI void LLVMOrcDisposeDumpObjects (LLVMOrcDumpObjectsRef DumpObjects)
Dispose of a DumpObjects instance.
Definition at line 883 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeIndirectStubsManager()
LLVM_C_ABI void LLVMOrcDisposeIndirectStubsManager (LLVMOrcIndirectStubsManagerRef ISM)
Dispose of an IndirectStubsManager.
Definition at line 1187 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeJITTargetMachineBuilder()
LLVM_C_ABI void LLVMOrcDisposeJITTargetMachineBuilder (LLVMOrcJITTargetMachineBuilderRef JTMB)
Dispose of a JITTargetMachineBuilder.
Definition at line 796 of file OrcV2CBindings.cpp.
References llvm::unwrap().
Referenced by LLVMOrcLLJITBuilderSetJITTargetMachineBuilder().
LLVMOrcDisposeLazyCallThroughManager()
LLVM_C_ABI void LLVMOrcDisposeLazyCallThroughManager (LLVMOrcLazyCallThroughManagerRef LCTM)
Dispose of an LazyCallThroughManager.
Definition at line 1204 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeMaterializationResponsibility()
LLVM_C_ABI void LLVMOrcDisposeMaterializationResponsibility (LLVMOrcMaterializationResponsibilityRef MR)
Disposes of the passed MaterializationResponsibility object.
This should only be done after the symbols covered by the object have either been resolved and emitted (via LLVMOrcMaterializationResponsibilityNotifyResolved and LLVMOrcMaterializationResponsibilityNotifyEmitted) or failed (via LLVMOrcMaterializationResponsibilityFailMaterialization).
Definition at line 469 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeMaterializationUnit()
LLVM_C_ABI void LLVMOrcDisposeMaterializationUnit (LLVMOrcMaterializationUnitRef MU)
Dispose of a MaterializationUnit.
Definition at line 423 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeObjectLayer()
LLVM_C_ABI void LLVMOrcDisposeObjectLayer (LLVMOrcObjectLayerRef ObjLayer)
Dispose of an ObjectLayer.
Definition at line 837 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeSymbols()
LLVM_C_ABI void LLVMOrcDisposeSymbols (LLVMOrcSymbolStringPoolEntryRef * Symbols)
Disposes of the passed LLVMOrcSymbolStringPoolEntryRef* .
Does not release the symbols themselves.
Definition at line 530 of file OrcV2CBindings.cpp.
LLVMOrcDisposeThreadSafeContext()
LLVM_C_ABI void LLVMOrcDisposeThreadSafeContext (LLVMOrcThreadSafeContextRef TSCtx)
Dispose of a ThreadSafeContext.
Definition at line 739 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcDisposeThreadSafeModule()
LLVM_C_ABI void LLVMOrcDisposeThreadSafeModule (LLVMOrcThreadSafeModuleRef TSM)
Dispose of a ThreadSafeModule.
This should only be called if ownership has not been passed to LLJIT (e.g. because some error prevented the client from adding this to the JIT).
Definition at line 758 of file OrcV2CBindings.cpp.
References llvm::unwrap().
Referenced by LLVMOrcIRTransformLayerSetTransform().
LLVMOrcDumpObjects_CallOperator()
LLVM_C_ABI LLVMErrorRef LLVMOrcDumpObjects_CallOperator (LLVMOrcDumpObjectsRef DumpObjects, LLVMMemoryBufferRef * ObjBuffer)
Dump the contents of the given MemoryBuffer.
Definition at line 887 of file OrcV2CBindings.cpp.
References LLVMErrorSuccess, llvm::orc::Result, llvm::unwrap(), and llvm::wrap().
LLVMOrcExecutionSessionCreateBareJITDylib()
LLVM_C_ABI LLVMOrcJITDylibRef LLVMOrcExecutionSessionCreateBareJITDylib (LLVMOrcExecutionSessionRef ES, const char * Name)
Create a "bare" JITDylib.
The client is responsible for ensuring that the JITDylib's name is unique, e.g. by calling LLVMOrcExecutionSessionGetJTIDylibByName first.
This call does not install any library code or symbols into the newly created JITDylib. The client is responsible for all configuration.
Definition at line 606 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcExecutionSessionCreateJITDylib()
LLVM_C_ABI LLVMErrorRef LLVMOrcExecutionSessionCreateJITDylib (LLVMOrcExecutionSessionRef ES, LLVMOrcJITDylibRef * Result, const char * Name)
Create a JITDylib.
The client is responsible for ensuring that the JITDylib's name is unique, e.g. by calling LLVMOrcExecutionSessionGetJTIDylibByName first.
If a Platform is attached to the ExecutionSession then Platform::setupJITDylib will be called to install standard platform symbols (e.g. standard library interposes). If no Platform is installed then this call is equivalent to LLVMExecutionSessionRefCreateBareJITDylib and will always return success.
Definition at line 612 of file OrcV2CBindings.cpp.
References LLVMErrorSuccess, llvm::orc::Result, llvm::unwrap(), and llvm::wrap().
LLVMOrcExecutionSessionGetJITDylibByName()
LLVM_C_ABI LLVMOrcJITDylibRef LLVMOrcExecutionSessionGetJITDylibByName (LLVMOrcExecutionSessionRef ES, const char * Name)
Returns the JITDylib with the given name, or NULL if no such JITDylib exists.
Definition at line 623 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcExecutionSessionGetSymbolStringPool()
LLVM_C_ABI LLVMOrcSymbolStringPoolRef LLVMOrcExecutionSessionGetSymbolStringPool (LLVMOrcExecutionSessionRef ES)
Return a reference to the SymbolStringPool for an ExecutionSession.
Ownership of the pool remains with the ExecutionSession: The caller is not required to free the pool.
Definition at line 326 of file OrcV2CBindings.cpp.
References llvm::get(), llvm::unwrap(), and llvm::wrap().
LLVMOrcExecutionSessionIntern()
LLVM_C_ABI LLVMOrcSymbolStringPoolEntryRef LLVMOrcExecutionSessionIntern (LLVMOrcExecutionSessionRef ES, const char * Name)
Intern a string in the ExecutionSession's SymbolStringPool and return a reference to it.
This increments the ref-count of the pool entry, and the returned value should be released once the client is done with it by calling LLVMOrcReleaseSymbolStringPoolEntry.
Since strings are uniqued within the SymbolStringPool LLVMOrcSymbolStringPoolEntryRefs can be compared by value to test string equality.
Note that this function does not perform linker-mangling on the string.
Definition at line 336 of file OrcV2CBindings.cpp.
References llvm::orc::SymbolStringPoolEntryUnsafe::take(), llvm::unwrap(), and llvm::wrap().
LLVMOrcExecutionSessionLookup()
LLVM_C_ABI void LLVMOrcExecutionSessionLookup (LLVMOrcExecutionSessionRef ES, LLVMOrcLookupKind K, LLVMOrcCJITDylibSearchOrder SearchOrder, size_t SearchOrderSize, LLVMOrcCLookupSet Symbols, size_t SymbolsSize, LLVMOrcExecutionSessionLookupHandleResultFunction HandleResult, void * Ctx)
Look up symbols in an execution session.
This is a wrapper around the general ExecutionSession::lookup function.
The SearchOrder argument contains a list of (JITDylibs, JITDylibSearchFlags) pairs that describe the search order. The JITDylibs will be searched in the given order to try to find the symbols in the Symbols argument.
The Symbols argument should contain a null-terminated array of (SymbolStringPtr, SymbolLookupFlags) pairs describing the symbols to be searched for. This function takes ownership of the elements of the Symbols array. The Name fields of the Symbols elements are taken to have been retained by the client for this function. The client should not release the Name fields, but are still responsible for destroying the array itself.
The HandleResult function will be called once all searched for symbols have been found, or an error occurs. The HandleResult function will be passed an LLVMErrorRef indicating success or failure, and (on success) a null-terminated LLVMOrcCSymbolMapPairs array containing the function result, and the Ctx value passed to the lookup function.
The client is fully responsible for managing the lifetime of the Ctx object. A common idiom is to allocate the context prior to the lookup and deallocate it in the handler.
THIS API IS EXPERIMENTAL AND LIKELY TO CHANGE IN THE NEAR FUTURE!
Definition at line 340 of file OrcV2CBindings.cpp.
References llvm::orc::SymbolLookupSet::add(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::orc::SymbolStringPoolEntryUnsafe::from(), I, LLVMErrorSuccess, llvm::orc::NoDependenciesToRegister, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::orc::Ready, llvm::orc::Result, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::unwrap(), and llvm::wrap().
LLVMOrcExecutionSessionSetErrorReporter()
LLVM_C_ABI void LLVMOrcExecutionSessionSetErrorReporter (LLVMOrcExecutionSessionRef ES, LLVMOrcErrorReporterFunction ReportError, void * Ctx)
Attach a custom error reporter function to the ExecutionSession.
The error reporter will be called to deliver failure notices that can not be directly reported to a caller. For example, failure to resolve symbols in the JIT linker is typically reported via the error reporter (callers requesting definitions from the JIT will typically be delivered a FailureToMaterialize error instead).
Definition at line 318 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcIRTransformLayerEmit()
LLVM_C_ABI void LLVMOrcIRTransformLayerEmit (LLVMOrcIRTransformLayerRef IRTransformLayer, LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcThreadSafeModuleRef TSM)
Definition at line 596 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcIRTransformLayerSetTransform()
LLVM_C_ABI void LLVMOrcIRTransformLayerSetTransform (LLVMOrcIRTransformLayerRef IRTransformLayer, LLVMOrcIRTransformLayerTransformFunction TransformFunction, void * Ctx)
Set the transform function of the provided transform layer, passing through a pointer to user provided context.
Definition at line 841 of file OrcV2CBindings.cpp.
References assert(), LLVMOrcDisposeThreadSafeModule(), llvm::orc::Result, llvm::unwrap(), and llvm::wrap().
LLVMOrcJITDylibAddGenerator()
LLVM_C_ABI void LLVMOrcJITDylibAddGenerator (LLVMOrcJITDylibRef JD, LLVMOrcDefinitionGeneratorRef DG)
Add a DefinitionGenerator to the given JITDylib.
The JITDylib will take ownership of the given generator: The client is no longer responsible for managing its memory.
Definition at line 643 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcJITDylibClear()
LLVM_C_ABI LLVMErrorRef LLVMOrcJITDylibClear (LLVMOrcJITDylibRef JD)
Calls remove on all trackers associated with this JITDylib, see JITDylib::clear().
Definition at line 639 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcJITDylibCreateResourceTracker()
LLVM_C_ABI LLVMOrcResourceTrackerRef LLVMOrcJITDylibCreateResourceTracker (LLVMOrcJITDylibRef JD)
Return a reference to a newly created resource tracker associated with JD.
The tracker is returned with an initial ref-count of 1, and must be released with LLVMOrcReleaseResourceTracker when no longer needed.
Definition at line 389 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcJITDylibDefine()
LLVM_C_ABI LLVMErrorRef LLVMOrcJITDylibDefine (LLVMOrcJITDylibRef JD, LLVMOrcMaterializationUnitRef MU)
Add the given MaterializationUnit to the given JITDylib.
If this operation succeeds then JITDylib JD will take ownership of MU. If the operation fails then ownership remains with the caller who should call LLVMOrcDisposeMaterializationUnit to destroy it.
Definition at line 628 of file OrcV2CBindings.cpp.
References LLVMErrorSuccess, llvm::unwrap(), and llvm::wrap().
LLVMOrcJITDylibGetDefaultResourceTracker()
LLVM_C_ABI LLVMOrcResourceTrackerRef LLVMOrcJITDylibGetDefaultResourceTracker (LLVMOrcJITDylibRef JD)
Return a reference to the default resource tracker for the given JITDylib.
This operation will increase the retain count of the tracker: Clients should call LLVMOrcReleaseResourceTracker when the result is no longer needed.
Definition at line 397 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcJITTargetMachineBuilderCreateFromTargetMachine()
LLVM_C_ABI LLVMOrcJITTargetMachineBuilderRef LLVMOrcJITTargetMachineBuilderCreateFromTargetMachine (LLVMTargetMachineRef TM)
Create a JITTargetMachineBuilder from the given TargetMachine template.
This operation takes ownership of the given TargetMachine and destroys it before returing. The resulting JITTargetMachineBuilder is owned by the client and must be passed to a consuming operation (e.g. LLVMOrcLLJITBuilderSetJITTargetMachineBuilder) or disposed of by calling LLVMOrcDisposeJITTargetMachineBuilder.
Definition at line 777 of file OrcV2CBindings.cpp.
References LLVMDisposeTargetMachine(), llvm::unwrap(), and llvm::wrap().
LLVMOrcJITTargetMachineBuilderDetectHost()
LLVM_C_ABI LLVMErrorRef LLVMOrcJITTargetMachineBuilderDetectHost (LLVMOrcJITTargetMachineBuilderRef * Result)
Create a JITTargetMachineBuilder by detecting the host.
On success the client owns the resulting JITTargetMachineBuilder. It must be passed to a consuming operation (e.g. LLVMOrcLLJITBuilderSetJITTargetMachineBuilder) or disposed of by calling LLVMOrcDisposeJITTargetMachineBuilder.
Definition at line 762 of file OrcV2CBindings.cpp.
References assert(), llvm::orc::JITTargetMachineBuilder::detectHost(), LLVMErrorSuccess, llvm::orc::Result, and llvm::wrap().
LLVMOrcJITTargetMachineBuilderGetTargetTriple()
LLVM_C_ABI char * LLVMOrcJITTargetMachineBuilderGetTargetTriple (LLVMOrcJITTargetMachineBuilderRef JTMB)
Returns the target triple for the given JITTargetMachineBuilder as a string.
The caller owns the resulting string as must dispose of it by calling LLVMDisposeMessage
Definition at line 801 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcJITTargetMachineBuilderSetTargetTriple()
LLVM_C_ABI void LLVMOrcJITTargetMachineBuilderSetTargetTriple (LLVMOrcJITTargetMachineBuilderRef JTMB, const char * TargetTriple)
Sets the target triple for the given JITTargetMachineBuilder to the given string.
Definition at line 809 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcLazyReexports()
LLVM_C_ABI LLVMOrcMaterializationUnitRef LLVMOrcLazyReexports (LLVMOrcLazyCallThroughManagerRef LCTM, LLVMOrcIndirectStubsManagerRef ISM, LLVMOrcJITDylibRef SourceRef, LLVMOrcCSymbolAliasMapPairs CallableAliases, size_t NumPairs)
Create a MaterializationUnit to define lazy re-expots.
These are callable entry points that call through to the given symbols.
This function takes ownership of the CallableAliases array. The Name fields of the array elements are taken to have been retained for this function. This allows the following pattern...
size_t NumPairs; LLVMOrcCSymbolAliasMapPairs CallableAliases; – Build CallableAliases array – LLVMOrcMaterializationUnitRef MU = LLVMOrcLazyReexports(LCTM, ISM, JD, CallableAliases, NumPairs);
... without requiring cleanup of the elements of the CallableAliases array afterwards.
The client is still responsible for deleting the CallableAliases array itself.
If a client wishes to reuse elements of the CallableAliases array after this call they must explicitly retain each of the elements for themselves.
Definition at line 450 of file OrcV2CBindings.cpp.
References I, llvm::orc::lazyReexports(), llvm::release, llvm::unwrap(), and llvm::wrap().
LLVMOrcLookupStateContinueLookup()
LLVM_C_ABI void LLVMOrcLookupStateContinueLookup (LLVMOrcLookupStateRef S, LLVMErrorRef Err)
Continue a lookup that was suspended in a generator (see LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction).
Definition at line 655 of file OrcV2CBindings.cpp.
References llvm::orc::OrcV2CAPIHelper::resetLookupState(), and llvm::unwrap().
LLVMOrcMaterializationResponsibilityDefineMaterializing()
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityDefineMaterializing (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcCSymbolFlagsMapPairs Pairs, size_t NumPairs)
Attempt to claim responsibility for new definitions.
This method can be used to claim responsibility for symbols that are added to a materialization unit during the compilation process (e.g. literal pool symbols). Symbol linkage rules are the same as for symbols that are defined up front: duplicate strong definitions will result in errors. Duplicate weak definitions will be discarded (in which case they will not be added to this responsibility instance).
This method can be used by materialization units that want to add additional symbols at materialization time (e.g. stubs, compile callbacks, metadata)
Definition at line 556 of file OrcV2CBindings.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityDelegate()
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityDelegate (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcSymbolStringPoolEntryRef * Symbols, size_t NumSymbols, LLVMOrcMaterializationResponsibilityRef * Result)
Delegates responsibility for the given symbols to the returned materialization responsibility.
Useful for breaking up work between threads, or different kinds of materialization processes.
The caller retains responsibility of the the passed MaterializationResponsibility.
Definition at line 574 of file OrcV2CBindings.cpp.
References I, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), LLVMErrorSuccess, llvm::orc::Result, llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityFailMaterialization()
LLVM_C_ABI void LLVMOrcMaterializationResponsibilityFailMaterialization (LLVMOrcMaterializationResponsibilityRef MR)
Notify all not-yet-emitted covered by this MaterializationResponsibility instance that an error has occurred.
This will remove all symbols covered by this MaterializationResponsibility from the target JITDylib, and send an error to any queries waiting on these symbols.
Definition at line 591 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcMaterializationResponsibilityGetExecutionSession()
LLVM_C_ABI LLVMOrcExecutionSessionRef LLVMOrcMaterializationResponsibilityGetExecutionSession (LLVMOrcMaterializationResponsibilityRef MR)
Returns the ExecutionSession for this MaterializationResponsibility.
Definition at line 480 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityGetInitializerSymbol()
LLVM_C_ABI LLVMOrcSymbolStringPoolEntryRef LLVMOrcMaterializationResponsibilityGetInitializerSymbol (LLVMOrcMaterializationResponsibilityRef MR)
Returns the initialization pseudo-symbol, if any.
This symbol will also be present in the SymbolFlagsMap for this MaterializationResponsibility object.
The returned symbol is not retained over any mutating operation of the MaterializationResponsbility or beyond the lifetime thereof.
Definition at line 507 of file OrcV2CBindings.cpp.
References llvm::orc::SymbolStringPoolEntryUnsafe::from(), llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityGetRequestedSymbols()
LLVM_C_ABI LLVMOrcSymbolStringPoolEntryRef * LLVMOrcMaterializationResponsibilityGetRequestedSymbols (LLVMOrcMaterializationResponsibilityRef MR, size_t * NumSymbols)
Returns the names of any symbols covered by this MaterializationResponsibility object that have queries pending.
This information can be used to return responsibility for unrequested symbols back to the JITDylib via the delegate method.
Definition at line 514 of file OrcV2CBindings.cpp.
References llvm::orc::SymbolStringPoolEntryUnsafe::from(), I, llvm::orc::Result, llvm::safe_malloc(), llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityGetSymbols()
LLVM_C_ABI LLVMOrcCSymbolFlagsMapPairs LLVMOrcMaterializationResponsibilityGetSymbols (LLVMOrcMaterializationResponsibilityRef MR, size_t * NumPairs)
Returns the symbol flags map for this responsibility instance.
The length of the array is returned in NumPairs and the caller is responsible for the returned memory and needs to call LLVMOrcDisposeCSymbolFlagsMap.
To use the returned symbols beyond the livetime of the MaterializationResponsibility requires the caller to retain the symbols explicitly.
Definition at line 485 of file OrcV2CBindings.cpp.
References llvm::orc::SymbolStringPoolEntryUnsafe::from(), I, llvm::orc::Result, llvm::safe_malloc(), llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityGetTargetDylib()
LLVM_C_ABI LLVMOrcJITDylibRef LLVMOrcMaterializationResponsibilityGetTargetDylib (LLVMOrcMaterializationResponsibilityRef MR)
Returns the target JITDylib that these symbols are being materialized into.
Definition at line 474 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityNotifyEmitted()
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityNotifyEmitted (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcCSymbolDependenceGroup * SymbolDepGroups, size_t NumSymbolDepGroups)
Notifies the target JITDylib (and any pending queries on that JITDylib) that all symbols covered by this MaterializationResponsibility instance have been emitted.
This function takes ownership of the symbols in the Dependencies struct. This allows the following pattern...
LLVMOrcSymbolStringPoolEntryRef Names[] = {...}; LLVMOrcCDependenceMapPair Dependence = {JD, {Names, sizeof(Names)}} LLVMOrcMaterializationResponsibilityAddDependencies(JD, Name, &Dependence, 1);
... without requiring cleanup of the elements of the Names array afterwards.
The client is still responsible for deleting the Dependencies.Names arrays, and the Dependencies array itself.
This method will return an error if any symbols being resolved have been moved to the error state due to the failure of a dependency. If this method returns an error then clients should log it and call LLVMOrcMaterializationResponsibilityFailMaterialization. If no dependencies have been registered for the symbols covered by this MaterializationResponsibility then this method is guaranteed to return LLVMErrorSuccess.
Definition at line 541 of file OrcV2CBindings.cpp.
References I, llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityNotifyResolved()
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityNotifyResolved (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcCSymbolMapPairs Symbols, size_t NumPairs)
Notifies the target JITDylib that the given symbols have been resolved.
This will update the given symbols' addresses in the JITDylib, and notify any pending queries on the given symbols of their resolution. The given symbols must be ones covered by this MaterializationResponsibility instance. Individual calls to this method may resolve a subset of the symbols, but all symbols must have been resolved prior to calling emit.
This method will return an error if any symbols being resolved have been moved to the error state due to the failure of a dependency. If this method returns an error then clients should log it and call LLVMOrcMaterializationResponsibilityFailMaterialization. If no dependencies have been registered for the symbols covered by this MaterializationResponsibility then this method is guaranteed to return LLVMErrorSuccess.
Definition at line 534 of file OrcV2CBindings.cpp.
References SM(), llvm::unwrap(), and llvm::wrap().
LLVMOrcMaterializationResponsibilityReplace()
LLVM_C_ABI LLVMErrorRef LLVMOrcMaterializationResponsibilityReplace (LLVMOrcMaterializationResponsibilityRef MR, LLVMOrcMaterializationUnitRef MU)
Transfers responsibility to the given MaterializationUnit for all symbols defined by that MaterializationUnit.
This allows materializers to break up work based on run-time information (e.g. by introspecting which symbols have actually been looked up and materializing only those).
Definition at line 567 of file OrcV2CBindings.cpp.
References llvm::replace(), llvm::unwrap(), and llvm::wrap().
LLVMOrcObjectLayerAddObjectFile()
LLVM_C_ABI LLVMErrorRef LLVMOrcObjectLayerAddObjectFile (LLVMOrcObjectLayerRef ObjLayer, LLVMOrcJITDylibRef JD, LLVMMemoryBufferRef ObjBuffer)
Add an object to an ObjectLayer to the given JITDylib.
Adds a buffer representing an object file to the given JITDylib using the given ObjectLayer instance. This operation transfers ownership of the buffer to the ObjectLayer instance. The buffer should not be disposed of or referenced once this function returns.
Resources associated with the given object will be tracked by the given JITDylib's default ResourceTracker.
Definition at line 814 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcObjectLayerAddObjectFileWithRT()
LLVM_C_ABI LLVMErrorRef LLVMOrcObjectLayerAddObjectFileWithRT (LLVMOrcObjectLayerRef ObjLayer, LLVMOrcResourceTrackerRef RT, LLVMMemoryBufferRef ObjBuffer)
Add an object to an ObjectLayer using the given ResourceTracker.
Adds a buffer representing an object file to the given ResourceTracker's JITDylib using the given ObjectLayer instance. This operation transfers ownership of the buffer to the ObjectLayer instance. The buffer should not be disposed of or referenced once this function returns.
Resources associated with the given object will be tracked by ResourceTracker RT.
Definition at line 821 of file OrcV2CBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcObjectLayerEmit()
LLVM_C_ABI void LLVMOrcObjectLayerEmit (LLVMOrcObjectLayerRef ObjLayer, LLVMOrcMaterializationResponsibilityRef R, LLVMMemoryBufferRef ObjBuffer)
Emit an object buffer to an ObjectLayer.
Ownership of the responsibility object and object buffer pass to this function. The client is not responsible for cleanup.
Definition at line 829 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcObjectTransformLayerSetTransform()
LLVM_C_ABI void LLVMOrcObjectTransformLayerSetTransform (LLVMOrcObjectTransformLayerRef ObjTransformLayer, LLVMOrcObjectTransformLayerTransformFunction TransformFunction, void * Ctx)
Set the transform function on an LLVMOrcObjectTransformLayer.
Definition at line 861 of file OrcV2CBindings.cpp.
References assert(), llvm::unwrap(), and llvm::wrap().
LLVMOrcReleaseResourceTracker()
LLVM_C_ABI void LLVMOrcReleaseResourceTracker (LLVMOrcResourceTrackerRef RT)
Reduces the ref-count of a ResourceTracker.
Definition at line 403 of file OrcV2CBindings.cpp.
References llvm::ThreadSafeRefCountedBase< Derived >::Release(), and llvm::unwrap().
LLVMOrcReleaseSymbolStringPoolEntry()
LLVM_C_ABI void LLVMOrcReleaseSymbolStringPoolEntry (LLVMOrcSymbolStringPoolEntryRef S)
Reduces the ref-count for of a SymbolStringPool entry.
Definition at line 380 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcResourceTrackerRemove()
LLVM_C_ABI LLVMErrorRef LLVMOrcResourceTrackerRemove (LLVMOrcResourceTrackerRef RT)
Remove all resources associated with the given tracker.
See ResourceTracker::remove().
Definition at line 414 of file OrcV2CBindings.cpp.
References llvm::orc::ResourceTracker::remove(), llvm::unwrap(), and llvm::wrap().
LLVMOrcResourceTrackerTransferTo()
LLVM_C_ABI void LLVMOrcResourceTrackerTransferTo (LLVMOrcResourceTrackerRef SrcRT, LLVMOrcResourceTrackerRef DstRT)
Transfers tracking of all resources associated with resource tracker SrcRT to resource tracker DstRT.
Definition at line 408 of file OrcV2CBindings.cpp.
References llvm::orc::ResourceTracker::transferTo(), and llvm::unwrap().
LLVMOrcRetainSymbolStringPoolEntry()
LLVM_C_ABI void LLVMOrcRetainSymbolStringPoolEntry (LLVMOrcSymbolStringPoolEntryRef S)
Increments the ref-count for a SymbolStringPool entry.
Definition at line 376 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcSymbolStringPoolClearDeadEntries()
LLVM_C_ABI void LLVMOrcSymbolStringPoolClearDeadEntries (LLVMOrcSymbolStringPoolRef SSP)
Clear all unreferenced symbol string pool entries.
This can be called at any time to release unused entries in the ExecutionSession's string pool. Since it locks the pool (preventing interning of any new strings) it is recommended that it only be called infrequently, ideally when the caller has reason to believe that some entries will have become unreferenced, e.g. after removing a module or closing a JITDylib.
Definition at line 331 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcSymbolStringPoolEntryStr()
LLVM_C_ABI const char * LLVMOrcSymbolStringPoolEntryStr (LLVMOrcSymbolStringPoolEntryRef S)
Return the c-string for the given symbol.
This string will remain valid until the entry is freed (once all LLVMOrcSymbolStringPoolEntryRefs have been released).
Definition at line 384 of file OrcV2CBindings.cpp.
References llvm::unwrap().
LLVMOrcThreadSafeModuleWithModuleDo()
LLVM_C_ABI LLVMErrorRef LLVMOrcThreadSafeModuleWithModuleDo (LLVMOrcThreadSafeModuleRef TSM, LLVMOrcGenericIRModuleOperationFunction F, void * Ctx)
Apply the given function to the module contained in this ThreadSafeModule.
Definition at line 744 of file OrcV2CBindings.cpp.
References F, llvm::unwrap(), and llvm::wrap().