LLVM: Other Types
Other Types
LLVM-C: C interface to LLVM » Core » Types
Functions
LLVM_C_ABI LLVMTypeRef LLVMVoidTypeInContext (LLVMContextRef C)
Create a void type in a context.
LLVM_C_ABI LLVMTypeRef LLVMLabelTypeInContext (LLVMContextRef C)
Create a label type in a context.
LLVM_C_ABI LLVMTypeRef LLVMX86AMXTypeInContext (LLVMContextRef C)
Create a X86 AMX type in a context.
LLVM_C_ABI LLVMTypeRef LLVMTokenTypeInContext (LLVMContextRef C)
Create a token type in a context.
LLVM_C_ABI LLVMTypeRef LLVMMetadataTypeInContext (LLVMContextRef C)
Create a metadata type in a context.
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMVoidType(void), "Use of the global context is deprecated, use " "LLVMVoidTypeInContext instead")
These are similar to the above functions except they operate on the global context.
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMLabelType(void), "Use of the global context is deprecated, use " "LLVMLabelTypeInContext instead")
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMX86AMXType(void), "Use of the global context is deprecated, use " "LLVMX86AMXTypeInContext instead")
LLVM_C_ABI LLVMTypeRef LLVMTargetExtTypeInContext (LLVMContextRef C, const char *Name, LLVMTypeRef *TypeParams, unsigned TypeParamCount, unsigned *IntParams, unsigned IntParamCount)
Create a target extension type in LLVM context.
LLVM_C_ABI const char * LLVMGetTargetExtTypeName (LLVMTypeRef TargetExtTy)
Obtain the name for this target extension type.
LLVM_C_ABI unsigned LLVMGetTargetExtTypeNumTypeParams (LLVMTypeRef TargetExtTy)
Obtain the number of type parameters for this target extension type.
LLVM_C_ABI LLVMTypeRef LLVMGetTargetExtTypeTypeParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the type parameter at the given index for the target extension type.
LLVM_C_ABI unsigned LLVMGetTargetExtTypeNumIntParams (LLVMTypeRef TargetExtTy)
Obtain the number of int parameters for this target extension type.
LLVM_C_ABI unsigned LLVMGetTargetExtTypeIntParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the int parameter at the given index for the target extension type.
Detailed Description
Function Documentation
LLVM_ATTRIBUTE_C_DEPRECATED() [1/3]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMLabelTypevoid, "Use of the global context is deprecated, use " "LLVMLabelTypeInContext instead")
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [2/3]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMVoidTypevoid, "Use of the global context is deprecated, use " "LLVMVoidTypeInContext instead")
These are similar to the above functions except they operate on the global context.
References LLVM_C_ABI.
LLVM_ATTRIBUTE_C_DEPRECATED() [3/3]
LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED (LLVMTypeRef LLVMX86AMXTypevoid, "Use of the global context is deprecated, use " "LLVMX86AMXTypeInContext instead")
References C(), and LLVM_C_ABI.
LLVMGetTargetExtTypeIntParam()
LLVM_C_ABI unsigned LLVMGetTargetExtTypeIntParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the int parameter at the given index for the target extension type.
See also
llvm::TargetExtType::getIntParameter()
Definition at line 997 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeName()
LLVM_C_ABI const char * LLVMGetTargetExtTypeName (LLVMTypeRef TargetExtTy)
Obtain the name for this target extension type.
See also
llvm::TargetExtType::getName()
Definition at line 976 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeNumIntParams()
LLVM_C_ABI unsigned LLVMGetTargetExtTypeNumIntParams (LLVMTypeRef TargetExtTy)
Obtain the number of int parameters for this target extension type.
See also
llvm::TargetExtType::getNumIntParameters()
Definition at line 992 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeNumTypeParams()
LLVM_C_ABI unsigned LLVMGetTargetExtTypeNumTypeParams (LLVMTypeRef TargetExtTy)
Obtain the number of type parameters for this target extension type.
See also
llvm::TargetExtType::getNumTypeParameters()
Definition at line 981 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeTypeParam()
LLVM_C_ABI LLVMTypeRef LLVMGetTargetExtTypeTypeParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the type parameter at the given index for the target extension type.
See also
llvm::TargetExtType::getTypeParameter()
Definition at line 986 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMLabelTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMLabelTypeInContext (LLVMContextRef C)
Create a label type in a context.
Definition at line 948 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getLabelTy(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMLabelType().
LLVMMetadataTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMMetadataTypeInContext (LLVMContextRef C)
Create a metadata type in a context.
Definition at line 954 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getMetadataTy(), llvm::unwrap(), and llvm::wrap().
LLVMTargetExtTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMTargetExtTypeInContext (LLVMContextRef C, const char * Name, LLVMTypeRef * TypeParams, unsigned TypeParamCount, unsigned * IntParams, unsigned IntParamCount)
Create a target extension type in LLVM context.
Definition at line 965 of file Core.cpp.
References llvm::CallingConv::C, llvm::TargetExtType::get(), llvm::unwrap(), and llvm::wrap().
LLVMTokenTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMTokenTypeInContext (LLVMContextRef C)
Create a token type in a context.
Definition at line 951 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getTokenTy(), llvm::unwrap(), and llvm::wrap().
LLVMVoidTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMVoidTypeInContext (LLVMContextRef C)
Create a void type in a context.
Definition at line 945 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getVoidTy(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMVoidType().
LLVMX86AMXTypeInContext()
LLVM_C_ABI LLVMTypeRef LLVMX86AMXTypeInContext (LLVMContextRef C)
Create a X86 AMX type in a context.
Definition at line 736 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getX86_AMXTy(), and llvm::unwrap().
Referenced by LLVMX86AMXType().