LLVM: Linker
Linker
LLVM-C: C interface to LLVM » Core
Enumerations
enum LLVMLinkerMode { LLVMLinkerDestroySource = 0 , LLVMLinkerPreserveSource_Removed = 1 }
Functions
LLVM_C_ABI LLVMBool LLVMLinkModules2 (LLVMModuleRef Dest, LLVMModuleRef Src)
Detailed Description
Enumeration Type Documentation
LLVMLinkerMode
enum LLVMLinkerMode
Enumerator
LLVMLinkerDestroySource
LLVMLinkerPreserveSource_Removed
Definition at line 31 of file Linker.h.
Function Documentation
LLVMLinkModules2()
LLVM_C_ABI LLVMBool LLVMLinkModules2 (LLVMModuleRef Dest, LLVMModuleRef Src)
Definition at line 651 of file LinkModules.cpp.
References D(), llvm::Linker::linkModules(), and llvm::unwrap().