LLVM: Memory Buffers
Memory Buffers
LLVM-C: C interface to LLVM
Functions
LLVM_C_ABI LLVMBool LLVMCreateMemoryBufferWithContentsOfFile (const char *Path, LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVM_C_ABI LLVMBool LLVMCreateMemoryBufferWithSTDIN (LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVM_C_ABI LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange (const char *InputData, size_t InputDataLength, const char *BufferName, LLVMBool RequiresNullTerminator)
LLVM_C_ABI LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy (const char *InputData, size_t InputDataLength, const char *BufferName)
LLVM_C_ABI const char * LLVMGetBufferStart (LLVMMemoryBufferRef MemBuf)
LLVM_C_ABI size_t LLVMGetBufferSize (LLVMMemoryBufferRef MemBuf)
LLVM_C_ABI void LLVMDisposeMemoryBuffer (LLVMMemoryBufferRef MemBuf)
Detailed Description
Function Documentation
LLVMCreateMemoryBufferWithContentsOfFile()
LLVM_C_ABI LLVMBool LLVMCreateMemoryBufferWithContentsOfFile (const char * Path, LLVMMemoryBufferRef * OutMemBuf, char ** OutMessage)
Definition at line 4583 of file Core.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), and llvm::wrap().
LLVMCreateMemoryBufferWithMemoryRange()
LLVM_C_ABI LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange (const char * InputData, size_t InputDataLength, const char * BufferName, LLVMBool RequiresNullTerminator)
Definition at line 4608 of file Core.cpp.
References llvm::MemoryBuffer::getMemBuffer(), llvm::release, and llvm::wrap().
LLVMCreateMemoryBufferWithMemoryRangeCopy()
LLVM_C_ABI LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy (const char * InputData, size_t InputDataLength, const char * BufferName)
Definition at line 4619 of file Core.cpp.
References llvm::MemoryBuffer::getMemBufferCopy(), llvm::release, and llvm::wrap().
Referenced by LLVMTargetMachineEmitToMemoryBuffer().
LLVMCreateMemoryBufferWithSTDIN()
LLVM_C_ABI LLVMBool LLVMCreateMemoryBufferWithSTDIN (LLVMMemoryBufferRef * OutMemBuf, char ** OutMessage)
Definition at line 4597 of file Core.cpp.
References llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getSTDIN(), and llvm::wrap().
LLVMDisposeMemoryBuffer()
LLVM_C_ABI void LLVMDisposeMemoryBuffer (LLVMMemoryBufferRef MemBuf)
Definition at line 4637 of file Core.cpp.
References llvm::unwrap().
LLVMGetBufferSize()
LLVM_C_ABI size_t LLVMGetBufferSize (LLVMMemoryBufferRef MemBuf)
Definition at line 4633 of file Core.cpp.
References llvm::unwrap().
LLVMGetBufferStart()
LLVM_C_ABI const char * LLVMGetBufferStart (LLVMMemoryBufferRef MemBuf)
Definition at line 4629 of file Core.cpp.
References llvm::unwrap().