LLVM: Scalar constants
Scalar constants
LLVM-C: C interface to LLVM » Core » Values » Constants
Functions in this group model LLVMValueRef instances that correspond to constants referring to scalar types.
Functions
LLVM_C_ABI LLVMValueRef LLVMConstInt (LLVMTypeRef IntTy, unsigned long long N, LLVMBool SignExtend)
Obtain a constant value for an integer type.
LLVM_C_ABI LLVMValueRef LLVMConstIntOfArbitraryPrecision (LLVMTypeRef IntTy, unsigned NumWords, const uint64_t Words[])
Obtain a constant value for an integer of arbitrary precision.
LLVM_C_ABI LLVMValueRef LLVMConstIntOfString (LLVMTypeRef IntTy, const char *Text, uint8_t Radix)
Obtain a constant value for an integer parsed from a string.
LLVM_C_ABI LLVMValueRef LLVMConstIntOfStringAndSize (LLVMTypeRef IntTy, const char *Text, unsigned SLen, uint8_t Radix)
Obtain a constant value for an integer parsed from a string with specified length.
LLVM_C_ABI LLVMValueRef LLVMConstReal (LLVMTypeRef RealTy, double N)
Obtain a constant value referring to a double floating point value.
LLVM_C_ABI LLVMValueRef LLVMConstRealOfString (LLVMTypeRef RealTy, const char *Text)
Obtain a constant for a floating point value parsed from a string.
LLVM_C_ABI LLVMValueRef LLVMConstRealOfStringAndSize (LLVMTypeRef RealTy, const char *Text, unsigned SLen)
Obtain a constant for a floating point value parsed from a string.
LLVM_C_ABI LLVMValueRef LLVMConstFPFromBits (LLVMTypeRef Ty, const uint64_t N[])
Obtain a constant for a floating point value from array of 64 bit values.
LLVM_C_ABI unsigned long long LLVMConstIntGetZExtValue (LLVMValueRef ConstantVal)
Obtain the zero extended value for an integer constant value.
LLVM_C_ABI long long LLVMConstIntGetSExtValue (LLVMValueRef ConstantVal)
Obtain the sign extended value for an integer constant value.
LLVM_C_ABI double LLVMConstRealGetDouble (LLVMValueRef ConstantVal, LLVMBool *losesInfo)
Obtain the double value for an floating point constant value.
Detailed Description
Functions in this group model LLVMValueRef instances that correspond to constants referring to scalar types.
For integer types, the LLVMTypeRef parameter should correspond to a llvm::IntegerType instance and the returned LLVMValueRef will correspond to a llvm::ConstantInt.
For floating point types, the LLVMTypeRef returned corresponds to a llvm::ConstantFP.
Function Documentation
LLVMConstFPFromBits()
LLVM_C_ABI LLVMValueRef LLVMConstFPFromBits (LLVMTypeRef Ty, const uint64_t N[])
Obtain a constant for a floating point value from array of 64 bit values.
The length of the array N must be ceildiv(bits, 64), where bits is the scalar size in bits of the floating-point type.
Definition at line 1580 of file Core.cpp.
References llvm::divideCeil(), N, T, llvm::unwrap(), and llvm::wrap().
LLVMConstInt()
LLVM_C_ABI LLVMValueRef LLVMConstInt (LLVMTypeRef IntTy, unsigned long long N, LLVMBool SignExtend)
Obtain a constant value for an integer type.
The returned value corresponds to a llvm::ConstantInt.
See also
llvm::ConstantInt::get()
Parameters
IntTy Integer type to obtain value of.
N The value the returned instance should refer to.
SignExtend Whether to sign extend the produced value.
Definition at line 1542 of file Core.cpp.
References N, llvm::unwrap(), and llvm::wrap().
LLVMConstIntGetSExtValue()
LLVM_C_ABI long long LLVMConstIntGetSExtValue (LLVMValueRef ConstantVal)
Obtain the sign extended value for an integer constant value.
See also
llvm::ConstantInt::getSExtValue()
Definition at line 1592 of file Core.cpp.
References llvm::unwrap().
LLVMConstIntGetZExtValue()
LLVM_C_ABI unsigned long long LLVMConstIntGetZExtValue (LLVMValueRef ConstantVal)
Obtain the zero extended value for an integer constant value.
See also
llvm::ConstantInt::getZExtValue()
Definition at line 1588 of file Core.cpp.
References llvm::unwrap().
LLVMConstIntOfArbitraryPrecision()
LLVM_C_ABI LLVMValueRef LLVMConstIntOfArbitraryPrecision (LLVMTypeRef IntTy, unsigned NumWords, const uint64_t Words[])
Obtain a constant value for an integer of arbitrary precision.
See also
llvm::ConstantInt::get()
Definition at line 1547 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMConstIntOfString()
LLVM_C_ABI LLVMValueRef LLVMConstIntOfString (LLVMTypeRef IntTy, const char * Text, uint8_t Radix)
Obtain a constant value for an integer parsed from a string.
A similar API, LLVMConstIntOfStringAndSize is also available. If the string's length is available, it is preferred to call that function instead.
See also
llvm::ConstantInt::get()
References LLVM_C_ABI.
LLVMConstIntOfStringAndSize()
LLVM_C_ABI LLVMValueRef LLVMConstIntOfStringAndSize (LLVMTypeRef IntTy, const char * Text, unsigned SLen, uint8_t Radix)
Obtain a constant value for an integer parsed from a string with specified length.
See also
llvm::ConstantInt::get()
References LLVM_C_ABI, and N.
LLVMConstReal()
LLVM_C_ABI LLVMValueRef LLVMConstReal (LLVMTypeRef RealTy, double N)
Obtain a constant value referring to a double floating point value.
Definition at line 1567 of file Core.cpp.
References N, llvm::unwrap(), and llvm::wrap().
LLVMConstRealGetDouble()
LLVM_C_ABI double LLVMConstRealGetDouble (LLVMValueRef ConstantVal, LLVMBool * losesInfo)
Obtain the double value for an floating point constant value.
losesInfo indicates if some precision was lost in the conversion.
See also
llvm::ConstantFP::getDoubleValue
Definition at line 1596 of file Core.cpp.
References llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::Value::getType(), llvm::ConstantFP::getValueAPF(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::rmNearestTiesToEven, and llvm::unwrap().
LLVMConstRealOfString()
LLVM_C_ABI LLVMValueRef LLVMConstRealOfString (LLVMTypeRef RealTy, const char * Text)
Obtain a constant for a floating point value parsed from a string.
A similar API, LLVMConstRealOfStringAndSize is also available. It should be used if the input string's length is known.
Definition at line 1571 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMConstRealOfStringAndSize()
LLVM_C_ABI LLVMValueRef LLVMConstRealOfStringAndSize (LLVMTypeRef RealTy, const char * Text, unsigned SLen)
Obtain a constant for a floating point value parsed from a string.
References C(), LLVM_C_ABI, and N.