LLVM: lib/DebugInfo/GSYM/GsymContext.cpp File Reference
GsymContext.cpp File Reference
#include "llvm/DebugInfo/GSYM/GsymContext.h"
#include "llvm/DebugInfo/GSYM/GsymReader.h"
#include "llvm/Support/Path.h"
Functions
static bool fillLineInfoFromLocation (const SourceLocation &Location, DILineInfoSpecifier Specifier, DILineInfo &LineInfo)
Function Documentation
fillLineInfoFromLocation()
bool fillLineInfoFromLocation (const SourceLocation & Location, DILineInfoSpecifier Specifier, DILineInfo & LineInfo) static
Definition at line 23 of file GsymContext.cpp.
References llvm::DILineInfoSpecifier::AbsoluteFilePath, llvm::sys::path::append(), llvm::DILineInfo::BadString, llvm::DILineInfoSpecifier::BaseNameOnly, llvm::None, llvm::DILineInfoSpecifier::RawValue, and llvm::DILineInfoSpecifier::RelativeFilePath.
Referenced by llvm::gsym::GsymContext::getInliningInfoForAddress(), and llvm::gsym::GsymContext::getLineInfoForAddress().