LLVM: lib/Target/Hexagon/HexagonVectorCombine.cpp File Reference
HexagonVectorCombine.cpp File Reference
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumeBundleQueries.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/InstSimplifyFolder.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsHexagon.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Utils/Local.h"
#include "Hexagon.h"
#include "HexagonSubtarget.h"
#include "HexagonTargetMachine.h"
#include <algorithm>
#include <deque>
#include <map>
#include <optional>
#include <set>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "hexagon-vc"
#define DEFAULT_HVX_VTCM_PAGE_SIZE 131072
#define CallBuilder(B, F)
Functions
static Align effectiveAlignForValueTy (const DataLayout &DL, Type *ValTy, int Requested)
Instruction * locateDestination (Instruction *In, HvxIdioms::DstQualifier &Qual)
bool isArithmetic (unsigned Opc)
Value * getPointer (Value *Ptr)
static Instruction * selectDestination (Instruction *In, HvxIdioms::DstQualifier &Qual)
GetElementPtrInst * locateGepFromIntrinsic (Instruction *In)
static Value * locateAddressFromIntrinsic (Instruction *In)
static Type * getIndexType (Value *In)
static Value * locateIndexesFromGEP (Value *In)
static Value * locateIndexesFromIntrinsic (Instruction *In)
Value * getReinterpretiveCast_i16_to_i32 (const HexagonVectorCombine &HVC, IRBuilderBase &Builder, LLVMContext &Ctx, Value *I)
Value * getReinterpretiveCast_i8_to_i32 (const HexagonVectorCombine &HVC, IRBuilderBase &Builder, LLVMContext &Ctx, Value *I)
Value * get_i32_Mask (const HexagonVectorCombine &HVC, IRBuilderBase &Builder, LLVMContext &Ctx, unsigned int pattern)
INITIALIZE_PASS_BEGIN (HexagonVectorCombineLegacy, DEBUG_TYPE, "Hexagon Vector Combine", false, false) INITIALIZE_PASS_END(HexagonVectorCombineLegacy
Variables
DEBUG_TYPE
Hexagon Vector Combine
Hexagon Vector false
Macro Definition Documentation
CallBuilder
#define CallBuilder (B, F)
Value:
[&](auto &B_) {                                                              \
  Value *V = B_.F;                                                           \
  if (auto *I = dyn_cast<Instruction>(V))                                    \
    B_.ToErase.push_back(I);                                                 \
  return V;                                                                  \
}(B)
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-vc"
Definition at line 60 of file HexagonVectorCombine.cpp.
DEFAULT_HVX_VTCM_PAGE_SIZE
#define DEFAULT_HVX_VTCM_PAGE_SIZE 131072
Definition at line 65 of file HexagonVectorCombine.cpp.
Function Documentation
effectiveAlignForValueTy()
Align effectiveAlignForValueTy (const DataLayout & DL, Type * ValTy, int Requested) static
Definition at line 676 of file HexagonVectorCombine.cpp.
References DL.
get_i32_Mask()
Value * get_i32_Mask (const HexagonVectorCombine & HVC, IRBuilderBase & Builder, LLVMContext & Ctx, unsigned int pattern) inline
Definition at line 2170 of file HexagonVectorCombine.cpp.
References llvm::HexagonSubtarget::getIntrinsicId().
getIndexType()
Type * getIndexType (Value * In) static
Definition at line 2079 of file HexagonVectorCombine.cpp.
References llvm::dyn_cast(), llvm::getLoadStoreType(), II, and llvm::isa().
getPointer()
Value * getPointer (Value * Ptr) inline
Definition at line 1928 of file HexagonVectorCombine.cpp.
References assert(), llvm::dyn_cast(), llvm::getLoadStorePointerOperand(), II, and llvm::isa().
Referenced by llvm::GlobalsAAResult::FunctionInfo::FunctionInfo(), llvm::sandboxir::ConstantPtrAuth::getPointer(), LLVMGetConstantPtrAuthPointer(), and locateDestination().
getReinterpretiveCast_i16_to_i32()
Value * getReinterpretiveCast_i16_to_i32 (const HexagonVectorCombine & HVC, IRBuilderBase & Builder, LLVMContext & Ctx, Value * I) inline
Definition at line 2140 of file HexagonVectorCombine.cpp.
References assert(), llvm::ConstantDataVector::get(), and I.
getReinterpretiveCast_i8_to_i32()
Value * getReinterpretiveCast_i8_to_i32 (const HexagonVectorCombine & HVC, IRBuilderBase & Builder, LLVMContext & Ctx, Value * I) inline
Definition at line 2155 of file HexagonVectorCombine.cpp.
References assert(), llvm::ConstantDataVector::get(), and I.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (HexagonVectorCombineLegacy , DEBUG_TYPE , "Hexagon Vector Combine" , false , false)
References DEBUG_TYPE, and INITIALIZE_PASS_DEPENDENCY.
isArithmetic()
bool isArithmetic (unsigned Opc) inline
Definition at line 1910 of file HexagonVectorCombine.cpp.
References Opc.
Referenced by selectDestination().
locateAddressFromIntrinsic()
Value * locateAddressFromIntrinsic (Instruction * In) static
Definition at line 2033 of file HexagonVectorCombine.cpp.
References llvm::dbgs(), llvm::dyn_cast(), llvm::GetElementPtrInst::getPointerOperand(), II, llvm::isa(), LLVM_DEBUG, locateAddressFromIntrinsic(), and locateGepFromIntrinsic().
Referenced by locateAddressFromIntrinsic().
locateDestination()
Instruction * locateDestination (Instruction * In, HvxIdioms::DstQualifier & Qual)
Definition at line 1994 of file HexagonVectorCombine.cpp.
References llvm::dyn_cast(), getPointer(), I, selectDestination(), and Users.
Referenced by selectDestination().
locateGepFromIntrinsic()
GetElementPtrInst * locateGepFromIntrinsic (Instruction * In) inline
Definition at line 2016 of file HexagonVectorCombine.cpp.
References assert(), llvm::dyn_cast(), llvm::IntrinsicInst::getIntrinsicID(), and llvm::User::getOperand().
Referenced by locateAddressFromIntrinsic(), and locateIndexesFromIntrinsic().
locateIndexesFromGEP()
Value * locateIndexesFromGEP (Value * In) static
Definition at line 2095 of file HexagonVectorCombine.cpp.
References llvm::dyn_cast(), II, llvm::isa(), and locateIndexesFromGEP().
Referenced by locateIndexesFromGEP(), and locateIndexesFromIntrinsic().
locateIndexesFromIntrinsic()
Value * locateIndexesFromIntrinsic (Instruction * In) static
Definition at line 2123 of file HexagonVectorCombine.cpp.
References llvm::dbgs(), llvm::User::getOperand(), LLVM_DEBUG, locateGepFromIntrinsic(), and locateIndexesFromGEP().
selectDestination()
Instruction * selectDestination (Instruction * In, HvxIdioms::DstQualifier & Qual) static
Definition at line 1941 of file HexagonVectorCombine.cpp.
References llvm::dbgs(), llvm::dyn_cast(), II, llvm::isa(), isArithmetic(), LLVM_DEBUG, and locateDestination().
Referenced by locateDestination().
Variable Documentation
Combine
Hexagon Vector Combine
Definition at line 4098 of file HexagonVectorCombine.cpp.
DEBUG_TYPE
DEBUG_TYPE
Definition at line 4097 of file HexagonVectorCombine.cpp.
false
Hexagon Vector false
Definition at line 4098 of file HexagonVectorCombine.cpp.