LLVM: lib/Target/Hexagon/HexagonISelLowering.cpp File Reference
HexagonISelLowering.cpp File Reference
#include "HexagonISelLowering.h"
#include "Hexagon.h"
#include "HexagonMachineFunctionInfo.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "HexagonTargetMachine.h"
#include "HexagonTargetObjectFile.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/TargetCallingConv.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsHexagon.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <limits>
#include <utility>
#include "HexagonGenCallingConv.inc"
Macros
#define DEBUG_TYPE "hexagon-lowering"
Functions
static bool CC_SkipOdd (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG &DAG, const SDLoc &dl)
CreateCopyOfByValArgument - Make a copy of an aggregate at address specified by "Src" to address "Dst" of size "Size".
static bool isBrevLdIntrinsic (const Value *Inst)
static Value * getBrevLdObject (Value *V)
static Value * returnEdge (const PHINode *PN, Value *IntrBaseVal)
static Value * getUnderLyingObjectForBrevLdIntr (Value *V)
Variables
static cl::opt< bool > EmitJumpTables ("hexagon-emit-jump-tables", cl::init(true), cl::Hidden, cl::desc("Control jump table emission on Hexagon target"))
static cl::opt< bool > EnableHexSDNodeSched ("enable-hexagon-sdnode-sched", cl::Hidden, cl::desc("Enable Hexagon SDNode scheduling"))
static cl::opt< int > MinimumJumpTables ("minimum-jump-tables", cl::Hidden, cl::init(5), cl::desc("Set minimum jump tables"))
static cl::opt< bool > ConstantLoadsToImm ("constant-loads-to-imm", cl::Hidden, cl::init(true), cl::desc("Convert constant loads to immediate values."))
static cl::opt< bool > AlignLoads ("hexagon-align-loads", cl::Hidden, cl::init(false), cl::desc("Rewrite unaligned loads as a pair of aligned loads"))
static cl::opt< bool > DisableArgsMinAlignment ("hexagon-disable-args-min-alignment", cl::Hidden, cl::init(false), cl::desc("Disable minimum alignment of 1 for " "arguments passed by value on stack"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-lowering"
Definition at line 66 of file HexagonISelLowering.cpp.
Function Documentation
CC_SkipOdd()
bool CC_SkipOdd (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 96 of file HexagonISelLowering.cpp.
CreateCopyOfByValArgument()
SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG & DAG, const SDLoc & dl) static
CreateCopyOfByValArgument - Make a copy of an aggregate at address specified by "Src" to address "Dst" of size "Size".
Alignment information is specified by the specific parameter attribute. The copy will be passed as a byval function parameter. Sometimes what we are copying is the end of a larger object, the part that does not fit in registers.
Definition at line 214 of file HexagonISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), and llvm::SelectionDAG::getMemcpy().
Referenced by llvm::HexagonTargetLowering::LowerCall().
getBrevLdObject()
Value * getBrevLdObject (Value * V) static
Definition at line 1968 of file HexagonISelLowering.cpp.
References llvm::cast(), llvm::Operator::getOpcode(), llvm::isa(), and isBrevLdIntrinsic().
Referenced by getUnderLyingObjectForBrevLdIntr(), and returnEdge().
getUnderLyingObjectForBrevLdIntr()
Value * getUnderLyingObjectForBrevLdIntr (Value * V) static
Definition at line 2010 of file HexagonISelLowering.cpp.
References llvm::dyn_cast(), getBrevLdObject(), and returnEdge().
Referenced by llvm::HexagonTargetLowering::getTgtMemIntrinsic().
isBrevLdIntrinsic()
bool isBrevLdIntrinsic (const Value * Inst) static
Definition at line 1955 of file HexagonISelLowering.cpp.
References llvm::cast().
Referenced by getBrevLdObject().
returnEdge()
Value * returnEdge (const PHINode * PN, Value * IntrBaseVal) static
Definition at line 1980 of file HexagonISelLowering.cpp.
References assert(), getBrevLdObject(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), and llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent().
Referenced by getUnderLyingObjectForBrevLdIntr().
Variable Documentation
AlignLoads
cl::opt< bool > AlignLoads("hexagon-align-loads", cl::Hidden, cl::init(false), cl::desc("Rewrite unaligned loads as a pair of aligned loads")) ("hexagon-align-loads" , cl::Hidden , cl::init(false) , cl::desc("Rewrite unaligned loads as a pair of aligned loads")) static
Referenced by llvm::HexagonTargetLowering::LowerUnalignedLoad().
ConstantLoadsToImm
cl::opt< bool > ConstantLoadsToImm("constant-loads-to-imm", cl::Hidden, cl::init(true), cl::desc("Convert constant loads to immediate values.")) ("constant-loads-to-imm" , cl::Hidden , cl::init(true) , cl::desc("Convert constant loads to immediate values.")) static
Referenced by llvm::HexagonTargetLowering::shouldConvertConstantLoadToIntImm().
DisableArgsMinAlignment
cl::opt< bool > DisableArgsMinAlignment("hexagon-disable-args-min-alignment", cl::Hidden, cl::init(false), cl::desc("Disable minimum alignment of 1 for " "arguments passed by value on stack")) ("hexagon-disable-args-min-alignment" , cl::Hidden , cl::init(false) , cl::desc("Disable minimum alignment of 1 for " "arguments passed by value on stack")) static
Referenced by llvm::HexagonTargetLowering::LowerCall(), and llvm::HexagonTargetLowering::LowerFormalArguments().
EmitJumpTables
cl::opt< bool > EmitJumpTables("hexagon-emit-jump-tables", cl::init(true), cl::Hidden, cl::desc("Control jump table emission on Hexagon target")) ("hexagon-emit-jump-tables" , cl::init(true) , cl::Hidden , cl::desc("Control jump table emission on Hexagon target")) static
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
EnableHexSDNodeSched
cl::opt< bool > EnableHexSDNodeSched("enable-hexagon-sdnode-sched", cl::Hidden, cl::desc("Enable Hexagon SDNode scheduling")) ("enable-hexagon-sdnode-sched" , cl::Hidden , cl::desc("Enable Hexagon SDNode scheduling")) static
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
MinimumJumpTables
cl::opt< int > MinimumJumpTables("minimum-jump-tables", cl::Hidden, cl::init(5), cl::desc("Set minimum jump tables")) ("minimum-jump-tables" , cl::Hidden , cl::init(5) , cl::desc("Set minimum jump tables")) static
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().