LLVM: lib/Transforms/HipStdPar/HipStdPar.cpp File Reference
HipStdPar.cpp File Reference
#include "llvm/Transforms/HipStdPar/HipStdPar.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <cassert>
#include <string>
#include <utility>
Functions
template<typename T>
static void eraseFromModule (T &ToErase)
static bool checkIfSupported (GlobalVariable &G)
static void clearModule (Module &M)
static SmallVector< std::reference_wrapper< Use > > collectIndirectableUses (GlobalVariable *G)
static GlobalVariable * getGlobalForName (GlobalVariable *G)
static GlobalVariable * getIndirectionGlobal (Module *M)
static Constant * appendIndirectedGlobal (const GlobalVariable *IndirectionTable, SmallVector< Constant * > &SymbolIndirections, GlobalVariable *ToIndirect)
static void fillIndirectionTable (GlobalVariable *IndirectionTable, SmallVector< Constant * > Indirections)
static void replaceWithIndirectUse (const Use &U, const GlobalVariable *G, Constant *IndirectedG)
static bool isValidIndirectionTable (GlobalVariable *IndirectionTable)
static void indirectGlobals (GlobalVariable *IndirectionTable, SmallVector< GlobalVariable * > ToIndirect)
static void maybeHandleGlobals (Module &M)
template<unsigned N>
static void removeUnreachableFunctions (const SmallPtrSet< const Function *, N > &Reachable, Module &M)
static bool isAcceleratorExecutionRoot (const Function *F)
static bool checkIfSupported (const Function *F, const CallBase *CB)
Variables
static constexpr std::pair< StringLiteral, StringLiteral > ReplaceMap []
static constexpr std::pair< StringLiteral, StringLiteral > HiddenMap []
static constexpr std::pair< StringLiteral, StringLiteral > MathLibToHipStdPar []
Function Documentation
appendIndirectedGlobal()
Constant * appendIndirectedGlobal (const GlobalVariable * IndirectionTable, SmallVector< Constant * > & SymbolIndirections, GlobalVariable * ToIndirect) static
Definition at line 178 of file HipStdPar.cpp.
References llvm::cast(), llvm::ConstantStruct::get(), llvm::ConstantExpr::getAddrSpaceCast(), getGlobalForName(), getIndirectionGlobal(), llvm::GlobalValue::getParent(), llvm::GlobalValue::getValueType(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by indirectGlobals().
checkIfSupported() [1/2]
bool checkIfSupported (const Function * F, const CallBase * CB) inline static
Definition at line 372 of file HipStdPar.cpp.
References llvm::cast(), llvm::DS_Error, F, llvm::CallBase::getArgOperand(), llvm::Instruction::getDebugLoc(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), N, and llvm::StringRef::npos.
checkIfSupported() [2/2]
bool checkIfSupported (GlobalVariable & G) static
Definition at line 78 of file HipStdPar.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::cast(), llvm::DS_Error, llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), G, I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::isa(), and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
Referenced by maybeHandleGlobals(), and llvm::HipStdParAcceleratorCodeSelectionPass::run().
clearModule()
void clearModule (Module & M) inline static
Definition at line 118 of file HipStdPar.cpp.
References eraseFromModule().
Referenced by maybeHandleGlobals(), and llvm::HipStdParAcceleratorCodeSelectionPass::run().
collectIndirectableUses()
SmallVector< std::reference_wrapper< Use > > collectIndirectableUses (GlobalVariable * G) static
Definition at line 130 of file HipStdPar.cpp.
References G, llvm::isa(), llvm::transform(), and Uses.
Referenced by indirectGlobals().
eraseFromModule()
template<typename T> void eraseFromModule (T & ToErase) inline static
Definition at line 73 of file HipStdPar.cpp.
References llvm::PoisonValue::get(), and T.
Referenced by clearModule(), indirectGlobals(), removeUnreachableFunctions(), and llvm::HipStdParAllocationInterpositionPass::run().
fillIndirectionTable()
void fillIndirectionTable (GlobalVariable * IndirectionTable, SmallVector< Constant * > Indirections) static
Definition at line 198 of file HipStdPar.cpp.
References llvm::cast(), llvm::Count, llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::PoisonValue::get(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::GlobalValue::getParent(), llvm::Type::getStructElementType(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::PrivateLinkage, llvm::GlobalVariable::setInitializer(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by indirectGlobals().
getGlobalForName()
GlobalVariable * getGlobalForName (GlobalVariable * G) inline static
Definition at line 147 of file HipStdPar.cpp.
References G, llvm::ConstantDataArray::getString(), N, and llvm::GlobalValue::PrivateLinkage.
Referenced by appendIndirectedGlobal().
getIndirectionGlobal()
GlobalVariable * getIndirectionGlobal (Module * M) inline static
Definition at line 161 of file HipStdPar.cpp.
References llvm::PointerType::get(), llvm::PoisonValue::get(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::PrivateLinkage, llvm::GlobalVariable::setConstant(), llvm::GlobalVariable::setExternallyInitialized(), llvm::GlobalVariable::setInitializer(), and llvm::GlobalValue::setLinkage().
Referenced by appendIndirectedGlobal().
indirectGlobals()
void indirectGlobals (GlobalVariable * IndirectionTable, SmallVector< GlobalVariable * > ToIndirect) static
Definition at line 289 of file HipStdPar.cpp.
References appendIndirectedGlobal(), collectIndirectableUses(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), eraseFromModule(), fillIndirectionTable(), llvm::for_each(), G, replaceWithIndirectUse(), and Uses.
Referenced by maybeHandleGlobals().
isAcceleratorExecutionRoot()
bool isAcceleratorExecutionRoot (const Function * F) inline static
Definition at line 365 of file HipStdPar.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, and F.
Referenced by llvm::HipStdParAcceleratorCodeSelectionPass::run().
isValidIndirectionTable()
bool isValidIndirectionTable (GlobalVariable * IndirectionTable) inline static
Definition at line 253 of file HipStdPar.cpp.
References llvm::cast(), llvm::LLVMContext::diagnose(), llvm::DS_Error, llvm::Value::getContext(), getNumElements(), llvm::GlobalValue::getValueType(), and llvm::isa().
Referenced by maybeHandleGlobals().
maybeHandleGlobals()
void maybeHandleGlobals (Module & M) inline static
Definition at line 316 of file HipStdPar.cpp.
References checkIfSupported(), clearModule(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), G, llvm::PoisonValue::get(), indirectGlobals(), isValidIndirectionTable(), IT, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::HipStdParAcceleratorCodeSelectionPass::run().
removeUnreachableFunctions()
template<unsigned N> void removeUnreachableFunctions (const SmallPtrSet< const Function *, N > & Reachable, Module & M) inline static
Definition at line 348 of file HipStdPar.cpp.
References llvm::CallingConv::C, llvm::copy_if(), llvm::dyn_cast(), eraseFromModule(), F, llvm::for_each(), llvm::removeFromUsedLists(), and ToRemove.
Referenced by llvm::HipStdParAcceleratorCodeSelectionPass::run().
replaceWithIndirectUse()
void replaceWithIndirectUse (const Use & U, const GlobalVariable * G, Constant * IndirectedG) static
Definition at line 223 of file HipStdPar.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), G, I, and OpIdx.
Referenced by indirectGlobals().
Variable Documentation
HiddenMap
std::pair<StringLiteral, StringLiteral> HiddenMap[] static constexpr
Initial value:
{
    {"__hipstdpar_hidden_malloc", "__libc_malloc"},
    {"__hipstdpar_hidden_free", "__libc_free"},
    {"__hipstdpar_hidden_memalign", "__libc_memalign"},
    {"__hipstdpar_hidden_mmap", "mmap"},
    {"__hipstdpar_hidden_munmap", "munmap"}}
Definition at line 484 of file HipStdPar.cpp.
Referenced by llvm::HipStdParAllocationInterpositionPass::run().
MathLibToHipStdPar
std::pair<StringLiteral, StringLiteral> MathLibToHipStdPar[] static constexpr
Definition at line 534 of file HipStdPar.cpp.
Referenced by llvm::HipStdParMathFixupPass::run().
ReplaceMap
std::pair<StringLiteral, StringLiteral> ReplaceMap[] static constexpr
Definition at line 442 of file HipStdPar.cpp.
Referenced by llvm::HipStdParAllocationInterpositionPass::run().