LLVM: lib/Transforms/Scalar/IndVarSimplify.cpp File Reference
IndVarSimplify.cpp File Reference
#include "llvm/Transforms/Scalar/IndVarSimplify.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ScalarEvolutionPatternMatch.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar/SimpleLoopUnswitch.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
#include "llvm/Transforms/Utils/SimplifyIndVar.h"
#include <cassert>
#include <cstdint>
#include <utility>
Classes
struct FloatingPointIV
Represents a floating-point induction variable pattern that may be convertible to integer form.
struct IntegerIV
Represents the integer values for a converted IV.
Macros
#define DEBUG_TYPE "indvars"
Functions
STATISTIC (NumWidened, "Number of indvars widened")
STATISTIC (NumReplaced, "Number of exit values replaced")
STATISTIC (NumLFTR, "Number of loop exit tests replaced")
STATISTIC (NumElimExt, "Number of IV sign/zero extends eliminated")
STATISTIC (NumElimIV, "Number of congruent IVs eliminated")
static bool ConvertToSInt (const APFloat &APF, int64_t &IntVal)
Convert APF to an integer, if possible.
static bool isRepresentableAsExactInteger (const APFloat &FPVal, int64_t IntVal)
Ensure we stay within the bounds of fp values that can be represented as integers without gaps, which are 2^24 and 2^53 for IEEE-754 single and double precision respectively (both on negative and positive side).
static CmpInst::Predicate getIntegerPredicate (CmpInst::Predicate FPPred)
static std::optional< FloatingPointIV > maybeFloatingPointRecurrence (Loop *L, PHINode *PN)
Analyze a PN to determine whether it represents a simple floating-point induction variable, with constant fp init, increment, and exit values.
static std::optional< IntegerIV > tryConvertToIntegerIV (const FloatingPointIV &FPIV)
Ensure that the floating-point IV can be converted to a semantics-preserving signed 32-bit integer IV.
static void canonicalizeToIntegerIV (Loop *L, PHINode *PN, const FloatingPointIV &FPIV, const IntegerIV &IIV, const TargetLibraryInfo *TLI, std::unique_ptr< MemorySSAUpdater > &MSSAU)
Rewrite the floating-point IV as an integer IV.
static void visitIVCast (CastInst *Cast, WideIVInfo &WI, ScalarEvolution *SE, const TargetTransformInfo *TTI)
Update information about the induction variable that is extended by this sign or zero extend operation.
static PHINode * getLoopPhiForCounter (Value *IncV, Loop *L)
Given an Value which is hoped to be part of an add recurance in the given loop, return the associated Phi node if so.
static bool isLoopExitTestBasedOn (Value *V, BasicBlock *ExitingBB)
Whether the current loop exit test is based on this value.
static bool needsLFTR (Loop *L, BasicBlock *ExitingBB)
linearFunctionTestReplace policy.
static bool hasConcreteDefImpl (Value *V, SmallPtrSetImpl< Value * > &Visited, unsigned Depth)
Recursive helper for hasConcreteDef().
static bool hasConcreteDef (Value *V)
Return true if the given value is concrete.
static bool isLoopCounter (PHINode *Phi, Loop *L, ScalarEvolution *SE)
Return true if the given phi is a "counter" in L.
static PHINode * FindLoopCounter (Loop *L, BasicBlock *ExitingBB, const SCEV *BECount, ScalarEvolution *SE, DominatorTree *DT)
Search the loop header for a loop counter (anadd rec w/step of one) suitable for use by LFTR.
static Value * genLoopLimit (PHINode *IndVar, BasicBlock *ExitingBB, const SCEV *ExitCount, bool UsePostInc, Loop *L, SCEVExpander &Rewriter, ScalarEvolution *SE)
Insert an IR expression which computes the value held by the IV IndVar (which must be an loop counter w/unit stride) after the backedge of loop L is taken ExitCount times.
static void replaceExitCond (BranchInst *BI, Value *NewCond, SmallVectorImpl< WeakTrackingVH > &DeadInsts)
static Constant * createFoldedExitCond (const Loop *L, BasicBlock *ExitingBB, bool IsTaken)
static void foldExit (const Loop *L, BasicBlock *ExitingBB, bool IsTaken, SmallVectorImpl< WeakTrackingVH > &DeadInsts)
static void replaceLoopPHINodesWithPreheaderValues (LoopInfo *LI, Loop *L, SmallVectorImpl< WeakTrackingVH > &DeadInsts, ScalarEvolution &SE)
static Value * createInvariantCond (const Loop *L, BasicBlock *ExitingBB, const ScalarEvolution::LoopInvariantPredicate &LIP, SCEVExpander &Rewriter)
static std::optional< Value * > createReplacement (ICmpInst *ICmp, const Loop *L, BasicBlock *ExitingBB, const SCEV *MaxIter, bool Inverted, bool SkipLastIter, ScalarEvolution *SE, SCEVExpander &Rewriter)
static bool optimizeLoopExitWithUnknownExitCount (const Loop *L, BranchInst *BI, BasicBlock *ExitingBB, const SCEV *MaxIter, bool SkipLastIter, ScalarEvolution *SE, SCEVExpander &Rewriter, SmallVectorImpl< WeakTrackingVH > &DeadInsts)
static bool crashingBBWithoutEffect (const BasicBlock &BB)
Variables
static cl::opt< ReplaceExitVal > ReplaceExitValue ("replexitval", cl::Hidden, cl::init(OnlyCheapRepl), cl::desc("Choose the strategy to replace exit value in IndVarSimplify"), cl::values(clEnumValN(NeverRepl, "never", "never replace exit value"), clEnumValN(OnlyCheapRepl, "cheap", "only replace exit value when the cost is cheap"), clEnumValN(UnusedIndVarInLoop, "unusedindvarinloop", "only replace exit value when it is an unused " "induction variable in the loop and has cheap replacement cost"), clEnumValN(NoHardUse, "noharduse", "only replace exit values when loop def likely dead"), clEnumValN(AlwaysRepl, "always", "always replace exit value whenever possible")))
static cl::opt< bool > UsePostIncrementRanges ("indvars-post-increment-ranges", cl::Hidden, cl::desc("Use post increment control-dependent ranges in IndVarSimplify"), cl::init(true))
static cl::opt< bool > DisableLFTR ("disable-lftr", cl::Hidden, cl::init(false), cl::desc("Disable Linear Function Test Replace optimization"))
static cl::opt< bool > LoopPredication ("indvars-predicate-loops", cl::Hidden, cl::init(true), cl::desc("Predicate conditions in read only loops"))
static cl::opt< bool > LoopPredicationTraps ("indvars-predicate-loop-traps", cl::Hidden, cl::init(true), cl::desc("Predicate conditions that trap in loops with only local writes"))
static cl::opt< bool > AllowIVWidening ("indvars-widen-indvars", cl::Hidden, cl::init(true), cl::desc("Allow widening of indvars to eliminate s/zext"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "indvars"
Definition at line 84 of file IndVarSimplify.cpp.
Function Documentation
canonicalizeToIntegerIV()
void canonicalizeToIntegerIV (Loop * L, PHINode * PN, const FloatingPointIV & FPIV, const IntegerIV & IIV, const TargetLibraryInfo * TLI, std::unique_ptr< MemorySSAUpdater > & MSSAU) static
Rewrite the floating-point IV as an integer IV.
Definition at line 425 of file IndVarSimplify.cpp.
References llvm::PHINode::addIncoming(), llvm::cast(), FloatingPointIV::Compare, llvm::PHINode::Create(), llvm::dbgs(), IntegerIV::ExitValue, llvm::PoisonValue::get(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Type::getInt32Ty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::CmpInst::getPredicateName(), llvm::ConstantInt::getSigned(), llvm::Value::getType(), IntegerIV::IncrValue, IntegerIV::InitValue, llvm::Int32Ty, LLVM_DEBUG, IntegerIV::NewPred, llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::Value::replaceAllUsesWith(), llvm::Instruction::setDebugLoc(), llvm::Value::takeName(), and llvm::Instruction::user_back().
ConvertToSInt()
bool ConvertToSInt (const APFloat & APF, int64_t & IntVal) static
Convert APF to an integer, if possible.
Definition at line 189 of file IndVarSimplify.cpp.
References llvm::APFloat::convertToInteger(), llvm::APFloatBase::opOK, and llvm::APFloatBase::rmTowardZero.
Referenced by tryConvertToIntegerIV().
crashingBBWithoutEffect()
bool crashingBBWithoutEffect (const BasicBlock & BB) static
Definition at line 1820 of file IndVarSimplify.cpp.
References llvm::all_of(), llvm::dyn_cast(), I, and llvm::isa().
createFoldedExitCond()
Constant * createFoldedExitCond (const Loop * L, BasicBlock * ExitingBB, bool IsTaken) static
Definition at line 1279 of file IndVarSimplify.cpp.
References llvm::cast(), llvm::BranchInst::getCondition(), llvm::BasicBlock::getTerminator(), and llvm::succ_begin().
Referenced by createReplacement(), and foldExit().
createInvariantCond()
Value * createInvariantCond (const Loop * L, BasicBlock * ExitingBB, const ScalarEvolution::LoopInvariantPredicate & LIP, SCEVExpander & Rewriter) static
Definition at line 1334 of file IndVarSimplify.cpp.
References assert(), llvm::cast(), llvm::BranchInst::getCondition(), llvm::CmpInst::getInversePredicate(), llvm::Value::getName(), llvm::BasicBlock::getTerminator(), llvm::ScalarEvolution::LoopInvariantPredicate::LHS, llvm::ScalarEvolution::LoopInvariantPredicate::Pred, llvm::ScalarEvolution::LoopInvariantPredicate::RHS, and llvm::succ_begin().
Referenced by createReplacement().
createReplacement()
std::optional< Value * > createReplacement (ICmpInst * ICmp, const Loop * L, BasicBlock * ExitingBB, const SCEV * MaxIter, bool Inverted, bool SkipLastIter, ScalarEvolution * SE, SCEVExpander & Rewriter) static
Definition at line 1353 of file IndVarSimplify.cpp.
References llvm::cast(), createFoldedExitCond(), createInvariantCond(), llvm::dyn_cast(), llvm::ScalarEvolution::evaluatePredicateAt(), llvm::ICmpInst::getCmpPredicate(), llvm::ICmpInst::getInverseCmpPredicate(), llvm::ScalarEvolution::getLoopInvariantExitCondDuringFirstIterations(), llvm::ScalarEvolution::getMinusOne(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getOne(), llvm::User::getOperand(), llvm::ScalarEvolution::getSCEVAtScope(), llvm::BasicBlock::getTerminator(), llvm::ScalarEvolution::getTruncateExpr(), llvm::SCEV::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::CmpInst::ICMP_ULE, llvm::ScalarEvolution::isKnownPredicateAt(), LHS, RHS, and llvm::UMin.
Referenced by optimizeLoopExitWithUnknownExitCount().
FindLoopCounter()
PHINode * FindLoopCounter (Loop * L, BasicBlock * ExitingBB, const SCEV * BECount, ScalarEvolution * SE, DominatorTree * DT) static
Search the loop header for a loop counter (anadd rec w/step of one) suitable for use by LFTR.
If multiple counters are available, select the "best" one based profitable heuristics.
BECount may be an i8* pointer type. The pointer difference is already valid count without scaling the address stride, so it remains a pointer expression as far as SCEV is concerned.
Definition at line 939 of file IndVarSimplify.cpp.
References assert(), llvm::cast(), Cond, DL, llvm::ScalarEvolution::getSCEV(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), hasConcreteDef(), I, llvm::isa(), llvm::isAlmostDeadIV(), isLoopCounter(), isLoopExitTestBasedOn(), llvm::SCEV::isZero(), and llvm::mustExecuteUBIfPoisonOnPathTo().
foldExit()
void foldExit (const Loop * L, BasicBlock * ExitingBB, bool IsTaken, SmallVectorImpl< WeakTrackingVH > & DeadInsts) static
Definition at line 1288 of file IndVarSimplify.cpp.
References llvm::cast(), createFoldedExitCond(), llvm::BasicBlock::getTerminator(), and replaceExitCond().
genLoopLimit()
Value * genLoopLimit (PHINode * IndVar, BasicBlock * ExitingBB, const SCEV * ExitCount, bool UsePostInc, Loop * L, SCEVExpander & Rewriter, ScalarEvolution * SE) static
Insert an IR expression which computes the value held by the IV IndVar (which must be an loop counter w/unit stride) after the backedge of loop L is taken ExitCount times.
Definition at line 1019 of file IndVarSimplify.cpp.
References assert(), llvm::cast(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::SCEVAddRecExpr::getPostIncExpr(), llvm::ScalarEvolution::getSCEV(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::BasicBlock::getTerminator(), llvm::ScalarEvolution::getTruncateExpr(), llvm::SCEV::getType(), llvm::SCEVAddRecExpr::getType(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::isa(), llvm::Type::isIntegerTy(), isLoopCounter(), llvm::ScalarEvolution::isLoopInvariant(), and llvm::SCEV::isOne().
getIntegerPredicate()
CmpInst::Predicate getIntegerPredicate (CmpInst::Predicate FPPred) static
Definition at line 235 of file IndVarSimplify.cpp.
References llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, and llvm::CmpInst::ICMP_SLT.
Referenced by tryConvertToIntegerIV().
getLoopPhiForCounter()
PHINode * getLoopPhiForCounter (Value * IncV, Loop * L) static
Given an Value which is hoped to be part of an add recurance in the given loop, return the associated Phi node if so.
Otherwise, return null. Note that this is less general than SCEVs AddRec checking.
Definition at line 771 of file IndVarSimplify.cpp.
References llvm::dyn_cast(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), and llvm::User::getOperand().
Referenced by isLoopCounter(), and needsLFTR().
hasConcreteDef()
bool hasConcreteDef (Value * V) static
Return true if the given value is concrete.
We must prove that undef can never reach it.
TODO: If we decide that this is a good approach to checking for undef, we may factor it into a common location.
Definition at line 905 of file IndVarSimplify.cpp.
References hasConcreteDefImpl(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by FindLoopCounter().
hasConcreteDefImpl()
bool hasConcreteDefImpl (Value * V, SmallPtrSetImpl< Value * > & Visited, unsigned Depth) static
Recursive helper for hasConcreteDef().
Unfortunately, this currently boils down to checking that all operands are constant and listing instructions that may hide undef.
Definition at line 872 of file IndVarSimplify.cpp.
References llvm::Depth, llvm::dyn_cast(), hasConcreteDefImpl(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::isa().
Referenced by hasConcreteDef(), and hasConcreteDefImpl().
isLoopCounter()
bool isLoopCounter (PHINode * Phi, Loop * L, ScalarEvolution * SE) static
Return true if the given phi is a "counter" in L.
A counter is an add recurance (of integer or pointer type) with an arbitrary start, and a step of 1. Note that L must have exactly one latch.
Definition at line 914 of file IndVarSimplify.cpp.
References assert(), getLoopPhiForCounter(), llvm::ScalarEvolution::getSCEV(), llvm::isa(), llvm::ScalarEvolution::isSCEVable(), llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_AffineAddRec(), llvm::SCEVPatternMatch::m_scev_One(), llvm::SCEVPatternMatch::m_SpecificLoop(), and llvm::SCEVPatternMatch::match().
Referenced by FindLoopCounter(), and genLoopLimit().
isLoopExitTestBasedOn()
bool isLoopExitTestBasedOn (Value * V, BasicBlock * ExitingBB) static
Whether the current loop exit test is based on this value.
Currently this is limited to a direct use in the loop condition.
Definition at line 809 of file IndVarSimplify.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::BranchInst::getCondition(), llvm::User::getOperand(), and llvm::BasicBlock::getTerminator().
Referenced by FindLoopCounter().
isRepresentableAsExactInteger()
bool isRepresentableAsExactInteger (const APFloat & FPVal, int64_t IntVal) static
Ensure we stay within the bounds of fp values that can be represented as integers without gaps, which are 2^24 and 2^53 for IEEE-754 single and double precision respectively (both on negative and positive side).
Definition at line 204 of file IndVarSimplify.cpp.
References llvm::AbsoluteValue(), llvm::APFloat::getSemantics(), llvm::APFloatBase::isIEEELikeFP(), llvm::isUIntN(), and llvm::APFloatBase::semanticsPrecision().
Referenced by tryConvertToIntegerIV().
maybeFloatingPointRecurrence()
std::optional< FloatingPointIV > maybeFloatingPointRecurrence (Loop * L, PHINode * PN) static
Analyze a PN to determine whether it represents a simple floating-point induction variable, with constant fp init, increment, and exit values.
Returns a FloatingPointIV struct if matched, std::nullopt otherwise.
Definition at line 265 of file IndVarSimplify.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::find_if(), llvm::PHINode::getIncomingBlock(), and llvm::PHINode::getIncomingValue().
needsLFTR()
bool needsLFTR (Loop * L, BasicBlock * ExitingBB) static
linearFunctionTestReplace policy.
Return true unless we can show that the current exit test is already sufficiently canonical.
Definition at line 822 of file IndVarSimplify.cpp.
References assert(), llvm::cast(), Cond, llvm::dyn_cast(), llvm::BranchInst::getCondition(), getLoopPhiForCounter(), llvm::BasicBlock::getTerminator(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, LHS, RHS, and std::swap().
optimizeLoopExitWithUnknownExitCount()
bool optimizeLoopExitWithUnknownExitCount (const Loop * L, BranchInst * BI, BasicBlock * ExitingBB, const SCEV * MaxIter, bool SkipLastIter, ScalarEvolution * SE, SCEVExpander & Rewriter, SmallVectorImpl< WeakTrackingVH > & DeadInsts) static
Definition at line 1410 of file IndVarSimplify.cpp.
References assert(), llvm::ScalarEvolution::computeExitLimitFromCond(), llvm::SmallPtrSetImpl< PtrType >::count(), createReplacement(), llvm::dbgs(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::BranchInst::getCondition(), llvm::ScalarEvolution::getExitCount(), llvm::Value::getName(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::BranchInst::getSuccessor(), llvm::SCEV::getType(), llvm::ScalarEvolution::getWiderType(), llvm::Value::hasOneUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), LHS, LLVM_DEBUG, llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::PatternMatch::m_Value(), llvm::SCEVPatternMatch::match(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), RHS, llvm::SmallPtrSetImplBase::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ScalarEvolution::SymbolicMaximum.
replaceExitCond()
void replaceExitCond (BranchInst * BI, Value * NewCond, SmallVectorImpl< WeakTrackingVH > & DeadInsts) static
Definition at line 1269 of file IndVarSimplify.cpp.
References llvm::dbgs(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::BranchInst::getCondition(), LLVM_DEBUG, and llvm::BranchInst::setCondition().
Referenced by foldExit().
replaceLoopPHINodesWithPreheaderValues()
void replaceLoopPHINodesWithPreheaderValues (LoopInfo * LI, Loop * L, SmallVectorImpl< WeakTrackingVH > & DeadInsts, ScalarEvolution & SE) static
Definition at line 1295 of file IndVarSimplify.cpp.
References assert(), llvm::cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::ScalarEvolution::forgetValue(), llvm::PHINode::getIncomingValueForBlock(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::LoopInfo::replacementPreservesLCSSAForm(), llvm::simplifyInstruction(), and llvm::Value::users().
STATISTIC() [1/5]
STATISTIC (NumElimExt , "Number of IV sign/zero extends eliminated")
STATISTIC() [2/5]
STATISTIC (NumElimIV , "Number of congruent IVs eliminated")
STATISTIC() [3/5]
STATISTIC (NumLFTR , "Number of loop exit tests replaced")
STATISTIC() [4/5]
STATISTIC (NumReplaced , "Number of exit values replaced")
STATISTIC() [5/5]
STATISTIC (NumWidened , "Number of indvars widened")
tryConvertToIntegerIV()
std::optional< IntegerIV > tryConvertToIntegerIV (const FloatingPointIV & FPIV) static
Ensure that the floating-point IV can be converted to a semantics-preserving signed 32-bit integer IV.
Returns a IntegerIV struct if possible, std::nullopt otherwise.
Definition at line 333 of file IndVarSimplify.cpp.
References llvm::CmpInst::BAD_ICMP_PREDICATE, FloatingPointIV::Compare, ConvertToSInt(), FloatingPointIV::ExitValue, getIntegerPredicate(), llvm::CmpInst::getPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, FloatingPointIV::IncrValue, FloatingPointIV::InitValue, llvm::isInt(), isRepresentableAsExactInteger(), and Range.
visitIVCast()
void visitIVCast (CastInst * Cast, WideIVInfo & WI, ScalarEvolution * SE, const TargetTransformInfo * TTI) static
Update information about the induction variable that is extended by this sign or zero extend operation.
This is used to determine the final width of the IV before actually widening it.
Definition at line 620 of file IndVarSimplify.cpp.
References llvm::Instruction::getDataLayout(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::DataLayout::isLegalInteger(), llvm::WideIVInfo::IsSigned, llvm::WideIVInfo::NarrowIV, and llvm::WideIVInfo::WidestNativeType.
Variable Documentation
AllowIVWidening
cl::opt< bool > AllowIVWidening("indvars-widen-indvars", cl::Hidden, cl::init(true), cl::desc("Allow widening of indvars to eliminate s/zext")) ("indvars-widen-indvars" , cl::Hidden , cl::init(true) , cl::desc("Allow widening of indvars to eliminate s/zext")) static
Referenced by llvm::IndVarSimplifyPass::run().
DisableLFTR
cl::opt< bool > DisableLFTR("disable-lftr", cl::Hidden, cl::init(false), cl::desc("Disable Linear Function Test Replace optimization")) ("disable-lftr" , cl::Hidden , cl::init(false) , cl::desc("Disable Linear Function Test Replace optimization")) static
LoopPredication
cl::opt< bool > LoopPredication("indvars-predicate-loops", cl::Hidden, cl::init(true), cl::desc("Predicate conditions in read only loops")) ("indvars-predicate-loops" , cl::Hidden , cl::init(true) , cl::desc("Predicate conditions in read only loops")) static
LoopPredicationTraps
cl::opt< bool > LoopPredicationTraps("indvars-predicate-loop-traps", cl::Hidden, cl::init(true), cl::desc("Predicate conditions that trap in loops with only local writes")) ("indvars-predicate-loop-traps" , cl::Hidden , cl::init(true) , cl::desc("Predicate conditions that trap in loops with only local writes")) static
ReplaceExitValue
cl::opt< ReplaceExitVal > ReplaceExitValue("replexitval", cl::Hidden, cl::init(OnlyCheapRepl), cl::desc("Choose the strategy to replace exit value in IndVarSimplify"), cl::values(clEnumValN(NeverRepl, "never", "never replace exit value"), clEnumValN(OnlyCheapRepl, "cheap", "only replace exit value when the cost is cheap"), clEnumValN(UnusedIndVarInLoop, "unusedindvarinloop", "only replace exit value when it is an unused " "induction variable in the loop and has cheap replacement cost"), clEnumValN(NoHardUse, "noharduse", "only replace exit values when loop def likely dead"), clEnumValN(AlwaysRepl, "always", "always replace exit value whenever possible"))) ("replexitval" , cl::Hidden , cl::init(OnlyCheapRepl) , cl::desc("Choose the strategy to replace exit value in IndVarSimplify") , cl::values(clEnumValN(NeverRepl, "never", "never replace exit value"), clEnumValN(OnlyCheapRepl, "cheap", "only replace exit value when the cost is cheap"), clEnumValN(UnusedIndVarInLoop, "unusedindvarinloop", "only replace exit value when it is an unused " "induction variable in the loop and has cheap replacement cost"), clEnumValN(NoHardUse, "noharduse", "only replace exit values when loop def likely dead"), clEnumValN(AlwaysRepl, "always", "always replace exit value whenever possible"))) static
Referenced by llvm::rewriteLoopExitValues().
UsePostIncrementRanges
cl::opt< bool > UsePostIncrementRanges("indvars-post-increment-ranges", cl::Hidden, cl::desc("Use post increment control-dependent ranges in IndVarSimplify"), cl::init(true)) ("indvars-post-increment-ranges" , cl::Hidden , cl::desc("Use post increment control-dependent ranges in IndVarSimplify") , cl::init(true)) static
Referenced by llvm::createWideIV().