LLVM: lib/CodeGen/GlobalISel/InlineAsmLowering.cpp File Reference
InlineAsmLowering.cpp File Reference
This file implements the lowering from LLVM IR inline asm to MIR INLINEASM.
#include "llvm/CodeGen/GlobalISel/InlineAsmLowering.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/Module.h"
Macros
#define DEBUG_TYPE "inline-asm-lowering"
Functions
static void getRegistersForValue (MachineFunction &MF, MachineIRBuilder &MIRBuilder, GISelAsmOperandInfo &OpInfo, GISelAsmOperandInfo &RefOpInfo)
Assign virtual/physical registers for the specified register operand.
static void computeConstraintToUse (const TargetLowering *TLI, TargetLowering::AsmOperandInfo &OpInfo)
static unsigned getNumOpRegs (const MachineInstr &I, unsigned OpIdx)
static bool buildAnyextOrCopy (Register Dst, Register Src, MachineIRBuilder &MIRBuilder)
Detailed Description
This file implements the lowering from LLVM IR inline asm to MIR INLINEASM.
Definition in file InlineAsmLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inline-asm-lowering"
Definition at line 22 of file InlineAsmLowering.cpp.
Function Documentation
buildAnyextOrCopy()
bool buildAnyextOrCopy (Register Dst, Register Src, MachineIRBuilder & MIRBuilder) static
Definition at line 185 of file InlineAsmLowering.cpp.
References llvm::MachineIRBuilder::buildAnyExt(), llvm::MachineIRBuilder::buildCopy(), llvm::dbgs(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstrBuilder::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, MRI, llvm::LLT::scalar(), and TRI.
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().
computeConstraintToUse()
void computeConstraintToUse (const TargetLowering * TLI, TargetLowering::AsmOperandInfo & OpInfo) static
Definition at line 139 of file InlineAsmLowering.cpp.
References assert(), llvm::TargetLowering::C_Immediate, llvm::TargetLowering::C_Other, E(), G, llvm::TargetLowering::getConstraintPreferences(), llvm::TargetLowering::getConstraintType(), llvm::isa(), and llvm::TargetLowering::LowerXConstraint().
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().
getNumOpRegs()
unsigned getNumOpRegs (const MachineInstr & I, unsigned OpIdx) static
Definition at line 180 of file InlineAsmLowering.cpp.
References F, I, and OpIdx.
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().
getRegistersForValue()
void getRegistersForValue (MachineFunction & MF, MachineIRBuilder & MIRBuilder, GISelAsmOperandInfo & OpInfo, GISelAsmOperandInfo & RefOpInfo) static
Assign virtual/physical registers for the specified register operand.
Definition at line 83 of file InlineAsmLowering.cpp.
References assert(), llvm::TargetRegisterClass::begin(), llvm::TargetLowering::C_Memory, llvm::TargetRegisterClass::end(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), I, Register, and TRI.
Referenced by llvm::InlineAsmLowering::lowerInlineAsm().