LLVM: lib/Analysis/InlineAdvisor.cpp File Reference
InlineAdvisor.cpp File Reference
#include "llvm/Analysis/InlineAdvisor.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/EphemeralValuesCache.h"
#include "llvm/Analysis/IR2Vec.h"
#include "llvm/Analysis/InlineCost.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/ReplayInlineAdvisor.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/Utils/ImportedFunctionsInliningStatistics.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "inline"
Functions
STATISTIC (NumCallerCallersAnalyzed, "Number of caller-callers analyzed")
static std::optional< llvm::InlineCost > getDefaultInlineAdvice (CallBase &CB, FunctionAnalysisManager &FAM, const InlineParams &Params)
static bool shouldBeDeferred (Function *Caller, TargetTransformInfo &CalleeTTI, InlineCost IC, int &TotalSecondaryCost, function_ref< InlineCost(CallBase &CB)> GetInlineCost)
Return true if inlining of CB can block the caller from being inlined which is proved to be more beneficial.
static raw_ostream & llvm::operator<< (raw_ostream &R, const ore::NV &Arg)
template<class RemarkT>
decltype(auto) llvm::operator<< (RemarkT &&R, const InlineCost &IC)
static const char * getLTOPhase (ThinOrFullLTOPhase LTOPhase)
static const char * getInlineAdvisorContext (InlinePass IP)
Variables
static cl::opt< bool > InlineRemarkAttribute ("inline-remark-attribute", cl::init(false), cl::Hidden, cl::desc("Enable adding inline-remark attribute to" " callsites processed by inliner but decided" " to be not inlined"))
Flag to add inline messages as callsite attributes 'inline-remark'.
static cl::opt< bool > EnableInlineDeferral ("inline-deferral", cl::init(false), cl::Hidden, cl::desc("Enable deferred inlining"))
static cl::opt< int > InlineDeferralScale ("inline-deferral-scale", cl::desc("Scale to limit the cost of inline deferral"), cl::init(2), cl::Hidden)
static cl::opt< bool > AnnotateInlinePhase ("annotate-inline-phase", cl::Hidden, cl::init(false), cl::desc("If true, annotate inline advisor remarks " "with LTO and pass information."))
static cl::opt< std::string > IR2VecVocabFile ("ml-inliner-ir2vec-vocab-file", cl::Hidden, cl::desc("Vocab file for IR2Vec; Setting this enables " "configuring the model to use IR2Vec embeddings."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inline"
Definition at line 34 of file InlineAdvisor.cpp.
Function Documentation
getDefaultInlineAdvice()
std::optional< llvm::InlineCost > getDefaultInlineAdvice (CallBase & CB, FunctionAnalysisManager & FAM, const InlineParams & Params) static
Definition at line 144 of file InlineAdvisor.cpp.
References DEBUG_TYPE, llvm::InlineParams::EnableDeferral, EnableInlineDeferral, F, FAM, llvm::CallBase::getCalledFunction(), llvm::CallBase::getCaller(), llvm::getInlineCost(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), and llvm::shouldInline().
Referenced by llvm::InlineAdvisorAnalysis::Result::tryCreate().
getInlineAdvisorContext()
const char * getInlineAdvisorContext (InlinePass IP) inline static
Definition at line 596 of file InlineAdvisor.cpp.
References llvm::AlwaysInliner, llvm::CGSCCInliner, llvm::EarlyInliner, llvm_unreachable, llvm::MLInliner, llvm::ModuleInliner, llvm::ReplayCGSCCInliner, llvm::ReplaySampleProfileInliner, and llvm::SampleProfileInliner.
Referenced by llvm::AnnotateInlinePassName().
getLTOPhase()
const char * getLTOPhase (ThinOrFullLTOPhase LTOPhase) inline static
Definition at line 582 of file InlineAdvisor.cpp.
References llvm::FullLTOPostLink, llvm::FullLTOPreLink, llvm_unreachable, llvm::None, llvm::ThinLTOPostLink, and llvm::ThinLTOPreLink.
Referenced by llvm::AnnotateInlinePassName().
shouldBeDeferred()
bool shouldBeDeferred (Function * Caller, TargetTransformInfo & CalleeTTI, InlineCost IC, int & TotalSecondaryCost, function_ref< InlineCost(CallBase &CB)> GetInlineCost) static
Return true if inlining of CB can block the caller from being inlined which is proved to be more beneficial.
IC is the estimated inline cost associated with callsite CB. TotalSecondaryCost will be set to the estimated cost of inlining the caller if CB is suppressed for inlining.
Definition at line 284 of file InlineAdvisor.cpp.
References llvm::dyn_cast(), llvm::CallBase::getCalledFunction(), llvm::InlineCost::getCost(), llvm::InlineCost::getCostDelta(), llvm::TargetTransformInfo::getInliningLastCallToStaticBonus(), InlineDeferralScale, and llvm::InlineCost::isAlways().
Referenced by llvm::shouldInline().
STATISTIC()
STATISTIC (NumCallerCallersAnalyzed , "Number of caller-callers analyzed")
Variable Documentation
AnnotateInlinePhase
cl::opt< bool > AnnotateInlinePhase("annotate-inline-phase", cl::Hidden, cl::init(false), cl::desc("If true, annotate inline advisor remarks " "with LTO and pass information.")) ("annotate-inline-phase" , cl::Hidden , cl::init(false) , cl::desc("If true, annotate inline advisor remarks " "with LTO and pass information.")) static
Referenced by llvm::InlineAdvisor::InlineAdvisor().
EnableInlineDeferral
cl::opt< bool > EnableInlineDeferral("inline-deferral", cl::init(false), cl::Hidden, cl::desc("Enable deferred inlining")) ("inline-deferral" , cl::init(false) , cl::Hidden , cl::desc("Enable deferred inlining")) static
Referenced by getDefaultInlineAdvice().
InlineDeferralScale
cl::opt< int > InlineDeferralScale("inline-deferral-scale", cl::desc("Scale to limit the cost of inline deferral"), cl::init(2), cl::Hidden) ("inline-deferral-scale" , cl::desc("Scale to limit the cost of inline deferral") , cl::init(2) , cl::Hidden) static
Referenced by shouldBeDeferred().
InlineRemarkAttribute
cl::opt< bool > InlineRemarkAttribute("inline-remark-attribute", cl::init(false), cl::Hidden, cl::desc("Enable adding inline-remark attribute to" " callsites processed by inliner but decided" " to be not inlined")) ("inline-remark-attribute" , cl::init(false) , cl::Hidden , cl::desc("Enable adding inline-remark attribute to" " callsites processed by inliner but decided" " to be not inlined")) static
Flag to add inline messages as callsite attributes 'inline-remark'.
Referenced by llvm::setInlineRemark().
IR2VecVocabFile
cl::opt< std::string > IR2VecVocabFile("ml-inliner-ir2vec-vocab-file", cl::Hidden, cl::desc("Vocab file for IR2Vec; Setting this enables " "configuring the model to use IR2Vec embeddings.")) ("ml-inliner-ir2vec-vocab-file" , cl::Hidden , cl::desc("Vocab file for IR2Vec; Setting this enables " "configuring the model to use IR2Vec embeddings.")) static