LLVM: lib/ProfileData/InstrProfCorrelator.cpp File Reference
InstrProfCorrelator.cpp File Reference
#include "llvm/ProfileData/InstrProfCorrelator.h"
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFLocationExpression.h"
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
#include "llvm/DebugInfo/DWARF/LowLevel/DWARFExpression.h"
#include "llvm/Object/MachO.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/WithColor.h"
#include <optional>
Classes
struct llvm::yaml::MappingTraits< InstrProfCorrelator::CorrelationData >
struct llvm::yaml::MappingTraits< InstrProfCorrelator::Probe >
struct llvm::yaml::SequenceElementTraits< InstrProfCorrelator::Probe >
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "correlator"
Functions
static Expected< object::SectionRef > getInstrProfSection (const object::ObjectFile &Obj, InstrProfSectKind IPSK)
Get profile section.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "correlator"
Definition at line 23 of file InstrProfCorrelator.cpp.
Function Documentation
getInstrProfSection()
Expected< object::SectionRef > getInstrProfSection (const object::ObjectFile & Obj, InstrProfSectKind IPSK) static
Get profile section.
Definition at line 29 of file InstrProfCorrelator.cpp.
References llvm::Triple::COFF, llvm::getInstrProfSectionName(), llvm::make_error(), N, and llvm::unable_to_correlate_profile.
Referenced by llvm::InstrProfCorrelator::Context::get().