LLVM: lib/Transforms/InstCombine/InstCombineSelect.cpp File Reference
InstCombineSelect.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CmpInstAnalysis.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/OverflowInstAnalysis.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/FMF.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include <cassert>
#include <optional>
#include <utility>
#include "llvm/Transforms/Utils/InstructionWorklist.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "instcombine"
Functions
static Instruction * foldSelectBinOpIdentity (SelectInst &Sel, const TargetLibraryInfo &TLI, InstCombinerImpl &IC)
Replace a select operand based on an equality comparison with the identity constant of a binop.
static Value * foldSelectICmpAnd (SelectInst &Sel, Value *CondVal, Value *TrueVal, Value *FalseVal, Value *V, const APInt &AndMask, bool CreateAnd, InstCombiner::BuilderTy &Builder)
This folds: select (icmp eq (and X, C1)), TC, FC iff C1 is a power 2 and the difference between TC and FC is a power-of-2.
static unsigned getSelectFoldableOperands (BinaryOperator *I)
We want to turn code that looks like this: C = or A, B D = select cond, C, A into: C = select cond, B, 0 D = or A, C.
static bool isSelect01 (const APInt &C1I, const APInt &C2I)
static Value * foldSelectICmpMinMax (const ICmpInst *Cmp, Value *TVal, Value *FVal, InstCombiner::BuilderTy &Builder, const SimplifyQuery &SQ)
Try to fold a select to a min/max intrinsic.
static Instruction * foldSelectICmpAndAnd (Type *SelType, const ICmpInst *Cmp, Value *TVal, Value *FVal, InstCombiner::BuilderTy &Builder)
We want to turn: (select (icmp eq (and X, Y), 0), (and (lshr X, Z), 1), 1) into: zext (icmp ne i32 (and X, (or Y, (shl 1, Z))), 0) Note: Z may be 0 if lshr is missing.
static Value * foldSelectICmpAndZeroShl (const ICmpInst *Cmp, Value *TVal, Value *FVal, InstCombiner::BuilderTy &Builder)
We want to turn: (select (icmp eq (and X, C1), 0), 0, (shl [nsw/nuw] X, C2)); iff C1 is a mask and the number of its leading zeros is equal to C2 into: shl X, C2.
static Value * foldSelectICmpLshrAshr (const ICmpInst *IC, Value *TrueVal, Value *FalseVal, InstCombiner::BuilderTy &Builder)
We want to turn: (select (icmp sgt x, C), lshr (X, Y), ashr (X, Y)); iff C s>= -1 (select (icmp slt x, C), ashr (X, Y), lshr (X, Y)); iff C s>= 0 into: ashr (X, Y).
static Value * foldSelectICmpAndBinOp (Value *CondVal, Value *TrueVal, Value *FalseVal, Value *V, const APInt &AndMask, bool CreateAnd, InstCombiner::BuilderTy &Builder)
We want to turn: (select (icmp eq (and X, C1), 0), Y, (BinOp Y, C2)) into: IF C2 u>= C1 (BinOp Y, (shl (and X, C1), C3)) ELSE (BinOp Y, (lshr (and X, C1), C3)) iff: 0 on the RHS is the identity value (i.e add, xor, shl, etc...) C1 and C2 are both powers of 2 where: IF C2 u>= C1 C3 = Log(C2) - Log(C1) ELSE C3 = Log(C1) - Log(C2).
static Instruction * foldSetClearBits (SelectInst &Sel, InstCombiner::BuilderTy &Builder)
Canonicalize a set or clear of a masked set of constant bits to select-of-constants form.
static Instruction * foldSelectZeroOrFixedOp (SelectInst &SI, InstCombinerImpl &IC)
static Value * canonicalizeSaturatedSubtract (const ICmpInst *ICI, const Value *TrueVal, const Value *FalseVal, InstCombiner::BuilderTy &Builder)
Transform patterns such as (a > b) ?
static Value * canonicalizeSaturatedAddUnsigned (ICmpInst *Cmp, Value *TVal, Value *FVal, InstCombiner::BuilderTy &Builder)
static Value * canonicalizeSaturatedAddSigned (ICmpInst *Cmp, Value *TVal, Value *FVal, InstCombiner::BuilderTy &Builder)
static Value * canonicalizeSaturatedAdd (ICmpInst *Cmp, Value *TVal, Value *FVal, InstCombiner::BuilderTy &Builder)
static Value * foldAbsDiff (ICmpInst *Cmp, Value *TVal, Value *FVal, InstCombiner::BuilderTy &Builder)
Try to match patterns with select and subtract as absolute difference.
static Instruction * foldSelectWithExtremeEqCond (Value *CmpLHS, Value *CmpRHS, Value *TrueVal, Value *FalseVal)
Fold the following code sequence:
static Instruction * foldSelectICmpEq (SelectInst &SI, ICmpInst *ICI, InstCombinerImpl &IC)
static Instruction * foldICmpUSubSatWithAndForMostSignificantBitCmp (SelectInst &SI, ICmpInst *ICI, InstCombiner::BuilderTy &Builder)
Folds: a_sub = call @llvm.usub.sat(x, IntConst1) b_sub = call @llvm.usub.sat(y, IntConst2) or = or a_sub, b_sub cmp = icmp eq or, 0 sel = select cmp, 0, MostSignificantBit into: a_sub' = usub.sat(x, IntConst1 - MostSignificantBit) b_sub' = usub.sat(y, IntConst2 - MostSignificantBit) or = or a_sub', b_sub' and = and or, MostSignificantBit Likewise, for vector arguments as well.
static Instruction * foldAddSubSelect (SelectInst &SI, InstCombiner::BuilderTy &Builder)
Turn select C, (X + Y), (X - Y) --> (X + (select C, Y, (-Y))).
static Instruction * foldOverflowingAddSubSelect (SelectInst &SI, InstCombiner::BuilderTy &Builder)
Turn X + Y overflows ?
static Instruction * canonicalizeSelectToShuffle (SelectInst &SI)
Try to transform a vector select with a constant condition vector into a shuffle for easier combining with other shuffles and insert/extract.
static Instruction * canonicalizeScalarSelectOfVecs (SelectInst &Sel, InstCombinerImpl &IC)
If we have a select of vectors with a scalar condition, try to convert that to a vector select by splatting the condition.
static Instruction * foldSelectCmpBitcasts (SelectInst &Sel, InstCombiner::BuilderTy &Builder)
Reuse bitcasted operands between a compare and select: select (cmp (bitcast C), (bitcast D)), (bitcast' C), (bitcast' D) --> bitcast (select (cmp (bitcast C), (bitcast D)), (bitcast C), (bitcast D)).
static Value * foldSelectCmpXchg (SelectInst &SI)
Try to eliminate select instructions that test the returned flag of cmpxchg instructions.
static Instruction * foldSelectFunnelShift (SelectInst &Sel, InstCombiner::BuilderTy &Builder)
Try to reduce a funnel/rotate pattern that includes a compare and select into a funnel shift intrinsic.
static Instruction * foldSelectToCopysign (SelectInst &Sel, InstCombiner::BuilderTy &Builder)
static Instruction * foldSelectToPhiImpl (SelectInst &Sel, BasicBlock *BB, const DominatorTree &DT, InstCombiner::BuilderTy &Builder)
static Instruction * foldSelectToPhi (SelectInst &Sel, const DominatorTree &DT, InstCombiner::BuilderTy &Builder)
static Instruction * foldSelectWithSRem (SelectInst &SI, InstCombinerImpl &IC, IRBuilderBase &Builder)
Tries to reduce a pattern that arises when calculating the remainder of the Euclidean division.
static Value * simplifyNestedSelectsUsingImpliedCond (SelectInst &SI, Value *CondVal, bool CondIsTrue, const DataLayout &DL)
Given that CondVal is known to be CondIsTrue, try to simplify SI.
static Instruction * foldSelectWithFCmpToFabs (SelectInst &SI, InstCombinerImpl &IC)
static Value * foldRoundUpIntegerWithPow2Alignment (SelectInst &SI, InstCombiner::BuilderTy &Builder)
static Instruction * foldSelectOfSymmetricSelect (SelectInst &OuterSelVal, InstCombiner::BuilderTy &Builder)
Folds patterns like: select c2 (select c1 a b) (select c1 b a) into: select (xor c1 c2) b a.
static Instruction * foldNestedSelects (SelectInst &OuterSelVal, InstCombiner::BuilderTy &Builder)
Look for patterns like outer.cond = select i1 inner.cond, i1 alt.cond, i1 false inner.sel = select i1 inner.cond, i8 inner.sel.t, i8 inner.sel.f outer.sel = select i1 outer.cond, i8 outer.sel.t, i8 inner.sel and rewrite it as inner.sel = select i1 cond.alternative, i8 sel.outer.t, i8 sel.inner.t sel.outer = select i1 cond.inner, i8 inner.sel, i8 sel.inner.f.
static bool impliesPoisonOrCond (const Value *ValAssumedPoison, const Value *V, bool Expected)
Return true if V is poison or Expected given that ValAssumedPoison is already poison.
static bool isSafeToRemoveBitCeilSelect (ICmpInst::Predicate Pred, Value *Cond0, const APInt *Cond1, Value *CtlzOp, unsigned BitWidth, bool &ShouldDropNoWrap)
static Instruction * foldBitCeil (SelectInst &SI, IRBuilderBase &Builder, InstCombinerImpl &IC)
static bool matchFMulByZeroIfResultEqZero (InstCombinerImpl &IC, Value *Cmp0, Value *Cmp1, Value *TrueVal, Value *FalseVal, Instruction &CtxI, bool SelectIsNSZ)
static bool hasAffectedValue (Value *V, SmallPtrSetImpl< Value * > &Affected, unsigned Depth)
Check whether the KnownBits of a select arm may be affected by the select condition.
static Value * foldSelectIntoAddConstant (SelectInst &SI, InstCombiner::BuilderTy &Builder)
static Value * foldSelectBitTest (SelectInst &Sel, Value *CondVal, Value *TrueVal, Value *FalseVal, InstCombiner::BuilderTy &Builder, const SimplifyQuery &SQ)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 49 of file InstCombineSelect.cpp.
Function Documentation
canonicalizeSaturatedAdd()
Value * canonicalizeSaturatedAdd (ICmpInst * Cmp, Value * TVal, Value * FVal, InstCombiner::BuilderTy & Builder) static
Definition at line 1217 of file InstCombineSelect.cpp.
References canonicalizeSaturatedAddSigned(), and canonicalizeSaturatedAddUnsigned().
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
canonicalizeSaturatedAddSigned()
Value * canonicalizeSaturatedAddSigned (ICmpInst * Cmp, Value * TVal, Value * FVal, InstCombiner::BuilderTy & Builder) static
Definition at line 1142 of file InstCombineSelect.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::getFlippedStrictnessPredicateAndConstant(), llvm::CmpInst::getInversePredicate(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::isa(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_MaxSignedValue(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_StrictlyPositive(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), std::swap(), and X.
Referenced by canonicalizeSaturatedAdd().
canonicalizeSaturatedAddUnsigned()
Value * canonicalizeSaturatedAddUnsigned (ICmpInst * Cmp, Value * TVal, Value * FVal, InstCombiner::BuilderTy & Builder) static
Definition at line 1041 of file InstCombineSelect.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::CmpInst::getInversePredicate(), llvm::User::getOperand(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_c_Add(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NotForbidPoison(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), std::swap(), X, and Y.
Referenced by canonicalizeSaturatedAdd().
canonicalizeSaturatedSubtract()
Value * canonicalizeSaturatedSubtract (const ICmpInst * ICI, const Value * TrueVal, const Value * FalseVal, InstCombiner::BuilderTy & Builder) static
Transform patterns such as (a > b) ?
a - b : 0 into usub.sat(a, b). There are 8 commuted/swapped variants of this pattern.
Definition at line 973 of file InstCombineSelect.cpp.
References A(), assert(), B(), llvm::CallingConv::C, llvm::CmpInst::getInversePredicate(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), and std::swap().
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
canonicalizeScalarSelectOfVecs()
Instruction * canonicalizeScalarSelectOfVecs (SelectInst & Sel, InstCombinerImpl & IC) static
If we have a select of vectors with a scalar condition, try to convert that to a vector select by splatting the condition.
A splat may get folded with other operations in IR and having all operands of a select be vector types is likely better for vector codegen.
Definition at line 2587 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, Cond, llvm::IRBuilderBase::CreateVectorSplat(), llvm::dyn_cast(), llvm::SelectInst::getCondition(), llvm::Value::getType(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ExtractElt(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::InstCombiner::replaceOperand().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
canonicalizeSelectToShuffle()
Instruction * canonicalizeSelectToShuffle (SelectInst & SI) static
Try to transform a vector select with a constant condition vector into a shuffle for easier combining with other shuffles and insert/extract.
Definition at line 2548 of file InstCombineSelect.cpp.
References llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::Value::getType(), llvm::isa(), llvm::Constant::isNullValue(), llvm::Constant::isOneValue(), llvm::PatternMatch::m_Constant(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldAbsDiff()
Value * foldAbsDiff (ICmpInst * Cmp, Value * TVal, Value * FVal, InstCombiner::BuilderTy & Builder) static
Try to match patterns with select and subtract as absolute difference.
Definition at line 1232 of file InstCombineSelect.cpp.
References A(), B(), llvm::dyn_cast(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::match(), and std::swap().
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
foldAddSubSelect()
Instruction * foldAddSubSelect (SelectInst & SI, InstCombiner::BuilderTy & Builder) static
Turn select C, (X + Y), (X - Y) --> (X + (select C, Y, (-Y))).
This is even legal for FP.
Definition at line 2313 of file InstCombineSelect.cpp.
References llvm::dyn_cast(), llvm::Instruction::setFastMathFlags(), and std::swap().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldBitCeil()
Instruction * foldBitCeil (SelectInst & SI, IRBuilderBase & Builder, InstCombinerImpl & IC) static
Definition at line 3845 of file InstCombineSelect.cpp.
References llvm::InstCombiner::addToWorklist(), llvm::BitWidth, llvm::cast(), llvm::BinaryOperator::Create(), llvm::CmpInst::getInversePredicate(), llvm::Type::getScalarSizeInBits(), llvm::isPowerOf2_32(), isSafeToRemoveBitCeilSelect(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::Masked, llvm::PatternMatch::match(), and std::swap().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldICmpUSubSatWithAndForMostSignificantBitCmp()
Instruction * foldICmpUSubSatWithAndForMostSignificantBitCmp (SelectInst & SI, ICmpInst * ICI, InstCombiner::BuilderTy & Builder) static
Folds: a_sub = call @llvm.usub.sat(x, IntConst1) b_sub = call @llvm.usub.sat(y, IntConst2) or = or a_sub, b_sub cmp = icmp eq or, 0 sel = select cmp, 0, MostSignificantBit into: a_sub' = usub.sat(x, IntConst1 - MostSignificantBit) b_sub' = usub.sat(y, IntConst2 - MostSignificantBit) or = or a_sub', b_sub' and = and or, MostSignificantBit Likewise, for vector arguments as well.
Definition at line 2161 of file InstCombineSelect.cpp.
References A(), B(), llvm::APInt::getBitWidth(), llvm::APInt::getSignMask(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::APInt::isNonNegative(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
foldNestedSelects()
Instruction * foldNestedSelects (SelectInst & OuterSelVal, InstCombiner::BuilderTy & Builder) static
Look for patterns like outer.cond = select i1 inner.cond, i1 alt.cond, i1 false inner.sel = select i1 inner.cond, i8 inner.sel.t, i8 inner.sel.f outer.sel = select i1 outer.cond, i8 outer.sel.t, i8 inner.sel and rewrite it as inner.sel = select i1 cond.alternative, i8 sel.outer.t, i8 sel.inner.t sel.outer = select i1 cond.inner, i8 inner.sel, i8 sel.inner.f.
Definition at line 3333 of file InstCombineSelect.cpp.
References llvm::SelectInst::Create(), llvm::SelectInst::getCondition(), llvm::PatternMatch::m_c_LogicalAnd(), llvm::PatternMatch::m_c_LogicalOp(), llvm::PatternMatch::m_c_LogicalOr(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_LogicalAnd(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::PatternMatch::match_fn(), llvm::none_of(), std::swap(), and llvm::Value::takeName().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldOverflowingAddSubSelect()
Instruction * foldOverflowingAddSubSelect (SelectInst & SI, InstCombiner::BuilderTy & Builder) static
Turn X + Y overflows ?
-1 : X + Y -> uadd_sat X, Y And X - Y overflows ? 0 : X - Y -> usub_sat X, Y Along with a number of patterns similar to: X + Y overflows ? (X < 0 ? INTMIN : INTMAX) : X + Y --> sadd_sat X, Y X - Y overflows ? (X > 0 ? INTMAX : INTMIN) : X - Y --> ssub_sat X, Y
Definition at line 2389 of file InstCombineSelect.cpp.
References llvm::CallingConv::C, llvm::CallInst::Create(), F, llvm::Intrinsic::getOrInsertDeclaration(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, II, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ExtractValue(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_WithOverflowInst(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldRoundUpIntegerWithPow2Alignment()
Value * foldRoundUpIntegerWithPow2Alignment (SelectInst & SI, InstCombiner::BuilderTy & Builder) static
Definition at line 3233 of file InstCombineSelect.cpp.
References Cond, llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_NE, llvm::impliesPoison(), llvm::ICmpInst::isEquality(), llvm::APInt::isMask(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), std::swap(), and X.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectBinOpIdentity()
Instruction * foldSelectBinOpIdentity (SelectInst & Sel, const TargetLibraryInfo & TLI, InstCombinerImpl & IC) static
Replace a select operand based on an equality comparison with the identity constant of a binop.
Definition at line 61 of file InstCombineSelect.cpp.
References llvm::CallingConv::C, llvm::cannotBeNegativeZero(), llvm::dyn_cast(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_UNE, llvm::ConstantExpr::getBinOpIdentity(), llvm::SelectInst::getCondition(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::InstCombiner::getSimplifyQuery(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), llvm::CmpInst::ICMP_EQ, llvm::Instruction::isCommutative(), llvm::ICmpInst::isEquality(), llvm::CmpInst::isFPPredicate(), llvm::PatternMatch::m_AnyZeroFP(), llvm::MIPatternMatch::m_BinOp(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceOperand(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectBitTest()
Value * foldSelectBitTest (SelectInst & Sel, Value * CondVal, Value * TrueVal, Value * FalseVal, InstCombiner::BuilderTy & Builder, const SimplifyQuery & SQ) static
Definition at line 4158 of file InstCombineSelect.cpp.
References assert(), llvm::computeKnownBits(), llvm::decomposeBitTestICmp(), llvm::dyn_cast(), foldSelectICmpAnd(), foldSelectICmpAndBinOp(), llvm::KnownBits::getMaxValue(), llvm::Value::getType(), llvm::SimplifyQuery::getWithInstruction(), llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), llvm::APInt::isPowerOf2(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), std::swap(), and X.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectCmpBitcasts()
Instruction * foldSelectCmpBitcasts (SelectInst & Sel, InstCombiner::BuilderTy & Builder) static
Reuse bitcasted operands between a compare and select: select (cmp (bitcast C), (bitcast D)), (bitcast' C), (bitcast' D) --> bitcast (select (cmp (bitcast C), (bitcast D)), (bitcast C), (bitcast D)).
Definition at line 2608 of file InstCombineSelect.cpp.
References A(), B(), llvm::CallingConv::C, Cond, D(), llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_Cmp(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectCmpXchg()
Value * foldSelectCmpXchg (SelectInst & SI) static
Try to eliminate select instructions that test the returned flag of cmpxchg instructions.
If a select instruction tests the returned flag of a cmpxchg instruction and selects between the returned value of the cmpxchg instruction its compare operand, the result of the select will always be equal to its false value. For example:
cmpxchg = cmpxchg ptr ptr, i64 compare, i64 new_value seq_cst seq_cst val = extractvalue { i64, i1 } cmpxchg, 0 success = extractvalue { i64, i1 } cmpxchg, 1 sel = select i1 success, i64 compare, i64 val ret i64 sel
The returned value of the cmpxchg instruction (val) is the original value located at ptr prior to any update. If the cmpxchg operation succeeds, val must have been equal to compare. Thus, the result of the select is always equal to val, and the code can be simplified to:
cmpxchg = cmpxchg ptr ptr, i64 compare, i64 new_value seq_cst seq_cst val = extractvalue { i64, i1 } cmpxchg, 0 ret i64 val
Definition at line 2675 of file InstCombineSelect.cpp.
References llvm::dyn_cast(), I, Select, and X.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectFunnelShift()
Instruction * foldSelectFunnelShift (SelectInst & Sel, InstCombiner::BuilderTy & Builder) static
Try to reduce a funnel/rotate pattern that includes a compare and select into a funnel shift intrinsic.
Example: rotl32(a, b) --> (b == 0 ? a : ((a >> (32 - b)) | (a << b))) --> call llvm.fshl.i32(a, a, b) fshl32(a, b, c) --> (c == 0 ? a : ((b >> (32 - c)) | (a << c))) --> call llvm.fshl.i32(a, b, c) fshr32(a, b, c) --> (c == 0 ? b : ((a >> (32 - c)) | (b << c))) --> call llvm.fshr.i32(a, b, c)
Definition at line 2728 of file InstCombineSelect.cpp.
References assert(), Cond, llvm::CallInst::Create(), F, llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::Instruction::getModule(), llvm::BinaryOperator::getOpcode(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::Type::getScalarSizeInBits(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::isGuaranteedNotToBePoison(), llvm::isPowerOf2_32(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_LogicalShift(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::PatternMatch::match(), and std::swap().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectICmpAnd()
Value * foldSelectICmpAnd (SelectInst & Sel, Value * CondVal, Value * TrueVal, Value * FalseVal, Value * V, const APInt & AndMask, bool CreateAnd, InstCombiner::BuilderTy & Builder) static
This folds: select (icmp eq (and X, C1)), TC, FC iff C1 is a power 2 and the difference between TC and FC is a power-of-2.
To something like: (shr (and (X, C1)), (log2(C1) - log2(TC-FC))) + FC Or: (shl (and (X, C1)), (log2(TC-FC) - log2(C1))) + FC With some variations depending if FC is larger than TC, or the shift isn't needed, or the bit widths don't match.
Definition at line 131 of file InstCombineSelect.cpp.
References llvm::ConstantFoldBinaryOpOperands(), llvm::APInt::getBitWidth(), llvm::Instruction::getDataLayout(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::APInt::isPowerOf2(), llvm::APInt::isZero(), llvm::APInt::logBase2(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), and Opc.
Referenced by foldSelectBitTest().
foldSelectICmpAndAnd()
Instruction * foldSelectICmpAndAnd (Type * SelType, const ICmpInst * Cmp, Value * TVal, Value * FVal, InstCombiner::BuilderTy & Builder) static
We want to turn: (select (icmp eq (and X, Y), 0), (and (lshr X, Z), 1), 1) into: zext (icmp ne i32 (and X, (or Y, (shl 1, Z))), 0) Note: Z may be 0 if lshr is missing.
Worst-case scenario is that we will replace 5 instructions with 5 different instructions, but we got rid of select.
Definition at line 657 of file InstCombineSelect.cpp.
References B(), llvm::Type::getScalarSizeInBits(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), X, and Y.
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
foldSelectICmpAndBinOp()
Value * foldSelectICmpAndBinOp (Value * CondVal, Value * TrueVal, Value * FalseVal, Value * V, const APInt & AndMask, bool CreateAnd, InstCombiner::BuilderTy & Builder) static
We want to turn: (select (icmp eq (and X, C1), 0), Y, (BinOp Y, C2)) into: IF C2 u>= C1 (BinOp Y, (shl (and X, C1), C3)) ELSE (BinOp Y, (lshr (and X, C1), C3)) iff: 0 on the RHS is the identity value (i.e add, xor, shl, etc...) C1 and C2 are both powers of 2 where: IF C2 u>= C1 C3 = Log(C2) - Log(C1) ELSE C3 = Log(C1) - Log(C2).
This transform handles cases where:
The icmp predicate is inverted
The select operands are reversed
The magnitude of C2 and C1 are flipped
Definition at line 798 of file InstCombineSelect.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::ConstantExpr::getBinOpIdentity(), llvm::BinaryOperator::getOpcode(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::APInt::logBase2(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), and Y.
Referenced by foldSelectBitTest().
foldSelectICmpAndZeroShl()
Value * foldSelectICmpAndZeroShl (const ICmpInst * Cmp, Value * TVal, Value * FVal, InstCombiner::BuilderTy & Builder) static
We want to turn: (select (icmp eq (and X, C1), 0), 0, (shl [nsw/nuw] X, C2)); iff C1 is a mask and the number of its leading zeros is equal to C2 into: shl X, C2.
Definition at line 705 of file InstCombineSelect.cpp.
References llvm::APInt::countLeadingZeros(), llvm::dyn_cast(), llvm::APInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::APInt::isMask(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), std::swap(), and X.
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
foldSelectICmpEq()
Instruction * foldSelectICmpEq (SelectInst & SI, ICmpInst * ICI, InstCombinerImpl & IC) static
Definition at line 2035 of file InstCombineSelect.cpp.
References foldSelectWithExtremeEqCond(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), and std::swap().
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
foldSelectICmpLshrAshr()
Value * foldSelectICmpLshrAshr (const ICmpInst * IC, Value * TrueVal, Value * FalseVal, InstCombiner::BuilderTy & Builder) static
We want to turn: (select (icmp sgt x, C), lshr (X, Y), ashr (X, Y)); iff C s>= -1 (select (icmp slt x, C), ashr (X, Y), lshr (X, Y)); iff C s>= 0 into: ashr (X, Y).
Definition at line 743 of file InstCombineSelect.cpp.
References llvm::cast(), llvm::APInt::getAllOnes(), llvm::Value::getName(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::APInt::getZero(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt_ICMP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), std::swap(), X, and Y.
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
foldSelectICmpMinMax()
Value * foldSelectICmpMinMax (const ICmpInst * Cmp, Value * TVal, Value * FVal, InstCombiner::BuilderTy & Builder, const SimplifyQuery & SQ) static
Try to fold a select to a min/max intrinsic.
Many cases are already handled by matchDecomposedSelectPattern but here we handle the cases where more extensive modification of the IR is required.
Definition at line 596 of file InstCombineSelect.cpp.
References llvm::cast(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::isKnownNonZero(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_NSWAdd(), llvm::PatternMatch::m_NUWAdd(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), and std::swap().
Referenced by llvm::InstCombinerImpl::foldSelectInstWithICmp().
foldSelectIntoAddConstant()
Value * foldSelectIntoAddConstant (SelectInst & SI, InstCombiner::BuilderTy & Builder) static
Definition at line 4098 of file InstCombineSelect.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::FAdd, llvm::FastMathFlags::intersectRewrite(), llvm::CmpInst::isRelational(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FAdd(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_Instruction(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::Value::takeName(), llvm::FastMathFlags::unionValue(), and X.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectOfSymmetricSelect()
Instruction * foldSelectOfSymmetricSelect (SelectInst & OuterSelVal, InstCombiner::BuilderTy & Builder) static
Folds patterns like: select c2 (select c1 a b) (select c1 b a) into: select (xor c1 c2) b a.
Definition at line 3305 of file InstCombineSelect.cpp.
References llvm::SelectInst::Create(), llvm::Value::getType(), llvm::PatternMatch::m_Deferred(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::Xor.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectToCopysign()
Instruction * foldSelectToCopysign (SelectInst & Sel, InstCombiner::BuilderTy & Builder) static
Definition at line 2799 of file InstCombineSelect.cpp.
References llvm::abs(), assert(), llvm::APFloat::bitwiseIsEqual(), llvm::CallingConv::C, Cond, llvm::CallInst::Create(), F, llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::Instruction::getModule(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::APFloat::isNegative(), llvm::isSignBitCheck(), llvm::PatternMatch::m_APFloatAllowPoison(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_ICmp(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectToPhi()
Instruction * foldSelectToPhi (SelectInst & Sel, const DominatorTree & DT, InstCombiner::BuilderTy & Builder) static
Definition at line 2988 of file InstCombineSelect.cpp.
References llvm::dyn_cast(), foldSelectToPhiImpl(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), I, llvm::SetVector< T, Vector, Set, N >::insert(), and llvm::User::operands().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectToPhiImpl()
Instruction * foldSelectToPhiImpl (SelectInst & Sel, BasicBlock * BB, const DominatorTree & DT, InstCombiner::BuilderTy & Builder) static
Definition at line 2927 of file InstCombineSelect.cpp.
References llvm::BasicBlock::begin(), Cond, llvm::DominatorTree::dominates(), llvm::Value::DoPHITranslation(), llvm::dyn_cast(), llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::BasicBlock::getTerminator(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::PatternMatch::m_BasicBlock(), llvm::PatternMatch::m_Br(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), llvm::predecessors(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by foldSelectToPhi().
foldSelectWithExtremeEqCond()
Instruction * foldSelectWithExtremeEqCond (Value * CmpLHS, Value * CmpRHS, Value * TrueVal, Value * FalseVal) static
Fold the following code sequence:
      %XeqZ = icmp eq i64 %X, %Z
      %YeqZ = icmp eq i64 %Y, %Z
      %XeqY = icmp eq i64 %X, %Y
      %not.YeqZ = xor i1 %YeqZ, true
      %and = select i1 %not.YeqZ, i1 %XeqY, i1 false
      %equal = select i1 %XeqZ, i1 %YeqZ, i1 %and
    \code
    into:
      %equal = icmp eq i64 %X, %Y */
Instruction *InstCombinerImpl::foldSelectEqualityTest(SelectInst &Sel) {
  Value *X, *Y, *Z;
  Value *XeqY, *XeqZ = Sel.getCondition(), *YeqZ = Sel.getTrueValue();
  if (!match(XeqZ, m_SpecificICmp(ICmpInst::ICMP_EQ, m_Value(X), m_Value(Z))))
    return nullptr;
  if (!match(YeqZ,
             m_c_SpecificICmp(ICmpInst::ICMP_EQ, m_Value(Y), m_Specific(Z))))
    std::swap(X, Z);
  if (!match(YeqZ,
             m_c_SpecificICmp(ICmpInst::ICMP_EQ, m_Value(Y), m_Specific(Z))))
    return nullptr;
  if (!match(Sel.getFalseValue(),
             m_c_LogicalAnd(m_Not(m_Specific(YeqZ)), m_Value(XeqY))))
    return nullptr;
  if (!match(XeqY,
             m_c_SpecificICmp(ICmpInst::ICMP_EQ, m_Specific(X), m_Specific(Y))))
    return nullptr;
  cast<ICmpInst>(XeqY)->setSameSign(false);
  return replaceInstUsesWith(Sel, XeqY);
}
See if this is a pattern like:
%old_cmp1 = icmp slt i32 %x, C2
%old_replacement = select i1 %old_cmp1, i32 %target_low, i32 %target_high
%old_x_offseted = add i32 %x, C1
%old_cmp0 = icmp ult i32 %old_x_offseted, C0
%r = select i1 %old_cmp0, i32 %x, i32 %old_replacement
This can be rewritten as more canonical pattern:
%new_cmp1 = icmp slt i32 %x, -C1
%new_cmp2 = icmp sge i32 %x, C0-C1
%new_clamped_low = select i1 %new_cmp1, i32 %target_low, i32 %x
%r = select i1 %new_cmp2, i32 %target_high, i32 %new_clamped_low
Iff -C1 s<= C2 s<= C0-C1
Also ULT predicate can also be UGT iff C0 != -1 (+invert result)
SLT predicate can also be SGT iff C2 != INT_MAX (+invert res.)
static Value *canonicalizeClampLike(SelectInst &Sel0, ICmpInst &Cmp0,
                                    InstCombiner::BuilderTy &Builder,
                                    InstCombiner &IC) {
  Value *X = Sel0.getTrueValue();
  Value *Sel1 = Sel0.getFalseValue();
First match the condition of the outermost select.
Said condition must be one-use.
  if (!Cmp0.hasOneUse())
    return nullptr;
  ICmpInst::Predicate Pred0 = Cmp0.getPredicate();
  Value *Cmp00 = Cmp0.getOperand(0);
  Constant *C0;
  if (!match(Cmp0.getOperand(1),
             m_CombineAnd(m_AnyIntegralConstant(), m_Constant(C0))))
    return nullptr;
  if (!isa<SelectInst>(Sel1)) {
    Pred0 = ICmpInst::getInversePredicate(Pred0);
    std::swap(X, Sel1);
  }
Canonicalize Cmp0 into ult or uge.
FIXME: we shouldn't care about lanes that are 'undef' in the end?
  switch (Pred0) {
  case ICmpInst::Predicate::ICMP_ULT:
  case ICmpInst::Predicate::ICMP_UGE:
Although icmp ult %x, 0 is an unusual thing to try and should generally
have been simplified, it does not verify with undef inputs so ensure we
are not in a strange state.
    if (!match(C0, m_SpecificInt_ICMP(
                       ICmpInst::Predicate::ICMP_NE,
                       APInt::getZero(C0->getType()->getScalarSizeInBits()))))
      return nullptr;
    break; // Great!
  case ICmpInst::Predicate::ICMP_ULE:
  case ICmpInst::Predicate::ICMP_UGT:
We want to canonicalize it to 'ult' or 'uge', so we'll need to increment
C0, which again means it must not have any all-ones elements.
    if (!match(C0,
               m_SpecificInt_ICMP(
                   ICmpInst::Predicate::ICMP_NE,
                   APInt::getAllOnes(C0->getType()->getScalarSizeInBits()))))
      return nullptr; // Can't do, have all-ones element[s].
    Pred0 = ICmpInst::getFlippedStrictnessPredicate(Pred0);
    C0 = InstCombiner::AddOne(C0);
    break;
  default:
    return nullptr; // Unknown predicate.
  }
Now that we've canonicalized the ICmp, we know the X we expect;
the select in other hand should be one-use.
  if (!Sel1->hasOneUse())
    return nullptr;
If the types do not match, look through any truncs to the underlying
instruction.
  if (Cmp00->getType() != X->getType() && X->hasOneUse())
    match(X, m_TruncOrSelf(m_Value(X)));
We now can finish matching the condition of the outermost select:
it should either be the X itself, or an addition of some constant to X.
  Constant *C1;
  if (Cmp00 == X)
    C1 = ConstantInt::getNullValue(X->getType());
  else if (!match(Cmp00,
                  m_Add(m_Specific(X),
                        m_CombineAnd(m_AnyIntegralConstant(), m_Constant(C1)))))
    return nullptr;
  Value *Cmp1;
  CmpPredicate Pred1;
  Constant *C2;
  Value *ReplacementLow, *ReplacementHigh;
  if (!match(Sel1, m_Select(m_Value(Cmp1), m_Value(ReplacementLow),
                            m_Value(ReplacementHigh))) ||
      !match(Cmp1,
             m_ICmp(Pred1, m_Specific(X),
                    m_CombineAnd(m_AnyIntegralConstant(), m_Constant(C2)))))
    return nullptr;
  if (!Cmp1->hasOneUse() && (Cmp00 == X || !Cmp00->hasOneUse()))
    return nullptr; // Not enough one-use instructions for the fold.
FIXME: this restriction could be relaxed if Cmp1 can be reused as one of
two comparisons we'll need to build.
Canonicalize Cmp1 into the form we expect.
FIXME: we shouldn't care about lanes that are 'undef' in the end?
  switch (Pred1) {
  case ICmpInst::Predicate::ICMP_SLT:
    break;
  case ICmpInst::Predicate::ICMP_SLE:
We'd have to increment C2 by one, and for that it must not have signed
max element, but then it would have been canonicalized to 'slt' before
we get here. So we can't do anything useful with 'sle'.
    return nullptr;
  case ICmpInst::Predicate::ICMP_SGT:
We want to canonicalize it to 'slt', so we'll need to increment C2,
which again means it must not have any signed max elements.
    if (!match(C2,
               m_SpecificInt_ICMP(ICmpInst::Predicate::ICMP_NE,
                                  APInt::getSignedMaxValue(
                                      C2->getType()->getScalarSizeInBits()))))
      return nullptr; // Can't do, have signed max element[s].
    C2 = InstCombiner::AddOne(C2);
    [[fallthrough]];
  case ICmpInst::Predicate::ICMP_SGE:
Also non-canonical, but here we don't need to change C2,
so we don't have any restrictions on C2, so we can just handle it.
    Pred1 = ICmpInst::Predicate::ICMP_SLT;
    std::swap(ReplacementLow, ReplacementHigh);
    break;
  default:
    return nullptr; // Unknown predicate.
  }
  assert(Pred1 == ICmpInst::Predicate::ICMP_SLT &&
         "Unexpected predicate type.");
The thresholds of this clamp-like pattern.
  auto *ThresholdLowIncl = ConstantExpr::getNeg(C1);
  auto *ThresholdHighExcl = ConstantExpr::getSub(C0, C1);
  assert((Pred0 == ICmpInst::Predicate::ICMP_ULT ||
          Pred0 == ICmpInst::Predicate::ICMP_UGE) &&
         "Unexpected predicate type.");
  if (Pred0 == ICmpInst::Predicate::ICMP_UGE)
    std::swap(ThresholdLowIncl, ThresholdHighExcl);
The fold has a precondition 1: C2 s>= ThresholdLow
  auto *Precond1 = ConstantFoldCompareInstOperands(
      ICmpInst::Predicate::ICMP_SGE, C2, ThresholdLowIncl, IC.getDataLayout());
  if (!Precond1 || !match(Precond1, m_One()))
    return nullptr;
The fold has a precondition 2: C2 s<= ThresholdHigh
  auto *Precond2 = ConstantFoldCompareInstOperands(
      ICmpInst::Predicate::ICMP_SLE, C2, ThresholdHighExcl, IC.getDataLayout());
  if (!Precond2 || !match(Precond2, m_One()))
    return nullptr;
If we are matching from a truncated input, we need to sext the
ReplacementLow and ReplacementHigh values. Only do the transform if they
are free to extend due to being constants.
  if (X->getType() != Sel0.getType()) {
    Constant *LowC, *HighC;
    if (!match(ReplacementLow, m_ImmConstant(LowC)) ||
        !match(ReplacementHigh, m_ImmConstant(HighC)))
      return nullptr;
    const DataLayout &DL = Sel0.getDataLayout();
    ReplacementLow =
        ConstantFoldCastOperand(Instruction::SExt, LowC, X->getType(), DL);
    ReplacementHigh =
        ConstantFoldCastOperand(Instruction::SExt, HighC, X->getType(), DL);
    assert(ReplacementLow && ReplacementHigh &&
           "Constant folding of ImmConstant cannot fail");
  }
All good, finally emit the new pattern.
  Value *ShouldReplaceLow = Builder.CreateICmpSLT(X, ThresholdLowIncl);
  Value *ShouldReplaceHigh = Builder.CreateICmpSGE(X, ThresholdHighExcl);
  Value *MaybeReplacedLow =
      Builder.CreateSelect(ShouldReplaceLow, ReplacementLow, X);
Create the final select. If we looked through a truncate above, we will
need to retruncate the result.
  Value *MaybeReplacedHigh = Builder.CreateSelect(
      ShouldReplaceHigh, ReplacementHigh, MaybeReplacedLow);
  return Builder.CreateTrunc(MaybeReplacedHigh, Sel0.getType());
}
If we have
%cmp = icmp [canonical predicate] i32 %x, C0
%r = select i1 %cmp, i32 %y, i32 C1
Where C0 != C1 and %x may be different from %y, see if the constant that we
will have if we flip the strictness of the predicate (i.e. without changing
the result) is identical to the C1 in select. If it matches we can change
original comparison to one with swapped predicate, reuse the constant,
and swap the hands of select.
static Instruction *
tryToReuseConstantFromSelectInComparison(SelectInst &Sel, ICmpInst &Cmp,
                                         InstCombinerImpl &IC) {
  CmpPredicate Pred;
  Value *X;
  Constant *C0;
  if (!match(&Cmp, m_OneUse(m_ICmp(
                       Pred, m_Value(X),
                       m_CombineAnd(m_AnyIntegralConstant(), m_Constant(C0))))))
    return nullptr;
If comparison predicate is non-relational, we won't be able to do anything.
  if (ICmpInst::isEquality(Pred))
    return nullptr;
If comparison predicate is non-canonical, then we certainly won't be able
to make it canonical; canonicalizeCmpWithConstant() already tried.
  if (!InstCombiner::isCanonicalPredicate(Pred))
    return nullptr;
If the [input] type of comparison and select type are different, lets abort
for now. We could try to compare constants with trunc/[zs]ext though.
  if (C0->getType() != Sel.getType())
    return nullptr;
ULT with 'add' of a constant is canonical. See foldICmpAddConstant().
FIXME: Are there more magic icmp predicate+constant pairs we must avoid?
Or should we just abandon this transform entirely?
  if (Pred == CmpInst::ICMP_ULT && match(X, m_Add(m_Value(), m_Constant())))
    return nullptr;
  Value *SelVal0, *SelVal1; // We do not care which one is from where.
  match(&Sel, m_Select(m_Value(), m_Value(SelVal0), m_Value(SelVal1)));
At least one of these values we are selecting between must be a constant
else we'll never succeed.
  if (!match(SelVal0, m_AnyIntegralConstant()) &&
      !match(SelVal1, m_AnyIntegralConstant()))
    return nullptr;
Does this constant C match any of the <tt>select</tt> values?
  auto MatchesSelectValue = [SelVal0, SelVal1](Constant *C) {
    return C->isElementWiseEqual(SelVal0) || C->isElementWiseEqual(SelVal1);
  };
If C0 <em>already</em> matches true/false value of select, we are done.
  if (MatchesSelectValue(C0))
    return nullptr;
Check the constant we'd have with flipped-strictness predicate.
  auto FlippedStrictness = getFlippedStrictnessPredicateAndConstant(Pred, C0);
  if (!FlippedStrictness)
    return nullptr;
If said constant doesn't match either, then there is no hope,
  if (!MatchesSelectValue(FlippedStrictness->second))
    return nullptr;
It matched! Lets insert the new comparison just before select.
  InstCombiner::BuilderTy::InsertPointGuard Guard(IC.Builder);
  IC.Builder.SetInsertPoint(&Sel);
  Pred = ICmpInst::getSwappedPredicate(Pred); // Yes, swapped.
  Value *NewCmp = IC.Builder.CreateICmp(Pred, X, FlippedStrictness->second,
                                        Cmp.getName() + ".inv");
  IC.replaceOperand(Sel, 0, NewCmp);
  Sel.swapValues();
  Sel.swapProfMetadata();
  return &Sel;
}
static Instruction *foldSelectZeroOrOnes(ICmpInst *Cmp, Value *TVal,
                                         Value *FVal,
                                         InstCombiner::BuilderTy &Builder) {
  if (!Cmp->hasOneUse())
    return nullptr;
  const APInt *CmpC;
  if (!match(Cmp->getOperand(1), m_APIntAllowPoison(CmpC)))
    return nullptr;
(X u< 2) ? -X : -1 --> sext (X != 0)
  Value *X = Cmp->getOperand(0);
  if (Cmp->getPredicate() == ICmpInst::ICMP_ULT && *CmpC == 2 &&
      match(TVal, m_Neg(m_Specific(X))) && match(FVal, m_AllOnes()))
    return new SExtInst(Builder.CreateIsNotNull(X), TVal->getType());
(X u> 1) ? -1 : -X --> sext (X != 0)
  if (Cmp->getPredicate() == ICmpInst::ICMP_UGT && *CmpC == 1 &&
      match(FVal, m_Neg(m_Specific(X))) && match(TVal, m_AllOnes()))
    return new SExtInst(Builder.CreateIsNotNull(X), TVal->getType());
  return nullptr;
}
static Value *foldSelectInstWithICmpConst(SelectInst &SI, ICmpInst *ICI,
                                          InstCombiner::BuilderTy &Builder) {
  const APInt *CmpC;
  Value *V;
  CmpPredicate Pred;
  if (!match(ICI, m_ICmp(Pred, m_Value(V), m_APInt(CmpC))))
    return nullptr;
Match clamp away from min/max value as a max/min operation.
  Value *TVal = SI.getTrueValue();
  Value *FVal = SI.getFalseValue();
  if (Pred == ICmpInst::ICMP_EQ && V == FVal) {
(V == UMIN) ? UMIN+1 : V --> umax(V, UMIN+1)
    if (CmpC->isMinValue() && match(TVal, m_SpecificInt(*CmpC + 1)))
      return Builder.CreateBinaryIntrinsic(Intrinsic::umax, V, TVal);
(V == UMAX) ? UMAX-1 : V --> umin(V, UMAX-1)
    if (CmpC->isMaxValue() && match(TVal, m_SpecificInt(*CmpC - 1)))
      return Builder.CreateBinaryIntrinsic(Intrinsic::umin, V, TVal);
(V == SMIN) ? SMIN+1 : V --> smax(V, SMIN+1)
    if (CmpC->isMinSignedValue() && match(TVal, m_SpecificInt(*CmpC + 1)))
      return Builder.CreateBinaryIntrinsic(Intrinsic::smax, V, TVal);
(V == SMAX) ? SMAX-1 : V --> smin(V, SMAX-1)
    if (CmpC->isMaxSignedValue() && match(TVal, m_SpecificInt(*CmpC - 1)))
      return Builder.CreateBinaryIntrinsic(Intrinsic::smin, V, TVal);
  }
Fold icmp(X) ? f(X) : C to f(X) when f(X) is guaranteed to be equal to C
for all X in the exact range of the inverse predicate.
  Instruction *Op;
  const APInt *C;
  CmpInst::Predicate CPred;
  if (match(&SI, m_Select(m_Specific(ICI), m_APInt(C), m_Instruction(Op))))
    CPred = ICI->getPredicate();
  else if (match(&SI, m_Select(m_Specific(ICI), m_Instruction(Op), m_APInt(C))))
    CPred = ICI->getInversePredicate();
  else
    return nullptr;
  ConstantRange InvDomCR = ConstantRange::makeExactICmpRegion(CPred, *CmpC);
  const APInt *OpC;
  if (match(Op, m_BinOp(m_Specific(V), m_APInt(OpC)))) {
    ConstantRange R = InvDomCR.binaryOp(
        static_cast<Instruction::BinaryOps>(Op->getOpcode()), *OpC);
    if (R == *C) {
      Op->dropPoisonGeneratingFlags();
      return Op;
    }
  }
  if (auto *MMI = dyn_cast<MinMaxIntrinsic>(Op);
      MMI && MMI->getLHS() == V && match(MMI->getRHS(), m_APInt(OpC))) {
    ConstantRange R = ConstantRange::intrinsic(MMI->getIntrinsicID(),
                                               {InvDomCR, ConstantRange(*OpC)});
    if (R == *C) {
      MMI->dropPoisonGeneratingAnnotations();
      return MMI;
    }
  }
  return nullptr;
}
/** <tt>A == MIN_INT ? B != MIN_INT : A < B</tt> --> <tt>A < B</tt>
    <tt>A == MAX_INT ? B != MAX_INT : A > B</tt> --> <tt>A > B</tt>
Definition at line 1997 of file InstCombineSelect.cpp.
References B(), llvm::BitWidth, llvm::CallingConv::C, llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::Value::getType(), llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isGT(), llvm::ICmpInst::isLT(), llvm::CmpInst::isSigned(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by foldSelectICmpEq().
foldSelectWithFCmpToFabs()
Instruction * foldSelectWithFCmpToFabs (SelectInst & SI, InstCombinerImpl & IC) static
Definition at line 3089 of file InstCombineSelect.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::canIgnoreSignBitOfNaN(), llvm::canIgnoreSignBitOfZero(), llvm::cast(), llvm::UnaryOperator::CreateFNegFMF(), llvm::IRBuilderBase::CreateUnaryIntrinsic(), llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::InstCombiner::getSimplifyQuery(), llvm::CmpInst::getSwappedPredicate(), llvm::SimplifyQuery::getWithInstruction(), llvm::Value::hasOneUse(), llvm::isKnownNeverNaN(), llvm::CmpInst::isOrdered(), llvm::isSignBitCheck(), llvm::CmpInst::isUnordered(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), llvm::InstCombiner::replaceInstUsesWith(), llvm::Instruction::setFastMathFlags(), std::swap(), and X.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectWithSRem()
Instruction * foldSelectWithSRem (SelectInst & SI, InstCombinerImpl & IC, IRBuilderBase & Builder) static
Tries to reduce a pattern that arises when calculating the remainder of the Euclidean division.
When the divisor is a power of two and is guaranteed not to be negative, a signed remainder can be folded with a bitwise and.
(x % n) < 0 ? (x % n) + n : (x % n) -> x & (n - 1)
Definition at line 3009 of file InstCombineSelect.cpp.
References llvm::Add, llvm::CallingConv::C, llvm::Constant::getAllOnesValue(), llvm::Value::getType(), llvm::InstCombiner::isKnownToBeAPowerOfTwo(), llvm::isSignBitCheck(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and std::swap().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSelectZeroOrFixedOp()
Instruction * foldSelectZeroOrFixedOp (SelectInst & SI, InstCombinerImpl & IC) static
Definition at line 909 of file InstCombineSelect.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::CmpInst::ICMP_NE, llvm::InstCombiner::InsertNewInstBefore(), llvm::isa(), llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Intrinsic(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_FShl(), llvm::PatternMatch::m_FShr(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_IDiv(), llvm::PatternMatch::m_IRem(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::Constant::mergeUndefsWith(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), std::swap(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
foldSetClearBits()
Instruction * foldSetClearBits (SelectInst & Sel, InstCombiner::BuilderTy & Builder) static
Canonicalize a set or clear of a masked set of constant bits to select-of-constants form.
Definition at line 866 of file InstCombineSelect.cpp.
References llvm::CallingConv::C, Cond, F, llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::Constant::getNullValue(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), T, and X.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
getSelectFoldableOperands()
unsigned getSelectFoldableOperands (BinaryOperator * I) static
We want to turn code that looks like this: C = or A, B D = select cond, C, A into: C = select cond, B, 0 D = or A, C.
Assuming that the specified instruction is an operand to the select, return a bitmask indicating which operands of this instruction are foldable if they equal the other incoming value of the select.
Definition at line 229 of file InstCombineSelect.cpp.
References I.
Referenced by llvm::InstCombinerImpl::foldSelectIntoOp().
hasAffectedValue()
bool hasAffectedValue (Value * V, SmallPtrSetImpl< Value * > & Affected, unsigned Depth) static
Check whether the KnownBits of a select arm may be affected by the select condition.
Definition at line 4071 of file InstCombineSelect.cpp.
References llvm::any_of(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::Depth, llvm::dyn_cast(), I, llvm::isa(), and llvm::MaxAnalysisRecursionDepth.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
impliesPoisonOrCond()
bool impliesPoisonOrCond (const Value * ValAssumedPoison, const Value * V, bool Expected) static
Return true if V is poison or Expected given that ValAssumedPoison is already poison.
For example, if ValAssumedPoison is icmp samesign X, 10 and V is icmp ne X, 5, impliesPoisonOrCond returns true.
Definition at line 3407 of file InstCombineSelect.cpp.
References llvm::BitWidth, llvm::dyn_cast(), llvm::APInt::getBitWidth(), llvm::ICmpInst::getInverseCmpPredicate(), llvm::APInt::getSignedMinValue(), llvm::APInt::getZero(), llvm::ConstantRange::icmp(), llvm::impliesPoison(), llvm::APInt::isNonNegative(), LHS, llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_APIntForbidPoison(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::foldSelectOfBools().
isSafeToRemoveBitCeilSelect()
bool isSafeToRemoveBitCeilSelect (ICmpInst::Predicate Pred, Value * Cond0, const APInt * Cond1, Value * CtlzOp, unsigned BitWidth, bool & ShouldDropNoWrap) static
Definition at line 3750 of file InstCombineSelect.cpp.
References llvm::ConstantRange::add(), llvm::ConstantRange::binaryNot(), llvm::BitWidth, llvm::CallingConv::C, llvm::CmpInst::getInversePredicate(), llvm::APInt::getSignMask(), llvm::ConstantRange::icmp(), llvm::CmpInst::ICMP_UGE, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::ConstantRange::makeExactICmpRegion(), llvm::PatternMatch::match(), and llvm::ConstantRange::sub().
Referenced by foldBitCeil().
isSelect01()
bool isSelect01 (const APInt & C1I, const APInt & C2I) static
Definition at line 495 of file InstCombineSelect.cpp.
References llvm::APInt::isAllOnes(), llvm::APInt::isOne(), and llvm::APInt::isZero().
Referenced by llvm::InstCombinerImpl::foldSelectIntoOp().
matchFMulByZeroIfResultEqZero()
bool matchFMulByZeroIfResultEqZero (InstCombinerImpl & IC, Value * Cmp0, Value * Cmp1, Value * TrueVal, Value * FalseVal, Instruction & CtxI, bool SelectIsNSZ) static
Definition at line 4052 of file InstCombineSelect.cpp.
References llvm::cast(), llvm::InstCombinerImpl::fmulByZeroIsZero(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::FastMathFlags::setNoSignedZeros().
Referenced by llvm::InstCombinerImpl::visitSelectInst().
simplifyNestedSelectsUsingImpliedCond()
Value * simplifyNestedSelectsUsingImpliedCond (SelectInst & SI, Value * CondVal, bool CondIsTrue, const DataLayout & DL) static
Given that CondVal is known to be CondIsTrue, try to simplify SI.
Definition at line 3059 of file InstCombineSelect.cpp.
References assert(), DL, llvm::Value::getType(), and llvm::isImpliedCondition().
Referenced by llvm::InstCombinerImpl::visitSelectInst().