LLVM: lib/Transforms/InstCombine/InstCombineAndOrXor.cpp File Reference
InstCombineAndOrXor.cpp File Reference
#include "InstCombineInternal.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/Analysis/CmpInstAnalysis.h"
#include "llvm/Analysis/FloatingPointPredicateUtils.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/Transforms/Utils/Local.h"
Classes
struct IntPart
struct DecomposedBitMaskMul
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "instcombine"
Enumerations
enum MaskedICmpType {
AMask_AllOnes = 1 , AMask_NotAllOnes = 2 , BMask_AllOnes = 4 , BMask_NotAllOnes = 8 ,
Mask_AllZeros = 16 , Mask_NotAllZeros = 32 , AMask_Mixed = 64 , AMask_NotMixed = 128 ,
BMask_Mixed = 256 , BMask_NotMixed = 512
}
Classify (icmp eq (A & B), C) and (icmp ne (A & B), C) as matching patterns that can be simplified.
Functions
static Value * getNewICmpValue (unsigned Code, bool Sign, Value *LHS, Value *RHS, InstCombiner::BuilderTy &Builder)
This is the complement of getICmpCode, which turns an opcode and two operands into either a constant true or false, or a brand new ICmp instruction.
static Value * getFCmpValue (unsigned Code, Value *LHS, Value *RHS, InstCombiner::BuilderTy &Builder, FMFSource FMF)
This is the complement of getFCmpCode, which turns an opcode and two operands into either a FCmp instruction, or a true/false constant.
static unsigned getMaskedICmpType (Value *A, Value *B, Value *C, ICmpInst::Predicate Pred)
Return the set of patterns (from MaskedICmpType) that (icmp SCC (A & B), C) satisfies.
static unsigned conjugateICmpMask (unsigned Mask)
Convert an analysis of a masked ICmp into its equivalent if all boolean operations had the opposite sense.
static bool decomposeBitTest (Value *Cond, CmpInst::Predicate &Pred, Value *&X, Value *&Y, Value *&Z)
static std::optional< std::pair< unsigned, unsigned > > getMaskedTypeForICmpPair (Value *&A, Value *&B, Value *&C, Value *&D, Value *&E, Value *LHS, Value *RHS, ICmpInst::Predicate &PredL, ICmpInst::Predicate &PredR)
Handle (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E).
static Value * foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed (Value *LHS, Value *RHS, bool IsAnd, Value *A, Value *B, Value *D, Value *E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, InstCombiner::BuilderTy &Builder)
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side is of type Mask_NotAllZeros and the right hand side is of type BMask_Mixed.
static Value * foldLogOpOfMaskedICmpsAsymmetric (Value *LHS, Value *RHS, bool IsAnd, Value *A, Value *B, Value *C, Value *D, Value *E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, unsigned LHSMask, unsigned RHSMask, InstCombiner::BuilderTy &Builder)
Try to fold (icmp(A & B) ==/!= 0) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side and the right hand side aren't of the common mask pattern type.
static Value * foldLogOpOfMaskedICmps (Value *LHS, Value *RHS, bool IsAnd, bool IsLogical, InstCombiner::BuilderTy &Builder, const SimplifyQuery &Q)
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y).
static Value * foldAndOrOfICmpsWithPow2AndWithZero (InstCombiner::BuilderTy &Builder, ICmpInst *LHS, ICmpInst *RHS, bool IsAnd, const SimplifyQuery &Q)
static Value * foldSignedTruncationCheck (ICmpInst *ICmp0, ICmpInst *ICmp1, Instruction &CxtI, InstCombiner::BuilderTy &Builder)
General pattern: X & Y.
static Value * foldIsPowerOf2OrZero (ICmpInst *Cmp0, ICmpInst *Cmp1, bool IsAnd, InstCombiner::BuilderTy &Builder, InstCombinerImpl &IC)
Fold (icmp eq ctpop(X) 1) | (icmp eq X 0) into (icmp ult ctpop(X) 2) and fold (icmp ne ctpop(X) 1) & (icmp ne X 0) into (icmp ugt ctpop(X) 1).
static Value * foldIsPowerOf2 (ICmpInst *Cmp0, ICmpInst *Cmp1, bool JoinedByAnd, InstCombiner::BuilderTy &Builder, InstCombinerImpl &IC)
Reduce a pair of compares that check if a value has exactly 1 bit set.
static Value * foldNegativePower2AndShiftedMask (Value *A, Value *B, Value *D, Value *E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, InstCombiner::BuilderTy &Builder)
Try to fold (icmp(A & B) == 0) & (icmp(A & D) != E) into (icmp A u< D) iff B is a contiguous set of ones starting from the most significant bit (negative power of 2), D and E are equal, and D is a contiguous set of ones starting at the most significant zero bit in B.
static Value * foldPowerOf2AndShiftedMask (ICmpInst *Cmp0, ICmpInst *Cmp1, bool JoinedByAnd, InstCombiner::BuilderTy &Builder)
Try to fold ((icmp X u< P) & (icmp(X & M) != M)) or ((icmp X s> -1) & (icmp(X & M) != M)) into (icmp X u< M).
static Value * foldUnsignedUnderflowCheck (ICmpInst *ZeroICmp, ICmpInst *UnsignedICmp, bool IsAnd, const SimplifyQuery &Q, InstCombiner::BuilderTy &Builder)
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
static std::optional< IntPart > matchIntPart (Value *V)
Match an extraction of bits from an integer.
static Value * extractIntPart (const IntPart &P, IRBuilderBase &Builder)
Materialize an extraction of bits from an integer in IR.
static Value * foldAndOrOfICmpsWithConstEq (ICmpInst *Cmp0, ICmpInst *Cmp1, bool IsAnd, bool IsLogical, InstCombiner::BuilderTy &Builder, const SimplifyQuery &Q, Instruction &I)
Reduce logic-of-compares with equality to a constant by substituting a common operand with the constant.
static Value * stripSignOnlyFPOps (Value *Val)
Ignore all operations which only change the sign of a value, returning the underlying magnitude value.
static bool matchIsNotNaN (FCmpInst::Predicate P, Value *LHS, Value *RHS)
Matches canonical form of isnan, fcmp ord x, 0.
static bool matchUnorderedInfCompare (FCmpInst::Predicate P, Value *LHS, Value *RHS)
Matches fcmp u__ x, +/-inf.
static Value * matchIsFiniteTest (InstCombiner::BuilderTy &Builder, FCmpInst *LHS, FCmpInst *RHS)
and (fcmp ord x, 0), (fcmp u* x, inf) -> fcmp o* x, inf
static bool matchIsFPClassLikeFCmp (Value *Op, Value *&ClassVal, uint64_t &ClassMask)
Match an fcmp against a special value that performs a test possible by llvm.is.fpclass.
static Instruction * reassociateFCmps (BinaryOperator &BO, InstCombiner::BuilderTy &Builder)
This a limited reassociation for a special case (see above) where we are checking if two values are either both NAN (unordered) or not-NAN (ordered).
static Instruction * matchDeMorgansLaws (BinaryOperator &I, InstCombiner &IC)
Match variations of De Morgan's Laws: (~A & ~B) == (~(A | B)) (~A | ~B) == (~(A & B)).
static Instruction * foldLogicCastConstant (BinaryOperator &Logic, CastInst *Cast, InstCombinerImpl &IC)
Fold {and,or,xor} (cast X), C.
static Instruction * foldAndToXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static Instruction * foldOrToXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static bool canNarrowShiftAmt (Constant *C, unsigned BitWidth)
Return true if a constant shift amount is always less than the specified bit-width.
static Instruction * foldComplexAndOrPatterns (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
Try folding relatively complex patterns for both And and Or operations with all And and Or swapped.
static Instruction * reassociateForUses (BinaryOperator &BO, InstCombinerImpl::BuilderTy &Builder)
Try to reassociate a pair of binops so that values with one use only are part of the same instruction.
static Instruction * canonicalizeLogicFirst (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static Instruction * foldBitwiseLogicWithIntrinsics (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static Value * simplifyAndOrWithOpReplaced (Value *V, Value *Op, Value *RepOp, bool SimplifyOnly, InstCombinerImpl &IC, unsigned Depth=0)
static Instruction * matchFunnelShift (Instruction &Or, InstCombinerImpl &IC)
Match UB-safe variants of the funnel shift intrinsic.
static Value * matchOrConcat (Instruction &Or, InstCombiner::BuilderTy &Builder)
Attempt to combine or(zext(x),shl(zext(y),bw/2) concat packing patterns.
static bool areInverseVectorBitmasks (Constant *C1, Constant *C2)
If all elements of two constant vectors are 0/-1 and inverses, return true.
static Value * foldAndOrOfICmpEqConstantAndICmp (ICmpInst *LHS, ICmpInst *RHS, bool IsAnd, bool IsLogical, IRBuilderBase &Builder)
static Value * foldOrOfInversions (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static bool matchSubIntegerPackFromVector (Value *V, Value *&Vec, int64_t &VecOffset, SmallBitVector &Mask, const DataLayout &DL)
Match V as "shufflevector -> bitcast" or "extractelement -> zext -> shl" patterns, which extract vector elements and pack them in the same relative positions.
static Instruction * foldIntegerPackFromVector (Instruction &I, InstCombiner::BuilderTy &Builder, const DataLayout &DL)
Try to fold the join of two scalar integers whose contents are packed elements of the same vector.
static bool matchZExtedSubInteger (Value *V, Value *&Int, APInt &Mask, uint64_t &Offset, bool &IsShlNUW, bool &IsShlNSW)
Match V as "lshr -> mask -> zext -> shl".
static Value * foldIntegerRepackThroughZExt (Value *Lhs, Value *Rhs, InstCombiner::BuilderTy &Builder)
Try to fold the join of two scalar integers whose bits are unpacked and zexted from the same source integer.
static std::optional< DecomposedBitMaskMul > matchBitmaskMul (Value *V)
static Value * foldBitmaskMul (Value *Op0, Value *Op1, InstCombiner::BuilderTy &Builder)
(A & N) * C + (A & M) * C -> (A & (N + M)) & C This also accepts the equivalent select form of (A & N) * C expressions i.e.
static Value * foldOrUnsignedUMulOverflowICmp (BinaryOperator &I, InstCombiner::BuilderTy &Builder, const DataLayout &DL)
Fold Res, Overflow = (umul.with.overflow x c1); (or Overflow (ugt Res c2)) --> (ugt x (c2/c1)).
static Value * FoldOrOfSelectSmaxToAbs (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
Fold select(X >s 0, 0, -X) | smax(X, 0) --> abs(X) select(X <s 0, -X, 0) | smax(X, 0) --> abs(X).
static Instruction * foldXorToXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
A ^ B can be specified using other logic ops in a variety of patterns.
static Instruction * visitMaskedMerge (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
If we have a masked merge, in the canonical form of: (assuming that A only has one use.) | A | |B| ((x ^ y) & M) ^ y | D |.
static Instruction * foldNotXor (BinaryOperator &I, InstCombiner::BuilderTy &Builder)
static Instruction * canonicalizeAbs (BinaryOperator &Xor, InstCombiner::BuilderTy &Builder)
Canonicalize a shifty way to code absolute value to the more common pattern that uses negation and select.
static bool canFreelyInvert (InstCombiner &IC, Value *Op, Instruction *IgnoredUser)
static Value * freelyInvert (InstCombinerImpl &IC, Value *Op, Instruction *IgnoredUser)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 29 of file InstCombineAndOrXor.cpp.
Enumeration Type Documentation
MaskedICmpType
enum MaskedICmpType
Classify (icmp eq (A & B), C) and (icmp ne (A & B), C) as matching patterns that can be simplified.
One of A and B is considered the mask. The other is the value. This is described as the "AMask" or "BMask" part of the enum. If the enum contains only "Mask", then both A and B can be considered masks. If A is the mask, then it was proven that (A & C) == C. This is trivial if C == A or C == 0. If both A and C are constants, this proof is also easy. For the following explanations, we assume that A is the mask.
"AllOnes" declares that the comparison is true only if (A & B) == A or all bits of A are set in B. Example: (icmp eq (A & 3), 3) -> AMask_AllOnes
"AllZeros" declares that the comparison is true only if (A & B) == 0 or all bits of A are cleared in B. Example: (icmp eq (A & 3), 0) -> Mask_AllZeroes
"Mixed" declares that (A & B) == C and C might or might not contain any number of one bits and zero bits. Example: (icmp eq (A & 3), 1) -> AMask_Mixed
"Not" means that in above descriptions "==" should be replaced by "!=". Example: (icmp ne (A & 3), 3) -> AMask_NotAllOnes
If the mask A contains a single bit, then the following is equivalent: (icmp eq (A & B), A) equals (icmp ne (A & B), 0) (icmp ne (A & B), A) equals (icmp eq (A & B), 0)
Enumerator
AMask_AllOnes
AMask_NotAllOnes
BMask_AllOnes
BMask_NotAllOnes
Mask_AllZeros
Mask_NotAllZeros
AMask_Mixed
AMask_NotMixed
BMask_Mixed
BMask_NotMixed
Definition at line 111 of file InstCombineAndOrXor.cpp.
Function Documentation
areInverseVectorBitmasks()
bool areInverseVectorBitmasks (Constant * C1, Constant * C2) static
If all elements of two constant vectors are 0/-1 and inverses, return true.
Definition at line 3191 of file InstCombineAndOrXor.cpp.
References llvm::cast(), llvm::Constant::getAggregateElement(), llvm::Value::getType(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_Zero(), and llvm::PatternMatch::match().
canFreelyInvert()
bool canFreelyInvert (InstCombiner & IC, Value * Op, Instruction * IgnoredUser) static
Definition at line 4884 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::canFreelyInvertAllUsersOf(), llvm::dyn_cast(), I, and llvm::InstCombiner::isFreeToInvert().
Referenced by llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), and llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp().
canNarrowShiftAmt()
bool canNarrowShiftAmt (Constant * C, unsigned BitWidth) static
Return true if a constant shift amount is always less than the specified bit-width.
If not, the shift could create poison in the narrower type.
Definition at line 1990 of file InstCombineAndOrXor.cpp.
References llvm::BitWidth, llvm::CallingConv::C, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_SpecificInt_ICMP(), and llvm::PatternMatch::match().
canonicalizeAbs()
Instruction * canonicalizeAbs (BinaryOperator & Xor, InstCombiner::BuilderTy & Builder) static
Canonicalize a shifty way to code absolute value to the more common pattern that uses negation and select.
Definition at line 4852 of file InstCombineAndOrXor.cpp.
References A(), llvm::Add, assert(), llvm::cast(), llvm::SelectInst::Create(), llvm::Constant::getNullValue(), llvm::Value::hasNUses(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_Add(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, std::swap(), and llvm::Xor.
Referenced by llvm::InstCombinerImpl::visitXor().
canonicalizeLogicFirst()
Instruction * canonicalizeLogicFirst (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 2212 of file InstCombineAndOrXor.cpp.
References llvm::CallingConv::C, llvm::APInt::countr_zero(), llvm::BinaryOperator::CreateWithCopiedFlags(), I, llvm_unreachable, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, and X.
Referenced by llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitXor().
conjugateICmpMask()
unsigned conjugateICmpMask (unsigned Mask) static
Convert an analysis of a masked ICmp into its equivalent if all boolean operations had the opposite sense.
Since each "NotXXX" flag (recording !=) is adjacent to the corresponding normal flag (recording ==), this just involves swapping those bits over.
Definition at line 176 of file InstCombineAndOrXor.cpp.
References AMask_AllOnes, AMask_Mixed, AMask_NotAllOnes, AMask_NotMixed, BMask_AllOnes, BMask_Mixed, BMask_NotAllOnes, BMask_NotMixed, Mask_AllZeros, and Mask_NotAllZeros.
Referenced by foldLogOpOfMaskedICmps(), and foldLogOpOfMaskedICmpsAsymmetric().
decomposeBitTest()
bool decomposeBitTest (Value * Cond, CmpInst::Predicate & Pred, Value *& X, Value *& Y, Value *& Z) static
Definition at line 190 of file InstCombineAndOrXor.cpp.
References Cond, llvm::decomposeBitTest(), X, and Y.
extractIntPart()
Value * extractIntPart (const IntPart & P, IRBuilderBase & Builder) static
Materialize an extraction of bits from an integer in IR.
Definition at line 1177 of file InstCombineAndOrXor.cpp.
References llvm::Type::getWithNewBitWidth(), and P.
foldAndOrOfICmpEqConstantAndICmp()
Value * foldAndOrOfICmpEqConstantAndICmp (ICmpInst * LHS, ICmpInst * RHS, bool IsAnd, bool IsLogical, IRBuilderBase & Builder) static
Definition at line 3330 of file InstCombineAndOrXor.cpp.
References llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::Type::isIntOrIntVectorTy(), llvm::APInt::isZero(), LHS, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificIntAllowPoison(), llvm::PatternMatch::match(), llvm::Other, and RHS.
foldAndOrOfICmpsWithConstEq()
Value * foldAndOrOfICmpsWithConstEq (ICmpInst * Cmp0, ICmpInst * Cmp1, bool IsAnd, bool IsLogical, InstCombiner::BuilderTy & Builder, const SimplifyQuery & Q, Instruction & I) static
Reduce logic-of-compares with equality to a constant by substituting a common operand with the constant.
Callers are expected to call this with Cmp0/Cmp1 switched to handle logic op commutativity.
Definition at line 1276 of file InstCombineAndOrXor.cpp.
References llvm::CallingConv::C, llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::isa(), llvm::isGuaranteedNotToBeUndefOrPoison(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), nullptr, llvm::ProfcheckDisableMetadataFixes, llvm::simplifyICmpInst(), X, and Y.
foldAndOrOfICmpsWithPow2AndWithZero()
Value * foldAndOrOfICmpsWithPow2AndWithZero (InstCombiner::BuilderTy & Builder, ICmpInst * LHS, ICmpInst * RHS, bool IsAnd, const SimplifyQuery & Q) static
Definition at line 784 of file InstCombineAndOrXor.cpp.
References llvm::SimplifyQuery::AC, llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::isKnownToBeAPowerOfTwo(), LHS, llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_One(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), RHS, and std::swap().
foldAndToXor()
Instruction * foldAndToXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 1928 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::BinaryOperator::CreateNot(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and Op0.
Referenced by llvm::InstCombinerImpl::visitAnd().
foldBitmaskMul()
Value * foldBitmaskMul (Value * Op0, Value * Op1, InstCombiner::BuilderTy & Builder) static
(A & N) * C + (A & M) * C -> (A & (N + M)) & C This also accepts the equivalent select form of (A & N) * C expressions i.e.
!(A & N) ? 0 : N * C)
Definition at line 3930 of file InstCombineAndOrXor.cpp.
References llvm::Value::getType(), matchBitmaskMul(), and Op0.
foldBitwiseLogicWithIntrinsics()
Instruction * foldBitwiseLogicWithIntrinsics (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 2300 of file InstCombineAndOrXor.cpp.
References assert(), llvm::APInt::byteSwap(), llvm::CallInst::Create(), llvm::dyn_cast(), F, llvm::Intrinsic::getOrInsertDeclaration(), I, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), llvm::APInt::reverseBits(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitXor().
foldComplexAndOrPatterns()
Instruction * foldComplexAndOrPatterns (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Try folding relatively complex patterns for both And and Or operations with all And and Or swapped.
Definition at line 2038 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::CallingConv::C, llvm::cast(), llvm::BinaryOperator::Create(), llvm::BinaryOperator::CreateNot(), I, llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_BinOp(), llvm::PatternMatch::m_c_Xor(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, X, llvm::Xor, and Y.
Referenced by llvm::InstCombinerImpl::visitAnd(), and llvm::InstCombinerImpl::visitOr().
foldIntegerPackFromVector()
Instruction * foldIntegerPackFromVector (Instruction & I, InstCombiner::BuilderTy & Builder, const DataLayout & DL) static
Try to fold the join of two scalar integers whose contents are packed elements of the same vector.
Definition at line 3748 of file InstCombineAndOrXor.cpp.
References assert(), llvm::cast(), llvm::CastInst::Create(), DL, llvm::Constant::getNullValue(), llvm::Value::getType(), I, and matchSubIntegerPackFromVector().
Referenced by llvm::InstCombinerImpl::visitOr().
foldIntegerRepackThroughZExt()
Value * foldIntegerRepackThroughZExt (Value * Lhs, Value * Rhs, InstCombiner::BuilderTy & Builder) static
Try to fold the join of two scalar integers whose bits are unpacked and zexted from the same source integer.
Definition at line 3826 of file InstCombineAndOrXor.cpp.
References llvm::Value::getName(), llvm::Value::getType(), matchZExtedSubInteger(), and llvm::Value::takeName().
foldIsPowerOf2()
Value * foldIsPowerOf2 (ICmpInst * Cmp0, ICmpInst * Cmp1, bool JoinedByAnd, InstCombiner::BuilderTy & Builder, InstCombinerImpl & IC) static
Reduce a pair of compares that check if a value has exactly 1 bit set.
Also used for logical and/or, must be poison safe if range attributes are dropped.
Definition at line 973 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::addToWorklist(), llvm::cast(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), std::swap(), and X.
foldIsPowerOf2OrZero()
Value * foldIsPowerOf2OrZero (ICmpInst * Cmp0, ICmpInst * Cmp1, bool IsAnd, InstCombiner::BuilderTy & Builder, InstCombinerImpl & IC) static
Fold (icmp eq ctpop(X) 1) | (icmp eq X 0) into (icmp ult ctpop(X) 2) and fold (icmp ne ctpop(X) 1) & (icmp ne X 0) into (icmp ugt ctpop(X) 1).
Also used for logical and/or, must be poison safe if range attributes are dropped.
Definition at line 943 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::addToWorklist(), llvm::cast(), llvm::User::getOperand(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), and X.
foldLogicCastConstant()
Instruction * foldLogicCastConstant (BinaryOperator & Logic, CastInst * Cast, InstCombinerImpl & IC) static
Fold {and,or,xor} (cast X), C.
Definition at line 1776 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::IRBuilderBase::CreateBinOp(), DL, llvm::dyn_cast(), llvm::InstCombiner::getDataLayout(), llvm::getLosslessSignedTrunc(), llvm::getLosslessUnsignedTrunc(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CastInst::getSrcTy(), llvm::Value::getType(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SExtLike(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), and X.
foldLogOpOfMaskedICmps()
Value * foldLogOpOfMaskedICmps (Value * LHS, Value * RHS, bool IsAnd, bool IsLogical, InstCombiner::BuilderTy & Builder, const SimplifyQuery & Q) static
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y).
Definition at line 534 of file InstCombineAndOrXor.cpp.
References A(), AMask_AllOnes, AMask_NotAllOnes, assert(), B(), BMask_AllOnes, BMask_Mixed, BMask_NotAllOnes, BMask_NotMixed, llvm::CallingConv::C, conjugateICmpMask(), D(), llvm::dyn_cast(), E(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::CmpInst::getInversePredicate(), getMaskedTypeForICmpPair(), llvm::Constant::getNullValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), llvm::isGuaranteedNotToBeUndefOrPoison(), llvm::isKnownToBeAPowerOfTwo(), llvm::APInt::isSubsetOf(), LHS, llvm::PatternMatch::m_APInt(), Mask_AllZeros, Mask_NotAllZeros, llvm::Masked, llvm::PatternMatch::match(), nullptr, and RHS.
foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed()
Value * foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed (Value * LHS, Value * RHS, bool IsAnd, Value * A, Value * B, Value * D, Value * E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, InstCombiner::BuilderTy & Builder) static
Try to fold (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side is of type Mask_NotAllZeros and the right hand side is of type BMask_Mixed.
For example, (icmp (A & 12) != 0) & (icmp (A & 15) == 8) -> (icmp (A & 15) == 8). Also used for logical and/or, must be poison safe.
Definition at line 353 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::APFloat::bitcastToAPInt(), llvm::APInt::clearSignBit(), D(), llvm::dyn_cast(), E(), llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UNO, llvm::APFloat::getInf(), llvm::ConstantFP::getZero(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::APInt::intersects(), llvm::APInt::isZero(), LHS, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and RHS.
Referenced by foldLogOpOfMaskedICmpsAsymmetric().
foldLogOpOfMaskedICmpsAsymmetric()
Value * foldLogOpOfMaskedICmpsAsymmetric (Value * LHS, Value * RHS, bool IsAnd, Value * A, Value * B, Value * C, Value * D, Value * E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, unsigned LHSMask, unsigned RHSMask, InstCombiner::BuilderTy & Builder) static
Try to fold (icmp(A & B) ==/!= 0) &/| (icmp(A & D) ==/!= E) into a single (icmp(A & X) ==/!= Y), where the left-hand side and the right hand side aren't of the common mask pattern type.
Also used for logical and/or, must be poison safe.
Definition at line 503 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), BMask_Mixed, llvm::CallingConv::C, conjugateICmpMask(), D(), E(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), llvm::ICmpInst::isEquality(), LHS, Mask_NotAllZeros, and RHS.
Referenced by foldLogOpOfMaskedICmps().
foldNegativePower2AndShiftedMask()
Value * foldNegativePower2AndShiftedMask (Value * A, Value * B, Value * D, Value * E, ICmpInst::Predicate PredL, ICmpInst::Predicate PredR, InstCombiner::BuilderTy & Builder) static
Try to fold (icmp(A & B) == 0) & (icmp(A & D) != E) into (icmp A u< D) iff B is a contiguous set of ones starting from the most significant bit (negative power of 2), D and E are equal, and D is a contiguous set of ones starting at the most significant zero bit in B.
Parameter B supports masking using undef/poison in either scalar or vector values.
Definition at line 1015 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::APInt::countLeadingOnes(), llvm::APInt::countLeadingZeros(), D(), llvm::dyn_cast(), E(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_NegatedPower2(), llvm::PatternMatch::m_ShiftedMask(), and llvm::PatternMatch::match().
Referenced by foldPowerOf2AndShiftedMask().
foldNotXor()
Instruction * foldNotXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 4818 of file InstCombineAndOrXor.cpp.
References A(), B(), llvm::CallingConv::C, D(), I, llvm::PatternMatch::m_And(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::match(), X, and Y.
foldOrOfInversions()
Value * foldOrOfInversions (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 3617 of file InstCombineAndOrXor.cpp.
References assert(), I, llvm::isKnownInversion(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by llvm::InstCombinerImpl::visitOr().
FoldOrOfSelectSmaxToAbs()
Value * FoldOrOfSelectSmaxToAbs (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Fold select(X >s 0, 0, -X) | smax(X, 0) --> abs(X) select(X <s 0, -X, 0) | smax(X, 0) --> abs(X).
Definition at line 4007 of file InstCombineAndOrXor.cpp.
References I, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::PatternMatch::m_c_Or(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_Value(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstCombinerImpl::visitOr().
foldOrToXor()
Instruction * foldOrToXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
Definition at line 1954 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::BinaryOperator::CreateNot(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::match(), and Op0.
Referenced by llvm::InstCombinerImpl::visitOr().
foldOrUnsignedUMulOverflowICmp()
Value * foldOrUnsignedUMulOverflowICmp (BinaryOperator & I, InstCombiner::BuilderTy & Builder, const DataLayout & DL) static
Fold Res, Overflow = (umul.with.overflow x c1); (or Overflow (ugt Res c2)) --> (ugt x (c2/c1)).
This code checks whether a multiplication of two unsigned numbers (one is a constant) is mathematically greater than a second constant.
Definition at line 3986 of file InstCombineAndOrXor.cpp.
References DL, I, llvm::CmpInst::ICMP_UGT, llvm::APInt::isZero(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_ExtractValue(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SpecificCmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::APInt::udiv(), and X.
Referenced by llvm::InstCombinerImpl::visitOr().
foldPowerOf2AndShiftedMask()
Value * foldPowerOf2AndShiftedMask (ICmpInst * Cmp0, ICmpInst * Cmp1, bool JoinedByAnd, InstCombiner::BuilderTy & Builder) static
Try to fold ((icmp X u< P) & (icmp(X & M) != M)) or ((icmp X s> -1) & (icmp(X & M) != M)) into (icmp X u< M).
Where P is a power of 2, M < P, and M is a contiguous shifted mask starting at the right most significant zero bit in P. SGT is supported as when P is the largest representable power of 2, an earlier optimization converts the expression into (icmp X s> -1). Parameter P supports masking using undef/poison in either scalar or vector values.
Definition at line 1081 of file InstCombineAndOrXor.cpp.
References A(), B(), BMask_NotAllOnes, BMask_NotMixed, llvm::CallingConv::C, D(), E(), foldNegativePower2AndShiftedMask(), getMaskedTypeForICmpPair(), and Mask_AllZeros.
foldSignedTruncationCheck()
Value * foldSignedTruncationCheck (ICmpInst * ICmp0, ICmpInst * ICmp1, Instruction & CxtI, InstCombiner::BuilderTy & Builder) static
General pattern: X & Y.
Where Y is checking that all the high bits (covered by a mask 4294967168) are uniform, i.e. arg & 4294967168 can be either 4294967168 or 0 Pattern can be one of: t = add i32 arg, 128 r = icmp ult i32 t, 256 Or t0 = shl i32 arg, 24 t1 = ashr i32 t0, 24 r = icmp eq i32 t1, arg Or t0 = trunc i32 arg to i8 t1 = sext i8 t0 to i32 r = icmp eq i32 t1, arg This pattern is a signed truncation check.
And X is checking that some bit in that same mask is zero. I.e. can be one of: r = icmp sgt i32 arg, -1 Or t = and i32 arg, 2147483648 r = icmp eq i32 t, 0
Since we are checking that all the bits in that mask are the same, and a particular bit is zero, what we are really checking is that all the masked bits are zero. So this should be transformed to: r = icmp ult i32 arg, 128
Definition at line 847 of file InstCombineAndOrXor.cpp.
References assert(), llvm::decomposeBitTestICmp(), llvm::Value::getName(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::APInt::intersects(), llvm::APInt::isPowerOf2(), llvm::APInt::isSubsetOf(), llvm::APInt::isZero(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificICmp(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::APInt::shl(), llvm::APIntOps::umin(), X, and llvm::APInt::zext().
foldUnsignedUnderflowCheck()
Value * foldUnsignedUnderflowCheck (ICmpInst * ZeroICmp, ICmpInst * UnsignedICmp, bool IsAnd, const SimplifyQuery & Q, InstCombiner::BuilderTy & Builder) static
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
Definition at line 1113 of file InstCombineAndOrXor.cpp.
References A(), B(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::isKnownNonZero(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::Other, and std::swap().
foldXorToXor()
Instruction * foldXorToXor (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
A ^ B can be specified using other logic ops in a variety of patterns.
We can fold these early and efficiently by morphing an existing instruction.
Definition at line 4586 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::BinaryOperator::CreateNot(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Deferred(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::match(), and Op0.
Referenced by llvm::InstCombinerImpl::visitXor().
freelyInvert()
Value * freelyInvert (InstCombinerImpl & IC, Value * Op, Instruction * IgnoredUser) static
Definition at line 4891 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::Builder, llvm::cast(), llvm::IRBuilderBase::CreateNot(), llvm::InstCombinerImpl::freelyInvertAllUsersOf(), I, and llvm::IRBuilderBase::SetInsertPoint().
Referenced by llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), and llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp().
getFCmpValue()
Value * getFCmpValue (unsigned Code, Value * LHS, Value * RHS, InstCombiner::BuilderTy & Builder, FMFSource FMF) static
This is the complement of getFCmpCode, which turns an opcode and two operands into either a FCmp instruction, or a true/false constant.
Definition at line 49 of file InstCombineAndOrXor.cpp.
References llvm::getPredForFCmpCode(), LHS, and RHS.
getMaskedICmpType()
unsigned getMaskedICmpType (Value * A, Value * B, Value * C, ICmpInst::Predicate Pred) static
Return the set of patterns (from MaskedICmpType) that (icmp SCC (A & B), C) satisfies.
Definition at line 126 of file InstCombineAndOrXor.cpp.
References A(), AMask_AllOnes, AMask_Mixed, AMask_NotAllOnes, AMask_NotMixed, B(), BMask_AllOnes, BMask_Mixed, BMask_NotAllOnes, BMask_NotMixed, llvm::CallingConv::C, llvm::CmpInst::ICMP_EQ, llvm::APInt::isPowerOf2(), llvm::APInt::isSubsetOf(), llvm::PatternMatch::m_APInt(), Mask_AllZeros, Mask_NotAllZeros, and llvm::PatternMatch::match().
Referenced by getMaskedTypeForICmpPair().
getMaskedTypeForICmpPair()
std::optional< std::pair< unsigned, unsigned > > getMaskedTypeForICmpPair (Value *& A, Value *& B, Value *& C, Value *& D, Value *& E, Value * LHS, Value * RHS, ICmpInst::Predicate & PredL, ICmpInst::Predicate & PredR) static
Handle (icmp(A & B) ==/!= C) &/| (icmp(A & D) ==/!= E).
Return the pattern classes (from MaskedICmpType) for the left hand side and the right hand side as a pair. LHS and RHS are the left hand side and the right hand side ICmps and PredL and PredR are their predicates, respectively.
Definition at line 210 of file InstCombineAndOrXor.cpp.
References A(), B(), llvm::CallingConv::C, D(), llvm::decomposeBitTest(), llvm::dyn_cast(), E(), llvm::Constant::getAllOnesValue(), getMaskedICmpType(), llvm::Value::getType(), llvm::ICmpInst::isEquality(), LHS, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), R2, and RHS.
Referenced by foldLogOpOfMaskedICmps(), and foldPowerOf2AndShiftedMask().
getNewICmpValue()
Value * getNewICmpValue (unsigned Code, bool Sign, Value * LHS, Value * RHS, InstCombiner::BuilderTy & Builder) static
This is the complement of getICmpCode, which turns an opcode and two operands into either a constant true or false, or a brand new ICmp instruction.
The sign is passed in to determine which kind of predicate to use in the new icmp instruction.
Definition at line 39 of file InstCombineAndOrXor.cpp.
References llvm::getPredForICmpCode(), LHS, and RHS.
matchBitmaskMul()
std::optional< DecomposedBitMaskMul > matchBitmaskMul (Value * V) static
Definition at line 3872 of file InstCombineAndOrXor.cpp.
References assert(), llvm::cast(), Cond, llvm::decomposeBitTest(), llvm::dyn_cast(), llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), llvm::APInt::isZero(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and std::swap().
Referenced by foldBitmaskMul().
matchDeMorgansLaws()
Instruction * matchDeMorgansLaws (BinaryOperator & I, InstCombiner & IC) static
Match variations of De Morgan's Laws: (~A & ~B) == (~(A | B)) (~A | ~B) == (~(A & B)).
Definition at line 1723 of file InstCombineAndOrXor.cpp.
References A(), assert(), B(), llvm::InstCombiner::Builder, llvm::CallingConv::C, llvm::BinaryOperator::Create(), llvm::IRBuilderBase::CreateBinOp(), llvm::BinaryOperator::CreateNot(), llvm::IRBuilderBase::CreateNot(), I, llvm::InstCombiner::isFreeToInvert(), llvm::PatternMatch::m_c_BinOp(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and Op0.
Referenced by llvm::InstCombinerImpl::visitAnd(), and llvm::InstCombinerImpl::visitOr().
matchFunnelShift()
Instruction * matchFunnelShift (Instruction & Or, InstCombinerImpl & IC) static
Match UB-safe variants of the funnel shift intrinsic.
Definition at line 3116 of file InstCombineAndOrXor.cpp.
References llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::CallInst::Create(), F, and llvm::Intrinsic::getOrInsertDeclaration().
Referenced by foldGuardedFunnelShift(), and llvm::InstCombinerImpl::visitOr().
matchIntPart()
std::optional< IntPart > matchIntPart (Value * V) static
Match an extraction of bits from an integer.
Definition at line 1159 of file InstCombineAndOrXor.cpp.
References llvm::APInt::getZExtValue(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_LShr(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::APInt::ule(), X, and Y.
matchIsFiniteTest()
Value * matchIsFiniteTest (InstCombiner::BuilderTy & Builder, FCmpInst * LHS, FCmpInst * RHS) static
and (fcmp ord x, 0), (fcmp u* x, inf) -> fcmp o* x, inf
Clang emits this pattern for doing an isfinite check in __builtin_isnormal.
Definition at line 1434 of file InstCombineAndOrXor.cpp.
References llvm::CmpInst::getOrderedPredicate(), llvm::FMFSource::intersect(), LHS, matchIsNotNaN(), matchUnorderedInfCompare(), and RHS.
matchIsFPClassLikeFCmp()
bool matchIsFPClassLikeFCmp (Value * Op, Value *& ClassVal, uint64_t & ClassMask) static
Match an fcmp against a special value that performs a test possible by llvm.is.fpclass.
Definition at line 1580 of file InstCombineAndOrXor.cpp.
References llvm::dyn_cast(), and llvm::fcmpToClassTest().
matchIsNotNaN()
bool matchIsNotNaN (FCmpInst::Predicate P, Value * LHS, Value * RHS) static
Matches canonical form of isnan, fcmp ord x, 0.
Definition at line 1421 of file InstCombineAndOrXor.cpp.
References llvm::CmpInst::FCMP_ORD, LHS, llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::match(), P, and RHS.
Referenced by matchIsFiniteTest().
matchOrConcat()
Value * matchOrConcat (Instruction & Or, InstCombiner::BuilderTy & Builder) static
Attempt to combine or(zext(x),shl(zext(y),bw/2) concat packing patterns.
Definition at line 3128 of file InstCombineAndOrXor.cpp.
References assert(), llvm::CallingConv::C, llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Hi, llvm::isa(), llvm::Lo, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_BitReverse(), llvm::PatternMatch::m_BSwap(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_SExtOrSelf(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), Op0, std::swap(), and X.
Referenced by llvm::InstCombinerImpl::visitOr().
matchSubIntegerPackFromVector()
bool matchSubIntegerPackFromVector (Value * V, Value *& Vec, int64_t & VecOffset, SmallBitVector & Mask, const DataLayout & DL) static
Match V as "shufflevector -> bitcast" or "extractelement -> zext -> shl" patterns, which extract vector elements and pack them in the same relative positions.
Vec is the underlying vector being extracted from. Mask is a bitmask identifying which packed elements are obtained from the vector. VecOffset is the vector element corresponding to index 0 of the mask.
Definition at line 3645 of file InstCombineAndOrXor.cpp.
References DL, llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::Type::getIntegerBitWidth(), llvm::Value::getType(), llvm::isa(), llvm::PatternMatch::m_BitCast(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ExtractElt(), llvm::PatternMatch::m_InsertElt(), llvm::PatternMatch::m_Instruction(), llvm::PatternMatch::m_ShlOrSelf(), llvm::PatternMatch::m_Shuffle(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExtOrSelf(), llvm::PatternMatch::match(), and llvm::PoisonMaskElem.
Referenced by foldIntegerPackFromVector().
matchUnorderedInfCompare()
bool matchUnorderedInfCompare (FCmpInst::Predicate P, Value * LHS, Value * RHS) static
Matches fcmp u__ x, +/-inf.
Definition at line 1426 of file InstCombineAndOrXor.cpp.
References llvm::CmpInst::isUnordered(), LHS, llvm::PatternMatch::m_Inf(), llvm::PatternMatch::match(), P, and RHS.
Referenced by matchIsFiniteTest().
matchZExtedSubInteger()
bool matchZExtedSubInteger (Value * V, Value *& Int, APInt & Mask, uint64_t & Offset, bool & IsShlNUW, bool & IsShlNSW) static
Match V as "lshr -> mask -> zext -> shl".
Int is the underlying integer being extracted from. Mask is a bitmask identifying which bits of the integer are being extracted. Offset identifies which bit of the result V corresponds to the least significant bit of Int
Definition at line 3785 of file InstCombineAndOrXor.cpp.
References llvm::cast(), llvm::APInt::getBitsSetFrom(), Int, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LShr(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::Offset, and llvm::APInt::shl().
Referenced by foldIntegerRepackThroughZExt().
reassociateFCmps()
Instruction * reassociateFCmps (BinaryOperator & BO, InstCombiner::BuilderTy & Builder) static
This a limited reassociation for a special case (see above) where we are checking if two values are either both NAN (unordered) or not-NAN (ordered).
This could be handled more generally in '-reassociation', but it seems like an unlikely pattern for a large number of logic ops and fcmps.
Definition at line 1682 of file InstCombineAndOrXor.cpp.
References assert(), llvm::BinaryOperator::Create(), llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UNO, llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::FMFSource::intersect(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_SpecificFCmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, std::swap(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitAnd(), and llvm::InstCombinerImpl::visitOr().
reassociateForUses()
Instruction * reassociateForUses (BinaryOperator & BO, InstCombinerImpl::BuilderTy & Builder) static
Try to reassociate a pair of binops so that values with one use only are part of the same instruction.
This may enable folds that are limited with multi-use restrictions and makes it more likely to match other patterns that are looking for a common operand.
Definition at line 2179 of file InstCombineAndOrXor.cpp.
References llvm::BinaryOperator::Create(), llvm::BinaryOperator::getOpcode(), llvm::isa(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_BinOp(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), X, and Y.
Referenced by llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitXor().
simplifyAndOrWithOpReplaced()
Value * simplifyAndOrWithOpReplaced (Value * V, Value * Op, Value * RepOp, bool SimplifyOnly, InstCombinerImpl & IC, unsigned Depth = 0) static
Definition at line 2355 of file InstCombineAndOrXor.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilderBase::CreateBinOp(), llvm::Depth, llvm::dyn_cast(), llvm::InstCombiner::getSimplifyQuery(), llvm::SimplifyQuery::getWithInstruction(), I, simplifyAndOrWithOpReplaced(), and llvm::simplifyBinOp().
Referenced by simplifyAndOrWithOpReplaced(), llvm::InstCombinerImpl::visitAnd(), and llvm::InstCombinerImpl::visitOr().
stripSignOnlyFPOps()
Value * stripSignOnlyFPOps (Value * Val) static
Ignore all operations which only change the sign of a value, returning the underlying magnitude value.
Definition at line 1413 of file InstCombineAndOrXor.cpp.
References llvm::PatternMatch::m_CopySign(), llvm::PatternMatch::m_FAbs(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
visitMaskedMerge()
Instruction * visitMaskedMerge (BinaryOperator & I, InstCombiner::BuilderTy & Builder) static
If we have a masked merge, in the canonical form of: (assuming that A only has one use.) | A | |B| ((x ^ y) & M) ^ y | D |.
If M is inverted: | D | ((x ^ y) & ~M) ^ y We can canonicalize by swapping the final xor operand to eliminate the 'not' of the mask. ((x ^ y) & M) ^ x
If M is a constant, and D has one use, we transform to 'and' / 'or' ops because that shortens the dependency chain and improves analysis: (x & M) | (y & ~M)
Definition at line 4786 of file InstCombineAndOrXor.cpp.
References B(), llvm::CallingConv::C, D(), llvm::Constant::getAllOnesValue(), I, LHS, llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Deferred(), llvm::MIPatternMatch::m_Not(), llvm::MIPatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::Constant::replaceUndefsWith(), RHS, and X.
Referenced by llvm::InstCombinerImpl::visitXor().