LLVM: lib/Analysis/InstructionSimplify.cpp File Reference
InstructionSimplify.cpp File Reference
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/CmpInstAnalysis.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/FloatingPointPredicateUtils.h"
#include "llvm/Analysis/InstSimplifyFolder.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/LoopAnalysisManager.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/OverflowInstAnalysis.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/ConstantFPRange.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/KnownFPClass.h"
#include <algorithm>
#include <optional>
#include "llvm/IR/Instruction.def"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "instsimplify"
#define HANDLE_CAST_INST(num, opc, clas)
Enumerations
enum { RecursionLimit = 3 }
enum class MonotonicType { GreaterEq , LowerEq }
enum class MinMaxOptResult { CannotOptimize = 0 , UseNewConstVal = 1 , UseOtherVal = 2 , UseEither = 3 }
Functions
STATISTIC (NumExpand, "Number of expansions")
STATISTIC (NumReassoc, "Number of reassociations")
static Value * simplifyAndInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an And, see if we can fold the result.
static Value * simplifyUnOp (unsigned Opcode, Value *Op, const SimplifyQuery &Q, unsigned MaxRecurse)
Given the operand for a UnaryOperator, see if we can fold the result.
static Value * simplifyFPUnOp (unsigned Opcode, Value *Op, const FastMathFlags &FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given the operand for a UnaryOperator, see if we can fold the result.
static Value * simplifyBinOp (unsigned Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a BinaryOperator, see if we can fold the result.
static Value * simplifyBinOp (unsigned Opcode, Value *LHS, Value *RHS, const FastMathFlags &FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a BinaryOperator, see if we can fold the result.
static Value * simplifyCmpInst (CmpPredicate Predicate, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a CmpInst, see if we can fold the result.
static Value * simplifyICmpInst (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an ICmpInst, see if we can fold the result.
static Value * simplifyOrInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Or, see if we can fold the result.
static Value * simplifyXorInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a Xor, see if we can fold the result.
static Value * simplifyCastInst (unsigned, Value *, Type *, const SimplifyQuery &, unsigned)
static Value * simplifyGEPInst (Type *SrcTy, Value *Ptr, ArrayRef< Value * > Indices, GEPNoWrapFlags NW, const SimplifyQuery &Q, unsigned)
Given operands for an GetElementPtrInst, see if we can fold the result.
static Value * simplifySelectInst (Value *Cond, Value *TrueVal, Value *FalseVal, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a SelectInst, see if we can fold the result.
static Value * simplifyInstructionWithOperands (Instruction *I, ArrayRef< Value * > NewOps, const SimplifyQuery &SQ, unsigned MaxRecurse)
See if we can compute a simplified version of this instruction.
static Constant * getFalse (Type *Ty)
For a boolean type or a vector of boolean type, return false or a vector with every element false.
static Constant * getTrue (Type *Ty)
For a boolean type or a vector of boolean type, return true or a vector with every element true.
static bool isSameCompare (Value *V, CmpPredicate Pred, Value *LHS, Value *RHS)
isSameCompare - Is V equivalent to the comparison "LHS Pred RHS"?
static Value * simplifyCmpSelCase (CmpPredicate Pred, Value *LHS, Value *RHS, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse, Constant *TrueOrFalse)
Simplify comparison with true or false branch of select: sel = select i1 cond, i32 tv, i32 fv cmp = icmp sle i32 sel, rhs Compose new comparison by substituting sel with either tv or fv and see if it simplifies.
static Value * simplifyCmpSelTrueCase (CmpPredicate Pred, Value *LHS, Value *RHS, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse)
Simplify comparison with true branch of select.
static Value * simplifyCmpSelFalseCase (CmpPredicate Pred, Value *LHS, Value *RHS, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse)
Simplify comparison with false branch of select.
static Value * handleOtherCmpSelSimplifications (Value *TCmp, Value *FCmp, Value *Cond, const SimplifyQuery &Q, unsigned MaxRecurse)
We know comparison with both branches of select can be simplified, but they are not equal.
static bool valueDominatesPHI (Value *V, PHINode *P, const DominatorTree *DT)
Does the given value dominate the specified phi node?
static Value * expandBinOp (Instruction::BinaryOps Opcode, Value *V, Value *OtherOp, Instruction::BinaryOps OpcodeToExpand, const SimplifyQuery &Q, unsigned MaxRecurse)
Try to simplify a binary operator of form "V op OtherOp" where V is "(B0 opex B1)" by distributing 'op' across 'opex' as "(B0 op OtherOp) opex (B1 op OtherOp)".
static Value * expandCommutativeBinOp (Instruction::BinaryOps Opcode, Value *L, Value *R, Instruction::BinaryOps OpcodeToExpand, const SimplifyQuery &Q, unsigned MaxRecurse)
Try to simplify binops of form "A op (B op' C)" or the commuted variant by distributing op over op'.
static Value * simplifyAssociativeBinOp (Instruction::BinaryOps Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Generic simplifications for associative binary operations.
static Value * threadBinOpOverSelect (Instruction::BinaryOps Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a binary operation with a select instruction as an operand, try to simplify the binop by seeing whether evaluating it on both branches of the select results in the same value.
static Value * threadCmpOverSelect (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a comparison with a select instruction, try to simplify the comparison by seeing whether both branches of the select result in the same value.
static Value * threadBinOpOverPHI (Instruction::BinaryOps Opcode, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a binary operation with an operand that is a PHI instruction, try to simplify the binop by seeing whether evaluating it on the incoming phi values yields the same result for every value.
static Value * threadCmpOverPHI (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
In the case of a comparison with a PHI instruction, try to simplify the comparison by seeing whether comparing with all of the incoming phi values yields the same result every time.
static Constant * foldOrCommuteConstant (Instruction::BinaryOps Opcode, Value *&Op0, Value *&Op1, const SimplifyQuery &Q)
static Value * simplifyAddInst (Value *Op0, Value *Op1, bool IsNSW, bool IsNUW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Add, see if we can fold the result.
static APInt stripAndComputeConstantOffsets (const DataLayout &DL, Value *&V)
Compute the base pointer and cumulative constant offsets for V.
static Constant * computePointerDifference (const DataLayout &DL, Value *LHS, Value *RHS)
Compute the constant difference between two pointer values.
static Value * simplifyByDomEq (unsigned Opcode, Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Test if there is a dominating equivalence condition for the two operands.
static Value * simplifySubInst (Value *Op0, Value *Op1, bool IsNSW, bool IsNUW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a Sub, see if we can fold the result.
static Value * simplifyMulInst (Value *Op0, Value *Op1, bool IsNSW, bool IsNUW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a Mul, see if we can fold the result.
static bool isICmpTrue (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
Given a predicate and two operands, return true if the comparison is true.
static bool isDivZero (Value *X, Value *Y, const SimplifyQuery &Q, unsigned MaxRecurse, bool IsSigned)
Return true if we can simplify X / Y to 0.
static Value * simplifyDivRem (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Check for common or similar folds of integer division or integer remainder.
static Value * simplifyDiv (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, bool IsExact, const SimplifyQuery &Q, unsigned MaxRecurse)
These are simplifications common to SDiv and UDiv.
static Value * simplifyRem (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
These are simplifications common to SRem and URem.
static Value * simplifySDivInst (Value *Op0, Value *Op1, bool IsExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an SDiv, see if we can fold the result.
static Value * simplifyUDivInst (Value *Op0, Value *Op1, bool IsExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a UDiv, see if we can fold the result.
static Value * simplifySRemInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an SRem, see if we can fold the result.
static Value * simplifyURemInst (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for a URem, see if we can fold the result.
static bool isPoisonShift (Value *Amount, const SimplifyQuery &Q)
Returns true if a shift by Amount always yields poison.
static Value * simplifyShift (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, bool IsNSW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Shl, LShr or AShr, see if we can fold the result.
static Value * simplifyRightShift (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, bool IsExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an LShr or AShr, see if we can fold the result.
static Value * simplifyShlInst (Value *Op0, Value *Op1, bool IsNSW, bool IsNUW, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an Shl, see if we can fold the result.
static Value * simplifyLShrInst (Value *Op0, Value *Op1, bool IsExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an LShr, see if we can fold the result.
static Value * simplifyAShrInst (Value *Op0, Value *Op1, bool IsExact, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an AShr, see if we can fold the result.
static Value * simplifyUnsignedRangeCheck (ICmpInst *ZeroICmp, ICmpInst *UnsignedICmp, bool IsAnd, const SimplifyQuery &Q)
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
static Value * simplifyAndOrOfICmpsWithConstants (ICmpInst *Cmp0, ICmpInst *Cmp1, bool IsAnd)
Test if a pair of compares with a shared operand and 2 constants has an empty set intersection, full set union, or if one compare is a superset of the other.
static Value * simplifyAndOfICmpsWithAdd (ICmpInst *Op0, ICmpInst *Op1, const InstrInfoQuery &IIQ)
static Value * simplifyAndOrOfICmpsWithCtpop (ICmpInst *Cmp0, ICmpInst *Cmp1, bool IsAnd)
Try to simplify and/or of icmp with ctpop intrinsic.
static Value * simplifyAndOfICmps (ICmpInst *Op0, ICmpInst *Op1, const SimplifyQuery &Q)
static Value * simplifyOrOfICmpsWithAdd (ICmpInst *Op0, ICmpInst *Op1, const InstrInfoQuery &IIQ)
static Value * simplifyOrOfICmps (ICmpInst *Op0, ICmpInst *Op1, const SimplifyQuery &Q)
static Value * simplifyAndOrOfFCmpsWithConstants (FCmpInst *Cmp0, FCmpInst *Cmp1, bool IsAnd)
Test if a pair of compares with a shared operand and 2 constants has an empty set intersection, full set union, or if one compare is a superset of the other.
static Value * simplifyAndOrOfFCmps (const SimplifyQuery &Q, FCmpInst *LHS, FCmpInst *RHS, bool IsAnd)
static Value * simplifyAndOrOfCmps (const SimplifyQuery &Q, Value *Op0, Value *Op1, bool IsAnd)
static Value * simplifyWithOpReplaced (Value *V, Value *Op, Value *RepOp, const SimplifyQuery &Q, bool AllowRefinement, SmallVectorImpl< Instruction * > *DropFlags, unsigned MaxRecurse)
static Value * simplifyAndOrWithICmpEq (unsigned Opcode, Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
static Value * simplifyLogicOfAddSub (Value *Op0, Value *Op1, Instruction::BinaryOps Opcode)
Given a bitwise logic op, check if the operands are add/sub with a common source value and inverted constant (identity: C - X -> ~(X + ~C)).
static Value * simplifyAndCommutative (Value *Op0, Value *Op1, const SimplifyQuery &Q, unsigned MaxRecurse)
static Value * simplifyOrLogic (Value *X, Value *Y)
static Type * getCompareTy (Value *Op)
static Value * extractEquivalentCondition (Value *V, CmpPredicate Pred, Value *LHS, Value *RHS)
Rummage around inside V looking for something equivalent to the comparison "LHS Pred RHS".
static bool isAllocDisjoint (const Value *V)
Return true if the underlying object (storage) must be disjoint from storage returned by any noalias return call.
static bool haveNonOverlappingStorage (const Value *V1, const Value *V2)
Return true if V1 and V2 are each the base of some distict storage region [V, object_size(V)] which do not overlap.
static Constant * computePointerICmp (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q)
static Value * simplifyICmpOfBools (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q)
Fold an icmp when its operands have i1 scalar type.
static Value * simplifyICmpWithZero (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q)
Try hard to fold icmp with zero RHS because this is a common case.
static Value * simplifyICmpWithConstant (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q)
static void getUnsignedMonotonicValues (SmallPtrSetImpl< Value * > &Res, Value *V, MonotonicType Type, const SimplifyQuery &Q, unsigned Depth=0)
Get values V_i such that V uge V_i (GreaterEq) or V ule V_i (LowerEq).
static Value * simplifyICmpUsingMonotonicValues (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q)
static Value * simplifyICmpWithBinOpOnLHS (CmpPredicate Pred, BinaryOperator *LBO, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
static bool trySimplifyICmpWithAdds (CmpPredicate Pred, Value *LHS, Value *RHS, const InstrInfoQuery &IIQ)
static Value * simplifyICmpWithBinOp (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
TODO: A large part of this logic is duplicated in InstCombine's foldICmpBinOp().
static Value * simplifyICmpWithMinMax (CmpPredicate Pred, Value *LHS, Value *RHS, const SimplifyQuery &Q, unsigned MaxRecurse)
simplify integer comparisons where at least one operand of the compare matches an integer min/max idiom.
static Value * simplifyICmpWithDominatingAssume (CmpPredicate Predicate, Value *LHS, Value *RHS, const SimplifyQuery &Q)
static Value * simplifyICmpWithIntrinsicOnLHS (CmpPredicate Pred, Value *LHS, Value *RHS)
static std::optional< ConstantRange > getRange (Value *V, const InstrInfoQuery &IIQ)
Helper method to get range from metadata or attribute.
static Value * simplifyFCmpInst (CmpPredicate Pred, Value *LHS, Value *RHS, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given operands for an FCmpInst, see if we can fold the result.
static Value * simplifyWithOpsReplaced (Value *V, ArrayRef< std::pair< Value *, Value * > > Ops, const SimplifyQuery &Q, bool AllowRefinement, SmallVectorImpl< Instruction * > *DropFlags, unsigned MaxRecurse)
static Value * simplifySelectBitTest (Value *TrueVal, Value *FalseVal, Value *X, const APInt *Y, bool TrueWhenUnset)
Try to simplify a select instruction when its condition operand is an integer comparison where one operand of the compare is a constant.
static Value * simplifyCmpSelOfMaxMin (Value *CmpLHS, Value *CmpRHS, CmpPredicate Pred, Value *TVal, Value *FVal)
static Value * simplifySelectWithBitTest (Value *CondVal, Value *TrueVal, Value *FalseVal)
An alternative way to test if a bit is set or not.
static Value * simplifySelectWithEquivalence (ArrayRef< std::pair< Value *, Value * > > Replacements, Value *TrueVal, Value *FalseVal, const SimplifyQuery &Q, unsigned MaxRecurse)
Try to simplify a select instruction when its condition operand is an integer equality or floating-point equivalence comparison.
static Value * simplifySelectWithICmpCond (Value *CondVal, Value *TrueVal, Value *FalseVal, const SimplifyQuery &Q, unsigned MaxRecurse)
Try to simplify a select instruction when its condition operand is an integer comparison.
static Value * simplifySelectWithFCmp (Value *Cond, Value *T, Value *F, const SimplifyQuery &Q, unsigned MaxRecurse)
Try to simplify a select instruction when its condition operand is a floating-point comparison.
bool isSelectWithIdenticalPHI (PHINode &PN, PHINode &IdenticalPN)
Look for the following pattern and simplify to_fold to identicalPhi.
static Value * simplifyInsertValueInst (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const SimplifyQuery &Q, unsigned)
Given operands for an InsertValueInst, see if we can fold the result.
static Value * simplifyExtractValueInst (Value *Agg, ArrayRef< unsigned > Idxs, const SimplifyQuery &, unsigned)
Given operands for an ExtractValueInst, see if we can fold the result.
static Value * simplifyExtractElementInst (Value *Vec, Value *Idx, const SimplifyQuery &Q, unsigned)
Given operands for an ExtractElementInst, see if we can fold the result.
static Value * simplifyPHINode (PHINode *PN, ArrayRef< Value * > IncomingValues, const SimplifyQuery &Q)
See if we can fold the given phi. If not, returns null.
static Value * foldIdentityShuffles (int DestElt, Value *Op0, Value *Op1, int MaskVal, Value *RootVec, unsigned MaxRecurse)
For the given destination element of a shuffle, peek through shuffles to match a root vector source operand that contains that element in the same vector lane (ie, the same mask index), so we can eliminate the shuffle(s).
static Value * simplifyShuffleVectorInst (Value *Op0, Value *Op1, ArrayRef< int > Mask, Type *RetTy, const SimplifyQuery &Q, unsigned MaxRecurse)
static Constant * foldConstant (Instruction::UnaryOps Opcode, Value *&Op, const SimplifyQuery &Q)
static Value * simplifyFNegInst (Value *Op, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse)
Given the operand for an FNeg, see if we can fold the result.
static Constant * propagateNaN (Constant *In)
Try to propagate existing NaN values when possible.
static Constant * simplifyFPOp (ArrayRef< Value * > Ops, FastMathFlags FMF, const SimplifyQuery &Q, fp::ExceptionBehavior ExBehavior, RoundingMode Rounding)
Perform folds that are common to any floating-point operation.
static Value * simplifyFAddInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior=fp::ebIgnore, RoundingMode Rounding=RoundingMode::NearestTiesToEven)
Given operands for an FAdd, see if we can fold the result.
static Value * simplifyFSubInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior=fp::ebIgnore, RoundingMode Rounding=RoundingMode::NearestTiesToEven)
Given operands for an FSub, see if we can fold the result.
static Value * simplifyFMAFMul (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior, RoundingMode Rounding)
static Value * simplifyFMulInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior=fp::ebIgnore, RoundingMode Rounding=RoundingMode::NearestTiesToEven)
Given the operands for an FMul, see if we can fold the result.
static Value * simplifyFDivInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned, fp::ExceptionBehavior ExBehavior=fp::ebIgnore, RoundingMode Rounding=RoundingMode::NearestTiesToEven)
static Value * simplifyFRemInst (Value *Op0, Value *Op1, FastMathFlags FMF, const SimplifyQuery &Q, unsigned, fp::ExceptionBehavior ExBehavior=fp::ebIgnore, RoundingMode Rounding=RoundingMode::NearestTiesToEven)
static bool isIdempotent (Intrinsic::ID ID)
static bool removesFPFraction (Intrinsic::ID ID)
Return true if the intrinsic rounds a floating-point value to an integral floating-point value (not an integer type).
static Value * simplifyRelativeLoad (Constant *Ptr, Constant *Offset, const DataLayout &DL)
static Value * simplifyLdexp (Value *Op0, Value *Op1, const SimplifyQuery &Q, bool IsStrict)
static Value * simplifyUnaryIntrinsic (Function *F, Value *Op0, const SimplifyQuery &Q, const CallBase *Call)
static Value * foldMinMaxSharedOp (Intrinsic::ID IID, Value *Op0, Value *Op1)
Given a min/max intrinsic, see if it can be removed based on having an operand that is another min/max intrinsic with shared operand(s).
static Value * foldMinimumMaximumSharedOp (Intrinsic::ID IID, Value *Op0, Value *Op1)
Given a min/max intrinsic, see if it can be removed based on having an operand that is another min/max intrinsic with shared operand(s).
static MinMaxOptResult OptimizeConstMinMax (const Constant *RHSConst, const Intrinsic::ID IID, const CallBase *Call, Constant **OutNewConstVal)
static Value * simplifySVEIntReduction (Intrinsic::ID IID, Type *ReturnType, Value *Op0, Value *Op1)
static Value * simplifyIntrinsic (CallBase *Call, Value *Callee, ArrayRef< Value * > Args, const SimplifyQuery &Q)
static Value * tryConstantFoldCall (CallBase *Call, Value *Callee, ArrayRef< Value * > Args, const SimplifyQuery &Q)
static Value * simplifyFreezeInst (Value *Op0, const SimplifyQuery &Q)
Given operands for a Freeze, see if we can fold the result.
static bool replaceAndRecursivelySimplifyImpl (Instruction *I, Value *SimpleV, const TargetLibraryInfo *TLI, const DominatorTree *DT, AssumptionCache *AC, SmallSetVector< Instruction *, 8 > *UnsimplifiedUsers=nullptr)
Implementation of recursive simplification through an instruction's uses.
LLVM_ABI const SimplifyQuery llvm::getBestSimplifyQuery (Pass &, Function &)
LLVM_ABI const SimplifyQuery llvm::getBestSimplifyQuery (LoopStandardAnalysisResults &, const DataLayout &)
template<class T, class... TArgs>
const SimplifyQuery llvm::getBestSimplifyQuery (AnalysisManager< T, TArgs... > &, Function &)
template const SimplifyQuery llvm::getBestSimplifyQuery (AnalysisManager< Function > &, Function &)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instsimplify"
Definition at line 55 of file InstructionSimplify.cpp.
HANDLE_CAST_INST
#define HANDLE_CAST_INST (num, opc, clas)
Value:
case Instruction::opc:
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RecursionLimit
Definition at line 57 of file InstructionSimplify.cpp.
MinMaxOptResult
enum class MinMaxOptResult strong
Enumerator
CannotOptimize
UseNewConstVal
UseOtherVal
UseEither
Definition at line 6626 of file InstructionSimplify.cpp.
MonotonicType
enum class MonotonicType strong
Enumerator
GreaterEq
LowerEq
Definition at line 3081 of file InstructionSimplify.cpp.
Function Documentation
computePointerDifference()
Constant * computePointerDifference (const DataLayout & DL, Value * LHS, Value * RHS) static
Compute the constant difference between two pointer values.
If the difference is not a constant, returns zero.
Definition at line 688 of file InstructionSimplify.cpp.
References DL, llvm::dyn_cast(), llvm::ConstantVector::getSplat(), LHS, RHS, and stripAndComputeConstantOffsets().
Referenced by simplifySubInst().
computePointerICmp()
Constant * computePointerICmp (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Definition at line 2730 of file InstructionSimplify.cpp.
References A(), llvm::all_of(), assert(), llvm::CaptureTracker::captured(), llvm::ICmpInst::compare(), llvm::Continue, DL, llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::ObjectSizeOpts::EvalMode, F, getCompareTy(), llvm::getObjectSize(), llvm::ICmpInst::getSignedPredicate(), llvm::getUnderlyingObjects(), haveNonOverlappingStorage(), I, llvm::isa(), isAllocDisjoint(), llvm::isAllocLikeFn(), llvm::ICmpInst::isEquality(), llvm::ICmpInst::isEquality(), llvm::CmpInst::isFalseWhenEqual(), llvm::isKnownNonZero(), llvm::isNoAliasCall(), llvm::APInt::isNonNegative(), llvm::CmpInst::isSigned(), llvm::CmpInst::isTrueWhenEqual(), LHS, MI, llvm::ObjectSizeOpts::Min, llvm::ObjectSizeOpts::NullIsUnknownSize, llvm::NullPointerIsDefined(), llvm::PointerMayBeCaptured(), RHS, llvm::SimplifyQuery::TLI, llvm::CaptureTracker::tooManyUses(), and llvm::APInt::ult().
Referenced by simplifyICmpInst().
expandBinOp()
Value * expandBinOp (Instruction::BinaryOps Opcode, Value * V, Value * OtherOp, Instruction::BinaryOps OpcodeToExpand, const SimplifyQuery & Q, unsigned MaxRecurse) static
Try to simplify a binary operator of form "V op OtherOp" where V is "(B0 opex B1)" by distributing 'op' across 'opex' as "(B0 op OtherOp) opex (B1 op OtherOp)".
Definition at line 198 of file InstructionSimplify.cpp.
References B(), llvm::dyn_cast(), llvm::SimplifyQuery::getWithoutUndef(), llvm::Instruction::isCommutative(), and llvm::simplifyBinOp().
Referenced by expandCommutativeBinOp().
expandCommutativeBinOp()
Value * expandCommutativeBinOp (Instruction::BinaryOps Opcode, Value * L, Value * R, Instruction::BinaryOps OpcodeToExpand, const SimplifyQuery & Q, unsigned MaxRecurse) static
Try to simplify binops of form "A op (B op' C)" or the commuted variant by distributing op over op'.
Definition at line 232 of file InstructionSimplify.cpp.
References expandBinOp().
Referenced by simplifyAndInst(), simplifyMulInst(), and simplifyOrInst().
extractEquivalentCondition()
Value * extractEquivalentCondition (Value * V, CmpPredicate Pred, Value * LHS, Value * RHS) static
Rummage around inside V looking for something equivalent to the comparison "LHS Pred RHS".
Return such a value if found, otherwise return null. Helper function for analyzing max/min idioms.
Definition at line 2621 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::CmpInst::getSwappedPredicate(), LHS, and RHS.
Referenced by simplifyICmpWithMinMax().
foldConstant()
Constant * foldConstant (Instruction::UnaryOps Opcode, Value *& Op, const SimplifyQuery & Q) static
Definition at line 5731 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::ConstantFoldUnaryOpOperand(), llvm::SimplifyQuery::DL, and llvm::dyn_cast().
Referenced by simplifyFMAFMul(), simplifyFNegInst(), and simplifyFSubInst().
foldIdentityShuffles()
Value * foldIdentityShuffles (int DestElt, Value * Op0, Value * Op1, int MaskVal, Value * RootVec, unsigned MaxRecurse) static
For the given destination element of a shuffle, peek through shuffles to match a root vector source operand that contains that element in the same vector lane (ie, the same mask index), so we can eliminate the shuffle(s).
Definition at line 5564 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::dyn_cast(), foldIdentityShuffles(), and Op0.
Referenced by foldIdentityShuffles(), and simplifyShuffleVectorInst().
foldMinimumMaximumSharedOp()
Value * foldMinimumMaximumSharedOp (Intrinsic::ID IID, Value * Op0, Value * Op1) static
Given a min/max intrinsic, see if it can be removed based on having an operand that is another min/max intrinsic with shared operand(s).
The caller is expected to swap the operand arguments to handle commutation.
Definition at line 6572 of file InstructionSimplify.cpp.
References assert(), llvm::dyn_cast(), llvm::getInverseMinMaxIntrinsic(), llvm::M0(), llvm::M1(), and Op0.
Referenced by llvm::simplifyBinaryIntrinsic().
foldMinMaxSharedOp()
Value * foldMinMaxSharedOp (Intrinsic::ID IID, Value * Op0, Value * Op1) static
Given a min/max intrinsic, see if it can be removed based on having an operand that is another min/max intrinsic with shared operand(s).
The caller is expected to swap the operand arguments to handle commutation.
Definition at line 6547 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::getInverseMinMaxIntrinsic(), llvm::PatternMatch::m_c_MaxOrMin(), llvm::PatternMatch::m_MaxOrMin(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, X, and Y.
Referenced by llvm::simplifyBinaryIntrinsic().
foldOrCommuteConstant()
Constant * foldOrCommuteConstant (Instruction::BinaryOps Opcode, Value *& Op0, Value *& Op1, const SimplifyQuery & Q) static
Definition at line 566 of file InstructionSimplify.cpp.
References llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldFPInstOperands(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::Instruction::isCommutative(), Op0, and std::swap().
Referenced by simplifyAddInst(), simplifyAndInst(), simplifyDiv(), simplifyFAddInst(), simplifyFDivInst(), simplifyFMulInst(), simplifyFRemInst(), simplifyFSubInst(), simplifyMulInst(), simplifyOrInst(), simplifyRem(), simplifyShift(), simplifySubInst(), and simplifyXorInst().
getCompareTy()
Type * getCompareTy (Value * Op) static
Definition at line 2614 of file InstructionSimplify.cpp.
References llvm::CmpInst::makeCmpResultType().
Referenced by computePointerICmp(), simplifyFCmpInst(), simplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpUsingMonotonicValues(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithConstant(), simplifyICmpWithDominatingAssume(), simplifyICmpWithIntrinsicOnLHS(), simplifyICmpWithMinMax(), and simplifyICmpWithZero().
getFalse()
Constant * getFalse (Type * Ty) static
For a boolean type or a vector of boolean type, return false or a vector with every element false.
Definition at line 91 of file InstructionSimplify.cpp.
References llvm::ConstantInt::getFalse().
Referenced by simplifyAndOfICmpsWithAdd(), simplifyAndOrOfICmpsWithConstants(), simplifyCmpSelFalseCase(), simplifyExtractValueInst(), simplifyFCmpInst(), simplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), and simplifyUnsignedRangeCheck().
getRange()
std::optional< ConstantRange > getRange (Value * V, const InstrInfoQuery & IIQ) static
Helper method to get range from metadata or attribute.
Definition at line 3774 of file InstructionSimplify.cpp.
References A(), llvm::dyn_cast(), llvm::getConstantRangeFromMetadata(), llvm::InstrInfoQuery::getMetadata(), and I.
getTrue()
Constant * getTrue (Type * Ty) static
For a boolean type or a vector of boolean type, return true or a vector with every element true.
Definition at line 95 of file InstructionSimplify.cpp.
References llvm::ConstantInt::getTrue().
Referenced by simplifyAndOrOfICmpsWithConstants(), simplifyCmpSelTrueCase(), simplifyFCmpInst(), simplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), simplifyOrOfICmpsWithAdd(), and simplifyUnsignedRangeCheck().
getUnsignedMonotonicValues()
void getUnsignedMonotonicValues (SmallPtrSetImpl< Value * > & Res, Value * V, MonotonicType Type, const SimplifyQuery & Q, unsigned Depth = 0) static
Get values V_i such that V uge V_i (GreaterEq) or V ule V_i (LowerEq).
Definition at line 3084 of file InstructionSimplify.cpp.
References assert(), llvm::Depth, llvm::dyn_cast(), getUnsignedMonotonicValues(), GreaterEq, I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isKnownNonZero(), LowerEq, llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), X, and Y.
Referenced by getUnsignedMonotonicValues(), and simplifyICmpUsingMonotonicValues().
handleOtherCmpSelSimplifications()
Value * handleOtherCmpSelSimplifications (Value * TCmp, Value * FCmp, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse) static
We know comparison with both branches of select can be simplified, but they are not equal.
This routine handles some logical simplifications.
Definition at line 148 of file InstructionSimplify.cpp.
References Cond, llvm::Constant::getAllOnesValue(), llvm::impliesPoison(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::simplifyAndInst(), llvm::simplifyOrInst(), and llvm::simplifyXorInst().
Referenced by threadCmpOverSelect().
haveNonOverlappingStorage()
bool haveNonOverlappingStorage (const Value * V1, const Value * V2) static
Return true if V1 and V2 are each the base of some distict storage region [V, object_size(V)] which do not overlap.
Note that zero sized regions are possible, and that zero sized regions do not overlap with any other.
Definition at line 2660 of file InstructionSimplify.cpp.
References A(), llvm::dyn_cast(), and llvm::isa().
Referenced by computePointerICmp().
isAllocDisjoint()
bool isAllocDisjoint (const Value * V) static
Return true if the underlying object (storage) must be disjoint from storage returned by any noalias return call.
Definition at line 2640 of file InstructionSimplify.cpp.
References A(), and llvm::dyn_cast().
Referenced by computePointerICmp().
isDivZero()
bool isDivZero (Value * X, Value * Y, const SimplifyQuery & Q, unsigned MaxRecurse, bool IsSigned) static
Return true if we can simplify X / Y to 0.
Remainder can adapt that answer to simplify X % Y to X.
Definition at line 981 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::computeKnownBits(), llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULT, isICmpTrue(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), X, and Y.
Referenced by simplifyDivRem().
isICmpTrue()
bool isICmpTrue (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given a predicate and two operands, return true if the comparison is true.
This is a helper for div/rem simplification where we return some other value when we can prove a relationship between the operands.
Definition at line 972 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::dyn_cast_or_null(), LHS, RHS, and llvm::simplifyICmpInst().
Referenced by isDivZero(), and llvm::simplifyBinaryIntrinsic().
isIdempotent()
bool isIdempotent (Intrinsic::ID ID) static
Definition at line 6298 of file InstructionSimplify.cpp.
Referenced by simplifyUnaryIntrinsic().
isPoisonShift()
bool isPoisonShift (Value * Amount, const SimplifyQuery & Q) static
Returns true if a shift by Amount always yields poison.
Definition at line 1271 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), E(), llvm::APInt::getBitWidth(), I, llvm::isa(), isPoisonShift(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::match(), and llvm::APInt::uge().
Referenced by isPoisonShift(), and simplifyShift().
isSameCompare()
bool isSameCompare (Value * V, CmpPredicate Pred, Value * LHS, Value * RHS) static
isSameCompare - Is V equivalent to the comparison "LHS Pred RHS"?
Definition at line 98 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::CmpInst::getSwappedPredicate(), LHS, and RHS.
Referenced by simplifyCmpSelCase().
isSelectWithIdenticalPHI()
bool isSelectWithIdenticalPHI (PHINode & PN, PHINode & IdenticalPN)
Look for the following pattern and simplify to_fold to identicalPhi.
Here phi, to_fold and phi.next perform the same functionality as identicalPhi and hence the select instruction to_fold can be folded into identicalPhi.
BB1: identicalPhi = phi [ X, BB0 ], [ identicalPhi.next, BB1 ] phi = phi [ X, BB0 ], [ phi.next, BB1 ] ... identicalPhi.next = select cmp, val, identicalPhi (or select cmp, identicalPhi, val) to_fold = select cmp2, identicalPhi, phi phi.next = select cmp, val, to_fold (or select cmp, to_fold, val)
Prove that phi and identicalPhi are the same by induction:
Base case: Both phi and identicalPhi are equal on entry to the loop. Inductive case: Suppose phi and identicalPhi are equal at iteration i. We look at their values at iteration i+1 which are phi.next and identicalPhi.next. They would have become different only when cmp is false and the corresponding values to_fold and identicalPhi differ (similar reason for the other "or" case in the bracket).
The only condition when to_fold and identicalPh could differ is when cmp2 is false and to_fold is phi, which contradicts our inductive hypothesis that phi and identicalPhi are equal. Thus phi and identicalPhi are always equal at iteration i+1.
Definition at line 4910 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::SelectInst::getFalseValue(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getIncomingValueForBlock(), llvm::PHINode::getNumIncomingValues(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), and llvm::SelectInst::getTrueValue().
Referenced by simplifySelectInst().
OptimizeConstMinMax()
MinMaxOptResult OptimizeConstMinMax (const Constant * RHSConst, const Intrinsic::ID IID, const CallBase * Call, Constant ** OutNewConstVal) static
Definition at line 6638 of file InstructionSimplify.cpp.
References assert(), CannotOptimize, llvm::dyn_cast(), llvm::Value::getType(), llvm::ConstantFP::getValueAPF(), llvm::isa(), llvm::APFloat::isInfinity(), llvm::APFloat::isLargest(), llvm::APFloat::isNaN(), llvm::APFloat::isNegative(), llvm::APFloat::isSignaling(), llvm::APFloat::makeQuiet(), UseEither, UseNewConstVal, and UseOtherVal.
Referenced by llvm::simplifyBinaryIntrinsic().
propagateNaN()
Constant * propagateNaN (Constant * In) static
Try to propagate existing NaN values when possible.
If not, replace the constant or elements in the constant with a canonical NaN.
Definition at line 5760 of file InstructionSimplify.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::ConstantVector::get(), llvm::ConstantFP::getNaN(), llvm::Value::getType(), llvm::isa(), llvm::Constant::isNaN(), and llvm::Splat.
Referenced by simplifyFPOp().
removesFPFraction()
bool removesFPFraction (Intrinsic::ID ID) static
Return true if the intrinsic rounds a floating-point value to an integral floating-point value (not an integer type).
Definition at line 6320 of file InstructionSimplify.cpp.
Referenced by simplifyUnaryIntrinsic().
replaceAndRecursivelySimplifyImpl()
bool replaceAndRecursivelySimplifyImpl (Instruction * I, Value * SimpleV, const TargetLibraryInfo * TLI, const DominatorTree * DT, AssumptionCache * AC, SmallSetVector< Instruction *, 8 > * UnsimplifiedUsers = nullptr) static
Implementation of recursive simplification through an instruction's uses.
This is the common implementation of the recursive simplification routines. If we have a pre-simplified value in 'SimpleV', that is forcibly used to replace the instruction 'I'. Otherwise, we simply add 'I' to the list of instructions to process and attempt to simplify it using InstructionSimplify. Recursively visited users which could not be simplified themselves are to the optional UnsimplifiedUsers set for further processing by the caller.
This routine returns 'true' only when it simplifies something. The passed in simplified value does not count toward this.
Definition at line 7619 of file InstructionSimplify.cpp.
References llvm::cast(), DL, I, llvm::SetVector< T, Vector, Set, N >::insert(), llvm::simplifyInstruction(), and llvm::SetVector< T, Vector, Set, N >::size().
Referenced by llvm::replaceAndRecursivelySimplify().
simplifyAddInst()
Value * simplifyAddInst (Value * Op0, Value * Op1, bool IsNSW, bool IsNUW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Add, see if we can fold the result.
If not, this returns null.
i1 add -> xor.
Definition at line 594 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, foldOrCommuteConstant(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::isa(), llvm::isKnownNegation(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_AllOnes(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), Op0, simplifyAssociativeBinOp(), llvm::simplifyXorInst(), and Y.
simplifyAndCommutative()
Value * simplifyAndCommutative (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 2020 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::MIPatternMatch::m_Neg(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, simplifyAndOrWithICmpEq(), llvm::APInt::uge(), X, and Y.
Referenced by simplifyAndInst().
simplifyAndInst()
Value * simplifyAndInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an And, see if we can fold the result.
If not, this returns null.
Definition at line 2072 of file InstructionSimplify.cpp.
References A(), llvm::SimplifyQuery::AC, llvm::CallingConv::C, llvm::computeKnownBits(), llvm::KnownBits::countMaxActiveBits(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, expandCommutativeBinOp(), foldOrCommuteConstant(), llvm::APInt::getActiveBits(), llvm::ConstantInt::getFalse(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::KnownBits::getMaxValue(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::SimplifyQuery::IIQ, llvm::APInt::intersects(), llvm::isa(), llvm::isImpliedCondition(), llvm::isKnownToBeAPowerOfTwo(), llvm::APInt::isSubsetOf(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), Op0, simplifyAndCommutative(), simplifyAndOrOfCmps(), simplifyAssociativeBinOp(), simplifyByDomEq(), simplifyLogicOfAddSub(), threadBinOpOverPHI(), threadBinOpOverSelect(), llvm::InstrInfoQuery::UseInstrInfo, X, and Y.
simplifyAndOfICmps()
Value * simplifyAndOfICmps (ICmpInst * Op0, ICmpInst * Op1, const SimplifyQuery & Q) static
Definition at line 1726 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::IIQ, Op0, simplifyAndOfICmpsWithAdd(), simplifyAndOrOfICmpsWithConstants(), simplifyAndOrOfICmpsWithCtpop(), simplifyUnsignedRangeCheck(), and X.
Referenced by simplifyAndOrOfCmps().
simplifyAndOfICmpsWithAdd()
Value * simplifyAndOfICmpsWithAdd (ICmpInst * Op0, ICmpInst * Op1, const InstrInfoQuery & IIQ) static
Definition at line 1658 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::APInt::getBoolValue(), getFalse(), llvm::User::getOperand(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APInt::isStrictlyPositive(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and Op0.
Referenced by simplifyAndOfICmps().
simplifyAndOrOfCmps()
Value * simplifyAndOrOfCmps (const SimplifyQuery & Q, Value * Op0, Value * Op1, bool IsAnd) static
Definition at line 1903 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::ConstantFoldCastOperand(), llvm::SimplifyQuery::DL, llvm::dyn_cast(), Op0, simplifyAndOfICmps(), simplifyAndOrOfFCmps(), and simplifyOrOfICmps().
Referenced by simplifyAndInst(), and simplifyOrInst().
simplifyAndOrOfFCmps()
Value * simplifyAndOrOfFCmps (const SimplifyQuery & Q, FCmpInst * LHS, FCmpInst * RHS, bool IsAnd) static
Definition at line 1859 of file InstructionSimplify.cpp.
References llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UNO, llvm::ConstantInt::getBool(), llvm::Value::getType(), llvm::CmpInst::isOrdered(), llvm::CmpInst::isUnordered(), LHS, llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_FAbs(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), RHS, and simplifyAndOrOfFCmpsWithConstants().
Referenced by simplifyAndOrOfCmps().
simplifyAndOrOfFCmpsWithConstants()
Value * simplifyAndOrOfFCmpsWithConstants (FCmpInst * Cmp0, FCmpInst * Cmp1, bool IsAnd) static
Test if a pair of compares with a shared operand and 2 constants has an empty set intersection, full set union, or if one compare is a superset of the other.
Definition at line 1822 of file InstructionSimplify.cpp.
References llvm::ConstantInt::getBool(), llvm::CmpInst::getInversePredicate(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::PatternMatch::m_APFloat(), llvm::ConstantFPRange::makeExactFCmpRegion(), and llvm::PatternMatch::match().
Referenced by simplifyAndOrOfFCmps().
simplifyAndOrOfICmpsWithConstants()
Value * simplifyAndOrOfICmpsWithConstants (ICmpInst * Cmp0, ICmpInst * Cmp1, bool IsAnd) static
Test if a pair of compares with a shared operand and 2 constants has an empty set intersection, full set union, or if one compare is a superset of the other.
Definition at line 1621 of file InstructionSimplify.cpp.
References getFalse(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), getTrue(), llvm::Value::getType(), llvm::PatternMatch::m_APInt(), llvm::ConstantRange::makeExactICmpRegion(), and llvm::PatternMatch::match().
Referenced by simplifyAndOfICmps(), and simplifyOrOfICmps().
simplifyAndOrOfICmpsWithCtpop()
Value * simplifyAndOrOfICmpsWithCtpop (ICmpInst * Cmp0, ICmpInst * Cmp1, bool IsAnd) static
Try to simplify and/or of icmp with ctpop intrinsic.
Definition at line 1706 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), and X.
Referenced by simplifyAndOfICmps(), and simplifyOrOfICmps().
simplifyAndOrWithICmpEq()
Value * simplifyAndOrWithICmpEq (unsigned Opcode, Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 1946 of file InstructionSimplify.cpp.
References A(), assert(), B(), llvm::ConstantExpr::getBinOpAbsorber(), llvm::ConstantExpr::getBinOpIdentity(), llvm::SimplifyQuery::getWithoutUndef(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, and llvm::simplifyWithOpReplaced().
Referenced by simplifyAndCommutative(), and simplifyOrInst().
simplifyAShrInst()
Value * simplifyAShrInst (Value * Op0, Value * Op1, bool IsExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an AShr, see if we can fold the result.
If not, this returns null.
Definition at line 1479 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::ComputeNumSignBits(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::Constant::getAllOnesValue(), llvm::SimplifyQuery::IIQ, llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, simplifyRightShift(), llvm::InstrInfoQuery::UseInstrInfo, and X.
simplifyAssociativeBinOp()
Value * simplifyAssociativeBinOp (Instruction::BinaryOps Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Generic simplifications for associative binary operations.
Returns the simpler value, or null if none was found.
Definition at line 250 of file InstructionSimplify.cpp.
References A(), assert(), B(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), LHS, Op0, RHS, and llvm::simplifyBinOp().
Referenced by simplifyAddInst(), simplifyAndInst(), simplifyMulInst(), simplifyOrInst(), and simplifyXorInst().
simplifyBinOp() [1/2]
Value * simplifyBinOp (unsigned Opcode, Value * LHS, Value * RHS, const FastMathFlags & FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a BinaryOperator, see if we can fold the result.
If not, this returns null. Try to use FastMathFlags when folding the result.
Definition at line 6258 of file InstructionSimplify.cpp.
References LHS, RHS, llvm::simplifyBinOp(), llvm::simplifyFAddInst(), llvm::simplifyFDivInst(), llvm::simplifyFMulInst(), and llvm::simplifyFSubInst().
simplifyBinOp() [2/2]
Value * simplifyBinOp (unsigned Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a BinaryOperator, see if we can fold the result.
If not, this returns null.
Definition at line 6207 of file InstructionSimplify.cpp.
References LHS, llvm_unreachable, RHS, llvm::simplifyAddInst(), llvm::simplifyAndInst(), llvm::simplifyAShrInst(), llvm::simplifyFAddInst(), llvm::simplifyFDivInst(), llvm::simplifyFMulInst(), llvm::simplifyFRemInst(), llvm::simplifyFSubInst(), llvm::simplifyLShrInst(), llvm::simplifyMulInst(), llvm::simplifyOrInst(), llvm::simplifySDivInst(), llvm::simplifyShlInst(), llvm::simplifySRemInst(), llvm::simplifySubInst(), llvm::simplifyUDivInst(), llvm::simplifyURemInst(), and llvm::simplifyXorInst().
Referenced by llvm::InstSimplifyFolder::FoldBinOp(), llvm::InstSimplifyFolder::FoldBinOpFMF(), llvm::InstSimplifyFolder::FoldExactBinOp(), and llvm::InstSimplifyFolder::FoldNoWrapBinOp().
simplifyByDomEq()
Value * simplifyByDomEq (unsigned Opcode, Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Test if there is a dominating equivalence condition for the two operands.
If there is, try to reduce the binary operation between the two operands. Example: Op0 - Op1 --> 0 when Op0 == Op1
Definition at line 712 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::Constant::getNullValue(), llvm::CmpInst::ICMP_EQ, llvm::isImpliedByDomCondition(), Op0, and RecursionLimit.
Referenced by simplifyAndInst(), simplifyDivRem(), simplifyOrInst(), simplifySubInst(), and simplifyXorInst().
simplifyCastInst()
Value * simplifyCastInst (unsigned CastOpc, Value * Op, Type * Ty, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 5520 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::ConstantFoldCastOperand(), llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::DataLayout::getIndexType(), llvm::Value::getType(), llvm::CastInst::isEliminableCastPair(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_PtrAdd(), llvm::PatternMatch::m_PtrToIntOrAddr(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
Referenced by llvm::InstSimplifyFolder::FoldCast().
simplifyCmpInst()
Value * simplifyCmpInst (CmpPredicate Predicate, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a CmpInst, see if we can fold the result.
Definition at line 6286 of file InstructionSimplify.cpp.
References llvm::CmpInst::isIntPredicate(), LHS, RHS, llvm::simplifyFCmpInst(), and llvm::simplifyICmpInst().
Referenced by llvm::InstSimplifyFolder::FoldCmp().
simplifyCmpSelCase()
Value * simplifyCmpSelCase (CmpPredicate Pred, Value * LHS, Value * RHS, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse, Constant * TrueOrFalse) static
Simplify comparison with true or false branch of select: sel = select i1 cond, i32 tv, i32 fv cmp = icmp sle i32 sel, rhs Compose new comparison by substituting sel with either tv or fv and see if it simplifies.
Definition at line 115 of file InstructionSimplify.cpp.
References Cond, isSameCompare(), LHS, RHS, and llvm::simplifyCmpInst().
Referenced by simplifyCmpSelFalseCase(), and simplifyCmpSelTrueCase().
simplifyCmpSelFalseCase()
Value * simplifyCmpSelFalseCase (CmpPredicate Pred, Value * LHS, Value * RHS, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse) static
Simplify comparison with false branch of select.
Definition at line 139 of file InstructionSimplify.cpp.
References Cond, getFalse(), LHS, RHS, and simplifyCmpSelCase().
Referenced by threadCmpOverSelect().
simplifyCmpSelOfMaxMin()
Value * simplifyCmpSelOfMaxMin (Value * CmpLHS, Value * CmpRHS, CmpPredicate Pred, Value * TVal, Value * FVal) static
Definition at line 4605 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::CmpInst::getInversePredicate(), llvm::CmpInst::getStrictPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::PatternMatch::m_c_MaxOrMin(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), std::swap(), X, and Y.
Referenced by simplifySelectWithICmpCond().
simplifyCmpSelTrueCase()
Value * simplifyCmpSelTrueCase (CmpPredicate Pred, Value * LHS, Value * RHS, Value * Cond, const SimplifyQuery & Q, unsigned MaxRecurse) static
Simplify comparison with true branch of select.
Definition at line 131 of file InstructionSimplify.cpp.
References Cond, getTrue(), LHS, RHS, and simplifyCmpSelCase().
Referenced by threadCmpOverSelect().
simplifyDiv()
Value * simplifyDiv (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, bool IsExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
These are simplifications common to SDiv and UDiv.
Definition at line 1140 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::computeKnownBits(), llvm::KnownBits::countMaxTrailingZeros(), llvm::APInt::countr_zero(), foldOrCommuteConstant(), llvm::PoisonValue::get(), llvm::APInt::isPowerOf2(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, simplifyDivRem(), and X.
Referenced by simplifySDivInst(), and simplifyUDivInst().
simplifyDivRem()
Value * simplifyDivRem (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Check for common or similar folds of integer division or integer remainder.
This applies to all 4 opcodes (sdiv/udiv/srem/urem).
Definition at line 1046 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::PoisonValue::get(), llvm::KnownBits::getBitWidth(), llvm::Constant::getNullValue(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::SimplifyQuery::IIQ, llvm::isa(), isDivZero(), llvm::SimplifyQuery::isUndefValue(), llvm::KnownBits::isZero(), llvm::PatternMatch::m_c_Mul(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), Mul, Op0, simplifyByDomEq(), threadBinOpOverPHI(), threadBinOpOverSelect(), and X.
Referenced by simplifyDiv(), and simplifyRem().
simplifyExtractElementInst()
Value * simplifyExtractElementInst (Value * Vec, Value * Idx, const SimplifyQuery & Q, unsigned) static
Given operands for an ExtractElementInst, see if we can fold the result.
If not, this returns null.
Definition at line 5417 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::findScalarElement(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getExtractElement(), llvm::getSplatValue(), llvm::Value::getType(), llvm::isa(), llvm::SimplifyQuery::isUndefValue(), and llvm::Splat.
Referenced by llvm::InstSimplifyFolder::FoldExtractElement().
simplifyExtractValueInst()
Value * simplifyExtractValueInst (Value * Agg, ArrayRef< unsigned > Idxs, const SimplifyQuery & , unsigned) static
Given operands for an ExtractValueInst, see if we can fold the result.
If not, this returns null.
Definition at line 5374 of file InstructionSimplify.cpp.
References assert(), llvm::ConstantFoldExtractValueInstruction(), llvm::dyn_cast(), getFalse(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Value(), llvm::CmpInst::makeCmpResultType(), llvm::PatternMatch::match(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::InstSimplifyFolder::FoldExtractValue().
simplifyFAddInst()
Value * simplifyFAddInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior = fp::ebIgnore, RoundingMode Rounding = RoundingMode::NearestTiesToEven) static
Given operands for an FAdd, see if we can fold the result.
If not, this returns null.
Definition at line 5844 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), llvm::CallingConv::C, llvm::canIgnoreSNaN(), llvm::cannotBeNegativeZero(), llvm::canRoundingModeBe(), llvm::fp::ebIgnore, foldOrCommuteConstant(), llvm::ConstantFP::getZero(), llvm::isDefaultFPEnvironment(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_Inf(), llvm::PatternMatch::m_NegZeroFP(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::NearestTiesToEven, llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), Op0, simplifyFPOp(), llvm::TowardNegative, and X.
simplifyFCmpInst()
Value * simplifyFCmpInst (CmpPredicate Pred, Value * LHS, Value * RHS, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an FCmpInst, see if we can fold the result.
If not, this returns null.
Definition at line 4105 of file InstructionSimplify.cpp.
References assert(), llvm::CallingConv::C, llvm::KnownFPClass::cannotBeOrderedLessThanZero(), llvm::cast(), llvm::computeKnownFPClass(), llvm::ConstantFoldCompareInstOperands(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::fcAllFlags, llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::fcmpToClassTest(), llvm::fcNan, llvm::fcNone, llvm::PoisonValue::get(), llvm::ConstantInt::getBool(), getCompareTy(), getFalse(), llvm::Instruction::getFunction(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::isa(), llvm::CmpInst::isFalseWhenEqual(), llvm::CmpInst::isFPPredicate(), llvm::isImpliedByDomCondition(), llvm::KnownFPClass::isKnownAlwaysNaN(), llvm::KnownFPClass::isKnownNeverNaN(), llvm::CmpInst::isTrueWhenEqual(), llvm::SimplifyQuery::isUndefValue(), llvm::CmpInst::isUnordered(), LHS, llvm_unreachable, llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_APFloatAllowPoison(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), llvm::KnownFPClass::OrderedLessThanZeroMask, RHS, std::swap(), threadCmpOverPHI(), threadCmpOverSelect(), and llvm::SimplifyQuery::TLI.
simplifyFDivInst()
Value * simplifyFDivInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned , fp::ExceptionBehavior ExBehavior = fp::ebIgnore, RoundingMode Rounding = RoundingMode::NearestTiesToEven) static
Definition at line 6072 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), llvm::CallingConv::C, llvm::fp::ebIgnore, foldOrCommuteConstant(), llvm::PoisonValue::get(), llvm::Value::getType(), llvm::ConstantFP::getZero(), llvm::isDefaultFPEnvironment(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_c_FMul(), llvm::PatternMatch::m_FNegNSZ(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::NearestTiesToEven, llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), Op0, simplifyFPOp(), and X.
simplifyFMAFMul()
Value * simplifyFMAFMul (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior, RoundingMode Rounding) static
Definition at line 5976 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), llvm::CallingConv::C, llvm::computeKnownFPClass(), llvm::fcInf, llvm::fcNan, foldConstant(), llvm::ConstantFP::getZero(), llvm::isDefaultFPEnvironment(), llvm::KnownFPClass::isKnownNever(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_Sqrt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), Op0, llvm::KnownFPClass::SignBit, simplifyFPOp(), std::swap(), and X.
simplifyFMulInst()
Value * simplifyFMulInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior = fp::ebIgnore, RoundingMode Rounding = RoundingMode::NearestTiesToEven) static
Given the operands for an FMul, see if we can fold the result.
Definition at line 6027 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::fp::ebIgnore, foldOrCommuteConstant(), llvm::isDefaultFPEnvironment(), llvm::NearestTiesToEven, Op0, and llvm::simplifyFMAFMul().
simplifyFNegInst()
Value * simplifyFNegInst (Value * Op, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given the operand for an FNeg, see if we can fold the result.
If not, this returns null.
Definition at line 5740 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, foldConstant(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and X.
simplifyFPOp()
Constant * simplifyFPOp (ArrayRef< Value * > Ops, FastMathFlags FMF, const SimplifyQuery & Q, fp::ExceptionBehavior ExBehavior, RoundingMode Rounding) static
Perform folds that are common to any floating-point operation.
This implies transforms based on poison/undef/NaN because the operation itself makes no difference to the result.
Definition at line 5802 of file InstructionSimplify.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::any_of(), llvm::cast(), llvm::fp::ebStrict, llvm::PoisonValue::get(), llvm::ConstantFP::getNaN(), getType(), llvm::IsaPred, llvm::isDefaultFPEnvironment(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_Inf(), llvm::PatternMatch::m_NaN(), llvm::PatternMatch::match(), llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), and propagateNaN().
Referenced by simplifyFAddInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFRemInst(), simplifyFSubInst(), and simplifyIntrinsic().
simplifyFPUnOp()
Value * simplifyFPUnOp (unsigned Opcode, Value * Op, const FastMathFlags & FMF, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given the operand for a UnaryOperator, see if we can fold the result.
If not, this returns null. Try to use FastMathFlags when folding the result.
Definition at line 6185 of file InstructionSimplify.cpp.
References llvm::simplifyFNegInst(), and llvm::simplifyUnOp().
simplifyFreezeInst()
Value * simplifyFreezeInst (Value * Op0, const SimplifyQuery & Q) static
Given operands for a Freeze, see if we can fold the result.
Definition at line 7404 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DT, llvm::isGuaranteedNotToBeUndefOrPoison(), and Op0.
simplifyFRemInst()
Value * simplifyFRemInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned , fp::ExceptionBehavior ExBehavior = fp::ebIgnore, RoundingMode Rounding = RoundingMode::NearestTiesToEven) static
Definition at line 6131 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::fp::ebIgnore, foldOrCommuteConstant(), llvm::ConstantFP::getNegativeZero(), llvm::ConstantFP::getZero(), llvm::isDefaultFPEnvironment(), llvm::PatternMatch::m_NegZeroFP(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::match(), llvm::NearestTiesToEven, llvm::FastMathFlags::noNaNs(), Op0, and simplifyFPOp().
simplifyFSubInst()
Value * simplifyFSubInst (Value * Op0, Value * Op1, FastMathFlags FMF, const SimplifyQuery & Q, unsigned MaxRecurse, fp::ExceptionBehavior ExBehavior = fp::ebIgnore, RoundingMode Rounding = RoundingMode::NearestTiesToEven) static
Given operands for an FSub, see if we can fold the result.
If not, this returns null.
Definition at line 5910 of file InstructionSimplify.cpp.
References llvm::FastMathFlags::allowReassoc(), llvm::CallingConv::C, llvm::canIgnoreSNaN(), llvm::cannotBeNegativeZero(), llvm::canRoundingModeBe(), llvm::fp::ebIgnore, foldConstant(), foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::isDefaultFPEnvironment(), llvm::PatternMatch::m_AnyZeroFP(), llvm::PatternMatch::m_c_FAdd(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_Inf(), llvm::PatternMatch::m_NegZeroFP(), llvm::PatternMatch::m_PosZeroFP(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::NearestTiesToEven, llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), Op0, simplifyFPOp(), llvm::TowardNegative, and X.
simplifyGEPInst()
Value * simplifyGEPInst (Type * SrcTy, Value * Ptr, ArrayRef< Value * > Indices, GEPNoWrapFlags NW, const SimplifyQuery & Q, unsigned) static
Given operands for an GetElementPtrInst, see if we can fold the result.
If not, this returns null.
Definition at line 5157 of file InstructionSimplify.cpp.
References llvm::all_of(), llvm::any_of(), llvm::ArrayRef< T >::back(), llvm::CallingConv::C, llvm::cast(), llvm::ConstantFoldConstant(), llvm::ConstantFoldGetElementPtr(), llvm::SimplifyQuery::DL, llvm::ArrayRef< T >::drop_back(), llvm::dyn_cast(), llvm::ArrayRef< T >::empty(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::VectorType::get(), llvm::DataLayout::getAddressSizeInBits(), llvm::Type::getContext(), llvm::ConstantExpr::getGetElementPtr(), llvm::GetElementPtrInst::getIndexedType(), llvm::DataLayout::getIndexSizeInBits(), llvm::ConstantExpr::getIntToPtr(), llvm::Type::getPointerAddressSpace(), getScalarSizeInBits(), llvm::Type::getScalarType(), getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeSizeInBits(), llvm::getUnderlyingObject(), llvm::isa(), llvm::IsaPred, llvm::APInt::isOne(), llvm::ConstantExpr::isSupportedGetElementPtr(), llvm::SimplifyQuery::isUndefValue(), llvm::Type::isVectorTy(), llvm::APInt::isZero(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_PtrToIntOrAddr(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::PatternMatch::match_fn(), P, llvm::ArrayRef< T >::size(), and llvm::Value::stripAndAccumulateInBoundsConstantOffsets().
Referenced by llvm::InstSimplifyFolder::FoldGEP().
simplifyICmpInst()
Value * simplifyICmpInst (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an ICmpInst, see if we can fold the result.
If not, this returns null.
Definition at line 3790 of file InstructionSimplify.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), computePointerICmp(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstOperands(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::DataLayout::getAddressType(), llvm::Constant::getAllOnesValue(), llvm::ConstantInt::getBool(), getCompareTy(), getFalse(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getIntToPtr(), llvm::CmpInst::getInversePredicate(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::getRange(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::ICmpInst::getUnsignedPredicate(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::SimplifyQuery::IIQ, llvm::isa(), llvm::Constant::isAllOnesValue(), llvm::ICmpInst::isEquality(), llvm::isImpliedByDomCondition(), llvm::CmpInst::isIntPredicate(), llvm::isKnownNonEqual(), llvm::Constant::isNullValue(), llvm::CmpInst::isTrueWhenEqual(), llvm::SimplifyQuery::isUndefValue(), LHS, llvm_unreachable, llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), RHS, llvm::simplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpUsingMonotonicValues(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), simplifyICmpWithDominatingAssume(), simplifyICmpWithIntrinsicOnLHS(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), std::swap(), threadCmpOverPHI(), threadCmpOverSelect(), and llvm::SimplifyQuery::TLI.
simplifyICmpOfBools()
Value * simplifyICmpOfBools (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Fold an icmp when its operands have i1 scalar type.
For signed comparison, the values for an i1 are 0 and -1 respectively. This maps into a truth table of: LHS | RHS | LHS >=s RHS | LHS implies RHS 0 | 0 | 1 (0 >= 0) | 1 0 | 1 | 1 (0 >= -1) | 1 1 | 0 | 0 (-1 >= 0) | 0 1 | 1 | 1 (-1 >= -1) | 1
SLE follows the same logic as SGE with the LHS and RHS swapped.
Definition at line 2867 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::DL, getCompareTy(), getFalse(), getTrue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isImpliedCondition(), llvm::Type::isIntOrIntVectorTy(), LHS, llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), RHS, and X.
Referenced by simplifyICmpInst().
simplifyICmpUsingMonotonicValues()
Value * simplifyICmpUsingMonotonicValues (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Definition at line 3135 of file InstructionSimplify.cpp.
References llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::ConstantInt::getBool(), getCompareTy(), getUnsignedMonotonicValues(), GreaterEq, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, LHS, LowerEq, and RHS.
Referenced by simplifyICmpInst().
simplifyICmpWithBinOp()
Value * simplifyICmpWithBinOp (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
TODO: A large part of this logic is duplicated in InstCombine's foldICmpBinOp().
We should be able to share that and avoid the code duplication.
Definition at line 3299 of file InstructionSimplify.cpp.
References A(), assert(), B(), llvm::CallingConv::C, llvm::cast(), D(), llvm::dyn_cast(), getCompareTy(), llvm::ConstantInt::getFalse(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::SimplifyQuery::IIQ, llvm::ICmpInst::isEquality(), llvm::ICmpInst::isEquality(), llvm::InstrInfoQuery::isExact(), llvm::isKnownNonZero(), llvm::APInt::isNonNegative(), llvm::ICmpInst::isRelational(), llvm::CmpInst::isSigned(), llvm::APInt::isSubsetOf(), llvm::CmpInst::isUnsigned(), LHS, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SignMask(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), RHS, llvm::simplifyICmpInst(), simplifyICmpWithBinOpOnLHS(), std::swap(), trySimplifyICmpWithAdds(), and Y.
Referenced by simplifyICmpInst().
simplifyICmpWithBinOpOnLHS()
Value * simplifyICmpWithBinOpOnLHS (CmpPredicate Pred, BinaryOperator * LBO, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 3154 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::computeKnownBits(), llvm::APInt::getBitWidth(), getCompareTy(), getFalse(), getTrue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::isKnownNonZero(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), RHS, llvm::APInt::ule(), and Y.
Referenced by simplifyICmpWithBinOp().
simplifyICmpWithConstant()
Value * simplifyICmpWithConstant (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Definition at line 3030 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::computeConstantRange(), llvm::ConstantRange::contains(), llvm::ConstantInt::getBool(), getCompareTy(), llvm::ConstantInt::getFalse(), llvm::ConstantInt::getTrue(), llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::SimplifyQuery::IIQ, llvm::ConstantRange::inverse(), llvm::ConstantRange::isEmptySet(), llvm::ICmpInst::isEquality(), llvm::ConstantRange::isFullSet(), llvm::isKnownNonZero(), llvm::isSignBitCheck(), llvm::CmpInst::isSigned(), LHS, llvm::PatternMatch::m_APIntAllowPoison(), llvm::PatternMatch::m_ElementWiseBitCast(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Value(), llvm::ConstantRange::makeExactICmpRegion(), llvm::PatternMatch::match(), RHS, llvm::InstrInfoQuery::UseInstrInfo, and X.
Referenced by simplifyICmpInst().
simplifyICmpWithDominatingAssume()
Value * simplifyICmpWithDominatingAssume (CmpPredicate Predicate, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Definition at line 3718 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::AssumptionCache::assumptionsFor(), llvm::cast(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, getCompareTy(), llvm::isImpliedCondition(), llvm::isValidAssumeForContext(), LHS, and RHS.
Referenced by simplifyICmpInst().
simplifyICmpWithIntrinsicOnLHS()
Value * simplifyICmpWithIntrinsicOnLHS (CmpPredicate Pred, Value * LHS, Value * RHS) static
Definition at line 3741 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), getCompareTy(), llvm::ConstantInt::getFalse(), llvm::ConstantInt::getTrue(), llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, II, LHS, llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::match(), and RHS.
Referenced by simplifyICmpInst().
simplifyICmpWithMinMax()
Value * simplifyICmpWithMinMax (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
simplify integer comparisons where at least one operand of the compare matches an integer min/max idiom.
Definition at line 3533 of file InstructionSimplify.cpp.
References A(), B(), llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::CallingConv::C, D(), extractEquivalentCondition(), getCompareTy(), getFalse(), llvm::CmpInst::getInversePredicate(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, LHS, llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), P, RHS, llvm::simplifyICmpInst(), and std::swap().
Referenced by simplifyICmpInst().
simplifyICmpWithZero()
Value * simplifyICmpWithZero (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q) static
Try hard to fold icmp with zero RHS because this is a common case.
Definition at line 2970 of file InstructionSimplify.cpp.
References llvm::computeKnownBits(), getCompareTy(), getFalse(), getTrue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isKnownNonZero(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), LHS, llvm_unreachable, llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), and RHS.
Referenced by simplifyICmpInst().
simplifyInsertValueInst()
Value * simplifyInsertValueInst (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const SimplifyQuery & Q, unsigned) static
Given operands for an InsertValueInst, see if we can fold the result.
If not, this returns null.
Definition at line 5295 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInsertValueInstruction(), llvm::dyn_cast(), llvm::Value::getType(), llvm::isa(), llvm::isGuaranteedNotToBePoison(), and llvm::SimplifyQuery::isUndefValue().
Referenced by llvm::InstSimplifyFolder::FoldInsertValue().
simplifyInstructionWithOperands()
Value * simplifyInstructionWithOperands (Instruction * I, ArrayRef< Value * > NewOps, const SimplifyQuery & SQ, unsigned MaxRecurse) static
See if we can compute a simplified version of this instruction.
If not, this returns null.
Definition at line 7455 of file InstructionSimplify.cpp.
References llvm::all_of(), assert(), llvm::ArrayRef< T >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), llvm::ConstantFoldInstOperands(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::ArrayRef< T >::drop_back(), llvm::Instruction::getFunction(), llvm::SimplifyQuery::getWithInstruction(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), I, llvm::SimplifyQuery::IIQ, llvm::IsaPred, llvm::InstrInfoQuery::isExact(), IV, llvm::simplifyAddInst(), llvm::simplifyAndInst(), llvm::simplifyAShrInst(), llvm::simplifyCall(), llvm::simplifyCastInst(), llvm::simplifyExtractElementInst(), llvm::simplifyExtractValueInst(), llvm::simplifyFAddInst(), llvm::simplifyFCmpInst(), llvm::simplifyFDivInst(), llvm::simplifyFMulInst(), llvm::simplifyFNegInst(), llvm::simplifyFreezeInst(), llvm::simplifyFRemInst(), llvm::simplifyFSubInst(), llvm::simplifyGEPInst(), llvm::simplifyICmpInst(), llvm::simplifyInsertElementInst(), llvm::simplifyInsertValueInst(), llvm::simplifyLoadInst(), llvm::simplifyLShrInst(), llvm::simplifyMulInst(), llvm::simplifyOrInst(), simplifyPHINode(), llvm::simplifySDivInst(), llvm::simplifySelectInst(), llvm::simplifyShlInst(), llvm::simplifyShuffleVectorInst(), llvm::simplifySRemInst(), llvm::simplifySubInst(), llvm::simplifyUDivInst(), llvm::simplifyURemInst(), llvm::simplifyXorInst(), llvm::ArrayRef< T >::size(), llvm::SimplifyQuery::TLI, and llvm::transform().
simplifyIntrinsic()
Value * simplifyIntrinsic (CallBase * Call, Value * Callee, ArrayRef< Value * > Args, const SimplifyQuery & Q) static
Definition at line 7134 of file InstructionSimplify.cpp.
References llvm::any_of(), assert(), llvm::BitWidth, llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::fp::ebIgnore, F, llvm::ConstantPointerNull::get(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::Constant::getAllOnesValue(), llvm::GCRelocateInst::getBasePtr(), llvm::APInt::getBitWidth(), llvm::GCRelocateInst::getDerivedPtr(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::ConstantRange::getSingleElement(), llvm::Value::getType(), llvm::getVScaleRange(), llvm::intrinsicPropagatesPoison(), llvm::isa(), llvm::IsaPred, llvm::APInt::isNonNegative(), llvm::isSplatValue(), llvm::SimplifyQuery::isUndefValue(), llvm::APInt::isZero(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::maskIsAllZeroOrUndef(), llvm::PatternMatch::match(), llvm::NearestTiesToEven, llvm::Intrinsic::not_intrinsic, Op0, llvm::simplifyBinaryIntrinsic(), llvm::simplifyFAddInst(), llvm::simplifyFDivInst(), llvm::simplifyFMulInst(), simplifyFPOp(), llvm::simplifyFRemInst(), llvm::simplifyFSubInst(), simplifyLdexp(), simplifyUnaryIntrinsic(), std::swap(), llvm::APInt::urem(), and X.
Referenced by llvm::simplifyCall(), and llvm::simplifyConstrainedFPCall().
simplifyLdexp()
Value * simplifyLdexp (Value * Op0, Value * Op1, const SimplifyQuery & Q, bool IsStrict) static
Definition at line 6389 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::ConstantFP::getNaN(), llvm::isa(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_APFloat(), llvm::PatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), and Op0.
Referenced by llvm::simplifyBinaryIntrinsic(), and simplifyIntrinsic().
simplifyLogicOfAddSub()
Value * simplifyLogicOfAddSub (Value * Op0, Value * Op1, Instruction::BinaryOps Opcode) static
Given a bitwise logic op, check if the operands are add/sub with a common source value and inverted constant (identity: C - X -> ~(X + ~C)).
Definition at line 1997 of file InstructionSimplify.cpp.
References assert(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getNot(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Instruction::isBitwiseLogicOp(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, and X.
Referenced by simplifyAndInst(), simplifyOrInst(), and simplifyXorInst().
simplifyLShrInst()
Value * simplifyLShrInst (Value * Op0, Value * Op1, bool IsExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an LShr, see if we can fold the result.
If not, this returns null.
Definition at line 1442 of file InstructionSimplify.cpp.
References llvm::computeKnownBits(), llvm::KnownBits::countMaxActiveBits(), llvm::SimplifyQuery::IIQ, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, simplifyRightShift(), llvm::APInt::uge(), llvm::InstrInfoQuery::UseInstrInfo, X, and Y.
simplifyMulInst()
Value * simplifyMulInst (Value * Op0, Value * Op1, bool IsNSW, bool IsNUW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a Mul, see if we can fold the result.
If not, this returns null.
Definition at line 899 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, expandCommutativeBinOp(), foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::SimplifyQuery::IIQ, llvm::isa(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_IDiv(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), Op0, llvm::simplifyAndInst(), simplifyAssociativeBinOp(), threadBinOpOverPHI(), threadBinOpOverSelect(), llvm::InstrInfoQuery::UseInstrInfo, and X.
simplifyOrInst()
Value * simplifyOrInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Or, see if we can fold the result.
If not, this returns null.
Definition at line 2347 of file InstructionSimplify.cpp.
References A(), B(), llvm::CallingConv::C, llvm::SimplifyQuery::DL, expandCommutativeBinOp(), foldOrCommuteConstant(), llvm::Constant::getAllOnesValue(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::isa(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::isImpliedCondition(), llvm::APInt::isMask(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_Add(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::MaskedValueIsZero(), llvm::PatternMatch::match(), N, Op0, simplifyAndOrOfCmps(), simplifyAndOrWithICmpEq(), simplifyAssociativeBinOp(), simplifyByDomEq(), simplifyLogicOfAddSub(), simplifyOrLogic(), threadBinOpOverPHI(), threadBinOpOverSelect(), X, and Y.
simplifyOrLogic()
Value * simplifyOrLogic (Value * X, Value * Y) static
Definition at line 2256 of file InstructionSimplify.cpp.
References A(), assert(), B(), llvm::Constant::getAllOnesValue(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_LogicalAnd(), llvm::PatternMatch::m_c_LogicalOr(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_c_Xor(), llvm::PatternMatch::m_CombineAnd(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::match(), X, and Y.
Referenced by simplifyOrInst().
simplifyOrOfICmps()
Value * simplifyOrOfICmps (ICmpInst * Op0, ICmpInst * Op1, const SimplifyQuery & Q) static
Definition at line 1796 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::IIQ, Op0, simplifyAndOrOfICmpsWithConstants(), simplifyAndOrOfICmpsWithCtpop(), simplifyOrOfICmpsWithAdd(), simplifyUnsignedRangeCheck(), and X.
Referenced by simplifyAndOrOfCmps().
simplifyOrOfICmpsWithAdd()
Value * simplifyOrOfICmpsWithAdd (ICmpInst * Op0, ICmpInst * Op1, const InstrInfoQuery & IIQ) static
Definition at line 1749 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::APInt::getBoolValue(), llvm::User::getOperand(), getTrue(), llvm::InstrInfoQuery::hasNoSignedWrap(), llvm::InstrInfoQuery::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::APInt::isStrictlyPositive(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and Op0.
Referenced by simplifyOrOfICmps().
simplifyPHINode()
Value * simplifyPHINode (PHINode * PN, ArrayRef< Value * > IncomingValues, const SimplifyQuery & Q) static
See if we can fold the given phi. If not, returns null.
Definition at line 5468 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DT, llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::Value::getType(), llvm::isa(), llvm::isGuaranteedNotToBePoison(), llvm::SimplifyQuery::isUndefValue(), and valueDominatesPHI().
Referenced by simplifyInstructionWithOperands().
simplifyRelativeLoad()
Value * simplifyRelativeLoad (Constant * Ptr, Constant * Offset, const DataLayout & DL) static
Definition at line 6336 of file InstructionSimplify.cpp.
References llvm::ConstantFoldLoadFromConstPtr(), DL, llvm::dyn_cast(), llvm::Value::getContext(), llvm::Type::getInt32Ty(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Int32Ty, llvm::IsConstantOffsetFromGlobal(), llvm::Offset, llvm::APInt::sextOrTrunc(), and llvm::APInt::srem().
Referenced by llvm::simplifyBinaryIntrinsic().
simplifyRem()
Value * simplifyRem (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
These are simplifications common to SRem and URem.
Definition at line 1175 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, foldOrCommuteConstant(), llvm::Constant::getNullValue(), llvm::SimplifyQuery::IIQ, llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_CheckedInt(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, simplifyDivRem(), and llvm::InstrInfoQuery::UseInstrInfo.
Referenced by simplifySRemInst(), and simplifyURemInst().
simplifyRightShift()
Value * simplifyRightShift (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, bool IsExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an LShr or AShr, see if we can fold the result.
If not, this returns null.
Definition at line 1372 of file InstructionSimplify.cpp.
References llvm::computeKnownBits(), llvm::Constant::getNullValue(), llvm::SimplifyQuery::isUndefValue(), llvm::KnownBits::One, Op0, and simplifyShift().
Referenced by simplifyAShrInst(), and simplifyLShrInst().
simplifySDivInst()
Value * simplifySDivInst (Value * Op0, Value * Op1, bool IsExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an SDiv, see if we can fold the result.
If not, this returns null.
Definition at line 1212 of file InstructionSimplify.cpp.
References llvm::Constant::getAllOnesValue(), llvm::isKnownNegation(), Op0, and simplifyDiv().
simplifySelectBitTest()
Value * simplifySelectBitTest (Value * TrueVal, Value * FalseVal, Value * X, const APInt * Y, bool TrueWhenUnset) static
Try to simplify a select instruction when its condition operand is an integer comparison where one operand of the compare is a constant.
Definition at line 4564 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), X, and Y.
Referenced by simplifySelectWithBitTest(), and simplifySelectWithICmpCond().
simplifySelectInst()
Value * simplifySelectInst (Value * Cond, Value * TrueVal, Value * FalseVal, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a SelectInst, see if we can fold the result.
If not, this returns null.
Definition at line 4966 of file InstructionSimplify.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), Cond, llvm::ConstantFoldSelectInstruction(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::ConstantVector::get(), llvm::PoisonValue::get(), llvm::Constant::getAggregateElement(), llvm::ConstantInt::getFalse(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::impliesPoison(), llvm::isa(), llvm::isGuaranteedNotToBePoison(), llvm::isImpliedByDomCondition(), isSelectWithIdenticalPHI(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_c_LogicalAnd(), llvm::PatternMatch::m_c_LogicalOr(), llvm::PatternMatch::m_Constant(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::MIPatternMatch::m_ZeroInt(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), simplifySelectWithBitTest(), simplifySelectWithFCmp(), simplifySelectWithICmpCond(), llvm::SmallVectorTemplateCommon< T, typename >::size(), X, and Y.
Referenced by llvm::InstSimplifyFolder::FoldSelect().
simplifySelectWithBitTest()
Value * simplifySelectWithBitTest (Value * CondVal, Value * TrueVal, Value * FalseVal) static
An alternative way to test if a bit is set or not.
uses e.g. sgt/slt or trunc instead of eq/ne.
Definition at line 4679 of file InstructionSimplify.cpp.
References llvm::decomposeBitTest(), llvm::CmpInst::ICMP_EQ, and simplifySelectBitTest().
Referenced by simplifySelectInst().
simplifySelectWithEquivalence()
Value * simplifySelectWithEquivalence (ArrayRef< std::pair< Value *, Value * > > Replacements, Value * TrueVal, Value * FalseVal, const SimplifyQuery & Q, unsigned MaxRecurse) static
Try to simplify a select instruction when its condition operand is an integer equality or floating-point equivalence comparison.
Definition at line 4690 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::getWithoutUndef(), and simplifyWithOpsReplaced().
Referenced by simplifySelectWithFCmp(), and simplifySelectWithICmpCond().
simplifySelectWithFCmp()
Value * simplifySelectWithFCmp (Value * Cond, Value * T, Value * F, const SimplifyQuery & Q, unsigned MaxRecurse) static
Try to simplify a select instruction when its condition operand is a floating-point comparison.
Definition at line 4833 of file InstructionSimplify.cpp.
References llvm::cast(), Cond, llvm::SimplifyQuery::CxtI, F, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::getInversePredicate(), llvm::Instruction::hasNoSignedZeros(), I, llvm::isa(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), simplifySelectWithEquivalence(), std::swap(), and T.
Referenced by simplifySelectInst().
simplifySelectWithICmpCond()
Value * simplifySelectWithICmpCond (Value * CondVal, Value * TrueVal, Value * FalseVal, const SimplifyQuery & Q, unsigned MaxRecurse) static
Try to simplify a select instruction when its condition operand is an integer comparison.
Definition at line 4715 of file InstructionSimplify.cpp.
References llvm::canReplacePointersIfEqual(), llvm::cast(), llvm::SimplifyQuery::DL, llvm::SelectPatternResult::Flavor, llvm::getInverseMinMaxFlavor(), llvm::getMinMaxLimit(), llvm::getMinMaxPred(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::Type::isIntOrIntVectorTy(), llvm::SelectPatternResult::isMinOrMax(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_FShl(), llvm::PatternMatch::m_FShr(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Intrinsic(), llvm::MIPatternMatch::m_Neg(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::matchDecomposedSelectPattern(), simplifyCmpSelOfMaxMin(), simplifySelectBitTest(), simplifySelectWithEquivalence(), std::swap(), X, and Y.
Referenced by simplifySelectInst().
simplifyShift()
Value * simplifyShift (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, bool IsNSW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Shl, LShr or AShr, see if we can fold the result.
If not, this returns null.
Definition at line 1302 of file InstructionSimplify.cpp.
References assert(), llvm::CallingConv::C, llvm::computeKnownBits(), llvm::KnownBits::countMinTrailingZeros(), foldOrCommuteConstant(), llvm::PoisonValue::get(), llvm::KnownBits::getBitWidth(), llvm::KnownBits::getMinValue(), llvm::Constant::getNullValue(), llvm::KnownBits::hasConflict(), llvm::isa(), isPoisonShift(), llvm::APInt::isSignBitSet(), llvm::Log2_32_Ceil(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::KnownBits::One, Op0, llvm::APInt::setSignBit(), llvm::KnownBits::shl(), threadBinOpOverPHI(), threadBinOpOverSelect(), llvm::APInt::uge(), X, and llvm::KnownBits::Zero.
Referenced by simplifyRightShift(), and simplifyShlInst().
simplifyShlInst()
Value * simplifyShlInst (Value * Op0, Value * Op1, bool IsNSW, bool IsNUW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an Shl, see if we can fold the result.
If not, this returns null.
Definition at line 1401 of file InstructionSimplify.cpp.
References llvm::Constant::getNullValue(), llvm::SimplifyQuery::IIQ, llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_Negative(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, simplifyShift(), llvm::InstrInfoQuery::UseInstrInfo, and X.
simplifyShuffleVectorInst()
Value * simplifyShuffleVectorInst (Value * Op0, Value * Op1, ArrayRef< int > Mask, Type * RetTy, const SimplifyQuery & Q, unsigned MaxRecurse) static
Definition at line 5609 of file InstructionSimplify.cpp.
References llvm::all_equal(), llvm::all_of(), assert(), llvm::SmallVectorImpl< T >::assign(), llvm::CallingConv::C, llvm::cast(), llvm::ShuffleVectorInst::commuteShuffleMask(), llvm::dyn_cast(), foldIdentityShuffles(), llvm::ConstantVector::get(), llvm::PoisonValue::get(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::ConstantExpr::getShuffleVector(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::is_contained(), llvm::isa(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_InsertElt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, llvm::PoisonMaskElem, and std::swap().
Referenced by llvm::InstSimplifyFolder::FoldShuffleVector().
simplifySRemInst()
Value * simplifySRemInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for an SRem, see if we can fold the result.
If not, this returns null.
Definition at line 1240 of file InstructionSimplify.cpp.
References llvm::Constant::getNullValue(), llvm::isKnownNegation(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Op0, simplifyRem(), and X.
simplifySubInst()
Value * simplifySubInst (Value * Op0, Value * Op1, bool IsNSW, bool IsNUW, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a Sub, see if we can fold the result.
If not, this returns null.
Definition at line 746 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::computeKnownBits(), computePointerDifference(), llvm::ConstantFoldIntegerCast(), llvm::SimplifyQuery::DL, foldOrCommuteConstant(), llvm::PoisonValue::get(), llvm::UndefValue::get(), llvm::Constant::getNullValue(), llvm::isa(), llvm::APInt::isMaxSignedValue(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_LowBitMask(), llvm::PatternMatch::m_PtrToIntOrAddr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), Op0, llvm::simplifyBinOp(), simplifyByDomEq(), llvm::simplifyCastInst(), llvm::simplifyXorInst(), X, Y, and llvm::KnownBits::Zero.
simplifySVEIntReduction()
Value * simplifySVEIntReduction (Intrinsic::ID IID, Type * ReturnType, Value * Op0, Value * Op1) static
Definition at line 6701 of file InstructionSimplify.cpp.
References assert(), llvm::dyn_cast(), llvm::APInt::getMaxValue(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::getSplatValue(), llvm::Constant::isAllOnesValue(), llvm::Constant::isMaxSignedValue(), llvm::Constant::isMinSignedValue(), llvm::Constant::isNullValue(), and Op0.
Referenced by llvm::simplifyBinaryIntrinsic().
simplifyUDivInst()
Value * simplifyUDivInst (Value * Op0, Value * Op1, bool IsExact, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a UDiv, see if we can fold the result.
If not, this returns null.
Definition at line 1228 of file InstructionSimplify.cpp.
References Op0, and simplifyDiv().
simplifyUnaryIntrinsic()
Value * simplifyUnaryIntrinsic (Function * F, Value * Op0, const SimplifyQuery & Q, const CallBase * Call) static
Definition at line 6438 of file InstructionSimplify.cpp.
References llvm::SimplifyQuery::AC, llvm::BitWidth, llvm::computeKnownFPSignBit(), llvm::SimplifyQuery::CxtI, llvm::SimplifyQuery::DL, llvm::SimplifyQuery::DT, llvm::dyn_cast(), F, llvm::APInt::getHighBitsSet(), II, isIdempotent(), llvm::isKnownToBeAPowerOfTwo(), llvm::isSplatValue(), llvm::PatternMatch::m_BitReverse(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_SIToFP(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_UIToFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_VecReverse(), llvm::MaskedValueIsZero(), llvm::PatternMatch::match(), Op0, removesFPFraction(), and X.
Referenced by simplifyIntrinsic().
simplifyUnOp()
Value * simplifyUnOp (unsigned Opcode, Value * Op, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given the operand for a UnaryOperator, see if we can fold the result.
If not, this returns null.
Definition at line 6172 of file InstructionSimplify.cpp.
References llvm_unreachable, and llvm::simplifyFNegInst().
Referenced by llvm::InstSimplifyFolder::FoldUnOpFMF().
simplifyUnsignedRangeCheck()
Value * simplifyUnsignedRangeCheck (ICmpInst * ZeroICmp, ICmpInst * UnsignedICmp, bool IsAnd, const SimplifyQuery & Q) static
Commuted variants are assumed to be handled by calling this function again with the parameters swapped.
Definition at line 1512 of file InstructionSimplify.cpp.
References A(), B(), getFalse(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::isKnownNonZero(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_c_ICmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), X, and Y.
Referenced by simplifyAndOfICmps(), and simplifyOrOfICmps().
simplifyURemInst()
Value * simplifyURemInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a URem, see if we can fold the result.
If not, this returns null.
Definition at line 1261 of file InstructionSimplify.cpp.
References Op0, and simplifyRem().
simplifyWithOpReplaced()
Value * simplifyWithOpReplaced (Value * V, Value * Op, Value * RepOp, const SimplifyQuery & Q, bool AllowRefinement, SmallVectorImpl< Instruction * > * DropFlags, unsigned MaxRecurse) static
Definition at line 4540 of file InstructionSimplify.cpp.
References simplifyWithOpsReplaced().
simplifyWithOpsReplaced()
Value * simplifyWithOpsReplaced (Value * V, ArrayRef< std::pair< Value *, Value * > > Ops, const SimplifyQuery & Q, bool AllowRefinement, SmallVectorImpl< Instruction * > * DropFlags, unsigned MaxRecurse) static
Definition at line 4339 of file InstructionSimplify.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::any_of(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::canCreatePoison(), llvm::SimplifyQuery::CanUseUndef, llvm::cast(), llvm::ConstantFoldInstOperands(), llvm::SimplifyQuery::DL, llvm::dyn_cast(), llvm::ConstantExpr::getBinOpAbsorber(), llvm::ConstantExpr::getBinOpIdentity(), llvm::Constant::getNullValue(), I, II, llvm::impliesPoison(), llvm::isa(), llvm::isNotCrossLaneOperation(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::simplifyInstructionWithOperands(), simplifyWithOpsReplaced(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::SimplifyQuery::TLI.
Referenced by simplifySelectWithEquivalence(), simplifyWithOpReplaced(), and simplifyWithOpsReplaced().
simplifyXorInst()
Value * simplifyXorInst (Value * Op0, Value * Op1, const SimplifyQuery & Q, unsigned MaxRecurse) static
Given operands for a Xor, see if we can fold the result.
If not, this returns null.
Definition at line 2531 of file InstructionSimplify.cpp.
References A(), B(), llvm::CallingConv::C, foldOrCommuteConstant(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::isa(), llvm::SimplifyQuery::isUndefValue(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_CombineAnd(), llvm::PatternMatch::m_LowBitMask(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_NUWSub(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), Op0, simplifyAssociativeBinOp(), simplifyByDomEq(), simplifyLogicOfAddSub(), X, and Y.
STATISTIC() [1/2]
STATISTIC (NumExpand , "Number of expansions")
STATISTIC() [2/2]
STATISTIC (NumReassoc , "Number of reassociations")
References I, LHS, and RHS.
stripAndComputeConstantOffsets()
APInt stripAndComputeConstantOffsets (const DataLayout & DL, Value *& V) static
Compute the base pointer and cumulative constant offsets for V.
This strips all constant offsets off of V, leaving it the base pointer, and accumulates the total constant offset applied in the returned constant. It returns zero if there are no constant offsets applied.
This is very similar to stripAndAccumulateConstantOffsets(), except it normalizes the offset bitwidth to the stripped pointer type, not the original pointer type.
Definition at line 675 of file InstructionSimplify.cpp.
References assert(), DL, llvm::APInt::getZero(), and llvm::Offset.
Referenced by computePointerDifference().
threadBinOpOverPHI()
Value * threadBinOpOverPHI (Instruction::BinaryOps Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a binary operation with an operand that is a PHI instruction, try to simplify the binop by seeing whether evaluating it on the incoming phi values yields the same result for every value.
If so returns the common value, otherwise returns null.
Definition at line 478 of file InstructionSimplify.cpp.
References assert(), llvm::cast(), llvm::SimplifyQuery::DT, llvm::PHINode::getIncomingBlock(), llvm::BasicBlock::getTerminator(), llvm::SimplifyQuery::getWithInstruction(), llvm::PHINode::incoming_values(), llvm::isa(), LHS, RHS, llvm::simplifyBinOp(), and valueDominatesPHI().
Referenced by simplifyAndInst(), simplifyDivRem(), simplifyMulInst(), simplifyOrInst(), and simplifyShift().
threadBinOpOverSelect()
Value * threadBinOpOverSelect (Instruction::BinaryOps Opcode, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a binary operation with a select instruction as an operand, try to simplify the binop by seeing whether evaluating it on both branches of the select results in the same value.
Returns the common value if so, otherwise returns null.
Definition at line 354 of file InstructionSimplify.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::isa(), llvm::SimplifyQuery::isUndefValue(), LHS, RHS, and llvm::simplifyBinOp().
Referenced by simplifyAndInst(), simplifyDivRem(), simplifyMulInst(), simplifyOrInst(), and simplifyShift().
threadCmpOverPHI()
Value * threadCmpOverPHI (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a comparison with a PHI instruction, try to simplify the comparison by seeing whether comparing with all of the incoming phi values yields the same result every time.
If so returns the common result, otherwise returns null.
Definition at line 525 of file InstructionSimplify.cpp.
References assert(), llvm::cast(), llvm::SimplifyQuery::DT, llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::CmpInst::getSwappedPredicate(), llvm::BasicBlock::getTerminator(), llvm::SimplifyQuery::getWithInstruction(), llvm::isa(), LHS, RHS, llvm::simplifyCmpInst(), std::swap(), and valueDominatesPHI().
Referenced by simplifyFCmpInst(), and simplifyICmpInst().
threadCmpOverSelect()
Value * threadCmpOverSelect (CmpPredicate Pred, Value * LHS, Value * RHS, const SimplifyQuery & Q, unsigned MaxRecurse) static
In the case of a comparison with a select instruction, try to simplify the comparison by seeing whether both branches of the select result in the same value.
Returns the common value if so, otherwise returns null. For example, if we have: tmp = select i1 cmp, i32 1, i32 2 cmp1 = icmp sle i32 tmp, 3 We can simplify cmp1 to true, because both branches of select are less than 3. We compose new comparison by substituting tmp with both branches of select and see if it can be simplified.
Definition at line 433 of file InstructionSimplify.cpp.
References assert(), llvm::cast(), Cond, llvm::CmpInst::getSwappedPredicate(), handleOtherCmpSelSimplifications(), llvm::isa(), LHS, RHS, simplifyCmpSelFalseCase(), simplifyCmpSelTrueCase(), and std::swap().
Referenced by simplifyFCmpInst(), and simplifyICmpInst().
tryConstantFoldCall()
Value * tryConstantFoldCall (CallBase * Call, Value * Callee, ArrayRef< Value * > Args, const SimplifyQuery & Q) static
Definition at line 7345 of file InstructionSimplify.cpp.
References llvm::CallingConv::C, llvm::canConstantFoldCallTo(), llvm::ConstantFoldCall(), llvm::dyn_cast(), F, llvm::isa(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SimplifyQuery::TLI.
Referenced by llvm::simplifyCall(), and llvm::simplifyConstrainedFPCall().
trySimplifyICmpWithAdds()
bool trySimplifyICmpWithAdds (CmpPredicate Pred, Value * LHS, Value * RHS, const InstrInfoQuery & IIQ) static
Definition at line 3274 of file InstructionSimplify.cpp.
References llvm::APInt::isNonNegative(), llvm::APInt::isNonPositive(), llvm::CmpInst::isSigned(), LHS, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_NSWAdd(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), RHS, llvm::APInt::sle(), std::swap(), llvm::InstrInfoQuery::UseInstrInfo, and X.
Referenced by simplifyICmpWithBinOp().
valueDominatesPHI()
bool valueDominatesPHI (Value * V, PHINode * P, const DominatorTree * DT) static
Does the given value dominate the specified phi node?
Definition at line 176 of file InstructionSimplify.cpp.
References llvm::DominatorTree::dominates(), llvm::dyn_cast(), I, llvm::isa(), and P.
Referenced by simplifyPHINode(), threadBinOpOverPHI(), and threadCmpOverPHI().