LLVM: lib/ExecutionEngine/Orc/IRPartitionLayer.cpp File Reference
IRPartitionLayer.cpp File Reference
#include "llvm/ExecutionEngine/Orc/IRPartitionLayer.h"
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Classes
class llvm::orc::PartitioningIRMaterializationUnit
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::orc
Functions
static ThreadSafeModule extractSubModule (ThreadSafeModule &TSM, StringRef Suffix, GVPredicate ShouldExtract)
Function Documentation
extractSubModule()
ThreadSafeModule extractSubModule (ThreadSafeModule & TSM, StringRef Suffix, GVPredicate ShouldExtract) static
Definition at line 16 of file IRPartitionLayer.cpp.
References A(), assert(), llvm::cast(), llvm::orc::cloneFunctionDecl(), llvm::orc::cloneGlobalVariableDecl(), llvm::orc::cloneToNewContext(), llvm::GlobalValue::ExternalLinkage, F, G, llvm::Value::hasName(), llvm::isa(), and llvm_unreachable.