LLVM: lib/ExecutionEngine/Orc/TargetProcess/JITLoaderPerf.cpp File Reference
JITLoaderPerf.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderPerf.h"
#include "llvm/ExecutionEngine/Orc/Shared/PerfSharedStructs.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Threading.h"
#include <mutex>
#include <optional>
Functions
static Error badOS ()
static Error badOSBatch (PerfJITRecordBatch &Batch)
llvm::orc::shared::CWrapperFunctionBuffer llvm_orc_registerJITLoaderPerfImpl (const char *ArgData, size_t ArgSize)
llvm::orc::shared::CWrapperFunctionBuffer llvm_orc_registerJITLoaderPerfStart (const char *ArgData, size_t ArgSize)
llvm::orc::shared::CWrapperFunctionBuffer llvm_orc_registerJITLoaderPerfEnd (const char *ArgData, size_t ArgSize)
Function Documentation
badOS()
Error badOS () static
Definition at line 427 of file JITLoaderPerf.cpp.
References llvm::inconvertibleErrorCode(), and llvm::make_error().
Referenced by badOSBatch(), llvm_orc_registerJITLoaderPerfEnd(), and llvm_orc_registerJITLoaderPerfStart().
badOSBatch()
Error badOSBatch (PerfJITRecordBatch & Batch) static
Definition at line 434 of file JITLoaderPerf.cpp.
References badOS().
Referenced by llvm_orc_registerJITLoaderPerfImpl().
llvm_orc_registerJITLoaderPerfEnd()
llvm::orc::shared::CWrapperFunctionBuffer llvm_orc_registerJITLoaderPerfEnd (const char * ArgData, size_t ArgSize)
Definition at line 451 of file JITLoaderPerf.cpp.
References badOS().
llvm_orc_registerJITLoaderPerfImpl()
llvm::orc::shared::CWrapperFunctionBuffer llvm_orc_registerJITLoaderPerfImpl (const char * ArgData, size_t ArgSize)
Definition at line 437 of file JITLoaderPerf.cpp.
References badOSBatch().
llvm_orc_registerJITLoaderPerfStart()
llvm::orc::shared::CWrapperFunctionBuffer llvm_orc_registerJITLoaderPerfStart (const char * ArgData, size_t ArgSize)
Definition at line 445 of file JITLoaderPerf.cpp.
References badOS().