LLVM: lib/Support/KnownFPClass.cpp File Reference
KnownFPClass.cpp File Reference
#include "llvm/Support/KnownFPClass.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static bool inputDenormalIsIEEE (DenormalMode Mode)
Return true if it's possible to assume IEEE treatment of input denormals in F for Val.
static bool inputDenormalIsIEEEOrPosZero (DenormalMode Mode)
Function Documentation
inputDenormalIsIEEE()
bool inputDenormalIsIEEE (DenormalMode Mode) static
Return true if it's possible to assume IEEE treatment of input denormals in F for Val.
Definition at line 25 of file KnownFPClass.cpp.
References llvm::DenormalMode::IEEE, and Mode.
Referenced by fpclassTestIsFCmp0(), and llvm::KnownFPClass::isKnownNeverLogicalZero().
inputDenormalIsIEEEOrPosZero()
bool inputDenormalIsIEEEOrPosZero (DenormalMode Mode) static
Definition at line 29 of file KnownFPClass.cpp.
References llvm::DenormalMode::IEEE, Mode, and llvm::DenormalMode::PositiveZero.
Referenced by llvm::KnownFPClass::isKnownNeverLogicalNegZero().