LLVM: lib/Target/Lanai/LanaiTargetMachine.cpp File Reference
LanaiTargetMachine.cpp File Reference
#include "LanaiTargetMachine.h"
#include "Lanai.h"
#include "LanaiMachineFunctionInfo.h"
#include "LanaiTargetObjectFile.h"
#include "LanaiTargetTransformInfo.h"
#include "TargetInfo/LanaiTargetInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Target/TargetOptions.h"
#include <optional>
Functions
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiTarget ()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
Function Documentation
getEffectiveRelocModel()
Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 40 of file LanaiTargetMachine.cpp.
References llvm::Reloc::PIC_.
LLVMInitializeLanaiTarget()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiTarget ()
Definition at line 30 of file LanaiTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheLanaiTarget(), llvm::initializeLanaiAsmPrinterPass(), llvm::initializeLanaiDAGToDAGISelLegacyPass(), llvm::initializeLanaiMemAluCombinerPass(), LLVM_ABI, and LLVM_EXTERNAL_VISIBILITY.