LLVM: lib/CodeGen/LiveDebugValues/LiveDebugValues.cpp File Reference
LiveDebugValues.cpp File Reference
The LiveDebugValues pass extends the range of variable locations (specified by DBG_VALUE instructions) from single blocks to successors and any other code locations where the variable location is valid.
#include "LiveDebugValues.h"
#include "llvm/CodeGen/LiveDebugValuesPass.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/PassRegistry.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/TargetParser/Triple.h"
Macros
#define DEBUG_TYPE "livedebugvalues"
Functions
INITIALIZE_PASS (LiveDebugValuesLegacy, DEBUG_TYPE, "Live DEBUG_VALUE analysis", false, false) LiveDebugValuesLegacy
Default construct and initialize the pass.
Variables
static cl::opt< bool > ForceInstrRefLDV ("force-instr-ref-livedebugvalues", cl::Hidden, cl::desc("Use instruction-ref based LiveDebugValues with " "normal DBG_VALUE inputs"), cl::init(false))
static cl::opt< cl::boolOrDefault > ValueTrackingVariableLocations ("experimental-debug-variable-locations", cl::desc("Use experimental new value-tracking variable locations"))
static cl::opt< unsigned > InputBBLimit ("livedebugvalues-input-bb-limit", cl::desc("Maximum input basic blocks before DBG_VALUE limit applies"), cl::init(10000), cl::Hidden)
static cl::opt< unsigned > InputDbgValueLimit ("livedebugvalues-input-dbg-value-limit", cl::desc("Maximum input DBG_VALUE insts supported by debug range extension"), cl::init(50000), cl::Hidden)
Detailed Description
The LiveDebugValues pass extends the range of variable locations (specified by DBG_VALUE instructions) from single blocks to successors and any other code locations where the variable location is valid.
There are currently two implementations: the "VarLoc" implementation explicitly tracks the location of a variable, while the "InstrRef" implementation tracks the values defined by instructions through locations.
This file implements neither; it merely registers the pass, allows the user to pick which implementation will be used to propagate variable locations.
Definition in file LiveDebugValues.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "livedebugvalues"
Definition at line 37 of file LiveDebugValues.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LiveDebugValuesLegacy , DEBUG_TYPE , "Live DEBUG_VALUE analysis" , false , false)
Default construct and initialize the pass.
Definition at line 100 of file LiveDebugValues.cpp.
References DEBUG_TYPE, llvm::PassRegistry::getPassRegistry(), and llvm::initializeLiveDebugValuesLegacyPass().
Variable Documentation
ForceInstrRefLDV
cl::opt< bool > ForceInstrRefLDV("force-instr-ref-livedebugvalues", cl::Hidden, cl::desc("Use instruction-ref based LiveDebugValues with " "normal DBG_VALUE inputs"), cl::init(false)) ("force-instr-ref-livedebugvalues" , cl::Hidden , cl::desc("Use instruction-ref based LiveDebugValues with " "normal DBG_VALUE inputs") , cl::init(false)) static
InputBBLimit
cl::opt< unsigned > InputBBLimit("livedebugvalues-input-bb-limit", cl::desc("Maximum input basic blocks before DBG_VALUE limit applies"), cl::init(10000), cl::Hidden) ("livedebugvalues-input-bb-limit" , cl::desc("Maximum input basic blocks before DBG_VALUE limit applies") , cl::init(10000) , cl::Hidden) static
Referenced by llvm::SharedLiveDebugValues::LDVImpl::ExtendRanges().
InputDbgValueLimit
cl::opt< unsigned > InputDbgValueLimit("livedebugvalues-input-dbg-value-limit", cl::desc("Maximum input DBG_VALUE insts supported by debug range extension"), cl::init(50000), cl::Hidden) ("livedebugvalues-input-dbg-value-limit" , cl::desc("Maximum input DBG_VALUE insts supported by debug range extension") , cl::init(50000) , cl::Hidden) static
ValueTrackingVariableLocations
cl::opt< cl::boolOrDefault > ValueTrackingVariableLocations("experimental-debug-variable-locations", cl::desc("Use experimental new value-tracking variable locations")) ("experimental-debug-variable-locations" , cl::desc("Use experimental new value-tracking variable locations")) static
Referenced by llvm::debuginfoShouldUseDebugInstrRef().