LLVM: lib/Analysis/Loads.cpp File Reference
Loads.cpp File Reference
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumeBundleQueries.h"
#include "llvm/Analysis/LoopAccessAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
Functions
static bool isAligned (const Value *Base, Align Alignment, const DataLayout &DL)
static bool isDereferenceableAndAlignedPointerViaAssumption (const Value *Ptr, Align Alignment, function_ref< bool(const RetainedKnowledge &RK)> CheckSize, const DataLayout &DL, const Instruction *CtxI, AssumptionCache *AC, const DominatorTree *DT)
static bool isDereferenceableAndAlignedPointer (const Value *V, Align Alignment, const APInt &Size, const DataLayout &DL, const Instruction *CtxI, AssumptionCache *AC, const DominatorTree *DT, const TargetLibraryInfo *TLI, SmallPtrSetImpl< const Value * > &Visited, unsigned MaxDepth)
Test if V is always a pointer to allocated and suitably aligned memory for a simple load or store.
static bool AreEquivalentAddressValues (const Value *A, const Value *B)
Test if A and B will obviously have the same value.
static bool suppressSpeculativeLoadForSanitizers (const Instruction &CtxI)
static bool areNonOverlapSameBaseLoadAndStore (const Value *LoadPtr, Type *LoadTy, const Value *StorePtr, Type *StoreTy, const DataLayout &DL)
static Value * getAvailableLoadStore (Instruction *Inst, const Value *Ptr, Type *AccessTy, bool AtLeastAtomic, const DataLayout &DL, bool *IsLoadCSE)
static bool isPointerUseReplacable (const Use &U, bool HasNonAddressBits)
static bool isPointerAlwaysReplaceable (const Value *From, const Value *To, const DataLayout &DL)
Function Documentation
AreEquivalentAddressValues()
bool AreEquivalentAddressValues (const Value * A, const Value * B) static
Test if A and B will obviously have the same value.
This includes recognizing that t0 and t1 will have the same value in code like this:
%t0 = getelementptr \@a, 0, 3
store i32 0, i32* %t0
%t1 = getelementptr \@a, 0, 3
%t2 = load i32* %t1
Definition at line 270 of file Loads.cpp.
References A(), B(), llvm::cast(), llvm::dyn_cast(), and llvm::isa().
Referenced by getAvailableLoadStore(), and llvm::isSafeToLoadUnconditionally().
areNonOverlapSameBaseLoadAndStore()
bool areNonOverlapSameBaseLoadAndStore (const Value * LoadPtr, Type * LoadTy, const Value * StorePtr, Type * StoreTy, const DataLayout & DL) static
Definition at line 559 of file Loads.cpp.
References DL, llvm::Value::getType(), llvm::ConstantRange::intersectWith(), llvm::ConstantRange::isEmptySet(), llvm::LocationSize::precise(), and llvm::Value::stripAndAccumulateConstantOffsets().
Referenced by llvm::findAvailablePtrLoadStore().
getAvailableLoadStore()
Value * getAvailableLoadStore (Instruction * Inst, const Value * Ptr, Type * AccessTy, bool AtLeastAtomic, const DataLayout & DL, bool * IsLoadCSE) static
Definition at line 581 of file Loads.cpp.
References AreEquivalentAddressValues(), llvm::CallingConv::C, llvm::ConstantFoldLoadFromConst(), DL, llvm::dyn_cast(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::GetPointerBaseWithConstantOffset(), llvm::APInt::getSplat(), llvm::Value::getType(), llvm::CastInst::isBitOrNoopPointerCastable(), llvm::details::FixedOrScalableQuantity< TypeSize, uint64_t >::isKnownLE(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::Splat, and llvm::Value::stripPointerCasts().
Referenced by llvm::FindAvailableLoadedValue(), and llvm::findAvailablePtrLoadStore().
isAligned()
bool isAligned (const Value * Base, Align Alignment, const DataLayout & DL) static
Definition at line 30 of file Loads.cpp.
References llvm::sampleprof::Base, and DL.
isDereferenceableAndAlignedPointer()
bool isDereferenceableAndAlignedPointer (const Value * V, Align Alignment, const APInt & Size, const DataLayout & DL, const Instruction * CtxI, AssumptionCache * AC, const DominatorTree * DT, const TargetLibraryInfo * TLI, SmallPtrSetImpl< const Value * > & Visited, unsigned MaxDepth) static
Test if V is always a pointer to allocated and suitably aligned memory for a simple load or store.
TODO refactor this function to be able to search independently for Dereferencability and Alignment requirements.
Definition at line 71 of file Loads.cpp.
References llvm::RetainedKnowledge::ArgValue, assert(), llvm::sampleprof::Base, DL, llvm::dyn_cast(), GEP, llvm::getArgumentAliasingToReturnedPointer(), llvm::APInt::getBoolValue(), llvm::getObjectSize(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::isAligned(), llvm::isDereferenceableAndAlignedPointer(), isDereferenceableAndAlignedPointerViaAssumption(), llvm::isKnownNonZero(), llvm::isValidAssumeForContext(), llvm::ObjectSizeOpts::NullIsUnknownSize, llvm::Offset, llvm::ObjectSizeOpts::RoundToAlign, Size, llvm::APInt::uge(), and llvm::Align::value().
isDereferenceableAndAlignedPointerViaAssumption()
bool isDereferenceableAndAlignedPointerViaAssumption (const Value * Ptr, Align Alignment, function_ref< bool(const RetainedKnowledge &RK)> CheckSize, const DataLayout & DL, const Instruction * CtxI, AssumptionCache * AC, const DominatorTree * DT) static
Look through assumes to see if both dereferencability and alignment can be proven by an assume if needed.
Definition at line 35 of file Loads.cpp.
References llvm::RetainedKnowledge::ArgValue, llvm::RetainedKnowledge::AttrKind, llvm::Value::canBeFreed(), DL, llvm::getKnowledgeForValue(), llvm::Value::getPointerAlignment(), llvm::isValidAssumeForContext(), llvm::Align::value(), and llvm::willNotFreeBetween().
Referenced by llvm::isDereferenceableAndAlignedInLoop(), and isDereferenceableAndAlignedPointer().
isPointerAlwaysReplaceable()
bool isPointerAlwaysReplaceable (const Value * From, const Value * To, const DataLayout & DL) static
Definition at line 832 of file Loads.cpp.
References DL, llvm::Value::getContext(), llvm::Type::getInt8Ty(), llvm::Value::getType(), llvm::getUnderlyingObjectAggressive(), llvm::isa(), llvm::isDereferenceablePointer(), and llvm::Type::isPointerTy().
Referenced by llvm::canReplacePointersIfEqual(), and llvm::canReplacePointersInUseIfEqual().
isPointerUseReplacable()
bool isPointerUseReplacable (const Use & U, bool HasNonAddressBits) static
Definition at line 806 of file Loads.cpp.
References llvm::SmallVectorImpl< T >::insert(), llvm::isa(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by llvm::canReplacePointersInUseIfEqual().
suppressSpeculativeLoadForSanitizers()
bool suppressSpeculativeLoadForSanitizers (const Instruction & CtxI) static
Definition at line 411 of file Loads.cpp.
References F, and llvm::Instruction::getFunction().
Referenced by llvm::isSafeToLoadUnconditionally(), and llvm::mustSuppressSpeculation().