LLVM: lib/Target/LoongArch/AsmParser/LoongArchAsmParser.cpp File Reference
LoongArchAsmParser.cpp File Reference
#include "MCTargetDesc/LoongArchBaseInfo.h"
#include "MCTargetDesc/LoongArchInstPrinter.h"
#include "MCTargetDesc/LoongArchMCAsmInfo.h"
#include "MCTargetDesc/LoongArchMCTargetDesc.h"
#include "MCTargetDesc/LoongArchMatInt.h"
#include "MCTargetDesc/LoongArchTargetStreamer.h"
#include "TargetInfo/LoongArchTargetInfo.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "LoongArchGenAsmMatcher.inc"
Macros
#define DEBUG_TYPE "loongarch-asm-parser"
#define GET_ASSEMBLER_HEADER
#define GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_REGISTER_MATCHER
#define GET_SUBTARGET_FEATURE_NAME
#define GET_MATCHER_IMPLEMENTATION
#define GET_MNEMONIC_SPELL_CHECKER
Functions
static MCRegister convertFPR32ToFPR64 (MCRegister Reg)
static bool matchRegisterNameHelper (MCRegister &RegNo, StringRef Name)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchAsmParser ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-asm-parser"
Definition at line 33 of file LoongArchAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 86 of file LoongArchAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 653 of file LoongArchAsmParser.cpp.
GET_MNEMONIC_SPELL_CHECKER
#define GET_MNEMONIC_SPELL_CHECKER
Definition at line 654 of file LoongArchAsmParser.cpp.
GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_OPERAND_DIAGNOSTIC_TYPES
Definition at line 187 of file LoongArchAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 651 of file LoongArchAsmParser.cpp.
GET_SUBTARGET_FEATURE_NAME
#define GET_SUBTARGET_FEATURE_NAME
Definition at line 652 of file LoongArchAsmParser.cpp.
Function Documentation
convertFPR32ToFPR64()
MCRegister convertFPR32ToFPR64 (MCRegister Reg) static
Definition at line 657 of file LoongArchAsmParser.cpp.
References assert(), and Reg.
LLVMInitializeLoongArchAsmParser()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchAsmParser ()
Definition at line 2090 of file LoongArchAsmParser.cpp.
References llvm::getTheLoongArch32Target(), llvm::getTheLoongArch64Target(), X, and Y.
matchRegisterNameHelper()
bool matchRegisterNameHelper (MCRegister & RegNo, StringRef Name) static
Definition at line 665 of file LoongArchAsmParser.cpp.
References assert(), MatchRegisterAltName(), and MatchRegisterName().