LLVM: lib/Target/LoongArch/LoongArchTargetMachine.cpp File Reference
LoongArchTargetMachine.cpp File Reference
#include "LoongArchTargetMachine.h"
#include "LoongArch.h"
#include "LoongArchMachineFunctionInfo.h"
#include "LoongArchTargetTransformInfo.h"
#include "MCTargetDesc/LoongArchBaseInfo.h"
#include "TargetInfo/LoongArchTargetInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Transforms/Scalar.h"
#include <optional>
Macros
#define DEBUG_TYPE "loongarch"
Functions
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchTarget ()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveLoongArchCodeModel (const Triple &TT, std::optional< CodeModel::Model > CM)
Variables
static cl::opt< bool > EnableLoongArchDeadRegisterElimination ("loongarch-enable-dead-defs", cl::Hidden, cl::desc("Enable the pass that removes dead" " definitons and replaces stores to" " them with stores to r0"), cl::init(true))
static cl::opt< bool > EnableLoopDataPrefetch ("loongarch-enable-loop-data-prefetch", cl::Hidden, cl::desc("Enable the loop data prefetch pass"), cl::init(false))
static cl::opt< bool > EnableMergeBaseOffset ("loongarch-enable-merge-offset", cl::desc("Enable the merge base offset pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableSinkFold ("loongarch-enable-sink-fold", cl::desc("Enable sinking and folding of instruction copies"), cl::init(true), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch"
Definition at line 31 of file LoongArchTargetMachine.cpp.
Function Documentation
getEffectiveLoongArchCodeModel()
CodeModel::Model getEffectiveLoongArchCodeModel (const Triple & TT, std::optional< CodeModel::Model > CM) static
Definition at line 75 of file LoongArchTargetMachine.cpp.
References llvm::CodeModel::Large, llvm::CodeModel::Medium, llvm::report_fatal_error(), and llvm::CodeModel::Small.
Referenced by llvm::LoongArchTargetMachine::LoongArchTargetMachine().
getEffectiveRelocModel()
Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 70 of file LoongArchTargetMachine.cpp.
References llvm::Reloc::Static.
LLVMInitializeLoongArchTarget()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchTarget ()
Definition at line 34 of file LoongArchTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheLoongArch32Target(), llvm::getTheLoongArch64Target(), llvm::initializeLoongArchDAGToDAGISelLegacyPass(), llvm::initializeLoongArchDeadRegisterDefinitionsPass(), llvm::initializeLoongArchExpandAtomicPseudoPass(), llvm::initializeLoongArchExpandPseudoPass(), llvm::initializeLoongArchMergeBaseOffsetOptPass(), llvm::initializeLoongArchOptWInstrsPass(), llvm::initializeLoongArchPreRAExpandPseudoPass(), X, and Y.
Variable Documentation
EnableLoongArchDeadRegisterElimination
cl::opt< bool > EnableLoongArchDeadRegisterElimination("loongarch-enable-dead-defs", cl::Hidden, cl::desc("Enable the pass that removes dead" " definitons and replaces stores to" " them with stores to r0"), cl::init(true)) ("loongarch-enable-dead-defs" , cl::Hidden , cl::desc("Enable the pass that removes dead" " definitons and replaces stores to" " them with stores to r0") , cl::init(true)) static
EnableLoopDataPrefetch
cl::opt< bool > EnableLoopDataPrefetch("loongarch-enable-loop-data-prefetch", cl::Hidden, cl::desc("Enable the loop data prefetch pass"), cl::init(false)) ("loongarch-enable-loop-data-prefetch" , cl::Hidden , cl::desc("Enable the loop data prefetch pass") , cl::init(false)) static
EnableMergeBaseOffset
cl::opt< bool > EnableMergeBaseOffset("loongarch-enable-merge-offset", cl::desc("Enable the merge base offset pass"), cl::init(true), cl::Hidden) ("loongarch-enable-merge-offset" , cl::desc("Enable the merge base offset pass") , cl::init(true) , cl::Hidden) static
EnableSinkFold
cl::opt< bool > EnableSinkFold("loongarch-enable-sink-fold", cl::desc("Enable sinking and folding of instruction copies"), cl::init(true), cl::Hidden) ("loongarch-enable-sink-fold" , cl::desc("Enable sinking and folding of instruction copies") , cl::init(true) , cl::Hidden) static