LLVM: lib/Transforms/Scalar/LowerMatrixIntrinsics.cpp File Reference
LowerMatrixIntrinsics.cpp File Reference
#include "llvm/Transforms/Scalar/LowerMatrixIntrinsics.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/MatrixBuilder.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/MatrixUtils.h"
#include <cmath>
Macros
#define DEBUG_TYPE "lower-matrix-intrinsics"
Enumerations
enum class MatrixLayoutTy { ColumnMajor , RowMajor }
Functions
STATISTIC (FlattenedMatrices, "Number of matrix flattenings")
STATISTIC (ReshapedMatrices, "Number of matrix reshapes")
STATISTIC (SplitMatrices, "Number of matrix splits")
static DISubprogram * getSubprogram (DIScope *Scope)
Helper function to either return Scope, if it is a subprogram or the attached subprogram for a local scope.
static bool isSplat (Value *V)
Return true if V is a splat of a value (which is used when multiplying a matrix with a scalar).
template<typename LTy, typename RTy>
static auto m_AnyMul (const LTy &L, const RTy &R)
Match any mul operation (fp or integer).
template<typename LTy, typename RTy>
static auto m_AnyAdd (const LTy &L, const RTy &R)
Match any add operation (fp or integer).
static Value * computeVectorAddr (Value *BasePtr, Value *VecIdx, Value *Stride, unsigned NumElements, Type *EltType, IRBuilder<> &Builder)
static bool isShapePreserving (Value *V)
static iterator_range< Use * > getShapedOperandsForInst (Instruction *I)
Return an iterator over the operands of I that should share shape information with I.
static std::optional< ShapeInfo > computeShapeInfoForInst (Instruction *I, const DenseMap< Value *, ShapeInfo > &ShapeMap)
Return the ShapeInfo for the result of I, it it can be determined.
Variables
static cl::opt< bool > FuseMatrix ("fuse-matrix", cl::init(true), cl::Hidden, cl::desc("Enable/disable fusing matrix instructions."))
static cl::opt< unsigned > TileSize ("fuse-matrix-tile-size", cl::init(4), cl::Hidden, cl::desc("Tile size for matrix instruction fusion using square-shaped tiles."))
static cl::opt< bool > TileUseLoops ("fuse-matrix-use-loops", cl::init(false), cl::Hidden, cl::desc("Generate loop nest for tiling."))
static cl::opt< bool > ForceFusion ("force-fuse-matrix", cl::init(false), cl::Hidden, cl::desc("Force matrix instruction fusion even if not profitable."))
static cl::opt< bool > AllowContractEnabled ("matrix-allow-contract", cl::init(false), cl::Hidden, cl::desc("Allow the use of FMAs if available and profitable. This may " "result in different results, due to less rounding error."))
static cl::opt< bool > VerifyShapeInfo ("verify-matrix-shapes", cl::Hidden, cl::desc("Enable/disable matrix shape verification."), cl::init(false))
static cl::opt< MatrixLayoutTy > MatrixLayout ("matrix-default-layout", cl::init(MatrixLayoutTy::ColumnMajor), cl::desc("Sets the default matrix layout"), cl::values(clEnumValN(MatrixLayoutTy::ColumnMajor, "column-major", "Use column-major layout"), clEnumValN(MatrixLayoutTy::RowMajor, "row-major", "Use row-major layout")))
static cl::opt< bool > PrintAfterTransposeOpt ("matrix-print-after-transpose-opt", cl::init(false))
static cl::opt< unsigned > SplitMatmulRemainderOverThreshold ("matrix-split-matmul-remainder-over-threshold", cl::Hidden, cl::desc("Illegal remainder vectors over this size in bits should be split " "in the inner loop of matmul"), cl::init(0))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-matrix-intrinsics"
Definition at line 57 of file LowerMatrixIntrinsics.cpp.
Enumeration Type Documentation
MatrixLayoutTy
enum class MatrixLayoutTy strong
Enumerator
ColumnMajor
RowMajor
Definition at line 87 of file LowerMatrixIntrinsics.cpp.
Function Documentation
computeShapeInfoForInst()
std::optional< ShapeInfo > computeShapeInfoForInst (Instruction * I, const DenseMap< Value *, ShapeInfo > & ShapeMap) static
Return the ShapeInfo for the result of I, it it can be determined.
Definition at line 318 of file LowerMatrixIntrinsics.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), getShapedOperandsForInst(), I, isShapePreserving(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::m_Store(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and N.
computeVectorAddr()
Value * computeVectorAddr (Value * BasePtr, Value * VecIdx, Value * Stride, unsigned NumElements, Type * EltType, IRBuilder<> & Builder) static
Definition at line 174 of file LowerMatrixIntrinsics.cpp.
References assert(), llvm::cast(), llvm::isa(), and isZero().
getShapedOperandsForInst()
iterator_range< Use * > getShapedOperandsForInst (Instruction * I) static
Return an iterator over the operands of I that should share shape information with I.
Definition at line 308 of file LowerMatrixIntrinsics.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::drop_begin(), I, llvm::isa(), and isShapePreserving().
Referenced by computeShapeInfoForInst().
getSubprogram()
DISubprogram * getSubprogram (DIScope * Scope) static
Helper function to either return Scope, if it is a subprogram or the attached subprogram for a local scope.
Definition at line 108 of file LowerMatrixIntrinsics.cpp.
References llvm::cast(), llvm::dyn_cast(), and llvm::DILocalScope::getSubprogram().
isShapePreserving()
bool isShapePreserving (Value * V) static
Definition at line 248 of file LowerMatrixIntrinsics.cpp.
References llvm::dyn_cast(), I, II, llvm::isa(), and llvm_unreachable.
Referenced by computeShapeInfoForInst(), and getShapedOperandsForInst().
isSplat()
bool isSplat (Value * V) static
Return true if V is a splat of a value (which is used when multiplying a matrix with a scalar).
Definition at line 116 of file LowerMatrixIntrinsics.cpp.
References llvm::dyn_cast().
Referenced by llvm::PPC::get_VSPLTI_elt(), slpvectorizer::BoUpSLP::isTreeNotExtendable(), slpvectorizer::BoUpSLP::isTreeTinyAndNotFullyVectorizable(), slpvectorizer::BoUpSLP::processBuildVector(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
m_AnyAdd()
template<typename LTy, typename RTy> auto m_AnyAdd (const LTy & L, const RTy & R) static
Match any add operation (fp or integer).
Definition at line 130 of file LowerMatrixIntrinsics.cpp.
References llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_CombineOr(), and llvm::PatternMatch::m_FAdd().
m_AnyMul()
template<typename LTy, typename RTy> auto m_AnyMul (const LTy & L, const RTy & R) static
Match any mul operation (fp or integer).
Definition at line 124 of file LowerMatrixIntrinsics.cpp.
References llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_FMul(), and llvm::PatternMatch::m_Mul().
STATISTIC() [1/3]
STATISTIC (FlattenedMatrices , "Number of matrix flattenings")
STATISTIC() [2/3]
STATISTIC (ReshapedMatrices , "Number of matrix reshapes")
STATISTIC() [3/3]
STATISTIC (SplitMatrices , "Number of matrix splits")
Variable Documentation
AllowContractEnabled
cl::opt< bool > AllowContractEnabled("matrix-allow-contract", cl::init(false), cl::Hidden, cl::desc("Allow the use of FMAs if available and profitable. This may " "result in different results, due to less rounding error.")) ("matrix-allow-contract" , cl::init(false) , cl::Hidden , cl::desc("Allow the use of FMAs if available and profitable. This may " "result in different results, due to less rounding error.")) static
ForceFusion
cl::opt< bool > ForceFusion("force-fuse-matrix", cl::init(false), cl::Hidden, cl::desc("Force matrix instruction fusion even if not profitable.")) ("force-fuse-matrix" , cl::init(false) , cl::Hidden , cl::desc("Force matrix instruction fusion even if not profitable.")) static
FuseMatrix
cl::opt< bool > FuseMatrix("fuse-matrix", cl::init(true), cl::Hidden, cl::desc("Enable/disable fusing matrix instructions.")) ("fuse-matrix" , cl::init(true) , cl::Hidden , cl::desc("Enable/disable fusing matrix instructions.")) static
MatrixLayout
cl::opt< MatrixLayoutTy > MatrixLayout("matrix-default-layout", cl::init(MatrixLayoutTy::ColumnMajor), cl::desc("Sets the default matrix layout"), cl::values(clEnumValN(MatrixLayoutTy::ColumnMajor, "column-major", "Use column-major layout"), clEnumValN(MatrixLayoutTy::RowMajor, "row-major", "Use row-major layout"))) ("matrix-default-layout" , cl::init(MatrixLayoutTy::ColumnMajor) , cl::desc("Sets the default matrix layout") , cl::values(clEnumValN(MatrixLayoutTy::ColumnMajor, "column-major", "Use column-major layout"), clEnumValN(MatrixLayoutTy::RowMajor, "row-major", "Use row-major layout"))) static
PrintAfterTransposeOpt
cl::opt< bool > PrintAfterTransposeOpt("matrix-print-after-transpose-opt", cl::init(false)) ("matrix-print-after-transpose-opt" , cl::init(false)) static
SplitMatmulRemainderOverThreshold
cl::opt< unsigned > SplitMatmulRemainderOverThreshold("matrix-split-matmul-remainder-over-threshold", cl::Hidden, cl::desc("Illegal remainder vectors over this size in bits should be split " "in the inner loop of matmul"), cl::init(0)) ("matrix-split-matmul-remainder-over-threshold" , cl::Hidden , cl::desc("Illegal remainder vectors over this size in bits should be split " "in the inner loop of matmul") , cl::init(0)) static
TileSize
cl::opt< unsigned > TileSize("fuse-matrix-tile-size", cl::init(4), cl::Hidden, cl::desc("Tile size for matrix instruction fusion using square-shaped tiles.")) ("fuse-matrix-tile-size" , cl::init(4) , cl::Hidden , cl::desc("Tile size for matrix instruction fusion using square-shaped tiles.")) static
Referenced by llvm::OpenMPIRBuilder::tileLoops().
TileUseLoops
cl::opt< bool > TileUseLoops("fuse-matrix-use-loops", cl::init(false), cl::Hidden, cl::desc("Generate loop nest for tiling.")) ("fuse-matrix-use-loops" , cl::init(false) , cl::Hidden , cl::desc("Generate loop nest for tiling.")) static
VerifyShapeInfo
cl::opt< bool > VerifyShapeInfo("verify-matrix-shapes", cl::Hidden, cl::desc("Enable/disable matrix shape verification."), cl::init(false)) ("verify-matrix-shapes" , cl::Hidden , cl::desc("Enable/disable matrix shape verification.") , cl::init(false)) static