LLVM: lib/Target/M68k/M68kTargetMachine.cpp File Reference
M68kTargetMachine.cpp File Reference
This file contains implementation for M68k target machine.
#include "M68kTargetMachine.h"
#include "M68k.h"
#include "M68kMachineFunction.h"
#include "M68kSubtarget.h"
#include "M68kTargetObjectFile.h"
#include "TargetInfo/M68kTargetInfo.h"
#include "llvm/CodeGen/GlobalISel/IRTranslator.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/GlobalISel/Legalizer.h"
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/PassRegistry.h"
#include <memory>
#include <optional>
Macros
#define DEBUG_TYPE "m68k"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeM68kTarget ()
Detailed Description
This file contains implementation for M68k target machine.
Definition in file M68kTargetMachine.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "m68k"
Definition at line 34 of file M68kTargetMachine.cpp.
Function Documentation
LLVMInitializeM68kTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeM68kTarget ()
Definition at line 36 of file M68kTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheM68kTarget(), llvm::initializeGlobalISel(), llvm::initializeM68kAsmPrinterPass(), llvm::initializeM68kCollapseMOVEMPass(), llvm::initializeM68kDAGToDAGISelLegacyPass(), llvm::initializeM68kExpandPseudoPass(), llvm::initializeM68kGlobalBaseRegPass(), LLVM_EXTERNAL_VISIBILITY, and X.