LLVM: lib/CodeGen/MachineFunction.cpp File Reference
MachineFunction.cpp File Reference
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/PseudoSourceValueManager.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/WasmEHFuncInfo.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/EHPersonalities.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/Value.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <string>
#include <utility>
#include <vector>
#include "LiveDebugValues/LiveDebugValues.h"
Classes
struct llvm::DOTGraphTraits< const MachineFunction * >
Macros
#define DEBUG_TYPE "codegen"
Functions
static const char * getPropertyName (MachineFunctionProperties::Property Prop)
void setUnsafeStackSize (const Function &F, MachineFrameInfo &FrameInfo)
static Align getFnStackAlignment (const TargetSubtargetInfo &STI, const Function &F)
OS<< "\n# End machine code for function "<< getName()<< ".\n\n";}bool MachineFunction::needsFrameMoves() const { return getTarget().Options.ForceDwarfFrameSection||F.needsUnwindTableEntry()||!F.getParent() -> debug_compile_units ().empty()
static bool CanShareConstantPoolEntry (const Constant *A, const Constant *B, const DataLayout &DL)
Test whether the given two constants can be allocated the same constant pool entry referenced by.
template<>
std::optional< Function::ProfileCount > ProfileSummaryInfo::getEntryCount< llvm::MachineFunction > (const llvm::MachineFunction *F) const
Exception Handling
static const MachineInstr * getCallInstr (const MachineInstr *MI)
Return the call machine instruction or find a call within bundle.
Variables
static cl::opt< unsigned > AlignAllFunctions ("align-all-functions", cl::desc("Force the alignment of all functions in log2 format (e.g. 4 " "means align on 16B boundaries)."), cl::init(0), cl::Hidden)
true
Allocate a new MachineBasicBlock.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "codegen"
Definition at line 82 of file MachineFunction.cpp.
Function Documentation
CanShareConstantPoolEntry()
bool CanShareConstantPoolEntry (const Constant * A, const Constant * B, const DataLayout & DL) static
Test whether the given two constants can be allocated the same constant pool entry referenced by.
Parameters
A.
Definition at line 1513 of file MachineFunction.cpp.
References A(), B(), llvm::ConstantFoldCastOperand(), DL, llvm::IntegerType::get(), and llvm::isa().
Referenced by llvm::MachineConstantPool::getConstantPoolIndex().
debug_compile_units()
OS<< "\n# End machine code for function "<< getName()<< ".\n\n";}bool MachineFunction::needsFrameMoves() const { return getTarget().Options.ForceDwarfFrameSection||F.needsUnwindTableEntry()||!F.getParent() -> debug_compile_units ()
References F.
getCallInstr()
const MachineInstr * getCallInstr (const MachineInstr * MI) static
Return the call machine instruction or find a call within bundle.
Definition at line 947 of file MachineFunction.cpp.
References llvm::getBundleEnd(), llvm::getBundleStart(), llvm_unreachable, llvm::make_range(), and MI.
Referenced by llvm::MachineFunction::copyAdditionalCallInfo(), llvm::MachineFunction::eraseAdditionalCallInfo(), and llvm::MachineFunction::moveAdditionalCallInfo().
getFnStackAlignment()
Align getFnStackAlignment (const TargetSubtargetInfo & STI, const Function & F) inline static
Definition at line 157 of file MachineFunction.cpp.
References F, llvm::TargetSubtargetInfo::getFrameLowering(), and llvm::TargetFrameLowering::getStackAlign().
getPropertyName()
const char * getPropertyName (MachineFunctionProperties::Property Prop) static
Definition at line 90 of file MachineFunction.cpp.
References llvm_unreachable, and P.
ProfileSummaryInfo::getEntryCount< llvm::MachineFunction >()
template<> std::optional< Function::ProfileCount > ProfileSummaryInfo::getEntryCount< llvm::MachineFunction > (const llvm::MachineFunction * F) const
Definition at line 1601 of file MachineFunction.cpp.
setUnsafeStackSize()
void setUnsafeStackSize (const Function & F, MachineFrameInfo & FrameInfo)
Definition at line 112 of file MachineFunction.cpp.
References llvm::dyn_cast_or_null(), llvm::mdconst::extract(), F, N, and llvm::MachineFrameInfo::setUnsafeStackSize().
Variable Documentation
AlignAllFunctions
cl::opt< unsigned > AlignAllFunctions("align-all-functions", cl::desc("Force the alignment of all functions in log2 format (e.g. 4 " "means align on 16B boundaries)."), cl::init(0), cl::Hidden) ("align-all-functions" , cl::desc("Force the alignment of all functions in log2 format (e.g. 4 " "means align on 16B boundaries).") , cl::init(0) , cl::Hidden) static
true
true
Allocate a new MachineBasicBlock.
Use this instead of new MachineBasicBlock'. */ MachineBasicBlock * MachineFunction::CreateMachineBasicBlock(const BasicBlock *BB, std::optional<UniqueBBID> BBID) { MachineBasicBlock *MBB = new (BasicBlockRecycler.Allocate<MachineBasicBlock>(Allocator)) MachineBasicBlock(*this, BB); of APIs to run individual stages in isolation. BBID for -basic-block-sections=list and -basic-block-address-map` to allow robust mapping of profiles to basic blocks. if (Target.Options.BBAddrMap || Target.getBBSectionsType() == BasicBlockSection::List) MBB->setBBID(BBID.has_value() ? *BBID : UniqueBBID{NextBBID++, 0}); return MBB; }
/ Delete the given MachineBasicBlock. void MachineFunction::deleteMachineBasicBlock(MachineBasicBlock *MBB) { assert(MBB->getParent() == this && "MBB parent mismatch!"); Clean up any references to MBB in jump tables before deleting it. if (JumpTableInfo) JumpTableInfo->RemoveMBBFromJumpTables(MBB); MBB->~MachineBasicBlock(); BasicBlockRecycler.Deallocate(Allocator, MBB); }
MachineMemOperand *MachineFunction::getMachineMemOperand(MachinePointerInfo PtrInfo, MachineMemOperand::Flags F, LocationSize Size, Align BaseAlignment, const AAMDNodes &AAInfo, const MDNode *Ranges, SyncScope::ID SSID, AtomicOrdering Ordering, AtomicOrdering FailureOrdering) { assert((!Size.hasValue() || Size.getValue().getKnownMinValue() != ~UINT64_C(0)) && "Unexpected an unknown size to be represented using " "LocationSize::beforeOrAfter()"); return new (Allocator) MachineMemOperand(PtrInfo, F, Size, BaseAlignment, AAInfo, Ranges, SSID, Ordering, FailureOrdering); }
MachineMemOperand *MachineFunction::getMachineMemOperand(MachinePointerInfo PtrInfo, MachineMemOperand::Flags f, LLT MemTy, Align base_alignment, const AAMDNodes &AAInfo, const MDNode *Ranges, SyncScope::ID SSID, AtomicOrdering Ordering, AtomicOrdering FailureOrdering) { return new (Allocator) MachineMemOperand(PtrInfo, f, MemTy, base_alignment, AAInfo, Ranges, SSID, Ordering, FailureOrdering); }
MachineMemOperand * MachineFunction::getMachineMemOperand(const MachineMemOperand *MMO, const MachinePointerInfo &PtrInfo, LocationSize Size) { assert((!Size.hasValue() || Size.getValue().getKnownMinValue() != ~UINT64_C(0)) && "Unexpected an unknown size to be represented using " "LocationSize::beforeOrAfter()"); return new (Allocator) MachineMemOperand(PtrInfo, MMO->getFlags(), Size, MMO->getBaseAlign(), AAMDNodes(), nullptr, MMO->getSyncScopeID(), MMO->getSuccessOrdering(), MMO->getFailureOrdering()); }
MachineMemOperand *MachineFunction::getMachineMemOperand(const MachineMemOperand *MMO, const MachinePointerInfo &PtrInfo, LLT Ty) { return new (Allocator) MachineMemOperand(PtrInfo, MMO->getFlags(), Ty, MMO->getBaseAlign(), AAMDNodes(), nullptr, MMO->getSyncScopeID(), MMO->getSuccessOrdering(), MMO->getFailureOrdering()); }
MachineMemOperand * MachineFunction::getMachineMemOperand(const MachineMemOperand *MMO, int64_t Offset, LLT Ty) { const MachinePointerInfo &PtrInfo = MMO->getPointerInfo();
If there is no pointer value, the offset isn't tracked so we need to adjust the base alignment. Align Alignment = PtrInfo.V.isNull() ? commonAlignment(MMO->getBaseAlign(), Offset) : MMO->getBaseAlign();
Do not preserve ranges, since we don't necessarily know what the high bits are anymore. return new (Allocator) MachineMemOperand(PtrInfo.getWithOffset(Offset), MMO->getFlags(), Ty, Alignment, MMO->getAAInfo(), nullptr, MMO->getSyncScopeID(), MMO->getSuccessOrdering(), MMO->getFailureOrdering()); }
MachineMemOperand * MachineFunction::getMachineMemOperand(const MachineMemOperand *MMO, const AAMDNodes &AAInfo) { MachinePointerInfo MPI = MMO->getValue() ? MachinePointerInfo(MMO->getValue(), MMO->getOffset()) : MachinePointerInfo(MMO->getPseudoValue(), MMO->getOffset());
return new (Allocator) MachineMemOperand(MPI, MMO->getFlags(), MMO->getSize(), MMO->getBaseAlign(), AAInfo, MMO->getRanges(), MMO->getSyncScopeID(), MMO->getSuccessOrdering(), MMO->getFailureOrdering()); }
MachineMemOperand * MachineFunction::getMachineMemOperand(const MachineMemOperand *MMO, MachineMemOperand::Flags Flags) { return new (Allocator) MachineMemOperand(MMO->getPointerInfo(), Flags, MMO->getSize(), MMO->getBaseAlign(), MMO->getAAInfo(), MMO->getRanges(), MMO->getSyncScopeID(), MMO->getSuccessOrdering(), MMO->getFailureOrdering()); }
MachineInstr::ExtraInfo *MachineFunction::createMIExtraInfo(ArrayRef<MachineMemOperand *> MMOs, MCSymbol *PreInstrSymbol, MCSymbol *PostInstrSymbol, MDNode *HeapAllocMarker, MDNode *PCSections, uint32_t CFIType, MDNode *MMRAs, Value *DS) { return MachineInstr::ExtraInfo::create(Allocator, MMOs, PreInstrSymbol, PostInstrSymbol, HeapAllocMarker, PCSections, CFIType, MMRAs, DS); }
const char *MachineFunction::createExternalSymbolName(StringRef Name) { char *Dest = Allocator.Allocate<char>(Name.size() + 1); llvm::copy(Name, Dest); Dest[Name.size()] = 0; return Dest; }
uint32_t *MachineFunction::allocateRegMask() { unsigned NumRegs = getSubtarget().getRegisterInfo()->getNumRegs(); unsigned Size = MachineOperand::getRegMaskSize(NumRegs); uint32_t *Mask = Allocator.Allocate<uint32_t>(Size); memset(Mask, 0, Size * sizeof(Mask[0])); return Mask; }
ArrayRef<int> MachineFunction::allocateShuffleMask(ArrayRef<int> Mask) { int* AllocMask = Allocator.Allocate<int>(Mask.size()); copy(Mask, AllocMask); return {AllocMask, Mask.size()}; }
LLVM_DUMP_METHOD void MachineFunction::dump() const { print(dbgs()); }
StringRef MachineFunction::getName() const { return getFunction().getName(); }
void MachineFunction::print(raw_ostream &OS, const SlotIndexes *Indexes) const { OS << "# Machine code for function " << getName() << ": "; getProperties().print(OS); OS << '
';
Print Frame Information FrameInfo->print(*this, OS);
Print JumpTable Information if (JumpTableInfo) JumpTableInfo->print(OS);
Print Constant Pool ConstantPool->print(OS);
const TargetRegisterInfo *TRI = getSubtarget().getRegisterInfo();
if (RegInfo && !RegInfo->livein_empty()) { OS << "Function Live Ins: "; for (MachineRegisterInfo::livein_iterator I = RegInfo->livein_begin(), E = RegInfo->livein_end(); I != E; ++I) { OS << printReg(I->first, TRI); if (I->second) OS << " in " << printReg(I->second, TRI); if (std::next(I) != E) OS << ", "; } OS << '
'; }
ModuleSlotTracker MST(getFunction().getParent()); MST.incorporateFunction(getFunction()); for (const auto &BB : *this) { OS << '
'; If we print the whole function, print it at its most verbose level. BB.print(OS, MST, Indexes, /*IsStandalone=
Definition at line 684 of file MachineFunction.cpp.