LLVM: lib/Target/AArch64/MachineSMEABIPass.cpp File Reference
MachineSMEABIPass.cpp File Reference
#include "AArch64InstrInfo.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64Subtarget.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "llvm/ADT/BitmaskEnum.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/EdgeBundles.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineOptimizationRemarkEmitter.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "aarch64-machine-sme-abi"
#define MAKE_CASE(V)
Functions
INITIALIZE_PASS (MachineSMEABI, "aarch64-machine-sme-abi", "Machine SME ABI", false, false) bool MachineSMEABI
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-machine-sme-abi"
Definition at line 72 of file MachineSMEABIPass.cpp.
MAKE_CASE
#define MAKE_CASE (V)
Value:
case V:                                                                      \
  return #V;
Referenced by llvm::ARMSelectionDAGInfo::getTargetNodeName(), and llvm::NVPTXSelectionDAGInfo::getTargetNodeName().
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (MachineSMEABI , "aarch64-machine-sme-abi" , "Machine SME ABI" , false , false)
Definition at line 1149 of file MachineSMEABIPass.cpp.
References assert(), llvm::MachineBasicBlock::front(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineBasicBlock::getNumber(), if(), MBBI, MRI, TII, and TRI.