LLVM: lib/MC/MCExpr.cpp File Reference
MCExpr.cpp File Reference
#include "llvm/MC/MCExpr.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
Namespaces
namespace stats
Macros
#define DEBUG_TYPE "mcexpr"
Functions
static int getPrecedence (MCBinaryExpr::Opcode Op)
static void attemptToFoldSymbolOffsetDifference (const MCAssembler *Asm, bool InSet, const MCSymbol *&A, const MCSymbol *&B, int64_t &Addend)
Helper method for.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mcexpr"
Definition at line 31 of file MCExpr.cpp.
Function Documentation
attemptToFoldSymbolOffsetDifference()
void attemptToFoldSymbolOffsetDifference (const MCAssembler * Asm, bool InSet, const MCSymbol *& A, const MCSymbol *& B, int64_t & Addend) static
Helper method for.
See also
EvaluateSymbolAdd().
Definition at line 273 of file MCExpr.cpp.
References A(), B(), llvm::dyn_cast(), F, llvm::MCFragment::FT_Align, llvm::MCFragment::FT_Data, llvm::MCFragment::FT_Relaxable, llvm::MCSymbol::getFragment(), llvm::MCFragment::getLayoutOrder(), llvm::MCSymbol::getOffset(), llvm::MCFragment::getParent(), llvm::MCSection::isLinkerRelaxable(), llvm::MCSymbol::isUndefined(), llvm::MCSymbol::isVariable(), llvm::Reverse, and std::swap().
Referenced by llvm::MCExpr::evaluateSymbolicAdd().
getPrecedence()
int getPrecedence (MCBinaryExpr::Opcode Op) static
Definition at line 41 of file MCExpr.cpp.
References llvm::MCBinaryExpr::Add, and llvm::MCBinaryExpr::Sub.