LLVM: lib/Support/MemoryBuffer.cpp File Reference
MemoryBuffer.cpp File Reference
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/AutoConvert.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/IOSandbox.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/SmallVectorMemoryBuffer.h"
#include <algorithm>
#include <cassert>
#include <cstring>
#include <new>
#include <sys/types.h>
#include <system_error>
#include <unistd.h>
Functions
static void CopyStringRef (char *Memory, StringRef Data)
CopyStringRef - Copies contents of a StringRef into a block of memory and null-terminates it.
void * operator new (size_t N, const NamedBufferAlloc &Alloc)
template<typename MB>
static ErrorOr< std::unique_ptr< MB > > getFileAux (const Twine &Filename, uint64_t MapSize, uint64_t Offset, bool IsText, bool RequiresNullTerminator, bool IsVolatile, std::optional< Align > Alignment)
static ErrorOr< std::unique_ptr< WritableMemoryBuffer > > getMemBufferCopyImpl (StringRef InputData, const Twine &BufferName)
static ErrorOr< std::unique_ptr< WritableMemoryBuffer > > getMemoryBufferForStream (sys::fs::file_t FD, const Twine &BufferName)
template<typename MB>
static ErrorOr< std::unique_ptr< MB > > getOpenFileImpl (sys::fs::file_t FD, const Twine &Filename, uint64_t FileSize, uint64_t MapSize, int64_t Offset, bool RequiresNullTerminator, bool IsVolatile, std::optional< Align > Alignment)
static bool shouldUseMmap (sys::fs::file_t FD, size_t FileSize, size_t MapSize, off_t Offset, bool RequiresNullTerminator, int PageSize, bool IsVolatile)
static ErrorOr< std::unique_ptr< WriteThroughMemoryBuffer > > getReadWriteFile (const Twine &Filename, uint64_t FileSize, uint64_t MapSize, uint64_t Offset)
Function Documentation
CopyStringRef()
void CopyStringRef (char * Memory, StringRef Data) static
CopyStringRef - Copies contents of a StringRef into a block of memory and null-terminates it.
Definition at line 63 of file MemoryBuffer.cpp.
References llvm::Data.
Referenced by llvm::WritableMemoryBuffer::getNewUninitMemBuffer(), and operator new().
getFileAux()
template<typename MB> ErrorOr< std::unique_ptr< MB > > getFileAux (const Twine & Filename, uint64_t MapSize, uint64_t Offset, bool IsText, bool RequiresNullTerminator, bool IsVolatile, std::optional< Align > Alignment) static
Definition at line 282 of file MemoryBuffer.cpp.
References llvm::sys::fs::closeFile(), llvm::errorToErrorCode(), getOpenFileImpl(), llvm::sys::fs::OF_None, llvm::sys::fs::OF_TextWithCRLF, llvm::Offset, llvm::sys::fs::openNativeFileForRead(), and llvm::Expected< T >::takeError().
Referenced by llvm::MemoryBuffer::getFile(), llvm::WritableMemoryBuffer::getFile(), llvm::MemoryBuffer::getFileSlice(), and llvm::WritableMemoryBuffer::getFileSlice().
getMemBufferCopyImpl()
ErrorOr< std::unique_ptr< WritableMemoryBuffer > > getMemBufferCopyImpl (StringRef InputData, const Twine & BufferName) static
Definition at line 142 of file MemoryBuffer.cpp.
References llvm::copy(), llvm::WritableMemoryBuffer::getNewUninitMemBuffer(), llvm::make_error_code(), llvm::not_enough_memory, and llvm::StringRef::size().
Referenced by llvm::MemoryBuffer::getMemBufferCopy(), and getMemoryBufferForStream().
getMemoryBufferForStream()
ErrorOr< std::unique_ptr< WritableMemoryBuffer > > getMemoryBufferForStream (sys::fs::file_t FD, const Twine & BufferName) static
Definition at line 256 of file MemoryBuffer.cpp.
References E(), llvm::errorToErrorCode(), getMemBufferCopyImpl(), and llvm::sys::fs::readNativeFileToEOF().
Referenced by llvm::MemoryBuffer::getFileAsStream(), getOpenFileImpl(), and llvm::MemoryBuffer::getSTDIN().
getOpenFileImpl()
template<typename MB> ErrorOr< std::unique_ptr< MB > > getOpenFileImpl (sys::fs::file_t FD, const Twine & Filename, uint64_t FileSize, uint64_t MapSize, int64_t Offset, bool RequiresNullTerminator, bool IsVolatile, std::optional< Align > Alignment) static
Definition at line 486 of file MemoryBuffer.cpp.
References llvm::sys::fs::block_file, llvm::MutableArrayRef< T >::data(), llvm::MutableArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::errorToErrorCode(), llvm::ErrorOr< T >::getError(), getMemoryBufferForStream(), llvm::WritableMemoryBuffer::getNewUninitMemBuffer(), llvm::sys::Process::getPageSizeEstimate(), llvm::make_error_code(), llvm::not_enough_memory, llvm::Offset, PageSize, llvm::sys::fs::readNativeFileSlice(), llvm::sys::fs::regular_file, shouldUseMmap(), llvm::ArrayRef< T >::size(), llvm::sys::fs::status(), and llvm::Expected< T >::takeError().
Referenced by getFileAux(), llvm::MemoryBuffer::getOpenFile(), and llvm::MemoryBuffer::getOpenFileSlice().
getReadWriteFile()
ErrorOr< std::unique_ptr< WriteThroughMemoryBuffer > > getReadWriteFile (const Twine & Filename, uint64_t FileSize, uint64_t MapSize, uint64_t Offset) static
Definition at line 428 of file MemoryBuffer.cpp.
References llvm::sys::fs::block_file, llvm::sys::fs::CD_OpenExisting, llvm::errorToErrorCode(), llvm::invalid_argument, llvm::make_error_code(), llvm::sys::fs::OF_None, llvm::Offset, llvm::sys::fs::openNativeFileForReadWrite(), llvm::sys::fs::regular_file, llvm::sys::fs::status(), and llvm::Expected< T >::takeError().
Referenced by llvm::WriteThroughMemoryBuffer::getFile(), and llvm::WriteThroughMemoryBuffer::getFileSlice().
operator new()
void * operator new (size_t N, const NamedBufferAlloc & Alloc)
Definition at line 76 of file MemoryBuffer.cpp.
References Alloc, CopyStringRef(), N, llvm::report_bad_alloc_error(), and llvm::StringRef::size().
shouldUseMmap()
bool shouldUseMmap (sys::fs::file_t FD, size_t FileSize, size_t MapSize, off_t Offset, bool RequiresNullTerminator, int PageSize, bool IsVolatile) static
Definition at line 367 of file MemoryBuffer.cpp.
References assert(), llvm::Offset, PageSize, and llvm::sys::fs::status().
Referenced by getOpenFileImpl().