LLVM: lib/Analysis/MemorySSAUpdater.cpp File Reference
MemorySSAUpdater.cpp File Reference
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/IteratedDominanceFrontier.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Dominators.h"
#include "llvm/Support/Debug.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "memoryssa"
Functions
static void setMemoryPhiValueForBlock (MemoryPhi *MP, const BasicBlock *BB, MemoryAccess *NewDef)
static MemoryAccess * onlySingleValue (MemoryPhi *MP)
If all arguments of a MemoryPHI are defined by the same incoming argument, return that argument.
static MemoryAccess * getNewDefiningAccessForClone (MemoryAccess *MA, const ValueToValueMapTy &VMap, PhiToDefMap &MPhiMap, MemorySSA *MSSA, function_ref< bool(BasicBlock *BB)> IsInClonedRegion)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memoryssa"
Definition at line 24 of file MemorySSAUpdater.cpp.
Function Documentation
getNewDefiningAccessForClone()
MemoryAccess * getNewDefiningAccessForClone (MemoryAccess * MA, const ValueToValueMapTy & VMap, PhiToDefMap & MPhiMap, MemorySSA * MSSA, function_ref< bool(BasicBlock *BB)> IsInClonedRegion) static
Definition at line 559 of file MemorySSAUpdater.cpp.
References assert(), llvm::cast(), llvm::cast_or_null(), llvm::dyn_cast(), llvm::MemorySSA::getMemoryAccess(), getNewDefiningAccessForClone(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::isa(), llvm::MemorySSA::isLiveOnEntryDef(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and llvm::ValueMap< KeyT, ValueT, Config >::lookup().
Referenced by getNewDefiningAccessForClone(), and llvm::MemorySSAUpdater::updateForClonedLoop().
onlySingleValue()
MemoryAccess * onlySingleValue (MemoryPhi * MP) static
If all arguments of a MemoryPHI are defined by the same incoming argument, return that argument.
Definition at line 547 of file MemorySSAUpdater.cpp.
References llvm::cast(), and llvm::User::operands().
Referenced by llvm::MemorySSAUpdater::removeMemoryAccess(), and llvm::MemorySSAUpdater::updateForClonedLoop().
setMemoryPhiValueForBlock()
void setMemoryPhiValueForBlock (MemoryPhi * MP, const BasicBlock * BB, MemoryAccess * NewDef) static
Definition at line 285 of file MemorySSAUpdater.cpp.
References assert(), llvm::MemoryPhi::blocks(), llvm::drop_begin(), llvm::MemoryPhi::getBasicBlockIndex(), and llvm::MemoryPhi::setIncomingValue().