LLVM: lib/Target/Mips/MipsSEInstrInfo.cpp File Reference
MipsSEInstrInfo.cpp File Reference
#include "MipsSEInstrInfo.h"
#include "MipsAnalyzeImmediate.h"
#include "MipsTargetMachine.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
Functions
static unsigned getUnconditionalBranch (const MipsSubtarget &STI)
static std::pair< bool, bool > readsWritesFloatRegister (MachineInstr &MI, Register Reg)
static bool isWritedByFCMP (MachineBasicBlock::iterator I, Register Reg)
static bool isOnlyReadsBySEL (MachineBasicBlock::iterator I, Register Reg)
static bool isORCopyInst (const MachineInstr &MI)
Function Documentation
getUnconditionalBranch()
unsigned getUnconditionalBranch (const MipsSubtarget & STI) static
Definition at line 24 of file MipsSEInstrInfo.cpp.
References llvm::MipsSubtarget::inMicroMipsMode(), and llvm::MipsSubtarget::isPositionIndependent().
Referenced by llvm::MipsSEInstrInfo::MipsSEInstrInfo().
isOnlyReadsBySEL()
bool isOnlyReadsBySEL (MachineBasicBlock::iterator I, Register Reg) static
Definition at line 118 of file MipsSEInstrInfo.cpp.
References I, MBB, readsWritesFloatRegister(), and Reg.
Referenced by llvm::MipsSEInstrInfo::copyPhysReg().
isORCopyInst()
bool isORCopyInst (const MachineInstr & MI) static
Definition at line 274 of file MipsSEInstrInfo.cpp.
References MI.
Referenced by llvm::MipsSEInstrInfo::isCopyInstrImpl().
isWritedByFCMP()
bool isWritedByFCMP (MachineBasicBlock::iterator I, Register Reg) static
Definition at line 100 of file MipsSEInstrInfo.cpp.
References I, MBB, readsWritesFloatRegister(), and Reg.
Referenced by llvm::MipsSEInstrInfo::copyPhysReg().
readsWritesFloatRegister()
std::pair< bool, bool > readsWritesFloatRegister (MachineInstr & MI, Register Reg) static
Definition at line 76 of file MipsSEInstrInfo.cpp.
References assert(), llvm::getFloatRegFromFReg(), MI, and Reg.
Referenced by isOnlyReadsBySEL(), and isWritedByFCMP().