LLVM: lib/Target/Mips/MCTargetDesc/MipsMCAsmInfo.cpp File Reference
MipsMCAsmInfo.cpp File Reference
#include "MipsMCAsmInfo.h"
#include "MipsABIInfo.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/TargetParser/Triple.h"
Functions
static void printImpl (const MCAsmInfo &MAI, raw_ostream &OS, const MCSpecifierExpr &Expr)
static bool evaluate (const MCSpecifierExpr &Expr, MCValue &Res, const MCAssembler *Asm)
Function Documentation
evaluate()
bool evaluate (const MCSpecifierExpr & Expr, MCValue & Res, const MCAssembler * Asm) static
Definition at line 183 of file MipsMCAsmInfo.cpp.
References llvm::cast(), llvm::MCExpr::evaluateAsRelocatable(), llvm::MCSpecifierExpr::getSpecifier(), llvm::MCSpecifierExpr::getSubExpr(), llvm::MCValue::getSubSym(), llvm::Mips::isGpOff(), llvm::Mips::S_Special, and llvm::MCValue::setSpecifier().
printImpl()
void printImpl (const MCAsmInfo & MAI, raw_ostream & OS, const MCSpecifierExpr & Expr) static
Definition at line 72 of file MipsMCAsmInfo.cpp.
References llvm::MCExpr::evaluateAsAbsolute(), llvm::MCSpecifierExpr::getSpecifier(), llvm::MCSpecifierExpr::getSubExpr(), llvm_unreachable, llvm::MCAsmInfo::printExpr(), llvm::Mips::S_CALL_HI16, llvm::Mips::S_CALL_LO16, llvm::Mips::S_DTPREL, llvm::Mips::S_DTPREL_HI, llvm::Mips::S_DTPREL_LO, llvm::Mips::S_GOT, llvm::Mips::S_GOT_CALL, llvm::Mips::S_GOT_DISP, llvm::Mips::S_GOT_HI16, llvm::Mips::S_GOT_LO16, llvm::Mips::S_GOT_OFST, llvm::Mips::S_GOT_PAGE, llvm::Mips::S_GOTTPREL, llvm::Mips::S_GPREL, llvm::Mips::S_HI, llvm::Mips::S_HIGHER, llvm::Mips::S_HIGHEST, llvm::Mips::S_LO, llvm::Mips::S_NEG, llvm::Mips::S_None, llvm::Mips::S_PCREL_HI16, llvm::Mips::S_PCREL_LO16, llvm::Mips::S_Special, llvm::Mips::S_TLSGD, llvm::Mips::S_TLSLDM, llvm::Mips::S_TPREL_HI, and llvm::Mips::S_TPREL_LO.
Referenced by llvm::vfs::FileSystem::print(), llvm::MipsCOFFMCAsmInfo::printSpecifierExpr(), and llvm::MipsELFMCAsmInfo::printSpecifierExpr().