LLVM: lib/CodeGen/MIRFSDiscriminator.cpp File Reference
MIRFSDiscriminator.cpp File Reference
#include "llvm/CodeGen/MIRFSDiscriminator.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/Analysis/BlockFrequencyInfoImpl.h"
#include "llvm/CodeGen/MIRFSDiscriminatorOptions.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PseudoProbe.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/xxhash.h"
#include "llvm/Transforms/Utils/SampleProfileLoaderBaseUtil.h"
Macros
#define DEBUG_TYPE "mirfs-discriminators"
Functions
static uint64_t getCallStackHashV0 (const MachineBasicBlock &BB, const MachineInstr &MI, const DILocation *DIL)
static uint64_t getCallStackHash (const DILocation *DIL)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mirfs-discriminators"
Definition at line 35 of file MIRFSDiscriminator.cpp.
Function Documentation
getCallStackHash()
uint64_t getCallStackHash (const DILocation * DIL) static
Definition at line 76 of file MIRFSDiscriminator.cpp.
References Seed, and llvm::xxh3_64bits().
getCallStackHashV0()
uint64_t getCallStackHashV0 (const MachineBasicBlock & BB, const MachineInstr & MI, const DILocation * DIL) static
Definition at line 58 of file MIRFSDiscriminator.cpp.
References llvm::MachineBasicBlock::getName(), llvm::sampleprof::MD5Hash(), and MI.