LLVM: lib/CodeGen/MIRPrinter.cpp File Reference
MIRPrinter.cpp File Reference
#include "llvm/CodeGen/MIRPrinter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MIRFormatter.h"
#include "llvm/CodeGen/MIRYamlMapping.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionAnalysis.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineModuleSlotTracker.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGenTypes/LowLevelType.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/Value.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <iterator>
#include <string>
#include <utility>
#include <vector>
Classes
struct llvm::yaml::BlockScalarTraits< Module >
This struct serializes the LLVM IR module.
Functions
static void printRegMIR (Register Reg, yaml::StringValue &Dest, const TargetRegisterInfo *TRI)
static DenseMap< const uint32_t *, unsigned > initRegisterMaskIds (const MachineFunction &MF)
static void printMBB (raw_ostream &OS, MFPrintState &State, const MachineBasicBlock &MBB)
static void convertMRI (yaml::MachineFunction &YamlMF, const MachineFunction &MF, const MachineRegisterInfo &RegInfo, const TargetRegisterInfo *TRI)
static void convertMCP (yaml::MachineFunction &MF, const MachineConstantPool &ConstantPool)
static void convertMJTI (ModuleSlotTracker &MST, yaml::MachineJumpTable &YamlJTI, const MachineJumpTableInfo &JTI)
static void convertMFI (ModuleSlotTracker &MST, yaml::MachineFrameInfo &YamlMFI, const MachineFrameInfo &MFI, const TargetRegisterInfo *TRI)
static void convertSRPoints (ModuleSlotTracker &MST, std::vector< yaml::SaveRestorePointEntry > &YamlSRPoints, const llvm::SaveRestorePoints &SRPoints, const TargetRegisterInfo *TRI)
static void convertStackObjects (yaml::MachineFunction &YMF, const MachineFunction &MF, ModuleSlotTracker &MST, MFPrintState &State)
static void convertEntryValueObjects (yaml::MachineFunction &YMF, const MachineFunction &MF, ModuleSlotTracker &MST)
static void convertCallSiteObjects (yaml::MachineFunction &YMF, const MachineFunction &MF, ModuleSlotTracker &MST)
static void convertMachineMetadataNodes (yaml::MachineFunction &YMF, const MachineFunction &MF, MachineModuleSlotTracker &MST)
static void convertCalledGlobals (yaml::MachineFunction &YMF, const MachineFunction &MF, MachineModuleSlotTracker &MST)
static void printMF (raw_ostream &OS, MFGetterFnT Fn, const MachineFunction &MF)
static void printCustomRegMask (const uint32_t *RegMask, raw_ostream &OS, const TargetRegisterInfo *TRI)
static void printRegClassOrBank (Register Reg, yaml::StringValue &Dest, const MachineRegisterInfo &RegInfo, const TargetRegisterInfo *TRI)
template<typename T>
static void printStackObjectDbgInfo (const MachineFunction::VariableDbgInfo &DebugVar, T &Object, ModuleSlotTracker &MST)
static void printRegFlags (Register Reg, std::vector< yaml::FlowStringValue > &RegisterFlags, const MachineFunction &MF, const TargetRegisterInfo *TRI)
static void printStackObjectReference (raw_ostream &OS, const MFPrintState &State, int FrameIndex)
static bool canPredictSuccessors (const MachineBasicBlock &MBB)
static void printMI (raw_ostream &OS, MFPrintState &State, const MachineInstr &MI)
static void printMIOperand (raw_ostream &OS, MFPrintState &State, const MachineInstr &MI, unsigned OpIdx, const TargetRegisterInfo *TRI, const TargetInstrInfo *TII, bool ShouldPrintRegisterTies, SmallBitVector &PrintedTypes, const MachineRegisterInfo &MRI, bool PrintDef)
static std::string formatOperandComment (std::string Comment)
Variables
static cl::opt< bool > SimplifyMIR ("simplify-mir", cl::Hidden, cl::desc("Leave out unnecessary information when printing MIR"))
static cl::opt< bool > PrintLocations ("mir-debug-loc", cl::Hidden, cl::init(true), cl::desc("Print MIR debug-locations"))
Function Documentation
canPredictSuccessors()
bool canPredictSuccessors (const MachineBasicBlock & MBB) static
Definition at line 696 of file MIRPrinter.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineFunction::end(), llvm::guessSuccessors(), llvm::is_contained(), MBB, llvm::Next, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by printMBB().
convertCalledGlobals()
void convertCalledGlobals (yaml::MachineFunction & YMF, const MachineFunction & MF, MachineModuleSlotTracker & MST) static
Definition at line 580 of file MIRPrinter.cpp.
References A(), B(), llvm::yaml::MachineFunction::CalledGlobals, llvm::MachineFunction::getCalledGlobals(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), and llvm::sort().
Referenced by printMF().
convertCallSiteObjects()
void convertCallSiteObjects (yaml::MachineFunction & YMF, const MachineFunction & MF, ModuleSlotTracker & MST) static
Definition at line 528 of file MIRPrinter.cpp.
References A(), llvm::yaml::CallSiteInfo::ArgForwardingRegs, llvm::yaml::CallSiteInfo::ArgRegPair::ArgNo, B(), llvm::yaml::MachineInstrLoc::BlockNum, llvm::yaml::CallSiteInfo::CalleeTypeIds, llvm::yaml::CallSiteInfo::CallLocation, llvm::yaml::MachineFunction::CallSitesInfo, llvm::MachineFunction::getCallSitesInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), MI, llvm::yaml::MachineInstrLoc::Offset, printRegMIR(), llvm::yaml::CallSiteInfo::ArgRegPair::Reg, llvm::sort(), and TRI.
Referenced by printMF().
convertEntryValueObjects()
void convertEntryValueObjects (yaml::MachineFunction & YMF, const MachineFunction & MF, ModuleSlotTracker & MST) static
Definition at line 372 of file MIRPrinter.cpp.
References llvm::yaml::MachineFunction::EntryValueObjects, llvm::MachineFunction::getEntryValueVariableDbgInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), printRegMIR(), printStackObjectDbgInfo(), and TRI.
Referenced by printMF().
convertMachineMetadataNodes()
void convertMachineMetadataNodes (yaml::MachineFunction & YMF, const MachineFunction & MF, MachineModuleSlotTracker & MST) static
Definition at line 567 of file MIRPrinter.cpp.
References llvm::MachineModuleSlotTracker::collectMachineMDNodes(), llvm::MachineFunction::getFunction(), llvm::GlobalValue::getParent(), and llvm::yaml::MachineFunction::MachineMetadataNodes.
Referenced by printMF().
convertMCP()
void convertMCP (yaml::MachineFunction & MF, const MachineConstantPool & ConstantPool) static
Definition at line 602 of file MIRPrinter.cpp.
References llvm::yaml::MachineConstantPoolValue::Alignment, llvm::yaml::MachineFunction::Constants, llvm::yaml::MachineConstantPoolValue::ID, llvm::yaml::MachineConstantPoolValue::IsTargetSpecific, llvm::Value::print(), llvm::Value::printAsOperand(), and llvm::yaml::MachineConstantPoolValue::Value.
Referenced by printMF().
convertMFI()
void convertMFI (ModuleSlotTracker & MST, yaml::MachineFrameInfo & YamlMFI, const MachineFrameInfo & MFI, const TargetRegisterInfo * TRI) static
Definition at line 344 of file MIRPrinter.cpp.
References llvm::yaml::MachineFrameInfo::AdjustsStack, llvm::MachineFrameInfo::adjustsStack(), convertSRPoints(), llvm::yaml::MachineFrameInfo::CVBytesOfCalleeSavedRegisters, llvm::MachineFrameInfo::getCVBytesOfCalleeSavedRegisters(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineFrameInfo::getMaxAlign(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::MachineFrameInfo::getOffsetAdjustment(), llvm::MachineFrameInfo::getRestorePoints(), llvm::MachineFrameInfo::getSavePoints(), llvm::MachineFrameInfo::getStackSize(), llvm::yaml::MachineFrameInfo::HasCalls, llvm::MachineFrameInfo::hasCalls(), llvm::yaml::MachineFrameInfo::HasMustTailInVarArgFunc, llvm::MachineFrameInfo::hasMustTailInVarArgFunc(), llvm::yaml::MachineFrameInfo::HasOpaqueSPAdjustment, llvm::MachineFrameInfo::hasOpaqueSPAdjustment(), llvm::yaml::MachineFrameInfo::HasPatchPoint, llvm::MachineFrameInfo::hasPatchPoint(), llvm::yaml::MachineFrameInfo::HasStackMap, llvm::MachineFrameInfo::hasStackMap(), llvm::yaml::MachineFrameInfo::HasTailCall, llvm::MachineFrameInfo::hasTailCall(), llvm::yaml::MachineFrameInfo::HasVAStart, llvm::MachineFrameInfo::hasVAStart(), llvm::yaml::MachineFrameInfo::IsCalleeSavedInfoValid, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), llvm::yaml::MachineFrameInfo::IsFrameAddressTaken, llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::MachineFrameInfo::isMaxCallFrameSizeComputed(), llvm::yaml::MachineFrameInfo::IsReturnAddressTaken, llvm::MachineFrameInfo::isReturnAddressTaken(), llvm::yaml::MachineFrameInfo::LocalFrameSize, llvm::yaml::MachineFrameInfo::MaxAlignment, llvm::yaml::MachineFrameInfo::MaxCallFrameSize, llvm::yaml::MachineFrameInfo::OffsetAdjustment, llvm::yaml::MachineFrameInfo::RestorePoints, llvm::yaml::MachineFrameInfo::SavePoints, llvm::yaml::MachineFrameInfo::StackSize, TRI, and llvm::Align::value().
Referenced by printMF().
convertMJTI()
void convertMJTI (ModuleSlotTracker & MST, yaml::MachineJumpTable & YamlJTI, const MachineJumpTableInfo & JTI) static
Definition at line 657 of file MIRPrinter.cpp.
References llvm::yaml::MachineJumpTable::Entries, llvm::MachineJumpTableInfo::getEntryKind(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::yaml::MachineJumpTable::Entry::ID, llvm::yaml::MachineJumpTable::Kind, MBB, and llvm::printMBBReference().
Referenced by printMF().
convertMRI()
void convertMRI (yaml::MachineFunction & YamlMF, const MachineFunction & MF, const MachineRegisterInfo & RegInfo, const TargetRegisterInfo * TRI) static
Definition at line 302 of file MIRPrinter.cpp.
References llvm::yaml::MachineFunction::CalleeSavedRegisters, llvm::yaml::VirtualRegisterDefinition::Class, E(), I, llvm::yaml::VirtualRegisterDefinition::ID, llvm::Register::index2VirtReg(), llvm::yaml::MachineFunction::LiveIns, llvm::yaml::VirtualRegisterDefinition::PreferredRegister, llvm::printRegClassOrBank(), printRegFlags(), printRegMIR(), Reg, llvm::yaml::MachineFunctionLiveIn::Register, llvm::yaml::VirtualRegisterDefinition::RegisterFlags, llvm::yaml::MachineFunction::TracksRegLiveness, TRI, llvm::yaml::MachineFunctionLiveIn::VirtualRegister, and llvm::yaml::MachineFunction::VirtualRegisters.
Referenced by printMF().
convertSRPoints()
void convertSRPoints (ModuleSlotTracker & MST, std::vector< yaml::SaveRestorePointEntry > & YamlSRPoints, const llvm::SaveRestorePoints & SRPoints, const TargetRegisterInfo * TRI) static
Definition at line 624 of file MIRPrinter.cpp.
References Info, MBB, llvm::printMBBReference(), llvm::printReg(), llvm::raw_svector_ostream::str(), llvm::StringRef::str(), and TRI.
Referenced by convertMFI().
convertStackObjects()
void convertStackObjects (yaml::MachineFunction & YMF, const MachineFunction & MF, ModuleSlotTracker & MST, MFPrintState & State) static
Definition at line 396 of file MIRPrinter.cpp.
References llvm::yaml::FixedMachineStackObject::Alignment, llvm::yaml::MachineStackObject::Alignment, assert(), llvm::yaml::FixedMachineStackObject::DefaultType, llvm::yaml::MachineStackObject::DefaultType, E(), llvm::yaml::MachineFunction::FixedStackObjects, llvm::yaml::MachineFunction::FrameInfo, llvm::yaml::MachineFrameInfo::FunctionContext, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getFunctionContextIndex(), llvm::MachineFunction::getInStackSlotVariableDbgInfo(), llvm::MachineFrameInfo::getLocalFrameObjectCount(), llvm::MachineFrameInfo::getLocalFrameObjectMap(), llvm::MachineFrameInfo::getNumFixedObjects(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectAllocation(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackID(), llvm::MachineFrameInfo::getStackProtectorIndex(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasFunctionContextIndex(), llvm::MachineFrameInfo::hasStackProtectorIndex(), I, llvm::yaml::FixedMachineStackObject::ID, llvm::yaml::MachineStackObject::ID, llvm::yaml::FixedMachineStackObject::IsAliased, llvm::MachineFrameInfo::isAliasedObjectIndex(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::yaml::FixedMachineStackObject::IsImmutable, llvm::MachineFrameInfo::isImmutableObjectIndex(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::MachineFrameInfo::isVariableSizedObjectIndex(), llvm::yaml::MachineStackObject::Name, llvm::yaml::FixedMachineStackObject::Offset, llvm::yaml::MachineStackObject::Offset, printRegMIR(), printStackObjectDbgInfo(), printStackObjectReference(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::SmallVectorImpl< T >::reserve(), llvm::yaml::FixedMachineStackObject::Size, llvm::yaml::MachineStackObject::Size, llvm::yaml::FixedMachineStackObject::SpillSlot, llvm::yaml::MachineStackObject::SpillSlot, llvm::yaml::FixedMachineStackObject::StackID, llvm::yaml::MachineStackObject::StackID, llvm::yaml::MachineFunction::StackObjects, llvm::yaml::MachineFrameInfo::StackProtector, TRI, llvm::yaml::FixedMachineStackObject::Type, llvm::yaml::MachineStackObject::Type, llvm::yaml::StringValue::Value, and llvm::yaml::MachineStackObject::VariableSized.
Referenced by printMF().
formatOperandComment()
std::string formatOperandComment (std::string Comment) static
Definition at line 929 of file MIRPrinter.cpp.
Referenced by printMIOperand().
initRegisterMaskIds()
DenseMap< const uint32_t *, unsigned > initRegisterMaskIds (const MachineFunction & MF) static
Definition at line 132 of file MIRPrinter.cpp.
References llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), and TRI.
Referenced by printMF().
printCustomRegMask()
void printCustomRegMask (const uint32_t * RegMask, raw_ostream & OS, const TargetRegisterInfo * TRI) static
Definition at line 251 of file MIRPrinter.cpp.
References assert(), E(), I, llvm::printReg(), and TRI.
Referenced by printMIOperand().
printMBB()
void printMBB (raw_ostream & OS, MFPrintState & State, const MachineBasicBlock & MBB) static
Definition at line 725 of file MIRPrinter.cpp.
References assert(), llvm::MachineInstr::BundledSucc, canPredictSuccessors(), E(), llvm::format(), I, llvm::raw_ostream::indent(), MBB, MI, MRI, llvm::PrintLaneMask(), llvm::printMBBReference(), printMI(), llvm::MachineBasicBlock::PrintNameAttributes, llvm::MachineBasicBlock::PrintNameIr, llvm::printReg(), SimplifyMIR, and TRI.
Referenced by printMF().
printMF()
void printMF (raw_ostream & OS, MFGetterFnT Fn, const MachineFunction & MF) static
Definition at line 174 of file MIRPrinter.cpp.
References llvm::yaml::MachineFunction::Alignment, llvm::yaml::MachineFunction::Body, llvm::yaml::MachineFunction::CallsEHReturn, llvm::MachineFunction::callsEHReturn(), llvm::yaml::MachineFunction::CallsUnwindInit, llvm::MachineFunction::callsUnwindInit(), convertCalledGlobals(), convertCallSiteObjects(), convertEntryValueObjects(), llvm::TargetMachine::convertFuncInfoToYAML(), convertMachineMetadataNodes(), convertMCP(), convertMFI(), convertMJTI(), convertMRI(), convertStackObjects(), llvm::MachineFunction::DebugValueSubstitutions, llvm::yaml::MachineFunction::DebugValueSubstitutions, llvm::yaml::MachineFunction::ExposesReturnsTwice, llvm::MachineFunction::exposesReturnsTwice(), llvm::yaml::MachineFunction::FailedISel, llvm::yaml::MachineFunction::FailsVerification, llvm::yaml::MachineFunction::FrameInfo, llvm::MachineFunction::getAlignment(), llvm::MachineFunction::getConstantPool(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineFunction::getName(), llvm::MachineFunction::getProperties(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::yaml::MachineFunction::HasEHContTarget, llvm::MachineFunction::hasEHContTarget(), llvm::yaml::MachineFunction::HasEHFunclets, llvm::MachineFunction::hasEHFunclets(), llvm::yaml::MachineFunction::HasEHScopes, llvm::MachineFunction::hasEHScopes(), llvm::yaml::MachineFunction::HasFakeUses, llvm::MachineFunction::hasFakeUses(), llvm::yaml::MachineFunction::HasWinCFI, llvm::MachineFunction::hasWinCFI(), llvm::ModuleSlotTracker::incorporateFunction(), initRegisterMaskIds(), llvm::yaml::MachineFunction::IsOutlined, llvm::MachineFunction::isOutlined(), llvm::yaml::MachineFunction::IsSSA, llvm::yaml::MachineFunction::JumpTableInfo, llvm::yaml::MachineFunction::Legalized, llvm::yaml::MachineFunction::MachineFuncInfo, MBB, llvm::yaml::MachineFunction::Name, llvm::yaml::MachineFunction::NoPHIs, llvm::yaml::MachineFunction::NoVRegs, printMBB(), llvm::yaml::MachineFunction::RegBankSelected, llvm::yaml::MachineFunction::Selected, llvm::yaml::Output::setWriteDefaultValues(), SimplifyMIR, llvm::Sub, llvm::yaml::MachineFunction::TracksDebugUserValues, llvm::yaml::MachineFunction::UseDebugInstrRef, llvm::MachineFunction::useDebugInstrRef(), llvm::yaml::BlockStringValue::Value, and llvm::yaml::StringValue::Value.
Referenced by llvm::printMIR(), and llvm::printMIR().
printMI()
void printMI (raw_ostream & OS, MFPrintState & State, const MachineInstr & MI) static
Definition at line 794 of file MIRPrinter.cpp.
References assert(), llvm::MachineInstr::Disjoint, DL, E(), llvm::MachineInstr::FmAfn, llvm::MachineInstr::FmArcp, llvm::MachineInstr::FmContract, llvm::MachineInstr::FmNoInfs, llvm::MachineInstr::FmNoNans, llvm::MachineInstr::FmNsz, llvm::MachineInstr::FmReassoc, llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, I, llvm::MachineInstr::InBounds, llvm::MachineOperand::isDef(), llvm::MachineInstr::IsExact, llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), MI, MRI, llvm::MachineInstr::NoConvergent, llvm::MachineInstr::NoFPExcept, llvm::MachineInstr::NoMerge, llvm::MachineInstr::NonNeg, llvm::MachineInstr::NoSWrap, llvm::MachineInstr::NoUSWrap, llvm::MachineInstr::NoUWrap, llvm::MIRFormatter::printIRValue(), PrintLocations, printMIOperand(), llvm::MachineOperand::printSymbol(), llvm::MachineInstr::SameSign, TII, TRI, and llvm::MachineInstr::Unpredictable.
Referenced by printMBB().
printMIOperand()
void printMIOperand (raw_ostream & OS, MFPrintState & State, const MachineInstr & MI, unsigned OpIdx, const TargetRegisterInfo * TRI, const TargetInstrInfo * TII, bool ShouldPrintRegisterTies, SmallBitVector & PrintedTypes, const MachineRegisterInfo & MRI, bool PrintDef) static
Definition at line 935 of file MIRPrinter.cpp.
References formatOperandComment(), llvm::StringRef::lower(), MI, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_CFIIndex, llvm::MachineOperand::MO_CImmediate, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_DbgInstrRef, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_FrameIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_IntrinsicID, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_LaneMask, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_MCSymbol, llvm::MachineOperand::MO_Metadata, llvm::MachineOperand::MO_Predicate, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterLiveOut, llvm::MachineOperand::MO_RegisterMask, llvm::MachineOperand::MO_ShuffleMask, llvm::MachineOperand::MO_TargetIndex, MRI, OpIdx, printCustomRegMask(), printStackObjectReference(), llvm::MachineOperand::printSubRegIdx(), llvm::MachineOperand::printTargetFlags(), TII, and TRI.
Referenced by printMI().
printRegClassOrBank()
void printRegClassOrBank (Register Reg, yaml::StringValue & Dest, const MachineRegisterInfo & RegInfo, const TargetRegisterInfo * TRI) static
Definition at line 270 of file MIRPrinter.cpp.
References llvm::printRegClassOrBank(), Reg, TRI, and llvm::yaml::StringValue::Value.
printRegFlags()
void printRegFlags (Register Reg, std::vector< yaml::FlowStringValue > & RegisterFlags, const MachineFunction & MF, const TargetRegisterInfo * TRI) static
Definition at line 293 of file MIRPrinter.cpp.
References Reg, and TRI.
Referenced by convertMRI().
printRegMIR()
void printRegMIR (Register Reg, yaml::StringValue & Dest, const TargetRegisterInfo * TRI) static
Definition at line 125 of file MIRPrinter.cpp.
References llvm::printReg(), Reg, TRI, and llvm::yaml::StringValue::Value.
Referenced by convertCallSiteObjects(), convertEntryValueObjects(), convertMRI(), and convertStackObjects().
printStackObjectDbgInfo()
template<typename T> void printStackObjectDbgInfo (const MachineFunction::VariableDbgInfo & DebugVar, T & Object, ModuleSlotTracker & MST) static
Definition at line 279 of file MIRPrinter.cpp.
References llvm::MachineFunction::VariableDbgInfo::Expr, llvm::MachineFunction::VariableDbgInfo::Loc, T, and llvm::MachineFunction::VariableDbgInfo::Var.
Referenced by convertEntryValueObjects(), and convertStackObjects().
printStackObjectReference()
void printStackObjectReference (raw_ostream & OS, const MFPrintState & State, int FrameIndex) static
Definition at line 385 of file MIRPrinter.cpp.
References assert(), and llvm::MachineOperand::printStackObjectReference().
Referenced by convertStackObjects(), and printMIOperand().
Variable Documentation
PrintLocations
cl::opt< bool > PrintLocations("mir-debug-loc", cl::Hidden, cl::init(true), cl::desc("Print MIR debug-locations")) ("mir-debug-loc" , cl::Hidden , cl::init(true) , cl::desc("Print MIR debug-locations")) static
Referenced by printMI().
SimplifyMIR
cl::opt< bool > SimplifyMIR("simplify-mir", cl::Hidden, cl::desc("Leave out unnecessary information when printing MIR")) ("simplify-mir" , cl::Hidden , cl::desc("Leave out unnecessary information when printing MIR")) static
Referenced by printMBB(), and printMF().