LLVM: lib/Target/MSP430/MSP430TargetMachine.cpp File Reference
MSP430TargetMachine.cpp File Reference
#include "MSP430TargetMachine.h"
#include "MSP430.h"
#include "MSP430MachineFunctionInfo.h"
#include "TargetInfo/MSP430TargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include <optional>
Functions
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430Target ()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
Function Documentation
getEffectiveRelocModel()
Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 33 of file MSP430TargetMachine.cpp.
References llvm::Reloc::Static.
LLVMInitializeMSP430Target()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430Target ()
Definition at line 25 of file MSP430TargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheMSP430Target(), llvm::initializeMSP430AsmPrinterPass(), llvm::initializeMSP430DAGToDAGISelLegacyPass(), LLVM_ABI, LLVM_EXTERNAL_VISIBILITY, and X.