LLVM: lib/Target/ARM/MVEGatherScatterLowering.cpp File Reference
MVEGatherScatterLowering.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMSubtarget.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Transforms/Utils/Local.h"
#include <cassert>
Macros
#define DEBUG_TYPE "arm-mve-gather-scatter-lowering"
Functions
INITIALIZE_PASS (MVEGatherScatterLowering, DEBUG_TYPE, "MVE gather/scattering lowering pass", false, false) Pass *llvm
static bool checkOffsetSize (Value *Offsets, unsigned TargetElemCount)
static bool isAddLikeOr (Instruction *I, const DataLayout &DL)
static bool hasAllGatScatUsers (Instruction *I, const DataLayout &DL)
static Value * CheckAndCreateOffsetAdd (Value *X, unsigned ScaleX, Value *Y, unsigned ScaleY, IRBuilder<> &Builder)
Variables
cl::opt< bool > EnableMaskedGatherScatters ("enable-arm-maskedgatscat", cl::Hidden, cl::init(true), cl::desc("Enable the generation of masked gathers and scatters"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-mve-gather-scatter-lowering"
Definition at line 47 of file MVEGatherScatterLowering.cpp.
Function Documentation
CheckAndCreateOffsetAdd()
Value * CheckAndCreateOffsetAdd (Value * X, unsigned ScaleX, Value * Y, unsigned ScaleY, IRBuilder<> & Builder) static
Definition at line 1114 of file MVEGatherScatterLowering.cpp.
References llvm::Add, assert(), llvm::cast(), checkOffsetSize(), llvm::dbgs(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::VectorType::getElementType(), llvm::FixedVectorType::getNumElements(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::ConstantInt::getZExtValue(), LLVM_DEBUG, N, X, and Y.
checkOffsetSize()
bool checkOffsetSize (Value * Offsets, unsigned TargetElemCount) static
Definition at line 184 of file MVEGatherScatterLowering.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::ConstantInt::getSExtValue(), llvm::Value::getType(), and llvm::isa().
Referenced by CheckAndCreateOffsetAdd().
hasAllGatScatUsers()
bool hasAllGatScatUsers (Instruction * I, const DataLayout & DL) static
Definition at line 949 of file MVEGatherScatterLowering.cpp.
References llvm::cast(), DL, llvm::dyn_cast(), hasAllGatScatUsers(), I, llvm::isa(), isAddLikeOr(), and llvm::isGatherScatter().
Referenced by hasAllGatScatUsers().
INITIALIZE_PASS()
INITIALIZE_PASS (MVEGatherScatterLowering , DEBUG_TYPE , "MVE gather/scattering lowering pass" , false , false)
Definition at line 163 of file MVEGatherScatterLowering.cpp.
References llvm::createMVEGatherScatterLoweringPass(), and DEBUG_TYPE.
isAddLikeOr()
bool isAddLikeOr (Instruction * I, const DataLayout & DL) static
Definition at line 366 of file MVEGatherScatterLowering.cpp.
References DL, llvm::haveNoCommonBitsSet(), and I.
Referenced by hasAllGatScatUsers().
Variable Documentation
EnableMaskedGatherScatters
cl::opt< bool > EnableMaskedGatherScatters("enable-arm-maskedgatscat", cl::Hidden, cl::init(true), cl::desc("Enable the generation of masked gathers and scatters")) ("enable-arm-maskedgatscat" , cl::Hidden , cl::init(true) , cl::desc("Enable the generation of masked gathers and scatters"))