LLVM: llvm::AArch64_IMM Namespace Reference
llvm::AArch64_IMM Namespace Reference
Classes
struct ImmInsnModel
Functions
void expandMOVImm (uint64_t Imm, unsigned BitSize, SmallVectorImpl< ImmInsnModel > &Insn)
Expand a MOVi32imm or MOVi64imm pseudo instruction to one or more real move-immediate instructions to synthesize the immediate.
Function Documentation
expandMOVImm()
void llvm::AArch64_IMM::expandMOVImm (uint64_t Imm, unsigned BitSize, SmallVectorImpl< ImmInsnModel > & Insn)
Expand a MOVi32imm or MOVi64imm pseudo instruction to one or more real move-immediate instructions to synthesize the immediate.
Definition at line 598 of file AArch64ExpandImm.cpp.
References assert(), expandMOVImmSimple(), getChunk(), llvm::AArch64_AM::getShifterImm(), llvm::AArch64_AM::LSL, Opc, llvm::AArch64_AM::processLogicalImmediate(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::rotl(), llvm::SmallVectorTemplateCommon< T, typename >::size(), tryAndOfLogicalImmediates(), tryCopyWithNegation(), tryEorOfLogicalImmediates(), tryOrrOfLogicalImmediates(), trySequenceOfOnes(), and tryToreplicateChunks().
Referenced by llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::AArch64TTIImpl::getIntImmCost(), isCheapImmediate(), llvm::AArch64TargetLowering::isFPImmLegal(), llvm::AArch64TargetLowering::isMulAddWithConstProfitable(), numberOfInstrToLoadImm(), and splitAddSubImm().