LLVM: llvm::remarks Namespace Reference
llvm::remarks Namespace Reference
Classes
struct BitstreamRemarkSerializerHelper
Serialize the remarks to LLVM bitstream.
struct BitstreamRemarkSerializer
Implementation of the remark serializer using LLVM bitstream.
struct BitstreamMetaSerializer
Serializer of metadata for bitstream remarks.
class HotnessThresholdParser
struct RemarkLocation
The debug location used to track a remark back to the source file.
struct Argument
A key-value pair with a debug location that is used to display the remarks at the right place in the source.
struct Remark
A remark type used for both emission and parsing.
struct RemarkLinker
class EndOfFileError
struct RemarkParser
Parser used to parse a raw buffer to remarks::Remark objects.
struct ParsedStringTable
In-memory representation of the string table parsed from a buffer (e.g.
struct RemarkSerializer
This is the base class for a remark serializer.
struct MetaSerializer
This is the base class for a remark metadata serializer.
class RemarkStreamer
struct StringTable
The string table used for serializing remarks.
struct YAMLRemarkSerializer
Serialize the remarks to YAML.
struct YAMLMetaSerializer
class BitstreamBlockParserHelperBase
class BitstreamBlockParserHelper
class BitstreamMetaParserHelper
Helper to parse a META_BLOCK for a bitstream remark container.
class BitstreamRemarkParserHelper
Helper to parse a REMARK_BLOCK for a bitstream remark container.
struct BitstreamParserHelper
Helper to parse any bitstream remark container.
struct BitstreamRemarkParser
Parses and holds the state of the latest parsed remark.
class YAMLParseError
struct YAMLRemarkParser
Regular YAML to Remark parser.
Enumerations
enum class BitstreamRemarkContainerType { RemarksFileExternal , RemarksFile , First = RemarksFileExternal , Last = RemarksFile }
Type of the remark container.
enum BlockIDs { META_BLOCK_ID = bitc::FIRST_APPLICATION_BLOCKID , REMARK_BLOCK_ID }
The possible blocks that will be encountered in a bitstream remark container.
enum RecordIDs {
RECORD_META_CONTAINER_INFO = 1 , RECORD_META_REMARK_VERSION , RECORD_META_STRTAB , RECORD_META_EXTERNAL_FILE ,
RECORD_REMARK_HEADER , RECORD_REMARK_DEBUG_LOC , RECORD_REMARK_HOTNESS , RECORD_REMARK_ARG_WITH_DEBUGLOC ,
RECORD_REMARK_ARG_WITHOUT_DEBUGLOC , RECORD_FIRST = RECORD_META_CONTAINER_INFO , RECORD_LAST = RECORD_REMARK_ARG_WITHOUT_DEBUGLOC
}
The possible records that can be encountered in the previously described blocks.
enum class Type {
Unknown , Passed , Missed , Analysis ,
AnalysisFPCommute , AnalysisAliasing , Failure , First = Unknown ,
Last = Failure
}
The type of the remark.
enum class Format { Unknown , Auto , YAML , Bitstream }
The format used for serializing/deserializing remarks.
Functions
constexpr StringLiteral ContainerMagic ("RMRK")
The magic number used for identifying remark blocks.
constexpr StringLiteral MetaBlockName ("Meta")
constexpr StringLiteral RemarkBlockName ("Remark")
constexpr StringLiteral MetaContainerInfoName ("Container info")
constexpr StringLiteral MetaRemarkVersionName ("Remark version")
constexpr StringLiteral MetaStrTabName ("String table")
constexpr StringLiteral MetaExternalFileName ("External File")
constexpr StringLiteral RemarkHeaderName ("Remark header")
constexpr StringLiteral RemarkDebugLocName ("Remark debug location")
constexpr StringLiteral RemarkHotnessName ("Remark hotness")
constexpr StringLiteral RemarkArgWithDebugLocName ("Argument with debug location")
constexpr StringLiteral RemarkArgWithoutDebugLocName ("Argument")
Expected< std::optional< uint64_t > > parseHotnessThresholdOption (StringRef Arg)
StringRef typeToStr (Type Ty)
template<typename T>
bool operator< (const std::optional< T > &LHS, const std::optional< T > &RHS)
Comparison operators for Remark objects and dependent objects.
bool operator== (const RemarkLocation &LHS, const RemarkLocation &RHS)
bool operator!= (const RemarkLocation &LHS, const RemarkLocation &RHS)
bool operator< (const RemarkLocation &LHS, const RemarkLocation &RHS)
bool operator== (const Argument &LHS, const Argument &RHS)
bool operator!= (const Argument &LHS, const Argument &RHS)
bool operator< (const Argument &LHS, const Argument &RHS)
bool operator== (const Remark &LHS, const Remark &RHS)
bool operator!= (const Remark &LHS, const Remark &RHS)
bool operator< (const Remark &LHS, const Remark &RHS)
raw_ostream & operator<< (raw_ostream &OS, const RemarkLocation &RLoc)
raw_ostream & operator<< (raw_ostream &OS, const Argument &Arg)
raw_ostream & operator<< (raw_ostream &OS, const Remark &Remark)
constexpr StringLiteral Magic ("REMARKS")
LLVM_ABI Expected< Format > parseFormat (StringRef FormatStr)
Parse and validate a string for the remark format.
LLVM_ABI Expected< Format > magicToFormat (StringRef Magic)
Parse and validate a magic number to a remark format.
LLVM_ABI Expected< Format > detectFormat (Format Selected, StringRef Magic)
Detect format based on selected format and magic number.
LLVM_ABI Expected< std::optional< StringRef > > getRemarksSectionContents (const object::ObjectFile &Obj)
Returns a buffer with the contents of the remarks section depending on the format of the file.
LLVM_ABI Expected< std::unique_ptr< RemarkParser > > createRemarkParser (Format ParserFormat, StringRef Buf)
LLVM_ABI Expected< std::unique_ptr< RemarkParser > > createRemarkParserFromMeta (Format ParserFormat, StringRef Buf, std::optional< StringRef > ExternalFilePrependPath=std::nullopt)
LLVM_ABI Expected< std::unique_ptr< RemarkSerializer > > createRemarkSerializer (Format RemarksFormat, raw_ostream &OS)
Create a remark serializer.
LLVM_ABI Expected< std::unique_ptr< RemarkSerializer > > createRemarkSerializer (Format RemarksFormat, raw_ostream &OS, remarks::StringTable StrTab)
Create a remark serializer that uses a pre-filled string table.
Expected< std::unique_ptr< BitstreamRemarkParser > > createBitstreamParserFromMeta (StringRef Buf, std::optional< StringRef > ExternalFilePrependPath=std::nullopt)
Expected< std::unique_ptr< YAMLRemarkParser > > createYAMLParserFromMeta (StringRef Buf, std::optional< StringRef > ExternalFilePrependPath=std::nullopt)
Variables
constexpr uint64_t CurrentContainerVersion = 1
The current version of the remark container.
constexpr uint64_t CurrentRemarkVersion = 0
The current version of the remark entry.
Enumeration Type Documentation
BitstreamRemarkContainerType
enum class llvm::remarks::BitstreamRemarkContainerType strong
Type of the remark container.
Enumerator
RemarksFileExternal
Emit a link to an external remarks file (usually as a section of the object file, to enable discovery of all remarks files from the final linked object file) RemarksFileExternal: | Meta: | | Container info | | External file.
RemarksFile
Emit metadata and remarks into a file RemarksFile: | Meta: | | Container info | | Remark version | Remarks: | | Remark0 | | Remark1 | | Remark2 | | ... | Late Meta: | | String table.
First
Last
Definition at line 31 of file BitstreamRemarkContainer.h.
BlockIDs
enum llvm::remarks::BlockIDs
The possible blocks that will be encountered in a bitstream remark container.
Enumerator
META_BLOCK_ID
The metadata block is mandatory.
It should always come after the BLOCKINFO_BLOCK, and contains metadata that should be used when parsing REMARK_BLOCKs. There should always be only one META_BLOCK.
REMARK_BLOCK_ID
One remark entry is represented using a REMARK_BLOCK.
There can be multiple REMARK_BLOCKs in the same file.
Definition at line 59 of file BitstreamRemarkContainer.h.
Format
enum class llvm::remarks::Format strong
The format used for serializing/deserializing remarks.
Enumerator
Unknown
Auto
YAML
Bitstream
Definition at line 26 of file RemarkFormat.h.
RecordIDs
enum llvm::remarks::RecordIDs
The possible records that can be encountered in the previously described blocks.
Enumerator
RECORD_META_CONTAINER_INFO
RECORD_META_REMARK_VERSION
RECORD_META_STRTAB
RECORD_META_EXTERNAL_FILE
RECORD_REMARK_HEADER
RECORD_REMARK_DEBUG_LOC
RECORD_REMARK_HOTNESS
RECORD_REMARK_ARG_WITH_DEBUGLOC
RECORD_REMARK_ARG_WITHOUT_DEBUGLOC
RECORD_FIRST
RECORD_LAST
Definition at line 75 of file BitstreamRemarkContainer.h.
Type
enum class llvm::remarks::Type strong
The type of the remark.
MessagePack types as defined in the standard, with the exception of Integer being divided into a signed Int and unsigned UInt variant in order to map directly to C++ types.
The types map onto corresponding union members of the Object struct.
Enumerator
Unknown
Passed
Missed
Analysis
AnalysisFPCommute
AnalysisAliasing
Failure
First
Last
Definition at line 75 of file Remark.h.
Function Documentation
ContainerMagic()
StringLiteral llvm::remarks::ContainerMagic ("RMRK") constexpr
The magic number used for identifying remark blocks.
Referenced by llvm::remarks::BitstreamParserHelper::expectMagic(), magicToFormat(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupBlockInfo().
createBitstreamParserFromMeta()
Expected< std::unique_ptr< BitstreamRemarkParser > > llvm::remarks::createBitstreamParserFromMeta (StringRef Buf, std::optional< StringRef > ExternalFilePrependPath = std::nullopt)
Definition at line 294 of file BitstreamRemarkParser.cpp.
Referenced by createRemarkParserFromMeta().
createRemarkParser()
Expected< std::unique_ptr< RemarkParser > > llvm::remarks::createRemarkParser (Format ParserFormat, StringRef Buf)
Definition at line 53 of file RemarkParser.cpp.
References Auto, Bitstream, detectFormat(), llvm_unreachable, Unknown, and YAML.
createRemarkParserFromMeta()
Expected< std::unique_ptr< RemarkParser > > llvm::remarks::createRemarkParserFromMeta (Format ParserFormat, StringRef Buf, std::optional< StringRef > ExternalFilePrependPath = std::nullopt)
Definition at line 71 of file RemarkParser.cpp.
References Auto, Bitstream, createBitstreamParserFromMeta(), createYAMLParserFromMeta(), detectFormat(), llvm_unreachable, Unknown, and YAML.
Referenced by llvm::remarks::RemarkLinker::link().
createRemarkSerializer() [1/2]
Expected< std::unique_ptr< RemarkSerializer > > llvm::remarks::createRemarkSerializer (Format RemarksFormat, raw_ostream & OS)
Create a remark serializer.
Definition at line 21 of file RemarkSerializer.cpp.
References Auto, Bitstream, llvm::createStringError(), llvm_unreachable, llvm::RemarksFormat, Unknown, and YAML.
Referenced by llvm::remarks::RemarkLinker::serialize(), llvm::setupLLVMOptimizationRemarks(), and llvm::setupLLVMOptimizationRemarks().
createRemarkSerializer() [2/2]
Expected< std::unique_ptr< RemarkSerializer > > llvm::remarks::createRemarkSerializer (Format RemarksFormat, raw_ostream & OS, remarks::StringTable StrTab)
Create a remark serializer that uses a pre-filled string table.
Definition at line 36 of file RemarkSerializer.cpp.
References Auto, Bitstream, llvm::createStringError(), llvm_unreachable, llvm::RemarksFormat, Unknown, and YAML.
createYAMLParserFromMeta()
Expected< std::unique_ptr< YAMLRemarkParser > > llvm::remarks::createYAMLParserFromMeta (StringRef Buf, std::optional< StringRef > ExternalFilePrependPath = std::nullopt)
Definition at line 98 of file YAMLRemarkParser.cpp.
References llvm::sys::path::append(), llvm::createFileError(), llvm::createStringError(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), parseMagic(), parseStrTabSize(), parseVersion(), llvm::StringRef::starts_with(), llvm::Expected< T >::takeError(), and llvm::Version.
Referenced by createRemarkParserFromMeta().
detectFormat()
Expected< Format > llvm::remarks::detectFormat (Format Selected, StringRef Magic)
Detect format based on selected format and magic number.
Definition at line 51 of file RemarkFormat.cpp.
References Auto, Bitstream, llvm::createStringError(), llvm::StringRef::empty(), magicToFormat(), and Unknown.
Referenced by createRemarkParser(), and createRemarkParserFromMeta().
getRemarksSectionContents()
Expected< std::optional< StringRef > > llvm::remarks::getRemarksSectionContents (const object::ObjectFile & Obj)
Returns a buffer with the contents of the remarks section depending on the format of the file.
If the section doesn't exist, this returns an empty optional.
Definition at line 39 of file RemarkLinker.cpp.
References getRemarksSectionName(), and llvm::Expected< T >::takeError().
Referenced by llvm::remarks::RemarkLinker::link().
Magic()
StringLiteral llvm::remarks::Magic ("REMARKS") constexpr
Referenced by emitMagic(), magicToFormat(), and parseMagic().
magicToFormat()
Expected< Format > llvm::remarks::magicToFormat (StringRef Magic)
Parse and validate a magic number to a remark format.
Definition at line 34 of file RemarkFormat.cpp.
References Bitstream, ContainerMagic(), llvm::createStringError(), llvm::StringRef::data(), llvm::StringSwitch< T, R >::Default(), Magic(), llvm::StringSwitch< T, R >::StartsWith(), Unknown, and YAML.
Referenced by detectFormat().
MetaBlockName()
StringLiteral llvm::remarks::MetaBlockName ("Meta") constexpr
Referenced by llvm::remarks::BitstreamMetaParserHelper::BitstreamMetaParserHelper(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaBlockInfo().
MetaContainerInfoName()
StringLiteral llvm::remarks::MetaContainerInfoName ("Container info") constexpr
Referenced by llvm::remarks::BitstreamMetaParserHelper::parseRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaBlockInfo().
MetaExternalFileName()
StringLiteral llvm::remarks::MetaExternalFileName ("External File") constexpr
Referenced by llvm::remarks::BitstreamMetaParserHelper::parseRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaExternalFile().
MetaRemarkVersionName()
StringLiteral llvm::remarks::MetaRemarkVersionName ("Remark version") constexpr
Referenced by llvm::remarks::BitstreamMetaParserHelper::parseRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaRemarkVersion().
MetaStrTabName()
StringLiteral llvm::remarks::MetaStrTabName ("String table") constexpr
Referenced by llvm::remarks::BitstreamMetaParserHelper::parseRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupMetaStrTab().
operator!=() [1/3]
bool llvm::remarks::operator!= (const Argument & LHS, const Argument & RHS) inline
Definition at line 194 of file Remark.h.
References LHS, and RHS.
operator!=() [2/3]
bool llvm::remarks::operator!= (const Remark & LHS, const Remark & RHS) inline
Definition at line 210 of file Remark.h.
References LHS, and RHS.
operator!=() [3/3]
bool llvm::remarks::operator!= (const RemarkLocation & LHS, const RemarkLocation & RHS) inline
Definition at line 181 of file Remark.h.
References LHS, and RHS.
operator<() [1/4]
bool llvm::remarks::operator< (const Argument & LHS, const Argument & RHS) inline
Definition at line 198 of file Remark.h.
References LHS, and RHS.
operator<() [2/4]
bool llvm::remarks::operator< (const Remark & LHS, const Remark & RHS) inline
Definition at line 214 of file Remark.h.
References LHS, and RHS.
operator<() [3/4]
bool llvm::remarks::operator< (const RemarkLocation & LHS, const RemarkLocation & RHS) inline
Definition at line 185 of file Remark.h.
References LHS, and RHS.
operator<() [4/4]
template<typename T> bool llvm::remarks::operator< (const std::optional< T > & LHS, const std::optional< T > & RHS)
Comparison operators for Remark objects and dependent objects.
Definition at line 162 of file Remark.h.
References LHS, and RHS.
operator<<() [1/3]
raw_ostream & llvm::remarks::operator<< (raw_ostream & OS, const Argument & Arg) inline
Definition at line 226 of file Remark.h.
References llvm::remarks::Argument::print().
operator<<() [2/3]
raw_ostream & llvm::remarks::operator<< (raw_ostream & OS, const Remark & Remark) inline
Definition at line 231 of file Remark.h.
References llvm::remarks::Remark::print().
operator<<() [3/3]
raw_ostream & llvm::remarks::operator<< (raw_ostream & OS, const RemarkLocation & RLoc) inline
Definition at line 221 of file Remark.h.
References llvm::remarks::RemarkLocation::print().
operator==() [1/3]
bool llvm::remarks::operator== (const Argument & LHS, const Argument & RHS) inline
Definition at line 190 of file Remark.h.
References LHS, and RHS.
operator==() [2/3]
bool llvm::remarks::operator== (const Remark & LHS, const Remark & RHS) inline
Definition at line 203 of file Remark.h.
References LHS, and RHS.
operator==() [3/3]
bool llvm::remarks::operator== (const RemarkLocation & LHS, const RemarkLocation & RHS) inline
Definition at line 175 of file Remark.h.
References LHS, and RHS.
parseFormat()
Expected< Format > llvm::remarks::parseFormat (StringRef FormatStr)
Parse and validate a string for the remark format.
Definition at line 20 of file RemarkFormat.cpp.
References Bitstream, llvm::StringSwitch< T, R >::Cases(), llvm::createStringError(), llvm::StringRef::data(), llvm::StringSwitch< T, R >::Default(), Unknown, and YAML.
Referenced by llvm::setupLLVMOptimizationRemarks(), and llvm::setupLLVMOptimizationRemarks().
parseHotnessThresholdOption()
Expected< std::optional< uint64_t > > llvm::remarks::parseHotnessThresholdOption (StringRef Arg) inline
Definition at line 32 of file HotnessThresholdParser.h.
References llvm::createStringError(), llvm::StringRef::data(), llvm::StringRef::getAsInteger(), and llvm::inconvertibleErrorCode().
Referenced by llvm::remarks::HotnessThresholdParser::parse().
RemarkArgWithDebugLocName()
StringLiteral llvm::remarks::RemarkArgWithDebugLocName ("Argument with debug location") constexpr
Referenced by llvm::remarks::BitstreamRemarkParserHelper::handleRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkArgWithoutDebugLocName()
StringLiteral llvm::remarks::RemarkArgWithoutDebugLocName ("Argument") constexpr
Referenced by llvm::remarks::BitstreamRemarkParserHelper::handleRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkBlockName()
StringLiteral llvm::remarks::RemarkBlockName ("Remark") constexpr
Referenced by llvm::remarks::BitstreamRemarkParserHelper::BitstreamRemarkParserHelper(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkDebugLocName()
StringLiteral llvm::remarks::RemarkDebugLocName ("Remark debug location") constexpr
Referenced by llvm::remarks::BitstreamRemarkParserHelper::handleRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkHeaderName()
StringLiteral llvm::remarks::RemarkHeaderName ("Remark header") constexpr
Referenced by llvm::remarks::BitstreamRemarkParserHelper::handleRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
RemarkHotnessName()
StringLiteral llvm::remarks::RemarkHotnessName ("Remark hotness") constexpr
Referenced by llvm::remarks::BitstreamRemarkParserHelper::handleRecord(), and llvm::remarks::BitstreamRemarkSerializerHelper::setupRemarkBlockInfo().
typeToStr()
StringRef llvm::remarks::typeToStr (Type Ty) inline
Definition at line 87 of file Remark.h.
References Analysis, AnalysisAliasing, AnalysisFPCommute, Missed, Passed, and Unknown.
Referenced by llvm::remarks::Remark::print().
Variable Documentation
CurrentContainerVersion
uint64_t llvm::remarks::CurrentContainerVersion = 1 constexpr
The current version of the remark container.
Note: this is different from the version of the remark entry.
Definition at line 26 of file BitstreamRemarkContainer.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaBlock(), and llvm::remarks::BitstreamMetaParserHelper::parseRecord().
CurrentRemarkVersion
uint64_t llvm::remarks::CurrentRemarkVersion = 0 constexpr
The current version of the remark entry.
Definition at line 29 of file Remark.h.
Referenced by llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaBlock(), emitVersion(), llvm::remarks::BitstreamMetaParserHelper::parseRecord(), and parseVersion().