LLVM: llvm::PatternMatch Namespace Reference
llvm::PatternMatch Namespace Reference
Classes
struct MatchFunctor
struct OneUse_match
struct AllowReassoc_match
struct class_match
struct undef_match
struct constantexpr_match
struct Splat_match
struct match_unless
Inverting matcher.
struct match_combine_or
Matching combinators.
struct match_combine_and
struct ap_match
struct constantint_match
struct cstval_pred_ty
This helper class is used to match constant scalars, vector splats, and fixed width vectors that satisfy a specified predicate.
struct api_pred_ty
This helper class is used to match scalar and vector constants that satisfy a specified predicate, and bind them to an APInt.
struct apf_pred_ty
This helper class is used to match scalar and vector constants that satisfy a specified predicate, and bind them to an APFloat.
struct custom_checkfn
struct is_any_apint
struct is_shifted_mask
struct is_all_ones
struct is_maxsignedvalue
struct is_negative
struct is_nonnegative
struct is_strictlypositive
struct is_nonpositive
struct is_one
struct is_zero_int
struct is_zero
struct is_power2
struct is_negated_power2
struct is_negated_power2_or_zero
struct is_power2_or_zero
struct is_sign_mask
struct is_lowbit_mask
struct is_lowbit_mask_or_zero
struct icmp_pred_with_threshold
struct is_nan
struct is_nonnan
struct is_inf
struct is_noninf
struct is_finite
struct is_finitenonzero
struct is_any_zero_fp
struct is_pos_zero_fp
struct is_neg_zero_fp
struct is_non_zero_fp
struct is_non_zero_not_denormal_fp
struct bind_ty
struct bind_and_match_ty
Check whether the value has the given Class and matches the nested pattern.
struct immconstant_ty
struct match_immconstant_ty
struct bind_immconstant_ty
struct specificval_ty
Match a specified Value*.
struct deferredval_ty
Stores a reference to the Value *, not the Value * itself, thus can be used in commutative matchers.
struct specific_fpval
Match a specified floating point value or vector of all elements of that value.
struct bind_const_intval_ty
struct specific_intval
Match a specified integer value or vector of all elements of that value.
struct specific_intval64
struct specific_bbval
Match a specified basic block value.
struct AnyBinaryOp_match
struct AnyUnaryOp_match
struct BinaryOp_match
struct FNeg_match
struct ShiftLike_match
struct OverflowingBinaryOp_match
struct SpecificBinaryOp_match
struct DisjointOr_match
struct XorLike_match
struct BinOpPred_match
struct is_shift_op
struct is_right_shift_op
struct is_logical_shift_op
struct is_bitwiselogic_op
struct is_idiv_op
struct is_irem_op
struct Exact_match
struct CmpClass_match
struct SpecificCmpClass_match
struct OneOps_match
Matches instructions with Opcode and three operands.
struct TwoOps_match
Matches instructions with Opcode and three operands.
struct ThreeOps_match
Matches instructions with Opcode and three operands.
struct AnyOps_match
Matches instructions with Opcode and any number of operands.
struct Shuffle_match
Matches shuffle.
struct m_Mask
struct m_ZeroMask
struct m_SpecificMask
struct m_SplatOrPoisonMask
struct PtrAdd_match
struct CastOperator_match
struct CastInst_match
struct PtrToIntSameSize_match
struct NNegZExt_match
struct NoWrapTrunc_match
struct ElementWiseBitCast_match
struct br_match
struct brc_match
struct MaxMin_match
struct smax_pred_ty
Helper class for identifying signed max predicates.
struct smin_pred_ty
Helper class for identifying signed min predicates.
struct umax_pred_ty
Helper class for identifying unsigned max predicates.
struct umin_pred_ty
Helper class for identifying unsigned min predicates.
struct ofmax_pred_ty
Helper class for identifying ordered max predicates.
struct ofmin_pred_ty
Helper class for identifying ordered min predicates.
struct ufmax_pred_ty
Helper class for identifying unordered max predicates.
struct ufmin_pred_ty
Helper class for identifying unordered min predicates.
struct UAddWithOverflow_match
struct Argument_match
struct IntrinsicID_match
Intrinsic matchers.
struct m_Intrinsic_Ty
Intrinsic matches are combinations of ID matchers, and argument matchers.
struct m_Intrinsic_Ty< T0 >
struct m_Intrinsic_Ty< T0, T1 >
struct m_Intrinsic_Ty< T0, T1, T2 >
struct m_Intrinsic_Ty< T0, T1, T2, T3 >
struct m_Intrinsic_Ty< T0, T1, T2, T3, T4 >
struct m_Intrinsic_Ty< T0, T1, T2, T3, T4, T5 >
struct CommutativeBinaryIntrinsic_match
struct Signum_match
struct ExtractValue_match
struct InsertValue_match
Matcher for a single index InsertValue instruction.
struct LogicalOp_match
Typedefs
template<typename Predicate, bool AllowPoison = true>
using cst_pred_ty = cstval_pred_ty<Predicate, ConstantInt, AllowPoison>
specialization of cstval_pred_ty for ConstantInt
template<typename Predicate>
using cstfp_pred_ty
specialization of cstval_pred_ty for ConstantFP
Functions
template<typename Val, typename Pattern>
bool match (Val *V, const Pattern &P)
template<typename Val = const Value, typename Pattern>
MatchFunctor< Val, Pattern > match_fn (const Pattern &P)
A match functor that can be used as a UnaryPredicate in functional algorithms like all_of.
template<typename Pattern>
bool match (ArrayRef< int > Mask, const Pattern &P)
template<typename T>
OneUse_match< T > m_OneUse (const T &SubPattern)
template<typename T>
AllowReassoc_match< T > m_AllowReassoc (const T &SubPattern)
class_match< Value > m_Value ()
Match an arbitrary value and ignore it.
class_match< UnaryOperator > m_UnOp ()
Match an arbitrary unary operation and ignore it.
class_match< BinaryOperator > m_BinOp ()
Match an arbitrary binary operation and ignore it.
class_match< CmpInst > m_Cmp ()
Matches any compare instruction and ignore it.
auto m_Undef ()
Match an arbitrary undef constant.
class_match< UndefValue > m_UndefValue ()
Match an arbitrary UndefValue constant.
class_match< PoisonValue > m_Poison ()
Match an arbitrary poison constant.
class_match< Constant > m_Constant ()
Match an arbitrary Constant and ignore it.
class_match< ConstantInt > m_ConstantInt ()
Match an arbitrary ConstantInt and ignore it.
class_match< ConstantFP > m_ConstantFP ()
Match an arbitrary ConstantFP and ignore it.
constantexpr_match m_ConstantExpr ()
Match a constant expression or a constant that contains a constant expression.
template<typename T>
Splat_match< T > m_ConstantSplat (const T &SubPattern)
Match a constant splat. TODO: Extend this to non-constant splats.
class_match< BasicBlock > m_BasicBlock ()
Match an arbitrary basic block value and ignore it.
template<typename Ty>
match_unless< Ty > m_Unless (const Ty &M)
Match if the inner matcher does NOT match.
template<typename LTy, typename RTy>
match_combine_or< LTy, RTy > m_CombineOr (const LTy &L, const RTy &R)
Combine two pattern matchers matching L || R.
template<typename LTy, typename RTy>
match_combine_and< LTy, RTy > m_CombineAnd (const LTy &L, const RTy &R)
Combine two pattern matchers matching L && R.
ap_match< APInt > m_APInt (const APInt *&Res)
Match a ConstantInt or splatted ConstantVector, binding the specified pointer to the contained APInt.
ap_match< APInt > m_APIntAllowPoison (const APInt *&Res)
Match APInt while allowing poison in splat vector constants.
ap_match< APInt > m_APIntForbidPoison (const APInt *&Res)
Match APInt while forbidding poison in splat vector constants.
ap_match< APFloat > m_APFloat (const APFloat *&Res)
Match a ConstantFP or splatted ConstantVector, binding the specified pointer to the contained APFloat.
ap_match< APFloat > m_APFloatAllowPoison (const APFloat *&Res)
Match APFloat while allowing poison in splat vector constants.
ap_match< APFloat > m_APFloatForbidPoison (const APFloat *&Res)
Match APFloat while forbidding poison in splat vector constants.
template<int64_t Val>
constantint_match< Val > m_ConstantInt ()
Match a ConstantInt with a specific value.
cst_pred_ty< custom_checkfn< APInt > > m_CheckedInt (function_ref< bool(const APInt &)> CheckFn)
Match an integer or vector where CheckFn(ele) for each element is true.
cst_pred_ty< custom_checkfn< APInt > > m_CheckedInt (const Constant *&V, function_ref< bool(const APInt &)> CheckFn)
cstfp_pred_ty< custom_checkfn< APFloat > > m_CheckedFp (function_ref< bool(const APFloat &)> CheckFn)
Match a float or vector where CheckFn(ele) for each element is true.
cstfp_pred_ty< custom_checkfn< APFloat > > m_CheckedFp (const Constant *&V, function_ref< bool(const APFloat &)> CheckFn)
cst_pred_ty< is_any_apint > m_AnyIntegralConstant ()
Match an integer or vector with any integral constant.
cst_pred_ty< is_shifted_mask > m_ShiftedMask ()
cst_pred_ty< is_all_ones > m_AllOnes ()
Match an integer or vector with all bits set.
cst_pred_ty< is_all_ones, false > m_AllOnesForbidPoison ()
cst_pred_ty< is_maxsignedvalue > m_MaxSignedValue ()
Match an integer or vector with values having all bits except for the high bit set (0x7f...).
api_pred_ty< is_maxsignedvalue > m_MaxSignedValue (const APInt *&V)
cst_pred_ty< is_negative > m_Negative ()
Match an integer or vector of negative values.
api_pred_ty< is_negative > m_Negative (const APInt *&V)
cst_pred_ty< is_nonnegative > m_NonNegative ()
Match an integer or vector of non-negative values.
api_pred_ty< is_nonnegative > m_NonNegative (const APInt *&V)
cst_pred_ty< is_strictlypositive > m_StrictlyPositive ()
Match an integer or vector of strictly positive values.
api_pred_ty< is_strictlypositive > m_StrictlyPositive (const APInt *&V)
cst_pred_ty< is_nonpositive > m_NonPositive ()
Match an integer or vector of non-positive values.
api_pred_ty< is_nonpositive > m_NonPositive (const APInt *&V)
cst_pred_ty< is_one > m_One ()
Match an integer 1 or a vector with all elements equal to 1.
cst_pred_ty< is_zero_int > m_ZeroInt ()
Match an integer 0 or a vector with all elements equal to 0.
is_zero m_Zero ()
Match any null constant or a vector with all elements equal to 0.
cst_pred_ty< is_power2 > m_Power2 ()
Match an integer or vector power-of-2.
api_pred_ty< is_power2 > m_Power2 (const APInt *&V)
cst_pred_ty< is_negated_power2 > m_NegatedPower2 ()
Match a integer or vector negated power-of-2.
api_pred_ty< is_negated_power2 > m_NegatedPower2 (const APInt *&V)
cst_pred_ty< is_negated_power2_or_zero > m_NegatedPower2OrZero ()
Match a integer or vector negated power-of-2.
api_pred_ty< is_negated_power2_or_zero > m_NegatedPower2OrZero (const APInt *&V)
cst_pred_ty< is_power2_or_zero > m_Power2OrZero ()
Match an integer or vector of 0 or power-of-2 values.
api_pred_ty< is_power2_or_zero > m_Power2OrZero (const APInt *&V)
cst_pred_ty< is_sign_mask > m_SignMask ()
Match an integer or vector with only the sign bit(s) set.
cst_pred_ty< is_lowbit_mask > m_LowBitMask ()
Match an integer or vector with only the low bit(s) set.
api_pred_ty< is_lowbit_mask > m_LowBitMask (const APInt *&V)
cst_pred_ty< is_lowbit_mask_or_zero > m_LowBitMaskOrZero ()
Match an integer or vector with only the low bit(s) set.
api_pred_ty< is_lowbit_mask_or_zero > m_LowBitMaskOrZero (const APInt *&V)
cst_pred_ty< icmp_pred_with_threshold > m_SpecificInt_ICMP (ICmpInst::Predicate Predicate, const APInt &Threshold)
Match an integer or vector with every element comparing 'pred' (eg/ne/...) to Threshold.
cstfp_pred_ty< is_nan > m_NaN ()
Match an arbitrary NaN constant.
cstfp_pred_ty< is_nonnan > m_NonNaN ()
Match a non-NaN FP constant.
cstfp_pred_ty< is_inf > m_Inf ()
Match a positive or negative infinity FP constant.
cstfp_pred_ty< is_noninf > m_NonInf ()
Match a non-infinity FP constant, i.e.
cstfp_pred_ty< is_finite > m_Finite ()
Match a finite FP constant, i.e.
apf_pred_ty< is_finite > m_Finite (const APFloat *&V)
cstfp_pred_ty< is_finitenonzero > m_FiniteNonZero ()
Match a finite non-zero FP constant.
apf_pred_ty< is_finitenonzero > m_FiniteNonZero (const APFloat *&V)
cstfp_pred_ty< is_any_zero_fp > m_AnyZeroFP ()
Match a floating-point negative zero or positive zero.
cstfp_pred_ty< is_pos_zero_fp > m_PosZeroFP ()
Match a floating-point positive zero.
cstfp_pred_ty< is_neg_zero_fp > m_NegZeroFP ()
Match a floating-point negative zero.
cstfp_pred_ty< is_non_zero_fp > m_NonZeroFP ()
Match a floating-point non-zero.
cstfp_pred_ty< is_non_zero_not_denormal_fp > m_NonZeroNotDenormalFP ()
Match a floating-point non-zero that is not a denormal.
bind_ty< Value > m_Value (Value *&V)
Match a value, capturing it if we match.
bind_ty< const Value > m_Value (const Value *&V)
template<typename MatchTy>
bind_and_match_ty< Value, MatchTy > m_Value (Value *&V, const MatchTy &Match)
Match against the nested pattern, and capture the value if we match.
template<typename MatchTy>
bind_and_match_ty< const Value, MatchTy > m_Value (const Value *&V, const MatchTy &Match)
Match against the nested pattern, and capture the value if we match.
bind_ty< Instruction > m_Instruction (Instruction *&I)
Match an instruction, capturing it if we match.
bind_ty< const Instruction > m_Instruction (const Instruction *&I)
template<typename MatchTy>
bind_and_match_ty< Instruction, MatchTy > m_Instruction (Instruction *&I, const MatchTy &Match)
Match against the nested pattern, and capture the instruction if we match.
template<typename MatchTy>
bind_and_match_ty< const Instruction, MatchTy > m_Instruction (const Instruction *&I, const MatchTy &Match)
bind_ty< UnaryOperator > m_UnOp (UnaryOperator *&I)
Match a unary operator, capturing it if we match.
bind_ty< const UnaryOperator > m_UnOp (const UnaryOperator *&I)
bind_ty< BinaryOperator > m_BinOp (BinaryOperator *&I)
Match a binary operator, capturing it if we match.
bind_ty< const BinaryOperator > m_BinOp (const BinaryOperator *&I)
bind_ty< WithOverflowInst > m_WithOverflowInst (WithOverflowInst *&I)
Match a with overflow intrinsic, capturing it if we match.
bind_ty< const WithOverflowInst > m_WithOverflowInst (const WithOverflowInst *&I)
bind_ty< UndefValue > m_UndefValue (UndefValue *&U)
Match an UndefValue, capturing the value if we match.
bind_ty< Constant > m_Constant (Constant *&C)
Match a Constant, capturing the value if we match.
bind_ty< ConstantInt > m_ConstantInt (ConstantInt *&CI)
Match a ConstantInt, capturing the value if we match.
bind_ty< ConstantFP > m_ConstantFP (ConstantFP *&C)
Match a ConstantFP, capturing the value if we match.
bind_ty< ConstantExpr > m_ConstantExpr (ConstantExpr *&C)
Match a ConstantExpr, capturing the value if we match.
bind_ty< BasicBlock > m_BasicBlock (BasicBlock *&V)
Match a basic block value, capturing it if we match.
bind_ty< const BasicBlock > m_BasicBlock (const BasicBlock *&V)
match_immconstant_ty m_ImmConstant ()
Match an arbitrary immediate Constant and ignore it.
bind_immconstant_ty m_ImmConstant (Constant *&C)
Match an immediate Constant, capturing the value if we match.
specificval_ty m_Specific (const Value *V)
Match if we have a specific specified value.
deferredval_ty< Value > m_Deferred (Value *const &V)
Like m_Specific(), but works if the specific value to match is determined as part of the same match() expression.
deferredval_ty< const Value > m_Deferred (const Value *const &V)
specific_fpval m_SpecificFP (double V)
Match a specific floating point value or vector with all elements equal to the value.
specific_fpval m_FPOne ()
Match a float 1.0 or vector with all elements equal to 1.0.
specific_intval< false > m_SpecificInt (const APInt &V)
Match a specific integer value or vector with all elements equal to the value.
specific_intval64< false > m_SpecificInt (uint64_t V)
specific_intval< true > m_SpecificIntAllowPoison (const APInt &V)
specific_intval64< true > m_SpecificIntAllowPoison (uint64_t V)
bind_const_intval_ty m_ConstantInt (uint64_t &V)
Match a ConstantInt and bind to its value.
specific_bbval m_SpecificBB (BasicBlock *BB)
Match a specific basic block value.
deferredval_ty< BasicBlock > m_Deferred (BasicBlock *const &BB)
A commutative-friendly version of m_Specific().
deferredval_ty< const BasicBlock > m_Deferred (const BasicBlock *const &BB)
template<typename LHS, typename RHS>
AnyBinaryOp_match< LHS, RHS > m_BinOp (const LHS &L, const RHS &R)
template<typename OP_t>
AnyUnaryOp_match< OP_t > m_UnOp (const OP_t &X)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Add > m_Add (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FAdd > m_FAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Sub > m_Sub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FSub > m_FSub (const LHS &L, const RHS &R)
template<typename OpTy>
FNeg_match< OpTy > m_FNeg (const OpTy &X)
Match 'fneg X' as 'fsub -0.0, X'.
template<typename RHS>
BinaryOp_match< cstfp_pred_ty< is_any_zero_fp >, RHS, Instruction::FSub > m_FNegNSZ (const RHS &X)
Match 'fneg X' as 'fsub +-0.0, X'.
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Mul > m_Mul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FMul > m_FMul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::UDiv > m_UDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::SDiv > m_SDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FDiv > m_FDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::URem > m_URem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::SRem > m_SRem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FRem > m_FRem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::And > m_And (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Or > m_Or (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Xor > m_Xor (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Shl > m_Shl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::LShr > m_LShr (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::AShr > m_AShr (const LHS &L, const RHS &R)
template<typename LHS>
ShiftLike_match< LHS, Instruction::Shl > m_ShlOrSelf (const LHS &L, uint64_t &R)
Matches shl L, ConstShAmt or L itself (R will be set to zero in this case).
template<typename LHS>
ShiftLike_match< LHS, Instruction::LShr > m_LShrOrSelf (const LHS &L, uint64_t &R)
Matches lshr L, ConstShAmt or L itself (R will be set to zero in this case).
template<typename LHS>
ShiftLike_match< LHS, Instruction::AShr > m_AShrOrSelf (const LHS &L, uint64_t &R)
Matches ashr L, ConstShAmt or L itself (R will be set to zero in this case).
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap > m_NSWAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap, true > m_c_NSWAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoSignedWrap > m_NSWSub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoSignedWrap > m_NSWMul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoSignedWrap > m_NSWShl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap, true > m_c_NUWAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWSub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWMul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWShl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
SpecificBinaryOp_match< LHS, RHS > m_BinOp (unsigned Opcode, const LHS &L, const RHS &R)
Matches a specific opcode.
template<typename LHS, typename RHS>
DisjointOr_match< LHS, RHS > m_DisjointOr (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
DisjointOr_match< LHS, RHS, true > m_c_DisjointOr (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
match_combine_or< BinaryOp_match< LHS, RHS, Instruction::Add >, DisjointOr_match< LHS, RHS > > m_AddLike (const LHS &L, const RHS &R)
Match either "add" or "or disjoint".
template<typename LHS, typename RHS>
match_combine_or< OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap >, DisjointOr_match< LHS, RHS > > m_NSWAddLike (const LHS &L, const RHS &R)
Match either "add nsw" or "or disjoint".
template<typename LHS, typename RHS>
match_combine_or< OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap >, DisjointOr_match< LHS, RHS > > m_NUWAddLike (const LHS &L, const RHS &R)
Match either "add nuw" or "or disjoint".
template<typename LHS, typename RHS>
auto m_c_XorLike (const LHS &L, const RHS &R)
Match either (xor L, R), (xor R, L) or (sub nuw R, L) iff R.isMask() Only commutative matcher as the sub will need to swap the L and R.
template<typename LHS, typename RHS>
BinOpPred_match< LHS, RHS, is_shift_op > m_Shift (const LHS &L, const RHS &R)
Matches shift operations.
template<typename LHS, typename RHS>
BinOpPred_match< LHS, RHS, is_right_shift_op > m_Shr (const LHS &L, const RHS &R)
Matches logical shift operations.
template<typename LHS, typename RHS>
BinOpPred_match< LHS, RHS, is_logical_shift_op > m_LogicalShift (const LHS &L, const RHS &R)
Matches logical shift operations.
template<typename LHS, typename RHS>
BinOpPred_match< LHS, RHS, is_bitwiselogic_op > m_BitwiseLogic (const LHS &L, const RHS &R)
Matches bitwise logic operations.
template<typename LHS, typename RHS>
BinOpPred_match< LHS, RHS, is_bitwiselogic_op, true > m_c_BitwiseLogic (const LHS &L, const RHS &R)
Matches bitwise logic operations in either order.
template<typename LHS, typename RHS>
BinOpPred_match< LHS, RHS, is_idiv_op > m_IDiv (const LHS &L, const RHS &R)
Matches integer division operations.
template<typename LHS, typename RHS>
BinOpPred_match< LHS, RHS, is_irem_op > m_IRem (const LHS &L, const RHS &R)
Matches integer remainder operations.
template<typename T>
Exact_match< T > m_Exact (const T &SubPattern)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, CmpInst > m_Cmp (CmpPredicate &Pred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, ICmpInst > m_ICmp (CmpPredicate &Pred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, FCmpInst > m_FCmp (CmpPredicate &Pred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, CmpInst > m_Cmp (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, ICmpInst > m_ICmp (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, FCmpInst > m_FCmp (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
SpecificCmpClass_match< LHS, RHS, CmpInst > m_SpecificCmp (CmpPredicate MatchPred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
SpecificCmpClass_match< LHS, RHS, ICmpInst > m_SpecificICmp (CmpPredicate MatchPred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
SpecificCmpClass_match< LHS, RHS, ICmpInst, true > m_c_SpecificICmp (CmpPredicate MatchPred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
SpecificCmpClass_match< LHS, RHS, FCmpInst > m_SpecificFCmp (CmpPredicate MatchPred, const LHS &L, const RHS &R)
template<typename Cond, typename LHS, typename RHS>
ThreeOps_match< Cond, LHS, RHS, Instruction::Select > m_Select (const Cond &C, const LHS &L, const RHS &R)
Matches SelectInst.
template<int64_t L, int64_t R, typename Cond>
ThreeOps_match< Cond, constantint_match< L >, constantint_match< R >, Instruction::Select > m_SelectCst (const Cond &C)
This matches a select of two constants, e.g.: m_SelectCst<-1, 0>(m_Value(V)).
template<typename LHS, typename RHS>
ThreeOps_match< decltype(m_Value()), LHS, RHS, Instruction::Select, true > m_c_Select (const LHS &L, const RHS &R)
Match Select(C, LHS, RHS) or Select(C, RHS, LHS).
template<typename OpTy>
OneOps_match< OpTy, Instruction::Freeze > m_Freeze (const OpTy &Op)
Matches FreezeInst.
template<typename Val_t, typename Elt_t, typename Idx_t>
ThreeOps_match< Val_t, Elt_t, Idx_t, Instruction::InsertElement > m_InsertElt (const Val_t &Val, const Elt_t &Elt, const Idx_t &Idx)
Matches InsertElementInst.
template<typename Val_t, typename Idx_t>
TwoOps_match< Val_t, Idx_t, Instruction::ExtractElement > m_ExtractElt (const Val_t &Val, const Idx_t &Idx)
Matches ExtractElementInst.
template<typename V1_t, typename V2_t>
TwoOps_match< V1_t, V2_t, Instruction::ShuffleVector > m_Shuffle (const V1_t &v1, const V2_t &v2)
Matches ShuffleVectorInst independently of mask value.
template<typename V1_t, typename V2_t, typename Mask_t>
Shuffle_match< V1_t, V2_t, Mask_t > m_Shuffle (const V1_t &v1, const V2_t &v2, const Mask_t &mask)
template<typename OpTy>
OneOps_match< OpTy, Instruction::Load > m_Load (const OpTy &Op)
Matches LoadInst.
template<typename ValueOpTy, typename PointerOpTy>
TwoOps_match< ValueOpTy, PointerOpTy, Instruction::Store > m_Store (const ValueOpTy &ValueOp, const PointerOpTy &PointerOp)
Matches StoreInst.
template<typename... OperandTypes>
auto m_GEP (const OperandTypes &...Ops)
Matches GetElementPtrInst.
template<typename PointerOpTy, typename OffsetOpTy>
PtrAdd_match< PointerOpTy, OffsetOpTy > m_PtrAdd (const PointerOpTy &PointerOp, const OffsetOpTy &OffsetOp)
Matches GEP with i8 source element type.
template<typename OpTy>
CastOperator_match< OpTy, Instruction::BitCast > m_BitCast (const OpTy &Op)
Matches BitCast.
template<typename OpTy>
ElementWiseBitCast_match< OpTy > m_ElementWiseBitCast (const OpTy &Op)
template<typename OpTy>
CastOperator_match< OpTy, Instruction::PtrToInt > m_PtrToInt (const OpTy &Op)
Matches PtrToInt.
template<typename OpTy>
PtrToIntSameSize_match< OpTy > m_PtrToIntSameSize (const DataLayout &DL, const OpTy &Op)
template<typename OpTy>
CastOperator_match< OpTy, Instruction::PtrToAddr > m_PtrToAddr (const OpTy &Op)
Matches PtrToAddr.
template<typename OpTy>
auto m_PtrToIntOrAddr (const OpTy &Op)
Matches PtrToInt or PtrToAddr.
template<typename OpTy>
CastOperator_match< OpTy, Instruction::IntToPtr > m_IntToPtr (const OpTy &Op)
Matches IntToPtr.
template<typename OpTy>
match_combine_or< CastInst_match< OpTy, CastInst >, OpTy > m_CastOrSelf (const OpTy &Op)
Matches any cast or self. Used to ignore casts.
template<typename OpTy>
CastInst_match< OpTy, TruncInst > m_Trunc (const OpTy &Op)
Matches Trunc.
template<typename OpTy>
NoWrapTrunc_match< OpTy, TruncInst::NoUnsignedWrap > m_NUWTrunc (const OpTy &Op)
Matches trunc nuw.
template<typename OpTy>
NoWrapTrunc_match< OpTy, TruncInst::NoSignedWrap > m_NSWTrunc (const OpTy &Op)
Matches trunc nsw.
template<typename OpTy>
match_combine_or< CastInst_match< OpTy, TruncInst >, OpTy > m_TruncOrSelf (const OpTy &Op)
template<typename OpTy>
CastInst_match< OpTy, SExtInst > m_SExt (const OpTy &Op)
Matches SExt.
template<typename OpTy>
CastInst_match< OpTy, ZExtInst > m_ZExt (const OpTy &Op)
Matches ZExt.
template<typename OpTy>
NNegZExt_match< OpTy > m_NNegZExt (const OpTy &Op)
template<typename OpTy>
match_combine_or< CastInst_match< OpTy, ZExtInst >, OpTy > m_ZExtOrSelf (const OpTy &Op)
template<typename OpTy>
match_combine_or< CastInst_match< OpTy, SExtInst >, OpTy > m_SExtOrSelf (const OpTy &Op)
template<typename OpTy>
match_combine_or< CastInst_match< OpTy, SExtInst >, NNegZExt_match< OpTy > > m_SExtLike (const OpTy &Op)
Match either "sext" or "zext nneg".
template<typename OpTy>
match_combine_or< CastInst_match< OpTy, ZExtInst >, CastInst_match< OpTy, SExtInst > > m_ZExtOrSExt (const OpTy &Op)
template<typename OpTy>
match_combine_or< match_combine_or< CastInst_match< OpTy, ZExtInst >, CastInst_match< OpTy, SExtInst > >, OpTy > m_ZExtOrSExtOrSelf (const OpTy &Op)
template<typename OpTy>
match_combine_or< match_combine_or< CastInst_match< OpTy, ZExtInst >, CastInst_match< OpTy, TruncInst > >, OpTy > m_ZExtOrTruncOrSelf (const OpTy &Op)
template<typename OpTy>
CastInst_match< OpTy, UIToFPInst > m_UIToFP (const OpTy &Op)
template<typename OpTy>
CastInst_match< OpTy, SIToFPInst > m_SIToFP (const OpTy &Op)
template<typename OpTy>
CastInst_match< OpTy, FPToUIInst > m_FPToUI (const OpTy &Op)
template<typename OpTy>
CastInst_match< OpTy, FPToSIInst > m_FPToSI (const OpTy &Op)
template<typename OpTy>
CastInst_match< OpTy, FPTruncInst > m_FPTrunc (const OpTy &Op)
template<typename OpTy>
CastInst_match< OpTy, FPExtInst > m_FPExt (const OpTy &Op)
br_match m_UnconditionalBr (BasicBlock *&Succ)
template<typename Cond_t>
brc_match< Cond_t, bind_ty< BasicBlock >, bind_ty< BasicBlock > > m_Br (const Cond_t &C, BasicBlock *&T, BasicBlock *&F)
template<typename Cond_t, typename TrueBlock_t, typename FalseBlock_t>
brc_match< Cond_t, TrueBlock_t, FalseBlock_t > m_Br (const Cond_t &C, const TrueBlock_t &T, const FalseBlock_t &F)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty > m_SMax (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty > m_SMin (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty > m_UMax (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty > m_UMin (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
match_combine_or< match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty >, MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty > >, match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty >, MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty > > > m_MaxOrMin (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ofmax_pred_ty > m_OrdFMax (const LHS &L, const RHS &R)
Match an 'ordered' floating point maximum function.
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ofmin_pred_ty > m_OrdFMin (const LHS &L, const RHS &R)
Match an 'ordered' floating point minimum function.
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ufmax_pred_ty > m_UnordFMax (const LHS &L, const RHS &R)
Match an 'unordered' floating point maximum function.
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ufmin_pred_ty > m_UnordFMin (const LHS &L, const RHS &R)
Match an 'unordered' floating point minimum function.
template<typename LHS, typename RHS>
match_combine_or< MaxMin_match< FCmpInst, LHS, RHS, ofmax_pred_ty >, MaxMin_match< FCmpInst, LHS, RHS, ufmax_pred_ty > > m_OrdOrUnordFMax (const LHS &L, const RHS &R)
Match an 'ordered' or 'unordered' floating point maximum function.
template<typename LHS, typename RHS>
match_combine_or< MaxMin_match< FCmpInst, LHS, RHS, ofmin_pred_ty >, MaxMin_match< FCmpInst, LHS, RHS, ufmin_pred_ty > > m_OrdOrUnordFMin (const LHS &L, const RHS &R)
Match an 'ordered' or 'unordered' floating point minimum function.
template<typename ValTy>
BinaryOp_match< cst_pred_ty< is_all_ones >, ValTy, Instruction::Xor, true > m_Not (const ValTy &V)
Matches a 'Not' as 'xor V, -1' or 'xor -1, V'.
template<typename ValTy>
BinaryOp_match< cst_pred_ty< is_all_ones, false >, ValTy, Instruction::Xor, true > m_NotForbidPoison (const ValTy &V)
template<typename LHS_t, typename RHS_t, typename Sum_t>
UAddWithOverflow_match< LHS_t, RHS_t, Sum_t > m_UAddWithOverflow (const LHS_t &L, const RHS_t &R, const Sum_t &S)
Match an icmp instruction checking for unsigned overflow on addition.
template<unsigned OpI, typename Opnd_t>
Argument_match< Opnd_t > m_Argument (const Opnd_t &Op)
Match an argument.
template<Intrinsic::ID IntrID>
IntrinsicID_match m_Intrinsic ()
Match intrinsic calls like this: m_Intrinsic<Intrinsic::fabs>(m_Value(X)).
template<typename Opnd0, typename Opnd1, typename Opnd2>
m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty m_MaskedLoad (const Opnd0 &Op0, const Opnd1 &Op1, const Opnd2 &Op2)
Matches MaskedLoad Intrinsic.
template<typename Opnd0, typename Opnd1, typename Opnd2>
m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty m_MaskedStore (const Opnd0 &Op0, const Opnd1 &Op1, const Opnd2 &Op2)
Matches MaskedStore Intrinsic.
template<typename Opnd0, typename Opnd1, typename Opnd2>
m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty m_MaskedGather (const Opnd0 &Op0, const Opnd1 &Op1, const Opnd2 &Op2)
Matches MaskedGather Intrinsic.
template<Intrinsic::ID IntrID, typename T0>
m_Intrinsic_Ty< T0 >::Ty m_Intrinsic (const T0 &Op0)
template<Intrinsic::ID IntrID, typename T0, typename T1>
m_Intrinsic_Ty< T0, T1 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2>
m_Intrinsic_Ty< T0, T1, T2 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3>
m_Intrinsic_Ty< T0, T1, T2, T3 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2, const T3 &Op3)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3, typename T4>
m_Intrinsic_Ty< T0, T1, T2, T3, T4 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2, const T3 &Op3, const T4 &Op4)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5>
m_Intrinsic_Ty< T0, T1, T2, T3, T4, T5 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2, const T3 &Op3, const T4 &Op4, const T5 &Op5)
template<typename Opnd0>
m_Intrinsic_Ty< Opnd0 >::Ty m_BitReverse (const Opnd0 &Op0)
template<typename Opnd0>
m_Intrinsic_Ty< Opnd0 >::Ty m_BSwap (const Opnd0 &Op0)
template<typename Opnd0>
m_Intrinsic_Ty< Opnd0 >::Ty m_FAbs (const Opnd0 &Op0)
template<typename Opnd0>
m_Intrinsic_Ty< Opnd0 >::Ty m_FCanonicalize (const Opnd0 &Op0)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMinNum (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMinimum (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMinimumNum (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMaxNum (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMaximum (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMaximumNum (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0, typename Opnd1, typename Opnd2>
m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty m_FShl (const Opnd0 &Op0, const Opnd1 &Op1, const Opnd2 &Op2)
template<typename Opnd0, typename Opnd1, typename Opnd2>
m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty m_FShr (const Opnd0 &Op0, const Opnd1 &Op1, const Opnd2 &Op2)
template<typename Opnd0>
m_Intrinsic_Ty< Opnd0 >::Ty m_Sqrt (const Opnd0 &Op0)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_CopySign (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0>
m_Intrinsic_Ty< Opnd0 >::Ty m_VecReverse (const Opnd0 &Op0)
template<typename Opnd0, typename Opnd1, typename Opnd2>
m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty m_VectorInsert (const Opnd0 &Op0, const Opnd1 &Op1, const Opnd2 &Op2)
template<typename LHS, typename RHS>
AnyBinaryOp_match< LHS, RHS, true > m_c_BinOp (const LHS &L, const RHS &R)
Matches a BinaryOperator with LHS and RHS in either order.
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, ICmpInst, true > m_c_ICmp (CmpPredicate &Pred, const LHS &L, const RHS &R)
Matches an ICmp with a predicate over LHS and RHS in either order.
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, ICmpInst, true > m_c_ICmp (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
SpecificBinaryOp_match< LHS, RHS, true > m_c_BinOp (unsigned Opcode, const LHS &L, const RHS &R)
Matches a specific opcode with LHS and RHS in either order.
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Add, true > m_c_Add (const LHS &L, const RHS &R)
Matches a Add with LHS and RHS in either order.
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Mul, true > m_c_Mul (const LHS &L, const RHS &R)
Matches a Mul with LHS and RHS in either order.
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::And, true > m_c_And (const LHS &L, const RHS &R)
Matches an And with LHS and RHS in either order.
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Or, true > m_c_Or (const LHS &L, const RHS &R)
Matches an Or with LHS and RHS in either order.
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Xor, true > m_c_Xor (const LHS &L, const RHS &R)
Matches an Xor with LHS and RHS in either order.
template<typename ValTy>
BinaryOp_match< cst_pred_ty< is_zero_int >, ValTy, Instruction::Sub > m_Neg (const ValTy &V)
Matches a 'Neg' as 'sub 0, V'.
template<typename ValTy>
OverflowingBinaryOp_match< cst_pred_ty< is_zero_int >, ValTy, Instruction::Sub, OverflowingBinaryOperator::NoSignedWrap > m_NSWNeg (const ValTy &V)
Matches a 'Neg' as 'sub nsw 0, V'.
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty, true > m_c_SMin (const LHS &L, const RHS &R)
Matches an SMin with LHS and RHS in either order.
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty, true > m_c_SMax (const LHS &L, const RHS &R)
Matches an SMax with LHS and RHS in either order.
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty, true > m_c_UMin (const LHS &L, const RHS &R)
Matches a UMin with LHS and RHS in either order.
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty, true > m_c_UMax (const LHS &L, const RHS &R)
Matches a UMax with LHS and RHS in either order.
template<typename LHS, typename RHS>
match_combine_or< match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty, true >, MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty, true > >, match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty, true >, MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty, true > > > m_c_MaxOrMin (const LHS &L, const RHS &R)
template<Intrinsic::ID IntrID, typename T0, typename T1>
CommutativeBinaryIntrinsic_match< IntrID, T0, T1 > m_c_Intrinsic (const T0 &Op0, const T1 &Op1)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FAdd, true > m_c_FAdd (const LHS &L, const RHS &R)
Matches FAdd with LHS and RHS in either order.
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FMul, true > m_c_FMul (const LHS &L, const RHS &R)
Matches FMul with LHS and RHS in either order.
template<typename Val_t>
Signum_match< Val_t > m_Signum (const Val_t &V)
Matches a signum pattern.
template<int Ind, typename Val_t>
ExtractValue_match< Ind, Val_t > m_ExtractValue (const Val_t &V)
Match a single index ExtractValue instruction.
template<typename Val_t>
ExtractValue_match<-1, Val_t > m_ExtractValue (const Val_t &V)
Match an ExtractValue instruction with any index.
template<int Ind, typename Val_t, typename Elt_t>
InsertValue_match< Ind, Val_t, Elt_t > m_InsertValue (const Val_t &Val, const Elt_t &Elt)
Matches a single index InsertValue instruction.
IntrinsicID_match m_VScale ()
Matches a call to llvm.vscale().
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_Interleave2 (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd>
m_Intrinsic_Ty< Opnd >::Ty m_Deinterleave2 (const Opnd &Op)
template<typename LHS, typename RHS>
LogicalOp_match< LHS, RHS, Instruction::And > m_LogicalAnd (const LHS &L, const RHS &R)
Matches L && R either in the form of L & R or L ?
auto m_LogicalAnd ()
Matches L && R where L and R are arbitrary values.
template<typename LHS, typename RHS>
LogicalOp_match< LHS, RHS, Instruction::And, true > m_c_LogicalAnd (const LHS &L, const RHS &R)
Matches L && R with LHS and RHS in either order.
template<typename LHS, typename RHS>
LogicalOp_match< LHS, RHS, Instruction::Or > m_LogicalOr (const LHS &L, const RHS &R)
Matches L || R either in the form of L | R or L ?
auto m_LogicalOr ()
Matches L || R where L and R are arbitrary values.
template<typename LHS, typename RHS>
LogicalOp_match< LHS, RHS, Instruction::Or, true > m_c_LogicalOr (const LHS &L, const RHS &R)
Matches L || R with LHS and RHS in either order.
template<typename LHS, typename RHS, bool Commutable = false>
auto m_LogicalOp (const LHS &L, const RHS &R)
Matches either L && R or L || R, either one being in the either binary or logical form.
auto m_LogicalOp ()
Matches either L && R or L || R where L and R are arbitrary values.
template<typename LHS, typename RHS>
auto m_c_LogicalOp (const LHS &L, const RHS &R)
Matches either L && R or L || R with LHS and RHS in either order.
Typedef Documentation
cst_pred_ty
template<typename Predicate, bool AllowPoison = true> using llvm::PatternMatch::cst_pred_ty = cstval_pred_ty<Predicate, ConstantInt, AllowPoison>
specialization of cstval_pred_ty for ConstantInt
Definition at line 416 of file PatternMatch.h.
cstfp_pred_ty
template<typename Predicate> using llvm::PatternMatch::cstfp_pred_ty
Initial value:
cstval_pred_ty<Predicate, ConstantFP,
                                    true>
specialization of cstval_pred_ty for ConstantFP
Definition at line 420 of file PatternMatch.h.
Function Documentation
m_Add()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Add > llvm::PatternMatch::m_Add (const LHS & L, const RHS & R) inline
Definition at line 1208 of file PatternMatch.h.
References LHS, and RHS.
Referenced by canonicalizeLogicFirst(), canonicalizeLowbitMask(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), canonicalizeSaturatedSubtract(), checkForNegativeOperand(), combineAdd(), combineShlAddIAddImpl(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), createWidenInductionRecipe(), decompose(), detectPMADDUBSW(), detectShiftUntilZeroIdiom(), dropRedundantMaskingOfLeftShiftInput(), llvm::findHistogram(), llvm::findScalarElement(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpEqConstantAndICmp(), foldAndToUsubsat(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpWithConstant(), foldICmpWithHighBitMask(), foldMulHigh(), foldMulShl1(), foldRoundUpIntegerWithPow2Alignment(), foldSelectICmpMinMax(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), llvm::InstCombiner::getFreelyInvertedImpl(), getKnownBitsFromAndXorOr(), llvm::vputils::getSCEVExprForVPValue(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), llvm::isKnownToBeAPowerOfTwo(), isMaskOrZero(), isSafeToRemoveBitCeilSelect(), m_AddLike(), m_AnyAdd(), llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match(), matchIncrement(), matchPMADDWD(), matchPMADDWD_2(), matchUAddWithOverflowConstantEdgeCases(), matchVPMADD52(), moveAddAfterMinMax(), optimizeBranch(), performAddTruncShiftCombine(), performLastTrueTestVectorCombine(), llvm::X86TargetLowering::shouldFoldSelectWithIdentityConstant(), simplifyAndCommutative(), simplifyAndInst(), simplifyAndOfICmpsWithAdd(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyLogicOfAddSub(), llvm::simplifyLoopAfterUnroll(), simplifyOrOfICmpsWithAdd(), simplifySubInst(), trySimplifyICmpWithAdds(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitURem(), and llvm::InstCombinerImpl::visitXor().
m_AddLike()
template<typename LHS, typename RHS> match_combine_or< BinaryOp_match< LHS, RHS, Instruction::Add >, DisjointOr_match< LHS, RHS > > llvm::PatternMatch::m_AddLike (const LHS & L, const RHS & R) inline
Match either "add" or "or disjoint".
Definition at line 1562 of file PatternMatch.h.
References LHS, m_Add(), m_CombineOr(), m_DisjointOr(), and RHS.
Referenced by canonicalizeGEPOfConstGEPI8(), computeKnownBitsFromCmp(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldICmpBinOp(), foldReduceOperandViaVQDOT(), matchICmpOperand(), llvm::simplifyInstruction(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSub().
m_AllOnes()
cst_pred_ty< is_all_ones > llvm::PatternMatch::m_AllOnes () inline
Match an integer or vector with all bits set.
For vectors, this includes constants with undefined elements.
Definition at line 536 of file PatternMatch.h.
Referenced by areInverseVectorBitmasks(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeLowbitMask(), canonicalizeSaturatedAddUnsigned(), canonicalizeSaturatedSubtract(), dropRedundantMaskingOfLeftShiftInput(), FindSingleBitChange(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldAddWithConstant(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), foldICmpOfUAddOv(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpPow2Test(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), foldMulSelectToNegate(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldOverflowingAddSubSelect(), foldSelectICmpMinMax(), llvm::InstCombinerImpl::foldSelectInstWithICmp(), llvm::InstCombinerImpl::foldSelectToCmp(), llvm::InstCombinerImpl::foldVectorBinop(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), getKnownBitsFromAndXorOr(), getMaskedTypeForICmpPair(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::isKnownToBeAPowerOfTwo(), isMaskOrZero(), m_Not(), llvm::SDPatternMatch::m_Not(), matchSelectPattern(), matchUAddWithOverflowConstantEdgeCases(), performLastTrueTestVectorCombine(), shouldExpandCmpArithRMWInIR(), llvm::X86TargetLowering::shouldFoldSelectWithIdentityConstant(), simplifyAddInst(), simplifyAndCommutative(), simplifyAndInst(), simplifyAShrInst(), llvm::simplifyBinaryIntrinsic(), simplifyGEPInst(), simplifyIntrinsic(), simplifyOrInst(), simplifyRecipe(), simplifySelectWithICmpCond(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitXor().
m_AllOnesForbidPoison()
cst_pred_ty< is_all_ones, false > llvm::PatternMatch::m_AllOnesForbidPoison () inline
Definition at line 540 of file PatternMatch.h.
Referenced by m_NotForbidPoison().
m_AllowReassoc()
template<typename T> AllowReassoc_match< T > llvm::PatternMatch::m_AllowReassoc (const T & SubPattern) inline
Definition at line 96 of file PatternMatch.h.
References T.
Referenced by llvm::InstCombinerImpl::foldFMulReassoc(), and llvm::InstCombinerImpl::foldPowiReassoc().
m_And()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::And > llvm::PatternMatch::m_And (const LHS & L, const RHS & R) inline
Definition at line 1322 of file PatternMatch.h.
References LHS, and RHS.
Referenced by canScalarizeAccess(), checkForNegativeOperand(), collectBitParts(), combineAnd(), combineAndNotOrIntoAndNotAnd(), combineAndXorSubWithBMI(), combineNarrowableShiftedLoad(), combineOrAndToBitfieldInsert(), combineSetCC(), combineXorToBitfieldInsert(), computeKnownBitsFromCmp(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), countToEliminateCompares(), llvm::decomposeBitTestICmp(), llvm::findValuesAffectedByCondition(), foldAddSubBoolOfMaskedVal(), foldAddToAshr(), foldAndToUsubsat(), foldAnyOrAllBitsSet(), foldBoxMultiply(), foldCopySignIdioms(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpWithLowBitMaskedVal(), foldMaskedMerge(), foldMulHigh(), foldNotXor(), foldOrOfInversions(), foldOrToXor(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBitTest(), foldSelectICmpAndAnd(), foldSelectICmpAndZeroShl(), foldSetClearBits(), foldSubCtlzNot(), foldXorToXor(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::SystemZTargetLowering::getJumpConditionMergingParams(), getMaskedTypeForICmpPair(), getShlAddShlAdd(), haveNoCommonBitsSetSpecialCases(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), llvm::X86TTIImpl::isProfitableToSinkOperands(), lookThroughAnd(), matchAndOrChain(), matchBitmaskMul(), matchLogicBlend(), MatchRem(), matchZExtedSubInteger(), narrowBitOpRMW(), parseCondition(), llvm::parseWidenableBranch(), reverseZExtICmpCombine(), llvm::simplifyInstruction(), simplifyOrInst(), simplifyOrLogic(), simplifySelectBitTest(), simplifySelectWithICmpCond(), llvm::stripNullTest(), llvm::InstCombinerImpl::takeLog2(), tryToImproveAlign(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitXor(), and llvm::InstCombinerImpl::visitZExt().
m_AnyIntegralConstant()
cst_pred_ty< is_any_apint > llvm::PatternMatch::m_AnyIntegralConstant () inline
Match an integer or vector with any integral constant.
For vectors, this includes constants with undefined elements.
Definition at line 519 of file PatternMatch.h.
Referenced by foldTwoEntryPHINode().
m_AnyZeroFP()
cstfp_pred_ty< is_any_zero_fp > llvm::PatternMatch::m_AnyZeroFP () inline
Match a floating-point negative zero or positive zero.
For vectors, this includes constants with undefined elements.
Definition at line 778 of file PatternMatch.h.
Referenced by foldFCmpFSubIntoFCmp(), foldFCmpReciprocalAndZero(), foldSelectBinOpIdentity(), foldSelectIntoAddConstant(), foldSelectWithFCmpToFabs(), llvm::GCNTTIImpl::instCombineIntrinsic(), m_FNegNSZ(), matchIsNotNaN(), matchSelectPattern(), reassociateFCmps(), simplifyFAddInst(), simplifyFCmpInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFSubInst(), llvm::InstCombinerImpl::visitFAdd(), and llvm::InstCombinerImpl::visitFCmpInst().
m_APFloat()
ap_match< APFloat > llvm::PatternMatch::m_APFloat (const APFloat *& Res) inline
Match a ConstantFP or splatted ConstantVector, binding the specified pointer to the contained APFloat.
Definition at line 328 of file PatternMatch.h.
Referenced by computeKnownFPClass(), computeKnownFPClassFromCond(), factorizeFAddFSub(), foldFabsWithFcmpZero(), foldFCmpFpTrunc(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), foldFCmpReciprocalAndZero(), foldFrexpOfSelect(), getNegatibleInsts(), llvm::GCNTTIImpl::instCombineIntrinsic(), isImpliedCondFCmps(), isMinMaxCmpSelectEliminable(), matchFastFloatClamp(), simplifyAndOrOfFCmpsWithConstants(), simplifyFCmpInst(), simplifyLdexp(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFAdd(), and llvm::InstCombinerImpl::visitFCmpInst().
m_APFloatAllowPoison()
ap_match< APFloat > llvm::PatternMatch::m_APFloatAllowPoison (const APFloat *& Res) inline
Match APFloat while allowing poison in splat vector constants.
Definition at line 334 of file PatternMatch.h.
Referenced by foldSelectToCopysign(), simplifyFCmpInst(), and llvm::InstCombinerImpl::visitFMul().
m_APFloatForbidPoison()
ap_match< APFloat > llvm::PatternMatch::m_APFloatForbidPoison (const APFloat *& Res) inline
Match APFloat while forbidding poison in splat vector constants.
Definition at line 339 of file PatternMatch.h.
m_APInt()
ap_match< APInt > llvm::PatternMatch::m_APInt (const APInt *& Res) inline
Match a ConstantInt or splatted ConstantVector, binding the specified pointer to the contained APInt.
Definition at line 311 of file PatternMatch.h.
Referenced by bitTrackingDCE(), canEvaluateShifted(), canEvaluateShiftedShift(), canonicalizeAbs(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeGEPOfConstGEPI8(), canonicalizeLogicFirst(), canonicalizeSaturatedSubtract(), checkForNegativeOperand(), cmpExcludesZero(), collectBitParts(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonIRemTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), computeKnownBits(), computeKnownBitsFromCmp(), computeKnownBitsFromOperator(), computeKnownFPClassFromCond(), ComputeNumSignBitsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), foldBitCeil(), foldBitwiseLogicWithIntrinsics(), foldClampRangeOfTwo(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpAndShift(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEqIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpEqualityWithOffset(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), foldICmpShlLHSC(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpUSubSatOrUAddSatWithConstant(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), llvm::InstCombinerImpl::foldICmpWithClamp(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpXorConstant(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldNegativePower2AndShiftedMask(), foldNoWrapAdd(), llvm::InstCombinerImpl::foldOpIntoPhi(), foldOrUnsignedUMulOverflowICmp(), foldOverflowingAddSubSelect(), llvm::InstCombinerImpl::foldSelectICmp(), foldSelectICmpAnd(), foldSelectICmpAndZeroShl(), llvm::InstCombinerImpl::foldSelectIntoOp(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectToCopysign(), foldSelectWithFCmpToFabs(), foldSelectWithSRem(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftedShift(), foldToUnsignedSaturatedAdd(), foldVecExtTruncToExtElt(), getDemandedBitsLHSMask(), llvm::ConstantExpr::getExactLogBase2(), llvm::SystemZTargetLowering::getJumpConditionMergingParams(), getMaskedICmpType(), getNotValue(), getRangeForIntrinsic(), getRangeForSelectPattern(), getValueFromOverflowCondition(), haveNoCommonBitsSetSpecialCases(), isAllocSiteRemovable(), isDivZero(), isImpliedCondICmps(), isImpliedToBeAPowerOfTwoFromCond(), llvm::isKnownInversion(), isLoadCombineCandidateImpl(), isNonEqualMul(), isNonEqualPHIs(), isNonEqualShl(), isNonZeroRecurrence(), isPoisonShift(), isSafeToRemoveBitCeilSelect(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), isSignedMinMaxClamp(), isSignedMinMaxIntrinsicClamp(), isSignificantBitCheckWellFormed(), isTruePredicate(), lookThroughAnd(), maintainNoSignedWrap(), matchAndOrChain(), matchBitmaskMul(), matchClamp(), MatchDiv(), matchICmpOperand(), matchIntPart(), matchMinMax(), MatchMul(), matchOrConcat(), MatchRem(), matchZExtedSubInteger(), moveAddAfterMinMax(), optimizeVectorInductionWidthForTCAndVFUF(), setLimitsForBinOp(), ShrinkDemandedConstant(), simplifyAndCommutative(), simplifyAndInst(), simplifyAndOfICmpsWithAdd(), simplifyAndOrOfICmpsWithConstants(), simplifyAndOrOfICmpsWithCtpop(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyDiv(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), llvm::simplifyInstruction(), simplifyIntrinsic(), simplifyIRemMulShl(), llvm::simplifyLoopAfterUnroll(), simplifyLShrInst(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyOrInst(), simplifyOrOfICmpsWithAdd(), simplifyRecipe(), simplifyRem(), simplifySelectBitTest(), simplifySelectWithICmpCond(), simplifySwitchOnSelectUsingRanges(), llvm::stripNullTest(), tryFactorization(), trySimplifyICmpWithAdds(), tryToFPToSat(), tryToImproveAlign(), tryToMatchAndCreateMulAccumulateReduction(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitXor(), and llvm::reassociate::XorOpnd::XorOpnd().
m_APIntAllowPoison()
ap_match< APInt > llvm::PatternMatch::m_APIntAllowPoison (const APInt *& Res) inline
Match APInt while allowing poison in splat vector constants.
Definition at line 317 of file PatternMatch.h.
Referenced by canonicalizeSaturatedAddUnsigned(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::decomposeBitTestICmp(), foldAndOrOfICmpEqConstantAndICmp(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), foldNegativePower2AndShiftedMask(), foldRoundUpIntegerWithPow2Alignment(), llvm::X86TTIImpl::getIntrinsicInstrCost(), impliesPoisonOrCond(), llvm::simplifyBinaryIntrinsic(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithConstant(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitXor().
m_APIntForbidPoison()
ap_match< APInt > llvm::PatternMatch::m_APIntForbidPoison (const APInt *& Res) inline
Match APInt while forbidding poison in splat vector constants.
Definition at line 322 of file PatternMatch.h.
Referenced by impliesPoisonOrCond().
m_Argument()
template<unsigned OpI, typename Opnd_t> Argument_match< Opnd_t > llvm::PatternMatch::m_Argument (const Opnd_t & Op) inline
Match an argument.
Definition at line 2750 of file PatternMatch.h.
Referenced by m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), and m_Intrinsic().
m_AShr()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::AShr > llvm::PatternMatch::m_AShr (const LHS & L, const RHS & R) inline
Definition at line 1352 of file PatternMatch.h.
References LHS, and RHS.
Referenced by canonicalizeAbs(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldAddWithConstant(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldSelectICmpLshrAshr(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::X86TTIImpl::isProfitableToSinkOperands(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), matchOrConcat(), llvm::simplifyBinaryIntrinsic(), simplifyGEPInst(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitXor().
m_AShrOrSelf()
template<typename LHS> ShiftLike_match< LHS, Instruction::AShr > llvm::PatternMatch::m_AShrOrSelf (const LHS & L, uint64_t & R) inline
Matches ashr L, ConstShAmt or L itself (R will be set to zero in this case).
Definition at line 1391 of file PatternMatch.h.
References LHS.
m_BasicBlock() [1/3]
class_match< BasicBlock > llvm::PatternMatch::m_BasicBlock () inline
Match an arbitrary basic block value and ignore it.
Definition at line 222 of file PatternMatch.h.
Referenced by llvm::canPeelLastIteration(), canProveExitOnFirstIteration(), collectUnswitchCandidatesWithInjections(), computeKnownBitsFromOperator(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), foldSelectToPhiImpl(), llvm::SCEVExpander::hasRelatedExistingExpansion(), isProcessableCondBI(), and m_Br().
m_BasicBlock() [2/3]
bind_ty< BasicBlock > llvm::PatternMatch::m_BasicBlock (BasicBlock *& V) inline
Match a basic block value, capturing it if we match.
Definition at line 926 of file PatternMatch.h.
m_BasicBlock() [3/3]
bind_ty< const BasicBlock > llvm::PatternMatch::m_BasicBlock (const BasicBlock *& V) inline
Definition at line 927 of file PatternMatch.h.
m_BinOp() [1/5]
class_match< BinaryOperator > llvm::PatternMatch::m_BinOp () inline
Match an arbitrary binary operation and ignore it.
Definition at line 113 of file PatternMatch.h.
Referenced by cheapToScalarize(), combineAdd(), combineOr(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::findHistogram(), foldAndToXor(), llvm::InstCombinerImpl::foldBinOpSelectBinOp(), foldBitCastBitwiseLogic(), foldComplexAndOrPatterns(), foldDependentIVs(), llvm::InstCombinerImpl::foldFMulReassoc(), llvm::InstCombinerImpl::foldICmpBinOp(), foldMulShl1(), foldSelectBinOpIdentity(), foldSelectFunnelShift(), foldSelectICmpAndBinOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), foldTwoEntryPHINode(), llvm::InstCombinerImpl::foldVectorBinop(), instCombineSVELast(), isInstructionPairMul(), llvm::isSplatValue(), matchesSquareSum(), matchLogicBlend(), matchRdxBop(), NegateValue(), passingValueIsAlwaysUndefined(), reassociateFCmps(), reassociateForUses(), simplifyAndInst(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), llvm::InstCombinerImpl::simplifyBinOpSplats(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitShl(), and llvm::InstCombinerImpl::visitSub().
m_BinOp() [2/5]
bind_ty< BinaryOperator > llvm::PatternMatch::m_BinOp (BinaryOperator *& I) inline
Match a binary operator, capturing it if we match.
Definition at line 897 of file PatternMatch.h.
References I.
m_BinOp() [3/5]
bind_ty< const BinaryOperator > llvm::PatternMatch::m_BinOp (const BinaryOperator *& I) inline
Definition at line 898 of file PatternMatch.h.
References I.
m_BinOp() [4/5]
template<typename LHS, typename RHS> AnyBinaryOp_match< LHS, RHS > llvm::PatternMatch::m_BinOp (const LHS & L, const RHS & R) inline
Definition at line 1154 of file PatternMatch.h.
References LHS, and RHS.
m_BinOp() [5/5]
template<typename LHS, typename RHS> SpecificBinaryOp_match< LHS, RHS > llvm::PatternMatch::m_BinOp (unsigned Opcode, const LHS & L, const RHS & R) inline
Matches a specific opcode.
Definition at line 1522 of file PatternMatch.h.
References LHS, and RHS.
m_BitCast()
template<typename OpTy> CastOperator_match< OpTy, Instruction::BitCast > llvm::PatternMatch::m_BitCast (const OpTy & Op) inline
Matches BitCast.
Definition at line 2176 of file PatternMatch.h.
Referenced by combineCastedMaskArithmetic(), combineSCALAR_TO_VECTOR(), foldBitCastBitwiseLogic(), foldBitCastSelect(), foldIdentityExtractShuffle(), foldReductionIdiom(), foldSelectCmpBitcasts(), foldTruncShuffle(), foldVecTruncToExtElt(), isUsedWithinShuffleVector(), matchSubIntegerPackFromVector(), performBitcastCombine(), performCTPOPCombine(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitInsertElementInst(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
m_BitReverse()
template<typename Opnd0> m_Intrinsic_Ty< Opnd0 >::Ty llvm::PatternMatch::m_BitReverse (const Opnd0 & Op0) inline
Definition at line 2879 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by collectBitParts(), foldCtpop(), foldCttzCtlz(), matchOrConcat(), and simplifyUnaryIntrinsic().
m_BitwiseLogic()
template<typename LHS, typename RHS> BinOpPred_match< LHS, RHS, is_bitwiselogic_op > llvm::PatternMatch::m_BitwiseLogic (const LHS & L, const RHS & R) inline
Matches bitwise logic operations.
Definition at line 1693 of file PatternMatch.h.
References LHS, and RHS.
Referenced by combineCastedMaskArithmetic(), foldBitOrderCrossLogicOp(), and foldBitOrderCrossLogicOp().
m_Br() [1/2]
template<typename Cond_t> brc_match< Cond_t, bind_ty< BasicBlock >, bind_ty< BasicBlock > > llvm::PatternMatch::m_Br (const Cond_t & C, BasicBlock *& T, BasicBlock *& F) inline
Definition at line 2402 of file PatternMatch.h.
References llvm::CallingConv::C, F, m_BasicBlock(), and T.
Referenced by llvm::canPeelLastIteration(), canProveExitOnFirstIteration(), collectUnswitchCandidatesWithInjections(), computeKnownBitsFromOperator(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), foldGuardedFunnelShift(), foldICmpWithDominatingICmp(), foldSelectToPhiImpl(), getAppleRuntimeUnrollPreferences(), getDomPredecessorCondition(), llvm::SCEVExpander::hasRelatedExistingExpansion(), isLoopNeverExecuted(), isProcessableCondBI(), and tryToMoveFreeBeforeNullTest().
m_Br() [2/2]
template<typename Cond_t, typename TrueBlock_t, typename FalseBlock_t> brc_match< Cond_t, TrueBlock_t, FalseBlock_t > llvm::PatternMatch::m_Br (const Cond_t & C, const TrueBlock_t & T, const FalseBlock_t & F) inline
Definition at line 2409 of file PatternMatch.h.
References llvm::CallingConv::C, F, and T.
m_BSwap()
template<typename Opnd0> m_Intrinsic_Ty< Opnd0 >::Ty llvm::PatternMatch::m_BSwap (const Opnd0 & Op0) inline
Definition at line 2884 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by collectBitParts(), foldCtpop(), matchOrConcat(), llvm::recognizeBSwapOrBitReverseIdiom(), simplifyUnaryIntrinsic(), and llvm::InstCombinerImpl::visitCallInst().
m_c_Add()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Add, true > llvm::PatternMatch::m_c_Add (const LHS & L, const RHS & R) inline
Matches a Add with LHS and RHS in either order.
Definition at line 3001 of file PatternMatch.h.
References LHS, and RHS.
Referenced by canonicalizeAbs(), llvm::VPlanTransforms::canonicalizeEVLLoops(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), combineAddSubWithShlAddSub(), detectShiftUntilZeroIdiom(), foldBoxMultiply(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), foldMulHigh(), foldSelectWithSRem(), foldSubOfMinMax(), foldToUnsignedSaturatedAdd(), foldUnsignedUnderflowCheck(), getKnownBitsFromAndXorOr(), getOptimizableIVOf(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::AArch64TTIImpl::isExtPartOfAvgExpr(), isImpliedCondICmps(), isTruePredicate(), matchesAdd(), shouldExpandCmpArithRMWInIR(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithIntrinsicOnLHS(), simplifyOrInst(), simplifyRecipe(), tryToRecognizePopCount(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitIntToPtr(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitSub().
m_c_And()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::And, true > llvm::PatternMatch::m_c_And (const LHS & L, const RHS & R) inline
Matches an And with LHS and RHS in either order.
Definition at line 3015 of file PatternMatch.h.
References LHS, and RHS.
Referenced by computeKnownBitsFromCmp(), detectShiftUntilBitTestIdiom(), dropRedundantMaskingOfLeftShiftInput(), FindSingleBitChange(), foldAndToXor(), foldAnyOrAllBitsSet(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpAndConstant(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpPow2Test(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), foldOrToXor(), foldSelectICmpAndAnd(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectZeroOrFixedOp(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldXorToXor(), getKnownBitsFromAndXorOr(), llvm::AMDGPUTargetMachine::getPredicatedAddrSpace(), haveNoCommonBitsSetSpecialCases(), llvm::isKnownToBeAPowerOfTwo(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), isSignificantBitCheckWellFormed(), isTruePredicate(), matchICmpOperand(), shouldExpandCmpArithRMWInIR(), simplifyOrLogic(), simplifyXorInst(), tryToRecognizeTableBasedCttz(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitXor().
m_c_BinOp() [1/2]
template<typename LHS, typename RHS> AnyBinaryOp_match< LHS, RHS, true > llvm::PatternMatch::m_c_BinOp (const LHS & L, const RHS & R) inline
Matches a BinaryOperator with LHS and RHS in either order.
Definition at line 2974 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::SCEVExpander::canReuseFlagsFromOriginalIVInc(), combineAdd(), combineBasicSADPattern(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldComplexAndOrPatterns(), foldDependentIVs(), foldSelectBinOpIdentity(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), getInvertibleOperands(), getKnownBitsFromAndXorOr(), matchDeMorgansLaws(), matchesSquareSum(), reassociateForUses(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::stripNullTest(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSDiv().
m_c_BinOp() [2/2]
template<typename LHS, typename RHS> SpecificBinaryOp_match< LHS, RHS, true > llvm::PatternMatch::m_c_BinOp (unsigned Opcode, const LHS & L, const RHS & R) inline
Matches a specific opcode with LHS and RHS in either order.
Definition at line 2995 of file PatternMatch.h.
References LHS, and RHS.
m_c_BitwiseLogic()
template<typename LHS, typename RHS> BinOpPred_match< LHS, RHS, is_bitwiselogic_op, true > llvm::PatternMatch::m_c_BitwiseLogic (const LHS & L, const RHS & R) inline
Matches bitwise logic operations in either order.
Definition at line 1700 of file PatternMatch.h.
References LHS, and RHS.
m_c_DisjointOr()
template<typename LHS, typename RHS> DisjointOr_match< LHS, RHS, true > llvm::PatternMatch::m_c_DisjointOr (const LHS & L, const RHS & R) inline
Definition at line 1553 of file PatternMatch.h.
References LHS, and RHS.
Referenced by simplifyShiftSelectingPackedElement(), and llvm::InstCombinerImpl::visitOr().
m_c_FAdd()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FAdd, true > llvm::PatternMatch::m_c_FAdd (const LHS & L, const RHS & R) inline
Matches FAdd with LHS and RHS in either order.
Definition at line 3111 of file PatternMatch.h.
References LHS, and RHS.
Referenced by factorizeLerp(), simplifyFSubInst(), llvm::InstCombinerImpl::visitFAdd(), and llvm::InstCombinerImpl::visitFSub().
m_c_FMul()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FMul, true > llvm::PatternMatch::m_c_FMul (const LHS & L, const RHS & R) inline
Matches FMul with LHS and RHS in either order.
Definition at line 3118 of file PatternMatch.h.
References LHS, and RHS.
Referenced by factorizeFAddFSub(), factorizeLerp(), llvm::InstCombinerImpl::foldFMulReassoc(), foldMulSelectToNegate(), llvm::InstCombinerImpl::foldPowiReassoc(), matchFMulByZeroIfResultEqZero(), simplifyFDivInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), and llvm::InstCombinerImpl::visitFSub().
m_c_ICmp() [1/2]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, ICmpInst, true > llvm::PatternMatch::m_c_ICmp (CmpPredicate & Pred, const LHS & L, const RHS & R) inline
Matches an ICmp with a predicate over LHS and RHS in either order.
Swaps the predicate if operands are commuted.
Definition at line 2982 of file PatternMatch.h.
References LHS, and RHS.
Referenced by computeKnownBitsFromOperator(), foldAndOrOfICmpsWithConstEq(), foldAndOrOfICmpsWithPow2AndWithZero(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), foldICmpWithHighBitMask(), foldICmpWithTruncSignExtendedVal(), foldICmpXNegX(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectWithExtremeEqCond(), foldUnsignedUnderflowCheck(), llvm::isKnownInversion(), isKnownNonNullFromDominatingCondition(), isKnownNonZeroFromAssume(), isKnownNonZeroFromOperator(), shouldExpandCmpArithRMWInIR(), simplifyUnsignedRangeCheck(), llvm::InstCombinerImpl::visitAdd(), and llvm::InstCombinerImpl::visitICmpInst().
m_c_ICmp() [2/2]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, ICmpInst, true > llvm::PatternMatch::m_c_ICmp (const LHS & L, const RHS & R) inline
Definition at line 2987 of file PatternMatch.h.
References LHS, and RHS.
m_c_Intrinsic()
template<Intrinsic::ID IntrID, typename T0, typename T1> CommutativeBinaryIntrinsic_match< IntrID, T0, T1 > llvm::PatternMatch::m_c_Intrinsic (const T0 & Op0, const T1 & Op1) inline
Definition at line 3104 of file PatternMatch.h.
References Op0, and T1.
Referenced by foldSelectZeroOrFixedOp(), llvm::InstCombinerImpl::visitFAdd(), and llvm::InstCombinerImpl::visitFMul().
m_c_LogicalAnd()
template<typename LHS, typename RHS> LogicalOp_match< LHS, RHS, Instruction::And, true > llvm::PatternMatch::m_c_LogicalAnd (const LHS & L, const RHS & R) inline
Matches L && R with LHS and RHS in either order.
Definition at line 3290 of file PatternMatch.h.
References LHS, and RHS.
Referenced by foldNestedSelects(), llvm::InstCombinerImpl::foldSelectOfBools(), simplifyOrLogic(), and simplifySelectInst().
m_c_LogicalOp()
template<typename LHS, typename RHS> auto llvm::PatternMatch::m_c_LogicalOp (const LHS & L, const RHS & R) inline
Matches either L && R or L || R with LHS and RHS in either order.
Definition at line 3327 of file PatternMatch.h.
References LHS, m_LogicalOp(), and RHS.
Referenced by foldNestedSelects().
m_c_LogicalOr()
template<typename LHS, typename RHS> LogicalOp_match< LHS, RHS, Instruction::Or, true > llvm::PatternMatch::m_c_LogicalOr (const LHS & L, const RHS & R) inline
Matches L || R with LHS and RHS in either order.
Definition at line 3308 of file PatternMatch.h.
References LHS, and RHS.
Referenced by foldNestedSelects(), llvm::InstCombinerImpl::foldSelectOfBools(), simplifyOrLogic(), and simplifySelectInst().
m_c_MaxOrMin()
template<typename LHS, typename RHS> match_combine_or< match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty, true >, MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty, true > >, match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty, true >, MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty, true > > > llvm::PatternMatch::m_c_MaxOrMin (const LHS & L, const RHS & R) inline
Definition at line 3081 of file PatternMatch.h.
References LHS, m_c_SMax(), m_c_SMin(), m_c_UMax(), m_c_UMin(), m_CombineOr(), and RHS.
Referenced by foldMinMaxSharedOp(), reassociateMinMaxWithConstantInOperand(), simplifyCmpSelOfMaxMin(), and llvm::InstCombinerImpl::visitSub().
m_c_Mul()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Mul, true > llvm::PatternMatch::m_c_Mul (const LHS & L, const RHS & R) inline
Matches a Mul with LHS and RHS in either order.
Definition at line 3008 of file PatternMatch.h.
References LHS, and RHS.
Referenced by checkOuterLoopInsts(), llvm::InstCombinerImpl::commonIDivTransforms(), computeKnownBitsFromLerpPattern(), foldBoxMultiply(), llvm::InstCombinerImpl::foldICmpBinOp(), foldIDivShl(), foldMulHigh(), foldMulSelectToNegate(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldSelectZeroOrFixedOp(), matchExpandedRem(), simplifyDivRem(), simplifyRecipe(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitMul().
m_c_NSWAdd()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap, true > llvm::PatternMatch::m_c_NSWAdd (const LHS & L, const RHS & R) inline
Definition at line 1434 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, and RHS.
Referenced by llvm::InstCombinerImpl::visitSub().
m_c_NUWAdd()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap, true > llvm::PatternMatch::m_c_NUWAdd (const LHS & L, const RHS & R) inline
Definition at line 1476 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and RHS.
Referenced by computeKnownBitsFromCmp(), and isRemOfLoopIncrementWithLoopInvariant().
m_c_Or()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Or, true > llvm::PatternMatch::m_c_Or (const LHS & L, const RHS & R) inline
Matches an Or with LHS and RHS in either order.
Definition at line 3022 of file PatternMatch.h.
References LHS, and RHS.
Referenced by computeKnownBitsFromCmp(), foldAndToXor(), foldCopySignIdioms(), foldCtpop(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpOrXX(), foldLoadsRecursive(), FoldOrOfSelectSmaxToAbs(), foldOrToXor(), foldOrUnsignedUMulOverflowICmp(), llvm::InstCombinerImpl::foldSelectOfBools(), foldXorToXor(), haveNoCommonBitsSetSpecialCases(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), isTruePredicate(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), matchesOr(), matchICmpOperand(), shouldExpandCmpArithRMWInIR(), simplifyAndCommutative(), simplifyAndInst(), simplifyICmpWithBinOpOnLHS(), simplifyLShrInst(), simplifyOrLogic(), simplifyXorInst(), splitMergedValStore(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitXor().
m_c_Select()
template<typename LHS, typename RHS> ThreeOps_match< decltype(m_Value()), LHS, RHS, Instruction::Select, true > llvm::PatternMatch::m_c_Select (const LHS & L, const RHS & R) inline
Match Select(C, LHS, RHS) or Select(C, RHS, LHS).
Definition at line 1970 of file PatternMatch.h.
References LHS, m_Value(), and RHS.
Referenced by foldTwoEntryPHINode(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFreeze(), and llvm::InstCombinerImpl::visitSub().
m_c_SMax()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty, true > llvm::PatternMatch::m_c_SMax (const LHS & L, const RHS & R) inline
Matches an SMax with LHS and RHS in either order.
Definition at line 3059 of file PatternMatch.h.
References LHS, and RHS.
Referenced by isTruePredicate(), m_c_MaxOrMin(), and llvm::InstCombinerImpl::visitSub().
m_c_SMin()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty, true > llvm::PatternMatch::m_c_SMin (const LHS & L, const RHS & R) inline
Matches an SMin with LHS and RHS in either order.
Definition at line 3053 of file PatternMatch.h.
References LHS, and RHS.
Referenced by isTruePredicate(), m_c_MaxOrMin(), and llvm::InstCombinerImpl::visitSub().
m_c_SpecificICmp()
template<typename LHS, typename RHS> SpecificCmpClass_match< LHS, RHS, ICmpInst, true > llvm::PatternMatch::m_c_SpecificICmp (CmpPredicate MatchPred, const LHS & L, const RHS & R) inline
Definition at line 1849 of file PatternMatch.h.
References LHS, and RHS.
m_c_UMax()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty, true > llvm::PatternMatch::m_c_UMax (const LHS & L, const RHS & R) inline
Matches a UMax with LHS and RHS in either order.
Definition at line 3071 of file PatternMatch.h.
References LHS, and RHS.
Referenced by isTruePredicate(), m_c_MaxOrMin(), and llvm::InstCombinerImpl::visitSub().
m_c_UMin()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty, true > llvm::PatternMatch::m_c_UMin (const LHS & L, const RHS & R) inline
Matches a UMin with LHS and RHS in either order.
Definition at line 3065 of file PatternMatch.h.
References LHS, and RHS.
Referenced by foldToUnsignedSaturatedAdd(), isTruePredicate(), m_c_MaxOrMin(), and llvm::InstCombinerImpl::visitSub().
m_c_Xor()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Xor, true > llvm::PatternMatch::m_c_Xor (const LHS & L, const RHS & R) inline
Matches an Xor with LHS and RHS in either order.
Definition at line 3029 of file PatternMatch.h.
References LHS, and RHS.
Referenced by foldComplexAndOrPatterns(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldICmpXorXX(), foldXorToXor(), getKnownBitsFromAndXorOr(), haveNoCommonBitsSetSpecialCases(), isConditionalOnXorOfPHIs(), isMaskOrZero(), isSignificantBitCheckWellFormed(), m_Not(), m_NotForbidPoison(), shouldExpandCmpArithRMWInIR(), simplifyAndInst(), simplifyOrLogic(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitXor().
m_c_XorLike()
template<typename LHS, typename RHS> auto llvm::PatternMatch::m_c_XorLike (const LHS & L, const RHS & R) inline
Match either (xor L, R), (xor R, L) or (sub nuw R, L) iff R.isMask() Only commutative matcher as the sub will need to swap the L and R.
Definition at line 1610 of file PatternMatch.h.
References LHS, and RHS.
m_CastOrSelf()
template<typename OpTy> match_combine_or< CastInst_match< OpTy, CastInst >, OpTy > llvm::PatternMatch::m_CastOrSelf (const OpTy & Op) inline
Matches any cast or self. Used to ignore casts.
Definition at line 2243 of file PatternMatch.h.
References m_CombineOr().
Referenced by tryToRecognizeTableBasedCttz().
m_CheckedFp() [1/2]
cstfp_pred_ty< custom_checkfn< APFloat > > llvm::PatternMatch::m_CheckedFp (const Constant *& V, function_ref< bool(const APFloat &)> CheckFn) inline
Definition at line 510 of file PatternMatch.h.
m_CheckedFp() [2/2]
cstfp_pred_ty< custom_checkfn< APFloat > > llvm::PatternMatch::m_CheckedFp (function_ref< bool(const APFloat &)> CheckFn) inline
Match a float or vector where CheckFn(ele) for each element is true.
For vectors, poison elements are assumed to match.
Definition at line 505 of file PatternMatch.h.
m_CheckedInt() [1/2]
cst_pred_ty< custom_checkfn< APInt > > llvm::PatternMatch::m_CheckedInt (const Constant *& V, function_ref< bool(const APInt &)> CheckFn) inline
Definition at line 498 of file PatternMatch.h.
m_CheckedInt() [2/2]
cst_pred_ty< custom_checkfn< APInt > > llvm::PatternMatch::m_CheckedInt (function_ref< bool(const APInt &)> CheckFn) inline
Match an integer or vector where CheckFn(ele) for each element is true.
For vectors, poison elements are assumed to match.
Definition at line 493 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpCommutative(), foldMinimumOverTrailingOrLeadingZeroCount(), simplifyRem(), and llvm::InstCombinerImpl::visitMul().
m_Cmp() [1/3]
class_match< CmpInst > llvm::PatternMatch::m_Cmp () inline
Matches any compare instruction and ignore it.
Definition at line 118 of file PatternMatch.h.
Referenced by cheapToScalarize(), llvm::VPInstruction::computeCost(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::VPlanTransforms::createInLoopReductionRecipes(), foldSelectBinOpIdentity(), foldSelectCmpBitcasts(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), getHashValueImpl(), llvm::SystemZTargetLowering::getJumpConditionMergingParams(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::RecurrenceDescriptor::isAnyOfPattern(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), isEqualImpl(), llvm::RecurrenceDescriptor::isFindIVPattern(), llvm::RecurrenceDescriptor::isMinMaxPattern(), RecurrenceInfo::matchConditionalRecurrence(), planContainsAdditionalSimplifications(), simplifyRecipe(), and llvm::InstCombinerImpl::visitExtractElementInst().
m_Cmp() [2/3]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, CmpInst > llvm::PatternMatch::m_Cmp (CmpPredicate & Pred, const LHS & L, const RHS & R) inline
Definition at line 1774 of file PatternMatch.h.
References LHS, and RHS.
m_Cmp() [3/3]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, CmpInst > llvm::PatternMatch::m_Cmp (const LHS & L, const RHS & R) inline
Definition at line 1792 of file PatternMatch.h.
References LHS, and RHS.
m_CombineAnd()
template<typename LTy, typename RTy> match_combine_and< LTy, RTy > llvm::PatternMatch::m_CombineAnd (const LTy & L, const RTy & R) inline
Combine two pattern matchers matching L && R.
Definition at line 278 of file PatternMatch.h.
Referenced by detectShiftUntilBitTestIdiom(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldNestedSelects(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), matchExpandedRem(), reassociateMinMaxWithConstantInOperand(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), simplifyAndInst(), simplifyOrLogic(), simplifyXorInst(), and llvm::InstCombinerImpl::visitICmpInst().
m_CombineOr()
template<typename LTy, typename RTy> match_combine_or< LTy, RTy > llvm::PatternMatch::m_CombineOr (const LTy & L, const RTy & R) inline
Combine two pattern matchers matching L || R.
Definition at line 272 of file PatternMatch.h.
Referenced by addValueAffectedByCondition(), collectUnswitchCandidates(), computeKnownBitsFromCmp(), computeKnownBitsFromLerpPattern(), llvm::ConstantFoldBinaryInstruction(), dropRedundantMaskingOfLeftShiftInput(), foldBoxMultiply(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpWithHighBitMask(), llvm::InstCombinerImpl::foldSelectShuffle(), foldShuffleOfUnaryOps(), foldTwoEntryPHINode(), foldVecTruncToExtElt(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), hasConditionalTerminator(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::RecurrenceDescriptor::isFindIVPattern(), isKnownNonZeroFromAssume(), isMultipleOfN(), isSignificantBitCheckWellFormed(), m_AddLike(), m_AnyAdd(), m_AnyMul(), m_c_MaxOrMin(), m_CastOrSelf(), m_LogicalOp(), m_MaxOrMin(), m_NSWAddLike(), m_NUWAddLike(), m_OrdOrUnordFMax(), m_OrdOrUnordFMin(), m_PtrToIntOrAddr(), m_SExtLike(), m_SExtOrSelf(), m_TruncOrSelf(), m_ZExtOrSelf(), m_ZExtOrSExt(), m_ZExtOrSExtOrSelf(), m_ZExtOrTruncOrSelf(), markAliveBlocks(), matchesSquareSum(), matchSelectPattern(), matchZExtedSubInteger(), optimizeShiftInOrChain(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), shouldCanonicalizeGEPToPtrAdd(), llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect(), simplifyAndOrOfFCmps(), simplifyRecipe(), simplifySelectWithICmpCond(), tryToMoveFreeBeforeNullTest(), llvm::JumpThreadingPass::tryToUnfoldSelectInCurrBB(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitSelectInst().
m_Constant() [1/2]
class_match< Constant > llvm::PatternMatch::m_Constant () inline
Match an arbitrary Constant and ignore it.
Definition at line 178 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeSelectToShuffle(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::findScalarElement(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithConstEq(), foldBitCastBitwiseLogic(), foldConstantInsEltIntoShuffle(), foldFDivConstantDividend(), llvm::InstCombinerImpl::foldFMulReassoc(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEquality(), foldNoWrapAdd(), foldSelectBinOpIdentity(), llvm::InstCombinerImpl::foldSelectExtConst(), foldSelectGEP(), llvm::InstCombinerImpl::foldSelectInstWithICmp(), foldSelectIntoAddConstant(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::foldSelectValueEquivalence(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), foldShiftOfShiftedBinOp(), llvm::InstCombinerImpl::foldSignBitTest(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), getNegatibleInsts(), hoistInsEltConst(), llvm::ARMTTIImpl::instCombineIntrinsic(), lookThroughCastConst(), matchIncrement(), matchSubIntegerPackFromVector(), narrowUDivURem(), NegateValue(), recordCondition(), llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect(), simplifyAssocCastAssoc(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyLogicOfAddSub(), simplifySelectInst(), simplifyShuffleVectorInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitFSub(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitXor(), and llvm::InstCombinerImpl::visitZExt().
m_Constant() [2/2]
bind_ty< Constant > llvm::PatternMatch::m_Constant (Constant *& C) inline
Match a Constant, capturing the value if we match.
Definition at line 914 of file PatternMatch.h.
References llvm::CallingConv::C.
m_ConstantExpr() [1/2]
constantexpr_match llvm::PatternMatch::m_ConstantExpr () inline
Match a constant expression or a constant that contains a constant expression.
Definition at line 199 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldSelectOfBools(), simplifyInstructionWithPHI(), and llvm::InstCombinerImpl::visitXor().
m_ConstantExpr() [2/2]
bind_ty< ConstantExpr > llvm::PatternMatch::m_ConstantExpr (ConstantExpr *& C) inline
Match a ConstantExpr, capturing the value if we match.
Definition at line 923 of file PatternMatch.h.
References llvm::CallingConv::C.
m_ConstantFP() [1/2]
class_match< ConstantFP > llvm::PatternMatch::m_ConstantFP () inline
Match an arbitrary ConstantFP and ignore it.
Definition at line 186 of file PatternMatch.h.
Referenced by llvm::GCNTTIImpl::instCombineIntrinsic(), and matchFPExtFromF16().
m_ConstantFP() [2/2]
bind_ty< ConstantFP > llvm::PatternMatch::m_ConstantFP (ConstantFP *& C) inline
Match a ConstantFP, capturing the value if we match.
Definition at line 920 of file PatternMatch.h.
References llvm::CallingConv::C.
m_ConstantInt() [1/4]
template<int64_t Val> constantint_match< Val > llvm::PatternMatch::m_ConstantInt () inline
Match a ConstantInt with a specific value.
Definition at line 359 of file PatternMatch.h.
m_ConstantInt() [2/4]
class_match< ConstantInt > llvm::PatternMatch::m_ConstantInt () inline
Match an arbitrary ConstantInt and ignore it.
Definition at line 181 of file PatternMatch.h.
Referenced by annotateNonNullAndDereferenceable(), llvm::VPIntrinsic::canIgnoreVectorLengthParam(), canonicalizeInsertSplat(), canonicalizeScalarSelectOfVecs(), canScalarizeAccess(), cheapToScalarize(), computeKnownBitsFromCmp(), computeKnownFPClassFromCond(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), decompose(), llvm::findScalarElement(), llvm::findValuesAffectedByCondition(), foldConstantInsEltIntoShuffle(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpWithConstant(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), foldShuffleWithInsert(), foldTruncInsEltPair(), foldVecExtTruncToExtElt(), foldVecTruncToExtElt(), getKnownTypeFromMaskedOp(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), hoistInsEltConst(), instCombinePTrue(), isLoopNeverExecuted(), isMultipleOfN(), isOperandOfVmullHighP64(), isSSATMinMaxPattern(), m_SelectCst(), llvm::PatternMatch::ShiftLike_match< LHS_t, Opcode >::match(), matchesAdd(), matchesOr(), matchSubIntegerPackFromVector(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), matchZExtedSubInteger(), shouldCanonicalizeGEPToPtrAdd(), shouldSinkVScale(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyGEPInst(), simplifyRecipe(), simplifyShiftSelectingPackedElement(), simplifyShuffleVectorInst(), simplifySwitchWhenUMin(), tryToReplaceALMWithWideALM(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSwitchInst(), and llvm::InstCombinerImpl::visitXor().
m_ConstantInt() [3/4]
bind_ty< ConstantInt > llvm::PatternMatch::m_ConstantInt (ConstantInt *& CI) inline
Match a ConstantInt, capturing the value if we match.
Definition at line 917 of file PatternMatch.h.
m_ConstantInt() [4/4]
bind_const_intval_ty llvm::PatternMatch::m_ConstantInt (uint64_t & V) inline
Match a ConstantInt and bind to its value.
This does not match ConstantInts wider than 64-bits.
Definition at line 1104 of file PatternMatch.h.
m_ConstantSplat()
template<typename T> Splat_match< T > llvm::PatternMatch::m_ConstantSplat (const T & SubPattern) inline
Match a constant splat. TODO: Extend this to non-constant splats.
Definition at line 217 of file PatternMatch.h.
References T.
Referenced by llvm::InstCombinerImpl::foldVectorBinop().
m_CopySign()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_CopySign (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 2952 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by optimizeSymmetricCall(), stripSignOnlyFPOps(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitFNeg().
m_Deferred() [1/4]
deferredval_ty< BasicBlock > llvm::PatternMatch::m_Deferred (BasicBlock *const & BB) inline
A commutative-friendly version of m_Specific().
Definition at line 1124 of file PatternMatch.h.
m_Deferred() [2/4]
deferredval_ty< const BasicBlock > llvm::PatternMatch::m_Deferred (const BasicBlock *const & BB) inline
Definition at line 1128 of file PatternMatch.h.
m_Deferred() [3/4]
deferredval_ty< const Value > llvm::PatternMatch::m_Deferred (const Value *const & V) inline
Definition at line 1007 of file PatternMatch.h.
m_Deferred() [4/4]
deferredval_ty< Value > llvm::PatternMatch::m_Deferred (Value *const & V) inline
Like m_Specific(), but works if the specific value to match is determined as part of the same match() expression.
For example: m_Add(m_Value(X), m_Specific(X)) is incorrect, because m_Specific() will bind X before the pattern match starts. m_Add(m_Value(X), m_Deferred(X)) is correct, and will check against whichever value m_Value(X) populated.
Definition at line 1006 of file PatternMatch.h.
Referenced by combineAndXorSubWithBMI(), combineBasicSADPattern(), combineXorToBitfieldInsert(), dropRedundantMaskingOfLeftShiftInput(), factorizeLerp(), foldAndToUsubsat(), foldAndToXor(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldFMulReassoc(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), foldICmpWithTruncSignExtendedVal(), foldICmpXNegX(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), foldMaskedMerge(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldOrUnsignedUMulOverflowICmp(), llvm::InstCombinerImpl::foldPowiReassoc(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectOfSymmetricSelect(), foldToUnsignedSaturatedAdd(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldXorToXor(), getKnownBitsFromAndXorOr(), llvm::AMDGPUTargetMachine::getPredicatedAddrSpace(), haveNoCommonBitsSetSpecialCases(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), isMaskOrZero(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), matchesSquareSum(), matchExpandedRem(), matchLogicBlend(), narrowBitOpRMW(), PerformSELECTShiftCombine(), simplifyAndInst(), simplifyCastInst(), simplifyRecipe(), simplifySelectWithICmpCond(), llvm::stripNullTest(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitXor().
m_Deinterleave2()
template<typename Opnd> m_Intrinsic_Ty< Opnd >::Ty llvm::PatternMatch::m_Deinterleave2 (const Opnd & Op) inline
Definition at line 3225 of file PatternMatch.h.
References m_Intrinsic().
m_DisjointOr()
template<typename LHS, typename RHS> DisjointOr_match< LHS, RHS > llvm::PatternMatch::m_DisjointOr (const LHS & L, const RHS & R) inline
Definition at line 1548 of file PatternMatch.h.
References LHS, and RHS.
Referenced by decompose(), llvm::InstCombinerImpl::foldAddWithConstant(), m_AddLike(), m_NSWAddLike(), m_NUWAddLike(), llvm::InstCombinerImpl::tryFoldInstWithCtpopWithNot(), and llvm::InstCombinerImpl::visitXor().
m_ElementWiseBitCast()
template<typename OpTy> ElementWiseBitCast_match< OpTy > llvm::PatternMatch::m_ElementWiseBitCast (const OpTy & Op) inline
Definition at line 2204 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::commonCastTransforms(), computeKnownBitsFromOperator(), computeKnownFPClass(), computeKnownFPClassFromCond(), llvm::findValuesAffectedByCondition(), foldCopySignIdioms(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldSelectToCopysign(), foldSelectWithFCmpToFabs(), simplifyICmpWithConstant(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitXor().
m_Exact()
template<typename T> Exact_match< T > llvm::PatternMatch::m_Exact (const T & SubPattern) inline
Definition at line 1733 of file PatternMatch.h.
References T.
Referenced by foldCttzCtlz(), simplifyMulInst(), simplifyShlInst(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitShl(), and llvm::InstCombinerImpl::visitUDiv().
m_ExtractElt()
template<typename Val_t, typename Idx_t> TwoOps_match< Val_t, Idx_t, Instruction::ExtractElement > llvm::PatternMatch::m_ExtractElt (const Val_t & Val, const Idx_t & Idx) inline
Matches ExtractElementInst.
Definition at line 1992 of file PatternMatch.h.
Referenced by canonicalizeBitCastExtElt(), canonicalizeScalarSelectOfVecs(), foldInsEltIntoIdentityShuffle(), foldVecExtTruncToExtElt(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), isAddSubOrSubAdd(), isOperandOfVmullHighP64(), lowerBUILD_VECTOR(), matchPMADDWD(), matchPMADDWD_2(), matchSubIntegerPackFromVector(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::simplifyInsertElementInst(), and llvm::InstCombinerImpl::visitInsertElementInst().
m_ExtractValue() [1/2]
template<typename Val_t> ExtractValue_match<-1, Val_t > llvm::PatternMatch::m_ExtractValue (const Val_t & V) inline
Match an ExtractValue instruction with any index.
For example m_ExtractValue(...)
Definition at line 3188 of file PatternMatch.h.
m_ExtractValue() [2/2]
template<int Ind, typename Val_t> ExtractValue_match< Ind, Val_t > llvm::PatternMatch::m_ExtractValue (const Val_t & V) inline
Match a single index ExtractValue instruction.
For example m_ExtractValue<1>(...)
Definition at line 3181 of file PatternMatch.h.
Referenced by directlyImpliesPoison(), dominatesMergePoint(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), foldICmpOfUAddOv(), foldOrUnsignedUMulOverflowICmp(), foldOverflowingAddSubSelect(), isKnownNonZeroFromOperator(), matchIncrement(), llvm::patchReplacementInstruction(), replaceSubOverflowUses(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractValueInst(), and llvm::InstCombinerImpl::visitOr().
m_FAbs()
template<typename Opnd0> m_Intrinsic_Ty< Opnd0 >::Ty llvm::PatternMatch::m_FAbs (const Opnd0 & Op0) inline
Definition at line 2889 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::findValuesAffectedByCondition(), foldFabsWithFcmpZero(), foldShuffleOfUnaryOps(), llvm::GCNTTIImpl::isProfitableToSinkOperands(), optimizeSymmetricCall(), simplifyAndOrOfFCmps(), stripSignOnlyFPOps(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitFDiv().
m_FAdd()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FAdd > llvm::PatternMatch::m_FAdd (const LHS & L, const RHS & R) inline
Definition at line 1214 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::foldFMulReassoc(), foldFNegIntoConstant(), foldSelectIntoAddConstant(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), m_AnyAdd(), llvm::InstCombinerImpl::visitFAdd(), and llvm::InstCombinerImpl::visitFCmpInst().
m_FCanonicalize()
template<typename Opnd0> m_Intrinsic_Ty< Opnd0 >::Ty llvm::PatternMatch::m_FCanonicalize (const Opnd0 & Op0) inline
Definition at line 2894 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
m_FCmp() [1/2]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, FCmpInst > llvm::PatternMatch::m_FCmp (CmpPredicate & Pred, const LHS & L, const RHS & R) inline
Definition at line 1786 of file PatternMatch.h.
References LHS, and RHS.
Referenced by computeKnownFPClassFromCond(), llvm::findValuesAffectedByCondition(), foldSelectIntoAddConstant(), foldSelectWithFCmpToFabs(), reassociateFCmps(), simplifySelectWithFCmp(), and llvm::InstCombinerImpl::visitBranchInst().
m_FCmp() [2/2]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, FCmpInst > llvm::PatternMatch::m_FCmp (const LHS & L, const RHS & R) inline
Definition at line 1802 of file PatternMatch.h.
References LHS, and RHS.
m_FDiv()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FDiv > llvm::PatternMatch::m_FDiv (const LHS & L, const RHS & R) inline
Definition at line 1298 of file PatternMatch.h.
References LHS, and RHS.
Referenced by convertFSqrtDivIntoFMul(), factorizeFAddFSub(), foldFDivConstantDividend(), foldFDivSqrtDivisor(), llvm::InstCombinerImpl::foldFMulReassoc(), foldFNegIntoConstant(), getFSqrtDivOptPattern(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFDiv(), and llvm::InstCombinerImpl::visitFSub().
m_Finite() [1/2]
cstfp_pred_ty< is_finite > llvm::PatternMatch::m_Finite () inline
Match a finite FP constant, i.e.
not infinity or NaN. For vectors, this includes constants with undefined elements.
Definition at line 756 of file PatternMatch.h.
m_Finite() [2/2]
apf_pred_ty< is_finite > llvm::PatternMatch::m_Finite (const APFloat *& V) inline
Definition at line 759 of file PatternMatch.h.
m_FiniteNonZero() [1/2]
cstfp_pred_ty< is_finitenonzero > llvm::PatternMatch::m_FiniteNonZero () inline
Match a finite non-zero FP constant.
For vectors, this includes constants with undefined elements.
Definition at line 766 of file PatternMatch.h.
Referenced by llvm::GCNTTIImpl::canSimplifyLegacyMulToMul().
m_FiniteNonZero() [2/2]
apf_pred_ty< is_finitenonzero > llvm::PatternMatch::m_FiniteNonZero (const APFloat *& V) inline
Definition at line 769 of file PatternMatch.h.
m_FMaximum()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMaximum (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 2923 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern(), and matchRdxBop().
m_FMaximumNum()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMaximumNum (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 2930 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern().
m_FMaxNum()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMaxNum (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 2917 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern(), and matchRdxBop().
m_FMinimum()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMinimum (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 2905 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern(), and matchRdxBop().
m_FMinimumNum()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMinimumNum (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 2912 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern().
m_FMinNum()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMinNum (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 2899 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern(), and matchRdxBop().
m_FMul()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FMul > llvm::PatternMatch::m_FMul (const LHS & L, const RHS & R) inline
Definition at line 1280 of file PatternMatch.h.
References LHS, and RHS.
Referenced by factorizeFAddFSub(), foldFDivConstantDividend(), foldFNegIntoConstant(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), getFSqrtDivOptPattern(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), isInstructionPairMul(), m_AnyMul(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFMul(), and llvm::InstCombinerImpl::visitFSub().
m_FNeg()
template<typename OpTy> FNeg_match< OpTy > llvm::PatternMatch::m_FNeg (const OpTy & X) inline
Match 'fneg X' as 'fsub -0.0, X'.
Definition at line 1262 of file PatternMatch.h.
References X.
Referenced by llvm::findValuesAffectedByCondition(), foldFCmpFNegCommonOp(), foldFDivConstantDividend(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSelectWithFCmpToFabs(), foldShuffleOfUnaryOps(), llvm::InstCombiner::getComplexity(), isFNeg(), isNeg(), llvm::ARMTTIImpl::isProfitableToSinkOperands(), llvm::GCNTTIImpl::isProfitableToSinkOperands(), LinearizeExprTree(), NegateValue(), optimizeSymmetricCall(), llvm::RISCVTargetLowering::PerformDAGCombine(), ShouldBreakUpSubtract(), llvm::simplifyBinaryIntrinsic(), simplifyFAddInst(), simplifyFNegInst(), simplifyFSubInst(), stripSignOnlyFPOps(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), and llvm::InstCombinerImpl::visitFSub().
m_FNegNSZ()
template<typename RHS> BinaryOp_match< cstfp_pred_ty< is_any_zero_fp >, RHS, Instruction::FSub > llvm::PatternMatch::m_FNegNSZ (const RHS & X) inline
Match 'fneg X' as 'fsub +-0.0, X'.
Definition at line 1269 of file PatternMatch.h.
References m_AnyZeroFP(), m_FSub(), RHS, and X.
Referenced by simplifyFDivInst().
m_FPExt()
template<typename OpTy> CastInst_match< OpTy, FPExtInst > llvm::PatternMatch::m_FPExt (const OpTy & Op) inline
Definition at line 2358 of file PatternMatch.h.
Referenced by canSafelyConvertTo16Bit(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::GCNTTIImpl::instCombineIntrinsic(), matchFPExtFromF16(), narrowInsElt(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFPTrunc(), and llvm::InstCombinerImpl::visitFSub().
m_FPOne()
specific_fpval llvm::PatternMatch::m_FPOne () inline
Match a float 1.0 or vector with all elements equal to 1.0.
Definition at line 1034 of file PatternMatch.h.
References m_SpecificFP().
Referenced by factorizeLerp(), llvm::GCNTTIImpl::getArithmeticInstrCost(), getFSqrtDivOptPattern(), simplifyFDivInst(), and simplifyFMAFMul().
m_FPToSI()
template<typename OpTy> CastInst_match< OpTy, FPToSIInst > llvm::PatternMatch::m_FPToSI (const OpTy & Op) inline
Definition at line 2348 of file PatternMatch.h.
Referenced by isKnownExactCastIntToFP(), and tryToFPToSat().
m_FPToUI()
template<typename OpTy> CastInst_match< OpTy, FPToUIInst > llvm::PatternMatch::m_FPToUI (const OpTy & Op) inline
Definition at line 2343 of file PatternMatch.h.
Referenced by isKnownExactCastIntToFP().
m_FPTrunc()
template<typename OpTy> CastInst_match< OpTy, FPTruncInst > llvm::PatternMatch::m_FPTrunc (const OpTy & Op) inline
Definition at line 2353 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpBitCast(), and llvm::InstCombinerImpl::visitFSub().
m_Freeze()
template<typename OpTy> OneOps_match< OpTy, Instruction::Freeze > llvm::PatternMatch::m_Freeze (const OpTy & Op) inline
Matches FreezeInst.
Definition at line 1977 of file PatternMatch.h.
Referenced by getStartValueFromReductionResult(), and llvm::InstCombinerImpl::visitFreeze().
m_FRem()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FRem > llvm::PatternMatch::m_FRem (const LHS & L, const RHS & R) inline
Definition at line 1316 of file PatternMatch.h.
References LHS, and RHS.
m_FShl()
template<typename Opnd0, typename Opnd1, typename Opnd2> m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty llvm::PatternMatch::m_FShl (const Opnd0 & Op0, const Opnd1 & Op1, const Opnd2 & Op2) inline
Definition at line 2936 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by collectBitParts(), foldCtpop(), foldSelectZeroOrFixedOp(), llvm::recognizeBSwapOrBitReverseIdiom(), simplifySelectWithICmpCond(), and llvm::InstCombinerImpl::visitCallInst().
m_FShr()
template<typename Opnd0, typename Opnd1, typename Opnd2> m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty llvm::PatternMatch::m_FShr (const Opnd0 & Op0, const Opnd1 & Op1, const Opnd2 & Op2) inline
Definition at line 2942 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by collectBitParts(), foldCtpop(), foldSelectZeroOrFixedOp(), llvm::recognizeBSwapOrBitReverseIdiom(), and simplifySelectWithICmpCond().
m_FSub()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FSub > llvm::PatternMatch::m_FSub (const LHS & L, const RHS & R) inline
Definition at line 1226 of file PatternMatch.h.
References LHS, and RHS.
Referenced by factorizeLerp(), llvm::InstCombinerImpl::foldFMulReassoc(), foldSelectWithFCmpToFabs(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), m_FNegNSZ(), simplifyFAddInst(), simplifyFSubInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFNeg(), and llvm::InstCombinerImpl::visitFSub().
m_GEP()
template<typename... OperandTypes> auto llvm::PatternMatch::m_GEP (const OperandTypes &... Ops) inline
Matches GetElementPtrInst.
Definition at line 2092 of file PatternMatch.h.
References AbstractManglingParser< Derived, Alloc >::Ops.
Referenced by foldDependentIVs(), and processUse().
m_ICmp() [1/2]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, ICmpInst > llvm::PatternMatch::m_ICmp (CmpPredicate & Pred, const LHS & L, const RHS & R) inline
Definition at line 1780 of file PatternMatch.h.
References LHS, and RHS.
Referenced by analyzeICmp(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::canPeelLastIteration(), checkOrAndOpImpliedByOther(), collectUnswitchCandidatesWithInjections(), computeKnownFPClassFromCond(), countToEliminateCompares(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), llvm::findValuesAffectedByCondition(), foldAddToAshr(), foldAndOrOfICmpsWithConstEq(), foldAndOrOfICmpsWithPow2AndWithZero(), foldBitCeil(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOrChain(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldIsPowerOf2OrZero(), llvm::InstCombinerImpl::foldOpIntoPhi(), foldOverflowingAddSubSelect(), foldReductionIdiom(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBitTest(), foldSelectICmpAndZeroShl(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectToCopysign(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), foldSelectWithFCmpToFabs(), foldSelectWithSRem(), foldSelectZeroOrFixedOp(), llvm::InstCombinerImpl::foldSignBitTest(), foldUnsignedUnderflowCheck(), getAppleRuntimeUnrollPreferences(), llvm::vputils::getRecipesForUncountableExit(), llvm::SCEVExpander::hasRelatedExistingExpansion(), hoistAddSub(), hoistMinMax(), impliesPoisonOrCond(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::vputils::isHeaderMask(), isImpliedToBeAPowerOfTwoFromCond(), llvm::isKnownInversion(), llvm::isOnlyUsedInZeroComparison(), isProcessableCondBI(), isSignificantBitCheckWellFormed(), llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match(), matchSelectWithOptionalNotCond(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), optimizeVectorInductionWidthForTCAndVFUF(), recordCondition(), shouldExpandCmpArithRMWInIR(), simplifyAndOfICmpsWithAdd(), simplifyAndOrOfICmpsWithCtpop(), simplifyAndOrWithICmpEq(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyOrOfICmpsWithAdd(), simplifySelectWithICmpCond(), simplifySwitchOnSelectUsingRanges(), simplifyUnsignedRangeCheck(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), tryToMoveFreeBeforeNullTest(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitSelectInst().
m_ICmp() [2/2]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, ICmpInst > llvm::PatternMatch::m_ICmp (const LHS & L, const RHS & R) inline
Definition at line 1797 of file PatternMatch.h.
References LHS, and RHS.
m_IDiv()
template<typename LHS, typename RHS> BinOpPred_match< LHS, RHS, is_idiv_op > llvm::PatternMatch::m_IDiv (const LHS & L, const RHS & R) inline
Matches integer division operations.
Definition at line 1706 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldSelectZeroOrFixedOp(), isKnownNonNullFromDominatingCondition(), matchExpandedRem(), simplifyMulInst(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
m_ImmConstant() [1/2]
match_immconstant_ty llvm::PatternMatch::m_ImmConstant () inline
Match an arbitrary immediate Constant and ignore it.
Definition at line 957 of file PatternMatch.h.
Referenced by AddParamAndFnBasicAttributes(), canEvaluateShifted(), llvm::collectPossibleValues(), llvm::InstCombinerImpl::commonIDivRemTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::InstCombinerImpl::foldAddWithConstant(), llvm::InstCombinerImpl::foldBinOpSelectBinOp(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpEqualityWithOffset(), foldICmpIntrinsicWithIntrinsic(), llvm::InstCombinerImpl::foldICmpOrConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldReversedIntrinsicOperands(), llvm::InstCombinerImpl::foldSelectValueEquivalence(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftOfShiftedBinOp(), llvm::InstCombinerImpl::foldShuffledIntrinsicOperands(), foldTwoEntryPHINode(), foldURemOfLoopIncrement(), llvm::InstCombinerImpl::foldVectorBinop(), getAlternateBinop(), getBinOpsForFactorization(), llvm::InstCombiner::getFreelyInvertedImpl(), isImpliedCondFCmps(), isImpliedCondICmps(), reassociateMinMaxWithConstantInOperand(), reassociateMinMaxWithConstants(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpInst(), simplifyTernarylogic(), llvm::InstCombinerImpl::tryFoldInstWithCtpopWithNot(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitXor().
m_ImmConstant() [2/2]
bind_immconstant_ty llvm::PatternMatch::m_ImmConstant (Constant *& C) inline
Match an immediate Constant, capturing the value if we match.
Definition at line 974 of file PatternMatch.h.
References llvm::CallingConv::C.
m_Inf()
cstfp_pred_ty< is_inf > llvm::PatternMatch::m_Inf () inline
Match a positive or negative infinity FP constant.
For vectors, this includes constants with undefined elements.
Definition at line 740 of file PatternMatch.h.
Referenced by matchUnorderedInfCompare(), simplifyFAddInst(), simplifyFPOp(), and simplifyFSubInst().
m_InsertElt()
template<typename Val_t, typename Elt_t, typename Idx_t> ThreeOps_match< Val_t, Elt_t, Idx_t, Instruction::InsertElement > llvm::PatternMatch::m_InsertElt (const Val_t & Val, const Elt_t & Elt, const Idx_t & Idx) inline
Matches InsertElementInst.
Definition at line 1984 of file PatternMatch.h.
Referenced by canonicalizeInsertSplat(), cheapToScalarize(), foldIdentityExtractShuffle(), foldInsEltIntoSplat(), foldShuffleWithInsert(), foldTruncInsEltPair(), llvm::getSplatValue(), llvm::ARMTTIImpl::isProfitableToSinkOperands(), llvm::RISCVTTIImpl::isProfitableToSinkOperands(), llvm::WebAssemblyTTIImpl::isProfitableToSinkOperands(), matchSubIntegerPackFromVector(), simplifyShuffleVectorInst(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitInsertElementInst(), and llvm::InstCombinerImpl::visitPtrToInt().
m_InsertValue()
template<int Ind, typename Val_t, typename Elt_t> InsertValue_match< Ind, Val_t, Elt_t > llvm::PatternMatch::m_InsertValue (const Val_t & Val, const Elt_t & Elt) inline
Matches a single index InsertValue instruction.
Definition at line 3210 of file PatternMatch.h.
m_Instruction() [1/4]
bind_ty< const Instruction > llvm::PatternMatch::m_Instruction (const Instruction *& I) inline
Definition at line 875 of file PatternMatch.h.
References I.
m_Instruction() [2/4]
template<typename MatchTy> bind_and_match_ty< const Instruction, MatchTy > llvm::PatternMatch::m_Instruction (const Instruction *& I, const MatchTy & Match) inline
Definition at line 887 of file PatternMatch.h.
References I.
m_Instruction() [3/4]
bind_ty< Instruction > llvm::PatternMatch::m_Instruction (Instruction *& I) inline
Match an instruction, capturing it if we match.
Definition at line 874 of file PatternMatch.h.
References I.
Referenced by analyzeCostOfVecReduction(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::InstCombinerImpl::commonShiftTransforms(), computeKnownBitsFromLerpPattern(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), detectShiftUntilZeroIdiom(), llvm::findHistogram(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldICmpAddConstant(), foldICmpInvariantGroup(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), foldLoadsRecursive(), foldMulHigh(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), llvm::InstCombinerImpl::foldSelectExtConst(), foldSelectGEP(), foldSelectIntoAddConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::InstCombinerImpl::foldSignBitTest(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), getAppleRuntimeUnrollPreferences(), getNegatibleInsts(), llvm::LoopVectorizationCostModel::getReductionPatternCost(), llvm::SCEVExpander::hasRelatedExistingExpansion(), llvm::AArch64TTIImpl::isExtPartOfAvgExpr(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), isSignificantBitCheckWellFormed(), LinearizeExprTree(), lookThroughAnd(), RecurrenceInfo::matchConditionalRecurrence(), matchExpandedRem(), matchIncrement(), matchSubIntegerPackFromVector(), reassociateMinMaxWithConstantInOperand(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitOr().
m_Instruction() [4/4]
template<typename MatchTy> bind_and_match_ty< Instruction, MatchTy > llvm::PatternMatch::m_Instruction (Instruction *& I, const MatchTy & Match) inline
Match against the nested pattern, and capture the instruction if we match.
Definition at line 882 of file PatternMatch.h.
References I.
m_Interleave2()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_Interleave2 (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 3220 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
m_Intrinsic() [1/7]
template<Intrinsic::ID IntrID> IntrinsicID_match llvm::PatternMatch::m_Intrinsic () inline
Match intrinsic calls like this: m_Intrinsic<Intrinsic::fabs>(m_Value(X)).
Definition at line 2810 of file PatternMatch.h.
Referenced by llvm::AliasSetTracker::add(), cannotHoistOrSinkRecipe(), llvm::canSinkOrHoistInst(), cheapToScalarize(), llvm::collectEphemeralRecipesForVPlan(), computeKnownFPClassFromCond(), computeShapeInfoForInst(), llvm::findValuesAffectedByCondition(), foldBitCeil(), foldBitOrderCrossLogicOp(), foldCttzCtlz(), foldFCmpWithFloorAndCeil(), llvm::InstCombinerImpl::foldFMulReassoc(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), foldICmpOfUAddOv(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), foldMinimumOverTrailingOrLeadingZeroCount(), foldOrUnsignedUMulOverflowICmp(), llvm::InstCombinerImpl::foldPowiReassoc(), llvm::InstCombinerImpl::foldVectorBinop(), getBundleFromUse(), llvm::ARMTTIImpl::getGatherScatterOpCost(), getKnownTypeFromMaskedOp(), llvm::AMDGPUTargetMachine::getPredicatedAddrSpace(), llvm::vputils::getSCEVExprForVPValue(), getUnsignedMonotonicValues(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::hoistRegion(), llvm::ARMTTIImpl::instCombineIntrinsic(), instCombineLD1GatherIndex(), instCombineST1ScatterIndex(), instCombineSVEDup(), instCombineSVEDupqLane(), instCombineSVESrshl(), instCombineSVEUzp1(), instCombineSVEVectorFuseMulAddSub(), instCombineSVEZip(), isAllActivePredicate(), isAMXCast(), llvm::isCheckForZeroAndMulWithOverflow(), isDeadRecipe(), llvm::isGuard(), llvm::isGuardAsWidenableBranch(), isImpliedToBeAPowerOfTwoFromCond(), llvm::ConstantPtrAuth::isKnownCompatibleWith(), isPTruePromoted(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), llvm::MemoryWriteTracking::isSpecialInstruction(), llvm::isWidenableCondition(), m_BitReverse(), m_BSwap(), m_CopySign(), m_Deinterleave2(), m_FAbs(), m_FCanonicalize(), m_FMaximum(), m_FMaximumNum(), m_FMaxNum(), m_FMinimum(), m_FMinimumNum(), m_FMinNum(), m_FShl(), m_FShr(), m_Interleave2(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_MaskedGather(), m_MaskedLoad(), m_MaskedStore(), m_Sqrt(), m_VecReverse(), m_VectorInsert(), m_VScale(), matchIncrement(), matchRdxBop(), matchStridedStart(), llvm::parseWidenableBranch(), processUse(), llvm::AssumptionCache::registerAssumption(), llvm::DropUnnecessaryAssumesPass::run(), setShiftFlags(), simplifyAndOrOfICmpsWithCtpop(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyExtractValueInst(), simplifyFCmpInst(), simplifyIntrinsic(), simplifyOrInst(), simplifyRecipe(), simplifySelectWithICmpCond(), simplifyUnaryIntrinsic(), simplifyWithOpsReplaced(), llvm::InstCombinerImpl::tryFoldInstWithCtpopWithNot(), llvm::AssumptionCacheTracker::verifyAnalysis(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitExtractValueInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitPtrToAddr(), llvm::InstCombinerImpl::visitPtrToInt(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitTrunc().
m_Intrinsic() [2/7]
template<Intrinsic::ID IntrID, typename T0> m_Intrinsic_Ty< T0 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0) inline
Definition at line 2836 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), and Op0.
m_Intrinsic() [3/7]
template<Intrinsic::ID IntrID, typename T0, typename T1> m_Intrinsic_Ty< T0, T1 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1) inline
Definition at line 2841 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), Op0, and T1.
m_Intrinsic() [4/7]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2> m_Intrinsic_Ty< T0, T1, T2 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2) inline
Definition at line 2848 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), Op0, and T1.
m_Intrinsic() [5/7]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3> m_Intrinsic_Ty< T0, T1, T2, T3 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2, const T3 & Op3) inline
Definition at line 2855 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), Op0, and T1.
m_Intrinsic() [6/7]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3, typename T4> m_Intrinsic_Ty< T0, T1, T2, T3, T4 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2, const T3 & Op3, const T4 & Op4) inline
Definition at line 2862 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), Op0, and T1.
m_Intrinsic() [7/7]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3, typename T4, typename T5> m_Intrinsic_Ty< T0, T1, T2, T3, T4, T5 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2, const T3 & Op3, const T4 & Op4, const T5 & Op5) inline
Definition at line 2871 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), Op0, and T1.
m_IntToPtr()
template<typename OpTy> CastOperator_match< OpTy, Instruction::IntToPtr > llvm::PatternMatch::m_IntToPtr (const OpTy & Op) inline
Matches IntToPtr.
Definition at line 2236 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldPtrToIntOrAddrOfGEP(), and llvm::InstCombinerImpl::visitPtrToInt().
m_IRem()
template<typename LHS, typename RHS> BinOpPred_match< LHS, RHS, is_irem_op > llvm::PatternMatch::m_IRem (const LHS & L, const RHS & R) inline
Matches integer remainder operations.
Definition at line 1713 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldSelectZeroOrFixedOp(), isKnownNonNullFromDominatingCondition(), and llvm::InstCombinerImpl::SimplifyAddWithRemainder().
m_Load()
template<typename OpTy> OneOps_match< OpTy, Instruction::Load > llvm::PatternMatch::m_Load (const OpTy & Op) inline
Matches LoadInst.
Definition at line 2078 of file PatternMatch.h.
Referenced by cheapToScalarize(), llvm::findHistogram(), foldToMaskedStore(), llvm::X86TTIImpl::getShuffleCost(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), and processUse().
m_LogicalAnd() [1/2]
auto llvm::PatternMatch::m_LogicalAnd () inline
Matches L && R where L and R are arbitrary values.
Definition at line 3285 of file PatternMatch.h.
References m_LogicalAnd(), and m_Value().
Referenced by checkOrAndOpImpliedByOther(), collectHomogenousInstGraphLoopInvariants(), collectUnswitchCandidates(), computeKnownBitsFromCond(), computeKnownFPClassFromCond(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), findBestNonTrivialUnswitchCandidate(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), hoistMinMax(), isImpliedCondAndOr(), llvm::isImpliedCondition(), isKnownNonNullFromDominatingCondition(), m_LogicalAnd(), RemoveMask_match< Op0_t, Op1_t >::match(), optimizeLoopExitWithUnknownExitCount(), llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect(), simplifyRecipe(), llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp(), llvm::JumpThreadingPass::tryToUnfoldSelectInCurrBB(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSelectInst(), and llvm::InstCombinerImpl::visitXor().
m_LogicalAnd() [2/2]
template<typename LHS, typename RHS> LogicalOp_match< LHS, RHS, Instruction::And > llvm::PatternMatch::m_LogicalAnd (const LHS & L, const RHS & R) inline
Matches L && R either in the form of L & R or L ?
R : false. Note that the latter form is poison-blocking.
Definition at line 3279 of file PatternMatch.h.
References LHS, and RHS.
Referenced by foldNestedSelects(), removeCommonBlendMask(), llvm::InstCombiner::shouldAvoidAbsorbingNotIntoSelect(), and unswitchTrivialBranch().
m_LogicalOp() [1/2]
auto llvm::PatternMatch::m_LogicalOp () inline
Matches either L && R or L || R where L and R are arbitrary values.
Definition at line 3323 of file PatternMatch.h.
References m_LogicalOp(), and m_Value().
Referenced by computeKnownBitsFromCond(), llvm::findValuesAffectedByCondition(), m_LogicalOp(), llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), and llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp().
m_LogicalOp() [2/2]
template<typename LHS, typename RHS, bool Commutable = false> auto llvm::PatternMatch::m_LogicalOp (const LHS & L, const RHS & R) inline
Matches either L && R or L || R, either one being in the either binary or logical form.
Note that the latter form is poison-blocking.
Definition at line 3316 of file PatternMatch.h.
References LHS, m_CombineOr(), and RHS.
Referenced by m_c_LogicalOp().
m_LogicalOr() [1/2]
auto llvm::PatternMatch::m_LogicalOr () inline
Matches L || R where L and R are arbitrary values.
Definition at line 3303 of file PatternMatch.h.
References m_LogicalOr(), and m_Value().
Referenced by checkOrAndOpImpliedByOther(), collectHomogenousInstGraphLoopInvariants(), collectUnswitchCandidates(), computeKnownBitsFromCond(), computeKnownFPClassFromCond(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), findBestNonTrivialUnswitchCandidate(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), hoistMinMax(), isImpliedCondAndOr(), llvm::isImpliedCondition(), m_LogicalOr(), optimizeLoopExitWithUnknownExitCount(), llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect(), llvm::JumpThreadingPass::tryToUnfoldSelectInCurrBB(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSelectInst(), and llvm::InstCombinerImpl::visitXor().
m_LogicalOr() [2/2]
template<typename LHS, typename RHS> LogicalOp_match< LHS, RHS, Instruction::Or > llvm::PatternMatch::m_LogicalOr (const LHS & L, const RHS & R) inline
Matches L || R either in the form of L | R or L ?
true : R. Note that the latter form is poison-blocking.
Definition at line 3297 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombiner::shouldAvoidAbsorbingNotIntoSelect(), and unswitchTrivialBranch().
m_LogicalShift()
template<typename LHS, typename RHS> BinOpPred_match< LHS, RHS, is_logical_shift_op > llvm::PatternMatch::m_LogicalShift (const LHS & L, const RHS & R) inline
Matches logical shift operations.
Definition at line 1686 of file PatternMatch.h.
References LHS, and RHS.
Referenced by collectBitParts(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), foldSelectFunnelShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::InstCombinerImpl::visitAnd(), and llvm::InstCombinerImpl::visitCallInst().
m_LowBitMask() [1/2]
cst_pred_ty< is_lowbit_mask > llvm::PatternMatch::m_LowBitMask () inline
Match an integer or vector with only the low bit(s) set.
For vectors, this includes constants with undefined elements.
Definition at line 685 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), llvm::PatternMatch::XorLike_match< LHS, RHS >::match(), processAnd(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::simplifyInstruction(), simplifySubInst(), simplifyXorInst(), llvm::stripNullTest(), llvm::InstCombinerImpl::visitAdd(), and llvm::InstCombinerImpl::visitTrunc().
m_LowBitMask() [2/2]
api_pred_ty< is_lowbit_mask > llvm::PatternMatch::m_LowBitMask (const APInt *& V) inline
Definition at line 688 of file PatternMatch.h.
m_LowBitMaskOrZero() [1/2]
cst_pred_ty< is_lowbit_mask_or_zero > llvm::PatternMatch::m_LowBitMaskOrZero () inline
Match an integer or vector with only the low bit(s) set.
For vectors, this includes constants with undefined elements.
Definition at line 695 of file PatternMatch.h.
Referenced by isMaskOrZero().
m_LowBitMaskOrZero() [2/2]
api_pred_ty< is_lowbit_mask_or_zero > llvm::PatternMatch::m_LowBitMaskOrZero (const APInt *& V) inline
Definition at line 698 of file PatternMatch.h.
m_LShr()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::LShr > llvm::PatternMatch::m_LShr (const LHS & L, const RHS & R) inline
Definition at line 1346 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), dropRedundantMaskingOfLeftShiftInput(), foldBoxMultiply(), foldCttzCtlz(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEquality(), foldMulHigh(), foldSelectICmpAndAnd(), foldSelectICmpLshrAshr(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldTruncInsEltPair(), foldVecExtTruncToExtElt(), foldVecTruncToExtElt(), getBinOpsForFactorization(), haveNoCommonBitsSetSpecialCases(), llvm::isKnownToBeAPowerOfTwo(), isTruePredicate(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), matchAndOrChain(), MatchDiv(), matchIntPart(), matchZExtedSubInteger(), simplifyAndInst(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithBinOpOnLHS(), simplifyOrInst(), simplifyValueKnownNonZero(), llvm::stripNullTest(), llvm::InstCombinerImpl::takeLog2(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), and llvm::InstCombinerImpl::visitXor().
m_LShrOrSelf()
template<typename LHS> ShiftLike_match< LHS, Instruction::LShr > llvm::PatternMatch::m_LShrOrSelf (const LHS & L, uint64_t & R) inline
Matches lshr L, ConstShAmt or L itself (R will be set to zero in this case).
Definition at line 1384 of file PatternMatch.h.
References LHS.
Referenced by matchPartStore().
m_MaskedGather()
template<typename Opnd0, typename Opnd1, typename Opnd2> m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty llvm::PatternMatch::m_MaskedGather (const Opnd0 & Op0, const Opnd1 & Op1, const Opnd2 & Op2) inline
Matches MaskedGather Intrinsic.
Definition at line 2831 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::InstCombinerImpl::visitSelectInst().
m_MaskedLoad()
template<typename Opnd0, typename Opnd1, typename Opnd2> m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty llvm::PatternMatch::m_MaskedLoad (const Opnd0 & Op0, const Opnd1 & Op1, const Opnd2 & Op2) inline
Matches MaskedLoad Intrinsic.
Definition at line 2817 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by optimizeMaskToEVL(), and llvm::InstCombinerImpl::visitSelectInst().
m_MaskedStore()
template<typename Opnd0, typename Opnd1, typename Opnd2> m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty llvm::PatternMatch::m_MaskedStore (const Opnd0 & Op0, const Opnd1 & Op1, const Opnd2 & Op2) inline
Matches MaskedStore Intrinsic.
Definition at line 2824 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by optimizeMaskToEVL().
m_MaxOrMin()
template<typename LHS, typename RHS> match_combine_or< match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty >, MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty > >, match_combine_or< MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty >, MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty > > > llvm::PatternMatch::m_MaxOrMin (const LHS & L, const RHS & R) inline
Definition at line 2553 of file PatternMatch.h.
References LHS, m_CombineOr(), m_SMax(), m_SMin(), m_UMax(), m_UMin(), and RHS.
Referenced by llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldMinMaxSharedOp(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), llvm::InstCombiner::getFreelyInvertedImpl(), and reassociateMinMaxWithConstantInOperand().
m_MaxSignedValue() [1/2]
cst_pred_ty< is_maxsignedvalue > llvm::PatternMatch::m_MaxSignedValue () inline
Match an integer or vector with values having all bits except for the high bit set (0x7f...).
For vectors, this includes constants with undefined elements.
Definition at line 550 of file PatternMatch.h.
Referenced by canonicalizeSaturatedAddSigned(), and llvm::InstCombinerImpl::visitAnd().
m_MaxSignedValue() [2/2]
api_pred_ty< is_maxsignedvalue > llvm::PatternMatch::m_MaxSignedValue (const APInt *& V) inline
Definition at line 553 of file PatternMatch.h.
m_Mul()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Mul > llvm::PatternMatch::m_Mul (const LHS & L, const RHS & R) inline
Definition at line 1274 of file PatternMatch.h.
References LHS, and RHS.
Referenced by analyzeCostOfVecReduction(), llvm::VPIntrinsic::canIgnoreVectorLengthParam(), combinePMULH(), combineShiftToPMULH(), llvm::InstCombinerImpl::commonIDivTransforms(), detectPMADDUBSW(), foldBoxMultiply(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpWithZero(), foldMulHigh(), foldReduceOperandViaVQDOT(), llvm::LoopVectorizationCostModel::getReductionPatternCost(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), isNonEqualMul(), m_AnyMul(), matchBitmaskMul(), MatchMul(), matchPMADDWD_2(), matchVPMADD52(), processUse(), shouldCanonicalizeGEPToPtrAdd(), shouldSinkVScale(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithBinOpOnLHS(), simplifyIRemMulShl(), tryToMatchAndCreateMulAccumulateReduction(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitShl(), and llvm::InstCombinerImpl::visitSub().
m_NaN()
cstfp_pred_ty< is_nan > llvm::PatternMatch::m_NaN () inline
Match an arbitrary NaN constant.
This includes quiet and signalling nans. For vectors, this includes constants with undefined elements.
Definition at line 724 of file PatternMatch.h.
Referenced by simplifyFPOp().
m_Neg()
template<typename ValTy> BinaryOp_match< cst_pred_ty< is_zero_int >, ValTy, Instruction::Sub > llvm::PatternMatch::m_Neg (const ValTy & V) inline
Matches a 'Neg' as 'sub 0, V'.
Definition at line 3037 of file PatternMatch.h.
References m_Sub(), and m_ZeroInt().
Referenced by llvm::PatternMatch::Signum_match< Opnd_t >::match().
m_NegatedPower2() [1/2]
cst_pred_ty< is_negated_power2 > llvm::PatternMatch::m_NegatedPower2 () inline
Match a integer or vector negated power-of-2.
For vectors, this includes constants with undefined elements.
Definition at line 639 of file PatternMatch.h.
Referenced by foldNegativePower2AndShiftedMask(), llvm::simplifyInstruction(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitTrunc().
m_NegatedPower2() [2/2]
api_pred_ty< is_negated_power2 > llvm::PatternMatch::m_NegatedPower2 (const APInt *& V) inline
Definition at line 642 of file PatternMatch.h.
m_NegatedPower2OrZero() [1/2]
cst_pred_ty< is_negated_power2_or_zero > llvm::PatternMatch::m_NegatedPower2OrZero () inline
Match a integer or vector negated power-of-2.
For vectors, this includes constants with undefined elements.
Definition at line 651 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpBinOp(), and isMaskOrZero().
m_NegatedPower2OrZero() [2/2]
api_pred_ty< is_negated_power2_or_zero > llvm::PatternMatch::m_NegatedPower2OrZero (const APInt *& V) inline
Definition at line 655 of file PatternMatch.h.
m_Negative() [1/2]
cst_pred_ty< is_negative > llvm::PatternMatch::m_Negative () inline
Match an integer or vector of negative values.
For vectors, this includes constants with undefined elements.
Definition at line 562 of file PatternMatch.h.
Referenced by foldICmpXorXX(), llvm::simplifyBinaryIntrinsic(), simplifyShlInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitUDiv(), and llvm::InstCombinerImpl::visitURem().
m_Negative() [2/2]
api_pred_ty< is_negative > llvm::PatternMatch::m_Negative (const APInt *& V) inline
Definition at line 565 of file PatternMatch.h.
m_NegZeroFP()
cstfp_pred_ty< is_neg_zero_fp > llvm::PatternMatch::m_NegZeroFP () inline
Match a floating-point negative zero.
For vectors, this includes constants with undefined elements.
Definition at line 796 of file PatternMatch.h.
Referenced by llvm::ConstantFoldBinaryInstruction(), simplifyFAddInst(), simplifyFRemInst(), simplifyFSubInst(), and llvm::InstCombinerImpl::visitCallInst().
m_NNegZExt()
template<typename OpTy> NNegZExt_match< OpTy > llvm::PatternMatch::m_NNegZExt (const OpTy & Op) inline
Definition at line 2286 of file PatternMatch.h.
Referenced by decompose(), m_SExtLike(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
m_NonInf()
cstfp_pred_ty< is_noninf > llvm::PatternMatch::m_NonInf () inline
Match a non-infinity FP constant, i.e.
finite or NaN. For vectors, this includes constants with undefined elements.
Definition at line 747 of file PatternMatch.h.
m_NonNaN()
cstfp_pred_ty< is_nonnan > llvm::PatternMatch::m_NonNaN () inline
Match a non-NaN FP constant.
For vectors, this includes constants with undefined elements.
Definition at line 731 of file PatternMatch.h.
m_NonNegative() [1/2]
cst_pred_ty< is_nonnegative > llvm::PatternMatch::m_NonNegative () inline
Match an integer or vector of non-negative values.
For vectors, this includes constants with undefined elements.
Definition at line 572 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpBinOp(), foldICmpWithLowBitMaskedVal(), getBinOpsForFactorization(), instCombineSVESrshl(), isImpliedCondICmps(), llvm::InstCombinerImpl::OptimizePointerDifference(), and llvm::InstCombinerImpl::visitSDiv().
m_NonNegative() [2/2]
api_pred_ty< is_nonnegative > llvm::PatternMatch::m_NonNegative (const APInt *& V) inline
Definition at line 575 of file PatternMatch.h.
m_NonPositive() [1/2]
cst_pred_ty< is_nonpositive > llvm::PatternMatch::m_NonPositive () inline
Match an integer or vector of non-positive values.
For vectors, this includes constants with undefined elements.
Definition at line 594 of file PatternMatch.h.
Referenced by isImpliedCondICmps().
m_NonPositive() [2/2]
api_pred_ty< is_nonpositive > llvm::PatternMatch::m_NonPositive (const APInt *& V) inline
Definition at line 597 of file PatternMatch.h.
m_NonZeroFP()
cstfp_pred_ty< is_non_zero_fp > llvm::PatternMatch::m_NonZeroFP () inline
Match a floating-point non-zero.
For vectors, this includes constants with undefined elements.
Definition at line 805 of file PatternMatch.h.
m_NonZeroNotDenormalFP()
cstfp_pred_ty< is_non_zero_not_denormal_fp > llvm::PatternMatch::m_NonZeroNotDenormalFP () inline
Match a floating-point non-zero that is not a denormal.
For vectors, this includes constants with undefined elements.
Definition at line 817 of file PatternMatch.h.
Referenced by hasNonZeroFPOperands().
m_Not()
template<typename ValTy> BinaryOp_match< cst_pred_ty< is_all_ones >, ValTy, Instruction::Xor, true > llvm::PatternMatch::m_Not (const ValTy & V) inline
Matches a 'Not' as 'xor V, -1' or 'xor -1, V'.
NOTE: we first match the 'Not' (by matching '-1'), and only then match the inner matcher!
Definition at line 2649 of file PatternMatch.h.
References m_AllOnes(), and m_c_Xor().
Referenced by llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match().
m_NotForbidPoison()
template<typename ValTy> BinaryOp_match< cst_pred_ty< is_all_ones, false >, ValTy, Instruction::Xor, true > llvm::PatternMatch::m_NotForbidPoison (const ValTy & V) inline
Definition at line 2656 of file PatternMatch.h.
References m_AllOnesForbidPoison(), and m_c_Xor().
Referenced by canonicalizeSaturatedAddUnsigned().
m_NSWAdd()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWAdd (const LHS & L, const RHS & R) inline
Definition at line 1426 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, and RHS.
Referenced by decompose(), foldSelectICmpMinMax(), foldURemOfLoopIncrement(), hoistAdd(), isTruePredicate(), m_NSWAddLike(), trySimplifyICmpWithAdds(), and llvm::InstCombinerImpl::visitSub().
m_NSWAddLike()
template<typename LHS, typename RHS> match_combine_or< OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap >, DisjointOr_match< LHS, RHS > > llvm::PatternMatch::m_NSWAddLike (const LHS & L, const RHS & R) inline
Match either "add nsw" or "or disjoint".
Definition at line 1572 of file PatternMatch.h.
References LHS, m_CombineOr(), m_DisjointOr(), m_NSWAdd(), and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), foldNoWrapAdd(), isTruePredicate(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::InstCombinerImpl::visitSub().
m_NSWMul()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWMul (const LHS & L, const RHS & R) inline
Definition at line 1450 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), decompose(), simplifyDiv(), simplifyICmpWithConstant(), simplifyRem(), llvm::InstCombinerImpl::visitAShr(), and llvm::InstCombinerImpl::visitLShr().
m_NSWNeg()
template<typename ValTy> OverflowingBinaryOp_match< cst_pred_ty< is_zero_int >, ValTy, Instruction::Sub, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWNeg (const ValTy & V) inline
Matches a 'Neg' as 'sub nsw 0, V'.
Definition at line 3046 of file PatternMatch.h.
References m_NSWSub(), and m_ZeroInt().
Referenced by foldICmpXNegX(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitSRem().
m_NSWShl()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWShl (const LHS & L, const RHS & R) inline
Definition at line 1458 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), decompose(), foldICmpEqualityWithOffset(), optimizeShiftInOrChain(), simplifyAShrInst(), simplifyRem(), llvm::InstCombinerImpl::visitAShr(), and llvm::InstCombinerImpl::visitSDiv().
m_NSWSub()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWSub (const LHS & L, const RHS & R) inline
Definition at line 1442 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, and RHS.
Referenced by canonicalizeSaturatedAddSigned(), llvm::computeOverflowForSignedSub(), decompose(), foldAbsDiff(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldSubOfMinMax(), getKnownSign(), getKnownSignOrZero(), hoistSub(), isImpliedCondICmps(), llvm::isKnownNegation(), m_NSWNeg(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitOr().
m_NSWTrunc()
template<typename OpTy> NoWrapTrunc_match< OpTy, TruncInst::NoSignedWrap > llvm::PatternMatch::m_NSWTrunc (const OpTy & Op) inline
Matches trunc nsw.
Definition at line 2263 of file PatternMatch.h.
Referenced by decompose(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), and llvm::InstCombinerImpl::visitSelectInst().
m_NUWAdd()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWAdd (const LHS & L, const RHS & R) inline
Definition at line 1467 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and RHS.
Referenced by decompose(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), foldSelectICmpMinMax(), hoistAdd(), isRemOfLoopIncrementWithLoopInvariant(), and m_NUWAddLike().
m_NUWAddLike()
template<typename LHS, typename RHS> match_combine_or< OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap >, DisjointOr_match< LHS, RHS > > llvm::PatternMatch::m_NUWAddLike (const LHS & L, const RHS & R) inline
Match either "add nuw" or "or disjoint".
Definition at line 1582 of file PatternMatch.h.
References LHS, m_CombineOr(), m_DisjointOr(), m_NUWAdd(), and RHS.
Referenced by canonicalizeGEPOfConstGEPI8(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), foldNoWrapAdd(), isTruePredicate(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::InstCombinerImpl::visitSub().
m_NUWMul()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWMul (const LHS & L, const RHS & R) inline
Definition at line 1493 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), decompose(), getUnsignedMonotonicValues(), isMultipleOfN(), simplifyDiv(), simplifyICmpWithConstant(), simplifyRem(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitUDiv().
m_NUWShl()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWShl (const LHS & L, const RHS & R) inline
Definition at line 1501 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), decompose(), foldCttzCtlz(), foldICmpEqualityWithOffset(), foldICmpShlLHSC(), optimizeShiftInOrChain(), simplifyAndInst(), simplifyLShrInst(), simplifyRem(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitLShr().
m_NUWSub()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWSub (const LHS & L, const RHS & R) inline
Definition at line 1485 of file PatternMatch.h.
References LHS, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and RHS.
Referenced by computeKnownBitsFromCmp(), computeKnownBitsFromLerpPattern(), llvm::computeOverflowForUnsignedSub(), decompose(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldAddLikeCommutative(), hoistSub(), simplifyXorInst(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitLShr().
m_NUWTrunc()
template<typename OpTy> NoWrapTrunc_match< OpTy, TruncInst::NoUnsignedWrap > llvm::PatternMatch::m_NUWTrunc (const OpTy & Op) inline
Matches trunc nuw.
Definition at line 2256 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::PredicateBase::getConstraint(), llvm::isImpliedCondition(), llvm::isImpliedCondition(), and llvm::InstCombinerImpl::visitSelectInst().
m_One()
cst_pred_ty< is_one > llvm::PatternMatch::m_One () inline
Match an integer 1 or a vector with all elements equal to 1.
For vectors, this includes constants with undefined elements.
Definition at line 604 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeICmpBool(), canonicalizeLowbitMask(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), checkForNegativeOperand(), combineSetCC(), llvm::InstCombinerImpl::commonIDivTransforms(), computeKnownBitsFromOperator(), llvm::VPlanTransforms::convertToConcreteRecipes(), despeculateCountZeros(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), dropRedundantMaskingOfLeftShiftInput(), emitTransformedIndex(), foldAddSubBoolOfMaskedVal(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithPow2AndWithZero(), foldAnyOrAllBitsSet(), foldBitCeil(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), foldICmpOfUAddOv(), foldICmpWithHighBitMask(), llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldMulSelectToNegate(), foldMulShl1(), foldSelectICmpAndAnd(), foldSelectICmpMinMax(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectWithSRem(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), getRangeForIntrinsic(), handleOtherCmpSelSimplifications(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::Constant::isElementWiseEqual(), llvm::vputils::isHeaderMask(), llvm::isKnownToBeAPowerOfTwo(), isNeutralValue(), isRemOfLoopIncrementWithLoopInvariant(), isSignificantBitCheckWellFormed(), llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match(), matchAndOrChain(), matchSelectPattern(), narrowBitOpRMW(), llvm::LoopVectorizePass::processLoop(), replaceConditionalBranchesOnConstant(), reverseZExtICmpCombine(), llvm::simplifyBinaryIntrinsic(), simplifyExtractValueInst(), simplifyICmpOfBools(), simplifyICmpWithBinOp(), simplifyMulInst(), simplifyOrInst(), simplifyRecipe(), simplifySelectInst(), simplifyValueKnownNonZero(), simplifyX86pmulh(), skipTrivialSelect(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitURem(), and llvm::InstCombinerImpl::visitXor().
m_OneUse()
template<typename T> OneUse_match< T > llvm::PatternMatch::m_OneUse (const T & SubPattern) inline
Definition at line 80 of file PatternMatch.h.
References T.
Referenced by llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match().
m_Or()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Or > llvm::PatternMatch::m_Or (const LHS & L, const RHS & R) inline
Definition at line 1328 of file PatternMatch.h.
References LHS, and RHS.
Referenced by checkForNegativeOperand(), collectBitParts(), combineAndNotOrIntoAndNotAnd(), combineOr(), combineOrAndToBitfieldInsert(), combineOrToBitfieldInsert(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), countToEliminateCompares(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndToXor(), foldAnyOrAllBitsSet(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpOrXorSubChain(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), foldICmpWithLowBitMaskedVal(), foldMaskedMerge(), foldNotXor(), foldSelectFunnelShift(), foldSetClearBits(), foldXorToXor(), llvm::InstCombiner::getFreelyInvertedImpl(), getUnsignedMonotonicValues(), isLoadCombineCandidateImpl(), isTruePredicate(), matchAndOrChain(), matchLogicBlend(), narrowBitOpRMW(), llvm::recognizeBSwapOrBitReverseIdiom(), simplifySelectBitTest(), simplifySelectWithICmpCond(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSelectInst(), and llvm::InstCombinerImpl::visitXor().
m_OrdFMax()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ofmax_pred_ty > llvm::PatternMatch::m_OrdFMax (const LHS & L, const RHS & R) inline
Match an 'ordered' floating point maximum function.
Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'maximum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ogt/ge, L, R), L, R) semantics matched by this predicate.
                    max(L, R)  iff L and R are not NaN
m_OrdFMax(L, R) = R iff L or R are NaN
Definition at line 2568 of file PatternMatch.h.
References LHS, and RHS.
m_OrdFMin()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ofmin_pred_ty > llvm::PatternMatch::m_OrdFMin (const LHS & L, const RHS & R) inline
Match an 'ordered' floating point minimum function.
Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'minimum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(olt/le, L, R), L, R) semantics matched by this predicate.
                    min(L, R)  iff L and R are not NaN
m_OrdFMin(L, R) = R iff L or R are NaN
Definition at line 2583 of file PatternMatch.h.
References LHS, and RHS.
m_OrdOrUnordFMax()
template<typename LHS, typename RHS> match_combine_or< MaxMin_match< FCmpInst, LHS, RHS, ofmax_pred_ty >, MaxMin_match< FCmpInst, LHS, RHS, ufmax_pred_ty > > llvm::PatternMatch::m_OrdOrUnordFMax (const LHS & L, const RHS & R) inline
Match an 'ordered' or 'unordered' floating point maximum function.
Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'maximum' semantics.
Definition at line 2626 of file PatternMatch.h.
References LHS, m_CombineOr(), and RHS.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern(), matchFastFloatClamp(), and llvm::InstCombinerImpl::visitSelectInst().
m_OrdOrUnordFMin()
template<typename LHS, typename RHS> match_combine_or< MaxMin_match< FCmpInst, LHS, RHS, ofmin_pred_ty >, MaxMin_match< FCmpInst, LHS, RHS, ufmin_pred_ty > > llvm::PatternMatch::m_OrdOrUnordFMin (const LHS & L, const RHS & R) inline
Match an 'ordered' or 'unordered' floating point minimum function.
Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'minimum' semantics.
Definition at line 2639 of file PatternMatch.h.
References LHS, m_CombineOr(), and RHS.
Referenced by llvm::RecurrenceDescriptor::isMinMaxPattern(), matchFastFloatClamp(), and llvm::InstCombinerImpl::visitSelectInst().
m_Poison()
class_match< PoisonValue > llvm::PatternMatch::m_Poison () inline
Match an arbitrary poison constant.
Definition at line 173 of file PatternMatch.h.
Referenced by canonicalizeInsertSplat(), collectShuffleElements(), collectSingleShuffleElements(), foldIdentityExtractShuffle(), foldInsEltIntoIdentityShuffle(), foldInsSequenceIntoSplat(), llvm::InstCombinerImpl::foldShuffledIntrinsicOperands(), foldTruncShuffle(), llvm::InstCombinerImpl::foldVectorBinop(), narrowVectorSelect(), llvm::InstCombinerImpl::simplifyBinOpSplats(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::InstCombinerImpl::visitFNeg(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
m_PosZeroFP()
cstfp_pred_ty< is_pos_zero_fp > llvm::PatternMatch::m_PosZeroFP () inline
Match a floating-point positive zero.
For vectors, this includes constants with undefined elements.
Definition at line 787 of file PatternMatch.h.
Referenced by foldSelectWithFCmpToFabs(), foldSqrtWithFcmpZero(), matchFMulByZeroIfResultEqZero(), simplifyAndOrOfFCmps(), simplifyFAddInst(), simplifyFRemInst(), simplifyFSubInst(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitFCmpInst().
m_Power2() [1/2]
cst_pred_ty< is_power2 > llvm::PatternMatch::m_Power2 () inline
Match an integer or vector power-of-2.
For vectors, this includes constants with undefined elements.
Definition at line 631 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::commonShiftTransforms(), computeKnownBitsFromCmp(), foldAddToAshr(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldSelectBitTest(), foldSelectICmpAndBinOp(), foldSignedTruncationCheck(), llvm::isKnownToBeAPowerOfTwo(), isPowerOfTwoRecurrence(), simplifyAndInst(), simplifyICmpWithBinOp(), llvm::InstCombinerImpl::takeLog2(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitTrunc().
m_Power2() [2/2]
api_pred_ty< is_power2 > llvm::PatternMatch::m_Power2 (const APInt *& V) inline
Definition at line 632 of file PatternMatch.h.
m_Power2OrZero() [1/2]
cst_pred_ty< is_power2_or_zero > llvm::PatternMatch::m_Power2OrZero () inline
Match an integer or vector of 0 or power-of-2 values.
For vectors, this includes constants with undefined elements.
Definition at line 664 of file PatternMatch.h.
Referenced by llvm::isKnownToBeAPowerOfTwo().
m_Power2OrZero() [2/2]
api_pred_ty< is_power2_or_zero > llvm::PatternMatch::m_Power2OrZero (const APInt *& V) inline
Definition at line 667 of file PatternMatch.h.
m_PtrAdd()
template<typename PointerOpTy, typename OffsetOpTy> PtrAdd_match< PointerOpTy, OffsetOpTy > llvm::PatternMatch::m_PtrAdd (const PointerOpTy & PointerOp, const OffsetOpTy & OffsetOp) inline
Matches GEP with i8 source element type.
Definition at line 2099 of file PatternMatch.h.
Referenced by canonicalizeGEPOfConstGEPI8(), simplifyCastInst(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
m_PtrToAddr()
template<typename OpTy> CastOperator_match< OpTy, Instruction::PtrToAddr > llvm::PatternMatch::m_PtrToAddr (const OpTy & Op) inline
Matches PtrToAddr.
Definition at line 2224 of file PatternMatch.h.
Referenced by m_PtrToIntOrAddr(), and llvm::InstCombinerImpl::visitSub().
m_PtrToInt()
template<typename OpTy> CastOperator_match< OpTy, Instruction::PtrToInt > llvm::PatternMatch::m_PtrToInt (const OpTy & Op) inline
Matches PtrToInt.
Definition at line 2211 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpOrConstant(), isKnownNonZeroFromAssume(), m_PtrToIntOrAddr(), simplifyGEPInst(), and llvm::InstCombinerImpl::visitSub().
m_PtrToIntOrAddr()
template<typename OpTy> auto llvm::PatternMatch::m_PtrToIntOrAddr (const OpTy & Op) inline
Matches PtrToInt or PtrToAddr.
Definition at line 2229 of file PatternMatch.h.
References m_CombineOr(), m_PtrToAddr(), and m_PtrToInt().
Referenced by addValueAffectedByCondition(), isImpliedCondICmps(), llvm::simplifyBinaryIntrinsic(), simplifyCastInst(), simplifyGEPInst(), simplifySubInst(), tryToImproveAlign(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::InstCombinerImpl::visitSub().
m_PtrToIntSameSize()
template<typename OpTy> PtrToIntSameSize_match< OpTy > llvm::PatternMatch::m_PtrToIntSameSize (const DataLayout & DL, const OpTy & Op) inline
Definition at line 2216 of file PatternMatch.h.
References DL.
Referenced by computeKnownBitsFromCmp(), isKnownNonEqual(), llvm::InstCombinerImpl::visitIntToPtr(), and llvm::InstCombinerImpl::visitSub().
m_SDiv()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::SDiv > llvm::PatternMatch::m_SDiv (const LHS & L, const RHS & R) inline
Definition at line 1292 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldAddToAshr(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::FoldShiftByConstant(), MatchDiv(), simplifyDivRem(), simplifyGEPInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSDiv().
m_Select()
template<typename Cond, typename LHS, typename RHS> ThreeOps_match< Cond, LHS, RHS, Instruction::Select > llvm::PatternMatch::m_Select (const Cond & C, const LHS & L, const RHS & R) inline
Matches SelectInst.
Definition at line 1954 of file PatternMatch.h.
References llvm::CallingConv::C, Cond, LHS, and RHS.
Referenced by annotateNonNullAndDereferenceable(), breakSelfRecursivePHI(), llvm::canConvertToMinOrMaxIntrinsic(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::VPlanTransforms::canonicalizeEVLLoops(), llvm::InstCombinerImpl::commonIDivRemTransforms(), llvm::VPlanTransforms::createInLoopReductionRecipes(), fixReductionScalarResumeWhenVectorizingEpilog(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), foldBitCastSelect(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), foldMulHigh(), foldMulSelectToNegate(), foldNestedSelects(), FoldOrOfSelectSmaxToAbs(), foldOverflowingAddSubSelect(), foldSelectGEP(), foldSelectIntoAddConstant(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectOfSymmetricSelect(), llvm::InstCombinerImpl::foldSelectToCmp(), llvm::InstCombinerImpl::FoldShiftByConstant(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::VPlanTransforms::handleMultiUseReductions(), llvm::RecurrenceDescriptor::isAnyOfPattern(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), llvm::RecurrenceDescriptor::isFindIVPattern(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isReductionCandidate(), isSignificantBitCheckWellFormed(), llvm::isSplatValue(), m_SelectCst(), matchBitmaskMul(), RecurrenceInfo::matchConditionalRecurrence(), matchSelectWithOptionalNotCond(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), narrowVectorSelect(), optimizeMaskToEVL(), PerformSELECTShiftCombine(), llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect(), simplifyAndInst(), simplifyOrInst(), simplifyRecipe(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), skipTrivialSelect(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractValueInst(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSelectInst(), and llvm::InstCombinerImpl::visitSub().
m_SelectCst()
template<int64_t L, int64_t R, typename Cond> ThreeOps_match< Cond, constantint_match< L >, constantint_match< R >, Instruction::Select > llvm::PatternMatch::m_SelectCst (const Cond & C) inline
This matches a select of two constants, e.g.: m_SelectCst<-1, 0>(m_Value(V)).
Definition at line 1963 of file PatternMatch.h.
References llvm::CallingConv::C, Cond, m_ConstantInt(), and m_Select().
m_SExt()
template<typename OpTy> CastInst_match< OpTy, SExtInst > llvm::PatternMatch::m_SExt (const OpTy & Op) inline
Matches SExt.
Definition at line 2275 of file PatternMatch.h.
Referenced by combineAnd(), llvm::InstCombinerImpl::commonShiftTransforms(), decompose(), detectPMADDUBSW(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldSelectToCmp(), getBoolVecFromMask(), llvm::vputils::getSCEVExprForVPValue(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), m_SExtLike(), m_SExtOrSelf(), m_ZExtOrSExt(), matchPMADDWD_2(), matchSelectPattern(), narrowInsElt(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyRecipe(), simplifyShift(), simplifySRemInst(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), and llvm::InstCombinerImpl::visitURem().
m_SExtLike()
template<typename OpTy> match_combine_or< CastInst_match< OpTy, SExtInst >, NNegZExt_match< OpTy > > llvm::PatternMatch::m_SExtLike (const OpTy & Op) inline
Match either "sext" or "zext nneg".
Definition at line 2305 of file PatternMatch.h.
References m_CombineOr(), m_NNegZExt(), and m_SExt().
Referenced by foldLogicCastConstant(), foldNoWrapAdd(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::InstCombinerImpl::visitSub().
m_SExtOrSelf()
template<typename OpTy> match_combine_or< CastInst_match< OpTy, SExtInst >, OpTy > llvm::PatternMatch::m_SExtOrSelf (const OpTy & Op) inline
Definition at line 2298 of file PatternMatch.h.
References m_CombineOr(), and m_SExt().
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), matchOrConcat(), llvm::InstCombinerImpl::simplifyRangeCheck(), and llvm::InstCombinerImpl::visitAnd().
m_Shift()
template<typename LHS, typename RHS> BinOpPred_match< LHS, RHS, is_shift_op > llvm::PatternMatch::m_Shift (const LHS & L, const RHS & R) inline
Matches shift operations.
Definition at line 1671 of file PatternMatch.h.
References LHS, and RHS.
Referenced by detectShiftUntilZeroIdiom(), dropRedundantMaskingOfLeftShiftInput(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldCttzCtlz(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), and llvm::InstCombinerImpl::visitZExt().
m_ShiftedMask()
cst_pred_ty< is_shifted_mask > llvm::PatternMatch::m_ShiftedMask () inline
Definition at line 527 of file PatternMatch.h.
Referenced by foldNegativePower2AndShiftedMask().
m_Shl()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Shl > llvm::PatternMatch::m_Shl (const LHS & L, const RHS & R) inline
Definition at line 1340 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeLowbitMask(), combineAdd(), combineAddSubWithShlAddSub(), combineNarrowableShiftedLoad(), combineSetCC(), combineShlAddIAddImpl(), computeKnownBitsFromCmp(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), detectShiftUntilBitTestIdiom(), dropRedundantMaskingOfLeftShiftInput(), factorizeMathWithShlOps(), llvm::InstCombinerImpl::foldAddLikeCommutative(), llvm::InstCombinerImpl::foldAddWithConstant(), foldBitCeil(), foldBoxMultiply(), foldCttzCtlz(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpWithHighBitMask(), foldICmpWithTruncSignExtendedVal(), foldIDivShl(), foldMulShl1(), foldSelectICmpAndZeroShl(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), getBinOpsForFactorization(), haveNoCommonBitsSetSpecialCases(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::isKnownToBeAPowerOfTwo(), isLoadCombineCandidateImpl(), isNonEqualShl(), llvm::X86TTIImpl::isProfitableToSinkOperands(), MatchMul(), matchOrConcat(), matchZExtedSubInteger(), narrowBitOpRMW(), PerformSELECTShiftCombine(), setShiftFlags(), shouldCanonicalizeGEPToPtrAdd(), shouldSinkVScale(), simplifyAndCommutative(), simplifyAndInst(), simplifyAShrInst(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyIRemMulShl(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyOrInst(), simplifyShiftSelectingPackedElement(), simplifyValueKnownNonZero(), splitMergedValStore(), llvm::InstCombinerImpl::takeLog2(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitXor().
m_ShlOrSelf()
template<typename LHS> ShiftLike_match< LHS, Instruction::Shl > llvm::PatternMatch::m_ShlOrSelf (const LHS & L, uint64_t & R) inline
Matches shl L, ConstShAmt or L itself (R will be set to zero in this case).
Definition at line 1377 of file PatternMatch.h.
References LHS.
Referenced by foldLoadsRecursive(), and matchSubIntegerPackFromVector().
m_Shr()
template<typename LHS, typename RHS> BinOpPred_match< LHS, RHS, is_right_shift_op > llvm::PatternMatch::m_Shr (const LHS & L, const RHS & R) inline
Matches logical shift operations.
Definition at line 1678 of file PatternMatch.h.
References LHS, and RHS.
Referenced by computeKnownBitsFromCmp(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldSignBitTest(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), optimizeBranch(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyShlInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitShl(), and llvm::InstCombinerImpl::visitTrunc().
m_Shuffle() [1/2]
template<typename V1_t, typename V2_t> TwoOps_match< V1_t, V2_t, Instruction::ShuffleVector > llvm::PatternMatch::m_Shuffle (const V1_t & v1, const V2_t & v2) inline
Matches ShuffleVectorInst independently of mask value.
Definition at line 2066 of file PatternMatch.h.
Referenced by areExtractShuffleVectors(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::InstCombinerImpl::foldICmpBitCast(), foldIdentityExtractShuffle(), llvm::InstCombinerImpl::foldShuffledIntrinsicOperands(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::InstCombinerImpl::foldVectorSelect(), llvm::getSplatValue(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::ARMTTIImpl::isProfitableToSinkOperands(), llvm::RISCVTTIImpl::isProfitableToSinkOperands(), llvm::WebAssemblyTTIImpl::isProfitableToSinkOperands(), matchSubIntegerPackFromVector(), narrowVectorSelect(), llvm::InstCombinerImpl::simplifyBinOpSplats(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyReductionOperand(), and llvm::InstCombinerImpl::visitFNeg().
m_Shuffle() [2/2]
template<typename V1_t, typename V2_t, typename Mask_t> Shuffle_match< V1_t, V2_t, Mask_t > llvm::PatternMatch::m_Shuffle (const V1_t & v1, const V2_t & v2, const Mask_t & mask) inline
Definition at line 2072 of file PatternMatch.h.
References mask().
m_SignMask()
cst_pred_ty< is_sign_mask > llvm::PatternMatch::m_SignMask () inline
Match an integer or vector with only the sign bit(s) set.
For vectors, this includes constants with undefined elements.
Definition at line 676 of file PatternMatch.h.
Referenced by foldCopySignIdioms(), llvm::InstCombinerImpl::foldICmpBinOp(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), llvm::isKnownToBeAPowerOfTwo(), isPowerOfTwoRecurrence(), simplifyAddInst(), simplifyICmpWithBinOp(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitXor().
m_Signum()
template<typename Val_t> Signum_match< Val_t > llvm::PatternMatch::m_Signum (const Val_t & V) inline
Matches a signum pattern.
signum(x) = x > 0 -> 1 x == 0 -> 0 x < 0 -> -1
Definition at line 3158 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpOrConstant(), and llvm::InstCombinerImpl::foldICmpTruncConstant().
m_SIToFP()
template<typename OpTy> CastInst_match< OpTy, SIToFPInst > llvm::PatternMatch::m_SIToFP (const OpTy & Op) inline
Definition at line 2338 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpBitCast(), and simplifyUnaryIntrinsic().
m_SMax()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty > llvm::PatternMatch::m_SMax (const LHS & L, const RHS & R) inline
Definition at line 2524 of file PatternMatch.h.
References LHS, and RHS.
Referenced by detectSSatPattern(), detectSSatSPattern(), detectSSatUPattern(), detectUSatPattern(), foldClampRangeOfTwo(), llvm::InstCombinerImpl::foldICmpWithClamp(), FoldOrOfSelectSmaxToAbs(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), m_MaxOrMin(), matchClamp(), simplifyICmpWithMinMax(), tryToFPToSat(), and llvm::InstCombinerImpl::visitCallInst().
m_SMin()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty > llvm::PatternMatch::m_SMin (const LHS & L, const RHS & R) inline
Definition at line 2530 of file PatternMatch.h.
References LHS, and RHS.
Referenced by detectSSatPattern(), detectSSatSPattern(), detectSSatUPattern(), detectUSatPattern(), foldClampRangeOfTwo(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), m_MaxOrMin(), matchClamp(), simplifyICmpWithMinMax(), and tryToFPToSat().
m_Specific()
specificval_ty llvm::PatternMatch::m_Specific (const Value * V) inline
Match if we have a specific specified value.
Definition at line 988 of file PatternMatch.h.
Referenced by llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), breakSelfRecursivePHI(), canonicalizeAbs(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::VPlanTransforms::canonicalizeEVLLoops(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), canonicalizeSaturatedSubtract(), llvm::SCEVExpander::canReuseFlagsFromOriginalIVInc(), checkOuterLoopInsts(), collectComplementaryPredicatedMemOps(), combineLogicBlendIntoConditionalNegate(), combineSelect(), combineShiftLeft(), combineShiftRightLogical(), llvm::InstCombinerImpl::commonIDivTransforms(), computeKnownBitsFromCmp(), computeKnownBitsFromCond(), llvm::computeKnownBitsFromContext(), computeKnownBitsFromICmpCond(), computeKnownBitsFromLerpPattern(), computeKnownBitsFromOperator(), computeKnownFPClassFromCond(), llvm::computeOverflowForSignedSub(), llvm::computeOverflowForUnsignedSub(), convertFSqrtDivIntoFMul(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), createWidenInductionRecipe(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), directlyImpliesPoison(), factorizeFAddFSub(), factorizeMathWithShlOps(), llvm::findHistogram(), fixReductionScalarResumeWhenVectorizingEpilog(), foldAbsDiff(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldAddToAshr(), foldAndOrOfICmpEqConstantAndICmp(), foldAndOrOfICmpsWithConstEq(), foldAndOrOfICmpsWithPow2AndWithZero(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), llvm::InstCombinerImpl::foldBinOpSelectBinOp(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldBoxMultiply(), foldComplexAndOrPatterns(), foldCttzCtlz(), foldDependentIVs(), foldFCmpFNegCommonOp(), foldFCmpWithFloorAndCeil(), llvm::InstCombinerImpl::foldFMulReassoc(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpEqualityWithOffset(), foldICmpOrXX(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpWithClamp(), foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithLowBitMaskedVal(), foldICmpXorXX(), foldIDivShl(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), foldMinMaxSharedOp(), foldMulHigh(), foldNestedSelects(), llvm::InstCombinerImpl::foldOpIntoPhi(), FoldOrOfSelectSmaxToAbs(), foldOrToXor(), foldOverflowingAddSubSelect(), llvm::InstCombinerImpl::foldPowiReassoc(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBinOpIdentity(), foldSelectFunnelShift(), foldSelectICmpAndAnd(), foldSelectICmpAndBinOp(), foldSelectICmpAndZeroShl(), foldSelectICmpLshrAshr(), foldSelectICmpMinMax(), foldSelectIntoAddConstant(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectToPhiImpl(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), foldSelectWithExtremeEqCond(), foldSelectWithFCmpToFabs(), foldSelectWithSRem(), foldSelectZeroOrFixedOp(), foldSetClearBits(), foldSignedTruncationCheck(), foldSubOfMinMax(), foldToMaskedStore(), foldTruncInsEltPair(), foldUnsignedUnderflowCheck(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), foldXorToXor(), getBundleFromUse(), llvm::PredicateBase::getConstraint(), getFSqrtDivOptPattern(), getInvertibleOperands(), getOptimizableIVOf(), getRangeForSelectPattern(), llvm::VPlanTransforms::handleMultiUseReductions(), haveNoCommonBitsSetSpecialCases(), impliesPoisonOrCond(), llvm::ARMTTIImpl::instCombineIntrinsic(), instCombineSVEVectorFuseMulAddSub(), instCombineSVEZip(), llvm::invertCondition(), isConditionalOnXorOfPHIs(), isConditionTrueViaVFAndUF(), isDivZero(), isEqualImpl(), llvm::RecurrenceDescriptor::isFindIVPattern(), llvm::vputils::isHeaderMask(), isImpliedCondICmps(), isImpliedToBeAPowerOfTwoFromCond(), llvm::ConstantPtrAuth::isKnownCompatibleWith(), llvm::isKnownInversion(), llvm::isKnownNegation(), isKnownNonNullFromDominatingCondition(), isKnownNonZeroFromAssume(), isKnownNonZeroFromOperator(), llvm::isKnownToBeAPowerOfTwo(), isNonEqualMul(), isNonEqualShl(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), isRemOfLoopIncrementWithLoopInvariant(), isSafeToRemoveBitCeilSelect(), isSignificantBitCheckWellFormed(), isTruePredicate(), isUsedWithinShuffleVector(), lookThroughCast(), RemoveMask_match< Op0_t, Op1_t >::match(), matchClamp(), matchExpandedRem(), matchFastFloatClamp(), matchFMulByZeroIfResultEqZero(), matchICmpOperand(), matchMinMaxOfMinMax(), matchOpWithOpEqZero(), matchOrConcat(), matchSelectPattern(), matchSelectWithOptionalNotCond(), matchUAddWithOverflowConstantEdgeCases(), optimizeBranch(), optimizeMaskToEVL(), optimizeVectorInductionWidthForTCAndVFUF(), passingValueIsAlwaysUndefined(), processUse(), removeCommonBlendMask(), setLimitsForBinOp(), setShiftFlags(), shouldExpandCmpArithRMWInIR(), llvm::X86TargetLowering::shouldFoldSelectWithIdentityConstant(), simplifyAddInst(), simplifyAndCommutative(), simplifyAndInst(), simplifyAndOfICmpsWithAdd(), simplifyAndOrOfFCmps(), simplifyAndOrOfICmpsWithCtpop(), simplifyAShrInst(), llvm::simplifyBinaryIntrinsic(), simplifyCmpSelOfMaxMin(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyDiv(), simplifyDivRem(), simplifyFAddInst(), simplifyFDivInst(), simplifyFSubInst(), simplifyGEPInst(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithIntrinsicOnLHS(), llvm::simplifyInsertElementInst(), simplifyIntrinsic(), simplifyIRemMulShl(), simplifyLogicOfAddSub(), simplifyLShrInst(), simplifyMulInst(), simplifyOperationIntoSelectOperand(), simplifyOrInst(), simplifyOrLogic(), simplifyOrOfICmpsWithAdd(), llvm::InstCombinerImpl::simplifyRangeCheck(), simplifyRecipe(), simplifyRem(), simplifySelectBitTest(), simplifySelectInst(), simplifySelectWithICmpCond(), simplifyShlInst(), simplifySubInst(), simplifySwitchOnSelectUsingRanges(), simplifyUnsignedRangeCheck(), simplifyXorInst(), llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), swapICmpOperandsToExposeCSEOpportunities(), trySimplifyICmpWithAdds(), tryToMoveFreeBeforeNullTest(), tryToRecognizePopCount(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitXor(), and llvm::InstCombinerImpl::visitZExt().
m_SpecificBB()
specific_bbval llvm::PatternMatch::m_SpecificBB (BasicBlock * BB) inline
Match a specific basic block value.
Definition at line 1119 of file PatternMatch.h.
Referenced by foldGuardedFunnelShift().
m_SpecificCmp()
template<typename LHS, typename RHS> SpecificCmpClass_match< LHS, RHS, CmpInst > llvm::PatternMatch::m_SpecificCmp (CmpPredicate MatchPred, const LHS & L, const RHS & R) inline
Definition at line 1837 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::VPlanTransforms::canonicalizeEVLLoops(), foldOrUnsignedUMulOverflowICmp(), and simplifyRecipe().
m_SpecificFCmp()
template<typename LHS, typename RHS> SpecificCmpClass_match< LHS, RHS, FCmpInst > llvm::PatternMatch::m_SpecificFCmp (CmpPredicate MatchPred, const LHS & L, const RHS & R) inline
Definition at line 1855 of file PatternMatch.h.
References LHS, and RHS.
Referenced by reassociateFCmps().
m_SpecificFP()
specific_fpval llvm::PatternMatch::m_SpecificFP (double V) inline
Match a specific floating point value or vector with all elements equal to the value.
Definition at line 1031 of file PatternMatch.h.
Referenced by convertFSqrtDivIntoFMul(), llvm::InstCombinerImpl::foldFMulReassoc(), foldMulSelectToNegate(), llvm::InstCombinerImpl::foldSquareSumFP(), getFSqrtDivOptPattern(), m_FPOne(), simplifyUnaryIntrinsic(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFDiv(), and llvm::InstCombinerImpl::visitFMul().
m_SpecificICmp()
template<typename LHS, typename RHS> SpecificCmpClass_match< LHS, RHS, ICmpInst > llvm::PatternMatch::m_SpecificICmp (CmpPredicate MatchPred, const LHS & L, const RHS & R) inline
Definition at line 1843 of file PatternMatch.h.
References LHS, and RHS.
Referenced by fixReductionScalarResumeWhenVectorizingEpilog(), foldGuardedFunnelShift(), foldIsPowerOf2(), foldMulHigh(), llvm::InstCombinerImpl::foldOpIntoPhi(), FoldOrOfSelectSmaxToAbs(), foldSelectFunnelShift(), foldSelectWithExtremeEqCond(), foldSignedTruncationCheck(), llvm::X86TargetLowering::getJumpConditionMergingParams(), isConditionTrueViaVFAndUF(), matchOpWithOpEqZero(), processUse(), shouldExpandCmpArithRMWInIR(), simplifyOperationIntoSelectOperand(), llvm::stripNullTest(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitOr().
m_SpecificInt() [1/2]
specific_intval< false > llvm::PatternMatch::m_SpecificInt (const APInt & V) inline
Match a specific integer value or vector with all elements equal to the value.
Definition at line 1086 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeSaturatedSubtract(), combineAdd(), combineOr(), combineSelect(), combineShiftLeft(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShiftToPMULH(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), detectSSatPattern(), detectSSatSPattern(), detectSSatUPattern(), detectUSatUPattern(), expandMulToAddOrSubOfShl(), FindSingleBitChange(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndToUsubsat(), foldBitCeil(), foldBoxMultiply(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpEquality(), foldInsEltIntoIdentityShuffle(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), foldMulHigh(), foldOverflowingAddSubSelect(), foldSelectFunnelShift(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectWithExtremeEqCond(), foldSelectWithSRem(), llvm::InstCombinerImpl::foldSquareSumInt(), getShlAddShlAdd(), instCombineLD1GatherIndex(), instCombineST1ScatterIndex(), instCombineSVEDup(), isAddSubOrSubAdd(), llvm::AArch64TTIImpl::isExtPartOfAvgExpr(), llvm::X86TTIImpl::isProfitableToSinkOperands(), isSignificantBitCheckWellFormed(), isSupportedMemset(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), matchOrConcat(), optimizeBranch(), performLastTrueTestVectorCombine(), PerformSELECTShiftCombine(), preparePlanForEpilogueVectorLoop(), processUse(), simplifyAndInst(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyGEPInst(), simplifyIntrinsic(), simplifyOrInst(), simplifySelectWithICmpCond(), simplifyShlInst(), splitMergedValStore(), tryToRecognizePopCount(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), and widenBuildVector().
m_SpecificInt() [2/2]
specific_intval64< false > llvm::PatternMatch::m_SpecificInt (uint64_t V) inline
Definition at line 1090 of file PatternMatch.h.
m_SpecificInt_ICMP()
cst_pred_ty< icmp_pred_with_threshold > llvm::PatternMatch::m_SpecificInt_ICMP (ICmpInst::Predicate Predicate, const APInt & Threshold) inline
Match an integer or vector with every element comparing 'pred' (eg/ne/...) to Threshold.
For vectors, this includes constants with undefined elements.
Definition at line 712 of file PatternMatch.h.
References P.
Referenced by canNarrowShiftAmt(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), foldSelectICmpAndAnd(), foldSelectICmpLshrAshr(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), llvm::InstCombinerImpl::foldSignBitTest(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombinerImpl::visitAnd(), and llvm::InstCombinerImpl::visitTrunc().
m_SpecificIntAllowPoison() [1/2]
specific_intval< true > llvm::PatternMatch::m_SpecificIntAllowPoison (const APInt & V) inline
Definition at line 1094 of file PatternMatch.h.
Referenced by canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpEqConstantAndICmp(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::FoldShiftByConstant(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSExt().
m_SpecificIntAllowPoison() [2/2]
specific_intval64< true > llvm::PatternMatch::m_SpecificIntAllowPoison (uint64_t V) inline
Definition at line 1098 of file PatternMatch.h.
m_Sqrt()
template<typename Opnd0> m_Intrinsic_Ty< Opnd0 >::Ty llvm::PatternMatch::m_Sqrt (const Opnd0 & Op0) inline
Definition at line 2947 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::InstCombinerImpl::foldFMulReassoc(), foldSqrtWithFcmpZero(), getFSqrtDivOptPattern(), and simplifyFMAFMul().
m_SRem()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::SRem > llvm::PatternMatch::m_SRem (const LHS & L, const RHS & R) inline
Definition at line 1310 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::computeOverflowForSignedSub(), foldSelectWithSRem(), isDivZero(), MatchRem(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitSRem().
m_Store()
template<typename ValueOpTy, typename PointerOpTy> TwoOps_match< ValueOpTy, PointerOpTy, Instruction::Store > llvm::PatternMatch::m_Store (const ValueOpTy & ValueOp, const PointerOpTy & PointerOp) inline
Matches StoreInst.
Definition at line 2085 of file PatternMatch.h.
Referenced by computeShapeInfoForInst(), llvm::findHistogram(), and slpvectorizer::BoUpSLP::isLoadCombineCandidate().
m_StrictlyPositive() [1/2]
cst_pred_ty< is_strictlypositive > llvm::PatternMatch::m_StrictlyPositive () inline
Match an integer or vector of strictly positive values.
For vectors, this includes constants with undefined elements.
Definition at line 582 of file PatternMatch.h.
Referenced by canonicalizeSaturatedAddSigned(), and llvm::InstCombinerImpl::visitCallInst().
m_StrictlyPositive() [2/2]
api_pred_ty< is_strictlypositive > llvm::PatternMatch::m_StrictlyPositive (const APInt *& V) inline
Definition at line 585 of file PatternMatch.h.
m_Sub()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Sub > llvm::PatternMatch::m_Sub (const LHS & L, const RHS & R) inline
Definition at line 1220 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeSaturatedSubtract(), combineAdd(), combineBasicSADPattern(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::VPlanTransforms::createInLoopReductionRecipes(), detectShiftUntilZeroIdiom(), llvm::findHistogram(), FindSingleBitChange(), llvm::findValuesAffectedByCondition(), foldAbsDiff(), llvm::InstCombinerImpl::foldAddLikeCommutative(), llvm::InstCombinerImpl::foldAddWithConstant(), foldBitCeil(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOrXorSubChain(), foldSelectFunnelShift(), foldSubCtlzNot(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombiner::getFreelyInvertedImpl(), getKnownBitsFromAndXorOr(), getOptimizableIVOf(), llvm::vputils::getSCEVExprForVPValue(), haveNoCommonBitsSetSpecialCases(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), isImpliedCondICmps(), llvm::isKnownNegation(), isSafeToRemoveBitCeilSelect(), m_Neg(), matchExpandedRem(), matchIncrement(), optimizeBranch(), processUse(), shouldExpandCmpArithRMWInIR(), simplifyAddInst(), simplifyCastInst(), simplifyGEPInst(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithIntrinsicOnLHS(), simplifyLogicOfAddSub(), simplifyOrInst(), simplifySubInst(), simplifyUnsignedRangeCheck(), swapICmpOperandsToExposeCSEOpportunities(), tryToMatchAndCreateMulAccumulateReduction(), tryToRecognizePopCount(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), and llvm::InstCombinerImpl::visitXor().
m_Trunc()
template<typename OpTy> CastInst_match< OpTy, TruncInst > llvm::PatternMatch::m_Trunc (const OpTy & Op) inline
Matches Trunc.
Definition at line 2249 of file PatternMatch.h.
Referenced by addValueAffectedByCondition(), collectBitParts(), computeKnownBitsFromCond(), computeKnownBitsFromICmpCond(), llvm::decomposeBitTest(), llvm::decomposeBitTestICmp(), dropRedundantMaskingOfLeftShiftInput(), llvm::findValuesAffectedByCondition(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldSignedTruncationCheck(), foldTruncInsEltPair(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::vputils::getSCEVExprForVPValue(), m_TruncOrSelf(), m_ZExtOrTruncOrSelf(), matchIntPart(), matchPartStore(), performAddTruncShiftCombine(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), reverseZExtICmpCombine(), simplifyRecipe(), simplifySubInst(), llvm::InstCombinerImpl::takeLog2(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitZExt(), and widenBuildVector().
m_TruncOrSelf()
template<typename OpTy> match_combine_or< CastInst_match< OpTy, TruncInst >, OpTy > llvm::PatternMatch::m_TruncOrSelf (const OpTy & Op) inline
Definition at line 2269 of file PatternMatch.h.
References m_CombineOr(), and m_Trunc().
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::InstCombinerImpl::foldSignBitTest(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::VPlanTransforms::handleMultiUseReductions(), PerformSELECTShiftCombine(), llvm::InstCombinerImpl::visitAdd(), and llvm::InstCombinerImpl::visitXor().
m_UAddWithOverflow()
template<typename LHS_t, typename RHS_t, typename Sum_t> UAddWithOverflow_match< LHS_t, RHS_t, Sum_t > llvm::PatternMatch::m_UAddWithOverflow (const LHS_t & L, const RHS_t & R, const Sum_t & S)
Match an icmp instruction checking for unsigned overflow on addition.
S is matched to the addition whose result is being checked for overflow, and L and R are matched to the LHS and RHS of S.
Definition at line 2730 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::visitICmpInst().
m_UDiv()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::UDiv > llvm::PatternMatch::m_UDiv (const LHS & L, const RHS & R) inline
Definition at line 1286 of file PatternMatch.h.
References LHS, and RHS.
Referenced by llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), isTruePredicate(), MatchDiv(), processUse(), simplifyDivRem(), simplifyICmpWithBinOpOnLHS(), simplifyRecipe(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::InstCombinerImpl::visitMul().
m_UIToFP()
template<typename OpTy> CastInst_match< OpTy, UIToFPInst > llvm::PatternMatch::m_UIToFP (const OpTy & Op) inline
Definition at line 2333 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpBitCast(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), simplifyICmpWithConstant(), simplifyUnaryIntrinsic(), and llvm::InstCombinerImpl::visitFMul().
m_UMax()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty > llvm::PatternMatch::m_UMax (const LHS & L, const RHS & R) inline
Definition at line 2536 of file PatternMatch.h.
References LHS, and RHS.
Referenced by combineBasicSADPattern(), llvm::InstCombinerImpl::foldAddWithConstant(), foldClampRangeOfTwo(), llvm::InstCombinerImpl::foldICmpWithClamp(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), m_MaxOrMin(), matchClamp(), and simplifyICmpWithMinMax().
m_UMin()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty > llvm::PatternMatch::m_UMin (const LHS & L, const RHS & R) inline
Definition at line 2542 of file PatternMatch.h.
References LHS, and RHS.
Referenced by combineBasicSADPattern(), combineShiftRightArithmetic(), detectSSatUPattern(), detectUSatPattern(), detectUSatUPattern(), foldClampRangeOfTwo(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSubOfMinMax(), foldToUnsignedSaturatedAdd(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), m_MaxOrMin(), matchClamp(), processUse(), simplifyICmpWithMinMax(), and simplifySwitchWhenUMin().
m_UnconditionalBr()
br_match llvm::PatternMatch::m_UnconditionalBr (BasicBlock *& Succ) inline
Definition at line 2381 of file PatternMatch.h.
Referenced by tryToMoveFreeBeforeNullTest().
m_Undef()
auto llvm::PatternMatch::m_Undef () inline
Match an arbitrary undef constant.
This matches poison as well. If this is an aggregate and contains a non-aggregate element that is neither undef nor poison, the aggregate is not matched.
Definition at line 165 of file PatternMatch.h.
Referenced by areExtractShuffleVectors(), combineOr(), combineTargetShuffle(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::ConstantFoldBinaryInstruction(), evaluateInDifferentElementOrder(), llvm::InstCombinerImpl::foldICmpBitCast(), foldIdentityPaddedShuffles(), foldInsEltIntoSplat(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectZeroOrFixedOp(), foldTruncInsEltPair(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::ARMTTIImpl::isProfitableToSinkOperands(), llvm::SimplifyQuery::isUndefValue(), likeBitCastFromVector(), markAliveBlocks(), llvm::Constant::mergeUndefsWith(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::Constant::replaceUndefsWith(), shrinkInsertElt(), shrinkSplatShuffle(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyReductionOperand(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::InstCombinerImpl::visitSelectInst(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
m_UndefValue() [1/2]
class_match< UndefValue > llvm::PatternMatch::m_UndefValue () inline
Match an arbitrary UndefValue constant.
Definition at line 168 of file PatternMatch.h.
m_UndefValue() [2/2]
bind_ty< UndefValue > llvm::PatternMatch::m_UndefValue (UndefValue *& U) inline
Match an UndefValue, capturing the value if we match.
Definition at line 911 of file PatternMatch.h.
m_Unless()
template<typename Ty> match_unless< Ty > llvm::PatternMatch::m_Unless (const Ty & M) inline
Match if the inner matcher does NOT match.
Definition at line 236 of file PatternMatch.h.
Referenced by llvm::InstCombinerImpl::foldICmpEquality(), getBundleFromUse(), and llvm::InstCombinerImpl::visitXor().
m_UnOp() [1/4]
class_match< UnaryOperator > llvm::PatternMatch::m_UnOp () inline
Match an arbitrary unary operation and ignore it.
Definition at line 108 of file PatternMatch.h.
Referenced by cheapToScalarize(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitExtractElementInst().
m_UnOp() [2/4]
template<typename OP_t> AnyUnaryOp_match< OP_t > llvm::PatternMatch::m_UnOp (const OP_t & X) inline
Definition at line 1174 of file PatternMatch.h.
References X.
m_UnOp() [3/4]
bind_ty< const UnaryOperator > llvm::PatternMatch::m_UnOp (const UnaryOperator *& I) inline
Definition at line 893 of file PatternMatch.h.
References I.
m_UnOp() [4/4]
bind_ty< UnaryOperator > llvm::PatternMatch::m_UnOp (UnaryOperator *& I) inline
Match a unary operator, capturing it if we match.
Definition at line 892 of file PatternMatch.h.
References I.
m_UnordFMax()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ufmax_pred_ty > llvm::PatternMatch::m_UnordFMax (const LHS & L, const RHS & R) inline
Match an 'unordered' floating point maximum function.
Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'maximum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ugt/ge, L, R), L, R) semantics matched by this predicate.
                    max(L, R)  iff L and R are not NaN
m_UnordFMax(L, R) = L iff L or R are NaN
Definition at line 2599 of file PatternMatch.h.
References LHS, and RHS.
m_UnordFMin()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ufmin_pred_ty > llvm::PatternMatch::m_UnordFMin (const LHS & L, const RHS & R) inline
Match an 'unordered' floating point minimum function.
Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'minimum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ult/le, L, R), L, R) semantics matched by this predicate.
                     min(L, R)  iff L and R are not NaN
m_UnordFMin(L, R) = L iff L or R are NaN
Definition at line 2614 of file PatternMatch.h.
References LHS, and RHS.
m_URem()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::URem > llvm::PatternMatch::m_URem (const LHS & L, const RHS & R) inline
Definition at line 1304 of file PatternMatch.h.
References LHS, and RHS.
Referenced by canScalarizeAccess(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::computeOverflowForUnsignedSub(), llvm::InstCombinerImpl::foldICmpWithZero(), isRemOfLoopIncrementWithLoopInvariant(), MatchRem(), and simplifyICmpWithBinOpOnLHS().
m_Value() [1/5]
class_match< Value > llvm::PatternMatch::m_Value () inline
Match an arbitrary value and ignore it.
Definition at line 105 of file PatternMatch.h.
Referenced by addValueAffectedByCondition(), analyzeCostOfVecReduction(), analyzeICmp(), annotateNonNullAndDereferenceable(), areExtractExts(), areExtractExts(), areExtractShuffleVectors(), breakSelfRecursivePHI(), llvm::canConvertToMinOrMaxIntrinsic(), llvm::InstCombiner::canFreelyInvertAllUsersOf(), canonicalizeAbs(), canonicalizeBitCastExtElt(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeGEPOfConstGEPI8(), canonicalizeInsertSplat(), canonicalizeLogicFirst(), canonicalizeLowbitMask(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), canonicalizeScalarSelectOfVecs(), llvm::canPeelLastIteration(), canProveExitOnFirstIteration(), llvm::SCEVExpander::canReuseFlagsFromOriginalIVInc(), canSafelyConvertTo16Bit(), canScalarizeAccess(), canShiftBinOpWithConstantRHS(), cheapToScalarize(), checkForNegativeOperand(), checkOrAndOpImpliedByOther(), collectBitParts(), collectUnswitchCandidatesWithInjections(), combineAdd(), combineAddSubWithShlAddSub(), combineAnd(), combineAndNotOrIntoAndNotAnd(), combineAndXorSubWithBMI(), combineBasicSADPattern(), combineCastedMaskArithmetic(), combineLogicBlendIntoConditionalNegate(), combineNarrowableShiftedLoad(), combineOr(), combineOrAndToBitfieldInsert(), combineOrToBitfieldInsert(), combinePMULH(), combineSCALAR_TO_VECTOR(), combineSetCC(), combineShiftRightArithmetic(), combineShiftToPMULH(), combineShlAddIAddImpl(), combineTargetShuffle(), combineXorToBitfieldInsert(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::InstCombinerImpl::commonIDivRemTransforms(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), commuteSelect(), computeKnownBitsFromCmp(), computeKnownBitsFromCond(), computeKnownBitsFromLerpPattern(), computeKnownBitsFromOperator(), computeKnownFPClass(), computeKnownFPClassFromCond(), ComputeNumSignBitsImpl(), llvm::computeOverflowForSignedSub(), llvm::computeOverflowForUnsignedSub(), computeShapeInfoForInst(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), countToEliminateCompares(), decompose(), llvm::decomposeBitTest(), llvm::decomposeBitTestICmp(), detectPMADDUBSW(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), detectSSatPattern(), detectSSatSPattern(), detectSSatUPattern(), detectUSatPattern(), detectUSatUPattern(), dropRedundantMaskingOfLeftShiftInput(), expandMulToAddOrSubOfShl(), factorizeFAddFSub(), factorizeLerp(), factorizeMathWithShlOps(), llvm::findHistogram(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::findScalarElement(), FindSingleBitChange(), llvm::findValuesAffectedByCondition(), fixReductionScalarResumeWhenVectorizingEpilog(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldAddSubBoolOfMaskedVal(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithConstEq(), foldAndOrOfICmpsWithPow2AndWithZero(), foldAndToUsubsat(), foldAndToXor(), foldAnyOrAllBitsSet(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), foldBitCastBitwiseLogic(), foldBitCastSelect(), foldBitCeil(), foldBitOrderCrossLogicOp(), foldBitOrderCrossLogicOp(), foldBoxMultiply(), foldClampRangeOfTwo(), foldComplexAndOrPatterns(), foldCopySignIdioms(), foldCtpop(), foldCttzCtlz(), foldFabsWithFcmpZero(), foldFCmpFNegCommonOp(), foldFDivConstantDividend(), foldFDivSqrtDivisor(), llvm::InstCombinerImpl::foldFMulReassoc(), foldFNegIntoConstant(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpEqualityWithOffset(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), foldICmpOfUAddOv(), foldICmpOrChain(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpOrXorSubChain(), foldICmpOrXX(), foldICmpPow2Test(), foldICmpShlLHSC(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), llvm::InstCombinerImpl::foldICmpWithConstant(), foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldICmpXorXX(), foldIdentityExtractShuffle(), foldIDivShl(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), foldLoadsRecursive(), foldLogicCastConstant(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldMaskedMerge(), foldMinimumOverTrailingOrLeadingZeroCount(), foldMinMaxSharedOp(), foldMulHigh(), foldMulSelectToNegate(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldNestedSelects(), foldNotXor(), foldNoWrapAdd(), foldOrOfInversions(), FoldOrOfSelectSmaxToAbs(), foldOrToXor(), foldOrUnsignedUMulOverflowICmp(), foldOverflowingAddSubSelect(), llvm::InstCombinerImpl::foldPowiReassoc(), llvm::InstCombinerImpl::foldPtrToIntOrAddrOfGEP(), foldReduceOperandViaVQDOT(), foldReductionIdiom(), llvm::InstCombinerImpl::foldReversedIntrinsicOperands(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBinOpIdentity(), foldSelectBitTest(), foldSelectCmpBitcasts(), foldSelectFunnelShift(), foldSelectGEP(), foldSelectICmpAndAnd(), foldSelectICmpAndZeroShl(), foldSelectICmpLshrAshr(), foldSelectIntoAddConstant(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectOfSymmetricSelect(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectToCopysign(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), foldSelectWithExtremeEqCond(), foldSelectWithIdentityConstant(), foldSelectWithSRem(), foldSelectZeroOrFixedOp(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), llvm::InstCombinerImpl::foldShuffledIntrinsicOperands(), foldShuffleOfUnaryOps(), foldShuffleWithInsert(), llvm::InstCombinerImpl::foldSignBitTest(), foldSignedTruncationCheck(), foldSqrtWithFcmpZero(), foldSubCtlzNot(), foldSubOfMinMax(), foldToMaskedStore(), foldToUnsignedSaturatedAdd(), foldTruncInsEltPair(), foldTruncShuffle(), foldTwoEntryPHINode(), foldUnsignedUnderflowCheck(), foldURemOfLoopIncrement(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVecExtTruncToExtElt(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::InstCombinerImpl::foldVectorSelect(), foldVecTruncToExtElt(), foldVSelectToSignBitSplatMask(), foldXorToXor(), getAppleRuntimeUnrollPreferences(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), getBinOpsForFactorization(), getBoolVecFromMask(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::InstCombiner::getComplexity(), getDomPredecessorCondition(), llvm::InstCombiner::getFreelyInvertedImpl(), getFSqrtDivOptPattern(), getHashValueImpl(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), getInvertibleOperands(), llvm::SystemZTargetLowering::getJumpConditionMergingParams(), llvm::X86TargetLowering::getJumpConditionMergingParams(), getKnownBitsFromAndXorOr(), getKnownSign(), getKnownSignOrZero(), getMaskedTypeForICmpPair(), getNotValue(), llvm::AMDGPUTargetMachine::getPredicatedAddrSpace(), llvm::LoopVectorizationCostModel::getReductionPatternCost(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), getShlAddShlAdd(), llvm::X86TTIImpl::getShuffleCost(), llvm::getSplatValue(), getUnsignedMonotonicValues(), haveNoCommonBitsSetSpecialCases(), hoistAdd(), hoistAddSub(), hoistInsEltConst(), hoistMinMax(), hoistSub(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), instCombineLD1GatherIndex(), instCombineST1ScatterIndex(), instCombineSVEDupqLane(), instCombineSVELast(), instCombineSVESrshl(), instCombineSVEUzp1(), instCombineSVEVectorFuseMulAddSub(), instCombineSVEZip(), llvm::invertCondition(), isAllActivePredicate(), isAMXCast(), llvm::RecurrenceDescriptor::isAnyOfPattern(), llvm::isCheckForZeroAndMulWithOverflow(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), isDivZero(), isEqualImpl(), llvm::AArch64TTIImpl::isExtPartOfAvgExpr(), llvm::RecurrenceDescriptor::isFindIVPattern(), isFNeg(), isImpliedCondAndOr(), isImpliedCondICmps(), llvm::isImpliedCondition(), llvm::isImpliedCondition(), isInstructionPairMul(), llvm::ConstantPtrAuth::isKnownCompatibleWith(), isKnownExactCastIntToFP(), llvm::isKnownInversion(), llvm::isKnownNegation(), isKnownNonEqual(), isKnownNonNullFromDominatingCondition(), isKnownNonZeroFromAssume(), isKnownNonZeroFromOperator(), llvm::isKnownToBeAPowerOfTwo(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), slpvectorizer::BoUpSLP::isLoadCombineCandidate(), isLoadCombineCandidateImpl(), isMaskOrZero(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), isMultipleOfN(), isNeg(), llvm::isOnlyUsedInZeroComparison(), isOperandOfVmullHighP64(), isProcessableCondBI(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), llvm::ARMTTIImpl::isProfitableToSinkOperands(), llvm::GCNTTIImpl::isProfitableToSinkOperands(), llvm::RISCVTTIImpl::isProfitableToSinkOperands(), llvm::WebAssemblyTTIImpl::isProfitableToSinkOperands(), llvm::X86TTIImpl::isProfitableToSinkOperands(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), isReductionCandidate(), isRemOfLoopIncrementWithLoopInvariant(), isSafeToRemoveBitCeilSelect(), isSignificantBitCheckWellFormed(), llvm::isSplatValue(), isTruePredicate(), isTruncateOf(), LinearizeExprTree(), lowerBUILD_VECTOR(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), m_c_Select(), m_LogicalAnd(), m_LogicalOp(), m_LogicalOr(), llvm::PatternMatch::Signum_match< Opnd_t >::match(), llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match(), matchAndOrChain(), matchBitmaskMul(), matchDeMorgansLaws(), MatchDiv(), matchesAdd(), matchesOr(), matchesSquareSum(), matchExpandedRem(), matchFMulByZeroIfResultEqZero(), matchFPExtFromF16(), matchICmpOperand(), matchIntPart(), matchLogicBlend(), MatchMul(), matchOrConcat(), matchPartStore(), matchPMADDWD(), matchPMADDWD_2(), matchRdxBop(), MatchRem(), matchSelectWithOptionalNotCond(), matchSubIntegerPackFromVector(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), matchVPMADD52(), matchZExtedSubInteger(), moveAddAfterMinMax(), narrowBitOpRMW(), narrowInsElt(), narrowUDivURem(), narrowVectorSelect(), NegateValue(), OptimizeAndOrXor(), optimizeLoopExitWithUnknownExitCount(), optimizeShiftInOrChain(), optimizeSymmetricCall(), parseCondition(), llvm::parseWidenableBranch(), passingValueIsAlwaysUndefined(), performAddTruncShiftCombine(), performAnyAllCombine(), performBitcastCombine(), performCTPOPCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformSELECTShiftCombine(), processUse(), reassociateFCmps(), reassociateForUses(), reassociateMinMaxWithConstantInOperand(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::recognizeBSwapOrBitReverseIdiom(), recordCondition(), replaceSubOverflowUses(), reverseZExtICmpCombine(), setShiftFlags(), llvm::InstCombiner::shouldAvoidAbsorbingNotIntoSelect(), ShouldBreakUpSubtract(), shouldCanonicalizeGEPToPtrAdd(), shouldExpandCmpArithRMWInIR(), llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect(), simplifyAddInst(), llvm::InstCombinerImpl::SimplifyAddWithRemainder(), simplifyAndCommutative(), simplifyAndInst(), simplifyAndOfICmpsWithAdd(), simplifyAndOrOfICmpsWithCtpop(), simplifyAndOrWithICmpEq(), simplifyAShrInst(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::simplifyBinOpSplats(), simplifyCastInst(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyDiv(), simplifyDivRem(), simplifyExtractValueInst(), simplifyFAddInst(), simplifyFCmpInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFNegInst(), simplifyFSubInst(), simplifyGEPInst(), simplifyICmpOfBools(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithConstant(), simplifyICmpWithMinMax(), llvm::simplifyInstruction(), simplifyIntrinsic(), simplifyIRemMulShl(), simplifyLogicOfAddSub(), llvm::simplifyLoopAfterUnroll(), simplifyLShrInst(), simplifyMulInst(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyOperationIntoSelectOperand(), simplifyOrInst(), simplifyOrLogic(), simplifyOrOfICmpsWithAdd(), simplifyReductionOperand(), simplifyRem(), simplifySelectInst(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifySelectWithFCmp(), simplifySelectWithICmpCond(), simplifyShift(), simplifyShiftSelectingPackedElement(), simplifyShlInst(), simplifyShuffleVectorInst(), simplifySRemInst(), simplifySubInst(), simplifySwitchWhenUMin(), simplifyUnaryIntrinsic(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), simplifyXorInst(), llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp(), skipTrivialSelect(), splitMergedValStore(), llvm::stripNullTest(), stripSignOnlyFPOps(), takeInexpensiveLog2(), llvm::InstCombinerImpl::takeLog2(), llvm::InstCombinerImpl::tryFoldInstWithCtpopWithNot(), trySimplifyICmpWithAdds(), tryToFoldExtendSelectLoad(), tryToFPToSat(), tryToImproveAlign(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitExtractValueInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::InstCombinerImpl::visitIntToPtr(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitPtrToAddr(), llvm::InstCombinerImpl::visitPtrToInt(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), and widenBuildVector().
m_Value() [2/5]
bind_ty< const Value > llvm::PatternMatch::m_Value (const Value *& V) inline
Definition at line 857 of file PatternMatch.h.
m_Value() [3/5]
template<typename MatchTy> bind_and_match_ty< const Value, MatchTy > llvm::PatternMatch::m_Value (const Value *& V, const MatchTy & Match) inline
Match against the nested pattern, and capture the value if we match.
Definition at line 868 of file PatternMatch.h.
m_Value() [4/5]
bind_ty< Value > llvm::PatternMatch::m_Value (Value *& V) inline
Match a value, capturing it if we match.
Definition at line 856 of file PatternMatch.h.
m_Value() [5/5]
template<typename MatchTy> bind_and_match_ty< Value, MatchTy > llvm::PatternMatch::m_Value (Value *& V, const MatchTy & Match) inline
Match against the nested pattern, and capture the value if we match.
Definition at line 861 of file PatternMatch.h.
m_VecReverse()
template<typename Opnd0> m_Intrinsic_Ty< Opnd0 >::Ty llvm::PatternMatch::m_VecReverse (const Opnd0 & Op0) inline
Definition at line 2958 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::InstCombinerImpl::foldReversedIntrinsicOperands(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::InstCombinerImpl::foldVectorSelect(), simplifyReductionOperand(), simplifyUnaryIntrinsic(), and llvm::InstCombinerImpl::visitFNeg().
m_VectorInsert()
template<typename Opnd0, typename Opnd1, typename Opnd2> m_Intrinsic_Ty< Opnd0, Opnd1, Opnd2 >::Ty llvm::PatternMatch::m_VectorInsert (const Opnd0 & Op0, const Opnd1 & Op1, const Opnd2 & Op2) inline
Definition at line 2964 of file PatternMatch.h.
References m_Intrinsic(), and Op0.
Referenced by llvm::InstCombinerImpl::foldVectorBinop().
m_VScale()
IntrinsicID_match llvm::PatternMatch::m_VScale () inline
Matches a call to llvm.vscale().
Definition at line 3216 of file PatternMatch.h.
References m_Intrinsic().
Referenced by areBothVScale(), llvm::VPIntrinsic::canIgnoreVectorLengthParam(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::isKnownToBeAPowerOfTwo(), performLastTrueTestVectorCombine(), shouldSinkVScale(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitZExt().
m_WithOverflowInst() [1/2]
bind_ty< const WithOverflowInst > llvm::PatternMatch::m_WithOverflowInst (const WithOverflowInst *& I) inline
Definition at line 906 of file PatternMatch.h.
References I.
m_WithOverflowInst() [2/2]
bind_ty< WithOverflowInst > llvm::PatternMatch::m_WithOverflowInst (WithOverflowInst *& I) inline
Match a with overflow intrinsic, capturing it if we match.
Definition at line 902 of file PatternMatch.h.
References I.
Referenced by directlyImpliesPoison(), dominatesMergePoint(), foldOverflowingAddSubSelect(), isKnownNonZeroFromOperator(), llvm::patchReplacementInstruction(), and llvm::InstCombinerImpl::visitOr().
m_Xor()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Xor > llvm::PatternMatch::m_Xor (const LHS & L, const RHS & R) inline
Definition at line 1334 of file PatternMatch.h.
References LHS, and RHS.
Referenced by checkForNegativeOperand(), combineAndXorSubWithBMI(), combineXorToBitfieldInsert(), computeKnownBitsFromLerpPattern(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndToUsubsat(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOrXorSubChain(), foldNotXor(), foldOrToXor(), foldSubCtlzNot(), foldXorToXor(), llvm::InstCombiner::getFreelyInvertedImpl(), llvm::ARMTTIImpl::instCombineIntrinsic(), narrowBitOpRMW(), optimizeBranch(), simplifyAddInst(), simplifyAndInst(), simplifyGEPInst(), simplifyOrInst(), simplifyOrLogic(), simplifySubInst(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitOr(), visitORCommutative(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitXor(), and llvm::InstCombinerImpl::visitZExt().
m_Zero()
is_zero llvm::PatternMatch::m_Zero () inline
Match any null constant or a vector with all elements equal to 0.
For vectors, this includes constants with undefined elements.
Definition at line 624 of file PatternMatch.h.
Referenced by areInverseVectorBitmasks(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeForInvariantConditionInjection(), canonicalizeICmpBool(), canonicalizeSaturatedSubtract(), cmpExcludesZero(), combineAdd(), combineOr(), combineTargetShuffle(), computeKnownBitsFromCmp(), llvm::ConstantFoldBinaryInstruction(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), detectSSatUPattern(), llvm::findValuesAffectedByCondition(), FlattenLoopPair(), foldAddSubBoolOfMaskedVal(), foldAndOrOfICmpsWithPow2AndWithZero(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpInvariantGroup(), foldICmpOrChain(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithZero(), foldIdentityExtractShuffle(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldMulHigh(), llvm::InstCombinerImpl::foldOpIntoPhi(), foldOverflowingAddSubSelect(), foldReductionIdiom(), foldSelectBitTest(), foldSelectICmpAndAnd(), foldSelectICmpAndZeroShl(), llvm::InstCombinerImpl::foldSelectOfBools(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectZeroOrFixedOp(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::InstCombinerImpl::foldSignBitTest(), foldUnsignedUnderflowCheck(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), handleOtherCmpSelSimplifications(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::isCheckForZeroAndMulWithOverflow(), isMaskOrZero(), isNeutralValue(), llvm::isOnlyUsedInZeroComparison(), isTruncateOf(), lowerBUILD_VECTOR(), llvm::SDPatternMatch::m_Neg(), markAliveBlocks(), matchOpWithOpEqZero(), matchSubIntegerPackFromVector(), llvm::InstCombinerImpl::OptimizePointerDifference(), optimizeUniformIntrinsic(), performAnyAllCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformSELECTShiftCombine(), replaceConditionalBranchesOnConstant(), simplifyAddInst(), simplifyAndInst(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyDivRem(), llvm::InstCombinerImpl::simplifyDivRemOfSelectWithZeroOp(), simplifyGEPInst(), simplifyICmpInst(), simplifyICmpOfBools(), simplifyICmpWithZero(), simplifyIntrinsic(), simplifyMulInst(), simplifyOrInst(), simplifySelectInst(), simplifySelectWithICmpCond(), simplifyShift(), simplifySubInst(), simplifyUnsignedRangeCheck(), simplifyWithOpsReplaced(), simplifyXorInst(), skipTrivialSelect(), llvm::stripNullTest(), tryToMoveFreeBeforeNullTest(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitPHINode(), and llvm::InstCombinerImpl::visitSelectInst().
m_ZeroInt()
cst_pred_ty< is_zero_int > llvm::PatternMatch::m_ZeroInt () inline
Match an integer 0 or a vector with all elements equal to 0.
For vectors, this includes constants with undefined elements.
Definition at line 611 of file PatternMatch.h.
Referenced by m_Neg(), m_NSWNeg(), llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match(), and simplifyLdexp().
m_ZExt()
template<typename OpTy> CastInst_match< OpTy, ZExtInst > llvm::PatternMatch::m_ZExt (const OpTy & Op) inline
Matches ZExt.
Definition at line 2281 of file PatternMatch.h.
Referenced by canSafelyConvertTo16Bit(), collectBitParts(), combineAdd(), combineBasicSADPattern(), ComputeNumSignBitsImpl(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), decompose(), detectPMADDUBSW(), llvm::InstCombinerImpl::foldAddWithConstant(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), foldLoadsRecursive(), foldLogicCastConstant(), foldNoWrapAdd(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSubCtlzNot(), llvm::vputils::getSCEVExprForVPValue(), llvm::GCNTTIImpl::instCombineIntrinsic(), isLoadCombineCandidateImpl(), m_ZExtOrSelf(), m_ZExtOrSExt(), m_ZExtOrTruncOrSelf(), matchOrConcat(), matchZExtedSubInteger(), narrowInsElt(), narrowUDivURem(), performCTPOPCombine(), shouldSinkVScale(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithBinOp(), simplifyOperationIntoSelectOperand(), splitMergedValStore(), llvm::stripNullTest(), llvm::InstCombinerImpl::takeLog2(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), visitORCommutative(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitTrunc().
m_ZExtOrSelf()
template<typename OpTy> match_combine_or< CastInst_match< OpTy, ZExtInst >, OpTy > llvm::PatternMatch::m_ZExtOrSelf (const OpTy & Op) inline
Definition at line 2292 of file PatternMatch.h.
References m_CombineOr(), and m_ZExt().
Referenced by llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::VPlanTransforms::canonicalizeEVLLoops(), dropRedundantMaskingOfLeftShiftInput(), foldSelectFunnelShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), matchSubIntegerPackFromVector(), performLastTrueTestVectorCombine(), processUse(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombinerImpl::visitAdd(), and llvm::InstCombinerImpl::visitAnd().
m_ZExtOrSExt()
template<typename OpTy> match_combine_or< CastInst_match< OpTy, ZExtInst >, CastInst_match< OpTy, SExtInst > > llvm::PatternMatch::m_ZExtOrSExt (const OpTy & Op) inline
Definition at line 2312 of file PatternMatch.h.
References m_CombineOr(), m_SExt(), and m_ZExt().
Referenced by analyzeCostOfVecReduction(), areExtractExts(), areExtractExts(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), llvm::LoopVectorizationCostModel::getReductionPatternCost(), haveNoCommonBitsSetSpecialCases(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::AArch64TTIImpl::isExtPartOfAvgExpr(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), lookThroughCast(), m_ZExtOrSExtOrSelf(), matchOpWithOpEqZero(), simplifyRecipe(), tryToMatchAndCreateExtendedReduction(), tryToMatchAndCreateMulAccumulateReduction(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSwitchInst().
m_ZExtOrSExtOrSelf()
template<typename OpTy> match_combine_or< match_combine_or< CastInst_match< OpTy, ZExtInst >, CastInst_match< OpTy, SExtInst > >, OpTy > llvm::PatternMatch::m_ZExtOrSExtOrSelf (const OpTy & Op) inline
Definition at line 2320 of file PatternMatch.h.
References m_CombineOr(), and m_ZExtOrSExt().
Referenced by llvm::findHistogram(), and llvm::InstCombinerImpl::visitCallInst().
m_ZExtOrTruncOrSelf()
template<typename OpTy> match_combine_or< match_combine_or< CastInst_match< OpTy, ZExtInst >, CastInst_match< OpTy, TruncInst > >, OpTy > llvm::PatternMatch::m_ZExtOrTruncOrSelf (const OpTy & Op) inline
Definition at line 2328 of file PatternMatch.h.
References m_CombineOr(), m_Trunc(), and m_ZExt().
Referenced by isConditionalOnXorOfPHIs(), and isSignificantBitCheckWellFormed().
match() [1/2]
template<typename Pattern> bool llvm::PatternMatch::match (ArrayRef< int > Mask, const Pattern & P)
Definition at line 66 of file PatternMatch.h.
References P.
match() [2/2]
template<typename Val, typename Pattern> bool llvm::PatternMatch::match (Val * V, const Pattern & P)
Definition at line 49 of file PatternMatch.h.
References P.
Referenced by llvm::AliasSetTracker::add(), addCanonicalIVRecipes(), llvm::VPlanTransforms::addExitUsersForFirstOrderRecurrences(), AddParamAndFnBasicAttributes(), addValueAffectedByCondition(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), analyzeCostOfVecReduction(), analyzeICmp(), annotateNonNullAndDereferenceable(), areBothVScale(), areExtractExts(), areExtractExts(), areExtractShuffleVectors(), areInverseVectorBitmasks(), bitTrackingDCE(), breakSelfRecursivePHI(), llvm::calculateRegisterUsageForPlan(), llvm::canConvertToMinOrMaxIntrinsic(), canEvaluateShifted(), canEvaluateShiftedShift(), llvm::InstCombiner::canFreelyInvertAllUsersOf(), llvm::VPIntrinsic::canIgnoreVectorLengthParam(), canNarrowShiftAmt(), cannotHoistOrSinkRecipe(), canonicalizeAbs(), canonicalizeBitCastExtElt(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), llvm::VPlanTransforms::canonicalizeEVLLoops(), canonicalizeForInvariantConditionInjection(), canonicalizeGEPOfConstGEPI8(), canonicalizeICmpBool(), canonicalizeInsertSplat(), canonicalizeLogicFirst(), canonicalizeLowbitMask(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), canonicalizeSaturatedSubtract(), canonicalizeScalarSelectOfVecs(), canonicalizeSelectToShuffle(), canProveExitOnFirstIteration(), llvm::SCEVExpander::canReuseFlagsFromOriginalIVInc(), canSafelyConvertTo16Bit(), canScalarizeAccess(), canShiftBinOpWithConstantRHS(), llvm::GCNTTIImpl::canSimplifyLegacyMulToMul(), llvm::canSinkOrHoistInst(), cheapToScalarize(), checkForNegativeOperand(), checkOrAndOpImpliedByOther(), checkOuterLoopInsts(), cloneForLane(), cmpExcludesZero(), collectBitParts(), collectComplementaryPredicatedMemOps(), collectDivisibilityInformation(), llvm::collectEphemeralRecipesForVPlan(), collectHomogenousInstGraphLoopInvariants(), llvm::collectPossibleValues(), collectShuffleElements(), collectSingleShuffleElements(), collectUnswitchCandidates(), collectUnswitchCandidatesWithInjections(), combineAddSubWithShlAddSub(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::InstCombinerImpl::commonIDivRemTransforms(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonIRemTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::BaseIndexOffset::computeAliasing(), llvm::ScalarEvolution::computeConstantDifference(), llvm::VPInstruction::computeCost(), computeKnownBits(), computeKnownBitsFromCmp(), computeKnownBitsFromCond(), llvm::computeKnownBitsFromContext(), computeKnownBitsFromICmpCond(), computeKnownBitsFromLerpPattern(), computeKnownBitsFromOperator(), computeKnownFPClass(), computeKnownFPClassFromCond(), ComputeNumSignBitsImpl(), llvm::computeOverflowForSignedSub(), llvm::computeOverflowForUnsignedSub(), computeShapeInfoForInst(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ScalarEvolution::containsUndefs(), convertFSqrtDivIntoFMul(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::VPlanTransforms::convertToConcreteRecipes(), llvm::VPlanTransforms::createInLoopReductionRecipes(), createWidenInductionRecipe(), decompose(), llvm::decomposeBitTest(), llvm::decomposeBitTestICmp(), despeculateCountZeros(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), directlyImpliesPoison(), dominatesMergePoint(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), dropRedundantMaskingOfLeftShiftInput(), evaluateInDifferentElementOrder(), llvm::VPlanTransforms::expandBranchOnTwoConds(), factorizeFAddFSub(), factorizeLerp(), factorizeMathWithShlOps(), findBestNonTrivialUnswitchCandidate(), llvm::findHistogram(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::findScalarElement(), FindSingleBitChange(), llvm::findValuesAffectedByCondition(), fixReductionScalarResumeWhenVectorizingEpilog(), FlattenLoopPair(), foldAbsDiff(), llvm::InstCombinerImpl::foldAddLikeCommutative(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpEqConstantAndICmp(), foldAndOrOfICmpsWithConstEq(), foldAndOrOfICmpsWithPow2AndWithZero(), foldAndToXor(), foldAnyOrAllBitsSet(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), llvm::InstCombinerImpl::foldBinOpSelectBinOp(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), foldBitCastBitwiseLogic(), foldBitCastSelect(), foldBitCeil(), foldBitOrderCrossLogicOp(), foldBitwiseLogicWithIntrinsics(), foldBoxMultiply(), foldClampRangeOfTwo(), foldComplexAndOrPatterns(), foldConstantInsEltIntoShuffle(), foldCopySignIdioms(), foldCtpop(), foldCttzCtlz(), foldDependentIVs(), foldFabsWithFcmpZero(), foldFCmpFNegCommonOp(), foldFCmpFpTrunc(), foldFCmpFSubIntoFCmp(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), foldFCmpReciprocalAndZero(), foldFCmpWithFloorAndCeil(), foldFDivConstantDividend(), foldFDivSqrtDivisor(), llvm::InstCombinerImpl::foldFMulReassoc(), foldFNegIntoConstant(), foldFrexpOfSelect(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpAndShift(), foldICmpAndXX(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpCommutative(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEqIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpEqualityWithOffset(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), foldICmpIntrinsicWithIntrinsic(), foldICmpInvariantGroup(), llvm::InstCombinerImpl::foldICmpMulConstant(), foldICmpOfUAddOv(), foldICmpOrChain(), llvm::InstCombinerImpl::foldICmpOrConstant(), foldICmpOrXorSubChain(), foldICmpOrXX(), foldICmpPow2Test(), llvm::InstCombinerImpl::foldICmpShlConstant(), foldICmpShlLHSC(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldICmpUSubSatOrUAddSatWithConstant(), foldICmpUSubSatWithAndForMostSignificantBitCmp(), llvm::InstCombinerImpl::foldICmpWithClamp(), llvm::InstCombinerImpl::foldICmpWithConstant(), foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), llvm::InstCombinerImpl::foldICmpXorConstant(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldICmpXorXX(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIDivShl(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), foldInsSequenceIntoSplat(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), llvm::InstCombinerImpl::foldIsMultipleOfAPowerOfTwo(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), foldLoadsRecursive(), foldLogicCastConstant(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldMinimumOverTrailingOrLeadingZeroCount(), foldMinMaxSharedOp(), foldMulHigh(), foldMulSelectToNegate(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldNegativePower2AndShiftedMask(), foldNestedSelects(), foldNotXor(), foldNoWrapAdd(), llvm::InstCombinerImpl::foldOpIntoPhi(), foldOrOfInversions(), FoldOrOfSelectSmaxToAbs(), foldOrToXor(), foldOrUnsignedUMulOverflowICmp(), foldOverflowingAddSubSelect(), llvm::InstCombinerImpl::foldPowiReassoc(), llvm::InstCombinerImpl::foldPtrToIntOrAddrOfGEP(), foldReductionIdiom(), llvm::InstCombinerImpl::foldReversedIntrinsicOperands(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBinOpIdentity(), foldSelectBitTest(), foldSelectCmpBitcasts(), llvm::InstCombinerImpl::foldSelectExtConst(), foldSelectFunnelShift(), foldSelectGEP(), llvm::InstCombinerImpl::foldSelectICmp(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndBinOp(), foldSelectICmpAndZeroShl(), foldSelectICmpLshrAshr(), foldSelectICmpMinMax(), llvm::InstCombinerImpl::foldSelectInstWithICmp(), foldSelectIntoAddConstant(), llvm::InstCombinerImpl::foldSelectIntoOp(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectOfSymmetricSelect(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::foldSelectToCmp(), foldSelectToCopysign(), foldSelectToPhiImpl(), llvm::InstCombinerImpl::foldSelectValueEquivalence(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), foldSelectWithExtremeEqCond(), foldSelectWithFCmpToFabs(), foldSelectWithSRem(), foldSelectZeroOrFixedOp(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), llvm::InstCombinerImpl::foldShuffledIntrinsicOperands(), foldShuffleOfUnaryOps(), foldShuffleWithInsert(), llvm::InstCombinerImpl::foldSignBitTest(), foldSignedTruncationCheck(), foldSqrtWithFcmpZero(), foldSubOfMinMax(), foldToUnsignedSaturatedAdd(), foldTruncInsEltPair(), foldTruncShuffle(), foldTwoEntryPHINode(), foldUnsignedUnderflowCheck(), foldURemOfLoopIncrement(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), foldVecExtTruncToExtElt(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::InstCombinerImpl::foldVectorSelect(), foldVecTruncToExtElt(), foldXorToXor(), llvm::VPTransformState::get(), llvm::ScalarEvolution::getAddExpr(), getAlternateBinop(), getAppleRuntimeUnrollPreferences(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::GCNTTIImpl::getArithmeticInstrCost(), getBinOpsForFactorization(), getBoolVecFromMask(), getBundleFromUse(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::InstCombiner::getComplexity(), llvm::PredicateBase::getConstraint(), getDemandedBitsLHSMask(), getDomPredecessorCondition(), llvm::ConstantExpr::getExactLogBase2(), llvm::InstCombiner::getFreelyInvertedImpl(), getFSqrtDivOptPattern(), llvm::ARMTTIImpl::getGatherScatterOpCost(), getHashValueImpl(), llvm::TargetTransformInfoImplCRTPBase< T >::getInstructionCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), getInvertibleOperands(), llvm::SystemZTargetLowering::getJumpConditionMergingParams(), llvm::X86TargetLowering::getJumpConditionMergingParams(), getKnownBitsFromAndXorOr(), getKnownSign(), getKnownSignOrZero(), getKnownTypeFromMaskedOp(), getMaskedICmpType(), getMaskedTypeForICmpPair(), llvm::ScalarEvolution::getMulExpr(), getNegatibleInsts(), getNextSCEVDivisibleByDivisor(), getNotValue(), getOptimizableIVOf(), llvm::AMDGPUTargetMachine::getPredicatedAddrSpace(), getPreviousSCEVDivisibleByDivisor(), getRangeForIntrinsic(), getRangeForSelectPattern(), llvm::LoopVectorizationCostModel::getReductionPatternCost(), slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::X86TTIImpl::getShuffleCost(), llvm::getSplatValue(), getStartValueFromReductionResult(), getStrideFromAddRec(), getStrideFromPointer(), llvm::ScalarEvolution::getUDivExpr(), getUnsignedMonotonicValues(), getValueFromOverflowCondition(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::VPlanTransforms::handleMaxMinNumReductions(), llvm::VPlanTransforms::handleMultiUseReductions(), handleOtherCmpSelSimplifications(), llvm::VPlanTransforms::handleUncountableEarlyExit(), hasConditionalTerminator(), hasNonZeroFPOperands(), llvm::SCEVExpander::hasRelatedExistingExpansion(), haveNoCommonBitsSetSpecialCases(), hoistAdd(), hoistAddSub(), hoistInsEltConst(), hoistMinMax(), llvm::hoistRegion(), hoistSub(), impliesPoisonOrCond(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), instCombineLD1GatherIndex(), instCombinePTrue(), instCombineST1ScatterIndex(), instCombineSVEDup(), instCombineSVEDupqLane(), instCombineSVELast(), instCombineSVESrshl(), instCombineSVEUzp1(), instCombineSVEVectorFuseMulAddSub(), instCombineSVEZip(), llvm::VPlanTransforms::introduceMasksAndLinearize(), llvm::invertCondition(), isAllActivePredicate(), isAllocSiteRemovable(), llvm::SCEV::isAllOnesValue(), isAMXCast(), llvm::RecurrenceDescriptor::isAnyOfPattern(), isBigEndianBitShift(), llvm::isCheckForZeroAndMulWithOverflow(), isConditionalOnXorOfPHIs(), llvm::RecurrenceDescriptor::isConditionalRdxPattern(), isConditionTrueViaVFAndUF(), isDeadRecipe(), isDivisibilityGuard(), isDivZero(), llvm::Constant::isElementWiseEqual(), isEqualImpl(), llvm::AArch64TTIImpl::isExtPartOfAvgExpr(), llvm::RecurrenceDescriptor::isFindIVPattern(), isFNeg(), llvm::isGuard(), llvm::isGuardAsWidenableBranch(), isImpliedCondAndOr(), isImpliedCondFCmps(), isImpliedCondICmps(), llvm::isImpliedCondition(), llvm::isImpliedCondition(), isImpliedToBeAPowerOfTwoFromCond(), llvm::InductionDescriptor::isInductionPHI(), isInstructionPairMul(), llvm::ConstantPtrAuth::isKnownCompatibleWith(), isKnownExactCastIntToFP(), llvm::isKnownInversion(), llvm::isKnownNegation(), isKnownNonEqual(), isKnownNonNullFromDominatingCondition(), isKnownNonZeroFromAssume(), isKnownNonZeroFromOperator(), isKnownPredicateExtendIdiom(), IsKnownPredicateViaAddRecStart(), llvm::isKnownToBeAPowerOfTwo(), slpvectorizer::BoUpSLP::isLoadCombineCandidate(), isLoadCombineCandidateImpl(), isLoopNeverExecuted(), isMaskOrZero(), isMinMaxCmpSelectEliminable(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxReductionPhiWithUsersOutsideReductionChain(), isMultipleOfN(), isNeg(), isNeutralValue(), isNonEqualMul(), isNonEqualPHIs(), isNonEqualShl(), isNonZeroRecurrence(), llvm::SCEV::isOne(), isOperandOfVmullHighP64(), isPoisonShift(), isPowerOfTwoRecurrence(), isProcessableCondBI(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), llvm::ARMTTIImpl::isProfitableToSinkOperands(), llvm::GCNTTIImpl::isProfitableToSinkOperands(), llvm::RISCVTTIImpl::isProfitableToSinkOperands(), llvm::WebAssemblyTTIImpl::isProfitableToSinkOperands(), llvm::X86TTIImpl::isProfitableToSinkOperands(), isPTruePromoted(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), isReductionCandidate(), isRemOfLoopIncrementWithLoopInvariant(), isSafeToRemoveBitCeilSelect(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), isSignedMinMaxClamp(), isSignedMinMaxIntrinsicClamp(), isSimpleCastedPHI(), llvm::MemoryWriteTracking::isSpecialInstruction(), llvm::isSplatValue(), isSSATMinMaxPattern(), isSupportedMemset(), isTruePredicate(), llvm::SimplifyQuery::isUndefValue(), isUsedWithinShuffleVector(), llvm::isWidenableCondition(), llvm::SCEV::isZero(), likeBitCastFromVector(), LinearizeExprTree(), lookThroughAnd(), lookThroughCast(), lookThroughCastConst(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), maintainNoSignedWrap(), markAliveBlocks(), llvm::PatternMatch::XorLike_match< LHS, RHS >::match(), matchAndOrChain(), MatchBinarySub(), matchBitmaskMul(), matchClamp(), matchDeMorgansLaws(), MatchDiv(), matchesAdd(), matchesOr(), matchesSquareSum(), matchExpandedRem(), matchFastFloatClamp(), matchFMulByZeroIfResultEqZero(), matchFPExtFromF16(), matchICmpOperand(), matchIncrement(), matchIntPart(), matchIsNotNaN(), matchMinMax(), matchMinMaxOfMinMax(), MatchMul(), MatchNotExpr(), matchOpWithOpEqZero(), matchOrConcat(), matchPartStore(), matchRdxBop(), MatchRem(), matchSelectPattern(), matchSelectWithOptionalNotCond(), matchStridedStart(), matchSubIntegerPackFromVector(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), matchUAddWithOverflowConstantEdgeCases(), matchUnorderedInfCompare(), matchZExtedSubInteger(), mayLoopAccessLocation(), llvm::Constant::mergeUndefsWith(), moveAddAfterMinMax(), narrowInsElt(), narrowUDivURem(), narrowVectorSelect(), NegateValue(), OptimizeAndOrXor(), optimizeBranch(), optimizeEarlyExitInductionUser(), optimizeLatchExitInductionUser(), optimizeMaskToEVL(), llvm::InstCombinerImpl::OptimizePointerDifference(), optimizeShiftInOrChain(), optimizeSymmetricCall(), optimizeUniformIntrinsic(), optimizeVectorInductionWidthForTCAndVFUF(), parseCondition(), llvm::parseWidenableBranch(), passingValueIsAlwaysUndefined(), llvm::patchReplacementInstruction(), preparePlanForEpilogueVectorLoop(), processAnd(), llvm::LoopVectorizePass::processLoop(), processUse(), reassociateFCmps(), reassociateForUses(), reassociateMinMaxWithConstantInOperand(), reassociateMinMaxWithConstants(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::recognizeBSwapOrBitReverseIdiom(), recordCondition(), llvm::AssumptionCache::registerAssumption(), llvm::VPlanTransforms::removeBranchOnConst(), removeCommonBlendMask(), replaceConditionalBranchesOnConstant(), replaceSubOverflowUses(), llvm::VPlanTransforms::replaceSymbolicStrides(), llvm::Constant::replaceUndefsWith(), llvm::DropUnnecessaryAssumesPass::run(), setLimitsForBinOp(), setShiftFlags(), llvm::InstCombiner::shouldAvoidAbsorbingNotIntoSelect(), ShouldBreakUpSubtract(), shouldCanonicalizeGEPToPtrAdd(), shouldExpandCmpArithRMWInIR(), shouldSinkVScale(), llvm::TargetTransformInfoImplBase::shouldTreatInstructionLikeSelect(), ShrinkDemandedConstant(), shrinkInsertElt(), shrinkSplatShuffle(), simplifyAddInst(), llvm::InstCombinerImpl::SimplifyAddWithRemainder(), simplifyAndCommutative(), simplifyAndInst(), simplifyAndOfICmpsWithAdd(), simplifyAndOrOfFCmps(), simplifyAndOrOfFCmpsWithConstants(), simplifyAndOrOfICmpsWithConstants(), simplifyAndOrOfICmpsWithCtpop(), simplifyAndOrWithICmpEq(), simplifyAShrInst(), simplifyAssocCastAssoc(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), llvm::simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::simplifyBinOpSplats(), simplifyBlends(), simplifyBranchConditionForVFAndUF(), simplifyCastInst(), simplifyCmpSelOfMaxMin(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyDiv(), simplifyDivRem(), llvm::InstCombinerImpl::simplifyDivRemOfSelectWithZeroOp(), simplifyExtractValueInst(), simplifyFAddInst(), simplifyFCmpInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFNegInst(), simplifyFPOp(), simplifyFRemInst(), simplifyFSubInst(), simplifyGEPInst(), simplifyICmpInst(), simplifyICmpOfBools(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithConstant(), simplifyICmpWithIntrinsicOnLHS(), simplifyICmpWithMinMax(), simplifyICmpWithZero(), llvm::simplifyInsertElementInst(), llvm::simplifyInstruction(), simplifyInstructionWithPHI(), simplifyIntrinsic(), simplifyIRemMulShl(), simplifyKnownEVL(), simplifyLdexp(), simplifyLogicOfAddSub(), llvm::simplifyLoopAfterUnroll(), simplifyLShrInst(), simplifyMulInst(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyOperationIntoSelectOperand(), simplifyOrInst(), simplifyOrLogic(), simplifyOrOfICmpsWithAdd(), llvm::InstCombinerImpl::simplifyRangeCheck(), simplifyRecipe(), simplifyReductionOperand(), simplifyRem(), simplifySelectBitTest(), simplifySelectInst(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifySelectWithFCmp(), simplifySelectWithICmpCond(), simplifyShift(), simplifyShiftSelectingPackedElement(), simplifyShlInst(), simplifyShuffleVectorInst(), simplifySRemInst(), simplifySubInst(), simplifySVEIntrinsic(), simplifySwitchOnSelectUsingRanges(), simplifySwitchWhenUMin(), simplifyTernarylogic(), simplifyUnaryIntrinsic(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), simplifyWithOpsReplaced(), simplifyX86addcarry(), simplifyX86pmulh(), simplifyXorInst(), llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp(), skipTrivialSelect(), splitMergedValStore(), llvm::stripNullTest(), stripSignOnlyFPOps(), swapICmpOperandsToExposeCSEOpportunities(), llvm::InstCombinerImpl::takeLog2(), transformRecipestoEVLRecipes(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), tryFactorization(), llvm::InstCombinerImpl::tryFoldInstWithCtpopWithNot(), trySimplifyICmpWithAdds(), tryToFPToSat(), tryToImproveAlign(), tryToMatchAndCreateExtendedReduction(), tryToMatchAndCreateMulAccumulateReduction(), tryToMoveFreeBeforeNullTest(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), tryToReplaceALMWithWideALM(), llvm::JumpThreadingPass::tryToUnfoldSelectInCurrBB(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::AssumptionCacheTracker::verifyAnalysis(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitExtractValueInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::InstCombinerImpl::visitIntToPtr(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitPHINode(), llvm::InstCombinerImpl::visitPtrToAddr(), llvm::InstCombinerImpl::visitPtrToInt(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), and llvm::reassociate::XorOpnd::XorOpnd().
match_fn()
template<typename Val = const Value, typename Pattern> MatchFunctor< Val, Pattern > llvm::PatternMatch::match_fn (const Pattern & P)
A match functor that can be used as a UnaryPredicate in functional algorithms like all_of.
Definition at line 62 of file PatternMatch.h.
References P.
Referenced by findUserOf(), foldNestedSelects(), llvm::InstCombinerImpl::foldShuffledIntrinsicOperands(), llvm::isOnlyUsedInZeroComparison(), planContainsAdditionalSimplifications(), simplifyGEPInst(), simplifyRecipe(), and llvm::InstCombinerImpl::visitSub().