LLVM: llvm::dwarf_linker Namespace Reference
llvm::dwarf_linker Namespace Reference
Namespaces
namespace classic
namespace parallel
Classes
class AddressesMap
AddressesMap represents information about valid addresses used by debug information.
class DWARFFile
This class represents DWARF information for source file and it's address map.
class DWARFLinkerBase
The base interface for DWARFLinker implementations.
class IndexedValuesMap
This class stores values sequentually and assigns index to the each value.
class StringPoolEntryInfo
class StringPool
Typedefs
using RangesTy = AddressRangesMap
Mapped value in the address map is the offset to apply to the linked address.
using StringEntry = StringMapEntry<EmptyStringSetTag>
StringEntry keeps data of the string: the length, external offset and a string body which is placed right after StringEntry.
Enumerations
enum class DebugSectionKind : uint8_t {
DebugInfo = 0 , DebugLine , DebugFrame , DebugRange ,
DebugRngLists , DebugLoc , DebugLocLists , DebugARanges ,
DebugAbbrev , DebugMacinfo , DebugMacro , DebugAddr ,
DebugStr , DebugLineStr , DebugStrOffsets , DebugPubNames ,
DebugPubTypes , DebugNames , AppleNames , AppleNamespaces ,
AppleObjC , AppleTypes , NumberOfEnumEntries
}
List of tracked debug tables.
Functions
static constexpr const StringLiteral & getSectionName (DebugSectionKind SectionKind)
Return the name of the section.
LLVM_ABI std::optional< DebugSectionKind > parseDebugTableName (StringRef Name)
Recognise the table name and match it with the DebugSectionKind.
Error finiteLoop (function_ref< Expected< bool >()> Iteration, size_t MaxCounter=100000)
This function calls Iteration() until it returns false.
StringRef guessDeveloperDir (StringRef SysRoot)
Make a best effort to guess the Xcode.app/Contents/Developer path from an SDK path.
bool isInToolchainDir (StringRef Path)
Make a best effort to determine whether Path is inside a toolchain.
bool isPathAbsoluteOnWindowsOrPosix (const Twine &Path)
Variables
static constexpr size_t SectionKindsNum
static constexpr StringLiteral SectionNames [SectionKindsNum]
Typedef Documentation
RangesTy
using llvm::dwarf_linker::RangesTy = AddressRangesMap
Mapped value in the address map is the offset to apply to the linked address.
Definition at line 24 of file AddressesMap.h.
StringEntry
using llvm::dwarf_linker::StringEntry = StringMapEntry<EmptyStringSetTag>
StringEntry keeps data of the string: the length, external offset and a string body which is placed right after StringEntry.
Definition at line 23 of file StringPool.h.
Enumeration Type Documentation
DebugSectionKind
enum class llvm::dwarf_linker::DebugSectionKind : uint8_t strong
List of tracked debug tables.
Enumerator
DebugInfo
DebugLine
DebugFrame
DebugRange
DebugRngLists
DebugLoc
DebugLocLists
DebugARanges
DebugAbbrev
DebugMacinfo
DebugMacro
DebugAddr
DebugStr
DebugLineStr
DebugStrOffsets
DebugPubNames
DebugPubTypes
DebugNames
AppleNames
AppleNamespaces
AppleObjC
AppleTypes
NumberOfEnumEntries
Definition at line 28 of file DWARFLinkerBase.h.
Function Documentation
finiteLoop()
Error llvm::dwarf_linker::finiteLoop (function_ref< Expected< bool >()> Iteration, size_t MaxCounter = 100000) inline
This function calls Iteration() until it returns false.
If number of iterations exceeds MaxCounter then an Error is returned. This function should be used for loops which assumed to have number of iterations significantly smaller than MaxCounter to avoid infinite looping in error cases.
Definition at line 26 of file Utils.h.
References llvm::createStringError(), llvm::Expected< T >::get(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by hashFullyQualifiedName(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::link(), and llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::linkSingleCompileUnit().
getSectionName()
constexpr const StringLiteral & llvm::dwarf_linker::getSectionName (DebugSectionKind SectionKind) static constexpr
Return the name of the section.
Definition at line 67 of file DWARFLinkerBase.h.
References SectionNames.
Referenced by llvm::dwarf_linker::parallel::SectionDescriptorBase::getName(), llvm::dwarf_linker::parallel::OutputSections::getSectionDescriptor(), llvm::dwarf_linker::parallel::OutputSections::getSectionDescriptor(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ELFObjectFile< ELFT >::isDebugSection(), and parseDebugTableName().
guessDeveloperDir()
StringRef llvm::dwarf_linker::guessDeveloperDir (StringRef SysRoot) inline
Make a best effort to guess the Xcode.app/Contents/Developer path from an SDK path.
Definition at line 41 of file Utils.h.
References llvm::StringRef::data(), llvm::end(), llvm::sys::path::rbegin(), and llvm::sys::path::rend().
Referenced by llvm::analyzeImportedModule(), and llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule().
isInToolchainDir()
bool llvm::dwarf_linker::isInToolchainDir (StringRef Path) inline
Make a best effort to determine whether Path is inside a toolchain.
Definition at line 77 of file Utils.h.
References llvm::end(), llvm::sys::path::rbegin(), and llvm::sys::path::rend().
Referenced by llvm::analyzeImportedModule(), and llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule().
isPathAbsoluteOnWindowsOrPosix()
bool llvm::dwarf_linker::isPathAbsoluteOnWindowsOrPosix (const Twine & Path) inline
Definition at line 98 of file Utils.h.
References llvm::sys::path::is_absolute(), llvm::sys::path::posix, and llvm::sys::path::windows.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::getDirAndFilenameFromLineTable(), and llvm::DWARFDebugLine::Prologue::getFileNameByIndex().
parseDebugTableName()
std::optional< DebugSectionKind > llvm::dwarf_linker::parseDebugTableName (llvm::StringRef SecName)
Recognise the table name and match it with the DebugSectionKind.
Definition at line 16 of file DWARFLinkerBase.cpp.
References AppleNames, AppleNamespaces, AppleObjC, AppleTypes, llvm::StringSwitch< T, R >::Case(), DebugAbbrev, DebugAddr, DebugARanges, DebugFrame, DebugInfo, DebugLine, DebugLineStr, DebugLoc, DebugLocLists, DebugMacinfo, DebugMacro, DebugNames, DebugPubNames, DebugPubTypes, DebugRange, DebugRngLists, DebugStr, DebugStrOffsets, llvm::StringSwitch< T, R >::Default(), llvm::StringRef::find_first_not_of(), getSectionName(), and llvm::StringRef::substr().
Referenced by llvm::dwarf_linker::parallel::SectionDescriptor::setSizesForSectionCreatedByAsmPrinter().
Variable Documentation
SectionKindsNum
size_t llvm::dwarf_linker::SectionKindsNum static constexpr
Initial value:
                                    =
static_cast<size_t>(DebugSectionKind::NumberOfEnumEntries)
Definition at line 54 of file DWARFLinkerBase.h.
SectionNames
StringLiteral llvm::dwarf_linker::SectionNames[SectionKindsNum] static constexpr
Initial value:
                                        = {
"debug_info",     "debug_line",     "debug_frame",       "debug_ranges",
"debug_rnglists", "debug_loc",      "debug_loclists",    "debug_aranges",
"debug_abbrev",   "debug_macinfo",  "debug_macro",       "debug_addr",
"debug_str",      "debug_line_str", "debug_str_offsets", "debug_pubnames",
"debug_pubtypes", "debug_names",    "apple_names",       "apple_namespac",
"apple_objc",     "apple_types"}
Definition at line 57 of file DWARFLinkerBase.h.
Referenced by llvm::DWARFFormValue::dumpAddressSection(), and getSectionName().