LLVM: KernelInfo Namespace Reference
KernelInfo Namespace Reference
Functions
GlobalVariable * getKernelEnvironementGVFromKernelInitCB (CallBase *KernelInitCB)
ConstantStruct * getKernelEnvironementFromKernelInitCB (CallBase *KernelInitCB)
Function Documentation
getKernelEnvironementFromKernelInitCB()
ConstantStruct * KernelInfo::getKernelEnvironementFromKernelInitCB (CallBase * KernelInitCB)
Definition at line 267 of file OpenMPOpt.cpp.
References llvm::cast(), llvm::GlobalVariable::getInitializer(), and getKernelEnvironementGVFromKernelInitCB().
getKernelEnvironementGVFromKernelInitCB()
GlobalVariable * KernelInfo::getKernelEnvironementGVFromKernelInitCB (CallBase * KernelInitCB)
Definition at line 260 of file OpenMPOpt.cpp.
References llvm::cast(), llvm::CallBase::getArgOperand(), and llvm::Value::stripPointerCasts().
Referenced by getKernelEnvironementFromKernelInitCB().