LLVM: llvm::memprof Namespace Reference
llvm::memprof Namespace Reference
Namespaces
namespace internal
namespace detail
Classes
class CallStackTrie
Class to build a trie of call stack contexts for a particular profiled allocation call, along with their associated allocation types.
class CallStack
Helper class to iterate through stack ids in both metadata (memprof MIB and callsite) and the corresponding ThinLTO summary data structures (CallsiteInfo and MIBInfo).
struct SourceLocation
The location of data in the source code. Used by profile lookup API.
struct DataAccessProfRecord
The data access profiles for a symbol.
class DataAccessProfData
Encapsulates the data access profile data and the methods to operate on it.
struct IndexedMemProfData
struct PortableMemInfoBlock
struct Frame
struct IndexedCallSiteInfo
struct IndexedAllocationInfo
struct AllocationInfo
struct IndexedMemProfRecord
struct CallSiteInfo
struct MemProfRecord
class RecordLookupTrait
class RecordWriterTrait
class FrameWriterTrait
class FrameLookupTrait
class CallStackWriterTrait
class CallStackLookupTrait
struct LineLocation
struct FrameIdConverter
struct CallStackIdConverter
struct LinearFrameIdConverter
struct LinearCallStackIdConverter
struct CallerCalleePairExtractor
struct IndexedCallstackIdConverter
struct FrameStat
class CallStackRadixTreeBuilder
class MemProfReader
class RawMemProfReader
class YAMLMemProfReader
class MemProfSummary
class MemProfSummaryBuilder
struct GUIDMemProfRecordPair
struct YamlDataAccessProfData
struct AllMemProfData
struct LineLocationHash
Typedefs
using ContextSizeTypePair = std::pair<ContextTotalSize, AllocationType>
using SymbolHandleRef = std::variant<StringRef, uint64_t>
using SymbolHandle = std::variant<std::string, uint64_t>
using MemProfSchema = llvm::SmallVector<Meta, static_cast<int>(Meta::Size)>
using FrameId = uint64_t
using LinearFrameId = uint32_t
using CallStackId = uint64_t
using LinearCallStackId = uint32_t
using CallEdgeTy = std::pair<LineLocation, uint64_t>
using CallStackMap = llvm::DenseMap<uint64_t, llvm::SmallVector<uint64_t>>
using LocToLocMap
Enumerations
enum class AnnotationKind : uint8_t { AnnotationOK , DeclForLinker , ExplicitSection , ReservedName }
enum IndexedVersion : uint64_t { Version2 = 2 , Version3 = 3 , Version4 = 4 }
enum class Meta : uint64_t { Start = 0 , MIBEntryDef }
Functions
LLVM_ABI bool metadataIncludesAllContextSizeInfo ()
Whether the alloc memeprof metadata will include context size info for all MIBs.
LLVM_ABI bool metadataMayIncludeContextSizeInfo ()
Whether the alloc memprof metadata may include context size info for some MIBs (but possibly not all).
LLVM_ABI bool recordContextSizeInfoForAnalysis ()
Whether we need to record the context size info in the alloc trie used to build metadata.
LLVM_ABI MDNode * buildCallstackMetadata (ArrayRef< uint64_t > CallStack, LLVMContext &Ctx)
Build callstack metadata from the provided list of call stack ids.
LLVM_ABI MDNode * getMIBStackNode (const MDNode *MIB)
Returns the stack node from an MIB metadata node.
LLVM_ABI AllocationType getMIBAllocType (const MDNode *MIB)
Returns the allocation type from an MIB metadata node.
LLVM_ABI std::string getAllocTypeAttributeString (AllocationType Type)
Returns the string to use in attributes with the given type.
LLVM_ABI bool hasSingleAllocType (uint8_t AllocTypes)
True if the AllocTypes bitmask contains just a single type.
LLVM_ABI void removeAnyExistingAmbiguousAttribute (CallBase *CB)
Removes any existing "ambiguous" memprof attribute.
LLVM_ABI void addAmbiguousAttribute (CallBase *CB)
Adds an "ambiguous" memprof attribute to call with a matched allocation profile but that we haven't yet been able to disambiguate.
AnnotationKind getAnnotationKind (const GlobalVariable &GV)
Returns the annotation kind of the global variable GV.
bool IsAnnotationOK (const GlobalVariable &GV)
Returns true if the annotation kind of the global variable GV is AnnotationOK.
llvm::StringRef getMemprofOptionsSymbolDarwinLinkageName ()
llvm::StringRef getMemprofOptionsSymbolName ()
LLVM_ABI MemProfSchema getFullSchema ()
LLVM_ABI MemProfSchema getHotColdSchema ()
LLVM_ABI GlobalValue::GUID getGUID (const StringRef FunctionName)
LLVM_ABI Expected< MemProfSchema > readMemProfSchema (const unsigned char *&Buffer)
LLVM_ABI AllocationType getAllocType (uint64_t TotalLifetimeAccessDensity, uint64_t AllocCount, uint64_t TotalLifetime)
Return the allocation type for a given set of memory profile values.
LLVM_ABI uint64_t computeFullStackId (ArrayRef< Frame > CallStack)
Helper to generate a single hash id for a given callstack, used for emitting matching statistics and useful for uniquing such statistics across modules.
template<typename FrameIdTy>
llvm::DenseMap< FrameIdTy, FrameStat > computeFrameHistogram (llvm::MapVector< CallStackId, llvm::SmallVector< FrameIdTy > > &MemProfCallStackData)
LLVM_ABI DenseMap< uint64_t, SmallVector< CallEdgeTy, 0 > > extractCallsFromIR (Module &M, const TargetLibraryInfo &TLI, function_ref< bool(uint64_t)> IsPresentInProfile=[](uint64_t) { return true;})
LLVM_ABI DenseMap< uint64_t, LocToLocMap > computeUndriftMap (Module &M, IndexedInstrProfReader *MemProfReader, const TargetLibraryInfo &TLI)
static bool hasExplicitSectionName (const GlobalVariable &GVar)
static std::pair< StringRef, uint64_t > saveStringToMap (DataAccessProfData::StringToIndexMap &Map, llvm::UniqueStringSaver &Saver, StringRef Str)
static Expected< StringRef > getCanonicalName (StringRef Name)
static size_t serializedSizeV2 (const IndexedAllocationInfo &IAI, const MemProfSchema &Schema)
static size_t serializedSizeV3 (const IndexedAllocationInfo &IAI, const MemProfSchema &Schema)
static size_t serializedSizeV2 (const IndexedMemProfRecord &Record, const MemProfSchema &Schema)
static size_t serializedSizeV3 (const IndexedMemProfRecord &Record, const MemProfSchema &Schema)
static size_t serializedSizeV4 (const IndexedMemProfRecord &Record, const MemProfSchema &Schema)
static void serializeV2 (const IndexedMemProfRecord &Record, const MemProfSchema &Schema, raw_ostream &OS)
static void serializeV3 (const IndexedMemProfRecord &Record, const MemProfSchema &Schema, raw_ostream &OS, llvm::DenseMap< CallStackId, LinearCallStackId > &MemProfCallStackIndexes)
static void serializeV4 (const IndexedMemProfRecord &Record, const MemProfSchema &Schema, raw_ostream &OS, llvm::DenseMap< CallStackId, LinearCallStackId > &MemProfCallStackIndexes)
static IndexedMemProfRecord deserializeV2 (const MemProfSchema &Schema, const unsigned char *Ptr)
static IndexedMemProfRecord deserializeV3 (const MemProfSchema &Schema, const unsigned char *Ptr)
static IndexedMemProfRecord deserializeV4 (const MemProfSchema &Schema, const unsigned char *Ptr)
template LLVM_ABI llvm::DenseMap< FrameId, FrameStat > computeFrameHistogram< FrameId > (llvm::MapVector< CallStackId, llvm::SmallVector< FrameId > > &MemProfCallStackData)
template LLVM_ABI llvm::DenseMap< LinearFrameId, FrameStat > computeFrameHistogram< LinearFrameId > (llvm::MapVector< CallStackId, llvm::SmallVector< LinearFrameId > > &MemProfCallStackData)
Variables
constexpr uint64_t MinimumSupportedVersion = Version2
constexpr uint64_t MaximumSupportedVersion = Version4
template class LLVM_TEMPLATE_ABI CallStackRadixTreeBuilder< FrameId >
template class LLVM_TEMPLATE_ABI CallStackRadixTreeBuilder< LinearFrameId >
Typedef Documentation
CallEdgeTy
using llvm::memprof::CallEdgeTy = std::pair<LineLocation, uint64_t>
Definition at line 854 of file MemProf.h.
CallStackId
using llvm::memprof::CallStackId = uint64_t
Definition at line 352 of file MemProf.h.
CallStackMap
using llvm::memprof::CallStackMap = llvm::DenseMap<uint64_t, llvm::SmallVector<uint64_t>>
Definition at line 105 of file MemProfReader.h.
ContextSizeTypePair
using llvm::memprof::ContextSizeTypePair = std::pair<ContextTotalSize, AllocationType>
Definition at line 71 of file MemoryProfileInfo.h.
FrameId
using llvm::memprof::FrameId = uint64_t
Definition at line 236 of file MemProf.h.
LinearCallStackId
using llvm::memprof::LinearCallStackId = uint32_t
Definition at line 355 of file MemProf.h.
LinearFrameId
using llvm::memprof::LinearFrameId = uint32_t
Definition at line 238 of file MemProf.h.
LocToLocMap
using llvm::memprof::LocToLocMap
Initial value:
std::unordered_map<LineLocation, LineLocation, LineLocationHash>
Definition at line 65 of file MemProfUse.h.
MemProfSchema
using llvm::memprof::MemProfSchema = llvm::SmallVector<Meta, static_cast<int>(Meta::Size)>
Definition at line 76 of file MemProf.h.
SymbolHandle
using llvm::memprof::SymbolHandle = std::variant<std::string, uint64_t>
Definition at line 102 of file DataAccessProf.h.
SymbolHandleRef
using llvm::memprof::SymbolHandleRef = std::variant<StringRef, uint64_t>
Definition at line 99 of file DataAccessProf.h.
Enumeration Type Documentation
AnnotationKind
enum class llvm::memprof::AnnotationKind : uint8_t strong
Enumerator
AnnotationOK
DeclForLinker
ExplicitSection
ReservedName
Definition at line 17 of file StaticDataProfileInfo.h.
IndexedVersion
enum llvm::memprof::IndexedVersion : uint64_t
Enumerator
Version2
Version3
Version4
Definition at line 42 of file MemProf.h.
Meta
enum class llvm::memprof::Meta : uint64_t strong
Enumerator
Start
MIBEntryDef
Definition at line 68 of file MemProf.h.
Function Documentation
addAmbiguousAttribute()
void llvm::memprof::addAmbiguousAttribute (CallBase * CB)
Adds an "ambiguous" memprof attribute to call with a matched allocation profile but that we haven't yet been able to disambiguate.
Definition at line 139 of file MemoryProfileInfo.cpp.
References A(), llvm::CallBase::addFnAttr(), assert(), llvm::Attribute::get(), llvm::Value::getContext(), llvm::CallBase::getFnAttr(), llvm::Attribute::getValueAsString(), llvm::CallBase::hasFnAttr(), and llvm::MemProfUseAmbiguousAttributes().
Referenced by llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata().
buildCallstackMetadata()
MDNode * llvm::memprof::buildCallstackMetadata (ArrayRef< uint64_t > CallStack, LLVMContext & Ctx)
Build callstack metadata from the provided list of call stack ids.
Returns the resulting metadata node.
Definition at line 76 of file MemoryProfileInfo.cpp.
References llvm::MDNode::get(), llvm::ValueAsMetadata::get(), llvm::Type::getInt64Ty(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
Referenced by addCallsiteMetadata(), and createMIBNode().
computeFrameHistogram()
template<typename FrameIdTy> llvm::DenseMap< FrameIdTy, FrameStat > llvm::memprof::computeFrameHistogram (llvm::MapVector< CallStackId, llvm::SmallVector< FrameIdTy > > & MemProfCallStackData)
Definition at line 228 of file MemProfRadixTree.cpp.
References E(), and I.
Referenced by llvm::writeMemProfRadixTreeBased().
computeFrameHistogram< FrameId >()
template LLVM_ABI llvm::DenseMap< FrameId, FrameStat > llvm::memprof::computeFrameHistogram< FrameId > (llvm::MapVector< CallStackId, llvm::SmallVector< FrameId > > & MemProfCallStackData)
References LLVM_ABI.
computeFrameHistogram< LinearFrameId >()
template LLVM_ABI llvm::DenseMap< LinearFrameId, FrameStat > llvm::memprof::computeFrameHistogram< LinearFrameId > (llvm::MapVector< CallStackId, llvm::SmallVector< LinearFrameId > > & MemProfCallStackData)
References LLVM_ABI.
Referenced by writeMemoryProfileRadixTree().
computeFullStackId()
uint64_t llvm::memprof::computeFullStackId (ArrayRef< Frame > CallStack)
Helper to generate a single hash id for a given callstack, used for emitting matching statistics and useful for uniquing such statistics across modules.
Also used to dedup contexts when computing the summary.
Definition at line 77 of file MemProfCommon.cpp.
References llvm::HashBuilder< HasherT, Endianness >::add(), F, llvm::HashBuilderBase< HasherT >::final(), and llvm::little.
Referenced by llvm::memprof::MemProfSummaryBuilder::addRecord(), and handleAllocSite().
computeUndriftMap()
DenseMap< uint64_t, LocToLocMap > llvm::memprof::computeUndriftMap (Module & M, IndexedInstrProfReader * MemProfReader, const TargetLibraryInfo & TLI)
Definition at line 334 of file MemProfUse.cpp.
References A(), assert(), B(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), extractCallsFromIR(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::longestCommonSequence(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by llvm::MemProfUsePass::run().
deserializeV2()
IndexedMemProfRecord llvm::memprof::deserializeV2 (const MemProfSchema & Schema, const unsigned char * Ptr) static
Definition at line 199 of file MemProf.cpp.
References I, llvm::support::endian::readNext(), and llvm::memprof::PortableMemInfoBlock::serializedSize().
Referenced by llvm::memprof::IndexedMemProfRecord::deserialize().
deserializeV3()
IndexedMemProfRecord llvm::memprof::deserializeV3 (const MemProfSchema & Schema, const unsigned char * Ptr) static
Definition at line 230 of file MemProf.cpp.
References I, llvm::support::endian::readNext(), and llvm::memprof::PortableMemInfoBlock::serializedSize().
Referenced by llvm::memprof::IndexedMemProfRecord::deserialize().
deserializeV4()
IndexedMemProfRecord llvm::memprof::deserializeV4 (const MemProfSchema & Schema, const unsigned char * Ptr) static
Definition at line 267 of file MemProf.cpp.
References I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::support::endian::readNext(), llvm::SmallVectorImpl< T >::reserve(), and llvm::memprof::PortableMemInfoBlock::serializedSize().
Referenced by llvm::memprof::IndexedMemProfRecord::deserialize().
extractCallsFromIR()
DenseMap< uint64_t, SmallVector< CallEdgeTy, 0 > > llvm::memprof::extractCallsFromIR (Module & M, const TargetLibraryInfo & TLI, function_ref< bool(uint64_t)> IsPresentInProfile = [](uint64_t) { return true; })
Definition at line 259 of file MemProfUse.cpp.
References assert(), llvm::dyn_cast(), llvm::StringRef::empty(), F, getGUID(), I, llvm::isa(), isAllocationWithHotColdVariant(), llvm::sort(), and llvm::unique().
Referenced by computeUndriftMap().
getAllocType()
AllocationType llvm::memprof::getAllocType (uint64_t TotalLifetimeAccessDensity, uint64_t AllocCount, uint64_t TotalLifetime)
Return the allocation type for a given set of memory profile values.
Definition at line 55 of file MemProfCommon.cpp.
References llvm::Cold, llvm::Hot, llvm::MemProfAveLifetimeColdThreshold(), llvm::MemProfLifetimeAccessDensityColdThreshold(), llvm::MemProfMinAveLifetimeAccessDensityHotThreshold(), llvm::MemProfUseHotHints(), and llvm::NotCold.
Referenced by addCallStack(), getAllocType(), and handleAllocSite().
getAllocTypeAttributeString()
std::string llvm::memprof::getAllocTypeAttributeString (AllocationType Type)
Returns the string to use in attributes with the given type.
Definition at line 109 of file MemoryProfileInfo.cpp.
References assert(), llvm::Cold, llvm::Hot, llvm_unreachable, and llvm::NotCold.
Referenced by llvm::memprof::CallStackTrie::addSingleAllocTypeAttribute(), createMIBNode(), handleAllocSite(), and llvm::MemProfUsePass::run().
getAnnotationKind()
AnnotationKind llvm::memprof::getAnnotationKind (const GlobalVariable & GV)
Returns the annotation kind of the global variable GV.
Definition at line 33 of file StaticDataProfileInfo.cpp.
References AnnotationOK, DeclForLinker, ExplicitSection, llvm::Value::getName(), hasExplicitSectionName(), llvm::GlobalValue::isDeclarationForLinker(), and ReservedName.
Referenced by IsAnnotationOK().
getCanonicalName()
Expected< StringRef > llvm::memprof::getCanonicalName (StringRef Name) static
Definition at line 25 of file DataAccessProf.cpp.
References llvm::InstrProfSymtab::getCanonicalName(), llvm::invalid_argument, and llvm::make_error().
Referenced by llvm::memprof::DataAccessProfData::addKnownSymbolWithoutSamples(), llvm::memprof::DataAccessProfData::getProfileRecord(), and llvm::memprof::DataAccessProfData::setDataAccessProfile().
getFullSchema()
MemProfSchema llvm::memprof::getFullSchema ()
Definition at line 11 of file MemProf.cpp.
Referenced by llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo(), llvm::writeMemProfRadixTreeBased(), and llvm::writeMemProfV2().
getGUID()
GlobalValue::GUID llvm::memprof::getGUID (const StringRef FunctionName)
Definition at line 344 of file MemProf.cpp.
References llvm::sampleprof::FunctionSamples::getCanonicalFnName(), and llvm::GlobalValue::getGUIDAssumingExternalLinkage().
Referenced by extractCallsFromIR(), and llvm::yaml::ScalarTraits< memprof::GUIDHex64 >::input().
getHotColdSchema()
MemProfSchema llvm::memprof::getHotColdSchema ()
Definition at line 19 of file MemProf.cpp.
Referenced by llvm::writeMemProfRadixTreeBased(), and llvm::writeMemProfV2().
getMemprofOptionsSymbolDarwinLinkageName()
llvm::StringRef llvm::memprof::getMemprofOptionsSymbolDarwinLinkageName () inline
Definition at line 58 of file MemProf.h.
Referenced by getMemprofOptionsSymbolName().
getMemprofOptionsSymbolName()
llvm::StringRef llvm::memprof::getMemprofOptionsSymbolName () inline
Definition at line 62 of file MemProf.h.
References llvm::StringRef::drop_front(), and getMemprofOptionsSymbolDarwinLinkageName().
Referenced by createMemprofDefaultOptionsVar().
getMIBAllocType()
AllocationType llvm::memprof::getMIBAllocType (const MDNode * MIB)
Returns the allocation type from an MIB metadata node.
Definition at line 94 of file MemoryProfileInfo.cpp.
References assert(), llvm::Cold, llvm::dyn_cast(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::Hot, and llvm::NotCold.
Referenced by llvm::memprof::CallStackTrie::addCallStack(), computeFunctionSummary(), and saveFilteredNewMIBNodes().
getMIBStackNode()
MDNode * llvm::memprof::getMIBStackNode (const MDNode * MIB)
Returns the stack node from an MIB metadata node.
Definition at line 88 of file MemoryProfileInfo.cpp.
References assert(), llvm::cast(), llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Referenced by llvm::memprof::CallStackTrie::addCallStack(), checkAllocContextIds(), computeFunctionSummary(), propagateMemProfHelper(), and saveFilteredNewMIBNodes().
hasExplicitSectionName()
bool llvm::memprof::hasExplicitSectionName (const GlobalVariable & GVar) static
Definition at line 21 of file StaticDataProfileInfo.cpp.
References llvm::GlobalVariable::getAttributes(), and llvm::GlobalObject::hasSection().
Referenced by getAnnotationKind().
hasSingleAllocType()
bool llvm::memprof::hasSingleAllocType (uint8_t AllocTypes)
True if the AllocTypes bitmask contains just a single type.
Definition at line 126 of file MemoryProfileInfo.cpp.
References assert(), and llvm::popcount().
Referenced by llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata().
IsAnnotationOK()
bool llvm::memprof::IsAnnotationOK (const GlobalVariable & GV)
Returns true if the annotation kind of the global variable GV is AnnotationOK.
Definition at line 47 of file StaticDataProfileInfo.cpp.
References AnnotationOK, and getAnnotationKind().
Referenced by llvm::StaticDataProfileInfo::getConstantSectionPrefix(), and StaticDataAnnotator::runOnModule().
metadataIncludesAllContextSizeInfo()
bool llvm::memprof::metadataIncludesAllContextSizeInfo ()
Whether the alloc memeprof metadata will include context size info for all MIBs.
Definition at line 63 of file MemoryProfileInfo.cpp.
References llvm::MemProfReportHintedSizes, and llvm::MinClonedColdBytePercent.
Referenced by computeFunctionSummary(), createMIBNode(), and metadataMayIncludeContextSizeInfo().
metadataMayIncludeContextSizeInfo()
bool llvm::memprof::metadataMayIncludeContextSizeInfo ()
Whether the alloc memprof metadata may include context size info for some MIBs (but possibly not all).
Definition at line 67 of file MemoryProfileInfo.cpp.
References metadataIncludesAllContextSizeInfo(), and llvm::MinPercentMaxColdSize.
Referenced by recordContextSizeInfoForAnalysis().
readMemProfSchema()
Expected< MemProfSchema > llvm::memprof::readMemProfSchema (const unsigned char *& Buffer)
Definition at line 360 of file MemProf.cpp.
References I, llvm::make_error(), llvm::malformed, and llvm::support::endian::readNext().
recordContextSizeInfoForAnalysis()
bool llvm::memprof::recordContextSizeInfoForAnalysis ()
Whether we need to record the context size info in the alloc trie used to build metadata.
Definition at line 71 of file MemoryProfileInfo.cpp.
References metadataMayIncludeContextSizeInfo(), and llvm::MinCallsiteColdBytePercent.
Referenced by addCallStack().
removeAnyExistingAmbiguousAttribute()
void llvm::memprof::removeAnyExistingAmbiguousAttribute (CallBase * CB)
Removes any existing "ambiguous" memprof attribute.
Called before we apply a specific allocation type such as "cold", "notcold", or "hot".
Definition at line 132 of file MemoryProfileInfo.cpp.
References assert(), llvm::CallBase::getFnAttr(), llvm::Attribute::getValueAsString(), llvm::CallBase::hasFnAttr(), and llvm::CallBase::removeFnAttr().
Referenced by llvm::memprof::CallStackTrie::addSingleAllocTypeAttribute().
saveStringToMap()
std::pair< StringRef, uint64_t > llvm::memprof::saveStringToMap (DataAccessProfData::StringToIndexMap & Map, llvm::UniqueStringSaver & Saver, StringRef Str) static
Definition at line 18 of file DataAccessProf.cpp.
References llvm::UniqueStringSaver::save().
Referenced by llvm::memprof::DataAccessProfData::addKnownSymbolWithoutSamples(), llvm::memprof::DataAccessProfData::setDataAccessProfile(), and llvm::memprof::DataAccessProfData::setDataAccessProfile().
serializedSizeV2() [1/2]
size_t llvm::memprof::serializedSizeV2 (const IndexedAllocationInfo & IAI, const MemProfSchema & Schema) static
Definition at line 24 of file MemProf.cpp.
References llvm::memprof::PortableMemInfoBlock::serializedSize(), and Size.
Referenced by llvm::memprof::IndexedAllocationInfo::serializedSize(), and llvm::memprof::IndexedMemProfRecord::serializedSize().
serializedSizeV2() [2/2]
size_t llvm::memprof::serializedSizeV2 (const IndexedMemProfRecord & Record, const MemProfSchema & Schema) static
Definition at line 57 of file MemProf.cpp.
References N, and Version2.
serializedSizeV3() [1/2]
size_t llvm::memprof::serializedSizeV3 (const IndexedAllocationInfo & IAI, const MemProfSchema & Schema) static
Definition at line 34 of file MemProf.cpp.
References llvm::memprof::PortableMemInfoBlock::serializedSize(), and Size.
Referenced by llvm::memprof::IndexedAllocationInfo::serializedSize(), and llvm::memprof::IndexedMemProfRecord::serializedSize().
serializedSizeV3() [2/2]
size_t llvm::memprof::serializedSizeV3 (const IndexedMemProfRecord & Record, const MemProfSchema & Schema) static
Definition at line 71 of file MemProf.cpp.
References N, and Version3.
serializedSizeV4()
size_t llvm::memprof::serializedSizeV4 (const IndexedMemProfRecord & Record, const MemProfSchema & Schema) static
Definition at line 86 of file MemProf.cpp.
References N, and Version4.
Referenced by llvm::memprof::IndexedMemProfRecord::serializedSize().
serializeV2()
void llvm::memprof::serializeV2 (const IndexedMemProfRecord & Record, const MemProfSchema & Schema, raw_ostream & OS) static
Definition at line 114 of file MemProf.cpp.
References llvm::little, and N.
Referenced by llvm::memprof::IndexedMemProfRecord::serialize().
serializeV3()
void llvm::memprof::serializeV3 (const IndexedMemProfRecord & Record, const MemProfSchema & Schema, raw_ostream & OS, llvm::DenseMap< CallStackId, LinearCallStackId > & MemProfCallStackIndexes) static
Definition at line 132 of file MemProf.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), llvm::little, and N.
Referenced by llvm::memprof::IndexedMemProfRecord::serialize().
serializeV4()
void llvm::memprof::serializeV4 (const IndexedMemProfRecord & Record, const MemProfSchema & Schema, raw_ostream & OS, llvm::DenseMap< CallStackId, LinearCallStackId > & MemProfCallStackIndexes) static
Definition at line 155 of file MemProf.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), llvm::Guid, llvm::little, and N.
Referenced by llvm::memprof::IndexedMemProfRecord::serialize().
Variable Documentation
CallStackRadixTreeBuilder< FrameId >
template class LLVM_EXPORT_TEMPLATE llvm::memprof::CallStackRadixTreeBuilder< FrameId >
Definition at line 223 of file MemProfRadixTree.cpp.
CallStackRadixTreeBuilder< LinearFrameId >
template class LLVM_EXPORT_TEMPLATE llvm::memprof::CallStackRadixTreeBuilder< LinearFrameId >
Definition at line 224 of file MemProfRadixTree.cpp.
MaximumSupportedVersion
uint64_t llvm::memprof::MaximumSupportedVersion = Version4 constexpr
Definition at line 53 of file MemProf.h.
Referenced by llvm::IndexedMemProfReader::deserialize(), llvm::IndexedMemProfReader::getMemProfRecord(), llvm::memprof::PortableMemInfoBlock::MIBEntryDef(), and llvm::writeMemProf().
MinimumSupportedVersion
uint64_t llvm::memprof::MinimumSupportedVersion = Version2 constexpr
Definition at line 52 of file MemProf.h.
Referenced by llvm::IndexedMemProfReader::deserialize(), llvm::IndexedMemProfReader::getMemProfRecord(), llvm::memprof::PortableMemInfoBlock::MIBEntryDef(), llvm::memprof::PortableMemInfoBlock::MIBEntryDef(), and llvm::writeMemProf().