LLVM: llvm::lsp Namespace Reference
llvm::lsp Namespace Reference
Classes
class Logger
This class represents the main interface for logging, and allows for filtering logging based on different levels of severity or significance.
class LSPError
This class models an LSP error as an llvm::Error.
class URIForFile
URI in "file" scheme for a file.
struct ClientCapabilities
struct ClientInfo
struct InitializeParams
struct NoParams
struct TextDocumentItem
struct TextDocumentIdentifier
struct VersionedTextDocumentIdentifier
struct Position
struct Range
struct Location
struct TextDocumentPositionParams
struct ReferenceContext
struct ReferenceParams
struct DidOpenTextDocumentParams
struct DidCloseTextDocumentParams
struct TextDocumentContentChangeEvent
struct DidChangeTextDocumentParams
struct MarkupContent
struct Hover
struct DocumentSymbol
Represents programming constructs like variables, classes, interfaces etc.
struct DocumentSymbolParams
struct DiagnosticRelatedInformation
Represents a related message and source code location for a diagnostic.
struct Diagnostic
struct PublishDiagnosticsParams
struct TextEdit
struct CompletionItem
struct CompletionList
Represents a collection of completion items to be presented in the editor.
struct CompletionContext
struct CompletionParams
struct ParameterInformation
A single parameter of a particular signature.
struct SignatureInformation
Represents the signature of something callable.
struct SignatureHelp
Represents the signature of a callable.
struct DocumentLinkParams
Parameters for the document link request.
struct DocumentLink
A range in a text document that links to an internal or external resource, like another text document or a web site.
struct InlayHintsParams
A parameter literal used in inlay hint requests.
struct InlayHint
Inlay hint information.
struct CodeActionContext
struct CodeActionParams
struct WorkspaceEdit
struct CodeAction
A code action represents a change that can be performed in code, e.g.
struct MessageActionItem
struct ShowMessageParams
class JSONTransportInput
An abstract class used by the JSONTransport to read JSON message.
class JSONTransportInputOverFile
Concrete implementation of the JSONTransportInput that reads from a file.
class JSONTransport
A transport class that performs the JSON-RPC communication with the LSP client.
class MessageHandler
A handler used to process the incoming transport messages.
Typedefs
using InitializedParams = NoParams
using CompletionItemKindBitset = std::bitset<kCompletionItemKindMax + 1>
template<typename T>
using Callback = llvm::unique_function<void(llvm::Expected<T>)>
A Callback<T> is a void function that accepts Expected<T>.
template<typename T>
using OutgoingNotification = llvm::unique_function<void(const T &)>
An OutgoingNotification<T> is a function used for outgoing notifications send to the client.
template<typename T>
using OutgoingRequest
An OutgoingRequest<T> is a function used for outgoing requests to send to the client.
template<typename T>
using OutgoingRequestCallback
An OutgoingRequestCallback is invoked when an outgoing request to the client receives a response in turn.
Enumerations
enum class ErrorCode {
ParseError = -32700 , InvalidRequest = -32600 , MethodNotFound = -32601 , InvalidParams = -32602 ,
InternalError = -32603 , ServerNotInitialized = -32002 , UnknownErrorCode = -32001 , RequestCancelled = -32800 ,
ContentModified = -32801 , RequestFailed = -32803
}
enum class TextDocumentSyncKind { None = 0 , Full = 1 , Incremental = 2 }
Defines how the host (editor) should sync document changes to the language server.
enum class TraceLevel { Off = 0 , Messages = 1 , Verbose = 2 }
enum class MarkupKind { PlainText , Markdown }
Describes the content type that a client supports in various result literals like Hover.
enum class SymbolKind {
File = 1 , Module = 2 , Namespace = 3 , Package = 4 ,
Class = 5 , Method = 6 , Property = 7 , Field = 8 ,
Constructor = 9 , Enum = 10 , Interface = 11 , Function = 12 ,
Variable = 13 , Constant = 14 , String = 15 , Number = 16 ,
Boolean = 17 , Array = 18 , Object = 19 , Key = 20 ,
Null = 21 , EnumMember = 22 , Struct = 23 , Event = 24 ,
Operator = 25 , TypeParameter = 26
}
enum class DiagnosticSeverity {
Undetermined = 0 , Error = 1 , Warning = 2 , Information = 3 ,
Hint = 4
}
enum class DiagnosticTag { Unnecessary = 1 , Deprecated = 2 }
enum class CompletionItemKind {
Missing = 0 , Text = 1 , Method = 2 , Function = 3 ,
Constructor = 4 , Field = 5 , Variable = 6 , Class = 7 ,
Interface = 8 , Module = 9 , Property = 10 , Unit = 11 ,
Value = 12 , Enum = 13 , Keyword = 14 , Snippet = 15 ,
Color = 16 , File = 17 , Reference = 18 , Folder = 19 ,
EnumMember = 20 , Constant = 21 , Struct = 22 , Event = 23 ,
Operator = 24 , TypeParameter = 25
}
The kind of a completion entry.
enum class InsertTextFormat { Missing = 0 , PlainText = 1 , Snippet = 2 }
Defines whether the insert text in a completion item should be interpreted as plain text or a snippet.
enum class CompletionTriggerKind { Invoked = 1 , TriggerCharacter = 2 , TriggerTriggerForIncompleteCompletions = 3 }
enum class InlayHintKind { Type = 1 , Parameter = 2 }
Inlay hint kinds.
enum class MessageType {
Error = 1 , Warning = 2 , Info = 3 , Log = 4 ,
Debug = 5
}
enum JSONStreamStyle { Standard , Delimited }
The encoding style of the JSON-RPC messages (both input and output).
Functions
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const URIForFile &value)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, URIForFile &result, llvm::json::Path path)
raw_ostream & operator<< (raw_ostream &os, const URIForFile &value)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, ClientCapabilities &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, ClientInfo &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, TraceLevel &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, InitializeParams &result, llvm::json::Path path)
Add support for JSON serialization.
bool fromJSON (const llvm::json::Value &, NoParams &, llvm::json::Path)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, TextDocumentItem &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const TextDocumentIdentifier &value)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, TextDocumentIdentifier &result, llvm::json::Path path)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const VersionedTextDocumentIdentifier &value)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, VersionedTextDocumentIdentifier &result, llvm::json::Path path)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, Position &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const Position &value)
raw_ostream & operator<< (raw_ostream &os, const Position &value)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, Range &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const Range &value)
raw_ostream & operator<< (raw_ostream &os, const Range &value)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, Location &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const Location &value)
raw_ostream & operator<< (raw_ostream &os, const Location &value)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, TextDocumentPositionParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, ReferenceContext &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, ReferenceParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, DidOpenTextDocumentParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, DidCloseTextDocumentParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, TextDocumentContentChangeEvent &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, DidChangeTextDocumentParams &result, llvm::json::Path path)
Add support for JSON serialization.
raw_ostream & operator<< (raw_ostream &os, MarkupKind kind)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const MarkupContent &mc)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const Hover &hover)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const DocumentSymbol &symbol)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, DocumentSymbolParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, DiagnosticRelatedInformation &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const DiagnosticRelatedInformation &info)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (DiagnosticTag tag)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, DiagnosticTag &result, llvm::json::Path path)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const Diagnostic &diag)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, Diagnostic &result, llvm::json::Path path)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const PublishDiagnosticsParams &params)
Add support for JSON serialization.
bool operator== (const TextEdit &lhs, const TextEdit &rhs)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, TextEdit &result, llvm::json::Path path)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const TextEdit &value)
raw_ostream & operator<< (raw_ostream &os, const TextEdit &value)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, CompletionItemKind &result, llvm::json::Path path)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, CompletionItemKindBitset &result, llvm::json::Path path)
CompletionItemKind adjustKindToCapability (CompletionItemKind kind, CompletionItemKindBitset &supportedCompletionItemKinds)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const CompletionItem &value)
Add support for JSON serialization.
raw_ostream & operator<< (raw_ostream &os, const CompletionItem &value)
bool operator< (const CompletionItem &lhs, const CompletionItem &rhs)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const CompletionList &value)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, CompletionContext &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, CompletionParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const ParameterInformation &value)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const SignatureInformation &value)
Add support for JSON serialization.
raw_ostream & operator<< (raw_ostream &os, const SignatureInformation &value)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const SignatureHelp &value)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, DocumentLinkParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const DocumentLink &value)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, InlayHintsParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const InlayHint &)
Add support for JSON serialization.
bool operator== (const InlayHint &lhs, const InlayHint &rhs)
bool operator< (const InlayHint &lhs, const InlayHint &rhs)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, InlayHintKind value)
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, CodeActionContext &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, CodeActionParams &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST bool fromJSON (const llvm::json::Value &value, WorkspaceEdit &result, llvm::json::Path path)
Add support for JSON serialization.
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const WorkspaceEdit &value)
LLVM_ABI_FOR_TEST llvm::json::Value toJSON (const CodeAction &)
Add support for JSON serialization.
llvm::json::Value toJSON (const MessageActionItem &Params)
Add support for JSON serialization.
llvm::json::Value toJSON (const ShowMessageParams &Params)
Add support for JSON serialization.
Variables
constexpr auto kCompletionItemKindMin
constexpr auto kCompletionItemKindMax
Typedef Documentation
Callback
template<typename T> using llvm::lsp::Callback = llvm::unique_function<void(llvm::Expected<T>)>
A Callback<T> is a void function that accepts Expected<T>.
This is accepted by functions that logically return T.
Definition at line 139 of file Transport.h.
CompletionItemKindBitset
using llvm::lsp::CompletionItemKindBitset = std::bitset<kCompletionItemKindMax + 1>
Definition at line 831 of file Protocol.h.
InitializedParams
using llvm::lsp::InitializedParams = NoParams
Definition at line 233 of file Protocol.h.
OutgoingNotification
template<typename T> using llvm::lsp::OutgoingNotification = llvm::unique_function<void(const T &)>
An OutgoingNotification<T> is a function used for outgoing notifications send to the client.
Definition at line 144 of file Transport.h.
OutgoingRequest
template<typename T> using llvm::lsp::OutgoingRequest
Initial value:
llvm::unique_function<void(const T &, llvm::json::Value Id)>
An OutgoingRequest<T> is a function used for outgoing requests to send to the client.
Definition at line 149 of file Transport.h.
OutgoingRequestCallback
template<typename T> using llvm::lsp::OutgoingRequestCallback
Initial value:
std::function<void(llvm::json::Value, llvm::Expected<T>)>
An OutgoingRequestCallback is invoked when an outgoing request to the client receives a response in turn.
It is passed the original request's ID, as well as the response result.
Definition at line 156 of file Transport.h.
Enumeration Type Documentation
CompletionItemKind
enum class llvm::lsp::CompletionItemKind strong
The kind of a completion entry.
Enumerator
Missing
Text
Method
Function
Constructor
Field
Variable
Class
Interface
Module
Property
Unit
Value
Enum
Keyword
Snippet
Color
File
Reference
Folder
EnumMember
Constant
Struct
Event
Operator
TypeParameter
Definition at line 795 of file Protocol.h.
CompletionTriggerKind
enum class llvm::lsp::CompletionTriggerKind strong
Enumerator
Invoked
Completion was triggered by typing an identifier (24x7 code complete), manual invocation (e.g Ctrl+Space) or via API.
TriggerCharacter
Completion was triggered by a trigger character specified by the triggerCharacters properties of the CompletionRegistrationOptions.
TriggerTriggerForIncompleteCompletions
Completion was re-triggered as the current completion list is incomplete.
Definition at line 942 of file Protocol.h.
DiagnosticSeverity
enum class llvm::lsp::DiagnosticSeverity strong
Enumerator
Undetermined
It is up to the client to interpret diagnostics as error, warning, info or hint.
Error
Warning
Information
Hint
Definition at line 693 of file Protocol.h.
DiagnosticTag
enum class llvm::lsp::DiagnosticTag strong
Enumerator
Unnecessary
Deprecated
Definition at line 703 of file Protocol.h.
ErrorCode
enum class llvm::lsp::ErrorCode strong
Enumerator
ParseError
InvalidRequest
MethodNotFound
InvalidParams
InternalError
ServerNotInitialized
UnknownErrorCode
RequestCancelled
ContentModified
RequestFailed
Definition at line 44 of file Protocol.h.
InlayHintKind
enum class llvm::lsp::InlayHintKind strong
Inlay hint kinds.
Enumerator
Type
An inlay hint that for a type annotation.
An example of a type hint is a hint in this position: auto var ^ = expr; which shows the deduced type of the variable.
Parameter
An inlay hint that is for a parameter.
An example of a parameter hint is a hint in this position: func(^arg); which shows the name of the corresponding parameter.
Definition at line 1115 of file Protocol.h.
InsertTextFormat
enum class llvm::lsp::InsertTextFormat strong
Defines whether the insert text in a completion item should be interpreted as plain text or a snippet.
Enumerator
Missing
PlainText
The primary text to be inserted is treated as a plain string.
Snippet
The primary text to be inserted is treated as a snippet.
A snippet can define tab stops and placeholders with $1, $2 and ${3:foo}. $0 defines the final tab stop, it defaults to the end of the snippet. Placeholders with equal identifiers are linked, that is typing in one will update others too.
See also: https//github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md
Definition at line 846 of file Protocol.h.
JSONStreamStyle
enum llvm::lsp::JSONStreamStyle
The encoding style of the JSON-RPC messages (both input and output).
Enumerator
Standard
Encoding per the LSP specification, with mandatory Content-Length header.
Delimited
Messages are delimited by a '// --—' line. Comment lines start with //.
Definition at line 45 of file Transport.h.
MarkupKind
enum class llvm::lsp::MarkupKind strong
Describes the content type that a client supports in various result literals like Hover.
Enumerator
PlainText
Markdown
Definition at line 542 of file Protocol.h.
MessageType
enum class llvm::lsp::MessageType strong
Enumerator
Error
Warning
Info
Log
Debug
Definition at line 1276 of file Protocol.h.
SymbolKind
enum class llvm::lsp::SymbolKind strong
Enumerator
File
Module
Namespace
Package
Class
Method
Property
Field
Constructor
Enum
Interface
Function
Variable
Constant
String
Number
Boolean
Array
Object
Key
Null
EnumMember
Struct
Event
Operator
TypeParameter
Definition at line 579 of file Protocol.h.
TextDocumentSyncKind
enum class llvm::lsp::TextDocumentSyncKind strong
Defines how the host (editor) should sync document changes to the language server.
Enumerator
None
Documents should not be synced at all.
Full
Documents are synced by always sending the full content of the document.
Incremental
Documents are synced by sending the full content on open.
After that only incremental updates to the document are sent.
Definition at line 63 of file Protocol.h.
TraceLevel
enum class llvm::lsp::TraceLevel strong
Enumerator
Off
Messages
Verbose
Definition at line 199 of file Protocol.h.
Function Documentation
adjustKindToCapability()
CompletionItemKind llvm::lsp::adjustKindToCapability (CompletionItemKind kind, CompletionItemKindBitset & supportedCompletionItemKinds)
Definition at line 744 of file Protocol.cpp.
References Class, Enum, EnumMember, File, Folder, kCompletionItemKindMin, Struct, and Text.
fromJSON() [1/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & , NoParams & , llvm::json::Path) inline
Definition at line 230 of file Protocol.h.
fromJSON() [2/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, ClientCapabilities & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 265 of file Protocol.cpp.
fromJSON() [3/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, ClientInfo & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 296 of file Protocol.cpp.
fromJSON() [4/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, CodeActionContext & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 983 of file Protocol.cpp.
fromJSON() [5/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, CodeActionParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 996 of file Protocol.cpp.
fromJSON() [6/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, CompletionContext & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 838 of file Protocol.cpp.
References mapOptOrNull().
fromJSON() [7/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, CompletionItemKind & result, llvm::json::Path path)
Definition at line 732 of file Protocol.cpp.
References Text, and TypeParameter.
fromJSON() [8/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, CompletionItemKindBitset & result, llvm::json::Path path)
Definition at line 766 of file Protocol.cpp.
References fromJSON(), and I.
fromJSON() [9/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, CompletionParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 853 of file Protocol.cpp.
References fromJSON().
fromJSON() [10/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, Diagnostic & result, llvm::json::Path path)
Definition at line 675 of file Protocol.cpp.
References mapOptOrNull().
fromJSON() [11/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, DiagnosticRelatedInformation & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 625 of file Protocol.cpp.
fromJSON() [12/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, DiagnosticTag & result, llvm::json::Path path)
Definition at line 648 of file Protocol.cpp.
References I.
fromJSON() [13/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, DidChangeTextDocumentParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 547 of file Protocol.cpp.
fromJSON() [14/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, DidCloseTextDocumentParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 498 of file Protocol.cpp.
fromJSON() [15/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, DidOpenTextDocumentParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 487 of file Protocol.cpp.
fromJSON() [16/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, DocumentLinkParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 920 of file Protocol.cpp.
fromJSON() [17/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, DocumentSymbolParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 615 of file Protocol.cpp.
fromJSON() [18/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, InitializeParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 330 of file Protocol.cpp.
References mapOptOrNull().
fromJSON() [19/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, InlayHintsParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 941 of file Protocol.cpp.
fromJSON() [20/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, Location & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 436 of file Protocol.cpp.
fromJSON() [21/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, Position & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 393 of file Protocol.cpp.
fromJSON() [22/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, Range & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 415 of file Protocol.cpp.
fromJSON() [23/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, ReferenceContext & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 469 of file Protocol.cpp.
fromJSON() [24/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, ReferenceParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 475 of file Protocol.cpp.
References llvm::sampleprof::Base, and fromJSON().
fromJSON() [25/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, TextDocumentContentChangeEvent & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 539 of file Protocol.cpp.
fromJSON() [26/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, TextDocumentIdentifier & result, llvm::json::Path path)
Definition at line 363 of file Protocol.cpp.
fromJSON() [27/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, TextDocumentItem & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 347 of file Protocol.cpp.
fromJSON() [28/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, TextDocumentPositionParams & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 457 of file Protocol.cpp.
fromJSON() [29/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, TextEdit & result, llvm::json::Path path)
Definition at line 709 of file Protocol.cpp.
fromJSON() [30/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, TraceLevel & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 311 of file Protocol.cpp.
References Messages, Off, and Verbose.
fromJSON() [31/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, URIForFile & result, llvm::json::Path path)
Definition at line 238 of file Protocol.cpp.
References llvm::consumeError(), llvm::lsp::URIForFile::fromURI(), and llvm::Expected< T >::takeError().
Referenced by fromJSON(), fromJSON(), fromJSON(), mapOptOrNull(), and llvm::lsp::MessageHandler::parse().
fromJSON() [32/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, VersionedTextDocumentIdentifier & result, llvm::json::Path path)
Definition at line 382 of file Protocol.cpp.
fromJSON() [33/33]
bool llvm::lsp::fromJSON (const llvm::json::Value & value, WorkspaceEdit & result, llvm::json::Path path)
Add support for JSON serialization.
Definition at line 1007 of file Protocol.cpp.
operator<() [1/2]
bool llvm::lsp::operator< (const CompletionItem & lhs, const CompletionItem & rhs)
Definition at line 817 of file Protocol.cpp.
References llvm::lsp::CompletionItem::label, and llvm::lsp::CompletionItem::sortText.
operator<() [2/2]
bool llvm::lsp::operator< (const InlayHint & lhs, const InlayHint & rhs)
Definition at line 963 of file Protocol.cpp.
References llvm::lsp::InlayHint::kind, llvm::lsp::InlayHint::label, and llvm::lsp::InlayHint::position.
operator<<() [1/9]
llvm::raw_ostream & llvm::lsp::operator<< (llvm::raw_ostream & os, InlayHintKind value)
Definition at line 968 of file Protocol.cpp.
References llvm_unreachable, Parameter, and Type.
operator<<() [2/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, const CompletionItem & value)
Definition at line 812 of file Protocol.cpp.
References toJSON().
operator<<() [3/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, const Location & value)
Definition at line 449 of file Protocol.cpp.
operator<<() [4/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, const Position & value)
Definition at line 407 of file Protocol.cpp.
operator<<() [5/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, const Range & value)
Definition at line 428 of file Protocol.cpp.
operator<<() [6/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, const SignatureInformation & value)
Definition at line 895 of file Protocol.cpp.
References toJSON().
operator<<() [7/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, const TextEdit & value)
Definition at line 722 of file Protocol.cpp.
operator<<() [8/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, const URIForFile & value)
Definition at line 257 of file Protocol.cpp.
operator<<() [9/9]
raw_ostream & llvm::lsp::operator<< (raw_ostream & os, MarkupKind kind)
Definition at line 569 of file Protocol.cpp.
References toTextKind().
operator==() [1/2]
bool llvm::lsp::operator== (const InlayHint & lhs, const InlayHint & rhs)
Definition at line 959 of file Protocol.cpp.
References llvm::lsp::InlayHint::kind, llvm::lsp::InlayHint::label, and llvm::lsp::InlayHint::position.
operator==() [2/2]
bool llvm::lsp::operator== (const TextEdit & lhs, const TextEdit & rhs) inline
Definition at line 781 of file Protocol.h.
References llvm::lsp::TextEdit::newText, and llvm::lsp::TextEdit::range.
toJSON() [1/25]
llvm::json::Value llvm::lsp::toJSON (const CodeAction & Value)
Add support for JSON serialization.
Definition at line 1028 of file Protocol.cpp.
toJSON() [2/25]
llvm::json::Value llvm::lsp::toJSON (const CompletionItem & value)
Add support for JSON serialization.
Definition at line 784 of file Protocol.cpp.
References assert(), and Missing.
toJSON() [3/25]
llvm::json::Value llvm::lsp::toJSON (const CompletionList & value)
Add support for JSON serialization.
Definition at line 827 of file Protocol.cpp.
toJSON() [4/25]
llvm::json::Value llvm::lsp::toJSON (const Diagnostic & diag)
Add support for JSON serialization.
Definition at line 658 of file Protocol.cpp.
References llvm::lsp::Diagnostic::category, llvm::lsp::Diagnostic::message, llvm::lsp::Diagnostic::range, llvm::lsp::Diagnostic::relatedInformation, llvm::lsp::Diagnostic::severity, llvm::lsp::Diagnostic::source, and llvm::lsp::Diagnostic::tags.
toJSON() [5/25]
llvm::json::Value llvm::lsp::toJSON (const DiagnosticRelatedInformation & info)
Definition at line 633 of file Protocol.cpp.
toJSON() [6/25]
llvm::json::Value llvm::lsp::toJSON (const DocumentLink & value)
Add support for JSON serialization.
Definition at line 930 of file Protocol.cpp.
toJSON() [7/25]
llvm::json::Value llvm::lsp::toJSON (const DocumentSymbol & symbol)
Add support for JSON serialization.
Definition at line 598 of file Protocol.cpp.
toJSON() [8/25]
llvm::json::Value llvm::lsp::toJSON (const Hover & hover)
Add support for JSON serialization.
Definition at line 587 of file Protocol.cpp.
References llvm::lsp::Hover::contents, llvm::lsp::Hover::range, and toJSON().
toJSON() [9/25]
llvm::json::Value llvm::lsp::toJSON (const InlayHint & Value)
Add support for JSON serialization.
Definition at line 952 of file Protocol.cpp.
toJSON() [10/25]
llvm::json::Value llvm::lsp::toJSON (const Location & value)
Definition at line 442 of file Protocol.cpp.
toJSON() [11/25]
llvm::json::Value llvm::lsp::toJSON (const MarkupContent & mc)
Add support for JSON serialization.
Definition at line 573 of file Protocol.cpp.
References llvm::lsp::MarkupContent::kind, toTextKind(), and llvm::lsp::MarkupContent::value.
toJSON() [12/25]
llvm::json::Value llvm::lsp::toJSON (const MessageActionItem & Params)
Add support for JSON serialization.
Definition at line 1055 of file Protocol.cpp.
References llvm::lsp::MessageActionItem::title.
toJSON() [13/25]
llvm::json::Value llvm::lsp::toJSON (const ParameterInformation & value)
Add support for JSON serialization.
Definition at line 866 of file Protocol.cpp.
References assert().
toJSON() [14/25]
llvm::json::Value llvm::lsp::toJSON (const Position & value)
Definition at line 400 of file Protocol.cpp.
toJSON() [15/25]
llvm::json::Value llvm::lsp::toJSON (const PublishDiagnosticsParams & params)
Add support for JSON serialization.
Definition at line 697 of file Protocol.cpp.
References llvm::lsp::PublishDiagnosticsParams::diagnostics, llvm::lsp::PublishDiagnosticsParams::uri, and llvm::lsp::PublishDiagnosticsParams::version.
toJSON() [16/25]
llvm::json::Value llvm::lsp::toJSON (const Range & value)
Definition at line 421 of file Protocol.cpp.
toJSON() [17/25]
llvm::json::Value llvm::lsp::toJSON (const ShowMessageParams & Params)
Add support for JSON serialization.
Definition at line 1045 of file Protocol.cpp.
References llvm::lsp::ShowMessageParams::actions, llvm::lsp::ShowMessageParams::message, and llvm::lsp::ShowMessageParams::type.
toJSON() [18/25]
llvm::json::Value llvm::lsp::toJSON (const SignatureHelp & value)
Add support for JSON serialization.
Definition at line 904 of file Protocol.cpp.
References assert().
toJSON() [19/25]
llvm::json::Value llvm::lsp::toJSON (const SignatureInformation & value)
Add support for JSON serialization.
Definition at line 884 of file Protocol.cpp.
References assert().
toJSON() [20/25]
llvm::json::Value llvm::lsp::toJSON (const TextDocumentIdentifier & value)
Add support for JSON serialization.
Definition at line 359 of file Protocol.cpp.
toJSON() [21/25]
llvm::json::Value llvm::lsp::toJSON (const TextEdit & value)
Definition at line 715 of file Protocol.cpp.
toJSON() [22/25]
llvm::json::Value llvm::lsp::toJSON (const URIForFile & value)
Add support for JSON serialization.
Definition at line 253 of file Protocol.cpp.
Referenced by operator<<(), operator<<(), and toJSON().
toJSON() [23/25]
llvm::json::Value llvm::lsp::toJSON (const VersionedTextDocumentIdentifier & value)
Add support for JSON serialization.
Definition at line 375 of file Protocol.cpp.
toJSON() [24/25]
llvm::json::Value llvm::lsp::toJSON (const WorkspaceEdit & value)
Definition at line 1013 of file Protocol.cpp.
toJSON() [25/25]
llvm::json::Value llvm::lsp::toJSON (DiagnosticTag tag)
Add support for JSON serialization.
Definition at line 644 of file Protocol.cpp.
Variable Documentation
kCompletionItemKindMax
auto llvm::lsp::kCompletionItemKindMax constexpr
Initial value:
                                  =
static_cast<size_t>(CompletionItemKind::TypeParameter)
Definition at line 829 of file Protocol.h.
kCompletionItemKindMin
auto llvm::lsp::kCompletionItemKindMin constexpr
Initial value:
                                  =
static_cast<size_t>(CompletionItemKind::Text)
Definition at line 827 of file Protocol.h.
Referenced by adjustKindToCapability().