LLVM: llvm::mustache Namespace Reference
llvm::mustache Namespace Reference
Classes
struct MustacheContext
class Template
class MustacheOutputStream
class RawMustacheOutputStream
class Token
class ASTNode
struct Tag
class EscapeStringStream
class AddIndentationStringStream
class Parser
Typedefs
using Lambda = std::function<llvm::json::Value()>
using SectionLambda = std::function<llvm::json::Value(std::string)>
using AstPtr = ASTNode *
using EscapeMap = DenseMap<char, std::string>
using ASTNodeList = iplist<ASTNode>
Functions
static AstPtr createRootNode (MustacheContext &Ctx)
static AstPtr createNode (MustacheContext &Ctx, ASTNode::Type T, ArrayRef< StringRef > A, ASTNode *Parent)
static AstPtr createTextNode (MustacheContext &Ctx, StringRef Body, ASTNode *Parent)
static bool hasTextBehind (size_t Idx, const ArrayRef< Token > &Tokens)
static bool hasTextAhead (size_t Idx, const ArrayRef< Token > &Tokens)
static bool requiresCleanUp (Token::Type T)
static void stripTokenAhead (SmallVectorImpl< Token > &Tokens, size_t Idx)
void stripTokenBefore (SmallVectorImpl< Token > &Tokens, size_t Idx, Token &CurrentToken, Token::Type CurrentType)
static const char * tagKindToString (Tag::Kind K)
static const char * jsonKindToString (json::Value::Kind K)
static SmallVector< Token > tokenize (StringRef Template, MustacheContext &Ctx)
static void toMustacheString (const json::Value &Data, raw_ostream &OS)
Typedef Documentation
ASTNodeList
using llvm::mustache::ASTNodeList = iplist<ASTNode>
Definition at line 90 of file Mustache.h.
AstPtr
using llvm::mustache::AstPtr = ASTNode *
Definition at line 88 of file Mustache.h.
EscapeMap
typedef DenseMap< char, std::string > llvm::mustache::EscapeMap = DenseMap<char, std::string>
Definition at line 89 of file Mustache.h.
Lambda
using llvm::mustache::Lambda = std::function<llvm::json::Value()>
Definition at line 84 of file Mustache.h.
SectionLambda
using llvm::mustache::SectionLambda = std::function<llvm::json::Value(std::string)>
Definition at line 85 of file Mustache.h.
Function Documentation
createNode()
AstPtr llvm::mustache::createNode (MustacheContext & Ctx, ASTNode::Type T, ArrayRef< StringRef > A, ASTNode * Parent) static
Definition at line 256 of file Mustache.cpp.
References A(), and T.
createRootNode()
AstPtr llvm::mustache::createRootNode (MustacheContext & Ctx) static
Definition at line 252 of file Mustache.cpp.
Referenced by llvm::mustache::Parser::parse().
createTextNode()
AstPtr llvm::mustache::createTextNode (MustacheContext & Ctx, StringRef Body, ASTNode * Parent) static
Definition at line 261 of file Mustache.cpp.
hasTextAhead()
bool llvm::mustache::hasTextAhead (size_t Idx, const ArrayRef< Token > & Tokens) static
Definition at line 294 of file Mustache.cpp.
References getType(), llvm::StringRef::ltrim(), llvm::mustache::Token::RawBody, llvm::ArrayRef< T >::size(), llvm::StringRef::starts_with(), and llvm::mustache::Token::Text.
Referenced by tokenize().
hasTextBehind()
bool llvm::mustache::hasTextBehind (size_t Idx, const ArrayRef< Token > & Tokens) static
Definition at line 278 of file Mustache.cpp.
References llvm::StringRef::empty(), llvm::StringRef::ends_with(), getType(), llvm::mustache::Token::RawBody, llvm::StringRef::rtrim(), and llvm::mustache::Token::Text.
Referenced by tokenize().
jsonKindToString()
const char * llvm::mustache::jsonKindToString (json::Value::Kind K) static
Definition at line 371 of file Mustache.cpp.
References llvm::json::Value::Array, llvm::json::Value::Boolean, llvm_unreachable, llvm::json::Value::Null, llvm::json::Value::Number, llvm::json::Value::Object, and llvm::json::Value::String.
Referenced by toMustacheString().
requiresCleanUp()
bool llvm::mustache::requiresCleanUp (Token::Type T) static
Definition at line 307 of file Mustache.cpp.
References llvm::mustache::Token::Comment, llvm::mustache::Token::InvertSectionOpen, llvm::mustache::Token::Partial, llvm::mustache::Token::SectionClose, llvm::mustache::Token::SectionOpen, llvm::mustache::Token::SetDelimiter, and T.
Referenced by tokenize().
stripTokenAhead()
void llvm::mustache::stripTokenAhead (SmallVectorImpl< Token > & Tokens, size_t Idx) static
Definition at line 320 of file Mustache.cpp.
References llvm::StringRef::starts_with(), llvm::StringRef::substr(), and llvm::mustache::Token::TokenBody.
Referenced by tokenize().
stripTokenBefore()
void llvm::mustache::stripTokenBefore (SmallVectorImpl< Token > & Tokens, size_t Idx, Token & CurrentToken, Token::Type CurrentType)
Definition at line 336 of file Mustache.cpp.
References llvm::StringRef::rtrim(), llvm::mustache::Token::setIndentation(), llvm::StringRef::size(), and llvm::mustache::Token::TokenBody.
Referenced by tokenize().
tagKindToString()
const char * llvm::mustache::tagKindToString (Tag::Kind K) static
Definition at line 359 of file Mustache.cpp.
References llvm_unreachable, llvm::mustache::Tag::None, llvm::mustache::Tag::Normal, and llvm::mustache::Tag::Triple.
Referenced by tokenize().
tokenize()
SmallVector< Token > llvm::mustache::tokenize (StringRef Template, MustacheContext & Ctx) static
Definition at line 390 of file Mustache.cpp.
References llvm::CallingConv::C, llvm::dbgs(), llvm::StringRef::drop_front(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::StringRef::empty(), llvm::StringRef::front(), llvm::mustache::Token::getType(), hasTextAhead(), hasTextBehind(), LLVM_DEBUG, llvm::mustache::Tag::Normal, llvm::StringRef::npos, requiresCleanUp(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::size(), llvm::StringRef::split(), llvm::StringRef::starts_with(), stripTokenAhead(), stripTokenBefore(), tagKindToString(), llvm::StringRef::take_until(), llvm::StringRef::trim(), and llvm::mustache::Tag::Triple.
Referenced by llvm::mustache::Parser::parse().
toMustacheString()
void llvm::mustache::toMustacheString (const json::Value & Data, raw_ostream & OS) static
Definition at line 669 of file Mustache.cpp.
References llvm::json::Value::Array, llvm::json::Value::Boolean, llvm::Data, llvm::dbgs(), jsonKindToString(), LLVM_DEBUG, llvm::json::Value::Null, llvm::json::Value::Number, llvm::json::Value::Object, llvm::json::Value::String, and llvm::json::OStream::value().