LLVM: llvm::yaml Namespace Reference
llvm::yaml Namespace Reference
Namespaces
namespace detail
Classes
struct StringValue
A wrapper around std::string which contains a source range that's being set during parsing.
struct ScalarTraits< StringValue >
struct FlowStringValue
struct ScalarTraits< FlowStringValue >
struct BlockStringValue
struct BlockScalarTraits< BlockStringValue >
struct UnsignedValue
A wrapper around unsigned which contains a source range that's being set during parsing.
struct ScalarTraits< UnsignedValue >
struct ScalarEnumerationTraits< MachineJumpTableInfo::JTEntryKind >
struct ScalarTraits< MaybeAlign >
struct ScalarTraits< Align >
struct VirtualRegisterDefinition
struct MappingTraits< VirtualRegisterDefinition >
struct MachineFunctionLiveIn
struct MappingTraits< MachineFunctionLiveIn >
struct MachineStackObject
Serializable representation of stack object from the MachineFrameInfo class.
struct ScalarEnumerationTraits< MachineStackObject::ObjectType >
struct MappingTraits< MachineStackObject >
struct EntryValueObject
Serializable representation of the MCRegister variant of MachineFunction::VariableDbgInfo.
struct MappingTraits< EntryValueObject >
struct FixedMachineStackObject
Serializable representation of the fixed stack object from the MachineFrameInfo class.
struct ScalarEnumerationTraits< FixedMachineStackObject::ObjectType >
struct ScalarEnumerationTraits< TargetStackID::Value >
struct MappingTraits< FixedMachineStackObject >
struct FrameIndex
A serializaable representation of a reference to a stack object or fixed stack object.
struct ScalarTraits< FrameIndex >
struct MachineInstrLoc
Identifies call instruction location in machine function.
struct CallSiteInfo
Serializable representation of CallSiteInfo.
struct MappingTraits< CallSiteInfo::ArgRegPair >
struct MappingTraits< CallSiteInfo >
struct DebugValueSubstitution
Serializable representation of debug value substitutions.
struct MappingTraits< DebugValueSubstitution >
struct MachineConstantPoolValue
struct MappingTraits< MachineConstantPoolValue >
struct MachineJumpTable
struct MappingTraits< MachineJumpTable::Entry >
struct CalledGlobal
struct MappingTraits< CalledGlobal >
struct SaveRestorePointEntry
struct MappingTraits< SaveRestorePointEntry >
struct MappingTraits< MachineJumpTable >
struct MachineFrameInfo
Serializable representation of MachineFrameInfo.
struct MappingTraits< MachineFrameInfo >
struct MachineFunctionInfo
Targets should override this in a way that mirrors the implementation of llvm::MachineFunctionInfo.
struct MappingTraits< std::unique_ptr< MachineFunctionInfo > >
struct MachineFunction
struct MappingTraits< MachineFunction >
struct MappingTraits
This class should be specialized by any type that needs to be converted to/from a YAML mapping.
struct ScalarEnumerationTraits< TypeTestResolution::Kind >
struct MappingTraits< TypeTestResolution >
struct ScalarEnumerationTraits< WholeProgramDevirtResolution::ByArg::Kind >
struct MappingTraits< WholeProgramDevirtResolution::ByArg >
struct CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >
struct ScalarEnumerationTraits< WholeProgramDevirtResolution::Kind >
struct MappingTraits< WholeProgramDevirtResolution >
struct CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >
struct MappingTraits< TypeIdSummary >
struct GlobalValueSummaryYaml
struct MappingTraits< FunctionSummary::VFuncId >
struct MappingTraits< FunctionSummary::ConstVCall >
struct MappingTraits< GlobalValueSummaryYaml >
struct CustomMappingTraits< GlobalValueSummaryMapTy >
struct CustomMappingTraits< TypeIdSummaryMapTy >
struct MappingTraits< ModuleSummaryIndex >
struct MappingTraits< ArchYAML::Archive >
struct MappingTraits< ArchYAML::Archive::Child >
struct ScalarEnumerationTraits< COFFYAML::WeakExternalCharacteristics >
struct ScalarEnumerationTraits< COFFYAML::AuxSymbolType >
struct ScalarEnumerationTraits< COFFYAML::COMDATType >
struct ScalarEnumerationTraits< COFF::MachineTypes >
struct ScalarEnumerationTraits< COFF::SymbolBaseType >
struct ScalarEnumerationTraits< COFF::SymbolStorageClass >
struct ScalarEnumerationTraits< COFF::SymbolComplexType >
struct ScalarEnumerationTraits< COFF::RelocationTypeI386 >
struct ScalarEnumerationTraits< COFF::RelocationTypeAMD64 >
struct ScalarEnumerationTraits< COFF::RelocationTypesMips >
struct ScalarEnumerationTraits< COFF::RelocationTypesARM >
struct ScalarEnumerationTraits< COFF::RelocationTypesARM64 >
struct ScalarEnumerationTraits< COFF::WindowsSubsystem >
struct ScalarBitSetTraits< COFF::Characteristics >
struct ScalarBitSetTraits< COFF::SectionCharacteristics >
struct ScalarBitSetTraits< COFF::DLLCharacteristics >
struct MappingTraits< COFFYAML::Relocation >
struct MappingTraits< COFFYAML::PEHeader >
struct MappingTraits< COFF::DataDirectory >
struct MappingTraits< COFF::header >
struct MappingTraits< COFF::AuxiliaryFunctionDefinition >
struct MappingTraits< COFF::AuxiliarybfAndefSymbol >
struct MappingTraits< COFF::AuxiliaryWeakExternal >
struct MappingTraits< COFF::AuxiliarySectionDefinition >
struct MappingTraits< COFF::AuxiliaryCLRToken >
struct MappingTraits< object::coff_load_configuration32 >
struct MappingTraits< object::coff_load_configuration64 >
struct MappingTraits< object::coff_load_config_code_integrity >
struct MappingTraits< COFFYAML::Symbol >
struct MappingTraits< COFFYAML::SectionDataEntry >
struct MappingTraits< COFFYAML::Section >
struct MappingTraits< COFFYAML::Object >
struct MappingTraits< DXContainerYAML::VersionTuple >
struct MappingTraits< DXContainerYAML::FileHeader >
struct MappingTraits< DXContainerYAML::DXILProgram >
struct MappingTraits< DXContainerYAML::ShaderFeatureFlags >
struct MappingTraits< DXContainerYAML::ShaderHash >
struct MappingTraits< DXContainerYAML::PSVInfo >
struct MappingTraits< DXContainerYAML::Part >
struct MappingTraits< DXContainerYAML::Object >
struct MappingTraits< DXContainerYAML::ResourceFlags >
struct MappingTraits< DXContainerYAML::ResourceBindInfo >
struct MappingTraits< DXContainerYAML::SignatureElement >
struct MappingTraits< DXContainerYAML::SignatureParameter >
struct MappingTraits< DXContainerYAML::Signature >
struct MappingTraits< DXContainerYAML::RootSignatureYamlDesc >
struct MappingContextTraits< DXContainerYAML::RootParameterLocationYaml, DXContainerYAML::RootSignatureYamlDesc >
struct MappingTraits< llvm::DXContainerYAML::RootConstantsYaml >
struct MappingTraits< llvm::DXContainerYAML::RootDescriptorYaml >
struct MappingTraits< llvm::DXContainerYAML::DescriptorTableYaml >
struct MappingTraits< llvm::DXContainerYAML::DescriptorRangeYaml >
struct MappingTraits< llvm::DXContainerYAML::StaticSamplerYamlDesc >
struct MappingTraits< MachOYAML::FileHeader >
struct MappingTraits< MachOYAML::Object >
struct MappingTraits< MachOYAML::FatHeader >
struct MappingTraits< MachOYAML::FatArch >
struct MappingTraits< MachOYAML::UniversalBinary >
struct MappingTraits< MachOYAML::LoadCommand >
struct MappingTraits< MachOYAML::LinkEditData >
struct MappingTraits< MachOYAML::RebaseOpcode >
struct MappingTraits< MachOYAML::BindOpcode >
struct MappingTraits< MachOYAML::ExportEntry >
struct MappingTraits< MachOYAML::Relocation >
struct MappingTraits< MachOYAML::Section >
struct MappingTraits< MachOYAML::NListEntry >
struct MappingTraits< MachO::build_tool_version >
struct MappingTraits< MachOYAML::DataInCodeEntry >
struct ScalarEnumerationTraits< MachO::LoadCommandType >
struct ScalarEnumerationTraits< MachO::RebaseOpcode >
struct ScalarEnumerationTraits< MachO::BindOpcode >
struct ScalarTraits< char_16 >
struct ScalarTraits< uuid_t >
struct MappingTraits< MachO::dylib >
struct MappingTraits< MachO::fvmlib >
struct MappingTraits< MachO::section >
struct MappingTraits< MachO::section_64 >
struct BlockScalarTraits< MinidumpYAML::BlockStringRef >
struct MappingTraits< std::unique_ptr< MinidumpYAML::Stream > >
struct MappingContextTraits< minidump::MemoryDescriptor, BinaryRef >
struct MappingContextTraits< minidump::MemoryDescriptor_64, BinaryRef >
struct YamlObjectFile
struct MappingTraits< YamlObjectFile >
struct ScalarEnumerationTraits< object::ImageKind >
struct ScalarEnumerationTraits< object::OffloadKind >
struct MappingTraits< OffloadYAML::Binary >
struct MappingTraits< OffloadYAML::Binary::StringEntry >
struct MappingTraits< OffloadYAML::Binary::Member >
struct MappingTraits< WasmYAML::FileHeader >
struct MappingTraits< std::unique_ptr< WasmYAML::Section > >
struct MappingTraits< WasmYAML::Object >
struct MappingTraits< WasmYAML::Import >
struct MappingTraits< WasmYAML::Export >
struct MappingTraits< WasmYAML::Global >
struct ScalarBitSetTraits< WasmYAML::LimitFlags >
struct ScalarBitSetTraits< WasmYAML::SymbolFlags >
struct ScalarEnumerationTraits< WasmYAML::SymbolKind >
struct ScalarBitSetTraits< WasmYAML::SegmentFlags >
struct ScalarEnumerationTraits< WasmYAML::SectionType >
struct MappingTraits< WasmYAML::Signature >
struct MappingTraits< WasmYAML::Table >
struct MappingTraits< WasmYAML::Limits >
struct MappingTraits< WasmYAML::Function >
struct MappingTraits< WasmYAML::Relocation >
struct MappingTraits< WasmYAML::NameEntry >
struct MappingTraits< WasmYAML::ProducerEntry >
struct ScalarEnumerationTraits< WasmYAML::FeaturePolicyPrefix >
struct MappingTraits< WasmYAML::FeatureEntry >
struct MappingTraits< WasmYAML::SegmentInfo >
struct MappingTraits< WasmYAML::LocalDecl >
struct MappingTraits< WasmYAML::InitExpr >
struct MappingTraits< WasmYAML::DataSegment >
struct MappingTraits< WasmYAML::ElemSegment >
struct MappingTraits< WasmYAML::SymbolInfo >
struct MappingTraits< WasmYAML::InitFunction >
struct ScalarEnumerationTraits< WasmYAML::ComdatKind >
struct MappingTraits< WasmYAML::ComdatEntry >
struct MappingTraits< WasmYAML::Comdat >
struct ScalarEnumerationTraits< WasmYAML::ValueType >
struct ScalarEnumerationTraits< WasmYAML::ExportKind >
struct ScalarEnumerationTraits< WasmYAML::TableType >
struct ScalarEnumerationTraits< WasmYAML::Opcode >
struct ScalarEnumerationTraits< WasmYAML::RelocType >
struct MappingTraits< WasmYAML::DylinkImportInfo >
struct MappingTraits< WasmYAML::DylinkExportInfo >
struct ScalarBitSetTraits< XCOFF::SectionTypeFlags >
struct ScalarEnumerationTraits< XCOFF::DwarfSectionSubtypeFlags >
struct ScalarEnumerationTraits< XCOFF::StorageClass >
struct ScalarEnumerationTraits< XCOFF::StorageMappingClass >
struct ScalarEnumerationTraits< XCOFF::SymbolType >
struct ScalarEnumerationTraits< XCOFF::CFileStringType >
struct ScalarEnumerationTraits< XCOFFYAML::AuxSymbolType >
struct MappingTraits< XCOFFYAML::FileHeader >
struct MappingTraits< XCOFFYAML::AuxiliaryHeader >
struct MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >
struct MappingTraits< XCOFFYAML::Symbol >
struct MappingTraits< XCOFFYAML::Relocation >
struct MappingTraits< XCOFFYAML::Section >
struct MappingTraits< XCOFFYAML::StringTable >
struct MappingTraits< XCOFFYAML::Object >
class BinaryRef
Specialized YAMLIO scalar type for representing a binary blob.
struct ScalarTraits< BinaryRef >
struct CustomMappingTraits
This class should be specialized by any type that needs to be converted to/from a YAML mapping in the case where the names of the keys are not known in advance, e.g.
struct ScalarTraits< memprof::GUIDHex64 >
struct MappingTraits< memprof::Frame >
struct CustomMappingTraits< memprof::PortableMemInfoBlock >
struct MappingTraits< memprof::AllocationInfo >
struct MappingTraits< memprof::CallSiteInfo >
struct MappingTraits< memprof::GUIDMemProfRecordPair >
struct MappingTraits< memprof::SourceLocation >
struct MappingTraits< memprof::DataAccessProfRecord >
struct MappingTraits< memprof::YamlDataAccessProfData >
struct MappingTraits< memprof::AllMemProfData >
struct SequenceTraits< SmallVector< memprof::GUIDHex64 > >
class Stream
This class represents a YAML stream potentially containing multiple documents.
class Node
Abstract base class for all Nodes.
class NullNode
A null value.
class ScalarNode
A scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
class BlockScalarNode
A block scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
class KeyValueNode
A key and value pair.
class basic_collection_iterator
This is an iterator abstraction over YAML collections shared by both sequences and maps.
class MappingNode
Represents a YAML map created from either a block map for a flow map.
class SequenceNode
Represents a YAML sequence created from either a block sequence for a flow sequence.
class AliasNode
Represents an alias to a Node with an anchor.
class Document
A YAML Stream is a sequence of Documents.
class document_iterator
Iterator abstraction for Documents over a Stream.
struct EmptyContext
struct MappingContextTraits
This class is similar to MappingTraits<T> but allows you to pass in additional context for each map operation.
struct ScalarEnumerationTraits
This class should be specialized by any integral type that converts to/from a YAML scalar where there is a one-to-one mapping between in-memory values and a string in YAML.
struct ScalarBitSetTraits
This class should be specialized by any integer type that is a union of bit values and the YAML representation is a flow sequence of strings.
struct ScalarTraits
This class should be specialized by type that requires custom conversion to/from a yaml scalar.
struct BlockScalarTraits
This class should be specialized by type that requires custom conversion to/from a YAML literal block scalar.
struct TaggedScalarTraits
This class should be specialized by type that requires custom conversion to/from a YAML scalar with optional tags.
struct SequenceTraits
This class should be specialized by any type that needs to be converted to/from a YAML sequence.
struct SequenceElementTraits
This class should be specialized by any type for which vectors of that type need to be converted to/from a YAML sequence.
struct DocumentListTraits
This class should be specialized by any type that needs to be converted to/from a list of YAML documents.
struct PolymorphicTraits
This class should be specialized by any type that can be represented as a scalar, map, or sequence, decided dynamically.
struct MissingTrait
struct has_ScalarEnumerationTraits
struct has_ScalarBitSetTraits
struct has_ScalarTraits
struct has_BlockScalarTraits
struct has_TaggedScalarTraits
struct has_MappingTraits
struct has_MappingTraits< T, EmptyContext >
struct has_MappingValidateTraits
struct has_MappingValidateTraits< T, EmptyContext >
struct has_MappingEnumInputTraits
struct has_MappingEnumInputTraits< T, EmptyContext >
struct has_SequenceMethodTraits
struct has_CustomMappingTraits
struct has_FlowTraits
struct has_SequenceTraits
struct has_DocumentListTraits
struct has_PolymorphicTraits
struct missingTraits
struct validatedMappingTraits
struct unvalidatedMappingTraits
class IO
struct ScalarTraits< bool >
struct ScalarTraits< StringRef >
struct ScalarTraits< std::string >
struct ScalarTraits< uint8_t >
struct ScalarTraits< uint16_t >
struct ScalarTraits< uint32_t >
struct ScalarTraits< uint64_t >
struct ScalarTraits< int8_t >
struct ScalarTraits< int16_t >
struct ScalarTraits< int32_t >
struct ScalarTraits< int64_t >
struct ScalarTraits< float >
struct ScalarTraits< double >
struct ScalarTraits< support::detail::packed_endian_specific_integral< value_type, endian, alignment >, std::enable_if_t< has_ScalarTraits< value_type >::value > >
struct ScalarEnumerationTraits< support::detail::packed_endian_specific_integral< value_type, endian, alignment >, std::enable_if_t< has_ScalarEnumerationTraits< value_type >::value > >
struct ScalarBitSetTraits< support::detail::packed_endian_specific_integral< value_type, endian, alignment >, std::enable_if_t< has_ScalarBitSetTraits< value_type >::value > >
struct MappingNormalization
struct MappingNormalizationHeap
class Input
The Input class is used to parse a yaml document into in-memory structs and vectors.
class Output
The Output class is used to generate a yaml document from in-memory structs and vectors.
struct ScalarTraits< Hex8 >
Use these types instead of uintXX_t in any mapping to have its yaml output formatted as hexadecimal.
struct ScalarTraits< Hex16 >
struct ScalarTraits< Hex32 >
struct ScalarTraits< Hex64 >
struct ScalarTraits< VersionTuple >
struct IsFlowSequenceBase
struct IsFlowSequenceBase< true >
struct IsResizableBase
struct SequenceTraitsImpl
struct CheckIsBool
struct SequenceTraits< std::vector< T >, std::enable_if_t< CheckIsBool< SequenceElementTraits< T >::flow >::value > >
struct SequenceTraits< std::array< T, N >, std::enable_if_t< CheckIsBool< SequenceElementTraits< T >::flow >::value > >
struct SequenceTraits< SmallVector< T, N >, std::enable_if_t< CheckIsBool< SequenceElementTraits< T >::flow >::value > >
struct SequenceTraits< SmallVectorImpl< T >, std::enable_if_t< CheckIsBool< SequenceElementTraits< T >::flow >::value > >
struct SequenceTraits< MutableArrayRef< T >, std::enable_if_t< CheckIsBool< SequenceElementTraits< T >::flow >::value > >
struct SequenceElementTraits< T, std::enable_if_t< std::is_fundamental_v< T > > >
struct SequenceElementTraits< std::string >
struct SequenceElementTraits< StringRef >
struct SequenceElementTraits< std::pair< std::string, std::string > >
struct StdMapStringCustomMappingTraitsImpl
Implementation of CustomMappingTraits for std::map<std::string, T>.
struct ScalarEnumerationTraits< xray::SledEntry::FunctionKinds >
struct MappingTraits< xray::YAMLXRaySledEntry >
struct ScalarEnumerationTraits< xray::RecordTypes >
struct MappingTraits< xray::YAMLXRayFileHeader >
struct MappingTraits< xray::YAMLXRayRecord >
struct MappingTraits< llvm::xray::YAMLXRayTrace >
struct PolymorphicTraits< DocNode >
YAMLIO for DocNode.
struct TaggedScalarTraits< ScalarDocNode >
YAMLIO for ScalarDocNode.
struct CustomMappingTraits< MapDocNode >
YAMLIO for MapDocNode.
struct SequenceTraits< ArrayDocNode >
YAMLIO for ArrayNode.
struct MappingTraits< HashNodeStable >
struct CustomMappingTraits< IdHashNodeStableMapTy >
struct MappingTraits< IndexPairHash >
struct MappingTraits< StableFunction >
struct BlockScalarTraits< Module >
This struct serializes the LLVM IR module.
struct CallSiteYAML
struct FunctionYAML
struct FunctionsYAML
struct MappingTraits< CallSiteYAML >
struct MappingTraits< FunctionYAML >
struct MappingTraits< FunctionsYAML >
struct ScalarEnumerationTraits< IFSSymbolType >
YAML traits for ELFSymbolType.
struct ScalarTraits< IFSEndiannessType >
struct ScalarTraits< IFSBitWidthType >
struct MappingTraits< IFSTarget >
struct MappingTraits< IFSSymbol >
YAML traits for ELFSymbol.
struct MappingTraits< IFSStub >
YAML traits for ELFStub objects.
struct MappingTraits< IFSStubTriple >
YAML traits for ELFStubTriple objects.
struct MappingTraits< LocalVariableAddrRange >
struct MappingTraits< LocalVariableAddrGap >
struct MappingTraits< SymbolRecordBase >
struct MappingTraits< LeafRecordBase >
struct MappingTraits< MemberRecordBase >
struct ScalarTraits< StOtherPiece >
struct SequenceElementTraits< StOtherPiece >
struct ScalarTraits< ELFYAML::YAMLFlowString >
struct SequenceElementTraits< ELFYAML::YAMLFlowString >
struct ScalarTraits< FixedSizeHex< N > >
struct ScalarTraits< FixedSizeString< N > >
struct NSectionFlags
struct MappingTraits< InstrProfCorrelator::CorrelationData >
struct MappingTraits< InstrProfCorrelator::Probe >
struct SequenceElementTraits< InstrProfCorrelator::Probe >
struct MappingTraits< SerializableCtxRepresentation >
struct MappingTraits< SerializableRootRepresentation >
struct MappingTraits< SerializableProfileRepresentation >
struct MappingTraits< SerializableFlatProfileRepresentation >
struct MappingTraits< remarks::Remark * >
struct MappingTraits< RemarkLocation >
struct StringBlockVal
Helper struct for multiline string block literals.
struct BlockScalarTraits< StringBlockVal >
struct SequenceTraits< ArrayRef< T > >
ArrayRef is not really compatible with the YAMLTraits.
struct MappingTraits< Argument >
Implement this as a mapping for now to get proper quotation for the value.
struct ScalarEnumerationTraits< AccessQualifier >
struct ScalarEnumerationTraits< AddressSpaceQualifier >
struct ScalarEnumerationTraits< ValueKind >
struct ScalarEnumerationTraits< ValueType >
struct MappingTraits< Kernel::Attrs::Metadata >
struct MappingTraits< Kernel::Arg::Metadata >
struct MappingTraits< Kernel::CodeProps::Metadata >
struct MappingTraits< Kernel::DebugProps::Metadata >
struct MappingTraits< Kernel::Metadata >
struct MappingTraits< HSAMD::Metadata >
struct Token
Token - A single YAML token.
class Scanner
Scans YAML tokens from a MemoryBuffer.
struct AArch64FunctionInfo
struct MappingTraits< AArch64FunctionInfo >
struct SIArgument
struct MappingTraits< SIArgument >
struct SIArgumentInfo
struct MappingTraits< SIArgumentInfo >
struct SIMode
struct MappingTraits< SIMode >
struct SIMachineFunctionInfo
struct MappingTraits< SIMachineFunctionInfo >
struct ARMFunctionInfo
struct MappingTraits< ARMFunctionInfo >
struct RISCVMachineFunctionInfo
struct MappingTraits< RISCVMachineFunctionInfo >
struct WebAssemblyFunctionInfo
struct MappingTraits< WebAssemblyFunctionInfo >
struct CustomMappingTraits< BBNumberMap >
struct ScalarEnumerationTraits< AMXProgModelEnum >
struct X86MachineFunctionInfo
struct MappingTraits< X86MachineFunctionInfo >
struct MappingTraits< ExportSection >
struct MappingTraits< UndefinedSection >
struct MappingTraits< SymbolSection >
struct MappingTraits< UmbrellaSection >
struct MappingTraits< UUIDv4 >
struct MappingContextTraits< MetadataSection, MetadataSection::Option >
struct ScalarBitSetTraits< TBDFlags >
struct ScalarTraits< Target >
struct MappingTraits< const InterfaceFile * >
struct DocumentListTraits< std::vector< const MachO::InterfaceFile * > >
struct ScalarTraits< FlowStringRef >
struct ScalarEnumerationTraits< MachO::ObjCConstraintType >
struct ScalarTraits< MachO::PlatformSet >
struct ScalarBitSetTraits< MachO::ArchitectureSet >
struct ScalarTraits< MachO::Architecture >
struct ScalarTraits< MachO::PackedVersion >
struct ScalarTraits< SwiftVersion >
struct ScalarTraits< UUID >
Typedefs
using char_16 = char[16]
using uuid_t = raw_ostream::uuid_t
using ErrorHandler = llvm::function_ref<void(const Twine &Msg)>
template<typename T>
using check_resize_t = decltype(std::declval<T>().resize(0))
using BBNumberMap = DenseMap<int, int>
Enumerations
enum class NodeKind : uint8_t { Scalar , Map , Sequence }
enum class QuotingType { None , Single , Double }
Describe which type of quotes should be used when quoting is necessary.
Functions
bool operator== (const BinaryRef &LHS, const BinaryRef &RHS)
LLVM_ABI bool yaml2archive (ArchYAML::Archive &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2coff (COFFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2goff (GOFFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2elf (ELFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH, uint64_t MaxSize)
LLVM_ABI bool yaml2macho (YamlObjectFile &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2minidump (MinidumpYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2offload (OffloadYAML::Binary &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2wasm (WasmYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2xcoff (XCOFFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool yaml2dxcontainer (DXContainerYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
LLVM_ABI bool convertYAML (Input &YIn, raw_ostream &Out, ErrorHandler ErrHandler, unsigned DocNum=1, uint64_t MaxSize=UINT64_MAX)
LLVM_ABI std::unique_ptr< object::ObjectFile > yaml2ObjectFile (SmallVectorImpl< char > &Storage, StringRef Yaml, ErrorHandler ErrHandler)
Convenience function for tests.
LLVM_ABI bool dumpTokens (StringRef Input, raw_ostream &)
Dump all the tokens in this stream to OS.
LLVM_ABI bool scanTokens (StringRef Input)
Scans all tokens in input without outputting anything.
LLVM_ABI std::string escape (StringRef Input, bool EscapePrintable=true)
Escape Input for a double quoted scalar; if EscapePrintable is true, all UTF8 sequences will be escaped, if EscapePrintable is false, those UTF8 sequences encoding printable unicode scalars will not be escaped, but emitted verbatim.
LLVM_ABI std::optional< bool > parseBool (StringRef S)
Parse S as a bool according to https://yaml.org/type/bool.html.
template<class CollectionType>
CollectionType::iterator begin (CollectionType &C)
template<class CollectionType>
void skip (CollectionType &C)
bool isNumeric (StringRef S)
bool isNull (StringRef S)
bool isBool (StringRef S)
QuotingType needsQuotes (StringRef S, bool ForcePreserveAsString=true)
template<typename T>
std::enable_if_t< has_ScalarEnumerationTraits< T >::value, void > yamlize (IO &io, T &Val, bool, EmptyContext &Ctx)
template<typename T>
std::enable_if_t< has_ScalarBitSetTraits< T >::value, void > yamlize (IO &io, T &Val, bool, EmptyContext &Ctx)
template<typename T>
std::enable_if_t< has_ScalarTraits< T >::value, void > yamlize (IO &io, T &Val, bool, EmptyContext &Ctx)
template<typename T>
std::enable_if_t< has_BlockScalarTraits< T >::value, void > yamlize (IO &YamlIO, T &Val, bool, EmptyContext &Ctx)
template<typename T>
std::enable_if_t< has_TaggedScalarTraits< T >::value, void > yamlize (IO &io, T &Val, bool, EmptyContext &Ctx)
template<typename T, typename Context>
std::enable_if_t< validatedMappingTraits< T, Context >::value, void > yamlize (IO &io, T &Val, bool, Context &Ctx)
template<typename T, typename Context>
bool yamlizeMappingEnumInput (IO &io, T &Val)
template<typename T, typename Context>
std::enable_if_t< unvalidatedMappingTraits< T, Context >::value, void > yamlize (IO &io, T &Val, bool, Context &Ctx)
template<typename T>
std::enable_if_t< has_CustomMappingTraits< T >::value, void > yamlize (IO &io, T &Val, bool, EmptyContext &Ctx)
template<typename T>
std::enable_if_t< has_PolymorphicTraits< T >::value, void > yamlize (IO &io, T &Val, bool, EmptyContext &Ctx)
template<typename T>
std::enable_if_t< missingTraits< T, EmptyContext >::value, void > yamlize (IO &io, T &Val, bool, EmptyContext &Ctx)
template<typename T, typename Context>
std::enable_if_t< has_SequenceTraits< T >::value, void > yamlize (IO &io, T &Seq, bool, Context &Ctx)
template<typename T>
std::enable_if_t< has_DocumentListTraits< T >::value, Input & > operator>> (Input &yin, T &docList)
template<typename T>
std::enable_if_t< has_MappingTraits< T, EmptyContext >::value, Input & > operator>> (Input &yin, T &docMap)
template<typename T>
std::enable_if_t< has_SequenceTraits< T >::value, Input & > operator>> (Input &yin, T &docSeq)
template<typename T>
std::enable_if_t< has_BlockScalarTraits< T >::value, Input & > operator>> (Input &In, T &Val)
template<typename T>
std::enable_if_t< has_CustomMappingTraits< T >::value, Input & > operator>> (Input &In, T &Val)
template<typename T>
std::enable_if_t< has_PolymorphicTraits< T >::value, Input & > operator>> (Input &In, T &Val)
template<typename T>
std::enable_if_t< missingTraits< T, EmptyContext >::value, Input & > operator>> (Input &yin, T &docSeq)
template<typename T>
std::enable_if_t< has_DocumentListTraits< T >::value, Output & > operator<< (Output &yout, T &docList)
template<typename T>
std::enable_if_t< has_MappingTraits< T, EmptyContext >::value, Output & > operator<< (Output &yout, T &map)
template<typename T>
std::enable_if_t< has_SequenceTraits< T >::value, Output & > operator<< (Output &yout, T &seq)
template<typename T>
std::enable_if_t< has_BlockScalarTraits< T >::value, Output & > operator<< (Output &Out, T &Val)
template<typename T>
std::enable_if_t< has_CustomMappingTraits< T >::value, Output & > operator<< (Output &Out, T &Val)
template<typename T>
std::enable_if_t< has_PolymorphicTraits< T >::value, Output & > operator<< (Output &Out, T &Val)
template<typename T>
std::enable_if_t< missingTraits< T, EmptyContext >::value, Output & > operator<< (Output &yout, T &seq)
template<typename T, typename M>
void mapLoadConfigMember (IO &IO, T &LoadConfig, const char *Name, M &Member)
template<typename T>
void mapLoadConfig (IO &IO, T &LoadConfig)
static void commonSectionMapping (IO &IO, ELFYAML::Section &Section)
static void sectionMapping (IO &IO, ELFYAML::DynamicSection &Section)
static void sectionMapping (IO &IO, ELFYAML::RawContentSection &Section)
static void sectionMapping (IO &IO, ELFYAML::BBAddrMapSection &Section)
static void sectionMapping (IO &IO, ELFYAML::StackSizesSection &Section)
static void sectionMapping (IO &IO, ELFYAML::HashSection &Section)
static void sectionMapping (IO &IO, ELFYAML::NoteSection &Section)
static void sectionMapping (IO &IO, ELFYAML::GnuHashSection &Section)
static void sectionMapping (IO &IO, ELFYAML::NoBitsSection &Section)
static void sectionMapping (IO &IO, ELFYAML::VerdefSection &Section)
static void sectionMapping (IO &IO, ELFYAML::SymverSection &Section)
static void sectionMapping (IO &IO, ELFYAML::VerneedSection &Section)
static void sectionMapping (IO &IO, ELFYAML::RelocationSection &Section)
static void sectionMapping (IO &IO, ELFYAML::RelrSection &Section)
static void groupSectionMapping (IO &IO, ELFYAML::GroupSection &Group)
static void sectionMapping (IO &IO, ELFYAML::SymtabShndxSection &Section)
static void sectionMapping (IO &IO, ELFYAML::AddrsigSection &Section)
static void fillMapping (IO &IO, ELFYAML::Fill &Fill)
static void sectionHeaderTableMapping (IO &IO, ELFYAML::SectionHeaderTable &SHT)
static void sectionMapping (IO &IO, ELFYAML::LinkerOptionsSection &Section)
static void sectionMapping (IO &IO, ELFYAML::DependentLibrariesSection &Section)
static void sectionMapping (IO &IO, ELFYAML::CallGraphProfileSection &Section)
static void sectionMapping (IO &IO, ELFYAML::ARMIndexTableSection &Section)
static void sectionMapping (IO &IO, ELFYAML::MipsABIFlags &Section)
static StringRef getStringValue (IO &IO, const char *Key)
static void setStringValue (IO &IO, const char *Key, StringRef Val)
static bool isInteger (StringRef Val)
template<typename StructType>
void mapLoadCommandData (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::segment_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::segment_command_64 > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::dylib_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::rpath_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::dylinker_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_framework_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_umbrella_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_client_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_library_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::build_version_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
static void commonSectionMapping (IO &IO, WasmYAML::Section &Section)
static void sectionMapping (IO &IO, WasmYAML::DylinkSection &Section)
static void sectionMapping (IO &IO, WasmYAML::NameSection &Section)
static void sectionMapping (IO &IO, WasmYAML::LinkingSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ProducersSection &Section)
static void sectionMapping (IO &IO, WasmYAML::TargetFeaturesSection &Section)
static void sectionMapping (IO &IO, WasmYAML::CustomSection &Section)
static void sectionMapping (IO &IO, WasmYAML::TypeSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ImportSection &Section)
static void sectionMapping (IO &IO, WasmYAML::FunctionSection &Section)
static void sectionMapping (IO &IO, WasmYAML::TableSection &Section)
static void sectionMapping (IO &IO, WasmYAML::MemorySection &Section)
static void sectionMapping (IO &IO, WasmYAML::TagSection &Section)
static void sectionMapping (IO &IO, WasmYAML::GlobalSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ExportSection &Section)
static void sectionMapping (IO &IO, WasmYAML::StartSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ElemSection &Section)
static void sectionMapping (IO &IO, WasmYAML::CodeSection &Section)
static void sectionMapping (IO &IO, WasmYAML::DataSection &Section)
static void sectionMapping (IO &IO, WasmYAML::DataCountSection &Section)
static void auxSymMapping (IO &IO, XCOFFYAML::CsectAuxEnt &AuxSym, bool Is64)
static void auxSymMapping (IO &IO, XCOFFYAML::FileAuxEnt &AuxSym)
static void auxSymMapping (IO &IO, XCOFFYAML::BlockAuxEnt &AuxSym, bool Is64)
static void auxSymMapping (IO &IO, XCOFFYAML::FunctionAuxEnt &AuxSym, bool Is64)
static void auxSymMapping (IO &IO, XCOFFYAML::ExcpetionAuxEnt &AuxSym)
static void auxSymMapping (IO &IO, XCOFFYAML::SectAuxEntForDWARF &AuxSym)
static void auxSymMapping (IO &IO, XCOFFYAML::SectAuxEntForStat &AuxSym)
template<typename AuxEntT>
static void ResetAuxSym (IO &IO, std::unique_ptr< XCOFFYAML::AuxSymbolEnt > &AuxSym)
Typedef Documentation
BBNumberMap
using llvm::yaml::BBNumberMap = DenseMap<int, int>
Definition at line 180 of file WebAssemblyMachineFunctionInfo.h.
char_16
using llvm::yaml::char_16 = char[16]
Definition at line 298 of file MachOYAML.h.
check_resize_t
template<typename T> using llvm::yaml::check_resize_t = decltype(std::declval<T>().resize(0))
Definition at line 1843 of file YAMLTraits.h.
ErrorHandler
using llvm::yaml::ErrorHandler = llvm::function_ref<void(const Twine &Msg)>
Definition at line 68 of file yaml2obj.h.
uuid_t
using llvm::yaml::uuid_t = raw_ostream::uuid_t
Definition at line 308 of file MachOYAML.h.
Enumeration Type Documentation
NodeKind
enum class llvm::yaml::NodeKind : uint8_t strong
Enumerator
Scalar
Map
Sequence
Definition at line 44 of file YAMLTraits.h.
QuotingType
enum class llvm::yaml::QuotingType strong
Describe which type of quotes should be used when quoting is necessary.
Some non-printable characters need to be double-quoted, while some others are fine with simple-quoting, and some don't need any quoting.
Enumerator
None
Single
Double
Definition at line 131 of file YAMLTraits.h.
Function Documentation
auxSymMapping() [1/7]
void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::BlockAuxEnt & AuxSym, bool Is64) static
Definition at line 280 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::BlockAuxEnt::LineNum, llvm::XCOFFYAML::BlockAuxEnt::LineNumHi, llvm::XCOFFYAML::BlockAuxEnt::LineNumLo, and llvm::yaml::IO::mapOptional().
auxSymMapping() [2/7]
void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::CsectAuxEnt & AuxSym, bool Is64) static
Definition at line 258 of file XCOFFYAML.cpp.
References llvm::yaml::IO::mapOptional(), llvm::XCOFFYAML::CsectAuxEnt::ParameterHashIndex, llvm::XCOFFYAML::CsectAuxEnt::SectionOrLength, llvm::XCOFFYAML::CsectAuxEnt::SectionOrLengthHi, llvm::XCOFFYAML::CsectAuxEnt::SectionOrLengthLo, llvm::XCOFFYAML::CsectAuxEnt::StabInfoIndex, llvm::XCOFFYAML::CsectAuxEnt::StabSectNum, llvm::XCOFFYAML::CsectAuxEnt::StorageMappingClass, llvm::XCOFFYAML::CsectAuxEnt::SymbolAlignment, llvm::XCOFFYAML::CsectAuxEnt::SymbolAlignmentAndType, llvm::XCOFFYAML::CsectAuxEnt::SymbolType, and llvm::XCOFFYAML::CsectAuxEnt::TypeChkSectNum.
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping().
auxSymMapping() [3/7]
void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::ExcpetionAuxEnt & AuxSym) static
Definition at line 298 of file XCOFFYAML.cpp.
References llvm::yaml::IO::mapOptional(), llvm::XCOFFYAML::ExcpetionAuxEnt::OffsetToExceptionTbl, llvm::XCOFFYAML::ExcpetionAuxEnt::SizeOfFunction, and llvm::XCOFFYAML::ExcpetionAuxEnt::SymIdxOfNextBeyond.
auxSymMapping() [4/7]
void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::FileAuxEnt & AuxSym) static
Definition at line 275 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::FileAuxEnt::FileNameOrString, llvm::XCOFFYAML::FileAuxEnt::FileStringType, and llvm::yaml::IO::mapOptional().
auxSymMapping() [5/7]
void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::FunctionAuxEnt & AuxSym, bool Is64) static
Definition at line 289 of file XCOFFYAML.cpp.
References llvm::yaml::IO::mapOptional(), llvm::XCOFFYAML::FunctionAuxEnt::OffsetToExceptionTbl, llvm::XCOFFYAML::FunctionAuxEnt::PtrToLineNum, llvm::XCOFFYAML::FunctionAuxEnt::SizeOfFunction, and llvm::XCOFFYAML::FunctionAuxEnt::SymIdxOfNextBeyond.
auxSymMapping() [6/7]
void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::SectAuxEntForDWARF & AuxSym) static
Definition at line 304 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::SectAuxEntForDWARF::LengthOfSectionPortion, llvm::yaml::IO::mapOptional(), and llvm::XCOFFYAML::SectAuxEntForDWARF::NumberOfRelocEnt.
auxSymMapping() [7/7]
void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::SectAuxEntForStat & AuxSym) static
Definition at line 309 of file XCOFFYAML.cpp.
References llvm::yaml::IO::mapOptional(), llvm::XCOFFYAML::SectAuxEntForStat::NumberOfLineNum, llvm::XCOFFYAML::SectAuxEntForStat::NumberOfRelocEnt, and llvm::XCOFFYAML::SectAuxEntForStat::SectionLength.
begin()
template<class CollectionType> CollectionType::iterator llvm::yaml::begin (CollectionType & C)
Definition at line 397 of file YAMLParser.h.
References assert(), and llvm::CallingConv::C.
Referenced by llvm::yaml::MappingNode::begin(), llvm::yaml::SequenceNode::begin(), llvm::yaml::MappingNode::yaml::begin, and llvm::yaml::SequenceNode::yaml::begin.
commonSectionMapping() [1/2]
void llvm::yaml::commonSectionMapping (IO & IO, ELFYAML::Section & Section) static
Definition at line 1412 of file ELFYAML.cpp.
References assert(), llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and llvm::yaml::IO::outputting().
Referenced by groupSectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), sectionMapping(), and sectionMapping().
commonSectionMapping() [2/2]
void llvm::yaml::commonSectionMapping (IO & IO, WasmYAML::Section & Section) static
Definition at line 46 of file WasmYAML.cpp.
References llvm::yaml::IO::mapOptional(), and llvm::yaml::IO::mapRequired().
convertYAML()
bool llvm::yaml::convertYAML (yaml::Input & YIn, raw_ostream & Out, ErrorHandler ErrHandler, unsigned DocNum = 1, uint64_t MaxSize = UINT64_MAX)
Definition at line 20 of file yaml2obj.cpp.
References llvm::yaml::YamlObjectFile::Arch, llvm::yaml::YamlObjectFile::Coff, data, llvm::yaml::YamlObjectFile::DXContainer, llvm::yaml::YamlObjectFile::Elf, llvm::yaml::Input::error(), llvm::yaml::YamlObjectFile::FatMachO, llvm::yaml::YamlObjectFile::Goff, llvm::yaml::YamlObjectFile::MachO, llvm::yaml::YamlObjectFile::Minidump, llvm::yaml::Input::nextDocument(), llvm::yaml::YamlObjectFile::Offload, llvm::yaml::YamlObjectFile::Wasm, llvm::yaml::YamlObjectFile::Xcoff, yaml2archive(), yaml2coff(), yaml2dxcontainer(), yaml2elf(), yaml2goff(), yaml2macho(), yaml2minidump(), yaml2offload(), yaml2wasm(), and yaml2xcoff().
Referenced by yaml2ObjectFile().
dumpTokens()
bool llvm::yaml::dumpTokens (StringRef Input, raw_ostream & OS)
Dump all the tokens in this stream to OS.
Returns
true if there was an error, false otherwise.
Definition at line 607 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), SM(), T, llvm::yaml::Token::TK_Alias, llvm::yaml::Token::TK_Anchor, llvm::yaml::Token::TK_BlockEnd, llvm::yaml::Token::TK_BlockEntry, llvm::yaml::Token::TK_BlockMappingStart, llvm::yaml::Token::TK_BlockScalar, llvm::yaml::Token::TK_BlockSequenceStart, llvm::yaml::Token::TK_DocumentEnd, llvm::yaml::Token::TK_DocumentStart, llvm::yaml::Token::TK_Error, llvm::yaml::Token::TK_FlowEntry, llvm::yaml::Token::TK_FlowMappingEnd, llvm::yaml::Token::TK_FlowMappingStart, llvm::yaml::Token::TK_FlowSequenceEnd, llvm::yaml::Token::TK_FlowSequenceStart, llvm::yaml::Token::TK_Key, llvm::yaml::Token::TK_Scalar, llvm::yaml::Token::TK_StreamEnd, llvm::yaml::Token::TK_StreamStart, llvm::yaml::Token::TK_Tag, llvm::yaml::Token::TK_TagDirective, llvm::yaml::Token::TK_Value, and llvm::yaml::Token::TK_VersionDirective.
escape()
std::string llvm::yaml::escape (StringRef Input, bool EscapePrintable = true)
Escape Input for a double quoted scalar; if EscapePrintable is true, all UTF8 sequences will be escaped, if EscapePrintable is false, those UTF8 sequences encoding printable unicode scalars will not be escaped, but emitted verbatim.
Definition at line 704 of file YAMLParser.cpp.
References llvm::append_range(), decodeUTF8(), encodeUTF8(), and llvm::sys::unicode::isPrintable().
fillMapping()
void llvm::yaml::fillMapping (IO & IO, ELFYAML::Fill & Fill) static
Definition at line 1545 of file ELFYAML.cpp.
References llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), llvm::ELFYAML::Chunk::Name, llvm::ELFYAML::Chunk::Offset, llvm::ELFYAML::Fill::Pattern, and llvm::ELFYAML::Fill::Size.
getStringValue()
StringRef llvm::yaml::getStringValue (IO & IO, const char * Key) static
Definition at line 1606 of file ELFYAML.cpp.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::yaml::IO::mapRequired().
groupSectionMapping()
void llvm::yaml::groupSectionMapping (IO & IO, ELFYAML::GroupSection & Group) static
Definition at line 1529 of file ELFYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), llvm::ELFYAML::GroupSection::Members, and llvm::ELFYAML::GroupSection::Signature.
isBool()
bool llvm::yaml::isBool (StringRef S) inline
Definition at line 574 of file YAMLTraits.h.
Referenced by needsQuotes().
isInteger()
bool llvm::yaml::isInteger (StringRef Val) static
Definition at line 1616 of file ELFYAML.cpp.
References llvm::StringRef::getAsInteger().
isNull()
bool llvm::yaml::isNull (StringRef S) inline
Definition at line 570 of file YAMLTraits.h.
Referenced by needsQuotes().
isNumeric()
bool llvm::yaml::isNumeric (StringRef S) inline
Definition at line 475 of file YAMLTraits.h.
References assert(), Default, llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::find_first_not_of(), llvm::StringRef::front(), llvm::StringRef::npos, llvm::StringRef::size(), llvm::StringRef::starts_with(), and llvm::CallingConv::Tail.
Referenced by needsQuotes().
mapLoadCommandData()
template<typename StructType> void llvm::yaml::mapLoadCommandData (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 217 of file MachOYAML.cpp.
References mapLoadCommandData().
Referenced by mapLoadCommandData(), mapLoadCommandData< MachO::build_version_command >(), mapLoadCommandData< MachO::dylib_command >(), mapLoadCommandData< MachO::dylinker_command >(), mapLoadCommandData< MachO::rpath_command >(), mapLoadCommandData< MachO::segment_command >(), mapLoadCommandData< MachO::segment_command_64 >(), mapLoadCommandData< MachO::sub_client_command >(), mapLoadCommandData< MachO::sub_framework_command >(), mapLoadCommandData< MachO::sub_library_command >(), and mapLoadCommandData< MachO::sub_umbrella_command >().
mapLoadCommandData< MachO::build_version_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::build_version_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 274 of file MachOYAML.cpp.
References mapLoadCommandData(), llvm::yaml::IO::mapOptional(), and llvm::MachOYAML::LoadCommand::Tools.
mapLoadCommandData< MachO::dylib_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::dylib_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 232 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content, mapLoadCommandData(), and llvm::yaml::IO::mapOptional().
mapLoadCommandData< MachO::dylinker_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::dylinker_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 244 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content, mapLoadCommandData(), and llvm::yaml::IO::mapOptional().
mapLoadCommandData< MachO::rpath_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::rpath_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 238 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content, mapLoadCommandData(), and llvm::yaml::IO::mapOptional().
mapLoadCommandData< MachO::segment_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::segment_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 220 of file MachOYAML.cpp.
References mapLoadCommandData(), llvm::yaml::IO::mapOptional(), and llvm::MachOYAML::LoadCommand::Sections.
mapLoadCommandData< MachO::segment_command_64 >()
template<> void llvm::yaml::mapLoadCommandData< MachO::segment_command_64 > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 226 of file MachOYAML.cpp.
References mapLoadCommandData(), llvm::yaml::IO::mapOptional(), and llvm::MachOYAML::LoadCommand::Sections.
mapLoadCommandData< MachO::sub_client_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_client_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 262 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content, mapLoadCommandData(), and llvm::yaml::IO::mapOptional().
mapLoadCommandData< MachO::sub_framework_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_framework_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 250 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content, mapLoadCommandData(), and llvm::yaml::IO::mapOptional().
mapLoadCommandData< MachO::sub_library_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_library_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 268 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content, mapLoadCommandData(), and llvm::yaml::IO::mapOptional().
mapLoadCommandData< MachO::sub_umbrella_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_umbrella_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 256 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content, mapLoadCommandData(), and llvm::yaml::IO::mapOptional().
mapLoadConfig()
template<typename T> void llvm::yaml::mapLoadConfig (IO & IO, T & LoadConfig)
Definition at line 589 of file COFFYAML.cpp.
References llvm::yaml::IO::mapOptional(), MCase, llvm::yaml::IO::setError(), and T.
Referenced by llvm::yaml::MappingTraits< object::coff_load_configuration32 >::mapping(), and llvm::yaml::MappingTraits< object::coff_load_configuration64 >::mapping().
mapLoadConfigMember()
template<typename T, typename M> void llvm::yaml::mapLoadConfigMember (IO & IO, T & LoadConfig, const char * Name, M & Member)
Definition at line 581 of file COFFYAML.cpp.
References llvm::yaml::IO::mapOptional(), and T.
needsQuotes()
QuotingType llvm::yaml::needsQuotes (StringRef S, bool ForcePreserveAsString = true) inline
Definition at line 589 of file YAMLTraits.h.
References llvm::StringRef::back(), llvm::CallingConv::C, Double, llvm::StringRef::empty(), llvm::StringRef::front(), isBool(), isNull(), isNumeric(), None, and Single.
Referenced by llvm::yaml::ScalarTraits< BinaryRef >::mustQuote(), llvm::yaml::ScalarTraits< char_16 >::mustQuote(), llvm::yaml::ScalarTraits< FixedSizeString< N > >::mustQuote(), llvm::yaml::ScalarTraits< FlowStringValue >::mustQuote(), llvm::yaml::ScalarTraits< FrameIndex >::mustQuote(), llvm::yaml::ScalarTraits< std::string >::mustQuote(), llvm::yaml::ScalarTraits< StringRef >::mustQuote(), llvm::yaml::ScalarTraits< StringValue >::mustQuote(), llvm::yaml::ScalarTraits< uuid_t >::mustQuote(), and llvm::PrintStatisticsJSON().
operator<<() [1/7]
template<typename T> std::enable_if_t< has_BlockScalarTraits< T >::value, Output & > llvm::yaml::operator<< (Output & Out, T & Val) inline
Definition at line 1731 of file YAMLTraits.h.
operator<<() [2/7]
template<typename T> std::enable_if_t< has_CustomMappingTraits< T >::value, Output & > llvm::yaml::operator<< (Output & Out, T & Val) inline
Definition at line 1731 of file YAMLTraits.h.
operator<<() [3/7]
template<typename T> std::enable_if_t< has_PolymorphicTraits< T >::value, Output & > llvm::yaml::operator<< (Output & Out, T & Val) inline
Definition at line 1731 of file YAMLTraits.h.
operator<<() [4/7]
template<typename T> std::enable_if_t< has_DocumentListTraits< T >::value, Output & > llvm::yaml::operator<< (Output & yout, T & docList) inline
Definition at line 1731 of file YAMLTraits.h.
References T.
operator<<() [5/7]
template<typename T> std::enable_if_t< has_MappingTraits< T, EmptyContext >::value, Output & > llvm::yaml::operator<< (Output & yout, T & map) inline
Definition at line 1731 of file YAMLTraits.h.
operator<<() [6/7]
template<typename T> std::enable_if_t< has_SequenceTraits< T >::value, Output & > llvm::yaml::operator<< (Output & yout, T & seq) inline
Definition at line 1731 of file YAMLTraits.h.
operator<<() [7/7]
template<typename T> std::enable_if_t< missingTraits< T, EmptyContext >::value, Output & > llvm::yaml::operator<< (Output & yout, T & seq) inline
Definition at line 1731 of file YAMLTraits.h.
operator==()
bool llvm::yaml::operator== (const BinaryRef & LHS, const BinaryRef & RHS) inline
Definition at line 99 of file YAML.h.
operator>>() [1/7]
template<typename T> std::enable_if_t< has_PolymorphicTraits< T >::value, Input & > llvm::yaml::operator>> (Input & In, T & Val) inline
Definition at line 1721 of file YAMLTraits.h.
References T, and yamlize().
operator>>() [2/7]
template<typename T> std::enable_if_t< has_CustomMappingTraits< T >::value, Input & > llvm::yaml::operator>> (Input & In, T & Val) inline
Definition at line 1711 of file YAMLTraits.h.
References T, and yamlize().
operator>>() [3/7]
template<typename T> std::enable_if_t< has_BlockScalarTraits< T >::value, Input & > llvm::yaml::operator>> (Input & In, T & Val) inline
Definition at line 1701 of file YAMLTraits.h.
References T, and yamlize().
operator>>() [4/7]
template<typename T> std::enable_if_t< has_DocumentListTraits< T >::value, Input & > llvm::yaml::operator>> (Input & yin, T & docList) inline
Definition at line 1664 of file YAMLTraits.h.
References llvm::yaml::Input::error(), llvm::yaml::Input::nextDocument(), llvm::yaml::Input::setCurrentDocument(), T, and yamlize().
operator>>() [5/7]
template<typename T> std::enable_if_t< has_MappingTraits< T, EmptyContext >::value, Input & > llvm::yaml::operator>> (Input & yin, T & docMap) inline
Definition at line 1680 of file YAMLTraits.h.
References llvm::yaml::Input::setCurrentDocument(), T, and yamlize().
operator>>() [6/7]
template<typename T> std::enable_if_t< missingTraits< T, EmptyContext >::value, Input & > llvm::yaml::operator>> (Input & yin, T & docSeq) inline
Definition at line 1731 of file YAMLTraits.h.
operator>>() [7/7]
template<typename T> std::enable_if_t< has_SequenceTraits< T >::value, Input & > llvm::yaml::operator>> (Input & yin, T & docSeq) inline
Definition at line 1691 of file YAMLTraits.h.
References llvm::yaml::Input::setCurrentDocument(), T, and yamlize().
parseBool()
std::optional< bool > llvm::yaml::parseBool (StringRef S)
Parse S as a bool according to https://yaml.org/type/bool.html.
Definition at line 771 of file YAMLParser.cpp.
References llvm::StringRef::drop_front(), llvm::StringRef::front(), and llvm::StringRef::size().
ResetAuxSym()
template<typename AuxEntT> void llvm::yaml::ResetAuxSym (IO & IO, std::unique_ptr< XCOFFYAML::AuxSymbolEnt > & AuxSym) static
Definition at line 316 of file XCOFFYAML.cpp.
References llvm::yaml::IO::outputting().
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping().
scanTokens()
bool llvm::yaml::scanTokens (StringRef Input)
Scans all tokens in input without outputting anything.
This is used for benchmarking the tokenizer.
Returns
true if there was an error, false otherwise.
Definition at line 691 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), SM(), T, llvm::yaml::Token::TK_Error, and llvm::yaml::Token::TK_StreamEnd.
sectionHeaderTableMapping()
void llvm::yaml::sectionHeaderTableMapping (IO & IO, ELFYAML::SectionHeaderTable & SHT) static
Definition at line 1552 of file ELFYAML.cpp.
References llvm::ELFYAML::SectionHeaderTable::Excluded, llvm::yaml::IO::mapOptional(), llvm::ELFYAML::SectionHeaderTable::NoHeaders, llvm::ELFYAML::Chunk::Offset, and llvm::ELFYAML::SectionHeaderTable::Sections.
sectionMapping() [1/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::AddrsigSection & Section) static
Definition at line 1540 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [2/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::ARMIndexTableSection & Section) static
Definition at line 1581 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [3/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::BBAddrMapSection & Section) static
Definition at line 1460 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [4/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::CallGraphProfileSection & Section) static
Definition at line 1571 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [5/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::DependentLibrariesSection & Section) static
Definition at line 1565 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [6/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::DynamicSection & Section) static
Definition at line 1439 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< WasmYAML::Section > >::mapping().
sectionMapping() [7/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::GnuHashSection & Section) static
Definition at line 1490 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [8/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::HashSection & Section) static
Definition at line 1472 of file ELFYAML.cpp.
References assert(), commonSectionMapping(), llvm::yaml::IO::mapOptional(), and llvm::yaml::IO::outputting().
sectionMapping() [9/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::LinkerOptionsSection & Section) static
Definition at line 1560 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [10/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::MipsABIFlags & Section) static
Definition at line 1586 of file ELFYAML.cpp.
References llvm::Mips::AFL_EXT_NONE, llvm::Mips::AFL_REG_NONE, commonSectionMapping(), llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), and llvm::Mips::Val_GNU_MIPS_ABI_FP_ANY.
sectionMapping() [11/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::NoBitsSection & Section) static
Definition at line 1497 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [12/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::NoteSection & Section) static
Definition at line 1484 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [13/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RawContentSection & Section) static
Definition at line 1444 of file ELFYAML.cpp.
References assert(), commonSectionMapping(), llvm::yaml::IO::mapOptional(), llvm::yaml::IO::outputting(), and llvm::yaml::IO::setError().
sectionMapping() [14/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RelocationSection & Section) static
Definition at line 1518 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [15/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RelrSection & Section) static
Definition at line 1524 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [16/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::StackSizesSection & Section) static
Definition at line 1467 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [17/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::SymtabShndxSection & Section) static
Definition at line 1535 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [18/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::SymverSection & Section) static
Definition at line 1507 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [19/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::VerdefSection & Section) static
Definition at line 1501 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [20/39]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::VerneedSection & Section) static
Definition at line 1512 of file ELFYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [21/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::CodeSection & Section) static
Definition at line 153 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapRequired().
sectionMapping() [22/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::CustomSection & Section) static
Definition at line 97 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapRequired().
sectionMapping() [23/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::DataCountSection & Section) static
Definition at line 163 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapRequired().
sectionMapping() [24/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::DataSection & Section) static
Definition at line 158 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapRequired().
sectionMapping() [25/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::DylinkSection & Section) static
Definition at line 52 of file WasmYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), and llvm::yaml::IO::mapRequired().
sectionMapping() [26/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ElemSection & Section) static
Definition at line 148 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [27/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ExportSection & Section) static
Definition at line 138 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [28/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::FunctionSection & Section) static
Definition at line 113 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [29/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::GlobalSection & Section) static
Definition at line 133 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [30/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ImportSection & Section) static
Definition at line 108 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [31/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::LinkingSection & Section) static
Definition at line 73 of file WasmYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), and llvm::yaml::IO::mapRequired().
sectionMapping() [32/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::MemorySection & Section) static
Definition at line 123 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [33/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::NameSection & Section) static
Definition at line 65 of file WasmYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), and llvm::yaml::IO::mapRequired().
sectionMapping() [34/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ProducersSection & Section) static
Definition at line 83 of file WasmYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), and llvm::yaml::IO::mapRequired().
sectionMapping() [35/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::StartSection & Section) static
Definition at line 143 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [36/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TableSection & Section) static
Definition at line 118 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [37/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TagSection & Section) static
Definition at line 128 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
sectionMapping() [38/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TargetFeaturesSection & Section) static
Definition at line 91 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapRequired().
sectionMapping() [39/39]
void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TypeSection & Section) static
Definition at line 103 of file WasmYAML.cpp.
References commonSectionMapping(), and llvm::yaml::IO::mapOptional().
setStringValue()
void llvm::yaml::setStringValue (IO & IO, const char * Key, StringRef Val) static
Definition at line 1612 of file ELFYAML.cpp.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, and llvm::yaml::IO::mapRequired().
skip()
template<class CollectionType> void llvm::yaml::skip (CollectionType & C)
Definition at line 405 of file YAMLParser.h.
References assert(), llvm::begin(), and llvm::CallingConv::C.
Referenced by llvm::yaml::MappingNode::skip(), llvm::yaml::SequenceNode::skip(), llvm::yaml::MappingNode::yaml::skip, and llvm::yaml::SequenceNode::yaml::skip.
yaml2archive()
bool llvm::yaml::yaml2archive (ArchYAML::Archive & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 19 of file ArchiveEmitter.cpp.
References llvm::CallingConv::C, llvm::ArchYAML::Archive::Content, llvm::StringRef::data(), I, llvm::ArchYAML::Archive::Magic, llvm::ArchYAML::Archive::Members, P, Size, llvm::StringRef::size(), and llvm::raw_ostream::write().
Referenced by convertYAML().
yaml2coff()
bool llvm::yaml::yaml2coff (COFFYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 618 of file COFFEmitter.cpp.
References layoutCOFF(), layoutOptionalHeader(), and writeCOFF().
Referenced by convertYAML().
yaml2dxcontainer()
bool llvm::yaml::yaml2dxcontainer (DXContainerYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 396 of file DXContainerEmitter.cpp.
References llvm::handleAllErrors(), and yaml2dxcontainer().
Referenced by convertYAML(), and yaml2dxcontainer().
yaml2elf()
bool llvm::yaml::yaml2elf (ELFYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH, uint64_t MaxSize)
Definition at line 2168 of file ELFEmitter.cpp.
References llvm::ELFYAML::FileHeader::Class, llvm::ELFYAML::FileHeader::Data, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, and llvm::ELFYAML::Object::Header.
Referenced by llvm::offloading::intel::containerizeOpenMPSPIRVImage(), and convertYAML().
yaml2goff()
bool llvm::yaml::yaml2goff (GOFFYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 273 of file GOFFEmitter.cpp.
References yaml2goff().
Referenced by convertYAML(), and yaml2goff().
yaml2macho()
bool llvm::yaml::yaml2macho (YamlObjectFile & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 775 of file MachOEmitter.cpp.
References llvm::handleAllErrors(), and yaml2macho().
Referenced by convertYAML(), and yaml2macho().
yaml2minidump()
bool llvm::yaml::yaml2minidump (MinidumpYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 257 of file MinidumpEmitter.cpp.
References llvm::ArrayRef(), llvm::enumerate(), layout(), and yaml2minidump().
Referenced by convertYAML(), and yaml2minidump().
yaml2ObjectFile()
std::unique_ptr< object::ObjectFile > llvm::yaml::yaml2ObjectFile (SmallVectorImpl< char > & Storage, StringRef Yaml, ErrorHandler ErrHandler)
Convenience function for tests.
Definition at line 66 of file yaml2obj.cpp.
References llvm::SmallVectorImpl< T >::clear(), convertYAML(), llvm::object::ObjectFile::createObjectFile(), llvm::raw_svector_ostream::str(), llvm::Expected< T >::takeError(), and llvm::toString().
yaml2offload()
bool llvm::yaml::yaml2offload (OffloadYAML::Binary & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 20 of file OffloadEmitter.cpp.
References llvm::Data, llvm::OffloadYAML::Binary::EntryOffset, llvm::OffloadYAML::Binary::EntrySize, llvm::MemoryBuffer::getMemBufferCopy(), llvm::OffloadYAML::Binary::Members, llvm::OffloadYAML::Binary::Size, llvm::raw_svector_ostream::str(), llvm::object::OffloadBinary::Header::Version, llvm::OffloadYAML::Binary::Version, llvm::object::OffloadBinary::write(), and llvm::raw_ostream::write().
Referenced by convertYAML().
yaml2wasm()
bool llvm::yaml::yaml2wasm (WasmYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 697 of file WasmEmitter.cpp.
References yaml2wasm().
Referenced by convertYAML(), and yaml2wasm().
yaml2xcoff()
bool llvm::yaml::yaml2xcoff (XCOFFYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 894 of file XCOFFEmitter.cpp.
References yaml2xcoff().
Referenced by convertYAML(), and yaml2xcoff().
yamlize() [1/11]
template<typename T, typename Context> std::enable_if_t< has_SequenceTraits< T >::value, void > llvm::yaml::yamlize (IO & io, T & Seq, bool , Context & Ctx)
Definition at line 1075 of file YAMLTraits.h.
References llvm::yaml::IO::beginFlowSequence(), llvm::yaml::IO::beginSequence(), llvm::count(), llvm::yaml::IO::endFlowSequence(), llvm::yaml::IO::endSequence(), llvm::yaml::IO::outputting(), llvm::yaml::IO::postflightElement(), llvm::yaml::IO::postflightFlowElement(), llvm::yaml::IO::preflightElement(), llvm::yaml::IO::preflightFlowElement(), T, and yamlize().
yamlize() [2/11]
template<typename T, typename Context> std::enable_if_t< unvalidatedMappingTraits< T, Context >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , Context & Ctx)
Definition at line 1024 of file YAMLTraits.h.
References llvm::yaml::IO::beginFlowMapping(), llvm::yaml::IO::beginMapping(), llvm::yaml::detail::doMapping(), llvm::yaml::IO::endFlowMapping(), llvm::yaml::IO::endMapping(), T, and yamlizeMappingEnumInput().
yamlize() [3/11]
template<typename T, typename Context> std::enable_if_t< validatedMappingTraits< T, Context >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , Context & Ctx)
Definition at line 983 of file YAMLTraits.h.
References assert(), llvm::yaml::IO::beginFlowMapping(), llvm::yaml::IO::beginMapping(), llvm::yaml::detail::doMapping(), llvm::yaml::detail::doValidate(), llvm::yaml::IO::endFlowMapping(), llvm::yaml::IO::endMapping(), llvm::errs(), llvm::yaml::IO::outputting(), llvm::yaml::IO::setError(), and T.
yamlize() [4/11]
template<typename T> std::enable_if_t< missingTraits< T, EmptyContext >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , EmptyContext & Ctx)
Definition at line 1069 of file YAMLTraits.h.
References T.
yamlize() [5/11]
template<typename T> std::enable_if_t< has_PolymorphicTraits< T >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , EmptyContext & Ctx)
Definition at line 1055 of file YAMLTraits.h.
References llvm::yaml::IO::getNodeKind(), Map, llvm::yaml::IO::outputting(), Scalar, Sequence, T, and yamlize().
yamlize() [6/11]
template<typename T> std::enable_if_t< has_CustomMappingTraits< T >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , EmptyContext & Ctx)
Definition at line 1040 of file YAMLTraits.h.
References llvm::yaml::IO::beginMapping(), llvm::yaml::IO::endMapping(), llvm::yaml::IO::keys(), llvm::yaml::IO::outputting(), and T.
yamlize() [7/11]
template<typename T> std::enable_if_t< has_TaggedScalarTraits< T >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , EmptyContext & Ctx)
Definition at line 945 of file YAMLTraits.h.
References llvm::yaml::IO::getContext(), None, llvm::yaml::IO::outputting(), llvm::yaml::IO::scalarString(), llvm::yaml::IO::scalarTag(), llvm::yaml::IO::setError(), and T.
yamlize() [8/11]
template<typename T> std::enable_if_t< has_ScalarTraits< T >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , EmptyContext & Ctx)
Definition at line 906 of file YAMLTraits.h.
References llvm::yaml::IO::getContext(), llvm::yaml::IO::outputting(), llvm::yaml::IO::scalarString(), llvm::yaml::IO::setError(), llvm::raw_svector_ostream::str(), and T.
yamlize() [9/11]
template<typename T> std::enable_if_t< has_ScalarBitSetTraits< T >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , EmptyContext & Ctx)
Definition at line 895 of file YAMLTraits.h.
References llvm::yaml::IO::beginBitSetScalar(), llvm::yaml::IO::endBitSetScalar(), and T.
yamlize() [10/11]
template<typename T> std::enable_if_t< has_ScalarEnumerationTraits< T >::value, void > llvm::yaml::yamlize (IO & io, T & Val, bool , EmptyContext & Ctx)
Definition at line 887 of file YAMLTraits.h.
References llvm::yaml::IO::beginEnumScalar(), llvm::yaml::IO::endEnumScalar(), and T.
Referenced by llvm::yaml::IO::enumFallback(), operator>>(), operator>>(), operator>>(), operator>>(), llvm::MIRParserImpl::parseMachineFunction(), yamlize(), and yamlize().
yamlize() [11/11]
template<typename T> std::enable_if_t< has_BlockScalarTraits< T >::value, void > llvm::yaml::yamlize (IO & YamlIO, T & Val, bool , EmptyContext & Ctx)
Definition at line 926 of file YAMLTraits.h.
References llvm::yaml::IO::blockScalarString(), llvm::yaml::IO::getContext(), llvm::yaml::IO::outputting(), llvm::yaml::IO::setError(), and T.
yamlizeMappingEnumInput()
template<typename T, typename Context> bool llvm::yaml::yamlizeMappingEnumInput (IO & io, T & Val)
Definition at line 1008 of file YAMLTraits.h.
References llvm::yaml::IO::beginEnumScalar(), llvm::yaml::IO::endEnumScalar(), llvm::yaml::IO::matchEnumFallback(), llvm::yaml::IO::outputting(), T, and llvm::yaml::has_MappingEnumInputTraits< T, Context >::value.
Referenced by yamlize().