LLVM: llvm::support::detail Namespace Reference
llvm::support::detail Namespace Reference
Classes
struct PickAlignment
::value is either alignment, or alignof(T) if alignment is 0.
struct packed_endian_specific_integral
class AlignAdapter
class PadAdapter
class RepeatAdapter
class ErrorAdapter
struct use_integral_formatter
struct use_char_formatter
struct is_cstring
struct use_string_formatter
struct use_pointer_formatter
struct use_double_formatter
class HelperFunctions
struct range_item_has_provider
class format_adapter
class provider_format_adapter
class stream_operator_format_adapter
class missing_format_adapter
class has_FormatProvider
class has_StreamOperator
struct uses_format_member
struct uses_format_provider
struct uses_stream_operator
struct uses_missing_provider
Typedefs
template<typename IterT>
using IterValue = typename std::iterator_traits<IterT>::value_type
Functions
template<typename T>
std::enable_if_t< uses_format_member< T >::value, T > build_format_adapter (T &&Item)
template<typename T>
std::enable_if_t< uses_format_provider< T >::value, provider_format_adapter< T > > build_format_adapter (T &&Item)
template<typename T>
std::enable_if_t< uses_stream_operator< T >::value, stream_operator_format_adapter< T > > build_format_adapter (T &&Item)
template<typename T>
std::enable_if_t< uses_missing_provider< T >::value, missing_format_adapter< T > > build_format_adapter (T &&)
Typedef Documentation
IterValue
template<typename IterT> using llvm::support::detail::IterValue = typename std::iterator_traits<IterT>::value_type
Definition at line 320 of file FormatProviders.h.
Function Documentation
build_format_adapter() [1/4]
template<typename T> std::enable_if_t< uses_missing_provider< T >::value, missing_format_adapter< T > > llvm::support::detail::build_format_adapter (T &&)
Definition at line 150 of file FormatVariadicDetails.h.
References T.
build_format_adapter() [2/4]
template<typename T> std::enable_if_t< uses_stream_operator< T >::value, stream_operator_format_adapter< T > > llvm::support::detail::build_format_adapter (T && Item)
Definition at line 138 of file FormatVariadicDetails.h.
References T.
build_format_adapter() [3/4]
template<typename T> std::enable_if_t< uses_format_provider< T >::value, provider_format_adapter< T > > llvm::support::detail::build_format_adapter (T && Item)
Definition at line 131 of file FormatVariadicDetails.h.
References T.
build_format_adapter() [4/4]
template<typename T> std::enable_if_t< uses_format_member< T >::value, T > llvm::support::detail::build_format_adapter (T && Item)
Definition at line 125 of file FormatVariadicDetails.h.
References T.
Referenced by llvm::format_provider< llvm::iterator_range< IterT > >::format(), llvm::support::detail::AlignAdapter< T >::format(), llvm::support::detail::PadAdapter< T >::format(), llvm::support::detail::RepeatAdapter< T >::format(), and llvm::formatv().