LLVM: llvm::AArch64 Namespace Reference
llvm::AArch64 Namespace Reference
Classes
struct ExtensionInfo
struct FMVInfo
struct ExtensionDependency
struct ArchInfo
struct CpuInfo
struct ExtensionSet
struct Alias
Typedefs
using ExtensionBitset = Bitset<AEK_NUM_EXTENSIONS>
using Specifier = uint16_t
Enumerations
enum CPUFeatures {
FEAT_RNG , FEAT_FLAGM , FEAT_FLAGM2 , FEAT_FP16FML ,
FEAT_DOTPROD , FEAT_SM4 , FEAT_RDM , FEAT_LSE ,
FEAT_FP , FEAT_SIMD , FEAT_CRC , FEAT_CSSC ,
FEAT_SHA2 , FEAT_SHA3 , RESERVED_FEAT_AES , FEAT_PMULL ,
FEAT_FP16 , FEAT_DIT , FEAT_DPB , FEAT_DPB2 ,
FEAT_JSCVT , FEAT_FCMA , FEAT_RCPC , FEAT_RCPC2 ,
FEAT_FRINTTS , RESERVED_FEAT_DGH , FEAT_I8MM , FEAT_BF16 ,
RESERVED_FEAT_EBF16 , RESERVED_FEAT_RPRES , FEAT_SVE , RESERVED_FEAT_SVE_BF16 ,
RESERVED_FEAT_SVE_EBF16 , RESERVED_FEAT_SVE_I8MM , FEAT_SVE_F32MM , FEAT_SVE_F64MM ,
FEAT_SVE2 , RESERVED_FEAT_SVE_AES , FEAT_SVE_PMULL128 , FEAT_SVE_BITPERM ,
FEAT_SVE_SHA3 , FEAT_SVE_SM4 , FEAT_SME , RESERVED_FEAT_MEMTAG ,
FEAT_MEMTAG2 , RESERVED_FEAT_MEMTAG3 , FEAT_SB , RESERVED_FEAT_PREDRES ,
RESERVED_FEAT_SSBS , FEAT_SSBS2 , FEAT_BTI , RESERVED_FEAT_LS64 ,
RESERVED_FEAT_LS64_V , RESERVED_FEAT_LS64_ACCDATA , FEAT_WFXT , FEAT_SME_F64 ,
FEAT_SME_I64 , FEAT_SME2 , FEAT_RCPC3 , FEAT_MOPS ,
FEAT_MAX , FEAT_EXT = 62 , FEAT_INIT
}
enum FeatPriorities {
PRIOR_RNG , PRIOR_FLAGM , PRIOR_FLAGM2 , PRIOR_LSE ,
PRIOR_FP , PRIOR_SIMD , PRIOR_DOTPROD , PRIOR_SM4 ,
PRIOR_RDM , PRIOR_CRC , PRIOR_SHA2 , PRIOR_SHA3 ,
PRIOR_PMULL , PRIOR_FP16 , PRIOR_FP16FML , PRIOR_DIT ,
PRIOR_DPB , PRIOR_DPB2 , PRIOR_JSCVT , PRIOR_FCMA ,
PRIOR_RCPC , PRIOR_RCPC2 , PRIOR_RCPC3 , PRIOR_FRINTTS ,
PRIOR_I8MM , PRIOR_BF16 , PRIOR_SVE , PRIOR_SVE_F32MM ,
PRIOR_SVE_F64MM , PRIOR_SVE2 , PRIOR_SVE_PMULL128 , PRIOR_SVE_BITPERM ,
PRIOR_SVE_SHA3 , PRIOR_SVE_SM4 , PRIOR_SME , PRIOR_MEMTAG2 ,
PRIOR_SB , PRIOR_SSBS2 , PRIOR_BTI , PRIOR_WFXT ,
PRIOR_SME_F64 , PRIOR_SME_I64 , PRIOR_SME2 , PRIOR_MOPS ,
PRIOR_CSSC , PRIOR_MAX , PRIOR_P0 = 120 , PRIOR_P1 ,
PRIOR_P2 , PRIOR_P3 , PRIOR_P4 , PRIOR_P5 ,
PRIOR_P6 , PRIOR_P7
}
enum ArchProfile { AProfile = 'A' , RProfile = 'R' , InvalidProfile = '?' }
enum ElementSizeType {
ElementSizeMask = TSFLAG_ELEMENT_SIZE_TYPE(0x7) , ElementSizeNone = TSFLAG_ELEMENT_SIZE_TYPE(0x0) , ElementSizeB = TSFLAG_ELEMENT_SIZE_TYPE(0x1) , ElementSizeH = TSFLAG_ELEMENT_SIZE_TYPE(0x2) ,
ElementSizeS = TSFLAG_ELEMENT_SIZE_TYPE(0x3) , ElementSizeD = TSFLAG_ELEMENT_SIZE_TYPE(0x4)
}
enum DestructiveInstType {
DestructiveInstTypeMask = TSFLAG_DESTRUCTIVE_INST_TYPE(0xf) , NotDestructive = TSFLAG_DESTRUCTIVE_INST_TYPE(0x0) , DestructiveOther = TSFLAG_DESTRUCTIVE_INST_TYPE(0x1) , DestructiveUnary = TSFLAG_DESTRUCTIVE_INST_TYPE(0x2) ,
DestructiveBinaryImm = TSFLAG_DESTRUCTIVE_INST_TYPE(0x3) , DestructiveBinaryShImmUnpred = TSFLAG_DESTRUCTIVE_INST_TYPE(0x4) , DestructiveBinary = TSFLAG_DESTRUCTIVE_INST_TYPE(0x5) , DestructiveBinaryComm = TSFLAG_DESTRUCTIVE_INST_TYPE(0x6) ,
DestructiveBinaryCommWithRev = TSFLAG_DESTRUCTIVE_INST_TYPE(0x7) , DestructiveTernaryCommWithRev = TSFLAG_DESTRUCTIVE_INST_TYPE(0x8) , Destructive2xRegImmUnpred = TSFLAG_DESTRUCTIVE_INST_TYPE(0x9) , DestructiveUnaryPassthru = TSFLAG_DESTRUCTIVE_INST_TYPE(0xa)
}
enum FalseLaneType { FalseLanesMask = TSFLAG_FALSE_LANE_TYPE(0x3) , FalseLanesZero = TSFLAG_FALSE_LANE_TYPE(0x1) , FalseLanesUndef = TSFLAG_FALSE_LANE_TYPE(0x2) }
enum SMEMatrixType {
SMEMatrixTypeMask = TSFLAG_SME_MATRIX_TYPE(0x7) , SMEMatrixNone = TSFLAG_SME_MATRIX_TYPE(0x0) , SMEMatrixTileB = TSFLAG_SME_MATRIX_TYPE(0x1) , SMEMatrixTileH = TSFLAG_SME_MATRIX_TYPE(0x2) ,
SMEMatrixTileS = TSFLAG_SME_MATRIX_TYPE(0x3) , SMEMatrixTileD = TSFLAG_SME_MATRIX_TYPE(0x4) , SMEMatrixTileQ = TSFLAG_SME_MATRIX_TYPE(0x5) , SMEMatrixArray = TSFLAG_SME_MATRIX_TYPE(0x6)
}
enum Rounding {
RN = 0 , RP = 1 , RM = 2 , RZ = 3 ,
rmMask = 3
}
Possible values of current rounding mode, which is specified in bits 23:22 of FPCR.
enum Fixups {
fixup_aarch64_pcrel_adr_imm21 = FirstTargetFixupKind , fixup_aarch64_pcrel_adrp_imm21 , fixup_aarch64_add_imm12 , fixup_aarch64_ldst_imm12_scale1 ,
fixup_aarch64_ldst_imm12_scale2 , fixup_aarch64_ldst_imm12_scale4 , fixup_aarch64_ldst_imm12_scale8 , fixup_aarch64_ldst_imm12_scale16 ,
fixup_aarch64_ldr_pcrel_imm19 , fixup_aarch64_movw , fixup_aarch64_pcrel_branch9 , fixup_aarch64_pcrel_branch14 ,
fixup_aarch64_pcrel_branch16 , fixup_aarch64_pcrel_branch19 , fixup_aarch64_pcrel_branch26 , fixup_aarch64_pcrel_call26 ,
LastTargetFixupKind , NumTargetFixupKinds = LastTargetFixupKind - FirstTargetFixupKind
}
enum {
S_None = 0 , S_ABS = 0x001 , S_SABS = 0x002 , S_PREL = 0x003 ,
S_GOT = 0x004 , S_DTPREL = 0x005 , S_GOTTPREL = 0x006 , S_TPREL = 0x007 ,
S_TLSDESC = 0x008 , S_SECREL = 0x009 , S_AUTH = 0x00a , S_AUTHADDR = 0x00b ,
S_GOT_AUTH = 0x00c , S_TLSDESC_AUTH = 0x00d , S_SymLocBits = 0x00f , S_PAGE = 0x010 ,
S_PAGEOFF = 0x020 , S_HI12 = 0x030 , S_G0 = 0x040 , S_G1 = 0x050 ,
S_G2 = 0x060 , S_G3 = 0x070 , S_LO15 = 0x080 , S_AddressFragBits = 0x0f0 ,
S_NC = 0x100 , S_CALL = S_ABS , S_ABS_PAGE = S_ABS | S_PAGE , S_ABS_PAGE_NC = S_ABS | S_PAGE | S_NC ,
S_ABS_G3 = S_ABS | S_G3 , S_ABS_G2 = S_ABS | S_G2 , S_ABS_G2_S = S_SABS | S_G2 , S_ABS_G2_NC = S_ABS | S_G2 | S_NC ,
S_ABS_G1 = S_ABS | S_G1 , S_ABS_G1_S = S_SABS | S_G1 , S_ABS_G1_NC = S_ABS | S_G1 | S_NC , S_ABS_G0 = S_ABS | S_G0 ,
S_ABS_G0_S = S_SABS | S_G0 , S_ABS_G0_NC = S_ABS | S_G0 | S_NC , S_LO12 = S_ABS | S_PAGEOFF | S_NC , S_PREL_G3 = S_PREL | S_G3 ,
S_PREL_G2 = S_PREL | S_G2 , S_PREL_G2_NC = S_PREL | S_G2 | S_NC , S_PREL_G1 = S_PREL | S_G1 , S_PREL_G1_NC = S_PREL | S_G1 | S_NC ,
S_PREL_G0 = S_PREL | S_G0 , S_PREL_G0_NC = S_PREL | S_G0 | S_NC , S_GOT_LO12 = S_GOT | S_PAGEOFF | S_NC , S_GOT_PAGE = S_GOT | S_PAGE ,
S_GOT_PAGE_LO15 = S_GOT | S_LO15 | S_NC , S_GOT_AUTH_LO12 = S_GOT_AUTH | S_PAGEOFF | S_NC , S_GOT_AUTH_PAGE = S_GOT_AUTH | S_PAGE , S_DTPREL_G2 = S_DTPREL | S_G2 ,
S_DTPREL_G1 = S_DTPREL | S_G1 , S_DTPREL_G1_NC = S_DTPREL | S_G1 | S_NC , S_DTPREL_G0 = S_DTPREL | S_G0 , S_DTPREL_G0_NC = S_DTPREL | S_G0 | S_NC ,
S_DTPREL_HI12 = S_DTPREL | S_HI12 , S_DTPREL_LO12 = S_DTPREL | S_PAGEOFF , S_DTPREL_LO12_NC = S_DTPREL | S_PAGEOFF | S_NC , S_GOTTPREL_PAGE = S_GOTTPREL | S_PAGE ,
S_GOTTPREL_LO12_NC = S_GOTTPREL | S_PAGEOFF | S_NC , S_GOTTPREL_G1 = S_GOTTPREL | S_G1 , S_GOTTPREL_G0_NC = S_GOTTPREL | S_G0 | S_NC , S_TPREL_G2 = S_TPREL | S_G2 ,
S_TPREL_G1 = S_TPREL | S_G1 , S_TPREL_G1_NC = S_TPREL | S_G1 | S_NC , S_TPREL_G0 = S_TPREL | S_G0 , S_TPREL_G0_NC = S_TPREL | S_G0 | S_NC ,
S_TPREL_HI12 = S_TPREL | S_HI12 , S_TPREL_LO12 = S_TPREL | S_PAGEOFF , S_TPREL_LO12_NC = S_TPREL | S_PAGEOFF | S_NC , S_TLSDESC_LO12 = S_TLSDESC | S_PAGEOFF ,
S_TLSDESC_PAGE = S_TLSDESC | S_PAGE , S_TLSDESC_AUTH_LO12 = S_TLSDESC_AUTH | S_PAGEOFF , S_TLSDESC_AUTH_PAGE = S_TLSDESC_AUTH | S_PAGE , S_SECREL_LO12 = S_SECREL | S_PAGEOFF ,
S_SECREL_HI12 = S_SECREL | S_HI12 , S_PLT = 0x400 , S_GOTPCREL , S_FUNCINIT ,
S_MACHO_GOT , S_MACHO_GOTPAGE , S_MACHO_GOTPAGEOFF , S_MACHO_PAGE ,
S_MACHO_PAGEOFF , S_MACHO_TLVP , S_MACHO_TLVPPAGE , S_MACHO_TLVPPAGEOFF ,
S_INVALID = 0xfff
}
enum OperandType { OPERAND_IMPLICIT_IMM_0 = MCOI::OPERAND_FIRST_TARGET , OPERAND_SHIFT_MSL , OPERAND_SHIFTED_REGISTER , OPERAND_SHIFTED_IMMEDIATE }
Functions
LLVM_ABI const std::vector< FMVInfo > & getFMVInfo ()
LLVM_ABI const ExtensionInfo & getExtensionByID (ArchExtKind(ExtID))
LLVM_ABI bool getExtensionFeatures (const AArch64::ExtensionBitset &Extensions, std::vector< StringRef > &Features)
LLVM_ABI StringRef getArchExtFeature (StringRef ArchExt)
LLVM_ABI StringRef resolveCPUAlias (StringRef CPU)
LLVM_ABI const ArchInfo * getArchForCpu (StringRef CPU)
LLVM_ABI const ArchInfo * parseArch (StringRef Arch)
LLVM_ABI std::optional< ExtensionInfo > targetFeatureToExtension (StringRef TargetFeature)
LLVM_ABI std::optional< ExtensionInfo > parseArchExtension (StringRef Extension)
LLVM_ABI std::optional< FMVInfo > parseFMVExtension (StringRef Extension)
LLVM_ABI std::optional< CpuInfo > parseCpu (StringRef Name)
LLVM_ABI void fillValidCPUArchList (SmallVectorImpl< StringRef > &Values)
LLVM_ABI bool isX18ReservedByDefault (const Triple &TT)
LLVM_ABI APInt getFMVPriority (ArrayRef< StringRef > Features)
LLVM_ABI APInt getCpuSupportsMask (ArrayRef< StringRef > Features)
LLVM_ABI void PrintSupportedExtensions ()
LLVM_ABI void printEnabledExtensions (const std::set< StringRef > &EnabledFeatureNames)
int getSVEPseudoMap (uint16_t Opcode)
int getSVERevInstr (uint16_t Opcode)
int getSVENonRevInstr (uint16_t Opcode)
int getSMEPseudoMap (uint16_t Opcode)
ArrayRef< MCPhysReg > getGPRArgRegs ()
ArrayRef< MCPhysReg > getFPRArgRegs ()
FastISel * createFastISel (FunctionLoweringInfo &funcInfo, const TargetLibraryInfo *libInfo)
StringRef getSpecifierName (Specifier S)
Return the string representation of the ELF relocation specifier (e.g.
Specifier getSymbolLoc (Specifier S)
Specifier getAddressFrag (Specifier S)
bool isNotChecked (Specifier S)
Variables
static const uint64_t InstrFlagIsWhile = TSFLAG_INSTR_FLAGS(0x1)
static const uint64_t InstrFlagIsPTestLike = TSFLAG_INSTR_FLAGS(0x2)
const unsigned RoundingBitsPos = 22
const uint64_t ReservedFPControlBits = 0xfffffffff80040f8
const unsigned StackProbeMaxUnprobedStack = 1024
Maximum allowed number of unprobed bytes above SP at an ABI boundary.
const unsigned StackProbeMaxLoopUnroll = 4
Maximum number of iterations to unroll for a constant size probing loop.
static constexpr unsigned SVEBitsPerBlock = 128
static constexpr unsigned SVEMaxBitsPerVector = 2048
Typedef Documentation
ExtensionBitset
using llvm::AArch64::ExtensionBitset = Bitset<AEK_NUM_EXTENSIONS>
Definition at line 50 of file AArch64TargetParser.h.
Specifier
using llvm::AArch64::Specifier = uint16_t
Definition at line 64 of file AArch64MCAsmInfo.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
S_None
S_ABS
S_SABS
S_PREL
S_GOT
S_DTPREL
S_GOTTPREL
S_TPREL
S_TLSDESC
S_SECREL
S_AUTH
S_AUTHADDR
S_GOT_AUTH
S_TLSDESC_AUTH
S_SymLocBits
S_PAGE
S_PAGEOFF
S_HI12
S_G0
S_G1
S_G2
S_G3
S_LO15
S_AddressFragBits
S_NC
S_CALL
S_ABS_PAGE
S_ABS_PAGE_NC
S_ABS_G3
S_ABS_G2
S_ABS_G2_S
S_ABS_G2_NC
S_ABS_G1
S_ABS_G1_S
S_ABS_G1_NC
S_ABS_G0
S_ABS_G0_S
S_ABS_G0_NC
S_LO12
S_PREL_G3
S_PREL_G2
S_PREL_G2_NC
S_PREL_G1
S_PREL_G1_NC
S_PREL_G0
S_PREL_G0_NC
S_GOT_LO12
S_GOT_PAGE
S_GOT_PAGE_LO15
S_GOT_AUTH_LO12
S_GOT_AUTH_PAGE
S_DTPREL_G2
S_DTPREL_G1
S_DTPREL_G1_NC
S_DTPREL_G0
S_DTPREL_G0_NC
S_DTPREL_HI12
S_DTPREL_LO12
S_DTPREL_LO12_NC
S_GOTTPREL_PAGE
S_GOTTPREL_LO12_NC
S_GOTTPREL_G1
S_GOTTPREL_G0_NC
S_TPREL_G2
S_TPREL_G1
S_TPREL_G1_NC
S_TPREL_G0
S_TPREL_G0_NC
S_TPREL_HI12
S_TPREL_LO12
S_TPREL_LO12_NC
S_TLSDESC_LO12
S_TLSDESC_PAGE
S_TLSDESC_AUTH_LO12
S_TLSDESC_AUTH_PAGE
S_SECREL_LO12
S_SECREL_HI12
S_PLT
S_GOTPCREL
S_FUNCINIT
S_MACHO_GOT
S_MACHO_GOTPAGE
S_MACHO_GOTPAGEOFF
S_MACHO_PAGE
S_MACHO_PAGEOFF
S_MACHO_TLVP
S_MACHO_TLVPPAGE
S_MACHO_TLVPPAGEOFF
S_INVALID
Definition at line 66 of file AArch64MCAsmInfo.h.
ArchProfile
enum llvm::AArch64::ArchProfile
Enumerator
AProfile
RProfile
InvalidProfile
Definition at line 99 of file AArch64TargetParser.h.
CPUFeatures
enum llvm::AArch64::CPUFeatures
Enumerator
FEAT_RNG
FEAT_FLAGM
FEAT_FLAGM2
FEAT_FP16FML
FEAT_DOTPROD
FEAT_SM4
FEAT_RDM
FEAT_LSE
FEAT_FP
FEAT_SIMD
FEAT_CRC
FEAT_CSSC
FEAT_SHA2
FEAT_SHA3
RESERVED_FEAT_AES
FEAT_PMULL
FEAT_FP16
FEAT_DIT
FEAT_DPB
FEAT_DPB2
FEAT_JSCVT
FEAT_FCMA
FEAT_RCPC
FEAT_RCPC2
FEAT_FRINTTS
RESERVED_FEAT_DGH
FEAT_I8MM
FEAT_BF16
RESERVED_FEAT_EBF16
RESERVED_FEAT_RPRES
FEAT_SVE
RESERVED_FEAT_SVE_BF16
RESERVED_FEAT_SVE_EBF16
RESERVED_FEAT_SVE_I8MM
FEAT_SVE_F32MM
FEAT_SVE_F64MM
FEAT_SVE2
RESERVED_FEAT_SVE_AES
FEAT_SVE_PMULL128
FEAT_SVE_BITPERM
FEAT_SVE_SHA3
FEAT_SVE_SM4
FEAT_SME
RESERVED_FEAT_MEMTAG
FEAT_MEMTAG2
RESERVED_FEAT_MEMTAG3
FEAT_SB
RESERVED_FEAT_PREDRES
RESERVED_FEAT_SSBS
FEAT_SSBS2
FEAT_BTI
RESERVED_FEAT_LS64
RESERVED_FEAT_LS64_V
RESERVED_FEAT_LS64_ACCDATA
FEAT_WFXT
FEAT_SME_F64
FEAT_SME_I64
FEAT_SME2
FEAT_RCPC3
FEAT_MOPS
FEAT_MAX
FEAT_EXT
FEAT_INIT
Definition at line 25 of file AArch64TargetParser.h.
DestructiveInstType
enum llvm::AArch64::DestructiveInstType
Enumerator
DestructiveInstTypeMask
NotDestructive
DestructiveOther
DestructiveUnary
DestructiveBinaryImm
DestructiveBinaryShImmUnpred
DestructiveBinary
DestructiveBinaryComm
DestructiveBinaryCommWithRev
DestructiveTernaryCommWithRev
Destructive2xRegImmUnpred
DestructiveUnaryPassthru
Definition at line 851 of file AArch64InstrInfo.h.
ElementSizeType
enum llvm::AArch64::ElementSizeType
Enumerator
ElementSizeMask
ElementSizeNone
ElementSizeB
ElementSizeH
ElementSizeS
ElementSizeD
Definition at line 842 of file AArch64InstrInfo.h.
FalseLaneType
enum llvm::AArch64::FalseLaneType
Enumerator
FalseLanesMask
FalseLanesZero
FalseLanesUndef
Definition at line 866 of file AArch64InstrInfo.h.
FeatPriorities
enum llvm::AArch64::FeatPriorities
Enumerator
PRIOR_RNG
PRIOR_FLAGM
PRIOR_FLAGM2
PRIOR_LSE
PRIOR_FP
PRIOR_SIMD
PRIOR_DOTPROD
PRIOR_SM4
PRIOR_RDM
PRIOR_CRC
PRIOR_SHA2
PRIOR_SHA3
PRIOR_PMULL
PRIOR_FP16
PRIOR_FP16FML
PRIOR_DIT
PRIOR_DPB
PRIOR_DPB2
PRIOR_JSCVT
PRIOR_FCMA
PRIOR_RCPC
PRIOR_RCPC2
PRIOR_RCPC3
PRIOR_FRINTTS
PRIOR_I8MM
PRIOR_BF16
PRIOR_SVE
PRIOR_SVE_F32MM
PRIOR_SVE_F64MM
PRIOR_SVE2
PRIOR_SVE_PMULL128
PRIOR_SVE_BITPERM
PRIOR_SVE_SHA3
PRIOR_SVE_SM4
PRIOR_SME
PRIOR_MEMTAG2
PRIOR_SB
PRIOR_SSBS2
PRIOR_BTI
PRIOR_WFXT
PRIOR_SME_F64
PRIOR_SME_I64
PRIOR_SME2
PRIOR_MOPS
PRIOR_CSSC
PRIOR_MAX
PRIOR_P0
PRIOR_P1
PRIOR_P2
PRIOR_P3
PRIOR_P4
PRIOR_P5
PRIOR_P6
PRIOR_P7
Definition at line 18 of file AArch64TargetParser.h.
Fixups
enum llvm::AArch64::Fixups
Enumerator
fixup_aarch64_pcrel_adr_imm21
fixup_aarch64_pcrel_adrp_imm21
fixup_aarch64_add_imm12
fixup_aarch64_ldst_imm12_scale1
fixup_aarch64_ldst_imm12_scale2
fixup_aarch64_ldst_imm12_scale4
fixup_aarch64_ldst_imm12_scale8
fixup_aarch64_ldst_imm12_scale16
fixup_aarch64_ldr_pcrel_imm19
fixup_aarch64_movw
fixup_aarch64_pcrel_branch9
fixup_aarch64_pcrel_branch14
fixup_aarch64_pcrel_branch16
fixup_aarch64_pcrel_branch19
fixup_aarch64_pcrel_branch26
fixup_aarch64_pcrel_call26
LastTargetFixupKind
NumTargetFixupKinds
Definition at line 17 of file AArch64FixupKinds.h.
OperandType
enum llvm::AArch64::OperandType
Enumerator
OPERAND_IMPLICIT_IMM_0
OPERAND_SHIFT_MSL
OPERAND_SHIFTED_REGISTER
OPERAND_SHIFTED_IMMEDIATE
Definition at line 71 of file AArch64MCTargetDesc.h.
Rounding
enum llvm::AArch64::Rounding
Possible values of current rounding mode, which is specified in bits 23:22 of FPCR.
Enumerator
RN
RP
RM
RZ
rmMask
Definition at line 31 of file AArch64ISelLowering.h.
SMEMatrixType
enum llvm::AArch64::SMEMatrixType
Enumerator
SMEMatrixTypeMask
SMEMatrixNone
SMEMatrixTileB
SMEMatrixTileH
SMEMatrixTileS
SMEMatrixTileD
SMEMatrixTileQ
SMEMatrixArray
Definition at line 876 of file AArch64InstrInfo.h.
Function Documentation
createFastISel()
FastISel * llvm::AArch64::createFastISel (FunctionLoweringInfo & funcInfo, const TargetLibraryInfo * libInfo)
Definition at line 5191 of file AArch64FastISel.cpp.
References llvm::MachineFunction::getInfo(), llvm::SMEAttrs::hasAgnosticZAInterface(), llvm::SMEAttrs::hasStreamingCompatibleInterface(), llvm::SMEAttrs::hasStreamingInterfaceOrBody(), llvm::SMEAttrs::hasZAState(), llvm::SMEAttrs::hasZT0State(), and llvm::FunctionLoweringInfo::MF.
Referenced by llvm::AArch64TargetLowering::createFastISel().
fillValidCPUArchList()
void llvm::AArch64::fillValidCPUArchList (SmallVectorImpl< StringRef > & Values)
Definition at line 136 of file AArch64TargetParser.cpp.
References llvm::AArch64::Alias::AltName, llvm::CallingConv::C, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sort().
getAddressFrag()
Specifier llvm::AArch64::getAddressFrag (Specifier S) inline
Definition at line 191 of file AArch64MCAsmInfo.h.
References S_AddressFragBits.
Referenced by adjustFixupValue().
getArchExtFeature()
StringRef llvm::AArch64::getArchExtFeature (StringRef ArchExt)
Definition at line 124 of file AArch64TargetParser.cpp.
References assert(), llvm::StringRef::drop_front(), parseArchExtension(), and llvm::StringRef::starts_with().
getArchForCpu()
const AArch64::ArchInfo * llvm::AArch64::getArchForCpu (StringRef CPU)
Definition at line 36 of file AArch64TargetParser.cpp.
References parseCpu().
getCpuSupportsMask()
APInt llvm::AArch64::getCpuSupportsMask (ArrayRef< StringRef > Features)
Definition at line 89 of file AArch64TargetParser.cpp.
References llvm::AArch64::ExtensionSet::enable(), llvm::AArch64::ExtensionSet::Enabled, getFMVInfo(), getFMVInfoFrom(), llvm::APInt::getZero(), llvm::APInt::setBit(), and llvm::Bitset< NumBits >::test().
Referenced by llvm::AArch64TTIImpl::getFeatureMask().
getExtensionByID()
LLVM_ABI const ExtensionInfo & llvm::AArch64::getExtensionByID (ArchExtKind(ExtID))
References Extensions, and LLVM_ABI.
getExtensionFeatures()
bool llvm::AArch64::getExtensionFeatures (const AArch64::ExtensionBitset & Extensions, std::vector< StringRef > & Features)
Definition at line 106 of file AArch64TargetParser.cpp.
References Extensions, and llvm::Bitset< NumBits >::test().
getFMVInfo()
LLVM_ABI const std::vector< FMVInfo > & llvm::AArch64::getFMVInfo ()
Referenced by getCpuSupportsMask(), getFMVPriority(), lookupFMVByID(), and parseFMVExtension().
getFMVPriority()
APInt llvm::AArch64::getFMVPriority (ArrayRef< StringRef > Features)
Definition at line 67 of file AArch64TargetParser.cpp.
References llvm::AArch64::ExtensionSet::enable(), llvm::AArch64::ExtensionSet::Enabled, getFMVInfo(), getFMVInfoFrom(), llvm::APInt::getZero(), llvm::APInt::setBit(), and llvm::Bitset< NumBits >::test().
Referenced by llvm::AArch64TTIImpl::getPriorityMask().
getFPRArgRegs()
ArrayRef< MCPhysReg > llvm::AArch64::getFPRArgRegs ()
Definition at line 180 of file AArch64ISelLowering.cpp.
References FPRArgRegs.
getGPRArgRegs()
ArrayRef< MCPhysReg > llvm::AArch64::getGPRArgRegs ()
Definition at line 178 of file AArch64ISelLowering.cpp.
References GPRArgRegs.
getSMEPseudoMap()
int llvm::AArch64::getSMEPseudoMap (uint16_t Opcode)
Referenced by llvm::AArch64TargetLowering::EmitInstrWithCustomInserter().
getSpecifierName()
StringRef llvm::AArch64::getSpecifierName (AArch64::Specifier S)
Return the string representation of the ELF relocation specifier (e.g.
":got:", ":lo12:").
Definition at line 57 of file AArch64MCAsmInfo.cpp.
References llvm_unreachable, S_ABS_G0, S_ABS_G0_NC, S_ABS_G0_S, S_ABS_G1, S_ABS_G1_NC, S_ABS_G1_S, S_ABS_G2, S_ABS_G2_NC, S_ABS_G2_S, S_ABS_G3, S_ABS_PAGE, S_ABS_PAGE_NC, S_CALL, S_DTPREL_G0, S_DTPREL_G0_NC, S_DTPREL_G1, S_DTPREL_G1_NC, S_DTPREL_G2, S_DTPREL_HI12, S_DTPREL_LO12, S_DTPREL_LO12_NC, S_GOT, S_GOT_AUTH, S_GOT_AUTH_LO12, S_GOT_AUTH_PAGE, S_GOT_LO12, S_GOT_PAGE, S_GOT_PAGE_LO15, S_GOTTPREL, S_GOTTPREL_G0_NC, S_GOTTPREL_G1, S_GOTTPREL_LO12_NC, S_GOTTPREL_PAGE, S_LO12, S_PREL_G0, S_PREL_G0_NC, S_PREL_G1, S_PREL_G1_NC, S_PREL_G2, S_PREL_G2_NC, S_PREL_G3, S_SECREL_HI12, S_SECREL_LO12, S_TLSDESC, S_TLSDESC_AUTH, S_TLSDESC_AUTH_LO12, S_TLSDESC_AUTH_PAGE, S_TLSDESC_LO12, S_TLSDESC_PAGE, S_TPREL_G0, S_TPREL_G0_NC, S_TPREL_G1, S_TPREL_G1_NC, S_TPREL_G2, S_TPREL_HI12, S_TPREL_LO12, and S_TPREL_LO12_NC.
Referenced by llvm::AArch64MCAsmInfoDarwin::printSpecifierExpr(), llvm::AArch64MCAsmInfoELF::printSpecifierExpr(), llvm::AArch64MCAsmInfoGNUCOFF::printSpecifierExpr(), and llvm::AArch64MCAsmInfoMicrosoftCOFF::printSpecifierExpr().
getSVENonRevInstr()
int llvm::AArch64::getSVENonRevInstr (uint16_t Opcode)
getSVEPseudoMap()
int llvm::AArch64::getSVEPseudoMap (uint16_t Opcode)
Referenced by llvm::AArch64RegisterInfo::getRegAllocationHints().
getSVERevInstr()
int llvm::AArch64::getSVERevInstr (uint16_t Opcode)
getSymbolLoc()
Specifier llvm::AArch64::getSymbolLoc (Specifier S) inline
Definition at line 187 of file AArch64MCAsmInfo.h.
References S_SymLocBits.
Referenced by adjustFixupValue().
isNotChecked()
bool llvm::AArch64::isNotChecked (Specifier S) inline
Definition at line 195 of file AArch64MCAsmInfo.h.
References S_NC.
isX18ReservedByDefault()
bool llvm::AArch64::isX18ReservedByDefault (const Triple & TT)
Definition at line 148 of file AArch64TargetParser.cpp.
Referenced by llvm::AArch64Subtarget::AArch64Subtarget().
parseArch()
const AArch64::ArchInfo * llvm::AArch64::parseArch (StringRef Arch)
Definition at line 154 of file AArch64TargetParser.cpp.
References A(), checkArchVersion(), llvm::ARM::getArchSynonym(), and llvm::ARM::getCanonicalArchName().
parseArchExtension()
std::optional< AArch64::ExtensionInfo > llvm::AArch64::parseArchExtension (StringRef Extension)
Definition at line 168 of file AArch64TargetParser.cpp.
References A(), llvm::StringRef::empty(), and Extensions.
Referenced by getArchExtFeature(), and llvm::AArch64::ExtensionSet::parseModifier().
parseCpu()
std::optional< AArch64::CpuInfo > llvm::AArch64::parseCpu (StringRef Name)
Definition at line 199 of file AArch64TargetParser.cpp.
References llvm::CallingConv::C, and resolveCPUAlias().
Referenced by getArchForCpu().
parseFMVExtension()
std::optional< AArch64::FMVInfo > llvm::AArch64::parseFMVExtension (StringRef Extension)
Definition at line 178 of file AArch64TargetParser.cpp.
References getFMVInfo(), and I.
Referenced by getFMVInfoFrom().
printEnabledExtensions()
void llvm::AArch64::printEnabledExtensions (const std::set< StringRef > & EnabledFeatureNames)
Definition at line 229 of file AArch64TargetParser.cpp.
References llvm::format(), llvm::left_justify(), llvm::outs(), and targetFeatureToExtension().
PrintSupportedExtensions()
void llvm::AArch64::PrintSupportedExtensions ()
Definition at line 211 of file AArch64TargetParser.cpp.
References Extensions, llvm::format(), llvm::left_justify(), and llvm::outs().
resolveCPUAlias()
StringRef llvm::AArch64::resolveCPUAlias (StringRef CPU)
Definition at line 117 of file AArch64TargetParser.cpp.
References A().
Referenced by createAArch64MCSubtargetInfo(), and parseCpu().
targetFeatureToExtension()
std::optional< AArch64::ExtensionInfo > llvm::AArch64::targetFeatureToExtension (StringRef TargetFeature)
Definition at line 191 of file AArch64TargetParser.cpp.
References Extensions.
Referenced by getFMVInfoFrom(), printEnabledExtensions(), and llvm::AArch64::ExtensionSet::reconstructFromParsedFeatures().
Variable Documentation
InstrFlagIsPTestLike
const uint64_t llvm::AArch64::InstrFlagIsPTestLike = TSFLAG_INSTR_FLAGS(0x2) static
Definition at line 874 of file AArch64InstrInfo.h.
Referenced by llvm::AArch64InstrInfo::isPTestLikeOpcode().
InstrFlagIsWhile
const uint64_t llvm::AArch64::InstrFlagIsWhile = TSFLAG_INSTR_FLAGS(0x1) static
Definition at line 873 of file AArch64InstrInfo.h.
Referenced by llvm::AArch64InstrInfo::isWhileOpcode().
ReservedFPControlBits
const uint64_t llvm::AArch64::ReservedFPControlBits = 0xfffffffff80040f8
Definition at line 43 of file AArch64ISelLowering.h.
RoundingBitsPos
const unsigned llvm::AArch64::RoundingBitsPos = 22
Definition at line 40 of file AArch64ISelLowering.h.
StackProbeMaxLoopUnroll
const unsigned llvm::AArch64::StackProbeMaxLoopUnroll = 4
Maximum number of iterations to unroll for a constant size probing loop.
Definition at line 54 of file AArch64ISelLowering.h.
StackProbeMaxUnprobedStack
const unsigned llvm::AArch64::StackProbeMaxUnprobedStack = 1024
Maximum allowed number of unprobed bytes above SP at an ABI boundary.
Definition at line 51 of file AArch64ISelLowering.h.
Referenced by llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr().
SVEBitsPerBlock
unsigned llvm::AArch64::SVEBitsPerBlock = 128 static constexpr
Definition at line 1024 of file AArch64BaseInfo.h.
Referenced by findMoreOptimalIndexType(), GenerateFixedLengthSVETBL(), llvm::AArch64TTIImpl::getCastInstrCost(), getHistogramCost(), getPackedVectorTypeFromPredicateType(), llvm::AArch64TTIImpl::getShuffleCost(), instCombineSVECmpNE(), isPackedVectorType(), isUnpackedVectorVT(), LowerSVEIntrinsicEXT(), performGatherLoadCombine(), performLD1Combine(), performScatterStoreCombine(), and llvm::AArch64Subtarget::useSVEForFixedLengthVectors().
SVEMaxBitsPerVector
unsigned llvm::AArch64::SVEMaxBitsPerVector = 2048 static constexpr
Definition at line 1025 of file AArch64BaseInfo.h.