LLVM: llvm::objcopy::dxbc Namespace Reference
llvm::objcopy::dxbc Namespace Reference
Classes
struct Part
struct Object
class DXContainerReader
class DXContainerWriter
Typedefs
using PartPred = llvm::function_ref<bool(const Part &)>
Functions
Error executeObjcopyOnBinary (const CommonConfig &Config, const DXContainerConfig &, object::DXContainerObjectFile &In, raw_ostream &Out)
Apply the transformations described by Config and DXContainerConfig to In and writes the result into Out.
static Error extractPartAsObject (StringRef PartName, StringRef OutFilename, StringRef InputFilename, const Object &Obj)
static Error dumpPartToFile (StringRef PartName, StringRef Filename, StringRef InputFilename, Object &Obj)
static Error handleArgs (const CommonConfig &Config, Object &Obj)
Typedef Documentation
PartPred
using llvm::objcopy::dxbc::PartPred = llvm::function_ref<bool(const Part &)>
Definition at line 32 of file DXContainerObject.h.
Function Documentation
dumpPartToFile()
Error llvm::objcopy::dxbc::dumpPartToFile (StringRef PartName, StringRef Filename, StringRef InputFilename, Object & Obj) static
Definition at line 47 of file DXContainerObjcopy.cpp.
References llvm::copy(), llvm::FileOutputBuffer::create(), llvm::createFileError(), llvm::ArrayRef< T >::drop_front(), E(), llvm::ArrayRef< T >::empty(), llvm::find_if(), InputFilename, P, llvm::ArrayRef< T >::size(), llvm::StringRef::str(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by handleArgs().
executeObjcopyOnBinary()
Error llvm::objcopy::dxbc::executeObjcopyOnBinary (const CommonConfig & Config, const DXContainerConfig & , object::DXContainerObjectFile & In, raw_ostream & Out)
Apply the transformations described by Config and DXContainerConfig to In and writes the result into Out.
Returns
any Error encountered whilst performing the operation.
Definition at line 121 of file DXContainerObjcopy.cpp.
References assert(), llvm::objcopy::dxbc::DXContainerReader::create(), llvm::createFileError(), E(), llvm::Expected< T >::get(), handleArgs(), llvm::objcopy::CommonConfig::InputFilename, llvm::objcopy::CommonConfig::OutputFilename, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::objcopy::dxbc::DXContainerWriter::write().
Referenced by llvm::objcopy::executeObjcopyOnBinary().
extractPartAsObject()
Error llvm::objcopy::dxbc::extractPartAsObject (StringRef PartName, StringRef OutFilename, StringRef InputFilename, const Object & Obj) static
Definition at line 24 of file DXContainerObjcopy.cpp.
References llvm::createFileError(), E(), llvm::objcopy::dxbc::Object::Header, InputFilename, P, llvm::objcopy::dxbc::Object::Parts, llvm::objcopy::dxbc::Object::recomputeHeader(), llvm::StringRef::str(), llvm::Error::success(), llvm::Write, llvm::objcopy::dxbc::DXContainerWriter::write(), and llvm::writeToOutput().
Referenced by handleArgs().
handleArgs()
Error llvm::objcopy::dxbc::handleArgs (const CommonConfig & Config, Object & Obj) static
Definition at line 81 of file DXContainerObjcopy.cpp.
References dumpPartToFile(), llvm::objcopy::CommonConfig::DumpSection, E(), llvm::objcopy::NameMatcher::empty(), extractPartAsObject(), llvm::objcopy::CommonConfig::ExtractSection, llvm::objcopy::CommonConfig::InputFilename, llvm::objcopy::NameMatcher::matches(), llvm::objcopy::CommonConfig::OnlySection, P, llvm::Error::success(), and llvm::objcopy::CommonConfig::ToRemove.
Referenced by executeObjcopyOnBinary().