LLVM: llvm::rdf Namespace Reference
llvm::rdf Namespace Reference
Namespaces
namespace detail
Classes
struct NodeAttrs
struct BuildOptions
struct NodeAddr
struct NodeAllocator
struct TargetOperandInfo
struct PackedRegisterRef
struct LaneMaskIndex
struct NodeBase
struct RefNode
struct DefNode
struct UseNode
struct PhiUseNode
struct CodeNode
struct InstrNode
struct PhiNode
struct StmtNode
struct BlockNode
struct FuncNode
struct DataFlowGraph
struct Print
struct PrintNode
struct Liveness
struct IndexedSet
struct RegisterRef
struct PhysicalRegisterInfo
struct RegisterRefEqualTo
struct RegisterRefLess
struct RegisterAggr
struct RegisterAggrMap
struct PrintLaneMaskShort
struct CopyPropagation
struct DeadCodeElimination
Typedefs
using NodeId = uint32_t
using Node = NodeAddr<NodeBase *>
using Ref = NodeAddr<RefNode *>
using Def = NodeAddr<DefNode *>
using Use = NodeAddr<UseNode *>
using PhiUse = NodeAddr<PhiUseNode *>
using Code = NodeAddr<CodeNode *>
using Instr = NodeAddr<InstrNode *>
using Phi = NodeAddr<PhiNode *>
using Stmt = NodeAddr<StmtNode *>
using Block = NodeAddr<BlockNode *>
using Func = NodeAddr<FuncNode *>
using RegisterSet = std::set<RegisterRef, RegisterRefLess>
using NodeList = SmallVector<Node, 4>
using NodeSet = std::set<NodeId>
using RegisterId = uint32_t
Functions
template<typename T>
Print (const T &, const DataFlowGraph &) -> Print< T >
raw_ostream & operator<< (raw_ostream &OS, const Print< RegisterRef > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< NodeId > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Def > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Use > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< PhiUse > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Ref > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< NodeList > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< NodeSet > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Phi > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Stmt > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Instr > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Block > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Func > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< RegisterSet > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< RegisterAggr > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< DataFlowGraph::DefStack > &P)
raw_ostream & operator<< (raw_ostream &OS, const Print< Liveness::RefMap > &P)
template<typename T>
bool disjoint (const std::set< T > &A, const std::set< T > &B)
raw_ostream & operator<< (raw_ostream &OS, const RegisterAggr &A)
raw_ostream & operator<< (raw_ostream &OS, const PrintLaneMaskShort &P)
static void printRefHeader (raw_ostream &OS, const Ref RA, const DataFlowGraph &G)
Typedef Documentation
Block
using llvm::rdf::Block = NodeAddr<BlockNode *>
Definition at line 392 of file RDFGraph.h.
Code
using llvm::rdf::Code = NodeAddr<CodeNode *>
Definition at line 388 of file RDFGraph.h.
Def
using llvm::rdf::Def = NodeAddr<DefNode *>
Definition at line 384 of file RDFGraph.h.
Func
using llvm::rdf::Func = NodeAddr<FuncNode *>
Definition at line 393 of file RDFGraph.h.
Instr
using llvm::rdf::Instr = NodeAddr<InstrNode *>
Definition at line 389 of file RDFGraph.h.
Node
using llvm::rdf::Node = NodeAddr<NodeBase *>
Definition at line 381 of file RDFGraph.h.
NodeId
using llvm::rdf::NodeId = uint32_t
Definition at line 262 of file RDFGraph.h.
NodeList
using llvm::rdf::NodeList = SmallVector<Node, 4>
Definition at line 550 of file RDFGraph.h.
NodeSet
using llvm::rdf::NodeSet = std::set<NodeId>
Definition at line 551 of file RDFGraph.h.
Phi
using llvm::rdf::Phi = NodeAddr<PhiNode *>
Definition at line 390 of file RDFGraph.h.
PhiUse
using llvm::rdf::PhiUse = NodeAddr<PhiUseNode *>
Definition at line 386 of file RDFGraph.h.
Ref
using llvm::rdf::Ref = NodeAddr<RefNode *>
Definition at line 383 of file RDFGraph.h.
RegisterId
using llvm::rdf::RegisterId = uint32_t
Definition at line 33 of file RDFRegisters.h.
RegisterSet
typedef std::set< RegisterRef, RegisterRefLess > llvm::rdf::RegisterSet = std::set<RegisterRef, RegisterRefLess>
Definition at line 450 of file RDFGraph.h.
Stmt
using llvm::rdf::Stmt = NodeAddr<StmtNode *>
Definition at line 391 of file RDFGraph.h.
Use
using llvm::rdf::Use = NodeAddr<UseNode *>
Definition at line 385 of file RDFGraph.h.
Function Documentation
disjoint()
template<typename T> bool llvm::rdf::disjoint (const std::set< T > & A, const std::set< T > & B)
Definition at line 36 of file RDFRegisters.h.
References A(), and B().
Referenced by llvm::rdf::PhysicalRegisterInfo::alias(), and llvm::rdf::DataFlowGraph::isTracked().
operator<<() [1/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Block > & P)
Definition at line 262 of file RDFGraph.cpp.
References B(), I, N, P, llvm::MachineBasicBlock::pred_size(), llvm::MachineBasicBlock::predecessors(), Print(), llvm::printMBBReference(), llvm::MachineBasicBlock::succ_size(), and llvm::MachineBasicBlock::successors().
operator<<() [2/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< DataFlowGraph::DefStack > & P)
Definition at line 317 of file RDFGraph.cpp.
References E(), I, P, and Print().
operator<<() [3/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Def > & P)
Definition at line 117 of file RDFGraph.cpp.
References N, P, Print(), and printRefHeader().
operator<<() [4/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Func > & P)
Definition at line 294 of file RDFGraph.cpp.
References I, P, and Print().
operator<<() [5/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Instr > & P)
Definition at line 247 of file RDFGraph.cpp.
References P, llvm::rdf::NodeAttrs::Phi, Print(), and llvm::rdf::NodeAttrs::Stmt.
operator<<() [6/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Liveness::RefMap > & P)
Definition at line 61 of file RDFLiveness.cpp.
References I, P, Print(), and llvm::printReg().
operator<<() [7/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< NodeId > & P)
Definition at line 49 of file RDFGraph.cpp.
References llvm::rdf::NodeAttrs::Block, llvm::rdf::NodeAttrs::Clobbering, llvm::rdf::NodeAttrs::Code, llvm::rdf::NodeAttrs::Dead, llvm::rdf::NodeAttrs::Def, llvm::rdf::NodeAttrs::flags(), llvm::rdf::NodeAttrs::Func, llvm::rdf::NodeAttrs::kind(), P, llvm::rdf::NodeAttrs::Phi, llvm::rdf::NodeAttrs::Preserving, llvm::rdf::NodeAttrs::Ref, llvm::rdf::NodeAttrs::Shadow, llvm::rdf::NodeAttrs::Stmt, llvm::rdf::NodeAttrs::type(), llvm::rdf::NodeAttrs::Undef, and llvm::rdf::NodeAttrs::Use.
operator<<() [8/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< NodeList > & P)
Definition at line 174 of file RDFGraph.cpp.
References I, N, P, and Print().
operator<<() [9/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< NodeSet > & P)
Definition at line 184 of file RDFGraph.cpp.
References I, N, P, and Print().
operator<<() [10/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Phi > & P)
Definition at line 217 of file RDFGraph.cpp.
References P, and Print().
operator<<() [11/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< PhiUse > & P)
Definition at line 145 of file RDFGraph.cpp.
References N, P, Print(), and printRefHeader().
operator<<() [12/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Ref > & P)
Definition at line 159 of file RDFGraph.cpp.
References llvm::rdf::NodeAttrs::Def, P, llvm::rdf::NodeAttrs::PhiRef, and llvm::rdf::NodeAttrs::Use.
operator<<() [13/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< RegisterAggr > & P)
Definition at line 312 of file RDFGraph.cpp.
References P.
operator<<() [14/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< RegisterRef > & P)
Definition at line 44 of file RDFGraph.cpp.
References P.
operator<<() [15/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< RegisterSet > & P)
Definition at line 304 of file RDFGraph.cpp.
References I, P, and Print().
operator<<() [16/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Stmt > & P)
Definition at line 223 of file RDFGraph.cpp.
References llvm::find_if(), MI, Opc, P, Print(), llvm::printMBBReference(), and T.
operator<<() [17/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const Print< Use > & P)
Definition at line 134 of file RDFGraph.cpp.
References N, P, Print(), and printRefHeader().
operator<<() [18/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const PrintLaneMaskShort & P)
Definition at line 404 of file RDFRegisters.cpp.
References llvm::format(), P, and llvm::PrintLaneMask().
operator<<() [19/19]
raw_ostream & llvm::rdf::operator<< (raw_ostream & OS, const RegisterAggr & A)
Definition at line 399 of file RDFRegisters.cpp.
References A().
Print()
template<typename T> llvm::rdf::Print (const T & , const DataFlowGraph &) -> Print< T >
References T.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), printRefHeader(), and llvm::rdf::CopyPropagation::run().
printRefHeader()
void llvm::rdf::printRefHeader (raw_ostream & OS, const Ref RA, const DataFlowGraph & G) static
Definition at line 110 of file RDFGraph.cpp.
References llvm::rdf::NodeAttrs::Fixed, G, Print(), and RA.
Referenced by operator<<(), operator<<(), and operator<<().