LLVM: llvm::object::DirectX Namespace Reference
llvm::object::DirectX Namespace Reference
Classes
struct RootParameterView
struct RootConstantView
struct RootDescriptorView
struct DescriptorTable
struct DescriptorTableView
class RootSignature
class PSVRuntimeInfo
class Signature
Functions
static Error parseFailed (const Twine &Msg)
Function Documentation
parseFailed()
Error llvm::object::DirectX::parseFailed (const Twine & Msg) static
Definition at line 217 of file DXContainer.h.
References llvm::make_error(), llvm::object::parse_failed, and llvm::Twine::str().
Referenced by llvm::object::DirectX::RootSignature::getParameter(), llvm::object::DirectX::Signature::initialize(), llvm::object::DirectX::PSVRuntimeInfo::parse(), and llvm::object::DirectX::RootSignature::parse().