LLVM: llvm::offloading Namespace Reference
llvm::offloading Namespace Reference
Namespaces
namespace amdgpu
namespace intel
Classes
struct SYCLJITOptions
struct EntryTy
This is the record of an object that just be registered with the offloading runtime.
Typedefs
using EntryArrayTy = std::pair<GlobalVariable *, GlobalVariable *>
using ByteArray = SmallVector<unsigned char, 0>
using PropertyValue = std::variant<uint32_t, ByteArray>
using PropertySet = std::map<std::string, PropertyValue>
using PropertySetRegistry = std::map<std::string, PropertySet>
Enumerations
enum OffloadEntryKindFlag : uint32_t {
OffloadGlobalEntry = 0x0 , OffloadGlobalManagedEntry = 0x1 , OffloadGlobalSurfaceEntry = 0x2 , OffloadGlobalTextureEntry = 0x3 ,
OffloadGlobalExtern = 0x1 << 3 , OffloadGlobalConstant = 0x1 << 4 , OffloadGlobalNormalized = 0x1 << 5
}
Offloading entry flags for CUDA / HIP.
Functions
LLVM_ABI llvm::Error wrapOpenMPBinaries (llvm::Module &M, llvm::ArrayRef< llvm::ArrayRef< char > > Images, EntryArrayTy EntryArray, llvm::StringRef Suffix="", bool Relocatable=false)
Wraps the input device images into the module M as global symbols and registers the images with the OpenMP Offloading runtime libomptarget.
LLVM_ABI llvm::Error wrapCudaBinary (llvm::Module &M, llvm::ArrayRef< char > Images, EntryArrayTy EntryArray, llvm::StringRef Suffix="", bool EmitSurfacesAndTextures=true)
Wraps the input fatbinary image into the module M as global symbols and registers the images with the CUDA runtime.
LLVM_ABI llvm::Error wrapHIPBinary (llvm::Module &M, llvm::ArrayRef< char > Images, EntryArrayTy EntryArray, llvm::StringRef Suffix="", bool EmitSurfacesAndTextures=true)
Wraps the input bundled image into the module M as global symbols and registers the images with the HIP runtime.
LLVM_ABI llvm::Error wrapSYCLBinaries (llvm::Module &M, llvm::ArrayRef< char > Buffer, SYCLJITOptions Options=SYCLJITOptions())
Wraps OffloadBinaries in the given Buffers into the module M as global symbols and registers the images with the SYCL Runtime.
LLVM_ABI void writePropertiesToJSON (const PropertySetRegistry &P, raw_ostream &O)
LLVM_ABI Expected< PropertySetRegistry > readPropertiesFromJSON (MemoryBufferRef Buf)
LLVM_ABI StructType * getEntryTy (Module &M)
Returns the type of the offloading entry we use to store kernels and globals that will be registered with the offloading runtime.
LLVM_ABI GlobalVariable * emitOffloadingEntry (Module &M, object::OffloadKind Kind, Constant *Addr, StringRef Name, uint64_t Size, uint32_t Flags, uint64_t Data, Constant *AuxAddr=nullptr, StringRef SectionName="llvm_offload_entries")
Create an offloading section struct used to register this global at runtime.
LLVM_ABI std::pair< Constant *, GlobalVariable * > getOffloadingEntryInitializer (Module &M, object::OffloadKind Kind, Constant *Addr, StringRef Name, uint64_t Size, uint32_t Flags, uint64_t Data, Constant *AuxAddr)
Create a constant struct initializer used to register this global at runtime.
LLVM_ABI std::pair< GlobalVariable *, GlobalVariable * > getOffloadEntryArray (Module &M, StringRef SectionName="llvm_offload_entries")
Creates a pair of globals used to iterate the array of offloading entries by accessing the section variables provided by the linker.
Typedef Documentation
ByteArray
using llvm::offloading::ByteArray = SmallVector<unsigned char, 0>
Definition at line 25 of file PropertySet.h.
EntryArrayTy
using llvm::offloading::EntryArrayTy = std::pair<GlobalVariable *, GlobalVariable *>
Definition at line 20 of file OffloadWrapper.h.
PropertySet
using llvm::offloading::PropertySet = std::map<std::string, PropertyValue>
Definition at line 27 of file PropertySet.h.
PropertySetRegistry
using llvm::offloading::PropertySetRegistry = std::map<std::string, PropertySet>
Definition at line 28 of file PropertySet.h.
PropertyValue
using llvm::offloading::PropertyValue = std::variant<uint32_t, ByteArray>
Definition at line 26 of file PropertySet.h.
Enumeration Type Documentation
OffloadEntryKindFlag
enum llvm::offloading::OffloadEntryKindFlag : uint32_t
Offloading entry flags for CUDA / HIP.
The first three bits indicate the type of entry while the others are a bit field for additional information.
Enumerator
OffloadGlobalEntry
Mark the entry as a global entry.
This indicates the presense of a kernel if the size size field is zero and a variable otherwise.
OffloadGlobalManagedEntry
Mark the entry as a managed global variable.
OffloadGlobalSurfaceEntry
Mark the entry as a surface variable.
OffloadGlobalTextureEntry
Mark the entry as a texture variable.
OffloadGlobalExtern
Mark the entry as being extern.
OffloadGlobalConstant
Mark the entry as being constant.
OffloadGlobalNormalized
Mark the entry as being a normalized surface.
Definition at line 51 of file Utility.h.
Function Documentation
emitOffloadingEntry()
GlobalVariable * llvm::offloading::emitOffloadingEntry (Module & M, object::OffloadKind Kind, Constant * Addr, StringRef Name, uint64_t Size, uint32_t Flags, uint64_t Data, Constant * AuxAddr = nullptr, StringRef SectionName = "llvm_offload_entries")
Create an offloading section struct used to register this global at runtime.
Parameters
M The module to be used
Addr The pointer to the global being registered.
Kind The offloading language expected to consume this.
Name The symbol name associated with the global.
Size The size in bytes of the global (0 for functions).
Flags Flags associated with the entry.
Data Extra data storage associated with the entry.
SectionName The section this entry will be placed at.
AuxAddr An extra pointer if needed.
Returns
The emitted global variable containing the offloading entry.
Definition at line 86 of file Utility.cpp.
References llvm::Data, llvm::object::OffloadBinary::getAlignment(), getEntryTy(), getOffloadingEntryInitializer(), llvm::Triple::isNVPTX(), llvm::Triple::isOSBinFormatCOFF(), llvm::GlobalValue::NotThreadLocal, Size, and llvm::GlobalValue::WeakAnyLinkage.
Referenced by llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), and llvm::OpenMPIRBuilder::createOffloadEntry().
getEntryTy()
StructType * llvm::offloading::getEntryTy (Module & M)
Returns the type of the offloading entry we use to store kernels and globals that will be registered with the offloading runtime.
Definition at line 26 of file Utility.cpp.
References llvm::CallingConv::C, llvm::StructType::create(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::StructType::getTypeByName(), and llvm::PointerType::getUnqual().
Referenced by emitOffloadingEntry(), getOffloadEntryArray(), and getOffloadingEntryInitializer().
getOffloadEntryArray()
std::pair< GlobalVariable *, GlobalVariable * > llvm::offloading::getOffloadEntryArray (Module & M, StringRef SectionName = "llvm_offload_entries")
Creates a pair of globals used to iterate the array of offloading entries by accessing the section variables provided by the linker.
Definition at line 113 of file Utility.cpp.
References llvm::appendToCompilerUsed(), llvm::GlobalValue::ExternalLinkage, llvm::ArrayType::get(), llvm::ConstantAggregateZero::get(), llvm::object::OffloadBinary::getAlignment(), getEntryTy(), llvm::GlobalValue::HiddenVisibility, llvm::GlobalValue::InternalLinkage, llvm::Triple::isOSBinFormatCOFF(), llvm::Triple::isOSBinFormatELF(), and llvm::GlobalValue::WeakODRLinkage.
getOffloadingEntryInitializer()
std::pair< Constant *, GlobalVariable * > llvm::offloading::getOffloadingEntryInitializer (Module & M, object::OffloadKind Kind, Constant * Addr, StringRef Name, uint64_t Size, uint32_t Flags, uint64_t Data, Constant * AuxAddr)
Create a constant struct initializer used to register this global at runtime.
Returns
the constant struct and the global variable holding the symbol name.
Definition at line 40 of file Utility.cpp.
References llvm::NamedMDNode::addOperand(), llvm::Data, llvm::ConstantAsMetadata::get(), llvm::ConstantStruct::get(), llvm::MDNode::get(), getEntryTy(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantDataArray::getString(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::GlobalValue::Global, llvm::Int32Ty, llvm::GlobalValue::InternalLinkage, llvm::Triple::isNVPTX(), and Size.
Referenced by emitOffloadingEntry().
readPropertiesFromJSON()
Expected< PropertySetRegistry > llvm::offloading::readPropertiesFromJSON (MemoryBufferRef Buf)
Definition at line 67 of file PropertySet.cpp.
References assert(), createStringErrorV(), llvm::MemoryBufferRef::getBuffer(), llvm::json::parse(), readPropertyValueFromJSON(), llvm::Expected< T >::takeError(), and llvm::toString().
wrapCudaBinary()
Error llvm::offloading::wrapCudaBinary (llvm::Module & M, llvm::ArrayRef< char > Images, EntryArrayTy EntryArray, llvm::StringRef Suffix = "", bool EmitSurfacesAndTextures = true)
Wraps the input fatbinary image into the module M as global symbols and registers the images with the CUDA runtime.
Parameters
EntryArray Optional pair pointing to the __start and __stop symbols holding the __tgt_offload_entry array.
Suffix An optional suffix appended to the emitted symbols.
EmitSurfacesAndTextures Whether to emit surface and textures registration code. It defaults to false.
Definition at line 1042 of file OffloadWrapper.cpp.
References llvm::createStringError(), llvm::inconvertibleErrorCode(), and llvm::Error::success().
wrapHIPBinary()
Error llvm::offloading::wrapHIPBinary (llvm::Module & M, llvm::ArrayRef< char > Images, EntryArrayTy EntryArray, llvm::StringRef Suffix = "", bool EmitSurfacesAndTextures = true)
Wraps the input bundled image into the module M as global symbols and registers the images with the HIP runtime.
Parameters
EntryArray Optional pair pointing to the __start and __stop symbols holding the __tgt_offload_entry array.
Suffix An optional suffix appended to the emitted symbols.
EmitSurfacesAndTextures Whether to emit surface and textures registration code. It defaults to false.
Definition at line 1056 of file OffloadWrapper.cpp.
References llvm::createStringError(), llvm::inconvertibleErrorCode(), and llvm::Error::success().
wrapOpenMPBinaries()
Error llvm::offloading::wrapOpenMPBinaries (llvm::Module & M, llvm::ArrayRef< llvm::ArrayRef< char > > Images, EntryArrayTy EntryArray, llvm::StringRef Suffix = "", bool Relocatable = false)
Wraps the input device images into the module M as global symbols and registers the images with the OpenMP Offloading runtime libomptarget.
Parameters
EntryArray Optional pair pointing to the __start and __stop symbols holding the __tgt_offload_entry array.
Suffix An optional suffix appended to the emitted symbols.
Relocatable Indicate if we need to change the offloading section to create a relocatable object.
Definition at line 1030 of file OffloadWrapper.cpp.
References llvm::createStringError(), llvm::inconvertibleErrorCode(), and llvm::Error::success().
wrapSYCLBinaries()
Error llvm::offloading::wrapSYCLBinaries (llvm::Module & M, llvm::ArrayRef< char > Buffer, SYCLJITOptions Options = SYCLJITOptions())
Wraps OffloadBinaries in the given Buffers into the module M as global symbols and registers the images with the SYCL Runtime.
Parameters
Options Compiler and linker options to be encoded for the later use by a runtime for JIT compilation. Not used for AOT.
Definition at line 1069 of file OffloadWrapper.cpp.
References llvm::ArrayRef< T >::begin(), llvm::createStringError(), llvm::object::extractOffloadBinaries(), llvm::inconvertibleErrorCode(), Options, llvm::ArrayRef< T >::size(), and llvm::Error::success().
writePropertiesToJSON()
void llvm::offloading::writePropertiesToJSON (const PropertySetRegistry & P, raw_ostream & O)
Definition at line 17 of file PropertySet.cpp.
References llvm::json::OStream::attribute(), llvm::json::OStream::attributeObject(), llvm::encodeBase64(), llvm_unreachable, and llvm::json::OStream::object().