LLVM: adjust Namespace Reference
adjust Namespace Reference
Namespaces
namespace ldi
Fixups relating to the LDI instruction.
Functions
static void unsigned_width (unsigned Width, uint64_t Value, std::string Description, const MCFixup &Fixup, MCContext *Ctx)
static void adjustBranch (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
Adjusts the value of a branch target before fixup application.
static bool adjustRelativeBranch (unsigned Size, const MCFixup &Fixup, uint64_t &Value, const MCSubtargetInfo *STI)
Adjusts the value of a relative branch target before fixup application.
static void fixup_call (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
22-bit absolute fixup.
static void fixup_7_pcrel (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
7-bit PC-relative fixup.
static void fixup_13_pcrel (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
12-bit PC-relative fixup.
static void fixup_6 (const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
6-bit fixup for the immediate operand of the STD/LDD family of instructions.
static void fixup_6_adiw (const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
6-bit fixup for the immediate operand of the ADIW family of instructions.
static void fixup_port5 (const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
5-bit port number fixup on the SBIC family of instructions.
static void fixup_port6 (const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
6-bit port number fixup on the IN family of instructions.
static void fixup_lds_sts_16 (const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
7-bit data space address fixup for the LDS/STS instructions on AVRTiny.
static void pm (uint64_t &Value)
Adjusts a program memory address.
Function Documentation
adjustBranch()
void adjust::adjustBranch (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
Adjusts the value of a branch target before fixup application.
Definition at line 49 of file AVRAsmBackend.cpp.
References llvm::AVR::fixups::adjustBranchTarget(), Fixup, Size, and unsigned_width().
Referenced by fixup_call().
adjustRelativeBranch()
bool adjust::adjustRelativeBranch (unsigned Size, const MCFixup & Fixup, uint64_t & Value, const MCSubtargetInfo * STI) static
Adjusts the value of a relative branch target before fixup application.
Definition at line 60 of file AVRAsmBackend.cpp.
References llvm::AVR::fixups::adjustBranchTarget(), assert(), Fixup, llvm::MCSubtargetInfo::hasFeature(), llvm::isIntN(), and Size.
Referenced by fixup_13_pcrel(), and fixup_7_pcrel().
fixup_13_pcrel()
void adjust::fixup_13_pcrel (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
12-bit PC-relative fixup.
Yes, the fixup is 12 bits even though the name says otherwise.
Resolves to: 0000 kkkk kkkk kkkk Offset of 0 (so the result isn't left-shifted before application).
Definition at line 131 of file AVRAsmBackend.cpp.
References adjustRelativeBranch(), Fixup, llvm_unreachable, and Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
fixup_6()
void adjust::fixup_6 (const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
6-bit fixup for the immediate operand of the STD/LDD family of instructions.
Resolves to: 10q0 qq10 0000 1qqq
Definition at line 146 of file AVRAsmBackend.cpp.
References Fixup, and unsigned_width().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
fixup_6_adiw()
void adjust::fixup_6_adiw (const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
6-bit fixup for the immediate operand of the ADIW family of instructions.
Resolves to: 0000 0000 kk00 kkkk
Definition at line 157 of file AVRAsmBackend.cpp.
References Fixup, and unsigned_width().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
fixup_7_pcrel()
void adjust::fixup_7_pcrel (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
7-bit PC-relative fixup.
Resolves to: 0000 00kk kkkk k000 Offset of 0 (so the result is left shifted by 3 bits before application).
Definition at line 115 of file AVRAsmBackend.cpp.
References adjustRelativeBranch(), Fixup, llvm_unreachable, and Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
fixup_call()
void adjust::fixup_call (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
22-bit absolute fixup.
Resolves to: 1001 kkkk 010k kkkk kkkk kkkk 111k kkkk
Offset of 0 (so the result is left shifted by 3 bits before application).
Definition at line 99 of file AVRAsmBackend.cpp.
References adjustBranch(), Fixup, and Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
fixup_lds_sts_16()
void adjust::fixup_lds_sts_16 (const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
7-bit data space address fixup for the LDS/STS instructions on AVRTiny.
Resolves to: 1010 ikkk dddd kkkk
Definition at line 190 of file AVRAsmBackend.cpp.
References Fixup, and unsigned_width().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
fixup_port5()
void adjust::fixup_port5 (const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
5-bit port number fixup on the SBIC family of instructions.
Resolves to: 0000 0000 AAAA A000
Definition at line 168 of file AVRAsmBackend.cpp.
References Fixup, and unsigned_width().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
fixup_port6()
void adjust::fixup_port6 (const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
6-bit port number fixup on the IN family of instructions.
Resolves to: 1011 0AAd dddd AAAA
Definition at line 180 of file AVRAsmBackend.cpp.
References Fixup, and unsigned_width().
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
pm()
void adjust::pm (uint64_t & Value) static
Adjusts a program memory address.
This is a simple right-shift.
Definition at line 198 of file AVRAsmBackend.cpp.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
unsigned_width()
void adjust::unsigned_width (unsigned Width, uint64_t Value, std::string Description, const MCFixup & Fixup, MCContext * Ctx) static
Definition at line 33 of file AVRAsmBackend.cpp.
References Fixup, llvm::isUIntN(), and llvm::maxUIntN().
Referenced by adjustBranch(), llvm::AVRAsmBackend::adjustFixupValue(), fixup_6(), fixup_6_adiw(), fixup_lds_sts_16(), fixup_port5(), and fixup_port6().