LLVM: llvm::pgo Namespace Reference
llvm::pgo Namespace Reference
Functions
LLVM_ABI CallBase & promoteIndirectCall (CallBase &CB, Function *F, uint64_t Count, uint64_t TotalCount, bool AttachProfToDirectCall, OptimizationRemarkEmitter *ORE)
Function Documentation
promoteIndirectCall()
CallBase & llvm::pgo::promoteIndirectCall (CallBase & CB, Function * F, uint64_t Count, uint64_t TotalCount, bool AttachProfToDirectCall, OptimizationRemarkEmitter * ORE)
Definition at line 666 of file IndirectCallPromotion.cpp.
References llvm::Count, createBranchWeights(), DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), llvm::Value::getContext(), llvm::promoteCallWithIfThenElse(), and llvm::setFittedBranchWeights().