LLVM: llvm::mir2vec Namespace Reference
llvm::mir2vec Namespace Reference
Classes
class MIRVocabulary
Class for storing and accessing the MIR2Vec vocabulary.
class MIREmbedder
Base class for MIR embedders.
class SymbolicMIREmbedder
Class for computing Symbolic embeddings Symbolic embeddings are constructed based on the entity-level representations obtained from the MIR Vocabulary.
Typedefs
using Embedding = ir2vec::Embedding
using MachineInstEmbeddingsMap = DenseMap<const MachineInstr *, Embedding>
using MachineBlockEmbeddingsMap
Functions
cl::OptionCategory MIR2VecCategory ("MIR2Vec Options")
cl::opt< float > OpcWeight ("mir2vec-opc-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for machine opcode embeddings"), cl::cat(MIR2VecCategory))
cl::opt< float > CommonOperandWeight ("mir2vec-common-operand-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for common operand embeddings"), cl::cat(MIR2VecCategory))
cl::opt< float > RegOperandWeight ("mir2vec-reg-operand-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for register operand embeddings"), cl::cat(MIR2VecCategory))
Variables
LLVM_ABI llvm::cl::OptionCategory MIR2VecCategory
LLVM_ABI cl::opt< float > OpcWeight
LLVM_ABI cl::opt< float > CommonOperandWeight
LLVM_ABI cl::opt< float > RegOperandWeight
static cl::opt< std::string > VocabFile ("mir2vec-vocab-path", cl::Optional, cl::desc("Path to the vocabulary file for MIR2Vec"), cl::init(""), cl::cat(MIR2VecCategory))
cl::opt< MIR2VecKind > MIR2VecEmbeddingKind ("mir2vec-kind", cl::Optional, cl::values(clEnumValN(MIR2VecKind::Symbolic, "symbolic", "Generate symbolic embeddings for MIR")), cl::init(MIR2VecKind::Symbolic), cl::desc("MIR2Vec embedding kind"), cl::cat(MIR2VecCategory))
Typedef Documentation
Embedding
using llvm::mir2vec::Embedding = ir2vec::Embedding
Definition at line 79 of file MIR2Vec.h.
MachineBlockEmbeddingsMap
using llvm::mir2vec::MachineBlockEmbeddingsMap
Initial value:
DenseMap<const MachineBasicBlock *, Embedding>
Definition at line 81 of file MIR2Vec.h.
MachineInstEmbeddingsMap
using llvm::mir2vec::MachineInstEmbeddingsMap = DenseMap<const MachineInstr *, Embedding>
Definition at line 80 of file MIR2Vec.h.
Function Documentation
CommonOperandWeight()
cl::opt< float > llvm::mir2vec::CommonOperandWeight ("mir2vec-common-operand-weight" , cl::Optional , cl::init(1.0) , cl::desc("Weight for common operand embeddings") , cl::cat(MIR2VecCategory))
References llvm::cl::init(), MIR2VecCategory, and llvm::cl::Optional.
MIR2VecCategory()
cl::OptionCategory llvm::mir2vec::MIR2VecCategory ("MIR2Vec Options")
OpcWeight()
cl::opt< float > llvm::mir2vec::OpcWeight ("mir2vec-opc-weight" , cl::Optional , cl::init(1.0) , cl::desc("Weight for machine opcode embeddings") , cl::cat(MIR2VecCategory))
References llvm::cl::init(), MIR2VecCategory, and llvm::cl::Optional.
RegOperandWeight()
cl::opt< float > llvm::mir2vec::RegOperandWeight ("mir2vec-reg-operand-weight" , cl::Optional , cl::init(1.0) , cl::desc("Weight for register operand embeddings") , cl::cat(MIR2VecCategory))
References llvm::cl::init(), MIR2VecCategory, and llvm::cl::Optional.
Variable Documentation
CommonOperandWeight
cl::opt< float > llvm::mir2vec::CommonOperandWeight("mir2vec-common-operand-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for common operand embeddings"), cl::cat(MIR2VecCategory))
Definition at line 77 of file MIR2Vec.h.
MIR2VecCategory
cl::OptionCategory llvm::mir2vec::MIR2VecCategory("MIR2Vec Options")
Referenced by CommonOperandWeight(), OpcWeight(), and RegOperandWeight().
MIR2VecEmbeddingKind
cl::opt< MIR2VecKind > llvm::mir2vec::MIR2VecEmbeddingKind("mir2vec-kind", cl::Optional, cl::values(clEnumValN(MIR2VecKind::Symbolic, "symbolic", "Generate symbolic embeddings for MIR")), cl::init(MIR2VecKind::Symbolic), cl::desc("MIR2Vec embedding kind"), cl::cat(MIR2VecCategory)) ("mir2vec-kind" , cl::Optional , cl::values(clEnumValN(MIR2VecKind::Symbolic, "symbolic", "Generate symbolic embeddings for MIR")) , cl::init(MIR2VecKind::Symbolic) , cl::desc("MIR2Vec embedding kind") , cl::cat(MIR2VecCategory))
Referenced by llvm::MIR2VecPrinterLegacyPass::runOnMachineFunction().
OpcWeight
cl::opt< float > llvm::mir2vec::OpcWeight("mir2vec-opc-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for machine opcode embeddings"), cl::cat(MIR2VecCategory))
RegOperandWeight
cl::opt< float > llvm::mir2vec::RegOperandWeight("mir2vec-reg-operand-weight", cl::Optional, cl::init(1.0), cl::desc("Weight for register operand embeddings"), cl::cat(MIR2VecCategory))
Definition at line 77 of file MIR2Vec.h.
VocabFile
cl::opt< std::string > llvm::mir2vec::VocabFile("mir2vec-vocab-path", cl::Optional, cl::desc("Path to the vocabulary file for MIR2Vec"), cl::init(""), cl::cat(MIR2VecCategory)) ("mir2vec-vocab-path" , cl::Optional , cl::desc("Path to the vocabulary file for MIR2Vec") , cl::init("") , cl::cat(MIR2VecCategory)) static