LLVM: llvm::Sparc Namespace Reference
llvm::Sparc Namespace Reference
Enumerations
enum Fixups { fixup_sparc_call30 = FirstTargetFixupKind , fixup_sparc_13 , LastTargetFixupKind , NumTargetFixupKinds = LastTargetFixupKind - FirstTargetFixupKind }
Functions
uint16_t parseSpecifier (StringRef name)
StringRef getSpecifierName (uint16_t S)
Enumeration Type Documentation
Fixups
enum llvm::Sparc::Fixups
Enumerator
fixup_sparc_call30
fixup_sparc_13
fixup_sparc_13 - 13-bit fixup
LastTargetFixupKind
NumTargetFixupKinds
Definition at line 18 of file SparcFixupKinds.h.
Function Documentation
getSpecifierName()
StringRef llvm::Sparc::getSpecifierName (uint16_t S)
Definition at line 22 of file SparcMCExpr.cpp.
References llvm_unreachable.
Referenced by llvm::SparcELFMCAsmInfo::printSpecifierExpr().
parseSpecifier()
uint16_t llvm::Sparc::parseSpecifier (StringRef name)
Definition at line 69 of file SparcMCExpr.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and name.