LLVM: llvm::AMDGPU::DepCtr Namespace Reference
llvm::AMDGPU::DepCtr Namespace Reference
Functions
int getDefaultDepCtrEncoding (const MCSubtargetInfo &STI)
bool isSymbolicDepCtrEncoding (unsigned Code, bool &HasNonDefaultVal, const MCSubtargetInfo &STI)
bool decodeDepCtr (unsigned Code, int &Id, StringRef &Name, unsigned &Val, bool &IsDefault, const MCSubtargetInfo &STI)
int encodeDepCtr (const StringRef Name, int64_t Val, unsigned &UsedOprMask, const MCSubtargetInfo &STI)
unsigned getVaVdstBitMask ()
unsigned getVmVsrcBitMask ()
unsigned decodeFieldVmVsrc (unsigned Encoded)
unsigned decodeFieldVaVdst (unsigned Encoded)
unsigned decodeFieldSaSdst (unsigned Encoded)
unsigned decodeFieldVaSdst (unsigned Encoded)
unsigned decodeFieldVaVcc (unsigned Encoded)
unsigned decodeFieldVaSsrc (unsigned Encoded)
unsigned decodeFieldHoldCnt (unsigned Encoded)
unsigned encodeFieldVmVsrc (unsigned Encoded, unsigned VmVsrc)
unsigned encodeFieldVmVsrc (unsigned VmVsrc, const MCSubtargetInfo &STI)
unsigned encodeFieldVaVdst (unsigned Encoded, unsigned VaVdst)
unsigned encodeFieldVaVdst (unsigned VaVdst, const MCSubtargetInfo &STI)
unsigned encodeFieldSaSdst (unsigned Encoded, unsigned SaSdst)
unsigned encodeFieldSaSdst (unsigned SaSdst, const MCSubtargetInfo &STI)
unsigned encodeFieldVaSdst (unsigned Encoded, unsigned VaSdst)
unsigned encodeFieldVaSdst (unsigned VaSdst, const MCSubtargetInfo &STI)
unsigned encodeFieldVaVcc (unsigned Encoded, unsigned VaVcc)
unsigned encodeFieldVaVcc (unsigned VaVcc, const MCSubtargetInfo &STI)
unsigned encodeFieldVaSsrc (unsigned Encoded, unsigned VaSsrc)
unsigned encodeFieldVaSsrc (unsigned VaSsrc, const MCSubtargetInfo &STI)
unsigned encodeFieldHoldCnt (unsigned Encoded, unsigned HoldCnt)
unsigned encodeFieldHoldCnt (unsigned HoldCnt, const MCSubtargetInfo &STI)
Variables
const CustomOperandVal DepCtrInfo []
const int DEP_CTR_SIZE
Function Documentation
decodeDepCtr()
bool llvm::AMDGPU::DepCtr::decodeDepCtr (unsigned Code, int & Id, StringRef & Name, unsigned & Val, bool & IsDefault, const MCSubtargetInfo & STI)
Definition at line 2063 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::decodeCustomOperand(), DEP_CTR_SIZE, and DepCtrInfo.
Referenced by llvm::AMDGPUInstPrinter::printDepCtr().
decodeFieldHoldCnt()
unsigned llvm::AMDGPU::DepCtr::decodeFieldHoldCnt (unsigned Encoded)
Returns
Decoded HoldCnt from given immediate Encoded.
Definition at line 2103 of file AMDGPUBaseInfo.cpp.
decodeFieldSaSdst()
unsigned llvm::AMDGPU::DepCtr::decodeFieldSaSdst (unsigned Encoded)
Returns
Decoded SaSdst from given immediate Encoded.
Definition at line 2087 of file AMDGPUBaseInfo.cpp.
decodeFieldVaSdst()
unsigned llvm::AMDGPU::DepCtr::decodeFieldVaSdst (unsigned Encoded)
Returns
Decoded VaSdst from given immediate Encoded.
Definition at line 2091 of file AMDGPUBaseInfo.cpp.
decodeFieldVaSsrc()
unsigned llvm::AMDGPU::DepCtr::decodeFieldVaSsrc (unsigned Encoded)
Returns
Decoded SaSrc from given immediate Encoded.
Definition at line 2099 of file AMDGPUBaseInfo.cpp.
decodeFieldVaVcc()
unsigned llvm::AMDGPU::DepCtr::decodeFieldVaVcc (unsigned Encoded)
Returns
Decoded VaVcc from given immediate Encoded.
Definition at line 2095 of file AMDGPUBaseInfo.cpp.
decodeFieldVaVdst()
unsigned llvm::AMDGPU::DepCtr::decodeFieldVaVdst (unsigned Encoded)
Returns
Decoded VaVdst from given immediate Encoded.
Definition at line 2083 of file AMDGPUBaseInfo.cpp.
decodeFieldVmVsrc()
unsigned llvm::AMDGPU::DepCtr::decodeFieldVmVsrc (unsigned Encoded)
Returns
Decoded VmVsrc from given immediate Encoded.
Definition at line 2079 of file AMDGPUBaseInfo.cpp.
encodeDepCtr()
int llvm::AMDGPU::DepCtr::encodeDepCtr (const StringRef Name, int64_t Val, unsigned & UsedOprMask, const MCSubtargetInfo & STI)
Definition at line 2069 of file AMDGPUBaseInfo.cpp.
References DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::encodeCustomOperand().
encodeFieldHoldCnt() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldHoldCnt (unsigned Encoded, unsigned HoldCnt)
Returns
Encoded combined with encoded HoldCnt.
Definition at line 2161 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldHoldCnt().
encodeFieldHoldCnt() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldHoldCnt (unsigned HoldCnt, const MCSubtargetInfo & STI)
Returns
HoldCnt as an encoded Depctr immediate.
Definition at line 2165 of file AMDGPUBaseInfo.cpp.
References encodeFieldHoldCnt(), and getDefaultDepCtrEncoding().
encodeFieldSaSdst() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldSaSdst (unsigned Encoded, unsigned SaSdst)
Returns
Encoded combined with encoded SaSdst.
Definition at line 2125 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldSaSdst(), and llvm::SIInstrInfo::insertIndirectBranch().
encodeFieldSaSdst() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldSaSdst (unsigned SaSdst, const MCSubtargetInfo & STI)
Returns
SaSdst as an encoded Depctr immediate.
Definition at line 2129 of file AMDGPUBaseInfo.cpp.
References encodeFieldSaSdst(), and getDefaultDepCtrEncoding().
encodeFieldVaSdst() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaSdst (unsigned Encoded, unsigned VaSdst)
Returns
Encoded combined with encoded VaSdst.
Definition at line 2134 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldVaSdst().
encodeFieldVaSdst() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaSdst (unsigned VaSdst, const MCSubtargetInfo & STI)
Returns
VaSdst as an encoded Depctr immediate.
Definition at line 2138 of file AMDGPUBaseInfo.cpp.
References encodeFieldVaSdst(), and getDefaultDepCtrEncoding().
encodeFieldVaSsrc() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaSsrc (unsigned Encoded, unsigned VaSsrc)
Returns
Encoded combined with encoded VaSsrc.
Definition at line 2152 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldVaSsrc().
encodeFieldVaSsrc() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaSsrc (unsigned VaSsrc, const MCSubtargetInfo & STI)
Returns
VaSsrc as an encoded Depctr immediate.
Definition at line 2156 of file AMDGPUBaseInfo.cpp.
References encodeFieldVaSsrc(), and getDefaultDepCtrEncoding().
encodeFieldVaVcc() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaVcc (unsigned Encoded, unsigned VaVcc)
Returns
Encoded combined with encoded VaVcc.
Definition at line 2143 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldVaVcc().
encodeFieldVaVcc() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaVcc (unsigned VaVcc, const MCSubtargetInfo & STI)
Returns
VaVcc as an encoded Depctr immediate.
Definition at line 2147 of file AMDGPUBaseInfo.cpp.
References encodeFieldVaVcc(), and getDefaultDepCtrEncoding().
encodeFieldVaVdst() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaVdst (unsigned Encoded, unsigned VaVdst)
Returns
Encoded combined with encoded VaVdst.
Definition at line 2116 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldVaVdst().
encodeFieldVaVdst() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaVdst (unsigned VaVdst, const MCSubtargetInfo & STI)
Returns
VaVdst as an encoded Depctr immediate.
Definition at line 2120 of file AMDGPUBaseInfo.cpp.
References encodeFieldVaVdst(), and getDefaultDepCtrEncoding().
encodeFieldVmVsrc() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVmVsrc (unsigned Encoded, unsigned VmVsrc)
Returns
Encoded combined with encoded VmVsrc.
Definition at line 2107 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldVmVsrc().
encodeFieldVmVsrc() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVmVsrc (unsigned VmVsrc, const MCSubtargetInfo & STI)
Returns
VmVsrc as an encoded Depctr immediate.
Definition at line 2111 of file AMDGPUBaseInfo.cpp.
References encodeFieldVmVsrc(), and getDefaultDepCtrEncoding().
getDefaultDepCtrEncoding()
int llvm::AMDGPU::DepCtr::getDefaultDepCtrEncoding (const MCSubtargetInfo & STI)
Definition at line 2050 of file AMDGPUBaseInfo.cpp.
References Default, DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::getDefaultCustomOperandEncoding().
Referenced by encodeFieldHoldCnt(), encodeFieldSaSdst(), encodeFieldVaSdst(), encodeFieldVaSsrc(), encodeFieldVaVcc(), encodeFieldVaVdst(), and encodeFieldVmVsrc().
getVaVdstBitMask()
unsigned llvm::AMDGPU::DepCtr::getVaVdstBitMask ()
Returns
Maximum VaVdst value that can be encoded.
Definition at line 2075 of file AMDGPUBaseInfo.cpp.
Referenced by llvm::AMDGPU::HardwareLimits::HardwareLimits().
getVmVsrcBitMask()
unsigned llvm::AMDGPU::DepCtr::getVmVsrcBitMask ()
Returns
Maximum VmVsrc value that can be encoded.
Definition at line 2077 of file AMDGPUBaseInfo.cpp.
Referenced by llvm::AMDGPU::HardwareLimits::HardwareLimits().
isSymbolicDepCtrEncoding()
bool llvm::AMDGPU::DepCtr::isSymbolicDepCtrEncoding (unsigned Code, bool & HasNonDefaultVal, const MCSubtargetInfo & STI)
Definition at line 2057 of file AMDGPUBaseInfo.cpp.
References DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::isSymbolicCustomOperandEncoding().
Referenced by llvm::AMDGPUInstPrinter::printDepCtr().
Variable Documentation
DEP_CTR_SIZE
const int llvm::AMDGPU::DepCtr::DEP_CTR_SIZE
Initial value:
                   =
static_cast<int>(sizeof(DepCtrInfo) / sizeof(CustomOperandVal))
Definition at line 78 of file AMDGPUAsmUtils.cpp.
Referenced by decodeDepCtr(), encodeDepCtr(), getDefaultDepCtrEncoding(), and isSymbolicDepCtrEncoding().
DepCtrInfo
const CustomOperandVal llvm::AMDGPU::DepCtr::DepCtrInfo
Initial value:
                                  = {
  {{"depctr_hold_cnt"},  1,   1,    7,    1,   isGFX10_BEncoding},
  {{"depctr_sa_sdst"},   1,   1,    0,    1},
  {{"depctr_va_vdst"},  15,  15,   12,    4},
  {{"depctr_va_sdst"},   7,   7,    9,    3},
  {{"depctr_va_ssrc"},   1,   1,    8,    1},
  {{"depctr_va_vcc"},    1,   1,    1,    1},
  {{"depctr_vm_vsrc"},   7,   7,    2,    3},
}
Definition at line 66 of file AMDGPUAsmUtils.cpp.
Referenced by decodeDepCtr(), encodeDepCtr(), getDefaultDepCtrEncoding(), and isSymbolicDepCtrEncoding().