LLVM: llvm::CodeViewYAML Namespace Reference
llvm::CodeViewYAML Namespace Reference
Namespaces
namespace detail
Classes
struct YAMLFrameData
struct YAMLCrossModuleImport
struct SourceLineEntry
struct SourceColumnEntry
struct SourceLineBlock
struct HexFormattedString
struct SourceFileChecksumEntry
struct SourceLineInfo
struct InlineeSite
struct InlineeInfo
struct YAMLDebugSubsection
struct SymbolRecord
struct GlobalHash
struct DebugHSection
struct MemberRecord
struct LeafRecord
Functions
LLVM_ABI Expected< std::vector< std::shared_ptr< codeview::DebugSubsection > > > toCodeViewSubsectionList (BumpPtrAllocator &Allocator, ArrayRef< YAMLDebugSubsection > Subsections, const codeview::StringsAndChecksums &SC)
LLVM_ABI std::vector< YAMLDebugSubsection > fromDebugS (ArrayRef< uint8_t > Data, const codeview::StringsAndChecksumsRef &SC)
LLVM_ABI void initializeStringsAndChecksums (ArrayRef< YAMLDebugSubsection > Sections, codeview::StringsAndChecksums &SC)
DebugHSection fromDebugH (ArrayRef< uint8_t > DebugH)
ArrayRef< uint8_t > toDebugH (const DebugHSection &DebugH, BumpPtrAllocator &Alloc)
LLVM_ABI std::vector< LeafRecord > fromDebugT (ArrayRef< uint8_t > DebugTorP, StringRef SectionName)
LLVM_ABI ArrayRef< uint8_t > toDebugT (ArrayRef< LeafRecord >, BumpPtrAllocator &Alloc, StringRef SectionName)
Function Documentation
fromDebugH()
DebugHSection llvm::CodeViewYAML::fromDebugH (ArrayRef< uint8_t > DebugH)
Definition at line 46 of file CodeViewYAMLTypeHashing.cpp.
References assert(), llvm::BinaryStreamReader::bytesRemaining(), llvm::cantFail(), llvm::CodeViewYAML::DebugHSection::HashAlgorithm, llvm::CodeViewYAML::DebugHSection::Hashes, llvm::little, llvm::CodeViewYAML::DebugHSection::Magic, llvm::BinaryStreamReader::readBytes(), llvm::BinaryStreamReader::readInteger(), llvm::ArrayRef< T >::size(), and llvm::CodeViewYAML::DebugHSection::Version.
fromDebugS()
std::vector< YAMLDebugSubsection > llvm::CodeViewYAML::fromDebugS (ArrayRef< uint8_t > Data, const codeview::StringsAndChecksumsRef & SC)
Definition at line 897 of file CodeViewYAMLDebugSections.cpp.
References assert(), llvm::BinaryStreamReader::bytesRemaining(), llvm::Data, llvm::COFF::DEBUG_SECTION_MAGIC, llvm::CodeViewYAML::YAMLDebugSubsection::fromCodeViewSubection(), llvm::little, llvm::BinaryStreamReader::readArray(), and llvm::BinaryStreamReader::readInteger().
fromDebugT()
std::vector< LeafRecord > llvm::CodeViewYAML::fromDebugT (ArrayRef< uint8_t > DebugTorP, StringRef SectionName)
Definition at line 785 of file CodeViewYAMLTypes.cpp.
References assert(), llvm::BinaryStreamReader::bytesRemaining(), llvm::COFF::DEBUG_SECTION_MAGIC, llvm::CodeViewYAML::LeafRecord::fromCodeViewRecord(), llvm::little, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readInteger(), and T.
initializeStringsAndChecksums()
void llvm::CodeViewYAML::initializeStringsAndChecksums (ArrayRef< YAMLDebugSubsection > Sections, codeview::StringsAndChecksums & SC)
Definition at line 918 of file CodeViewYAMLDebugSections.cpp.
References llvm::codeview::FileChecksums, llvm::codeview::StringsAndChecksums::hasChecksums(), llvm::codeview::StringsAndChecksums::hasStrings(), llvm::codeview::StringsAndChecksums::setChecksums(), llvm::codeview::StringsAndChecksums::setStrings(), and llvm::codeview::StringTable.
Referenced by layoutCOFF().
toCodeViewSubsectionList()
Expected< std::vector< std::shared_ptr< DebugSubsection > > > llvm::CodeViewYAML::toCodeViewSubsectionList (BumpPtrAllocator & Allocator, ArrayRef< YAMLDebugSubsection > Subsections, const codeview::StringsAndChecksums & SC)
Definition at line 743 of file CodeViewYAMLDebugSections.cpp.
References assert(), and llvm::ArrayRef< T >::empty().
Referenced by toDebugS().
toDebugH()
ArrayRef< uint8_t > llvm::CodeViewYAML::toDebugH (const DebugHSection & DebugH, BumpPtrAllocator & Alloc)
Definition at line 65 of file CodeViewYAMLTypeHashing.cpp.
References assert(), llvm::BinaryStreamWriter::bytesRemaining(), llvm::cantFail(), llvm::SmallVectorImpl< T >::clear(), llvm::Data, H, llvm::CodeViewYAML::DebugHSection::HashAlgorithm, llvm::CodeViewYAML::DebugHSection::Hashes, llvm::little, llvm::CodeViewYAML::DebugHSection::Magic, Size, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::CodeViewYAML::DebugHSection::Version, llvm::BinaryStreamWriter::writeFixedString(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by layoutCOFF().
toDebugT()
ArrayRef< uint8_t > llvm::CodeViewYAML::toDebugT (ArrayRef< LeafRecord > Leafs, BumpPtrAllocator & Alloc, StringRef SectionName)
Definition at line 805 of file CodeViewYAMLTypes.cpp.
References assert(), llvm::BinaryStreamWriter::bytesRemaining(), llvm::COFF::DEBUG_SECTION_MAGIC, llvm::little, llvm::codeview::AppendingTypeTableBuilder::records(), Size, T, llvm::BinaryStreamWriter::writeBytes(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by layoutCOFF().