LLVM: llvm::adl_detail Namespace Reference
llvm::adl_detail Namespace Reference
Functions
template<typename RangeT>
constexpr auto begin_impl (RangeT &&range) -> decltype(begin(std::forward< RangeT >(range)))
template<typename RangeT>
constexpr auto end_impl (RangeT &&range) -> decltype(end(std::forward< RangeT >(range)))
template<typename RangeT>
constexpr auto rbegin_impl (RangeT &&range) -> decltype(rbegin(std::forward< RangeT >(range)))
template<typename RangeT>
constexpr auto rend_impl (RangeT &&range) -> decltype(rend(std::forward< RangeT >(range)))
template<typename T>
constexpr void swap_impl (T &&lhs, T &&rhs) noexcept(noexcept(swap(std::declval< T >(), std::declval< T >())))
template<typename RangeT>
constexpr auto size_impl (RangeT &&range) -> decltype(size(std::forward< RangeT >(range)))
void swap (llvm::BitVector &LHS, llvm::BitVector &RHS)
Implement std::swap in terms of BitVector swap.
Function Documentation
begin_impl()
template<typename RangeT> auto llvm::adl_detail::begin_impl (RangeT && range) -> decltype(begin(std::forward< RangeT >(range))) constexpr
Definition at line 27 of file ADL.h.
References llvm::begin().
Referenced by llvm::adl_begin().
end_impl()
template<typename RangeT> auto llvm::adl_detail::end_impl (RangeT && range) -> decltype(end(std::forward< RangeT >(range))) constexpr
Definition at line 35 of file ADL.h.
References llvm::end().
Referenced by llvm::adl_end().
rbegin_impl()
template<typename RangeT> auto llvm::adl_detail::rbegin_impl (RangeT && range) -> decltype(rbegin(std::forward< RangeT >(range))) constexpr
Definition at line 43 of file ADL.h.
Referenced by llvm::adl_rbegin().
rend_impl()
template<typename RangeT> auto llvm::adl_detail::rend_impl (RangeT && range) -> decltype(rend(std::forward< RangeT >(range))) constexpr
Definition at line 51 of file ADL.h.
Referenced by llvm::adl_rend().
size_impl()
template<typename RangeT> auto llvm::adl_detail::size_impl (RangeT && range) -> decltype(size(std::forward< RangeT >(range))) constexpr
Definition at line 68 of file ADL.h.
References llvm::size().
Referenced by llvm::adl_size().
swap()
void std::swap (llvm::BitVector & LHS, llvm::BitVector & RHS) inline
Implement std::swap in terms of BitVector swap.
Definition at line 872 of file BitVector.h.
Referenced by swap_impl().
swap_impl()
template<typename T> void llvm::adl_detail::swap_impl (T && lhs, T && rhs) constexpr noexcept
Definition at line 59 of file ADL.h.
References swap(), and T.
Referenced by llvm::adl_swap().