LLVM: std Namespace Reference
std Namespace Reference
Implement std::hash so that hash_code can be used in STL containers.
Classes
struct hash< llvm::hash_code >
struct tuple_size< llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > >
struct tuple_element< I, llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info > >
struct tuple_size< llvm::detail::enumerator_result< Refs... > >
struct tuple_element< I, llvm::detail::enumerator_result< Refs... > >
struct tuple_element< I, const llvm::detail::enumerator_result< Refs... > >
struct tuple_size< llvm::StringMapEntry< ValueTy > >
struct tuple_element< Index, llvm::StringMapEntry< ValueTy > >
struct is_error_code_enum< llvm::BitcodeError >
struct hash< llvm::rdf::detail::NodeRef >
struct hash< llvm::rdf::RegisterRef >
struct hash< llvm::rdf::RegisterAggr >
struct is_error_code_enum< llvm::codeview::cv_error_code >
class reverse_iterator< llvm::DWARFDie::iterator >
struct is_error_code_enum< llvm::msf::msf_error_code >
struct is_error_code_enum< llvm::pdb::dia_error_code >
struct is_error_code_enum< llvm::pdb::pdb_error_code >
struct is_error_code_enum< llvm::pdb::raw_error_code >
struct hash< llvm::pdb::PDB_SymType >
struct is_error_code_enum< llvm::object::object_error >
struct hash< llvm::sampleprof::FunctionId >
Template specialization for FunctionId so that it can be used in STL containers.
struct is_error_code_enum< llvm::sampleprof_error >
struct is_error_code_enum< llvm::errc >
struct hash< VarLocInsertPt >
struct hash< SDValue >
Functions
void swap (llvm::BitVector &LHS, llvm::BitVector &RHS)
Implement std::swap in terms of BitVector swap.
template<class Ty>
void swap (llvm::iplist< Ty > &Left, llvm::iplist< Ty > &Right)
template<typename T, typename V, typename S, unsigned N>
void swap (llvm::SetVector< T, V, S, N > &LHS, llvm::SetVector< T, V, S, N > &RHS)
Implement std::swap in terms of SetVector swap.
template<typename T, unsigned N>
void swap (llvm::SmallSetVector< T, N > &LHS, llvm::SmallSetVector< T, N > &RHS)
Implement std::swap in terms of SmallSetVector swap.
void swap (llvm::SmallBitVector &LHS, llvm::SmallBitVector &RHS)
Implement std::swap in terms of BitVector swap.
template<class T, unsigned N>
void swap (llvm::SmallPtrSet< T, N > &LHS, llvm::SmallPtrSet< T, N > &RHS)
Implement std::swap in terms of SmallPtrSet swap.
template<typename T>
void swap (llvm::SmallVectorImpl< T > &LHS, llvm::SmallVectorImpl< T > &RHS)
Implement std::swap in terms of SmallVector swap.
template<typename T, unsigned N>
void swap (llvm::SmallVector< T, N > &LHS, llvm::SmallVector< T, N > &RHS)
Implement std::swap in terms of SmallVector swap.
Detailed Description
Implement std::hash so that hash_code can be used in STL containers.
Function Documentation
swap() [1/8]
void std::swap (llvm::BitVector & LHS, llvm::BitVector & RHS) inline
Implement std::swap in terms of BitVector swap.
Definition at line 872 of file BitVector.h.
References LHS, and RHS.
Referenced by addAttributeImpl(), llvm::logicalview::LVRange::addEntry(), llvm::PressureDiff::addPressureChange(), adjustICmp128(), llvm::AMDGPUAAResult::alias(), llvm::coro::Shape::analyze(), analyzeICmp(), llvm::CombinerHelper::applyCombineAddP2IToPtrAdd(), llvm::SPIRVCombinerHelper::applySPIRVFaceForward(), llvm::MemoryDepChecker::areDepsSafe(), attemptToFoldSymbolOffsetDifference(), llvm::SUnit::biasCriticalPath(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), llvm::memprof::CallStackRadixTreeBuilder< FrameIdTy >::build(), llvm::TargetLowering::buildLegalVectorShuffle(), canonicalHeaderAndLatch(), canonicalizeAbs(), llvm::SelectionDAG::canonicalizeCommutativeBinop(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeForInvariantConditionInjection(), canonicalizeICmpBool(), canonicalizeSaturatedAddSigned(), canonicalizeSaturatedAddUnsigned(), canonicalizeSaturatedSubtract(), canonicalizeShuffleMaskWithHorizOp(), checkBiasedBranch(), checkForNegativeOperand(), llvm::MachineBasicBlock::clearLiveIns(), combineADDToADDZE(), combineADDToMAT_PCREL_ADDR(), combineANDOfSETCCToCZERO(), combineAndOrForCcmpCtest(), combineBinOpOfExtractToReduceTree(), combineCarryDiamond(), combineCMov(), combineFMulcFCMulc(), combineFunnelShift(), combineHorizOpWithShuffle(), combineLogicBlendIntoConditionalNegate(), combineMul(), combineOp_VLToVWOp_VL(), combineOrCmpEqZeroToCtlzSrl(), combinePExtTruncate(), combineSelect(), llvm::VETargetLowering::combineSelect(), combineSelectAndUse(), combineSelectAndUse(), combineSelectAndUse(), llvm::VETargetLowering::combineSelectCC(), combineSelectOfTwoConstants(), combineSetCC(), combineShuffleToFMAddSub(), combineSVEPrefetchVecBaseImmOff(), combineTargetShuffle(), combineToVWMACC(), combineVqdotAccum(), combineVSelectWithAllOnesOrZeros(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::SIInstrInfo::commuteInstructionImpl(), commuteShuffle(), llvm::KnownBits::computeForAddSub(), llvm::KnownBits::computeForSubBorrow(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), computeMergedBranchWeights(), llvm::SelectionDAG::ComputeNumSignBits(), constantFoldBinOpWithSplat(), llvm::ConstantFoldTerminator(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), llvm::SelectionDAG::copyExtraInfo(), countToEliminateCompares(), createGPRPairNode(), createGPRPairNodei64(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::DomTreeBuilder::DeleteEdge(), detectExtMul(), detectPMADDUBSW(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::orc::detail::WaitingOnGraph< JITDylib *, NonOwningSymbolStringPtr >::emit(), emitBuildPairF64Pseudo(), EmitCMP(), emitConjunctionRec(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::MipsSEFrameLowering::emitPrologue(), emitSplitF64Pseudo(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::DominatorTreeBase< BlockT, false >::eraseNode(), estimateLoopTripCount(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::TargetLowering::expandCMP(), expandSGPRCopy(), llvm::gsym::GsymCreator::finalize(), llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::finalize(), llvm::orc::MapperJITLinkMemoryManager::InFlightAlloc::finalize(), llvm::orc::EPCGenericRTDyldMemoryManager::finalizeMemory(), llvm::TargetRegisterInfo::findCommonRegClass(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), llvm::CoalescerPair::flip(), foldAbsDiff(), foldAddSubSelect(), foldAndOrOfICmpsWithPow2AndWithZero(), foldBinOpIntoSelectIfProfitable(), foldBinOpIntoSelectIfProfitable(), foldBitCeil(), foldCSELOfCSEL(), foldFCmpFNegCommonOp(), foldFCmpWithFloorAndCeil(), llvm::AMDGPUTargetLowering::foldFreeOpFromSelect(), foldGuardedFunnelShift(), foldICmpAndXX(), foldICmpOrXX(), llvm::InstCombinerImpl::foldICmpTruncWithTruncOrExt(), foldICmpWithLowBitMaskedVal(), llvm::InstCombinerImpl::foldICmpWithMinMax(), foldICmpXorXX(), foldIntrinsicUsingDistributiveLaws(), foldIsPowerOf2(), foldLoadsRecursive(), foldMulHigh(), foldMulShl1(), foldNestedSelects(), foldOrCommuteConstant(), foldReduceOperandViaVQDOT(), foldRoundUpIntegerWithPow2Alignment(), foldSelectBitTest(), llvm::InstCombinerImpl::foldSelectExtConst(), foldSelectFunnelShift(), foldSelectICmpAndZeroShl(), foldSelectICmpEq(), foldSelectICmpLshrAshr(), foldSelectICmpMinMax(), llvm::InstCombinerImpl::foldSelectOfBools(), foldSelectShuffleOfSelectShuffle(), llvm::InstCombinerImpl::foldSelectToCmp(), llvm::InstCombinerImpl::foldSelectValueEquivalence(), llvm::InstCombinerImpl::foldSelectWithConstOpToBinOp(), foldSelectWithFCmpToFabs(), foldSelectWithIdentityConstant(), foldSelectWithSRem(), foldSelectZeroOrFixedOp(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShuffleWithInsert(), foldTwoEntryPHINode(), foldUnsignedUnderflowCheck(), llvm::InstCombinerImpl::foldVectorBinop(), foldVSelectToSignBitSplatMask(), generateEquivalentSub(), GenerateTBL(), getAArch64Cmp(), getBranchHint(), llvm::getBranchProbability(), getBranchWeights(), getBuildVectorSplat(), getCmp(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), getCopyFromParts(), llvm::PPCMCCodeEmitter::getDispRI34PCRelEncoding(), getDivRemArgList(), getHashValueImpl(), getI128Select(), llvm::GetIfCondition(), llvm::Loop::getIncomingAndBackEdge(), llvm::getLoopEstimatedTripCount(), llvm::ScalarEvolution::getLoopInvariantExitCondDuringFirstIterationsImpl(), llvm::ScalarEvolution::getLoopInvariantPredicate(), llvm::getMetadataToPropagate(), llvm::SelectionDAG::getNode(), llvm::AMDGPUSubtarget::getOccupancyWithWorkGroupSizes(), getOperandsForBranch(), llvm::PeelingModuloScheduleExpander::getPhiCanonicalReg(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::PPCTargetLowering::getPreIndexedAddressParts(), llvm::TargetInstrInfo::getReassociationOpcodes(), llvm::RegBankSelect::getRepairCost(), getShuffleHalfVectors(), llvm::getShuffleMaskWithWidestElts(), llvm::getStartAndEndForAccess(), getTestBitReg(), getThreeSrcCommuteCase(), getZeroPaddedAdd(), GroupByComplexity(), llvm::orc::SimpleRemoteEPC::handleDisconnect(), llvm::orc::SimpleRemoteEPCServer::handleDisconnect(), llvm::VPlanTransforms::handleMultiUseReductions(), handlePhiDef(), llvm::TargetInstrInfo::hasReassociableSibling(), hoistAdd(), hoistAddSub(), hoistBOAssociation(), hoistMinMax(), hoistMulAddAssociation(), hoistSub(), llvm::GCNRegPressure::inc(), llvm::orc::SimpleRemoteMemoryMapper::initialize(), llvm::InlineFunctionImpl(), llvm::DomTreeBuilder::InsertEdge(), insertFoldCacheEntry(), insertNoDuplicates(), llvm::SIInstrInfo::insertSelect(), llvm::GCNTTIImpl::instCombineIntrinsic(), interChangeDependencies(), isAddSubOrSubAdd(), llvm::CoalescerPair::isCoalescable(), isFNEG(), isHorizontalBinOp(), isI128MovedFromParts(), isImpliedCondFCmps(), isImpliedCondICmps(), isKnownPredicateExtendIdiom(), IsKnownPredicateViaMinOrMax(), isLegalToInterChangeLoops(), isLoopNeverExecuted(), isMaskedSlidePair(), isSetCC(), isSignedMinMaxClamp(), isSignedMinMaxIntrinsicClamp(), legalizeFCmpPredicate(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), llvm::TargetLowering::LegalizeSetCCCondCode(), llvm::cfg::LegalizeUpdates(), LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks(), lowerAddSubToHorizontalOp(), LowerAndToBT(), LowerAndToBTST(), llvm::RISCVTargetLowering::LowerCall(), LowerFMINIMUM_FMAXIMUM(), llvm::SparcTargetLowering::LowerFormalArguments_32(), LowerIntVSETCC_AVX512(), lowerMSABinaryBitImmIntr(), lowerMSASplatZExt(), LowerMUL(), llvm::RISCVTargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerReturn(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleWithPERMV(), lowerShuffleWithSHUFPS(), llvm::LegalizerHelper::lowerThreewayCompare(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLEAsVSlide1(), LowerVSETCC(), LowerVSETCC(), LowerVSETCCWithSUBUS(), matchBinaryShuffle(), matchBitmaskMul(), llvm::CombinerHelper::matchCanonicalizeFCmp(), llvm::CombinerHelper::matchCanonicalizeICmp(), matchClamp(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), matchCondition(), matchFastFloatClamp(), matchMinMaxOfMinMax(), matchOrConcat(), matchPMADDWD(), matchPMADDWD_2(), llvm::CombinerHelper::matchRepeatedFPDivisor(), matchSelectAddSub(), llvm::CombinerHelper::matchSelectIMinMax(), matchSelectPattern(), llvm::SPIRVCombinerHelper::matchSelectToFaceForward(), matchSelectWithOptionalNotCond(), matchShuffleWithSHUFPD(), matchShuffleWithUNPCK(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), mayUseP9Setb(), mergeConditionalStores(), mergeConditionalStoreToAddress(), MergeSeqs(), llvm::AliasSet::mergeSetIn(), llvm::LiveRange::MergeValueNumberInto(), llvm::hashing::detail::hash_state::mix(), llvm::LoopCarriedEdges::modifySUnits(), llvm::orc::SymbolStringPoolEntryUnsafe::moveToSymbolStringPtr(), multikeySort(), needsLFTR(), NegateCC(), llvm::FullDependence::normalize(), llvm::Triple::normalize(), llvm::AA::PointerInfo::State::operator=(), llvm::ItaniumPartialDemangler::operator=(), llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::operator=(), llvm::MustBeExecutedIterator::operator=(), llvm::orc::shared::WrapperFunctionBuffer::operator=(), llvm::orc::SymbolStringPtr::operator=(), llvm::Regex::operator=(), llvm::StringMap< EmptyStringSetTag, AllocatorTy >::operator=(), PODSmallVector< Node *, 8 >::operator=(), llvm::X86::optimizeInstFromVEX3ToVEX2(), llvm::LiveRange::overlaps(), llvm::LiveRange::overlapsFrom(), parseBraceExpansions(), AbstractManglingParser< Derived, Alloc >::parseFoldExpr(), llvm::LoopStructure::parseLoopStructure(), llvm::peelLoop(), llvm::PeelSingleBlockLoop(), performADDCombine(), performAddCSelIntoCSinc(), performAddDotCombine(), performAddTruncShiftCombine(), performANDORCSELCombine(), performBRCONDCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtBinopLoadFold(), PerformFAddVSelectCombine(), performGatherLoadCombine(), PerformMinMaxCombine(), PerformMinMaxToSatCombine(), performMULCombine(), performMulCombine(), performORCombine(), performScatterStoreCombine(), performSELECT_CCCombine(), PerformSELECTCombine(), performSetccAddFolding(), performVecReduceAddCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), performVP_TRUNCATECombine(), PerformVSetCCToVCTPCombine(), llvm::LatencyPriorityQueue::pop(), llvm::ResourcePriorityQueue::pop(), llvm::gsym::GsymCreator::prepareMergedFunctions(), PrintResults(), slpvectorizer::BoUpSLP::processBuildVector(), pushAddIntoCmovOfConsts(), reassociateCSELOperandsForCSE(), reassociateFCmps(), llvm::TargetInstrInfo::reassociateOps(), reconnectChildLoops(), llvm::orc::shared::WrapperFunctionBuffer::release(), llvm::LatencyPriorityQueue::remove(), llvm::orc::SymbolLookupSet::remove(), llvm::ResourcePriorityQueue::remove(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), ReorganizeVector(), llvm::RegBankSelect::repairReg(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::SIRegisterInfo::resolveFrameIndex(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::ScalarEvolution::LoopGuards::rewrite(), runImpl(), llvm::mca::Scheduler::select(), selectUmullSmull(), llvm::setBranchProbability(), setLimitsForBinOp(), llvm::setLoopEstimatedTripCount(), llvm::CoalescerPair::setRegisters(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::shutdown(), llvm::InstCombinerImpl::SimplifyAddWithRemainder(), llvm::simplifyBinaryIntrinsic(), simplifyCmpSelOfMaxMin(), simplifyFCmpInst(), simplifyFMAFMul(), simplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), simplifyIntrinsic(), simplifyLoopInst(), simplifySelectWithFCmp(), simplifySelectWithICmpCond(), simplifyShuffleVectorInst(), simplifySuspendPoints(), simplifySwitchOfCmpIntrinsic(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::CallGraphNode::stealCalledFunctionsFrom(), llvm::AllocatorList< T, BumpPtrAllocator >< Addend >::swap(), llvm::Any::swap(), llvm::BitVector::swap(), llvm::CachedHashString::swap, llvm::CGSCCToFunctionPassAdaptor::swap, llvm::detail::AnalysisPassModel< IRUnitT, PassT, InvalidatorT, ExtraArgTs >::swap, llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, false >::swap, llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::swap, llvm::detail::PassModel< IRUnitT, PassT, AnalysisManagerT, ExtraArgTs >::swap, llvm::MapVector< StringRef, HashData >::swap(), llvm::ModuleToPostOrderCGSCCPassAdaptor::swap, llvm::simple_ilist< Node >::swap(), llvm::SmallBitVector::swap(), llvm::SmallPtrSetImplBase::swap(), llvm::SmallVectorImpl< T >::swap(), llvm::StringMapImpl::swap(), llvm::xray::Profile::swap, swap(), swap(), llvm::GVNExpression::BasicExpression::swapOperands(), llvm::VPUser::swapOperands(), llvm::VPBlockBase::swapPredecessors(), llvm::BranchProbabilityInfo::swapSuccEdgesProbabilities(), llvm::VPBlockBase::swapSuccessors(), llvm::SwingSchedulerDDGEdge::SwingSchedulerDDGEdge(), Swizzle(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), llvm::orc::SymbolStringPoolEntryUnsafe::take(), llvm::AddrLabelMap::takeDeletedSymbolsForFunction(), threadCmpOverPHI(), threadCmpOverSelect(), TranslateM68kCC(), translateSetCCForBranch(), translateSetCCForBranch(), TranslateX86CC(), translateX86FSETCC(), tryBitfieldInsertOpFromOr(), tryDemorganOfBooleanCondition(), tryFactorization(), tryFoldMADwithSRL(), tryFoldSelectIntoOp(), TryMULWIDECombine(), llvm::tryPressure(), trySequenceOfOnes(), trySimplifyICmpWithAdds(), llvm::VPRecipeBuilder::tryToCreatePartialReduction(), unpackF64OnRV32DSoftABI(), llvm::MCJIT::UnregisterJITEventListener(), updateBranchWeights(), upgradeX86ConcatShift(), upgradeX86IntrinsicCall(), upgradeX86VPERMT2Intrinsics(), valuesOverlap(), shuffles::vdealvdd(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSelectInst(), llvm::InstCombinerImpl::visitShl(), llvm::SelectionDAGBuilder::visitSwitchCase(), llvm::InstCombinerImpl::visitXor(), shuffles::vshuffvdd(), llvm::orc::shared::WrapperFunctionBuffer::WrapperFunctionBuffer(), llvm::reassociate::XorOpnd::XorOpnd(), and llvm::orc::DefinitionGenerator::~DefinitionGenerator().
swap() [2/8]
template<class Ty> void std::swap (llvm::iplist< Ty > & Left, llvm::iplist< Ty > & Right)
Definition at line 352 of file ilist.h.
swap() [3/8]
template<typename T, typename V, typename S, unsigned N> void std::swap (llvm::SetVector< T, V, S, N > & LHS, llvm::SetVector< T, V, S, N > & RHS) inline
Implement std::swap in terms of SetVector swap.
Definition at line 350 of file SetVector.h.
References LHS, and RHS.
swap() [4/8]
void std::swap (llvm::SmallBitVector & LHS, llvm::SmallBitVector & RHS) inline
Implement std::swap in terms of BitVector swap.
Definition at line 761 of file SmallBitVector.h.
References LHS, and RHS.
swap() [5/8]
template<class T, unsigned N> void std::swap (llvm::SmallPtrSet< T, N > & LHS, llvm::SmallPtrSet< T, N > & RHS) inline
Implement std::swap in terms of SmallPtrSet swap.
Definition at line 595 of file SmallPtrSet.h.
References LHS, and RHS.
swap() [6/8]
template<typename T, unsigned N> void std::swap (llvm::SmallSetVector< T, N > & LHS, llvm::SmallSetVector< T, N > & RHS) inline
Implement std::swap in terms of SmallSetVector swap.
Definition at line 358 of file SetVector.h.
References LHS, and RHS.
swap() [7/8]
template<typename T, unsigned N> void std::swap (llvm::SmallVector< T, N > & LHS, llvm::SmallVector< T, N > & RHS) inline
Implement std::swap in terms of SmallVector swap.
Definition at line 1364 of file SmallVector.h.
References LHS, RHS, and swap().
swap() [8/8]
template<typename T> void std::swap (llvm::SmallVectorImpl< T > & LHS, llvm::SmallVectorImpl< T > & RHS) inline
Implement std::swap in terms of SmallVector swap.
Definition at line 1357 of file SmallVector.h.
References LHS, RHS, and swap().