LLVM: llvm::SPIRV Namespace Reference
llvm::SPIRV Namespace Reference
Namespaces
namespace OperandCategory
namespace Extension
namespace Capability
namespace Environment
namespace SourceLanguage
namespace AddressingModel
namespace ExecutionModel
namespace MemoryModel
namespace MatrixMultiplyAccumulateOperands
namespace ExecutionMode
namespace StorageClass
namespace Dim
namespace SamplerAddressingMode
namespace SamplerFilterMode
namespace ImageFormat
namespace ImageChannelOrder
namespace ImageChannelDataType
namespace ImageOperand
namespace FPFastMathMode
namespace FPRoundingMode
namespace LinkageType
namespace AccessQualifier
namespace FunctionParameterAttribute
namespace Decoration
namespace BuiltIn
namespace SelectionControl
namespace LoopControl
namespace FunctionControl
namespace MemorySemantics
namespace MemoryOperand
namespace Scope
namespace GroupOperation
namespace KernelEnqueueFlags
namespace KernelProfilingInfo
namespace InstructionSet
namespace OpenCLExtInst
namespace GLSLExtInst
namespace NonSemanticExtInst
namespace Opcode
namespace CooperativeMatrixLayout
namespace CooperativeMatrixOperands
namespace SpecConstantOpOperands
namespace FPEncoding
Classes
class ConvergenceRegion
class ConvergenceRegionInfo
struct SymbolicOperand
struct ExtensionEntry
struct CapabilityEntry
struct EnvironmentEntry
struct ExtendedBuiltin
struct DemangledBuiltin
struct IncomingCall
struct NativeBuiltin
struct GroupBuiltin
struct IntelSubgroupsBuiltin
struct AtomicFloatingBuiltin
struct GroupUniformBuiltin
struct GetBuiltin
struct ImageQueryBuiltin
struct IntegerDotProductBuiltin
struct ConvertBuiltin
struct VectorLoadStoreBuiltin
struct BuiltinType
struct OpenCLType
union ImageAttrs
struct Requirements
struct RequirementHandler
struct ModuleAnalysisInfo
struct FPFastMathDefaultInfo
struct FPFastMathDefaultInfoVector
Typedefs
using MIHandle = std::tuple<const MachineInstr *, Register, size_t>
using IRHandle = std::tuple<const void *, unsigned, unsigned>
using IRHandleMF = std::pair<IRHandle, const MachineFunction *>
using InstrList = SmallVector<const MachineInstr *>
using LocalToGlobalRegTable = std::map<Register, MCRegister>
using RegisterAliasMapTy
Enumerations
enum InstFlags { INST_PRINTER_WIDTH16 = 1 , INST_PRINTER_WIDTH64 = INST_PRINTER_WIDTH16 << 1 }
enum AsmComments { ASM_PRINTER_WIDTH16 = MachineInstr::TAsmComments , ASM_PRINTER_WIDTH64 = ASM_PRINTER_WIDTH16 << 1 }
enum SpecialTypeKind {
STK_Empty = 0 , STK_Image , STK_SampledImage , STK_Sampler ,
STK_Pipe , STK_DeviceEvent , STK_ElementPointer , STK_Type ,
STK_Value , STK_MachineInstr , STK_VkBuffer , STK_Padding ,
STK_ExplictLayoutType , STK_Last = -1
}
enum ModuleSectionType {
MB_EntryPoints , MB_DebugNames , MB_DebugStrings , MB_DebugModuleProcessed ,
MB_AliasingInsts , MB_Annotations , MB_TypeConstVars , MB_NonSemanticGlobalDI ,
MB_ExtFuncDecls , NUM_MODULE_SECTIONS
}
Functions
std::optional< IntrinsicInst * > getConvergenceToken (BasicBlock *BB)
std::optional< const IntrinsicInst * > getConvergenceToken (const BasicBlock *BB)
ConvergenceRegionInfo getConvergenceRegions (Function &F, DominatorTree &DT, LoopInfo &LI)
unsigned getIDFromRegister (unsigned Reg)
std::string lookupBuiltinNameHelper (StringRef DemangledCall, FPDecorationId *DecorationId)
Parses the name part of the demangled builtin call.
std::tuple< int, unsigned, unsigned > mapBuiltinToOpcode (const StringRef DemangledCall, SPIRV::InstructionSet::InstructionSet Set)
Helper function for finding a builtin function attributes by a demangled function name.
std::optional< bool > lowerBuiltin (const StringRef DemangledCall, SPIRV::InstructionSet::InstructionSet Set, MachineIRBuilder &MIRBuilder, const Register OrigRet, const Type *OrigRetTy, const SmallVectorImpl< Register > &Args, SPIRVGlobalRegistry *GR, const CallBase &CB)
Type * parseBuiltinCallArgumentType (StringRef TypeStr, LLVMContext &Ctx)
bool parseBuiltinTypeStr (SmallVector< StringRef, 10 > &BuiltinArgsTypeStrs, const StringRef DemangledCall, LLVMContext &Ctx)
Type * parseBuiltinCallArgumentBaseType (const StringRef DemangledCall, unsigned ArgIdx, LLVMContext &Ctx)
Parses the provided ArgIdx argument base type in the DemangledCall skeleton.
TargetExtType * parseBuiltinTypeNameToTargetExtType (std::string TypeName, LLVMContext &Context)
Translates a string representing a SPIR-V or OpenCL builtin type to a TargetExtType that can be further lowered with lowerBuiltinType().
SPIRVType * lowerBuiltinType (const Type *OpaqueType, SPIRV::AccessQualifier::AccessQualifier AccessQual, MachineIRBuilder &MIRBuilder, SPIRVGlobalRegistry *GR)
std::optional< bool > lowerBuiltin (const StringRef DemangledCall, InstructionSet::InstructionSet Set, MachineIRBuilder &MIRBuilder, const Register OrigRet, const Type *OrigRetTy, const SmallVectorImpl< Register > &Args, SPIRVGlobalRegistry *GR, const CallBase &CB)
Lowers a builtin function call using the provided DemangledCall skeleton and external instruction Set.
SPIRVType * lowerBuiltinType (const Type *Type, AccessQualifier::AccessQualifier AccessQual, MachineIRBuilder &MIRBuilder, SPIRVGlobalRegistry *GR)
Handles the translation of the provided special opaque/builtin type Type to SPIR-V type.
size_t to_hash (const MachineInstr *MI)
MIHandle getMIKey (const MachineInstr *MI)
IRHandleMF getIRHandleMF (IRHandle Handle, const MachineFunction *MF)
IRHandle irhandle_image (const Type *SampledTy, unsigned Dim, unsigned Depth, unsigned Arrayed, unsigned MS, unsigned Sampled, unsigned ImageFormat, unsigned AQ=0)
IRHandle irhandle_sampled_image (const Type *SampledTy, const MachineInstr *ImageTy)
IRHandle irhandle_sampler ()
IRHandle irhandle_pipe (uint8_t AQ)
IRHandle irhandle_event ()
IRHandle irhandle_pointee (const Type *ElementType, unsigned AddressSpace)
IRHandle irhandle_ptr (const void *Ptr, unsigned Arg, enum SpecialTypeKind STK)
IRHandle irhandle_vkbuffer (const Type *ElementType, StorageClass::StorageClass SC, bool IsWriteable)
IRHandle irhandle_padding ()
IRHandle irhandle_explict_layout_type (const Type *Ty)
IRHandle handle (const Type *Ty)
IRHandle handle (const Value *V)
IRHandle handle (const MachineInstr *KeyMI)
bool type_has_layout_decoration (const Type *T)
static FunctionType * extractFunctionTypeFromMetadata (NamedMDNode *NMD, FunctionType *FTy, StringRef Name)
FunctionType * getOriginalFunctionType (const Function &F)
FunctionType * getOriginalFunctionType (const CallBase &CB)
Typedef Documentation
InstrList
using llvm::SPIRV::InstrList = SmallVector<const MachineInstr *>
Definition at line 128 of file SPIRVModuleAnalysis.h.
IRHandle
using llvm::SPIRV::IRHandle = std::tuple<const void *, unsigned, unsigned>
Definition at line 48 of file SPIRVIRMapping.h.
IRHandleMF
using llvm::SPIRV::IRHandleMF = std::pair<IRHandle, const MachineFunction *>
Definition at line 49 of file SPIRVIRMapping.h.
LocalToGlobalRegTable
using llvm::SPIRV::LocalToGlobalRegTable = std::map<Register, MCRegister>
Definition at line 130 of file SPIRVModuleAnalysis.h.
MIHandle
using llvm::SPIRV::MIHandle = std::tuple<const MachineInstr *, Register, size_t>
Definition at line 42 of file SPIRVIRMapping.h.
RegisterAliasMapTy
using llvm::SPIRV::RegisterAliasMapTy
Initial value:
std::map<const MachineFunction *, LocalToGlobalRegTable>
Definition at line 131 of file SPIRVModuleAnalysis.h.
Enumeration Type Documentation
AsmComments
enum llvm::SPIRV::AsmComments
Enumerator
ASM_PRINTER_WIDTH16
ASM_PRINTER_WIDTH64
Definition at line 63 of file SPIRVInstrInfo.h.
InstFlags
enum llvm::SPIRV::InstFlags
Enumerator
INST_PRINTER_WIDTH16
INST_PRINTER_WIDTH64
Definition at line 246 of file SPIRVBaseInfo.h.
ModuleSectionType
enum llvm::SPIRV::ModuleSectionType
Enumerator
MB_EntryPoints
MB_DebugNames
MB_DebugStrings
MB_DebugModuleProcessed
MB_AliasingInsts
MB_Annotations
MB_TypeConstVars
MB_NonSemanticGlobalDI
MB_ExtFuncDecls
NUM_MODULE_SECTIONS
Definition at line 31 of file SPIRVModuleAnalysis.h.
SpecialTypeKind
enum llvm::SPIRV::SpecialTypeKind
Enumerator
STK_Empty
STK_Image
STK_SampledImage
STK_Sampler
STK_Pipe
STK_DeviceEvent
STK_ElementPointer
STK_Type
STK_Value
STK_MachineInstr
STK_VkBuffer
STK_Padding
STK_ExplictLayoutType
STK_Last
Definition at line 55 of file SPIRVIRMapping.h.
Function Documentation
extractFunctionTypeFromMetadata()
FunctionType * llvm::SPIRV::extractFunctionTypeFromMetadata (NamedMDNode * NMD, FunctionType * FTy, StringRef Name) static
Definition at line 36 of file SPIRVUtils.cpp.
References assert(), llvm::dyn_cast(), llvm::find_if(), llvm::FunctionType::get(), getConstInt(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::FunctionType::getReturnType(), I, llvm::FunctionType::isVarArg(), N, llvm::NamedMDNode::op_end(), llvm::NamedMDNode::operands(), and llvm::FunctionType::params().
Referenced by getOriginalFunctionType(), and getOriginalFunctionType().
getConvergenceRegions()
ConvergenceRegionInfo llvm::SPIRV::getConvergenceRegions (Function & F, DominatorTree & DT, LoopInfo & LI)
Definition at line 307 of file SPIRVConvergenceRegionAnalysis.cpp.
References F.
Referenced by llvm::SPIRVConvergenceRegionAnalysis::run(), and llvm::SPIRVConvergenceRegionAnalysisWrapperPass::runOnFunction().
getConvergenceToken() [1/2]
std::optional< IntrinsicInst * > llvm::SPIRV::getConvergenceToken (BasicBlock * BB)
Definition at line 104 of file SPIRVConvergenceRegionAnalysis.cpp.
Referenced by llvm::SPIRV::ConvergenceRegion::ConvergenceRegion().
getConvergenceToken() [2/2]
std::optional< const IntrinsicInst * > llvm::SPIRV::getConvergenceToken (const BasicBlock * BB)
Definition at line 109 of file SPIRVConvergenceRegionAnalysis.cpp.
getIDFromRegister()
unsigned llvm::SPIRV::getIDFromRegister (unsigned Reg) inline
Definition at line 52 of file SPIRVMCTargetDesc.h.
References assert(), and Reg.
Referenced by emitOperand(), and llvm::SPIRVInstPrinter::printOperand().
getIRHandleMF()
IRHandleMF llvm::SPIRV::getIRHandleMF (IRHandle Handle, const MachineFunction * MF) inline
Definition at line 51 of file SPIRVIRMapping.h.
Referenced by llvm::SPIRVIRMapping::add(), and llvm::SPIRVIRMapping::findMI().
getMIKey()
MIHandle llvm::SPIRV::getMIKey (const MachineInstr * MI) inline
Definition at line 44 of file SPIRVIRMapping.h.
References MI, and to_hash().
Referenced by llvm::SPIRVIRMapping::add().
getOriginalFunctionType() [1/2]
FunctionType * llvm::SPIRV::getOriginalFunctionType (const CallBase & CB)
Definition at line 88 of file SPIRVUtils.cpp.
References extractFunctionTypeFromMetadata(), llvm::CallBase::getFunctionType(), llvm::Instruction::getModule(), llvm::Value::getName(), and llvm::Module::getNamedMetadata().
getOriginalFunctionType() [2/2]
FunctionType * llvm::SPIRV::getOriginalFunctionType (const Function & F)
Definition at line 82 of file SPIRVUtils.cpp.
References extractFunctionTypeFromMetadata(), and F.
Referenced by getArgSPIRVType(), llvm::SPIRVGlobalRegistry::getDeducedGlobalValueType(), llvm::SPIRVCallLowering::lowerCall(), and llvm::SPIRVCallLowering::lowerFormalArguments().
handle() [1/3]
IRHandle llvm::SPIRV::handle (const MachineInstr * KeyMI) inline
Definition at line 171 of file SPIRVIRMapping.h.
References irhandle_ptr(), STK_MachineInstr, and to_hash().
handle() [2/3]
IRHandle llvm::SPIRV::handle (const Type * Ty) inline
Definition at line 162 of file SPIRVIRMapping.h.
References llvm::Type::getTypeID(), irhandle_ptr(), STK_Type, and llvm::unifyPtrType().
Referenced by llvm::SPIRVIRMapping::add(), llvm::SPIRVIRMapping::add(), llvm::SPIRVIRMapping::add(), llvm::SPIRVIRMapping::find(), llvm::SPIRVIRMapping::find(), llvm::SPIRVIRMapping::find(), llvm::SPIRVIRMapping::findMI(), llvm::SPIRVIRMapping::findMI(), llvm::SPIRVIRMapping::findMI(), and llvm::SPIRVGlobalRegistry::getOrCreateLayoutType().
handle() [3/3]
IRHandle llvm::SPIRV::handle (const Value * V) inline
Definition at line 167 of file SPIRVIRMapping.h.
References irhandle_ptr(), and STK_Value.
irhandle_event()
IRHandle llvm::SPIRV::irhandle_event () inline
Definition at line 131 of file SPIRVIRMapping.h.
References STK_DeviceEvent.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent().
irhandle_explict_layout_type()
IRHandle llvm::SPIRV::irhandle_explict_layout_type (const Type * Ty) inline
Definition at line 157 of file SPIRVIRMapping.h.
References llvm::Type::getTypeID(), irhandle_ptr(), STK_ExplictLayoutType, and llvm::unifyPtrType().
Referenced by llvm::SPIRVIRMapping::add(), llvm::SPIRVIRMapping::find(), and llvm::SPIRVIRMapping::findMI().
irhandle_image()
IRHandle llvm::SPIRV::irhandle_image (const Type * SampledTy, unsigned Dim, unsigned Depth, unsigned Arrayed, unsigned MS, unsigned Sampled, unsigned ImageFormat, unsigned AQ = 0) inline
Definition at line 97 of file SPIRVIRMapping.h.
References llvm::Depth, and STK_Image.
irhandle_padding()
IRHandle llvm::SPIRV::irhandle_padding () inline
Definition at line 153 of file SPIRVIRMapping.h.
References STK_Padding.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreatePaddingType().
irhandle_pipe()
IRHandle llvm::SPIRV::irhandle_pipe (uint8_t AQ) inline
Definition at line 127 of file SPIRVIRMapping.h.
References STK_Pipe.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe().
irhandle_pointee()
IRHandle llvm::SPIRV::irhandle_pointee (const Type * ElementType, unsigned AddressSpace) inline
Definition at line 135 of file SPIRVIRMapping.h.
References STK_ElementPointer, and llvm::unifyPtrType().
Referenced by llvm::SPIRVIRMapping::add(), llvm::SPIRVIRMapping::find(), and llvm::SPIRVIRMapping::findMI().
irhandle_ptr()
IRHandle llvm::SPIRV::irhandle_ptr (const void * Ptr, unsigned Arg, enum SpecialTypeKind STK) inline
Definition at line 141 of file SPIRVIRMapping.h.
Referenced by handle(), handle(), handle(), and irhandle_explict_layout_type().
irhandle_sampled_image()
IRHandle llvm::SPIRV::irhandle_sampled_image (const Type * SampledTy, const MachineInstr * ImageTy) inline
Definition at line 107 of file SPIRVIRMapping.h.
References assert(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), STK_SampledImage, and llvm::SPIRV::ImageAttrs::Val.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage().
irhandle_sampler()
IRHandle llvm::SPIRV::irhandle_sampler () inline
Definition at line 123 of file SPIRVIRMapping.h.
References STK_Sampler.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampler().
irhandle_vkbuffer()
IRHandle llvm::SPIRV::irhandle_vkbuffer (const Type * ElementType, StorageClass::StorageClass SC, bool IsWriteable) inline
Definition at line 146 of file SPIRVIRMapping.h.
References STK_VkBuffer.
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateVulkanBufferType(), and llvm::SPIRVGlobalRegistry::getOrCreateVulkanPushConstantType().
lookupBuiltinNameHelper()
std::string llvm::SPIRV::lookupBuiltinNameHelper (StringRef DemangledCall, FPDecorationId * DecorationId)
Parses the name part of the demangled builtin call.
Definition at line 186 of file SPIRVBuiltins.cpp.
References llvm::demangledPostfixToDecorationId(), llvm::StringRef::rfind(), llvm::StringRef::size(), llvm::StringRef::starts_with(), and llvm::StringRef::substr().
Referenced by llvm::lookupBuiltin().
lowerBuiltin() [1/2]
std::optional< bool > llvm::SPIRV::lowerBuiltin (const StringRef DemangledCall, InstructionSet::InstructionSet Set, MachineIRBuilder & MIRBuilder, const Register OrigRet, const Type * OrigRetTy, const SmallVectorImpl< Register > & Args, SPIRVGlobalRegistry * GR, const CallBase & CB)
Lowers a builtin function call using the provided DemangledCall skeleton and external instruction Set.
Returns
the lowering success status if the called function is a recognized builtin, std::nullopt otherwise.
DemangledCall is the skeleton of the lowered builtin function call. Set is the external instruction set containing the given builtin. OrigRet is the single original virtual return register if defined, Register(0) otherwise. OrigRetTy is the type of the OrigRet. Args are the arguments of the lowered builtin call.
lowerBuiltin() [2/2]
std::optional< bool > llvm::SPIRV::lowerBuiltin (const StringRef DemangledCall, SPIRV::InstructionSet::InstructionSet Set, MachineIRBuilder & MIRBuilder, const Register OrigRet, const Type * OrigRetTy, const SmallVectorImpl< Register > & Args, SPIRVGlobalRegistry * GR, const CallBase & CB)
Definition at line 3116 of file SPIRVBuiltins.cpp.
References assert(), llvm::dbgs(), llvm::generate2DBlockIOINTELInst(), llvm::generateAPFixedPointInst(), llvm::generateAsyncCopy(), llvm::generateAtomicFloatingInst(), llvm::generateAtomicInst(), llvm::generateBarrierInst(), llvm::generateBindlessImageINTELInst(), llvm::generateBlockingPipesInst(), llvm::generateBuiltinVar(), llvm::generateCastToPtrInst(), llvm::generateConstructInst(), llvm::generateConvertInst(), llvm::generateCoopMatrInst(), llvm::generateDotOrFMulInst(), llvm::generateEnqueueInst(), llvm::generateExtendedBitOpsInst(), llvm::generateExtInst(), llvm::generateGetQueryInst(), llvm::generateGroupInst(), llvm::generateGroupUniformInst(), llvm::generateICarryBorrowInst(), llvm::generateImageChannelDataTypeInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::generateIntelSubgroupsInst(), llvm::generateKernelClockInst(), llvm::generateLoadStoreInst(), llvm::generatePipeInst(), llvm::generatePredicatedLoadStoreInst(), llvm::generateReadImageInst(), llvm::generateRelationalInst(), llvm::generateSampleImageInst(), llvm::generateSelectInst(), llvm::generateSpecConstantInst(), llvm::generateTernaryBitwiseFunctionINTELInst(), llvm::generateVectorLoadStoreInst(), llvm::generateWaveInst(), llvm::generateWriteImageInst(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), LLVM_DEBUG, and llvm::lookupBuiltin().
Referenced by llvm::SPIRVCallLowering::lowerCall().
lowerBuiltinType() [1/2]
SPIRVType * llvm::SPIRV::lowerBuiltinType (const Type * OpaqueType, SPIRV::AccessQualifier::AccessQualifier AccessQual, MachineIRBuilder & MIRBuilder, SPIRVGlobalRegistry * GR)
Definition at line 3514 of file SPIRVBuiltins.cpp.
References llvm::buildOpName(), llvm::dbgs(), llvm::dyn_cast(), llvm::MachineIRBuilder::getContext(), llvm::getCoopMatrType(), llvm::SPIRVGlobalRegistry::getImageType(), llvm::getInlineSpirvType(), llvm::getLayoutType(), llvm::MachineIRBuilder::getMRI(), llvm::getNonParameterizedType(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent(), llvm::SPIRVGlobalRegistry::getOrCreatePaddingType(), llvm::getPipeType(), llvm::getSampledImageType(), llvm::getSamplerType(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), llvm::Type::getStructName(), llvm::getVulkanBufferType(), llvm::getVulkanPushConstantType(), LLVM_DEBUG, llvm::SPIRV::BuiltinType::Opcode, parseBuiltinTypeNameToTargetExtType(), llvm::report_fatal_error(), and llvm::StringRef::str().
lowerBuiltinType() [2/2]
SPIRVType * llvm::SPIRV::lowerBuiltinType (const Type * Type, AccessQualifier::AccessQualifier AccessQual, MachineIRBuilder & MIRBuilder, SPIRVGlobalRegistry * GR)
Handles the translation of the provided special opaque/builtin type Type to SPIR-V type.
Generates the corresponding machine instructions for the target type or gets the already existing OpType<...> register from the global registry GR.
Returns
A machine instruction representing the OpType<...> SPIR-V type.
Type is the special opaque/builtin type to be lowered.
mapBuiltinToOpcode()
std::tuple< int, unsigned, unsigned > llvm::SPIRV::mapBuiltinToOpcode (const StringRef DemangledCall, SPIRV::InstructionSet::InstructionSet Set)
Helper function for finding a builtin function attributes by a demangled function name.
Defined in SPIRVBuiltins.cpp.
Definition at line 3046 of file SPIRVBuiltins.cpp.
References llvm::lookupBuiltin(), and Reg.
parseBuiltinCallArgumentBaseType()
Type * llvm::SPIRV::parseBuiltinCallArgumentBaseType (const StringRef DemangledCall, unsigned ArgIdx, LLVMContext & Ctx)
Parses the provided ArgIdx argument base type in the DemangledCall skeleton.
A base type is either a basic type (e.g. i32 for int), pointer element type (e.g. i8 for char*), or builtin type (TargetExtType).
Returns
LLVM Type or nullptr if unrecognized
DemangledCall is the skeleton of the lowered builtin function call. ArgIdx is the index of the argument to parse.
Definition at line 3281 of file SPIRVBuiltins.cpp.
References parseBuiltinCallArgumentType(), parseBuiltinTypeStr(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
parseBuiltinCallArgumentType()
Type * llvm::SPIRV::parseBuiltinCallArgumentType (StringRef TypeStr, LLVMContext & Ctx)
Definition at line 3224 of file SPIRVBuiltins.cpp.
References assert(), llvm::StringRef::consume_back(), llvm::StringRef::consume_front(), llvm::StringRef::ends_with(), llvm::StringRef::find(), llvm::StringRef::find_first_of(), llvm::VectorType::get(), llvm::StringRef::getAsInteger(), llvm::Type::getInt8Ty(), llvm::hasBuiltinTypePrefix(), llvm::parseBasicTypeName(), parseBuiltinTypeNameToTargetExtType(), llvm::StringRef::slice(), llvm::StringRef::str(), and llvm::StringRef::substr().
Referenced by parseBuiltinCallArgumentBaseType().
parseBuiltinTypeNameToTargetExtType()
TargetExtType * llvm::SPIRV::parseBuiltinTypeNameToTargetExtType (std::string TypeName, LLVMContext & Context)
Translates a string representing a SPIR-V or OpenCL builtin type to a TargetExtType that can be further lowered with lowerBuiltinType().
Returns
A TargetExtType representing the builtin SPIR-V type.
TypeName is the full string representation of the SPIR-V or OpenCL builtin type.
Definition at line 3465 of file SPIRVBuiltins.cpp.
References assert(), llvm::StringRef::contains(), llvm::StringRef::find(), llvm::TargetExtType::get(), isDigit(), llvm::parseTypeString(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::SPIRV::OpenCLType::SpirvTypeLiteral, llvm::StringRef::starts_with(), and llvm::StringRef::substr().
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateSPIRVTypeByName(), lowerBuiltinType(), and parseBuiltinCallArgumentType().
parseBuiltinTypeStr()
bool llvm::SPIRV::parseBuiltinTypeStr (SmallVector< StringRef, 10 > & BuiltinArgsTypeStrs, const StringRef DemangledCall, LLVMContext & Ctx)
Definition at line 3268 of file SPIRVBuiltins.cpp.
References llvm::StringRef::find(), llvm::StringRef::npos, llvm::StringRef::slice(), and llvm::StringRef::split().
Referenced by llvm::generateDotOrFMulInst(), and parseBuiltinCallArgumentBaseType().
to_hash()
size_t llvm::SPIRV::to_hash (const MachineInstr * MI) inline
Definition at line 28 of file SPIRVIRMapping.h.
References llvm::MachineOperand::getCImm(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getType(), H, llvm::hash_combine(), I, MI, llvm::MachineOperand::MO_CImmediate, and llvm::MachineOperand::MO_FPImmediate.
Referenced by llvm::SPIRVIRMapping::findMI(), getMIKey(), and handle().
type_has_layout_decoration()
bool llvm::SPIRV::type_has_layout_decoration (const Type * T) inline
Definition at line 175 of file SPIRVIRMapping.h.
References llvm::isa(), and T.
Referenced by llvm::SPIRVIRMapping::add(), llvm::SPIRVIRMapping::find(), and llvm::SPIRVIRMapping::findMI().