LLVM: llvm::RISCVVType Namespace Reference
llvm::RISCVVType Namespace Reference
Enumerations
enum VLMUL : uint8_t {
LMUL_1 = 0 , LMUL_2 , LMUL_4 , LMUL_8 ,
LMUL_RESERVED , LMUL_F8 , LMUL_F4 , LMUL_F2
}
enum { TAIL_UNDISTURBED_MASK_UNDISTURBED = 0 , TAIL_AGNOSTIC = 1 , MASK_AGNOSTIC = 2 }
Functions
static bool isValidSEW (unsigned SEW)
static bool isValidLMUL (unsigned LMUL, bool Fractional)
LLVM_ABI unsigned encodeVTYPE (VLMUL VLMUL, unsigned SEW, bool TailAgnostic, bool MaskAgnostic, bool AltFmt=false)
LLVM_ABI unsigned encodeXSfmmVType (unsigned SEW, unsigned Widen, bool AltFmt)
static VLMUL getVLMUL (unsigned VType)
LLVM_ABI std::pair< unsigned, bool > decodeVLMUL (VLMUL VLMul)
static VLMUL encodeLMUL (unsigned LMUL, bool Fractional)
static unsigned decodeVSEW (unsigned VSEW)
static unsigned encodeSEW (unsigned SEW)
static unsigned getSEW (unsigned VType)
static unsigned decodeTWiden (unsigned TWiden)
static bool hasXSfmmWiden (unsigned VType)
static unsigned getXSfmmWiden (unsigned VType)
static bool isValidXSfmmVType (unsigned VTypeI)
static bool isTailAgnostic (unsigned VType)
static bool isMaskAgnostic (unsigned VType)
static bool isAltFmt (unsigned VType)
LLVM_ABI void printVType (unsigned VType, raw_ostream &OS)
LLVM_ABI void printXSfmmVType (unsigned VType, raw_ostream &OS)
LLVM_ABI unsigned getSEWLMULRatio (unsigned SEW, VLMUL VLMul)
LLVM_ABI std::optional< VLMUL > getSameRatioLMUL (unsigned Ratio, unsigned EEW)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TAIL_UNDISTURBED_MASK_UNDISTURBED
TAIL_AGNOSTIC
MASK_AGNOSTIC
Definition at line 84 of file RISCVTargetParser.h.
VLMUL
enum llvm::RISCVVType::VLMUL : uint8_t
Enumerator
LMUL_1
LMUL_2
LMUL_4
LMUL_8
LMUL_RESERVED
LMUL_F8
LMUL_F4
LMUL_F2
Definition at line 73 of file RISCVTargetParser.h.
Function Documentation
decodeTWiden()
unsigned llvm::RISCVVType::decodeTWiden (unsigned TWiden) inline static
Definition at line 134 of file RISCVTargetParser.h.
References assert().
Referenced by llvm::RISCVDAGToDAGISel::selectXSfmmVSET().
decodeVLMUL()
std::pair< unsigned, bool > llvm::RISCVVType::decodeVLMUL (VLMUL VLMul)
Definition at line 186 of file RISCVTargetParser.cpp.
References llvm_unreachable, LMUL_1, LMUL_2, LMUL_4, LMUL_8, LMUL_F2, LMUL_F4, and LMUL_F8.
Referenced by llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCV::computeVLMAX(), llvm::RISCVInstrInfo::copyPhysRegVector(), getEMULEqualsEEWDivSEWTimesLMUL(), llvm::RISCVTargetLowering::getLMULCost(), getSEWLMULRatio(), llvm::RISCVTargetLowering::isLegalInterleavedAccessType(), llvm::RISCV::isLMUL1OrSmaller(), isTupleInsertInstr(), llvm::RISCVInstrInfo::isVRegCopy(), llvm::RISCVRegisterInfo::lowerSegmentSpillReload(), printVType(), llvm::RISCVDAGToDAGISel::selectVLXSEG(), and llvm::RISCVDAGToDAGISel::selectVSXSEG().
decodeVSEW()
unsigned llvm::RISCVVType::decodeVSEW (unsigned VSEW) inline static
Definition at line 119 of file RISCVTargetParser.h.
References assert().
Referenced by llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), getSEW(), llvm::RISCVDAGToDAGISel::selectVSETVLI(), and llvm::RISCVDAGToDAGISel::selectXSfmmVSET().
encodeLMUL()
VLMUL llvm::RISCVVType::encodeLMUL (unsigned LMUL, bool Fractional) inline static
Definition at line 113 of file RISCVTargetParser.h.
References assert(), isValidLMUL(), and llvm::Log2_32().
Referenced by getSameRatioLMUL(), and lowerGetVectorLength().
encodeSEW()
unsigned llvm::RISCVVType::encodeSEW (unsigned SEW) inline static
Definition at line 124 of file RISCVTargetParser.h.
References assert(), isValidSEW(), and llvm::Log2_32().
Referenced by encodeVTYPE(), encodeXSfmmVType(), lowerGetVectorLength(), and lowerVectorIntrinsicScalars().
encodeVTYPE()
unsigned llvm::RISCVVType::encodeVTYPE (VLMUL VLMUL, unsigned SEW, bool TailAgnostic, bool MaskAgnostic, bool AltFmt = false)
Definition at line 161 of file RISCVTargetParser.cpp.
References assert(), encodeSEW(), and isValidSEW().
Referenced by llvm::RISCV::VSETVLIInfo::encodeVTYPE(), and llvm::RISCVDAGToDAGISel::selectVSETVLI().
encodeXSfmmVType()
unsigned llvm::RISCVVType::encodeXSfmmVType (unsigned SEW, unsigned Widen, bool AltFmt)
Definition at line 177 of file RISCVTargetParser.cpp.
References assert(), encodeSEW(), isValidSEW(), llvm::Log2_32(), and Widen().
Referenced by llvm::RISCV::VSETVLIInfo::encodeVTYPE(), and llvm::RISCVDAGToDAGISel::selectXSfmmVSET().
getSameRatioLMUL()
std::optional< VLMUL > llvm::RISCVVType::getSameRatioLMUL (unsigned Ratio, unsigned EEW)
Definition at line 247 of file RISCVTargetParser.cpp.
References encodeLMUL(), and isValidLMUL().
Referenced by adjustIncoming(), and llvm::mca::getEEWAndEMUL().
getSEW()
unsigned llvm::RISCVVType::getSEW (unsigned VType) inline static
Definition at line 129 of file RISCVTargetParser.h.
References decodeVSEW().
Referenced by llvm::RISCV::areCompatibleVTYPEs(), llvm::mca::RISCVInstrumentManager::createInstruments(), isConvertibleToVMV_V_V(), isValidXSfmmVType(), printVType(), llvm::RISCVInstPrinter::printVTypeI(), llvm::RISCVInstPrinter::printXSfmmVType(), printXSfmmVType(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
getSEWLMULRatio()
unsigned llvm::RISCVVType::getSEWLMULRatio (unsigned SEW, VLMUL VLMul)
Definition at line 235 of file RISCVTargetParser.cpp.
References assert(), and decodeVLMUL().
Referenced by llvm::RISCV::areCompatibleVTYPEs(), computeKnownBitsFromOperator(), llvm::mca::getEEWAndEMUL(), llvm::RISCV::VSETVLIInfo::getSEWLMULRatio(), and llvm::RISCVDAGToDAGISel::selectVSETVLI().
getVLMUL()
VLMUL llvm::RISCVVType::getVLMUL (unsigned VType) inline static
Definition at line 105 of file RISCVTargetParser.h.
Referenced by llvm::RISCV::areCompatibleVTYPEs(), llvm::mca::RISCVInstrumentManager::createInstruments(), isConvertibleToVMV_V_V(), printVType(), llvm::RISCVInstPrinter::printVTypeI(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
getXSfmmWiden()
unsigned llvm::RISCVVType::getXSfmmWiden (unsigned VType) inline static
Definition at line 145 of file RISCVTargetParser.h.
References assert().
Referenced by llvm::RISCV::areCompatibleVTYPEs(), isValidXSfmmVType(), llvm::RISCVInstPrinter::printXSfmmVType(), printXSfmmVType(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
hasXSfmmWiden()
bool llvm::RISCVVType::hasXSfmmWiden (unsigned VType) inline static
Definition at line 140 of file RISCVTargetParser.h.
Referenced by llvm::RISCV::areCompatibleVTYPEs(), isValidXSfmmVType(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
isAltFmt()
bool llvm::RISCVVType::isAltFmt (unsigned VType) inline static
Definition at line 160 of file RISCVTargetParser.h.
Referenced by llvm::RISCV::areCompatibleVTYPEs(), printVType(), llvm::RISCVInstPrinter::printVTypeI(), llvm::RISCVInstPrinter::printXSfmmVType(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
isMaskAgnostic()
bool llvm::RISCVVType::isMaskAgnostic (unsigned VType) inline static
Definition at line 158 of file RISCVTargetParser.h.
Referenced by llvm::RISCV::areCompatibleVTYPEs(), printVType(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
isTailAgnostic()
bool llvm::RISCVVType::isTailAgnostic (unsigned VType) inline static
Definition at line 156 of file RISCVTargetParser.h.
Referenced by llvm::RISCV::areCompatibleVTYPEs(), isConvertibleToVMV_V_V(), printVType(), and llvm::RISCV::VSETVLIInfo::setVTYPE().
isValidLMUL()
bool llvm::RISCVVType::isValidLMUL (unsigned LMUL, bool Fractional) inline static
Definition at line 96 of file RISCVTargetParser.h.
References llvm::isPowerOf2_32().
Referenced by encodeLMUL(), and getSameRatioLMUL().
isValidSEW()
bool llvm::RISCVVType::isValidSEW (unsigned SEW) inline static
Definition at line 91 of file RISCVTargetParser.h.
References llvm::isPowerOf2_32().
Referenced by llvm::RISCV::RISCVVSETVLIInfoAnalysis::computeInfoForInstr(), llvm::RISCVInstrInfo::createMIROperandComment(), encodeSEW(), encodeVTYPE(), encodeXSfmmVType(), and llvm::RISCVInstrInfo::verifyInstruction().
isValidXSfmmVType()
bool llvm::RISCVVType::isValidXSfmmVType (unsigned VTypeI) inline static
Definition at line 151 of file RISCVTargetParser.h.
References getSEW(), getXSfmmWiden(), and hasXSfmmWiden().
Referenced by llvm::RISCVInstPrinter::printXSfmmVType(), and llvm::RISCVInstrInfo::verifyInstruction().
printVType()
void llvm::RISCVVType::printVType (unsigned VType, raw_ostream & OS)
Definition at line 202 of file RISCVTargetParser.cpp.
References decodeVLMUL(), getSEW(), getVLMUL(), isAltFmt(), isMaskAgnostic(), and isTailAgnostic().
Referenced by llvm::RISCVInstrInfo::createMIROperandComment(), and llvm::RISCVInstPrinter::printVTypeI().
printXSfmmVType()
void llvm::RISCVVType::printXSfmmVType (unsigned VType, raw_ostream & OS)
Definition at line 231 of file RISCVTargetParser.cpp.
References getSEW(), and getXSfmmWiden().
Referenced by llvm::RISCVInstrInfo::createMIROperandComment().