LLVM: llvm::sys::detail Namespace Reference
llvm::sys::detail Namespace Reference
Namespaces
namespace x86
Helper functions to extract CPU details from CPUID on x86.
Functions
LLVM_ABI StringRef getHostCPUNameForPowerPC (StringRef ProcCpuinfoContent)
Helper functions to extract HostCPUName from /proc/cpuinfo on linux.
LLVM_ABI StringRef getHostCPUNameForARM (StringRef ProcCpuinfoContent)
LLVM_ABI StringRef getHostCPUNameForARM (uint64_t PrimaryCpuInfo, ArrayRef< uint64_t > UniqueCpuInfos)
LLVM_ABI StringRef getHostCPUNameForS390x (StringRef ProcCpuinfoContent)
LLVM_ABI StringRef getHostCPUNameForRISCV (StringRef ProcCpuinfoContent)
LLVM_ABI StringRef getHostCPUNameForSPARC (StringRef ProcCpuinfoContent)
LLVM_ABI StringRef getHostCPUNameForBPF ()
Function Documentation
getHostCPUNameForARM() [1/2]
StringRef llvm::sys::detail::getHostCPUNameForARM (StringRef ProcCpuinfoContent)
Definition at line 399 of file Host.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), getHostCPUNameForARMFromComponents(), I, llvm::sort(), llvm::StringRef::split(), and llvm::unique().
getHostCPUNameForARM() [2/2]
StringRef llvm::sys::detail::getHostCPUNameForARM (uint64_t PrimaryCpuInfo, ArrayRef< uint64_t > UniqueCpuInfos)
Definition at line 441 of file Host.cpp.
References llvm::Bitfield::get(), getHostCPUNameForARMFromComponents(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::ArrayRef< T >::size(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
getHostCPUNameForBPF()
StringRef llvm::sys::detail::getHostCPUNameForBPF ()
Definition at line 572 of file Host.cpp.
getHostCPUNameForPowerPC()
StringRef llvm::sys::detail::getHostCPUNameForPowerPC (StringRef ProcCpuinfoContent)
Helper functions to extract HostCPUName from /proc/cpuinfo on linux.
Definition at line 89 of file Host.cpp.
References llvm::StringRef::begin(), llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and llvm::StringRef::end().
getHostCPUNameForRISCV()
StringRef llvm::sys::detail::getHostCPUNameForRISCV (StringRef ProcCpuinfoContent)
Definition at line 551 of file Host.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and llvm::StringRef::split().
getHostCPUNameForS390x()
StringRef llvm::sys::detail::getHostCPUNameForS390x (StringRef ProcCpuinfoContent)
Definition at line 510 of file Host.cpp.
References llvm::is_contained(), llvm::StringRef::npos, and llvm::StringRef::split().
getHostCPUNameForSPARC()
LLVM_ABI StringRef llvm::sys::detail::getHostCPUNameForSPARC (StringRef ProcCpuinfoContent)
References LLVM_ABI.