LLVM: llvm::sys::sandbox Namespace Reference
llvm::sys::sandbox Namespace Reference
Classes
struct ScopedSetting
Functions
ScopedSetting scopedEnable ()
ScopedSetting scopedDisable ()
void violationIfEnabled ()
Function Documentation
scopedDisable()
ScopedSetting llvm::sys::sandbox::scopedDisable () inline
Definition at line 36 of file IOSandbox.h.
Referenced by llvm::cas::ondisk::UnifiedOnDiskCache::close(), llvm::vfs::OnDiskOutputBackend::createFileImpl(), createTempFile(), llvm::sys::fs::createTemporaryFile(), getFD(), llvm::cas::ondisk::OnDiskGraphDB::load(), llvm::vfs::OnDiskOutputBackend::makeAbsolute(), llvm::cas::ondisk::UnifiedOnDiskCache::open(), llvm::raw_fd_ostream::raw_fd_ostream(), llvm::sys::RunSignalHandlers(), llvm::LockFileManager::tryLock(), llvm::LockFileManager::unsafeMaybeUnlock(), llvm::LockFileManager::waitForUnlockFor(), and llvm::LockFileManager::~LockFileManager().
scopedEnable()
ScopedSetting llvm::sys::sandbox::scopedEnable () inline
Definition at line 35 of file IOSandbox.h.
violationIfEnabled()
void llvm::sys::sandbox::violationIfEnabled () inline
Definition at line 37 of file IOSandbox.h.
Referenced by llvm::vfs::createPhysicalFileSystem(), llvm::MemoryBuffer::getFile(), llvm::WritableMemoryBuffer::getFile(), llvm::WriteThroughMemoryBuffer::getFile(), llvm::MemoryBuffer::getFileAsStream(), llvm::MemoryBuffer::getFileOrSTDIN(), llvm::MemoryBuffer::getFileSlice(), llvm::WritableMemoryBuffer::getFileSlice(), llvm::WriteThroughMemoryBuffer::getFileSlice(), llvm::MemoryBuffer::getOpenFile(), llvm::MemoryBuffer::getOpenFileSlice(), llvm::sys::fs::getPermissions(), llvm::vfs::getRealFileSystem(), llvm::MemoryBuffer::getSTDIN(), llvm::sys::fs::getUniqueID(), llvm::sys::fs::is_directory(), llvm::sys::fs::is_other(), llvm::sys::fs::is_regular_file(), llvm::sys::fs::is_symlink_file(), llvm::sys::fs::make_absolute(), llvm::sys::fs::md5_contents(), llvm::sys::fs::md5_contents(), and llvm::sys::fs::readNativeFileToEOF().