LLVM: llvm::offloading::intel Namespace Reference
llvm::offloading::intel Namespace Reference
Functions
LLVM_ABI Error containerizeOpenMPSPIRVImage (std::unique_ptr< MemoryBuffer > &Binary)
Containerizes an offloading binary into the ELF binary format expected by the Intel runtime offload plugin.
Function Documentation
containerizeOpenMPSPIRVImage()
Error llvm::offloading::intel::containerizeOpenMPSPIRVImage (std::unique_ptr< MemoryBuffer > & Binary)
Containerizes an offloading binary into the ELF binary format expected by the Intel runtime offload plugin.
Definition at line 380 of file Utility.cpp.
References llvm::ELFYAML::Section::AddressAlign, llvm::ELFYAML::FileHeader::Class, llvm::ELFYAML::Section::Content, llvm::createStringError(), llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::EM_INTELGT, llvm::ELF::ET_DYN, llvm::MemoryBuffer::getMemBufferCopy(), llvm::ELFYAML::Chunk::Name, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PROGBITS, llvm::Error::success(), llvm::ELFYAML::Section::Type, UINT64_MAX, llvm::Version, and llvm::yaml::yaml2elf().