LLVM: llvm::RISCVZC Namespace Reference
llvm::RISCVZC Namespace Reference
Enumerations
enum RLISTENCODE {
RA = 4 , RA_S0 , RA_S0_S1 , RA_S0_S2 ,
RA_S0_S3 , RA_S0_S4 , RA_S0_S5 , RA_S0_S6 ,
RA_S0_S7 , RA_S0_S8 , RA_S0_S9 , RA_S0_S11 ,
INVALID_RLIST
}
Functions
unsigned encodeRegList (MCRegister EndReg, bool IsRVE=false)
static unsigned encodeRegListNumRegs (unsigned NumRegs)
static unsigned getStackAdjBase (unsigned RlistVal, bool IsRV64)
void printRegList (unsigned RlistEncode, raw_ostream &OS)
Enumeration Type Documentation
RLISTENCODE
enum llvm::RISCVZC::RLISTENCODE
Enumerator
RA
RA_S0
RA_S0_S1
RA_S0_S2
RA_S0_S3
RA_S0_S4
RA_S0_S5
RA_S0_S6
RA_S0_S7
RA_S0_S8
RA_S0_S9
RA_S0_S11
INVALID_RLIST
Definition at line 696 of file RISCVBaseInfo.h.
Function Documentation
encodeRegList()
unsigned llvm::RISCVZC::encodeRegList (MCRegister EndReg, bool IsRVE = false) inline
Definition at line 713 of file RISCVBaseInfo.h.
References assert(), llvm::MCRegister::id(), llvm_unreachable, RA, RA_S0, RA_S0_S1, RA_S0_S11, RA_S0_S2, RA_S0_S3, RA_S0_S4, RA_S0_S5, RA_S0_S6, RA_S0_S7, RA_S0_S8, and RA_S0_S9.
encodeRegListNumRegs()
unsigned llvm::RISCVZC::encodeRegListNumRegs (unsigned NumRegs) inline static
Definition at line 745 of file RISCVBaseInfo.h.
References assert(), RA, and RA_S0_S11.
Referenced by llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), and llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
getStackAdjBase()
unsigned llvm::RISCVZC::getStackAdjBase (unsigned RlistVal, bool IsRV64) inline static
Definition at line 754 of file RISCVBaseInfo.h.
References llvm::alignTo(), assert(), RA, RA_S0_S11, and RegSize.
Referenced by llvm::RISCVInstPrinter::printStackAdj().
printRegList()
void llvm::RISCVZC::printRegList (unsigned RlistEncode, raw_ostream & OS)
Definition at line 245 of file RISCVBaseInfo.cpp.
References assert(), RA, RA_S0, and RA_S0_S11.