LLVM: llvm::sframe Namespace Reference
llvm::sframe Namespace Reference
Namespaces
namespace detail
Classes
struct Preamble
struct Header
struct FDEInfo
struct FuncDescEntry
struct FREInfo
struct FrameRowEntry
Typedefs
template<endianness E>
using FrameRowEntryAddr1 = FrameRowEntry<uint8_t, E>
template<endianness E>
using FrameRowEntryAddr2 = FrameRowEntry<uint16_t, E>
template<endianness E>
using FrameRowEntryAddr4 = FrameRowEntry<uint32_t, E>
Enumerations
enum class Version : uint8_t
enum class Flags : uint8_t { V2AllFlags = FDESorted | FramePointer | FDEFuncStartPCRel , LLVM_MARK_AS_BITMASK_ENUM =(0xff) }
enum class ABI : uint8_t
enum class FREType : uint8_t
SFrame FRE Types. Bits 0-3 of FuncDescEntry.Info.
enum class FDEType : uint8_t
SFrame FDE Types. Bit 4 of FuncDescEntry.Info.
enum class AArch64PAuthKey : uint8_t
Speficies key used for signing return addresses.
enum class FREOffset : uint8_t
Size of stack offsets. Bits 6-7 of FREInfo.Info.
enum class BaseReg : uint8_t { FP = 0 , SP = 1 }
Stack frame base register. Bit 0 of FREInfo.Info.
Functions
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
LLVM_ABI ArrayRef< EnumEntry< Version > > getVersions ()
LLVM_ABI ArrayRef< EnumEntry< Flags > > getFlags ()
LLVM_ABI ArrayRef< EnumEntry< ABI > > getABIs ()
LLVM_ABI ArrayRef< EnumEntry< FREType > > getFRETypes ()
LLVM_ABI ArrayRef< EnumEntry< FDEType > > getFDETypes ()
LLVM_ABI ArrayRef< EnumEntry< AArch64PAuthKey > > getAArch64PAuthKeys ()
LLVM_ABI ArrayRef< EnumEntry< FREOffset > > getFREOffsets ()
LLVM_ABI ArrayRef< EnumEntry< BaseReg > > getBaseRegisters ()
Variables
constexpr uint16_t Magic = 0xdee2
Typedef Documentation
FrameRowEntryAddr1
template<endianness E> using llvm::sframe::FrameRowEntryAddr1 = FrameRowEntry<uint8_t, E>
Definition at line 167 of file SFrame.h.
FrameRowEntryAddr2
template<endianness E> using llvm::sframe::FrameRowEntryAddr2 = FrameRowEntry<uint16_t, E>
Definition at line 168 of file SFrame.h.
FrameRowEntryAddr4
template<endianness E> using llvm::sframe::FrameRowEntryAddr4 = FrameRowEntry<uint32_t, E>
Definition at line 169 of file SFrame.h.
Enumeration Type Documentation
AArch64PAuthKey
enum class llvm::sframe::AArch64PAuthKey : uint8_t strong
Speficies key used for signing return addresses.
Bit 5 of FuncDescEntry.Info.
Definition at line 65 of file SFrame.h.
ABI
enum class llvm::sframe::ABI : uint8_t strong
Definition at line 46 of file SFrame.h.
BaseReg
enum class llvm::sframe::BaseReg : uint8_t strong
Stack frame base register. Bit 0 of FREInfo.Info.
Enumerator
FP
SP
Definition at line 77 of file SFrame.h.
FDEType
enum class llvm::sframe::FDEType : uint8_t strong
SFrame FDE Types. Bit 4 of FuncDescEntry.Info.
Definition at line 58 of file SFrame.h.
Flags
enum class llvm::sframe::Flags : uint8_t strong
Enumerator
V2AllFlags
LLVM_MARK_AS_BITMASK_ENUM
Definition at line 39 of file SFrame.h.
FREOffset
enum class llvm::sframe::FREOffset : uint8_t strong
Size of stack offsets. Bits 6-7 of FREInfo.Info.
Definition at line 71 of file SFrame.h.
FREType
enum class llvm::sframe::FREType : uint8_t strong
SFrame FRE Types. Bits 0-3 of FuncDescEntry.Info.
Definition at line 52 of file SFrame.h.
Version
enum class llvm::sframe::Version : uint8_t strong
Definition at line 34 of file SFrame.h.
Function Documentation
getAArch64PAuthKeys()
ArrayRef< EnumEntry< sframe::AArch64PAuthKey > > llvm::sframe::getAArch64PAuthKeys ()
Definition at line 55 of file SFrame.cpp.
References llvm::ArrayRef().
getABIs()
ArrayRef< EnumEntry< sframe::ABI > > llvm::sframe::getABIs ()
Definition at line 31 of file SFrame.cpp.
References llvm::ArrayRef().
getBaseRegisters()
ArrayRef< EnumEntry< sframe::BaseReg > > llvm::sframe::getBaseRegisters ()
Definition at line 72 of file SFrame.cpp.
References llvm::ArrayRef(), FP, and SP.
getFDETypes()
ArrayRef< EnumEntry< sframe::FDEType > > llvm::sframe::getFDETypes ()
Definition at line 47 of file SFrame.cpp.
References llvm::ArrayRef().
getFlags()
ArrayRef< EnumEntry< sframe::Flags > > llvm::sframe::getFlags ()
Definition at line 23 of file SFrame.cpp.
References llvm::ArrayRef().
getFREOffsets()
ArrayRef< EnumEntry< sframe::FREOffset > > llvm::sframe::getFREOffsets ()
Definition at line 64 of file SFrame.cpp.
References llvm::ArrayRef().
getFRETypes()
ArrayRef< EnumEntry< sframe::FREType > > llvm::sframe::getFRETypes ()
Definition at line 39 of file SFrame.cpp.
References llvm::ArrayRef().
getVersions()
ArrayRef< EnumEntry< sframe::Version > > llvm::sframe::getVersions ()
Definition at line 14 of file SFrame.cpp.
References llvm::ArrayRef().
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
llvm::sframe::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
Variable Documentation
Magic
uint16_t llvm::sframe::Magic = 0xdee2 constexpr
Definition at line 32 of file SFrame.h.
Referenced by llvm::object::SFrameParser< E >::create().