LLVM: adjust::ldi Namespace Reference
adjust::ldi Namespace Reference
Fixups relating to the LDI instruction.
Functions
static void fixup (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
Adjusts a value to fix up the immediate of an LDI Rd, K instruction.
static void neg (uint64_t &Value)
static void lo8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
static void hi8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
static void hh8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
static void ms8 (unsigned Size, const MCFixup &Fixup, uint64_t &Value, MCContext *Ctx)
Detailed Description
Fixups relating to the LDI instruction.
Function Documentation
fixup()
void adjust::ldi::fixup (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
Adjusts a value to fix up the immediate of an LDI Rd, K instruction.
Resolves to: 0000 KKKK 0000 KKKK Offset of 0 (so the result isn't left-shifted before application).
Definition at line 208 of file AVRAsmBackend.cpp.
References Fixup.
Referenced by llvm::AVRAsmBackend::adjustFixupValue(), hh8(), hi8(), lo8(), and ms8().
hh8()
void adjust::ldi::hh8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
Definition at line 230 of file AVRAsmBackend.cpp.
References Fixup, fixup(), and Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
hi8()
void adjust::ldi::hi8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
Definition at line 224 of file AVRAsmBackend.cpp.
References Fixup, fixup(), and Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
lo8()
void adjust::ldi::lo8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
Definition at line 218 of file AVRAsmBackend.cpp.
References Fixup, fixup(), and Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
ms8()
void adjust::ldi::ms8 (unsigned Size, const MCFixup & Fixup, uint64_t & Value, MCContext * Ctx) static
Definition at line 236 of file AVRAsmBackend.cpp.
References Fixup, fixup(), and Size.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().
neg()
void adjust::ldi::neg (uint64_t & Value) static
Definition at line 216 of file AVRAsmBackend.cpp.
Referenced by llvm::AVRAsmBackend::adjustFixupValue().