LLVM: llvm::cas::builtin Namespace Reference
llvm::cas::builtin Namespace Reference
Classes
class BuiltinCASContext
CASContext for LLVM builtin CAS using BLAKE3 hash type.
class BuiltinCAS
Common base class for builtin CAS implementations using the same CASContext.
Typedefs
using HasherT = BLAKE3
Current hash type for the builtin CAS.
using HashType = decltype(HasherT::hash(std::declval<ArrayRef<uint8_t> &>()))
Functions
Expected< std::unique_ptr< ondisk::UnifiedOnDiskCache > > createBuiltinUnifiedOnDiskCache (StringRef Path)
Create a UnifiedOnDiskCache instance that uses BLAKE3 hashing.
std::unique_ptr< ObjectStore > createObjectStoreFromUnifiedOnDiskCache (std::shared_ptr< ondisk::UnifiedOnDiskCache > UniDB)
std::unique_ptr< ActionCache > createActionCacheFromUnifiedOnDiskCache (std::shared_ptr< ondisk::UnifiedOnDiskCache > UniDB)
Variables
constexpr StringLiteral DefaultDirProxy = "/^llvm::cas::builtin::default"
constexpr StringLiteral DefaultDir = "llvm.cas.builtin.default"
Typedef Documentation
HasherT
using llvm::cas::builtin::HasherT = BLAKE3
Current hash type for the builtin CAS.
FIXME: This should be configurable via an enum to allow configuring the hash function. The enum should be sent into createInMemoryCAS() and createOnDiskCAS().
This is important (at least) for future-proofing, when we want to make new CAS instances use BLAKE7, but still know how to read/write BLAKE3.
Even just for BLAKE3, it would be useful to have these values:
BLAKE3     => 32B hash from BLAKE3
BLAKE3_16B => 16B hash from BLAKE3 (truncated)
... where BLAKE3_16 uses TruncatedBLAKE3<16>.
Motivation for a truncated hash is that it's cheaper to store. It's not clear if we always (or ever) need the full 32B, and for an ephemeral in-memory CAS, we almost certainly don't need it.
Note that the cost is linear in the number of objects for the builtin CAS, since we're using internal offsets and/or pointers as an optimization.
However, it's possible we'll want to hook up a local builtin CAS to, e.g., a distributed generic hash map to use as an ActionCache. In that scenario, the transitive closure of the structured objects that are the results of the cached actions would need to be serialized into the map, something like:
"action:<schema>:<key>" -> "0123"
"object:<schema>:0123"  -> "3,4567,89AB,CDEF,9,some data"
"object:<schema>:4567"  -> ...
"object:<schema>:89AB"  -> ...
"object:<schema>:CDEF"  -> ...
These references would be full cost.
Definition at line 54 of file BuiltinCASContext.h.
HashType
using llvm::cas::builtin::HashType = decltype(HasherT::hash(std::declval<ArrayRef<uint8_t> &>()))
Definition at line 55 of file BuiltinCASContext.h.
Function Documentation
createActionCacheFromUnifiedOnDiskCache()
std::unique_ptr< ActionCache > llvm::cas::builtin::createActionCacheFromUnifiedOnDiskCache (std::shared_ptr< ondisk::UnifiedOnDiskCache > UniDB)
Parameters
UniDB A UnifiedOnDiskCache instance from createBuiltinUnifiedOnDiskCache.
Definition at line 278 of file ActionCaches.cpp.
Referenced by llvm::cas::createOnDiskUnifiedCASDatabases(), and validateInProcess().
createBuiltinUnifiedOnDiskCache()
Expected< std::unique_ptr< ondisk::UnifiedOnDiskCache > > llvm::cas::builtin::createBuiltinUnifiedOnDiskCache (StringRef Path)
Create a UnifiedOnDiskCache instance that uses BLAKE3 hashing.
Definition at line 98 of file BuiltinCAS.cpp.
References llvm::createStringError(), llvm::cas::builtin::BuiltinCASContext::getHashName(), llvm::inconvertibleErrorCode(), and llvm::cas::ondisk::UnifiedOnDiskCache::open().
Referenced by llvm::cas::createOnDiskUnifiedCASDatabases().
createObjectStoreFromUnifiedOnDiskCache()
std::unique_ptr< ObjectStore > llvm::cas::builtin::createObjectStoreFromUnifiedOnDiskCache (std::shared_ptr< ondisk::UnifiedOnDiskCache > UniDB)
Parameters
UniDB A UnifiedOnDiskCache instance from createBuiltinUnifiedOnDiskCache.
Definition at line 208 of file OnDiskCAS.cpp.
Referenced by llvm::cas::createOnDiskUnifiedCASDatabases(), and validateInProcess().
Variable Documentation
DefaultDir
StringLiteral llvm::cas::builtin::DefaultDir = "llvm.cas.builtin.default" constexpr
Definition at line 90 of file BuiltinCAS.h.
DefaultDirProxy
StringLiteral llvm::cas::builtin::DefaultDirProxy = "/^llvm::cas::builtin::default" constexpr
Definition at line 89 of file BuiltinCAS.h.