LLVM: llvm::cas Namespace Reference
llvm::cas Namespace Reference
Namespaces
namespace builtin
namespace ondisk
Classes
class CacheKey
A key for caching an operation.
class ActionCache
A cache from a key (that describes an action) to the result of performing that action.
class BuiltinObjectHasher
Hasher for stored objects in builtin CAS.
class CASContext
Context for CAS identifiers.
class CASID
Unique identifier for a CAS object.
class ReferenceBase
Base class for references to things in ObjectStore.
class ObjectRef
Reference to an object in an ObjectStore instance.
class ObjectHandle
Handle to a loaded object in a ObjectStore instance.
class FileOffset
FileOffset is a wrapper around uint64_t to represent the offset of data from the beginning of the file.
class MappedFileRegionArena
Allocator for an owned mapped file region that supports thread-safe and process-safe bump pointer allocation.
class ObjectStore
Content-addressable storage for objects.
class ObjectProxy
Reference to an abstract hierarchical node, with data and references.
class OnDiskDataAllocator
Sink for data.
class OnDiskTrieRawHashMap
OnDiskTrieRawHashMap is a persistent trie data structure used as hash maps.
Enumerations
enum class ValidationResult { Valid , Recovered , Skipped }
Represents the result of validating the contents using validateOnDiskUnifiedCASDatabasesIfNeeded.
Functions
LLVM_ABI std::unique_ptr< ActionCache > createInMemoryActionCache ()
Create an action cache in memory.
LLVM_ABI Expected< std::unique_ptr< ActionCache > > createOnDiskActionCache (StringRef Path)
Create an action cache on disk.
LLVM_ABI Expected< std::pair< std::unique_ptr< ObjectStore >, std::unique_ptr< ActionCache > > > createOnDiskUnifiedCASDatabases (StringRef Path)
Create on-disk ObjectStore and ActionCache instances based on ondisk::UnifiedOnDiskCache, with built-in hashing.
LLVM_ABI Expected< ValidationResult > validateOnDiskUnifiedCASDatabasesIfNeeded (StringRef Path, bool CheckHash, bool AllowRecovery, bool ForceValidation, std::optional< StringRef > LLVMCasBinaryPath)
Validate the data in Path, if needed to ensure correctness.
LLVM_ABI std::unique_ptr< ObjectStore > createInMemoryCAS ()
Create an in memory CAS.
bool isOnDiskCASEnabled ()
LLVM_ABI Expected< std::unique_ptr< ObjectStore > > createOnDiskCAS (const Twine &Path)
Create a persistent on-disk path at Path.
Enumeration Type Documentation
ValidationResult
enum class llvm::cas::ValidationResult strong
Represents the result of validating the contents using validateOnDiskUnifiedCASDatabasesIfNeeded.
Note: invalid results are handled as an Error.
Enumerator
Valid
The data is already valid.
Recovered
The data was invalid, but was recovered.
Skipped
Validation was skipped, as it was not needed.
Definition at line 29 of file BuiltinUnifiedCASDatabases.h.
Function Documentation
createInMemoryActionCache()
std::unique_ptr< ActionCache > llvm::cas::createInMemoryActionCache ()
Create an action cache in memory.
Definition at line 143 of file ActionCaches.cpp.
createInMemoryCAS()
std::unique_ptr< ObjectStore > llvm::cas::createInMemoryCAS ()
Create an in memory CAS.
Definition at line 335 of file InMemoryCAS.cpp.
createOnDiskActionCache()
Expected< std::unique_ptr< ActionCache > > llvm::cas::createOnDiskActionCache (StringRef Path)
Create an action cache on disk.
Definition at line 269 of file ActionCaches.cpp.
References llvm::createStringError(), and llvm::inconvertibleErrorCode().
createOnDiskCAS()
Expected< std::unique_ptr< ObjectStore > > llvm::cas::createOnDiskCAS (const Twine & Path)
Create a persistent on-disk path at Path.
Definition at line 193 of file OnDiskCAS.cpp.
References llvm::createStringError(), llvm::inconvertibleErrorCode(), and llvm::sys::fs::make_absolute().
createOnDiskUnifiedCASDatabases()
Expected< std::pair< std::unique_ptr< ObjectStore >, std::unique_ptr< ActionCache > > > llvm::cas::createOnDiskUnifiedCASDatabases (StringRef Path)
Create on-disk ObjectStore and ActionCache instances based on ondisk::UnifiedOnDiskCache, with built-in hashing.
Definition at line 18 of file BuiltinUnifiedCASDatabases.cpp.
References llvm::cas::builtin::createActionCacheFromUnifiedOnDiskCache(), llvm::cas::builtin::createBuiltinUnifiedOnDiskCache(), and llvm::cas::builtin::createObjectStoreFromUnifiedOnDiskCache().
isOnDiskCASEnabled()
bool llvm::cas::isOnDiskCASEnabled ()
Returns
true if LLVM_ENABLE_ONDISK_CAS configuration was enabled.
Definition at line 185 of file OnDiskCAS.cpp.
validateOnDiskUnifiedCASDatabasesIfNeeded()
Expected< ValidationResult > llvm::cas::validateOnDiskUnifiedCASDatabasesIfNeeded (StringRef Path, bool CheckHash, bool AllowRecovery, bool ForceValidation, std::optional< StringRef > LLVMCasBinaryPath)
Validate the data in Path, if needed to ensure correctness.
Parameters
Path directory for the on-disk database.
CheckHash Whether to validate hashes match the data.
AllowRecovery Whether to automatically recover from invalid data by marking the files for garbage collection.
ForceValidation Whether to force validation to occur even if it should not be necessary.
LLVMCasBinaryPath If provided, validation is performed out-of-process using the given llvm-cas executable which protects against crashes during validation. Otherwise validation is performed in-process.
Returns
Valid if the data is already valid, Recovered if data was invalid but has been cleared, Skipped if validation is not needed, or an Error if validation cannot be performed or if the data is left in an invalid state because AllowRecovery is false.
Definition at line 27 of file BuiltinUnifiedCASDatabases.cpp.
References llvm::createStringError(), llvm::cas::builtin::BuiltinCASContext::getHashName(), llvm::inconvertibleErrorCode(), and llvm::cas::ondisk::UnifiedOnDiskCache::validateIfNeeded().