LLVM: llvm::MIPS_MC Namespace Reference
llvm::MIPS_MC Namespace Reference
Functions
void initLLVMToCVRegMapping (MCRegisterInfo *MRI)
StringRef selectMipsCPU (const Triple &TT, StringRef CPU)
Select the Mips CPU for the given triple and cpu name.
Function Documentation
initLLVMToCVRegMapping()
void llvm::MIPS_MC::initLLVMToCVRegMapping (MCRegisterInfo * MRI)
Definition at line 48 of file MipsMCTargetDesc.cpp.
References I, and MRI.
Referenced by llvm::MipsRegisterInfo::MipsRegisterInfo().
selectMipsCPU()
StringRef llvm::MIPS_MC::selectMipsCPU (const Triple & TT, StringRef CPU)
Select the Mips CPU for the given triple and cpu name.
Definition at line 136 of file MipsMCTargetDesc.cpp.
References llvm::Triple::MipsSubArch_r6.
Referenced by createMipsMCSubtargetInfo(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), and llvm::MipsSubtarget::initializeSubtargetDependencies().