LLVM: llvm::detail Namespace Reference
llvm::detail Namespace Reference
A self-contained host- and target-independent arbitrary-precision floating-point software implementation.
Classes
class IEEEFloat
class DoubleAPFloat
struct DenseMapPair
struct DenseSetEmpty
class DenseSetPair
class DenseSetImpl
Base class for DenseSet and DenseSmallSet.
class UniqueFunctionBase
struct IdentityIndex
struct PunnedPointer
struct PointerSumTypeHelper
A helper template for implementing PointerSumType.
struct CheckedInt
struct SafeIntIterator
class SlowDynamicAPInt
A simple class providing dynamic arbitrary-precision arithmetic.
struct ZipTupleType
struct zip_common
struct zip_first
struct zip_shortest
struct ZippyIteratorTuple
Helper to obtain the iterator types for the tuple storage within zippy.
struct ZippyIteratorTuple< ItType, std::tuple< Args... >, std::index_sequence< Ns... > >
Partial specialization for non-const tuple storage.
struct ZippyIteratorTuple< ItType, const std::tuple< Args... >, std::index_sequence< Ns... > >
Partial specialization for const tuple storage.
class zippy
struct ZipLongestItemType
struct ZipLongestTupleType
class zip_longest_iterator
class zip_longest_range
class concat_range
Helper to store a sequence of ranges being concatenated and access them.
class indexed_accessor_range_base
The class represents the base of a range of indexed_accessor_iterators.
class first_or_second_type
Return a reference to the first or second member of a reference.
struct Visitor
struct Visitor< HeadT, TailTs... >
struct Visitor< HeadT >
struct enumerator_result
Tuple-like type for zip_enumerator dereference.
struct zip_enumerator
Zippy iterator that uses the second iterator for comparisons.
struct enumerator_result< std::size_t, Refs... >
struct index_iterator
struct index_stream
Infinite stream of increasing 0-based size_t indices.
struct detector
struct detector< std::void_t< Op< Args... > >, Op, Args... >
class TypeSwitchBase
class PtrUseVisitorBase
Implementation of non-dependent functionality for PtrUseVisitor.
class BCField
Convenience base for all kinds of bitcode abbreviation fields.
class BCRecordCoding
Helper class for dealing with a scalar element in the middle of a record.
class BCRecordCoding< ElementTy >
Helper class for dealing with a scalar element at the end of a record.
class BCRecordCoding< BCArray< ElementTy > >
Helper class for dealing with an array at the end of a record.
class BCRecordCoding< BCBlob >
Helper class for dealing with a blob at the end of a record.
struct last_type
A type trait whose type field is the last of its template parameters.
struct last_type< Head >
struct is_array
A type trait whose value field is true if the given type is a BCArray (of any element kind).
struct PassConcept
Template for the abstract base class used to dispatch polymorphically over pass objects.
struct PassModel
A template wrapper used to implement the polymorphic API.
struct AnalysisResultConcept
Abstract concept of an analysis result.
class ResultHasInvalidateMethod
SFINAE metafunction for computing whether ResultT provides an invalidate member function.
struct AnalysisResultModel
Wrapper to model the analysis result concept.
struct AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, false >
Specialization of AnalysisResultModel which provides the default invalidate functionality.
struct AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >
Specialization of AnalysisResultModel which delegates invalidate handling to ResultT.
struct AnalysisPassConcept
Abstract concept of an analysis pass.
struct AnalysisPassModel
Wrapper to model the analysis pass concept.
class AllocatorHolder
class AllocatorHolder< Alloc & >
struct IsaCheckPredicate
struct IsaAndPresentCheckPredicate
struct StaticCastFunc
Usable in generic algorithms like map_range.
struct DynCastFunc
struct CastFunc
struct CastIfPresentFunc
struct DynCastIfPresentFunc
struct unit
struct unit< std::ratio< 3600 > >
struct unit< std::ratio< 60 > >
struct unit< std::ratio< 1 > >
struct unit< std::milli >
struct unit< std::micro >
struct unit< std::nano >
struct decay_if_c_char_array
struct decay_if_c_char_array< char[N]>
struct HasPointerLikeTypeTraits
struct HasPointerLikeTypeTraits< T, decltype((sizeof(PointerLikeTypeTraits< T >)+sizeof(T)), void())>
struct IsPointerLike
struct IsPointerLike< T * >
class StringMapEntryMatcherImpl
class StringMapEntryMatcher
class ValueMatchesMono
class ValueMatchesPoly
class ErrorMatchesMono
class ErrorMessageMatches
struct ErrorHolder
struct ExpectedHolder
class ValueIsMatcher
Typedefs
template<typename RangeT>
using IterOfRange = decltype(adl_begin(std::declval<RangeT &>()))
template<typename RangeT>
using ValueOfRange
using integerPart = APFloatBase::integerPart
using uninitializedTag = APFloatBase::uninitializedTag
using roundingMode = APFloatBase::roundingMode
using opStatus = APFloatBase::opStatus
using cmpResult = APFloatBase::cmpResult
using fltCategory = APFloatBase::fltCategory
using ExponentType = APFloatBase::ExponentType
template<typename ValueT, typename ValueInfoT>
using DenseSet
template<typename ValueT, unsigned InlineBuckets, typename ValueInfoT>
using SmallDenseSet
template<typename CallableT, typename ThisT>
using EnableUnlessSameType
template<typename CallableT, typename Ret, typename... Params>
using EnableIfCallable
template<typename T>
using has_number_t
template<typename Set, typename Fn>
using check_has_member_remove_if_t
template<typename Set>
using check_has_member_erase_iter_t
template<typename Range>
using check_has_free_function_rbegin
template<typename IterT>
using fwd_or_bidi_tag
A type alias which is std::bidirectional_iterator_tag if the category of IterT derives from it, and std::forward_iterator_tag otherwise.
template<typename ZipType, typename ReferenceTupleType, typename... Iters>
using zip_traits
template<typename T>
using sort_trivially_copyable
template<typename Range>
using check_has_free_function_size
template<typename Range, typename Element>
using check_has_member_contains_t
template<typename Range, typename Element>
using check_has_member_find_t
template<typename... Iters>
using EnumeratorTupleType = enumerator_result<decltype(*declval<Iters>())...>
template<typename T>
using has_sizeof = decltype(sizeof(T))
template<typename... Types>
using has_blob = std::is_same<BCBlob, typename last_type<int, Types...>::type>
A type trait whose value field is true if the last type is BCBlob.
template<typename... Types>
using has_array = is_array<typename last_type<int, Types...>::type>
A type trait whose value field is true if the last type is a BCArray (of any element kind).
template<typename OptionalDerived, typename Default>
using SelfType
A helper to derive the type to use with Self for cast traits, when the provided CRTP derived type is allowed to be void.
template<typename T>
using decay_if_c_char_array_t = typename decay_if_c_char_array<T>::type
template<class BlockT>
using has_hoist_check = decltype(&BlockT::isLegalToHoistInto)
template<class BlockT>
using detect_has_hoist_check = llvm::is_detected<has_hoist_check, BlockT>
template<typename T>
using check_ostream
Functions
LLVM_ABI hash_code hash_value (const IEEEFloat &Arg)
LLVM_ABI int ilogb (const IEEEFloat &Arg)
LLVM_ABI IEEEFloat scalbn (IEEEFloat X, int Exp, roundingMode RoundingMode)
LLVM_ABI IEEEFloat frexp (const IEEEFloat &Val, int &Exp, roundingMode RM)
LLVM_ABI hash_code hash_value (const DoubleAPFloat &Arg)
LLVM_ABI DoubleAPFloat scalbn (const DoubleAPFloat &Arg, int Exp, roundingMode RM)
LLVM_ABI DoubleAPFloat frexp (const DoubleAPFloat &X, int &Exp, roundingMode)
unsigned combineHashValue (unsigned a, unsigned b)
Simplistic combination of 32-bit hash values into 32-bit hash values.
template<typename ValueT, typename MapTy, typename ValueInfoT>
bool operator== (const DenseSetImpl< ValueT, MapTy, ValueInfoT > &LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > &RHS)
Equality comparison for DenseSet.
template<typename ValueT, typename MapTy, typename ValueInfoT>
bool operator!= (const DenseSetImpl< ValueT, MapTy, ValueInfoT > &LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > &RHS)
Inequality comparison for DenseSet.
template<typename T, typename U>
bool canTypeFitValue (const U Value)
template<class S1Ty, class S2Ty>
bool set_intersects_impl (const S1Ty &S1, const S2Ty &S2)
raw_ostream & operator<< (raw_ostream &OS, const SlowDynamicAPInt &X)
LLVM_ABI SlowDynamicAPInt mod (const SlowDynamicAPInt &LHS, const SlowDynamicAPInt &RHS)
Returns the remainder of dividing LHS by RHS.
LLVM_ABI SlowDynamicAPInt lcm (const SlowDynamicAPInt &A, const SlowDynamicAPInt &B)
Returns the least common multiple of A and B.
LLVM_ABI SlowDynamicAPInt abs (const SlowDynamicAPInt &X)
Redeclarations of friend declarations above to make it discoverable by lookups.
LLVM_ABI SlowDynamicAPInt ceilDiv (const SlowDynamicAPInt &LHS, const SlowDynamicAPInt &RHS)
LLVM_ABI SlowDynamicAPInt floorDiv (const SlowDynamicAPInt &LHS, const SlowDynamicAPInt &RHS)
LLVM_ABI SlowDynamicAPInt gcd (const SlowDynamicAPInt &A, const SlowDynamicAPInt &B)
LLVM_ABI hash_code hash_value (const SlowDynamicAPInt &X)
LLVM_ABI SlowDynamicAPInt & operator+= (SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt & operator-= (SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt & operator*= (SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt & operator/= (SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt & operator%= (SlowDynamicAPInt &A, int64_t B)
LLVM_ABI bool operator== (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI bool operator!= (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI bool operator> (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI bool operator< (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI bool operator<= (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI bool operator>= (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt operator+ (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt operator- (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt operator* (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt operator/ (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI SlowDynamicAPInt operator% (const SlowDynamicAPInt &A, int64_t B)
LLVM_ABI bool operator== (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI bool operator!= (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI bool operator> (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI bool operator< (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI bool operator<= (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI bool operator>= (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI SlowDynamicAPInt operator+ (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI SlowDynamicAPInt operator- (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI SlowDynamicAPInt operator* (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI SlowDynamicAPInt operator/ (int64_t A, const SlowDynamicAPInt &B)
LLVM_ABI SlowDynamicAPInt operator% (int64_t A, const SlowDynamicAPInt &B)
template<typename Iter>
Iter next_or_end (const Iter &I, const Iter &End)
template<typename Iter>
auto deref_or_none (const Iter &I, const Iter &End) -> std::optional< std::remove_const_t< std::remove_reference_t< decltype(*I)> > >
template<typename OtherT, typename DerivedT, typename BaseT, typename T, typename PointerT, typename ReferenceT>
bool operator== (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &lhs, const OtherT &rhs)
Compare this range with another.
template<typename OtherT, typename DerivedT, typename BaseT, typename T, typename PointerT, typename ReferenceT>
bool operator!= (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &lhs, const OtherT &rhs)
template<typename Predicate, typename... Args>
bool all_of_zip_predicate_first (Predicate &&P, Args &&...args)
template<typename... ArgsThenPredicate, size_t... InputIndexes>
bool all_of_zip_predicate_last (std::tuple< ArgsThenPredicate... > argsThenPredicate, std::index_sequence< InputIndexes... >)
template<typename FieldTy>
static void emitOps (llvm::BitCodeAbbrev &abbrev)
Attaches the last field to an abbreviation.
template<typename FieldTy, typename Next, typename... Rest>
static void emitOps (llvm::BitCodeAbbrev &abbrev)
Attaches fields to an abbreviation.
template<typename DieType>
DieType resolveReferencedType (DieType D, dwarf::Attribute Attr=dwarf::DW_AT_type)
template<typename DieType>
DieType resolveReferencedType (DieType D, typename DieType::DWARFFormValue F)
template<typename DWARFFormValueType>
const char * toString (std::optional< DWARFFormValueType > F)
template<typename DieType>
DieType unwrapReferencedTypedefType (DieType D)
Resolve the DW_AT_type of D until we reach a DIE that is not a DW_TAG_typedef.
template<typename PassT, typename IRUnitT, typename AnalysisManagerT, typename... ArgTs, size_t... Ns>
PassT::Result getAnalysisResultUnpackTuple (AnalysisManagerT &AM, IRUnitT &IR, std::tuple< ArgTs... > Args, std::index_sequence< Ns... >)
Actual unpacker of extra arguments in getAnalysisResult, passes only those tuple arguments that are mentioned in index_sequence.
template<typename PassT, typename IRUnitT, typename... AnalysisArgTs, typename... MainArgTs>
PassT::Result getAnalysisResult (AnalysisManager< IRUnitT, AnalysisArgTs... > &AM, IRUnitT &IR, std::tuple< MainArgTs... > Args)
Helper for partial unpacking of extra arguments in getAnalysisResult.
LLVM_ABI void printBumpPtrAllocatorStats (unsigned NumSlabs, size_t BytesAllocated, size_t TotalMemory)
template<typename T>
bool isPresent (const T &t)
template<typename T>
decltype(auto) unwrapValue (T &t)
template<typename Range>
auto reverse_if_helper (Range &&R, std::bool_constant< false >)
template<typename Range>
auto reverse_if_helper (Range &&R, std::bool_constant< true >)
template<bool B, typename Range>
auto reverse_if (Range &&R)
template<class BlockT>
bool isLegalToHoistInto (BlockT *Block)
SFINAE functions that dispatch to the isLegalToHoistInto member function or return false, if it doesn't exist.
ErrorHolder TakeError (Error Err)
template<typename T>
ExpectedHolder< T > TakeExpected (Expected< T > &Exp)
template<typename T>
ExpectedHolder< T > TakeExpected (Expected< T > &&Exp)
void PrintTo (const ErrorHolder &Err, std::ostream *Out)
template<typename T>
void PrintTo (const ExpectedHolder< T > &Item, std::ostream *Out)
static void tcSetLeastSignificantBits (APInt::WordType *dst, unsigned parts, unsigned bits)
static std::pair< APFloat, APFloat > fastTwoSum (APFloat X, APFloat Y)
int ilogb (const DoubleAPFloat &Arg)
DoubleAPFloat scalbn (const DoubleAPFloat &Arg, int Exp, APFloat::roundingMode RM)
DoubleAPFloat frexp (const DoubleAPFloat &Arg, int &Exp, APFloat::roundingMode RM)
template<typename DstTy, typename RecipeBasePtrTy>
static auto castToVPIRMetadata (RecipeBasePtrTy R) -> DstTy
Variables
static constexpr uninitializedTag uninitialized = APFloatBase::uninitialized
static constexpr roundingMode rmNearestTiesToEven
static constexpr roundingMode rmNearestTiesToAway
static constexpr roundingMode rmTowardNegative = APFloatBase::rmTowardNegative
static constexpr roundingMode rmTowardPositive = APFloatBase::rmTowardPositive
static constexpr roundingMode rmTowardZero = APFloatBase::rmTowardZero
static constexpr unsigned integerPartWidth = APFloatBase::integerPartWidth
static constexpr cmpResult cmpEqual = APFloatBase::cmpEqual
static constexpr cmpResult cmpLessThan = APFloatBase::cmpLessThan
static constexpr cmpResult cmpGreaterThan = APFloatBase::cmpGreaterThan
static constexpr cmpResult cmpUnordered = APFloatBase::cmpUnordered
static constexpr opStatus opOK = APFloatBase::opOK
static constexpr opStatus opInvalidOp = APFloatBase::opInvalidOp
static constexpr opStatus opDivByZero = APFloatBase::opDivByZero
static constexpr opStatus opOverflow = APFloatBase::opOverflow
static constexpr opStatus opUnderflow = APFloatBase::opUnderflow
static constexpr opStatus opInexact = APFloatBase::opInexact
static constexpr fltCategory fcInfinity = APFloatBase::fcInfinity
static constexpr fltCategory fcNaN = APFloatBase::fcNaN
static constexpr fltCategory fcNormal = APFloatBase::fcNormal
static constexpr fltCategory fcZero = APFloatBase::fcZero
template<typename Set, typename Fn>
static constexpr bool HasMemberRemoveIf
template<typename Set>
static constexpr bool HasMemberEraseIter
template<typename Range>
static constexpr bool HasFreeFunctionRBegin
template<typename Range>
static constexpr bool HasFreeFunctionSize
template<typename Range, typename Element>
static constexpr bool HasMemberContains
template<typename Range, typename Element>
static constexpr bool HasMemberFind
template<typename Period>
const char unit< Period >::value [] = ""
Detailed Description
A self-contained host- and target-independent arbitrary-precision floating-point software implementation.
Casting from (const) VPRecipeBase -> (const) VPIRMetadata is supported for all recipe types implementing VPIRMetadata.
These are templated helper classes used by the format function that capture the object to be formatted and the format string.
These are wrappers over isa* function that allow them to be used in generic algorithms such as llvm:all_of, llvm::none_of, etc.
APFloat uses bignum integer arithmetic as provided by static functions in the APInt class. The library will work with bignum integers whose parts are any unsigned type at least 16 bits wide, but 64 bits is recommended.
Written for clarity rather than speed, in particular with a view to use in the front-end of a cross compiler so that target arithmetic can be correctly performed on the host. Performance should nonetheless be reasonable, particularly for its intended use. It may be useful as a base implementation for a run-time library during development of a faster target-specific one.
All 5 rounding modes in the IEEE-754R draft are handled correctly for all implemented operations. Currently implemented operations are add, subtract, multiply, divide, fused-multiply-add, conversion-to-float, conversion-to-integer and conversion-from-integer. New rounding modes (e.g. away from zero) can be added with three or four lines of code.
Four formats are built-in: IEEE single precision, double precision, quadruple precision, and x87 80-bit extended double (when operating with full extended precision). Adding a new format that obeys IEEE semantics only requires adding two lines of code: a declaration and definition of the format.
All operations return the status of that operation as an exception bit-mask, so multiple operations can be done consecutively with their results or-ed together. The returned status can be useful for compiler diagnostics; e.g., inexact, underflow and overflow can be easily diagnosed on constant folding, and compiler optimizers can determine what exceptions would be raised by folding operations and optimize, or perhaps not optimize, accordingly.
At present, underflow tininess is detected after rounding; it should be straight forward to add support for the before-rounding case too.
The library reads hexadecimal floating point numbers as per C99, and correctly rounds if necessary according to the specified rounding mode. Syntax is required to have been validated by the caller. It also converts floating point numbers to hexadecimal text as per the C99 a and A conversions. The output precision (or alternatively the natural minimal precision) can be specified; if the requested precision is less than the natural precision the output is correctly rounded for the specified rounding mode.
It also reads decimal floating point numbers and correctly rounds according to the specified rounding mode.
Conversion to decimal text is not currently implemented.
Non-zero finite numbers are represented internally as a sign bit, a 16-bit signed exponent, and the significand as an array of integer parts. After normalization of a number of precision P the exponent is within the range of the format, and if the number is not denormal the P-th bit of the significand is set as an explicit integer bit. For denormals the most significant bit is shifted right so that the exponent is maintained at the format's minimum, so that the smallest denormal has just the least significant bit of the significand set. The sign of zeroes and infinities is significant; the exponent and significand of such numbers is not stored, but has a known implicit (deterministic) value: 0 for the significands, 0 for zero exponent, all 1 bits for infinity exponent. For NaNs the sign and significand are deterministic, although not really meaningful, and preserved in non-conversion operations. The exponent is implicitly all 1 bits.
APFloat does not provide any exception handling beyond default exception handling. We represent Signaling NaNs via IEEE-754R 2008 6.2.1 should clause by encoding Signaling NaNs with the first bit of its trailing significand as 0.
TODO
Some features that may or may not be worth adding:
Binary to decimal conversion (hard).
Optional ability to detect underflow tininess before rounding.
New formats: x87 in single and double precision mode (IEEE apart from extended exponent range) (hard).
New operations: sqrt, IEEE remainder, C90 fmod, nexttoward.
This is accomplished by exposing the isa* functions through function objects with a generic function call operator.
When actually printed, this synthesizes the string into a temporary buffer provided and returns whether or not it is big enough.
Used by isa<> & co.
Typedef Documentation
check_has_free_function_rbegin
template<typename Range> using llvm::detail::check_has_free_function_rbegin
Initial value:
decltype(adl_rbegin(std::declval<Range &>()))
Definition at line 396 of file STLExtras.h.
check_has_free_function_size
template<typename Range> using llvm::detail::check_has_free_function_size
Initial value:
decltype(adl_size(std::declval<Range &>()))
Definition at line 1678 of file STLExtras.h.
check_has_member_contains_t
template<typename Range, typename Element> using llvm::detail::check_has_member_contains_t
Initial value:
decltype(std::declval<Range &>().contains(std::declval<const Element &>()))
Definition at line 1921 of file STLExtras.h.
check_has_member_erase_iter_t
template<typename Set> using llvm::detail::check_has_member_erase_iter_t
Initial value:
decltype(std::declval<Set>().erase(std::declval<Set>().begin()))
Definition at line 32 of file SetOperations.h.
check_has_member_find_t
template<typename Range, typename Element> using llvm::detail::check_has_member_find_t
Initial value:
decltype(std::declval<Range &>().find(std::declval<const Element &>()) !=
         std::declval<Range &>().end())
Definition at line 1929 of file STLExtras.h.
check_has_member_remove_if_t
template<typename Set, typename Fn> using llvm::detail::check_has_member_remove_if_t
Initial value:
decltype(std::declval<Set>().remove_if(std::declval<Fn>()))
Definition at line 24 of file SetOperations.h.
check_ostream
template<typename T> using llvm::detail::check_ostream
Initial value:
decltype(std::declval<std::ostream &>() << std::declval<T>())
Definition at line 22 of file StringMapEntry.h.
cmpResult
using llvm::detail::cmpResult = APFloatBase::cmpResult
Definition at line 418 of file APFloat.h.
decay_if_c_char_array_t
template<typename T> using llvm::detail::decay_if_c_char_array_t = typename decay_if_c_char_array<T>::type
Definition at line 89 of file Format.h.
DenseSet
template<typename ValueT, typename ValueInfoT> using llvm::detail::DenseSet
Initial value:
DenseSetImpl<
   ValueT, DenseMap<ValueT, DenseSetEmpty, ValueInfoT, DenseSetPair<ValueT>>,
   ValueInfoT>
Definition at line 264 of file DenseSet.h.
detect_has_hoist_check
template<class BlockT> using llvm::detail::detect_has_hoist_check = llvm::is_detected<has_hoist_check, BlockT>
Definition at line 190 of file GenericLoopInfoImpl.h.
EnableIfCallable
template<typename CallableT, typename Ret, typename... Params> using llvm::detail::EnableIfCallable
Initial value:
std::enable_if_t<std::disjunction<
   std::is_void<Ret>,
   std::is_same<decltype(std::declval<CallableT>()(std::declval<Params>()...)),
                Ret>,
   std::is_same<const decltype(std::declval<CallableT>()(
                    std::declval<Params>()...)),
                Ret>,
   std::is_convertible<decltype(std::declval<CallableT>()(
                           std::declval<Params>()...)),
                       Ret>>::value>
Definition at line 64 of file FunctionExtras.h.
EnableUnlessSameType
template<typename CallableT, typename ThisT> using llvm::detail::EnableUnlessSameType
Initial value:
std::enable_if_t<!std::is_same<remove_cvref_t<CallableT>, ThisT>::value>
Definition at line 61 of file FunctionExtras.h.
EnumeratorTupleType
template<typename... Iters> using llvm::detail::EnumeratorTupleType = enumerator_result<decltype(*declval<Iters>())...>
Definition at line 2337 of file STLExtras.h.
ExponentType
using llvm::detail::ExponentType = APFloatBase::ExponentType
Definition at line 420 of file APFloat.h.
fltCategory
using llvm::detail::fltCategory = APFloatBase::fltCategory
Definition at line 419 of file APFloat.h.
fwd_or_bidi_tag
template<typename IterT> using llvm::detail::fwd_or_bidi_tag
Initial value:
std::conditional_t<
   std::is_base_of_v<std::bidirectional_iterator_tag,
                     typename std::iterator_traits<IterT>::iterator_category>,
   std::bidirectional_iterator_tag, std::forward_iterator_tag>
A type alias which is std::bidirectional_iterator_tag if the category of IterT derives from it, and std::forward_iterator_tag otherwise.
Definition at line 527 of file STLExtras.h.
has_array
template<typename... Types> using llvm::detail::has_array = is_array<typename last_type<int, Types...>::type>
A type trait whose value field is true if the last type is a BCArray (of any element kind).
Definition at line 350 of file BitcodeConvenience.h.
has_blob
template<typename... Types> using llvm::detail::has_blob = std::is_same<BCBlob, typename last_type<int, Types...>::type>
A type trait whose value field is true if the last type is BCBlob.
Definition at line 332 of file BitcodeConvenience.h.
has_hoist_check
template<class BlockT> using llvm::detail::has_hoist_check = decltype(&BlockT::isLegalToHoistInto)
Definition at line 187 of file GenericLoopInfoImpl.h.
has_number_t
template<typename T> using llvm::detail::has_number_t
Initial value:
decltype(GraphTraits<T>::getNumber(
   std::declval<typename GraphTraits<T>::NodeRef>()))
Definition at line 100 of file GraphTraits.h.
has_sizeof
template<typename T> using llvm::detail::has_sizeof = decltype(sizeof(T))
Definition at line 2663 of file STLExtras.h.
integerPart
using llvm::detail::integerPart = APFloatBase::integerPart
Definition at line 414 of file APFloat.h.
IterOfRange
template<typename RangeT> using llvm::detail::IterOfRange = decltype(adl_begin(std::declval<RangeT &>()))
Definition at line 126 of file ADL.h.
opStatus
using llvm::detail::opStatus = APFloatBase::opStatus
Definition at line 417 of file APFloat.h.
roundingMode
using llvm::detail::roundingMode = APFloatBase::roundingMode
Definition at line 416 of file APFloat.h.
SelfType
template<typename OptionalDerived, typename Default> using llvm::detail::SelfType
Initial value:
std::conditional_t<std::is_same_v<OptionalDerived, void>,
                                   Default, OptionalDerived>
A helper to derive the type to use with Self for cast traits, when the provided CRTP derived type is allowed to be void.
Definition at line 321 of file Casting.h.
SmallDenseSet
template<typename ValueT, unsigned InlineBuckets, typename ValueInfoT> using llvm::detail::SmallDenseSet
Initial value:
DenseSetImpl<ValueT,
             SmallDenseMap<ValueT, DenseSetEmpty, InlineBuckets, ValueInfoT,
                           DenseSetPair<ValueT>>,
             ValueInfoT>
Definition at line 269 of file DenseSet.h.
sort_trivially_copyable
template<typename T> using llvm::detail::sort_trivially_copyable
Initial value:
std::conjunction<
   std::is_pointer<T>,
   std::is_trivially_copyable<typename std::iterator_traits<T>::value_type>>
Definition at line 1626 of file STLExtras.h.
uninitializedTag
using llvm::detail::uninitializedTag = APFloatBase::uninitializedTag
Definition at line 415 of file APFloat.h.
ValueOfRange
template<typename RangeT> using llvm::detail::ValueOfRange
Initial value:
std::remove_reference_t<decltype(*adl_begin(std::declval<RangeT &>()))>
Definition at line 129 of file ADL.h.
zip_traits
template<typename ZipType, typename ReferenceTupleType, typename... Iters> using llvm::detail::zip_traits
Initial value:
iterator_facade_base<
   ZipType,
   std::common_type_t<
       std::bidirectional_iterator_tag,
       typename std::iterator_traits<Iters>::iterator_category...>,
   ReferenceTupleType,
   typename std::iterator_traits<
       std::tuple_element_t<0, std::tuple<Iters...>>>::difference_type,
   ReferenceTupleType *, ReferenceTupleType>
Definition at line 661 of file STLExtras.h.
Function Documentation
abs()
SlowDynamicAPInt llvm::detail::abs (const SlowDynamicAPInt & X)
Redeclarations of friend declarations above to make it discoverable by lookups.
Definition at line 190 of file SlowDynamicAPInt.cpp.
References X.
Referenced by frexp(), lcm(), and llvm::detail::DoubleAPFloat::roundToIntegral().
all_of_zip_predicate_first()
template<typename Predicate, typename... Args> bool llvm::detail::all_of_zip_predicate_first (Predicate && P, Args &&... args)
Definition at line 2548 of file STLExtras.h.
References args, llvm::end(), P, and llvm::zip().
Referenced by all_of_zip_predicate_last().
all_of_zip_predicate_last()
template<typename... ArgsThenPredicate, size_t... InputIndexes> bool llvm::detail::all_of_zip_predicate_last (std::tuple< ArgsThenPredicate... > argsThenPredicate, std::index_sequence< InputIndexes... >)
Definition at line 2563 of file STLExtras.h.
References all_of_zip_predicate_first(), and unit< Period >::value.
Referenced by llvm::all_of_zip().
canTypeFitValue()
template<typename T, typename U> bool llvm::detail::canTypeFitValue (const U Value)
Definition at line 114 of file Sequence.h.
References llvm::Value.
Referenced by llvm::detail::CheckedInt::from(), and llvm::detail::CheckedInt::to().
castToVPIRMetadata()
template<typename DstTy, typename RecipeBasePtrTy> auto llvm::detail::castToVPIRMetadata (RecipeBasePtrTy R) -> DstTy inline static
Definition at line 3882 of file VPlan.h.
References llvm::cast(), and llvm_unreachable.
Referenced by llvm::CastInfoVPIRMetadata< DstTy, SrcTy >::doCast().
ceilDiv()
SlowDynamicAPInt llvm::detail::ceilDiv (const SlowDynamicAPInt & LHS, const SlowDynamicAPInt & RHS)
Definition at line 193 of file SlowDynamicAPInt.cpp.
References getMaxWidth(), llvm::APIntOps::RoundingSDiv(), and llvm::APInt::UP.
combineHashValue()
unsigned llvm::detail::combineHashValue (unsigned a, unsigned b) inline
Simplistic combination of 32-bit hash values into 32-bit hash values.
Definition at line 41 of file DenseMapInfo.h.
References llvm::densemap::detail::mix().
Referenced by llvm::ScalarEvolution::FoldID::computeHash(), ReachabilityQueryInfo< ToTy >::computeHashValue(), llvm::DenseMapInfo< AA::RangeTy >::getHashValue(), llvm::DenseMapInfo< BoUpSLP::EdgeInfo >::getHashValue(), llvm::DenseMapInfo< MBBSectionID >::getHashValue(), llvm::DenseMapInfo< std::optional< T > >::getHashValue(), llvm::DenseMapInfo< std::pair< const MCSymbol *, PPCMCExpr::Specifier > >::getHashValue(), llvm::DenseMapInfo< std::pair< T, U > >::getHashValue(), llvm::DenseMapInfo< VersionTuple >::getHashValue(), llvm::DenseMapInfo< std::tuple< Ts... > >::getHashValueImpl(), and llvm::DenseMapInfo< std::pair< T, U > >::getHashValuePiecewise().
deref_or_none()
template<typename Iter> auto llvm::detail::deref_or_none (const Iter & I, const Iter & End) -> std::optional< std::remove_const_t< std::remove_reference_t< decltype(*I)> > >
Definition at line 870 of file STLExtras.h.
References I.
emitOps() [1/2]
template<typename FieldTy, typename Next, typename... Rest> void llvm::detail::emitOps (llvm::BitCodeAbbrev & abbrev) static
Attaches fields to an abbreviation.
This is the recursive case for emitOps.
See also
BCRecordLayout::emitAbbrev
Definition at line 176 of file BitcodeConvenience.h.
References emitOps(), and llvm::Next.
emitOps() [2/2]
template<typename FieldTy> void llvm::detail::emitOps (llvm::BitCodeAbbrev & abbrev) static
Attaches the last field to an abbreviation.
This is the base case for emitOps.
See also
BCRecordLayout::emitAbbrev
Definition at line 166 of file BitcodeConvenience.h.
Referenced by llvm::BCGenericRecordLayout< BCLiteral< RecordCode >, Fields... >::emitAbbrev(), and emitOps().
fastTwoSum()
std::pair< APFloat, APFloat > llvm::detail::fastTwoSum (APFloat X, APFloat Y) static
Definition at line 4857 of file APFloat.cpp.
References llvm::APFloat::getZero(), llvm::Hi, llvm::Lo, X, and Y.
Referenced by llvm::detail::DoubleAPFloat::roundToIntegral().
floorDiv()
SlowDynamicAPInt llvm::detail::floorDiv (const SlowDynamicAPInt & LHS, const SlowDynamicAPInt & RHS)
Definition at line 201 of file SlowDynamicAPInt.cpp.
References llvm::APInt::DOWN, getMaxWidth(), and llvm::APIntOps::RoundingSDiv().
frexp() [1/3]
DoubleAPFloat llvm::detail::frexp (const DoubleAPFloat & Arg, int & Exp, APFloat::roundingMode RM)
Definition at line 5843 of file APFloat.cpp.
References abs(), assert(), llvm::APFloatBase::fcNormal, llvm::First, llvm::detail::DoubleAPFloat::getCategory(), llvm::detail::DoubleAPFloat::getFirst(), llvm::detail::DoubleAPFloat::getSecond(), llvm::harrisonUlp(), llvm::Hi, llvm::APFloatBase::IEK_Inf, llvm::APFloatBase::IEK_NaN, llvm::APFloatBase::IEK_Zero, ilogb(), llvm::APFloat::isNegative(), llvm::detail::DoubleAPFloat::isNegative(), llvm::APFloat::isZero(), llvm::Lo, llvm::APFloat::makeQuiet(), llvm::APFloat::next(), llvm::APFloatBase::PPCDoubleDouble(), llvm::Quiet, rmNearestTiesToAway, rmNearestTiesToEven, rmTowardNegative, rmTowardPositive, rmTowardZero, and scalbn().
frexp() [2/3]
LLVM_ABI DoubleAPFloat llvm::detail::frexp (const DoubleAPFloat & X, int & Exp, roundingMode RM)
Definition at line 5843 of file APFloat.cpp.
References abs(), assert(), llvm::APFloatBase::fcNormal, llvm::First, llvm::detail::DoubleAPFloat::getCategory(), llvm::detail::DoubleAPFloat::getFirst(), llvm::detail::DoubleAPFloat::getSecond(), llvm::harrisonUlp(), llvm::Hi, llvm::APFloatBase::IEK_Inf, llvm::APFloatBase::IEK_NaN, llvm::APFloatBase::IEK_Zero, ilogb(), llvm::APFloat::isNegative(), llvm::detail::DoubleAPFloat::isNegative(), llvm::APFloat::isZero(), llvm::Lo, llvm::APFloat::makeQuiet(), llvm::APFloat::next(), llvm::APFloatBase::PPCDoubleDouble(), llvm::Quiet, rmNearestTiesToAway, rmNearestTiesToEven, rmTowardNegative, rmTowardPositive, rmTowardZero, and scalbn().
frexp() [3/3]
IEEEFloat llvm::detail::frexp (const IEEEFloat & Val, int & Exp, roundingMode RM)
Definition at line 4768 of file APFloat.cpp.
gcd()
SlowDynamicAPInt llvm::detail::gcd (const SlowDynamicAPInt & A, const SlowDynamicAPInt & B)
Definition at line 217 of file SlowDynamicAPInt.cpp.
References A(), assert(), B(), getMaxWidth(), and llvm::APIntOps::GreatestCommonDivisor().
Referenced by lcm().
getAnalysisResult()
template<typename PassT, typename IRUnitT, typename... AnalysisArgTs, typename... MainArgTs> PassT::Result llvm::detail::getAnalysisResult (AnalysisManager< IRUnitT, AnalysisArgTs... > & AM, IRUnitT & IR, std::tuple< MainArgTs... > Args)
Helper for partial unpacking of extra arguments in getAnalysisResult.
Arguments passed in tuple come from PassManager, so they might have extra arguments after those AnalysisManager's ExtraArgTs ones that we need to pass to getResult.
Definition at line 138 of file PassManager.h.
References getAnalysisResultUnpackTuple(), and IR.
Referenced by llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run().
getAnalysisResultUnpackTuple()
template<typename PassT, typename IRUnitT, typename AnalysisManagerT, typename... ArgTs, size_t... Ns> PassT::Result llvm::detail::getAnalysisResultUnpackTuple (AnalysisManagerT & AM, IRUnitT & IR, std::tuple< ArgTs... > Args, std::index_sequence< Ns... >)
Actual unpacker of extra arguments in getAnalysisResult, passes only those tuple arguments that are mentioned in index_sequence.
Definition at line 123 of file PassManager.h.
References IR.
Referenced by getAnalysisResult().
hash_value() [1/3]
hash_code llvm::detail::hash_value (const DoubleAPFloat & Arg)
Definition at line 5338 of file APFloat.cpp.
hash_value() [2/3]
hash_code llvm::detail::hash_value (const IEEEFloat & Arg)
Note that the use of hash codes for floating point values is in general frought with peril. Equality is hard to define for these values. For example, should negative and positive zero hash to different codes? Are they equal or not? This hash value implementation specifically emphasizes producing different codes for different inputs in order to be used in canonicalization and memoization. As such, equality is bitwiseIsEqual, and 0 != -0.
Definition at line 3471 of file APFloat.cpp.
Referenced by llvm::detail::DoubleAPFloat::hash_value, hash_value(), and llvm::hash_value().
hash_value() [3/3]
hash_code llvm::detail::hash_value (const SlowDynamicAPInt & X)
Definition at line 26 of file SlowDynamicAPInt.cpp.
References hash_value(), and X.
ilogb() [1/2]
int llvm::detail::ilogb (const DoubleAPFloat & Arg)
Definition at line 5817 of file APFloat.cpp.
ilogb() [2/2]
int llvm::detail::ilogb (const IEEEFloat & Arg)
Definition at line 4729 of file APFloat.cpp.
Referenced by frexp(), and llvm::detail::DoubleAPFloat::ilogb.
isLegalToHoistInto()
template<class BlockT> bool llvm::detail::isLegalToHoistInto (BlockT * Block)
SFINAE functions that dispatch to the isLegalToHoistInto member function or return false, if it doesn't exist.
Definition at line 194 of file GenericLoopInfoImpl.h.
References llvm::Block.
Referenced by llvm::LoopBase< BlockT, LoopT >::getLoopPreheader().
isPresent()
template<typename T> bool llvm::detail::isPresent (const T & t) inline
Definition at line 623 of file Casting.h.
References llvm::simplify_type< From >::getSimplifiedValue(), isPresent(), and T.
Referenced by llvm::cast_if_present(), llvm::cast_if_present(), llvm::cast_if_present(), llvm::cast_if_present(), llvm::dyn_cast(), llvm::dyn_cast(), llvm::dyn_cast(), llvm::dyn_cast(), llvm::dyn_cast_if_present(), llvm::dyn_cast_if_present(), llvm::dyn_cast_if_present(), llvm::isa_and_present(), and isPresent().
lcm()
SlowDynamicAPInt llvm::detail::lcm (const SlowDynamicAPInt & A, const SlowDynamicAPInt & B)
Returns the least common multiple of A and B.
Definition at line 226 of file SlowDynamicAPInt.cpp.
References A(), abs(), B(), gcd(), X, and Y.
mod()
SlowDynamicAPInt llvm::detail::mod (const SlowDynamicAPInt & LHS, const SlowDynamicAPInt & RHS)
Returns the remainder of dividing LHS by RHS.
is always non-negative.
The RHS is always expected to be positive, and the result is always non-negative.
Definition at line 211 of file SlowDynamicAPInt.cpp.
References assert().
next_or_end()
template<typename Iter> Iter llvm::detail::next_or_end (const Iter & I, const Iter & End)
Definition at line 863 of file STLExtras.h.
References I.
operator!=() [1/4]
template<typename ValueT, typename MapTy, typename ValueInfoT> bool llvm::detail::operator!= (const DenseSetImpl< ValueT, MapTy, ValueInfoT > & LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > & RHS) nodiscard
Inequality comparison for DenseSet.
Equivalent to !(LHS == RHS). See operator== for performance notes.
Definition at line 258 of file DenseSet.h.
References LHS, and RHS.
operator!=() [2/4]
template<typename OtherT, typename DerivedT, typename BaseT, typename T, typename PointerT, typename ReferenceT> bool llvm::detail::operator!= (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > & lhs, const OtherT & rhs)
Definition at line 1333 of file STLExtras.h.
References T.
operator!=() [3/4]
bool llvm::detail::operator!= (const SlowDynamicAPInt & A, int64_t B)
Definition at line 52 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator!=() [4/4]
bool llvm::detail::operator!= (int64_t A, const SlowDynamicAPInt & B)
Definition at line 86 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator%() [1/2]
SlowDynamicAPInt llvm::detail::operator% (const SlowDynamicAPInt & A, int64_t B)
Definition at line 79 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator%() [2/2]
SlowDynamicAPInt llvm::detail::operator% (int64_t A, const SlowDynamicAPInt & B)
Definition at line 113 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator%=()
SlowDynamicAPInt & llvm::detail::operator%= (SlowDynamicAPInt & A, int64_t B)
Definition at line 45 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator*() [1/2]
SlowDynamicAPInt llvm::detail::operator* (const SlowDynamicAPInt & A, int64_t B)
Definition at line 73 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator*() [2/2]
SlowDynamicAPInt llvm::detail::operator* (int64_t A, const SlowDynamicAPInt & B)
Definition at line 107 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator*=()
SlowDynamicAPInt & llvm::detail::operator*= (SlowDynamicAPInt & A, int64_t B)
Definition at line 39 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator+() [1/2]
SlowDynamicAPInt llvm::detail::operator+ (const SlowDynamicAPInt & A, int64_t B)
Definition at line 67 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator+() [2/2]
SlowDynamicAPInt llvm::detail::operator+ (int64_t A, const SlowDynamicAPInt & B)
Definition at line 101 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator+=()
SlowDynamicAPInt & llvm::detail::operator+= (SlowDynamicAPInt & A, int64_t B)
Convenience operator overloads for int64_t.
Convenience operator overloads for int64_t.
Definition at line 33 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator-() [1/2]
SlowDynamicAPInt llvm::detail::operator- (const SlowDynamicAPInt & A, int64_t B)
Definition at line 70 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator-() [2/2]
SlowDynamicAPInt llvm::detail::operator- (int64_t A, const SlowDynamicAPInt & B)
Definition at line 104 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator-=()
SlowDynamicAPInt & llvm::detail::operator-= (SlowDynamicAPInt & A, int64_t B)
Definition at line 36 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator/() [1/2]
SlowDynamicAPInt llvm::detail::operator/ (const SlowDynamicAPInt & A, int64_t B)
Definition at line 76 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator/() [2/2]
SlowDynamicAPInt llvm::detail::operator/ (int64_t A, const SlowDynamicAPInt & B)
Definition at line 110 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator/=()
SlowDynamicAPInt & llvm::detail::operator/= (SlowDynamicAPInt & A, int64_t B)
Definition at line 42 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator<() [1/2]
bool llvm::detail::operator< (const SlowDynamicAPInt & A, int64_t B)
Definition at line 58 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator<() [2/2]
bool llvm::detail::operator< (int64_t A, const SlowDynamicAPInt & B)
Definition at line 92 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator<<()
raw_ostream & llvm::detail::operator<< (raw_ostream & OS, const SlowDynamicAPInt & X) inline
Definition at line 89 of file SlowDynamicAPInt.h.
References X.
operator<=() [1/2]
bool llvm::detail::operator<= (const SlowDynamicAPInt & A, int64_t B)
Definition at line 61 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator<=() [2/2]
bool llvm::detail::operator<= (int64_t A, const SlowDynamicAPInt & B)
Definition at line 95 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator==() [1/4]
template<typename ValueT, typename MapTy, typename ValueInfoT> bool llvm::detail::operator== (const DenseSetImpl< ValueT, MapTy, ValueInfoT > & LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > & RHS) nodiscard
Equality comparison for DenseSet.
Iterates over elements of LHS confirming that each element is also a member of RHS, and that RHS contains no additional values. Equivalent to N calls to RHS.count. Amortized complexity is linear, worst case is O(N^2) (if every hash collides).
Definition at line 241 of file DenseSet.h.
References E(), LHS, and RHS.
operator==() [2/4]
template<typename OtherT, typename DerivedT, typename BaseT, typename T, typename PointerT, typename ReferenceT> bool llvm::detail::operator== (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > & lhs, const OtherT & rhs)
Compare this range with another.
FIXME: Make me a member function instead of friend when it works in C++20.
Definition at line 1325 of file STLExtras.h.
References T.
operator==() [3/4]
bool llvm::detail::operator== (const SlowDynamicAPInt & A, int64_t B)
Definition at line 49 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator==() [4/4]
bool llvm::detail::operator== (int64_t A, const SlowDynamicAPInt & B)
Definition at line 83 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator>() [1/2]
bool llvm::detail::operator> (const SlowDynamicAPInt & A, int64_t B)
Definition at line 55 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator>() [2/2]
bool llvm::detail::operator> (int64_t A, const SlowDynamicAPInt & B)
Definition at line 89 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator>=() [1/2]
bool llvm::detail::operator>= (const SlowDynamicAPInt & A, int64_t B)
Definition at line 64 of file SlowDynamicAPInt.cpp.
References A(), and B().
operator>=() [2/2]
bool llvm::detail::operator>= (int64_t A, const SlowDynamicAPInt & B)
Definition at line 98 of file SlowDynamicAPInt.cpp.
References A(), and B().
printBumpPtrAllocatorStats()
void llvm::detail::printBumpPtrAllocatorStats (unsigned NumSlabs, size_t BytesAllocated, size_t TotalMemory)
Definition at line 20 of file Allocator.cpp.
References llvm::errs().
Referenced by llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::PrintStats().
PrintTo() [1/2]
void llvm::detail::PrintTo (const ErrorHolder & Err, std::ostream * Out) inline
Definition at line 38 of file SupportHelpers.h.
References Info.
Referenced by PrintTo().
PrintTo() [2/2]
template<typename T> void llvm::detail::PrintTo (const ExpectedHolder< T > & Item, std::ostream * Out)
Definition at line 53 of file SupportHelpers.h.
References llvm::detail::ExpectedHolder< T >::Exp, PrintTo(), and llvm::detail::ErrorHolder::Success().
resolveReferencedType() [1/2]
template<typename DieType> DieType llvm::detail::resolveReferencedType (DieType D, dwarf::Attribute Attr = dwarf::DW_AT_type)
Definition at line 152 of file DWARFTypePrinter.h.
References D().
Referenced by llvm::DWARFTypePrinter< DieType >::appendConstVolatileQualifierAfter(), llvm::DWARFTypePrinter< DieType >::appendConstVolatileQualifierBefore(), llvm::DWARFTypePrinter< DieType >::appendSubroutineNameAfter(), llvm::DWARFTypePrinter< DieType >::appendTemplateParameters(), llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameAfter(), llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameBefore(), llvm::DWARFTypePrinter< DieType >::decomposeConstVolatile(), llvm::DWARFTypePrinter< DieType >::skipQualifiers(), and unwrapReferencedTypedefType().
resolveReferencedType() [2/2]
template<typename DieType> DieType llvm::detail::resolveReferencedType (DieType D, typename DieType::DWARFFormValue F)
Definition at line 157 of file DWARFTypePrinter.h.
References D(), and F.
reverse_if()
template<bool B, typename Range> auto llvm::detail::reverse_if (Range && R)
Definition at line 45 of file CFGDiff.h.
References Range, and reverse_if_helper().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), and llvm::GraphDiff< MachineBasicBlock *, false >::getChildren().
reverse_if_helper() [1/2]
template<typename Range> auto llvm::detail::reverse_if_helper (Range && R, std::bool_constant< false >)
Definition at line 36 of file CFGDiff.h.
References Range.
Referenced by reverse_if().
reverse_if_helper() [2/2]
template<typename Range> auto llvm::detail::reverse_if_helper (Range && R, std::bool_constant< true >)
Definition at line 41 of file CFGDiff.h.
References Range, and llvm::reverse().
scalbn() [1/3]
DoubleAPFloat llvm::detail::scalbn (const DoubleAPFloat & Arg, int Exp, APFloat::roundingMode RM)
Definition at line 5834 of file APFloat.cpp.
References assert(), llvm::APFloatBase::PPCDoubleDouble(), and scalbn().
scalbn() [2/3]
LLVM_ABI DoubleAPFloat llvm::detail::scalbn (const DoubleAPFloat & Arg, int Exp, roundingMode RM)
Definition at line 5834 of file APFloat.cpp.
References assert(), llvm::APFloatBase::PPCDoubleDouble(), and scalbn().
scalbn() [3/3]
IEEEFloat llvm::detail::scalbn (IEEEFloat X, int Exp, roundingMode RoundingMode)
Definition at line 4747 of file APFloat.cpp.
Referenced by frexp(), and scalbn().
set_intersects_impl()
template<class S1Ty, class S2Ty> bool llvm::detail::set_intersects_impl (const S1Ty & S1, const S2Ty & S2)
Definition at line 163 of file SetOperations.h.
References E(), and S1.
Referenced by llvm::set_intersects().
TakeError()
llvm::detail::ErrorHolder llvm::detail::TakeError (llvm::Error Err)
Definition at line 13 of file Error.cpp.
References llvm::handleAllErrors().
Referenced by TakeExpected().
TakeExpected() [1/2]
template<typename T> ExpectedHolder< T > llvm::detail::TakeExpected (Expected< T > && Exp)
Definition at line 26 of file Error.h.
References TakeExpected().
TakeExpected() [2/2]
template<typename T> ExpectedHolder< T > llvm::detail::TakeExpected (Expected< T > & Exp)
Definition at line 22 of file Error.h.
References TakeError().
Referenced by TakeExpected().
tcSetLeastSignificantBits()
void llvm::detail::tcSetLeastSignificantBits (APInt::WordType * dst, unsigned parts, unsigned bits) static
Definition at line 1566 of file APFloat.cpp.
References llvm::APInt::APINT_BITS_PER_WORD.
Referenced by llvm::detail::DoubleAPFloat::convertToInteger(), and llvm::detail::IEEEFloat::convertToInteger().
toString()
template<typename DWARFFormValueType> const char * llvm::detail::toString (std::optional< DWARFFormValueType > F)
Definition at line 161 of file DWARFTypePrinter.h.
References llvm::consumeError(), E(), and F.
Referenced by llvm::DWARFTypePrinter< DieType >::appendTemplateParameters(), and llvm::DWARFTypePrinter< DieType >::appendUnqualifiedNameBefore().
unwrapReferencedTypedefType()
template<typename DieType> DieType llvm::detail::unwrapReferencedTypedefType (DieType D)
Resolve the DW_AT_type of D until we reach a DIE that is not a DW_TAG_typedef.
Definition at line 173 of file DWARFTypePrinter.h.
References D(), resolveReferencedType(), TypeAttr, and unwrapReferencedTypedefType().
Referenced by llvm::DWARFTypePrinter< DieType >::appendTemplateParameters(), and unwrapReferencedTypedefType().
unwrapValue()
template<typename T> decltype(auto) llvm::detail::unwrapValue (T & t) inline
Definition at line 629 of file Casting.h.
References T, and llvm::ValueIsPresent< T, Enable >::unwrapValue().
Referenced by llvm::cast_if_present(), llvm::cast_if_present(), llvm::cast_if_present(), llvm::dyn_cast_if_present(), llvm::dyn_cast_if_present(), and llvm::dyn_cast_if_present().
Variable Documentation
cmpEqual
cmpResult llvm::detail::cmpEqual = APFloatBase::cmpEqual static constexpr
Definition at line 430 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::compare(), llvm::detail::DoubleAPFloat::compareAbsoluteValue(), llvm::detail::IEEEFloat::compareAbsoluteValue(), llvm::detail::IEEEFloat::isInteger(), llvm::detail::DoubleAPFloat::isLargest(), llvm::detail::DoubleAPFloat::isSmallest(), llvm::detail::DoubleAPFloat::isSmallestNormalized(), and llvm::detail::IEEEFloat::remainder().
cmpGreaterThan
cmpResult llvm::detail::cmpGreaterThan = APFloatBase::cmpGreaterThan static constexpr
Definition at line 432 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::compare(), llvm::detail::DoubleAPFloat::compareAbsoluteValue(), llvm::detail::IEEEFloat::compareAbsoluteValue(), llvm::detail::DoubleAPFloat::next(), and llvm::detail::IEEEFloat::remainder().
cmpLessThan
cmpResult llvm::detail::cmpLessThan = APFloatBase::cmpLessThan static constexpr
Definition at line 431 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::compare(), llvm::detail::DoubleAPFloat::compareAbsoluteValue(), llvm::detail::IEEEFloat::compareAbsoluteValue(), and llvm::detail::IEEEFloat::mod().
cmpUnordered
cmpResult llvm::detail::cmpUnordered = APFloatBase::cmpUnordered static constexpr
Definition at line 433 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::compare().
fcInfinity
fltCategory llvm::detail::fcInfinity = APFloatBase::fcInfinity static constexpr
Definition at line 440 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::bitwiseIsEqual(), llvm::detail::IEEEFloat::compare(), llvm::detail::IEEEFloat::convert(), llvm::detail::IEEEFloat::convertToHexString(), llvm::detail::IEEEFloat::isInfinity(), llvm::detail::IEEEFloat::makeInf(), llvm::detail::DoubleAPFloat::multiply(), llvm::detail::DoubleAPFloat::next(), llvm::detail::IEEEFloat::next(), and llvm::detail::IEEEFloat::toString().
fcNaN
fltCategory llvm::detail::fcNaN = APFloatBase::fcNaN static constexpr
Definition at line 441 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::compare(), llvm::detail::IEEEFloat::convert(), llvm::detail::IEEEFloat::convertToHexString(), llvm::detail::DoubleAPFloat::convertToInteger(), llvm::detail::IEEEFloat::convertToInteger(), llvm::detail::IEEEFloat::isNaN(), llvm::detail::IEEEFloat::makeNaN(), llvm::detail::DoubleAPFloat::multiply(), llvm::detail::DoubleAPFloat::next(), llvm::detail::IEEEFloat::next(), and llvm::detail::IEEEFloat::toString().
fcNormal
fltCategory llvm::detail::fcNormal = APFloatBase::fcNormal static constexpr
Definition at line 442 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::compare(), llvm::detail::IEEEFloat::convertToHexString(), llvm::detail::IEEEFloat::IEEEFloat(), llvm::detail::DoubleAPFloat::ilogb, llvm::detail::DoubleAPFloat::isDenormal(), llvm::detail::DoubleAPFloat::isLargest(), llvm::detail::DoubleAPFloat::isSmallest(), llvm::detail::DoubleAPFloat::isSmallestNormalized(), llvm::detail::IEEEFloat::isSmallestNormalized(), llvm::detail::IEEEFloat::makeLargest(), llvm::detail::IEEEFloat::makeSmallest(), llvm::detail::IEEEFloat::makeSmallestNormalized(), llvm::detail::DoubleAPFloat::multiply(), llvm::detail::DoubleAPFloat::next(), llvm::detail::IEEEFloat::next(), and llvm::detail::IEEEFloat::toString().
fcZero
fltCategory llvm::detail::fcZero = APFloatBase::fcZero static constexpr
Definition at line 443 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::bitwiseIsEqual(), llvm::detail::IEEEFloat::compare(), llvm::detail::IEEEFloat::convert(), llvm::detail::IEEEFloat::convertToHexString(), llvm::detail::IEEEFloat::fusedMultiplyAdd(), llvm::detail::IEEEFloat::makeZero(), llvm::detail::DoubleAPFloat::multiply(), llvm::detail::DoubleAPFloat::next(), llvm::detail::IEEEFloat::next(), and llvm::detail::IEEEFloat::toString().
HasFreeFunctionRBegin
template<typename Range> bool llvm::detail::HasFreeFunctionRBegin static constexpr
Initial value:
                                        =
is_detected<check_has_free_function_rbegin, Range>::value
Definition at line 400 of file STLExtras.h.
Referenced by llvm::reverse().
HasFreeFunctionSize
template<typename Range> bool llvm::detail::HasFreeFunctionSize static constexpr
Initial value:
                                      =
is_detected<check_has_free_function_size, Range>::value
Definition at line 1682 of file STLExtras.h.
Referenced by llvm::range_size().
HasMemberContains
template<typename Range, typename Element> bool llvm::detail::HasMemberContains static constexpr
Initial value:
                                    =
is_detected<check_has_member_contains_t, Range, Element>::value
Definition at line 1925 of file STLExtras.h.
Referenced by llvm::is_contained(), and llvm::set_subtract().
HasMemberEraseIter
template<typename Set> bool llvm::detail::HasMemberEraseIter static constexpr
Initial value:
                                     =
is_detected<check_has_member_erase_iter_t, Set>::value
Definition at line 36 of file SetOperations.h.
Referenced by llvm::set_subtract().
HasMemberFind
template<typename Range, typename Element> bool llvm::detail::HasMemberFind static constexpr
Initial value:
                                =
is_detected<check_has_member_find_t, Range, Element>::value
Definition at line 1934 of file STLExtras.h.
Referenced by llvm::is_contained().
HasMemberRemoveIf
template<typename Set, typename Fn> bool llvm::detail::HasMemberRemoveIf static constexpr
Initial value:
                                    =
is_detected<check_has_member_remove_if_t, Set, Fn>::value
Definition at line 28 of file SetOperations.h.
Referenced by llvm::set_intersect(), and llvm::set_subtract().
integerPartWidth
unsigned llvm::detail::integerPartWidth = APFloatBase::integerPartWidth static constexpr
Definition at line 429 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::makeLargest().
opDivByZero
opStatus llvm::detail::opDivByZero = APFloatBase::opDivByZero static constexpr
Definition at line 436 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::remainder().
opInexact
opStatus llvm::detail::opInexact = APFloatBase::opInexact static constexpr
Definition at line 439 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::convert(), llvm::detail::IEEEFloat::divide(), llvm::detail::IEEEFloat::fusedMultiplyAdd(), and llvm::detail::IEEEFloat::multiply().
opInvalidOp
opStatus llvm::detail::opInvalidOp = APFloatBase::opInvalidOp static constexpr
Definition at line 435 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::convert(), llvm::detail::DoubleAPFloat::convertToInteger(), llvm::detail::IEEEFloat::convertToInteger(), llvm::detail::DoubleAPFloat::next(), llvm::detail::IEEEFloat::next(), and llvm::detail::IEEEFloat::roundToIntegral().
opOK
opStatus llvm::detail::opOK = APFloatBase::opOK static constexpr
Definition at line 434 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::convert(), llvm::detail::IEEEFloat::convertFromString(), llvm::detail::IEEEFloat::fusedMultiplyAdd(), llvm::detail::IEEEFloat::mod(), llvm::detail::DoubleAPFloat::multiply(), llvm::detail::DoubleAPFloat::next(), llvm::detail::IEEEFloat::next(), llvm::detail::IEEEFloat::remainder(), and llvm::detail::IEEEFloat::roundToIntegral().
opOverflow
opStatus llvm::detail::opOverflow = APFloatBase::opOverflow static constexpr
Definition at line 437 of file APFloat.h.
opUnderflow
opStatus llvm::detail::opUnderflow = APFloatBase::opUnderflow static constexpr
Definition at line 438 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::fusedMultiplyAdd().
rmNearestTiesToAway
roundingMode llvm::detail::rmNearestTiesToAway static constexpr
Initial value:
                                              =
APFloatBase::rmNearestTiesToAway
Definition at line 424 of file APFloat.h.
Referenced by frexp(), and llvm::detail::DoubleAPFloat::roundToIntegral().
rmNearestTiesToEven
roundingMode llvm::detail::rmNearestTiesToEven static constexpr
Initial value:
                                              =
APFloatBase::rmNearestTiesToEven
Definition at line 422 of file APFloat.h.
Referenced by frexp(), llvm::detail::IEEEFloat::IEEEFloat(), llvm::detail::IEEEFloat::mod(), llvm::detail::IEEEFloat::remainder(), llvm::detail::DoubleAPFloat::roundToIntegral(), and llvm::detail::IEEEFloat::roundToIntegral().
rmTowardNegative
roundingMode llvm::detail::rmTowardNegative = APFloatBase::rmTowardNegative static constexpr
Definition at line 426 of file APFloat.h.
Referenced by frexp(), llvm::detail::IEEEFloat::fusedMultiplyAdd(), and llvm::detail::DoubleAPFloat::roundToIntegral().
rmTowardPositive
roundingMode llvm::detail::rmTowardPositive = APFloatBase::rmTowardPositive static constexpr
Definition at line 427 of file APFloat.h.
Referenced by frexp(), and llvm::detail::DoubleAPFloat::roundToIntegral().
rmTowardZero
roundingMode llvm::detail::rmTowardZero = APFloatBase::rmTowardZero static constexpr
Definition at line 428 of file APFloat.h.
Referenced by frexp(), llvm::detail::IEEEFloat::isInteger(), llvm::detail::DoubleAPFloat::next(), and llvm::detail::DoubleAPFloat::roundToIntegral().
uninitialized
uninitializedTag llvm::detail::uninitialized = APFloatBase::uninitialized static constexpr
Definition at line 421 of file APFloat.h.
Referenced by llvm::detail::DoubleAPFloat::DoubleAPFloat(), and llvm::detail::DoubleAPFloat::next().
unit< Period >::value
template<typename Period> const char llvm::detail::unit< Period >::value[] = ""
Definition at line 104 of file Chrono.h.
Referenced by all_of_zip_predicate_last(), and llvm::detail::IEEEFloat::IEEEFloat().