LLVM: llvm::AArch64BuildAttributes Namespace Reference
llvm::AArch64BuildAttributes Namespace Reference
Enumerations
enum VendorID : unsigned { AEABI_FEATURE_AND_BITS = 0 , AEABI_PAUTHABI = 1 , VENDOR_UNKNOWN = 404 }
AArch64 build attributes vendors IDs (a.k.a subsection name).
enum SubsectionOptional : unsigned { REQUIRED = 0 , OPTIONAL = 1 , OPTIONAL_NOT_FOUND = 404 }
enum SubsectionType : unsigned { ULEB128 = 0 , NTBS = 1 , TYPE_NOT_FOUND = 404 }
enum PauthABITags : unsigned { TAG_PAUTH_PLATFORM = 1 , TAG_PAUTH_SCHEMA = 2 , PAUTHABI_TAG_NOT_FOUND = 404 }
enum FeatureAndBitsTags : unsigned { TAG_FEATURE_BTI = 0 , TAG_FEATURE_PAC = 1 , TAG_FEATURE_GCS = 2 , FEATURE_AND_BITS_TAG_NOT_FOUND = 404 }
enum FeatureAndBitsFlag : unsigned { Feature_BTI_Flag = 1 << 0 , Feature_PAC_Flag = 1 << 1 , Feature_GCS_Flag = 1 << 2 }
Functions
StringRef getVendorName (unsigned const Vendor)
VendorID getVendorID (StringRef const Vendor)
StringRef getOptionalStr (unsigned Optional)
SubsectionOptional getOptionalID (StringRef Optional)
StringRef getSubsectionOptionalUnknownError ()
StringRef getTypeStr (unsigned Type)
SubsectionType getTypeID (StringRef Type)
StringRef getSubsectionTypeUnknownError ()
StringRef getPauthABITagsStr (unsigned PauthABITag)
PauthABITags getPauthABITagsID (StringRef PauthABITag)
StringRef getFeatureAndBitsTagsStr (unsigned FeatureAndBitsTag)
FeatureAndBitsTags getFeatureAndBitsTagsID (StringRef FeatureAndBitsTag)
Enumeration Type Documentation
FeatureAndBitsFlag
enum llvm::AArch64BuildAttributes::FeatureAndBitsFlag : unsigned
Enumerator
Feature_BTI_Flag
Feature_PAC_Flag
Feature_GCS_Flag
Definition at line 67 of file AArch64BuildAttributes.h.
FeatureAndBitsTags
enum llvm::AArch64BuildAttributes::FeatureAndBitsTags : unsigned
Enumerator
TAG_FEATURE_BTI
TAG_FEATURE_PAC
TAG_FEATURE_GCS
FEATURE_AND_BITS_TAG_NOT_FOUND
Definition at line 58 of file AArch64BuildAttributes.h.
PauthABITags
enum llvm::AArch64BuildAttributes::PauthABITags : unsigned
Enumerator
TAG_PAUTH_PLATFORM
TAG_PAUTH_SCHEMA
PAUTHABI_TAG_NOT_FOUND
Definition at line 50 of file AArch64BuildAttributes.h.
SubsectionOptional
enum llvm::AArch64BuildAttributes::SubsectionOptional : unsigned
Enumerator
REQUIRED
OPTIONAL
OPTIONAL_NOT_FOUND
Definition at line 36 of file AArch64BuildAttributes.h.
SubsectionType
enum llvm::AArch64BuildAttributes::SubsectionType : unsigned
Enumerator
ULEB128
NTBS
TYPE_NOT_FOUND
Definition at line 45 of file AArch64BuildAttributes.h.
VendorID
enum llvm::AArch64BuildAttributes::VendorID : unsigned
AArch64 build attributes vendors IDs (a.k.a subsection name).
Enumerator
AEABI_FEATURE_AND_BITS
AEABI_PAUTHABI
VENDOR_UNKNOWN
Definition at line 28 of file AArch64BuildAttributes.h.
Function Documentation
getFeatureAndBitsTagsID()
FeatureAndBitsTags llvm::AArch64BuildAttributes::getFeatureAndBitsTagsID (StringRef FeatureAndBitsTag)
Definition at line 113 of file AArch64BuildAttributes.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), FEATURE_AND_BITS_TAG_NOT_FOUND, TAG_FEATURE_BTI, TAG_FEATURE_GCS, and TAG_FEATURE_PAC.
getFeatureAndBitsTagsStr()
StringRef llvm::AArch64BuildAttributes::getFeatureAndBitsTagsStr (unsigned FeatureAndBitsTag)
Definition at line 98 of file AArch64BuildAttributes.cpp.
References FEATURE_AND_BITS_TAG_NOT_FOUND, TAG_FEATURE_BTI, TAG_FEATURE_GCS, and TAG_FEATURE_PAC.
getOptionalID()
SubsectionOptional llvm::AArch64BuildAttributes::getOptionalID (StringRef Optional)
Definition at line 46 of file AArch64BuildAttributes.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), OPTIONAL, OPTIONAL_NOT_FOUND, and REQUIRED.
getOptionalStr()
StringRef llvm::AArch64BuildAttributes::getOptionalStr (unsigned Optional)
Definition at line 35 of file AArch64BuildAttributes.cpp.
References OPTIONAL, OPTIONAL_NOT_FOUND, and REQUIRED.
getPauthABITagsID()
PauthABITags llvm::AArch64BuildAttributes::getPauthABITagsID (StringRef PauthABITag)
Definition at line 90 of file AArch64BuildAttributes.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), PAUTHABI_TAG_NOT_FOUND, TAG_PAUTH_PLATFORM, and TAG_PAUTH_SCHEMA.
getPauthABITagsStr()
StringRef llvm::AArch64BuildAttributes::getPauthABITagsStr (unsigned PauthABITag)
Definition at line 78 of file AArch64BuildAttributes.cpp.
References PAUTHABI_TAG_NOT_FOUND, TAG_PAUTH_PLATFORM, and TAG_PAUTH_SCHEMA.
getSubsectionOptionalUnknownError()
StringRef llvm::AArch64BuildAttributes::getSubsectionOptionalUnknownError ()
Definition at line 52 of file AArch64BuildAttributes.cpp.
getSubsectionTypeUnknownError()
StringRef llvm::AArch64BuildAttributes::getSubsectionTypeUnknownError ()
Definition at line 74 of file AArch64BuildAttributes.cpp.
getTypeID()
SubsectionType llvm::AArch64BuildAttributes::getTypeID (StringRef Type)
Definition at line 68 of file AArch64BuildAttributes.cpp.
References llvm::StringSwitch< T, R >::Cases(), Default, NTBS, TYPE_NOT_FOUND, and ULEB128.
getTypeStr()
StringRef llvm::AArch64BuildAttributes::getTypeStr (unsigned Type)
Definition at line 57 of file AArch64BuildAttributes.cpp.
References NTBS, TYPE_NOT_FOUND, and ULEB128.
getVendorID()
VendorID llvm::AArch64BuildAttributes::getVendorID (StringRef const Vendor)
Definition at line 28 of file AArch64BuildAttributes.cpp.
References AEABI_FEATURE_AND_BITS, AEABI_PAUTHABI, llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and VENDOR_UNKNOWN.
getVendorName()
StringRef llvm::AArch64BuildAttributes::getVendorName (unsigned const Vendor)
Definition at line 15 of file AArch64BuildAttributes.cpp.
References AEABI_FEATURE_AND_BITS, AEABI_PAUTHABI, assert(), and VENDOR_UNKNOWN.