LLVM: llvm::orc::rt_bootstrap Namespace Reference
llvm::orc::rt_bootstrap Namespace Reference
Classes
class ExecutorSharedMemoryMapperService
class SimpleExecutorDylibManager
Simple page-based allocator.
class SimpleExecutorMemoryManager
Simple page-based allocator.
Functions
template<typename WriteT, typename SPSWriteT>
static llvm::orc::shared::CWrapperFunctionBuffer writeUIntsWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer writePointersWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer writeBuffersWrapper (const char *ArgData, size_t ArgSize)
template<typename ReadT>
static llvm::orc::shared::CWrapperFunctionBuffer readUIntsWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer readPointersWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer readBuffersWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer readStringsWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer runAsMainWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer runAsVoidFunctionWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionBuffer runAsIntFunctionWrapper (const char *ArgData, size_t ArgSize)
void addTo (StringMap< ExecutorAddr > &M)
Function Documentation
addTo()
void llvm::orc::rt_bootstrap::addTo (StringMap< ExecutorAddr > & M)
Definition at line 158 of file OrcRTBootstrap.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::orc::rt::MemoryReadBuffersWrapperName, llvm::orc::rt::MemoryReadPointersWrapperName, llvm::orc::rt::MemoryReadStringsWrapperName, llvm::orc::rt::MemoryReadUInt16sWrapperName, llvm::orc::rt::MemoryReadUInt32sWrapperName, llvm::orc::rt::MemoryReadUInt64sWrapperName, llvm::orc::rt::MemoryReadUInt8sWrapperName, llvm::orc::rt::MemoryWriteBuffersWrapperName, llvm::orc::rt::MemoryWritePointersWrapperName, llvm::orc::rt::MemoryWriteUInt16sWrapperName, llvm::orc::rt::MemoryWriteUInt32sWrapperName, llvm::orc::rt::MemoryWriteUInt64sWrapperName, llvm::orc::rt::MemoryWriteUInt8sWrapperName, readBuffersWrapper(), readPointersWrapper(), readStringsWrapper(), readUIntsWrapper(), runAsIntFunctionWrapper(), llvm::orc::rt::RunAsIntFunctionWrapperName, runAsMainWrapper(), llvm::orc::rt::RunAsMainWrapperName, runAsVoidFunctionWrapper(), llvm::orc::rt::RunAsVoidFunctionWrapperName, writeBuffersWrapper(), writePointersWrapper(), and writeUIntsWrapper().
Referenced by llvm::orc::SimpleRemoteEPCServer::defaultBootstrapSymbols().
readBuffersWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::readBuffersWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 92 of file OrcRTBootstrap.cpp.
References llvm::release, and llvm::orc::Result.
Referenced by addTo().
readPointersWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::readPointersWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 77 of file OrcRTBootstrap.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::release, and llvm::orc::Result.
Referenced by addTo().
readStringsWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::readStringsWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 112 of file OrcRTBootstrap.cpp.
References llvm::release, and llvm::orc::Result.
Referenced by addTo().
readUIntsWrapper()
template<typename ReadT> llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::readUIntsWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 62 of file OrcRTBootstrap.cpp.
References llvm::release, and llvm::orc::Result.
Referenced by addTo().
runAsIntFunctionWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::runAsIntFunctionWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 148 of file OrcRTBootstrap.cpp.
References llvm::release, llvm::orc::runAsIntFunction(), and llvm::orc::ExecutorAddr::toPtr().
Referenced by addTo().
runAsMainWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::runAsMainWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 127 of file OrcRTBootstrap.cpp.
References llvm::release, llvm::orc::runAsMain(), and llvm::orc::ExecutorAddr::toPtr().
Referenced by addTo().
runAsVoidFunctionWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::runAsVoidFunctionWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 138 of file OrcRTBootstrap.cpp.
References llvm::release, llvm::orc::runAsVoidFunction(), and llvm::orc::ExecutorAddr::toPtr().
Referenced by addTo().
writeBuffersWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::writeBuffersWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 49 of file OrcRTBootstrap.cpp.
References llvm::release.
Referenced by addTo().
writePointersWrapper()
llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::writePointersWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 37 of file OrcRTBootstrap.cpp.
References llvm::release.
Referenced by addTo().
writeUIntsWrapper()
template<typename WriteT, typename SPSWriteT> llvm::orc::shared::CWrapperFunctionBuffer llvm::orc::rt_bootstrap::writeUIntsWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 26 of file OrcRTBootstrap.cpp.
References llvm::release.
Referenced by addTo().