LLVM: llvm::sys::fs::detail Namespace Reference
llvm::sys::fs::detail Namespace Reference
Classes
struct DirIterState
Keeps state for the directory_iterator.
struct RecDirIterState
Keeps state for the recursive_directory_iterator.
Functions
LLVM_ABI std::error_code directory_iterator_construct (DirIterState &, StringRef, bool)
LLVM_ABI std::error_code directory_iterator_increment (DirIterState &)
LLVM_ABI std::error_code directory_iterator_destruct (DirIterState &)
Function Documentation
directory_iterator_construct()
LLVM_ABI std::error_code llvm::sys::fs::detail::directory_iterator_construct (DirIterState & , StringRef , bool)
References LLVM_ABI.
Referenced by llvm::sys::fs::directory_iterator::directory_iterator(), and llvm::sys::fs::directory_iterator::directory_iterator().
directory_iterator_destruct()
LLVM_ABI std::error_code llvm::sys::fs::detail::directory_iterator_destruct (DirIterState &)
References LLVM_ABI.
Referenced by llvm::sys::fs::detail::DirIterState::~DirIterState().
directory_iterator_increment()
LLVM_ABI std::error_code llvm::sys::fs::detail::directory_iterator_increment (DirIterState &)
References LLVM_ABI.