LLVM: lib/Target/NVPTX/NVPTXRegisterInfo.cpp File Reference
NVPTXRegisterInfo.cpp File Reference
#include "NVPTXRegisterInfo.h"
#include "MCTargetDesc/NVPTXInstPrinter.h"
#include "NVPTX.h"
#include "NVPTXTargetMachine.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "NVPTXGenRegisterInfo.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "nvptx-reg-info"
#define GET_REGINFO_TARGET_DESC
Functions
StringRef llvm::getNVPTXRegClassName (TargetRegisterClass const *RC)
StringRef llvm::getNVPTXRegClassStr (TargetRegisterClass const *RC)
static uint64_t encodeRegisterForDwarf (StringRef RegisterName)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-reg-info"
Definition at line 24 of file NVPTXRegisterInfo.cpp.
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 81 of file NVPTXRegisterInfo.cpp.
Function Documentation
encodeRegisterForDwarf()
uint64_t encodeRegisterForDwarf (StringRef RegisterName) static
Definition at line 144 of file NVPTXRegisterInfo.cpp.
References llvm::StringRef::size().
Referenced by llvm::NVPTXRegisterInfo::addToDebugRegisterMap(), and llvm::NVPTXRegisterInfo::getDwarfRegNum().