LLVM: lib/Target/NVPTX/NVPTXProxyRegErasure.cpp File Reference
NVPTXProxyRegErasure.cpp File Reference
#include "NVPTX.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
Functions
INITIALIZE_PASS (NVPTXProxyRegErasure, "nvptx-proxyreg-erasure", "NVPTX ProxyReg Erasure", false, false) bool NVPTXProxyRegErasure
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (NVPTXProxyRegErasure , "nvptx-proxyreg-erasure" , "NVPTX ProxyReg Erasure" , false , false)
Definition at line 48 of file NVPTXProxyRegErasure.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), for(), MI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().