LLVM: lib/Target/NVPTX/MCTargetDesc/NVPTXMCTargetDesc.cpp File Reference
NVPTXMCTargetDesc.cpp File Reference
#include "NVPTXMCTargetDesc.h"
#include "NVPTXInstPrinter.h"
#include "NVPTXMCAsmInfo.h"
#include "NVPTXTargetStreamer.h"
#include "TargetInfo/NVPTXTargetInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "NVPTXGenInstrInfo.inc"
#include "NVPTXGenSubtargetInfo.inc"
#include "NVPTXGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createNVPTXMCInstrInfo ()
static MCRegisterInfo * createNVPTXMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createNVPTXMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createNVPTXMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &, MCInstPrinter *)
static MCTargetStreamer * createNullTargetStreamer (MCStreamer &S)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeNVPTXTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 27 of file NVPTXMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 26 of file NVPTXMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 33 of file NVPTXMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 30 of file NVPTXMCTargetDesc.cpp.
Function Documentation
createNullTargetStreamer()
MCTargetStreamer * createNullTargetStreamer (MCStreamer & S) static
Definition at line 70 of file NVPTXMCTargetDesc.cpp.
Referenced by LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetMC(), LLVMInitializeSparcTargetMC(), LLVMInitializeSystemZTargetMC(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyTargetMC(), and LLVMInitializeXCoreTargetMC().
createNVPTXMCInstPrinter()
MCInstPrinter * createNVPTXMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 54 of file NVPTXMCTargetDesc.cpp.
References MRI, and T.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCInstrInfo()
MCInstrInfo * createNVPTXMCInstrInfo () static
Definition at line 36 of file NVPTXMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCRegisterInfo()
MCRegisterInfo * createNVPTXMCRegisterInfo (const Triple & TT) static
Definition at line 42 of file NVPTXMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCSubtargetInfo()
MCSubtargetInfo * createNVPTXMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 50 of file NVPTXMCTargetDesc.cpp.
Referenced by LLVMInitializeNVPTXTargetMC().
createTargetAsmStreamer()
MCTargetStreamer * createTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & , MCInstPrinter *) static
Definition at line 64 of file NVPTXMCTargetDesc.cpp.
LLVMInitializeNVPTXTargetMC()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeNVPTXTargetMC ()
Definition at line 76 of file NVPTXMCTargetDesc.cpp.
References createNullTargetStreamer(), createNVPTXMCInstPrinter(), createNVPTXMCInstrInfo(), createNVPTXMCRegisterInfo(), createNVPTXMCSubtargetInfo(), createTargetAsmStreamer(), llvm::getTheNVPTXTarget32(), llvm::getTheNVPTXTarget64(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), T, and X.