LLVM: lib/Target/NVPTX/NVPTXForwardParams.cpp File Reference
NVPTXForwardParams.cpp File Reference
#include "NVPTX.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static bool traverseMoveUse (MachineInstr &U, const MachineRegisterInfo &MRI, SmallVectorImpl< MachineInstr * > &RemoveList, SmallVectorImpl< MachineInstr * > &LoadInsts)
static bool eliminateMove (MachineInstr &Mov, const MachineRegisterInfo &MRI, SmallVectorImpl< MachineInstr * > &RemoveList)
static bool forwardDeviceParams (MachineFunction &MF)
INITIALIZE_PASS (NVPTXForwardParamsPass, "nvptx-forward-params", "NVPTX Forward Params", false, false) bool NVPTXForwardParamsPass
Function Documentation
eliminateMove()
bool eliminateMove (MachineInstr & Mov, const MachineRegisterInfo & MRI, SmallVectorImpl< MachineInstr * > & RemoveList) static
Definition at line 84 of file NVPTXForwardParams.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::begin(), llvm::iterator_range< IteratorT >::begin(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::isSymbol(), MRI, llvm::MachineInstr::operands_begin(), llvm::NVPTX::Param, llvm::SmallVectorTemplateBase< T, bool >::push_back(), traverseMoveUse(), and llvm::MachineInstr::uses().
Referenced by forwardDeviceParams().
forwardDeviceParams()
bool forwardDeviceParams (MachineFunction & MF) static
Definition at line 110 of file NVPTXForwardParams.cpp.
References llvm::MachineFunction::begin(), eliminateMove(), llvm::MachineFunction::getRegInfo(), llvm::make_early_inc_range(), MI, and MRI.
Referenced by INITIALIZE_PASS().
INITIALIZE_PASS()
INITIALIZE_PASS (NVPTXForwardParamsPass , "nvptx-forward-params" , "NVPTX Forward Params" , false , false)
Definition at line 145 of file NVPTXForwardParams.cpp.
References forwardDeviceParams().
traverseMoveUse()
bool traverseMoveUse (MachineInstr & U, const MachineRegisterInfo & MRI, SmallVectorImpl< MachineInstr * > & RemoveList, SmallVectorImpl< MachineInstr * > & LoadInsts) static
Definition at line 52 of file NVPTXForwardParams.cpp.
References MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and traverseMoveUse().
Referenced by eliminateMove(), and traverseMoveUse().