LLVM: lib/Target/NVPTX/NVPTXIRPeephole.cpp File Reference
NVPTXIRPeephole.cpp File Reference
#include "NVPTXUtilities.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
Macros
#define DEBUG_TYPE "nvptx-ir-peephole"
Functions
static bool tryFoldBinaryFMul (BinaryOperator *BI)
static bool foldFMA (Function &F)
INITIALIZE_PASS (NVPTXIRPeephole, "nvptx-ir-peephole", "NVPTX IR Peephole", false, false) bool NVPTXIRPeephole
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-ir-peephole"
Definition at line 31 of file NVPTXIRPeephole.cpp.
Function Documentation
foldFMA()
bool foldFMA (Function & F) static
Definition at line 113 of file NVPTXIRPeephole.cpp.
References llvm::dyn_cast(), F, I, instructions, llvm::make_early_inc_range(), and tryFoldBinaryFMul().
Referenced by INITIALIZE_PASS(), and llvm::NVPTXIRPeepholePass::run().
INITIALIZE_PASS()
INITIALIZE_PASS (NVPTXIRPeephole , "nvptx-ir-peephole" , "NVPTX IR Peephole" , false , false)
Definition at line 150 of file NVPTXIRPeephole.cpp.
References F, foldFMA(), and runOnFunction().
tryFoldBinaryFMul()
bool tryFoldBinaryFMul (BinaryOperator * BI) static
Definition at line 35 of file NVPTXIRPeephole.cpp.
References llvm::cast(), llvm::dbgs(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::FMul, llvm::Instruction::getFastMathFlags(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::FastMathFlags::intersectRewrite(), LLVM_DEBUG, Op0, llvm::Value::replaceAllUsesWith(), and llvm::FastMathFlags::unionValue().
Referenced by foldFMA().