LLVM: lib/Object/OffloadBundle.cpp File Reference
OffloadBundle.cpp File Reference
#include "llvm/Object/OffloadBundle.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/IR/Module.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/COFF.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/Error.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/Timer.h"
Classes
union RawCompressedBundleHeader
struct RawCompressedBundleHeader::CommonFields
struct RawCompressedBundleHeader::V1Header
struct RawCompressedBundleHeader::V2Header
struct RawCompressedBundleHeader::V3Header
Functions
Error extractOffloadBundle (MemoryBufferRef Contents, uint64_t SectionOffset, StringRef FileName, SmallVectorImpl< OffloadBundleFatBin > &Bundles)
static std::string formatWithCommas (unsigned long long Value)
static LLVM_PACKED_END size_t getHeaderSize (uint16_t Version)
Variables
static TimerGroup OffloadBundlerTimerGroup ("Offload Bundler Timer Group", "Timer group for offload bundler")
Function Documentation
extractOffloadBundle()
Error extractOffloadBundle (MemoryBufferRef Contents, uint64_t SectionOffset, StringRef FileName, SmallVectorImpl< OffloadBundleFatBin > & Bundles)
Definition at line 33 of file OffloadBundle.cpp.
References llvm::object::OffloadBundleFatBin::create(), llvm::createFileError(), llvm::createStringError(), llvm::object::CompressedOffloadBundle::decompress(), llvm::StringRef::drop_front(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MemoryBufferRef::getBuffer(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getMemBuffer(), llvm::identify_magic(), llvm::StringRef::npos, llvm::file_magic::offload_bundle, llvm::file_magic::offload_bundle_compressed, llvm::Offset, llvm::StringRef::size(), llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::toString().
Referenced by llvm::object::extractOffloadBundleFatBinary().
formatWithCommas()
std::string formatWithCommas (unsigned long long Value) static
Definition at line 286 of file OffloadBundle.cpp.
Referenced by llvm::object::CompressedOffloadBundle::compress(), and llvm::object::CompressedOffloadBundle::decompress().
getHeaderSize()
LLVM_PACKED_END size_t getHeaderSize (uint16_t Version) static
Definition at line 448 of file OffloadBundle.cpp.
References llvm_unreachable.
Referenced by llvm::object::CompressedOffloadBundle::decompress(), and llvm::object::CompressedOffloadBundle::CompressedBundleHeader::tryParse().
Variable Documentation
OffloadBundlerTimerGroup
TimerGroup OffloadBundlerTimerGroup("Offload Bundler Timer Group", "Timer group for offload bundler") ("Offload Bundler Timer Group" , "Timer group for offload bundler") static
Referenced by llvm::object::CompressedOffloadBundle::compress(), and llvm::object::CompressedOffloadBundle::decompress().