LLVM: lib/Option/OptTable.cpp File Reference
OptTable.cpp File Reference
#include "llvm/Option/OptTable.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Option/Arg.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Option/OptSpecifier.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/OptionStrCmp.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstring>
#include <map>
#include <set>
#include <string>
#include <vector>
Functions
static bool isInput (const ArrayRef< StringRef > &Prefixes, StringRef Arg)
static unsigned matchOption (const StringTable &StrTable, ArrayRef< StringTable::Offset > PrefixesTable, const OptTable::Info *I, StringRef Str, bool IgnoreCase)
static bool optionMatches (const StringTable &StrTable, ArrayRef< StringTable::Offset > PrefixesTable, const OptTable::Info &In, StringRef Option)
static std::string getOptionHelpName (const OptTable &Opts, OptSpecifier Id)
static void PrintHelpOptionList (raw_ostream &OS, StringRef Title, std::vector< OptionInfo > &OptionHelp)
static const char * getOptionHelpGroup (const OptTable &Opts, OptSpecifier Id)
Function Documentation
getOptionHelpGroup()
const char * getOptionHelpGroup (const OptTable & Opts, OptSpecifier Id) static
Definition at line 700 of file OptTable.cpp.
References llvm::opt::OptTable::getOptionGroupID(), getOptionHelpGroup(), and llvm::opt::OptTable::getOptionHelpText().
Referenced by getOptionHelpGroup().
getOptionHelpName()
std::string getOptionHelpName (const OptTable & Opts, OptSpecifier Id) static
Definition at line 611 of file OptTable.cpp.
References llvm::opt::Option::CommaJoinedClass, llvm::opt::Option::FlagClass, llvm::opt::OptTable::getOption(), llvm::opt::OptTable::getOptionMetaVar(), llvm::opt::Option::GroupClass, llvm::opt::Option::InputClass, llvm::opt::Option::JoinedAndSeparateClass, llvm::opt::Option::JoinedClass, llvm::opt::Option::JoinedOrSeparateClass, llvm_unreachable, llvm::opt::Option::MultiArgClass, llvm::opt::Option::RemainingArgsClass, llvm::opt::Option::RemainingArgsJoinedClass, llvm::opt::Option::SeparateClass, llvm::opt::Option::UnknownClass, and llvm::opt::Option::ValuesClass.
isInput()
bool isInput (const ArrayRef< StringRef > & Prefixes, StringRef Arg) static
Definition at line 148 of file OptTable.cpp.
Referenced by llvm::Dependence::isUnordered().
matchOption()
unsigned matchOption (const StringTable & StrTable, ArrayRef< StringTable::Offset > PrefixesTable, const OptTable::Info * I, StringRef Str, bool IgnoreCase) static
Returns
Matched size. 0 means no match.
Definition at line 158 of file OptTable.cpp.
References I, llvm::StringRef::starts_with(), and llvm::StringRef::starts_with_insensitive().
optionMatches()
bool optionMatches (const StringTable & StrTable, ArrayRef< StringTable::Offset > PrefixesTable, const OptTable::Info & In, StringRef Option) static
Definition at line 177 of file OptTable.cpp.
Referenced by llvm::opt::OptTable::suggestValueCompletions().
PrintHelpOptionList()
void PrintHelpOptionList (raw_ostream & OS, StringRef Title, std::vector< OptionInfo > & OptionHelp) static
Definition at line 663 of file OptTable.cpp.
References assert(), llvm::raw_ostream::indent(), and llvm::Length.