LLVM: lib/Transforms/Scalar/PartiallyInlineLibCalls.cpp File Reference
PartiallyInlineLibCalls.cpp File Reference
#include "llvm/Transforms/Scalar/PartiallyInlineLibCalls.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/DebugCounter.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <optional>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "partially-inline-libcalls"
Functions
DEBUG_COUNTER (PILCounter, "partially-inline-libcalls-transform", "Controls transformations in partially-inline-libcalls")
static bool optimizeSQRT (CallInst *Call, Function *CalledFunc, BasicBlock &CurrBB, Function::iterator &BB, const TargetTransformInfo *TTI, DomTreeUpdater *DTU, OptimizationRemarkEmitter *ORE)
static bool runPartiallyInlineLibCalls (Function &F, TargetLibraryInfo *TLI, const TargetTransformInfo *TTI, DominatorTree *DT, OptimizationRemarkEmitter *ORE)
INITIALIZE_PASS_BEGIN (PartiallyInlineLibCallsLegacyPass, "partially-inline-libcalls", "Partially inline calls to library functions", false, false) INITIALIZE_PASS_END(PartiallyInlineLibCallsLegacyPass
Variables
partially inline libcalls
partially inline Partially calls to library functions
partially inline Partially calls to library false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "partially-inline-libcalls"
Definition at line 35 of file PartiallyInlineLibCalls.cpp.
Function Documentation
DEBUG_COUNTER()
DEBUG_COUNTER (PILCounter , "partially-inline-libcalls-transform" , "Controls transformations in partially-inline-libcalls")
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PartiallyInlineLibCallsLegacyPass , "partially-inline-libcalls" , "Partially inline calls to library functions" , false , false)
References INITIALIZE_PASS_DEPENDENCY, and INITIALIZE_PASS_END.
optimizeSQRT()
bool optimizeSQRT (CallInst * Call, Function * CalledFunc, BasicBlock & CurrBB, Function::iterator & BB, const TargetTransformInfo * TTI, DomTreeUpdater * DTU, OptimizationRemarkEmitter * ORE) static
Definition at line 40 of file PartiallyInlineLibCalls.cpp.
References llvm::BasicBlock::begin(), llvm::cast(), llvm::MDBuilder::createLikelyBranchWeights(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getName(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Instruction::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::ProfcheckDisableMetadataFixes, llvm::Value::setName(), llvm::DebugCounter::shouldExecute(), and llvm::SplitBlockAndInsertIfThen().
Referenced by runPartiallyInlineLibCalls().
runPartiallyInlineLibCalls()
bool runPartiallyInlineLibCalls (Function & F, TargetLibraryInfo * TLI, const TargetTransformInfo * TTI, DominatorTree * DT, OptimizationRemarkEmitter * ORE) static
Definition at line 118 of file PartiallyInlineLibCalls.cpp.
References llvm::dyn_cast(), F, llvm::TargetLibraryInfo::getLibFunc(), llvm::TargetLibraryInfo::has(), llvm::GlobalValue::hasLocalLinkage(), II, and optimizeSQRT().
Referenced by llvm::PartiallyInlineLibCallsPass::run().
Variable Documentation
false
partially inline Partially calls to library false
Definition at line 232 of file PartiallyInlineLibCalls.cpp.
functions
partially inline Partially calls to library functions inline
Definition at line 232 of file PartiallyInlineLibCalls.cpp.
libcalls
partially inline libcalls
Definition at line 231 of file PartiallyInlineLibCalls.cpp.