LLVM: lib/CodeGen/PHIEliminationUtils.cpp File Reference
PHIEliminationUtils.cpp File Reference
#include "PHIEliminationUtils.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
Functions
static bool hasInlineAsmBrToSuccessor (MachineBasicBlock *MBB, MachineBasicBlock *SuccMBB)
Function Documentation
hasInlineAsmBrToSuccessor()
bool hasInlineAsmBrToSuccessor (MachineBasicBlock * MBB, MachineBasicBlock * SuccMBB) static
Definition at line 18 of file PHIEliminationUtils.cpp.
References llvm::MachineBasicBlock::isInlineAsmBrIndirectTarget(), MBB, MI, and llvm::reverse().
Referenced by llvm::findPHICopyInsertPoint().