LLVM: lib/Target/PowerPC/TargetInfo/PowerPCTargetInfo.cpp File Reference
PowerPCTargetInfo.cpp File Reference
#include "TargetInfo/PowerPCTargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
Functions
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCTargetInfo ()
Function Documentation
LLVMInitializePowerPCTargetInfo()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCTargetInfo ()
Definition at line 32 of file PowerPCTargetInfo.cpp.
References llvm::getThePPC32LETarget(), llvm::getThePPC32Target(), llvm::getThePPC64LETarget(), llvm::getThePPC64Target(), llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::ppcle, X, and Y.