LLVM: lib/Target/PowerPC/GISel/PPCLegalizerInfo.cpp File Reference
PPCLegalizerInfo.cpp File Reference
This file implements the targeting of the Machinelegalizer class for PowerPC.
#include "PPCLegalizerInfo.h"
Macros
#define DEBUG_TYPE "ppc-legalinfo"
Functions
static LegalityPredicate isRegisterType (unsigned TypeIdx)
Detailed Description
This file implements the targeting of the Machinelegalizer class for PowerPC.
Definition in file PPCLegalizerInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-legalinfo"
Definition at line 14 of file PPCLegalizerInfo.cpp.
Function Documentation
isRegisterType()
LegalityPredicate isRegisterType (unsigned TypeIdx) static
Definition at line 21 of file PPCLegalizerInfo.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), and llvm::LLT::isVector().