LLVM: lib/CodeGen/PreISelIntrinsicLowering.cpp File Reference
PreISelIntrinsicLowering.cpp File Reference
#include "llvm/CodeGen/PreISelIntrinsicLowering.h"
#include "llvm/Analysis/ObjCARCInstKind.h"
#include "llvm/Analysis/ObjCARCUtil.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/ExpandVectorPredication.h"
#include "llvm/CodeGen/LibcallLoweringInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/RuntimeLibcalls.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Scalar/LowerConstantIntrinsics.h"
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/Transforms/Utils/LowerMemIntrinsics.h"
#include "llvm/Transforms/Utils/LowerVectorIntrinsics.h"
#include "llvm/IR/VPIntrinsics.def"
Macros
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, MASKPOS, VLENPOS)
Functions
template<class T>
static bool forEachCall (Function &Intrin, T Callback)
static bool lowerLoadRelative (Function &F)
static CallInst::TailCallKind getOverridingTailCallKind (const Function &F)
static bool lowerObjCCall (Function &F, RTLIB::LibcallImpl NewFn, bool setNonLazyBind=false)
static bool canEmitLibcall (const LibcallLoweringModuleAnalysisResult &ModuleLowering, const TargetMachine *TM, Function *F, RTLIB::Libcall LC)
static bool canEmitMemcpy (const LibcallLoweringModuleAnalysisResult &ModuleLowering, const TargetMachine *TM, Function *F)
static Constant * getMemSetPattern16Value (MemSetPatternInst *Inst, const TargetLibraryInfo &TLI)
static bool expandProtectedFieldPtr (Function &Intr)
INITIALIZE_PASS_BEGIN (PreISelIntrinsicLoweringLegacyPass, "pre-isel-intrinsic-lowering", "Pre-ISel Intrinsic Lowering", false, false) INITIALIZE_PASS_END(PreISelIntrinsicLoweringLegacyPass
Variables
static cl::opt< int64_t > MemIntrinsicExpandSizeThresholdOpt ("mem-intrinsic-expand-size", cl::desc("Set minimum mem intrinsic size to expand in IR"), cl::init(-1), cl::Hidden)
Threshold to leave statically sized memory intrinsic calls.
pre isel intrinsic lowering
pre isel intrinsic Pre ISel Intrinsic Lowering
pre isel intrinsic Pre ISel Intrinsic false
Macro Definition Documentation
BEGIN_REGISTER_VP_INTRINSIC
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, MASKPOS, VLENPOS)
Value:
case Intrinsic::VPID:
Function Documentation
canEmitLibcall()
bool canEmitLibcall (const LibcallLoweringModuleAnalysisResult & ModuleLowering, const TargetMachine * TM, Function * F, RTLIB::Libcall LC) static
Definition at line 240 of file PreISelIntrinsicLowering.cpp.
References F, llvm::LibcallLoweringModuleAnalysisResult::getLibcallLowering(), llvm::TargetMachine::getSubtargetImpl(), and Lowering.
canEmitMemcpy()
bool canEmitMemcpy (const LibcallLoweringModuleAnalysisResult & ModuleLowering, const TargetMachine * TM, Function * F) static
Definition at line 251 of file PreISelIntrinsicLowering.cpp.
References F, llvm::LibcallLoweringModuleAnalysisResult::getLibcallLowering(), llvm::TargetMachine::getSubtargetImpl(), and Lowering.
expandProtectedFieldPtr()
bool expandProtectedFieldPtr (Function & Intr) static
Definition at line 476 of file PreISelIntrinsicLowering.cpp.
References B(), llvm::cast(), llvm::StringRef::contains(), llvm::GlobalAlias::create(), llvm::dyn_cast(), llvm::SmallPtrSetImplBase::empty(), llvm::GlobalValue::ExternalLinkage, F, llvm::FunctionType::get(), llvm::PointerType::get(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::ConstantExpr::getIntToPtr(), llvm::User::getOperand(), llvm::Intrinsic::getOrInsertDeclaration(), llvm::GlobalValue::getParent(), llvm::Attribute::getValueAsString(), llvm::GlobalValue::HiddenVisibility, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::Attribute::isValid(), llvm::make_early_inc_range(), llvm::LLVMContext::OB_deactivation_symbol, llvm::reportFatalUsageError(), llvm::User::setOperand(), and llvm::Value::users().
forEachCall()
template<class T> bool forEachCall (Function & Intrin, T Callback) static
Definition at line 86 of file PreISelIntrinsicLowering.cpp.
References llvm::dyn_cast(), T, llvm::Value::use_begin(), and llvm::Value::use_empty().
getMemSetPattern16Value()
Constant * getMemSetPattern16Value (MemSetPatternInst * Inst, const TargetLibraryInfo & TLI) static
Definition at line 264 of file PreISelIntrinsicLowering.cpp.
References llvm::CallingConv::C, DL, llvm::dyn_cast(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::Instruction::getDataLayout(), llvm::Instruction::getModule(), llvm::Type::getPointerAddressSpace(), llvm::MemIntrinsicBase< Derived >::getRawDest(), llvm::Value::getType(), llvm::MemSetBase< BaseCL >::getValue(), llvm::isa(), llvm::isLibFuncEmittable(), llvm::isPowerOf2_64(), and Size.
getOverridingTailCallKind()
CallInst::TailCallKind getOverridingTailCallKind (const Function & F) static
Definition at line 136 of file PreISelIntrinsicLowering.cpp.
References F, llvm::objcarc::GetFunctionClass(), llvm::objcarc::IsAlwaysTail(), llvm::objcarc::IsNeverTail(), llvm::CallInst::TCK_None, llvm::CallInst::TCK_NoTail, and llvm::CallInst::TCK_Tail.
Referenced by lowerObjCCall().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PreISelIntrinsicLoweringLegacyPass , "pre-isel-intrinsic-lowering" , "Pre-ISel Intrinsic Lowering" , false , false)
References INITIALIZE_PASS_DEPENDENCY, and INITIALIZE_PASS_END.
lowerLoadRelative()
bool lowerLoadRelative (Function & F) static
Definition at line 107 of file PreISelIntrinsicLowering.cpp.
References B(), llvm::dyn_cast(), F, llvm::Type::getInt32Ty(), llvm::Int32Ty, and llvm::make_early_inc_range().
lowerObjCCall()
bool lowerObjCCall (Function & F, RTLIB::LibcallImpl NewFn, bool setNonLazyBind = false) static
Definition at line 145 of file PreISelIntrinsicLowering.cpp.
References llvm::CallBase::addParamAttr(), assert(), llvm::cast(), llvm::dyn_cast(), F, llvm::objcarc::getAttachedARCFunction(), llvm::FunctionCallee::getCallee(), llvm::RTLIB::RuntimeLibcallsInfo::getLibcallImplName(), getOverridingTailCallKind(), llvm::make_early_inc_range(), llvm::IntrinsicInst::mayLowerToFunctionCall(), llvm::Value::setName(), setNonLazyBind(), and llvm::CallInst::setTailCallKind().
Variable Documentation
false
pre isel intrinsic Pre ISel Intrinsic false
Definition at line 810 of file PreISelIntrinsicLowering.cpp.
Lowering
pre isel intrinsic Pre ISel Intrinsic Lowering
Definition at line 810 of file PreISelIntrinsicLowering.cpp.
Referenced by canEmitLibcall(), canEmitMemcpy(), EnsureStackAlignment(), llvm::AMDGPUDAGToDAGISel::PostprocessISelDAG(), llvm::PreISelIntrinsicLoweringPass::run(), and llvm::AMDGPUDAGToDAGISel::Select().
lowering
pre isel intrinsic lowering
Definition at line 809 of file PreISelIntrinsicLowering.cpp.
MemIntrinsicExpandSizeThresholdOpt
cl::opt< int64_t > MemIntrinsicExpandSizeThresholdOpt("mem-intrinsic-expand-size", cl::desc("Set minimum mem intrinsic size to expand in IR"), cl::init(-1), cl::Hidden) ("mem-intrinsic-expand-size" , cl::desc("Set minimum mem intrinsic size to expand in IR") , cl::init(-1) , cl::Hidden) static
Threshold to leave statically sized memory intrinsic calls.
Calls of known size larger than this will be expanded by the pass. Calls of unknown or lower size will be left for expansion in codegen.