LLVM: lib/IR/ProfileSummary.cpp File Reference
ProfileSummary.cpp File Reference
#include "llvm/IR/ProfileSummary.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Format.h"
Functions
static Metadata * getKeyValMD (LLVMContext &Context, const char *Key, uint64_t Val)
static Metadata * getKeyFPValMD (LLVMContext &Context, const char *Key, double Val)
static Metadata * getKeyValMD (LLVMContext &Context, const char *Key, const char *Val)
static ConstantAsMetadata * getValMD (MDTuple *MD, const char *Key)
static bool getVal (MDTuple *MD, const char *Key, uint64_t &Val)
static bool getVal (MDTuple *MD, const char *Key, double &Val)
static bool isKeyValuePair (MDTuple *MD, const char *Key, const char *Val)
static bool getSummaryFromMD (MDTuple *MD, SummaryEntryVector &Summary)
template<typename ValueType>
static bool getOptionalVal (MDTuple *Tuple, unsigned &Idx, const char *Key, ValueType &Value)
Function Documentation
getKeyFPValMD()
Metadata * getKeyFPValMD (LLVMContext & Context, const char * Key, double Val) static
Definition at line 34 of file ProfileSummary.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDTuple::get(), llvm::Type::getDoubleTy(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::ProfileSummary::getMD().
getKeyValMD() [1/2]
Metadata * getKeyValMD (LLVMContext & Context, const char * Key, const char * Val) static
Definition at line 44 of file ProfileSummary.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::MDString::get(), llvm::MDTuple::get(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
getKeyValMD() [2/2]
Metadata * getKeyValMD (LLVMContext & Context, const char * Key, uint64_t Val) static
Definition at line 26 of file ProfileSummary.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDTuple::get(), llvm::Type::getInt64Ty(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::ProfileSummary::getMD().
getOptionalVal()
template<typename ValueType> bool getOptionalVal (MDTuple * Tuple, unsigned & Idx, const char * Key, ValueType & Value) static
Definition at line 181 of file ProfileSummary.cpp.
References llvm::dyn_cast(), getVal(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::ProfileSummary::getFromMD().
getSummaryFromMD()
bool getSummaryFromMD (MDTuple * MD, SummaryEntryVector & Summary) static
Definition at line 149 of file ProfileSummary.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), llvm::ConstantAsMetadata::getValue(), Op0, and llvm::MDNode::operands().
Referenced by llvm::ProfileSummary::getFromMD().
getVal() [1/2]
bool getVal (MDTuple * MD, const char * Key, double & Val) static
Definition at line 127 of file ProfileSummary.cpp.
References llvm::cast(), getValMD(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
getVal() [2/2]
bool getVal (MDTuple * MD, const char * Key, uint64_t & Val) static
Definition at line 119 of file ProfileSummary.cpp.
References llvm::cast(), getValMD(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::ProfileSummary::getFromMD(), getOptionalVal(), and isRegImmLoadOrStore().
getValMD()
ConstantAsMetadata * getValMD (MDTuple * MD, const char * Key) static
Definition at line 104 of file ProfileSummary.cpp.
References llvm::dyn_cast(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by getVal(), and getVal().
isKeyValuePair()
bool isKeyValuePair (MDTuple * MD, const char * Key, const char * Val) static
Definition at line 136 of file ProfileSummary.cpp.
References llvm::dyn_cast(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), and llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key.
Referenced by llvm::ProfileSummary::getFromMD().