LLVM: lib/IR/ProfDataUtils.cpp File Reference
ProfDataUtils.cpp File Reference
#include "llvm/IR/ProfDataUtils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/CommandLine.h"
Functions
static bool isTargetMD (const MDNode *ProfData, const char *Name, unsigned MinOps)
template<typename T, typename = typename std::enable_if<std::is_arithmetic_v<T>>>
static void extractFromBranchWeightMD (const MDNode *ProfileData, SmallVectorImpl< T > &Weights)
static bool hasCountTypeMD (const Instruction &I)
Variables
static constexpr unsigned MinBWOps = 3
static constexpr unsigned MinVPOps = 5
static cl::opt< bool > ElideAllZeroBranchWeights ("elide-all-zero-branch-weights", cl::init(true))
Function Documentation
extractFromBranchWeightMD()
template<typename T, typename = typename std::enable_if<std::is_arithmetic_v<T>>> void extractFromBranchWeightMD (const MDNode * ProfileData, SmallVectorImpl< T > & Weights) static
Definition at line 69 of file ProfDataUtils.cpp.
References assert(), llvm::mdconst::dyn_extract(), E(), llvm::APInt::getActiveBits(), llvm::getBranchWeightOffset(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), llvm::isBranchWeightMD(), llvm::SmallVectorImpl< T >::resize(), and T.
Referenced by llvm::extractBranchWeights(), llvm::extractFromBranchWeightMD32(), and llvm::extractFromBranchWeightMD64().
hasCountTypeMD()
bool hasCountTypeMD (const Instruction & I) static
Definition at line 136 of file ProfDataUtils.cpp.
References I, llvm::isa(), llvm::isBranchWeightMD(), and llvm::isValueProfileMD().
Referenced by llvm::scaleProfData().
isTargetMD()
bool isTargetMD (const MDNode * ProfData, const char * Name, unsigned MinOps) static
Definition at line 49 of file ProfDataUtils.cpp.
References llvm::dyn_cast(), llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Referenced by llvm::isBranchWeightMD(), and llvm::isValueProfileMD().
Variable Documentation
ElideAllZeroBranchWeights
cl::opt< bool > ElideAllZeroBranchWeights("elide-all-zero-branch-weights", cl::init(true)) ("elide-all-zero-branch-weights" , cl::init(true)) static
Referenced by llvm::setBranchWeights().
MinBWOps
unsigned MinBWOps = 3 static constexpr
Definition at line 42 of file ProfDataUtils.cpp.
Referenced by llvm::isBranchWeightMD().
MinVPOps
unsigned MinVPOps = 5 static constexpr
Definition at line 45 of file ProfDataUtils.cpp.
Referenced by llvm::isValueProfileMD().