LLVM: lib/Frontend/Offloading/PropertySet.cpp File Reference
PropertySet.cpp File Reference
#include "llvm/Frontend/Offloading/PropertySet.h"
#include "llvm/Support/Base64.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/MemoryBufferRef.h"
Functions
template<typename... Ts>
auto createStringErrorV (Ts &&...Args)
Expected< PropertyValue > readPropertyValueFromJSON (const json::Value &PropValueVal)
Function Documentation
createStringErrorV()
template<typename... Ts> auto createStringErrorV (Ts &&... Args)
Definition at line 45 of file PropertySet.cpp.
References llvm::createStringError(), and llvm::formatv().
Referenced by llvm::offloading::readPropertiesFromJSON(), and readPropertyValueFromJSON().
readPropertyValueFromJSON()
Expected< PropertyValue > readPropertyValueFromJSON (const json::Value & PropValueVal)
Definition at line 50 of file PropertySet.cpp.
References createStringErrorV(), llvm::decodeBase64(), E(), llvm::json::Value::getAsString(), llvm::json::Value::getAsUINT64(), and llvm::toString().
Referenced by llvm::offloading::readPropertiesFromJSON().