LLVM: lib/Support/LSP/Protocol.cpp File Reference
Protocol.cpp File Reference
#include "llvm/Support/LSP/Protocol.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
Functions
template<typename T>
static bool mapOptOrNull (const llvm::json::Value &Params, llvm::StringLiteral Prop, T &Out, llvm::json::Path Path)
static bool isWindowsPath (StringRef Path)
static bool isNetworkPath (StringRef Path)
static bool shouldEscapeInURI (unsigned char C)
static void percentEncode (StringRef Content, std::string &Out)
Encodes a string according to percent-encoding.
static std::string percentDecode (StringRef Content)
Decodes a string according to percent-encoding.
static StringSet & getSupportedSchemes ()
Return the set containing the supported URI schemes.
static bool isStructurallyValidScheme (StringRef Scheme)
Returns true if the given scheme is structurally valid, i.e.
static llvm::Expected< std::string > uriFromAbsolutePath (StringRef AbsolutePath, StringRef Scheme)
static llvm::Expected< std::string > getAbsolutePath (StringRef Authority, StringRef Body)
static llvm::Expected< std::string > parseFilePathFromURI (StringRef OrigUri)
static llvm::StringRef toTextKind (MarkupKind Kind)
Function Documentation
getAbsolutePath()
llvm::Expected< std::string > getAbsolutePath (StringRef Authority, StringRef Body) static
Definition at line 158 of file Protocol.cpp.
References llvm::StringRef::consume_front(), llvm::createStringError(), llvm::StringRef::empty(), llvm::inconvertibleErrorCode(), isWindowsPath(), llvm::sys::path::native, llvm::StringRef::starts_with(), and llvm::StringRef::substr().
Referenced by parseFilePathFromURI().
getSupportedSchemes()
StringSet & getSupportedSchemes () static
Return the set containing the supported URI schemes.
Definition at line 111 of file Protocol.cpp.
Referenced by parseFilePathFromURI(), and llvm::lsp::URIForFile::registerSupportedScheme().
isNetworkPath()
bool isNetworkPath (StringRef Path) static
Definition at line 54 of file Protocol.cpp.
References llvm::sys::path::is_separator().
Referenced by uriFromAbsolutePath().
isStructurallyValidScheme()
bool isStructurallyValidScheme (StringRef Scheme) static
Returns true if the given scheme is structurally valid, i.e.
it does not contain any invalid scheme characters. This does not check that the scheme is actually supported.
Definition at line 119 of file Protocol.cpp.
References llvm::all_of(), llvm::CallingConv::C, llvm::drop_begin(), and llvm::StringRef::empty().
Referenced by parseFilePathFromURI().
isWindowsPath()
bool isWindowsPath (StringRef Path) static
Definition at line 50 of file Protocol.cpp.
Referenced by getAbsolutePath(), and uriFromAbsolutePath().
mapOptOrNull()
template<typename T> bool mapOptOrNull (const llvm::json::Value & Params, llvm::StringLiteral Prop, T & Out, llvm::json::Path Path) static
Definition at line 27 of file Protocol.cpp.
References assert(), llvm::lsp::fromJSON(), llvm::json::Value::getAsObject(), and T.
Referenced by llvm::lsp::fromJSON(), llvm::lsp::fromJSON(), and llvm::lsp::fromJSON().
parseFilePathFromURI()
llvm::Expected< std::string > parseFilePathFromURI (StringRef OrigUri) static
Definition at line 179 of file Protocol.cpp.
References llvm::StringRef::consume_front(), contains(), llvm::createStringError(), llvm::StringRef::find(), getAbsolutePath(), getSupportedSchemes(), llvm::inconvertibleErrorCode(), isStructurallyValidScheme(), llvm::StringRef::npos, percentDecode(), and llvm::StringRef::substr().
Referenced by llvm::lsp::URIForFile::fromURI().
percentDecode()
std::string percentDecode (StringRef Content) static
Decodes a string according to percent-encoding.
Definition at line 96 of file Protocol.cpp.
References llvm::StringRef::begin(), E(), llvm::StringRef::end(), and I.
Referenced by parseFilePathFromURI().
percentEncode()
void percentEncode (StringRef Content, std::string & Out) static
Encodes a string according to percent-encoding.
Unreserved characters are not escaped.
Reserved characters always escaped with exceptions like '/'.
All other characters are escaped.
Definition at line 83 of file Protocol.cpp.
References llvm::CallingConv::C, and shouldEscapeInURI().
Referenced by uriFromAbsolutePath().
shouldEscapeInURI()
bool shouldEscapeInURI (unsigned char C) static
Definition at line 59 of file Protocol.cpp.
References llvm::CallingConv::C.
Referenced by percentEncode().
toTextKind()
llvm::StringRef toTextKind (MarkupKind Kind) static
Definition at line 559 of file Protocol.cpp.
References llvm_unreachable, llvm::lsp::Markdown, and llvm::lsp::PlainText.
Referenced by llvm::lsp::operator<<(), and llvm::lsp::toJSON().
uriFromAbsolutePath()
llvm::Expected< std::string > uriFromAbsolutePath (StringRef AbsolutePath, StringRef Scheme) static
Definition at line 129 of file Protocol.cpp.
References llvm::StringRef::consume_front(), llvm::sys::path::convert_to_slash(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), isNetworkPath(), isWindowsPath(), percentEncode(), llvm::sys::path::root_name(), starts_with(), and llvm::StringRef::str().
Referenced by llvm::lsp::URIForFile::fromFile().