LLVM: lib/FuzzMutate/RandomIRBuilder.cpp File Reference
RandomIRBuilder.cpp File Reference
#include "llvm/FuzzMutate/RandomIRBuilder.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/FuzzMutate/OpDescriptor.h"
#include "llvm/FuzzMutate/Random.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
Functions
static std::vector< BasicBlock * > getDominators (BasicBlock *BB)
Return a vector of Blocks that dominates this block, excluding current block.
static std::vector< BasicBlock * > getDominatees (BasicBlock *BB)
Return a vector of Blocks that is dominated by this block, excluding current block.
static Value * buildTargetLegalPtr (Module *M, Value *Ptr, InsertPosition IP, const Twine &Name, SmallVector< Instruction * > *NewInsts)
static Instruction * buildTargetLegalStore (Value *Val, Value *Ptr, InsertPosition IP, Module *M)
static std::pair< Instruction *, SmallVector< Instruction * > > buildTargetLegalLoad (Type *AccessTy, Value *Ptr, InsertPosition IP, Module *M, const Twine &LoadName)
static void eraseNewInstructions (SmallVector< Instruction * > &NewInsts)
static bool isCompatibleReplacement (const Instruction *I, const Use &Operand, const Value *Replacement)
Function Documentation
buildTargetLegalLoad()
std::pair< Instruction *, SmallVector< Instruction * > > buildTargetLegalLoad (Type * AccessTy, Value * Ptr, InsertPosition IP, Module * M, const Twine & LoadName) static
Definition at line 141 of file RandomIRBuilder.cpp.
References buildTargetLegalPtr(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::RandomIRBuilder::findOrCreateSource(), and llvm::RandomIRBuilder::newSource().
buildTargetLegalPtr()
Value * buildTargetLegalPtr (Module * M, Value * Ptr, InsertPosition IP, const Twine & Name, SmallVector< Instruction * > * NewInsts) static
Definition at line 112 of file RandomIRBuilder.cpp.
References llvm::dyn_cast(), llvm::PointerType::get(), llvm::Value::getType(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by buildTargetLegalLoad(), and buildTargetLegalStore().
buildTargetLegalStore()
Instruction * buildTargetLegalStore (Value * Val, Value * Ptr, InsertPosition IP, Module * M) static
Definition at line 132 of file RandomIRBuilder.cpp.
References buildTargetLegalPtr().
Referenced by llvm::RandomIRBuilder::connectToSink(), and llvm::RandomIRBuilder::newSink().
eraseNewInstructions()
void eraseNewInstructions (SmallVector< Instruction * > & NewInsts) static
Definition at line 153 of file RandomIRBuilder.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), and llvm::SmallVectorTemplateCommon< T, typename >::rend().
Referenced by llvm::RandomIRBuilder::findOrCreateSource(), and llvm::RandomIRBuilder::newSource().
getDominatees()
std::vector< BasicBlock * > getDominatees (BasicBlock * BB) static
Return a vector of Blocks that is dominated by this block, excluding current block.
Definition at line 45 of file RandomIRBuilder.cpp.
References llvm::DomTreeNodeBase< NodeT >::children(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), and llvm::BasicBlock::getParent().
Referenced by llvm::RandomIRBuilder::connectToSink().
getDominators()
std::vector< BasicBlock * > getDominators (BasicBlock * BB) static
Return a vector of Blocks that dominates this block, excluding current block.
Definition at line 26 of file RandomIRBuilder.cpp.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), and llvm::BasicBlock::getParent().
Referenced by llvm::RandomIRBuilder::connectToSink(), and llvm::RandomIRBuilder::findOrCreateSource().
isCompatibleReplacement()
bool isCompatibleReplacement (const Instruction * I, const Use & Operand, const Value * Replacement) static
Definition at line 293 of file RandomIRBuilder.cpp.
References llvm::cast(), llvm::Use::getOperandNo(), llvm::Value::getType(), and I.
Referenced by llvm::RandomIRBuilder::connectToSink().