LLVM: lib/Support/raw_ostream.cpp File Reference
raw_ostream.cpp File Reference
#include "llvm/Support/raw_ostream.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Config/config.h"
#include "llvm/Support/AutoConvert.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Duration.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/IOSandbox.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/NativeFormatting.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Program.h"
#include <algorithm>
#include <cerrno>
#include <cstdio>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
Functions
template<char C>
static raw_ostream & write_padding (raw_ostream &OS, unsigned NumChars)
static int getFD (StringRef Filename, std::error_code &EC, sys::fs::CreationDisposition Disp, sys::fs::FileAccess Access, sys::fs::OpenFlags Flags)
Function Documentation
getFD()
int getFD (StringRef Filename, std::error_code & EC, sys::fs::CreationDisposition Disp, sys::fs::FileAccess Access, sys::fs::OpenFlags Flags) static
Definition at line 555 of file raw_ostream.cpp.
References Access, assert(), llvm::sys::ChangeStdoutMode(), llvm::sys::fs::FA_Read, llvm::sys::fs::FA_Write, llvm::sys::fs::openFileForReadWrite(), llvm::sys::fs::openFileForWrite(), llvm::sys::sandbox::scopedDisable(), and STDOUT_FILENO.
Referenced by llvm::raw_fd_ostream::raw_fd_ostream(), and llvm::raw_fd_stream::raw_fd_stream().
write_padding()
template<char C> raw_ostream & write_padding (raw_ostream & OS, unsigned NumChars) static
Definition at line 465 of file raw_ostream.cpp.
References llvm::CallingConv::C, and llvm::raw_ostream::write().
Referenced by llvm::raw_ostream::indent(), and llvm::raw_ostream::write_zeros().