LLVM: lib/CodeGen/RegAllocEvictionAdvisor.cpp File Reference
RegAllocEvictionAdvisor.cpp File Reference
#include "llvm/CodeGen/RegAllocEvictionAdvisor.h"
#include "AllocationOrder.h"
#include "RegAllocGreedy.h"
#include "llvm/CodeGen/LiveRegMatrix.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/RegAllocPriorityAdvisor.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetMachine.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "regalloc"
Functions
cl::opt< unsigned > llvm::EvictInterferenceCutoff ("regalloc-eviction-max-interference-cutoff", cl::Hidden, cl::desc("Number of interferences after which we declare " "an interference unevictable and bail out. This " "is a compilation cost-saving consideration. To " "disable, pass a very large number."), cl::init(10))
INITIALIZE_PASS (RegAllocEvictionAdvisorAnalysisLegacy, "regalloc-evict", "Regalloc eviction policy", false, true) namespace
Variables
static cl::opt< RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode > Mode ("regalloc-enable-advisor", cl::Hidden, cl::init(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Default), cl::desc("Enable regalloc advisor mode"), cl::values(clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Development, "development", "for training")))
static cl::opt< bool > EnableLocalReassignment ("enable-local-reassign", cl::Hidden, cl::desc("Local reassignment can yield better allocation decisions, but " "may be compile time intensive"), cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regalloc"
Definition at line 59 of file RegAllocEvictionAdvisor.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RegAllocEvictionAdvisorAnalysisLegacy , "regalloc-evict" , "Regalloc eviction policy" , false , true)
Definition at line 65 of file RegAllocEvictionAdvisor.cpp.
References llvm::classof(), llvm::Pass::doInitialization(), llvm::RegAllocEvictionAdvisorProvider::getAdvisor(), RA, llvm::RegAllocEvictionAdvisorAnalysisLegacy::RegAllocEvictionAdvisorAnalysisLegacy(), and llvm::RegAllocEvictionAdvisorProvider::RegAllocEvictionAdvisorProvider().
Variable Documentation
EnableLocalReassignment
cl::opt< bool > EnableLocalReassignment("enable-local-reassign", cl::Hidden, cl::desc("Local reassignment can yield better allocation decisions, but " "may be compile time intensive"), cl::init(false)) ("enable-local-reassign" , cl::Hidden , cl::desc("Local reassignment can yield better allocation decisions, but " "may be compile time intensive") , cl::init(false)) static
Referenced by llvm::RegAllocEvictionAdvisor::RegAllocEvictionAdvisor().
Mode
cl::opt< RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode > Mode("regalloc-enable-advisor", cl::Hidden, cl::init(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Default), cl::desc("Enable regalloc advisor mode"), cl::values(clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Development, "development", "for training"))) ("regalloc-enable-advisor" , cl::Hidden , cl::init(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Default) , cl::desc("Enable regalloc advisor mode") , cl::values(clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocEvictionAdvisorAnalysisLegacy::AdvisorMode::Development, "development", "for training"))) static
Referenced by llvm::sys::fs::access(), applyDebugify(), applyDebugify(), applyMnemonicAliases(), ARM64EmitUnwindCode(), llvm::AAResults::canInstructionRangeModRef(), llvm::KnownFPClass::cannotBeOrderedGreaterEqZero(), canReduceVMulWidth(), computeKnownBitsForPRMT(), computeKnownFPClass(), computePRMT(), convertNvvmIntrinsicToLlvm(), createCheckDebugifyFunctionPass(), createCheckDebugifyModulePass(), createDebugifyFunctionPass(), createDebugifyModulePass(), createInMemoryBuffer(), createOnDiskBuffer(), createUniqueEntity(), llvm::denormalModeKindName(), ExpandHorizontalBinOp(), llvm::GenericFloatingPointPredicateUtils< SSAContext >::fcmpImpliesClass(), flushDenormalConstant(), flushDenormalConstantFP(), foldFabsWithFcmpZero(), llvm::GCNTTIImpl::GCNTTIImpl(), llvm::ARM_AM::getAM4SubMode(), llvm::ARM_AM::getAMSubModeStr(), llvm::SIModeRegisterDefaults::getDefaultForCallingConv(), getFPMode(), getLoadStoreMultipleOpcode(), getPostIndexedLoadStoreOpcode(), getPreIndexedLoadStoreOpcode(), getPRMT(), getPRMT(), getPRMTSelector(), getSPDenormModeValue(), getUpdatingLSMultipleOpcode(), getVectorComparison(), getVectorComparisonOrInvert(), INITIALIZE_PASS_END(), inputDenormalIsIEEE(), inputDenormalIsIEEEOrPosZero(), llvm::TargetTransformInfoImplBase::isIndexedLoadLegal(), llvm::TargetTransformInfoImplBase::isIndexedStoreLegal(), isMemberPointer(), llvm::RISCVFPRndMode::isValidRoundingMode(), llvm::RISCVVXRndMode::isValidRoundingMode(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVMSetTargetMachineGlobalISelAbort(), LLVMSetThreadLocalMode(), lowerPrmtIntrinsic(), llvm::yaml::MappingTraits< SIMode >::mapping(), matchPMADDWD(), llvm::orc::EPCGenericDylibManager::open(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::open(), llvm::sys::fs::openFile(), llvm::sys::fs::openFileForReadWrite(), llvm::sys::fs::openFileForWrite(), llvm::sys::fs::openNativeFile(), llvm::sys::fs::openNativeFileForReadWrite(), llvm::sys::fs::openNativeFileForWrite(), llvm::operator<<(), outputDenormalIsIEEEOrPosZero(), llvm::parseDenormalFPAttribute(), printAsmMRegister(), printAsmVRegister(), reduceVMULWidth(), llvm::TargetMachine::setGlobalISelAbort(), setXFormForUnalignedFI(), llvm::yaml::SIMode::SIMode(), simplifyDemandedBitsForPRMT(), llvm::KnownFPClass::square(), toggleSPDenormMode(), llvm::codeview::TypeIndex::TypeIndex(), llvm::ir2vec::Embedder::~Embedder(), and llvm::mir2vec::MIREmbedder::~MIREmbedder().