LLVM: lib/CodeGen/RegAllocPriorityAdvisor.cpp File Reference
RegAllocPriorityAdvisor.cpp File Reference
#include "llvm/CodeGen/RegAllocPriorityAdvisor.h"
#include "RegAllocGreedy.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
Functions
INITIALIZE_PASS (RegAllocPriorityAdvisorAnalysisLegacy, "regalloc-priority", "Regalloc priority policy", false, true) namespace
Variables
static cl::opt< RegAllocPriorityAdvisorProvider::AdvisorMode > Mode ("regalloc-enable-priority-advisor", cl::Hidden, cl::init(RegAllocPriorityAdvisorProvider::AdvisorMode::Default), cl::desc("Enable regalloc advisor mode"), cl::values(clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Development, "development", "for training"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Dummy, "dummy", "prioritize low virtual register numbers for test and debug")))
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RegAllocPriorityAdvisorAnalysisLegacy , "regalloc-priority" , "Regalloc priority policy" , false , true)
Definition at line 39 of file RegAllocPriorityAdvisor.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::classof(), llvm::Pass::doInitialization(), llvm::RegAllocPriorityAdvisorProvider::getAdvisor(), llvm::RegAllocPriorityAdvisorAnalysisLegacy::getAnalysisUsage(), RA, llvm::RegAllocPriorityAdvisorAnalysisLegacy::RegAllocPriorityAdvisorAnalysisLegacy(), and llvm::RegAllocPriorityAdvisorProvider::RegAllocPriorityAdvisorProvider().
Variable Documentation
Mode
cl::opt< RegAllocPriorityAdvisorProvider::AdvisorMode > Mode("regalloc-enable-priority-advisor", cl::Hidden, cl::init(RegAllocPriorityAdvisorProvider::AdvisorMode::Default), cl::desc("Enable regalloc advisor mode"), cl::values(clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Development, "development", "for training"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Dummy, "dummy", "prioritize low virtual register numbers for test and debug"))) ("regalloc-enable-priority-advisor" , cl::Hidden , cl::init(RegAllocPriorityAdvisorProvider::AdvisorMode::Default) , cl::desc("Enable regalloc advisor mode") , cl::values(clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Development, "development", "for training"), clEnumValN(RegAllocPriorityAdvisorProvider::AdvisorMode::Dummy, "dummy", "prioritize low virtual register numbers for test and debug"))) static