LLVM: lib/Transforms/Utils/RelLookupTableConverter.cpp File Reference
RelLookupTableConverter.cpp File Reference
#include "llvm/Transforms/Utils/RelLookupTableConverter.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
Classes
struct LookupTableInfo
Functions
static bool shouldConvertToRelLookupTable (LookupTableInfo &Info, Module &M, GlobalVariable &GV)
static GlobalVariable * createRelLookupTable (LookupTableInfo &Info, Function &Func, GlobalVariable &LookupTable)
static void convertToRelLookupTable (LookupTableInfo &Info, GlobalVariable &LookupTable)
static bool convertToRelativeLookupTables (Module &M, function_ref< TargetTransformInfo &(Function &)> GetTTI)
Function Documentation
convertToRelativeLookupTables()
bool convertToRelativeLookupTables (Module & M, function_ref< TargetTransformInfo &(Function &)> GetTTI) static
Definition at line 207 of file RelLookupTableConverter.cpp.
References convertToRelLookupTable(), F, Info, llvm::make_early_inc_range(), and shouldConvertToRelLookupTable().
Referenced by llvm::RelLookupTableConverterPass::run().
convertToRelLookupTable()
void convertToRelLookupTable (LookupTableInfo & Info, GlobalVariable & LookupTable) static
Definition at line 166 of file RelLookupTableConverter.cpp.
References llvm::cast(), createRelLookupTable(), GEP, llvm::Intrinsic::getOrInsertDeclaration(), llvm::BasicBlock::getParent(), Info, and llvm::Offset.
Referenced by convertToRelativeLookupTables().
createRelLookupTable()
GlobalVariable * createRelLookupTable (LookupTableInfo & Info, Function & Func, GlobalVariable & LookupTable) static
Definition at line 132 of file RelLookupTableConverter.cpp.
References llvm::sampleprof::Base, llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getPtrToInt(), llvm::ConstantExpr::getSub(), llvm::ConstantExpr::getTrunc(), llvm::GlobalValue::Global, Info, llvm::GlobalVariable::setAlignment(), llvm::GlobalVariable::setInitializer(), llvm::GlobalValue::setUnnamedAddr(), and llvm::Sub.
Referenced by convertToRelLookupTable().
shouldConvertToRelLookupTable()
bool shouldConvertToRelLookupTable (LookupTableInfo & Info, Module & M, GlobalVariable & GV) static
Definition at line 29 of file RelLookupTableConverter.cpp.
References llvm::CallingConv::C, llvm::ConstantFoldLoadFromConst(), DL, llvm::dyn_cast(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::front(), GEP, llvm::GlobalVariable::getInitializer(), llvm::Use::getUser(), llvm::GlobalValue::getValueType(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasOneUse(), Info, llvm::GlobalVariable::isConstant(), llvm::IsConstantOffsetFromGlobal(), llvm::GlobalValue::isDSOLocal(), llvm::GlobalValue::isImplicitDSOLocal(), llvm::Type::isPointerTy(), llvm::APInt::isZero(), llvm::GlobalValue::None, llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size(), llvm::APInt::ult(), and llvm::Value::use_begin().
Referenced by convertToRelativeLookupTables().