LLVM: lib/ExecutionEngine/Orc/ReOptimizeLayer.cpp File Reference
ReOptimizeLayer.cpp File Reference
#include "llvm/ExecutionEngine/Orc/ReOptimizeLayer.h"
#include "llvm/ExecutionEngine/Orc/Mangling.h"
Functions
static void orc_rt_lite_reoptimize_helper (shared::CWrapperFunctionBuffer(*JITDispatch)(void *Ctx, void *Tag, const char *Data, size_t Size), void *JITDispatchCtx, void *Tag, uint64_t MUID, uint32_t CurVersion)
Function Documentation
orc_rt_lite_reoptimize_helper()
void orc_rt_lite_reoptimize_helper (shared::CWrapperFunctionBuffer(* JITDispatch)(void *Ctx, void *Tag, const char *Data, size_t Size), void * JITDispatchCtx, void * Tag, uint64_t MUID, uint32_t CurVersion) static
Definition at line 29 of file ReOptimizeLayer.cpp.
References llvm::orc::shared::WrapperFunctionBuffer::allocate(), llvm::Data, llvm::errs(), and llvm::orc::shared::WrapperFunctionBuffer::getOutOfBandError().
Referenced by llvm::orc::ReOptimizeLayer::addOrcRTLiteSupport().