LLVM: lib/IR/ReplaceConstant.cpp File Reference
ReplaceConstant.cpp File Reference
#include "llvm/IR/ReplaceConstant.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
Functions
static bool isExpandableUser (User *U)
static void expandUser (BasicBlock::iterator InsertPt, Constant *C, SmallVector< Instruction *, 4 > &NewInsts)
Function Documentation
expandUser()
void expandUser (BasicBlock::iterator InsertPt, Constant * C, SmallVector< Instruction *, 4 > & NewInsts) static
Definition at line 25 of file ReplaceConstant.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::SmallVectorImpl< T >::clear(), llvm::InsertElementInst::Create(), llvm::InsertValueInst::Create(), llvm::dyn_cast(), llvm::enumerate(), llvm::PoisonValue::get(), llvm::Type::getInt32Ty(), llvm::Instruction::insertBefore(), llvm::isa(), llvm_unreachable, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::convertUsersOfConstantsToInstructions().
isExpandableUser()
bool isExpandableUser (User * U) static
Definition at line 21 of file ReplaceConstant.cpp.
References llvm::isa().
Referenced by llvm::convertUsersOfConstantsToInstructions().