LLVM: lib/Target/RISCV/MCTargetDesc/RISCVMatInt.cpp File Reference
RISCVMatInt.cpp File Reference
#include "RISCVMatInt.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "llvm/ADT/APInt.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/Support/MathExtras.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::RISCVMatInt
Functions
static int getInstSeqCost (RISCVMatInt::InstSeq &Res, bool HasRVC)
static void generateInstSeqImpl (int64_t Val, const MCSubtargetInfo &STI, RISCVMatInt::InstSeq &Res)
static unsigned extractRotateInfo (int64_t Val)
static void generateInstSeqLeadingZeros (int64_t Val, const MCSubtargetInfo &STI, RISCVMatInt::InstSeq &Res)
InstSeq llvm::RISCVMatInt::generateInstSeq (int64_t Val, const MCSubtargetInfo &STI)
void llvm::RISCVMatInt::generateMCInstSeq (int64_t Val, const MCSubtargetInfo &STI, MCRegister DestReg, SmallVectorImpl< MCInst > &Insts)
InstSeq llvm::RISCVMatInt::generateTwoRegInstSeq (int64_t Val, const MCSubtargetInfo &STI, unsigned &ShiftAmt, unsigned &AddOpc)
int llvm::RISCVMatInt::getIntMatCost (const APInt &Val, unsigned Size, const MCSubtargetInfo &STI, bool CompressionCost, bool FreeZeroes)
Function Documentation
extractRotateInfo()
unsigned extractRotateInfo (int64_t Val) static
Definition at line 214 of file RISCVMatInt.cpp.
References llvm::countl_one(), llvm::countr_one(), llvm::Hi_32(), and llvm::Lo_32().
Referenced by llvm::RISCVMatInt::generateInstSeq().
generateInstSeqImpl()
void generateInstSeqImpl (int64_t Val, const MCSubtargetInfo & STI, RISCVMatInt::InstSeq & Res) static
Definition at line 53 of file RISCVMatInt.cpp.
References assert(), llvm::countr_zero(), llvm::SmallVectorImpl< T >::emplace_back(), generateInstSeqImpl(), llvm::MCSubtargetInfo::hasFeature(), llvm::isInt(), llvm::isPowerOf2_64(), llvm::isUInt(), llvm::Log2_64(), Opc, llvm::SignExtend64(), and Unsigned.
Referenced by llvm::RISCVMatInt::generateInstSeq(), generateInstSeqImpl(), and generateInstSeqLeadingZeros().
generateInstSeqLeadingZeros()
void generateInstSeqLeadingZeros (int64_t Val, const MCSubtargetInfo & STI, RISCVMatInt::InstSeq & Res) static
Definition at line 232 of file RISCVMatInt.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::countl_zero(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), generateInstSeqImpl(), llvm::MCSubtargetInfo::hasFeature(), llvm::maskTrailingOnes(), llvm::maskTrailingZeros(), llvm::SignExtend64(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::RISCVMatInt::generateInstSeq().
getInstSeqCost()
int getInstSeqCost (RISCVMatInt::InstSeq & Res, bool HasRVC) static
Definition at line 16 of file RISCVMatInt.cpp.
References llvm::isInt(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::RISCVMatInt::getIntMatCost().