LLVM: lib/Target/RISCV/Disassembler/RISCVDisassembler.cpp File Reference
RISCVDisassembler.cpp File Reference
#include "MCTargetDesc/RISCVBaseInfo.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoder.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Endian.h"
#include "RISCVGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "riscv-disassembler"
Functions
static MCDisassembler * createRISCVDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRF16RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRF32RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRX1X5RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR16RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32CRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64CRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR128RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRX1RegisterClass (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeSPRegisterClass (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeSPRegisterClass (MCInst &Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRX5RegisterClass (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRNoX0RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRNoX2RegisterClass (MCInst &Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRNoX31RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRCRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRPairRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRPairNoX0RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRPairCRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSR07RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVRRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM2RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM4RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM8RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVMV0RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeTRRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeTRM2RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeTRM4RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeVMaskReg (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeImmThreeOperand (MCInst &Inst, const MCDisassembler *Decoder)
static DecodeStatus decodeImmFourOperand (MCInst &Inst, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned Width, unsigned LowerBound>
static DecodeStatus decodeUImmOperandGE (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned Width, unsigned LowerBound>
static DecodeStatus decodeUImmPlus1OperandGE (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeUImmSlistOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeUImmLog2XLenOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmNonZeroOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeUImmLog2XLenNonZeroOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmPlus1Operand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeImmZibiOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmNonZeroOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned T, unsigned N>
static DecodeStatus decodeSImmOperandAndLslN (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeCLUIImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeFRMArg (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRTZArg (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeZcmpRlist (MCInst &Inst, uint32_t Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeXqccmpRlistS0 (MCInst &Inst, uint32_t Imm, uint64_t Address, const MCDisassembler *Decoder)
Variables
static constexpr FeatureBitset XCVFeatureGroup
static constexpr FeatureBitset XRivosFeatureGroup
static constexpr FeatureBitset XqciFeatureGroup
static constexpr FeatureBitset XSfVectorGroup
static constexpr FeatureBitset XSfSystemGroup
static constexpr FeatureBitset XMIPSGroup
static constexpr FeatureBitset XTHeadGroup
static constexpr FeatureBitset XAndesGroup
static constexpr FeatureBitset XSMTGroup = {RISCV::FeatureVendorXSMTVDot}
static constexpr DecoderListEntry DecoderList32 []
static constexpr DecoderListEntry DecoderList16 []
static constexpr DecoderListEntry DecoderList48 []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-disassembler"
Definition at line 31 of file RISCVDisassembler.cpp.
Function Documentation
createRISCVDisassembler()
MCDisassembler * createRISCVDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 62 of file RISCVDisassembler.cpp.
References T.
Referenced by LLVMInitializeRISCVDisassembler().
decodeCLUIImmOperand()
DecodeStatus decodeCLUIImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 565 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::isUInt(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeFPR128RegisterClass()
DecodeStatus DecodeFPR128RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 186 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR16RegisterClass()
DecodeStatus DecodeFPR16RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 131 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR32CRegisterClass()
DecodeStatus DecodeFPR32CRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 153 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR32RegisterClass()
DecodeStatus DecodeFPR32RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 142 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR64CRegisterClass()
DecodeStatus DecodeFPR64CRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 175 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeFPR64RegisterClass()
DecodeStatus DecodeFPR64RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 164 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
decodeFRMArg()
DecodeStatus decodeFRMArg (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 576 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::isUInt(), llvm::RISCVFPRndMode::isValidRoundingMode(), and llvm::MCDisassembler::Success.
DecodeGPRCRegisterClass()
DecodeStatus DecodeGPRCRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 251 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeGPRF16RegisterClass()
DecodeStatus DecodeGPRF16RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 94 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), Reg, and llvm::MCDisassembler::Success.
DecodeGPRF32RegisterClass()
DecodeStatus DecodeGPRF32RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 107 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), Reg, and llvm::MCDisassembler::Success.
DecodeGPRNoX0RegisterClass()
DecodeStatus DecodeGPRNoX0RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 223 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
DecodeGPRNoX2RegisterClass()
DecodeStatus DecodeGPRNoX2RegisterClass (MCInst & Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler * Decoder) static
Definition at line 232 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
DecodeGPRNoX31RegisterClass()
DecodeStatus DecodeGPRNoX31RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 241 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
DecodeGPRPairCRegisterClass()
DecodeStatus DecodeGPRPairCRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 287 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), Reg, and llvm::MCDisassembler::Success.
DecodeGPRPairNoX0RegisterClass()
DecodeStatus DecodeGPRPairNoX0RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 279 of file RISCVDisassembler.cpp.
References DecodeGPRPairRegisterClass(), and llvm::MCDisassembler::Fail.
DecodeGPRPairRegisterClass()
DecodeStatus DecodeGPRPairRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 262 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeGPRPairNoX0RegisterClass().
DecodeGPRRegisterClass()
DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 81 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), Reg, and llvm::MCDisassembler::Success.
Referenced by DecodeGPRNoX0RegisterClass(), DecodeGPRNoX2RegisterClass(), and DecodeGPRNoX31RegisterClass().
DecodeGPRX1RegisterClass()
DecodeStatus DecodeGPRX1RegisterClass (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 197 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
DecodeGPRX1X5RegisterClass()
DecodeStatus DecodeGPRX1X5RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 120 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeGPRX5RegisterClass()
DecodeStatus DecodeGPRX5RegisterClass (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 217 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
decodeImmFourOperand()
DecodeStatus decodeImmFourOperand (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 437 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
decodeImmThreeOperand()
DecodeStatus decodeImmThreeOperand (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 431 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
decodeImmZibiOperand()
DecodeStatus decodeImmZibiOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 526 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), and llvm::MCDisassembler::Success.
decodeRTZArg()
DecodeStatus decodeRTZArg (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 586 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::isUInt(), llvm::RISCVFPRndMode::RTZ, and llvm::MCDisassembler::Success.
decodeSImmNonZeroOperand()
template<unsigned N> DecodeStatus decodeSImmNonZeroOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 545 of file RISCVDisassembler.cpp.
References decodeSImmOperand(), and llvm::MCDisassembler::Fail.
decodeSImmOperand()
template<unsigned N> DecodeStatus decodeSImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 535 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
Referenced by decodeSImmNonZeroOperand().
decodeSImmOperandAndLslN()
template<unsigned T, unsigned N> DecodeStatus decodeSImmOperandAndLslN (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 554 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), N, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeSPRegisterClass() [1/2]
DecodeStatus DecodeSPRegisterClass (MCInst & Inst, const MCDisassembler * Decoder) static
Definition at line 203 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
DecodeSPRegisterClass() [2/2]
DecodeStatus DecodeSPRegisterClass (MCInst & Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler * Decoder) static
Definition at line 209 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
DecodeSR07RegisterClass()
DecodeStatus DecodeSR07RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 303 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeTRM2RegisterClass()
DecodeStatus DecodeTRM2RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 397 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeTRM4RegisterClass()
DecodeStatus DecodeTRM4RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 408 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeTRRegisterClass()
DecodeStatus DecodeTRRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 386 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
decodeUImmLog2XLenNonZeroOperand()
DecodeStatus decodeUImmLog2XLenNonZeroOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 510 of file RISCVDisassembler.cpp.
References decodeUImmLog2XLenOperand(), and llvm::MCDisassembler::Fail.
decodeUImmLog2XLenOperand()
DecodeStatus decodeUImmLog2XLenOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 487 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), llvm::isUInt(), and llvm::MCDisassembler::Success.
Referenced by decodeUImmLog2XLenNonZeroOperand().
decodeUImmNonZeroOperand()
template<unsigned N> DecodeStatus decodeUImmNonZeroOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 501 of file RISCVDisassembler.cpp.
References decodeUImmOperand(), and llvm::MCDisassembler::Fail.
decodeUImmOperand()
template<unsigned N> DecodeStatus decodeUImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 444 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), and llvm::MCDisassembler::Success.
Referenced by decodeUImmNonZeroOperand().
decodeUImmOperandGE()
template<unsigned Width, unsigned LowerBound> DecodeStatus decodeUImmOperandGE (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 453 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::isUInt(), and llvm::MCDisassembler::Success.
decodeUImmPlus1Operand()
template<unsigned N> DecodeStatus decodeUImmPlus1Operand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 518 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), and llvm::MCDisassembler::Success.
decodeUImmPlus1OperandGE()
template<unsigned Width, unsigned LowerBound> DecodeStatus decodeUImmPlus1OperandGE (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 466 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::isUInt(), and llvm::MCDisassembler::Success.
decodeUImmSlistOperand()
DecodeStatus decodeUImmSlistOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 478 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), and llvm::MCDisassembler::Success.
decodeVMaskReg()
DecodeStatus decodeVMaskReg (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 419 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
DecodeVMV0RegisterClass()
DecodeStatus DecodeVMV0RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 376 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeVRM2RegisterClass()
DecodeStatus DecodeVRM2RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 325 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), Reg, and llvm::MCDisassembler::Success.
DecodeVRM4RegisterClass()
DecodeStatus DecodeVRM4RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 342 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), Reg, and llvm::MCDisassembler::Success.
DecodeVRM8RegisterClass()
DecodeStatus DecodeVRM8RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 359 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), Reg, and llvm::MCDisassembler::Success.
DecodeVRRegisterClass()
DecodeStatus DecodeVRRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 314 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, Reg, and llvm::MCDisassembler::Success.
decodeXqccmpRlistS0()
DecodeStatus decodeXqccmpRlistS0 (MCInst & Inst, uint32_t Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 606 of file RISCVDisassembler.cpp.
References decodeZcmpRlist(), llvm::MCDisassembler::Fail, and llvm::RISCVZC::RA_S0.
decodeZcmpRlist()
DecodeStatus decodeZcmpRlist (MCInst & Inst, uint32_t Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 596 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), llvm::RISCVZC::RA, llvm::RISCVZC::RA_S0_S2, and llvm::MCDisassembler::Success.
Referenced by decodeXqccmpRlistS0().
LLVMInitializeRISCVDisassembler()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
Definition at line 69 of file RISCVDisassembler.cpp.
References createRISCVDisassembler(), llvm::getTheRISCV32beTarget(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64beTarget(), llvm::getTheRISCV64Target(), and llvm::TargetRegistry::RegisterMCDisassembler().
Variable Documentation
DecoderList16
DecoderListEntry DecoderList16[] static constexpr
Initial value:
{
    {DecoderTableXqci16, XqciFeatureGroup, "Qualcomm uC 16-bit"},
    {DecoderTableXqccmp16,
     {RISCV::FeatureVendorXqccmp},
     "Xqccmp (Qualcomm 16-bit Push/Pop & Double Move Instructions)"},
    {DecoderTableXwchc16, {RISCV::FeatureVendorXwchc}, "WCH QingKe XW"},
    {DecoderTableZicfiss16, {}, "Zicfiss (Shadow Stack 16-bit)"},
    {DecoderTable16, {}, "standard 16-bit instructions"},
    {DecoderTableRV32Only16, {}, "RV32-only 16-bit instructions"},
    {DecoderTableZcOverlap16,
     {},
     "ZcOverlap (16-bit Instructions overlapping with Zcf/Zcd)"},
}
Definition at line 747 of file RISCVDisassembler.cpp.
DecoderList32
DecoderListEntry DecoderList32[] static constexpr
Initial value:
{
    {DecoderTableXCV32, XCVFeatureGroup, "CORE-V extensions"},
    {DecoderTableXRivos32, XRivosFeatureGroup, "Rivos"},
    {DecoderTableXqci32, XqciFeatureGroup, "Qualcomm uC Extensions"},
    {DecoderTableXVentana32,
     {RISCV::FeatureVendorXVentanaCondOps},
     "XVentanaCondOps"},
    {DecoderTableXTHead32, XTHeadGroup, "T-Head extensions"},
    {DecoderTableXSfvector32, XSfVectorGroup, "SiFive vector extensions"},
    {DecoderTableXSfsystem32, XSfSystemGroup, "SiFive system extensions"},
    {DecoderTableXSfcease32, {RISCV::FeatureVendorXSfcease}, "SiFive sf.cease"},
    {DecoderTableXMIPS32, XMIPSGroup, "Mips extensions"},
    {DecoderTableXAndes32, XAndesGroup, "Andes extensions"},
    {DecoderTableXSMT32, XSMTGroup, "SpacemiT extensions"},
    {DecoderTable32, {}, "standard 32-bit instructions"},
    {DecoderTableRV32Only32, {}, "RV32-only standard 32-bit instructions"},
    {DecoderTableZfinx32, {}, "Zfinx (Float in Integer)"},
    {DecoderTableZdinxRV32Only32, {}, "RV32-only Zdinx (Double in Integer)"},
}
Definition at line 689 of file RISCVDisassembler.cpp.
DecoderList48
DecoderListEntry DecoderList48[] static constexpr
Initial value:
{
    {DecoderTableXqci48, XqciFeatureGroup, "Qualcomm uC 48bit"},
}
Definition at line 791 of file RISCVDisassembler.cpp.
XAndesGroup
FeatureBitset XAndesGroup static constexpr
Initial value:
                                       = {
RISCV::FeatureVendorXAndesPerf,      RISCV::FeatureVendorXAndesBFHCvt,
RISCV::FeatureVendorXAndesVBFHCvt,   RISCV::FeatureVendorXAndesVSIntH,
RISCV::FeatureVendorXAndesVSIntLoad, RISCV::FeatureVendorXAndesVPackFPH,
RISCV::FeatureVendorXAndesVDot}
Definition at line 681 of file RISCVDisassembler.cpp.
XCVFeatureGroup
FeatureBitset XCVFeatureGroup static constexpr
Initial value:
                                           = {
RISCV::FeatureVendorXCVbitmanip, RISCV::FeatureVendorXCVelw,
RISCV::FeatureVendorXCVmac,      RISCV::FeatureVendorXCVmem,
RISCV::FeatureVendorXCValu,      RISCV::FeatureVendorXCVsimd,
RISCV::FeatureVendorXCVbi}
Definition at line 631 of file RISCVDisassembler.cpp.
XMIPSGroup
FeatureBitset XMIPSGroup static constexpr
Initial value:
                                          = {
    RISCV::FeatureVendorXMIPSLSP,
    RISCV::FeatureVendorXMIPSCMov,
    RISCV::FeatureVendorXMIPSCBOP,
    RISCV::FeatureVendorXMIPSEXECTL,
}
Definition at line 666 of file RISCVDisassembler.cpp.
XqciFeatureGroup
FeatureBitset XqciFeatureGroup static constexpr
Initial value:
                                                = {
    RISCV::FeatureVendorXqcia,   RISCV::FeatureVendorXqciac,
    RISCV::FeatureVendorXqcibi,  RISCV::FeatureVendorXqcibm,
    RISCV::FeatureVendorXqcicli, RISCV::FeatureVendorXqcicm,
    RISCV::FeatureVendorXqcics,  RISCV::FeatureVendorXqcicsr,
    RISCV::FeatureVendorXqciint, RISCV::FeatureVendorXqciio,
    RISCV::FeatureVendorXqcilb,  RISCV::FeatureVendorXqcili,
    RISCV::FeatureVendorXqcilia, RISCV::FeatureVendorXqcilo,
    RISCV::FeatureVendorXqcilsm, RISCV::FeatureVendorXqcisim,
    RISCV::FeatureVendorXqcisls, RISCV::FeatureVendorXqcisync,
}
Definition at line 642 of file RISCVDisassembler.cpp.
XRivosFeatureGroup
FeatureBitset XRivosFeatureGroup static constexpr
Initial value:
                                                  = {
    RISCV::FeatureVendorXRivosVisni,
    RISCV::FeatureVendorXRivosVizip,
}
Definition at line 637 of file RISCVDisassembler.cpp.
XSfSystemGroup
FeatureBitset XSfSystemGroup static constexpr
Initial value:
                                              = {
    RISCV::FeatureVendorXSiFivecdiscarddlone,
    RISCV::FeatureVendorXSiFivecflushdlone,
}
Definition at line 661 of file RISCVDisassembler.cpp.
XSfVectorGroup
FeatureBitset XSfVectorGroup static constexpr
Initial value:
                                          = {
RISCV::FeatureVendorXSfvcp,          RISCV::FeatureVendorXSfvqmaccdod,
RISCV::FeatureVendorXSfvqmaccqoq,    RISCV::FeatureVendorXSfvfwmaccqqq,
RISCV::FeatureVendorXSfvfnrclipxfqf, RISCV::FeatureVendorXSfmmbase,
RISCV::FeatureVendorXSfvfexpa,       RISCV::FeatureVendorXSfvfexpa64e,
RISCV::FeatureVendorXSfvfbfexp16e,   RISCV::FeatureVendorXSfvfexp16e,
RISCV::FeatureVendorXSfvfexp32e}
Definition at line 654 of file RISCVDisassembler.cpp.
XSMTGroup
FeatureBitset XSMTGroup = {RISCV::FeatureVendorXSMTVDot} static constexpr
Definition at line 687 of file RISCVDisassembler.cpp.
XTHeadGroup
FeatureBitset XTHeadGroup static constexpr
Initial value:
                                       = {
RISCV::FeatureVendorXTHeadBa,      RISCV::FeatureVendorXTHeadBb,
RISCV::FeatureVendorXTHeadBs,      RISCV::FeatureVendorXTHeadCondMov,
RISCV::FeatureVendorXTHeadCmo,     RISCV::FeatureVendorXTHeadFMemIdx,
RISCV::FeatureVendorXTHeadMac,     RISCV::FeatureVendorXTHeadMemIdx,
RISCV::FeatureVendorXTHeadMemPair, RISCV::FeatureVendorXTHeadSync,
RISCV::FeatureVendorXTHeadVdot}
Definition at line 673 of file RISCVDisassembler.cpp.