LLVM: lib/Target/RISCV/RISCVLateBranchOpt.cpp File Reference
RISCVLateBranchOpt.cpp File Reference
#include "RISCVInstrInfo.h"
#include "RISCVSubtarget.h"
Macros
#define RISCV_LATE_BRANCH_OPT_NAME "RISC-V Late Branch Optimisation Pass"
Functions
INITIALIZE_PASS (RISCVLateBranchOpt, "riscv-late-branch-opt", RISCV_LATE_BRANCH_OPT_NAME, false, false) bool RISCVLateBranchOpt
Macro Definition Documentation
RISCV_LATE_BRANCH_OPT_NAME
#define RISCV_LATE_BRANCH_OPT_NAME "RISC-V Late Branch Optimisation Pass"
Definition at line 20 of file RISCVLateBranchOpt.cpp.
Referenced by INITIALIZE_PASS().
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVLateBranchOpt , "riscv-late-branch-opt" , RISCV_LATE_BRANCH_OPT_NAME , false , false)
Definition at line 45 of file RISCVLateBranchOpt.cpp.
References assert(), Cond, llvm::RISCVCC::COND_INVALID, DL, llvm::RISCVInstrInfo::evaluateCondBranch(), llvm::RISCVInstrInfo::getCondFromBranchOpc(), if(), llvm::RISCVInstrInfo::isFromLoadImm(), MBB, MRI, RISCV_LATE_BRANCH_OPT_NAME, runOnBasicBlock(), and TBB.