LLVM: lib/Target/RISCV/GISel/RISCVLegalizerInfo.cpp File Reference
RISCVLegalizerInfo.cpp File Reference
This file implements the targeting of the Machinelegalizer class for RISC-V.
#include "RISCVLegalizerInfo.h"
#include "MCTargetDesc/RISCVMatInt.h"
#include "RISCVMachineFunctionInfo.h"
#include "RISCVSubtarget.h"
#include "llvm/CodeGen/GlobalISel/GIMatchTableExecutor.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsRISCV.h"
#include "llvm/IR/Type.h"
Functions
static LegalityPredicate typeIsLegalIntOrFPVec (unsigned TypeIdx, std::initializer_list< LLT > IntOrFPVecTys, const RISCVSubtarget &ST)
static LegalityPredicate typeIsLegalBoolVec (unsigned TypeIdx, std::initializer_list< LLT > BoolVecTys, const RISCVSubtarget &ST)
static LegalityPredicate typeIsLegalPtrVec (unsigned TypeIdx, std::initializer_list< LLT > PtrVecTys, const RISCVSubtarget &ST)
static LLT getMaskTypeFor (LLT VecTy)
Return the type of the mask type suitable for masking the provided vector type.
static MachineInstrBuilder buildAllOnesMask (LLT VecTy, const SrcOp &VL, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Creates an all ones mask suitable for masking a vector of type VecTy with vector length VL.
static std::pair< MachineInstrBuilder, MachineInstrBuilder > buildDefaultVLOps (LLT VecTy, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Gets the two common "VL" operands: an all-ones mask and the vector length.
static MachineInstrBuilder buildSplatPartsS64WithVL (const DstOp &Dst, const SrcOp &Passthru, Register Lo, Register Hi, const SrcOp &VL, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
static MachineInstrBuilder buildSplatSplitS64WithVL (const DstOp &Dst, const SrcOp &Passthru, const SrcOp &Scalar, const SrcOp &VL, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
static LLT getLMUL1Ty (LLT VecTy)
static unsigned getRISCVWOpcode (unsigned Opcode)
Detailed Description
This file implements the targeting of the Machinelegalizer class for RISC-V.
Todo
This should be generated by TableGen.
Definition in file RISCVLegalizerInfo.cpp.
Function Documentation
buildAllOnesMask()
MachineInstrBuilder buildAllOnesMask (LLT VecTy, const SrcOp & VL, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Creates an all ones mask suitable for masking a vector of type VecTy with vector length VL.
Definition at line 1037 of file RISCVLegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildInstr(), getMaskTypeFor(), and MRI.
Referenced by buildDefaultVLOps().
buildDefaultVLOps()
std::pair< MachineInstrBuilder, MachineInstrBuilder > buildDefaultVLOps (LLT VecTy, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Gets the two common "VL" operands: an all-ones mask and the vector length.
VecTy is a scalable vector type.
Definition at line 1047 of file RISCVLegalizerInfo.cpp.
References assert(), buildAllOnesMask(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getSubtarget(), llvm::RISCVSubtarget::getXLenVT(), llvm::LLT::isScalableVector(), and MRI.
buildSplatPartsS64WithVL()
MachineInstrBuilder buildSplatPartsS64WithVL (const DstOp & Dst, const SrcOp & Passthru, Register Lo, Register Hi, const SrcOp & VL, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Definition at line 1057 of file RISCVLegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildInstr(), llvm::Hi, llvm::Lo, and MRI.
Referenced by buildSplatSplitS64WithVL().
buildSplatSplitS64WithVL()
MachineInstrBuilder buildSplatSplitS64WithVL (const DstOp & Dst, const SrcOp & Passthru, const SrcOp & Scalar, const SrcOp & VL, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Definition at line 1073 of file RISCVLegalizerInfo.cpp.
References assert(), buildSplatPartsS64WithVL(), llvm::MachineIRBuilder::buildUnmerge(), llvm::SrcOp::getReg(), MRI, and llvm::LLT::scalar().
getLMUL1Ty()
LLT getLMUL1Ty (LLT VecTy) static
Definition at line 1138 of file RISCVLegalizerInfo.cpp.
References assert(), llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), llvm::RISCV::RVVBitsPerBlock, and llvm::LLT::scalable_vector().
getMaskTypeFor()
LLT getMaskTypeFor (LLT VecTy) static
Return the type of the mask type suitable for masking the provided vector type.
This is simply an i1 element type vector of the same (possibly scalable) length.
Definition at line 1029 of file RISCVLegalizerInfo.cpp.
References assert(), llvm::LLT::getElementCount(), llvm::LLT::isVector(), llvm::LLT::scalar(), and llvm::LLT::vector().
Referenced by buildAllOnesMask(), getAllOnesMask(), lowerFMAXIMUM_FMINIMUM(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), and llvm::RISCVTargetLowering::PerformDAGCombine().
getRISCVWOpcode()
unsigned getRISCVWOpcode (unsigned Opcode) static
Definition at line 1364 of file RISCVLegalizerInfo.cpp.
References llvm_unreachable.
Referenced by customLegalizeToWOp(), and llvm::RISCVLegalizerInfo::legalizeCustom().
typeIsLegalBoolVec()
LegalityPredicate typeIsLegalBoolVec (unsigned TypeIdx, std::initializer_list< LLT > BoolVecTys, const RISCVSubtarget & ST) static
Definition at line 53 of file RISCVLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), P, and llvm::LegalityPredicates::typeInSet().
typeIsLegalIntOrFPVec()
LegalityPredicate typeIsLegalIntOrFPVec (unsigned TypeIdx, std::initializer_list< LLT > IntOrFPVecTys, const RISCVSubtarget & ST) static
Definition at line 38 of file RISCVLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), P, and llvm::LegalityPredicates::typeInSet().
Referenced by llvm::RISCVLegalizerInfo::RISCVLegalizerInfo().
typeIsLegalPtrVec()
LegalityPredicate typeIsLegalPtrVec (unsigned TypeIdx, std::initializer_list< LLT > PtrVecTys, const RISCVSubtarget & ST) static
Definition at line 63 of file RISCVLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), P, and llvm::LegalityPredicates::typeInSet().