LLVM: lib/Target/RISCV/MCA/RISCVCustomBehaviour.cpp File Reference
RISCVCustomBehaviour.cpp File Reference
This file implements methods from the RISCVCustomBehaviour class.
#include "RISCVCustomBehaviour.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "RISCV.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugLog.h"
#include "RISCVGenSearchableTables.inc"
Classes
struct llvm::RISCV::VXMemOpInfo
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::RISCV
namespace llvm::mca
Macros
#define DEBUG_TYPE "llvm-mca-riscv-custombehaviour"
#define GET_RISCVBaseVXMemOpTable_IMPL
Functions
static std::pair< uint8_t, uint8_t > llvm::mca::getEEWAndEMUL (unsigned Opcode, RISCVVType::VLMUL LMUL, uint8_t SEW)
static bool llvm::mca::opcodeHasEEWAndEMULInfo (unsigned short Opcode)
static InstrumentManager * createRISCVInstrumentManager (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTargetMCA ()
Extern function to initialize the targets for the RISC-V backend.
Detailed Description
This file implements methods from the RISCVCustomBehaviour class.
Definition in file RISCVCustomBehaviour.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "llvm-mca-riscv-custombehaviour"
Definition at line 23 of file RISCVCustomBehaviour.cpp.
GET_RISCVBaseVXMemOpTable_IMPL
#define GET_RISCVBaseVXMemOpTable_IMPL
Definition at line 34 of file RISCVCustomBehaviour.cpp.
Function Documentation
createRISCVInstrumentManager()
InstrumentManager * createRISCVInstrumentManager (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) static
Definition at line 343 of file RISCVCustomBehaviour.cpp.
Referenced by LLVMInitializeRISCVTargetMCA().
LLVMInitializeRISCVTargetMCA()
LLVM_ABI LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTargetMCA ()
Extern function to initialize the targets for the RISC-V backend.
Definition at line 350 of file RISCVCustomBehaviour.cpp.
References createRISCVInstrumentManager(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), and llvm::TargetRegistry::RegisterInstrumentManager().