LLVM: lib/Target/RISCV/RISCVRedundantCopyElimination.cpp File Reference
RISCVRedundantCopyElimination.cpp File Reference
#include "RISCV.h"
#include "RISCVInstrInfo.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "riscv-copyelim"
Functions
STATISTIC (NumCopiesRemoved, "Number of copies removed.")
INITIALIZE_PASS (RISCVRedundantCopyElimination, "riscv-copyelim", "RISC-V Redundant Copy Elimination", false, false) static bool guaranteesZeroRegInBlock(MachineBasicBlock &MBB
assert (TBB !=nullptr &&"Expected branch target basic block")
if (Opc==RISCV::BEQ &&Cond[2].isReg() &&Cond[2].getReg()==RISCV::X0 &&TBB==&MBB) return true
static bool guaranteesRegEqualsImmInBlock (MachineBasicBlock &MBB, const SmallVectorImpl< MachineOperand > &Cond, MachineBasicBlock *TBB)
Variables
const SmallVectorImpl< MachineOperand > & Cond
const SmallVectorImpl< MachineOperand > MachineBasicBlock * TBB
auto Opc = Cond[0].getImm()
return false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-copyelim"
Definition at line 37 of file RISCVRedundantCopyElimination.cpp.
Function Documentation
assert()
assert (TBB ! = nullptr &&"Expected branch target basic block")
References TBB.
Referenced by guaranteesRegEqualsImmInBlock().
guaranteesRegEqualsImmInBlock()
bool guaranteesRegEqualsImmInBlock (MachineBasicBlock & MBB, const SmallVectorImpl< MachineOperand > & Cond, MachineBasicBlock * TBB) static
Definition at line 88 of file RISCVRedundantCopyElimination.cpp.
References assert(), Cond, llvm::getImm(), MBB, Opc, and TBB.
if()
if (Opc = =RISCV::BEQ &&Cond[2].isReg() &&Cond[2].getReg()==RISCV::X0 &&TBB==&MBB)
References Cond, MBB, Opc, and TBB.
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVRedundantCopyElimination , "riscv-copyelim" , "RISC-V Redundant Copy Elimination" , false , false) &
References MBB.
STATISTIC()
STATISTIC (NumCopiesRemoved , "Number of copies removed.")
References MRI, TII, and TRI.
Variable Documentation
Cond
const SmallVectorImpl<MachineOperand>& Cond
Definition at line 73 of file RISCVRedundantCopyElimination.cpp.
Referenced by addConditions(), llvm::addPredicatedMveVpredNOp(), llvm::addPredicatedMveVpredROp(), llvm::adjustKnownBitsForSelectArm(), llvm::adjustKnownFPClassForSelectArm(), llvm::MipsInstrInfo::adjustStackPtr(), llvm::AArch64InstrInfo::analyzeBranch(), llvm::ARCInstrInfo::analyzeBranch(), llvm::ARMBaseInstrInfo::analyzeBranch(), llvm::AVRInstrInfo::analyzeBranch(), llvm::BPFInstrInfo::analyzeBranch(), llvm::CSKYInstrInfo::analyzeBranch(), llvm::HexagonInstrInfo::analyzeBranch(), llvm::LoongArchInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::analyzeBranch(), llvm::MipsInstrInfo::analyzeBranch(), llvm::MipsInstrInfo::analyzeBranch(), llvm::MSP430InstrInfo::analyzeBranch(), llvm::NVPTXInstrInfo::analyzeBranch(), llvm::PPCInstrInfo::analyzeBranch(), llvm::R600InstrInfo::analyzeBranch(), llvm::RISCVInstrInfo::analyzeBranch(), llvm::SIInstrInfo::analyzeBranch(), llvm::SparcInstrInfo::analyzeBranch(), llvm::SPIRVInstrInfo::analyzeBranch(), llvm::SystemZInstrInfo::analyzeBranch(), llvm::TargetInstrInfo::analyzeBranch(), llvm::VEInstrInfo::analyzeBranch(), llvm::WebAssemblyInstrInfo::analyzeBranch(), llvm::X86InstrInfo::analyzeBranch(), llvm::XCoreInstrInfo::analyzeBranch(), llvm::XtensaInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::AnalyzeBranchImpl(), llvm::SIInstrInfo::analyzeBranchImpl(), llvm::X86InstrInfo::analyzeBranchPredicate(), analyzeICmp(), llvm::AArch64InstrInfo::analyzeLoopForPipelining(), llvm::RISCVInstrInfo::analyzeLoopForPipelining(), llvm::ARMBaseInstrInfo::analyzeSelect(), llvm::LanaiInstrInfo::analyzeSelect(), llvm::RISCVInstrInfo::analyzeSelect(), llvm::TargetInstrInfo::analyzeSelect(), llvm::sandboxir::SelectInst::areInvalidOperands(), llvm::VPlanTransforms::attachCheckBlock(), buildNonAtomicBinOp(), buildPartialInvariantUnswitchConditionalBranch(), buildPartialUnswitchConditionalBranch(), calculateUpperBound(), llvm::AArch64InstrInfo::canInsertSelect(), llvm::PPCInstrInfo::canInsertSelect(), llvm::SIInstrInfo::canInsertSelect(), llvm::TargetInstrInfo::canInsertSelect(), llvm::X86InstrInfo::canInsertSelect(), llvm::TargetInstrInfo::canMakeTailCallConditional(), canonicalizeScalarSelectOfVecs(), canProveExitOnFirstIteration(), CanProveNotTakenFirstIteration(), llvm::MachineBasicBlock::canSplitCriticalEdge(), canSplitLoopBound(), carryFlagToValue(), checkBoolTestAndOrSetCCCombine(), checkDecodedInstruction(), collectUnswitchCandidates(), combineBallotPattern(), combineBrCond(), combineCMov(), combineM68kBrCond(), combineMulSelectConstOne(), combineOr(), combineOrOfCZERO(), combineSelect(), llvm::VETargetLowering::combineSelect(), combineSelectAsExtAnd(), combineSelectOfTwoConstants(), combineShiftLeft(), combineShiftRightLogical(), combineSubABS(), combineTruncSelectToSMaxUSat(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), commuteSelect(), computeKnownBitsFromCond(), computeKnownFPClassFromCond(), computeKnownFPClassFromContext(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldTerminator(), ConvertSelectToConcatVector(), llvm::VPlanTransforms::convertToConcreteRecipes(), llvm::BranchInst::Create(), llvm::sandboxir::BranchInst::create(), llvm::sandboxir::SelectInst::create(), llvm::IRBuilderBase::CreateAssumption(), createCMovFP(), llvm::sandboxir::CmpInst::createCommon(), llvm::IRBuilderBase::CreateCondBr(), llvm::IRBuilderBase::CreateCondBr(), createDedicatedExit(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::OpenMPIRBuilder::createLoopSkeleton(), createNodeForSelectViaUMinSeq(), llvm::OpenMPIRBuilder::createReductionsGPU(), llvm::TargetInstrInfo::PipelinerLoopInfo::createRemainingIterationsGreaterCondition(), llvm::VPBuilder::createSelect(), createShuffleMaskFromVSELECT(), llvm::TargetInstrInfo::PipelinerLoopInfo::createTripCountGreaterCondition(), DecodeLDR(), decomposeBitTest(), llvm::decomposeBitTest(), dependsOnLocalPhi(), distributeOpThroughSelect(), eliminateDeadSwitchCases(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), llvm::OpenMPIRBuilder::emitIfClause(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::XtensaTargetLowering::EmitInstrWithCustomInserter(), emitMisexpectDiagnostic(), eraseTerminatorAndDCECond(), llvm::VPReductionRecipe::execute(), llvm::VPWidenRecipe::execute(), expandAnyOrAllIntrinsic(), llvm::TargetLowering::expandIntMINMAX(), llvm::TargetLowering::expandShiftParts(), llvm::TargetLowering::expandShlSat(), expandStepIntrinsic(), findAffectedValues(), findBestNonTrivialUnswitchCandidate(), FindLoopCounter(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::findValuesAffectedByCondition(), FixTail(), llvm::PeelingModuloScheduleExpander::fixupBranches(), llvm::CondOpInit::Fold(), foldADCToCINC(), foldBitCastSelect(), foldBoolSelectToLogic(), llvm::foldBranchToCommonDest(), foldCondBranchOnValueKnownInPredecessorImpl(), foldCSELOfCSEL(), llvm::AMDGPUTargetLowering::foldFreeOpFromSelect(), foldFrexpOfSelect(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpBinOpWithConstantViaTruthTable(), llvm::InstCombinerImpl::foldICmpSelectConstant(), foldMulSelectToNegate(), foldRoundUpIntegerWithPow2Alignment(), foldSelectCmpBitcasts(), llvm::InstCombinerImpl::foldSelectExtConst(), foldSelectFunnelShift(), foldSelectGEP(), foldSelectOfConstantsUsingSra(), foldSelectOfCTTZOrCTLZ(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSelectToCopysign(), foldSelectToPhiImpl(), foldSelectWithIdentityConstant(), llvm::SelectionDAG::FoldSetCC(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), llvm::InstCombinerImpl::foldVectorSelect(), foldXorTruncShiftIntoCmp(), llvm::AMDGPU::genAMDGPUReportBlock(), generateReproducer(), llvm::CondOpInit::getAsString(), getBBFallenThrough(), getBitTestCondition(), getBranchCondString(), getBranchOpcode(), getCmp(), getCondCode(), llvm::SelectionDAG::getCondCode(), getCondition(), llvm::RISCVTargetLowering::getCustomCtpopCost(), llvm::TargetLoweringBase::getCustomCtpopCost(), llvm::MachineBasicBlock::getFallThrough(), getFauxShuffleMask(), getFPBranchKind(), llvm::InstCombiner::getFreelyInvertedImpl(), getHashValueImpl(), getIntrinsicCmp(), llvm::HexagonInstrInfo::getInvertedPredSense(), llvm::rdf::DataFlowGraph::getNextRelated(), getOnlyLiveSuccessor(), llvm::HexagonInstrInfo::getPredReg(), getPTest(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSelectCC(), getSETCC(), getSETCC(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSetCCVP(), llvm::MipsTargetLowering::getTypeForExtReturn(), llvm::ISD::getUnorderedFlavor(), getValueOnFirstIteration(), getX86XALUOOp(), guaranteesRegEqualsImmInBlock(), llvm::coro::BaseCloner::handleFinalSuspend(), handleOtherCmpSelSimplifications(), hasOnlySelectUsers(), hasProcessableCondition(), hoistConditionalLoadsStores(), hostParallelCallback(), if(), INITIALIZE_PASS(), llvm::AArch64InstrInfo::insertBranch(), llvm::ARCInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::AVRInstrInfo::insertBranch(), llvm::BPFInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::M68kInstrInfo::insertBranch(), llvm::MipsInstrInfo::insertBranch(), llvm::MSP430InstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::SPIRVInstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::TargetInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::XCoreInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranchAtInst(), llvm::XtensaInstrInfo::insertConstBranchAtInst(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::TargetInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), llvm::SIInstrInfo::insertVectorSelect(), llvm::isAlmostDeadIV(), isAnalyzableBB(), llvm::XtensaInstrInfo::isBranch(), isConditionTrueViaVFAndUF(), isGuaranteedNotToBeUndefOrPoison(), llvm::isImpliedByDomCondition(), isImpliedToBeAPowerOfTwoFromCond(), isKnownNonEqualFromContext(), llvm::isKnownToBeAPowerOfTwo(), isLoopNeverExecuted(), llvm::AArch64TTIImpl::isProfitableToSinkOperands(), llvm::X86TargetLowering::isTargetCanonicalSelect(), llvm::ISD::isTrueWhenEqual(), IsVPNOTEquivalent(), llvm::X86TargetLowering::isXAndYEqZeroPreferableToXAndYEqY(), jumpTableHasOtherUses(), llvm::SPIRVLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeFroundeven(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), LLVM_ATTRIBUTE_C_DEPRECATED(), LLVMSetCondition(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), llvm::LanaiTargetLowering::LowerBR_CC(), LowerBRCOND(), LowerBUILD_VECTORvXi1(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::RISCVTargetLowering::LowerOperation(), lowerSELECT(), llvm::LanaiTargetLowering::LowerSELECT_CC(), llvm::LanaiTargetLowering::LowerSETCC(), LowerSETCCCARRY(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), lowerVSELECTtoVectorShuffle(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowerXALUO(), llvm::PatternMatch::m_Select(), llvm::SDPatternMatch::m_Select(), llvm::PatternMatch::m_SelectCst(), llvm::SDPatternMatch::m_SelectLike(), llvm::SDPatternMatch::m_VSelect(), llvm::PatternMatch::LogicalOp_match< LHS, RHS, Opcode, Commutable >::match(), llvm::SDPatternMatch::MaxMin_match< LHS_P, RHS_P, Pred_t, Commutable, ExcludeChain >::match(), llvm::SDPatternMatch::smax_pred_ty::match(), llvm::SDPatternMatch::smin_pred_ty::match(), llvm::SDPatternMatch::umax_pred_ty::match(), llvm::SDPatternMatch::umin_pred_ty::match(), matchBitmaskMul(), llvm::CombinerHelper::matchCastOfSelect(), matchCondition(), matchSelectWithOptionalNotCond(), matchShiftULTCondition(), llvm::CombinerHelper::matchSimplifySelectToMinMax(), llvm::JumpThreadingPass::maybethreadThroughTwoBasicBlocks(), llvm::SMTSolver::mkIte(), llvm::InsertCFGStrategy::mutate(), narrowVectorSelect(), narrowVectorSelect(), needsLFTR(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), parseCC(), parseCond(), parseCond(), parseCondBranch(), parseCondBranch(), parseCondBranch(), parseCondBranch(), parseCondBranch(), parseCondBranch(), parseConstraintCode(), parseConstraintCode(), AbstractManglingParser< Derived, Alloc >::parseExpr(), llvm::parseWidenableBranch(), llvm::peelLoop(), llvm::PeelSingleBlockLoop(), llvm::ARMTargetLowering::PerformCMOVCombine(), PerformCMPZCombine(), performCSELCombine(), PerformCSETCombine(), llvm::AMDGPUTargetLowering::performCtlz_CttzCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformHWLoopCombine(), performORCombine(), performOrXorChainCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSETCCCombine(), performSETCCCombine(), performSetccMergeZeroCombine(), performSetCCPunpkCombine(), PerformVCMPCombine(), PerformVSELECTCombine(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::PredicateWithEdge::PredicateWithEdge(), llvm::HexagonInstrInfo::predOpcodeHasNot(), llvm::InstCombinerImpl::prepareWorklist(), llvm::JumpThreadingPass::processImpliedCondition(), processSwitch(), llvm::JumpThreadingPass::processThreadableEdges(), ProfileCondOpInit(), llvm::promoteCallWithVTableCmp(), recordCondition(), llvm::TargetInstrInfo::reduceLoopCount(), llvm::XtensaInstrInfo::removeBranch(), llvm::VPlanTransforms::removeBranchOnConst(), removeUndefIntroducingPredecessor(), llvm::TargetInstrInfo::replaceBranchWithTailCall(), replaceFoldableUses(), llvm::CondOpInit::resolveReferences(), llvm::AArch64InstrInfo::reverseBranchCondition(), llvm::ARCInstrInfo::reverseBranchCondition(), llvm::ARMBaseInstrInfo::reverseBranchCondition(), llvm::AVRInstrInfo::reverseBranchCondition(), llvm::CSKYInstrInfo::reverseBranchCondition(), llvm::HexagonInstrInfo::reverseBranchCondition(), llvm::LoongArchInstrInfo::reverseBranchCondition(), llvm::MipsInstrInfo::reverseBranchCondition(), llvm::MSP430InstrInfo::reverseBranchCondition(), llvm::PPCInstrInfo::reverseBranchCondition(), llvm::R600InstrInfo::reverseBranchCondition(), llvm::RISCVInstrInfo::reverseBranchCondition(), llvm::SIInstrInfo::reverseBranchCondition(), llvm::SparcInstrInfo::reverseBranchCondition(), llvm::SystemZInstrInfo::reverseBranchCondition(), llvm::TargetInstrInfo::reverseBranchCondition(), llvm::VEInstrInfo::reverseBranchCondition(), llvm::WebAssemblyInstrInfo::reverseBranchCondition(), llvm::X86InstrInfo::reverseBranchCondition(), llvm::XCoreInstrInfo::reverseBranchCondition(), llvm::XtensaInstrInfo::reverseBranchCondition(), llvm::DropUnnecessaryAssumesPass::run(), llvm::RewriteStatepointsForGC::runOnFunction(), OffsetResult::select(), llvm::CondCodeSDNode::SelectionDAG, shouldConvertSelectOfConstantsToMath(), shouldInsertFreeze(), simplifyBranchConditionForVFAndUF(), simplifyCmpSelCase(), simplifyCmpSelFalseCase(), simplifyCmpSelTrueCase(), SimplifyCondBranchToCondBranch(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyOneLoop(), llvm::SelectionDAG::simplifySelect(), llvm::simplifySelectInst(), simplifySelectInst(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifySelectWithFCmp(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), simplifyUsingControlFlow(), skipTrivialSelect(), llvm::SplitBlockAndInsertIfElse(), llvm::SplitBlockAndInsertIfElse(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockAndInsertIfThenElse(), llvm::SplitBlockAndInsertIfThenElse(), llvm::SplitBlockAndInsertIfThenElse(), llvm::SplitBlockAndInsertIfThenElse(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitEdge(), splitLoopBound(), splitVSETCC(), STATISTIC(), takeInexpensiveLog2(), targetParallelCallback(), threadCmpOverSelect(), transformToIndexedCompare(), tryDemorganOfBooleanCondition(), TryMatchTrue(), trySwitchToSelect(), llvm::VPRecipeBuilder::tryToCreatePartialReduction(), tryToFoldExtendSelectLoad(), llvm::JumpThreadingPass::tryToUnfoldSelectInCurrBB(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), updateBranches(), llvm::MachineBasicBlock::updateTerminator(), useInversedSetcc(), llvm::HexagonInstrInfo::validateBranchCond(), llvm::versionCallSite(), versionCallSiteWithCond(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitBranchInst(), llvm::Interpreter::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), visitCmpBlock(), llvm::InstCombinerImpl::visitExtractValueInst(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSub(), llvm::SelectionDAGBuilder::visitSwitchCase(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::Interpreter::visitSwitchInst(), and llvm::wouldInstructionBeTriviallyDead().
false
return false
Definition at line 84 of file RISCVRedundantCopyElimination.cpp.
Opc
auto Opc = Cond[0].getImm()
Definition at line 77 of file RISCVRedundantCopyElimination.cpp.
Referenced by AddCombineTo64bitMLAL(), llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsSETargetLowering::addMSAIntType(), llvm::GISelInstProfileBuilder::addNodeIDOpcode(), llvm::TargetLoweringBase::AddPromotedToType(), addSrcModifiersAndSrc(), llvm::RISCVRegisterInfo::adjustReg(), llvm::MipsInstrInfo::adjustStackPtr(), llvm::MipsSEInstrInfo::adjustStackPtr(), allUsesTruncate(), llvm::HexagonInstrInfo::analyzeCompare(), llvm::PPCInstrInfo::analyzeCompare(), llvm::CombinerHelper::applyFunnelShiftToRotate(), llvm::AMDGPURegisterBankInfo::applyMappingBFE(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::ARCTargetLowering::ARCTargetLowering(), areCombinableOperations(), llvm::RegBankSelect::assignInstr(), llvm::AtomicSDNode::AtomicSDNode(), AVRDAGToDAGISel::select< ISD::LOAD >(), AVRDAGToDAGISel::select< ISD::STORE >(), llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::BinaryOpc_match(), BinopElts::BinopElts(), bitOpWithConstantIsReducible(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::MachineIRBuilder::buildAssertInstr(), buildBufferLoad(), llvm::CSEMIRBuilder::buildConstant(), buildEpilogRestore(), llvm::CSEMIRBuilder::buildFConstant(), buildFromShuffleMostly(), llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstr(), buildMUBUFOffsetLoadStore(), llvm::ARMBaseInstrInfo::buildOutlinedFrame(), buildPrologSpill(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), calcNextStatus(), canConvert2Copy(), canEnableCoalescing(), canFoldIntoCSel(), canonicalizeShuffleWithOp(), llvm::HexagonInstrInfo::changeAddrMode_abs_io(), llvm::HexagonInstrInfo::changeAddrMode_io_abs(), llvm::HexagonInstrInfo::changeAddrMode_io_pi(), llvm::HexagonInstrInfo::changeAddrMode_io_rr(), llvm::HexagonInstrInfo::changeAddrMode_pi_io(), llvm::HexagonInstrInfo::changeAddrMode_rr_io(), llvm::HexagonInstrInfo::changeAddrMode_rr_ur(), llvm::HexagonInstrInfo::changeAddrMode_ur_rr(), CheckOpcode(), llvm::X86InstrInfo::classifyLEAReg(), llvm::ConcreteOperator< SuperClass, Opc >::classof(), llvm::ConcreteOperator< SuperClass, Opc >::classof(), collectVOPModifiers(), combineAcrossLanesIntrinsic(), combineAndOrForCcmpCtest(), combineArithReduction(), combineBinOpOfExtractToReduceTree(), combineBinOpToReduce(), combineBitcastToBoolVector(), combineBitOpWithMOVMSK(), combineBitOpWithPACK(), combineBitOpWithShift(), combineConcatVectorOps(), combineDeMorganOfBoolean(), combineFP_ROUND(), combineMaskedStore(), combineMul(), combineOrXorWithSETCC(), combinePExtTruncate(), combinePMULH(), combineSCALAR_TO_VECTOR(), combineSetCCAtomicArith(), combineShiftToPMULH(), combineShuffleToAddSubOrFMAddSub(), combineStore(), combineSVEReductionFP(), combineSVEReductionInt(), combineSVEReductionOrderedFP(), combineToVCPOP(), combineToVWMACC(), combineTruncToVnclip(), combineVPMADD(), combineVqdotAccum(), combineVWADDSUBWSelect(), combineX86AddSub(), combineX86ShuffleChain(), llvm::RISCVInstrInfo::commuteInstructionImpl(), llvm::SIInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), CompressEVEXImpl(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SITargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownFPClass(), convertALUrr2ALUri(), llvm::AMDGPUDisassembler::convertDPP8Inst(), convertFPToInt(), convertIntLogicToFPLogic(), convertMergedOpToPredOp(), llvm::AArch64InstrInfo::convertToFlagSettingOpc(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::AMDGPUDisassembler::convertTrue16OpSel(), llvm::AMDGPUDisassembler::convertVOP3DPPInst(), llvm::AMDGPUDisassembler::convertVOP3PDPPInst(), llvm::AMDGPUDisassembler::convertVOPC64DPPInst(), llvm::AMDGPUDisassembler::convertVOPCDPPInst(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::AVRInstrInfo::copyPhysReg(), llvm::LoongArchInstrInfo::copyPhysReg(), llvm::M68kInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MSP430InstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysRegVector(), llvm::ARMBaseInstrInfo::copyToCPSR(), costAndCollectOperands(), llvm::GISelCSEInfo::countOpcodeHit(), llvm::MCBinaryExpr::create(), llvm::MCUnaryExpr::create(), createAtomicLibcall(), llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateBinOpFMF(), createCall(), llvm::BinaryOperator::CreateDisjoint(), llvm::BinaryOperator::CreateDisjoint(), llvm::BinaryOperator::CreateExact(), llvm::BinaryOperator::CreateExact(), createLoadLR(), llvm::IRBuilderBase::CreateLogicalOp(), createLogicalOp(), llvm::createMemLibcall(), llvm::IRBuilderBase::CreateNAryOp(), llvm::BinaryOperator::CreateNSW(), llvm::BinaryOperator::CreateNSW(), llvm::BinaryOperator::CreateNUW(), llvm::BinaryOperator::CreateNUW(), createStoreLR(), llvm::IRBuilderBase::CreateUnOp(), llvm::BinaryOperator::CreateWithCopiedFlags(), llvm::UnaryOperator::CreateWithCopiedFlags(), llvm::BinaryOperator::CreateWithFMF(), cvtVOP3DstOpSelOnly(), DecodeAddrMode2IdxInstruction(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::HexagonInstrInfo::doesNotReturn(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::emitARMRegPlusImmediate(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), llvm::MipsTargetStreamer::emitEmptyDelaySlot(), llvm::ARCFrameLowering::emitEpilogue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::emitFrameOffset(), emitFrameOffsetAdj(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::XtensaAsmPrinter::emitInstruction(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), emitLoad(), EmitMaskedTruncSStore(), emitNop(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), emitRegUpdate(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::M68kFrameLowering::emitSPUpdate(), llvm::X86FrameLowering::emitSPUpdate(), emitStore(), llvm::emitT2RegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::AArch64TargetLowering::EmitTileLoad(), EmitTruncSStore(), llvm::AArch64TargetLowering::EmitZAInstr(), llvm::HexagonMCCodeEmitter::encodeSingleInstruction(), llvm::BitTracker::MachineEvaluator::evaluate(), llvm::HexagonEvaluator::evaluate(), llvm::HexagonEvaluator::evaluate(), EvaluateInDifferentTypeImpl(), Expand64BitScalarArithmetic(), Expand64BitShift(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandFMINIMUM_FMAXIMUM(), llvm::TargetLowering::expandFMINIMUMNUM_FMAXIMUMNUM(), llvm::AArch64_IMM::expandMOVImm(), expandMOVImmSimple(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::MipsSEInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandVGatherPseudo(), llvm::SIInstrInfo::findCommutedOpIndices(), llvm::HexagonInstrInfo::findLoopInstr(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::AArch64PrologueEpilogueCommon::fixupCalleeSaveRestoreStackOffset(), fnegFoldsIntoOp(), fnegFoldsIntoOpcode(), llvm::ConstantFolder::FoldBinOp(), llvm::InstSimplifyFolder::FoldBinOp(), llvm::IRBuilderFolder::FoldBinOp(), llvm::NoFolder::FoldBinOp(), llvm::TargetFolder::FoldBinOp(), llvm::ConstantFolder::FoldBinOpFMF(), llvm::InstSimplifyFolder::FoldBinOpFMF(), llvm::IRBuilderFolder::FoldBinOpFMF(), llvm::NoFolder::FoldBinOpFMF(), llvm::TargetFolder::FoldBinOpFMF(), llvm::InstCombinerImpl::foldBinOpOfSelectAndCastOfSelectCondition(), llvm::InstCombinerImpl::foldBinOpShiftWithShift(), llvm::InstCombinerImpl::foldBinopWithRecurrence(), llvm::foldBranchToCommonDest(), llvm::ConstantFolder::FoldExactBinOp(), llvm::InstSimplifyFolder::FoldExactBinOp(), llvm::IRBuilderFolder::FoldExactBinOp(), llvm::NoFolder::FoldExactBinOp(), llvm::TargetFolder::FoldExactBinOp(), llvm::AMDGPUTargetLowering::foldFreeOpFromSelect(), llvm::SIInstrInfo::foldImmediate(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantFolder::FoldNoWrapBinOp(), llvm::InstSimplifyFolder::FoldNoWrapBinOp(), llvm::IRBuilderFolder::FoldNoWrapBinOp(), llvm::NoFolder::FoldNoWrapBinOp(), llvm::TargetFolder::FoldNoWrapBinOp(), llvm::InstCombinerImpl::foldPHIArgBinOpIntoPHI(), foldReduceOperandViaVQDOT(), foldSelectICmpAnd(), foldToSaturated(), llvm::ConstantFolder::FoldUnOpFMF(), llvm::InstSimplifyFolder::FoldUnOpFMF(), llvm::IRBuilderFolder::FoldUnOpFMF(), llvm::NoFolder::FoldUnOpFMF(), llvm::TargetFolder::FoldUnOpFMF(), foldVGPRCopyIntoRegSequence(), llvm::HexagonPacketizerList::foundLSInPacket(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), genAlternativeDpCodeSequence(), llvm::LoongArchMatInt::generateInstSeq(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqImpl(), GenerateSignBits(), genFNegatedMAD(), getAArch64XALUOOp(), llvm::TargetInstrInfo::getAccumulatorReassociationPatterns(), llvm::ARM_AM::getAM2Opc(), llvm::ARM_AM::getAM3Opc(), llvm::ARM_AM::getAM5FP16Opc(), llvm::ARM_AM::getAM5Opc(), llvm::getAVLPos(), getAVX2GatherNode(), getBaseAddressOpcode(), llvm::AMDGPU::getBitOp2(), llvm::SelectionDAG::getBlockAddress(), getBMIMatchingOp(), getBranchDisplacementBits(), llvm::AMDGPU::getCanBeVOPD(), getCmpOperandFoldingProfit(), getComplementOpc(), getConcreteOpcode(), llvm::AVRInstrInfo::getCondFromBranchOpc(), llvm::RISCVInstrInfo::getCondFromBranchOpc(), llvm::HexagonInstrInfo::getCondOpcode(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::WebAssembly::GetDefaultP2Align(), llvm::WebAssembly::GetDefaultP2AlignAny(), llvm::getDefSrcRegIgnoringCopies(), llvm::AArch64InstrInfo::getElementSizeForOpcode(), getExtendForIntVecReduction(), GetExtendHigh(), getExtendOp(), llvm::X86InstrInfo::getFMA3OpcodeToCommuteOperands(), getFNEGPatterns(), llvm::AMDGPU::getFPDstSelType(), getFPFusedMultiplyPatterns(), llvm::RTLIB::getFPLibCall(), llvm::SelectionDAG::getFrameIndex(), llvm::SelectionDAG::getGlobalAddress(), getIdentityValueFor32BitWaveReduction(), getIdentityValueFor64BitWaveReduction(), getImmScale(), getImplicitCondFromMI(), getInsertVecEltOpInfo(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::M68kRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::RISCVRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::LanaiTTIImpl::getIntImmCostInst(), llvm::HexagonSubtarget::getIntrinsicId(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::HexagonInstrInfo::getInvertedPredicatedOpcode(), llvm::HexagonInstrInfo::getInvertedPredSense(), llvm::getITInstrPredicate(), llvm::SystemZTargetLowering::getJumpConditionMergingParams(), llvm::X86TargetLowering::getJumpConditionMergingParams(), llvm::SelectionDAG::getJumpTable(), llvm::sandboxir::getLLVMBinaryOp(), llvm::sandboxir::getLLVMCastOp(), llvm::sandboxir::getLLVMUnaryOp(), llvm::AArch64InstrInfo::getLoadStoreImmIdx(), getLogicalBitOpcode(), llvm::X86InstrInfo::getMachineCombinerPatterns(), getMaddPatterns(), llvm::AMDGPU::getMAIIsDGEMM(), llvm::AMDGPU::getMAIIsGFX940XDL(), llvm::AMDGPU::getMaskedMIMGOp(), llvm::getMaskPos(), llvm::getMatchingCondBranchOpcode(), getMatchingNonSExtOpcode(), getMatchingPairOpcode(), getMatchingWideOpcode(), llvm::SIInstrInfo::getMemOperandsWithOffsetWidth(), llvm::AArch64InstrInfo::getMemScale(), llvm::AMDGPU::getMIMGBaseOpcode(), llvm::AMDGPU::getMIMGG16MappingInfo(), llvm::AMDGPU::getMIMGInfo(), getMiscPatterns(), getMnemonic(), llvm::AMDGPU::getMTBUFBaseOpcode(), llvm::AMDGPU::getMTBUFElements(), llvm::AMDGPU::getMTBUFHasSoffset(), llvm::AMDGPU::getMTBUFHasSrsrc(), llvm::AMDGPU::getMTBUFHasVAddr(), llvm::AMDGPU::getMUBUFBaseOpcode(), llvm::AMDGPU::getMUBUFElements(), llvm::AMDGPU::getMUBUFHasSoffset(), llvm::AMDGPU::getMUBUFHasSrsrc(), llvm::AMDGPU::getMUBUFHasVAddr(), llvm::AMDGPU::getMUBUFIsBufferInv(), llvm::AMDGPU::getMUBUFTfe(), llvm::PPCTargetLowering::getNegatedExpression(), llvm::X86TargetLowering::getNegatedExpression(), getNewFMAAKInst(), getNewFMAInst(), getNewFMAMKInst(), getNewOpcFromTable(), llvm::X86::getNFVariant(), getNonFlagSettingVariant(), llvm::X86::getNonNDVariant(), llvm::ARMBaseInstrInfo::getNumMicroOps(), getNumMicroOpsSingleIssuePlusExtras(), getOffenMUBUFLoad(), getOffenMUBUFStore(), getOffsetMUBUFLoad(), getOffsetMUBUFStore(), getOModValue(), llvm::TargetInstrInfo::getOpcodeAfterMemoryUnfold(), llvm::X86InstrInfo::getOpcodeAfterMemoryUnfold(), getOpcodeWithCC(), getOppositeBranchOpc(), llvm::Mips16InstrInfo::getOppositeBranchOpc(), llvm::MipsInstrInfo::getOppositeBranchOpc(), llvm::MipsSEInstrInfo::getOppositeBranchOpc(), llvm::RTLIB::getOUTLINE_ATOMIC(), getOutlineAtomicLibcall(), llvm::ARMBaseInstrInfo::getOutliningTypeImpl(), llvm::TargetLoweringBase::getPartialReduceMLAAction(), getPostIndexedLoadStoreOpcode(), getPostIndexedOpcode(), getPPCStrictOpcode(), getPrefetchNode(), getPreIndexedLoadStoreOpcode(), getPreIndexedOpcode(), getRealVLDOpcode(), getRealVSTOpcode(), llvm::getReductionForBinop(), llvm::getReductionIdentity(), getRegFromMIA(), llvm::AMDGPUInstPrinter::getRegisterName(), getRelevantOperands(), llvm::AMDGPU::RegBankLegalizeRules::getRulesForOpc(), getSaveExecOp(), getSBufferLoadCorrespondingBufferLoadOpcode(), getScatterNode(), getSHXADDShiftAmount(), getSHXADDUWShiftAmount(), llvm::AMDGPU::getSMEMIsBuffer(), llvm::RTLIB::getSYNC(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getTargetVShiftUniformOpcode(), llvm::AMDGPU::getTemporalHintType(), getTestBitReg(), getTransformOpcode(), getUnconditionalBrDisp(), getUnconditionalBrDisp(), getUnconditionalBrDisp(), llvm::ARMBaseInstrInfo::getUnindexedOpcode(), llvm::ARMInstrInfo::getUnindexedOpcode(), llvm::Thumb1InstrInfo::getUnindexedOpcode(), llvm::Thumb2InstrInfo::getUnindexedOpcode(), llvm::AArch64InstrInfo::getUnscaledLdSt(), getUpdatingLSMultipleOpcode(), getVecReduceOpcode(), llvm::getVectorSplat(), getVLDSTRegisterUpdateOpcode(), llvm::AMDGPU::getVOP1IsSingle(), llvm::AMDGPU::getVOP2IsSingle(), llvm::AMDGPU::getVOP3IsSingle(), llvm::AMDGPU::getVOPDOpcode(), getVShift(), llvm::AMDGPU::getWMMAIsXDL(), guaranteesRegEqualsImmInBlock(), llvm::AMDGPU::hasAny64BitVGPROperands(), llvm::AArch64InstrInfo::hasUnscaledLdStOffset(), if(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS_END(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::CSKYInstrInfo::insertBranch(), llvm::M68kInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::XCoreInstrInfo::insertBranch(), llvm::insertMultibyteShift(), llvm::MipsInstrInfo::insertNop(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), insertSEH(), llvm::AArch64InstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), llvm::PPCInstrInfo::instrHasImmForm(), llvm::rdf::CopyPropagation::interpretAsCopy(), inverseMinMax(), inverseMinMax(), invertFMAOpcode(), is32bitWaveReduceOperation(), llvm::PPCInstrInfo::isADDIInstrEligibleForFolding(), llvm::PPCInstrInfo::isADDInstrEligibleForFolding(), isAddSubOrSubAdd(), isAmbiguous(), isAMXOpcode(), isANDOpcode(), isAndOrOfSetCCs(), isAndOrOfSetCCs(), llvm::WebAssembly::isArgument(), isArithmetic(), isArithmeticOp(), llvm::RISCVInstrInfo::isAssociativeAndCommutative(), llvm::SystemZInstrInfo::isAssociativeAndCommutative(), llvm::AMDGPU::isAsyncStore(), isBitfieldExtractOp(), isBitfieldExtractOpFromAnd(), isBitfieldExtractOpFromSExtInReg(), isBitfieldExtractOpFromShr(), llvm::MipsInstrInfo::isBranchWithImm(), llvm::MipsSEInstrInfo::isBranchWithImm(), llvm::WebAssembly::isBrTable(), isBSwapHWordElement(), llvm::WebAssembly::isCallDirect(), llvm::WebAssembly::isCallIndirect(), llvm::WebAssembly::isCatch(), llvm::WebAssembly::isCatchAll(), llvm::SIInstrInfo::isCBranchVCCZRead(), isCombineInstrCandidate(), isCombineInstrCandidate32(), isCombineInstrCandidate64(), isCombineInstrSettingFlag(), isCondBranchOpcode(), isCondBranchOpcode(), isCondBranchOpcode(), llvm::isCondBranchOpcode(), IsConditionalBranch(), llvm::WebAssembly::isConst(), llvm::BuildVectorSDNode::isConstant(), llvm::WebAssembly::isCopy(), isCtlzOpc(), isCttzOpc(), llvm::AMDGPU::isCvt_F32_Fp8_Bf8_e64(), llvm::ARMTargetLowering::isDesirableToTransformToIntegerOp(), llvm::PPCTargetLowering::isDesirableToTransformToIntegerOp(), llvm::AMDGPU::isDPALU_DPP32BitOpc(), llvm::AMDGPU::isDPMACCInstruction(), llvm::WebAssembly::isEndMarker(), llvm::WebAssemblyInstrInfo::isExplicitTargetIndexDef(), isFADD(), isFCondBranchOpcode(), isFloatingPointOpcodeDef(), isFloatingPointOpcodeUse(), isFloatingPointWaveReduceOperation(), isFMUL(), isFNEG(), isFoldableUseOfShuffle(), isFSUB(), llvm::AMDGPU::isGenericAtomic(), llvm::TargetInstrInfo::isGenericAtomicRMWOpcode(), llvm::TargetInstrInfo::isGenericOpcode(), llvm::SIInstrInfo::isGFX12CacheInvOrWBInst(), llvm::RISCVInstrInfo::isHighLatencyDef(), llvm::SIInstrInfo::isHighLatencyDef(), isI32CondBranchOpcode(), isi32Load(), isi32Store(), isI64CondBranchOpcode(), llvm::PPCInstrInfo::isImmInstrEligibleForFolding(), isIndirectBranchOpcode(), isIndirectBranchOpcode(), llvm::isIndirectBranchOpcode(), isIndirectBranchOrTailCall(), llvm::isIndirectCall(), llvm::isIndirectCallOpcode(), isInStreamingCallSiteRegion(), llvm::AMDGPU::isInvalidSingleUseConsumerInst(), llvm::AMDGPU::isInvalidSingleUseProducerInst(), isJumpOpcode(), llvm::isJumpTableBranchOpcode(), isLaneInsensitive(), llvm::X86TTIImpl::isLegalAltInstr(), llvm::SIInstrInfo::isLegalRegOperand(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::SIInstrInfo::isLegalToSwap(), isLoadAbsSet(), llvm::MipsSEInstrInfo::isLoadFromStackSlot(), isLoadSingle(), llvm::WebAssembly::isLocalGet(), llvm::WebAssembly::isLocalSet(), llvm::WebAssembly::isLocalTee(), llvm::SIInstrInfo::isLowLatencyInstruction(), isM68kLogicalCmp(), llvm::AMDGPU::isMAC(), llvm::WebAssembly::isMarker(), isMemOPCandidate(), isMergeableIndexLdSt(), isMergeableLdStUpdate(), isMergePassthruOpcode(), llvm::isMovRegOpcode(), isNonFoldablePartialRegisterLoad(), isOpcWithIntImmediate(), isOpcWithIntImmediate(), isOpcWithIntImmediate(), isOpcWithIntImmediate(), llvm::ISD::isOverflowIntrOpRes(), llvm::AMDGPU::isPackedFP32Inst(), llvm::isPackingSupportOpcode(), llvm::RISCVInstrInfo::isPairableLdStInstOpc(), llvm::TargetLoweringBase::isPartialReduceMLALegalOrCustom(), llvm::AMDGPU::isPermlane16(), llvm::isPopOpcode(), llvm::isPreISelGenericFloatingPointOpcode(), isPromotableZeroStoreInst(), llvm::AArch64InstrInfo::isPTestLikeOpcode(), llvm::isPTrueOpcode(), llvm::isPushOpcode(), isRegCondBranchOpcode(), isRestoreCall(), isRewritableImplicitDef(), llvm::WebAssembly::isScalarConst(), llvm::AArch64InstrInfo::isSEHInstruction(), llvm::isSEHInstruction(), isSeveralBitsExtractOpFromShr(), llvm::isSpeculationBarrierEndBBOpcode(), llvm::X86TargetLowering::isSplatValueForTargetNode(), llvm::MipsSEInstrInfo::isStoreToStackSlot(), isStride64(), llvm::isSubImmOpcode(), isSystemInstr(), isT1i32Load(), isT1i32Store(), isT2i32Load(), isT2i32Store(), isTailCallOpcode(), isTailCallOpcode(), llvm::WebAssembly::isTee(), llvm::AMDGPU::isTensorStore(), isTransformable(), llvm::AMDGPU::isTrue16Inst(), llvm::WebAssembly::isTry(), llvm::AArch64TargetLowering::isTypeDesirableForOp(), llvm::X86TargetLowering::isTypeDesirableForOp(), isUncondBranchOpcode(), isUncondBranchOpcode(), isUncondBranchOpcode(), llvm::isUncondBranchOpcode(), IsUnconditionalJump(), llvm::AArch64PrologueEpilogueCommon::isVGInstruction(), isVLDfixed(), llvm::AMDGPU::isVOPC64DPP(), llvm::AMDGPU::isVOPCAsmOnly(), llvm::AMDGPU::isVOPD(), llvm::VPCastIntrinsic::isVPCast(), llvm::isVPTOpcode(), isVSTfixed(), isVSXSwap(), llvm::AArch64InstrInfo::isWhileOpcode(), isX86LogicalCmp(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBufferStore(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::AMDGPULegalizerInfo::legalizeSBufferLoad(), llvm::TargetLowering::LegalizeSetCCCondCode(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::M68kInstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadStoreTileReg(), LowerADDSUBO_CARRY(), lowerAtomicArith(), LowerAVXExtend(), llvm::LegalizerHelper::lowerBitCount(), LowerBR_CC(), lowerBUILD_VECTOR(), lowerBuildVectorOfConstants(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), LowerCTLZ(), llvm::AMDGPUTargetLowering::lowerCTLZResults(), llvm::PPCRegisterInfo::lowerDMRRestore(), llvm::PPCRegisterInfo::lowerDMRSpilling(), lowerDSPIntr(), LowerEXTEND_VECTOR_INREG(), lowerFMAXIMUM_FMINIMUM(), LowerFMINIMUM_FMAXIMUM(), llvm::LegalizerHelper::lowerFMinimumMaximum(), lowerFP_TO_INT_SAT(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), LowerINTRINSIC_W_CHAIN(), llvm::LegalizerHelper::lowerMemCpyFamily(), lowerMSABinaryBitImmIntr(), lowerMSACopyIntr(), llvm::HexagonTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerOperationWrapper(), llvm::SITargetLowering::LowerReturn(), LowerSELECT_CC(), LowerShift(), llvm::MSP430TargetLowering::LowerShifts(), llvm::AMDGPUCallLowering::lowerTailCall(), lowerTileCopy(), lowerToAddSubOrFMAddSub(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::HexagonTargetLowering::LowerUAddSubOCarry(), llvm::HexagonTargetLowering::LowerVECTOR_SHIFT(), lowerVECTOR_SHUFFLE(), LowerVectorINT_TO_FP(), LowerVSETCC(), LowerVSETCC(), lowerVZIP(), lowerWaveReduce(), llvm::SDPatternMatch::m_BinOp(), llvm::SDPatternMatch::m_c_BinOp(), llvm::SDPatternMatch::m_c_ChainedBinOp(), llvm::SDPatternMatch::m_c_TernaryOp(), llvm::SDPatternMatch::m_ChainedBinOp(), llvm::SDPatternMatch::m_ChainedUnaryOp(), llvm::SDPatternMatch::m_TernaryOp(), llvm::SDPatternMatch::m_UnaryOp(), macToMad(), llvm::Mips16InstrInfo::makeFrame(), llvm::AMDGPU::mapWMMA2AddrTo3AddrOpcode(), llvm::AMDGPU::mapWMMA3AddrTo2AddrOpcode(), llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::match(), llvm::VPMatchContext::match(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchMulOBy2(), llvm::CombinerHelper::matchReassocCommBinOp(), llvm::CombinerHelper::matchRedundantNegOperands(), matchRoundingOp(), llvm::maySafelyIgnoreMask(), maySpeculateLanes(), llvm::SIInstrInfo::mayWriteLDSThroughDMA(), llvm::MemIntrinsicSDNode::MemIntrinsicSDNode(), llvm::MemSDNode::MemSDNode(), llvm::M68kFrameLowering::mergeSPUpdates(), minMaxOpcToMin3Max3Opc(), minMaxToCompare(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::LegalizerHelper::moreElementsVector(), llvm::SelectionDAG::MorphNodeTo(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::SIInstrInfo::moveToVALUImpl(), llvm::RISCVInstrInfo::mulImm(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), needsStackFrame(), llvm::SDPatternMatch::Opcode_match::Opcode_match(), llvm::rdf::operator<<(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::optimizeTerminators(), parseCondBranch(), performANDCombine(), performBITCASTCombine(), performBranchToCommonDestFolding(), performBuildShuffleExtendCombine(), performCMovFPCombine(), llvm::AMDGPUTargetLowering::performCtlz_CttzCombine(), performCustomAdjustments(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::MipsTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDivRemCombine(), performDSPShiftCombine(), PerformExtendCombine(), performFADDCombine(), PerformFADDVCMLACombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), performGLD1Combine(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), performLD1Combine(), performSETCC_BITCASTCombine(), performSIGN_EXTEND_INREGCombine(), performSignExtendInRegCombine(), performSVEAndCombine(), PerformVSetCCToVCTPCombine(), performVWADDSUBW_VLCombine(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::RISCVTargetLowering::preferScalarizeSplat(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::sandboxir::SeedContainer::print(), llvm::X86InstPrinterCommon::printCondCode(), llvm::WebAssemblyInstPrinter::printInst(), llvm::AMDGPUInstPrinter::printRegOperand(), llvm::SIInstrInfo::removeModOperands(), llvm::X86InstrInfo::replaceBranchWithTailCall(), ReplaceLongIntrinsic(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), scalarizeExtractedBinOp(), scaleOffset(), llvm::SCEVOperand::SCEVOperand(), llvm::SDNode::SDNode(), SearchOptions::SearchOptions(), llvm::AMDGPUDAGToDAGISel::Select(), llvm::RISCVDAGToDAGISel::Select(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), llvm::GlobalAddressSDNode::SelectionDAG, llvm::MachineSDNode::SelectionDAG, llvm::RISCVDAGToDAGISel::selectSETCC(), llvm::TargetLoweringBase::setOperationPromotedToType(), llvm::TargetLoweringBase::setPartialReduceMLAAction(), llvm::TargetLoweringBase::setPartialReduceMLAAction(), llvm::GISelCSEInfo::shouldCSE(), llvm::CSEConfigBase::shouldCSEOpc(), llvm::CSEConfigConstantOnly::shouldCSEOpc(), llvm::CSEConfigFull::shouldCSEOpc(), shouldExpandCmpArithRMWInIR(), llvm::SelectionDAGBuilder::shouldKeepJumpConditionsTogether(), llvm::ARMTargetLowering::shouldReassociateReduction(), llvm::LoongArchTargetLowering::shouldScalarizeBinop(), llvm::RISCVTargetLowering::shouldScalarizeBinop(), llvm::X86TargetLowering::shouldScalarizeBinop(), shouldScheduleVOPDAdjacent(), llvm::SelectionDAG::SignBitIsZeroFP(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::LoongArchTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyDivRem(), llvm::RISCVInstrInfo::simplifyInstruction(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifySVEIntrinsicBinOp(), llvm::SITargetLowering::SITargetLowering(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), spillVGPRtoAGPR(), llvm::SPIRVLegalizerInfo::SPIRVLegalizerInfo(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), llvm::SITargetLowering::splitBinaryVectorOp(), llvm::VETargetLowering::splitMaskArithmetic(), llvm::SITargetLowering::splitTernaryVectorOp(), llvm::SITargetLowering::splitUnaryVectorOp(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::M68kInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), supportsMin3Max3(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::TernaryOpc_match(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), tryCompressVPMOVPattern(), tryCopyWithNegation(), tryDemorganOfBooleanCondition(), llvm::InstCombinerImpl::tryFoldInstWithCtpopWithNot(), tryFoldSelectIntoOp(), TryMULWIDECombine(), tryOptimizeLEAtoMOV(), llvm::CombinerHelper::tryReassocBinOp(), llvm::RISCVDAGToDAGISel::trySignedBitfieldExtract(), llvm::RISCVDAGToDAGISel::trySignedBitfieldInsertInSign(), llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldExtract(), llvm::RISCVDAGToDAGISel::tryUnsignedBitfieldInsertInZero(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::UnaryOpc_match(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::HexagonPacketizerList::useCalleesSP(), llvm::HexagonPacketizerList::useCallersSP(), usesAllOnesMask(), verifyCTRBranch(), VerifyLowRegs(), llvm::X86TargetLowering::X86TargetLowering(), llvm::CSEConfigConstantOnly::~CSEConfigConstantOnly(), and llvm::CSEConfigFull::~CSEConfigFull().
TBB
const SmallVectorImpl<MachineOperand> MachineBasicBlock* TBB
Initial value:
{
  assert(Cond.size() == 3 && "Unexpected number of operands")
Definition at line 74 of file RISCVRedundantCopyElimination.cpp.
Referenced by llvm::MipsInstrInfo::adjustStackPtr(), llvm::AArch64InstrInfo::analyzeBranch(), llvm::ARCInstrInfo::analyzeBranch(), llvm::ARMBaseInstrInfo::analyzeBranch(), llvm::AVRInstrInfo::analyzeBranch(), llvm::BPFInstrInfo::analyzeBranch(), llvm::CSKYInstrInfo::analyzeBranch(), llvm::HexagonInstrInfo::analyzeBranch(), llvm::LoongArchInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::analyzeBranch(), llvm::MipsInstrInfo::analyzeBranch(), llvm::MipsInstrInfo::analyzeBranch(), llvm::MSP430InstrInfo::analyzeBranch(), llvm::NVPTXInstrInfo::analyzeBranch(), llvm::PPCInstrInfo::analyzeBranch(), llvm::R600InstrInfo::analyzeBranch(), llvm::RISCVInstrInfo::analyzeBranch(), llvm::SIInstrInfo::analyzeBranch(), llvm::SparcInstrInfo::analyzeBranch(), llvm::SPIRVInstrInfo::analyzeBranch(), llvm::SystemZInstrInfo::analyzeBranch(), llvm::TargetInstrInfo::analyzeBranch(), llvm::VEInstrInfo::analyzeBranch(), llvm::WebAssemblyInstrInfo::analyzeBranch(), llvm::X86InstrInfo::analyzeBranch(), llvm::XCoreInstrInfo::analyzeBranch(), llvm::XtensaInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::AnalyzeBranchImpl(), llvm::SIInstrInfo::analyzeBranchImpl(), llvm::AArch64InstrInfo::analyzeLoopForPipelining(), llvm::RISCVInstrInfo::analyzeLoopForPipelining(), assert(), llvm::MachineBasicBlock::canSplitCriticalEdge(), createDedicatedExit(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), llvm::SelectionDAGBuilder::FindMergedConditions(), FixTail(), getBBFallenThrough(), getBranchHint(), llvm::MachineBasicBlock::getFallThrough(), getFallThroughMBB(), guaranteesRegEqualsImmInBlock(), if(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::AArch64InstrInfo::insertBranch(), llvm::ARCInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::AVRInstrInfo::insertBranch(), llvm::BPFInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::M68kInstrInfo::insertBranch(), llvm::MipsInstrInfo::insertBranch(), llvm::MSP430InstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::SPIRVInstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::TargetInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::XCoreInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranch(), llvm::XtensaInstrInfo::insertBranchAtInst(), isAnalyzableBB(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::RISCVInstrInfo::optimizeCondBranch(), llvm::PeelSingleBlockLoop(), STATISTIC(), updateBranches(), and llvm::MachineBasicBlock::updateTerminator().