LLVM: lib/Target/RISCV/RISCVSubtarget.cpp File Reference
RISCVSubtarget.cpp File Reference
#include "RISCVSubtarget.h"
#include "GISel/RISCVCallLowering.h"
#include "GISel/RISCVLegalizerInfo.h"
#include "RISCV.h"
#include "RISCVFrameLowering.h"
#include "RISCVSelectionDAGInfo.h"
#include "RISCVTargetMachine.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "RISCVGenSubtargetInfo.inc"
#include "RISCVGenMacroFusion.inc"
#include "RISCVGenSearchableTables.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::RISCVTuneInfoTable
Macros
#define DEBUG_TYPE "riscv-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
#define GET_RISCV_MACRO_FUSION_PRED_IMPL
#define GET_RISCVTuneInfoTable_IMPL
Variables
static cl::opt< unsigned > RVVVectorLMULMax ("riscv-v-fixed-length-vector-lmul-max", cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported."), cl::init(8), cl::Hidden)
static cl::opt< bool > RISCVDisableUsingConstantPoolForLargeInts ("riscv-disable-using-constant-pool-for-large-ints", cl::desc("Disable using constant pool for large integers."), cl::init(false), cl::Hidden)
static cl::opt< unsigned > RISCVMaxBuildIntsCost ("riscv-max-build-ints-cost", cl::desc("The maximum cost used for building integers."), cl::init(0), cl::Hidden)
static cl::opt< bool > UseAA ("riscv-use-aa", cl::init(true), cl::desc("Enable the use of AA during codegen."))
static cl::opt< unsigned > RISCVMinimumJumpTableEntries ("riscv-min-jump-table-entries", cl::Hidden, cl::desc("Set minimum number of entries to use a jump table on RISCV"))
static cl::opt< bool > UseMIPSLoadStorePairsOpt ("use-riscv-mips-load-store-pairs", cl::desc("Enable the load/store pair optimization pass"), cl::init(false), cl::Hidden)
static cl::opt< bool > UseMIPSCCMovInsn ("use-riscv-mips-ccmov", cl::desc("Use 'mips.ccmov' instruction"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnablePExtSIMDCodeGen ("riscv-enable-p-ext-simd-codegen", cl::desc("Turn on P Extension SIMD codegen(This is a temporary switch " "where only partial codegen is currently supported)"), cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-subtarget"
Definition at line 25 of file RISCVSubtarget.cpp.
GET_RISCV_MACRO_FUSION_PRED_IMPL
#define GET_RISCV_MACRO_FUSION_PRED_IMPL
Definition at line 31 of file RISCVSubtarget.cpp.
GET_RISCVTuneInfoTable_IMPL
#define GET_RISCVTuneInfoTable_IMPL
Definition at line 36 of file RISCVSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 28 of file RISCVSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 27 of file RISCVSubtarget.cpp.
Variable Documentation
EnablePExtSIMDCodeGen
cl::opt< bool > EnablePExtSIMDCodeGen("riscv-enable-p-ext-simd-codegen", cl::desc("Turn on P Extension SIMD codegen(This is a temporary switch " "where only partial codegen is currently supported)"), cl::init(false), cl::Hidden) ("riscv-enable-p-ext-simd-codegen" , cl::desc("Turn on P Extension SIMD codegen(This is a temporary switch " "where only partial codegen is currently supported)") , cl::init(false) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::enablePExtSIMDCodeGen().
RISCVDisableUsingConstantPoolForLargeInts
cl::opt< bool > RISCVDisableUsingConstantPoolForLargeInts("riscv-disable-using-constant-pool-for-large-ints", cl::desc("Disable using constant pool for large integers."), cl::init(false), cl::Hidden) ("riscv-disable-using-constant-pool-for-large-ints" , cl::desc("Disable using constant pool for large integers.") , cl::init(false) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::useConstantPoolForLargeInts().
RISCVMaxBuildIntsCost
cl::opt< unsigned > RISCVMaxBuildIntsCost("riscv-max-build-ints-cost", cl::desc("The maximum cost used for building integers."), cl::init(0), cl::Hidden) ("riscv-max-build-ints-cost" , cl::desc("The maximum cost used for building integers.") , cl::init(0) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxBuildIntsCost().
RISCVMinimumJumpTableEntries
cl::opt< unsigned > RISCVMinimumJumpTableEntries("riscv-min-jump-table-entries", cl::Hidden, cl::desc("Set minimum number of entries to use a jump table on RISCV")) ("riscv-min-jump-table-entries" , cl::Hidden , cl::desc("Set minimum number of entries to use a jump table on RISCV")) static
Referenced by llvm::RISCVSubtarget::getMinimumJumpTableEntries().
RVVVectorLMULMax
cl::opt< unsigned > RVVVectorLMULMax("riscv-v-fixed-length-vector-lmul-max", cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported."), cl::init(8), cl::Hidden) ("riscv-v-fixed-length-vector-lmul-max" , cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported.") , cl::init(8) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxLMULForFixedLengthVectors().
UseAA
cl::opt< bool > UseAA("riscv-use-aa", cl::init(true), cl::desc("Enable the use of AA during codegen.")) ("riscv-use-aa" , cl::init(true) , cl::desc("Enable the use of AA during codegen.")) static
UseMIPSCCMovInsn
cl::opt< bool > UseMIPSCCMovInsn("use-riscv-mips-ccmov", cl::desc("Use 'mips.ccmov' instruction"), cl::init(true), cl::Hidden) ("use-riscv-mips-ccmov" , cl::desc("Use 'mips.ccmov' instruction") , cl::init(true) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::useMIPSCCMovInsn().
UseMIPSLoadStorePairsOpt
cl::opt< bool > UseMIPSLoadStorePairsOpt("use-riscv-mips-load-store-pairs", cl::desc("Enable the load/store pair optimization pass"), cl::init(false), cl::Hidden) ("use-riscv-mips-load-store-pairs" , cl::desc("Enable the load/store pair optimization pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::RISCVSubtarget::useMIPSLoadStorePairs().