LLVM: lib/Target/RISCV/RISCVFrameLowering.cpp File Reference
RISCVFrameLowering.cpp File Reference
#include "RISCVFrameLowering.h"
#include "MCTargetDesc/RISCVBaseInfo.h"
#include "RISCVMachineFunctionInfo.h"
#include "RISCVSubtarget.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/CFIInstBuilder.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/Support/LEB128.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "riscv-frame"
Functions
static Align getABIStackAlignment (RISCVABI::ABI ABI)
static bool needsDwarfCFI (const MachineFunction &MF)
Returns true if DWARF CFI instructions ("frame moves") should be emitted.
static void emitSCSPrologue (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL)
static void emitSCSEpilogue (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL)
static void emitSiFiveCLICStackSwap (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL)
static void createSiFivePreemptibleInterruptFrameEntries (MachineFunction &MF, RISCVMachineFunctionInfo &RVFI)
static void emitSiFiveCLICPreemptibleSaves (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL)
static void emitSiFiveCLICPreemptibleRestores (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL)
static int getLibCallID (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static const char * getSpillLibCallName (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static const char * getRestoreLibCallName (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static unsigned getNumPushPopRegs (const std::vector< CalleeSavedInfo > &CSI)
static SmallVector< CalleeSavedInfo, 8 > getUnmanagedCSI (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static SmallVector< CalleeSavedInfo, 8 > getRVVCalleeSavedInfo (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static SmallVector< CalleeSavedInfo, 8 > getPushOrLibCallsSavedInfo (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static SmallVector< CalleeSavedInfo, 8 > getQCISavedInfo (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static void appendScalableVectorExpression (const TargetRegisterInfo &TRI, SmallVectorImpl< char > &Expr, StackOffset Offset, llvm::raw_string_ostream &Comment)
static MCCFIInstruction createDefCFAExpression (const TargetRegisterInfo &TRI, Register Reg, StackOffset Offset)
static MCCFIInstruction createDefCFAOffset (const TargetRegisterInfo &TRI, Register Reg, StackOffset Offset)
static bool isPush (unsigned Opcode)
static bool isPop (unsigned Opcode)
static unsigned getPushOpcode (RISCVMachineFunctionInfo::PushPopKind Kind, bool UpdateFP)
static unsigned getPopOpcode (RISCVMachineFunctionInfo::PushPopKind Kind)
static MCRegister getRVVBaseRegister (const RISCVRegisterInfo &TRI, const Register &Reg)
static unsigned getScavSlotsNumForRVV (MachineFunction &MF)
static bool hasRVVFrameObject (const MachineFunction &MF)
static unsigned estimateFunctionSizeInBytes (const MachineFunction &MF, const RISCVInstrInfo &TII)
static unsigned getCalleeSavedRVVNumRegs (const Register &BaseReg)
static void emitStackProbeInline (MachineBasicBlock::iterator MBBI, DebugLoc DL, Register TargetReg, bool IsRVV)
Variables
static constexpr MCPhysReg FPReg = RISCV::X8
static constexpr MCPhysReg SPReg = RISCV::X2
static constexpr MCPhysReg RAReg = RISCV::X1
static const MCPhysReg FixedCSRFIMap []
static constexpr uint64_t QCIInterruptPushAmount = 96
static const std::pair< MCPhysReg, int8_t > FixedCSRFIQCIInterruptMap []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-frame"
Definition at line 31 of file RISCVFrameLowering.cpp.
Function Documentation
appendScalableVectorExpression()
void appendScalableVectorExpression (const TargetRegisterInfo & TRI, SmallVectorImpl< char > & Expr, StackOffset Offset, llvm::raw_string_ostream & Comment) static
Definition at line 674 of file RISCVFrameLowering.cpp.
References llvm::appendLEB128(), llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and TRI.
Referenced by createDefCFAExpression(), and createDefCFAOffset().
createDefCFAExpression()
MCCFIInstruction createDefCFAExpression (const TargetRegisterInfo & TRI, Register Reg, StackOffset Offset) static
Definition at line 702 of file RISCVFrameLowering.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::appendLEB128(), appendScalableVectorExpression(), assert(), llvm::MCCFIInstruction::createEscape(), llvm::Offset, llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::SmallVectorTemplateCommon< T, typename >::size(), SPReg, llvm::SmallString< InternalLen >::str(), and TRI.
createDefCFAOffset()
MCCFIInstruction createDefCFAOffset (const TargetRegisterInfo & TRI, Register Reg, StackOffset Offset) static
Definition at line 729 of file RISCVFrameLowering.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::appendLEB128(), appendScalableVectorExpression(), assert(), llvm::MCCFIInstruction::createEscape(), llvm::Offset, llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallString< InternalLen >::str(), and TRI.
createSiFivePreemptibleInterruptFrameEntries()
void createSiFivePreemptibleInterruptFrameEntries (MachineFunction & MF, RISCVMachineFunctionInfo & RVFI) static
Definition at line 251 of file RISCVFrameLowering.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getSubtarget(), I, llvm::RISCVMachineFunctionInfo::isSiFivePreemptibleInterrupt(), llvm::RISCVMachineFunctionInfo::pushInterruptCSRFrameIndex(), and TRI.
Referenced by llvm::RISCVFrameLowering::determineCalleeSaves().
emitSCSEpilogue()
void emitSCSEpilogue (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL) static
Definition at line 181 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::CFIInstBuilder::buildRestore(), llvm::RegState::Define, DL, llvm::MachineInstr::FrameDestroy, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::CalleeSavedInfo::getReg(), llvm::RISCVABI::getSCSPReg(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), MBB, MI, needsDwarfCFI(), llvm::none_of(), RAReg, llvm::MachineInstrBuilder::setMIFlag(), and TII.
Referenced by llvm::RISCVFrameLowering::emitEpilogue().
emitSCSPrologue()
void emitSCSPrologue (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL) static
Definition at line 105 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::CFIInstBuilder::buildEscape(), llvm::BuildMI(), llvm::RegState::Define, DL, llvm::MachineInstr::FrameSetup, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::CalleeSavedInfo::getReg(), llvm::RISCVABI::getSCSPReg(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), MBB, MI, needsDwarfCFI(), llvm::none_of(), llvm::Offset, RAReg, llvm::MachineInstrBuilder::setMIFlag(), TII, and TRI.
Referenced by llvm::RISCVFrameLowering::emitPrologue().
emitSiFiveCLICPreemptibleRestores()
void emitSiFiveCLICPreemptibleRestores (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL) static
Definition at line 323 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, DL, llvm::MachineInstr::FrameSetup, llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::RegState::Kill, MBB, MBBI, llvm::MachineInstrBuilder::setMIFlag(), and TII.
Referenced by llvm::RISCVFrameLowering::emitEpilogue().
emitSiFiveCLICPreemptibleSaves()
void emitSiFiveCLICPreemptibleSaves (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL) static
Definition at line 271 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, DL, llvm::MachineInstr::FrameSetup, llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), MBB, MBBI, llvm::MachineInstrBuilder::setMIFlag(), and TII.
Referenced by llvm::RISCVFrameLowering::emitPrologue().
emitSiFiveCLICStackSwap()
void emitSiFiveCLICStackSwap (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL) static
Definition at line 228 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::RegState::Define, DL, llvm::MachineInstr::FrameSetup, llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::RegState::Kill, MBB, MBBI, llvm::MachineInstrBuilder::setMIFlag(), SPReg, and TII.
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), and llvm::RISCVFrameLowering::emitPrologue().
emitStackProbeInline()
void emitStackProbeInline (MachineBasicBlock::iterator MBBI, DebugLoc DL, Register TargetReg, bool IsRVV) static
Definition at line 2403 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameSetup, llvm::fullyRecomputeLiveIns(), llvm::RISCVTargetLowering::getStackProbeSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::insert(), MBB, MBBI, llvm::MachineInstrBuilder::setMIFlags(), llvm::MachineBasicBlock::splice(), SPReg, TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
estimateFunctionSizeInBytes()
unsigned estimateFunctionSizeInBytes (const MachineFunction & MF, const RISCVInstrInfo & TII) static
Definition at line 1759 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getSubtarget(), MBB, MI, and TII.
getABIStackAlignment()
Align getABIStackAlignment (RISCVABI::ABI ABI) static
Definition at line 35 of file RISCVFrameLowering.cpp.
References llvm::RISCVABI::ABI_ILP32E, and llvm::RISCVABI::ABI_LP64E.
Referenced by llvm::RISCVFrameLowering::RISCVFrameLowering().
getCalleeSavedRVVNumRegs()
unsigned getCalleeSavedRVVNumRegs (const Register & BaseReg) static
Definition at line 2180 of file RISCVFrameLowering.cpp.
getLibCallID()
int getLibCallID (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 374 of file RISCVFrameLowering.cpp.
References FPReg, llvm::MachineFunction::getInfo(), llvm::MCRegister::id(), llvm_unreachable, and RAReg.
Referenced by llvm::RISCVFrameLowering::assignCalleeSavedSpillSlots(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), getRestoreLibCallName(), and getSpillLibCallName().
getNumPushPopRegs()
unsigned getNumPushPopRegs (const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 467 of file RISCVFrameLowering.cpp.
References assert(), llvm::find_if(), FixedCSRFIMap, and P.
Referenced by llvm::RISCVFrameLowering::assignCalleeSavedSpillSlots().
getPopOpcode()
unsigned getPopOpcode (RISCVMachineFunctionInfo::PushPopKind Kind) static
Definition at line 899 of file RISCVFrameLowering.cpp.
References llvm_unreachable, llvm::RISCVMachineFunctionInfo::StdExtZcmp, and llvm::RISCVMachineFunctionInfo::VendorXqccmp.
Referenced by llvm::RISCVFrameLowering::restoreCalleeSavedRegisters().
getPushOpcode()
unsigned getPushOpcode (RISCVMachineFunctionInfo::PushPopKind Kind, bool UpdateFP) static
Definition at line 887 of file RISCVFrameLowering.cpp.
References llvm_unreachable, llvm::RISCVMachineFunctionInfo::StdExtZcmp, and llvm::RISCVMachineFunctionInfo::VendorXqccmp.
Referenced by llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
getPushOrLibCallsSavedInfo()
SmallVector< CalleeSavedInfo, 8 > getPushOrLibCallsSavedInfo (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 583 of file RISCVFrameLowering.cpp.
References FixedCSRFIMap, FixedCSRFIQCIInterruptMap, llvm::MachineFunction::getInfo(), llvm::is_contained(), and llvm::make_first_range().
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), and llvm::RISCVFrameLowering::emitPrologue().
getQCISavedInfo()
SmallVector< CalleeSavedInfo, 8 > getQCISavedInfo (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 610 of file RISCVFrameLowering.cpp.
References FixedCSRFIQCIInterruptMap, llvm::MachineFunction::getInfo(), llvm::is_contained(), and llvm::make_first_range().
Referenced by llvm::RISCVFrameLowering::emitPrologue().
getRestoreLibCallName()
const char * getRestoreLibCallName (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 442 of file RISCVFrameLowering.cpp.
References getLibCallID().
Referenced by llvm::RISCVFrameLowering::restoreCalleeSavedRegisters().
getRVVBaseRegister()
MCRegister getRVVBaseRegister (const RISCVRegisterInfo & TRI, const Register & Reg) static
Definition at line 1556 of file RISCVFrameLowering.cpp.
References Reg, and TRI.
Referenced by llvm::RISCVFrameLowering::determineCalleeSaves().
getRVVCalleeSavedInfo()
SmallVector< CalleeSavedInfo, 8 > getRVVCalleeSavedInfo (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 568 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackID(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::TargetStackID::ScalableVector.
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), and llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
getScavSlotsNumForRVV()
unsigned getScavSlotsNumForRVV (MachineFunction & MF) static
Definition at line 1696 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackID(), llvm::MachineFunction::getSubtarget(), llvm::RISCVSubtarget::hasVInstructions(), llvm::RISCV::isRVVSpill(), MBB, MI, and llvm::TargetStackID::ScalableVector.
Referenced by llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().
getSpillLibCallName()
const char * getSpillLibCallName (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 415 of file RISCVFrameLowering.cpp.
References getLibCallID().
Referenced by llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
getUnmanagedCSI()
SmallVector< CalleeSavedInfo, 8 > getUnmanagedCSI (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 553 of file RISCVFrameLowering.cpp.
References llvm::TargetStackID::Default, llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackID(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), and llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
hasRVVFrameObject()
bool hasRVVFrameObject (const MachineFunction & MF) static
Definition at line 1740 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getSubtarget().
Referenced by llvm::RISCVFrameLowering::hasReservedCallFrame(), and llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().
isPop()
bool isPop (unsigned Opcode) static
Definition at line 875 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), getPopRetOpcode(), and INITIALIZE_PASS().
isPush()
bool isPush (unsigned Opcode) static
Definition at line 864 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::emitPrologue().
needsDwarfCFI()
bool needsDwarfCFI (const MachineFunction & MF) static
Returns true if DWARF CFI instructions ("frame moves") should be emitted.
Definition at line 99 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::needsFrameMoves().
Referenced by llvm::RISCVFrameLowering::eliminateCallFramePseudoInstr(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), emitSCSEpilogue(), and emitSCSPrologue().
Variable Documentation
FixedCSRFIMap
const MCPhysReg FixedCSRFIMap[] static
Initial value:
                                = {
RAReg,       FPReg,       RISCV::X9,
RISCV::X18,  RISCV::X19,  RISCV::X20,
RISCV::X21,  RISCV::X22,  RISCV::X23,
RISCV::X24,  RISCV::X25,  RISCV::X26,
RISCV::X27}
Definition at line 63 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::assignCalleeSavedSpillSlots(), getNumPushPopRegs(), getPushOrLibCallsSavedInfo(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), and llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
FixedCSRFIQCIInterruptMap
const std::pair<MCPhysReg, int8_t> FixedCSRFIQCIInterruptMap[] static
Initial value:
                                                 = {
    { FPReg, -2},
    { RAReg, -4},
    { RISCV::X5, -6},
    { RISCV::X6, -7},
    { RISCV::X7, -8},
    { RISCV::X10, -9},
    { RISCV::X11, -10},
    { RISCV::X12, -11},
    { RISCV::X13, -12},
    { RISCV::X14, -13},
    { RISCV::X15, -14},
    { RISCV::X16, -15},
    { RISCV::X17, -16},
    { RISCV::X28, -17},
    { RISCV::X29, -18},
    { RISCV::X30, -19},
    { RISCV::X31, -20},
}
Definition at line 74 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::assignCalleeSavedSpillSlots(), getPushOrLibCallsSavedInfo(), getQCISavedInfo(), and llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
FPReg
MCPhysReg FPReg = RISCV::X8 static constexpr
Definition at line 51 of file RISCVFrameLowering.cpp.
Referenced by llvm::M68kFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::getFrameIndexReference(), getLibCallID(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
QCIInterruptPushAmount
uint64_t QCIInterruptPushAmount = 96 static constexpr
Definition at line 72 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::assignCalleeSavedSpillSlots(), and llvm::RISCVFrameLowering::emitPrologue().
RAReg
MCPhysReg RAReg = RISCV::X1 static constexpr
Definition at line 57 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::determineCalleeSaves(), emitSCSEpilogue(), emitSCSPrologue(), and getLibCallID().
SPReg
MCPhysReg SPReg = RISCV::X2 static constexpr
Definition at line 54 of file RISCVFrameLowering.cpp.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::RISCVFrameLowering::allocateStack(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), createDefCFAExpression(), llvm::CSKYFrameLowering::eliminateCallFramePseudoInstr(), llvm::LoongArchFrameLowering::eliminateCallFramePseudoInstr(), llvm::RISCVFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::RISCVTargetLowering::emitDynamicProbedAlloc(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::CSKYFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), emitSiFiveCLICStackSwap(), emitStackProbeInline(), llvm::LegalizerHelper::getDynStackAllocTargetPtr(), llvm::RISCVFrameLowering::getFrameIndexReference(), M68kOutgoingArgHandler::getStackAddress(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCInstrInfo::isTOCSaveMI(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::LegalizerHelper::lowerDynStackAlloc(), and LowerSTACKADDRESS().