LLVM: lib/Target/RISCV/RISCVIndirectBranchTracking.cpp File Reference
RISCVIndirectBranchTracking.cpp File Reference
#include "RISCV.h"
#include "RISCVInstrInfo.h"
#include "RISCVSubtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
Macros
#define DEBUG_TYPE "riscv-indirect-branch-tracking"
#define PASS_NAME "RISC-V Indirect Branch Tracking"
Functions
static void emitLpad (MachineBasicBlock &MBB, const RISCVInstrInfo *TII, uint32_t Label, MachineBasicBlock::iterator I=MachineBasicBlock::iterator{})
static bool isCallReturnTwice (const MachineOperand &MOp)
Variables
cl::opt< uint32_t > PreferredLandingPadLabel ("riscv-landing-pad-label", cl::ReallyHidden, cl::desc("Use preferred fixed label for all labels"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-indirect-branch-tracking"
Definition at line 24 of file RISCVIndirectBranchTracking.cpp.
PASS_NAME
#define PASS_NAME "RISC-V Indirect Branch Tracking"
Definition at line 25 of file RISCVIndirectBranchTracking.cpp.
Function Documentation
emitLpad()
void emitLpad (MachineBasicBlock & MBB, const RISCVInstrInfo * TII, uint32_t Label, MachineBasicBlock::iterator I = MachineBasicBlock::iterator{}) static
Definition at line 59 of file RISCVIndirectBranchTracking.cpp.
References I, MBB, and TII.
isCallReturnTwice()
bool isCallReturnTwice (const MachineOperand & MOp) static
Definition at line 67 of file RISCVIndirectBranchTracking.cpp.
References llvm::dyn_cast(), llvm::MachineOperand::getGlobal(), and llvm::MachineOperand::isGlobal().
Variable Documentation
PreferredLandingPadLabel
cl::opt< uint32_t > PreferredLandingPadLabel("riscv-landing-pad-label", cl::ReallyHidden, cl::desc("Use preferred fixed label for all labels")) ("riscv-landing-pad-label" , cl::ReallyHidden , cl::desc("Use preferred fixed label for all labels"))