LLVM: lib/Analysis/ScalarEvolution.cpp File Reference
ScalarEvolution.cpp File Reference
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ScalarEvolutionPatternMatch.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/InterleavedRange.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <climits>
#include <cstdint>
#include <cstdlib>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <tuple>
#include <utility>
#include <vector>
Classes
class SCEVCastSinkingRewriter
The SCEVCastSinkingRewriter takes a scalar evolution expression, which computes a pointer-typed value, and rewrites the whole expression tree so that all the computations are done on integers, and the only pointer-typed operands in the expression are SCEVUnknown.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "scalar-evolution"
Functions
STATISTIC (NumExitCountsComputed, "Number of loop exits with predictable exit counts")
STATISTIC (NumExitCountsNotComputed, "Number of loop exits without predictable exit counts")
STATISTIC (NumBruteForceTripCountsComputed, "Number of loops with trip counts computed by force")
static int CompareValueComplexity (const LoopInfo *const LI, Value *LV, Value *RV, unsigned Depth)
Compare the two values LV and RV in terms of their "complexity" where "complexity" is a partial (and somewhat ad-hoc) relation used to order operands in SCEV expressions.
static std::optional< int > CompareSCEVComplexity (const LoopInfo *const LI, const SCEV *LHS, const SCEV *RHS, DominatorTree &DT, unsigned Depth=0)
static void GroupByComplexity (SmallVectorImpl< const SCEV * > &Ops, LoopInfo *LI, DominatorTree &DT)
Given a list of SCEV objects, order them by their complexity, and group objects of the same complexity together by value.
static bool hasHugeExpression (ArrayRef< const SCEV * > Ops)
Returns true if Ops contains a huge SCEV (the subtree of S contains at least HugeExprThreshold nodes).
template<typename FoldT, typename IsIdentityT, typename IsAbsorberT>
static const SCEV * constantFoldAndGroupOps (ScalarEvolution &SE, LoopInfo &LI, DominatorTree &DT, SmallVectorImpl< const SCEV * > &Ops, FoldT Fold, IsIdentityT IsIdentity, IsAbsorberT IsAbsorber)
Performs a number of common optimizations on the passed Ops.
static const SCEV * BinomialCoefficient (const SCEV *It, unsigned K, ScalarEvolution &SE, Type *ResultTy)
Compute BC(It, K). The result has width W. Assume, K > 0.
static const SCEV * getSignedOverflowLimitForStep (const SCEV *Step, ICmpInst::Predicate *Pred, ScalarEvolution *SE)
static const SCEV * getUnsignedOverflowLimitForStep (const SCEV *Step, ICmpInst::Predicate *Pred, ScalarEvolution *SE)
template<typename ExtendOpTy>
static const SCEV * getPreStartForExtend (const SCEVAddRecExpr *AR, Type *Ty, ScalarEvolution *SE, unsigned Depth)
template<typename ExtendOpTy>
static const SCEV * getExtendAddRecStart (const SCEVAddRecExpr *AR, Type *Ty, ScalarEvolution *SE, unsigned Depth)
static APInt extractConstantWithoutWrapping (ScalarEvolution &SE, const SCEVConstant *ConstantTerm, const SCEVAddExpr *WholeAddExpr)
static APInt extractConstantWithoutWrapping (ScalarEvolution &SE, const APInt &ConstantStart, const SCEV *Step)
static void insertFoldCacheEntry (const ScalarEvolution::FoldID &ID, const SCEV *S, DenseMap< ScalarEvolution::FoldID, const SCEV * > &FoldCache, DenseMap< const SCEV *, SmallVector< ScalarEvolution::FoldID, 2 > > &FoldCacheUser)
static bool CollectAddOperandsWithScales (SmallDenseMap< const SCEV *, APInt, 16 > &M, SmallVectorImpl< const SCEV * > &NewOps, APInt &AccumulatedConstant, ArrayRef< const SCEV * > Ops, const APInt &Scale, ScalarEvolution &SE)
Process the given Ops list, which is a list of operands to be added under the given scale, update the given map.
static SCEV::NoWrapFlags StrengthenNoWrapFlags (ScalarEvolution *SE, SCEVTypes Type, ArrayRef< const SCEV * > Ops, SCEV::NoWrapFlags Flags)
static uint64_t umul_ov (uint64_t i, uint64_t j, bool &Overflow)
static uint64_t Choose (uint64_t n, uint64_t k, bool &Overflow)
Compute the result of "n choose k", the binomial coefficient.
static bool containsConstantInAddMulChain (const SCEV *StartExpr)
Determine if any of the operands in this SCEV are a constant or if any of the add or multiply expressions in this SCEV contain a constant.
APInt gcd (const SCEVConstant *C1, const SCEVConstant *C2)
static bool scevUnconditionallyPropagatesPoisonFromOperands (SCEVTypes Kind)
static bool impliesPoison (const SCEV *AssumedPoison, const SCEV *S)
Return true if V is poison given that AssumedPoison is already poison.
static const SCEV * MatchNotExpr (const SCEV *Expr)
If Expr computes ~A, return A else return nullptr.
static void PushDefUseChildren (Instruction *I, SmallVectorImpl< Instruction * > &Worklist, SmallPtrSetImpl< Instruction * > &Visited)
Push users of the given Instruction onto the given Worklist.
static std::optional< BinaryOp > MatchBinaryOp (Value *V, const DataLayout &DL, AssumptionCache &AC, const DominatorTree &DT, const Instruction *CxtI)
Try to map V into a BinaryOp, and return std::nullopt on failure.
static Type * isSimpleCastedPHI (const SCEV *Op, const SCEVUnknown *SymbolicPHI, bool &Signed, ScalarEvolution &SE)
Helper function to createAddRecFromPHIWithCasts.
static const Loop * isIntegerLoopHeaderPHI (const PHINode *PN, LoopInfo &LI)
static bool BrPHIToSelect (DominatorTree &DT, BranchInst *BI, PHINode *Merge, Value *&C, Value *&LHS, Value *&RHS)
bool SCEVMinMaxExprContains (const SCEV *Root, const SCEV *OperandToFind, SCEVTypes RootKind)
static std::optional< const SCEV * > createNodeForSelectViaUMinSeq (ScalarEvolution *SE, const SCEV *CondExpr, const SCEV *TrueExpr, const SCEV *FalseExpr)
static std::optional< const SCEV * > createNodeForSelectViaUMinSeq (ScalarEvolution *SE, Value *Cond, Value *TrueVal, Value *FalseVal)
static std::optional< ConstantRange > GetRangeFromMetadata (Value *V)
Helper method to assign a range to V from metadata present in the IR.
static ConstantRange getRangeForAffineARHelper (APInt Step, const ConstantRange &StartRange, const APInt &MaxBECount, bool Signed)
static unsigned getConstantTripCount (const SCEVConstant *ExitCount)
static void PushLoopPHIs (const Loop *L, SmallVectorImpl< Instruction * > &Worklist, SmallPtrSetImpl< Instruction * > &Visited)
Push PHI nodes in the header of the given loop onto the given Worklist.
static ConstantInt * EvaluateConstantChrecAtConstant (const SCEVAddRecExpr *AddRec, ConstantInt *C, ScalarEvolution &SE)
static bool CanConstantFold (const Instruction *I)
Return true if we can constant fold an instruction of the specified type, assuming that all operands were constants.
static bool canConstantEvolve (Instruction *I, const Loop *L)
Determine whether this instruction can constant evolve within this loop assuming its operands can all constant evolve.
static PHINode * getConstantEvolvingPHIOperands (Instruction *UseInst, const Loop *L, DenseMap< Instruction *, PHINode * > &PHIMap, unsigned Depth)
getConstantEvolvingPHIOperands - Implement getConstantEvolvingPHI by recursing through each instruction operand until reaching a loop header phi.
static PHINode * getConstantEvolvingPHI (Value *V, const Loop *L)
getConstantEvolvingPHI - Given an LLVM value and a loop, return a PHI node in the loop that V is derived from.
static Constant * EvaluateExpression (Value *V, const Loop *L, DenseMap< Instruction *, Constant * > &Vals, const DataLayout &DL, const TargetLibraryInfo *TLI)
EvaluateExpression - Given an expression that passes the getConstantEvolvingPHI predicate, evaluate its value assuming the PHI node in the loop has the value PHIVal.
static Constant * getOtherIncomingValue (PHINode *PN, BasicBlock *BB)
static Constant * BuildConstantFromSCEV (const SCEV *V)
This builds up a Constant using the ConstantExpr interface.
static const SCEV * SolveLinEquationWithOverflow (const APInt &A, const SCEV *B, SmallVectorImpl< const SCEVPredicate * > *Predicates, ScalarEvolution &SE, const Loop *L)
Finds the minimum unsigned root of the following equation:
static std::optional< std::tuple< APInt, APInt, APInt, APInt, unsigned > > GetQuadraticEquation (const SCEVAddRecExpr *AddRec)
For a given quadratic addrec, generate coefficients of the corresponding quadratic equation, multiplied by a common value to ensure that they are integers.
static std::optional< APInt > MinOptional (std::optional< APInt > X, std::optional< APInt > Y)
Helper function to compare optional APInts: (a) if X and Y both exist, return min(X, Y), (b) if neither X nor Y exist, return std::nullopt, (c) if exactly one of X and Y exists, return that value.
static std::optional< APInt > TruncIfPossible (std::optional< APInt > X, unsigned BitWidth)
Helper function to truncate an optional APInt to a given BitWidth.
static std::optional< APInt > SolveQuadraticAddRecExact (const SCEVAddRecExpr *AddRec, ScalarEvolution &SE)
Let c(n) be the value of the quadratic chrec {L,+,M,+,N} after n iterations.
static std::optional< APInt > SolveQuadraticAddRecRange (const SCEVAddRecExpr *AddRec, const ConstantRange &Range, ScalarEvolution &SE)
Let c(n) be the value of the quadratic chrec {0,+,M,+,N} after n iterations.
static bool HasSameValue (const SCEV *A, const SCEV *B)
SCEV structural equivalence is usually sufficient for testing whether two expressions are equal, however for the purposes of looking for a condition guarding a loop, it can be useful to be a little more general, since a front-end may have replicated the controlling expression.
static bool MatchBinarySub (const SCEV *S, const SCEV *&LHS, const SCEV *&RHS)
template<typename MinMaxExprType>
static bool IsMinMaxConsistingOf (const SCEV *MaybeMinMaxExpr, const SCEV *Candidate)
Is MaybeMinMaxExpr an (U|S)(Min|Max) of Candidate and some other values?
static bool IsKnownPredicateViaAddRecStart (ScalarEvolution &SE, CmpPredicate Pred, const SCEV *LHS, const SCEV *RHS)
static bool IsKnownPredicateViaMinOrMax (ScalarEvolution &SE, CmpPredicate Pred, const SCEV *LHS, const SCEV *RHS)
Is LHS Pred RHS true on the virtue of LHS or RHS being a Min or Max expression?
static bool isKnownPredicateExtendIdiom (CmpPredicate Pred, const SCEV *LHS, const SCEV *RHS)
static void PrintSCEVWithTypeHint (raw_ostream &OS, const SCEV *S)
When printing a top-level SCEV for trip counts, it's helpful to include a type for constants which are otherwise hard to disambiguate.
static void PrintLoopInfo (raw_ostream &OS, ScalarEvolution *SE, const Loop *L)
static raw_ostream & llvm::operator<< (raw_ostream &OS, ScalarEvolution::LoopDisposition LD)
static raw_ostream & llvm::operator<< (raw_ostream &OS, llvm::ScalarEvolution::BlockDisposition BD)
INITIALIZE_PASS_BEGIN (ScalarEvolutionWrapperPass, "scalar-evolution", "Scalar Evolution Analysis", false, true) INITIALIZE_PASS_END(ScalarEvolutionWrapperPass
static const SCEV * getPreviousSCEVDivisibleByDivisor (const SCEV *Expr, const APInt &DivisorVal, ScalarEvolution &SE)
static const SCEV * getNextSCEVDivisibleByDivisor (const SCEV *Expr, const APInt &DivisorVal, ScalarEvolution &SE)
static bool collectDivisibilityInformation (ICmpInst::Predicate Predicate, const SCEV *LHS, const SCEV *RHS, DenseMap< const SCEV *, const SCEV * > &DivInfo, DenseMap< const SCEV *, APInt > &Multiples, ScalarEvolution &SE)
static bool isDivisibilityGuard (const SCEV *LHS, const SCEV *RHS, ScalarEvolution &SE)
static const SCEV * applyDivisibilityOnMinMaxExpr (const SCEV *MinMaxExpr, APInt Divisor, ScalarEvolution &SE)
Variables
static cl::opt< unsigned > MaxBruteForceIterations ("scalar-evolution-max-iterations", cl::ReallyHidden, cl::desc("Maximum number of iterations SCEV will " "symbolically execute a constant " "derived loop"), cl::init(100))
static cl::opt< bool, true > VerifySCEVOpt ("verify-scev", cl::Hidden, cl::location(VerifySCEV), cl::desc("Verify ScalarEvolution's backedge taken counts (slow)"))
static cl::opt< bool > VerifySCEVStrict ("verify-scev-strict", cl::Hidden, cl::desc("Enable stricter verification with -verify-scev is passed"))
static cl::opt< bool > VerifyIR ("scev-verify-ir", cl::Hidden, cl::desc("Verify IR correctness when making sensitive SCEV queries (slow)"), cl::init(false))
static cl::opt< unsigned > MulOpsInlineThreshold ("scev-mulops-inline-threshold", cl::Hidden, cl::desc("Threshold for inlining multiplication operands into a SCEV"), cl::init(32))
static cl::opt< unsigned > AddOpsInlineThreshold ("scev-addops-inline-threshold", cl::Hidden, cl::desc("Threshold for inlining addition operands into a SCEV"), cl::init(500))
static cl::opt< unsigned > MaxSCEVCompareDepth ("scalar-evolution-max-scev-compare-depth", cl::Hidden, cl::desc("Maximum depth of recursive SCEV complexity comparisons"), cl::init(32))
static cl::opt< unsigned > MaxSCEVOperationsImplicationDepth ("scalar-evolution-max-scev-operations-implication-depth", cl::Hidden, cl::desc("Maximum depth of recursive SCEV operations implication analysis"), cl::init(2))
static cl::opt< unsigned > MaxValueCompareDepth ("scalar-evolution-max-value-compare-depth", cl::Hidden, cl::desc("Maximum depth of recursive value complexity comparisons"), cl::init(2))
static cl::opt< unsigned > MaxArithDepth ("scalar-evolution-max-arith-depth", cl::Hidden, cl::desc("Maximum depth of recursive arithmetics"), cl::init(32))
static cl::opt< unsigned > MaxConstantEvolvingDepth ("scalar-evolution-max-constant-evolving-depth", cl::Hidden, cl::desc("Maximum depth of recursive constant evolving"), cl::init(32))
static cl::opt< unsigned > MaxCastDepth ("scalar-evolution-max-cast-depth", cl::Hidden, cl::desc("Maximum depth of recursive SExt/ZExt/Trunc"), cl::init(8))
static cl::opt< unsigned > MaxAddRecSize ("scalar-evolution-max-add-rec-size", cl::Hidden, cl::desc("Max coefficients in AddRec during evolving"), cl::init(8))
static cl::opt< unsigned > HugeExprThreshold ("scalar-evolution-huge-expr-threshold", cl::Hidden, cl::desc("Size of the expression which is considered huge"), cl::init(4096))
static cl::opt< unsigned > RangeIterThreshold ("scev-range-iter-threshold", cl::Hidden, cl::desc("Threshold for switching to iteratively computing SCEV ranges"), cl::init(32))
static cl::opt< unsigned > MaxLoopGuardCollectionDepth ("scalar-evolution-max-loop-guard-collection-depth", cl::Hidden, cl::desc("Maximum depth for recursive loop guard collection"), cl::init(1))
static cl::opt< bool > ClassifyExpressions ("scalar-evolution-classify-expressions", cl::Hidden, cl::init(true), cl::desc("When printing analysis, include information on every instruction"))
static cl::opt< bool > UseExpensiveRangeSharpening ("scalar-evolution-use-expensive-range-sharpening", cl::Hidden, cl::init(false), cl::desc("Use more powerful methods of sharpening expression ranges. May " "be costly in terms of compile time"))
static cl::opt< unsigned > MaxPhiSCCAnalysisSize ("scalar-evolution-max-scc-analysis-depth", cl::Hidden, cl::desc("Maximum amount of nodes to process while searching SCEVUnknown " "Phi strongly connected components"), cl::init(8))
static cl::opt< bool > EnableFiniteLoopControl ("scalar-evolution-finite-loop", cl::Hidden, cl::desc("Handle <= and >= in finite loops"), cl::init(true))
static cl::opt< bool > UseContextForNoWrapFlagInference ("scalar-evolution-use-context-for-no-wrap-flag-strenghening", cl::Hidden, cl::desc("Infer nuw/nsw flags using context where suitable"), cl::init(true))
scalar evolution
scalar Scalar Evolution Analysis
scalar Scalar Evolution false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "scalar-evolution"
Definition at line 138 of file ScalarEvolution.cpp.
Function Documentation
applyDivisibilityOnMinMaxExpr()
const SCEV * applyDivisibilityOnMinMaxExpr (const SCEV * MinMaxExpr, APInt Divisor, ScalarEvolution & SE) static
Definition at line 15553 of file ScalarEvolution.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, applyDivisibilityOnMinMaxExpr(), assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::ScalarEvolution::getMinMaxExpr(), getNextSCEVDivisibleByDivisor(), getPreviousSCEVDivisibleByDivisor(), llvm::isa(), llvm::ScalarEvolution::isKnownNonNegative(), LHS, and RHS.
Referenced by applyDivisibilityOnMinMaxExpr().
BinomialCoefficient()
const SCEV * BinomialCoefficient (const SCEV * It, unsigned K, ScalarEvolution & SE, Type * ResultTy) static
Compute BC(It, K). The result has width W. Assume, K > 0.
Definition at line 870 of file ScalarEvolution.cpp.
References llvm::countr_zero(), llvm::IntegerType::get(), llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getContext(), llvm::ScalarEvolution::getCouldNotCompute(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getMulExpr(), llvm::APInt::getOneBitSet(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), llvm::SCEV::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getUDivExpr(), llvm::APInt::multiplicativeInverse(), and T.
Referenced by llvm::SCEVAddRecExpr::evaluateAtIteration().
BrPHIToSelect()
bool BrPHIToSelect (DominatorTree & DT, BranchInst * BI, PHINode * Merge, Value *& C, Value *& LHS, Value *& RHS) static
Definition at line 5973 of file ScalarEvolution.cpp.
References assert(), llvm::CallingConv::C, llvm::DominatorTree::dominates(), llvm::BranchInst::getCondition(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BranchInst::getSuccessor(), llvm::BasicBlockEdge::isSingleEdge(), LHS, Merge, and RHS.
BuildConstantFromSCEV()
Constant * BuildConstantFromSCEV (const SCEV * V) static
This builds up a Constant using the ConstantExpr interface.
That way, we will return Constants for objects which aren't represented by a SCEVConstant, because SCEVConstant is restricted to ConstantInt. Returns NULL if the SCEV isn't representable as a Constant.
Definition at line 9930 of file ScalarEvolution.cpp.
References assert(), BuildConstantFromSCEV(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::ConstantExpr::getAdd(), llvm::ConstantExpr::getGetElementPtr(), llvm::Type::getInt8Ty(), llvm::SCEVCastExpr::getOperand(), llvm::ConstantExpr::getPtrToInt(), llvm::ConstantExpr::getTrunc(), llvm::SCEVCastExpr::getType(), llvm::Value::getType(), llvm::Type::isPointerTy(), llvm_unreachable, llvm::SCEVNAryExpr::operands(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scPtrToInt, llvm::scSequentialUMinExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, llvm::scVScale, and llvm::scZeroExtend.
Referenced by BuildConstantFromSCEV().
canConstantEvolve()
bool canConstantEvolve (Instruction * I, const Loop * L) static
Determine whether this instruction can constant evolve within this loop assuming its operands can all constant evolve.
Definition at line 9611 of file ScalarEvolution.cpp.
References CanConstantFold(), I, and llvm::isa().
Referenced by EvaluateExpression(), getConstantEvolvingPHI(), and getConstantEvolvingPHIOperands().
CanConstantFold()
bool CanConstantFold (const Instruction * I) static
Return true if we can constant fold an instruction of the specified type, assuming that all operands were constants.
Definition at line 9597 of file ScalarEvolution.cpp.
References llvm::canConstantFoldCallTo(), llvm::dyn_cast(), F, I, and llvm::isa().
Referenced by canConstantEvolve().
Choose()
uint64_t Choose (uint64_t n, uint64_t k, bool & Overflow) static
Compute the result of "n choose k", the binomial coefficient.
If an intermediate computation overflows, Overflow will be set and the return will be garbage. Overflow is not cleared on absence of overflow.
Definition at line 3043 of file ScalarEvolution.cpp.
References umul_ov().
Referenced by llvm::ScalarEvolution::getMulExpr().
CollectAddOperandsWithScales()
bool CollectAddOperandsWithScales (SmallDenseMap< const SCEV *, APInt, 16 > & M, SmallVectorImpl< const SCEV * > & NewOps, APInt & AccumulatedConstant, ArrayRef< const SCEV * > Ops, const APInt & Scale, ScalarEvolution & SE) static
Process the given Ops list, which is a list of operands to be added under the given scale, update the given map.
This is a helper function for getAddRecExpr. As an example of what it does, given a sequence of operands that would form an add expression like this:
m + n + 13 + (A * (o + p + (B * (q + m + 29)))) + r + (-1 * r)
where A and B are constants, update the map with these values:
(m, 1+A*B), (n, 1), (o, A), (p, A), (q, A*B), (r, 0)
and add 13 + A*B*29 to AccumulatedConstant. This will allow getAddRecExpr to produce this:
13+A*B*29 + n + (m * (1+A*B)) + ((o + p) * A) + (q * A*B)
This form often exposes folding opportunities that are hidden in the original operand list.
Return true iff it appears that any interesting folding opportunities may be exposed. This helps getAddRecExpr short-circuit extra work in the common case where no interesting opportunities are present, and is also used as a check to avoid infinite recursion.
Definition at line 2225 of file ScalarEvolution.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::Add, llvm::CallingConv::C, llvm::cast(), CollectAddOperandsWithScales(), llvm::drop_begin(), llvm::dyn_cast(), llvm::ScalarEvolution::getMulExpr(), llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::isa(), Mul, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by CollectAddOperandsWithScales(), and llvm::ScalarEvolution::getAddExpr().
collectDivisibilityInformation()
bool collectDivisibilityInformation (ICmpInst::Predicate Predicate, const SCEV * LHS, const SCEV * RHS, DenseMap< const SCEV *, const SCEV * > & DivInfo, DenseMap< const SCEV *, APInt > & Multiples, ScalarEvolution & SE) static
Definition at line 15520 of file ScalarEvolution.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getUDivExpr(), llvm::CmpInst::ICMP_EQ, LHS, llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_URem(), llvm::SCEVPatternMatch::m_scev_Zero(), llvm::SCEVPatternMatch::m_SCEVUnknown(), llvm::PatternMatch::match(), and RHS.
CompareSCEVComplexity()
std::optional< int > CompareSCEVComplexity (const LoopInfo *const LI, const SCEV * LHS, const SCEV * RHS, DominatorTree & DT, unsigned Depth = 0) static
Definition at line 660 of file ScalarEvolution.cpp.
References assert(), llvm::cast(), CompareSCEVComplexity(), CompareValueComplexity(), llvm::Depth, llvm::DominatorTree::dominates(), llvm::SCEVConstant::getAPInt(), llvm::APInt::getBitWidth(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::SCEVAddRecExpr::getLoop(), getType(), llvm::SCEVUnknown::getValue(), LHS, llvm_unreachable, MaxSCEVCompareDepth, RA, RHS, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scPtrToInt, llvm::scSequentialUMinExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, llvm::scVScale, llvm::scZeroExtend, llvm::ArrayRef< T >::size(), llvm::APInt::ult(), and X.
Referenced by CompareSCEVComplexity(), and GroupByComplexity().
CompareValueComplexity()
int CompareValueComplexity (const LoopInfo *const LI, Value * LV, Value * RV, unsigned Depth) static
Compare the two values LV and RV in terms of their "complexity" where "complexity" is a partial (and somewhat ad-hoc) relation used to order operands in SCEV expressions.
Definition at line 580 of file ScalarEvolution.cpp.
References llvm::cast(), CompareValueComplexity(), llvm::Depth, llvm::dyn_cast(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopDepth(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Value::getValueID(), llvm::GlobalValue::isInternalLinkage(), llvm::Type::isPointerTy(), llvm::GlobalValue::isPrivateLinkage(), MaxValueCompareDepth, RA, and llvm::seq().
Referenced by CompareSCEVComplexity(), and CompareValueComplexity().
constantFoldAndGroupOps()
template<typename FoldT, typename IsIdentityT, typename IsAbsorberT> const SCEV * constantFoldAndGroupOps (ScalarEvolution & SE, LoopInfo & LI, DominatorTree & DT, SmallVectorImpl< const SCEV * > & Ops, FoldT Fold, IsIdentityT IsIdentity, IsAbsorberT IsAbsorber) static
Performs a number of common optimizations on the passed Ops.
If the whole expression reduces down to a single operand, it will be returned.
The following optimizations are performed:
Fold constants using the Fold function.
Remove identity constants satisfying IsIdentity.
If a constant satisfies IsAbsorber, return it.
Sort operands by complexity.
Definition at line 832 of file ScalarEvolution.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, assert(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::SCEVConstant::getAPInt(), llvm::ScalarEvolution::getConstant(), and GroupByComplexity().
Referenced by llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMinMaxExpr(), and llvm::ScalarEvolution::getMulExpr().
containsConstantInAddMulChain()
bool containsConstantInAddMulChain (const SCEV * StartExpr) static
Determine if any of the operands in this SCEV are a constant or if any of the add or multiply expressions in this SCEV contain a constant.
Definition at line 3068 of file ScalarEvolution.cpp.
References F, and llvm::isa().
Referenced by llvm::ScalarEvolution::getMulExpr().
createNodeForSelectViaUMinSeq() [1/2]
std::optional< const SCEV * > createNodeForSelectViaUMinSeq (ScalarEvolution * SE, const SCEV * CondExpr, const SCEV * TrueExpr, const SCEV * FalseExpr) static
Definition at line 6236 of file ScalarEvolution.cpp.
References assert(), llvm::CallingConv::C, llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getNotSCEV(), llvm::SCEV::getType(), llvm::ScalarEvolution::getUMinExpr(), llvm::isa(), llvm::Type::isIntegerTy(), and X.
Referenced by createNodeForSelectViaUMinSeq().
createNodeForSelectViaUMinSeq() [2/2]
std::optional< const SCEV * > createNodeForSelectViaUMinSeq (ScalarEvolution * SE, Value * Cond, Value * TrueVal, Value * FalseVal) static
Definition at line 6269 of file ScalarEvolution.cpp.
References Cond, createNodeForSelectViaUMinSeq(), llvm::ScalarEvolution::getSCEV(), and llvm::isa().
EvaluateConstantChrecAtConstant()
ConstantInt * EvaluateConstantChrecAtConstant (const SCEVAddRecExpr * AddRec, ConstantInt * C, ScalarEvolution & SE) static
Definition at line 9443 of file ScalarEvolution.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getConstant(), and llvm::isa().
Referenced by llvm::SCEVAddRecExpr::getNumIterationsInRange(), SolveQuadraticAddRecExact(), and SolveQuadraticAddRecRange().
EvaluateExpression()
Constant * EvaluateExpression (Value * V, const Loop * L, DenseMap< Instruction *, Constant * > & Vals, const DataLayout & DL, const TargetLibraryInfo * TLI) static
EvaluateExpression - Given an expression that passes the getConstantEvolvingPHI predicate, evaluate its value assuming the PHI node in the loop has the value PHIVal.
If we can't fold this expression for some reason, return null.
Definition at line 9687 of file ScalarEvolution.cpp.
References llvm::CallingConv::C, canConstantEvolve(), llvm::ConstantFoldInstOperands(), DL, llvm::dyn_cast(), EvaluateExpression(), I, llvm::isa(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by EvaluateExpression().
extractConstantWithoutWrapping() [1/2]
APInt extractConstantWithoutWrapping (ScalarEvolution & SE, const APInt & ConstantStart, const SCEV * Step) static
Definition at line 1507 of file ScalarEvolution.cpp.
References llvm::BitWidth, llvm::APInt::getBitWidth(), llvm::ScalarEvolution::getMinTrailingZeros(), llvm::APInt::trunc(), and llvm::APInt::zext().
extractConstantWithoutWrapping() [2/2]
APInt extractConstantWithoutWrapping (ScalarEvolution & SE, const SCEVConstant * ConstantTerm, const SCEVAddExpr * WholeAddExpr) static
Definition at line 1486 of file ScalarEvolution.cpp.
References llvm::BitWidth, llvm::CallingConv::C, E(), llvm::SCEVConstant::getAPInt(), llvm::ScalarEvolution::getMinTrailingZeros(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), and I.
Referenced by llvm::ScalarEvolution::getSignExtendExprImpl(), and llvm::ScalarEvolution::getZeroExtendExprImpl().
gcd()
APInt gcd (const SCEVConstant * C1, const SCEVConstant * C2)
Definition at line 3601 of file ScalarEvolution.cpp.
References A(), llvm::APInt::abs(), B(), llvm::SCEVConstant::getAPInt(), and llvm::APIntOps::GreatestCommonDivisor().
getConstantEvolvingPHI()
PHINode * getConstantEvolvingPHI (Value * V, const Loop * L) static
getConstantEvolvingPHI - Given an LLVM value and a loop, return a PHI node in the loop that V is derived from.
We allow arbitrary operations along the way, but the operands of an operation must either be constants or a value derived from a constant PHI. If this expression does not fit with these constraints, return null.
Definition at line 9671 of file ScalarEvolution.cpp.
References canConstantEvolve(), llvm::dyn_cast(), getConstantEvolvingPHIOperands(), and I.
getConstantEvolvingPHIOperands()
PHINode * getConstantEvolvingPHIOperands (Instruction * UseInst, const Loop * L, DenseMap< Instruction *, PHINode * > & PHIMap, unsigned Depth) static
getConstantEvolvingPHIOperands - Implement getConstantEvolvingPHI by recursing through each instruction operand until reaching a loop header phi.
Definition at line 9629 of file ScalarEvolution.cpp.
References canConstantEvolve(), llvm::Depth, llvm::dyn_cast(), getConstantEvolvingPHIOperands(), llvm::isa(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), MaxConstantEvolvingDepth, llvm::User::operands(), P, and PHI.
Referenced by getConstantEvolvingPHI(), and getConstantEvolvingPHIOperands().
getConstantTripCount()
unsigned getConstantTripCount (const SCEVConstant * ExitCount) static
Definition at line 8273 of file ScalarEvolution.cpp.
References llvm::APInt::getActiveBits(), llvm::ConstantInt::getValue(), llvm::SCEVConstant::getValue(), and llvm::ConstantInt::getZExtValue().
Referenced by llvm::ScalarEvolution::getSmallConstantMaxTripCount(), llvm::ScalarEvolution::getSmallConstantTripCount(), and llvm::ScalarEvolution::getSmallConstantTripCount().
getExtendAddRecStart()
template<typename ExtendOpTy> const SCEV * getExtendAddRecStart (const SCEVAddRecExpr * AR, Type * Ty, ScalarEvolution * SE, unsigned Depth) static
Definition at line 1392 of file ScalarEvolution.cpp.
References llvm::Depth, llvm::ScalarEvolution::getAddExpr(), getPreStartForExtend(), llvm::SCEVAddRecExpr::getStart(), and llvm::SCEVAddRecExpr::getStepRecurrence().
Referenced by llvm::ScalarEvolution::getSignExtendExprImpl(), and llvm::ScalarEvolution::getZeroExtendExprImpl().
getNextSCEVDivisibleByDivisor()
const SCEV * getNextSCEVDivisibleByDivisor (const SCEV * Expr, const APInt & DivisorVal, ScalarEvolution & SE) static
Definition at line 15506 of file ScalarEvolution.cpp.
References llvm::ScalarEvolution::getConstant(), llvm::APInt::isNegative(), llvm::APInt::isNonPositive(), llvm::APInt::isZero(), llvm::SCEVPatternMatch::m_scev_APInt(), llvm::PatternMatch::match(), and llvm::APInt::urem().
Referenced by applyDivisibilityOnMinMaxExpr(), and llvm::ScalarEvolution::LoopGuards::rewrite().
getOtherIncomingValue()
Constant * getOtherIncomingValue (PHINode * PN, BasicBlock * BB) static
Definition at line 9729 of file ScalarEvolution.cpp.
References llvm::dyn_cast(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), and llvm::PHINode::getNumIncomingValues().
getPreStartForExtend()
template<typename ExtendOpTy> const SCEV * getPreStartForExtend (const SCEVAddRecExpr * AR, Type * Ty, ScalarEvolution * SE, unsigned Depth) static
Definition at line 1315 of file ScalarEvolution.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::BitWidth, llvm::Depth, llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SCEV::FlagAnyWrap, llvm::SCEV::FlagNUW, llvm::IntegerType::get(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getBackedgeTakenCount(), llvm::ScalarEvolution::getContext(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEVAddRecExpr::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::isa(), llvm::ScalarEvolution::isKnownPositive(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::ScalarEvolution::maskFlags(), llvm::SCEVNAryExpr::operands(), llvm::ScalarEvolution::setNoWrapFlags(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by getExtendAddRecStart().
getPreviousSCEVDivisibleByDivisor()
const SCEV * getPreviousSCEVDivisibleByDivisor (const SCEV * Expr, const APInt & DivisorVal, ScalarEvolution & SE) static
Definition at line 15491 of file ScalarEvolution.cpp.
References llvm::ScalarEvolution::getConstant(), llvm::APInt::isNegative(), llvm::APInt::isNonPositive(), llvm::SCEVPatternMatch::m_scev_APInt(), llvm::PatternMatch::match(), and llvm::APInt::urem().
Referenced by applyDivisibilityOnMinMaxExpr().
GetQuadraticEquation()
std::optional< std::tuple< APInt, APInt, APInt, APInt, unsigned > > GetQuadraticEquation (const SCEVAddRecExpr * AddRec) static
For a given quadratic addrec, generate coefficients of the corresponding quadratic equation, multiplied by a common value to ensure that they are integers.
The returned value is a tuple { A, B, C, M, BitWidth }, where Ax^2 + Bx + C is the quadratic function, M is the value that A, B and C were multiplied by, and BitWidth is the bit width of the original addrec coefficients. This function returns std::nullopt if the addrec coefficients are not compile- time constants.
Definition at line 10314 of file ScalarEvolution.cpp.
References A(), assert(), B(), llvm::BitWidth, llvm::CallingConv::C, llvm::dbgs(), llvm::dyn_cast(), llvm::SCEVConstant::getAPInt(), llvm::APInt::getBitWidth(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), LLVM_DEBUG, N, NC, and T.
Referenced by SolveQuadraticAddRecExact(), and SolveQuadraticAddRecRange().
getRangeForAffineARHelper()
ConstantRange getRangeForAffineARHelper (APInt Step, const ConstantRange & StartRange, const APInt & MaxBECount, bool Signed) static
Definition at line 7032 of file ScalarEvolution.cpp.
References llvm::APInt::abs(), assert(), llvm::BitWidth, llvm::ConstantRange::contains(), llvm::APInt::getBitWidth(), llvm::ConstantRange::getBitWidth(), llvm::ConstantRange::getLower(), llvm::APInt::getMaxValue(), llvm::ConstantRange::getNonEmpty(), llvm::ConstantRange::getUpper(), llvm::ConstantRange::isFullSet(), llvm::APInt::isNegative(), llvm::Offset, and Signed.
GetRangeFromMetadata()
std::optional< ConstantRange > GetRangeFromMetadata (Value * V) static
Helper method to assign a range to V from metadata present in the IR.
Definition at line 6458 of file ScalarEvolution.cpp.
References A(), llvm::dyn_cast(), llvm::getConstantRangeFromMetadata(), I, and Range.
getSignedOverflowLimitForStep()
const SCEV * getSignedOverflowLimitForStep (const SCEV * Step, ICmpInst::Predicate * Pred, ScalarEvolution * SE) static
Definition at line 1223 of file ScalarEvolution.cpp.
References llvm::BitWidth, llvm::ScalarEvolution::getConstant(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::ScalarEvolution::getSignedRangeMax(), llvm::ScalarEvolution::getSignedRangeMin(), llvm::SCEV::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::ScalarEvolution::isKnownNegative(), and llvm::ScalarEvolution::isKnownPositive().
getUnsignedOverflowLimitForStep()
const SCEV * getUnsignedOverflowLimitForStep (const SCEV * Step, ICmpInst::Predicate * Pred, ScalarEvolution * SE) static
Definition at line 1243 of file ScalarEvolution.cpp.
References llvm::BitWidth, llvm::ScalarEvolution::getConstant(), llvm::APInt::getMinValue(), llvm::SCEV::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getUnsignedRangeMax(), and llvm::CmpInst::ICMP_ULT.
GroupByComplexity()
void GroupByComplexity (SmallVectorImpl< const SCEV * > & Ops, LoopInfo * LI, DominatorTree & DT) static
Given a list of SCEV objects, order them by their complexity, and group objects of the same complexity together by value.
When this routine is finished, we know that any duplicates in the vector are consecutive and that complexity is monotonically increasing.
Note that we go take special precautions to ensure that we get deterministic results from this routine. In other words, we don't want the results of this to depend on where the addresses of various SCEV objects happened to land in memory.
Definition at line 770 of file ScalarEvolution.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, CompareSCEVComplexity(), llvm::SCEV::getSCEVType(), LHS, RHS, llvm::stable_sort(), and std::swap().
Referenced by constantFoldAndGroupOps().
hasHugeExpression()
bool hasHugeExpression (ArrayRef< const SCEV * > Ops) static
Returns true if Ops contains a huge SCEV (the subtree of S contains at least HugeExprThreshold nodes).
Definition at line 816 of file ScalarEvolution.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::any_of(), llvm::SCEV::getExpressionSize(), and HugeExprThreshold.
Referenced by llvm::ScalarEvolution::getAddExpr(), and llvm::ScalarEvolution::getMulExpr().
HasSameValue()
bool HasSameValue (const SCEV * A, const SCEV * B) static
SCEV structural equivalence is usually sufficient for testing whether two expressions are equal, however for the purposes of looking for a condition guarding a loop, it can be useful to be a little more general, since a front-end may have replicated the controlling expression.
Definition at line 10770 of file ScalarEvolution.cpp.
References A(), B(), llvm::dyn_cast(), and llvm::isa().
Referenced by llvm::ScalarEvolution::SimplifyICmpOperands().
impliesPoison()
bool impliesPoison (const SCEV * AssumedPoison, const SCEV * S) static
Return true if V is poison given that AssumedPoison is already poison.
Definition at line 4173 of file ScalarEvolution.cpp.
References llvm::set_is_subset(), and llvm::visitAll().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ScalarEvolutionWrapperPass , "scalar-evolution" , "Scalar Evolution Analysis" , false , true)
References INITIALIZE_PASS_DEPENDENCY.
insertFoldCacheEntry()
void insertFoldCacheEntry (const ScalarEvolution::FoldID & ID, const SCEV * S, DenseMap< ScalarEvolution::FoldID, const SCEV * > & FoldCache, DenseMap< const SCEV *, SmallVector< ScalarEvolution::FoldID, 2 > > & FoldCacheUser) static
Definition at line 1518 of file ScalarEvolution.cpp.
References assert(), llvm::count(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), and std::swap().
Referenced by llvm::ScalarEvolution::getSignExtendExpr(), and llvm::ScalarEvolution::getZeroExtendExpr().
isDivisibilityGuard()
bool isDivisibilityGuard (const SCEV * LHS, const SCEV * RHS, ScalarEvolution & SE) static
Definition at line 15544 of file ScalarEvolution.cpp.
References LHS, llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_URem(), llvm::PatternMatch::match(), RHS, X, and Y.
isIntegerLoopHeaderPHI()
const Loop * isIntegerLoopHeaderPHI (const PHINode * PN, LoopInfo & LI) static
Definition at line 5414 of file ScalarEvolution.cpp.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Value::getType(), and llvm::Type::isIntegerTy().
Referenced by llvm::ScalarEvolution::createAddRecFromPHIWithCasts().
isKnownPredicateExtendIdiom()
bool isKnownPredicateExtendIdiom (CmpPredicate Pred, const SCEV * LHS, const SCEV * RHS) static
Definition at line 12836 of file ScalarEvolution.cpp.
References llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, LHS, llvm_unreachable, llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_SExt(), llvm::SCEVPatternMatch::m_scev_Specific(), llvm::SCEVPatternMatch::m_scev_ZExt(), llvm::PatternMatch::match(), RHS, and std::swap().
IsKnownPredicateViaAddRecStart()
bool IsKnownPredicateViaAddRecStart (ScalarEvolution & SE, CmpPredicate Pred, const SCEV * LHS, const SCEV * RHS) static
Definition at line 12606 of file ScalarEvolution.cpp.
References llvm::cast(), llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::ScalarEvolution::isKnownPredicate(), llvm::ICmpInst::isRelational(), llvm::CmpInst::isSigned(), LHS, llvm::SCEVPatternMatch::m_Loop(), llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_AffineAddRec(), llvm::SCEVPatternMatch::m_scev_Specific(), llvm::SCEVPatternMatch::m_SpecificLoop(), llvm::PatternMatch::match(), and RHS.
IsKnownPredicateViaMinOrMax()
bool IsKnownPredicateViaMinOrMax (ScalarEvolution & SE, CmpPredicate Pred, const SCEV * LHS, const SCEV * RHS) static
Is LHS Pred RHS true on the virtue of LHS or RHS being a Min or Max expression?
Definition at line 12635 of file ScalarEvolution.cpp.
References llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, IsMinMaxConsistingOf(), LHS, llvm_unreachable, RHS, and std::swap().
IsMinMaxConsistingOf()
template<typename MinMaxExprType> bool IsMinMaxConsistingOf (const SCEV * MaybeMinMaxExpr, const SCEV * Candidate) static
Is MaybeMinMaxExpr an (U|S)(Min|Max) of Candidate and some other values?
Definition at line 12597 of file ScalarEvolution.cpp.
References llvm::dyn_cast(), and llvm::is_contained().
Referenced by IsKnownPredicateViaMinOrMax().
isSimpleCastedPHI()
Type * isSimpleCastedPHI (const SCEV * Op, const SCEVUnknown * SymbolicPHI, bool & Signed, ScalarEvolution & SE) static
Helper function to createAddRecFromPHIWithCasts.
We have a phi node whose symbolic (unknown) SCEV is SymbolicPHI, which is updated via the loop backedge by a SCEVAddExpr, possibly also with a few casts on the way. This function checks if Op, an operand of this SCEVAddExpr, follows one of the following patterns: Op == (SExt ix (Trunc iy (SymbolicPHI) to ix) to iy) Op == (ZExt ix (Trunc iy (SymbolicPHI) to ix) to iy) If the SCEV expression of Op conforms with one of the expected patterns we return the type of the truncation operation, and indicate whether the truncated type should be treated as signed/unsigned by setting Signed to true/false, respectively.
Definition at line 5383 of file ScalarEvolution.cpp.
References llvm::cast(), llvm::SCEVUnknown::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::SCEVPatternMatch::m_scev_SExt(), llvm::SCEVPatternMatch::m_scev_Specific(), llvm::SCEVPatternMatch::m_scev_Trunc(), llvm::SCEVPatternMatch::m_scev_ZExt(), llvm::PatternMatch::match(), and Signed.
MatchBinaryOp()
std::optional< BinaryOp > MatchBinaryOp (Value * V, const DataLayout & DL, AssumptionCache & AC, const DominatorTree & DT, const Instruction * CxtI) static
Try to map V into a BinaryOp, and return std::nullopt on failure.
Definition at line 5277 of file ScalarEvolution.cpp.
References llvm::BitWidth, llvm::cast(), DL, llvm::dyn_cast(), llvm::APInt::getOneBitSet(), II, llvm::isOverflowIntrinsicNoWrap(), Signed, and X.
MatchBinarySub()
bool MatchBinarySub (const SCEV * S, const SCEV *& LHS, const SCEV *& RHS) static
Definition at line 10794 of file ScalarEvolution.cpp.
References LHS, llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_Add(), llvm::SCEVPatternMatch::m_scev_AllOnes(), llvm::SCEVPatternMatch::m_scev_Mul(), llvm::PatternMatch::match(), Op0, and RHS.
Referenced by llvm::ScalarEvolution::LoopGuards::rewrite(), and llvm::ScalarEvolution::SimplifyICmpOperands().
MatchNotExpr()
const SCEV * MatchNotExpr (const SCEV * Expr) static
If Expr computes ~A, return A else return nullptr.
Definition at line 4617 of file ScalarEvolution.cpp.
References llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_Add(), llvm::SCEVPatternMatch::m_scev_AllOnes(), llvm::SCEVPatternMatch::m_scev_Mul(), and llvm::PatternMatch::match().
Referenced by llvm::ScalarEvolution::getNotSCEV().
MinOptional()
std::optional< APInt > MinOptional (std::optional< APInt > X, std::optional< APInt > Y) static
Helper function to compare optional APInts: (a) if X and Y both exist, return min(X, Y), (b) if neither X nor Y exist, return std::nullopt, (c) if exactly one of X and Y exists, return that value.
Definition at line 10367 of file ScalarEvolution.cpp.
References llvm::APInt::slt(), X, and Y.
Referenced by SolveQuadraticAddRecRange().
PrintLoopInfo()
void PrintLoopInfo (raw_ostream & OS, ScalarEvolution * SE, const Loop * L) static
Definition at line 13835 of file ScalarEvolution.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::ScalarEvolution::getBackedgeTakenCount(), llvm::ScalarEvolution::getConstantMaxBackedgeTakenCount(), llvm::ScalarEvolution::getExitCount(), llvm::Value::getName(), llvm::ScalarEvolution::getPredicatedBackedgeTakenCount(), llvm::ScalarEvolution::getPredicatedConstantMaxBackedgeTakenCount(), llvm::ScalarEvolution::getPredicatedExitCount(), llvm::ScalarEvolution::getPredicatedSymbolicMaxBackedgeTakenCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::ScalarEvolution::getSymbolicMaxBackedgeTakenCount(), llvm::ScalarEvolution::hasLoopInvariantBackedgeTakenCount(), I, llvm::isa(), llvm::ScalarEvolution::isBackedgeTakenCountMaxOrZero(), P, PrintLoopInfo(), PrintSCEVWithTypeHint(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ScalarEvolution::SymbolicMaximum.
Referenced by llvm::ScalarEvolution::print(), and PrintLoopInfo().
PrintSCEVWithTypeHint()
void PrintSCEVWithTypeHint (raw_ostream & OS, const SCEV * S) static
When printing a top-level SCEV for trip counts, it's helpful to include a type for constants which are otherwise hard to disambiguate.
Definition at line 13829 of file ScalarEvolution.cpp.
References llvm::SCEV::getType(), and llvm::isa().
Referenced by PrintLoopInfo().
PushDefUseChildren()
void PushDefUseChildren (Instruction * I, SmallVectorImpl< Instruction * > & Worklist, SmallPtrSetImpl< Instruction * > & Visited) static
Push users of the given Instruction onto the given Worklist.
Definition at line 4877 of file ScalarEvolution.cpp.
References llvm::cast(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
PushLoopPHIs()
void PushLoopPHIs (const Loop * L, SmallVectorImpl< Instruction * > & Worklist, SmallPtrSetImpl< Instruction * > & Visited) static
Push PHI nodes in the header of the given loop onto the given Worklist.
Definition at line 8428 of file ScalarEvolution.cpp.
References llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::ScalarEvolution::forgetLoop().
SCEVMinMaxExprContains()
bool SCEVMinMaxExprContains (const SCEV * Root, const SCEV * OperandToFind, SCEVTypes RootKind)
Definition at line 6092 of file ScalarEvolution.cpp.
References llvm::SCEVSequentialMinMaxExpr::getEquivalentNonSequentialSCEVType(), llvm::SCEV::getSCEVType(), llvm::scZeroExtend, and llvm::visitAll().
scevUnconditionallyPropagatesPoisonFromOperands()
bool scevUnconditionallyPropagatesPoisonFromOperands (SCEVTypes Kind) static
Definition at line 4114 of file ScalarEvolution.cpp.
References llvm_unreachable, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scPtrToInt, llvm::scSequentialUMinExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scSMinExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUMinExpr, llvm::scUnknown, llvm::scVScale, and llvm::scZeroExtend.
SolveLinEquationWithOverflow()
const SCEV * SolveLinEquationWithOverflow (const APInt & A, const SCEV * B, SmallVectorImpl< const SCEVPredicate * > * Predicates, ScalarEvolution & SE, const Loop * L) static
Finds the minimum unsigned root of the following equation:
A * X = B (mod N)
where N = 2^BW and BW is the common bit width of A and B. The signedness of A and B isn't important.
If the equation does not have a solution, SCEVCouldNotCompute is returned.
Definition at line 10247 of file ScalarEvolution.cpp.
References A(), assert(), B(), D(), llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getCouldNotCompute(), llvm::ScalarEvolution::getEqualPredicate(), llvm::ScalarEvolution::getMinTrailingZeros(), llvm::ScalarEvolution::getMulExpr(), llvm::APInt::getOneBitSet(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::ScalarEvolution::getURemExpr(), llvm::ScalarEvolution::getZero(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ScalarEvolution::isKnownPredicate(), llvm::APInt::multiplicativeInverse(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::APInt::zext().
SolveQuadraticAddRecExact()
std::optional< APInt > SolveQuadraticAddRecExact (const SCEVAddRecExpr * AddRec, ScalarEvolution & SE) static
Let c(n) be the value of the quadratic chrec {L,+,M,+,N} after n iterations.
The values L, M, N are assumed to be signed, and they should all have the same bit widths. Find the least n >= 0 such that c(n) = 0 in the arithmetic modulo 2^BW, where BW is the bit width of the addrec's coefficients. If the calculated value is a BW-bit integer (for BW > 1), it will be returned as such, otherwise the bit width of the returned value may be greater than BW.
This function returns std::nullopt if (a) the addrec coefficients are not constant, or (b) SolveQuadraticEquationWrap was unable to find a solution. For cases like x^2 = 5, no integer solutions exist, in other cases an integer solution may exist, but SolveQuadraticEquationWrap may fail to find it.
Definition at line 10416 of file ScalarEvolution.cpp.
References A(), B(), llvm::BitWidth, llvm::CallingConv::C, llvm::dbgs(), EvaluateConstantChrecAtConstant(), llvm::ScalarEvolution::getContext(), GetQuadraticEquation(), LLVM_DEBUG, llvm::APIntOps::SolveQuadraticEquationWrap(), T, TruncIfPossible(), and X.
SolveQuadraticAddRecRange()
std::optional< APInt > SolveQuadraticAddRecRange (const SCEVAddRecExpr * AddRec, const ConstantRange & Range, ScalarEvolution & SE) static
Let c(n) be the value of the quadratic chrec {0,+,M,+,N} after n iterations.
The values M, N are assumed to be signed, and they should all have the same bit widths. Find the least n such that c(n) does not belong to the given range, while c(n-1) does.
This function returns std::nullopt if (a) the addrec coefficients are not constant, or (b) SolveQuadraticEquationWrap was unable to find a solution for the bounds of the range.
Definition at line 10449 of file ScalarEvolution.cpp.
References A(), assert(), B(), llvm::BitWidth, llvm::CallingConv::C, llvm::dbgs(), EvaluateConstantChrecAtConstant(), llvm::ScalarEvolution::getContext(), llvm::SCEVNAryExpr::getOperand(), GetQuadraticEquation(), llvm::SCEVAddRecExpr::getType(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ConstantInt::getValue(), llvm::SCEV::isZero(), LLVM_DEBUG, llvm::Lower, MinOptional(), Range, llvm::APIntOps::SolveQuadraticEquationWrap(), T, TruncIfPossible(), llvm::Upper, and X.
Referenced by llvm::SCEVAddRecExpr::getNumIterationsInRange().
STATISTIC() [1/3]
STATISTIC (NumBruteForceTripCountsComputed , "Number of loops with trip counts computed by force")
References llvm::VerifySCEV.
STATISTIC() [2/3]
STATISTIC (NumExitCountsComputed , "Number of loop exits with predictable exit counts")
STATISTIC() [3/3]
STATISTIC (NumExitCountsNotComputed , "Number of loop exits without predictable exit counts")
StrengthenNoWrapFlags()
SCEV::NoWrapFlags StrengthenNoWrapFlags (ScalarEvolution * SE, SCEVTypes Type, ArrayRef< const SCEV * > Ops, SCEV::NoWrapFlags Flags) static
Definition at line 2412 of file ScalarEvolution.cpp.
References AbstractManglingParser< Derived, Alloc >::Ops, llvm::all_of(), assert(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEV::FlagNW, llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getUnsignedRange(), llvm::ScalarEvolution::hasFlags(), llvm::isa(), llvm::ScalarEvolution::isKnownNonNegative(), llvm_unreachable, llvm::ConstantRange::makeGuaranteedNoWrapRegion(), llvm::ScalarEvolution::maskFlags(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scMulExpr, and llvm::ScalarEvolution::setFlags().
Referenced by llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), and llvm::ScalarEvolution::getMulExpr().
TruncIfPossible()
std::optional< APInt > TruncIfPossible (std::optional< APInt > X, unsigned BitWidth) static
Helper function to truncate an optional APInt to a given BitWidth.
When solving addrec-related equations, it is preferable to return a value that has the same bit width as the original addrec's coefficients. If the solution fits in the original bit width, truncate it (except for i1). Returning a value of a different bit width may inhibit some optimizations.
In general, a solution to a quadratic equation generated from an addrec may require BW+1 bits, where BW is the bit width of the addrec's coefficients. The reason is that the coefficients of the quadratic equation are BW+1 bits wide (to avoid truncation when converting from the addrec to the equation).
Definition at line 10391 of file ScalarEvolution.cpp.
References llvm::BitWidth, llvm::isIntN(), and X.
Referenced by SolveQuadraticAddRecExact(), and SolveQuadraticAddRecRange().
umul_ov()
uint64_t umul_ov (uint64_t i, uint64_t j, bool & Overflow) static
Definition at line 3034 of file ScalarEvolution.cpp.
Referenced by Choose(), llvm::SelectionDAG::computeKnownBits(), and llvm::ScalarEvolution::getMulExpr().
Variable Documentation
AddOpsInlineThreshold
cl::opt< unsigned > AddOpsInlineThreshold("scev-addops-inline-threshold", cl::Hidden, cl::desc("Threshold for inlining addition operands into a SCEV"), cl::init(500)) ("scev-addops-inline-threshold" , cl::Hidden , cl::desc("Threshold for inlining addition operands into a SCEV") , cl::init(500)) static
Referenced by llvm::ScalarEvolution::getAddExpr().
Analysis
scalar Scalar Evolution Analysis
Definition at line 14800 of file ScalarEvolution.cpp.
ClassifyExpressions
cl::opt< bool > ClassifyExpressions("scalar-evolution-classify-expressions", cl::Hidden, cl::init(true), cl::desc("When printing analysis, include information on every instruction")) ("scalar-evolution-classify-expressions" , cl::Hidden , cl::init(true) , cl::desc("When printing analysis, include information on every instruction")) static
Referenced by llvm::ScalarEvolution::print().
EnableFiniteLoopControl
cl::opt< bool > EnableFiniteLoopControl("scalar-evolution-finite-loop", cl::Hidden, cl::desc("Handle <= and >= in finite loops"), cl::init(true)) ("scalar-evolution-finite-loop" , cl::Hidden , cl::desc("Handle <= and >= in finite loops") , cl::init(true)) static
evolution
scalar evolution
Definition at line 14799 of file ScalarEvolution.cpp.
false
scalar Scalar Evolution false
Definition at line 14800 of file ScalarEvolution.cpp.
HugeExprThreshold
cl::opt< unsigned > HugeExprThreshold("scalar-evolution-huge-expr-threshold", cl::Hidden, cl::desc("Size of the expression which is considered huge"), cl::init(4096)) ("scalar-evolution-huge-expr-threshold" , cl::Hidden , cl::desc("Size of the expression which is considered huge") , cl::init(4096)) static
Referenced by hasHugeExpression().
MaxAddRecSize
cl::opt< unsigned > MaxAddRecSize("scalar-evolution-max-add-rec-size", cl::Hidden, cl::desc("Max coefficients in AddRec during evolving"), cl::init(8)) ("scalar-evolution-max-add-rec-size" , cl::Hidden , cl::desc("Max coefficients in AddRec during evolving") , cl::init(8)) static
Referenced by llvm::ScalarEvolution::getMulExpr().
MaxArithDepth
cl::opt< unsigned > MaxArithDepth("scalar-evolution-max-arith-depth", cl::Hidden, cl::desc("Maximum depth of recursive arithmetics"), cl::init(32)) ("scalar-evolution-max-arith-depth" , cl::Hidden , cl::desc("Maximum depth of recursive arithmetics") , cl::init(32)) static
Referenced by llvm::ScalarEvolution::getAddExpr(), and llvm::ScalarEvolution::getMulExpr().
MaxBruteForceIterations
cl::opt< unsigned > MaxBruteForceIterations("scalar-evolution-max-iterations", cl::ReallyHidden, cl::desc("Maximum number of iterations SCEV will " "symbolically execute a constant " "derived loop"), cl::init(100)) ("scalar-evolution-max-iterations" , cl::ReallyHidden , cl::desc("Maximum number of iterations SCEV will " "symbolically execute a constant " "derived loop") , cl::init(100)) static
MaxCastDepth
cl::opt< unsigned > MaxCastDepth("scalar-evolution-max-cast-depth", cl::Hidden, cl::desc("Maximum depth of recursive SExt/ZExt/Trunc"), cl::init(8)) ("scalar-evolution-max-cast-depth" , cl::Hidden , cl::desc("Maximum depth of recursive SExt/ZExt/Trunc") , cl::init(8)) static
Referenced by llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::ScalarEvolution::getTruncateExpr(), and llvm::ScalarEvolution::getZeroExtendExprImpl().
MaxConstantEvolvingDepth
cl::opt< unsigned > MaxConstantEvolvingDepth("scalar-evolution-max-constant-evolving-depth", cl::Hidden, cl::desc("Maximum depth of recursive constant evolving"), cl::init(32)) ("scalar-evolution-max-constant-evolving-depth" , cl::Hidden , cl::desc("Maximum depth of recursive constant evolving") , cl::init(32)) static
Referenced by getConstantEvolvingPHIOperands().
MaxLoopGuardCollectionDepth
cl::opt< unsigned > MaxLoopGuardCollectionDepth("scalar-evolution-max-loop-guard-collection-depth", cl::Hidden, cl::desc("Maximum depth for recursive loop guard collection"), cl::init(1)) ("scalar-evolution-max-loop-guard-collection-depth" , cl::Hidden , cl::desc("Maximum depth for recursive loop guard collection") , cl::init(1)) static
MaxPhiSCCAnalysisSize
cl::opt< unsigned > MaxPhiSCCAnalysisSize("scalar-evolution-max-scc-analysis-depth", cl::Hidden, cl::desc("Maximum amount of nodes to process while searching SCEVUnknown " "Phi strongly connected components"), cl::init(8)) ("scalar-evolution-max-scc-analysis-depth" , cl::Hidden , cl::desc("Maximum amount of nodes to process while searching SCEVUnknown " "Phi strongly connected components") , cl::init(8)) static
MaxSCEVCompareDepth
cl::opt< unsigned > MaxSCEVCompareDepth("scalar-evolution-max-scev-compare-depth", cl::Hidden, cl::desc("Maximum depth of recursive SCEV complexity comparisons"), cl::init(32)) ("scalar-evolution-max-scev-compare-depth" , cl::Hidden , cl::desc("Maximum depth of recursive SCEV complexity comparisons") , cl::init(32)) static
Referenced by CompareSCEVComplexity().
MaxSCEVOperationsImplicationDepth
cl::opt< unsigned > MaxSCEVOperationsImplicationDepth("scalar-evolution-max-scev-operations-implication-depth", cl::Hidden, cl::desc("Maximum depth of recursive SCEV operations implication analysis"), cl::init(2)) ("scalar-evolution-max-scev-operations-implication-depth" , cl::Hidden , cl::desc("Maximum depth of recursive SCEV operations implication analysis") , cl::init(2)) static
MaxValueCompareDepth
cl::opt< unsigned > MaxValueCompareDepth("scalar-evolution-max-value-compare-depth", cl::Hidden, cl::desc("Maximum depth of recursive value complexity comparisons"), cl::init(2)) ("scalar-evolution-max-value-compare-depth" , cl::Hidden , cl::desc("Maximum depth of recursive value complexity comparisons") , cl::init(2)) static
Referenced by CompareValueComplexity().
MulOpsInlineThreshold
cl::opt< unsigned > MulOpsInlineThreshold("scev-mulops-inline-threshold", cl::Hidden, cl::desc("Threshold for inlining multiplication operands into a SCEV"), cl::init(32)) ("scev-mulops-inline-threshold" , cl::Hidden , cl::desc("Threshold for inlining multiplication operands into a SCEV") , cl::init(32)) static
Referenced by llvm::ScalarEvolution::getMulExpr().
RangeIterThreshold
cl::opt< unsigned > RangeIterThreshold("scev-range-iter-threshold", cl::Hidden, cl::desc("Threshold for switching to iteratively computing SCEV ranges"), cl::init(32)) ("scev-range-iter-threshold" , cl::Hidden , cl::desc("Threshold for switching to iteratively computing SCEV ranges") , cl::init(32)) static
UseContextForNoWrapFlagInference
cl::opt< bool > UseContextForNoWrapFlagInference("scalar-evolution-use-context-for-no-wrap-flag-strenghening", cl::Hidden, cl::desc("Infer nuw/nsw flags using context where suitable"), cl::init(true)) ("scalar-evolution-use-context-for-no-wrap-flag-strenghening" , cl::Hidden , cl::desc("Infer nuw/nsw flags using context where suitable") , cl::init(true)) static
Referenced by llvm::ScalarEvolution::getStrengthenedNoWrapFlagsFromBinOp().
UseExpensiveRangeSharpening
cl::opt< bool > UseExpensiveRangeSharpening("scalar-evolution-use-expensive-range-sharpening", cl::Hidden, cl::init(false), cl::desc("Use more powerful methods of sharpening expression ranges. May " "be costly in terms of compile time")) ("scalar-evolution-use-expensive-range-sharpening" , cl::Hidden , cl::init(false) , cl::desc("Use more powerful methods of sharpening expression ranges. May " "be costly in terms of compile time")) static
VerifyIR
cl::opt< bool > VerifyIR("scev-verify-ir", cl::Hidden, cl::desc("Verify IR correctness when making sensitive SCEV queries (slow)"), cl::init(false)) ("scev-verify-ir" , cl::Hidden , cl::desc("Verify IR correctness when making sensitive SCEV queries (slow)") , cl::init(false)) static
Referenced by llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond(), and llvm::ScalarEvolution::isLoopBackedgeGuardedByCond().
VerifySCEVOpt
cl::opt< bool, true > VerifySCEVOpt("verify-scev", cl::Hidden, cl::location(VerifySCEV), cl::desc("Verify ScalarEvolution's backedge taken counts (slow)")) ("verify-scev" , cl::Hidden , cl::location(VerifySCEV) , cl::desc("Verify ScalarEvolution's backedge taken counts (slow)")) static
VerifySCEVStrict
cl::opt< bool > VerifySCEVStrict("verify-scev-strict", cl::Hidden, cl::desc("Enable stricter verification with -verify-scev is passed")) ("verify-scev-strict" , cl::Hidden , cl::desc("Enable stricter verification with -verify-scev is passed")) static
Referenced by llvm::ScalarEvolution::verify().