LLVM: lib/Object/SFrameParser.cpp File Reference
SFrameParser.cpp File Reference
#include "llvm/Object/SFrameParser.h"
#include "llvm/BinaryFormat/SFrame.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
Functions
static Expected< ArrayRef< uint8_t > > getDataSlice (ArrayRef< uint8_t > Data, uint64_t Offset, uint64_t Size)
template<typename T>
static Expected< ArrayRef< T > > getDataSliceAsArrayOf (ArrayRef< uint8_t > Data, uint64_t Offset, uint64_t Count)
template<typename T>
static Expected< const T & > getDataSliceAs (ArrayRef< uint8_t > Data, uint64_t Offset)
template<typename EndianT>
static Error readArray (ArrayRef< uint8_t > Data, uint64_t Count, uint64_t &Offset, SmallVectorImpl< int32_t > &Vec)
template<typename T, endianness E>
static Error readFRE (ArrayRef< uint8_t > Data, uint64_t &Offset, typename SFrameParser< E >::FrameRowEntry &FRE)
static std::optional< int32_t > getOffset (ArrayRef< int32_t > Offsets, size_t Idx)
Function Documentation
getDataSlice()
Expected< ArrayRef< uint8_t > > getDataSlice (ArrayRef< uint8_t > Data, uint64_t Offset, uint64_t Size) static
Definition at line 19 of file SFrameParser.cpp.
References llvm::createStringError(), llvm::Data, llvm::formatv(), llvm::Offset, llvm::SaturatingAdd(), Size, and llvm::object::unexpected_eof.
Referenced by llvm::object::SFrameParser< E >::fdes(), llvm::object::SFrameParser< E >::getAuxHeader(), and getDataSliceAsArrayOf().
getDataSliceAs()
template<typename T> Expected< const T & > getDataSliceAs (ArrayRef< uint8_t > Data, uint64_t Offset) static
Definition at line 47 of file SFrameParser.cpp.
References llvm::Data, getDataSliceAsArrayOf(), and llvm::Offset.
Referenced by llvm::object::SFrameParser< E >::create(), and readFRE().
getDataSliceAsArrayOf()
template<typename T> Expected< ArrayRef< T > > getDataSliceAsArrayOf (ArrayRef< uint8_t > Data, uint64_t Offset, uint64_t Count) static
Definition at line 36 of file SFrameParser.cpp.
References llvm::ArrayRef(), llvm::Count, llvm::Data, getDataSlice(), llvm::Offset, and T.
Referenced by getDataSliceAs(), and readArray().
getOffset()
std::optional< int32_t > getOffset (ArrayRef< int32_t > Offsets, size_t Idx) static
Definition at line 187 of file SFrameParser.cpp.
Referenced by llvm::logicalview::LVLine::getAddress().
readArray()
template<typename EndianT> Error readArray (ArrayRef< uint8_t > Data, uint64_t Count, uint64_t & Offset, SmallVectorImpl< int32_t > & Vec) static
Definition at line 118 of file SFrameParser.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::copy(), llvm::Count, llvm::Data, getDataSliceAsArrayOf(), llvm::Offset, llvm::SmallVectorImpl< T >::resize(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by readFRE().
readFRE()
template<typename T, endianness E> Error readFRE (ArrayRef< uint8_t > Data, uint64_t & Offset, typename SFrameParser< E >::FrameRowEntry & FRE) static
Definition at line 131 of file SFrameParser.cpp.
References llvm::object::createError(), llvm::Data, llvm::formatv(), getDataSliceAs(), llvm::sframe::FREInfo< E >::getOffsetCount(), llvm::sframe::FREInfo< E >::getOffsetSize(), llvm::object::SFrameParser< E >::FrameRowEntry::Info, llvm::sframe::FREInfo< E >::Info, llvm::Offset, llvm::object::SFrameParser< E >::FrameRowEntry::Offsets, readArray(), llvm::object::SFrameParser< E >::FrameRowEntry::StartAddress, and llvm::Expected< T >::takeError().
Referenced by llvm::object::SFrameParser< E >::FallibleFREIterator::inc().