LLVM: lib/Target/SPIRV/SPIRVCBufferAccess.cpp File Reference
SPIRVCBufferAccess.cpp File Reference
#include "SPIRVCBufferAccess.h"
#include "SPIRV.h"
#include "llvm/Frontend/HLSL/CBuffer.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ReplaceConstant.h"
Macros
#define DEBUG_TYPE "spirv-cbuffer-access"
Functions
static Instruction * findHandleDef (GlobalVariable *HandleVar)
static bool replaceCBufferAccesses (Module &M)
INITIALIZE_PASS (SPIRVCBufferAccessLegacy, DEBUG_TYPE, "SPIRV CBuffer Access", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-cbuffer-access"
Definition at line 40 of file SPIRVCBufferAccess.cpp.
Function Documentation
findHandleDef()
Instruction * findHandleDef (GlobalVariable * HandleVar) static
Definition at line 45 of file SPIRVCBufferAccess.cpp.
References llvm::dyn_cast(), I, and llvm::Value::users().
Referenced by replaceCBufferAccesses().
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVCBufferAccessLegacy , DEBUG_TYPE , "SPIRV CBuffer Access" , false , false)
Definition at line 146 of file SPIRVCBufferAccess.cpp.
References llvm::createSPIRVCBufferAccessLegacyPass(), and DEBUG_TYPE.
replaceCBufferAccesses()
bool replaceCBufferAccesses (Module & M) static
Definition at line 56 of file SPIRVCBufferAccess.cpp.
References llvm::cast(), llvm::convertUsersOfConstantsToInstructions(), llvm::dyn_cast(), findHandleDef(), llvm::hlsl::CBufferMetadata::get(), llvm::StructLayout::getElementContainingOffset(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::GlobalValue::getType(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::report_fatal_error(), llvm::Value::use_empty(), and llvm::Value::users().