LLVM: lib/Target/SPIRV/SPIRVPostLegalizer.cpp File Reference
SPIRVPostLegalizer.cpp File Reference
#include "SPIRV.h"
#include "SPIRVSubtarget.h"
#include "SPIRVUtils.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/Support/Debug.h"
#include <stack>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "spirv-postlegalizer"
Functions
void llvm::updateRegType (Register Reg, Type *Ty, SPIRVType *SpirvTy, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Helper external function for assigning SPIRVType to a register, ensuring the register class and type are set in MRI.
void llvm::processInstr (MachineInstr &MI, MachineIRBuilder &MIB, MachineRegisterInfo &MRI, SPIRVGlobalRegistry *GR, SPIRVType *KnownResType)
static SPIRVType * deduceIntTypeFromResult (Register ResVReg, MachineIRBuilder &MIB, SPIRVGlobalRegistry *GR)
static SPIRVType * deduceTypeFromSingleOperand (MachineInstr *I, MachineIRBuilder &MIB, SPIRVGlobalRegistry *GR, unsigned OpIdx)
static SPIRVType * deduceTypeFromOperandRange (MachineInstr *I, MachineIRBuilder &MIB, SPIRVGlobalRegistry *GR, unsigned StartOp, unsigned EndOp)
static SPIRVType * deduceTypeFromResultRegister (MachineInstr *Use, Register UseRegister, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB)
static SPIRVType * deducePointerTypeFromResultRegister (MachineInstr *Use, Register UseRegister, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB)
static SPIRVType * deduceTypeFromPointerOperand (MachineInstr *Use, Register UseRegister, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB)
static SPIRVType * deduceTypeFromUses (Register Reg, MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB)
static SPIRVType * deduceResultTypeFromOperands (MachineInstr *I, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB)
static bool deduceAndAssignTypeForGUnmerge (MachineInstr *I, MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB)
static bool deduceAndAssignSpirvType (MachineInstr *I, MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB)
static bool requiresSpirvType (MachineInstr &I, SPIRVGlobalRegistry *GR, MachineRegisterInfo &MRI)
static void registerSpirvTypeForNewInstructions (MachineFunction &MF, SPIRVGlobalRegistry *GR)
static bool hasAssignType (Register Reg, MachineRegisterInfo &MRI)
static void generateAssignType (MachineInstr &MI, Register ResultRegister, SPIRVType *ResultType, SPIRVGlobalRegistry *GR, MachineRegisterInfo &MRI)
static void ensureAssignTypeForTypeFolding (MachineFunction &MF, SPIRVGlobalRegistry *GR)
void visit (MachineFunction &MF, MachineBasicBlock &Start, std::function< void(MachineBasicBlock *)> op)
void visit (MachineFunction &MF, std::function< void(MachineBasicBlock *)> op)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-postlegalizer"
Definition at line 25 of file SPIRVPostLegalizer.cpp.
Function Documentation
deduceAndAssignSpirvType()
bool deduceAndAssignSpirvType (MachineInstr * I, MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB) static
Definition at line 264 of file SPIRVPostLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::SPIRVGlobalRegistry::CurMF, llvm::dbgs(), deduceAndAssignTypeForGUnmerge(), deduceResultTypeFromOperands(), deduceTypeFromUses(), llvm::MachineFunction::getRegInfo(), I, LLVM_DEBUG, MRI, and llvm::setRegClassType().
Referenced by registerSpirvTypeForNewInstructions().
deduceAndAssignTypeForGUnmerge()
bool deduceAndAssignTypeForGUnmerge (MachineInstr * I, MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB) static
Definition at line 220 of file SPIRVPostLegalizer.cpp.
References assert(), deduceTypeFromUses(), llvm::SPIRVSubtarget::getInstrInfo(), llvm::LLT::getNumElements(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::MachineFunction::getRegInfo(), llvm::SPIRVGlobalRegistry::getScalarOrVectorComponentType(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::MachineFunction::getSubtarget(), I, llvm::LLT::isVector(), MRI, and llvm::setRegClassType().
Referenced by deduceAndAssignSpirvType().
deduceIntTypeFromResult()
SPIRVType * deduceIntTypeFromResult (Register ResVReg, MachineIRBuilder & MIB, SPIRVGlobalRegistry * GR) static
Definition at line 48 of file SPIRVPostLegalizer.cpp.
References llvm::MachineIRBuilder::getMRI(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), and llvm::MachineRegisterInfo::getType().
Referenced by deduceResultTypeFromOperands().
deducePointerTypeFromResultRegister()
SPIRVType * deducePointerTypeFromResultRegister (MachineInstr * Use, Register UseRegister, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB) static
Definition at line 111 of file SPIRVPostLegalizer.cpp.
References assert(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), and llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg().
Referenced by deduceTypeFromUses().
deduceResultTypeFromOperands()
SPIRVType * deduceResultTypeFromOperands (MachineInstr * I, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB) static
Definition at line 198 of file SPIRVPostLegalizer.cpp.
References deduceIntTypeFromResult(), deduceTypeFromOperandRange(), deduceTypeFromSingleOperand(), and I.
Referenced by deduceAndAssignSpirvType().
deduceTypeFromOperandRange()
SPIRVType * deduceTypeFromOperandRange (MachineInstr * I, MachineIRBuilder & MIB, SPIRVGlobalRegistry * GR, unsigned StartOp, unsigned EndOp) static
Definition at line 73 of file SPIRVPostLegalizer.cpp.
References assert(), deduceTypeFromSingleOperand(), and I.
Referenced by deduceResultTypeFromOperands().
deduceTypeFromPointerOperand()
SPIRVType * deduceTypeFromPointerOperand (MachineInstr * Use, Register UseRegister, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB) static
Definition at line 127 of file SPIRVPostLegalizer.cpp.
References assert(), llvm::SPIRVGlobalRegistry::getPointeeType(), and llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg().
Referenced by deduceTypeFromUses().
deduceTypeFromResultRegister()
SPIRVType * deduceTypeFromResultRegister (MachineInstr * Use, Register UseRegister, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB) static
Definition at line 91 of file SPIRVPostLegalizer.cpp.
References llvm::MachineIRBuilder::getMRI(), llvm::LLT::getNumElements(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getScalarOrVectorComponentType(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::MachineRegisterInfo::getType(), and llvm::LLT::isVector().
Referenced by deduceTypeFromUses().
deduceTypeFromSingleOperand()
SPIRVType * deduceTypeFromSingleOperand (MachineInstr * I, MachineIRBuilder & MIB, SPIRVGlobalRegistry * GR, unsigned OpIdx) static
Definition at line 55 of file SPIRVPostLegalizer.cpp.
References llvm::MachineIRBuilder::getMRI(), llvm::LLT::getNumElements(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getScalarOrVectorComponentType(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::MachineRegisterInfo::getType(), I, llvm::LLT::isVector(), and OpIdx.
Referenced by deduceResultTypeFromOperands(), and deduceTypeFromOperandRange().
deduceTypeFromUses()
SPIRVType * deduceTypeFromUses (Register Reg, MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder & MIB) static
Definition at line 142 of file SPIRVPostLegalizer.cpp.
References llvm::cast(), llvm::dbgs(), deducePointerTypeFromResultRegister(), deduceTypeFromPointerOperand(), deduceTypeFromResultRegister(), llvm::MachineFunction::getRegInfo(), LLVM_DEBUG, MRI, and Reg.
Referenced by deduceAndAssignSpirvType(), and deduceAndAssignTypeForGUnmerge().
ensureAssignTypeForTypeFolding()
void ensureAssignTypeForTypeFolding (MachineFunction & MF, SPIRVGlobalRegistry * GR) static
Definition at line 435 of file SPIRVPostLegalizer.cpp.
References assert(), llvm::dbgs(), generateAssignType(), llvm::MachineFunction::getName(), llvm::MachineFunction::getRegInfo(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), hasAssignType(), llvm::isTypeFoldingSupported(), LLVM_DEBUG, MBB, MI, and MRI.
generateAssignType()
void generateAssignType (MachineInstr & MI, Register ResultRegister, SPIRVType * ResultType, SPIRVGlobalRegistry * GR, MachineRegisterInfo & MRI) static
Definition at line 396 of file SPIRVPostLegalizer.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildInstr(), llvm::dbgs(), E(), llvm::MachineIRBuilder::getMF(), llvm::MachineOperand::getReg(), llvm::SPIRVGlobalRegistry::getRegClass(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), I, LLVM_DEBUG, MI, MRI, llvm::printReg(), llvm::MachineInstrBuilder::setMIFlags(), llvm::MachineOperand::setReg(), and llvm::updateRegType().
Referenced by ensureAssignTypeForTypeFolding().
hasAssignType()
bool hasAssignType (Register Reg, MachineRegisterInfo & MRI) static
Definition at line 387 of file SPIRVPostLegalizer.cpp.
References MRI, and Reg.
Referenced by ensureAssignTypeForTypeFolding().
registerSpirvTypeForNewInstructions()
void registerSpirvTypeForNewInstructions (MachineFunction & MF, SPIRVGlobalRegistry * GR) static
Definition at line 325 of file SPIRVPostLegalizer.cpp.
References llvm::dbgs(), deduceAndAssignSpirvType(), llvm::SmallVectorTemplateCommon< T, typename >::empty(), llvm::LLT::getElementType(), llvm::LLT::getNumElements(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::MachineFunction::getRegInfo(), llvm::LLT::getSizeInBits(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), I, llvm::LLT::isVector(), LLVM_DEBUG, MBB, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), requiresSpirvType(), and llvm::setRegClassType().
requiresSpirvType()
bool requiresSpirvType (MachineInstr & I, SPIRVGlobalRegistry * GR, MachineRegisterInfo & MRI) static
Definition at line 297 of file SPIRVPostLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::CurMF, llvm::dbgs(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), I, LLVM_DEBUG, MRI, and llvm::setRegClassType().
Referenced by registerSpirvTypeForNewInstructions().
visit() [1/2]
void visit (MachineFunction & MF, MachineBasicBlock & Start, std::function< void(MachineBasicBlock *)> op)
Definition at line 462 of file SPIRVPostLegalizer.cpp.
References llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::SmallPtrSetImpl< PtrType >::insert(), MBB, and op.
Referenced by llvm::computeDeadSymbolsAndUpdateIndirectCalls(), visit(), SCEVCastSinkingRewriter::visitAddExpr(), and SCEVCastSinkingRewriter::visitMulExpr().
visit() [2/2]
void visit (MachineFunction & MF, std::function< void(MachineBasicBlock *)> op)
Definition at line 486 of file SPIRVPostLegalizer.cpp.
References llvm::MachineFunction::begin(), op, and visit().