LLVM: lib/Target/SPIRV/SPIRVEmitIntrinsics.cpp File Reference
SPIRVEmitIntrinsics.cpp File Reference
#include "SPIRV.h"
#include "SPIRVBuiltins.h"
#include "SPIRVSubtarget.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/TypedPointerType.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Utils/Local.h"
#include <cassert>
#include <queue>
#include <unordered_set>
#include "SPIRVGenTables.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::SPIRV
Macros
#define GET_BuiltinGroup_DECL
Functions
INITIALIZE_PASS (SPIRVEmitIntrinsics, "emit-intrinsics", "SPIRV emit intrinsics", false, false) static inline bool isAssignTypeInstr(const Instruction *I)
static bool isMemInstrToReplace (Instruction *I)
static bool isAggrConstForceInt32 (const Value *V)
static void setInsertPointSkippingPhis (IRBuilder<> &B, Instruction *I)
static void setInsertPointAfterDef (IRBuilder<> &B, Instruction *I)
static bool requireAssignType (Instruction *I)
static void reportFatalOnTokenType (const Instruction *I)
static void emitAssignName (Instruction *I, IRBuilder<> &B)
static bool IsKernelArgInt8 (Function *F, StoreInst *SI)
static Type * restoreMutatedType (SPIRVGlobalRegistry *GR, Instruction *I, Type *Ty)
static Type * getPointeeTypeByCallInst (StringRef DemangledName, Function *CalledF, unsigned OpIdx)
static Type * getAtomicElemTy (SPIRVGlobalRegistry *GR, Instruction *I, Value *PointerOperand)
static void createDecorationIntrinsic (Instruction *I, MDNode *Node, IRBuilder<> &B)
static void createRoundingModeDecoration (Instruction *I, unsigned RoundingModeDeco, IRBuilder<> &B)
static void createSaturatedConversionDecoration (Instruction *I, IRBuilder<> &B)
static void addSaturatedDecorationToIntrinsic (Instruction *I, IRBuilder<> &B)
static bool isFirstIndexZero (const GetElementPtrInst *GEP)
static SPIRV::FPFastMathDefaultInfoVector & getOrCreateFPFastMathDefaultInfoVec (const Module &M, DenseMap< Function *, SPIRV::FPFastMathDefaultInfoVector > &FPFastMathDefaultInfoMap, Function *F)
static SPIRV::FPFastMathDefaultInfo & getFPFastMathDefaultInfo (SPIRV::FPFastMathDefaultInfoVector &FPFastMathDefaultInfoVec, const Type *Ty)
static FunctionType * getFunctionPointerElemType (Function *F, SPIRVGlobalRegistry *GR)
Variables
static cl::opt< bool > SpirvEmitOpNames ("spirv-emit-op-names", cl::desc("Emit OpName for all instructions"), cl::init(false))
Macro Definition Documentation
GET_BuiltinGroup_DECL
#define GET_BuiltinGroup_DECL
Definition at line 60 of file SPIRVEmitIntrinsics.cpp.
Function Documentation
addSaturatedDecorationToIntrinsic()
void addSaturatedDecorationToIntrinsic (Instruction * I, IRBuilder<> & B) static
Definition at line 1508 of file SPIRVEmitIntrinsics.cpp.
References B(), createSaturatedConversionDecoration(), llvm::dyn_cast(), llvm::CallBase::getCalledFunction(), and I.
createDecorationIntrinsic()
void createDecorationIntrinsic (Instruction * I, MDNode * Node, IRBuilder<> & B) static
Definition at line 1477 of file SPIRVEmitIntrinsics.cpp.
References B(), llvm::MDNode::get(), llvm::MetadataAsValue::get(), I, and setInsertPointAfterDef().
Referenced by createRoundingModeDecoration(), and createSaturatedConversionDecoration().
createRoundingModeDecoration()
void createRoundingModeDecoration (Instruction * I, unsigned RoundingModeDeco, IRBuilder<> & B) static
Definition at line 1485 of file SPIRVEmitIntrinsics.cpp.
References B(), createDecorationIntrinsic(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::Type::getInt32Ty(), I, and llvm::Int32Ty.
createSaturatedConversionDecoration()
void createSaturatedConversionDecoration (Instruction * I, IRBuilder<> & B) static
Definition at line 1498 of file SPIRVEmitIntrinsics.cpp.
References B(), createDecorationIntrinsic(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::Type::getInt32Ty(), I, and llvm::Int32Ty.
Referenced by addSaturatedDecorationToIntrinsic().
emitAssignName()
void emitAssignName (Instruction * I, IRBuilder<> & B) static
Definition at line 365 of file SPIRVEmitIntrinsics.cpp.
References B(), llvm::dyn_cast(), F, llvm::MDNode::get(), llvm::MDString::get(), llvm::MetadataAsValue::get(), I, llvm::isa(), reportFatalOnTokenType(), setInsertPointAfterDef(), and SpirvEmitOpNames.
getAtomicElemTy()
Type * getAtomicElemTy (SPIRVGlobalRegistry * GR, Instruction * I, Value * PointerOperand) inline static
Definition at line 1011 of file SPIRVEmitIntrinsics.cpp.
References llvm::dyn_cast(), llvm::SPIRVGlobalRegistry::findDeducedElementType(), llvm::getTypedPointerWrapper(), I, and llvm::isUntypedPointerTy().
getFPFastMathDefaultInfo()
SPIRV::FPFastMathDefaultInfo & getFPFastMathDefaultInfo (SPIRV::FPFastMathDefaultInfoVector & FPFastMathDefaultInfoVec, const Type * Ty) static
Definition at line 2373 of file SPIRVEmitIntrinsics.cpp.
References assert(), llvm::BitWidth, llvm::SPIRV::FPFastMathDefaultInfoVector::computeFPFastMathDefaultInfoVecIndex(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
getFunctionPointerElemType()
FunctionType * getFunctionPointerElemType (Function * F, SPIRVGlobalRegistry * GR) static
Definition at line 2731 of file SPIRVEmitIntrinsics.cpp.
References F, llvm::SPIRVGlobalRegistry::findDeducedElementType(), llvm::FunctionType::get(), llvm::getPointerAddressSpace(), llvm::getTypedPointerWrapper(), llvm::Type::isPointerTy(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getOrCreateFPFastMathDefaultInfoVec()
SPIRV::FPFastMathDefaultInfoVector & getOrCreateFPFastMathDefaultInfoVec (const Module & M, DenseMap< Function *, SPIRV::FPFastMathDefaultInfoVector > & FPFastMathDefaultInfoMap, Function * F) static
Definition at line 2351 of file SPIRVEmitIntrinsics.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), and llvm::Type::getHalfTy().
getPointeeTypeByCallInst()
Type * getPointeeTypeByCallInst (StringRef DemangledName, Function * CalledF, unsigned OpIdx) static
Definition at line 608 of file SPIRVEmitIntrinsics.cpp.
References llvm::Function::getContext(), llvm::Type::getInt8Ty(), OpIdx, and llvm::StringRef::starts_with().
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVEmitIntrinsics , "emit-intrinsics" , "SPIRV emit intrinsics" , false , false) const
Definition at line 313 of file SPIRVEmitIntrinsics.cpp.
References llvm::cast(), const, I, inline, and llvm::isa().
isAggrConstForceInt32()
bool isAggrConstForceInt32 (const Value * V) static
Definition at line 326 of file SPIRVEmitIntrinsics.cpp.
References llvm::isa().
isFirstIndexZero()
bool isFirstIndexZero (const GetElementPtrInst * GEP) static
Definition at line 1613 of file SPIRVEmitIntrinsics.cpp.
References llvm::dyn_cast(), and GEP.
IsKernelArgInt8()
bool IsKernelArgInt8 (Function * F, StoreInst * SI) static
Definition at line 420 of file SPIRVEmitIntrinsics.cpp.
References F, llvm::isa(), llvm::isPointerTy(), and llvm::CallingConv::SPIR_KERNEL.
isMemInstrToReplace()
bool isMemInstrToReplace (Instruction * I) static
Definition at line 321 of file SPIRVEmitIntrinsics.cpp.
References I, and llvm::isa().
reportFatalOnTokenType()
void reportFatalOnTokenType (const Instruction * I) inline static
Definition at line 358 of file SPIRVEmitIntrinsics.cpp.
References I, and llvm::report_fatal_error().
Referenced by emitAssignName().
requireAssignType()
bool requireAssignType (Instruction * I) static
Definition at line 347 of file SPIRVEmitIntrinsics.cpp.
References llvm::dyn_cast(), and I.
restoreMutatedType()
Type * restoreMutatedType (SPIRVGlobalRegistry * GR, Instruction * I, Type * Ty) inline static
Definition at line 427 of file SPIRVEmitIntrinsics.cpp.
References llvm::dyn_cast(), llvm::SPIRVGlobalRegistry::findMutated(), llvm::CallBase::getCalledFunction(), I, llvm::CallBase::isIndirectCall(), llvm::CallBase::isInlineAsm(), and llvm::Function::isIntrinsic().
setInsertPointAfterDef()
void setInsertPointAfterDef (IRBuilder<> & B, Instruction * I) static
Definition at line 339 of file SPIRVEmitIntrinsics.cpp.
References B(), and I.
Referenced by createDecorationIntrinsic(), and emitAssignName().
setInsertPointSkippingPhis()
void setInsertPointSkippingPhis (IRBuilder<> & B, Instruction * I) static
Definition at line 332 of file SPIRVEmitIntrinsics.cpp.
References B(), I, and llvm::isa().
Variable Documentation
SpirvEmitOpNames
cl::opt< bool > SpirvEmitOpNames("spirv-emit-op-names", cl::desc("Emit OpName for all instructions"), cl::init(false)) ("spirv-emit-op-names" , cl::desc("Emit OpName for all instructions") , cl::init(false)) static
Referenced by emitAssignName().