LLVM: lib/Target/SPIRV/SPIRVPushConstantAccess.cpp File Reference
SPIRVPushConstantAccess.cpp File Reference
#include "SPIRVPushConstantAccess.h"
#include "SPIRV.h"
#include "SPIRVSubtarget.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "llvm/Frontend/HLSL/CBuffer.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/IR/Module.h"
Macros
#define DEBUG_TYPE "spirv-pushconstant-access"
Functions
static bool replacePushConstantAccesses (Module &M, SPIRVGlobalRegistry *GR)
INITIALIZE_PASS (SPIRVPushConstantAccessLegacy, DEBUG_TYPE, "SPIRV push constant Access", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-pushconstant-access"
Definition at line 28 of file SPIRVPushConstantAccess.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVPushConstantAccessLegacy , DEBUG_TYPE , "SPIRV push constant Access" , false , false)
Definition at line 95 of file SPIRVPushConstantAccess.cpp.
References llvm::createSPIRVPushConstantAccessLegacyPass(), and DEBUG_TYPE.
replacePushConstantAccesses()
bool replacePushConstantAccesses (Module & M, SPIRVGlobalRegistry * GR) static
Definition at line 31 of file SPIRVPushConstantAccess.cpp.
References llvm::SPIRVGlobalRegistry::buildAssignPtr(), llvm::cast(), llvm::TargetExtType::get(), llvm::GlobalValue::getType(), I, llvm::make_early_inc_range(), llvm::GlobalValue::setVisibility(), and llvm::storageClassToAddressSpace().
Referenced by llvm::SPIRVPushConstantAccess::run().