LLVM: lib/Target/SPIRV/SPIRVISelLowering.cpp File Reference
SPIRVISelLowering.cpp File Reference
#include "SPIRVISelLowering.h"
#include "SPIRV.h"
#include "SPIRVInstrInfo.h"
#include "SPIRVRegisterBankInfo.h"
#include "SPIRVRegisterInfo.h"
#include "SPIRVSubtarget.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
Macros
#define DEBUG_TYPE "spirv-lower"
Functions
static bool typesLogicallyMatch (const SPIRVType *Ty1, const SPIRVType *Ty2, SPIRVGlobalRegistry &GR)
Register getTypeReg (MachineRegisterInfo *MRI, Register OpReg)
static void doInsertBitcast (const SPIRVSubtarget &STI, MachineRegisterInfo *MRI, SPIRVGlobalRegistry &GR, MachineInstr &I, Register OpReg, unsigned OpIdx, SPIRVType *NewPtrType)
static SPIRVType * createNewPtrType (SPIRVGlobalRegistry &GR, MachineInstr &I, SPIRVType *OpType, bool ReuseType, SPIRVType *ResType, const Type *ResTy)
static void validatePtrTypes (const SPIRVSubtarget &STI, MachineRegisterInfo *MRI, SPIRVGlobalRegistry &GR, MachineInstr &I, unsigned OpIdx, SPIRVType *ResType, const Type *ResTy=nullptr)
static void validateGroupWaitEventsPtr (const SPIRVSubtarget &STI, MachineRegisterInfo *MRI, SPIRVGlobalRegistry &GR, MachineInstr &I)
static void validateLifetimeStart (const SPIRVSubtarget &STI, MachineRegisterInfo *MRI, SPIRVGlobalRegistry &GR, MachineInstr &I)
static void validatePtrUnwrapStructField (const SPIRVSubtarget &STI, MachineRegisterInfo *MRI, SPIRVGlobalRegistry &GR, MachineInstr &I, unsigned OpIdx)
void validateFunCallMachineDef (const SPIRVSubtarget &STI, MachineRegisterInfo *DefMRI, MachineRegisterInfo *CallMRI, SPIRVGlobalRegistry &GR, MachineInstr &FunCall, MachineInstr *FunDef)
const Function * validateFunCall (const SPIRVSubtarget &STI, MachineRegisterInfo *CallMRI, SPIRVGlobalRegistry &GR, MachineInstr &FunCall)
void validateForwardCalls (const SPIRVSubtarget &STI, MachineRegisterInfo *DefMRI, SPIRVGlobalRegistry &GR, MachineInstr &FunDef)
void validateAccessChain (const SPIRVSubtarget &STI, MachineRegisterInfo *MRI, SPIRVGlobalRegistry &GR, MachineInstr &I)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-lower"
Definition at line 23 of file SPIRVISelLowering.cpp.
Function Documentation
createNewPtrType()
SPIRVType * createNewPtrType (SPIRVGlobalRegistry & GR, MachineInstr & I, SPIRVType * OpType, bool ReuseType, SPIRVType * ResType, const Type * ResTy) static
Definition at line 166 of file SPIRVISelLowering.cpp.
References llvm::getImm(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), and I.
Referenced by validateGroupWaitEventsPtr(), and validatePtrTypes().
doInsertBitcast()
void doInsertBitcast (const SPIRVSubtarget & STI, MachineRegisterInfo * MRI, SPIRVGlobalRegistry & GR, MachineInstr & I, Register OpReg, unsigned OpIdx, SPIRVType * NewPtrType) static
Definition at line 149 of file SPIRVISelLowering.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineInstrBuilder::constrainAllUses(), llvm::createVirtualRegister(), llvm::SPIRVSubtarget::getInstrInfo(), llvm::MachineIRBuilder::getMF(), llvm::SPIRVSubtarget::getRegBankInfo(), llvm::SPIRVSubtarget::getRegisterInfo(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), I, MRI, OpIdx, and llvm::report_fatal_error().
Referenced by validateGroupWaitEventsPtr(), validateLifetimeStart(), validatePtrTypes(), and validatePtrUnwrapStructField().
getTypeReg()
Register getTypeReg (MachineRegisterInfo * MRI, Register OpReg) inline
Definition at line 142 of file SPIRVISelLowering.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and MRI.
Referenced by validateGroupWaitEventsPtr(), validateLifetimeStart(), validatePtrTypes(), and validatePtrUnwrapStructField().
typesLogicallyMatch()
bool typesLogicallyMatch (const SPIRVType * Ty1, const SPIRVType * Ty2, SPIRVGlobalRegistry & GR) static
Definition at line 33 of file SPIRVISelLowering.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), I, and typesLogicallyMatch().
Referenced by llvm::SPIRVTargetLowering::enforcePtrTypeCompatibility(), and typesLogicallyMatch().
validateAccessChain()
void validateAccessChain (const SPIRVSubtarget & STI, MachineRegisterInfo * MRI, SPIRVGlobalRegistry & GR, MachineInstr & I)
Definition at line 368 of file SPIRVISelLowering.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), I, MRI, and validatePtrTypes().
Referenced by llvm::SPIRVTargetLowering::finalizeLowering().
validateForwardCalls()
void validateForwardCalls (const SPIRVSubtarget & STI, MachineRegisterInfo * DefMRI, SPIRVGlobalRegistry & GR, MachineInstr & FunDef)
Definition at line 355 of file SPIRVISelLowering.cpp.
References F, llvm::SPIRVGlobalRegistry::getForwardCalls(), llvm::SPIRVGlobalRegistry::getFunctionByDefinition(), and validateFunCallMachineDef().
Referenced by llvm::SPIRVTargetLowering::finalizeLowering().
validateFunCall()
const Function * validateFunCall (const SPIRVSubtarget & STI, MachineRegisterInfo * CallMRI, SPIRVGlobalRegistry & GR, MachineInstr & FunCall)
Definition at line 338 of file SPIRVISelLowering.cpp.
References llvm::dyn_cast(), F, llvm::SPIRVGlobalRegistry::getFunctionDefinition(), llvm::MachineOperand::getGlobal(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getRegInfo(), and validateFunCallMachineDef().
Referenced by llvm::SPIRVTargetLowering::finalizeLowering().
validateFunCallMachineDef()
void validateFunCallMachineDef (const SPIRVSubtarget & STI, MachineRegisterInfo * DefMRI, MachineRegisterInfo * CallMRI, SPIRVGlobalRegistry & GR, MachineInstr & FunCall, MachineInstr * FunDef)
Definition at line 302 of file SPIRVISelLowering.cpp.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::SPIRVGlobalRegistry::getTypeForSPIRVType(), llvm::MachineRegisterInfo::getVRegDef(), OpIdx, llvm::SPIRVGlobalRegistry::setCurrentFunc(), and validatePtrTypes().
Referenced by validateForwardCalls(), and validateFunCall().
validateGroupWaitEventsPtr()
void validateGroupWaitEventsPtr (const SPIRVSubtarget & STI, MachineRegisterInfo * MRI, SPIRVGlobalRegistry & GR, MachineInstr & I) static
Definition at line 216 of file SPIRVISelLowering.cpp.
References createNewPtrType(), doInsertBitcast(), llvm::TargetExtType::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineInstr::getOpcode(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), getTypeReg(), I, MRI, and OpIdx.
Referenced by llvm::SPIRVTargetLowering::finalizeLowering().
validateLifetimeStart()
void validateLifetimeStart (const SPIRVSubtarget & STI, MachineRegisterInfo * MRI, SPIRVGlobalRegistry & GR, MachineInstr & I) static
Definition at line 238 of file SPIRVISelLowering.cpp.
References doInsertBitcast(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::getImm(), llvm::MachineOperand::getImm(), llvm::Type::getInt8Ty(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getPointeeType(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), getTypeReg(), I, and MRI.
Referenced by llvm::SPIRVTargetLowering::finalizeLowering().
validatePtrTypes()
void validatePtrTypes (const SPIRVSubtarget & STI, MachineRegisterInfo * MRI, SPIRVGlobalRegistry & GR, MachineInstr & I, unsigned OpIdx, SPIRVType * ResType, const Type * ResTy = nullptr) static
Definition at line 182 of file SPIRVISelLowering.cpp.
References createNewPtrType(), doInsertBitcast(), llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::SPIRVGlobalRegistry::getTypeForSPIRVType(), getTypeReg(), I, llvm::SPIRVGlobalRegistry::isBitcastCompatible(), MRI, OpIdx, and llvm::report_fatal_error().
Referenced by llvm::SPIRVTargetLowering::finalizeLowering(), validateAccessChain(), and validateFunCallMachineDef().
validatePtrUnwrapStructField()
void validatePtrUnwrapStructField (const SPIRVSubtarget & STI, MachineRegisterInfo * MRI, SPIRVGlobalRegistry & GR, MachineInstr & I, unsigned OpIdx) static
Definition at line 261 of file SPIRVISelLowering.cpp.
References doInsertBitcast(), llvm::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::MachineOperand::getReg(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), getTypeReg(), I, MRI, and OpIdx.
Referenced by llvm::SPIRVTargetLowering::finalizeLowering().