LLVM: lib/CGData/StableFunctionMapRecord.cpp File Reference
StableFunctionMapRecord.cpp File Reference
#include "llvm/CGData/StableFunctionMapRecord.h"
#include "llvm/Support/EndianStream.h"
Classes
struct llvm::yaml::MappingTraits< IndexPairHash >
struct llvm::yaml::MappingTraits< StableFunction >
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::yaml
Macros
#define DEBUG_TYPE "stable-function-map-record"
Functions
static SmallVector< const StableFunctionMap::StableFunctionEntry * > getStableFunctionEntries (const StableFunctionMap &SFM)
static IndexOperandHashVecType getStableIndexOperandHashes (const StableFunctionMap::StableFunctionEntry *FuncEntry)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "stable-function-map-record"
Definition at line 19 of file StableFunctionMapRecord.cpp.
Function Documentation
getStableFunctionEntries()
SmallVector< const StableFunctionMap::StableFunctionEntry * > getStableFunctionEntries (const StableFunctionMap & SFM) static
Definition at line 53 of file StableFunctionMapRecord.cpp.
References A(), B(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::StableFunctionMap::getFunctionMap(), llvm::StableFunctionMap::getNameForId(), P, and llvm::stable_sort().
Referenced by llvm::StableFunctionMapRecord::serialize(), and llvm::StableFunctionMapRecord::serializeYAML().
getStableIndexOperandHashes()
IndexOperandHashVecType getStableIndexOperandHashes (const StableFunctionMap::StableFunctionEntry * FuncEntry) static
Definition at line 70 of file StableFunctionMapRecord.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::StableFunctionMap::StableFunctionEntry::IndexOperandHashMap, and llvm::sort().
Referenced by llvm::StableFunctionMapRecord::serialize(), and llvm::StableFunctionMapRecord::serializeYAML().