LLVM: lib/MC/StringTableBuilder.cpp File Reference
StringTableBuilder.cpp File Reference
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/CachedHashString.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <utility>
#include <vector>
Typedefs
using StringPair = std::pair<CachedHashStringRef, size_t>
Functions
static int charTailAt (StringPair *P, size_t Pos)
static void multikeySort (MutableArrayRef< StringPair * > Vec, int Pos)
Typedef Documentation
StringPair
using StringPair = std::pair<CachedHashStringRef, size_t>
Definition at line 69 of file StringTableBuilder.cpp.
Function Documentation
charTailAt()
int charTailAt (StringPair * P, size_t Pos) static
Definition at line 87 of file StringTableBuilder.cpp.
References P, and llvm::StringRef::size().
Referenced by multikeySort().
multikeySort()
void multikeySort (MutableArrayRef< StringPair * > Vec, int Pos) static
Definition at line 96 of file StringTableBuilder.cpp.
References llvm::CallingConv::C, charTailAt(), I, multikeySort(), llvm::ArrayRef< T >::size(), llvm::MutableArrayRef< T >::slice(), and std::swap().
Referenced by multikeySort().