LLVM: include/llvm/Support/SystemZ/zos_wrappers/string.h File Reference
string.h File Reference
Functions
char * strsignal (int sig) asm("llvm_zos_strsignal")
size_t strnlen (const char *S, size_t MaxLen) asm("llvm_zos_strnlen")
Function Documentation
strnlen()
size_t strnlen (const char * S, size_t MaxLen)
Referenced by constructSectionCommon(), extractSegmentName(), and llvm::yaml::ScalarTraits< char_16 >::output().
strsignal()
char * strsignal (int sig)