LLVM: llvm::EvictionCost Struct Reference
llvm::EvictionCost Struct Reference
Cost of evicting interference - used by default advisor, and the eviction chain heuristic in RegAllocGreedy.
#include "llvm/CodeGen/RegAllocEvictionAdvisor.h"
Public Member Functions
EvictionCost ()=default
bool isMax () const
void setMax ()
void setBrokenHints (unsigned NHints)
bool operator< (const EvictionCost &O) const
bool operator>= (const EvictionCost &O) const
Public Attributes
unsigned BrokenHints = 0
Total number of broken hints.
float MaxWeight = 0
Maximum spill weight evicted.
Detailed Description
Cost of evicting interference - used by default advisor, and the eviction chain heuristic in RegAllocGreedy.
Definition at line 78 of file RegAllocEvictionAdvisor.h.
Constructor & Destructor Documentation
EvictionCost()
llvm::EvictionCost::EvictionCost () default
Referenced by operator<(), and operator>=().
Member Function Documentation
isMax()
bool llvm::EvictionCost::isMax () const inline
Definition at line 84 of file RegAllocEvictionAdvisor.h.
References BrokenHints.
operator<()
bool llvm::EvictionCost::operator< (const EvictionCost & O) const inline
Definition at line 90 of file RegAllocEvictionAdvisor.h.
References BrokenHints, EvictionCost(), and MaxWeight.
operator>=()
bool llvm::EvictionCost::operator>= (const EvictionCost & O) const inline
Definition at line 95 of file RegAllocEvictionAdvisor.h.
References EvictionCost().
setBrokenHints()
void llvm::EvictionCost::setBrokenHints (unsigned NHints) inline
Definition at line 88 of file RegAllocEvictionAdvisor.h.
References BrokenHints.
setMax()
void llvm::EvictionCost::setMax () inline
Definition at line 86 of file RegAllocEvictionAdvisor.h.
References BrokenHints.
Member Data Documentation
BrokenHints
unsigned llvm::EvictionCost::BrokenHints = 0
Total number of broken hints.
Definition at line 79 of file RegAllocEvictionAdvisor.h.
Referenced by isMax(), operator<(), setBrokenHints(), and setMax().
MaxWeight
float llvm::EvictionCost::MaxWeight = 0
Maximum spill weight evicted.
Definition at line 80 of file RegAllocEvictionAdvisor.h.
Referenced by operator<().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/RegAllocEvictionAdvisor.h