LLVM: llvm::RangeListEntry Struct Reference
llvm::RangeListEntry Struct Reference
A class representing a single range list entry.
#include "llvm/DebugInfo/DWARF/DWARFDebugRnglists.h"
Public Member Functions
LLVM_ABI Error extract (DWARFDataExtractor Data, uint64_t *OffsetPtr)
LLVM_ABI void dump (raw_ostream &OS, uint8_t AddrSize, uint8_t MaxEncodingStringLength, uint64_t &CurrentBase, DIDumpOptions DumpOpts, llvm::function_ref< std::optional< object::SectionedAddress >(uint32_t)> LookupPooledAddress) const
bool isSentinel () const
Public Attributes
uint64_t Value0
The values making up the range list entry.
uint64_t Value1
Public Attributes inherited from llvm::DWARFListEntryBase
uint64_t Offset
The offset at which the entry is located in the section.
uint8_t EntryKind
The DWARF encoding (DW_RLE_* or DW_LLE_*).
uint64_t SectionIndex
The index of the section this entry belongs to.
Detailed Description
A class representing a single range list entry.
Definition at line 31 of file DWARFDebugRnglists.h.
Member Function Documentation
dump()
void RangeListEntry::dump (raw_ostream & OS, uint8_t AddrSize, uint8_t MaxEncodingStringLength, uint64_t & CurrentBase, DIDumpOptions DumpOpts, llvm::function_ref< std::optional< object::SectionedAddress >(uint32_t)> LookupPooledAddress) const
Definition at line 175 of file DWARFDebugRnglists.cpp.
References assert(), llvm::dwarf::computeTombstoneAddress(), DenseMapInfo< LocallyHashedType >::Tombstone, llvm::DIDumpOptions::DisplayRawContents, llvm::DWARFAddressRange::dump(), llvm::DWARFFormValue::dumpAddress(), llvm::DWARFListEntryBase::EntryKind, llvm::format(), llvm_unreachable, llvm::DWARFListEntryBase::Offset, llvm::dwarf::RangeListEncodingString(), Value0, Value1, and llvm::DIDumpOptions::Verbose.
extract()
Error RangeListEntry::extract (DWARFDataExtractor Data, uint64_t * OffsetPtr)
Definition at line 20 of file DWARFDebugRnglists.cpp.
References assert(), llvm::CallingConv::C, llvm::consumeError(), llvm::createStringError(), llvm::Data, data, llvm::DWARFListEntryBase::EntryKind, llvm::invalid_argument, llvm::not_supported, llvm::DWARFListEntryBase::Offset, llvm::dwarf::RLEString(), llvm::DWARFListEntryBase::SectionIndex, llvm::Error::success(), Value0, and Value1.
isSentinel()
bool llvm::RangeListEntry::isSentinel () const inline
Definition at line 45 of file DWARFDebugRnglists.h.
References llvm::DWARFListEntryBase::EntryKind.
Member Data Documentation
Value0
uint64_t llvm::RangeListEntry::Value0
The values making up the range list entry.
Most represent a range with a start and end address or a start address and a length. Others are single value base addresses or end-of-list with no values. The unneeded values are semantically undefined, but initialized to 0.
Definition at line 36 of file DWARFDebugRnglists.h.
Referenced by dump(), and extract().
Value1
uint64_t llvm::RangeListEntry::Value1
Definition at line 37 of file DWARFDebugRnglists.h.
Referenced by dump(), and extract().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugRnglists.h
lib/DebugInfo/DWARF/DWARFDebugRnglists.cpp