LLVM: llvm::KnownFPClass Struct Reference
llvm::KnownFPClass Struct Reference
#include "llvm/Support/KnownFPClass.h"
Public Types
enum class MinMaxKind {
minimum , maximum , minimumnum , maximumnum ,
minnum , maxnum
}
Public Member Functions
KnownFPClass (FPClassTest Known=fcAllFlags, std::optional< bool > Sign={})
LLVM_ABI KnownFPClass (const APFloat &C)
bool operator== (KnownFPClass Other) const
bool isKnownNever (FPClassTest Mask) const
Return true if it's known this can never be one of the mask entries.
bool isKnownAlways (FPClassTest Mask) const
bool isUnknown () const
bool isKnownNeverNaN () const
Return true if it's known this can never be a nan.
bool isKnownAlwaysNaN () const
Return true if it's known this must always be a nan.
bool isKnownNeverInfinity () const
Return true if it's known this can never be an infinity.
bool isKnownNeverInfOrNaN () const
Return true if it's known this can never be an infinity or nan.
bool isKnownNeverPosInfinity () const
Return true if it's known this can never be +infinity.
bool isKnownNeverNegInfinity () const
Return true if it's known this can never be -infinity.
bool isKnownNeverSubnormal () const
Return true if it's known this can never be a subnormal.
bool isKnownNeverPosSubnormal () const
Return true if it's known this can never be a positive subnormal.
bool isKnownNeverNegSubnormal () const
Return true if it's known this can never be a negative subnormal.
bool isKnownNeverZero () const
Return true if it's known this can never be a zero.
bool isKnownNeverPosZero () const
Return true if it's known this can never be a literal positive zero.
bool isKnownNeverNegZero () const
Return true if it's known this can never be a negative zero.
LLVM_ABI bool isKnownNeverLogicalZero (DenormalMode Mode) const
Return true if it's known this can never be interpreted as a zero.
LLVM_ABI bool isKnownNeverLogicalNegZero (DenormalMode Mode) const
Return true if it's known this can never be interpreted as a negative zero.
LLVM_ABI bool isKnownNeverLogicalPosZero (DenormalMode Mode) const
Return true if it's known this can never be interpreted as a positive zero.
bool cannotBeOrderedLessThanZero () const
Return true if we can prove that the analyzed floating-point value is either NaN or never less than -0.0.
bool cannotBeOrderedGreaterThanZero () const
Return true if we can prove that the analyzed floating-point value is either NaN or never greater than -0.0.
bool cannotBeOrderedGreaterEqZero (DenormalMode Mode) const
Return true if it's know this can never be a negative value or a logical 0.
KnownFPClass intersectWith (const KnownFPClass &RHS)
KnownFPClass & operator|= (const KnownFPClass &RHS)
void knownNot (FPClassTest RuleOut)
void fneg ()
void fabs ()
bool signBitIsZeroOrNaN () const
Return true if the sign bit must be 0, ignoring the sign of nans.
void signBitMustBeZero ()
Assume the sign bit is zero.
void signBitMustBeOne ()
Assume the sign bit is one.
void copysign (const KnownFPClass &Sign)
void propagateNaN (const KnownFPClass &Src, bool PreserveSign=false)
LLVM_ABI void propagateDenormal (const KnownFPClass &Src, DenormalMode Mode)
Propagate knowledge from a source value that could be a denormal or zero.
LLVM_ABI void propagateCanonicalizingSrc (const KnownFPClass &Src, DenormalMode Mode)
Report known classes if Src is evaluated through a potentially canonicalizing operation.
void resetAll ()
Static Public Member Functions
static LLVM_ABI KnownFPClass minMaxLike (const KnownFPClass &LHS, const KnownFPClass &RHS, MinMaxKind Kind, DenormalMode DenormMode=DenormalMode::getDynamic())
static LLVM_ABI KnownFPClass canonicalize (const KnownFPClass &Src, DenormalMode DenormMode=DenormalMode::getDynamic())
Apply the canonicalize intrinsic to this value.
static LLVM_ABI KnownFPClass fmul (const KnownFPClass &LHS, const KnownFPClass &RHS, DenormalMode Mode=DenormalMode::getDynamic())
Report known values for fmul.
static KnownFPClass square (const KnownFPClass &Src, DenormalMode Mode=DenormalMode::getDynamic())
static LLVM_ABI KnownFPClass exp (const KnownFPClass &Src)
Report known values for exp, exp2 and exp10.
static LLVM_ABI KnownFPClass log (const KnownFPClass &Src, DenormalMode Mode=DenormalMode::getDynamic())
Propagate known class for log/log2/log10.
static LLVM_ABI KnownFPClass sqrt (const KnownFPClass &Src, DenormalMode Mode=DenormalMode::getDynamic())
Propagate known class for sqrt.
static LLVM_ABI KnownFPClass fpext (const KnownFPClass &KnownSrc, const fltSemantics &DstTy, const fltSemantics &SrcTy)
Propagate known class for fpext.
static LLVM_ABI KnownFPClass roundToIntegral (const KnownFPClass &Src, bool IsTrunc, bool IsMultiUnitFPType)
Propagate known class for rounding intrinsics (trunc, floor, ceil, rint, nearbyint, round, roundeven).
Public Attributes
FPClassTest KnownFPClasses = fcAllFlags
Floating-point classes the value could be one of.
std::optional< bool > SignBit
std::nullopt if the sign bit is unknown, true if the sign bit is definitely set or false if the sign bit is definitely unset.
Static Public Attributes
static constexpr FPClassTest OrderedLessThanZeroMask
static constexpr FPClassTest OrderedGreaterThanZeroMask
Detailed Description
Definition at line 25 of file KnownFPClass.h.
Member Enumeration Documentation
MinMaxKind
enum class llvm::KnownFPClass::MinMaxKind strong
Enumerator
minimum
maximum
minimumnum
maximumnum
minnum
maxnum
Definition at line 186 of file KnownFPClass.h.
Constructor & Destructor Documentation
KnownFPClass() [1/2]
llvm::KnownFPClass::KnownFPClass (FPClassTest Known = fcAllFlags, std::optional< bool > Sign = {}) inline
Definition at line 33 of file KnownFPClass.h.
References llvm::fcAllFlags.
Referenced by canonicalize(), copysign(), exp(), fmul(), fpext(), intersectWith(), log(), minMaxLike(), operator==(), operator|=(), propagateCanonicalizingSrc(), propagateDenormal(), propagateNaN(), resetAll(), roundToIntegral(), sqrt(), and square().
KnownFPClass() [2/2]
KnownFPClass::KnownFPClass (const APFloat & C)
Definition at line 20 of file KnownFPClass.cpp.
References llvm::CallingConv::C, KnownFPClasses, and SignBit.
Member Function Documentation
cannotBeOrderedGreaterEqZero()
bool llvm::KnownFPClass::cannotBeOrderedGreaterEqZero (DenormalMode Mode) const inline
Return true if it's know this can never be a negative value or a logical 0.
 NaN --> true
x >= -0 --> false nsub --> true if mode is ieee, false otherwise. x < -0 --> true
Definition at line 136 of file KnownFPClass.h.
References llvm::fcPositive, isKnownNever(), isKnownNeverLogicalNegZero(), and Mode.
Referenced by llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
cannotBeOrderedGreaterThanZero()
bool llvm::KnownFPClass::cannotBeOrderedGreaterThanZero () const inline
Return true if we can prove that the analyzed floating-point value is either NaN or never greater than -0.0.
NaN --> true +0 --> true -0 --> true x > +0 --> false x < -0 --> true
Definition at line 125 of file KnownFPClass.h.
References isKnownNever(), and OrderedGreaterThanZeroMask.
Referenced by computeKnownFPClass(), exp(), and minMaxLike().
cannotBeOrderedLessThanZero()
bool llvm::KnownFPClass::cannotBeOrderedLessThanZero () const inline
Return true if we can prove that the analyzed floating-point value is either NaN or never less than -0.0.
 NaN --> true
  +0 --> true
  -0 --> true
x > +0 --> true x < -0 --> false
Definition at line 114 of file KnownFPClass.h.
References isKnownNever(), and OrderedLessThanZeroMask.
Referenced by llvm::cannotBeOrderedLessThanZero(), computeKnownFPClass(), computeKnownFPClassForFPTrunc(), exp(), log(), minMaxLike(), simplifyFCmpInst(), and sqrt().
canonicalize()
KnownFPClass KnownFPClass::canonicalize (const KnownFPClass & Src, DenormalMode DenormMode = DenormalMode::getDynamic()) static
Apply the canonicalize intrinsic to this value.
This is essentially a stronger form of propagateCanonicalizingSrc.
Definition at line 186 of file KnownFPClass.cpp.
References llvm::fcNan, llvm::fcNegSubnormal, llvm::fcNegZero, llvm::fcPosSubnormal, llvm::fcPosZero, llvm::fcQNan, llvm::fcSNan, llvm::fcSubnormal, llvm::fcZero, llvm::DenormalMode::getIEEE(), llvm::DenormalMode::getPreserveSign(), llvm::DenormalMode::IEEE, llvm::DenormalMode::Input, llvm::DenormalMode::inputsAreZero(), isKnownNever(), isKnownNeverNaN(), KnownFPClass(), KnownFPClasses, knownNot(), llvm::DenormalMode::Output, llvm::DenormalMode::outputsAreZero(), and llvm::DenormalMode::PositiveZero.
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
copysign()
void llvm::KnownFPClass::copysign (const KnownFPClass & Sign) inline
Definition at line 238 of file KnownFPClass.h.
References llvm::fcInf, llvm::fcNan, llvm::fcNegative, llvm::fcNormal, llvm::fcPositive, llvm::fcSubnormal, llvm::fcZero, isKnownNever(), KnownFPClass(), KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
exp()
KnownFPClass KnownFPClass::exp (const KnownFPClass & Src) static
Report known values for exp, exp2 and exp10.
Definition at line 289 of file KnownFPClass.cpp.
References cannotBeOrderedGreaterThanZero(), cannotBeOrderedLessThanZero(), llvm::fcNegative, llvm::fcPosInf, llvm::fcPosSubnormal, llvm::fcPosZero, KnownFPClass(), knownNot(), and propagateNaN().
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
fabs()
void llvm::KnownFPClass::fabs () inline
Definition at line 169 of file KnownFPClass.h.
References llvm::fcNegInf, llvm::fcNegNormal, llvm::fcNegSubnormal, llvm::fcNegZero, llvm::fcPosInf, llvm::fcPosNormal, llvm::fcPosSubnormal, llvm::fcPosZero, KnownFPClasses, and signBitMustBeZero().
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
fmul()
KnownFPClass KnownFPClass::fmul (const KnownFPClass & LHS, const KnownFPClass & RHS, DenormalMode Mode = DenormalMode::getDynamic()) static
Report known values for fmul.
Definition at line 236 of file KnownFPClass.cpp.
References llvm::fcInf, llvm::fcNan, llvm::fcNegative, llvm::fcNormal, llvm::fcPositive, llvm::fcSubnormal, llvm::fcZero, isKnownAlways(), isKnownNever(), isKnownNeverInfinity(), isKnownNeverLogicalZero(), isKnownNeverNaN(), KnownFPClass(), knownNot(), SignBit, signBitMustBeOne(), and signBitMustBeZero().
Referenced by computeKnownFPClass(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), and square().
fneg()
void llvm::KnownFPClass::fneg () inline
Definition at line 163 of file KnownFPClass.h.
References llvm::fneg(), KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
fpext()
KnownFPClass KnownFPClass::fpext (const KnownFPClass & KnownSrc, const fltSemantics & DstTy, const fltSemantics & SrcTy) static
Propagate known class for fpext.
Definition at line 358 of file KnownFPClass.cpp.
References llvm::fcNegNormal, llvm::fcNegSubnormal, llvm::fcPosNormal, llvm::fcPosSubnormal, llvm::fcSubnormal, isKnownNeverNaN(), llvm::APFloatBase::isRepresentableAsNormalIn(), KnownFPClass(), KnownFPClasses, knownNot(), and SignBit.
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
intersectWith()
KnownFPClass llvm::KnownFPClass::intersectWith (const KnownFPClass & RHS) inline
Definition at line 140 of file KnownFPClass.h.
References KnownFPClass(), KnownFPClasses, RHS, and SignBit.
Referenced by computeKnownFPClass(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), and llvm::InstCombinerImpl::SimplifyMultipleUseDemandedFPClass().
isKnownAlways()
bool llvm::KnownFPClass::isKnownAlways (FPClassTest Mask) const inline
Definition at line 46 of file KnownFPClass.h.
References isKnownNever().
Referenced by computeKnownFPClass(), fmul(), isKnownAlwaysNaN(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
isKnownAlwaysNaN()
bool llvm::KnownFPClass::isKnownAlwaysNaN () const inline
Return true if it's known this must always be a nan.
Definition at line 54 of file KnownFPClass.h.
References llvm::fcNan, and isKnownAlways().
Referenced by simplifyFCmpInst().
isKnownNever()
bool llvm::KnownFPClass::isKnownNever (FPClassTest Mask) const inline
Return true if it's known this can never be one of the mask entries.
Definition at line 42 of file KnownFPClass.h.
References llvm::fcNone, and KnownFPClasses.
Referenced by cannotBeOrderedGreaterEqZero(), cannotBeOrderedGreaterThanZero(), cannotBeOrderedLessThanZero(), canonicalize(), computeKnownFPClass(), copysign(), fmul(), foldFPtoI(), isKnownAlways(), isKnownNeverInfinity(), isKnownNeverInfOrNaN(), isKnownNeverNaN(), isKnownNeverNegInfinity(), isKnownNeverNegSubnormal(), isKnownNeverNegZero(), isKnownNeverPosInfinity(), isKnownNeverPosSubnormal(), isKnownNeverPosZero(), isKnownNeverSubnormal(), isKnownNeverZero(), knownNot(), roundToIntegral(), signBitIsZeroOrNaN(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), simplifyFMAFMul(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedFPClass(), simplifyX86FPMaxMin(), and sqrt().
isKnownNeverInfinity()
bool llvm::KnownFPClass::isKnownNeverInfinity () const inline
Return true if it's known this can never be an infinity.
Definition at line 57 of file KnownFPClass.h.
References llvm::fcInf, and isKnownNever().
Referenced by computeKnownFPClass(), fmul(), llvm::InstCombinerImpl::fmulByZeroIsZero(), llvm::isKnownNeverInfinity(), and llvm::isKnownNeverInfOrNaN().
isKnownNeverInfOrNaN()
bool llvm::KnownFPClass::isKnownNeverInfOrNaN () const inline
Return true if it's known this can never be an infinity or nan.
Definition at line 60 of file KnownFPClass.h.
References llvm::fcInf, llvm::fcNan, and isKnownNever().
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
isKnownNeverLogicalNegZero()
bool KnownFPClass::isKnownNeverLogicalNegZero (DenormalMode Mode) const
Return true if it's known this can never be interpreted as a negative zero.
Definition at line 39 of file KnownFPClass.cpp.
References inputDenormalIsIEEEOrPosZero(), isKnownNeverNegSubnormal(), and isKnownNeverNegZero().
Referenced by cannotBeOrderedGreaterEqZero(), computeKnownFPClass(), and sqrt().
isKnownNeverLogicalPosZero()
bool KnownFPClass::isKnownNeverLogicalPosZero (DenormalMode Mode) const
Return true if it's known this can never be interpreted as a positive zero.
Definition at line 44 of file KnownFPClass.cpp.
References llvm::DenormalMode::IEEE, isKnownNeverPosSubnormal(), isKnownNeverPosZero(), isKnownNeverSubnormal(), llvm_unreachable, llvm::DenormalMode::PositiveZero, and llvm::DenormalMode::PreserveSign.
Referenced by computeKnownFPClass().
isKnownNeverLogicalZero()
bool KnownFPClass::isKnownNeverLogicalZero (DenormalMode Mode) const
Return true if it's known this can never be interpreted as a zero.
This extends isKnownNeverZero to cover the case where the assumed floating-point mode for the function interprets denormals as zero.
Definition at line 34 of file KnownFPClass.cpp.
References inputDenormalIsIEEE(), isKnownNeverSubnormal(), and isKnownNeverZero().
Referenced by computeKnownFPClass(), fmul(), log(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
isKnownNeverNaN()
bool llvm::KnownFPClass::isKnownNeverNaN () const inline
Return true if it's known this can never be a nan.
Definition at line 51 of file KnownFPClass.h.
References llvm::fcNan, and isKnownNever().
Referenced by canonicalize(), computeKnownFPClass(), fmul(), llvm::InstCombinerImpl::fmulByZeroIsZero(), fpext(), llvm::isKnownNeverInfOrNaN(), llvm::isKnownNeverNaN(), log(), minMaxLike(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), simplifyFCmpInst(), and sqrt().
isKnownNeverNegInfinity()
bool llvm::KnownFPClass::isKnownNeverNegInfinity () const inline
Return true if it's known this can never be -infinity.
Definition at line 66 of file KnownFPClass.h.
References llvm::fcNegInf, and isKnownNever().
Referenced by computeKnownFPClass(), and roundToIntegral().
isKnownNeverNegSubnormal()
bool llvm::KnownFPClass::isKnownNeverNegSubnormal () const inline
Return true if it's known this can never be a negative subnormal.
Definition at line 75 of file KnownFPClass.h.
References llvm::fcNegSubnormal, and isKnownNever().
Referenced by computeKnownFPClass(), and isKnownNeverLogicalNegZero().
isKnownNeverNegZero()
bool llvm::KnownFPClass::isKnownNeverNegZero () const inline
Return true if it's known this can never be a negative zero.
This means a literal -0 and does not include denormal inputs implicitly treated as -0.
Definition at line 86 of file KnownFPClass.h.
References llvm::fcNegZero, and isKnownNever().
Referenced by llvm::cannotBeNegativeZero(), isKnownNeverLogicalNegZero(), and minMaxLike().
isKnownNeverPosInfinity()
bool llvm::KnownFPClass::isKnownNeverPosInfinity () const inline
Return true if it's known this can never be +infinity.
Definition at line 63 of file KnownFPClass.h.
References llvm::fcPosInf, and isKnownNever().
Referenced by computeKnownFPClass(), log(), roundToIntegral(), and sqrt().
isKnownNeverPosSubnormal()
bool llvm::KnownFPClass::isKnownNeverPosSubnormal () const inline
Return true if it's known this can never be a positive subnormal.
Definition at line 72 of file KnownFPClass.h.
References llvm::fcPosSubnormal, and isKnownNever().
Referenced by computeKnownFPClass(), and isKnownNeverLogicalPosZero().
isKnownNeverPosZero()
bool llvm::KnownFPClass::isKnownNeverPosZero () const inline
Return true if it's known this can never be a literal positive zero.
Definition at line 82 of file KnownFPClass.h.
References llvm::fcPosZero, and isKnownNever().
Referenced by isKnownNeverLogicalPosZero(), and minMaxLike().
isKnownNeverSubnormal()
bool llvm::KnownFPClass::isKnownNeverSubnormal () const inline
Return true if it's known this can never be a subnormal.
Definition at line 69 of file KnownFPClass.h.
References llvm::fcSubnormal, and isKnownNever().
Referenced by computeKnownFPClass(), isKnownNeverLogicalPosZero(), isKnownNeverLogicalZero(), minMaxLike(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
isKnownNeverZero()
bool llvm::KnownFPClass::isKnownNeverZero () const inline
Return true if it's known this can never be a zero.
This means a literal [+-]0, and does not include denormal inputs implicitly treated as [+-]0.
Definition at line 79 of file KnownFPClass.h.
References llvm::fcZero, and isKnownNever().
Referenced by isKnownNeverLogicalZero(), and llvm::LegalizerHelper::lowerFMinimumMaximum().
isUnknown()
bool llvm::KnownFPClass::isUnknown () const inline
Definition at line 48 of file KnownFPClass.h.
References llvm::fcAllFlags, KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass().
knownNot()
void llvm::KnownFPClass::knownNot (FPClassTest RuleOut) inline
Definition at line 153 of file KnownFPClass.h.
References llvm::fcNan, llvm::fcNegative, llvm::fcPositive, isKnownNever(), KnownFPClasses, and SignBit.
Referenced by canonicalize(), computeKnownFPClass(), computeKnownFPClassForFPTrunc(), computeKnownFPClassFromCond(), exp(), fmul(), fpext(), log(), minMaxLike(), propagateNaN(), roundToIntegral(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), sqrt(), and square().
log()
KnownFPClass KnownFPClass::log (const KnownFPClass & Src, DenormalMode Mode = DenormalMode::getDynamic()) static
Propagate known class for log/log2/log10.
Definition at line 316 of file KnownFPClass.cpp.
References cannotBeOrderedLessThanZero(), llvm::fcNan, llvm::fcNegInf, llvm::fcNegZero, llvm::fcPosInf, isKnownNeverLogicalZero(), isKnownNeverNaN(), isKnownNeverPosInfinity(), KnownFPClass(), and knownNot().
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
minMaxLike()
KnownFPClass KnownFPClass::minMaxLike (const KnownFPClass & LHS, const KnownFPClass & RHS, MinMaxKind Kind, DenormalMode DenormMode = DenormalMode::getDynamic()) static
Definition at line 94 of file KnownFPClass.cpp.
References cannotBeOrderedGreaterThanZero(), cannotBeOrderedLessThanZero(), llvm::fcNan, llvm::fcNone, llvm::fcZero, llvm::DenormalMode::getIEEE(), isKnownNeverNaN(), isKnownNeverNegZero(), isKnownNeverPosZero(), isKnownNeverSubnormal(), KnownFPClass(), KnownFPClasses, knownNot(), llvm_unreachable, maximum, maximumnum, maxnum, minimum, minimumnum, minnum, OrderedGreaterThanZeroMask, OrderedLessThanZeroMask, SignBit, signBitMustBeOne(), and signBitMustBeZero().
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
operator==()
bool llvm::KnownFPClass::operator== (KnownFPClass Other) const inline
Definition at line 37 of file KnownFPClass.h.
References KnownFPClass(), KnownFPClasses, llvm::Other, and SignBit.
operator|=()
KnownFPClass & llvm::KnownFPClass::operator|= (const KnownFPClass & RHS) inline
Definition at line 145 of file KnownFPClass.h.
References KnownFPClass(), KnownFPClasses, RHS, and SignBit.
propagateCanonicalizingSrc()
void KnownFPClass::propagateCanonicalizingSrc (const KnownFPClass & Src, DenormalMode Mode)
Report known classes if Src is evaluated through a potentially canonicalizing operation.
We can assume signaling nans will not be introduced, but cannot assume a denormal will be flushed under FTZ/DAZ.
This assumes a copy-like operation and will replace any currently known information.
Definition at line 310 of file KnownFPClass.cpp.
References KnownFPClass(), propagateDenormal(), and propagateNaN().
Referenced by computeKnownFPClass().
propagateDenormal()
void KnownFPClass::propagateDenormal (const KnownFPClass & Src, DenormalMode Mode)
Propagate knowledge from a source value that could be a denormal or zero.
We have to be conservative since output flushing is not guaranteed, so known-never-zero may not hold.
This assumes a copy-like operation and will replace any currently known information.
Definition at line 67 of file KnownFPClass.cpp.
References llvm::DenormalMode::Dynamic, llvm::fcNegZero, llvm::fcPosZero, llvm::DenormalMode::getIEEE(), llvm::DenormalMode::getPositiveZero(), KnownFPClass(), KnownFPClasses, and llvm::DenormalMode::PositiveZero.
Referenced by propagateCanonicalizingSrc().
propagateNaN()
void llvm::KnownFPClass::propagateNaN (const KnownFPClass & Src, bool PreserveSign = false) inline
Definition at line 263 of file KnownFPClass.h.
References llvm::fcNan, llvm::fcSNan, KnownFPClass(), knownNot(), and SignBit.
Referenced by computeKnownFPClass(), computeKnownFPClassForFPTrunc(), exp(), propagateCanonicalizingSrc(), and roundToIntegral().
resetAll()
void llvm::KnownFPClass::resetAll () inline
Definition at line 309 of file KnownFPClass.h.
References KnownFPClass().
Referenced by computeKnownFPClass(), and llvm::TargetLowering::computeKnownFPClassForTargetInstr().
roundToIntegral()
KnownFPClass KnownFPClass::roundToIntegral (const KnownFPClass & Src, bool IsTrunc, bool IsMultiUnitFPType) static
Propagate known class for rounding intrinsics (trunc, floor, ceil, rint, nearbyint, round, roundeven).
This is trunc if IsTrunc. IsMultiUnitFPType if this is for a multi-unit floating-point type.
Definition at line 380 of file KnownFPClass.cpp.
References llvm::fcNegFinite, llvm::fcNegInf, llvm::fcPosFinite, llvm::fcPosInf, llvm::fcSubnormal, isKnownNever(), isKnownNeverNegInfinity(), isKnownNeverPosInfinity(), KnownFPClass(), knownNot(), and propagateNaN().
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
signBitIsZeroOrNaN()
bool llvm::KnownFPClass::signBitIsZeroOrNaN () const inline
Return true if the sign bit must be 0, ignoring the sign of nans.
Definition at line 224 of file KnownFPClass.h.
References llvm::fcNegative, and isKnownNever().
Referenced by llvm::InstCombinerImpl::fmulByZeroIsZero().
signBitMustBeOne()
void llvm::KnownFPClass::signBitMustBeOne () inline
Assume the sign bit is one.
Definition at line 233 of file KnownFPClass.h.
References llvm::fcNan, llvm::fcNegative, KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass(), computeKnownFPClassFromCond(), fmul(), and minMaxLike().
signBitMustBeZero()
void llvm::KnownFPClass::signBitMustBeZero () inline
Assume the sign bit is zero.
Definition at line 227 of file KnownFPClass.h.
References llvm::fcNan, llvm::fcPositive, KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass(), computeKnownFPClassFromCond(), fabs(), fmul(), and minMaxLike().
sqrt()
KnownFPClass KnownFPClass::sqrt (const KnownFPClass & Src, DenormalMode Mode = DenormalMode::getDynamic()) static
Propagate known class for sqrt.
Definition at line 333 of file KnownFPClass.cpp.
References cannotBeOrderedLessThanZero(), llvm::fcNan, llvm::fcNegInf, llvm::fcNegNormal, llvm::fcNegSubnormal, llvm::fcNegZero, llvm::fcPosInf, llvm::fcPosSubnormal, llvm::fcSNan, isKnownNever(), isKnownNeverLogicalNegZero(), isKnownNeverNaN(), isKnownNeverPosInfinity(), KnownFPClass(), and knownNot().
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
square()
KnownFPClass llvm::KnownFPClass::square (const KnownFPClass & Src, DenormalMode Mode = DenormalMode::getDynamic()) inline static
Definition at line 211 of file KnownFPClass.h.
References llvm::fcNegative, fmul(), llvm::DenormalMode::getDynamic(), KnownFPClass(), knownNot(), and Mode.
Referenced by computeKnownFPClass(), and llvm::InstCombinerImpl::SimplifyDemandedUseFPClass().
Member Data Documentation
KnownFPClasses
FPClassTest llvm::KnownFPClass::KnownFPClasses = fcAllFlags
Floating-point classes the value could be one of.
Definition at line 27 of file KnownFPClass.h.
Referenced by canonicalize(), computeKnownFPClass(), copysign(), fabs(), fneg(), fpext(), intersectWith(), isKnownNever(), isUnknown(), KnownFPClass(), knownNot(), minMaxLike(), operator==(), operator|=(), propagateDenormal(), signBitMustBeOne(), signBitMustBeZero(), llvm::InstCombinerImpl::SimplifyDemandedFPClass(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), and llvm::InstCombinerImpl::SimplifyMultipleUseDemandedFPClass().
OrderedGreaterThanZeroMask
FPClassTest llvm::KnownFPClass::OrderedGreaterThanZeroMask static constexpr
Initial value:
                                                    =
fcPosSubnormal | fcPosNormal | fcPosInf
Definition at line 103 of file KnownFPClass.h.
Referenced by cannotBeOrderedGreaterThanZero(), computeKnownFPClass(), and minMaxLike().
OrderedLessThanZeroMask
FPClassTest llvm::KnownFPClass::OrderedLessThanZeroMask static constexpr
Initial value:
                                                 =
fcNegSubnormal | fcNegNormal | fcNegInf
Definition at line 101 of file KnownFPClass.h.
Referenced by llvm::cannotBeOrderedLessThanZero(), cannotBeOrderedLessThanZero(), computeKnownFPClass(), computeKnownFPClassForFPTrunc(), minMaxLike(), and simplifyFCmpInst().
SignBit
std::optional<bool> llvm::KnownFPClass::SignBit
std::nullopt if the sign bit is unknown, true if the sign bit is definitely set or false if the sign bit is definitely unset.
Definition at line 31 of file KnownFPClass.h.
Referenced by computeKnownFPClass(), llvm::computeKnownFPSignBit(), copysign(), fmul(), fneg(), fpext(), intersectWith(), isUnknown(), KnownFPClass(), knownNot(), minMaxLike(), operator==(), operator|=(), propagateNaN(), signBitMustBeOne(), signBitMustBeZero(), llvm::InstCombinerImpl::SimplifyDemandedUseFPClass(), and simplifyFMAFMul().
The documentation for this struct was generated from the following files:
include/llvm/Support/KnownFPClass.h
lib/Support/KnownFPClass.cpp