LLVM: llvm::ms_demangle::ThunkSignatureNode Struct Reference
llvm::ms_demangle::ThunkSignatureNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Classes
struct ThisAdjustor
Public Member Functions
ThunkSignatureNode ()
void outputPre (OutputBuffer &OB, OutputFlags Flags) const override
void outputPost (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::FunctionSignatureNode
FunctionSignatureNode (NodeKind K)
FunctionSignatureNode ()
Public Member Functions inherited from llvm::ms_demangle::TypeNode
TypeNode (NodeKind K)
void output (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
DEMANGLE_ABI std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Static Public Member Functions inherited from llvm::ms_demangle::FunctionSignatureNode
static bool classof (const Node *N)
Static Public Member Functions inherited from llvm::ms_demangle::TypeNode
static bool classof (const Node *N)
Public Attributes
ThisAdjustor ThisAdjust
Public Attributes inherited from llvm::ms_demangle::FunctionSignatureNode
PointerAffinity Affinity = PointerAffinity::None
CallingConv CallConvention = CallingConv::None
FuncClass FunctionClass = FC_Global
FunctionRefQualifier RefQualifier = FunctionRefQualifier::None
TypeNode * ReturnType = nullptr
bool IsVariadic = false
NodeArrayNode * Params = nullptr
bool IsNoexcept = false
Public Attributes inherited from llvm::ms_demangle::TypeNode
Qualifiers Quals = Q_None
Detailed Description
Definition at line 513 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
ThunkSignatureNode()
llvm::ms_demangle::ThunkSignatureNode::ThunkSignatureNode () inline
Definition at line 514 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::FunctionSignatureNode::FunctionSignatureNode(), and llvm::ms_demangle::ThunkSignature.
Member Function Documentation
classof()
bool llvm::ms_demangle::ThunkSignatureNode::classof (const Node * N) inline static
Definition at line 519 of file MicrosoftDemangleNodes.h.
References N, and llvm::ms_demangle::ThunkSignature.
outputPost()
void ThunkSignatureNode::outputPost (OutputBuffer & OB, OutputFlags Flags) const override virtual
Reimplemented from llvm::ms_demangle::FunctionSignatureNode.
Definition at line 463 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::FC_StaticThisAdjust, llvm::ms_demangle::FC_VirtualThisAdjust, llvm::ms_demangle::FC_VirtualThisAdjustEx, llvm::ms_demangle::FunctionSignatureNode::FunctionClass, llvm::ms_demangle::FunctionSignatureNode::outputPost(), and ThisAdjust.
outputPre()
void ThunkSignatureNode::outputPre (OutputBuffer & OB, OutputFlags Flags) const override virtual
Reimplemented from llvm::ms_demangle::FunctionSignatureNode.
Definition at line 457 of file MicrosoftDemangleNodes.cpp.
References llvm::ms_demangle::FunctionSignatureNode::outputPre().
Member Data Documentation
ThisAdjust
ThisAdjustor llvm::ms_demangle::ThunkSignatureNode::ThisAdjust
Definition at line 530 of file MicrosoftDemangleNodes.h.
Referenced by outputPost().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp