LLVM: GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * > Struct Template Reference
GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * > Struct Template Reference
Public Types
using GraphType = const CallsiteContextGraph<DerivedCCG, FuncTy, CallTy> *
using NodeRef = const ContextNode<DerivedCCG, FuncTy, CallTy> *
using NodePtrTy = std::unique_ptr<ContextNode<DerivedCCG, FuncTy, CallTy>>
using nodes_iterator
using EdgePtrTy = std::shared_ptr<ContextEdge<DerivedCCG, FuncTy, CallTy>>
using ChildIteratorType
Static Public Member Functions
static NodeRef getNode (const NodePtrTy &P)
static nodes_iterator nodes_begin (GraphType G)
static nodes_iterator nodes_end (GraphType G)
static NodeRef getEntryNode (GraphType G)
static const ContextNode< DerivedCCG, FuncTy, CallTy > * GetCallee (const EdgePtrTy &P)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
template<typename DerivedCCG, typename FuncTy, typename CallTy>
struct GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >
Definition at line 3337 of file MemProfContextDisambiguation.cpp.
Member Typedef Documentation
ChildIteratorType
template<typename DerivedCCG, typename FuncTy, typename CallTy> using GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::ChildIteratorType
Initial value:
mapped_iterator<typename std::vector<std::shared_ptr<ContextEdge<
                    DerivedCCG, FuncTy, CallTy>>>::const_iterator,
                decltype(&GetCallee)>
Definition at line 3366 of file MemProfContextDisambiguation.cpp.
EdgePtrTy
template<typename DerivedCCG, typename FuncTy, typename CallTy> using GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::EdgePtrTy = std::shared_ptr<ContextEdge<DerivedCCG, FuncTy, CallTy>>
Definition at line 3360 of file MemProfContextDisambiguation.cpp.
GraphType
template<typename DerivedCCG, typename FuncTy, typename CallTy> using GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::GraphType = const CallsiteContextGraph<DerivedCCG, FuncTy, CallTy> *
Definition at line 3338 of file MemProfContextDisambiguation.cpp.
NodePtrTy
template<typename DerivedCCG, typename FuncTy, typename CallTy> using GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::NodePtrTy = std::unique_ptr<ContextNode<DerivedCCG, FuncTy, CallTy>>
Definition at line 3341 of file MemProfContextDisambiguation.cpp.
NodeRef
template<typename DerivedCCG, typename FuncTy, typename CallTy> using GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::NodeRef = const ContextNode<DerivedCCG, FuncTy, CallTy> *
Definition at line 3339 of file MemProfContextDisambiguation.cpp.
nodes_iterator
template<typename DerivedCCG, typename FuncTy, typename CallTy> using GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::nodes_iterator
Initial value:
mapped_iterator<typename std::vector<NodePtrTy>::const_iterator,
                decltype(&getNode)>
Definition at line 3344 of file MemProfContextDisambiguation.cpp.
Member Function Documentation
child_begin()
template<typename DerivedCCG, typename FuncTy, typename CallTy> ChildIteratorType GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::child_begin (NodeRef N) inline static
Definition at line 3371 of file MemProfContextDisambiguation.cpp.
References GetCallee(), and N.
child_end()
template<typename DerivedCCG, typename FuncTy, typename CallTy> ChildIteratorType GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::child_end (NodeRef N) inline static
Definition at line 3375 of file MemProfContextDisambiguation.cpp.
References GetCallee(), and N.
GetCallee()
template<typename DerivedCCG, typename FuncTy, typename CallTy> const ContextNode< DerivedCCG, FuncTy, CallTy > * GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::GetCallee (const EdgePtrTy & P) inline static
Definition at line 3362 of file MemProfContextDisambiguation.cpp.
References P.
Referenced by child_begin(), and child_end().
getEntryNode()
template<typename DerivedCCG, typename FuncTy, typename CallTy> NodeRef GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::getEntryNode (GraphType G) inline static
Definition at line 3356 of file MemProfContextDisambiguation.cpp.
References G.
getNode()
template<typename DerivedCCG, typename FuncTy, typename CallTy> NodeRef GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::getNode (const NodePtrTy & P) inline static
Definition at line 3342 of file MemProfContextDisambiguation.cpp.
References P.
Referenced by nodes_begin(), and nodes_end().
nodes_begin()
template<typename DerivedCCG, typename FuncTy, typename CallTy> nodes_iterator GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::nodes_begin (GraphType G) inline static
Definition at line 3348 of file MemProfContextDisambiguation.cpp.
References G, and getNode().
nodes_end()
template<typename DerivedCCG, typename FuncTy, typename CallTy> nodes_iterator GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::nodes_end (GraphType G) inline static
Definition at line 3352 of file MemProfContextDisambiguation.cpp.
References G, and getNode().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/MemProfContextDisambiguation.cpp