LLVM: llvm::MCAsmMacroParameter Struct Reference
llvm::MCAsmMacroParameter Struct Reference
#include "llvm/MC/MCAsmMacro.h"
Public Member Functions
void dump () const
LLVM_DUMP_METHOD void dump (raw_ostream &OS) const
Public Attributes
StringRef Name
std::vector< AsmToken > Value
bool Required = false
bool Vararg = false
Detailed Description
Definition at line 122 of file MCAsmMacro.h.
Member Function Documentation
dump() [1/2]
void llvm::MCAsmMacroParameter::dump () const inline
Definition at line 129 of file MCAsmMacro.h.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void MCAsmMacroParameter::dump (raw_ostream & OS) const
Definition at line 15 of file MCAsmMacro.cpp.
References Name, Required, T, Value, and Vararg.
Member Data Documentation
Name
StringRef llvm::MCAsmMacroParameter::Name
Definition at line 123 of file MCAsmMacro.h.
Referenced by dump().
Required
bool llvm::MCAsmMacroParameter::Required = false
Definition at line 125 of file MCAsmMacro.h.
Referenced by dump().
Value
std::vector<AsmToken> llvm::MCAsmMacroParameter::Value
Definition at line 124 of file MCAsmMacro.h.
Referenced by dump().
Vararg
bool llvm::MCAsmMacroParameter::Vararg = false
Definition at line 126 of file MCAsmMacro.h.
Referenced by dump().
The documentation for this struct was generated from the following files:
include/llvm/MC/MCAsmMacro.h
lib/MC/MCAsmMacro.cpp