LLVM: llvm::sampleprof::SampleContextFrame Struct Reference
llvm::sampleprof::SampleContextFrame Struct Reference
#include "llvm/ProfileData/SampleProf.h"
Public Member Functions
SampleContextFrame ()
SampleContextFrame (FunctionId Func, LineLocation Location)
bool operator== (const SampleContextFrame &That) const
bool operator!= (const SampleContextFrame &That) const
std::string toString (bool OutputLineLocation) const
uint64_t getHashCode () const
Public Attributes
FunctionId Func
LineLocation Location
Detailed Description
Definition at line 496 of file SampleProf.h.
Constructor & Destructor Documentation
SampleContextFrame() [1/2]
llvm::sampleprof::SampleContextFrame::SampleContextFrame () inline
Definition at line 500 of file SampleProf.h.
References Location.
Referenced by operator!=(), and operator==().
SampleContextFrame() [2/2]
llvm::sampleprof::SampleContextFrame::SampleContextFrame (FunctionId Func, LineLocation Location) inline
Definition at line 502 of file SampleProf.h.
References Func, and Location.
Member Function Documentation
getHashCode()
uint64_t llvm::sampleprof::SampleContextFrame::getHashCode () const inline
Definition at line 524 of file SampleProf.h.
References Func, and Location.
Referenced by llvm::sampleprof::FunctionSamples::getCallSiteHash(), and llvm::sampleprof::hash_value().
operator!=()
bool llvm::sampleprof::SampleContextFrame::operator!= (const SampleContextFrame & That) const inline
Definition at line 509 of file SampleProf.h.
References SampleContextFrame().
operator==()
bool llvm::sampleprof::SampleContextFrame::operator== (const SampleContextFrame & That) const inline
Definition at line 505 of file SampleProf.h.
References Func, Location, and SampleContextFrame().
toString()
std::string llvm::sampleprof::SampleContextFrame::toString (bool OutputLineLocation) const inline
Definition at line 513 of file SampleProf.h.
References Func, and Location.
Member Data Documentation
Func
FunctionId llvm::sampleprof::SampleContextFrame::Func
Definition at line 497 of file SampleProf.h.
Referenced by getHashCode(), operator==(), SampleContextFrame(), and toString().
Location
LineLocation llvm::sampleprof::SampleContextFrame::Location
Definition at line 498 of file SampleProf.h.
Referenced by getHashCode(), operator==(), SampleContextFrame(), SampleContextFrame(), and toString().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/SampleProf.h