LLVM: llvm::yaml::MappingTraits< OffloadYAML::Binary::StringEntry > Struct Reference
llvm::yaml::MappingTraits< OffloadYAML::Binary::StringEntry > Struct Reference
#include "llvm/ObjectYAML/OffloadYAML.h"
Static Public Member Functions
static void mapping (IO &IO, OffloadYAML::Binary::StringEntry &M)
Detailed Description
Definition at line 68 of file OffloadYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< OffloadYAML::Binary::StringEntry >::mapping (IO & IO, OffloadYAML::Binary::StringEntry & M) static
Definition at line 59 of file OffloadYAML.cpp.
References assert(), llvm::yaml::IO::getContext(), llvm::OffloadYAML::Binary::StringEntry::Key, llvm::yaml::IO::mapRequired(), and llvm::OffloadYAML::Binary::StringEntry::Value.
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/OffloadYAML.h
lib/ObjectYAML/OffloadYAML.cpp