LLVM: llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t > Struct Template Reference
llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t > Struct Template Reference
Match unsigned remainder pattern.
#include "llvm/Analysis/ScalarEvolutionPatternMatch.h"
Public Member Functions
SCEVURem_match (Op0_t Op0, Op1_t Op1, ScalarEvolution &SE)
bool match (const SCEV *Expr) const
Public Attributes
Op0_t Op0
Op1_t Op1
ScalarEvolution & SE
Detailed Description
template<typename Op0_t, typename Op1_t>
struct llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >
Match unsigned remainder pattern.
Matches patterns generated by getURemExpr.
Definition at line 273 of file ScalarEvolutionPatternMatch.h.
Constructor & Destructor Documentation
SCEVURem_match()
template<typename Op0_t, typename Op1_t> llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::SCEVURem_match (Op0_t Op0, Op1_t Op1, ScalarEvolution & SE) inline
Definition at line 278 of file ScalarEvolutionPatternMatch.h.
References Op0, Op1, and SE.
Member Function Documentation
match()
template<typename Op0_t, typename Op1_t> bool llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::match (const SCEV * Expr) const inline
Definition at line 281 of file ScalarEvolutionPatternMatch.h.
References A(), B(), llvm::cast(), llvm::SCEV::getType(), llvm::isa(), llvm::Type::isPointerTy(), LHS, llvm::SCEVPatternMatch::m_SCEV(), llvm::SCEVPatternMatch::m_scev_Add(), llvm::SCEVPatternMatch::m_scev_Mul(), llvm::SCEVPatternMatch::m_scev_Trunc(), llvm::SCEVPatternMatch::m_scev_ZExt(), llvm::SCEVPatternMatch::match(), Mul, Op0, Op1, RHS, and SE.
Member Data Documentation
Op0
template<typename Op0_t, typename Op1_t> Op0_t llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::Op0
Definition at line 274 of file ScalarEvolutionPatternMatch.h.
Referenced by match(), and SCEVURem_match().
Op1
template<typename Op0_t, typename Op1_t> Op1_t llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::Op1
Definition at line 275 of file ScalarEvolutionPatternMatch.h.
Referenced by match(), and SCEVURem_match().
SE
template<typename Op0_t, typename Op1_t> ScalarEvolution& llvm::SCEVPatternMatch::SCEVURem_match< Op0_t, Op1_t >::SE
Definition at line 276 of file ScalarEvolutionPatternMatch.h.
Referenced by match(), and SCEVURem_match().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/ScalarEvolutionPatternMatch.h