LLVM: llvm::detail::index_iterator Struct Reference
llvm::detail::index_iterator Struct Reference
#include "llvm/ADT/STLExtras.h"
Public Member Functions
index_iterator (std::size_t Index)
index_iterator & operator+= (std::ptrdiff_t N)
index_iterator & operator-= (std::ptrdiff_t N)
std::ptrdiff_t operator- (const index_iterator &R) const
std::size_t operator* () const
Public Member Functions inherited from llvm::iterator_facade_base< index_iterator, std::random_access_iterator_tag, std::size_t >
index_iterator operator+ (std::ptrdiff_t n) const
index_iterator operator- (std::ptrdiff_t n) const
index_iterator & operator++ ()
index_iterator & operator-- ()
bool operator!= (const index_iterator &RHS) const
bool operator> (const index_iterator &RHS) const
bool operator<= (const index_iterator &RHS) const
bool operator>= (const index_iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Friends
bool operator== (const index_iterator &Lhs, const index_iterator &Rhs)
bool operator< (const index_iterator &Lhs, const index_iterator &Rhs)
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< index_iterator, std::random_access_iterator_tag, std::size_t >
enum
using iterator_category
using value_type
using difference_type
using pointer
using reference
Detailed Description
Definition at line 2432 of file STLExtras.h.
Constructor & Destructor Documentation
index_iterator()
llvm::detail::index_iterator::index_iterator (std::size_t Index) inline
Definition at line 2435 of file STLExtras.h.
Referenced by operator+=(), operator-(), operator-=(), operator<, and operator==.
Member Function Documentation
operator*()
std::size_t llvm::detail::index_iterator::operator* () const inline
Definition at line 2456 of file STLExtras.h.
operator+=()
index_iterator & llvm::detail::index_iterator::operator+= (std::ptrdiff_t N) inline
Definition at line 2437 of file STLExtras.h.
References index_iterator(), and N.
operator-()
std::ptrdiff_t llvm::detail::index_iterator::operator- (const index_iterator & R) const inline
Definition at line 2447 of file STLExtras.h.
References index_iterator().
operator-=()
index_iterator & llvm::detail::index_iterator::operator-= (std::ptrdiff_t N) inline
Definition at line 2442 of file STLExtras.h.
References index_iterator(), and N.
Friends And Related Symbol Documentation
operator<
bool operator< (const index_iterator & Lhs, const index_iterator & Rhs) friend
Definition at line 2462 of file STLExtras.h.
References index_iterator().
operator==
bool operator== (const index_iterator & Lhs, const index_iterator & Rhs) friend
Definition at line 2458 of file STLExtras.h.
References index_iterator().
The documentation for this struct was generated from the following file:
include/llvm/ADT/STLExtras.h