LLVM: llvm::ms_demangle::Node Struct Reference
llvm::ms_demangle::Node Struct Reference abstract
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
virtual void output (OutputBuffer &OB, OutputFlags Flags) const =0
DEMANGLE_ABI std::string toString (OutputFlags Flags=OF_Default) const
Detailed Description
Definition at line 277 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
Node()
llvm::ms_demangle::Node::Node (NodeKind K) inline explicit
Definition at line 278 of file MicrosoftDemangleNodes.h.
Referenced by llvm::ms_demangle::IdentifierNode::classof(), llvm::ms_demangle::IntegerLiteralNode::classof(), llvm::ms_demangle::NodeArrayNode::classof(), llvm::ms_demangle::PointerAuthQualifierNode::classof(), llvm::ms_demangle::QualifiedNameNode::classof(), llvm::ms_demangle::SymbolNode::classof(), llvm::ms_demangle::TemplateParameterReferenceNode::classof(), llvm::ms_demangle::TypeNode::classof(), llvm::ms_demangle::QualifiedNameNode::getUnqualifiedIdentifier(), llvm::ms_demangle::IdentifierNode::IdentifierNode(), llvm::ms_demangle::IntegerLiteralNode::IntegerLiteralNode(), llvm::ms_demangle::IntegerLiteralNode::IntegerLiteralNode(), llvm::ms_demangle::NodeArrayNode::NodeArrayNode(), llvm::ms_demangle::PointerAuthQualifierNode::PointerAuthQualifierNode(), llvm::ms_demangle::QualifiedNameNode::QualifiedNameNode(), llvm::ms_demangle::SymbolNode::SymbolNode(), llvm::ms_demangle::TemplateParameterReferenceNode::TemplateParameterReferenceNode(), and llvm::ms_demangle::TypeNode::TypeNode().
~Node()
virtual llvm::ms_demangle::Node::~Node () virtual default
Member Function Documentation
kind()
NodeKind llvm::ms_demangle::Node::kind () const inline
Definition at line 281 of file MicrosoftDemangleNodes.h.
output()
virtual void llvm::ms_demangle::Node::output (OutputBuffer & OB, OutputFlags Flags) const pure virtual
Implemented in llvm::ms_demangle::ConversionOperatorIdentifierNode, llvm::ms_demangle::DynamicStructorIdentifierNode, llvm::ms_demangle::EncodedStringLiteralNode, llvm::ms_demangle::FunctionSymbolNode, llvm::ms_demangle::IntegerLiteralNode, llvm::ms_demangle::IntrinsicFunctionIdentifierNode, llvm::ms_demangle::IntrinsicNode, llvm::ms_demangle::LiteralOperatorIdentifierNode, llvm::ms_demangle::LocalStaticGuardIdentifierNode, llvm::ms_demangle::LocalStaticGuardVariableNode, llvm::ms_demangle::NamedIdentifierNode, llvm::ms_demangle::NodeArrayNode, llvm::ms_demangle::PointerAuthQualifierNode, llvm::ms_demangle::QualifiedNameNode, llvm::ms_demangle::RttiBaseClassDescriptorNode, llvm::ms_demangle::SpecialTableSymbolNode, llvm::ms_demangle::StructorIdentifierNode, llvm::ms_demangle::SymbolNode, llvm::ms_demangle::TemplateParameterReferenceNode, llvm::ms_demangle::TypeNode, llvm::ms_demangle::VariableSymbolNode, and llvm::ms_demangle::VcallThunkIdentifierNode.
References DEMANGLE_ABI, and llvm::ms_demangle::OF_Default.
Referenced by toString().
toString()
std::string Node::toString (OutputFlags Flags = OF_Default) const
Definition at line 120 of file MicrosoftDemangleNodes.cpp.
References output(), and toString().
Referenced by toString().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp