LLVM: llvm::vfs::OutputConfig Struct Reference
llvm::vfs::OutputConfig Struct Reference
Full configuration for an output for use by the OutputBackend.
#include "llvm/Support/VirtualOutputConfig.h"
Public Member Functions
LLVM_ABI_FOR_TEST void print (raw_ostream &OS) const
void dump () const
constexpr OutputConfig & setBinary ()
constexpr OutputConfig & setTextWithCRLF ()
constexpr OutputConfig & setTextWithCRLF (bool Value)
constexpr bool getTextWithCRLF () const
constexpr bool getBinary () const
LLVM_ABI_FOR_TEST OutputConfig & setOpenFlags (const sys::fs::OpenFlags &Flags)
Updates Text and CRLF flags based on sys::fs::OF_Text and sys::fs::OF_CRLF in Flags.
constexpr OutputConfig ()
bool operator== (OutputConfig RHS) const
bool operator!= (OutputConfig RHS) const
Detailed Description
Full configuration for an output for use by the OutputBackend.
Each configuration flag is either true or false.
Definition at line 37 of file VirtualOutputConfig.h.
Constructor & Destructor Documentation
OutputConfig()
llvm::vfs::OutputConfig::OutputConfig () inline constexpr
Definition at line 66 of file VirtualOutputConfig.h.
References HANDLE_OUTPUT_CONFIG_FLAG.
Referenced by operator!=(), operator==(), setBinary(), setOpenFlags(), setTextWithCRLF(), and setTextWithCRLF().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void OutputConfig::dump () const
Definition at line 50 of file VirtualOutputConfig.cpp.
References llvm::dbgs(), LLVM_DUMP_METHOD, and print().
getBinary()
bool llvm::vfs::OutputConfig::getBinary () const inline constexpr
Definition at line 59 of file VirtualOutputConfig.h.
getTextWithCRLF()
bool llvm::vfs::OutputConfig::getTextWithCRLF () const inline constexpr
Definition at line 58 of file VirtualOutputConfig.h.
Referenced by generateFlagsFromConfig().
operator!=()
bool llvm::vfs::OutputConfig::operator!= (OutputConfig RHS) const inline
Definition at line 80 of file VirtualOutputConfig.h.
References operator==(), OutputConfig(), and RHS.
operator==()
bool llvm::vfs::OutputConfig::operator== (OutputConfig RHS) const inline
Definition at line 73 of file VirtualOutputConfig.h.
References OutputConfig(), and RHS.
Referenced by operator!=().
print()
void OutputConfig::print (raw_ostream & OS) const
Definition at line 30 of file VirtualOutputConfig.cpp.
Referenced by dump(), and llvm::operator<<().
setBinary()
OutputConfig & llvm::vfs::OutputConfig::setBinary () inline constexpr
Definition at line 53 of file VirtualOutputConfig.h.
References OutputConfig().
Referenced by setOpenFlags(), and setTextWithCRLF().
setOpenFlags()
OutputConfig & OutputConfig::setOpenFlags (const sys::fs::OpenFlags & Flags)
Updates Text and CRLF flags based on sys::fs::OF_Text and sys::fs::OF_CRLF in Flags.
Rejects CRLF without Text (calling setBinary()).
Definition at line 22 of file VirtualOutputConfig.cpp.
References llvm::sys::fs::OF_Append, llvm::sys::fs::OF_CRLF, llvm::sys::fs::OF_Text, OutputConfig(), and setBinary().
setTextWithCRLF() [1/2]
OutputConfig & llvm::vfs::OutputConfig::setTextWithCRLF () inline constexpr
Definition at line 54 of file VirtualOutputConfig.h.
References OutputConfig().
setTextWithCRLF() [2/2]
OutputConfig & llvm::vfs::OutputConfig::setTextWithCRLF (bool Value) inline constexpr
Definition at line 55 of file VirtualOutputConfig.h.
References OutputConfig(), and setBinary().
The documentation for this struct was generated from the following files:
include/llvm/Support/VirtualOutputConfig.h
lib/Support/VirtualOutputConfig.cpp