LLVM: llvm::DenseMapInfo< ValueIDNum > Struct Reference
llvm::DenseMapInfo< ValueIDNum > Struct Reference
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Static Public Member Functions
static ValueIDNum getEmptyKey ()
static ValueIDNum getTombstoneKey ()
static unsigned getHashValue (const ValueIDNum &Val)
static bool isEqual (const ValueIDNum &A, const ValueIDNum &B)
Detailed Description
Definition at line 226 of file InstrRefBasedImpl.h.
Member Function Documentation
getEmptyKey()
ValueIDNum llvm::DenseMapInfo< ValueIDNum >::getEmptyKey () inline static
Definition at line 227 of file InstrRefBasedImpl.h.
References LiveDebugValues::ValueIDNum::EmptyValue.
getHashValue()
unsigned llvm::DenseMapInfo< ValueIDNum >::getHashValue (const ValueIDNum & Val) inline static
Definition at line 232 of file InstrRefBasedImpl.h.
References LiveDebugValues::ValueIDNum::asU64(), and llvm::hash_value().
getTombstoneKey()
ValueIDNum llvm::DenseMapInfo< ValueIDNum >::getTombstoneKey () inline static
Definition at line 228 of file InstrRefBasedImpl.h.
References LiveDebugValues::ValueIDNum::TombstoneValue.
isEqual()
bool llvm::DenseMapInfo< ValueIDNum >::isEqual (const ValueIDNum & A, const ValueIDNum & B) inline static
Definition at line 236 of file InstrRefBasedImpl.h.
References A(), and B().
The documentation for this struct was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h