LLVM: false::SUnitWithMemInfo Struct Reference
false::SUnitWithMemInfo Struct Reference
This class holds an SUnit corresponding to a memory operation and other information related to the instruction.
Public Member Functions
SUnitWithMemInfo (SUnit *SU)
bool isTriviallyDisjoint (const SUnitWithMemInfo &Other) const
bool isUnknown () const
Public Attributes
SUnit * SU
SmallVector< const Value *, 2 > UnderlyingObjs
const Value * MemOpValue = nullptr
The value of a memory operand.
int64_t MemOpOffset = 0
The offset of a memory operand.
AAMDNodes AATags
bool IsAllIdentified = false
True if all the underlying objects are identified.
Detailed Description
This class holds an SUnit corresponding to a memory operation and other information related to the instruction.
Definition at line 248 of file MachinePipeliner.cpp.
Constructor & Destructor Documentation
SUnitWithMemInfo()
SUnitWithMemInfo::SUnitWithMemInfo (SUnit * SU)
Definition at line 1009 of file MachinePipeliner.cpp.
References IsAllIdentified, llvm::isIdentifiedObject(), SU, SUnitWithMemInfo(), and UnderlyingObjs.
Referenced by isTriviallyDisjoint(), and SUnitWithMemInfo().
Member Function Documentation
isTriviallyDisjoint()
bool SUnitWithMemInfo::isTriviallyDisjoint (const SUnitWithMemInfo & Other) const
Definition at line 1019 of file MachinePipeliner.cpp.
References llvm::is_contained(), IsAllIdentified, llvm::Other, SUnitWithMemInfo(), and UnderlyingObjs.
isUnknown()
bool false::SUnitWithMemInfo::isUnknown () const inline
Definition at line 267 of file MachinePipeliner.cpp.
References MemOpValue.
Member Data Documentation
AATags
AAMDNodes false::SUnitWithMemInfo::AATags
Definition at line 258 of file MachinePipeliner.cpp.
IsAllIdentified
bool false::SUnitWithMemInfo::IsAllIdentified = false
True if all the underlying objects are identified.
Definition at line 261 of file MachinePipeliner.cpp.
Referenced by isTriviallyDisjoint(), and SUnitWithMemInfo().
MemOpOffset
int64_t false::SUnitWithMemInfo::MemOpOffset = 0
The offset of a memory operand.
Definition at line 256 of file MachinePipeliner.cpp.
MemOpValue
const Value* false::SUnitWithMemInfo::MemOpValue = nullptr
The value of a memory operand.
Definition at line 253 of file MachinePipeliner.cpp.
Referenced by isUnknown().
SU
SUnit* false::SUnitWithMemInfo::SU
Definition at line 249 of file MachinePipeliner.cpp.
Referenced by SUnitWithMemInfo().
UnderlyingObjs
SmallVector<const Value *, 2> false::SUnitWithMemInfo::UnderlyingObjs
Definition at line 250 of file MachinePipeliner.cpp.
Referenced by isTriviallyDisjoint(), and SUnitWithMemInfo().
The documentation for this struct was generated from the following file:
lib/CodeGen/MachinePipeliner.cpp