LLVM: llvm::DXContainerYAML::RootSignatureYamlDesc Struct Reference
llvm::DXContainerYAML::RootSignatureYamlDesc Struct Reference
#include "llvm/ObjectYAML/DXContainerYAML.h"
Public Member Functions
RootSignatureYamlDesc ()=default
LLVM_ABI uint32_t getEncodedFlags ()
iterator_range< StaticSamplerYamlDesc * > samplers ()
Static Public Member Functions
static LLVM_ABI llvm::Expected< DXContainerYAML::RootSignatureYamlDesc > create (const object::DirectX::RootSignature &Data)
Public Attributes
uint32_t Version
uint32_t NumRootParameters
std::optional< uint32_t > RootParametersOffset
uint32_t NumStaticSamplers
std::optional< uint32_t > StaticSamplersOffset
RootParameterYamlDesc Parameters
SmallVector< StaticSamplerYamlDesc > StaticSamplers
Detailed Description
Definition at line 188 of file DXContainerYAML.h.
Constructor & Destructor Documentation
RootSignatureYamlDesc()
llvm::DXContainerYAML::RootSignatureYamlDesc::RootSignatureYamlDesc () default
Referenced by create().
Member Function Documentation
create()
llvm::Expected< DXContainerYAML::RootSignatureYamlDesc > llvm::DXContainerYAML::RootSignatureYamlDesc::create (const object::DirectX::RootSignature & Data) static
Definition at line 81 of file DXContainerYAML.cpp.
References llvm::DXContainerYAML::StaticSamplerYamlDesc::AddressU, llvm::DXContainerYAML::StaticSamplerYamlDesc::AddressV, llvm::DXContainerYAML::StaticSamplerYamlDesc::AddressW, llvm::DXContainerYAML::StaticSamplerYamlDesc::BorderColor, llvm::DXContainerYAML::StaticSamplerYamlDesc::ComparisonFunc, llvm::createStringError(), llvm::Data, llvm::dyn_cast(), E(), llvm::DXContainerYAML::StaticSamplerYamlDesc::Filter, llvm::Expected< T >::get(), llvm::DXContainerYAML::RootParameterYamlDesc::getOrInsertConstants(), llvm::DXContainerYAML::RootParameterYamlDesc::getOrInsertDescriptor(), llvm::DXContainerYAML::RootParameterYamlDesc::insertLocation(), llvm::dxbc::isValidAddress(), llvm::dxbc::isValidBorderColor(), llvm::dxbc::isValidComparisonFunc(), llvm::dxbc::isValidParameterType(), llvm::dxbc::isValidSamplerFilter(), llvm::dxbc::isValidShaderVisibility(), llvm_unreachable, llvm::DXContainerYAML::StaticSamplerYamlDesc::MaxAnisotropy, llvm::DXContainerYAML::StaticSamplerYamlDesc::MaxLOD, llvm::DXContainerYAML::StaticSamplerYamlDesc::MinLOD, llvm::DXContainerYAML::StaticSamplerYamlDesc::MipLODBias, llvm::DXContainerYAML::RootConstantsYaml::Num32BitValues, NumRootParameters, NumStaticSamplers, Parameters, llvm::readDescriptorRanges(), llvm::DXContainerYAML::RootConstantsYaml::RegisterSpace, llvm::DXContainerYAML::RootDescriptorYaml::RegisterSpace, llvm::DXContainerYAML::StaticSamplerYamlDesc::RegisterSpace, RootParametersOffset, RootSignatureYamlDesc(), llvm::DXContainerYAML::RootConstantsYaml::ShaderRegister, llvm::DXContainerYAML::RootDescriptorYaml::ShaderRegister, llvm::DXContainerYAML::StaticSamplerYamlDesc::ShaderRegister, llvm::DXContainerYAML::StaticSamplerYamlDesc::ShaderVisibility, StaticSamplers, StaticSamplersOffset, llvm::Expected< T >::takeError(), and Version.
getEncodedFlags()
uint32_t llvm::DXContainerYAML::RootSignatureYamlDesc::getEncodedFlags ()
Definition at line 235 of file DXContainerYAML.cpp.
samplers()
iterator_range< StaticSamplerYamlDesc * > llvm::DXContainerYAML::RootSignatureYamlDesc::samplers () inline
Definition at line 202 of file DXContainerYAML.h.
References llvm::make_range(), and StaticSamplers.
Member Data Documentation
NumRootParameters
uint32_t llvm::DXContainerYAML::RootSignatureYamlDesc::NumRootParameters
Definition at line 192 of file DXContainerYAML.h.
Referenced by create(), and llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping().
NumStaticSamplers
uint32_t llvm::DXContainerYAML::RootSignatureYamlDesc::NumStaticSamplers
Definition at line 194 of file DXContainerYAML.h.
Referenced by create(), and llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping().
Parameters
RootParameterYamlDesc llvm::DXContainerYAML::RootSignatureYamlDesc::Parameters
Definition at line 197 of file DXContainerYAML.h.
Referenced by create(), llvm::yaml::MappingContextTraits< DXContainerYAML::RootParameterLocationYaml, DXContainerYAML::RootSignatureYamlDesc >::mapping(), llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping(), and llvm::readDescriptorRanges().
RootParametersOffset
std::optional<uint32_t> llvm::DXContainerYAML::RootSignatureYamlDesc::RootParametersOffset
Definition at line 193 of file DXContainerYAML.h.
Referenced by create(), and llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping().
StaticSamplers
SmallVector<StaticSamplerYamlDesc> llvm::DXContainerYAML::RootSignatureYamlDesc::StaticSamplers
Definition at line 198 of file DXContainerYAML.h.
Referenced by create(), llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping(), and samplers().
StaticSamplersOffset
std::optional<uint32_t> llvm::DXContainerYAML::RootSignatureYamlDesc::StaticSamplersOffset
Definition at line 195 of file DXContainerYAML.h.
Referenced by create(), and llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping().
Version
uint32_t llvm::DXContainerYAML::RootSignatureYamlDesc::Version
Definition at line 191 of file DXContainerYAML.h.
Referenced by create(), and llvm::yaml::MappingTraits< DXContainerYAML::RootSignatureYamlDesc >::mapping().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/DXContainerYAML.h
lib/ObjectYAML/DXContainerYAML.cpp