LLVM: llvm::DenseMapInfo< DIExpression::FragmentInfo > Struct Reference
llvm::DenseMapInfo< DIExpression::FragmentInfo > Struct Reference
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
using FragInfo = DIExpression::FragmentInfo
Static Public Member Functions
static FragInfo getEmptyKey ()
static FragInfo getTombstoneKey ()
static unsigned getHashValue (const FragInfo &Frag)
static bool isEqual (const FragInfo &A, const FragInfo &B)
Static Public Attributes
static const uint64_t MaxVal = std::numeric_limits<uint64_t>::max()
Detailed Description
Definition at line 3872 of file DebugInfoMetadata.h.
Member Typedef Documentation
FragInfo
using llvm::DenseMapInfo< DIExpression::FragmentInfo >::FragInfo = DIExpression::FragmentInfo
Definition at line 3873 of file DebugInfoMetadata.h.
Member Function Documentation
getEmptyKey()
FragInfo llvm::DenseMapInfo< DIExpression::FragmentInfo >::getEmptyKey () inline static
Definition at line 3876 of file DebugInfoMetadata.h.
References MaxVal.
getHashValue()
unsigned llvm::DenseMapInfo< DIExpression::FragmentInfo >::getHashValue (const FragInfo & Frag) inline static
Definition at line 3880 of file DebugInfoMetadata.h.
References llvm::DbgVariableFragmentInfo::OffsetInBits, and llvm::DbgVariableFragmentInfo::SizeInBits.
getTombstoneKey()
FragInfo llvm::DenseMapInfo< DIExpression::FragmentInfo >::getTombstoneKey () inline static
Definition at line 3878 of file DebugInfoMetadata.h.
References MaxVal.
isEqual()
bool llvm::DenseMapInfo< DIExpression::FragmentInfo >::isEqual (const FragInfo & A, const FragInfo & B) inline static
Definition at line 3884 of file DebugInfoMetadata.h.
References A(), and B().
Member Data Documentation
MaxVal
const uint64_t llvm::DenseMapInfo< DIExpression::FragmentInfo >::MaxVal = std::numeric_limits<uint64_t>::max() static
Definition at line 3874 of file DebugInfoMetadata.h.
Referenced by getEmptyKey(), and getTombstoneKey().
The documentation for this struct was generated from the following file:
include/llvm/IR/DebugInfoMetadata.h