LLVM: llvm::yaml::MappingTraits< MachineFunction > Struct Reference
llvm::yaml::MappingTraits< MachineFunction > Struct Reference
#include "llvm/CodeGen/MIRYamlMapping.h"
Static Public Member Functions
static void mapping (IO &YamlIO, MachineFunction &MF)
Detailed Description
Definition at line 837 of file MIRYamlMapping.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< MachineFunction >::mapping (IO & YamlIO, MachineFunction & MF) inline static
Definition at line 838 of file MIRYamlMapping.h.
References llvm::yaml::MachineFunction::Alignment, llvm::yaml::MachineFunction::Body, llvm::yaml::MachineFunction::CalledGlobals, llvm::yaml::MachineFunction::CalleeSavedRegisters, llvm::yaml::MachineFunction::CallsEHReturn, llvm::yaml::MachineFunction::CallSitesInfo, llvm::yaml::MachineFunction::CallsUnwindInit, llvm::yaml::MachineFunction::Constants, llvm::yaml::MachineFunction::DebugValueSubstitutions, llvm::yaml::MachineJumpTable::Entries, llvm::yaml::MachineFunction::EntryValueObjects, llvm::yaml::MachineFunction::ExposesReturnsTwice, llvm::yaml::MachineFunction::FailedISel, llvm::yaml::MachineFunction::FailsVerification, llvm::yaml::MachineFunction::FixedStackObjects, llvm::yaml::MachineFunction::FrameInfo, llvm::yaml::MachineFunction::HasEHContTarget, llvm::yaml::MachineFunction::HasEHFunclets, llvm::yaml::MachineFunction::HasEHScopes, llvm::yaml::MachineFunction::HasFakeUses, llvm::yaml::MachineFunction::HasWinCFI, llvm::yaml::MachineFunction::IsOutlined, llvm::yaml::MachineFunction::IsSSA, llvm::yaml::MachineFunction::JumpTableInfo, llvm::yaml::MachineFunction::Legalized, llvm::yaml::MachineFunction::LiveIns, llvm::yaml::MachineFunction::MachineFuncInfo, llvm::yaml::MachineFunction::MachineMetadataNodes, llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), llvm::yaml::MachineFunction::Name, llvm::yaml::MachineFunction::NoPHIs, llvm::yaml::MachineFunction::NoVRegs, llvm::yaml::IO::outputting(), llvm::yaml::MachineFunction::RegBankSelected, llvm::yaml::MachineFunction::Selected, llvm::yaml::MachineFunction::StackObjects, llvm::yaml::MachineFunction::TracksDebugUserValues, llvm::yaml::MachineFunction::TracksRegLiveness, llvm::yaml::MachineFunction::UseDebugInstrRef, and llvm::yaml::MachineFunction::VirtualRegisters.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MIRYamlMapping.h