LLVM: llvm::EpilogueLoopVectorizationInfo Struct Reference
llvm::EpilogueLoopVectorizationInfo Struct Reference
Encapsulate information regarding vectorization of a loop and its epilogue.
Public Member Functions
EpilogueLoopVectorizationInfo (ElementCount MVF, unsigned MUF, ElementCount EVF, unsigned EUF, VPlan &EpiloguePlan)
Public Attributes
ElementCount MainLoopVF = ElementCount::getFixed(0)
unsigned MainLoopUF = 0
ElementCount EpilogueVF = ElementCount::getFixed(0)
unsigned EpilogueUF = 0
BasicBlock * MainLoopIterationCountCheck = nullptr
BasicBlock * EpilogueIterationCountCheck = nullptr
Value * TripCount = nullptr
Value * VectorTripCount = nullptr
VPlan & EpiloguePlan
Detailed Description
Encapsulate information regarding vectorization of a loop and its epilogue.
This information is meant to be updated and used across two stages of epilogue vectorization.
Definition at line 600 of file LoopVectorize.cpp.
Constructor & Destructor Documentation
EpilogueLoopVectorizationInfo()
llvm::EpilogueLoopVectorizationInfo::EpilogueLoopVectorizationInfo (ElementCount MVF, unsigned MUF, ElementCount EVF, unsigned EUF, VPlan & EpiloguePlan) inline
Definition at line 611 of file LoopVectorize.cpp.
References assert(), EpiloguePlan, EpilogueUF, EpilogueVF, MainLoopUF, and MainLoopVF.
Member Data Documentation
EpilogueIterationCountCheck
BasicBlock* llvm::EpilogueLoopVectorizationInfo::EpilogueIterationCountCheck = nullptr
Definition at line 606 of file LoopVectorize.cpp.
Referenced by connectEpilogueVectorLoop().
EpiloguePlan
VPlan& llvm::EpilogueLoopVectorizationInfo::EpiloguePlan
Definition at line 609 of file LoopVectorize.cpp.
Referenced by EpilogueLoopVectorizationInfo().
EpilogueUF
unsigned llvm::EpilogueLoopVectorizationInfo::EpilogueUF = 0
Definition at line 604 of file LoopVectorize.cpp.
Referenced by EpilogueLoopVectorizationInfo(), preparePlanForEpilogueVectorLoop(), and llvm::LoopVectorizePass::processLoop().
EpilogueVF
ElementCount llvm::EpilogueLoopVectorizationInfo::EpilogueVF = ElementCount::getFixed(0)
Definition at line 603 of file LoopVectorize.cpp.
Referenced by EpilogueLoopVectorizationInfo(), preparePlanForEpilogueVectorLoop(), and llvm::LoopVectorizePass::processLoop().
MainLoopIterationCountCheck
BasicBlock* llvm::EpilogueLoopVectorizationInfo::MainLoopIterationCountCheck = nullptr
Definition at line 605 of file LoopVectorize.cpp.
Referenced by connectEpilogueVectorLoop(), and preparePlanForEpilogueVectorLoop().
MainLoopUF
unsigned llvm::EpilogueLoopVectorizationInfo::MainLoopUF = 0
Definition at line 602 of file LoopVectorize.cpp.
Referenced by EpilogueLoopVectorizationInfo(), preparePlanForEpilogueVectorLoop(), and llvm::LoopVectorizePass::processLoop().
MainLoopVF
ElementCount llvm::EpilogueLoopVectorizationInfo::MainLoopVF = ElementCount::getFixed(0)
Definition at line 601 of file LoopVectorize.cpp.
Referenced by EpilogueLoopVectorizationInfo(), preparePlanForEpilogueVectorLoop(), and llvm::LoopVectorizePass::processLoop().
TripCount
Value* llvm::EpilogueLoopVectorizationInfo::TripCount = nullptr
Definition at line 607 of file LoopVectorize.cpp.
Referenced by preparePlanForEpilogueVectorLoop().
VectorTripCount
Value* llvm::EpilogueLoopVectorizationInfo::VectorTripCount = nullptr
Definition at line 608 of file LoopVectorize.cpp.
Referenced by connectEpilogueVectorLoop(), and preparePlanForEpilogueVectorLoop().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/LoopVectorize.cpp