LLVM: llvm::VarStreamArrayExtractor< T > Struct Template Reference
llvm::VarStreamArrayExtractor< T > Struct Template Reference
VarStreamArrayExtractor is intended to be specialized to provide customized extraction logic.
#include "llvm/Support/BinaryStreamArray.h"
Public Member Functions
Error operator() (BinaryStreamRef Stream, uint32_t &Len, T &Item) const =delete
Detailed Description
template<typename T>
struct llvm::VarStreamArrayExtractor< T >
VarStreamArrayExtractor is intended to be specialized to provide customized extraction logic.
On input it receives a BinaryStreamRef pointing to the beginning of the next record, but where the length of the record is not yet known. Upon completion, it should return an appropriate Error instance if a record could not be extracted, or if one could be extracted it should return success and set Len to the number of bytes this record occupied in the underlying stream, and it should fill out the fields of the value type Item appropriately to represent the current record.
You can specialize this template for your own custom value types to avoid having to specify a second template argument to VarStreamArray (documented below).
Definition at line 47 of file BinaryStreamArray.h.
Member Function Documentation
operator()()
template<typename T> Error VarStreamArrayExtractor::operator() (BinaryStreamRef Stream, uint32_t & Len, T & Item) const delete
Definition at line 34 of file DebugChecksumsSubsection.cpp.
References llvm::alignTo(), llvm::codeview::FileChecksumEntry::Checksum, llvm::codeview::EC, llvm::codeview::FileChecksumEntry::FileNameOffset, llvm::codeview::FileChecksumEntry::Kind, llvm::BinaryStreamReader::readBytes(), llvm::BinaryStreamReader::readObject(), and llvm::Error::success().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/PDB/Native/DbiModuleDescriptor.h
include/llvm/Support/BinaryStreamArray.h
lib/DebugInfo/CodeView/DebugChecksumsSubsection.cpp
lib/DebugInfo/CodeView/DebugCrossImpSubsection.cpp
lib/DebugInfo/CodeView/DebugInlineeLinesSubsection.cpp