LLVM: llvm::PGOCtxProfile Struct Reference
llvm::PGOCtxProfile Struct Reference
#include "llvm/ProfileData/PGOCtxProfReader.h"
Public Member Functions
PGOCtxProfile ()=default
PGOCtxProfile (const PGOCtxProfile &)=delete
PGOCtxProfile (PGOCtxProfile &&)=default
PGOCtxProfile & operator= (PGOCtxProfile &&)=default
Public Attributes
CtxProfContextualProfiles Contexts
CtxProfFlatProfile FlatProfiles
Detailed Description
Definition at line 189 of file PGOCtxProfReader.h.
Constructor & Destructor Documentation
PGOCtxProfile() [1/3]
llvm::PGOCtxProfile::PGOCtxProfile () default
Referenced by operator=(), PGOCtxProfile(), and PGOCtxProfile().
PGOCtxProfile() [2/3]
llvm::PGOCtxProfile::PGOCtxProfile (const PGOCtxProfile &) delete
References PGOCtxProfile().
PGOCtxProfile() [3/3]
llvm::PGOCtxProfile::PGOCtxProfile (PGOCtxProfile &&) default
References PGOCtxProfile().
Member Function Documentation
operator=()
PGOCtxProfile & llvm::PGOCtxProfile::operator= (PGOCtxProfile &&) default
References PGOCtxProfile().
Member Data Documentation
Contexts
CtxProfContextualProfiles llvm::PGOCtxProfile::Contexts
Definition at line 190 of file PGOCtxProfReader.h.
Referenced by llvm::PGOCtxProfileReader::loadProfiles().
FlatProfiles
CtxProfFlatProfile llvm::PGOCtxProfile::FlatProfiles
Definition at line 191 of file PGOCtxProfReader.h.
Referenced by llvm::PGOCtxProfileReader::loadProfiles().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/PGOCtxProfReader.h