LLVM: SameSignRange Struct Reference
SameSignRange Struct Reference
Represent a contiguous range of values sharing the same sign.
Public Member Functions
SameSignRange (const APFloat &Lower, const APFloat &Upper)
Public Attributes
bool HasZero
bool HasNonZero
bool HasInf
std::optional< std::pair< APFloat, APFloat > > FinitePart
Detailed Description
Represent a contiguous range of values sharing the same sign.
Definition at line 533 of file ConstantFPRange.cpp.
Constructor & Destructor Documentation
SameSignRange()
SameSignRange::SameSignRange (const APFloat & Lower, const APFloat & Upper) inline explicit
Definition at line 541 of file ConstantFPRange.cpp.
References assert(), llvm::APFloatBase::cmpGreaterThan, FinitePart, llvm::APFloat::getLargest(), HasInf, HasNonZero, HasZero, isZero(), llvm::Lower, strictCompare(), and llvm::Upper.
Member Data Documentation
FinitePart
std::optional<std::pair<APFloat, APFloat> > SameSignRange::FinitePart
Definition at line 539 of file ConstantFPRange.cpp.
Referenced by SameSignRange().
HasInf
bool SameSignRange::HasInf
Definition at line 536 of file ConstantFPRange.cpp.
Referenced by SameSignRange().
HasNonZero
bool SameSignRange::HasNonZero
Definition at line 535 of file ConstantFPRange.cpp.
Referenced by SameSignRange().
HasZero
bool SameSignRange::HasZero
Definition at line 534 of file ConstantFPRange.cpp.
Referenced by SameSignRange().
The documentation for this struct was generated from the following file:
lib/IR/ConstantFPRange.cpp