LLVM: llvm::VPIRValue Struct Reference
llvm::VPIRValue Struct Reference
A VPValue representing a live-in from the input IR or a constant.
#include "Transforms/Vectorize/VPlanValue.h"
Public Member Functions
VPIRValue (Value *UV)
Value * getValue () const
Returns the underlying IR value.
Type * getType () const
Returns the type of the underlying IR value.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
Value * getLiveInIRValue () const
Return the underlying IR value for a VPIRValue.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser () const
Returns true if the value has more than one unique user.
bool hasOneUse () const
VPUser * getSingleUser ()
Return the single user of this value, or nullptr if there is not exactly one user.
const VPUser * getSingleUser () const
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isDefinedOutsideLoopRegions () const
Returns true if the VPValue is defined outside any loop.
void setUnderlyingValue (Value *Val)
Static Public Member Functions
static bool classof (const VPValue *V)
Additional Inherited Members
Public Types inherited from llvm::VPValue
enum { VPVIRValueSC , VPVSymbolicSC , VPVRecipeValueSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Detailed Description
A VPValue representing a live-in from the input IR or a constant.
It wraps an underlying IR Value.
Definition at line 184 of file VPlanValue.h.
Constructor & Destructor Documentation
VPIRValue()
llvm::VPIRValue::VPIRValue (Value * UV) inline
Definition at line 185 of file VPlanValue.h.
References assert(), and llvm::VPValue::VPVIRValueSC.
Member Function Documentation
classof()
bool llvm::VPIRValue::classof (const VPValue * V) inline static
Definition at line 195 of file VPlanValue.h.
References llvm::VPValue::VPVIRValueSC.
getType()
Type * VPIRValue::getType () const
Returns the type of the underlying IR value.
Definition at line 137 of file VPlan.cpp.
References llvm::Value::getType(), and llvm::VPValue::getUnderlyingValue().
Referenced by llvm::VPCanonicalIVPHIRecipe::getScalarType(), llvm::VPDerivedIVRecipe::getScalarType(), llvm::VPWidenIntOrFpInductionRecipe::getScalarType(), and llvm::VPlanTransforms::replaceSymbolicStrides().
getValue()
Value * llvm::VPIRValue::getValue () const inline
Returns the underlying IR value.
Definition at line 190 of file VPlanValue.h.
References llvm::VPValue::getUnderlyingValue().
Referenced by llvm::VPWidenIntOrFpInductionRecipe::isCanonical().
The documentation for this struct was generated from the following files:
lib/Transforms/Vectorize/VPlanValue.h
lib/Transforms/Vectorize/VPlan.cpp