LLVM: llvm::cgdata::StreamCacheData Struct Reference
llvm::cgdata::StreamCacheData Struct Reference
#include "llvm/CGData/CodeGenData.h"
Public Member Functions
StreamCacheData (unsigned Size, const FileCache &OrigCache, const Twine &CachePrefix)
StreamCacheData ()=delete
std::unique_ptr< SmallVector< StringRef > > getResult ()
Retrieve results from either the cache or the stream.
Public Attributes
SmallVector< SmallString< 0 > > Outputs
Backing buffer for serialized data stream.
AddStreamFn AddStream
Callback function to add serialized data to the stream.
SmallVector< std::unique_ptr< MemoryBuffer > > Files
Backing buffer for cached data.
FileCache Cache
Cache mechanism for storing data.
Detailed Description
Definition at line 200 of file CodeGenData.h.
Constructor & Destructor Documentation
StreamCacheData() [1/2]
llvm::cgdata::StreamCacheData::StreamCacheData (unsigned Size, const FileCache & OrigCache, const Twine & CachePrefix) inline
Definition at line 210 of file CodeGenData.h.
References AddStream, Cache, Files, if(), llvm::FileCache::isValid(), Outputs, and llvm::report_fatal_error().
StreamCacheData() [2/2]
llvm::cgdata::StreamCacheData::StreamCacheData () delete
Member Function Documentation
getResult()
std::unique_ptr< SmallVector< StringRef > > llvm::cgdata::StreamCacheData::getResult () inline
Retrieve results from either the cache or the stream.
Definition at line 233 of file CodeGenData.h.
References Files, I, and Outputs.
Member Data Documentation
AddStream
AddStreamFn llvm::cgdata::StreamCacheData::AddStream
Callback function to add serialized data to the stream.
Definition at line 204 of file CodeGenData.h.
Referenced by StreamCacheData().
Cache
FileCache llvm::cgdata::StreamCacheData::Cache
Cache mechanism for storing data.
Definition at line 208 of file CodeGenData.h.
Referenced by StreamCacheData().
Files
SmallVector<std::unique_ptr<MemoryBuffer> > llvm::cgdata::StreamCacheData::Files
Backing buffer for cached data.
Definition at line 206 of file CodeGenData.h.
Referenced by getResult(), and StreamCacheData().
Outputs
SmallVector<SmallString<0> > llvm::cgdata::StreamCacheData::Outputs
Backing buffer for serialized data stream.
Definition at line 202 of file CodeGenData.h.
Referenced by getResult(), and StreamCacheData().
The documentation for this struct was generated from the following file:
include/llvm/CGData/CodeGenData.h