LLVM: llvm::DIFile::ChecksumInfo< T > Struct Template Reference
llvm::DIFile::ChecksumInfo< T > Struct Template Reference
A single checksum, represented by a Kind and a Value (a string).
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
ChecksumInfo (ChecksumKind Kind, T Value)
~ChecksumInfo ()=default
bool operator== (const ChecksumInfo< T > &X) const
bool operator!= (const ChecksumInfo< T > &X) const
StringRef getKindAsString () const
Public Attributes
ChecksumKind Kind
The kind of checksum which Value encodes.
T Value
The string value of the checksum.
Detailed Description
template<typename T>
struct llvm::DIFile::ChecksumInfo< T >
A single checksum, represented by a Kind and a Value (a string).
Definition at line 648 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
ChecksumInfo()
template<typename T> llvm::DIFile::ChecksumInfo< T >::ChecksumInfo (ChecksumKind Kind, T Value) inline
Definition at line 654 of file DebugInfoMetadata.h.
References Kind, T, and Value.
Referenced by operator!=(), and operator==().
~ChecksumInfo()
template<typename T> llvm::DIFile::ChecksumInfo< T >::~ChecksumInfo () default
Member Function Documentation
getKindAsString()
template<typename T> StringRef llvm::DIFile::ChecksumInfo< T >::getKindAsString () const inline
Definition at line 660 of file DebugInfoMetadata.h.
References Kind.
operator!=()
template<typename T> bool llvm::DIFile::ChecksumInfo< T >::operator!= (const ChecksumInfo< T > & X) const inline
Definition at line 659 of file DebugInfoMetadata.h.
References ChecksumInfo(), and X.
operator==()
template<typename T> bool llvm::DIFile::ChecksumInfo< T >::operator== (const ChecksumInfo< T > & X) const inline
Definition at line 656 of file DebugInfoMetadata.h.
References ChecksumInfo(), Kind, Value, and X.
Member Data Documentation
Kind
template<typename T> ChecksumKind llvm::DIFile::ChecksumInfo< T >::Kind
The kind of checksum which Value encodes.
Definition at line 650 of file DebugInfoMetadata.h.
Referenced by ChecksumInfo(), getKindAsString(), and operator==().
Value
template<typename T> T llvm::DIFile::ChecksumInfo< T >::Value
The string value of the checksum.
Definition at line 652 of file DebugInfoMetadata.h.
Referenced by ChecksumInfo(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/IR/DebugInfoMetadata.h