LLVM: llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * > Struct Template Reference
llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * > Struct Template Reference
#include "Target/X86/ImmutableGraph.h"
Public Types
using GraphT = ImmutableGraph<NodeValueT, EdgeValueT>
using NodeRef = typename GraphT::Node const *
using EdgeRef = typename GraphT::Edge const &
using ChildIteratorType
using nodes_iterator
using ChildEdgeIteratorType = typename GraphT::Edge const *
Static Public Member Functions
static NodeRef edge_dest (EdgeRef E)
static NodeRef getEntryNode (GraphT *G)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static NodeRef getNode (typename GraphT::Node const &N)
static nodes_iterator nodes_begin (GraphT *G)
static nodes_iterator nodes_end (GraphT *G)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
static GraphT::size_type size (GraphT *G)
Detailed Description
template<typename NodeValueT, typename EdgeValueT>
struct llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >
Definition at line 405 of file ImmutableGraph.h.
Member Typedef Documentation
ChildEdgeIteratorType
template<typename NodeValueT, typename EdgeValueT> using llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::ChildEdgeIteratorType = typename GraphT::Edge const *
Definition at line 432 of file ImmutableGraph.h.
ChildIteratorType
template<typename NodeValueT, typename EdgeValueT> using llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::ChildIteratorType
Initial value:
mapped_iterator<typename GraphT::Edge const *, decltype(&edge_dest)>
Definition at line 411 of file ImmutableGraph.h.
EdgeRef
template<typename NodeValueT, typename EdgeValueT> using llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::EdgeRef = typename GraphT::Edge const &
Definition at line 408 of file ImmutableGraph.h.
GraphT
template<typename NodeValueT, typename EdgeValueT> using llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::GraphT = ImmutableGraph<NodeValueT, EdgeValueT>
Definition at line 406 of file ImmutableGraph.h.
NodeRef
template<typename NodeValueT, typename EdgeValueT> using llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::NodeRef = typename GraphT::Node const *
Definition at line 407 of file ImmutableGraph.h.
nodes_iterator
template<typename NodeValueT, typename EdgeValueT> using llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::nodes_iterator
Initial value:
mapped_iterator<typename GraphT::Node const *, decltype(&getNode)>
Definition at line 423 of file ImmutableGraph.h.
Member Function Documentation
child_begin()
template<typename NodeValueT, typename EdgeValueT> ChildIteratorType llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::child_begin (NodeRef N) inline static
Definition at line 415 of file ImmutableGraph.h.
References edge_dest(), and N.
child_edge_begin()
template<typename NodeValueT, typename EdgeValueT> ChildEdgeIteratorType llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::child_edge_begin (NodeRef N) inline static
Definition at line 434 of file ImmutableGraph.h.
References N.
child_edge_end()
template<typename NodeValueT, typename EdgeValueT> ChildEdgeIteratorType llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::child_edge_end (NodeRef N) inline static
Definition at line 437 of file ImmutableGraph.h.
References N.
child_end()
template<typename NodeValueT, typename EdgeValueT> ChildIteratorType llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::child_end (NodeRef N) inline static
Definition at line 418 of file ImmutableGraph.h.
References edge_dest(), and N.
edge_dest()
template<typename NodeValueT, typename EdgeValueT> NodeRef llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::edge_dest (EdgeRef E) inline static
Definition at line 410 of file ImmutableGraph.h.
References E().
Referenced by child_begin(), and child_end().
getEntryNode()
template<typename NodeValueT, typename EdgeValueT> NodeRef llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::getEntryNode (GraphT * G) inline static
Definition at line 414 of file ImmutableGraph.h.
References G.
getNode()
template<typename NodeValueT, typename EdgeValueT> NodeRef llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::getNode (typename GraphT::Node const & N) inline static
Definition at line 422 of file ImmutableGraph.h.
References N.
Referenced by nodes_begin(), and nodes_end().
nodes_begin()
template<typename NodeValueT, typename EdgeValueT> nodes_iterator llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::nodes_begin (GraphT * G) inline static
Definition at line 425 of file ImmutableGraph.h.
References G, and getNode().
nodes_end()
template<typename NodeValueT, typename EdgeValueT> nodes_iterator llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::nodes_end (GraphT * G) inline static
Definition at line 428 of file ImmutableGraph.h.
References G, and getNode().
size()
template<typename NodeValueT, typename EdgeValueT> GraphT::size_type llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::size (GraphT * G) inline static
Definition at line 440 of file ImmutableGraph.h.
References G.
The documentation for this struct was generated from the following file:
lib/Target/X86/ImmutableGraph.h