LLVM: llvm::yaml::MappingTraits< Kernel::Metadata > Struct Reference
llvm::yaml::MappingTraits< Kernel::Metadata > Struct Reference
Static Public Member Functions
static void mapping (IO &YIO, Kernel::Metadata &MD)
Detailed Description
Definition at line 181 of file AMDGPUMetadata.cpp.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< Kernel::Metadata >::mapping (IO & YIO, Kernel::Metadata & MD) inline static
Definition at line 182 of file AMDGPUMetadata.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::AMDGPU::HSAMD::Kernel::Key::CodeProps, llvm::AMDGPU::HSAMD::Kernel::Key::DebugProps, llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::empty(), llvm::AMDGPU::HSAMD::Kernel::CodeProps::Metadata::empty(), llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::empty(), llvm::AMDGPU::HSAMD::Kernel::Key::Language, llvm::AMDGPU::HSAMD::Kernel::Key::LanguageVersion, llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), llvm::AMDGPU::HSAMD::Kernel::Metadata::mArgs, llvm::AMDGPU::HSAMD::Kernel::Metadata::mAttrs, llvm::AMDGPU::HSAMD::Kernel::Metadata::mCodeProps, llvm::AMDGPU::HSAMD::Kernel::Metadata::mDebugProps, llvm::AMDGPU::HSAMD::Kernel::Metadata::mLanguage, llvm::AMDGPU::HSAMD::Kernel::Metadata::mLanguageVersion, llvm::AMDGPU::HSAMD::Kernel::Metadata::mName, llvm::AMDGPU::HSAMD::Kernel::Metadata::mSymbolName, llvm::AMDGPU::HSAMD::Kernel::Key::Name, llvm::yaml::IO::outputting(), and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
The documentation for this struct was generated from the following file:
lib/Support/AMDGPUMetadata.cpp