LLVM: llvm::PatternMatch::Signum_match< Opnd_t > Struct Template Reference
llvm::PatternMatch::Signum_match< Opnd_t > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
Signum_match (const Opnd_t &V)
template<typename OpTy>
bool match (OpTy *V) const
Public Attributes
Opnd_t Val
Detailed Description
template<typename Opnd_t>
struct llvm::PatternMatch::Signum_match< Opnd_t >
Definition at line 3122 of file PatternMatch.h.
Constructor & Destructor Documentation
Signum_match()
template<typename Opnd_t> llvm::PatternMatch::Signum_match< Opnd_t >::Signum_match (const Opnd_t & V) inline
Definition at line 3124 of file PatternMatch.h.
References Val.
Member Function Documentation
match()
template<typename Opnd_t> template<typename OpTy> bool llvm::PatternMatch::Signum_match< Opnd_t >::match (OpTy * V) const inline
Definition at line 3126 of file PatternMatch.h.
References LHS, llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Deferred(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), RHS, and Val.
Member Data Documentation
Val
template<typename Opnd_t> Opnd_t llvm::PatternMatch::Signum_match< Opnd_t >::Val
Definition at line 3123 of file PatternMatch.h.
Referenced by match(), and Signum_match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h