LLVM: llvm::dxbc::RTS0::v3::StaticSampler Struct Reference
llvm::dxbc::RTS0::v3::StaticSampler Struct Reference
#include "llvm/BinaryFormat/DXContainer.h"
Public Member Functions
StaticSampler ()=default
StaticSampler (v1::StaticSampler &Base)
void swapBytes ()
Public Member Functions inherited from llvm::dxbc::RTS0::v1::StaticSampler
void swapBytes ()
Public Attributes
uint32_t Flags
Public Attributes inherited from llvm::dxbc::RTS0::v1::StaticSampler
uint32_t Filter
uint32_t AddressU
uint32_t AddressV
uint32_t AddressW
float MipLODBias
uint32_t MaxAnisotropy
uint32_t ComparisonFunc
uint32_t BorderColor
float MinLOD
float MaxLOD
uint32_t ShaderRegister
uint32_t RegisterSpace
uint32_t ShaderVisibility
Detailed Description
Definition at line 783 of file DXContainer.h.
Constructor & Destructor Documentation
StaticSampler() [1/2]
llvm::dxbc::RTS0::v3::StaticSampler::StaticSampler () default
Referenced by StaticSampler().
StaticSampler() [2/2]
llvm::dxbc::RTS0::v3::StaticSampler::StaticSampler (v1::StaticSampler & Base) inline explicit
Definition at line 787 of file DXContainer.h.
References llvm::sampleprof::Base, Flags, and StaticSampler().
Member Function Documentation
swapBytes()
void llvm::dxbc::RTS0::v3::StaticSampler::swapBytes () inline
Definition at line 790 of file DXContainer.h.
References Flags, llvm::sys::swapByteOrder(), and llvm::dxbc::RTS0::v1::StaticSampler::swapBytes().
Member Data Documentation
Flags
uint32_t llvm::dxbc::RTS0::v3::StaticSampler::Flags
Definition at line 784 of file DXContainer.h.
Referenced by StaticSampler(), and swapBytes().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/DXContainer.h