LLVM: llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes > Struct Template Reference
llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes > Struct Template Reference
Cmp_match is a variant of BinaryRecipe_match that also binds the comparison predicate.
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
Cmp_match (CmpPredicate &Pred, const Op0_t &Op0, const Op1_t &Op1)
Cmp_match (const Op0_t &Op0, const Op1_t &Op1)
bool match (const VPValue *V) const
bool match (const VPRecipeBase *V) const
Public Attributes
CmpPredicate * Predicate = nullptr
Op0_t Op0
Op1_t Op1
Detailed Description
template<typename Op0_t, typename Op1_t, unsigned... Opcodes>
struct llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >
Cmp_match is a variant of BinaryRecipe_match that also binds the comparison predicate.
Opcodes must either be Instruction::ICmp or Instruction::FCmp, or both.
Definition at line 603 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
Cmp_match() [1/2]
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >::Cmp_match (CmpPredicate & Pred, const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 614 of file VPlanPatternMatch.h.
References Op0, Op1, and Predicate.
Cmp_match() [2/2]
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >::Cmp_match (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 616 of file VPlanPatternMatch.h.
References Op0, and Op1.
Member Function Documentation
match() [1/2]
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> bool llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >::match (const VPRecipeBase * V) const inline
Definition at line 623 of file VPlanPatternMatch.h.
References llvm::cast(), llvm::VPlanPatternMatch::m_Binary(), match(), Op0, Op1, and Predicate.
match() [2/2]
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> bool llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >::match (const VPValue * V) const inline
Definition at line 618 of file VPlanPatternMatch.h.
References match().
Referenced by match(), and match().
Member Data Documentation
Op0
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> Op0_t llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >::Op0
Definition at line 611 of file VPlanPatternMatch.h.
Referenced by Cmp_match(), Cmp_match(), and match().
Op1
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> Op1_t llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >::Op1
Definition at line 612 of file VPlanPatternMatch.h.
Referenced by Cmp_match(), Cmp_match(), and match().
Predicate
template<typename Op0_t, typename Op1_t, unsigned... Opcodes> CmpPredicate* llvm::VPlanPatternMatch::Cmp_match< Op0_t, Op1_t, Opcodes >::Predicate = nullptr
Definition at line 610 of file VPlanPatternMatch.h.
Referenced by Cmp_match(), and match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h