LLVM: llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true > Struct Template Reference
llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true > Struct Template Reference
Specialization of AnalysisResultModel which delegates invalidate handling to ResultT.
#include "llvm/IR/PassManagerInternal.h"
Public Member Functions
AnalysisResultModel (ResultT Result)
AnalysisResultModel (const AnalysisResultModel &Arg)
AnalysisResultModel (AnalysisResultModel &&Arg)
AnalysisResultModel & operator= (AnalysisResultModel RHS)
bool invalidate (IRUnitT &IR, const PreservedAnalyses &PA, InvalidatorT &Inv) override
The model delegates to the ResultT method.
Public Member Functions inherited from llvm::detail::AnalysisResultConcept< IRUnitT, InvalidatorT >
virtual ~AnalysisResultConcept ()=default
Public Attributes
ResultT Result
Friends
void swap (AnalysisResultModel &LHS, AnalysisResultModel &RHS)
Detailed Description
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT>
struct llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >
Specialization of AnalysisResultModel which delegates invalidate handling to ResultT.
Definition at line 233 of file PassManagerInternal.h.
Constructor & Destructor Documentation
AnalysisResultModel() [1/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::AnalysisResultModel (ResultT Result) inline explicit
Definition at line 235 of file PassManagerInternal.h.
References llvm::move(), and Result.
Referenced by AnalysisResultModel(), AnalysisResultModel(), operator=(), and swap.
AnalysisResultModel() [2/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::AnalysisResultModel (const AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true > & Arg) inline
Definition at line 238 of file PassManagerInternal.h.
References AnalysisResultModel(), and Result.
AnalysisResultModel() [3/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::AnalysisResultModel (AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true > && Arg) inline
Definition at line 239 of file PassManagerInternal.h.
References AnalysisResultModel(), llvm::move(), and Result.
Member Function Documentation
invalidate()
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT> bool llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::invalidate (IRUnitT & IR, const PreservedAnalyses & PA, InvalidatorT & Inv) inline override virtual
The model delegates to the ResultT method.
Implements llvm::detail::AnalysisResultConcept< IRUnitT, InvalidatorT >.
Definition at line 253 of file PassManagerInternal.h.
References IR, and Result.
operator=()
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT> AnalysisResultModel & llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::operator= (AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true > RHS) inline
Definition at line 247 of file PassManagerInternal.h.
References AnalysisResultModel(), RHS, and swap.
Friends And Related Symbol Documentation
swap
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT> void swap (AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true > & LHS, AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true > & RHS) friend
Definition at line 242 of file PassManagerInternal.h.
References AnalysisResultModel(), LHS, RHS, swap, and std::swap().
Referenced by operator=(), and swap.
Member Data Documentation
Result
template<typename IRUnitT, typename PassT, typename ResultT, typename InvalidatorT> ResultT llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, InvalidatorT, true >::Result
Definition at line 258 of file PassManagerInternal.h.
Referenced by AnalysisResultModel(), AnalysisResultModel(), AnalysisResultModel(), and invalidate().
The documentation for this struct was generated from the following file:
include/llvm/IR/PassManagerInternal.h