LLVM: llvm::sandboxir::Action Struct Reference
llvm::sandboxir::Action Struct Reference
#include "llvm/Transforms/Vectorize/SandboxVectorizer/InstrMaps.h"
Public Member Functions
Action (const LegalityResult *LR, ArrayRef< Value * > B, ArrayRef< Value * > UB, unsigned Depth)
void print (raw_ostream &OS) const
void dump () const
Public Attributes
unsigned Idx = 0
const LegalityResult * LegalityRes = nullptr
SmallVector< Value *, 4 > Bndl
SmallVector< Value * > UserBndl
unsigned Depth
SmallVector< Action * > Operands
Value * Vec = nullptr
Friends
raw_ostream & operator<< (raw_ostream &OS, const Action &A)
Detailed Description
Definition at line 27 of file InstrMaps.h.
Constructor & Destructor Documentation
Action()
llvm::sandboxir::Action::Action (const LegalityResult * LR, ArrayRef< Value * > B, ArrayRef< Value * > UB, unsigned Depth) inline
Definition at line 35 of file InstrMaps.h.
References B(), Bndl, Depth, LegalityRes, and UserBndl.
Referenced by operator<<.
Member Function Documentation
dump()
void llvm::sandboxir::Action::dump () const
Definition at line 26 of file InstrMaps.cpp.
References llvm::dbgs(), and print().
print()
void llvm::sandboxir::Action::print (raw_ostream & OS) const
Definition at line 16 of file InstrMaps.cpp.
References Bndl, Depth, Idx, llvm::raw_ostream::indent(), LegalityRes, and UserBndl.
Referenced by dump().
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const Action & A) friend
Definition at line 41 of file InstrMaps.h.
References A(), and Action().
Member Data Documentation
Bndl
SmallVector<Value *, 4> llvm::sandboxir::Action::Bndl
Definition at line 30 of file InstrMaps.h.
Referenced by Action(), and print().
Depth
unsigned llvm::sandboxir::Action::Depth
Definition at line 32 of file InstrMaps.h.
Referenced by Action(), and print().
Idx
unsigned llvm::sandboxir::Action::Idx = 0
Definition at line 28 of file InstrMaps.h.
Referenced by print().
LegalityRes
const LegalityResult* llvm::sandboxir::Action::LegalityRes = nullptr
Definition at line 29 of file InstrMaps.h.
Referenced by Action(), and print().
Operands
SmallVector<Action *> llvm::sandboxir::Action::Operands
Definition at line 33 of file InstrMaps.h.
UserBndl
SmallVector<Value *> llvm::sandboxir::Action::UserBndl
Definition at line 31 of file InstrMaps.h.
Referenced by Action(), and print().
Vec
Value* llvm::sandboxir::Action::Vec = nullptr
Definition at line 34 of file InstrMaps.h.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Vectorize/SandboxVectorizer/InstrMaps.h
lib/Transforms/Vectorize/SandboxVectorizer/InstrMaps.cpp