LLVM: llvm::CastInfoVPPhiAccessors< SrcTy > Struct Template Reference
llvm::CastInfoVPPhiAccessors< SrcTy > Struct Template Reference
Support casting from VPRecipeBase -> VPPhiAccessors, by down-casting to the recipe types implementing VPPhiAccessors.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using Self = CastInfo<VPPhiAccessors, SrcTy>
Static Public Member Functions
static VPPhiAccessors * doCast (SrcTy R)
doCast is used by cast<>.
static VPPhiAccessors * doCastIfPossible (SrcTy f)
doCastIfPossible is used by dyn_cast<>.
Static Public Member Functions inherited from llvm::CastIsPossible< VPPhiAccessors, SrcTy >
static bool isPossible (const SrcTy &f)
Detailed Description
template<typename SrcTy>
struct llvm::CastInfoVPPhiAccessors< SrcTy >
Support casting from VPRecipeBase -> VPPhiAccessors, by down-casting to the recipe types implementing VPPhiAccessors.
Used by cast<>, dyn_cast<> & co.
Definition at line 3844 of file VPlan.h.
Member Typedef Documentation
Self
template<typename SrcTy> using llvm::CastInfoVPPhiAccessors< SrcTy >::Self = CastInfo<VPPhiAccessors, SrcTy>
Definition at line 3846 of file VPlan.h.
Member Function Documentation
doCast()
template<typename SrcTy> VPPhiAccessors * llvm::CastInfoVPPhiAccessors< SrcTy >::doCast (SrcTy R) inline static
doCast is used by cast<>.
Definition at line 3849 of file VPlan.h.
References llvm::cast().
Referenced by doCastIfPossible().
doCastIfPossible()
template<typename SrcTy> VPPhiAccessors * llvm::CastInfoVPPhiAccessors< SrcTy >::doCastIfPossible (SrcTy f) inline static
doCastIfPossible is used by dyn_cast<>.
Definition at line 3865 of file VPlan.h.
References doCast(), and llvm::CastIsPossible< VPPhiAccessors, SrcTy >::isPossible().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h