LLVM: llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t > Struct Template Reference
llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
UAddWithOverflow_match (const LHS_t &L, const RHS_t &R, const Sum_t &S)
template<typename OpTy>
bool match (OpTy *V) const
Public Attributes
LHS_t L
RHS_t R
Sum_t S
Detailed Description
template<typename LHS_t, typename RHS_t, typename Sum_t>
struct llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >
Definition at line 2666 of file PatternMatch.h.
Constructor & Destructor Documentation
UAddWithOverflow_match()
template<typename LHS_t, typename RHS_t, typename Sum_t> llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::UAddWithOverflow_match (const LHS_t & L, const RHS_t & R, const Sum_t & S) inline
Definition at line 2671 of file PatternMatch.h.
References L, R, and S.
Member Function Documentation
match()
template<typename LHS_t, typename RHS_t, typename Sum_t> template<typename OpTy> bool llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::match (OpTy * V) const inline
Definition at line 2674 of file PatternMatch.h.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, L, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZeroInt(), match(), R, and S.
Referenced by match().
Member Data Documentation
L
template<typename LHS_t, typename RHS_t, typename Sum_t> LHS_t llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::L
Definition at line 2667 of file PatternMatch.h.
Referenced by match(), and UAddWithOverflow_match().
R
template<typename LHS_t, typename RHS_t, typename Sum_t> RHS_t llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::R
Definition at line 2668 of file PatternMatch.h.
Referenced by match(), and UAddWithOverflow_match().
S
template<typename LHS_t, typename RHS_t, typename Sum_t> Sum_t llvm::PatternMatch::UAddWithOverflow_match< LHS_t, RHS_t, Sum_t >::S
Definition at line 2669 of file PatternMatch.h.
Referenced by match(), and UAddWithOverflow_match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h