LLVM: llvm::IndirectBrInst::succ_op_iterator Struct Reference
llvm::IndirectBrInst::succ_op_iterator Struct Reference
Iterator type that casts an operand to a basic block.
#include "llvm/IR/Instructions.h"
Public Member Functions
succ_op_iterator (value_op_iterator I)
BasicBlock * operator* () const
BasicBlock * operator-> () const
Public Member Functions inherited from llvm::iterator_adaptor_base< succ_op_iterator, value_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >
succ_op_iterator & operator+= (difference_type n)
succ_op_iterator & operator-= (difference_type n)
difference_type operator- (const succ_op_iterator &RHS) const
succ_op_iterator & operator++ ()
succ_op_iterator & operator-- ()
BasicBlock * operator* () const
Public Member Functions inherited from llvm::iterator_facade_base< succ_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >
succ_op_iterator operator+ (ptrdiff_t n) const
succ_op_iterator operator- (ptrdiff_t n) const
succ_op_iterator & operator++ ()
succ_op_iterator & operator-- ()
bool operator!= (const succ_op_iterator &RHS) const
bool operator> (const succ_op_iterator &RHS) const
bool operator<= (const succ_op_iterator &RHS) const
bool operator>= (const succ_op_iterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_adaptor_base< succ_op_iterator, value_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >
using difference_type
Public Types inherited from llvm::iterator_facade_base< succ_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >
enum
using iterator_category
using value_type
using difference_type
using pointer
using reference
Protected Member Functions inherited from llvm::iterator_adaptor_base< succ_op_iterator, value_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >
iterator_adaptor_base ()=default
const value_op_iterator & wrapped () const
Protected Attributes inherited from llvm::iterator_adaptor_base< succ_op_iterator, value_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >
value_op_iterator I
Detailed Description
Iterator type that casts an operand to a basic block.
This only makes sense because the successors are stored as adjacent operands for indirectbr instructions.
Definition at line 3634 of file Instructions.h.
Constructor & Destructor Documentation
succ_op_iterator()
llvm::IndirectBrInst::succ_op_iterator::succ_op_iterator (value_op_iterator I) inline explicit
Definition at line 3638 of file Instructions.h.
References llvm::iterator_adaptor_base< succ_op_iterator, value_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >::I, and llvm::iterator_adaptor_base< succ_op_iterator, value_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >::iterator_adaptor_base().
Member Function Documentation
operator*()
BasicBlock * llvm::IndirectBrInst::succ_op_iterator::operator* () const inline
Definition at line 3640 of file Instructions.h.
References llvm::Instruction::BasicBlock, llvm::cast(), and llvm::iterator_adaptor_base< succ_op_iterator, value_op_iterator, std::random_access_iterator_tag, BasicBlock *, ptrdiff_t, BasicBlock *, BasicBlock * >::I.
Referenced by operator->().
operator->()
BasicBlock * llvm::IndirectBrInst::succ_op_iterator::operator-> () const inline
Definition at line 3641 of file Instructions.h.
References llvm::Instruction::BasicBlock, and operator*().
The documentation for this struct was generated from the following file:
include/llvm/IR/Instructions.h