LLVM: llvm::index_iterator::int_wrapper Struct Reference
llvm::index_iterator::int_wrapper Struct Reference
#include "llvm/IR/Attributes.h"
Public Member Functions
int_wrapper (unsigned i)
unsigned operator* ()
bool operator!= (const int_wrapper &Other)
int_wrapper & operator++ ()
Public Attributes
unsigned i
Detailed Description
Definition at line 1012 of file Attributes.h.
Constructor & Destructor Documentation
int_wrapper()
llvm::index_iterator::int_wrapper::int_wrapper (unsigned i) inline
Definition at line 1013 of file Attributes.h.
References i.
Referenced by operator!=(), and operator++().
Member Function Documentation
operator!=()
bool llvm::index_iterator::int_wrapper::operator!= (const int_wrapper & Other) inline
Definition at line 1016 of file Attributes.h.
References i, and int_wrapper().
operator*()
unsigned llvm::index_iterator::int_wrapper::operator* () inline
Definition at line 1015 of file Attributes.h.
References i.
operator++()
int_wrapper & llvm::index_iterator::int_wrapper::operator++ () inline
Definition at line 1017 of file Attributes.h.
References i, and int_wrapper().
Member Data Documentation
i
unsigned llvm::index_iterator::int_wrapper::i
Definition at line 1014 of file Attributes.h.
Referenced by int_wrapper(), operator!=(), operator*(), and operator++().
The documentation for this struct was generated from the following file:
include/llvm/IR/Attributes.h