LLVM: llvm::CoroAnnotationElidePass Struct Reference
llvm::CoroAnnotationElidePass Struct Reference
#include "llvm/Transforms/Coroutines/CoroAnnotationElide.h"
Public Member Functions
CoroAnnotationElidePass ()=default
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< CoroAnnotationElidePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< CoroAnnotationElidePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 26 of file CoroAnnotationElide.h.
Constructor & Destructor Documentation
CoroAnnotationElidePass()
llvm::CoroAnnotationElidePass::CoroAnnotationElidePass () default
References llvm::CallingConv::C.
Member Function Documentation
isRequired()
bool llvm::CoroAnnotationElidePass::isRequired () inline static
Definition at line 32 of file CoroAnnotationElide.h.
run()
PreservedAnalyses CoroAnnotationElidePass::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 115 of file CoroAnnotationElide.cpp.
References llvm::PreservedAnalyses::all(), llvm::Function::arg_size(), llvm::CallingConv::C, CoroElideBranchRatio, DEBUG_TYPE, llvm::dyn_cast(), FAM, llvm::Function::getParamAlign(), llvm::Function::getParamDereferenceableBytes(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::CallGraphUpdater::initialize(), llvm::LazyCallGraph::lookup(), llvm::LazyCallGraph::lookupSCC(), N, llvm::PreservedAnalyses::none(), processCall(), llvm::updateCGAndAnalysisManagerForCGSCCPass(), Users, and llvm::MaybeAlign::valueOrOne().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Coroutines/CoroAnnotationElide.h
lib/Transforms/Coroutines/CoroAnnotationElide.cpp