LLVM: llvm::AA::ValueAndContext Struct Reference
llvm::AA::ValueAndContext Struct Reference
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using Base = std::pair<Value *, const Instruction *>
Public Member Functions
ValueAndContext (const Base &B)
ValueAndContext (Value &V, const Instruction *CtxI)
ValueAndContext (Value &V, const Instruction &CtxI)
Value * getValue () const
const Instruction * getCtxI () const
Detailed Description
Definition at line 188 of file Attributor.h.
Member Typedef Documentation
Base
using llvm::AA::ValueAndContext::Base = std::pair<Value *, const Instruction *>
Definition at line 189 of file Attributor.h.
Constructor & Destructor Documentation
ValueAndContext() [1/3]
llvm::AA::ValueAndContext::ValueAndContext (const Base & B) inline
Definition at line 190 of file Attributor.h.
References B().
ValueAndContext() [2/3]
llvm::AA::ValueAndContext::ValueAndContext (Value & V, const Instruction * CtxI) inline
Definition at line 191 of file Attributor.h.
ValueAndContext() [3/3]
llvm::AA::ValueAndContext::ValueAndContext (Value & V, const Instruction & CtxI) inline
Definition at line 192 of file Attributor.h.
Member Function Documentation
getCtxI()
const Instruction * llvm::AA::ValueAndContext::getCtxI () const inline
Definition at line 195 of file Attributor.h.
Referenced by llvm::AA::isValidAtPosition().
getValue()
Value * llvm::AA::ValueAndContext::getValue () const inline
Definition at line 194 of file Attributor.h.
Referenced by llvm::Attributor::checkForAllReturnedValues(), and llvm::AA::isValidAtPosition().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h