LLVM: llvm::orc::ExecutorAddrRange Struct Reference
llvm::orc::ExecutorAddrRange Struct Reference
Represents an address range in the exceutor process.
#include "llvm/ExecutionEngine/Orc/Shared/ExecutorAddress.h"
Public Member Functions
ExecutorAddrRange ()=default
ExecutorAddrRange (ExecutorAddr Start, ExecutorAddr End)
ExecutorAddrRange (ExecutorAddr Start, ExecutorAddrDiff Size)
bool empty () const
ExecutorAddrDiff size () const
bool contains (ExecutorAddr Addr) const
bool contains (const ExecutorAddrRange &Other)
bool overlaps (const ExecutorAddrRange &Other)
Static Public Member Functions
template<typename T, typename UnwrapFn = ExecutorAddr::defaultUnwrap<T>>
static ExecutorAddrRange fromPtrRange (T *Start, T *End, UnwrapFn &&Unwrap=UnwrapFn())
template<typename T, typename UnwrapFn = ExecutorAddr::defaultUnwrap<T>>
static ExecutorAddrRange fromPtrRange (T *Ptr, ExecutorAddrDiff Size, UnwrapFn &&Unwrap=UnwrapFn())
Public Attributes
ExecutorAddr Start
ExecutorAddr End
Friends
bool operator== (const ExecutorAddrRange &LHS, const ExecutorAddrRange &RHS)
bool operator!= (const ExecutorAddrRange &LHS, const ExecutorAddrRange &RHS)
bool operator< (const ExecutorAddrRange &LHS, const ExecutorAddrRange &RHS)
bool operator<= (const ExecutorAddrRange &LHS, const ExecutorAddrRange &RHS)
bool operator> (const ExecutorAddrRange &LHS, const ExecutorAddrRange &RHS)
bool operator>= (const ExecutorAddrRange &LHS, const ExecutorAddrRange &RHS)
Detailed Description
Represents an address range in the exceutor process.
Definition at line 222 of file ExecutorAddress.h.
Constructor & Destructor Documentation
ExecutorAddrRange() [1/3]
llvm::orc::ExecutorAddrRange::ExecutorAddrRange () default
Referenced by contains(), fromPtrRange(), fromPtrRange(), operator!=, operator<, operator<=, operator==, operator>, operator>=, and overlaps().
ExecutorAddrRange() [2/3]
llvm::orc::ExecutorAddrRange::ExecutorAddrRange (ExecutorAddr Start, ExecutorAddr End) inline
Definition at line 224 of file ExecutorAddress.h.
References End, and Start.
ExecutorAddrRange() [3/3]
llvm::orc::ExecutorAddrRange::ExecutorAddrRange (ExecutorAddr Start, ExecutorAddrDiff Size) inline
Definition at line 226 of file ExecutorAddress.h.
References End, and Start.
Member Function Documentation
contains() [1/2]
bool llvm::orc::ExecutorAddrRange::contains (const ExecutorAddrRange & Other) inline
Definition at line 275 of file ExecutorAddress.h.
References End, ExecutorAddrRange(), llvm::Other, and Start.
contains() [2/2]
bool llvm::orc::ExecutorAddrRange::contains (ExecutorAddr Addr) const inline
Definition at line 274 of file ExecutorAddress.h.
References End, and Start.
empty()
bool llvm::orc::ExecutorAddrRange::empty () const inline
Definition at line 242 of file ExecutorAddress.h.
References End, and Start.
Referenced by llvm::orc::MapperJITLinkMemoryManager::allocate().
fromPtrRange() [1/2]
template<typename T, typename UnwrapFn = ExecutorAddr::defaultUnwrap<T>> ExecutorAddrRange llvm::orc::ExecutorAddrRange::fromPtrRange (T * Ptr, ExecutorAddrDiff Size, UnwrapFn && Unwrap = UnwrapFn()) inline static
Definition at line 237 of file ExecutorAddress.h.
References ExecutorAddrRange(), llvm::orc::ExecutorAddr::fromPtr(), Size, and T.
fromPtrRange() [2/2]
template<typename T, typename UnwrapFn = ExecutorAddr::defaultUnwrap<T>> ExecutorAddrRange llvm::orc::ExecutorAddrRange::fromPtrRange (T * Start, T * End, UnwrapFn && Unwrap = UnwrapFn()) inline static
Definition at line 230 of file ExecutorAddress.h.
References End, ExecutorAddrRange(), llvm::orc::ExecutorAddr::fromPtr(), Start, and T.
overlaps()
bool llvm::orc::ExecutorAddrRange::overlaps (const ExecutorAddrRange & Other) inline
Definition at line 278 of file ExecutorAddress.h.
References End, ExecutorAddrRange(), llvm::Other, and Start.
size()
ExecutorAddrDiff llvm::orc::ExecutorAddrRange::size () const inline
Definition at line 243 of file ExecutorAddress.h.
References End, and Start.
Referenced by deregisterEHFrameWrapper(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::initialize(), and registerEHFrameWrapper().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const ExecutorAddrRange & LHS, const ExecutorAddrRange & RHS) friend
Definition at line 249 of file ExecutorAddress.h.
References ExecutorAddrRange(), LHS, and RHS.
operator<
bool operator< (const ExecutorAddrRange & LHS, const ExecutorAddrRange & RHS) friend
Definition at line 253 of file ExecutorAddress.h.
References ExecutorAddrRange(), LHS, and RHS.
operator<=
bool operator<= (const ExecutorAddrRange & LHS, const ExecutorAddrRange & RHS) friend
Definition at line 258 of file ExecutorAddress.h.
References ExecutorAddrRange(), LHS, and RHS.
operator==
bool operator== (const ExecutorAddrRange & LHS, const ExecutorAddrRange & RHS) friend
Definition at line 245 of file ExecutorAddress.h.
References ExecutorAddrRange(), LHS, and RHS.
operator>
bool operator> (const ExecutorAddrRange & LHS, const ExecutorAddrRange & RHS) friend
Definition at line 263 of file ExecutorAddress.h.
References ExecutorAddrRange(), LHS, and RHS.
operator>=
bool operator>= (const ExecutorAddrRange & LHS, const ExecutorAddrRange & RHS) friend
Definition at line 268 of file ExecutorAddress.h.
References ExecutorAddrRange(), LHS, and RHS.
Member Data Documentation
End
ExecutorAddr llvm::orc::ExecutorAddrRange::End
Definition at line 283 of file ExecutorAddress.h.
Referenced by contains(), contains(), empty(), ExecutorAddrRange(), ExecutorAddrRange(), fromPtrRange(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::initialize(), overlaps(), and size().
Start
ExecutorAddr llvm::orc::ExecutorAddrRange::Start
Definition at line 282 of file ExecutorAddress.h.
Referenced by contains(), contains(), deregisterEHFrameWrapper(), empty(), ExecutorAddrRange(), ExecutorAddrRange(), llvm::orc::EPCGenericRTDyldMemoryManager::finalizeMemory(), fromPtrRange(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::initialize(), overlaps(), registerEHFrameWrapper(), and size().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/ExecutorAddress.h