LLVM: slpvectorizer::BoUpSLP::EdgeInfo Struct Reference
slpvectorizer::BoUpSLP::EdgeInfo Struct Reference
This structure holds any data we need about the edges being traversed during buildTreeRec().
Public Member Functions
EdgeInfo ()=default
EdgeInfo (TreeEntry *UserTE, unsigned EdgeIdx)
void dump (raw_ostream &OS) const
Debug print.
LLVM_DUMP_METHOD void dump () const
bool operator== (const EdgeInfo &Other) const
operator bool () const
Public Attributes
TreeEntry * UserTE = nullptr
The user TreeEntry.
unsigned EdgeIdx = UINT_MAX
The operand index of the use.
Friends
raw_ostream & operator<< (raw_ostream &OS, const BoUpSLP::EdgeInfo &EI)
Detailed Description
This structure holds any data we need about the edges being traversed during buildTreeRec().
We keep track of: (i) the user TreeEntry index, and (ii) the index of the edge.
Definition at line 2372 of file SLPVectorizer.cpp.
Constructor & Destructor Documentation
EdgeInfo() [1/2]
slpvectorizer::BoUpSLP::EdgeInfo::EdgeInfo () default
Referenced by operator==().
EdgeInfo() [2/2]
slpvectorizer::BoUpSLP::EdgeInfo::EdgeInfo (TreeEntry * UserTE, unsigned EdgeIdx) inline
Definition at line 2374 of file SLPVectorizer.cpp.
References EdgeIdx, and UserTE.
Member Function Documentation
dump() [1/2]
LLVM_DUMP_METHOD void slpvectorizer::BoUpSLP::EdgeInfo::dump () const inline
Definition at line 2391 of file SLPVectorizer.cpp.
References llvm::dbgs(), dump(), and LLVM_DUMP_METHOD.
Referenced by dump().
dump() [2/2]
void slpvectorizer::BoUpSLP::EdgeInfo::dump (raw_ostream & OS) const inline
Debug print.
Definition at line 2387 of file SLPVectorizer.cpp.
References EdgeIdx, and UserTE.
Referenced by operator<<.
operator bool()
slpvectorizer::BoUpSLP::EdgeInfo::operator bool () const inline
Definition at line 2397 of file SLPVectorizer.cpp.
References UserTE.
operator==()
bool slpvectorizer::BoUpSLP::EdgeInfo::operator== (const EdgeInfo & Other) const inline
Definition at line 2393 of file SLPVectorizer.cpp.
References EdgeIdx, EdgeInfo(), llvm::Other, and UserTE.
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const BoUpSLP::EdgeInfo & EI) friend
Definition at line 2381 of file SLPVectorizer.cpp.
References dump().
Member Data Documentation
EdgeIdx
unsigned slpvectorizer::BoUpSLP::EdgeInfo::EdgeIdx = UINT_MAX
The operand index of the use.
Definition at line 2379 of file SLPVectorizer.cpp.
Referenced by dump(), EdgeInfo(), llvm::DenseMapInfo< BoUpSLP::EdgeInfo >::getHashValue(), and operator==().
UserTE
TreeEntry* slpvectorizer::BoUpSLP::EdgeInfo::UserTE = nullptr
The user TreeEntry.
Definition at line 2377 of file SLPVectorizer.cpp.
Referenced by dump(), EdgeInfo(), llvm::DenseMapInfo< BoUpSLP::EdgeInfo >::getHashValue(), operator bool(), operator==(), and tryToFindDuplicates().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/SLPVectorizer.cpp