LLVM: llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable > Struct Template Reference
llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
BinaryOp_match (const LHS_t &LHS, const RHS_t &RHS)
template<typename OpTy>
bool match (unsigned Opc, OpTy *V) const
template<typename OpTy>
bool match (OpTy *V) const
Public Attributes
LHS_t L
RHS_t R
Detailed Description
template<typename LHS_t, typename RHS_t, unsigned Opcode, bool Commutable = false>
struct llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >
Definition at line 1184 of file PatternMatch.h.
Constructor & Destructor Documentation
BinaryOp_match()
template<typename LHS_t, typename RHS_t, unsigned Opcode, bool Commutable = false> llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::BinaryOp_match (const LHS_t & LHS, const RHS_t & RHS) inline
Definition at line 1190 of file PatternMatch.h.
References L, LHS, R, and RHS.
Member Function Documentation
match() [1/2]
template<typename LHS_t, typename RHS_t, unsigned Opcode, bool Commutable = false> template<typename OpTy> bool llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::match (OpTy * V) const inline
Definition at line 1202 of file PatternMatch.h.
References match().
match() [2/2]
template<typename LHS_t, typename RHS_t, unsigned Opcode, bool Commutable = false> template<typename OpTy> bool llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::match (unsigned Opc, OpTy * V) const inline
Definition at line 1192 of file PatternMatch.h.
References llvm::cast(), I, L, Opc, and R.
Referenced by match(), and llvm::PatternMatch::SpecificBinaryOp_match< LHS_t, RHS_t, Commutable >::match().
Member Data Documentation
L
template<typename LHS_t, typename RHS_t, unsigned Opcode, bool Commutable = false> LHS_t llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::L
Definition at line 1185 of file PatternMatch.h.
Referenced by BinaryOp_match(), and match().
R
template<typename LHS_t, typename RHS_t, unsigned Opcode, bool Commutable = false> RHS_t llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode, Commutable >::R
Definition at line 1186 of file PatternMatch.h.
Referenced by BinaryOp_match(), and match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h