LLVM: llvm::rdf::RegisterRef Struct Reference
llvm::rdf::RegisterRef Struct Reference
#include "llvm/CodeGen/RDFRegisters.h"
Public Member Functions
constexpr RegisterRef ()=default
constexpr RegisterRef (RegisterId R, LaneBitmask M=LaneBitmask::getAll())
constexpr bool isReg () const
constexpr bool isUnit () const
constexpr bool isMask () const
constexpr MCRegister asMCReg () const
constexpr MCRegUnit asMCRegUnit () const
constexpr unsigned asMaskIdx () const
constexpr operator bool () const
size_t hash () const
bool operator< (RegisterRef) const =delete
bool operator== (RegisterRef) const =delete
bool operator!= (RegisterRef) const =delete
Static Public Member Functions
static constexpr bool isRegId (RegisterId Id)
static constexpr bool isUnitId (RegisterId Id)
static constexpr bool isMaskId (RegisterId Id)
static constexpr RegisterId toUnitId (unsigned Idx)
static constexpr RegisterId toMaskId (unsigned Idx)
Public Attributes
RegisterId Id = 0
LaneBitmask Mask = LaneBitmask::getNone()
Detailed Description
Definition at line 89 of file RDFRegisters.h.
Constructor & Destructor Documentation
RegisterRef() [1/2]
llvm::rdf::RegisterRef::RegisterRef () constexpr default
Referenced by operator!=(), operator<(), and operator==().
RegisterRef() [2/2]
llvm::rdf::RegisterRef::RegisterRef (RegisterId R, LaneBitmask M = LaneBitmask::getAll()) inline explicit constexpr
Definition at line 99 of file RDFRegisters.h.
References llvm::LaneBitmask::getAll(), Id, isRegId(), and Mask.
Member Function Documentation
asMaskIdx()
unsigned llvm::rdf::RegisterRef::asMaskIdx () const inline constexpr
Definition at line 118 of file RDFRegisters.h.
References assert(), Id, and isMask().
Referenced by llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), and llvm::rdf::PhysicalRegisterInfo::getRegMaskBits().
asMCReg()
MCRegister llvm::rdf::RegisterRef::asMCReg () const inline constexpr
Definition at line 108 of file RDFRegisters.h.
References assert(), Id, and isReg().
Referenced by llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::DataFlowGraph::hasUntrackedRef(), llvm::rdf::RegisterAggr::insert(), llvm::rdf::CopyPropagation::interpretAsCopy(), and llvm::rdf::PhysicalRegisterInfo::mapTo().
asMCRegUnit()
MCRegUnit llvm::rdf::RegisterRef::asMCRegUnit () const inline constexpr
Definition at line 113 of file RDFRegisters.h.
References assert(), Id, and isUnit().
hash()
size_t llvm::rdf::RegisterRef::hash () const inline
Definition at line 127 of file RDFRegisters.h.
References Id, and Mask.
isMask()
bool llvm::rdf::RegisterRef::isMask () const inline constexpr
Definition at line 106 of file RDFRegisters.h.
References Id, and isMaskId().
Referenced by asMaskIdx(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), and llvm::rdf::RegisterAggr::insert().
isMaskId()
constexpr bool llvm::rdf::RegisterRef::isMaskId (RegisterId Id) inline static constexpr
Definition at line 136 of file RDFRegisters.h.
References Id.
Referenced by isMask(), and llvm::rdf::DataFlowGraph::makeRegRef().
isReg()
bool llvm::rdf::RegisterRef::isReg () const inline constexpr
Definition at line 104 of file RDFRegisters.h.
References Id, and isRegId().
Referenced by asMCReg(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::DataFlowGraph::hasUntrackedRef(), and operator bool().
isRegId()
constexpr bool llvm::rdf::RegisterRef::isRegId (RegisterId Id) inline static constexpr
Definition at line 132 of file RDFRegisters.h.
References Id.
Referenced by isReg(), llvm::rdf::DataFlowGraph::makeRegRef(), and RegisterRef().
isUnit()
bool llvm::rdf::RegisterRef::isUnit () const inline constexpr
Definition at line 105 of file RDFRegisters.h.
References Id, and isUnitId().
Referenced by asMCRegUnit(), and llvm::rdf::PhysicalRegisterInfo::getAliasSet().
isUnitId()
constexpr bool llvm::rdf::RegisterRef::isUnitId (RegisterId Id) inline static constexpr
Definition at line 135 of file RDFRegisters.h.
References Id.
Referenced by isUnit().
operator bool()
llvm::rdf::RegisterRef::operator bool () const inline explicit constexpr
Definition at line 123 of file RDFRegisters.h.
References Id, isReg(), and Mask.
operator!=()
bool llvm::rdf::RegisterRef::operator!= (RegisterRef) const delete
References RegisterRef().
operator<()
bool llvm::rdf::RegisterRef::operator< (RegisterRef) const delete
References RegisterRef().
operator==()
bool llvm::rdf::RegisterRef::operator== (RegisterRef) const delete
References RegisterRef().
toMaskId()
constexpr RegisterId llvm::rdf::RegisterRef::toMaskId (unsigned Idx) inline static constexpr
Definition at line 140 of file RDFRegisters.h.
Referenced by llvm::rdf::PhysicalRegisterInfo::getRegMaskId().
toUnitId()
constexpr RegisterId llvm::rdf::RegisterRef::toUnitId (unsigned Idx) inline static constexpr
Definition at line 138 of file RDFRegisters.h.
Member Data Documentation
Id
RegisterId llvm::rdf::RegisterRef::Id = 0
Definition at line 95 of file RDFRegisters.h.
Referenced by asMaskIdx(), asMCReg(), asMCRegUnit(), llvm::rdf::Liveness::computeLiveIns(), hash(), isMask(), isMaskId(), isReg(), isRegId(), isUnit(), isUnitId(), llvm::rdf::PhysicalRegisterInfo::mapTo(), operator bool(), llvm::rdf::DataFlowGraph::pack(), llvm::rdf::DataFlowGraph::pack(), and RegisterRef().
Mask
LaneBitmask llvm::rdf::RegisterRef::Mask = LaneBitmask::getNone()
Definition at line 96 of file RDFRegisters.h.
Referenced by llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), hash(), llvm::rdf::RegisterAggr::insert(), llvm::rdf::PhysicalRegisterInfo::mapTo(), operator bool(), llvm::rdf::DataFlowGraph::pack(), llvm::rdf::DataFlowGraph::pack(), and RegisterRef().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/RDFRegisters.h