LLVM: llvm::GraphTraits< ProfiledCallGraph * > Struct Reference
llvm::GraphTraits< ProfiledCallGraph * > Struct Reference
#include "llvm/Transforms/IPO/ProfiledCallGraph.h"
Public Types
using NodeRef
Public Types inherited from llvm::GraphTraits< ProfiledCallGraphNode * >
using NodeType = ProfiledCallGraphNode
using NodeRef = ProfiledCallGraphNode *
using EdgeType = NodeType::edge
using ChildIteratorType = NodeType::const_iterator
Static Public Member Functions
static NodeRef getEntryNode (ProfiledCallGraph *PCG)
static ChildIteratorType nodes_begin (ProfiledCallGraph *PCG)
static ChildIteratorType nodes_end (ProfiledCallGraph *PCG)
Static Public Member Functions inherited from llvm::GraphTraits< ProfiledCallGraphNode * >
static NodeRef getEntryNode (NodeRef PCGN)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 228 of file ProfiledCallGraph.h.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< ProfiledCallGraph * >::NodeRef
Definition at line 95 of file GraphTraits.h.
Member Function Documentation
getEntryNode()
NodeRef llvm::GraphTraits< ProfiledCallGraph * >::getEntryNode (ProfiledCallGraph * PCG) inline static
Definition at line 230 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraph::getEntryNode().
nodes_begin()
ChildIteratorType llvm::GraphTraits< ProfiledCallGraph * >::nodes_begin (ProfiledCallGraph * PCG) inline static
Definition at line 234 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraph::begin().
nodes_end()
ChildIteratorType llvm::GraphTraits< ProfiledCallGraph * >::nodes_end (ProfiledCallGraph * PCG) inline static
Definition at line 238 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraph::end().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/ProfiledCallGraph.h