LLVM: llvm::IndexedCGData::Header Struct Reference
llvm::IndexedCGData::Header Struct Reference
#include "llvm/CGData/CodeGenData.h"
Static Public Member Functions
static LLVM_ABI Expected< Header > readFromBuffer (const unsigned char *Curr)
Public Attributes
uint64_t Magic
uint32_t Version
uint32_t DataKind
uint64_t OutlinedHashTreeOffset
uint64_t StableFunctionMapOffset
Detailed Description
Definition at line 295 of file CodeGenData.h.
Member Function Documentation
readFromBuffer()
Expected< Header > llvm::IndexedCGData::Header::readFromBuffer (const unsigned char * Curr) static
Definition at line 177 of file CodeGenData.cpp.
References llvm::bad_magic, llvm::IndexedCGData::CurrentVersion, H, llvm::IndexedCGData::Magic, llvm::make_error(), llvm::support::endian::readNext(), llvm::unsupported_version, and llvm::IndexedCGData::Version4.
Referenced by llvm::IndexedCodeGenDataReader::read().
Member Data Documentation
DataKind
uint32_t llvm::IndexedCGData::Header::DataKind
Definition at line 298 of file CodeGenData.h.
Magic
uint64_t llvm::IndexedCGData::Header::Magic
Definition at line 296 of file CodeGenData.h.
OutlinedHashTreeOffset
uint64_t llvm::IndexedCGData::Header::OutlinedHashTreeOffset
Definition at line 299 of file CodeGenData.h.
StableFunctionMapOffset
uint64_t llvm::IndexedCGData::Header::StableFunctionMapOffset
Definition at line 300 of file CodeGenData.h.
Version
uint32_t llvm::IndexedCGData::Header::Version
Definition at line 297 of file CodeGenData.h.
The documentation for this struct was generated from the following files:
include/llvm/CGData/CodeGenData.h
lib/CGData/CodeGenData.cpp