LLVM: llvm::MachineFunction::CallSiteInfo Struct Reference
llvm::MachineFunction::CallSiteInfo Struct Reference
#include "llvm/CodeGen/MachineFunction.h"
Public Member Functions
CallSiteInfo ()=default
LLVM_ABI CallSiteInfo (const CallBase &CB)
Extracts the numeric type id from the CallBase's callee_type Metadata, and sets CalleeTypeIds.
Public Attributes
SmallVector< ArgRegPair, 1 > ArgRegPairs
Vector of call argument and its forwarding register.
SmallVector< ConstantInt *, 4 > CalleeTypeIds
Callee type ids.
Detailed Description
Definition at line 515 of file MachineFunction.h.
Constructor & Destructor Documentation
CallSiteInfo() [1/2]
llvm::MachineFunction::CallSiteInfo::CallSiteInfo () default
References LLVM_ABI.
CallSiteInfo() [2/2]
MachineFunction::CallSiteInfo::CallSiteInfo (const CallBase & CB)
Extracts the numeric type id from the CallBase's callee_type Metadata, and sets CalleeTypeIds.
This is used as type id for the indirect call in the call graph section.
Definition at line 702 of file MachineFunction.cpp.
References CalleeTypeIds, llvm::cast(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), llvm::Instruction::getMetadata(), llvm::MDNode::getOperand(), llvm::MDString::getString(), llvm::CallBase::isIndirectCall(), llvm::sampleprof::MD5Hash(), and llvm::MDNode::operands().
Member Data Documentation
ArgRegPairs
SmallVector<ArgRegPair, 1> llvm::MachineFunction::CallSiteInfo::ArgRegPairs
Vector of call argument and its forwarding register.
Definition at line 517 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeCallSiteInfo(), and llvm::RISCVTargetLowering::LowerCall().
CalleeTypeIds
SmallVector<ConstantInt *, 4> llvm::MachineFunction::CallSiteInfo::CalleeTypeIds
Callee type ids.
Definition at line 519 of file MachineFunction.h.
Referenced by CallSiteInfo(), and llvm::MIRParserImpl::initializeCallSiteInfo().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MachineFunction.h
lib/CodeGen/MachineFunction.cpp