LLVM: llvm::lsp::Location Struct Reference
llvm::lsp::Location Struct Reference
#include "llvm/Support/LSP/Protocol.h"
Public Member Functions
Location ()=default
Location (const URIForFile &uri, Range range)
Location (const URIForFile &uri, llvm::SourceMgr &mgr, SMRange range)
Construct a Location from the given source range.
Public Attributes
URIForFile uri
The text document's URI.
Range range
Friends
bool operator== (const Location &lhs, const Location &rhs)
bool operator!= (const Location &lhs, const Location &rhs)
bool operator< (const Location &lhs, const Location &rhs)
Detailed Description
Definition at line 399 of file Protocol.h.
Constructor & Destructor Documentation
Location() [1/3]
llvm::lsp::Location::Location () default
Referenced by Location(), operator!=, operator<, and operator==.
Location() [2/3]
llvm::lsp::Location::Location (const URIForFile & uri, Range range) inline
Definition at line 401 of file Protocol.h.
References range, and uri.
Location() [3/3]
llvm::lsp::Location::Location (const URIForFile & uri, llvm::SourceMgr & mgr, SMRange range) inline
Construct a Location from the given source range.
Definition at line 404 of file Protocol.h.
References Location(), range, and uri.
Friends And Related Symbol Documentation
operator!=
bool operator!= (const Location & lhs, const Location & rhs) friend
Definition at line 415 of file Protocol.h.
References Location().
operator<
bool operator< (const Location & lhs, const Location & rhs) friend
Definition at line 419 of file Protocol.h.
References Location(), range, and uri.
operator==
bool operator== (const Location & lhs, const Location & rhs) friend
Definition at line 411 of file Protocol.h.
References Location(), range, and uri.
Member Data Documentation
range
Range llvm::lsp::Location::range
Definition at line 409 of file Protocol.h.
Referenced by Location(), Location(), operator<, and operator==.
uri
URIForFile llvm::lsp::Location::uri
The text document's URI.
Definition at line 408 of file Protocol.h.
Referenced by Location(), Location(), operator<, and operator==.
The documentation for this struct was generated from the following file:
include/llvm/Support/LSP/Protocol.h