LLVM: llvm::WasmYAML::Section Struct Reference
llvm::WasmYAML::Section Struct Reference
#include "llvm/ObjectYAML/WasmYAML.h"
Public Member Functions
Section (SectionType SecType)
virtual ~Section ()
Public Attributes
SectionType Type
std::vector< Relocation > Relocations
std::optional< uint8_t > HeaderSecSizeEncodingLen
Detailed Description
Definition at line 187 of file WasmYAML.h.
Constructor & Destructor Documentation
Section()
llvm::WasmYAML::Section::Section (SectionType SecType) inline explicit
Definition at line 188 of file WasmYAML.h.
References Type.
Referenced by llvm::WasmYAML::CodeSection::classof(), llvm::WasmYAML::CustomSection::classof(), llvm::WasmYAML::DataCountSection::classof(), llvm::WasmYAML::DataSection::classof(), llvm::WasmYAML::ElemSection::classof(), llvm::WasmYAML::ExportSection::classof(), llvm::WasmYAML::FunctionSection::classof(), llvm::WasmYAML::GlobalSection::classof(), llvm::WasmYAML::ImportSection::classof(), llvm::WasmYAML::MemorySection::classof(), llvm::WasmYAML::StartSection::classof(), llvm::WasmYAML::TableSection::classof(), llvm::WasmYAML::TagSection::classof(), llvm::WasmYAML::TypeSection::classof(), llvm::WasmYAML::CodeSection::CodeSection(), llvm::WasmYAML::CustomSection::CustomSection(), llvm::WasmYAML::DataCountSection::DataCountSection(), llvm::WasmYAML::DataSection::DataSection(), llvm::WasmYAML::ElemSection::ElemSection(), llvm::WasmYAML::ExportSection::ExportSection(), llvm::WasmYAML::FunctionSection::FunctionSection(), llvm::WasmYAML::GlobalSection::GlobalSection(), llvm::WasmYAML::ImportSection::ImportSection(), llvm::WasmYAML::MemorySection::MemorySection(), llvm::WasmYAML::StartSection::StartSection(), llvm::WasmYAML::TableSection::TableSection(), llvm::WasmYAML::TagSection::TagSection(), and llvm::WasmYAML::TypeSection::TypeSection().
~Section()
llvm::WasmYAML::Section::~Section () virtual default
Member Data Documentation
HeaderSecSizeEncodingLen
std::optional<uint8_t> llvm::WasmYAML::Section::HeaderSecSizeEncodingLen
Definition at line 193 of file WasmYAML.h.
Relocations
std::vector<Relocation> llvm::WasmYAML::Section::Relocations
Definition at line 192 of file WasmYAML.h.
Type
SectionType llvm::WasmYAML::Section::Type
Definition at line 191 of file WasmYAML.h.
Referenced by llvm::WasmYAML::CodeSection::classof(), llvm::WasmYAML::CustomSection::classof(), llvm::WasmYAML::DataCountSection::classof(), llvm::WasmYAML::DataSection::classof(), llvm::WasmYAML::ElemSection::classof(), llvm::WasmYAML::ExportSection::classof(), llvm::WasmYAML::FunctionSection::classof(), llvm::WasmYAML::GlobalSection::classof(), llvm::WasmYAML::ImportSection::classof(), llvm::WasmYAML::MemorySection::classof(), llvm::WasmYAML::StartSection::classof(), llvm::WasmYAML::TableSection::classof(), llvm::WasmYAML::TagSection::classof(), llvm::WasmYAML::TypeSection::classof(), and Section().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/WasmYAML.h
lib/ObjectYAML/WasmYAML.cpp