LLVM: llvm::FileLoc Struct Reference
llvm::FileLoc Struct Reference
Struct holding Line:Column location.
#include "llvm/AsmParser/FileLoc.h"
Public Member Functions
bool operator== (const FileLoc &RHS) const
bool operator<= (const FileLoc &RHS) const
bool operator< (const FileLoc &RHS) const
FileLoc ()
FileLoc (unsigned L, unsigned C)
FileLoc (std::pair< unsigned, unsigned > LC)
Public Attributes
unsigned Line
0-based line number
unsigned Col
0-based column number
Detailed Description
Struct holding Line:Column location.
Definition at line 18 of file FileLoc.h.
Constructor & Destructor Documentation
FileLoc() [1/3]
llvm::FileLoc::FileLoc () inline
Definition at line 36 of file FileLoc.h.
References Col, and Line.
Referenced by operator<(), operator<=(), and operator==().
FileLoc() [2/3]
llvm::FileLoc::FileLoc (unsigned L, unsigned C) inline
Definition at line 37 of file FileLoc.h.
References llvm::CallingConv::C, Col, and Line.
FileLoc() [3/3]
llvm::FileLoc::FileLoc (std::pair< unsigned, unsigned > LC) inline
Definition at line 38 of file FileLoc.h.
References Col, and Line.
Member Function Documentation
operator<()
bool llvm::FileLoc::operator< (const FileLoc & RHS) const inline
Definition at line 32 of file FileLoc.h.
References Col, FileLoc(), Line, and RHS.
operator<=()
bool llvm::FileLoc::operator<= (const FileLoc & RHS) const inline
Definition at line 28 of file FileLoc.h.
References Col, FileLoc(), Line, and RHS.
operator==()
bool llvm::FileLoc::operator== (const FileLoc & RHS) const inline
Definition at line 24 of file FileLoc.h.
References Col, FileLoc(), Line, and RHS.
Member Data Documentation
Col
unsigned llvm::FileLoc::Col
0-based column number
Definition at line 22 of file FileLoc.h.
Referenced by FileLoc(), FileLoc(), FileLoc(), operator<(), operator<=(), and operator==().
Line
unsigned llvm::FileLoc::Line
0-based line number
Definition at line 20 of file FileLoc.h.
Referenced by FileLoc(), FileLoc(), FileLoc(), operator<(), operator<=(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/AsmParser/FileLoc.h