LLVM: llvm::remarks::YAMLMetaSerializer Struct Reference
llvm::remarks::YAMLMetaSerializer Struct Reference
#include "llvm/Remarks/YAMLRemarkSerializer.h"
Public Member Functions
YAMLMetaSerializer (raw_ostream &OS, StringRef ExternalFilename)
void emit () override
Public Member Functions inherited from llvm::remarks::MetaSerializer
MetaSerializer (raw_ostream &OS)
virtual ~MetaSerializer ()=default
This is just an interface.
Public Attributes
StringRef ExternalFilename
Public Attributes inherited from llvm::remarks::MetaSerializer
raw_ostream & OS
The open raw_ostream that the metadata is emitted to.
Detailed Description
Definition at line 50 of file YAMLRemarkSerializer.h.
Constructor & Destructor Documentation
YAMLMetaSerializer()
llvm::remarks::YAMLMetaSerializer::YAMLMetaSerializer (raw_ostream & OS, StringRef ExternalFilename) inline
Definition at line 53 of file YAMLRemarkSerializer.h.
References ExternalFilename, llvm::remarks::MetaSerializer::MetaSerializer(), and llvm::remarks::MetaSerializer::OS.
Member Function Documentation
emit()
void YAMLMetaSerializer::emit () override virtual
Implements llvm::remarks::MetaSerializer.
Definition at line 180 of file YAMLRemarkSerializer.cpp.
References emitExternalFile(), emitMagic(), emitVersion(), ExternalFilename, llvm::remarks::MetaSerializer::OS, and llvm::support::endian::write64le().
Member Data Documentation
ExternalFilename
StringRef llvm::remarks::YAMLMetaSerializer::ExternalFilename
Definition at line 51 of file YAMLRemarkSerializer.h.
Referenced by emit(), and YAMLMetaSerializer().
The documentation for this struct was generated from the following files:
include/llvm/Remarks/YAMLRemarkSerializer.h
lib/Remarks/YAMLRemarkSerializer.cpp