LLVM: llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy > Struct Reference
llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy > Struct Reference
#include "llvm/IR/ModuleSummaryIndexYAML.h"
Static Public Member Functions
static void inputOne (IO &io, StringRef Key, GlobalValueSummaryMapTy &V)
static void output (IO &io, GlobalValueSummaryMapTy &V)
static void fixAliaseeLinks (GlobalValueSummaryMapTy &V)
Detailed Description
Definition at line 215 of file ModuleSummaryIndexYAML.h.
Member Function Documentation
fixAliaseeLinks()
void llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::fixAliaseeLinks (GlobalValueSummaryMapTy & V) inline static
Definition at line 296 of file ModuleSummaryIndexYAML.h.
References llvm::dyn_cast(), EmptyVI, llvm::get(), llvm::ValueInfo::getSummaryList(), and P.
inputOne()
void llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::inputOne (IO & io, StringRef Key, GlobalValueSummaryMapTy & V) inline static
Definition at line 216 of file ModuleSummaryIndexYAML.h.
References llvm::InnerAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs... >::Key, llvm::yaml::IO::mapRequired(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::yaml::IO::setError().
output()
void llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::output (IO & io, GlobalValueSummaryMapTy & V) inline static
Definition at line 260 of file ModuleSummaryIndexYAML.h.
References llvm::dyn_cast(), llvm::yaml::IO::mapRequired(), and P.
The documentation for this struct was generated from the following file:
include/llvm/IR/ModuleSummaryIndexYAML.h