LLVM: llvm::UseCaptureInfo Struct Reference
llvm::UseCaptureInfo Struct Reference
Capture information for a specific Use.
#include "llvm/Analysis/CaptureTracking.h"
Public Member Functions
UseCaptureInfo (CaptureComponents UseCC, CaptureComponents ResultCC=CaptureComponents::None)
bool isPassthrough () const
operator CaptureComponents () const
Static Public Member Functions
static UseCaptureInfo passthrough ()
Public Attributes
CaptureComponents UseCC
Components captured by this use.
CaptureComponents ResultCC
Components captured by the return value of the user of this Use.
Detailed Description
Capture information for a specific Use.
Definition at line 115 of file CaptureTracking.h.
Constructor & Destructor Documentation
UseCaptureInfo()
llvm::UseCaptureInfo::UseCaptureInfo (CaptureComponents UseCC, CaptureComponents ResultCC = CaptureComponents::None) inline
Definition at line 121 of file CaptureTracking.h.
References llvm::None, ResultCC, and UseCC.
Referenced by passthrough().
Member Function Documentation
isPassthrough()
bool llvm::UseCaptureInfo::isPassthrough () const inline
Definition at line 129 of file CaptureTracking.h.
References llvm::capturesAnything(), llvm::capturesNothing(), ResultCC, and UseCC.
operator CaptureComponents()
llvm::UseCaptureInfo::operator CaptureComponents () const inline
Definition at line 133 of file CaptureTracking.h.
References ResultCC, and UseCC.
passthrough()
UseCaptureInfo llvm::UseCaptureInfo::passthrough () inline static
Definition at line 125 of file CaptureTracking.h.
References llvm::All, llvm::None, and UseCaptureInfo().
Referenced by llvm::DetermineUseCaptureKind().
Member Data Documentation
ResultCC
CaptureComponents llvm::UseCaptureInfo::ResultCC
Components captured by the return value of the user of this Use.
Definition at line 119 of file CaptureTracking.h.
Referenced by isPassthrough(), operator CaptureComponents(), llvm::PointerMayBeCaptured(), and UseCaptureInfo().
UseCC
CaptureComponents llvm::UseCaptureInfo::UseCC
Components captured by this use.
Definition at line 117 of file CaptureTracking.h.
Referenced by isPassthrough(), operator CaptureComponents(), llvm::PointerMayBeCaptured(), and UseCaptureInfo().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/CaptureTracking.h