LLVM: llvm::Annotation2MetadataPass Struct Reference
llvm::Annotation2MetadataPass Struct Reference
Pass to convert @llvm.global.annotations to !annotation metadata.
#include "llvm/Transforms/IPO/Annotation2Metadata.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< Annotation2MetadataPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< Annotation2MetadataPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass to convert @llvm.global.annotations to !annotation metadata.
Definition at line 24 of file Annotation2Metadata.h.
Member Function Documentation
run()
PreservedAnalyses Annotation2MetadataPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 64 of file Annotation2Metadata.cpp.
References llvm::PreservedAnalyses::all(), convertAnnotation2Metadata(), and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Annotation2Metadata.h
lib/Transforms/IPO/Annotation2Metadata.cpp