LLVM: llvm::ShouldRunExtraPasses< MarkerTy >::Result Struct Reference
llvm::ShouldRunExtraPasses< MarkerTy >::Result Struct Reference
#include "llvm/Transforms/Utils/ExtraPassManager.h"
Public Member Functions
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &)
bool invalidate (Loop &L, const PreservedAnalyses &PA, LoopAnalysisManager::Invalidator &)
Detailed Description
template<typename MarkerTy>
struct llvm::ShouldRunExtraPasses< MarkerTy >::Result
Definition at line 27 of file ExtraPassManager.h.
Member Function Documentation
invalidate() [1/2]
template<typename MarkerTy> bool llvm::ShouldRunExtraPasses< MarkerTy >::Result::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator &) inline
Definition at line 28 of file ExtraPassManager.h.
References F, llvm::PreservedAnalyses::getChecker(), and llvm::PreservedAnalyses::PreservedAnalysisChecker::preservedWhenStateless().
invalidate() [2/2]
template<typename MarkerTy> bool llvm::ShouldRunExtraPasses< MarkerTy >::Result::invalidate (Loop & L, const PreservedAnalyses & PA, LoopAnalysisManager::Invalidator &) inline
Definition at line 36 of file ExtraPassManager.h.
References llvm::PreservedAnalyses::getChecker(), and llvm::PreservedAnalyses::PreservedAnalysisChecker::preservedWhenStateless().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/Utils/ExtraPassManager.h