LLVM: llvm::GlobalValueSummaryInfo Struct Reference
llvm::GlobalValueSummaryInfo Struct Reference
#include "llvm/IR/ModuleSummaryIndex.h"
Classes
union NameOrGV
Public Member Functions
GlobalValueSummaryInfo (bool HaveGVs)
ArrayRef< std::unique_ptr< GlobalValueSummary > > getSummaryList () const
Access a read-only list of global value summary structures for a particular value held in the GlobalValueMap.
void addSummary (std::unique_ptr< GlobalValueSummary > Summary)
Add a summary corresponding to a global value definition in a module with the corresponding GUID.
void verifyLocal () const
Verify that the HasLocal flag is consistent with the SummaryList.
bool hasLocal () const
Public Attributes
union llvm::GlobalValueSummaryInfo::NameOrGV U
Detailed Description
Definition at line 142 of file ModuleSummaryIndex.h.
Constructor & Destructor Documentation
GlobalValueSummaryInfo()
llvm::GlobalValueSummaryInfo::GlobalValueSummaryInfo (bool HaveGVs) inline
Definition at line 666 of file ModuleSummaryIndex.h.
References U.
Member Function Documentation
addSummary()
void llvm::GlobalValueSummaryInfo::addSummary (std::unique_ptr< GlobalValueSummary > Summary) inline
Add a summary corresponding to a global value definition in a module with the corresponding GUID.
Definition at line 669 of file ModuleSummaryIndex.h.
References llvm::GlobalValue::isLocalLinkage().
getSummaryList()
ArrayRef< std::unique_ptr< GlobalValueSummary > > llvm::GlobalValueSummaryInfo::getSummaryList () const inline
Access a read-only list of global value summary structures for a particular value held in the GlobalValueMap.
Definition at line 169 of file ModuleSummaryIndex.h.
hasLocal()
bool llvm::GlobalValueSummaryInfo::hasLocal () const inline
Definition at line 181 of file ModuleSummaryIndex.h.
verifyLocal()
void llvm::GlobalValueSummaryInfo::verifyLocal () const inline
Verify that the HasLocal flag is consistent with the SummaryList.
Should only be called prior to index-based internalization and promotion.
Definition at line 676 of file ModuleSummaryIndex.h.
References llvm::any_of(), assert(), and llvm::GlobalValue::isLocalLinkage().
Member Data Documentation
U
union llvm::GlobalValueSummaryInfo::NameOrGV llvm::GlobalValueSummaryInfo::U
Referenced by GlobalValueSummaryInfo().
The documentation for this struct was generated from the following file:
include/llvm/IR/ModuleSummaryIndex.h