LLVM: llvm::cl::OptionValue< FnT > Struct Reference
llvm::cl::OptionValue< FnT > Struct Reference final
Public Member Functions
OptionValue ()=default
OptionValue (const FnT &V)
OptionValue< FnT > & operator= (const FnT &V)
Public Member Functions inherited from llvm::cl::OptionValueCopy< FnT >
bool hasValue () const
const FnT & getValue () const
void setValue (const FnT &V)
bool compare (const FnT &V) const
Public Member Functions inherited from llvm::cl::GenericOptionValue
virtual bool compare (const GenericOptionValue &V) const =0
Additional Inherited Members
Protected Member Functions inherited from llvm::cl::OptionValueCopy< FnT >
OptionValueCopy (const OptionValueCopy &)=default
OptionValueCopy & operator= (const OptionValueCopy &)=default
~OptionValueCopy ()=default
Protected Member Functions inherited from llvm::cl::GenericOptionValue
GenericOptionValue ()=default
GenericOptionValue (const GenericOptionValue &)=default
GenericOptionValue & operator= (const GenericOptionValue &)=default
~GenericOptionValue ()=default
Detailed Description
Definition at line 34 of file TableGenBackend.cpp.
Constructor & Destructor Documentation
OptionValue() [1/2]
llvm::cl::OptionValue< FnT >::OptionValue () default
Referenced by operator=().
OptionValue() [2/2]
llvm::cl::OptionValue< FnT >::OptionValue (const FnT & V) inline
Definition at line 37 of file TableGenBackend.cpp.
References llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >::setValue().
Member Function Documentation
operator=()
OptionValue< FnT > & llvm::cl::OptionValue< FnT >::operator= (const FnT & V) inline
Definition at line 39 of file TableGenBackend.cpp.
References OptionValue(), and llvm::cl::OptionValueBase< DataType, std::is_class_v< DataType > >::setValue().
The documentation for this struct was generated from the following file:
lib/TableGen/TableGenBackend.cpp