LLVM: llvm::MIPatternMatch::SpecificConstantMatch Struct Reference
llvm::MIPatternMatch::SpecificConstantMatch Struct Reference
Matcher for a specific constant value.
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
SpecificConstantMatch (const APInt &RequestedVal)
bool match (const MachineRegisterInfo &MRI, Register Reg)
Public Attributes
APInt RequestedVal
Detailed Description
Matcher for a specific constant value.
Definition at line 194 of file MIPatternMatch.h.
Constructor & Destructor Documentation
SpecificConstantMatch()
llvm::MIPatternMatch::SpecificConstantMatch::SpecificConstantMatch (const APInt & RequestedVal) inline
Definition at line 196 of file MIPatternMatch.h.
References RequestedVal.
Member Function Documentation
match()
bool llvm::MIPatternMatch::SpecificConstantMatch::match (const MachineRegisterInfo & MRI, Register Reg) inline
Definition at line 198 of file MIPatternMatch.h.
References llvm::APInt::getBitWidth(), llvm::APInt::isSameValue(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::mi_match(), MRI, Reg, RequestedVal, and llvm::APInt::sext().
Member Data Documentation
RequestedVal
APInt llvm::MIPatternMatch::SpecificConstantMatch::RequestedVal
Definition at line 195 of file MIPatternMatch.h.
Referenced by match(), and SpecificConstantMatch().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h