LLVM: llvm::MemorySanitizerPass Struct Reference
llvm::MemorySanitizerPass Struct Reference
A module pass for msan instrumentation.
#include "llvm/Transforms/Instrumentation/MemorySanitizer.h"
Public Member Functions
MemorySanitizerPass (MemorySanitizerOptions Options)
LLVM_ABI PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
LLVM_ABI void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< MemorySanitizerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< MemorySanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A module pass for msan instrumentation.
Instruments functions to detect unitialized reads. This function pass inserts calls to runtime library functions. If the functions aren't declared yet, the pass inserts the declarations. Otherwise the existing globals are used.
Definition at line 43 of file MemorySanitizer.h.
Constructor & Destructor Documentation
MemorySanitizerPass()
llvm::MemorySanitizerPass::MemorySanitizerPass (MemorySanitizerOptions Options) inline
Definition at line 44 of file MemorySanitizer.h.
Member Function Documentation
isRequired()
bool llvm::MemorySanitizerPass::isRequired () inline static
Definition at line 50 of file MemorySanitizer.h.
printPipeline()
void MemorySanitizerPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 794 of file MemorySanitizer.cpp.
References printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses MemorySanitizerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 763 of file MemorySanitizer.cpp.
References llvm::PreservedAnalyses::abandon(), llvm::PreservedAnalyses::all(), llvm::checkIfAlreadyInstrumented(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), Modified, and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation/MemorySanitizer.h
lib/Transforms/Instrumentation/MemorySanitizer.cpp