LLVM: llvm::orc::LibraryScanner::LibraryDepsInfo Struct Reference
llvm::orc::LibraryScanner::LibraryDepsInfo Struct Reference
Dependency info for a library.
#include "llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h"
Public Member Functions
void addRPath (StringRef s)
void addRunPath (StringRef s)
void addDep (StringRef s)
Public Attributes
llvm::BumpPtrAllocator Alloc
llvm::StringSaver Saver {Alloc}
SmallVector< StringRef, 2 > rpath
SmallVector< StringRef, 2 > runPath
SmallVector< StringRef, 4 > deps
bool isPIE = false
Detailed Description
Dependency info for a library.
Definition at line 486 of file LibraryScanner.h.
Member Function Documentation
addDep()
void llvm::orc::LibraryScanner::LibraryDepsInfo::addDep (StringRef s) inline
Definition at line 499 of file LibraryScanner.h.
References deps, and Saver.
Referenced by llvm::orc::parseELF(), and llvm::orc::parseMachODeps().
addRPath()
void llvm::orc::LibraryScanner::LibraryDepsInfo::addRPath (StringRef s) inline
Definition at line 495 of file LibraryScanner.h.
References rpath, and Saver.
Referenced by llvm::orc::parseELF(), and llvm::orc::parseMachODeps().
addRunPath()
void llvm::orc::LibraryScanner::LibraryDepsInfo::addRunPath (StringRef s) inline
Definition at line 497 of file LibraryScanner.h.
References runPath, and Saver.
Referenced by llvm::orc::parseELF().
Member Data Documentation
Alloc
llvm::BumpPtrAllocator llvm::orc::LibraryScanner::LibraryDepsInfo::Alloc
Definition at line 487 of file LibraryScanner.h.
deps
SmallVector<StringRef, 4> llvm::orc::LibraryScanner::LibraryDepsInfo::deps
Definition at line 492 of file LibraryScanner.h.
Referenced by addDep().
isPIE
bool llvm::orc::LibraryScanner::LibraryDepsInfo::isPIE = false
Definition at line 493 of file LibraryScanner.h.
Referenced by llvm::orc::parseELF().
rpath
SmallVector<StringRef, 2> llvm::orc::LibraryScanner::LibraryDepsInfo::rpath
Definition at line 490 of file LibraryScanner.h.
Referenced by addRPath().
runPath
SmallVector<StringRef, 2> llvm::orc::LibraryScanner::LibraryDepsInfo::runPath
Definition at line 491 of file LibraryScanner.h.
Referenced by addRunPath().
Saver
llvm::StringSaver llvm::orc::LibraryScanner::LibraryDepsInfo::Saver {Alloc}
Definition at line 488 of file LibraryScanner.h.
Referenced by addDep(), addRPath(), and addRunPath().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/TargetProcess/LibraryScanner.h