LLVM: llvm::XCOFFYAML::AuxSymbolEnt Struct Reference
llvm::XCOFFYAML::AuxSymbolEnt Struct Reference
#include "llvm/ObjectYAML/XCOFFYAML.h"
Public Member Functions
AuxSymbolEnt (AuxSymbolType T)
virtual ~AuxSymbolEnt ()
Public Attributes
AuxSymbolType Type
Detailed Description
Definition at line 97 of file XCOFFYAML.h.
Constructor & Destructor Documentation
AuxSymbolEnt()
llvm::XCOFFYAML::AuxSymbolEnt::AuxSymbolEnt (AuxSymbolType T) inline explicit
Definition at line 100 of file XCOFFYAML.h.
References T, and Type.
Referenced by llvm::XCOFFYAML::BlockAuxEnt::BlockAuxEnt(), llvm::XCOFFYAML::BlockAuxEnt::classof(), llvm::XCOFFYAML::CsectAuxEnt::classof(), llvm::XCOFFYAML::ExcpetionAuxEnt::classof(), llvm::XCOFFYAML::FileAuxEnt::classof(), llvm::XCOFFYAML::FunctionAuxEnt::classof(), llvm::XCOFFYAML::SectAuxEntForDWARF::classof(), llvm::XCOFFYAML::SectAuxEntForStat::classof(), llvm::XCOFFYAML::CsectAuxEnt::CsectAuxEnt(), llvm::XCOFFYAML::ExcpetionAuxEnt::ExcpetionAuxEnt(), llvm::XCOFFYAML::FileAuxEnt::FileAuxEnt(), llvm::XCOFFYAML::FunctionAuxEnt::FunctionAuxEnt(), llvm::XCOFFYAML::SectAuxEntForDWARF::SectAuxEntForDWARF(), and llvm::XCOFFYAML::SectAuxEntForStat::SectAuxEntForStat().
~AuxSymbolEnt()
llvm::XCOFFYAML::AuxSymbolEnt::~AuxSymbolEnt () virtual default
Member Data Documentation
Type
AuxSymbolType llvm::XCOFFYAML::AuxSymbolEnt::Type
Definition at line 98 of file XCOFFYAML.h.
Referenced by AuxSymbolEnt(), llvm::XCOFFYAML::BlockAuxEnt::classof(), llvm::XCOFFYAML::CsectAuxEnt::classof(), llvm::XCOFFYAML::ExcpetionAuxEnt::classof(), llvm::XCOFFYAML::FileAuxEnt::classof(), llvm::XCOFFYAML::FunctionAuxEnt::classof(), llvm::XCOFFYAML::SectAuxEntForDWARF::classof(), and llvm::XCOFFYAML::SectAuxEntForStat::classof().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/XCOFFYAML.h
lib/ObjectYAML/XCOFFYAML.cpp