LLVM: llvm::object::XCOFFSectionHeader< T > Struct Template Reference
llvm::object::XCOFFSectionHeader< T > Struct Template Reference
#include "llvm/Object/XCOFFObjectFile.h"
Public Member Functions
StringRef getName () const
uint16_t getSectionType () const
uint32_t getSectionSubtype () const
bool isReservedSectionType () const
Static Public Attributes
static constexpr unsigned SectionFlagsReservedMask = 0x7
static constexpr unsigned SectionFlagsTypeMask = 0xffffu
Detailed Description
template<typename T>
struct llvm::object::XCOFFSectionHeader< T >
Definition at line 159 of file XCOFFObjectFile.h.
Member Function Documentation
getName()
template<typename T> StringRef llvm::object::XCOFFSectionHeader< T >::getName () const
Definition at line 58 of file XCOFFObjectFile.cpp.
References llvm::object::generateXCOFFFixedNameStringRef(), and T.
getSectionSubtype()
template<typename T> uint32_t llvm::object::XCOFFSectionHeader< T >::getSectionSubtype () const
Definition at line 69 of file XCOFFObjectFile.cpp.
References SectionFlagsTypeMask, and T.
getSectionType()
template<typename T> uint16_t llvm::object::XCOFFSectionHeader< T >::getSectionType () const
Definition at line 63 of file XCOFFObjectFile.cpp.
References SectionFlagsTypeMask, and T.
Referenced by isReservedSectionType().
isReservedSectionType()
template<typename T> bool llvm::object::XCOFFSectionHeader< T >::isReservedSectionType () const
Definition at line 75 of file XCOFFObjectFile.cpp.
References getSectionType(), and SectionFlagsReservedMask.
Member Data Documentation
SectionFlagsReservedMask
template<typename T> unsigned llvm::object::XCOFFSectionHeader< T >::SectionFlagsReservedMask = 0x7 static constexpr
Definition at line 162 of file XCOFFObjectFile.h.
Referenced by isReservedSectionType().
SectionFlagsTypeMask
template<typename T> unsigned llvm::object::XCOFFSectionHeader< T >::SectionFlagsTypeMask = 0xffffu static constexpr
Definition at line 167 of file XCOFFObjectFile.h.
Referenced by getSectionSubtype(), and getSectionType().
The documentation for this struct was generated from the following files:
include/llvm/Object/XCOFFObjectFile.h
lib/Object/XCOFFObjectFile.cpp