LLVM: llvm::MIPatternMatch::Or< Pred, Preds... > Struct Template Reference
llvm::MIPatternMatch::Or< Pred, Preds... > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
Or (Pred &&p, Preds &&... preds)
template<typename MatchSrc>
bool match (const MachineRegisterInfo &MRI, MatchSrc &&src)
Public Member Functions inherited from llvm::MIPatternMatch::Or< Preds... >
bool match (const MachineRegisterInfo &MRI, MatchSrc &&src)
Public Attributes
Pred P
Detailed Description
template<typename Pred, typename... Preds>
struct llvm::MIPatternMatch::Or< Pred, Preds... >
Definition at line 341 of file MIPatternMatch.h.
Constructor & Destructor Documentation
Or()
template<typename Pred, typename... Preds> llvm::MIPatternMatch::Or< Pred, Preds... >::Or (Pred && p, Preds &&... preds) inline
Definition at line 343 of file MIPatternMatch.h.
References Or(), and P.
Referenced by Or().
Member Function Documentation
match()
template<typename Pred, typename... Preds> template<typename MatchSrc> bool llvm::MIPatternMatch::Or< Pred, Preds... >::match (const MachineRegisterInfo & MRI, MatchSrc && src) inline
Definition at line 346 of file MIPatternMatch.h.
References llvm::MIPatternMatch::Or< Preds >::match(), MRI, and P.
Member Data Documentation
P
template<typename Pred, typename... Preds> Pred llvm::MIPatternMatch::Or< Pred, Preds... >::P
Definition at line 342 of file MIPatternMatch.h.
Referenced by match(), and Or().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h