LLVM: llvm::memprof::IndexedCallstackIdConverter Struct Reference
llvm::memprof::IndexedCallstackIdConverter Struct Reference
#include "llvm/ProfileData/MemProfRadixTree.h"
Public Member Functions
IndexedCallstackIdConverter ()=delete
IndexedCallstackIdConverter (IndexedMemProfData &MemProfData)
IndexedCallstackIdConverter (const IndexedCallstackIdConverter &)=delete
IndexedCallstackIdConverter & operator= (const IndexedCallstackIdConverter &)=delete
std::vector< Frame > operator() (CallStackId CSId)
Public Attributes
FrameIdConverter< decltype(IndexedMemProfData::Frames)> FrameIdConv
CallStackIdConverter< decltype(IndexedMemProfData::CallStacks)> CSIdConv
Detailed Description
Definition at line 221 of file MemProfRadixTree.h.
Constructor & Destructor Documentation
IndexedCallstackIdConverter() [1/3]
llvm::memprof::IndexedCallstackIdConverter::IndexedCallstackIdConverter () delete
Referenced by IndexedCallstackIdConverter(), and operator=().
IndexedCallstackIdConverter() [2/3]
llvm::memprof::IndexedCallstackIdConverter::IndexedCallstackIdConverter (IndexedMemProfData & MemProfData) inline
Definition at line 223 of file MemProfRadixTree.h.
References CSIdConv, and FrameIdConv.
IndexedCallstackIdConverter() [3/3]
llvm::memprof::IndexedCallstackIdConverter::IndexedCallstackIdConverter (const IndexedCallstackIdConverter &) delete
References IndexedCallstackIdConverter().
Member Function Documentation
operator()()
std::vector< Frame > llvm::memprof::IndexedCallstackIdConverter::operator() (CallStackId CSId) inline
Definition at line 234 of file MemProfRadixTree.h.
References CSIdConv.
operator=()
IndexedCallstackIdConverter & llvm::memprof::IndexedCallstackIdConverter::operator= (const IndexedCallstackIdConverter &) delete
References IndexedCallstackIdConverter().
Member Data Documentation
CSIdConv
CallStackIdConverter<decltype(IndexedMemProfData::CallStacks)> llvm::memprof::IndexedCallstackIdConverter::CSIdConv
Definition at line 237 of file MemProfRadixTree.h.
Referenced by IndexedCallstackIdConverter(), and operator()().
FrameIdConv
FrameIdConverter<decltype(IndexedMemProfData::Frames)> llvm::memprof::IndexedCallstackIdConverter::FrameIdConv
Definition at line 236 of file MemProfRadixTree.h.
Referenced by IndexedCallstackIdConverter().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProfRadixTree.h