LLVM: llvm::yaml::MappingTraits< COFFYAML::Relocation > Struct Reference
llvm::yaml::MappingTraits< COFFYAML::Relocation > Struct Reference
#include "llvm/ObjectYAML/COFFYAML.h"
Static Public Member Functions
static void mapping (IO &IO, COFFYAML::Relocation &Rel)
Detailed Description
Definition at line 217 of file COFFYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< COFFYAML::Relocation >::mapping (IO & IO, COFFYAML::Relocation & Rel) static
Definition at line 434 of file COFFYAML.cpp.
References llvm::yaml::IO::getContext(), H, llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMAGE_FILE_MACHINE_R4000, llvm::COFF::isAnyArm64(), llvm::yaml::IO::mapOptional(), llvm::yaml::IO::mapRequired(), llvm::COFFYAML::Relocation::SymbolName, llvm::COFFYAML::Relocation::SymbolTableIndex, llvm::COFFYAML::Relocation::Type, and llvm::COFFYAML::Relocation::VirtualAddress.
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/COFFYAML.h
lib/ObjectYAML/COFFYAML.cpp