LLVM: llvm::ms_demangle::IntegerLiteralNode Struct Reference
llvm::ms_demangle::IntegerLiteralNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
IntegerLiteralNode ()
IntegerLiteralNode (uint64_t Value, bool IsNegative)
void output (OutputBuffer &OB, OutputFlags Flags) const override
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
DEMANGLE_ABI std::string toString (OutputFlags Flags=OF_Default) const
Static Public Member Functions
static bool classof (const Node *N)
Public Attributes
uint64_t Value = 0
bool IsNegative = false
Detailed Description
Definition at line 658 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
IntegerLiteralNode() [1/2]
llvm::ms_demangle::IntegerLiteralNode::IntegerLiteralNode () inline
Definition at line 659 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::Node::Node().
IntegerLiteralNode() [2/2]
llvm::ms_demangle::IntegerLiteralNode::IntegerLiteralNode (uint64_t Value, bool IsNegative) inline
Definition at line 660 of file MicrosoftDemangleNodes.h.
References IsNegative, llvm::ms_demangle::Node::Node(), and Value.
Member Function Documentation
classof()
bool llvm::ms_demangle::IntegerLiteralNode::classof (const Node * N) inline static
Definition at line 665 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::IntegerLiteral, N, and llvm::ms_demangle::Node::Node().
output()
void IntegerLiteralNode::output (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::Node.
Definition at line 195 of file MicrosoftDemangleNodes.cpp.
References IsNegative, and Value.
Referenced by llvm::ms_demangle::ArrayTypeNode::outputOneDimension().
Member Data Documentation
IsNegative
bool llvm::ms_demangle::IntegerLiteralNode::IsNegative = false
Definition at line 670 of file MicrosoftDemangleNodes.h.
Referenced by IntegerLiteralNode(), and output().
Value
uint64_t llvm::ms_demangle::IntegerLiteralNode::Value = 0
Definition at line 669 of file MicrosoftDemangleNodes.h.
Referenced by IntegerLiteralNode(), output(), and llvm::ms_demangle::ArrayTypeNode::outputOneDimension().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp