LLVM: llvm::memprof::Frame Struct Reference
llvm::memprof::Frame Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
Frame ()=default
Frame (const Frame &Other)
Frame (GlobalValue::GUID Hash, uint32_t Off, uint32_t Col, bool Inline)
bool operator== (const Frame &Other) const
Frame & operator= (const Frame &Other)
bool operator!= (const Frame &Other) const
bool hasSymbolName () const
StringRef getSymbolName () const
std::string getSymbolNameOr (StringRef Alt) const
void serialize (raw_ostream &OS) const
void printYAML (raw_ostream &OS) const
Static Public Member Functions
static Frame deserialize (const unsigned char *Ptr)
static constexpr size_t serializedSize ()
Public Attributes
GlobalValue::GUID Function = 0
std::unique_ptr< std::string > SymbolName
uint32_t LineOffset = 0
uint32_t Column = 0
bool IsInlineFrame = false
Detailed Description
Definition at line 242 of file MemProf.h.
Constructor & Destructor Documentation
Frame() [1/3]
llvm::memprof::Frame::Frame () default
Referenced by deserialize(), Frame(), operator!=(), operator=(), and operator==().
Frame() [2/3]
llvm::memprof::Frame::Frame (const Frame & Other) inline
Definition at line 258 of file MemProf.h.
References Column, Frame(), Function, IsInlineFrame, LineOffset, and SymbolName.
Frame() [3/3]
llvm::memprof::Frame::Frame (GlobalValue::GUID Hash, uint32_t Off, uint32_t Col, bool Inline) inline
Definition at line 268 of file MemProf.h.
References Column, Function, IsInlineFrame, and LineOffset.
Member Function Documentation
deserialize()
Frame llvm::memprof::Frame::deserialize (const unsigned char * Ptr) inline static
Definition at line 320 of file MemProf.h.
References llvm::CallingConv::C, F, Frame(), I, and llvm::support::endian::readNext().
Referenced by llvm::memprof::LinearFrameIdConverter::operator()(), and llvm::memprof::FrameLookupTrait::ReadData().
getSymbolName()
StringRef llvm::memprof::Frame::getSymbolName () const inline
Definition at line 293 of file MemProf.h.
References assert(), hasSymbolName(), and SymbolName.
getSymbolNameOr()
std::string llvm::memprof::Frame::getSymbolNameOr (StringRef Alt) const inline
Definition at line 298 of file MemProf.h.
References getSymbolName(), and hasSymbolName().
Referenced by printYAML().
hasSymbolName()
bool llvm::memprof::Frame::hasSymbolName () const inline
Definition at line 291 of file MemProf.h.
References SymbolName.
Referenced by getSymbolName(), and getSymbolNameOr().
operator!=()
bool llvm::memprof::Frame::operator!= (const Frame & Other) const inline
Definition at line 289 of file MemProf.h.
References Frame(), and operator==().
operator=()
Frame & llvm::memprof::Frame::operator= (const Frame & Other) inline
Definition at line 278 of file MemProf.h.
References Column, Frame(), Function, IsInlineFrame, LineOffset, and SymbolName.
operator==()
bool llvm::memprof::Frame::operator== (const Frame & Other) const inline
Definition at line 271 of file MemProf.h.
References Column, Frame(), Function, IsInlineFrame, and LineOffset.
printYAML()
void llvm::memprof::Frame::printYAML (raw_ostream & OS) const inline
Definition at line 341 of file MemProf.h.
References Column, Function, getSymbolNameOr(), IsInlineFrame, and LineOffset.
serialize()
void llvm::memprof::Frame::serialize (raw_ostream & OS) const inline
Definition at line 303 of file MemProf.h.
References Column, Function, IsInlineFrame, LineOffset, and llvm::little.
serializedSize()
constexpr size_t llvm::memprof::Frame::serializedSize () inline static constexpr
Definition at line 335 of file MemProf.h.
References Column, Function, IsInlineFrame, and LineOffset.
Referenced by llvm::memprof::LinearFrameIdConverter::operator()().
Member Data Documentation
Column
uint32_t llvm::memprof::Frame::Column = 0
Definition at line 253 of file MemProf.h.
Referenced by computeStackId(), Frame(), Frame(), operator=(), operator==(), printYAML(), serialize(), and serializedSize().
Function
GlobalValue::GUID llvm::memprof::Frame::Function = 0
Definition at line 245 of file MemProf.h.
Referenced by computeStackId(), Frame(), Frame(), operator=(), operator==(), printYAML(), serialize(), and serializedSize().
IsInlineFrame
bool llvm::memprof::Frame::IsInlineFrame = false
Definition at line 255 of file MemProf.h.
Referenced by Frame(), Frame(), operator=(), operator==(), printYAML(), serialize(), and serializedSize().
LineOffset
uint32_t llvm::memprof::Frame::LineOffset = 0
Definition at line 250 of file MemProf.h.
Referenced by computeStackId(), Frame(), Frame(), operator=(), operator==(), printYAML(), serialize(), and serializedSize().
SymbolName
std::unique_ptr<std::string> llvm::memprof::Frame::SymbolName
Definition at line 248 of file MemProf.h.
Referenced by Frame(), getSymbolName(), hasSymbolName(), and operator=().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h