LLVM: llvm::GraphTraits< MachineRegionInfoPass * > Struct Reference
llvm::GraphTraits< MachineRegionInfoPass * > Struct Reference
#include "llvm/CodeGen/MachineRegionInfo.h"
Public Types
using nodes_iterator
using NodeRef
Public Types inherited from llvm::GraphTraits< MachineRegionInfo * >
using nodes_iterator
using NodeRef
Public Types inherited from llvm::GraphTraits< FlatIt< MachineRegionNode * > >
using NodeRef
Static Public Member Functions
static NodeRef getEntryNode (MachineRegionInfoPass *RI)
static nodes_iterator nodes_begin (MachineRegionInfoPass *RI)
static nodes_iterator nodes_end (MachineRegionInfoPass *RI)
Static Public Member Functions inherited from llvm::GraphTraits< MachineRegionInfo * >
static NodeRef getEntryNode (MachineRegionInfo *RI)
static nodes_iterator nodes_begin (MachineRegionInfo *RI)
static nodes_iterator nodes_end (MachineRegionInfo *RI)
Detailed Description
Definition at line 157 of file MachineRegionInfo.h.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< MachineRegionInfoPass * >::NodeRef
Definition at line 95 of file GraphTraits.h.
nodes_iterator
using llvm::GraphTraits< MachineRegionInfoPass * >::nodes_iterator
Initial value:
df_iterator<NodeRef, df_iterator_default_set<NodeRef>,
                                    false, GraphTraits<FlatIt<NodeRef>>>
Definition at line 159 of file MachineRegionInfo.h.
Member Function Documentation
getEntryNode()
NodeRef llvm::GraphTraits< MachineRegionInfoPass * >::getEntryNode (MachineRegionInfoPass * RI) inline static
Definition at line 162 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
nodes_begin()
nodes_iterator llvm::GraphTraits< MachineRegionInfoPass * >::nodes_begin (MachineRegionInfoPass * RI) inline static
Definition at line 166 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
nodes_end()
nodes_iterator llvm::GraphTraits< MachineRegionInfoPass * >::nodes_end (MachineRegionInfoPass * RI) inline static
Definition at line 170 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineRegionInfo.h