LLVM: llvm::DomTreeNodeTraits< NodeT > Struct Template Reference
llvm::DomTreeNodeTraits< NodeT > Struct Template Reference
Default DomTreeNode traits for NodeT.
#include "llvm/Support/GenericDomTree.h"
Public Types
using NodeType = NodeT
using NodePtr = NodeT *
using ParentPtr = decltype(std::declval<NodePtr>()->getParent())
using ParentType = std::remove_pointer_t<ParentPtr>
Static Public Member Functions
static NodeT * getEntryNode (ParentPtr Parent)
static ParentPtr getParent (NodePtr BB)
Detailed Description
template<typename NodeT>
struct llvm::DomTreeNodeTraits< NodeT >
Default DomTreeNode traits for NodeT.
The default implementation assume a Function-like NodeT. Can be specialized to support different node types.
Definition at line 219 of file GenericDomTree.h.
Member Typedef Documentation
NodePtr
template<typename NodeT> using llvm::DomTreeNodeTraits< NodeT >::NodePtr = NodeT *
Definition at line 221 of file GenericDomTree.h.
NodeType
template<typename NodeT> using llvm::DomTreeNodeTraits< NodeT >::NodeType = NodeT
Definition at line 220 of file GenericDomTree.h.
ParentPtr
template<typename NodeT> using llvm::DomTreeNodeTraits< NodeT >::ParentPtr = decltype(std::declval<NodePtr>()->getParent())
Definition at line 222 of file GenericDomTree.h.
ParentType
template<typename NodeT> using llvm::DomTreeNodeTraits< NodeT >::ParentType = std::remove_pointer_t<ParentPtr>
Definition at line 225 of file GenericDomTree.h.
Member Function Documentation
getEntryNode()
template<typename NodeT> NodeT * llvm::DomTreeNodeTraits< NodeT >::getEntryNode (ParentPtr Parent) inline static
Definition at line 227 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator().
getParent()
template<typename NodeT> ParentPtr llvm::DomTreeNodeTraits< NodeT >::getParent (NodePtr BB) inline static
Definition at line 228 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT, false >::deleteEdge(), llvm::DominatorTreeBase< BlockT, false >::findNearestCommonDominator(), llvm::DominatorTreeBase< BlockT, false >::getNode(), and llvm::DominatorTreeBase< BlockT, false >::insertEdge().
The documentation for this struct was generated from the following file:
include/llvm/Support/GenericDomTree.h