LLVM: llvm::DomTreeGraphTraitsBase< Node, ChildIterator > Struct Template Reference
llvm::DomTreeGraphTraitsBase< Node, ChildIterator > Struct Template Reference
#include "llvm/IR/Dominators.h"
Public Types
using NodeRef = Node *
using ChildIteratorType = ChildIterator
using nodes_iterator = df_iterator<Node *, df_iterator_default_set<Node*>>
Static Public Member Functions
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static nodes_iterator nodes_begin (NodeRef N)
static nodes_iterator nodes_end (NodeRef N)
Detailed Description
template<class Node, class ChildIterator>
struct llvm::DomTreeGraphTraitsBase< Node, ChildIterator >
Definition at line 243 of file Dominators.h.
Member Typedef Documentation
ChildIteratorType
template<class Node, class ChildIterator> using llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::ChildIteratorType = ChildIterator
Definition at line 245 of file Dominators.h.
NodeRef
template<class Node, class ChildIterator> using llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::NodeRef = Node *
Definition at line 244 of file Dominators.h.
nodes_iterator
template<class Node, class ChildIterator> using llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::nodes_iterator = df_iterator<Node *, df_iterator_default_set<Node*>>
Definition at line 246 of file Dominators.h.
Member Function Documentation
child_begin()
template<class Node, class ChildIterator> ChildIteratorType llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::child_begin (NodeRef N) inline static
Definition at line 249 of file Dominators.h.
References N.
child_end()
template<class Node, class ChildIterator> ChildIteratorType llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::child_end (NodeRef N) inline static
Definition at line 250 of file Dominators.h.
References N.
getEntryNode()
template<class Node, class ChildIterator> NodeRef llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::getEntryNode (NodeRef N) inline static
Definition at line 248 of file Dominators.h.
References N.
Referenced by nodes_begin(), and nodes_end().
nodes_begin()
template<class Node, class ChildIterator> nodes_iterator llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::nodes_begin (NodeRef N) inline static
Definition at line 252 of file Dominators.h.
References llvm::df_begin(), getEntryNode(), and N.
nodes_end()
template<class Node, class ChildIterator> nodes_iterator llvm::DomTreeGraphTraitsBase< Node, ChildIterator >::nodes_end (NodeRef N) inline static
Definition at line 256 of file Dominators.h.
References llvm::df_end(), getEntryNode(), and N.
The documentation for this struct was generated from the following file:
include/llvm/IR/Dominators.h