LLVM: llvm::VPlanPatternMatch::bind_const_int Struct Reference
llvm::VPlanPatternMatch::bind_const_int Struct Reference
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
bind_const_int (uint64_t &Res)
bool match (VPValue *VPV) const
Public Attributes
uint64_t & Res
Detailed Description
Definition at line 200 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
bind_const_int()
llvm::VPlanPatternMatch::bind_const_int::bind_const_int (uint64_t & Res) inline
Definition at line 203 of file VPlanPatternMatch.h.
References Res.
Member Function Documentation
match()
bool llvm::VPlanPatternMatch::bind_const_int::match (VPValue * VPV) const inline
Definition at line 205 of file VPlanPatternMatch.h.
References llvm::CallingConv::C, match(), Res, and llvm::APInt::tryZExtValue().
Referenced by match().
Member Data Documentation
Res
uint64_t& llvm::VPlanPatternMatch::bind_const_int::Res
Definition at line 201 of file VPlanPatternMatch.h.
Referenced by bind_const_int(), and match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h