LLVM: llvm::object::CompressedOffloadBundle::CompressedBundleHeader Struct Reference
llvm::object::CompressedOffloadBundle::CompressedBundleHeader Struct Reference
#include "llvm/Object/OffloadBundle.h"
Static Public Member Functions
static llvm::Expected< CompressedBundleHeader > tryParse (llvm::StringRef)
Public Attributes
unsigned Version
llvm::compression::Format CompressionFormat
std::optional< size_t > FileSize
size_t UncompressedFileSize
uint64_t Hash
Detailed Description
Definition at line 52 of file OffloadBundle.h.
Member Function Documentation
tryParse()
Expected< CompressedOffloadBundle::CompressedBundleHeader > CompressedOffloadBundle::CompressedBundleHeader::tryParse (llvm::StringRef Blob) static
Definition at line 462 of file OffloadBundle.cpp.
References assert(), CompressionFormat, llvm::createStringError(), llvm::StringRef::data(), FileSize, getHeaderSize(), Hash, llvm::identify_magic(), llvm::file_magic::offload_bundle_compressed, llvm::StringRef::size(), UncompressedFileSize, Version, llvm::compression::Zlib, and llvm::compression::Zstd.
Referenced by llvm::object::CompressedOffloadBundle::decompress().
Member Data Documentation
CompressionFormat
llvm::compression::Format llvm::object::CompressedOffloadBundle::CompressedBundleHeader::CompressionFormat
Definition at line 54 of file OffloadBundle.h.
Referenced by llvm::object::CompressedOffloadBundle::decompress(), and tryParse().
FileSize
std::optional<size_t> llvm::object::CompressedOffloadBundle::CompressedBundleHeader::FileSize
Definition at line 55 of file OffloadBundle.h.
Referenced by llvm::object::CompressedOffloadBundle::decompress(), and tryParse().
Hash
uint64_t llvm::object::CompressedOffloadBundle::CompressedBundleHeader::Hash
Definition at line 57 of file OffloadBundle.h.
Referenced by llvm::object::CompressedOffloadBundle::decompress(), and tryParse().
UncompressedFileSize
size_t llvm::object::CompressedOffloadBundle::CompressedBundleHeader::UncompressedFileSize
Definition at line 56 of file OffloadBundle.h.
Referenced by llvm::object::CompressedOffloadBundle::decompress(), and tryParse().
Version
unsigned llvm::object::CompressedOffloadBundle::CompressedBundleHeader::Version
Definition at line 53 of file OffloadBundle.h.
Referenced by llvm::object::CompressedOffloadBundle::decompress(), and tryParse().
The documentation for this struct was generated from the following files:
include/llvm/Object/OffloadBundle.h
lib/Object/OffloadBundle.cpp