LLVM: llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false > Struct Template Reference
llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false > Struct Template Reference
#include "llvm/Object/ELFTypes.h"
Public Member Functions
uint64_t getRInfo (bool isMips64EL) const
void setRInfo (uint64_t R, bool IsMips64EL)
uint32_t getSymbol (bool isMips64EL) const
uint32_t getType (bool isMips64EL) const
void setSymbol (uint32_t s, bool IsMips64EL)
void setType (uint32_t t, bool IsMips64EL)
void setSymbolAndType (uint32_t s, uint32_t t, bool IsMips64EL)
Public Attributes
Elf_Addr r_offset
Elf_Xword r_info
Static Public Attributes
static const bool HasAddend = false
static const bool IsCrel = false
Detailed Description
template<endianness Endianness>
struct llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >
Definition at line 434 of file ELFTypes.h.
Member Function Documentation
getRInfo()
template<endianness Endianness> uint64_t llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::getRInfo (bool isMips64EL) const inline
Definition at line 441 of file ELFTypes.h.
References getRInfo(), isMips64EL(), and r_info.
Referenced by getRInfo(), getSymbol(), and getType().
getSymbol()
template<endianness Endianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::getSymbol (bool isMips64EL) const inline
Definition at line 462 of file ELFTypes.h.
References getRInfo(), and isMips64EL().
Referenced by setType().
getType()
template<endianness Endianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::getType (bool isMips64EL) const inline
Definition at line 465 of file ELFTypes.h.
References getRInfo(), and isMips64EL().
setRInfo()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::setRInfo (uint64_t R, bool IsMips64EL) inline
Definition at line 452 of file ELFTypes.h.
References r_info.
Referenced by setSymbolAndType().
setSymbol()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::setSymbol (uint32_t s, bool IsMips64EL) inline
Definition at line 468 of file ELFTypes.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::setSymbolAndType (uint32_t s, uint32_t t, bool IsMips64EL) inline
Definition at line 474 of file ELFTypes.h.
References setRInfo().
Referenced by setSymbol(), and setType().
setType()
template<endianness Endianness> void llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::setType (uint32_t t, bool IsMips64EL) inline
Definition at line 471 of file ELFTypes.h.
References getSymbol(), and setSymbolAndType().
Member Data Documentation
HasAddend
template<endianness Endianness> const bool llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::HasAddend = false static
Definition at line 436 of file ELFTypes.h.
IsCrel
template<endianness Endianness> const bool llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::IsCrel = false static
Definition at line 437 of file ELFTypes.h.
r_info
template<endianness Endianness> Elf_Xword llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::r_info
Definition at line 439 of file ELFTypes.h.
Referenced by getRInfo(), and setRInfo().
r_offset
template<endianness Endianness> Elf_Addr llvm::object::Elf_Rel_Impl< ELFType< Endianness, true >, false >::r_offset
Definition at line 438 of file ELFTypes.h.
The documentation for this struct was generated from the following file:
include/llvm/Object/ELFTypes.h