LLVM: llvm::dxil::ModuleShaderFlags Struct Reference
llvm::dxil::ModuleShaderFlags Struct Reference
#include "Target/DirectX/DXILShaderFlags.h"
Public Member Functions
void initialize (Module &, DXILResourceTypeMap &DRTM, const DXILResourceMap &DRM, const ModuleMetadataInfo &MMDI)
Construct ModuleShaderFlags for module Module M.
const ComputedShaderFlags & getFunctionFlags (const Function *) const
Return the shader flags mask of the specified function Func.
const ComputedShaderFlags & getCombinedFlags () const
Detailed Description
Definition at line 86 of file DXILShaderFlags.h.
Member Function Documentation
getCombinedFlags()
const ComputedShaderFlags & llvm::dxil::ModuleShaderFlags::getCombinedFlags () const inline
Definition at line 90 of file DXILShaderFlags.h.
Referenced by llvm::dxil::ShaderFlagsAnalysisPrinter::run().
getFunctionFlags()
const ComputedShaderFlags & ModuleShaderFlags::getFunctionFlags (const Function * Func) const
Return the shader flags mask of the specified function Func.
Definition at line 382 of file DXILShaderFlags.cpp.
References assert().
Referenced by llvm::dxil::ShaderFlagsAnalysisPrinter::run().
initialize()
void ModuleShaderFlags::initialize (Module & M, DXILResourceTypeMap & DRTM, const DXILResourceMap & DRM, const ModuleMetadataInfo & MMDI)
Construct ModuleShaderFlags for module Module M.
Definition at line 301 of file DXILShaderFlags.cpp.
References assert(), llvm::dxil::ModuleMetadataInfo::DXILVersion, llvm::mdconst::extract_or_null(), F, I, llvm::scc_iterator< GraphT, GT >::isAtEnd(), llvm::dxil::ComputedShaderFlags::merge(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::scc_begin().
Referenced by llvm::dxil::ShaderFlagsAnalysis::run().
The documentation for this struct was generated from the following files:
lib/Target/DirectX/DXILShaderFlags.h
lib/Target/DirectX/DXILShaderFlags.cpp