LLVM: llvm::NamedRegionTimer Struct Reference
llvm::NamedRegionTimer Struct Reference
This class is basically a combination of TimeRegion and Timer.
#include "llvm/Support/Timer.h"
Public Member Functions
LLVM_ABI NamedRegionTimer (StringRef Name, StringRef Description, StringRef GroupName, StringRef GroupDescription, bool Enabled=true)
Public Member Functions inherited from llvm::TimeRegion
TimeRegion (Timer &t)
TimeRegion (Timer *t)
~TimeRegion ()
Static Public Member Functions
static LLVM_ABI TimerGroup & getNamedTimerGroup (StringRef GroupName, StringRef GroupDescription)
Detailed Description
This class is basically a combination of TimeRegion and Timer.
It allows you to declare a new timer, AND specify the region to time, all in one statement. All timers with the same name are merged. This is primarily used for debugging and for hunting performance problems.
Definition at line 175 of file Timer.h.
Constructor & Destructor Documentation
NamedRegionTimer()
NamedRegionTimer::NamedRegionTimer (StringRef Name, StringRef Description, StringRef GroupName, StringRef GroupDescription, bool Enabled = true) explicit
Definition at line 252 of file Timer.cpp.
References llvm::Enabled, llvm::get(), namedGroupedTimers(), and nullptr.
Member Function Documentation
getNamedTimerGroup()
TimerGroup & NamedRegionTimer::getNamedTimerGroup (StringRef GroupName, StringRef GroupDescription) static
Definition at line 260 of file Timer.cpp.
References namedGroupedTimers().
The documentation for this struct was generated from the following files:
include/llvm/Support/Timer.h
lib/Support/Timer.cpp