LLVM: llvm::DenseMapInfo< at::VarRecord > Struct Reference
llvm::DenseMapInfo< at::VarRecord > Struct Reference
#include "llvm/IR/DebugInfo.h"
Static Public Member Functions
static at::VarRecord getEmptyKey ()
static at::VarRecord getTombstoneKey ()
static unsigned getHashValue (const at::VarRecord &Var)
static bool isEqual (const at::VarRecord &A, const at::VarRecord &B)
Detailed Description
Definition at line 253 of file DebugInfo.h.
Member Function Documentation
getEmptyKey()
at::VarRecord llvm::DenseMapInfo< at::VarRecord >::getEmptyKey () inline static
Definition at line 254 of file DebugInfo.h.
getHashValue()
unsigned llvm::DenseMapInfo< at::VarRecord >::getHashValue (const at::VarRecord & Var) inline static
Definition at line 264 of file DebugInfo.h.
References llvm::at::VarRecord::DL, llvm::hash_combine(), and llvm::at::VarRecord::Var.
getTombstoneKey()
at::VarRecord llvm::DenseMapInfo< at::VarRecord >::getTombstoneKey () inline static
Definition at line 259 of file DebugInfo.h.
isEqual()
bool llvm::DenseMapInfo< at::VarRecord >::isEqual (const at::VarRecord & A, const at::VarRecord & B) inline static
Definition at line 268 of file DebugInfo.h.
References A(), and B().
The documentation for this struct was generated from the following file:
include/llvm/IR/DebugInfo.h