LLVM: llvm::memprof::PortableMemInfoBlock Struct Reference
llvm::memprof::PortableMemInfoBlock Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
PortableMemInfoBlock ()=default
PortableMemInfoBlock (const MemInfoBlock &Block, const MemProfSchema &IncomingSchema)
PortableMemInfoBlock (const MemProfSchema &Schema, const unsigned char *Ptr)
void deserialize (const MemProfSchema &IncomingSchema, const unsigned char *Ptr)
void serialize (const MemProfSchema &Schema, raw_ostream &OS) const
void printYAML (raw_ostream &OS) const
std::bitset< llvm::to_underlying(Meta::Size)> getSchema () const
MIBEntryDef (AllocCount=1, AllocCount, uint32_t) MIBEntryDef(TotalAccessCount
uint64_t MIBEntryDef (MinAccessCount=3, MinAccessCount, uint64_t) MIBEntryDef(MaxAccessCount
uint64_t uint64_t MIBEntryDef (TotalSize=5, TotalSize, uint64_t) MIBEntryDef(MinSize
uint64_t uint64_t uint32_t MIBEntryDef (MaxSize=7, MaxSize, uint32_t) MIBEntryDef(AllocTimestamp
uint64_t uint64_t uint32_t uint32_t MIBEntryDef (DeallocTimestamp=9, DeallocTimestamp, uint32_t) MIBEntryDef(TotalLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t MIBEntryDef (MinLifetime=11, MinLifetime, uint32_t) MIBEntryDef(MaxLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t MIBEntryDef (AllocCpuId=13, AllocCpuId, uint32_t) MIBEntryDef(DeallocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t MIBEntryDef (NumMigratedCpu=15, NumMigratedCpu, uint32_t) MIBEntryDef(NumLifetimeOverlaps
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t MIBEntryDef (NumSameAllocCpu=17, NumSameAllocCpu, uint32_t) MIBEntryDef(NumSameDeallocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t MIBEntryDef (DataTypeId=19, DataTypeId, uint64_t) MIBEntryDef(TotalAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t MIBEntryDef (MinAccessDensity=21, MinAccessDensity, uint32_t) MIBEntryDef(MaxAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t MIBEntryDef (TotalLifetimeAccessDensity=23, TotalLifetimeAccessDensity, uint64_t) MIBEntryDef(MinLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t MIBEntryDef (MaxLifetimeAccessDensity=25, MaxLifetimeAccessDensity, uint32_t) MIBEntryDef(AccessHistogramSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t MIBEntryDef (AccessHistogram=27, AccessHistogram, uintptr_t) MIBEntryDef(AllocCount
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t MIBEntryDef (TotalAccessCount=2, TotalAccessCount, uint64_t) MIBEntryDef(MinAccessCount
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t MIBEntryDef (MaxAccessCount=4, MaxAccessCount, uint64_t) MIBEntryDef(TotalSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t MIBEntryDef (MinSize=6, MinSize, uint32_t) MIBEntryDef(MaxSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t MIBEntryDef (AllocTimestamp=8, AllocTimestamp, uint32_t) MIBEntryDef(DeallocTimestamp
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t MIBEntryDef (TotalLifetime=10, TotalLifetime, uint64_t) MIBEntryDef(MinLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t MIBEntryDef (MaxLifetime=12, MaxLifetime, uint32_t) MIBEntryDef(AllocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t MIBEntryDef (DeallocCpuId=14, DeallocCpuId, uint32_t) MIBEntryDef(NumMigratedCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t MIBEntryDef (NumLifetimeOverlaps=16, NumLifetimeOverlaps, uint32_t) MIBEntryDef(NumSameAllocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t MIBEntryDef (NumSameDeallocCpu=18, NumSameDeallocCpu, uint32_t) MIBEntryDef(DataTypeId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t MIBEntryDef (TotalAccessDensity=20, TotalAccessDensity, uint64_t) MIBEntryDef(MinAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t MIBEntryDef (MaxAccessDensity=22, MaxAccessDensity, uint32_t) MIBEntryDef(TotalLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t MIBEntryDef (MinLifetimeAccessDensity=24, MinLifetimeAccessDensity, uint32_t) MIBEntryDef(MaxLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t uint32_t MIBEntryDef (AccessHistogramSize=26, AccessHistogramSize, uint32_t) MIBEntryDef(AccessHistogram
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t uint32_t uintptr_t void clear ()
bool operator== (const PortableMemInfoBlock &Other) const
bool operator!= (const PortableMemInfoBlock &Other) const
Static Public Member Functions
static size_t serializedSize (const MemProfSchema &Schema)
Public Attributes
TotalAccessCount
uint64_t MaxAccessCount
uint64_t uint64_t MinSize
uint64_t uint64_t uint32_t AllocTimestamp
uint64_t uint64_t uint32_t uint32_t TotalLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t MaxLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t DeallocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t NumLifetimeOverlaps
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t NumSameDeallocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t TotalAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t MaxAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t MinLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t AccessHistogramSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t AllocCount
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t MinAccessCount
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t TotalSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t MaxSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t DeallocTimestamp
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t MinLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t AllocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t NumMigratedCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t NumSameAllocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t DataTypeId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t MinAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t TotalLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t MaxLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t uint32_t AccessHistogram
Friends
struct yaml::CustomMappingTraits< memprof::PortableMemInfoBlock >
Detailed Description
Definition at line 87 of file MemProf.h.
Constructor & Destructor Documentation
PortableMemInfoBlock() [1/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock () default
Referenced by clear(), operator!=(), and operator==().
PortableMemInfoBlock() [2/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock (const MemInfoBlock & Block, const MemProfSchema & IncomingSchema) inline explicit
Definition at line 89 of file MemProf.h.
References llvm::to_underlying().
PortableMemInfoBlock() [3/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock (const MemProfSchema & Schema, const unsigned char * Ptr) inline
Definition at line 98 of file MemProf.h.
Member Function Documentation
clear()
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t uint32_t uintptr_t void llvm::memprof::PortableMemInfoBlock::clear () inline
Definition at line 185 of file MemProf.h.
References PortableMemInfoBlock().
deserialize()
void llvm::memprof::PortableMemInfoBlock::deserialize (const MemProfSchema & IncomingSchema, const unsigned char * Ptr) inline
Definition at line 104 of file MemProf.h.
getSchema()
std::bitset< llvm::to_underlying(Meta::Size)> llvm::memprof::PortableMemInfoBlock::getSchema () const inline
Definition at line 163 of file MemProf.h.
Referenced by llvm::yaml::CustomMappingTraits< memprof::PortableMemInfoBlock >::output().
MIBEntryDef() [1/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AccessHistogram = 27, AccessHistogram , uintptr_t)
References llvm::memprof::MaximumSupportedVersion, and llvm::memprof::MinimumSupportedVersion.
MIBEntryDef() [2/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AccessHistogramSize = 26, AccessHistogramSize , uint32_t)
MIBEntryDef() [3/27]
llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AllocCount = 1, AllocCount , uint32_t)
MIBEntryDef() [4/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AllocCpuId = 13, AllocCpuId , uint32_t)
MIBEntryDef() [5/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AllocTimestamp = 8, AllocTimestamp , uint32_t)
MIBEntryDef() [6/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (DataTypeId = 19, DataTypeId , uint64_t)
MIBEntryDef() [7/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (DeallocCpuId = 14, DeallocCpuId , uint32_t)
MIBEntryDef() [8/27]
uint64_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (DeallocTimestamp = 9, DeallocTimestamp , uint32_t)
MIBEntryDef() [9/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MaxAccessCount = 4, MaxAccessCount , uint64_t)
MIBEntryDef() [10/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MaxAccessDensity = 22, MaxAccessDensity , uint32_t)
MIBEntryDef() [11/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MaxLifetime = 12, MaxLifetime , uint32_t)
MIBEntryDef() [12/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MaxLifetimeAccessDensity = 25, MaxLifetimeAccessDensity , uint32_t)
MIBEntryDef() [13/27]
uint64_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MaxSize = 7, MaxSize , uint32_t)
MIBEntryDef() [14/27]
uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinAccessCount = 3, MinAccessCount , uint64_t)
MIBEntryDef() [15/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinAccessDensity = 21, MinAccessDensity , uint32_t)
MIBEntryDef() [16/27]
uint64_t uint64_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinLifetime = 11, MinLifetime , uint32_t)
MIBEntryDef() [17/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinLifetimeAccessDensity = 24, MinLifetimeAccessDensity , uint32_t)
MIBEntryDef() [18/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinSize = 6, MinSize , uint32_t)
MIBEntryDef() [19/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (NumLifetimeOverlaps = 16, NumLifetimeOverlaps , uint32_t)
MIBEntryDef() [20/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (NumMigratedCpu = 15, NumMigratedCpu , uint32_t)
References llvm::memprof::Version2.
MIBEntryDef() [21/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (NumSameAllocCpu = 17, NumSameAllocCpu , uint32_t)
MIBEntryDef() [22/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (NumSameDeallocCpu = 18, NumSameDeallocCpu , uint32_t)
MIBEntryDef() [23/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (TotalAccessCount = 2, TotalAccessCount , uint64_t)
MIBEntryDef() [24/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (TotalAccessDensity = 20, TotalAccessDensity , uint64_t)
MIBEntryDef() [25/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (TotalLifetime = 10, TotalLifetime , uint64_t)
MIBEntryDef() [26/27]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (TotalLifetimeAccessDensity = 23, TotalLifetimeAccessDensity , uint64_t)
References llvm::memprof::MinimumSupportedVersion, and llvm::memprof::Version2.
MIBEntryDef() [27/27]
uint64_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (TotalSize = 5, TotalSize , uint64_t)
operator!=()
bool llvm::memprof::PortableMemInfoBlock::operator!= (const PortableMemInfoBlock & Other) const inline
Definition at line 200 of file MemProf.h.
References operator==(), llvm::Other, and PortableMemInfoBlock().
operator==()
bool llvm::memprof::PortableMemInfoBlock::operator== (const PortableMemInfoBlock & Other) const inline
Definition at line 187 of file MemProf.h.
References llvm::Other, and PortableMemInfoBlock().
Referenced by operator!=().
printYAML()
void llvm::memprof::PortableMemInfoBlock::printYAML (raw_ostream & OS) const inline
Definition at line 147 of file MemProf.h.
References AccessHistogram, AccessHistogramSize, and I.
serialize()
void llvm::memprof::PortableMemInfoBlock::serialize (const MemProfSchema & Schema, raw_ostream & OS) const inline
Definition at line 128 of file MemProf.h.
References llvm::little, and llvm_unreachable.
serializedSize()
size_t llvm::memprof::PortableMemInfoBlock::serializedSize (const MemProfSchema & Schema) inline static
Definition at line 204 of file MemProf.h.
References llvm_unreachable.
Referenced by llvm::memprof::deserializeV2(), llvm::memprof::deserializeV3(), llvm::memprof::deserializeV4(), llvm::memprof::serializedSizeV2(), and llvm::memprof::serializedSizeV3().
Friends And Related Symbol Documentation
yaml::CustomMappingTraits< memprof::PortableMemInfoBlock >
friend struct yaml::CustomMappingTraits< memprof::PortableMemInfoBlock > friend
Definition at line 204 of file MemProf.h.
Member Data Documentation
AccessHistogram
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::AccessHistogram
Definition at line 121 of file MemProf.h.
Referenced by printYAML().
AccessHistogramSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::AccessHistogramSize
Definition at line 55 of file MemProf.h.
Referenced by printYAML().
AllocCount
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::AllocCount
Definition at line 95 of file MemProf.h.
AllocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::AllocCpuId
Definition at line 107 of file MemProf.h.
AllocTimestamp
uint64_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::AllocTimestamp
Definition at line 37 of file MemProf.h.
DataTypeId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::DataTypeId
Definition at line 113 of file MemProf.h.
DeallocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::DeallocCpuId
Definition at line 43 of file MemProf.h.
DeallocTimestamp
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::DeallocTimestamp
Definition at line 103 of file MemProf.h.
MaxAccessCount
uint64_t llvm::memprof::PortableMemInfoBlock::MaxAccessCount
Definition at line 33 of file MemProf.h.
MaxAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MaxAccessDensity
Definition at line 51 of file MemProf.h.
MaxLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MaxLifetime
Definition at line 41 of file MemProf.h.
MaxLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MaxLifetimeAccessDensity
Definition at line 119 of file MemProf.h.
MaxSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t llvm::memprof::PortableMemInfoBlock::MaxSize
Definition at line 101 of file MemProf.h.
MinAccessCount
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MinAccessCount
Definition at line 97 of file MemProf.h.
MinAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MinAccessDensity
Definition at line 115 of file MemProf.h.
MinLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MinLifetime
Definition at line 105 of file MemProf.h.
MinLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MinLifetimeAccessDensity
Definition at line 53 of file MemProf.h.
MinSize
uint64_t uint64_t llvm::memprof::PortableMemInfoBlock::MinSize
Definition at line 35 of file MemProf.h.
NumLifetimeOverlaps
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::NumLifetimeOverlaps
Definition at line 45 of file MemProf.h.
NumMigratedCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::NumMigratedCpu
Definition at line 109 of file MemProf.h.
NumSameAllocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::NumSameAllocCpu
Definition at line 111 of file MemProf.h.
NumSameDeallocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::NumSameDeallocCpu
Definition at line 47 of file MemProf.h.
TotalAccessCount
llvm::memprof::PortableMemInfoBlock::TotalAccessCount
Definition at line 31 of file MemProf.h.
TotalAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::TotalAccessDensity
Definition at line 49 of file MemProf.h.
TotalLifetime
uint64_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::TotalLifetime
Definition at line 39 of file MemProf.h.
TotalLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint64_t uint32_t uint32_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::TotalLifetimeAccessDensity
Definition at line 117 of file MemProf.h.
TotalSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::TotalSize
Definition at line 99 of file MemProf.h.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h