LLVM: llvm::Pattern::MatchResult Struct Reference
llvm::Pattern::MatchResult Struct Reference
#include "FileCheck/FileCheckImpl.h"
Public Member Functions
MatchResult (size_t MatchPos, size_t MatchLen, Error E)
MatchResult (Match M, Error E)
MatchResult (Error E)
Public Attributes
std::optional< Match > TheMatch
Error TheError
Detailed Description
Definition at line 713 of file FileCheckImpl.h.
Constructor & Destructor Documentation
MatchResult() [1/3]
llvm::Pattern::MatchResult::MatchResult (size_t MatchPos, size_t MatchLen, Error E) inline
Definition at line 716 of file FileCheckImpl.h.
References E(), llvm::move(), TheError, and TheMatch.
MatchResult() [2/3]
llvm::Pattern::MatchResult::MatchResult (Match M, Error E) inline
Definition at line 718 of file FileCheckImpl.h.
References E(), llvm::move(), TheError, and TheMatch.
MatchResult() [3/3]
llvm::Pattern::MatchResult::MatchResult (Error E) inline
Definition at line 719 of file FileCheckImpl.h.
References E(), llvm::move(), and TheError.
Member Data Documentation
TheError
Error llvm::Pattern::MatchResult::TheError
Definition at line 715 of file FileCheckImpl.h.
Referenced by llvm::FileCheckString::CheckDag(), MatchResult(), MatchResult(), MatchResult(), printMatch(), and reportMatchResult().
TheMatch
std::optional<Match> llvm::Pattern::MatchResult::TheMatch
Definition at line 714 of file FileCheckImpl.h.
Referenced by llvm::FileCheckString::Check(), llvm::FileCheckString::CheckDag(), MatchResult(), MatchResult(), printMatch(), and reportMatchResult().
The documentation for this struct was generated from the following file:
lib/FileCheck/FileCheckImpl.h