LLVM: llvm::memprof::LineLocation Struct Reference
llvm::memprof::LineLocation Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
LineLocation (uint32_t L, uint32_t D)
bool operator< (const LineLocation &O) const
bool operator== (const LineLocation &O) const
bool operator!= (const LineLocation &O) const
uint64_t getHashCode () const
Public Attributes
uint32_t LineOffset
uint32_t Column
Detailed Description
Definition at line 832 of file MemProf.h.
Constructor & Destructor Documentation
LineLocation()
llvm::memprof::LineLocation::LineLocation (uint32_t L, uint32_t D) inline
Definition at line 833 of file MemProf.h.
References Column, D(), and LineOffset.
Referenced by operator!=(), operator<(), and operator==().
Member Function Documentation
getHashCode()
uint64_t llvm::memprof::LineLocation::getHashCode () const inline
Definition at line 847 of file MemProf.h.
References Column, and LineOffset.
operator!=()
bool llvm::memprof::LineLocation::operator!= (const LineLocation & O) const inline
Definition at line 843 of file MemProf.h.
References Column, LineLocation(), and LineOffset.
operator<()
bool llvm::memprof::LineLocation::operator< (const LineLocation & O) const inline
Definition at line 835 of file MemProf.h.
References Column, LineLocation(), and LineOffset.
operator==()
bool llvm::memprof::LineLocation::operator== (const LineLocation & O) const inline
Definition at line 839 of file MemProf.h.
References Column, LineLocation(), and LineOffset.
Member Data Documentation
Column
uint32_t llvm::memprof::LineLocation::Column
Definition at line 850 of file MemProf.h.
Referenced by getHashCode(), LineLocation(), operator!=(), operator<(), and operator==().
LineOffset
uint32_t llvm::memprof::LineLocation::LineOffset
Definition at line 849 of file MemProf.h.
Referenced by getHashCode(), LineLocation(), operator!=(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h