LLVM: llvm::MCDwarfLineTableHeader Struct Reference
llvm::MCDwarfLineTableHeader Struct Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
MCDwarfLineTableHeader ()=default
LLVM_ABI Expected< unsigned > tryGetFile (StringRef &Directory, StringRef &FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber=0)
LLVM_ABI std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS, MCDwarfLineTableParams Params, std::optional< MCDwarfLineStr > &LineStr) const
LLVM_ABI std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS, MCDwarfLineTableParams Params, ArrayRef< char > SpecialOpcodeLengths, std::optional< MCDwarfLineStr > &LineStr) const
void resetMD5Usage ()
void trackMD5Usage (bool MD5Used)
bool isMD5UsageConsistent () const
void setRootFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source)
void resetFileTable ()
Public Attributes
MCSymbol * Label = nullptr
SmallVector< std::string, 3 > MCDwarfDirs
SmallVector< MCDwarfFile, 3 > MCDwarfFiles
StringMap< unsigned > SourceIdMap
std::string CompilationDir
MCDwarfFile RootFile
bool HasAnySource = false
Detailed Description
Definition at line 278 of file MCDwarf.h.
Constructor & Destructor Documentation
MCDwarfLineTableHeader()
llvm::MCDwarfLineTableHeader::MCDwarfLineTableHeader () default
References LLVM_ABI.
Member Function Documentation
Emit() [1/2]
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS, MCDwarfLineTableParams Params, ArrayRef< char > SpecialOpcodeLengths, std::optional< MCDwarfLineStr > & LineStr) const
Definition at line 550 of file MCDwarf.cpp.
References llvm::MCContext::createTempSymbol(), DWARF2_LINE_DEFAULT_IS_STMT, llvm::MCDwarfLineTableParams::DWARF2LineBase, llvm::MCDwarfLineTableParams::DWARF2LineRange, llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitDwarfLineStartLabel(), llvm::MCStreamer::emitDwarfUnitLength(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfFormat(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::MCContext::getDwarfVersion(), llvm::MCAsmInfo::getMinInstAlignment(), Label, llvm::Length, and llvm::ArrayRef< T >::size().
Emit() [2/2]
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS, MCDwarfLineTableParams Params, std::optional< MCDwarfLineStr > & LineStr) const
Definition at line 345 of file MCDwarf.cpp.
References llvm::ArrayRef(), assert(), llvm::MCDwarfLineTableParams::DWARF2LineOpcodeBase, and Emit().
Referenced by Emit().
isMD5UsageConsistent()
bool llvm::MCDwarfLineTableHeader::isMD5UsageConsistent () const inline
Definition at line 315 of file MCDwarf.h.
References MCDwarfFiles.
resetFileTable()
void llvm::MCDwarfLineTableHeader::resetFileTable () inline
Definition at line 331 of file MCDwarf.h.
References HasAnySource, MCDwarfDirs, MCDwarfFiles, resetMD5Usage(), and RootFile.
resetMD5Usage()
void llvm::MCDwarfLineTableHeader::resetMD5Usage () inline
Definition at line 307 of file MCDwarf.h.
Referenced by resetFileTable().
setRootFile()
void llvm::MCDwarfLineTableHeader::setRootFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source) inline
Definition at line 319 of file MCDwarf.h.
References CompilationDir, HasAnySource, RootFile, and trackMD5Usage().
trackMD5Usage()
void llvm::MCDwarfLineTableHeader::trackMD5Usage (bool MD5Used) inline
Definition at line 311 of file MCDwarf.h.
Referenced by setRootFile(), and tryGetFile().
tryGetFile()
Expected< unsigned > MCDwarfLineTableHeader::tryGetFile (StringRef & Directory, StringRef & FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber = 0)
Definition at line 648 of file MCDwarf.cpp.
References assert(), CompilationDir, llvm::StringRef::empty(), llvm::sys::path::filename(), llvm::find(), HasAnySource, llvm::inconvertibleErrorCode(), isRootFile(), llvm::make_error(), MCDwarfDirs, MCDwarfFiles, llvm::sys::path::parent_path(), RootFile, SourceIdMap, and trackMD5Usage().
Member Data Documentation
CompilationDir
std::string llvm::MCDwarfLineTableHeader::CompilationDir
Definition at line 283 of file MCDwarf.h.
Referenced by setRootFile(), and tryGetFile().
HasAnySource
bool llvm::MCDwarfLineTableHeader::HasAnySource = false
Definition at line 285 of file MCDwarf.h.
Referenced by resetFileTable(), setRootFile(), and tryGetFile().
Label
MCSymbol* llvm::MCDwarfLineTableHeader::Label = nullptr
Definition at line 279 of file MCDwarf.h.
Referenced by Emit().
MCDwarfDirs
SmallVector<std::string, 3> llvm::MCDwarfLineTableHeader::MCDwarfDirs
Definition at line 280 of file MCDwarf.h.
Referenced by resetFileTable(), and tryGetFile().
MCDwarfFiles
SmallVector<MCDwarfFile, 3> llvm::MCDwarfLineTableHeader::MCDwarfFiles
Definition at line 281 of file MCDwarf.h.
Referenced by isMD5UsageConsistent(), resetFileTable(), and tryGetFile().
RootFile
MCDwarfFile llvm::MCDwarfLineTableHeader::RootFile
Definition at line 284 of file MCDwarf.h.
Referenced by resetFileTable(), setRootFile(), and tryGetFile().
SourceIdMap
StringMap<unsigned> llvm::MCDwarfLineTableHeader::SourceIdMap
Definition at line 282 of file MCDwarf.h.
Referenced by tryGetFile().
The documentation for this struct was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp