LLVM: llvm::SDPatternMatch::And< Pred, Preds... > Struct Template Reference
llvm::SDPatternMatch::And< Pred, Preds... > Struct Template Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Member Functions
And (const Pred &p, const Preds &...preds)
template<typename MatchContext>
bool match (const MatchContext &Ctx, SDValue N)
Public Member Functions inherited from llvm::SDPatternMatch::And< Preds... >
bool match (const MatchContext &, SDValue N)
Public Attributes
Pred P
Detailed Description
template<typename Pred, typename... Preds>
struct llvm::SDPatternMatch::And< Pred, Preds... >
Definition at line 166 of file SDPatternMatch.h.
Constructor & Destructor Documentation
And()
template<typename Pred, typename... Preds> llvm::SDPatternMatch::And< Pred, Preds... >::And (const Pred & p, const Preds &... preds) inline
Definition at line 168 of file SDPatternMatch.h.
References And(), and P.
Referenced by And().
Member Function Documentation
match()
template<typename Pred, typename... Preds> template<typename MatchContext> bool llvm::SDPatternMatch::And< Pred, Preds... >::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 171 of file SDPatternMatch.h.
References llvm::SDPatternMatch::And< Preds >::match(), N, and P.
Member Data Documentation
P
template<typename Pred, typename... Preds> Pred llvm::SDPatternMatch::And< Pred, Preds... >::P
Definition at line 167 of file SDPatternMatch.h.
Referenced by And(), and match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h