LLVM: llvm::orc::SPSCallSerializer< SPSSig > Struct Template Reference
llvm::orc::SPSCallSerializer< SPSSig > Struct Template Reference
SPS serialization for non-void calls.
#include "llvm/ExecutionEngine/Orc/CallSPSViaEPC.h"
Public Member Functions
template<typename RetT>
Expected< RetT > deserialize (shared::WrapperFunctionBuffer ResultBytes)
Detailed Description
template<typename SPSSig>
struct llvm::orc::SPSCallSerializer< SPSSig >
SPS serialization for non-void calls.
Definition at line 48 of file CallSPSViaEPC.h.
Member Function Documentation
deserialize()
template<typename SPSSig> template<typename RetT> Expected< RetT > llvm::orc::SPSCallSerializer< SPSSig >::deserialize (shared::WrapperFunctionBuffer ResultBytes) inline
Definition at line 51 of file CallSPSViaEPC.h.
References llvm::orc::shared::WrapperFunctionBuffer::data(), llvm::inconvertibleErrorCode(), llvm::make_error(), and llvm::orc::shared::WrapperFunctionBuffer::size().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/CallSPSViaEPC.h