LLVM: llvm::GraphTraits< AADepGraph * > Struct Reference
llvm::GraphTraits< AADepGraph * > Struct Reference
Public Types
using nodes_iterator
using NodeRef
Public Types inherited from llvm::GraphTraits< AADepGraphNode * >
using NodeRef = AADepGraphNode *
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using EdgeRef = PointerIntPair<AADepGraphNode *, 1>
using ChildIteratorType
using ChildEdgeIteratorType = AADepGraphNode::DepSetTy::iterator
Static Public Member Functions
static NodeRef getEntryNode (AADepGraph *DG)
static nodes_iterator nodes_begin (AADepGraph *DG)
static nodes_iterator nodes_end (AADepGraph *DG)
Static Public Member Functions inherited from llvm::GraphTraits< AADepGraphNode * >
static NodeRef getEntryNode (AADepGraphNode *DGN)
static NodeRef DepGetVal (const DepTy &DT)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 4146 of file Attributor.cpp.
Member Typedef Documentation
NodeRef
using llvm::GraphTraits< AADepGraph * >::NodeRef
Definition at line 95 of file GraphTraits.h.
nodes_iterator
using llvm::GraphTraits< AADepGraph * >::nodes_iterator
Initial value:
mapped_iterator<AADepGraphNode::DepSetTy::iterator, decltype(&DepGetVal)>
Definition at line 4149 of file Attributor.cpp.
Member Function Documentation
getEntryNode()
NodeRef llvm::GraphTraits< AADepGraph * >::getEntryNode (AADepGraph * DG) inline static
Definition at line 4147 of file Attributor.cpp.
References llvm::AADepGraph::GetEntryNode().
nodes_begin()
nodes_iterator llvm::GraphTraits< AADepGraph * >::nodes_begin (AADepGraph * DG) inline static
Definition at line 4152 of file Attributor.cpp.
References llvm::AADepGraph::begin().
nodes_end()
nodes_iterator llvm::GraphTraits< AADepGraph * >::nodes_end (AADepGraph * DG) inline static
Definition at line 4154 of file Attributor.cpp.
References llvm::AADepGraph::end().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/Attributor.cpp