LLVM: llvm::object::OffloadBundleURI Struct Reference
llvm::object::OffloadBundleURI Struct Reference
#include "llvm/Object/OffloadBundle.h"
Public Member Functions
OffloadBundleURI (StringRef File, int64_t Off, int64_t Size)
StringRef getFileName () const
Static Public Member Functions
static Expected< std::unique_ptr< OffloadBundleURI > > createOffloadBundleURI (StringRef Str, UriTypeT Type)
static Expected< std::unique_ptr< OffloadBundleURI > > createFileURI (StringRef Str)
static Expected< std::unique_ptr< OffloadBundleURI > > createMemoryURI (StringRef Str)
Public Attributes
int64_t Offset = 0
int64_t Size = 0
uint64_t ProcessID = 0
StringRef FileName
UriTypeT URIType
Detailed Description
Definition at line 138 of file OffloadBundle.h.
Constructor & Destructor Documentation
OffloadBundleURI()
llvm::object::OffloadBundleURI::OffloadBundleURI (StringRef File, int64_t Off, int64_t Size) inline
Definition at line 147 of file OffloadBundle.h.
References llvm::object::FILE_URI, FileName, Offset, ProcessID, Size, and URIType.
Referenced by createFileURI().
Member Function Documentation
createFileURI()
Expected< std::unique_ptr< OffloadBundleURI > > llvm::object::OffloadBundleURI::createFileURI (StringRef Str) inline static
Definition at line 166 of file OffloadBundle.h.
References llvm::CallingConv::C, llvm::createStringError(), llvm::StringRef::getAsInteger(), OffloadBundleURI(), llvm::object::parse_failed, and llvm::StringRef::size().
Referenced by createOffloadBundleURI().
createMemoryURI()
Expected< std::unique_ptr< OffloadBundleURI > > llvm::object::OffloadBundleURI::createMemoryURI (StringRef Str) inline static
Definition at line 197 of file OffloadBundle.h.
References llvm::createStringError(), and llvm::object::parse_failed.
Referenced by createOffloadBundleURI().
createOffloadBundleURI()
Expected< std::unique_ptr< OffloadBundleURI > > llvm::object::OffloadBundleURI::createOffloadBundleURI (StringRef Str, UriTypeT Type) inline static
Definition at line 153 of file OffloadBundle.h.
References createFileURI(), createMemoryURI(), llvm::object::FILE_URI, llvm_unreachable, and llvm::object::MEMORY_URI.
Referenced by llvm::object::extractOffloadBundleByURI().
getFileName()
StringRef llvm::object::OffloadBundleURI::getFileName () const inline
Definition at line 203 of file OffloadBundle.h.
References FileName.
Member Data Documentation
FileName
StringRef llvm::object::OffloadBundleURI::FileName
Definition at line 142 of file OffloadBundle.h.
Referenced by llvm::object::extractOffloadBundleByURI(), getFileName(), and OffloadBundleURI().
Offset
int64_t llvm::object::OffloadBundleURI::Offset = 0
Definition at line 139 of file OffloadBundle.h.
Referenced by llvm::object::extractOffloadBundleByURI(), and OffloadBundleURI().
ProcessID
uint64_t llvm::object::OffloadBundleURI::ProcessID = 0
Definition at line 141 of file OffloadBundle.h.
Referenced by OffloadBundleURI().
Size
int64_t llvm::object::OffloadBundleURI::Size = 0
Definition at line 140 of file OffloadBundle.h.
Referenced by llvm::object::extractOffloadBundleByURI(), and OffloadBundleURI().
URIType
UriTypeT llvm::object::OffloadBundleURI::URIType
Definition at line 143 of file OffloadBundle.h.
Referenced by OffloadBundleURI().
The documentation for this struct was generated from the following file:
include/llvm/Object/OffloadBundle.h